### PR TITLE
raises stabilized bluespace extract threshold for activation

### PR DESCRIPTION
**Pull request by Red-byte3D**
## About The Pull Request

raises the  thresholds for the teleportation effect of the crossbreed extract

## Why It's Good For The Game
Raising the thresholds will make it useful and make it work like its supposed to as a get out of jail free card rather then actively teleporting around the station because a rat farted in your general direction

## Changelog
:cl:
balance: Raises the damage threshold and the cooldown of the stabilized bluespace extract
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I think the "rather then actively teleporting around the station because a rat farted in your general direction" bit is supposed to be the main drawback of using this crossbreed (intentionally so).

**Comment by ATH1909** [comment]
Also, this PR would make the stabilized bluespace extract almost useless against anything other than, like, category 2 explosion effects, as you'd have to take more than 50 damage between two ticks of the extract for it to activate (healthcheck updates each time the extract ticks).

**Comment by InsaneRed** [comment]
> I think the "rather then actively teleporting around the station because a rat farted in your general direction" bit is supposed to be the main drawback of using this crossbreed (intentionally so).

i want to change it to where its actually a way to get out of combat and a reward for spending some time to get the slimes you need ideally we could increase the cooldown it has to make it more of a 1 time per every 5-10 minutes to a point where its balanced and you wont get to escape everytime security or an antag finds you

**Comment by ATH1909** [comment]
> > I think the "rather then actively teleporting around the station because a rat farted in your general direction" bit is supposed to be the main drawback of using this crossbreed (intentionally so).
> 
> i want to change it to where its actually a way to get out of combat and a reward for spending some time to get the slimes you need ideally we could increase the cooldown it has to make it more of a 1 time per every 5-10 minutes to a point where its balanced and you wont get to escape everytime security or an antag finds you

if you want to do that, 50 is not the damage threshold that you want to bring this to

**Comment by InsaneRed** [comment]
> > > I think the "rather then actively teleporting around the station because a rat farted in your general direction" bit is supposed to be the main drawback of using this crossbreed (intentionally so).
> > 
> > 
> > i want to change it to where its actually a way to get out of combat and a reward for spending some time to get the slimes you need ideally we could increase the cooldown it has to make it more of a 1 time per every 5-10 minutes to a point where its balanced and you wont get to escape everytime security or an antag finds you
> 
> if you want to do that, >50 is not the health jump threshold that you want to bring this to.

im open to suggestions on a number,i also kind of want it to be a way from having a second chance from rather fatal blows i.e dswords,ninja sword,fireballs,and other stuff that would otherwise kill you and not something like 2 shots from a laser or a harmbaton because imo otherwise it makes people rely on it too much or in a way if you are already being harmbattoned you are probably already stunned / cuffed and your bag was already taken off by the person stunning you

**Comment by moocowswag** [comment]
The extract is already almost as good as a heretic shattering their blade, they both always put you in a non shitmos area.

If you dont want the extract to be able to proc put it in a box in your backpack, if you think something sketch is about to happen you can take it out of the 2+ layers or inventory that youre using to disable it.

Sure it requires you to be alittle bit proactive to a small extent but you already have some degree of control over this item.

**Comment by InsaneRed** [comment]
> The extract is already almost as good as (and situationaly better than) a heretic shattering their blade, they both always put you in a non shitmos area.
> 
> If you dont want the extract to be able to proc put it in a box in your backpack, if you think something sketch is about to happen you can take it out of the 2+ layers of inventory that youre using to disable it.
> 
> Sure it requires you to be alittle bit proactive to a small extent but you have some degree of control over this item.
> 
> But changing it to function even better without player input is just going to make it too good.
> 
> I respect you for trying to buff/make an underused / niche item more reliable so people will play with it but this is an informational issue not a balance issue, most of the player base doesnt know what items like this does or what this item works well with or even any ways to manipulate it to their advantage.

> Not to mention this is one of those late game crossbreeds that requires a high tier adult slime which means a player has to be genuinely interested in wanting to try it out for it to see the light of day.


its part nerf part buff, right now it basically serves as a heretic blade as you said but on a auto scale, can you imagine having to deal with this currently as a security member or an antag ? you get them down to stay still and they teleport to the other side of existence on your first hit, this makes it so that its more punishable to always have it out as some people do since the cooldown is 120s. ideally if you are smart enough you can literally punch yourself a few times the first time you get batonned to teleport yourself to safety which is not something i'd consider balance because you can teleport to safety every 120 seconds. i'll nerf the cooldown as well to 5 minutes and lets see how that works

also about the "nobody does this is the last tier" or "nobody knows about them"
xenobio is mostly rng and you can get them under 20 minutes or not even get one over an hour so making them more balanced and interesting will push more people to do xenobio and push more requests for the item as time passes since ti will be a get out of jail freecad if you mess up once

**Comment by moocowswag** [comment]
Im willing to see how it plays out but i can already think of a few ways to still keep this useful against stun batons/disablers via voice activated self damage.

**Comment by TheBonded** [comment]
The ideal way to use this is to have a stable rainbow with a regen rainbow in it, and the stable bluespace in the internals box in your bag. Stable extracts don't activate while in containers in your bag, so it won't activate. When the stable rainbow activates, and makes you immortal and pacifist for 10 seconds, you quickly alt click your box to open it and put the stable bluespace in your main bag area. It then activates and takes you out. That way, you only take it out of your bag during combat where you are already losing

**Comment by InsaneRed** [comment]
> Im willing to see how it plays out but i can already think of a few ways to still keep this useful against stun batons/disablers via voice activated self damage.
> 
> Cooldown change is interesting though but getting a second chance to fight anything at all tends to be a huge advantage since knowing what youre up against is half the battle.

exactly, thats the point it should give you an advantage because you wasted a fair amnout of time with it and honestly if you spend even more time on setting up a way to damage yourself enough for it to work then that is just stuff working together and i see it as having implemented the feature in a way where people find actual interesting ways to use it and combine it with other said stuff i feel like a cooldown of 5 minutes also helps with giving you less chances

**Comment by InsaneRed** [comment]
> The ideal way to use this is to have a stable rainbow with a regen rainbow in it, and the stable bluespace in the internals box in your bag. Stable extracts don't activate while in containers in your bag, so it won't activate. When the stable rainbow activates, and makes you immortal and pacifist for 10 seconds, you quickly alt click your box to open it and put the stable bluespace in your main bag area. It then activates and takes you out. That way, you only take it out of your bag during combat where you are already losing

a pacifist can still stun people so you have alot of chances to fight back,and this way you can always have it on you in combat and out of combat so you dont have to micromanage also if the other person is using stun batons you cant take stuff out of your bag AND if you have gotten rainbows you probably have greens by that point to roll for a lumi and just using a bluespace major extract is far better then a stabilized bluespace one

**Comment by TheBonded** [comment]
> > The ideal way to use this is to have a stable rainbow with a regen rainbow in it, and the stable bluespace in the internals box in your bag. Stable extracts don't activate while in containers in your bag, so it won't activate. When the stable rainbow activates, and makes you immortal and pacifist for 10 seconds, you quickly alt click your box to open it and put the stable bluespace in your main bag area. It then activates and takes you out. That way, you only take it out of your bag during combat where you are already losing
> 
> a pacifist can still stun people so you have alot of chances to fight back,and this way you can always have it on you in combat and out of combat so you dont have to micromanage also if the other person is using stun batons you cant take stuff out of your bag AND if you have gotten rainbows you probably have greens by that point to roll for a lumi and just using a bluespace major extract is far better then a stabilized bluespace one

okay, but the changes proposed would still be worse than a luminescent slime using major bluespace activation. Also, if you're going full powergame xeno, don't cut off halfway at luminescent slime, become an alien golem for the stamina damage resistance + natural regen + natural armour + spaceproof + nobreathe + ability to easily communicate with your alien golem slaves.

**Comment by moocowswag** [comment]
Why are we comparing an item to a species power, yes stab blue is inferior to lumi bluespace but that doesnt mean it cant be good for other species like hulks or stargazers or alien golems.

**Comment by Mothblocks** [comment]
don't really have any stake in xenobio here but no other maintainer seems to be going for this. going based off that this doesn't seem to be too popular

**Pull request closed without merging**
