### PR TITLE
Post-revs win now ends the shift.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Post revs win now ends the shift.

Does some misc code cleanup of stuff that annoyed me while I was reading code.

Implements revs win ending the shift via a new global used in `/datum/game_mode/proc/check_finished(force_ending)` that is set to TRUE when revs win.

The rev station charter has been removed (for lack of anywhere else good to put it trivially).

The bedsheet has been incorporated into the Post-Revolutionary Fervor station trait. It replaces Captain bedsheets when this station trait rolls.

image

**This is all untested, and I'm not sure if I'm able to test this on local. Please carefully review code changes or consider testmerging over fullmerging.**
## Why It's Good For The Game

Quoting myself from https://tgstation13.org/phpBB/viewtopic.php?f=85&t=33860

> I have no issues with post-revs loss. It's simple, everyone knows where they stand and it works well. Please keep it.
>
> I have issues with post-revs win. Too complex; not intuitive; too many factions; no way to identify which faction a player belongs to ICly; difficult to administrate as a result.
>
>...
>
>Without a good code solution improving post-revs win, I would remove it while retaining current post-revs lose if such an option was available to me as headmin.
>
>If my quibbles with it were dealt with, I would happily vote in favour of re-introducing post-revs win. It's not an ideologicial opposition, just a practical one.

This can really be summarised as: Revs refuses to end even after the revolution wins and the revolution is over.

There's exiled heads, the sec team, mindshielded non-revs, non-revs, ex-revs and ex-headrevs. Generally exiled heads and the sec team buddy up as a single faction. Ex-revs and ex-headrevs are the same.

But mindshielded crew and non-mindshielded crew sit in an awkward limbo, where mindshielded crew aren't anti-revs, and the non-mindshielded non-rev crew aren't rev-sided. Mindshields also do nothing about the ex-antag status.

Since the simplest solution to this problem is ending on post-revs win, that's the one I've gone for.
## Changelog
:cl:
del: Revolution has been reverted back to old behaviour. The round once again ends when the revolution is successful. The round continues as normal if the revolution fails.
add: When the station is rolled in a state of Post-Revolutionary Fervor, the Captain will find their bedsheets replaced with an anti-Nanotrasen variant.
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
I feel bad for the heretics that will never ascend because the revs decide speedrun things.

**Comment by Timberpoes** [comment]
> I feel bad for the heretics that will never ascend because the revs decide speedrun things.

If revs is executing often enough and the crew is losing often enough for this to make a tangible difference to heretic ascention rates, we have other issues.

**Comment by Pickle-Coding** [comment]
Guess I don't have to buy BYOS anymore to own the revs.

**Comment by nukularpower** [comment]
Very much dislike this (and in fact, all forced round ends, such as the cult one.)  Those extreme situations can be chaotic messes;  they can also lead the the most fun roleplay for estranged survivors trying to find a way.   I get that people jsut want to move on their next antag roll but I feel like this is a mistake.

**Comment by RedBaronFlyer** [comment]
> Very much dislike this (and in fact, all forced round ends, such as the cult one.) Those extreme situations can be chaotic messes; they can also lead the the most fun roleplay for estranged survivors trying to find a way. I get that people jsut want to move on their next antag roll but I feel like this is a mistake.

The only thing I'd change about the cult ending is having more time (like, two or three minutes) for the harvesters to go around butchering people and converting them post-Nar'Sie rising. Perhaps some way to end it faster if all the convertible people are off station at that point though.

**Comment by nukularpower** [comment]
> The only thing I'd change about the cult ending is having more time (like, two or three minutes) for the harvesters to go around butchering people and converting them post-Nar'Sie rising. Perhaps some way to end it faster if all the convertible people are off station at that point though.

Either of thsoe would be preferable to me than the practically instant forced end that happens now - more time or have it auto-end once the last noncultist dies or leaves

**Comment by Lufferly** [comment]
Im worried that this might make all other antagonists in the round (traitors, heretics, what-have-you) directly or indirectly team up with the crew against the revolutionaries, as a revolutionary win would mean their antag round ends, and a crew win would mean it keeps going. This is already kinda what happens with cult rounds, but it tends to be fine as cultists are more powerful, and it makes sense that nobody would want the weird eldritch doomsday cult to achieve their ends.

**Comment by jughu** [comment]
i think revs on its own shouldn't mix any other antags in it as its already super chaotic and its a gamemode that relies on trust and other antags break said trust for the loyalist side

**Comment by Byzz2077** [comment]
Revs should be its on gamemode together with its merge as it would just ruin the rounds for other antags

**Comment by DaydreamIQ** [comment]
This was a long time coming. I never understood why revs was the one conversion antag that didn't have an ending scenario

**Comment by kinneb** [comment]
thank you coderpoes, this was a whiiillleee coming

**Comment by scriptis** [comment]
END. THE. ROUND. END. THE. ROUND. END. THE. ROUND!!

thxs u timberpbo

**Comment by Timberpoes** [comment]
This is me speaking as a maintainer that has been opposed to post-revs win not ending the shift for quite some time.

The arguments for and against this will be both circular and infinite, but I think the true issue is Dynamic. Which is to say, we've replaced structured gamemodes for Randy Random.

Pre-dynamic we never had to worry about major game modes ending causing an issue for other minor antag types, because each game mode was a story and generally had an exclusive set of antags.

If your antag was a major one that dominated the shift, it got exclusivity to allow all players to focus purely on the game mode. 

Some survived the transition, like wizard; which in modern tg doesn't really merit ending the shift when it dies.

But round-defining antags like Revs were never designed to run alongside other minor antags. Also Cult. Nukies. Designed to be one-and-done. The crew vs. a single, well-defined threat.

Now we have to worry about these exclusive round-ending rulesets overlapping with other antag types. Rulesets that weren't designed to continue after the antag achieves victory, like Revolutionaries. We've tried to cram a rev-shaped peg into a traitor-shaped hole as a result.

If I had the support, I'd re-introduce antag rulesets controlled by dynamic. Not just the return of traitorling rounds, but a variant of ragin' mages where only magical antags spawn like cult, heretic and wizard, or a syndicate-only ruleset featuring revs or nukies and traitors. And then Randy Random dynamic would be its own ruleset.

That way you can make sure slow-burn antags like Heretic don't roll alongside nukies or revs, but instead find their home in slower-paced "traditional" shifts alongside traitors and lings and stuff. Or part of a themed set where they can be better designed and balanced around the other kind of antags they'll be crammed into a shift with.

**Comment by MrrFiish** [comment]
I think I would like this more if instead of immediately ending it forces a shuttle call, good stories can be made from post revs and I feel like a forced, unrecallable shuttle would be best.

**Comment by scriptis** [comment]
> I think I would like this more if instead of immediately ending it forces a shuttle call, good stories can be made from post revs and I feel like a forced, unrecallable shuttle would be best.

personally I'd find it hilarious if NT just immediately nuked the station like amazon ~~demolishing a warehouse before it can unionize~~ being a great company with no flaws whatsoever

**Comment by the-orange-cow** [comment]
> > I think I would like this more if instead of immediately ending it forces a shuttle call, good stories can be made from post revs and I feel like a forced, unrecallable shuttle would be best.
> 
> personally I'd find it hilarious if NT just immediately nuked the station like amazon ~demolishing a warehouse before it can unionize~ being a great company with no flaws whatsoever

Or, rev victory triggers an automatic death squad.

**Comment by Timberpoes** [comment]
> I think I would like this more if instead of immediately ending it forces a shuttle call, good stories can be made from post revs and I feel like a forced, unrecallable shuttle would be best.

It already auto-calls a (recallable) shuttle if able.

Don't get me wrong, it's not that post-revs-win is unplayable or unworkable as-is. But the number of times it works and everyone "gets" it are overshadowed by the other set of shifts where everything goes to shit administratively and/or players are highly confused at what they can and can't do because the code throws new antag datums around like candy.

When the revolution wins or loses, things should end for everyone except exiles. The game mode is over.

When Cult wins, there isn't a post-cult where non-converted crew and converted crew live in harmony while cultists battle what's left of sec. There's just Nar'sie-brand slaughter and then the shift ends before it outstays its welcome.

When Nukies win, there isn't a post-nukies where the crew's survivors fight on. The nuke goes boom then the shift ends before it outsays its welcome.

Revs win is the same vibe. Antag faction wins, station faction loses and the round is concluded.

**Comment by EricZilla** [comment]
Plus it makes no sense for revs to get on the shuttle after literally fighting for control of the station, maybe on round end have a exile shuttle come instantly to let the nonrevs leave could work

**Comment by Mothblocks** [comment]
not reading any of the comments just here to say i am not happy with a single compromise that is not ending the round

**Review by Mothblocks — CHANGES_REQUESTED** [review]
you left in /obj/item/station_charter/revolution and /obj/item/bedsheet/rev

**Comment by Timberpoes** [comment]
> you left in /obj/item/station_charter/revolution and /obj/item/bedsheet/rev

The rev station charter has been removed (for lack of anywhere else good to put it trivially).

The bedsheet has been incorporated into the Post-Revolutionary Fervor station trait. It replaces Captain bedsheets when this station trait rolls.

image

**Comment by TheVekter** [comment]
Ehhhh, I'm never not going to dislike hard round ends. It was funny back in the day when a wizard ate shit like five minutes in, but it's less enjoyable now that Dynamic is a thing.

I think I prefer the forced shuttle call just so it gives people time to wrap up what they're working on. Hard ending the round feels so inelegant a solution when there's not a major event, like blob winning or nukies blowing up the station.

I also maintain that there's a lot of rev rounds that end with the last command head leaving the station voluntarily but I'm not sure what the numbers are on that.

Whatever, I guess I'm okay with it.

**Comment by nianjiilical** [comment]
im not super opposed to this but i am very curious to see what sort of gameplay dynamic this introduces between revs and solo antags who now have an incentive to actually stop the revolution

will traitors/heretics teaming up with command to stop the revolution become a thing? if so, will it end up becoming a lore thing that the revolutionaries are some kind of fringe sect of the syndicate that the rest disapproves of? theres some neat potential there i think

**Comment by Livrah** [comment]
Can I get antag token for every rev round ended that way

**Comment by TheVekter** [comment]
> Can I get antag token for every rev round ended that way

I know you're joking, but the fastest way to not get an antag token is asking for one.

**Comment by plutori** [comment]
I'm.... not happy about this, per se, but it's fine. As long as it never ends on revs LOSS. Can't count the number of times a revolution has ended and everyone goes "Wait, there was a revolution?".

**Comment by CPTANT** [comment]
Only comment I have is that ~10 seconds between the last headrev being killed and the round actually ending would be nice.

**Comment by MrMelbert** [comment]
~~Should've made this a config option~~

**Comment by Mothblocks** [comment]
I would've tried hard to block it in favor of a removal lol

**Comment by Mothblocks** [comment]
Going to TM this and tell teh admins to force revs rounds because I don't have the time to do it myself

**Comment by BlueMemesauce** [comment]
> The round ending suddenly for solo antags isn't new.
> 
> Cult does it. Nukies do it. Blob does it. Space dragon does it. Malf AI delta does it.
> 
> Your antag round has never been sacred. Blame Dynamic for being a shitshow of blind RNG throwing every antag type together in the same mixer with niether rhyme nor reason behind what it's doing beyond rolling a D20 on what to spend its Disney Dollars on.

These are all big events that don't just happen out of nowhere, most of them kill everyone with a climatic timer. Ending the round makes sense since everyone died and you can't really continue after that. But the round ending after revs win doesn't make sense, since everyone else besides the heads can continue on with the game.  That's why it feels like you're losing your antag round unfairly.

**Comment by TheVekter** [comment]
> Going to TM this and tell teh admins to force revs rounds because I don't have the time to do it myself

okay I'll do it tomorrow


> These are all big events that don't just happen out of nowhere, most of them kill everyone with a climatic timer. Ending the round makes sense since everyone died and you can't really continue after that. But the round ending after revs win doesn't make sense, since everyone else besides the heads can continue on with the game. That's why it feels like you're losing your antag round unfairly. But that's basically what Vekter already said anyway.

I don't really care about it ending antag rounds early. If anything that feels good because it gives other antags incentive to help fight the revs, like they would nuke ops or cult.

I just more think it punishes people who aren't involved in the fight and are actively doing something. It also feels like an inelegant solution to just stop the round immediately. I'm not 100% against it, but I'm a _little_ against it and thus will do my grumpy old man grumble while it gets merged anyway.

**Comment by Mothblocks** [comment]
being told 210090 did not end the round despite a revs win

**Comment by Mothblocks** [comment]
nevermind was not given complete information. revs lost

**Pull request merged**
