### PR TITLE
Removes Swag Outfit

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Removes the swag goku reference outfit.

## Why It's Good For The Game

It provides runway for other such flavor of the month meme references to be added, and it makes me die a little inside every time I remember it exists.

## Changelog
:cl:
del: Removes swag outfit
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
I feel like its humor in the game has outgrown its origin as a meme, we could respite it to not be a meme outfit and be a unique flashy overpriced outfit, but I know I'm not up for the task

**Comment by Loafin34** [comment]
its a tradition for assistants to get the swag shoes when they become rich, please don't remove it.

**Comment by DrAmazing343** [comment]
if it was literally named after goku that'd be one thing but now that the flavor of the month has passed, it's just normal clothing with a little more swagger than usual. this is not currently an issue I've seen any of my team being forced to police so evidently it's not being abused as a meme reference anymore. Rename them to something super grounded, if you'd like, but I see no reason to remove it as the reference isn't super outright anymore and I've seen people just generally using it as swag.

**Comment by Striders13** [comment]
the flavor of the month passed like 2 years ago. It's fine now

**Comment by necromanceranne** [comment]
What's the meme of the moment, I'm out of touch with the youth.

**Comment by carlarctg** [comment]
> What's the meme of the moment, I'm out of touch with the youth.

hawk tuah, parkour civilization. skibidi is gone. only ancient boomers care about that now

**Comment by necromanceranne** [comment]
Why in the fuck is a meme about sloppy toppy hip with the youth. Things are not right.

**Comment by Likteer** [comment]
You are a bad person

**Comment by ArcaneMusic** [comment]
I could defend the shoes, rest of the outfit I could care less about

**Comment by Sadboysuss** [comment]
I didn't even know it's a meme outfit

**Comment by CCC23** [comment]
no more swag outfit :(

**Comment by SomeoneYouProbablyKnow** [comment]
The mene is like a year old and i barely see anyone using the outfit and when they do it's to use it as just a swag outfit not as a direct reference.
Probably only like 3 people would actually be impacted if it got removed, the rest care on principle. But just feels weird to remove it now and not when it got added

**Comment by deathrobotpunch** [comment]
Drip or Die

**Comment by ElGitificador** [comment]
too good to be on tg

**Comment by YuliceTheDruid** [comment]
-1 on principle though I don't super care about the outfit

**Comment by LemonInTheDark** [comment]
> I could defend the shoes, rest of the outfit I could care less about

I am willing to ceed the boots under the proviso that I would really prefer a different sprite

**Comment by Zargoar** [comment]
#SaveSwag

**Comment by LSommers** [comment]
> I am willing to ceed the boots under the proviso that I would really prefer a different sprite
> 
> Edit: Will get around to this likely sometime next week, fucked up my hands some

The whole point is that the shoes and suit are overpriced hypewear that's absolutely not worth it but will be bought by people to flex their money anyways.

SUPREME and Jordans are still a thing outside of the brief "Goku Drip" meme.
The sprites on the shoes are not only fine but actually look pretty neat.
The jacket admittedly looks a bit scuffed but like.
People use it. People like it. Why try to "fix" what's working?

**Comment by KingkumaArt** [comment]
I now find it funnier now that it is no longer the flavor of the month.

**Comment by deathrobotpunch** [comment]
this is so dumb ngl

**Comment by Ghommie** [comment]
The shoes and the jacket are decent garments, even if we don't care about the meme anymore.

**Comment by necromanceranne** [comment]
Ghommie you legend

**Comment by LemonInTheDark** [comment]
you're going in the book of grudges for this one

**Pull request closed without merging**
