### PR TITLE
Titanium Resprite

### PR DESCRIPTION
**Pull request by Onule**
## About The Pull Request

Resprites titanium walls, windows, floors, airlocks and sheet items.
Haven't done a PR in a long while, think I've done everything correctly.

image

## Why It's Good For The Game

It gives titanium turfs and objects a more unique visual, one closer to belonging to a shuttle.

## Changelog
:cl: 
imageadd: Recent changes in the manufacture of titanium sheets introduces a fresh new look! Expect your shuttles to look different. 
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
NOOOOO MY SOUUUUUUUUUL

**Comment by willox** [comment]
There's a visual error in the top row of shuttle_wall.dmi's fwall_closing. It shows up in Dream Maker too.
image

**Comment by Onule** [comment]
> 
> 
> There's a visual error in the top row of shuttle_wall.dmi's fwall_closing. It shows up in Dream Maker too.
> image

Thank you, it should be fixed now!

**Comment by actioninja** [comment]
These sprites are very...crisp? I'm not sure how exactly to explain what I'm thinking but the style is awesome. They look very dirty and used.

**Comment by tmtmtl30** [comment]
a step closer to perspective walls...?

**Comment by FloranOtten** [comment]
The airlock looks really sharp. As in, sharp. Like a knife. There's no smoothness in the doorway, and no mask for the black lines of pixels. Looks meh.

**Comment by Iamgoofball** [comment]
lol its fine good airlocks

**Comment by Pumpkinoe** [comment]
Sexy!

**Comment by Electronics** [comment]
Seems a bit oversharpened to me

**Comment by nicbn** [comment]
looks like the ugly """perspective""" walls from hippie
I'd say either stick to topdown or go full 3/4

**Comment by Onule** [comment]
> 
> 
> looks like the ugly """perspective""" walls from hippie
> I'd say either stick to topdown or go full 3/4

but it is topdown
??
3/4 would need all the other walls and wall mounted objects to also be resprited to 3/4, I ain't doing that

**Comment by optimumtact** [comment]
@Twaticus

**Comment by nicbn** [comment]
>but it is topdown

It doesn't look like it. looks like the darker part is the top of the wall and the lighter part the sides

>3/4 would need all the other walls and wall mounted objects to also be resprited to 3/4,

Not really, we can go one step at a time

**Comment by minichibis** [comment]
These look real nice, I appreciate the shading and style.

Out of curiosity what did the old ones look like?

**Comment by Electronics** [comment]
Having seen them in game now, they really don't seem to fit the rest of the aesthetics of the station...

**Pull request merged**
