### PR TITLE
Securitron assembly fix

### LINKED ISSUE #12265: That securitron seems really unpowered you know?
Securitrons made by robotics and not admin spawned seem unpowered, and do not work, ever.

### PR DESCRIPTION
**Pull request by GunHog**
- Fixes handcrafted securitrons being "unpowered".
- Fixes #12265

### CODE REVIEW

**Comment by Steelpoint** [comment]
This was a annoying issue that I thought was the Robotcist using a wrong part.

You can still remotely turn on the securitron's via a PDA. 

Though I never use new Securitron's due to traitors loving to emag them.

:+1:

**Comment by WJohn** [comment]
Does it also fix the handcrafting requirements? I mentioned that it *only* accepts right cyborg arms when handcrafting, it should accept left arms too.

**Comment by GunHog** [comment]
It does not fix tablecrafting or touch it at all. I do not know how it works, but it *looks* like would have to either duplicate each recipe to take the items, or put borg arms under a /arm/ in their path. Doing the first one would probably be considered unacceptable by maintainers, and the second one would require map edits and potentially touching the surgery system too - well beyond the scope of this PR.

**Comment by WJohn** [comment]
Ah well, I'll put that up in a separate issue then.

**Comment by Jalleo** [comment]
Cyborg arms arent on any maps @gunhog

**Pull request merged**
