### PR TITLE
Fixes a bunch of gun case code

### PR DESCRIPTION
**Pull request by ChangelingRain**
four guns would go outside the case: fixed
you could remove guns from a closed gun case: fixed
guns layered improperly because of a weird loop order: fixed
no forcemove: fixed

### CODE REVIEW

**Comment by coiax** [comment]
What is a guncase

**Comment by ChangelingRain** [comment]
a case for guns

**Comment by coiax** [comment]
but where are they?

**Comment by ChangelingRain** [comment]
nobody has mapped them in

**Comment by AnturK** [comment]
I believe they were only used on that snow planet away.

**Comment by MMMiracles** [comment]
Danno added them at some point if I remember correctly, the snowdin away mission was just the first place to actually map them in.

**Comment by Jordie0608** [comment]
I think these should just be removed instead.

**Comment by duncathan** [comment]
either way this is a worthy fix

**Pull request merged**
