### PR TITLE
Updated MetaStation.v41H.dmm to MetaStation.v41I.dmm

### LINKED ISSUE #11719: Metastation: Corporate Display posters displaying incorrect posters.
This also causes description issues.

### LINKED ISSUE #12298: Disposals outlet is ejecting stuff diagonally causing it to miss the conveyors.
disposal
Metastation cargo disposals conveyor is shown here, but the same thing happens on box in the crusher room where items will eject and land on the conveyor belt below the crusher, bypassing it completely.

### PR DESCRIPTION
**Pull request by Metacide**
**Updated MetaStation.v41H.dmm to MetaStation.v41I.dmm
Updated metastation.dm**
_[Full Resolution Image](https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-11-01%2016-19%20MSv41I%20Full.png)
[Wiki Page Updated](http://tgstation13.org/wiki/index.php/MetaStation)
[Feedback Thread](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=3090)_
- Added lethal shotgun ammo locker and rubber buckshot boxes to the armory
- Added independent area designation to armory (formerly part of brig control)
- Added more flashes to the AI chamber to give AIs more delaying power against borg attacks
- Added camera monitor to AI chamber foyer letting borgs see in to open the blast door
- Added windows to the mailroom conveyor to stop mail falling off it
- Added a few posters to non-command non-security areas of the station
- Added more twists and turns to some of the long, straight paths in maintenance
- Added winter boots to various lockers in the locker room
- Gave roboticists access to the R&D lab
- Moved AI holopads off vents on the MiniSat walkway
- Remove most autorifles - one remains in the warden's locker.
- Removed posters from command/security areas
- Removed random grille spawns blocking areas of maintenance
- Removed duplicate intercom in the teleporter room
- Renamed Secure Lab to Xenobiology again for slime management system
- Fixes https://github.com/tgstation/-tg-station/issues/12298 (MetaStation only)
- Fixes https://github.com/tgstation/-tg-station/issues/11719

Just a minor update with a few tweaks and fixes, really. 

Should be good to go.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Please add two of the new xenobio consoles to your xenobio lab

**Comment by Metacide** [comment]
Oh, they're ready to go? I'll see what I can do.

**Comment by KorPhaeron** [comment]
@Metacide 

Just got merged less than an hour ago, yeah

**Comment by KorPhaeron** [comment]
I've also found having an airless pen is extremely useful for dropping slimes in to be killed, I dunno if you have room for one the way you have xenobio set up though.

**Comment by Metacide** [comment]
Think that's going to be a bit awkward to do as part of this pull request, my fork's outdated and it'll all get complex and such.

Will add them as soon as this goes through, though.

**Comment by KorPhaeron** [comment]
Cool, thanks

**Pull request merged**
