### PR TITLE
New crate sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
imageadd: NT changed all crates because they wanted to.
/:cl:

image

image

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
It's used on *some* ruin

**Comment by SpaceManiac** [comment]
```
_maps\RandomZLevels\caves.dmm
1531:/obj/structure/closet/crate/trashcart,

_maps\RandomZLevels\Academy.dmm
1685:/obj/structure/closet/crate/trashcart,

_maps\shuttles\emergency_clown.dmm
332:/obj/structure/closet/crate/trashcart{
333:    desc = "A heavy, metal trashcart with wheels. Feel free to hop in at any time!"

_maps\RandomRuins\LavaRuins\lavaland_surface_animal_hospital.dmm
122:/obj/structure/closet/crate/trashcart,

_maps\RandomRuins\LavaRuins\lavaland_surface_biodome_winter.dmm
112:/obj/structure/closet/crate/trashcart,

_maps\RandomRuins\SpaceRuins\spacehotel.dmm
4249:/obj/structure/closet/crate/trashcart,

_maps\RandomZLevels\VR\syndicate_trainer.dmm
1449:/obj/structure/closet/crate/trashcart,
1911:/obj/structure/closet/crate/trashcart,
```

**Comment by mattroks101** [comment]
Are these crates or beer coolers?

**Comment by DaxDupont** [comment]
Remind me to make the trash cart play wheel sounds when pulled and make them craftable with a crate. in a month or so

**Comment by Thunder12345** [comment]
Large crate looks kinda squashed, the rest are great though

**Comment by Therapist1** [comment]
Fantastic. The trash cart spawns outside the vet ruin by the way.

**Comment by MrDoomBringer** [comment]
I feel like theres a few details or things that could be done (imo the crates should be a pixel or two higher, not touching the bottom outline of the floortile), but they're an improvement from old crates

**Comment by Iatots** [comment]
Not really a fan of the smooth, plastichy crate faces. I also dislike the trashcart; Solid black wheels, cheap metallic gradient and too small in size.

**Comment by JStheguy** [comment]
Yeah, looking at these, I think more either beer cooler, like @mattroks101 said, or maybe some kind of retro-futuristic ottoman, rather than any sort of practical steel storage/shipping container.

**Comment by barbedwireqtip** [comment]
freezer and wooden crate sprites are alright, others are just kinda... meh.

**Comment by chesse20** [comment]
dont make them a replacement just have it pick randomly which sprite it uses when the crate is generated (new or old sprites)

**Comment by Bawhoppen** [comment]
The edges seem a little *too* rounded off, especially on the wooden crate. Otherwise, the sprite quality seems fair to me (though the anti-aliasing certainly doesn't do them any justice).

**Comment by Dorsisdwarf** [comment]
I absolutely hate all of these, except the crittercrate and large crate. Why would you do this

**Comment by Supermichael777** [comment]
http://theakiba.com/images/2011/09/1283_eye-bleed.jpg

Who put the crates through a rock tumbler? Those corners save money on ship tonnage!

https://en.wikipedia.org/wiki/Packing_problems

**Comment by nicbn** [comment]
I pr'ed rectangle 3/4 crates some time ago and I got told to remake the crates. Now you are saying that it should be kept the way it was. Wow

**Comment by PKPenguin321** [comment]
The idea was that the new sprites would be an improvement

**Comment by Supermichael777** [comment]
@nicbn People were complaining because they want to change art style from retro-futuristic to normal futuristic. They were whining because they sprites were just in a different perspective and didn't fix the ugly. these make the ugly worse.  They look like in-hands and don't look like crates at first glance.

image

Retro-futuristic means base it off things that exist, or at least appeared in fiction at the time.

image

**Pull request closed without merging**
