### PR TITLE
Add inhand icons for changeling tentacle

### PR DESCRIPTION
**Pull request by Destrings2**
Changeling tentacles now have inhand icons. 

:cl: Lombardo2
add: The tentacle changeling mutation now changes the arm appearance when activated.
/:cl:

### CODE REVIEW

**Comment by lombardo2** [comment]
dreamseeker_2017-03-19_18-39-16dreamseeker_2017-03-19_18-39-32dreamseeker_2017-03-19_18-39-48dreamseeker_2017-03-19_18-39-57

**Comment by lombardo2** [comment]
As with the arm blade, it always uses the right hand whether the tentacle is in the left arm or not. Is that a bug?

**Comment by GunHog** [comment]
It looks like an **ANGRY** robot arm!

**Comment by XDTM** [comment]
Arm blades use the correct arm as far as i know, i'll check tentacles whenever i'm able to

**Comment by PKPenguin321** [comment]
West-facing looks wrong, you can still see the right hand and it's coming out of their butt

**Comment by lombardo2** [comment]
@PKPenguin321 Oh you are right. Fixing it

**Comment by ExcessiveUseOfCobblestone** [comment]
butt tentacle is obvious lore

**Comment by WJohn** [comment]
These aren't exactly superb looking, but what's important is getting the actual sprites in at all. These can be improved at a later date.

**Comment by lombardo2** [comment]
@WJohn Yeah, figured as much. Still learning the trade. What would you improve?

**Pull request merged**
