### PR TITLE
Removes the undertale skeleton toy

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by evsey9** [comment]
no

**Comment by Incoming5643** [comment]
If you're going to do this remove all the sound files, that's what always bugged me the most.

**Comment by evsey9** [comment]
reeeeeeeeeeeeeeee
ok fine

**Comment by Iamgoofball** [comment]
@Incoming5643 oh christ there's sound files? fuck me man

**Comment by bgobandit** [comment]
do you wanna have a bad time

**Comment by PKPenguin321** [comment]
I like the skeleton action figure but nix the sounds

**Comment by Iamgoofball** [comment]
@PKPenguin321 the figure exists only to push le so fanny xD undertale memes

**Comment by Militaires** [comment]
ooc approved of thi

**Comment by Cyberboss** [comment]
# TOO FAR!

**Comment by FantasticFwoosh** [comment]
@Militaires its ig OOC vs coderbus at this point in opinion polls.

**Comment by MMMiracles** [comment]
the only reference it makes to underememe is the font, everything else is just generic skeleton puns

did a skeleton kick your dog or something?

**Comment by PKPenguin321** [comment]
Yeah we already had skeletons and associated puns before Undertale, just nix the sounds

**Comment by Iamgoofball** [comment]
you guys forget the original PR

the original version of this was 100% undertale memes

**Comment by PKPenguin321** [comment]
So purge the memes keep the skeletons

**Comment by Iamgoofball** [comment]
if you want skeleton meme puns just become an actual fucking skeleton

**Comment by PKPenguin321** [comment]
???
I'll redo this PR myself properly later

**Comment by coiax** [comment]
There are no Undertale memes, you already removed them all.

**Comment by optimumtact** [comment]
I support this one

**Comment by PKPenguin321** [comment]
This can be closed now

**Comment by optimumtact** [comment]
finish your pr please goof

**Comment by PKPenguin321** [comment]
goof rebase to my branch `genocide-run` i did a proper PR for you but oranges wants you to push it because ????

**Comment by MMMiracles** [comment]
theres a skeleton inside all of us

**Comment by KorPhaeron** [comment]
Just make it adminspawn

**Comment by Bawhoppen** [comment]
Don't like undertake or fandom but by principle you shouldn't remove shot just cause you don't like it

**Comment by ShadowDeath6** [comment]
boned

**Comment by PKPenguin321** [comment]
mine is better because we keep skeletons just purge the undertale correlation

**Comment by PKPenguin321** [comment]
also this PR is still incomplete, didnt remove quite everything

**Comment by Iamgoofball** [comment]
still merging stuff over

**Comment by Jordie0608** [comment]
You still need to remove the `/obj/item/organ/tongue/bone/TongueSpeech(` and `sans` and `papyrus` from `chatter.dm`

**Comment by Jordie0608** [comment]
Also i've just noticed `phomeme` should be spelt `phoneme`, idk if you want to correct that here as well it might be better in a new PR.

**Comment by RemieRichards** [comment]
@Jordie0608 Read it again.

**Comment by Jordie0608** [comment]
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/toys.dm#L469
http://www.dictionary.com/browse/phoneme
What?

**Comment by RemieRichards** [comment]
Specifically the last 4 letters.

**Comment by Jordie0608** [comment]
Yes I am aware, it's still spelt wrong.

**Comment by RemieRichards** [comment]
Its not, because it was intentional by coiax.

**Comment by Jordie0608** [comment]
Well I tried.

**Comment by Cyberboss** [comment]
Genocide ending

**Comment by unrealair** [comment]
Remove all the models from the arcades while you're at it

**Comment by Qbopper** [comment]
dunked on

**Comment by JamieH** [comment]
no fun allowed goofball

**Comment by Iamgoofball** [comment]
@unrealair 
nah, those are original tgstation memes

**Pull request merged**
