### PR TITLE
Removes meta, delta and pubby as unmaintained

### LINKED ISSUE #23706: the only tiki masks you can make are the eyebrow ones

### PR DESCRIPTION
**Pull request by Supermichael777**
Ima dunce

See title. Fixes #23706

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
this is dumb I was thinking of it as like you'd get a random mask style why do our tiki masks have to be magic

**Comment by Supermichael777** [comment]
because clown meme magic
(crayon)

**Comment by PKPenguin321** [comment]
sneaky

**Comment by Supermichael777** [comment]
wait what

**Pull request merged**
