### PR TITLE
Replaces normal revolution with speedy revolution

### PR DESCRIPTION
**Pull request by Buggy123**
Thank you @vuonojenmustaturska this is EXACTLY what we needed.

:cl:
tweak: Given the recent influx of revolutions, Nanotrasen has taken decisive action; any station with a revolution lasting longer than twenty minutes will have its nuke remotely activated!
/:cl:

For anyone unfamiliar, speedy revolution is normal revs except if no one has won by the 20 minute mark the station nuke is activated.

### CODE REVIEW

**Comment by Kraseo** [comment]
thank you

**Comment by Buggy123** [comment]
I probably need to add some sort of message alerting people to this fact, when should I announce it? I can't do it right at the start or you lose the element of surprise.

**Comment by Cyberboss** [comment]
change the config you mongs

**Comment by lordsaladin** [comment]
ai should have the option to ask CENTCOM to activate the nuke for other thing as well(i.e uncontainable kudzu, a massive zombie horde etc.)

**Pull request closed without merging**
