### PR TITLE
Adds green jester shoes for the green jester outfit, and recipes for all four glitters.

### PR DESCRIPTION
**Pull request by Slorbin**
## About The Pull Request

This adds a recipe for all four glitter types so they can actually be craftable. It also adds a set of green jester shoes to the game and to the autodrobe, since for some reason, while we HAVE jester shoes in the game, it's only for the alternative set of yellow jester clothes. These shoes don't waddle but they do jingle a bit.
## Why It's Good For The Game

There are 0 good shoes that go with the green jester outfit since it's lacking an entire third of the costume for some inconceivable reason. Here are some shoes that go with it and jingle.

The glitter recipes aren't 'super' easy to make since they require color powder (not crayon powder!) with confetti requiring colorful reagent but they're not super hard either because it's more of just a gag chemical. Now you can finally 'reliably' fill a smoke machine with confetti powder without having to slave away with strange seeds.
## Changelog
:cl:
add: Added some old-timey jester shoes that jingle, and added these to the autodrobe.
add: Added recipes for all four glitter types: Plasma, N2O, Blue and Confetti.
/:cl:

### CODE REVIEW

**Comment by DeerJesus** [comment]
> You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

anything i try to fix will explode. i will get a delta of -100 if i must

**Comment by Jacquerel** [comment]
> > You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> 
> anything i try to fix will explode. i will get a delta of -100 if i must

If you can't be trusted to fix bugs why would we merge any other new code you added either, when that is _more_ likely to break?

**Comment by DeerJesus** [comment]
im gonna get this shit fixed and revert the weird commits that are from an earlier branch i made (i couldsve sworn i made this all on a new branch from master and it shouldve all be like fine)

**Comment by DeerJesus** [comment]
> > > You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> > 
> > 
> > anything i try to fix will explode. i will get a delta of -100 if i must
> 
> If you can't be trusted to fix bugs why would we merge any other new code you added either, when that is _more_ likely to break?

fie ill try a fix or two

**Comment by Wallemations** [comment]
These should be two separate PRs, they have nothing to do with each other

**Comment by Jacquerel** [comment]
> These should be two separate PRs, they have nothing to do with each other

Correct.
Please reopen this:
- As two separate PRs
- When you actually have some gbp

**Pull request closed without merging**
