### PR TITLE
SlimeHUD

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR ports /vg/ station slimeHUD (credits to them), which adds custom HUD to our slime friends. In practice it means for us only one thing currently - slimes will have their own unique health display indicator, example gif below:

3nVAZrnGwL

I have also added classic red corner overlay which updates and gets progressively worse as slime gets more injured.

Last thing I need to say that the slime HUD can now be very easily be expanded for more elements in the future, if that need arises, for example custom damage zone indicator for slimes.

## Why It's Good For The Game

Better immersion and aesthetics when playing as a slime. You will also be able to estimate your current health without looking at the Status tab.

## Changelog
:cl: Arkatos
add: Added SlimeHUD, which means slimes will have their own custom health display indicator and red corner injury overlay
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
slimes can go into crit?

**Comment by ExcessiveUseOfCobblestone** [comment]
trips notice

**Comment by Arkatos1** [comment]
@ExcessiveUseOfCobblestone I am actually not sure about that, that crit health overlay is used when slime is near death and extremely slowed. Can be changed if that is a problem.

**Comment by nemvar** [comment]
Kinda feels like every singlemob should have this.

**Comment by ExcessiveUseOfCobblestone** [comment]
yeah if they don't go into crit prob shouldn't have a crit indicator.

**Comment by Arkatos1** [comment]
@ExcessiveUseOfCobblestone Eh, its not really that much needed. I took it out and tweaked the thresholds, main post gif updated.

**Pull request merged**
