### PR TITLE
You can attack with ABSTRACT items again.

### LINKED ISSUE #17158: Chainsaw Augment is broken
Put chainsaw on arm.
Try to attack things.
Not be able to attack things and have a useless arm.

### PR DESCRIPTION
**Pull request by phil235**
Fixes #17158

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
> _Fantastic Fwoosh hits this PR with the ethereal philosophical question!!_

Post this PR it probably needs to be defined what abstract objects can hit other things specifically because hitting someone with something that is truly abstract is just silly.

> adjective: abstract
>                 /'abstrakt/
> 
>     1. existing in thought or as an idea but not having a physical or concrete existence.

**Comment by PKPenguin321** [comment]
Abstract flag isn't necessarily truly abstract though, it's useful for a lot of things in code, especially hand replacements

**Comment by coiax** [comment]
As far as I understand, an ABSTRACT item is one that won't show up on examine. For example, a grab is technically an item that you hold, but it's got ABSTRACT.

Also the chaplain's god hand, because it's just his arm. Same with the red hands you gain when bloodcrawling, even if you could be examined in that state, they're ABSTRACT

**Comment by KorPhaeron** [comment]
Just a couple lines, pure fix

**Comment by phil235** [comment]
Yeah, I'm not satisfied with how we use ABSTRACT, it should've only been used for actually abstract things like off hands, grabs, and tk grabs. It should probably be split into two flags, but that's for another PR...

**Comment by KorPhaeron** [comment]
I think it's used for stuff like armblade to stop them ending up on the ground in odd scenarios, but yeah, could stand to be its own flag

**Comment by phil235** [comment]
The thing is it used to be its own flag, only used by truly abstract objects, but little by little people used it for other things for the sake of convenience:  arm blade, nullrod stuff, etc...

**Comment by optimumtact** [comment]
strange

**Pull request merged**
