### PR TITLE
Fixes neat/neet traits.

### PR DESCRIPTION
**Pull request by WJohn**
## About The Pull Request
Fixes neat/neet traits.

## Why It's Good For The Game
They didn't actually do anything. Now they do!

## Changelog
:cl: WJohnston
fix: Neat and NEET traits actually work now.
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
I always thought the mood was invisible. depressing how long this took to be fixed.

**Comment by Qustinnus** [comment]
i am good code

**Comment by Mickyan** [comment]
I guess you could say this is some

dirty code

**Review by SpaceManiac — APPROVED** [review]

**Comment by Shapsy** [comment]
Fitting that NEET code didn't work

**Pull request merged**
