### PR TITLE
Meme PR that attempts to replace all explosion sounds with bikehorns

### PR DESCRIPTION
**Pull request by ma44**
:cl: Something important
tweak: Nanotrasen found out that something exploding near plasma creates.... interesting sounds
/:cl:

Just here memeing, don't mind me

### CODE REVIEW

**Comment by Ergovisavi** [comment]
Should've saved this for april fools.

**Comment by ma44** [comment]
April fools is to far away

Could be able to make this a admin verb that replaces explosions/items/all sounds with a certain sound

**Review by Razharas — CHANGES_REQUESTED** [review]
Hur dur

**Review by ma44 — COMMENTED** [review]
wat

**Pull request closed without merging**
