### PR TITLE
Foam&Smoke buff, some tweaks to sorium/ldm effect, plus some fixes.

### LINKED ISSUE #5965: Slipping on foam when climbing onto a table with foam underneath
If the janitor lets off a cleaning foam grenade, and you're adjacent to a table with foam underneath it, climbing onto the table causes you to slip, as though walking on the foam underneath it.

### LINKED ISSUE #8647: Liquid dark matter and sorium behave strangely, and other goofchem things
Not really a bug, it just works wierdly.

When they activate, they pull/push basically everything, but it's not like when you throw stuff - things just kind of, teleport to their new location and that's it.

I don't know if that's what's actually happening, or it's just a visual thing, but it looks wierd.

Also foam and smoke are pretty fucked up now.

Smoke is really bad now, because it transfers its reagents then becomes immediately useless.
While death smoke was arguable way too strong, that was more of an issue with certain chemicals (namely acid and mutagen that are super deadly specifically because of the 20+ TOUCH effects the smoke would proc just by going anywhere near the smoke, not the reagents itself, as seen by: (almost) any other death smoke, not actually being ggnore insta death.

Foam on the other hand, will just keep applying its full quantity of reagents every single tick, leading to hilarious things like me making grenade that put enough black powder in everyone that touches it to gib them and anything near them.

And speaking of blackpowder, after you mix it (or heat the stabilised version) you get the 'sparks an reacts violenly message, but it doesn't actually explode for a good 3 seconds. This is kind of dumb, for obvious reasons, and whenyou have it in grende form, the grende visually sits there for a bit after activation, before the actual boom happens.

Is this delay intended?

### LINKED ISSUE #9283: Unable to move after blob smoke hit.
Well. I was the CMO and was dragging a cuffed dude to escape. It was then that the smoke from one of those killed blob spores hit me, the one which knocks you back. Afterwards I couldn't move at all, even though I could interact with everything. Thus didn't fade and lasted until the round ended.

Ausops checked me and said I had no reagents in me, and no active status effects.

### LINKED ISSUE #10399: sorium blob can throw you for a loop
An infinite space loop. it throws you fast enough that you can't affect your trajectory
hapened on sybil

### LINKED ISSUE #10473: Nanofrost does not close scrubbers
Nanofrost is only closing up vents, not scrubbers.

### LINKED ISSUE #10488: Fluoroacid nades/smoke is too underpowered.
Please revert #10085 posthaste. It is a unecessary nerf, modifying a mechanic that was already reltively balanced. Acidnade clouds are  relatively easy to navigate out of before your shit getd melted, not to mention dodging a grenade before it blows.  Besides, Acidnades were one of the better counters against mm+el nath wizards/nuke ops, and compared to the effort that they need to prepare (à 6-10 minutes, which is about the same as toxin bombs) they're relatively balanced.

### LINKED ISSUE #10597: Backpack Firefigher Watertank Foam Not Solidifying
Server: Sybil

Revision: 
Server revision compiled on: 2015-07-13
c429522f3b02b5a057b4fdc353a80934679d6c4c 

Problem Description: 
The Metal Foam setting on the Atmospheric watertank backpack no longer works. It spews out foam, but the foam does not become a metal wall able to seal breaches.

What did you expect to happen: 
I know that the metal foam setting has worked in the past.

What happened instead: 
As mentioned, it spews useless foam on the ground instead of metal foam.

Why is this bad/What are the consequences: 
Atmospherics has one less too to use to seal breaches.

Steps to reproduce the problem: 
1: Equip Backpack
2: Set to Metal Foam Setting
3: Use the Nozzle to coat the ground in useless goop instead of a wall.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): 
I had noticed this problem a while ago. I'm sorry for not posting this sooner.

### PR DESCRIPTION
**Pull request by phil235**
- iron foam is now blue steel color just like aluminium foam.
- Fixes metal foam from backpack firefighter watertank.
- Fixes nanofrost not freezing shut vent scrubbers.
- Atmos backpack watertank now starts full of water.
- Change foam layer to Objlayer +0.1 so that it is above foammetalstructure so it doesn't hide the dissolving animation and also above tables.
- Buff foam and smoke: smoke/foam contains four times the amount of reagents that was inserted in them, for balancing.
- Add a little more smoke clouds for tear gas grenade.
- Removed the no longer needed max_lifetime smoke var.
- Reagent_dispensers (watertank) now show how much reagents they have left upon examination.
- Fixed some code formatting in reagent_dispensers.
- Fixes nanofrost temperature lowering effect that wasn't working.
- Adjusted reagent volume in blob spore smoke because of the buff.
- Change to sorium and ldm: effect varies with created volume.
- If you are close to a powerful vortex you are thrown, otherwise you are just moved instead.
- Vortex blobs now only make you step if you are far from it when reaction hits, otherwise it throws you. The vortex blob range gets +1 to compensate. Also the range and effect depends on the reagent volume which means lower effect for blobspore smoke.

Fixes #10473
Fixes #5965 
Fixes #10488 
Fixes #8647 
Fixes #10399
Fixes #9283 (probably, since it's unreproduceable but definitely comes from sorium blob stuff)
Fixes #10597

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Just a suggestion. Make Liquid Dark Matter also throw things at the point of detonation, as well--it's the way it functions on Goon, as well and is always how it was meant to function.

**Comment by phil235** [comment]
@Fox-McCloud will do

**Comment by duncathan** [comment]
>Atmos backpack watertank now starts full of water.

:+1: for that alone

**Comment by Iamgoofball** [comment]
>Buff foam and smoke: smoke/foam contains four times the amount of reagents that was inserted in them, for balancing.
OH MY GOD YES

**Comment by phil235** [comment]
Should be ready to merge now.

**Pull request merged**
