### PR TITLE
Nerfs monkey spam

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
:cl: Naksu
tweak: the amount of simultaneous monkey cube-spawned monkeys has been restricted.
server: the cap is adjustable via the mobs subsystem
/:cl:

@KorPhaeron

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
Attempting to spawn a monkey via a xenobio console doesn't consume the cube, but attempting to do so via extinguishering a pile of cubes does.

**Comment by arsserpentarium** [comment]
Why do you nerf so hard?
Maybe 100-200?

**Comment by Kromgar** [comment]
So wait there's a max of 20 monkeys on the entire station? That's stupid

**Comment by vuonojenmustaturska** [comment]
20 monkeys spawned from cubes, at one time. That's more monkeys than there are cubes at roundstart, and as you recycle/gib the monkeys, their slots are freed.

**Comment by arsserpentarium** [comment]
Also,maybe free monkey slots not with gibbing, but with death?

**Comment by vuonojenmustaturska** [comment]
That'd still allow you to spam infinite monkeys to kill the server with. All the "intended" uses of monkey cubes eventually destroy the monkey, so Destroy() is likely fine for the list removal. 

I'm not really set on 20 being the right number on the limit, i just reckoned it to be the lowest we can go before problems happen.

**Comment by arsserpentarium** [comment]
Dead ones doesn't processing,IIRC. So unlikely you will kill server this way

**Comment by Buggy123** [comment]
Nice to see I ~~died~~ got permabanned for a good reason. Rip 548 monkies on 1 tile.

**Comment by deathride58** [comment]
You should probably make the subsystem automatically remove tracked monkeys over time, otherwise it's gonna be very easy to render xenobio 100% inoperable by simply deconstructing the consoles and shoving 20 monkey cubes into a small, secluded area off-station.

**Comment by Buggy123** [comment]
Personally, I'd just address monkies cubes somehow. Make it so that 1 fire extinguisher blast does not wet 548 cubes at once.

**Comment by kevinz000** [comment]
maybe you should have some common sense buggy

**Comment by kevinz000** [comment]
@vuonojenmustaturska i suggest a system where the amoutn spawned is slowly reduced so someone can't completely disabled monkey cubes but it still helps prevent someone from immediately making thousands.

**Comment by Buggy123** [comment]
I'm telling you, its far better to rate-limit it than to cap it. If you have to wet monkey cubes 1-by-1 with a fire extinguisher the most you'll get is like 3 a second, giving people much more time to deal with the situation.

@kevinz000 

Common what?

**Comment by improvedname** [comment]
Just nerf the monkey recycler tier 4 lol

>1 monkey is 4 cubes
Let me get a conveyor belt and a electrified grille

**Comment by vuonojenmustaturska** [comment]
@improvedname the problem is that every way to acquire monkey cubes is broken

**Comment by improvedname** [comment]
one takes effort and the other is just unbelanced by standards lol turning 1 monkey to 4 then to 16 then to 121

**Comment by CPTANT** [comment]
Wait the monkey recycler has an efficiency of 400%?

Who thought THAT was a good idea......

**Comment by KorPhaeron** [comment]
goof

**Comment by KorPhaeron** [comment]
biggest problem with this is if you make 20 monkeys somewhere and hide them it will break monkey cubes for everyone else and I am not sure how to fix that

**Comment by ChuckTheSheep** [comment]
Borrow from buggy and make each entry only last 10 minutes if not destroyed?

**Comment by Robustin** [comment]
@KorPhaeron 

Who will it break it for? Other monkeyspam griefers?

The only department that actually "uses" monkeycubes is Xenobio and they never actually wet the cubes since you can just shove them in a computer.

**Comment by KorPhaeron** [comment]
@Robustin 

I forgot xenobio doesnt actually use cubes

I guess that makes it easily bypassable as well though

**Comment by CPTANT** [comment]
This is a bad snowflake solution to solve monkey spam

The actual solution is to make monkey cube have sensible effort to produce.

**Comment by Robustin** [comment]
Only bypassible if you want to spam Xenobio - or actually put effort into a re-routed monkey disposal into escape.

I definitely don't see a problem with that.

**Comment by KorPhaeron** [comment]
@robustin

This is about server crashing, not balance, so effort on a players part shouldnt make it possible

**Comment by improvedname** [comment]
just nerf the monkey recycler if you can turn 1 monkey into 300 in a minute its too strong

so heres the charts if i believe.
tier 1 5 monkeys  = 1
tier 2 4 monkeys =1
tier 3 3 monkeys = 1
tier 4 1 monkey = 4

**Comment by KorPhaeron** [comment]
I believe the server crash was done with botany in this case

**Comment by CPTANT** [comment]
Then just nerf that as well.

**Comment by Doppeltongue** [comment]
You can probably get away with greatly increasing the cost of monkey cubes from the biogenerator without stepping on anybody's toes.

**Comment by arsserpentarium** [comment]
I've got better idea! if you are trying to water more than 10 monkey cubes on one tile at once, it spawns not monkey, but abomination.Hostile mob from derelict/wizard pet.

**Comment by ChuckTheSheep** [comment]
Like a "ratking" but with monkeys?

**Comment by Robustin** [comment]
or a gorilla

**Comment by Tlaltecuhtli** [comment]
is the monkey ai the problem or just too many mobs?

**Comment by arsserpentarium** [comment]
Yes, monkey rat king.
Gorilla fine too. But some body horror is better.

**Comment by KorPhaeron** [comment]
@Tlaltecuhtli monkey AI

**Comment by Cyberboss** [comment]
Rate limiting the spawns of monkeys is a much better idea

**Comment by McBawbaggings** [comment]
if it's the AI that is the issue and not the numbers, couldn't it just be made that monkey cubes spawn a subclass of monkeys that are lobotomized and do nothing, thus solving the issue?

**Comment by optimumtact** [comment]
That's a decent approach to fixing it

**Comment by CPTANT** [comment]
Come on, this is a horrible way of fixing this issue.

There are so much better ways, like nerfing monkey cube generation or just not allowing more monkey to spawn on a tile already containing 10 of them.

**Comment by arsserpentarium** [comment]
That's horrible way to fix it.And too low cap.

**Comment by optimumtact** [comment]
I'm sorry but the server's stability has priority over your gameplay

**Comment by CPTANT** [comment]
Fixing this in a non horrible way is not bad for server stability.

**Comment by Cyberboss** [comment]
He means immediate stability you mong

**Pull request merged**
