### PR TITLE
New sprite for construct shell

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
learntoembedkor

Golem shells still use the old one

Sprite is from https://github.com/d3athrow/vgstation13/pull/1711

Was made by @DeityLink

### CODE REVIEW

**Comment by LatD** [comment]
Golems could also use a slightly different sprite for incomplete shell and completed shell if someone wants to modify the sprite or make a new one

**Comment by WJohn** [comment]
👍 from me.

**Comment by ChangelingRain** [comment]
tbh it looks like a construct on its own, that's kind of bad

**Comment by DeityLink** [comment]
>tbh it looks like a construct on its own

That was the intent. To produce this sprite I worked from the merged sprites of an artificer, a wraith, and a juggernaut.

**Pull request merged**
