### PR TITLE
Canned Laughter Improvements

### PR DESCRIPTION
**Pull request by PKPenguin321**
Ports being unable to laugh while muted from https://github.com/HippieStationCode/HippieStation13/pull/2657

Todo:
- [ ] Add an adminspawnable grenade/clustergrenade that fires Laughter gas

:cl: PKPenguin321
bugfix: Laughter no longer makes you laugh if you're muted.
rscadd: Laughter can now be brewed with banana juice and sugar.
/:cl:

### CODE REVIEW

**Comment by Lexorion** [comment]
Can you add a recipe for the chemical? I don't think there is one yet, something like potassium+sugar+mutagen should be fine.

**Comment by PKPenguin321** [comment]
Done, you can brew it with banana juice and sugar. 1u of each yields 10u of Laughter.

**Comment by Jalleo** [comment]
@PKPenguin321 I suggest also a lethal variant of laughing gas admin only. For those traitor clowns to trade TC for or actual DS clowns

**Comment by PKPenguin321** [comment]
okay well the grenade can be for another day

**Pull request merged**
