### PR TITLE
Flight suits are no longer constructable

### PR DESCRIPTION
**Pull request by dannno**
:cl: Dannno
del: Someone deleted the Flight Suit schematics. Whoops!
/:cl:

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=10198

My thoughts are basically outlined here. These just don't serve any worthwhile purpose.

>they're for hostile environments!

the only hostile environments we have are space and lavaland, and we already have things for those that AREN'T hyperspeed stun tools.

### CODE REVIEW

**Comment by Yoshmaster** [comment]
how about just make them only work in ~0 pressure environments?
They're cool, the only problem is all the stupid shit people do with them in the wrong context. Like ACTUALLY moving around in space with them is cool, they're just supposed to be unlimited jetpacks.

**Comment by KorPhaeron** [comment]
Could just replace the stun with a throw

**Comment by Yoshmaster** [comment]
how about:
if you collide with literally any human while wearing your kevsuit, you turn into ash, leaving the other person untouched. FIXED

**Comment by Tofa01** [comment]
Improve don't remove, completely nuking it seems overkill.

**Comment by Yoshmaster** [comment]
Or just make the suit wearer's limbs fly off in an arc if they run into someone!

**Comment by Yoshmaster** [comment]
Make the suits lower sperm count by 100%

**Comment by MMMiracles** [comment]
@Yoshmaster further reason why female characters are for real powergamers

**Comment by Yoshmaster** [comment]
Then it would lower the amount of sperm in their hair I guess

**Comment by dannno** [comment]
This isn't even about the balance of it. It's purely about the design philosophy.

**Comment by Yoshmaster** [comment]
It's honestly a pretty great tool for space exploration, since you'd need to keep refilling a jetpack otherwise. The use is pretty niche when it's not being used to powergame, but it definitely has a use. Just nerf the crazy stuff and it would turn into a niche item that still serves a purpose.

**Comment by Aloraydrel** [comment]
Improve don't remove is the worst argument here

**Comment by Yoshmaster** [comment]
I mean, you should just remove the stupid crap that it has, not like it needs to be upgraded or anything

**Comment by XDTM** [comment]
Who added a stun on hit anyway

**Comment by Yoshmaster** [comment]
pretty sure they started that OP, people just took a while to notice

**Comment by ExcessiveUseOfCobblestone** [comment]
>I mean, you should just remove the stupid crap that it has, not like it needs to be upgraded or anything

Isn't this what the PR is doing?

**Comment by dannno** [comment]
I'd suggest that if you're brainstorming ideas on how to buff/nerf the flight suits, don't do it on this PR. I'm not going to buff or nerf them or change them in any way. This PR is solely for removing them from the fabs.

**Comment by ShadowDeath6** [comment]
you should take immense damage when you crash into someone hard enough to knock them over and physically throw their body in a different direction

**Comment by Bawhoppen** [comment]
you also should take immense damage when you get a bullet in the head but you don't


genetically modified spesshumans

**Comment by dannno** [comment]
This PR is only for removing Flight Suits from the fab, it will not change to accommodate your ideas
Feel free to do them yourselves

**Comment by Bluespace** [comment]
Removal of something fun and endgame for RnD based entirely on someone saying "but i don't like these in the game".
I would meme this response but I worry it might actually get merged.

**Comment by XDTM** [comment]
If the issue is that they're used to stun remove the damn stun

**Comment by Nanotransistor** [comment]
Why not make them work like the skateboards, that only stun the wearer?

**Comment by dannno** [comment]
@XTDM It's not the only issue I have. I don't think they have a place in the game at all.

**Comment by FantasticFwoosh** [comment]
These tears are delicious. Never seen the flight suit used "properly", codersprites and generally annoyance to build contribute to all of this.

**Comment by optimumtact** [comment]
This is already receiving multiple nerfs, I suggest you give it a few weeks for those to embed in and see how it goes.

**Comment by AnturK** [comment]
Reopened on request from creator.

**Comment by kevinz000** [comment]
?

**Comment by kevinz000** [comment]
danno?

**Comment by kevinz000** [comment]
care to explain?

**Comment by XDTM** [comment]
balance change disguised as removal?

**Comment by dannno** [comment]
OOC was talking about not liking flight suits, I also do not like flight suits, and Anturke said he wanted someone to open a removal PR for flight suits. I already had one, so I offered to re-open it.

**Comment by AnturK** [comment]
My secret agenda revealed. Anyway, if @KorPhaeron  or any other maintainer feels this is freeze violation feel free to close.

**Comment by kevinz000** [comment]
what's the beef with them this time?

**Comment by dannno** [comment]
I still just don't think they have a place in the game, Kevin. I think they're a hamfisted prize that only accentuates the parts of research and the game as a whole that I don't like.

**Comment by KorPhaeron** [comment]
Freeze

**Pull request closed without merging**
