### PR TITLE
Removes emergency meetings

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Removes emergency meetings. Uh, let me know if I missed anything

## Why It's Good For The Game

We gotta come up with NEW ways to ruin the round each year, this one's so old and busted

## Changelog
:cl:
del: Votes out some sussy emergency meeting code
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
and before you ask

**Comment by saprasam** [comment]
AMONG US

**Comment by private-tristan** [comment]
bad change 👎

**Comment by tralezab** [comment]
IDED

**Comment by wawabenford** [comment]
litterly 1983

**Comment by Iamgoofball** [comment]
:-1:

**Comment by optimumtact** [comment]
among us

**Comment by tralezab** [comment]
guys the votes on the pr are indeed voting it out

**Comment by tralezab** [comment]
its about to get ejected

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Under no circumstances will this get merged because it goes against the entire point of April Fools.

April Fools is not a time for shenanigans/horseplay/clowning/fooling/tomfoolery/buffoonery/pranks/practical jokes/antics/hijinks. April Fools is a time for miserable coders to enact their hatred onto the playerbase, by having an opportunity to force innocent key holders into test merging their PR to remove all floor tiles from the station. Emergency meetings exist to encapsulate this bitterness and force it upon the admins. The problem with April Fools is that people often take things too far. What starts as harmless fun quickly turns into a nightmare for those on the receiving end of the so-called "pranks." It's not just miserable coders who get in on the act either - anyone with a mean streak can use this day as an excuse to be cruel and hurtful. And let's not forget about the sheer stupidity of some of the jokes that people come up with. Club Penguin? Really? What kind of moron thinks that's funny? It's a wonder that anyone even bothers with this stupid holiday anymore.

**Comment by tralezab** [comment]
I’m sorry but I don’t agree with the decision to close this pull request. I think the changes I proposed are valuable and necessary for the project. I have addressed all the feedback and resolved all the conflicts. I don’t see any reason why this pull request should not be merged. That’s why I’m deciding to reopen it and request a review from another maintainer. Please reconsider your decision and let me know if you have any questions or concerns. Thank you.

**Comment by tralezab** [comment]
Мне жаль, но я не согласен с решением закрыть этот запрос на вытягивание. Я думаю, что изменения, которые я предложил, ценные и необходимые для проекта. Я учел все отзывы и разрешил все конфликты. Я не вижу никаких причин, по которым этот запрос на вытягивание не должен быть объединен. Вот почему я решил открыть его снова и запросить обзор от другого сопровождающего. Пожалуйста, пересмотрите свое решение и дайте мне знать, если у вас есть какие-либо вопросы или опасения. Спасибо.

**Comment by Mothblocks** [comment]
# WHAT PART OF UNDER NO CIRCUMSTANCES DO YOU NOT UNDERSTAND

**Comment by tralezab** [comment]
## REREAD MY LAST POST

**Comment by Capsandi** [comment]
posting in a legendary thread
| l| || |_

**Comment by MrDoomBringer** [comment]
image

**Comment by MrDoomBringer** [comment]
I cant believe trazelb hates my code :(

**Comment by Sealed101** [comment]
arm who wrote your Russian speech

**Pull request merged**
