### PR TITLE
Allows Universal Scanner Equip on Cargo Coats/Jackets

### PR DESCRIPTION
**Pull request by Literallynotpickles**
## About The Pull Request
title
## Why It's Good For The Game
its already a pocket-sized item, usually pretty important for cargonians to carry around - easy spot to not forget where it is compared to randomly shoving it into bag/box/pockets!

also just nice to have a little more options on what you can carry with departmental coats
## Changelog

:cl: SuicidalPickles
qol: Cargo Coats/Jackets can now equip universal scanners on their suit-slots.
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
Crazy that it cant hold an emergency oxygen tank, but this solves that issue

**Comment by DATA-xPUNGED** [comment]
Does this add them to the cargo winter jacket too?

**Comment by Literallynotpickles** [comment]
> Does this add them to the cargo winter jacket too?

adjusting, forgot these existed!

**Comment by Literallynotpickles** [comment]
> Crazy that it cant hold an emergency oxygen tank, but this solves that issue

tbf theres a _lot_ of suits/coats/jackets that probably(?) should be able to hold those, gets out of scope tho and dont wanna bandaid fix only _one_ of them

**Pull request merged**
