### PR TITLE
Restores the old sound of windowed doors

### PR DESCRIPTION
**Pull request by Incoming5643**
Makes the vanilla white windowed doors (the fulltile ones) sound like other doors again as opposed to sounding like windoors (the tile border ones).

I'll take "Things everyone wanted to do but inexplicably didn't" for 400, Alex.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I kinda like that they have the windoor sound, personally.

**Comment by PKPenguin321** [comment]
fuck you fox you are wrong

:+1: for this PR

**Comment by WJohn** [comment]
Thank you.

**Comment by xxalpha** [comment]
This bothers me also, they are airlocks just like the others and have no reason to sound different. :+1:

**Comment by lzimann** [comment]
I kinda liked tbh

**Comment by Ultimate-Chimera** [comment]
But why? :(

**Comment by PKPenguin321** [comment]
chimerafags pls go

**Comment by Ultimate-Chimera** [comment]
;-;

**Pull request merged**
