### PR TITLE
Removes excess ID boxes from the HoP's office and adds silver IDs to their locker.

### PR DESCRIPTION
**Pull request by DATA-xPUNGED**
## About The Pull Request

Every ID, silver ID, and PDA box has been removed from the maps. You can now only find ID boxes on the HoP's locker and PDAs must be bought from the tech vendor. Said locker also had two instances of ID boxes, so i've swapped one of them for the silver ID box
## Why It's Good For The Game

tram had, in total, 5 ID boxes. That's *35 IDs in total.* No one is ever gonna lose that much, and having 7 is more than enough. If a situation happens where you somehow need more, you can still buy it on the tech vendor AND on cargo. I realized how many boxes the HoP had on the other PR
## Changelog
:cl:
del: Removed excess ID boxes on HoP's office
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
whoops sorry HOP i may have lost 33 IDs so far but this 34th one should be the charm

**Comment by EricZilla** [comment]
Honestly thank God for adding silver to the locker, can't remember which map doesn't have ANY but I know there is one

**Comment by newfren** [comment]
does this leave the box of silver ids in the cap's locker or no?

**Comment by DATA-xPUNGED** [comment]
> does this leave the box of silver ids in the cap's locker or no?

It does, and i should probably get rid of that too tbh

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
