### PR TITLE
[Ready]Legion Cores now deal slight cellular damage

### PR DESCRIPTION
**Pull request by Djiq**
## About The Pull Request

I'm working on a big changes to lavaland that will make it harder to aquire gamer loot, basically I;m going to add much more harder enemies and make the current loot a lot harder to aquire. This was going to be in the megaPR but i decided it will be better if i make it it's own thing.

Legion cores now deal 5 clone damage.

## Why It's Good For The Game

Forces miners that overuse legion cores to go to medbay once in a while

## Changelog
:cl:
balance: Legion cores now deal 5 clone loss.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
lol

**Comment by Fikou** [comment]
> This was going to be in the megaPR but i decided it will be better if i make it it's own thing.

why

**Comment by ATH1909** [comment]
okay but why

legion cores decay unless a miner buys a specific one-use item to stabilize them, and they're not aheals anymore (unless you get one implanted, IIRC, but even that might have been nerfed). what's your deal with 'em?

side note: sitting unconscious in a cryo tube in medbay because you were using the healing items that you're expected to use as a miner sounds about as thrilling and engaging as sitting out an ash storm in a bluespace pod.

**Comment by XDTM** [comment]
>basically I;m going to add much more harder enemies and make the current loot a lot harder to aquire.

That's not the solution, miners that are good now will just git more gud and we'll be back at the start, only even less players will actually have the option to play mining due to bad ping or poor reflexes.

If you want to gate miner loot, gate them with something other than raw mechanical difficulty, ideally something that ties closely to round time and the rest of the station. For example, vaults that require RnD-researched keys or large amounts of money to open, or monsters that cannot (_literally!_) be defeated without some special equipment/preparations, like maybe having to build a disruptor field w/ engineering to remove invulnerability from a boss and having to lure the boss into it before the fight.

**Comment by ATH1909** [comment]
```
/datum/status_effect/regenerative_core/on_apply()
	ADD_TRAIT(owner, TRAIT_IGNOREDAMAGESLOWDOWN, id)
	owner.adjustBruteLoss(-25)
	owner.adjustFireLoss(-25)
	owner.remove_CC()
	owner.bodytemperature = owner.get_body_temp_normal()
	return TRUE
```

🤔

**Comment by ATH1909** [comment]
> If you want to gate miner loot, gate them with something other than raw mechanical difficulty, ideally something that ties closely to round time and the rest of the station. For example, vaults that require RnD-researched keys or large amounts of money to open, or monsters that cannot (_literally!_) be defeated without some special equipment/preparations, like maybe having to build a disruptor field w/ engineering to remove invulnerability from a boss and having to lure the boss into it before the fight.

Won't some of that stuff fuck over lavaland ghost roles?

**Comment by EdgeLordExe** [comment]
> Also, isn't there a mech-based lavaland rework planned anyway?

yeah thats what i'm doing

**Comment by XDTM** [comment]
> side note: sitting unconscious in a cryo tube in medbay because you were using the healing items that you're expected to use as a miner sounds about as thrilling and engaging as sitting out an ash storm in a bluespace pod.

You could make the same argument to say that players shouldn't be able to die. It's unfun, right?

This pr makes sense to me because as a result you'd have to make a choice between instant healing now and visiting medbay later, or using conventional healing and having to go back to the station only for more supplies, instead of having only one choice that trumps the others. 

Though, since they'd end up more equal in power, i'd also make legion cores not decay anymore on top of this change.

**Comment by TheMidnightRose** [comment]
Legion cores dont even heal that much as is based against what lavaland can currently do. About two goliath melee strikes equals one legion core depending on armour and amount of plates in said armour. Watchers dont even do damage currently. Legions, if you fuck up fighting them, can cause MORE damage than their core heals. I am perfectly happy with the removal of self antag gear from mining, I am perfectly fine with the mech stuff being moved around. 

I am not okay with more permadeath being added to mining. Because thats what this will do in the end. Cause miners to take permenant damage they cant heal without going up to the station. Something they might not always be able to do. This effects icebox too with multiple players falling down chasms.

Why not work on removing the gamer items that dont help their job that are within the boss loot and replacing them with other items that would. Or code new ones that would to replace the boss gamer items.

**Comment by Ryll-Ryll** [comment]
Miss me with all this balance talk, cloneloss ought to be phased out now that cloning is dead

**Comment by XDTM** [comment]
Design-wise we _want_ miners to have to come up to the station every now and then, or they might as well be a ghost-role in terms of direct station interaction.


Cloneloss used to be the only "permanent" damage we have aside from traumas, wounds and organ damage, but now that we have them it does make sense to use those instead.

**Comment by ishitbyabullet** [comment]
> 
> 
> Miss me with all this balance talk, cloneloss ought to be phased out now that cloning is dead

That's just stupid however the point of cloneloss damage isn't really about cloning anymore. It's just cellular damage aka requires more advanced medicine to heal. Think of it as radiation or something, especially since the only ways to dish it out yourself is with the alien pistol, the decloner gun, and maybe one other thing.

**Comment by Pugie** [comment]
This gradual change that only serves to inconvenience stuff is really rubbish. Look at read only rd consoles shift start - supposedly part of some grand design but it's only served to be needlessly tedious for months.

**Comment by Ryll-Ryll** [comment]
> especially since the only ways to dish it out yourself is with the alien pistol, the decloner gun, and maybe one other thing.

Sounds like a good reason to get rid of it

**Comment by ishitbyabullet** [comment]
> 
> 
> > especially since the only ways to dish it out yourself is with the alien pistol, the decloner gun, and maybe one other thing.
> 
> Sounds like a good reason to get rid of it

And replace it with what? Radiation? That would be a pretty huge buff as well as debuff.

**Comment by Pugie** [comment]
> > > especially since the only ways to dish it out yourself is with the alien pistol, the decloner gun, and maybe one other thing.
> > 
> > 
> > Sounds like a good reason to get rid of it
> 
> And replace it with what? Radiation? That would be a pretty huge buff as well as debuff. Just imagine how annoying it'd be to have to worry about radiation for SELF-DEFENSE as an abductor. You'd have to buff them again then.

Agent stun baton still hardstuns I'm pretty sure and knocks people out.

**Comment by ishitbyabullet** [comment]
> Agent stun baton still hardstuns I'm pretty sure and knocks people out.

And when that isn't enough?

Either way, this "we need to remove cloning damage becuz cloning bad" argument is off-topic here. Should probably stop now.

**Comment by Investigator77** [comment]
"Continuously make mining harder" Should stop being a mindset, no matter how much you nerf them to the ground you'll still have players getting the funny epic gamer loot. There's no escaping it.

**Comment by IndieanaJones** [comment]
If you're working on forcing players to use mechs on Lavaland for another PR, what's the point in even having this PR in the first place?  Making the mining experience slightly more miserable until you make another PR to actually fix the gameplay?  At this point, why even bother fight megafauna as a human when you can send in a cyborg to do it for you, since they don't have to deal with any of the stupid penalties in regards to healing that have been tacked on?  If you want to nerf powergamers, why keep pushing PRs that nerf all miners instead of nerfs to the loot that these "powergamers" supposively abuse constantly?

**Comment by EdgeLordExe** [comment]
Do you even consider how useful is instant 35/35 damage heal is? That is a lot of damage that is instantly healed, this item is a thing from trek-chems era where that kind of shit was ok. It no longer is ok to have instant damage healing for no cost at all.

**Comment by trexter555** [comment]
remember that by punishing mining via nerfs you are indirectly punishing the rest of the station by making it harder to not die as a miner, meaning no mats get to the station

**Comment by TheMidnightRose** [comment]
Idea: Instead of this. Make it so that the cores dont work station Zlevel. Make Legions stronger with more health or more skull spawn rate. Maybe cause tendrils to spawn the big boy legions if you kill too many in a row at one tendril. 

Ways to nerf it that doesnt increase the rate the miners die from their healing tools.

**Comment by ATH1909** [comment]
> Do you even consider how useful is instant 35/35 damage heal is? That is a lot of damage that is instantly healed, this item is a thing from trek-chems era where that kind of shit was ok. It no longer is ok to have instant damage healing for no cost at all.

*25/25

**Comment by TerraGS** [comment]
Speaking without any idea of how feasible this would be, an idea would be to make the healing from cores temporary as in you get the healing along with a timer of say 2 minutes and when it runs out the damage/wounds get reapplied. You'd then have miners that have a chance to run back to the station and hopefully medbay before suddenly collapsing in a bloody heap to be stitched back together.

**Comment by GuyonBroadway** [comment]
Hey remember when most of minings cool toys were just in the mining vendor? And how if you actually did your job as a miner you were rewarded with fun stuff? 

Wouldn't it be nice if we incentivized the bringing back and processing of ore rather than the harvesting of ore being an incidental by product of "unga bunga me click on skull man to get gamer gear"

**Comment by TerraGS** [comment]
> 
> 
> Hey remember when most of minings cool toys were just in the mining vendor? And how if you actually did your job as a miner you were rewarded with fun stuff?
> 
> Wouldn't it be nice if we incentivized the bringing back and processing of ore rather than the harvesting of ore being an incidental by product of "unga bunga me click on skull man to get gamer gear"

New mining balance idea: Make necropolis chests locked and only opened by single use keys distributed by the mining vendor.

**Comment by IndieanaJones** [comment]
> Do you even consider how useful is instant 35/35 damage heal is? That is a lot of damage that is instantly healed, this item is a thing from trek-chems era where that kind of shit was ok. It no longer is ok to have instant damage healing for no cost at all.

First off, it's 25. Second off, yeah, it is pretty useful, especially since everything on lavaland can fuck you up pretty easily.  Finally, this response doesn't actually answer any of my previous questions:

> If the future of Lavaland is mech-reliant, why make this PR?
> Why continuously nerf human healing to the point where the cyborg variant of the job is becoming a straight upgrade?
> Why not focus nerfs onto lavaland items that only powergamers see use for instead of the tools that all miners use?

And if your answer is, "use on station bad :(", then why not just prevent their use on board the station?  Not to even mention that cores expire after a period of time, requiring a 400 credit item to keep them from expiring, why not just decrease the time it takes to make them go inert?

**Comment by Doosteroni** [comment]
Why doth edgelordexe loath mining?

**Comment by FloranOtten** [comment]
What the fuck is the point of this PR? Seriously. What are you hoping to achieve here?

Make miners go to the station? Nah. This just means miners will not use them at all. The only time it'll be used will be in a dire emergency, and the debuff won't be a "gotta go interact with medical", it'll be a "god fucking damnit I've gotta go all the way to medical?". It's quite a distance, and for what? Interaction that's literally just "hey, put me in this tube"?

Is this a step on a long path to utterly kneecap mining heals to incentivize mechs? If so, include this in that PR. We don't need this right now, and if your later PR fails this'll forever be in the game as a random middle finger to new players who didn't know better. 

25/25 heal isn't that good. It just isn't. If you've taken 25 damage, you can just walk over to the nearest shelter pod and eat the donkpockets. If it is more, just use a medipen
 It's rare for them to heal their full potential anyway. When's the last time you had both damage types?

What the fuck is this "on-station" argument? Make them unusable on the station then! Nerf them in high pressure! Hell, you can't even use these on station because they decay and for a lesser price you can just get a medipen.

**Comment by TheMidnightRose** [comment]
Why not put this PR on pause till if after your Lavaland Reforged PR is merged to see how the new lavaland works with current legion cores. If it is still too powerful we can likely push the heal down to 15/15 from 25/25. Adding the clone damage with your Lavaland rework is going to make it absolutely hell getting back to the station.

**Comment by Doosteroni** [comment]
If this gets merged with THAT like/dislike ratio I AM GONNA HAVE AN ANEURYSM AND THROTTLE SOMEONE SERIOUSLY!

**Comment by ExcessiveUseOfCobblestone** [comment]
I really miss the days when miner players would come and complain if you made it easier.

**Comment by IndieanaJones** [comment]
> I really miss the days when miner players would come and complain if you made it easier.

I play miner borg so none of this really affects me, but so many baby miners come along and die for a myriad of reasons.  I'm not really keen on adding another reason to the ever-growing list.

**Comment by ExcessiveUseOfCobblestone** [comment]
is there a doc for this

**Comment by Whoneedspacee** [comment]
> I really miss the days when miner players would come and complain if you made it easier.

easier as in difficulty, not like this, this is an application of permanent damage for a common healing item.

id rather you reduce pka damage than do this to be honest.

**Comment by Rohesie** [comment]
The intent behind this is fine, nerfing mining. The method is not ideal, though, cloneloss is not really something we want to expand upon, at least not without a proper design.
Feel free to make changes and bring up a new concept to re-open this, ideally one that you've discussed previously with a maintainer. Or open a new PR once you've done it.

**Pull request closed without merging**
