### PR TITLE
Baptismal holy water fonts in Box and Meta chapels

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

Wanted to flesh out chaplain with some religious miscellania I thought was missing. This is the first thing. 

## Why It's Good For The Game

Gives the chaplain another gameplay goal to aid their roleplay, baptising people to protect their souls from devils. Can be used by anyone as an environmental attack. Can be experimented with as a reagent holder you can dunk people in.

- [ ] Needs better sprites with reagent overlays
- [ ] Need to test emptying it
- [x] Need to add a temporary moodlet for blessing oneself
- [x] Need to make chaplain baptism harmless (no oxyloss) and require holy water (no harmful reagents)
- [x] Need to make swirlie baptism take the same time as toilet swirlies (3 seconds)
- [x] Need to make it harder for the chaplain to accidentally beat people's heads on the font (add a harm intent check and pacifism check)
- [ ] Need to make sure the reagent volumes on the touch interactions and how much the fonts hold makes sense because I never play chemistry and don't know if it's too much or too little
- ~~I'd like to be able to scoop solution out with an empty reagent container but it didn't work properly in testing (took the reagents out but added them back in again) and I couldn't be bothered looking into fixing it~~

## Changelog
:cl: cacogen
add: Adds holy water fonts to entrances of Box and MetaStation chapels. These are like a cross between toilets and mop buckets in functionality. These can be used to bless yourself or to try to baptise people with whatever reagents are inside.
add: Adds baptised trait, given by being baptised by a chaplain. Gives a permanent mood boost of 2, and prevents you from signing devil contracts. The chaplain can see who is baptised and who isn't by examining them.
/:cl:

### CODE REVIEW

**Review by actioninja — CHANGES_REQUESTED** [review]
just make it a subtype of toilets

**Comment by SkeletalElite** [comment]
Does it have any interaction with the spiritual quirk? It should.

**Comment by Dorsisdwarf** [comment]
Is this a WIP PR? I thought we didnt do those any more

**Comment by actioninja** [comment]
Actually yeah, good point, this is a WIP PR.

Feel free to open this again when at the very least it would be testable on a live server.

**Pull request closed without merging**
