### PR TITLE
Plastic golems

### PR DESCRIPTION
**Pull request by coiax**
image

:cl: coiax
add: It is now possible to make plastic golems, who are made of a material
flexible enough to crawl through vents (while not carrying equipment). They also can pass through plastic flaps.
/:cl:

Pretty simple. Plastic golems (remember, we actually have plastic as a
material) can ventcrawl, which also gives them the ability to go through
plastic flaps. They are otherwise the same as iron golems.

More uses of plastic are good, and this seems appropriate for a flexible
material to make flexible golems. Very much a material only found on the
station, and thus having an ability that really only makes sense on the
station.

@XDTM

### CODE REVIEW

**Comment by WJohn** [comment]
Plastic is a material? What?

**Comment by XDTM** [comment]
ventcrawling with equipment is very very strong

just basic ventcrawling should be fine, and even then i think it should get lower armor

**Comment by Militaires** [comment]
make them look like hotglue dolls

**Comment by coiax** [comment]
@XDTM lower armour is fine by me.

the only ventcrawlers that can carry items that I'm currently aware of are drones. I can see in theory that ventcrawling with a backpack is strong, but is it that strong?

**Comment by Militaires** [comment]
finally, a human fleshlight in the code.

**Comment by XDTM** [comment]
It's "carry the armory off for free" strong. I'm pretty sure monkeys used to fully ventcrawl until it got abused, and golems are full humans.

**Comment by coiax** [comment]
@XDTM this isn't a defence, but did you know that https://github.com/tgstation/tgstation/blob/9feab253b8c4c47283fe16bbd1df11b9d8c0ddb5/code/game/gamemodes/miniantags/abduction/gland.dm#L114 grants ALWAYS ventcrawling? Honk honk.

**Comment by Repukan** [comment]
You mean a RNG organ given with a side of anal probing gives the owners weird powers?!?!?!?!?

**Comment by Cyberboss** [comment]
Should probably be immune to electricity if it isn't already

**Comment by coiax** [comment]
The base golem is immune to electricity, so they all are.

**Comment by KorPhaeron** [comment]
Probably gonna be op

**Pull request merged**
