### PR TITLE
[s]You can no longer take non-integer amounts of sheets from a stack.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/tgstation/issues/23427.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
is round floor or ceiling in byond I always forget

**Comment by Supermichael777** [comment]
this has been in stacks forever
how long have stacks been around?

**Comment by XDTM** [comment]
Actually stack splitting is fairly recent, before that you had to take single sheets with the other hand.

**Review by Cyberboss — APPROVED** [review]
How many other things have this problem?

**Comment by optimumtact** [comment]
@ExcessiveUseOfCobblestone round works either way depending on which side of .5 it is on, there are specific floor and ceiling procs in the code we have implemented

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact nice, are they just floor(math) and ceiling(math)?

**Comment by optimumtact** [comment]
floor(value, multiple)
ceiling(value, multiple)

multiple is the nearest multiple to floor or ceiling to

**Pull request merged**
