### PR TITLE
Excessively improves various sprites.

### PR DESCRIPTION
**Pull request by WJohn**
all aboard the sprite train!

Candles.

ID Cards.

Also touched up the color palette a tad. Reduced contrast burn from certain colors and improved some ramps. Folders and a few other sprites should look a bit better.

:cl: WJohnston
imageadd: Recolored and resprited candles and ID cards. Folders should have improved color contrast.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
3rd candle state kinda looks like a penis and I'm sorry for pointing that out

**Comment by WJohn** [comment]
doesnt everything

**Comment by ChangelingRain** [comment]
Needs pictures of the other adjustments done.

**Comment by WJohn** [comment]
They're super minor, like it's literally just the red folder that has slightly better contrast changed with it. It won't really be noticeable on anything else.

**Comment by ChangelingRain** [comment]
You also touched `aicards.dmi`, `ammo.dmi`, and `bloodpacks.dmi`. Please provide before and after pictures.

**Comment by TechnoAlchemisto** [comment]
i feel personally feel attacked by these ID card changes

**Comment by WJohn** [comment]
Like I said, literally tiny changes. Without turning these into gifs (and .dmis being a ridiculously poor format to do that with), you would hardly see anything. The changes to the color palette is described here.
https://tgstation13.org/phpBB/viewtopic.php?f=11&t=7444#p217178

Most of the changes are to a single dark red or dark blue color, and again that's to improve contrast very slightly. For all intents and purposes you won't see anything different.

**Comment by ChangelingRain** [comment]
At least do side-by-side pics jeez

**Comment by WJohn** [comment]
The red folder is the ONLY sprite here than might be noticeably different if you have a very keen eye. The blue one has a slightly brighter outline if you've got some seriously weirdo eyes. Anything else I touched, even I don't know what got changed. I ran this stuff through gimp to update the color palettes on things I resprited.

**Comment by nullbear** [comment]
HEY while you're here do colored candles!
1 for each crayon color + white/recolourable.

**Comment by WJohn** [comment]
That'd require code changes, I'm purely respriting or recoloring what's already there. If anyone wants to offer to do colored candles, hit me up on IRC and we'll work something out.

**Comment by Iamgoofball** [comment]
@WJohn i want to learn how to do the color palette thing with gimp how do I do that

**Comment by Jordie0608** [comment]
@Iamgoofball https://docs.gimp.org/en/gimp-image-convert-indexed.html

**Comment by Tacolizard** [comment]
what's the ID that looks like a piece of paper?

**Comment by WJohn** [comment]
Fingerprint ID. It's quite literally a piece of paper with ink.

**Comment by nullbear** [comment]
I'm fine with coding them, like it's not much trouble (aside from fancy storage ugh i hate fancy storage) but having the sprites available would b nice.

**Comment by Tacolizard** [comment]
@WJohn Are they implemented in-game? I've never seen one.

**Comment by WJohn** [comment]
Fairly certain they are. They're basically never used though.

**Comment by Cheridan** [comment]
The cards look off

**Comment by WJohn** [comment]
What do you want me to change about them? I fixed some issues with them, like them having a couple of random sharp edges on the top left and bottom right corners, being offset to the right for no real reason, having pillow shading etc. I wanted to keep them mostly the same since I KNOW I'll be fighting the whole bloody community over it, but still.

**Comment by Iamgoofball** [comment]
teach me to sprite

**Comment by nullbear** [comment]
I like the cards. Cheridan might be talking about how they appear to be quite thick, however. This would be due to the extra shading on the edges.

**Comment by optimumtact** [comment]
They look more natural in game instead of the artificial pictures Wjohn takes.

**Comment by WJohn** [comment]
The background 127 lum grey is very close to the color of a tile, so I just slap everything on it because it's much easier than having to throw both into paint and dreammaker n shit just to get a slightly better pic.

**Comment by Militaires** [comment]
i notice both the darker outline on the blue folder and the changed tab of colour on the bottom of the red folder

these eyes dont lie.

**Pull request merged**
