### PR TITLE
Smooth out gliding so movement isn't (as) jerky

### PR DESCRIPTION
**Pull request by MrPerson**
Only applies to non-ghost, non-camera mob movement. Scales automatically to any fps and any move delay.

Also took this oppurtunity to remove tickcomp because it was USELESS and shit.

All the rounding is because of floating point imprecision. round(2.7, 0.9) != 2.7, for example. 2.7 + world.time would wind up being < than world.time 3 ticks later even though they should be equal.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Interesting :+1:

**Comment by GunHog** [comment]
Add a .gif, please?

**Comment by RemieRichards** [comment]
@GunHog 

>smooth movements
>gif

rofl.

**Comment by GunHog** [comment]
Ehh, that was a dumb statement. A video, then?

**Comment by MrPerson** [comment]
github doesn't support webm

**Comment by Fox-McCloud** [comment]
correct me if I'm wrong, but isn't havin wonky movements, in part, due to you guys manually setting the oudated glide_size var on all atoms?

**Comment by MrPerson** [comment]
glide_size is only outdated if one doesn't use pixel movement, which we don't

**Comment by MrStonedOne** [comment]
Some notes, I think the rounding out of the world.ticklag might be doing you more harm then good.

Rounding out loses preciseness, called rounding errors as I'm sure you know. Doing multiplication or division with these rounded out numbers compounds the rounding error. I noticed some times with slower movements, it could be choppy, like the move delay was too slow compared to the move speed, and I'm thinking these rounding errors might be to blame.

at fpses of 24 or 60, you have world.ticklags of 0.4166666666 and 0.1666666666. in the case of 24, you round to 25, in the case of 60, you round to 50. 

This also leads to issues with running anything above 75fps as this will round out to 100fps, giving you a tick_lag of 0, and completely ruining the entire point of the feature.

**Comment by MrPerson** [comment]
There may not be a perfect solution (for now) because byond enforces glide_sizes in whole numbers anyway, but yeah, I'll do something about the rounding.

**Comment by RemieRichards** [comment]
if you need a whole number, and thus NEED to round, then you should do it after all the calculations, so you're rounding the "final" number, this mitigates rounding errors in the rest of the calculations as much as possible.

**Comment by MrPerson** [comment]
Should be right now

**Comment by MrStonedOne** [comment]
Something is messed up in the math, glidesize is much too high on higher move speeds, and too low in lower move speeds.

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=1918756

**Comment by MrPerson** [comment]
I don't really want to have to redo this after http://www.byond.com/forum/?post=1882348#comment16384168

**Comment by MrPerson** [comment]
There we go, exactly as requested. It does feel a bit better in testing with odd fps's and slower movement speeds.

**Comment by Steelpoint** [comment]
Merge he.

**Comment by Steelpoint** [comment]
Continue to merge this now please.

**Comment by WJohn** [comment]
There's some big visual problems when dragging or grab-dragging people or objects, mrperson.

**Comment by Anonus** [comment]
>smooths movement
>movement gets more jerky
very good excellent

**Comment by AnonymousNow** [comment]
As somebody actually playing on the server right now, the amount of lag is absolutely incredible, and judging by what I've heard from people, sourced to this here update.

**Comment by Miauw62** [comment]
No it didn't. It sourced to MSO increasing the FPS massively, which means
that EVERYTHING processes much more
Op 29-aug.-2015 22:27 schreef "AnonymousNow" <notifications@github.com>:

**Pull request merged**
