### PR TITLE
Adds a new parallax space layer

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: your main nizza tacolizza
add: the High and Insane parallax settings do something now
/:cl:

Parallax was designed so that the High and Insane settings would allow more than 2 layers, but only two layers were ever added.

### CODE REVIEW

**Comment by optimumtact** [comment]
We're in a feature freeze, also reset your master branch to match the upstream please

**Comment by Tacolizard** [comment]
its not a feature u dingus

**Comment by PKPenguin321** [comment]
Yes it is

**Comment by MrStonedOne** [comment]
Its a bad pr anyways, the layer would have to be actually different or there would be oddities since all layers start synchronized.

**Pull request closed without merging**
