### PR TITLE
Modifies the "No ERP" poster

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
There have been lots of arguments between players and admins about whether it's acceptable to use the term "ERP" in-character or if it constitutes netspeak, and inevitably this poster gets brought up as justification for it being IC. This PR defuses the argument entirely by changing the poster to be about how stupid saying ERP makes you sound.

Really though I just think this joke is funnier

## Why It's Good For The Game
Gives a new coat of paint to an old joke

## Changelog
:cl: Ryll/Shaps
spellcheck: Nanotrasen has modified its previous "No ERP" ad campaign to encourage people to stop saying "ERP"
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
I was so expecting "Extreme Role Play" joke but this is pretty great too

**Comment by LemonInTheDark** [comment]
> There have been lots of arguments between players and admins about whether it's acceptable to use the term "ERP" in-character or if it constitutes netspeak, and inevitably this poster gets brought up as justification for it being IC. This PR defuses the argument entirely by changing the poster to be about how stupid saying ERP makes you sound.

This is stupid. Players using this poster as an excuse aren't making a good faith argument, and there's a lot of other shit in the game like this. Just tell them no. Please not this again.

**Comment by InsaneRed** [comment]
just say "no fucking on station"

**Comment by Ryll-Ryll** [comment]
> > There have been lots of arguments between players and admins about whether it's acceptable to use the term "ERP" in-character or if it constitutes netspeak, and inevitably this poster gets brought up as justification for it being IC. This PR defuses the argument entirely by changing the poster to be about how stupid saying ERP makes you sound.
> 
> This is stupid. Players using this poster as an excuse aren't making a good faith argument, and there's a lot of other shit in the game like this. Just tell them no. Please not this again.

Mostly this PR was made because I think this line is funnier and more relevant to today's players, I have updated the PR to mention that

**Comment by YakumoChen** [comment]
:-1:
The argument doesnt even hold water, the examine text is clear it's an acronym for No "Eroticism, Rape, and Perversion" or something.

**Comment by YakumoChen** [comment]
Also you sound more like a tool telling people to stop saying a netspeak phrase *in an in character context* than you do to tell people to stop having sex

**Comment by interestingusernam3** [comment]
cringe PR

**Pull request closed without merging**
