### PR TITLE
Adds 91 new sprites for the Detective's Fedora and gives it some better booze.

### PR DESCRIPTION
**Pull request by Expletive**
:cl:
tweak: The detective's flask has Hearty Punch instead of whiskey.
fix: The Detective's fedora no longer clips with hair.
imageadd: Adds 91 new sprites to fix clipping issues with the Detective's fedora and hair.
imageadd: Change the standard fedora to match the detective and treasure hunter variants.
tweak: Detective, Treasure Hunter, and standard fedoras now all benefit from new sprites.
/:cl:

As I'm sure you're all aware,  since it's inception the Detective's hat has clipped with almost every single hairstyle in the game. Well, no longer. I've fixed it, and it was hours of fiddly monotonous work. There really should be some kind of automated tool for generating hair extensions. @cyberboss :wink: 

Edit: Adds treasure hunter wardrobe for the curator, repaths treasure hunter and detective fedoras as subtypes of fedora, resprites fedora to match detective and treasure hunter variants, and of course all of them will benefit from the hair extension sprites.

### CODE REVIEW

**Comment by WJohn** [comment]
holy shit. you went and fixed like the oldest bug ever #3583

**Comment by ChangelingRain** [comment]
holy shit, dude, you're so good.

**Comment by Expletive** [comment]
@ChangelingRain This was not a matter of good. This was a matter of being stupid and patient enough to sit at a desk and edit 454 32x32 images. Literally anyone could have done it, but no one else wanted to.

**Comment by ChangelingRain** [comment]
I think using a single dmi for hat-based hair changes might be a liiiitle impractical if people keep fixing hats that have issues with hair, though.

**Comment by Expletive** [comment]
If my experience was anything to go by, the Detective's Fedora will be the first and last hat to be fixed with @RemieRichards's dynamic hair system.

**Comment by ChangelingRain** [comment]
People who can sit down and do that are worth their weight in gold.

**Comment by optimumtact** [comment]
resource bloat

**Comment by RemieRichards** [comment]
@Expletive why are you @ ing Cyberboss for a tool? I'm the one who makes all the sprite cutting tools around here ;_;

**Comment by Cyberboss** [comment]
People just love me

**Comment by Cyberboss** [comment]
I don't know why

**Comment by optimumtact** [comment]
you have big t...eeth

**Comment by RemieRichards** [comment]
Also, amusing that you chose to do:
Hat -> All Hair
As opposed to Hair -> All Hats

this means everyone gets the improvement for that hat (where as improving one hair would only help certain people)

Well done.

**Comment by lzimann** [comment]
what kind of detective would drink something named "hearty punch" instead of the manly whiskey

**Comment by Expletive** [comment]
"bravado in the face of disaster" seems like a pretty manly flavor to me.

**Comment by DoctoreMad** [comment]
>The detective's flask has Hearty Punch

Do you realize how strong that thing is?
Not that I completely oppose this but.

**Comment by Expletive** [comment]
@RemieRichards Need a bit of help with dynamic hair. It doesn't seem to update properly. When the game starts, the detective hat will be clipping with the hair until update_hair() is called.  Additionally, when you take off the hat, the overlay isn't removed properly, so you look like you have male pattern baldness.

**Comment by dannno** [comment]
Jesus christ

**Comment by Expletive** [comment]
Okay, the issues with dynamic hair not loading at the start are fixed.

**Comment by ma44** [comment]
>30 units of hearty punch

That's like 5 minutes

**Comment by RemieRichards** [comment]
@Expletive I would assume outfits/job equipping isn't calling the right procs in time?
And I would assume unequipping hats is doing the same.

**Comment by FantasticFwoosh** [comment]
Hearty punch can save people out of critical, this amount of it can be used & abused by Odyy's as powergaming tool. 

It takes bare mimumum effort to take with mixing & heating but 30 ounces takes a shit-ton of time when it only makes 7 ounces from almost a 100 units of mixed drinks heated up.

**Comment by Tacolizard** [comment]
hey look it's Fantastic 'Try my hardest to find some emergent gameplay edge case and call it powergaming because i like hugbox and i want to remove any feature that isn't 100% directly intended' Fwoosh.

**Comment by Shapsy** [comment]
I mean he's not wrong that it's a strange choice considering how it takes forever to brew a tiny amount and how powerful it is

**Comment by PKPenguin321** [comment]
Doesn't hearty punch indefinitely raise your max HP while it's in your system or something

**Comment by Expletive** [comment]
@PKPenguin321  Hearty Punch heals you but only when you're in crit.  You're thinking of Brave Bull, and that  only increases your max HP by 5.

**Comment by lzimann** [comment]
When you have to add 91 new sprites to fix something, you have to ask yourself: Is such thing even needed? Not trying to undermine your work or anything, but such thing is just not feasible to even think about. Imagine if someone wants and resprite the detective's fedora, he would have to change all these 91 icons aswell. And 91 just for a single hat. We can't simply add 91 new sprites for every hat that has a hair problem...

**Comment by Expletive** [comment]
>We can't simply add 91 new sprites for every hat that has a hair problem...

Can't, or won't? As far as re-spriting the detective's fedora, or any hat for that matter, if you make a sprite that is going to conflict with the vast majority of the game's hairs, shouldn't you go through the work of fixing those conflicts? Additionally, of the 91 sprite I added, only about ten required required unique adjustments, while the rest could likely have been done by an algorithm that just clears all pixels above the brim of the hat. The problem is definitely one that can be solved by a tool. I just didn't have the tool, and so substituted patience.

**Pull request merged**
