### PR TITLE
Pet Command Component + Regal Rats can order their subjects around

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Another atomisation of #71421 but I had a fun idea while I was testing it.

This adds a component based on the existing system for giving instructions to tamed carp or dogs, but hopefully more modular.
It also gives it to the rat minions of a regal rat.
The basic function allows the mob to listen and react to spoken commands, which passes things to its AI blackboard. Additionally if you alt-click a commandable mob it will show a radial menu which both allows you to select a command, and also contains tooltips explaining what they do and what audible words trigger it.

<details>
  <summary>Video</summary>
  
https://user-images.githubusercontent.com/7483112/204308693-0eccebec-75c9-411c-81c5-5aa0d682d1a5.mp4

</details>

Now if you riot some rats, you can alt click on them individually to give them specific orders (more useful for other creatures than rats), or you can speak out loud to command your legion.
Rats aren't very smart so you can't give them many instructions, but this is expandable for other creatures.

Additional change: Mice don't squeak if stepped on by other mice because this made an absolutely unholy noise and I am not sure there's a way to get non-dense mobs to spread out.

## Why It's Good For The Game

Allows for giving more mobs the ability to be tamed and instructable by their owner, without copy/pasting code which lives inside a specific mob.
Yelling at your rats to give them commands is funny. It also adds the possibility of telling your rats to stop biting someone if they have agreed to your demands, allowing for more courtly roleplay.
When Regal Rat is converted to a basic mob its AI can also give other AIs instructions by yelling at them which I think is a good feature.

## Changelog

:cl:
add: The followers of Regal Rats will now respond to simple instructions, if given by their rightful lord. Except frogs. They're too busy licking themselves and watching the colours.
/:cl:

### CODE REVIEW

**Comment by Oranggu** [comment]
If i gather many rats will i be able to storm sec and kill everyone?

**Comment by Oranggu** [comment]
> If i gather many rats will i be able to storm sec and kill everyone?

Oh and will i be able to go through vents with my mice together and all come out of the same vent and scare the shit out of people?

**Comment by Jacquerel** [comment]
> If i gather many rats will i be able to storm sec and kill everyone?

Yes. You could already do this by generating a lot of cheese _inside_ security but this required nobody to be around, it's certainly much easier when you can have rats follow you. 
Rats aren't very hard to kill though.

> Can rats vent crawl with me?

No. Maybe one day someone will add the ability for this, but their pathfinding isn't that smart and their AI doesn't know what vent crawling is.

**Comment by Jacquerel** [comment]
image

I will try this with future flexibility in mind.

**Comment by Jacquerel** [comment]
Alright updated with suggestions to make it more flexible for the future, and someone allowed regal rats to convert more mob types since I branched so now you can order roaches as well.
It doesn't work for frogs because they still have simple mob retaliate AI. Someone should get on that some time.

Pinging @CapybaraExtravagante and @Watermelon914 because you had opinions about it in Discord.

**Comment by Jacquerel** [comment]
Someone merged dogs now I have to add those in too

**Comment by Jacquerel** [comment]
Starting to think I didn't learn my lesson and should do the dog stuff in another PR, I will maybe just branch from that point and revert this branch to before I started.

**Comment by Time-Green** [comment]
@tralezab can you take a look at this? You know this system well

**Pull request merged**
