### PR TITLE
Balances pyro anomaly

### PR DESCRIPTION
**Pull request by LatD**
Some nerfs to the huge constant fires which burn huge areas but also buffs the final damage if the anomaly is left un-signalled. I tested this with these values and now it looks better. It's still constantly releasing flames around it and the final explosion is pretty big but not too big.

It's hard to analyze the signal when the room looks like this 1 second after the anomaly spawns:
pyro

### CODE REVIEW

**Comment by KorPhaeron** [comment]
It probably needs a sprite change so you can actually see it

**Comment by LatD** [comment]
It used to be okay since it wasn't completely hidden by fire and after this it won't be again. But still, that would also help. Orange cloud in fire is really hard to see.

**Comment by Cheridan** [comment]
something i do with these events is if they go off and the slime spawns, i offer control of it to ghosts. i think it'd be neat if it did that automatically.

**Comment by optimumtact** [comment]
post change pic ?

**Comment by LatD** [comment]
newpyro

It's pretty close to what it used to be I think. It lights about 4 tiles on fire and then disappears so you actually have a chance of scanning it without being set on fire if you're careful/lucky. 

And the final big fire got buffed in both if I remember correctly. The room was burning about 10 seconds in this test before the plasma ran out and it raised the temperature pretty high.

finalfire

**Pull request merged**
