### PR TITLE
Fixes a poster in delta departures security checkpoint

### PR DESCRIPTION
**Pull request by FlamingCheese**
## About The Pull Request
image
this poster has bugged me for quite a while and i have just decided to open sdmm to fix it

## Why It's Good For The Game
we dont have to suffer the purple and black checkerboard rectangle in departures anymore

## Changelog

:cl:
fix: Reality has downloaded CS Source which fixed the missing texture of a poster in departures security checkpoint
/:cl:

### CODE REVIEW

**Comment by FlamingCheese** [comment]
fuck i forgot the name

**Comment by RazorManager89** [comment]
speed merge coming?

**Comment by EOBGames** [comment]
You should replace this with the poster it's actually meant to be according to the icon state, which would be /obj/structure/sign/poster/official/report_crimes.

**Review by EOBGames — CHANGES_REQUESTED** [review]
Replace this with the poster it's actually meant to be according to the icon state, which would be /obj/structure/sign/poster/official/report_crimes.

**Pull request merged**
