### PR TITLE
Spices up the syndie shuttle loan event

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
balance: Syndicate shuttle boarding parties have been beefed up considerably.
/:cl:

"Hey Frank, who should we send to infiltrate this space station full of deranged sociopaths?" "How about two to four dudes but we don't give them any weapons?" 🤔 

New crew is two syndies with an esword+eshield. 75% chance for another dude with a pistol as well as a 50% for a melee stormtrooper (really just a spaceproof melee syndie with twice the HP).

Keep in mind that these are still simplemobs, which means they're very easy to cheese if you know what you're doing. It's just no longer a completely risk free specops crate + cargo $$$.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
is that the oneshot shotgun trooper? also the spec op crate is garbage

**Comment by 81Denton** [comment]
Nah, the crazy strong one is the ranged stormtrooper

**Comment by ExcessiveUseOfCobblestone** [comment]
Do you ignore the armor/insuls/noslips lol?

**Comment by 81Denton** [comment]
wait shit

**Comment by 81Denton** [comment]
don't drink and PR kids

**Pull request closed without merging**
