### PR TITLE
Take out the trash

### PR DESCRIPTION
**Pull request by optimumtact**
:put_litter_in_its_place:

### CODE REVIEW

**Comment by xxalpha** [comment]
:+1: :put_litter_in_its_place:

**Comment by optimumtact** [comment]
:put_litter_in_its_place:

**Comment by MrStonedOne** [comment]
>not deleting the sound file

**Comment by optimumtact** [comment]
fucku.ogg

**Comment by xxalpha** [comment]
>doesn't even compile

:put_litter_in_its_place:

**Comment by duncathan** [comment]
what about the crate

**Comment by optimumtact** [comment]
Yeah give me time okay :slothcode:

**Comment by WJohn** [comment]
:-1: x :100:

**Comment by ike709** [comment]
:-1: WEEEEOOO. WEEEEEOOO. WEEEEOOOO.

**Comment by optimumtact** [comment]
Grudge code ends here

**Pull request closed without merging**
