### PR TITLE
Implements LIGHTING_ROUND_VALUE in lighting

### PR DESCRIPTION
**Pull request by Incoming5643**
Implements LIGHTING_ROUND_VALUE, which was defined as 1 / 128 but never used anywhere. It's since been moved up to 1 / 64 as a result of discussion in this pull.

#25778 worked off the assumption that values for lighting would actually reach 1 or 0 when the tile was full bright/full dark. For whatever reason once a lighting object had been interacted with it would sometimes lead to values of just not quite 0 and not quite 1 moving forward. That pull worked on the assumption that LIGHTING_ROUND_VALUE was a thing that actually existed, but it didn't. So now it does.

Theoretically this DOES change the visuals, but the chunking of values is so fine I could not tell the difference.

### CODE REVIEW

**Review by duncathan — APPROVED** [review]
The minor if not unnoticeable visual differences are worth the performance increase.

**Comment by MrStonedOne** [comment]
It's currently 1/128

Thats 28 bits of entropy or 268 million states.

1/64 would still mean 24 bits of entropy in lighting, so that's 16million states,

Unrounded is 128 bits of entropy, the same as all of ipv6, or `340,282,366,920,938,463,463,374,607,431,768,211,456`

**Comment by lzimann** [comment]
If it changes the visual, post pictures of it, please.

**Comment by Incoming5643** [comment]
@Izimann time for a rousing game of spot the difference

lightcomparison

Disclaimers: 
This is how it renders locally, other people's computers might render it different.
The number by no means has to be a power of 2.

**Comment by ChangelingRain** [comment]
Please make that four different images so I can actually flip through them to see if anything changes.

**Comment by Incoming5643** [comment]
1 / 16
light16

---

1 / 32
light32

---

1 / 64
light64

---

1 / 128
light128

**Comment by Incoming5643** [comment]
They are not exactly the same, but none of them look objectively "less correct" in my opinion. Things only start to look goofy at very low values of 1 / X.

**Comment by lzimann** [comment]
I honestly can't see any difference so all good I guess

**Comment by ChangelingRain** [comment]
The biggest difference I can see is that 1/16, 1/32, and 1/128(???) seem to have less darkness. Otherwise they don't appear really that different.

**Pull request merged**
