### PR TITLE
Void suit and jetpack resprite

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Changed the void suit and jetpack sprites to a modified version of those made by Azlan for Bay 12.

image

Current sprite for reference: 
image

## Why It's Good For The Game

The sprite looks professional, and has better shading.

## Changelog

:cl: Azlan, Fikou, MTandi
imageadd: Void suit and jetpack resprited
fix: Also fixed the issue with all jetpack sprites not updating on the back
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
time to get mistaken for a syndi (looks good as fuck)

**Comment by Fikou** [comment]
image
missing a pixel here

and the inventory helmet sprite does not fit our art style, none of our helmets are sprited isometrically

**Comment by MTandi** [comment]
> and the inventory helmet sprite does not fit our art style, none of our helmets are sprited isometrically (other than like the wizard modsuit) they are all done in a 3/4th

Should be ok if I just replace it with the SOUTH version of the helmet, right?

**Comment by Addust** [comment]
oldstation is OLD station
it should look OLD
let us have our soul in our voidsuits

**Comment by MTandi** [comment]
> oldstation is OLD station it should look OLD let us have our soul in our voidsuits

It's more pleasant for people to play with nice sprites, instead of crudely made ones, most don't care about that "soul" argument. I play oldstation and I'd love the suits to be at least at the same level as the ancient engineer's modsuit. It's just weird that you have a cool looking modsuit and 2 ugly space suits on the same map.
And I will replace those damn hollow windows in my lifetime too.

**Comment by Serxule** [comment]
> oldstation is OLD station it should look OLD let us have our soul in our voidsuits

void suit isnt nearly as iconic as something like the toolbox, and this still keeps a good bit of soul, as its just a new version of the old sprite

**Pull request merged**
