### PR TITLE
Revert "Improve youtube-dl subsystem  (#40396)"

### PR DESCRIPTION
**Pull request by lilacrhododendron**
This reverts commit 7d05db3cdd559b799ab496c841799b60680c9e6c.

This was done on behalf of Arianya for testmerge. Kevinz broke the play internet sound verb.

### CODE REVIEW

**Comment by Arianya** [comment]
Thanks subject

**Comment by Arianya** [comment]
kevinzzzzzzzzzz

@kevinz000

**Comment by kevinz000** [comment]
I will not open any webeditor prs x200 on whiteboard

**Comment by Borisvanmemes** [comment]
someone speedmerge this for the love of god how am i meant to spam the players with trash anime like this aaaaaaaaa

**Comment by subject217** [comment]
It's not meant to be merged, it's meant to be testmerged while @kevinz000 fixes his mistakes.

**Comment by Arianya** [comment]
It wasn't testmerged everywhere hence boris' comment.

It now is.

**Comment by Cyberboss** [comment]
@kevinz000 fucking fix this

**Pull request merged**
