### PR TITLE
Allows admins to see how many people have MIDIs enabled!

### PR DESCRIPTION
**Pull request by silicons**
ITS NOT A FEATURE!!

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Pretty sure this is

**Comment by jughu** [comment]
Only if we can see admins playing a midi too!

**Comment by kevinz000** [comment]
@KorPhaeron It's "logging" and "Statistics"

**Comment by TechnoAlchemisto** [comment]
Something about this seems weird

**Comment by ExcessiveUseOfCobblestone** [comment]
why is this needed?

**Comment by Haevacht** [comment]
It's a way for kevinz to fix which midis he plays, totally not a feature.

**Comment by ExcessiveUseOfCobblestone** [comment]
yet another science buff from mekhi

**Comment by KorPhaeron** [comment]
Reopen after the freeze

**Pull request closed without merging**
