### PR TITLE
nukes families being in dynamic

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Removes families from dynamic

## Why It's Good For The Game
Families seriously just doesn't work with dynamic, in any capacity, and I have yet to find someone who likes it in dynamic.

## Changelog
:cl:
tweak: removes families from the dynamic rulesets
/:cl:

### CODE REVIEW

**Comment by ShibaInuLord** [comment]
yeah, families is utterly broken on dynamic and this is the best pr ive ever seen

**Comment by tmtmtl30** [comment]
what about it doesn't work?

also, if you're going to do this, for christ's sake move the code out of the handler. it's a dumb hack i did to make the code easier to maintain and if there's no need for it i don't want to perpetuate shitcode

**Comment by optimumtact** [comment]
this is configurable.

**Comment by Paxilmaniac** [comment]
> this is configurable.

then do it

**Comment by Iamgoofball** [comment]
Stop touching my gamemode.

**Comment by MortimerMcMire** [comment]
your game mode fucking sucks

**Comment by IndieanaJones** [comment]
I don't blame them seeing the round on Bagil which spurred this PR.

**Comment by Iamgoofball** [comment]
The round timer is not supposed to be an hour on Dynamic Families. This is a bug. I will fix it.

**Comment by optimumtact** [comment]
@Paxilmaniac that's a question for the headadmins, not me.

**Pull request closed without merging**
