### PR TITLE
Bababoo-sie

### PR DESCRIPTION
**Pull request by Toastgoats**
## About The Pull Request
babagfoogugggege

Bababoo-sie

## Why It's Good For The Game
Bababoo-sie

# I am so sorry

## Changelog
:cl: Toastgoats
add: BABABOO-SIE HAS RISEN
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
Howard stern is one of the lowest life forms to exist.

**Comment by ATH1909** [comment]
> Howard stern is one of the lowest life forms to exist.

*highest

**Comment by trollbreeder** [comment]
> > Howard stern is one of the lowest life forms to exist.
> 
> *highest

*lowester

**Comment by Doosteroni** [comment]
> Howard stern is one of the lowest life forms to exist.

You misspelled “God”

**Comment by TheVekter** [comment]
bababooey

**Pull request closed without merging**
