### PR TITLE
Oldstation QoL tweaks and minor fixes

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Made minor changes to Oldstation:

- Adjusted paper texts to not show HTML tags and have more consistent lore/hints
- Removes soul by changing hollow windows to fulltile windows with new helpers that make windows look damaged with cracks. You can fix them now if carps damage them from outside.
- Trash bins contain random trash instead of random maintenance loot
- Beta airlock extended to 2 tiles (you could not enter safely dragging a chest before)
- Delta AI sat airlock extended to 2 tiles (1 tile is just not good for cycling airlocks)
- Air alarms and APCs now require general_away access instead of being all-access or requiring a special card

No changes in loot.

## Why It's Good For The Game

Better player experience for Oldstation.

## Changelog

:cl:
qol: Oldstation: Windows are easier to fix as they're now fulltile and use the new helpers to appear cracked.  
qol: Oldstation: You don't need a special card to access APCs, other minor access tweaks.
qol: Oldstation: Some walls have been moved and adjusted for better navigation and look.
fix: Oldstation: Fixed paper text, overlapping objects, xenos being blocked by flying crates, and some other minor issues.
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
oldstation return real?

**Comment by MTandi** [comment]
> oldstation return real?

Always has been

**Comment by Googles-Hands** [comment]
Noooo, not the hollow windows, you cannot sacrifice that mouch soul, nothing is worth the price!

**Comment by MTandi** [comment]
> Noooo, not the hollow windows, you cannot sacrifice that much soul, nothing is worth the price!

The blue toolbox is enough for soul.

**Pull request merged**
