### PR TITLE
Head Megaphones + Megaphone changes

### PR DESCRIPTION
**Pull request by GunHog**
Adds Command Megaphones to the following head of staff lockers:
- Research Director
- Chief Medical Officer
- Chief Engineer

You may now yell over the radio using your megaphone. **Clowns intensify!**

:cl:
Name: Gun Hog
rscadd: The CE, RD, and CMO have been issued megaphones.
/:cl:

The Captain, Head of Security, and Head of Personnel already have one.

Salvaged from https://github.com/tgstation/tgstation/pull/17795 

**EDIT:** Megaphones now use the `say()` proc, and thus respect more properties about the mob.

screenshot 2016-05-26 17 52 33

Fixes https://github.com/tgstation/tgstation/issues/17104
Fixes https://github.com/tgstation/tgstation/issues/15865
Fixes https://github.com/tgstation/tgstation/issues/9850
Fixes https://github.com/tgstation/tgstation/issues/9842

### CODE REVIEW

**Comment by Cheridan** [comment]
we really shouldn't be adding more of these to the game until their multiple bugs get fixed

**Comment by optimumtact** [comment]
Cheridan has a point, these things disobey language rules, have all sorts of strange bugs.

**Comment by kevinz000** [comment]
mekhi buff :+1:

**Comment by GunHog** [comment]
This is not a map edit, oranges. I could hardly call this "balance", though. A megaphone just lets you yell at people - it does not many anyone stronger or weaker, just more annoying. As for the bugs, I am testing a fix to make it run through `say()`.

**Comment by optimumtact** [comment]
It's the only relevant tag I have on hand

**Comment by GunHog** [comment]
I will need a moment to test this with abductors and other say() oddities.

**Comment by bgobandit** [comment]
as the coder of the clown megaphone: f e a t u r e

**Comment by GunHog** [comment]
Added the issue reports I found about megaphones. Also, this could use a "Fix" tag.

**Pull request merged**
