### PR TITLE
THE HAND OF GOD (APPARENTLY MOST OF CODERBUS WAS ALSO WORKING ON THIS SO)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Xhuis** [comment]
# WELL IT TURNS OUT THAT REMIE AND ANTUR WERE BOTH WORKING ON HAND OF GOD TOO SO I'M JUST GONNA CLOSE THIS AND WE CAN PRETEND IT NEVER HAPPENED

**Comment by RemieRichards** [comment]
Honk honk.

**Comment by Anonus** [comment]
>THREE PEOPLE WORKING ON ONE MODE EACH INDEPENDENTLY

**Comment by RemieRichards** [comment]
@Anonus ON THE SAME DAY NO LESS!

**Pull request closed without merging**
