### PR TITLE
Revert "Multiverse clones are now identical to the summoner"

### LINKED ISSUE #14183: Multiverse Swords are broken
Instead of making copies of the copy you're supposed to be, they instead made a carbon copy of my lizard character

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
That wasn't well thought out

Fixes #14183

### CODE REVIEW

**Comment by Zilenan91** [comment]
Just make them all have the same outfit and give the swords 100 AP, that'll fix it.

**Comment by Zilenan91** [comment]
Alternatively we can just remove multiverse swords because the whole round turning into memes 3 seconds in got old a few weeks ago

**Comment by GunHog** [comment]
Is there a way to have a multiverse HUD for allied clones?

**Comment by KazeEspada** [comment]
What happened?

**Comment by RemieRichards** [comment]
@KazeEspada people's clones would make a clone, but it would look like them instead of the original.
meaning none of the people looked like each other, meaning it was even MORE of a clusterfuck than usual.

**Comment by KorPhaeron** [comment]
>Is there a way to have a multiverse HUD for allied clones?

Probably not

**Comment by Jordie0608** [comment]
#14183

**Comment by tkdrg** [comment]
There is a way but it would suck unless I rewrote huds again

**Comment by KorPhaeron** [comment]
Infinite datum gangs of clone teams

**Comment by Incoming5643** [comment]
Datum antags might vaguely hold the answer, but man I'm not promising on that one.

As for this couldn't you just store a copy of the original sword owners prefs in the sword and then have any sword it makes inherit those prefs?

**Comment by tkdrg** [comment]
Then if I steal someone's sword I can clone the other person?

**Comment by Incoming5643** [comment]
you could have the swords saved prefs reset if someone else took the sword, it DOES have a "binding it to you" thing.

I don't know why I'm trying to save the memesword

**Comment by Zilenan91** [comment]
Just make the sword curse the players current outfit, and when used, spawn another player in that exact same outfit that is also cursed. Everyone looks different, easy to identify.

**Comment by Jacquerel** [comment]
Making all the clones have the same clothes and appearance really does seem like it would solve all the issues, I don't know why it's taking so long to turn to it,
Is randomly coloured jumpsuits really so important?

**Pull request merged**
