### PR TITLE
Add airport luggage conveyer for Meta cargo warehouse

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This adds a circular conveyer system for cargo warehouse that is aimed to represent:

<details>
<summary>Airport Luggage Conveyer</summary>

suitcases-on-the-airport-luggage-conveyor-belt-bag-EG4NH9Q-1024x682

</details>

In order to get this to work properly, I added a disposals outlet to the end of the cargo unloading conveyer that transports any crates directly into the warehouse.  The mail sorting also will feed any cargo tagged mail to the warehouse instead of the disposal bin in the main cargo area.

<details>
<summary>Before:</summary>

StrongDMM_5DF7pZKACn

</details>

<details>
<summary>After:</summary>

StrongDMM_SWvdQPCz2X

</details>

<details>
<summary>After (with air pipes visible):</summary>

StrongDMM_GndnDwKdQ2

</details>

## Why It's Good For The Game

You've got mail!

## Changelog

:cl:
qol: Add airport luggage conveyer for Cargo warehouse
/:cl:

### CODE REVIEW

**Comment by EOBGames** [comment]
Alright I figure I should be direct about this- I don't like this change, it looks to make cargo more awkward to play for the sake of a gimmick I don't see many people, if any, engaging with.

I'll leave this open for 24 hours to see if someone can change my mind.

**Comment by timothymtorres** [comment]
The warehouse wasn't heavily used except as a niche spot to convert/kill people.  The changes give it more utility by: 

- Routing the offloaded cargo crates get transported to the warehouse via conveyer
- Routing cargo mail to the warehouse for storage
- Letting people pickup crates without having to let them into cargo
- Keeping the room not opaque so you can still murder/kill people

Cargo already uses conveyers to _input_ crates.  It makes sense to do the same to _output_ crates.

Also I don't understand why you are restricting it to 24 hours?  Most maintainers allow discussion on a PR for longer than that before it gets closed to provide player feedback, compromise, alternate changes, etc.

**Comment by Edelor68** [comment]
Maybe make it so that the outlet empties directly onto the roundabout from one of the sides. Right now you have to walk across the conveyor belt to get to the doors and there would be more actual room to use that way.

**Comment by SuperNovaa41** [comment]
> Also I don't understand why you are restricting it to 24 hours?
aka he wants to close it but 24 hour rule

**Comment by tralezab** [comment]
> > Also I don't understand why you are restricting it to 24 hours?
> 
> aka he wants to close it but 24 hour rule

or more accurately "closeworthy but not instacloseworthy"

anyways, to contribute myself I actually like the idea of an airport luggage conveyor on one of the maps but meta seems like the absolute worst one to choose, does it not? I mean, you gore that warehouse

**Comment by timothymtorres** [comment]
Meta is the only map that has its cargo adjacent to the main hallway, which is kind of the whole purpose of players to come pick up their luggage.

**Comment by zxaber** [comment]
By moving the above return section down one tile (with directional windows rather than full-tiles), and moving the despenser to be along the edge, you could make this a 2x6 tile feature rather than a 6x5 one. That would leave most of the room mostly untouched and useful for other things.

**Comment by timothymtorres** [comment]
> By moving the above return section down one tile (with directional windows rather than full-tiles), and moving the despenser to be along the edge, you could make this a 2x6 tile feature rather than a 6x5 one. That would leave most of the room mostly untouched and useful for other things.

This is not a bad idea.  The original map I ported it from (my own custom map) had a larger area for the warehouse.

StrongDMM_STrPiuOslW

**Comment by Mothblocks** [comment]
> Also I don't understand why you are restricting it to 24 hours? Most maintainers allow discussion on a PR for longer than that before it gets closed to provide player feedback, compromise, propose alternate changes, etc.

> aka he wants to close it but 24 hour rule

There is no 24 hour rule for closing and maintainers can close any PR they want whenever they feel like. The 24 hour time *is* Inept allowing discussion on a change he does not agree with.

**Comment by Serxule** [comment]
> The warehouse wasn't heavily used except as a niche spot to convert/kill people. The changes give it more utility by:
> 
> * Routing the offloaded cargo crates to get transported to the warehouse via conveyer
> * Routing cargo mail to the warehouse for storage
> * Letting people pickup crates without having to let them into cargo
> * Keeping the room not opaque so you can still convert/kill people

the warehouse is for storing stuff, it doesnt need utility, none of this will change cargo to be any better, and itll just take up more space

**Comment by Jolly-66** [comment]
I don't really like this.
I can't tell if there's windoors or something in the plastic flaps, but what's stopping an annoying assistance from getting into the rest or cargo?

Also you put it in the warehouse, it looks ridiculous.

**Comment by Wallemations** [comment]
I'd recommend adding a windoor to the input chute so you can choose to have it go into the rotator or not.

**Comment by timothymtorres** [comment]
> There is no 24 hour rule for closing and maintainers can close any PR they want whenever they feel like. The 24 hour time _is_ Inept allowing discussion on a change he does not agree with.

I was asking why so I could get feedback since the only vague reasons given were:

> it looks to make cargo more awkward to play for the sake of a gimmick I don't see many people, if any, engaging with.

Which doesn't really communicate anything to me.  Adding conveyors to the warehouse is awkward? (aren't there several conveyor belts already) Cargo techs won't use them?  People from other departments won't pickup their crates from the warehouse?  It would have been nice if he could have elaborated on what was wrong.

The rest of the people in this thread have pointed at _specific_ problems need to be addressed, which have been very helpful and engaging.  Regardless, I think this PR is dead at this point so I'm going to close it.

**Pull request closed without merging**
