### PR TITLE
Fixes inserting/ejecting console ID's

### LINKED ISSUE #45577: ORM does not recognise mining ID card and refuse to dispense points
## Reproduction:
Be miner
Mine
Put hard earned ores into ORM
Watch as it doesn't give you points when you put ID in
Watch as it refuses to dispense your card, so you have to alt+click it
It swallows up budget cards and you have to pry it open to get it back
github_issue

It COULD be because we are on Donut, if you cannot reproduce it in any other maps.

### PR DESCRIPTION
**Pull request by kingofkosmos**
My PR #45193 wasn't 100 % tested before merging and it resulted in some consoles not accepting ID cards and other wonkiness. This should fix those multiple issues although it contains lots of copypastacode which is far from elegant.

Closes #45577

## Changelog
:cl:
fix: inserting/ejecting consoles with id's fixed.
/:cl:

### CODE REVIEW

**Comment by peoplearestrange** [comment]
Will this also fix protolathes not being able to eject materials?
I couldn't find a relevant bug report, but Its been noted in happening.

**Comment by TerraGS** [comment]
@peoplearestrange that sounds like an issue tied to Floyd Mats

**Comment by peoplearestrange** [comment]
Hmmm Ok, I'll make a bug report next time someone talks about it. Its definitely seems to be a bug with machine interfaces in general right now though.

**Comment by actioninja** [comment]
I'm working on a better refactor of this anyways and I would prefer it functional in the mean time.

**Pull request merged**
