### PR TITLE
blood cleave nerf

### PR DESCRIPTION
**Pull request by ghost**
## Why It's Good For The Game

one click to almost certainly kill someone is not interesting for the heretic or the victim

## Changelog
:cl:
tweak: blood cleave does only one wound instead of 3 now
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
image
image

**Comment by EdgeLordExe** [comment]
you are breaking how heretics skill tree works, youve got to make a new spell and replace cleave with it/ or just nerf cleave to give only 1 serious wound

**Comment by Krysonism** [comment]
I think it will be fine when people learn how to appropriate medical supplies.

It is premature to ided nerf something before the playerbase even tries to learn how to counterplay this.

**Comment by necromanceranne** [comment]
Actually, critical cuts are serious enough that it'll exsanguinate you extremely quickly. You cannot stop that mid combat reasonably well without completely relocating yourself, and it actually is relevant in a fight. Only a few times has a critical cut come into a fight I've been in, but the most recent was a ninja attack I survived via spamming teleportation via relics and teleport armor as well as hand tele. I ended it on deeply low blood despite having used the right med supplies and only fighting for a short time. And it took two strikes from the ninia to even get to that point. That heretics just slap you with them is terrifying. That's a fucking monster of an ability.

**Comment by Krysonism** [comment]
> Actually, critical cuts are serious enough that it'll exsanguinate you extremely quickly. You cannot stop that mid combat reasonably well without completely relocating yourself, and it actually is relevant in a fight. Only a few times has a critical cut come into a fight I've been in, but the most recent was a ninja attack I survived via spamming teleportation via relics and teleport armor as well as hand tele. I ended it on deeply low blood despite having used the right med supplies and only fighting for a short time, and I nearly died mid treatment. And it took two strikes from the ninia to even get to that point. That heretics just slap you with crit cuts is terrifying. That's a fucking monster of an ability.

Athath said he was able to survive getting blood cleaved "like 10 times" using the emergency pens from the emergency kits.

**Comment by necromanceranne** [comment]
Do you steal all the emergency medipens from the stations lockers like a kleptomatic lunatic?

Oh look at that he has a pr to make that tactic more possible by adding them to the most abundant medical vendor on the station WHAT A FUNNY COINCIDENCE.

**Comment by Krysonism** [comment]
> Do you steal all the emergency medipens from the stations lockers like a kleptomatic lunatic?
> 
> Oh look at that he has a pr to make that tactic more possible by adding them to the most abundant medical vendor on the station WHAT A FUNNY COINCIDENCE.

I am going to test blood cleave Vs the two types of coagulant pens once I get home from work and report back the results.

**Comment by necromanceranne** [comment]
Who cares, not everyone insists on hoarding the specific counters to every potential threat. If you cannot survive even one use of this power without the ONE item you might need to seek out to obtain, what kind of balance is that?

**Comment by Krysonism** [comment]
> Who cares, not everyone insists on hoarding the specific counters to every potential threat. If you cannot survive even one use of this power without the ONE item you might need to seek out to obtain, what kind of balance is that?

One of the pen types spawns in your box at round start.

**Comment by Krysonism** [comment]
normal blood volume = 560

emergency medipen / standing still - final blood volume: 540
emergency medipen / running around - final blood volume: 537.6
epinepherine medipen / standing still - final blood volume: 498
epinepherine medipen / running around - final blood volume: 499

This little test seems to indicate that the spell seems to be almost completely countered if you can epi pen yourself right away.

If everyone spawns with the counter in their bag, the complaints about this ability seems to largely due to insufficient knowledge of the mechanics, as i suspected.

However, this does not mean this is a good state of things, since this makes this ability very all or nothing.

I would support this nerf, or a similar nerf, if the coagulant clotting rate also was reduced to not be a nigh perfect counter for cuts.

As it stands, your normal epi pens cures multiple of the most severe cuts in just a few cycles.

**Comment by Tlaltecuhtli** [comment]
make it delimb instead of wounds

**Comment by Krysonism** [comment]
> 
> 
> make it delimb instead of wounds

Making it melee range is a better nerf i think.

**Comment by Iatots** [comment]
Melee range is almost useless, heretics already need to powergame with stunbatons and shit because they get so little toys.

Also it was already supposed to be nerfed to two cuts, what happened to that?

**Comment by LoserWasTaken** [comment]
> Also it was already supposed to be nerfed to two cuts, what happened to that?

huh?

**Comment by Iatots** [comment]
Back when its first nerf was being discussed, it was suggested that it be changed to not do 3 grievious wounds. Edgelord seemed alright with it, but it seems that in the end they just moved it further down the research tree unnerfed, basically delaying the inevitable.

**Comment by ATH1909** [comment]
literally just pop your roundstart epipen and you'll be good, it basically deletes all of your cuts within seconds due to how stronk coagulant is.

this nerf turns cleave from "basically lexorin" (only good against people who either don't have their roundstart epipen on them or who don't know that they can counter it with an epipen) to "basically useless".

**Comment by Krysonism** [comment]
Why was this merged?

**Pull request merged**
