### PR TITLE
Adds Send To All to Lawyer/Captain cartridges

### PR DESCRIPTION
**Pull request by AnturK**
Random feature request.
Not giving this to Librarian because we all know how will that end.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
10/10 would steal as assistant

**Comment by Zilenan91** [comment]
Do these spawn on the lawyers themselves, or do they spawn in the office? I'd love if they spawned in the office if you wouldn't mind cracking open a map edit, it would allow for some really clownish shenanigans

**Comment by Shapsy** [comment]
This would be hitler for the admins and dead people when they get 50-60 copies of the same message

**Comment by Shadowlight213** [comment]
:-1: what shaps said. Fix it spamming deadchat with messages.

**Comment by Nanotransistor** [comment]
If you get spammed, just turn the messenger off.

**Comment by octareenroon91** [comment]
It looks like this PR does post only one line to ghosts.
The line in create_message that would be spamming ghosts is suppressed for bulk messages.

**Comment by bgobandit** [comment]
why the lawyer though

**Comment by Zilenan91** [comment]
JC Denton always spams his generic law firm message every round he's lawyer

**Comment by Aranclanos** [comment]
the send_to_all() proc is just a big chunk of coypaste, fix that

**Comment by Zilenan91** [comment]
Woody's everywhere rejoiced

**Pull request merged**
