### PR TITLE
Converts atmos, disposal, and transit tube pipedispensers to tgui

### PR DESCRIPTION
**Pull request by neopythagorean**
## About The Pull Request

- Converts atmos, disposal, and transit tube pipedispenser (the stationary ones) dialogs to tgui.
- Creates the PipeDispenser react component
- removes the now unneeded Render proc for pipe_info
- removes old traditional ui procs
- gives atmos pipedispensers the ability to color pipes and dispense smart pipes
- Decomposes RapidPipeDispenser component a bit, to make the resuse of stuff like the color picker easier.

## Why It's Good For The Game

tgui good.

Also this now allows the atmos pipedispensers to take advantage of pipe colors and smart pipes.

tgui

## Changelog

:cl:
refactor: stationary pipe dispensers now take advantage of tgui
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I love you

**Comment by jlsnow301** [comment]
very clean js +1

**Review by stylemistake — APPROVED** [review]
Lazy copypasta, but no technical issues with PR. It was definitely possible to reuse UI bits instead of copying them.

**Comment by neopythagorean** [comment]
I can go ahead and modify it to do that.

**Pull request merged**
