### PR TITLE
Beds are not stools anymore

### LINKED ISSUE #12126: It takes 5 sheets of metal to make a swivel chair, deconning it returns one

### PR DESCRIPTION
**Pull request by phil235**
- Changes the paths of stools, beds and chairs. It is now obj/structure/bed/chair/stool. It makes much more sense since stools barely have any code of their own.
- Beds/chairs now have buildstacktype and buildstackamount vars to handle how many sheets of what they should drop on deconstruction.
- They also have a foldabletype var to handle folding into item (currently only used by roller beds) so that people can add foldable chairs in the future.
- Fixes swivel chairs not dropping the correct amount of metal sheets. Fixes #12126 
- Alien nests no longer drop metal upon ex_act().

### CODE REVIEW

**Comment by WJohn** [comment]
Oh my god. You really went and edited every single map, didn't you?

**Comment by MrStonedOne** [comment]
I think they mass find -> replace'ed all the maps

**Comment by Incoming5643** [comment]
If this isn't merged near instantly it will conflict 4eva

**Comment by Jordie0608** [comment]
Merger didn't work on MetaStation.v41H.dmm

**Comment by phil235** [comment]
@Jordie0608 Travis worked fine, what broke exactly?

**Comment by Jordie0608** [comment]
I mean the line diff.

**Comment by AnturK** [comment]
Janicarts probably could probably be just obj/structure/janicart they don't share much besides handle_rotation thing which could possibly be made atom/movable proc for all the buckled stuff.

:+1:  Anyway.

**Comment by Supermichael777** [comment]
uranium chairs when

**Comment by Razharas** [comment]
@phil235

**Comment by phil235** [comment]
I can't seem to fix merge conflicts, so I'm making a new PR.

**Pull request closed without merging**
