### PR TITLE
Labcoats: Roboticist unique labcoat, updated remaining labcoats 

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Gives the roboticists unique labcoats. Because why are geneticists allowed a unique labcoat but roboticists get a generic one?

So now, roboticists have the most extra of the labcoats to go with their jumpsuits. It even has shoulder pads!

robocoat_alt_colour_palatte

The rest of the labcoats have had a very mild tweak, and their icons now no longer use the ancient, janky labcoat sprites. You know, the ones with the fucked up outlining.

Oh also the virologist labcoat suggested it was somehow more protective against biological things. This is not true, so the labcoat has had it's description fixed.

(While I was here I fixed up some suit storage sprites related to the stuff that goes in labcoats, hehehe)

## Why It's Good For The Game

You either wear the morbid white and red labcoat or you're wearing the other morbid and red techpriest outfit. Or you're just wearing the jumpsuit because you're showing off the best/most snowflake jumpsuit on the station. 

There is no shortage of edge in robotics.

If none of these are your style, just go get a science labcoat.

Some of these sprites are quite old!

## Changelog
:cl:
add: Roboticist unique labcoat! Because you're worth it! Aesthetics!
fix: All other labcoats no longer utilize the oldest labcoat sprites we have for their icons!
fix: The virologist labcoat no longer lies about being more resistant to biological effects! Not that bio armor does anything in the first place.
fix: Some stuff that could be worn in the suit storage slot no longer shows pink! Hooray!
/:cl:

### CODE REVIEW

**Comment by Capsandi** [comment]
Isn't there a ban on alternate job uniforms in effect?

**Comment by necromanceranne** [comment]
This is their standard outfit, not an alternative outfit.

As an example, the techpriest outfit is an alternative outfit.

Another example is that the detective spawns with a brown trenchcoat and fedora, and the detective's noir outfit is an alternative outfit.

**Comment by wesoda25** [comment]
It looks more like the outfit from kill la kill than a lab coat

**Comment by Iatots** [comment]
Edgy. The white ones provide some nice contrast.

**Comment by necromanceranne** [comment]
robocoat comparison

Which ones would be better given the comparison?

**Comment by necromanceranne** [comment]
I've swapped over to the white version.

**Comment by Farquaar** [comment]
Yeah, black and red looks too syndi. White and red is much better.

**Comment by necromanceranne** [comment]
Funny you should mention that. Should I give the black one to lavaland scientists?

**Comment by TheBonded** [comment]
I like the white and red, looks like it came straight out of Space-Canada

**Review by Twaticus — APPROVED** [review]
good labcoat tweaks

**Pull request merged**
