### PR TITLE
Medipens can't have reagents removed from them anymore.

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

This will be needed for https://github.com/tgstation/tgstation/pull/82449 because this removes the machine's ability to make infinite chems.
Basically in https://github.com/tgstation/tgstation/pull/29139 they removed medipen's ability to have reagents injected into them, but never removed the ability to take reagents out.
You could take a syringe, remove all chemicals from a medipen, put the main ingredient in a medipen refiller, then refill. You could do this right now on live servers with an epipen for infinite formaldehyde.

This doesn't affect the hypospray.

## Why It's Good For The Game

Removes a way of infinitely making reagents with a medipen refiller and also removes a dumb mechanic.
You could take all chemicals out of an EHMS autoinjector, which removes the visual and feedback tell to the target that they've been injected, and even with 0 chemicals they get the disease anyways.
You could buy medipens as a miner, take the chemicals out, and put them in a syringe or pill that you can inject yourself instantly with.
You can take otherwise hard-to-get chemicals like fungal TB's 2-use cure injector, and make 40 cure pills instead.

## Changelog

:cl:
fix: You can no longer take chemicals out of medipens with a syringe.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
I’m not sure I understand the bug? So you can remove reagents from a medipen with a syringe, but then the medipen still injects the reagents even though it’s empty?

**Comment by zoomachina** [comment]
> I’m not sure I understand the bug? So you can remove reagents from a medipen with a syringe, but then the medipen still injects the reagents even though it’s empty?

Medipen refillers only need the "main" chemical to refill a medipen. If the pen has other chems in it, the refiller generates them itself. For instance, epinephrine medipens only need epi to be refilled, the rest (1u formaldehyde and 2?u sanguirite) is generated by the machine.
Because of that, if you remove reagents from a medipen by a syringe, you can put the "main" chemical in the refiller, use it and be left with a filled medipen and extra 1u formaldehyde and 2u sanguirite, just like that cholocate bar trick. Apparently, being able to get these chemicals in liquid form, which the machine generated as intended, is considered a bug.

**Comment by Profakos** [comment]
> I’m not sure I understand the bug? So you can remove reagents from a medipen with a syringe, but then the medipen still injects the reagents even though it’s empty?

Medipen refillers check for a primary reagent. If enough of its present, it will materialize its secondary reagents from thin air. If you extract all the reagents from the pen, you can keep on stockpiling the extra chems.

**Comment by JohnFulpWillard** [comment]
> I’m not sure I understand the bug? So you can remove reagents from a medipen with a syringe, but then the medipen still injects the reagents even though it’s empty?

The bug is that you can take reagents out of the medipen which is something we never take into account for balancing stuff. Mining pens for example are limited with a 15 second cooldown between use when in a fully pressured environment, but the whole thing would also fit in say a bluespace syringe, letting you bypass everything. For the case of EHMS, you can inject them without any reagents and still infect them, etc.

**Comment by Time-Green** [comment]
@JohnFulpWillard Ah, I thought there was a second bug unrelated to drawing that this was also masking. 

@zoomachina Ah, yeah okay that’s the infinite production I was confused about. That should also definitely be fixed, even if it’s somewhat nerfed by this fix (but scope and w/e)

**Comment by ExcessiveUseOfCobblestone** [comment]
> in my opinion this kind of lifts off the need to tirelessly grind the chems you want for a gimmick, not to mention this is just limited to duping of chems that are in medipens which none of are much of something balance breaking to use.

What do you think the balancer for chem is right now if not the time needed to make the chem at a good purity or to set up a factory (which ur bypassing here) or the power cost associated with the dispenser or all the chem factory machines (which you're also bypassing)?

It isnt good to see the actual job of chem to simply be the obstacle to getting your goodies, and not an important part of why chem has the options that it does from the get-go of the round.

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Comment by moocowswag** [comment]
you could still inject a monkey then gib them and grind their liver or whatever right.

**Comment by jughu** [comment]
> you could still inject a monkey then gib them and grind their liver or whatever right.
> 
> Not terribly easy but still a work around

This isn't the issue duping chems the issue is that they shouldn't be extractable because we put rare chems in easy gettable pens and it also voids the whole cooldown of miner pens on the station

**Comment by moocowswag** [comment]
> This isn't the issue duping chems the issue is that they shouldn't be extractable because we put rare chems in easy gettable pens and it also voids the whole cooldown of miner pens on the station

Ya you get the chem through a monkey and now you have it in a beaker/syringe/pill ready for use.

**Comment by Exester509** [comment]
> > This isn't the issue duping chems the issue is that they shouldn't be extractable because we put rare chems in easy gettable pens and it also voids the whole cooldown of miner pens on the station
> 
> Ya you get the chem through a monkey and now you have it in a beaker/syringe/pill ready for use.

That does expend the medipen, so it does fix things like the EHMS infection or whatever

**Comment by JohnFulpWillard** [comment]
at least penthrite wouldnt be extractable cause it would cause a heart attack and delete itself

**Comment by gueba14** [comment]
gotta ask how is it that you are now suposed to get Sanguirite? its  a rare chemical that sometimes pops up in the secret regeants recipies, i dont see anything in regards to that so i take it no one realized it

**Pull request merged**
