### PR TITLE
drones can be emaged to become EVIL

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
on getting emaged, a drone will get these laws:
```
"1. You must always involve yourself in the matters of other beings, even if such matters conflict with Law Two or Law Three.
"2. You may harm any being, regardless of intent or circumstance.
"3. Your goals are to destroy, sabotage, hinder, break, and depower to the best of your abilities, You must never actively work against these goals."
```
additionally, it loses the ability to vent crawl and stops being shy.

A drone can be reset by wrenching it, or you know.. just smash it.
## Why It's Good For The Game
I think it's pretty cool, drones are really rare and it's an interaction that makes sense.
## Changelog
:cl: grungussuss
add: drones can now be emaged to make them EVIL
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
With how low health they have I wouldn't mind them retaining the ability to vent crawl

**Comment by Sadboysuss** [comment]
> With how low health they have I wouldn't mind them retaining the ability to vent crawl

no it would be annoying as hell, especially considering they have AA and are a ghost role

**Comment by ZephyrTFA** [comment]
hard no

**Comment by MrMelbert** [comment]
Ftr when someone proposed this I wanted something more like what Paradise has https://tgstation13.org/phpBB/viewtopic.php?f=9&t=36076&p=727516&hilit=drone#p727516

**Pull request closed without merging**
