### PR TITLE
The Gateway to the Celestial Derelict immediately tells everyone what direction it's in from them

### PR DESCRIPTION
**Pull request by ChangelingRain**

### CODE REVIEW

**Comment by Xhuis** [comment]
100% disagree with this. It should at least be more ambiguous for people who aren't servants, and the occasional direction indication is meant to give a hint as to where it is, not just straight-up telling them.

**Comment by ChangelingRain** [comment]
The general response to the gateway is "where the fuck is it" and that's absolutely awful, nobody enjoys trying to use what is basically a random-announce pinpointer to find the gateway.

**Comment by Xhuis** [comment]
Ehhhh. I still don't like it, but I'll humor you and let this go through.

**Comment by ChangelingRain** [comment]
If you get me interesting sprites, like fullscreen overlay things, for gateway directions I'll totally do that instead.

**Comment by Xhuis** [comment]
\>implying I can sprite
ehh, i'll try

**Pull request merged**
