### PR TITLE
A few nerfs to cult items.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Nerfs a lot of cult items.
Cult dagger.
-Force 15 -> 12
-Throwforce 25 -> 15
Cult sword & ghost sword
-Force 30 (19) -> 18 This is still nullrod levels of damage and you still have a whetstone
Normal armor
-Melee 40 -> 30
-Laser  40 -> 20
Shielded armor
-Melee 50 -> 40
-Bullet 40 -> 30
-Laser 50 -> 40
Cult spear
-Throwforce 40 -> 30
-Throwing now does knockdown instead of paralyze
Mirror shield
-Throwing now does knockdown instead of paralyze
Unholy water
-Now heals cultists around 25% less.
-Now deals stamina and a bit of fire damage to non cultists instead of basically murdering people

## Why It's Good For The Game

Normally strong antag gear is highly restricted but cult somehow seems immune to that. With stuff like flashbang dragging and other security cheese being slowly removed, cult also needs a squish on their stats. A lot of these values are just hilariously high and this changes that.

Cult currently has a way too easy time to just go loud and even a single cultist is pretty scary due to there many ranged stuns and high damage output.

This is by no means a fine tuned balance change.

I'm perfectly willing to discuss the exact numbers of this.

## Changelog
:cl:
balance: A lot of cult items have been nerfed.
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
How much damage does the cult whetstone add on?

**Comment by nemvar** [comment]
5. Which still brings the swords above airlock smashing level.

**Comment by Dawson1917** [comment]
Maybe the swords should do 20 damage. A summonable esword for every cultist is stupid, but the whetstones requiring a forge means they are actually pretty underused in cult rounds. A 20 damage sword feels OK to me and so is going the extra mile for +5 damage. Either way it'd still be 10 less damage than what it currently is

**Comment by nemvar** [comment]
The thing is that I want people to actually use the items and stuff that cult has access to instead of just murderhoboing with their gamer gear that's already strong enough. Cult will be fine with 18 damage bulky weapons and you should do the extra step is you want an extra good weapon.

20 is also a really meaningful number for damage because it means that two hits apply slowdown instead of three if the target is unarmored.

**Comment by Dawson1917** [comment]
To me the limiting factor of making whetstones has always been the cooldown for each forge. It's like what, minutes?
I don't doubt cult will still be fine, since they just need to stun > bash as usual while murdering as always. Nearly halving the damage of their strongest weapon is pretty intense. I see your point about damage slowdown though. Should both this and your bola nerf PR go through, cultists will have a better reason to use the bola that spawns alongside their sword and armor to apply slowdown before chopping someone up.

**Comment by Tlaltecuhtli** [comment]
cult spears are never used i dont see why nerf them

**Comment by FloranOtten** [comment]
Halving the damage on the cult sword seems overkill. Maybe reduce it to 20?

**Comment by dr-bee** [comment]
How about removing the cult restriction on cult weapons. If cultists get to steal guns crew members should be able to steal sweet, sweet swords from cultists without taking brain damage. Or pick up bolas without being stunned.

**Comment by necromanceranne** [comment]
Finally cult gets its shit kicked in numbers wise and yet they will still likely be as strong as ever since most of this isn't what makes cult strong. It's just stuff piled on top of their actual strengths.

Also cult had 40 laser armor that's better than most sec gear jesus fuck. How did they get away with that for so long.

**Comment by Tlaltecuhtli** [comment]
cult swords can be turned into claymores by chaplain already

**Comment by CPTANT** [comment]
Loud cult is a lot more fun than them just hiding in maint converting the entire crew.

**Comment by InsaneHyena** [comment]
Cults needs nerfs and changes to save the game mode from itself, and this is a good start.

**Comment by optimumtact** [comment]
it's all robustins fault, I honestly believe cult is completely ruined.

It's a confusing tonal mess of a gamemode because it's just rev under the hood, so everything added to try to differentiate it is just garbage.

**Comment by necromanceranne** [comment]
This is also not targeting the bits that makes it a mess either. While this helps, we still have a cult that can pull victories from absolute nothing even while there is a significant difference in cult numbers against living crew. You could argue the same of revs but at least revs requires rebustness to pull that off, not just have that handed to them on a silver platter.

**Comment by Akrilla** [comment]
works well with baton change :sunglasses:

**Comment by Swagile** [comment]
None of this is what makes cult so good.

Its blood boil, empower rune giving you 2 stuns, 1 EMP, 1 teleport to get out of dodge if surrounded / mobbed, blood rites, and constructs (making AI and borgs pathetic, which ironically enough is half the advantage of crew; AI outs the spots cult is, immensely narrowing down the actual location of the cult base, allowing you a chance to actually fight cult before they narsie because they grow so quick due to stun magics).

You also forgot about the flag robe that gives you meth speed with very little demerits, allowing quick converts.

**Comment by nemvar** [comment]
You got that wrong, that are the thing that are on my shitlist and probably get removed completely instead of getting nerfed.

Possible future nerfs would include:
Removal of blood boil
Removal of spirit realm
Removal of most soulstone gibbing except for the cult target
Removal of shades counting for invoking
Removal of flag robes, but they will probably get some kind of replacement
Removal of the EMP spell or at least making it take some time to cast
Shuttle curse taking having some invoke time and displaying the location of the caster.
Around 30% less stun time on the stun spell, silence duration feels about right
Making the teleport spell and runes no instant
Around a 50% longer summon time

All of those features listed make this gamemode extremely unfun to play as crew.

The point is that cultists shouldn't have it easy. A 50 50 winrate isn't we should strive for.

**Comment by optimumtact** [comment]
I think I should find someone willing to completely tear cult down and rework it.

**Comment by Akrilla** [comment]
Cult could be so cool given some fundamental changes... From how well fleshed out it is, it’s a shame it’s just a fancier revs.

**Comment by Swagile** [comment]
> 
> 
> You got that wrong, that are the thing that are on my shitlist and probably get removed completely instead of getting nerfed.
> 
> Possible future nerfs would include:
> Removal of blood boil
> Removal of spirit realm
> Removal of most soulstone gibbing except for the cult target
> Removal of shades counting for invoking
> Removal of flag robes, but they will probably get some kind of replacement
> Removal of the EMP spell or at least making it take some time to cast
> Shuttle curse taking having some invoke time and displaying the location of the caster.
> Around 30% less stun time on the stun spell, silence duration feels about right
> Making the teleport spell and runes no instant
> Around a 50% longer summon time
> 
> All of those features listed make this gamemode extremely unfun to play as crew.
> 
> The point is that cultists shouldn't have it easy. A 50 50 winrate isn't we should strive for. Cultist SHOULD use at least some crew equipment for their fight, instead of having an inbuilt answer to everything. What is the value in converting certain key targets if you already have access to almost everything with just your base mechanics?

Based.

Though some of these could stay, like spirit realm; its got clear merits and demerits.

**Comment by bigfatbananacyclops** [comment]
cult spears? Isnt that some clockwork stuff

**Comment by ExcessiveUseOfCobblestone** [comment]
Please someone make a HoG rework under the guise of Cult rework

**Comment by Shadowflame909** [comment]
Cult went from wizards to soldiers.

I think they should be very glass cannon-like, as mages are always like.

Dunno why this stuff isn't being yanked out entirely in favor of a more stealthy and actual cult. Watching and tinkering with things in the shadows.

**Comment by nemvar** [comment]
I really hope someone really does something with cult.

**Pull request closed without merging**
