### PR TITLE
Waypoint Finders now properly pull living playtime

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request

There is no "Living" job in GLOB.exp_jobsmap so the proc will always return -1

## Why It's Good For The Game

muh pocket slot

## Changelog
:cl:
fix: Players who are old (and wrinkly) will no longer receive the waypoint unless they have the quirk now.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
I was wondering why my 200+ hour-having ass was starting with a pinpointer.

**Comment by kriskog** [comment]
Fix is here too  #48616

**Comment by MrPerson** [comment]
Although this gives me an idea for Leif Erickson day

**Comment by cacogen** [comment]
thanks

**Review by kriskog — APPROVED** [review]
This is a better fix :+1:

**Comment by Tharcoonvagh** [comment]
So many bots

**Pull request merged**
