### PR TITLE
Bane AI

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
**Bane?**
111376376-9cc1ec80-865c-11eb-9018-d32a130c97e5

## Why It's Good For The Game

We take Gotham from the corrupt! The rich! The oppressors of generations who have kept you down with myths of opportunity, and we give it back to you...the people...Gotham is yours. None shall interfere, do as you please!

## Changelog
🆑
add: Bane AI
/🆑

### CODE REVIEW

**Comment by Timberpoes** [comment]
Closing Goof PRs is about the only joy I get in life.

**Comment by Iamgoofball** [comment]
@Timberpoes Excuse me, but
1. 24 hour rule
2. I have enough GBP for this PR.

**Comment by tralezab** [comment]
The powerful will be ripped from their decadent nests, and cast out into the cold world that we know and endure.

**Comment by spessbro** [comment]
why is goof pr'ing from arm's branch?

**Comment by Iamgoofball** [comment]
@spessbro armhulen didn't have the GBP, i did

**Comment by 81Denton** [comment]
he didn't merge so good

**Pull request closed without merging**
