### PR TITLE
Adding Clonepod to Supply Blacklist, Fixes #12979

### LINKED ISSUE #12979: Possible to Use Cloner to Get to Centcomm
If you build a cloner on the supply shuttle then upgrade it so you can autoprocess bodies, it's possible to get to Centcomm.

Just build the cloner on the shuttle, scan yourself with autoprocess on, send the shuttle away and kill yourself, then enjoy being at Centcomm.

Screenshots:
https://i.imgur.com/1jZDcy4.png
https://i.imgur.com/xiQmjKD.png
https://i.imgur.com/7iGMnjQ.png
https://i.imgur.com/zACw2iK.png
https://i.imgur.com/HLgFfWr.png (Gear change to open doors, but you could also hack them).

~~As an aside, I'm pretty sure this is fixable by just blacklisting */obj/machinery/clonepod* in */code/controllers/subsystem/shuttles/supply.dm* except I can't test it myself because every time I try to compile the code (for most anything I do actually), I just get a huge string of errors ( http://i.imgur.com/ypzH6iO.png ). If anyone could show me where I could go to help resolve this, I would **massively** appreciate it.~~

Adding the clonepod to the blacklist does work, suppose I'll put in a PR with the fix now.

### PR DESCRIPTION
**Pull request by Yolopanther12**
Added clonepod to the supply shuttle blacklist, fixing issue #12979 
Fixes #12979

### CODE REVIEW

**Comment by lordpidey** [comment]
What about replica pods?  Are those also blacklisted?  If not, this would be a good place to fix them too.

**Comment by phil235** [comment]
@lordpidey Don't replica pods need someone to harvest them to spawn the mob?

**Comment by PKPenguin321** [comment]
phil's correct

**Comment by ike709** [comment]
"Fixes #12979" needs to be in the OP

**Pull request merged**
