### PR TITLE
Realigns the Space Station 13 logo

### PR DESCRIPTION
**Pull request by Incoming5643**
For a long time now, a very long time, probably even before we forked, there's been a problem, a huge problem, a problem so huge that it impacted the lives of every single spaceman who ever played this game:

d10_icon

THE GODDAMN LOGO IS MISALIGNED

---

But not anymore

341s6

Fixes the problem for both box and meta

### CODE REVIEW

**Comment by SconesC** [comment]
Mother of god

**Comment by Dorsisdwarf** [comment]
Never noticed it

**Comment by Serithi** [comment]
What is this sorcery

**Comment by xxalpha** [comment]
thank you

**Comment by JJRcop** [comment]
Travis couldn't retrieve BYOND in one of the 3 tests, compiles fine on the other two.

**Comment by Miauw62** [comment]
ill restart the build

**Comment by MrStonedOne** [comment]
Your pr changes random unrelated things in the map.

Please see to that.

**Comment by Incoming5643** [comment]
I'm not sure it actually does.

The old logo was 8 tiles wide and 2 tiles high, while the new centered version is only 7 tiles wide (which is why we can center it). Because of this the entire logo turf structure moved a tile to the left and the two leftmost pieces of that structure (L15 and L16) ceased to be a thing on the map. That, in combination with the fact that things like wires and nodes for bot pathfinding are now under tiles with different but prexisting icon states, lead to some internal shuffling of tile definitions but I don't think anything actually changed, the map just took advantage of the fact that some shorter map tile designations were freed up.

**Comment by Anonus** [comment]
Fucking finally. How many points do you get for fixing this, lots?

**Comment by RemieRichards** [comment]
@Anonus none, it's not a reported issue, and to report it now would also be worth 0 points.

**Comment by Incoming5643** [comment]
I have a bad habit of fixing old shit no one ever bothered to report. That said I'm not really "going for points" because my laptop is a toaster and can't really benefit from any of the prizes.

**Comment by Thunder12345** [comment]
This always bugged me, but never enough to bother fixing it

**Comment by RocKeD** [comment]
Hurray we are saved!!

**Comment by Incoming5643** [comment]
There aren't, see https://github.com/tgstation/-tg-station/pull/9575#issuecomment-104063620

I'm looking at the tgstation incinerator right now and nothing looks different

**Comment by RocKeD** [comment]
Why are these lines modified?
https://github.com/tgstation/-tg-station/pull/9575/files#diff-6fa39aae44907c93c83869eeff8ad87bR1982
https://github.com/tgstation/-tg-station/pull/9575/files#diff-6fa39aae44907c93c83869eeff8ad87bR2629

**Comment by Xhuis** [comment]
;_;7

**Pull request merged**
