### PR TITLE
Removes the IRC from the README

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request

Removes the IRC link from the README.

## Why It's Good For The readme

ITS DEAD. ITS BEEN DEAD.
I bet you like 90% of the new players we get that open up github have no fucking clue what IRC even is. Does anyone even ask if we have an IRC server anymore? Why would they care that there *was* an IRC server. It's time we move on.

## Changelog

removes the IRC link

### CODE REVIEW

**Comment by Iamgoofball** [comment]
no

**Comment by Bawhoppen** [comment]
This makes me genuinely so sad

**Comment by optimumtact** [comment]
This should be done as the IRC is not actively watched and anyone asking for help there won't get it.

**Comment by Mothblocks** [comment]
2022 is the year of the coderbus irc baby

**Comment by esainane** [comment]
F

**Comment by tralezab** [comment]
The real question you should be asking yourself is: Would MSO not revert this immediately?

**Comment by Mothblocks** [comment]
Probabl y not

**Comment by Iamgoofball** [comment]
end of an era

**Comment by Bawhoppen** [comment]
https://www.youtube.com/watch?v=WChTqYlDjtI

**Pull request merged**
