### PR TITLE
Gives the colossus voice of god, adds language support to voice of god

### LINKED ISSUE #33650: Runtime when AI uses Voice of God spell
> [11:52:56] Runtime in ,: bad arg name 'spans'
>   proc name: say (/mob/living/silicon/ai/say)
>   usr: Emerald (coiax) (/mob/living/silicon/ai)
>   usr.loc: The floor (171,134,2) (/turf/open/floor/plasteel/neutral/corner)
>   src: Emerald (/mob/living/silicon/ai)
>   src.loc: the floor (171,134,2) (/turf/open/floor/plasteel/neutral/corner)
>   call stack:
>   Emerald (/mob/living/silicon/ai): say("HI THERE", null, null)
>   voice of god("HI THERE", Emerald (/mob/living/silicon/ai), /list (/list), 1, 0, 1)
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): cast(null, Emerald (/mob/living/silicon/ai))
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): perform(null, 1, Emerald (/mob/living/silicon/ai))
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): perform(null, 1, Emerald (/mob/living/silicon/ai))
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): choose targets(Emerald (/mob/living/silicon/ai))
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): Click()
>   Voice of God (/datum/action/spell_action): Trigger()
>   Voice of God (/obj/screen/movable/action_button): Click(null, "mapwindow.map", "icon-x=16;icon-y=6;left=1;scre...")

1) Be an AI.
2) Grant Voice of God spell.
3) Try using it, it runtimes.

@XDTM

### LINKED ISSUE #33776: Sentient colossi do not speak with voice of god
[Round ID]: # 80632

THIS IS A TERRIBLE OVERSIGHT, @XDTM PLZ FIX IMMEDIATELY

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
fix: If a colossus is somehow able to gain sentience, they'll speak with the Voice of God instead of a wimpy, human voice.
tweak: Voice of God now uses your default language. The effect is the same regardless of language, but it can be made incomprehensible to listeners.
fix: AIs can now properly use the voice of god spell. It still does not work over radio, but better than nothing.
/:cl:

Fixes #33776 
Fixes #33650

### CODE REVIEW

**Comment by coiax** [comment]
Wait, so if you can't hear the Voice then you're immune, but if someone tells you to DANCE LIKE A MONKEY in Slime, and you don't understand, then you still dance?

**Comment by XDTM** [comment]
The lizard brain inside you knows better than not to obey the command, understood or not

**Comment by coiax** [comment]
But that command is stopped by wearing ear muffs?

**Comment by XDTM** [comment]
Then it never reaches your brain!

**Comment by coiax** [comment]
Don't mention that people have lizard brains, they might vote down the PR.

**Comment by Buggy123** [comment]
>lizard

Gas

**Comment by Anonmare** [comment]
>lizard brain

🔫  😠 💢

**Comment by Doppeltongue** [comment]
Shouldn't something that's a "voice of god" actually be heard in all languages?

**Comment by XDTM** [comment]
I think an Ancient God declaring something in a mysterious eldritch language is makes more sense than it being translated in plain old space english in your head for your convenience

**Comment by Rinoka** [comment]
Watch all the miner powergamers swap to lizards so they can run around hissing at people when they get VoG loot.

**Comment by AdamElTablawy** [comment]
Wait, does the simplemob collosus also invoke the voice of god when it talks with this change? Because one of its lines is 'die', which hurts you if used with the voice of god.

**Comment by ChangelingRain** [comment]
No, since all of those lines are actually visible messages.

**Comment by PromethTK11** [comment]
>lizards

**Pull request closed without merging**
