### PR TITLE
Adds some default vscode tasks

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Adds some default vscode tasks for byond and tgui builds.
image

A clarification on this is that the file is still included in the .gitignore so local changes would still be possible and untracked by git. This would just be defaults for freshly downloaded repos.

### CODE REVIEW

**Comment by optimumtact** [comment]
I hate when projects touch my editor configs

**Comment by actioninja** [comment]
This and settings.json are local files that your global settings will be overwritten by. On top of that they're in the gitignore so after an initial clone/modification you would be able to edit them to your local liking as you please.
I'm looking into alternatives though, this was just the nuclear option due to a lack of proper yarn task providing plugins.

**Comment by stylemistake** [comment]
> file is still included in the .gitignore so local changes would still be possible and untracked by git
That's not how it works!

**Comment by actioninja** [comment]
That's not how I remember gitignore working, but good to know and in that case I'll look into other methods.

**Pull request closed without merging**
