### PR TITLE
Added item cup of coffe. does nothing. handed out by gms at random

### PR DESCRIPTION
**Pull request by Apogate**
Added item cup of coffe. does nothing. handed out by gms at random

the build needs this. please merge. regular coffee doesn't cut it.

### CODE REVIEW

**Comment by Cheridan** [comment]
?

**Comment by coiax** [comment]
I thought this was going to be a prayer cookie, but no, it's some sort of misspelled coffee meme

**Comment by MMMiracles** [comment]
life's greatest mystery

**Comment by Cheridan** [comment]
thank you for your contributions but at this time coffee is a very sensitive subject

**Comment by Apogate** [comment]
please for my child. dont do this

**Comment by optimumtact** [comment]
Hello I've detected a possible meme

**Comment by Aloraydrel** [comment]
Drink the coffee

**Pull request closed without merging**
