### PR TITLE
Unbreaks Tgui for people running < IE11 by reverting "Update all of tgui's dependencies except ractive"

### PR DESCRIPTION
**Pull request by Incoming5643**
I've given it <s>three weeks</s> 18 days and all I can really tell about this pull is that:

1. There are indeed people playing on our servers who cannot run IE11. This would be anyone running Windows XP or using a virtual machine to play in another OS. I have personally talked to more than a few people who are in either one of these situations, and can confirm that there are people playing our game with even worse computers than me.

2. Nothing's actually been done to build on #21958  for <s>three weeks</s> 18 days. It hasn't validated its worth. Big info intensive Tgui windows like Engineering Power Monitoring Console are still slow to load. Whatever benefits these updated dependencies are bringing, they seem pretty marginal, and carry a cost to our players.

3. Updating these dependencies broke no frills mode, which was [specifically designed to allow people with less than IE11 to still use TGui](https://github.com/tgstation/tgstation/blob/master/tgui/src/components/warnings.ract#L26).

I'm sure there'll come a time when it makes sense to move forward with these dependencies but for now the value they bring doesn't match up with the cost they impose.

:cl:
bugfix: TGui consoles should once again work on systems not running Internet Explorer 11.
experiment: If you are capable of running IE11 (i.e. you have Windows 7 or above) you should upgrade to IE11. Don't worry we don't actually expect you to USE internet explorer, but the game makes use of its features. Just a little future proofing.
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
I hope you recompiled tgui, because you can't rely on the revert to do it for you

**Comment by Incoming5643** [comment]
I can't say I did, why wouldn't this work? The state it's being returned to was valid at the time.

If it's not going to work tell me what I should be doing to recompile it.

**Comment by Cyberboss** [comment]
If there have been any modifications to tguis since that commit it will have to be recompiled as tgui.css and tgui.js will be wrong because they are both 1 line. There are batch files in the tgui folder to install the dependencies and build it.

**Comment by Incoming5643** [comment]
It's my understanding that if either of those one line files had changed in the interim between then and now the auto revert github button wouldn't have been available. The last change to both tgui.css and tgui.js was part of the PR being reverted here.

I will check to make sure it works locally sometime tonight or tomorrow.

**Comment by Iamgoofball** [comment]
@oranges

**Comment by Cyberboss** [comment]
T-That's not @optimumtact goof...

**Comment by Mervill** [comment]
You %100 need to recompile tgui if your reverting this. `tgui.css` and `tgui.js` are marked as binaries (the contents are not actually diff'd by git).

**Comment by optimumtact** [comment]
if you want to continue to flounder around in a backwater of support be my guest, but I'll be redirecting any and all tgui complaints to you in the future.

**Comment by Incoming5643** [comment]
But updating the dependencies didn't fix any of the complaints? I mean if there was a big difference in performance maybe I'd understand, but there just isn't.

**Comment by Crushtoe** [comment]
Direct all complaints to me if you want. If it brought no increase in maintainability or speed and only alienated a large part of our player base, then it seems sensible to revert it.

**Comment by Incoming5643** [comment]
I wouldn't say large parts, maybe "a few dozen people". It's really nasty because these people are fans, they didn't just give up and leave when that pull went live, they're working around this even as more and more things are ported to TGui. People shouldn't get left out in the compatibility cold without a really good reason.

**Comment by AnturK** [comment]
The performance improvements stem from ractive update to 0.8 which was not done. So there shouldn't be really any noticeable differences so i don't really get these "no visible improvement" arguments.

**Comment by JJRcop** [comment]
@Cyberboss Both tgui.js and tgui.css were reverted to their pre-dependency-upgrade state, because both files are tracked by git, no need to worry.

**Comment by Mervill** [comment]
The update to ractive 0.8 was posponed as we discussed exactly how we wanted to move forward with tgui (there was talk of replacing ractive with something else IIRC).  I ultimately got distracted by other things and progress stalled completely.

If the plan is still to upgrade to ractive 0.8 "at some point (™)" then this is really just postponing the inevitable, but I/we may not get around to it for a while so if it's preferred we can revert this now and it will return when ractive is finally upgraded.

**Comment by MrStonedOne** [comment]
Honestly.

I think building a tailored made framework might be the best way to do it. Use data-attribute and/or id fields for identifying updates, and parse the template server side once rather than make all the clients do it. ractive was too much, and honestly we aren't saving anything important by making the clients parse the template now that byond has proper string/list conversion procs

The only reason to use the javascript side templates is now gone, so why are we still trying to make toasters do frequent mvc calculations?

**Comment by MrStonedOne** [comment]
also, incoming, you would need to re-compile tgui. I honestly don't know why it even let you revert.

**Comment by Mervill** [comment]
There are dozens, if not hundreds of good ways to redo this, the main problem is that the first step after establishing what the new process is is to rewrite all the existing tgui in the new process, and nobody wants to do that.

Maybe with the feature freeze I might get bored enough to do it.

**Comment by Mervill** [comment]
@MrStonedOne we should talk later this week about what you just suggested though, since it sounds like something I'd be up for doing. Just need to be a tad less jetlagged

**Comment by Incoming5643** [comment]
rebuilt TGui using the older dependencies, but I still need to check to be sure that it works properly in game.

**Comment by Incoming5643** [comment]
In a comical twist of fate, I think my machine isn't capable of compiling tgui.

I run install_dependencies.bat and get everything except a few supposed optional things just fine.

I run build_assets.bat and it seems to complete fine.

The tgui in game looks fine, it just never updates.

**Comment by ChangelingRain** [comment]
Which tgUI isn't updating? Because if it's apcs then that's probably a bug.

**Comment by Mervill** [comment]
Which optional dependencies? tgui is so broken some of the broken dependencies actually aren't

**Comment by Incoming5643** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32
"})

**Comment by JJRcop** [comment]
I built it on my machine and git is not detecting any differences, so that means that the .js and .css files that are in this PR were reverted correctly.

**Comment by Mervill** [comment]
@Incoming5643 Yeah those are the broken-but-not-broken dependencies

**Comment by Incoming5643** [comment]
It's possible that tgui just doesn't work right with my test server for some reason? I've never had a reason to check before.

Maybe a test merge can confirm if this works or not

**Comment by Incoming5643** [comment]
Unfortunately the test merge revealed the problem wasn't local, in its current form this breaks updates.

**Comment by Incoming5643** [comment]
Updated NPM and reran install_dependencies.bat.

It uninstalled a lot of previously installed dependencies and left me with many more error messages relating to what sounds like really basic dependencies like "paths-js". Rereruning install_dependencies.bat refuses to install the things it took away.

JS is a silly beast and I don't know how to placate it.

**Comment by Incoming5643** [comment]
oh well, then maybe I'm on the right path. Let me check.

**Comment by Incoming5643** [comment]
@Mervill Probably going to have to take you up on your offer to do the revert yourself.

**Comment by vista-** [comment]
mergebegging right now

**Comment by Mervill** [comment]
It's been at the bottom of my list since Incoming asked me to do it... I guess I should do it

**Comment by Cyberboss** [comment]
@Mervill All on you, I couldn't do it

**Comment by Mervill** [comment]
I know, I'm sorry I've been putting it off

**Pull request closed without merging**
