### PR TITLE
Gives dragon swooping a non-cult sprite marker.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
KILLME

It ain't anything fancy, but it gets the job done.

### CODE REVIEW

**Comment by kevinz000** [comment]
self portrait tbh

**Comment by Xhuis** [comment]
I still think that it should be a big red circle with the words "___U DED___" inside of it.

**Comment by TechnoAlchemisto** [comment]
I spent a solid half hour trying to freehand a skull until I had a mental breakdown

**Comment by Kromgar** [comment]
Totally not Khorne's symbol

**Pull request merged**
