### PR TITLE
Make ChangeTurf to keep air by default.

### LINKED ISSUE #44623: Floor tiles can produce infinite air
Round ID: 110897
Placing or crowbar'ing up floor tiles causes them to release air for some reason, and is repeatable infinitely.
This has actually been around for months but I just never got around to reporting it.

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
ChangeTurf keep air by default if no flags sended on ChangeTurf().
fix#44623

## Changelog
:cl:
fix: air issues on changing turfs
/:cl:

### CODE REVIEW

**Comment by XDTM** [comment]
Isn't it better to set the flags arg to CHANGETURF_INHERIT_AIR on the proc definition? If you make `!flags` result in CHANGETURF_INHERIT_AIR, you can't have an empty `flags` intentionally, if i read it right.

**Comment by MrPerson** [comment]
XDTM is right, but changing the default arg won't work either. I believe in BYOND there is no difference between someproc() and someproc(null) assuming someproc() has a default argument. And even if it did work, it would create different behavior depending on if the proc was called with a flag argument or not (no flags means it inherits air, any flags means it doesn't inherit air unless told to), which would definitely cause bugs.

Best solution is probably to invert the logic and change the flag to CHANGETURF_NO_INHERIT_AIR.

**Comment by Dennok** [comment]
if you want empty, you can sent something not a flag or i can add empty flag. Or another way, just add to all places where we have empty changeturf and aff flag to it

**Comment by vuonojenmustaturska** [comment]
Don't add an unused flag, just flip the meaning of the flag if you're making it the default. Which I don't recommend at all because it will likely create a lot of atmos-related bugs. The real fix would be to find the floortile's placeontop and put the flag in there.

**Comment by XDTM** [comment]
It's true that most changeturfs should replace air, though. Ideally a refactor would set it as default and manually check the existing ones.

**Comment by SpaceManiac** [comment]
IMO the default should be keeping air. Map loading is the exception.

Default arguments are only taken when `null` is passed or the argument is omitted (implicit null).

**Comment by ninjanomnom** [comment]
Making this default is fine but we'll need to test this

**Comment by optimumtact** [comment]
testing time

**Comment by Cyprex** [comment]
TheChosenEvilOne suspects that this breaks atmosphere on shuttles

**Comment by Dennok** [comment]
ohhh, no

**Comment by Cyprex** [comment]
TheChosenEvilOne mentioned that building tiles with an RCD or in Buildmode is also broken. Testing this I've found that both leave the air as immutable/space too.

**Comment by Dennok** [comment]
Yes, i find problem. When it keep air, it keeps it type. type. Just need add Copy
Problem like in cloning quantum linking.

**Pull request merged**
