### PR TITLE
Alien icon update fixes

### LINKED ISSUE #7849: Editing alien icon .dmi paths reverts to what it was a second later.
As an admin, if you try to edit an alien's icon .dmi location to something else or something you made (in my example to try out different looks and castes), it will revert back to what it was almost immediately. This doesn't seem to happen with humans.

### LINKED ISSUE #8321: Aliens can't attack turrets.
Pretty irrelevant since you can slash APC but aliens can't attack turrets.

-"You don't have dexterity.. etc"

### LINKED ISSUE #8630: Alien shifting from sleeping and pounce stance toggle is very slow to happen.
When you rest as an alien, you're given a pixel shift of 6 about a full second after you've lied down (which looks really odd). Likewise toggling hunt on will take about a second to actually turn on or off visually, though usage is instant.

### LINKED ISSUE #8714: Mice are annoying as fuck now
Mice are mobs now so if you're not on help intent you just end up pushing them which makes running through maint really annoying

### PR DESCRIPTION
**Pull request by phil235**
- Giving simple_animal their own version of update_canmove(). This fixes small animals' density being always set to 1 by life(). Fixes #8714.
- Fixes pixel y shift when lying down as an alien.
- Removes the no longer needed slime/update_icons.dm and larva/login.dm
- Fixes alien icon var being reset to its initial value during every life(). I added an alt_icon var to aliens to achieve that. Fixes #7849 
- Fixes alien humanoid no using the unconscious icon instead of their sleeping icon when sleeping.
- Fixes many instances of lying mob getting shifted up (pixel_y reset to 0) by adding a lying_pixel_offset var to mob/living.
- Removes the delay when toggling resting, sleeping and pouncing, the mob sprite will now update instantly. Fixes #8630 
-  Fixes alien and simple animal being unable to attack porta_turret. Fixes #8321
- Making a take_damage() proc to update the turret's health.
- Fixes porta_turret being broken by severity = 1 explosion and deleted by severity = 3 instead of the other way around.
- Fixes soda can being named 'drink' in tablecraft window.

### CODE REVIEW

**Comment by Xhuis** [comment]
This will make @WJohn happy. Might conflict with #8629?

**Comment by phil235** [comment]
Possible yeah, but the conflicts won't be too big, I'll let your PR go first and I'll fix the possible conflicts.

**Comment by Xhuis** [comment]
cool, thanks

**Comment by WJohn** [comment]
AW YISS.

ALIEN. ICON. EDITING.

**Comment by WJohn** [comment]
Since the minor alien changes PR was closed temporarily due to conflicts, you should be able to merge this and your other alien related PRs without any problem.

**Comment by Jordie0608** [comment]
This is still merge conflicting.

**Comment by phil235** [comment]
I'll fix the conflict tonight.

**Pull request merged**
