### PR TITLE
Removes the frog mask for being a violation of server policy

### PR DESCRIPTION
**Pull request by Iamgoofball**
The active permaban appeal of Woross has made it clear that netspeak isn't ok.

### CODE REVIEW

**Comment by lzimann** [comment]
\>server

**Comment by Qustinnus** [comment]
never change goof man

**Comment by kevinz000** [comment]
SAY IT WITH ME
😂

**Comment by BeeSting12** [comment]
SERVER AND CODEBASE SEPERATION IS ABSOLUTE

**Pull request closed without merging**
