### PR TITLE
Shaft miner suit sensors default to tracking

### PR DESCRIPTION
**Pull request by ghost**
Why was this never a thing, why force shaft miners to clutter their inventory with GPS, especially now that telesci is gone. whyyyyy

### CODE REVIEW

**Comment by Actionb** [comment]
Unless you include a crew monitoring console on the asteroid along with this, it is of no use. Suit sensors are only tracked on the z-level they are in: leave station z-level, vanish from the sensors list.

**Comment by paprka** [comment]
That's pretty awful. Oh well.

**Comment by Deantwo** [comment]
So add a kind of relay on the Mining Station? Like there is for the TCOM?

**Comment by paprka** [comment]
Perhaps, we need something to replace telesci recovery for miners.

**Comment by Deantwo** [comment]
Well right now we don't even know if the miners are dead.
So we don't know when they need saving unless they scream before being attacked or miss a radio check in.

**Pull request closed without merging**
