### PR TITLE
Adds the high quality gamemode rod madness

### PR DESCRIPTION
**Pull request by lzimann**
Did this mainly to be test merged so it's pure copypasta from meteor mode.
The gamemode is basically meteor mode but with rods instead of meteors.

### CODE REVIEW

**Comment by bobdobbington** [comment]
literally merge this shit immediately best new gamemode since traitor

**Comment by Bawhoppen** [comment]
add one with rockets too

**Comment by Crushtoe** [comment]
When rod encountered a chicken, the chicken died.

A+

**Comment by Xhuis** [comment]
You might be able to make this a subtype of meteor and just override its `process()`. Meteor's process says this:
```
/datum/game_mode/meteor/process()
	if(nometeors || meteordelay > world.time - round_start_time) 
		return
	
	var/list/wavetype = meteors_normal
	var/meteorminutes = (world.time - round_start_time - meteordelay) / 10 / 60
	
	
	if (prob(meteorminutes))
		wavetype = meteors_threatening

	if (prob(meteorminutes/2))
		wavetype = meteors_catastrophic

	var/ramp_up_final = Clamp(round(meteorminutes/rampupdelta), 1, 10)

	spawn_meteors(ramp_up_final, wavetype)
```
So it should be simple to make the rod madness' process use different procs and just spawn rods all over the place.

**Comment by anconfuzedrock** [comment]
are these the rods that loop so it destroys the exact same thing errytime

**Comment by lzimann** [comment]
rod looping is random

**Comment by AdamElTablawy** [comment]
oh boy

a gamemode about long, hard rods penetrating things

exactly what we needed

**Comment by KorPhaeron** [comment]
doesnt need to be opened to be test merged

**Comment by CitrusGender** [comment]
merge this pls

**Pull request closed without merging**
