### PR TITLE
Adds the Coroner (to Mafia)

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

- Adds the Coroner, which works like the old Chaplain does
- Chaplains now have the ability to hear dead players from dead-chat, by having those players orbit the Mafia panel. This is now also said in their UI.
- Changelings no longer have .j to talk to eachother, they now just telepathically speak to eachother during the day. Someone could make up some lore-reason as to why, I just thought they should be standardized with the Chaplain.
- Updates in-game icons for characters to match their new clothes.
- Added shoes to Traitors and Obsessed outfits, because they were missing while I was trying to get their icons.
- Fixes the Mafia UI showing a 'new game' if you're dead. Takes away their buttons to compensate for this (they couldn't use them anyways).

## Why It's Good For The Game

Adds a new role to Mafia to make use of the newly revoked rights I have given to Ghosts (removing their ability to hear Changeling chat).
Removes the alternative way of Ghosts to see who the Changelings are, by hiding the Changeling vote's text.
Updates Icons so they now look like what they appear like in-game. I want to make this use landmarks, however that requires landmarks also stores antags. It currently CAN, but they all appear as naked because their clothes are handled by antag datums and not job outfits. This can be changed in a future PR hopefully.
Adds more claim space for evils and gives Town an extra way of deducting who is evil through the help of your fallen allies.
Also makes the game more interesting for Changelings by preventing them from secretly talking to eachother during the day, they now have to plan in advance during the Night what they want to do the following day.

## Changelog

:cl:
add: [Mafia] Adds the Coroner, taking the current spot of the Chaplain.
add: [Mafia] Chaplains' ability is now to hear deadchat, instead of being able to reveal roles.
balance: [Mafia] Changelings can now only talk to eachother during the night, but no longer need to use the .j saymode.
image: [Mafia] Job icons now reflect the in-game job characters they play are playing as.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
> Imagine if deadchat in town of salem could see mafia and could tell the medium who all the mafia are.

People playing Mafia can't hear Changeling chat. I removed it 2 Mafia PRs ago. In ToS people can see votes and can still talk to the Medium, it isn't a problem there and I don't see it as a problem here.

**Comment by Helg2** [comment]
So the chaplain is either completely useless or just denies all the fun? Meh

**Comment by BlueMemesauce** [comment]
> > Imagine if deadchat in town of salem could see mafia and could tell the medium who all the mafia are.
> 
> People playing Mafia can't hear Changeling chat. I removed it 2 Mafia PRs ago. In ToS people can see votes and can still talk to the Medium, it isn't a problem there and I don't see it as a problem here.

No I mean the votes at night, that confirms them as changeling since only changelings can vote to kill people at night.

**Comment by JohnFulpWillard** [comment]
that's an interesting way of thinking about Medium and I've never seen it that way before. Very insightful comment

**Comment by JohnFulpWillard** [comment]
> No I mean the votes at night, that confirms them as changeling since only changelings can vote to kill people at night.

That's true, I'll patch that. Thank you

**Comment by JohnFulpWillard** [comment]
I've completely reworked how the abilities work, let me know if you have any problems with it.
Chaplains can now only hear dead players, not deadchat entirely
Changeling votes are hidden
Chaplains have no real way of confirming themselves, so evil roles can still argue against it.

This should solve all issues brought up so far.

**Comment by LemonInTheDark** [comment]
they're gonna sue us one of these days

**Comment by JohnFulpWillard** [comment]
They can't I added Coroner before they did
image
image

**Pull request closed without merging**
