### PR TITLE
Hyperspace ripples now animate at the rate of the arriving shuttle

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by coiax** [comment]
WHY ARE YOU DOING THIS?

JUST MAKE THE ARRIVAL SHUTTLE TAKE 10 SECONDS

**Comment by Cyberboss** [comment]
I can't do that, only someone with config access can

**Comment by Cyberboss** [comment]
As an aside, this PR makes it so the full animation will play even if SSshuttle is lagging behind

**Comment by coiax** [comment]
@Cyberboss I don't know why you made it a config option to begin with

**Comment by Cyberboss** [comment]
Because the headmin said to

**Comment by Iamgoofball** [comment]
@Cyberboss You fell for a classic trap

They don't want to outright say they don't want the feature so they don't lose player rep, so they pull the "le downstreams might want a config" card and silently disable it

**Pull request merged**
