### PR TITLE
played_url is json now

### PR DESCRIPTION
**Pull request by JJRcop**
Just makes it a JSON map instead of separating with |

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
@nfreader

**Comment by nfreader** [comment]
Cool beans, more snowflake data I have to handle because the previous played_url data isn't json ^_^

**Comment by JJRcop** [comment]
@nfreader just forget about the previous data, honestly

**Comment by Jordie0608** [comment]
All feedback is becoming json soon and since, as ned said, this will just make things more annoying in the meantime for more snowflake than benefit I'm going to close this.

No data left behind.

**Comment by JJRcop** [comment]
That's good

**Pull request closed without merging**
