### PR TITLE
[Remake] Medical Changes (More than just broken bones)

### PR DESCRIPTION
**Pull request by AffectedArc07**
## Remake of #44401
The reason I remade this is I have changed more than the original PR compensated for, and to say the comments of the previous PR derailed, is an understatement.

## About The Pull Request
This PR makes a few changes to medical, as well as adding new items in. The main two changes are as follows:
- Adding sleepers back __alongside__ the stasis beds. This is to stop medical from relying on patches so much, because competent chemistry is even harder to find than competent medical.
- Adds bone breaking (Read below, its not as harsh as the other PR)

**Bone breaking**
Blunt weapons (high force, example: Toolbox) have a  `(force * 2)%` chance to break a bone with a hit, as long as they have a force of 10 or more. Sharp weapons have a 50% worse chance to break a bone.

Bones will now break if hit with excessively blunt objects (High force, example: Toolbox). Penalties for broken limbs are as follows:
- All limbs: 5% chance of gaining 1-3 damage when walking
- Legs: A broken leg will give you a movement speed decrease. Two broken legs will not impact further
- Arms: A broken arm will mean you occasionally drop things out of that hand. Only applies to the arm that is broken

**Ways to deal with broken bones**
There are three ways, two proper one to deal with broken bones

Option 1: Surgery
You can fix broken bones via surgery, with the following surgical procedure
```
Step 1: Select bone repair with the surgical drapes
Step 2: Make incision with scalpel
Step 3: Retract skin with retractor
Step 4: Set bone with the hemostat
Step 5: Cauterise incision
```
[Wiki update required if this gets merged]
This method is best for early in round when not too many people are in, as it takes around 30 seconds to fully fix a limb via surgery

Option 2: Medical Splints
Medical splints can be found in the medical vendors. There are 10 packs of splints in each NanoMed Plus, and each pack of splints can be used 6 times. 
- Splinted arms function fine 
- Splinted legs have a halved walkspeed penalty (Half as slowed as broken bones), and you no longer take the damage
- You cannot splint the chest or skull

Option 3: Bluespace Bone Repair Tool
This device can be printed in a science or medical protolathe, and require advanced biotech to be research in the techweb tree. It costs 2000 metal (1 sheet), 1000 glass (0.5 sheets), 500 silver (0.25 sheets), and 100 diamond (0.05 sheets). While expensive, it can repair any bone without surgery, just takes 5 seconds for it to be used. The tool has unlimited uses.

**Sleepers**
My main reason for adding these back is the fact that current medical is way too reliant on patches and chemistry. Patches will run out (usually do within 15 minutes), and good chemistry is a rarity. Sleepers have the ability to heal people quickly without having to harass chemistry. The reason for keeping these and the stasis beds is they both have their uses.

Things I **do not** wish to change/add:
- The way crit/defibs/reviving works
- Organ damage
- Internal bleeding

If youre going to comment, I request you actually stay on topic and provide actual suggestions in how this can be improved, instead of just ***REEEEEEEEE BAYMED*** comments.

## Why It's Good For The Game
Our medical system is currently very lacking, which is discouraging people from wanting to play the role. Considering how important of a role on the station it is, having people not want to play it is a bad idea. 

As well as this, knowing there are bigger consequences of a fight, this will discourage random greyshit beatouts from occurring, saving from IC (and possibly administrative) trouble.

## Changelog
:cl: AffectedArc07
add: Bones will now break if hit with blunt objects. Pick your weapons wisely
add: Medical splints can bodge broken bones, but they wont function as well as unbroken bones
add: Bones can be fully repaired via surgery, or by bluespace magic
add: Science and medical can now print bluespace bone repair tools. Does what it says on the tin
add: Medical now has sleepers again, as well as stasis pods
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
Atomize please so I can upvote sleeper restoration but downvote broken bones. Also, from a glance this doesn't touch sleepers' list of chems, which is ungood because they _are_ overpowered.

**Comment by Tlaltecuhtli** [comment]
why add sleepers :joy: thats an express ticket to closed pr :joy:

**Comment by OverlyGeneric** [comment]
when are we going to get some Frankenstein-esque surgeries or just being able to make body horror shit like leg-arms and people with monkey head but a human body?

**Comment by AffectedArc07** [comment]
@Barhandar part of me wants to gut the upgraded chems list slightly, and start off with the 4 main healing chems (syptic, silver sulf, salbutamol, charcoal), then add in some others later on, making them less OP in lateround

**Comment by Barhandar** [comment]
First, fuck you and fuck your goofchems. Second, sleepers inject which means toxin damage if you try to use styptic and sulf in them, and IIRC perf PR was merged (or at least testmerged on sybil since oxykits were stuffed full of perf syringes instead of having salbu pills) so perfluorodecalin is the base oxychem and not salbutamol.

**Comment by AffectedArc07** [comment]
@Barhandar few things:
1] I meant the perfluorodecalin, im still used to fagchems
2] In terms of sleepers, someone bought up this idea:
- Sleepers are like chem dispensers in terms of chemical storage (needing energy)
- More powerful chems need a lot more energy to produce
- *maybe* make the lowest tier healing chems free
- Definatley pull back on the power creep of the sleepers

**Comment by Whoneedspacee** [comment]
I'd still like to see bone breaking working in stages and getting worse over time, it might make it feel less RNG bullshit when you get hit once and are basically out of combat or dead.

Also I'll ask once again, does the calculations for bone breaking happen based on the actual damage dealt? If I'm wearing SWAT armor and get hit by a toolbox, it should at least have less of a chance to break my bones.

Otherwise the above chemistry problems I at least think this is on the right track and has improved, especially with the descriptions of what happen to broken bones.

**Comment by Tlaltecuhtli** [comment]
milk should fix bones

**Comment by shellspeed1** [comment]
First of all, can you make splints craftable with wood. Second of all, what about restockable sleepers?

**Comment by Barhandar** [comment]
Sleepers needing energy is massively annoying and against the point I'm making (powerful chems have no business being in the sleeper at all - you SHOULD require one of the dedicated medbay departments for treating big stuff).

Ironically, goon sleepers would actually be more balanced even with tg's pacing, as they provide aforementioned super basic chems allowing patient to survive until chem gets off their arses and makes medicine, oxygen supply, and stasis option.

A better idea for upgraded sleepers would be making them able to _autoinject_ basic stabilizer chems; roundstart medibots already can do autoinjection so why not a complicated, stationary machine?  
So for example roundstart, T1 sleeper has epinephrine, T2 also has salglu, T3 starts autoinjecting epinephrine to safe threshold, T4 also autoinjects salglu.

**Comment by AffectedArc07** [comment]
@Whoneedspacee I want to make it calculate on that, and I do agree the RNG stuff is a pain in the ass. Stages to broken bones may be a good idea, but I think that is outside my code ability. 

I'll attempt to make the bones have a higher break chance the higher the damage, but still have a force of 10 required. Sound good?

**Comment by Barhandar** [comment]
@AffectedArc07 yes, the upgrades should give functionality along or instead more chems. And hyper-dedicated chems (stuff like pentetic) should NEVER be in the sleeper ever.

So sleepers should have at most epi (moreso its chem recipe is bloody stupid for something that >pauses crit), salglu, charcoal, potassium iodide (...does it even exist roundstart? It's two clicks in chemistry but you have to make chemistry actually do that), and that's about it. Stuff like atropine, salicylic, oxandrolone, the dedicated oxyloss chem, pentetic etc should not be in sleepers at all, make chemists mix them or grab from storage.

**Comment by optimumtact** [comment]
this isn't getting merged with sleepers in it

**Comment by optimumtact** [comment]
In fact the more I look this is just a blatant bribe to improve response to a thing that people didn't like and it pisses me off

**Comment by adamkad1** [comment]
no bone gel?

**Comment by AffectedArc07** [comment]
@optimumtact Do you want to elaborate on what you even mean? Improved things that people didnt like? Yes. Bribe? No not really.

**Comment by Arianya** [comment]
Speaking personally, I don't see how sleeper re-integration is related to your bone changes (other then the very tenuous link of both being medical things) and given the controversy surrounding it, it does rather look like you're trying to score easy points by doing something people want in the hopes it'll motivate support for your less popular bone changes.

**Comment by Arianya** [comment]
Basically this is the github equivelant of "attaching an unpopular rider to a popular bill in the hopes people won't vote it down"

**Comment by AffectedArc07** [comment]
@Arianya If it was just bone changes I would have kept going with the old PR. This point of this one is to keep adding more medical changes which people **actually** want in attempt to make medical not a festering shithole, by doing things such as adding back sleepers.

**Comment by adamkad1** [comment]
> @Arianya If it was just bone changes I would have kept going with the old PR. This point of this one is to keep adding more medical changes which people **actually** want in attempt to make medical not a festering shithole, by doing things such as adding back sleepers.

i mean, hygiene is still in, economy is still in...

**Comment by Ziiro** [comment]
I suggested the sleeper thing, because think of it this way:

If "Mild" injury is treated faster/more efficiently, that would leave time to fix the more in depth problems (bone breaks)

But if **_every_** part of medical is time consuming and shitty, it's just bad.

**Comment by adamkad1** [comment]
> I suggested the sleeper thing, because think of it this way:
> 
> If "Mild" injury is treated faster/more efficiently, that would leave time to fix the more in depth problems (bone breaks)
> 
> But if **_every_** part of medical is time consuming and shitty, it's just bad.

i dont think oranges can think this way

**Comment by optimumtact** [comment]
I can, I just don't agree with you

**Comment by Whoneedspacee** [comment]
everyone want sleepeys instead of orange boy

**Comment by Ziiro** [comment]
Fair enough, thought I'd just make my own perspective clear. Carry on, orange man.

**Comment by adamkad1** [comment]
goofball 2.0

**Comment by KetasDotepasto** [comment]
@optimumtact  good call.

Also, competent chemistry isn't at all as rarer as you guys make it sound.

**Comment by optimumtact** [comment]
I don't know why people are so fucking suprised? like hello, im not running a pick and choose mart here.

**Pull request closed without merging**
