### PR TITLE
Adds shamebrero penguin for dumb alphonzo

### PR DESCRIPTION
**Pull request by Militaires**
:cl: basilman
add: penguins may now have shamebreros, noot noot
/:cl:

requested by dumb stupid alphonzo
he will defend this pr

image

### CODE REVIEW

**Comment by Armhulen** [comment]
They totally look like they fit on that head.

**Comment by DoctoreMad** [comment]
Do they get scared if you start building walls near them?

**Comment by YotaXP** [comment]
I'm triggered that the sombrero is an even number of pixels wide, when the penguin is odd.

**Comment by ExcessiveUseOfCobblestone** [comment]
Can we have an obvious runescape reference where the penguins are dressed up as sheep next

**Pull request merged**
