### PR TITLE
Disables x-ray mutation

### PR DESCRIPTION
**Pull request by Time-Green**
Poll: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=21035 25 / 25 as of time of writing
(I'll admit it's not a clear win, since it's 50/50 and also included "or Nerf", but an altered version can be released later)
:cl:
del: Removes the x-ray mutation
/:cl:
It's quite frankly really powerful, allowing someone complete vision of their screen by simple genetics. It's unfair for anyone trying to do stealth and shouldn't be so easily available.

This also makes x-ray eyes more useful, since they aren't 100% overshadowed anymore.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
I forgot I was going to change this, whoops. This is fine for now

**Comment by Angustmeta** [comment]
I cast my vote on remove so that settles it.

**Comment by knacker48** [comment]
the vote was 50/50. At least propose a rework for xray or your just gonna piss off half of the player base

**Comment by ATH1909** [comment]
I didn't even know that there was a poll...

I vote for keeping it, for the record.

**Comment by Shadowflame909** [comment]
I just propose that X-ray becomes a Trigger/Power Mutation. Instead of being outright removed.

Let us look at the realistic X-ray vision facts.

1. X-ray is near the end of the light spectrum.

2. Use it too many times and it'll give you cancer.

What if X-ray just gave people a dose of toxin damage, for however long they have it on. A good bit too, since it's coming from their eyeballs.

**Comment by davethwave** [comment]
Or eye damage

**Comment by zeroisthebiggay** [comment]
give it a wraith spectacles treatment where the longer it's on the more fucked up your eyes get.
but don't make it fix your eyes.

**Comment by knacker48** [comment]
I would go more the combinations plus high instability route.
Lets say eye related defect/power + radioactive = xray with instability = 40
That way you need to put in more work into getting it and it isn't just an auto include due to the cost

**Comment by Jujumatic** [comment]
why would you do this?

**Comment by Shadowflame909** [comment]
To add onto support for X-ray. Recently Hulks have been made not at all useful for blocking disabler beams. And, since they can't hold guns. They're literally less useful then grabbing a jackhammer.

Genetics is in a neutered state already, so if X-ray is gone. Genetics isn't even a threat. Very Laughable, as I think it should be getting some buffs and alternatives to Hulk. What can it really do?

**Comment by knacker48** [comment]
Yeah I find these nerfs/removals completely unnecessary. But this is coming from someone who plays genetics frequently so I'm biased

**Comment by Time-Green** [comment]
X-ray is ridicoulusly overpowered, allowing someone to see everything on their screen. It’s really easy and convenient to get and completely overshadows x-ray cybernetics aswell. The synergy with telekinesis is also ridiculous. A few more points were adressed in the original forum post

**Comment by subject217** [comment]
the genetics nerf we need but not the one we deserve

**Comment by MegaEmpirical** [comment]
I once had a genetist who got lucky early game, walked into the dorms, and called me out whilst I was getting the chameleon kit on. I was not super thrilled. I'm not opposed to this being going. Mesons allow us to easily identify hidden rooms and nooks.

**Comment by ExcessiveUseOfCobblestone** [comment]
Remove and Nerf are two entirely different things and even combined they scored 50%. Unless you're telling me literally everyone in that pool wants remove, Stay is definitely the winning option. I don't listen to polls tho :^)

There are various stats, ironically the PR author implemented, that can be used to curb a powerful mutation. I don't see why those aren't being implemented here especially when the concept of xray hasn't been removed, just a single way of obtaining it.

**Comment by PKPenguin321** [comment]
I can work on the change I proposed earlier I guess

**Comment by PKPenguin321** [comment]
alternative PR: https://github.com/tgstation/tgstation/pull/43340

**Comment by Time-Green** [comment]
imo theres no amount of instability and combining that makes up for x-ray. I just don’t think something like x-ray should be available in genetics

**Comment by PKPenguin321** [comment]
It's fine honestly. Only annoying when somebody gets it by RNG very early on and screws over antags before they can get the ball rolling. A timegate like what I add in my PR fixes that.

**Comment by SouDescolado** [comment]
Make X Ray have that weird vision drones had so they cannot identify who is who. Why you can see through walls but not through skin (And then again through the wall behind the person you are identifying)

**Comment by SpaceManiac** [comment]
Closed in favor of #43340

**Pull request closed without merging**
