### PR TITLE
Corrects the description for Hunter Spiders and Vipers

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request

The spiders toxin injection amount was changed in #63117, lowering it to 5. This was not changed in their description and the subtypes that followed it. 
## Why It's Good For The Game

Consistency is nice.
## Changelog

:cl:
spellcheck: Vipers, Hunter Spiders (and their subtypes) do indeed, inject 5u of toxins and not 10u, as the old description stated.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
Could make it poison_per_bite instead so its automatic?

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Automate it

**Comment by Jolly-66** [comment]
> Automate it

Could you give me an idea/direction to go with this? I'm not sure what to do exactly

**Comment by Mothblocks** [comment]
Set the description on `/Initialize`, refering to whatever value actually does the damage.

**Comment by Jolly-66** [comment]
I'm gonna come back to this later unless someone else beats me to the chase

**Pull request closed without merging**
