### PR TITLE
Sigils of submission now uncuff upon successful conversion

### PR DESCRIPTION
**Pull request by ghost**
No more retards forgetting to uncuff after conversion

:cl: More Robust Than You
balance: Sigils of submission now uncuff upon successful conversion
/:cl:

### CODE REVIEW

**Comment by imsxz** [comment]
it'd be nice if it spawned a slab on them too like with blood cult. It can be very frustrating when you're converted but never given a slab.

**Comment by MoreRobustThanYou** [comment]
@imsxz well i mean, since 99% of conversions are on Reebe, you can just grab an extra slab from the dressing room.

**Comment by optimumtact** [comment]
This seems to be a player issue and I don't think we should solve it in code

**Comment by MoreRobustThanYou** [comment]
@optimumtact blood cult conversions heal

**Pull request merged**
