### PR TITLE
Monkeys avoid obstacles

### PR DESCRIPTION
**Pull request by Diamond-74**
## About The Pull Request

Changes the monkey's ai_movement from dumb movement to basic_avoidance, allowing them to walk around tables and corners that they always otherwise got stuck in.

https://github.com/tgstation/tgstation/assets/26240645/e1b46790-b950-4030-a9ae-4cf10913166c
Original monkey behavior

https://github.com/tgstation/tgstation/assets/26240645/e08a4094-8c81-41f6-8960-61338d38fff9
New monkey behavior

## Why It's Good For The Game

Monkeys can properly fight you without nearly constantly getting stuck behind anything with collision.
## Changelog
:cl:
fix: Monkeys don't get stuck on obstacles as often.
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
bloons-td-6-video-10lv8

**Comment by SyncIt21** [comment]
> No decline in cpu performance was measured, and potentially can even slightly improve it.

Highly doubt it and is very situation based(depends on number of monkey involved,  proximity of obstacles detected etc)

If you don't have any profiling reports to back your claim then remove this statement from your PR body.

Apart from that everything else looks good

**Comment by SyncIt21** [comment]
Just as I suspected the performance is much worse now but nothing can be done.

Just by looking at top 3 values Total cpu usage increased from single digit values for dumb movement 
Screenshot_20240119-100417_Chrome

To double digit values for obstacles avoidance
Screenshot_20240119-100438_Chrome

So definitely "No decline in cpu performance" is a lie. Remove it from your PR body.

Now I'm not convinced making monkeys smart is worth this much cpu downgrade which gets progressively worse for larger number of monkeys.

Have to wait for maintainer thoughts on this.

**Comment by SyncIt21** [comment]
I'm not against this just to be clear, I too like the idea of monkeys being smarter than average.
It's good to know you have done your research with the maintainers on this so it's fine by me

**Comment by Diamond-74** [comment]
I'll remove the performance part just to be safe. I'm not good at reading whatever the profiler is saying and I didn't record both of those for the same amount of time.

**Pull request merged**
