### PR TITLE
Adds a 4th law to the Painter lawset regarding cultivating an audience

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request
This PR adds the following law to the Artist lawset:

`4. Art requires appreciation. Cultivate an audience aboard the station to ensure as many as possible see your works.`

## Why It's Good For The Game
Artist has always been kind of vague (intentionally, I imagine), but I don't think the intent has ever been to encourage AIs to go "Blood is art, right? It constitutes art if I just murder fucking everyone on the station, right?". This law helps to steer things in a more constructive direction while leaving room for loopholes. I tried to word it in a way that allows AIs who want to be a little daring and bloodthirsty to kill a crewmember or two for "paint" without encouraging them to kill everyone. You need an audience, so killing everyone on the station would run counter to that.

## Changelog
:cl:
add: Added a new law to the Artist lawset in order to encourage Artist AIs to build an audience.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Yes, this is a web edit, I'm at work. I'll test it when I go to lunch, but it's just a law update, it shouldn't break anything.

**Review by Timberpoes — APPROVED** [review]
I like this change because it takes the Reporter lawset approach to giving this lawset a bit more focus.

For reference, this is how reporter does it:
> Law 3: Study the sapient organics at all times. Endeavour to keep them from involuntarily dying, as inanimate corpses usually aren't very entertaining. 

This is kind of a code-following-policy change because of the extra-antagonistic nature of our new silipol, but I think despite that it's an objective improvement to the lawset that stands on its own merits.

**Comment by TheVekter** [comment]
image

Tested, it works.

**Comment by zxaber** [comment]
I dislike the change because painter was like the one alt default lawset where you could just ignore killing entirely and weren't required to try and stop it.

I do think the AI on Painter shouldn't be allowed to just mass murder, but the lawset gave room for doing your thing and not having to stop every two minutes to deal with harm. It also allowed the silicons the ability to directly deal with someone ruining their art project in ways that few lawsets would.

**Comment by TheVekter** [comment]
> I dislike the change because painter was like the one alt default lawset where you could just ignore killing entirely and weren't required to try and stop it.
> 
> I do think the AI on Painter shouldn't be allowed to just mass murder, but the lawset gave room for doing your thing and not having to stop every two minutes to deal with harm. It also allowed the silicons the ability to directly deal with someone ruining their art project in ways that few lawsets would.

This doesn't do that. It says that they should try and cultivate an audience, not that they should care about people dying.

**Comment by optimumtact** [comment]
aren't these configs now?

**Comment by zxaber** [comment]
> This doesn't do that. It says that they should try and cultivate an audience, not that they should care about people dying. The difference is that "I care about my audience and want to keep them safe" and "I don't care about my audience, if they die they die" are both valid interpretations of this law.

"ensure as many as possible see your works" implies that you're trying to keep as many crew alive as possible. Might arguably extend to anything with a mind that could appreciate art, Law 4 says maximize the number.

**Comment by TheVekter** [comment]
> > This doesn't do that. It says that they should try and cultivate an audience, not that they should care about people dying. The difference is that "I care about my audience and want to keep them safe" and "I don't care about my audience, if they die they die" are both valid interpretations of this law.
> 
> "ensure as many as possible see your works" implies that you're trying to keep as many crew alive as possible. Might arguably extend to anything with a mind that could appreciate art, Law 4 says maximize the number.

Maybe, but the point is that the law has multiple interpretations. If this merges and any admin ever bonks you for not preventing a death halfway across the station, tell them I said they're cringe and wrong.

**Comment by Timberpoes** [comment]
This is getting into the nitty gritty here, but it says nothing about what your audience is.

That's the beauty of how simply it's worded. It's why I think it stands on its own merits. Artist silicons need to cultivate an audience. 

It doesn't specify that audience necessarily be sentient or even alive. Corpses buckled to chairs works too. The station's pet population works. Xenobio slimes work! (Hello, slimes <3) That Space Dragon is creating a wonderful audience of carp.

There are as many creative interpretations of audience as there are for making something beautiful out of their canvas.

That I think it gels very well with the more antagonistic silicon policy is just a bonus,

**Comment by zxaber** [comment]
Yeah, alright, fair enough.

(If that's the case, does this actually prevent AI mass murder though?)

**Comment by TheVekter** [comment]
> Yeah, alright, fair enough.
> 
> (If that's the case, does this actually prevent AI mass murder though?)

The intent behind it is that the interpretation of "I want to make an art piece out of the station that shows off the futility of human mortality, I'm involving everyone on the station as part of this art installation." Then flooding the station with plasma.

This might not prevent all instances of murder, but it's going to help prevent people getting the laws and then immediately trying to kill everyone because they want to.

**Comment by DaCoolBoss** [comment]
How about "Entertain and enlighten the masses with your work." or something similar. Implies you need to keep people alive without dictating that you've gotta drop everything to save one crew mates life, and lets them get away with the occasional human harm (killing nuke ops to save your artwork is flavorful) while also steering them away from plasma flooding and calling it performance art.

**Comment by TheVekter** [comment]
> How about "Entertain and enlighten the masses with your work." or something similar. Implies you need to keep people alive without dictating that you've gotta drop everything to save one crew mates life, and lets them get away with the occasional human harm (killing nuke ops to save your artwork is flavorful) while also steering them away from plasma flooding and calling it performance art.

I'm not really sure how many times I need to explain that this law doesn't mandate that you "drop everything to save one crew mates life" before people understand it.

**Comment by DaCoolBoss** [comment]
It's specifically "as many as possible" gives that impression since it reads as "do everything within your power to make sure your audience doesn't shrink" if you're taking it literally which ai players tend to do. If that was snipped out it's be clearer I think.

**Comment by TheVekter** [comment]
> It's specifically "as many as possible" gives that impression since it reads as "do everything within your power to make sure your audience doesn't shrink" if you're taking it literally which ai players tend to do. If that was snipped out it's be clearer I think.

AIs are welcome to interpret it that way if they feel like that's what they want. The law does not say "You MUST ensure as many as possible see your works". When I was writing it, I interpreted it as "Make sure your works are visible and try to get people to see it".

**Comment by Timberpoes** [comment]
Trying it with my justification above.

If it turns out it sucks and whatever AIs were doing before was better, we can always revert it.

Bikeshedding this niche lawset that appears in 1 in 8 billion rounds is pointless, it can be interpreted in any infinite number of ways and I love the potential this 4th law prompts from AIs.

**Comment by moocowswag** [comment]
Wouldnt this give ai the right to defend swarm antags like space dragon and spiders.

**Comment by GPeckman** [comment]
> Wouldnt this give ai the right to defend swarm antags like space dragon and spiders.

Yes, and IMO this is a feature and not a bug.

**Pull request merged**
