### PR TITLE
Makes more things use colored lights

### PR DESCRIPTION
**Pull request by Tacolizard**
I made the lights as dim as possible, so they can only be seen in total darkness. There aren't a huge number of additions in this PR, so I may add more. This isn't WIP though and can be merged.

These changes make very little impact in lit areas

the following pics are of the clonepod, the strongest light I've added

**clonepod in the dark**
poddark

**clonepod in light**
podlight

### CODE REVIEW

**Comment by Bawhoppen** [comment]
CYAN for the clearly green clone pod? CONSPIRACY

**Comment by Incoming5643** [comment]
Client processing hit for very little gain.

**Comment by Tacolizard** [comment]
@Incoming5643 stop being a meme and get a better comp. This doesn't decrease performance lower than it is already.

**Comment by Tacolizard** [comment]
also i removed the light on the syndiebomb

**Comment by InsaneHyena** [comment]
It's time to stop

**Comment by kevinz000** [comment]
first of all don't tell incoming to get a better comp as they've already said they can't.
second of all this seems like pointless colored lighting that just pollutes the game view.

**Comment by Tacolizard** [comment]
@kevinz000 

> I made the lights as dim as possible, so they can only be seen in total darkness.


these changes are to make the game more atmospheric in the dark. They also cast their light in such a small range that they can't be used to light an area at all. The items i have changed just have a dim glow on their tile, and don't cast light far enough for navigation.

**Comment by TrustyGun** [comment]
pictures?

**Comment by Tacolizard** [comment]
@TrustyGun pics coming in an hour mabye

**Comment by lzimann** [comment]
Stop adding more colored lights. The game isn't a rave party

**Comment by lzimann** [comment]
@tgstation/commit-access I am closing this in 24h if no one wants to merge. Adding more and more colored lights is just awful and makes the game look like shit.

**Comment by optimumtact** [comment]
why wait

**Comment by Cyberboss** [comment]
>4 months to merge newlighting

>don't use it

wew

**Comment by lzimann** [comment]
We are using it though.

**Pull request closed without merging**
