### PR TITLE
Removes example.dmm from away missions

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
http://i.imgur.com/ZkknCRZ.png

We have plenty of full fledged away missions that serve as examples, we no longer need to maintain this file, and there isn't enough in it worth even porting to be space ruins.

### CODE REVIEW

**Comment by WJohn** [comment]
:+1:

**Comment by ike709** [comment]
>muh tg culture

:+1:

**Comment by Jordie0608** [comment]
You will need to remove it from the away missions configs as well.

**Comment by KorPhaeron** [comment]
@Jordie0608 

I did all of the updates in a file in my most recent commit to avoid conflicting with myself

**Pull request merged**
