### PR TITLE
Lighters use welding fuel and can be used as welders in some cases

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Lighters now have welding fuel which can be filled/extracted by hand, giving a small but consistent source of welding fuel for non-chemists.
Welding fuel is now required for these lighters to work, they'll close automatically once they're out of fuel.
They last for a minute, zippo lasts 2 minutes, before they need to be refuelled. It can have other reagents put into it but it only checks for welding fuel, so it won't work at all unless its got some.
They can be used as welding tools in minor cases, mostly fixing things and welding doors shut, but can't do big things like deconstruction, except the xenobio one because it's a lot hotter than the normal lighter.

Also added a baseline support to check for heat to perform certain welds, before heat is just this binary "has or doesnt have heat", which made its value useless.

## Why It's Good For The Game

Adds a ghetto way of getting welding fuel, hiding reagents, and a ghetto welding tool without being something that prisoners could break out of prison with. They could weld the doors shut which is a little funny, security still has proper welding tools to counter it.
It also currently is kinda lame that lighters could just be open 24/7, unlike matches which has a lifespan of 10 seconds each or something.

## Changelog

:cl:
add: Lighters now use and require welding fuel to work, but can be used as a welding tool for tasks that don't require much heat.
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
ngl being able to weld doors with these sounds REALLY weird.

**Comment by kawaiinick** [comment]
Thats such a bullshit if you can weld airlock or repair a durand with your 5 cent plastic lighter. Crafting ghetto welder from a lighter would make more sense

**Comment by GuillaumePrata** [comment]
This opens the way for more chem interaction outside of healing/damage which is just good for the game.

It doesn't need, and probably shouldn't be on this PR, but we could have things like grinded plasma ghetto welders, rigged meth lighters, etc, etc.

**Comment by SomeoneYouProbablyKnow** [comment]
Repairing a robo-arm is one thing, repairing a mech.. I guess it doesn't matter, anyone in a mech has a welding tool to begin with. Welding doors is insane thematically but kinda cool since it's pretty underutilized as a mechanic, the lighter should probably only have enough fuel for one or two doors on its own. And if you can find fuel you can find a welder so it hardly matters

**Comment by Dorsisdwarf** [comment]
Being able to use a zippo to weld bulkhead doors shut is absolutely wild

**Comment by deathrobotpunch** [comment]
> This opens the way for more chem interaction outside of healing/damage which is just good for the game.

sadly only welding fuel is checked for and all other chema are ignored

**Comment by Loafin34** [comment]
what'd be funny is if it was like a slime extract where if you injected it with the right shit it turns into a more badass lighter. slime? how about a slime lighter? pure nicotine? badass lighter!

**Comment by SomeoneYouProbablyKnow** [comment]
Considering how lighters work you could make it heat up the reagents slightly, portable smoke bomb lighter or something. An explosing lighter trap. A healing smoke lighter. Chemistry as much as i dislike the mechanics can make for some fun outcomes

**Comment by zxaber** [comment]
I dunno about the welding with a bic lighter thing. Seems a bit dumb, and we already have emergency welding tools scattered about as a lower-tier welder option. I guess I could see it for augment and glass repair, but anything higher becomes silly.

**Comment by SomeoneYouProbablyKnow** [comment]
What about a middle ground, let lighters carry reagents, heat up reagents on use, fix small stuff AND make a new chem like super welding fuel which WOULD allow you to use a lighter. Anyone who'd actually want to weld airlocks would rather just grab a normal welder BUT with a chem setup or ghetto using a lighter for "cool points" would work

**Comment by Loafin34** [comment]
can you make this retain the welding tool bomb component that happens when there's liquid plasma inside it?

**Comment by JohnFulpWillard** [comment]
> can you make this retain the welding tool bomb component that happens when there's liquid plasma inside it?

idek what this is can you explain

**Comment by SomeoneYouProbablyKnow** [comment]
I assume they mean. Put plasma in cigar, light cigar cigar, explodes. Same thing for lighters. Pull a fast one on someone by offering them a lighter primed to explore. Never used it myself but presumably its a thing

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
