### PR TITLE
Being drunk improves mood

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
tweak: Drinking alcohol now improves your mood
/:cl:
At last, the bartender finds his purpose.
This may be a bit strong but I think making the bar the best place to go to improve mood is a good thing.

### CODE REVIEW

**Comment by bgobandit** [comment]
there should be a hangover component if you drink too much that reduces mood

**Comment by Mickyan** [comment]
Adding a "drank a fancy drink" moodlet for a few specific types of advanced drinks should be pretty easy, anything more than that probably would require some doing

I'm going to stick with the basics for this PR however

**Comment by optimumtact** [comment]
Also could someone please remove the bad mood visual overlay? I did not realise it was still in and I don't want it included.

Bad moods should only lower your crit threshold

**Comment by Kagus** [comment]
I was deeply disappointed when I originally found out that alcohol had no effect on mood, while reading "MY ASS: A AUTOBRAPHY" in the library did.

But yes, aside from the obvious benefit of giving people a normal reason to drink, this also gives the bartender something more to do than just RP or validhunt. In theory.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
