### PR TITLE
Adds Queen Finder for Xenos

### PR DESCRIPTION
**Pull request by GunHog**
:cl: Gun Hog and WJohnston
add: Aliens (Xenos) now have the ability to sense the direction and rough distance of their queen!
/:cl:
- Xenos now have a "queen sense" which tracks the queen like a
  pinpointer.
- Added WJ's custom sprites for all non-queen Xenos.
- Modded the alien type finder to support queen finding

PR on behalf of @WJohn, **sprites subject to change!!**

The little red dot changes to an eye at longer distances. I will add more examples as the sprites are finalized.

screenshot 2016-07-14 20 09 14

screenshot 2016-07-14 20 11 04

### CODE REVIEW

**Comment by jughu** [comment]
Only a matter of time we turn into marines...

**Comment by WJohn** [comment]
Very much approved, great work!

**Comment by jughu** [comment]
Will this affect be added to the alien hivecores

**Comment by GunHog** [comment]
> Will this affect be added to the alien hivecores

If it is something WJ desires. My personal opinion is against this, as the ability to compromise their chat AND have complete hugger immunity is powerful enough. A Queen who knew I killed the other queen and took her node fed me false information over the Hivemind channel. It would be a shame to lose such emergent gameplay.

That being said, this PR is for WJ, so whatever changes he wants, I will do.

**Comment by jughu** [comment]
Will there be additional chance of having a special queen hivecore so aliens can know where i am

**Comment by GunHog** [comment]
It is not tied to organs at all - There can only be one active (alive, has a ckey) alien queen at a time without admin memes (in such a case, the first active queen gets tracked), and your queen finder will always track the current queen.

**Comment by GunHog** [comment]
Updated sprites! Looks nicer now

**Comment by jughu** [comment]
Oke 1+

**Pull request merged**
