### PR TITLE
Resprites Jackboots and Black Gloves

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Self-Explanatory, resprites Black Gloves/Fingerless Gloves and jackboots into newer standards!
(thanks @SmArtKar for the object sprite for jackboots and @axietheaxolotl for the black gloves on mob sprites)
image

## Why It's Good For The Game
In the case of gloves, they looked more grey than actually black, and for jackboots, they lacked polish and shine. And now behold, improved versions of them!

## Changelog

:cl: PositiveEntropy, SmArtKar, axietheaxolotl
imageadd: Resprites Black Gloves and Jackboots!
/:cl:

### CODE REVIEW

**Comment by capsaicinz** [comment]
You have a negative soul delta of "-27373837474838283748337."

**Comment by iwishforducks** [comment]
https://www.youtube.com/watch?v=hj2UwrDj9O0

**Comment by SmArtKar** [comment]
Jackboots look too plain and resemble galoches because of that small widening ontop. Maybe add some details and make the widening taller?

**Comment by Imaginos16** [comment]
> Jackboots look too plain and resemble galoches because of that small widening ontop. Maybe add some details and make the widening taller?

To be quite fair, I am unhappy with the object icon so it'll be adjusted in the following hours.

**Comment by Wallemations** [comment]
Yea the jackboots could definitely use some laces at least.
While I like the right gloves, I feel like the fingerless ones aren't very easy to discern.

**Comment by Imaginos16** [comment]
image
@SmArtKar made new ones so /shrug

**Comment by Fikou** [comment]
> Yea the jackboots could definitely use some laces at least. While I like the right gloves, I feel like the fingerless ones aren't very easy to discern.

our jackboots are laceless

**Comment by Imaginos16** [comment]
> Yea the jackboots could definitely use some laces at least.
> While I like the right gloves, I feel like the fingerless ones aren't very easy to discern.

As for fingerless, its almost one to one what the old sprite was, it was simply changed color-wise

**Comment by CRITAWAKETS** [comment]
Needs more contrast. Also those jackboots are so blocky you could make a minecraft reference.

**Comment by Serxule** [comment]
but seriously, comparing these to the current sprites, they dont really resemble eachother other than being black 
153679113-9efc9bd9-1452-4e8a-81d7-71baa22051b2 (1)

**Comment by Tennessee116** [comment]
> and for jackboots, they lacked polish and shine

But the new ones literally look like pillows.

**Comment by YakumoChen** [comment]
The old sprite does feel more accurate, jackboots are essentially tubes with feet on the bottom.

**Review by Twaticus — APPROVED** [review]

**Comment by Mithrun** [comment]
Definitely vibing with the combat boot style you're going for over what jackboots actually look like IRL, that's how i always envisioned them, could use a little more detail on foot and more shine though. Gloves look nice!

**Pull request merged**
