### PR TITLE
Adds androids and synths to the lists of species that pride and magic mirrors can turn you into

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR adds androids and synths (but NOT military synths (their combo of 25 racial armor and the ability to wear body armor is a bit 3spooky5me)) to the lists of races available from pride mirrors and magic mirrors.

## Why It's Good For The Game

Synths are a relatively weak race, so I think they're fine to include.

Androids are spaceproof and have the ability to wear wizard clothes, but they also have a crippling weakness to EMPs (and a special text span that alerts the crew to the fact that they're a robot and thus are likely weak to EMPs).

## Changelog
:cl: ATHAHTH
balance: Androids and synths have been added to the lists of races available from pride mirrors and magic mirrors.
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
I thought androids had some beefy combat bonuses too, or have I been confused by the large array of robotic admin-only races?

**Comment by optimumtact** [comment]
Dunno how I feel about it tbh

**Comment by Fikou** [comment]
arent synths supposed to fix their disguise with synthflesh
isnt synthflesh removed or something

**Comment by Rayisken** [comment]
> Unless someone has touched them recently I thought that synth code was just an unusable mess? +1 For androids, though

I use them on yogs for events, I think someone cleaned up the code at least a little.

**Pull request merged**
