### PR TITLE
Pubbystation mapping fixes

### LINKED ISSUE #53767: new pubby cargo has no qm spawner

### LINKED ISSUE #53768: new pubby cargo has 2doors that cant be opened with cargo access
noaccess
noaccess2

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Fixes #53767, fixes #53768 

Adds the QM spawn in their office overlooking the cargo bay and fixes cargo techs not being able to access the delivery office. ~~I didn't change the mining office door, because as far as I know only the QM and miners can access mining on most stations.~~ 
EDIT: I thought that was a cargo tech in the picture attached to the access issue. Fixed the mining door to include QM access.

As I was adding the QM spawn I noticed that the miner spawns and cargo tech spawns were missing as well, so I added them in their usual spots.

## Why It's Good For The Game
Cargo techs can now access the delivery office, QMs can access mining, QMs, techs, and miners have spawns!

## Changelog
:cl:
add: Quartermaster spawnpoint on Pubbystation
add: Shaft Miner spawnpoints on Pubbystation
add: Cargo Tech spawnpoints on Pubbystation
fix: Fixed Pubbystation delivery access and mining access
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
qm cant open the mining door

**Comment by RuneQuester** [comment]
QM Also cant open mining office,and cargo techs can open the QMS office

**Comment by dragomagol** [comment]
All right, I will now neurotically check all doors in cargo to make sure they're not broke

**Comment by dragomagol** [comment]
Regarding the cargo techs (and miners!) being able to access the QM's office, it turns out that for some reason the Cargo Tech and Shaft Miner access includes the QM's office by default. Not sure why that is.

**Comment by Timberpoes** [comment]
image

We'll get this merged so the proletariat don't rebel again.

**Review by Timberpoes — APPROVED** [review]

**Pull request merged**
