### PR TITLE
Removes aesthetic window panes

### PR DESCRIPTION
**Pull request by pudl**
This pr removes window panes that served no purpose other than aesthetic value. Windows that were used for real reasons like walling off important areas, blocking space, etc remain.

Examples of windows that are removed:
- All windows that formed broken looking windows in maint
- Window panes in robotics surgery
- Window panes blocking off scrubbers/pumps in dorms

Examples of windows that remain:
- Windows blocking off the gateway, theater, boxing ring, etc.
- Windows blocking off space inside of shuttles

For anyone who is sick of my prs that break everything and wants me to actually help this codebase, this pr's for you! :) Yes, I tested this one.

### CODE REVIEW

**Comment by Xhuis** [comment]
A few screenshots might help people decide.

**Comment by pudl** [comment]
Go look at a picture of the map, and imagine it without all the shitty window panes

**Comment by Xhuis** [comment]
By "window panes" do you mean the one-directional windows?

**Comment by pudl** [comment]
Yep

**Comment by GunHog** [comment]
Why do you feel this is necessary?

**Comment by ChangelingRain** [comment]
Screenshots, please.

**Comment by pudl** [comment]
@GunHog Border objects suck

**Comment by MMMiracles** [comment]
dislike and unsubscribe

**Comment by Bawhoppen** [comment]
autism awareness

**Comment by Aloraydrel** [comment]
Robos window panes are dumb and deserve death

**Pull request closed without merging**
