### PR TITLE
Fixes #12309: Borg RCDs using too much power

### LINKED ISSUE #12309: Borg RCDs can't build much
Like two walls or something and that's it

My fault, when I changed RCD build costs to match metal build costs I didn't test the borg RCD properly

### PR DESCRIPTION
**Pull request by freerealestate**
Their RCDs are now about 1.3x as efficient as their human counterparts.

Fixes #12309

### CODE REVIEW

**Comment by Miauw62** [comment]
:+1:

**Comment by KorPhaeron** [comment]
Thank you

**Comment by RemieRichards** [comment]
Oh thank god, I thought this was some idiot's idea of balance.

**Comment by KorPhaeron** [comment]
@RemieRichards 

It was. Borgs used to be able to build entire wings of the station on a single charge but it was declared unfun and too strong and nerfed. I think the proposed charge is still way more than the old one was

**Comment by RemieRichards** [comment]
@KorPhaeron Yes I know what they used to be able to do, as I *USED* to play them, but stopped at somepoint, tried engi borg again a week ago and was VERY unhappy with the new RCD.

**Comment by Miauw62** [comment]
right now it's REALLY little, I feel like this would be a good change.

**Pull request merged**
