### PR TITLE
[READY] Fusion: Prepare to Die Edition (and more)

### PR DESCRIPTION
**Pull request by mirrorcult**
:cl: cyclowns
tweak: Fusion has been reworked to be a whole lot deadlier! 
tweak: You can now use analyzers on gas mixtures holders (canisters, pipes, turfs, etc) that have undergone fusion to see the power of the fusion reaction that occurred.
balance: Several gases' fusion power and fusion's gas creation has been reworked to make its tier system more linear and less cheese-able.
/:cl:

Heres just what fusion can do to you:
https://streamable.com/nf0ay (it's a little hard to see the nuclear particles, but those pretty pretty lights come from them)
- Zap the shit out of anyone nearby
- Irradiate the entire area around where the reaction happened for a really, really long time
- Blow everything up
- Release a ton of nuclear particles that all do 20 damage AND irradiate you

All this and I'm still unsure if its dangerous enough.

And, fusion reaction analyzing!
image

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
Fusion, even after my rework, is still kinda lackluster in the 'risk <-> reward' department. It's pretty easy to  bypass the consequences of fusion as it stands right now, so I wanted to change that. I think you can suspend your disbelief enough for the new effects. Also, there are a couple balance changes to fusion that I'll outline more below that I noticed happening and theorized could happen, so I tackled those here as well.

More specific reasoning for every change:

- Addition of nuclear particles/tesla zap

As said before, I thought fusion should be more dangerous. As to why these specifically, I chose the addition of nuclear particles because I felt like it was at least decently thematically appropriate, and had a lot of potential to look visually interesting. The sprite is pretty much just a downscaled gumball with some added fluff. They all have random colors that are chosen when created, and fire out from the fusion holder's turf in random angles and with a 1 decisecond delay. I chose tesla zaps because.. well, they're pretty cool, felt *reasonable* enough (an extremely powerful release of energy goes well with fusion) and they mix up the damage types caused by fusion (brute from explosion, burn from zap, tox from radiation/particles). I added TESLA_FUSION_FLAGS because the tesla zaps defaultly just ended up exploding whatever they came out of (canisters usually) and ruined the whole thing.
- BZ fusion power nerf, nitryl fusion power buff

These go hand in hand. When I first made BZ useful for fusion, I completely forgot (or maybe it just wasn't merged yet, don't remember) that xenobio started with a BZ canister. So, it was super easy to cheese high/super tier fusion by just stealing the canister from xenobio. Thus, I switched BZ's role in fusions progression to nitryl instead, which is harder to make and currently doesn't see much usefulness outside of making it for stimulum.
- Fusion analyzing, addition of analyzer_results to datum/gas_mixture

I quickly realized after my fusion rework that there wasn't any ingame way to really quantify how good a fusion reaction was, which is a mistake on my part. Now, you can analyze the power of a fusion reaction and its tier after it happens. I added analyzer_results, since reaction_results worked in a matter that didn't fit what I wanted (reset completely every react() cycle) and I didn't want to change it. analyzer_results is only ever initialized when it's actually going to be used, which currently is only for fusion.
- Overall fusion code cleanup

Pretty self-explanatory. I moved all the effects (radiation, tesla zap, etc) to one area instead of having it happen separately for every tier. Now the tiers just set variables used for those effects. Apologies if the diff is kinda hard to read.
- Changes to gases created

Low tier is now BZ/CO2, mid tier is nitryl/N2O, high tier is stimulum/pluoxium, and super tier is tritium.
Gas creation numbers are lower across the board, mostly for bz/nitryl/stim.
BZ/nitryl/stim were added in low quantities to the tiers to help with the progression of the various tiers. It didn't really make sense that before, super tier fusion gave stimulum/pluox when the only feasible way to get super tier fusion was using stimulum, and the low tier rewards were straight up useless. Tritium for super tier was chosen because I think it's the gas with the most potential of causing a massive disaster in this scenario.
- Plasma no longer counts towards gases fused

Before this change, I realized that you could just stack as much plasma as humanly possible and a minimum amount of trit to instantly get several thousand moles of BZ and potentially other gases for free. No thank you.

I'm still not 100% satisfied with fusion, so expect more PRs like this in the future.

### CODE REVIEW

**Comment by optimumtact** [comment]
Hahaha surely it won't be completely absurdly overpowered this time right

**Comment by cyclowns** [comment]
considering my rework last time has proven it isn't, and this doesn't change much of the 'overpowered' portion, no it won't

**Comment by granpawalton** [comment]
the bz nerf is needed

**Comment by praisenarsie** [comment]
[I EXPECT YOU TO DIE](https://youtu.be/ht1ZChKF4Ek)

**Comment by davethwave** [comment]
The BZ fusion WAS nerfed. It's now a lower tier fusion instead of high tier.

**Pull request merged**
