### PR TITLE
USB cables can now be attached directly to bluespace launchpads

### PR DESCRIPTION
**Pull request by Y0SH1M4S73R**
## About The Pull Request

See title. Because of this change, a launchpad does not need a connected console if you have no need for it. You can still use the console to control a launchpad, and you can still connect a USB cable to a console to control all its connected launchpads with a single circuit component.

## Why It's Good For The Game

Reduces the boilerplate necessary in setting up a circuit-controlled launchpad.

## Changelog

:cl:
qol: USB cables can connect directly to bluespace launchpads. As a consequence, You do not need a console for a launchpad if you only intend to control it via circuits.
/:cl:

### CODE REVIEW

**Comment by Watermelon914** [comment]
There is use to having it connect to a console, specifically the fact that you can set up a system using multiple launchpads. I recommend having both be an option, to allow a connection from the console (as to more easily manage the launchpads) and allowing it to directly connect to a launchpad too

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Briefcase launchpads intentionally don't have circuit support because they don't have the long delay/charge up. Giving them circuit support would mean bringing back some old strategies that I did not like such as insta-click teleport into gibbers. However, I do not want the briefcase launchpad to be nerfed, so please remove their circuit support. See #61999

**Comment by Y0SH1M4S73R** [comment]
> Briefcase launchpads intentionally don't have circuit support because they don't have the long delay/charge up. Giving them circuit support would mean bringing back some old strategies that I did not like such as insta-click teleport into gibbers. However, I do not want the briefcase launchpad to be nerfed, so please remove their circuit support. See #61999

When I tested it, the briefcase launchpad wasn't instant. May have been a *slightly* shorter cooldown than a normal launchpad. Perhaps the lack of indicative particles keeps the balance concern relavent. Either way, I'll remove USB support from it.

**Comment by moocowswag** [comment]
Im wondering what situations to build a launchpad like this for. The console is actually valuable for other conviences too, like an easy way to feed it coords to send yourself to a location, plus you dont want the circuit near the pad if youre weaponizing it.

Im not really making arguements against this pr i just cant think of any reason to build a pad like this.

**Pull request merged**
