### PR TITLE
[15.ai] [April Fools] The Nanotrasen Voice Module subscription has expired.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
Replaces all the bot audio with different voices.
Adds idle lines to Beepsky, along with making him properly say his voicelines for arrests.
Adds voice acting to the hygiene bot.
Adds idle lines to the Firebot.
## Why It's Good For The Game
We need to re-activate the Nanotrasen Voice Module, guys. Until then, the bots are gonna sound slightly weird.

### CODE REVIEW

**Comment by Kylerace** [comment]
:trollface:

**Comment by tralezab** [comment]
>

**Comment by Mothblocks** [comment]
For the benefit of the maintainers, April Fools PRs will be labeled and closed. Key Holders are still able to test merge PRs that are closed, so this makes no difference to you, the author, assuming you were able to find a Key Holder to merge this PR in the first place.

**Comment by TheBonded** [comment]
@Iamgoofball 
make this into a station trait **_please_**

**Comment by Iamgoofball** [comment]
maybe

**Comment by TheBonded** [comment]
> maybe

if you do, please @ me in a comment so I can come see the pr

**Pull request closed without merging**
