### PR TITLE
Fixes the E.X.P.E.R.I-MENTOR and related reagent runtime

### PR DESCRIPTION
**Pull request by GunHog**
The "FAIL" define was set equal to the "SCANTYPE_DISCOVER" define,
resulting in the machine thinking everything was a relic and calling a
nonexistant reveal() proc on it.

You may now return to your regularly scheduled program of setting yourselves on fire, EMPing half of Science, teleporting Ian, and irradiating yourself.

Note: This PR also includes a fix for the reagents runtime! Thanks Goof!

### CODE REVIEW

**Comment by Deantwo** [comment]
Are all these fixed?
http://hastebin.com/wewafazove.rb

**Comment by GunHog** [comment]
They should be now, thanks to Goof

**Comment by Miauw62** [comment]
Can this be merged?

**Comment by GunHog** [comment]
Well, the fix for the reagent runtimes is not complete. I am getting them for nearly every reagent the machine can make, so I am not quite sure what the problem is. Goof would know more than I do.

**Comment by GunHog** [comment]
Problem with reagents should go away now, I did not encounter any while I was testing (before I died in a plasma fire, at least). This is now ready for a Maintainer to review and test.

**Pull request merged**
