### PR TITLE
Adds a way for admins to disable deadchat

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by kevinz000** [comment]
good now i can make good on my threats of "stop fucking with each other or i'm muting dchat"

**Comment by Armhulen** [comment]
...

**Comment by obscolene** [comment]
(F) DEAD: Harold Robinson says, "REACTIVATE MY OOK"
DEAD: ADMIN(Cyberboss) says, "i can disable d-chat too"
(F) DEAD: Steals-the-Bolts says, "no you cant"
(F) DEAD: Klara Ellstrom says, "no you cant"
DEAD: ADMIN(Cyberboss) says, "dont test me"
 
2 minutes later 

DEAD: ADMIN(Cyberboss) says, "you guys"
DEAD: ADMIN(Cyberboss) says, "got lucky"
PR: Pull Request opened by Cyberboss: #27207 Cyberboss - Adds a way for admins to disable deadchat

**Comment by Shadowlight213** [comment]
Make this a verb not a var.

**Comment by KorPhaeron** [comment]
In what circumstances will these be desirable?

If someone is shitting up deadchat mute them, dont collectively punish everyone and kill server pop by making ghosts miserable

**Comment by KorPhaeron** [comment]
As obnoxious as ghosts can get I strongly believe this will be detrimental to the server and community if the primary social meeting point is disabled

**Comment by optimumtact** [comment]
classic cyberboss

**Pull request closed without merging**
