### PR TITLE
this should deal with those pesky atmos runtimes

### LINKED ISSUE #17248: Atmos runtimes in temperature_share()
https://github.com/tgstation/-tg-station/blob/6a2df04760db0808973a2ceea26ab2e89bb130aa/code/modules/atmospherics/environmental/LINDA_turf_tile.dm#L375
https://github.com/tgstation/-tg-station/blob/6a2df04760db0808973a2ceea26ab2e89bb130aa/code/modules/atmospherics/environmental/LINDA_turf_tile.dm#L407

temperature_share() is called there with null as first argument, this is causing the following runtimes:

[19:32:37]Cannot read null.temperature
[19:32:37]proc name: temperature share (/datum/gas_mixture/temperature_share)
[19:32:37]  source file: gas_mixture.dm,505
[19:32:37]  usr: null
[19:32:37]  src: /datum/gas_mixture (/datum/gas_mixture)
[19:32:37]  call stack:
[19:32:37]/datum/gas_mixture (/datum/gas_mixture): temperature share(null, 0.025, 293.15, 1e+031)
[19:32:37]the vacuum floor (151,74,1) (/turf/open/floor/engine/vacuum): finish superconduction()

runtime error: 
[19:32:38]Cannot read null.temperature_archived
[19:32:38]proc name: temperature share (/datum/gas_mixture/temperature_share)
[19:32:38]  source file: gas_mixture.dm,494
[19:32:38]  usr: null
[19:32:38]  src: /datum/gas_mixture (/datum/gas_mixture)
[19:32:38]  call stack:
[19:32:38]/datum/gas_mixture (/datum/gas_mixture): temperature share(null, 0.025, null, 1e+031)
[19:32:38]the vacuum floor (150,74,1) (/turf/open/floor/engine/vacuum): finish superconduction()

These runtimes happens A LOT ("The following runtime has occurred 1407321 time(s)."). Pretty much whenever there's a fire.

@duncathan

### PR DESCRIPTION
**Pull request by duncathan**
fixes #17248

### CODE REVIEW

**Comment by KazeEspada** [comment]
Why would sharer be null?

**Comment by phil235** [comment]
@KazeEspada because some parts of the code calls temperature_share(null, x, y, z)

**Comment by KorPhaeron** [comment]
This is important

**Comment by duncathan** [comment]
Sharer being null is intentional.

**Pull request merged**
