### PR TITLE
Raptor and Shawl icons/Unused icons

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Spriters often make sprites for projects that never get finished, or projects that are never started.

Coders often don't have sprites

Would putting sprites that are made for SS13 that nobody has used yet into an unused folder so they're not scattered across a dozen places/lost to time be a terrible idea?

### CODE REVIEW

**Comment by KorPhaeron** [comment]
I guess we could probably find a different place to store these all that doesn't increase the file size here

**Comment by ExcessiveUseOfCobblestone** [comment]
Have a separate repository for individuals who want to PR their own sprites but don't have a code home for it.

**Comment by MrDoomBringer** [comment]
Yesss @ExcessiveUseOfCobblestone I have a fuckton of unused sprites.

**Comment by ExcessiveUseOfCobblestone** [comment]
Having a judgement free zone (since it's not being added to the game yet) where people would be willing to give you good tips on how to improve as a spriter would also be nice.

If it's in its own repo you could also tack on tutorials in there.

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/tgstation-sprites

**Pull request closed without merging**
