### PR TITLE
adds myself to the credits

### PR DESCRIPTION
**Pull request by ghost**
i've contributed, what's a man to do to get respect on the streets? Tell me if I'm doing this wrong btw

### CODE REVIEW

**Comment by YakumoChen** [comment]
add me too

**Comment by PraiseRatvar** [comment]
@Cyberboss aaaaaaaAAAAAAAAAAA FUCK

**Comment by Cyberboss** [comment]
I'm setting up an automatic process to do this, be patient

**Comment by Cyberboss** [comment]
@YakumoChen you're already on

**Pull request closed without merging**
