### PR TITLE
Fixes empty oxygen tanks in icebox chapel.

### LINKED ISSUE #75341: Ice Box Station - Oxygen Tanks In Chapel Start Empty
Reporting client version: 514.1589

## Round ID:
[205448](https://scrubby.melonmesa.com/round/205448)

## Reproduction:

>Open icebox station 
>Get tank from chapel (bottom left)
> use it and go outside
> die because it has no oxygen in it

pls fix

### PR DESCRIPTION
**Pull request by orthography**
## About The Pull Request

As the PR name says.

## Why It's Good For The Game

Fixes #75341

## Changelog
:cl:
fix: replaces empty oxygen tanks in icebox chapel.
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
lmao nice

**Comment by ShizCalev** [comment]
there's another empty one on birdshot too, not sure if it's intentional.

**Comment by orthography** [comment]
> there's another empty one on birdshot too, not sure if it's intentional.

In the chapel?

**Comment by san7890** [comment]
you can search it up by typepath in strongdmm.

**Pull request merged**
