### PR TITLE
Mouse Cursors 2: Cursor Boogaloo

### LINKED ISSUE #10106: Can't fire through smoke
I noticed this while fighting a blob today. When you destroy one of the blob spores (or whatever they're called), they leave a smoke cloud (as usual) but because it obscures your vision (leaving black squares behind it) you're unable to fire through it, which prevents you attacking further blob spores or other threats after you destroy one. You have to simply retreat until the cloud clears or the spores advance past it.

### PR DESCRIPTION
**Pull request by Iamgoofball**
okay so this is basically #6616 electric boogaloo

I fixed the flickering on the chat box and verb box, by making it so it doesn't use the cursor on non atoms.

BONUS: In order to get this working, I noticed that your cursor disappeared when you were hovering over darkness.

To fix this, I lifted the "click in darkness" crap from @Razharas autoclicker PR

so you can click the darkness now

c930fd88-8d75-11e4-8e3e-d98c79247561
c8055b98-8d75-11e4-97b2-9d847b7aac7d
c70997d6-8d75-11e4-995b-4e38b190ab59

Fix https://github.com/tgstation/-tg-station/issues/10106

### CODE REVIEW

**Comment by RemieRichards** [comment]
PICS

**Comment by Iamgoofball** [comment]
@RemieRichards soon

**Comment by Iamgoofball** [comment]
OP updated w/ pics

**Comment by vista-** [comment]
Does this work well with Wine?

**Comment by Iamgoofball** [comment]
no clue, can't test it

**Comment by Miauw62** [comment]
we really can't support linux, especially since there isnt even an official DS version for linux.

**Comment by RemieRichards** [comment]
Webclient can support linux and mac, that's why Lummox has said linux and mac clients are off the table. However we're not supporting the Webclient anytime soon (mainly because SS13 just doesn't work at the moment, and I have 0 clue how far Bay got with getting it to work for them)

**Comment by Jordie0608** [comment]
Mouse pointer icons need a hot-spot set.

**Comment by Miauw62** [comment]
esword would make a pretty funny mouse pointer too :V

**Comment by vista-** [comment]
This is how broken it looks like on Linux with Wine 1.7.45
http://puu.sh/ipDC7/b492d6b4e8.webm

Not worth it for a small cosmetic change.
:-1: :100:

**Comment by Midaychi** [comment]
I can confirm that it functions as displayed in above webm for my wine as well, though the transitions between cursor and plus sign are much faster and smoother.

Idk I kind of like the plus sign though.

**Comment by CorruptComputer** [comment]
>Linux 

There's your problem, join us in the glorious Windows master race.

**Comment by Midaychi** [comment]
Yeah I agree, even though I use it myself, this project should support Linux unless lummox suddenly decides to start supporting it too. Why throw away perfectly cool features because some wine dev took a stupid shortcut or made a decision on vague api documentation that interferes with it?

**Comment by vista-** [comment]
My problems with this PR - even if this feature is disabled, the cursor breaks with Wine. 

I'm fine with this as long as webclient compatibility is rolled out before this is merged.

**Comment by Iamgoofball** [comment]
I can probably fix the plus sign

**Comment by Razharas** [comment]
@Iamgoofball FIX IT GODDAMN THE CLICK FEATURE IS SO NICE YOU ARE HOLDING IT BACK

**Comment by Razharas** [comment]
Ask someone to reopen it if you decide to return to it

**Pull request closed without merging**
