### PR TITLE
votes now play a sound when they get started

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
admin: votes now play a beep noise when they get started
/:cl:

sometimes map votes get started by server or griefers after shuttle launches, which no one notices and get rigged by people voting boxstation without anyone knowing and votes should have a sound effect to prevent this and other malicious actions by evil people

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Can we get a toggle for this?

**Comment by optimumtact** [comment]
this should be a gentle chime, not this ear damaging horn

**Review by kriskog — CHANGES_REQUESTED** [review]
Yeah thats another no on the sound. Use something nicer. Perhaps https://freesound.org/people/tim.kahn/sounds/130377/ ?

**Comment by Tlaltecuhtli** [comment]
the website asks my credentials to download the sound, do you have a place where its free to download?

**Comment by kriskog** [comment]
Allright. Since its licensed under CC attribution, you need to add a license file with the information. You can use the format of https://github.com/tgstation/tgstation/blob/master/sound/effects/license.txt for instance.
I also shortened and faded it out slightly, you can grab it here: https://github.com/kriskog/tgstation/blob/sound/sound/misc/bloop.ogg

**Comment by kriskog** [comment]
Make a new license text file in the misc folder so its easier to keep track of it

**Pull request merged**
