### PR TITLE
Adds an arrival lobby to centcom.

### PR DESCRIPTION
**Pull request by WJohn**
For coiax.

### CODE REVIEW

**Comment by WJohn** [comment]
I don't know how to remote so he told me to do this instead.

**Comment by coiax** [comment]
- Not all of the air pumps are on, some are red
- There's a lightbulb embedded in the wall on the south side.
- The departure lounge in the North can be seen from the north spawn
- The maintenance doors don't require Maintenance access
- The area is called Admin Prison, and is omnilit.
- The south departure longue needs more chairs
-There's no clothesmate in the north
- There's no shuttle timer displays, or intercoms for announcements
- There should be more scaffold visible from the space view
- I love the assistant clothes wardrobe in the south maint, but there's no equivalent stuff in the north maint

**Comment by Niknakflak** [comment]
This is a really ugly map

**Comment by Incoming5643** [comment]
Why would you intentionally create choke points in the post round murder area.

**Comment by lzimann** [comment]
why though

**Comment by PKPenguin321** [comment]
does this add on to centcomm or replace it
if it adds on sure fine whatever
if it replaces then fuck no, this is a straight downgrade and looks like trash

**Comment by Jordie0608** [comment]
@PKPenguin321 Looking at the file diff, this is a docking zone for the arrivals shuttle, possibly to allow it in the future to transit from here to the station

However I don't see why this should be added as it doesn't yet have any function.
There's quite a bit of inaccessible content, is that meant to just be for flavour?
For instance why are there functional atmos and power networks on centcom?

**Comment by RemieRichards** [comment]
This isn't being added, read:

>WJohn commented 4 hours ago
I don't know how to remote so he told me to do this instead.

he being coiax, this PR is just so coiax can grab the map file, this PR isn't to be merged

**Comment by Niknakflak** [comment]
Yea but does that mean that coiax intends to use this abomination of a map?

**Comment by RemieRichards** [comment]
ya

**Comment by Niknakflak** [comment]
>internal screaming

**Comment by coiax** [comment]
This map was designed by WJohn on my request; if you have an issue with the map, take it up with him. I think it's great, and WJohn has done a great job of making a coherent map out of my half boiled ideas.

**Comment by pudl** [comment]
CANT ESCAPE THE FILTH MAINT MEME EVEN AT CENTCOM FUCK

**Comment by optimumtact** [comment]
there's no reason to leave this open?

**Pull request closed without merging**
