### PR TITLE
[READY] Adds Purified Soulstones and Constructs

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Purification of a soulstone (hitting it with a bible as noncult) no longer destroys the stone, and releases a spirit. Instead, it purifies the stone, which is crew friendly and has a new sprite. Said stones can be placed into construct shells to create purified angelic constructs, which are easily distinguishable from cult/wizard constructs. 

## Why It's Good For The Game

Crew finding and using construct shells to create stealthy anti-cult constructs sucks. This PR would get rid of this shitty gameplay, and adds some new flavor to the whole cult/anti-cult dynamic. 

## Changelog
:cl: weeeeesoda
add: You can now purify soulstones! This can be done by any crew member using a bible on one. 
add: Purified constructs can be created by using a purifed soulstone on a construct shell. Amongst their normal abilities, purified constructs can dispel cult runes by clicking on them.
del: Ability to place chaplains soulstone or mining soulstones in construct shells
imageadd: angelplasm, angelic sprites, purifed sprites
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
bro i swear some madman hacked my account and made 30 extra commits its not my fault dont look at me

**Comment by tralezab** [comment]
really cool but those sprites are boring wow

**Comment by DaxDupont** [comment]
Jesus christ learn to merge comits

**Comment by habader** [comment]
send pics

**Comment by ExcessiveUseOfCobblestone** [comment]
> it's an entirely webedited PR

**Comment by OverlyGeneric** [comment]
sprites are pretty boring. not really angelic.

**Comment by wesoda25** [comment]
dont worry mr tralezab is supposedly making new sprites for me

**Comment by HomocidlePancakes** [comment]
Angelic construct should shit out already purified soulstones

**Comment by ATH1909** [comment]
I like this because this will mean that my chaplain shades will get lynched less often.

Personally, I feel like the cult infiltration thing was kind of cool, but I'm fine with it being removed if we get to have this.

**Comment by FantasticFwoosh** [comment]
I think giving chaplains more 'cult' features that can damage balance is a slippery slope bad idea, not that im against leaving unsecured constructs to be destroyed or subverted.

Im happy to just sit out for another PR to improve the sprites.

**Comment by Shadowflame909** [comment]
I'm the idea guy

and Oranges senpai ignored me

**Comment by ExcessiveUseOfCobblestone** [comment]
this is a major nerf to that rune that revives cults when you can delete bodies with a click of a button.

**Comment by wesoda25** [comment]
Cobby idk what you’re saying

**Comment by ExcessiveUseOfCobblestone** [comment]
There is a rune that revives cultists.

That rune is useless when the cultist bodies are dusted to make anti-cult constructs that churn out more stones that make anti-cult constructs that churn out....

It's prob not too big of a deal since you could hide the bodies/ gib them / incin them, but at least all of those can be countered in some way. If the chaplain gets his hand on a soulstone and especially a shell, you're basically fighting an uphill batter (moreso than normal) the rest of the round.

That's not to say this shouldn't be merged tho.

**Comment by necromanceranne** [comment]
You mean like the crew has to deal with fighting the cult while it ramps up?

It would be fairly ironic and daunting to end up having a landslide occur because the chaplain got his hands on a single shell. Does this work for wiznerd Artificer stuff?

**Comment by wesoda25** [comment]
> That rune is useless when the cultist bodies are dusted to make anti-cult constructs that churn out more stones that make anti-cult constructs that churn out....

Solution here being don't leave your comrades bodies lying around. Cult has the exact same landslide element, except its faster, more dangerous, and extends to the living. At the end of the day it still requires a _dead_ cultist, whereas cult requires a stunned person. 
> It's prob not too big of a deal since you could hide the bodies/ gib them / incin them, but at least all of those can be countered in some way. If the chaplain gets his hand on a soulstone and especially a shell, you're basically fighting an uphill batter (moreso than normal) the rest of the round.

I'd like to also point out my PR wouldn't change anything. Chappy can already do this, and its been happening a lot as of late (kinda). My PR is more of a buff to cult, since they can now distinguish easily between cult contructs and angelic constructs. So no, I don't think there will be balance concerns. If there are, we can revisit the issue at a later date. 

>Does this work for wiznerd Artificer stuff?

Wizard classifies as a cultist, uses the same soulstone as them, with some flavor text difference. In order for crew to use a soulstone, they must first purify it.

**Comment by wesoda25** [comment]
> Angelic constructs should shit out already purified soulstones

Done, also they can't spawn runed walls/floors anymore.

**Comment by AdamElTablawy** [comment]
not sure how fair it would be that one lost soulstone could result in the crew building their own anti-cult unstunnable construct army. unless i'm misreading something this is a soulstone anyone can use that can capture the souls of anyone, like ordinary cult soulstones

and therefore the crew can take any single soulstone they find and make an artificer with it, and then continually sacrifice willing volunteers (or cultists, or unwilling volunteers at a certain point, or just dead bodies without a soul to draw from the ghost pool) to make yet more constructs and build their own construct army

since the crew can easily tell them apart, there's now no risk of accidentally shooting crew-sided constructs because you think they're evil. so it'd just sort of create a landslide.

iunno about having the artificer being able to spawn additional soulstones, is what i'm saying. it should come from capturing soulstones from cultists rather than one fuckup resulting in an enormous construct army.

**Comment by PKPenguin321** [comment]
I feel like constructs are inherently evil and unnatural so it's bizarre that the "good" side would be able to use them at all. That's just me though

**Comment by AdamElTablawy** [comment]
being able to create a holy warrior who has chosen of their own volition to bind their soul to a suit of armor to fight evil is pretty much as chaplain kill-the-heretics-and-fight-evil as you can get, so it makes sense

the issue is just that the chaplain would be able to create their own construct army with even one lost soulstone as they could make their own angelic artificer-and not run into the issue of losing them to people who don't realize the constructs are crew sided. 

preferably they should be comparatively rare and depend entirely on capturing and purifying already filled soulstones rather than stoning monkeymen corpses and waiting for ghosts to fill up the stone and slotting it into one of your 20 shells and spiralling from there.

**Comment by Tlaltecuhtli** [comment]
tbh just give one angelic average construct with no special powers so people sharded captured by crew can help/play without being a shitty ghost.
sharding the cult back because you found a shell in maint and now you have an artificer shitting out shards all day is dumb

**Comment by RaveRadbury** [comment]
> bless: gives 30s of antimagic to ppl around and self heals

If this happens consider adding the "Blessed" mood event as well.

**Comment by ATH1909** [comment]
> tbh just give one angelic average construct with no special powers (instead of the cult types) so people sharded captured by crew can help/play without being a shitty ghost.
> sharding the cult back because you found a shell in maint and now you have an artificer shitting out shards all day is dumb
> 
> here some powers for the construct u can use without copyrights:
> dispel:aoe removes runes/cult structures
> bless: gives 30s of antimagic to ppl around and self heals

Maybe make purified soulstones make this generic construct when slotted into a construct shell, cult/wizard soulstones make the normal cult constructs when slotted into a construct shell, and the chaplain's special "usable by anybody" soulstone make non-cult (but also not holy) constructs if not purified when it is slotted into a construct shell like it currently does. That way, the crew needs the chaplain's specific roundstart soulstone to start pumping out crew-aligned cult constructs (instead of just any old soulstone that they can pick up off of the ground and purify with a bible).

**Comment by ExcessiveUseOfCobblestone** [comment]
In the PR's defense, you need both a stone (relatively easy to obtain) and a shell (much harder, especially when cult can craft as needed)

**Comment by AdamElTablawy** [comment]
you only need one shell to start a steamroll

**Comment by wesoda25** [comment]
See thats the thing though, its already entirely possible. This mechanic is in the game already, what I'm doing is basically just adding blue variants to everything. So far, this has not resulted in any sort of steam roll type deal, since they're still constructs, and constructs are weak as shit. Its not as if each one has the strength to take on 5 cultists and win, far from it. This is quite literally a cult _buff_, since before, it was very, very difficult for cult to differentiate between their constructs and crew constructs. 

I do like the idea of just a single construct though, but I might just keep the 3 as is. I also wanna add some spells along the lines of tlal post, namely a holey AOE spell, which purifies ground around it and purges cult spells and shit.

**Comment by necromanceranne** [comment]
wesoda's got the right of it. Since we have it already as a half-existing obscure mechanic it would be better as a completed feature of the mode

**Comment by AdamElTablawy** [comment]
this is a cult nerf, not a cult buff, Wesoda.

cultists can tell their constructs apart.

the crew cannot.

if you make it so that the crew can distinguish between friendly and hostile constructs with their own sprite, then the main obstacle to a counter construct army from the chaplain-that the crew will kill them-is lost.

**Comment by habader** [comment]
do wizards get cult or angelic constructs then?

**Comment by imsxz** [comment]
i dont think it'll be that much of an issue tbh the constructs dont multiply that quickly when theyre limited by finding unused shells or waiting for the angelic artificer to shit it out every 3 minutes, and also limited by getting soulstones (either taking already ensouled shards from looting cultists or sharding dead bodies with the 1 angelic soul stone they get every 5 minutes from the arti)

it wouldnt really snowball unless the cult just left around a fuckload of shells/active soul stones (you cant purify or use normal, uninhabited cult soul stones, and the stones are destroyed when you make them into a construct). I feel it'd add another neat sort of rare feature to cult that could end in some interesting interactions, worst case scenario it's not like cult would be that hurt from a small change like this. To get a anti-cult construct army really snowballing off of 1 soulstone and 1 stolen shell, you'll need like 15 minutes at least to get a few artificers ready to pump out shells/shards with /any/ effective frequency.

**Comment by wesoda25** [comment]
> this is a cult nerf, not a cult buff, Wesoda.
> 
> cultists can tell their constructs apart.
> 
> the crew cannot.
> 
> if you make it so that the crew can distinguish between friendly and hostile constructs with their own sprite, then the main obstacle to a counter construct army from the chaplain-that the crew will kill them-is lost.

CUlt doesnt have time to differentiate between their constructs and crew constructs. Most of the time, they don't expect it at all. This results in constructs stealing sac targets, destroying bases, etc. cult buff

**Comment by AdamElTablawy** [comment]
there is a floating icon over cult constructs that tells cultists if they are aligned or not-so they’re recognized instantly on sight

The crew however can’t tell it apart and usually kill constructs on sight

If you give them a floating ‘not antag’ sign by giving them a custom easily identified sprite it removes the risk of friendly firing constructs

**Comment by AdamElTablawy** [comment]
It’ll snowball like wizard snowballs, for the record. Which is comparatively slower, but still usually leads to a blob of constructs-and considering they’ll be fighting a much smaller enemy without any main defenses against them (due to lack of guns by default and being forced into meleeing the things usually within the tight corridors of cult bases, and potentially having their bases breached to space by those constructs) the slow startup isn’t that much of an issue either

**Comment by wesoda25** [comment]
lol that never happens with wizards, and it never happens in cult. This is already a fucking mechanic, so its not gonna go any more snowballing than it already did. no one checks hte cult antag hud since they think constructs are universally cult, this is a buff. Take it from someone who actually plays very often and has encountered this numerous times.

**Comment by AdamElTablawy** [comment]
it's already a mechanic except the crew can _and does_ shoot at friendly constructs thinking they are hostile. 

it's not any riskier than it currently is mechanics-wise except the fact that the crew can identify those constructs as non-antag as a glance makes it much easier for the chaplain to build up an anti-cult construct army without worrying about the crew killing them in the halls if he's not next to them constantly shouting 'DON'T SHOOT.'

the snowball effect is the same as it always was and nothing will change there, but the main issue is just that the crew won't shoot the constructs by mistake, thus allowing for greater numbers without risk

**Comment by wesoda25** [comment]
I suppose thats true. But at the end of the day, I feel its outweighed by the disadvantage cult is put at by "fake" constructs. Agree to disagree I guess, thats my opinion. I also feel the constructs really won't be able to snowball, given how weak they are. If anything its incentive to not leave shells lying around. If its so bad an issue, it could be unmerged (if it is merged in the first place).

**Comment by wesoda25** [comment]
Alright, the PR is done. Constructs destroy runes on touch now, but no other anti magic type spells. I tied up some loose ends, and fixed some bugs.

**Comment by wesoda25** [comment]
modsss?!!!

**Pull request merged**
