### PR TITLE
Playtest testmerge PR to combine virology and genetics on meta 

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
## About The Pull Request

This PR moves cloning and genetics in meta over to an expanded virology sat, now called "medical research." The mapping is quite coarse and not intended to be final, this is just to test the concept in a testmerge fashion.

The proposed endgoal is combining the jobs of virologist and geneticist into one medical researcher job, who is in charge of cloning, genetics and virology in the same way scientists have a number of "sub-jobs" they can choose from.

Changelog not included as this is not intended to be merged.

### CODE REVIEW

**Comment by actioninja** [comment]
Interesting

**Comment by HomocidlePancakes** [comment]
Remove MDs, have robos do the surgery and have the 3 medical jobs left heal people alongside their regular stuff.

**Comment by kriskog** [comment]
What every virologist ever wanted: Hulks with tk and xray near the deadly infectious diseases.

This would be a very big viro nerf, since antag viro relies heavily on planning and secrecy before you launch your virus. Having people through the doors every time someone needs cloning doesn't mix well with that. Something to consider if this goes past a playtest.

**Comment by HomocidlePancakes** [comment]
I disagree. Botany and xenobio exist and noone cares about them making überdethopplsnerf. People just assume it’s to powergame and not to antag. If you check viro as CMO you can find him making super aids pretty often just because he can, but moat of the time he won’t end up using it

**Comment by knacker48** [comment]
While I do like the idea of jobs having multiple things to do I'm not sure that geneticist or virologist were really lacking. That said I honestly have no problem with this in principle and I'm interested to see if this will be an improvement or not.

**Comment by datorangebottle** [comment]
> I disagree. Botany and xenobio exist and noone cares about them making überdethopplsnerf. People just assume it’s to powergame and not to antag. If you check viro as CMO you can find him making super aids pretty often just because he can, but most of the time he won’t end up using it

just as a point, xenobio has the same level and need of/for secrecy that viro currently has.

Unless it's also moved to the satellite, but then nobody will play scientist anymore because the only things to do are R&D, bombs, and nanites. Plus, the new satellite job would be completely overloaded with the would-be xenobio mains, when genetics and viro mains are already numerous.

Maybe move it to the sat and give it a separate job slot? I could see Xenobiologists severely getting in the way of people signing up for medical researcher if rolled into the same slot.

**Comment by vuonojenmustaturska** [comment]
virology is not xenobiology

**Comment by HomocidlePancakes** [comment]
This PR has four fours. It's a sign from god that we are moving in the right direction

**Comment by zxaber** [comment]
I know every map places genetics and cloning side-by-side, but I don't actually think there's a need for it. We could just leave cloning where it was. Or, for a more permanent solution, move cloning to replace the current surgery area, and turn old cloning and old genetics into two surgery rooms.

**Comment by vuonojenmustaturska** [comment]
replacing the old genetics area with a double surgery shared between medbay and robotics was something i was toying with, but i just merely want to see what combined viro/genetics will do

**Comment by NoxVS** [comment]
Im pretty sure its this PR that completely fucked up wiring in maint by medical.

**Comment by datorangebottle** [comment]
> virology is not xenobiology

I brought it up because i was making a point and then had an idea about it while i was making that point. Read the damn post first.



> I know every map places genetics and cloning side-by-side, but I don't actually think there's a need for it. We could just leave cloning where it was. Or, for a more permanent solution, move cloning to replace the current surgery area, and turn old cloning and old genetics into two surgery rooms.

Geneticists tend to not do cloning anyway, so leaving it where it was is ideal- just change the access on the door to let MDs in.

**Comment by francinum** [comment]
Isolating cloning like this only makes it easy to destroy with no repercussions, as you no longer need to actually walk past medbay staff.

**Comment by datorangebottle** [comment]
> Isolating cloning like this only makes it easy to destroy with no repercussions, as you no longer need to actually walk past medbay staff.

Permanently destroying cloning requires you to destroy engineering as well. And Science. And Robotics. And any other imprinters anyone else has ever constructed during the course of the round. And every machine because getting the parts isn't that hard.

**Comment by zxaber** [comment]
Far as I am aware, MDs already have cloning access, even on normal pop.
My best guess is that cloning was just tacked onto genetics because it was originally a bug that genetics could do to bring people back in (or so I'm told), and has just stuck there for tradition's sake.

**Comment by vuonojenmustaturska** [comment]
this PR was good

**Pull request closed without merging**
