### PR TITLE
WIZARD BUFF

### PR DESCRIPTION
**Pull request by Iamgoofball**
We checked stat gathering today.

Wizard had a win rate of (RATING: 15%).

No.

:cl: Iamgoofball
rscadd: Wizard now has 20 charges on his spellbook instead of 10.
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
>20 charges

ha ha ha ha goof you're an idiot this will end in 5x timestop plus whatever else

**Comment by Iamgoofball** [comment]
15
percent
winrate

**Comment by TechnoAlchemisto** [comment]
I think this would be better resolved by making other wizard builds more viable, not by making it so I can take the ULTIMATE BUILD, as well as a bunch of other shit.

This honestly make killing the entire station easy for anyone who isn't garbage.

**Comment by kilkun** [comment]
I like this but wizzies need to git gud.

10 tc is more than enough for a wizard to shit on even the biggest of power gamer.

Just give the wizard the rending blade back for 5 tc

**Comment by Iamgoofball** [comment]
@technoalchemisto if there was an ULTIMATE BUILD than there wouldn't be  15 PERCENNT WINRNATE

**Comment by kilkun** [comment]
@Iamgoofball 

jaunt + timestop + mutate + disintegrate + scrying orb

I'm unrobust as shit but I've yet to lose a round of wiz with that loadout.

**Comment by Iamgoofball** [comment]
was it low pop or high pop

**Comment by Saegrimr** [comment]
The win rate is so low because wizards
-Kill themselves with fireball
-Retarded "friendly wizard" memes
-Drop their staff of change and get turned into a slime
-Teleport into space
-Teleport into the engine
- http://puu.sh/nTWap/ba03e4e16d.gif
-Get set on fire.
-Don't actually care about greentext because WIZARD! Teleporting around being a flaming jackass is fun.

More points is only going to make that last part even more true, and not prevent any of the others.

**Comment by Xhuis** [comment]
Yep, this confirms it. Goofball has no idea how to balance games.

The winrate is primarily for several reasons. For one, you become wizard so little on average that it's very hard to get experience. For two, wizards don't always focus on objectives and maybe try to have a little fun. There's so many options available that maybe I want to do my permafire gimmick instead of picking the spells that guarantee me the ability to kill anyone.

This doesn't mention the fact that most players on /tg/ are powergamers. If you say "WIZARD" over radio, some people would ask where he was and others would wordlessly arm up. Chemists would get their syringe guns and self-surgery meth pills to reduce stuns.

And yes, there is an easy win button. Magic missile and ethereal jaunt will make it extremely easy to both stun people and escape from almost any confrontation. Combo with Teleport and nobody can catch you unless you're predictable with your teleports.

**Comment by kilkun** [comment]
@Iamgoofball high pop with mekhi running hos

**Comment by KorPhaeron** [comment]
epic

**Comment by Xhuis** [comment]
I think you're a little too trigger-happy with closing PRs, Kor.

**Comment by RandomMarine** [comment]
@Saegrimr I was around for that gif, fucking hilarious.

**Comment by KorPhaeron** [comment]
Literally my job to close bad PRs

**Comment by Zilenan91** [comment]
Basing wizard around winrate is a terrible terrible terrible way to balance it.

**Comment by Xhuis** [comment]
"Bad" is opinionated, but I guess you have a point.

**Comment by ChangelingRain** [comment]
For 20 points, you can: buy a gemsuit, scrying orb, maxed time stop, maxed smoke, and a 1-point something. but a gemsuit, scrying orb, and timestop+smoke makes you literally untouchable because nobody can see you in an advancing wave of smoke, you can see them, and you can timestop meme anyone who enters the smoke.

**Comment by PKPenguin321** [comment]
Low winrate is because only the shittiest wizards actually care about greentext lmao

**Comment by Supermichael777** [comment]
low winrate is because they get shuttle meme the worst objective. yes i am bitter

**Pull request closed without merging**
