### PR TITLE
Fixes delays in emp_act

### LINKED ISSUE #13968: EMPs can lock up processing
Simply put, because of sleeps:

https://github.com/tgstation/-tg-station/blob/da0ba3659f3f83bfbc6c0e28c378a0728caa2cc6/code/game/machinery/doors/door.dm#L140

this calls open() on doors, which have a sleep: https://github.com/tgstation/-tg-station/blob/da0ba3659f3f83bfbc6c0e28c378a0728caa2cc6/code/game/machinery/doors/door.dm#L185

it's only a total sleep of 1 second, but that's still one second of delayed processing---this could be particularly problematic during mass EMP events like the singularity, telsa release, etc.

I believe adding a spawn(0) then having open() would solve this problem; generally lots of spawning isn't a good thing (as evidence by the "fix" to lopsided explosions), but in this case, I believe it's applicable.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #13968

### CODE REVIEW

**Comment by coiax** [comment]
I would @MrStonedOne this change.

**Comment by xxalpha** [comment]
I don't think this does anything.

**Comment by MrStonedOne** [comment]
@cyberboss have you checked every usage of emp_act to make sure nothing is expecting emp_act() to block?

**Comment by optimumtact** [comment]
@Cyberboss pls respond soonest

**Comment by Cyberboss** [comment]
Rah rah vacation, I'll get to it tonight

**Comment by Cyberboss** [comment]
Checked, it's fine

**Comment by optimumtact** [comment]
I dunno, I feel like this is a bandaid, most subsystems shouldn't be setup like this imo, instead spawns or addtimer should simply be applied where needed

**Comment by optimumtact** [comment]
that wasn't a command it was an opening conversation

**Comment by Cyberboss** [comment]
its only 1 or two procs that sleep ill just fix those

**Pull request closed without merging**
