### PR TITLE
Implants can now be removed fairly quickly

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
tweak: To facilitate better game flow the steps for implant removal have been decreased.
tweak: The steps are now incise, remove, close.
/:cl:

Now people might try to actually convert sec officers.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Delete "optional name here" in your cl

**Comment by Supermichael777** [comment]
wups

**Comment by kevinz000** [comment]
I suddenly like Kilkun and Ma44 better.

**Comment by optimumtact** [comment]
Don't you think that realistically this isn't because of a few extra steps in the surgery and the fact that surgery is hard to do outside of the theatre?

**Comment by XDTM** [comment]
It's already pretty fast, my suggestion is to put mindshield implants in the head instead of chest so it won't require declothing and reclothing.

**Comment by Durkel** [comment]
For some reason I have the feeling that removing a implant that's (supposed to be) in your fucking skull incredibly dangerous, and skipping steps would fuck you up hardcore,

**Comment by AdamElTablawy** [comment]
i don't really see a purpose for this 

if you're willing to do surgery a few steps isn't what's blocking people it's more the difficulty of sedating w/o killing a sec officer, removing his implant, and converting him presumably while the AI whines about CULT THEATRE CULT THEATRE

not to mention kill-clone-convert is easier still

i think it's just general incompetence and lack of patience that leads to kill-no convert 

the impact that this has is honestly negligible for most implants

**Comment by optimumtact** [comment]
I don't think this achieves what it sets out to do.

**Pull request closed without merging**
