### PR TITLE
Remapping of Nuke Op's Ship

### PR DESCRIPTION
**Pull request by Steelpoint**
A slight remapping of the interior of the Nuke Op's ship.

screenshot 2016-02-22 17 58 03

Changes to note.
- Expanded the ship's medbay
- Moved cyborg rechargers to tool storage.
- Added additional C4 charges to prep room.
- Slightly smoothed out exterior of ship.
- Sectioned off seating area.
- Oxy Tank dispenser in medbay.

### CODE REVIEW

**Comment by Anonmare** [comment]
Would be nice with an actual airlock. The Black and red space suit get's sucked out constantly

**Comment by Steelpoint** [comment]
Fair point.

**Comment by KazeEspada** [comment]
Tank dispensor please.

**Comment by xxalpha** [comment]
Don't put unanchored objects in the exit room, it's just asking for things to get ejected.

**Comment by Steelpoint** [comment]
Well if I add a proper air lock system that's not much a problem.

**Comment by Incoming5643** [comment]
You might want to add a turret or two to the backside to keep people from deconning in.

There's probably a issue report for that somewhere

**Comment by Steelpoint** [comment]
Some minor changes, added additional exterior turrets in exposed flanks as well as moving the space suit out of the airlock and adding a tank dispenser. 

I'm going to have to reflect all these changes onto all current in rotation maps or else bad things will happen, that plus the merge conflicts means I'll have to effect a bunch of changes.

screenshot 2016-02-19 01 31 10

**Comment by KazeEspada** [comment]
Add an airlock and make it semeticral

**Comment by Steelpoint** [comment]
That would require more intense remapping of both the derelict (to a extent) and the Ops base to extend and move everything.

Doable but just worth noting, and I want to at least get all non-box maps up to snuff.

**Comment by Shapsy** [comment]
Is it possible to just make the shuttle impossible to decon again? People spacing the nuke is dumb and cheesy and trying to enforce whether or not they had a valid reason to know where the nuke ops shuttle was in the first place is a royal pain in the ass

:+1: to more C4 also

**Comment by Niknakflak** [comment]
The windows at the bottom next to the nuke look weird to me personally but I also don't know what else you could do there

**Comment by PKPenguin321** [comment]
while you're at this, make the ship indestructible, thanks

**Comment by bgobandit** [comment]
The medbay is kind of proportionally enormous.

**Comment by Lumipharon** [comment]
Make it indestructable please, for the love of god.

**Comment by optimumtact** [comment]
For fucks sake where did the turrets go?

**Comment by Anonmare** [comment]
Yeah the medbay is too big for it's function. Maybe a small brig with some flavourful items?

**Comment by Iamgoofball** [comment]
add another turret next to the blast door entrance

there's way too little in the way of turrets on this

**Comment by Steelpoint** [comment]
The turrets are the grey wierd boxes, they don't have any sprites in the map maker viewer, you can see in the top left and right of the cockpit as a example.

**Comment by Lumipharon** [comment]
Steel, just make it invulnerable again. Everyone is sick of the nuke getting spaced every 2nd ops round.
Someone claimed it was a simple var for walls to make them indestructable, but could be wrong.

**Comment by Bawhoppen** [comment]
steelpoint pls someday I'll get to it

**Comment by Steelpoint** [comment]
Look if I can find the value (I'll check the Centcom walls) I'll do it.

**Comment by Steelpoint** [comment]
Making the walls indestructible would be far too much effort code wise, it'll be easier for me to just place more turrets around the exterior of the ship.

**Comment by PKPenguin321** [comment]
literally every wall then pls

**Comment by Steelpoint** [comment]
I was planning to double their health, increase their scanning range to 14 tiles and increase their rate of fire to around one round a tick.

**Comment by PKPenguin321** [comment]
and put them on at least a majority of the walls, right?
good thanks

**Comment by Lumipharon** [comment]
We have indestructable walls on centcomm, and certain z-levels (like around the wish granter on that away mission.

How do they have that set?

**Comment by MMMiracles** [comment]
Making the indestructible would literally be as easy as making a subtype of the generic indestructible wall with the same icon as the what the nuke shuttle wall's use. Do the same for the corner pieces and you're done.

Literally 5 minutes and copypasta is all you'd need to do.

**Comment by KorPhaeron** [comment]
>Making the walls indestructible would be far too much effort code wise

Just use /turf/indestructible

**Comment by Steelpoint** [comment]
I'll be fixing the merge conflicts and expanding this change to all maps, since if I don't things will break horribly.

Well, tomorrow.

**Comment by Steelpoint** [comment]
Made some changes, still a work in progress.

Syndi Ship turrets have been buffed, they now have 160 health, they have a scan (attack) range of 14 tiles and they have a buffed rate of fire of one round per in game tick. In addition the all angles of the exterior of the ship now have a turret covering it.

There are now two indoor turrets, both of them are flanking the Nuke and have a opacity of 1 (meaning you can walk through them). They are very deadly and will not hit the glass panes.

I've also added a new southern entry point that docks the Syndi shuttle with a maintenance airlock on Boxstation. Though this is WIP.

After I finish tidying up the ship I'll be adding this change to all map's and their Syndi Ships (Not the docking port, that's Box only).

**Comment by Steelpoint** [comment]
Image of new docking point AND the ship.

screenshot 2016-02-21 22 27 10

**Comment by Bawhoppen** [comment]
steelpoint just close this PR and never look back and we'll all forgive you for your atrocities committed today

**Comment by Steelpoint** [comment]
I like the deconstruction of the ship, but with these new turrets it'll be extremely difficult for anyone to even get near the Syndi ship.

**Comment by Steelpoint** [comment]
Well what exactly do you dislike about the PR?

**Comment by Jalleo** [comment]
How much ammo does the turrets have? And is there a way to refill it?

**Comment by Steelpoint** [comment]
They've always had infinite ammo.

Beforehand the turrets were easy to bypass as you could just cut your way into the south west side of the ship, now you have to confront at least one turret to get into the ship, let alone the two turrets on the inside.

**Comment by optimumtact** [comment]
:+1: thanks for adding a shot with the turrets on

If anything I'd suggest a few more, nobody should ever be getting onto the syndicate shuttle

**Comment by Lumipharon** [comment]
Well, time to just push up computer consoles and steal the nuke exactly as I can now.
Or just float through space in a CARDBOARD BOX and not get shot.

Seriously, fuck deconstructable nuke shuttles, it CAN be abused, and it WILL be abused, we've seen this time and time again.

Crew chasing ops into space with a pinpointer and saving the day is great. Turrets that can murder you without you even seeing them stops this.

Crew deconing the shuttle and spacing the nuke is shit. Turrets that can murder you without even seeing them doesn't neccesarily stop this.

Indestructable walls like it was designed to has stops the cheese and still lets the crew fight ops in space.

**Comment by KorPhaeron** [comment]
Listen to Lumi

**Comment by Bawhoppen** [comment]
doesn't matter? it's pretty blatantly against the rules anyways

also that brings up a good point, why haven't we nerfed computer frames (and other shit) yet

**Comment by Steelpoint** [comment]
Turrets are essentially two shot crits and they now have a attack range beyond their visual range, well they should.

**Comment by Bawhoppen** [comment]
thats also a huge buff to steel rain turrets

**Comment by Steelpoint** [comment]
I thought of that, the Nuke Op ship turrets are a unique turret, the Droppod turrets remain unaffected.

**Comment by Lumipharon** [comment]
Steel why are you trying to push an idea that is a bandaid fix instead of what is (according to kor) a simple, and reliable one?

**Comment by Steelpoint** [comment]
Because at the exact moment you posted that I was just typing that I went back on my decision and made the Nuke Op ship wall indestructible, while also reducing the turrets back to their original form (4 turrets on the north east side).

I'll post a final image of the shuttle and port it all over to the other maps.

**Comment by Steelpoint** [comment]
Merge conflicts should be fixed, the PR is merge ready.

Image will be up in a moment.

**Comment by Steelpoint** [comment]
screenshot 2016-02-22 17 58 03

**Comment by Bawhoppen** [comment]
govom I can work with that but remove the new docking port

**Comment by Steelpoint** [comment]
What's wrong with it?

**Comment by Bawhoppen** [comment]
a few things, you should just save it for another PR instead

**Comment by Steelpoint** [comment]
I should mention the above image is indicative of where the new destination is, its wedge between the AI Satellite and the south east solar arrays. Its not directly connected to the station as doing so would require a lot of reworking to get it right.

**Comment by Iamgoofball** [comment]
what happened to all the back turrets wtf

**Comment by Lumipharon** [comment]
Now that the walls can't be deconned turrets only matter near the airlock/front window.
I guess you can still chese it with telearmour/handtele, but that's not an issue with the shuttle.

**Comment by Bawhoppen** [comment]
lumi you know its still against the rules anyways

**Comment by Lumipharon** [comment]
As I said, cheesing it, and not an issue with the shuttle itself

**Comment by Steelpoint** [comment]
The new python mapmerge tool is fucking me over so this is going to have to wait until I can figure out what's wrong.

**Comment by Steelpoint** [comment]
Merge conflicts should be fixed, the sooner this is merged now the better as its getting annoying to fix merge conflicts.

**Comment by Steelpoint** [comment]
Ok I removed the new destination, this is merge ready.

@WJohn and co.

**Comment by Steelpoint** [comment]
Danke

**Pull request merged**
