### PR TITLE
Gives shadow walk a new, spookier, and shorter sound effect that no longer ignores walls

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

This gives shadow walk a snazzy new sound effect for entering/exiting jaunt.

https://github.com/tgstation/tgstation/assets/28870487/c25f720f-5bad-4063-8d6e-140fd41bd740

This also has the sounds it plays no longer passes through walls.
## Why It's Good For The Game

The ethereal_entrance/exit sound effects are drawn out, and pretty grating. They work for the other jaunts they're used for because a jaunt typically lasts longer than the sound itself. Nightmares are frequently dancing in and out of jaunt, and the sound effects for entering/exiting tend to overlap. It gets loud and annoying really fast.

This sound effect is quicker, spookier, and more distinct.

As for making the sound not ignore walls, I think it's pretty dumb how easy it is to detect the spooky scary shadow antag just by sitting in your department. It takes a lot of the initial fear and paranoia they have the potential for is wasted when Joe Geneticist can hear them messing around in their territory without having to leave their chair.
## Changelog
:cl: Rhials
sound: Nightmare has a new sound effect for entering/exiting shadow jaunt. It also no longer can be heard through walls.
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
we really need to set a standard for what should be heard through walls and what shouldn't rather than just what does and what doesn't.

**Comment by Rhials** [comment]
> we really need to set a standard for what should be heard through walls and what shouldn't rather than just what does and what doesn't, alot of seemingly quiet things can be heard through walls.

Personally, I think it's dumb that ignore_walls is TRUE by default. I'd change it myself but that would probably have a much bigger impact than expected and don't want to audit all 3000 uses of playsound().

**Comment by Eronymun** [comment]
Love this, sounds great, maybe it can be slightly more waily? This is exactly the kind of things I've been hoping for nightmare to get. Nightmare needs more "horror" esque changes. The sprite is pretty dated, and the arm blade doesn't match the sprite that well either. Emissive red eyes in the dark and some interesting effects might get that "this is a NIGHTMARE" spooky feeling I've been hoping for.

**Comment by DaydreamIQ** [comment]
Bit by bit nightmare will become an actual threatening antag some day

**Pull request merged**
