### PR TITLE
Adds Chemical Autoinjector Backpack

### PR DESCRIPTION
**Pull request by AnturK**
And some snowflake chem for the subtype.
Admin item until feedback because i can't balance, wanted to put in traitor kit.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
finally, a way to inject constant streams of drugs and alcohol into your body at all times

**Comment by Bawhoppen** [comment]
@PKPenguin321 you already have IV drips
also when typing your name pap's showed up, conspiracy? :mahjong:

**Comment by Fox-McCloud** [comment]
reminds me a little of Goon's injector belts and vapor masks---which inject reagents when a certain health threshhold is reached (that you can set) or when you die.

**Comment by tkdrg** [comment]
@AnturK  conflcits

**Pull request merged**
