### PR TITLE
Datum Antags Part 1: Traitors

### PR DESCRIPTION
**Pull request by Iamgoofball**
We can now modularize antags to the maximum potential.

### CODE REVIEW

**Comment by kevinz000** [comment]
You're a codebase antag.

**Comment by Iamgoofball** [comment]
For you.

**Comment by MrStonedOne** [comment]
it doesn't work like that.

**Comment by evsey9** [comment]
is this good or bad
is this a start to datum antags that coiax never finished
or is this a fucking meme pr
also FIX NULL CRATES REEEEEE

**Comment by Jordie0608** [comment]
@evsey9 this fixes null crates

**Comment by Ninja137** [comment]
>All checks have failed
RIP

**Comment by FlavoredCactus** [comment]
meme pr

**Pull request closed without merging**
