### PR TITLE
Makes wawastation AI sat hospitable to human AI's

### LINKED ISSUE #85013: wawastation's ai core is somewhat inhospitable to human ais
## Round ID: [232190](https://scrubby.melonmesa.com/round/232190)

wawa's ai sat/core design puts the telecomms machines and the ai core itself in a single room, which is cool design but has the unfortunate effect of freezing the big brother to death when the human ai station trait rolls

### PR DESCRIPTION
**Pull request by EEASAS**
## About The Pull Request
Fixes #85013
makes it not very cold and full of nitrogen
so human ais can still live in there without a space suit and oxygen tank always at the ready
## Why It's Good For The Game
bUG FIXES are Great for the game
i need gbp
## Changelog
:cl:
fix: Human AI can now not die in Wawastation AI Sat due to nitrogen poisoning
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
I want to block this because I think it's a cool, unique design element about the map and I don't want to be forced to change it due to a single station trait

@JohnFulpWillard Can you think of an alternative to this

**Comment by EEASAS** [comment]
> I want to block this because I think it's a cool, unique design element about the map and I don't want to be forced to change it due to a single station trait

so what do i do then

**Comment by MrMelbert** [comment]
You don't have to do anything we (the maintainers) just have to discuss what we actually want out of this

**Comment by SmArtKar** [comment]
Human AI trait probably should be removed, so far I haven't heard much positive feedback about it, only frustration with only a couple of funny "gimmicks"/jokes

**Comment by Likteer** [comment]
> Human AI trait probably should be removed, so far I haven't heard much positive feedback about it, only frustration with only a couple of funny "gimmicks"/jokes

Yeah...
MandatoryFun

**Pull request closed without merging**
