### PR TITLE
Removes the gag ball.

### PR DESCRIPTION
**Pull request by Aranclanos**
honk

### CODE REVIEW

**Review by Cw3040 — COMMENTED** [review]
this is stupid

**Comment by Chocobro** [comment]
thanks for commenting on a 4 year old PR dickhead don't make this appear in my emails ever again or else

**Comment by IsdatAfamas** [comment]
Memes

**Comment by Intigracy** [comment]
Thanks for the notification

**Comment by Iamgoofball** [comment]
fellow boomer coders, who up tonight?

**Comment by Fikou** [comment]
pog

**Comment by Anton-Kr** [comment]
Bring back NTStation

**Pull request merged**
