### PR TITLE
How nanotrasen discovered the recipe to non-yellow lightbulbs: Wall and floor lights resprite

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

So there I was looking through random dmi files for something specific, when I had the unfortunate circumstance of coming across the lights files. After a quick glance, I realized I could probably do something a tad bit better, and thus two hours of my life are never coming back.

image
## Why It's Good For The Game

<details>
<summary>See for yourself how much less crust the lights have now:</summary>
<br>

image

image

image

image

</details>

## Changelog
:cl:
image: Wall and floor lights have been resprited to be a lot less dated looking, and a lot less yellow
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
Biggest removal of soul to date. I love them piss yellow lights

**Comment by OrionTheFox** [comment]
My one complaint is that it looks like I can trip over the floorlights now, instead of them being embedded into the floor
I don't wanna trip :c

**Comment by mc-oofert** [comment]
not retro sci-fi

**Comment by Sealed101** [comment]
hahaha what the fuck icon diffbot

68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f37373232392f31373636373436343337333536393535303536302e676966

**Comment by newfren** [comment]
got any ingame screenshots? especially around like medbay or somewhere with the white tiles, worried about them blending in

**Comment by SimplySmiley123** [comment]
What I'm worried about is visibility issue in areas like medbay, science, kitchen, shuttles.
Yellow lights do stand out from white colours.
White lights don't stand out and blend in, especially when frames also blend in with the walls.

**Comment by nianjiilical** [comment]
> My one complaint is that it looks like I can trip over the floorlights now, instead of them being embedded into the floor I don't wanna trip :c
> 
> Also, does this touch the object sprites of the tubes/bulbs, or just the frames? Do the constructed states have new sprites?

seconding this, the sprites are good but the shading on the floorlamp makes it look like it's a square extruding from the floor as opposed to being inset/level with the floor which is a bit weird

just a minor nitpick though i think this is an improvement overall

**Comment by atlasle** [comment]
why are their metal bits a different color than every other metal thing in the game, can't we have any consistency

**Comment by GuillaumePrata** [comment]
Lights that blend in on places like medbay should be a benefit from this PR, not a con.

Lights are not important enough to get the players' attention, the other more important wall mounts with meaningful interactions should be the ones that the player finds easily.

If there are too many "high visibility" items in an area, it just becomes harder to find the important ones.

**Comment by mc-oofert** [comment]
> Lights are not important enough to get the players' attention, the other more important wall mounts with meaningful interactions should be the ones that the player finds easily.

Theyre important!
Nightmares and other light sensitive creatures
Traitors trying to break all lights to set up an ambush or fill with plasma
Assistants breaking them for shits and giggles
Janitors repairing them

**Comment by Paxilmaniac** [comment]
> What I'm worried about is visibility issue in areas like medbay, science, kitchen, shuttles. Yellow lights do stand out from white colours. White lights don't stand out and blend in, especially when frames also blend in with the walls.

This is a good point and probably the only benefit that piss yellow lights had. When I get some time later today I'll load it up with all the different maps and see how it ends up looking. If they blend in too much I can fix that.

**Comment by Acer202** [comment]
I've seen many other codebases go for this sterile while look for lights and it makes them blend into the surroundings. TG's warm-white bulbs are very nice for distinguishing from the floor and tables and whatnot.

**Comment by GuillaumePrata** [comment]
> Theyre important!

All the examples you gave are of people actively looking for the light tubes.
This PR doesn't decrease their size, changes them around the map or anything of the kind. People that want to use light tubes will easily find them.

Light tubes are not something that people interact with for most of their rounds, they should be the last thing players pay attention into a room *unless* they are actively looking for them for an interaction.

**Comment by mc-oofert** [comment]
> > Theyre important!
> Light tubes are not something that people interact with for most of their rounds, they should be the last thing players pay attention into a room _unless_ they are actively looking for them for an interaction.

janitors fix light

>This PR doesn't decrease their size, changes them around the map or anything of the kind. People that want to use light tubes will easily find them.

you are completely oblivious to the term "visibility issue"

**Comment by GuillaumePrata** [comment]
> janitors fix light

I know... My point was literally that people don't interact with the lights on most shifts *unless* they are actively looking for them.
AKA janitor fixing broken lights.

> you are completely oblivious to the term "visibility issue"

That is just plain wrong.
My point is that lights are not important enough to warrant such a worry about becoming a less catchy sprite.
We have multiple items above light tubes on the "visibility importance" totem pole.

**Comment by mc-oofert** [comment]
> That is just plain wrong. My point is that lights are not important enough blah blah blah

literally oblivious

**Comment by Paxilmaniac** [comment]
> My one complaint is that it looks like I can trip over the floorlights now, instead of them being embedded into the floor I don't wanna trip :c
> 
> Also, does this touch the object sprites of the tubes/bulbs, or just the frames? Do the constructed states have new sprites?

The constructed states have matching sprites, the light bulb items have matching sprites, everything

**Comment by Paxilmaniac** [comment]
@newfren @mc-oofert @Acer202 

Doing some testing, I'd say these don't blend in with the white ground enough to worry about. Thoughts?

image

**Comment by GuillaumePrata** [comment]
> literally oblivious

Just repeating what you said before instead of trying to have a conversation with someone that has the opposite view on the PR is pointless... why even bother commenting again? Need to have a last word or something?

I guess we will agree to disagree with the importance of light tubes when compared with other wall mounts.

**Review by Wallemations — CHANGES_REQUESTED** [review]
If you're changing all them to be white then you should swap the object sprites to match (the tubes and bulbs you can print from lathes)

**Comment by Paxilmaniac** [comment]
> If you're changing all them to be white then you should swap the object sprites to match (the tubes and bulbs you can print from lathes)

The object sprites were updated and they were updated to look like how the lights do when turned off. Because you know, the lights are off when not in a socket.

**Comment by newfren** [comment]
maybe an issue on a busier tile with the smaller globes, but frankly the lights we currently have already blend into the yellow and black hazard stripes severely and this is hardly worse than that

**Comment by DrDiasyl** [comment]
For some reason, the in-game screenshot looks like the lights don't have emissives.

**Comment by Paxilmaniac** [comment]
> For some reason, the in-game screenshot looks like the lights don't have emissives.

I don't think lights actually have emissives, I'm seeing nothing on it in the code, its just a normal overlay ont hes prite

**Review by Wallemations — APPROVED** [review]

**Comment by carshalash** [comment]
image
This, really doesn't look like a light.

**Comment by MrDoomBringer** [comment]
wjohnston is spinning in his grave. retro futurism aesthetic in shambles

**Pull request merged**
