### PR TITLE
Codeowners, the fourth change today

### PR DESCRIPTION
**Pull request by san7890**
Blame potato. Removes whitespacing stuff.

Why is this good for the game? it is not.

### CODE REVIEW

**Comment by WarlockD** [comment]
Screw NFT, just watching all these VM's spin up for this is worth gold.

**Comment by tralezab** [comment]
this pr removes two spaces and nothing else
unknown-4

**Comment by LemonInTheDark** [comment]
The weak should fear the strong

**Comment by WarlockD** [comment]
God all those bots must love us.

**Comment by san7890** [comment]
> God all those bots must love us.

Less so the bots, and more so the people who have to deal with the ports of these on the downstream.

**Pull request merged**
