### PR TITLE
Science can now print off processors as well

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
@GrayRachnid 

:cl: Cobby (Stolen from GrayRachnid)
tweak: The processor has now been generalized techweb-wise into the "food/slime processor".
add: The processor can now be made by Science.
/:cl:

Fixes the issue brought up in #37257 in that science SHOULD have access to the processor already but actually adding it to a node was overlooked. This PR combines the design since they are made using the same board (no need for 2 designs of the same thing), and informs the player of such.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
I tried to merge these back when I made them upgradable but people got pissy. Can we merge them yet?

**Comment by newfren** [comment]
You used to be able to grind slimes in the kitchen grinder when did that change.

**Comment by ExcessiveUseOfCobblestone** [comment]
I have no idea lol

**Comment by improvedname** [comment]
BRING BACK JAR OF SLIME JELLY BY GRINDING WHOLE SLIMES IN FOOD PROCESSORS

**Comment by AnturK** [comment]
Conflict

**Comment by ExcessiveUseOfCobblestone** [comment]
@AnturK

**Pull request merged**
