### PR TITLE
Highly increasing Timelock on all Security Department Jobs (Besides the lawyer)

### PR DESCRIPTION
**Pull request by mrhugo13**
## About The Pull Request

Changes the `exp_requirements` for the following jobs in the list:

Security Officer from `300` to `480` (5h to 8h)
Detective from `300` to `600` (5h to 10h)
Warden from `300` to `720` (5h to 12h)
And the HoS from `300` to `960` (5h to 16h)

## Why It's Good For The Game

As-is the current Time-lock (which is set to 5 hours for all of the security Department jobs) is, as i believe, not enough time of playing crew to properly understand how big Security can have an effect on the round and how easily Security can change any person on the stations plans for anything, here’s a few examples of this:

You wanna do surgery as a roboticist on a Security Officer to turn him into a robo-cop with the Sec-Officers permission?: Security can come in and arrest you, sometimes in a manner that can only be described as “Shitcurity”.

You feel like carving up some human bodies for food as chef?: Security can comes in and arrests you despite the fact that the bodies were un-recoverable beyond all means.

Do you want to just do some good ‘ol toxins as a scientist?: You get shot on the spot for holding a bomb while in toxins.

All of these are examples where Security can completely change someones plans, sometimes this is completely justified, other times it’s about as justified as the existence of mosquitos, hence why this PR is ment to fix this issue by increasing the Security Officers to 8 hours, the Detectives timelock to 10 hours, the Warden gets theirs increased to 12 hours, & the HoS gets theirs increased to 16 hours hours so that Security Officers would take (if a round was, on average, around 2 hours long) around 4 rounds to properly understand the impact of the job and become able to play it, while Warden has 12 hours which would give 4 hours in-between the Warden and the HoS so atleast 2 rounds could be fit in-between so the Warden can atleast get some experience with Sec-Wrangling, and the HoS would require 16 hours so they can fully understand their job of both wrangling the Greytiders and the Security who has no clue on what to do with their job at the same time.

## Changelog
:cl:Mrhugo13
tweak: Security Officer now require 8 hours of playing any department to play.
tweak: Detective now require 10 hours of playing any department to play.
tweak: Warden now require 12 hours of playing any department to play.
tweak: Head of Security now require 16 hours of playing any department to play.
/:cl:

### CODE REVIEW

**Comment by pireamaineach** [comment]
Increase them more please.

**Comment by carlarctg** [comment]
good change :thumbsup: baldsec makes me want to cry

**Comment by pireamaineach** [comment]
Good change more please. Also put Detective on a higher time lock. Either on par with Warden or on par with H.O.S.

**Comment by mrhugo13** [comment]
> 
> 
> Good change more please. Also put Detective on a higher time lock. Either on par with Warden or on par with H.O.S.

How so? In my personal opinion i see detective on-par with the average Security-Officer, i'm intrested in hearing your arguments for a higher time-lock on the Detective.

**Comment by carlarctg** [comment]
detective culture is "shitsec with a lethal" 

i've been critted by a moron 357 detective jumping to conclusions before,  they should be upped a bit more than officer imo

**Comment by pireamaineach** [comment]
Detective job-bans also ought to be handed out far more liberally but that's an administration issue.

**Comment by mrhugo13** [comment]
How about putting it to `600` instead of `480`? that would be 10 hours instead of 8.

**Comment by Difrit** [comment]
I'm not against this. Newer Security players need a bit more time played to understand how Security should act, so they can't pretend to be ignorant or innocent if they do something bad.

**Comment by pireamaineach** [comment]
I was thinking more along the lines of 24 hours for H.O.S., 16 for warden and detective, and 10 for security officers.

**Comment by mrhugo13** [comment]
I'll keep that idea on a branch of this version, if enough people think thats a good idea (With some pretty good and extensive reasoning) i'll get this version of the PR to the increased numbers that @pireamaineach suggested.

**Comment by wesoda25** [comment]
new security players are a national treasure and one day you’ll be able to appreciate them

**Comment by ExcessiveUseOfCobblestone** [comment]
playtime reqs aren't configbound?

**Comment by Dawson1917** [comment]
Increase detective a lot more please. It's sec officer for edgelords and gives you a free lethal and no disabler. Maybe make it require a few (5 or 6) hours of security officer. Anything to stem det shitters who've never played security and think critting anyone who has a red W next to their name is how you do your job.

**Comment by mrhugo13** [comment]
With people saying that Det required time should be increased, their required time has been increased by 2 hours in this PR, making them require a total 10 hours of playtime for any of the jobs on the station.



> 
> 
> playtime reqs aren't configbound?

Also yeah suprisingly it isn't config-bound and is instead bound to some exp_requirement var in their own files, which i personally think shouldn't be there and should be instead in some sort of config file.

**Comment by pireamaineach** [comment]
Probably ought to be based on time as sec.

**Comment by mrhugo13** [comment]
> 
> 
> Probably ought to be based on time as sec.

I personally think any crew does fine, as Security interactions goes for all crew, and playing SEC can help this but it isn't neccecary, however i am willing to change my mind on the matter given enough good and sensible reasons are given.

**Comment by CPTANT** [comment]
> 
> 
> new security players are a national treasure and one day you’ll be able to appreciate them

unironically they often lead to interesting/funny gameplay situations.

**Comment by wesoda25** [comment]
> > new security players are a national treasure and one day you’ll be able to appreciate them
> 
> unironically they often lead to interesting/funny gameplay situations.

Thats why I downvoted the PR : )

**Comment by nemvar** [comment]
Why is this not in config? wtf?

**Comment by Ratvar** [comment]
Problem with detective is having revolver and super stunbaton. Role itself enables validhunting lethal-happy shitlers, no matter the timegate. It won't be fixed until it's reworked into something that's not officer with legal lethals, no matter how "cool" idea sounds on paper.
Good PR, tho, newbies need more time to learn wtf's going on.

**Comment by optimumtact** [comment]
you know what you should do instead? make this a config file

**Comment by mrhugo13** [comment]
> 
> 
> you know what you should do instead? make this a config file

I'd maybe look into it once this PR get's Closed/Merged, eitherway works for me to fix this sort of stuff.

**Comment by Arathianen** [comment]
I 100% support the changes but this should clearly be a config done/changed by headmins.

This is rules territory. Not coder territory. Admin/coder separation goes both ways and should be respected.

**Comment by wesoda25** [comment]
> > you know what you should do instead? make this a config file
> 
> I'd maybe look into it once this PR get's Closed/Merged, eitherway works for me to fix this sort of stuff.

Translation: Merge this so I can forget about it

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
Get 2 headmins on board then send verifiable evidence they did such (or have them post here, idc).

**Comment by mrhugo13** [comment]
> 
> 
> Get 2 headmins on board then send verifiable evidence they did such (or have them post here, idc).

Here's the response(s) from Wubli:
https://imgur.com/a/MFYpUyN

Here's the response from Hulkmania:
https://imgur.com/a/6uCD3I4

And Here's Nerveres response:
https://imgur.com/a/MyMEODg

**Comment by ExcessiveUseOfCobblestone** [comment]
ugh they can't just say "yes those numbers look ok" or "no"

reeee

**Comment by optimumtact** [comment]
I already pinged them on this and only hulk replied saying it was good.

**Comment by ExcessiveUseOfCobblestone** [comment]
just config bind it I guess, I don't really feel comfortable making these more difficult without headmin ability to partial/full revert as they see fit.

**Pull request closed without merging**
