### PR TITLE
[NO GBP] Moussaka/pita bread fixes

### PR DESCRIPTION
**Pull request by MidoriWroth**
## About The Pull Request

When doing my new food release, I thought moussaka used both potatoes and eggplants when it only uses eggplants, which can be substituted for potatoes (which is lame and not authentic!)
Also, pita bread no longer burns on the griddle

## Why It's Good For The Game

Food becomes a bit more consistent!

## Changelog
:cl:
fix: Moussaka now only uses eggplants instead of eggplants and potatoes
fix: Pita bread no longer burns on the griddle/oven
/:cl:

### CODE REVIEW

**Comment by Ticklezcat** [comment]
IRL Moussaka can have potatoes, eggplants, or both at the same time, Julia Child went the "both" route for hers. Both are south American crops and about equally authentic in their adopted Balkan home.

**Comment by MidoriWroth** [comment]
Huh, everywhere I read just said that it was a possible substitute

**Comment by Ticklezcat** [comment]
Doing a bit of checking the eggplant seems to be standard for Greek recipes, Bulgarian ones have potato standard, even found a Croatian one that didn't have either.

**Comment by MidoriWroth** [comment]
yeah, this update was meant for more mediterranean themed stuff so i guess just eggplants will be fine

**Pull request merged**
