### PR TITLE
Turns /datum.isprocessing into a datum flag

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
:cl: Naksu
code: moved /datum.isprocessing into datum flags
/:cl:

just a light touch on the MC here

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
image
wasted a get

**Comment by Cyberboss** [comment]
The var seems pretty useless overall methinks considering we have many processing SS's now

**Comment by MrStonedOne** [comment]
Its either that or we return to `|=`, having this var removed 7 seconds from initialization.

**Comment by vuonojenmustaturska** [comment]
we still have room for 13 more flags in datum_flags after this PR, i wouldn't worry about it

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
