### PR TITLE
The Galactic Materials Market no longer runtimes on opening or ordering.

### PR DESCRIPTION
**Pull request by lizardqueenlexi**
## About The Pull Request

The Galactic Materials Market, currently, runtimes while attempting to open the UI. This is due to attempting to load various fields from un-initialized material datums. Through liberal application of `initial()`, these runtimes have been removed, and it is now possible to use the market at all (though it has some other issues that I'll make bug reports for...).

Also gives priority to `greyscale_colors` over `color` when choosing colors for the UI, to make the correct colors appear.
## Why It's Good For The Game

The Materials Market is rather important as the only source of minerals on rounds without any miners. So... it's good if it actually loads.
## Changelog
:cl:
fix: The Galactic Materials Market now offers things for sale as it should.
/:cl:

### CODE REVIEW

**Comment by lizardqueenlexi** [comment]
I've been informed that this feature is apparently already working fine? Even though it's been runtiming on my master branch as well as downstream. Very strange...

**Comment by Profakos** [comment]
Maybe the dictionary's keys are *sometimes* typepaths, and *sometimes* actual material datums?

**Comment by Profakos** [comment]
Bug successfully reproduced on latest, its real.

**Review by Ghommie — CHANGES_REQUESTED** [review]
There's another loop where the contents of `materials_prices` are mistakingly treated as datums rather than paths: https://github.com/tgstation/tgstation/blob/467f4cd1b55498941ff24e83eb1f09bb8e23c813/code/modules/cargo/packs/stock_market_items.dm#L17

**Comment by SyncIt21** [comment]
@ArcaneMusic #78500 Approve?

**Review by ArcaneMusic — APPROVED** [review]

**Comment by ArcaneMusic** [comment]
> There's another loop where the contents of `materials_prices` are mistakingly treated as datums rather than paths:
> 
> https://github.com/tgstation/tgstation/blob/467f4cd1b55498941ff24e83eb1f09bb8e23c813/code/modules/cargo/packs/stock_market_items.dm#L17

I'll try and hit this when I hit the other open GMM issues, read my notifications too quickly

**Pull request merged**
