### PR TITLE
You can now control the rate at which bees die

### PR DESCRIPTION
**Pull request by Lett1**
Added custom initializer to bee/short to allow setting a lifetime for the bee.

### CODE REVIEW

**Comment by WJohn** [comment]
you monster i don't want the bees to die :(

**Comment by ATH1909** [comment]
https://i.kym-cdn.com/entries/icons/original/000/027/172/Screen_Shot_2018-09-18_at_10.17.37_AM.png

**Comment by FantasticFwoosh** [comment]
Just use the flyswatter to one shot them. Now I am bee-come death, the destroyer of worlds.

**Comment by Tlaltecuhtli** [comment]
those arent real bees

**Comment by ExcessiveUseOfCobblestone** [comment]
well ok lol

**Pull request merged**
