### PR TITLE
Makes gibtonite ore look like diamond to a scanner until revealed

### PR DESCRIPTION
**Pull request by ghost**
Exactly what the title implies.

Until revealed by actually hitting it, Gibtonite will look identical to diamond. Now when you mine diamond, it might be a trap.

Inspired by that being how it used to be and me thinking that was pretty cool. Also, because I don't feel like lavaland is quite dangerous enough. Also, I hate fun.

:cl: Adam
tweak: Gibtonite ore looks like diamond on a scanner until revealed by hitting it.
/:cl:

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Repukan** [comment]
Seems like it would make checking for diamonds rather more annoying than dangerous.

**Comment by jughu** [comment]
this was already done in the old mining days if anything you just assblast miners more using plasma cutters

**Comment by AdamElTablawy** [comment]
correct

and also correct jughu, which is what i said in the pr

**Comment by Repukan** [comment]
On the one hand this opens the slope you had on yog what with the grudge code because you hate miners and all.

In the other hand it shits on cutter miners, which would make them less meta first pick.

**Comment by AdamElTablawy** [comment]
I don't actually hate miners. I coded quite a lot for mining on yog.

I just shouted it to piss people off. It worked, too.

Other than that, lavaland as far as i've seen it on /tg/ is fairly easy, especially with dual-wield and your new plasma cutters and all. I figured some more unpleasant surprises along the lines of 'stop being greedy' might change that up.

What's more is that yes, it certainly does mean that the plasma cutter now has a more apparent downside as compared to every other weapon mining can use, rather than being all-around-better.

**Comment by Repukan** [comment]
Meh, I followed what other coders echoed.

Are you gonna port the megafauna buffs you guys made over there too?

**Comment by AdamElTablawy** [comment]
HA no.

That shit was terrible. I'd remove it if trying to do anything over there wasn't an exercise in futility.

**Comment by Repukan** [comment]
Mind pinging me on discord?

I'd like to hear your full thoughts about that but this isn't the place for it, I think.

**Comment by AdamElTablawy** [comment]
sure, what's yours

**Comment by Repukan** [comment]
Repukan#3597

**Comment by AdamElTablawy** [comment]
Not working. Check your BYOND. I'll delete the other messages so the PR isn't cluttered.

**Comment by Repukan** [comment]
Try it again I messed up the numbers.

Deleting previous Convo too

**Comment by jughu** [comment]
Also plasma cutter wouldnt be less greedy issues it be a more of a fuck you while fighting megafauna and you need to make quick halls

**Comment by FantasticFwoosh** [comment]
I love it, unless we find another 'mysterious ore' for it to mimic is a great idea.

**Comment by jughu** [comment]
Salt ore

**Comment by Ergovisavi** [comment]
I originally made gibtonite like this and while on the one hand it was hilarious from one perspective the reality is that due to how you get to diamonds it's just annoying.

Consider that when you have a mimic mob in Dark Souls or even one of the Tales of X games, the mimic isn't usually annoying to get to. You walk up to the mimic, and the encounter begins. The engagement is in the fact that it's a bait and switch.

Meanwhile, Gibtonite disguised as diamonds is often behind 6 tiles of digging which effectively wastes your time for no damn reason. It was a failed experiment, and should not come back.

**Comment by AdamElTablawy** [comment]
Plasma cutters, Ergovisavi.

**Comment by uraniummeltdown** [comment]
Why do we want to punish plasma cutter miners? Least they do their job and bring back minerals quickly.

**Comment by Repukan** [comment]
😂😂😂

**Comment by ExcessiveUseOfCobblestone** [comment]
make a subtype instead with having DOUBLE THE EXPLOSION

**Comment by Anonymous583** [comment]
This is just going to make anyone in their right mind avoid diamond entirely.

**Comment by ExcessiveUseOfCobblestone** [comment]
wrong

**Comment by GunHog** [comment]
No, you would just get ready move back, just in case. Alternatively, you would just smack the gibtonite with your scanner. If you shoot with your KA or plasma cutter, you would just step back. If you are using a melee type mining tool, then you REALLY want be ready to step back. 

I do not exactly agree with this PR, however it is not really a big deal (besides lots of moments filled with disappointment...). Just do not mine a diamond node without an escape plan. Virtually everyone/everything with the ability to mine can safely deal with gibtonite.

**Comment by Swagile** [comment]
> punishing miners for doing their job while subtly encouraging them to be more of a looter hunter than before

:thinking:

**Comment by Repukan** [comment]
Pff.

Dual plasma cutter isn't mining, it's making straight holes to get to tendrils.

The plasma cutters are too good.

**Comment by Swagile** [comment]
that doesn't solve the initial issue of plasma cutter mining then?

just avoid all diamond ores till you really need it

boom, your still OP as fuck with plasma cutters

**Comment by AdamElTablawy** [comment]
good way to piss off science and watch them not give you plasma cutters, though

**Comment by Arianya** [comment]
How is this going to annoy plasmacutter miners, plasma cutters have insane range.

I tend to blow gibtonite incidentally when using them.

**Comment by KorPhaeron** [comment]
Sounds obnoxious to deal with and like it wont kill any player more than once

**Pull request closed without merging**
