### PR TITLE
Check ticks some more in dock()

### PR DESCRIPTION
**Pull request by ninjanomnom**
@Cruix Don't add anything to the un-CHECK_TICK'd portion of the dock proc without great necessity. I'm still trying to cut it down.

The hidden turfs code is placed badly but I'll fix it for real when I break up the dock proc

### CODE REVIEW

**Comment by Cruix** [comment]
You had two weeks to complain about this when the PR was up.

**Comment by ninjanomnom** [comment]
If I could make github notify me when a pr goes up that modifies shuttle.dm I would. I don't look at the contents of every pr.

**Comment by AnturK** [comment]
What are code owners ?

**Comment by ninjanomnom** [comment]
I'm extremely tempted to do that but I don't like how it's not just a personal notification

**Comment by Cyberboss** [comment]
Codeowners was a good idea

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
