### PR TITLE
Makes the Regal Condor realistically simulate being shot dead with a high caliber hand cannon by making it HITSCAN

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

The Regal Condor come with a magazine and ammo already inside.

The recipe for the magazine now no longer needs TC, but does need donk pockets (sponsored murder gear, you see) and a hell of a lot more materials per magazine (you're looking at like 40 sheets of various materials all up). It also needs you to make the Condor first. But it comes preloaded with ammo.

The Condor is 1 whole TC more expensive. Also needs some metal. The old recipe is there in spirit.

The Regal Condor and the magazines come with 10mm Reaper bullets. They're high damage. They're high AP. They are also hitscan. 

## Why It's Good For The Game

Apparently people don't like the Condor. Too much effort for not enough reward. After all, revolvers exist. 'It must be a joke' they say! 'It's joke content! I went to all that effort to make it for nothing! That slut Anne tricked us!'

**Wrong, bitch.**

If you want the Condor to make you shit yourself the moment someone with it appears on the screen, then fine!

## Changelog
:cl:
balance: Despite earlier reports suggesting that the famous lethality of the Regal Condor was largely a myth, there has been rumors that the gun has once again started to display its true killing potential on any station that it 'manifests'.
/:cl:

### CODE REVIEW

**Comment by DaydreamIQ** [comment]
I don't think this really addresses the issue that it's a gun which costs 18tc and 20k out of cargo to obtain. Its a cool gun but most people are just gonna buy a revolver instead of jumping through so many hoops

**Comment by necromanceranne** [comment]
### BORING

**Comment by carlarctg** [comment]
Now this is what I'm talking about. Badass! Though I don't remember anyone calling you a slut.

Just needs some CS references and it's perfect.

**Comment by necromanceranne** [comment]
### In my heart, I know what I am.

**Comment by DaydreamIQ** [comment]
**Look I can use bold text too, it doesn't make you cool**

**Comment by necromanceranne** [comment]
### Speak up, please.

**Comment by TheVekter** [comment]
> ### BORING

Based.

**Comment by Borisvanmemes** [comment]
Does it still fire in a two round burst?

**Comment by Eronymun** [comment]
The Anne try not to make something absurdly powerful challenge (impossible). Super cool though, given the input cost it's well worth it!

**Comment by CCC23** [comment]
who the fuck was saying the condor wasnt good that thing is a 1 click destroyer. though I do love this pr

**Comment by Striders13** [comment]
make it ricochet too!!

**Comment by necromanceranne** [comment]
### Ricochet hitscan projectiles just kill you if you shoot in the cardinal directions and miss. Not really interested. Marksman ammo is bad enough for this.

**Pull request merged**
