### PR TITLE
Add check for soundloop runtime

### LINKED ISSUE #32709: Computers at holodeck runtiming at roundstart
```
[14:03:51] Runtime in _computer.dm, line 70: Cannot execute null.stop().
proc name: power change (/obj/machinery/computer/power_change)
src: the atmospheric alert console (/obj/machinery/computer/atmos_alert)
src.loc: the holodeck projector floor (236,227,1) (/turf/open/floor/holofloor/plating)
call stack:
the atmospheric alert console (/obj/machinery/computer/atmos_alert): power change()
the atmospheric alert console (/obj/machinery/computer/atmos_alert): Initialize(1, null)
the atmospheric alert console (/obj/machinery/computer/atmos_alert): Initialize(1, null)
the atmospheric alert console (/obj/machinery/computer/atmos_alert): Initialize(1)
Atoms (/datum/controller/subsystem/atoms): InitAtom(the atmospheric alert console (/obj/machinery/computer/atmos_alert), /list (/list))
Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
Atoms (/datum/controller/subsystem/atoms): Initialize(686306)
Master (/datum/controller/master): Initialize(10, 0)
```

```
[14:03:51] Runtime in _computer.dm, line 70: Cannot execute null.stop().
proc name: power change (/obj/machinery/computer/power_change)
src: the station alert console (/obj/machinery/computer/station_alert)
src.loc: the holodeck projector floor (236,228,1) (/turf/open/floor/holofloor/plating)
call stack:
the station alert console (/obj/machinery/computer/station_alert): power change()
the station alert console (/obj/machinery/computer/station_alert): Initialize(1, null)
the station alert console (/obj/machinery/computer/station_alert): Initialize(1, null)
Atoms (/datum/controller/subsystem/atoms): InitAtom(the station alert console (/obj/machinery/computer/station_alert), /list (/list))
Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
Atoms (/datum/controller/subsystem/atoms): Initialize(686306)
Master (/datum/controller/master): Initialize(10, 0)
```

ect

### PR DESCRIPTION
**Pull request by psykzz**
Closes #32709

Check for a soundloop before calling to ensure we don't get a runtime.

### CODE REVIEW

**Comment by ninjanomnom** [comment]
This is a problem with initialization order, adding a check here just hides a bug

**Comment by psykzz** [comment]
Can you point me in the right direction? Otherwise ill leave this to someone else and close.

**Comment by Qustinnus** [comment]
the direction is @optimumtact don't blue ball me by merging my WIP prs

**Comment by Qustinnus** [comment]
can be closed

**Pull request closed without merging**
