### PR TITLE
Makes typing indicators use your bubble icon

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Typing indicators now rely on what bubble icon you have, rather than all being the default.

Most speech bubbles with Admin Combo HUD: https://cdn.discordapp.com/attachments/751307359351210014/992025794207551538/speechbubbles.mp4

A new sprite has been added for every bubble type for this to properly work, and nearly all bubble icons have been resprited by @Crumpaloo

All bubbles have been moved to the right side of the user as to not cover their HUDs, so it is now consistent with the default bubbles.

## Why It's Good For The Game

This sucks:
https://user-images.githubusercontent.com/53777086/174477936-98d92891-7d2d-409c-8b9b-f92cd046edc4.mp4

It also lets us re-add one of the main perks of the Lawyer's badge, which is currently locked to not being on runechat, an option that might not exist in the future.

## Changelog

:cl: Crumpaloo, jlsnow301, JohnFulpWillard
add: Typing indicators now use your speech bubble type, rather than all being the same, so Cyborgs no longer look like a human when typing, and Lawyers have that cool speech bubble again.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
> For moving the typing indicator to the left side of the person, it's both so it would be consistent with the rest of the chat bubbles, and also because it currently covers HUDs.

I thought the whole point is it *isn't* covering the HUDs when it's flipped. CC @jlsnow301

**Comment by jlsnow301** [comment]
> I thought the whole point is it *isn't* covering the HUDs when it's flipped. CC @jlsnow301 

That is correct. I was having new sprites made by @crumpaloo for this same project 😅

**Comment by Mothblocks** [comment]
@JohnFulpWillard Can you show a picture of someones typing indicator with a full HUD on? Med HUD, revolutionary icon (or just toggle combo HUD), etc?

**Comment by Wallemations** [comment]
Hell yea, can't wait to see this done

**Comment by JohnFulpWillard** [comment]
Video with (mostly) all speech bubbles, with Combo HUD enabled, in most recent commit

https://cdn.discordapp.com/attachments/751307359351210014/992025794207551538/speechbubbles.mp4

I think this is good to go, I'm just waiting on confirmation that all new sprites were made by @Crumpaloo for changelog credits.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
