### PR TITLE
Catwalk improvements

### PR DESCRIPTION
**Pull request by norill**
- added use wirecutters on catwalk to decon to lattice
- fixed welding catwalk giving only 1 rod
- added delay to building catwalk to avoid unintentional construction

i was unable to fix a bug where deconstructing lattice would not update surrounding lattices

### CODE REVIEW

**Comment by babinsquared** [comment]
:+1: for construction delay. Accidentally placing catwalks and wasting rods was annoying.

**Comment by xxalpha** [comment]
Personally I don't consider giving it a construction delay an improvement.

**Comment by Miauw62** [comment]
???
Op 9-apr.-2015 18:02 schreef "norill" <notifications@github.com>:

**Comment by phil235** [comment]
Why? The PR looked good to me.

**Comment by norill** [comment]
i'm not sure if i wish to contribute to this project any longer

**Pull request closed without merging**
