### PR TITLE
Revert "Revert "adds alternate medborg sprites""

### PR DESCRIPTION
**Pull request by Cyberboss**
Reverts tgstation/tgstation#54629

The dog is cute, stop prejudicing it.

### CODE REVIEW

**Comment by justinbooj9** [comment]
the saga continues

**Comment by LemonInTheDark** [comment]
CYBER NO, YOU DON'T UNDERSTAND

**Comment by Cyberboss** [comment]
I understand everything

**Review by Twaticus — APPROVED** [review]
cool dog

**Review by alexkar598 — APPROVED** [review]

**Review by Fikou — APPROVED** [review]

**Review by MrDoomBringer — APPROVED** [review]

**Review by Mothblocks — APPROVED** [review]
Nobody will tell me what's wrong with this sprite, so I'll just assume it's Reddit

**Comment by DinkleNH** [comment]
dogs r cool upvoted

**Review by kriskog — APPROVED** [review]

**Comment by kriskog** [comment]
Not as cool as a cat, but dogs are cute too.

**Comment by ArcaneDefence** [comment]
I hate the world we live in.

**Comment by LemonInTheDark** [comment]
What do we do with well loved prs folks?

**Comment by Cyberboss** [comment]
> 
> 
> I hate the world we live in.

Try therapy, talking helps

**Comment by optimumtact** [comment]
I WAS WITHOUT DISCORD AT WORK FOR FOUR HOURS

FOUR

**Comment by Twaticus** [comment]
boooooo orange man bad he hates dogs

**Comment by brotherbeyondd** [comment]
cute dog

**Comment by PolishUser** [comment]
Sad, the dog was put to sleep.

**Comment by MaltVinegar** [comment]
😔

**Comment by Fikou** [comment]
butter dawg

**Pull request closed without merging**
