### PR TITLE
Adds luminosity to active welders and eswords.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
:cl: Papa Bones
Welders and eswords now give off light.
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Don't you need to reset that when it's dropped, picked up, or disabled?

**Comment by TechnoAlchemisto** [comment]
Good question!

**Comment by TechnoAlchemisto** [comment]
Okay yeah I figured it out

**Comment by jughu** [comment]
👍👍👍👍
Can you add god hand too its basically a burning hand

**Comment by PKPenguin321** [comment]
But stealth :(

**Comment by jughu** [comment]
Well thats the drawback for having 2x against blob/xenos

**Comment by GunHog** [comment]
>Well thats the drawback for having 2x against blob/xenos

Energy swords are brute.

**Comment by GunHog** [comment]
> Well thats the drawback for having 2x against blob/xenos

Energy swords are brute.

**Comment by kingofkosmos** [comment]
Could it be possible to emit light only when used on something actively? Would make sense on welders at least.

**Comment by jughu** [comment]
@GunHog 
Im speaking about god hand and not eswords

**Comment by TechnoAlchemisto** [comment]
@kingofkosmos If I knew how to code I'd make them emit sparks when welding walls and shit, but it makes sense for the lit welding torch to give off light, I mean, it's lit.

**Comment by PKPenguin321** [comment]
:ok_hand: :fire: 

no but seriously my stealth

**Comment by TechnoAlchemisto** [comment]
Don't use a lightsaber if you want to be invisible in the dark

**Comment by optimumtact** [comment]
What's the difference between this and  #19640

**Comment by TechnoAlchemisto** [comment]
This one has eswords!

**Comment by TheCarlSaganExpress** [comment]
@optimumtact there's actually a couple of differences. There's an error in Techno's code where if the welder runs out of fuel it will still retain its illumination effect. Also, I just want to say that I had absolutely no idea that Techno was implementing this as well. This is honestly a massive coincidence because #19640 is the first time that I have contributed any code.

**Comment by TechnoAlchemisto** [comment]
I actually just added a fuel check, tested and it works as intended!

**Comment by TheCarlSaganExpress** [comment]
Then why not just merge the one with E-Sword? Also, errors still persist in your code. When the player runs out of fuel it will still throw an error, like on line 398-

` 			user << "<span class='warning'>[src] shuts off!</span>"
 		user.AddLuminosity(-1)`

You can't use "user" here, I don't know the exact reason because I'm getting acquainted with byond code, but it will throw an error here. Also, it still throws an error when you run out of fuel.

**Comment by TechnoAlchemisto** [comment]
I haven't really experienced an error when I tested it, but I'm not against merging just the esword one.

**Comment by optimumtact** [comment]
Right so this code is ugly as sin, define a switched_on and switched_off proc, call them at appropriate moments and handle the luminosity updating there, look to move anything else you can there as well, such as on/off messages (with perhaps a held/on floor arg to determine what kind of on/off message to show).

That goes for your pr too @TheCarlSaganExpress

**Comment by TechnoAlchemisto** [comment]
I have no idea how to code I literally made this by just looking at the lighter code and copying it

**Comment by optimumtact** [comment]
Then learn how to code.

**Comment by TechnoAlchemisto** [comment]
I'm learning from our existing code D:

**Pull request closed without merging**
