### PR TITLE
Stackable zipties

### PR DESCRIPTION
**Pull request by ghost**
Zipties now come in stacks of 5 to make them less worthless. However, they have half the breakout time of normal cuffs and can be instantly removed with wirecutters like cable cuffs.

Fixes zipties being usable in stun prod construction and being washable in machines.

Commence oberating

### CODE REVIEW

**Comment by Razharas** [comment]
Woe woe woe, oh why dont byond have interfaces, why are we forced into this madness of typechecks and inability to combine procs of different types

**Comment by paprka** [comment]
byond is babby's first game development what did you even expect

**Comment by Razharas** [comment]
Respectable game development platform

**Comment by optimumtact** [comment]
Let me just make sure it doesn't delete people

**Comment by paprka** [comment]
if(handcuffed.ckey == "optimumtact")

**Comment by phil235** [comment]
merge conflict

**Comment by Jordie0608** [comment]
Changelog

**Pull request closed without merging**
