### PR TITLE
Kills throwing tiles.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

See title.

## Why It's Good For The Game

Critting people with 10 floor tiles is bad gameplay.

## Changelog
:cl:
balance: Tiles no longer do 10 damage on throw.
/:cl:

### CODE REVIEW

**Comment by MMMiracles** [comment]
did someone die to tile-fu

**Comment by Paxilmaniac** [comment]
An ided pr by a man who doesn't play the game. We are reaching levels of power that far surpass normal levels.

**Comment by Serxule** [comment]
i never see anyone use a floor tile unironically, its mostly a joke than an actual use.

**Comment by MMMiracles** [comment]
> 
> 
> @MMMiracles i didn't die, im just preventing tourist bot deaths

this solves literally nothing if your end-goal is to prevent them from dying

**Comment by cacogen** [comment]
This has been in the game perhaps since before /tg/station and I don't see it used that often. You have to hit them ten times, so assuming they're being thrown that's pretty fair. Just seems like a salt PR and it will ultimately be easier on you just to let it go.

Took me ages to realise that the thing of it giving you an estimation of its damage based on how many throws to crit a human was something I'd added. Should be on all objects to be quite honest with you friend

**Comment by YakumoChen** [comment]
It's mostly used against slow moving targets for people who have nothing better to do, like Cult juggers. 

Why are we balancing the game around tourist bot abuse lmao

**Comment by Iamgoofball** [comment]
alright, the other reason is that throwing tiles are dumb

**Comment by Mothblocks** [comment]
I think this is dumb, you'll need to provide a better reason for it.

**Comment by cacogen** [comment]
If somebody is hit by a tile hard enough it should cause damage to the area of the body it hits. Our health system supports that. Presumably they do that already. Why would it embed without doing any initial damage? Adding an embed to floor tiles for normal throws (as opposed to things propelled with explosive force) doesn't make sense either. They aren't sharp.

**Comment by Timberpoes** [comment]
> I think this is dumb, you'll need to provide a better reason for it. Fix the tourist bots not factoring in things being thrown at them or whatever the problem is, you might be surprised to learn there's a lot more stuff that damages when its thrown.

Second this sentiment fully.

I'm not gonna see combat nerfs targeted at protecting simplemob tourists. Let's just not go there.

**Comment by ATH1909** [comment]
> @MMMiracles i didn't die, im just preventing tourist bot deaths

then people will just use other items that happen to have a decent throwforce. most throwing items are reusable.

**Comment by ATH1909** [comment]
also

image

**Comment by ATH1909** [comment]
> you could just buff their armour against whatever damage type this is

simplemobs don't get access to armor vs. most attack methods, they just use multipliers for brute, burn, tox, etc. damage. I think goliaths have some anti-thrown item code (or at least an invocation of said code) that you can yoink, though.

**Comment by ATH1909** [comment]
> alright, the other reason is that throwing tiles are dumb and our health system doesn't support the level of depth that we would need to make throwing tiles not dumb
> 
> unless we made them do no damage but embed real hard

could you elaborate on WHY they're dumb?

**Comment by YakumoChen** [comment]
Make them embed I think the concept of a 1x1m hunk of metal sticking out of your eyebrow and just defying gravity sounds hilarious

**Comment by YakumoChen** [comment]
Also nobody tell goof that toolboxes have the same throw force shhhh

**Comment by Iamgoofball** [comment]
@YakumoChen you can't stack 50 toolboxes in one inventory slot

**Comment by CRITAWAKETS** [comment]
> @YakumoChen you can't stack 50 toolboxes in one inventory slot

you also have to seperate every single tile because if you throw a stack, it just counts as throwing 1 tile

**Comment by esainane** [comment]
this PR makes Fleur Tyles sad

**Comment by XDTM** [comment]
> 
> 
> > @YakumoChen you can't stack 50 toolboxes in one inventory slot
> 
> you also have to seperate every single tile because if you throw a stack, it just counts as throwing 1 tile

Some people can use either keybinds with muscle memory or straight-up macros to do that really fast, so he does have a point there, although the correct nerf for that would be to prevent rapid-fire unstacking somehow.

Also wasn't a common response to sleeping carp/double esword nerfs to 'get robust and throw floortiles'? It _has_ had a significant place in the combat meta, which is kind of unfitting for cheap construction material.

**Comment by cacogen** [comment]
In defense of iamgoofball

**Comment by Sparkezel** [comment]
> > > @YakumoChen you can't stack 50 toolboxes in one inventory slot
> > 
> > 
> > you also have to seperate every single tile because if you throw a stack, it just counts as throwing 1 tile
> 
> Some people can use either keybinds with muscle memory or straight-up macros to do that really fast, so he does have a point there, although the correct nerf for that would be to prevent rapid-fire unstacking somehow.
> 
> Also wasn't a common response to sleeping carp/double esword nerfs to 'get robust and throw floortiles'? It _has_ had a significant place in the combat meta, which is kind of unfitting for cheap construction material.

I NEVER EVER saw that happen on terry. Even if people start doing that just duck at them lol, what will they do?

**Comment by maxymax13** [comment]
making an ided pr for something that has never been done in the history of ever, peak tg

**Comment by Iamgoofball** [comment]
Throwing tiles used to be meta, before your time zoomer.

**Comment by XDTM** [comment]
On a second look through the forums, the only people mentioning floor tiles as weapons were those who were trying to justify double eswords and carp projectile immunity being fair and balanced, so i cannot really take them seriously.

Unless we get a scripter epidemic, nerfing tile damage doesn't seem very necessary. They also compose a good part of the shrapnel from large explosions, and i feel like it would be a pity to lose that, if there's no balance issue to correct.

**Comment by ilikesaying** [comment]
start throwing botany hatchets

**Comment by eeSPee** [comment]
I once died to tile-fu. The thing is, I was hijack tot and had 3 guns on me. It was me and another guy on the shuttle.

**Pull request closed without merging**
