### PR TITLE
Give plasmamen their plasma suits in VR

### LINKED ISSUE #38364: Plasmamen spawn without their suit in VR
localhost latest commit

1) become plasma
2) go to vr
3) spontaneously combust

this is bad because it means plasmamen can't do VR

### PR DESCRIPTION
**Pull request by SpaceManiac**
:cl:
fix: Plasmamen now receive their suit and internals when entering VR.
/:cl:

Fixes #38364.

### CODE REVIEW

**Comment by DaxDupont** [comment]
Is istype necessary? The original code for the ID cards didn't use it.

**Comment by chesse20** [comment]
they shouldnt be able to combust in vr

**Comment by DaxDupont** [comment]
@chesse20 plasmamen players must suffer

**Comment by SpaceManiac** [comment]
It's probably not necessary but I felt like throwing it in there in case someone eventually puts a non-ID in the ID slot.

**Comment by GuppyLaxx** [comment]
let me suffer

**Pull request merged**
