### PR TITLE
Reworks Guvax

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
experiment: Guvax is now targeted; invoking it charges your slab to bind and start converting the next target attacked in melee within 10 seconds. This makes your slab visible in-hand.
tweak: Above 5 Servants, the invocation to charge your slab is not whispered, and the conversion time is increased for each Servant above 5.
wip: Using Guvax on an already bound target will stun them. The bound target can resist out, which will prevent conversion.
experiment: Sentinel's Compromise is now targeted, like Guvax, but can select any target in vision range.
rscadd: Sentinel's Compromise now also removes holy water from the target Servant.
wip: Clicking your slab will cancel these scriptures.
imageadd: Both of these will change your cursor, to make it obvious they're active and you can't do anything else.
/:cl:

Convert times are faster at very high servant amounts, but it's much easier for 1-on-1 conversions to go wrong and have the target escape. (Though the binding makes early conversions slightly easier.)

Resist time for the binding is a flat 4 seconds, and moving/being moved while chanting will break it immediately.
Formula for conversion time is `5 + (0.5 for each valid servant above 5)` seconds up to a maximum of 10 seconds at 15 servants.

### CODE REVIEW

**Comment by Supermichael777** [comment]
remove convert traps
i have seen them used by people to get antag

**Comment by ChangelingRain** [comment]
I'd like to note, since this is important; while this is a stunpaper-like effect, it's much, much less awful in design.

You have to:

1. Finish the initial chant to charge your slab.
2. Get to the target you want to convert with your slab fully-visible, click them in melee(with full awareness you're coming at them).
3. Finish the chant that starts without them escaping the binding or you being interrupted(which may be difficult, depending on where you managed to click them and how fast they react).

All of those need to be done without being stunned or disarmed and 1. and 3. need to be done without moving.

As compared to stunpapers, which are just 'Get the paper out of your pocket, hit the target before they react, get them out of the way.'

**Comment by TechnoAlchemisto** [comment]
Does the chant being interrupted counter the binding? Because otherwise you could just stun and cuff them

**Comment by ChangelingRain** [comment]
Yes, the chant being interrupted breaks the binding.

**Comment by AdamElTablawy** [comment]
probably good to testmerge this, it'll be very difficult to convert now

**Comment by ChangelingRain** [comment]
This is having about the effect I want; obvious, but effective if the target doesn't resist quickly enough. It just needs some tuning so that it's less effective later in the round/when there are a lot of servants active.

**Comment by ExcessiveUseOfCobblestone** [comment]
rip clockwork shuttle madness where you just start converting people in bulk.

**Comment by XDTM** [comment]
If you get binded you can always resist out unless you're lagging or want to join the antag team; trying to move starts the resist so it's pretty much instant. Basically this means that you need a buddy disarming the target while you convert, although this isn't necessarily a bad thing, i guess.

**Comment by ChangelingRain** [comment]
A buddy can also invoke Guvax to stun the bound target briefly, though disarming is probably still more practical.

**Pull request merged**
