### PR TITLE
Fix holymelon armor not inheriting magic resistance

### LINKED ISSUE #87621: Antimagic Does Not Block Void Heretic Status Stacks
### Client Version:

515.1637

### Issue Summary:

Antimagic does not block the status stacks from at the least the void ascension effect. I did not test to see if there's a similar issue with the other void heretic spells that apply the stacks like void conduit.

### Round ID:

[241147](https://scrubby.melonmesa.com/round/241147)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [[TM ONLY] The roundstart report will only ever show either Pulsar Star or White Dwarf](https://www.github.com/tgstation/tgstation/pull/87584)

### Reproduction Steps:

1. Have antimagic
2. Be next to an ascended void heretic
3. Still get the status stacks

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
- Fixes #87621

Holymelon armor had a missing antimagic flag that did not stop magic attacks. The holymelon plant gene has `MAGIC_RESISTANCE|MAGIC_RESISTANCE_HOLY` but the armor only had `MAGIC_RESISTANCE_HOLY` so this is just making it consistent.

## Why It's Good For The Game
Consistency.

## Changelog
:cl:
fix: Fix holymelon armor not inheriting magic resistance
/:cl:

### CODE REVIEW

**Review by MrMelbert — APPROVED** [review]
I'm not touching the label because I agree with the "consistency" justification, however I have to wonder if it was done intentionally because making cheap, mass producible antimagic armor seems a little crazy

**Comment by timothymtorres** [comment]
I double checked the [original PR](https://github.com/tgstation/tgstation/pull/85128#top)'s commits, reviews, and description and none of them mentioned anti magic specifically. The most it says is:

> add: You can now hollow out melons of all kinds with a spoon to make helmets or chestplates, based on the potency! If you are unlucky, you can tie up three helmets into a chestplate with durathread using the crafting menu.

They did however set the number of antimagic charges to be a hardcoded 1, regardless of potency.

**Comment by Deadgebert** [comment]
This is a pretty big balance change. This shuts down most heretics, early cult, and many wizard builds. You can currently play around it by knocking the holy melon out of their hands, but you can't really knock armor off someone.
I think this is a horrible idea for game balance reasons and I don't think 'consistency' justifies it.

**Comment by timothymtorres** [comment]
You didn't read the PR. The melon armor already has holy resistance. (which blocks a decent amount of magic and spells) The number of charges hasn't been changed. It's still 1 charge no matter the potency.

**Comment by Deadgebert** [comment]
I did read it, quite thoroughly to be sure you were actually trying to change what I thought you were. 

Holy resistance does not block much at all, and it does not matter if it only has one charge. Most spells have a cooldown and the anti-magic shield lasts about 5 seconds, far more than enough time to rush down whatever magical entity you're hunting.

Holy resistance blocks the following - 
Voice of god
Juggernaut Fist
Abyssal Gaze (i don't think this is in the game)
Dominate (i don't think this is in the game)
Tie Shoes
Cult Convert
Chaplain Music
and various revenant + vampire stuff.

The change you are proposing is immunity to... everything else?

**Comment by timothymtorres** [comment]
> Holy resistance does not block much at all, and it does not matter if it only has one charge. Most spells have a cooldown and the anti-magic shield itself lasts about 5 seconds, far more than enough time to rush down whatever magical entity you're hunting.

Guess who spent several months rebuilding the antimagic component to make it more robust?

[Me.](https://github.com/tgstation/tgstation/pull/64124)

So let me tell you some relevant facts:

The visual red anti-magic shield is a cosmetic effect so others can see if a person has spell resistance in their possession. It was a _vast_ improvement over the `to_chat` message people would get that was not obvious. The time duration of the shield itself does nothing. The only thing that determines if you block magic is how many charges are left.

You cannot stack anti-magic items together to get more charges since they all simultaneously lose one charge. So if you have a helmet + armor, it only gives you one charge instead of two since they both will be drained at the same time.

Also the null-rod is a terrible comparison. It has infinite charges and can be put in your pocket (and backpack I think?) while still giving you FULL anti-magic resistance to everything.

> The change you are proposing is immunity to... everything else?

The change I am proposing is to keep the holymelon effect the same. There is no good reason why it was removed and it was not documented in their PR anywhere.

**Comment by Ghommie** [comment]
Perhaps, we will nerf these armors later if necessary.

**Pull request merged**
