### PR TITLE
GAGS Lizard Plushes 

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

This PR converts lizard plushes to GAGS. 

Now, all lizard plushes are generated with a random (valid) lizard body color when they're created.
image
image

This PR also repaths lizard plushes to use snake case and makes the space lizard plush its own type of plush, instead of a lizard subtype, since the space lizard plush is untouched by GAGS.

## Why It's Good For The Game

All lizards of all colors are now represented by the lizard plushes, isntead of just green lizards. Hurrah!

## Changelog
:cl: Melbert
add: GAGS Lizard Plushes. Now, lizard plushes get a randomly generated lizard color when they're made. 
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Speed merge.

**Comment by CRITAWAKETS** [comment]
would it be possible to make spray-painting the lizard plush change the color? I want to make the Pride Lizards.

**Comment by MrMelbert** [comment]
> 
> 
> would it be possible to make spray-painting the lizard plush change the color? I want to make the Pride Lizards.

Not sure how GAGS works with spray cans, so I can't say, but if someone puts them in a vendor at some point you'd be able to chose their color.

**Comment by Mothblocks** [comment]
Spray cans just set color, but we could totally add an element or similar to get it to spray paint GAGS portions.

Out of scope, though.

**Comment by ATH1909** [comment]
cute!

**Comment by EOBGames** [comment]
Can I have permission to merge this one? Please?

**Comment by TheBonded** [comment]
> Can I have permission to merge this one? Please?

You have my totally legitimate permission. Do it

**Review by Twaticus — APPROVED** [review]

**Comment by EOBGames** [comment]
lizard plushies, my love

**Pull request merged**
