### PR TITLE
Wizard rods now do less damage

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
balance: Wizard rods now do less damage, and, unless the wizard has only used points on rod form, will not instantly put you into critical.
/:cl:

Very simple, means the rod won't instantly kill you or put you into crit unless the wizard has it as their literal only spell.
Closes #26537

Spell level scaling:
1. 60 damage
2. 70 damage
3. 80 damage
4. 90 damage
5. 100 damage

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Someone fixing rod form?
My god

The legends were true

**Comment by coiax** [comment]
Well this is needing it into the ground

**Comment by coiax** [comment]
Nerfing

**Comment by XDTM** [comment]
Yes, but it's the level of power it should've had in the first place

**Comment by FantasticFwoosh** [comment]
I once got instantly knocked down into crit as a bartender (with my armor) while a wiz was about 3 tiles away from me and started casting the spell, the rod also moves quite fast which makes the violent nature of it passing through worse. Full orange and high damage yellow on my chest where my protection was.

Glad to see its being brought to heel.

**Comment by ChangelingRain** [comment]
Well no shit this is nerfing it into the ground, it's going from an instant crit+10% chance of just flat out killing to these values.

**Comment by Robustin** [comment]
I prefered the 3-point cost, hell make it 4.

I never thought Rod form was that bad. Once you knew the wizard had it, it was easy to play around. The only issue was that at 2 points you would fit it into almost any wizard archetype. It's cooldown could've been increase too.

This just makes the spell useless and into the graveyard of "kind of interesting wizard spells that nobody will ever take because coders were too eager to nerf it".

**Comment by ExcessiveUseOfCobblestone** [comment]
If you take the gimmick [that is, being an actual immovable rod] away why even keep it? The whole point of the spell was gimmicky high octane memes.

Honestly if the complaint is it's both an offensive and mobility spell in one, just make it 4 points.

**Comment by ChangelingRain** [comment]
Gimmicks can get balanced like everything else.
It's still literally an immovable rod, but it's not an instantly lethal rod unless you spend all your points on it.

**Comment by Robustin** [comment]
Balance can come in point cost. You're making it cost 10 for its current functionality (along with a much lower cooldown), we're saying that 4 would already be plenty to prevent it from being abused.

At 10 points to crit, you might as well remove the spell because the only people who are going to take it will be those who don't vigorously read patch notes and they will subsequently get shit on for it.

Making it 4 points means wizards will immediately understand the balance implications and nobody has their wizard round ruined because they didn't check every single changelog.

**Comment by ChangelingRain** [comment]
I want to keep it at 2 points so you can get the lowest possible cooldown if you spend a lot on it.
Damage at each level can be easily adjusted, as well, so maybe suggest some values?

**Comment by KorPhaeron** [comment]
Gonna try what Coiax PRd first

**Pull request closed without merging**
