### PR TITLE
Heads of Staff can no longer wear cat ears

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
tweak: Heads of Staff can no longer wear cat ears
/:cl:

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
why is that a good change?

**Comment by MoreRobustThanYou** [comment]
because it prevents them from bypassing the "catpeople aren't allowed as heads of staff" thing

**Comment by The-clown-known-as-Pepe** [comment]
does their species change when they wear kitty ears?

**Comment by MoreRobustThanYou** [comment]
@The-clown-known-as-Pepe There is almost zero way to tell the difference between a catperson and someone wearing cat ears visually ---- making them nearly the same.

also kitty ears don't change the species either way

**Comment by The-clown-known-as-Pepe** [comment]
@MoreRobustThanYou block inserting cat ears and tail thru surgery too then

**Comment by The-clown-known-as-Pepe** [comment]
>There is almost zero way to tell the difference between a catperson and someone wearing cat ears visually ---- making them nearly the same.

so why is this a change towards command staff only?

**Comment by MoreRobustThanYou** [comment]
@The-clown-known-as-Pepe Also I just notice _**you have a catperson avatar, therefore your opinion means jack shit on this PR**_

**Comment by optimumtact** [comment]
I literally just told awesine this but stop touching this shit, it's maintainers only at this point

**Comment by FantasticFwoosh** [comment]
The nightmare never ends @optimumtact

**Pull request closed without merging**
