### PR TITLE
Greentext can now be turned off

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Does not prevent actual objective generation, just the text

## Why It's Good For The Game

Speedrunning a shuttle call after killing all the antags/doing steal objectives so they can see a red or green text at the end of the round isnt a good thing.

This arcade speedrun gameplay style is frankly,
shit.

It discourages RP and makes for a competitive play to win mentality instead of a play to have fun/create a good story mentality.

In particular this is seen on manuel where antags do _nothing_ all round only to silently do a steal objective 5 minutes before shuttle dock, which makes  for an abysmally boring round. LRP might want to keep this around(?) which is why it is a config option.

As some people are uncreative I also opted to leave objectives in.

## Changelog
:cl:
add:  Greentext can now be disabled through config
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
Is there interest for this on Manuel?

**Comment by optimumtact** [comment]
Where is the even coming from

**Comment by trexter555** [comment]
this isnt going to change anything

**Comment by wesoda25** [comment]
Sounds like there need to be more objectives on manuel then

**Comment by LemonInTheDark** [comment]
This does sound more like an issue with the objectives, though there are people who act like that.

**Comment by TiviPlus** [comment]
> Is there interest for this on Manuel?

Yes

> Where is the even coming from

Because Manuel antags suck so much a rule was added that tried to force them to engage with the crew over afking/validhunting other antags until the shuttle is called.


> Sounds like you need to change the objectives themselves

The issue is the people chasing the """win""" instead of actually engaging with the crew

Additionally, Mrmelbert is currently working on something along those lines

**Comment by Jared-Fogle** [comment]
> The issue is the people chasing the """win""" instead of actually engaging with the crew in a fun way.

If they still have objectives, then they can still """win""" even if the text isn't red.

**Comment by itseasytosee** [comment]
I don't think this is going to do anything but you bring up an interesting topic.
Manual is super boring the majority of the time. Without conflict, you are playing a job simulator. Antags either use their status as a pass to do whatever they want, perhaps because they get an odd joy out of making sprites go sideways or other methods of getting pleasure from other people's disgruntlement. Or they do there best to do their personal objectives in which only security will ever interfere with and not even then if the do it well enough.

In a community of people interested in storytelling and occ respect, objectives would be plenty fine at making a base from which traitorous bastards can add conflict into the round, no rules would be needed. But how do you implement features that force people into this mindset? You can't.

The issue here is that the antagonists do not interact with the crew as a whole, the most interesting part of the story is only ever experienced by them. At most Security gets involved or someone might fight off or die to a personal assailant. Nothing for the chef to do except cook burgers.

As a person who has suffered from "do your objectives in a badass and unseen way" syndrome, this would not make me want to accomplish my objectives any less.

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
Please document this config in `game_options.txt`, commented out.

**Comment by wesoda25** [comment]
The point _is_ to win. You are sent to complete a series of objectives, it is your entire point of being as an antagonist. Characters are free to ignore this if they please, as they clearly do on lrp, however mrp rules force them to make an effort at their objectives. This isn’t a problem with greentext, this is a problem with mrp itself. That, and linear objectives. Regardless, disabling greentext changes nothing.

**Comment by TheVekter** [comment]
Sounds interesting. I can see it possibly being misused for some situations, but I kinda like the idea of being able to toggle this.

**Comment by necromanceranne** [comment]
Actually, I have some actual insight into this change.

So, weirdly, I'd argue that objectives are actually a good element since they contribute to putting players into goal orientated mindsets. They are there to provide an objective 'success' or 'failure', and that means the stakes are reasonably high for antagonists on whether they survive or, in the case of glorious death, survive long enough to achieve their objectives. Which differentiates normal crew in this regard. If they have no objectives whatsoever, usually, crew are more willing to sacrifice themselves recklessly than the antagonists who are super motivated to survive. It's a really weird dichotomy.

Removing greentext actually just provides zero feedback on success or failure, so players are going to be significantly less inclined to bother with it, since they won't know whether or not they've absolutely succeeded or there existed some twist that ensured their failure that was unforeseen. This is actually one of the things that will be more important for newer players than older players. Older players are typically the ones to utterly ignore their objectives to go do X, whatever X might be.

I saw another server do this exact change. The result wasn't more RP. It was either extremely listless antagonists, or it was even more murderboning since nothing mattered and the antags out the gate just went gun-ho since as far as their objectives were concerned, what did it matter? With no motivation, who cared. The greentext is a pat on the back for playing and trying. But it's also to demonstrate to everyone else you were trying to achieve your goals and how close you got. It tells us whether you were playing or role or not.

**Comment by Fikou** [comment]
what is the point of this, the only thing this will do is make it more confusing whether an antagonist completed or didnt complete an objective

**Comment by moocowswag** [comment]
Can we get a more clear indication for what you`re trying to fix/solve and how exactly you`re solving it?

Correct me if im wrong but your reasoning makes it seem like you`re trying to force/pressure antags into doing more than just their objectives on MRP/HRP servers because all they do is hide all round and do their objective as obscurely as possible?

Thats not chasing a win, thats following the rules because if you get outed as an antag you`re kind of forced to break the rules and murderbone anyone that walks up to you since ss13 combat is largely stunbased and it only takes one click to end your run.

You also seem to be trying to stop the reverse of people killing antags/meta-ing out their objectives then calling shuttle so they can see who they red texted and go onto the next round to roll antag themselves.

All of this sounds more like server policy issues that you`re attempting to conflict with (and will fail to since you atleast made this an option and removing greentext doesnt really stop people from doing their objectives, it simply takes away proof that they have won which is simply not okay).

**Comment by optimumtact** [comment]
@moocowswag  I don't know who you are but you clearly are talking out of your butthole.
>All of this sounds more like server policy issues that youre attempting to conflict with

This is a configuration setting, so it's enabling admins to even consider a policy discussion

**Comment by Spepbuthewranglesgithub** [comment]
i don't see how this would change anything, nor do i see any server actually using the config.

**Comment by optimumtact** [comment]
There's no reason to merge this before you've had a conversation with the admin team about this and the headadmins are on board with trialling it.

**Comment by moocowswag** [comment]
@optimumtact you cut off the part where i said (and will fail to since you atleast made this an option) and instead said its a server config, dont know why you need to repeat what i said but in your own words.

**Pull request closed without merging**
