### PR TITLE
Bluespace RPED beam sprite change

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl:
sprite: changed the bluespace rped beam sprite
/:cl:

the old sprite really bugged me because it looked ugly so i changed it to the bsa sprite which can look like one continuous beam instead of a bunch of weird diamonds.

Before:
untitled

after:
untitled1

also the bsa sprite is animated so yeah

also in a later pr i wanna go back and redo a lot of the projectile sprites, specifically adding blur to lasers

### CODE REVIEW

**Comment by evsey9** [comment]
THIS WILL CHANGE RND -FOREVER-

**Comment by GunHog** [comment]
And old/new comparison is an order due to this being a sprite PR.

**Comment by phil235** [comment]
Please stop with the dumb titles.

**Comment by Tacolizard** [comment]
@phil235 

> THIS WILL CHANGE RND -FOREVER-

**Comment by WJohn** [comment]
It's still garbage but I guess it's technically slightly less garbage.

**Comment by GunHog** [comment]
You could totally make it even less garbage, WJ! You vastly improved the medical beamgun sprite, why not do so here? You could even make it so that you have blobs of light travelling along a thin beam, across both sides to signify the exchange of parts!

We untalented coders can criticize all we want, as we lack the ability to improve the sprite (aside from deleting it or replacing it with another). You, WJ, are an artist. _You can make it better._ By complaining about it being garbage, you somewhat obligate yourself into contributing a superior solution!

**Comment by Bawhoppen** [comment]
Use sprite change tag on changelog instead of tweak

**Comment by Iamgoofball** [comment]
:-1: ruining a classic

**Comment by Iamgoofball** [comment]
@GunHog yeah but in this case the chef is complaining the bass is fuckin raw

fix it

**Comment by PKPenguin321** [comment]
pshoom

**Comment by WJohn** [comment]
You didn't commit the sprite file change, actually.

**Comment by Tacolizard** [comment]
@WJohn I didn't delete the rped beam sprite, i just changed the beam the rped makes to the bsa beam sprite.

**Comment by Iamgoofball** [comment]
it doesn't use that sprite because it looks super weird with overlapping, especially at angled beams you nerdlord

this will look way shittier

**Comment by WJohn** [comment]
Wait we have two equally shit sprites for beams?

Huh.

**Comment by Iamgoofball** [comment]
Yeah, I made the BSRPED one so that it looked a little less autistic at angles.

**Comment by WJohn** [comment]
In that case, use the medbeam sprite. It also has the thin/thick parts shtick going on, and while it's animated it'll be so brief it shouldn't be terribly noticeable.

**Comment by Iamgoofball** [comment]
I also wanted it to be very obviously the BSRPED so people will know "hey science doing #work" and not "UGH SCIENCE UPGRADE MY MACHINES ALREADY FUCK" "i upgraded them earlier"

**Comment by Tacolizard** [comment]
"A classic .45 handgun with a small magazine capacity. An engraving on the side reads: Tacolizard Forever"

**Pull request closed without merging**
