### PR TITLE
Makes medipens unable to be emptied and then filled with toxins for a hardsuit-piercing OHKO weapon that has the disguise of medical aid

### PR DESCRIPTION
**Pull request by silicons**
opencontainer lmao

### CODE REVIEW

**Comment by Ergovisavi** [comment]
>opencontainer

**Comment by LanCartwright** [comment]
fucking ridiculous instantly flooring a hardsuited shielded person

**Review by Cyberboss — APPROVED** [review]

**Comment by FantasticFwoosh** [comment]
Produce them via RnD instead or something, lol this is hilarious.

**Comment by MoreRobustThanYou** [comment]
But muh neurotoxin pens for absorbing the captain

**Comment by Durkel** [comment]
A way to produce these would be kind of cool though, upgradable chem dispenser when? Minus the hardsuit pierce of course.

**Comment by MoreRobustThanYou** [comment]
Maybe like, make them be able to get through "softsuits" (space suits, biosuits, etc) but not hardsuits

**Comment by octareenroon91** [comment]
Research has the PIERCING SYRINGE

**Comment by FantasticFwoosh** [comment]
Yes but if you replaced it with empty medi-pens it'd stop syringeguns with piercing syringes meta and keep RnD grounded, so you "could" use it to stab people through suits early but can't shoot it at range.

**Comment by alexkar598** [comment]
Is it the emergency medipen?

**Comment by Fox-McCloud** [comment]
>Is it the emergency medipen?

Yep.

**Comment by MoreRobustThanYou** [comment]
MUH NEUROTOXIN PENS

**Comment by Iamgoofball** [comment]
just in case you weirdos are thinking this was intentional, I added epipens and yes this wass a bug

**Comment by ChemicalRascal** [comment]
Goof get off reddit

**Comment by Iamgoofball** [comment]
fuck you

**Comment by MoreRobustThanYou** [comment]
muh neurotoxin insta-stun pens

**Pull request merged**
