### PR TITLE
Manually correct dir on every special airalarm

### LINKED ISSUE #62752: Air alarms are offset improperly
Reporting client version: 514.1569

## Round ID:
[172873](https://scrubby.melonmesa.com/round/172873)

## Testmerges:
N/A

## Reproduction:

Reproduces itself as it is related to the offset of air alarms.

image

### PR DESCRIPTION
**Pull request by esainane**
## About The Pull Request

Air alarm equivalent of #62789 with more manual intervention.

Manually corrects the dir on every special air alarm.

Also fix the placement of the box mixing air alarm.

`GBP: No Update`, please.

## Why It's Good For The Game

mea culpa

Fixes #62752

## Changelog

:cl:
fix: Special air alarms (syndicate, ruins, unlocked, engine, etc) should now all be facing the correct direction.
fix: IceBox's Mixing Chamber air alarm is now placed on the correct tile.
/:cl:

### CODE REVIEW

**Comment by ORCACommander** [comment]
62752 is not just limited to special alarms. Standard air alarms are also upside down now|
image

**Comment by ORCACommander** [comment]
https://github.com/tgstation/tgstation/pull/62601/checks?check_run_id=4129485893

looks like every single icon was inverted for some reason

**Comment by esainane** [comment]
All wall items are now consistent in their direction, floor to wall. See #62601, and the large table in the description behind the `Table of various paths, related paths, and the adjustments they used` fold detailing the previous state of affairs - it's not as simple as every single item being inverted, only the icons that weren't consistent with using dir as floor-to-wall were inverted. In that screenshot, it looks like that air alarm has its dir set correctly, but its icon hasn't been updated. That doesn't look like a tg sprite, so perhaps that is from downstream differences?

**Comment by ORCACommander** [comment]
> 
> 
> All wall items are now consistent in their direction, floor to wall. See #62601, and the large table in the description behind the `Table of various paths, related paths, and the adjustments they used` fold detailing the previous state of affairs - it's not as simple as every single item being inverted, only the icons that weren't consistent with using dir as floor-to-wall were inverted. In that screenshot, it looks like that air alarm has its dir set correctly, but its icon hasn't been updated. That doesn't look like a tg sprite, so perhaps that is from downstream differences?
yep, downstream respite. Sorry i didn't check that

**Review by Maurukas — APPROVED** [review]
Everything looks correct to me.

It's not urgent and doesn't need to be in this PR, but when you get a chance could you look at the Camera Report verb under the mapping tab? It seems very unhappy with the changes to cameras and is reporting everything as disconnected.

**Pull request merged**
