### PR TITLE
washing machine can be used as ghetto filter

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
add: washing machine can be used as ghetto filter
/:cl:

how it works:
you put the unfiltered beakers inside
then you screwdrive and put empty beakers,
turn it on
each chem in the beakers gets moved into the empty beakers

might need more edge case testing but it works

### CODE REVIEW

**Comment by cacogen** [comment]
what

**Comment by tralezab** [comment]
it's better than toilets and doesn't have the piss perfume, so you have that

**Comment by Potato-Masher** [comment]
what

**Comment by ATH1909** [comment]
From what I can tell, this tries to put only one kind of reagent in each beaker.

In other words, if you put a 20u oil/15u mannitol mix in there with some beakers, this will put 20u of oil in one beaker and 15u of mannitol in another beaker.

**Comment by cacogen** [comment]
it bugs me because it doesn't make sense which i can sometimes forgive (e.g. borgs being able to do certain things that would actually require hands) but i don't know why you want this

**Comment by ninjanomnom** [comment]
what

**Pull request closed without merging**
