### PR TITLE
Create MAINTAINER_GUIDELINES.md

### PR DESCRIPTION
**Pull request by Cyberboss**
This is echoing a post I made on the maintainer team page.

@tgstation/commit-access

### CODE REVIEW

**Review by spookydonut — APPROVED** [review]

**Review by stylemistake — APPROVED** [review]

**Comment by Jared-Fogle** [comment]
According to @stylemistake, 4 approvals bypass the 24 hours requirement. If this is true, it should be put on here as well.

**Review by Timberpoes — APPROVED** [review]

**Comment by Timberpoes** [comment]
> 
> 
> According to stylemistake, 4 approvals bypass the 24 hours requirement. If this is true, it should be put on here as well.

Be the change you want to see in the world. Approve this and let's see if that's really true!

**Comment by stylemistake** [comment]
Never said that, but in my opinion, 2 maintainer approvals (1 reviewer, and one who actually merges the thing) make the speedmerge legitimate.

**Comment by Jared-Fogle** [comment]
ive been goofed https://github.com/tgstation/tgstation/pull/53372#issuecomment-684146337

**Comment by LemonInTheDark** [comment]
Nooooooo now I can be held to our guidelines ahhhhhhhhhhhhhhhhhhhhhhhhhhh

**Review by Rohesie — APPROVED** [review]

**Comment by Ryll-Ryll** [comment]
> Also I already regret merging wzhzhzhzh before 24h, because it could've collected way more likes and views otherwise. What a shame.

I made that PR solely for the upvotes and attention, and you stole them from me ;_;

Anyway I thought it was obvious that the speedmerge was because it was a meme PR and "speedmerges are okay if 4 maintainers approve it" wasn't actual policy.

**Comment by spookydonut** [comment]
> 
> 
> Never said that, but in my opinion, 2 maintainer approvals (1 reviewer, and one who actually merges the thing) make the speedmerge of simple PRs legitimate.
> 

this has been the defacto standard as long as I've known.

**Pull request merged**
