### PR TITLE
Wall tweaks

### PR DESCRIPTION
**Pull request by Spess-Rando**
Tweaks to the appearance of station walls.

Old metal walls:

New metal walls:

Old reinforced walls:

New reinforced walls:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Misleading title and I guarantee this will be bad

**Comment by Armhulen** [comment]
yeah mane we jus TWEAKIN it

**Comment by xxalpha** [comment]
Exactly what did you change, it doesn't look any different. Pictures please.

**Comment by WJohn** [comment]
Bolts were added at the corners of every variation of walls (horizontal, vertical etc), instead of JUST the corner variations. This means a stretch of horizontal wall will no longer be perfectly smooth, instead showing bolts as part of the texture. Originally, ONLY the corners of walls used to do this.

**Comment by Armhulen** [comment]
>I guarantee this will be bad

**Comment by MrStonedOne** [comment]
Current:
 
New:

**Comment by dannno** [comment]
that isn't super helpful, I think we need pics of them in game vs. current in game

**Comment by PKPenguin321** [comment]
actually pretty subtle and not awful. should have made that clearer in the OP

**Comment by Sligneris** [comment]
I was going to ask for a "do not merge tag" too, and yeah, it's a very much a WIP.

**Comment by Sligneris** [comment]
Old:
wall_old
New:
wall_new

**Comment by Armhulen** [comment]
i don't like it but it's not a massive change so it doesn't _really_ matter

**Comment by PKPenguin321** [comment]
kinda nasty actually, would prefer without

**Comment by Sligneris** [comment]
**Old:**
rwall_old

**New:**
rwall_new

**Should I?**
rwall_new

**Goon:**
rwall_goon

**Comment by PKPenguin321** [comment]
rwalls is fine actually but leave regular walls alone
DEFINITELY dont do that proposed thing or the goonwalls

**Comment by Sligneris** [comment]
Personally I believe the extra bolts are quite fine details actually. I'm contemplating making rwalls connect too.

Goonwalls are just there to look awful and hilarious in the context though.

**Comment by WJohn** [comment]
I don't think I would mind seeing Rwalls connect, just not in the goon style.

**Comment by RemieRichards** [comment]
Don't connect, and no extra bolts (essentially, 👎 this PR)

**Comment by xxalpha** [comment]
I don't really care as long as it's not the goon style you showed, that looks vomit inducing.

**Comment by Lexorion** [comment]
I dislike the extra bolts,the walls we have right now are okay

**Comment by Iamgoofball** [comment]
# wah wah i hate change :(

**Comment by PKPenguin321** [comment]
i'm not opposed to the rwall tweak but leave regular walls alone please

**Comment by Cheridan** [comment]
guess people dont like it

**Comment by Cheridan** [comment]
more walls to come apparently so i'll reopen

**Comment by optimumtact** [comment]
Please take pictures in game

**Comment by Robustin** [comment]
You might be onto something with the smoothing plasteel lines but no to all the rivets

**Pull request closed without merging**
