### PR TITLE
Makes surgery more stealthy

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Part of #44440 

Surgery now gives detailed description to the surgeon and anyone within one tile of distance, and more vague or ambiguous descriptions to the patient and anyone further away. This can lead to a surgeon being able to perform a brainwashing in place of a brain surgery with nobody being the wiser, or implanting a different organ than the one agreed on, and so on.

## Changelog
:cl:
add: Surgery steps are now shown in detail only to the surgeon and anyone standing adjacent to them; the patient and people watching from further away get a more vague/ambiguous description.
/:cl:

### CODE REVIEW

**Comment by Arathianen** [comment]
I love this very much.

Is the change where the patient can no longer see his computer kept?

Will this affect augmentic self surgery?

**Comment by XDTM** [comment]
Yeah, patients cannot see the console while lying down.

Wait, was self surgery re-added at some point? If so, i've missed it

**Comment by loserXD** [comment]
> 
> 
> Yeah, patients cannot see the console while lying down.
> 
> Wait, was self surgery re-added at some point? If so, i've missed it

you can do surgery on yourself if the limb you are doing it on is augmented

**Comment by Farquaar** [comment]
People in the observation room should be able to see what's going on.

**Comment by SkeletalElite** [comment]
> People in the observation room should be able to see what's going on.

Maybe add a sort of long range surgery computer so that the observer's can tell whats going on through that.

**Comment by XDTM** [comment]
That's doable, but i feel like it defeats the point of making surgery stealthy to observers - if people can check up on you from the observation room, you can no longer brainwash Johnny during his brain surgery, after all.

**Comment by AdamElTablawy** [comment]
Health HUD implants should let you see, rather.

**Comment by Farquaar** [comment]
> 
> 
> That's doable, but i feel like it defeats the point of making surgery stealthy to observers - if people can check up on you from the observation room, you can no longer brainwash Johnny during his brain surgery, after all.

I mean, that's the point of the observation room. It's a security measure, if a rarely used one.

**Comment by ExcessiveUseOfCobblestone** [comment]
You're still watching from afar. If a guy goes in for an arm replacement and you're observing you should realize the surgeon has successfully done a bunch of extra steps but still no arm.

It still serves it's purpose but now you actually have to observe the surgery to pick up the cues instead of it literally saying they're brainwashed or whatever.

**Comment by Farquaar** [comment]
> 
> 
> That's doable, but i feel like it defeats the point of making surgery stealthy to observers - if people can check up on you from the observation room, you can no longer brainwash Johnny during his brain surgery, after all.

I mean, that's the point of the observation room. It's a security measure, if a rarely used one.

> 
> 
> You're still watching from afar. If a guy goes in for an arm replacement and you're observing you should realize the surgeon has successfully done a bunch of extra steps but still no arm.
> 
> It still serves it's purpose but now you actually have to observe the surgery to pick up the cues instead of it literally saying they're brainwashed or whatever.

Fair enough. Though you should certainly be able to tell from a distance whether someone is doing arm surgery or brain surgery, even if you can't tell exactly what they are doing to that particular part of the body.

**Comment by XDTM** [comment]
Yeah, you do know which part the surgeon starts the surgery on.

Vagueness mostly means that you can't tell what kind of brain surgery is going on, what item is being planted/removed with stuff like organ manipulation or cavity implant (if the item is small or tiny), potentially letting you bait and switch, and other details like that.

**Comment by Farquaar** [comment]
I do like the ambiguity. Still, I don't fancy how CMOs won't be able to use the observation room to supervise shifty MDs mid-procedure anymore. Might as well remove the observation room at that point and just make extra space in the surgery room, since it's almost always better to breathe down their neck while they operate.

**Comment by XDTM** [comment]
Observation room is for the public, CMO can look over their shoulder and see evrything if they want to.

**Comment by Farquaar** [comment]
It was my understanding that only medical staff had access to the observation room. If that's not the case, then there isn't much to complain about.

**Comment by KetasDotepasto** [comment]
> I mean, that's the point of the observation room. It's a security measure, if a rarely used one.

I thought the point is to let med students observe the surgery, so that they can learn how to surgery.

**Pull request merged**
