### PR TITLE
Changes up the sprites for stasis beds to look more like operating tables.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

This changes the sprites for stasis beds to look closer to operating tables, kind of a fusion of the two in my opinion.
image
This also adjusts the directional sprites to at least flip when aimed left or right as well.

The damaged state now has a bit more life to it as well, gently flickering and sparking when broken.

The sprite maintains it's 3/4ths perspective, but now you get the feeling that it's  an actual bed for a patient as opposed to just a pod without it's covering.

Nothing against the old sprites, honestly, I'm partially curious to see the reactions to this mostly.

## Why It's Good For The Game

Seems like a clean resprite for these that I had floating around my "half finished projects that will get me doinked if I PR them" folder, so I thought I'd put the sprites to work.

## Changelog
:cl:
imageadd: The Stasis beds on station have been given a bold, moderné new design.
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
Looks great
Is that white angled bit supposed to be a headrest, though?

**Comment by ArcaneMusic** [comment]
Yup, headrest/built in cushion thing.

**Comment by msgerbs** [comment]
I like this. Nothing against this PR but it does seem to drive home the idea that surgical tables are just outdated and useless though.

**Comment by Winterous** [comment]
I mean I'll miss the cozy looking ones we have now, but these are good.

**Review by Twaticus — APPROVED** [review]

**Comment by Jared-Fogle** [comment]
alt click on stasis bed go beeeurrrrrrrr..................................bwoooooooooooooooooooommmmmm

**Pull request merged**
