### PR TITLE
restore removed individual logs and place them under LOG_VICTIM category

### PR DESCRIPTION
**Pull request by Couls**
## About The Pull Request
it turns out that admins use the removed information in #61179 for faster live in-round logging, I've restored that information under a LOG_VICTIM category that should not interfere with mind-reading and ling absorb text

## Changelog
:cl:
admin: individual logging now displays things that happened to the individual again
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
can you guys speedmerge this admins need their logging

**Comment by NamelessFairy** [comment]
> can you guys speedmerge this admins need their logging

Seconding this, would be ideal to have the logging issues fixed urgently

**Comment by BorisVcBorison** [comment]
please speedmerge this, logging is very important for admin duties

**Comment by optimumtact** [comment]
Speed merging wont' do anything because mso turned off the auto updater anyway.

Just bug the keyholders for a test merge, we can't help you.

**Comment by MrMelbert** [comment]
I think this PR puts **all** the victim logs in the `[SAY LOG]` tab of individual logs, even attack logs, strip logs, etc

**Comment by NamelessFairy** [comment]
> I think this PR puts **all** the victim logs in the `[SAY LOG]` tab of individual logs, even attack logs, strip logs, etc

I can confirm this, could you look into a fix @Couls

**Comment by Couls** [comment]
it should be putting them in the LOG_VICTIM tab

**Pull request merged**
