### PR TITLE
New "parry" ability for some swords.

### PR DESCRIPTION
**Pull request by paganiy**
## About The Pull Request
Adds a new "parry" ability to all energy swords, desword, energy and ordinary katana. Its essence lies in the fact that if the attack is successfully blocked, then the damage is inflicted:

- **if the attack was made with an item**: on the item in full amount of the weapon damage
-  **if the attack was made with bare hands (punch, shove, grab):** on the attacker's active hand in the amount of 50% of the weapon's damage.
- **if the attack was made with tacklers, body throw or if the attacker is just a mob**: on the attacker's head (in case of humans) in the amount of 70% of the weapon's damage.

Here's a preview of how it works:

https://github.com/tgstation/tgstation/assets/126676387/121dd99a-6028-4eaa-9d0f-061dc6b1f942
## Why It's Good For The Game
Due to recent updates, such as baton disarm, weapons with block capability, especially the esword and desword, have become quite mediocre for their price and the time you need to wait to accumulate reputation. This PR will slightly improve these weapons, giving it a slight advantage in melee combat and in combat against unarmed.
~~_nerf stun meta, buff RNG meta_~~
## Changelog
:cl:
balance: Esword, desword, energy katana and common katana now have a new ability "parry". If these weapons successfully block an attack, damage is partially inflicted on the attacker or their weapon.
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
I am not interested in power creep of any form.

**Comment by paganiy** [comment]
> I am not interested in power creep of any form.

eh, where were you when https://github.com/tgstation/tgstation/pull/83055#issue-2279182734 was merged

**Comment by ZephyrTFA** [comment]
> > I am not interested in power creep of any form.
> 
> eh, where were you when https://github.com/tgstation/tgstation/pull/83055#issue-2279182734 was merged 

that's the opposite of power creep and I approved it

**Comment by Xackii** [comment]
Delete old mechanics - merge.
Add new ones - close.

**Comment by paganiy** [comment]
> > > I am not interested in power creep of any form.
> > 
> > 
> > eh, where were you when [#83055 (comment)](https://github.com/tgstation/tgstation/pull/83055#issue-2279182734) was merged
> 
> that's the opposite of power creep and I approved it

what does "power creep" mean in your understanding? And what exactly is "power creep" with this PR?

**Comment by uaioy** [comment]
its like the parry idea that i wanted to give medieval pirates

**Comment by Xackii** [comment]
> its like the parry idea that i wanted to give medieval pirates

now you know that ZephyrTFA will close it automatically

**Comment by Sakamoto4ka** [comment]
unrobust department don't wanna stunshove nerf and tot buff

**Pull request closed without merging**
