### PR TITLE
Atmos gas miners

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: replaced the canisters in the atmos loop with gas miners
/:cl:

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by SyruseEln** [comment]
Don't gas miners generate infinite gas? Isn't gas on the station supposed to be finite? Aren't the canisters in the atmos gas chambers there for identification purposes? I'm struggling to see a reason for this change.

**Comment by MoreRobustThanYou** [comment]
@SyruseEln lore wise it uses bluespace bullshit to pull gas from a ~fart planet~ gas giant near the station

**Comment by Iamgoofball** [comment]
@SyruseEln Much cleaner than 3x3 tiles of insanely high pressure gas tbh

**Comment by Cyberboss** [comment]
Actually this does represent a rather significant balance change as smashing the glass on the storage tanks is no longer enough to get rid of the gas for the round

**Comment by MoreRobustThanYou** [comment]
@Cyberboss you can always just space the miners

**Comment by Iamgoofball** [comment]
@Cyberboss the time it takes for us to actually physically breathe up all the air mix on the station roundstart excluding the gas tanks and air cans is like 2-3 hours

**Comment by BeeSting12** [comment]
wheres plasma's gas miner?

**Comment by DoctoreMad** [comment]
Well, I see no problem with the changes noted so far. Maybe I am missing something?

**Comment by MoreRobustThanYou** [comment]
@BeeSting12 in the code, plasma is called "toxins"

**Comment by MoreRobustThanYou** [comment]
@SyruseEln also you can just put your mouse over the gas miner and it'll say the type

**Comment by ShizCalev** [comment]
What @SyruseEln said is correct, the canisters are just there for quick identification purposes, they're not even actually opened. The chambers are filled via their turf tiles.

https://github.com/tgstation/tgstation/blob/1e17bb7b837b1afdd088a88b6e2e1a92d188a1d2/code/game/turfs/simulated/floor/reinf_floor.dm#L77

**Comment by SyruseEln** [comment]
So this meas we can have an infinite plasma/CO2/N2O flood yes? Bad change.

**Comment by Anonmare** [comment]
Technically gas miners would mean there would be less gas overall since I presume we won't need the snowflake turf tiles anymore. 

I forget the actual amount of gas there is in the roundstart tanks but it;s something ridiculous like 3 million moles or something

**Comment by as334** [comment]
Not a huge fan. It's actually possible to drain the station supply of plasma or oxygen if you're running a fire or a big flood for a while, so making it unlimited seems kind of broken. Don't really see the advantage of the gas miners TBH.

**Comment by MoreRobustThanYou** [comment]
capture

**Comment by Poojawa** [comment]
This is really good for when space dust somehow RNGs its way to breaking the nitrogen/oxygen atmosia bunker and spacing the entire package 45 minutes in. Or being able to replenish supplies post meteors/high energy flux/etc.

Or a carp spotting a cockroach at just the right spot and shattering the glass. Or any number of not-player-intentional sabotage.

**Comment by deathride58** [comment]
Miners are designed for Planetstation and other planet-side maps. It'd make a lot more sense for miners to be placed on Lavaland rather than on the space station. As others have already said, replacing the station's finite gas chambers with miners would be a pretty big balance change.

As for carp being able to space the gas, a better solution would be to replace the reinforced glass with plasma glass. Meteors and space dust breaching gas chambers falls mostly on map design and player ability. Meteor shields exist, cargo is able to order extra gas canisters, atmos has holo airlocks, and most maps usually have their atmosia designed in such a way that raw oxygen is protected by other parts of the station. Atmos shouldn't be hugboxed to prevent player stupidity.

**Comment by SyruseEln** [comment]
deathride hit the nail on the head.

**Comment by Poojawa** [comment]
Holo airlocks are limited 3 per projector, and are only meant as a stopgap measure mid-repair. After repairs are done... well it sure would be great to replenish the distro.

Cargo can't order enough canisters to be a viable replacement and trying to move and link 30+ canisters into distro is a huge pain in the ass for the engineers involved. There's just no easy way to move more than two at a time anywhere.

Meteor shields are also not always available for purchase, depending on what station goal is randomly selected.

**Comment by as334** [comment]
@Poojawa Atmos can definitely replenish oxygen and such easily? Refilling the tanks is literally as easy as dumping them into waste, where they get filtered into the correct tanks without issue. Also atmos rarely ends up actually needing to replenish station air except in the event of a breach, in which case canisters or pumps are usually used anyways for speed.

**Comment by deathride58** [comment]
There's two atmos holoprojectors on most maps, bumping the total holo airlock count to 6. That's all you need to replace broken gas chamber windows, and it's more than enough to maintain temporary doors to shove extra gas canisters into breached chambers.

One single oxygen canister is more than enough to replenish the station's air supply in a pinch, and cargo can order them for 1500 credits a pop, which is essentially pocket change when cargo is fully staffed. Nitrogen is 2000 credits a pop, which is also pocket change. An investment of 17,500 credits for 5 O2 canisters and 5 N canisters is a pretty cheap investment for cargo during most rounds, and is more than enough to replenish the station's air supply without making fires spread easier.

Even without meteor shields, it's entirely possible to build a grille shield to prevent space dust, or construct a barrier of reinforced walls to shield atmos from lighter meteors. On boxstation, atmos is already partially shielded by the AI satellite and a space pod, which is more than sufficient enough to protect atmos from meteors and space dust.

**Comment by Poojawa** [comment]
tfw people who don't play Engineering comment on engineering tools. 

Atmosia is not just for plasma grief memes. Technically, the gas miner would be better off as its own thing, pumping x amount of a "raw" gas mix per tick, and being able to adjust which kinds it prioritizes to mine as a mixture through a console rather than 'this one magically generates 50L/s of N2O because of bluespace memes'. say out of 50L/s it mines mostly nitrogen, let's say 25L/s. then a bit of oxygen 10L/s, CO2/N2O, 5L/s each, plasma (because it's our meme gas) 5L/s. since we don't use/represent hydrogen, or any other gasses, the radio's are a bit weird.

@as334 Unless you tear out the floor of Cargo and use a combination of connectors, volume pumps, and manifolds into a scrubber line, then just constantly cycle canisters, there's no real way to refill the gas bunkers. Atmosia has a few canisters on hand, but that's just for people needing quick access to specialty gas without having to understand how the land of pipes work.

Once you attempt to re-air anything larger than say, escape with provided air pumps (which are almost always empty by default) or the few canisters tucked away, or even the emergency maintenance tanks (the ones with a manual valve attached) you're still having to decide which rooms you're going to vent to refill any other holes (like say, arrivals or security).

Planetary gas miners would literally just be a syphoning scrubber placed outside. Not really mining so much as just, y'know raw intake. Atmospheric mix -> Filtering system -> Nitrogen/Oxygen Gas mix -> Air mix.

Vorestation's Tether map has Atmosia basically completely replaced by a few holding tanks mapedited to insane amounts, no gas bunkers, and a few gas miners. It basically fails to re-air just about everything but small rooms and cordorned off hallways.

**Comment by deathride58** [comment]
Meteor shields. Meteor shields. Meteor shields. It's entirely possible to bust the containment fields out of secure storage to use them as ghetto meteor shields, and they're even able to be purchased regardless of station objectives. I'm personally surprised meteor shields haven't been reduced to a generic, non-station-objective-exclusive order yet, given how much of a necessity they are during longer rounds.

Again, holofans are a thing. They completely stop the flow of gas without restricting movement, allowing an atmos tech to simply patch up the floor, and then plop down the holofans to repair a chamber to a functional state without putting in too much effort. Walls can then be constructed on top of the holofans, returning the chamber to its original, unable-to-be-walked-into state.

This is also not about nerfing plasma floods. This is about keeping the station's air supply something valuable that takes a small amount of effort to repair. The station's air supply being breached is something that should have quite a bit of impact on the round, similar to the engine. The addition of holofans already buffed atmos repair capabilities quite a bit, since they make it insanely easy to add extra gas to the chambers. Exchanging the station's limited air supply with an unlimited air generator would only completely trivialize repairing it.

**Comment by Magikarpet** [comment]
just remove the surplus of gas in the chamber and use the miners roundstart to mine all of the gas the station will have 

You can look at /vg/ or any server running their code it's not like it's a huge balance issue 

The speed at which they mine gas isn't fast enough to make it an infinite volume when burning an oxygen and plasma miner up for a fire anyways

you also cant talk about keeping value to the station air tank when a random meteor hitting it or space dust hitting it instantly vents all of the gasses in o2/air/n2 rendering the station uninhabitable if a single breach happens which kinda defeats your point of keeping the gas as a valuable resource

Canisters also have a smaller volume than a tile, a full canister of o2 or n2 will reach 11 tiles before dissipating IIRC but don't use me as a factual source go test it yourself

**Comment by Poojawa** [comment]
Yah, cut it to a tenth of roundstart capacity, have the miners default to off on roundstart so people actually have to set up Atmosia. 

Enhance the consoles to work with multi-tool reconnections with the miners so they can be rebuilt if destroyed, same with sensors, injectors and the snowflake intake vent that pulls from the bunker. 

Atmosia would be wonderful from that point on.

**Comment by lordpidey** [comment]
<quote>One single oxygen canister is more than enough to replenish the station's air supply in a pinch</quote>
BULLSHIT.

Go hop on a local server, and make a 10x10 empty room in space, and then take a full oxygen canister, and dump it in the room.

There won't be enough O2 in the air to breathe,, let alone enough pressure to survive.

**Comment by kevinz000** [comment]
HOLD UP
HOLD UP
H O L D U P.
@MoreRobustThanYou Make a new subpath for each of them, /gas_miner/roundstart or whatever.
Set target moles/pressure/temperature for them.
DO. NOT. USE. THE. BASE. PATH.
I have not calculated how much the limits on the base ones go for pressure/moles and you can actually break atmos balance with it.

**Comment by kevinz000** [comment]
Oh yeah, also, please make the roundstart ones take lots of power. I was going to do that when I tried adding them to the map and didn't. Infinite gas should take power, atmospherics should be more reliant on power. Either make them use apc power, or cable node power, and make sure they have an on off switch, or even code a digital switch for powerlines that people can toggle.

**Comment by lordpidey** [comment]
This will likely conflict with #30391

**Comment by nicbn** [comment]
This is a bad idea. We can find a better solution than this.

**Comment by CPTANT** [comment]
There is no problem to solve, the pressurized tanks suit their purpose just fine. Having tanks smashed is just a hazard the crew has to react to.

Magical infinite gas is just lame.

**Comment by kevinz000** [comment]
https://github.com/tgstation/tgstation/pull/25433

**Comment by deathride58** [comment]
Unless canister volume was nerfed in the last three days, all that's needed to repressurize a room after a breach is a single canister of air or raw o2. If the room's too big (like boxstation's bar) then it'd take two canisters instead of one. Seriously, try venting all of the air in metastation's chemistry, and let off a single air or o2 canister. Then try venting all of the air in pubby's medbay, and try to do the same thing. With the chemistry example, the room ends up repressurized. With the medbay example, the pressure inside the room is too low to be inhabitable.

Atmos pipes are able to store gasses, and they have a surprisingly large volume per pipe. Vents draw directly from the pipes in a way similar to how APCs draw directly from SMES' around the station. Vents draw a minuscule amount of gas from rooms that are already at their target pressure. So long as there's no major breaches, and air alarms haven't been set to pressurize rooms over the roundstart default, five air canister's worth of gas is essentially five room's worth of repressurizations.

It's also entirely possible to shove a considerable chunk of the station's air supply into the atmos pipes roundstart, something that surprisingly rarely happens. By doing this, vents will continue to function for quite a while after atmos gets breached.

I am in full support of slow, power-consuming miners roundstart to replace the station's standard gas supply though, as it's a nice middleground between trivial atmos repair and keeping the option of breaching atmos' chambers a viable option for traitors.

**Comment by Poojawa** [comment]
The claim: One canister of air is all that's needed
The setup: Box Station Chemistry. https://gyazo.com/fd929b5d07b059d53fb50933a0042680
One canister of air, spawned. 
room depressurized via build-mode floor removal to space and 0kPa reported before being rebuilt.
Scrubbers and vent set to off. Breaches sealed with obvious wall constructions.

The result: https://i.gyazo.com/df4dd780903f031be4194cfa569fe929.png

@deathride58  You have absolutely no idea what you're on about. It filled it at best, to half way. And Box Chemistry is smaller than Meta's. 

Super-pressurizing Atmosia pipes does nothing except enable your air supply to be vented off into space in any room that still has an active APC and connected vent. It'd be nice to have the auto-shutoff for that, but we don't. So you bleed off your 4-5,000 kPa airmix into space for no gain at all.

**Comment by Magikarpet** [comment]
people hallucinating balance is batshit insane speculative nonsense, if you want an actual applied measure of how this works out check how /vg/ runs gas miners for applied data

**Comment by deathride58** [comment]
For reference, Lavaland is 36.8 kPa. All you need to survive there is an internals mask, as the amount of damage you take from low pressure there can simply be shrugged off. Pressure damage from low pressures is only deadly if it drops below 25 kPa. All you really need to survive is enough moles of oxygen to breathe.

That means that this is 100% inhabitable, despite what the air alarm says: https://i.imgur.com/myW0LSf.png

27 kPa is also 100% inhabitable: https://i.imgur.com/jqPxlfb.png

On top of that, during normal gameplay, air typically bleeds into other rooms from people opening airlocks. 27 kPa in a large room can easily grow to 35 kPa just from a handful of people walking in and out.

**Comment by Cyberboss** [comment]
I'm not a fan of just giving the miners out roundstart, tbh. If any other maintainer has an different opinion they can reopen this if they plan on merging it

**Pull request closed without merging**
