### PR TITLE
Hilbert's Hotel Bag of Holding is now a raw bluespace anomaly core with an accompanying inert bag.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Swaps out Hilbert's Hotel Bag of Holding with a raw bluespace anomaly core with a matching inert bag of holding.

Tweaks various pixel_x and pixel_y values to place items more aesthetically on the tables.

screenie

## Why It's Good For The Game

Hilbert's Hotel was out of comission during my space loot sweep. Now it's back, it doesn't get to bypass it untouched either.

We added raw anomaly cores as a gating mechanic for certain items for good reason. Hilbert's Hotel doesn't get to bypass this by injecting a bonus activated anomaly core item into the shift. 

The raw anomaly core can be activated like any other anomaly core and counts towards the hard cap of anomaly core items in the round. It can then be used to create any of a Reactive Teleport Armour, Wormhole Projector, Phazon or Bag of Holding.

## Changelog
:cl:
tweak: Hilbert's Hotel Bag of Holding has been replaced with a raw bluespace anomaly core and inert bag of holding. For flavour.
/:cl:

### CODE REVIEW

**Comment by MimicFaux** [comment]
Why not make it an activated core? There is still the middling effort of finding/getting in, and the research and materials to print the inert bag is still a factor. It's a still a nerf, but is a step up from simply ordering raw cores from cargo.

**Comment by Timberpoes** [comment]
> 
> 
> Why not make it an activated core? There is still the middling effort of finding/getting in, and the research and materials to print the inert bag is still a factor. It's a still a nerf, but is a step up from simply ordering raw cores from cargo.

Because if I make it an activated core, it either bypasses the anomaly core cap (which I said in the body of my PR I do not want to do) or it meta-infos the station that Hilbert's has spawned when someone tries to activate a bluespace anomaly core and finds out that it requires the equivalent of +1 core count to the required bomb.

Because the anomaly core cap is a constant, I can't just increase it by 1. And I also do not **want** to increase it by 1. There's a reason we implemented anomaly cores and capped their max activated counts per round.

**Comment by EdgeLordExe** [comment]
make it a coreless boh and a raw core instead of just raw core, that way hilber hotel stays a good ruin while at the same time not breaking the anomaly core item balance

**Comment by Timberpoes** [comment]
> 
> 
> make it a coreless boh and a raw core instead of just raw core, that way hilber hotel stays a good ruin while at the same time not breaking the anomaly core item balance

Generally pointless, since the department that'll be activating your core is also the department that can print you a BoH but sure, if it satisfies as a compromise.

**Comment by itseasytosee** [comment]
flavor

**Comment by Timberpoes** [comment]
`... and inert bag of holding. For flavour.`

**Comment by Winterous** [comment]
Would an ACTIVE bag of holding really contribute towards hitting the core cap? I thought it only incremented when an active core was created.
Isn't the active BOH just its own item, with no anomaly core attached or connected to it, and therefore wouldn't contribute?
If that's the case, what's the issue with the active BOH loot?

**Comment by Livrah** [comment]
Noone ever will activate raw cores from the space, why is this a thing.

**Comment by Timberpoes** [comment]
> 
> 
> Would an ACTIVE bag of holding really contribute towards hitting the core cap? I thought it only incremented when an active core was created.
> Isn't the active BOH just its own item, with no anomaly core attached or connected to it, and therefore wouldn't contribute?
> If that's the case, what's the issue with the active BOH loot?

No, it won't contribute to the core cap. That is the issue. The reason raw anomaly cores and their activation was introduced was to set a hard cap on the number of certain items that could exist in a round. Space loot is not going to bypass this cap.

**Comment by Timberpoes** [comment]
> 
> 
> Noone ever will activate raw cores from the space, why is this a thing.

Because we introduced systems to hard cap the numbers of specific items that could be created in a round, that is why this is a thing.

**Comment by Tlaltecuhtli** [comment]
why not full removal? we need more quality in ruins and keeping a giga room filled with trash isnt sign of quality

**Comment by Timberpoes** [comment]
I'm not removing Hilbert's again. The original PR I did only removed it because it was a runtime factory. If I wanted it removed for being low quality, I'd have stated such.

There is one more follow up PR addressing the free and relatively low-risk warp whistle effect and some other things, though.

**Comment by interestingusernam3** [comment]
>Because we introduced systems to hard cap the numbers of specific items that could be created in a round, that is why this is a thing.

Yes, that reason was to prevent mass production of BoH's and distributing them to literally everyone who asked for one in favor of creating a system where BoHs are scarce as hell and therefore can be a source of legitimate and interesting conflict between crew and do not entirelly break item size-based balancing, as well as preventing solving every single fucking problem ever with BoHbombs IIRC.

Unless there is also a code reason like assuming at most a certain amount of BoHs are created per round allowing for the implementation of something that makes the game faster.

It's not like anyone who isn't exceedingly stupid will purposely spend an entire round trying to obtain a BoH from space just to MAYBE put a massive pile of junk in it and haul it to escape/BoHbomb some random place that won't be of use to anyone anymore anyways because the round is ending already.






If there's some reason why the BoH absolutely cannot be kept in, I suggest maybe replacing the core and bag with a mining bag of holding so it at least fits the other items in the room instead of being essentially two pieces of slightly out of place trash.

**Pull request merged**
