### PR TITLE
Disembowelment now only works if you are dead/in critical 

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Disembowelment now only works if a mob is either dead or in critical condition, as opposed to the complete RNG it used to be (RNG now limited to those two health states). 

## Why It's Good For The Game

Its not fair or fun to have your organs removed in one hit by a rando with an esword. Disembowelment results in you dying a short time later, with no chance of defibrillation. 

## Changelog
:cl: wesoda25
balance: disembowelment no longer works on mobs that aren't dead or in critical condition
/:cl:

also thanks to imsxz and 4dplanner with helping me on this

### CODE REVIEW

**Comment by wesoda25** [comment]
Also, someone had suggested it only work on dead mobs, which I disagree with. Namely, sometimes as certain roles you need to hit someone until organ disembowelment to ensure they are dead (see nuke op round where everyone has regen coma). Having it work in crit preserves this use, and makes it less bullshit by not working randomly.

**Comment by Time-Green** [comment]
Finally. Now I don’t have to worry about that guy with a papercut I accidently chainsawed once. Too many times I’ve removed someones organs like that

**Comment by Magikarpet** [comment]
One time while I was gathering organs for bounties I got disarmed by a monkey and the first hit it did on me with the circular saw instantly disemboweled me and killed me while i was at 100%

Instakills with any normal sized sharp weapon and up weapon on heavily armored/full health targets is horrid and I don't think anyone will miss this

**Comment by kingoftheautism** [comment]
Good, now I don't need to be worried about getting yeeted by blood drunk miner with one single hit

**Comment by anconfuzedrock** [comment]
haha, waiting for someone else to fix something always works

**Comment by KomradeSpectre** [comment]
wtf I love Wesoda PRs now?

Don't know if you do this, but disemboweling a person also works if you strike any other body part. I had my organs spilled by a guy who hit my arm in a round yesterday. Don't know if the one change in bodyparts.dm covers that.

**Comment by ATH1909** [comment]
I was expecting a bunch of people to scream "i ded", but was pleasantly surprised to learn that everyone hates getting killed by random disembowlments (when they're not already in crit/dead).

**Comment by nicbn** [comment]
I think this should look for limb damage instead of crit. That way if your chest got the red blinking bruisings but you're somehow up and alive it will still work.

**Comment by wesoda25** [comment]
Sorry, what?

**Comment by subject217** [comment]
I think what Nicbn means is that disembowlment would only happen when the chest "limb" is heavily damaged.

**Comment by wesoda25** [comment]
> I think what Nicbn means is that disembowlment would only happen when the chest "limb" is heavily damaged.

I considered that but decided against it because the only point of damage I'd want disemboweling to have a chance of happening would be the point where the hit from the esword will crit you anyways so...

**Review by 81Denton — APPROVED** [review]

**Comment by Daxxed** [comment]
Rng is bad pls remove all forms of rng, I want to choose the loot when I kill a megafauna and make disarms always push 100% of the time...
@kingoftheautism 
Atleast that kept the fight a bit exciting, once you learn to dodge his PKA it becomes impossible to die unless you get hit by the lucky disembowel.

**Comment by Timonkeyn** [comment]
Wait so, now it's completely useless to target the chest with sharp items?

**Comment by Magikarpet** [comment]
Hitting people with high force items on the chest still causes a lot of dizzyness and fucks up their controls

unless that was changed

**Comment by ExcessiveUseOfCobblestone** [comment]
That's not disembowelment ;)

**Pull request merged**
