### PR TITLE
Ratvar will now convert lattices and catwalks to clockwork versions

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
add: Ratvar will now convert lattices and catwalks to clockwork versions.
/:cl:

ha!

### CODE REVIEW

**Comment by WJohn** [comment]
now you've got clockwork catwalks to do!

but good work, genuinely impressive, what with the fairly crazy amount of connecting points lattices have.

**Comment by francinum** [comment]
Hey, that's pretty good.

**Comment by Supermichael777** [comment]
its a bit dark but good

**Comment by Kromgar** [comment]
Add the kind of conversion ratvar does to nar'sie so the entire station turns blood cult

**Pull request merged**
