### PR TITLE
Gang Update: Implants Edition

### PR DESCRIPTION
**Pull request by Ikarrus**
### Loyalty & Gang Implants
- Security can once again deconvert gangsters with loyalty implants
  - A message is shown if the deconversion destroys the implant in the process
- Added an Implant Breaker item to the gangtool as a purchasable item for 10 influence each
  - They are a one-use item that destroys all implants in the target, including loyalty implants
  - They will also attempt to recruit the target before destroying itself
  - Can recruit enemy gangsters
  - As this is an implanter it requires the target to remain still for a few seconds to administer it
- Implanters no longer work if the target is wearing headgear. Remove them first
### Gang Leaders
- Multiple gang leaders are spawned at round start, the number which depends on server population
  - 1 to 3 leaders per gang
  - Only one boss per gang, the rest are lieutenants
- Gangsters can no longer be promoted mid-game.
### Minor Changes
- Added help text whenever you buy certain items from the gangtool
- Spare gangtools now cost 30 influence for everyone
  - They no longer give you a free pen
- Increases domination limit back to 3
- Purchased outfits are automatically equipped in your hand, if possible
- Gang boss has a 3 minute window at round start to select an outfit style. If he doesn't select one, the his lieutenants may pick one. No gang outfits can be created without a style picked first.
  - This is just to give the gang boss the first opportunity to pick an outfit style for his gang
- You can now see how many outfits your gangtool has in stock
- Outfits are no longer used up if you cancel the style selection prompt
- Loyalty implant destruction message has been moved to its Destroy()

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Really don't think headgear should block implants, but aside from that, :+1:

**Comment by Lumipharon** [comment]
same opinion on the headgear, although I understand where you're coming from, in terms of stun -> implant HoS/cap ggnore.
Why have you made it only the boss can recall?

The rest looks good.

**Comment by Ikarrus** [comment]
I wanted to put some added risk into losing the gang boss. As well, it's more likely the gang boss would be out of commission late round, so it might help rounds from being dragged too long by motivating the gangsters to do something other than sit back and spam recall.

**Comment by Alek2ander** [comment]
:-1: on lieutenants being preselected. Promoting people midround is pretty nifty (boss won't choose chucklefucks for promotion, gang members have incentive not to be chucklefucks to have a chance of promotion).

**Comment by Ikarrus** [comment]
It's to spread the risk of the gang boss from ruining the round by either being too meek or doing something stupid and getting caught early in the round. 

It's basically there to help prevent shit rounds.

**Comment by Dorsisdwarf** [comment]
Can you increase the influence cost on the "Make security your bitch" implant to a little more than, what, a baseball bat?

**Comment by Alek2ander** [comment]
>That assumes the gang boss isn't a chucklefuck to start with.

Add a way to challenge and depose a gang boss then. It's a gang after all.

**Comment by PKPenguin321** [comment]
:-1: on not allowing gang bosses to choose who their lieutenants should be. I had a round as a (successful) gang boss, and I don't think I would have had that success if I couldn't chose my lieutenants.

>Only the gang boss can recall the shuttle (I was a bit iffy on this so it might change)

Horrible. Again, coming from my experience, I would command a lieutenant (the least active one) to go to some isolated place and recall. That way we could give the least active lieutenant something to do while also not getting hurt by blowing our location and not being able to use our gangtools.

:-1: for these things, and I'm a little iffy about loyalty implants being able to deconvert again, but that might be okay.

**Comment by Steelpoint** [comment]
10 influence for loyalty implant breakers might be on the cheap side, but that's in comparison to all the other equipment gangsters will be buying so it might not be too bad.

**Comment by AlexanderUlanH** [comment]
:-1: on removing promotions.  That was my favorite part of the gamemode.
Chucklefuck bosses are a problem, but I think they'll become less of a problem as the mode gets older, and they become even less of a problem once you've promoted lieutenants.

**Comment by Ikarrus** [comment]
IF they promote anyone, which a surprising amount of people don't

and we're always going to be getting new players which will make the same mistakes. Which is what most of them are. Veteran players usually just intentionally fuck over their gang.

**Comment by Fox-McCloud** [comment]
I'll stress again that I don't think implants should be blocked by headgear. I understand where this is going, to a degree, but it's also going to make using regular implants on yourself more of a pain, and it's also going to make using explosive implants/microbombs a huge pain as well. Would you please consider removing it, @Ikarrus?

**Comment by Ikarrus** [comment]
Imo those are minor inconveniences at most. I think they're worth putting up with just to dampen the stun+implant ggnore as someone mentioned earlier, which has the potential to be really strong.

**Comment by Ikarrus** [comment]
Also explosive implants can only be used by nuke ops now.

**Comment by PKPenguin321** [comment]
Going to restate: :-1: for not allowing us to promote our own lieutenants. It's a good feature of gang that should not be removed.

**Comment by Lumipharon** [comment]
Promoting lieutenants (for better or worse) means if the bosses have half a brain, they'll rush to convert and promote known robust people, which gives them a huge advantage, compared to random selected, possible chucklefucks.

Whether that's good or not is another question.

**Comment by PKPenguin321** [comment]
it's good

**Comment by ExcessiveUseOfCobblestone** [comment]
:-1: to not being able to choose your own gang lieutenants. Similar to Rev [Gang's undeveloped sibling], The game's pinnacle point is not killing the <important units of the gamemode>, it's the Conversion-Rushing and the Win/Lose risk that comes with it. Being stupid with your conversion process just makes it easy for the other gang to snowball you, which I thought was the whole point of the game [to kick the other gang's butt in FAST PACED FUN] rather than a boring, unfun, hour long version of a Sensitive Freeze-tag [with lethals] + Capture The Points Hybrid.

The "it helps new players" argument doesn't validate it either, as New players can get the wonderful position of the randomly-chosen lieutenant, which ruins the game even moreso because now the round is drawn out than a round where a gang leader simply gets snowballed out of the game and GG'd.

**Comment by Ikarrus** [comment]
A single new player antag carries a greater risk of producing a bad round than having a small team of them.

That said, if the results of this are not satisfactory, I'll likely revert it. But I won't say no until I see it.

**Comment by PKPenguin321** [comment]
i'm disappointed tbh

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't mind about the round being ruined in a quick fashion because people haven't invested anything, My issue lies with the gangleader having bad teammates [because he cannot select them] who die instantly so now it's a long drawn out round for no reason except to have people whining in deadchat.

Is there a thread for this for feedback post-merge?

**Comment by Ikarrus** [comment]
I'm reading all your feedback right now.

**Pull request merged**
