### PR TITLE
Gives Renault a walk animation

### PR DESCRIPTION
**Pull request by ArcaneDefence**
## About The Pull Request
Nabski made this sprite a good ways back and didn't want to make a pr himself but I offered to PR it for him and only got the file recently
Thanks for making this whimsical sprite man

## Why It's Good For The Game
It's adorable
2-Scurry

## Changelog
:cl: Nabski
imageadd: Renault has a dopey walk animation now, god bless.
/:cl:

### CODE REVIEW

**Comment by Nabski89** [comment]
I was going to do Ian but he has like 20 different sprites depending on form and what he is wearing.

**Comment by Loafin34** [comment]
Make a throwing animation where he becomes a torpedo, that'd be great!

**Comment by ArcaneMusic** [comment]
Neat!

**Review by ZephyrTFA — APPROVED** [review]
adorable

**Pull request merged**
