### PR TITLE
Fixes the most annoying thing about admin helping.

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Ticket #3: ColeArkenach/(Ashton Ulery) (?) (PP) (VV) (SM) (FLW) (TP) (LOGS) (SMITE) (REJT) (IC) (CLOSE) (RSLVE): I keep getting the message "Your previous action was ignored because you've done too many in a minute." without doing anything. 

ADMIN LOG: MrStonedOne/(Curtis Picard) has started replying to ColeArkenach's admin help.

Error: Admin-PM: Client not found.

**Comment by MrStonedOne** [comment]
Why the fuck haven't i fixed this before.

**Comment by bgobandit** [comment]
but the most annoying thing about adminhelping is the players

**Comment by Cyberboss** [comment]
# THIS LINE IS  FUCKING CURSED

**Pull request merged**
