### PR TITLE
Updates the sprite of the bulldog shotgun and fixes some related code

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Changes the bulldog's sprite to something extremely similar in looks, just not as old as the gun's code itself.
Fixes a few random bits of code around the bulldog that were broken or could be slightly improved.

image

## Why It's Good For The Game

I haven't checked but I'm fairly certain that the bulldog's sprite is as old as the bulldog itself is, just like the rocket launcher's sprite was. It could use a little freshening up after a few years I think.
## Changelog
:cl:
fix: Fixes bulldog shotgun unique mag display not working on the sprite
image: resprites the bulldog shotgun along with inhands and new worn sprites
code: cleans up a little of the code surrounding the bulldog
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
It looks like shit.

**Comment by zoomachina** [comment]
The shotgun itself looks really bad & the mags look like LED lights

**Review by Wallemations — CHANGES_REQUESTED** [review]
Love the base sprite, but those mags are WAY too bright. Makes them look like it's a laser gun or something.

**Comment by SmArtKar** [comment]
shading looks kind of blurry, and the shape doesn't make a lot of sense from a gun perspective, thats not how bullpups work. Honestly, current sprite is more than fine.

**Comment by Paxilmaniac** [comment]
> shading looks kind of blurry, and the shape doesn't make a lot of sense from a gun perspective, thats not how bullpups work. Honestly, current sprite is more than fine.

lets not talk about "how a gun would work" like that without considering the old bulldog
image

**Comment by Paxilmaniac** [comment]
image
by request the magazine colors are now darker

**Comment by Blacklist897** [comment]
I dont understand how its ment to work but its miles better then the cursed duel drum mag pancor jackhammer

**Comment by arnociiroc** [comment]
> I dont understand how its ment to work but its miles better then the cursed duel drum mag pancor jackhammer

the ballsack bulldog was so peak though

**Comment by YuliceTheDruid** [comment]
Gotta say personally I'm a fan of the older sprite; just 'cause something is old doesn't necessarily mean it needs to be updated. DEFINITELY not a fan of the exposed barrel on such a short weapon, along with the free-floating foregrip that doesn't really stabilize anything.

**Comment by necromanceranne** [comment]
I'm just glad you can tell there are two mags in it. I hacked that shit on and gave no fucks because the sprite itself was old as shit and i wasn't gonna fix it.

**Comment by Blacklist897** [comment]
how the fuck would two drums that you can switch between even work???
I know you can have two tubes but ????

**Comment by necromanceranne** [comment]
Really fast hands.

**Comment by Exester509** [comment]
> how the fuck would two drums that you can switch between even work??? I know you can have two tubes but ????

Springs, mechanical arms, and a bit of BlueSpace(tm) to keep it all together.

Also a shotgun with an exposed barrel isn't that big of a deal, though it does look a bit weird without any muzzle at all.

**Comment by Wallemations** [comment]
I didn't even notice the exposed barrel, yea that looks odd, specifically with the grip on it too it makes it look like the grip is floating

**Comment by Paxilmaniac** [comment]
also by request the front end has been slightly redone 
image

**Review by Wallemations — APPROVED** [review]
Better with the fixes

**Comment by necromanceranne** [comment]
Could you make sure the back sprite is also mirrored in the belt_mirror.dmi, I'm pretty sure it can fit into suit storage 🥺

**Comment by Paxilmaniac** [comment]
> Could you make sure the back sprite is also mirrored in the belt_mirror.dmi, I'm pretty sure it can fit into suit storage 🥺

the screenshots are of it in suit storage, seems to be working fine

**Comment by Paxilmaniac** [comment]
> > Could you make sure the back sprite is also mirrored in the belt_mirror.dmi, I'm pretty sure it can fit into suit storage 🥺
> 
> the screenshots are of it in suit storage, seems to be working fine

actually what was i talking about here this is entirely wrong
they still work fine in suit storage but the screenshot contains zero images of it

**Comment by necromanceranne** [comment]
our suitstorage uses a separate dmi for suit storage overlays. Go check out belt_mirror.dmi and see what I mean (it's a deceptive name as it actually also handles mirrored back sprites)

**Comment by Paxilmaniac** [comment]
> our suitstorage uses a separate dmi for suit storage overlays. Go check out belt_mirror.dmi and see what I mean (it's a deceptive name as it actually also handles mirrored back sprites)

I'm aware of what belt mirror does, however setting the worn icon of something makes it not care one bit and just use the worn icon. It works completely fine like I said.

**Pull request merged**
