### PR TITLE
Resprites the payscanner

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
resprites the payscanner

paystand_new

## Why It's Good For The Game
It helps keeps the 3/4 perspective rule, since the current sprite is at an angle

## Changelog

:cl:
imageadd: new payscanner
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
The original sprite wasn't doing that shine thing, it was slowly scanning constantly, which in itself brings up a few problems.
Generally speaking, the original sprite was pretty much a copy of the book scanner. If you plan on keeping the shape, I don't see why you can't just take the new book scanner and change it to be unique to this machine instead. Perhaps a different color for the scanning area would work?

**Comment by etherware-novice** [comment]
i was hoping i could make an original sprite..

**Comment by ArcaneMusic** [comment]
I would maybe make a state with no shimmer on it for when it's not in use, and then use you're current sprite on a `flick()` proc that would go off when the card is being scanned. Otherwise it makes it pretty busy, even though the animation looks great don't get me wrong.

**Comment by etherware-novice** [comment]
ty, and ill probably just make the animation a constant speed

**Comment by Wallemations** [comment]
If you don't want to do the `flick()` then at least space out the shimmers by making the non-shining part have a longer delay.
Also, I'd recommend you make the scanning screen 1 pixel taller.

**Comment by etherware-novice** [comment]
@Imaginos16 please re review rhis?

**Review by Twaticus — CHANGES_REQUESTED** [review]
shouldnt have sat for this long, apologies.
feels very thin at the bottom like it'll topple over at any second, maybe we can add some decorative cabinets or something underneath? just something to make it a little thicker

**Comment by etherware-novice** [comment]
hhow

**Comment by etherware-novice** [comment]
it doesnt follow 3/4 rule tho!

**Pull request closed without merging**
