### PR TITLE
Removes revolver speed loading delay

### PR DESCRIPTION
**Pull request by Iamgoofball**
Desucake said to do this.

### CODE REVIEW

**Comment by Armhulen** [comment]
this, and if not atleast a reduction

**Comment by TehZombehz** [comment]
I'm expressing my opinion as a player.

**Comment by PKPenguin321** [comment]
i say keep it but make the do_after 10 instead of 30

**Comment by Desucake** [comment]
I would understand if you had to load a bullet one by one, but it seems redundant to do if you are using a speed loader.

**Comment by KorPhaeron** [comment]
I dont know why people find this delay offensive when every other station gun requires you to run back to another room and wait for more ammo

**Comment by Desucake** [comment]
Well, if I remember, this was only added cause the detective can become an antag now and if I remember, it was just pushed into the job cause it "seemed like the best way to equalize it." The weapon needs to have ammo made from cargo and doesn't have the ability to be reloaded via charger, which there are more locations to reload at.

**Comment by AdamElTablawy** [comment]
i mean bullet weapons have limited ammunition but the delay is just sort of, you know, dumb, since it really didn't contribute anything at all since it's rare you'll reload your weapon in the middle of combat long enough for it to matter and it's not like traitor detectives won't have sixty other weapons with them

**Comment by Supermichael777** [comment]
"Hey warden can I get a tazer? The AI gets mad when I shoot people."

**Comment by Dorsisdwarf** [comment]
Thank hell

**Comment by xxalpha** [comment]
Smart to do this when the person who made this change isn't around.

**Comment by Lumipharon** [comment]
This was always a retarded change.
:+1:

**Comment by KorPhaeron** [comment]
Fine you filthy powergamers

**Comment by ChangelingRain** [comment]
abusing [s] to hide prs from the players is easily grounds for pr closure

**Comment by Lumipharon** [comment]
what does [s] do?

**Comment by PKPenguin321** [comment]
makes the "XYZ has been opened/closed by CoderMcCoder" messages on the server not appear

**Comment by Lumipharon** [comment]
Wew, sneaky shit.

**Comment by xxalpha** [comment]
Joan, separation between server and code is absolute.

**Comment by Dorsisdwarf** [comment]
I will not be listening to any more portitudes and will no longer be subscribed to this PR

**Pull request closed without merging**
