### PR TITLE
Lipstick re-sprite

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

Resprites the lipstick!

Lipstick comparison shot

Screenshot 2021-11-28 193157

## Why It's Good For The Game

The lipsticks were overdue for a resprite cause, well, they didn't really look like lipsticks. This re-sprite aims to improve that.

## Changelog

:cl:
imageadd: Resprited the lipsticks
/:cl:

### CODE REVIEW

**Comment by FernandoJ8** [comment]
meant to make it a draft...

**Comment by Imaginos16** [comment]
I got you!

**Comment by FernandoJ8** [comment]
> I got you!

Thank you.

**Comment by Imaginos16** [comment]
There, your PR is now drafted. Good luck!

**Comment by FernandoJ8** [comment]
Alright, I think I'm happy enough with it now.

**Pull request merged**
