### PR TITLE
Removed a janky fish bounty and introduced exporting fish thru cargo.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
The fish bounty for specific kind of fish has been removed for being a bit janky and relying on RNG way too much. The other two remain, and have had their payout buffed a little to compensate.

To make it make it better, a fish export has been added. Each and every fish can be sold to cargo, with a selling price determined by their size and weight, meaning bigger fish sell for more. A fish of default size and weight generally sells for around 130, rarely goes above 600 for most fish, yet a few can sell for 1k, and it can **theorically** go all the way up to ~11k if you were to reach max size and weight for the biggest fish in the game.

This PR also reduces the weight of the jumpercable a bit for balance reasons. It's a big, self-reproducing fish that requires no care whatsoever so it's quite the cash cow, only offset by its rarity (EMAG or blackmarket RNG). Conversely, I made the bone fish evolution a bit easier (still a useless-ish braggard niche tbh).

## Why It's Good For The Game
The aforementioned fish bounty was janky, complex, relied on RNG too much and the info on it didn't really fit in the bounty console. It's better gone tbh. My fault for adding it in the first place.

As for the fish export, I want something simple, that doesn't require the fish to be alive rather than dead, with a low payout per fish on average, to complete the addition of "bomb fishing" from the other PR, ergo dropping maxcaps in the ocean for shit and giggles, but that can also have the potential to generate a decent income by cultivating big fish.

## Changelog

:cl:
del: Removed a janky fish bounty
add: introduced exporting fish through cargo.
balance: reduced the average weight of the jumpercable. Conversely, eased up the requirements for the bone fish evolution.
/:cl:

### CODE REVIEW

**Comment by Dawnseer** [comment]
Does the fish have to be alive for the export?

**Comment by Ghommie** [comment]
> Does the fish have to be alive for the export?

No.

**Comment by Ghommie** [comment]
> > Does the fish have to be alive for the export?
> 
> No. This is supposed to be an export that you can do in large quantities, so that'd be a pita. Also I need to rework stasis bags a little.

**Comment by Time-Green** [comment]
can't wait for the fish economy to put the station economy into shambles

**Pull request merged**
