### PR TITLE
Adds a Felinid laugh

### PR DESCRIPTION
**Pull request by Rohesie**
## About The Pull Request

Ports a custom laugh from Citadel to celebrate the felinid official addition into the game. 

## Why It's Good For The Game

More content! Not only moths have their own custom sounds!
Plus I had pledged to make this PR if the vote passed: <https://discordapp.com/channels/326822144233439242/326831214667235328/645948325606064138>

## Changelog
:cl:
soundadd: Very reasonable Felinid laugh added. Not obnoxious nor cursed at all.
/:cl:

What if the maintainers merged this...
Haha just kidding... Unless..?

### CODE REVIEW

**Comment by TheVekter** [comment]
>Ports from Citadel

**_No._**

**Comment by Kraseo** [comment]
humies mad (x24)

**Comment by pireamaineach** [comment]
Too feminine, doesn't account for catmen.

**Comment by Rohesie** [comment]
Agreed. If you get me a male nyahaha .ogg I'll add it.

**Comment by pireamaineach** [comment]
Wait yes it does

**Comment by pireamaineach** [comment]
Just isn't nya horseshit.


Why don't you record it yourself. OH WAIT! Cringe momentum

**Comment by actioninja** [comment]
please save me from this hell

**Comment by pireamaineach** [comment]
I concur.

**Comment by Rowelll** [comment]
where are sounds

**Comment by Rohesie** [comment]
Sounds here: <https://discordapp.com/channels/326822144233439242/326831214667235328/645947631587295232>

**Comment by KomradeSpectre** [comment]
We already have two laugh variants that cover all our use cases, snowflaking in more isn't a good idea.

**Comment by Rohesie** [comment]
> We already have two laugh variants that cover all our use cases, snowflaking in more for specific races isn't a good idea.

Try laughing as any species other than human.

**Comment by KomradeSpectre** [comment]
Yes, it gives a generic laugh. That's the point.

**Comment by Rohesie** [comment]
> Yes, it gives a generic laugh. That's the point.

It doesn't, it gives no sound. Only humans get a laugh sound, no other species does.

**Comment by KomradeSpectre** [comment]
Okay, and the patrician's choice isn't to generalize that but instead bloat?

**Comment by Dawson1917** [comment]
i said it was going to get worse

**Comment by pireamaineach** [comment]
You say that like we didn't believe you.

**Comment by HomocidlePancakes** [comment]
Go back to your swamp.

**Comment by DaedWren** [comment]
Hey I voice acted this, thanks for tryina put me in again!

**Comment by 81Denton** [comment]
What if I closed this...
Haha just kidding... Unless..?
Nah just kidding
Or am I...?

**Comment by optimumtact** [comment]
species change require approval and this is not getting it

**Comment by Keekenox** [comment]
ORANGE MAN ENACTING OPPRESSION AGAINST INNOCENT CATGIRLS

**Comment by Stealthkibblers** [comment]
orange man bad

**Pull request closed without merging**
