### PR TITLE
Adds a new guideline about gameplay and roleplay to the codebase.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Even games like Final Fantasy with years upon years of lore have to draw the line at some point.

As a case study, let's look at Doom or Death spells in Final Fantasy.

The descriptions for them often imply you can kill literally anything with these spells, but this is not the case, despite the lore stating it.

Imagine how easy those games would be if you could just cast Death or Doom on every boss. The lore says you should be able to. Some of the bosses are just guys with extra ranks in the military or something, not all of them are super dimensional beings and gods and stuff. But you still can't cast death or doom on them.

### CODE REVIEW

**Comment by evsey9** [comment]
first good pr that goof made

**Comment by Bawhoppen** [comment]
gameplay is worthless without lore or atleast flavor to back it up however

**Comment by Iamgoofball** [comment]
can you provide proof of your statement?

**Comment by evsey9** [comment]
baw
this is a lowrp server

**Comment by Bawhoppen** [comment]
@evsey9 just because you live in squalor, doesn't mean the rest of us do

**Comment by Iamgoofball** [comment]
This isn't the server, this is the /tg/station codebase. Please delete your comments and refrain from going off topic in this PR.

**Comment by loqoman** [comment]
Wait, this wasn't always the case?

**Comment by Qustinnus** [comment]
baw if you actually think lore goes infront of gameplay then you don't know how game design works. Usually it's feature, then lore. unless you're working with a predefined story or lore that has to stay the same. SS13 is open as fuck so that's not the case. gameplay >>>>>> lore.

**Comment by Bawhoppen** [comment]
Why does everyone live in the world of black and whites? There's this thing called "balance" that exists in life, it's something that you all should try.

**Comment by Iamgoofball** [comment]
Did you read the OP, baw?

**Comment by Bawhoppen** [comment]
Yes your actual statement in the code itself was not that unreasonable and did include a balance to it

**Comment by FantasticFwoosh** [comment]
My lore is that i am a ultimate badass who can shoot lasers out of my eyes and i have green skin, hence for lore reasons give my character wizard laser eye abilities permanently without a second though about how i might use it to validhunt or counter/endanger other people.

> (Exaggerated) point and case

**Comment by XDTM** [comment]
It's not all lore nor it's all gameplay; to make an example, you wouldn't give security the ability to make their own holy water during cult because it makes no sense lorewise for them to be able to do that, even if it might make sense gameplaywise.

**Comment by Iamgoofball** [comment]
If cult was horribly broken and the fix was to give Security easier access to holy water and this would fix every problem, we should do it.

**Comment by FantasticFwoosh** [comment]
Usually settled by the lore & gameplay expectations of interdepartmental co-operation.

**Comment by kevinz000** [comment]
Lmao go away goof

**Comment by XDTM** [comment]
I agree with the sentiment overall, my personal grudge is against certain unshakeable traditions that are often kept even if their gameplay sucks because they're "what ss13 is", like the singulo until the SM replaced it.

**Comment by outbools** [comment]
SS13 is not a visual novel nor any other story-driven game. It was never focused on story, actually you playing the same shift people played 15 years ago (my headcannon). End your fucking lore bullshit. 

We always consider lore to be flexible enough to even be redacted ingame through admin events, so when the time come and some good-made big PR gets rejected because of lore, you should know we either switched to singleplayer or we just got fucked design-wise.

People coming here to play and we never going to provide unique or decent lore yet we can provide exciting, unique and niche gameplay.

**Comment by Bawhoppen** [comment]
@outbools I don't think ss13 is the game for you if you just want combat and mechanics non-stop

**Comment by outbools** [comment]
@Bawhoppen maybe its not a game for you if you want to fuck features, balance and other guys PR because of yours nonsense lore that you even cant keep in one place? Bay got their lore categorized in their repo yet even their lore still got many unfinished moments. So are you asking us, BRILLIANT coders, to cease our feast of creativity because some bunch of fanfic writers told you so?

**Comment by outbools** [comment]
Lore was always bend over around the existing features if you didnt noticed.

**Comment by XDTM** [comment]
It's not like you have to sacrifice either, lore can be warped a lot and still be consistent enough for ss13.

**Comment by AnturK** [comment]
Please keep the soapboxing out.

**Comment by Really-Good-Soda-Flavor** [comment]
Reopen this

**Comment by Iamgoofball** [comment]
@Cheridan Could you please consider reopening this?

@AnturK I don't quite understand what you mean, this PR is designed to PREVENT soapboxing.

**Comment by AnturK** [comment]
We don't need to codify common sense.

**Comment by Bawhoppen** [comment]
@outbools This game and its features has always had a basis of some level of RP, if you completely choose to forego that and decide to make it completely about combat, PVP, and make it into a TDM, you're not playing Space Station 13 anymore.

**Comment by Iamgoofball** [comment]
@AnturK Obviously we do, because it's getting to the point where features and game balance are getting held up over lore.

**Pull request closed without merging**
