### PR TITLE
Minebots will no longer attempt to stop you from committing suicide by killing you

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

The `/datum/pet_command/protect_owner` behaviour did not have any validation for if the person who attacked you was yourself.
The three mobs which used this behaviour would sometimes be capable of seeing you accidentally slap yourself with a burrito and decide that this meant that you needed to be protected from this hideous and violent aggressor (yourself), and would then start trying to kill you.

If you had multiple minebots they would then start attacking each other in a fit of jealous and protective rage, which I think was quite funny but isn't supposed to be how the game works.

## Changelog

:cl:
fix: Minebots, Tamed Wolves, and Regal Rat Minions will now give you some space if you start attacking yourself, rather than joining in.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
okay but i just had the greatest idea to keep this unintentional feature in and i think we should have this as a separate check

```dm
if(source == attacker)
 say("Please stop hurting yourself!") // can tie this to a blackboard keyed list with various mob-specific phrases
```

**Comment by Ephemeralis** [comment]
> Wolf might whine sadly and regal rat minions would squeak sadly but i think it's really funny to have minebots get worried when you do that

If only the regal rat had its own language, so the rats can all squeak "MY LIEGE! NO!" or some variation thereof and nuke ghost ears observers with 120 lines of randomized concern lines.

**Comment by Jacquerel** [comment]
> > Wolf might whine sadly and regal rat minions would squeak sadly but i think it's really funny to have minebots get worried when you do that
> 
> If only the regal rat had its own language, so the rats can all squeak "MY LIEGE! NO!" or some variation thereof and nuke ghost ears observers with 120 lines of randomized concern prompts.

I think I will probably give this both a _chance_ to fire and a cooldown 😅

**Comment by Exester509** [comment]
Minebots doing that if emagged would be the most hilarious thing ever done

**Comment by Jacquerel** [comment]
ok I got around to it

**Pull request merged**
