### PR TITLE
Adds chemical dispenser functionality to the Portable Chemical Mixer

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
The Portable Chemical Mixer can now accept any power cell, allowing it to dispense any of the basic chems like a normal chem dispenser, excluding those available from a femto manipulator upgrade or an emag.
Makes the UI more user-friendly.
The beaker that you place in the mixer to receive chems no longer occupies a slot in the bag.
## Why It's Good For The Game
Portable Chem Mixer suffers from misuse due to several factors.
1. The UI is different from the standard chem dispenser, which slows down chemical mixing due to the loss of built up muscle memory
2. Having to refill it manually with beakers, containing reagents from a machine chem dispenser is just additional effort, when you can just directly use the machine chem dispenser.
3. When mixing large amounts of chemicals, plumbing is more likely to be used, since it's easy to setup, automate and just works.

I am giving the portable chem mixer some basic dispensing functionality, albeit at half efficiency compared to a normal portable chem dispenser. 
## Changelog
:cl:
add: Portable Chemical Mixer can now accept a power cell to dispense basic chems.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
this is an absolutely absurd power creep on an item that is already not bad if you know how to use it (cc @maurukas). you are welcome to make a portable chem dispenser but it should be a separate item, and probably start behind an anomaly core

**Comment by Xander3359** [comment]
The chem dispenser is already portable, you can unwrench it and drag it literally anywhere as long as there's power.

**Comment by Mothblocks** [comment]
surely you do not think that is equivalent xander

**Comment by LemonInTheDark** [comment]
> I know this is powercreep, but I think it can be balanced behind tech

https://www.youtube.com/watch?v=f1437qWlQXM

**Comment by Xander3359** [comment]
I mean hey, I just thought it could be a cool way to revive a item that literally nobody uses. I don't think an anomaly core is the way to go though, I think if a chemist wants access to cooler tools, it should be something they accomplish (like botany completing wild biomatter mutation to unlock advanced tools). Not sci just randomly deciding to refine a core they dont have any use for, or getting lucky with a random anomaly spawn.

**Comment by Mothblocks** [comment]
the anomaly core is literally the way to go thats the entire reason the system was added is to let us make more powerful items

**Comment by Xander3359** [comment]
I'm looking at the history of this item and I can see the reasoning for this item is that an anomaly core gives a way for this item to be restricted in number in a round. Would re-adding the anomaly core requirement + the chem dispenser functionality be a acceptable way to go with this item? In its current state, despite being mass printable, most people do not even know that this item exists, let alone want to interact with its clunky UI.

**Comment by Mothblocks** [comment]
it having a clunky ui can be adjusted without giving it a chem dispenser. i think you would be better off making it a separate item

**Comment by Xander3359** [comment]
If anything I think the item should be deleted altogether. If it's a science item then there is no way for chemistry to acquire it, and it has to compete against a portable chem dispenser machine, which when femto upgraded can dispense pure oil, ash, ammonia, dieth, acetone and saltpetre. Just being able to dispense pure oil/ash is already extremely powerful and is something you give up by using the portable variant.

**Comment by Mothblocks** [comment]
this is a completely fine and fun item though i used to play with it

**Comment by Mothblocks** [comment]
im giving you an out here but u dont want it

**Comment by Mothblocks** [comment]
the point of the anomaly cores is to gate off powerful items in a way that lets us know exactly how many are in the round

they are also to incentivize more people work with science

i dont know where the miscommunication is here. i dont want people just making powerful chems to power their thing, i want anomaly cores because thats the specific feature we built for this exact purpose

**Comment by Xander3359** [comment]
Would an anomaly core upgraded variant of the item be a good solution then? Or just a new item altogether.

**Comment by Mothblocks** [comment]
i still think you should just make a new item

**Comment by Maurukas** [comment]
I have been summoned.

Mothblocks has already made this clear - but as it stands the portable chem mixer is one of the most absurdly powerful items in the game, and it has already had it's gating chipped away. The only reason that this thing hasn't ended up on the chopping block is to use it to anywhere near it's full potential you need a very solid understanding of medicine, chemistry and plumbing, not to mention a few apparently innocuous items from other departments. It's also very strong in a non-destructive role if you want to play pharmacist in Medbay.

If you want a portable synthesizer then I would say that:

* It needs to be a completely separate item from the mixer
* It's construction needs to be in the hands of Med/chem (printed from their lathe)
* It's construction needs to be gated behind an anomaly core
* It needs its own late game tech node with a unique experiment (equivalent to the high end sec guns)
* It needs to have a very, very small power capacity - no more than 500 units of charge maximum
* It should **not** have the ability to heat or chill chemicals, or to separate them.

My suggestion for an experiment would be: Detonate a chemical payload with a minimum strength. That strength should be around 600u Teslium + 600u RDX. An experiment like this would require multiple pieces of interdepartmental cooperation - Bluespace Beakers and the bomb range from Science, chemicals from a reasonably skilled chemist, and Gibtonite from Cargo.

**Pull request closed without merging**
