### PR TITLE
Replace the map merger with a new map converter.

### PR DESCRIPTION
**Pull request by pubby**
_Don't merge this yet I haven't tested it enough._

This is a partial rewrite of the map merging tools to make both the code and workflow simpler.

**OLD MERGER:**

It was a 3-step process:

1. Run a preparation script to make "backup" copies of all the .dmm files.
2. Edit the map file
3. Run a second script which reads both the edited .dmm and the backup .dmm and "merges" them together.

This workflow takes a lot of discipline to get right and it doesn't mesh well with git. [If you're an idiot like me then you're bound to screw up over and over again.](https://github.com/tgstation/tgstation/pull/21405#issuecomment-259019178) And the code behind the "merge" step is really quite complicated.

After the script runs the resulting .dmm file has dictionary keys defined in a linear order and looks like this:
```
"aaa" = (
)
"aab" = (
)
"aac" = (
)

// . . . at the end of the dictionary section it ends with 'b's:
"bav" = (
)
```

**NEW CONVERTER:**

This new converter does not make backups or care about the past. It performs a direct conversion from one format to another.

Here's the workflow:

1. Edit the map file
2. Convert the map file

It's as easy as converting from PNG to JPG.

The dictionary keys are not linearly ordered, but rather spread out across the entire range of possible values. This is done using an open-addressed hash function that uses tile definitions as the input parameter. The .dmm files look like this:

```
"AAH" = (
)
"AAX" = (
)
"AAZ" = (
)

// . . . at the end of the dictionary section it ends with 'z's:
"zZq" = (
)
```

Using hash values as dictionary keys ensures that lines remain stable and unchanged across edits. Inserting and removing dictionary keys can be done without affecting nearby lines.

**TESTING:**

As a test I tried running the converter script on [this commit where I had botched the map merger:](https://github.com/tgstation/tgstation/pull/21405/commits/78ff635d84461885b29d70d48fb8148a59c92ab3)

- Map merger (botched): 1663 additions, 1,658 deletions. 
- Converter: 47 insertions, 52 deletions.

(Note: I spent like 20 fucking minutes trying to get the map merger working correctly so that I would have a fair comparison here, but after 3 attempts I couldn't get it working. Though, a correctly working map merger would probably have a +47, -52 diff too.

**FINAL THOUGHTS**

If this gets in then all of the existing maps would have to be converted. :new_moon_with_face:

### CODE REVIEW

**Comment by CrAzYPiLoT-SS13** [comment]
TBH, you can just use FastDMM and avoid the map merge process altogether.
It's also much faster and better than the original DM map editor.

**Comment by xxalpha** [comment]
Uhm, what.

**Comment by Cyberboss** [comment]
That fast dmm is good shit, we should probably get it as a submodule or something

**Comment by optimumtact** [comment]
If the tile is edited, won't this mean the dictionary key will change?

How can this
>Using hash values as dictionary keys ensures that lines remain stable and unchanged across edits. 

Be true in that case?

**Comment by xxalpha** [comment]
I knew I was missing something when I was reviewing this in the toilet.

**Comment by pubby** [comment]
@optimumtact 

If you modify all instances of a dictionary entry then the old entry gets removed and a new entry under a different hash gets added.

If you modify only a few instances of a dictionary entry then the old entry stays and a new entry under a different hash gets added.

Both cases have small diffs and are friendly to merging.

**Comment by xxalpha** [comment]
The point is that keys will always be changing if the tiles are changed.

**Comment by optimumtact** [comment]
I don't understand how this is minimizing diffs, can you explain the process to me as if I was a moron?

**Comment by xxalpha** [comment]
Hmm...two people can't change the same tile, actually. It sort of increases the conflict possibility from "conflict if you edit the same atom" to "conflict if you edit the same model".

I found it is more complicated than that, but it's simple enough explanation for this.

**Comment by pubby** [comment]
@optimumtact

The .dmm file format is a bunch of key/value pairs that look like this:
```
"aaa" = (/some/path/)
"aab" = (/some/other/path/)
"aac" = (/some/third/path/)
```
DreamMaker is dumb and assigns keys to values arbitrarily. If you were to make changes to the map file and save it, chances are the values would have different keys and thus be sorted in a different order. This is especially true when adding/removing dictionary values:

```
"aaa" = (/some/path/)
"aab" = (/some/new/path/)   // the only addition to the map
"aac" = (/some/other/path/) // was aab previously
"aad" = (/some/third/path/) // was aac previously
```
A diff for the above would touch the bottom two lines despite the fact that those two areas weren't actually modified. The diff would show 3 additions, 2 removals.

**Conversion script**

The conversion script changes how the keys are assigned to make everything non-arbitrary and deterministic. Converted keys are just a hash of their value.

```
"aAb" = (/some/path/)
"dXq" = (/some/other/path/)
"mpT" = (/some/third/path/)
```
These associations remain constant across all .dmm files; `/some/path/` will be assigned to key `"aAb"` in Box, Dream, Meta, Eff3, etc. This allows adding and removing dictionary entries from maps without causing unrelated entries to changes:

```
"aAb" = (/some/path/)
"dXq" = (/some/other/path/)
"llK" = (/some/new/path/)   // the only addition to the map
"mpT" = (/some/third/path/) // wasn't modified!
```
A diff for the above would show a 1 line addition.

**Edits**

Editing a dictionary entry is equivalent to creating a new entry and removing the old one. For example, changing `/some/path/` to `/some/edited/path/` would have this effect:

```
"dXq" = (/some/other/path/)
"llK" = (/some/new/path/)
"mpT" = (/some/third/path/)
"xJw" = (/some/edited/path/) // the edit
```

Note that "aAb" is gone and "xJw is added". The diff would show 1 insertion, 1 removal.

**Comment by optimumtact** [comment]
Thanks, seems like it would work well in practice

**Comment by xxalpha** [comment]
So there would only be conflicta on the map layout, am I getting this right?

**Comment by pubby** [comment]
So I ran some more tests and tried merging two large-scale edits together with this converter script...

And I got conflicts.

They were spurious and easy to fix conflicts caused by git being extra cautious, but still, I got conflicts. The script is a pile of shit.

***But that's okay because I found a better way~***

Ditch the dictionary compression and store everything "uncompressed":
```
 "aaa"=(
/turf/open/space,
/area/space)
(1,1,1)={"aaa"}
"aab"=(
/turf/open/space,
/area/space)
(2,1,1)={"aab"}
"aac"=(
/turf/open/space,
/area/space)
(3,1,1)={"aac"}
"aad"=(
/turf/open/space,
/area/space)
``` 
Every coordinate on the map gets its own entry. There is no sharing of entries. There is no hashing. The file size is huge but that's okay because...

***It merges fucking perfectly***

Edits to separate areas of the map are guaranteed to not have conflicts. Overlapping edits *can* have conflicts, but that's okay because they're really easy to fix with this format.

***Important optimization:***

Interleaving dictionary definitions with use of those

**Comment by xxalpha** [comment]
That makes no sense.

**Comment by CrAzYPiLoT-SS13** [comment]
I still don't understand why you are ignoring the fact that FastDMM does
exactly this, just in a more efficient way and creates exactly 0 conflicts
each time. Not trying to advertise here, but you're making a problem out of
something that can be easily solved an had already been solved by
monster860.

**Comment by xxalpha** [comment]
Did fastDMM fix its performance problems yet? Until the people running this project say FastDMM is standard, we need the map merger.

**Comment by CrAzYPiLoT-SS13** [comment]
It never had performance problems, afaik.

2016-11-10 16:54 GMT+01:00 xxalpha <notifications@github.com>:

**Comment by optimumtact** [comment]
FastDMM is a perfectly fine alternative to the map merger, as it does very similar things in terms of rewriting the diff's and it exports to tgm.

It's a very nice tool

**Comment by Mervill** [comment]
Interesting. I've been working on something similar in C#, looks like pubby beat me to the punch. My tool is a bit more general, being able to preform arbitrary checks/mutations on the map such as fixing step_x/step_y issues, and potentially being able to pre-smooth some objects like tables.

Is that something people might still be interested in? I'm a sucker for writing developer tools.

**Comment by monster860** [comment]
If you do this, please make it so there is some way for FastDMM to tell that this algorithm is in place, and clearly document it.

**Comment by optimumtact** [comment]
At the moment this offers no benefit over our existing map merger

**Comment by optimumtact** [comment]
@Mervill we avoid presmoothing as we have a smoothing framework established in the code

it smooths 99% of items that do smooth together at the moment

**Comment by Mervill** [comment]
The smoothing framework is awesome, obviously. But why pay a startup cost when you can presmooth and save? Especially if it's an automated process?

If smoothing doesn't seem like an issue, what about finding atmospheric tiles adjacent to space? It could probably reduce/eliminate the "X air tiles adjacent Y space tiles at startup" warning, which almost always has a nontrivial startup cost associated with it.

**Comment by xxalpha** [comment]
I think the hashing method would be better in all aspects if it works.

**Comment by xxalpha** [comment]
@Mervill smoothing is fast, there is no need to do any pre calculations.

**Comment by optimumtact** [comment]
@Mervill basically what @xxalpha it's fast, plus it removes the temptation from developers to avoid setting up smoothing and relying on map editors (which then means it doesn't resmooth if people rebuild the item when it's destroyed)

Other map tweak items are certainly welcomed however.

**Comment by pubby** [comment]
What is the format of FastDMM files? It's not clear to me.

@xxalpha 

The problem with hashing is that modifying adjacent lines is considered a conflict. So if branch one adds hash "aac", and branch two adds "aad", then there will be a conflict on those two lines. It's trivial to fix this conflict by just including both "aac" and "aad" in the final output, but still, conflicts.

@Mervill

>If smoothing doesn't seem like an issue, what about finding atmospheric tiles adjacent to space?

This is an existing feature in the game's debugging menu (check roundstart turfs) so it's not super critical.

**Comment by optimumtact** [comment]
FastDMM just outputs tgm as far as I know

**Comment by monster860** [comment]
@optumumtact @pubby FastDMM remembers the TGM-ness of the file it loaded and saves it that way when you hit save.

**Comment by Iamgoofball** [comment]
@optimumtact i did get told by people who made the shuttle system we use now, to pre-smooth and not use autosmooth shuttle walls but that's just what I was told

**Comment by Mervill** [comment]
You could also include nontrivial smoothing operations like smooth windows + walls.

@optimumtact 

> which then means it doesn't resmooth if people rebuild the item when it's destroyed

I don't see why that has to be true, presmoothing simply removes the need to walk the smoothable items list at startup. Smoothable objects can have all of their current behavior preserved, minus any startup penalty.

**Comment by pubby** [comment]
I did some more testing.

First I tried merging two large-scale (500 tile) changes using the old mapmerger. Each branch's diff had about +2000, -1000 changes. When I tried doing the merge I got conflicts.

Second I tried merging the same changes using the uncompressed format converter. The diffs were +1500, -1500 and I got no conflicts.

Uncompressed seems objectively better to me. It is guaranteed to not conflict unless both branches modify the same position on the map.

**Review by MrsTonedOne — APPROVED** [review]

**Comment by MrStonedOne** [comment]
Please test with bigger maps to make sure the extra entries don't cause issues in byond.

255*255 might work fine, but how about 300*300 or 512*512 I think you might end up hitting some hard limit in byond.

**Comment by MrStonedOne** [comment]
also, compare memory and startup times of both, as byond may be using the dictionary key storage to detect dupe tiles when storing the map info.

(I do know that this would increase the prototype storage since each var edited atom in a map is stored as a new type when compiled, but that shouldn't matter)

**Comment by MrStonedOne** [comment]
oh, and finally, make sure the runtime map reader code can understand this format.

**Comment by pubby** [comment]
perf stat results for compiling:

merger:

```
     103534.893731      task-clock:u (msec)       #    0.999 CPUs utilized
            33,948      page-faults:u             #    0.328 K/sec

     103.615214933 seconds time elapsed

```

converter:

```
     110072.033046      task-clock:u (msec)       #    0.996 CPUs utilized
            35,808      page-faults:u             #    0.325 K/sec

     110.540920277 seconds time elapsed
```

perf stat results for server startup:

merger:

```
     115055.354833      task-clock:u (msec)       #    0.998 CPUs utilized
           131,803      page-faults:u             #    0.001 M/sec

     115.241043860 seconds time elapsed
```

converter:

```
     116602.579265      task-clock:u (msec)       #    0.991 CPUs utilized
           135,024      page-faults:u             #    0.001 M/sec

     117.717597879 seconds time elapsed
```

I only ran one of each test and so my results may not be accurate, but confirmation bias is telling me that each converted map file takes a second or two longer to load. Important note: I have a shitty, slow-speed HDD.

**Comment by xxalpha** [comment]
The format you suggested (not the hash format) does not bring any advantages over the current format.

**Comment by pubby** [comment]
@xxalpha I'm not convinced either, but it did appear to merge branches that weren't mergable with the current format. Also it's simpler.

**Comment by xxalpha** [comment]
You need to provide hard evidence for that.

**Comment by optimumtact** [comment]
Well
What about this then

**Comment by pubby** [comment]
It doesn't seem very popular and the added downsides are making people unsure, so I'm just going to close this.

(also I'm lazy and don't want to be maintaining this)

**Comment by PKPenguin321** [comment]
unfortunate

**Comment by xxalpha** [comment]
>(also I'm lazy and don't want to be maintaining this)

No damn you! TAKE THE BURDEN

**Pull request closed without merging**
