### PR TITLE
Removes Access Restriction on Mining Shuttle Console

### PR DESCRIPTION
**Pull request by Cheridan**

### CODE REVIEW

**Comment by palpatine213** [comment]
Might want to remove the emag act then, as it removes the access restrictions.

**Comment by Supermichael777** [comment]
central control to outpost transit inbound

**Comment by Cheridan** [comment]
@palpatine213 That's a general /obj/machinery/computer/shuttle emag action. Other shuttle console types such as the gulag shuttle still have access restrictions. 
I could override the emag_act() for this type but there isn't really a whole lot else it could do. Make it crash? That'd be for another PR at any rate.

**Comment by Rinoka** [comment]
I'd think an interesting emag action would be locking it down, for when you don't want the crew escaping alive. Or just to fuck up Science's day.

**Comment by Alek2ander** [comment]
Or send it to the clown asteroid on a one way trip.

**Comment by Rinoka** [comment]
But then traitor clown's entire goal would be robusting his way to Mining and emagging the console.

Honk.

**Pull request merged**
