### PR TITLE
Revenant Changes XVIII: You'd better be afraid of the ghost

### PR DESCRIPTION
**Pull request by ChangelingRain**
> Revenants can now tell if they are currently visible.
> Revenant draining now takes about 5 seconds to complete and can be interrupted by dragging the target away.
> Draining a living human now gives you 5 additional maximum essence.
> Draining a perfect soul now gives 15 additional maximum essence instead of 25.
> This is instead of the 5 essence for a living soul, and not in addition to it.
> 
> Revenant abilities tweaked:
> Defile now costs 40 essence to cast.
> Overload Lights now costs 45 essence to cast.
> Malfunction now costs 50 essence to cast.
> Defile does an extremely low amount of toxin damage to humans and confuses, but does much less stamina damage and stuns the revenant for slightly longer.
> Overload Lights will no longer shock if the light is broken after a light is chosen to shock an area.
> Overload Lights does 18 damage instead of 20.
> Malfunction now affects non-machine objects, even if they're not being held by a human.

TODO: GET SPOOKY FOR HALLOWEEN

### CODE REVIEW

**Comment by Supermichael777** [comment]
Halloween was a week ago....
but otherwise these seem fairly good.

**Comment by Zilenan91** [comment]
So how long is the stun on defile? Is it stupidly long like Overload lights is? If it is it's awful.

Also can you please lower the stun on overload lights? It's so so stupidly long for what it does.

**Comment by Anonus** [comment]
Defile is 3~ seconds, overload lights is 4~ seconds.
Overload lights is that high because it's a really powerful stun+damage with pretty good range, and you should be somewhat able to pin it down instead of it escaping rapidly.
Fun fact, revenants can hear eachother talk.

**Comment by Zilenan91** [comment]
Do you mind reducing the stun of overload lights by 1? 4 seconds is just too long to ever be viable, almost every single time I've bought it I've just died.

**Comment by Anonus** [comment]
Overload lights is extremely viable at the moment, so you may be using it wrong, such as on disabled lights or in spots that only cause one or two lights to shock targets.
I'll just fix the bug where it could shock through walls and lower the stun to 35.

**Comment by Zilenan91** [comment]
Nah. Every time I used I had it shock people, then them get up, pull out a spear/laser and kill me.

**Comment by Dorsisdwarf** [comment]
Never seen a revenant get killed for using the gigantic AOE damaging unescapable stun myself, no

**Comment by Zilenan91** [comment]
The exact situation was me stunning a janitor next to me, who then whipped out a laser gun and killed me while I was completely unable to move.

Also overload lights only shocked people in a radius of two around the lights, so he moved out of it right after I casted it and wasn't effected.

**Comment by Anonus** [comment]
My thoughts on that are basically "if you mess up the huge aoe stun, you deserve to get dunked on" because it's pretty hard to mess up. In 3-wide hallways, a single light will cover the entire width of the hallway, easy.

**Comment by KorPhaeron** [comment]
I dunno if this is really fixable so I dont want to make an issue report but we had a revenant recently camping genetics and instant killing people in that second of unconciousness after cloning. He ate the same guy ~5 times like this

**Comment by Anonus** [comment]
It's somewhat impractical to fix, if you know a revenant is about you should probably keep watch on the clones and drag them away from the revenant.
I could make draining check AGAIN if they're getting up after harvest, but I'm not entirely sure I want to do that.
In any case, this slows down the drain so it's a bit easier to interrupt a revenant eating people.

**Pull request merged**
