### PR TITLE
Removes medbay

### PR DESCRIPTION
**Pull request by FloranOtten**
SNAP

## About The Pull Request

Removes medbay

## Why It's Good For The Game

Medbay has always been a shitty process. Walk in, get meds, walk out.  This aims to make death more impactful by forcing crews to scavange the few space ruins for meds. 

## Changelog
:cl:
del: Removes medbay.
/:cl:

### CODE REVIEW

**Comment by adamkad1** [comment]
remove ss13 plz

**Comment by Fikou** [comment]
did you buff tlalte and space powergaming

**Comment by Teepeepee** [comment]
this is a great bartender buff, finally people will need to drink stuff with lime juice for toxin, tomato juice for burn, milk for brute and orange juice for oxydamage
that is without even considering the other healing drinks like barefoot, or bastion bourbon, which will create more cooperation with botany
+1 from this humble bartender

**Comment by ShizCalev** [comment]
Conflicted, but regardless still, no.

**Comment by FloranOtten** [comment]
I'm severely annoyed at my lag of an april fools tag

**Pull request closed without merging**
