### PR TITLE
All of space is now randomised

### PR DESCRIPTION
**Pull request by coiax**
With thanks to incoming for doing some of the work.

:cl: coiax, incoming
rscadd: Due to budget cuts, the builtin anti-orbit engines on the station have been removed. As such, expect the station to start orbiting the system again, and encounter an unpredictable stellar environment.
rscdel: All permanent structures (not on station, Centcom or lavaland) have been removed.
rscadd: All removed structures are now space ruins, and can be placed randomly in space ruin zlevels.
wip: The White Ship remains at its current location, but has lost any reliable landmarks near it. Its starting position will be made more random in a coming update.
rscadd: The Space Bar has a small atmos system added and a teleporter. Some other ruins have been cleaned up to not have atmos active turfs.
/:cl:

Bugs:
- [x] Sometimes, crossing the transition of a z level will just send the mob to nullspace rather than to another z level. This is a bad thing.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
shhh space exploration is one of my only skills

**Comment by Core0verload** [comment]
Loading КС13 takes something like 5 seconds in roundstart setup and often breaks the atmosphere. No.

**Comment by Bawhoppen** [comment]
Coiax is a god

**Comment by kevinz000** [comment]
>no reliable landmarks
>gps

**Comment by Dorsisdwarf** [comment]
If you're doing this, can you trim the derelict space ruins so they don't have a thirty fucking tile radius of space around the good stuff? They might actually be used for admin events then.

**Comment by Bawhoppen** [comment]
I imagine the reason they have that is for the derelict teleporter, but that could probably be split into a seperate ruin

**Comment by Dorsisdwarf** [comment]
No, as in the existing derelict templates 1-6 you can drop. They all have a huge area of space tiles around them which means you can't place them near the station without deleting all the turfs in that area.

**Comment by Bawhoppen** [comment]
oh those ones are shit and I oppose them

**Comment by InsaneHyena** [comment]
This kills the white ship memes for cult, right?

**Comment by Incoming5643** [comment]
the derelict ruin isn't the whole z-level, the derelict teleporter, Rusky DJ station, and Clownship are now their own derelicts seperate of it.

**Comment by coiax** [comment]
@Dorsisdwarf if I do any more map edited I think github might just run away and cry. But I'll trim the excess space around them in another PR

**Comment by PKPenguin321** [comment]
Honestly I think white ship and abandoned teleporter should stay static. They're a huge source of teleporter and space explorer related gimmicks, and it would be a shame to see them go.

How does white ship docking on derelict interact with this?

**Comment by MrStonedOne** [comment]
What spawns them in? wouldn't this require changes to the spawn map code in the mc setup? I can't actually see if any of that was changed in the pr list because the diff is too big.

**Comment by MrStonedOne** [comment]
Edit: Ya, this edits the MC. I'm moving all of that stuff in setup over to a init only subsystem so keep the snowflake and spam out of mc's setup()

**Comment by coiax** [comment]
@MrStonedOne I've removed any modification of the master controller, can we un-feature freeze it?

**Comment by optimumtact** [comment]
Unfrozen by merging the MC

**Comment by optimumtact** [comment]
@coiax do you intend to add those MC changes back now?

**Comment by coiax** [comment]
Yeah.

**Comment by optimumtact** [comment]
RIP randomized space

**Comment by Dorsisdwarf** [comment]
Is this being testmerged? apparently the derelict is AWOL and people are having fits.

**Comment by coiax** [comment]
Yes, it is test merged at the moment.

**Comment by optimumtact** [comment]
How did the test merge go?

**Comment by Dorsisdwarf** [comment]
I get ahelps every few rounds about "Derelict is gone" "cant find derelict" "wtf happened to derelict", but that's it really

**Comment by optimumtact** [comment]
I'm suprised so many people visit the derelict

**Comment by Bawhoppen** [comment]
I never ever see anyone in space as far as I was aware I was the only one to ever to go there

**Comment by optimumtact** [comment]
Wait so the derelict missing, is that a bug or just a feature of how the remapping works? It's not clear if I can merge this

**Comment by Incoming5643** [comment]
the derelict is still there, it's thederelict.dmm

**Comment by coiax** [comment]
The derelict isn't missing, it's just not a guaranteed spawn.

**Comment by optimumtact** [comment]
Did you resolve that bug in the OP yet?

**Comment by MrStonedOne** [comment]
Could you detail what the space transitions look like now?

Like how z-levels are connected.

**Comment by coiax** [comment]
Yes, I fixed the bug.
Z levels are connected in exactly the same way as they were before, via some magical torus or something. I removed the stuff about the 3x3 grid, that's not happening until I shout at the space transition code more

**Comment by optimumtact** [comment]
Alright, lets do it!

**Pull request merged**
