### PR TITLE
Mulebots no longer require hacking to load everything. 

### PR DESCRIPTION
**Pull request by KazeEspada**
They can load everything by default. It just makes more sense.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Viva la disagree.
If you want fancy mulebot rides, spend the 20 seconds hacking them, you're supposed to send crates places, not joyride!

**Comment by KazeEspada** [comment]
Actually, I did this so I can put a cardboard box on the mule. Well, since you could just climb into the box, and then put the box on the mule, it was easier to just do this.

**Comment by ChangelingRain** [comment]
You, uh, could just change it to search for `/obj/structure/closet` instead of `/obj/structure/closet/crate`

**Comment by KazeEspada** [comment]
Then humans could get into the locker, and RIDE THE BOT ANYWAYS.

**Comment by duncathan** [comment]
@KorPhaeron

**Comment by PKPenguin321** [comment]
:+1:

**Comment by neersighted** [comment]
Make it `/obj/structure/closet`. Humans can ride anyway, but its humans directly on top of the mule instead of in a package that should be behind hacking.

**Comment by KorPhaeron** [comment]
I don't really care either way honestly.

It's easy busy work so its not a balance thing, but if we automate/remove all the little tasks there will not be anything left to do

**Comment by phil235** [comment]
:-1: What's next? Making contraband items in vendors already available at roundstart?

**Comment by KorPhaeron** [comment]
Seems several maintainers are against this, sorry.

**Pull request closed without merging**
