### PR TITLE
Nitroglycerin heals heart damage

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Nitroglycerin heals heart damage when metabolized

## Why It's Good For The Game

- I thought it'd be a fun nod to one of the actual uses of Nitroglycerin.
- "Plausible Deniability" to chemists making Nitroglycerin. 
- Adds more niche chem effects to the ecosystem chemists may experiment with.

## Changelog

:cl: Melbert
add: Nitroglycerin now heals heart damage.
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
when are we adding 3 month wait lists to be seen by a doctor

**Comment by Loafin34** [comment]
i thought penthrite did this already

**Comment by Time-Green** [comment]
For reference, nooartrium deals 1 damage per tick at a 100% purity. This is another method of indefinite immortality. Maybe put it at something like .8 to force an expiration date?

**Comment by MrMelbert** [comment]
What if I just add a chemical reaction between the two that blows you up

**Comment by Sakamoto4ka** [comment]
grandma confirmed

**Comment by Exester509** [comment]
> What if I just add a chemical reaction between the two that blows you up

What if you got worrying messages about your heart before it promptly shoots out of your chest as a primed explosive, blowing up shortly after?

**Comment by Livrah** [comment]
> For reference, nooartrium deals 1 damage per tick at a 100% purity. This is another method of indefinite immortality. Maybe put it at something like .8 to force an expiration date?

Nitroglycerin heals only 0.5

**Comment by dalmationer** [comment]
> For reference, nooartrium deals 1 damage per tick at a 100% purity. This is another method of indefinite immortality. Maybe put it at something like .8 to force an expiration date?

even if it was, it'd be fine because if you had enough in your system for a long period of immortality, the nitroglycerin would detonate due to body temp increases if you got set on fire, destroying your body, which is really funny.

**Comment by CCC23** [comment]
> For reference, nooartrium deals 1 damage per tick at a 100% purity. This is another method of indefinite immortality. Maybe put it at something like .8 to force an expiration date?

It's timed immortality where if you get lit on fire you immedielty gib and die

**Comment by Sakamoto4ka** [comment]
btw nitroglycerin is often used to prevent a heart attack so why not make a counter initropidril

**Pull request merged**
