### PR TITLE
Wooden holodeck chairs can no longer be picked up

### LINKED ISSUE #16867: Wood chairs in the holodeck can be picked up and carried out
Apparently, the wooden chairs in the holodeck stop being holographic once picked up. This basically means infinite wood.

Steps to reproduce:
1. Enter holodeck
2. Set holodeck to Lounge (or maybe it's called Lobby, I don't recall 100%)
3. Pick up a wooden chair by dragging it to your character
4. Carry it out of the holodeck
5. Place the chair and notice how it does not disappear
6. Wrench chair and get free wood

You can also bash a mob with a chair until it breaks to get the wood.

### PR DESCRIPTION
**Pull request by coiax**
Fixes #16867

### CODE REVIEW

**Comment by ChangelingRain** [comment]
This seems like a somewhat improper way to do it, even though I know it'll work.

**Comment by coiax** [comment]
Holodeck object "derez" works by the holodeck keeping a track of all holographic objects, and checking each process() for any being out of bounds.

The only existing object that is supposed to make child objects is the deck of cards, and that specifically has a variable in it to reference the holodeck so it can inform mama HD when it makes a new card so it can be added to the objects list.

To make a chair that could be picked up and dropped, you'd need to track the holodeck in both chair(structure) and chair(object), and I figured that was probably more mess than it was worth. So I just made them unpickable, which is a supported part of the pickingupchairs code.

**Comment by coiax** [comment]
It's been suggested that instead of modifying the map code, I instead make chair picking up obey the NODECONSTRUCTION flag, which should be set on all items spawned in the holodeck.

**Comment by coiax** [comment]
@ChangelingRain ready for review plox

**Pull request merged**
