### PR TITLE
Charger holoparasites now shake the target's camera

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Charger holoparasites now play a sound when hitting a target, as well as shaking the target's camera.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
when are you going to make charger holos actually make people go flying backwards without a stun

**Comment by ChangelingRain** [comment]
Basically never until we have a throw that doesn't stun when you hit a wall

**Comment by Iamgoofball** [comment]
i dont see wall throws used enough to warrant keeping them tbh

i'll stat track it and see how often its used

**Comment by PKPenguin321** [comment]
that is autismal

**Comment by Iamgoofball** [comment]
test

**Comment by Iamgoofball** [comment]
@ChangelingRain is my mom irl

**Pull request merged**
