### PR TITLE
Remove rads

### PR DESCRIPTION
**Pull request by Ghilker**
Radiations are gone, machines that used to directly add radiations to mobs will instead add toxins.

## About The Pull Request
Total removal of the radiation system.
There is more work to be done but the bulk should be done

## Why It's Good For The Game
Radiations are the worst system in the game, harmful, with low usecase on non-antags. 
The worst offender is that the rads are totally invisible and there isn't a way to know that you are being hit (the glow only start at 350 contamination). The performance loss is another big stone in this, but wasn't considered on the why i'm making the PR.

## Changelog

:cl:
remove: Radiations are gone
/:cl:

### CODE REVIEW

**Comment by Zytolg** [comment]
I thought you were removing contamination  LOL

**Comment by HighPrincessErinys** [comment]
tgstation dont make horrendous changes challenge

**Comment by Ghilker** [comment]
> I thought you were removing contamination LOL

I tried that, but the glow went away from anything bringing the radiation system back to all invisible, so I changed to this

**Comment by FernandoJ8** [comment]
3134cc946f29b2e3a2d186591a5a81f1d41ac746ef14c662338ad8c09b43f5d2_1

**Comment by FernandoJ8** [comment]
Doesn't it make sense for the machines that used to deal rad damage to deal cellular damage instead, rather than toxins?

**Comment by FernandoJ8** [comment]
> 
> 
> > Does that mean celullar is probably the next type of damage that's going under the axe?
> 
> nah is just that cellular damage is harder to cure than tox

Isn't that part of the point? Plus, it makes it so that cryo is still relevant for dealing with this kind of thing and it could allow potassium iodide to be changed to heal low amounts of cellular damage rather than being outright removed.

**Comment by Serxule** [comment]
> is only one chem the potassium iodine 

isnt there another chem thats better at removing rads? 
also, if radiation gets switched to cellular that's gonna be even harder to deal with than radiation

**Comment by plutori** [comment]
Why not just lower the required rad contamination value from 350 to something much lower like 10 for the green rad glow so that radiation becomes much more visible?

**Review by necromanceranne — COMMENTED** [review]
Since this potentially could still come back I figured I'd just leave some things to note.

**Comment by Supermichael777** [comment]
Wouldn't the simple option be to remove contamination and thus the explosion in rad sources and the preformed hit?  Axing the whole system just seems flat.

**Comment by Ghilker** [comment]
one last commit to readd technetium and seiver

**Comment by itseasytosee** [comment]
>Wouldn't the simple option be to remove contamination(a system that never made much sense from pure radiance) and thus the explosion in rad sources and the performed hit? Axing the whole system just seems flat.

I think this would work. Makeing a distinction between something being radioactive and irradiated.

**Comment by optimumtact** [comment]
on hold pending a document from mothblocks

**Comment by Acer202** [comment]
Hang on, if the machines just do toxins damage now, what happens if a slimeperson stands next to one? Do they just become god? HFR-powered slime demon.

**Comment by Kylerace** [comment]
removing rads completely is dumb. there is nothing prompting a removal as opposed to an overhaul that gets rid of the one truly offending part of it (contamination)

**Comment by Acer202** [comment]
> > The HFR?
> 
> No rads

I should clarify what I meant. If machines that spit out radiation damage like the HFR are changed so they just give people toxin damage when they're nearby, wouldn't a slime person be able to get some ridiculously high-powered healing effect from it?

"machines that used to directly add radiations to mobs will instead add toxins."

Unless what you're saying is that the HFR will just be entirely inert.

**Comment by MNarath1** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/3294

**Comment by MNarath1** [comment]
A PR on bee that completly reworked how radiation spreads and other stuff making it a lot less laggy while also removing the infinit rads by placing stuff on the ground problem

**Comment by LemonInTheDark** [comment]
We're aware of this yes. The behavior changes weren't something ninja was ok with, so we went with a more stripped down solution.

Xeno's based.

**Comment by Mothblocks** [comment]
huge desmos charts vs chad "if youre near something irradiated you might be irradiated"

**Pull request closed without merging**
