### PR TITLE
Reorganize holidays.dm

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
-moved all the scattered holidays (they weren't in date or alphabet order) to be ordered by date separated by comment
-created categories for hebrew, islamic, easter, holiday functionality addons, and holidays with moving dates

## Why It's Good For The Game
reordered messy file

### CODE REVIEW

**Comment by optimumtact** [comment]
I don't think we need more holidays unless they have a gimmick associated with them

**Comment by Mooshimi** [comment]
> I don't think we need more holidays unless they have a gimmick associated with them

Then just keep the organization?

**Comment by optimumtact** [comment]
yes

**Comment by Mooshimi** [comment]
when you delete the branch on accident :eyes:

**Comment by AMonkeyThatCodes** [comment]
> I don't think we need more holidays unless they have a gimmick associated with them

we can remove the new zealand ones to make room?

**Comment by optimumtact** [comment]
no

**Comment by Mooshimi** [comment]
> no

this is so basic y it not merge yet

**Comment by Mothblocks** [comment]
we busy

**Pull request merged**
