### PR TITLE
Remove an infinite loop in getFlatIcon

### PR DESCRIPTION
**Pull request by optimumtact**
It's unlikely that this could ever be triggered but it's worth doing

Credit to report from
https://github.com/ParadiseSS13/Paradise/issues/596

### CODE REVIEW

**Comment by optimumtact** [comment]
I would just like to say that this code is awful as sin

**Comment by AndroidSFV** [comment]
Yes, yes it is... 

Does this happen to fix any of the issues I attempted (and failed) to fix with #7477?

**Comment by Chocobro** [comment]
IF IT DOES I WILL BE SO HYPE i'll finally be able to take pictures of food and make a food blog on space twitter

**Comment by Fox-McCloud** [comment]
@optimumtact 

Actually, it can occur--it's happened to us twice---but...still, that's two times too many.

**Comment by optimumtact** [comment]
Hate to say, but this will likely not affect any of the issues relating to camera's, it's merely to prevent the infinite loop.

**Comment by Iamgoofball** [comment]
@optimumtact 

this might have broken foam

**Comment by AndroidSFV** [comment]
Foam uses getFlatIcon?

**Comment by optimumtact** [comment]
it would be pretty funny if it did

**Pull request merged**
