### PR TITLE
Removes glitter

### LINKED ISSUE #41910: Glitter prevents interaction with the floor now
https://github.com/yogstation13/Yogstation-TG/issues/3820

Since glitter was changed to use the new gas sprite, it's impossible to click the tile underneath, since unlike gas, glitter isn't clickthrough

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
del: Removed glitter
/:cl:

It doesn't even look like glitter, the joke is over.

Closes #41910

### CODE REVIEW

**Comment by 81Denton** [comment]
That's kinda lazy instead of adjusting the sprites

**Comment by ExcessiveUseOfCobblestone** [comment]
you clean it up with a mop don't you? Just remove mouse opacity to troll the n00bs

**Comment by k-k-karma** [comment]
his atmos sprite changes were apart of his master plan to ruin clowns everywhere

**Comment by nicbn** [comment]
Everyone knows good clowns use real plasma.

**Comment by nicbn** [comment]
Also the sprites used to be the old gas ones (which actually looked like glitter), but someone changed it

**Comment by SpaceManiac** [comment]
The new sprites don't look like glitter so the joke doesn't work anymore.

Glitter could be made clickthrough in a couple different ways but I think removing it makes the most sense honestly.

**Comment by Grazyn** [comment]
The purpose of toys is to make pranks through items that look like hazards or syndicate stuff, just rename it to "colorful powder" instead of removing fun

**Comment by nicbn** [comment]
It's not that fun, come on
Everyone already got used to it

**Comment by ExcessiveUseOfCobblestone** [comment]
- Change the Icon

- Make it Clickthrough

- Change name to powder or something

It's a cute feature and I've been fooled by it before (when glitter = gas). I don't really want to see it removed.

**Comment by optimumtact** [comment]
This can be improved, not removed. It doesn't seriously impact peoples QoL that the thing doesn't act like how it's named.

**Pull request closed without merging**
