### PR TITLE
Adds petting for real

### PR DESCRIPTION
**Pull request by Thunder12345**
:cl: Thunder12345
fix: It's ACTUALLY possible to pat people on the head now
/:cl:

### CODE REVIEW

**Comment by RemieRichards** [comment]
AWOOSMUG

**Comment by GunHog** [comment]
What is that girl's name? I must know for reasons of petting.

**Comment by RemieRichards** [comment]
Momiji Inubashiri
She's a wolfgirl.
and "Inu" means dog.

**Comment by ShadowDeath6** [comment]
Oranges' abuse of power meme >>>>> head pat anime meme

**Comment by Iamgoofball** [comment]
holy shit

# trying to add this feature as a """bugfix""" after it's been denied 3 times is fucking stupid

@optimumtact please close
@Cheridan please apply git ban

**Comment by RemieRichards** [comment]
@Iamgoofball oranges isn't a maintainer anymore.

**Comment by Iamgoofball** [comment]
What retard thought that was a good idea?

**Comment by RemieRichards** [comment]
@Iamgoofball himself, for pulling that stunt with the previous PR of this.
(he "merged" it (hence why this is being considered a "fix"), but just before he did he used the "Enabled edits from maintainers" feature to remove all of the PR's content and just add one of his meme comments instead)

**Comment by Iamgoofball** [comment]
@RemieRichards 
why is it not OK for him to meme on an obvious meme PR?

**Comment by Iamgoofball** [comment]
i'm forking from tg, this retarded shit is done

**Comment by RemieRichards** [comment]
Because it wasn't a meme, also goof just stop, you've dragged this joke through the mud way too far now.

**Comment by Iamgoofball** [comment]
you fired one of the few maintainers merging PRs because he meme'd on some stupid assholes PRing something that had been denied 2 times previously

**Comment by RemieRichards** [comment]
I mean, I didn't, I wasn't even there, you might be meaning "you" as in coderbus here, but since i'm the only one talking to your right now I figured i'd cover my bum.

**Comment by Iamgoofball** [comment]
i mean you as in coderbus, sorry for that meme confusion

**Comment by Kraseo** [comment]
🏌               ⛳

**Comment by Iamgoofball** [comment]
box in one

**Comment by TheColdTurtle** [comment]
wholeinone

**Comment by feemjmeem** [comment]
> @Iamgoofball wrote:
> i'm forking from tg, this retarded shit is done

bye~

i don't know why all of this is so controversial but i'm all for patting people on the head

**Comment by PKPenguin321** [comment]
oranges got removed over memeing on a meme PR?

**Comment by GunHog** [comment]
@PKPenguin321 I do not make "meme" PRs. I never have made a "meme" PR. Every PR I post is with the intent that it be merged. 

I did not know the depths of drama this would produce.
I did not know that I was opening the door to the salt vault.
**I did not know the magnitude to which people would react.**

I. Did. Not. Know. This. Would. Happen.

**Comment by feemjmeem** [comment]
people (goof, apparently oranges) clearly have very strong feelings about patting which were heretofore unexpressed

**Comment by optimumtact** [comment]
I thought it was funny

**Comment by Grazyn** [comment]
I for one am looking forward to goof-fork with free guncrafting and unhinged frying

**Comment by optimumtact** [comment]
20x Deep fried crafted guns

**Comment by PKPenguin321** [comment]
Wait, the petting PRs aren't meme PRs??
?????

**Comment by GunHog** [comment]
Mine was not. This one is likely not, as it contains the code I originally intended to have merged. The others are most likely memes, however.

**Comment by PKPenguin321** [comment]
What the fuck guys

**Comment by optimumtact** [comment]
You thought it was a meme?

**Comment by PKPenguin321** [comment]
Yeah I had no idea any of these were remotely serious, seemed too plain stupid + it was denied before which is a red flag

I can't believe any of this happened hahaha

**Comment by dannno** [comment]
free oranges

**Comment by PKPenguin321** [comment]
The erroneous tag, misleading titles, and multiple duplicate PRs opened at once are also big indicators

That and how head patting is already a meme on its own

How is this not a joke

**Comment by Thunder12345** [comment]
Not erroneous, petting is in the change log and not functional in game, sounds like a bug to me

**Comment by PKPenguin321** [comment]
See what I mean??

**Comment by ShadowDeath6** [comment]
close the pr for thunder emoji'ing his own post

**Comment by Thunder12345** [comment]
I was actually emoji'ing oranges emoji'ing of my post

**Comment by Arianya** [comment]
My patting PR was a meme, but it seemed reasonable at the time.

**Comment by Arianya** [comment]
Also MERGE CONLIIIICTS

**Comment by optimumtact** [comment]
The patting is no longer in the changelog and the comment was removed

**Comment by optimumtact** [comment]
@Cheridan @KorPhaeron you'll have to decide on this one

**Comment by optimumtact** [comment]
@Cheridan @KorPhaeron pls

**Comment by Arianya** [comment]
just do it

**Comment by ShadowDeath6** [comment]
>commenting on the pr
>not leaving it in pr limbo for the rest of eternity

**Pull request merged**
