### PR TITLE
Removes disc station

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Broken, not being maintained, maintainers asked for it to happen.

Unless @Strathcona wants to come back and maintain it (or they can always re-add it in the future when they have time)

### CODE REVIEW

**Comment by tkdrg** [comment]
Don't forget to remove _maps/DiscStation.dm

**Comment by KorPhaeron** [comment]
@tkdrg 

All gone now

**Comment by Strathcona** [comment]
Sounds good. I'll try again with another map when I get around to it. If there's a list of issues somewhere, that'd be helpful.

**Comment by KorPhaeron** [comment]
@Strathcona 

Not exactly sure either since it isnt in rotation. I remember that those big halls had almost no airlocks or firelocks though, so one hole would depressurize the whole station

**Comment by Shadowlight213** [comment]
There were design issues with the airlocks as well. There was only a single door seperating maint from space rather than a double door airlock. That made maint get depressurized a lot.

**Pull request merged**
