### PR TITLE
Changes the announcement of extended to be on the Status Report

### PR DESCRIPTION
**Pull request by Arianya**
:cl: Arianya
tweak: When extended is picked in secret, it will now only notify command staff of such through the paper report. Stationwide announcements and security level will behave like other secret modes.
/:cl:

The station announcement now behaves as it does in other secret modes, but the Status Summary (the paper that it prints out) will have a special message denoting the fact that there are no antagonists.

This should help a key concern of some people with extended (the crew preparing for antags that will never come) while also dissuading some of the more questionable behaviour that comes from people getting a woop woop siren telling them its extended by shifting the planning of what to do that round to command staff. Also allows for captain events without worrying about Johnny Tator busting in with a esword.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1: literally undos the whole point

**Comment by Iamgoofball** [comment]
if this gets merged every time I'm captain I'm going to hide the real status summaries and say it's extended every time to prove why this PR is cancer as fuck

**Comment by Arianya** [comment]
The current method of announcing it isn't working as intended, because per Kor's PR

> Extended mode now has a special command report that tells you the round type. This is to let people know they have time to start on large scale projects rather than milling about waiting for antagonists to attack.

As discussed on the forums, this is leading to people behaving questionably and shouting for the shuttle to be called while people actually interested in large scale projects get shouted down, plus (anecdotally) people behaving in ways that would be bwoinkable in a standard round.

This change lets the Captain engage in events, the CE engage in autism forts, Science to build telescience, etc. and at their discretion share the report with others/the whole station if they thinks thats the best plan.

If you want the report to be more durable, @Iamgoofball, we can just have it sent as a PDA message to all the heads at the same time.

**Comment by Shadowlight213** [comment]
I've seriously seen a massive increase in general greytide with announced extended.
It's like the shittery that used to sort of build up and happen in extended rounds before due to the tension of nothing happening, but just shifted up to literally right after the announcement occurs.

**Comment by ExcessiveUseOfCobblestone** [comment]
Doesn't this just encourage to remove extended from rot altogether?

If the [assumingly majority of the population, othrwise these 1 or 2 people would just be banned] don't want to play extended, then why are you going to force them to?

**Comment by Arianya** [comment]
@ExcessiveUseOfCobblestone Opinion still seems relatively split between "keep extended hidden", "announce extended", "remove extended from secret", though theres not been a poll to my knowledge. (There's one linked in Kor's PR but it leads nowhere)

As the icon notes, this is a _tweak_ to see if people will behave more in line with expectations if only key people are informed.

**Comment by KorPhaeron** [comment]
In my experience the captain/HoS are the ones agitating for a shuttle call in the first place in the absence of anyone to shoot.

**Comment by KorPhaeron** [comment]
Huh, the polls broke

**Comment by Iamgoofball** [comment]
@Arianya You know, if people don't like playing extended so much they demand shuttle calls when they realize it's extended, maybe we shouldn't force them to play it?

**Comment by Iamgoofball** [comment]
@Shadowlight213 maybe it's because the game isn't going to create any conflict(the core of storytelling) for them, so they make it themselves

**Comment by Arianya** [comment]
@Iamgoofball You could make the same argument about conversion antag types that force people to play rev/cult/clockcult/gang

As stated, there are people who like extended, people who like extended but want to know its extended, and people who hate extended and want it gone. This PR mainly affects the middle category, but discussion of the removing it entirely should probably be in a forum thread as opposed to here, since this PR isn't removing it or adding it back in.

**Comment by Shadowlight213** [comment]
@Iamgoofball to replace extended, you should add the old deathmatch gametype where it just makes everyone a traitor. Or the "Corporate restructuring" one where it just shifts who is valid constantly.
Or disable ahelps during extended. Server rules are still server rules.

**Comment by ExcessiveUseOfCobblestone** [comment]
My thing is if it's one or two people then we [admins] can speak to them.

 If it's half the station constantly, then you just need to remove the gamemode from rotation.

I don't blame HoS for wanting to leave though, I was warden one extended round and the arse of the HoP wouldn't let have all/all of the needed access to autism up the aux base.

**Comment by Arianya** [comment]
This is pure opinion, but "the HoP is being obstructive to a station project" sounds like a thing that would be an IC issue that would be interesting to resolve, and is one of those conflicts that would fill the supposed void that extended represents.

Though, as I say, its hard to gauge whether the issue is people having a problem with extended or just that extended presents a heightened potential for greytiding/general mischief because sec is more wary of being harsh with people when there's no possibility of antags.

**Comment by KorPhaeron** [comment]
Headmins can put normal extended back if they want this announced. Can take a new server poll on it soon if you'd like

**Comment by Arianya** [comment]
@KorPhaeron I think a new server poll/the old one would be very useful in shaping what we do with extended, yes.

**Pull request closed without merging**
