### PR TITLE
Fixes wet floor scaling

### LINKED ISSUE #36661: Wet floors dry too quickly
**[Round ID]:** 85425

**[Reproduction]:** Wet a floor with any water source, observe as the wet tile dries itself in roughly 2 seconds.

Most likely related to #36130. 
@kevinz000 

Assuming I'm reading the code right, it looks like floor tiles wetted by normal water from a mop/shower/etc should be wet for 15 seconds, and then have that time sped up by ([TEMPERATURE IN CELSIUS] * 0.1) seconds.

So in 20 degrees Celsius, this should be lowering the time to dry from 15 to 13. Instead, things appear to be drying in 2 seconds.

Wasn't able to test this in non-20*C enviroments.

### PR DESCRIPTION
**Pull request by silicons**
@Arianya 
Wet floors are now scaled to the time of their last process (more accuracy), and the dry time at room temperature is no longer doubled.
However, this also means that the drying effect of ALL temperatures ranging from 0 to 100C on wet floors has been cut by half, because I don't want the old inconsistent switch statement back so slap a balance tag on this too I guess?
Fixes #36661

### CODE REVIEW

**Comment by Arianya** [comment]
What's the average floor drying time post this? At 20*C etc.

**Comment by ShizCalev** [comment]
#36569 
> Any kind of tweak/balance change

**Comment by Arianya** [comment]
@ShizCalev This is basically just restoring status quo before #36130 broke the entire drying system, without this fix wet floors dry far too fast, I'd argue this one should get an exemption from the freeze.

**Comment by Tlaltecuhtli** [comment]
it is a fix

**Comment by kevinz000** [comment]
@ShizCalev the water nerf was unintentional my pr being a refactor wasn't meant to change it but it did so now this is fixing it

**Pull request merged**
