### PR TITLE
[READY] Overhauls Security on IceBox

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This PR adds Multi-Z functionality to Security on IceBox by completely remaking the department. In the process, I moved the lavaland gulag to the bottom to make it more consistent and give miners more space to mine in (while also fixing its terrain generation).

The main features of the new design are as follows:
1. Showcase of the plasma lakes for the entrance, sides, and execution chamber
2. Utilization of multi-z mechanics for the brig, armory, courtroom, and perma (Use that look-down hotkey, kids!)
3. Better use on IceBox wastes, letting the wastes contribute to security's raidability in both positive and negative ways
4. Mik's Maint Bar

SDMM pictures:
image
image
image

Cool Cells:
image

Armory:
image

Brig Entrance:
image

The Bear Cave:
image

Execution Chamber:
image

Detective's Office:
image

Courtroom:
image

## Why It's Good For The Game

Adds life to and brings security up to the same standards as the rest of the departments. Adds some extra interesting mechanics to the department for players to fool around with (Courtroom Trapdoor as an example). Gives us some divergent design changes to measure up against our playerbase (such as multi-z armory and a more prevalent plasma pit).

## Changelog

:cl:
add: IceBox Station has a new Security Department
/:cl:

### CODE REVIEW

**Comment by CMDR-Gungnir** [comment]
This is really cool but having all of the entrances (and the entirety of it, itself) of the brig just...hanging over the plasma lake is an instant nightmare, no no no no no that's a HORRIBLE idea.

**Comment by Son-of-Space** [comment]
> This is really cool but having all of the entrances (and the entirety of it, itself) of the brig just...hanging over the plasma lake is an instant nightmare, no no no no no that's a HORRIBLE idea.

The maintenance entrance is not over the plasma lake, and you can make an entrance into the brig from the lower public walkway through visitation if the upper area is bombed.

**Comment by CMDR-Gungnir** [comment]
> > This is really cool but having all of the entrances (and the entirety of it, itself) of the brig just...hanging over the plasma lake is an instant nightmare, no no no no no that's a HORRIBLE idea.
> 
> The maintenance entrance is not over the plasma lake, and you can make an entrance into the brig from the lower public walkway through visitation if the upper area is bombed.

Fair- but as absolutely awesome as it looks, I really think the place most likely to get Spite Bombed is probably not the ONLY department that should be over a plasma lake. I'm a little spooked.

**Comment by Zargoar** [comment]
Please give the Law office a few pairs of sunglasses.

**Comment by LemonInTheDark** [comment]
I will miss the old courthouse, but this is amazing

**Comment by Son-of-Space** [comment]
> Please give the Law office a few pairs of sunglasses.

Sorry, powergamer. No.

**Comment by Zargoar** [comment]
> > Please give the Law office a few pairs of sunglasses.
> 
> Sorry, powergamer. No.

Give each lawyer a pair. I typically play lawyer less on maps without the thick sunglasses.

**Comment by Zargoar** [comment]
Oh another thing consider adding more graffiti to perma.

**Comment by YakumoChen** [comment]
Actually hilariously over-secured tbh. 

Most of the important rooms are a nightmare to break into by virtue of their location alone. There's no sane or easy way to break into the armoury, the prison, the gear room is an rwall brick (no windows or weak points). About the only place that looks remotely antag-friendly is the HoS office.

**Comment by Son-of-Space** [comment]
> Actually hilariously over-secured tbh.
> 
> Most of the important rooms are a nightmare to break into by virtue of their location alone. There's no sane or easy way to break into the armoury, the prison, the gear room is an rwall brick (no windows or weak points). About the only place that looks remotely antag-friendly is the HoS office.

Play on it as warden a few times and you will quickly find out how hilariously wrong you are.

**Comment by YakumoChen** [comment]
I see the armoury is two-level now but the only break-in point is clear as day in view from the warden's office on the top level. As is the HoS office. 
If you intend prison escapes to be from a public hallway and two windows, I'm not sure what you're smoking to think that's a good idea.

**Comment by Serxule** [comment]
this looks like overkill, 2 small bridges, and a maintenance tunnel being the only normal way to get into sec? along with being nearly at the top of the map, along with the random bear cage (seriously why is that even there), perma being fairly easily escapable, same with normal cells, armory is now incredibly easy to get into (due to likelyhood of no one being/watching down there), HoSs office is now harder to get into compared to the majority of maps, the unnecessary plasma river (easy trolling of security)

**Comment by Son-of-Space** [comment]
The bear cave is there so people can't just walk up on the cells and or warden's office and RCD in. Needed a little bit of challenge ; )

**Comment by Serxule** [comment]
ok but 
img-1019555-eminem-5-musicas-do-eminem-que-so-os-maiores-fas-conhecem-ca_widelg

**Comment by Son-of-Space** [comment]
First you don't like the bears and now you want me to surround that side with bears. Settle on what you want from me. /s

**Comment by Serxule** [comment]
Screenshot_2066

**Comment by JohnFulpWillard** [comment]
As a Lawyer enjoyer (compared to Detective fan), I have a few complaints for the Law office;
1 - I'd like to see law office and detective office swapped, detective is sec so they should be closer to the Brig.
2 - Regular windows makes it piss-easy to break into and I already hate how many people greytide the law office. The only thing deterring people to break into it is the lack of sunglasses, a problem no other map has.
3 - I feel it is way too cramped for what's supposed to be a service area, they sit next to the disposal bin while their records console is out of the way, expanding it 1-2 tiles would really make it easier to expand it in-game with decorations and such.

**Comment by Son-of-Space** [comment]
> Measured Response from JohnFulpWizard

I've taken what you've said into account and here is my redesign:
image

**Comment by Son-of-Space** [comment]
MapDiffBot why are you so persnickety?

**Comment by JohnFulpWillard** [comment]
> I've taken what you've said into account and here is my redesign:

That is way better, thank you for this

**Comment by MrMelbert** [comment]
Damn pretty. Some notes:

- Don't look like no pod airlock. They're also all backwards
image

- This one's sideways
image

- There is very little buffer between mob spawn territory and the permabrig's windows and no chasms to protect them, meaning bears and wolves will bust into perma very often

- Court is like, really tiny, which is kinda a shame. You can't really pack many people inside

- Beepsky doesn't leave their home due to not having enough access

- My personal opinion but since these are hallway stairs you should add some openspace overhead
image
(Chemistry for example)
image

- This external airlock is useless, shuold be put on the opposite side
image

- I can't help but feel like these grass sections are a little out of place. IMO the section on the right could be redistrubuted a bit to give a 2x2 walkway into the armory + some openspace over the stairs (below). McGriff could be put in the left section as well, that could be cute
image

**Comment by Son-of-Space** [comment]
ty for the feedback Melbert. I will work on all those things. Only thing I can't fix very much is the courtroom. There's a viewing area above to watch from as well. I can see what I can do about making that courtroom space a little more cozy instead of barren so it being tiny isn't an issue.

**Comment by Son-of-Space** [comment]
forgot to mention in the commit message that I moved EVA out of the way a little bit so players don't have to go through the medical area. I thought I couldn't do it at first but after further review decided it was worth not having that lip be something you could move around.

**Comment by Swiftkor** [comment]
Looks good but I'm a tad disappointed we're not getting genpop brig. Having perma prisoners and temporary prisioners interact and giving temporary prisoners something to do is much more interesting than shoving criminals in a box where they tab out for a few minutes. Since icebox is a multi-z station it seems like it would be perfect for a tram style genpop layout.

**Comment by Son-of-Space** [comment]
> Looks good but I'm a tad disappointed we're not getting genpop brig. Having perma prisoners and temporary prisioners interact and giving temporary prisoners something to do is much more interesting than shoving criminals in a box where they tab out for a few minutes. Since icebox is a multi-z station it seems like it would be perfect for a tram style genpop layout.

I don't particularly agree with the idea that genpop is better than the cells, but that discussion is out of scope for this PR. I am perfectly content allowing Tram to keep its unique, experimental features so that it stays a characteristically valuable map.

**Comment by BrandonSmith6** [comment]
Problems I have,image Guantanamo bay styled entrance

Someone may argue that you can go through maints but think again...
image


Another person may say you can break through the back image

Think again there is a lava moat and a bear pit. 


I think icebox needs a sec revamp but turning it into an impenetrable castle is not realistic.

**Comment by Son-of-Space** [comment]
There are plenty of other ways to invade this brig, namely not the ones that require the most effort, that you've neglected to highlight.

For information, this came directly off a warops round where the flukies decided to invade the brig via the bridge. It was awesome https://cdn.discordapp.com/attachments/705679956021215264/958166899974369290/unknown.png

Players were very happy about it after the round was over, and so was I. Loads of fun trying to breach this space and afterwards the bridge after two marauders came in and absolutely cracked the egg.

**Comment by BrandonSmith6** [comment]
And holding cells on a completely different z level right next to perma that are also paired with more doors and lava moats to prevent approaching from the outsideimage

**Comment by LemonInTheDark** [comment]
Step one:
Take maint to this area 
image

Step two: 
Place one floor

Profit

**Comment by Bawhoppen** [comment]
Okay this is pretty good. No hard feelings. Even if I'll be sad to see my old prison go away. 
Only feedback is that some of the flooring decal is too dark. Feels a bit too much. I recommend classic floor tile colors, to fit with Box's motif more.

**Comment by Son-of-Space** [comment]
> Okay this is pretty good. No hard feelings. Even if I'll be sad to see my old prison go away. Only feedback is that some of the flooring decal is too dark. Feels a bit too much. I recommend classic floor tile colors, to fit with Box's motif more.

The idea of your prison lives on in the rooms and ideas.

I wanted to use some of the new flooring to hopefully give people some inspiration down the road. Downstairs keeps the theme of the rest pretty well, and I think having it "separated" gives the ability to have the theme slightly different without clashing with the rest of the map.

**Comment by BrandonSmith6** [comment]
> > Okay this is pretty good. No hard feelings. Even if I'll be sad to see my old prison go away. Only feedback is that some of the flooring decal is too dark. Feels a bit too much. I recommend classic floor tile colors, to fit with Box's motif more.
> 
> 
> 
> Your prison lives on in the rooms and ideas it has spread.
> 
> 
> 
> I wanted to use some of the new flooring to hopefully give people some inspiration down the road. Downstairs keeps the theme of the rest pretty well, and I think having it "separated" gives the ability to have the theme slightly different without clashing with the rest of the map.

What do you think about the concerns I have?

**Comment by BrandonSmith6** [comment]
You literally analyzed this to find the only way. It should not be that you have to go to such extremes> Step one:
> 
> Take maint to this area 
> 
> image
> 
> Step two: 
> 
> Place one floor
> 
> Step three:
> 
> Profit
> 
> 
> 
> It's nice

**Comment by BrandonSmith6** [comment]
Sec needs a sliding door in maints for mail

**Comment by BrandonSmith6** [comment]
I propose adding a window here image

**Comment by MrMelbert** [comment]
- Warden's office could use a telescreen that shows JUST the cells / perma-brig, it's a bit difficult to keep an eye despite the glass floors 
- wow there's a lot of rubbershot in the armory huh
- is security's only cyborg recharging station in the lower armory? I feel like one should be in the equipment room/office, or EVA room
- Maybe have a door here so sec can get into visitation without walking all the way around?
- 
image

- sneaky genturf

image

- stacked table

image

- none of these airlocks are cycling, which means people'll just leave them open

image

**Comment by Son-of-Space** [comment]
There's an issue right now with the cycle helpers causing them not to work. Something about them running on LateInitialize?

I think adding a door would make that area a little too susceptible to breakins and too easy to respond to issues on the outer part of the cells. Part of the appeal of assaulting from that area is it takes a lot of travel time to move over and stop something. I want to encourage players to think of ways they can lengthen that response time further when they go about invading that area.

Rubbershot is the same amount that was on box before, didn't edit that. Reduced to 3 boxes.

Added the cameras on both sides of the hallway and lower visitation to the prison network and gave the warden a prison monitor (Doh!)

Removed genturf and extra table.

**Comment by Son-of-Space** [comment]
Changed the bottom level exterior windows to match the window style for the rest of level 2. Changed around some flooring to avoid running cables through walls. Added windows to perma kitchen and re-ed.
image

**Comment by Bawhoppen** [comment]
All is well. I'm glad my design inspired the rest of the redesigns across the maps. Either way though, tiny little detail here that's obscure: some of the toilets should have an open cistern to brew pruno. The issue is the sprite is the same, so it's such an odd detail that I think few people know about it. (You may have actually done this already, mentioning it if you haven't yet is all)

I was meaning to rework toilets a bit, but haven't gotten around to it yet.

**Comment by notfrying1pans** [comment]
I prefer a larger court room. Court sessions are incredibly rare but are incredibly funny if done

**Comment by Zargoar** [comment]
I just noticed that the execution pit lacks atmospherics or heat. Is this by design?

Also I think it would be nice for the lawyer to have access to the trial transfer doors to save them from having to go the long way around to SEC every time.

**Pull request merged**
