### PR TITLE
Tactical dickpixel™ removal

### PR DESCRIPTION
**Pull request by Incoming5643**
Modifies the fitted var to allow for clothing that looks good with female uniform generation save for the dickpixel™, FEMALE_UNIFORM_TOP.

Reclassified uniforms as needed. Most uniforms can now get some sort of variation without any sort of visual weirdness.

Uniforms with "enhanced" chests continue to be excluded for that very reason, ironically.

### CODE REVIEW

**Comment by Chocobro** [comment]
rip dixel
:+1:

**Comment by RemieRichards** [comment]
Privilege - [X]

**Comment by paprka** [comment]
this doesn't fix people randomly turning into men though

**Comment by Incoming5643** [comment]
No this isn't a fix for that, that's a whole 'nother thing.

Anyway Dixel/Dickpixel isn't completely gone anyways, anything with FEMALE_UNIFORM_FULL still has it

**Comment by fj45** [comment]
"Uniforms with "enhanced" chests continue to be excluded for that very reason, ironically."

What?

**Comment by Incoming5643** [comment]
There's a few old pieces of clothing that are actually sprited to make chests look bigger that can't be used with this because pixels are removed from "within" the outfit. The most seen offender is probably the nurse's uniform.

(also yes that does mean it gives the dudes boobs too)

**Comment by phil235** [comment]
merge conflict

**Pull request merged**
