### PR TITLE
[WIP] Reverse-Engineering and Autolathe tweaks

### PR DESCRIPTION
**Pull request by octareenroon91**
Fix:
- Add feedback when loading a design to the autolathe.

Feature:
- Add logic so an object can be reverse-engineered under some circumstances. For now, the object will require a "self" or typepath entry in its origin_tech .

### CODE REVIEW

**Comment by GunHog** [comment]
You could...let autolathes connect to the research network, thereby making the disk thing entirely obsolete....

**Comment by MMMiracles** [comment]
@GunHog Yeah but its more funny to imagine things like cargo breaking into RnD to steal research for their own cargonia needs.

**Comment by Jalleo** [comment]
@MMMiracles but that spare R&D console is probably more likely to get stolen with a single disk to do that instead.

**Comment by Ultimate-Chimera** [comment]
What exactly does this do?

**Comment by octareenroon91** [comment]
>Kill a Russian simple_animal
>Loot his bolt action rifle
>Use up the ammunition he had.
>Now what

The casing is so simple, it's absurd that you can't make more at will. Defining the design so you automatically get it in the autolathe or protolathe is also absurd. So, how about a design that you get when you get the rifle, and no sooner? I am trying to make that possible.

**Comment by octareenroon91** [comment]
need to cherry-pick 8b5ffe47796e457eeed287d6157ee8375a7f8b4b I guess

**Comment by KorPhaeron** [comment]
Are you going to finish this?

**Comment by octareenroon91** [comment]
>Are you going to finish this?

...someday.

**Pull request closed without merging**
