### PR TITLE
Adds Bluespace artillery button. 

### PR DESCRIPTION
**Pull request by tedward1337**
Adds a new button for admins with +fun to push. Sends bluespace artillery to the station at the whim of God. Can also be used to right click on mobs and hit them that way.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
needs an auto-BSA button on incoming adminhelps and prayers for when you get those /really/ bad ones.

**Comment by WJohn** [comment]
We actually have that for centcomm messages (or at least for nuke code requests). Of course, it'd have to have a prompt that is VERY CLEAR about what it's going to do.

**Comment by RemieRichards** [comment]
I hate this version of the BSA, sometimes you want to punish someone without scoring a direct fucking hit on where they're stood.

It's why I always spawn the BSA Console instead, it targets AREAs instead of individual (the effect is also bigger I believe)

Only slightly relevant to this PR so, yeah.

**Comment by Dorsisdwarf** [comment]
the admin BSA artillery verb has a confirmation check built-in, as far as I could tell when making nuke codes.

**Comment by Miauw62** [comment]
Yeah, there should be a button to BSA an area instead of a person.
Op 26-mrt.-2015 14:12 schreef "Dorsisdwarf" <notifications@github.com>:

**Comment by Jordie0608** [comment]
Unless you mean calling BSA on everyone in an area, that'd just be dropping a bomb.

**Pull request merged**
