### PR TITLE
Adds an award for the HoP to give

### PR DESCRIPTION
**Pull request by MadoFrog**
## About The Pull Request
Adds _the head of personnel award for outstanding achievement in the field of excellence_ as a medal the Head of Personnel can award.

## Why It's Good For The Game
The service department's efforts (which are, doubtless, integral to the station's functioning) have gone unnoticed for far too long. This pull request would add an award to be given to those most valuable crewmembers.

## Changelog
:cl:
add: the head of personnel award for outstanding achievement in the field of excellence
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
seems useless to give a medal box just for 1 medal

**Comment by MadoFrog** [comment]
The QM has a medal box for just one medal. 
Regardless, I'm not sure why you'd want to leave such a valuable award unprotected and exposed to the elements.

**Comment by wesoda25** [comment]
Give the HOP 3 of them, there are many unspoken heroes about the station.

**Comment by Swagile** [comment]
> 
> 
> Give the HOP 3 of them, there are many unspoken heroes about the station.

Agreed, no idea why its only 1 medal when HoS gets 3 he can give out.

**Comment by MadoFrog** [comment]
I could add some more if you'd like, but I get the feeling that having more than one would dilute the ~~joke~~ prestige of receiving such a highly sought after award.

**Comment by Swagile** [comment]
> 
> 
> I could add some more if you'd like, but I get the feeling that having more than one would dilute the ~joke~ prestige of receiving such a highly sought after award.

Chef making a Cak, Bartender making gargle blasters, and Cargo being able to afford the bicycle is no joke, mister..........

**Comment by YakumoChen** [comment]
Cargo isn't a service job

**Comment by dee-dubya** [comment]
>not immediately looting the Captain's medal box with your freshly minted AA card and giving those out instead

This seems like a good PR. Don't think they'd need more than one medal, since the QM has their own medal box for cargo shit.

**Pull request merged**
