### PR TITLE
Human nightvision

### LINKED ISSUE #17389: Ghost HUDs are broken
They dont appear when you toggle them

### LINKED ISSUE #19248: orbit debris action button doesn't show when you reconnect while ghost.

### PR DESCRIPTION
**Pull request by MrPerson**
#:cl:
add: Humans can now see in the dark slightly around themselves.
/:cl:

Humans can see in the dark a little bit around themselves. While I should probably extend this to other mobs, I was in a hurry so humans only for now. Extending this is trivially easy anyway.

What you see:
image

Reality:
dreamseeker_2016-11-18_00-41-51

Forces clients onto 510 and suggests upgrading to 511 in the default config. The suggestion is still commented out but forcing clients to 510+ is mandatory.

Ghosts and brains now actually render the default HUD instead of skipping the whole process. Dead mobs will show their fullscreens. All of the existing screens will skip rendering to dead mobs to keep the existing behavior of not rendering the brute/blindness screens.
Fixes #17389
Possibly, but probably not, #19248 need to test

### CODE REVIEW

**Comment by MrStonedOne** [comment]
clients are already forced to 510 on the server https://tgstation13.org/parsed-logs/sybil/config/config.txt

and we already use 510 only features

**Comment by MrPerson** [comment]
Yeah but the game was still playable without them. With this if a 509 client tried to play they would just see a white screen.

Still point taken

**Comment by MrStonedOne** [comment]
as it stands, i think byond is enforcing 510 clients because we use certain 510 features, so it wouldn't even let them connect

**Comment by GunHog** [comment]
This makes me wish we had one of the other codebases' smooth lighting systems. Good change though, I hope someone extends it to playable simple_mobs as well.

**Comment by FantasticFwoosh** [comment]
I downvote this idea, it makes hiding in the shadows trivial, since the light off a small source like a PDA does functionally the same job & will be amplified with the night vision.

Real pro SS13'ers can navigate the station maint from reflexive memory alone in pitch black.

**Comment by Shapsy** [comment]
Yeah I dunno, I always liked the tradeoff of having to reveal yourself to other people with your PDA light if you wanted to see around you, made things much more tense when the lights went out

**Comment by XDTM** [comment]
I'd allow seeing your own tile at least, so you can tell if you're moving or smacking into a wall when the screen is black

**Comment by Aloraydrel** [comment]
But why?

**Comment by Durkel** [comment]
Wearing thermals and having your lights off has the same effect, which allows you to hunt in the dark without letting others see you. I don't think we really need to expand the view range of those in the dark, and it's not like you don't already spawn with a light source.

**Comment by Fox-McCloud** [comment]
Definitely how it used to be.

Could be interesting.

**Comment by FantasticFwoosh** [comment]
Super good point. @Durkel 

PDA is clumsy to clutch operate but its nearly always with you, when you have a better on/off switch light object (a sectorch attached to a helmet or a fire/construction helmet) its more of a play to turn your light off with a quick click and go hide.

> It also makes clicking your surroundings too powerful, given that in current game very very low light levels you can atleast alt or right click to get a concise detail of what you are looking at which you can't do in pitch blackness.

Not to mention final nail in the coffin for any antag type/powers that rely on darkness (everything about shadowling/xeno stealth) as they could never be re-imbursed or reworked reliably with this PR in place.

> What are blind people supposed to do huh?

On the contrary @Fox-McCloud the small localised radius has never been as strobe light bright as this, even if it is one sided. I re-instate my point that additive light like a PDA would render it void anyway.

**Comment by PKPenguin321** [comment]
kind of assblasts sneaking up on people in the dark, pretty much negates the PDA light and mesons giving a tiny amount of night vision

not super fond of it, at least for humans.

**Comment by MrPerson** [comment]
Note that to sneak up on someone in the dark, you have to be able to see them too. If anything this actually makes darkness more intense because people are no longer assumed to be emitting light when they walk around, so there literally could be someone waiting in the shadows and you'd never know.

**Comment by PKPenguin321** [comment]
>Note that to sneak up on someone in the dark, you have to be able to see them too.

which you can do with mesons or NVGs without making light

**Comment by GunHog** [comment]
Not mesons, they do not let you see people without light, unless they are also NV.

**Comment by PKPenguin321** [comment]
mesons give you either 1x1 or 3x3 nvg i forget which but either way you can sneak up on people with them

**Comment by KorPhaeron** [comment]
We used to have this for a long time

Was nice

**Comment by Kevak** [comment]
Give it to catpeople and lizards. Not baseline humans.

**Comment by Bawhoppen** [comment]
no thats dumb they're not supposed to have practical benefits, nobody should have this by default just add to the code

**Comment by MrPerson** [comment]
While I'm not going to push for this too bad if it's really hated, I would like to see a test merge so everyone (including me) can see how it goes in an actual game.

**Comment by MrStonedOne** [comment]
You talked about making it darker, I'd look at doing that, as this in it's current form would be too powergamey. People already turn up brightness and angle their monitor to see in low light that even a lighting object's alpha of 250 for them might as well be fully bright.

While you're having fun with planes and shit, I wonder if you could figure out a way to make self illuminating objects (ie, something that itself is fully bright, but doesn't make it's tile fully bright) So that we could apply that to things like the cherry of burning cigs, borg eyes, etc.

**Comment by Kevak** [comment]
I know para did that with cult constructs. Might be able to borrow their code for that.

**Comment by BeeSting12** [comment]
Instead of letting you see everything around you, how about just walls, airlocks, etc so you can tell when you're bumping into something but not if anyone's behind you. Or just go with the old way and carry a flashlight/PDA light on you. (who doesn't carry a flashlight on them at all times anyways)

**Comment by Cyberboss** [comment]
Solid downvote on this. Taking away my P A R A N O I A

**Comment by optimumtact** [comment]
Errm so what was the point/reasoning of this?

**Comment by jughu** [comment]
Time to port lifeweb player views only whats infront of him :^)

**Comment by MrPerson** [comment]
Right now, if you get stuck somewhere pitch black without a source of light, the game becomes literally unplayable. Granted everyone has a PDA light, but I wouldn't expect a new player to know that. 

I'll whip up a smaller circle of even weaker "light" and see how that looks.

**Comment by FantasticFwoosh** [comment]
> @MrPerson "This aint funny, im locked in the darkest, least fun room on the map!"

That's why you have ahelp (not guranteed) and ghost verbs to escape if you're too un-robust to get out by yourself by bashing a door (which has acting outside light on it to make it visible possibly) or call for help, given if you can guess your general location.

**Comment by Cyberboss** [comment]
Reduce it to the size of the crit/sleep vision and I'll be okay with it

**Comment by MrPerson** [comment]
I put in a smaller, darker light and updated the OP with a new picture.

**Comment by ChangelingRain** [comment]
MAKE IT ***DARKER***

**Comment by optimumtact** [comment]
Looks fine now, will merge once I have reviewed :+1:

**Comment by XDTM** [comment]
looks pretty good now

**Pull request merged**
