### PR TITLE
fixes mystical cable coils of doom

### PR DESCRIPTION
**Pull request by Bawhoppen**
Fixes https://github.com/tgstation/-tg-station/issues/13897

### CODE REVIEW

**Comment by Bawhoppen** [comment]
this time with less box killing

**Comment by KorPhaeron** [comment]
<Bawhoppen> even fathom this cable coils

Did you actually fix this? Your previous attempt at a random area of the map, and your recent IRC messages, suggest otherwise

**Comment by Bawhoppen** [comment]
it's fixed
I even tested it

**Comment by as334** [comment]
Good work Baw. I'm proud of you.

**Pull request merged**
