### PR TITLE
Adds fun 😃 to asay

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Emoji in asay! 😃 🎉🙌👏
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
wtf i like mrty now
also @lzimann is going to butcher you

**Comment by MoreRobustThanYou** [comment]
this is a serious PR because i wanna gossip in asay with 💩

**Comment by kevinz000** [comment]
because @lzimann doesnt like fun and @lzimann doesnt like emojis so @lzimann is likely going to butcher this pr?
why else would i ping @lzimann ?
👍

**Comment by MoreRobustThanYou** [comment]
🖕🖕🖕 why would you ping him reeee 👿👿👿👿

**Comment by Jordie0608** [comment]
dont

**Comment by MoreRobustThanYou** [comment]
24 hour rule, @lzimann! this is a SERIOUS PR!!

**Comment by Bawhoppen** [comment]
we shouldn't encourage the dumb idea that asay is for anything other than serious discussion

**Comment by kevinz000** [comment]
>asay is for serious discussion

lol nonadmins

**Comment by Bawhoppen** [comment]
Having your name on a txt file doesn't give you free special privileges on the server. You're job is supposed to be to enforce the rules as needed, not to joke around amongst yourselves

**Comment by lzimann** [comment]
ok fine, this pr will still die in 24h

**Comment by Armhulen** [comment]
>not to joke around amongst yourselves

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA

**Comment by Bawhoppen** [comment]
Like I said, you're not SUPPOSED to, even if it happens in reality.

**Comment by BeeSting12** [comment]
@Bawhoppen lol

**Comment by Aloraydrel** [comment]
LooooooL

**Comment by DoctoreMad** [comment]
This PR is why Cheridan needs to come up/down form hell/heaven and remove the 24 hour rule.

**Comment by Bawhoppen** [comment]
24 hour rule exists so everyone in theory gets a chance to express support/disapproval against a PR.

**Comment by praisenarsie** [comment]
except mrty is just saying "haha 24hours you can't close it!" and doesn't express his opinion on why this should be merged.
besides this emoji thing looks better for something like our downstreams.

**Comment by KorPhaeron** [comment]
Pirou> 3f5fd6f1 KorPhaeron: <MrStonedOne> the /tg/ gestapo demands your support on #31265

The host wants it, and he is king of the admin things, so unless the code is completely awful I don't think it is reasonable to deny it. I guess we could lock it behind yet another config option

**Comment by Bawhoppen** [comment]
Deleted message detected

Conspiracy?????

**Comment by Jordie0608** [comment]
It was just kor failing an Insight roll

**Comment by Cyberboss** [comment]
See the quoted reply here

**Comment by KorPhaeron** [comment]
Jordie said that message didn't mean what I thought so I guess I'll just more directly say

It's to @MrStonedOne

**Comment by DoctoreMad** [comment]
Are you telling me the MSO wants this in or that MSO needs to see this PR
I believe the wording now implies the latter but why would he check this meme PR

**Comment by KorPhaeron** [comment]
Because he expressed interest in this PR and it's an admin side thing and he is king of the admins

**Comment by DoctoreMad** [comment]
[I can't wake up]

**Comment by MrStonedOne** [comment]
ooc emojis already exist in admin to player or admin to admin adminpms (but not player ahelps or player replies), adding them to asay isn't that far fetched.

https://github.com/tgstation/tgstation/blob/4178c209f139ad9d78eda609d539f2b24af94565/code/modules/admin/verbs/adminpm.dm#L140

**Comment by Armhulen** [comment]
just do it it's haaarmless

**Comment by Qbopper** [comment]
mso +1'd this one but -1'd the other one

god tier host

**Comment by lzimann** [comment]
meh

**Comment by Qbopper** [comment]
lzi = anti fun

**Pull request closed without merging**
