### PR TITLE
Air tanks get their own sprite, plus reset fix.

### LINKED ISSUE #31011: Air tanks issues
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)
AIR tanks (mixed air that is), use the O2 icon, which is downright confusing at best. Further, pressing "reset" sets them to 16 pressure, which will kill you if you relied on that before and didn't notice the change now.

Similarly, O2 tanks seem to start at 101 pressure, despite only needing 16.
(This is for the large tanks, by the way)

### PR DESCRIPTION
**Pull request by RandomMarine**
:cl: RandomMarine
imageadd: Air tanks (o2+n2) now have a different appearance from oxygen tanks.
/:cl:

Also fixes #31011
nutanks

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Needs inhands.

**Comment by ChangelingRain** [comment]
Also, that stripe looks weird.

**Comment by ChangelingRain** [comment]
@ausops You did these originally can you give tips

**Comment by msgerbs** [comment]
You forgot to change the release pressure.

**Comment by RandomMarine** [comment]
Didn't forget anything but the inhands. Initial release pressure is handled automatically.

**Comment by msgerbs** [comment]
It is? Because the original issue says that the don't start with the correct release pressure.

**Comment by ChangelingRain** [comment]
oh, right, back sprites too.

**Comment by RandomMarine** [comment]
@msgerbs The issue is that pushing the reset button on air and anesthetic tanks resets the default 101kpa pressure to 16kpa. They also report that oxygen tanks were starting with 101kpa but that just isn't the case in testing.

Anyway, here's some inhands and back sprites. I'll wait on pushing any commits until @WJohn gives input.
sprit

**Comment by praisenarsie** [comment]
@ChangelingRain anesthetic tank is white and red stripe. i like the blue stripe because it indicates oxygen.

**Comment by ChangelingRain** [comment]
Let me clarify; the stripe's color isn't bad, but it isn't shaded properly and thus looks weird. Compare to the other stripes.

**Comment by praisenarsie** [comment]
i see

**Comment by nicbn** [comment]
For me it looks pretty good

**Review by Cyberboss — APPROVED** [review]

**Comment by WJohn** [comment]
Yeah these look pretty good. 👍

**Comment by Cyberboss** [comment]
@RandomMarine please PR the inhands and back sprites

**Comment by praisenarsie** [comment]
because @Cyberboss is dum

**Pull request merged**
