### PR TITLE
Removes a defect concerning a simple tool in the admin toolset

### PR DESCRIPTION
**Pull request by Jalleo**
Removes a meme item that actually could be abused by bad people who find a certain way to be able to get this item. Since it would work on admins in stealth mode.

### CODE REVIEW

**Comment by Jalleo** [comment]
Travis failed to load a part of itself that is why it failed.

**Comment by AlexTheSysop42** [comment]
It's supposed to be a meme/unobtainable item, it's not like it'll cause problems except in sandbox or something (unless there's a bug that would let you get it which in itself may be punishable)

Even if someone does get it, all it does is tell them when an admin's near them, observing does not count, nor does deadminning after aghosting, nor does simply deleting the multitool.

**Comment by chesse20** [comment]
no support dont remove pls

**Comment by kevinz000** [comment]
How... is this.. an issue?
It's adminspawn only, if you're removing it the reason would be "unused item" rather than abusable?
If someone is somehow getting it they're probably able to spawn arbitrary typepaths without permissions anyways? I fail to see the point here.

**Comment by Tlaltecuhtli** [comment]
i wonder can the new experimentors mutate get it with a standard multitool?

**Comment by AlexTheSysop42** [comment]
I don't think it can. The "item change" effects are pretty rare and have whitelists, none of which include multitools, and new <path>() doesn't make random subtypes.

Actually, scratch that. There's a somewhat rare relic that has the same effects of one of the gifts from Christmas, but it almost always deletes the relic on use and has a somewhat low chance of getting anything useful, extraordinarily low for this specific item.

**Comment by Jalleo** [comment]
Okay I checked out what can be made in that list and man some things shouldn't be on there but I will mentioned it to the maintainers since that is more buggy than overpowered with most of those items.

**Comment by AlexTheSysop42** [comment]
Or you can tell me so I can change it

**Comment by Jalleo** [comment]
Infinite powercells and power cells meant for energy guns or otherwise and cyborg tools along with dangerous hardcoded paths for nades (bioterror and so forth) along with possibly certain foods that you shouldn't obtain because admin stuff (if a version of xeno and robo burger or something like that exists)

**Comment by Cyberboss** [comment]
This is a bad meme

**Comment by nichlas0010** [comment]
seriously though, why remove it?

**Comment by Cyberboss** [comment]
Literally ban bait is not a good meme

**Pull request merged**
