### PR TITLE
Pubby Whiteship Redo

### PR DESCRIPTION
**Pull request by Addust**
Reworks the Pubby Station whiteship. If there are any problems with this, let me know.

## About The Pull Request

Completely reworks the Pubbystation White Ship. If there's anything wrong, let me know.

## Why It's Good For The Game

Completely reworks the Pubby whiteship, which in its old form was kinda shit in my opinion, into a mining-themed ship. Generally just a complete replacement for the old one.

## Changelog

:cl:
add: Adds a brand new Pubbystation whiteship. This new one has mining loot and no more medbeam sadly.
del: Removed the original Pubbystation whiteship.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
compile with Tgm instead of Byond please
image

**Comment by Addust** [comment]
okay, i'll try to figure that out and update the PR

**Comment by Addust** [comment]
i actually have no fucking idea how tgm works

**Comment by Addust** [comment]
im going to test the map with my private server

**Comment by Addust** [comment]
it doesnt fucking work gah

**Comment by JohnFulpWillard** [comment]
> i actually have no fucking idea how tgm works

It’s just a setting in StrongDMM

**Comment by Addust** [comment]
i never even knew strongDMM existed. i'll attempt to rework this PR, DO NOT MERGE until then

**Comment by Sealed101** [comment]
screenshots of the shop would be nice to have
also lol can this be considered powercreep

**Comment by Addust** [comment]
i'll get a screenshot, one momento

**Comment by Addust** [comment]
image

**Comment by iwishforducks** [comment]
the ufo whiteship easily had the most swag out of all of our bland civilian whiteships. why must we de-swagify (de-soulify) it by turning it into quite possibly the most generic ship of all time?

there's ways to make the UFO better, but making it Bigger and More Like A Ship is not the solution. im remembering one time a QM had turned the inside of cargo on metastation into a docking port for the UFO due to its small size. and why remove the medibeam?

just have it so there's two side entrances to the UFO and move the consoles and tables against the walls so it feels less crowded inside of it.

**Comment by Addust** [comment]
i have another concept model of it that has the medbeam but is still expanded

**Comment by Maurukas** [comment]
This seems to be very WIP, without decal work, as well as being fairly generic. The map formatting issue is a blocker. If you need assistance and want to take another stab at this, please hop into mapping-general on the discord.

**Pull request closed without merging**
