### PR TITLE
Ports tables from Sunset Station (Sprites are credited to Quantum-M)

### PR DESCRIPTION
**Pull request by mrhugo13**
## About The Pull Request
Changes most table sprites to that of those from Sunset station (Credits to [Quantum-M](https://github.com/Quantum-M) for the sprites)

The ones changed are: Normal Table, Glass Table, Poker Table, and Wooden Table.
dreamseeker_2020-04-29_13-40-27
dreamseeker_2020-05-01_11-03-28
dreamseeker_2020-04-29_13-41-06
dreamseeker_2020-04-29_13-45-30

## Why It's Good For The Game
These look pretty neat and comfy.

## Changelog
:cl: Vondiech (Thank Quantum-M for the sprites)
tweak: Nanotrasen has decided to provide the station with tables from their Sunset-Station branch
/:cl:

### CODE REVIEW

**Comment by tmtmtl30** [comment]
feel kind of confused, perspective-wise.

**Comment by EdgeLordExe** [comment]
i like these sprites

**Comment by trollbreeder** [comment]
Error 666, no soul found.

**Comment by partyaddict** [comment]
nitpick, i think the wood tables should be darkened a bit

also no love for the reinforced table?

**Comment by Fikou** [comment]
the perspective is really weird on them and it will be really inconsistent with metal, plasteel, wood, alien alloy, all stuff having different styles

**Comment by Dorsisdwarf** [comment]
these tables look like theyre about a foot high? why?

**Comment by mrhugo13** [comment]
dreamseeker_2020-04-29_15-27-28

I'm gonna close and keep this closed until _this_ mystery of material datums get solved.

**Comment by Qustinnus** [comment]
are you sure its a material datum thing?

**Comment by Qustinnus** [comment]
image

**Comment by mrhugo13** [comment]
Yeah it seems to work completely fine with the normal metal table, but refuses to work for things like titanium, uranium, and meat.

**Comment by Qustinnus** [comment]
you can tell its stacking 2 parts of the table in one spot, @4dplanner do you maybe know if keeptogether could cause this?

**Comment by Qustinnus** [comment]
@mrhugo13 my scientists tell me that your sprites for 3-w and 4-e are just super dark at the bottom which is why the overlay and re-coloring makes it more apparent.

**Comment by mrhugo13** [comment]
Thank you floyd
dreamseeker_2020-04-29_17-25-19

**Comment by MrPerson** [comment]
Those tables are yummy

**Comment by Iatots** [comment]
They look plasticy, especially the wooden ones.

**Comment by MrDoomBringer** [comment]
they feel shorter than the current tables we have

**Review by Twaticus — CHANGES_REQUESTED** [review]
i really like these i just have an issue with the metal table color. it looks too plastic-y and would work really well for the actual plastic tables, but for metal it should be recolored to match our current metal tables.

**Comment by ArcaneMusic** [comment]
Overall I'd say it's a good change, but I will say, all the tables look like they're about 6 inches tall now.

**Comment by mrhugo13** [comment]
@Twaticus As you wish, my lord.
dreamseeker_2020-05-01_11-02-51

**Comment by Rohesie** [comment]
Pending approval by Twaticus.

**Review by Twaticus — APPROVED** [review]

**Comment by cacogen** [comment]
these suck

**Comment by MrDoomBringer** [comment]
cacogen raises an interesting point

**Comment by cacogen** [comment]
Objectively worse. Change for its own sake.

**Pull request merged**
