### PR TITLE
Adds goonbee and cult, plus improves several emojis.

### PR DESCRIPTION
**Pull request by praisenarsie**
-Adds :goon:
-Adds :cult:
-Improves :gear:
-Improves :tophat:

:cl: Frozenguy5
add: Adds a goon and cult emoji. Improves gear and tophat. (Credits to GoonStation for creating the goon bee sprite.)
/:cl:

Credits to GoonStation for spriting the bee.

### CODE REVIEW

**Comment by JJRcop** [comment]
Are we allowed to use the bee?

**Comment by Iamgoofball** [comment]
iirc yeah

**Comment by praisenarsie** [comment]
oranges told me i was allowed. i credited them where i can anyway

**Comment by awesine** [comment]
next replace how our current bees work with goonbees

seriously they're so cute

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
