### PR TITLE
Mind Control is no longer the "airlock walkies power"

### PR DESCRIPTION
**Pull request by Kierany9**
## Changelog
:cl: Kierany9
balance: A Hivemind Host's Mind Control now lasts 30 seconds regardless of the size of their hive.
balance: People under Mind Control are now slowed down slightly.
balance: Mind Control now breaks if the vessel is too hot or too cold.
balance: Mind Control now requires 18 vessels to unlock. Mass Assimilation and Induce panic are now unlocked at 12 and 10 respectively.
/:cl:

Minor Assimilation PR before I start on some big stuff, including more touchups to this power.

Hopefully this allows Mind Control to still be functional while making uses other than "walk the dude out of an airlock" viable. ~~Tested locally, they've got to be quite close to an airlock and at full HP if you want to kill someone like this. The slowdown also makes it more noticeable and easier to catch someone acting up.~~ ~~Now more functional without slowdown.~~ aaa

### CODE REVIEW

**Comment by wesoda25** [comment]
I think mind control should be normal walk speed. The fun part about it is spreading confusion, any sort of hard tell would strip the fun of it. 

Spacing seems to be just a player issue really.

**Comment by Kierany9** [comment]
>The fun part about it is spreading confusion, any sort of hard tell would strip the fun of it.

I wouldn't call this a _hard_ tell considering that walk intent is a thing, hive powers usually deal a lot of stamina damage, and that unless you're running straight at people, it's not terribly obvious. I've received a few other suggestions on how to fix mind control which I might replace this with when I do a code cleanup of the mode.

>Spacing seems to be just a player issue really.

Partially yes, but this is a relatively easy fix compared to curbing the powergamer's play-to-win attitude on TG. This is an LRP server and the gamemodes need to be coded with that in mind, from the perspective of antags and non-antags alike.

**Comment by Kierany9** [comment]
Hivemind hosts just got a massive buff in the form of #42156 as mindshield implants no longer instantly screw over every single hivemind host, since sec is nabbing one host per mindshield _at most_.

While I don't particularly want to hit 'em with a nerf, removing airlock walkies while still preserving mind control as a power is, IMO, a net positive change. Besides, Mind Control's main purpose was never supposed to be a kill power, the vessel dying could be a consequence but its intended use has always been to do things that you can't (or don't want to risk) with your current access and items.

**Comment by pizzatiger** [comment]
I feel like this is a knife into the functionality of mind control when there could be other solutions to this problem without removing the other fun things you can do with mind control. What if entering space resulted in you losing control of the mindcontrolled person because "there are no walls to reflect the signal back to you" or something

**Comment by datorangebottle** [comment]
Hivemind is already extremely weak. It doesn't need a nerf like this. A better idea, IMO, is to make people unable to use external airlocks or break windows while MC'd, in a similar way to swarmers not being able to eat apcs. Give hiveminds a fear of space or something, don't make their only good ability into garbage.

**Comment by ATH1909** [comment]
> I feel like this is a knife into the functionality of mind control when there could be other solutions to this problem without removing the other fun things you can do with mind control. What if entering space resulted in you losing control of the mindcontrolled person because "there are no walls to reflect the signal back to you" or something

Instead of doing what this PR does, make being cold (or hot?) free your victim from mind control. It'd be like slapping them or dunking them in water (maybe we should make those break the mind control too) and feels thematic.

**Comment by Kierany9** [comment]
I like that idea
It is done

**Comment by Borisvanmemes** [comment]
Making mind control break apon getting cold is kinda a giant nerf due to temp guns being a thing but at the same time it sounds like a GREAT fucking idea.

**Comment by subject217** [comment]
airlock walkies

**Comment by Kierany9** [comment]
>also the cold thing doesnt stop you from doing the EPIC FOR THE WIN fullstrip in arrivals and THEN jumping out the airlock which is what most people do

local coder jumps out of airlock, more at 11

**Comment by wesoda25** [comment]
God players are so stupid. The best use for mind control is making meta friends kill each other. 

But subject most people don't strip everything off, meaning someone quick enough could throw their headset or something to get back. Of course then the hivemind might be waiting for you, but then its just good planning. 

Also, would temp gun force someone out of mind control?

**Comment by subject217** [comment]
all the successful hivemind airlock walkies spacings i have seen all involve a fullstrip, it's the meta strategy and not doing it that way is simply inefficient, especially so if the proposed solution of just using cold was implemented, wherein it'd be the only successful way to still do it.

**Comment by wesoda25** [comment]
OK then alternative idea: lock hivemind inside of body if cold. That way, if the body dies they die with it. Maybe self applied cold would be the new assimilator meta tactic but theres ways to figure that out.

**Comment by Kierany9** [comment]
gonna take a break, think this one through a bit better and implement a fix when I do the big stuff PR

**Pull request closed without merging**
