### PR TITLE
Adds a max temperature to fusion

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Adds a soft cap to fusion temperature at 1e8. When the temperatures get above this point, fusion will no longer be endothermic or react properly, instead waiting for the next exothermic reaction to take place. This will slow fusion down overall, which isn't such a bad thing. Trit will still be consumed during those ticks.

## Why It's Good For The Game
At a max of 1e8, you can no longer cook half the station by dumping a fusion can inside atmos. Spread is a lot more contained, and a fusion flood will require a minimum of work to be effective just like all the other floods.
This should also limit some of the nan and inf issues we have been having when combined with the SM, TEG and open air. These still need proper fixes, but this is a step in the right direction.
Might make catalysts more interesting in some exotic gas reactions that steal heat, probably wont though.

## Changelog
:cl: Skoglol
tweak: The fusion reaction is now soft capped to a temperature of 1e8.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Speedmerge? Yes.

**Comment by FloranOtten** [comment]
A bit low if you ask me. This is a cap that, as an engineer, I have SME designs already in place that can handle someone dumping a fusion can at that temp in without me touching the SME at all.

**Comment by kriskog** [comment]
Cool, but I disagree. It's high enough, and even dumping this in the SM is retarded good.

**Comment by MCterra10** [comment]
Tbh this will kinda make it hard to make hyper noblium, because each reaction consumes 1e9 joules of energy

**Comment by Ghilker** [comment]
is this a poor thought out and ided PR? 
the cap is too low (unless you can go higher somehow)
instead of making fusion harder, you are just limiting it; lock it behind a research wall where you need t4 parts and energy canisters/containment

**Comment by kriskog** [comment]
> 
> 
> Tbh this will kinda make it hard to make hyper noblium, because each reaction consumes 1e9 joules of energy

I tested hypernob, made 40 moles off an e8 can with no issue. Also, bz can be used as a catalyst to reduce the heat loss which is currently never done because lol fusion temps.

> 
> 
> is this a poor thought out and ided PR?
> the cap is too low (unless you can go higher somehow)
> instead of making fusion harder, you are just limiting it; lock it behind a research wall where you need t4 parts and energy canisters/containment
> 
> edit: also don't start with the usual WhEn YoU cOdE iT. If I knew how to code I would definitely do it

Hardly. I know my fusion shit, and while yeah this doesn't make fusion any harder to achieve, it reduces the insane and needless temperatures that we currently have. Limiting fusion temps is not the issue you make it out to be, except no more overflowing for you.
Besides, you're the one pretending to care about having someone """fix""" fusion, so why are you in here at all?

**Comment by MCterra10** [comment]
40 moles, which would consume about 400 moles of trit and 800 moles of n2 to form. Pretty abysmal performance compared to what I can get currently with an e20 can

**Comment by MCterra10** [comment]
Also rip bragging about how high your fusion temps got

**Comment by kriskog** [comment]
> 
> 
> 40 moles, which would consume about 400 moles of trit and 800 moles of n2 to form. Pretty abysmal performance compared to what I can get currently with an e20 can

That was my test case, and I didn't say my temp dropped much. I could have run more.
Again, this is why the catalyst exists. If you are doing grand scale hypernob production, you should be using the catalyst to prevent losing heat to the full degree.

**Comment by Ghilker** [comment]
What's there to brag about when everyone can make a 10 balls tesla generator given enough money and time?
I'm complaining about the now lack of content in fusion because you make one canister and is over, at least before I could pretend I was working with something very dangerous and that you have to take special care to not let It out
With this, one canister, you make a bit of hyper, maybe nitryl, then? Also reaching e31 was fun because you need a specific mix of gases to reach it easily or you have to deal with the random spikes of high and low temp changes
Also rip to the bragging of making the highest instability since two pulses and it flat to 0

Don't try to think I don't want fusion to be somewhat made harder to make, and to use, but this only remove the "fun" part of it, since you can still cook the station with that temperature (like 10 minutes in, hook it to distro, profit)

**Comment by kriskog** [comment]
Making a hotter can isn't content. If making hotter cans is all you got left, maybe its time to move on and do something less destructive.

Instability wasn't touched.

Once this is in, you can try flooding with the 1e8 can. You'll soon notice it's nowhere near as effective as even a 1e12 can.

**Comment by Ghilker** [comment]
Making a hotter can is a content, not the only one
I'm fine with limiting/making it harder for obvious reasons 
The problem here is that you removed something without adding anything, you could add more kinds of gases that have different uses, different types of canisters and pipes, etc.
Is like making maxcap bombs cap but you didn't add the theoretical max size for the research points

**Comment by Learner10** [comment]
There's a certain line of logic you could apply to this that is easily presented if you posed this question...

Should we apply a cap to the amount of energy an SME can produce? If you say no, then why? I mean, after all, a standard SM can produce enough power to fully run the station without any issue. Why do we need all of that extra energy if all it's going to do is just instantly dust anyone who looks at an exposed wire the wrong way?

All things considered, there's a certain level of pleasure one can obtain by pushing the envelope with extremes. If there's one thing we as people want, it's more of the things, even if the things don't even really do anything extra. "We want more money for Cargo" even though they're so flushed with boxes that they can't even move in the bay. "We want more mechs" even though they've made everyone on board a custom built mech and forgot to make charging ports for them. "We want more heat", even though they've reached the point that the center of the sun is by comparison an ice cube. The difference in all of these is that one of the above is more responsible in causing harm then the others...

And well... that's always been the latent danger of engineering. They as a department have always had the power to cause the most harm to the station. If the SM ended up making a singulo each and every round, then that'd just be par for the course for engineering. If you start putting limitations on what they can do with engineering, then you may as well go all the way. If they can't kill the station with snowflake air, they could probably just cause a station-wide radwave from the SME, or just directly pipe from the SME to the station.

There's a reason they've been called Autismos... and also, is this even believable science? And does this apply to cold fusion?

**Comment by AdamElTablawy** [comment]
while there does need to be an upper limit it's kind of stupid to argue that 'making a hotter can isn't content'

i mean the point of most of this stuff is to experiment and get it as good as possible. nobody needs a supermatter that produces any more energy than the ordinary n2 setup, nobody needs to set up 4 singulo engines, nobody needs a bomb of 50/100/200, but they try to aim for those things because it's cool to push the envelope

**Comment by Dorsisdwarf** [comment]
Yeah and theres an artificial cap on bomb sizes to stop people who've already pushed the limits to the point where its routine from deleting the station every antag round

**Comment by Ghilker** [comment]
I'm against this change because it doesn't make fusion better, it just lock it artificially instead of integrating it with science.
Bombs had a cap put on them, but they can still be used both by antags (blowing stuff up) and non antags (science still receive max caps points) 
I bet that if this change would happen, people won't work on fusion anymore, because nobody care much about it. It will stay locked behind a fake wall and nothing will be added to it.

**Comment by kriskog** [comment]
>
> 
> Should we apply a cap to the amount of energy an SME can produce? If you say no, then why? I mean, after all, a standard SM can produce enough power to fully run the station without any issue. Why do we need all of that extra energy if all it's going to do is just instantly dust anyone who looks at an exposed wire the wrong way?

Yeah, we probably should. Power is currently unbalanced to a point where trying to find any cool uses for it is instantly shot down by maintainers.

>
> 
> All things considered, there's a certain level of pleasure one can obtain by pushing the envelope with extremes. If there's one thing we as people want, it's more of the things, even if the things don't even really do anything extra. "We want more money for Cargo" even though they're so flushed with boxes that they can't even move in the bay. "We want more mechs" even though they've made everyone on board a custom built mech and forgot to make charging ports for them. "We want more heat", even though they've reached the point that the center of the sun is by comparison an ice cube. The difference in all of these is that one of the above is more responsible in causing harm then the others...

I am aware, I have played with nu-fusion for months now. While getting hot gas and breaking the game with it is fun, it isn't in a place where we could call this sustainable. It is too volatile, and even a mistake can make large parts of the station uninhabitable forever. Atmos will still be able to get more of the fusion products, they just won't get the moronic high heat we have had available for a while now.

>
>
> And well... that's always been the latent danger of engineering. They as a department have always had the power to cause the most harm to the station. If the SM ended up making a singulo each and every round, then that'd just be par for the course for engineering. If you start putting limitations on what they can do with engineering, then you may as well go all the way. If they can't kill the station with snowflake air, they could probably just cause a station-wide radwave from the SME, or just directly pipe from the SME to the station.

You just described the reason singulo and tesla have been phased out on all maps. If something is overdone like releasing tesla on pubby and singulo on donut was, it ceases to be fun or interesting and gets phased out of the game. Time for the next chapter.

> 
> 
> I'm against this change because it doesn't make fusion better, it just lock it artificially instead of integrating it with science.
> Bombs had a cap put on them, but they can still be used both by antags (blowing stuff up) and non antags (science still receive max caps points)
> I bet that if this change would happen, people won't work on fusion anymore, because nobody care much about it. It will stay locked behind a fake wall and nothing will be added to it.

Wyci. There is no reason we can't both lock fusion behind something and also reduce the temperatures. These are not mutually exclusive.
Fusion can still be used by antags with the cap.
Why are you even working on it right now if reaching high temperatures is all that entertains you about it? As I said before, it's time you move on if you are that bored with the mechanic. There is no "locked behind a fake wall" here, everything but temperature is still achieveable.

**Comment by AdamElTablawy** [comment]
@dorsisdwarf yeah but the sizes are achievable still, just locked behind a cap

the change to the can makes it so that things like hypernoblium are harder to get good yields out of

frankly, it’d be better to make it so that the temperature remained the same while inside the canister as it is now, but gas in open air was reduced to the value you’ve set, so that you could still hit those high temperatures but couldn’t obliterate stuff with them

much like how you can hit a huge station annihilating bomb blast in theoretical yield but it’s hardcapped at 5/10/20

**Comment by FloranOtten** [comment]
>>Should we apply a cap to the amount of energy an SME can produce? If you say no, then why? I mean, after all, a standard SM can produce enough power to fully run the station without any issue. Why do we need all of that extra energy if all it's going to do is just instantly dust anyone who looks at an exposed wire the wrong way?

>Yeah, we probably should. Power is currently unbalanced to a point where trying to find any cool uses for it is instantly shot down by maintainers.

That's misleading and you know it. The problem with SME power is that the radiation is exceptionally easy to bullshit by using bluespace rpeds.

**Comment by kriskog** [comment]
Radiation is currently being reworked, which should fix that. But power still could use some balancing.

**Comment by Ty-the-Smonk** [comment]
I don’t know anything about atmos but if you are needing scientific notation for tempuratures I think it is a bit ridiculous

**Review by 81Denton — APPROVED** [review]
This is a band aid fix, but a neccessary one until someone reworks fusion into something that needs to be contained with powered containment.
Plasmeme XIV murdering everyone by dumping a can of gas *the temperature of the Big Bang* into the SME gets old really fast.

**Pull request merged**
