### PR TITLE
New icons for mining devices and machinery

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

We had old goon icons of ORM and mining scanners for a really long time so I made new ones. Credits to Citadel for ORM sprites.

## Why It's Good For The Game

New sprites are always good

## Changelog
:cl:
imageadd: Added new icons for ORM and mining vendors
imageadd: Added new icons for mining and genetic scanners
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
Grug not like new mining scanner sprite. Should look more than just Analyzer But Different. Grug also not like new sequencer - now harder to differentiate from health scanner.
Grug like ORM and Miner Vendor though.

**Review by Twaticus — CHANGES_REQUESTED** [review]
machine changes good
not convinced on the device changes. while the details on the current ones are a bit flat and can use an upgrade, the shapes themselves are good and differentiate them from related devices. dont like the idea of removing the distinction and turning them into simple recolors instead

**Comment by SamDDBS** [comment]
I like the mining scanners designs, but I think the genetics scanners look too much like a health scanner.
The machine designs look good and I think they should fit in well with all the other machines.

**Comment by trerri** [comment]
It's hilarious because the mining scanner and gene analyzer are literally repaints of what the atmos analyzer and health scanner looked like at the time and the person who updated them had the galactic brain idea to just do that but with the new sprites for the base items

**Comment by TemporalOroboros** [comment]
I was wondering why the mining scanner and gene scanner looked like the goon analyzers.

**Comment by Rohesie** [comment]
What's the sentence here, @Twaticus ?

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
