### PR TITLE
Adds cat people laugh

### PR DESCRIPTION
**Pull request by ghost**
:cl: CosmicScientist
add: We found the felinid's laugh box, you may revile me at will
/:cl:

Better code than #40235 

Demands a check for felinid before human due to being a subtype/[ishumanbasic() being true for felinids.](https://github.com/tgstation/tgstation/blob/54828b8a18da0c325bde451f46e66a5b972edd74/code/__DEFINES/is_helpers.dm#L60-L61)

Adds a commented out config option for felinids because #39513 didn't add one (I couldn't test my PR).

youtube video clicky here:
<a href="http://www.youtube.com/watch?feature=player_embedded&v=JVS8N_PtFW0" target="_blank">IMAGE ALT TEXT HERE</a>

### CODE REVIEW

**Comment by Wilchenx** [comment]
image

ah the great lizard drama continues

**Comment by Cw3040** [comment]
it's because rootbeer is bigger gay than even oranges

**Comment by SgtxRootbeer** [comment]
meh

**Comment by DaedWren** [comment]
Hi papi I do voice gimme upmems

**Comment by GhostEcho** [comment]
Bad PR, don't merge

**Comment by 81Denton** [comment]
Why bother opening shitpost PRs that you know are just gonna get closed anyway

**Comment by Wilchenx** [comment]
this is too much effort for a shitpost

**Comment by SgtxRootbeer** [comment]
i feel like the sunk cost fallacy is involved in some way

**Comment by CosmicScientist** [comment]
I only make quality content.

**Comment by DaedWren** [comment]
I spent £30 on this PR plz no

**Comment by SgtxRootbeer** [comment]
there it is!

**Comment by CosmicScientist** [comment]
(not paid code, that was the mic's cost)

**Comment by Featherfield** [comment]
Now what we need is to have them lose their tongues if they laugh too much

**Comment by optimumtact** [comment]
this isn't funny

**Comment by optimumtact** [comment]
I swear to god people who start making species changes without asking the maintainers are gonna get gitbanned

**Comment by CosmicScientist** [comment]
There are rules?

**Comment by Cw3040** [comment]
Oranges makes up rules to ban people he doesn't like

**Comment by SgtxRootbeer** [comment]
How can you not find it funny? It's laughter!
Why, I'm sitting here busting a gut myself over it.

**Comment by GhostEcho** [comment]
@optimumtact wait hold the phone, making a **PR** for changes to a species isn't allowed without asking first, Im sorry, what?

**Comment by CosmicScientist** [comment]
Found the ban list (bottom of the page): https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md

>Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

**Comment by GhostEcho** [comment]
Its a request, it can be approved or denied, why is making a PR itself not allowed?

**Comment by FantasticFwoosh** [comment]
:eyes:

**Comment by Qustinnus** [comment]
@GhostEcho because they got made too much and turned into shitflinging contests instantly, we have a 24h open PR policy so that got annoying real fast

**Pull request closed without merging**
