### PR TITLE
Various hulk changes.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Mutations lost their UnarmedAttack hook. They now use signals instead. This effects chameleon and hulk.
Hulks now always scream if they sucessfully attack something.
You only do a proper hulk SMASH on harm intent.
You can't attack living things with hulk anymore if you have pacifism
Attack animation for hulk smash now gets handled in the mutation.
Hulks can now pick up turned on dswords, good thing it is physically impossible to drop a turned on dsword.

## Why It's Good For The Game

It gives the player better control over what the want to do.
Hulks screaming when they attack mobs makes sense.
Shitcode is bad.

## Changelog
:cl:
tweak: Hulks now always scream on attack.
tweak: Hulks now only hulk smash on harm intent.
code: Hulk code is less shit now.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Don't tell me this is conflicting with my own stuff.

**Comment by Nabski89** [comment]
You can use TK to turn on a DEsword while it's on the ground.

I came into this expecting to be mad, but I'm not. This is somehow not your average hulk PR.

**Comment by AdamElTablawy** [comment]
so now hulks are even fucking spammier

**Comment by nemvar** [comment]
@Nabski89 even if you can, it *should* still turn off when the TK guy drops it. If that doesn't happen, that's a bug with TK/twohanded items.

**Pull request merged**
