### PR TITLE
Puts some brakes on the Cult Train

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
balance: Once the blood cult reaches 20% of the active player population, they will receive a notice that the cult is "rising" - and after a moderate delay the eyes of all existing and new cultists will be permanently red. Examining a cultist with uncovered eyes will confirm their supernatural appearance.
balance: Once the blood cult reaches 40% of the active player population they will receive a warning and after a moderate delay will glow red, permanently revealing the identity of existing and new blood cultists. 
add: Any non-cultist can now strike a (filled) soulshard with a bible to purify it. Purified shades have a unique appearance and will be eager to get revenge on the cult. Bibles can be printed in the library.
balance: Juggernauts have 25% less HP and 35% less projectile reflection
balance: Cult mirror shield is 40% less effective at blocking physical attacks, has less illusions, and has -33% throwing distance. 
balance: The EMP blood spell has -1 light and heavy radius
balance: The revive rune now requires 3 sacrifices per revive, it still starts with one "freebie" revive. Giving "souls" to AFK/Catatonic cultists remains free of charge. 
balance: Twisted Construction now has a channel time with added noise/effects when used on doors
balance: You can now only hold 1 blood spell without an empowering rune and 4 with one.
tweak: Tooltips are will now capable of appearing without relying on mouse behavior. If no mouse params are provided - the tooltip will use the source atom for its location (which produces the same result 99.99% of the time). 
add: New cultists will be shown a set of tooltips informing them of the functionality of new UI elements.
/:cl:

With our stat tracking being down/rebuilt in recent months its been hard for me to gauge cult balance after the talisman removal. I'm busy working on anti-lag stuff but from what I've gleaned the cult is usually winning now so I feel comfortable with another round of nerfs to their most problematic strengths.

### CODE REVIEW

**Comment by Durkel** [comment]
Good changes but this might be too rough in the end. Worth testing it out for a few weeks and see how things are going at least.

**Comment by Cyberboss** [comment]
inb4 take off your glasses or baton

**Comment by davethwave** [comment]
as soon as you made this pr a cult round started in science, we basically took over the station within 30 minutes.

**Comment by Doppeltongue** [comment]
Giving the crew a vague sense of how strong the cult has become is a good idea. This also encourages the cult to think about how many recruits they get if they're not prepared to go loud yet.

**Comment by Robustin** [comment]
Given this PR wasn't even compiling when it opened, it certainly hasn't been testmerged.

I need to make a graphic for the aura, preferably one that isn't just a re-color, and figure out just how permanent I want to make the eye color change (having it override DNA/surgery changes might be obnoxious and could stifle some interesting gameplay).

**Comment by Tlaltecuhtli** [comment]
would mass suiciding reveal the cult?

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss literally slings "show me your face".

It was fun though.

**Comment by Hatfish** [comment]
Will the culties be able to tell when they're about to go over the threshold?

**Comment by Robustin** [comment]
Yea, I should've worded it better, each threshold will broadcast a message to the cult about 30 seconds before the effect begins so nobody gets fucked out of nowhere, though going AFK as a cultist is much riskier now.

**Comment by NocturnalQuill** [comment]
This should make things significantly better. I said it on the forums, but I would give serious consideration to locking some runes/spells behind conversion requirements and making constructs not count as cultists for rune unlock and invoking purposes. Live conversions are the "hardest" (needing 3 cultists) yet constructs are better in most circumstances.

**Comment by Tlaltecuhtli** [comment]
netf sacc rune, getting free simplemobs for cleaning dead bodies is bad

**Comment by Barhandar** [comment]
> balance: The revive rune now requires 3 sacrifices per revive, it still starts with one "freebie" revive. Giving "souls" to AFK/Catatonic cultists remains free of charge.

How does it compare to an autocloner in cult territory?

**Comment by Dorsisdwarf** [comment]
Is there any cost to the revive rune, or can you just one-click remove it and draw a new one every time for infinite "freebie" revives?

**Comment by Robustin** [comment]
The "tracking" for the revive runes works off a static var and a global list of sacrifices, so there's no way to cheat the system by drawing new runes.

**Comment by YPOQ** [comment]
The 
`The veil weakens as your cult grows, your eyes begin to glow...
Your cult is ascendent and your very blood pulses with power!`
message gets spammed to the cult

**Comment by adamkad1** [comment]
yeah, nerf cult more, we need more hugbox for the skilless security

**Comment by ExcessiveUseOfCobblestone** [comment]
Cult is a curbstomp unless you go cargosec which players have also begged admins to ban for.

**Comment by adamkad1** [comment]
cult is either crew gets curbstomed or cult gets curbstomped. no middle ground

**Comment by ExcessiveUseOfCobblestone** [comment]
Well that's part of conversion modes since they (theoretically) get exponential gains for each cultist so you either have to BTFO or get stomped on.

Dunno if it's bad or not, as long as the fight's good i'd imagine.

**Comment by Robustin** [comment]
Historically 2-to-convert cult hasn't been that snowbally because it relies on runes and somewhat centralized basebuilding so for example a cult base in science or scimaint might initially surged with fresh scientist converts but converting scientists wouldn't magically give you access to cargo or medbay or engineering, plus there'd be something of a bottleneck in the base where people would be struggling with overcrowding as everyone competes for limited rune/structure access.

Bloodspells helped eliminate one of the bottlenecks (paper), so growth seems to have sped up a bit, one solution would be to limit empower runes to one cultist at a time - but I feel that that sort of thing isn't the healthiest way to limit cult growth. I think adding these visual cues will help serve as a deterrent to just rampantly growing the cult and once they are triggered, especially the aura, your ability to get new members will diminish instead of just continually increasing.

**Comment by Wilchenx** [comment]
@Robustin will high-luminescent eyes override the eye color?

**Comment by callanrocks** [comment]
inb4 cultists just ripping our their eyes for robot eyes.

**Comment by ExcessiveUseOfCobblestone** [comment]
Does it matter?

If they waste their time trying to hide their eyes they're probably going to get BTFO'd directly (uh oh sec is raiding) or via attrition (omg while I spent hours getting surgery everyone is now implanted!!!!)

**Comment by Commandersand** [comment]
>sec starts arresting anyone who covers their eyes
>cult drops from 15% to 0% in a few minutes

**Comment by Robustin** [comment]
Yes it replaces your eye color but anything that covers your eyes (including most masks, certain helmets, etc.) will conceal them. Yes that means you can try to hide by having your eyeballs carved out, replaced, or genetically altered (probably the first time anyone has messed with the appearance genes).

The aura (which is now more of a blood seal) cannot be concealed in any way shape or form. 

Bonus clip of Warden using Krav Maga to check the eyes of suspected hulk cultist: https://www.youtube.com/watch?v=yBU_dOks2RM

**Comment by BeeSting12** [comment]
choo choo

**Comment by KorPhaeron** [comment]
stale

**Comment by Robustin** [comment]
@KorPhaeron @optimumtact 

What exactly was unfinished about this PR anyway?

**Comment by optimumtact** [comment]
hey robustin did you finish your case?

**Pull request closed without merging**
