### PR TITLE
Resprites toolboxes

### PR DESCRIPTION
**Pull request by RigglePrime**
## About The Pull Request

The sprites were made by @Imaginos16, I am only creating the PR (Git is being stupdi)

## Why It's Good For The Game

New sprites. Do I need to say anything more? Goon folder begone.

image
image

This PR also reverts #63930

## Changelog

:cl: PositiveEntropy
imageadd: resprite the toolboxes
imagedel: removes the old Goon toolbox sprites
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
but... the classic toolbox sprite...

**Comment by tralezab** [comment]
Yes, but what about the court of public opinions?

**Comment by Imaginos16** [comment]
> but... the classic toolbox sprites...

Skill issue

**Comment by castawaynont** [comment]
soo... are current toolboxes now considered Soul? are old toobox sprites considered soul^2?

**Comment by Mothblocks** [comment]
https://github.com/tgstation/tgstation/pull/64235

What about this?

**Comment by AndroidMK2** [comment]
Why is everything being turned to plastic...

**Comment by cacogen** [comment]
These aren't the worst sprites. I don't even dislike the Pokemon aesthetic. It just doesn't fit the rest of the game.

**Comment by Sealed101** [comment]
im not sold until i see how the triple latch ones look with this

**Comment by Fikou** [comment]
> #64235
> 
> What about this?

it would be redundant but wouldnt change anything

**Comment by Suspect-One** [comment]
The sprites themselves are good, but they feel.. wrong. I don't know, they just don't fit in. Maybe because of some kind of toy-ish style, something like that would look fine in kindergarten I guess.

**Comment by JohnFulpWillard** [comment]
I think the sprites look cool but I’m not a spritainer

**Comment by Livrah** [comment]
Current toolboxes was already desouled, this ones just looks bad.

**Comment by itseasytosee** [comment]
My complaint is specific and fixable. All toolboxes in the past have had handles that match their color, you know, like a toolbox.
These ones have shiny silver handles that look bad and make them look like metal purses. Make the handles match the toolbox.

**Comment by Farquaar** [comment]
While I do like that the glass toolbox actually looks like glass though, it doesn't match the glass in the rest of the game (should be blue-tinted, not white-tinted). Unless it's a ghost toolbox and I'm just dumb.

**Comment by Sealed101** [comment]
thats the hauntium toolbox mate

**Comment by Mothblocks** [comment]
@Fikou Is it redundant? This removes goon/toolbox.dmi again, which is what the soulful toolboxes use, I thought?

**Comment by Cboyjet4** [comment]
what makes these better than the current sprites?

**Comment by Imaginos16** [comment]
> what makes these better than the current sprites?

They are not from Goon.

**Comment by JohnFulpWillard** [comment]
> @Fikou Is it redundant? This removes goon/toolbox.dmi again, which is what the soulful toolboxes use, I thought?

the opposite, soulful toolboxes use ancient TG toolbox sprites, current ones use goon sprites.

**Comment by JohnFulpWillard** [comment]
I generally don't think we should be replacing goon stuff for the sake of removing goon stuff, but I think this is a genuine improvement over the old sprites.

I don't understand the comment saying to make all handles the same color just because the previous iterations did so, it's the point of a resprite.

**Review by Twaticus — APPROVED** [review]

**Comment by SomeDongus** [comment]
im going to kill myself

**Comment by theta006** [comment]
ugly as fuck revert this

**Comment by itseasytosee** [comment]
I wouldn't sweat it guys, it's bound to be resprited again sooner or later.

**Comment by jacklecroy** [comment]
I don't see why removing goon content is more important than having good-looking sprites. It's under the same license as all the other sprites, right?

**Comment by Mothblocks** [comment]
Goon sprites are CC-BY-NC-SA, our sprites are CC-BY-SA.

**Pull request merged**
