### PR TITLE
Removes dirtystation

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
The station starting covered in vomit was already gross and now the vomit has spread to the snow planet and lavaland it's time to stop

### CODE REVIEW

**Comment by lzimann** [comment]
If the issue is having on snow/lavaland, fix the areas/turfs spawning the dirty, don't remove everything.

**Comment by SgtxRootbeer** [comment]
Nah, lzimann, let it burn

**Comment by Tacolizard** [comment]
theres no real point to it. just let mappers place the vomit

**Comment by optimumtact** [comment]
no 👎 fix this properly

**Comment by optimumtact** [comment]
need a config for map type

**Pull request closed without merging**
