### PR TITLE
Fixes adminjump being dumb.

### PR DESCRIPTION
**Pull request by theOperand**
what it says on the tin.
did i already make this PR?

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Wow, that is immensely simplier.

**Comment by MrStonedOne** [comment]
actually, yeah, why have we been trying to hack together the force move, setting .loc seems like the obvious solution. 

Something tells me there was a reason for that, and we will find out what it is the hard way. Oh well, :+1: none the less

**Comment by Miauw62** [comment]
i'm the dude who made it use the Move() in the first place. it didnt work.

**Comment by Jordie0608** [comment]
Reminds of of an unreported issue wherein using Jump to Area from a right-click menu doesn't work.

Would this be related to that?

**Comment by Miauw62** [comment]
it may be.

**Comment by TheVekter** [comment]
@miauw62 Merge confliiiiiiiiict

**Comment by Miauw62** [comment]
conflicts fixed.
no merge commit because i am a certified git wizard tm

**Comment by Miauw62** [comment]
somebody merge pls

**Pull request merged**
