### PR TITLE
use your custom character as an AI hologram

### PR DESCRIPTION
**Pull request by azrael-x86**
## About The Pull Request

unknown
_don't mind the slightly different sprites, not included in the PR_

adds a new option to the change hologram command in AI commands, allowing you to now select a "custom character" option. this option allows you to either use another station member as a hologram, or use the currently selected character slot as a hologram (will use the preview of the highest job priority. set to assistant to have your loadout used as appearance.)

## Why It's Good For The Game

simply put this is pretty sick and cool. i'm led to believe we did infact have it at one point, and plenty of other stations already do have it, so we might aswell not miss out on it.

## Changelog

:cl:
add: added ability to change hologram appearance to custom character
/:cl:

### CODE REVIEW

**Comment by magatsuchi** [comment]
quit bullying me, i built this on my computer and it runs a-ok. :) webedit sux 2 much for this

**Comment by Y0SH1M4S73R** [comment]
fun fact: This PR was opened here because Skyrat maintainers said it belonged upstream.

**Comment by magatsuchi** [comment]
> fun fact: This PR was opened here because Skyrat maintainers said it belonged upstream.

this is not fun :((

**Comment by thestubborn** [comment]
> 
> 
> fun fact: This PR was opened here because Skyrat maintainers said it belonged upstream.

and?
its still a good feature

**Review by Watermelon914 — CHANGES_REQUESTED** [review]

**Review by Watermelon914 — CHANGES_REQUESTED** [review]

**Pull request merged**
