### PR TITLE
New Revenant icons

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Adds new sprites for the revenant.
Revenants now always look in the direction of their drain target

Sprites by Onule

## Why It's Good For The Game

It looks better.

## Changelog
:cl: Onule & Nemvar
imageadd: New Revenant icons
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
why there no directionals
also this is a balance change his hitbox is bigger now smh

**Comment by tralezab** [comment]
i really like it, make sure to remove the rogue pixels
image

**Comment by nemvar** [comment]
Fuck, I was 90% sure I got rid of all of them. I even double checked.

**Comment by nemvar** [comment]
Bow before your new god. We now have proper directional sprites!

**Comment by ExcessiveUseOfCobblestone** [comment]
@Onule can I beg for you to be our new art guy???

**Comment by mrhugo13** [comment]
the virgin normal sprite vs the chad detailed and well-made sprite.

Fuck yeah, merge this allready.

**Comment by granpawalton** [comment]
Really cool but if im not mistaken i dont think there is there a way to distinguish the visible vs invisible sprite anymore

**Comment by nemvar** [comment]
Icon diff doesn't display alpha correctly. Invisible is way less visible than revealed.

**Pull request merged**
