### PR TITLE
Removing z6

### PR DESCRIPTION
**Pull request by Superxpdude**
Removed the asteroids on z6 during extended/sandbox. Removed z6 from the map.
Ignored some more files.

### CODE REVIEW

**Comment by arkadiusz123** [comment]
#39574

**Comment by optimumtact** [comment]
for some reason github saw fit to ping me about this

**Comment by Cyberboss** [comment]
some nerd commented and deleted it

**Comment by HomocidlePancakes** [comment]
Super sekrit klub.

**Comment by trollbreeder** [comment]
> Super sekrit klub.

piss off homocidle

**Pull request closed without merging**
