### PR TITLE
Prevents Mindswapping on Bitrunners

### LINKED ISSUE #79310: Mass mindswap on bitrunners is disastrous
## Reproduction:
Just making this issue here after it was reported to me on discord - 
Mass mindswap caused one bitrunner to get their avatar swapped with a crew member, which lead to shenanigans. These should probably be removed from the list of targets

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Fixes #79310

Adds a new trait to prevent mindswaps (which is just useful for any future cases when we don't wanna rely on the blacklist typecache) while also accounting for bitrunners (who you can't mindswap because their mind is elsewhere) and their avatars (because that's not a real mind now is it).

this does mean that bitrunners while bitrunning are immune to all mindswaps but i don't have a good answer on how to fix it. i don't even much like the idea of VR but I think that having these traits are useful enough for future utilization.
## Why It's Good For The Game

prevent big breakage.
## Changelog

:cl:
fix: Bitrunners can no longer get mass-mindswapped out of their avatar when the wizard does the event. Something about machinery and magic not going well together.
/:cl:

### CODE REVIEW

**Comment by Singul0** [comment]
glitched virtual copies in the virtual world mindswapping into a bitrunner sounds like a banger idea

**Comment by jlsnow301** [comment]
I can add a case for this where it still works on the actual crew member, but avatar doesn't make sense in any case

**Comment by ninjanomnom** [comment]
The avatar should be ignoring this but shouldn't a mindswap on the crew members force the new owner of the body into the netrun, and the old one out? Assuming they havent been swapped with someone else in the same run anyway.

**Comment by jlsnow301** [comment]
> The avatar should be ignoring this but shouldn't a mindswap on the crew members force the new owner of the body into the netrun, and the old one out? Assuming they havent been swapped with someone else in the same run anyway.

this was my plan. i propose we merge this as a stop gap, and keep the trait for future use

**Comment by san7890** [comment]
yea then merge it then

**Pull request merged**
