### PR TITLE
Fixes incorrect closing html tag

### PR DESCRIPTION
**Pull request by ThatLing**
Found this while fixing merge conflicts downstream.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
wonder how I managed that one

**Review by Cyberboss — APPROVED** [review]

**Review by SpaceManiac — APPROVED** [review]

**Review by ShizCalev — APPROVED** [review]

**Comment by Carbonhell** [comment]
Wouldn't you have to close <font> aswell?

**Comment by Carbonhell** [comment]
i meant close font aswell, github just stripped it from my comment

**Comment by SpaceManiac** [comment]
It is closed: `<font color='blue'>...<b>...</b>: <span ...>...</span></font>`

**Pull request merged**
