### PR TITLE
Adds clarification to the Baseball Bat's botanical status.

### PR DESCRIPTION
**Pull request by Potato-Masher**
## About The Pull Request
Updates the baseball bat description to clarify it's botanical status. 

## Why It's Good For The Game
Clears up possible confusion and misinformation created at the /tg/ gameshow.

## Changelog
:cl:
spellcheck: Adds clarification to the Baseball Bat's botanical status.
/:cl:

### CODE REVIEW

**Comment by RandomGamer123** [comment]
speedmerge

**Comment by Sparkezel** [comment]
ided pr, laugh at this user

**Review by Mothblocks — APPROVED** [review]
my best friend asked me to merge this

**Comment by PolishUser** [comment]
Lola won.

**Comment by RandomGamer123** [comment]
> speedmerge

actually even funnier, speedmerge and instant revert

**Comment by Lauwma** [comment]
Speedmerge

**Comment by Mothblocks** [comment]
u can wait

**Comment by maxymax13** [comment]
joey played fair, terryite played to win

**Comment by ATH1909** [comment]
but the bat's literally entirely made out of plants.

**Comment by RaveRadbury** [comment]
> but the bat's literally entirely made out of plants.
> 
> how is a harvested deathnettle different from a harvested log that's been turned into a 100% wooden baseball bat?

One of them inherited botany stats and data, the other was made from wood planks and is always the same.

**Comment by optimumtact** [comment]
heartbreaking

**Comment by Mothblocks** [comment]
oranges is referring to my best friend

**Comment by Potato-Masher** [comment]
they hated him because he told them the truth

**Pull request closed without merging**
