### PR TITLE
You can now see whether or not a piece of clothing is pressure-proof when examining

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

A picture is worth a thousand words: 
unsealed
sealed
helmet
As you can see from the first picture, it takes unsealed modsuits (and similar items, if any exist) into account. It also has text for clothing that covers both the head and torso, but as far as I can tell no single item does this (hoods don't count since it's a separate item).
## Why It's Good For The Game

Knowing that a piece of gear protects you from space is vital information, especially to new players. For EVA suits, it might already be obvious, but how many new players will know that a firesuit does the same?
## Changelog
:cl:
qol: Clothing now tells you if it is pressure-proof and insulated enough for spacewalking when examining it.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
may as well take the opportunity to do this for a lot of other flags like temp resist

**Comment by GPeckman** [comment]
Temp resist is already a thing, that's what the "EVA helmet offers the wearer some protection from fire" thing means. But I might change that to make it more explicit.

**Comment by SimplySmiley123** [comment]
> Temp resist is already a thing, that's what the "EVA helmet offers the wearer some protection from fire" thing means. But I might change that to make it more explicit.

That doesn't really tell someone it will protect them from cold and temperature changes, just that it gives _some_ unspecified resistance to fire.

**Comment by GPeckman** [comment]
Alright, I added some support for temperature as well:

insulated
uninsulated

I would make it more detailed, but to be perfectly honest I have no idea how limb coverage works when it comes to insulation.

**Pull request merged**
