### PR TITLE
Adds a chemistry bag for moving large amounts of patches/pills/bottles at once

### PR DESCRIPTION
**Pull request by nukeop**
This adds a chemistry bag that can store pills, patches and bottles like an ore or plant satchel. Handy for chemists to collect all patches a machine creates at once and put them somewhere else (like a fridge).

It also puts one such bag on the glass table in chemistry lab.

### CODE REVIEW

**Comment by WJohn** [comment]
You dun goofed the map merger.

**Comment by Iamgoofball** [comment]
Fuck yes :+1:

**Comment by Tokiko1** [comment]
Add it to metastation/ministation too.

**Comment by Dorsisdwarf** [comment]
If only bags could place things on tables

**Comment by pavelheer** [comment]
>Add it to metastation/ministation too. Maybe make the biogenerator able to produce these too, seeing as how the bio generator can create most bags?
Good idea, I'll add it to the other maps and fix the merge issue too.

>If only bags could place things on tables
We could probably change the default behaviour to emptying the bag onto a table, to put it there you'd need to drag&drop.

**Comment by pavelheer** [comment]
I added an icon for the bag (a recolor of the plant/ore satchel), added it to the chemistry closet so it'll spawn on all maps, added an option to make it in a biogenerator, and reverted the map.

I have no idea what controls the behaviour of items when you click a desk though. You can easily empty the bag into a fridge however. Maybe it'd be worth moving it to the spot between desks as I've seen many players do in game, but that's material for another pull request.

**Comment by nukeop** [comment]
merge pls

**Pull request merged**
