### PR TITLE
Add a statically compiled so for bygex [DNM]

### PR DESCRIPTION
**Pull request by optimumtact**
This is a best effort attempt at compiling bygex for linux systems.

Required slight modifications to bygex code that can be found here
https://github.com/optimumtact/byond-regex

I cross compile this on a debian stable system with teh following
invocations of great darkness

gcc -c -Wall -g --static  -lboost_regex -o bygex.o -fPIC -m32 main.cpp
gcc bygex.o -m32 -shared -o bygex.so

I haven't tested this yet, and I'd also appreciate others testing on their various distros

### CODE REVIEW

**Comment by optimumtact** [comment]
fuck I forgot an soname

**Comment by optimumtact** [comment]
Fuck it, to be honest the best and most useful solution is to write a make file and include that along with the source and let server ops build the code themselves

**Comment by optimumtact** [comment]
Doh I left debugging info on

**Comment by Chnkr** [comment]
Will test on OpenBSD, FreeBSD and Fedora.

**Comment by optimumtact** [comment]
Yeah, compiling a static lib with all the dependencies will be quite hard, best I can do is a makefile and some instructions for common distros.

i'll try to do that this week.

**Comment by optimumtact** [comment]
closing for now so to not busy up the tracker

this will come back soon tm

**Pull request closed without merging**
