### PR TITLE
Adds two blaze it emojis

### PR DESCRIPTION
**Pull request by JJRcop**
This pull request was created at gunpoint from [**kosmos**](https://tgstation13.org/phpBB/memberlist.php?mode=viewprofile&u=256).

:rollie:
:ambrosia:

### CODE REVIEW

**Comment by Chocobro** [comment]
finally
it's my time to shine
the brigand of 420s will ride once more

**Comment by MrPerson** [comment]
:-1: :-1: :-1: :-1: :-1: 

Please no.

**Comment by WJohn** [comment]
Yes

**Comment by dannno** [comment]
:-1:

**Comment by CorruptComputer** [comment]
:-1: x :100:

**Comment by Dorsisdwarf** [comment]
:-1: :100:  also. I think you've forgotten the Prime Directive

**Comment by Antimattercarp** [comment]
:-1:

**Comment by Nienhaus** [comment]
I like the ambrosia.

**Comment by JJRcop** [comment]
Still at gunpoint here..

**Comment by Cheridan** [comment]
The official terminology is rollie.

**Comment by Iamgoofball** [comment]
:+1:

**Comment by JJRcop** [comment]
Help, anyone?

**Comment by dannno** [comment]
i think it's quite obvious that most people think this is bad

**Comment by Iamgoofball** [comment]
I think it's quite obvious that most people hate fun

**Comment by Xhuis** [comment]
Tell kosmos that GitHub approves and the pull has been merged without complaint.
Jokes aside, :smoking: :man_with_gua_pi_mao:
:+1:

**Comment by cookingboy3** [comment]
tgstation needs more blaze
:+1:

**Comment by Incoming5643** [comment]
:ambrosia: :+1: :joint: :-1: 

If only because ambrosia is too complicated a word to overuse as a bad joke

**Comment by JJRcop** [comment]
So, change to :rollie:?

**Comment by kingofkosmos** [comment]
:gun: :gun: :gun: 

If people don't want it, it's ok. I just wanted to :joint: it :faggot:

**Comment by Dorsisdwarf** [comment]
We've been adding too much fun lately. Therefore we need to correct this imbalance in the PR section.

**Comment by JJRcop** [comment]
>not getting FUCK or Controversial tags

**Comment by Cheridan** [comment]
>So, change to :rollie:?

yeah

**Comment by TZK13** [comment]
I had the idea of adding an ambrosia emoji as a BYOND subscriber only thing but I didn't know how to go about it, that would help gate them off a bit and would be a way better subscriber benefit than what there is now.

**Comment by JJRcop** [comment]
Don't worry guys this will be merged after it has been open for 420 days.

**Comment by Iamgoofball** [comment]
Based jordie

Smoke a tobacco rollie in his honor today

**Pull request merged**
