### PR TITLE
Curator's whip now makes a whip crack sound effect

### PR DESCRIPTION
**Pull request by CodeJack0711**
:cl: obscolene
soundadd: Curator's whip actually makes a whip sound now
/:cl:

why: Firstly: A leather whip makes a cracking sound, not a metal chain sound. ~~Secondly: It is already immensely overpowered with its 100% guaranteed disarm on hit, as well as doing 15 brute per hit (7 hits to crit). It now does stamina damage, which, when paired with its disarm, makes it great for nonharmful pacification rather than cheap killing.~~

### CODE REVIEW

**Comment by Jordie0608** [comment]
What's the source of the file? It appears to be an mp3 in an ogg instead of an ogg vorbis; I'm not sure if that'll cause problems for byond but it messes with audacity unless renamed/converted.

I've made an edit that's an actual ogg vorbis which doesn't have silence at the start and end of the file, it's significantly smaller: 44.8KB down to 16.9KB
https://file.house/gg7f.ogg

I also made another that cuts out whatever that quieter sound after the whip crack is, 13.9KB
https://file.house/hrZB.ogg

**Comment by XDTM** [comment]
If you're converting damage to stamina you should increase the force a bit, to account for the rapid regeneration of stamina damage.

**Comment by PKPenguin321** [comment]
Give it reach reee

**Comment by fonedsky** [comment]
you should use the whipcrack sound effect from johnny test

**Comment by obscolene** [comment]
@fonedsky it literally is, check the branch name

**Comment by Shadowflame909** [comment]
ONE MORE TIME.

**Review by ninjanomnom — CHANGES_REQUESTED** [review]
Not sure how I feel about the damage change but the sound seems fine, split up the balance change into another pr

**Comment by obscolene** [comment]
@ninjanomnom okay done AAAAAAHHHHHHHH!! AAAAAAAAAAAAAHHHHHHHHHHHH!!! AAAAAAAAAAAAAAAAAAAAAHHHHHHHHHH!! aAAAaaaAAaAAaAHAhGGHHHHASHHHhhhHHH!!!!

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
