### PR TITLE
Syndicate Hardsuit colored lights + Light level decrease

### PR DESCRIPTION
**Pull request by GunHog**
:cl: Gun Hog
tweak: The Syndicate and Shielded Syndicate Hardsuits now have green visor
lights.
del: These two hardsuits now have weaker helmet lights.
/:cl:

I am not sure I am happy with these colors. Some recommendations (Please post a hex code if it is not defined) would be appreciated.
**LIGHT LEVEL OF 3 Changes to Elite Hardsuit reverted.**
image

**OLD LIGHT LEVEL OF 4**
screenshot 2017-03-06 19 44 41

### CODE REVIEW

**Comment by coiax** [comment]
I dunno, it's not like they're glowing that much, make it a lot smaller.

**Comment by KorPhaeron** [comment]
This is getting a bit out of control

**Comment by chanoc1** [comment]
Yeah that is a little bit too much glow... also making it a little less yellow would be nice

**Comment by Ausops** [comment]
>nuke ops want to replicate 21st century green night vision so they add bright green led floodlights on top of perfectly working full colour night vision

ok!

**Comment by GunHog** [comment]
I think it was made that way so that Ops would be encouraged to switch to combat mode when on the station. Again, if you have a color recommendation, please post a hex code, we will be here all week if I do not ask!

**Comment by Ausops** [comment]
the colours are totally fine could  you reduce the radius of the colour while keeping the radius of the actually lit tiles?

**Comment by GunHog** [comment]
What light strength would you suggest?

**Comment by ShadowDeath6** [comment]
fiery*

**Comment by Incoming5643** [comment]
I don't like this, it makes it very easy to tell when nuke ops are about without actually seeing them because the colored glow is a dead giveaway. You could probably even tell on the opposite side of a wall.

❕ Most things don't need to have colored lighting ❕

**Comment by GunHog** [comment]
If you switch to combat mode while in station maintenance, you will not have any lighting at all! I am pretty sure that is why they make light only in EVA mode.

**Comment by TrustyGun** [comment]
i would decrease the range by 1 imo

**Comment by Sligneris** [comment]
I like actually seeing my surrounding as a nuke op.

**Comment by GunHog** [comment]
Reduced the light level by 1, now looks like this:

image

**Comment by ChangelingRain** [comment]
I think this should probably be normal light with a secondary tiny colored glow
Also like the elite hardsuit doesn't actually have orange light, it just has a standard light???

**Comment by Sligneris** [comment]
I had the same complaint with syndiborg and this one - this was actually the first comment. I simply forgot about NVG.

**Comment by GunHog** [comment]
I think this should probably be normal light with a secondary tiny colored glow
Also like the elite hardsuit doesn't actually have orange light, it just has a standard light???

I will revert the color for the Elite Syndie suit, then. And what do you mean by 'secondary tiny colored glow'?  If mean I should change the light color, please provide the hex code!

**Comment by Militaires** [comment]
elite hardsuit light is good keep it what hte fuck are you talking about joan

keep the sexy orange light

**Comment by optimumtact** [comment]
Lets hold off on too many coloured light changes for now - I know the feature is new and exciting but we dont' want to make the station look like a disco

:-1: from me

**Comment by GunHog** [comment]
That makes sense for common items like computers and other machines, but you do not see Ops/Hardsuit Traitors often enough for it count as "make the station look like a disco".

**Comment by PKPenguin321** [comment]
Dislike for the same reason I dislike swarmer lights

**Comment by GunHog** [comment]
I am told that MSO plans to fix the light bleed through walls, and this is not a hard-tell due to glowsticks. Also, you have no lights when your suit is in Combat Mode (which you should be using when you enter the station).

**Comment by PKPenguin321** [comment]
Are there orange glow sticks?

**Comment by GunHog** [comment]
I reverted the change to the Elite Hardsuits at Joan's request. Only the green ones are there now. (I am lazy and did not take a new picture, but I did edit the text)

**Comment by GunHog** [comment]
With great regret, I am closing this PR :cry: It would seem that none of the maintainers really want this.

I would be happy to re-open this if any maintainers have interest in merging it or any additional changes.

**Pull request closed without merging**
