### PR TITLE
*crack* *sip* Ahhhh. Yep, Removes ballgags was a good PR. They don't make PRs like 'em anymore.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: Thirty year old boomers can now sip their monster safely as God intended.
fix: Even if it's 9 in the morning on a Saturday.
fix: Even if your kid's trying to sleep because they were up all night shitposting.
fix: Yep. Times were good back then.
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
https://www.youtube.com/watch?v=BcxeZ4Wwdn0
PR theme

**Comment by Shadowflame909** [comment]
I'm glad you're here goofball. I enjoy this type of comedy

**Comment by Cyberboss** [comment]
I have friends that are 30 and are still the coolest cats

**Comment by bgobandit** [comment]
goof this is too far

**Comment by plapatin** [comment]
> https://www.youtube.com/watch?v=BcxeZ4Wwdn0
> PR theme

i just want to say something about that video link. do people actually fall asleep to the sounds of lawnmowers? why would someone make this?

**Comment by ma44** [comment]
>removal

**Comment by Iamgoofball** [comment]
this is abuse and the bot had a five hour delay

**Comment by plapatin** [comment]
based

**Pull request merged**
