### PR TITLE
[planetstation] mushroom people

### PR DESCRIPTION
**Pull request by Militaires**
kor told me to finish this

let me fix conflicts

### CODE REVIEW

**Comment by Militaires** [comment]
wow that's alot of conflicts

**Comment by TheDreamweaver** [comment]
What sort of traits we looking at

**Comment by Militaires** [comment]
i almost dont want to do this

**Comment by Militaires** [comment]
actually i dont

**Comment by PKPenguin321** [comment]
Thicc

**Comment by FantasticFwoosh** [comment]
They are going to be dismembered & devoured by dwarves anyway.

**Comment by Militaires** [comment]
if someone wants to take the code and do it on a new branch i'd be grateful but otherwise ill silence this **for now**

**Pull request closed without merging**
