### PR TITLE
Give the atmos jumpsuit/skirt some black overalls

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Just that, blatantly copied from the CE one...

atmosoverall2

atmosoverall
## Why It's Good For The Game
Atmos Techs get the short stick of the fashion in the engineering department.
Their jumpsuits/skirts are a copy of the Station Engineers but with the orange swapped to cyan, same for their winter coats.
Engineers have a second uniform with the hazard jumpsuits, ATs have none.
The backpack/satchel they spawn is orange and clashes a lot with their uniform.
They don't have access to Bandanas or Berets that engineers have (God bless for the second at least.)

So it is basically just the Firesuit + MODsuit, which just cover all your sprite and are mostly up only for emergencies.

And honestly... I just think it is cute that the "plumber job" will look like a plumber...
## Changelog
:cl: Guillaume Prata
imageadd: After too many Atmospherics Technicians ruined their uniforms by unwrenching a pipe and leaking plasma on top of it, NT's Clothing Department decided to attach some black overalls on the Atmospherics Technician's jumpsuits/skirts.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
either have this be an alternate jumpsuit buyable from the vendor or dont change it at all, you can get this almost identical look with a clothing attachment waistcoat, which is what this looks like, doesnt at all fit with atmos/engineering

**Comment by SinfulBliss** [comment]
It looks sorta similar to the barkeep's waistcoat which is more of a formal thing. Would make sense to include it as an attachment maybe like the waistcoat though

**Comment by GuillaumePrata** [comment]
> doesnt at all fit with atmos/engineering

The CE has been using overalls for years...
Look up Firefighter uniforms and you will see that most of them use overalls too.

**Comment by Serxule** [comment]
> > doesnt at all fit with atmos/engineering
> 
> The CE has been using overalls for years... Look up Firefighter uniforms and you will see that most of them use overalls too.

the style doesnt fit with atmos or engineering, the CEs jumpsuit barely makes sense as it is

**Comment by SomeoneYouProbablyKnow** [comment]
Idea gud but the sprite is just black bricks on top of the existing jumpsuit, i recommend you try remaking the sprite so that it actually looks sensible. And since spriting is hard at least try a recolor of the mining jumpsuit (those have actual overalls)

**Comment by CRITAWAKETS** [comment]
Atmos overalls should probably be a suit item instead, that way it also acts a replacement for engineering's hazard vest.

**Comment by GuillaumePrata** [comment]
> Idea gud but the sprite is just black bricks on top of the existing jumpsuit, i recommend you try remaking the sprite so that it actually looks sensible. And since spriting is hard at least try a recolor of the mining jumpsuit (those have actual overalls, or maybe im not thinking of tg)

The CE, Miner and now Atmos have the same overall sprite. Now making it look good as black instead of brown or white is something I struggled with and can definitely be improved.

**Comment by kawoppi** [comment]
looks neat! although the belt might make less sense here, since the shoulder-straps already keep it in place

**Comment by Twaticus** [comment]
this is weird

**Pull request closed without merging**
