### PR TITLE
Fixes movement on boxstation

### LINKED ISSUE #10810: Smooth pixel movement broken on box
It was broken by  the use of step_x and step_y on map edits by #10723.

### PR DESCRIPTION
**Pull request by Incoming5643**
By removing the airlock sign that had the offending step_x var edit on it.

The airlock is glass and surrounded by space, you don't need a sign for people to know it leads to space!

Fixes #10810

### CODE REVIEW

**Comment by Incoming5643** [comment]
Don't mix up step_x/step_y with pixel_x/pixel_y. It could save your life!

**Comment by Incoming5643** [comment]
It would be nice if the map merge tool automatically scrubbed step_x step_y commands, but I don't know how practical that is.

**Comment by Iamgoofball** [comment]
ahahahahaha

this is why we make Travis check for step_x/y like BS12 does

**Comment by MrStonedOne** [comment]
Thats a stupid way of fixing it..

just remove the step_x step_y parts

**Pull request merged**
