### PR TITLE
Beepsky's New Groove

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request
Adds movement states to the secbot, and alters their charge state to wave their baton forward. 

Beepsky

Beepsky-charge

## Why It's Good For The Game
I always assumed that Beepsky just floats in the middle of the tile, wasn't until I looked at some fanart and another pointed this out that I realized this was incorrect. This gives more attention to the wheels of Beepsky, which I think is a neat thing.

## Changelog
:cl:
add: Beepsky now bumps around on its wheels when patrolling for crime.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
oh lawd he comin
he-comin

**Comment by Akrilla** [comment]
Wtf beepsky doesn’t float?

**Comment by MMMiracles** [comment]
groove

**Comment by Fikou** [comment]
can you make the baton spin since canonically beepsky flails the baton around to hit you

**Comment by Shapsy** [comment]
MAKE BEEPSKY *FLIP WHEN HE STUNS

**Comment by zombiegums** [comment]
Maximum cute.

**Comment by actioninja** [comment]
this is great and I can't wait for the inevitable bitching about how awful this is.

**Pull request merged**
