### PR TITLE
Makes all machines use the robot font. 

### LINKED ISSUE #8575: Holopads do not use the robot font
What it says on the tin. Holopad speak shows up normally, which it probably shouldnt.

### PR DESCRIPTION
**Pull request by theOperand**
Fixes #8575

Technically also does something that's not a fix, so if @cheridan wants to DNM this its fine by me.

### CODE REVIEW

**Comment by RemieRichards** [comment]
>maniasureamgoodatcomingupwithgooddescriptivebranchnamesdontyouthinksobecausethisbranchnameisverygoodanddescriptive

>maniasuream

> man I a sure am

you suck Miauw

**Comment by Miauw62** [comment]
;_;7

**Comment by Aranclanos** [comment]
👌

**Comment by Iamgoofball** [comment]
ahahahaha

:+1:

**Comment by Amnestik** [comment]
I guess this doesn't apply to robots?

**Comment by Miauw62** [comment]
it does

**Comment by Cheridan** [comment]
Beep boop

Nah this looks fine

**Comment by kingofkosmos** [comment]
Would it be possible to have them use speech bubbles as well? It would look cute on bots.

**Comment by Miauw62** [comment]
yeah, probably, but i dont into image manipulation so

**Comment by RemieRichards** [comment]
This is largely a fix.
Adding speech bubbles to machines would be a feature.
Plus Miauw's a silly and doesn't into image manipulation.

**Pull request merged**
