### PR TITLE
Reworks spray tan overdoses so they actually make sense

### PR DESCRIPTION
**Pull request by ghost**
:cl: That Really Good Soda Flavor
tweak: Changed spray tan overdoses to be more realistic.
/:cl:

So this meme is older than a decade, but that doesn't mean it's a bad one

# you can't just go around mixing and matching references with things you make up

there was like a charlie sheen reference or something

### CODE REVIEW

**Comment by lordpidey** [comment]
Won't this cause douchebag lizardmen to grow spiky hair?

I'm.... actually okay with this.

**Comment by kevinz000** [comment]
whatever if someone ruins my snowflake i'll valid their ass anyways.

**Comment by Armhulen** [comment]
Make it add beach bumbian

**Comment by Really-Good-Soda-Flavor** [comment]
I was thinking about that, but people would use it as a mute toxin, and space drugs already add it anyway.

**Pull request merged**
