### PR TITLE
Adds patting!

### PR DESCRIPTION
**Pull request by Arianya**
:cl: Gun Hog & Arianya
add: You can now hug someone while aiming at the head, eyes or mouth to give them a pat on the head!
experiment: Please be careful who you pet, certain people have divine protection.
/:cl:

Closes #23989 as its an improvement upon it.

As noted in the other PR, re-opened PRs must have added functionality or other changes to make them worthwhile considering afresh.

I hope this meets with the necessary approval.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
eat shit saltboy

**Comment by Cheridan** [comment]
what

**Comment by PKPenguin321** [comment]
funny joke

**Comment by PKPenguin321** [comment]
basically he realized there was no disproving my argument so he did this instead to distract everybody

**Comment by anconfuzedrock** [comment]
what was your argument I missed it

**Comment by PKPenguin321** [comment]
its still there in the other PR go find it!

**Comment by Arianya** [comment]
@PKPenguin321 I'm not sure why you're upset? I'm obliging by your request that re-opened PRs have added functionality or changes made.

@Cheridan If someone tries to pet a protected user, it gibs the initiator.

**Comment by PKPenguin321** [comment]
nice distraction but patting is gay

**Comment by Arianya** [comment]
@PKPenguin321 So is hugging.

Please remove all physical contact from SS13

**Comment by anconfuzedrock** [comment]
r u fuckin srs rn theres a major ass difference between pats and hugs fucktardo

**Comment by Arianya** [comment]
@anconfuzedrock Actually theres no difference

because they both just post a line of text in a online space man simulator

oh and they play a minor sound effect i guess

**Comment by PKPenguin321** [comment]
rock stop falling for the distraction

**Comment by Iamgoofball** [comment]
this lets me gib anyone I want

**Comment by Arianya** [comment]
I figured you needed a safe zone so you wouldn't get triggered.

Also that implies you play.

**Comment by Armhulen** [comment]
i think he'll play a lot more if he has ei nath hands

**Comment by RemieRichards** [comment]
@Armhulen he doesn't, this gibs him.
If anyone touches goof, they gib, he's that smelly.

**Comment by Arianya** [comment]
Yeah let me just state this clearly to clear all misunderstanadings:

If someone tries to pat goofball, they get gibbed

There is no other interaction with his ckey. I considered adding that goofball gets gibbed if he tries to pat but figured that this would be code bloat since he wouldn't use it anyway.

**Comment by Saegrimr** [comment]
Why can't we target the groin for a good old sportsmanlike american football pat.

**Comment by PKPenguin321** [comment]
meme pr close

**Pull request closed without merging**
