### PR TITLE
Adds sound effects to the tape recorder

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

Adds sound effects to the tape recorder.

https://streamable.com/vk3wda

Doesn't add the sound of the tape being inserted or removed or the playing/recording hum. Maybe another day. Would also like to add handling sounds to tapes like other objects have.

## Why It's Good For The Game

Tape recorders make satisfying sounds. Makes the object feel more real.

## Changelog
:cl: cacogen
soundadd: The tape recorder makes sounds when you interact with it
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
What's the source of these sounds? Do you have the license?

**Comment by cacogen** [comment]
The sources are in the metadata of the .ogg files.

https://freesound.org/people/andrewweathers/sounds/25421/
https://freesound.org/people/Pogotron/sounds/61075/
https://freesound.org/people/Bertrof/sounds/351567/

**Comment by optimumtact** [comment]
changelog is misformatted

**Comment by cacogen** [comment]
Thanks

**Pull request merged**
