### PR TITLE
Makes it so gate scanners can detect Felinids

### LINKED ISSUE #47654: gate scanners cant be set to detect feli*nid
i think it uses the "choosable roundstart species" which dont have them available

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Gate scanners can now detect Felinids 

fixes #47654

## Why It's Good For The Game

You can now find out if someone is a metahgang race and imprison them for their horrible crimes against Nanotrasen and all of spess.

(someone wanted them to be detectable and since it was an easy add I went ahead and done did the deed) 

## Changelog 
:cl: PepperPrepper
add: scan gates can now detect Felinids 
/:cl:

### CODE REVIEW

**Comment by PepperPrepper** [comment]
OH MY GOD NO

**Comment by PepperPrepper** [comment]
FUCK WRONG BRANCH HAHAHAHHAHAH

**Comment by PepperPrepper** [comment]
Leaf me alone I'm still new

**Comment by PepperPrepper** [comment]
okie fixed now.

**Comment by HomocidlePancakes** [comment]
It should check for the cat ears/tail, instead of the species

**Comment by PepperPrepper** [comment]
Then it would be checking for organs not what species the mob has. Which goes against the gates function.

**Comment by FantasticFwoosh** [comment]
This PR and subsequent successful salvage of a code oopsie-woopsy, deserves reddit gold :+1:

**Comment by HomocidlePancakes** [comment]
Oh wow. I didn’t know scanners can trigger on certain species. Well, shit.

**Comment by daklj** [comment]
sorry man but theyll get removed by the time this gets merged

**Comment by KomradeSpectre** [comment]
image

**Comment by PepperPrepper** [comment]
@KomradeSpectre  well it's a damn good thing this was not a webedit then.

**Comment by KomradeSpectre** [comment]
I mean, it did pass travis, and didn't get a verified tag, but
image

**Comment by PepperPrepper** [comment]
@KomradeSpectre That was because I was using the wrong branch (from an older pull). Every commit other than uhhh has nothing to do with this pull request and is only here because I'm dumb and can't git right

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
