### PR TITLE
Fixes the debug chemical synthesizer

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Fixes the debug chemical synthesizer, now it actually dispenses reagents instead of just yelling OUT OF RANGE.
Also changed the message to REAGENT NOT FOUND, which seems more clear.

### CODE REVIEW

**Comment by Lett1** [comment]
OUT OF RANGE is a reference to that coffee machine scp. Leave it in.

**Comment by XDTM** [comment]
It's no longer an SCP, it's been converted to a debug-only tool and flavor doesn't matter if you just want to test a reagent.

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Review by ExcessiveUseOfCobblestone — COMMENTED** [review]
Doesn't L61 return a type? I think it would be cool to make it clear you can input those as well (especially since this is OOC debug hooplah)

**Comment by XDTM** [comment]
As it is coded right now you can't input types if i read the code correctly, you have to search for them by name

**Comment by ExcessiveUseOfCobblestone** [comment]
What does L61 do then now that ID is gone lol.

**Comment by XDTM** [comment]
searches a pre-generated chem list by name to get the path, if i'm not mistaken

**Comment by ExcessiveUseOfCobblestone** [comment]
I want to say those are instances, and unlike atoms instances of datums won't return the name (since by default they don't have a name var).****

I'll check it out and get back to you soon (tm)

***citation very much needed yikes

**Comment by ExcessiveUseOfCobblestone** [comment]
I never did check this out but it's ok

**Pull request merged**
