### PR TITLE
Remove BIO armor flag and replace with DISEASE_IMMUNITY flag

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This removes the `BIO` armor type and replaces it with a `DISEASE_IMMUNITY` flag.  This is not unprecedented.  We have removed past armor types that were underutilized, (`MAGIC`, `RAD`, `TOX`) see:

- #62265
- #62594
- #65487

---

This is how many files and times BIO is used in the codebase.

Code_rBfERXxXFX

Yet, it only matters in two tiny and insignificant spots:

- To check if a mob can be infected via airborne disease as a hardcoded value `BIO_ARMOR_VALUE > 25` so it's essentially a boolean.  
- Neurospit is the only projectile to use BIO as it's damage type but it does 5 damage... lol

So that's not really a good enough reason to keep it in.  It _is_ code bloat and should be removed.

## Why It's Good For The Game

Removing code bloat is good.

## Changelog

:cl:
del: Remove BIO armor type
code: Add DISEASE_IMMUNITY flag to biosuits and relevant clothing
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
you shouldnt be opening drafts for prs that arent testmergeable yet

**Comment by SmArtKar** [comment]
This doesn't make much sense cuz some items have 1-99 bio protection. I also am using BIO armor in my xenobiology rework and I hope this PR doesn't get merged.

**Comment by Fikou** [comment]
> This doesn't make much sense cuz some items have 1-99 bio protection. I also am using BIO armor in my xenobiology rework and I hope this PR doesn't get merged.

xenomorph spits also use BIO armor

**Comment by timothymtorres** [comment]
> you shouldnt be opening drafts for prs that arent testmergeable yet

[From the Pull Request Process](https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#pull-request-process)

> If your pull request is not finished, you may open it as a draft for potential review. If you open it as a full-fledged PR make sure it is at least testable in a live environment. Pull requests that do not at least meet this requirement will be closed. You may request a maintainer reopen the pull request when you're ready, or make a new one.

I opened it as a draft since it's still a WIP that shouldn't take too long for me to finish.

**Comment by SmArtKar** [comment]
Also some projectiles use BIO armor. This isn't code improvement, this PR removes one feature and replaces it with a shitty simple another one.

**Comment by timothymtorres** [comment]
> Also some projectiles use BIO armor. This isn't code improvement, this PR removes one feature and replaces it with a shitty simple another one.

A lot of things that should be using BIO use the `permeability_coefficient` instead.

**Comment by SmArtKar** [comment]
> `permeability_coefficient`

you are making simple things cancer to use, permeability_coefficient is much harder to check/assign to object/projectiles rather than BIO armor. Again, this _isn't_ a code improvement but rather balance/feature and removal

**Comment by Ryll-Ryll** [comment]
> This doesn't make much sense cuz some items have 1-99 bio protection. I also am using BIO armor in my xenobiology rework and I hope this PR doesn't get merged.

Bio armor values have always been funny money that no one understands or knows how they work, there's no reason to have them be 1-99 and I definitely consider gutting them in favor of a more easily understood system an improvement

**Comment by timothymtorres** [comment]
This is not unprecedented.  We have removed past armor types that were underutilized, (`MAGIC` and `RAD`) see:

- #62265
- #62594

---

This is how many files and times BIO is used in the codebase.

Code_qRXH1Kqw4K

Yet, it only matters in two tiny and insignificant spots:

- To check if a mob can be infected via airborne disease as a hardcoded value `25 >` so it's essentially a boolean.  
- Neurospit is the only projectile to use BIO as it's damage type but it does 5 damage... lol

So that's not really a good enough reason to keep it in.  It _is_ code bloat and should be removed.  I would recommend you rework your BIO damage type for the xenobiology rework to something like the RAD PR linked above.  Mothblocks made it into a status effect.

Also I am doing this because I'm trying to improve virology code.  I'm not trying to rework it completely, but I do want to expand some features to make it more robust.  This includes killing deprecated or useless code which is what the BIO t

**Comment by SmArtKar** [comment]
> This is not unprecedented. We have removed past armor types that were underutilized, (`MAGIC` and `RAD`) see:
> 
> * [Modernizing Radiation -- TL;DR: Radiation is now a status effect healed by tox healing, and contamination is removed #62265](https://github.com/tgstation/tgstation/pull/62265)
> * [Deletes magic armor #62594](https://github.com/tgstation/tgstation/pull/62594)
> 
> This is how many files and times BIO is used in the codebase.
> 
> Code_rBfERXxXFX
> 
> Yet, it only matters in two tiny and insignificant spots:
> 
> * To check if a mob can be infected via airborne disease as a hardcoded value `25 >` so it's essentially a boolean.
> * Neurospit is the only projectile to use BIO as it's damage type but it does 5 damage... lol
> 
> So that's not really a good enough reason to keep it in. It _is_ code bloat and should be removed. I would recommend you rework your BIO damage type for the xenobiology rework to something like the RAD PR linked above. Mothblocks made it into a status effect.
> 
> Also I am doing this because I'm trying to improve virology code. I'm not trying to rework it completely, but I do want to expand some features to make it more robust. This includes killing deprecated or useless code which is what the BIO armor type is.

"rework your BIO damage into a status effect"
You want me to refactor SLIME FEEDING ON YOU INTO A STATUS EFFECT?
image

**Comment by Ryll-Ryll** [comment]
I value getting rid of the bio armor from 200 files far more than having a special armor values for slime feeding

**Comment by Fikou** [comment]
> I value getting rid of the bio armor from 200 files far more than having a special armor values for slime feeding

we should be getting rid of permeability coefficient not bio armor

**Comment by YakumoChen** [comment]
I thought blobs relied on bio armour for damage?

**Comment by JohnFulpWillard** [comment]
I tried doing this in the past too, I stopped because I got busy with other stuff and never came back to it.
I went the other route and made it an Element instead. This is probably the better solution, and while it does have a lot of balance implications, I think it's better for the game overall.

**Comment by Mothblocks** [comment]
Fikou is currently working on a PR to merge permeability with bio resistance, which I think is a good idea. I'll be merging that one if he can make it in a reasonable timeframe.

**Comment by Fikou** [comment]
> This removes the `BIO` armor type and replaces it with a `DISEASE_IMMUNITY` flag. This is not unprecedented. We have removed past armor types that were underutilized, (`MAGIC`, `RAD`, `TOX`) see:
> 
> * [Modernizing Radiation -- TL;DR: Radiation is now a status effect healed by tox healing, and contamination is removed #62265](https://github.com/tgstation/tgstation/pull/62265)
> * [Deletes magic armor #62594](https://github.com/tgstation/tgstation/pull/62594)
> * [changes projectile's armor resistance flag to "armor_flag" #65487](https://github.com/tgstation/tgstation/pull/65487)

TOXIN was literally added as a bugged oversight from the radiation pr, it proves no fuckin point
MAGIC was a janky way of making magic projectiles penetrate all armor, it also proves no fucking point
RAD became pointless as we completely reworked radiation to be a boolean yes/no

BIO is something that should be general biohazard protection, it is a good purpose in a video game where there are biohazards.
we have WOUND armor, which serves a very similar purpose, of affecting your rolls in checks and wound power

**Comment by timothymtorres** [comment]
Let's pretend there are many people contributing code to a **hypothetical codebase** that is quite large and growing.  

You come across a variable named `foo` that is a percent value from 0% - 100%. Every time a new object gets created `foo` must be declared to the object.  Some objects have set `foo = 45%`, `foo = 20%`, `foo = -10%`, etc.  Most of the time `foo` is either: 

- `foo = 0%`
- `foo = 100%`

As the codebase grows, `foo` must be declared manually to every new object.

But there is a problem!  Nobody bothered to look at what `foo` does and just mindlessly c/p the value from object to object assuming it had some purpose.  After digging deep into the code, you realize to your horror that `foo` is extremally redundant.  

- 99% of objects using `foo` ignore it completely.  (dead code)
- The precent values don't matter since `foo` only checks if `foo > 25%` when it's used

What would you do?

Wouldn't the ideal solution be to refactor `foo` so that it's now a Boolean?
Wouldn't it be a good idea to limit the scope of `foo` to _only_ the 1% of objects that need it?

Is this making sense now?  You remove all the dead and deprecated code in the present.  For the future you don't have to declare `foo` in every object, which is annoying and tedious.

---

Guess what `foo` represents here?  It's `BIO` armor.  Out of the 494 times it is declared in our codebase, only 16 objects actually use it for virology code.

https://github.com/tgstation/tgstation/blob/aeaffbd96bd0276d4c5b250a2485791c6f75e884/code/datums/diseases/_MobProcs.dm#L148-L149

It only checks if `BIO > 25` for helmets and masks thus it should be a Boolean and not a number.  

Neurospit is such a niche thing that:

- It's super rare
- It's only 5 damage
- `BIO` doesn't affect the stun
 
We should just make Neurospit use acid or burn instead.

---

If you looked at the Radiation PR you would notice that @Mothblocks removed a ton of `RAD = 25`, `RAD=100` for objects that had no purpose for the values.  This is what I'm trying to do.  I'm trying to get rid of the 478 objects that don't need `BIO`.

I hope this makes sense and isn't coming across as condescending.

**Comment by ATH1909** [comment]
don't blobs check bio armor?

**Comment by Fikou** [comment]
> Every time a new object gets created foo must be declared to the object. 

that is completely not true, you can omit bio armor. just like you can omit wound armor.

**Comment by tralezab** [comment]
alternate got merged

**Pull request closed without merging**
