### PR TITLE
Fixes silo runtime.

### PR DESCRIPTION
**Pull request by AnturK**
Unicode change revealed another material nonsense, who'd expect that.

### CODE REVIEW

**Review by SpaceManiac — APPROVED** [review]

**Comment by adamkad1** [comment]
Not fixed though

**Comment by SpaceManiac** [comment]
@adamkad1  care to provide more information

**Comment by adamkad1** [comment]
> @adamkad1 care to provide more information

Silos, and anything linked to them will not accept material when empty. you must smelt ores into the silo to be able to put in processed materials

**Comment by AnturK** [comment]
That's not really related to this change. Also i don't see anything wrong with silos as of 7eb788a01230371e24c9ee79cd6f0714e7286a45, open an issue with instruction on how to reproduce please.

**Pull request merged**
