### PR TITLE
Change machine frames and girders deconstruction step

### LINKED ISSUE #9332: Construction changes are unwarranted and not fun
Seriously, there was never even an opportunity to provide feedback on them, just "We're adding this for /consistency/"

They're fucking awful. Going blind moving machine frames, having girders be a huge pain in the ass - It's not fun, it just adds mindless tedium to the game. I don't think anybody cares about this being 'realistic' or whatever, or 'consistent' -  This was actually a pretty big change and I've heard nothing but negative feedback on it.

Revert this shit. Put a poll up or whatever but GET. IT. OUT.

### PR DESCRIPTION
**Pull request by optimumtact**
They now use the screwdriver instead of the welding tool

On top of that I added a check to ensure you can't disassemble the same girder
more than once to farm materials

Resolves #9332

### CODE REVIEW

**Comment by optimumtact** [comment]
Now that I think about it, it makes more sense to use the wrench in this step

**Comment by ike709** [comment]
Make it like it was before somebody ruined it.

**Comment by Man-Shroom** [comment]
Just put it back to the wrench step, and crowbar for making it pullable, there was a reason it was like that since literally the beginning of SS13.

**Comment by optimumtact** [comment]
I'm afraid I don't have time to do that full refactor, if someone else would want to pick it up thats fine though.

**Comment by SconesC** [comment]
:+1: I hope this makes both sides happy.

**Comment by Cheridan** [comment]
thanks

**Pull request merged**
