### PR TITLE
Removes the action button from chem implants

### PR DESCRIPTION
**Pull request by improvedname**
Sorry i heard you like to powercreep with stuff you can make with one chem macro every round?

:cl: Improvedname
fix: chem implants can no longer be self triggered
/:cl:

### CODE REVIEW

**Comment by DaxDupont** [comment]
salt

**Comment by 81Denton** [comment]
Hey buddy, I think you've got the wrong door, the citadel club's two sectors down.

**Comment by improvedname** [comment]
no sorry im at the right club where i press 1 button to win the game

**Comment by arsserpentarium** [comment]
Seriously,close this. Don't put shame on you.

**Comment by uraniummeltdown** [comment]
back to Bay

**Comment by improvedname** [comment]
the only shame is people abusing the chemical implant roundstart for validhunting with stun reducers if you want to validhunt use tooth pills aka dental implants

**Comment by cebutris** [comment]
Who hurt you?

**Comment by improvedname** [comment]
i-isiah d-did

**Comment by francinum** [comment]
This can still be triggered via `*deathgasp`

**Comment by improvedname** [comment]
atleast deatgasp gives off an warning

**Comment by Tlaltecuhtli** [comment]
wow lets remove the only not shitty thing medical can build with the lathe

**Comment by Iamgoofball** [comment]
Why do we have chem implants when we have pill implants

**Comment by 81Denton** [comment]
You can trigger them remotely. Implant a baddie with a deathmix implant and tell him to behave.
He acts like an antag, you hit the button and ded

**Comment by epochayur** [comment]
baw i ded

**Comment by improvedname** [comment]
except when you can use it manually which removes the whole point of implanting a baddie with a deathmix as they can just drink a cup water and eat a banana to get your whole wimpy mix purged

**Comment by AlexTheSysop42** [comment]
Maybe have an option on the implant pad to disable the action button so a baddie can't activate it when they're prepared (i.e. taking a swig of pentacid and/or charcoal right before activation), but keep it otherwise, it's balanced (sci might not research it, you need mats, and you can always just use toothpills).

**Comment by improvedname** [comment]
the whole point is that theres a captain that abuses this roundstart and just use it manually with stun reducing shit since chemical implants do not require cooperation you can instantly inject multiple midcombat theres no downside to it

**Comment by AlexTheSysop42** [comment]
that specific situation is pretty powergamey, especially for the captain 

>inject multiple mid-combat

That's definitely a problem, maybe make self-implanting chem implants (or maybe any implants) take a few seconds instead.

**Comment by optimumtact** [comment]
I'm merging this in 24 hours

**Comment by arsserpentarium** [comment]
why?

**Comment by optimumtact** [comment]
Because people I explicitly trust very much about the design of the game have said it's a bad mechanic and it was never intended to be used this way. These implants were for the warden to use on prisoners or his security officers (as a heal mix)

not for a self actionable adrenal shot

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Clean up your PR body or I'm closing it and stealing it

**Comment by 81Denton** [comment]
@optimumtact In that case *deathgasp activation should probably be removed too

**Comment by Iamgoofball** [comment]
That's a leftover from explosive implants I think.

**Comment by blobbernaut** [comment]
I love how this was merged despite it clearly being not wanted based on the downvotes

**Comment by optimumtact** [comment]
want is not enough to determine the future, you are foolish if you think anything runs truly on group beliefs alone.

**Pull request merged**
