### PR TITLE
Makes asay brighter orange

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by rustledjimm** [comment]
I dunno this one hurts my eyes what's wrong with our brown.

**Comment by Spaceinaba** [comment]
much cuter and has a better aesthetic than beer vomit brown

**Comment by obscolene** [comment]
> No player references

fuc kyou pkp i clicked on this PR just to say that

**Review by MrsTonedOne — COMMENTED** [review]
Looks orangered. like reddit

:+1:

**Comment by optimumtact** [comment]
that's cause it's the html colour orangered

**Pull request merged**
