### PR TITLE
Adds Prisoner to dynamic's protected roles list

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request
Before Cyberboss allowed the role to be merged he required that I exempt prisoners from all antag roles. I didn't think of dynamic and didn't configure it appropriately. This should take care of it.

## Why It's Good For The Game
It makes the role function as intended, without the ability to roll antag.

## Changelog
:cl:
fix: Prisoners are now protected from rolling antag on Dynamic
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
This is merely a config change on the repo, it wont do anything on the live servers. If you want this to be default, add prisoner to the protected roles lists of every ruleset, i.e.
image

**Comment by RaveRadbury** [comment]
I did that before the original PR was merged, yet here we are. They should be like this in the config by default for anyone who is hosting the code. I'll contact headmins to get the config adjusted for our servers.

**Comment by RaveRadbury** [comment]
Thanks for the help, Kriskog!

**Comment by kriskog** [comment]
You need to add them to the midround rulesets that apply as well. The wizard one is not needed, as it pulls people before job assignment.

**Comment by RaveRadbury** [comment]
It seems like midround traitor is the only one that pulls from the existing crew?

**Comment by kriskog** [comment]
That should be correct, so long as prisoners cant latejoin.

**Comment by RaveRadbury** [comment]
Prisoners shouldn't be able to late join but that is another thing that I messed up and need to take care of (disallowing prisoner job slots from the ID console) I'll get that going right now

**Comment by RaveRadbury** [comment]
#49886 Merged so now yeah no more latejoining prisoners.

**Review by kriskog — APPROVED** [review]

**Pull request merged**
