### PR TITLE
Actually make notes on airlocks animate when the airlock opens

### LINKED ISSUE #63979: Open airlocks with pinned paper let it float
## Round ID:

None, seen on-server, reproduced locally

## Reproduction:

1. pin paper / photo to airlock
3. open it
3. floating paper
7. get burned as a witch

### PR DESCRIPTION
**Pull request by Tastyfish**
## About The Pull Request

Notes on airlocks didn't animate because there was no code to do so. Also the function to pick note icon_states had a terrible name.
* Also added missing note sprites, and renamed the original ones to match the frame suffix format.
* Tested for both states of paper, and photos as well.
* Closes #63979

## Why It's Good For The Game

airlock

## Changelog

:cl: tastyfish
fix: Papers and photos pinned to airlocks now actually animate.
/:cl:

### CODE REVIEW

**Comment by Tastyfish** [comment]
done

**Comment by Ghommie** [comment]
I have a question, how come we can read notes on airlocks when these ones are open and the notes are visually gone? I know it's not a bug, but it's bothersome lack of foresight from the mind behind these.

**Comment by Tastyfish** [comment]
> I have a question, how come we can read notes on airlocks when these ones are open and the notes are visually gone? I know it's not a bug, but it's a bothersome lack of foresight from the original mind behind these.

I feel like that's an edge case argument on par with using computers when you're not facing the screen.

**Comment by Ghommie** [comment]
Yea, you're right.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
