### PR TITLE
That part where I make the fishing minigame easier without reworking it completely.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This PR tones down the gravity and reeling acceleration values of the bait by 1/5 and implements a "brake", so that the bait will decelerate toward zero velocity more rapidly, making it easier to control.

## Why It's Good For The Game
The fishing minigame is too hard (even tho the fish tends to hug the bottom of the minigame slider on the TGUI, for me), lag or no lag. The bait feels too slippery and moves too fast.

Beside, Mothblocks has called #78052 bs, and there's a chance he may be right, though it would be difficult to make a proper comparison while the old UI lacks the extra alleviation to the user experience.

## Changelog

:cl:
balance: The fishing minigame should be easier now.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
regardless of it all, I think the non-TGUI version of it looks way better and doesnt block the game as much as the tgui menu.

**Comment by carlarctg** [comment]
thank you so much

**Comment by CCC23** [comment]
thank god no more 3000 mile an hour fish

**Comment by Mothblocks** [comment]
> regardless of it all, I think the non-TGUI version of it looks way better and doesnt block the game as much as the tgui menu.

timing puzzles should not be being done on the server

**Comment by EricZilla** [comment]
Oh thank god. For what a pain it is to fish, and how low the chance of getting a catch is, the game itself being horsetalk was pretty frustrating

**Pull request merged**
