### PR TITLE
Removes the mining asteroid

### PR DESCRIPTION
**Pull request by Cyberboss**
See #24168

### CODE REVIEW

**Comment by Militaires** [comment]
nostalgia wave incoming

**Comment by Buggy123** [comment]
It should be a escape shuttle instead. The entire asteroid.

**Comment by Arianya** [comment]
Improve don't rem- oh. Hm. I guess Kor beat you to that one.

**Comment by Supermichael777** [comment]
On the one hand lava land kinda deserves its own surface station. on the other hand apparently mining is way better now.

**Comment by ShadowDeath6** [comment]
Is there an asteroid ruin with the old mining fauna on it, I know their icons are still used in the parent path so it's feasible

**Comment by calzilla1** [comment]
>It should be a escape shuttle instead. The entire asteroid.
This sounds fucking hilarious

**Comment by WJohn** [comment]
RIP asteroid, you will be missed.

**Comment by KorPhaeron** [comment]
cyberboss farming those line changes for top contributor

**Comment by optimumtact** [comment]
Now this is more like it for gettign that ultra high removal count

**Comment by Incoming5643** [comment]
gonna cut up the more memorable parts of this and space ruin em

**Comment by Haevacht** [comment]
Drop it is a space ruin later if fixed up or something, but for now, pull the trigger piglet.

**Comment by kevinz000** [comment]
Please no.

**Comment by KorPhaeron** [comment]
My victory is complete

**Pull request merged**
