### PR TITLE
Replaces callbacks in signals with simple proc paths

### PR DESCRIPTION
**Pull request by ninjanomnom**
## About The Pull Request

This removes the use of callbacks in signals. There are multiple benefits and a couple downsides to this.

Pros:
- Less memory usage per registered signal
- Signal registration has slightly better performance
- Signal sending has an even smaller benefit to performance but the amount is so minuscule it doesn't really mean anything
- You can no longer register signals such that a third party is in charge of relaying a signal between two other objects. This prevents a whole class of qdel bugs.
- You can no longer provide static arguments to receiver procs. If you need a new argument then handle your state properly instead of hiding it in callbacks.
- Fixes one of the reasons that named arguments don't work in signals. Doesn't make them functional though (yet)

Cons:
- You can no longer call global procs with signals. This could be changed if we want this to be supported.
- You can no longer provide static arguments to receiver procs. This means you can't easily provide one off variables for a particular usage without new vars stored in the object itself.

Some really rough memory profiling shows that this saves about 20-30mb memory roundstart.

Also this pr fixes signals behaving slightly differently when called with one vs many receivers.

### CODE REVIEW

**Comment by optimumtact** [comment]
can you add global components that can register for signals on many objects pls

**Comment by ninjanomnom** [comment]
I've been working on that and making it not awful code or syntax has been a real pain

**Comment by optimumtact** [comment]
is this ready?

**Comment by ninjanomnom** [comment]
It has been yeah. Was ready the day I opened the pr

**Pull request merged**
