### PR TITLE
Adds fishing! Now you can fish carps!

### PR DESCRIPTION
**Pull request by Aranclanos**
image

### CODE REVIEW

**Comment by bear1ake** [comment]
I want this stuff!

**Comment by PKPenguin321** [comment]
somebody revive this
@Iamgoofball ??

**Comment by Iamgoofball** [comment]
already tried #9913

**Comment by bobbahbrown** [comment]
somebody revive this
@Iamgoofball ??

**Comment by PKPenguin321** [comment]
Same

**Comment by Shadowflame909** [comment]
What up olden people. I like the way those old security sprites look.

**Comment by theOperand** [comment]
bring aran back from the dead 2019

**Comment by Aranclanos** [comment]
hey

**Comment by theOperand** [comment]
yo

**Comment by Fikou** [comment]
somebody revive this
@Iamgoofball ??

**Comment by cacogen** [comment]
please tell me this isn't actually a joke i need this

**Pull request closed without merging**
