### PR TITLE
colossus now enrages on sandstone golems

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

colossus now enrages on sandstone golem the same way it does on carp users
i dont know what enrage does but it seems cool

## Why It's Good For The Game

sand golems cheese colossus hard

## Changelog
:cl:
balance: colossus now enrages on sandstone golems
/:cl:

### CODE REVIEW

**Comment by TheMidnightRose** [comment]
So what you are saying is. Sandstone golems now ensure that on sight, Colossus will chase them to the ends of the wastelands to ensure they die. Enraging Colossus normally only happens if someone is a Sleeping Carp user, as it forces Colossus to chase you and melee you with about 30-40 brute damage attacks.

**Comment by Fikou** [comment]
> So what you are saying is. Sandstone golems now ensure that on sight, Colossus will chase them to the ends of the wastelands to ensure they die. Enraging Colossus normally only happens if someone is a Sleeping Carp user, as it forces Colossus to chase you and melee you with about 30-40 brute damage attacks.

yes

**Comment by XDTM** [comment]
It's worth noting that sandstone golems also have high brute resistance, so this might just make them able to tank colossus while they drag it to, say, the mining shuttle

**Comment by Fikou** [comment]
> It's worth noting that sandstone golems also have high brute resistance, so this might just make them able to tank colossus while they drag it to, say, the mining shuttle

cant you do that already?? im pretty sure colossus follows you even if its slow

**Comment by XDTM** [comment]
yeah, but it's gonna be faster and with no risk of a stray bolt destroying the shuttle console, i imagine (unless enraged colossus keeps shooting anyway)

**Comment by Fikou** [comment]
golems are slow and the only armor you'll get is like a bone helmet or something when colossus has 40 armor penetration, i think its the lesser of 2 evils than just letting sand golems with a crusher kill colossus without any effort

**Comment by HomocidlePancakes** [comment]
Alternatively, you can make colossus deal burn damage on enrange

**Comment by improvedname** [comment]
The point is that sandstone golems can't be damaged by the deathbolts.
And combine that with a KA its gauranteed easy megafauna kill

**Comment by Shadowflame909** [comment]
nightmares get psuedo sleeping carp as well.

**Comment by Fikou** [comment]
> nightmares get psuedo sleeping carp as well.

owen pimple

**Comment by CRITAWAKETS** [comment]
pro free golem meme strat:
step 1) do the free golem stuff until you have the legacy
step 2) become sandman
step 3) make ripley mk1
step 4) enrage colossus
step 5) run to the mining shuttle
step 6) send the colossus over to the station and enjoy the fireworks
step 7) this is legal in the rules for free golems to do

**Comment by AdamElTablawy** [comment]
@CRITAWAKETS since when lmao

**Comment by ATH1909** [comment]
> yeah, but it's gonna be faster and with no risk of a stray bolt destroying the shuttle console, i imagine (unless enraged colossus keeps shooting anyway)

The enraged colossus not only keeps shooting, but specifically spams the attack that fires bolts in all directions more often than it normally could. It also gets a speed increase so that it can get closer to you for melee striking faster.

**Comment by XDTM** [comment]
Maybe instead of such an arbitrary enrage mechanic colossus should have more than one attack

**Comment by ATH1909** [comment]
> Maybe instead of such an arbitrary enrage mechanic colossus should have more than one attack

Eh, I kind of like it. The colossus has a gimmick, and it sticks to it. I respect that.

**Pull request merged**
