### PR TITLE
Adds new sabre sprites 

### PR DESCRIPTION
**Pull request by Lexorion**
## Adds new sabre sprites
Reverts #31400  (I am sorry)
Closes #31559 

Can we please quit making these silly PRs? Why do you care so much about a few pixels? I really hope this ends it.

### CODE REVIEW

**Comment by Anonmare** [comment]
I move that any further PRs on the Captain's sword's sprite require maintainer approval because this is getting out of hand,

**Comment by banthebantz** [comment]
# STOP

**Comment by calzilla1** [comment]
Yes. These are gud

**Comment by praisenarsie** [comment]
:/

**Comment by Armhulen** [comment]
just stop making prs beetards

**Comment by Armhulen** [comment]
by the way this is the worst pr out of all of them because it names it the sabre but uses the rapier sprites

S T O P

**Comment by Lexorion** [comment]
They'd look extremely similar though. The inhands are fine.

**Comment by Iatots** [comment]
Hold on.

- A PR is opened to revert a sprite change based on the existing artstyle (and maybe to remove a codersprite)
- in said PR an ongoing discussion to find a better sprite produces a work by dorsidorf
- You then rip said sprite
- Modify it to your liking
- and open a new PR to implement your sprites, without taking part in the discussion or asking for feedback


And *they* are being silly?

**Comment by Bawhoppen** [comment]
Just close this

**Comment by Lexorion** [comment]
I made the original sprite? I ripped my own sprite then I guess Iatots.

**Comment by Dorsisdwarf** [comment]
my sprite is just the original rapier but with the fancy handle replaced by a saber handle and a longer blade

**Comment by Bawhoppen** [comment]
fuck you all I'm going to make a completely new sprite fuck this shit holy fuck

**Comment by Dorsisdwarf** [comment]
@Arianya btw

**Comment by Iatots** [comment]
You know what I meant, you used dorsi's edit. 
This could all have taken place in the other pr.

**Comment by Lexorion** [comment]
Except I didn't, I made this lmao

**Comment by Wyzack** [comment]
If lex doesnt stop stealing her own artwork there will be blood mark my words. If only i could settle on a name for my dueling sword.....curses

**Comment by Arianya** [comment]
I can hardly claim to be upset since I hadn't gotten home to fuck with spriting the sheath.

Ultimately it'll be up to @optimumtact since this is a partial revert and subject to his approval, but I have no issues with it superceding my PR

In as much as I have any say in the matter, I would suggest adding a changelog and crediting Dorsi, even if it was a derivative work, it's was nice of them to put in the effort!

**Comment by Arianya** [comment]
No edit on mobile but I should stipulate:
"I have no issues with it superceding my PR *if this meets maintainer approval*"

**Comment by Lexorion** [comment]
those are neat

**Comment by Dorsisdwarf** [comment]
swords
theres the png file if you want it

**Comment by duncathan** [comment]
this is good. both sprites in this pr are clearly sabres

**Comment by Dorsisdwarf** [comment]
swords2
heres an NT blue version

**Comment by TechnoAlchemisto** [comment]
Good sprite Lexorion!

**Comment by dannno** [comment]
this is way better than the alternatives

**Comment by AnonymousNow** [comment]
I have a better idea as to how to fix this.

Add every variation of sprites and sword type. Have the locker initially spawn with a single-use Sword Vendor Beacon, which lets you pick from a variety of swords, possibly even with slightly different effects (eg. rapier isn't sharp for cutting purposes, but pierces armour much better). This'd make it like the chaplain's Null Rod or the detective's revolver.

Problem solved, everyone wins, we all have tea and jam sandwiches.

**Review by ShizCalev — APPROVED** [review]

**Comment by optimumtact** [comment]
We're not going to bloat the DMI with multiple varietys at this stage.

This is an acceptable PR and I'm happy to accept it.

**Comment by WJohn** [comment]
I'd be happy with either lexorion's or dorsis's sword. Though I'm leaning slightly towards dorsis because the lighting is better, in my opinion.

**Comment by duncathan** [comment]
I just prefer dorsi's cuz I don't like borders

**Comment by Dorsisdwarf** [comment]
I agree with orangeS, there will be no duplication even if lexorion did decide they wanted to use my sprite. too many fucking swords and shit already augh

**Comment by PKPenguin321** [comment]
tfw naming pedantics forced us to replace a good sprite

**Comment by Dorsisdwarf** [comment]
tfw people couldnt accept the idea of not giving the captain a maximised amount of kill so they buffed his sword

**Pull request merged**
