### PR TITLE
Makes necropolis chests not burn up in lava

### PR DESCRIPTION
**Pull request by silicons**
What the title says. No more burned loot ;_;

### CODE REVIEW

**Comment by optimumtact** [comment]
Making items lavaproof because the bosses are spawning their loot in lava is the wrong fix.

Making the bosses look for a safe square to drop their loot when they die is the right fix.

**Comment by RemieRichards** [comment]
I suggest instead dropping the loot in like, magma proof eggs/spheres.
that way they can be lavaproof, without the actual item itself getting buffed.

**Comment by PKPenguin321** [comment]
doesnt even have to be an egg or a sphere, just make the loot crate they drop lava proof

**Comment by kevinz000** [comment]
Ok. Loot crate then?

**Comment by PKPenguin321** [comment]
also it would be extremely funny if somebody knocked someone out, threw them in one of these lavaproof crates, then shot the crate into the middle of a lava lake

**Comment by RemieRichards** [comment]
@PKPenguin321 a burial at sea...

**Comment by PKPenguin321** [comment]
i imagine it essentially being like the mafia tying you up in a car trunk before driving it into the ocean

**Comment by Cheridan** [comment]
>Making the bosses look for a safe square to drop their loot when they die is the right fix.

Well in Terraria when you killed the Hell boss it would make a box around where it died so that all the stuff wouldn't just drop in lava.

**Pull request merged**
