### PR TITLE
Re-adds erroneously removed deathmatch maps (for real this time)

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

In https://github.com/tgstation/tgstation/pull/85319, several deathmatch maps (sniper elite, mech madness, and others) were removed. There was no mention of this in the PR body, changelog, or discussion. Now they're back.
## Why It's Good For The Game

Stuff shouldn't just be removed without any discussion, scrutiny, or changelog. If nothing else, this PR can serve as a place for the first 2.
## Changelog
:cl:
fix: The instagib, ragecage, mech madness, secu-ring, shooting range, and sniper elite deathmatch maps are available again.
/:cl:

### CODE REVIEW

**Comment by EuSouAFazer** [comment]
Now this brings the question of if we want these maps back

**Comment by GPeckman** [comment]
I mean if the result of the discussion is "this was a good change, don't bring those maps back" then that's fine, but there should be a discussion for it.

**Comment by mc-oofert** [comment]
in my opinion mech madness and secu-ring are the ones least worth saving
secu-ring is just hitting people with disablers

**Comment by Iamgoofball** [comment]
Secu-Ring just needs some stage hazards and it'd be good.

Per discord, the author of the PR was literally banned from our repository so they decided, poorly, to just jam the removals into the existing PR instead of appealing their gitban and opening a new PR.

**Pull request merged**
