### PR TITLE
Changes the cockroach sprite for the better

### PR DESCRIPTION
**Pull request by TrustyGun**
Before:
disgusting
After:
howgross

They are also animated a little.

### CODE REVIEW

**Comment by xxalpha** [comment]
The animation needs to be faster, something like 1ds delay.

**Comment by WJohn** [comment]
These don't look terribly good. It doesn't give off the impression that it is an even size throughout, basically looks deformed.

Animation speed is okay with 2.5 or 1 ds delay.

**Comment by Buggy123** [comment]
Is this just as big as the old one? Why don't we just make roaches teeny weeny little cigarette butt-sized dots instead of huge, detailed sprites?

**Comment by TrustyGun** [comment]
The old one was 19x21, this one is 16x14

**Comment by CosmicScientist** [comment]
@Buggy123 I don't think they're supposed to be a hassle to splat beyond the RNG.

**Pull request merged**
