### PR TITLE
Adds origin tech values to a lot of items.

### PR DESCRIPTION
**Pull request by harmonyn**
Exactly what it says in the title. I tried to make most of these relatively low-impact. May add more if people suggest them. Here goes:

SYNDICATE ITEMS:
- Camera bug: Engineering 1, Syndicate 3
- Door charge: Combat 2, Syndicate 3
- Syndie magboots: Magnets 2, Syndicate 3

MINING ITEMS:
- Mining scanner: Engineering 1
- Advanced mining scanner: Engineering 3, Magnets 3
- Lazarus injector: Biotech 4
- Resonator: Magnets 2, Combat 2
- Kinetic accelerator: Combat 2, Power Manipulation 1

MISCELLANEOUS ITEMS:
- Magboots: Magnets 2 (how the FUCK did these not have this before?)
- Forensic scanner: Engineering 3, Biotech 1
- Holotape projectors: Materials 1, Engineering 1
- PDA: Programming 2

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Forensic scanner should have biotech on it.

**Comment by Lumipharon** [comment]
Laz injector will be like the only alternative to mech syringe guns for bio 5, which is good, if impractical.

**Comment by bgobandit** [comment]
Not true, slime potions have it

**Comment by Bawhoppen** [comment]
>PDAs still don't have anything
just give them something crap like data theory 2

**Comment by bgobandit** [comment]
added suggestions

**Pull request merged**
