### PR TITLE
Replaces the singularity with a supermatter on Donutstation

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request
Remodels the entirety of Engineering to accommodate a Supermatter setup.

## Why It's Good For The Game
In every round I hopped on to observe and take feedback over the past months, almost every time it ended in the singularity being released and a shuttle call within 25 minutes. Rose-tinted glasses are bad for the game and while the original map was built around this idea, it doesn't hold up now a days and if anything is too much of a hindrance to try and justify what few pros it had. I probably would of had to do this eventually with the current stance on non-SM engines so I might as well do it now. 

## Changelog
:cl: MMMiracles
tweak: The engine on Donutstation has been changed to the Supermatter.
/:cl:

Criticism would be super useful at this stage so I can hammer out any issues before this gets merged.

### CODE REVIEW

**Comment by actioninja** [comment]
Use the visible layer manifold type, they're under the floor right now.

**Comment by MrDoomBringer** [comment]
@MMMiracles you know you dont need to get pictures up, we have a bot that does that for us
https://github.com/tgstation/tgstation/pull/43246/checks?check_run_id=81929380

**Comment by MrDoomBringer** [comment]
image
also does this map difference smell like undocumented changes to you or is that just me

**Comment by MMMiracles** [comment]
Other than linking up the separate powernets due to the lack of external arms from the singularity and 2 noteboards in research, not really.

**Comment by actioninja** [comment]
Looking side by side, the undocumented changes are:
There's a bulletin board in the RDs office and the science lobby
Service lathe has it's own APC
A new wire connection was added in southeast maint
There's caution stripes on the sides of the atmos desk

Also not sure if this is intentional, but it looks like the engine area scrubbers are hooked directly to the exhaust loop, not just the chamber ones.

**Comment by anconfuzedrock** [comment]
I will just convince myself in my head and be smug and think "it's not that the singulo is easy to release it's that bagils are too stupid to realise it's important to contain" and then feel really smart for a few months.

**Comment by MMMiracles** [comment]
I didn't see any harm in having the scrubbers hooked up to the exhaust loop since it cuts down on the pipe spaghetti a small amount.

**Comment by dr-bee** [comment]
It isnt a very pretty layout, but it should function. One thing I would add is an atmos to engine line. and while you do that make the room scrubbers go to atmos and not into the loop. 

You are going to need to link atmos and the engine anyway for the mix-engine link, might as well make pipe spaghett.

Or you could increase the size of the engine room, there is a large amount of empty space between the engine and the donut loop that doesnt really need to be there. It would mitigate some of the pipe overlapping and make it so you dont need to use layered pipes.

**Comment by Farquaar** [comment]
https://www.youtube.com/watch?v=i7MLT4MmAK8

**Comment by Barhandar** [comment]
The point of Donut is the singularity in the middle. Just delete the map entirely if you like SME that much.

**Comment by actioninja** [comment]
> The point of Donut is the singularity in the middle. Just delete the map entirely if you like SME that much.

Pretty sure the point of donut is that it's shaped like a donut.

**Comment by MMMiracles** [comment]
@dr-bee there's already a line from the mix chamber in atmos to the engine, starting from the purple piping

**Comment by anconfuzedrock** [comment]
isn't mm the one who added donut? Though I prefer the singulo, I'd feel personally insulted if people told me the point of my map and opposed change so blindly.

**Comment by Jimmius** [comment]
why not just remove donut

**Comment by anconfuzedrock** [comment]
mmm over here explaining his reasons in a way that's perfectly easy to understand even if I personally think it's not an issue

**Comment by MMMiracles** [comment]
y'all dumbasses telling me to just remove the map I made because I'm changing the engine are why the ideas subforum exists

**Comment by plapatin** [comment]
why did you take away the one good thing about donut

**Comment by Barhandar** [comment]
Okay I've looked at the actual map and I think you should be banned for ERP on the map because it's a fucking orgy of multilayered pipes

* It's too optimized - it's _supposed_ to be unoptimized and barely performing so that _engineering has something to do_ instead of fucking off at roundstart because everything is set up already.
* The aforementioned layered mess of layered pipes makes it really tedious, with no gameplay benefit, to do any modifications to the engine. Or, for that matter, atmos and the entire piping on the map.
* There is zero danger if engine explodes now, unless whoever makes it do so actually goes to effort of causing overpower/overpressure and hence tesla/singulo, because it's too far from almost anything vital - the only thing it can reliably damage, the ore silo, is extremely easy to save and replace. And even that requires, effectively, maximum explosion power.

**Comment by FloranOtten** [comment]
This is the EPITOME of hugbox. Remove the danger, place in something thats not harmful to anyone. If this delaminates, It's probably only going to take out a bit of the inner circle, damage botany, EVA, maint, curator backroom, engi and vault.  So what's the delamidanger? Just wall off engi and live on solars. 

The location with chamber bypass looks horrible

Is there even a cooling loop bypass?

The cooling loop is so hilariously easy to sabotage, it's not even funny. Just weld a wall in maint, be quick with a firesuit and you're able to take it out.

How do engineers fix a damaged cooling loop? Where's the airlock? Having to break walls is bad design. Fuck modifying loop, I suppose.

Straightpiping the cooling loop; A brilliant idea. Not one you should use for the map. That's taking the modding out of the SM. 

All of these pipe layer manifolds look hilariously bad

Why have you made this entrance a chokepoint? Bad idea to have all access to the SM restricted to a single door. 

Maybe I'm seeing this wrong but are those box reflectors in the emitter room? Why? Regular reflectors work too, without being wasteful to the point of absurdity.

There's no freezer bypass pump, meaning you cannot prevent gas flowing through the freezers several times. There's an argument to be made about increased efficiency due to less bottlenecking, but again, we shouldn't be optimizing roundstart engine placements.

Why are you even lowering and raising the pipe layers all over the place? Only the freezers are locked on level 2, there's fuckall reason to have it divert for the filters, the SM chamber vents, the cooling loop etc.

This all but prevents additional emitters without significately modifying the room.

Where are the cameras? Am I missing something or is  the air alarm and chamber pumps out of the AIs reach?

This is the second time a badly made SM design has been merged. Do the maintainers even play engi?

**Comment by Barhandar** [comment]
>Maybe I'm seeing this wrong but are those box reflectors in the emitter room? Why? Regular reflectors work too, without being wasteful to the point of absurdity.

It's not wasteful, it's free diamonds.
>Where are the cameras? Am I missing something or is the air alarm and chamber pumps out of the AIs reach?

They are; I see no cameras inside and a lot of cameras outside.

**Comment by VileBeggar** [comment]
no atmos to loop, weak

**Comment by Barhandar** [comment]
Or rather, atmos to loop in a hilariously _shitty_ location overlapping with fucking everything else.

**Comment by Cyprex** [comment]
The SMES are hooked up wrong, input and output are mixed up, they output to rad collectors and input from the main station powernet. The piping is also very misleading.

@ShizCalev You really should have at least left this PR open for longer in my opinion, it's really subpar right now.

**Pull request merged**
