### PR TITLE
Removes shadowshrooms & related trait

### PR DESCRIPTION
**Pull request by AnturK**
Awful grief tool and eyesore.

### CODE REVIEW

**Comment by XDTM** [comment]
Could we make shrooms not spread instead

**Comment by uraniummeltdown** [comment]
just make them spread slower or affect lighting less, IMPROVE NOT REMOVE

**Comment by Anonmare** [comment]
Shrooms in general are a pain in the ass because they're next to impossible to remove once they hit a critical mass.
After that the only way to reasonably get rid of the damn things is plasma fire.

**Comment by Iamgoofball** [comment]
:-1:

>add original thing to take advantage of new lighting system

>butthurt revert

time to stop

**Comment by Iamgoofball** [comment]
just add fucking spray w/ weedkiller to instantly kill shrooms

**Comment by Iamgoofball** [comment]
of ANY kind

**Comment by Robustin** [comment]
Yea I want to see how this pans out, I'm kinda of opposed to any kneejerk reaction to a new feature. A lot of unique stuff was really awful when it was new and everyone wanted to try it, then it petered out and people stopped caring when it wasn't showing up every round.

**Comment by Dorsisdwarf** [comment]
I mean, these are truly awful and look hideous (*why is it purple*) but I do like the idea behind them

**Comment by ShadowDeath6** [comment]
I think the removal of the trait is a good idea

**Comment by kevinz000** [comment]
Outright removal for an actual unique plant instead of normal instakill is bad nerf and regulate it instead

**Comment by ChangelingRain** [comment]
An alternative; #25031
Super huge nerf and logging so admins can murder anybody who plants them as nonantag.

**Comment by Repukan** [comment]
Shadowshrooms are fucking horrible.

Had a round were an ash Drake had almost no counter since people couldn't see it in the darkness.

**Comment by Anonymous583** [comment]
Botany is becoming a guaranteed antagonist role with the amount of bullshit they're able to get away with.

**Comment by Supermichael777** [comment]
spraying them with weedkiller get rid of them. 2 u chem and 58 u foammix should clear the halls fast enough.

**Comment by ChangelingRain** [comment]
I'm going to close this pr and "suggest" that we try the nerf(#25031) and fix(#25044) to shadowshrooms before we actually axe them.

**Pull request closed without merging**
