### PR TITLE
Adds chemical heater nanoUI & construction/upgrade

### LINKED ISSUE #7040: some Issues with new Chemistry
TKDRG stated:
Some concerns (for the future):
1) Make the chem heater have an actual HTML interface with user feedback on the heating progress.
2) Make the chem heater researchable/constructable and upgradable.

Fox said:
Yeah, currently the chem heater is ...really wonky; the temperature ranges from 1 to 3000 (Goon chem only needs 0 to 1000); likewise, with Goonchem you can slap the beaker in and set the temperature, then start heating/cooling and watch the temperature slowly go up/down...this is especially important in a few chemical reactions like Crank---where improperly making it will blow up in your face.

This is from the PR if any other issues exist please state them here and how they are treat it like a full list of issues so these can be fixed quickly where possible.

### LINKED ISSUE #7060: chemistry heater is shit
a. it can't eject the beakers you put in until it's done heating
b. it doesn't have a gui
c. it heats INCREDIBLY slowly. 2 per tick may not seem too slow, but there is no chemical that is BELOW 200k to heat, so it takes incredibly long most of the time
d. there's no way to tell what the temperature is at the given moment

### PR DESCRIPTION
**Pull request by tkdrg**
Also buffs the heater to heat/cool 10 kelvin per tick per upgrade level.
One known issue with this is that there is no "panel open" sprite for the chem heater, so it might be a bit misleading.

Fixes #7040
Fixes #7060 
Fixes #7068

2015-01-14-214925_1366x768_scrot

### CODE REVIEW

**Comment by Anonus** [comment]
:+1: 
NANOUI THE BES

**Comment by pudl** [comment]
YES

**Comment by ike709** [comment]
heil

**Comment by Razharas** [comment]
Nice

**Comment by pudl** [comment]
PLEASE speed up the heater just a little. we sat on badger heating clf3, it took about 10 minutes for 474 K

**Comment by tkdrg** [comment]
Looks like you missed it in the PR.
> Also buffs the heater to heat/cool 10 kelvin per tick per upgrade level.
That's 5 times faster with no upgrades, and 15 times faster with full upgrades. Personally I'm concerned about this change unbalancing the heat chems, but only time will tell.

**Comment by Iamgoofball** [comment]
amazing 10/10 exactly what we needed

**Pull request merged**
