### PR TITLE
Spiders don't take damage from lack of oxygen, high and low pressure, cold and hot temp.

### PR DESCRIPTION
**Pull request by Xackii**
## About The Pull Request

Spiders don't take damage from lack of oxygen, high and low pressure, cold and hot temp.

## Why It's Good For The Game

The spiders cannot do anything about the fact that there is no oxygen in the room and room is just a hole in the station. The best tactic for playing against spiders is to simply depressurize near their habitat and wait until they die, which makes the antagonist nothing more than a cat with paws. Now it should be much easier for spiders to simply exist.

:cl:
balance: Spiders now don't take damage from lack of oxygen, high and low pressure, cold and hot temp.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Spiders have a way to counter it, they have air sealed webs

**Comment by tralezab** [comment]
And I entirely oppose the idea of heat immunity

**Comment by Xackii** [comment]
> Spiders have a way to counter it, they have air sealed webs

And what will web do when the room is already completely depressurized? (or the entire station as a whole). I’m talking about this because I recently played two rounds in a row on spiders and all the rounds ended with our team being at a station where all the rooms were depressurized and all we could do was hope that the nurse would heal us. 
it's so unpleasant and unplayable that it discourages the desire to play on spiders in general.

**Comment by MrMelbert** [comment]
In any case having antagonists countered by things that aren't running at them with laser guns is good, it adds variety

**Comment by Dorsisdwarf** [comment]
This just encourages spiders to do the xenomorph thing where they smash holes into space everywhere to make it harder to attack them for the crew, and use space to freely move around at high speed without crew interference. They already tread on each others toes enough.

**Comment by Rex9001** [comment]
Isnt this removing the main counter to spiders?

**Comment by DustanHache** [comment]
In my opinion, let them say “fuck” to cold, but leave heat resist/pressure as is. this way depressurizing the station intentionally or otherwise isn’t QUITE as deadly to them, but keeping them from jaunting through space like nothing is wrong. Heck, I would even increase the low pressure damage to compensate.

**Comment by Jacquerel** [comment]
> > Spiders have a way to counter it, they have air sealed webs
> 
> And what will web do when the room is already completely depressurized? (or the entire station as a whole). I’m talking about this because I recently played two rounds in a row on spiders and all the rounds ended with our team being at a station where all the rooms were depressurized and all we could do was hope that the nurse would heal us. it's so unpleasant and unplayable that it discourages the desire to play on spiders in general.

If you didnt build a pressurised nest and the entire station was depressurised by someone else (making it uninhabitable for the crew) I guess you lost that round.

**Comment by moocowswag** [comment]
Unironically the meta to fighting spiders is to just cool the station down because everyone's own temperature regulation is enough to overcome the cold and lizards can just wear a coat.

You can even intentionally breach icebox and wear internals or work on the scrubbing network to try to fight off any co2 coming in.

**Comment by GuillaumePrata** [comment]
Clearly we just need a new spider that makes silk space suits to the other spiders

**Comment by DaydreamIQ** [comment]
Spiders already have a single strain that's entirely immune to space and its one of the most obnoxious things to ever exist. No chance in hell we should be giving all of them that benefit

**Comment by Xackii** [comment]
> In any case having antagonists countered by things that aren't running at them with laser guns is good, it adds variety

this is good in cases where spiders can resist it. this is simple logic - if a spider cannot somehow avoid receiving damage from the environment, then they shouldn’t.

**Comment by Xackii** [comment]
> > > Spiders have a way to counter it, they have air sealed webs
> > 
> > 
> > And what will web do when the room is already completely depressurized? (or the entire station as a whole). I’m talking about this because I recently played two rounds in a row on spiders and all the rounds ended with our team being at a station where all the rooms were depressurized and all we could do was hope that the nurse would heal us. it's so unpleasant and unplayable that it discourages the desire to play on spiders in general.
> 
> If you didnt build a pressurised nest and the entire station was depressurised by someone else (making it uninhabitable for the crew) I guess you lost that round.

That's the problem. Spiders are a midround antagonist and by the time you appear at the station, most often something is already happening. One of the rounds that I played was on the ice blocks and there was simply depressurization everywhere, but the station didn’t give a damn about it because they had protection from the cold and tanks to breathe in. Spiders don't have such privileges. Why? Or as I said above, if they can’t fight it, then they can’t take damage.

**Comment by Xackii** [comment]
> Spiders already have a single strain that's entirely immune to space and its one of the most obnoxious things to ever exist. No chance in hell we should be giving all of them that benefit


This creates another problem when you have several types of spiders to choose from, but you will only choose one single type simply because it might exist. The rest of the spiders can create webs and die from the cold and perhaps even fight with a person who will shoot you with a laser

**Comment by Xackii** [comment]
> Unironically the meta to fighting spiders is to just cool the station down because everyone's own temperature regulation is enough to overcome the cold and lizards can just wear a coat.
> 
> You can even intentionally breach icebox and wear internals or work on the scrubbing network to try to fight off any co2 coming in.


that’s the problem: the station can counter it, but the spiders can’t

**Comment by Xkallubar** [comment]
Personally I'd rather we have something like moocowswag's idea, something that spiders can build that will fix the atmos in a sealed room. There's already a caste that's completely space immune anyways.

**Comment by the-orange-cow** [comment]
> Clearly we just need a new spider that makes silk space suits to the other spiders

Making little eight sets if spider mittens...

**Comment by SimplySmiley123** [comment]
> > Spiders already have a single strain that's entirely immune to space and its one of the most obnoxious things to ever exist. No chance in hell we should be giving all of them that benefit
> 
> This creates another problem when you have several types of spiders to choose from, but you will only choose one single type simply because it might exist. The rest of the spiders can create webs and die from the cold and perhaps even fight with a person who will shoot you with a laser

The other spiders are also obnoxious as fuck to fight as is unless you have a laser gun on you, or are immune to venom and poisons of all sorts.
The solution of "break the station apart just to kill these buggers and force a shuttle call regardless" exists for a reason, spiders are that annoying to fight.

Your solution to this would just turn these into differently flavored xenomorphs. I would much rather they get some expansion towards what they can make out of their webs (more pressure proof variants of webs) and moocows compromise so spiders get _some_ counter measures without just giving them flatout immunity to their major counter.

**Comment by Jacquerel** [comment]
We're not interested in spiders being immune to environmental damage: that is intentionally one of their weaknesses.
If you wanted to investigate some other avenue like having them build a structure which can repressurise webbed areas then that's sufficiently different to this that it need not be the same PR.

**Comment by SethLafuente** [comment]
Many measures have been implement it to remove this issue before hand this would have been resonable long ago when spiders didnt have their methods but is no longer reasonable, this would bring forth way too much of an advantage to spiders to destroy station atmos making them as annoying to play against as xenos and it would remove their whole mechanic of making nest within the station while attempting to keep it habitable.

If you do Infact think this is a legitimate issue you would want to have a helping hand in making better I more than encourage to attempt to come up with creative thoughtful solutions that wont tip off the balance of the spiders off to the wrong direction.

There is a spider that has all enviromental immunities do to its design and purpose if you'd like to try that one out when you play spiders.

**Comment by Xackii** [comment]
> Many measures have been implement it to remove this issue before hand this would have been resonable long ago when spiders didnt have their methods but is no longer reasonable, this would bring forth way too much of an advantage to spiders to destroy station atmos making them as annoying to play against as xenos and it would remove their whole mechanic of making nest within the station while attempting to keep it habitable.
> 
> If you do Infact think this is a legitimate issue you would want to have a helping hand in making better I more than encourage to attempt to come up with creative thoughtful solutions that wont tip off the balance of the spiders off to the wrong direction.
> 
> There is a spider that has all enviromental immunities do to its design and purpose if you'd like to try that one out when you play spiders.


As I already wrote, it’s a big minus that you have to take that spider that simply allows you not to die, and the balance of spiders itself is very questionable, so the lack of ways to deal with pressure and cold is not the only problem of spiders

**Pull request closed without merging**
