### PR TITLE
Removes backpack close-button

### PR DESCRIPTION
**Pull request by kingofkosmos**
Makes storage items close intuitively when clicked on (if you're already looking inside it).

Also makes the close-button smaller and more consistent with the rest of the UI.

sieppaa

:cl: kingofkosmos
rscdel: The backpack close-button has got a visual overhaul.
rscadd: All storage items can be closed by clicking on them again.
/:cl:

### CODE REVIEW

**Comment by CosmicScientist** [comment]
:+1: This is actually a really nice idea I think.

**Comment by Jalleo** [comment]
Good idea but it also may confuse a lot of people for a short while.

**Comment by Thunder12345** [comment]
Changelog would really help with the confusion thing

**Comment by ChangelingRain** [comment]
If you look inside a box in a backpack you'll have to open another storage item to close it, though.

**Comment by Supermichael777** [comment]
what Rain said. Leave the close button and make the click to close a feature.
Just because you made a different way to do it doesn't mean the old way HAS to go.

**Comment by kingofkosmos** [comment]
Changelog added.

You're right, the box in a backpack -situation is tricky, but in my experience the situation never called to only close it, because I would always want to see the backpack contents afterwards, which works as usual with this change.

IMHO the big red close-button looks very outdated compared to the rest of the UI. This makes it obsolete and removes screen clutter.

**Comment by Iamgoofball** [comment]
why dont we just resprite it

**Comment by Core0verload** [comment]
Yes, just resprite it, like d2k5 did.

**Comment by kingofkosmos** [comment]
This PR is about removing on-screen clutter with a more elegant solution, not just respriting them.

**Comment by Core0verload** [comment]
No, this PR is about removing without adding anything.

**Comment by kingofkosmos** [comment]
Are you being serious? Did you by change miss the first line of this PR, including the commit description, changelog and the code itself?

**Comment by Core0verload** [comment]
Yes I am. There is a 32x32 box of nothing where X was used to be. Even the larger storage items wouldn't fill it.

**Comment by duncathan** [comment]
Oh god this looks ugly :-1:

**Comment by Iamgoofball** [comment]
why not just have both the button AND click on closing

**Comment by Ultimate-Chimera** [comment]
:-1: for removing button and :+1: for making it closed when clicked on again

**Comment by WJohn** [comment]
Why not have both?

**Comment by kingofkosmos** [comment]
Out of curiosity, what are the arguments for keeping the close-button?

My argument for removing it is that this PR would make it obsolete --> free space on-screen to see what's going on in the game. What's there not to like?

**Comment by phil235** [comment]
Does it work correctly with ghosts looking inside containers?
What if I'm a living mob checking the content of a backpack on the floor (with clickdrag), how do I close that?

**Comment by Thunder12345** [comment]
thing
Replace it with this?

**Comment by ShadowDeath6** [comment]
Keep the current button, add close-on-click as well, best of both worlds. 
>how do I close clickdrsg?

Moving away from the container works.

**Comment by phil235** [comment]
>Moving away from the container works.

What if I'm lazy?

**Comment by PKPenguin321** [comment]
>Moving away from the container works.

Not if you're a ghost

**Comment by CosmicScientist** [comment]
I tried.
I tried

**Comment by TrustyGun** [comment]
@CosmicScientist

You could always just do the close button in the style of the storage boxes like so:

hud3
hud2

IMO this would look better.

**Comment by kingofkosmos** [comment]
Crap, I didn't think about ghosts looking into containers. Currently there's no way for ghosts to close the boxes.

**Comment by CosmicScientist** [comment]
@TrustyGun true, I just wanted to go to the nth degree of having a uniform UI because the container sprites never felt like they fitted well enough... nor the grab options.

**Comment by kingofkosmos** [comment]
Okay, due to popular demand (and an issue with ghosts unable to storage items without a close-button) the close-button has received a visual overhaul.

I tried to mimic @TrustyGun's style, but made it more like the storage boxes themselves. Like so:
sdasda

Which looks like this in-game:
sieppaa

What do you guys think?

**Comment by CosmicScientist** [comment]
:+1:

**Comment by duncathan** [comment]
This is still ugly as fuck
By making the button a different size, you're making the inventory off-center on the screen
If you move the inventory, it doesn't line up with the rest of the ui
Solution: make the button the same size

**Comment by CosmicScientist** [comment]
In the preview it lines up with the hands?

**Comment by duncathan** [comment]
Yea, but it's off center on the screen.

**Comment by duncathan** [comment]
@kingofkosmos please make the close button the same size as the rest of the inventory slots. then I'll merge

**Comment by kingofkosmos** [comment]
IMO it would not result in any less clutter and would look strange. Does everyone else agree with duncathan? Am I really the only one who thinks this looks quite nice?

**Comment by PKPenguin321** [comment]
yeah i think what we have is fine
a full tile button just kinda removes the purpose of the PR in the first place

**Comment by duncathan** [comment]
I think your new design looks nice, but it doesn't fit in with the rest of the ui. If you make the close button the same size as the inventory slots, that means that the inventory is centered over and in line with the hands, which means it's centered on screen. 
I really like the new look you have for the button; ideally we'd get the newer look but at the same size.

**Comment by Arquebusier** [comment]
The new button is much better

**Comment by optimumtact** [comment]
@duncathan honestly it should be left smaller but the UI alignment code fixed to account for it by offsetting the alignment slightly

**Comment by Cheridan** [comment]
lets just put a donk on it

**Comment by Iamgoofball** [comment]
https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

https://github.com/tgstation/-tg-station/issues/16278

**Pull request merged**
