### PR TITLE
martian hotfix

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Fixes a few issues with Martian food. Makes stuff that's cooked on the grill or oven not burn, and adds guide recipes for the non-crafting-menu stuff.
## Why It's Good For The Game
Fixes some problems, removes some confusion
## Changelog
:cl:
fix: a few issues with Martian food
/:cl:

### CODE REVIEW

**Comment by EOBGames** [comment]
Adding no update since these are my own mistakes

**Comment by AdipemDragon** [comment]
image
comin in with a couple things too,
firstly an incorrect ingredient/description
and secondly, less an actual problem but moreso asking, should one cookie eat a whole bar of butter? there's butter slices now

**Comment by EOBGames** [comment]
> image comin in with a couple things too, firstly an incorrect ingredient/description and secondly, less an actual problem but moreso asking, should one cookie eat a whole bar of butter? there's butter slices now (also thirdly i should get in and like, make more sprites for this martian food pr, cause that's straight up just the rootbreadsprite with no twist whatsoever for rice bread and its children recipes, should've known bout it before it was merged honestly)

Looks to me like I buggered up the pathing on the Prospect Sunrise- it's meant to be an omelette and egg sandwich. As for the boh loh yah, I made that long before butter slices were a thing and hadn't retrofitted it for that purpose because, frankly, I didn't know butter slices existed before this comment (keep in mind that this PR had been a rough WIP for about... 18 months? shit got real bad last year)

**Comment by AdipemDragon** [comment]
> (keep in mind that this PR had been a rough WIP for about... 18 months? shit got real bad last year)

well it's glad to see that it's gotten at least good enough to work through the pr, good luck in the future

**Pull request merged**
