### PR TITLE
Add the Quartermaster to the Chain of Command

### PR DESCRIPTION
**Pull request by celotajstg**
## About The Pull Request

from https://github.com/tgstation/tgstation/pull/59124 ([backup of this historical record here](https://archive.is/H3oS3)):
image

## Why It's Good For The Game

A historical injustice is no more.

## Changelog
:cl: Celotajs
balance: In an unexpected ruling, Central Command has recognized quartermasters as part of the chain of command, putting an end to a historic injustice against the cargo department.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
power be to the lizard qm

**Comment by JohnFulpWillard** [comment]
You'd also have to remove Cargo access/comms from the HoP, and give the QM a command headset, and change their liver trait from TRAIT_PRETENDER_ROYAL_METABOLISM to TRAIT_ROYAL_METABOLISM, and they'd need a lot more access, since all heads usually get a ton of extra added access, like Engineering foyer.

**Comment by celotajstg** [comment]
Nah, the HoP is an old friend. Let him have the access.

**Comment by Kylerace** [comment]
nonhuman qm's are soul and this makes that not possible due to config.

**Comment by Farquaar** [comment]
No more lizard QMs? Based

**Comment by zxaber** [comment]
Rev nerf.

**Comment by celotajstg** [comment]
> Rev nerf

oh right, that would make the cargo department less likely to revolt

pr cancelled

**Comment by InsaneRed** [comment]
17 minute lifespan

**Comment by Mothblocks** [comment]
about the lifespan of a real qm (they kill themselves out of boredom)

**Comment by maxymax13** [comment]
didnt even change any of the job icons to blue lazy smh

**Comment by FernandoJ8** [comment]
> 
> 
> > Rev nerf
> 
> oh right, that would make the cargo department less likely to revolt
> 
> pr cancelled

YOU WERE THE CHOSEN ONE.
YOU WERE MEAN TO BRING BALANCE TO THE QM, NOT LEAVE IT IN DARKNESS.
I

**Comment by AlinaStarkova** [comment]
> 
> 
> Rev nerf.

to be fair, QMs wear sunglasses from the start and arent technically supposed to just take them off willingly to get converted

**Comment by Mothblocks** [comment]
who said they were taking them off willingly

**Comment by AlinaStarkova** [comment]
> 
> 
> who said they were taking them off willingly

ah right the old "i have a flash boss" and then the "ohhh nooo i tripped, my glasses fell!" 

it does happen, a lot lmao. cant blame em though, its either give in or they will beat you to death and steal your ID to order guns anyway

**Comment by Mothblocks** [comment]
no silly the "shove stun them and have several people kick the shit out of them as you take off their glasses" move

**Pull request closed without merging**
