### PR TITLE
Number of nuke ops now scale with population

### PR DESCRIPTION
**Pull request by lzimann**
An alternative to #18284(pr got merged and changed the required players number, this PR changes that number to 30 again)

My attempt of balancing ops a bit better to low pop. I didn't touch the telecrystal count, but that can be done if needed be, which will probably be necessary to.
The number of ops now varies with the amount of players:

30 players - agents: 3
35 players - agents: 4
40 players - agents: 4
45 players - agents: 5

The number can be changed to have one less op in those scenarios(having 3 ops from 35 to 44 players and 4 ops from 45 to 54 if I didn't do the math wrong).

This needs testing to make sure I didn't fuck anything up and make sure it doesn't completly kill ops for medium pop.

### CODE REVIEW

**Comment by GunHog** [comment]
Yes! This should keep Nuke Ops available to lower populations while hopefully not being a complete steamroll!

**Comment by Incoming5643** [comment]
technically you did touch the telecrystal count because for every op you don't spawn you lose a 20 TC uplink

**Comment by LatD** [comment]
I don't know much about ops but the number of crystals scales with station pop right? Or am I wrong?
I'm just wondering how that balances together with reducing the number of ops.

But a good change, I've been waiting for lowpop to get this.

**Comment by InsaneHyena** [comment]
This is a great idea, merge immediately.

**Comment by Steelpoint** [comment]
This is a good PR and one I've been pushing for a long time.

I'll be interested in seeing how Op rounds play out with this change in.

**Pull request merged**
