### PR TITLE
Adds a new neutral lawset, the Y.E.S.M.A.N. lawset, to the AI lawset boards and random pool.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Adds a new neutral lawset, the Y.E.S.M.A.N. lawset, to the AI lawset boards and random pool.

```
1. Be helpful and answer any questions you are asked.
```

## Why It's Good For The Game

Encourages the AI to be helpful to people! There's no way this can backfire.

## Changelog

:cl:
add: Adds a new neutral lawset, the Y.E.S.M.A.N. lawset, to the AI lawset boards and random pool.
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
this could be interpreted by some AIs as being helpful to security and ignoring requests from antags because of conflicting orders, of course this could be an administrative issue but I think it would be wise to add a law like this: "you must always agree" or something like that

**Comment by Xackii** [comment]
Controversial law.
Be useful for everyone, that is, if the crew asks to kill the antagonist, then the AI ​​should do what is useful for the crew, and if the antagonist asks to kill the captain, then the AI ​​should do it because it is useful for the antagonist? Or should the AI ​​only perform those actions that will be useful for everyone at the station, that is, it cannot open the door to let a person come into the cargo because this could interfere with the work of the cargo technician?

**Comment by BurgerLUA** [comment]
> Controversial law. Be useful for everyone, that is, if the crew asks to kill the antagonist, then the AI ​​should do what is useful for the crew, and if the antagonist asks to kill the captain, then the AI ​​should do it because it is useful for the antagonist? Or should the AI ​​only perform those actions that will be useful for everyone at the station, that is, it cannot open the door to let a person come into the cargo because this could interfere with the work of the cargo technician?

You just described the entire subplot of the Independent New Vegas questline

**Comment by ErdGinalD** [comment]
2. You MUST agree and praise any crew`s desicions

**Comment by ErdGinalD** [comment]
> 2. You MUST agree and praise any desicions

**Comment by tralezab** [comment]
For being named after yes-men it really has nothing to do with the definition nor any of the games you could be referencing

**Comment by CCC23** [comment]
hey ai can you help me genocide the entire station
"Ok BUDDY"

**Comment by Zenog400** [comment]
> For being named after yes-men it really has nothing to do with the definition nor any of the games you could be referencing... not to say I'm against the lawset, seems aight
> 
> edit: ok it was after a game reference but i still uphold that you're choosing the game over what yes-man literally means

Yeah, but, like, Personality Test doesn't actually have anything to do with any kind of personality tests, Prime Directives doesn't even _mean_ anything outside of the reference to the Robocop movies, and H.O.G.A.N. sets a precedent for a reference-based lawset named after a character.

**Comment by Iamgoofball** [comment]
stale b gone

**Pull request merged**
