### PR TITLE
Fork eating no longer requires mouth zone sel

### PR DESCRIPTION
**Pull request by optimumtact**
Instead, if there is a fork load
you will simply eat the fork load.

### CODE REVIEW

**Comment by optimumtact** [comment]
Now any casual scrub can use the fork for their fork related nutriment requirements

**Comment by Lumipharon** [comment]
>removing skill requirements for elite player vs food combat

0/10

**Comment by optimumtact** [comment]
I'm making this MY HUGBOX STATION NOW

**Comment by SconesC** [comment]
>Now any casual scrub can use the fork for their fork related nutriment requirements

the fking skill cap is being ruined im going to post about this in the chef subforum

**Comment by Miauw62** [comment]
:open_hands: :mailbox:

**Comment by pudl** [comment]
patty cake mailbox

**Pull request merged**
