### PR TITLE
Abductee objective replacement: The Promethean Horror

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Replaces a kind of really uncomfortable and actively non-interactive abductee objective with a more interesting one that encourages people to become a horrifying amalgamation of various bodyparts. 

## Why It's Good For The Game

I kept forgetting this was a thing, and boy is is creepy. And not in the interesting way. This feels more interesting and interactive than hiding away to apparently give birth and have...nothing happen. 

## Changelog
:cl:
add: Replaces a less interesting abductee objective with THE PROMETHEAN HORROR. The Flesh is Weak, the New Flesh is Not So Weak.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I think this also encourages people to have a look at the newest DNA splicing, as a good addendum to this change.

**Comment by thgvr** [comment]
Thank god, I have no idea how that was unchanged for 6+ years.

**Comment by Sealed101** [comment]
kills the hilarity of getting this objective with an egg or slime gland

**Comment by thgvr** [comment]
> kills the hilarity of getting this objective with an egg or slime gland

If an objective has you do something that is breaking server rules, it needs to be changed. Some other servers may cater to your needs.

**Comment by ChungusGamer666** [comment]
this objective is pretty funny but admittedly very non-interactive, so, i don't know what to think of it

**Pull request merged**
