### PR TITLE
Miners with style meter can now parry kisses

### PR DESCRIPTION
**Pull request by spiders24110**
## About The Pull Request
idea by hometownfunky 
## Why It's Good For The Game
True gamers don't get hit
## Changelog
:cl:
add: miners with style meter can now parry kisses
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Do they get style points for doing so

**Comment by Striders13** [comment]
> Do they get style points for doing so

yes

**Comment by CCC23** [comment]
> > Do they get style points for doing so
> 
> yes

kiss spam to farm style points

**Comment by private-tristan** [comment]
Parry your own kisses

**Comment by Shadowflame909** [comment]
Now add them parrying shower droplets and you have a true GAMER

**Pull request merged**
