### PR TITLE
Donkpockets 3: Rise of the Mouse Pocket

### PR DESCRIPTION
**Pull request by Coconutwarrior97**
## About The Pull Request

Adds mouse pockets to the game, as well as the crab pocket.
image
Thanks to Farquaar for the icons and some of the fluff! Also thanks to oranges for coding help.
## Why It's Good For The Game

More donks for people to craft.

## Changelog
:cl:
add: Adds mouse pockets and the crab pocket.
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Absolutely cursed as fuck.
I'm confused, I'm scared, I'm outraged.
10/10 great use for mouse breeding mechanics.

**Comment by Farquaar** [comment]
This is the greatest PR in the history of the past few hours.

**Comment by wesoda25** [comment]
wtf im not eating mousepockets

**Comment by HomocidlePancakes** [comment]
Crab pockets sound tasty

**Comment by MrPerson** [comment]
What's next, spider pockets? Roach pockets? Corgi pockets?

**Comment by kriskog** [comment]
Finally, some lizard friendly food :+1:

**Review by Twaticus — APPROVED** [review]
god bless

**Comment by Tlaltecuhtli** [comment]
can you make the white thing smaller?

**Comment by Tharcoonvagh** [comment]
jesus

**Comment by kriskog** [comment]
Merge conflict

**Comment by optimumtact** [comment]
github is fully rogue

**Pull request closed without merging**
