### PR TITLE
The Chemistry Lab now has reinforced walls

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
See title,
yes I map merged

## Why It's Good For The Game
Chemistry has a much higher potential for danger than several other areas that were deemed worthy of reinforced walls, including but not limited to; R&D, Genetics, Robotics and the Nanite Lab.
This change would make Chemistry feel less flimsy and exposed, and would also help mitigate the effect of explosive mishaps on the surrounding hallway and medbay lobby thanks to dynamic explosions.

## Changelog
:cl:
add: Chemistry now has reinforced walls
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
hugbox

**Comment by wesoda25** [comment]
Hey Fikou are you aware that you spell "perfectly logical decision that will improve the game" as hugbox? fucking weird dude

**Comment by wesoda25** [comment]
Also go above and beyond put reinforced tiles surrounding chem dispensers

**Comment by MCterra10** [comment]
I could but oranges will be mad for me not separating changes into different PRs. And also r-floors are waayy easier to build than r-walls and don't require plasteel

**Comment by Qustinnus** [comment]
im getting PTSD from goof chemistry vats

**Comment by Dawson1917** [comment]
Chemistry is meant to be making medicines for medbay, not producing military-grade explosives. 

Balancing around the _potential_ threat of a workspace will need every room protected like a fortress as every job has dangerous things available to it. Botany as an example. The hydroponics room shouldn't be fort Knox because botanists or someone breaking in can make dangerous weapons, and neither should it be the case for chemistry.

**Comment by MCterra10** [comment]
By that logic we should remove r-walls from genetics because if they do their job right they should be distributing powers that don't pose a threat to the station, we should remove them from R&D because all they'll do is make upgrades and tools, we should remove them from robotics because all they should be doing is making cyborgs, not dangerous mechs.

If you add dangerous chemicals, expect chemists to make them. That's like saying "unga because people shouldn't be taking guns from the armory if they do their jobs properly, we don't need to make it a secure area dunga". 

Another point I've failed to express is that because dangerous chemicals are so easily made, chemistry needs to be more secure from people breaking into to make them, just like R&D needs to be secure from people breaking in to make AI modules

**Comment by Dawson1917** [comment]
Yes, we should remove r-walls from genetics and the nanite lab and robotics and even, dare I say it, RnD. R-walls should be for highly secure areas like the armory, not anywhere you can make a ghetto weapon.
The RnD issue is a result of almost everything in it being completely benign and safe for anyone to use, but fiveish items and boards being dangerous enough to get people killed and requiring the whole of RnD to be fortified. This is a similar issue for chemistry, in that most (intended) things made inside are beneficial while others are deadly and capable of blowing large holes in the station. 
I don't see adding reinforced walls as fixing the problem, just adding an easily circumventable obstacle. 

I don't care strongly either way, I just dislike reinforcing things for the sake of it.

**Comment by MCterra10** [comment]
With these category 2 chems that can kill in 15 seconds when overdosed together we really need this reinforcement

**Comment by MCterra10** [comment]
To be honest, this has been merged on my downstream a while now and nobody has cared about/noticed what is a basic QoL change, so I doubt it will have nearly as large an impact on gameplay as you might think

**Comment by Michael-Ashfield** [comment]
Chemistry does have grenade casings and much more potential for sabotage. It takes pasting 1 macro and a click to make a huge range of dangerous and explosive chemicals. Chemistry is also important to keep working as it is meant to be the core of the new medical system. I rarely see the walls deconstructed when people went to break in, however it is normally just the glass which is removed and the chem dispenser ~stolen by botany~ moved (On meta).

**Comment by MCterra10** [comment]
With upcoming changes to glass that could change quite a bit, hence this PR

**Comment by nemvar** [comment]
We should remove most r-walls and make normal walls slightly more durable. Current normal walls are as weak as paper mache, with certain items being capable of dismanteling them in seconds. On the other hand, r-walls are almost indestructible with normal tools and as such warrent only to be used at the most dangerous places.

What we need is a healthy balance of normal walls, instead of just pasting rwalls all over the place.

**Comment by MCterra10** [comment]
So like, a medium strength wall? I would be quite happy with that around sci and chemistry, but as the orange man says "When you code it", and until it's implemented this is the solution I could think of

**Comment by MCterra10** [comment]
Again, the majority of players probably won't even notice the change unless they're tiders out to steal your chem dispensers, and it's my personal opinion that we argue too much over simple PRs that people forget about after a few days

**Comment by nemvar** [comment]
bikeshedding is a way of life.

**Comment by Tlaltecuhtli** [comment]
why is it so hard for people to ask engi to build machines (its their job)

**Comment by CPTANT** [comment]
It is incredibly rare for most antagonists to break into chemistry and have enough time to brew something actually dangerous because of how exposed chemistry is. Why would we want to discourage this even more?

**Pull request closed without merging**
