### PR TITLE
Bloodcult Stun Spell Tweaks

### LINKED ISSUE #40285: Blood cult stun checks for null rod instead of anti_magic_check()
https://github.com/tgstation/tgstation/blob/bdae84ffcd8e363f4a50d65d7f9f8dc19673b9fc/code/modules/antagonists/cult/blood_magic.dm#L416

It would make more sense if this did an `anti_magic_check()` instead of checking for a null rod.

### PR DESCRIPTION
**Pull request by ShizCalev**
Updated to use anti_magic_check instead of a nullrod check.

Corrected the stun message showing if the target is immune to the effect.

Added some visual effects (an actual red flash), and a "holy bubble" around the target if they're immune to the effect.

https://i.imgur.com/wd77s8w.gifv

Closes #40285

:cl: ShizCalev
fix: Blood cultists using a stun spell now emit a flash of red light when.... they emit a flash of red light!
fix: Blood cult stun spells now properly check for any holy items on the target mob.
tweak: Targets immune to blood cult stun spells will now glow with holy light for a short duration after.
/:cl:

### CODE REVIEW

**Comment by Potato-Masher** [comment]
I really don't want to nag on a nice fix like this, but wouldn't people be able to see the red flash through walls somewhat because of how lights somewhat permeate walls, even on the other side?

**Comment by Vidiveni** [comment]
Give flash, wall mounted flash, flashbang and flash powder light effects as well, but white. Always bothered me how those are invisible.

**Comment by GuyonBroadway** [comment]
Underclocking flashbulbs to make ghetto flashlights when?

**Comment by ShizCalev** [comment]
moblight helper added so I can easily add it to flashes and all that that in another PR.

**Pull request merged**
