### PR TITLE
Changes the text human ==> humanoid where applicable.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/-tg-station/issues/9899.
Fixes https://github.com/tgstation/-tg-station/issues/12471.

This way is probably better for if we add more mutantraces

### CODE REVIEW

**Comment by demonfiren** [comment]
0/10 not being sneaky and doing it to assmov

**Comment by Alek2ander** [comment]
:snake:

**Comment by Firecage** [comment]
But....monkeys are also humanoid....so are xenos...

**Pull request merged**
