### PR TITLE
Bilingual can now choose their language

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

This was one of the tradeoffs for removing other, more consistent sources of languages, and was requested by Melbert among many others.
This does go against my wanted goal of decreasing the risk of eavesdropping by other players through just magically knowing a language, but it is an expensive quirk and it is in their medical records, which makes it better than language encryption keys or silicon just innately knowing them.

This also limits Bilingual to only roundstart languages (+Uncommon), rather than being randomly selected from a list (that had very useless ones like monkey, podpeople, and beachbum). This is mostly just for modularity, I didn't want to make it look terrible code-wise and thought this may be the optimal way to handle it.

This is also me going back on https://github.com/tgstation/tgstation/pull/71773 - which I had closed myself.

## Why It's Good For The Game

If we're gonna keep the Bilingual quirk, it might as well be something players can choose the language of, it's their character and they should be allowed to decide how their character is, and it is my fault that this stupid compromise of "getting a random language" was made in the first place. It never should've happened.
It now actually limits it to roundstart-only languages, so there's no way you can spy on people who prepare in advance through becoming podpeople, or monkeys, etc.

## Changelog

:cl:
balance: Bilingual quirk now lets you choose your language between ones given to roundstart species.
balance: Foreigner and Bilingual are now mutually exclusive languages.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
@timothymtorres vindicated today

**Comment by AyamePup** [comment]
While I do agree this is an overall improvement, I dislike that its only roundstart languages. "This also limits Bilingual to only roundstart languages, rather than being randomly selected from a list (that had very useless ones like monkey, podpeople, and beachbum)."
If you consider them useless, why not allow them in the list? It could allow for very interesting gimmicks. Languages like the syndicate codewords one and such I understand removing, but I think including the lesser used languages is far better than just limiting it to roundstart. Ie, a xenobio main taking slime, a maints sect chap taking shadowtongue, ect- Theres very few good ways for them to acquire the language otherwise unless a miner is willing to part with a book of babel.

**Comment by TheVekter** [comment]
Someone brought this up but I am not for increasing the price on bilingual; I like it as a positive quirk and -4 is in the same ballpark as other "generally useful but not explicitly powerful" quirks like alcohol tolerance and light step.

**Comment by SomeoneYouProbablyKnow** [comment]
Leaving an option for players to opt in into getting a totally random languages instead of a crew species one could be neat. Would keep it cleaner and prevent bullshit like all of sec taking a specific otherwise inaccessible languages as a meta

**Comment by TheVekter** [comment]
> prevent bullshit like all of sec taking a specific otherwise inaccessible languages as a meta

This would be an administration issue; if everyone in sec is meta planning to that degree, we have bigger problems.

**Comment by SomeoneYouProbablyKnow** [comment]
> This would be an administration issue; if everyone in sec is meta planning to that degree, we have bigger problems.

Wouldn't surprise me if that happened (obvioisly this is 100% vibes based). But it's not even planning, it could happen organically with the mindset sec seams to have. Like the improv shell craze.

**Review by spookydonut — APPROVED** [review]

**Pull request merged**
