### PR TITLE
Reorders the items and weapons dmi.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Reorders the items and weapons dmi and moves some of them in new icon files.

## Why It's Good For The Game

This file had almost 300 icon states and they had no order whatsoever, making it hard to actually find the icons you needed.

## Changelog
:cl:
imagedel: Some unused/duplicate changeling icons.
 /:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
I need to do a dmi cleanup sometime.

**Comment by nemvar** [comment]
We also lost 12 KB, so that's nice.

**Comment by AnturK** [comment]
Just split it into something more manageable ?

**Comment by nemvar** [comment]
Alright. I seperated banners, changeling stuff, energy swords and defibs into new icon files. Kinda regret the changeling stuff now that I know that it's only three icons and the rest were duplicates.

**Comment by nicbn** [comment]
It'd be neat to have DMI tool that reorders every DMI alphabetically and compresses colors (even if there's alpha) into palettes when it saves space

**Comment by ShizCalev** [comment]
@nicbn http://www.byond.com/forum/post/2433359

**Pull request merged**
