### PR TITLE
Fixes robotics lab disposals on tramstation

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Connects robotics trashbin to disposal system tramstation

## Why It's Good For The Game

Recycling

## Changelog

:cl:
fix: Connects robotics trashbin to disposal system on tramstation
/:cl:

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
where is this, mappdiff bot shows its here, but this isnt robotics

image

**Comment by Donpedrito** [comment]
Fixes #64570.
Roboticists and mailmen rejoice!

**Comment by SmoSmoSmoSmok** [comment]
> where is this, mappdiff bot shows its here, but this isnt robotics, maybe show a screenshot of what you changed (you should be doing that for map edits anyway, so we know whats actually being edited)
> 
> the code changes shows the sort segment was changed for a normal segment which feels odd too, shouldnt it be replaced with a normal pipe?? all you had to do was move the sort junction and the left pipe down by 1 tile, and place a straight pipe above it, shouldnt have needed a new segment
> 
> image

i just shifted the sort segment down 1 tile and added an extra pipe to the left of it

**Comment by SmoSmoSmoSmok** [comment]
> where is this, mappdiff bot shows its here, but this isnt robotics, maybe show a screenshot of what you changed (you should be doing that for map edits anyway, so we know whats actually being edited)
> 
> the code changes shows the sort segment was changed for a normal segment which feels odd too, shouldnt it be replaced with a normal pipe?? all you had to do was move the sort junction and the left pipe down by 1 tile, and place a straight pipe above it, shouldnt have needed a new segment
> 
> image

also you're viewing Z:1 go to Z:2 to see the change i did

**Comment by SmoSmoSmoSmok** [comment]
Before: https://prnt.sc/26n42i5

After: https://prnt.sc/26n425y

**Pull request merged**
