### PR TITLE
removes dual eswords

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl:
del: Dual energy swords can no longer be constructed.
/:cl:

reopened this pr for cheridan and kor since they wanted it or something idk i just saw the old pr pop up and cheri trying to reopen it but having to close for old age so i figured id remake it hey you folks seen that hot new movie manos the hands of fate i hear its chill

### CODE REVIEW

**Comment by ma44** [comment]
He's just trying to get the bounty so he can ten bribe the maintainer

**Comment by evsey9** [comment]
Did I kill you while I was murderboning as traitorling?

**Comment by SgtxRootbeer** [comment]
Changelog meme detected

**Comment by KorPhaeron** [comment]
You need a reason in the OP as to why

**Comment by KorPhaeron** [comment]
Cant wait from all the "git gud" from people upset they wont be able to tank an armories worth of gunfire while crippling everyone in one hit each

**Comment by Tacolizard** [comment]
git gud

**Comment by evsey9** [comment]
i thought this is a meme

**Comment by kevinz000** [comment]
Goofball is right.

**Comment by Tacolizard** [comment]
What is this coderbus custom of maintainers and staff asking coders to make controversial PRs and then take all the heat for it

**Comment by KorPhaeron** [comment]
vcordie isnt coderbus staff you meme

**Comment by kevinz000** [comment]
What's the difference between tacolizard and ma44?
Ma44 is tolerable.

**Comment by Iamgoofball** [comment]
@Tacolizard im just being a good samaritan

@Cheridan maintainer when

**Comment by XDTM** [comment]
wtf i like goof now

**Comment by Armhulen** [comment]
remove the description bit in the uplink that tells you that you can attach two swords please

**Comment by jughu** [comment]
Goof for headmaintener

**Comment by Tacolizard** [comment]
Whats the difference between kevinz and ma44?

at least ma44's code works

**Comment by GunHog** [comment]
> What is this coderbus custom of maintainers and staff asking coders to make controversial PRs and then take all the heat for it

To get around the rule against merging one's own PR.

**Comment by Tacolizard** [comment]
whats the difference between kevinz and an auto-downvote bot?

kevinz tries to disguise himself by making prs, except he is a robot so they never work correctly they are merely a smokescreen

**Comment by FantasticFwoosh** [comment]
Atleast we still have triple eswords for april fools

**Comment by CPTANT** [comment]
This will probably just shift murderbone to ebow + esword

**Comment by XDTM** [comment]
that gives me an idea for another pr!

**Comment by PKPenguin321** [comment]
Pretty stupid, at least make it available for nuke ops/add a real changelog/remove mentions of deswords being craftable. :-1:

**Comment by KorPhaeron** [comment]
@CPTANT 

At least you can shoot or disarm those people

**Comment by ShadowDeath6** [comment]
based

**Comment by FantasticFwoosh** [comment]
Already dealt with @CPTANT  #27078

**Comment by Bawhoppen** [comment]
I will thumbs up this PR if goof tells me his favorite anime

**Comment by Jordie0608** [comment]
Make a real changelog scrub.

**Comment by kevinz000** [comment]
oh yeah let oppers have it, since they're well, meant to be "lets kill everyone" type antags 
also what's the difference between tacolizard and me?
i contribute more than once (in which i mean the only thing he contributed is the graphics directx stuff).

**Comment by Tacolizard** [comment]
>i contribute more than once

re

**Comment by BeeSting12** [comment]
To preface I don't buy dual energy swords because they're actually fairly weak if the people you're fighting aren't autistic mongoloids. I could spend time listing their hard counters but you've already seen them. Dual energy swords are balanced and I greatly enjoy combatting them as security just because of how easy they are to take down and how salty the murderboner gets.

**Comment by ShadowDeath6** [comment]
Dual esword is extremely difficult to counter if the user aren't retarded because of its absurd delimb / knockdown chance and the ability to whip it out and activate it then click someone adjacent to you

Of course it's easy to counter someone waving it around like 10 tiles away, it's a melee item.

**Comment by Durkel** [comment]
Update the sith lord bundle you nerd.

**Comment by BeeSting12** [comment]
@ShadowDeath6 
Riot shotgun. Bola, which takes <10 seconds to make. Any ballistic really. I hear the librarian meme whip can do it. Soap obviously. Pies, I cucked a dual esword traitor with one of those. You can mob up on him, he can't hit 9 at once. It's not that hard.

**Comment by ShadowDeath6** [comment]
Notice how those all have range
The only times I've seen a dual esword user do well is by walking up to someone without it drawn then suddenly 3shotting them before they can react
It's not hard to stop someone who's using a weapon that restricts them to melee, but it's also very irritating to deal with an esworder who kills an officer while they're talking, takes their taser, then goes on a rampage stunning and 3shotting anyone hit by a taser bolt

**Comment by Repukan** [comment]
You mean a high price melee weapon has a high advantage in melee?

Holy fuck call the news channel

**Comment by Robustin** [comment]
>Nerfing a weapon thats not even in the top 5 of traitor murderbone combos

Fucking casuals.

**Comment by YakumoChen** [comment]
gut gud? Desword is easy to counter literally just by mobbing with disarm spam, getting a shotgun or .38, using slips, or one of the many, many, many other ways we've implemented non-taser stuns in our stun based combat game.

**Comment by Bawhoppen** [comment]
quick close the PR before the forum warriors find it
we can always remake it later

**Comment by jughu** [comment]
Using a bolas makes double esword litteraly a joke

**Comment by CPTANT** [comment]
double esword does block 75% of shotgun projectiles by the way.

**Comment by YakumoChen** [comment]
use the freeze gun so the esworder can't get you

**Comment by MrPerson** [comment]
I suspect the problem isn't balance, it just not wanting to encourage murderboners.

But what do I know, goof didn't include any reasoning in the PR body like he's supposed to.

**Comment by FantasticFwoosh** [comment]
@YakumoChen that item is garbage and thats pretty poor as far as gearchecks go, for me it'd be either the bartenders double barrel shotgun with beanbag rounds to knock them down in two, or to e-bola them in order to slow for a more accurate hit & try to baton them.

**Review by Dorsisdwarf — CHANGES_REQUESTED** [review]
If you're removing dualie construction, remove the uplink description saying you can stick them together.

**Comment by XDTM** [comment]
What mrperson said. We're giving the best possible combat gear at roundstart. Traitors aren't encouraged to try and steal some high-power weapons first, if they can buy-n-slay while also having an advantage over traitors who try to get weapons from other sources.

**Comment by 4dplanner** [comment]
But it's not the best possible gear. Every department has something that overpowers a double esword with time-
Botany's explosive tomatoes crush it
Cargo's null crates give you more stuff
Crush them with a mech
Emagged borgs are better
etc etc

**Comment by Tacolizard** [comment]
when a double esworder is murderboning roundstart, nobody has 'time' to build counters

**Comment by Iamgoofball** [comment]
@Dorsisdwarf done

**Review by Dorsisdwarf — APPROVED** [review]

**Comment by XDTM** [comment]
Explosive tomatoes are strong but the other examples are just traitor items again, and mechs may be sturdy, but much harder to murderbone with.

Plus i'd rather watch someone murder by tomato slinging or a deathbot than desword rampage number 10000

**Comment by lzimann** [comment]
Oh wow, missed the other pr closing this.

**Comment by ChangelingRain** [comment]
My PR basically replaces this PR unless goof wants to go through and try and remove dual eswords being buyable. I doubt he'll succeed.

**Comment by DamonFriedberg** [comment]
a properly cultivated death nettle is arguably scarier, unconscious in 1 hit, dead in ~3

**Pull request closed without merging**
