### PR TITLE
Four Corners, Red Rover: An Exploration in Decal Trends [MDB IGNORE]

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

You there! What exactly is wrong with this photograph?!

image

You don't need to tell me, I've boxed it out. There's four individual corners for the decalling. This is weird. You may be asking: Why don't they use the "full tile" turf decals? Let me demonstrate.

image

Look at the difference between the one at left and the one in the middle. The turf decal totally smothers the nice contrast lines afforded to use by the base turf, causing it to have smooth, clammy exterior. This is probably why no mapper ever uses the full turf decal, much to the chagrin of people who stare at how big the size of this repo is.

Now, what's that on the right? Why, it's the new sprite (and pathing I made) to help counter-act this issue! This perfectly lines up with the contrast lines of the base turf, allowing us to have a non-flattened visualization, while not having four fucking turf decals a turf load upon initialization. How epic!

image

I've also added "contrasted" variants of the "half" and "anticorner" turf decals for future use. I probably won't go through and update this across the maps in this PR, but the opportunity remains available.

I mapped this change in over all the instances I could see. Feel free to add onto my work.

## Why It's Good For The Game

Less var_edits, to keep coders happy.
Less instances of similar objects loading, may help with loading (unverified claim that I do not plan on verifying so don't quote this as being a performance change, i just think less things mean that load go faster)
More happy mappers with more tools to save time as they draw across this canvas we call life (and .dmm files).

image

## Changelog

:cl:
add: Instead of having four different corners on each floor, Nanotrasen has decided to slap down full corners on each floor to keep that one floor looking that masterful shade of beige.
/:cl:

My GitHub Webpage is lagging to shit writing this out so please exercise caution and have a prayer in your heart if you want to explore beyond this point.

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
You sir are a god amongst mappers.

**Comment by Zytolg** [comment]
First we had the most soulful of Plasteel floor sprites. Looked worn and used. 
They stole that from us.
They updated the tile decal and then expanded upon it, giving us half tiled turfs, corner tiled turfs, and full tiled turfs. 
They lacked companion decals on terms of tiling however.
I asked @Imaginos16 to bless us with tiles for the new turfs. He delivered. 
That's the modern history of stuff related to this PR. 

Ask yourself. Is having the specific 4 tiled fulltile turf worth the bloat in the environment window? That's going to be the weakest point of this PR. As one of the "Old Guard", I'm pretty neutral on this going in or not. If it does, then neat, I'll use it. If it doesn't, I don't care. I'll continue what I do best. If this does make it in though, I expect the PR Owner to go in and add all of their decals to all the maps where they are applicable. It's busy work that nobody is going to do and this PR isn't going to change much unless those decals replace the decals they intend to replace.

**Comment by TrashDoxx** [comment]
DIDN'T READ LOL

**Comment by san7890** [comment]
> First we had the most soulful of Plasteel floor sprites. Looked worn and used. 
> 
> They stole that from us.
> 
> They updated the tile decal and then expanded upon it, giving us half tiled turfs, corner tiled turfs, and full tiled turfs. 
> 
> They lacked companion decals on terms of tiling however.
> 
> I asked @Imaginos16 to bless us with tiles for the new turfs. He delivered. 
> 
> That's the modern history of stuff related to this PR. 
> 
> 
> 
> Ask yourself. Is having the specific 4 tiled fulltile turf worth the bloat in the environment window? That's going to be the weakest point of this PR. As one of the "Old Guard", I'm pretty neutral on this going in or not. If it does, then neat, I'll use it. If it doesn't, I don't care. I'll continue what I do best. If this does make it in though, I expect the PR Owner to go in and add all of their decals to all the maps where they are applicable. It's busy work that nobody is going to do and this PR isn't going to change much unless those decals replace the decals they intend to replace.

It's one extra decal (three). We have several turf decals already. I am not of the belief that adding one (three) things to the environment tree is "bloat" especially when you cut down on 30,000 extra lines and don't need to manually add every corner. 

Also, keep in mind what this is replacing. Any special turf decalling with FOUR corners will show up. Imagine a table with three objects on it, on top of a four-cornered tile. In the right-click menu, that is:

Object One
Object Two
Object Three
Table
Corner One
Corner Two
Corner Three
Corner Four
Turf
Area

This PR cuts it down to:
Object One
Object Two
Object Three
Table
Corner Decalling
Turf
Area

Now, let's think. This PR adds three things to the environment tree, and only ONE of them can remove FOUR items on the right-click menu.

Food for thought.

**Comment by Tastyfish** [comment]
Now for someone to make the in-game floor tile skinning menu not awful.

**Comment by Inari-Whitebear** [comment]
> Now for someone to make the in-game floor tile skinning menu not awful.

And to add an option to do half those decals in the game..

**Comment by ShizCalev** [comment]
conflicts. will merge once fixed.

**Pull request merged**
