### PR TITLE
Changelings can now speak through their decoy brain if placed in an MMI

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- If a changeling's decoy brain is placed in an MMI, they will now be prompted to speak through it. 
   - They can speak through the decoy even if incapacitated or dead (or fake-dead). 

https://github.com/tgstation/tgstation/assets/51863163/804bd48a-c4b8-4feb-b021-019ea70e4b8e

## Why It's Good For The Game

The oft-controversial ling MMI test has been brought up time and time again so I figure I throw my cards in for a solution.

We want as few ways as possible for people to hard and fast discover whether someone is an antag, especially changling which is supposed to revel in paranoia. This soft-patches out a big way, the MMI test, in which you place a ling's brain in an MMI to determine if it's vestigial and therefore, a ling. 

Now the ling player can provide some benefit of the doubt by speaking through the brain as normal, appearing active while actually in their body still. 

## Changelog

:cl: Melbert
add: Changelings can now speak through their decoy brain if it is placed in an MMI, to maintain the illusion they are actually dead and have been debrained. 
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Also maybe worth testmerging first because I messed with braincode a bit and we all know how that goes

**Comment by GPeckman** [comment]
> The decoy brain will relay speech that it hears to you in purple

I really hope someone uses this for a gimmick where they spy on everyone by leaving their own decoy brains all over the place.

**Comment by Jacquerel** [comment]
What happens if it is placed inside a cyborg?

**Comment by Pickle-Coding** [comment]
What happens if the changeling dropped multiple brains and they get MMId?

**Comment by MrMelbert** [comment]
> What happens if it is placed inside a cyborg?

It doesn't fit in shells

> What happens if the changeling dropped multiple brains and they get MMId?

They can talk through multiple MMIs

**Comment by MrMelbert** [comment]
> Also what happens if a wizard mindswaps with it?

... Can you mind-swap into an mmi? I know (I think I know) you can go *out* but not *in* AFAIK
In any case it would fail because it has no mind
But it would fail regardless because you can't mindswap into a ling

**Comment by trexter5555** [comment]
> > What happens if it is placed inside a cyborg?
> 
> It doesn't fit in shells
> 

wont people just try and put it in a shell to see if its a ling brain and confirm ling status or am i missing something

**Comment by Jacquerel** [comment]
> wont people just try and put it in a shell to see if its a ling brain and confirm ling status or am i missing something

The output you get there has several other causes (including cyborg roleban IIRC) which means it can't be shared as damning IC and makes banning people who use this OOC information very trivial.
It's still not foolproof because you get some information, but it's better.

**Comment by BlueMemesauce** [comment]
The meta is just going to become trying to convince the other person you're silicon banned

**Comment by Vincent983** [comment]
solution, just get sillicon banned, then you don't have to convince them

**Comment by BlueMemesauce** [comment]
Also what if they just test putting MMI in a mech? you can't get rolebanned from mechs i dont think. I guess it's too much of a waste of resources to be valuable?

**Comment by Vincent983** [comment]
To be fair, if you're suspect enough that security takes you in and debrains you, they probably don't want to risk putting you in a mech that you could punch them with. Plus the only way to get you out of said mech aside from you ejecting yourself is to destroy said mech, which gets expensive after a while

**Comment by san7890** [comment]
a good idea oranges and I had when this debate occurred around this time last year on the forums is that a changeling would be able to regenerate their body while in a cyborg machination and then burst out of that in a spectacular animation when they were finally free (and would be asimov otherwise, or at least pretend to be). that's much more work but i think it's a very good idea personally

**Comment by MrMelbert** [comment]
it is a cool suggestion however it's been a year and no one's coded it so here we are

**Comment by san7890** [comment]
well and truly a womp womp moment

**Comment by githubuser4141** [comment]
> To be fair, if you're suspect enough that security takes you in and debrains you, they probably don't want to risk putting you in a mech that you could punch them with. Plus the only way to get you out of said mech aside from you ejecting yourself is to destroy said mech, which gets expensive after a while

Except: mechs without a power cell can't do anything and are harmless

**Pull request merged**
