### PR TITLE
Detective's revolver and ammo now starts in his holster

### PR DESCRIPTION
**Pull request by jughu**
if security can have this luxery why not the detective

:cl: Hyena
tweak: Detective revolver/ammo now starts in their shoulder holster
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)SECURITY GETS THIS LUXERY WHY NOT DETECTIV

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Fix YOUR NAME IN YOUR CL AAAAAAA

**Comment by jughu** [comment]
what if my name is optional name?

**Comment by Robustin** [comment]
Holster is shit plz dont make me do more work tearing it apart every round.

**Comment by Haevacht** [comment]
Revolver spawns in the closet so people who are not the detective can get it, nerd.

**Comment by Steelpoint** [comment]
It spawns in the locker so that even if there is no Detective, security can still get access to the revolver in a emergency to help stop energy sword users, though I prefer a shotgun but I digress.

**Comment by jughu** [comment]
Holster is stil in his locker his gun and ammo are just in it like securities baton n stuff starts in their secbelts

**Pull request merged**
