### PR TITLE
Fixed maps constantly being metastation (fixes recent maps being included in mapvote)

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

See title. The vote subsystem needs to load after the persistence subsystem so that the blocked_maps list can be properly populated with data from the RecentMaps.json in the data folder.
This fixes the maps constantly being metastation

## Why It's Good For The Game

Same map over and over again = bad
Different maps each time = good

## Changelog

:cl:
fix: Fixed map vote including maps that have already been played twice in the last 3 rounds.
/:cl:

### CODE REVIEW

**Comment by epicgamer545** [comment]
But...
Metastation good...

**Comment by dawsonkeyes** [comment]
while this is a good fix, it's _very telling_ that everyone will vote metastation so long as it's always in the pool

**Comment by san7890** [comment]
image

I took this screenshot 30 seconds ago.

**Comment by the-orange-cow** [comment]
I get where this is coming from, but if the overwhelming majority of people want to play on metastation, it's hard to see preventing that as a net good.

**Comment by san7890** [comment]
> I get where this is coming from, but if the overwhelming majority of people want to play on metastation, it's hard to see preventing that as a net good.

It was always meant to be this way, it's just that the feature was broken in a rework of the voting system.

**Comment by LemonInTheDark** [comment]
> I get where this is coming from, but if the overwhelming majority of people want to play on metastation, it's hard to see preventing that as a net good.

haha no

**Pull request merged**
