### PR TITLE
Reverts newcult

### PR DESCRIPTION
**Pull request by Buggy123**
Wizard-revs is better than wizard-ops, a shitload of people don't like newcult, so lets see what people think of this.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
:+1: :x: :100:

**Comment by KorPhaeron** [comment]
Feature freeze is what I think of this

**Comment by feemjmeem** [comment]
feature fre--efb

**Comment by AnturK** [comment]
Nice meme commit.

**Comment by AlexanderUlanH** [comment]
:+1: I hate new ideas

**Comment by tkdrg** [comment]
Feature freeze and also incoming is working on datum antags and also this PR literally does nothing except remove the large narsie icon
The only reason I don't close your stupid meme PR right now is to avoid claims that I'm trying to censor it
@tgstation/commit-access please

**Comment by Buggy123** [comment]
Whoops i fucked it up

**Comment by borntohonk** [comment]
Good.

**Comment by Buggy123** [comment]
fixing

**Pull request closed without merging**
