### PR TITLE
Prohibits IC Changelogs

### PR DESCRIPTION
**Pull request by Cyberboss**
The changelog should actually describe what you change and shouldn't need deciphering/cross-referencing

### CODE REVIEW

**Comment by Armhulen** [comment]
f

**Comment by optimumtact** [comment]
A) they're funny if done right
B) this doesn't need to be said, just comment on the persons pr
C) stop wasting time

**Comment by lzimann** [comment]
IC changelogs are the one wasting everyone's time though

**Comment by ShiggyDiggyDo** [comment]
FIGHT! FIGHT! FIGHT!

**Comment by Anonmare** [comment]
They're traditional

**Pull request closed without merging**
