### PR TITLE
Replaces miner jackboots with mining boots

### PR DESCRIPTION
**Pull request by ChangelingRain**
piecemeal changes, creeping towards OVERALLS
overall, these are very boot-like

### CODE REVIEW

**Comment by Cheridan** [comment]
i don't like suits with fake boots since it covers up the _actual_ boot sprite that your character is wearing

**Comment by RandomMarine** [comment]
That. These aren't a space suit. Just add separate, matching boots.

**Comment by ChangelingRain** [comment]
Done. I'd like to note that, while the explorer suit will look odd with magboots, *literally every suit does* because magboots are as tall as galoshes and super fucking wide.

**Comment by Cheridan** [comment]
Yeah the magboot sprite is bad

**Comment by RandomMarine** [comment]
Magboots used to be a steal objective, so it made sense that it had a big, distinct sprite. Now, not really, could use a change.

**Comment by Core0verload** [comment]
CE's magboots still are.

**Comment by KorPhaeron** [comment]
I hate change reeeeeeeeeeeee

**Comment by KorPhaeron** [comment]
I think it looks weird for the reason that @RandomMarine said, in that the shoes look like the suit is some one piece thing now, instead of shoes.

**Comment by ChangelingRain** [comment]
The suit isn't one piece, the shoe just make it look like it is; this is super intentional because it looks really nice

**Pull request merged**
