### PR TITLE
Armor now resists Disabler shots more strongly than Lasers

### PR DESCRIPTION
**Pull request by TooFewSecrets**
## About The Pull Request
Most armor types formerly had 10 energy (a damage type near-exclusively used by Disablers) resistance across the board; now it is 10 points higher than the armor piece's Laser resistance, except for the Captain's Carapace where it is now equal (50 up from 10), to keep the Reflective Vest a superior anti-energy option in exchange for its specialization, and the Reflective Vest where it is now equal (60 up from 50), because 70 resistance and 50% reflect chance would make Disablers pitifully weak. May require further balancing for Pulse Rifles, but as those are admin-spawn only I think that's an entirely separate consideration - and Deathsquads usually show up to deal with targets that can't wear armor anyway. Oh, helmets are buffed too, as is any other exosuit clothing that provides damage resistances.

[Antag armor changes don't violate freeze, as per Cobby.](https://cdn.discordapp.com/attachments/497936641034551306/634328400147906570/unknown.png)

## Why It's Good For The Game
On the Security force, lethal weapons and all non-lethal options except the stun baton are mostly unused outside of the recently-nerfed shotguns because absolutely nothing reasonably protects from a Disabler at all except for Reflective Vests or outright stamina damage immunity - even if the victim doesn't have protection from other stuns, it's simply more practical to beam them down instead of using pepper spray or a flash, including people in something as supposedly-resilient as the Captain's Carapace. With these changes, Disablers are still the premier way of taking down unarmored targets, but it's far more practical to use other options, or at least aim for limbs before closing the distance to baton, against any target with actual armor on. Also gives a reason to actually consider carrying a lasgun as Security, when it's currently a weapon that almost always takes more shots to drop someone than the Disabler and has about half the battery size. Conversely, makes stolen or Cargo-ordered Disabler weapons far less dangerous against Security members who are guaranteed to have protection on their torso and head - dual Disablers will currently drop a Security Officer as fast as an expensive Syndicate Revolver or impossible-to-conceal Combat Shotgun, with almost twice as much total damage before having to reload.

## Changelog
:cl:
balance: Disablers are now more effectively stopped by all forms of body armor. Performance against unarmored targets is unchanged.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
+1 if you shoot red hardsuit man you use ouchy gun not anti-tider gun

**Comment by Shadowflame909** [comment]
I disagree with this.

Security should continue to focus and thrive on detainment and non lethal methods of stopping a criminal.

We already have an elevated culture of validhunting + mufderboning,

And the intent of security not spawning with lasers is to literally prevent any shoot and kill first, question second situations.

Lethal should be distributed when a confirmed code red threat appears.

Let's not make a crew member stealing armor from arrivals into one of them.

**Comment by Tlaltecuhtli** [comment]
why would civilian carry armor then?

**Comment by Ratvar** [comment]
Don't carry anti-security armor as a civilian

**Comment by Shadowflame909** [comment]
You guys are viewing the effects as limited.

Currently non lethal disablers can safely down all targets, high risk or not.

If one civilian gets sec armor. Out of 60 - 100 on a high pop round. Security now has justification for lethals when they didn't previously.

 Assistants will get armor

And security with lethals will shoot and kill instead of disable where they could and would previously.

Turning killing into the only method of detainment is not good for the current state of tg

**Comment by fludd12** [comment]
I think a good idea would to make a certain kind of armor resist disablers, one that isn't common or that is semi-difficult to obtain along with more conventional armor types. This would mean sacrificing resistance to more lethal combat in exchange for resistance to disablers, and give security a visual cue when to handle someone with lethal force.

Of course, this may have the same issues as mentioned above. It's a tough balance.

**Comment by py01** [comment]
Energy armor needs an update, considering none of them have been touched since taser removal and most armors have very little energy armor, despite being one of the more common damage types now.

Disablers are still better than lethals at taking down targets even with these armor changes, because disablers have a +10  damage bonus. Under the system of having energy = laser + 10, disablers are only worse than lasers if the target has greater than 70 laser, 80 energy armor.

**Comment by carlarctg** [comment]
ah yes shadowflame its so good when people detain the nuclear operative with a disabler instead of you know killing them with a normal gun (then execute them with a harmbaton)

**Comment by Shadowflame909** [comment]
If that's the only reason you like the PR...

Unironically yes. That's good.

If the flukie is too new to use there suicide. They deserve the gear.it also allows for situations like getting the crew close to you. So you can use your maxcap suicide bomb.

Also non antags can't use the syndicate uplink. So if they're too new to suicide. They're too new to access TC.

PR not needed to completely warp balance.

**Comment by carlarctg** [comment]
what the fuck kind of argument is that?
anyone with half a brain that wants to loot a nukie can simply shoot them into crit and strip them there, you don't need the crutch that is disablers if you have a few braincells?
and if that's your only argument then yikes because the game should in fact not be balanced around newbie nukies being loot pinatas

**Comment by Shadowflame909** [comment]
Shooting a nukie into crit and trying to loot them is like starting the timer on a syndicate bomb, and then waiting till it's at 30 before rushing it from bridge to an arrivals airlock.

The last part of what you said doesn't make sense because it isn't what I'm arguing. It's me trying to understand why you don't want nukies to be looted.

**Comment by TooFewSecrets** [comment]
I'm going to be pretty frank, Shadowflame - people do not bleed out fast enough in this game for crit vs. stamcrit to matter against Operatives that don't activate their bomb. Even in hardcrit you can take over a full minute to die, and unless you keep dumping bullets into them long after they fall over that simply isn't happening before they're stripped. "This nerfs powergamers abusing other people misplaying" is a pretty ridiculous argument for not liking a balance PR anyway, and macrobombs aren't really used by baiting someone into looting, they're used by attracting five or six people into Cargo to fight one Operative and blasting those people and the entire Cargo Bay into bits with the huge gib radius.

Also, there's a reason I specifically didn't buff hard hat energy resistance. (They're still at 10 rather than the 30 they "should" be.) This is supposed to nerf Disablers VS organized and supplied enemies, whether those enemies are Operatives, Revolutionaries who have taken over Cargo, or even Security officers themselves, because in such a situation the Warden should actually be doing his one job of handing out more effective gear against those targets (Again, when is the last time outside of Blob that you've seen a Warden hand out laser guns?), or people trying to murder Security officers should be doing it with lethal weapons and not stun guns.

**Comment by Shadowflame909** [comment]
I understand your intent. But you're literally turning armor into a hulk situation here.

The more hulks that are around, the more dead non antagonists there are.

Don't forget that with supplied enemies of whatever. Be it a traitor that looted sec arrivals or a wizard in their hardsuit. That security catches and detains 5 other people per that 1 antagonist.

And just like how escalation currently ends with a very antaglike bloodshed.

I don't want to see the downsides of this PR being lethals used on non antagonists because the mutinious cargo or whatever decided to loot and buy some armor so they couldn't be taken down with disablers.

Antagonists sadly aren't the only driving force of conflict in this game. Minor acts of shittyness will lead to non antagonists getting up to there own schemes, and I'd rather not have the non lethal weapon replaced with a lethal one because they took the time to put on armor.

**Comment by TooFewSecrets** [comment]
Why would Security even bother arresting crew during a Wizard or Nuclear round?
Why can Security magically not carry around a lasgun and a Disabler? I'd understand if we were nerfing a Bulky weapon that only fits in armor slots, but you can carry four sidearms in a backpack and still have space for healing items and spare grenades.
How is 40% resistance remotely the same as 100%?
If Cargo is not antagonist and rebels, I feel like they deserve to be shot at with lethal weapons, because not having Cargo can cripple a station depending on the round type.

Most importantly, why should a nonlethal stun gun be by far the most effective weapon per-shot against heavy armor? Again, two disablers outdo a _shotgun,_ which by default can't be carried anywhere but hands and has extremely bad range if sawn off, against just about any armor item in the game.

**Comment by Shadowflame909** [comment]
>Why would Security even bother arresting crew during a Wizard or Nuclear round?
It does happen. HoP doesn't want to hand out all-access, sec doesn't want to give guns. An assistant rushes/breaks into the armory. Etc Etc. Jail time, death. For the wizard round-type, there's a whole lot of paranoia bullshit and this would be a pretty perfect example. Since he has the ability to give the entire crew guns or magic. Including magic pieces of armor. So...

The main issue here is that you don't foresee the main design of this game going against your massive balance change.

It's about a normal plasma research vessel going off the rails for whatever reason. That being a wizard using it as a testing ground, the syndicate with a vendetta, revolutionaries sick of the governing body. Etc, Etc.

When things go off the rails, Items like armor and disablers won't be used by their intended job role. 

Hell, when was the last time you've seen an atmos technician stop a plasma-flood? Or have been healed up by a medical doctor during mass chaos. Or security being the ones to take down the malfunctioning Ai? It's usually some other random guy taking the mantle during insanity. 

Antagonism lurking behind the scenes and throwing the game in jeopardy. There is a very likely scenario of an assistant or whatever walking around with armor. Sec being suspicious and not trusting of the crew with armor. Will shoot to disable first, take it off of him and to sec. Then ask questions later.

Now? They're going to literally kill the non-antagonist. Maybe clone him. Some beef with escalation and a long angry spam argument in ahelps is going to ensue. When this can all be avoided with murphy's law.

Anything that can go wrong will go wrong.

And for the last tidbit that should be read: There's a lot that will go wrong when you bump up the importance of lethal's as an option, in a game set about a station going wrong.

**Comment by necromanceranne** [comment]
Why the bad man not go down when shoot disabler at him? He has no protection!

I'll be honest, I'm amazed it's taken this long for people to acknowledge just how powerful disablers (and ebows) really were number wise. I think in part it was because there was still the meme that armor values don't matter when, actually, they absolutely do matter in the current state of the game and disablers not only did more damage than lasers, but largely went unchallenged by armor values.

For those not in the know, ebows use energy. This is largely a security buff, and ebows will be far weaker as a result. Not like they weren't already stupidly strong just for disabling the crap out of you.

**Comment by TooFewSecrets** [comment]
I'd like to be clear here, we're talking about Disablers taking one more shot than Lasers. It's not like I'm bumping Energy resistance to 80, which is how you've reacted in the comments for this entire PR; I'm bumping it to 40, so they aren't a magical pierce-all-armor six-shot-down-literally-anyone weapon. They still have the massive magazine advantage over lethal Lasers, they just aren't a ridiculous over-emphasized option by virtue of downing anyone faster than anything else Security has. Lasers will down slightly faster, and their damage sticks even if you're forced to retreat, but they have less ammo. Currently, against any target with any amount of armor, the only advantage Lasers have is permanent damage, but Disablers down fast enough that actually being forced to back off is unlikely, so it's irrelevant. Shots to down will go up by two against Security-type 30 laser resistance armor.

Again, after this patch Disablers will be worse than Lasers by One. More. Shot.

Considering it takes literally twice as much damage to kill someone as it does to down someone, I'd posit it's nearly impossible to "accidentally" kill a person when trying to apprehend them with lethal Lasers anyway. _Maybe_ with a Combat Shotgun where the difference can be two fast-firing slugs, but not with Lasers where the difference is at least five shots on an unarmored target. It's not like someone in softcrit can still shoot back at you, and you need literally as many shots as you took to get them there in order to kill them. In the obviously-fake scenario you put forward, the Security officers blatantly intentionally killed someone for literally no reason other than nerves and would 100% deserve a job ban because it is _very_ hard to accidentally kill someone with laser guns. If you've ever done it somehow, bar shooting a welding tank, I would like to know how you managed it. And whether you have eyes.

**Comment by py01** [comment]
You don't need to respond to the peanut gallery, just ignore the insane ranters. It'll preserve your sanity.

**Comment by necromanceranne** [comment]
It's more or less that ancient argument of 'if you nerf nonlethal methods I'll use lethal methods' because people don't have higher brain function and don't realize that we're supposed to laugh at the shotgun man who is so insecure about losing he'll risk getting banned than be reasonably considerate because the game became slightly harder to powergame.

**Comment by Robustin** [comment]
It seems like energy armor values need an update but it should be more nuanced than "laser resistance + 10". Perhaps "light weight" armor should have significant energy resistance (something something better at dissipating energy) while "heavy" armors have very little. 

I also see no reason why disablers should be ineffective against Ops. Ops already have the advantage of teamwork, adrenals, stims, etc. which greatly reduces the potency of stamina damage and elite hardsuits already allow them to shrug off all other damage types. Hell, I'd oppose this PR solely on the grounds that it makes elite hardsuits more uncounterable than they already are.

**Comment by necromanceranne** [comment]
Disablers are some of the most widely available roundstart weaponry of the crew. You have it backwards. Nukies don't have teamwork, crew has numbers and an individual nukie should be able to fight a third/fourth/fifth of the living crew on their own, even when outnumbered. They should not lose to the most spam happy weapon the crew can get. Though obviously eshields exist and make disablers a bad joke, but an eshield is still a sizable investment, but an elite hardsuit is stll an investment.

Also adrenals got gutted and don't practically protect you from shit so frankly armor is the last protection nukies have right now. Touching adrenals are also likely to fall under antag freeze while this is a wider change.

**Comment by SkeletalElite** [comment]
> Also adrenals got gutted and don't practically protect you from shit so frankly armor is the last protection nukies have right now. Touching adrenals are also likely to fall under antag freeze while this is a wider change.

Adrenals are pretty much dead for nukies. Stims are great though. You use them and you get stamina regen + meth speed + stun reduction + baton knockdown reduction for a few minutes. I think that's fine though because you shouldn't be using disablers against a nukies anyways.

**Comment by carlarctg** [comment]
stamina reduction for nukies is very negligible with stimulants, it takes 10 seconds to remove 10 stamina and by that point the stamina removes itself by default

elite hardsuits are counterable by "just bomb them lol"

**Comment by optimumtact** [comment]
This is interesting enough to try out for a month or two

**Pull request merged**
