### PR TITLE
I SUMMON EXODIA, THE FORBIDDEN ONE!

### PR DESCRIPTION
**Pull request by lilacrhododendron**
The unholy trinity of fetish content. Technically made for testmerge for the /tg/ Winter Ball, but it can be full merged if you want oranges ;^) 

:cl: EXODIA
add: You can head pat now! Just target another player's head on help intent.
add: You can hold hands with other players now by targeting their arm on grab intent.
add: Humans can wear collars again, but why would you ever do this?
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️ ❗️ 😑 ❗️

**Comment by plapatin** [comment]
what the fuck is this

**Comment by ExcessiveUseOfCobblestone** [comment]
We need the chaplain to exorcise this PR

**Comment by Qustinnus** [comment]
why didnt you PR this to the winterball branch if its for the winterball idiot

**Comment by Qustinnus** [comment]
also this breaks contributing.MD

**Comment by optimumtact** [comment]
Obviously don't merge this, but leave it here for the ball team to test merge.

**Comment by Jordie0608** [comment]
This doesn't need to remain open to be testmerged; if you want to check it will still merge later just reopen.

**Pull request closed without merging**
