### PR TITLE
Adds system for randomized semi-persistent chem reactions.

### PR DESCRIPTION
**Pull request by AnturK**
Generates parametrized randomized recipe and resets them every x days.
One example reaction added, with recipe available in space ruin (or through experimentation of course).
There's a few obvious improvements to the randomization system but i feel this is good enough to start some discussion. Still need to decide how far should conflict resolution go.

### CODE REVIEW

**Comment by Barhandar** [comment]
Neat, but should never apply to stuff that you reliably need.

**Comment by ExcessiveUseOfCobblestone** [comment]
conflict resolution should just add a random catalyst. It's never used except for leporazine and maybe 1/2 others.

one "issue" from this should we take it further is that a lot of goofchems are grounded in actual medicines and even their recipes are reminiscent of such. If we are to do this I think we should go back to trek chem nomenclature or just make entirely different names for them.

**Comment by ATH1909** [comment]
On the one hand, this is kind of cool, on the other hand, I feel like this would take us down the path of goon (and give an unfair advantage to players who can play on both weekdays and weekends, as they can learn the recipes during the weekdays and then use them during the weekends before other people can find the ruin).

Also, expect the knowledgebase discord server to make a channel or something dedicated to posting whatever the current versions of these semi-persistent chem recipes are.

**Comment by ExcessiveUseOfCobblestone** [comment]
As opposed to features like toxins where once you know the optimal mix you can reliably make it round after round after round after... like people did when it could carry techwebs?

**Comment by Razharas** [comment]
Good feature but chemistry could use a much more useful work, namely a complete rewrite of all the chem handling systems

**Comment by HomocidlePancakes** [comment]
>and give an unfair advantage to players who can play on both weekdays and weekends

How is it unfair that the people who invest in to the game more gain an advantage over those who don’t? What you are saying is pretty much socialism

>Also, expect the knowledgebase discord server to make a channel or something dedicated to posting whatever the current versions of these semi-persistent chem recipes are.

Yeah, it’s a problem that makes these random chems pretty much useless. Goon managed to combat this by developing a culture where things like these are looked down on to. TG players will never have anything even close to some sort of self-restraint to develop something like that as our current rules can be summed up as “yeah go griff whatever and however you want as long as you don’t kill people”.

**Comment by Tlaltecuhtli** [comment]
reset it every round to prevent meta, maybe just roll on initialize

**Comment by HomocidlePancakes** [comment]
>reset every round
This will just make it another spaceloot item

**Comment by AnturK** [comment]
Just so we're clear my intention with this is not any basic recipe replacement. It would need a lot more to work reliably as that.

The recipe reset is on per-recipe basis so easier to find/guess recipes can reset every round while others every few days so this can be adjusted if the reaction in question becomes a problem.

**Comment by Qustinnus** [comment]
@HomocidlePancakes 
> How is it unfair that the people who invest in to the game more gain an advantage over those who don’t? What you are saying is pretty much socialism
its a round-based roleplaying game. you shouldn't have omnipotent knowledge in every round you loser.

**Comment by Militaires** [comment]
>its a round-based roleplaying game. you shouldn't have omnipotent knowledge in every round you loser.

bruh.... we are both playing on tg, also: Ahem.... Moodlets.

**Pull request merged**
