### PR TITLE
Fixes the banana honk recipe.

### LINKED ISSUE #26614: "Laughter" reagent combination overlaps "Banana Honk" drink mix recipie
It is impossible to mix the drink "[Banana Honk](https://tgstation13.org/wiki/Guide_to_food_and_drinks#Mixed_Drinks)" because when the components are mixed, it will yield the "[laughter](https://tgstation13.org/wiki/Guide_to_chemistry#Other_Recipes)" reagent instead which isn't in the recipe via combining sugar & banana juice together.

The cream in the mixture for banana honk does not react at all because of the laughter reagent (Banana Honk: Cream, Banana Juice & Sugar) and finish the drink because it does not react with laughter which combines first.

### PR DESCRIPTION
**Pull request by harmonyn**
only the top priority fixes here

laughter + cream, basically the same recipe, just in a way that does not conflict

Fixes https://github.com/tgstation/tgstation/issues/26614.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Its a good thing i even bother playing a bartender right to flag up these things. If people knew that the Banana honk actually heals clowns & monkeys better than banana juice people would use it.

**Comment by octareenroon91** [comment]
I was going to complain about laughter even being brewable, but then I remembered mimanas.

**Comment by FantasticFwoosh** [comment]
Good question, why can't we make "_Nothing_" out of mime toxin? It seems like a obvious production issue since its exclusively from mimes right now but parallel clowns can make their own unique mixture.

**Comment by octareenroon91** [comment]
The mimana gets 10% nothing, 10% mutetoxin, 2% nutriment.

**Pull request merged**
