### PR TITLE
fixed delta's n2o console and adds fireaxe to atmos

### LINKED ISSUE #30013: delta atmospherics has n2o atmos monitoring console named as co2 atmos monitoring console

### PR DESCRIPTION
**Pull request by BeeSting12**
fixes #30013
also adds a fireaxe cabinet, delta's the only map which atmos doesn't have a fireaxe
🆑 BeeSting12
fix: Deltastation's N2O console has been renamed to be an N2O console.
tweak: Deltastation's atmos now has a fire axe.
/🆑

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by PraiseRatvar** [comment]
also can you check for this weird machine frame near the actual co2 console, i think it's supposed to be something (or just not there)



@BeeSting12

**Comment by BeeSting12** [comment]
It looks like that's supposed to be a freezer or heater. At what point in the round was it broken?

**Comment by PraiseRatvar** [comment]
@BeeSting12 p sure from the start (roundid - 74901)

**Comment by BeeSting12** [comment]
Looks like it's definitely in the spot that the heater would be but it also looks like the pipes around it are editted from roundstart condition. Everything looks like it should work right from the map editor but I'll test locally to be sure

**Comment by PraiseRatvar** [comment]
add more hardsuits and an actual airlock for atmos tech to leave into spess

**Comment by BeeSting12** [comment]
for balance reasons atmos only has one fireproof hardsuit

**Pull request merged**
