### PR TITLE
Haha, no. Adjusts the AI's laws when it is a traitor.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: Malfunctioning AIs have had their zeroth law changed.
/:cl:

holy shit last round the AI went "lol im a traitor"

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Thanks

**Comment by Shapsy** [comment]
Limiting an AI from pulling a malevolent dictator Friend Computer shtick and saying "I can kill you at any time I want so let's be friends" is the stupidest shit, let them play how they want

**Comment by optimumtact** [comment]
To the best of your abilities leaves too much room for interpretation anyway.

Welcome to law school kids

**Comment by GunHog** [comment]
This cannot actually be enforced, Goof. Not that I am saying it should be. It runs counter to the 'solo antags can do what they want' playstyle.

**Comment by KorPhaeron** [comment]
muh freedoms

**Pull request closed without merging**
