### PR TITLE
Dummies no longer queue, which humans probably shouldn't do ever

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by optimumtact** [comment]
Test merge this and see if the runtimes go away

**Comment by Cyberboss** [comment]
```
9:21:15 AM %Cyberboss,.8b rewrite mobcode 
9:21:15 AM * beerobot shakes the magic 8 ball... One would be wise to think so 
```

**Comment by DoctoreMad** [comment]
Wait wasn't a earlier PR made EXPLICITLY to queue dummies when they're DEL'd?

**Comment by Cyberboss** [comment]
You act like we understand the consequences of our actions

**Comment by DoctoreMad** [comment]
Ah well
Bust out shrugs.jpg

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
