### PR TITLE
Department Night Vision Goggle Resprites

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR resprites the current suite of Med, Sec and Diagnostic NVG's. I felt the current sprites were mediocre, especially as they all used the same sprite. These new sprites should be more obvious and cooler, I hope. 

nvg

:cl: Steelpoint
imageadd: New sprites for the Security, Medical and Diagnostic Night Vision Goggles.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
> I felt the current sprites were mediocre, especially as they all used the same sprite. 

These use the same sprite, just recolored! That being said, they do look a lot better, and there is actually a difference for the on-mob sprites now, so it is indeed an improvement.

**Comment by nicbn** [comment]
You should use grey scale for that

**Comment by Barhandar** [comment]
They're _way_ less cool. Please change NVG sprite instead of changing _every other one_.

**Comment by adamkad1** [comment]
actually i think its better than previous ones, now its actually nvgs instead of 'departament huds but in green'. Also NVG's on one eye is just stupid, how does that work, how do you not go blind from that

**Comment by Barhandar** [comment]
I suggest you get inspired by nightvision mesons instead of le sam fisher meme that is plan NVGs.

@adamkad1 same way you somehow manage to use HUD with one eye.

**Comment by ExcessiveUseOfCobblestone** [comment]
definitely prefer these, but consider using greyscale

**Comment by Steelpoint** [comment]
I'd rather keep the Meson NVG's unique since they perform a different function.

I do admit the MOB sprites are a bit goofy looking, I could take a gander at making a change but I can't promise anything.

**Comment by adamkad1** [comment]
> I suggest you get inspired by nightvision mesons instead of le sam fisher meme that is plan NVGs.
> 
> @adamkad1 same way you somehow manage to use HUD with one eye.
huds are one eye in a lot of works, because they just add display on one side of your head,  but night vision? that just doesnt work

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
