### PR TITLE
Clockcult scripture tiers can no longer be lost by dipping below their requirements once they are unlocked

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
balance: Clockcult scripture tiers can no longer be lost by dipping below their requirements once they are unlocked.
/:cl:

I was going to do a complete overhaul of clockcult but it was pointed out that it's easier to do smaller chunks and see what each chunk does to the gameplay.

### CODE REVIEW

**Comment by Kromgar** [comment]
Oh for fucks sake god no

**Comment by DoctoreMad** [comment]
>Another clockwork cult buff

Reported

**Comment by ShadowDeath6** [comment]
Constructs don't count toward scripture unlocks, do they?

**Comment by Kromgar** [comment]
Why does clock cult need to be even stronger?  Seriously fucking why

**Comment by ChangelingRain** [comment]
Constructs do not count towards scripture unlocks, no.

**Comment by BeeSting12** [comment]
Clock cult does not need to be stronger

**Comment by MimicFaux** [comment]
The sudden loss of a tier because a base got bombed, or security ambushed a group in maint, or engineers found a tinkerer cache keeps things engaging for both sides of the conflict. A handful of cultists holed up in the AI satellite have no incentive to venture outside their base after a certain point. If the crew can find a crack in the brass armour and take out an auxiliary cluster of caches hidden in maint, or capture a couple cultists after doing hit and runs on the satellite, then that sort of attrition combat should have a meaningful impact for both sides.

**Comment by ChangelingRain** [comment]
Losing things/people should be bad enough on its own without also losing a tier on top of it.

**Comment by Robustin** [comment]
Joan there are so many other ways you can improve the clockcult without doing this. Every complaint about Clock Cult being a nightmare late-game is only going to multiply.

Once you hit applications is over if there's a single player who knows what they're doing. Slabs get more productive with less cultists and a couple daemons on a solar panel and I can spam anima fragments until the end of time.

**Comment by Kraseo** [comment]
this is way too big a buff

**Comment by meeeeme** [comment]
How about no

**Comment by ChangelingRain** [comment]
A cult that's actually winning is unlikely to benefit from this; it's purely a buff for cults that experience a setback.
Spamming anima fragments forever might let you kill the station, but it probably won't result in you winning, since you need 12 humans or silicons for that.

**Comment by Kromgar** [comment]
I knew joan wanted to make cucks unstoppable but to be so open about it

**Comment by Robustin** [comment]
Once a CC hits application tier I think its time for the round to go one way or another. My biggest concern with both cults is recovering from early setbacks. Cults DO need a mechanism to recover when one retard is caught muttering in cult chat in middle of the hall 30 seconds into the round, they don't need a mechanism so that when (after your revenant PR is done) they're literally just shy of the final tier they have a safety mechanism to ensure they never lose strength. 

Applications is where all the crazy CC shit kicks in and if the crew manages to push them out of the applications stage they shouldn't have to worry about one cultist staging a comeback with 10 anima fragments.

**Comment by ChangelingRain** [comment]
Perhaps I'll make anima fragments need two invokers or something.
I might even remove them, though that'd leave us with only scarabs, borgs, and mechs using soul vessels.

**Comment by Kromgar** [comment]
@ChangelingRain no one used anima fragments anyway why mae those when you can make superior cyborgs

**Pull request merged**
