### PR TITLE
Autosurgeons/autoimplanters are used by attacking yourself, not using in hand.

### PR DESCRIPTION
**Pull request by harmonyn**
:cl: bandit
tweak: Auto-implanters are now used by attacking yourself. There is a short cooldown.
/:cl:

Because using it in hand is a very unintuitive mechanic, inconsistent with almost every other device of this type. Also added a short cooldown.

I want to suppress the hit animation because it looks bad, but don't know how

### CODE REVIEW

**Comment by MrPerson** [comment]
Implants in your mouth, not in your hand

**Comment by optimumtact** [comment]
why not both

**Comment by bgobandit** [comment]
>why not both

Because using it in hand is a very unintuitive mechanic, inconsistent with almost every other device of this type. you don't use pills or patches or implanters etc in hand

**Comment by optimumtact** [comment]
Yes but if you allow both then it's intuitive for new users and disrupts old users less

**Comment by bgobandit** [comment]
it's arguably less intuitive for new users because they get used to in-hand working on some items but not others, as for old users, there is a changelog

**Comment by optimumtact** [comment]
how is doing both less intuitive for new users, they can use whichever way immediately comes to mind?

**Comment by bgobandit** [comment]
because they learn "oh, I can use this surgery thing by clicking it in hand, I guess this means surgery stuff is used by clicking it in hand"

then they try to click a pill or a patch or whatever in hand, and die

**Comment by Cyberboss** [comment]
The key thing here is these are **auto** machines. Turing them on and having them go tentacle porn on you is part of the lore

**Comment by Chronitonity** [comment]
yeah it should probably just use both, no real reason not to

**Comment by bgobandit** [comment]
I don't feel like arguing this

**Pull request closed without merging**
