### PR TITLE
[Ready] Adds Snow Cones

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Shh dont worry about the webedits. Its for a frozen wounder. 
Solving station hunger one pr at a time. So what if its just water.

## About The Pull Request

Hello its I your non-local cat, I seen no one ever made snow cones to be the in game!
Dont worry, I got you. Sprites and such are hard! So I shall make the best frozen wounder known to the carnival ever, the snow cone!

Adds in a new crafting slot thing. Frozen this is to house snow cones and other snow/cold items. To help remove the MISC food bloat...

Adds in snowcones to be crafted out of basic silly cones, ice and juice or soda.

## Changelog
:cl:
add: snowcones
imageadd: snowiest of snow cones
/:cl:

### CODE REVIEW

**Comment by Twaticus** [comment]
image

**Comment by Qustinnus** [comment]
why dont u make it greyscale and color it based on reagent color

**Comment by Ordonis** [comment]
Unstable mutagen Snowcone
ClF3 Snowcone
Lexorin Snowcone

Let these be so.

**Comment by Trilbyspaceclone** [comment]
@Qustinnus Gray scales would be rather bad for this. For note, if you use lets say water, + a gray scale it looks rather bad, and do to mixing and how colors works it can lead to snow cones looking rather bad/goofy - Such as a solid white or solid black, it was more fun/easier for me to simply make snow cones sprites that look more alive then a dull sorta copy cat, beaker.

**Comment by PKPenguin321** [comment]
You can make the code that applies color only accept colors within a hardcoded range to prevent full black or full white. It is preferable that way

**Comment by Qustinnus** [comment]
reagents are already greyscaled how is this any different

**Comment by Krysonism** [comment]
https://github.com/tgstation/tgstation/pull/44939

Here is how I did reagent ice-cream if you opt to go that route. It looks bad with white reagents primarily. Sadly meth ice cream is affected by this. Maybe swapping the base sprite when the overlay is too light would solve this.

**Comment by Trilbyspaceclone** [comment]
I just dont see a reason to make the snow cones change colors, if they did it wouldn't look as well as they do. Unless their is a issue with the code as it is, I dont see a reason to change it.
Krysonism ill keep that in mind for later PRs thank you!

**Comment by actioninja** [comment]
stop bikeshedding

**Pull request merged**
