### PR TITLE
[ON HOLD] Revert "Tank suicide no longer gibs w/o enough pressure"

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/tgstation#26597

Literally the worst change in the history of changes

where's the fun in hopline suicide if I have to go to atmos to fill up my oxytank ;(

### CODE REVIEW

**Comment by Armhulen** [comment]
first shadowlings than this

you're on a FUCKING ROLL YES

**Comment by optimumtact** [comment]
freeze

**Comment by MoreRobustThanYou** [comment]
@Armhulen shadowlings may be delayed because people hate sleep()

**Comment by MoreRobustThanYou** [comment]
so what, that's 5 PRs to be reopened at 12:01 AM on the 15th?

**Comment by Armhulen** [comment]
wew

**Comment by Xhuis** [comment]
⚠️ WOAH THERE PARTNER ⚠️ 
THAT THERE PR OF YOURS VIOLATES OUR ❄️ FEATURE FREEZE ❄️ 
CLOSE 🚪 THIS PR BEFORE I CLOSE 🔫 👨 YOUR LIFE

**Comment by MoreRobustThanYou** [comment]
lemme list em

* Shadowlings
* spacepods
* changeling overhaul
* adding chambelts to chamkits
* headpats

**Comment by Armhulen** [comment]
>changeling overhaul

HOOOOOOOOOOOOOOOOOOOLY SHIT YOU'RE GOOD.
also prepare to revert some conversion modes morerobust because slings won't get in without a cult dying

**Comment by MoreRobustThanYou** [comment]
@Armhulen see #28832

**Comment by jughu** [comment]
>have to go atmos to fill your tank or just use those certain emergency rooms with the green stripe and an air tank to fill it up!

**Pull request closed without merging**
