### PR TITLE
Adds departmental PDA painters to all command offices

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Adds respective departmental PDA painters/ID trimmers to all head of staff offices.

I also removed the BEPIS from RD's office on Kilostation to fit it in, there's already a BEPIS in Cargo and Science isn't supposed to have one, so I assume it was fine to do.

## Why It's Good For The Game

They have an app to edit access, and in the past were able to change jobs, they should still be able to.
It's a cool feature that I love taking advantage of as HoP, to tell people trying to job change to a department to go through that department's head of staff rather than through myself, and gives something more for Command players to do, since HoP already has a ton.

## Changelog

:cl:
qol: Departmental ID trimmer/PDA painters have been added to head of staff offices, making it way easier to job change someone into your department.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
mapping conflicts fucked up

**Comment by unit0016** [comment]
Run mapmerge2, it'll save your life, promise.

**Comment by JohnFulpWillard** [comment]
I don't know why there's so many lines changed, but apparently mapdiffbot says nothing else was changed so I'm hoping it didn't break shit.

**Comment by JohnFulpWillard** [comment]
Who the FUCK keeps touching maps

**Comment by san7890** [comment]
> I don't know why there's so many lines changed, but apparently mapdiffbot says nothing else was changed so I'm hoping it didn't break shit.

It's just that you had to rekey stuff, if you weren't already aware.

**Review by san7890 — CHANGES_REQUESTED** [review]
Few minor things.

image

For the CMO on DeltaStation, it doesn't make sense to have the PDA painter to be in the bedroom. They have two health laptops, so you could try shuffling around the glass tables a bit to accommodate maybe? I gave you a suggestion on the Discord if you wanna view that.

image

For the CE on IceBoxStation, I think it would look better to have it be a caution-line corner to cover the spot already present as well as that part I crossed out. It provides a much needed transition from the textured turf onto the rest of the office's tiles.

Otherwise, everything appears to be in fine condition. Ping me on Discord (you know who I am) when ready, or just reply here.

**Comment by san7890** [comment]
(john willard just found out about map merge how splendid)

**Review by san7890 — APPROVED** [review]
You didn't do it exactly like I told you to do it, but that's alright.

**Pull request merged**
