### PR TITLE
Adds a second functionality to the emagged defibrillator

### PR DESCRIPTION
**Pull request by ghost**
https://www.youtube.com/watch?v=N7yfLwMds5c

The old emagged functionality of stunning has been moved to disarm intent. Harm intent will now cause a large amount of damage after a short time in addition to stopping the patient's heart. This takes about eleven seconds and provides a warning before and after that the defibrillator was used for malicious purposes.

Because of the relative rarity of defibrillators, in addition to the long time it takes to hurt someone using them, I feel this is balanced. It is up for discussion.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

**Comment by PKPenguin321** [comment]
How much damage are we talking, here?
Doesn't stopping someone's heart do enough damage over a short amount of time to crit someone alone?
All I can see happening with this is someone stunning then shocking for the ultimate melee combo

**Comment by Iamgoofball** [comment]
Any competent medic can handle the heart attack easily.

**Comment by Iamgoofball** [comment]
Also, if a traitor has someone on the ground long enough to do this to them, then the person is dead anyways

**Comment by PKPenguin321** [comment]
The stun from emagged defibs, last time I used it, didn't require the victim to stand still and is a stupidly long stun
So you can literally walk up to someone with a defib, disarm intent, harm intent, dead

**Comment by Iamgoofball** [comment]
Okay. And I can do the same with a Sleepypen and any medium to high damage weapon in the game for much cheaper, along with being much less obvious. So where's the problem in this?

**Comment by Tokiko1** [comment]
I think the delay is pretty damn long, almost too much to be practical.

**Comment by RandomMarine** [comment]
You need to have the guy restrained or asleep, since it takes longer than most stuns, just to do 50 damage and inflict a damage over time effect on them, and just to add to the impracticality, it's for a bulky item that needs to be worn on your back to use and is only readily available for one department, and even consumes battery that you could be using for stuns.

Meanwhile, any traitor can just buy an esword and dish out 120 damage in four seconds.

**Comment by Xhuis** [comment]
I may lower the delay to normal defibrillator levels. I mainly added this to be more consistent with real life, in which shocking someone who is living with a defibrillator would do tremendous amounts of harm to them and stop their heart.

**Comment by Iamgoofball** [comment]
Reduce the delay and we're golden.

**Comment by Xhuis** [comment]
Travis' fault not mine

**Pull request merged**
