### PR TITLE
[NEW] Scientist's jumpsuit description changed to match the defenses

### PR DESCRIPTION
**Pull request by ma44**

### CODE REVIEW

**Comment by SweaterKittens** [comment]
I almost feel like you should change the description rather than the function, as explosive protection makes way more sense for scientists to have than bio protection.

**Comment by ma44** [comment]
If your dealing with explosives, slap on a bomb suit

**Comment by SweaterKittens** [comment]
Let's be real, 10% bomb protection is pretty useless anyway. I wasn't commenting from a mechanical standpoint as much as pointing out that doesn't really make sense for scientists to have bio protection as much as it would for them to have blast protection.

**Comment by KorPhaeron** [comment]
10% bio does literally nothing, 10% bomb could theoretically save you like 5 health maybe

**Comment by SweaterKittens** [comment]
^ That was sort of my point. They're both negligible, one just is more thematically fitting.

**Comment by GunHog** [comment]
> 10% bio does literally nothing, 10% bomb could theoretically save you like 5 health maybe

You do know that bomb damage is chance based, right? For heavy and light, it is a prob(bomb armor) chance to half the damage taken, and for devastation level explosions, it allows one to avoid being gibbed.

**Comment by RandomMarine** [comment]
Does bio armor even do literally anything in the code yet?

**Comment by Haevacht** [comment]
Lowering damage by 5 could keep you out of crit after exploding. Making this bio is totally irrelevant.

**Comment by Davdichan** [comment]
An explosion is a hazard to you biological health ya derp. /s

Seriously, change the descript, not the resist. Med has bio resist, sci has explosive cause that's the primary job hazard.

**Comment by jughu** [comment]
10% bomb armor is 10% not being gibbed

**Comment by kevinz000** [comment]
screw off with your nerfs pls

**Comment by Arianya** [comment]
Explosions are a hazard to your bio bits. Thats why its a biohazard.

**Comment by SweaterKittens** [comment]
@GunHog Damn, really? Man that makes bomb armor way way better than I thought. I guess that makes this a lot more of a balance change than I had expected. Seems kind of weird that your jumpsuit has a 10% chance to magically soak up the blast from a massive explosion, but I guess that's how it always has worked.

**Comment by ma44** [comment]
@kevinz000 enjoy your 10% resistance to bombs 👍

**Comment by GunHog** [comment]
Thanks Ma

**Comment by Kromgar** [comment]
Did someone brine ma44 with the lemons?

**Comment by ma44** [comment]
No, they didn't slap the lemon with a dosh bill so it's useless

**Comment by Davdichan** [comment]
@ma44 You should really just close this PR and open a new as the scope has changed.

**Pull request merged**
