### PR TITLE
Disallows silicons from using the keycard swipe auth

### PR DESCRIPTION
**Pull request by imedial**
## About The Pull Request
Apparently borgs can use the keycard swipe auth despite not having hands for things such as red alert/bsa controls/etc. This PR removes the ability to do that
## Why It's Good For The Game
I'm under the assumption that this is unintended behavior as they have no hands and technically cannot hold items (I'm assuming that the if(!HAS_TRAIT(user, TRAIT_CAN_HOLD_ITEMS)) check is supposed to catch silicons and prevent them from using it, but if that is not the case and they are in fact supposed to be able to use this machine, maintainers please annihilate me and close this PR
## Changelog
:cl:
fix: Silicons can no longer use keycard auth
/:cl:

### CODE REVIEW

**Comment by ElGitificador** [comment]
borgs have innate all access, it makes sense (to me) they can authorise such thing

**Comment by PeriodicChaos** [comment]
I have seen inconsistencies where borgs are able to login such things but not allowed to be in others, I rather they be allowed to login to an id required interface than just disallowing it. I think borgs can't use the specific announcement computers for medbay, and other departments when they can login to the command computer and do one there.

**Comment by Likteer** [comment]
Stuff's locked behind command IDs for a reason. 
Red alert & BSA protocols.
There's also the shuttle console with early launch authorization, similarly off-limits to borgs.

I agree with the PR.

**Comment by ElGitificador** [comment]
also what xzero said, many times it s very painful to get another player to sync for a double swipe

**Comment by xzero314** [comment]
Strong suspicion that this is just an Ided pr of some sort. Op was probably an antag and Borgs red altered.

**Comment by imedial** [comment]
> Strong suspicion that this is just an Ided pr of some sort. Op was probably an antag and Borgs red altered.

no this is from a downstream where a malf AI built and unlocked a BSA then fired it, I don't personally have issue with it (I thought it was hilarious) but as I said when I looked at the code I assumed that the check specified was supposed to bar borgs from it, and if that's not the case I have no issue with maintainers closing this :P

**Comment by KeRSedChaplain** [comment]
> > Strong suspicion that this is just an Ided pr of some sort. Op was probably an antag and Borgs red altered.
> 
> no this is from a downstream where a malf AI built and unlocked a BSA then fired it, I don't personally have issue with it (I thought it was hilarious) but as I said when I looked at the code I assumed that the check specified was supposed to bar borgs from it, and if that's not the case I have no issue with maintainers closing this :P

this is 100% an ided PR, I was observing this round in particular and there was
A: plenty of buildup when the AI started announcing about it
B: it took 2 hours to even do
C: there was ample warning to leave the area targetted, and only 4 people got qdel'd by the beam.
D: citadel had this balanced by just making all borg IDs count as one ID,globally, so they'd need to partner up with a traitor to do the swipes successfully. TLDR: all silicons required 1 carbon to do the swipes.

**Comment by imedial** [comment]
> > > Strong suspicion that this is just an Ided pr of some sort. Op was probably an antag and Borgs red altered.
> > 
> > 
> > no this is from a downstream where a malf AI built and unlocked a BSA then fired it, I don't personally have issue with it (I thought it was hilarious) but as I said when I looked at the code I assumed that the check specified was supposed to bar borgs from it, and if that's not the case I have no issue with maintainers closing this :P
> 
> this is 100% an ided PR, I was observing this round in particular and there was A: plenty of buildup when the AI started announcing about it B: it took 2 hours to even do C: there was ample warning to leave the area targetted, and only 4 people got qdel'd by the beam.
> 
> Citadel had this balanced by just making all borg IDs count as one ID,globally, so they'd need to partner up with a traitor to do the swipes successfully. TLDR: all silicons required 1 carbon to do the swipes.

First- I'm stupid Idk what ided means
second - I wasn't in the round, I head about it afterwards (I admin there) and I had always thought that borgs couldn't use the keycard auth. Warning or not, this is what I understood to be true (I was wrong) and what I thought the code intended for based on the if(!HAS_TRAIT(user, TRAIT_CAN_HOLD_ITEMS)) line was that they weren't supposed to

**Comment by DATA-xPUNGED** [comment]
I feel like the AI itself should be the only silicon allowed to swipe, it's silly that borgs can do it but the AI, which is psrt of command, can't; Swap it around

**Comment by imedial** [comment]
> Silicons being able to use this is intended and fine, though some of the conversation in here has good ideas for alternate changes. Silicons all sharing one ID for the purpose of dual authorizations and giving the AI itself access are both good ideas.

if that's the case, could reopen it and change issilicon(user) to iscyborg(user) and that would make it AI only

**Comment by ninjanomnom** [comment]
I was saying the ai having access *in addition* is a good idea

**Pull request closed without merging**
