### PR TITLE
Improve performance of creamatorium

### PR DESCRIPTION
**Pull request by SpaceManiac**
Uses the filtering feature of `GetAllContents` instead of a typed foreach

### CODE REVIEW

**Comment by octareenroon91** [comment]
If you're going to call it creamatorium please make `/obj/effect/decal/cleanable/ash/crematorium` spawn with cream added

**Comment by Time-Green** [comment]
a crematorium that turns everything into cream

**Comment by Bawhoppen** [comment]
This was no ordinary misspelling... The creamatorium is actually a subtype of the crematorium which makes ice cream. No joke.

**Comment by Tlaltecuhtli** [comment]
balance tag?

**Comment by octareenroon91** [comment]
@Tlaltecuhtli the PR is just code improvement. Changing the reagents might be a balance or tweak.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
