### PR TITLE
Permabrig Garden Update

### PR DESCRIPTION
**Pull request by JMoldy**
After being put in the permabrig I realized that there was no way at all to grow plants there because the weeds would naturally grow and eat up the fertilizer in the round-start trays, and the ambrosia that used to be considered a weed no longer has the trait, meaning that any seeds planted in the permabrig garden are guaranteed to die before you can get any plants to make fertilizer in the biogenerator.

This simply adds one bottle of E-Z Nutrient fertilizer to each permabrig garden so that gardening is actually possible there.

🆑 J Moldy
Makes it actually possible to garden in the permabrig now.
/🆑

### CODE REVIEW

**Comment by carshalash** [comment]
Nice, now we get prison soup.

**Comment by anconfuzedrock** [comment]
gamer tip: use the tofu as fertilizer

**Comment by actioninja** [comment]
conflict

**Comment by SpaceManiac** [comment]
one week merge conflict

**Pull request closed without merging**
