### PR TITLE
Energy ball can have no more than 25 orbiting balls.

### PR DESCRIPTION
**Pull request by Iamgoofball**
sad day

### CODE REVIEW

**Comment by Bawhoppen** [comment]
make the effects cap but let there visually be unlimited balls still pls

**Comment by Zilenan91** [comment]
Nope. :-1:  :heavy_multiplication_x:  :100:

**Comment by TrustyGun** [comment]
nooooo

**Comment by Iamgoofball** [comment]
@Bawhoppen the visuals are the problem

**Comment by bgobandit** [comment]
fun removal

**Comment by Bawhoppen** [comment]
I thought the teleporting anywhere on the zlevel instadeath no counter death ball was the problem

**Comment by Zilenan91** [comment]
@Bawhoppen It took a 50 minutes round to get it that strong, as well as three PAs at once

**Comment by Bawhoppen** [comment]
they never even got the 3rd PA up though, we got to 105 without the second even

**Comment by Iamgoofball** [comment]
we woulda had the 3rd PA up if I wasn't going back/forth between crit due to getting hit a few times by the second PA

**Comment by Zilenan91** [comment]
Do you really think that we're going to get nearly this many balls in a normal round? The highest I've seen before this is 62 when it was released and it wasn't lagging nearly this bad. It's fine, honestly.

**Comment by WJohn** [comment]
I've seen up to 150 balls in one round, the lag was atrocious.

**Comment by Anonus** [comment]
The problem wasn't the visual orbit, it was the beams. Just have it create a fake energy ball and have that orbit if it goes above 25 or whatever.

**Comment by Incoming5643** [comment]
You don't have to cap the number of balls, orbit is actually proper cheap now, you just need to have the number of beams per ball fall off.

Or do my suggestion and have the little balls fly off through the station ruining people's days when there's too many of them.

**Comment by KazeEspada** [comment]
At 26, make it break itself free.

**Comment by Zilenan91** [comment]
Or keep it as it is and make it break free at 60 so that it stops getting fed a retarded amount of radiation via the PAs

**Comment by KazeEspada** [comment]
Actually I was thinking.

First, why are the rotating balls doing anything at all? It would be easier just to make the center ball do everything.

Combine beams into stronger beams, so if 30 would produce 30 beams, what if 30 instead produced 6 stronger beams.

If one of the produced beams are too strong, it could blow an emitter or a shield generator.

The orbiting balls are just for a visual indicator of the teslas strength.

**Comment by Iamgoofball** [comment]
Okay, so here's why I'm capping balls since people didn't figure it out:

Each ball handles it's own beam zap. So, more balls = more beams

Beams are the problem here, and we've tried fixing the beams themselves but just doing that isn't good enough, so it needs combined with a cap.

**Comment by RemieRichards** [comment]
@Iamgoofball you failed to pool all the types properly, tkdrg is already working on something for beams

**Comment by Iamgoofball** [comment]
ohh, so that was my problem?

well shit let's see how that works out

**Comment by KazeEspada** [comment]
Goofball, it would produce less lag if one ONE ball was producing beams.

**Comment by Shadowlight213** [comment]
Have the effects continue to rise. Have the number of balls have a cap and upon reaching it it turns the balls a different color rather than adding a new ball.

**Comment by Fox-McCloud** [comment]
:+1:  To this.

Tesla_act() literally goes INSANE on the profiler when you have a lot of energy balls.

Frankly, 25 is still too high---15 would probably be better.

**Comment by tkdrg** [comment]
Nobody posted this here yet but I didn't manage to get a faster Beam() implementation to work out.

@Fox-McCloud tesla_zap() isn't that big of a deal, it's slowish but it's not a bottleneck. The biggest issue is the gigantic amount of Del()s from the beam effect. For comparison, the average cost of a properly GC'd deletion (which is the case for /obj/effect/ebeam) is 0.001 second aka 1ms which is gigantic. The average cost for tesla_zap is 0.00001 second aka 0.01 ms which is two orders of magnitude better than Del(). We could literally have 700 tesla_zap()s in the time it takes for a 7-tile ebeam to delete. Pooling reduces this but it's still too slow in my testing.

**Comment by Fox-McCloud** [comment]
@tkdrg 

Would you be willing to provide some profiling of beams, both with and without pooling?

I've profiled pooling before, but that was prior to the resetvars fixup, and it always lost to straight up GCing.

**Comment by tkdrg** [comment]
With pooling:
https://files.singulo.io/P4u7.txt
https://files.singulo.io/K2zj.txt
Without pooling: 
https://files.singulo.io/qait.txt
https://files.singulo.io/dLQf.txt
https://files.singulo.io/pkkg.txt
https://files.singulo.io/hKkC.txt (this one is just the lag peak)

**Comment by Fox-McCloud** [comment]
/proc/tesla_zap is 1/5 of the cost, but here's my concern:

- Adjust for total calls, it would seem you save ~43 Total CPU on tesla_zap
- Most of the savings seem to be in Del(); with a rough adjust savings of ~241 CPU
- PlaceInPool has a total CPU of over 200

This would be a bit easier to compare if the amount of tesla_act's were roughly the same; it's also difficult to get a true gauge on the overhead of qdel() as well; I believe that @MrStonedOne said that if you have a specific Del() for whatever you're profiling and just have it call parent, that it can show the true overhead of qdel.

Just trying to be sure that pooling really does incur a savings over qdel, now, because, well--before it didn't, and actually incurred *quite* a loss.

**Comment by tkdrg** [comment]
Well yeah, it does look like pooling saves on deletions, but spends more on creation. I dunno, it's hard to get a feel for it with real world data, a controlled test would be more accurate.

**Comment by Fox-McCloud** [comment]
@tkdrg 

Yep--that's the problem I had before, but before the resetvars() optimization, it made pooling a clear loser in 99% of cases.

Just want to be sure that *this time* it really is a good thing and worth implementing...or if it should just be wholesale ripped out as it always (or nearly always) incurs a loss, overall.

**Comment by Fox-McCloud** [comment]
Tested this out locally--I pooled the ebeam effect, and it had a significant performance loss---though I may have done it improperly...

**Pull request closed without merging**
