### PR TITLE
Drunk musicians

### PR DESCRIPTION
**Pull request by defrost256**
Musicians ability to play a song the "intended" way is impaired by the amount of alcohol consumed

:cl: Drunk Musicians
add: Drunk music
/:cl:

Because it's terribly boring to listen to the same songs over and over again

### CODE REVIEW

**Comment by xxalpha** [comment]
This is pretty neat, if only we could fix the playing lag.

**Comment by dannno** [comment]
ahahaaaaa that's hilarious

**Comment by MrPerson** [comment]
Stacking probs like this leads to a lack of clarity on the odds of anything in particular happening. Are they really all necessary?

**Comment by defrost256** [comment]
If it's only the clarity of odds, I don't think in this particular case it's an issue, since it only adds cosmetic value, and the odds can be tweaked "less this more that" style (though the way I originally wanted to do it was with a const list and pick() which would be a bit more clear (if dm even has const if not just a regular list))

**Pull request merged**
