### PR TITLE
make the safe use balloon alerts

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
makes the safe use balloon alerts to give you hints
https://gyazo.com/7c87998ff82cebcf617bf11f2c864b03

## Why It's Good For The Game
less chat clutter and maybe even make it more difficult without the chat log.

## Changelog

:cl:
qol: safes now use balloon alerts for the hint
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
Again, not too sure about the CL tags, so notify me if they are wrong.

**Comment by Mothblocks** [comment]
i fixed it

only player facing changes are in changelog, and your thing is qol

**Comment by jjpark-kb** [comment]
> i fixed it
> 
> only player facing changes are in changelog, and your thing is qol

wonderful, thank you!

**Comment by Mothblocks** [comment]
btw you didn't need to change `i`, if they're unused they should just be `_` anyway

**Pull request merged**
