### PR TITLE
Faking your death is more complete

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Faked deaths are now effectively indistinguishable from real deaths.
/:cl:

Includes medihud replacement, prevents shaking/CPR, and prevents all emotes, including deathgasping.

### CODE REVIEW

**Comment by XDTM** [comment]
Also when you try to help intent touch someone on fakedeath i think you try to shake them up instead of saying "[name] is dead!"

**Comment by ChangelingRain** [comment]
Fixed it.

**Comment by Zilenan91** [comment]
zombie powder faked death?

**Comment by ChangelingRain** [comment]
Yes, it'll include that. I'm calling that a feature because it's for faking your death, jeez.

**Comment by Zilenan91** [comment]
What kind of fake deaths are we talking about if it's not zombie powder?

**Comment by XDTM** [comment]
Changeling regeneration

**Pull request merged**
