### PR TITLE
Makes Pubby captain's office more spacious

### PR DESCRIPTION
**Pull request by Thunder12345**
:cl: Thunder12345
tweak: Pubby Station: Removed a double thickness reinforced wall to make the captain's office a little more spacious.
/:cl:

### CODE REVIEW

**Comment by Thunder12345** [comment]
\>Map conflicts
_skreeeeee_

**Comment by PKPenguin321** [comment]
wheres mapchange bot

**Comment by deranging** [comment]
ass

**Comment by nicbn** [comment]
spawn dat dif boy

**Comment by Thunder12345** [comment]
No diff because it's got conflicts, I'll g

**Pull request closed without merging**
