### PR TITLE
Reduces tool speed

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Faster-than-normal tools are somewhat slower than before.
/:cl:

Specifically;
Standard tools; 1 ➡️ 1
Cyborg tools, large crowbar, experimental welder, brass tools; 0.5 ➡️ 0.7
Nuke screwdriver; 0.5 ➡️ 0.5
CE's fancy double tools; 0.25 ➡️ 0.4

Level "one" tools literally halving speed is silly as heck.
Construction times might be too long right now, but super fast tools is probably not the solution.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:
# change for the sake of change stop

**Comment by KorPhaeron** [comment]
Why?

**Comment by Iamgoofball** [comment]
just gonna leave this here
chrome_2016-12-11_14-44-26

**Comment by TechnoAlchemisto** [comment]
Not everyone should be fast at construction, but people who have good tools should be good at it. Bad change.

**Comment by Firecage** [comment]
Joan, personally I must say I dislike this. The nice things about these tools, especially the hand drill and jaws of life, is that they make construction and deconstruction bearable, considering that some time ago building stuff was made so agonizingly slow. I would actually prefer it if the tools kept their current speeds(2x faster for borg tools and 4x faster for ultra tools like the hand drill)

**Comment by CPTANT** [comment]
Ohw while we are on the topic.

Bring back RPD instantly laying disposal pipes. The delay was added because you could spam disposal bins as obstacles, but since thats impossible now the delay should be removed again.

**Review by Razharas — APPROVED** [review]
I approve

**Comment by KorPhaeron** [comment]
@Razharas 

Why?

**Comment by ChangelingRain** [comment]
this is mildly amusing honestly now to never actually do the second pr and leave everything in slow tool hell

**Pull request merged**
