### PR TITLE
Convert PDAs to GAGS

### PR DESCRIPTION
**Pull request by celotajstg**
## About The Pull Request

Converts PDAs to GAGS. The PDAs look pretty much the same as they currently do.

before:
image
after (except the clown PDA is as it was):
image

## Why It's Good For The Game

Less space taken by the source icon file, better recolors.

## Changelog
:cl: Celotajs
imageadd: PDA icons are now generated with GAGS
/:cl:

### CODE REVIEW

**Review by Twaticus — APPROVED** [review]

**Comment by CPTANT** [comment]
Seems like a good change. Just curious, what made decide to do this refactoring?

**Comment by celotajstg** [comment]
> Seems like a good change. Just curious, what made decide to do this refactoring?

The PDAs just seemed like a perfect fit for having generated sprites, so I figured I might as well make that quick change

**Comment by bluetshirtguy** [comment]
I think pda's are a terrible fit for them looking all the same, since they're universal it become a excellent target for customized pdas and stylized design.

**Comment by YakumoChen** [comment]
clown PDA is no longer a garish pink color, :-1: fix it

**Comment by maxymax13** [comment]
clown pda soulless

**Comment by celotajstg** [comment]
discussed this; good to merge

**Comment by MrStonedOne** [comment]
I think you can try harder on the clown pda.

**Comment by celotajstg** [comment]
Ok, I left the clown PDA as it was, but the rest is GAGS'd

**Comment by Twaticus** [comment]
smh

**Comment by celotajstg** [comment]
> smh

do I return it to being GAGS-ified then? your call

**Comment by Twaticus** [comment]
nah no worries this is fine

**Comment by LemonInTheDark** [comment]
> 
> 
> I think you can try harder on the clown pda.

the host exerting authority over the codebase smh disgusting

**Pull request merged**
