### PR TITLE
Updates the nav beacon sprite

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Tin
navbeacon-expor1111t
navbeacon-111111

Doesn't touch the transparent sprites as #74575 is getting rid of the need for those.
## Why It's Good For The Game
navbeaconaaaaAAAAAAA
image
## Changelog
:cl: Wallem
imageadd: Updates navbeacon sprite
/:cl:

### CODE REVIEW

**Comment by Profakos** [comment]
Good and powerful.

**Comment by optimumtact** [comment]
removes soul

**Comment by Wallemations** [comment]
> removes soul

All in a day's work

**Review by Imaginos16 — APPROVED** [review]
nice work

**Pull request merged**
