### PR TITLE
Makes it so coroner is only listed in medical department instead of both service and medical

### LINKED ISSUE #75261: coroner is in the latejoin menu twice
Reporting client version: 514.1589

## Round ID:
[205304](https://scrubby.melonmesa.com/round/205304)

## Testmerges:
- [JSON Logging Take Two](https://www.github.com/tgstation/tgstation/pull/73604)
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)

## Reproduction:
image
this is inconsistent with lawyer and psychologist, other service jobs with a nominal to another department.

### PR DESCRIPTION
**Pull request by E231kei500bandai**
## About The Pull Request

Fixes #75261

Removes coroner from being under service in the crew manifest and latejoin menu
<details>
  <summary>Unnecessary Images</summary>

image
image
</details>

I believe it would also make it so getting banned from Service jobs wouldn't ban you from coroner. (Don't know if that ban type would ever be used) 
## Why It's Good For The Game

More in line with jobs like Psychologist and Lawyer which are only listed in a single department. (The service department)
Otherwise it mostly depends on JohnFulpWillard, since idk if they intended for it to be listed under medical or service. I just assumed medical made more sense for the Coroner. 
## Changelog
:cl:
fix: For the purposes of the crew manifest, Coroner is now considered a medical job rather than both service and medical. 
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
this also makes them pay for Service lathe tax and make them not get service deathrattle, which should not be the case because they are a service job as well.

**Comment by Helg2** [comment]
> this also makes them pay for Service lathe tax and make them not get service deathrattle, which should not be the case because they are a service job as well.

Can't it be done with a better way?

**Comment by BlueMemesauce** [comment]
> this also makes them pay for Service lathe tax and make them not get service deathrattle, which should not be the case because they are a service job as well.

Then this would be an issue with psychologist too right?

**Comment by JohnFulpWillard** [comment]
Psychologist is taxed for using the Medical lathe, as a Service-ONLY job it makes sense.

Coroner is both Medical and Service, they shouldn't be taxed for either

image

**Comment by JohnFulpWillard** [comment]
The optimal way to fix this I think would be by making the latejoin menu work similar to the roundstart one, it should be taking ``department_for_prefs`` into account

**Comment by BlueMemesauce** [comment]
Okay

**Comment by BlueMemesauce** [comment]
Maybe it would be leas confusing to just use departments_list[1]? This is how its done for nations

**Comment by BlueMemesauce** [comment]
It could go either way for now but I think this way makes more sense. And if another job was added to be in more than 1 department without a department_for_prefs set, it would have this problem again and display in both departments

**Pull request merged**
