### PR TITLE
Suplex The Rod

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
add: RDs can now attempt to recreate last year's Feats of Strength challenge.
/:cl:

If you can somehow pull this off I congratulate you.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
make it poop out an anomaly core when you do this too so theres incentive for RDs to get themselves killed

**Review by SpaceManiac — CHANGES_REQUESTED** [review]

**Comment by evsey9** [comment]
make the rod become a crafting element for  a single-use immovable rod launcher

**Comment by Time-Green** [comment]
yogs did it first
https://github.com/yogstation13/yogstation/pull/2727

**Comment by Barhandar** [comment]
More Enzo memes are always welcome.

**Comment by ExcessiveUseOfCobblestone** [comment]
ADD A MEDAL FOR IT

**Comment by MMMiracles** [comment]
that's the idea just trying to get ahold of someone with hub access to do it

**Comment by PKPenguin321** [comment]
i did something similar in https://github.com/tgstation/tgstation/pull/19764

idk if he's still the boss of the hub page but @Shadowlight213

**Comment by Kagus** [comment]
Can this be done to rodform wizards? If so... What even happens?

**Comment by MMMiracles** [comment]
wizard gets ejected if the rod is destroyed, so he'll just fall out like he would normally if the spell ended.

i probably should add something for that

**Comment by evsey9** [comment]
make the wizard get gibbed instantly because the rod impales the wizard after wizard un-rods

**Comment by MrStonedOne** [comment]
I have hub access, pm me on discord.

**Comment by MMMiracles** [comment]
image
It's officially a medal now thanks to MrStonedOne, which means this PR is ready for review.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
