### PR TITLE
Fix: #67960 Mech tgui does not let you drop some crates from cargo compartment

### PR DESCRIPTION
**Pull request by raffclar**
## About The Pull Request

An attempt at fixing #67960.
This prevents the `UtilityModulesPane` from overflowing. The `LabeledList` uses table for layout which is not ideal so it may be worth looking into changing  `LabeledList`.

## Why It's Good For The Game

Before:
image
image

Now:
image
image

The buttons are now usable again.

## Changelog

:cl:
fix: Fixed mecha cargo names breaking the utility module interface
/:cl:

### CODE REVIEW

**Comment by raffclar** [comment]
The horizontal bar sadly can't be removed without a class override. If you remove ` width: calc(100% + 1em);` from `.LabeledList` css class then the horizontal bar disappears.

**Comment by zxaber** [comment]
What if you put the button on the left side of the text?
Perhaps replace the button's own text with a font-awesome icon to make it smaller too.

**Comment by zxaber** [comment]
> The horizontal bar sadly can't be removed without a class override. If you remove ` width: calc(100% + 1em);` from `.LabeledList` css class then the horizontal bar disappears.

You can set a max length for text by replacing `{var}` with `{var.slice(0, X)}`, where `X` is your max number of characters. I did that for the borg self app to fix this exact same issue. If you do that, you could give the list item a tooltip to display the full name on mouse hover.

**Comment by raffclar** [comment]
> > The horizontal bar sadly can't be removed without a class override. If you remove ` width: calc(100% + 1em);` from `.LabeledList` css class then the horizontal bar disappears.
> 
> You can set a max length for text by replacing `{var}` with `{var.slice(0, X)}`, where `X` is your max number of characters. I did that for the borg self app to fix this exact same issue. If you do that, you could give the list item a tooltip to display the full name on mouse hover.

I added tooltips. Not a massive fan of using JS here.

**Comment by raffclar** [comment]
> What if you put the button on the left side of the text? Perhaps replace the button's own text with a font-awesome icon to make it smaller too.
> 
> Renaming the Cargo Compartment equipment to just "Cargo" or "Hold" would also free some space. That item doesn't exist outside of a mech, so it probably wouldn't be a big deal to cut the name down.

These are good ideas. I'll try them.

**Comment by raffclar** [comment]
Different states and showing responsive design to changing width and height:
image
image
image
image
image

**Review by stylemistake — APPROVED** [review]

**Pull request merged**
