### PR TITLE
Blorble

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Coiax was correct that slime telepathy makes little sense considering they suffer all other speech constraints, they just picked the wrong replacement verb

### CODE REVIEW

**Comment by coiax** [comment]
There are some other "telepathically" verbs in the same file.

**Review by Cyberboss — APPROVED** [review]
Disagree with the change though

**Comment by RemieRichards** [comment]
as the person who made slimes speak baby-talk, blorble is better.

**Review by Cyberboss — APPROVED** [review]

**Review by coiax — APPROVED** [review]
I also wanted to participate in pointless reviews for minor changes.

**Comment by Aloraydrel** [comment]
Now for smug slime faces

**Comment by ExcessiveUseOfCobblestone** [comment]
I think I need to unironically add slimes to the emoji list...

**Pull request merged**
