### PR TITLE
Revert "Revert "Automatic unbuckle by player moving""

### PR DESCRIPTION
**Pull request by nicbn**
Buckle tatics are bullshit and also the only reason this revert happened.

This is open for discussion, so no speed merge pls.

Reverts #30281.

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
6:02:24 PM Frozenguy5 let's not have another fucking revert war 
6:02:29 PM Frozenguy5 bees were enough

**Comment by ike709** [comment]
See: https://github.com/tgstation/tgstation/pull/30233

**Comment by Cyberboss** [comment]
Listen to me... closely...

No.

**Comment by nicbn** [comment]
Thou are so anti fun

**Comment by nicbn** [comment]
Tyranboss

**Pull request closed without merging**
