### PR TITLE
Ports Tiki mask from Hippie and adds the alt version of the wooden chair to the crafting menu.

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
tweak: The wooden chair with wings is now craft-able. -1 non reconstruct-able map object
add: Added the Tiki mask, you can make it in wood's crafting menu.
imageadd: Ported Tiki mask's sprites from Hippie station.  It is under the same Creative Commons 3.0 BY-SA as the rest of our sprites.  They are from Nienhaus.
/:cl:

For the mask the reason is UNGA-BUNGA.  For the chairs I just hate map objects that players can't fix.

masks
onmob for ants

### CODE REVIEW

**Comment by dannno** [comment]
pics

**Comment by ExcessiveUseOfCobblestone** [comment]
>pics

**Comment by Chronitonity** [comment]
Nienhaus actually sprited these for me and deserves the credit, I appreciate the shoutout though.

**Comment by Supermichael777** [comment]
Thanks

**Pull request merged**
