### PR TITLE
[READY] New Cargo Fixes (#50523)

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

Fix for #50523 

Namely:
Miner maint doors have gone from two to one.
Mining has gotten one tile smaller and more tables have been added.
The Maintenance Stump has been removed.
The APCs have been fixed.
A decal issue with the cargo bay floor has been handled.
There is now a set of windows/windoor from the trash conveyor into the deliveries room.
Conveyor levers for the main shuttle have been re-added
Bad power cables have been removed.
Lights have been removed from windows and placed on walls.
The ORMs I/O has been fixed.

On a side note, plastic flaps seem not to work from the top down. I have opened an issue #50605 and hopefully someone who looks at this can make a quick fix for that.

## Why It's Good For The Game

Fixes problems with the recent PR.

## Changelog
:cl:
fix: Fixed several issues with the new cargo layout.
/:cl:

### CODE REVIEW

**Comment by Cartographer-D** [comment]
Poor Travis

**Comment by Rohesie** [comment]
Poke in discord if you need help.

**Comment by Cartographer-D** [comment]
I am told this Travis error is just Travis being bad and to not worry about it.

**Comment by Tlaltecuhtli** [comment]
does it fix double windoors in cargo office(the room with paper wrappers) ?

**Comment by Cartographer-D** [comment]
> 
> 
> does it fix double windoors in cargo office(the room with paper wrappers) ?

Yes.

**Comment by Cartographer-D** [comment]
This is ready whenever Travis decides to finally cooperate.

**Comment by Mickyan** [comment]
there appears to be a floor breach in the maintenance above the warehouse

**Comment by Cartographer-D** [comment]
> 
> 
> there appears to be a floor breach in the maintenance above the warehouse

UHHH I DONT KNOW HOW THAT GOT THERE

**Comment by Cartographer-D** [comment]
@Mickyan 

Thanks for spotting that, I genuinely don't know how it got there.

**Pull request merged**
