### PR TITLE
Tiny mobs can't push shit.

### PR DESCRIPTION
**Pull request by KazeEspada**

### CODE REVIEW

**Comment by Cheridan** [comment]
butterfly effect

**Comment by optimumtact** [comment]
This will affect drones, but apart from that just a bunch of simple animals which shouldn't matter too much.

:+1: I guess

**Comment by KazeEspada** [comment]
Client check prevents players of any type from being affected. Also, drones are size SMALL, so they are unaffected.

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Thunder12345** [comment]
More like cockroach effect

**Comment by LanCartwright** [comment]
manlets when will they ever learn

**Comment by KazeEspada** [comment]
Manlets are full sized humans

**Comment by Bawhoppen** [comment]
:-1: cockroach PA nerf

**Pull request merged**
