### PR TITLE
Makes Hygiene Sprite Less Jarring

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Changes the hygiene sprite.

## Why It's Good For The Game

I think a huge issue most players have with hygiene is the obnoxious green clouds. This still conveys the "smell" factor, but I think in a more mild way. You guys said you want to improve hygiene, and this is how I'll go about doing it.

## Changelog
:cl:
imageadd: New Hygiene Sprite
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
@Qustinnus Alright w/ you?

**Comment by Qustinnus** [comment]
I think @mrdoombringer wanted to make a new low hygiene sprite so depends on if they still plan on doing so

**Comment by HomocidlePancakes** [comment]
These two horizontal lines that pop out on the torso level are annoying

**Comment by nemvar** [comment]
New sprite is arguably worse. It creates more visual noise than the old one. Mainly because of the horizontal things that keep swirling around, it looks almost cartoonish.

**Comment by 4dplanner** [comment]
Can you post a video of it on a mob?

**Comment by MrDoomBringer** [comment]
@Qustinnus I'm okay with someone making a new sprite, not sure if this is an improvement yet though

**Comment by ExcessiveUseOfCobblestone** [comment]
Need visual of what both look like on a person (pref on plating).

**Comment by wesoda25** [comment]
Yeah sure. Also in my opinion its less busy, but maybe im tripping. Ill get a vid up later

**Comment by habader** [comment]
orange man come angry when player tribe touch-change stink-stink

**Comment by optimumtact** [comment]
:crabRP:

**Comment by wesoda25** [comment]
yeah i dont have recording software and tbh its so much effort to get one

**Comment by DaxDupont** [comment]
Just use sharex like the rest of the civilized world

**Comment by wesoda25** [comment]
sharex keeps giving me an error ahhhhhhhhhhhhhhh

**Comment by Nickkoranda** [comment]
I got tired of seeing this PR go on so I made this so wesoda wouldn't have to https://i.imgur.com/CCnrwlN.gifv

**Comment by ExcessiveUseOfCobblestone** [comment]
that black makes it contrast more than the green, no?

You can probably fix the sprite by just giving the default less alpha tbh.

**Comment by Anonymous583** [comment]
That honestly looks just as obnoxious and obviously worse, like a bunch of flies buzzing around the character instead of brap residue. Just remove hygiene and be done with it.

**Comment by wesoda25** [comment]
letting someone else do the work for you always works

tbh id rather have flies than brap residue but perhaps that is just me

ill make it more transparent later

**Comment by ExcessiveUseOfCobblestone** [comment]
Sorry I have never heard that before, I always assumed the argument was it was visually obnoxious because of the thiccness rather than being conveyed as BO instead of say flies or something like that.

I don't care which sprite is used really, I just want it to be less contrasting/of an "in your face" feedback.

**Comment by wesoda25** [comment]
I personally always hated the green clouds bc they were way to suggestive and just pissed me off, if its just me then...

**Comment by SkeletalElite** [comment]
I prefer this one way more than the green clouds. It could use a little transparency though too.

**Comment by wesoda25** [comment]
Making it transparent looks much better, I think its all set now.

**Comment by 4dplanner** [comment]
Video >:(

**Comment by wesoda25** [comment]
Nickko mr planner is talking to you

**Comment by ExcessiveUseOfCobblestone** [comment]
lol

**Comment by habader** [comment]
BRRRAAAAAAAAAPP

**Comment by wesoda25** [comment]
Well since we are waiting I will use you guys as tech support. Sharex screenshot function works fine for me, but screen record/GIF both fail immediately after selecting an area to record. I get error code: 0xc000012f and am told to redownload it. I’ve done so multiple times, through multiple different mediums, but no dice. Mods??!!

**Comment by granpawalton** [comment]
It should just be like hunger and visible as an alert/on examine tbh

**Comment by wesoda25** [comment]
Another day another dollar

**Pull request merged**
