### PR TITLE
Resprites bluespace gas vendors and senders

### PR DESCRIPTION
**Pull request by NamelessFairy**
## About The Pull Request

The existing sprites are an amalgamation of parts of existing sprites, this PR replaces them with original sprites designed for the devices

Sprites were made by me and were recolored by maxymax13

## Why It's Good For The Game

These sprites are at least slightly better than what we have at the moment

## Changelog
:cl: NamelessFairy, maxymax13
imageadd: Bluespace gas vendors have been re-sprited
imageadd: Bluespace gas senders have been re-sprited
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
image
lmao what
this isn't how perspective works

**Comment by MrDoomBringer** [comment]
the north-facing sprites look great tho 👍

**Comment by Ghilker** [comment]
> image
> lmao what
> this isn't how perspective works

well it is from a top down perspective

**Comment by maxymax13** [comment]
> 
> 
> image
> lmao what
> this isn't how perspective works

tell that to the sprites of every other wall mount

**Comment by Fikou** [comment]
how do they look ingame?

**Comment by NamelessFairy** [comment]
> how do they look ingame?

image

**Comment by MrDoomBringer** [comment]
> well it is from a top down perspective

> tell that to the sprites of every other wall mount

I didn't realize these were wall-mounted, that makes the pain a little better

**Comment by cacogen** [comment]
I love the matching outfit

**Comment by maxymax13** [comment]
YAY

**Pull request merged**
