### PR TITLE
Makes NPC queens/drones plant weeds/eggs

### PR DESCRIPTION
**Pull request by AnturK**
What it says on the tin. Egg planting defaults to NOPE.

### CODE REVIEW

**Comment by AlexCrimson** [comment]
Can you still get Queens/Drones from Gold Slime Cores? If so then you might wanna remove that first. Balance and all.

**Comment by WJohn** [comment]
Yeah that was my first thought. It'd also break MO19's function, unless this is a var you can toggle in the mapmaker or something.

**Comment by AnturK** [comment]
You mean the weeds ? I suppose i can add toggle for that too so maps with them won't get overrun with growth. Not sure how a few weeds in xenobio is unbalanced though.

**Comment by WJohn** [comment]
I mean for the eggs especially. Having all simple animal queens be able to by default lay eggs is going to be a real problem. It should be something that starts off, but can be toggled on in the map maker or by admins with VV.

**Comment by RemieRichards** [comment]
@WJohn it says in the OP that the eggs start off.
And they do.

**Comment by Jordie0608** [comment]
Changelog

**Pull request merged**
