### PR TITLE
Recycler no longer tries to eat qdeleted items

### PR DESCRIPTION
**Pull request by optimumtact**
This is also a bad idea

### CODE REVIEW

**Comment by optimumtact** [comment]
need to change this to calculate all material costs first, before deleting anything

**Comment by NoxVS** [comment]
Would this fix weird behavior when tossing a filled His Grace into the recycler? I noticed it caused weird “ghost clothes” (Clothes are visible on the body but don’t exist, goes away when you put new clothes on) to be left on the victims but never got around to reporting the bug.

**Comment by optimumtact** [comment]
no idea

**Comment by Timonkeyn** [comment]
But I love qdeleted taste, it's just so good

**Comment by SpaceManiac** [comment]
Looks OK to me, do you still want the reclamation calculation to be done first?

**Comment by optimumtact** [comment]
I don't see how we can't not do it, as the previous behaviour would ensure you get paid for contents of a box, but this wont?

**Comment by optimumtact** [comment]
sorry im too burnt out to finish this

**Pull request closed without merging**
