### PR TITLE
Sketchin Alt Magazine Sprites

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR creates unique sprite marks for the alt ammo for the Sketchin Pistol, akin to the new Auto Rifle mag sprites.

newmags
Top left clockwise. Armour Piercing, Hollow Point, Incendiary and Standard.

:cl: Steelpoint
add: Sketchin alternative magazines (Armour Piercing, Hollow Point, Incendiary) now have unique sprites to better identify them. 
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
Good as always

**Comment by Repukan** [comment]
Would it be possible to have a vertical stripe instead? Looks like you put a colored rubber band on them

**Comment by Steelpoint** [comment]
I assumed the sprite shows the magazine at a slight incline.

**Comment by WJohn** [comment]
I would much prefer a vertical stripe.

**Comment by Steelpoint** [comment]
Stripes are now vertical.

magaizines2

**Comment by Repukan** [comment]
Uh

**Comment by Steelpoint** [comment]
I'm a big idiot who did not pay attention to the request and just made a assumption.

I'll resprite it.

**Comment by Tacolizard** [comment]
pics or gtfo

**Comment by Steelpoint** [comment]
New image based on vertical requirement.

newmags

**Comment by Lumipharon** [comment]
Was it the smg sprite, or some other gun where it has the holes along the side so you can visually see (roughly) how many bullets you have left?
That was always a nice feature to have.

**Comment by Repukan** [comment]
That's the nuke op cr 20

**Pull request merged**
