### PR TITLE
Adds compact pickaxes

### PR DESCRIPTION
**Pull request by MMMiracles**
pickaxe

Its a pickaxe that can fit in your bag in exchange for less damage and a slightly slower pickspeed. KAs have kinda made pickaxes irrelevant to a miner so this is a compromise for emergency situations, like getting cornered after a goliath fucks you out of your KA with several hundred legion skulls swarming you.

 No this wasn't made out of salt at all what are you talking about.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
You're probably better off making pickaxes normal sized items, they can already be held in explorer's belts anyhow

**Comment by Zilenan91** [comment]
There's no real reason to not make regular pickaxes smaller. It's just 15 brute.

**Comment by coiax** [comment]
> Just 15

**Comment by TechnoAlchemisto** [comment]
to be fair lit welders do the same amount and are way more common, circular saws are easily accessible to miners as well and they can dismember. 

And I don't want to highlight how strong miners are at round start but their survival knives also do 15 brute, can fit in a boot, and can dismember.

**Comment by Bawhoppen** [comment]
@TechnoAlchemisto where was this argument when I wanted to make crowbars not be utter garbage

**Comment by WJohn** [comment]
Because you can print out about 50 crowbars per sheet of metal, whereas circular saws take about 5 sheets to make each.

**Comment by Bawhoppen** [comment]
I wasn't even buffing them to 15, ONLY 10, WHICH IS THE SAME AS EXTINGUISHERS WHICH ARE THE FUCKING MOST COMMON SHIT REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Pull request merged**
