### PR TITLE
MiiyaBot's Marginally Edited BedHairs

### PR DESCRIPTION
**Pull request by MiiyaBox**
◈ About The Pull Request
Just a small touches to some Bedhair, plus some "new" ones.
currently just a small tiny amount as I have not time to go over most hairstyles.

image
image

◈ Why It's Good For The Game
Some hairstyles have some quirky shading, sometimes lacking any at all.
I plan on changing that so more hairstyles can be appreciated by the common station folk, while hated by the most bald angry man in charge of NTstation.

🆑
add: Adds far too little haircuts.
(Bedhead 4X, Marginally shorter yet Long Bedhead)
add: changes a tiny portion of bedhairs. (Bedhead 1, 3) 
/🆑

### CODE REVIEW

**Comment by Wallemations** [comment]
You should have picked a different shirt/hair color, it makes it very hard to tell where the hair is in relation to the shirt

**Comment by MiiyaBox** [comment]
> You should have picked a different shirt/hair color, it makes it very hard to tell where the hair is in relation to the shirt

Oop! Here it is!
image

**Comment by Bluedino1025** [comment]
I really like these (and have been wanting shoulder length bedhead forever) but I do kind of think it cuts off a bit suddenly on the sides of badly cut bedhead

**Comment by MiiyaBox** [comment]
> I really like these (and have been wanting shoulder length bedhead forever) but I do kind of think it cuts off a bit suddenly on the sides of badly cut bedhead

image

**Review by Imaginos16 — APPROVED** [review]
Nice work!

**Comment by Bluedino1025** [comment]
> image
> 
I was more meaning the side sprite cuts off very suddenly, (a couple pixels could help), but other than that I love it!

**Pull request merged**
