### PR TITLE
BirdShot Service Department Changes

### PR DESCRIPTION
**Pull request by GremlinSeeker**
## About The Pull Request

Revitalizing birdshot by extensively changing up most of the service departments.

## Why It's Good For The Game
Birdshot is in need of some changes. I was hoping that these changes would help improve it in the eyes of players.

This birdshot update features essentially an entirely moved/renovated service departments, along with an addition to an arcade and a commissary, along with a much improved public chapel. Moved the service lathe to a new service hall found between the kitchen and hydroponics. You can see the new layout below.

image
## Changelog
:cl:Viralmilk22

add: Shifted up the service departments on Birdshot.
add: Added an arcade.

/:cl:

### CODE REVIEW

**Review by Maurukas — CHANGES_REQUESTED** [review]
Missing APCs in the following areas relevant to this PR:
```
/area/station/hallway/primary/port
/area/station/hallway/primary/central/aft
/area/station/service/kitchen/
```
Missing Air alarms in the following PR relevant areas:
```
/area/station/service/kitchen/
/area/station/hallway/primary/central/aft
```

You have a large number of active turfs in the central hallway:
image

There may be more issues, but my Windows system has committed suicide and I cannot review further.

**Review by Maurukas — COMMENTED** [review]
Cameras look good, as do power and atmos networks. 

I like this a lot. It feels like the station has been lived in for a while and been given a nice remodel.

**Review by Pepsilawn — COMMENTED** [review]
image
wall decals

image
image
blue pipe not connecting to anything

image
image
a few atmos wackies (kitchen, kitchen, front of library, courtroom in that order)

image
wacky cable @ the library

image
no portals? :(

**Comment by Maurukas** [comment]
Ten Active Turfs left here:

image

You can use the Mapping tab in game on a local server to check.

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
