### PR TITLE
Replaces Nutriment with Salt in Virology cures

### PR DESCRIPTION
**Pull request by Iamgoofball**
suggestion from forum thread on making virology less painful and dumb

doesnt fix the rng but i guess this is better?

### CODE REVIEW

**Comment by GunHog** [comment]
Even though you are doing this as some silly little joke meme, it actually is not a bad change. Heal viruses normally have nutriment as the cure, and without weight even, the carrier may eventually eat and lose the virus unintentionally.

Consuming salty things or pure salt would be an act of intent, and thus the curing of a heal virus is always done by intent!

**Comment by Iamgoofball** [comment]
not as a joke meme, this is the only actual suggestion I've gotten on how to improve current viro

i'm looking into the other shit too

**Comment by Boredone** [comment]
Minor suggestion you switch around sugar and salt. Sugar is more common, being in most/all vending machine food, and nutriment was chosen as something EASY to cure.
Plus you can dispense pure sugar, but not pure salt, have to mix that.

**Comment by Kelenius** [comment]
>Sugar is more common, being in most/all vending machine food

Which is why nutriment is being replaced, isn't it?

>Plus you can dispense pure sugar, but not pure salt, have to mix that.

Two clicks instead of one, oh noooooooo.

**Comment by Firecage** [comment]
Well, nutriment is meant to be a quick and easy way to cure viruses with low resistance due to being common and easy to get, since, ding ding ding, that was the intent between virusses with beneficial effects and those with negative effects. Add some non-positive effects to a virus if you want it harder to cure.

**Comment by Tokiko1** [comment]
Is that really true? Silver is the second highest resistance cure and it's readily avaible at the chem dispenser while nutriment or orange juice are not, even though they are much lower.

**Comment by Kelenius** [comment]
I'd say it's easier to find salt than nutriment.

**Comment by Giacom** [comment]
Cool change.

**Comment by Fox-McCloud** [comment]
@Kelenius 

Not really. No vendor snacks have salt in them; the only publicly available salt is in the salt shakers--contrast this to nutriment, which is in every single snack vendor and every single food related item the chef has.

Either case, the entire scaling of cures needs to be changed, IMO. Currently only a gold-based cure is "difficult" to cure---and if things are bad, you can just yoink the gold from the vault.

**Comment by SconesC** [comment]
Good virology buff

**Comment by Zilenan91** [comment]
@Fox-McCloud Completely agree. The cure mechanic is really weird, since the highest resistance cure (spaceacillin) is actively available on the map at round start, and can be made entirely in chemistry, whereas things that should be easier to cure, like gold, are not, and thus are harder to get to without raiding the vault.

@Iamgoofball Virology as a whole could be improved if some kind of pseudo-random chance, like in Dota, where if you're trying to get a specific symptom, every time you don't get it, the chance to get it goes up until you do. It would make making diseases so much better than it is currently, and hopefully remove the occurences of virologists being unable to get even a single healing virus by 30 minutes into the game on some rounds, but not the chance of getting several healing viruses in 10 minutes. It would likely be need to be done in a new computer console specifically for virology (or just retooling the PANDEMIC machine).

**Comment by Iamgoofball** [comment]
merge when

**Comment by Iamgoofball** [comment]
merge when

**Pull request merged**
