### PR TITLE
Makes cable great again

### LINKED ISSUE #28067: Storage items that previously held cable coils in them no longer can.
Though full utility belts spawn 30 cable coil stacks in them, if you take it out and put it back in it won't fit anymore.

### PR DESCRIPTION
**Pull request by QualityVan**
Fixes #28067

### CODE REVIEW

**Comment by obscolene** [comment]
MAKE CABLE COILS SMALL AGAIN

**Comment by BeeSting12** [comment]
Test merge this or speed merge it this is really annoying

**Comment by DoctoreMad** [comment]
Change PR title to "makes cable great again"

**Comment by Bawhoppen** [comment]
or don't because that's a stale meme

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
