### PR TITLE
[READY] Plumbing: Chemical Filters

### PR DESCRIPTION
**Pull request by Time-Green**
Adds chemical filters to the plumbing arsenal

They have one input, and three outputs. The left and right outputs can be given filters. It's basically the exact same as atmos filters but it has TWO filter sides.

It doesn't have an enormous list of chems to select from, you just enter a chem and it's added if it's valid. 

:cl:
add: Adds chemical filters to plumbing
/:cl:
I was planning to do a bunch at once, but europe is on fire and im delirious

I also moved the existing unique plumbing datums into their own folder, wich was only chemical acclimators

### CODE REVIEW

**Comment by Time-Green** [comment]
The remainder is relatively small, so my next PR will be the big finisher. 

After that I'll PR it to be available in-game.

**Comment by wesoda25** [comment]
I want my chemistry/botany mutagen pipeline NOW!!

**Comment by SpaceManiac** [comment]
merge conflict

**Comment by Time-Green** [comment]
Thirs time sending this: I’ll get on it once I have working internet

**Comment by Time-Green** [comment]
Conflict homocidalized

**Comment by spessbro** [comment]
i honestly think this is one of the best prs we've had so far 👍

**Pull request merged**
