### PR TITLE
Armory re-mapping and autorifle removal

### PR DESCRIPTION
**Pull request by ghost**
I've been holding off on making this pull request for quite a while now. I played a lot of sec after autorifles were introduced, and I've had opportunity to observe a lot of rounds and play in even more, and I think autorifles should go.

Autorifles completely trivialize combat for the wielder. If Security has them, they can easily eliminate almost any threat by using a riot shield and autorifle, and there's no shortage of ammunition for them to use. If an antagonist has them, Security fall like dominoes because no matter how many lasers they use, the autorifles are still ridiculously powerful and trump them anyway.

Autorifles are still available in the code. They are not, however, found on the map at roundstart. Currently, the change only affects Box, as I don't know if the other maps have been changed to have the autorifles yet.

Screenshot of the new armory:

Note that the mechanical toolbox is actually a drone toolbox - this is so that Security gets all the tools. The ammunition locker to the right of the implants is bolted to the floor and cannot be moved.

### CODE REVIEW

**Comment by Steelpoint** [comment]
Personally I disagree, of course.

I think your overblowing the power of a auto rifle, how exactly do they trivialize combat for the wielder?

**Comment by Steelpoint** [comment]
If ammo is the problem (which its not now that I'm removing the excess magazines) then a simple value change can swap the auto rifle rounds from 9mm to something else, so you can't load bullets from cargo.

**Comment by GunHog** [comment]
There are other map changes that are being held up by this and the other armory PR, so could you make your epic Xhuis vs Steelpoint battle somewhat quick, please?

I do not agree with your removal of the rifles, by the way. The extra ammo was going to be removed, so that might help with the perception of them being OP. I am not a Sec player, though.

**Comment by Steelpoint** [comment]
Also "you think".

We had a poll and the vote was very down the line, hence why I'm introducing the ammo nerf. If that's not enough a magazine nerf to 15 or so rounds would also be fine.

As other's will spout, improve don't remove

**Comment by TechnoAlchemisto** [comment]
The poll has shown that these add and detract nothing from gameplay. They're non-essential and I think detract overall from the general theme of the game. We don't need more guns in the armory, and although it was an interesting thing to try it's just sorta unnecessary. 

Also the armory format is kinda lame.

**Comment by Shadowlight213** [comment]
No, xhuis is right. The autorifle completely beats any of security's other guns. Riot shield autorifle has pretty much been the goto I win combo for sec.

**Comment by Lumipharon** [comment]
If they're so important you can go to cargo and get all you want after a 2 minute wait.

:+1:

**Comment by Steelpoint** [comment]
Lumi you can say the same for virtually any item in the entire game.

If metal is so important you can go to cargo and get all you want after a 2 minute wait.

If armour is so important you can go to cargo and get all you want after a 2 minute wait.

If janitorial equipment is so important you can go to cargo and get all you want after a 2 minute wait.

**Comment by Steelpoint** [comment]
Also please explain why auto rifles beat any other sec gun?

Aside from ammo (which is being nerfed as I speak) how do they beat it? I already explained how both weapons function as a side grade to the other.

Just because people use X gun a lot does not make it more OP, it just means you see it more often.

**Comment by bustygoku** [comment]
GUYS IT'S FINE I'LL JUST DO A POLL LET'S TRY THEM OUT

>people hate them

OK I'LL NERF THEM!!!!

No you idiot, people don't want them. Get it through your thick, 50 melee resistance helmet.

**Comment by Steelpoint** [comment]
Did I accidently delete my own post?

Well in response to Techno I said that the change was just as highly praised by people as it was criticised.

**Comment by Dorsisdwarf** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
Not surprised it came down to this---I'm really shocked people pitched more of a fit about the pistols than these---the pistols had way more potential to be viable side-grade than these ever did, IMO.

**Comment by Steelpoint** [comment]
What's the point of a in game poll that clearly shows a divide in the player base, and then someone just decides to gut the item instead of making it work

Wowow

I'm already trying to effect changes to bring the rifles more in line, so instead of just removing it why don't we just improve it.

This was never a universally hated change, as much as some people really wish it was.

**Comment by Fox-McCloud** [comment]
ohhh...reminds me.

@Xhuis 

If you're going to do this, then make sure you remove the auto-rifle ammo from R&D--no sense in having ammo that doesn't go with anything.

**Comment by Lumipharon** [comment]
Steel whatever you do doesn't change the fact that you're massively buffing the total lethality of the armoury. It doesn't matter how you spin it, the fact is it just means moreguns for people to have.

I am saying you can just get it from cargo, because everyone has been just fine with an autorifleless armoury for years, and as a result OF THE PR WE ARE SPEAKING IN, you can just order them from cargo if this specific type of gun is so important to you.

**Comment by Steelpoint** [comment]
We've had a lot of things for years that were changed.

Stuns, energy guns, armour values.

The list goes on.

**Comment by Steelpoint** [comment]
Putting a item in cargo and telling me to order it is effective to removing it from the game but throwing me some spare change so you don't feel bad or seem like its not a bad change.

**Comment by Lumipharon** [comment]
Yes and everyone else is telling you we don't like this in the pr and forum thread.

Stop trying to make your pet project work - accept the fact it's not popular (less then 50% of a poll saying they don't dislike an item that doesn't effect every round does not mean it's popular) and just move on.

**Comment by Steelpoint** [comment]
Again, the poll clearly showed a equal amount of people liked the gun versus disliked it.

Just wait for my further changes to the gun before you unilaterally decide to remove the gun cause you think that's right.

**Comment by Lumipharon** [comment]
How is it unilaterally when every single person in this pr and the thread disagrees with you?

Making the item so shit and inconsequential that it can stay is not great.

**Comment by Steelpoint** [comment]
Because ever since I introduced this PR a small group of people have gone out of their way to find any method to harass and tell me how not only my change is shit but I'm a shit player and a bad person in general.

I've fought tooth and nail to balance and get this gun to work, and after all that work I got a server poll which showed, much to the dismay of those people, that the gun was not as universally reviled as they wanted it to be.

Over our history we've had many changes to the game that were highly contraversial, stun changes, energy guns changes, chemisty changes, massivly powerful additions from RnD to Med.

Yet now we have to put our foot down, these auto rifles are what tip the scales over.

Give me time to balance out the guns, instead of just removing them.

**Comment by Shapsy** [comment]
And remember folks, he does it for free

**Comment by Shapsy** [comment]
You made your initial PR a month ago and there's still no realistic solution to solving running around with 10 mags on you short of straight up making the guns useless without help from cargo or RND

**Comment by Lumipharon** [comment]
The differences between a autorifle and a laser gun.

Autorifle has higher capacity. You are saying you're going to cut that.
Autorifle has spare mags instead of recharging. You are removing them.
Autorifle can print fresh ammo. You're making them some special snowflake calibre

Which basically leaves us with: EMP immune and can shoot through windows.
How again does this "give more options against antags like rev and cult", anymore then simply buffing and/or increasing the number of lasers? (or nerfing the jugg reflect ability if thats the specific example there)

Also I suppose not being hard countered by 2 items designed explicitly to hardcounter energy weapons, which sec previously had almost solely access to.

**Comment by Shapsy** [comment]
>You keep changing your gun design to try make them stick, because you refuse to accept that there are far more reasonable, less balance effecting ways of solving the issues that this gun is supposed to address.

Yeah basically that

**Comment by Firecage** [comment]
:+1:

**Comment by Jalleo** [comment]
@Lumipharon since when can bullets go through windows?

**Comment by AlexanderUlanH** [comment]
>Because ever since I introduced this PR a small group of people have gone out of their way to find any method to harass and tell me how not only my change is shit but I'm a shit player and a bad person in general.

You got us, we oppose autorifles 'cause bob from accounting at your work told us to mess with you personally.

Except that's not the case.  People don't want autorifles because they think they're genuinely bad changes, and you haven't been able to offer arguments in support of their complaints.  They're attacking you personally because you
>fought tooth and nail to balance and get this gun to work

Without considering the possibility that they weren't a good idea in the first place.
People tend to make things personal when they're being ignored on the issues.

**Comment by Miauw62** [comment]
vote for removing them was 50/50, and there is quite some dislike against them amongst maintainers/coders, so :+1:

**Comment by Steelpoint** [comment]
The votes for features like Goon Chem, Slow Speed, Gun Rebalancing and areas like the the AI Satellite had around a 50/50 split in votes both ways, yet we kept them and improved them instead of allowing reverts to go through not long after the fact or while they were being worked on.

So why are Auto Rifles the only exception? Auto Rifles are actively being worked on, they have not been abandoned. Its been accepted that my rebalancing in my PR (https://github.com/tgstation/-tg-station/pull/12122) will be a good change.

So why don't we allow me to continue to balance and work out this feature?

We are very allowing for people to work and balance out features, look to Cult, Gang, Nuke Ops or any feature we have. But now we have to revert this as its unsalvageable.

**Comment by Miauw62** [comment]
didnt you literally say "this wont be like goofchem"

youve already done a lot of balancing and its still shit
maybe its time to remove it and start over

**Comment by Steelpoint** [comment]
Goon Chem was in a bad shape for months, this PR has barely been up for three weeks, give or take.

**Comment by Steelpoint** [comment]
I mean, I could make the guns two handed if the riot+gun combo is so OP.

**Comment by CPTANT** [comment]
I can't say I have heard a convincing argument on why the rifles should be in the game.

**Comment by Bawhoppen** [comment]
Making them two-handed would be more retarded, Like I said. Keep them but nerf them to 10 damage and 10 round clipazine.

**Comment by Steelpoint** [comment]
10 damage is too low, 15 to 20 rounds per mag is what I think is good. This in conjunction with my mag change meaning that sec would need to order more ammo to sustain gun usage for long term.

**Comment by Bawhoppen** [comment]
How is 10 too low for a thing that is already objectively better than lasers/eguns? With lasers and eguns your projectiles get auto-deflected by ablatives, eshields, dual eswords, juggs, and many other things, yet bullets don't by anything. That would make it VERY useful still, however just less overpowered than it currently is.

**Comment by Steelpoint** [comment]
Well counting bullet armour (which all antagonists have good bullet defence) that 10 damaging bullet is now dealing 5 or even 3 damage per round.

it's stupid that a gun is dealing less or equal damage to a fire extinguisher or a tool box.

**Comment by Bawhoppen** [comment]
It is logically, however balance-wise it most certainly is not. You can from a infinite distance fire very rapidly and just demolish someone, if you nerfed damage, you would really be making it more equal to lasers

**Comment by Steelpoint** [comment]
You can fire with lasers off of screen.

Also do you play with guns? Well you do since your bragging about your combat prowess in game. So you would know firing your gun off screen down a hallway is a waste of ammo.

Having the gun deal only 10 damage per round would make it ineffective. If you wanted to crit someone you would need to pray they are not wearing armour and land ten consecutive hits with your gun, mind you your proposal also has it that the gun has 10 rounds.

Good luck getting 100% accuracy.

**Comment by Dorsisdwarf** [comment]
>firing a gun offscreen is a waste of ammo

Have you even fired  the SAW down the dreamstation supercorridor? Collateral for days

**Comment by Steelpoint** [comment]
There's a worlds of difference between a six round bursting, 60 round per mag, LMG that deals 60 damage per bullet versus a rifle that deals 20 damage per bullet (had a very obvious sprite) and has a slow RoF akin to a laser, or even a Laser.

**Comment by Dorsisdwarf** [comment]
Firing /anything/ down the dreamstation corridor is going to hit at least one guy

**Comment by Steelpoint** [comment]
Ok.

So what's the problem?

If you fire a laser, a rifle or any other fire arm down a non-boxstation corridor it will likely hit someone at least once.

How is this relevant?

**Comment by Bawhoppen** [comment]
The infinite range argument in itself is relatively pointless, I don't know why I brought it up, but your rifles still have much more ammo capacity due to the ability to carry many mags on you, instead of needing to go back and recharge, as well as the usage against other things I listed above that energy projecticles don't work against. You like to act like decreasing damage to 10 would make them useless, but they'd still be another energy deflection defying ranged weapon which you can mass fire with barely any need to worry about ammo.


Also
>Well you do since your bragging about your combat prowess in game
Explain when the fuck did I ever do that?

**Comment by Steelpoint** [comment]
Maybe I mistook you, but I digress.

The magazine argument holds little water, considering my PR removes the excess mags from the map thus making it a cargo/RnD item only.

At that point there's little difference between ordering a crate of lasers versus a crate of ammo.

**Comment by Bawhoppen** [comment]
Why would you say its hard to get ammo from cargo? A box of 30 rounds for a few metal sheets? Seems pretty easy to me, all it takes is 5 minutes to stock up for a good amount of the round.

**Comment by Steelpoint** [comment]
Except you missed when I said I was changing the rifles to use non-9mm ammo.

**Comment by Bawhoppen** [comment]
then why did you say cargo just a second ago

**Comment by Steelpoint** [comment]
They can order magazine crates from cargo.

**Comment by Bawhoppen** [comment]
you mean crates yes? anyways I don't know what R&D level you want it at, but R&D speedgaming is not hard.

**Comment by Bawhoppen** [comment]
I realised that as I hit the post button, but still

**Comment by Steelpoint** [comment]
The magazines in RnD should be expensive to produce, if not I'm already buffing them.

**Comment by Steelpoint** [comment]
Also if RnD gets to high levels of research they can produce Laser Cannons or SABR's.

**Comment by Bawhoppen** [comment]
If we leave rifles in the armory, theres still 4 of them (3 if your pr is the one which is merged), which is still alot of firepower for what they are, their damage needs to be nerfed below the laser guns IMO still, even if only a little in order to help balance where bullets are almost always better than lasers. But the ammo limitation is very good.

**Comment by Aloraydrel** [comment]
:+1:  Yes please remove the meme rifles

**Comment by Dorsisdwarf** [comment]
Miauw picked the other PR to try first.

**Comment by Durkel** [comment]
:+1:  Getting real tired of having to play a bullet hell anytime security opens the armory. Seriously, you know how much of a bitch it is to dodge 20 fucking bullets in quick succession?

**Comment by PKPenguin321** [comment]
i like steelpoint but i don't like the rifles
:+1:

**Comment by Razharas** [comment]
I approve this change

**Comment by Xhuis** [comment]
I want to make something clear here: ___I am not removing the autorifles. Please do not think I am.___ I am removing them from the _Armory_ at _roundstart_, for the reasons outlined in the OP. @Steelpoint, nobody is personally against you. We don't want to fight you just because you're you. 

A majority of the admins and maintainers disagree with the addition of autorifles, and even the people who agree with them have nothing to back up their support when Amelius breaks into the armory for the 50th time as a changeling and steals all the autorifles to subsequently go on a killing spree and chain-recall the shuttle. Hence, I created this PR.

Autorifles are still in the game, but no longer very easily obtainable. The prototype SMG found in R&D is arguably better and easier to obtain, but autorifles are still obtainable from cargo if Security feels like a threat is too much for them to handle.

**Comment by Nanotransistor** [comment]
:+1:  In their current state they are just too good. I think the only way they would make more sense is if they dealt less damage per shot, maybe 6 or 8, and fire faster to compensate (like with the ranged Guardian). Also they should be big like a shotgun so you can't put them in your bag.

Right now they are too strong, and the go to weapon against any threat. They are only ineffective against a blob i think.

**Comment by Xhuis** [comment]
Working on a second remap of the armory based upon the latest version of the armory made by Steelpoint (because it's actually pretty good)


, here's a bit of what I have so far:

**Comment by Xhuis** [comment]
I re-mapped the armory, again. New layout is in the OP.

**Comment by Lumipharon** [comment]
Stops comparing steelrifles to things like slow speed, stun nerf or goofchem.

All 3 of the above were significant BALANCE changes that effected the enttire game (goofchem not so much, but still significant).

All you've done if buff one job by adding fuckloads of extra firepower to the armoury. And again, as I and others have said multiple times, yet been completely ignored, you refuse to accept the fact that that there could be better ways to try resolve the issues you supposedly added these rifles to fix, without fucking up balance in other way.

With the other mentioned changed, there really wasn't any other alternative to the changes (unless you could whatshisfaced vapourware chem changes). So there is a big difference.

**Comment by Xhuis** [comment]
### ___Stop arguing here. If you want to argue, do it in PM or on the forum feedback thread. If this keeps up, I will be pinging a maintainer to lock the conversation.___

**Comment by Fox-McCloud** [comment]
Wait uh...where's the shotgun ammo?

**Comment by Xhuis** [comment]
uhhh

**Comment by Robustin** [comment]
AR Observations:

1) Armory has become TOO important for station power balance. Raiding the armory was already a big deal, but you could recover from it. Now you've got dudes with a super efficient lethal. Before an armory run might net you ~5-7 kills before you need to start recharging. Now you can murder the entire station with a box of AR ammo in addition to the taser/laser combo. 

2) Over-encourages sec to go straight to lethals. Holy water the cult? Surgery the thralls? Implant the gangs/revs? Fuck that I've got enough ammo to wipe out an entire department, handcuffs are for pussies!!! *POP POP POP*

3) Unnecessarily complicates ranged combat and dilutes the themes of nanotrasen v. syndicate. 

The only aspect of my round I've ever seen enhanced by the AR's is my ability to mass murderbone. That's been my observation of other players too.

**Comment by Xhuis** [comment]
I added the beanbag ammo locker to the armory, to the right of the rack with implants. It's anchored to the floor, as well.

**Comment by Niknakflak** [comment]
Quick, someone meme merge before steelball rants my ears off again

**Comment by Xhuis** [comment]
This has no more conflicts, and is merge-ready (although it hasn't gone up to the 24H period yet).

**Comment by pudl** [comment]
The placement of the vent/scrubber is really inefficient. Putting them about arbitrarily results in bad things.

I would prefer that tg goes back to the old armory if you're reverting rifles. This version is awfully cramped and a lot uglier than what we had pre-rifles. Sorry.

**Comment by WJohn** [comment]
Yeah those scrubbers and vents need to be moved further into the room, it looks ugly where it is now.. While the armory IS cramped, I don't this that's too big an issue.

**Comment by Steelpoint** [comment]
Just put them where I put them.

Also I still think this is premature to remove the rifles, especially when I'm still working on them.

**Comment by pudl** [comment]
Jesus fucking Steelpoint, can you just piss off with your shit. The idea of autorifles are bad. It's a trial run, your trial failed. You lose, Pisspoint (Penispoint is funny too, I couldn't decide which I liked better so I'm including both), good day. You don't just throw something in and ask for a test run then tinker with it afterward. That's not what the system is for, dumbass. Also, don't act like they're really out of the code. I'm sure if an admin thinks Security is knee deep in semen they'll provide the autorifles, since they're BTFOmachines that fuck everything up with no ragrets.

**Comment by Steelpoint** [comment]
The trial was before the rifles were merged.

The vote showed clear support and opposition for the rifles, not some 100% opposition. Its 50/50 both ways.

**Comment by Xhuis** [comment]
@pudl You just defined the point of test runs. He let them be tested and is now seeing about making the players happy.

@WJohn I was requested to put the vent and scrubber there so that they'd still function under minor bombing. I will look into placing them more evenly in the room. 

@Steelpoint Enormous props, dude. Even after the huge shitstorm these rifles have caused, you haven't wv

**Comment by Xhuis** [comment]
Fucking phone

**Comment by Xhuis** [comment]
I further updated the armory, put the vent and scrubber under the racks, and updated the OP with the latest look. The ammunition locker is anchored and cannot be moved.

**Comment by Steelpoint** [comment]
I feel a merge at this time would be very premature, my balance PR has not even been updated to the server at this time.

If I had abandoned the Auto Rifles, and/or did not seek to improve and restrain them then a revert PR at this junction would be justified, but right now I feel that removing the weapons as they are being actively worked on is not only premature but somewhat insulting that I can't be allowed to balance and work the rifles in a reasonable time frame,

Rome was not built in a day, many good features took a long time to be worked on and made better than their initial implementation.

**Comment by Xhuis** [comment]
I have no problem with waiting a few days or so for the balance PR to be tested, but autorifles have been in for a month, and I think that most people have decided if they like the rifles overall.

**Comment by Steelpoint** [comment]
True, but I see that one of the biggest complaints against the rifles is the availability of easy to carry ammo.

So what I want to do is scale back the round start access to ammo, forcing sec to go out of their way to get more ammo if they want to sustain their rifle usage for the long term, hence to cooperate with cargo for crate or get science on their side for access to special ammo or even just better guns (SABR or Adv EGun).

At minimum my removal of the excess mags and removal of one extra should have really hit the core of the issue with the rifle.

**Comment by Dorsisdwarf** [comment]
DNM for the next few days. Give peace and machineguns a chance

**Comment by Steelpoint** [comment]
Is there any way to go forward that can satisfy both parties that does not involve merging this PR as is or closing the PR without further changes.

Such as alterations to the rifles to address aspects that may be seen as overpowered in comparison to laser rifles.

I'm already looking to effect the following changes.

* Change bullet type from 9mm to 4.6×30mm, dealing the same damage but 4.6×30mm cannot be printed from a cargo autolathe.

* Increase magazine cost from RnD significantly, including for alt ammo.

There'a also the possibility of not only nerfing the ammo of the rifle to around 15 bullets per magazine, but also looking to find sprites that fit a more retro theme, such as a MP5 or UMP style SMG. Or even just the original sprites I used originally.

**Comment by Steelpoint** [comment]
I mean, art wise I think that standard issue security officer equipment should have a more older retro theme to them, but the more advance and higher tier weapons and equipment should have a futuristic appearance. 

I think the rifles might look jarring as they are far more detailed than the other sec weapons

**Comment by pudl** [comment]
I think that art wise you should suck my chode. I play a round as warden and the first thing security officers do is beg for lethal weaponry, even if the roundtype isn't confirmed. Security doesn't need autorifles, they have lasers.

Oh yeah, what happened to Paprka and xxalpha's ballstics = antag and laser = Nanotrasen? These guns are just a sore thumb and like fuck do they stick out as devices made literally to enable your infantile antag v. security fantasy, as opposed to I don't know, people having fun.

**Comment by Xhuis** [comment]
@Steelpoint I think that, at this point, both parties will never be happy with one solution.

**Comment by pudl** [comment]
@Xhuis I just watched you comment that we were on the same page at the same time we're soulmates.

**Comment by Razharas** [comment]
TIME TO MAKE JUDGEMENT BASED ON NOTHING BUT MY PERSONAL FEELINGS AS I NEVER READ THE COMMENTS HAHA
MERGED

**Comment by Xhuis** [comment]
:O

**Comment by Bawhoppen** [comment]
This is good merge, BUT THERES STILL NO FUCKING CONTRABAND LOCKER. AND EVIDENCE STORAGE BETTER BE BACK

**Comment by pudl** [comment]
Thanks for not stopping this from happening @Xhuis I'm telling mom on you.

**Comment by Lumipharon** [comment]
:+1: 
Everything Baw said is very much valid though.

**Comment by Xhuis** [comment]
Evidence storage is back.

**Comment by Steelpoint** [comment]
I'll look over the armoury on my Hardsuit PR to make sure nothing else aside from the rifles was removed or relocated back to the armoury.

Annoyed a bit that we could not reach a middle ground, but ehhhhh.

**Comment by pudl** [comment]
@Steelpoint @Xhuis 



What do you think of that?

**Comment by Bawhoppen** [comment]
I forgot about the flashs myself, that is the best yet, however there is supposed to be an access door from the equipment room into the armory.

**Comment by pudl** [comment]
There's no reason for an access door anymore since the Tac equipment is removed. No one is doing any suiting up in there. Also, the image has been updated.

**Comment by KorPhaeron** [comment]
Time to steal autorifles for my own devious changes. You have not seen the last of them worry not

**Comment by Steelpoint** [comment]
Can we at least let the server update to the new design, and let my PR live, before we change the armoury yet again.

**Comment by Xhuis** [comment]
@pudl Isn't that literally the old armory, though?

**Comment by Steelpoint** [comment]
It is but the guns are in the middle versus the lower half.

Probley since the guns being higher makes it easier to steal them and bombs will destroy the guns reliably.

**Comment by Bawhoppen** [comment]
@pudl Thats not what I'm talking about, literally one existed in the old armory so officers could gear up in the armory.

**Comment by pudl** [comment]
The old armory had a desk without a shutter on it. And Steelpoint, this design doesn't have a lot of equipment because Xhuis forgot about it, and it doesn't fit what he forgot either.

**Comment by Xhuis** [comment]
I put the portable flashers in the Security Office. Other than the contraband locker and the (useless) bulletproof armor, I can't think of anything I forgot

**Comment by Steelpoint** [comment]
>useless

80 Bullet Defence armour is useless, hilarious.

**Comment by Bawhoppen** [comment]
Oldrifle armory had it.

**Comment by Xhuis** [comment]
@Steelpoint I've seen entire Sec teams in bulletproof armor fall to two gangsters with Uzis. When you consider that the helmets only have a fraction of that protection, and most people target the head, you end up with ineffectual protection on all accounts.

**Comment by Lumipharon** [comment]
That's because it bulletproof armour got nerfed, then only the vest got unnerfed, for REASONS.
Someone should fix that.

**Comment by pudl** [comment]
Note: As of this update, security now only has 2 flashers.

**Comment by pudl** [comment]
@Razharas Just as a question, I'm guessing that if I were to submit my redesign it would be instantly closed because of the whole "stop security wars" shit?

**Comment by Steelpoint** [comment]
Why don't we wait until the body is cold before changing the armoury again?

Hence why I was slightly annoyed with this merge as my balance PR was not even up for 24 hours on the server.

**Comment by Bawhoppen** [comment]
From seen in practice, I definitely don't like your new armory steelpoint. The removal of evidence storage, no contraband locker, no porta-flashers, warden can't even see the entire armory, is kind of a big deal.

**Comment by pudl** [comment]
@Bawhoppen Evidence storage removal was me, as it didn't serve any purpose. The detective got an evidence closet to replace it, with a dufflebag inside of it. The contraband locker was moved into the sec office so anyone could use it, porta flashers were in the aux. storage. The last part wasn't my fault, though.

**Comment by Lumipharon** [comment]
Contraband locker is pretty useless if any sec officer can loot it, you know.

**Comment by Bawhoppen** [comment]
@pudl  It definitely did serve a purpose, and if you mean 'Nobody ever uses it' thats not grounds to remove something like that. We need the evidence storage to be returned.

**Comment by pudl** [comment]
@Lumipharon The point of the contraband locker in the sec office was specifically so that there could be a communal place for officers to check for cool traitor gear. I don't see a problem with someone keeping the stuff a traitor has on them when they die.

@Bawhoppen It served a purpose of taking up a perfectly good 3x3 space for something more useful. 1 closet was more than enough, 6 is just overkill. If you think that evidence storage needs to be public just put an evidence storage closet in the sec office. Otherwise, it's totally useless. Also, evidence storage is returned by this PR.

**Comment by Bawhoppen** [comment]
I'd still argue with you, but if its returned by this already I'm not going to bother.

**Comment by pudl** [comment]
My design also keeps the evidence storage in tact, so if I end up submitting it remember 2 support ;)

**Comment by Lumipharon** [comment]
If people keep tator gear (which is perfectly fine), then they why would they dump it in the contraband locker?
The locker was specifically for shit not to be looted, but oh well.

**Comment by pudl** [comment]
Well as you can see, my very cool design brings it back in the armory so remember to support it thanks.

**Comment by Steelpoint** [comment]
What armoury? This is Xhuiss armoury design now.

**Comment by pudl** [comment]
@Steelpoint 



I just made the old armory slightly more organized and with the full windows. So it's very nearly pre-Ikarrus armory, we just still have the equipment room in the way blocking a door into the sec office.

**Comment by Miauw62** [comment]
I sort of liked the equipment room-armory connection. Any chance of getting that back?

**Comment by pudl** [comment]
@Miauw62 I'm iffy about it since I don't really see the purpose... there's nothing to really "suit up" in anymore. I think the warden actually passing out equipment it a more interesting/interactive experience. However, if it's literally what decides between the design being accepted or denied, shit I can compromise.

**Comment by Miauw62** [comment]
nah, it's just a suggestion i'm making. multiple breakin routes i guess?
i usually just ask the warden for equipment anyway.

and i'd keep the panes i guess. windoors have 150 health for some reason so with that setup all entrances into the armory have equal amounts of health.

**Comment by pudl** [comment]
I very definitely wanted to kill the panes. Full windows actually make the most secure place on the station feel like the most secure place on the station. If it helps, I can remove the electrification of the windows so you still don't need ygloves to break in.

**Comment by Miauw62** [comment]
if you want to kill the panes, kill the panes.
you either have a choice of smashing the full window and dismantling the electric grilles if you have gloves or taking somewhat longer to smash one of the windoors in that case.

**Pull request merged**
