### PR TITLE
Camera bugs have all upgrades by default.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Camera bugs now have the network, tracking, and sabotage bugs by default.
The upgrading mechanic has been removed, and the uplink description has been modified
Additionally, the tracking menu has a button to disable the camera if you have bugged it.

Camera bugs are probably the most underused traitor item due to how useless they were. Hopefully this will give them much more of a purpose.
TC cost is still 1 currently. Cost modification suggestions welcome.
Also fixes infinite loop that #11493 does.

### CODE REVIEW

**Comment by Xhuis** [comment]
:+1:
I've never seen this used or used it myself outside of surplus crates.

**Comment by Anonus** [comment]
Seems good, I'd say keep it at 1 unless it starts being used a whole lot.

**Comment by ike709** [comment]
Might actually use the camera bug/10
:+1:

**Comment by Core0verload** [comment]
That's what I already did in my codebase.
:+1:

**Comment by duncathan** [comment]
:+1:

**Comment by Miauw62** [comment]
:+1:

**Comment by Miauw62** [comment]
GOD DAMNIT

**Comment by Core0verload** [comment]
Resolve the conflict please.

**Comment by Shadowlight213** [comment]
God fucking damnit, I specifically added the fix so that aran wouldn't need to bother with merge conflicts. I'll get on this once I get back to a pc.

**Comment by Shadowlight213** [comment]
Conflicts fixed

**Comment by Lumipharon** [comment]
camera bugs were actually really useful, in certain situations.

For example setting a trap and remotely watching it, checking to see if your target was in a secluded place (like viro), where sec or borgs are, etc.

Super under used though, good chance.

**Pull request merged**
