### PR TITLE
Brig door timers no longer automatically pixel-shift based on dir

### PR DESCRIPTION
**Pull request by ChangelingRain**
All supported maps already pixel-shift them to the correct spot, and dir isn't used for any of their functions anyway.

> FUN FACT: THIS WAS ADDED BY MPORT ON OCTOBER 22, 2011, AND HAS BEEN IN FOR NEARLY FOUR YEARS.

### CODE REVIEW

**Comment by Anonus** [comment]
Even Ministation pixel-shifts them, this code has no reason to exist(unlike apc shifting which is actually important for a few things)

**Comment by WJohn** [comment]
Finally :+1:

**Comment by Tokiko1** [comment]
Good fix, this used to cause problems with north facing ones.

**Comment by Cheridan** [comment]
mport ruins everything again

**Pull request merged**
