### PR TITLE
Changing messages when using hivelord core 

### PR DESCRIPTION
**Pull request by phil235**
For consistency, you're no longer eating it but applying it on yourself. Taken from @EchoFade 's PR #9417.

### CODE REVIEW

**Comment by pudl** [comment]
no

**Comment by Thunder12345** [comment]
why not

**Comment by WJohn** [comment]
I really wished hivelord cores didn't rot like 10 seconds later. You literally cannot use them for anything other than fixing up the damage a hivelord did to you. It can't be used elsewhere to fight a station menace, it can't even be used for your next fight because those take too long.

**Comment by PKPenguin321** [comment]
nah, hivelords are easy to kill and if you're damage from a basilisk fight then they're essentially a free full heal
but this isn't the PR to discuss that anyways

**Comment by pudl** [comment]
why does everything have to be "applying on yourself" for consistency? the idea of eating the core of the hivelore seems a lot better, and is the reason it's instant healing, unlike a bruise pack or something.

**Comment by duncathan** [comment]
Because muh realisms mean that you can't eat through hardsuit helmets any more.

**Comment by pudl** [comment]
You can't apply bruise packs through hardsuits either.

**Pull request merged**
