### PR TITLE
Random Resprites and Edits Pt.1

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Resprites some stuff.
Some a lot.
Some a little.
Big edits pictured.
Baby edits not.

food/containers:
Yogurt, Cornmeal, Vinegar, Syrup, Worcestershire, Peanut Butter, Food Tray, Egg Box
foodcontainers1

storage/crates:
Mail, Wooden
storagecrates1storagecrates21

service/kitchen:
Ladle, Plastic Fork, Plastic Spoon, Plastic Knife
servicekitchen1

service/bureau:
Filing Cabinet, Employment Cabinet, Tall Cabinet, Chest Drawer
servicebureau1
## Why It's Good For The Game

Working on a list of outdated/slightly-off sprites.
## Changelog
:cl:

image: resprites egg (and more)

/:cl:

### CODE REVIEW

**Review by Wallemations — CHANGES_REQUESTED** [review]
You should probably add "and others" to the changelog but other than that these look great!

egg.

**Comment by Helg2** [comment]
Happiness bubblegum looks cool, but why make it yellow, when iirc it is pink to correspond the pink gum inside?

**Comment by Loafin34** [comment]
and the pink chemical inside

**Comment by Xkallubar** [comment]
Only complaint is that the only difference I can make out with the wooden crate is that it's unnecessarily longer and it looks like a briefcase. Other than that it's literally just the same exact colors and patterns.

**Comment by zoomachina** [comment]
Plastic knife and wooden crate looks really weird

**Comment by CCC23** [comment]
absolutely beautiful the best of resprites so good I wont even notice that they look different you have maintained the soul

**Comment by Twaticus** [comment]
i was the least satisfied with the gum sprites so ill just axe them for now and come back to it later



> Only complaint is that the only difference I can make out with the wooden crate is that it's unnecessarily longer and it looks like a briefcase. Other than that it's literally just the same exact colors and patterns.

the wooden crate was leftover from a previous respriting and didnt match the new crates. i just fixed the shape so it matches the rest, its supposed to look the same otherwise

**Comment by Wallemations** [comment]
Aw I liked the gum but alright, if y say so

**Comment by zoomachina** [comment]
image
It's literally half a mace

**Comment by LSommers** [comment]
My only gripe(s) are that the plastic fork looks more like a spork, and the plastic knife needs smaller serrations (something the OG crunchy sprite managed to get across surprisingly well), other than that this is actually a completely good resprite <sub> unless The J.M. Smucker Company ™️ decides to sue over that peanut butter. </sub>

**Pull request merged**
