### PR TITLE
Removes ambrosia gaia's capability to make self-sustaining trays

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
del: Ambrosia gaia can no longer be used to make trays self-sustaining.
/:cl:

After seeing so many posts about insane ambrosia gaia abuse and botanists completely annihilating the station, plus a little insistence from people bragging about their escapades in coderbus, I decided that this feature was bad. It removed most of the manual labor from Botany, which allowed you to completely dedicate your time to making insanely overpowered plants. The plant's primary purpose is now as a healing plant, as earthsblood remains one of the best healing chemicals in the game. I might also end up adding some chef recipes using it.

### CODE REVIEW

**Comment by lzimann** [comment]
You should probably atomize your pr.

**Comment by Iamgoofball** [comment]
:-1:

this is literally the point of gaia

remove this and you might as well just remove gaia

**Comment by Xhuis** [comment]
Colored lighting will be added later in a bundle with other colored lights.
@Iamgoofball I was originally going to, but it still has use as a healing chemical so I decided to keep it in. I will be adding another function to it later on but for the time being I think it's a big issue.

**Comment by Iamgoofball** [comment]
no, deus covers healing
just remove it NOW or add the function NOW

**Comment by Xhuis** [comment]
Deus heals brute and burn _slower_ than vulgaris. Its benefit is that it covers oxygen and toxin damage, which are negated by the synaptizine doing toxin damage anyway. I'm not going to remove it NOW unless a maintainer asks it of me, and I still want to think on what they will do in the future.

**Comment by Iamgoofball** [comment]
why are you being retarded xhuis dont keep useless shit in

**Comment by uraniummeltdown** [comment]
No way, having to constantly rush from tray to tray was extremely tedious and not fun, gaia made botany fun again. In a game where rounds keep getting shorter nobody has time to juggle nutrients. Gaia is great.

**Comment by bobdobbington** [comment]
This doesn't even nerf the shit people are actually complaining about. All of the bluespace shadowshroom nanner deathnettle kudzu hallway shit is still possible and in fact usually simpler to pull off without gaia. The plant doesn't need to last forever because even if you only top it off with fertilizer and water once it'll shit hundreds of units at max yield and production before it dies. All this is is more bullshit clicking required from the botanist. Once there's hundreds of the thing lying on the tile it doesn't matter if the plant under the enormous pile of shit is still alive or not; you can just seed one of the fruits and get it going again. Bluespace tomato hallway technique existed long before gaia.

**Comment by ShadowDeath6** [comment]
why not nerf the gaia sustain so it makes them grow slower / production speed reduced or something than they would normally so they can choose juggling fertilizer over having their plants be able to spam out more quickly

**Comment by Xhuis** [comment]
Well, you guys have made an impression on me, and I'm not going to shirk what players want in favor of pushing my own ideas. I'm going to close this and I'll deliberate how better to nerf it.

**Pull request closed without merging**
