### PR TITLE
powercreeps the powercrepe

### PR DESCRIPTION
**Pull request by Niknakflak**
It wasn't worth sacrificing the sabre for the crepe, and now it is.  You sacrifice dismemberment chance for higher force and not having a sprite.  Makes it more like the sabre from which it came.

Slather it up!

### CODE REVIEW

**Comment by ma44** [comment]
Don't get addicted to making meme PRs

**Comment by optimumtact** [comment]
Don't get addicted to making meme PRs

**Comment by ShadowDeath6** [comment]
now this is a change I can get behind, esword-tier pastries

**Comment by TechnoAlchemisto** [comment]
not having an inhand sprite is actually a buff

**Comment by PKPenguin321** [comment]
yes nobody said it wasnt

**Comment by TechnoAlchemisto** [comment]
you right

**Comment by kevinz000** [comment]
why doesnt this contain adminorazine/nanites?

**Comment by ma44** [comment]
This needs lemons

**Comment by XDTM** [comment]
Needs high RnD levels

**Comment by ma44** [comment]
It should just increase combat, considering this is made from a Sabre
inb4 "why does science want my sword'

**Comment by AdamElTablawy** [comment]
should allow you to break electric grilles without getting shocked

**Comment by ShadowDeath6** [comment]
>hitting a grille with a pastry will shock you

remove grilleshocking please, unrealistic

**Comment by optimumtact** [comment]
Alright I think this has been open long enough.

**Comment by optimumtact** [comment]
You need an inhand sprite

**Comment by Niknakflak** [comment]
Its coming

**Comment by optimumtact** [comment]
https://file.house/p1IP.mp4

**Pull request merged**
