### PR TITLE
Removes the Antimatter Engine (lol we had an antimatter engine?)

### PR DESCRIPTION
**Pull request by Robustin**
Resolves: https://github.com/tgstation/tgstation/issues/22653

I put one together and this is by far the ugliest, loudest, stupidest most pointless thing I've ever seen. 

And it doesn't work. 

Awful sprites, fucking clanging every 10 seconds, none of the object's names even make sense (who the fuck would think a JAR would be your fuel source? and of course the core is called "control unit"), its horribly intuitive to set up, some of the sprites are missing directions so they go invisible, and uh... oh right it doesn't even work.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@Shadowlight213

**Comment by Magikarpet** [comment]
https://www.youtube.com/watch?v=bWVK7m2S4cg&index=2&list=PLjF1CjJYXr_5HmhqzznTHxjlpEpN3LKIV
http://ss13.moe/wiki/index.php/Antimatter_Engine
https://puu.sh/v4MB5/004e99bb17.jpg
the point of the engine is to charge smeses
it works perfectly fine
the biggest issue it has is that its core shit doesnt update

**Comment by Robustin** [comment]
If /vg/ has made a better version then you can make a PR to bring it back in a better condition.

Watching that video its clear that I failed to make a core, but beyond all the counterintuitive shit I mentioned in my post, using SHIELDING to make the device's CORE by arranging a bunch of boxes in a certain shape and slapping them in a certain order with a multitool just goes beyond the pale of being obtuse. 

Plus as long as the UI is broken, the sprites are broken, and your video doesn't pop up whenever someone buys one, this is just a broken pile of ugly junk.

**Comment by Hatfish** [comment]
None of the engines are intuitive, you don't just get a guide on how to set up the tesla or supermatter engine.  If you can't be assed to learn how it works, then don't complain when you can't figure out how to run it.

**Comment by Robustin** [comment]
They're all pretty intuitive in that the component's purpose is obvious on its face. I don't thinK I ever read the wiki on the supermatter, but it didn't take a genius to figure out that fire = bad.

The shard you can order is less obvious but that was always ordered/kept around as a murderbone device anyway so at least it had a purpose. 

If I can get the UI to actually reflect that its working I will close this, but geez this is a terrible engine regardless.

**Comment by Robustin** [comment]
Alternatively if anyone can post a screenshot of the UI working properly (on the latest revision) I'll close it too since I'm pretty busy right now - either way the referenced issue needs to be resolved.

**Comment by Hatfish** [comment]
antimatter
Here, this is on the latest server revision.  If you'd like any more pics, I'd be happy to provide them.

**Comment by Robustin** [comment]
Fairs fair, its still a fucking godawful engine though. If I couldn't get it working with admin magic I can't fathom how or why anyone else would under normal circumstances. At least we can close the issue.

**Comment by optimumtact** [comment]
Remove it

**Comment by Robustin** [comment]
If its not a fix then it falls under FREEEEEEZE

Right? Plus I gave my word.

**Comment by kevinz000** [comment]
fuck off robustin

**Comment by ShizCalev** [comment]
Would this fall under the current freeze too?

**Pull request closed without merging**
