### PR TITLE
Adds new clown name  - Oranges 

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

:honk: Adds a new fun and wacky name to clowns  - Oranges, After all this name is so funny, and goofy that surely some clown folk should have it as a name! 

## Why It's Good For The Game

Oranges is a classic name for clowns, and who dosnt love clowns? Clearly this should be speed merged before the MIME gets his hands on this!

## Changelog
:cl:
add: new thematic name to clowns, joy for all!
spellcheck: Clearly im a good cat for correcting this missing name from Clown Homeworlds!
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
ok, now this is epic

**Comment by bigfatbananacyclops** [comment]
hes calling oranges a clown

**Comment by Whoneedspacee** [comment]
GET IT HAHA

**Comment by bobbahbrown** [comment]
speeedmerge

**Comment by actioninja** [comment]
ok, now this is epic

**Comment by MrFluffster** [comment]
a real pro gamer move from orange man

**Comment by ATH1909** [comment]
based orange man

**Pull request merged**
