### PR TITLE
Modifies the moodlet colors slightly

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Makes the moodlets between neutral and happy_1 use the info span instead of the gray span
## Why It's Good For The Game
You can actually tell whether your character likes/dislikes the lower-effect moodlets, and act accordingly. 
## Changelog
:cl:
qol: slight positive moodlets use a different color to slight negative ones
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
PICTURES???

**Comment by timothymtorres** [comment]
I don't think this is necessary.  Right now there are 5 colors:  Bold green, green, grey, red, and bold red.  The grey color is supposed to be neutral moods that barely affect anything (mood range from -3 to +3)  You change it so that grey is now split into grey for (-3 to 0) and blue for (0 to +3).

If anything, you should just remove grey and give green for any positive mood and red for any negative mood.

**Comment by etherware-novice** [comment]
well its a blue-gray for slight positive moodlets, so you still had the "gray zone" while being able to differentiate which one is good

**Comment by etherware-novice** [comment]
@SuperNovaa41 please review

**Comment by Mothblocks** [comment]
Merge from upstream

**Pull request merged**
