### PR TITLE
Removes Random AI EMP shuttle calls

### PR DESCRIPTION
**Pull request by Incoming5643**
Hello I just saw this mechanic for the first time in like three years and it's terrible

### CODE REVIEW

**Comment by Iamgoofball** [comment]
thanks [REDACTED]

**Comment by optimumtact** [comment]
:-1: if you never saw it then it can't be that bad

**Comment by Anonmare** [comment]
But it's fun tbh fam

**Comment by Incoming5643** [comment]
If [REDACTED] is here to stay it's going to become much more common

**Comment by Shadowlight213** [comment]
@Incoming5643 you didn't see it because it was only fixed recently. It used to not work. That said, :-1: on the removal.

**Comment by KorPhaeron** [comment]
The things that can EMP an AI are the kinds of things that usually warrant evacuation

**Comment by Iamgoofball** [comment]
okay round over

the tesla ball zapped the AI, calling emp_act, killing it

**Comment by Incoming5643** [comment]
"Whoops the round has randomly decided to end!" is not good game design.

**Comment by optimumtact** [comment]
What you can't recall it?

**Comment by Shadowlight213** [comment]
@incoming5643 people can just recall you know. Why not remove the auto call if the consoles and the AI are dead too. Then it will never be called, fulfilling your dream!

**Comment by Incoming5643** [comment]
The thing about recalls is that I've learned to stop expecting people to do recalls even if absolutely nothing is wrong.

**Comment by Shadowlight213** [comment]
@incoming5643 since tesla pretty much instakills and isn't as obvious as the singulo, it's gonna be much harder for people to call the shuttle at all. While calling the shuttle may not be fun for you, having a scenario where no one can call it isn't fun for the whole round. You can't even theoretically destroy the tesla like you can the singulo.

**Comment by Jazaen** [comment]
*Cries malf tears* I was the AI. Not that that mattered, from what I have seen no one fixed the plasma leak I did before tesla came for me. Though most of the time if EMP hits the AI it is already dead from the EMP.

**Comment by Incoming5643** [comment]
To be clear here what happened was the malf AI was shocked and the auto call proced, then the memeball proceeded to fuck off into space for the rest of the round. It only ever made it back to the station due to admins var editing there. There was no real reason to call the shuttle.

**Comment by bgobandit** [comment]
just disable it on malf only

ezpz

**Comment by Shadowlight213** [comment]
So due to an edge case of it fucking off for a round you're removing the call completely? Unlike singulo, tesla can't starve to death and just keeps getting bigger. With space torus, the chance for it to come back is pretty high.
Also you removed the chance to jump the AI's camera back to its core.

**Comment by Dorsisdwarf** [comment]
It's only a 25% chance anyway

This means this is only ever gonna be a problem with the rounds when:

1) we have a tesla
2) the tesla gets free
3) the tesla gets the AI
4) the 25% chance procs
5) the tesla ball fucks off
6) there are no other antags to do anything shuttleworthy
7) noobdy recalls

**Comment by Iamgoofball** [comment]
@Dorsisdwarf literally happened in that order

**Comment by Dorsisdwarf** [comment]
Oh boy one round ended when it shouldn't have because the crew was retarded repeatedly and had a long run of bad luck.

better remove features!!!1!

**Comment by Incoming5643** [comment]
EMP_acts can continue to be called on the AI's corpse I believe, the chance to occur doesn't matter too much if it gets hit 50 times.

**Comment by Shadowlight213** [comment]
The obvious solution is to have the shuttle require a code to call. The code is split into 3 parts, the pieces of which are placed at the end of 3 insanely difficult procedurally generated away missions. Said code is also only valid for 2 minutes and re-randomizes after that time. Also inputting the code incorrectly invalidates that iteration. Vote restart is also disabled and server restart button is limited to headmins/host.
Then incoming shall be happy.

**Comment by Incoming5643** [comment]
All these people veraciously defending a cruddy RNG feature <a href="https://github.com/tgstation/-tg-station/commit/a697428db741093f890be9f7827199d8d278b138" from early 2011</a> that no one even remembered until today.

Sometimes I wonder if y'all just like to argue for the sake of it.

**Comment by Shadowlight213** [comment]
@incoming5643 incorrect I remembered it enough to make an issue report for it being broken and someone else remembered it enough to fix it.
I've also used it as a ghetto shuttle caller by tossing a dead AI into the singulo chamber so it gets constantly emped.

**Pull request closed without merging**
