### PR TITLE
Storage implant techweb design

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Storage implants can now be built in protolathes if the Unregulated Bluespace node has been researched.
/:cl:

Requires #41339 to be complete, since it has the aforementioned node.

### CODE REVIEW

**Comment by HydroFloric** [comment]
God no please. Theres a reason they are tator only.

**Comment by ma44** [comment]
>Cuff, strip and perma that one scientist
>Scientist has an entire armory, all the tools in the world and chems for breaking out

**Comment by XDTM** [comment]
They require tator tech, end-tier materials and a medium-high techweb node to produce, so it's not exactly free; maybe limiting it to one or two implants per person would be more balanced though.

**Comment by drderp3635** [comment]
Maybe if you heavily nerfed it it could work but as is, just no

**Comment by HydroFloric** [comment]
Tator tech can be cheesed easily unless it was fixed.

**Comment by XDTM** [comment]
Now the techweb version no longer stacks.

**Comment by BeeSting12** [comment]
Traitor items in tech webs sucks, unique items like the bluespace deleter are better.

**Comment by XDTM** [comment]
i can agree about unique items, although i have a soft spot for trying to make as many items as possible obtainable in some form

**Comment by XDTM** [comment]
I'll just make some more original gadgets instead.

**Pull request closed without merging**
