### PR TITLE
Patch-related tweaks

### PR DESCRIPTION
**Pull request by pudl**
This update tweaks patches very slightly.

Instead of patches, like pills, holding 50 units, they now hold 40. This is a slight nerf because they are currently better than pills in every way. Although only some chemicals are touch-based, every chemical has some effect from ingestion. This means that making a patch of an ingestion based chemical is favorable to a pill, because patches apply both ingest and touch, and work when wearing a mask. For reference, a 50 unit patch of silver sulf heals 150 damage, a 40 unit patch would heal 130.

Pre-spawned brute and burn patches now only hold 20 units. This is because a single 50 unit burn/brute patch was capable of taking you from slightly above crit to full health. A 40 unit brute/burn patch could take you from ~20 to 100. You can still create a patch of this volume, of course. Silver sulf patches currently heal 150 damage, they will now heal 60.

Patches now have three different sprites. One for normally created patches (similar to what we have now), one for pre-spawned brute patches, and another for pre-spawned burn patches. This should help tell the difference when looking through a medical kit.
In order, default, brute, then burn. Credit to @Steelpoint for this idea.
default
brute
burn
In past PRs I have received complaints about the original size of these patches, so they have been edited.

As a very small adjustment, the messages for ingesting styptic and silver sulf no longer tell you to put them on as a patch or splash them on, because A. no other chemical gives you a hint when you don't use it to the best of its abilities and B. you can't splash a beaker onto yourself, only other people.
Silver sulf no longer makes you scream, only styptic.

@Iamgoofball has, several times, approved of these changes.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Let's not nerf patches please, people will start complaining that goonchem is underpowered again.

**Comment by pudl** [comment]
@Iamgoofball Every single time I have attempted this change, you have said "No", I talked to you about it on steam, and you said it was okay. Every time. Want to do it again?

**Comment by Razharas** [comment]
Id prefer patches actually require you to take off your full space suit as a nerf

**Comment by pudl** [comment]
@Razharas Goofball and everyone else said that was a bad idea when it was posted. For example, when you're floating through space in a space suit, there will be absolutely no way to heal without taking oxygen damage.

**Comment by pudl** [comment]
For reference, everyone, a 50 unit patch of silver sulf would heal 50 units of damage on touch, and another 100 damage over 50 seconds. 150 in total. A 40 unit patch would heal 40 damage initially, and 80 damage over time. 120 in total. The 20 unit patches included in medkits (in this PR) would heal 20 damage initially, and 40 over time. 60 in total. I think 60 is a perfectly fine amount, and if people think that makes medkits underpowered, why not get some full patches?

**Comment by pudl** [comment]
After further research, a 20 unit patch of silver sulf in Goon is 64 damage exactly. The reason that their patches heal 4 more damage is because our values are technically incorrect. However, a 4 damage difference isn't very big, so these patches are near accurate.
Considering our chemicals process once per tick again, we can't get the same values of healing as Goon without going or 2 or 3 decimal places. So we can't be truly, 100% accurate.

**Comment by Iamgoofball** [comment]
Well, alright then.

@Razharas Yeah, no. If anything we need to revert the stupid pill code for not eating with masks on, I'm like 99% certain paprika added that to shoehorn in mask flipping

**Comment by freerealestate** [comment]
Contrast on the burn patch cross should be upped.

**Comment by pudl** [comment]
@freerealestate I know, right? I wish we could just use the red cross.

**Comment by pudl** [comment]
I'd like this to be merged before merge conflicts come up.

**Comment by pudl** [comment]
There's currently a PR that conflicts with this, if it gets merged first I'm not gonna be a happy camper.

**Comment by Iamgoofball** [comment]
@pudl why don't you just fix the conflicts

it's super easy

**Comment by pudl** [comment]
@Iamgoofball No.

**Comment by Iamgoofball** [comment]
Why

**Pull request closed without merging**
