### PR TITLE
fix orm power unmove

### LINKED ISSUE #14086: Issues with ore redemption machine and losing power
You sometimes cannot deconstruct the ore redemption machine if the power is offline. Power sink in this case, and reproduced by turning the APC off manually, but when I tried setting stat to 2 manually in the thunderdome, it worked fine. Dunno what's up here. The screwdriver just didn't give any message. Furthermore, if it loses power with the panel unscrewed, it gets the "unpowered" sprite but with the panel closed. Not sure of the actual status of the panel however.

Thanks a lot to Polyp on Sybil for reporting and testing this.

### LINKED ISSUE #18167: The ORM cannot be interacted with if it is depowered.
It cannot be unbolted, deconstructed, or even hit when it is depowered.  It is effectively an immovable, unbreakable object until power is restored to the area.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Fixes #18167 
Fixes #14086

### CODE REVIEW

**Comment by Razharas** [comment]
>Depowered means uninteractable memes are still in the machine code

:sob:

**Comment by Razharas** [comment]
ALso see its not that hard rather simple issue and its fixed now
Now get to work on another one
Hurry hurry! Before someone steals all the bugs!

**Comment by LatD** [comment]
Also fixes #14086, it's the same issue

**Comment by Iamgoofball** [comment]
OH FUCK 2 TOKENS 1 PR

**Comment by Niknakflak** [comment]
#18122 
Dupe issues shouldn't count as two tokens? @Cheridan  ???

**Pull request merged**
