### PR TITLE
Changes the sprite of the supermatter's electricity arcs

### PR DESCRIPTION
**Pull request by SteelSlayer**
## About The Pull Request
This changes the sprite of the supermatter's shocking arcs to more electricity-looking arcs.

I really dislike the current SM arc sprite, it looks like it was stretched outwards unnaturally, and has a hard edge at the end of it, which is very jarring to look at.

Demo video: https://streamable.com/xxuuq

GIF

smarcsmorewhite

## Changelog
:cl:
imageadd: Changes the look of the supermatter's electricity arcs to appear more like electricity.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Maybe improve the supermatter lightning sprite instead of just using normal lightning arcs. Feels kinda lazy and I honestly prefer supermatter lightning having it's unique sprite, even if it isn't the most beautiful thing out there

**Comment by XDTM** [comment]
Maybe even just a yellow lightning instead of white

**Comment by SteelSlayer** [comment]
Yeah I'm no spriter, which is why I just tried to do a replacement. But I'll take a crack at coming up with something that hopefully looks cool.

**Comment by SteelSlayer** [comment]
Ok I attempted to make a new cool looking sprite, and updated the original post with pictures. Let me know what you think.

**Comment by wesoda25** [comment]
So glad someone finally made this PR

**Comment by trollbreeder** [comment]
Wow, a codersprite that doesn't look dogshite? NICE!

**Comment by ArcaneMusic** [comment]
_The SM was SHOCKING last round_

Looks dope. Much less issues with the size of the beam, unlike the old sprite. Very clean.

**Comment by LemonInTheDark** [comment]
Good change, glad the sprites are different as they behave differently, blessed codersprites.

**Review by kriskog — APPROVED** [review]
The word tinsel was thrown around, but I think it at least looks better than the old ones.

**Pull request merged**
