### PR TITLE
The Detective is now Service instead of Security, much like the Lawyer.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

The Detective is now Service instead of Security, much like the Lawyer.

## Why It's Good For The Game

"bro detective isn't security bro thats why they shouldn't have any ranged non-lethal option at all"

let's find out what people think of this idea then

if the Detective isn't supposed to be making arrests, then they should be treated the same as the other person in Security who's not supposed to be making arrests, the Lawyer. As such, I've made them a support Service/Security hybrid job like the Lawyer is with emphasis on Service.

## Changelog

:cl:
balance: The Detective is now Service instead of Security, much like the Lawyer.
balance: The Detective has lost his Brig access, and is now on par with a Lawyer.
balance: The Detective has lost his Mindshield because he's not a redshirt anymore.
balance: The Detective is no longer issued a baton since he's not supposed to be making arrests.
balance: The Detective is now capable of rolling for antagonist.
balance: The Detective's revolver is now loaded with rubbers to start with, as they don't need lethals for self defense. See: The Bartender's shotgun being loaded with rubber.
balance: The Detective's locker has had its' security gear removed from it.
/:cl:

### CODE REVIEW

**Comment by Pepsilawn** [comment]
Revolver is still in? Not sure they would be the most balanced antagonist.

**Comment by Iamgoofball** [comment]
@Pepsilawn The Bartender spawns with a shotgun and the CMO spawns with a chemical weapons plant.

**Comment by jughu** [comment]
Merge this and make goofball gbp go ibto -

**Comment by jughu** [comment]
> Revolver is still in? Not sure they would be the most balanced antagonist.

Doesnt matter i can just buy 357. as any antag and blast your ass

**Comment by EricZilla** [comment]
I think this is probably a good change, even if it wasn't made with the best reasons
(bad joke incoming)
Maintainers even if you wanna close this at least test merge it so we can piss off half the players for a few days over nothing lmao

**Comment by jughu** [comment]
We had a variant of like detectives roll antag before, where they still were mindshielded and part of security i think this is a better variant and what detectives really are in reality

Then people probaly will say that he just will validhunt with the gun but then you have paramedics with syringe guns and bartender with guns so who cares

Best pr

**Comment by Burgermancoding** [comment]
It's more badass that he has actual bullets, and I think the detective should keep his police baton for self defence, the baton isn't really the thing that should stop him from making arrests, it's the cuffs or lack thereof.

**Comment by SuperNovaa41** [comment]
your why its good for the game doesn't justify your change at all, it just reads like you moved an argument you were having from discord to github

**Comment by Farquaar** [comment]
Is your long-term goal to remove security as a department? You've already attempted to remove department guards from sec. You're now attempting to remove detective from sec. What gives?

**Comment by wesoda25** [comment]
I don't understand why you're taking lethals from them

**Review by Watermelon914 — CHANGES_REQUESTED** [review]
Can you write a design doc explaining your justification as to what is changing about detective, what the goals and non-goals of detective are and why you are making this change?
You haven't really given it justification other than 'detectives shouldn't be making arrests so they shouldn't be security', I don't find that strong enough justification for detective to not be security. Adding a private detective role sounds fine, but there's a reason detectives are a branch in actual police forces and it's because you can't rely on freelancers to find out who committed a crime.

**Comment by optimumtact** [comment]
this can be closed at the 24 hour mark, I don't think there's any value to this change.

**Comment by iprice** [comment]
Is the warden supposed to be making arrests or does the "logic" here mean that will be moved to service too then?

**Comment by thgvr** [comment]
ah sweet a schizo thread

**Comment by cacogen** [comment]
>"bro detective isn't security bro thats why they shouldn't have any ranged non-lethal option at all"

Your [other PR](https://github.com/tgstation/tgstation/pull/63855) is still open, and it looks like it'll be merged. So what is this in protest to?

**Comment by Iamgoofball** [comment]
@cacogen the PRs were made at the same time maybe consider looking at timestamps sometime

**Comment by SoreYew** [comment]
Then why did you make a PR that would make ammo accessible to a location that if the other PR merged, they couldn't access anyway?

**Comment by squi1-rasb** [comment]
This seems likr a pr made purely out of spite. Detective shouldnt be making arrests, they should be helping security find the person to arrest. The revolver is purely for self defense. Security would just employ the detective anyways if moved to service, i dont see a reason for this change

**Comment by tralezab** [comment]
well, it was interesting to think about

**Comment by Twaticus** [comment]
nah it really wasnt

**Comment by cacogen** [comment]
@Iamgoofball

so what prompted this then

**Pull request closed without merging**
