### PR TITLE
Liar liar pantsu on fiar

### PR DESCRIPTION
**Pull request by ghost**
Ports baymed

Removes goonchem

Adds pie launchers

Adds book-stocker mechs

### CODE REVIEW

**Comment by Razharas** [comment]
Didnt it lag last time?

**Comment by paprka** [comment]
That's so 'maintainer that doesn't even look at the line changes or code'

**Comment by Fox-McCloud** [comment]
just...lol.

**Comment by hornygranny** [comment]
i just got tricked

**Comment by Niknakflak** [comment]
Nice

**Comment by ike709** [comment]
false advertising

**Comment by Razharas** [comment]
Fuck i cant type

**Comment by Cheridan** [comment]
:fire: :jeans: :fire:    :fire_engine: :hankey:

**Comment by Miauw62** [comment]
>not adding ayy lmao

;-;

**Comment by paprka** [comment]
miauw i did that ages ago but you never merged it it's your own fault

anyway this pr served its purpose

**Comment by Thunder12345** [comment]
The fire brigade have finally extinguished the burning pantsu

**Comment by Miauw62** [comment]
paprka that pr also contained other memes that weren't even 1/10th as dank as ayy lmao

**Pull request closed without merging**
