### PR TITLE
Orbit refactor + features part dos: Icons, health bars.

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Yes, some may call it being indecisive, however,,,,
okay maybe they are correct. But I had a neat idea and I wanted to go with it.

This PR changes the orbit UI to more obviously display the new data from the backend, like health and job titles.
To keep this from being too confusing, I separated the orbiter heat map function into a toggleable button.

Cleaned up the UI and code a bit.

Look:
CFWoAQfxG7
Healthbars are default. I toggle heat map here, which highlights buttons by orbiter #.

## Why It's Good For The Game
More interactive orbit experience, easier to read UI.

## Changelog

:cl:
add: Orbit UI buttons now reflect health and show job icons
add: ID trims now have an orbit icon variable for its display on the observer menu
code: Orbit UI heatmap is now toggleable with health (top button)
fix: Sorting for disguised names should work better.
refactor: Refactored Orbit into a folder.
/:cl:

### CODE REVIEW

**Comment by msgerbs** [comment]
Does it show the health when hovered? I worry that it won't immediately be obvious that the color of the box is their health level.

**Comment by jlsnow301** [comment]
> Does it show the health when hovered? I worry that it won't immediately be obvious that the color of the box is their health level. Other than that I love this!

yes, it still shows this, but now as percentage rather than "good" etc

**Comment by JohnFulpWillard** [comment]
is there a way to make this modular for downstreams? Making the icon a var on the job?

**Comment by jlsnow301** [comment]
> is there a way to make this modular for downstreams? Making the icon a var on the job?

yes!

**Comment by jlsnow301** [comment]
This is done

**Pull request merged**
