### PR TITLE
Gives AI radios loudmode

### PR DESCRIPTION
**Pull request by silicons**
Now I can yell about human harm in bold!

### CODE REVIEW

**Comment by juanototo2** [comment]
# ASS BLAST USA!!

**Comment by Cyberboss** [comment]
Can you even access the menu for the AI radio?

**Comment by Anonmare** [comment]
You can, it's in the AI Commands tab under Subspace Transciever

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
@kevinz000 I swear to god I'll close your next PR with an Update XXX.dm commit

**Pull request merged**
