### PR TITLE
adds syringe and surgical drapes designs to medlathe

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
tweak: surgical drapes and syringes can be printed by medlathe
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Okay that's pretty cool i admit, but i always thought they were made out of cloth. :+1: 

[Same for surgical aprons](https://github.com/tgstation/tgstation/blob/8322ba19d8022345eb76f34aa6ea165bc89817a9/code/modules/clothing/suits/jobs.dm#L138) or outside of the scope of the PR for you?

**Comment by Tlaltecuhtli** [comment]
surgical apron is in the vendrobe

**Comment by dr-bee** [comment]
Thank goodness for this PR. Surgical drapes can be put into medical belts while bedsheets cannot. So you can carry around a full surgical kit in a belt without stealing the one set of drapes.

**Comment by ATH1909** [comment]
> Thank goodness for this PR. Surgical drapes can be put into medical belts while bedsheets cannot. So you can carry around a full surgical kit in a belt without stealing the one set of drapes.

Just wear the bedsheet in your neck slot.

**Comment by ExcessiveUseOfCobblestone** [comment]
was there even a source for medical drapes? I don't even think cargo has a replacement.

Then again I don't think you're actually punished for using bedsheets so 🤷‍♂

**Comment by Tlaltecuhtli** [comment]
if you wear the bedsheet then you cant wear the stethoscope

**Comment by ExcessiveUseOfCobblestone** [comment]
> if you wear the bedsheet then you cant wear the stethoscope

this is the mark of a medical player

**Pull request merged**
