### PR TITLE
Gibbing a Security Officer produces Pig Meat

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Ports the applicable half of https://github.com/Bubberstation/Bubberstation/pull/526 here and makes it apply to every member of security, sans Detective.

## Why It's Good For The Game

Lore accuracy is a very good thing.

## Changelog
:cl: Cursor
add: Security Officers are now Haram.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
If we are doing this then we should do it properly. This should be a property of a trait on the mob rather than checking a list of jobs, and the trait should probably be applied by their liver or something.

**Comment by wesoda25** [comment]
Screenshot 2024-02-05 at 10 22 48 AM

**Comment by optimumtact** [comment]
This doesn't make sense as a all the time trait, might work as either an event day, or a station trait.

**Comment by EricZilla** [comment]
I think you could have just have them drop human meat that is labeled pig meat for the same effect but none of the lore issues

**Comment by TheVekter** [comment]
Based.

Can you make them drop a donut like 1% of the time?

**Comment by K4rlox** [comment]
https://github.com/tgstation/tgstation/assets/118483925/ff5a5fa7-999b-4662-9310-ad4a7d885f4a

**Comment by Time-Green** [comment]
Very funny but it’s a little *too* in your face. Would be better if it was rare or date locked or something

**Comment by MrMelbert** [comment]
The problem with time locking or trait locking this is that then it requires the stars align for this to be active and a seccie to be placed through the gibber, which I don't think is very likely.

**Comment by TheVekter** [comment]
> Very funny but it’s a little _too_ in your face. Would be better if it was rare or date locked or something

Would it be more acceptable if it was a random chance, like 25% odds for it to replace one piece of human meat with pig meat?

**Comment by Time-Green** [comment]
> > Very funny but it’s a little _too_ in your face. Would be better if it was rare or date locked or something
> 
> Would it be more acceptable if it was a random chance, like 25% odds for it to replace one piece of human meat with pig meat?

Yeah that seems fine

**Comment by TheVekter** [comment]
@theselfish You heard the tomato creature.

**Comment by theselfish** [comment]
> @theselfish You heard the tomato creature.

I did, sadly.

Gonna be honest. I'm unsure how I'd make it into a % chance.
Even if I'd like it to be 40%. As we all know, 40% of Cops enjoy playing on Sybil. Google 40% Cops for more info.

**Comment by theselfish** [comment]
@Time-Green Would you take 40%?

**Comment by Time-Green** [comment]
I’m not gonna fight you on a 15% difference, even if it would be funny

**Pull request merged**
