### PR TITLE
remove dead code

### PR DESCRIPTION
**Pull request by optimumtact**
Alway delete comments, safer communities together

### CODE REVIEW

**Comment by Miauw62** [comment]
it literally says why its preserved

**Comment by Cheridan** [comment]
sorry miauw but showcasing this bad code off is bullying and we should all aspire to be greater

**Comment by bgobandit** [comment]
it's not like it isn't still in the history

**Comment by Miauw62** [comment]
people dont look at the history

**Comment by Aranclanos** [comment]
I'll summarize the history for you, old coders were bad. That's it.

**Comment by optimumtact** [comment]
there's' no need to tell us something we already know

**Comment by optimumtact** [comment]
the comment in the code, not aran's comment

**Comment by Cheridan** [comment]
aran in charge of destroying /tg/station artifacts

**Comment by optimumtact** [comment]
If only we could send a pull to destroy cheridan

**Pull request merged**
