### PR TITLE
Adds comments to handcuffs.dm

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Added comments to handcuffs.dm.
Also a few very minor readability improvements, including moving some classes around the file.
Includes changes made to handcuffs.dm in #58456.

## Why It's Good For The Game
Comments, readability.

## Changelog
Not player-facing.

### CODE REVIEW

**Comment by celotajstg** [comment]
Looks nice, though I would like to ask you to re-check your commit name and email settings, as they don't match your GitHub user.

**Comment by ExcessiveUseOfCobblestone** [comment]
No CL please

**Comment by interestingusernam3** [comment]
>Looks nice, though I would like to ask you to re-check your commit name and email settings, as they don't match your GitHub user.

I don't know what happened with the commit name. Also, email settings?

**Comment by interestingusernam3** [comment]
Do you mean the "invalid-email-adress" in commit history or something else? Does that something else leak my personal info?

**Comment by interestingusernam3** [comment]
>No CL please unless there are player-end changes

CL removed.

**Comment by Fikou** [comment]
these autodoc comments for handcuff subtypes suck and are unneeded 👎

**Comment by interestingusernam3** [comment]
>these autodoc comments for handcuff subtypes suck and are unneeded 👎

"A class must always be autodocumented, and all public functions must be documented"

**Comment by ATH1909** [comment]
a true hero

**Comment by Fikou** [comment]
> > these autodoc comments for handcuff subtypes suck and are unneeded 👎
> 
> "A class must always be autodocumented, and all public functions must be documented"

its bloat and makes readability worse, and the expanded descriptions are completely useless you just use synonyms for them

**Comment by interestingusernam3** [comment]
Will not change unless explicitly ordered to make an exception for those by a maintainer.

**Comment by interestingusernam3** [comment]
Ok the cablecuff variant ones don't repeat themselves anymore.

**Pull request merged**
