### PR TITLE
Airlock wires are random (within a limited pool)

### PR DESCRIPTION
**Pull request by Rohesie**
A little test on how the graytide handles having no guarantees of hacking without insulated or a station blueprint.
Instead of all airlocks sharing the same wires, we store up to ten (or more if you change the define) cable color variations. Should probably be enough to give the random airlock hacker pause, without wasting too much memory.
The CE blueprints work as normal if you are checking the airlock wires, but its directory only shows the static ones. Don't think it would be very useful adding all the possible variations.

## Changelog
:cl:
balance: The chance of that "red is bolt" pda message you get at the start of round, from a random gray, to be truthful is reduced to 10% of its former value.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
Linter is having a hiccup, but this should work.

**Comment by carlarctg** [comment]
hacking needs to be overhauled but this isn't the way to do ir

you know this doesn't only affect tiders right? it affects traitors, fighting against malf ai, rogue borgs, airlock deconstruction, etcetera

i don't want to get spotted as a traitor by the ai and having to fumble what the bolt wire is while i have to cut-mend the test wire, hope for no shock, and find bolt all the while security is running at full speed to catch me

this makes ais nigh omnipotent with doors and thats not okay

**Comment by SynnGraffkin** [comment]
This buffs Malf AI during the Antag freeze.

**Comment by Detective-Google** [comment]
This is actually quite a problem for engineers trying to deconstruct airlocks

**Comment by Qustinnus** [comment]
hacking shouldn't be easy indtead

**Comment by Qustinnus** [comment]
Fuck misclick AAAA

**Comment by Shadowflame909** [comment]
If this PR gets merged I hope the RCD removal from autolathes doesn't.

Only two ways to get past r-walled rooms without basically already having captain access

**Comment by dee-dubya** [comment]
Absolute madman. I thought this was a pipe dream when I suggested it, not that it'd have a functioning PR within a couple hours.

Overall a good change that'll combat the rampant greytide. Hacking doors is so goddamn fast, easy, and common now most people don't even give a shit that you're doing it.


> you know this doesn't only affect tiders right? it affects traitors
> i don't want to get spotted as a traitor by the ai and having to fumble what the bolt wire is while i have to cut-mend the test wire, hope for no shock, and find bolt all the while security is running at full speed to catch me
Buy an emag. Or black gloves. Or just risk the hack since you were too greedy and spent all your TC on other shit rather than the shit you needed.

>fighting against malf ai, rogue borgs,
Good. Malf AI is already kind of weak at the moment. Besides, if shit has hit the fan that hard, grab the fireaxes or make some chainsaws.

>airlock deconstruction
>This is actually quite a problem for engineers trying to deconstruct airlocks
Any job that's supposed to be doing this has insuls and possibly even the blueprints, so this change will hardly affect them.

>This buffs Malf AI during the Antag freeze.
Cobbmed buffed all traitor modes during the antag freeze. You can't salt away a PR you don't like because of it indirectly affecting an unrelated(and not hardline, see clock cult) mandate.

**Comment by zxaber** [comment]
Emag doesn't help against bolted airlocks, and some antags don't get TC.

Malf AI is weak at the moment, but this isn't a meaningful buff (and I disagree with that particular argument). If you don't want someone to hack a particular door, you just bolt it and disable the APC's environment circuit. This change doesn't really affect that except by possibly giving AIs more time to react.

My personal argument against this is that it removes most of the whole point of hackable doors in the first place. If we're gonna have ten different templates for airlocks, why not just make _every_ door random, like borg wires are (and if we're going that direction, we should re-work the door hacking so that you can safely probe each wire with one tool, and then use another tool to actually disable the wire once you get the clue you're looking for).

**Comment by anconfuzedrock** [comment]
This is absurd, now I can't do ANYTHING with signallers as engi. Don't act like the CE getting an exclusive set of blueprints is a fix. Hacking isn't even a good way to get into places! the door closes after a few seconds and you have to dick with it again but harder, you're immediately visible, it opens a possibly laggy window... Plenty of ways are easier.

**Comment by PKPenguin321** [comment]
>Emag doesn't help against bolted airlocks, and some antags don't get TC.

most* antags, as in the vast majority

**Comment by Rohesie** [comment]
> My personal argument against this is that it removes most of the whole point of hackable doors in the first place. If we're gonna have ten different templates for airlocks, why not just make _every_ door random, like borg wires are (and if we're going that direction, we should re-work the door hacking so that you can safely probe each wire with one tool, and then use another tool to actually disable the wire once you get the clue you're looking for).

There's 10 templates merely to reduce memory weight, having less lists when this amount does the job. Functionally it should be the same as every airlock being random.
As for safe probing, that's what the blueprints and insulated gloves are for.

Hacking doors is a way to bypass an access restriction. You can do this in several ways:
* Spending time, with a screwdriver, crowbar and multitool (wirecutter if you are lucky), perhaps some burn meds if necessary.
* Having insulated gloves.
* Having blueprints.
* Having a door remote.
* Having a subservient or compliant silicon.
* Destroying the door or bypassing it.

All this does is remove the certainty of bypassing any unbolted door in seconds with only a screwdriver, wire-cutter and crowbar.


> This is absurd, now I can't do ANYTHING with signallers as engi. Don't act like the CE getting an exclusive set of blueprints is a fix. Hacking isn't even a good way to get into places! the door closes after a few seconds and you have to dick with it again but harder, you're immediately visible, it opens a possibly laggy window... Plenty of ways are easier.

I don't understand how signalers are affected here. Could you explain?

The door does close if you don't bolt it open. If you are hacking without proper tools there's downsides, that's how it goes. It's the point of having an access-restricted door facing a person without access nor proper tools.

**Comment by Fhaxaris** [comment]
If you practice enough, a door can be bolted open from closed in about 5 seconds. If you think that hacking is too quick, the solution is DEFINITELY NOT adding randomness to a mechanic that is extremely important to the game (for some players) and is also consistent in its behavior throughout the round.

If you want to slow the tide, you could make it take time. Just a small amount based on tool speed would work.
You could also consider splitting it up by department. Then you would be able to figure out one door and apply it to the rest.

> I don't understand how signalers are affected here. Could you explain?

You have to test each door individually before you are able to put a signaler on it.

**Comment by zxaber** [comment]
>As for safe probing, that's what the blueprints and insulated gloves are for.

We already have people borderline murdering each other for insuls, I don't think they need to be made more valuable.

Change the interactions of the multitool with door wires. Make pulsing a power wire cause a message like "The [src]'s test light flickers". Do similar with all other wires. If you want to add to it a bit, make the two dummy wires throw out a line randomly chosen from the actual wire pulses. This makes door hacking take substantially longer than the current system, without making the hacker risk burn damage every time they try to break into something.

**Comment by Rohesie** [comment]
> > I don't understand how signalers are affected here. Could you explain?
> 
> You have to test each door individually before you are able to put a signaler on it.

That doesn't break signalers. It just breaks placing signalers on a large amount of doors without spending a little time on each, and while having no blueprints.

> Change the interactions of the multitool with door wires. Make pulsing a power wire cause a message like "The [src]'s test light flickers". Do similar with all other wires. If you want to add to it a bit, make the two dummy wires throw out a line randomly chosen from the actual wire pulses. This makes door hacking take substantially longer than the current system, without making the hacker risk burn damage every time they try to break into something.

That makes hacking the first door a tiny bit more difficult. Then the results get broadcasted and the situation remains unchanged. Not really a proper solution.


All in all this was never expected to be a popular PR. It's a nerf and makes hacking as a non-engineer, or mass-hacking, somewhat harder. But I believe it's positive for the long-term health of the server.

You can extend the blueprints functionality, give engineers (and/or antags) skills to more easily identify wires, expand access, buff traitor items, and plenty more if you want to prevent the doors from being obstacles. But the current status is extremely gamey. People are just used to starting a round, testing one door and broadcasting the results. There's zero challenge to hacking and access means very little. And while this doesn't fully solve that, it's a step in the right direction.

**Comment by zxaber** [comment]
>That makes hacking the first door a tiny bit more difficult. Then the results get broadcasted and the situation remains unchanged. Not really a proper solution.

I meant the multitool probing changes in addition to the rest of this PR. It's how borgs work; every borg has a different arrangement of wires (and wire colors), and you can use a multitool to get clues and figure them out.

**Comment by PKPenguin321** [comment]
Question about this PR, do the ten airlock types have any unique tell as to which of the ten types they are?

**Comment by OdoSendai** [comment]
Fixes a problem that doesn't need to be fixed.  People being able to quickly hack into places they aren't authorized for is a fundamental part of how the game currently functions.  People breaking into places generates conflict and already has downsides compared to obtaining legitimate access or using more specialized methods (such as emag).

This is a significant nerf to player movement and is a negative Quality of Life change.  Getting stuck in a room and having to hack your way out is something that happens decently often, and if hacking is made unfeasible people are gonna spend more time spamming ';ai open door lemme out reee' than they already do.  Players being able to move around the station (and circumvent access restrictions) allows for them to use more game systems and do more interesting things and is overall good for the health of the game.  A nerf to hacking makes it harder for an antag to perform some gimmick that involves things from departments they don't have access to.

This doesn't just slow down or discourage hacking, this makes it so anyone without insuls needs to either accept an RNG chance of being round removed or not hack at all.  If people hacking doors too easily is a problem that needs to be fixed (which I don't agree it is) there are better and less extreme ways of doing this.

**Comment by Shadowflame909** [comment]
Is this an alternative PR to the RCDs being removed from public use?

**Comment by Qustinnus** [comment]
> Fixes a problem that doesn't need to be fixed. People being able to quickly hack into places they aren't authorized for is a fundamental part of how the game currently functions. People breaking into places generates conflict and already has downsides compared to obtaining legitimate access or using more specialized methods (such as emag).


lol is the new "its part of tg culture"

**Comment by Rohesie** [comment]
> Question about this PR, do the ten airlock types have any unique tell as to which of the ten types they are?

They don't, the point of it is not being predictable. It's just ten variants merely to reduce memory load because functionally that is the same as every door being random.

> This doesn't just slow down or discourage hacking, this makes it so anyone without insuls needs to either accept an RNG chance of being round removed or not hack at all. If people hacking doors too easily is a problem that needs to be fixed (which I don't agree it is) there are better and less extreme ways of doing this.

You can still hack. It's just slower and your risk being shocked if you don't have insulation or access to a diagnostic tool, which kind of makes sense. You won't get round-removed unless if you do it while wounded or while the network has been overloaded. Antags have tools to circumvent this when it's expected for them to.
I wouldn't mind hearing about "less extreme" alternatives, though.

> Is this an alternative PR to the RCDs being removed from public use?

Convergent, but not otherwise related.

**Comment by Iatots** [comment]
This could be improved imo by making it so that all doors of the same department share the same template for engineering sanity, but I'd just rather have command / sec airlocks reinforced.

**Comment by OdoSendai** [comment]
> lol is the new "its part of tg culture"

SS13 culture in general, but /tg/ even more so since its LRP and very gamified.  This changes an important aspect of how the game works and will have a huge impact if it goes though.  Inertia isn't really my main point, which is instead that 'I want to do a thing but need to get past a locked door so nevermind'  isn't good gameplay.

> You can still hack. It's just slower and your risk being shocked if you don't have insulation or access to a diagnostic tool, which kind of makes sense. You won't get round-removed unless if you do it while wounded or while the network has been overloaded. Antags have tools to circumvent this when it's expected for them to.
I wouldn't mind hearing about "less extreme" alternatives, though.

Insuls and 'diagnostic tools' (CE's blueprint and abductor tools?) are super limited.  The network being overloaded isn't something you typically know about, so any time you hack without knowing you are taking the risk of getting critted/dusted.  If you know for a fact the grid is overloaded, you just can't hack.  Even under normal conditions this makes hacking take 10 times as long and you risk taking yourself to half health.

Less extreme method could be something like adding a timer to one of the hacking steps, or as someone suggested making all the "important" doors (bridge, sec, etc.) reinforced by default.  Something that makes the process take longer, but not something that would prevent people from doing it entirely.

**Comment by Shadowflame909** [comment]
Door-hacking as mentioned several times. Does have legitimate uses other then greytiding.

It can save someone's life from malicious antagonists!

It's like mass nerfing combat because greytiders keep killing each other and other people.

Shitters will be shitters and should be dealt with. Just don't throw the whole mechanic under the label of only used for greytide shittery.

PS. If the warden is guarding the armory, and the captain does literally anything with his spare. Hacking anywhere becomes 99% more of a non-issue.

**Comment by CRITAWAKETS** [comment]
This isnt going to reduce greytiding at all, its actually going to make it worse. Want to get semi-quickly in a department without breaking something? Well with this change you cant. Therefore every greyshits/engineer/doctors/scientists/goodsec/cargonian will just have to break down the doors to get in places.

**Comment by KomradeSpectre** [comment]
Did you honestly make this PR based off Deedubya's suggestions? Big yikes, Rohesie.
Explain how this makes the person still continue to hack, and not just break the door down instead?

**Comment by PKPenguin321** [comment]
Actually I think these DO have a reliable tell looking at it now, but it's not very intuitive
They should have an intuitive tell though. Maybe like a new light, where the color of it denotes its type. You would still solve your issue of the wires being easy to memorize and tell others without it being a total crapshoot.

That and the airlock circuit board should allow you to change the type.

**Comment by Rohesie** [comment]
> This could be improved imo by making it so that all doors of the same department share the same template for engineering sanity, but I'd just rather have command / sec airlocks reinforced.

It's not a bad suggestion, and I'm told Citadel does it that way (I'd have to check their code), but I feel it's less maintainable in the long run, adding another variable of interaction between doors and wires.

> Less extreme method could be something like adding a timer to one of the hacking steps, or as someone suggested making all the "important" doors (bridge, sec, etc.) reinforced by default. Something that makes the process take longer, but not something that would prevent people from doing it entirely.

Click-and-wait is much less interesting from a user experience than calculated and avoidable risks.

> Door-hacking as mentioned several times. Does have legitimate uses other then greytiding.
> 
> It can save someone's life from malicious antagonists!

The ability to hack is not removed. Just to do it without both no gear and possible consequences. This is precisely the job of the engineers.

If required this is a side of the game that can be expanded upon, such as giving doctors some paramedic tools, such as emergency override door remotes to certain places, or we can add an engineering skill/trait that does the same the blueprints do, or a engineering HUD scanning tool, you name it. But the current status is, as someone commented above, very gamified. We are just used to it because it has always been that way, but from a new player perspective it's not all that intuitive that you check one airlock and you know the configuration of every other. It's pretty artificial.

> Actually I think these DO have a reliable tell looking at it now, but it's not very intuitive
> They should have an intuitive tell though. Maybe like a new light, where the color of it denotes its type. You would still solve your issue of the wires being easy to memorize and tell others without it being a total crapshoot.
> 
> That and the airlock circuit board should allow you to change the type.

I don't mind making multitool probing more intuitive, though the obscurity and guessing game is something I enjoy. If you suggest me specific interactions with wires and the maintainers consider it not too much of a buff I don't mind implementing it.

On the circuit board allowing you to change the type, that makes things a little bit more complex, possibly requiring a larger refactor, and I don't see much gain. Could you expand on it?

**Comment by PKPenguin321** [comment]
The circuit board already has a menu to change the required access levels. You could just add a button that lets you choose which wire set to use. Would have a tangible benefit in the way of aiding in construction projects, especially when signallers are involved, plus it's nicer than it just being totally random and out of your control.

Multitool probing itself doesn't need to be more intuitive, what I'm saying is that there should be a way to determine the which wire set you're looking at. I'd do this by adding a new light that denotes type. Example:
You're making it so airlocks have ten sets of wires, and those sets are random. I'll refer to those sets as set 1, set 2, etc.
"The type light is red." This door has its wires in the set 1 configuration.
"The type light is blue." This door has its wires in the set 2 configuration.
Etc

**Comment by dee-dubya** [comment]
> 
> Multitool probing itself doesn't need to be more intuitive, what I'm saying is that there should be a way to determine the which wire set you're looking at. I'd do this by adding a new light that denotes type. Example:
> You're making it so airlocks have ten sets of wires, and those sets are random. I'll refer to those sets as set 1, set 2, etc.
> "The type light is red." This door has its wires in the set 1 configuration.
> "The type light is blue." This door has its wires in the set 2 configuration.
> Etc

I think this idea has legs after this PR gets merged. Perhaps having it be based on a series of 3 lights being on or off. Say for the sake of example, Red/Green/Blue. All doors with the same light combination(like Red on, Green on, Blue off) would have the same wire layout. That'd also allow it to be reliably added to the blueprints as well. Have a submenu in the blueprints for "airlock wires", with the ten different combinations selectable.

That's more of a future QOL change though, and not really necessary for the intended effect of this change. The people that are supposed to be messing with airlock wires will have all the necessary tools to safely do so regardless.

**Comment by Rohesie** [comment]
> The circuit board already has a menu to change the required access levels. You could just add a button that lets you choose which wire set to use. Would have a tangible benefit in the way of aiding in construction projects, especially when signallers are involved, plus it's nicer than it just being totally random and out of your control.

Made a simple implementation of your concept: the airlock electronics can make airlocks in either a random pattern, or in the static one listed by the blueprints.

ljtKUYZ
S4i6YUC

The concept can be expanded later, if needed. 

> Multitool probing itself doesn't need to be more intuitive, what I'm saying is that there should be a way to determine the which wire set you're looking at. I'd do this by adding a new light that denotes type. Example:
> You're making it so airlocks have ten sets of wires, and those sets are random. I'll refer to those sets as set 1, set 2, etc.
> "The type light is red." This door has its wires in the set 1 configuration.
> "The type light is blue." This door has its wires in the set 2 configuration.
> Etc

The request is reasonable. Design it exactly how you'd like it to work, with which inputs and outputs, and I'll implement it here if the maintainers agree to it.

**Comment by Quartich** [comment]
How would CE's blueprint work with this? List every door/template?

**Comment by Rohesie** [comment]
> How would CE's blueprint work with this? List every door/template?

There is one static set of wires that work like the current ones: random for the round, but its colors are listed on the CE's blueprints and you can set new airlocks to follow it, instead of a random one.

**Comment by 81Denton** [comment]
This would make construction projects or anything involving wire assemblies a huge pain in the rear. We already have different security levels for airlocks, I'd rather see those changed than randomizing wires.
Besides, the greytide is more of a player base problem than a code problem.

**Comment by optimumtact** [comment]
I don't disagree with the rest of your comments, but player problems are fucking code problems

**Comment by Ghilker** [comment]
> This would make construction projects or anything involving wire assemblies a huge pain in the rear. We already have different security levels for airlocks, I'd rather see those changed than randomizing wires.
> Besides, the greytide is more of a player base problem than a code problem.

Where is the problem with wire assemblies? he also made a cool GUI to help with those kind of jobs. More than often i see people announcing color wires and people opening doors in 5 seconds flat.
Engies can make doors easily enough with RCDs and also remove them without much problem

reopen this and merge it because is a good addition

**Comment by dee-dubya** [comment]
> 
> 
> This would make construction projects or anything involving wire assemblies a huge pain in the rear. We already have different security levels for airlocks, I'd rather see those changed than randomizing wires.
> Besides, the greytide is more of a player base problem than a code problem.

The entire reason I even proposed the idea was because it was a way to solve a major player problem without needing to make policy. Fixing an oft-abused feature of the game by reworking it in a way that only impacts the people abusing it, while only minorly inconveniencing people that are meant to make use of it. That's the entire purpose of a code solution versus a policy one.

**Comment by Rohesie** [comment]
> This would make construction projects or anything involving wire assemblies a huge pain in the rear. 

For construction, the airlock electronics can be selected to use static wires.

For wire assemblies only if there are no methods to check the wires, like currently with the blueprints. That can be easily changed through electrician diagnostic tools and/or mob traits.

> We already have different security levels for airlocks, I'd rather see those changed than randomizing wires.

This is not incompatible with airlock security levels.

**Comment by Detective-Google** [comment]
To be perfectly honest if this change had gone through i would have just started rcding down doors or engineering would be raided by a wave of people every round

**Comment by RaveRadbury** [comment]
How about having separate wire schematics for device subtype rather than full random? Much like how deconstruction is more difficult with reinforced variants. Mirror the spirit of that.

**Comment by PKPenguin321** [comment]
To be honest, if this had the type light I mentioned I could see it being a reasonable addition. If the number of wire sets is too much, it seems like it could be lowered too. OP looks to be open to changing this PR so I think a compromise could actually be really cool here. I think that this could add a very moderate and reasonable amount of complexity without it being too much once it has the right tweaks.

**Pull request closed without merging**
