### PR TITLE
Readds the parasting

### PR DESCRIPTION
**Pull request by optimumtact**
as a meme for retardation affected mobs

### CODE REVIEW

**Comment by hornygranny** [comment]
:+1:

**Comment by bgobandit** [comment]
https://www.youtube.com/watch?v=XtRCqxpyxnY

**Comment by Supermichael777** [comment]
change it to was fair and balenced

**Comment by optimumtact** [comment]
Oooh good idea

**Comment by Iamgoofball** [comment]
sign me the FUCK up good shit go౦ԁ sHit thats ✔ some goodshit rightth ere right✔there ✔✔if i do ƽaү so my selｆ :100: i say so :100: thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ:100: Н

**Comment by PKPenguin321** [comment]
quality pr :+1:

**Comment by Firecage** [comment]
Seriously Oranges, can you fucking put serious title's for once instead of retarded joke clickbait titles?

**Comment by optimumtact** [comment]
it's oranges

**Comment by AnonymousNow** [comment]
Suffering severe cardiac abscondment from that title; it's wearing a little hat and wheeling away a suitcase to the airport right now.

**Comment by optimumtact** [comment]
My insurance covers these cases, call me

**Pull request merged**
