### PR TITLE
Fixes a typo in station names

### PR DESCRIPTION
**Pull request by Tacolizard**
jklol i fixed a typo

### CODE REVIEW

**Comment by RemieRichards** [comment]
Just a warning, we don't allow meme titles anymore.

**Comment by Tacolizard** [comment]
so goof's guncrafting pr titles must be left blank now?

**Comment by KorPhaeron** [comment]
This isn't a typo. Notice that Neckbeard is already in the list as a separate entry.

**Comment by Tacolizard** [comment]
wtf is a neckbear

**Comment by KorPhaeron** [comment]
https://pbs.twimg.com/profile_images/529669739204050944/k8GxUWnn.jpeg

**Pull request closed without merging**
