### PR TITLE
Removes ling "Swap form" ability

### LINKED ISSUE #21277: Swapping forms as a ling causes the target to be ghosted
What it says ^^

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
del: Changelings no longer have the Swap Forms ability.
/:cl:

I don't get why changelings had a literal mindswap ability, when they already have many ways of becoming someone else.

Closes #21277

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Not even a good mind swap at that

**Comment by Crushtoe** [comment]
Needs a good bit of discussion before removal imo.

**Comment by ShadowDeath6** [comment]
didn't really make much sense to me. how did they transfer all their ling powers to the other person if (IC wise) their powers are all tied to the body? it's not like all humans have the capacity to grow a huge proboscis and suck the blood out of someone and their mind is stopping it

**Comment by TechnoAlchemisto** [comment]
Humans only use 6% of their brain it's gotta be in there somewhere

**Comment by PKPenguin321** [comment]
It's a dumb ability but I'm not sure removing it is necessary

**Comment by Aloraydrel** [comment]
Meme ability

**Comment by PKPenguin321** [comment]
Not an argument

**Comment by Aloraydrel** [comment]
Not an argument

**Pull request merged**
