### PR TITLE
Tacticool jumpsuits aren't cool for protection

### LINKED ISSUE #14587: tacticool turtlenecks have same armor as real things
https://github.com/tgstation/-tg-station/blob/02603d4f93a123942873f388bb5847ef38fb1f33/code/modules/clothing/under/syndicate.dm

While this *might* be intended, it certainly looks like somebody forgot about inheritance when making this item.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #14587

Also removes some vars that would be inherited from the sniper jumpsuit.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
put "Closes https://github.com/tgstation/-tg-station/pull/14588" in the OP if you're gonna go through w/this

**Comment by ChangelingRain** [comment]
I could do that, but it'd be rude and I'm being rude enough making oranges look like a tactifool.

**Comment by tedward1337** [comment]
thank

**Comment by Fox-McCloud** [comment]
:-1: 

As someone else pointed out, these are difficult to get ahold of and you can just get the sec jumpsuit from arrivals--what's the point of this?

**Comment by Bawhoppen** [comment]
:-1: this shouldn't have been reported as an issue its blatantly meant to give protection

**Comment by ChangelingRain** [comment]
You guys are gonna look like tactifools if you keep at this, it's an item you get from the arcade.
No other arcade item gives benefits.

**Comment by Fox-McCloud** [comment]
>You guys are gonna look like tactifools if you keep at this, it's an item you get from the arcade.
No other arcade item gives benefits.

Considering that the spacesuit hides your sprite, that's highly debatable.

**Comment by duncathan** [comment]
I'm sorry but I don't like balance memes

**Comment by Bawhoppen** [comment]
snap pops definitely can light fires and freak people out
crayons are self explanatory

**Pull request merged**
