### PR TITLE
Appendictis no longer murders the fuck out of you.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Removes the four toxin damage a broken appendix deals when it breaks.

## Why It's Good For The Game

Alright listen up, how about we don't make a fairly common random event that already has fairly hefty downsides in the way of vomiting murder you in seconds?

This change was poorly thought out and I don't ever want to die from this. This is basically heart attack levels of silly.

Be my guest if you want to remove the appendicits disease and make it completely handled by the appendix, but this is amount of damage is just stupid.

## Changelog
:cl:
balance: A broken appendix no longer murders you in seconds.
/:cl:

### CODE REVIEW

**Comment by CPTANT** [comment]
have you tried not letting your appendix burst?

**Comment by nemvar** [comment]
Sorry, that privilege is reserved to etherals and plasmemes.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/master/code/datums/diseases/appendicitis.dm#L17-L36

**Review by ExcessiveUseOfCobblestone — DISMISSED** [review]

**Comment by Vasily2013** [comment]
Have you tried not neglecting your medical staff? If you don't neglect your medical staff you're unlikely to have your appendix burst.

**Comment by Kmc2000** [comment]
This gives medical something to do on slow rounds and has livened up a lot of dull medbays.
I think it'd be better to just nerf the damage hard (0.5 per tick?), and make it display annoying messages until you fix it.

**Comment by RandolfTheMeh** [comment]
You left the organ damage that appendicitis does. Not every organ needs to have a failing effect, and yeah it sucks to die to something as lame as appendicitis when it's a random event, but random events in general kinda suck to have happen (like spontaneous brain damage, which has a resistance roll up to requiring a magic-cure for some reason).
Either way, if this isn't going to have an organ damage, set the decay to 0 and remove the damage appendicitis does. No point in having it show up in organ damage if it does nothing when damaged.

**Comment by wesoda25** [comment]
Whats wrong with it? I got appendicitis just the other day and noticed nothing wrong with it. Plenty of warning, and time, is given up to the burst. It places importance, and gives use, to a frequently forgotten and bypassed department.

**Comment by nemvar** [comment]
It's bad enough if it just stuns you repeatedly. I've said before that not everything in this game needs to murder you and I stand by that.

**Comment by nemvar** [comment]
wtf travis?

**Comment by ExcessiveUseOfCobblestone** [comment]
looking at it now I think it would be better to just lower the damage instead of remove it outright.

**Comment by Repukan** [comment]
Appendix burst (Peritonitis) is extremely lethal irl too.

You get ample warning to get it taken off before it bursts. If you decide to ignore that's your fault tbh

**Comment by Karmic-Skink** [comment]
Agreed, you get plenty of warning about this and it actually gives something for medical to do.
This change isn't needed.

**Comment by GoatMonarch** [comment]
I have no idea how a player can even get so far as to recieve the toxin damage considering the constant vomit stun, with the seizure like effect once your stomache is empty, not to mention the hunger slowdown, and the mood effect.

This is far more generous than most viruses or nanites in terms of warnings, and they are far more unforgiving once they come into effect.

I don't even know if a damage nerf is warranted with how unlikely this is to happen to you unless medical is blown to hell, and you can't bother to get a bedsheet and some getho surgery tools, or if someone cuff you and run off with you, where you're most likely dead before the toxin damage kicks in.

**Comment by optimumtact** [comment]
now this is podracing

**Pull request closed without merging**
