### PR TITLE
Properly encourages wardens to remain in the brig by instantly blowing up their legs at roundstart

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: Wardens are now properly incentivized to stay in the brig.
/:cl:

### CODE REVIEW

**Comment by Kraseo** [comment]
exploding knees

**Comment by Xhuis** [comment]
Every day lzimann closes a security PR, wardens remain rampant, wandering the halls with a full set of legs. How could you torture us so?

**Comment by Plapatin** [comment]
larry nolegs finally gets other wardens to do their job proper

**Comment by DEATHRATTLERS** [comment]
Secway has a purpose now

**Comment by ShiggyDiggyDo** [comment]
Add an irremovable explosive collar to the warden that blows his up head and deletes his brain when he leaves the brig

**Comment by Cyberboss** [comment]
Remind me to testmerge this on April 1st

**Comment by Buggy123** [comment]
Don't worry, I'll remind you cyberboss

**Comment by Anonmare** [comment]
Put the Warden in an electric wheelchair with his blown off legs that automatically shuts down if it's no longer in the brig section

**Comment by MrDoomBringer** [comment]
@Cyberboss

**Pull request closed without merging**
