### PR TITLE
Adds eighties carpet as a arcade reward.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

You thought you could get away with it, didn't you. You thought you could run this "event" and drive people insane with ugly eighties carpet. You didn't think I would screenshot, crop, adjust the sprite, and then PR it into the game as an arcade reward, did you.

image

image

## Why It's Good For The Game

It's a funky sprite, but in short, controlled doses looks nice, and would make for a nice arcade floor if you earn it as opposed to the usual space/pitfall floors.

## Changelog
:cl:
add: Funky 80s flooring can now be earned from the arcade game.
/:cl:

### CODE REVIEW

**Review by Rohesie — APPROVED** [review]
Simple PR, code looks fine.

**Comment by actioninja** [comment]
What the fuck

**Comment by Krysonism** [comment]
You should be forced to show how it tiles if you make new turf sprites.

**Comment by ArcaneMusic** [comment]
> You should be forced to show how it tiles if you make new turf sprites.

Done.

**Comment by MMMiracles** [comment]
I feel like it needs 2-3 more variations to cycle through, the defined shapes (specifically the purple triangle) make the edges pop a lot more and makes it look not that great in larger sections.

**Comment by HomocidlePancakes** [comment]
This is worse than old space backround. Fuck, my eyes.

**Comment by PKPenguin321** [comment]
it's like i'm really in a chuck e cheese

**Comment by RiskySikh** [comment]
the carpet reminds me of the sticky soda smell

**Comment by Shadowflame909** [comment]
Are you feeling the SURGE only at space station 13's arcade machine!

**Comment by Anonmare** [comment]
I can *smell* it

**Comment by Bokkiewokkie** [comment]
So as MMMiracles said before it looks a bit too straight around the edges which gives it a bit of a strange look. Though he was talking about the purple triangle around the edge I thought it was mostly because of the positioning of the white streaks, so I decided to tweak some of them. 
Here's my edit of the two white bits that cross over from left to right:
NMfloor
This is what it would look like when tiled:
NMfloortiledf

**Comment by kriskog** [comment]
Its horrible

**Pull request merged**
