### PR TITLE
Resprites Exo-Drone Scanner

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

I did the originals a few years ago, and in hindsight, those sprites suck tremendously.
New sprites, better perspective, looks like an actual radar dish.
image

## Why It's Good For The Game

I feel like it's a distinct improvement, and better matches modern sprite quality / my own quality standards.

## Changelog

:cl:
image: New cargo exo-drone scanner sprites!
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Weh, I like the lights. The new sprite looks better but it should still have a green light on the tip.

**Comment by Wallemations** [comment]
One part I'm confused about is the lighting angle on this, since the bowl is concave it should have its highlights on the lower portion since our sprites are typically lit from above, but the shine is on the higher portion, which makes it look like it's being lit from below.
The highlights have a similar issue where they are a little inconsistent
Finally I'm contemplating whether the side-facing dish should have so much of its bowl be visible, but I don't know if that's a shading issue or not so don't worry about it too much comparatively.

Otherwise this has a great palette and far more readable shape, good work.

**Comment by ArcaneMusic** [comment]
> One part I'm confused about is the lighting angle on this, since the bowl is concave it should have its highlights on the lower portion since our sprites are typically lit from above, but the shine is on the higher portion, which makes it look like it's being lit from below. The highlights have a similar issue where they are a little inconsistent Finally I'm contemplating whether the side-facing dish should have so much of its bowl be visible, but I don't know if that's a shading issue or not so don't worry about it too much comparatively.
> 
> Otherwise this has a great palette and far more readable shape, good work.

Gotcha chief. I'll run some improvements and we'll see if I can get that lighting angle down. Drafting for now

**Comment by Loafin34** [comment]
coderbus 2023 successful question entered!!

**Comment by ArcaneMusic** [comment]
Got trapped in the wage cage, will reopen when tweaked

**Comment by ArcaneMusic** [comment]
Back and got around to making the requested changes. I think it's a marked improvement personally

**Comment by Wallemations** [comment]
scanner_ready feels way too fast, but otherwise this is a big improvement

Ping me on discord when you slow that down a little and I'll merge

**Pull request merged**
