### PR TITLE
Fixes vending machines being empty

### LINKED ISSUE #29822: Vending machines start empty at roundstart
Seen on Sybil with the NanoMeds and the clown costume dispenser

<QualityVan> vending machines without refill cannisters are empty

### PR DESCRIPTION
**Pull request by lzimann**
Fixes #29822
Also fixes them filling the inventory twice.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
So they just self refill? (unless i've mistaken what the code implies)

-  I would have thought my timed[ auto-regeneration suggestion](https://tgstation13.org/phpBB/viewtopic.php?f=9&t=11903) would probably be more balanced so people don't spam them for infinite tools/metal and instead have to wait a reasonable amount of time.

**Comment by FantasticFwoosh** [comment]
- Please be clearer with the title, its hard to infer what you mean, same for issue report

If this is a fix for not being able to refill the contents of a cleared out nanomed or instead it not dropping items when broken open.

**Comment by optimumtact** [comment]
except we're in the middle of a feature freeze still fwoosh, please put at least as much thought into your ideas as you clearly do expressing them.

**Comment by FantasticFwoosh** [comment]
Just throwing some breadcrumbs for the ducks @optimumtact

**Pull request merged**
