### PR TITLE
Revert "Merge pull request #20049 from Iamgoofball/patch-112"

### PR DESCRIPTION
**Pull request by ohnopigeons**
* Doesn't do anything, let alone fixing [stock spikes](https://github.com/tgstation/tgstation/issues/37400)
* Garbage variable names
* Garbage logic
* Impairs code readability significantly.

Remove immediately.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
oh yeah cool let's just remove the only protection against stock spikes so the spikes can happen more often

why dont you actually fix the bug if you're going to revert a bandaid for it

**Comment by pigeonsk** [comment]
Can you please read the code you wrote yourself?

It doesn't

Do 

# ANYTHING

**Comment by pigeonsk** [comment]
Trick question you can't read it because it's unreadable.

**Comment by Barhandar** [comment]
>X += Y * X everywhere  
>is surprised by spikes

Also yeah it does jack shit because the condition is always true.

**Comment by Iamgoofball** [comment]
ah shit

**Pull request closed without merging**
