### PR TITLE
destroys a rare meme

### PR DESCRIPTION
**Pull request by silicons**
Memeber --> Member

### CODE REVIEW

**Review by phil235 — APPROVED** [review]
:+1:

**Comment by Iamgoofball** [comment]
:-1:

**Comment by PKPenguin321** [comment]
You have to wonder if this was intentional

**Comment by Thunder12345** [comment]
This is a good meme, leave it

**Comment by kevinz000** [comment]
Kek

**Comment by phil235** [comment]
why?

**Comment by optimumtact** [comment]
restore this

**Pull request closed without merging**
