### PR TITLE
Crafting recipe results blacklisted by default

### LINKED ISSUE #47205: Strobe shield crafting can use strobe shields rather than just riot shields
If you craft multiple strobe shields at once, rather than resulting in more strobe shields it can just keep using the outputed shield to make more of them, resulting in just the single shield

Issue reported from  Round ID: 121721 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

### PR DESCRIPTION
**Pull request by kriskog**
## Why It's Good For The Game
Fixes #47205

## Changelog
:cl: Skoglol
fix: Strobe shield can no longer be crafted using a strobe shield.
/:cl:

### CODE REVIEW

**Comment by ninjanomnom** [comment]
It might be a good idea for the result to automatically be included as part of the blacklist at some point

**Comment by kriskog** [comment]
Agreed, actually. That shouldnt be too hard, let me take a look.

**Comment by kriskog** [comment]
Need to rethink the result blacklisting. AnturK pointed out it would fuck with the firing pin removal recipe.

**Comment by kriskog** [comment]
Now checks for result in reqs before blacklisting

**Pull request merged**
