### PR TITLE
Gang Update: Recruitment Edition

### LINKED ISSUE #10099: Implanted Team Antags have their icons overlayed with the loyalty hud icon
When implanted, Cultists, Gangsters, (and probably nuke ops, too) have their icon covered by the loyalty implant icon.

While it doesn't cover the icon completely, it does make it harder to tell if they're on your team.

### PR DESCRIPTION
**Pull request by Ikarrus**
The biggest changes here to note is the ones to recruitment pen costs. The goal of raising their costs is to lighten the emphasis on recruitment rushes early in the round. Their high cost ensures they remain a luxury item for strong gangs, or leaders who have lost their own. 

Theoretically, gangs should be less inclined to spend all their early-game influence on pens and very quickly converting most of the station, and get encouraged to promote more bosses reducing the risk of a lame round due to an early capture of a gang boss.
### Major Changes
- Recruitment Pen cost raised back to 50
- Each gang lieutenant gets one free recruitment pen
- People stabbed with recruitment pens no longer feel a tiny prick
- Shuttle recalls now take about a minute during which the gangtool will not be usable
- Added C4 purchasable for 10 influence. 
  - This should help access-less gang bosses get into places they need to be.
- Buffed Gang outfit armor 
  - (melee = 20, bullet = 30, laser = 10, energy = 10, bomb = 20, bio = 0, rad = 0)
- Removed bulletproof vests from gangtool menu
### Minor Changes
- Added new gang names with tags by Joan
- Added puffer jackets and vests (Gang outfit option)
- Increased chance of deconversion for head trauma
- Pinpointers will no longer point to active dominators. Instead dominators will emit a loud beeping similar to syndicate bombs
- Domination announcement will now print the area's initial name instead of the actual one
- Custom Areas (Created with blueprints) are no longer valid places to place dominators
- Dominator health reduced back to 200
- Reduced starting influence to 20
  - Enough for a promotion and two spray cans
- Increased pen cooldown reduction to 15 seconds per extra head
- Added feedback for wearing gang outfits
- Reduced gang outfit stocking rate
- Red gang tag colors changed to match red crayon colors
- Fixes #10099 Offset the loyalty HUD icon a little bit so it doesn't completely overlay on top of antag icons
- Added some gang tips of the round
- Reorganized the gangtool menu for ease of use.
- Rewrote some text lines to try and improve their clarity

### CODE REVIEW

**Comment by Lumipharon** [comment]
why'd you remove the vest? It added some much needed GvG toughness.

**Comment by Lumipharon** [comment]
Also need a way to mitigate the issue of penning an enemy gangster and getting outed as a gang head and dunked. This is particularly bad for weaker gangs that can't protect their heads overtly/the enemy gang has loads of dudes.

**Comment by Ikarrus** [comment]
Yeah, I'll see if I can't remove the tiny prick message for them.

**Comment by Incomptinence** [comment]
If you remove the tiny prick message a scenario earlier where I met the other gang leader in the first five minutes and they pricked me first finding out who I was then killing me. Would have been totally unavoidable instead of a stupid mistake on my par disregarding the tiny prick message.

**Comment by Nanotransistor** [comment]
Not sure about the 5 cost on shuttle recall. Could easily be abused by sec from the moment a gang is sighted.

**Comment by Ikarrus** [comment]
Swapped out recall cost for something simpler.
Increased chance of deconversion on head trauma.

**Comment by Ikarrus** [comment]
Swapped out recall cost for something simpler.
Increased chance of deconversion on head trauma.
Removed tiny prick message for recruitment pens

**Pull request merged**
