### PR TITLE
fix for diseases sometimes being unable to infect anybody

### LINKED ISSUE #46408: Virus won't transmit via blood.
Issue reported from  Round ID: 118127 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

Made a 6 symptom beneficial virus with a resistance of 2, stealth of -3, stage speed of 9, and transmittability of 11. Airborne, so I gave it to my test monkies.

image

Made another 6 symptom virus, harmful this time, with the stats that theoretically should overtake the beneficial one. 14 resistance, -2 stealth, 9 stage speed, 5 transmittability.

image

Theoretically speaking based on what's on the wiki, a virus with a higher transmission than the resistance of the virus it is overtaking will successfully transfer. Putting infected blood into the monkies via syringe, splashing it on them directly, and spraying with a spray bottle (both as a blood spot on the floor and directly) does not transfer the virus. Up until recently I swear I've been able to splash the same exact virus onto people and it functioned as expected, so maybe a recent change to splash/spray transfers could've done this?

### LINKED ISSUE #47359: weird stuff is happening with custom viruses
I tested out a virus on Bagil last round. It had both necrotic metabolism and inorganic biology in it, as seen in this screenshot: https://cdn.discordapp.com/attachments/509932988688105482/636764128073220096/virology_bug_one.PNG

It infected skeletons (and maybe inorganics? I don't quite remember) just fine, but it wasn't able to infect any living organic creatures, even when injected.

EDIT: Scroll down to my comment below; it details the TRUE bug at work here (it has nothing to do with the inorganic biology symptom or the necrotic metabolism symptom).

EDIT EDIT: My comment below does not, in fact, detail the TRUE bug at work here.

### LINKED ISSUE #50607: Virus isn't infecting
Issue reported from  Round ID: [135290](https://scrubby.melonmesa.com/round/135290) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1517

This is an iffy one. Sometimes it works and sometimes it doesn't. It feels like at least once every few rounds you get a virus that doesn't infect, and I'm unsure what causes it. In this case my virus doesn't infect after I drink. When testing try rebooting the server several times to see if you get the same results, as I said sometimes it works sometimes it doesn't.

2020-04-21 18_53_19-Window
2020-04-21 18_54_27-Window
2020-04-21 18_54_07-Window

I tried this with a slight variation to test to see if it infects but it does not. Not even some sniffles.

### LINKED ISSUE #50641: Pandemic virus culture functionally just Toxin
Issue reported from  Round ID: [135428](https://scrubby.melonmesa.com/round/135428) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

Some rounds, it seems that any culture the Pandemic prints is incapable of infecting humans or monkeys. I have tried pills, patches, dropper to the eye, syringe, drinking the culture, and spray. A health analyzer's chemical analysis shows x units of the chemical 'Toxin' in subject's bloodstream. I have tried reconstructing the pandemic, with no luck. I have not found any way to tell that this is going to happen in advance.

### LINKED ISSUE #50663: Pandemic Culture Doesn't Infect Part 2
Issue reported from  Round ID: [135531](https://scrubby.melonmesa.com/round/135531) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

Okay this time I noted that I started by getting Inorganic Biology (IB) with rhino as base, then isolating IB. Then I built on that till I had my virus, all neutered and ready. 
Nothin.
Luckily I kept a culture where I lost IB, so I built on that one instead.
Drank it, no infection.

BUT.
I just put a drop of plasma into rhinovirus, giving it noct regen. I made a culture out of it from the Pandemic, drank it, Got Infected!!

So, viruses that came from the children of the isolated IB culture were unable to infect. But a new virus culture made from a new parent was perfectly fine.

### LINKED ISSUE #51128: Inorganic Biology Virus Not Working
Issue reported from  Round ID: [137199](https://scrubby.melonmesa.com/round/137199) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

This time IB was the last symptom I got, but it overrode one of my others. So I made a culture and added a drop from the old culture to get all 6 symptoms on there. The resulting virus was unable to infect anything. It worked when I replaced IB with sneezing.
I was human.

### LINKED ISSUE #51150: Inorganic Biology Bug Part 4 or 5
Issue reported from  Round ID: [137338](https://scrubby.melonmesa.com/round/137338) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1524

Same deal. This time I got IB early and set it aside. I made the rest of my virus, then mixed the cultures till I had all 6. Usually I get IB last to avoid the bug (works pretty consistently) so this time I wanted to see if I could predict and trigger it. I **/think/** it's related to IB being added in from a different culture rather than mutated by a chem, but that's an educated guess at best.

### PR DESCRIPTION
**Pull request by sohpeach**
## About The Pull Request
Yes, this is the fix. The operator precedence was fucking up on the following lines:
https://github.com/tgstation/tgstation/blob/448216574e9a65de23e6169c42f3e0bc4b47b359/code/datums/diseases/advance/symptoms/species.dm#L17
https://github.com/tgstation/tgstation/blob/448216574e9a65de23e6169c42f3e0bc4b47b359/code/datums/diseases/advance/symptoms/species.dm#L33

I checked out all the uses of these enums and didn't see anywhere that the current precedence would matter.

The following reports of this bug aren't 100% confirmed to be caused by this, but I'ma put 'em here anyway:
fixes https://github.com/tgstation/tgstation/issues/51150
fixes https://github.com/tgstation/tgstation/issues/51128
fixes https://github.com/tgstation/tgstation/issues/50663
fixes https://github.com/tgstation/tgstation/issues/50641
fixes https://github.com/tgstation/tgstation/issues/50641
fixes https://github.com/tgstation/tgstation/issues/50607
fixes https://github.com/tgstation/tgstation/issues/46408
fixes https://github.com/tgstation/tgstation/issues/47359

## Changelog
:cl:
fix: diseases now retain the ability to infect people after having 'inorganic biology' or 'necrotic metabolism' removed from them
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
absolute chad move

**Comment by XDTM** [comment]
good catch, i never considered the defines themselves

**Comment by ATH1909** [comment]
holy fuck

the bug is finally dead

I cannot express how grateful I am to you for finally figuring out what was causing this frustratingly hard to pin down bug (and fixing it).

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=S02BHmWPZNs

**Comment by ATH1909** [comment]
> That does narrow it down a lot.
> 
> The advance_mix proc apparently works by creating a Copy() of each disease **(which currently var-copies the infectable_biotypes var, but does not apply symptoms due to an oversight)**, then picks randomly one of these two diseases as a base and adds the symptom of the other (properly, calling `OnAdd()`) to it. So there is a 50% chance of having a disease with a cloned `infectable_biotypes` with Inorganic Biology never having used OnAdd(), and a 50% chance of a disease with a regular `infectable_biotypes` which then gets modified by the Inorganic Biology's OnAdd().
> 
> Given that it's pretty likely that one of these two results is what is causing the bug in some way (still not sure how it could happen, unless copying bitflag vars is subject to a byond bug).
> 
> I'm not able to test this myself now, but if anyone's inclined to it would be useful to see how the `infectable_biotypes` var changes when mixing diseases a few times.

We might also want to look into that bolded part as well.

**Comment by nemvar** [comment]
This fixes the bug.

**Comment by optimumtact** [comment]
when will people learn

**Comment by Shikarego** [comment]
B A S E D

**Pull request merged**
