### PR TITLE
Banishes the chef's cqc back into their domain

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Removes chef CQC from all areas that aren't directly part of a kitchen. Repaths the icebox diner area to not be a kitchen area.

## Why It's Good For The Game

The original rationale for expanding chef CQC into areas surrounding the kitchen was to allow them to counter people griefing their tourist bots. In the current state of gameplay people no longer routinely bother the bots, probably due to the combination of them being much more assertive of their personal space and the novelty wearing off.

With this original problem having resolved itself, I feel it's no longer necessary to allow the chef the ability to brutalise people with a built in combination stun baton, knockout, and strong melee weapon in public dining areas or on some maps sitting at the bar.

In particular, in the case of antagonist chefs it can be remarkably easy, depending on pop, to simply grab people from outside the kitchen, knock them out and gib them. At intermediate pops of like 30-40 players it wouldn't be at all unusual to be out of sight of everyone but the chef on some maps if you're standing at the chef's counter. It also only takes a few seconds to get them over the counter, unconscious, and moved into the cold room.

This isn't an issue that can be easily fixed by encouraging people to solve it in-game. Players can't be encouraged to throw themselves at a chef with CQC kidnapping people from the bar if they don't think they can win, they're people too and in general would really like to stay in the round. Limiting CQC to the kitchen itself means people have to be put in there by other means, or willingly choose to put themselves in harms way.

This will likely have little to no impact on the safety and wellbeing of tourist bots, as only a small number of players seem to be aware of CQC's extent outside the kitchen. Further, I've not come across any similar griefing of the bartender's bots even though they already lack CQC.

## Changelog

:cl:
balance: Chef CQC can now once again only be used within kitchens
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
people don't bother the bots because they know the chef can walk out and CQC them if they do so

admins never actually resolved the core issue(griefers can grief the chef with no punishment), this was the decided on punishment, if you remove this people will grief the chef for trying to use the robots again

**Comment by moocowswag** [comment]
I literally just saw people trying to disposal loop the bots yesterday.

**Comment by JohnFulpWillard** [comment]
I think it's funny, do we have a valid reason to remove it, or is it just because you don't agree with the initial reason for adding it?

**Comment by Thunder12345** [comment]
> I think it's funny, do we have a valid reason to remove it, or is it just because you don't agree with the initial reason for adding it?

It's a bit extra when an antag chef has the tools roundstart to walk outside their kitchen, grab their one customer and take them inside to gib/absorb/whatever them. Restricting the ability to inside the kitchen itself means you need an extra step to somehow get them inside, or for them to enter of their own accord.

Allowing it outside the kitchen is also highly confusing and inconsistent for chef players, as depending on the map the area it's possible ranges anywhere between a small strip of floorspace right outside the counter on delta to the entire contents of the metastation bar, restricting cqc to only kitchen spaces themselves is a lot more understandable to the average player.

> I literally just saw people trying to disposal loop the bots yesterday.

I haven't seen this be a common thing to do, a single case of someone putting tourists in a disposals loop can be resolved with a toolbox or a call to security, the rationale behind expanding cqc range in the past was to counter the new feature urge to grief the bots every single round.

> people don't bother the bots because they know the chef can walk out and CQC them if they do so
> 
> admins never actually resolved the core issue(griefers can grief the chef with no punishment), this was the decided on punishment, if you remove this people will grief the chef for trying to use the robots again

Given I've seen very few chefs who even realise they have CQC outside their kitchen, I'd be surprised if people are deliberately leaving the bots alone because of that. The bartender has tourists too and only has the shotgun to protect them and I don't see people systematically griefing those tourists.

**Comment by JohnFulpWillard** [comment]
> Allowing it outside the kitchen is also highly confusing and inconsistent for chef players

It should only be limited to where people eat, if that's not the case it should've been fixed.

> It's a bit extra when an antag chef has the tools roundstart to walk outside their kitchen, grab their one customer and take them inside to gib/absorb/whatever them.

I generally don't like deciding balance based on how well antagonists can do with an item, but here the Kitchen is an open area, and CQC is loud, so it shouldn't be easy for the Cook to just kill someone without at least one person hearing it, whether they care or not is up to the players, but it's something I think is better resolved in-game or even admins if necessary.

> Given I've seen very few chefs who even realise they have CQC outside their kitchen, I'd be surprised if people are deliberately leaving the bots alone because of that.

Not that this point matters because I'm looking for reasons to not have it, not reasons why it shouldn't have been added in the first place, but the Cook not being aware of CQC doesn't mean assistants aren't aware of the possibility.

**Comment by Jackal-boop** [comment]
Chef is better with cqc inside and around the kitchen. It let's him put rowdy crew men to sleep. I don't really see a reason to remove this other than ided

**Review by JohnFulpWillard — COMMENTED** [review]
I don't like nerfing service jobs, but I reconsidered this PR and I'm willing to merge it. Is there a reason you're keeping around ``additional_cqc_areas`` (the support for adding more kitchen areas through map files)?

**Comment by Thunder12345** [comment]
> I don't like nerfing service jobs, but I reconsidered this PR and I'm willing to merge it. Is there a reason you're keeping around `additional_cqc_areas` (the support for adding more kitchen areas through map files)?

In case any mappers ever want to support non-kitchen areas being treated as kitchens and need to use it again. For example the abandoned kitchen in NE maint on Delta is currently pathed as a kitchen area, and some day a mapper could decide pathing the abandoned areas in delta as maint subtypes instead of abandoned subtypes of the normal rooms is better and `additional_cqc_areas` would mean the abandoned kitchen could still function as a kitchen for the chef.

**Comment by Iamgoofball** [comment]
i have still yet to see anyone in this PR or it's comments address the fact that this feature was why people didn't fuck with the food robots

literally, this is the code-side fix we implemented to people fucking with the chef's robots

the headmin team at the time ruled it as not an admin issue that people were griefing the chef via fucking with his robots, this was stated directly to the coder who made the chef robots

as such, we had to implement a code solution(chef cqc in the adjacent to kitchen zones where the robots sit)

**Comment by private-tristan** [comment]
> i have still yet to see anyone in this PR or it's comments address the fact that this feature was why people didn't fuck with the food robots

food robots already have near infinite hp, the power to break every bone in your body, and have no actual reason to fight them? i've never seen anyone mess with food bots for more than 2~ minutes before getting their bones broken and never doing it again

I've only ever seen chefs use CQC outside of kitchen for killing people to throw them over the counter and gib them

**Review by Watermelon914 — CHANGES_REQUESTED** [review]
Your 'Why It's Good For The Game' doesn't really explain why removing CQC from areas is actually good for the game, only that a problem has been solved and that this change isn't necessary anymore.

What are chefs doing to abuse their CQC privilege in the diner/kitchen? please go into more detail and make sure to include it in the description of the PR

> probably due to the combination of them being much more assertive of their personal space 

Isn't this because of CQC?

**Comment by Iamgoofball** [comment]
@private-tristan 
>food robots already have near infinite hp, the power to break every bone in your body, and have no actual reason to fight them?

we put in the infinite HP and backbreaking to curb griefing and it still wasn't enough, and to reiterate since you seem to have missed the memo, the reason people fight them is to grief the chef

when the motivation is spite, it doesn't matter how obnoxious you make it to do, they will keep doing it because they want to piss the chef off to get him to fight them so they can claim valids and murder the chef

you may argue this is a player/admin issue and we should take it up with them

we, the codebase, were told verbatim by head administrator Lepi during their term that there would be no action from the admin team on this issue and that if we wanted to fix it we would have to dis-incentivize griefing the chef via code

thus, we dis-incentivized griefing the chef via code with chef CQC in and around the kitchen in the spaces the robots inhabit so that crewmembers have to, in 90% of situations, put themselves at risk of chef CQC if they want to fuck with the chef

there has been no further change of policy on this by future terms, and that policy still stands today, so why should we remove the code solution for a problem?

**Comment by Iamgoofball** [comment]
i guess it just feels like we put a stop sign up at an intersection because the properties on the corners refuse to cut their shrubberies causing it to be a blind intersection, the stop sign reducing people getting run over by 75%, and then 3 years later the people who refuse to cut the shrubberies going "wow, people dont get run over at this intersection anymore, we dont need this stop sign here"

**Pull request closed without merging**
