### PR TITLE
NEW RECORD: 4 PR'S TO GET THE FUCKING C4 TIMER DOWN TO 3 FROM 5

### PR DESCRIPTION
**Pull request by Robustin**
HO-LEE SHIT IM JUST REOPENING THE PR'S FOR THE SAME BRANCH AT THIS POINT WHAT THE FUCK.

### CODE REVIEW

**Comment by kevinz000** [comment]
lol
# x150

**Comment by Iamgoofball** [comment]
Why the fuck does this keep reverting

**Comment by WJohn** [comment]
👌

**Review by Cyberboss — APPROVED** [review]

**Review by Cyberboss — APPROVED** [review]

**Review by Cyberboss — APPROVED** [review]

**Review by Cyberboss — APPROVED** [review]

**Comment by 4dplanner** [comment]
"This branch is 3 commits ahead, 2389 commits behind tgstation:master."

**Comment by 4dplanner** [comment]
Run git diff upstream/master -- **/grenades/plastic.dm, you're missing like half a file and that's why it doesn't work

**Comment by Robustin** [comment]
Thank you for the tip 4d, I'll let your PR be the hero we need. As much fun as it would be to put this up like 10 times.

**Pull request closed without merging**
