### PR TITLE
Fix turbine

### PR DESCRIPTION
**Pull request by abbioro**
Fixes 2 turbine bugs
- Race condition rendered turbine broken at roundstart by #11489. This is because the turbine and compressor run process() soon after initalization, and were doing it before they had located their machinery.

Here's a helpful (somewhat simplified) visualization of what was going wrong:

```
| Time | Proc 1             | Proc 2             |
|------+--------------------+--------------------|
|    0 | initialize turbine |                    |
|    1 | spawn(10)          |                    |
|    2 |                    | process() turbine  |
|    3 |                    | oops no machinery  |
|    4 |                    | set turbine broken |
|    5 | locate_machinery() |                    |
```
- Could not locate compressor when using the turbine computer from the north on Box (has been a bug since forever). Turns out the computer was checking for the compressor 5 tiles away from the _user_ and not the computer itself.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
I think this might fix  #9279 .

**Comment by Miauw62** [comment]
i'd just like to note that "thread" is misleading because BYOND is not multithreaded. (you know that too, just noting this here for babby coders, note how when one "thread" is running the other isnt.)
its probably more accurate to name them proc 1 & 2.

thanks for the fix :+1:

**Comment by joonoro** [comment]
Yeah, thread was just the first word that came to mind when I was writing that.

**Comment by Razharas** [comment]
I really, really hope this is it

**Pull request merged**
