### PR TITLE
Adjust the shadows of several mobs. Adding shadows to mecha, vim, flora and cardboard cutouts.

### LINKED ISSUE #82499: You can't pick things up under a trees shadow
## Issue Summary
You can't pick up things like wrenches if their sprite is under a trees shadow.

## Round ID:
226735

## Testmerges:
#82458: 'Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.' by Watermelon914 at commit 785ac3a525](https://www.github.com/tgstation/tgstation/pull/82458)

## Reproduction:
1. Find a tree with a shadow (for example, the one by the entrance of medbay on Northstar
2. Place a wrench so that it lays under the shadow of the tree
3. Try to pick it back up
4. Notice that the parts of the wrench under the shadow can't be interacted with

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This PR adjusts the types of shadows of a lot of mobs whom previously had shadows unbefitting their small or large sprites. The shadows of ghosts and the likes are now less solid-looking. Mechas now have shadows; ditto with the vim and cardboard cutouts, both of which also lacked visual offsets.
Vampires no longer have shadows visible by anyone but the player, it's also fainter. Slimes also have a fainter shadow, as they're meant to look a tad transparent. Shadows are now less opaque when immersed in water.
I gave the mannequin pedestal a topdown resprite to be in line with the perspective of mob shadows. I gave the chad meme clown sprite a touch, so that can face left and it only does that walking goofy animation when moving.
Lava swooping, disguising, and the rocket jump suicide now (temporarily) give the shadowless trait.

EDIT: Tree and tall jungle bushes now use the drop shadow component. This will fix https://github.com/tgstation/tgstation/issues/82499.

## Why It's Good For The Game
Post-wallening drop shadows adjustments and tweaks.

## Changelog

:cl:
qol: adjusted the shadows of several mobs to be more in-line with their sprites. Vampires no longer have shadows that are visible to other players. Ghost shadows are now fainters. Mechas, Vim and cardboard cutouts now also have shadows.
imageadd: Resprited mannequin pedestals to have a topdown look.
fix: tree shadows shouldn't block your clicks as often.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Massive soul

**Comment by GPeckman** [comment]
Do mechs have offset now too as well?

**Comment by Ghommie** [comment]
> Do mechs have offset now too as well?

They already do, this PR doesn't change that (unless you count the vim as a mech, but it is not).

**Comment by Time-Green** [comment]
Neeeeed pictuuuuures

**Comment by Jacquerel** [comment]
I was too slow to get this merged sorry, might need to rebase it to the wallening repo when we figure out what the development process for that ends up being.
Given that we now cannot possibly merge this (Watermelon is in the process of reverting Wallening from the master branch) I must unfortunately close this PR.


It's... also unfortunately possible that I will remove drop shadows from most mobs again shortly after we put this on the wallening branch as a trial for removing the mob offset but I'll try to do it in a way that preserves this work (at the very least, maybe flying mobs can still retain shadows even if not offset? will see) or at least ensures that we can very easily restore it if the offset comes back.

**Pull request closed without merging**
