### PR TITLE
Reorganizes cargo's big "miscellaneous supplies" category

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: Cargo packs have been reorganized to shrink the big engineering, food&livestock and misc categories.
/:cl:

This PR moves most packs from the "Miscellaneous Supplies" category into more appropriate ones - conveyor belts go into "Engineering", janitorial supplies into "Service" and so on.
I also split up Engineering into Engineering + Engine Construction and Food&Livestock into Food&Hydroponics + Livestock.

All changes:
- Engineering -> Engineering + Engine Construction
- Food&Livestock -> Food & Hydroponics + Livestock
- New category: Service (janitor+cargo+shaft miner and vending machine resupply packs)
- New category: Costumes & Toys

### CODE REVIEW

**Comment by 81Denton** [comment]
oh god I am not good with PR titles

**Comment by ExcessiveUseOfCobblestone** [comment]
Does this work? usually if you touch TGUI without doing a lot of work it cries.

**Comment by 81Denton** [comment]
Yeah, I compiled and tested it. Thank god I didn‘t have to touch TGUI itself.

**Comment by ExcessiveUseOfCobblestone** [comment]
you lucky rascal...

**Comment by MrDoomBringer** [comment]
These are still ordered alphabetically, right?

**Comment by 81Denton** [comment]
@optimumtact 

<details><summary>Emergency</summary>

emergency

</details>

<details><summary>Security</summary>

security

</details>

<details><summary>Armory</summary>

armory

</details>

<details><summary>Engineering</summary>

engineering

</details>

<details><summary>Engine Construction</summary>

engineconstruction

</details>

<details><summary>Canisters & Materials</summary>

canisters

</details>

<details><summary>Medical</summary>

medical

</details>

<details><summary>Science</summary>

science

</details>

<details><summary>Service</summary>

service

</details>

<details><summary>Food & Hydroponics</summary>

food

</details>

<details><summary>Livestock</summary>

livestock

</details>

<details><summary>Costumes & Toys</summary>

costumes

</details>

<details><summary>Miscellaneous Supplies</summary>

misc

</details>

**Comment by 81Denton** [comment]
Just noticed that not all packs are in alphabetical order anymore, I'll fix it in a little

**Pull request merged**
