### PR TITLE
New Chrono MODsuit Sprites

### PR DESCRIPTION
**Pull request by dawsonkeyes**
**Active sprites (and thus original sprites) made by Halcyon#7104
Inactive variants made by Dawson#8115**

## About The Pull Request

This PR entirely changes the look of the Chrono MODsuit, updating it to modern standards in regards to shading and contrast.

See them and how they compare to the current chrono suit in the collapsibles below!

<details>
<summary>Old vs New, side-by-side</summary>

image

</details>

<details>
<summary>New, in totality</summary>

image

</details>

## Why It's Good For The Game

In the few instances you actually see these used, surely it would be nice if they actually looked _good_, right?

## Changelog
:cl:
add: Added entirely new icons for the Chrono MODsuit
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
> > You currently have a negative Fix/Feature pull request delta of -15. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> 
> image
> 
> ??? what the fuck

image

there will be hell to pay

**Comment by HoodMilk** [comment]
It is a shame it will be so rare to see this.
Looks very cool.

**Comment by tralezab** [comment]
I really like it, but is there any chance you could keep the old? There is support for multiple styles with modsuits, and the more the better!

**Comment by dawsonkeyes** [comment]
> I really like it, but is there any chance you could keep the old? There is support for multiple styles with modsuits, and the more the better!

I mean, I could, but the linework for that is far more than what's honestly worth the trouble. If someone feels like readding them, they totally can, but I don't see the point of adding really dated alt-looks to a MODsuit that's already exclusively admin-spawned.

**Comment by necromanceranne** [comment]
It's not worth keeping the old. Just stick the sprites into the sprite repo.

**Review by Twaticus — APPROVED** [review]

**Comment by calliophis-maculiceps** [comment]
what is this warframe overwatch bullshit, can we not keep the goofy looking suit for a goofy antag, this looks so fucking edgy for no reason, the sprite isnt even better

**Comment by Serxule** [comment]
just looks like darkmode medical modsuit, dont really like it

**Comment by Ebin-Halcyon** [comment]
> what is this warframe overwatch bullshit, can we not keep the goofy looking suit for a goofy antag, this looks so fucking edgy for no reason, the sprite isnt even better

Lol, lmao.

**Comment by dragomagol** [comment]
Would be nice (but optional) to move the old sprites to https://github.com/tgstation/SS13-sprites

**Pull request merged**
