### PR TITLE
FEATURE FREEZE, FEATURE FREEZE ABOVE THIS LINE

### PR DESCRIPTION
**Pull request by tralezab**
image

We will be doing a feature freeze for the month of August, to give maintainers a break from design discussions and to give some space for a few projects to maybe reach fruition.

## Freeze Rules

* New PRs under either Context Expansion, Mechanics, qol, and balance tags (Features) are subject to closure during the period of the freeze.
* Any Pull requests opened before the freeze begins are not subject to closure, allowing for longer term projects to get the scrutiny they require.
* Pull requests that are not labeled as a feature, but function as a feature in their solution is up to maintainer's to decide to close or allow.
* As always, everything can be super ultra double exempted from these by headcoder decision.
* All other PRs are allowed in the meantime.
* refactoring into tgui menus is allowed (source: https://cdn.discordapp.com/attachments/590280000977240105/871503150312456202/unknown.png)
* This image below (No developing features during the freeze. Don't wait it out, contribute!)
image

### CODE REVIEW

**Comment by Mothblocks** [comment]
can you write mothblocks on this pr somewhere

**Comment by Watermelon914** [comment]
balance prs too

**Comment by Mothblocks** [comment]
and potentially qol as well

**Comment by tralezab** [comment]
👍

**Comment by Mothblocks** [comment]
this isnt really drafted im just annoyed hwen it comes up in my bookmark

**Comment by Cyberboss** [comment]
Addendum, porting UIs to TGUI are fair game for the freeze

**Pull request closed without merging**
