### PR TITLE
Makes the autolathe repeat it's animation while it's still printing.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 
:cl: Dax Dupont
imageadd: Autolathe now repeats it's animation while printing.
/:cl:

[why]: Before you couldn't see that the autolathe was busy printing, now you can!
I made it rewind too so it looks like it's 3d printing by going over layers.

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by coiax** [comment]
One day that red toolbox will escape.

**Comment by GunHog** [comment]
Brilliant!

**Comment by LarissaMayrink** [comment]
Thats one of those little thing that has always been a bother to everyone but noone cares to fix. I'll see if i can get a actuall 'progressing' sprite done, but, not sure if i'm good enough for it.

**Comment by LarissaMayrink** [comment]
Here, try this. Maybe its too long, but hey, i tried. Also, yes, i realize it goes one pixel lower somewhere midway through, but, eh, i editted it on DM and i'm too lazy to fix now. If you like and plan on using it just do the tweakpng thing to convert it.

https://goo.gl/izYz8r

giffo

**Comment by DaxDupont** [comment]
problem is that your sprite looks like it has a more definite end and won't work well with more variable length stuff.

**Comment by LarissaMayrink** [comment]
Neither does it makes any sense to always animate a toolbox, its just supposed to be eye candy while acting as a visual indicator that the energy is still up and not done yet, very few things can be actually representative. And it stopping midway trought a cycle doesn't look any worse than a closed cycle.

Also if someone is willing to code we could have a half a dozen eyecandy sequencies that play randomly, i just got 0 idea on how to code that, or maybe i do but i'm too lazy to test if it would work.

**Comment by DaxDupont** [comment]
My sprite mod works better in this regard.
Also we really don't need sprite bloat for this.

**Pull request merged**
