### PR TITLE
Expands round end pop recording as json export

### PR DESCRIPTION
**Pull request by Jordie0608**
Redesigns `round_end_stats` to hold loads more information for each mob such as name, ckey, health, location, job, cyborg module and escape status. NPC (non-minded, non-human or silicon) mobs are tallied using their initial name. Since this generates a lot more data that'd need to be sent over the atlantic ocean it is now exported to the round's log directory as a json file (also i didn't want to modify blackbox code for this). Also allows for misc additional information; here used for station integrity, regardless of if the station was nuked.

Refactored counting of vars used for `survivor_report()` to be counted during `gather_roundend_feedback()` and then passed down. Should be returning the same results as `count_survivors()` would but didn't test for that. Note not all vars are now used and thus are removed.

@AnturK @nfreader

Some example data:
`{"escapees":{"humans":{"1":{"name":"Louis Noton","ckey":"jordie0608","location":"Emergency Shuttle","health":54.5,"job":"Captain","species":"Human"}},"silicons":{"1":{"name":"Alpha 6","ckey":"jordie0608","location":"Emergency Shuttle","health":70,"module":"Engineering"}},"others":[],"npcs":{"Cayenne":1,"Medibot":2,"brain":1}},"abandoned":{"humans":{"1":{"name":"Braydon Alekseev","ckey":"jordie0608","location":"Captain's Office","health":100,"job":"Unassigned","species":"Lizardperson"}},"silicons":[],"others":[],"npcs":{"Mysterious Medibot":1,"creature":1,"Officer Beep O'sky":2,"Legion":1,"Paperwork":1,"MULEbot":2,"Tom":1,"Ian":1,"Poly":1,"Lizard":2,"Pun Pun":1,"Cleanbot":2,"Floorbot":1,"Officer Pingsky":1,"goat":1,"monkey":17,"Runtime":1,"grey baby slime (123)":2,"hierophant":1,"guthen":1,"necropolis tendril nest":1,"gubbuck":1,"blood-drunk miner":1,"butterfly":1,"Spaceman":3,"goldgrub":7,"crab":1,"space carp":1,"basilisk":1,"bee":24,"Medibot":1,"Unknown":5,"watcher":28,"legion":20,"goliath":23,"necropolis tendril":5,"bubblegum":1,"dwarf legion":1,"ash drake":2,"colossus":1,"mouse":9}},"ghosts":[],"additional data":{"station integrity":100}}`

capture

### CODE REVIEW

**Comment by nfreader** [comment]
Excellent!

**Comment by optimumtact** [comment]
@Jordie0608 @nfreader you guys ready for this, does MSO need to action anything?

**Comment by nfreader** [comment]
Nyet. Sorry, @Jordie0608, I completely misread this. Can we keep/update basic pop stats (survivors, escapees, dead) in the feedback DB? File lookups from the server are expensive and I won't be able to show this data on the single round page.

**Comment by Jordie0608** [comment]
Yeah ok.
@MrStonedOne I assume would have to set up the file to be accessible by ned.

**Comment by MrStonedOne** [comment]
@Jordie0608 at no point do you mention the file name and now i gotta go digg in the code like some commoner

**Comment by Jordie0608** [comment]
maxresdefault

**Comment by Cyberboss** [comment]
Trevis

**Comment by Jordie0608** [comment]
It builds fine, full build was cancelled during earlier travis outage.

**Comment by Cyberboss** [comment]
Ahh, sorry

**Comment by optimumtact** [comment]
where we at my ddues

**Pull request merged**
