### PR TITLE
Fucks around with fire and bomb defines.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This should make ttv bombs a bit easier to max cap (and change the meta around formulas yet again :smile:)

This should also make fires burn a touch slower (again)

### CODE REVIEW

**Comment by PKPenguin321** [comment]
wingo :+1:

**Comment by duncathan** [comment]
Prevents Robustin's salty tears :-1:
(:+1:)

**Comment by GunHog** [comment]
THANK YOU :+1:

**Comment by Robustin** [comment]
If it removes even 5% of the issues I'm seeing in toxins, I'll be happy.

Please note the biggest bug I'm seeing with TTV's right now is that detonating them from bags or other containers appears to have no effect on the user in some circumstances. 

Ex: Detonated a bomb from my bag, killed everyone around me, I survived with perfect health.

**Comment by duncathan** [comment]
@robustin that actually sounds like a pretty serious issue; you should make a separate report for it.

**Pull request merged**
