### PR TITLE
Fixes AI law changes to no longer be restricted by z-level. AKA, kills powergaming antags out of AI subversion

### PR DESCRIPTION
**Pull request by Iamgoofball**
If you're about to whine in the PR comments about how golems will ruin everything, go buy guns and kill the golems. Duh.
https://tgstation13.org/phpBB/viewtopic.php?f=23&t=20354#p454667
oranges declared this a bug in the admin exchange, and so it's being fixed.
:cl: Iamgoofball
fix: AI laws are no longer only changeable on the same z-level as the AI.
/:cl:

### CODE REVIEW

**Comment by Arianya** [comment]
:-1: Wrong way to fix this IMO, would be better to just make AIs not on station z-level be unable to interact with the station, which would kill taking the AI to lavaland.

**Comment by zxaber** [comment]
Just to be clear, we _want_ free golems changing AI laws, right?

**Comment by fluffe9911** [comment]
Bit confused how this is a bug when it looks like someone coded it specifically so you cant subvert across z levels and your just removing that section but whateves lol

**Comment by BeeSting12** [comment]
This isn't a fix, it's removal of a feature and a balance change. It's obviously intentionally coded that way

**Comment by BeeSting12** [comment]
imsxz's is better anyway

**Comment by zxaber** [comment]
The other question would be, is there any intended counterplay to _seeing_ someone nab the upload boards, other than killing the AI? Or are you supposed to just camp an upload and purge/asimov it every minute or so for the entire round?

**Comment by HomocidlePancakes** [comment]
Can't wait for this to go through and then reverted the week later

**Comment by Iamgoofball** [comment]
@ everyone above, get over it LOL

**Comment by Iamgoofball** [comment]
this is not a democracy

**Comment by XDTM** [comment]
Why are you even pretending this is a fix? It's not like anyone actually believes it, just tag it as a balance change and argue why you think it's good

**Comment by Iamgoofball** [comment]
oranges says it's a bug, it's a bug

**Comment by PKPenguin321** [comment]
I like that goof thinks he's oranges

**Comment by XDTM** [comment]
I mean, there is no reason for antagonizing everyone here, there might potentially be a point in allowing cross-z law changes but coming in and saying that _it's a fix, oranges says so, get over it, yada yada_ is simply counterproductive

**Comment by delaron** [comment]
PR made based on a potential quote from a oranges but done some from a third party within a complaint about about oranges.

Seems like Oranges hasn't said anything on the record about this. 

Meme PR is weak  and lazy.

**Comment by Iamgoofball** [comment]
@Anonmare Then the station will show up and fucking murder your face. As they should.

Therefore, emergent gameplay.

**Comment by Iamgoofball** [comment]
@delaron its oranges

**Comment by ATH1909** [comment]
> @Anonmare Then the station will show up and fucking murder your face. As they should.
> 
> Therefore, emergent gameplay.

Good luck finding me on Charlie Station, some random location in Lavaland, that big abandoned Russian space station, etc. without any indication of which one of those I'm in.

**Comment by Jordie0608** [comment]
Yeah, OK, Iamgoofball, I guess you could consider that a PR. What I'd consider a PR would be something acutally fun and engaging for the coders. In reality, half of the coderbus sat out non-compiling, merge-conflicted, unable to code while the lucky coderss just manage to get all the good boy points. If this is going to be a pattern for your "PRs' (Grudgecoding) then I'd prefer you just `git push -tg-station --delete patch456` while you're ahead. Next time this happens, there will be a maintainer complaint. You have been warned

**Comment by epochayur** [comment]
image

**Pull request closed without merging**
