### PR TITLE
Makes orange colored papermache not burn into chasms

### PR DESCRIPTION
**Pull request by DaedalusGame**
:cl:
fix: fixes lava burning into chasm tiles i hate hate hate hate them so much grrrr
/:cl:

Ok we get it the fire is hotter than the surface of the sun but SO IS LAVA

### CODE REVIEW

**Comment by imsxz** [comment]
can lava evaporate?

**Comment by imsxz** [comment]
https://ntrs.nasa.gov/search.jsp?R=19660041998

**Comment by imsxz** [comment]
feature, don't remove it

**Comment by DaedalusGame** [comment]
I promise you that irl, 6000 kelvin don't magically evaporate lava and then proceed to replace it with an instant deletion chasm that has ugly seams with the lava and also allows you to construct on them when lava doesn't

**Comment by Kromgar** [comment]
@DaedalusGame can you fix acid melting lava into chasms?

**Comment by DaedalusGame** [comment]
I wanna say this should fix everything that can "break" lava: acid, fire... admin qdel... but I haven't tested acid

**Pull request merged**
