### PR TITLE
Removes colours from teleporter speech

### PR DESCRIPTION
**Pull request by coiax**
The only colours allowed are the clown loudhailer.

### CODE REVIEW

**Comment by Kromgar** [comment]
But why?

**Comment by Supermichael777** [comment]
should use visible message because its on a screen.

**Comment by Kromgar** [comment]
@Supermichael777 This

**Comment by optimumtact** [comment]
For what reason?

**Comment by coiax** [comment]
BECAUSE YOU CAN'T TALK IN COLOURS

**Comment by optimumtact** [comment]
This is quite silly, alerts from centcomm come up in big flashy red even though you can't speak in red because you want the player to pay attention to it.

Same with command headphones etc.

Please do not sacrifice gameplay for realism

**Comment by coiax** [comment]
No, the TEXT IS RED, regardless of where you hear it! A machine talks in red over the radio!

**Comment by optimumtact** [comment]
Yes

**Comment by Shadowlight213** [comment]
>Coiax can't hear colors

**Pull request merged**
