### PR TITLE
makes glitter use new atmos overlays

### LINKED ISSUE #41564: glitter doesn't look realistic
the new plasma and N2O overlays don't match glitter decals any more. Update glitter and spread ""plasma floods"" again!

### PR DESCRIPTION
**Pull request by imsxz**
:cl: imsxz
fix: glitter now uses the updated atmos overlays
/:cl:
Fixes #41564

### CODE REVIEW

**Comment by MMMiracles** [comment]
this isn't glitter anymore its FOG

**Comment by imsxz** [comment]
fog you

**Comment by Cyberboss** [comment]
The new atmos overlays clearly do not look like glitter

**Comment by improvedname** [comment]
Just rename it to pink fog

**Comment by subject217** [comment]
Now you can just never notice that the glitter is there because the atmos overlays are impossible to see. This is clearly a glitter nerf.

**Comment by nicbn** [comment]
The joke doesn't work now, add a new item with a name that matches the sprite

For the glitter either remove it or just keep it as is, it doesn't scare anyone but the joke still works

**Comment by Bawhoppen** [comment]
Just rename it to slime or something similar.

**Comment by ninjanomnom** [comment]
Colorized micro particles

**Comment by nicbn** [comment]
> Colorized micro particles
aka gas

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Rename to fog

**Comment by optimumtact** [comment]
rename it yourself

**Pull request merged**
