### PR TITLE
Novaflower and watermelon improvements

### PR DESCRIPTION
**Pull request by TZK13**
Novaflowers now ignite people with the amount of fire stacks applied depending on potency and you can now juice whole watermelons instead of just the slices.

### CODE REVIEW

**Comment by Lumipharon** [comment]
firestacks is an awful 'feature', if not bug. It means you're basically fucked if you don't have an extinguisher/non roll method of putting the fire out.

**Comment by TZK13** [comment]
It's fairly rare that a person has more than five fire stacks and personally I think it's pretty lame how incredibly easy it is to put yourself out what with it only taking one roll to deal with five fire stacks or less and the abundance of fire extinguishers across the station.

**Comment by Lumipharon** [comment]
100 potency novaflowers: 20 firestacks.
Max potency is not hard to get, and with that much fire you're literally fucked if you don't have an extinguisher/shower/space.

**Comment by TZK13** [comment]
Alright, I've halved it.

**Comment by TZK13** [comment]
A novaflower with 100 potency now applies 5 fire stacks which is 1/4 of what it was originally.

**Pull request merged**
