### PR TITLE
lowers portable pump max pressure to 25 atm

### LINKED ISSUE #24643: Portable Air Pumps cause plasma floods.
Every so often when overfilling plasma tanks with cold plasma using a portable air pump attacked to a connector port, the portable air pump will overshoot the target pressure causing the plasma tank to rupture and flood the compartment.

Steps to reproduce:
1. Attach a portable air pump to the connector port of an active cooling loop.
2. Set to max, and "Out" to empty the tank.
3. Flip to "In" to fill the tank.

Overshoot seems more dramatic if there are active fridges on the same pipenet.

Seems related to lag.

I ahelped this first few times this happened. Admins seem to understand that this happens regularly

### PR DESCRIPTION
**Pull request by duncathan**
Fixes #24643. Being able to fill a tank literally to bursting was a terrible idea and bound to cause issues like this.

:cl:
tweak: Portable air pumps can output to a maximum of 25 atmospheres.
/:cl:

### CODE REVIEW

**Comment by RandomMarine** [comment]
This bandaids the issue with a balance change instead of actually fixing it.

**Comment by duncathan** [comment]
The primary issue in this case is that tanks are allowed to fill to bursting. There is no bug to resolve. The pumps are moving the appropriate amount of moles, but due to differences in thermal between mixtures post transfer pressure increases.

**Comment by RandomMarine** [comment]
After some testing with empty but warmed tanks and canisters/pumps, it does make some sense that there would be some expansion.

But in this case, I disagree with the change because it's padding corners. May as well disallow people from opening canister valves without a tank if this is the direction we want to go.

**Comment by duncathan** [comment]
Portable air pumps should never have been able to output 30 atm in the first place. If I didn't want to avoid controversy I would've reverted it to 10 atm like it used to be. It's not "padding corners"; it's reverting a stupid decision made by somebody uninformed.

**Comment by RandomMarine** [comment]
Hold the phone.

Just a couple weeks ago I was able to pump a ton of plasma into a pipenet, chill it to 2.7k, and have an air pump suck out a tank's starting plasma then pump it back in to 3039kpa with no problems.

Just testing today now, there's _always_ a leak. Something else has changed this.

**Comment by SgtxRootbeer** [comment]
Sooooooo... It's a balance change disguised as a fix

**Comment by duncathan** [comment]
Nah, it's a fix that happens to have minor balance implications. I really don't care if it's a little bit harder for you to make single tank max caps.

**Comment by evsey9** [comment]
have fun trying to explore space without having your backpack full of oxygen tanks now
air pumps aren't used only for toxins.

**Comment by Grazyn** [comment]
There is definitely something wonky going on with portable pumps that didn't use to happen before (and I mean like until a few days ago). You used to be able to fill empty tanks with cold gas at a target pressure with no expansion, now the gas always expands and can even make the tank rupture and gib you. See #31802

If this is a recent change, it's a major one but I see nothing in the changelog. This will cause people to gib and wreck the place simply by filling a tank with supercooled gas, and you don't even need high pressure, you could gib just by setting the pressure to 1000 kPa if your gas is cold enough (e.g. upgraded freezer).

**Comment by Grazyn** [comment]
2e4e28461b64a8826f336b2a105928f2

This is what happens if you fill an empty tank with -270 °C oxygen and target pressure 1000 kPa. Until last week I was able to fill any tank with 3000 kPa of supercooled gas without any problems. Something has changed.

**Comment by duncathan** [comment]
@Grazyn that's an oversight on my part; the expansion is intended so this pr is still needed but the scale at which it's happening was accidentally increased

**Comment by duncathan** [comment]
@evsey9 I used to explore space with a single tank at 10 atm. 25 atm in a large tank lasts a hell of a long time.

**Comment by Grazyn** [comment]
When was the expansion added? It's still a major change, since you can no longer fill a tank with gas at a set temperature and pressure without calculating it beforehand. Also, how does it work exactly? Can a tank explode when heated from the outside (e.g. in a fire or in a hot room due to the gas expanding inside it)?  Is there even a way to cool down a tank?

**Comment by Robustin** [comment]
Wow overfilling is dangerous and carries a risk of bad shit happening. Sounds fine to me. This is a beloved feature and nerfing it because someone ruptured their tank is silly.

**Comment by duncathan** [comment]
@Grazyn expansion of pressure due to differences in thermal energy has existed since long before tgstation ever existed. The magnitude it's happening at right now is less than two weeks old, however.

**Comment by Grazyn** [comment]
I only noticed expansion before while mixing 2 different gases, but never while filling an empty tank. Let's say you wanted 1000 kPa of cold pure O2 in an empty tank, are you saying that you could end up with higher pressure (and higher temp) if you set the pump or canister to 1000 kPa due to in-tank expansion? Because this is not how it worked (even if it was intended to)

**Comment by duncathan** [comment]
it was very, very minor in the vast majority of cases. not even one kPa of pressure difference, typically. but it was enough that (as in this case) you could go over the threshold for leaking.

**Comment by Grazyn** [comment]
Alright thanks for clearing it up. Expansion is so skewed now that filling tanks is like playing Russian roulette.

**Comment by zOMGie9** [comment]
I made an account just to say this, but I'm an atmos main and all you did was nerf atmos and not fix the problem. Pumps still drastically overshoot target pressure and blow up tanks, and this only started happening as of about a week ago. Some other recent change broke them. This screenshot was taken as a tank exploded in a pump filled with -200C o2. Before this nerf the tank would hit about 8000kPa and explode, but just a week ago they would always hit exactly the target pressure no matter what temperature.
atmos problem

**Comment by evsey9** [comment]
oh, well, 2533 kPa in a tank isnt THAT bad. thats 1-2 less flamethrower shots from a full plasma/oxy tank, though, so.
also, @duncathan i was talking about space exploration with a jetpack ( like the CE's hardsuit )

**Comment by duncathan** [comment]
@zOMGie9 that's a distinct but related issue addressed in #31823.

Please guys, stop telling me that a week old change is what's causing an issue that was reported over 7 months ago. It's ridiculous.

**Comment by duncathan** [comment]
@evsey9 ah, the jetpack complaint is reasonable. even still, the limit after this change is 2.5 times the original limit. the only reason the buff to 30 atmospheres got in was because I wasn't active at the time to stop it - it was bound to cause issues no matter how good the intent. 25 atmospheres prevents the issue but tries to maintain the genuine QOL improvement of increasing the limit.

**Comment by zOMGie9** [comment]
@duncathan Just because I knew you were wrong here I downloaded the code from one week ago and compiled it, and ran it side by side with the current code. Left side is one week ago right side is current.
Both are just slightly cooled oxygen in an air pump.
Explain this:
https://www.youtube.com/watch?v=BkX2JizC6jE&feature=youtu.be

**Comment by RandomMarine** [comment]
\>the only reason the buff to 30 atmospheres got in was because I wasn't active at the time to stop it
2017-10-16 23_25_02-raised maximum pressure output of air pumps by nullbear pull request 16883

It's okay to change your mind about something a year later. But don't pretend that you never approved of it in the first place.

**Comment by duncathan** [comment]
oh shit you're right lmao
my bad. I'd only been back for two weeks at that point so I totally forgot. in that case the original decision was uninformed on my part too

**Pull request merged**
