### PR TITLE
New barsign!

### PR DESCRIPTION
**Pull request by Cheridan**
In honor of https://www.reddit.com/r/SS13/comments/322cm1/ss13_confirmed_isis_recruitment_shill/

2ougadp

We need more subliminal messages to appease our overlords
Adds some punctuation to sign descs too.

### CODE REVIEW

**Comment by Chocobro** [comment]
HAHAHAHAHA

**Comment by optimumtact** [comment]
You would've gotten a special backer preview of this if you support Cheridan's patreon

/endshill

**Comment by Chocobro** [comment]
i didn't even know he had one but okay

**Comment by Man-Shroom** [comment]
>reddit link
Embarassing.

**Comment by Cheridan** [comment]
show us on the doll where reddit touched you

**Pull request merged**
