### PR TITLE
OHH NO NOT THE BEES

### PR DESCRIPTION
**Pull request by PKPenguin321**
deactivates holodeck bees

this PR was unprompted i was just sitting at home one day and thought "hey what if i deactivated holodeck bees" thank you and goodnight

### CODE REVIEW

**Comment by Durkel** [comment]
:salt:

**Comment by Archie700** [comment]
>i ded

**Comment by PKPenguin321** [comment]
??? i don't understand what you mean, this was unprompted?

**Comment by PKPenguin321** [comment]
darn i wanted to do this without map edits but i don't think that's super possible now

**Comment by PKPenguin321** [comment]
fucking mapmerger is stupid
i need to add python to my PATH or something [(like in this guide)](http://superuser.com/questions/143119/how-to-add-python-to-the-windows-path) but in step 6 in that guide i dont actually know what the path is that i enter?
ugh

**Comment by ike709** [comment]
@PKPenguin321 Uninstall python and then reinstall it, and during reinstallation, make sure to tick the box that says something like "Automatically add Python to Windows PATH"

**Pull request closed without merging**
