### PR TITLE
Adds a note to maintainer guidelines

### PR DESCRIPTION
**Pull request by MrsTonedOne**
image
image

### CODE REVIEW

**Comment by Time-Green** [comment]
oh man wait until goof hears you skipped thr 24 hour waiting period

**Comment by MrStonedOne** [comment]
@Iamgoofball

**Comment by AMonkeyThatCodes** [comment]
dude i never believed weed could do harm to your brain but if its not the weed i dont know what it is.

**Comment by interestingusernam3** [comment]
mso_photo

**Comment by rellyreri** [comment]
concider

**Pull request merged**
