### PR TITLE
Here I was, alone in the codebase, completely twisted on BYOND, no IDE, no commit logs for the repo, and on top of everything else, a gigantic fucking cancerous mass someone added to cargo code

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl:
add: Here I was
add: alone in the codebase
del: completely twisted on BYOND
tweak: no IDE
fix: no commit logs for the repo
wip: and on top of everything else
experiment: a gigantic fucking cancerous mass someone added to cargo code
/:cl:

As your attorney, I advise you to drive at top speed, it'll be a god damn miracle if we can get there before you turn into a wild animal.

ha ha emags allowing you to order infinite traitor items is a good idea right guys?????????????????💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩 💩💩💩💩💩💩💩

### CODE REVIEW

**Comment by ma44** [comment]
you can remove emag just by screwdriving the console then reconstructing it. 

Also slap a detective onto the person that opened the crate and it's the easiest way to catch a traitor.

Also which cargo tech casually looks at a person ordering null crates and doesn't care?

**Comment by Iamgoofball** [comment]
@ma44 why would the crew remove free traitor items lmao are you high

**Comment by evsey9** [comment]
Null crates are the greatest thing for Traitor QM, and you want to remove it?
Haha no.

**Comment by AnturK** [comment]
Keep the title readable and i'll reopen it.

**Comment by callanrocks** [comment]
He can't even make it a serious commit.

**Pull request closed without merging**
