### PR TITLE
Adds marker beacons to miner borgs

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Miner borgs can now place marker beacons from a storage of 30.
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
There's a slight problem that they might spam these on the station as a generic lighting solution with higher or regenerating power charges (slime cores etc) in low power conditions

**Comment by KorPhaeron** [comment]
Fwoosh has a good point

**Comment by GunHog** [comment]
Independent cooldown?

**Comment by octareenroon91** [comment]
It's fine: marker beacons aren't going to be a preferred source of light. What they emit is weak and colored.

A few times a week, someone might ask a mineborg to drop mood lighting in their maint bar. That's all.

**Comment by ChangelingRain** [comment]
They don't actually cost charge, that was me misunderstanding this bullshit energy storage system

**Comment by lzimann** [comment]
Seems to take a long time to be a problem. If anything can always decrease the stack size.

**Pull request merged**
