### PR TITLE
Updates the brain damage gibbering string: HEEERE'S THE DEALIO!!! edition

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
Based on this:
https://tgstation13.org/phpBB/viewtopic.php?f=7&t=30355
Originally suggested by Craig via forum post.

## Why It's Good For The Game
Comedy

## Changelog

:cl: itseasytosee
expansion: Brained damaged people know what the dealio is now.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
A) your space formatting is wrong
B) we rarely accept new brain damage lines.

**Comment by itseasytosee** [comment]
worth a shot :shipit:

**Comment by optimumtact** [comment]
the YAML file is space indented, you've added tabs.

**Comment by Mothblocks** [comment]
I don't really want more of these

**Pull request closed without merging**
