### PR TITLE
Removes ei nath from spellbook

### PR DESCRIPTION
**Pull request by Bawhoppen**
Everyone agrees its the most hated spell and OP,
theres little to no counters to it, and it just isn't fair for wiz rounds

:cl: 
add: Wizard's federation now no longer stocks disintegrate in their standard spellbooks.
/:cl:

### CODE REVIEW

**Comment by lzimann** [comment]
I DED PLS NERF(remove)

**Comment by MMMiracles** [comment]
heres what you do to counter it:

run away from the man with the giant glowing fist of death, apply liberal dose of preferred ranged weapon.

**Comment by Bawhoppen** [comment]
>implying that works with MM, blink, and jaunt spam

**Comment by Nanotransistor** [comment]
Works if you have a shotgun.

**Comment by Bawhoppen** [comment]
it doesn't work if you are stunned or they're too busy teleporting around to be shot

**Comment by Incoming5643** [comment]
Get out of my house.

Ei nath isn't overused horseshit anymore, it requires melee range, a free hand, and enough robustness/hulkness to not get ranged stun.

I've said it before I'll say it again, if you are in melee range of a wizard you <u>should</u> be very worried.

:salt:/10

:-1:

**Comment by KorPhaeron** [comment]
Is this PR a joke?

**Comment by Bawhoppen** [comment]
no. Nobody fucking likes EL nathers

**Comment by Aloraydrel** [comment]
can we post memes in the meme pr?

**Comment by KorPhaeron** [comment]
Lets buff EI nath to work while stunned again instead

**Comment by newfren** [comment]
Looking at the stats can we just make Ei Nath a ranged gib? Then maybe more wizards would take it.

**Comment by Bawhoppen** [comment]
the main point is that ei nath is just not fun for anyone

also none of the people who said they'd support me are here goddamnit

**Comment by PKPenguin321** [comment]
PJSalt

:-1:

**Comment by GunHog** [comment]
Fun removal. Wizard is HARD, it is not supposed to be "fair". A fair fight against a wizard means that the 60 people he has to fight all have a "fair" chance to kill him. Too much.

**Comment by Bawhoppen** [comment]
welcome to video games where you have fun
murderbone is not fun

**Comment by GunHog** [comment]
I disagree! Murderbone is fun for the guy doing it!!

**Comment by PKPenguin321** [comment]
also fun to watch and fun to combat
if you seriously get so salty about dying that you refuse to admit you at any point had fun maybe this isn't the game for you

**Comment by Bawhoppen** [comment]
its just too unbalanced as it is

**Comment by PKPenguin321** [comment]
i don't think you're taking the concept of 1 wizard vs 70~ person crew into account when you're considering your balance factors

**Comment by Incoming5643** [comment]
say it with me folks

"You're never supposed to 1 v 1 a wizard"
---

**Comment by Bawhoppen** [comment]
I don't think you take into account the extreme mobility wizards have

jaunt and blink recharge extremely quickly, as soon as you get hit you jaunt away, heal, and keep el nathing

**Comment by PKPenguin321** [comment]
maybe wizards have all that mobility and power because they have to fight a 70~ person crew and that is why it has been balanced for several years
*maybe* you're being a salty fuck
hmm

**Comment by Incoming5643** [comment]
Travel in groups, don't get separated. Be prepared. If you're alone and see the wizard start to phase in, run like hell. If the wizard catches you alone on his terms you've already lost.

**Comment by Bawhoppen** [comment]
@PKPenguin321 don't try and interpret emotion through text, to me it seems like you're mad I'd even suggest removing it

**Comment by PKPenguin321** [comment]
>changing the subject and not even trying to argue for your stance

just close the pr you nerd

**Comment by Bawhoppen** [comment]
you're the one who starting calling me salty bro

and I'm not closing it unless I hear an actual good argument, the maintainers can decide

**Comment by Incoming5643** [comment]
I've given enough good arguements, here's a shitty one:

It's classic

**Comment by Bawhoppen** [comment]
best argument I've heard so far

**Comment by PKPenguin321** [comment]
>and I'm not closing it unless I hear an actual good argument, the maintainers can decide

\>the wizard having to fight 70 people by himself isn't a good argument
the only person with no good argument is you. "it's OP he's too fast and strong" isn't a real argument.

**Comment by Bawhoppen** [comment]
MM, einath, jaunt, blink, and one other freeby spell = whenever the wizard appears out of the woodwork MM and atleast someone is going down in your group and killed, then even if you got any shots off on him, he jaunts back into the walls and heals and does it all over again

**Comment by PKPenguin321** [comment]
that can be done with literally any spell that does damage (fireball, lightning). ei nath has like a half hour cooldown. it's not nearly as efficient and overpowered as you think it is.

**Comment by Bawhoppen** [comment]
its because its a 1shot ggnore
go into the server right now and ask and most people will agree its overpowered and silly

I'm not syaing this is the only unbalanced wiz spell, but this one is pretty disliked

**Comment by PKPenguin321** [comment]
>go into the server right now and ask and most people will agree its overpowered and silly

i fucking will fight me irl

**Comment by Bawhoppen** [comment]
do it you fucking white-ass nigga

**Comment by PKPenguin321** [comment]
im asking if they want it removed y/n and they're just fucking memeing
is this what player feedback is like
oh god

**Comment by Bawhoppen** [comment]
i mean something crazy did just happen so maybe nows not the time

**Comment by Lumipharon** [comment]
ei nath is more or less balanced now that you can't GIB NERDS WHILE FUCKING STUNNED.

**Comment by Bawhoppen** [comment]
I mean I'd be happy making it so they need to be in crit or already dead to use it

**Comment by PKPenguin321** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=5477&p=142618#p142618

i just decided to make a thread since ooc is not actually helpful (who knew)

**Comment by Incomptinence** [comment]
who is this everyone agreeing to kill ei nath?

I mean if I had to name a spell i really hated it would be blink spam.

**Comment by Xhuis** [comment]
thumbsdown

**Comment by Steelpoint** [comment]
> One Wizard versus up to nearly one hundred people.

> We can't have him be too powerful guys. 

Ei Nath was already nerfed significantly, its fine as is.

**Comment by Bawhoppen** [comment]
thinking about this more, all of wizard needs rebalancing not just one thing at a time

**Comment by xxalpha** [comment]
When will people realize wizard is supposed to be a really powerful antag? If raging mages is unbalanced, fix that, and not the wizard.

**Comment by Bawhoppen** [comment]
thats not the point bro, he can be powerful but with current spells he can also be really retarded
anyways
don't think this is the last of me

**Comment by Incoming5643** [comment]
ragin mages was always a meme mode and was never intended to be a balanced experience

**Pull request closed without merging**
