### PR TITLE
Glass to glass structure spawner and also...

### PR DESCRIPTION
**Pull request by kyrahabattoir**
Moved a pipe under a window rather than a wall (ez-er access)
Fixed the cook not having a roundstart spawn point.

### CODE REVIEW

**Comment by CorruptComputer** [comment]
Screenshot?

**Comment by kyrahabattoir** [comment]
Not trusting me hm?

**Comment by CosmicScientist** [comment]
If someone is inside the station itself, can they see the sign on the bottom left without the airlock being open?

**Comment by CorruptComputer** [comment]
Move the bottom left airlock warning sign to the right side and then :+1:

**Comment by kyrahabattoir** [comment]
i'll just move all the signs on the inner side of the airlocks.

**Comment by CosmicScientist** [comment]
:+1:

**Pull request merged**
