### PR TITLE
[WIP] Ports Runescape-Style Messages from Beestation

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request

This PR is a port of the [Runescape-style messages PR from Beestation](https://github.com/BeeStation/BeeStation-Hornet/pull/1591).

**I've tagged this as WIP as this is the literal port of the code from Beestation, but I would like to clean it up to a reasonable code standard prior to merging**

The following photos are gracefully borrowed with great thanks from the original PR on Beestation.

image

image

[Video of messages in action](https://gfycat.com/inconsequentialillegallemming)

## Why It's Good For The Game

Makes local chat a lot easier to see, helps to alleviate pressure from highpop when radio chatter fills the chat window rapidly.

## Changelog
:cl: bobbahbrown / CthulhuOnIce
add: Ported Runescape-style messages from Beestation, now you can advertise your gold selling business in style.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
> I've tagged this as WIP as this is the literal port of the code from Beestation, but I would like to clean it up to a reasonable code standard prior to merging

Bit of a dick comment. You're welcome to contribute towards the original one before porting.

**Comment by ZeWaka** [comment]
Maintainers might want to read my comment on the original PR before even considering merging this.

**Comment by bobbahbrown** [comment]
closing as this is a big old license violation in the making

**Comment by jacklecroy** [comment]
There are plenty of goon assets in the game

**Comment by bobbahbrown** [comment]
> > I've tagged this as WIP as this is the literal port of the code from Beestation, but I would like to clean it up to a reasonable code standard prior to merging
> 
> Bit of a dick comment. You're welcome to contribute towards the original one before porting.

Closed PR but as I said in coderbus I poorly late-night-posting worded this, I more or less was meaning to clean it up as in add documentation matching the dmdoc compliance required by tgstation's repository

bad wording moment

**Comment by Mickyan** [comment]
but I need this

**Comment by Qustinnus** [comment]
@Crossedfall its true though lol.

**Pull request closed without merging**
