### PR TITLE
Brutally butchers dr. beepers soul with new sprites.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Tweaks the medibot sprites to fit the new medkits some more.
Also removes a bunch of unused medibot sprites.

## Why It's Good For The Game

Current ones look silly right now.
And
Soul is bad for the game.

## Changelog
:cl:
imageadd: Changes medibot icons to more closely fit with the new medkit sprites.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
butchers soul some more

**Comment by plapatin** [comment]
no no no no no no no no no no. no. no. don't do this please my SOUL can only take so much

**Comment by TheChosenEvilOne** [comment]
S O U L L E S S, they feel too blocky though.

**Comment by Dawson1917** [comment]
I'm going back to killing these things on sight

**Comment by AcapitalA** [comment]
I unironically like the looks of it, feels modern.

Also RIP Doctor Beeper's soul.

**Comment by Akrilla** [comment]
what am I looking at nemvar what did you do oh god oh fuck why why why

**Comment by nemvar** [comment]
It's a box with wheels.

**Comment by MMMiracles** [comment]
imma tip it over

**Comment by bgobandit** [comment]
right now they look too similar to normal medikits imo

**Comment by Tlaltecuhtli** [comment]
if you are gonna add 2 wheels to a medkit and call it a sprite get out of here

**Comment by AcapitalA** [comment]
> if you are gonna add 2 wheels to a medkit and call it a sprite get out of here

Same could be said for the original sprite tbh.

**Comment by Twaticus** [comment]
>arm isnt out at all times

fix it fix it fix it you cant do this!!

**Comment by PKPenguin321** [comment]
you joke about the soul thing but it still hurts



also wtf why are the green/yellow light states completely separate icons instead of just an overlay?

**Comment by CRITAWAKETS** [comment]
Wheres the percieved uneven lines that look like it has a face?

This is the reverse of SOUL. This is outright reverse SOUL.

**Comment by cacogen** [comment]
Honestly I don't like these sprites that much but it's not like old ones were good. They were very old.

**Comment by lolman360** [comment]
I ask you good sir, **_why_**?

**Pull request closed without merging**
