### PR TITLE
Revives rust heretic rework

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Revives the https://github.com/tgstation/tgstation/pull/65361 rust heretic rework

## Why It's Good For The Game

Removes RNG shit from the rust heretic and adds more progression

## Changelog

:cl: GoblinBackwards
add: Heretic now has its ability to rust turfs scale with knowledge.
balance: Heretics now start off with limited rusting abilities, but grow to be able to rust almost anything as they progress
balance: Reinforced walls/floors can be rusted after unlocking Mark of Rust
balance: Titanium and plastitanium can be rusted after unlocking Toxic Blade
balance: Rust heretics can spread rust to almost anything after ascending.
balance: When playing as a non-rust heretic your rusting ability improves when you learn aggressive spread, entropic plume, and when you ascend. You need at least two to rust reinforced walls, and all three to be able to rust titanium.
balance: Rusting reinforced walls is no longer RNG, and instead turns them into a regular rusted wall after being rusted twice.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
you should look at doing more fixes, opening 2 feature prs does lower your gbp a bunch

**Comment by SuperSlayer0** [comment]
Ok

**Comment by JohnFulpWillard** [comment]
im gonna assume editing one line of spider code isnt what this pr is supposed to do, and will draft it.

**Comment by SuperSlayer0** [comment]
> im gonna assume editing one line of spider code isnt what this pr is supposed to do, and will draft it.

oh shit

**Comment by SuperSlayer0** [comment]
I accidentaly pushed the wrong branch

**Pull request closed without merging**
