### PR TITLE
Fixes a grammar issue with lockers

### LINKED ISSUE #17578: typographical error when locking lockers
`You locks the miner's equipment.`

### PR DESCRIPTION
**Pull request by Crushtoe**
Lockers no longer say that 'You locks X'

Fixes #17578

### CODE REVIEW

**Comment by bgobandit** [comment]
This kills tactical lockers. Locking lockers while timing the location of the text box to obscure your character, making it harder to hit. Yes, i am serious.

**Comment by Crushtoe** [comment]
Learn it with one less character being present. There's your solution.

**Comment by optimumtact** [comment]
That's an obscure in joke around here, so don't pay them too much attention.

**Comment by Crushtoe** [comment]
I don't know an in-joke? Dang. I'm out of touch these days. Need more artyom and badger.

**Pull request merged**
