### PR TITLE
Quick access hotkeys for backpack and belt

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: ninjanomnom
add: You can use Shift+E or Shift+B for belt/backpack respectively to quickly put in your held item or take out the most recently added item.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
time to abuse quickdraws!

**Comment by ShizCalev** [comment]
Time to become Bob Munden.

**Comment by XDTM** [comment]
Can you pull out mousetrap bombs with this?

**Comment by ninjanomnom** [comment]
ugh, yes. I'll fix that later

**Comment by outbools** [comment]
👍

**Comment by PKPenguin321** [comment]
Can you put a bag of holding into a bag of holding with this

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Update the hotkey help

**Pull request merged**
