### PR TITLE
Talisman of Construction is more useful

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: The talisman of construction now has 25 uses, each of which can convert a sheet of plasteel to a sheet of runed metal. It can still convert metal into construct shells, and requires no specific amount of uses to do so.
/:cl:

Some grammar fixes

### CODE REVIEW

**Comment by InsaneHyena** [comment]
For what purpose?

**Comment by ChangelingRain** [comment]
The cult can't make the structures, because they're invulnerable, so I'm removing their ability to use them at all because >lavaland

**Comment by FantasticFwoosh** [comment]
Can't you just require hitting a structure with a tome/splashing it with holy water to deactivate its "dark protective aura" so they can deconstruct it?

It really seems like a unreasonable grudge revert on the clause for the creator of the content overlooking the fine detail of destroying what they make.

**Comment by ChangelingRain** [comment]
The cult already can't make the structures, I never particularly liked the gameplay they produced, and so this is what you get.

**Comment by TechnoAlchemisto** [comment]
Cult structures are fun. This isn't a bugfix this is a removal. Maybe you should fix them instead of completely removing something that makes a game mode better?

**Comment by ChangelingRain** [comment]
they can't make the gamemode better because kor already removed them

**Comment by TechnoAlchemisto** [comment]
I imagine Kor would have completely removed them if he didn't intend for them to be fixed but

@KorPhaeron

**Comment by KorPhaeron** [comment]
Maybe if we refactoring them as machines since Phil generalized machine health and they all process anyway

**Comment by ChangelingRain** [comment]
only one of them processes though

**Comment by Kromgar** [comment]
Bloodcult lost all of the cool gear that ratvar cult already fucking has

**Comment by InsaneHyena** [comment]
> implying Ratvar can get any more stronger

**Comment by ChangelingRain** [comment]
#20246 got made!
As such, this pr is now the remaining non-stuff-removal fixes that it would have been otherwise.

**Comment by Kromgar** [comment]
But why 50 uses? Why does it need to be 50 uses ?

**Comment by ChangelingRain** [comment]
It's one use per sheet. Is 50 too many?

**Comment by Cheridan** [comment]
50 uses is kind of in the "so high you might as well make it unlimited" range.

That said, I don't think it being unlimited would be bad. Bloodcult is totally reliant on the items from their starting paper, so if they run out before they establish a foothold they can't actually do anything.

**Comment by ChangelingRain** [comment]
cult's limit right now is basically 'do they know how to churn out talismans via the imbue rune' and that's reaaaally not ideal or good design.

**Comment by Kromgar** [comment]
You should just be able to make talismans out of your book. It has paper in it

**Comment by ShadowDeath6** [comment]
worst peeve I have with blood cult is that you need paper to use literally the most important utility of the mode. I never got why it's considered a more offensive cult but clock cult has better mobility with the justiciar visor and guvax letting them convert anyone while alone, while cult needs to be in groups and has to consume paper to get reliable conversions going.

**Comment by TechnoAlchemisto** [comment]
paper really isn't hard to get covertly and easily though

**Comment by ShadowDeath6** [comment]
You still have to get it, though. If talismans are so imperative to cult then you shouldn't have the possibility of not getting it.

**Comment by XDTM** [comment]
Paper is so easy to get it might as well not be required, i guess

**Comment by optimumtact** [comment]
I dunno what this is nor do I understand the arguments but this has a lot of thumbs downs so it must be bad.

**Comment by ChangelingRain** [comment]
reeeeeeee all the thumbs down are from the structure 'removal'

**Comment by TechnoAlchemisto** [comment]
yeah basically what they said, i'll remove mine this is good

**Pull request merged**
