### PR TITLE
Fixes brooms again. Got caught in a refactor, sweeping up

### LINKED ISSUE #49925: Janitor's gear teleported around the station from his inventory
## Reproduction: Screw around with the wielded push broom enough?

We were playing as box station, traitor round, and I spawned in as Janitor, non-antag, and loaded up my kit to get to work. Some time into the round, I think a bit over an hour, after I've leveled my scrubbing skill to legendary, I became a syndicate sleeper agent, and was assigned to assassinate the detective, steal the medal of captaincy, and escape on the shuttle. Shortly after I was antagged, I purchased some gear: an emag, an agent ID, and a chameleon kit. I ran to the showers and, frequently honking the rubber duck inside as I moved around, started to change into my chameleon kit. I fumbled most parts of the kit and they went in and out of inventories and layers of inventories more times than I can count, but eventually I had everything on. After some moving around station, customizing my chameleon kit a bit more and stealing a botany tray and some chemicals, I disguised as the captain and tried to emag the shuttle console to recall the shuttle, but that didn't work. After that, I got back on the janicart, grabbed my janitorial cart once again, undisguised, bought a minibomb and a couple random items (including dart gun) and headed over to escape to catch the shuttle. There, at about 1 hour 30 minutes round time, a nightmare with envy's knife approached me and started slashing at the lights and APCs, then offered me the knife. I toggled my flashlight on and off a few times, and all of a sudden, my flashlight and tablet appeared on the ground beside me. There was no alert about the nightmare trying to take anything off me, and when I tried to pick it back up and put it back into my pockets, it acted like it had just been used inhand, like it was somehow codified as being  both in my pocket and in the hand that had just picked it up off the floor. Then my backpack and several items of my clothing (I think my shoes, gloves and hat) just vanished completely. I came to learn later that the clothing items had wound up in the hands of people on the other side of the station, while the minibomb and dart gun teleported directly  into the hands of people standing right beside me. The nightmare then proceeded to open fire with my dart gun while a random nearby scientist ran off with the minibomb. With nothing else left to do, I ran into medical and committed suicide with the janicart key. As soon as I died, all of a sudden my clothes popped back onto my body, and I think it was the original clothing I was wearing at the start of the shift - not the chameleon wear - but I'm not sure about that. I never got Envy's knife, and I don't think I was ever struck by it.

Update: Based on the comments, I'm pretty sure this was caused by some weird interaction with the push broom. I'm not entirely sure how I pulled it off, and I think it is one of the items that vanished from my inventory (my hands specifically) so I'm not sure how to recreate it. Either way, it caused some big time fuckery.

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Fully implements #49628, it seems like the fix got caught up in a refactor. #49422.

## Why It's Good For The Game

Maybe fixes #49925, I don't know, ask @Mickyan, I don't understand, I just sweep. 

This shouldn't be here. sweep sweep sweep.

## Changelog
:cl: LemonInTheDark, with theft from Mickyan.
fix: THE BROOM FIX DIDN'T JUST DIE, IT WAS MURDERED. I'm fixing that.
/:cl:

### CODE REVIEW

**Comment by Mickyan** [comment]
this is fine, I'm surprised this didn't get caught by merge conflicts in the two handed refactor

**Comment by nightred** [comment]
I just compared #49628 to this and the new check you added just now was not in that PR.
I made efforts to include the changes.

**Comment by Mickyan** [comment]
oh yeah you're right, this seems to be a slightly different problem

Not much to go on to figure out what caused it this time but this sanity check should definitely catch it

**Comment by Mickyan** [comment]
Upon further inspection my fix was actually missing from master but it was caused by #49433

**Pull request merged**
