### PR TITLE
Adds the Tulpa trauma

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: The Tulpa trauma has been added. You get a friend in your head who can talk. They can be annoying as fuck or helpful.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@xdtm didnt you already add this

**Comment by GunHog** [comment]
So, it is Split Personality, but a voice instead of control swapping?

**Comment by MoreRobustThanYou** [comment]
@GunHog sorta

@KorPhaeron that was imaginary friend, which is SLIGHTLYYY different (the friend is actually "visible")

**Comment by The-clown-known-as-Pepe** [comment]
add ability to have multiple tulpas

**Comment by WJohn** [comment]
this is redundant we already have the imaginary friend

**Comment by deathride58** [comment]
Tulpae already exist in the form of imaginary friends. If you're gonna reference weird shit from the darkest corners of the internet, at least reference them right.

**Pull request closed without merging**
