### PR TITLE
Makes gamemode odds show % at current population

### PR DESCRIPTION
**Pull request by AnturK**
WIP i'll throw in a cache there tommorow.

### CODE REVIEW

**Comment by RemieRichards** [comment]
>tomorrow

Tomorrow is Christmas!

**Comment by AnturK** [comment]
That won't stop me. (as long as i'm sober)

**Comment by Incoming5643** [comment]
Remember we have a limiting var for high pop now too that isn't in this yet.

**Comment by AnturK** [comment]
Oh right, will have to add that one too.

**Pull request merged**
