### PR TITLE
Canister frame code and UX improvements

### PR DESCRIPTION
**Pull request by Donkie**
## About The Pull Request
* Removed a bunch of duplicated code by making it more OOP.
* Added examine notes about what actions you can do at each stage.
* Fixed names being proper nouns
* Properly utilize the more modern screwdriver_act and use_tool etc procs
* Added being able to deconstruct a frame directly by applying wrench to it

Also did some minor fixes in atmos canister code:
* Removed their tier specific names because the tier number is displayed when examining anyways
* Improved welding act messages abit

## Why It's Good For The Game
This improves the user experience when dealing with the new canister frames which frankly were somewhat confusing before.

## Changelog
:cl:
tweak: Improved user experience when dealing with canister frames
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Welcome back donkie

**Review by Cyberboss — APPROVED** [review]

**Comment by Donkie** [comment]
Thank you @optimumtact 
After spending years discovering new programming languages and environments I've come to the conclusion that DM and byond is the best out there.

**Comment by LemonInTheDark** [comment]
F

**Pull request merged**
