### PR TITLE
Adds a sprite for sweet pea donuts in a donut box

### PR DESCRIPTION
**Pull request by Megarop**
## About The Pull Request
Adds a donut box sprite for the sweet pea donuts and sweet pea jelly donuts added by #54573.
This is what a box full of them looks like, next to a sweet pea donut outside of a box for comparison:
image
## Why It's Good For The Game
It stops this from happening:
image
## Changelog
:cl:
fix: Sweet pea donuts no longer cause a giant "error" sign to appear when you put them in a donut box.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
@Twaticus

**Review by Mothblocks — CHANGES_REQUESTED** [review]
You just made a file called donuts.dmi in the root instead of editing the existing one...?

**Review by Megarop — COMMENTED** [review]
I uploaded the updated donuts.dmi file there instead of where it's supposed to go, no idea how I didn't notice that, terribly sorry

**Comment by Jared-Fogle** [comment]
image

Can you keep the default state? Otherwise this issue can easily crop back up again.

**Review by Mothblocks — APPROVED** [review]
Everything is structured correctly, just needs a +1 from Twaticus.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
