### PR TITLE
Changes Monkey Tackling to Function Like Disarm Rework

### LINKED ISSUE #43386: monkey tackling still stuns

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request
Closes #43386

To clarify I based the knockdown on the existing knockdown to a solid surface

## Why It's Good For The Game
Monkeys shouldn't be excused from disarm overhaul

## Changelog
:cl: bobbahbrown
add: Monkeys now apply knockdown when tackling instead of stunning, and can stun you by tackling you whilst you are knocked down.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
1)Are we really hugboxing monkeys being too robust?
2)Shoves PR isn't even merged yet nerd.
3)
>Monkeys shouldn't be excused from disarm overhaul

Why? Player controlled monkeys can't even tackle.

**Comment by bobbahbrown** [comment]
> 1)Are we really hugboxing monkeys being too robust?
> 2)Shoves PR isn't even merged yet nerd.
> 3)
> 
> > Monkeys shouldn't be excused from disarm overhaul
> 
> Why? Player controlled monkeys can't even tackle.

I don't really see the issue with monkeys applying a knockdown instead of paralysis on tackling. Akin to the [yet unmerged] disarm rework pr, it makes interactions more interesting than purely "ok now you're stunned". It's not as much a nerf as it is a change of approach, in my opinion.

**Comment by HomocidlePancakes** [comment]
How can you make a mokey tackling you "more interesting"? This is a nerf that noone wants nor needs. Feels like a 4nr hugbox

**Comment by bobbahbrown** [comment]
> How can you make a monkey tackling you "more interesting"? This is a nerf that noone wants nor needs. Feels like a 4nr hugbox

this PR was made because someone wanted it #43386.

more interesting in that instead of just being stunned, you can now crawl and continue to interact instead of simply waiting to get up.

**Comment by bobbahbrown** [comment]
>This is a nerf that noone wants nor needs. 

>1)"Made because someone wanted"
>Great reason to nerf something already harmless

????

>2)Tackling is the only thing dangerous about monkeys. They are already not that hard to kill and you want to remove their only way to robust you(Oh and if you get tacled by a monkey it's your fault in the first place). It doesn't make it interesting.

weird flex but your argument implies that changing the effect from paralysis to knockdown is completely removing their ability to robust you, which is frankly not true.

on the topic of being interesting, please note that the existing effect will stop the player from doing any interaction but talking for 10 seconds.

is this interesting? no.

**Comment by HomocidlePancakes** [comment]
Ofcourse it won't completly remove their ability to harm you but it will reduce it significantly. Let's make all lasers deal 10 damage instead of 20. Why? Because why not. Can you still kill people with them? Sure, but good luck with that.

On topic of crawling being "interesting". Bruh.  As I said before you can't make monkeys tackling you more interesting.

**Comment by ExcessiveUseOfCobblestone** [comment]
Was this unintentional or something? I'm confused on what this fixes.

**Comment by bobbahbrown** [comment]
> Was this unintentional or something? I'm confused on what this fixes.

@ExcessiveUseOfCobblestone Sorry I should clarify, and did just edit the PR to reflect, that this is a feature request that was in an issue more than a bug. 

Once could consider it a consistency change, but it's better said a feature request I think.

**Comment by ExcessiveUseOfCobblestone** [comment]
> However, once knocked down, if you are shoved again it paralyzes for 4 seconds. This is the same length as the old disarm push.

Since you're using that PR as justification for the change, mind making it function similar (just the quoted, I don't need all the conditionals).

**Comment by bobbahbrown** [comment]
> > However, once knocked down, if you are shoved again it paralyzes for 4 seconds. This is the same length as the old disarm push.
> 
> Since you're using that PR as justification for the change, mind making it function similar (just the quoted, I don't need all the conditionals)?

@ExcessiveUseOfCobblestone done and done

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
I was waiting for the disarm pr

**Pull request merged**
