### PR TITLE
Fixes pretty much all spells having 10 times longer cooldowns than intended.

### LINKED ISSUE #53593: Revenant abilities
Issue reported from  Round ID: [145999](https://scrubby.melonmesa.com/round/145999) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1532

abilities take like 5 minutes to charge up, this is pretty dumb. please fix, its not worth doing anything except succ as rev

### LINKED ISSUE #53595: Spells take 10x longer to recharge.
## Round ID:
[145982](https://scrubby.melonmesa.com/round/145982)

## Reproduction:
Spells seem to take around 10x longer to recharge, i noticed this during my wizard round and decided to test it out later in the thunderdome, fireball takes around 1 minute, jaunt takes around 5, and ei nath takes about 10.
You can reproduce this by just using any spell and looking at the time it takes to recharge.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Fixes #53595
Fixes #53593

We're back again with my second fix related to #52981

This time spells! More specifically targetting wizard spells, but fixing anything that relies on proc_holder/spell in general - Including Revenants! How quaint! And heretics. Devil contracts and spells. Slaughter demon's blood crawl. Genetics powers. You know what? It just fixes everything. Ever. Oh yeah. And Santa's spell. Don't forget about Santa.

image

So anyway. What broke?

image

Spell proc_holders previously assumed a process() happened every 2 ticks and incremented charge_counter by 2.

They're now given a delta_time in seconds rather than in ticks.

image

This causes them to increment charge_counter by 0.2 instead of 2.

As a result, they're charging 10 times slower.

I just added the SECONDS macro to delta_time's value when it's added to charge_counter which effectively converts delta_time to its representation in ticks.

## VV Workaround For Admins

For an antag type such as Wizard who is able to pick all their spells in advance, the following will prove exceedingly useful.

image

`UPDATE /obj/effect/proc_holder/spell SET charge_max = charge_max / 10`

Note that any spells chosen AFTER this will still need to be changed manually. Similarly, geneticists, heretics and any others that get their spells and abilities over time may still need manual changes.

A VV method to accomplish that is below.

VV the player. Under `actions`, there should be a list of various spells. Each of these spells should have a `target` which is an `/obj/effect/proc_holder/spell` of some sort.

Locate the `charge_max` in this proc_holder/spell and divide it by 10. This will effectively grant the spell an equivalent cooldown to what it should have. 

image

## Why It's Good For The Game

Wizards are no longer useless with spells that have 10-fold increased cooldowns. Revenant spell cooldowns aren't 5 plus minutes. Basically, everyone gets happier except non-antags.

## Changelog
:cl:
fix: Various spells and abilities across reventants, wizards, genetics, heretics and others, no longer have cooldowns 10 times longer than expected.
/:cl:

### CODE REVIEW

**Comment by msgerbs** [comment]
Also fixes 53593

**Comment by ATH1909** [comment]
speedmerge

**Comment by Timberpoes** [comment]
> 
> 
> speedmerge

Pinged maintainers when I did the PR and there was no appetite for a speedmerge. For now, there are admin-usable workarounds that can be used to hotfix these issues on a round-by-round basis.

Be kind. Be polite. Be courteous. And good luck out there, gamers.

**Comment by Donkie** [comment]
Thank you ❤️

**Comment by AnturK** [comment]
I said this in the main PR already but i really don't like using SECONDS as conversion method here since it makes it really hard for unaware reader to understand. I'd suggest something like local CHARGE_PER_SECOND define instead.

**Comment by Timberpoes** [comment]
Both charge_max and charge_counter make reference to time values in seconds in their comments.

I can't see where any confusion would set in when you read the comments for both of those vars and see a delta time in seconds.

**Comment by ATH1909** [comment]
How does this interact with spells like Blink, which can have cooldown times measured in fractions of a second?

**Comment by Timberpoes** [comment]
The proposed change (multiply delta_time by 10 in some form) restores the status quo to before #52981 was merged.

Functionality before was to incremement the charge_counter by 2 every 2 ticks. Now we increment the charge counter by 2 every 0.2 seconds.

Fractional charge_max is handled how it always has been for `charge_type = "recharge"`. At some point charge_counter >= charge_max and the spell is ready.

**Comment by Donkie** [comment]
Yes I forgot to update all the charge_max of spells when converting this. Ideally they should be in seconds and not deciseconds, but charge_max is used 164 times in our codebase so keeping it in deciseconds is a lot easier.

You should update the comment at the definition for charge_max and charge_counter to reflect that it is in deciseconds. Also change default charge_max back to `10 SECONDS`

**Comment by Timberpoes** [comment]
> 
> 
> Yes I forgot to update all the charge_max of spells when converting this. Ideally they should be in seconds and not deciseconds, but charge_max is used 164 times in our codebase so keeping it in deciseconds is a lot easier.
> 
> You should update the comment at the definition for charge_max and charge_counter to reflect that it is in deciseconds. Also change default charge_max back to `10 SECONDS`

I didn't mention it, but I have now implemented your suggestions. Thank you!

**Pull request merged**
