### PR TITLE
∠( ᐛ 」∠)＿ !!SECURITY CHANGE!! DA MAN WIT DAT GOLDEN GUN !!SECURITY CHANGE!! ᕕ( ᐛ )ᕗ [NO CHILL] [DAYUM SON WHERE'D YOU FIND DIS]

### PR DESCRIPTION
**Pull request by pudl**
:cl: Quiltyquilty
rscadd: O shit waddup! The HoS's bluepilled e-gun has been replaced with a custom golden desert eagle!
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
The man with the **GOLDEN GUN!**

**Comment by Steelpoint** [comment]
Why not both?

Or make a multi gun, where you have one Energy Function but can instantly swap to using ballistic rounds. So a two in one gun?

Best of both worlds AND gives the HoS a pretty good gun.

**Comment by Cheridan** [comment]
As the man who has to single-handedly defeat wizards with instagib powers, this is the kind of weapon the HoS deserves.

**Comment by Steelpoint** [comment]
Excuse me, waiter, I don't see a merge symbol on this PR?

**Comment by Miauw62** [comment]
BRK BRK BRK

**Pull request closed without merging**
