### PR TITLE
Tramstation underpass changes

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
- Missing railings in the west wing added
- Disposal pipes and wires are properly below catwalks
- Adds tiles over plating, some glass for visuals, and makes the starlight recovery virus useful.

image

- 

## Why It's Good For The Game
Tram lower z-level looks better, has the missing railings fixed, gives a reason to make the starlight virus on Tram.
## Changelog
:cl: LT3
add: Added glass flooring to Tramstation's lower level.
fix: Tramstation's pipes and cables are now underneath the catwalk on the lower level.
fix: Fixed missing railings on Tramstation's west wing.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
it's a nice look, I worry that it might be taking away from the feel of the underpass as a large maint tunnel.

**Comment by Fikou** [comment]
soulless

**Comment by lessthnthree** [comment]
> it's a nice look, I worry that it might be taking away from the feel of the underpass as a large maint tunnel.

What about keeping the middle section as plating instead of smooth tile, and adding dirt back.

**Comment by MMMiracles** [comment]
the station is built into a giant asteroid why is there a big glass hole into space on the floor

**Comment by san7890** [comment]
> Fair. The SM loop has magic space tiles so I was thinking why not tram. I'll do a new PR with just the railings and such.

asteroid hole

**Comment by Wallemations** [comment]
> Fair. The SM loop has magic space tiles so I was thinking why not tram. I'll do a new PR with just the railings and such.

Could just be the other edge of the asteroid, but the entire lower half having glass would definitely be too much

**Pull request closed without merging**
