### PR TITLE
[SPRITE] Final Security Sprite Change | Bartender/HoP Armour

### PR DESCRIPTION
**Pull request by Steelpoint**
The final Security sprite change which even Paprika has (I assume) supported. This is also a change a lot of people on the forums and in game have supported. 

Relevant thread: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=2476

As such I present what Sec and all will appear in game.

From left to right.
- Security Officer(Image 1&2): Spawns with a Helmet, Beret in Locker.
- Tactical Officer: Three sets of Bulletproof Armour are in the Armoury, these use the old Ausops armour.
- Warden: Returns to the old red coat, keeps the old one in his locker.
- HoS: No change aside from uniform being red.
- Bartender: Spawns with the Corporate armour, now styled as "civilian" armour.
- HoP: His locker has a set of civilian armour.

### CODE REVIEW

**Comment by Steelpoint** [comment]
Lets keep it smooth and fun.

**Comment by vista-** [comment]
rip corporatecurity, i will miss you

**Comment by AnonymousNow** [comment]
As a journeyman complainer from a country of terminal complainers, I support this change with no complaints.

**Comment by pudl** [comment]
i like it, just wish sec colors weren't so dark

**Comment by Delimusca** [comment]
the red jumpsuit's left leg appears to be missing some pixels.
also what are those strap looking things on the civilian armour?

**Comment by Steelpoint** [comment]
Pockets.

Thanks for point out those missing pixels, I'll fix it.

**Comment by TZK13** [comment]
I strongly prefer the direction that's been taken in regards to the standard headgear for security officers being either berets or caps while helmets are left in the armoury, one needs only to look at the example pic to see just how faceless the helmets make you.

**Comment by Delimusca** [comment]
@TZK13 that was always a good thing though. the people who value their honour over a minor armour buff won't be wearing that helmet either way, so you can tell at a glance which faceless, soulless mook you should be throwing polyacid at.

**Comment by Dorsisdwarf** [comment]
Best of both worlds.

**Comment by paprka** [comment]
meh, remove civillian armor and give bartender/HoP the armor sec has. That armor honestly looks like a waistcoat, and I'd prefer if all standard armors looked identical. Other than that, this is good.

**Comment by drynwyn** [comment]
Yeah, I too dislike the "civilian" armor sprite

**Comment by Anonus** [comment]
Final final security sprite change: 2015 edition.
Actual feedback: I like corporate sec with grey jumpsuits more than red, sometimes-faceless goons.

**Comment by paprka** [comment]
Btw the old hos/warden clothes are fugly, I updated them for ausops' color palette here


mob
obj

**Comment by dannno** [comment]
this better not touch the warden's parade shit i s2g

**Comment by Yakk** [comment]
Did the warden's coat get a shade brighter?

**Comment by paprka** [comment]
probably, but then again i think i darkened it when i added the ausops styled armor to it ages ago I think

either that or someone mass-color changed like a moron

**Comment by Steelpoint** [comment]
Warden's Coat nor the HoS's Parade uniform have been touched.

**Comment by Steelpoint** [comment]
Ok. I've updated the HoS/Warden uniforms to the more refined one's pap gave, I've also given the Warden's Coat the more muted colour pallet that other Sec uniforms use.

screenshot 2015-01-22 13 06 45

**Comment by paprka** [comment]
looks gud

**Comment by Steelpoint** [comment]
Already done.

**Comment by pudl** [comment]
can officers no longer spawn with the bowman and just start with normal headsets?, also the tactical helmet doesn't look nearly different enough. i know this was a past problem but im bringing it up now especially.
i wish we could use my security resprite tbh

**Comment by Steelpoint** [comment]
Well the bowman was given to Officers because it offers flash protection, since Beret's did not.

However since Officers will spawn with their helmet on by default, I guess we can swap the headsets around.

**Comment by pudl** [comment]
i wish hos didnt spawn with that stupid ass coat dude, seriously. can he get his old thing back and the black one can be in his locker?

**Comment by AnonymousNow** [comment]
I forget how many variants of the Head of Security's armoured coat we've gone through in the last couple of years. I swear, at one point, we had three different coats sprited and two available in-game at once.

I rather like this new one, but I seem to recall a Jensen coat that was popular.

**Comment by pudl** [comment]
jensen was what you spawned with and it was amazing.
if security made sense, hos would be as armored as the officers. i really think he needs a debuff

**Comment by paprka** [comment]
Talk about nerfing elsewhere. This is about sprites.

**Comment by Steelpoint** [comment]
There' has only ever been two HoS Jackets in game at any time, one that the HoS would spawn with and the other inside his locker.

**Comment by Nienhaus** [comment]
@Steelpoint Can't merge.

**Comment by Nienhaus** [comment]
I think it's because, https://github.com/tgstation/-tg-station/pull/7206

**Comment by Steelpoint** [comment]
Give me a few minutes.

**Comment by Steelpoint** [comment]
Should be fixed once Travis updates.

**Comment by Nienhaus** [comment]
Everything looks right to me, if it messes up I'm blaming you Steel :p

**Comment by Steelpoint** [comment]
If something screws up I'll fix it.

**Pull request merged**
