### PR TITLE
Refactor Uplink Refunding

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Refactors @KorPhaeron's uplink refunding to be a bit more generic and allow for more objects that have an uplink to allow for refunding.

In this instance, no additional functionality is changed, from a player perspective; the player can still hit the syndi radio uplink with a valid item and it'll refund.

That said, this system _allows_ for giving regular traitors the ability to refund items as well; in the case of PDAs the PDA has to have an uplink AND the uplink has to be left open for you to be able to refund something (no going around smacking people's PDAs for meta-checks).

This system allows specifying alternative refund paths---that is, to say, if something comes in a box, you could specify that one of the items, in said box, is refundable, as opposed to the box itself. Additionally, a refund amount can also be specified, in case there needs to be a TC refund penalty.

I also added in a conditional `check_uplink_validity` proc in case you want something to only be conditionally able to be refunded.

For instance, say you wanted to make holoparasites refundable, but only if they haven't been used, you could define that behavior with the proc. Again, I'm not changing anything in this PR to be refundable or not, merely putting the system in place for generic day to day useage, should it be desired.

:cl: Fox McCloud
add: Adds in generic uplink refund system that potentially allows for even regular traitors to refund uplink items
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
It looks like this is implemented, so you need to go through all the items and make sure they're valid for refunding(everything that spawns in a box is definitely not, obviously)

**Comment by Fox-McCloud** [comment]
@ChangelingRain 

That's very correct. I fully admit checking for contents and such is a bit beyond my skill level, but this definitely paves the way for something *like* that.

**Comment by optimumtact** [comment]
I'm not following this closely enough to suggest what needs to be done but please move this pr along.

**Comment by jughu** [comment]
So i can refund anything any time and stack my tc by stealing others traitorshit?

**Comment by Fox-McCloud** [comment]
@jughu 

Please read the OP before commenting. I said this does nothing from a player perspective.

Either case @optimumtact I didn't do anything further 'cause I was waiting for comment. Either case, I'll implement my few ideas and push the commits.

**Comment by ChangelingRain** [comment]
As-coded it is a change, because it checks for hidden uplinks and will, as such, allow traitors to refund stuff with their PDA.

**Comment by Fox-McCloud** [comment]
Alrighty, made changes so that a specific path can be specified for refunding and an alternative refund cost (in case you wan to have a TC penalty for refunding).

**Pull request merged**
