### PR TITLE
Adds an metric ton of belt sprites and suit sprites for worn objects.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Alright, belt sprites and the lack thereof are a metric pain in the ass. I have elected to rectify this.
Here's what we got:
the RPED
Sales/Cargo Tagger.
Shovel (Normal/Serrated/spade) 
Normal Hand Radio/Uplinks
Flashlights/Glowsticks/Flares
Grenades/C4/X4/Syndicate Minibombs.
Clipboard
the RCD/RPD/RLD
Clerics Maces
Airlock/Decal Painter.
Lighters.
Paper Sheets.
Scrolls (Improvement/Teleportation)
Books (Spelltomes, Reading Books, Job Manuals, Eldritch Tomes, Syndicate Tomes)

## Why It's Good For The Game

Ctrl-Deletes more ERROR belt icons.

## Changelog
:cl:
imageadd: Adds a metric ton of belt icons.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
holy fuck arcane

**Comment by necromanceranne** [comment]
While you're here could you do me a massive favour and add mirrored sprites for shotguns and flip the mirrored eldritch knife sprites I added?

**Comment by ArcaneMusic** [comment]
> While you're here could you do me a massive favour and add mirrored sprites for shotguns and flip the mirrored eldritch knife sprites I added?
> 
> Most if not all the shotguns have back sprites but not mirrored, so they come up with pink errors. And the knives I added were the wrong side.

I don't really do gun sprites 🤷

**Comment by Rohesie** [comment]
Great PR

**Comment by necromanceranne** [comment]
It's just flipping the back sprites we have. No need to make new ones.

**Comment by LemonInTheDark** [comment]
Leave the man be, he just leveled a mountain, no need to deal with a molehill

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
