### PR TITLE
Automatic stack merging

### PR DESCRIPTION
**Pull request by MrPerson**
When a stack moves onto the same tile as another stack, they merge together. Unless it was being thrown, in which case no, they don't merge. Unless the stack was the original target to begin with, then yes, they do merge.

Just a convenience feature. The one downside is that crowbarring up a floor tile won't merge with other tiles on the floor, but if someone makes that event call Move() like it's supposed to, it should work fine. That would just be out of scope for this PR.

### CODE REVIEW

**Comment by WJohn** [comment]
:+1: 
Maybe you could make it so crowbaring up a floor tile puts the floor tiles where you're standing (and as a result merges them), like welding glass shards does.

**Comment by Jalleo** [comment]
Can we make ores stack please as a later PR?

**Comment by bustygoku** [comment]
Ores already do stack inside of mining satchels, if they stacked inside of backpacks or boxes it'd remove the need for mining satchels or ore boxes so no don't do that

**Comment by MrPerson** [comment]
That's stupid, just have them stack anywhere. Miners should want to use an ore satchel because it's the best way to transport ore, not because it has magic ore-storing abilities.

**Comment by Cheridan** [comment]
Yeah, X Satchel and Y Satchel for everything is really more of a workaround.

**Comment by RemieRichards** [comment]
Satchel of Satchels:
The best method for holding all your Satchels.
Does not allow another Satchel of Satchels inside the Satchel of Satchels.

**Comment by Aranclanos** [comment]
does it takes into account the amounts?

**Comment by MrPerson** [comment]
What, the stack merging? Yeah of course it does

**Pull request merged**
