### PR TITLE
Medical hardsuit can be toggled between modes, adds support for hardsuit toggling

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request
New medical hardsuit sprites by Paxilmaniac! It doesn't look like Mr. Freeze's spare suit anymore.
Medical hardsuits can now be toggled between Mobility and Protection.
Mobility allows the user to run at full speed, with **no slowdown**, and grants full biological protection alongside good radiaction resistance.
Protection grants minor amounts of melee protection, and full biological and radiological protection.

Went ahead and fixed up the annoying glitch where the syndicate shielded hardsuit's combat mode deleted masks from your sprite, exposing your bare skin and making you look bald,

## Why It's Good For The Game
The medical hardsuit is easily the most unused one in the game. Unlike the HOS' one, it doesn't have good protection. Unlike the security and engineering ones, it isn't easily accessible to a department. Unlike the CE's, it doesn't have complete radiation protection. Unlike the atmospherics one, it doesn't have full fire protection. And unlike all of those, it doesn't even protect from flashing. The slowdown reduction isn't really enough of a big deal.

To remedy these without making it too much of an obvious powergaming choice for non-CMOs, I gave it full speed so they can respond to EVA crises faster, full biological protection even on mobility so they're able to respond to virus outbreaks quickly, and full radiation protection (the normal resistance to radiation on mobility is the same as biosuits) so they can respond to similar radiation outbreaks without needing treatment themselves. I decided to keep the syringe gun protection so that CMOs can deal with unruly chemists a bit more easily.

## Changelog
:cl:
balance: Rebalanced the medical hardsuit. It can now switch between two modes; 
add: Mobility: Fast, no slowdown. Gives biological immunity and biosuit-level radiation resistance.
add: Protection: Slow, spaceproof. Full bio- and radiological immunity. Slightly stronger against melee.
fix: Fixed the bug where syndicate shielded hardsuit's combat mode disabled mask sprites.
imageadd: New medical hardsuit sprites by Paxilmaniac!
code: Added support for future hardsuits to toggle between modes more easily.
/:cl:

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
Any plans to give a speed mode to the unpopular Mining hardsuits?

**Comment by Shapsy** [comment]
Your commits tell a story

**Comment by carlarctg** [comment]
> Any plans to give a speed mode to the unpopular Mining hardsuits?

maybe after this pr goes through

**Comment by Dorsisdwarf** [comment]
New sprites look like a lazy ass recolour of the ERT medical hardsuit

**Comment by Dawson1917** [comment]
CMOs already run around in their spacesuit all shift for no reason. No hardsuits should be without slowdown.

The reason the suit is considered garbage is that it offers nothing to medical that the >dozen other hardsuits on the station don't already have, because they're ALL immune to disease and readily available. A slower radiation-resistant mode is good for sending the CMO to fetch bodies from the SM and not die themselves from a rad outbreak in medbay.

**Comment by AnonymousNow** [comment]
I'm not sure how to feel about a new look, since the medical hardsuit's current bubble look suits their function in my opinion, but having it have some perks to keep it up to speed with the other hardsuits on board instead of being worse because "lol, fuck medbay" is an appealing prospect.

**Comment by Neo-0** [comment]
why are you deleting it?
image

**Comment by AnonymousNow** [comment]
> 
> 
> why are you deleting it?
> image

This isn't mentioned, is it? Worrying.

**Comment by TheVekter** [comment]
The sprite looks a little ehhhh? I can't say I hate it, but I certainly don't love it. Except for the helmet. Getting mad Metroid vibes from the helmet, good shit.

The idea itself is aces. Love it.

**Comment by carlarctg** [comment]
there's a merge conflict apes that's why its stealth removing stuff

**Comment by daklj** [comment]
should come with a bulldog shotgun

**Comment by anconfuzedrock** [comment]
even biosuits have slowdown. this includes the special blue cmo biosuit.
I do not want to see cmos wearing hardsuits 24/7.

**Comment by SkeletalElite** [comment]
> I do not want to see cmos wearing hardsuits 24/7.

remove CMO bio-suit slowdown

**Comment by anconfuzedrock** [comment]
I do not want to see cmos wearing biosuits 24/7

**Comment by wesoda25** [comment]
No slowdown is really dumb

**Comment by MCterra10** [comment]
Add slowdown to syndicate hardsuits

**Comment by carlarctg** [comment]
😬

**Pull request closed without merging**
