### PR TITLE
Adds bar stools

### PR DESCRIPTION
**Pull request by pudl**
No where except the bar on Boxstation for now.
NOTE: Before you ask "Why isn't the stool on the right a bar stool?", I figured that the gambling area was probably thrown together by the bartender himself, which means he wouldn't take the time to screw a stool to the floor, just get a normal, movable stool.

NOTE 2: At Thunder's suggestion, I resprited the stool.

### CODE REVIEW

**Comment by Nienhaus** [comment]
:+1:

**Comment by Thunder12345** [comment]
Sprite looks a bit flat to me, so I took a couple of minutes to mess with the shading of the base.
barstool

**Comment by pudl** [comment]
@Thunder12345 Let me just restate what I've said in IRC.
Anyone with any experience spriting or being a spriter knows that editing someone's sprite without permission and then going around demonstrating their TOTALLY superior spriting skills in IRC is pretty much 100% scumbaggery. Maybe if you had asked or pm'd me on IRC that you weren't satisfied with my work, I would have actually just used whatever you made! But instead, you didn't, and now you look like a fool. Good job.

**Comment by Thunder12345** [comment]
I'll just make another PR to change the sprite after this gets merged then.
UPDATE: Made the base a little rounder
barstool

**Comment by xxalpha** [comment]
Why not be grateful that somebody bothered to improve your sprite?

**Comment by pudl** [comment]
untitled
Since you're being so polite by improving upon my foolishly created sprite, I returned the favor. There's a little center dot like on real bar stools.

@xxalpha I wouldn't mind him improving upon my sprite if he hadn't immediately turned around and bragged about how his sprite was better on IRC and insult me.

**Comment by xxalpha** [comment]
Either way, I like this.

**Comment by Ausops** [comment]
if we're being dicks to each other and flopping each other with bar-stool dick shaped banter, how about this https://imgur.com/YhMhTKB, here's a third one

also I don't like any of the three, since the base shape and lineart seem kinda small but this is really a small and minor change so whatever

**Comment by pudl** [comment]
@Ausops Although, as always, your contribution is an amazing sprite, it doesn't really fit in with the rest of the game (just like most of your other sprites). Unless a significant amount of people think your sprite would look fine, I'll keep the current.

**Comment by Ausops** [comment]
don't feel obliged to add it either way, I'm just bored on sybil

**Comment by pudl** [comment]
Before anyone argues with what I said, just take a look at this.

**Comment by freerealestate** [comment]
Awesome. They look good. This reminds me of the church pews we once had. Someone should bring those back.

**Comment by pudl** [comment]
@freerealestate We never used church pews in code, however, I do think that AriaStation 13 uses a variation of them? I could port that.

**Comment by freerealestate** [comment]
I'm sure I saw pews on the map in an old /tg/station revision

**Comment by Cheridan** [comment]
Do you think you could resprite normal stools to go along with it? These new stools look nice but the old ones are uglier and different stylistically so they look strange standing next to them.

**Comment by pudl** [comment]
@Cheridan These are bar stools, they are not a replacement to normal stools. These stools would make no sense in normal use.
Also, saying "they look weird standing next to them", did you look at the picture I posted of Ausops' resprite? I didn't use that one. The bar stools that I used are in the OP, and they are so similar to normal stools they use the same top red part.

**Comment by PKPenguin321** [comment]
\>tfw i thought this PR was gonna be adding the ability to pick up stools to fight each other with
\>tfw it's just shitflinging over a sprite change

**Comment by pudl** [comment]
@PKPenguin321 It isn't a sprite change, it is an all new object.

**Comment by Durkel** [comment]
Can you spin them?

**Comment by Xhuis** [comment]
Might not be a bad idea to make them constructable in case some shitler runs through and instawrenches them all apart.

**Comment by pudl** [comment]
@Xhuis Pretty sure they are.

**Comment by optimumtact** [comment]
You're not going to get many contributions if you keep closing the PR's on merge conflicts

**Comment by Xhuis** [comment]
what why

**Pull request closed without merging**
