### PR TITLE
[WIP] Space Dragon Fixes +Ghost Notification

### LINKED ISSUE #42779: space dragon command report issue
Reproduction:
1. The space dragon event triggers, randomly or admin triggered
2. Nobody accepts the ghost offer for it.
3. The command report sends anyways, even though there's no dragon coming.

Should be an easy fix. As an aside, this event could use a "send report?" option in the trigger events menu, like how rods work.

### PR DESCRIPTION
**Pull request by IndieanaJones**
## About The Pull Request

Fixes #42779 , adds ghost notification for the Space Dragon.

## Why It's Good For The Game

Just adds bug fix for the announcement and ghost notification.

## Changelog
:cl:
add: Space Dragon notification for ghosts to spectate it
fix: Space Dragon announcement playing when no Space Dragon spawns
/:cl:

Alright, as of now, no balance changes will be made with this PR.  If you have a good idea to add to SD though, feel free to comment.

### CODE REVIEW

**Comment by IndieanaJones** [comment]
Fellas giving the disapproval, it's because the speed reduction, right?  If that's the issue, it'd help to upvote this comment so I know.

**Comment by Repukan** [comment]
Anything can go on a rampage if people poorly equipped to deal with a real threat try to fight it instead of running

**Comment by 4dplanner** [comment]
Real ash drake still causes damage through fire protection, so it might be worth considering here as well

**Comment by tralezab** [comment]
I feel like it hasn't been long enough for a fairly rare new event. Megacarp have self healing if you find a lucky really good one it could be arguably better than the dragon

**Comment by IndieanaJones** [comment]
> 
> 
> Real ash drake still causes damage through fire protection, so it might be worth considering here as well

Space dragon does as well.

**Comment by 4dplanner** [comment]
Got confused by 
>Considering it literally has no options to go up against anyone with proper fire protection

Still haven't actually ever seen it in-game, honestly. Funny that the spawn rate is already under attack.

**Comment by TerraGS** [comment]
If it needs further nerfing then a future project could be adding a Space Bounty Hunter ghost role that spawns along with/shortly after Space Dragon.

**Comment by IndieanaJones** [comment]
Nerf reverted.

**Comment by Jordie0608** [comment]
Revert your last commit, announcing an event in `announce()` is the correct method. To enable the send report prompt when spawning an event `announceWhen` must be more than zero, which means `announce()` needs to exist for the event so it can be called.

https://github.com/tgstation/tgstation/blob/c56869fe0a09c358a89a4c3fa0b0232bd53bd0b6/code/modules/admin/topic.dm#L165-L184

**Comment by IndieanaJones** [comment]
I just set it up, and it doesn't work.

/datum/round_event_control/space_dragon
	name = "Spawn Space Dragon"
	typepath = /datum/round_event/ghost_role/space_dragon
	max_occurrences = 1
	weight = 8
	earliest_start = 70 MINUTES
	min_players = 20

/datum/round_event/space_dragon
	announceWhen = 2
	
/datum/round_event/ghost_role/space_dragon
	minimum_required = 1
	role_name = "Space Dragon"
	fakeable = TRUE
	

/datum/round_event/ghost_role/space_dragon/announce(fake)
	priority_announce("It appears a lifeform with magical traces is approaching [station_name()], please stand-by.", "Lifesign Alert")
	
/datum/round_event/ghost_role/space_dragon/spawn_role()
	var/list/candidates = get_candidates(ROLE_ALIEN, null, ROLE_ALIEN)
	if(!candidates.len)
		return NOT_ENOUGH_PLAYERS

	var/mob/dead/selected = pick(candidates)

	var/datum/mind/player_mind = new /datum/mind(selected.key)
	player_mind.active = TRUE

	var/list/spawn_locs = list()
	for(var/obj/effect/landmark/carpspawn/C in GLOB.landmarks_list)
		spawn_locs += (C.loc)
	if(!spawn_locs.len)
		message_admins("No valid spawn locations found, aborting...")
		return MAP_ERROR

	var/mob/living/simple_animal/hostile/megafauna/dragon/space_dragon/S = new ((pick(spawn_locs)))
	player_mind.transfer_to(S)
	player_mind.assigned_role = "Space Dragon"
	player_mind.special_role = "Space Dragon"
	player_mind.add_antag_datum(/datum/antagonist/space_dragon)
	playsound(S, 'sound/magic/ethereal_exit.ogg', 50, 1, -1)
	message_admins("[ADMIN_LOOKUPFLW(S)] has been made into a Space Dragon by an event.")
	log_game("[key_name(S)] was spawned as a Space Dragon by an event.")
	announce_to_ghosts(S)
	spawned_mobs += S
	return SUCCESSFUL_SPAWN

That will cause the Space Dragon announcement to go off regardless of it spawning, and does not give an admin who triggered the event to get an announcement cancellation prompt.

**Comment by IndieanaJones** [comment]
Closing until this properly works.

**Comment by Jordie0608** [comment]
You've added `announceWhen` to `/datum/round_event/space_dragon` but the event typepath is `/datum/round_event/ghost_role/space_dragon`
The announcement goes off even if nobody is picked when `announceWhen` is a small value, so while the event is still waiting to see if anyone accepts the prompt it reaches the processing tick for announcing the event. It then later sees nobody accepted and cancels. The solution is to either have a longer announcement wait time or edit `/datum/round_event/process()` to delay the announcement until it's known the event will actually run.

**Comment by Jordie0608** [comment]
Put `announceWhen` under `/datum/round_event/ghost_role/space_dragon` and not `/datum/round_event/space_dragon`

**Pull request closed without merging**
