### PR TITLE
Fixes ghost_roles spawning as transgenders.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

An oversight made in #51058. Almost every other source of changing gender was complete with changing body_type as well, but not the ghost_role spawners.

Right now ghost roles can spawn with one gender, but get the other body_type.
This results in looking at "her", while the person in question got a surprise.

For such things, we already added "Other" gender.

## Why It's Good For The Game

I don't even want to explain why this bug is bad.

## Changelog
:cl:
fix: Ghost roles can no longer spawn as a male with female body_type and vice-versa.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
Now you understand the pain of being born in a body you don't identify with

**Comment by iwishforducks** [comment]
Could you explain why this is so bad and why you think it's a bug? Because this seems too "based" to be a bug.

**Comment by TemporalOroboros** [comment]
This seems fine. I think you are creating an issue there there isn't one.

**Comment by OceanFish1** [comment]
Based fix

**Comment by fludd12** [comment]
let me know when this patch is implemented IRL, HRT ain't cheap.

**Comment by interestingusernam3** [comment]
https://www.youtube.com/watch?v=ooOELrGMn14

**Comment by Thunder12345** [comment]
Instead, allow this in character setup

**Pull request merged**
