### PR TITLE
[s]no

### PR DESCRIPTION
**Pull request by Iamgoofball**
# vote goof 2017

### CODE REVIEW

**Comment by RemieRichards** [comment]
if what you were doing before wasn't bribery, then I've no idea what this is

**Comment by YakumoChen** [comment]
I thought prs like this weren't allowed

**Comment by YakumoChen** [comment]
At what point have we had enough and goof gets gitbanned for unfunny garbage

**Comment by RemieRichards** [comment]
2 years ago

**Comment by Iamgoofball** [comment]
^

**Pull request closed without merging**
