### PR TITLE
Fixes span in wiping with rag.

### PR DESCRIPTION
**Pull request by kingofkosmos**
Was mentioned in #9201 .

### CODE REVIEW

**Comment by phil235** [comment]
Why not fix both the rag and mop messages in the same PR?

**Comment by kingofkosmos** [comment]
But TheVekter said in the comments that he'd include that
fix in his next PR...?

**Comment by phil235** [comment]
He said it 6 days ago, plus the fix is literally one character, I don't think he'll mind. It's probably better to fix an issue in one PR instead of two separate ones by two different authors.

**Comment by kingofkosmos** [comment]
I accidentally mop span fix into the wrong PR. It's in #9315 is that ok?

**Comment by Jordie0608** [comment]
Yes

**Pull request merged**
