### PR TITLE
Ethereal Pirates (Re-pr)

### PR DESCRIPTION
**Pull request by Toastgoats**
Other pr had some weird check failure, making a new pr to see if it fixes it.

## About The Pull Request
After he ended up finishing his pirate pr before I could, SethLafuente graciously offered to let me roll my in-progress pirate pr into his overall pirate expansion project.

This pr essentially adds a new faction of pirates, along with a new subspecies of Ethereals a-la silverscales.

- The Lustrous:

A unique subspecies of Ethereal, with years of exposure to bluespace dust mutating them into crystalline abominations sporting a new pointy head, pressure resistance, and a permanent bluespace prophet brain trauma. They're still as fragile as ever, but far more capable of getting in and out of sticky situations.

- Geode Pirates:

A hollowed out asteroid manned by three Lustrous, equipped with switchblades, traitor PKAs, jump boots, two teleporting turrets, and an upgradable bluespace launchpad.

However, they lack proper armor and ship defenses, forcing them to adopt a coordinated hit-and-run playstyle.

asteroid
shuttle
piratas
## Why It's Good For The Game

When I started working on this project, I wanted to implement this faction to cover for the loss of psykers and as a means of creating a "rock-paper-scissors" system to how standard pirate playstyles would work; with default pirates being offensive, Silverscales defensive, and Lustrous mobile.

With Seth's pr, things are a little different now, but I still believe a glass cannon mobility-focused pirate faction would be a welcome addition to the pirate roster.
## Changelog
:cl:
add: Adds the Lustrous, ethereal pirates in a big bluespace geode!
sound: Unique scream sound for the Lustrous species.
image: Unique head icon for the Lustrous species.
/:cl:

### CODE REVIEW

**Comment by Toastgoats** [comment]
Living embodiment of murphys law right here.

**Comment by Jacquerel** [comment]
I'll be honest I am not sure what you expected, you just want to wait for #76501

**Comment by Sealed101** [comment]
still no LotL gem names 😔

**Comment by Toastgoats** [comment]
THE TRAM CHECK IS STILL FAILING WHAT THE FUCK

**Comment by Jacquerel** [comment]
> THE TRAM CHECK IS STILL FAILING WHAT THE FUCK AAAAAAA


> I'll be honest I am not sure what you expected, you just want to wait for #76501

**Comment by Toastgoats** [comment]
> > THE TRAM CHECK IS STILL FAILING WHAT THE FUCK AAAAAAA
> 
> > I'll be honest I am not sure what you expected, you just want to wait for #76501

Oh sorry I wrote that before I read your comment.

**Pull request merged**
