### PR TITLE
adds organs to the limbgrower

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds all humans organs to the limbgrower
## Why It's Good For The Game

limbgrower is largely useless, only being able to print normal limbs when you can just print strong robotics ones and an armblade when emagged, also with the removal of cloning that may be coming this will be neat for restoring organs you cant just clone anymore

## Changelog
:cl:
add: The limb grower now grows a bunch of organella
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
WOAH SLOW DOWN WHAT'S ALL THIS LOVE FOR THE LIMB GROWER ALL OF A SUDDEN?!

**Comment by Krysonism** [comment]
This makes organ harvesting obsolete just as we see see organ potentially gaining some value down the road.

I think this idea could work if printing organs took something like a stem cell reagent gained from grinding up organs(at a loss).

**Comment by Fikou** [comment]
> This makes organ harvesting obsolete just as we see see organ potentially gaining some value down the road.
> 
> I think this idea could work if printing organs took something like a stem cell reagent gained from grinding up organs(at a loss).

i dont see the reason of having a machine literally no one uses still existing without any changes, being the only source of printable organs will finally make this r&d locked machine useful for something

**Comment by Krysonism** [comment]
> > This makes organ harvesting obsolete just as we see see organ potentially gaining some value down the road.
> > I think this idea could work if printing organs took something like a stem cell reagent gained from grinding up organs(at a loss).
> 
> i dont see the reason of having a machine literally no one uses still existing without any changes, being the only source of printable organs will finally make this r&d locked machine useful for something

I think it is better gameplay wise to have to prepare by harvesting organs and managing your organ resources. As opposed to just building a machine every shift and being able print organs on the fly.

Harvesting organs is something I feel a doctor should do.

**Comment by Qbopper** [comment]
harvesting organs sounds kinda neat

just spitballing, this is probably a terrible idea, but you could maybe make some kind of mechanic where "natural" organs can be put into someone to encourage harvesting/organ donors (lol) but the grown ones require you to take a specific chem to avoid organ rejection symptoms? like it wouldn't kill you but makes you puke and stuff

**Comment by CPTANT** [comment]
I like that you have to cut out someone's else's organs if you want to do a transplant.

**Comment by davethwave** [comment]
Well one way of doing things is that without upgrading the machine individual organs will be damaged but not lethally so or have different stats like a grown liver will have less alcohol resistance and gets damaged from toxins faster. Lungs would cause you to cough or you would pass out faster. Stuff like this in order to keep *natural* organs to be superior in comparision. Also we haven't even talked about how the medlathe can just print you a new heart for a sheet of metal and glass once it's been researched.

**Comment by davethwave** [comment]
Also we might want to consider a name change to the machine from limb grower to organic manipulator or something like that.

**Comment by tralezab** [comment]
people grower people grower

**Comment by Qbopper** [comment]
I really like organic manipulator yeah

**Comment by Ohagi-Chan** [comment]
Organ builder

**Comment by Time-Green** [comment]
Could be cool if you fed it organs, from lets say the organ harvester, and then use that to make stronger organs. 

You’d be giving the limb grower a spotlight and keep the organ harvester more than relevant.

Single transplants would still be viable if you didn’t have a big backlog of organs.

**Comment by AWalton** [comment]
The basic cybernetic organs PR seems like a better solution because at least there the organs can be given the EMP weakness to make them worser than harvesting real organs.

**Comment by ExcessiveUseOfCobblestone** [comment]
the organ grower should make subpar versions of the normal organs as to act as a sufficient stand-in until you have access to cybernetics (tech req) or you can find a "willing" participant.

Much less hp, much more organ decay / less passive healing, less beneficial in things like toxin purging, etc.

It still keeps you alive, but you're going to be much more susceptible to future organ damage until you get a "real" one.

**Comment by kriskog** [comment]
Limb grower is advanced biotech machinery, far from roundstart.

**Comment by ExcessiveUseOfCobblestone** [comment]
It should be much closer with parts being added as you progress.

**Comment by shellspeed1** [comment]
What about having it heal organs that are dead to a barely useable state?

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
