### PR TITLE
RPED & BRPED can now pick up & install stack components and display more verbose part information of machines

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
Rapid part exchange device RPED & Bluespace version of it BRPED can now

A) pick up 3 types of stacks
  - glass sheets[max 20]
  - plasteel[max 20]
  - cable coil[max 30]
 and install them in an incomplete machine frame

B)display more verbose part information[number of parts for each type including for stack components]

## Why It's Good For The Game

A)Some machines types such as

- [thermo machines](https://tgstation13.org/wiki/Machines#Freezer.2FHeater)
- [electrolyzers](https://tgstation13.org/wiki/Machines#Electrolyzer)
- crystallizer=10 cable pieces , 10 glass sheets , 5 plasteel sheets

All require either cable ,glass or plasteel. Usually you have to carry these components inside your backpack which occupy space there and later take it out from there and install it manually by hand and then use RPED or BRPED on the machine frame.

This feature now combines these 2 steps into 1 step thus making installing machine frames much faster and you also saves space inside your backpack as these are now carried inside the RPED itself

I limited the amounts to 20 & 30 as we dont want people using this as a general storage medium hence i add only these 3 new types and also limit how much of each type you can carry

You need to insert the exact stack type capacity available inside the RPED for it to work i.e. if you pick up 5 glass sheets then later you need a stack of exactly 15 glass sheets to complete the stack. This is easier from a coding perspective so we don't have to deal with subtracting & updating appearances of the remaining stack on the ground or the user hand. An log is displayed informing you how much stack you can insert for that type

B) When using the RPED or BRPED to display machine part information this is the new format
Screenshot (42)
We can all agree this is way better than display A matter bin,A matter bin..whatever

Plus the crystallizer information is also much clearer as it also displays stack amounts of machines
Screenshot (43)
We can all agree this is way better than displaying some glass,some plasteel...so on

##Change Log
:cl:
add: checks while inserting stack materials into an RPED and their amounts 
tweak: sorting of RPED part components to sort stack materials by their ratings 
del: old way of displaying parts when clicking on an machine frame with it
add:new way of displaying part info which displays  number of parts including for stack materials 
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
:D

**Comment by msgerbs** [comment]
> I dont know why commits from my previous pull request are showing up. Please only check the last latest commit i did

You created this branch from your previous branch rather than creating it from master. There's no way for maintainers to just ignore these commits, they would have to have merged your other PR or those changes would come with too.

There's some advanced git wizardry that can fix this but honestly the easiest way is going to be to copy the files you actually intended to change out somewhere else, then delete the branch and recreate it from master this time and force push it.

**Comment by SyncIt21** [comment]
> > I dont know why commits from my previous pull request are showing up. Please only check the last latest commit i did
> 
> You created this branch from your previous branch rather than creating it from master. There's no way for maintainers to just ignore these commits, they would have to have merged your other PR or those changes would come with too.
> 
> There's some advanced git wizardry that can fix this but honestly the easiest way is going to be to copy the files you actually intended to change out somewhere else, then delete the branch and recreate it from master this time and force push it.

Ahh crap. i made the commits for my first pull request to the master branch directly which means any branch i create from it will have these commits. Thanks i will be careful next time

**Comment by msgerbs** [comment]
In that case you'll need to wait until your other PR is accepted, if you try and fix this now you'll probably break your other PR.

**Comment by msgerbs** [comment]
My suggestion would be to make this a draft for now

**Comment by msgerbs** [comment]
After thinking for a bit I'm gonna play maintainer and slap a DNM on here so nobody accidentally merges it before this oops is fixed. Ping me if nobody else drops by to remove it when your other PR is merged.

**Comment by dragomagol** [comment]
You're missing a changelog as well.

**Comment by SyncIt21** [comment]
Good idea I mentioned that this request should not be merged unless my previous one is either approved/cancelled.

**Comment by SyncIt21** [comment]
Change Log added

**Comment by Mothblocks** [comment]
@msgerbs For the record we tend to prefer "Blocked" over DNM for stuff like this

**Comment by msgerbs** [comment]
> @msgerbs For the record we tend to prefer "Blocked" over DNM for stuff like this

Understood, thanks.

**Pull request closed without merging**
