### PR TITLE
Fixes crash bug in the byond beta

### PR DESCRIPTION
**Pull request by tkdrg**
Don't use unicode in byond jesus christ, this crashes DS on 507.1274

### CODE REVIEW

**Comment by ike709** [comment]
Until I looked very closely at the "x" I thought you changed literally nothing. GG. :+1:

**Comment by paprka** [comment]
I wonder who did this, it wasn't me

**Comment by hornygranny** [comment]
Literally why

**Comment by tkdrg** [comment]
Cheridan did it.

**Comment by tkdrg** [comment]
This is merge-ready.

**Pull request merged**
