### PR TITLE
Gives curse of madness it's own sound

### PR DESCRIPTION
**Pull request by Cyberboss**
Shameless Dota 2 theft

:cl:
soundadd: Added a new sound for curse of madness
/:cl:

### CODE REVIEW

**Comment by k-k-karma** [comment]
but this is sureyl copyrigted................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by Cyberboss** [comment]
Valve has a longstanding policy of not caring about asset reuse for games

**Comment by nicbn** [comment]
Vi sitter här I venten och spelar lite Dota

**Comment by GuyonBroadway** [comment]
Seeing as we aren't trying to sell this sound as our own intellectual property, consider these sounds are hosted for easy download on the dota2 wiki and consider dota2 is free to play and welcomes community contributions, content and all that jazz I think if valve DOES care then someone in valve secretly really really really hates tgstation or someone in it.

**Comment by PKPenguin321** [comment]
wtf, i was weaned off of using UNUSED valve sounds in one of my PRs because of potential copyright issues but this is ok?

**Comment by PKPenguin321** [comment]
dude, nice

**Comment by PKPenguin321** [comment]
wait why can't we use HL1 vox then

**Comment by nicbn** [comment]
we can

I think

I'm not a lawyer

**Comment by nicbn** [comment]
This is getting too complicated
Someone could just send a message to Valve asking if we could reuse their content, that way we would be in the safe side

**Comment by PKPenguin321** [comment]
i'll go email gaben@valvesoftware.com
didnt somebody from here email NASA about whether or not some space-related shit was realistic once or am i misremembering

**Comment by GuyonBroadway** [comment]
@PKPenguin321 bay or some other HRP server asked NASA what the head of a deep space station's job title would be and they wrote back "colony director" so they renamed captain to colony director.

**Comment by PKPenguin321** [comment]
gabe hasnt gotten back to me yet but if he does i'll update you guys here

**Comment by GuyonBroadway** [comment]
Valve being valve, unless we literally try to A: Claim this sound is legally our property and B: try to sell and make a profit of it then I doubt they care.

**Comment by Cyberboss** [comment]
Can't wait for downsyndromestreams to get blapped

**Pull request merged**
