### PR TITLE
Kills tactical brass chairs; alternatively, "this is why we can't have nice things"

### LINKED ISSUE #35338: Ratvarian chairspins are laggy as shit when done in mass.
I don't actually have video on hand for this, but chairspinning ratvar chairs will make them spin forever, causing a CRAPTON of lag and time dialation, allowing them to summon Ratvar rather quickly with little crew action being taken.

Proposed solution; flick a spinning chair *animation* until someone buckles in, at which point it may defer to the old behavior, only stopping once they unbuckle, then falling back to the previous animation.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: Brass chairs now stop spinning after eight rotations, so you can't crash the server with them.
/:cl:

Closes #35338.

This right here. This is why we can't have nice things. I hope you're very proud of yourselves.

### CODE REVIEW

**Comment by Potato-Masher** [comment]
You fools. You absolute buffoons. This is all your doing. You have brought this figurative hell upon thy selves.

**Comment by coiax** [comment]
Alternatively, why not just have X maximum chairs spinning, and it'll remove the oldest spinning chair if you start the X+1th spinning.

**Comment by Buggy123** [comment]
Alternatively, figure out why this is lagging so much and fix _that_ instead of removing.

**Comment by MrDoomBringer** [comment]
Alternatively, add a spinning animation, as suggested by the OP in #35338?

**Comment by AverageJoe82** [comment]
Plz dont merge

**Comment by Xhuis** [comment]
@Buggy123 The reason it's lagging is because of a large amount of objects processing five times a second and playing a sound each time. There is no easy way to fix that.

**Comment by Kromgar** [comment]
Thank fucking christ this fucking game mode is already ear-raping enough i'm glad this noisy garbage is gone

**Comment by Buggy123** [comment]
Okay then just animate it as suggested in #35338

**Comment by Xhuis** [comment]
That still doesn't change the sound part; I'd need to remove the sounds entirely.

**Comment by MoreRobustThanYou** [comment]
@Xhuis make a single /datum/looping_sound instance, and add each spinny chair to it's output_atoms

**Comment by Xhuis** [comment]
that still plays the sound constantly. no real change

**Comment by Buggy123** [comment]
I like the sound tbh

**Comment by Xhuis** [comment]
The sound is what is allowing players to crash the server.

**Comment by Buggy123** [comment]
Shit, really? Fuck.

**Pull request merged**
