### PR TITLE
Fixes pop cap messages not properly showing custom messages (with default config.txt)

### LINKED ISSUE #8119: Default Config settings for Pop Cap messages use the wrong string
The default config.txt uses strings like HARD_MESSAGE, but the game actually checks for HARD_POPCAP_MESSAGE

### PR DESCRIPTION
**Pull request by Incoming5643**
Fixes #8119

### CODE REVIEW

**Comment by Ikarrus** [comment]
I've already corrected the server configs to use HARD_POPCAP_MESSAGE

for the sake of convenience, could you just change the default to use this so I don't have to go in and re-correct the config?

**Comment by Incoming5643** [comment]
it works all the same

**Comment by Ikarrus** [comment]
Well then make sure you PM sos next time he updates it so he can fix it on our side

**Comment by Incoming5643** [comment]
No no I mean I'm doing what you asked, I was just agreeing that's an equally valid solution

**Comment by Ikarrus** [comment]
o ok

**Pull request merged**
