### PR TITLE
Removes the unused "black_suit_fem" icon state from syndicate.dmi

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Removes an unused icon from syndicate.dmi
## Why It's Good For The Game
image
Dude what even is this why is it here why has it been here for this long

Every single time I open this dmi I wonder again why it's here and then find out it's unused too.

Like. ENTIRELY unused. I did a thorough search for any use case of even just components of the icon_state. Maybe '_fem' was added later! NOPE!

Maybe it's called at some point when syndicate.dmi itself was linked?
NO! IT'S NOT! THIS IS USELESS!
## Changelog
No player facing changes.

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
sovl removal... tg has fallen, millions must sprite

**Comment by theselfish** [comment]
Why not just...move it to another DMI and place it in a vendor, or something?

**Comment by OrionTheFox** [comment]
> Why not just...move it to another DMI and place it in a vendor, or something?

I didn't make this PR to add a new item? I'm removing an unmaintained, unused sprite :|

**Comment by Singul0** [comment]
how long has that thing been there

**Comment by CCC23** [comment]
noooo not black_suit_fem my favoriteee thing in the code noooooooooo

**Comment by san7890** [comment]
is `black_suit` itself nonexistent?

**Pull request merged**
