### PR TITLE
Head Revolutionary promotions now exclude Monkeys unless absolutely necessary... again.

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

Makes #40938 work again.
Eventually, monkeys became a human subtype too, which broke the code that used to make them only be promoted to rev heads if there were no human candidates available. The other fixes of #40938 seem to have already been accounted for at some point or another.

Updates the comments and var names as well to make it clear that it is meant to exclude monkeys and not non-human races (lizards, moths, etc.).
## Why It's Good For The Game

A fix of a fix. How meta is that?
## Changelog
:cl:
fix: Monkey revolutionaries will not be considered for a promotion into Head Revolutionaries unless they're the only candidates... again.
/:cl:

### CODE REVIEW

**Comment by IndieanaJones** [comment]
What's wrong with having a monkey be a headrev? The element of surprise tends to make them rather good at the role from my personal experience.

**Comment by Vincent983** [comment]
Couldn't a headrev also just use a monkey injector on themself to have a headrev monkey?

**Comment by Momo8289** [comment]
This is blatant prejudice against our monkey-bodied brethren😔

**Comment by san7890** [comment]
> What's wrong with having a monkey be a headrev? The element of surprise tends to make them rather good at the role from my personal experience.

this would have to be addressed in a PR specifically regarding removing this mechanic, the fix must be allowed since the implementation of a deliberately merged feature is broken.

**Pull request merged**
