### PR TITLE
Gives doctors maintenance access

### PR DESCRIPTION
**Pull request by QualityVan**
:cl: QualityVan
balance: Doctors now have maintenance access
/:cl:

To make triage and corpse recovery easier. Also to make being a doctor slightly less boring during downtime.

### CODE REVIEW

**Comment by WJohn** [comment]
bALANCE *REEEEEEEEE*

**Comment by Qbopper** [comment]
I don't know how I feel about this

on the one hand, sweet, I can fucking go get the goddamn bodies out of maint

on the other I feel like this could have some potentially bad balance effects

**Comment by GunHog** [comment]
I am worried about this adding to much traffic to maint. We have Engineers, Atmos, Security, Heads, and greyscum currently.

**Comment by Xhuis** [comment]
I'm kind of iffy on this, yeah. I think it's a good change for the doctors, but for people who use maintenance for staying hidden/shady reasons, it'd probably make their lives that much harder.

**Comment by QualityVan** [comment]
Do note that this is only doctors, not chemists, virologists, or geneticists.

**Comment by Xhuis** [comment]
Well, yeah. But at the same time, doctor is already the most low-effort medical role, and I imagine that if anyone would pick one of the medbay roles just for the free medical supplies, it'd be doctor since they're not generally expected to do anything anyway. Whenever I play as a chemist or geneticist I usually end up being the one to treat people.

**Comment by BeeSting12** [comment]
sure lets make maintenance more of a secondary hallway than it already is. just go to the HoP office and ask for access, the most i will do as HoP is alert the HoS over comms that I gave someone maintenance access and they might need it for traitor/cult things. most HoPs don't do even that, maybe 1 in 10 will be a dick and say no.

**Comment by Repukan** [comment]
>Morphine someone in a sleeper
>Kill them in maint
>Nobody will ever know/coworkers can't check.

No thanks. Ask the HoP

**Comment by QualityVan** [comment]
Repukan, you realize that a: morphine isn't that strong and b: doctors already have access on most maps to the maint hallways adjacent to medical?

**Comment by Repukan** [comment]
It doesn't need to be strong, you only need them asleep for three seconds to strip the headset and choke.

And they only have access to medical maint, yeah. But what if an enteprising medic or emt takes away a corpse for "healing" and it never reaches medbay? Now you have a lot more hidey holes to look for.

I still think this should be resolved icly by asking the HoP for access.

**Comment by QualityVan** [comment]
>takes away a corpse for 'healing'
Then you could already space it, hide it in one of the patient lockers in medical, hide it in one of the patient rooms and close the shutters(less definite, but it'll last long enough for them to go braindead), stick it in the bodybag in the morgue, or debrain it.

And it takes about a minute before it'll knock someone out for those three seconds, for the entirety of which they're slowdown immune and for half of which they're aware you drugged them if you didn't overdose them in the first place.

**Comment by Repukan** [comment]
>Then you could already space it, hide it in one of the patient lockers in medical, hide it in one of the patient rooms and close the shutters(less definite, but it'll last long enough for them to go braindead), stick it in the bodybag in the morgue, or debrain it.

Yes, but most of these have a chance of being seen since they're being made in high transit areas. Maint isn't so.

**Comment by Xhuis** [comment]
You say that now, but I used to have an old recording of a nuke op team stuffed in a locker, unwelded and unlocked, with a suspicious Unknown in a gas mask dragging it across the station through multiple areas. Nobody even batted an eye. Not to mention, as a doctor, you're expected to have body bags; you can even drop it off as the chef with a body bag tag saying "Mental interface failure."

**Comment by Repukan** [comment]
Nobody uses body bags.

In the blue moon they do, they're always opened at least 5 times every 20 steps.

**Comment by DoctoreMad** [comment]
I'd rather not!

**Comment by Xhuis** [comment]
I use body bags.

**Comment by DoctoreMad** [comment]
Weirdo.

**Comment by QualityVan** [comment]
Yesterday I took a dead sec officer in full gear from medbay to the brig, found the brig was locked down due to explosions, and took the officer back to medbay. At no point was the bag opened.

**Comment by Aloraydrel** [comment]
>biting one word response repukan bait

Stop

**Comment by Xhuis** [comment]
But it looks so tasty.

**Comment by Shapsy** [comment]
Repukan's posts are very specific theorycrafting which aren't important but a better argument is keeping maint spooky and at least somewhat remote. Either pilfer a maint ID off a dead body in the morgue or talk to the HOP

**Comment by Grazyn** [comment]
Access creep. Maint access is finely balanced, not to mention that some novelty maps have so much stuff in maint you can do pretty much anything you want. If being a doctor is boring, code something to make it less boring, maint access will just add doctors to the roundstart validhunters list.

**Comment by QualityVan** [comment]
To repeat: part of doctoring is triage and corpse retrieval(invalid hunting, if you will). This's why suit sensors, among other things, exist. It's entirely reasonable that between the two of them, a target will be in maint. If they're in a department, you can just ask someone in a department; they're usually full of people. Who're you gonna ask for maint corpse retrieval? Sec? Assistants?

Secondarily: it's not that being a doctor is boring, it's that being a doctor is boring when you have no patients. A doctor's primary job is reactive. Improving doctoring won't make that less the case, and thus won't help when there's nothing to react to. Furthermore: if it was made necessary for people to go to medbay regularly and for any real duration, it would be a nuisance for them and they would cry that whatever else they were doing was being interrupted. 

Maint is spooky by virtue of it being dark, twisty, and narrow. Currently, access is limited to: engineers(5), atmos techs(3), heads(6), security and the warden on skeleton(6), cargo techs and the qm(4), miners on skeleton(3), janitors(2), the detective(1), and assistants(infinity). That's between 21 people with non-skeleton and no assistants and 30+. You're telling me adding three people to that somehow pushes it over the line?

**Comment by Tacolizard** [comment]
THIS IS A BALANCE CHANGE NOT A FEATURE REEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by lzimann** [comment]
Yea, freeze and all of that.

**Comment by Bawhoppen** [comment]
this is the problem with QoL changes, eventually you have so many that it waters down the game and removes any interesting dynamics

(if you want maint access as a doc, ask the HOP)

**Comment by KorPhaeron** [comment]
I think this would let too many people into maint who thematically have no reason to be there

**Pull request closed without merging**
