### PR TITLE
[WIP] Domination (Alternate Revolution Objective/Mode)

### PR DESCRIPTION
**Pull request by Eaglendia**
## About The Pull Request

_A hostile takeover is seldom enough to create a productive environment without the infrastructure to support it. While revolutionaries are still predicated on accomplishing their goals through violent means, some more visionary leaders turn their focus to what comes afterward._

Adds support for a non-meme alternate Revolution gamemode, Domination, with core gameplay mechanics identical to Revolution. Head-revolutionaries in this mode spawn with a beacon implant that can be used to produce the Dominator, a machine that can be used to gain control of the station's systems. Once active, the Dominator will assume control of the entire station in ten minutes (reduced by an amount proportional to the percentage of living crew that have been converted to the revolution, to a minimum of four minutes). A Dominator has 400 health and armor typical of solid machines. It must be placed on a solid tile in a powered area on the station z-level and cannot be activated if its space is occluded by a wall or other closed object. It will spawn anchored and can be unanchored and moved until it is activated, at which point its position will be locked.

Activating a Dominator will announce its location and change the station's alert level to Delta. An active Dominator can be tracked directly via pinpointer. Its countdown timer can be viewed on the pinpointer or by interacting with the machine while adjacent to it. Destroying an active Dominator will cause a small (0,0,2,2) explosion and restore the station's alert level to red. Ghosts are alerted to the position of an activated Dominator; spectators can see the overlayed timer and are prompted to jump to the Dominator's location.

In Domination, the Emergency Shuttle can depart from the station normally unless a Dominator is active (destroying the active Dominator will clear the hostile environment, resetting the shuttle departure timer). Once the emergency shuttle departs from the station, no further Dominators can be activated. Major and Minor victory conditions will be implemented for the revolutionaries and crew:
- A revolution major victory occurs when a Dominator takes control of the station, ending the round.
- A revolution minor victory occurs when the emergency shuttle departs and no heads of staff make it to Central Command.
- A crew major victory occurs when all revheads are killed and no Dominators are active, ending the round.
- A crew major victory occurs when a number of Dominators are destroyed equal to the number of revheads, and at least one head of staff is alive, ending the round.
- A crew minor victory occurs when the emergency shuttle departs and at least one head of staff makes it to Central Command.

Also adds support for a new type of implant, the beacon. It can be configured to spawn any sort of item, either by having it "appear" at the user's position (functioning identically to the suspicious beacons used to call in syndicate bombs and singularity markers), or having it sent via drop pod similar to a choice beacon.

Full disclosure: I might or might not need some help with getting this one right. I'm making things work, of course, but I don't know a whole lot at present about what constitutes good and bad code. I've thought about taking a crack at refactoring Revolution team handling to feel a little more clean and support things like multiple teams (faction HUD indicators for admin-spawned fun stuff? pseudo-gangs?) so more interesting things can be done with the core mode in the future but I'm new to DM and probably don't have the programming chops for it. I'd like to see something like this in the game, of course, but it wouldn't do anyone any real good to just pile it on top of a bunch of existing bad that will never get better. Guidance would be very appreciated alongside the typical improvement suggestions.

## Why It's Good For The Game
- Brings harmless change to a stale "meta", suggesting new strategies and elements of doubt without introducing large amounts of emergent complexity. The plan for Domination would be to share its gamemode weight with Revolution, such that a number of Revolution rounds would be Domination rounds instead. The revolution gamemode is cut-and-dried in terms of routing game actions; the fact that the emergency shuttle is not a hostile environment in Domination adds elements of counterplay (should the shuttle be called to force the revolutionaries to expose themselves place their Dominator before they might be ready?) and risk (should a head of staff attempt to secure the shuttle in an attempt to secure a minor victory, knowing that they could be walking into an ambush?) that are absent in Revolution, and its existence alongside Revolution introduces uncertainty to that gamemode.
- It is not a flaw, but a fact of Revolution, that the mode is predicated almost entirely on combat. Many players converted to revolutions feel inclined to opt out or are simply found standing around for a number of reasons: lack of perceived robustness, lack of knowing what useful actions they can take, or boredom with a straightforward gamemode. While Domination is meant to end with a series of climactic battles between revolutionaries and loyalists, the focus on area control increases the value of construction, medicine, and other tools that would otherwise be ignored for lack of utility to strategies that focus on moving around the station and killing as quickly as possible. Game announcements and more things to do help less experienced revolutionaries become involved, and coerced inclusion in battles will improve their play in future revolutions regardless of the outcome of those battles.
- Dominator fights are fuckin' sick. Players who were fond of earlier incarnations of Gang might or might not miss this aspect, but Domination provides an opportunity to bring this exciting gameplay to a more pure and balanced environment.

**To-Do**
- [x] Implement major/minor victory conditions rather than just the traditional end-screen.
- [x] Probably would want some actual logging features too.

## Changelog
:cl:
add: Domination, an alternate win condition for Revolution, has been added.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Idk seems nearly identical in concept, and I’m sure gameplay will be similar as well. Gangs but its just one? I feel as if people like me would like it, but not sybil main type people.

**Comment by zeroisthebiggay** [comment]
gangs but with no guns and no teams
so gangs but it's also revs

**Comment by optimumtact** [comment]
picture of the PR original post with the san andreas meme overlayed, ah shit here we go again

**Comment by necromanceranne** [comment]
We already got cult on Sybil so who cares. @wesoda25 

At least this version takes the element of cult that you can actually say is good (forcing a final conflict over a critical spot so you don't have to play hide-and-go-seek with the opposing side), and applying it to a game mode that we already know works pretty well due to the simplicity of its formula.

**Comment by Eaglendia** [comment]
I'm just gonna reopen this in a little bit because I'm embarrassing myself

**Comment by ATH1909** [comment]
> A crew major victory occurs when a number of Dominators are destroyed equal to the number of revheads, and at least one head of staff is alive, ending the round.
And what if a revhead dies before deploying their dominator? Can the rest of the revheads still just turtle/hide to extend the length of the round?

Will the revs be informed as to WHERE this dominator is? I feel like a fight over a dominator will less be a big clash between the revs and the nonrevs and more of a tiny clash between the handful of revs that the revhead that deployed the dominator behind 3 layers of reinforced walls in maint bothered to tell about the location of the dominator and the two people (and whoever they manage to bring along with them) who actually have the only two pinpointers on the station. That's assuming, of course, that the revs don't just steal the two pinpointers beforehand and set the dominator up in maint, leaving the non-revs with no way to actually find a dominator that's been hidden in maint (other than by guessing well/dumb luck/some rev doing something really stupid).

**Comment by Eaglendia** [comment]
image

Currently the area is reported as a minor announcement. Reports for deployments in maintenance areas are obviously more vague, though I imagine maintenance deploys have their own set of associated benefits and disadvantages.

The Dominator generally has to be in a real, powered area to be activated. Its periodic beeping can also be heard from nearby locations and grows louder as the takeover time approaches zero, meaning if it's buried in maintenance you'll generally be able to pinpoint its location if you're close enough (though getting there might be another story if it's been deployed in a fortified spot).
Abusive strategies, to some extent, are part of emergent gameplay. If revolutionaries manage to successfully steal both pinpointers (which a good station crew should be keeping track of as they're kind of important and usually in either secure locations or in the hands of high-threat or high-access staff members) and deploy in a fortified location, I think they deserve an appropriately dominant chance to win the game.

**Comment by PKPenguin321** [comment]
Gang-lite rev variant? I'm down

**Comment by Shadowflame909** [comment]
Give them spray cans and pens to convert

**Comment by Eaglendia** [comment]
Blueprints are strong, but time would have to tell if using them to misdirect would be a dominant strategy. High-risk items **should** under normal circumstances be protected, so there's a level of "maybe you shouldn't have lost the blueprints" that can be afforded as a reasonable defense of the strategy. It would take some proper testing to determine what is and isn't broken, and though the mode is in a testable condition I'd still like to get it fully functional and a little less janky.

**Comment by habader** [comment]
No more random rev roundends, nice

**Comment by YakumoChen** [comment]
I like it. It's simple, like Revolution is, but with a different overall objective instead of just "kill the heads" Cult and Gangs bring too much bullshit into the mix where Revolution is a perfect mode unto itself, this doesn't add much/any complexity to it, it simply shifts how things play out.

**Comment by Eaglendia** [comment]
>No more random rev roundends, nice

Half as many. This mode is not intended to replace Revolution; without Revolution in the rotation it doesn't accomplish what it sets out to. That, and I'm still open to criticism re: round-end conditions for Domination. Should the game end if all head revolutionaries die, if all Dominators are destroyed, or should loyalists be left to the mercy of the shuttle? I'm still deciding what to implement and figuring out how to code it. My ears are decidedly open!

**Comment by YakumoChen** [comment]
Well, if you take away the instant win condition of the round ending when all the heads of one side, you put a lot more weight on the remaining crew - ie, revolutionaries remain antagonists and security will remain as it is. Usually when all the heads die, the round is more or less over. Security will probably be broken and whatever other objectives exist are likely to be very easy to accomplish. It can be a lot different for revolutionaries - the antags. Sometimes you can get lucky and get the revheads early, but you still leave a large force of revolutionaries. It might unbalance things and make things drag out if you force security to go through the slow process of capturing and implanting most of the rest of the revs.

**Comment by habader** [comment]
Abrupt game ends should only occur after a dominator announcement, wether it be from the dominator winning or being destroyed

**Comment by dr-bee** [comment]
I see the same issue here as with anything that requires defending a set location (clock cult). Bombs, plasma fires, and BOH bombs will be abused to hell and back and there is little in the way of standing defenses that can be built to stop it.

Still sounds like a fun mode however. I prefer it over rev as you can actually help just by building or preparing for the end fight instead of just random murder.

**Comment by Tlaltecuhtli** [comment]
cult endgame has shown that having all be decided in a single announced area is a bad idea
as even the most useless assistant is gonna maxcap, plasma flood, boh bomb the place stalling the round

**Comment by ExcessiveUseOfCobblestone** [comment]
Is it not the point of rev to be a semi-mindless turbo murder round as a relief measure?

Also is this going to be like gang where the team kills everyone THEN drops the 10 minute beacon down?

**Comment by Eaglendia** [comment]
Currently, the revolutionaries have as many Dominator attempts as there are revheads. Unlike the old Gang mode, your tools aren't hooked into any kind of economy, meaning the mode remains Revolution-like in facilitating a handful of headrev strategies (blitz, subtle snowball, distraction dominator to get the heads into/away from one place or lure crew to create chaos with early conversions, achieve station takeover before attempting Domination). Remember that the Dominator is just an alternate win condition rather than a total overhaul of game flow, so if all else fails, "kill the heads, get access, and get looted" is still a real game plan - just with a handful of extra steps. 

Still, Dominator access might be the most abusable part of the mode and I'm thinking of features that would make it more sane.
- time gate dominator plant attempts (would rather not do this)
- the dominator can only be planted in a subset of areas like Cult
- the dominator can only be planted if a certain head is dead, or requires a head-access ID to activate
- one of the above restrictions could be chosen randomly each round as an additional objective
- loyalists can't be converted to the revolution while a dominator is active (revolutionaries have to win the fight and can't use the dominator as a distraction or bait for mass conversions)
- the dominator will only count down if there's a revolutionary in the area, or must be literally interacted with in order to continue working
- the dominator just takes enough time to literally activate that it's restrictive to use them recreationally

As an aside, the machine gets forensics from the person who turns it on, meaning if an early Dominator fails and the user escapes they can potentially be IDed by crew that are really on top of things.

**Comment by Ziiro** [comment]
I like the head level id requirement idea. Or the one that requires a certain head to be dead.

**Comment by bgobandit** [comment]
no fetish content

**Comment by HomocidlePancakes** [comment]
Meh. Don’t like it. All I see is a way for revs to end the round when they’ve converted everyone and the last head has been hiding for way too long. But it doesn’t tackle the problem when heads have implanted everyone and the last headrev is hidng.

**Comment by Eaglendia** [comment]
This is incorrect, as if heads have implanted everyone and the last headrev is hiding they can just call the shuttle. The last headrev will have to place and activate a Dominator before the shuttle departs or lose the round.

**Comment by HomocidlePancakes** [comment]
Welp. I completely missed that part. I feel dumb now.

**Comment by Akrilla** [comment]
For the "signal origin pinpointed to:", I'd just remove the colon, look more natural.

**Comment by Eaglendia** [comment]
Went ahead and removed that colon, and shored up some of the general messages as well. All the core features are in, though there's currently no minor victory detection with the shuttle call; that'll probably be what I do next, and shouldn't take terribly long.

Currently there are still no restrictions on activating a Dominator, other than that it can't be activated by a loyalist or interacted with by a silicon. Will probably add logging to Dominator drops and activations.

**Comment by ExcessiveUseOfCobblestone** [comment]
is this waiting for a review or...?

**Comment by optimumtact** [comment]
stale?

**Pull request closed without merging**
