### PR TITLE
Makes Servicianism actually work

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request
I did a big oops with quotation marks and the station's hottest new religion was unavailable under most conditions.

## Why It's Good For The Game
**SERVICIA MUST BE PRAISED**

## Changelog
:cl:
fix:  The Tenets of Servicia are properly available through "servicianism" and "partying" religions
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
Mind putting Servicianism alphabetically in the code?
I took the time to organize all the religions alphabetically a while back, would hate to see it get jumbled up again.

**Comment by AzureWildfire** [comment]
Ha, and I thought it was a problem on my side, at least I managed to convert engineering to servicianism

**Comment by Tlaltecuhtli** [comment]
this looks dumb and cringe who approved this

**Comment by RaveRadbury** [comment]
@Farquaar you got it! Sorry to mar your work.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's just a religion it'll be ok.

**Pull request merged**
