### PR TITLE
Icemoon Comms agent

### PR DESCRIPTION
**Pull request by DATA-xPUNGED**
## About The Pull Request

Adds a comms agent to icemoon, similar to the one that can spawn in space
<details>
  <summary>Image (spoilers, kind of)</summary>

image

</details>

## Why It's Good For The Game

Icemoon is sorely lacking on ghost roles, this should help with that somewhat.

## Changelog

:cl:
add: NT reports indicate that the Syndicate have increased listening activities on Icemoon, crew is advised to watch out for possible communication interference.
/:cl:

### CODE REVIEW

**Comment by DaydreamIQ** [comment]
Since there's two spawners is there gonna be a spare advanced console for the second guy? Hard to tell what the consoles there are via the screenshot

**Comment by DATA-xPUNGED** [comment]
> Since there's two spawners is there gonna be a spare advanced console for the second guy? Hard to tell what the consoles there are via the screenshot

The other spawn is empty

**Comment by necromanceranne** [comment]
Might wanna be careful. If this is underground, the higher layers could spawn in such a way that you could tunnel through the comms agent's roof.

**Comment by CCC23** [comment]
life_has_many_doors
the last thing a comms agent sees before a miner with some giblonite and a wrench tunnels through their ceiling

**Comment by Addust** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days blablablablablabla

go to hell this is the best PR i've seen this week

**Pull request merged**
