### PR TITLE
Removes the meme sloths

### PR DESCRIPTION
**Pull request by harmonyn**
>be cargo tech
>time to take the crates to the conveyor belt
>NOPE SLOTH FUCKING COCKBLOCKS YOU
>try to drag the crates around the sloth
>NOPE YOU MOTHERFUCKER
>die of frustration and salt

in all seriousness: few people like this sloth, a lot of people actively dislike it, it gets in the way of literally fucking everything a cargo tech does because a cargo tech's job involves manuevering things in a smallish space, people often kill it and/or shove it in lockers all round anyway, it exists in part due to a player reference meme, and the sprite looks fucking terrible. kill it with fire

(the alternative is moving it to the QM's office. but seriously, fuck this sloth)

### CODE REVIEW

**Comment by Anonmare** [comment]
u gon act lik a bitch.

u gon die lik a bitch.

**Comment by AnturK** [comment]
Map changes, but no dictionary changes. Seems wrong.

**Comment by chanoc1** [comment]
sloths are the worst fluff

**Comment by scoopscoop** [comment]
Just buckle it to cargo's front desk chair

**Comment by jughu** [comment]
The sloth is lazy, just like you

**Comment by Aloraydrel** [comment]
dumb sloth hater

**Comment by optimumtact** [comment]
sloth_cuddles_teddy

**Comment by optimumtact** [comment]
Why don't you just drag the sloth out of the way?

**Comment by YakumoChen** [comment]
i ded pls restart

**Comment by YakumoChen** [comment]
imagine, a creature that is well known for being slow helps make cargo...
...
...
slow.

or you could just drag it out of the way I guess.

**Comment by KorPhaeron** [comment]
Do you like the cargo sloth?
Yes: 11
No: 10
Don't care: 5
Did not vote: 47

**Comment by ChangelingRain** [comment]
get _slow_

**Comment by chanoc1** [comment]
can we just have a sloth gun in cargo that instant kills the sloths and turns them into diamonds for selling

**Comment by bgobandit** [comment]
dragging the sloth out of the way doesn't help for the same reason you can't drag lizards or other simple mobs, they move out of the drag

**Comment by optimumtact** [comment]
hmm, simple mobs should not be pushing out of drags if they are pets or friendly

**Pull request closed without merging**
