### PR TITLE
Fixes mop

### LINKED ISSUE #44523: Mops arent in autolathe
## Round ID:
#110593

## Reproduction:
1) open autolathe
2) search mop
3) no mop in list
#44141 added mops to the autolathe list but they don't seem printable.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Fixes mop. Fixes #44523

## Why It's Good For The Game

Fixes mop.

## Changelog
:cl:
fix: The mop can now be printed at the autolathe.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
mop

**Comment by Suicidalpickles** [comment]
mop

**Comment by HomocidlePancakes** [comment]
mopposters assemble

**Review by SpaceManiac — APPROVED** [review]

**Comment by Pugie** [comment]
wtf cult nerf wtf

**Pull request merged**
