### PR TITLE
Makes Recovered Crews (lost crews) more suceptible for antag chicanery + also adds felinids to its species pool

### PR DESCRIPTION
**Pull request by Singul0**
## About The Pull Request
Makes it so that recovered crews have more antagging potential by making the mind lock on the lockboxes of lost crews be tied to their body's dna instead of the mind (mind check still exists though, in-case of husking) and also changes dangerous_organ_removal from a damaging explosion to a localized acid spray.

This is to allow antags to use recovered bodies as backup identity in a pinch. by doing a brain surgery into one or DNA cloning themselves into them.

Oh and also, added felinids to the race pool for the bodies being spawned, I feel like it being too similar to humans as a weak justification.

## Why It's Good For The Game
In my opinion we really shouldn't add game-blocks/locks that checks for the mind, Mail really sets a bad precedent for this. imho we shouldn't outright stuff like this to be impossible to bypass. players, with enough equipment and effort should be able to find ways of getting around locks (ie. crew being able to hijack the nukie shuttle with enough preparations).

Tangent over, I feel like recovered crews has prime antaggery potential, this PR softens the code that hard-blocks it from having that antag potential, meant for anti cheese-strats.
## Changelog
:cl:
add: Recovered crews are now more prone to antag chicanery
add: after multiple legal disputes. Nanotrasen's insurance provider has included felinids as part of its recovered lost crew insurance program, instead of the lost pets insurance program.
/:cl:

### CODE REVIEW

**Comment by Singul0** [comment]
guh

**Comment by Autisem** [comment]
recoverd crew not having antagging potential was largely the point, I think its easier at that point to buy an agent ID/make fake ID and upload a false record then it is to change your own DNA, order recoverd crew case, break it open and steal there stuff.

Also fucks over that recoverd crew since if ghost decides to pick it they would be robed before they even lived

**Review by Time-Green — CHANGES_REQUESTED** [review]
I dislike the premise of antags messing with what's supposed to be protected starting equipment, but it's the nature of the sandbox. It can already be opened by EMPs, emags or shooting it with lasers so this doesn't make a lot of difference 

You also already know my feelings about adding felinids to this, I doubt anyone will even notice the difference between a human and a felinid given how derivative they are and the fact that most organs are usually removed and or damaged

**Comment by Xkallubar** [comment]
Please no felinids

**Comment by Loafin34** [comment]
so from what i can tell, you're giving the possibility of using the recovered crewmember's free ID and jumpsuit as an extra disguise. i think thats cool but you're basically lasering a posi brain with how ghostroles are treated.

**Pull request closed without merging**
