### PR TITLE
Removes the superfluous breathing mask from the survival box of clown/mime + New mime hugbox.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Some time ago this PR: #61603 removed the breathing masks from the survival boxes that plasmamen use as they already spawn with a breathing mask equipped.
This PR does the same with clowns and mimes and since I needed to give mimes their own box code wise I decided to also give them a recolored version of the hugbox icon wise. Mimes like hugs too!

## Why It's Good For The Game
This will decrease the number of breathing masks throw on the floor/bin per shift... not much but I really don't like the roundstart ritual of throwing my useless mask on the bin when I play as these jobs sooo...

Also, new and colorless mime hug box because I thought it would be funny:
mimebox

## Changelog

:cl: Guillaume Prata
qol: Clown/Mime survival boxes won't have a mostly pointless breathing mask, as their basic mask can be used for internals.
imageadd: New mime Hugbox!
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
When your clown mask inevitably gets burned off during a plasmaflood, the emergency mask is a lifesaver. Plus, some clowns opt to wear masks that don't have integration with internals. I don't see a reason to remove their emergency backup when they can throw it out if they don't want it.

**Comment by GuillaumePrata** [comment]
> When your clown mask inevitably gets burned off during a plasmaflood, the emergency mask is a lifesaver. Plus, some clowns opt to wear masks that don't have integration with internals. I don't see a reason to remove their emergency backup when they can throw it out if they don't want it.

True, but the number of clowns that need a spare breathing mask for one reason or another is tiny compared to the ones that never use it.
At worse, the breathing masks are on basically any hallway inside an O2 locker if it gets burned or they opt for another kind of mask.

**Comment by Farquaar** [comment]
> > When your clown mask inevitably gets burned off during a plasmaflood, the emergency mask is a lifesaver. Plus, some clowns opt to wear masks that don't have integration with internals. I don't see a reason to remove their emergency backup when they can throw it out if they don't want it.
> 
> True, but the number of clowns that need a spare breathing mask for one reason or another is tiny compared to the ones that never use it. At worse, the breathing masks are on basically any hallway inside an O2 locker if it gets burned, they opt for another kind of mask or just want to have a backup.

So? What's the issue? It takes two seconds to throw out the mask if you don't want it, and doesn't require anyone to pilfer the oxygen lockers before an actual emergency happens.

**Comment by ATH1909** [comment]
> When your clown mask inevitably gets burned off during a plasmaflood, the emergency mask is a lifesaver.

... what do you do when you don't play clown/mime, then? rush an emergency oxygen locker at roundstart for a backup mask?


>  Plus, some clowns opt to wear masks that don't have integration with internals. I don't see a reason to remove their emergency backup when they can throw it out if they don't want it.

if they're wearing an internals-incompatible main mask, can't they just use their original clown mask as their backup mask?

**Review by tralezab — APPROVED** [review]
i like it. "what if the clown loses his mask?!"
perish...

**Comment by VladinXXV** [comment]
This is swag. Have you considered allowing more of these boxes to be made via stamping cardboard with the mime stamp? It isn't **exactly** a parallel to the clown stamp being used to make a clown box, but I think it'd be a good option since the stamp isn't doing anything else.

**Comment by willox** [comment]
is this meant to be removing the `fishing` state from storage.dmi?

**Pull request merged**
