### PR TITLE
removes the slowdown from the security tider pack

### PR DESCRIPTION
**Pull request by Jackal-boop**
## About The Pull Request

removes the slowdown from the security tider pack

## Why It's Good For The Game

the tider pack is a very funny tool made obsolete that its locked behind a high price, takes up your back slot, and has a large slowdown effect while equipped. removing the slowdown may let us see them more.

## Changelog

:cl:
balance: removed slowdown from tider pack
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
cant you refill this with any chem, making it a straight upgrade to all other chemical spraying backpacks?

**Comment by SkeletalElite** [comment]
> cant you refill this with any chem, making it a straight upgrade to all other chemical spraying backpacks?

right now its just a straight down grade to the atmos backpack AFAIK
The Atmos firefighter backpack can be filled with pepper spray and, unlike this shitty backpack, it fires it like an extinguisher instead of an oversized handheld pepper spray making it nearly undogable.

**Comment by Jackal-boop** [comment]
> cant you refill this with any chem, making it a straight upgrade to all other chemical spraying backpacks?

well youd have to drain its supply of 1000 pepper spray first, which would take a while

**Comment by jughu** [comment]
pottasium+water

**Comment by ExcessiveUseOfCobblestone** [comment]
> pottasium+water

😈

**Comment by Jackal-boop** [comment]
> Someone should add some security feature that prevents this from being refilled with non pepperspray or something idk lol

There's only one of these on station. I don't think it's really that big of a deal. But if it's non negotiable, how would I do that?

**Comment by moocowswag** [comment]
So its a unique item that is only spawned in brig?

if clown steals it and fills it with space lube they deserve their fun

**Comment by SkeletalElite** [comment]
> So its a unique item that is only spawned in brig?
> 
> if clown steals it and fills it with space lube they deserve their fun

It's an expensive item in the sec vend

**Pull request closed without merging**
