### PR TITLE
Nerfs techweb cargo points

### PR DESCRIPTION
**Pull request by silicons**
Slightly-under halves them.

### CODE REVIEW

**Comment by Chocodaemon** [comment]
Just curious, what's your reasoning for this?

**Comment by praisenarsie** [comment]
@chocodaemon technology disks can give ten billion (exaggerated number) cargo points

**Comment by Chocodaemon** [comment]
So now they have to get twice as many disks from Science?

**Comment by praisenarsie** [comment]
@kevinz000 ok don't halve the cargo_costs, quarter them

**Comment by DaxDupont** [comment]
Wait can they export duplicates? Isn't it like the old system anymore?

**Comment by davethwave** [comment]
I don't believe you can export duplicates but however you can export disks with research that haven't been sent yet or was not in the disk you sent earlier.

**Comment by Buggy123** [comment]
No thank you :-1: fine as it is.

**Comment by FantasticFwoosh** [comment]
> No thank you 👎 fine as it is.

How else do you regularly harvest cargo points? because if a sole export good is of technology disks then you're probably not using cargo's ability to export as intended.

**Comment by Buggy123** [comment]
I don't harvest cargo points via any other means, because they're all terrible in comparison. Just like how I don't take a horse drawn carriage instead of driving a car.

**Comment by Kajmany** [comment]
I've been playing a lot of QM lately. It is very easy to get 250k-750k+ cargo points from one or two tech disks in about 20 minutes. That's absurd even for purchasing large amount of null crates.

Good change to start with. I'm interested in seeing it dropped even further depending on how this goes.

**Comment by ShizCalev** [comment]
Changelog.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm going to turn cargo into a roblox tycoon if you don't nip these in the bud buddy!

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
