### PR TITLE
Revert "Removes the gang gamemode"

### PR DESCRIPTION
**Pull request by PKPenguin321**
🆑
add: Undid the gang gamemode removal.
/:cl:

Reverts tgstation/tgstation#26816

We're fixing it. The separation between server and project ends NOW

### CODE REVIEW

**Comment by GunHog** [comment]
That was an awful merge, I hope this is reverted posthaste.

**Comment by ChangelingRain** [comment]
That should not have been merged, especially given that @Robustin had started work on potentially improving gang.
@Ausops

**Comment by lzimann** [comment]
Gang is an awful mode. I am probably killing in the future anyway, better to let it die now.

**Comment by coiax** [comment]
It should not have been merged when multiple maintainers had expressed severe doubts, including the design lead

**Comment by lzimann** [comment]
What maintainer expressed severe doubt? It was open for 48h and the only that said anything was Kor.

**Comment by coiax** [comment]
@PKPenguin321 put a changelog in the OP.

**Comment by Robustin** [comment]
I'm willing to work with the """"""design lead"""""" to try a new approach to GW.

My first several PR's are moderate adjustments just to see how the mode plays when its not a war of attrition. I've still got a few to open in that respect. After a few weeks of getting feedback on those changes, we can make the next step towards more experimental changes like removing security/crew guns/implants with the narrative premise I've outlined before. 

Assuming this revert goes through, I don't expect all of my early PR's to go through but I hope that people approach the changes with an open mind. I'd welcome other efforts to improve the mode as well (de-centralizing point income would be nice).

**Comment by Jordie0608** [comment]
Idk @coiax, that didn't stop lizard languages getting merged ( ͡° ͜ʖ ͡°)

**Comment by optimumtact** [comment]
No, gang is garbage and I will not carry it's weight in our codebase any longer

**Comment by ChangelingRain** [comment]
That is not your decision, as you should not be closing the revert of a pr you merged.

**Comment by Armhulen** [comment]
squeezer inbound

**Comment by KorPhaeron** [comment]
@Cheridan make them stop fighting

**Comment by PKPenguin321** [comment]
The real reason oranges dislikes https://tgstation13.org/phpBB/viewtopic.php?f=5&t=10933

**Comment by Militaires** [comment]
# THE CITRUS WARS 2: RISE OF VITAMIN C.

**Comment by Cheridan** [comment]
the day of the juicer is upon us

**Comment by kevinz000** [comment]
who needs drama when you have this?

**Comment by Shihrt** [comment]
🍿

**Comment by Lumipharon** [comment]
We've had literally ass fucked gamemodes stay in game, and in rotation, basically for years (ie: cult and it's horrible unfinished various iterations in the past).

You can't say 'hurr durr, no one is fixing it', if it's out of rotation for a year and so never gets touched.

**Comment by Cheridan** [comment]
sorry guys leoz paid me $50 to close this

**Comment by kevinz000** [comment]
wait what

**Comment by kevinz000** [comment]
wait are you serious?

**Comment by Pacmandevil** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Cheridan** [comment]
of course not doofus and i'm sad that people thought i was

**Comment by sawrge** [comment]
dude 4 conversion modes lmao

**Comment by optimumtact** [comment]
@PKPenguin321 are you proud of your legacy?

**Comment by PKPenguin321** [comment]
yes, especially since people want the mode back now

**Comment by optimumtact** [comment]
they won't get it back now that I'm in charge

**Pull request merged**
