### PR TITLE
 Removes water making turfs wet

### PR DESCRIPTION
**Pull request by Iamgoofball**
vubuopw

### CODE REVIEW

**Comment by ma44** [comment]
This is a thing because throwing water bottles is now considered a ranged stun

(what)

**Comment by Iamgoofball** [comment]
@ma44 this problem existed with every single OPENCONTAINER thing in the game so

**Comment by kevinz000** [comment]
No people need to git gud

**Comment by Iamgoofball** [comment]
I forgot the from removed thing

**Comment by MoreRobustThanYou** [comment]
10/10 shitpost

**Comment by Niknakflak** [comment]
Hacky change.  If he's removing water making turfs wet, he doesn't even bother handling or dealing with the place where turf handles water and slipping 

https://github.com/tgstation/tgstation/blob/77a2d3f5cd377284bcce6d8c81ba4dae65f0fd84/code/game/turfs/turf.dm

**Comment by Ergovisavi** [comment]
This is the result of a discussion regarding me and a few others holding the opinion that the water bottles in the vendors providing easy access to a very versatile stun via water slipping is bad. Spray bottles doing effectively the same thing via water slipping is also too much of a thing in my opinion. 

I think the mop is fine, being an object the janitor has access to, is a delayed action, and slipping has become basically the Janitor's source of entertainment. Water slipping from beakers/spraybottles instantly creates a tile, you can throw bottles at range, etc, it's like a weird ghetto taser.

**Comment by Tacolizard** [comment]
i mean this does violate the freeze, seeing as it's a blatant rebalance.

**Comment by octareenroon91** [comment]
# WE ARE DETECTING AN EXCESS OF HUGS

**Comment by MMMiracles** [comment]
I wish Emily "slips" Ranger was still around to have an aneurysm over this.

**Comment by FantasticFwoosh** [comment]
Very loud and obnoxious questions were raised to the viability of escape attempts/consequences of carrying water when bawhoppen introduced water bottles availible from sustenance machines just to stock the abandoned bunker ruin, i can't remember the exact discussion but i imagined i whined quite loudly and now goof has took notice and followed suit in some respect.

I won't lie, i always carry a spare bottle filled with water if i get thrown into perma so i can slip shitcurity members that like to physically abuse perma prisoners. Karma.

**Comment by Hatfish** [comment]
Make sure to remove slipping from other easily accessible items as well, like soap and banana peels.

**Comment by optimumtact** [comment]
The correct fix is to require an actually significant amount of water to "wet" a tile, instead of just any amount.

**Comment by KorPhaeron** [comment]
Freeze

**Comment by Cyberboss** [comment]
Goteem

**Comment by Iamgoofball** [comment]
@optimumtact 
It already does and doesnt stop water bottle throws

**Comment by FantasticFwoosh** [comment]
I forget, do water bottles splash on impact?

**Comment by calzilla1** [comment]
Get gud, emergent, etc

**Pull request closed without merging**
