### PR TITLE
Video Camera Circuit Added Interactions

### PR DESCRIPTION
**Pull request by BlueNothing**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl:
add: Allows video camera circuits to be seen on networks other than the science cameranet.
tweak: Alphabetizes camera list for camera bugs, and lets camera bugs see through borg and circuit cameras.
tweak: Makes video camera circuits fit in tiny assemblies.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
Camera bugs are almost criminally underused, it would seem, given their low cost and apparent utility... until you realize that their old organization made them a pain to use, and their most apparent niche use (combine with circuitry as a way to control R/C circuits from anywhere) was hampered by their previous inability to actually see through video camera circuits. Video camera circuits, in turn, were previously small components, but until very recently ( https://github.com/tgstation/tgstation/pull/39123 ), the difference between 'small component' and 'tiny component' was nil. The complexity cost of video camera circuits also makes it a significant investment to fit one in a tiny circuit (they take over 25% complexity *on their own*), so it seems harmless enough to allow it. Lastly, allowing circuits to be seen through networks aside from the science network allows people like security, cargo, or assistants to benefit from clever use of video camera circuits (I could imagine, for instance, someone linking to the screens in the Bar and hosting "Let's Explore Maintenance with Fred the Robot!" or having a Miner livestream their battle with Bubblegum; alternatively, security might use this in conjunction with a remote-transmitting microphone circuit to spy on organizing tiders, etc).

### CODE REVIEW

**Comment by kevinz000** [comment]
Two words
Helmet cams

**Comment by lolman360** [comment]
cavity implant tiny circuit cameras*

**Comment by Garen7** [comment]
you could already implant small/normal sized circuits with cameras in them

**Comment by BlueNothing** [comment]
That would be a waste. If you're going to cavity-implant a circuit with a camera... yeah, might as well use a bigger one.

**Comment by GunHog** [comment]
You could just carry the circuit in your box, like a normal violence-crazed speesman.

**Comment by octareenroon91** [comment]
Piloted bombs soon?

**Comment by BlueNothing** [comment]
R/C bombs are old news by now, really. PK has it, that's pretty much what this PR does.

**Comment by RandolfTheOkay** [comment]
I see this mostly coming down to a wider number of roles being able to use RC circuits. Traitors and security, namely. Bodycams and whatever a traitor wants to use over camera with a camera bug. The limitations that the camera circuit assembly was only accessible by the two cam screens in the circuitry lab was always annoying imo, and the buff made to the camera bug is neat, since that's hardly ever used.

**Comment by BlueNothing** [comment]
In theory, this may also allow the AI to get camera signals from maint and
other such strange places, if someone decides to help it.

**Comment by octareenroon91** [comment]
Would it be easier than getting an assistant to install cameras, or an AI shell?

**Comment by ahkent** [comment]
carrying a camera circuit in your bag or box is afaik something that prevents people from looking through it- i've consistently had the ai be unable to see me on cams while carrying an active camera circuit in my bag. 

seems balanced. certainly no easier than building cameras the normal way.

**Comment by BlueNothing** [comment]
Um... I don't think that was your problem, ahkent. The problem is that, as far as I know, AI doesn't get to see the science camera network. Wait, can it? Checking...

**Comment by ahkent** [comment]
@BlueNothing the ai in question (tested multiple times, but haven't looked at the code so don't know) could see the area as soon as i dropped the camera circuit, but not while it was in my bag

more testing required, it's not really related to this PR tho

**Comment by BlueNothing** [comment]
Fair enough. Strange... but interesting, all the same. Further testing is
certainly due.

**Pull request merged**
