### PR TITLE
Fixes riding datum runtimes

### PR DESCRIPTION
**Pull request by Cyberboss**
You can't unbuckle the mob while processing it your nerds!

### CODE REVIEW

**Comment by Supermichael777** [comment]
The ride never ends mate

**Comment by Militaires** [comment]
all kevinz's shitcode im an innocent man and my riding datum is golden fuckg

**Comment by KorPhaeron** [comment]
@Cyberboss 

Conflicts

**Comment by Cyberboss** [comment]
Ready

**Pull request merged**
