### PR TITLE
Multi-Z debug map update

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request
This PR updates the multi Z debug map with working stairs and multi Z wiring, piping and disposals.

## Why It's Good For The Game
It's good to have all features in this map to iron out multi Z related bugs/runtimes. Also serves as a reference for people who never worked with multi Z mapping before.

## Changelog
:cl: Denton
tweak: Updated the multi Z debug map with multi Z wiring/piping/disposals and stairs.
/:cl:

### CODE REVIEW

**Comment by AnturK** [comment]
You should make it use proper loading not broken multiz dmm first.

**Comment by 81Denton** [comment]
I wasn't encountering any errors earlier, but let me start up a local instance and look for any runtimes just in case.

**Comment by 81Denton** [comment]
The map loads and Z levels connect properly, I'm not sure what issues happened during the tournament.

**Comment by optimumtact** [comment]
multi z map loading definitely works

**Pull request merged**
