### PR TITLE
Added cloth construction bag recipe

### PR DESCRIPTION
**Pull request by WarlockD**
## About The Pull Request

I was tired of having only two per shift or them getting vaporized during a SM delem.  So I just added the recipe into the cloth list.

## Why It's Good For The Game

Evey other bag type can be made, why not the construction bag?

## Changelog
:cl: 
add: Crafting recipe for construction bags.
/:cl:

### CODE REVIEW

**Review by kriskog — APPROVED** [review]

**Comment by trollbreeder** [comment]
I'd say RPEDs are better for parts holding and application but inconsistency is bad so, thumbs up.

**Comment by dr-bee** [comment]
> 
> 
> I'd say RPEDs are better for parts holding and application but inconsistency is bad so, thumbs up.

RPEDs cant hold boards. so even if I have one Ill grab a construction bag to carry the 10+ boards I need for whatever large project Im doing. Great change!

**Comment by WarlockD** [comment]
> I'd say RPEDs are better for parts holding and application but inconsistency is bad so, thumbs up.

Thanks both of ya.  Honestly don't know why the original pull never put this in.  Hopefully once I get used to doing pulls I think I will try something crazy like doing Gold Symbiont organs.

**Comment by trollbreeder** [comment]
> > I'd say RPEDs are better for parts holding and application but inconsistency is bad so, thumbs up.
> 
> Thanks both of ya. Honestly don't know why the original pull never put this in. Hopefully once I get used to doing pulls I think I will try something crazy like doing Gold Symbiont organs.

Based madlad. Most of the crossbreed PRs after it was initially implemented were closed due to the slime curse (where the author gets burnt out and lets the pr crash and burn)

**Comment by WarlockD** [comment]
Well thats comforting:p. Maybe I should do one or pet slime so I don't sir myself.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Changelog

**Pull request merged**
