### PR TITLE
Suffocation color blue again, lightens column color on scanners

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request
title

## Why It's Good For The Game
- Suffocation is BLUE NOT PURPLE
- Column color is too dark for based players (dark mode users)
image
-Oranges will ban me if I don't do it

## Changelog
:cl:
tweak:suffocation is blue in scanner
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
dark mode is cringe though

**Comment by carlarctg** [comment]
whoops, thanks for the headsup

recommend me hex codes i dont know what's a good middleground

**Comment by fludd12** [comment]
I mean the same notification blue might be best, there, since it's already agreed upon for both light and dark mode and will look nice among the rest of notification text.

**Comment by carlarctg** [comment]
> I mean the same notification blue might be best, there, since it's already agreed upon for both light and dark mode and will look nice among the rest of notification text.

done

**Comment by 81Denton** [comment]
Conflict

**Comment by carlarctg** [comment]
@81Denton unconflictined

**Pull request merged**
