### PR TITLE
Remove no tick check flag from SSshuttle

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
I can't see why this is still SS_NO_TICK_CHECK, it's been this way 5 years and for 5 years it has infact had a tickcheck in fire()

I don't know what effect this may have, maybe test merge it for a few rounds.

### CODE REVIEW

**Comment by Cyberboss** [comment]
`CHECK_TICK` != `MC_TICK_CHECK` because the former doesn't handle proper subsystem pausing

**Comment by optimumtact** [comment]
if you dont know, you shouldn't change it

**Comment by MrStonedOne** [comment]
no_tick_check is pretty hacky in how it works, in certain odd cases the mc could day full on seconds to decide to run the thing. if there is any indicate ssshuttle isn't running when it should removing this could work. Im not opposed to removing the entire flag, it takes up the most lines of code out of any single flag.

**Comment by Cyberboss** [comment]
Also spooky pointed out fire() does contain `MC_TICK_CHECK`s

**Comment by spookydonut** [comment]
> 
> 
> no_tick_check is pretty hacky in how it works, in certain odd cases the mc could take full on seconds to decide to run the thing. if there is any indicator ssshuttle isn't running when it should removing this could work. Im not opposed to removing the entire flag, it takes up the most lines of code out of any single flag.

As far as I can tell ssshuttle is running fine however it does appear this flag is unneeded, my own testing revealed nothing but a test merge might reveal any issues.

If removing no_tick_check from SMC completely is on the table this would certainly be a step in the right direction.

**Comment by Mothblocks** [comment]
TM'ing on Manuel and Sybil.

**Comment by Mothblocks** [comment]
No issues reported.

**Pull request merged**
