### PR TITLE
Changes MetaSec Offices Layout, lathe location, and adds walls to maintenance by upload.

### PR DESCRIPTION
**Pull request by Son-of-Space**
Another plank to the ship.

## About The Pull Request

This pull request completely redoes the layout for MetaSec to give it a bit more character and tweak balance a little bit. Since part of the warden's job is to control and distribute gear/weapons, I've moved the lathe to the armory. I also fixed the issue where AI upload turrets would fire at random things in maintenance by pruning the windows a bit.

Here's the full layout:
image

The new firing range adds a lot more vulnerabilities for sec:
image

And the HoS' office has exchanged some of its natural defenses for a pair of cowboy boots and a few new ways to use it:
image

**EDIT**
I also swapped the emergency toolbox and wirecutters for an electrical toolbox, because shocked windows.

The lathe's new location:
image

New windows:
image

## Why It's Good For The Game

Adding more subtle ways for security to be breached is almost always good. Some of the changes will also affect gameplay (See the vendors by the eastern maintenance crushing someone trying to invade from that way).

Having the lathe out in the sec office completely negates the point of the warden and HoS controlling lethal weapons and gear when any officer can walk in, print what they want, and go without anybody noticing. This brings back the potential to properly curate and distribute gear/weapons, and if it goes well on Meta I'll implement it on the other maps as well. Hopefully the additional vulnerabilities to sec will balance out this change.

## Changelog
:cl: Son of Space
add: Completely redid MetaSec's Offices
balance: Moved MetaSec's lathe to the armory
fix: pruned windows in maint by the upload on Meta
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
This is good! I like this a lot. Only nitpick is the south-side of the briefing room looks like it may feel a little weird. Especially that couch and consoles.

**Comment by Cartographer-D** [comment]
Sec couch, sec couch.

**Comment by Pugie** [comment]
The regular windows on the south wall of the firing range seems really arbitrary. It doesn't effect balance much because the grilles arent shocked in space nor are they non reinforced windows in space, while also making little sense to have non reinforced windows in a FIRING RANGE

**Comment by AlinaStarkova** [comment]
> 
> 
> The regular windows on the south wall of the firing range seems really arbitrary. It doesn't effect balance much because the grilles arent shocked in space nor are they non reinforced windows in space, while also making little sense to have non reinforced windows in a FIRING RANGE

we dont know if they are shocked or not, to take the screenshot he turned off the layers for pipes and cables. so they might be there just invisible for the sake of the screenshot

**Comment by SkeletalElite** [comment]
The back window of firing range should be a wall otherwise lasers in the firing range might fly into the HOS office through the adjacent window.

**Comment by AlinaStarkova** [comment]
> 
> 
> The back window of firing range should be a wall otherwise lasers in the firing range might fly into the HOS office through the adjacent window, doesn't make sense for the window to be there.

i agree on that one, thats a design flaw on NTs behalf, well, that or remove the window on HoS room, either or

**Comment by MrDoomBringer** [comment]
+1 on setting the firing range inward facing windows to walls, turns the firing range into a bit more of a potential hiding spot for criminals or escapees or whatever

**Comment by Bawhoppen** [comment]
If you rearrange the HOS consoles and desks, you could leave open the rare opportunity for a shooter to shoot through the back of the firing range, through the windows, and into the HOS while they're sitting in their office at the chair.

**Comment by SkeletalElite** [comment]
Another thing, I feel like the lathe being in the armory is just going to be used as justification for sec to open the armory roundstart and never close it.
If you're okay with that then whatever I guess, but that lathe prints more than just guns.

**Comment by AlinaStarkova** [comment]
> 
> 
> Another thing, I feel like the lathe being in the armory is just going to be used as justification for sec to open the armory roundstart and never close it.
> If you're okay with that then whatever I guess, but that lathe prints more than just guns and the guns dont have firing pins anyways.

thats a behaviour issues admins are supposed to discourage with their powers, we shouldnt be mapping based on how we believe people will act, and map based on how we want people to act

**Comment by BeloneX** [comment]
image
Long straight corridors both look awful and are terrible for game balance.

**Comment by Fikou** [comment]
extremely minor nitpick but if youre gonna edit it imo hos should have a random spawn in his office

**Comment by SkeletalElite** [comment]
> thats a behaviour issues admins are supposed to discourage with their powers, we shouldnt be mapping based on how we believe people will act, and map based on how we want people to act

I don't exactly know how an admin would go about "discouraging" opening the armory roundstart without outright telling people not to which is not only hardcore railroading but is only something that needs to be done because that would make sec's lathe the ONLY lathe that can't be accessed by the main members of it's department. You don't see the cargolathe being put in the QMs office or the medlathe in the CMO office.

**Comment by wesoda25** [comment]
I also disagree with putting the lathe there. Having it in a room connected to maintenance makes it less secure and makes it easier on the crew trying to get items that are only obtained through it. Putting it in the armory is a decent sec buff.

**Comment by MrDoomBringer** [comment]
@wesoda25 cartographer isnt trying to hide the fact that this is a sec buff he describes it as a buff in the PR description

also the solution is to make a seclathe for guns only (no ammo, etc) and place it in the armory, much cleaner and makes way more sense than any other option imo

**Comment by Tlaltecuhtli** [comment]
why move sec lathe into armory? guns are probably the least printed thing when their high research price and low priority for scientists makes them unavailable for any threat before shift is fucked or antags have been all killed. 
i dont see any improvement for warden job in baby sitting 5 officers and a detective asking to print ammo or bolas every 2 min , thats more of a cargo job, when u should watch cams and process prisoners, doing what you signed for.

**Comment by CRiPLe1000** [comment]
Moving sec lathe to armory is a terrible idea because it robs security from the ability to print stuff they need behind access to armory while every other department gets access to their respective lathes included in the job access. And the reasoning? Weapon control. With (almost) all weapons being late in the tech tree. With them being _situational_ at best. After recent nerf to shotguns. While adding even more vulnerabilities to Brig on one of the most played maps. With Robotics having easier access to more powerful versions that does not need firing pin.

> Having the lathe out in the sec office completely negates the point of the warden and HoS controlling lethal weapons and gear when any officer can walk in, print what they want, and go without anybody noticing.

Let me give you a question - when people are actually printing guns from sec lathe? There are some things that needs to be done before even doing it:
a) guns needs to be researched and they are really far in the tech tree, the most probable moment when anyone from sci researches them is when Roboticist is arming Gygax they just built and even then, nobody will tell security "Yeah, you can now print new guns!" Even more, those guns are useless until you add a firing pin, with electronic ones being locked in armory anyway, leaving only Test Range and Mindshield Firing Pins (hint, one of them is useless unless used for a prank).
b) there needs to be enough materials to print them, which is another department that needs to get involved
c) there need to be a need for a gun to be printed - lets be honest, most guns that are printable are _situational_ at best, x-ray rifle for Malf AI (which is usually defeated with roundstart equipment by the crew), beam rifle with its mode of firing is only useful against the blob and the Advanced Energy Gun are mediocre at best, for some slightly better then normal energy gun, for others slightly worse because you cant recharge it.

Ok, so we have all of these done, guns researched, mats are not a problem, people want to print a gun.
But we are forgetting about the other use for the lathe - printing actually used items like bolas or forensic scanners, nonlethal ammo (remember, slugs and buckshot are not available for crew at this moment) - items that are actually being used by security officers. Lets lock officers from accessing those items when there is lack of them. No department is locked out of their own lathe and they items as deadly (if not more) ready to be printed. 

To sum up, this PR is a stealth nerf to security dressed as a layout update, put in between like it was a minor thing, while its a substantial change. It will end up the same as the R&D console situation, people will just skip over and break in, ask AI to open armory because they need to use lathe (and bypass warden while accessing the armory which is the opposite of what you wanted to do), they will hack into armory, its one airlock after all and nobody will scream at you from sec if you want to break in - all of this because they are locked out of their own lathe. In my opinion, you should remove that change from this PR as its a substantial balance change which needs discussion on its own, put lathe above secway (or replace it, nobody uses it anyway) and after its merged, open a new PR that moves lathe to armory with changes to all the stations - if you need to make that change, do it on every map as it shouldn't be counted as a quirk of the location but as a balance change (which should be universal across every map). Other solution is what was mentioned by @MrDoomBringer - split lathe into two: gun and sec lathe. It will need coding, of course, but that is why I am proposing to split this PR into two - more time, more discussion, better end result for all.

Outside of that **_minor_** change, i like that new layout.

**Comment by Pugie** [comment]
Forensic scanners shouldnt be printable anyways

**Comment by Cartographer-D** [comment]
So it seems like people can't decide whether the lathe is a buff or nerf to sec. : )

On "justification for sec opening the armory roundstart," If they want to open the armory into the main sec hallway where people like the lawyer, heads, and anybody else piggybacking into the department can just waltz in and take what they want... well... they wouldn't be doing a very good job as Warden/HoS, and roundstart opening the armory without a clear threat has traditionally been a punishable offense as powergame.

Belone's comment: redesigning the tool storage area isn't in the scope of my PR, so I'm not touching that hallway beyond the QoL improvement I made.

Bawhoppen's: I'll try to rearrange the desks : )

Now my personal thoughts on the lathe as a buff or nerf. It's really a nerf, and I only say it's a "buff" because people like tlal and wesoda will say it's a buff. Even if they're right, I deliberately put more vulnerabilities into the department to counter that, but I still think they're wrong. This change is being made to counteract powergame, because every single sec officer I've seen nowadays will print advanced eguns, xrays, etc. without any recompense and while the material cost is "high" it's still very easy for the entire sec team to get 2-3 guns with mindshield implants for each person. The number of times I've seen officers with xray guns, space adaptation, and thermal vision 30 minutes into the shift is uncountable.

It's a nerf to sec (That's good for the game) because instead of having every single officer running around with a lethal arsenal in their backpack halfway through the shift, it's something that the warden or HoS will have to control themselves. If there is no Warden or HoS, officers will have to rely on the AI, CE, hacking, etc. to get into the armory. This runs parallel to the shotgun changes and adds another soft barrier to security being able to step up and lethal threats whenever they want. There are very few non-weapon tools that sec can utilize on the lathe unless you're the warden, in which case you already have access.

This change will encourage players to cooperate with others if they want to have ideal loadouts, which discourages powergame and provides an opportunity for better escalation as security against antagonists.

**Comment by Cartographer-D** [comment]
Additionally, outside of what I'm fairly sure will happen with this change, nobody really knows until it's been done. There's a reason why I'm only doing this change for meta right now, and it's to see how it works out. If we revisit in a month and find that it isn't only powergamers complaining about the change, I'll be the first to move it back to the office.

**Comment by Tlaltecuhtli** [comment]
this is a poorly thought balance as much as the moving rnd console to rd office but you can print the circuit anyway,
powergamers will just hack in or ask ai and warden hos are gonna bolt open the door anyway after 10 min shift reveal of the cult rev ops lings if your problem is guns, just remove mindshield pin as its dumb, armory has an 14 pins and they can be bought if they ever run out.
this only punishes people who dont want to step in the armory to print zippies or flashlights and other basic gear that shouldnt be restricted

**Comment by Cartographer-D** [comment]
lmao we all know you aren't going to the lathe to print zippies, especially when there's more than 10 in the vendor. If you want I'll add a restocking unit to the vendor for you!

**Comment by AlinaStarkova** [comment]
they really just need to make a seperate lathe for the guns, because the whole point of warden and armory was that officers weren't supposed to have lethal weapons unless handed out to them due to an emergency, the point of the armory is useless right now, oh, eguns are locked away? who cares, i can print weapons 5x more powerful as any random officer, heck, even the detective too

alternatively, make it so you need warden or hos access to actually print weapons from the lathe. either way, having a ton of lethals outside of the armory is counter the point of the armory.

and to everyone talking about "b-but its locked behind tech!!", yea, which can be researched in about 5 minutes if toxins does their job. on top of that, have you considered we dont just open the armory 30 minutes into the round just because some time has passed? likewise giving lethals access just because time has passed and a research was done is moot

also we are talking about the codebase/map, which is used on more than basil-20min-round-machine. even within tg servers manuel and terry tend to have longer rounds

**Comment by CRiPLe1000** [comment]
@Cartographer-D 
First of all, thanks for confirming that its a nerf in your eyes, we can work with that as its cleared.
However, im still not convinced about moving lathe and i have some doubts.
Also here was a comment that i spent writing for like an hour or more but i cut it out as it turned into rant where i was shitting on basically everything and was getting nowhere.

I will just repeat myself instead - remove from that PR sec lathe, leave it in general sec, for now at least and then create a new PR with sec lathe being split into gun one and general sec one so we can testmerge and try it out. You will only see the change on one map, which add another variables to the outcome, limits the impact etc. Maybe that change is not needed in general (not only in my eyes), maybe the change will help in the flow of the round. This change, while small in the first glance is rather big and it needs testing on every possible map. So yeah

**Comment by Cartographer-D** [comment]
I'm not going to entertain moving the seclathe from the armory, it's a part of the layout changes and I'm holding to that.

**Comment by Zytolg** [comment]
I find myself agreeing with the topic of the seclathe and the prospect that it shouldn't be. The War Room is already a secure area, being tucked away in security. Any break-in in order to use the seclathe before risked the likely outcome of being spotted and brutalized by the forces of security. This change relocates the seclathe into one of the most secure rooms on the station, and therefore makes it so that illicit access to the lathe is a non-option for most who would seek it. It is securities job to keep an eye on objects such as the seclathe, and while you might argue that this PR does exactly that, it's at the detriment of tasking the Warden with handling all seclathe requests. One person should not be responsible for departmental printing.

**Comment by Cartographer-D** [comment]
> 
> 
> I find myself agreeing with the topic of the seclathe and the prospect that it shouldn't be. The War Room is already a secure area, being tucked away in security. Any break-in in order to use the seclathe before risked the likely outcome of being spotted and brutalized by the forces of security. This change relocates the seclathe into one of the most secure rooms on the station, and therefore makes it so that illicit access to the lathe is a non-option for most who would seek it. It is securities job to keep an eye on objects such as the seclathe, and while you might argue that this PR does exactly that, it's at the detriment of tasking the Warden with handling all seclathe requests. One person should not be responsible for departmental printing.

Nobody invades security to print guns from the lathe - the only people that it wholly benefits to have outside is security, as they enjoy the benefit of freely printing guns without the additional stopgaps to doing so. It's bad from a powergame aspect, bad from a roleplay aspect, and bad from an escalation aspect.

While it's harder to print guns, which are never done, it's now easier to get a traitor objective and mindshield implants, which is more than a fair trade given how infrequently the lathe is abused to the detriment of security (It's more frequently used to mass print weapons to give to the crew during emergencies like a blob than used by a traitor to get an energy gun).

**Comment by AlinaStarkova** [comment]
> 
> 
> I find myself agreeing with the topic of the seclathe and the prospect that it shouldn't be. The War Room is already a secure area, being tucked away in security. Any break-in in order to use the seclathe before risked the likely outcome of being spotted and brutalized by the forces of security. This change relocates the seclathe into one of the most secure rooms on the station, and therefore makes it so that illicit access to the lathe is a non-option for most who would seek it. It is securities job to keep an eye on objects such as the seclathe, and while you might argue that this PR does exactly that, it's at the detriment of tasking the Warden with handling all seclathe requests. One person should not be responsible for departmental printing.

i may soon work on splitting the lathe into a normal sec gear lathe, and a lethals/gun lathe specific to the armory, i do agree locking off ALL access to officers makes wardens job a pain, but the idea of lethals being easily accessible to all officers goes against the very idea of armory/warden in the first place.... i mean come on? lock away dinky lasers in a secure room officers cant access, yet 10 minutes into the round all officers + the detective can print as many lethal guns as they want and unlimited ammo, guns that are literally objectively atleast 2x superior to whats in the armory? sounds like a script written by the clown as a prank not gonna lie

**Comment by Cartographer-D** [comment]
Should also point out that the warden will certainly have enough time to print guns for sec if they also have time to distribute them from the armory - it's a miniscule change that better fits their job description

**Comment by AlinaStarkova** [comment]
> 
> 
> Should also point out that the warden will certainly have enough time to print guns for sec if they also have time to distribute them from the armory - it's a miniscule change that better fits their job description

to be fair, the wardens time issue is more for *everything* else in that lathe, not just the guns, wether it be bolas, huds, nightvision, or well, literally every category except (most) of the weapons and ammo category + the mindshield firing pin. hence why im planning on splitting the lathe, they should never have been combined in the first place tbh

**Comment by SkeletalElite** [comment]
The only place where security has thermals and 20 guns every shift is maybe Manuel.
Every other server no one even touches sec tech tree unless a robo is trying to make themselves a mech.

**Comment by Cartographer-D** [comment]
If vendor prices are too high to afford what's in them, which I don't think they are for a reasonable sec loadout, that's something to talk to Arcane about and is a vendor problem, not a lathe problem.

I'm considering adding a restocking unit to secure gear storage, though!

**Comment by Cartographer-D** [comment]
Fixed HoS Shutters
Changed windows on firing range so they don't shoot through the target and into the HoS' console
Placed the sec couch outside the meeting room
Re-arranged the meeting room to look nicer and better fit the original
Added a restocking unit for the sectech to secure gear storage

**Comment by Cartographer-D** [comment]
I am really bad at merge conflicts, I might have to blow this up

**Comment by Cartographer-D** [comment]
OH GOD WHAT HAVE I DONE

**Comment by Cartographer-D** [comment]
Long story short, couldn't update the map without work that's been done since (New areas) and tried to get the new stuff on so I could actually update and resolve the conflicts but it looks like that's not going to happen so uh, time for try number 2, will link back to this PR.

**Pull request closed without merging**
