### PR TITLE
Botany can now make Unstable Mutagen in the Biogenerator for 600 Biomass!

### PR DESCRIPTION
**Pull request by fluffe9911**
## About The Pull Request
Theres been some discussion recently about merging chemistry and botany together and one of the issues mentioned was botany stealing the chem dispenser just to make mutagen so decided to go ahead and make this pr (based off a feature yogs already had) to help fix that

## Why It's Good For The Game
This does not right away remove botanists dependence on chemistry 600 biomass will take some time to get so if a botanist wanted mutagen right away asking chemistry is still the best option but should still make things easier for them in the long run 

## Changelog
🆑 fluffe9911
tweak: Botany can now get mutagen from the biogenerator for 600 biomass!
/🆑

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
epic

**Comment by actioninja** [comment]
No

**Comment by habader** [comment]
100 for a bottle seems a bit much

**Comment by necromanceranne** [comment]
1000 biomass is a fucking pain in the ass to produce without upgrades. Seems reasonable enough though I do worry about the sudden availability of mutagen via the garden.

**Comment by optimumtact** [comment]
This will be irrelevant if botany and chem are merged like I proposed, do not merge this in the meantime.

**Comment by fluffe9911** [comment]
Yeah kinda a just incase the whole chemistry botany thing ends up falling apart *shrug*

**Comment by ATH1909** [comment]
Uh, lowering the biomass cost of this might be a good idea; 1000 biomass is a LOT, especially when you remember that 30u of mutagen only gets you 6 shots at mutating a plant's species, each of which only has a 10% chance to succeed. In short, you're paying 1000 biomass for a <47% chance to mutate at least one plant.

**Comment by fluffe9911** [comment]
eh fair enough

**Comment by WaterStBlues** [comment]
@optimumtact why are you so opposed to QOL features for botany/chem before your hypothetical merge goes through? Guarantee lots of stuff would be totally overhauled when(if) it finally does, making much of these changes irrelevant afterward. What isn't overhauled can be reverted/balanced once it's said and done.

**Comment by Shardj** [comment]
> This will be irrelevant if botany and chem are merged like I proposed, do not merge this in the meantime.

Or merge it since it's a good pr... it won't matter because you can undo it with your chemistry botany merge pr

**Comment by Teepeepee** [comment]
what do you mean by "1000 biomass is too much"? just plant like three 50 potency perennial growth wheat you can make roundstart and you'll be at 1000 biomass each harvest

**Comment by ExcessiveUseOfCobblestone** [comment]
@WaterStBlues this is not a QoL when it circumvents both botany-chemistry interaction and utilizing the chemistry aspect of botany. It's powercreep.

Personally I have no intention of merging this regardless of the chem/bot overhaul success.

**Comment by fluffe9911** [comment]
@ExcessiveUseOfCobblestone I mean it does not completely remove botany and chem interaction due to the fact it requires 600 biomass per bottle for less then a 50% chance of a mutation asking chem for mutagen is still the quicker and better option in the short term this just gives botany a alternative just incase chem is dead or its late game and they got enough biomass to be pretty much self sufficient (although at that point they most likely are producting mutagen using the blumpkin technique anyway)

**Comment by ExcessiveUseOfCobblestone** [comment]
Portable chems still exist right?

**Comment by fluffe9911** [comment]
Oh yeah forgot those existed yeah guess thats another option assuming science does there job *shrug*

**Comment by optimumtact** [comment]
Okay, well let me be more clear then, even if my merge wasn't going to go ahead, which it maybe wont.

I still wouldn't merge this because it's literally reducing department interactions.

**Comment by fluffe9911** [comment]
Welp

**Comment by FantasticFwoosh** [comment]
I didn't take my biogenerator PR's in such a direction to make working and interacting with others invalid.

- The only thing you're earning :+1: 's for is that you've removed the only skill curve or time-gate that seperates intermediary gardening for making chef food through plant maintenance, to plant mutations.

On the whole biogenerator's work better in my experience when products are mainly relevant to other people who can have access to the machine (assistants in public garden, chefs etc.) rather than just botanists.

**Comment by fluffe9911** [comment]
@FantasticFwoosh Im starting to feel like a broken record repeating this honestly but it does not remove chem and botany interaction since it takes time to get 600 biomass and you only get one bottle from it asking chem is and will always be the better option assuming chem is doing there job this was supposed to help deal with the issue for the rare occasions botany steals the chem dispenser or for the times theres no chemist's working at chem although I recently remembered chem boards where a thing so thats still a option I guess anyway atleast I gave a shot at a alt solution *shrug*

**Pull request closed without merging**
