### PR TITLE
Makes stamcrit not immediately

### PR DESCRIPTION
**Pull request by homexp13**
## About The Pull Request

Makes entering stamcrit not immediately. You have a few time (0.8 seconds) to be stamcrited

## Why It's Good For The Game

In my opinion, stun based weapon are too OP. Especially batons, one single hit gives too much advantage in combat. There is a only a few ways to counter play like chems, hulk and simply distance. After you have been batoned one time, what you can do is just escape, to avoid second hit.
My view is that after the second hit, you should still be able to fight back. This will give several opportunities in fight against stun weapon:

+ Use a trump card (activate granade, heretic blade, teleport)
+ Have one extra hit or shot, so you can win the fight even though you was stamcrited and/or stamcrit opponent in retort (parallel batoning)

So these opportunities will make security be more careful and not just rush someone with baton and disabler/laser,  cuz even after your attack opponent can win or go away.

There is a video if it is hard to get what i mean

https://user-images.githubusercontent.com/52973135/224629591-ad842556-6f89-4b30-89b0-0a770293f74d.mp4

## Changelog
:cl:
add: stamcrit takes time to be entered
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
> In my opinion, stun based weapon are too OP. Especially batons, one single hit gives too much advantage in combat. 

> My view is that after the second hit, you should still be able to fight back. 

I disagree completely, and nobody has ever been able to convince me of this, and I will politely suggest you will not either. By framing it this way I have no choice but to close your PR as per headcoder pronouncements:

image

**Comment by Sakamoto4ka** [comment]
=(

**Comment by Vect0r2** [comment]
aww that's sad

**Comment by Mothblocks** [comment]
Making a change *like* requiring 3 hits. My point is that this makes stun batons significantly worse in single fights, which is going to make them absurdly worse in multiple person fights, where I think they are very well balanced

**Pull request closed without merging**
