### PR TITLE
Fixes the lore

### PR DESCRIPTION
**Pull request by Aloraydrel**
Gang might be dead but the lore isn't

### CODE REVIEW

**Comment by coiax** [comment]
Wait, gang mode is dead?

**Comment by KingPhilipIII** [comment]
It's been removed from rotation. General opinion is it's a good mode but needs to be redone.

**Comment by kevinz000** [comment]
actually lots of people say it's shit and seriously needs a redo

**Comment by PKPenguin321** [comment]
There's no general opinion until we have a real poll smh

**Comment by optimumtact** [comment]
lorebus has no power here

**Comment by Shapsy** [comment]
But that's a legitimate oversight in the code?

**Pull request merged**
