### PR TITLE
Watertanks explode when shot

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Watertanks will now explode when shot.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
what is the lore behind this

**Comment by KorPhaeron** [comment]
They're highly pressurized

**Comment by KorPhaeron** [comment]
@Iamgoofball 

Goof did you ever figure out how to do chem puffs without copypaste or did you just exhaust phil until he gave up on code standards

**Comment by Shapsy** [comment]
Its more of a pop than an a boom, innit?

**Comment by nullbear** [comment]
chem puffs? I refactored chem grenades completely so you should be able to just use the global chem_splash proc for it.

**Comment by KorPhaeron** [comment]
I want to convert a water tank to holy water and then blow it up in a cult base

**Comment by Kromgar** [comment]
We dont have cult bases no more. No structures ya know

**Comment by nullbear** [comment]
Well to do that with these it should be fairly easy. 

call

`chem_splash(loc, 5, list(reagents.reagents)) `

for a 5x5 splash of whatever is in the tank.

**Comment by KorPhaeron** [comment]
Thanks

**Comment by Xhuis** [comment]
Title is a little misleading. :+1: otherwise.

**Comment by bgobandit** [comment]
clowning intensifies

**Comment by AnturK** [comment]
Add content reagents to the particle effect so it extinguishes fires.

**Comment by ma44** [comment]
Time to lube all the floors with my high capacity water tanks :D

**Comment by optimumtact** [comment]
boom

**Comment by Xhuis** [comment]
:boom: :droplet:

**Pull request merged**
