### PR TITLE
you can now open firelocks with your bare hands, and your bear hands

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
you can now open firelocks with your bare hands after a 6 second delay. simplemobs can do it too, im still iffy on that and i only did it for the bear pun anyways :trollface: 

## Why It's Good For The Game
dying because you were slow to grab a crowbar roundstart is ass. i dont see any reason why it should be impossible to open firelocks with your hands, and its still dangerous to not have a crowbar since you have to wait 6 seconds for every firelock.

## Changelog
:cl:
add: Nanotrasen has pushed a firmware update to its employees to allow opening firelocks with their bare hands after a 6 second delay
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
what if simplemobs or monkeys could also do it that would be pretty funny.....

**Comment by Farquaar** [comment]
See https://github.com/tgstation/tgstation/pull/57163

**Comment by IndieanaJones** [comment]
Please let this one get merged, firelocks are genuinely awful currently

**Comment by wesoda25** [comment]
It’s kind of shitty how crowbars are almost a necessity alongside internals. Survival box clutter is shitty so this makes the most sense, crowbars will still be preferable so their usefulness is preserved.

**Comment by Kylerace** [comment]
> See #57163

If lemon and moth still hate this solution enough to close it then so be it, but I don't care about fastmos itself even if it make the forelocks issue more pressing. Being stuck in an area with firelocks and no crowbar shouldn't leave you with zero options. That's it. If the do_after needs to be longer that's fine but I'm not convinced that changing how firelocks behave is going to fix the problem described rather than make it less common.

**Comment by Kylerace** [comment]
@LemonInTheDark turns out youve closed a pr that does functionally the same thing as this before. do you still hate this? i dont think its fair to label it as a solution to firelocks being closed by fastmos more often. its necessary because players shouldnt be stuck in a room with no hope to leave because of a device meant to improve station safety. regardless of how often firelocks get closed they create a situation where survival is completely dependent on grabbing a crowbar in the beginning of the round which i dont believe is fair. having them be openable without a crowbar after a time limit, even if its higher than the one i currently have, allows players to get out of a room just dangerous enough to kill them.

**Comment by ATH1909** [comment]
finally

what if we reduced the time required to open a firelock to 3 seconds and also added the ability to open unpowered doors (the other primary reason why grabbing a crowbar is an absolute necessity) with your bare hands over the course of 6 seconds 😳

**Comment by LemonInTheDark** [comment]
I closed that pr in the context of atmospherics changes, but I'm still not really all that hot on the idea even outside of that context. I'll elaborate in a bit

**Comment by maxymax13** [comment]
this wouldnt have to be such a pain if only like 20% of oxygen closets actually had a damn toolbox instead of just a medbriefcase or single lonely oxygen tank

**Comment by Kylerace** [comment]
pending for changes that ninjanomnom wanted

**Comment by Kylerace** [comment]
closing because the changes requested by maintainers make it significantly different from what it started as, will open a new one either today or tomorrow

**Pull request closed without merging**
