### PR TITLE
ICEBOX Multi-z: You've heard of wage-cage, get ready for the worship-pit (chapel, library, and departures remap) (art gallery finally)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

This PR remaps the library, chapel, and departures lounge of icebox station. Notably moving the chapel to the lower level and having a large open space above. 

Pictures below: 

<details>
  <summary>The Library's been expanded size-wise very slightly, and has an all new art gallery to view and save paintings.</summary>

image
</details>

<details>
  <summary>The maintenance behind the library received very minor shifts.</summary>

image

</details>

<details>
  <summary>The mass driver room is still on the top floor, and the pit outside now falls down to the bottom z-level.</summary>

image
</details>

<details>
  <summary>The departures lounge has been expanded. It now has chairs, a proper security outpost, and an emergency EVA storage that requires EVA access but has public access on red alert.</summary>

image
</details>

<details>
  <summary>The chapel itself still resides in the same location, but now spans across two levels vertically, and has a balcony overlooking it. </summary>

image

</details>

<details>
  <summary>Downstairs the chapel is a bit larger than it was before, also boating a graveyard. The chaplain also gets a relic closet now like on other maps, and a little bit of maintenance behind the chapel.</summary>

image

image

</details>

## Why It's Good For The Game

More cool multi-z interactions for icebox station.

## Changelog

:cl: Melbert
add: Icebox: The Chapel, Library, and Departures Lounge (and some maintenance around it) have been revamped and expanded to utilize multi-z.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
jesus the escape hall looks like an airport terminal

...which is great love the changes

**Comment by Zytolg** [comment]
I took a look at the whole bottom-z again, and this actually joins up to what I've been calling the "Icebox Basement Core" quite nicely. I certainly don't think we'll be able to expand any more eastwards after this, but it's not like there's anything left over there anymore. I like what I see here. Great work!

**Comment by LemonInTheDark** [comment]
The chapel being a part of that hallway's airspace is a bit annoying, but what can ya do

**Comment by Fikou** [comment]
great job on the chapel i love the graveyard

**Comment by wesoda25** [comment]
Awesome changes!

**Comment by Farquaar** [comment]
Love the little graveyard outside. I look forward to the individual graves being replaced with a huge corpse pit in the near future.

**Comment by MessoDepresso** [comment]
Before this is merged, I wanna ask if the Chapels lower maintenence lines up at all with any above it? And if so, Id suggest a ladder down that isnt engineering restricted, so that that maintinence area isnt just kinda isolated.
Just a thought tho, no complaints if its not done. It all looks feckin amazing.

**Review by Maurukas — CHANGES_REQUESTED** [review]
This is impressive. Not only does it look amazing, there's virtually none of the usual mapping issues and I had to go digging around to find anything that needs fixing. At this rate Icebox is going to be one of the best maps in rotation.

<details>
<summary> Consider some lighting in the confession booth </summary>

image

</details>

<details>
<summary> Doubled wire here</summary>

image

</details> 

<details>
<summary> Area issue with fire locks on the balcony </summary>
The balcony is inside the chapel area, and some of the tiles aren't considered adjacent to the hallway area. This results in firelocks not behaving in a useful way:

image
image


</details>

**Pull request merged**
