### PR TITLE
make explosions affect the z levels above and below

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
See title, adds the ability of explosions to make the above and below zlevels to explode at a decreased radious
Gibtonite will only expand the explosion to the level below them (to protect the miners from the wrath of the players and admins)

## Why It's Good For The Game
Explosions are more dangerous and staying on a different zlevel won't save you from them anymore (no more dropping bombs on the lower levels without being affected by them)

## Changelog

:cl:
balance: explosions affect the zlevels above and below, Gibtonite will only expand the explosion to the level below them
balance: floored the explosion sizes to remove the 0.01 ranges being equal to 1
/:cl:

### CODE REVIEW

**Comment by NamelessFairy** [comment]
Won’t this cause a lot of accidental breachs on ice box from miners breaking gibonite under the station?

**Comment by Ghilker** [comment]
> Won’t this cause a lot of accidental breachs on ice box from miners breaking gibonite under the station?

I'll add an argument for gibtonite to affect only the level below them

**Comment by AMonkeyThatCodes** [comment]
This is not a good way of doing multi-z explosions. If you want multiz explosions to not be unfun nukes you need to use a lens model for the explosions where each z level has a huge drop-off like in the image seen below (It's a crude drawing of a side-perspective.)
image

**Comment by Ghilker** [comment]
> This is not a good way of doing multi-z explosions. If you want multiz explosions to not be unfun nukes you need to use a lens model for the explosions where each z level has a huge drop-off like in the image seen below (It's a crude drawing of a side-perspective.)
> image

agreed, i've made the explosion falloff by 1/10th of the original explosion and expand more to the next level if present by another 1/10th falloff

**Comment by newfren** [comment]
This is only for connected z-levels right? It won't explode a random area of space?

**Comment by TemporalOroboros** [comment]
I can't wait to play atmospherics and maxcap the station from the mining level. 50Ks hit 4500 range which makes them maxcap on the station level from the lower icebox mining z.

**Comment by Ghilker** [comment]
> This is only for connected z-levels right? It won't explode a random area of space?

yes only station levels

> I can't wait to play atmospherics and maxcap the station from the mining level. 50Ks hit 4500 range which makes them maxcap on the station level from the lower icebox mining z.

you can't make a bomb bigger than 5, 10, 20; so from the lower mining you'll get 0.5, 1, 2 on the level above and 0.05, 0.1, 0.2 on the station

**Comment by TemporalOroboros** [comment]
> you can't make a bomb bigger than 5, 10, 20; so from the lower mining you'll get 0.5, 1, 2 on the level above and 0.05, 0.1, 0.2 on the station

Assuming that explosion size the effect would be negligible then. After all, explosion ranges are rounded down.

Aside from that, I would recommend making the propagation a for or while loop. You've currently made it hardcoded to only propagate up to two z-levels which will be annoying to whoever tries to rebalance the scaling.

**Comment by oklews** [comment]
this reminds me of how the SM delamination on tram doesn't cause hallucinations for the higher level

**Comment by Ghilker** [comment]
> this reminds me of how the SM delamination on tram doesn't cause hallucinations for the higher level

Fair, might fix that too

**Comment by oklews** [comment]
> > this reminds me of how the SM delamination on tram doesn't cause hallucinations for the higher level
> 
> Fair, might fix that too

That's a fix separate from this though, but I do love the PR regardless.

**Comment by Ghilker** [comment]
added a for loop for explosions call on all levels (upward and downward)
floored the explosion sizes to remove the 0.01 ranges being equal to 1

**Comment by D4C-420** [comment]
I got to be against the idea of gibnoite being able to explode the z level below because of the fact on icebox there are two mining levels. Lets say miner A. is on the upper mining level and hits a piece of gibnoite. Miner A. logically runs away from the bomb. Now lets assume that miner B. is on the lower level of mining and is unknowingly right under miner A.. They are below the gibonite and get hit by whatever it. I would not call it fun for anyone for that miner B. to get hit by that explosion however small because they had zero way to react or prevent themselves from getting exploded by the actions of miner A on the upper z level who had no idea that miner B was below them when the struck the ore..

**Comment by Zytolg** [comment]
OH MY GOD IT'S HAPPENING
OK CALM DOWN

**Comment by oklews** [comment]
> I got to be against the idea of gibnoite being able to explode the z level below because of the fact on icebox there are two mining levels. Lets say miner A. is on the upper mining level and hits a piece of gibnoite. Miner A. logically runs away from the bomb. Now lets assume that miner B. is on the lower level of mining and is unknowingly right under miner A.. They are below the gibonite and get hit by whatever it. I would not call it fun for anyone for that miner B. to get hit by that explosion however small because they had zero way to react or prevent themselves from getting exploded by the actions of miner A on the upper z level who had no idea that miner B was below them when the struck the ore..

I doubt it would be a common occurrence. It would do some damage and maybe delimb, maybe, but a stop by medical for a rare occurrence is equal random event heart attack imo.

**Comment by optimumtact** [comment]
I'm not interested in this, our engine just isn't setup in a way taht would make this interesting or exciting, not to mention the issues with trying to map a 2d grid into a 3 dimensional one and all the extra code required.

No thanks.

**Pull request closed without merging**
