### PR TITLE
A step up: The Lawyer Suit Resprite!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Based originally on sprites from PR: [Resprites the lawyer suits and skirts #4888](https://github.com/BeeStation/BeeStation-Hornet/pull/4888) from BeeStation, this PR aims to alleviate the issue of those incredibly soulful sprites being neglected due to their poor appearance, in exchange for fancier, much more formal versions for all to enjoy!
image

This PR also removes the old and strange "Black Female Suit" and "Black Female Suit Skirt" sprites, in favor of a more interesting reference, for those who want to truly be a **Criminal** Lawyer: The Good Lawyer Suits!
image

## Why It's Good For The Game
If you take a short look at the current versions of the suit sprites being replaced, the upgrade is undeniably positive!

## Changelog

:cl: PositiveEntropy
imageadd: Resprites the Black, Red and Blue lawyer suits!
expansion: Adds the Good Lawyer Suit, for those who truly want to be a CRIMINAL lawyer!
del: Removes the Black Female Suit and Black Female Suit Skirt

/:cl:

### CODE REVIEW

**Review by Krysonism — APPROVED** [review]

**Comment by wesoda25** [comment]
Is the eye bleed sky blue one still in? I actually liked using the most garish outfits possible as lawyer.

**Comment by Dorsisdwarf** [comment]
> Is the eye bleed sky blue one still in? I actually liked using the most garish outfits possible as lawyer.

the eyebleed blue is the new navy one.

This pr is respriting the garish block-colour suits, not the ace attorney suits

**Comment by wesoda25** [comment]
Imaginos please let us keep the sky blue one 🥺

**Review by Maurukas — APPROVED** [review]

**Comment by Kylerace** [comment]
code is good

**Pull request merged**
