### PR TITLE
New engine floor sprite

### PR DESCRIPTION
**Pull request by WJohn**
Then:
https://i.imgur.com/TqdLspH.png
Now:
https://i.imgur.com/iOnUG6L.png

:cl: WJohnston
imageadd: New reinforced floor sprites.
/:cl:

### CODE REVIEW

**Review by ChangelingRain — DISMISSED** [review]

**Review by ShizCalev — DISMISSED** [review]
I'd speedmerge this if I wouldn't be murdered by Oranges. ♥

**Comment by kingoftheautism** [comment]
@ShizCalev Blink twice if you need help

**Comment by Militaires** [comment]
nigga embed

**Comment by MrDoomBringer** [comment]
thesse are sick

**Review by SpaceManiac — APPROVED** [review]
Unshiny looks fine to me.

**Pull request merged**
