### PR TITLE
Duiffel Spotfix

### LINKED ISSUE #76407: Captains duffle bag spawns empty, no contents
**1. Reproduction**

1. Sign up as captain
2. Check your duffle bag
3. See that its empty when in fact it should have contained a
    - Survival Box
    - Telescopic beacon
    - Station Charter

Even the code agrees with me
https://github.com/tgstation/tgstation/blob/fe3738ffa09de102a48f5b3f5b6b2c6f328a72d3/code/modules/jobs/job_types/captain.dm#L63-L66

Revert #76313 & Test Locally
1. Sign up as captain
2. Check your duffle bag
3. Everything is there as it should be

Conclusion Broken by #76313

@LemonInTheDark

### LINKED ISSUE #76430: You can zip duffelbags not on your person but you cannot unzip them
## Reproduction:

- Go to open up the surgical dufflebag on the table next to you to commit surgery
- It's zipped.
- Try to unzip it
- It says it's locked.
- Have to pick it up to unzip it, then place it back down

### LINKED ISSUE #76441: TK and new duffel -  Telekinesis teleports bag to hand through walls
Screenshot (232)

## Reproduction:
Telekinesis teleports a duffel bag directly to your hand with the new duffel bag PR.

As seen, I managed to teleport the drone duffel bag on display into my hand through a wall. It could also be the unzip feature? As you are capable of unzipping the bag while it is in your TK hand, which then teleports it to you. Will test after the round ends

EDIT: using the duffel in your TK hand to zip/unzip appears to teleport it directly to you. Seems like an unintended interaction as TK should not be teleporting items through physical barriers like walls.

Screenshot (233)
Screenshot (234)
Screenshot (235)

#76313 
@wulfenbach-jpg
@LemonInTheDark 

Maybe this is the real buff duffels need? 😄

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Gives duffelbags their proper slot count
They inherited this from backpacks, but I sorta just forgot about that

[Creates "levels" of locked objects, uses that to make locked duffels work](https://github.com/tgstation/tgstation/pull/76442/commits/c613c00f62fa3ff03bb33737d24da9acbf2050e3)
[c613c00](https://github.com/tgstation/tgstation/pull/76442/commits/c613c00f62fa3ff03bb33737d24da9acbf2050e3)

Turns locked into something that holds defines, this makes life a lot easier. 
Requires a lot of boilerplate because of how many uses of these procs there are and all the passthrough and shit.

Adds a few outfit subtypes to avoid this class of failure in future.

Renames the args in a few but not all touched procs, one thing at a time

Closes #76407
Closes #76430 Had the lock check in the wrong place
Closes #76441 GOD I HATE TK SO MUCH

Wrote half the pr without glasses so if it's weird gimme some grace yeah?

## Changelog
:cl:
fix: Fixes some fuck with duffelbags, them not holding enough + issues with spawning gear in them (job shit and all)
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
https://github.com/tgstation/tgstation/pull/76425

**Comment by SyncIt21** [comment]
> #76425

Yeah we have to close that PR now as this supersedes that

**Comment by LemonInTheDark** [comment]
I mean I basically did what he did but also did the thing he was uncomfortable with. IDk

**Comment by SyncIt21** [comment]
> I mean I basically did what he did but also did the thing he was uncomfortable with. IDK

Isn't it possible to zip the backpack maybe in `LateInitialize()` so you know after all the stuff has been put in we can zip it up then? Does that work?

**Comment by LemonInTheDark** [comment]
> Isn't it possible to zip the backpack maybe in `LateInitialize()` so you know after all the stuff has been put in we can zip it up then? Does that work?

Nha cause it goes like
```
create duffel:
- New (If we aren't in maploading shit)
- Initailize
- LateInitialize
put duffel in back slot
put shit in "back slot" (IE: duffel)
whoops duffel is locked
```

**Comment by SyncIt21** [comment]
You right. Just tested it locally didn't work :(

Anyway you can close #76425 and link #76429

**Comment by SyncIt21** [comment]
If you got the time there are 2 small inconsistencies you could fix

`Initialize()` is defined twice for `/obj/item/storage/backpack/santabag`. You can just merge them into 1
Screenshot (272)

`slowdown` is defined as 2 `/obj/item/storage/backpack/duffelbag/cursed`
https://github.com/tgstation/tgstation/blob/0ef4c3a6b6be3ca5e0a6fa38460bd55cdc8b95d7/code/game/objects/items/storage/backpack.dm#L486

But when the player zips the duffel bag `set_zipped(TRUE)` will disregard it and make it 1 again
https://github.com/tgstation/tgstation/blob/0ef4c3a6b6be3ca5e0a6fa38460bd55cdc8b95d7/code/game/objects/items/storage/backpack.dm#L470

So maybe do `slowdown = initial(slowdown)`

**Comment by Funnytoilet** [comment]
Have you fixed the issue where you aren't given your mid-round traitor gear such as a sliver extraction kit if the duffel is closed?

**Comment by LemonInTheDark** [comment]
> If you got the time there are 2 small inconsistencies you could fix

Thanks for the review, s slightly out of scope but easy to handle, prichiate you letting me know

**Comment by LemonInTheDark** [comment]
> Have you fixed the issue where you aren't given your mid-round traitor gear such as a sliver extraction kit if the duffel is closed?

GAHHHHHHHHHHHH

**Comment by LemonInTheDark** [comment]
I've reverted the locked default change and instead added "levels" of locks to allow abstract insertion to bypass soft locks

**Pull request merged**
