### PR TITLE
Fixes several map issues

### LINKED ISSUE #14727: [Metastation] Mulebot delivers crate to wrong tile in R&D
When a mulebot delivers a crate to the Research and Development lab, it will pass under the plastic flaps, then drop the crate. However, instead of dropping it on the desired tile (which is one tile above it), it drops it one tile down, leaving the crate in maint and also trapping the mulebot inside the plastic flaps.

### LINKED ISSUE #15130: Metastation Chapel
Metastation Chapel area has three air alarms. There are two in the mass driver section and one in the main room.

### LINKED ISSUE #16096: Metastation improperly rotated corner conveyor in disposals.
conveyor
The conveyor below the stacker should be going from bottom to left, when it's actually going top to right.
@metacide

### LINKED ISSUE #16834: Meta: Command Hallway vending machines are in the Gateway area.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #14727 
Affected all maps to some extent, fixed on all.
Fixes #16096
Affected Metastation.
Fixes  #15130
Metastation-only.
Fixes  #16834
Metastation-only.
Fixes a major unreported bug where all the walls of efficiency's syndicate shuttle were virology floors.

I hope this doesn't step on anyone's toes @Metacide @WJohn

### CODE REVIEW

**Comment by xxalpha** [comment]
Mapmerge or manual?

**Comment by ChangelingRain** [comment]
Mapmerge, what else?

**Comment by xxalpha** [comment]
Just want to know for sure, for reasons.

**Comment by Metacide** [comment]
Thanks very much :+1:

**Pull request merged**
