### PR TITLE
Removes 'Cucumber Greek'

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

I don't want to make any jokes or anything this time.  Straightforward removal.

## Why It's Good For The Game

We all know what happened.

## Changelog

:cl:
del: Removes cucumber greek plush 
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
A man once said "There's nothing schwifty about domestic abuse."

**Review by spookydonut — APPROVED** [review]

**Review by Kylerace — APPROVED** [review]

**Comment by BlueMemesauce** [comment]
Remember #62874? We directly reference a literal terrorist organization. Seeing that this just indirect reference, does it really need to be removed?

**Review by ArcaneMusic — APPROVED** [review]
Funniest shit I've ever removed

**Comment by Time-Green** [comment]
End of an era

**Comment by Mothblocks** [comment]
its greek cucumber

**Comment by Thunder12345** [comment]
I think it's dumb to remove a reference because of one person involved with the show it's referencing being bad.

Remove it anyway because the joke aged all the way into the grave within days and is just grating now.

**Comment by san7890** [comment]
Add the sprites here for brownie points https://github.com/tgstation/SS13-sprites

**Comment by necromanceranne** [comment]
Don't so that they never see permeance on any server, for the sanity and health of all.

**Comment by san7890** [comment]
> Don't so that they never see permeance on any server, for the sanity and health of all.

I will save the DMI on my computer and inject it into every shift I play

**Comment by necromanceranne** [comment]
_Monster_

**Review by Imaginos16 — APPROVED** [review]
If I have to stare at that sprite one more time I am smashing my neighbor's window

**Comment by bruhman8ghughug** [comment]
i don't really am in favour for removing stuff just because a guy from the show did a bad thing, but cucumber greek wasn't funny anyways so i don't really care

**Comment by Mothblocks** [comment]
i wish people were honest that they just want it removed because its not funny. we don't need the guy to beat his wife to justify removal. its soap boxing

**Comment by Mothblocks** [comment]
just say you dont like pickle rick

**Review by Mothblocks — CHANGES_REQUESTED** [review]
just be honest and say you dont think pickle rick is funny and i will merge it

**Comment by Imaginos16** [comment]
Well I'll say that even without the context I find pickle rick painfully unfunny, and I don't want it on tg. Simple as that.

**Comment by Mothblocks** [comment]
thinking its not funny and a dumb reference is a perfectly justifiable reason for removal

**Comment by optimumtact** [comment]
I turned myself into a pickle rick

**Comment by carshalash** [comment]
> I turned myself into a pickle rick

Pls

**Comment by optimumtact** [comment]
Dear carshalash

I hope this message finds you well. I understand that recent events involving Justin Roiland have been distastable, and I share your concerns about the impact they may have on our community. However, I would like to remind you that many of the works associated with Justin Roiland are multi-person projects with numerous contributors, including [tgstation13].

While it is important to acknowledge the harm caused by these events, it is also crucial to take a broader perspective when considering their impact on our project. We must consider the implications of removing all content that is associated with Justin Roiland and weigh the impact it would have on our community and the people who have worked hard to contribute to these projects.

In light of this, I would like to request that you make attempts to justify your removal along lines that are not simply outrage based, and actually provide some concrete reasons for removal of a plushie.

Best regards,
oranges

**Comment by carshalash** [comment]
Dear Oranges.

Originally the cucumber PR included the sprite as a way of having pickle rick as a form of cringe humour. At the time, the sprite was quite poorly received in the PR. 

While I, like many others, disliked the plushie since it's conception, I begrudgingly accepted it as a part of the game as something for some people to laugh at in a cringe humour way. While there wasn't an audience for this on the server I played, I interpreted the lack of removal as some form of appreciation for it on one of the other three main /tg/ servers. I find mothblocks presumptions to be quite insulting. I have been enwrapped in assisting two separate domestic abuse cases in the last year, and I think parading around the perpetrator in the name of irony is stupid. 

The only other plushie in the game with no adjacency to SS13 would be the 'goat' plushie, those who find it distasteful at least have the option of flattening it. The rick and morty pickle has no such feature, and it merely exists as a large sprite to reference an episode of a cartoon. Its only actual function in the game is to either have people roll their eyes at it or for **exceptional** human beings to start spamming references to said cartoon ICly.

I'm aware there is a 50/50 chance that you just wanted to see whether I would write anything in response to your message, I chose to do so anyway. Hopefully you found my reasoning suitable.

Regards,
carshalash

**Comment by Mothblocks** [comment]
image

JUST SAY YOU DONT THINK PICKLE RICK IS FUNNY

**Comment by carshalash** [comment]
I posted why I did this and you're still doing this.

**Comment by SuperAggroCrag** [comment]
mothblocks i will dip your hand in boiling spaghetti sauce

**Comment by optimumtact** [comment]
> I have been enwrapped in assisting two separate domestic abuse cases in the last year, and I think parading around the perpetrator in the name of irony is stupid.

Not a single person has done this

>While I, like many others, disliked the plushie since it's conception, I begrudgingly accepted it as a part of the game as something for some people to laugh at in a cringe humour way. While there wasn't an audience for this on the server I played, I interpreted the lack of removal as some form of appreciation for it on one of the other three main /tg/ servers

So you agree there was a reason to add it

>I'm aware there is a 50/50 chance that you just wanted to see whether I would write anything in response to your message, I chose to do so anyway. Hopefully you found my reasoning suitable.

You haven't provided any

**Comment by carshalash** [comment]
Whatever, keep it. I'm too tired of this PR after having mothblocks screaming that I'm lying about my reasoning.

**Comment by optimumtact** [comment]
Because of the negativity that people are directing unfairly towards the other maintainers here, any changes to this plushie are frozen effective immediately for four months.

Once the toxic discourse has passed I will allow uninvolved people to make changes.

**Comment by SuperAggroCrag** [comment]
oranges supports violence against women and i gotta say that's pretty fucking based

**Comment by CMDR-Gungnir** [comment]
Oranges you're a literal sexpest, I really don't think you of all people should be the one to say "We shouldn't remove things for outrage sake" given that you would be one of those people.

Pickle Rick is painfully unfunny, the joke nosedived into the dirt about three days after it started, and I don't think you should be the one to make the decision when everyone else was in support of it, except for Mothblocks who just wanted Carsh to say "it's not funny", and you who seem ODDLY DEFENSIVE of it.

**Comment by SuperAggroCrag** [comment]
im gonna freeze this for 4 months cuz you're being unfairly toxic towards another maintainer who came in here and spammed meritless comments about how UR JUST MAD CUZ U DONT THINK IT FUNNY DANCE FOR ME MONKEY AND MAYBE ILL ALLOW IT and you responded by saying "whatever then close the PR i dont want to deal with them" hmmm who is truly the toxic one? could it be the one who supports violence against women and texting teenage girls sexually inappropriate content? no it's CARSH he's a dilbert

**Comment by optimumtact** [comment]
your toxic behavior is unnecessary

**Comment by CMDR-Gungnir** [comment]
> your toxic behavior is unnecessary and confirms the choice is the right one

Okay, sexpest. Go sexually harass another admin.

**Comment by optimumtact** [comment]
Your behaviour is not acceptable, if you wish to discuss this in a calm manner at a later date, please contact via dm's or forum pm to appeal your ban.

**Comment by optimumtact** [comment]
Your behaviour is not acceptable, if you wish to discuss this in a calm manner at a later date, please contact via dm's or forum pm to appeal your ban.

**Comment by LSommers** [comment]
Pickle Rick was never funny, the sprite is huge, and every time it comes out of the arcade machine I want to instantly roll midround traitor so I can put C4 on the arcade for wasting my tickets.
Also this comments section is a shitshow, like damn.

**Comment by CRITAWAKETS** [comment]
honestly would be funny if the plush was switch to a larry the cucumber reference, that one actually ages pretty well

**Pull request closed without merging**
