### PR TITLE
Fixes winter coats

### PR DESCRIPTION
**Pull request by Ergovisavi**
Due to winter coats magically having the HEAD flag in their body_parts_covered, and yet not occupying the head slot with or without the hood up, and then also having armor values, we have idiocy like the captain being 100% immune to melee and lasers to his head from armor stacking of winter coat + cap's hat.

Fixes this with a pseudoitem, much like how water tanks work. You can no longer wear an item on your head slot with your hood up.

### CODE REVIEW

**Comment by paprka** [comment]
I really really don't like the idea of having seperate items for hoods but if you're going to do this you'd better do the same thing for the chaplain too

**Comment by Dorsisdwarf** [comment]
That would be a 10/10 change, at last no more wearing the spacesuit hat all the time

**Comment by paprka** [comment]
If ergo wants to work with me on that we can generalize this kind of thing to work for all suits with a connected 'hood' (hardsuits would have space helmets for hoods) but the old system of putting the chaplain's 'hood' on was awful. This is actually really great code though, it can be a project for another time. I plan on cutting down how many winter coats there are on the station now that the holidays are over, but that will be in a few days.

**Comment by Razharas** [comment]
Can it be solved without pseudoitems?
Maybe just remove armour of wintercoats all together?
Or removing wintercoats all together?

**Comment by paprka** [comment]
Doesn't fix chaplain hoods raz

**Comment by Razharas** [comment]
I dont want wintercoats to become new iteration of ninja equipment

**Comment by paprka** [comment]
They won't, again if this is a thing we plan on doing I also plan on just converting ergovisavi's system here into a general 'hood toggle' proc for hardsuit helmets, and chaplain's hood, which is cool, unless ergovisavi does it first. You can probably make them have an entirely new path like hood/wnitercoat instead of toggle/wintercoat, but that's up to ergo right now. I understand if he just wants to leave this PR alone and would rather not waste his time on it because redoing all those suits is a large undertaking and all that.

**Comment by Cheridan** [comment]
#7346 resolves this issue in a similar fashion

**Pull request closed without merging**
