### PR TITLE
Mining voucher items no longer spawn below the machine.

### PR DESCRIPTION
**Pull request by harmonyn**
I'm sure this has to do with the machine console layer thing but it is still FUCKING ANNOYING as a miner

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Tested? I don't see how this would fix it

**Comment by bgobandit** [comment]
tested, yes

**Comment by Vidiveni** [comment]
Same problem exists with many other things. Taking explorer suits/other things from suit storages. Printing injectors from DNA console (seemingly randomly). Probably other vendors that I can't remember.

**Comment by FantasticFwoosh** [comment]
Alt click lets you see all the contents of the tile, but i imagine it would be annoying since some machines don't give any feedback when they're working/dispensing. Experimentor was a notorious example of layering gone bad before this became a mainstream issue because it hid in the enlargened faux space of the sprite when it ejected stuff.

**Comment by Vidiveni** [comment]
Alt-clicking is tedius and takes extra time.

**Review by AnturK — CHANGES_REQUESTED** [review]
Order of creation is not guarantee of render order. Set proper layers instead.

**Comment by bgobandit** [comment]
like I said I tested it

**Pull request closed without merging**
