### PR TITLE
Adds 9 New, More Human-Shaped Borg Skins.

### PR DESCRIPTION
**Pull request by SansSarif**
## About The Pull Request

This adds the following 9 additional cyborg skins (3 for service, and 1 for every other department) as designed by our partner @Or-Fi-S:
image
(as Pictured, top row: NT-06F, Hugbot, Mediorb. bottom row: DJBot, Papa Miner, Mixer, V.5, Ringleader, Stereobot)

Each bot has bespoke animations for transforming, each bot has clean sprites, each bot is intentionally unique but tries to stick close to the department/job they are fulfilling. Hats also work mostly nicely on all of them (except for Mixer & Ringleader (who have it disabled) & Papa Miner (Blame the backpack, but i couldn't keep it from that borg.))

## Why It's Good For The Game

While there's nothing wrong with the existing borgs per se, some of the designs are either very old, or simply are the only option for that specific type of borg. Adding additional designs without taking away from the existing ones generally allows for more player expression and makes it easier to distinguish different borgs apart (if the borgs want that!) The focus on this set of new borgs was to ensure several important rules during implementation:

1.  Borgs should not read human when looking at them during a split second (silhouettes are all intentionally removed from the base human/player sprite)
2. Borgs should clearly parse as belonging to the department/job that they are intended to fill (either through color coding, silhouette similarities, or design choices)
3. Borgs should have unique designs (no palette swaps, (there is an intentional choice to mimic existing design choices by existing borgs for peacekeeper/clown, however))

To this end, borgs, while being more human shaped for most departments than their standard counterparts, they are not human, and they are each their own special fellow! We also made sure to not touch any of the existing borgs, you can still be your egg-shaped clownborg with your orange hair, or your pink-polo wearing service borg, or your 3-medkits-in-a-trenchcoat borg. 

image

<details>

<summary>A sample of the animations provided for transformation/movement/idle</summary>

Ringleader Transformation
image
NT-06F Transformation
image
Mediorb Tranformation
image
Mediorb Moving
image

</details>

## Changelog
:cl:
add: adds the ability to choose 9 new cyborg skins across the various cyborg types
imageadd: adds 9 new cyborg skins: 3 for service-cyborgs, 1 for every other type of cyborg
/:cl:

### CODE REVIEW

**Comment by bluetshirtguy** [comment]
Some of those are pretty neat but that grey borg is just a dumptruck ass on legs.

**Comment by Sealed101** [comment]
chinese cartoons
the transformation sequences are great and the sprites are cool but I'm not sure these fit in in the general style of the game

**Comment by axietheaxolotl** [comment]
yeah, i don't think this is it, chief.

**Comment by OverwatchVoice** [comment]
Some of 'em are nice, but that ass has a volume so enormous it'd rival big slappy

**Comment by Singul0** [comment]
The more humanoid design of the new sprites (except for the miner puppy) makes them look more bland and samey. Compared to the droideka, water dispenser and industrial floor scrubber of the old. It's TF2 silhouette character design meme but unironically.

**Comment by Jackal-boop** [comment]
I think this would be perfect for /vg/ but is too anime for tg

**Comment by fishingsman** [comment]
tell me, who made you think this was a good idea

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
Completely ignoring commentary about how this is "anime", I do have an issue with how these are sprited. Most of them are noisy and have no sense of shading whatsoever. If you could somehow improve them until I am done deliberating with Twaticus, great! Otherwise, I am not interested.

**Comment by DAKKA-WAAAGH** [comment]
Ah cool, more fetish art for borgs... seriously why is it just more fetish art for borgs with spriters nowadays?
I'm here for the dystopian corporate nightmarish deathtrap in space, **NOT** your deviantart page.

Mining borg can stay though. He looks chill.

**Comment by SomeoneYouProbablyKnow** [comment]
Sprites are neat but.
a) i don't like humanoid borgs as an idea in general. They are very specifically not human in function and gameloop and should have non human shapes.
You can tell those are borgs here in the picture but it's gonna be much harder in an actual round with stuff happening

b) Maybe i'm too used to regular borgs but these are worse at expressing what job the borg is for. Partly i blame the hands but also the colors are less uniform compared to old borgs

c) They have hands (or well, something that looks like hands), borgs don't have hands. Visual confusion.

**Comment by arnociiroc** [comment]
janitor ultrakill

**Comment by SansSarif** [comment]
> 

just to confirm, the sprite maintainers would rather things go from neutral to darkest instead of highlights to shadow? or is it more generally "needs more shadow in total." also, is there specific things you're feeling are too busy, or is it a more general thing. more specific requests is better/will help with a shorter turnaround & less revisions and would be appreciated.

**Comment by VladinXXV** [comment]
i like this one he looks cool
image


please no balan wonder world borg

**Comment by MrDoomBringer** [comment]
i thought this was bait

**Comment by Time-Green** [comment]
I am very strongly against humanoids borgs altogheter. Humans are humans and borgs are borgs. Once we start making humanoid borg sprites we compromise on what borgs are

**Comment by Dorsisdwarf** [comment]
Quite aside from this PR bringing the serviceborg silhouette issue to every borg frame and the thick-thighs sprites, isn't the green one on the right straight up a deltarune character?

**Comment by Mothblocks** [comment]
yes

**Comment by Dorsisdwarf** [comment]
the medical borg on orb however is excellent

**Comment by dragomagol** [comment]
Make borgs look like robots instead of humans I beg

**Comment by epochayur** [comment]
this makes me sad

**Comment by Jackal-boop** [comment]
I like the janitor because it looks like v1 merge pls

**Comment by DATA-xPUNGED** [comment]
Hudbot and Mixer just seem horny, if i'm completely honest. and Stereo is just a deltarune character
With that said, i actually do quite like the other designs quite a bit, the Ringleader is so FUCKING cool

**Comment by chemistrymain2** [comment]
keep the mediborg orb

**Comment by thgvr** [comment]
orb borg is a winner design to be honest

**Comment by Imaginos16** [comment]
> orb borg is a winner design to be honest

On that note, Onule made a rendition I actually enjoyed.

image
image

If that rendition of the orb borg was done, I'd be fine with it being added.

**Comment by SomeoneYouProbablyKnow** [comment]
c'mon, if any design is the winner it's the mining lad

**Comment by Imaginos16** [comment]
> > 
> 
> just to confirm, the sprite maintainers would rather things go from neutral to darkest instead of highlights to shadow? or is it more generally "needs more shadow in total." also, is there specific things you're feeling are too busy, or is it a more general thing. more specific requests is better/will help with a shorter turnaround & less revisions and would be appreciated.

See my most recent post. Generally it should include more contrast, and keep the shading consistent.

As an example, **this is severely inconsistent**
image

**Comment by SomeoneYouProbablyKnow** [comment]
I feel like It's inconsistent here because they took the pallets and styles directly from the existing borg sprites

**Comment by CuteTuret** [comment]
If this ends up getting shot down, can we please keep the mining sprite, and the engineer that looks like a Zaku?

**Comment by LSommers** [comment]
The Zaku, MedOrb, Papa Miner, and MAYBE the unholy Janicart Centaur Nightmare Borg are the only ones that don't cross the line between "reasonable borg design" and "did I accidentally enter the wrong SS13 Git?".

Zaku engieborg could lose the blue striping too, make that shit construction reflector yellow.
Janitaur Sleep Paralysis Demon Borg could use some more consistent shading.
Papa Miner's outline needs to be more in line with current TG borgs.
MedOrb looks _okay_ I guess.
Both of the anime girl borgs are right out.

**Comment by LemonInTheDark** [comment]
vibes weird

**Comment by pilotmans** [comment]
what the hell get this goofy ah hentai sprites out of this serva

goofy ahh non death trap segs bots


No but seriously these do not fit with the tg style of "getting your skull bashed inward by a scientist after freezing a slime that was about to kill the unrobust captain."

**Comment by pilotmans** [comment]
> > Borgs should clearly parse as belonging to the department/job that they are intended to fill (either through color coding, silhouette similarities, or design choices)
> 
> I have no idea what any of these are
> 
> image

The red anime borg looks like a anime showman though honestly a spider showman borg would just be better for the shenigans that would arise out of a service borg giving the clown crack or something

Also why the fuck does the mining borg have **bust** to it?

**Comment by CuteTuret** [comment]
> > > Borgs should clearly parse as belonging to the department/job that they are intended to fill (either through color coding, silhouette similarities, or design choices)
> > 
> > 
> > I have no idea what any of these are
> > image
> 
> The red anime borg looks like a anime showman though honestly a spider showman borg would just be better for the shenigans that would arise out of a service borg giving the clown crack or something
> 
> Also why the fuck does the mining borg have **bust** to it?

I fail to see the bust. What I see is the purple part with the orb is the front, and the brown part a backpack.

**Comment by pilotmans** [comment]
none of these busto trons 9000s should be added really it just really does not sit well with me

**Comment by pilotmans** [comment]
> > > > Borgs should clearly parse as belonging to the department/job that they are intended to fill (either through color coding, silhouette similarities, or design choices)
> > > 
> > > 
> > > I have no idea what any of these are
> > > image
> > 
> > 
> > The red anime borg looks like a anime showman though honestly a spider showman borg would just be better for the shenigans that would arise out of a service borg giving the clown crack or something
> > Also why the fuck does the mining borg have **bust** to it?
> 
> I fail to see the bust. What I see is the purple part with the orb is the front, and the brown part a backpack.

oh shit i mean the orange one, look at the third image to the right 💀

**Comment by Jezzared** [comment]
I assume the mining borg is Big Daddy inspired.

![https://cdnb.artstation.com/p/assets/images/images/052/406/233/large/lewis-deane-bid-daddy.jpg?1659702312]

**Comment by CuteTuret** [comment]
> > > > > Borgs should clearly parse as belonging to the department/job that they are intended to fill (either through color coding, silhouette similarities, or design choices)
> > > > 
> > > > 
> > > > I have no idea what any of these are
> > > > image
> > > 
> > > 
> > > The red anime borg looks like a anime showman though honestly a spider showman borg would just be better for the shenigans that would arise out of a service borg giving the clown crack or something
> > > Also why the fuck does the mining borg have **bust** to it?
> > 
> > 
> > I fail to see the bust. What I see is the purple part with the orb is the front, and the brown part a backpack.
> 
> oh shit i mean the orange one, look at the third image to the right 💀

I'm still not sure, like the peacekeeper has a very obvious bust to it. The engineer one honestly looks more like armor to me than a bust.

**Comment by pilotmans** [comment]
all in all, busty robots are not allowed unless spawned in by an admin

**Comment by pilotmans** [comment]
Why would engineer need armor is the question? is this an assaultron from fallout 4 type shenigans where the actual reasoning for the bust for the PEACE KEEPER of all things is space for machinery inside?

**Comment by Pickle-Coding** [comment]
I disagree with the concept of humanoid cyborgs. Cyborgs were designed to follow their laws, with modules that allow them to specialise in a specific task efficiently. Humanoid modules do not make sense, as they are not crew, but a tool.

**Comment by CuteTuret** [comment]
> Why would engineer need armor is the question? is this an assaultron from fallout 4 type shenigans where the actual reasoning for the bust for the PEACE KEEPER of all things is space for machinery inside?

I can see the engineer and mining borgs needing extra armor tbh. Both operate in hostile environments of extreme heat, cold, or generally having things hit/fall on top of them.

I actually really like the engineer sprite proposed here, since it has a very industrial look to it.

If it failed, I'd still like to see at least a construction mech with this design.

**Comment by pilotmans** [comment]
> > Why would engineer need armor is the question? is this an assaultron from fallout 4 type shenigans where the actual reasoning for the bust for the PEACE KEEPER of all things is space for machinery inside?
> 
> I can see the engineer and mining borgs needing extra armor tbh. Both operate in hostile environments of extreme heat, cold, or generally having things hit/fall on top of them.
> 
> I actually really like the engineer sprite proposed here, since it has a very industrial look to it.
> 
> If it failed, I'd still like to see at least a construction mech with this design.

industrial? it looks smooth af it looks more like a samus suit than an industrial engineering repair robot

**Comment by pilotmans** [comment]
> I disagree with the concept of humanoid cyborgs. Cyborgs were designed to follow their laws, with modules that allow them to specialise in a specific task efficiently. Humanoid modules do not make sense, as they are not crew, but a tool.

I mean you really don't get the "horrors of modern engineering" vibe from these new designs, these feel more like goon station borgs than the "slaves" that they actually are here.

**Comment by IndieanaJones** [comment]
Ewww

**Comment by Twaticus** [comment]
im not interested in borg reskins at the moment

**Comment by Mechar418** [comment]
This is horrible

**Pull request closed without merging**
