### PR TITLE
Fixconfvic_numero_deux

### PR DESCRIPTION
**Pull request by vicirdek**

### CODE REVIEW

**Comment by vicirdek** [comment]
sorry lol.

**Comment by vicirdek** [comment]
Since i already accidently pinged all of you, nice to meet you people.

**Comment by Mothblocks** [comment]
this title is how i type to my gay frirends

**Comment by vicirdek** [comment]
That's why i titled it like this

**Comment by LemonInTheDark** [comment]
hello friend

**Pull request closed without merging**
