### PR TITLE
New wanted poster sprite

### PR DESCRIPTION
**Pull request by lzimann**
Sprite by Lexorion, just making the pr for him.

old and new
borkopc

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Please show old for comparison.

**Comment by lzimann** [comment]
@MrStonedOne done.

**Comment by WJohn** [comment]
Big improvement. :+1:

**Comment by yackemflam** [comment]
Tbh, I like the old one better due to that it fits in a space station better.
Tho I do like the new one. I just think it doesn't fit.

**Comment by Lexorion** [comment]
Just look at the old "wanted",fitting or not,it wasn't very pleasant to look at

**Comment by WJohn** [comment]
Pretty much anything is an improvement, even if it's not a smooth piece of latex-paper or whatever it is we use for our posters.

**Pull request merged**
