### PR TITLE
removes unused gas mixture code

### PR DESCRIPTION
**Pull request by duncathan**
I think I made this branch on upstream haha woops fuck github website

this removes a bunch of unused code from gas_mixture.dm
hopefully this can make this monstrosity easier to read/understand

### CODE REVIEW

**Comment by as334** [comment]
:+1:

**Comment by RemieRichards** [comment]
Maintainers are allowed to make branches on upstream, so long as we obey the rest of the rules @duncathan 

also :+1:

**Comment by as334** [comment]
Apparently those are still getting called somewhere, see travis.

**Comment by duncathan** [comment]
Yeah I figured I'd miss one or two calls, will fix

**Comment by Aranclanos** [comment]
>unused code
>removes share()
>Well played!

**Comment by duncathan** [comment]
@Aranclanos
The entirety of this PR has been done on github website
Evidently its search function is lackluster lol; I'll be putting share() back later today

**Comment by Razharas** [comment]
First step in getting new gas mixture code

**Comment by duncathan** [comment]
>251 lines removed

Very slowly, I work towards better gas mixture

**Pull request merged**
