### PR TITLE
Mining Voucher Kit Changes

### PR DESCRIPTION
**Pull request by Arianya**
:cl: Arianya
del: The Survival Capsule & Webbing Kit is dead.
balance: Advanced Scanners have been removed from all kits
balance: Webbing has been removed from the resonator kit
/:cl:

Closes #38153 

**Why:** There's been some noticeable powercreep on the kits, and it's become an issue as cobby evidenced in their PR.

Their PR was almost perfect, but it broke one of the kits and they seemed intractable to seeing why that was an issue, hence this PR.

I've removed the Survival Capsule & Webbing kit as it wasn't really worthwhile in it's own right, survival capsules are available in free supply anyway and webbing on it's own isn't worth having while the crusher kit requires it to function.

Happy to field suggestions for alternative kits to add to replace the removed one, but please bear in mind that one that includes the advanced mining scanner is extremely unlikely.

### CODE REVIEW

**Comment by Bluespace** [comment]
Can we not have a kit that's JUST the adv scanner?

**Comment by Arianya** [comment]
As Kor mentioned in #38123, having goods that are too valuable in their own right in the voucher selection just devalues people actually wanting points to get gear from the mining vendor, and I'll confess as a miner myself I use to pick the resonator kit just for the scanner.

I suspect there's a decent argument to remove the basic scanner entirely and replace it with the advanced scanner (or atleast do so for station miners), but that's OOS for this PR.

**Comment by Repukan** [comment]
There's no argument for removing the basic scanner since the basic scanner is shitty enough you are compelled to actually mine to get the upgrade.

This ensures a bare minimum of minerals you can get if they don't go just monster hunting.

**Comment by ExcessiveUseOfCobblestone** [comment]
> it's meant to be cumbersome to where it takes your backpack slot but it just HAS to come with a free backpack-on-belt item roundstart

bad

**Comment by Arianya** [comment]
@ExcessiveUseOfCobblestone I'm not arguing with you over it, just giving maintainers the option of which one to merge =)

**Comment by ExcessiveUseOfCobblestone** [comment]
Also it's pretty rude to make a competing PR when a maintainer can just tell me to change mine.

**Comment by Arianya** [comment]
It's not a competition Cobby.

**Comment by chesse20** [comment]
no support mining is fine as is

**Comment by SgtxRootbeer** [comment]
>ExcessiveUseOfCobblestone:  I am not changing it unless a maintainer says to.
>ExcessiveUseOfCobblestone: it's pretty rude to make a competing PR.

You've just shown that you don't wanna change it unless a maintainer strong-arms you into changing it, knowing full well that for most maintainers, anything more than pressing the merge button is beyond their capabilities.

**Comment by optimumtact** [comment]
Turns out we can hide comments too

**Comment by SgtxRootbeer** [comment]
>oranges being a twat

I should have seen it coming

**Comment by BeeSting12** [comment]
fuck off i like the capsule kit

**Comment by Hatfish** [comment]
This PR is better than @ExcessiveUseOfCobblestone 's PR

**Comment by Cyprex** [comment]
@Arianya It absolutely is either this or cobbys PR.
Personally I agree with this one.

**Comment by Magikarpet** [comment]
As someone who always gets the webbing kit, I really don't get all the hatred towards it. It has a simple purpose which people underestimate, storage. Being able to store more plates/ores/meds in your webbing is nice and does actually make it "powerful" and gives it a niche, but with storage. 

Something not being taken every round isn't a sign of bad design or uselessness, look at the conscription and fulton kits. They have a purpose and they do it really well but they aren't an ultra common pickup.

**Comment by Shadowflame909** [comment]
Wait, why did you give it a thumbs down then @Magikarpet. If you agree with this PR trying to save the webbing + crusher from being eviscerated from existence. Effectively ruining the crusher voucher!

**Comment by Borisvanmemes** [comment]
Maybe a bad idea but, what if you merged the Extraction and Rescue Kit and the Capsule and Webbing kit into one?

**Comment by Arianya** [comment]
@Magikarpet My proposed removal of the Survival Capsule & Webbing kit wasn't because of lack of usage, but rather because having two kits which feature the same item seemed pointless. Is there any reason you'd rather pick up the Survival Capsule & Webbing Kit over picking up a Crusher kit and just leaving the Crusher (this isn't ideal, either, but I don't want to open a full rework of kits/mining roundstart gear just yet)?

**Comment by Arianya** [comment]
@zaracka I can't see any good reason to keep it on the resonator kit. The resonator isn't bulky enough to replace your backpack, and notably didn't even have it in its kit as of November last year (I know this because I had to update my fork and noticed the old kits there)

I agree the resonator as a mining tool is in a weird shitty spot, but I don't think inflating it's kit with addons is going to fix that, just lead to people buying the kit for everything *except* the resonator

**Comment by zaracka** [comment]
It used to be the only kit with advanced mining scanners. My reasoning is mostly consistency and so the kit doesn't feel empty. If the webbing kit and resonator kit aren't used that much, merge them.

The resonator itself is probably the best starting mining tool species that can't use guns can get. The kit doesn't need to be called "Resonator Kit." It can be the "Explorer's Webbing Kit," except it comes with a resonator too. Or call it the "Resonator and Explorer's Webbing kit."

**Comment by lolman360** [comment]
The complete removal of advanced scanners is dent on the ability for miners to get minerals roundstart, which impacts RnD's ability to upgrade machines and Robotic's ability to upgrade borgs, et cetera, since there's so much interdepartmental co-operation between Mining/Cargo and Science. Possibly add a kit that's focused on the scanner/mining overall?

**Comment by Repukan** [comment]
Read the rest of the comments and discussion instead of only the title please

**Comment by Repukan** [comment]
Or the ones in the original pr which explains thoroughly why the scanner being in kits is bad

**Comment by ExcessiveUseOfCobblestone** [comment]
This is why having multiple prs that cover the same topic with minute differences will forever be dumb because it does nothing but scratches the record so everyone (particularly maintainers) have to sift through the same comments twice.

**Comment by Arianya** [comment]
Cobby if you want to have a debate on the merits of alternative PRs id suggest taking it up on the forums.

**Pull request closed without merging**
