### PR TITLE
Tweaks and fixes for the appearance window

### PR DESCRIPTION
**Pull request by Incoming5643**
Fixes an unreported bug where all the lizardpeople were horrifying on the character preview because it wasn't rendering their tails and noses. Incidentally the proc for character previews is horrifying.

Only relevant appearance settings will appear on the appearance screen for each race.

Moves the skin tones selector to the relevant appearance settings area for humans.

---

If your high setting is a silicon, you'll see that silicon in the preview window

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
The appearance window gives you job-based equipment based on your HIGH preference job, right?

**Comment by Cheridan** [comment]
Yeah.

**Comment by Dorsisdwarf** [comment]
Can you make it show you as an AI/borg if that's what your high pref is, instead of assistant/nekkid?

**Comment by Incoming5643** [comment]
Probably doable

**Comment by Incoming5643** [comment]
Boom, done

**Pull request merged**
