### PR TITLE
Adds swimsuits to clothesmate, holodeck, & beaches

### PR DESCRIPTION
**Pull request by ShizCalev**
Also corrects the charge number for the clothesmate refill.

Closes #38347
Closes #38372

### CODE REVIEW

**Comment by KorPhaeron** [comment]
I don't think it makes any sense to put these in lockers on a station with nowhere to swim

Maybe in the beach bum ruin

**Comment by Thunder12345** [comment]
Holodeck beach

**Comment by GuyonBroadway** [comment]
I thought these were only being added for that silly summer ball event.

**Comment by ExcessiveUseOfCobblestone** [comment]
Please have these as underwear a la @Armhulen said in 38347

**Comment by CitrusGender** [comment]
based maintainer

**Comment by Iamgoofball** [comment]
How does this improve the gameplay experience?

**Comment by ShizCalev** [comment]
How does adding swimsuits to the lockers at beaches (where the only currently available clothing is trunks) improve the gameplay experience?

Is that a serious question?

**Pull request closed without merging**
