### PR TITLE
Slime People love toxic (to others) food!

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
fix: Slimepeople have found a love for sugary and/or toxic dishes. Blorble!
/:cl:

Fixes https://tgstation13.org/phpBB/viewtopic.php?f=9&t=16079&p=389105&sid=7c3168de3664e31e92dc54e57bf686d7#p389105

### CODE REVIEW

**Comment by Repukan** [comment]
Is it really something to be fixed, though?

Just because it has toxins in it doesn't mean they'll like it.

**Comment by ExcessiveUseOfCobblestone** [comment]
Toxic food wise just means things like sushi and spider legs even though it doesn't have toxins that would heal the individual.

Slimes can feed directly off spiders so I don't see an issue nor do I particularly care enough to argue about the culinary preferences of a made up race.

**Comment by Repukan** [comment]
They can feed off podpeople too and it doesn't make them able to eat fruits.

Afaik from what you can see ingame, the cloneloss is the slimes feeding of enzymes they absorb through skin contact, not the literal flesh consumption

**Comment by ExcessiveUseOfCobblestone** [comment]
What's the end goal here arguing whether or not slimepeople should be able to eat sushi and spider legs?

**Comment by Qustinnus** [comment]
this pr doesnt even fix anything..?

**Pull request closed without merging**
