### PR TITLE
Lava is no longer a plating subtype

### LINKED ISSUE #26825: Walls can be used to build over lava
Pushing a displaced girder over lava, wrenching it in place, and then finishing the wall seems to delete the lava below.  This allows someone to build a wall over the lava by building and then dismantling walls across it.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #26825

### CODE REVIEW

**Comment by ChangelingRain** [comment]
@ShizCalev please replace all these baseturf edits with the baseturf helper please I beg you

**Comment by ShizCalev** [comment]
Is the `/turf/open/floor/plating/asteroid/basalt/lava_land_surface` baseturf intentional in certain areas on maps like clown planet & animal hospital? If so, I'll do it eventually in another PR since I'd have to cherrypick the shit out of everything and make new sub-areas.

**Comment by ChangelingRain** [comment]
It's probably an accident, since everything is supposed to be lava.

**Comment by ma44** [comment]
You should see if this also works against using a RCD or carpet chem grenade, as those are two other methods for removing lava

**Comment by ChangelingRain** [comment]
It does prevent RCDs but I don't know about carpet.

**Comment by Kromgar** [comment]
Im pretty sure using an rcd to cross lava became a feature according to Kor... @korphaeron

**Comment by Kromgar** [comment]
Ashwalkers are fucked if they spaen on a island and cant cross lava. Hell golems too really

**Comment by KorPhaeron** [comment]
RCD should still work

**Comment by ChangelingRain** [comment]
RCD is now allowed, but it works like space and builds a floor instead of a wall.

**Pull request merged**
