### PR TITLE
Updates caves.dm to use the new basalt asteroid flooring

### PR DESCRIPTION
**Pull request by MMMiracles**
also removes the plating variant as it has literally no reason to exist now.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Remember to change your walls to there will be basalt under them when they break.

**Comment by MMMiracles** [comment]
I already did that.

**Comment by KorPhaeron** [comment]
Nevermind me then

**Comment by Anonus** [comment]
Did you update the lava to be the smooth lava, too? The smooth lava will look really nice with the basalt flooring.

**Comment by MMMiracles** [comment]
i dont know how i managed to miss that one instance in notepad but w/e.

**Comment by Razharas** [comment]
Is this done?

**Comment by Razharas** [comment]
Looks done to me

**Pull request merged**
