### PR TITLE
Revert "Revert "SWAT vest !!!DOES NOT BUFF SWAT!!!""

### PR DESCRIPTION
**Pull request by Bawhoppen**
Reverts tgstation/tgstation#25620

DID NOT WAIT 24HOURS AND VIOLATED FREEZE

### CODE REVIEW

**Comment by Cheridan** [comment]
sorry baw this is a feature freaze

**Comment by Bawhoppen** [comment]
atleast just say you closed it because you disagreed dont give a bullshit reason

**Comment by Wyzack** [comment]
How is a feature freeze not a legitimate reason? No one is exempt

**Comment by Aloraydrel** [comment]
I want kor to apologize RIGHT NOW

**Comment by Bawhoppen** [comment]
@wyzack the other revert pr was speedmerged instead of closed so why should mine be closed?

**Comment by jughu** [comment]
>oranges auctally reverting a swat armour nerf and calling it a buff

**Pull request closed without merging**
