### PR TITLE
[MANUAL MIRROR] airlock fix from 77736

### PR DESCRIPTION
**Pull request by CliffracerX**
I DID IT AGAIN

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
lmao

**Comment by MrMelbert** [comment]
lmao

**Comment by optimumtact** [comment]
he did it again

**Comment by CliffracerX** [comment]
I don't even have late at night to blame this time, I'm just blinder than a bat and realized my mistake as the page reloaded.

I'm cutting the fork off the TG network before I nuke you guys *again.*  I'm so sorry.

**Pull request closed without merging**
