### PR TITLE
Charlie Station Redesign/Rework

### PR DESCRIPTION
**Pull request by redmoogle**
### About The Pull Request

**Charlie/Beta/Delta(slightly) have been redesigned:**
- Adding a mining area in Beta Hallway(has void jetpack)
- Adding walls to Beta Station
- Removing rust from 90% of the station
- Making the messes a little more varied
- Moving apcs
- Adding lockers
- Threat changed to xenos
- More people(1 more engi, and sci)
- Adding 2 pair of insulated gloves
- Moving all of the solar panels into 3 crates
- Moved the cleaner and lights to the spawn room
- Moved Sleeper into the Medical Crate(Now in medbay) along with moving defib closer
- A few more meteors added
- New Player Friendly

### OLD

image

### NEW
**There is resin floors but mapdiff doesn't pick up on it**

image

### Why It's Good For The Game

Charlie has too many hviebots in general to be worth playing so I god rid of some and while I was at it I cleaned the station design up alot to make the events around it to make more sense

### Changelog:

🆑 
tweak: Redesigned Charlie Station
 /🆑

### CODE REVIEW

**Comment by ernestget8thumb** [comment]
cool

**Comment by wesoda25** [comment]
God bless for removing the rusty walls

**Comment by redmoogle** [comment]
image

thank you travis very cool

**Comment by nemvar** [comment]
There are some nice (and not so nice) hivebot sprites hidden across ALL the dmis. You could add some of them for decor on the hivebot ship. Just an idea.
hivebot

**Comment by redmoogle** [comment]
> 
> 
> There are some nice (and not so nice) hivebot sprites hidden across ALL the dmis. You could add some of them for decor on the hivebot ship. Just an idea.
> hivebot

I'm scared to push another commit because of the bots being dumb

**Comment by SpaceManiac** [comment]
thank you for taking the hit, I've been trying to debug this particular travis issue

**Comment by Repukan** [comment]
It's supposed to be infested with hivebots.

Hence the whole reclamation process

**Comment by nemvar** [comment]
Well it still is. It's also supposed to be a tutorial of a sort for new players and tbh it's a bit too hard for that.

**Comment by Repukan** [comment]
The fuck? Lmao

At most is a callback to OS13

It will teach players not to blindly rush in and take out mobs little by little

**Comment by redmoogle** [comment]
> 
> 
> The fuck? Lmao
> 
> At most is a callback to OS13
> 
> It will teach players not to blindly rush in and take out mobs little by little

they're more annoying as hell than anything they're too weak to be a threat

**Comment by Repukan** [comment]
They're too weak to be a threat so there's no issue leaving them in, then

**Comment by redmoogle** [comment]
> 
> 
> They're too weak to be a threat so there's no issue leaving them in, then

except when you have 40 and it takes 30 minutes to clear

**Comment by TheChosenEvilOne** [comment]
> 
> 
> > They're too weak to be a threat so there's no issue leaving them in, then
> 
> except when you have 40 and it takes 30 minutes to clear

You actually just need a single spear and you can really quickly get rid of them all. Five to ten minutes and you got most of them killed in the science area.

**Comment by redmoogle** [comment]
> 
> 
> > > They're too weak to be a threat so there's no issue leaving them in, then
> > 
> > 
> > except when you have 40 and it takes 30 minutes to clear
> 
> You actually just need a single spear and you can really quickly get rid of them all. Five to ten minutes and you got most of them killed in the science area.

then it feels god awfully lame I want to design another part thats combat focused

**Comment by shellspeed1** [comment]
Good PR, I would consider looking at the experimental cloner ruin and make it look like it broke off of charlie station.

**Comment by TerraGS** [comment]
Nitpicking that the left bit no longer has pipes leading from atmos to the rest of the station.

**Comment by redmoogle** [comment]
It's supposed to be repair

**Comment by redmoogle** [comment]
Which would you all prefer xenos or hivebots

**Comment by Jimmius** [comment]
the hivebots are what made me stop rolling charlie, it used to be something i did every round instead of playing the main station, but setting aside half an hour to click on hivebots before you can do anything interesting is boring as piss

**Comment by wesoda25** [comment]
Don’t do xenos thats way fucking worse.

**Comment by redmoogle** [comment]
there's no live eggs

**Comment by shellspeed1** [comment]
I would maintain hivebots

**Comment by redmoogle** [comment]
> 
> 
> I would maintain hivebots

the way their designed would most likely ruin their balance of super-cheap to make(free @ 1 a second) and strongs being non-reporducable

**Review by actioninja — CHANGES_REQUESTED** [review]
don't use gas miners

**Comment by redmoogle** [comment]
done

**Comment by actioninja** [comment]
I'm not 100% on expanding the ruin size and giving them more equipment but the benomorphs and other mapping improvements are a really great change imo, the hivebots were awful.

**Comment by redmoogle** [comment]
@actioninja I mean aside from only 1 guy who abandoned it, it seems fine and looks like higher than average use

**Pull request merged**
