### PR TITLE
The NTSS Independence: Reimagined

### PR DESCRIPTION
**Pull request by norsvenska**
## About The Pull Request

Completely overhauls the NTSS Independence, or the cruise evac shuttle, into something more modern.

## Why It's Good For The Game

The NTSS Independence is one of the most expensive shuttles in the game. It's supposed to be luxurious, but all that it comes with is a bar and a couple big sitting rooms. This PR aims to make the shuttle more worth its value.

<details>
<summary>Full Shuttle, Ingame</summary>

Screenshot 2023-12-03 142810

</details>

It's the same size as the old cruise shuttle, and I tried to keep the exterior door placement the same.

<details>
<summary>Bar</summary>

Screenshot 2023-12-03 142932

</details>

The first place you'll walk into, assuming you enter from the departures lounge, is the bar/restaurant area. Like the original cruise, I added both the bar drone and the xenomorph barmaid. The syndicate balloon was there on accident; it has since been removed.

<details>
<summary>Dancefloor & Primary Hallway</summary>

Screenshot 2023-12-03 143148

</details>

This central area is just down the stairs from the bar. There are two (2) vibebots, which is pretty cool.

<details>
<summary>Infirmary</summary>

Screenshot 2023-12-03 143119

</details>

Infirmary is pretty straightforward. It's very small. I almost didn't add it, but decided to do so anyway due to not knowing what else to put there. Also, I think it looks nice.

<details>
<summary>Kitchen</summary>

Screenshot 2023-12-03 142853

</details>

The kitchen is across from the infirmary. There's a window that opens out to the bar, and it comes equipped with all the cooking devices one would need.

<details>
<summary>Aft Utility Rooms</summary>

Screenshot 2023-12-03 143350
Screenshot 2023-12-03 143306

</details>

At the stern of the ship, there are 2 rooms. Portside has a cargo hold. Starboard has a laundry room (and a disposal unit). Between them is the engineering lift. As we do not yet have multi-z shuttles, this lift is inoperable, so I left a note there.

<details>
<summary>Corporate Lounge</summary>

Screenshot 2023-12-03 143227

</details>

The corporate lounge is a small room towards the stern, where those with command access can hang out.

<details>
<summary>Bridge & Cap Office</summary>

Screenshot 2023-12-03 143032

</details>

The bridge and the captain's office are at the fore starboard corner of the ship. While the bridge doesn't have much notable to it, the captain's office has a box full of toys.

<details>
<summary>Laser Tag</summary>

Screenshot 2023-12-03 143545

</details>

And finally, there's the space laser tag arena. It's out of order (uh oh) but still has all the equipment. I decided to add this on because there was a lot of empty space left after designing the shape of the ship. I had wanted to make a transit tube "rollercoaster" that's supposed to go around the whole shuttle, but is broken and spits people out at the stern, but I decided that would be too cruel (totally not because there wasn't enough room outside the shuttle) and settled on a laser tag area instead.

<details>
<summary>Full Shuttle, SDMM</summary>

Screenshot 2023-12-03 143849

</details>

And here is a screenshot of it in StrongDMM. Yes, I kept Hides-on-Shuttle.
## Changelog

:cl:
add: The NTSS Independence (Cruise Evac Shuttle) has received a makeover! Engineering crews are still working on it, but it is operable and available for those who have the money to rent it.
/:cl:

### CODE REVIEW

**Comment by AdipemDragon** [comment]
I'm not even starting to fully get into how much I like the shuttle, but I'll just say right off. Please swap the bardrone and barmaid's locations (or something equivalent). I've had too many occasions where I was the sole person signing up for the NTSS's crew, and, because the sentie- uhh syndicate balloon is closer to the maid than the drone, I was put in The First Option, and thus, I was stuck with a bunch of people wanting drinks as a maid with cleaners for hands.

Otherwise fantastic ship i Will keep staring

**Comment by timothymtorres** [comment]
Maybe add a cryopod to medbay since it's supposed to be luxurious.  You will need room for a thermomachine and O2 canister though so it might be a tight squeeze!

**Comment by norsvenska** [comment]
ok after looking at it again i realized that it wouldnt work so here it is now
image

**Comment by BlueMemesauce** [comment]
That's not a syndicate balloon, it's a sentience balloon. `/obj/effect/fun_balloon/sentience/emergency_shuttle`
it's supposed to be there to give the drone and xeno sentience.

**Comment by AdipemDragon** [comment]
> That's not a syndicate balloon, it's a sentience balloon.

we been knew, king, I even made fun of it in my comment, "it has since been removed" is what people boarding the ship will see

**Comment by norsvenska** [comment]
> For a shuttle this big it sure does seem to not have many places to sit. 

I suppose I can add more benches and whatnot later tonight.

> Also, does this not have a sec place for prisoners?

This was done deliberately. The original NTSS Independence did not have a brig. I suppose I could turn the portside lounge into one, but I'm hesitant.

**Pull request merged**
