### PR TITLE
Black powder now makes plasmamen druggy

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR makes black powder set the drugginess of plasmamen to 15 (the same value that space drugs set it to) every tick that it's (being processed) in their system. It also caps how high black powder can bring a plasmaman's hallucination value to somewhere around [volume+5] (it won't lower their hallucination value if it's already above volume+5), in a similar way to how the space drugs OD does it.

## Why It's Good For The Game

Hey, black powder already makes plasmamen hallucinate, so why not have it make them feel druggy/high (unfortunately, being druggy on its own doesn't appear to give you a moodlet, which is a bit sad, but changing that will be something for a future PR)?

## Changelog
:cl: ATHATH (the code for this change was written by ExcessiveUseOfCobblestone)
balance: Black powder now makes plasmamen feel druggy.
balance: The value that black powder can increase a plasmaman's hallucination value to has been capped to somewhere near [volume+5].
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Only thing I could say is try to avoid nesting,  and use early returns. It's only 1 layer deep so it's not like it's an issue but it's good to keep in mind. Code is fine though.

**Review by ExcessiveUseOfCobblestone — COMMENTED** [review]
```DM
. = TRUE
..()
if(!isplasmaman(M))
    return
M.set_drugginess(15)
if(M.hallucination < volume)
    M.hallucination += 5
```

**Comment by ATH1909** [comment]
> ```dm
> . = TRUE
> ..()
> if(!isplasmaman(M))
>     return
> M.set_drugginess(15)
> if(M.hallucination < volume)
>     M.hallucination += 5
> ```

@ExcessiveUseOfCobblestone I replaced my code with yours and credited you in this PR's changelog.

**Comment by ExcessiveUseOfCobblestone** [comment]
i do it for free man

**Comment by ExcessiveUseOfCobblestone** [comment]
how did you break the indentation lol

**Comment by ATH1909** [comment]
@ExcessiveUseOfCobblestone this should be fixed now, I think

**Pull request merged**
