### PR TITLE
Changelings can't transform people into species they cannot absorb

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

This PR makes a change to the Transform Sting ability to prevent you from turning people into species that have unabsorbable DNA.
Now you may ask "Jacquerel, how do you even have a DNA profile of a species with unabsorbable DNA in the first place?"
The answer is that we do not do any species checks when assigning roundstart antagonists, or when admins try to make someone into a Changeling.

The upshot of this is that while you can't copy the DNA of a plasmaman and then wander around turning random people into plasmamen (instantly setting them on fire and suffocating them), you can **start** the round as a Plasmaman, apply _your own_ DNA to people, and have them experience those consequences.

We _could_ change this so that people queueing as Plasmaman who also are assigned to be Changelings use their forced human profile... but I think that's more boring than this solution (and might lead to very slightly more metagaming).
This way _also_ adds a little bit of protection for the cases of admins giving the changeling antag datum to Golems, Monkeys, Skeletons, Androids, or the like.

Just in case admins _want_ to turn people into burning skeletons with transform sting, I have added a variable on the ability which you can toggle to disable the check.

## Changelog

:cl:
balance: If you can't absorb a species' DNA as a changeling, you also can't use transform sting to turn someone into that species.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
> PTSD from that one plasmaman ling round I see. This change makes sense to add though.

People have said this about a few PRs I have made recently, forgetting that I do not play the game

**Comment by TheNobodyofimportance** [comment]
Jac we had that round yesterday. we had a plasmeme ling who dna stung everyone, technetium I think. You should've seen medbay lmaooooo. 
It's a change I guess? The stars have to align for this situation to happen, but I have seen the effects first hand. Good on you for including a toggle for admins to use.

**Comment by GPeckman** [comment]
> We could change this so that people queueing as Plasmaman who also are assigned to be Changelings use their forced human profile... but I think that's more boring than this solution (and might lead to very slightly more metagaming).
This way also adds a little bit of protection for the cases of admins giving the changeling antag datum to Golems, Monkeys, Skeletons, Androids, or the like.

Honestly, this solution would fix other issues too. Plasmamen changelings can't actually be absorbed by other changelings since lings can't absorb non-organics. I also don't really see how it's metagaming; by that logic, knowing that heads of staff can't be revolutionaries would also be metagaming.

**Comment by TheNobodyofimportance** [comment]
> > We could change this so that people queueing as Plasmaman who also are assigned to be Changelings use their forced human profile... but I think that's more boring than this solution (and might lead to very slightly more metagaming).
> 
> This way also adds a little bit of protection for the cases of admins giving the changeling antag datum to Golems, Monkeys, Skeletons, Androids, or the like.
> 
> 
> 
> Honestly, this solution would fix other issues too. Plasmamen changelings can't actually be absorbed by other changelings since lings can't absorb non-organics. I also don't really see how it's metagaming; by that logic, knowing that heads of staff can't be revolutionaries would also be metagaming.

I'd say it's the same kind of metagaming as seeing a sec main (lucia valdez kek) playing a non-sec role to a lesser degree. Like if you see a plasmeme static suddenly switch off that'd raise some meta-level suspicion. Though I'd doubt many would have a keen eye to notice that, and less would act on it since it's specific to a single antag.

**Pull request merged**
