### PR TITLE
Tesla no longer NOTHING PERSONNEL's the power beacon

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
tweak: The tesla will now move toward power beacons at a significantly slower rate. 
/:cl:

Also the announcement got a grammar fix and will occur slightly more frequently.

Currently the SM spawns teslas with 30+ balls, which means turning on a beacon will bring the Tesla to your position within seconds. I don't know why I keep messing with tesla and beacon code...

### CODE REVIEW

**Comment by kevinz000** [comment]
Lmao ic issue run fastwr

**Comment by PKPenguin321** [comment]
🏂

**Comment by Ratvar** [comment]
There is already thingie you buy from uplink to suck tesla/singullo in, no? And here you see the same thing, but with utility.

**Comment by Robustin** [comment]
It IS that thing dude.

**Comment by Ratvar** [comment]
Oh, i am dumb as hell

**Comment by ExcessiveUseOfCobblestone** [comment]
If you sabotage, sabotage correctly. Seems kinda lame to pr a way to maximize damage on something that's already a station-ending disaster when the proper fix is to simply calculate that when you're sabotaging the engine. You shouldn't be able to have your cake and eat it too.

**Comment by Anonmare** [comment]
>Teleports behind you
>Unsheathes energy balls
"heh, too easy"
>Ashes you 
"nothing personnel, kid"

**Comment by kevinz000** [comment]
if this is merged and robustin dies to a tesla it's going to be "everything personal, noob."

**Comment by Iatots** [comment]
Maybe the beacon could be armed while unpowered, and as soon as a current forms it starts working?
You could then snip the wire "upstream", plant the beacon (or a bomb with a new current-checker component) and then mend the wire away from the bomb.

**Comment by Robustin** [comment]
@ExcessiveUseOfCobblestone 

Huh? It costs 14TC for you to take a round-ending event and GAMBLE a way to make it station ending (I saw gamble because there's a very real possibility that the engine will do what you want it to without the beacon, second to last time I release tesla it literally went around the station and blew up every dept with no beacon). It's already immensely difficult to pull off and even creating a singulo/tesla takes exponentially more effort than the old "cut a single wire" or "plant a brick of c4" meme, plus you have to find an active power current near your destination when you've blow up the main power supply and the device itself is super obvious. You give up a shitload by taking the beacon and the fact its almost never bought speaks for itself. Also you can't really "calculate that", the singulo moves slowly towards the beacon, the only way to calculate how the tesla moves toward the beacon is looking up the code... so it makes sense to slow it down so that the tracker can actually do its job. 

I turned on the beacon yesterday and it told me the Tesla was 175 (tiles) away, before the next announcement came (every 10 seconds) the ball was on top of the beacon. 

Lastly I didn't die, I escaped alive, get your ided shit out of here.

**Comment by Dorsisdwarf** [comment]
Apologies, I saw you ranting about it in deadchat shortly afterwards and assumed.

**Comment by ExcessiveUseOfCobblestone** [comment]
> it already does what you want half the time

> but let's make it do more damage because ???

It's a niche item, especially now given that we no longer default to the singulo/tesla engine, using times purchased around it is a bit silly. It's not necessarily *suppose* to be purchased a bunch.

And not knowing how the tesla speed works (more energy balls = more jumping ability) is not reason to buff it's ability in damage moreso than it already is.

**Comment by Robustin** [comment]
It's not slower, the beacon before made roughly 60% of the tesla movement go toward the beacon. At 30 balls that meant close to 20 turf per tick. Now it's 10% which still means the ball will jump around wildly, but on average it will still move toward the beacon.

**Pull request merged**
