### PR TITLE
Changes ethereal low charge damage from brute to tox to prevent dying

### PR DESCRIPTION
**Pull request by SpironoZeppeli**
Ethereals really don't die from their low-charge damage this time

## About The Pull Request
Changes ethereal low charge damage from brute to tox

## Why It's Good For The Game
Turns out brute causes bleeding. Burn does not, so the damage can be stopped before they go into crit with tox. Stops Ethereals from dying to low charge to prevent SSD deaths.

## Changelog
:cl: Spyro Zeppeli
balance: Changes ethereal low charge damage from brute to tox
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
don't make it burn, make it something like TOX or OXY

**Comment by SpironoZeppeli** [comment]
Any particular reason why?

**Comment by Qustinnus** [comment]
them burning due to a lack of charge makes no sense within ethereals intended biology

**Comment by ExcessiveUseOfCobblestone** [comment]
Oxy is too easily fixable atm to be a useful punishment for not charging.

**Comment by SpironoZeppeli** [comment]
I see burn as the ethereal starting to burn up from running out of power, like a star. I think it can be reworked to fit this without changing much.

**Comment by Qustinnus** [comment]
yeah but the point is that I dont want to change their biology due to a PR that im working on.

**Comment by SpaceManiac** [comment]
@Qustinnus Do you have a different proposal to address OP's grievance that is more consistent with your unrevealed new lore?

**Comment by Qustinnus** [comment]
I proposed some in my first comment

**Comment by SpaceManiac** [comment]
@SpironoZeppeli Cobby has rejected OXY so how do you feel about TOX?

**Comment by SpironoZeppeli** [comment]
Tox could work, I dunno how this fits into the lore but I'll throw the change in and see what mantainers think

**Review by SpaceManiac — APPROVED** [review]
Seems alright to me, can always be tweaked again later if it doesn't work out

**Comment by MegaEmpirical** [comment]
Tox could be explained by an imbalance of energy or some shit. They need charge/energy to maintain homeostasis like all other creatures but without it, shit gets fucky and manifests as toxin damage.

**Comment by ExcessiveUseOfCobblestone** [comment]
rip changelog off

**Comment by SpironoZeppeli** [comment]
@ExcessiveUseOfCobblestone is that too late to fix

**Comment by ExcessiveUseOfCobblestone** [comment]
in this PR, yes.

**Comment by SpironoZeppeli** [comment]
Oops, I'll make sure to check next time

**Comment by ExcessiveUseOfCobblestone** [comment]
🤷‍♂️

**Comment by SpaceManiac** [comment]
CL fixed in #43403

**Comment by SpironoZeppeli** [comment]
Thanks much

**Pull request merged**
