### PR TITLE
Anomalies can now be deconstructed for techwebs for 10k points

### PR DESCRIPTION
**Pull request by silicons**
Reasoning for 10k: They can only happen from random events, and when the engine is overloaded.
If engineers are somehow good enough to do this for 15 minutes straight without anything blowing up considering overload-levels of SM tends to superheat the room so radsuits can't fully protect you from damage, CE's hardsuit isn't fulyl radproof, and no one ever sets something up to prevent that, and the anomalies themselves can make safely de-overloading the engine nearly impossible, we can lower it.
For future things I'll likely add diminishing returns for things like this but that'll be in another PR, and I'll also be making these things defined somewhere else when json techwebs comes out ;)

:cl:
rscadd: Any anomaly core can now be deconstructed for a one time boost of 10k points in the deconstructive analyzer.
/:cl:

### CODE REVIEW

**Comment by Wilchenx** [comment]
Engineering will blow up the engine for a chance of 10k research points.


yeah i don't think this will happen sucessfully ever

**Comment by GunHog** [comment]
This method can only produce the 10K points **once**, right? The engine generates lots of anomalies at a time.

**Comment by 81Denton** [comment]
This is pretty great! You really have to know what you're doing to push the engine so it produces anomalies but doesn't blow up.

**Comment by kevinz000** [comment]
@GunHog woops i forgot i made this stuff single-use hm

**Comment by Tlaltecuhtli** [comment]
why waste on research free phazons

**Comment by davethwave** [comment]
Perhaps it could be full price for the first time for each type of anomaly. After that it would go by a x amount of points times .5 per analysis of each type of core.

**Comment by Kromgar** [comment]
Why not full price on the first anomaly and like 1/3rd cost for every other anomaly

**Comment by davethwave** [comment]
can you make anomaly armor with the engineer lathe?

**Comment by KorPhaeron** [comment]
yes

**Comment by kevinz000** [comment]
in that case this is ready! @KorPhaeron Oh yeah, should I make it give 10k points  once per type of anomaly or just 10k points once for any type of anomaly

**Comment by Shadowflame909** [comment]
Yus more ways for points! Sadly, I don't know how to utilize this way. SOLARS BEST ENGINE!!

**Comment by arsserpentarium** [comment]
10k once for overloaded engine?Don't make me laugh.

**Comment by Kromgar** [comment]
10k is about 3 minutes of waiting or 4 low tier techs

**Comment by davethwave** [comment]
Yeah, unless you get anomaly engine setup the price per core is kind of a rip off

**Comment by KorPhaeron** [comment]
3 minutes is a pretty substantial boost for a single item when you consider our round times

**Comment by Spaceinaba** [comment]
we need more systems so I can finally go back to RD but instead of memorizing the best sequence to max research instead I show the world how powerful I am by doing every single point booster at the same time forcing kor and kevinz to nerf science

**Comment by optimumtact** [comment]
conflicts

**Comment by Cyberboss** [comment]
Needs changelog

**Comment by kevinz000** [comment]
@Cyberboss done

**Pull request merged**
