### PR TITLE
Alternative Stunprod Nerf

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
tweak: Stunprods now require proper insulation to not get shocked while using it.
/:cl:

Alternate to #20343

A stunprod is a metal rod with a live battery tacked onto it with wiring, going around prodding people without proper insulation is probably a really dumb idea. Don't be a fool, wrap your tool!

Either wrapping the stunprod's base with insulated gloves or wearing the gloves yourself negates the effects, otherwise trying to stun someone will only end with stunning yourself and loosing a small bit of your dignity along with it.

Probably a better way to do it so be sure to tell me about my spaghetti code.

### CODE REVIEW

**Comment by optimumtact** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/clothing/gloves/color.dm#L6
Check the Siemens coefficient value, not the type path

**Comment by KorPhaeron** [comment]
In the last 30 days the following objects were made:

/obj/item/weapon/melee/baton/cattleprod	335

In the last 30 days (720 hours), the server has been up for:

Rounds played:	828

I'm not sure how this PLAGUE OF STUNPRODS thing started up again bad enough to lead to multiple prs about it

**Comment by lzimann** [comment]
that's also cool, whatever people prefer/maintainers/kor decide i'm fine with it

**Comment by InsaneHyena** [comment]
Pointless nerf, all true powergamers making stun prods roundstart already have insulated gloves. I like the backpack one more.

**Comment by MMMiracles** [comment]
I don't really care about the whining I just wanted to put together a more interesting nerf that also makes sense.

**Comment by Ergovisavi** [comment]
@KorPhaeron 

I don't think it's MASS STUNPROD CREATION, it's more like 'These are pretty lame how can we make this mechanic better'

That said I prefer the back slot fix over this, I don't want to have to fear everyone with yellow gloves again.

**Comment by Cheridan** [comment]
In the spirit of compromise I'll just merge both nerfs :speak_no_evil:

**Comment by lzimann** [comment]
merge mine first so i don't have conflicts :^)

**Comment by AdamElTablawy** [comment]
Eh... It should probably stun you ANd the guy. You still hit him with an electric stick, you just fucking zapped yourself too.

**Comment by XDTM** [comment]
This is kind of a buff to it since you can't disarm and use it against its owner anymore

**Comment by Alek2ander** [comment]
Yeah, should stun both

**Comment by blobbernaut** [comment]
stun both but the user significantly less

**Comment by MMMiracles** [comment]
womped

**Pull request closed without merging**
