### PR TITLE
Datum view and some other things

### LINKED ISSUE #41248: Navigational shuttle computers do not work if you're using 2x (64x64) sprite scaling
Round ID: 96345
Server: Basil
Map: Metastation

Navigational shuttle computers do not work if you're using 2x (64x64) sprite scaling

The hud icons are off screen and you cannot view the entire view area.

### LINKED ISSUE #45599: White Ship Navigation Computer Bugged
Issue reported from  Round ID: 114559 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1472

The icons that are supposed to be in the upper left hand corner of the advanced navigation HUD do not appear. Resting to exit the HUD makes the icons appear briefly as my character exits the HUD.

### LINKED ISSUE #50772: widescreen + binoculars = fuck
buggy view probably anything that does zooms does the same it doesnt scale  like it used to be and gives you view like if you were 10 tiles away

### LINKED ISSUE #50919: Widescreen issue
When you hover hand on an icon in left-top like map vote or somethnig. The message is like 8cm down from that. Laptop 1920x1080

https://imgur.com/a/ZeQet3y

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Adds a datum wrapper for client.view, with a bunch of helper procs.
We store 2 values here, the default state, think world.view, 15x15, 7, ect and the additional x/y values. This lets us deal with widescreen in a clean way, and supports adding/subtracting zooms, although I have not used that anywhere.

I've had to change a couple values that were normally being added to client.view, had to subtract 0.5 from them, because otherwise due to order of operations they'd be janky. Didn't want to make the change on our side because it seemed half assed. See this [graph](https://www.desmos.com/calculator/utkpx2gkmk) for an explanation.

Turning while using a binocular or zooming with a gun will carry any direction changes it should.
I was tempted to make this a component, but it seemed frivolous.

Also added some support for translating negative single view values properly.

fixes #50772
fixes #41248
fixes #45599
fixes #50919

## Why It's Good For The Game

Fully supports widescreen, makes a tool that's easy to use without fucking someones view range accidentally.

## Changelog
:cl:
refactor: Refactored client.view into a datum, changed some zoom values to work properly
add: Spinning while using a binocular will work as expected
add: Fully adds widescreen support to zooming
refactor: I've moved the pixel scaling and zoom methods from the menu bar to the game preferences window. You'll need to reset them.
fix: Pixel size will now automatically update on zoom, so you won't end up with ui buttons you can't see.
fix: FIxed the epic gamer skill of binocular applied to advanced camera console 
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Good idea

**Comment by LemonInTheDark** [comment]
I know right? I'm so smart

**Comment by LemonInTheDark** [comment]
I've moved the pixel scaling and scaling methods from the menu bar into preferences, and wrapped it in the datum, just for convenience.

**Comment by LemonInTheDark** [comment]
Also added autoscaling for zooming, to prevent people's pixel perfectness from fucking up action button placement

**Comment by LemonInTheDark** [comment]
I made tooltips account for screensize change, took some notes from gooncode.

**Comment by LemonInTheDark** [comment]
I've fixed part of #42567 by adding a suppression variable to view_size. It prevents anything but the default from acting. Unfortunately I can't do the same with client.pixel_x due to animate, so you gotta deal.

**Comment by LemonInTheDark** [comment]
I've asked zewaka about the goon thing, waiting for them to respond

**Comment by LemonInTheDark** [comment]
Replace zewaka with wire, and the state of things still holds

**Comment by LemonInTheDark** [comment]
Wire's good with it. 10/10, not getting sued edition 
image

**Comment by optimumtact** [comment]
@LemonInTheDark why did you remove the view menu from the top level settings menu?

**Pull request merged**
