### PR TITLE
Fixes phlog firestacks

### LINKED ISSUE #25321: Injecting phlogiston is bugged
If you inject someone with phlogiston they don't ignite. Whoever they do get burn stacks and this causes the phlogiston to do extreme fire damage (even though you aren't on fire). This actually makes phlogiston one of the most effective poisons you can make....

If you inject them again, however they DO ignite.

It seems the ignite is performed before the adding of firestacks.

### PR DESCRIPTION
**Pull request by Iamgoofball**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)
[]: # (See here for how to easily make a changelog: https://github.com/tgstation/tgstation/wiki/Changelogs. An example changelog has been provided below. Please edit or remove)

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 

fixes #25321

### CODE REVIEW

**Comment by Iamgoofball** [comment]
phat stakz

**Comment by optimumtact** [comment]
Can you fix your changelog please

**Comment by CPTANT** [comment]
Dammit, I got ninja'd by Goof, I was just testing the same fix.

**Comment by optimumtact** [comment]
Goof just doesn't test

**Comment by Haevacht** [comment]
Phlogistinator is for terrible pyros

**Pull request merged**
