### PR TITLE
changes a botanist tip to be more helpful

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

changes botany tip to mention how you can use radium or uranium if chemistry is a bitch or you didnt get a chem dispenser and need to mutate stuff

## Why It's Good For The Game

h

### CODE REVIEW

**Comment by trollbreeder** [comment]
Tell em about the unstable mutagen genemodded blumpkins, fikou.

**Comment by Cyberboss** [comment]
Sounds powergamey, correct me if I'm wrong

**Comment by Fikou** [comment]
> Sounds powergamey, correct me if I'm wrong

the powergame that botanists always use is getting their own chem dispenser

**Comment by ATH1909** [comment]
> Tell em about the unstable mutagen genemodded blumpkins, fikou.

Those take way too long to put together/make, _especially_ if you don't already have a supply of mutagen.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
