### PR TITLE
Removes 2gang

### PR DESCRIPTION
**Pull request by Ikarrus**
3 gang seems to be far more preferable as it leaves less room for one of the bosses being a lame duck and ruining the round, or security robusting one gang and letting the other spiral out of control.

3 gangs is easier to deal with because they keep each other in check.

### CODE REVIEW

**Comment by Nerolat** [comment]
Yes.

**Comment by Core0verload** [comment]
You must raise required_enemies and recommended_enemies to 3 then.

**Comment by SconesC** [comment]
In my experience as a Security player:

2gang is a lot more fun and has been overall much better for both sides. While Security arguably has a more limited range of targets, it somehow feels as though two recruiting teams produces more members than three. Again, this is probably a player issue - New players get gang boss CONSTANTLY, and at any given time it's a guarantee that at least 1/3 of a gang will be afk/not interested in helping. 2gang is more fun in my eyes.

3gang rounds are either brutally stomped into dust by the red tide, or become obscene wars of attrition where it's anyones game, sadly much like rev sometimes. I don't like it as much, and 3gang makes the gangs themselves feel much weaker. Gangster identity does not matter, and its impossible to gauge relative strength of the gangs. You capture someone and say oh, another fucking gangster: Not, oh, another orion, we see a lot of these.

I just don't like it as much, but I guess we can go ahead with this?

**Comment by Lumipharon** [comment]
Just leave 2gang for the lower pop range.
Having more gangs makes it exponentially harder to recruit/not get cucked. This isn't so much of a problem when you have 60 people, but when you've only got a 20-25 man crew? Yeah, naw.

**Comment by PKPenguin321** [comment]
I actually have a lot of enjoyable 2gang rounds, in 3gang one of the gangs usually just gets stomped

**Comment by Ikarrus** [comment]
I don't actually play any more so I just rely on you guys for feedback. 

Thanks.

**Pull request closed without merging**
