### PR TITLE
Runechat emotes

### PR DESCRIPTION
**Pull request by Rohesie**
## About The Pull Request

This is the port of a port. From Skyrat to TGMC and now to tg, incorporating some small improvements at each step.
Credits to Azarak for the original implementation.
There's a tiny bit of code-cleaning added, shouldn't be too hard to review.

Note: this includes both intentional and unintentional emotes. You'll see both people willingly nodding and involuntarily screaming.

## Why It's Good For The Game

Every since runechat was added, saying has been the superior form of communication. This brings mimes and snowflake RPers back into the game.

## Changelog
:cl:
add: Emotes now show on runechat. You can disable them on your prefs.
/:cl:

### CODE REVIEW

**Comment by KathyRyals** [comment]
I don't like runechat emoting. It just look weird for me to see the emote text pops up above the head of someone like talking does.

**Comment by optimumtact** [comment]
what does it look like

**Comment by Nebulacrity** [comment]
Yeah, what he said. Y'should've attached a video with a demonstration.

**Comment by Rohesie** [comment]
dreamseeker_Zr5y3nc8Rx

This is currently a thing on TGMC.
I can produce more images or a video if needed on this code, but it looks exactly the same, and runechat is already a thing. The change is not that big.

**Comment by Mickyan** [comment]
I think the styling could be better it's easy to confuse it for speech at a glance, maybe put it inside brackets or also put the symbol at the end of the sentence?

**Comment by Rohesie** [comment]
It's pretty distinct in-game. You don't really confuse one for the other.

**Comment by spookydonut** [comment]
@Rohesie merge conflict

**Comment by ExcessiveUseOfCobblestone** [comment]
do you have a picture where there isnt a cluster of bodies, preferably without adminhud?

**Comment by Rohesie** [comment]
> 
> 
> do you have a picture where there isnt a cluster of bodies, preferably without adminhud?

dreamseeker_D3Zu6DqRHA

**Comment by ExcessiveUseOfCobblestone** [comment]
oh ok the blue icon denotes emote, i was confused because it looked just like the radio chatter format

**Comment by kriskog** [comment]
Gave it a quick testmerge on bagil, I was a little worried they might be a bit intrusive. Turned out the worries were misplaced, although some tweaks may be needed down the road. Runechat seems to handle spam just fine.

image
Given the general strong aversion to change, these are very positive results for a first round of running it.

I'll review soonish, but this is a likely merge on my part.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
