### PR TITLE
a building inside a place full of lava (or is it magma?)

### PR DESCRIPTION
**Pull request by MMMiracles**
lewt

Fancy ruin with vague backstory while offering non-shit protection from ash storms and could actually be renovated into a base. Includes a potentially-working power grid (if you set it up) and a small atmos setup to try and keep it partially habitable.

what is rebasing/squashing commits i don't know honestly

### CODE REVIEW

**Comment by PKPenguin321** [comment]
there is literally nothing inside this why is it surrounded by lava

:-1: this wont ever be used because it has nothing and also its surrounded by lava
maybe remove the lava

**Comment by TechnoAlchemisto** [comment]
you should probably add a land bridge

**Comment by MMMiracles** [comment]
i'll take 'what are lavaboats' for 500, alex.

**Comment by TechnoAlchemisto** [comment]
i don't think anybody is going to waste resources on lavaboats when there is no incentive to go inside of this base in the first place.

**Comment by PKPenguin321** [comment]
ill take 'why is there lava in the first place' for 109000000000000000000000 gorillion alex

**Comment by RemieRichards** [comment]
@PKPenguin321 I'll take "LAVAland" for priceless, alex.

**Comment by PKPenguin321** [comment]
okay if you insist but i guarantee that maybe only one person will waste the resources to get into this thing

**Comment by MMMiracles** [comment]
I mean if you're such a stickler as a miner/cultist/asher that the idea of an isolated base with a lava moat that has access to power and air isn't worth a few goliath plates then I don't know what to say honestly.

**Comment by ChangelingRain** [comment]
- this is not a very good ruin
 - it's huge, what the fuck, it's huge and takes up way too much space for something that isn't easy to access and has little to no actual loot.
 - those windows over lava will burn the second something moves on that lava tile
- fluff is cool, and all, but large ruins should have at least some worth instead of turning out to be 'basically a bunch of connected survival pods'
 - in this case, it's a bunch of pods with a moat.
- using a huge chunk of the ruin budget on something that is inaccessable most of the time is.... bad, let's say.

**Comment by PKPenguin321** [comment]
yeah what joan said in his last point. i was gonna say the same thing but didnt know how to phrase it. this just seems like a waste of ruin slots or whatever

**Comment by MMMiracles** [comment]
@ChangelingRain 
>isn't easy to access

did goliaths become an extinct species/become signifcantly harder to kill as of recently because I don't think anyone past regular crew are going to have difficulties getting onto the actual base, which surprise, is the whole purpose of the mini-moat.

the loot is a perfectly sustainable base of operations for any would-be miner/cultist/whatever where they don't have to do base-construction and have something semi-defendable, maybe even find some loot if they bother digging around *HINT HINT*

'a bunch of connected survival pods'. i mean by that logic anything that doesn't have visible PHAT LOOT is just a bunch of connected survival pods.

if ruin budget is a problem I'll just lower it, it isn't that difficult at all.

**Comment by ChangelingRain** [comment]
Making a lava boat to get to a ruin that is literally a huge worse survival pod is super not ideal and I will bet you nobody actually wants to do that if they can fling a pod capsule and have a base with way less hassle. 
- What the fuck is the loot
 - is there any loot

**Comment by MMMiracles** [comment]
if survival capsules were more than 3x3 areas (5x5 if you take the time to deconstruct all the walls) and had a power net pre-made so all you had to do was add a cell for whatever else you wanted to add then maybe you'd have a point.

also lazy people can just fling a shelter capsule into the moat to make their own draw bridge if they want easy access if they don't care about compromising the main advantage of having a moat around a base.

as for the loot, mesons are great for finding false-walls.

**Comment by ChangelingRain** [comment]
oh you made the loot be a shitty gun now it's a ruin with a GUN in it!
so the loot for this ruin is A Gun, and also the base itself, I guess.

- Except getting to it and using it as a base isn't really practical for most people unless they use survival capsules(which requires about as much welding as using capsules as a base, probably more if you get unlucky with placement) or a lava boat(but that doesn't work very well with multiple people unless you have multiple boats)

**Comment by MMMiracles** [comment]
Yes, the whole purpose of a moat was to inconvenience those who try to pass it without proper equipment/using a pre-established method of crossing it as a bottleneck. Trying to circumvent the inconveniences of the moat at the very start nullifies the whole purpose of the moat.

For a regular miner trying to grab as much loot as they can (because lavaland doesn't have enough of it already??), they might not find much value in this area past the gun (which has easily printable ammo at an autolathe). I can imagine a cultist stumbling upon the place sure as hell would be happy to see what is essentially an isolated breeding grounds for uninterrupted conversion/sacrificing/culting things.

Just because there isn't any upfront value in terms of "HOW MANY THINGS CAN I SHOVE IN MY BACKPACK TO MAKE ME BETTER THAN THE PEOPLE ON THE STATION?" doesn't mean its a shit ruin.

**Comment by ChangelingRain** [comment]
It's difficult to get to, isn't likely to spawn often, for cultists it's often easier to just throw a few survival pods together because wow guess what both cults have some relatively easy way of removing walls(it's the constructs), and on top of that a cultist is not actually likely to have the materials for a lava boat because they're busy doing cult shit.

I suppose it has some merit as a prebuilt base, but building a base out of survival pods isn't hard for either cult, and most people who are not cultists have little use for it as a base!

**Comment by MMMiracles** [comment]
If getting 3 goliath plates for the boat itself and some bones for the ore is as difficult as you make it out to be then either the quality of the average crewmember has gone down substantially or mining mobs have become miniboss-tier levels of difficulty.

The 'isn't likely to spawn' argument is thrown out the window because RNG is just as capable of spawning the same ruin multiple rounds in a row and then it never seeing the light of day again.

Do people just not like building shit anymore or something have I become super disconnected from this game or something.

**Comment by ChangelingRain** [comment]
Most cultists aren't out mining and fighting mobs, they're doing cult shit, and the ones that are fighting mobs and mining are probably not going to drop a tele rune for their fellow cultists if they happen to find this ruin(or actually help the cult at all)

I'd also argue about if we want to encourage this sort of thing for cults but ~moving the goalposts/policy issue~

**Comment by WJohn** [comment]
Literally what is the point of this ruin?

-What's up with the airlock up north? There's no room to move around in there normally.
-Maintenance doors with glass for clear maintenance areas is a no-go, you shouldn't be seeing into those rooms.
-Southern main room is extremely friggin' weirdly shaped AND also totally empty. What's the point of this room??
-Art storage immediately above it presumably, also no known purpose.
-Bathroom where only 2 of the 4 tiles are bathroom tiles. Why? The shower head is literally floating inside the wall, lower its pixel shift by like 8-9 pixels.
-Bedroom has no bedsheet, chair, or items on the desk to make it look like someone lived there.
-Botany boasts no water supplies or machines to make it actually function.
-Bridge has reinforced flooring for some reason, looks really ugly. See if you can't also make the glass proper glass tiles like the mining base does nowadays.
-What's the point of the room outside telecomms?
-Why does telecomms boast no circuits?
-LITERALLY 0 LOOT.
-INACCESSIBLE OTHER THAN A BOAT
-PRETTY HUGE TOO



MMMircales you have been mapping for over a year, if you need to contact me in IRC to tell you how to improve, please friggin' come over I am sick and tired of the low-quality shit you keep making and getting put into the game. THE BAR NEEDS TO BE RAISED.

**Comment by optimumtact** [comment]
I think the push to have completely unique and snowflake ruins with special items is absolutely wrongheaded, bad and ruining our ability to make space content as well as lavaland content.

Most ruins should be ordinary and unremarkable and not much to speak off, the filler in the sandwich so to speak.

There should only be a few high value ruins.

Yes the ruin should be somewhat interesting, but requiring every single ruin to be very interesting is a terrible idea and will reduce the number of ruins made to a crawl until someone comes along and rips it out just like away missions were ruined by people.

**Comment by WJohn** [comment]
That's not achievable oranges. We do not have even a fraction enough ruins to warrant having nothing in them, and the system only allows like 5-6 ruins to spawn at a time so that's going to mean that very often you will have nothing to play with.

I also don't want space ruins as asteroids that are literally just 2-3 tiny rocks taking up space in the pool points.

But if we're going to argue space content friggin' AGAIN, put your thoughts in this thread instead:
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=7433

**Comment by RemieRichards** [comment]
@WJohn you know the budget is 100% adjustable, right?

**Comment by Kromgar** [comment]
Boats suck ass because they are expensive oranges. Maybe if you made a pr for titanium lavaboats people would be more receptive?

**Comment by Kromgar** [comment]
The issue is too many ruins spawn and then we have the issue that it fucks with tendril spawns and megafauna spawns. I get constant rounds with a lot of ruins but like 2 tendrils and no megafauna.

Unless lavaland can get expanded to encompass 2 zlevels

**Comment by MMMiracles** [comment]
@WJohn 

>What's up with the airlock up north? There's no room to move around in there normally.

SSU units were a last-minute addition and I did not notice the issue with size afterwards, already fixed.


>Maintenance doors with glass for clear maintenance areas is a no-go, you shouldn't be seeing into those rooms.

Unintended, accidently used the same maintenance doors from the walkway for the rooms.


>Southern main room is extremely friggin' weirdly shaped AND also totally empty. What's the point of this room??

Meant more as a hallway/connection between all the other rooms.

>Art storage immediately above it presumably, also no known purpose.

To hold art supplies, as most art storages would of done if it wasn't for the fact everyone left.

>Bathroom where only 2 of the 4 tiles are bathroom tiles. Why? The shower head is literally floating 
inside the wall, lower its pixel shift by like 8-9 pixels.

The two bathroom tiles being generic ones are due to the issue with floors in ruins getting set to a default plasteel flooring, they're bathroom tiles in the editor. 

I blame perspective for the showerhead, I'll move it down.

>Bedroom has no bedsheet, chair, or items on the desk to make it look like someone lived there.

I guess I'll throw in a chair, still meant to be 'people got their shit quickly and left'.

>Botany boasts no water supplies or machines to make it actually function.

Anything of decent value was ripped out and taken by the prior residence before leaving.

>Bridge has reinforced flooring for some reason, looks really ugly. See if you can't also make the glass proper glass tiles like the mining base does nowadays.

Seems fitting that a bridge supposedly inter-connecting two separate areas over lava would be reinforced. I thought the panes look cooler but if you want gigantic winders for a supposedly-slim walkway.

>What's the point of the room outside telecomms?

As a connection between the rooms that also houses the important shit like the air alarm and fire alarm.

>Why does telecomms boast no circuits?

Because the people who lived here before realize that telecomms are expensive for a renegade group of 'freedom-fighters' and probably didn't want their investment to go to waste.

>LITERALLY 0 LOOT.

See above.

>INACCESSIBLE OTHER THAN A BOAT

Mechs, capsule pods, do RCDs still work for planting on lava? BOATS AREN'T EVEN THAT DIFFICULT TO MAKE JESUS PEOPLE. THE WHOLE POINT OF THE MOAT IS FOR INCONVENIENCE aaaaaaaaaaaaaa

>PRETTY HUGE TOO

WOULDN'T BE A VERY GOOD STARTER BASE IF IT WAS TINY, NOW WOULD IT?


If cost is such an issue then that is easily fixed. I still stand by the validity of this ruin because I'm apparently the only one who sees value in a pre-built base with a powergrid/atmos that has a friggin' lava moat to keep people out if they aren't properly prepared.

**Comment by xxalpha** [comment]
MMMiracles dreams: crushed.

**Comment by MMMiracles** [comment]
There's still hope.

**Comment by Kromgar** [comment]
Also starter bases are terrible. Taking here will take too long

**Comment by Hatfish** [comment]
Maybe this could be a thing that always spawns in a far corner of the map?  The ruined mining base on the old asteroid comes to mind.

**Comment by Cheridan** [comment]
This doesn't seem popular at all so I'll just do this

**Pull request closed without merging**
