### PR TITLE
Fixes lots of map issues on box.

### LINKED ISSUE #6495: Blastdoor of atmospherics desk appears behind table on box
Blastdoor of atmospherics desk appears behind table on box instead of in front of it, so you don't see it and get confused at why you can't get on the table.

### LINKED ISSUE #6659: [Map Feature Request] Body Bags in Sec's Execution Chamber
I would like to see a couple body bags close to the Execution Chamber. Because after people have been executed, I'd rather not have to drag their corpses around without a body bag.

### LINKED ISSUE #6819: [MAP] Turbine vent monitor isn't connected to any cameras
Used to watch the turbine vent.
Shows a list with cancel being the only option.

### LINKED ISSUE #6941: Camera consoles in science don't work
The grey camera consoles in science,Research monitors I think, Don't seem to be working.

### LINKED ISSUE #7093: Turbine vent monitor without cameras
In the (new) incinerator there is the turbine, and a "turbine vent monitor" on the wall. (like the toxins launch monitor)
But there are no cameras around the turbine.
I suppose this is a mapping issue.

### LINKED ISSUE #7110: Mapping Error: Gateway Shutters Control
Pretty sure the required access on the shutters control button is incorrectly set; it's currently set for "cargo" access of all things. Shouldn't this be gateway or even RD level access? Cargo makes literally no sense.

### PR DESCRIPTION
**Pull request by WJohn**
Changes execution chamber and AI sat a bit to be much prettier.
New execution chamber:
http://i.imgur.com/Dau9uod.png
New AI sat:
http://i.imgur.com/hzPAhMk.png

Fixes #7110
Fixes #7093
Fixes #6941
Fixes #6819
Fixes #6659
Fixes #6495
#6485 can be closed as it is a non issue.

### CODE REVIEW

**Comment by leibniztg** [comment]
Did you add cameras to the turbine? Because when I reported that I didn't consider that maybe the AI shouldnt have cameras there.

**Comment by WJohn** [comment]
Yes, one has been added only in the turbine chamber.

**Comment by phil235** [comment]
:+1:

**Comment by GunHog** [comment]
Was the aft portion of the MiniSat intended to be such a major weak point? I cannot help but feel it needs a turret or something. Just a thought. Other than that, it looks quite nice. :+1:

**Comment by WJohn** [comment]
I can make that change in another PR, this is primarily bug fixing and visual prettyfying.

**Comment by GunHog** [comment]
Alrighty. Thank you for your consideration. Are the MiniSat fire alarms functional on this version?

**Comment by WJohn** [comment]
I don't see why they wouldn't work, this pic was taken from the map editor so by default they look off from there, even though they get their overlays in game.

**Comment by Xhuis** [comment]
:+1: x :100:

**Comment by vista-** [comment]
I don't really like the positioning of the new execution chamber, or at least it's entrance, it's really out "in the open".

Does the AI have visibility on that door?

**Comment by Kromgar** [comment]
The reason the execution chamber doesn't look pretty is so the AI can't see the door and so that it looks like its sketchy as fuck

**Comment by WJohn** [comment]
There's a difference between looking sketchy and being poorly mapped. I'll see about shifting it out of the camera's range.

**Comment by Chocobro** [comment]
ai sat looks great.
might want to add a bit of a hallway between the execution chamber and the viewing chamber, though.
:+1:

**Comment by WJohn** [comment]
Ugh, merge conflicts. Will make a new PR in a bit.

**Pull request closed without merging**
