### PR TITLE
Clockcult AIs get the ability to listen in through cameras

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Clockcult AIs can now listen to conversations through cameras.
/:cl:

utility!

### CODE REVIEW

**Comment by GunHog** [comment]
ctOS online

**Comment by FantasticFwoosh** [comment]
Why. 

Is using the general intercomms too good for you?

> Stop overthinking clock cult so much its fine honestly, please focus more on fixing its issues.

**Comment by anconfuzedrock** [comment]
yea the already winning cock cult needs this, not regular traitor ais

**Comment by GunHog** [comment]
Traitor AIs DO have this, it is a power they can buy.

**Comment by Crushtoe** [comment]
We just need to add more intercoms for nosey AIs, and holopads.

**Comment by Xhuis** [comment]
This seems way too powerful for the already-omnipresent AI. I'm curious as to your reasoning for making this.

**Comment by XDTM** [comment]
An idea: Make clock AIs able to build/maybe proselityze some simple stuff remotely, to go with the mechanical theme

**Comment by XDTM** [comment]
I was imagining the station's hidden circuitry and all turning into gears, cogs and machinery, making it moveable like portal's labs, for example.

**Comment by PKPenguin321** [comment]
Maybe put this as a purchasable thing for traitor AIs too?

**Comment by GunHog** [comment]
> Maybe put this as a purchasable thing for traitor AIs too?

It already is!

**Comment by PKPenguin321** [comment]
Delet this

**Pull request merged**
