### PR TITLE
[TM ONLY] Removes particles from Slimed and Slime Food status effects to see if it fixes fps lag in xenobio

### PR DESCRIPTION
**Pull request by Iamgoofball**
for TBM to TM

### CODE REVIEW

**Comment by MrMelbert** [comment]
Spoilers but the answer will be yes, at least partially

**Comment by CCC23** [comment]
THANK GOD I hate whoever made that change because the moment it came in my computer started to brick any time I walked in

**Comment by Profakos** [comment]
I just wanted to make an invisible mechanic visible, but if it hurts the game, the visuals should go indeed. 😔

**Comment by MrMelbert** [comment]
We can optimize it with object pooling

**Pull request closed without merging**
