### PR TITLE
Reverts combat rebalance

### PR DESCRIPTION
**Pull request by hornygranny**
## About The Pull Request
Reverts #2931

Doubles most stun and knockout durations
## Why It's Good For The Game
Now that the dust has settled, I feel the effective lower time to kill provided by longer stun durations increased the skill ceiling of the game, and allowed players a better chance at combating multiple opponents.

## Changelog
:cl:
balance: rebalanced stun durations
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
shoes dm conflicts...

**Comment by trollbreeder** [comment]
help it's HG and he's back for revengeance

**Comment by EOBGames** [comment]
did oldbox bring back the boomers or something?

**Comment by Survivioboi** [comment]
How bout we dont. Stuns are already long enough, making them fucking 10 seconds will ruin it.

**Comment by Iamgoofball** [comment]
hg please come back to coderbus bro

**Comment by cacogen** [comment]
missed sexygranny

**Pull request closed without merging**
