### PR TITLE
Lets portable atmos react when wrenched.

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
Title.
Previous attempt by https://github.com/tgstation/tgstation/pull/66207

A bit surprised that I don't have to change that many things. 

Wrenched cans are always marked as excited every time the pipeline processes:
https://github.com/tgstation/tgstation/blob/03ec15115a5b0b5c9c8b9a89480ca96bef9224ed/code/controllers/subsystem/air.dm#L273
https://github.com/tgstation/tgstation/blob/7103f8150a6d281e452b26b8ae0a8948af26965c/code/modules/atmospherics/machinery/datum_pipeline.dm#L231
https://github.com/tgstation/tgstation/blob/7103f8150a6d281e452b26b8ae0a8948af26965c/code/modules/atmospherics/machinery/components/unary_devices/portables_connector.dm#L47

I.E. process every tick. Let me know if this is bad.

And when off grid it works as usual.

## Why It's Good For The Game
Canisters not reacting when wrenched but reacting every other time doesn't really make intuitive sense.

## Changelog
:cl:
qol: Canisters, scrubbers, and pumps no longer stop reacting when wrenched.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
> I.E. process every tick. Let me know if this is bad.

Processing every tick is expected behavior, since they're having gas inserted/removed every tick.
That said, I'm not sure how I feel about including them in the pipeline equalization step, since that means they're effectively reacting twice, which isn't great.

There are issues with removing that though, canisters and other portables would update more slowly, which isn't good.
Out of curiosity, what problem *specifically* are you trying to solve here? I feel like there might be a better (not shorter) way of going about it

**Comment by vincentiusvin** [comment]
Just wanted to make cans still react when wrenched. Feels that its more intuitive that way.

**Comment by LemonInTheDark** [comment]
What does react mean?

**Comment by vincentiusvin** [comment]
gas_mixture.react()

**Review by LemonInTheDark — APPROVED** [review]
Forgot how pipeline reactions worked, this is fine.

**Pull request merged**
