### PR TITLE
Makes the operation computer tgui

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 
:cl: DaxDupont
tweak: CentCom has issued a firmware updated for the operating computers. It is no longer needed to manually refresh the procedure and patient status.
/:cl:

[why]: It's way more handy to have the tgui autoupdate the steps and state of the patients so you do not need to needlessly free your hands.

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]
Need to compile TGUI

**Comment by GunHog** [comment]
You are a good person.

**Comment by DaxDupont** [comment]
Whoops I forgot to commit those files.

**Comment by DaxDupont** [comment]
Forgot to include the compiled tgui files, it's added @Cyberboss

**Comment by vuonojenmustaturska** [comment]
This is good stuff, now you can actually do surgery without wiki

**Comment by Bawhoppen** [comment]
@vuonojenmustaturska There was no reason you couldn't use the operating computer before to do it? I mean, sure, you had to click to update it, but it was perfectly functional.

**Comment by DaxDupont** [comment]
@Bawhoppen Personally I used the wiki over the older computer since it was just too cumbersome to handle, alt tabbing worked better.

**Comment by optimumtact** [comment]
Did you know you can also walk a short distance away and the UI will still update (although you cannot interact with it)

**Comment by DaxDupont** [comment]
@optimumtact Yup, it's pretty handy since you're generally moving a little to grab the surgical tools.

**Comment by optimumtact** [comment]
where is the ui update being triggered from?

**Comment by DaxDupont** [comment]
@optimumtact ui_data gets automatically called as long the window is open with tgui.

**Comment by optimumtact** [comment]
hmm, maybe I'm just thinking of when you set the return value in the actions proc

**Comment by vuonojenmustaturska** [comment]
@Bawhoppen the non-updating UI on the operating computer made it pretty much useless except as a crutch in some scenario where I couldn't open an extra browser window. And I play roboticist fairly often.

**Pull request merged**
