### PR TITLE
[READY] Fixes T4 reagents being added to wrong dispensers

### LINKED ISSUE #41164: Booze, soda and lifebringer (botanical) dispensers manifest T4 chem reagents too
Issue reported from  Round ID: 96088 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512
#41029: '[READY] Hilbert's Hotel' by TheDreamweaver at commit edfcd61e4e

Caused by #40871 not having an override for the variable for the children of chem dispenser.

BTW it would be nice if it made those manifest extra sodas/boozes or "basic" cocktails on T4.

### PR DESCRIPTION
**Pull request by Barhandar**
Fixes #41164

:cl: Barhandar
fix: Reagent dispensers that aren't chemdisp will no longer contain T4 chemicals.
/:cl:

### CODE REVIEW

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]
It'll work.

**Comment by Barhandar** [comment]
On second thought, I'll just do that in a different PR due to needing to ask bartender players what they're in need of. Is it possible to open another PR with the same branch that got merged?

**Comment by ExcessiveUseOfCobblestone** [comment]
No just make a branch off of this branch

**Comment by ExcessiveUseOfCobblestone** [comment]
haha gives the needs review label

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
