### PR TITLE
the cooler "Can no longer immediately return a wayfinding pinpointer for a costume"

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This should fix the issue mentioned in https://github.com/tgstation/tgstation/pull/56916 by properly fixing the indentation of an if statement block.

## Why It's Good For The Game

See the WIGFTG section of https://github.com/tgstation/tgstation/pull/56916.

This version of the PR won't add a needless cooldown for refunding pinpointers, since they already have a cooldown for being printed and don't give you all of their money back anyway.

It also doesn't add a 50% chance to deal 5 brute damage to your hand and make you scream when you try to return a pinpointer too early for some reason.

The funny thing is, I could've sworn that I've bought and then immediately refunded pinpointers for credits before without issue, but maybe I'm just misremembering or didn't do it right.

## Changelog
:cl: ATHATH
fix: Non-roundstart wayfinding pinpointers that you've bought now refund for credits instead of a costume like they should.
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
i wish the pinpointer machine was just a machine that bluespace bullshit teleports unwanted quirk pinpointers to the shadow realm and spawns one if you have one instead of being a quirky machine that takes way too many credits for an item that you basically need if you don't know the layout of a newly added map, and spawns garbage on the floor if you've forgotten to take off the noob quirk for the 4th round in a row

**Comment by cacogen** [comment]
The pinpointers don't cost and haven't done for over a month. There are more optimal ways of providing the player with pathfinding to departments and if I had known how to code one of those I would've done.

>spawns garbage on the floor if you've forgotten to take off the noob quirk for the 4th round in a row

Some people quite like the costumes. I do, when it creates one that isn't shit. In any case, my fix (not this lazy, swoop-in one changing something I worked very hard on instead of just giving feedback on my PR) prevents quirk pinpointers giving costumes.

Navigationally Challenged is a joke but I understand on the 4chan server people are very insecure about things like being seen as being new to the game or not knowing their way around a newer map and I should've taken that into account when making these. I don't have any interest in changing it.

Also I may be reading the code wrong but it looks to me like this doesn't even solve the issue it purports to.

**Comment by ATH1909** [comment]
> At the moment the pinpointers are free

... why?

**Comment by cacogen** [comment]
This was all decided a month ago by me in the PR I linked which Rohesie and other maintainers looked over for the thing I'd coded a year previously that had gone untouched in the interim, before you decided you cared. 

To justify the decisions I made there to you now would be beside the point of me commenting on this or the issue I'm trying to fix in the first place.

Let me repeat my main points:

1. This allows you to refund free pinpointers for money, which is a worse issue than what it's supposed to be fixing
2. The code block you're supposedly fixing the indentation of that I wrote was supposed to be indented
3. I may be reading your code wrong but it looks to me like this doesn't even solve the issue it's supposed to. Did you even test it?
1. This is a lazy, swoop-in fix in response to a fix I already made changing something I worked hard on without talking to me about it beforehand, instead of just giving feedback on my PR (which I've already incorporated anyway)

You should close this and stop submitting adversarial PRs, at least in situations where the author of the competing PR coded the feature, you don't understand how it's supposed to work, your fix adds a worse problem and may not even work

**Comment by Mothblocks** [comment]
Supreseded by #56916

**Comment by cacogen** [comment]
Great hill to have died on

**Pull request closed without merging**
