### PR TITLE
Adds classic baton holdable for detective suit storage vest

### PR DESCRIPTION
**Pull request by jughu**
Adds police baton being fit in detectives armor suitstorage it can hold a normal baton
And egun so why not a classic baton

### CODE REVIEW

**Comment by CosmicScientist** [comment]
Does this affect their trench coat?

**Comment by jughu** [comment]
It should now

**Comment by CosmicScientist** [comment]
:+1:

**Comment by PKPenguin321** [comment]
>closes pr the second conflicts arise

I know that feeling my friend

**Comment by jughu** [comment]
muh sanity just overide the conflict and merge :^)

**Pull request closed without merging**
