### PR TITLE
Removes tripai landmark

### PR DESCRIPTION
**Pull request by ShizCalev**
Condenses it into the AI start position landmark.

### CODE REVIEW

**Review by WJohn — DISMISSED** [review]

**Comment by Cyberboss** [comment]
wondering if /primary should be a type to avoid confusing mappers

**Comment by DaxDupont** [comment]
Can you rerun mapmerge2 since it'll probably remap a bunch of dict keys
https://github.com/tgstation/tgstation/pull/35133

**Comment by DaxDupont** [comment]
Yeah but if everyone's just gonna make notepad changes we're just gonna have conflicts forever reeeeeeee

**Comment by ShizCalev** [comment]
The point of mapmerge is to minimize the diff, not to increase it. The keys are not changing in this case, so there's no reason for me to create merge conflicts with the other station PRs that are open right now just to purge the dictionary.

**Comment by DaxDupont** [comment]
well I mean you're conflicting with mine currently

**Comment by ShizCalev** [comment]
@DaxDupont No conflicts here. :p

**Comment by DaxDupont** [comment]
oh you're right! Thanks for checking!

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
