### PR TITLE
Minor traitor poison kit buff

### PR DESCRIPTION
**Pull request by NoxVS**
## About The Pull Request

Adds a bottle of the oxyloss poison multiver to the poison kit

## Why It's Good For The Game

Allows traitors to have a little bit more variety in what they do with the poison kit, allowing for more interesting scenarios involving it

## Changelog
:cl:
balance: buffs the traitor poison kit slightly with a bottle of multiver
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
Haha epic xd

**Comment by NoxVS** [comment]
as much of a meme as this was it was also kinda serious this shit kills in 10 units, there are poisons in the kit that dont even do that.

**Comment by improvedname** [comment]
Alot of the poisonkit stuff kills in 10 units

**Comment by improvedname** [comment]
But i also think it shouldnt be added to the kit due how common multiver is all you doing with this is pretty much turning the poison kit box better and now can hold 15 small objects

**Comment by necromanceranne** [comment]
Multiver can be counteracted with injecting your epipen into yourself. Which is usually a pretty smart thing to do when someone shoots you with poison given it heals toxin damage. But if they DON'T do this, then your lungs are going to be toast.

I used multiver during a recent rev round to ping seccies as I went along hunting heads of staff. Was fun.

**Pull request closed without merging**
