### PR TITLE
[READY] Rebalances medicated suture, adv. regenerative mesh and few meme chemicals' recipes.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Changes recipes for some chemicals.

**Medicated Suture:**
- Cellulose 10u.
- Formaldehyde 10u.
- Libital 10u.

**Advanced Regenerative Mesh:**
- Cellulose 10u.
- Aloe juice 10u.
- Aiuri 10u.

**Scream Powder:**
- Helbital 1u.
- Space Drugs 1u.

**Mega Scream Powder - _Makes a BIGGER scream and deafens in a small radius_:**
- Helbital 2u.
- Fentanyl 1u.
- Strange Reagent 1u. 
- Sonic Powder 1u.

**Butterflium:**
- Colorful Reagent 1u. 
- Strange Reagent 1u.
- Nutriment 1u.

## Why It's Good For The Game

Sutures and Meshes required quite a lot help from botany, rendering those recipes quite underused, if not useless.
Same goes for meme chemicals, such as scream powder, which had absolutely impossible recipe.

_I hope this PR won't make people have too much fun._

## Changelog
:cl:
add: Mega scream powder(screams better and deafens in a small radius) recipe: [Helbital 2u, Fentanyl 1u, Strange Reagent 1u, Sonic Powder 1u]
balance: Easier recipes for: Medicated Sutures, Advanced Regenerative Meshes, Scream Powder and Butterflium.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
leave aloe in, its a tier 1 plant you just need to put it in the brrr grinder

**Comment by EgorDinamit** [comment]
Guess I can swap it with cellulose, so it requires at least a bit of collaboration with botany.

**Comment by wesoda25** [comment]
There doesn't even seem to be a point for scream powder, why are you adding another version of it?

**Comment by EgorDinamit** [comment]
For a meme flashbang that screams.

**Comment by Krysonism** [comment]
This is terribly imbalanced. This removes all effort in creating the sutures and meshes.

**Comment by Shadowflame909** [comment]
Might need to be buffed tbh Kryonism.

Last time I tried to mutate something for a cargo bounty, I wasn't doing anything else for the entire round.

**Comment by Krysonism** [comment]
> 
> 
> Might need to be buffed tbh Kryonism.
> 
> Last time I tried to mutate something for a cargo bounty, I wasn't doing anything else for the entire round.

Most of the issues people are having with turbotany stems from not understanding the mechanics, mainly cross-pollination.

Spaceman's trumpet is a bit crap at the moment because these suture are the only application for it.

The two most played maps have roundstart lilies, so these sutures are not even hard to make as is.

**Comment by EgorDinamit** [comment]
I will buff suture and mesh recipes by a bit again.

**Comment by MarioWizard119** [comment]
No, most people’s problems from turbotany stem from it being merged by triple sec, not oranges.

This is the _second_ time someone got suuuper drunk and “accidentally” hit merge instead of test merge on a massive rework that functionally _crippled_ a department because the whole thing was a massive _over_nerf that was not thought through.

There’s even _less_ justification to nerf botany than to nerf goonchem. Goonchem was busted since all it took to heal someone back to full health in a single click was 100u of synthflesh splashed on someone. Old botany was already considered a race against time to get anything cool done, so the solution is to make botany slower? Now botany is xenobio levels of slow, no, actually xenobio is better since all of your slimes don't suddenly die if you decide to tab off and watch vsauce. That and it fails to accomplish anything it says it does, besides take away any and all control botanists have, which in that, it did marvelously.

Dependency on chems has not changed one bit, and with how fast plants consume nutrients, it’s been made _more_ dependent.

The removal of Gaia trays and the addition of auto grow has had the opposite of the intended effect. Botanists have now become more tied to their trays since there’s a limit on how many trays you can have on autogrow before you eat power from your apc faster than it can recharge, and it becomes useless once you have t2 parts.

Botany now has a brand new restraint, _tech_. It’s bloody impossible to make a decent mix in 10u, so unless your plant trays are upgraded, which for how many there are, is a massive resource sink, you’re boned. Oh and there’s the floral somatoray and gene secateurs, if anyone actually bothered to research botanical engineering. It’s a massive artificial timegate that holds absolutely no skill in the botanist, but rather in the mercy of other departments. Upgrades should be a convenience, not a necessity.

So yeah, I call bull on the claims that “you’re not doing it right” when people have been doing _exactly_ the things asked and still haven’t been able to do jack. It’s about time someone’s cleaned up this mess.

**Comment by Shadowflame909** [comment]
So in short.

It is a good thing Egor is making the recipe easier. Because the botany mutation changes have made it require too much time for such an item. When you're actually able to create it, the end-game is here and the rest of the crew already has items that outclass it.

**Comment by optimumtact** [comment]
large rant

**Comment by MarioWizard119** [comment]
And what about the early game? Will people just have to diddle their thumbs until science/command/whatever gets off their rear ends? And what about that rarity thing tech webs are supposed to have? Will only one department get the privilege of actually being able to do something while the others are basically memes?

**Comment by MarioWizard119** [comment]
Also, shadow flame had a more accurate summary, though you marked it as spam.

**Comment by Krysonism** [comment]
> 
> 
> Guess I can swap it with cellulose, so it requires at least a bit of collaboration with botany.

Cellulose does not require collaboration with botany, a large number of station items grind into cellulose.

**Comment by EgorDinamit** [comment]
@Krysonism I meant swapping cellulose with Aloe.
I returned aloe into mesh recipe now.

**Comment by ExcessiveUseOfCobblestone** [comment]
I have been able to make all my mutations just fine within rounds, not sure what you're talking about. I get one bottle of muta from chem, although I dont mind botbros who make their own dispenser (free saltypee).

The gaia nerf was intended, you are not meant to have maintenance-free plants. Don't even think i had an issue leaving botany for a bit and coming back for either autogrow or not with current botany.

Sounds like you haven't played it on current commit, I'd recommend trying it now that you start with 20u trays.

Regarding the techweb comment, research has never been skill based. The highest skill ceiling was old RND where you placed items in a specific order for min/max effect. If you want to make it "fun" be my guest, but if it's in the game it should be considered fair use as a balance tool.

**Comment by ExcessiveUseOfCobblestone** [comment]
The point of them is that they're relatively easy healing items anyone can use and cannot be sabotaged (you cannot put naughty chems in a mesh or suture).

I'm not terribly sold on either becoming more widely available.

**Comment by EgorDinamit** [comment]
Why did my scream powder recipe rebalance PR turned into botany discussion, gosh.

**Comment by ExcessiveUseOfCobblestone** [comment]
don't really care for the changes to the medical items, but im fine with the others.

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> don't really care for the changes to the medical items, but im fine with the others.

**Comment by optimumtact** [comment]
don't really care for the changes to the medical items, but im fine with the others.

**Pull request closed without merging**
