### PR TITLE
[WIP] Adds the golem Qustinnus was too afraid to add (telecrystal golem type)

### PR DESCRIPTION
**Pull request by tralezab**
:cl:
add: Telecrystal golem! It can be completed for 10 telecrystals, but will be a worse golem until it has been fed 10 more crystals.
/:cl:

I may or may not make a sprite for this golem because it is so rare, if I do i'll let the bluespace golem also share the crystal look.

mechanics: it can't die. right now it has nodeath, but i'm planning to go further than that. Try to cremate it? It'll pop out of the machine afterwards. Explosions? It shrugs those off. After 30 seconds in crit, it lurches back out of crit. When it's not in crit, it slowly regenerates.

downsides: it has a speech impediment. It can only repeat one phrase it can switch every minute. This is to ~~make something cool~~ prevent friendly telecrystal golems on the station.

it also does not gain its immortality powers until it awakens, by consuming 10 more telecrystals in it's hand.

### CODE REVIEW

**Comment by Shadowflame909** [comment]
I don't think this is going to be merged, since the coder direction wants more death.

We also have bluespace golems already chief.


Maybe if it had pacifist and mute.

**Comment by tralezab** [comment]
Yeah my rationale is that you need to save all of your crystals until you can make this

**Comment by ExcessiveUseOfCobblestone** [comment]
even if it's difficult to obtain, immortality isn't fun to fight.

**Comment by fluffe9911** [comment]
I mean they can still be stunned then locked in a room somewhere doesn't seem that bad to me I would blacklist these from the magic mirror though so we dont get miners cheesing all the megafauna threw immortality

**Comment by necromanceranne** [comment]
Immortality is definitely not a good way to go about this. Making it ungodly difficult to kill by all conventional means, and itself very formidable would justify the ghost role gamble, the use of all your telecrystals to achieve it and the time sink investment into golems over some other xenobio meme.

**Comment by Shadowflame909** [comment]
Goliath Meat golem when

**Comment by tralezab** [comment]
I think it could lead to creative ways to destroy it. For example, it is physically immortal but not mentally, I'm going to remove the brain damage healing. You can also change it's race to remove its power

**Comment by Therapist1** [comment]
Taking into consideration it can’t use ranged weapons and the multitude of methods you can use to combat and disable the golem, it seems fair. (though BOH worries me slightly)

**Comment by necromanceranne** [comment]
Race swaps are the domains of botany (with roundstart rng most likely and time) and xenobio, the department in which you produced the fucking thing and likely have staffed with other sentient monstrosities.

Brain damage via chems would require that the golem A) could be injected with chems, which is can't unless you use a patch, B) breathes, which it doesn't.

Assuming you catch it. Nobody here has yet to acknowledge that xenobio can also produce red scooters and the golem can still use mechs. Both of which require 0 tc to produce. Both of which roboticists have access too on some stations, so it's possible to have them utilize this both at the same time.

There is a difference between unkillable and raid boss tier powerful. One is unfun, either for the players fighting it or the player piloting it, because to combat it requires cheap and bandaid fix solutions that produce literally nothing interesting. Like babysitting it with stuns, or it repeatedly suicide bombing with triggers tied to its one phrase, which could be a nonsense word. While the other is more enjoyable to fight because it requires an actual fucking fight. It'll just require more than a 1v1 to overcome most of the time.

I suggest maybe balancing it with that in mind. Giving it possibly lower stun durations, immense damage reduction and other features, over straight up being unkillable.

**Comment by tralezab** [comment]
I like the way you think, I want it to feel powerful to pilot but not brain dead easy. I can make it not be able to buckle to things so it is harder to make mobile, but if you have ideas that aren't stat changes, I'd love to implement them. I could go in the direction of spells like the runic, but I feel that goes away from the direction the original poster wanted

**Comment by tralezab** [comment]
But yeah in it's current state you put it into crit and put a shit ton of brain damage patches into it, giving it brain death. You can also use an eyedropper to give it reagents

**Comment by tralezab** [comment]
My last idea was to move immortality onto an immovable rod golem (I have sprites it looks hilarious) and the golem cant stop moving, built from a suplex'd rod

**Comment by ATH1909** [comment]
I think that it should have really good damage resistances, pretty good regen, and the effects of nodrops and a CNS rebooter. You should probably make it unauggable in that case, though, as augments provide flat damage reduction that appears to apply AFTER damage resistances (which could result in an invincible golem, as mentioned earlier).

OOH, better idea- it's a normal golem, but when it dies, it leaves behind another (full-power) telecrystal golem shell that can't be taken over by a ghost that has piloted it earlier. It's still a nigh-unkillable monstrosity, but it now has a (selfish) incentive to not suicide rush into things.

**Comment by tralezab** [comment]
golems.dm may scare you, but i assure you i am at least 70% sure everything is okay.

something something carriage return

**Comment by zxaber** [comment]
You could also do that one "automated shitcurity" thing where you handcuff buckle it to a chair sitting on a conveyor belt, which keeps it moving and therefore unable to break free.

Or just handcuff it and do the brain damage thing.

**Comment by Qustinnus** [comment]
image

**Comment by optimumtact** [comment]
This is as stupid as it sounds

**Comment by tralezab** [comment]
daw

**Pull request closed without merging**
