### PR TITLE
resprites surgery tables and stasis beds

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

"wahhh do things that actually require respriting grrrrr........."

ok fine. here.

image

image
## Why It's Good For The Game

old ones were dogshit.
## Changelog
:cl: axietheaxolotl / viro
image: resprited surgery tables, and stasis beds
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Could you go and do the same trick we have for n/s stasis beds for the surgical beds? That way we can get some easy E/W sprites there as well.

**Comment by DATA-xPUNGED** [comment]
How does it look with someone on top? I always disliked how the old one felt too small for the spess men

**Comment by SinfulBliss** [comment]
The stasis beds look better, the surgery beds look worse. They look a bit washed-out and too bulky and squarish, sort of too much like a roller bed. A bit too flat and not as shapely.

**Comment by Singul0** [comment]
roblox surgery bed

**Comment by CRITAWAKETS** [comment]
Should probably increase the glow on the stasis bed, especially make the outline less contrasting.
The shading also looks a little off on the stasis bed's bed part, but I'll probably get used to it.

**Review by Wallemations — APPROVED** [review]
They're both an overall improvement to the originals;
- surgical table angle is better
- stasis bed looks less blurry

Good work

**Comment by AtomTheProphet** [comment]
> They're both an overall improvement to the originals;
> 
>     * surgical table angle is better
> 
>     * stasis bed looks less blurry
> 
> 
> Good work

I agree with everything except the surgical table. It is not an improvement.

**Comment by Exester509** [comment]
I wonder where the "arms" went in the surgery table. Unless they're those two stripes on the sides, and, if so, why are they detached?

**Comment by Imaginos16** [comment]
Well made and inoffensive. I've seen that style of surgery table done on many servers, such as Shiptest. Fits the perspective that machines and tables are going for better.

**Pull request merged**
