### PR TITLE
Minor weather code split/refactor

### PR DESCRIPTION
**Pull request by ghost**
As part of my personal crusade against gigantic files with way too much information in them, I've hit weather. `weather_types.dm` is now a folder called `weather_types`, and each type of weather has its own file.

Additionally, I renamed `impact()` and `can_impact()` to `weather_act()` and `can_weather_act()` for consistency purposes, and changed the messages of some weather.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Personal crusade against easily readable file histories

**Comment by Xhuis** [comment]
My vengeful wrath cannot be stopped

**Comment by Cyberboss** [comment]
Confrictur

**Comment by Xhuis** [comment]
I know, I've just not been able to work on it; I'll try and get 'er done by tonight though.

**Pull request merged**
