### PR TITLE
Update Adminmenu

### PR DESCRIPTION
**Pull request by hrrgerfwefegrthsr**
This fixes an adminmenu.dm script some functions were broken

### CODE REVIEW

**Comment by kevinz000** [comment]
i permabanned please remove admin panel...
image

**Comment by Daturix** [comment]
https://prnt.sc/hmhdj2

**Comment by arkadiusz123** [comment]
okay suck my update

**Comment by alexkar598** [comment]
In your second OOC messasge,you putted a "will" which was not needed and made the sentence just wrong. Also they are not dumb,they won't ever accept it.

**Pull request closed without merging**
