### PR TITLE
New Engineering Crates, Shuttle Loan fix

### PR DESCRIPTION
**Pull request by Core0verload**
Even the hydroponics has it's own crate painting scheme, why engineering can't get one?
crates
For now, these sprites are only used by engineering supply packs in cargo.

Also fixes "Shuttle Loan" event giving useless 100 credits. It's now multiplied by 100, just like the rest of cargo points.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
cool but looks kind of out of place, looks more like a goon sprite almost

**Comment by duncathan** [comment]
I'm not a spriter, but I know pillow shading is wrong

**Comment by Iamgoofball** [comment]
this doesnt look pillowshaded

**Comment by WJohn** [comment]
This is not pillow shading, crate sprites just look ugly in general. Someone should resprite them at some point, as well as lockers.

**Comment by ChangelingRain** [comment]
It needs to use a brighter shade of yellow, like the secure engineering lockers do; it's too dark/dirty looking.

**Comment by Core0verload** [comment]
Sadly, I can't do any shading changes, because the sprites are actually made by one of Animus spriters.

**Comment by Supermichael777** [comment]
do they have the correct license and are you atribuitng properly?

**Comment by Iamgoofball** [comment]
@Supermichael777 They're a /tg/ downstream, it's kool babe

**Comment by ChangelingRain** [comment]
In which case they can be edited fine.

**Comment by Core0verload** [comment]
I'm not a spriter, so no, not really.

**Pull request merged**
