### PR TITLE
Reworked the Longevity symptom

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
del: Removed the Longevity symptom.
add: Added Viral Aggressive Metabolism, which will make viruses act quickly but decay over time.
/:cl:

The new symptom is called Viral Aggressive Metabolism, and makes any virus that has it as symptom start from stage 5 but decay in stages over time, curing itself when getting on stage 1.
The virus will still increase in stages depending on stage speed, like normal ones, so it'll last longer with stage speed.

Should still fit the niche of Longevity, while making it a bit more unique than "extra stats".

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
so do you not want speed because it will rapidly decay? or does speed help it not decay?

**Comment by XDTM** [comment]
You do want speed, it will keep the virus working for longer since stages will go back up

**Comment by LanCartwright** [comment]
that is interesting mechanic. I like it.

**Comment by PKPenguin321** [comment]
yeah this is really neat

**Pull request merged**
