### PR TITLE
DiscStation Cargo Update + stuff

### LINKED ISSUE #13072: Disc Station Cargo is awful
-The supply shuttle is airless and probably open to space because the thruster windows don't exist.
-You can't get crates out because of the lack of air causing space wind
-disposals ejectors spew trash out in the wrong direction
-There's a wall mounted radio in the mining dock under the window
-ore redemption takes ore from the wrong direction
-no QM office silver coin
-For such a gigantic highpop station, Disc Cargo is noticeably smaller then other stations, aside from the gigantic Delivery Office room
-There's a random toolbox embedded in a Delivery Office window
-QM office has too many doors, and one leads straight out to the main hallway
-Cargo completely lacks a maintenance entrance despite being adjacent to one.

Pretty awful.

### PR DESCRIPTION
**Pull request by Strathcona**
Fixes #13072

Revamps and widens DiscStation cargo and manages to fix all the issues with the sorting room, airless shuttle and more.
- Added a few more cosmetic items to the halls like mini gardens and a snack bar
- Readded disposals to medbay
- Fixed a few lighting issues
- Redid the rather bland and boring Cafeteria as an upscale coffee bar, Spacebucks (taking suggestions on the name)
- Fixed a few minor area issues with nearspace
- Added a space disposals to xeno

### CODE REVIEW

**Comment by Strathcona** [comment]
Oh, I guess this is a mapping PR so why not try @WJohn as a reviewer mention-bot?

**Comment by GunHog** [comment]
>Redid the rather bland and boring Cafeteria as an upscale coffee bar, Spacebucks (taking suggestions on the name)

Just name the area "bar". Use a barsign to allow the players to customize their establishment themselves.

**Comment by Strathcona** [comment]
There's already a bar on discstation with the diner aesthetic and it's got the sign and everything. Here's a side by side of the new cafe

image

**Comment by Dorsisdwarf** [comment]
Wood airlocks detected abort abort

**Comment by Strathcona** [comment]
What's wrong with wood airlocks?

**Comment by Supermichael777** [comment]
nominally they cannot be fixed if broken

**Comment by Anonus** [comment]
Also they look like shit, oh god.

**Comment by Strathcona** [comment]
Wait, you can't make wooden airlocks from wood? If so I'll just make them glass.

**Comment by Hatfish** [comment]
Have you fixed that one issue with the shuttle missing a wall yet?

**Comment by Strathcona** [comment]
The cargo shuttle was missing windows on the engines if that's what you mean.

**Comment by Hatfish** [comment]
No, there's a gaping hole into space on the left side of the shuttle, near the purple flooring.  At least, it was like that the last two times I saw it.

**Comment by Strathcona** [comment]
@Hatfish Looks like that was fixed. This is merge ready by the way.

**Comment by Strathcona** [comment]
Added the new pods into this as well. Merge please @tgstation/commit-access

**Comment by Strathcona** [comment]
Can we some Razharasing in here @Razharas?

**Comment by Strathcona** [comment]
Thanks Duncathan.

**Pull request merged**
