### PR TITLE
Better sprites for bed and bedsheets

### PR DESCRIPTION
**Pull request by Core0verload**
bedsheets

### CODE REVIEW

**Comment by Jalleo** [comment]
No runtime bedsheet?

**Comment by Core0verload** [comment]
These sprites aren't mine. They are stolen from old tgstation13 sprite hosting.

**Comment by WJohn** [comment]
As the guy who sprited the ones we currently have (forever ago, now) I can say these look quite a bit better. Although you'll need to change the red cross medical bedsheet to blue, as we have bluebay.

**Comment by Anonus** [comment]
To avoid red cross complaints, apparently.

**Comment by WJohn** [comment]
Also a big consistency bonus since medbay used to be every which color. Besides, I rather like bluebay.

**Comment by Firecage** [comment]
Core, I feel like the bedsheet which is middle row, second from left, is inconsistent compared to the rest. It's quality just looks...off.

**Comment by Cheridan** [comment]
Yeah, the quality differs a lot from sheet to sheet. The colored ones look good but the job-specific ones, like the cultist and the HoS one look pretty bad still.

Can be fixed later by a spriter, I suppose.

**Comment by Core0verload** [comment]
Cultist sheet and some others are old sheets changed a bit to look like new. And it's not HoS sheet, it's syndie sheet.

**Comment by SconesC** [comment]
I like em

**Comment by Ausops** [comment]
yeah firecage I never bothered to make cultist/wiz bedsheets that would be why

**Pull request merged**
