### PR TITLE
Makes AI controlled aliens spit acid (almost), which deals burn damage instead of toxin.

### PR DESCRIPTION
**Pull request by Helg2**
## About The Pull Request
So, AI controlled xenos, which you can meet on CharlieStation or Lavaland, spit with neurotoxin, which straigh up deals toxin damage and i remember it dealing brute damage, so it the whole idea.
Changes subtypes projectile name and damage_type, so it will write that it spits acid instead of neurotoxin when it hits someone and deal burn damage.
I closed the same previous pr so more people could see it.
## Why It's Good For The Game
Dunno
## Changelog
:cl:
add: AI controlled xenomorphs now spit acid, which deals burn damage instead of toxin.
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
But why?

**Comment by Helg2** [comment]
> But why?

So you can heal wounds from it with burn heals and not multiver bottle, and just because it seems illogical to me that it deals instant 30 toxin damage. It wont affect xenomorphs as antag, it's just simple mobs one, if you misunderstood it.

**Comment by optimumtact** [comment]
that's not a reason, that's just you saying you prefer it that way

**Comment by Helg2** [comment]
> that's not a reason, that's just you saying you prefer it that way

Technically yes, but any reason could be considered only as an opinion and not as reasonable reason. You can argue about it if you want and to prove i'm wrong.

**Comment by ZephyrTFA** [comment]
> You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Pull request closed without merging**
