### PR TITLE
Fixes beam-using projectiles runtiming if shooting a target adjacent to the firer

### PR DESCRIPTION
**Pull request by ChangelingRain**
Also fixes; meathooks being able to grab anchored mobs???
Beams not being deleted unless the projectile hit a living mob(aaaaaa)
Tesla revolver using a non-tesla beam for the bolt(koooooor)
Meathook 'hook' having dirs and thus looking super odd as a projectile

### CODE REVIEW

**Comment by lzimann** [comment]
woooow you killed my tendril cheesing method with hook with this

**Comment by Kromgar** [comment]
NOOOOO.

Meathook tendril was a valid strat for fighting goliath tendrils

**Comment by lzimann** [comment]
or watcher tendrils, fuck watcher tendrils

**Comment by nullbear** [comment]
^ make it unbuckle the mob.

**Pull request merged**
