### PR TITLE
Added advanced blob interaction mechanics

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Blobs can now sense touch. UGUUU~
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
go back to hippie

**Comment by Supermichael777** [comment]
BEGONE

**Comment by YakumoChen** [comment]
no, you already tried this once and it worked horribly, stop trying.

**Comment by GunHog** [comment]
This has no chance, but wow is it amusing!

**Comment by outbools** [comment]
this is weird sexual deviations come see doctor
[https://www.youtube.com/watch?v=l60MnDJklnM](url)

**Comment by kevinz000** [comment]
out

**Comment by AnturK** [comment]
Didn't notice this PR before.

**Comment by lzimann** [comment]
remember when we told you to stop with these meme prs

**Comment by MoreRobustThanYou** [comment]
@lzimann but those blobs need love :(

**Pull request closed without merging**
