### PR TITLE
OldStation Biolab and misc changes.

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Moved the storage with SM tools from R&D area to the new engine area and filled the space with a Biolab that acts as a micro cyto/viro/xeno lab. The dead miner in R&D is replaced by dead roboticist with some hints about robots (Charlie and Delta now also have navbeacons in hallways to allow patrolling). Also updated computers on the station and made some minor tweaks to different areas of the map.

## Why It's Good For The Game

My aim is to improve this map by adding more toys, puzzles and lore hints, making the activities on the map more diverse, but without breaking the immersion of partially destroyed derelict station infested by xenomorphs.

The Old station ghostrole is a very chill, unique SS13 experience that needs more love. I think that we need more missions that let you enjoy SS13 as a sandbox, rather than being thrown into the chaos of a regular shift.

### General

* Fixed gravity generator bug that lets you fix it when it was not broken.
* Fixed missing message that tells that the airlock is welded when you examine it.

### Delta biolab

biolab

Biolab acts as a micro viro/cyto/xeno area.
For the case if the player catches a virus from breathing in miasma, there is a broken Pandemic machine to find the cure, and a virus food to allow for working with viruses. (Will consider removing Pandemic if it won't be locked by the Human dissection experiment that can't be performed on this map unless you know how to get monkey cubes and mutate monkeys)
There is a small lore-related cytology puzzle (spoilers in the code) with other cytology-related hints that may lead the player to making a gray baby slime to start up xeno.
And there are remains of a xeno egg implying on the reason for the xeno incident.

### Beta engine room tweaks

engine

SM tools storage moved to the new engineering area, and part of the machinery is now scattered in the engine room implying on the struggles of engineers during the catastrophic event. An unpleasant surprise awaits you here. The engine room equipment is here to be an obstacle during that surprise and to make the storage less packed.

### Robotics hint and navbeacons

custodial

The dead miner in R&D is now a dead roboticist with a small hint on bot crafting and management. Use his ID to unlock the panels of manually crafted robots. 
Charlie and Delta now have navbeacons in the main hallways for patrolling.

### Consoles

Space-Station-13-2022-05-23-120538

The generic computers now can be deconstructed and drop a useless generic circuit that can be reclaimed for glass in autolathe. They also now has random sprites (all with the same old greenish style)

Two computers are replaced with working versions:
* Atmos console with sensors that show the contents of the O2 and N2 tanks.
* Solars maintenance room now has power monitoring console to see how solars charge the station.

Also added a modular computer with engi preset to the SM engine room to let people see the SM stats.

### Misc. minor changes

* The internal hollow windows are now not reinforced to allow easier breaking by players and xenomorphs.
* Added a Laundry to the Charlie station maintenance for fun and an option to get a mood boost by washing the jumpsuit.
* Moved the APC ID card closer to the APC, and added a crowbar and a note as a hint.
* Moved medbay defib to make the medkit visible and added a bonsai skillchip to the box to motivate players to build a skillstation. The bonsai skill will help to deal with all the dead pot plants on the station.
* Solars now use solar panel tiles with wires underneath to make the solars area more distinct and make cable laying less bothersome.
* Smelter conveyor belts can now be accessed, as the ore gets stuck there without a gravity.
* Changed some APC, cables, pipes, lights locations and made some minor consistency and prop changes.

### Map comparison

map_before

map_after

:cl:
fix: Gravgen now can't be repaired when not broken.
fix: Airlocks now properly say that they're welded when examined.
qol: Oldstation some internal windows are not reinforced to allow easier breaking
qol: Oldstation computers have random sprites and can be deconstructed, some of them became real computers (atmos monitor attached to sensors, power monitor in solars maint room to see how solars charge the station, and modular console with engineering preset to have an ability to see SM stats)
refactor: Oldstation SM tools storage moved into the engine area secure storage
refactor: Oldstation engine area now has a deadly trap and cluttered with remains of the pre-impact setup
add: Oldstation now has a Biolab in place of the previous SM tools storage
add: Oldsation now has navbeacons and a small robot-making hint
refactor: Oldstation dead miner is now dead roboticist 
refactor: Oldstation maintenance areas updated accordingly without loot changes
add: Oldstation now has a small laundry
refactor: Oldstation solars now use solar panel tiles
add: Oldstation medbay has bonsai skillchip in the box to provide a use for all the dead plant pots
fix: Oldstation minor fixes and visual tweaks like missing switches, etc
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
> 1. The fulltiles were intentional since that's how station maps used to be, and this is supposed to be an old station. 

This is subjective. This map is intended for playing and not a simple prop like other ruins. And the hollow tile windows have terrible UX - it's a pain to deconstruct, repair them and build if you want to fix the breached windows. Also the cracks are nice to show that the station is old and sustained damage.

>You also put floors under it when its supposed to be platings.

I think it's only for botany - grass tiles under windows give off the garden vibe, and the bridge has broken light tiles for ambient illumination to attract the player to the important button while there is no light.

> 2. The SM chamber being empty was intentional because I want players to freely build whatever SM they want, not have to deal with whatever's pre-built.

There is almost nothing pre-built, I made it so that the storage is not so cluttered and to make it look like there was a horrible accident where engineers had to fix things with foam etc. There is no piping or chamber, and some equipment is not even anchored.

> 3. I don't like them having a civilian console, feels way too out of place for oldstation

Why? The R&D console is there though. I like the fact that when you look at it you realise that you are alone.

> 4. The custodial closet being empty was because I just wanted to have a place to put a chemical synthesizer, I don't want them especially to have a cleanbot. The room also doesn't even look barred off like the old miner corpse was.

For me it didn't make sense where the miner got wood and what he was doing in R&D. Now the door is welded with the toolset implant next to the robotist's corpse. Please read the lore note to understand the reasoning.

> 5. There's not really a point of adding a skilchip to Med when there's no skillchip station, don't understand why you chose bonzai either...

In case if you play this together with someone who is not knowledgeable in terms of mechanics, you can just build a skill station and let them play with those dead plant pots. Right now you can't even deconstruct or break the dead plant pots, only space them out.

**Comment by Jolly-66** [comment]
> Willards points here

I'm echoing some of Willards points through my own comment as well. 
1. I had warned you against swapping to regular full window tiles. The spawners were fine (like KS13/TheDerelict, it too is an "echo" of an older time. The spawners fit the theming). 
2. I also suggested making the prototype lab have the cyto lab as some sort of branch to it, instead of being an entire wing off to the side. 
3. I'm personally not on board with giving them functional consoles. This is a *derelict*, barely anything is functional "round start". This ruin is to encourage players to rebuild what has been lost. I also suggested making the current consoles deconstructible (as now, they're put further into obscurity. They could use with that specific face lift to make them nicer).
4. I'm on the fence with giving them a pandemic machine. I learned viro myself through this ruin due to someone making a miasma room. The lab feels too complete for its purpose.
5. I can't tell if you did it in this PR, but it looks like the mostly fixed up the northern transit tube. I would like it if you put the deceased miner back because it was a second source of brute heal packs. 
6. Some of your misc changes perplex me.
> Remove reflector, as it guarantees a diamond drop

I don't understand the true logic behind this. The ancient lathe has a blacklist of constructible if thats your concern. 
> Added a washing machine to Charlie maint

You could've put it in the regular dorms room, all things considered. Its out of place there imo.
> Added an inducer

No. I'm against this. Players should be encouraged to learn how to open APCs, not use inducers. If players are having issues we have a wiki, and admins if they're truly stuck.
> Solar changes

Eh, its cool, but he plating is more soulful here. The station has been in disarray for so many years. 

> Removed the grav note

If there was a bug it should've been reported. This is a new addition, and I think Willard would've been more than happy to try and fix it (or someone else).

I'm not addressing the last two since the former is a qol change, and the latter I can care less about so long theres a complete circuit.

**Comment by Fikou** [comment]
the unhollow windows are lame as hell

**Comment by MTandi** [comment]
Reverted some changes, marked with strikethrough. 

Reverted windows seeing the backlash, but I still want to hear other reasons than "It's nostalgic for me", "They look less lame". As a relatively new player, I don't feel these echos, I only feel frustration when I bump into them. It may be easier to deconstruct a reinforced wall than a hollow window. And my OCD kicks in when all windows are hollow, but the one I'm repairing is fulltile. I'll go mad if I try to reconstruct the generated hollow tile windows.

>I also suggested making the prototype lab have the cyto lab as some sort of branch to it, instead of being an entire wing off to the side.

It is of a perfect size right now, I really don't know how to make it as a branch still having airlock, pens and a working area.

>I'm personally not on board with giving them functional consoles. This is a derelict, barely anything is functional "round start". This ruin is to encourage players to rebuild what has been lost. I also suggested making the current consoles deconstructible (as now, they're put further into obscurity. They could use with that specific face lift to make them nicer).

The code specifically states that circuitless should not be deconstructable. Not sure why. Probably because it will require a skip of one step during deconstruction. Don't really want to touch this as it will affect all consoles, but I still want to avoid having the same instance of consoles all with the same sprite on this map. By default - almost all of them are broken right now and you can't really benefit from repairing them since, they're mostly informational or require unavailable ID.

>I can't tell if you did it in this PR, but it looks like the mostly fixed up the northern transit tube. I would like it if you put the deceased miner back because it was a second source of brute heal packs.

The bruise pack is still there with the dead roboticist, the only difference is that it's behind a welded airlock rather than a wooden barricade. I replaced him to avoid heavy lore concentration in one place, and the roboticist is just an extended version of miner. My only concern here is that airlock examination doesn't say when it's welded, and some may not notice that.

>You could've put it in the regular dorms room, all things considered. Its out of place there imo.

You mean next to the pods? I thought that maintenance is a better place for loud and wet machinery. I'd rather remove it if it is really out of place in maintenance.

>Eh, its cool, but he plating is more soulful here. The station has been in disarray for so many years.

I'm not sure now. I like it when the cables are obscured by a tile under the solars - it looks less of a mess when finished, but you have a point.

**Comment by Colovorat** [comment]
Just remove crossed text, no need to keep it, especially in changelog

**Comment by MTandi** [comment]
I can't do anything to resolve the conflicts at this point, because the map dimensions got changed.

**Comment by MTandi** [comment]
Changed the way the console changes are made. Now it's just a generic deconstructable computer with random sprites that has a useless circuit. The images are in PR

**Review by Maurukas — APPROVED** [review]
A lot of care and effort went into this. Some of the detail work on these rooms is fantastic.

I can't check for roundstart ATs due to the ruin placement bug (fix coming soon hopefully), but that's something we can fix after the fact.

**Pull request merged**
