### PR TITLE
Removes the animal hospital ruin

### PR DESCRIPTION
**Pull request by ghost**
It's not funny, it's tragic. Nobody uses it, it's basically just a ruin that nobody uses

### CODE REVIEW

**Comment by PKPenguin321** [comment]
no dude

**Comment by deathride58** [comment]
No. Why would you?

**Comment by Armhulen** [comment]
Because it offers nothing to the game and I have a replacement after that isn't complete shit

**Comment by ACCount12** [comment]
How about you make a replacement PR first?

**Comment by Armhulen** [comment]
is there really a lot of love for the animal hospital

**Comment by Armhulen** [comment]
because i'm detecting a lot of not an argument here

**Comment by Bawhoppen** [comment]
You don't need to replace it. You can add a new ruin.

Animal hospital is a completely harmless ruin that can add fun and interesting situations with the vets, and isn't just another lootdrop ruin.

**Comment by Armhulen** [comment]
@KorPhaeron said to add a new ghost role ruin you have to remove one, and this has been asking for it for awhile.

**Comment by KorPhaeron** [comment]
To remove a ruin you must add one

**Comment by Armhulen** [comment]
okay

if people liiiiiiiiiiike this then i'll just add a ruin it's not worth the controversy

**Comment by Bawhoppen** [comment]
What a rude branch name though

**Comment by Armhulen** [comment]
i was mad

**Comment by calzilla1** [comment]
Make that HoG-lite ruin

**Pull request closed without merging**
