### PR TITLE
Wizard items resprite

### PR DESCRIPTION
**Pull request by MelokG000**
## About The Pull Request
Resprites wizard weapons
Wizard Weapons
StavesResprite

## Why It's Good For The Game
Wizard weapons look old and boring
## Changelog
:cl: MelokGleb and KREKS
image: modified wizard weapon textures
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
give my boy spellsword more focus on the runes and i love it, merge

**Comment by zeroisthebiggay** [comment]
image

you made a fucky with the healing staff's animation

lava staff has a similar issue too

**Comment by xKREKSx** [comment]
> image
> 
> you made a fucky with the healing staff's animation
> 
> lava staff has a similar issue too
> 
> unless github is tweaking

Hmm... strange, most likely GitHub is tweaking
Because the sprites should look like this
staffofhealing
lavastaff

**Review by Wallemations — APPROVED** [review]

**Comment by Admiral-Gigaton** [comment]
This affects nullrods yes?

**Pull request merged**
