### PR TITLE
Spamming runes / battlecries / etc will no longer trigger spam prevention

### PR DESCRIPTION
**Pull request by ghost**
NO LONGER WILL PEOPLE BE IC MUTED FOR CLICKING THE OFFER RUNE ONE TOO MANY TIMES!

:cl: Thefastfoodguy
fix: Spamming runes / battlecries / etc will no longer trigger spam prevention
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
i hereby ban you from capitalization.

**Comment by AnturK** [comment]
This shouldn't have been merged, only updates /living say

**Comment by duncathan** [comment]
what more needed to be updated?

**Comment by AnturK** [comment]
Signatures of living subtypes at least, all say procs should have the same signature in my opinion but that's more subjective.

**Pull request merged**
