### PR TITLE
Fix lionhunter ammo side path

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Makes lionhunter ammo recipe actually give you the stripper clip

## Why It's Good For The Game

makes a broken sidepath work as intended

## Changelog

:cl:
fix: Fixed lionhunter ammo sidepath
/:cl:

### CODE REVIEW

**Comment by Cenrus** [comment]
How can I trick this into passing linters?  `/obj/item/ammo_casing` doesn't have a caliber defined

**Comment by MrMelbert** [comment]
good catch

for the CI failure, you could check in the loop:
`if(isnull(casing.caliber) || casing.caliber in acceptable_calibers)`
I don't think any casings in practice have a `null` caliber, so for safety the casing should be valid if it's unset

**Comment by Cenrus** [comment]
Thanks, the way I was about to do it was way worse.

**Comment by Cenrus** [comment]
The unit test doesnt run the snowflake check which is why it's not playing ball

**Comment by MrMelbert** [comment]
> The unit test doesnt run the snowflake check 

That's weird, the test runs `do_ritual` which calls `recipe_snowflake_check`
Maybe it's caused by the ambiguous `||`?

**Comment by Cenrus** [comment]
I made the caliber list into a blacklist instead

**Pull request merged**
