### PR TITLE
Removes Virus Carrier RNG

### PR DESCRIPTION
**Pull request by ghost**
"what if there was a small chance for all your hard work to just fuck up"

### CODE REVIEW

**Comment by Incoming5643** [comment]
it's there as a back up strat if your virus is too deadly to spread much before the infectees die.

Also this is the wrong way to remove features, you should actually remove code and associated vars

**Comment by kevinz000** [comment]
What... does this do? :o

**Comment by RemieRichards** [comment]
@kevinz000 certain viruses had a 5% chance on spread to not trigger any effects, ever.
That person could still spread the virus to others, but they would never be effected themselves.

**Comment by Supermichael777** [comment]
IMO a Typhoid Mary feature is neat, wold be even cooler if it didn't show up on health hud. dont take it away.

**Comment by optimumtact** [comment]
What if you could just comment out code instead of deleting it

**Comment by PKPenguin321** [comment]
is this why sometimes my superviruses dont seem to do jack shit

**Comment by Cheridan** [comment]
I like the idea of asymptomatic carriers, but for this to be a proper feature it requires:
A. The ability to actually know that someone is an asymptomatic carrier instead of having no clue as to why your disease is doing nothing (scanners, medhud).
B. Some way to both induce and prevent carriers, so you can take advantage of it: Preventing your monkey from being a carrier during testing/becoming a carrier for a lethal disease/giving your jerk idiot boss an asymptomatic strain of your super-healing disease which prevents him from getting the real one so you can laugh when he collapses in a hull breach

**Comment by bustygoku** [comment]
@optimumtact I dunno future generations might see it and go wow virus carriers was a cool feature I'm going to improve on it and readd it instead of making it a bad 5% prob that just fucks up disease transfers!

**Comment by Jordie0608** [comment]
Remove the code instead of commenting it.

**Comment by bustygoku** [comment]
@Jordie0608 Done

**Pull request merged**
