### PR TITLE
[WIP]Ports bloodsuckers

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This PR will port bloodsuckers from fulp, a vampiric antagonist with cool progression mechanic and many other cool stuff.
It is a port of a port, because it ports yogstation bloodsucker port from fulp. So yeah.

Yogstation PR - https://github.com/yogstation13/Yogstation/pull/13273
Fulpstation PR - https://github.com/fulpstation/fulpstation/pull/97
Fulp wiki page about bloodsuckers - https://wiki.fulp.gg/en/Bloodsucker

It is opened as a draft for discussion purposes

## Why It's Good For The Game

New cool antagonist with unique mechanics

## Changelog

:cl: TheSwain, JohnFulpWillard, ported by SuperSlayer
add: Ports bloodsuckers
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
no fucking vampires

**Comment by TymurShatillo** [comment]
Based

**Comment by DAKKA-WAAAGH** [comment]
**PR (#69696) Adds the Morbpire**
Antagonist that uses extremely advanced syringe technology to instantly and discreetly steal blood from the crew.
The Morbpire uses blood to perform Scientific Rites, allowing them to grow in strength by acquiring new Scientific Abilities.

**Comment by moocowswag** [comment]
> next time you must make them science pires like morbius

It might be less about the theme/setting (we have witches and wizards) and more about orange being on team Jacob

**Pull request closed without merging**
