### PR TITLE
Wrapping paper fixes.

### LINKED ISSUE #73800: package wrap can't be pulled out of wrapping paper
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/stacks/wrap.dm

Due to changes on how you remove items from stacks, right clicking to extract package wrap from wrapping paper now conflicts with changing the coloring of that wrapping paper. The latter takes precedence over the former, making wrapping paper entirely unusable, as while package wrap can be wrapped around objects, wrapping paper cannot.

Left clicking with an empty hand on stack of wrapping paper in your other hand removes 1 instance of wrapping paper from the stack, not package wrap (as I believe it's supposed to).

This directly ruined a gimmick of mine where I was planning to pretend to be Santa Claus by wrapping up normal objects in Christmas-colored package wrap, as while wrapping paper can be recolored (which in turn recolors the package wrap you remove from it), package wrap cannot.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

This, as the title suggests, fixes some wrapping paper bugs.

First, wrapping paper coloration has been rebound to Alt+click, so the control doesn't conflict with extracting wrapping paper from a roll, which is right click. Originally, both of them were on right click, which caused problems.

Second, it fixes a problem with the greyscale icons on the gifts themselves. They were showing up as the default gift icon, no matter what color you selected, because the automatic path generation wasn't set up properly. This fixes that.

Fixes #73800.

## Why It's Good For The Game

Bugs are bad, and we should try to fix them.

## Changelog
:cl:
fix: Gifts you wrap will now display their greyscale colors as they're supposed to.
fix: Wrapping paper color selection has been rebound to Alt+click, to fix a bug where both wrapping paper color selection, and extracting wrapping paper from a roll were both bound to right click.
/:cl:

### CODE REVIEW

**Comment by sergeirocks100** [comment]
Upon further inspection, wrapping paper _isn't_ supposed to produce package wrap when you extract some from a stack, it (as expected) just gives you more wrapping paper.

However, judging by the fact there's sprites for it in the icon files, you're clearly _supposed_ to be able to wrap small packages with wrapping paper; it just doesn't work, for whatever reason.

I'm going to see if i can restore this functionality.

**Comment by sergeirocks100** [comment]
I think i'm going to mark this as draft for the time being.

**Comment by sergeirocks100** [comment]
I'm a doofus.

As it turns out, i don't think you're supposed to wrap a package in wrapping paper, by itself. You're supposed to put on package wrap first, and _then_ wrap it in the wrapping paper.

However, i did discover another bug, in that the greyscale colors on the wrapping paper don't appear to show up as they should when you wrap a package.

**Comment by san7890** [comment]
invert the behavior imo. alt-click makes more sense to have it be removing sheets of paper, and right-click would make more sense to bring up the selection wheel or whatever it is (i'm not intimiately familiar with how this works).

at least that's how i think material sheets (iron, glass) works? let me know if i'm wrong.

**Comment by sergeirocks100** [comment]
> invert the behavior imo. alt-click makes more sense to have it be removing sheets of paper, and right-click would make more sense to bring up the selection wheel or whatever it is (i'm not intimiately familiar with how this works).
> 
> at least that's how i think material sheets (iron, glass) works? let me know if i'm wrong.

I'm pretty sure that every stack has you remove an amount through right click, and i imagine people would get confused if wrapping paper had a different bind for that from every other material stack.

Besides, i have zero clue as to how i would move material extraction to Alt+click _specifically_ on wrapping paper, because my knowledge of DM (and programming in general) is pretty poor.

**Pull request merged**
