### PR TITLE
when you pick up an item it screams to let everyone know you picked it up

### PR DESCRIPTION
**Pull request by Militaires**
@ExcessiveUseOfCobblestone 
complements #39231 nicely 
sounds like this:
https://www.youtube.com/watch?v=j0CCGzOoS6k
:cl: bman
add: when you pick up an item it screams to let everyone know you picked it up
/:cl:

### CODE REVIEW

**Comment by Kawaii-Big-Boss** [comment]
holy shit yes
don't even fucking deny this because it's a joke PR, it's great

**Comment by RogueSteampunker** [comment]
Holy shit yes

**Comment by Suicidalpickles** [comment]
very immersive, yes

**Comment by Militaires** [comment]
WTF??? @optimumtact 24 hour rule????????????????????? hello????????????

**Comment by ExcessiveUseOfCobblestone** [comment]
Hitler maintainers going against THE PEOPLE

**Comment by AffectedArc07** [comment]
tyler fucking 1

**Pull request closed without merging**
