### PR TITLE
Nerfs tesla coil instakills

### PR DESCRIPTION
**Pull request by silicons**
Math with Mekhi part 1.

### CODE REVIEW

**Comment by jughu** [comment]
Featur

**Comment by ExcessiveUseOfCobblestone** [comment]
b-b-but lethality is fun!

**Comment by kevinz000** [comment]
This was instahusking people from off screen.

**Comment by PKPenguin321** [comment]
Tesla grilles used to do this because the math was about 2000 degrees off, good times

**Pull request merged**
