### PR TITLE
[s] Makes melee combat more skill-based

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: Melee combat is now more skill-based.
/ :cl:

Random critical hits have been added. All melee weapons have a 10% chance to critically hit upon an attack, which will cause 2x damage.

### CODE REVIEW

**Comment by Aloraydrel** [comment]
Dodge chance when?

**Comment by YotaXP** [comment]
Dodge chance that makes you randomly walk into lava when attacked.  Just like Dwarf Fortress!

**Comment by Aloraydrel** [comment]
Level 1 assistant stacking dodge chance

**Comment by Archie700** [comment]
random crits are fair and balanced - pub tf2 player

**Comment by PKPenguin321** [comment]
now all we need is a 60 brute weapon with no random crits and we will achieve perfect game balance

**Comment by Razharas** [comment]
>Crits arent showing as red numbers flowing upwards from the target

0/5

**Comment by drynwyn** [comment]
random crits are a fair and balanced game mechanic

**Pull request merged**
