### PR TITLE
Medical Revamp: Resprites and Jumpsuit/Under Changes

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

An overall revamp of the medical aesthetic, in line for a more surgical look. A full list of changes is below.

Resprites of scrubs, CMO's turtleneck (done by @Imaginos16), Virologist, Paramedic, and Chemist jumpsuits:

sfafsafsafsafsafsa

The biggest change I've made is the removal of the Medical Doctor's jumpsuit, in favour, they now immediately start with baby-blue scrubs, and can get different colours from the vendor.

I've also removed the nurse's dress from the game. Overall, it was a poorly done sprite, that was immensely over-sexualised and wasn't very funny.

## Why It's Good For The Game

Medical being more surgical is more appropriate for their general aesthetic and gameplay loop, as medbay is essentially an ER. The jumpsuits looked bad, and whilst it's possible to improve them, it'd be better to make them use something more fitting.

Everything else is just the plain ol' 'this looks better then what we had before'.

## Changelog

:cl: axietheaxolotl, Imaginos16
imageadd: New sprites for the CMO's turtleneck/skirtleneck, paramedic jumpsuit/jumpskirt, virologist jumpsuit/jumpskirt, and chemist jumpsuit/jumpskirt
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
I forgot to do fucking MAPS ughhhdnjkdhajnhndja

**Comment by bluetshirtguy** [comment]
is medical being more surgical why they wear skirts too? /s

**Comment by JosephJomama** [comment]
Most of these sprites seem quite well done, but why are you wearing a MODsuit while showing off the sprites? It makes the sprite's back impossible to see, and the back shading can be pretty important.

**Comment by Imaginos16** [comment]
Unrelated to the PR.

**Comment by GuillaumePrata** [comment]
The base medical jumpsuit could be adjusted to make it easier for doctors to patch people without fully stripping them and opening their gear to be looted be the average medbay goblin.
We have been adding this feature to most job's roundstart clothing over multiple PRs to stop the annoying side of going to medbay and losing all your stuff. The scrubs can't be adjusted and opening compared to the base medical jumpsuit/skirt and this is simply a bad trade.

**Comment by axietheaxolotl** [comment]
On request of Twaticus, I've made the following changes:

Medical Jumpsuits are back in, but with an edited sprite. Scrubs are still the default:
sgdhaha
bjhgisk

The Nurse's suit is back aswell, but in the autodrobe pending a re-sprite. Mostly I wanted it out of medical, and we came to this compromise.

**Comment by VladinXXV** [comment]
i maintain that cmo turtleneck should not be an itchy knitted sweater but rather a sleek and professional garment

**Comment by Imaginos16** [comment]
> The base medical jumpsuit could be adjusted to make it easier for doctors to patch people without fully stripping them and opening their gear to be looted by the average medbay goblin. We have been adding this feature to most job's roundstart clothing over multiple PRs to stop the annoying side of going to medbay and losing all your stuff. The scrubs can't be adjusted compared to the base medical jumpsuit/skirt and this is simply a bad trade.

The jumpsuit returned, but scrubs are the default outfit. Nothing stops you from simply going to the vendor and purchasing it however.

**Comment by Imaginos16** [comment]
> > The jumpsuit returned, but scrubs are the default outfit. Nothing stops you from simply going to the vendor and purchasing it however.
> 
> Adjusting suits instead of fully stripping is important for medbay, removing that feature from their main uniform is just backwards on multiple PRs that tried to drill into player's mind how to not turn their patients into easy loot piñatas while they are crit/dead in stasis.
> 
> Either way that is truly minor, nothing that can't be patched with another PR to let scrubs be adjusted if this one doesn't add it.

I'll add an adjust function for scrubs in a later PR.

**Comment by ExcessiveUseOfCobblestone** [comment]
the jumpsuit should still be the default if you are planning to merge this first then.

**Pull request merged**
