### PR TITLE
Infiltrators 3: Fuck edition

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Infiltration mode! 3-5 syndicate infiltrators armed with stealthy gear are tasked with infiltration SS13 with many objectives!
/:cl:
)

### CODE REVIEW

**Comment by praisenarsie** [comment]
how you doing, mrty.

**Comment by MoreRobustThanYou** [comment]
@praisenarsie just got unflagged

**Comment by optimumtact** [comment]
You're not welcome here

**Comment by ExcessiveUseOfCobblestone** [comment]
Hiiiiiiiiiiiiii MRTY!

**Pull request closed without merging**
