### PR TITLE
[NO GBP] more tablet additions

### PR DESCRIPTION
**Pull request by azrael-x86**
## About The Pull Request

actually makes the damn action button for the flashlight on your device work, as well as fixing clown/silicon/mime names properly showing up

+ fixes not chunky finger people not being able to use pdas

## Why It's Good For The Game

tweaks to make the tablet more user friendly

## Changelog

:cl:
fix: actually makes the flashlight action button work, and fixes silicon/clown/mime names showing up properly on tablets/messenger
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
isn't this intended behavior?

**Comment by magatsuchi** [comment]
> isn't this intended behavior?

for normal tablets and computers, people with chunky fingers should still be able to use their round start PDAs

**Review by stylemistake — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
I thought the tablet thing was kinda the point, aren't pdas currently a replacement for things like the roundstart engi tablet?

**Comment by magatsuchi** [comment]
> I thought the tablet thing was kinda the point, aren't pdas currently a replacement for things like the roundstart engi tablet?

pdas are currently a replacement for pdas
also being pedantic about "chunky fingers can NOT use this device (even though PDAs worked fine with chunky fingers)" is stupid

**Pull request merged**
