### PR TITLE
Fixes conveyor switches

### LINKED ISSUE #24772: Conveyor belts are broken
Turning the lever on them just doesn't work. See: Cargo belts/robotics belts on boxstation

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #24772

DIRTY DIRTY SPAWNS

### CODE REVIEW

**Comment by PKPenguin321** [comment]
related: i recently spawned new shutters and a button and linked them with ID but they didnt work, is it possible they werent initializing right or something?

**Comment by Cyberboss** [comment]
I changed machines to use Initialize recently, that's whats causing all these bugs

**Comment by PKPenguin321** [comment]
pls to fix 😮

**Comment by Cyberboss** [comment]
Oh wait that's not a bug, you can only link shutters before they are created

**Pull request merged**
