### PR TITLE
add hardware flags for silicons pdas

### PR DESCRIPTION
**Pull request by lizelive**
## About The Pull Request
adds PROGRAM_CYBORG and PROGRAM_AI hardware_flag and tags programs correctly.

## Why It's Good For The Game

a lot of apps are restricted to or from borgs. this pr makes it clean to do so.
tweaks borgs internal pda to be more like a laptop instead of a pda (with addition of NtosVirtualPet becuse it sounds adorable for a borg to have a virtual pet )

## Changelog
:cl:
code: add hardware flags for silicons pdas
balance: borgs are now able to view cameras via internal pda if someone uploads the app to them
code: apps borgs can't use are marked as such.
balance: borgs can't use lifeline app anymore
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
how are borgs meant to download anything without the app that allows them to do so?

**Comment by chemistrymain3** [comment]
what's with the stealth nerf where they can't use lifeline

**Comment by JohnFulpWillard** [comment]
> how are borgs meant to download anything without the app that allows them to do so?

Humans can upload programs to Borgs by hitting them with a data disk.

They should use PDA flags if they don't already instead, they should be treated like one.

**Review by JohnFulpWillard — CHANGES_REQUESTED** [review]
Actually they do use PDA flag. What's the point of this change other than to completely restrict them from using a ton of apps from an intended mechanic?

**Comment by zxaber** [comment]
I agree with John. The only app that is restricted from Borgs by design is the messenger app, by which the restriction is handled via making the app unavailable for disk transfer. All other apps that are incompatible with borgs are such due to them holding a PDA, not because they're silicons. So this is somewhat redundant at best, and newly restrictive at worst.

**Comment by Zergspower** [comment]
I'm still confused to why borgs on TG cant do Messenger or Crew Manifest, I've never heard a reason that made any sense

**Comment by JohnFulpWillard** [comment]
Borgs can have crew monitor installed onto them but they don't have a PDA because contact to and from them should be through their AI, roboticists have an exception one-way communication with them through the Borg monitor app (with their AI also sees)

**Comment by carlarctg** [comment]
Borgs are the AI's limbs, or at least the station's. Ask the brain to send the limbs your way - not having messenger goes a long way towards keeping the dehumanized image of cyborgs. You wouldn't DM a discord bot, you'd contact the owners of it.

**Comment by projectkepler-ru** [comment]
> I'm still confused to why borgs on TG cant do Messenger or Crew Manifest, I've never heard a reason that made any sense

borg aren't people
simple as

**Comment by Dorsisdwarf** [comment]
I didnt even know borgs could use apps, I thought the robotact panel was just a super clunky and slow-loading version of the old robot panel.

**Pull request closed without merging**
