### PR TITLE
Replaces borg detonation with hard-locking

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Removes borg detonation for anyone using the robotics console, except for malfunctioning AIs and the borg itself.

Adds a new hardlock variable that switches on when a human locks a borg. Humans can always lock and unlock borgs freely, but AIs cannot unlock a borg that was locked by a human.

Oh, and the actual order of buttons was changed a bit to group better under an issilicon() check.

## Why It's Good For The Game
Detonating borgs is done for three main reasons;
* When the crew has reason to believe the AI is subverted or malf, and cannot risk leaving the borgs locked
* When the AI is malf and wishes to use the borg as a bomb (or a borg themselves wants to do similar)
* When some other antag is murderboning and wants to add the borgs to their kill count (and/or doesn't want the borgs to try and stop them).

Being suddenly out of the round by a player you can't even see is never fun, and more so when you had no reason to believe it was about to happen. By including the hardlock function, I give the crew their tool against rogue borgs, and by allowing detonations under certain conditions, I allow for malf AIs or borgs to sacrifice in a pinch. This will only negatively affect unrelated antags that wanted to delete the borgs for whatever reason, and Captains that jump at any chance to validhunt anyone.

Locking the borgs down over blowing them up is better for the crew in the long-run; a rogue borg can be desynced and hit with law boards to make it help the crew, and an emagged borg can be deconstructed and its MMI placed into a fresh shell. 

## Changelog
:cl: Zxaber
balance: AIs can no longer unlock a borg that was locked by a human
balance: Only Malf AIs and the borg themselves can now detonate a borg.
spellcheck: The lockdown/release button text now uses light-green instead of green.
/:cl:

I suppose we'll need a new line for the RD action figure, too.

### CODE REVIEW

**Comment by adamkad1** [comment]
coooool

**Comment by plapatin** [comment]
whats the borg supposed to do if they get locked indefinitely and nobody wants to unlock them

**Comment by zxaber** [comment]
Probably whatever they do when it happens currently.

**Comment by habader** [comment]
>buffing borgs

**Comment by YakumoChen** [comment]
So does this replace detonation with a stronger lock mode or just remove detonation entirely

**Comment by zxaber** [comment]
Functionally, borg detonation is removed for most players. The hard-lock is appled automatically if the person locking the borg is not a silicon.

Hard-lock is intended to be the new solution for any situation where you would normally detonate the borg (outside random antag just blowing them because they can). Once hard-locked, the silicons can't directly do anything about it.

**Comment by wesoda25** [comment]
Just call it removal of blowing borgs because thats all this really is.

**Comment by zxaber** [comment]
The point is I'm adding a replacement. What difference is there between a blown malf borg and a perma-locked one? That you didn't get to kill them?

The perma-locked borg can be brought to the crew's side against the AI. Or just leave them locked and all they can do is complain, but at least the station isn't full of hull breaches from exploding borgs.

**Comment by PKPenguin321** [comment]
Oh boy let's make consequences of our actions less severe and lower drama and tension woopee

**Comment by CRITAWAKETS** [comment]
nobody had any issues though, why are you making this

**Comment by wesoda25** [comment]
Expecting that there will always be people on hand with both the tools and knowledge to convert malf borgs is unrealistic. The crew needs a tool that they know will eliminate the danger of a rogue borg. The two arguments that all borg mains use for how retardedly OP borgs are emps/flashes and robo console. If you take the power of the second away and replace with literally nothing, you have achieved nothing but buffing borgs.

**Comment by zxaber** [comment]
@CRITAWAKETS 
It's something I wanted to do for a while and just never got around to it.

I've never liked remote attacks that can kill. It's the same reason I hate hivemind's heart attack button (and the mind-control when used for similar reasons).

@wesoda25 
I'm not removing the outcome, just changing how it works. _No silicon can remove a hard-lock_, so if you lock them down, that's it. If no one bothers to reset them, then they just stay locked and ultimately can't do anything, which is about the same as them becoming a ghost. And because they don't explode, they don't leave holes in the floor to vent out hallways.

You're acting like I'm removing the whole feature.

**Comment by YakumoChen** [comment]
Actually I don't like this. Making borgs explode can be a good way to punish emaggers that stick around near the borgs they emag, since you can blow the rogue borg and take their emagger with it.

**Comment by zxaber** [comment]
While that's true, you're pretty much just hoping that the borg isn't off doing errands for the emagger (or hanging around something important like cloning). If you lock them down and find them, you can re-borg the MMI and order it to tell you the traitor's name.

**Comment by YakumoChen** [comment]
Yeah but blowing up a traitor is fun especially when everything has gone to shit to the extent that it's not feasible to just rebuild the borg.

**Comment by wesoda25** [comment]
You are removing the whole feature. The point of borg blowing is a messy way of immediately eliminating a threat. It doesn’t require cooperation, it doesn’t require teamwork, it just requires sufficient ID access. You’re proposing silicon hugbox in which it requires numerous people working together to do what used to be done with the click of a button. Just locking down a borg puts so many factors into play, you first need to lock it, then get to it, then dismantle/unsync it. During all this time anyone could unlock the borg, and for it to be successful at all you’ll need multiple people working together, which just isn’t possible in certain rogue borgue scenarios.

**Comment by wesoda25** [comment]
Alternatively give RDs a device that can blow locked down borgs (so that you still need to have a working console). Makes it a bit harder to blow and gives RD some form of usefulness.

**Comment by zxaber** [comment]
I could do that.

**Comment by 4dplanner** [comment]
My problem with this is it makes "hardlock" too cheap. Blowing a borg is a costly decision - you damage both the station and any nearby crew. "Hardlock" is comparatively free

**Comment by zxaber** [comment]
That's true, I suppose.

Anyway, when I was writing out the code for this, I saw it more as a buff to the crew rather than to the borg. Giving the crew a means to deal with rogue borgs in a way that the AI can't undo while also allowing for "de-conversion" to gain an extra ally sounds more helpful to the crew; it doesn't really help a borg fight or kill more. But if people are going to see it as a borg buff, it's just going to be used as reasoning for future borg nerfs, so I guess it's not worth it.

**Comment by adamkad1** [comment]
shame

**Comment by Detective-Google** [comment]
> Oh boy let's make consequences of our actions less severe and lower drama and tension woopee

unga how dare I not be able to instakill this silicon across the map because it read the silicon policy to me!!!!#!@#@#! borg buff remvoe borg!

Let's all be honest, borg blowing happens in 3 circumstances
1. Malf AI
2. Shitter smells a hint of rogue and blows borgs (*and never get punished for it, valid or not by admins*)
3. Tot wants to rid the station of an enemy

This PR makes it so that silicons on their own have 0 way to get unlocked, all this does is stop it from being an instakill on people.
because that's what you're blowing, *other players*

Would it be nice if sec had an implant that just detonates people on the press of a button? (might could be done with chem implants , but those have loads of caveats of their own) 
I'd say this PR could be more balanced, by making the "hard lock" cut the borg's module wire, meaning they have to get someone to manually open them, take the battery out, access the wires, and mend it, all whilst not being able to use modules.

**Comment by PKPenguin321** [comment]
seethe

**Comment by Detective-Google** [comment]
> seethe

you'd seethe too if the captain decided to do crewsimov or whatever and shitsec extraordinaire decides to detonate all the cyborgs on the map every 3 rounds because they're not perfect asimov.

**Pull request closed without merging**
