### PR TITLE
Stunprods can be make with igniters OR wirecutters

### PR DESCRIPTION
**Pull request by Buggy123**
Seriously why was this even changed in the first place?

### CODE REVIEW

**Comment by Zilenan91** [comment]
Razharas wanted to nerf them so he made them need igniters

**Comment by Cheridan** [comment]
You should make it change the sprite, right now the sprite visibly has an igniter on it.

**Comment by PKPenguin321** [comment]
Wrong way of doing it, I was gonna have one be the child of the other, make them have separate sprites, make only the igniter one spark, make only the wirecutter one upgradable into a teleprod, etc

**Comment by Buggy123** [comment]
That's a bit too much for me to easily do, do you want me to close it PK and let you do it?

**Comment by Buggy123** [comment]
Closing this to let PK do it instead.

**Pull request closed without merging**
