### PR TITLE
Tram uses looping sounds from horizon

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Sounds from hrzntal/horizon#434

## Why It's Good For The Game

Really gives life to it from what i've seen, it's no longer just floaty object

## Changelog

:cl: Tralezab + Azarak
add: Tram now has looping sounds
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Where did the sounds come from?

**Comment by Timberpoes** [comment]
Directional audio on these is suffering.

When you're stood directly to the left or the right of the tram, the entire opposite audio channel is muted.

When you're above or below the tram it's much more tolerable but the way we balancing the left/right panning of the audio when directly to the left/right of the tram is uncomfortable to listen to. Even worse if you're not wearing shoes.

When listening from here
image
when moving East, the entire left audio channel plays nothing, the right audio channel plays both footsteps (fucking hell) and the looping audio. When moving West, the left audio channel only plays the footsteps and the right audio channel only plays the audio.

This is really, really uncomfortable to listen to.

**Comment by tralezab** [comment]
@optimumtact 
image

**Comment by Mothblocks** [comment]
can we get a video of how this sounds in action  it's a lot easier than playing the start loop and end on their own

**Comment by Mothblocks** [comment]
needs pictures but its actually what i said above

**Comment by tralezab** [comment]
i can't figure out how to solve the surround sound problem. I really don't want to `SEND_SOUND`

**Pull request closed without merging**
