### PR TITLE
Makes ghost hud only animate on mouseover

### LINKED ISSUE #12707: Ghost hud icons are animated
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

### PR DESCRIPTION
**Pull request by Razharas**
Makes ghost hud only animate on mouseover
Fixes #12707 
Fixes https://github.com/tgstation/-tg-station/pull/12709

### CODE REVIEW

**Comment by Giacom** [comment]
Not sure about OnMouseOver. I remember carn removing these methods as she found that they caused extra overhead to BYOND as it will always check it on everything if it is used once in the codebase. I will need to find the discussion for this, I think it was on GitHub.

**Comment by MrPerson** [comment]
Every object that defines any of the MouseEvent() procs will generate network overhead on that object for the event defined. Lummox claims that only that object will send the information and only for the defined objects, for what it's worth.

**Comment by Giacom** [comment]
Sounds good then.

**Comment by RemieRichards** [comment]
@Giacom it's also a *tiny* bit late to protest ```MouseEntered()```, as it's used to pop open GoonTooltips on Screen alerts and Action buttons.

**Comment by Giacom** [comment]
Yeah I missed that one.

**Comment by Incoming5643** [comment]
I'm still not wild about having to have two full color clowns on my screen at all times.

**Comment by MrPerson** [comment]
Then we can make the non-mouseover'd ones black & white.

**Pull request merged**
