### PR TITLE
Cool Sunglasses

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Changes various Sunglasses sprites. Simple as that.

Screenshot 2023-07-01 235331

Also included a new sprite for Thermal Implants which still used the old box sprite.
## Why It's Good For The Game

Some of the Sunglasses sprites were just kinda... bad, so I decided to change that. Included are a new "aviator" variant that serves as the Bartender's new sunhud glasses.
## Changelog
:cl:
Image: New Sunglasses Sprites
Image: New Thermal Implants Sprites
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
I'll be honest, the checks preview is so small I can barely tell what was even changed. Was it just a color change?

**Comment by Youtubeboy139** [comment]
> I'll be honest, the checks preview is so small I can barely tell what was even changed. Was it just a color change?

Technically, yes, actual shape of a sunglasses hasn't been changed save for the new addition of the aviators

**Comment by Helg2** [comment]
Old medsunglasses were cool tho

**Comment by atlasle** [comment]
could you close this and open a PR with onule's original sprites

**Comment by Youtubeboy139** [comment]
> could you close this and open a PR with onule's original sprites

These were separated for a reason

**Comment by dragomagol** [comment]
image

Why were the static glasses removed?

**Comment by Youtubeboy139** [comment]
> Why were the static glasses removed?

Forgot to reply to this

Fixed it, was removed by accident

**Pull request merged**
