### PR TITLE
Revert "3/4 sprite boxes REDONE"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#24307

@Militaires 

Valid arguments against forced 3/4ths perspective (a work in progress) (stolen from @Incoming5643 )

1. It's terrible at showing depth. All you get is that wacky area at the top of the sprite. There's no context for thickness over the length of the sprite, meaning it only works on things that have a consistent thickness over the entire body of the sprite. Anything else is robbed of information.

2. It's more important to show what a sprite looks like in three dimensional space than how it might logically look from a specific viewpoint. SS13 is always going to be graphically lacking so letting people properly imagine what scenes playing out in game might look like is important. Knowing how something looks because you played before the sprite was changed is not a proper excuse.

3. There actually already is a fairly well established ruleset for how machines/structures look, it's a slightly offset isometric perspective pointing southwest to northeast. The diagonal showcases depth and gives a stronger impression of how things might actually look, the orientation being left up to the player.

4. Some of the PRs that added these sprites were written to be intentionally inflammatory, and I'm still not entirely sure this isn't just an extremely high effort shitpost.

5. The old style of sprites is direction agnostic, but 3/4ths sprites only really work well when they're "facing" south.

6. Creating 3/4th item sprites makes them blend into 3/4th machinery and structures. A rough shorthand currently is that if an item is shown face on, it's something you can pick up, and if it's show at the iso angle common to structures/machinery it's something you can interact with. This isn't true 100% of the time, but it's fairly consistent.

7. Creating 3/4 sprites are intrinsically trickier than allowing a more relaxed standard. This is a game that has trouble finding people to make sprites, we can't really afford to add a big barrier to entry. Not everyone is gonna know how to project a light source or understand how to angle things. Either less people will sprite or the people that do sprite might do a poorer job of it.

8. You cannot enforce a standard for sprites unless you commit to never leaving. I don't want that for you :(.

9. Creating a unique visual style means we can never port sprites from any other codebase (except maybe the goon leak) ever again.

10. Creating a unique visual style puts us at odds with every other codebase except goon. People like familiarity, goon is a dying server, we want to be a part of that?

### CODE REVIEW

**Comment by Militaires** [comment]
>mso writes a paragraph to revert a pr that didnt even spend a day and the server bot didnt even update and apply the pr yet.

fam just give it a while before.. this..

**Comment by MrStonedOne** [comment]
If you read it you would note that i didn't write shit, i stole it from incoming

**Comment by kevinz000** [comment]
The main point for me is "Why the fuck did a PR with 17 downvotes and 4 upvotes get merged anyways"? Separation memes? Just because Wjohn wants it that way? The old sprites were fine.

**Comment by Militaires** [comment]
you still read incoming's shit and compiled them into bullet points.

**Comment by MrStonedOne** [comment]
no, I copy and pasted, as is.

**Comment by kevinz000** [comment]
why are we still doing sprite changes that the majority of the players don't like? as for where's the evidence I even made a forum poll and there was a 2/3rds supermajority against the new sprites last I checked.

**Comment by Militaires** [comment]
@kevinz000 same with toolboxes and no one gives a shit now

**Comment by Cheridan** [comment]
>5. The old style of sprites is direction agnostic, but 3/4ths sprites only really work well when they're "facing" south.

Not true. New sprites are as agnostic as the old ones. Which is to say, neither are agnostic. They all faced south (though the old ones did so at a slight tilt)

>7. Creating 3/4 sprites are intrinsically trickier than allowing a more relaxed standard.

Not really.

>9. Creating a unique visual style means we can never port sprites from any other codebase (except maybe the goon leak) ever again.

No it doesn't. We just port them as-is and then change them later if we want.

**Comment by MrStonedOne** [comment]
\>i mean you guys dont seem to like them but little to none of you told me WHY they're bad or just gave me reddit downboats

>\>mso writes a paragraph to revert a pr that didnt even spend a day and the server bot didnt even update and apply the pr yet.
>
>fam just give it a while before.. this..

Asks for proper feedback, bitches about how the person spent too much time giving proper feedback

Holy fucking shit are you cancerous.

**Comment by Iamgoofball** [comment]
just going to talk about 10

point 10 is fucking bullshit

we do not pander to the "IT WAS FINE BACK IN '85" bullshitters

we should obviously bring stun gloves back people were used to it

# daily reminder that everyone everywhere whines about new things, and "old is new again" is the current hip retarded meme that is causing political instability via trump's "make X great again" slogan appealing to the masses who think we can reach the old '50s pax americana that was a result of us being the only economy left standing

related: https://www.youtube.com/watch?v=Z9FfI4-oRDo

**Comment by Cheridan** [comment]
@kevinz000 >why are we still doing sprite changes that the majority of the players don't like? 

https://github.com/tgstation/tgstation/pull/24348
People really liked the new vending machines, the PR had unanimous approval. 
The big contentious change was the toolboxes and that was mostly just about the size.

**Comment by Militaires** [comment]
@MrStonedOne giving proper feedback on a pr that the players didnt even see ingame yet.

and hence i dont bother to give you proper feedback in return

**Comment by Iamgoofball** [comment]
@Cheridan 
it wasn't about the size

any particular argument is always just a hoax

they're driving you away from the real point with bikeshed style arguments

they just don't like change

**Comment by MrPerson** [comment]
I don't think this is an appropriate place to bring up politics.

**Comment by dannno** [comment]
I was pretty down in the dumps until someone showed me a player poll from a few days ago or something about how people felt about toolboxes and the results were mostly "Like the new toolboxes" and "Don't care"

I wish you guys wouldn't get so heated over something so goofy
it's a game 
I'm no longer working to "enforce" a perspective change, I'm just going to sprite things that I want because I like it
calm down and stop screaming at each other, it's embarrassing

**Comment by Iamgoofball** [comment]
@MrPerson 
the "everything old is new again" shit effects the entire world and society as a whole, and directly impacts this situation

**Comment by Militaires** [comment]
if you jizz in a milkshake does it become a protein shake

**Comment by Iamgoofball** [comment]
i bet if i were to PR donut station right now it'd get unanimous approval because it's "just like the old days"

**Comment by MrPerson** [comment]
I didn't say it was off topic, I said it's probably better to stay clear. I mean you do whatever you want, I'm just concerned someone really strongly pro-Trump/anti-Trump will show up and take umbrage or point out how that's not related at all.

**Comment by Iamgoofball** [comment]
fair point, it's just the biggest example of it in recent history I can give

**Comment by Iamgoofball** [comment]
I guess another good one could be Coal power trying to make a comeback and failing but that's only known if you're following the rust belt

**Comment by Kromgar** [comment]
Look i like a lot of the 3/4ths sprites but these boxes look like fucking garbo

**Comment by Yoshmaster** [comment]
Support for the new sprites actually seems very positive when I asked randomly.
PRs have selection bias on full blast, so it's a little disingenuous to say that everyone hates the new sprites.
I mean, this could be because danno shitposts too much and you don't like him that much, but he did work hard on these, y'know?

**Comment by MrStonedOne** [comment]
"the new sprites"

**Comment by MrStonedOne** [comment]
There are alot of "the new sprites"

some better then others.

**Comment by Militaires** [comment]
WE ARE **ENFORCING** THE 3/4 PERSPECTIVE JUST LIKE THE GERMANS ENFORCED THE JEWS TO WEAR THE DAVID STAR ARMBAND.

**Comment by WJohn** [comment]
I'm not sure how much I'm allowed to say since I'm obviously biased in favor of 3/4th (and am art director, for whatever bullshit that's worth).

I'd just like to say that having art standards is nice, helps the game feel more connected and polished rather than a total mish-mash of inconsistent visuals.

**Comment by Militaires** [comment]
on the topic of boxes the latest version is wj's edit not me

@wjohn i just threw u under the bus hahaahah good luck dealing with 20 crybabies they're your problem now.

**Comment by Incoming5643** [comment]
SS13 is a patchwork project of the efforts of hundreds of people. High consistency is counter to its entire existence. This point isn't even a good argument but there it is.

**Comment by RussellTalbott** [comment]
mso is your brain turned on or are you too _weeded out on the pot smoke_

**Comment by Yoshmaster** [comment]
I mean, they made the new sprites to look better, I don't think they're causing a fascist uprising or anything

**Comment by Militaires** [comment]
@yoshmaster you have no idea how close i am to sending you to gulag

**Comment by Yoshmaster** [comment]
pretty sure this is 90% because danno is annoying so just give him an indian burn or something

**Comment by Militaires** [comment]
you guessed right

**Comment by Yoshmaster** [comment]
pick danno up and just throw him in a literal trash can and keep his good sprites
then get him to make more sprites and donkey punch him

**Comment by Kromgar** [comment]
Danno's sprites are awesome. @Militaires box sprites are shit. They look really bad

**Comment by SgtxRootbeer** [comment]
this, i like, MSO is doing something right for once. now, see if you can revert the icons for the vending machines.
toolbox is meh, as pick-up-able items should be 3/4th, but structures like welding fuel tanks are a no.

**Comment by Militaires** [comment]
@Kromgar last edit was wj im throwing him under the bus now - and you're still not giving me any reason as to why it's bad so it can be improved you wanker

**Comment by Kromgar** [comment]
@Militaires They look waaaay to fucking big

**Comment by Militaires** [comment]
@Kromgar did you know they're actually not that much the same dimensions from the original ones?

**Comment by Yoshmaster** [comment]
keep the toolboxes but get rid of the station
get rid of ian BUT KEEP AIRLOCK SPRITES

**Comment by MrStonedOne** [comment]
they look too big, and the perspective requires too many compromises compared to the old perspective.

**Comment by RandomMarine** [comment]
Why don't we just accept sprites based on whatever looks better and not give a flub about pushing perspectives?

New toolboxes look a bit better than the old ones.
Old boxes looked better than the new ones.

**Comment by Militaires** [comment]
@RandomMarine ABSOLUTE MADMAN GET THE FUCK OUT OF HERE WITH THAT CRAZY TALK NIGGA

**Comment by WJohn** [comment]
If it's a matter of picking better sprites, I totally understand.

I like the new boxes better than the old ones, but I'm biased towards 3/4th and that gets big marks in my book. Perhaps a second art director will be needed who's not biased towards 3/4th and can review sprites on their own merit would be good, too.

**Comment by Jordie0608** [comment]
The sprites aside, @WJohn for posterity it's best not to merge things because of, abridgedly what i recall from yesterday, "Despite the negative feedback I prefer them" since it precipitates reactions this like.

**Comment by Aloraydrel** [comment]
I never understood the appeal to 3/4th since it's a ugly perspective 

though the models do look a lot better.

**Comment by ExcessiveUseOfCobblestone** [comment]
Goofsprites, the future.

**Comment by WJohn** [comment]
3/4th gets big appeal from me largely because it works very well with topdown sprites like our floors (think FTL but not as intense). It's used in a ton of games (alongside isometric but we can't do that) for good reason.

**Comment by Kromgar** [comment]
These look like fuckign ovens

**Comment by Niknakflak** [comment]
I was wondering when mso would do this

**Comment by Incoming5643** [comment]
@WJohn I know this might sound somewhat absurd but I never saw our floor tiles as being "top down". I never took it so literally I guess. It's more just a representative thing to me.

**Comment by XDTM** [comment]
immagine

3/4 can be good if sprited properly in my opinion. Also, if i had to pick between equal-quality sprites in the old and new perspective i'd pick the new one.

As for that PR, don't forget that it was initially much worse, which caused it to accumulate 👎 which weren't removed after the sprite was redone.

**Comment by CPTANT** [comment]
3/4 on the boxes just fucks up the perception of depth, those 3/4 boxes all look flat to me.

**Comment by XDTM** [comment]
I feel like it could be solved with shading, but i don't know enough about sprites to tell.

**Comment by Militaires** [comment]
why is this still active most people on the server didnt give a shit and those that did were memeing with REEE CHANGE IN MY SPESSMAN

**Comment by CPTANT** [comment]
Ah, another step on  the famous "attempt at trying to force things through peoples throats" roadmap.

1. "They will like it once its merged!"
2. "Nobody said WHY they dislike it so I will merge it anyway"
3. "People playing the game weren't pissed off enough to complain (except the ones that did)"
4. "They just don't like change!"
5. "They will stop disliking it after they get used to it!"
6. "well we put so much time and effort into the change, we can't revert it now"

**Comment by Militaires** [comment]
@CPTANT but no one actually said why it's bad people said it's too big and it was sized down, then they resorted to "it's bad"

maybe if you actually gave constructive criticism instead of sitting and saying "it's bad" instead of whining when it's merged (and still not giving enough reason as to what makes it bad!)

this entire post is just mso trying to say the concept of 3/4th itself (and not the sprites) is bad without actually giving reasons, effectively saying nothing in the biggest amount of words possible.

even if his points werent shit (ahem, point 10), why is starting by reverting a SINGLE pr that makes fucking BOXES 3/4th instead of the bigger shit like vending machines which were sweet tbh.

**Comment by Kromgar** [comment]
@Militaires 

They don't look like small boxes that fit in a backpack they look like fucking ovens they just look off i don't know how to explain it they just look retarded.

**Comment by WJohn** [comment]
CPTANT you may not like this, and I'm sure most people don't like to hear it either, including the coders but:

Coders put whatever they want into the game. They change things on a whim based on their own individual desires. The only reason why things get denied is if there is something seriously wrong or if there is OVERWHELMING negativity with the proposed change. Otherwise any feature, sprite, or map edit gets in. 

Changes will be "forced down your throat" not because we're trying to piss you off or anything, but because being a coder for ss13 involves making whatever changes you want, despite the objection of some (but not everyone). Players are quite literally often never even a factor on changes because they never speak up, you HAVE to fight changes to prevent them from happening, and if you fight EVERY change then you'll look like the kind of guy who wants everything to stay stagnant no matter what.

SS13 changes over time because there is a group of people who decide it should. The same people also keep the game functioning, bug free, and smooth. Accept that.

**Comment by Militaires** [comment]
@Kromgar because of you my child im gonna go get the old one and the current ones and compare friend.



WOW THEY'RE SO HUGE autist.

**Comment by Militaires** [comment]
BONUS ROUND: whiny crybaby compilation /OR/ PEOPLE SAYING NOTHING WHILE TYPING.

chrome_2017-02-25_17-31-51
chrome_2017-02-25_17-32-03
chrome_2017-02-25_17-32-11
chrome_2017-02-25_17-32-38
chrome_2017-02-25_17-33-15

**Comment by Kromgar** [comment]
THE PERSPECTIVE MAKES THEM LOOK HUGE. 
HOW DO YOU NOT UNDERSTAND THIS.


LOOK I DEFENDED THE TOOLBOX SPRITES BECAUSE BUT THESE BOX SPRITES LOOK LIKE GARBAGE

**Comment by WJohn** [comment]
These sprites could very well be improved. The box sprites could be redrawn to look more rounded, or just be smaller, or something. Maybe ausops can show us his thought process (if he wants to redraw those).

**Comment by Militaires** [comment]
i could make them smaller if you guys are really triggered by their size at this stage

but i feel as if even if i did you guys wont be happy

**Comment by Hatfish** [comment]
The new tanks look great, the new machines look fine, even the new toolboxes look alright, but the new boxes just look bad.  I think they're too two-dimensional, really.  As said earlier, they just look completely flat right now.

**Comment by CPTANT** [comment]
"The only reason why things get denied is if there is something seriously wrong or if there is OVERWHELMING negativity with the proposed change."

*PR, gets 4 ups and 20 downs, merges anyway*

I think the overwhelming negativity is where we are now.

**Comment by WJohn** [comment]
As has been pointed out multiple times, most of those thumb downs (including the now really good looking welding tanks PR) have not been removed after the sprites were tweaked. They could be tweaked FURTHER, sure, but the data is not as accurate as you'd like.

I'm sure that if people for some reason have some whiplash against the welding tank changes (and of course they will, even if it's ausops) they'll point out how that has like 15 downs even though those are now out of date.

**Comment by CPTANT** [comment]
Sounds dandy.

Still I would like to point out that revert PR has 16 thumbs up and 4 down and that is most certainly after the tweak.

**Comment by Militaires** [comment]
im gonna resprite the boxes in isometric view

**Comment by calzilla1** [comment]
GOONBALL YOU FUCKS ARENT CHANGING YOURE R E P L A C I N G

**Comment by BeeSting12** [comment]
actually the boxes are ugly

**Comment by TrustyGun** [comment]
if we do remove these boxes, can we at least keep the overlay system? i do think it is quite useful and makes it easier to do boxes in the future.

i don't think we have to do that yet though, I decided to try my hand at modifying the boxes and addressing some of the complaints that we have about them (flat, lost detail, etc)

**Comment by TrustyGun** [comment]
Pic:

image

**Comment by WJohn** [comment]
Cool. Those look pretty neat. I'd approve em if you made a PR on it.

**Comment by optimumtact** [comment]
you need to remake this now that the other sprites have gone in if you're still in a titty twisted mood.

**Comment by optimumtact** [comment]
or ping me if you update this one and I'll reopen it

**Pull request closed without merging**
