### PR TITLE
Makes armor of various sec headgear consistent

### PR DESCRIPTION
**Pull request by PKPenguin321**
By buffing every headgear type's armor values to match the cap. Also adds bomb protection to the cap, since it was the only one without it. The magic of consistency!

:cl: PKPenguin321
tweak: The armor values for security helmets, caps, and berets have all been brought in line. Consequently, helmets and berets are a teeny bit better, and caps now have the slight bomb protection that the other two had.
/:cl:

### CODE REVIEW

**Comment by Steelpoint** [comment]
You do know this means that sec headware is now stronger than sec armour vests? Hell this puts the helmets/hats on par with the HoS's uniform due to how low the defence values are.

I don't mind this change in the name of consistency (and fuck off with the "b-but its a hat no armour guys"), but this is still inconsistent with the base bode armour. ,

**Comment by PKPenguin321** [comment]
i mean if you wore the cap it already was stronger than the vests, but you had to be able to read code to know that

**Comment by Steelpoint** [comment]
To be fair this is what happens when people make sweeping changes to the armour values and no one else can get in due to the fallout.

**Comment by The-Albinobigfoot** [comment]
>muh secret hat strat is dead

Please.

**Comment by ToadStar** [comment]
Would it be too much to ask for the armor vest and winter jacket/winter hood to also get updated to match the hats' armor values? Kinda insane that a cloth beret is more armored then a kevlar vest.

**Comment by PKPenguin321** [comment]
>cloth

its nanofiber you dip

**Comment by KazeEspada** [comment]
PUT YOUR DAMN HELMET ON!

**Comment by ToadStar** [comment]
Even if it is nanofiber, wouldn't the vests be made of the same thing? :V

**Comment by CosmicScientist** [comment]
Now to reference Starship Troopers endlessly.
:+1: for finding this and making them all equal given the state they were in.

**Pull request merged**
