### PR TITLE
Lings now have biodegrade by default

### PR DESCRIPTION
**Pull request by ghost**
_cuffs transforming monster_

_monster can't melt or escape cuffs_

:cl: More Robust Than You
balance: Lings now have biodegrade by default
/:cl:

### CODE REVIEW

**Comment by RemieRichards** [comment]
>STOP
>>DOING
>>>THIS
>>>>PLEASE

**Comment by InsaneHyena** [comment]
STOP BUFFING LINGS

**Comment by Repukan** [comment]
Get good.

**Comment by PopNotes** [comment]
for what possible fucking reason would you do this

**Comment by qbmax32** [comment]
stop buffing lings they're already cancer

**Comment by lzimann** [comment]
I'm not particularly good with balancing but holy shit this is a bad idea.

**Comment by Ratvar** [comment]
Make biodegrade drop hands off if you gonna do it and rise cost?

**Comment by KingPhilipIII** [comment]
Make lings able to lose limbs on command. Hilarious and if you can magick your cuffs off you're still armless.

**Comment by FantasticFwoosh** [comment]
How 2 defeat a ling.

Stuff ling inside a box and have your buddy sit ontop of it, ling is lying down and unable to use their armblade & escape. EZ.

**Pull request closed without merging**
