### PR TITLE
Adds in the admin outfit.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

So i was told to make this if i wanted to get an outfit that actually could work on things like radiation. I also gave it a box full of stabilized extracts because those give quite good effects like more speed and regeneration.

## Why It's Good For The Game

Admins can now scream in joy as they torture the masses, and coders can test more things like torturing the masses.

## Changelog
:cl:
admin: There now exists an admin outfit, better than the debug outfit for messing with things. There is also now a box with every single stabilized slime extract.
/:cl:

### CODE REVIEW

**Comment by trerri** [comment]
does it have codersocks

**Comment by CRITAWAKETS** [comment]
> does it have codersocks

this is the admin outfit, not the coder outfit, ya dingus

**Comment by Misdoubtful** [comment]
> > does it have codersocks
> 
> this is the admin outfit, not the coder outfit, ya dingus

Does it get admin toe shoes?

**Comment by coldud13** [comment]
image

**Comment by optimumtact** [comment]
file ./code/game/objects/items/storage/boxes.dm is missing a trailing newline

**Comment by Fikou** [comment]
maybe make the hardsuit a subtype of the jannie ert suit? that one is really simple (doesnt have weird modes like syndie hardsuit), fits in with the theme and has no slowdown

**Comment by Ryll-Ryll** [comment]
I thought we already had a jabroni suit

**Review by Timberpoes — APPROVED** [review]
Love me some admin tools.

**Pull request merged**
