### PR TITLE
Buffs Foam

### PR DESCRIPTION
**Pull request by Iamgoofball**
Been using foam recently, figured out that it isn't applying chemicals very well due to having a longer ish lifetime from the fastprocess foam stuff. Giving it a buff to compensate.

:cl: Iamgoofball
rscadd: Foam now uses it chemicals better, and is way more useful.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Why not buff smoke

**Comment by Iamgoofball** [comment]
Smoke is already good

**Comment by PKPenguin321** [comment]
Yeah why not both

**Comment by phil235** [comment]
As I said in the other PR, this change would make foam with harmful chems LUDICROUSLY OVERPOWERED.

**Comment by Iamgoofball** [comment]
Great, it needs a buff right now.

**Comment by phil235** [comment]
If you're not going to take this seriously, there's no reason for maintainers to take it seriously either.

**Comment by ChangelingRain** [comment]
Did goof listen when I said phil would kill him? No, he didn't.

**Comment by Iamgoofball** [comment]
What the fuck.

**Pull request closed without merging**
