### PR TITLE
Revert "Gasmaks tint and tint calculation update (Oranges approved edition)"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#62947

### CODE REVIEW

**Comment by Burgermancoding** [comment]
you typod the title

**Comment by Pickle-Coding** [comment]
Goodbye gasmak tints.

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=3i2FOyu5rDI

**Comment by SkeletalElite** [comment]
Definitely would like to see this with the FOV changes in,

having both is unnecessary and the FOV changes are a lot cooler.

**Comment by SethLafuente** [comment]
Today is a good day I can wear my drip back as a scientist

**Comment by optimumtact** [comment]
in case you are unaware this will be replaced by gasmask applying an FoV to you (which is also a useful test of how the FoV system plays out in practice)

**Comment by tralezab** [comment]
lets just send it

**Pull request merged**
