### PR TITLE
Contractor baton excluded from TBaton spy bounty

### PR DESCRIPTION
**Pull request by BlitzArde**
## About The Pull Request
The game adds the Contractor Baton to the "global tracker" whatever the hell that is, from what I understand it's what determines the potential bounty item pool, since the contractor baton is a subtype of the telescopic baton; Which of course is not very appropriate considering the baton came from the Syndicate in the first place. The code excludes all subtypes of the telescopic baton so that we don't get something goofy like this:
aJboHU3
Credit: _shod for the image
## Why It's Good For The Game
When problem is fixed, problem no longer bad.

Originally I wanted to just add a custom text saying what a contractor baton is instead of the telescopic baton, but was told it's not a good idea. Boowomp. Anyways, stealing back a contractor baton from the Syndicate who just GAVE someone that baton is a little weird I suppooosseee.....
## Changelog
:cl:
fix: You may no longer submit, or obtain, a spy bounty for the contractor baton.
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
> You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

im sorry gbp bot but this is a fiiiix you were soooo close to annihilating someone for gbp debt tho keep going you'll get 'em one day <3

**Comment by optimumtact** [comment]
This isn't really a fix because this may not be a bug, in fact it's possible it's a legacy from the time when contractors were not the same as syndicate prog tots

**Comment by IsaacExists** [comment]
> This isn't really a fix because this may not be a bug, in fact it's possible it's a legacy from the time when contractors were not the same as syndicate prog tots
> 
> but since the end result is mostly harmless i guess it's fine.

I reckon it's more-so an oversight. Despite not exactly ruining any gameplay mechanics, it does notify you if someone on the station has a contractor baton (Potential metagame material) and also allows you to submit a contractor baton in the stead of the telescopic baton theft objective, which I'm almost positive wasn't intentional.

**Review by Mothblocks — APPROVED** [review]
Real fix IMO is that contractor baton shouldn't be subtyped under telescopic baton

**Pull request merged**
