### PR TITLE
Harvest liver traitor objective

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

The intrusive thoughts won and I had to make this a traitor objective.
Jobs with easy access to surgical tools can have this as a roundstart objective, anyone else will need 30 minutes traitor progression.
givemeyourlvier

(I originally wanted to make this a more generalized "harvest organ" objective but decided against it. Maybe I should have done that?)

## Why It's Good For The Game

Eyesnatching is a pretty good and fun objective, but I think this is another funny objective that maims victims in a significant way.

## Changelog

:cl:
add: Traitors now have a new, very rare objective: Stealing livers.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
This should be in the same category as assassinate, kidnap, and eyetheft
But on that topic, it's not sufficiently different to eye theft that this seems like it justifies its existence, what is additionally engaging about it compared to what's already there?

**Comment by ChungusGamer666** [comment]
> This should be in the same category as assassinate, kidnap, and eyetheft But on that topic, it's not sufficiently different to eye theft that this seems like it justifies its existence, what is additionally engaging about it compared to what's already there?

Eyesnatching gives you a tool to easily accomplish this feat. 
This objective basically requires you to get surgical tools to do the thing, unless you want to beat the hell out of the body until every organ falls out. 
So yeah, the same thing, but slightly harder and rarer.
It's pretty much in the same category since it's a subtype of /datum/traitor_objective/target_player. It should not be possible to get eyesnatch and harvest liver at the same time.

**Comment by ChungusGamer666** [comment]
I have no clue how the hell all this fancy nu-traitor code works and probably fucked something up, there is a reason this is a draft. 
Be extra careful with this one, maintainers. Smiley face.

**Comment by ChungusGamer666** [comment]
Hmmm, you know what, I'll generalize this. It's more interesting if it applies to any organ (and I can make funnier fluff text for it).

**Comment by Nukechickenu64** [comment]
reminds me of how i would just take organs off the floor and eat them when there's no chef that round, really like this idea cause its unfortunate you never really get to feel actual peril when kidnapped, you're either gonna die or be converted by something, this incorparates another horror, the fear of losing all the fun party times getting drunk

**Comment by KittyNoodle** [comment]
> > This should be in the same category as assassinate, kidnap, and eyetheft But on that topic, it's not sufficiently different to eye theft that this seems like it justifies its existence, what is additionally engaging about it compared to what's already there?
> 
> Eyesnatching gives you a tool to easily accomplish this feat. This objective basically requires you to get surgical tools to do the thing, unless you want to beat the hell out of the body until every organ falls out. So yeah, the same thing, but slightly harder and rarer. It's pretty much in the same category since it's a subtype of /datum/traitor_objective/target_player. It should not be possible to get eyesnatch and harvest liver at the same time.

alternative: just stab the guy in the stomach like 20 times

**Comment by ChungusGamer666** [comment]
@KittyNoodle acknowledged in the original comment yes

**Comment by Vect0r2** [comment]
This feels just like sleeper surgery, and ehh I don't really like surgery objectives. It feels like I have to go out of my way to do it.

**Comment by Wallemations** [comment]
Honestly eyetheft makes me way too uncomfortable and confused, while an objective to steal the liver is practically the closest thing we can get to getting your kidneys stolen and sold on the black market.
I'd prefer as a replacement tbh but I know that's probably not the most popular opinion 
I just think eye-gore is gross and get squeamish over it

**Comment by ChungusGamer666** [comment]
will reopen this at a later date when i rework it properly and shit

**Pull request closed without merging**
