### PR TITLE
Fixes falsewall letting through air.

### LINKED ISSUE #37290: Falsewalls process atmos but only if they're closed....
Title.

@Robustin maybe?

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #37290

### CODE REVIEW

**Comment by YakumoChen** [comment]
@AnturK I remember this specifically not being a bug, I remember this was explicitly PR'd at some point that false walls block air.

**Comment by AnturK** [comment]
This doesn't change anything with that.

**Comment by YakumoChen** [comment]
Oh, maybe I'm reading the issue wrong then.

**Comment by AnturK** [comment]
It just wait with adjacent turf update until density actually changes (after the animation)

**Review by Cyberboss — DISMISSED** [review]

**Comment by Iatots** [comment]
So it's actually "fixes falsewalls not letting through air when open"?

**Pull request merged**
