### PR TITLE
Fixes random failure in cleanbot pathing

### LINKED ISSUE #71493: Cleanbot reads a lot of null values
**Steps to reproduce**
1. Start the server choose map metastation[from my experiments don't know about other maps]
2. Observe the server log for some time maybe 5 to 10 minutes
Screenshot (9)

Don't know the exact conditions when this occurs i just happened to randomly check my log. I'll post more details when i find them.

### LINKED ISSUE #71628: Flaky test failure - Cleanbots are making 0 timers
Flaky tests were detected in [this test run](https://github.com/tgstation/tgstation/actions/runs/3582080689/attempts/1). This means that there was a failure that was cleared when the tests were simply restarted.
Failures:
```
[09:44:44] Runtime in stack_trace.dm,4: addtimer called with a callback assigned to a qdeleted object. In the future such timers will not be supported and may refuse to run or run with a 0 wait (code/controllers/subsystem/timer.dm:583)
  proc name:  stack trace (/proc/_stack_trace)
  src: null
  call stack:
   stack trace("addtimer called with a callbac...", "code/controllers/subsystem/tim...", 583)
   addtimer(/datum/callback (/datum/callback), 0, 0, null, "code/modules/mob/living/simple...", 579)
  the Cleanbot (/mob/living/simple_animal/bot/cleanbot/autopatrol): bot move(the floor (86,153,2) (/turf/open/floor/iron), null)
  the Cleanbot (/mob/living/simple_animal/bot/cleanbot/autopatrol): handle automated action()
[09:44:44] Runtime in stack_trace.dm,4: addtimer called with a callback assigned to a qdeleted object. In the future such timers will not be supported and may refuse to run or run with a 0 wait (code/controllers/subsystem/timer.dm:583)
  proc name:  stack trace (/proc/_stack_trace)
  src: null
  call stack:
   stack trace("addtimer called with a callbac...", "code/controllers/subsystem/tim...", 583)
   addtimer(/datum/callback (/datum/callback), 4, 0, null, "code/modules/mob/living/simple...", 579)
  the Cleanbot (/mob/living/simple_animal/bot/cleanbot/autopatrol): bot move(the floor (86,153,2) (/turf/open/floor/iron), null)
  the Cleanbot (/mob/living/simple_animal/bot/cleanbot/autopatrol): handle automated action()

```

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Ok so like, it used to be we would hand back our path immediately after get_path_to

What's happening now is the path is completed, and THEN we have to wait a tick before getting it back
So between the path finishing and our UNTIL resuming, our mob could be deleted

This resolves that issue, wrapping the UNTIL in some qdeleted checks to return a failure response

## Why It's Good For The Game

Fixes #71628. Also fixes #71493, ~~quit using = to set the path it's a setter for a reason 🗞️~~ I FUCKED UP JPS SHOULD RETURN AN EMPTY LIST ON FAILURE NOT NULL

### CODE REVIEW

**Comment by Mothblocks** [comment]
If you make it VAR_PRIVATE does it lint that usage of `path =`? It shouldn't apply to descendants, that's protected.

**Comment by LemonInTheDark** [comment]
wait no shit right
some bots don't use set_path seemingly intentionally. something else is weird here please hold

**Comment by LemonInTheDark** [comment]
yeah we used to return an empty list in a failure case, please hold

**Comment by CapybaraExtravagante** [comment]
there might be some places that do the opposite , have you checked for that?

**Comment by Mothblocks** [comment]
@LemonInTheDark Update?

**Comment by LemonInTheDark** [comment]
Checked over, all looks good except for parrot code (fucking parrots) and a bit of botcode

**Pull request merged**
