### PR TITLE
QOL Buff to Solar power generation 

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request
A mirror of my downstream PR that i want to try here as i'm sure there's overlapping problems

### Solars
I also gave Solars a 2 KW per panel boost to ease the power crunch, mostly giving an incentive to FINALLY setup solars as well as give those not really comfortable pushing the engine past N2 a more reliable secondary source. It is nowhere near enough to power a full station at stock, but if someone wanted to be silly and setup 100 more solars and hope it can stay in optimal power input then all power to them.

The example screenshot below is an optimal position setup of 51, as most engineers know only 1-2 sides of the station at a time are at 'optimal' at any given point so the total input at any time may be far less than this. 

At 51 in perfect conditions:

- Current as-is: 76.5 KW max
- At 2000:  102 KW Max
- At 2500: 127.5 KW Max
- At 3000: 153 KW Max
- At 3500: **178.5 KW Max** - the one chosen

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
Roundstart - 400/400 and Fully Upgraded at 1.6/1.6
image

image

 
image

</details>

## Changelog
:cl:
qol: Solar power generation greatly improved
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
There's no reason to do this when engineers can just build more SMES in game, and they should be encouraged to do so?

**Comment by Zergspower** [comment]
> There's no reason to do this when engineers can just build more SMES in game, and they should be encouraged to do so?

Currently the solution is "hotwire it, it's too much work"

**Comment by optimumtact** [comment]
If there's already another workaround why do you need this?

**Comment by Zergspower** [comment]
I personally enjoy managing power properly, having that ability with upgrades to me makes more sense - given how much higher power demand is the current caps on SMES just aint it anymore

**Comment by optimumtact** [comment]
So build more SMES? I just don't see a justification for this change.

You have multiple ways to manage this in game already
1) build more SMES (if you want to do it properly)
2) hotwire the engine to the grid (the fast, but dangerous way)

The game isn't designed around only ever having exactly 3 SMES and no more.

**Comment by moocowswag** [comment]
Increase it so it caps out at 1k just so its clean.

**Comment by Zergspower** [comment]
originally i had it at a 50% increase, which capped the max out from 800/800 to 1.2/1.2

**Comment by MTandi** [comment]
Solars were fine as a power source on derelicts. 
They fit perfectly between rtgs/portgens and sm/turbine and don't need to go from 1.5 to whopping 3.5 kW per panel.
Right now it is properly balanced against the power usage of light frames.

**Comment by Zergspower** [comment]
> If there's already another workaround why do you need this?

you'd be fine with reducing that down to say a 25% increase? would be a 250/500/750/1MW step then

**Comment by DustanHache** [comment]
> There's no reason to do this when engineers can just build more SMES in game, and they should be encouraged to do so?

the reason this doesn't happen is because building new SMESes is a hassle byond measure. The SMES rooms themselves tend to be tiny and cramped, with their wires going through a wall. Not ideal for modularity. Hotwiring basically becomes a necessity to ensure power supply before tier 3 parts. Even then, that sometimes isn't enough for a basic setup if someone loses their mind and tries to charge multiple bluespace cells.

**Comment by Zergspower** [comment]
> Solars were fine as a power source on derelicts. They fit perfectly between rtgs/portgens and sm/turbine and don't need to go from 1.5 to whopping 3.5 kW per panel. Right now it is properly balanced against the power usage of light frames.

it really isn't - Solars across the board kind of got left behind after the big power rework and this is just giving them a small leg up - even with 51 panels in perfect alignment that's 178KW which really isnt that much when charging 1 sell eats 1MW. This change still slots them between portgens and Sm/turbine without encroaching unless you REALLY wanna build tons of solars. Which to reach 2MW of an N2 SM would be 572 of them

**Comment by DustanHache** [comment]
> > Solars were fine as a power source on derelicts. They fit perfectly between rtgs/portgens and sm/turbine and don't need to go from 1.5 to whopping 3.5 kW per panel. Right now it is properly balanced against the power usage of light frames.
> 
> it really isn't - Solars across the board kind of got left behind after the big power rework and this is just giving them a small leg up - even with 51 panels in perfect alignment that's 178KW which really isnt that much when charging 1 sell eats 1MW. This change still slots them between portgens and Sm/turbine without encroaching unless you REALLY wanna build tons of solars. Which to reach 2MW of an N2 SM would be 572 of them

2 MW is a VERY generous estimate on a n2 engine unless you are jamming in a ton of emitters (which mind you each consume a bare minimum of 2 KW to fire, so a full set of 8 is shaving off 16 KW minimum from that estimate, and closer to 40 KW if using tier 1 parts.) and this is before you account for lost power from inefficient parts and lack of machines (it goes to a grounding rod if there is excess power)

**Comment by Zergspower** [comment]
all the emitters : )

**Comment by carlarctg** [comment]
i wish i could actually play the game without every department shutting down from power 20 minutes in, unless the engineers speedrun everything with 5000 hour mastery

i dont like that the entire station is reliant on engineering being competent. theres no other department like this

no sec, departments can police themselves

no med, you can still heal with medkits and local resources

no sci, its only needed for unlocking new things

no command, no difference

no service, you can buy food and drinks from the vendors

no engineering? you cant play the game. someone needs to step up and do things

it sucks

**Comment by Dorsisdwarf** [comment]
There's definitely a balancing issue right now, station power draw regularly spikes so high that the SMESes are empty long before even a fairly simple "replace pumps with straight pipes" setup can get to power generation, and then power outages continue across the station for another 10-15 minutes because as soon as ALL apcs are trying to charge from ~50% on top of the actual station load, chemistry's superfactory, robotics insisting on charging 4 huge cells in their upgraded charger, etc, you're looking at a draw twice what the SMESes can output (Or even the engine generate if its not a high powered setup). Engineers have to get the PACMAN out to keep emitters firing through that period while everyone complains about brownouts basically every round i've seen lately.

**Comment by SimplySmiley123** [comment]
> i wish i could actually play the game without every department shutting down from power 20 minutes in, unless the engineers speedrun everything with 5000 hour mastery

I guess the problem is that the sole, real, valid power source is also not good enough if you're not extremely good with the atmos system and know how to wrangle it prefferably without exploding all of engineering in the process all while having to, as you said, speedrun it in the first 10 or 20 minutes so there's not a lynch mob waiting at the front of engineering, with the other options that do exist, being so ineffective that you might as well not bother with them at all and it won't make a difference (you can setup the solars perfectly fine, but in the end they never matter, if SM ain't setup, they won't prevent the whole station powering down nor even slow it down in any noticable way).

**Comment by CRITAWAKETS** [comment]
>     2. hotwire the engine to the grid (the fast, but dangerous way)

there's currently absolutely no drawback to hotwiring because we don't have power quality mechanics. if given the choice between a solution that fixes everything in quite literally 3 clicks and another that requires building one of the most complicated machines to build in the game, what option do you think players will take?

**Comment by DustanHache** [comment]
> >2. hotwire the engine to the grid (the fast, but dangerous way)
> 
> 
> 
> there's currently absolutely no drawback to hotwiring because we don't have power quality mechanics. if given the choice between a solution that fixes everything in quite literally 3 clicks and another that requires building one of the most complicated machines to build in the game possibly several times, what option do you think players will take? Suffice to say the SMES units are currently just the new player option (aside from botany/atmos cheese).

We actually do, and its called shock wires in hacking. the more power in the system (both general and excess) the more damage is done when someone hits a shock wire without insuls. the scaling on it is pretty forgiving at low outputs, but can scale into crit and even instant death.

**Comment by CRITAWAKETS** [comment]
> We actually do, and its called shock wires in hacking. the more power in the system (both general and excess) the more damage is done when someone hits a shock wire without insuls. the scaling on it is pretty forgiving at low outputs, but can scale into crit and even instant death.

SMES cells actually increase the shock damage from hacking because of how peak power works. Besides, if you're using SMES cells for extra power, you're still putting in extra power up to the 4.35 MW kill range.

**Comment by DustanHache** [comment]
> > We actually do, and its called shock wires in hacking. the more power in the system (both general and excess) the more damage is done when someone hits a shock wire without insuls. the scaling on it is pretty forgiving at low outputs, but can scale into crit and even instant death.
> 
> SMES cells actually increase the shock damage from hacking because of how peak power works. Besides, if you're using SMES cells for extra power, you're still putting in extra power up to the 4.35 MW kill range.

yes, this is true. the damage is calculated by excess power output. That said, it’s not hard to hit or surpass the 5 MW range with exotic gas setups, or even just a plain 80% CO2 engine. God help you if some madman decides to stable tesla and you touch a hotwired powergrid.

**Comment by Dorsisdwarf** [comment]
> I guess the problem is that the sole, real, valid power source is also not good enough if you're not extremely good with the atmos system and know how to wrangle it prefferably without exploding all of engineering in the process all while having to, as you said, speedrun it in the first 10 or 20 minutes so there's not a lynch mob waiting at the front of engineering.

I find that a basic straight-pipe n2 Supermatter _will_ generally be enough to keep the station running somewhat smoothly, at least if you can harass science for part upgrades before the roboticist puts t4s in his cell chargers and crashes the grid. It just struggles desperately at the job of filling up an entire depowered station trying to charge at once (pretty inevitable if not online within 10 minutes). I think you can also jerry-rig more power out of an already-live SM by adding the spare tesla coils from secstorage to the collection array?

**Comment by Zergspower** [comment]
```
/obj/machinery/power/energy_accumulator/tesla_coil/RefreshParts()
	. = ..()
	var/new_power_multiplier = 0.44
	zap_cooldown = 10 SECONDS
	for(var/datum/stock_part/capacitor/capacitor in component_parts)
		new_power_multiplier += capacitor.tier * 0.12
		zap_cooldown -= (capacitor.tier * 2 SECONDS)

	input_power_multiplier = clamp(new_power_multiplier, 0.44, 0.92)
```
is what we changed downstream to help with that a little, a basic bitch N2 will get about 1.5-1.7 with standard setups - which sitll isnt enough on its own so upgrades/more emitters/more teslas etc are added

**Comment by DustanHache** [comment]
> I find that a basic straight-pipe n2 Supermatter _will_ generally be enough to keep the station running somewhat smoothly, at least if you can harass science for part upgrades before the roboticist puts t4s in his cell chargers and crashes the grid. It just struggles desperately at the job of filling up an entire depowered station trying to charge at once (pretty inevitable if not online within 10 minutes). I think you can also jerry-rig more power out of an already-live SM by adding the spare tesla coils from secstorage to the collection array?

Okay, so, the problem is twofold: the first part is that you have rolling brownouts throughout the station even with peak basic n2 speedrun strats. the SMESes act as a chokepoint of sorts for the power output even on a n2 setup (you will only ever get 600 KW out of a basic SMES room setup, even if the engine is producing 2+ MW.) and that amplifies the problem by slowing down the charge rate of basically every APC. Secondly, if someone starts being powerhungry, like botany, robotics, or hell even the bitrunners, _The entire fucking station stops charging._ 
finally, I dont know what world you live in, but there are *not* any spare tesla coils in secure storage. Spare emitters, sure, but not spare coils. you have to assemble extra tesla coils, and that still doesn't directly adress the issue unless you have either hotwired the engine or upgraded the SMESes.

**Comment by Dorsisdwarf** [comment]
>I dont know what world you live in, but there are _not_ any spare tesla coils in secure storage. Spare emitters, sure, but not spare coils.


Apparently this is a deltastation-only thing for some reason oops

**Comment by Zergspower** [comment]
> > I find that a basic straight-pipe n2 Supermatter _will_ generally be enough to keep the station running somewhat smoothly, at least if you can harass science for part upgrades before the roboticist puts t4s in his cell chargers and crashes the grid. It just struggles desperately at the job of filling up an entire depowered station trying to charge at once (pretty inevitable if not online within 10 minutes). I think you can also jerry-rig more power out of an already-live SM by adding the spare tesla coils from secstorage to the collection array?
> 
> Okay, so, the problem is twofold: the first part is that you have rolling brownouts throughout the station even with peak basic n2 speedrun strats. the SMESes act as a chokepoint of sorts for the power output even on a n2 setup (you will only ever get 600 KW out of a basic SMES room setup, even if the engine is producing 2+ MW.) and that amplifies the problem by slowing down the charge rate of basically every APC.
> 
> Secondly, if someone starts being powerhungry, like botany, robotics, or hell even the bitrunners, _The entire fucking station stops charging._ This is because the power system rework prioritizes existing power draw over charging, with APCs being the "backup" instead. this leads to situations where other areas lose their power, and thusly their equipment, simply because one asshole decided to charge their bluespace cell and ate the entire power supply.
> 
> finally, I dont know what world you live in, but there are _not_ any spare tesla coils in secure storage. Spare emitters, sure, but not spare coils. you have to assemble extra tesla coils, and that still doesn't directly address the issue unless you have either hotwired the engine or upgraded the SMESes.

Don't forget that emitters stop firing too, the meta on Nova rn is either running them on their own generator or if you know how making a smes as a capactor JUST for the emitters so it doesn't cascade into a blackout because someone left an empty borg shell in the charger

**Comment by optimumtact** [comment]
Seems to me like the problem (supposedly) is SMES are too hard to build, so that is what you should seek to fix.

**Comment by DustanHache** [comment]
> Seems to me like the problem (supposedly) is SMES are too hard to build, so that is what you should seek to fix.

go ahead and remap all the SMES rooms yourself then, oranges.

**Comment by necromanceranne** [comment]
Mapping them in isn't a problem, the construction is just very time consuming and easy to fuck up by accidentally putting an input onto your grid, which winds up with very heavy demand on the grid.

**Comment by SimplySmiley123** [comment]
> We actually do, and its called shock wires in hacking. the more power in the system (both general and excess) the more damage is done when someone hits a shock wire without insuls. the scaling on it is pretty forgiving at low outputs, but can scale into crit and even instant death.

Bold of you to assume it's a downside to most players.
Non antags want it so the random tider kills himself breaking into their workplace.
Antags want it so random tiders kill themselves breaking into places or when going after them.

**Comment by SimplySmiley123** [comment]
> Mapping them in isn't a problem, the construction is just very time consuming and easy to fuck up by accidentally putting an input onto your grid, which winds up with very heavy demand on the grid, resulting in brownouts

It's more about the lack of space for more SMESs in their room and how the wiring in those rooms goes into the wall.

**Comment by Pickle-Coding** [comment]
We could probably do with adding a maintenance panel to walls that allow you to see and modify cables inside them. Could probably also do with t-ray scanners working on cables inside walls too, so they're not a complete invisible noob trap. Also I don't think SMES accept different layer cables even when setting their layer with a multitool. The terminal doesn't seem to be connecting to cables of layers either assigned from the SMES or layer of cables used to place the terminal.

The issues where these are the worst are in Birdshot. There is a massive line of cables under walls in the SMES room, so it's very easy to accidentally hotwire (hotwiring makes SMES pointless and actually makes the grid weaker to sudden spikes in power compared to stacking SMES, unless you're running a CO2 engine or whatever) the SMES and not notice until you check the grid, then go through process of elimination because you can't really see the connection of cables under SMES through walls very well.

**Comment by ExcessiveUseOfCobblestone** [comment]
Imagine if everyone spawned as assistant every round and no head of personnel, but none of the other heads want to man the counter because otherwise they would have just signed up as hop, and now someone who wanted to play the game has to put in the work to get the spare. Now imagine if under that same scenario they couldnt just get the spare and log in, they had to test different text strings of various lengths,capitalizations,and of course characters to unlock the access codes to give someone their proper access. Now imagine they dont want to do that part, so they dont even bother getting the spare and now no one can do any of the jobs because the hop is out of order.

Of course, tthe people who like the experimentation part enjoy the job, but its so few and far between while also requiring everyone else be subservient to these individuals and engage in their mechanic or face inability to even have a chance to play their role. Its so awkward

**Comment by Astrogem2** [comment]
Personally if I have to alter the station's construction to accommodate extra SMES to regulate the power in the station properly, I'd just consider it shit design to be honest.

**Comment by moocowswag** [comment]
what about this https://github.com/tgstation/tgstation/pull/55354 but instead of nerfing standard solars we add the plasma glass upgrade.

**Comment by deathrobotpunch** [comment]
> what about this #55354 but instead of nerfing standard solars we add the plasma glass upgrade.

sounds like a good idea but leave the nerf of normal solars out

**Comment by MTandi** [comment]
In my recent testing, if you set up all solars on Meta Station, it will be enough to power the entire station environment/lightning channels, and a half of the equipment. And the balance will be positive and eventually charge up the entire station on the roundstart setup.

And this PR buffs the generation more than twice. This is harmful for other power sources, and CL definitely should say balance, rather than QOL. 

This PR turns solars into a single power generation solution, alternative to SM and Hypertorus, instead of a secondary solution. It will make it unnecessary to explore other power sources, or even setup all of the panels, since a couple of arrays will suffice for all energy needs. Without any downsides. While SM can be sabotaged and delam, solars are always there and may suffer only from an occasional meteor. 

As a solution for this PR I suggest:

- Make the max solar panel power generation shift between 1.5 and 3 kW depending on the orbit type
- Introduce an orbit type like "Orbit over a red giant in a meteor belt" that 
  - Doubles the solars max generation 
  - Makes the meteor waves more frequent
  - Halves SM generation (tie it somehow to SM reacting to the gravity field of the star)

**Comment by projectkepler-ru** [comment]
This is not the right way nor is it QoL, yes, it stands to benefit people so therefore it logically could be considered quality of life.

Except that's not always what it means to have quality of life in this server
If you, truly care about the wellbeing of engineers and their enjoyment. The correct approach is simply adding more to the solar generation. Maybe a tiered glass system so  better glass = better power

Maybe add some sort of passive safe power generation that doesn't generate a lot of power (which is just solar but more portable or something) 

Or you know, you can always just maps in more SME if that's really the main issue

There's so much that could be done with power generation and so much that could be added to both planetary content (as seen in both nova sector, skyrat and bubberstation) that I'm surprised this was supposed to be a QoL

**Comment by optimumtact** [comment]
I dont think this PR has any future in it's current state.

**Pull request closed without merging**
