### PR TITLE
resprites stairs

### PR DESCRIPTION
**Pull request by pudl**
this resprites the current stair sprite that's been in game since r4407, with this it just looks simpler and can flow with normal turfs more easily and maybe it'll see more use.

http://puu.sh/fUOEL/9c33cad80f.png
left is resprite, right is original

additionally, this adds 3 extra sprites, a left stair, middle stair, and right stair. this way you can make a large multi-tile stair that looks more natural.

http://puu.sh/fUOsF/141acc499d.png

### CODE REVIEW

**Comment by TheVekter** [comment]
We have stairs?

**Comment by WJohn** [comment]
:+1:
They're just turfs that look like stairs but it works pretty well.

**Comment by Incoming5643** [comment]
8^y

**Comment by Miauw62** [comment]
Why is incoming commenting mathematics
Op 14-feb.-2015 20:36 schreef "Incoming5643" <notifications@github.com>:

**Comment by Nienhaus** [comment]
:+1:

**Comment by Deantwo** [comment]
I want to pour *space lube* on those soooo badly right now.

**Comment by fj45** [comment]
They look great, I try to use them where I can on Para. Helps gives rooms depth.

**Comment by Chocobro** [comment]
doesn't look good to me, but I can't tell why. gut feeling, maybe?
stairs are super underused anyway so :+1: I guess

**Pull request merged**
