### PR TITLE
Makes sorts work before GLOB

### PR DESCRIPTION
**Pull request by Cyberboss**
I was gonna remove sortInstance but that is some V I N T A G E shitcode
  
Required by #34198

### CODE REVIEW

**Comment by praisenarsie** [comment]
oh my GLOB

**Comment by optimumtact** [comment]
It's not vintage, it's like 2014/2015

**Comment by Cyberboss** [comment]
It's relatively pathed, oranges!

**Comment by optimumtact** [comment]
carn is stubborn

**Pull request merged**
