### PR TITLE
Paper markdown

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]:
[]:
:cl: 
add: Added paper markdown
/:cl:

- [X] Code the regexes
- [ ] Figure out why it's not working
- [X] Ask other contributors help

```
|text| : Centers the text.
**text** : Makes the text bold.
*text* : Makes the text italic.
_text_ : Makes the text underlined.
+text+ : Increases the size of the text.
%s : Inserts a signature of your name in a foolproof way.
%f : Inserts an invisible field which lets you start type from there.
__text__ : Decreases the size of the text.
* item : An unordered list item.
  * item: An unordered list child item.
--- : Adds a horizontal rule.
```

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
YESSSSS

**Comment by pubby** [comment]
Is regex even powerful enough to parse markdown? Sounds like you'd run into problems with nesting (especially because markdown has pretty strange rules when it comes to nesting)

**Comment by nicbn** [comment]
Just noticed I fucked up with lists.
Also yes regex are this powerful. But they are behaving oddly in DM.

**Comment by nicbn** [comment]
Ok I need help, this is crashing the server and I have no idea why.

**Comment by nicbn** [comment]
I'll replace regex by other method, looks like byond doesn't like complexity.

**Comment by tortellinitony** [comment]
Make bold, italic, etc. buttons like on _**git hub**_

**Comment by ExcessiveUseOfCobblestone** [comment]
do you still have to use br

**Comment by nicbn** [comment]
No, line breaks will do the job.

**Comment by msgerbs** [comment]
Can we get a markdown option for a "sign here" field? Most people don't know how to actually sign paper, and explaining to them "Just type [sign]!" doesn't work very well IC.

**Comment by MoreRobustThanYou** [comment]
yeah, a signature field would be nice, just click it to sign it

**Comment by nicbn** [comment]
Sure, I'll return working on this the day after tomorrow.

**Comment by optimumtact** [comment]
just dont' do a full markdown spec, and you can parse it

**Comment by nfreader** [comment]
Hooray! Death to the buggy paper renderer I whipped up in about 20 minutes!

**Comment by Cyberboss** [comment]
Getting stal

**Comment by KorPhaeron** [comment]
@nicbn 

Just ping me when you're ready to have this reopened

**Comment by nicbn** [comment]
I won't work on this for a while, if anyone wants to finish this, go on

**Comment by nicbn** [comment]
# New PR #30873

**Pull request closed without merging**
