### PR TITLE
Changes the regular meson goggle sprite to yellow

### LINKED ISSUE #76750: Scanner/Goggles Sprites Inconsistency
## Round ID:
[210032](https://scrubby.melonmesa.com/round/210032)

## Testmerges:
N/A

## Reproduction:
image
On the left is "Engineering Scanner Goggles" in meson mode and on the right is "Optical Meson Scanner" showing green colouring.
Meson mode was recently changed back to being yellow, but the "Optical Meson Scanner" has not been changed too.

image
This is an "Optical T-Ray Scanner" which Atmospheric Technicians usually wear, in Connectable mode.

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Changes the object and mob sprites for meson goggles from green to yellow, consistent with the engineering scanner goggles.

Fixes #76750

## Why It's Good For The Game

Visual consistensy is widely considered to be a good thing.

## Changelog
:cl:
image: Meson goggles are now yellow, consistent with engineering goggles' meson mode.
/:cl:

### CODE REVIEW

**Comment by 13spacemen** [comment]
@Thunder12345 shouldn't the engi scanners meson mode NOT be yellow and be green instead?
mesons have always been green. the engi scanners are a much newer thing

**Comment by Borisvanmemes** [comment]
What about night vision mesons?

**Review by Wallemations — CHANGES_REQUESTED** [review]
Make it the other way around

**Comment by Loafin34** [comment]
i want green mesons and yellow scannergoggles, its quite honestly just aesthetic. if its so important you can change yellow scannergoggles to green.

**Comment by Ghommie** [comment]
Very unpopular PR over a negligible thing, I don't see an issue with the googles being green.

**Pull request closed without merging**
