### PR TITLE
Grinders now use radials

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
add: All-In-One Blender UI uses a radial menu now. You can see the contents and reagents by examining.
/:cl:

If there are no reagents and beaker is empty or there is no beaker, clicking it will eject the contents.

image
image

Images outdated, eject button is always on top

### CODE REVIEW

**Comment by miniusAreas** [comment]
now we wait for grinders to become terminator.

**Comment by Farquaar** [comment]
Does this mean we can't use grinders to check the contents of a beaker anymore?

**Comment by nicbn** [comment]
You can, just examine it

**Comment by AlexTheSysop42** [comment]
That doesn't show the actual contents unless you have sci goggles

**Comment by nicbn** [comment]
It shows the contents regardless of wearing googles or not

**Comment by AlexTheSysop42** [comment]
Oh ok examine the grinder

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
