### PR TITLE
Finishes boards refactor

### LINKED ISSUE #18078: Can no longer upgrade Power Cells in Rechargers
So, when trying to replace the High Power Cells in the recharger with Super Capacity Cells, it did nothing.
Get the feeling this was caused by making it require a High Power cell instead of making it start with one.

### PR DESCRIPTION
**Pull request by Core0verload**
This PR finishes what I have started in #17300 by making all the machines use `apply_default_parts(src)` for components initialization.

It also adds two new board sprites, one for Abductor boards and one for Ravtar boards:
board board_a board_r
There are no deconstructable Ravtar machines yet, sprites are added for future use. Abductor sprite is used only by Seed Vault's plant DNA modifier. It wasn't made by actual abductors, but it was surely made by aliens.
- Boards now have a new var: `def_components`. It is a list containing replacement paths for default parts. For example, `list(/obj/item/weapon/stock_parts/matter_bin = /obj/item/weapon/stock_parts/matter_bin/super)` would make machine spawn with super matter bins instead of basic ones by default.
- Console screens that were used in machines instead of glass sheets are replaced with actual glass sheets. Support for sheets as machine components was added by me in #17300.
- Fixes #18078.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
do you sprite those yourself? you always have such good sprites

**Comment by Core0verload** [comment]
I just copypasted parts of existing abductor/Ravtar devices together and filled the gaps.

**Comment by Core0verload** [comment]
4 hours, and it's already conflicting? Fuck.

**Comment by LatD** [comment]
Can you apply that default parts thing to cyborg rechargers and fix them here too? It would fix #18078

**Comment by PKPenguin321** [comment]
>Abductor sprite is used only by Seed Vault's plant DNA modifier. It wasn't made by actual abductors, but it was surely made by aliens.

so plant DNA is alien magic but cloners that can bring back the dead and work on souls isn't????

**Comment by Core0verload** [comment]
@PKPenguin321: it applies only to plant DNA modifier in lavaland seed vault, the only device in ss13 that spawns with T4 parts. Botany's modifier is a cheap T1 replica of alien modifier, it spawns with a normal board.

@LatD: done. Situations like that were the reason I added `def_components`.

**Pull request merged**
