### PR TITLE
Science Crates

### PR DESCRIPTION
**Pull request by ghost**
Added sprites for science crates from /vg/

scicrate

:cl:
add: Science crates now have new sprites
/:cl:

### CODE REVIEW

**Comment by Iatots** [comment]
Nice crates but don't thumb up your own post.

**Comment by RandomMarine** [comment]
What are you, the thumb police?

**Comment by Tofa01** [comment]
I give both thumbs up and down, this is about equality.

**Comment by coiax** [comment]
Thumbing up your own post is tacky.

**Comment by XDTM** [comment]
Thumbing it down is just weird

**Comment by ShadowDeath6** [comment]
Upvoting your own posts should be grounds for a permanent ban from github tbh fam

**Comment by anconfuzedrock** [comment]
are you only adding this to be a dick to the 3/4ths guys

**Comment by SgtxRootbeer** [comment]
@anconfuzedrock
That's good enough reason for me, I hate the new 3/4ths perspective they are pushing.

**Comment by uraniummeltdown** [comment]
@anconfuzedrock 3/4 crates aren't in yet

**Comment by ExcessiveUseOfCobblestone** [comment]
t-t-travis?

**Comment by MrStonedOne** [comment]
@anconfuzedrock fuck you for even making that comment

**Pull request merged**
