### PR TITLE
Cryo stops non-medical chem metabolization

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Very low temperatures will now put bodies in stasis, preventing damage from overdoses and poisons. They will resume if they're not purged before unfreezing.
add: Cryo cells can now be set to not turn off at full health.
add: Viruses will not advance while cooled down.
add: Xenomorph embryos will grow more slowly while cooled down. Get a warm nest!
add: The cut-off temperature is 180K, so if you want to poison cryo simply raise the freezer's temperature above that and below 273.
/:cl:

Medicines and temperature-affecting chems still work, so you can use antitoxin to purge toxins. Most alcoholics, drugs, toxins and other miscellaneous chems will not.

This basically adds a way to prevent poison death while you are in medbay. Poisoning someone in the middle of a staffed and competent medbay should not result in death.

If someone wants a different value for the freezing point, ii'll change it; i just picked one that seemed cold enough. Cryo with base parts goes down to about 80 K

### CODE REVIEW

**Comment by coiax** [comment]
~~Here's a slightly more complex idea, **low body temperatures** stop the body's metabolism, and only specific "low temperature chemicals" will continue to function. Same idea, just not~~

You've already done this, it's tied to body temperature, not cryo. I approve. :+1:

**Comment by FantasticFwoosh** [comment]
Excuse me while i pop a cryoxadone tablet while on a IV drip of ice tea underneath a shower to **LIVE FOREVER!!**

**Comment by XDTM** [comment]
Should i also make it stop viruses?

**Comment by coiax** [comment]
This does nerf filling cryo with acid.

**Comment by XDTM** [comment]
i'm gonna make cryo inject even if the guy inside isn't cold

**Comment by Kromgar** [comment]
Filling it with acid should still melt people

**Comment by XDTM** [comment]
I'm adding acid to the whitelisted chems

**Comment by CPTANT** [comment]
👎 

Makes poisoning the cryo's pointless.

**Comment by XDTM** [comment]
Poisoning cryo is still doable, just raise the freezer temperature a bit

**Comment by XDTM** [comment]
oh shit i just realized that xenos can't keep facehugged people in space anymore

**Comment by XDTM** [comment]
In this commit: embryos will grow more slowly but not outright stop when cold.

**Comment by lordpidey** [comment]
What will this do to amantin (or whatever the toxin is that damages upon removal)?

**Comment by XDTM** [comment]
It won't gain stacks while frozen, so it will behave normally

**Comment by Iamgoofball** [comment]
:-1:

literally just "nullify any toxins"

this is fucking dumb

**Comment by Iamgoofball** [comment]
# "lol i'm too lazy to deal with toxins and overdoses PUT THEM IN THE MAGIC CURE-ALL TUBE"

**Comment by WJohn** [comment]
i like the xeno part, give at least *some* incentive not to space and freeze over the whole damn station.

the rest is up to others to debate.

**Comment by ExcessiveUseOfCobblestone** [comment]
Not a big fan of "nothing bad hurts you but you still benefit from the good" on a roundstart object that's already known for being such a huge crutch

**Comment by XDTM** [comment]
@Iamgoofball There is currently no way to counter toxins paired with anacea, since there is no way of removing chems that isn't a medicine. Also, you can't carry a cryocell wherever you want, and if you poison someone in the dead center of medbay you shouldn't expect to kill your target.
@ExcessiveUseOfCobblestone On the other hand it's very risky to use since it can be poisoned or keep you stunned forever, if someone were to set it that way. I wouldn't mind lowering the non-cellular healing of cryoxadone, though.

**Comment by CPTANT** [comment]
Than deal with anacea being a shitty chem.....

**Comment by Iamgoofball** [comment]
remember when I was saying it was powerful and you guys said "nah it's too weak to be a traitor chem"

**Comment by XDTM** [comment]
>Also, you can't carry a cryocell wherever you want, and if you poison someone in the dead center of medbay you shouldn't expect to kill your target.

**Comment by Iamgoofball** [comment]
@XDTM stop trying to make excuses to get away with your magical cure-all tube, what is it going to hand out free blowjobs next? stop undermining my attempts to add complexity to being a medical doctor

**Comment by XDTM** [comment]
If you want to add complexity, i'll remove cryo healing except for cellular damage, so tubes are only used for freezing

**Comment by optimumtact** [comment]
So why would you make it worse?

**Comment by XDTM** [comment]
goof is complaining that it is a cure-all, if i make it cure only specific issues it won't be a cure-all, but a type of treatment

**Comment by MisterTikva** [comment]
Anacea is purged by calomel isn't it?

**Comment by PKPenguin321** [comment]
Instead of nerfing toxins into non existence like this to counter one toxin, maybe make specific chems not affected by said toxin to act as an antidote.

**Comment by XDTM** [comment]
@MisterTikva Calomel is a medicine.
Again, it's not a reaction to anacea, but to poisons in general. If you put the right poisons in someone/OD him with medicines he'll outdamage antitoxins and kill the victim before you manage to purge the chem. 
And you're all treating this as if cryo chamber were spread in every corner; this won't affect a guy you syringe gun in a hallway unless he stays alive to reach medbay, and if there are docs in medbay it's fair that he gets treated before dying, much like you can stop bleeding and then treat the bloodloss.

**Comment by fludd12** [comment]
How about make it slow/stop your chemical consumption entirely, allowing more time to think of ways to deal with problems, instead of stopping the problems entirely? You could add a chemical tag which reverses the consumption time reduction, so things metabolize slower/less effectively at higher temperatures, for stuff like cryoxadone.

It'd also mean that people get to control to some extent the potency/duration of chemicals in medical situations, allowing low-level healing over a long time, or rapid healing over a shorter duration.

**Comment by Haevacht** [comment]
@goof They'll still get fucked right up by w/e toxin it is when ejected from cryo, this just makes it stasis. Gives your medical docs a chance to go get enough antitoxin/charcoal/fancy chems to deal with the problem. This adds a little complexity with cryo mixes and the purging medicines. How much of them? Is there room for mannitol for clones? Has anyone even set up cryo?

**Comment by PKPenguin321** [comment]
>goof They'll still get fucked right up by w/e toxin it is when ejected from cryo, this just makes it stasis.

literally false since you can put 1u of charcoal into the cryo beaker and it will purge the toxins by the time he's outta the tube

>Has anyone even set up cryo?

before goofchem yes

**Comment by ExcessiveUseOfCobblestone** [comment]
having more checks [aka indicators] to subvert cryo is not how you improve the ability to subvert cryo.

**Comment by FantasticFwoosh** [comment]
Just take a cold shower for the same stasis effect to live forever with your magic cure-all pills

**Comment by XDTM** [comment]
Don't blame cryoxadone on me, fwoosh.
Here's my reasoning: if you're a doctor and a guy is dragged in crit from poison, SOP is to give him charcoal and hope the toxin doesnt outdamage it while it purges the poison.
With this PR, the patient doesn't have to die if the doctors are competent enough to freeze him first, and then giving charcoal.
With bleeding you dont just give the patient iron, you also stop him from bleeding, first.

**Comment by AdamElTablawy** [comment]
No.

If a chem is op change the chem, this makes cryo too strong. You poison a guy, they get defibbed and thrown in cryo, they live. Poison the cryotube with something like mutagen, it wears off. Etc. magic cure all tube because the one thing cryo has difficulty with-toxins being inside a person-is too much for moronbay to handle is not a good thing. You can already just purge anacea with charcoal or calomel or pentetic-hell you can outdo it with a fucking sleeper. You just need more charcoal than anacea is removing.

**Comment by XDTM** [comment]
>You poison a guy, they get defibbed and thrown in cryo, they live.

Which was already the case.
>Poison the cryotube with something like mutagen, it wears off.

You can set the temperature above chem-freezing. Now you can even prevent cryo from opening at all, so they work as permanent cages if you want them to.
>Etc. magic cure all tube because the one thing cryo has difficulty with-toxins being inside a person-is too much for moronbay to handle is not a good thing.

It's not difficulty, it's that if the toxin is dealing enough poison damage all you can do is try to keep outhealing it. If you try treating a tricord overdose, it requires constant spamming of pentetic, bicaridine and kelotane at an upgraded sleeper, until you purge all 30 units. It's like if you had to keep curing the virus symptoms instead of stopping the virus itself.
>You can already just purge anacea with charcoal or calomel or pentetic-hell you can outdo it with a fucking sleeper. You just need more charcoal than anacea is removing.

Anacea removes 6 a tick of any of those. It's faster than you can inject it.

Again, this is not a reaction to anacea, i just want cryo to be less omni-healing and more specific, i.e. only for poisonings and cellular damage. I already said that i'd happily remove all non-cellular healing from cryoxadone.

**Comment by PKPenguin321** [comment]
>Anacea removes 6 a tick of any of those. It's faster than you can inject it.

Then make it not do that instead of removing poisonings

Or make it specifically not purge calomel or something

**Comment by Crushtoe** [comment]
I'm here to voice my concern that this is a bad idea.

Doctors should have a reason to check cryo at least once other than roundstart, to make sure that no one poisoned it. Yes, I understand you can raise the cryo temperature so that you can poison people, but no one will ever check the cooler to make sure it's not set above 180 which only moves to the problem. 

People will still poison just as much as always, you've just made it needlessly more difficult to do so. It accomplishes nothing besides making it require an extra step which you won't ever be caught doing. Because, again, *no one ever checks the coolers.*

**Comment by optimumtact** [comment]
With this kind of negative reaction already you will need to request admins to run a game poll and then return with a positive result.

Closing this for now.

**Comment by jughu** [comment]
Set cyro not to turn off at full health forget the patient and hes like a whole hour in the cyro and very very salty

**Pull request closed without merging**
