### PR TITLE
Epic Emitter Sprites

### PR DESCRIPTION
**Pull request by 13spacemen**
https://user-images.githubusercontent.com/46101244/179416604-72a76b7f-8729-4a4f-a3a7-7ee88dd4a36a.mp4

Ports the emitter sprites from /vg/station by Megautham. Also seen on SS14.
https://github.com/vgstation-coders/vgstation13/pull/26688

I did not port the thin blue emitter beam sprites (yet) because /vg/ beam code is too confusing for me at the moment

I still need to:

- [ ] add overlays for underpowered state and panel open
- [ ] delete the old emitter sprites
- [ ] tweak the sprites a bit maybe color the blue part light green like the current emitter beams

:cl:
imageadd: Emitter have epic new sprites as seen on SS14!
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
this looks so out of place

**Comment by 13spacemen** [comment]
@Kapu1178 it looks better with the thin blue beams, you can check out the /vg/ PR to see, need to figure out how to do that on TG
regardless of beams, I think these are better than the current emitter sprites

**Comment by Kapu1178** [comment]
> @Kapu1178 it looks better with the thin blue beams, you can check out the /vg/ PR to see, need to figure out how to do that on TG regardless of beams, I think these are better than the current emitter sprites

no it looks out of place because it's shading is completely different to every other object in TG. And the level of detail is significantly higher than TG's new (terrible) 4-color color palettes.

**Comment by ArcaneMusic** [comment]
I think it looks good, but I have to agree about the lighting. Most sprites assume top down lighting in terms of what and where metal is reflecting on the sprite. I realize you're just porting the sprites but you'll probably be asked to change the lighting.

**Comment by thgvr** [comment]
> And the level of detail is significantly higher than TG's new (terrible) 4-color color palettes.

Limited palettes provide needed constrast to sprites.

And here's the palette for this PR's sprite. 
image

This would need a lot of work to fit the rest of things. Also, vgstation does *not* use emitters in a way tg does, the sprites won't be compatible. a 1px blue line is pretty bad when we don't have the reflector mechanics and such that change the beams appearance that vgstation has.

**Comment by 13spacemen** [comment]
I will get back to this later

**Pull request closed without merging**
