### PR TITLE
Resprites the aquarium

### PR DESCRIPTION
**Pull request by Sheits**
## About The Pull Request

Resprites the aquarium and pufferfish
image
image

## Why It's Good For The Game

image

## Changelog
:cl:
imageadd: Replaces the old aquarium sprites
/:cl:

### CODE REVIEW

**Comment by Sheits** [comment]
I didn't wanna ruin how epic the pufferfish sprite was initially so it might look a lil weird

**Comment by Fikou** [comment]
the pufferfish is worse

**Comment by Time-Green** [comment]
Please, anything but the pufferfish

**Comment by EOBGames** [comment]
Yeah not a fan of the pufferfish, as much as the old one is shitty the new one just looks way too much like it's pogging.

**Comment by Sheits** [comment]
Yeah I do see what yous are talking about, I’ll probably tone it back when I get some free time

**Comment by Sheits** [comment]
Alright I toned em down a lil bit, tell me how you guys like it, I can always go back and change things easy.

**Comment by Time-Green** [comment]
I personally liked the blushing pufferfish, it looked real cute and had SOUL

**Comment by maxymax13** [comment]
looks too mediocre to make up for the loss of coder pufferfish

**Comment by Sheits** [comment]
love the feedback but suggestions would help a lot more...

**Comment by coiax** [comment]
If you've done two different things that don't depend on each other, and there's contention, break them into two separate PRs.

**Comment by Sheits** [comment]
I don't see why updating a series of outdated sprites in the same dmi should need two PRs, In my opinion I think having coder sprites in the game is stupid and only a very small sample of the playerbase can enjoy it, others may find it annoying and complain to spriters that theres outdated sprites in the game, the reason I made this PR in the first place.

**Review by Twaticus — APPROVED** [review]
and why are people complaining about this? are we even looking at the same pr?? give it a rest
image

**Comment by Twaticus** [comment]
surprise! we were not looking at the same pr 😃

**Comment by Sheits** [comment]
oh no like the majority of thumbs downs were after i updated it

**Pull request merged**
