### PR TITLE
Fixed regular scientists spawning in RD's office in kilo

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
Title
And i switch one of the walls to be reinforced. It's crooked when you look at it in game.

## Why It's Good For The Game
Bugfix

## Changelog
:cl:
fix: fixed regular scientists spawning in RD's office in kilo
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Its a feature :(

**Comment by Son-of-Space** [comment]
What do you mean by crooked in game? It's not consistent with the rest of the walls around that room so it doesn't make sense to include this change unless you're changing the walls around all secposts.

**Comment by vincentiusvin** [comment]
image
makes more sense than
image

**Comment by Son-of-Space** [comment]
Yup. Adding in that other R-Wall works. Nice 👍

**Comment by Son-of-Space** [comment]
Yup. Adding in that other R-Wall works. Nice 👍

**Review by Son-of-Space — APPROVED** [review]

**Pull request merged**
