### PR TITLE
Lower Friendly cost from 4 to 2

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request

Lowers cost of the Friendly quirk from 4 to 2 points. Approved by Floyd.

image

## Why It's Good For The Game
Floyd agrees that a quirk that exists to aide exclusively other people should not cost as much as something that aids exclusively you. This fits in terms of power for the existing 2 point quirks: Clown/Mime Fan and Musician.

## Changelog
:cl:
balance: Friendly quirk has been lowered from 4 to 2 points.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
increase the amount of points you get from bad touch too

seriously why does it only give one point does floyd not know how much people hug each other in this game

**Comment by Jared-Fogle** [comment]
u do it

**Comment by Tlaltecuhtli** [comment]
there isnt enough 2 point positive stuff stuff as if you have 2 surplus you can only choose instrument or mime fan or friendly now

**Comment by spessbro** [comment]
> mime fan

clown fan is clearly superior

**Pull request merged**
