### PR TITLE
Prevents sentience potion from working on monkies

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Logic: they can be converted to humans, this be too OP

### CODE REVIEW

**Comment by bgobandit** [comment]
How is this more OP than sentient statues or xenos or chaos magicarp or any of the other things that can be made sentient?

**Comment by Miauw62** [comment]
because this lets you make full humans, which sucks.

**Comment by Incoming5643** [comment]
I'm both confused how I missed this pull and it's reasoning.

"it lets you make humans"

We have adamantium golems guys. Literally the same thing on a different path. No one even used the monkey route.

**Comment by RemieRichards** [comment]
@Incoming5643 Golems are gimped by being tied to a human master and limited clothing/no armours.
They're not freeform humans that can do anything they please (within the bounds of the game and rules)

**Comment by Incoming5643** [comment]
The sentient slime potions have the same "please work with this guy who took the time to bring you back into the round" rules the golem rune does. Also you could scrub the golems species weakness with a DNA injector with the same amount of effort as humanizing a monkey. 

I mean whatever I'm just confused, I must have missed a REALLY fun round.

**Pull request merged**
