### PR TITLE
Revert "Soapstones now have a fixed vocabulary (and rating system!)"

### PR DESCRIPTION
**Pull request by coiax**
Reverts tgstation/tgstation#23717

- Breaks engraved message colours
- The rating system doesn't work, attacking it with empty hand does nothing
- You can't remove any message except for your own
- I was never a fan of the Dark Souls style message styling. I think that @Xhuis should open a PR to bring it back, possibly make it cheaper than a free form message (or a free form message more expensive).

This just broke too many things for me. Sorry @Xhuis

### CODE REVIEW

**Comment by calzilla1** [comment]
:+1:

**Comment by Xhuis** [comment]
Then, uh, fix them? Or give me time to open a fix instead of knee jerk reverts. I respect your wishes but this is an incredibly sloppy way to deal with your problems.

**Comment by Armhulen** [comment]
i like free form messages more...

**Comment by Xhuis** [comment]
I guess that works, too. I'll work on a patch when I get home to do some stuff.

**Comment by KorPhaeron** [comment]
Why was this closed? None of the PR you are reverting works

**Comment by Xhuis** [comment]
Does it really matter why he wanted to close his own PR?

**Comment by coiax** [comment]
Keeping it open then. :/

**Comment by Xhuis** [comment]
Hell with that, you can close PRs if you damn feel like it. They're your property.

**Comment by ExcessiveUseOfCobblestone** [comment]
was this suppose to use tgui or something?

**Comment by Xhuis** [comment]
Why not merge #23700 over this anyway? IMO we haven't seen a whole lot of action with the new vocabulary system yet, so we should probably let it stay a while.

**Comment by Xhuis** [comment]
What a convoluted mess of PRs. And this was even speedmerged for no real reason. All of it worked, and was tested on live yesterday.

Is it even worth it to try to work with these anymore, or will all of my PRs just get reverted too?

**Comment by Xhuis** [comment]
Call me stubborn, but I still feel that some of these changes are good. I'm going to further atomize them, as you said yourself that I could make a PR to re-add the vocabulary, and I feel like enough people wanted it in the first place.

If a maintainer has an issue with this, just comment and I won't bother.

**Pull request merged**
