### PR TITLE
The shuttle can no longer leave during clockcult rounds

### LINKED ISSUE #31318: New Clock Gets Cucked
If the shuttle docks, it counts as the ark getting destroyed, even if it doesn't activate to let the crew in.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: The Ark of the Clockwork Justiciar is now registered as a hostile environment.
/:cl:

Fixes #31318

The original intention was for the shuttle leaving to cause the servants to win, but an issue with that arose and now it just can't leave at all.

### CODE REVIEW

**Comment by Supermichael777** [comment]
still lame, interdict the shuttle to handle stealthcult(and make the ark activate)

**Comment by KorPhaeron** [comment]
red alerting and shuttle calling as stealth cult new meta

**Comment by Robustin** [comment]
Why not just do the rev system.

**Comment by Xhuis** [comment]
A hostile environment thing was considered, but it occurred to me that captains who go full *HYPERMETA* might attempt to call the shuttle just to see if it leaves or not, and if it doesn't, then to prep for the invasion. This makes it so that if they do that pre-emptively then they can't deny the clockers muh greentext.

I could also make it a halfwin, if worst comes to worst.

**Comment by ChangelingRain** [comment]
better solution: once the shuttle leaves, make the ark just slam on with a 2 and a half minute timer, so the crew gets the full "I have fucked up" experience. it's no fun if they don't realize just how badly they've fucked up.

**Comment by Xhuis** [comment]
If I wanted to go all-out I could make it have some spooky stuff with reverse parallax like it's being drawn back towards the station (`"where are you going?"`) but I'm not sure how feasible it is; it also might desync with the ark and shuttle timers and cause massive buzzkills all around

**Comment by ChangelingRain** [comment]
nah, it's funnier if they can't actually get back to the station to deal with it.
an entire shuttle's worth of panicking crew as ratvar just summons his own ass.

**Comment by Xhuis** [comment]
For accuracy on the stat tracker, I also added a separate stat report for the shuttle leaving. I think a "you fucked up" sequence might be a thing for another PR.

**Comment by RandomMarine** [comment]
We don't need more gamemodes with the shuttle being a win condition for one side of a team conflict.

**Comment by Xhuis** [comment]
It's either that or the potential to meta the roundtype by calling the shuttle, which is awful gameplay that I don't want to encourage.

**Comment by AnonymousNow** [comment]
Make using the shuttle as a weapon by the crew a punishable thing. I like it.

**Comment by RandomMarine** [comment]
That was a reach of a theory back when the hostile environment shuttle delay was first added and it's an even bigger one now.

Turned out nobody really wants to do the thing that **ends the round** just to find out what the gamemode is.

**Comment by Xhuis** [comment]
This is the only gamemode that's at least somewhat stealthy that could have the hostile environment delay out them. If a maintainer would rather I just make it a hostile environment from the getgo, I could do that, but right now I'd rather not take that risk.

**Comment by Arianya** [comment]
@RandomMarine But captains will absolutely call the shuttle ASAP once bloodcult is confirmed, since evacuating on the shuttle is a guaranteed 100% win even if its filled cultists so long as they don't complete their objectives in time.

Making the shuttle a win condition for the crew is no bueno for a team antag situation.

**Comment by RandomMarine** [comment]
@Arianya it's not a win condition for anyone if it uses the same shuttle launch delay that rev and a doomsdaying AI causes.

**Comment by sawrge** [comment]
its pretty blatant when people call the shuttle just to confirm roundtype

**Comment by RandomMarine** [comment]
I've never seen it even happen at all ever since the rev/malf auto-recall got removed.

On the other hand, clocker victory-by-shuttle will be way too easy because the magic warping camera consoles make it trivial to steal all the comm console boards and delete the design to make any replacements.

The only possibly challenging part is getting a head id, but the CMO getting dunked is rarely noticed.

**Comment by optimumtact** [comment]
Yeah I think everyone is right here, I've never seen a shuttle call used to meta the roundtype, it's much more likely that it will be called *when* the roundtype is confirmed, so it makes sense to use the hostile environment system.

**Comment by AnonymousNow** [comment]
I've frequently seen the shuttle called as a weapon against the current antagonists, when the roundtype has been discovered but nothing, y'know, interesting has happened yet.

**Comment by Xhuis** [comment]
Since a maintainer has given their own input, I'll make this use a hostile environment.

**Comment by Doppeltongue** [comment]
Seems fair. Not much point in a base-building antag if the crew is allowed to just run away.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
