### PR TITLE
Meth no longer breaks the space time continuum.

### LINKED ISSUE #8158: Meth breaks the space time continuum.
1. OD on meth until you start jumping around at random.
2. Hop in a sleeper.
3. Wait a moment.
4. Meth OD warps you out of the sleeper, sleeper thinks you're still inside of it.
4. Get a buddy to constantly pump beneficial reagents into you while you run around robusting people.

This probably also works with other machines/containers.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Fixes #8158

thanks remie

### CODE REVIEW

**Comment by Cheridan** [comment]
So I guess the space check wasn't needed? or will we have junkies moving around in space?

**Comment by Razharas** [comment]
Maybe just simulate the player movement so all the checks will be already in place + some automatic nice features like instead of doing nothing in containers meth junkies will walk out of them uncontrollably

**Comment by Cheridan** [comment]
Yeah, it seems like this should be using move() or some other proc which already has those checks in it.

**Comment by MrPerson** [comment]
Step() calls move. The problem is that code to reset sleepers (or whatever) isn't handled where it should be: sleeper/Exited().

**Pull request merged**
