### PR TITLE
fixes donut inhand sprites

### PR DESCRIPTION
**Pull request by Slorbin**
## About The Pull Request

adds donut inhand sprites in right hands 
## Why It's Good For The Game

fixes issue #76058
## Changelog
:cl:
fix: you can no longer tactially stealth-hide donuts in your right hand
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Is your profile from transformise

**Comment by DeerJesus** [comment]
no I’m just a furry

**Review by Mothblocks — APPROVED** [review]
I thought we had a test for this

**Comment by optimumtact** [comment]
damn don't accept any DM's from mothblocks they'll try to make you a tg maintainer okay.

**Comment by DeerJesus** [comment]
> damn don't accept any DM's from mothblocks they'll try to make you a tg maintainer okay.

ill make sure to get my gbp as low as possible

**Pull request merged**
