### PR TITLE
Adds bran requests

### PR DESCRIPTION
**Pull request by PKPenguin321**
🆑
add: The chef can now cook Bran Requests Cereal. Find it in the misc. foods tab in the crafting menu.
/:cl:

Sprite is by me, it's the 4no raisins but the label is now the word "BAN" in the same yellow microfont that 4no raisins used and it has an angry face on the buttom instead of the sun.
bran request

### CODE REVIEW

**Comment by dannno** [comment]
bad sprite

**Comment by dannno** [comment]
i'm redoing vendor stuff soon. just let me do it

**Comment by PKPenguin321** [comment]
nah you can just change the sprite when you get there

**Comment by Armhulen** [comment]
I imagined my raisin bran to be larger

**Comment by PKPenguin321** [comment]
it is a box of raisins with a piece of wheat in it

**Comment by Armhulen** [comment]
could you perhaps add a cardboard box to the recipe and then make the box bigger?

**Comment by PKPenguin321** [comment]
danno is already gonna do that he just said

**Comment by DoctorPork** [comment]
PKP CHAMPION OF THE PEOPLE

**Comment by Armhulen** [comment]
champion of the b r a n

**Comment by ShadowDeath6** [comment]
it looks like it says "duh" to me

**Comment by PKPenguin321** [comment]
There isn't enough sprite space to make anything even remotely legible so really unless you know what it's supposed to say already you probably won't figure out by trying to read it, just like the text on 4no raisins

**Comment by ShadowDeath6** [comment]
just make it a really big angry face :^)

**Comment by Qbopper** [comment]
you're my fucking hero

**Comment by Supermichael777** [comment]
4norasin

**Pull request merged**
