### PR TITLE
smoke machines --> techwebs

### PR DESCRIPTION
**Pull request by silicons**
:cl:
rscadd: smoke machines can now be printed after researching adv biotech
/:cl:

### CODE REVIEW

**Comment by Buggy123** [comment]
Okay but can we actually screwdriver them please? Last I checked they still can't be deconstructed or upgraded without a BRPED because of that.

**Comment by kevinz000** [comment]
no

**Comment by Buggy123** [comment]
So we can construct them but not deconstruct them? Once we build them, to get rid of them we have to break them apart by hitting them with a toolbox?

**Comment by ExcessiveUseOfCobblestone** [comment]
why aren't they inheriting that?

**Pull request merged**
