### PR TITLE
makes crematorium more resistant to damage

### PR DESCRIPTION
**Pull request by ghost**
Armblading the crematorium to dust is somewhat the new ling meta (and very bad.)

It's not quite uh, balanced, to have the only other way to permakill a ling be either gibbing it somehow with the shuttle while avoiding being spaced/it getting up and stinging you or to get some sort of explosive (or some other method that isn't a permakill but generally traps it until another ling frees it).

So the crematorium is resistant to melee and energy weapons, and fire. It's not however immune to acid bullets or bombs, so that it can be destroyed if a ling gets their hands on some sort of bullet weapon like a shotgun or revolver, acid, or an explosive like c4.

This means the crematorium being destroyed is possible, but not as easy as it should be for the main counter to lings.

And before you say 'ex dee gibber' you can grow flesh clothes to avoid that.

:cl: Nanotrasen Engineering Department
tweak: Nanotrasen has provided local space stations with more durable incineration and sterilization devices, located in the chapel, to replace the previous, fragile ones. No official reason has been provided.
/:cl:

this is generally to avoid mostly unkillable lings

### CODE REVIEW

**Comment by RandomMarine** [comment]
Why haven't we ever added an exception to the gibber for ling-"clothes"?

**Comment by GunHog** [comment]
Why not just make them build-able? Btw the gibber (kitchen cold room) works just as well on lings.

**Comment by KorPhaeron** [comment]
tfw you fix the flesh clothes thing 6 months ago
tfw gunhog posts proof of this last time you brought it up a week ago
tfw you just ignore it

**Comment by AdamElTablawy** [comment]
I mean the chitin armor you buttcheek.

**Comment by GunHog** [comment]
Please see https://github.com/tgstation/tgstation/issues/22162#issuecomment-266814830 regarding chitin armor and the gibber.

**Comment by ExcessiveUseOfCobblestone** [comment]
Seems a bit odd to give a machine special armor because the strategy is to break the machine down. That's kind of the point of the damage everything PR, defend it better or build a gibber there.

**Comment by PKPenguin321** [comment]
what stops me from just armblading the crematorium APC instead

**Comment by GunHog** [comment]
Nothing. And nothing is going to stop me killing you and taking you to the gibber instead of the crematorium!

**Comment by FantasticFwoosh** [comment]
> Still can be destroyed, just made it harder for lings to do initially.

What's even the point of this PR if it doesn't fix the problem of 1. instant body destruction being the antags only counter and 2. antags deliberately destroying the 'win conditions' for the crew as to be virtually unkillable.

**Comment by AdamElTablawy** [comment]
Excuse me, Fwoosh, but I think you left your brain at home. Go pick it up.

I'm not interested in touching lings needing to be cremated at the moment. That's nowhere near my concerns and the balance connotations of changing something as innate as that to ling gameplay and how ling always had it is far out of the scope of this pr or any upcoming pr.

If you want to bitch about total bodily destruction being the only counter to an antag bitch all you want, it's not my fucking concern because i'm not touching that with a ten foot pole.

But before we get into the subject of touching ten foot things (probably you and a large dildo) let's look into how fucking ridiculous it is that you decide to spew off 'an this pr doesn't fix ling gameplay' in a pr that isn't intended to. It's like going to a PR that adds a new slime type and bitching about xenobio rng-good point or not it's the wrong place to bitch about it.

But moving past even that let's address that your second complaint is that the crematorium is still destroyable and thus makes the ling 'virtually unkillable' etc and whining about destroying win conditions, etc.

Again, more stupid comments. First off, yes, the crematorium is still destroyable because indestructible irreplacable objects are fucking dumb and destroying or otherwise rendering the crematorium unusable had always been an end goal of lings. Walling it off, bombing it, depowering it, etc. 

The issue is that all of a sudden, compared to the difficulty of doing so before, it is now incredibly easy to remove an antagonist's default and most powerful counter at roundstart, comparable to revs being able to delete all implants on the station at roundstart. Sure you can order more but you have more difficulty getting them.

Same deal here, destroying the cremator means that lings have a huge threat to them gone and can keep fighting with less fear of permadeath. Other methods of disposal still exist but the main and easiest is gone. 

Lings have always been able to do this, but with specific items, like bombs. The issue is it became too easy for them to do, and so now it is back to pre-object damage levels of difficulty to remove your main counter-a ling needs access to bullet weapons, bombs, or a LOT of floroacid, and if a ling has access to the first two or nobody notices them melting the cremator for 10 minutes they're probably way out of crew league anyway.

Not to mention that other counters to ling still exist, for those concerned that they can get cremated again-he gibber is the first that comes to mind, but you could always fuck over a ling by just walling jt in, locking it in xeno or the active turbine, disposal traps-hell, even just spacing it in a welded locked usually means it can't come back, and if worst comes to worst you can gib it with the mining shuttle or even just chuck jt into lavaland and have the miners lava it. Or you can meatspike it and it can never leave before it runs out of blood. The list goes on.

But your complaint isn't even that-it seems to be that lings can destroy the cremator at all, to which i'm gonna first point you to where I demonstrated above how they could always do that, and then i'm gonna secondly point you to a safety padded room if you need a hugbox that bad that you can't deal with a lone, discovered, dead ling.

As for @Pkpenguin321, nothing is there to stop you just like nothing stopped lings from IEDing or welderbombing or deconstructing it before. Apc's can be made pretty easily and quickly and you can always just do any of the above to the ling in the meantime. Hell if you have wood bucklecuff it to a bonfire and splash welding fuel on it-that'll chainkill it for a while. Besides, the AI gets an alert when you smash an APC, as do engineers, all power consoles and all silicons and drones who are probably going to repair it shortly, so destroying a repairable apc is less severe than irrepairably destroying one of the best anti-ling tools.

Besides, lings can always get prescanned and ask a buddy to clone them if they're about to be cremated, so in all honesty destroying the cremator is unnecessary but w/e

**Comment by jughu** [comment]
I mean if a ling really wants to be invincible he destroys the gibber acid the board then destroy cremator acid rnd spare boards and then destroy rnd consoles in science and robotics

**Comment by GunHog** [comment]
> I mean if a ling really wants to be invincible he destroys the gibber acid the board then destroy cremator acid rnd spare boards and then destroy rnd consoles in science and robotics

If he manages to do ALL of this, he deserves to win. And if the ling does all of this, and still gets taken down, toss him into space! If you are lucky, it will take him forever to make it back, especially if he does not have re-adapt points or the space suit unlocked!

**STILL** having trouble with that pesky ling? Kill him again, then hold him in the path of the mining or gulag shuttles! The ling will be gibbed when the shuttle docks!

**Comment by karlnp** [comment]
or cargo, which is far more predictable

**Comment by Aloraydrel** [comment]
Cant you break the button?

**Comment by jughu** [comment]
Z levels aren't random nerd he just needs to jump the same direction back which he came from

**Comment by PKPenguin321** [comment]
>Cant you break the button?

Yeah this too just like screwdriver the button and the cremator is now unusable

Not that I disagree with the intent of this PR but this doesn't solve the issue it's trying to solve at all, there are too many workarounds

**Comment by Cyberboss** [comment]
So much salt today

**Comment by bgobandit** [comment]
>Hell if you have wood bucklecuff it to a bonfire and splash welding fuel on it-that'll chainkill it for a while.

I thought if I had wood I needed to find woody and

**Comment by optimumtact** [comment]
Doesn't solve the problem and makes snowflake armour on a structure.

**Pull request closed without merging**
