### PR TITLE
Radial menu for borg model selection

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Before:
image

After:
image

Inspired by [yogstation13/Yogstation/pull/3638](https://github.com/yogstation13/Yogstation/pull/3638). 

## Why It's Good For The Game
One less clunky list. 
Borg model names can still be seen via mouseover text! 

## Changelog
:cl:
qol: Borg model selection is now done by radial menu
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
wonderful

**Review by Mothblocks — APPROVED** [review]

**Comment by Pumpkinoe** [comment]
Was going to complain about names but saw that you can mouseover. Awesome!

**Comment by SuperNovaa41** [comment]
Is the menu for the specific mining Borg variant also a radial?

**Comment by dragomagol** [comment]
> 
> 
> Is the menu for the specific mining Borg variant also a radial?

Yup! Both mining and service variants already had radials.

**Comment by Makarov22** [comment]
Where are the security borgs?

**Pull request merged**
