### PR TITLE
Visible ghosts emit light

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Visible ghosts emit light.
/:cl:

- They're spooky visible ghosts, they glow enough to shed light on
things, like fireflies of the dead.

image

### CODE REVIEW

**Comment by MMMiracles** [comment]
should probably add it to the ghost simple mob while you're at it.

**Comment by ChangelingRain** [comment]
Do this for varedit too.

**Comment by ChangelingRain** [comment]
Color should change based on the ghost's sprite color.

**Comment by Bawhoppen** [comment]
This doesn't seem right

**Comment by ExcessiveUseOfCobblestone** [comment]
can you make it like really faint.

It's another "l-l-l-loooooooooooooooook attttttttttt meeeeeeee, I'mmmmmmm a GHOoooOOOOOooOOOOOOOOOsttt" episode

**Comment by FantasticFwoosh** [comment]
The worst part of this is that light giving ghosts could be used to meta-game, some additional controls please in which to turn your local light on & off would be great if you want to stalk someone.

**Comment by Bawhoppen** [comment]
you can't stalk someone if you're visible anyways

**Comment by coiax** [comment]
I considered changing the light colour based on the ghost sprite, but some of them are multiple colours and I didn't know what to do

**Comment by Tacolizard** [comment]
_**J I N K I E S**_

**Comment by Cyberboss** [comment]
Could do some strange shit where you grab the center pixel of the icon to determine the colour

**Comment by lzimann** [comment]
for lightning, no color(or i guess all of the colors since white) best color

**Pull request merged**
