### PR TITLE
[s] why I've been an extra caustic cunt PLEASE READ

### PR DESCRIPTION
**Pull request by Iamgoofball**
So for the past month or two I've been dealing with a fun personal situation and I've been taking my anger and confusion out on you guys and I'm sorry

I was dating this really awesome person. She's great. Until January 18th.

What happened on January 18th is she tried to kill herself but failed and got caught. She got sent to the ER, they recommended an institution for treatment, her parents were the ones who were willing to pay for it and they wanted to make sure she was ok. She's in what amounts to a maximum security prison but in the mental health world. She tries to strangle herself or something to die every night she gets the chance and refuses to comply with treatment. Her parents are going to pull the plug on her soon and I know she's going to try again as soon as she's out.

I talked with her today over the phone. She said she's not going to comply with the treatment stuff unless it lets her get out sooner and she didn't care at all about the impact her repeated attempts on her life had on anyone, let alone myself.

I think I see the appeal now.

I'm sorry for being a caustic asshole dick cunt recently because I've been worked up over trying to fix the unfixable for 2 months now and it's really not going well

I was taking it out on all you

You folks have been here through some of the shittiest parts of my life and have been really helpful in keeping it together

Thanks guys

I know it seems like bullshit but you all mean a lot to me

If you know anyone with suicidal thoughts patterns or behaviors please do your best to support and be there for them

### CODE REVIEW

**Comment by optimumtact** [comment]
This really isn't appropriate to commit to a public forum goof

**Comment by optimumtact** [comment]
Also this is the wrong place for this

**Comment by Iamgoofball** [comment]
I felt an apology was in order and an explanation

**Comment by Iamgoofball** [comment]
I felt an apology was in order and an explanation

**Comment by optimumtact** [comment]
Also it might be misplaced but do reach out to a local support hotline if you feel like you need to talk about how it affected you as well.

https://en.wikipedia.org/wiki/List_of_suicide_crisis_lines

**Comment by Iamgoofball** [comment]
Thanks

**Comment by Niknakflak** [comment]
Showboating

**Pull request closed without merging**
