### PR TITLE
View Own Notes Readabily Fix

### PR DESCRIPTION
**Pull request by Deantwo**
Adds a line brreak (`"<br>"`) after each note.

Fizes https://github.com/tgstation/-tg-station/issues/7337.

Picture:
view player notes

### CODE REVIEW

**Comment by Miauw62** [comment]
PR Markdown brotip: you can escape HTML tags by using backslashes, as such: ```\<br\>``` \<br\>

**Comment by Deantwo** [comment]
I just wanted to see what would happen if I used HTML and PenCode in it.
But yeah, it worked just fine.

**Comment by ike709** [comment]
ass effects detected, please purge hostile FILE_DIR takeover

**Comment by Deantwo** [comment]
Ok? Something you are gonna fix?
Or will you slowly and detailed explain to me what your talking about?

**Comment by JJRcop** [comment]
begin git transmission
```git reset --soft HEAD~1```
```git checkout -- tgstation.dme```
```git commit```
```git push origin BrBreaks```

**Comment by Miauw62** [comment]
You have to set your preferences and untick "automatically set file_dir", else it will cause what you can see in the diffs: it'll add a bunch of FILE_DIR defines to the .dme which makes loading sprites slower.

**Comment by Deantwo** [comment]
Oh. You mean I forgot to not include **tgstation.dme**.
Why didn't you just say that?

**Comment by Miauw62** [comment]
(pssst, if you go to build > preferences for tgstation > untick automatically set file_dir you never have to commit the .dme unless you're adding/removing files)

**Comment by Deantwo** [comment]
Making a commit to revert it was easier...
No complains about that wait... right?

**Comment by Miauw62** [comment]
Eh, its ok.

**Pull request merged**
