### PR TITLE
E-mags now have 15 uses.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
balance: Emags now have a limited amount of uses. 15 to be precise.
/:cl:

My take on the fun discussion we're having right now, feel free to close this if the other options are preffered. I think this will inherently lower the amount of doors opened with the emag (Or only very specific ones) because it'll waste the small amount of uses. I currently set the uses to 15 but I'm also considering 10 or 12.

### CODE REVIEW

**Comment by Farquaar** [comment]
To be honest, I don't mind this.
Emag has always made engineering and security's life a living hell. Having 15 or 20 uses still allows them to do this, but it requires a bit more thought as to which doors you open.

**Comment by Homingpenguins** [comment]
Fulp already made a sort of nerf like this. We left the emag as it is. But incresed the cost to 15 TC. We then made another emag that is only 6 TC. But has 3 uses. And recharges a use every 30 seconds. So you cant go guns blazing.

**Comment by Twaticus** [comment]
> Fulp already made a sort of nerf like this. We left the emag as it is. But incresed the cost to 15 TC. We then made another emag that is only 6 TC. But has 2 uses. And recharges a use every 30 seconds. So you cant go guns blazing.

ok recharging emag sounds awesome

**Comment by Shadowflame909** [comment]
This is very silly and ultimately incentivizes other cheaper ways of getting in somewhere.

Like just buying an infinite charge dual e-sword/e-sword to allow you to break in anywhere unlimited times.

Or buying an agent card, that allows you to take the access of anyone you kill.

Not good for game design, disincentivizing sabotage items only incentivizes the more lethal road.

**Comment by Qustinnus** [comment]
that sounds more like an issue with those items rather than a merit for this one.

**Comment by Shadowflame909** [comment]
There are a lot of ways to break in qustinnus. More lethal then non lethal.

E-mag was the best one, and it just happened to be non-lethal.

This changes the meta, and I think it'd be easier for players to accept using their door breaker as a lethal weapon, then spending 6 tc on a door breaker that breaks.

**Comment by wesoda25** [comment]
I considered making this PR sometime back but decided against it because A: its uncalled for and B: emags number of uses isn’t what makes its powerful, its its versatility. The only time an emags number of uses becomes an issue is when someone is being a shitter and emagging literally every door open, but this, like lings transformation stinging everyone, is something that is obvious and that the crew should handle.

**Comment by Qustinnus** [comment]
alright I'll close this and go with MrDoomBringer's approach then

**Pull request closed without merging**
