### PR TITLE
Freshen up virology

### PR DESCRIPTION
**Pull request by pubby**
Adds a few new symptoms and reworks old symptoms.

### Removed Symptoms:
- **Alkali Persperation:** This has been combined into Spontaneous Combustion.

### New Symptoms:

- **Explosive Death:** Virus creates a small explosion when its host dies. Replaces the explosive effect of Alkali Persperation.
- **Surface Healing:** Heals you when you're barely scratched, but does nothing if your injuries exceed 15 damage. It's largely irrelevant in combat.
- **Observer Effect:** Virus gains stages whenever it is scanned by a medical analyzer. The CMO's analyzer doesn't trigger it.
- **Scan Defense:** Virus violently destroys medical analyzers that scan it. The CMO's analyzer doesn't trigger it.
- **Plasma Flatulence:** Causes you to fart a tiny bit of plasma gas every now and then. Combos with other plasma-based symptoms.
- **Wet Flatulence:** Like plasma flatulence, but creates water vapor instead of plasma. It's annoying, but harmless.

### Changed Symptoms:
- **Sneezing:** Worse stats. It's no longer a no-brainer to include.
- **Vomit:** Slightly better stats.
- **Confusion:** Slightly better stats.
- **Dizziness:** Slightly better stats.
- **Narcolepsy:** Slightly better stats.
- **Choking:** Slightly better stats. 
- **Nano Boost:** Different stats.

### Why

Virology obviously needs a rework, but until that time comes we might as well make it as best as we can in the current framework.

## Changelog
:cl:
add: Several new virus symptoms
remove: Alkali Persperation
tweak: Change symptom stat values
/:cl:

### CODE REVIEW

**Comment by Therapist1** [comment]
Good PR (time for the revitaligo wet farting virus)

**Comment by 4dplanner** [comment]
"CMO's analyzer doesn't trigger it"

lame tbh

**Comment by Moja10** [comment]
if science does their job they medical protolathe can poop out CMO scanners by the dozen

**Comment by Tlaltecuhtli** [comment]
stealth fart add 👀

**Comment by Angustmeta** [comment]
Rip my 60+ virus spreadsheet, but this is awesome. I particularly like the anti-health analyzer symptoms. And we'll be able to create human water vapor/plasma fart-farms. 

I can tell you've put some thought into it. The symptoms you buffed were mostly things I had trouble fitting in without gimping the virus (such as nano-symbiosis or choking). 

To figure out if these new numbers/symptoms are balanced or not I'd have to wait for a merge and make 30 new viruses. It's going to take a while.

**Comment by Michael-Ashfield** [comment]
A good idea for a level 8 symptom is race change, changes you into a random safe race (moth, human, lizard, ethereal, fly, cat), threshold resistance will add unsafe races (pod, shadow person, plasma man, slime, skeleton e.c.t.).
It will have really low stats and a fair few text warnings so people can be cured, but a good virologist could have some fun with it.

**Comment by imsxz** [comment]
how quickly does the gas from the farting symptom add up? wondering because 1 mole water vapor seems like it'll vanish instantly and leave nothing

**Comment by pubby** [comment]
1 mole of water vapor creates about a 3x3 wet spot.

**Comment by uBadush** [comment]
how is nerfing sneeze a buff ?

**Comment by nicbn** [comment]
One does not simply get off of Mr. Viro' Wild Ride

**Comment by XDTM** [comment]
The scan symptoms feel way too metagamey imo, a virus pinpointing and remotely detonating a device that just so happens to be the main tool to fight feels out of place, as well as possibly overpowered

**Comment by XDTM** [comment]
Also, if you want to solve the issue of having symptoms not being worth their slot on a virus, change the symptom limit system so different symptoms have different slot costs, so minor stuff does not take the same space as a major symptom.

**Comment by Shadowflame909** [comment]
>Adding farts


Test this on citadel first and tell us the research here. Cat-girls already abuse hygiene to be weird about it.

What will we do once the catgirls start abusing this

**Comment by OverlyGeneric** [comment]
> > Adding farts

Goonstation and Hippie are fine. It's not weird to have butt for an organ.

**Comment by ArcaneMusic** [comment]
Look, you can leave the functionality as is, but dear lord name the "flatulence" something else. Maybe claim it's being produced in the lungs or the appendix, or something. Just don't give the really creepy players more fuel.

**Comment by ATH1909** [comment]
Since you're changing narcolepsy's stats, can you also make it not suck horribly? I'm pretty sure that the person who coded it thought that the minumum and maximum symptom delay values were measured in deciseconds, not seconds, resulting in a laughably bad symptom (as far as I can tell by looking at the code), even with all of its thresholds met.

Add a normal flatulence symptom that makes miasma.

Will health analyzers still return data before exploding?

All in all, looks like a good PR.

**Comment by ArcaneMusic** [comment]
>
> Add a normal flatulence symptom that makes miasma.
Or we can call it Halitosis to again, not make it fucking creepy.

**Comment by Shadowflame909** [comment]
Also, Sneezing is a round start culture for a good reason. That being it's for non antagonist virologists to spread good diseases. I feel like it's an unessecary nerf that'd kill virologies usefulness in transferability. Considering it wastes a slot for self infection anyways. It's like removing non antag transferability all together. If you want a decent healing virus.

**Comment by Tlaltecuhtli** [comment]
once this gets merged farts will be the mayor vector of not antag disease transmission

**Comment by pubby** [comment]
I've changed the wet farts symptom to be burps instead. One fart symptom is good. Multiple is overdoing it. 

Narcolepsy works now. 

Also added a few sound effects.

**Comment by ATH1909** [comment]
> I've changed the wet farts symptom to be wet burps instead. One fart symptom is good. Multiple is overdoing it.
> 
> Narcolepsy works now.
> 
> Also added a few sound effects.

Thanks.

You DID check to make sure that narcolepsy won't perma-sleep people now, right?

**Comment by uBadush** [comment]
No one considered that adding more symptoms will make virology harder because rng

**Comment by Shadowflame909** [comment]
don't forget that nerfing sneezing also makes an already useless antag even less of a threat. If that's even possible

**Comment by Grazyn** [comment]
Only one sound for burps and farts? Some variety wouldn't hurt

**Comment by ExcessiveUseOfCobblestone** [comment]
haven't looked at PR to any real extent but don't forget about sentient disease.

**Comment by WJohn** [comment]
Does explosive death gib you when you die, like a microbomb implant?

**Comment by pubby** [comment]
I think it can delimb but it's not supposed to gib.

**Comment by ExcessiveUseOfCobblestone** [comment]
Not a fan of burping/tooting, can you not fluff it as something else?

**Comment by Graporb13** [comment]
It could be something along the lines of plasma persperation, as alkali persperation is gone and it won't seem like a copy. Not sure about the burping one though, would seem like that smelly or whatever symptom.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'll accept them if catgirls can't get them and be weird with it :^)

**Comment by pubby** [comment]
Fart/burps are realistic disease symptoms. I don't intend to change them myself. I'm sure if they're too obnoxious, someone will PR a change within a week.

**Comment by ExcessiveUseOfCobblestone** [comment]
The reason I want them gone has nothing to do with realism.

**Comment by Shadowflame909** [comment]
Pubby you and I know that porting farts and burps to bagil will only appease people too young to play here- or quite literally fetish shit posters. Which is why I say. A change like this should go to the Citadel codebase. Much more mature to handle this, and you'd see unironic use for it.

**Comment by Nabski89** [comment]
This PR is terrible if you don't like dying randomly to viruses, as well as for the content of it.

You've raised the transmittal level on sneezing, which makes 4 more deadly symptoms able to be airborne.
You've boosted nano's to stage speed 4, which allows you to double up on deadly symptoms without having to give up the thresholds they were balanced around.
You're trying to re-add no-risk no-downside healing, under the reasoning that it doesn't activate if you've taken more than 25 damage per type.
Throw on top of that all the weird farting stuff.

Pretty sure the explode on death would be hilarious to sneak out into the wild with a bunch of stealth, and adding sound effects where they weren't previously get used is nice.

I feel like you have a mix of good and terrible ideas, but your ability to tell the difference is overwhelming.

**Comment by ExcessiveUseOfCobblestone** [comment]
Once the offending symptoms are refluffed to something else i'll do an actual review of the PR

**Comment by pubby** [comment]
anyone is welcome to branch off of this

gonna spend my time elsewhere

**Comment by Fume309** [comment]
i think that the idea of farts and burps being deemed to childish for a game with space clowns is kinda stupid. however I want those sensor changes to go through so I'll play ball.

perspiration is the obvious solution to the problem. it can even be applied to the wet farts/burps by calling it vaporous perspiration (calling it perspiration instead of sweat because yea catgirls are weird). I dont know how to code though so not going to be able to change it.

**Comment by zeskorion** [comment]
> anyone is welcome to branch off of this
> 
> gonna spend my time elsewhere

it's nearly a year later but i may steal some of your code here

**Pull request closed without merging**
