### PR TITLE
((spiderpalooza?)) Giant Magma Spiders!

### PR DESCRIPTION
**Pull request by ghost**
I need these for a ruin i'm adding to replace the simplemob xenomorphs. I have sprites for them, and i'll put em in when I have time. I probably need a more balanced poison than fire you can't put out.

### CODE REVIEW

**Comment by Armhulen** [comment]
Also i'll be adding special ice spider sprites if i can, no more i'm you but bluer!

**Comment by The-clown-known-as-Pepe** [comment]
>ice spiders

freeze

**Comment by Armhulen** [comment]
wait there is a freeze haha heyoo that's funny

**Comment by JJRcop** [comment]
At least you closed it so you can reopen it later

**Pull request closed without merging**
