### PR TITLE
Allow tabling small machinery

### PR DESCRIPTION
**Pull request by SpaceManiac**
:cl:
add: The following machines can now be tabled: all-in-one grinder, cell charger, dish drive, disk compartmentalizer, microwave, recharger, soda/booze dispenser.
add: Unanchored soda/booze dispensers can now be rotated with alt-click.
/:cl:

The following machines have had `PASSTABLE` added due to typically being placed on tables, in case they are made movable in the future, but this PR does not make them movable: 
* wooden TV
* medical laptop
* security laptop
* plant DNA manipulator
* book inventory management console

### CODE REVIEW

**Comment by kevinz000** [comment]
🤔

**Comment by Vidiveni** [comment]
Glad to see this happen. Moving a microwave was a bit tedious.

**Comment by Wilchenx** [comment]
>medical laptop
>security laptop

why weren't these replaced by actual laptops we have

**Comment by Bawhoppen** [comment]
@SpaceManiac IIRC, the med and sec laptops have something in their desc explaining that they're bolted to the floor/table, which is why they can't be moved. Probably would be wise to remove that if we're making them pseudo-movable.

**Comment by SpaceManiac** [comment]
The med and sec laptops are goofy for other reasons (screwdrivering them causes them to become large computers), this doesn't add the ability to unwrench them.

**Comment by Tlaltecuhtli** [comment]
can we just delete those laptops; they are never used, their sprite sucks and they are snowflake

**Comment by Cyprex** [comment]
>Stationary computers
>Laptops
>Laptops are just reskinned stationary computers that cannot be moved at all
I will never get over the disappointment of this.

**Pull request merged**
