### PR TITLE
Adds linking datums in asay

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
Want to easily share a datum with other admins/coders so they can look at it too? Don't want to deal with walking them through the steps to reach the datum from other datums? You can now link them in asay! 

[](https://i.imgur.com/3hX3XYu.png)

[](https://i.imgur.com/lnWE90Y.png)

Just take the REF for the datum (now printed underneath the fancytype in VV) and post it to asay (without brackets). This allows the other admins to click on the link to open up the datum's VV window directly. This PR also makes datums you've tagged show their tag index along with the other marked/var-edited/deleted tags.

I'd like to have the ref line in VV be clickable to automatically copy it to your clipboard, but I'm not well versed on JS, so if anyone has a quick way of doing so, it'd be appreciated.

## Why It's Good For The Game
This is something I've wanted for a long time, allowing you to directly link certain datums to other admins quickly and efficiently.

## Changelog

:cl: Ryll/Shaps
admin: You can now create links to a datum's VV window in asay by posting the datum's memory reference. The reference is now printed in the VV menu right below the fancytype, for copying purposes..
admin: Tagged datums will now show their tag index in VV
/:cl:

### CODE REVIEW

**Comment by Jordie0608** [comment]
What happens when you click on a ref that no longer exists?

**Comment by Ryll-Ryll** [comment]
> What happens when you click on a ref that no longer exists?

Basically the same as if you refresh the VV window for a datum that no longer exists. Brings up whatever new datum is at that memory location if there is one, or brings up the VV menu for the deleted datum's information with the [Deleted] line at the top. 

I'm not concerned with people clicking old links and getting the wrong datums, since ideally you should be communicating in asay what you're linking to so other people know if they're getting the wrong thing or not.

**Comment by Jordie0608** [comment]
Yeah, sounds fine.

**Comment by Mothblocks** [comment]
We should fix that on VV too FWIW, I set somethings loc to null and it literally GC'd right under me and fucked up a random lighting plane, lol.

**Pull request merged**
