### PR TITLE
Holy skateboard improvement + actually fixing space movement with hoverboards.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Added anti-magic support for things that mob can buckle to, so that we don't have to add the anti-magic component to the mob riding the holy skateboard but the skateboard itself.

Also, made it possible for the holy skateboard to soar space and open space with no support without falling, at the cost of a moderate slowdown.

## Why It's Good For The Game
It's a first-time contributor that added this skateboard to the game, and it looked like he couldn't find a solution to some of the issues I brought on in my review. Plus the holy skateboard being usable in spess has some real Space Jesus vibes to it.

## Changelog

:cl:
fix: ACTUALLY fixed hoverboards being able to be used in space.
balance: However, you can soar space with the holy skateboard. at a slower speed.
/:cl:

### CODE REVIEW

**Comment by Dawnseer** [comment]
Gonna kickflip right into the voidwalker once it gets merged

**Comment by DrAmazing343** [comment]
Good on ya for helping the new contributor. They had a FIRE fucking idea, love the Holy Skateboard.

**Comment by Loafin34** [comment]
thank you.

**Comment by MercuryArrow** [comment]
I've already used the board in space a few times, are you saying that's not supposed to be happening already?

More love for the board is welcome regardless.

**Comment by Ghommie** [comment]
> I've already used the board in space a few times, are you saying that's not supposed to be happening already?
> 
> More love for the board is welcome regardless.

Ok, it turns out I didn't fix it properly, though I thought I had tested it. I will in a jiffy.

**Pull request merged**
