### PR TITLE
ERT Balance Pass 2 | ERT Access and Foam

### PR DESCRIPTION
**Pull request by Steelpoint**
This balance pass see's four changes to the ERT, they are...
- New access for the ERT base. Prior players would simply go into any room and take whatever they liked, meaning you would see mismatched equipment given to random Officers, at worst people would steal items that did not belong to them (Commanders Revolver for example). The new access means that only someone with the relevant ID can enter a equipment room, so Sec can only go into a Sec room. The Commanders ID is the exception, he has access to all areas, but the Commander already spawns with his ID so there's no threat of someone taking it first.
- The ERT Commander now spawns in wearing his hardsuit (not helmet), this is to immediently distinguish him from his counterparts and to remind the player that they are the commander. 

Because of that, the Commanders room has had the Suit Storage removed and replaced with a table holding a oxy tank, mask and the ERT Comm Helmet.
- Two boxes of Metal Foam Grenades (7x Grenades) has been given to the ERT Engineers, people really liked the grenades but want more.
- The Gygax's Heavy Laser Cannon was replaced with a Pulse Cannon. 

Thank you.

### CODE REVIEW

**Comment by Deantwo** [comment]
Oh yes, Metal Foam Grenades are the best!
Just freaking Chemists tend to put too much acid in them...

**Comment by TZK13** [comment]
Could you add some loyalty implants to the commander's room, yesterday an ERT was made manually which meant we lacked loyalty implants and later on when I tried to use my pulse pistol I was unable to because of the loyalty firing pin. Had to get a loyalty implant from the HoS just to use my own gun.

**Comment by Steelpoint** [comment]
Seems like a trial admin was on.

I'll throw a box of 7 Loyalty Implants to the Commanders Office.

**Comment by Durkel** [comment]
The gygax doesn't have a laser cannon, it has a normal mech laser. Perhaps you should just upgrade it to a cannon before jumping to a pulse variant?

**Comment by Stickymayhem** [comment]
Could you make the door leading to the shuttle require ert access fuckwits keep running in to loot stuff while I'm setting things up

**Pull request merged**
