### PR TITLE
repaths neurotoxin + embedding changes in bullets + adds effects when you shoot energy weapons

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

repaths neurotoxin from obj projectile bullet neurotoxin to obj projectile neurotoxin
i thought it would be cute so i made it be affected by bio armor instead of bullet
makes bullet types that shouldnt embed like bananas or rockets not embed
adds a cool effect when you shoot something with an energy (not laser) weapon (which was unused for some reason) or shoot with neurotoxin

## Why It's Good For The Game

image

## Changelog
:cl:
fix: neurotoxin and some other bullets no longer get embedded in you
add: some cool effects are added when you hit with an energy weapon or neurotoxin
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Honestly the idea of some kind of weapon that embeds in you and slowly cripples you until you or someone else can pull it out sounds very cool. Put a sticky note on this idea for later.

**Comment by ArcaneDefence** [comment]
I am devastated that you want to take my embedding banana cannons away from me. 

Kinda hyped about that neurotoxin change though. Biohoods already serve a good role in counter-xeno, and I like that it's in line with that

**Comment by Pugie** [comment]
remove its stun too...

**Comment by Fikou** [comment]
> Kinda hyped about that neurotoxin change though. Biohoods already serve a good role in counter-xeno, and I like that it's in line with that

its just 5 toxin damage dont get that excited over it being 0 it still stuns...

**Comment by ATH1909** [comment]
you'll still be able to deflect neurotoxin with sleeping carp, right? it's hilarious to watch a xenomorph queen waste all of their plasma by spamming neurotoxin at you, even after they see you deflect it.

**Comment by ArcaneDefence** [comment]
It's only a matter until the xenos scum fall victim to the stun meta changes, and nerotoxin becomes a knockdown with stam damage.

Don't even try to pretend it will remain a taser forever.
Its heretical ways are numbered

**Pull request merged**
