### PR TITLE
Biogen dispenses botany chems in more user-friendly volumes.

### PR DESCRIPTION
**Pull request by Winterous**
## About The Pull Request
THIRD TIME'S THE CHARM?

You know what's super fun? When you want to fill a hydro nutrient bottle from the bio generator, and it only produces the stuff 30 units at a time, and the container you're using can only hold 50 units, and the generator won't overfill the container, so you can't fill the container completely without removing the container, removing 10 units from it by some means, then putting it back in and clicking the button again.

I love that.

## Changelog
:cl:
tweak: The biogenerator in hydroponics will now dispense botany chemicals in volumes that aren't specifically designed to upset the user.
/:cl:

### CODE REVIEW

**Comment by Winterous** [comment]
Oh thank god, it was auto-committing some changelog stuff I wasn't telling it to, and I had to figure out how to remove it.

**Comment by Jared-Fogle** [comment]
just force push the branch next time bro

**Comment by Barhandar** [comment]
It dispenses them 30u at a time because bottles in the vendor also have 30u at a time.

**Comment by Winterous** [comment]
> 
> 
> It dispenses them 30u at a time because bottles in the vendor also have 30u at a time.

Incorrect. They're 50.

**Comment by ArcaneMusic** [comment]
Wouldn't it make far more sense to dispense them 1u at a time and then use the built in UI option to select how many units to dispense, while scaling the biomass cost accordingly?

**Comment by Angustmeta** [comment]
> Wouldn't it make far more sense to dispense them 1u at a time
That would be require more aimed clicks and be very tedious. My forehead cramps when I need to specify amount in TGUI Next.

**Comment by ArcaneMusic** [comment]
> > Wouldn't it make far more sense to dispense them 1u at a time
> 
> That would be require more aimed clicks and be very tedious. My forehead cramps when I need to specify amount in TGUI Next.

You can click the number region and type a quantity in.

**Comment by Angustmeta** [comment]
> You can click the number region and type a quantity in. If not, then by all means carry on.

Having to type and specify is what I hate

**Comment by Winterous** [comment]
> 
> 
> Wouldn't it make far more sense to dispense them 1u at a time and then use the built in UI option to select how many units to dispense, while scaling the biomass cost accordingly?

Maybe but when you're growing plants you don't want to need precision, you want to dump out the 3.6 units you have remaining in your nutrient bottle and fill it up quickly.

**Pull request merged**
