### PR TITLE
Corrects crab pathway. Crab can be cooked again.

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

Someone listed the raw crab meat grilling process with /slab/ in the path. I don't think crab was ever actually cookable since this happened so uh... yeah, I guess we went almost a year without noticing this.

Edit: Okay, apparently a bunch of maps were checking for /slab/ for their crab. Crab has been updated to include the /slab/ pathway so that maps won't scream at me.

## Why It's Good For The Game

Fixing broken things is good.

image

## Changelog

:cl:
fix: error in crab pathway. Crab can be grilled again.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
medium rare crab when?

**Comment by carshalash** [comment]
> medium rare crab when?

I will share my pavlova with jackraxxus instead of you if you keep this up.

**Comment by optimumtact** [comment]
wtf

**Comment by datorangebottle** [comment]
freecrab

**Review by spookydonut — APPROVED** [review]

**Pull request merged**
