### PR TITLE
Orbital Cannon Icons

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Reassembled ausops bluespace artillery into a single icon, have plans for this later but I don't know what computer I'm gonna be on next so may as well put the files here forever.

sprite PR no pictures etc, this sprites have been in the game for 4 years now

### CODE REVIEW

**Comment by Jordie0608** [comment]
If you're doing this you should remove the previous segmented icons and their associated placeholder structures

**Comment by WJohn** [comment]
I doubt ausops would be masochistic enough to want to make up/down sprites for this, so we're stuck with left/right.

**Comment by Supermichael777** [comment]
un powered derelict that needs huge power to fire. powering up should take effort so no single solar panel dear gun like science would get

**Comment by Kromgar** [comment]
You know... you could totally implement the bluespace cannon as some bluespaced ruin on lavaland. That thing was like 8 tiles long wasnt it?

**Comment by KorPhaeron** [comment]
It wont be a lavaland ruin

**Comment by KorPhaeron** [comment]
I will when I do the actual PR @jordie0608

**Comment by Jordie0608** [comment]
It's almost like there wasn't any point in this PR then

**Pull request merged**
