### PR TITLE
Updates modular computer Nanotrasen logo

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes the sprite issue described in #32802

The nanotrasen standby screen from FTL wasn't imported with the directional sprite update. 

That said, their standby screen isn't good because it was just a static sprite and didn't have the glimmer animation our current one does, and whoever made it in the first place was lazy and just mirrored one of the sprites, leading to the N being backwards. Ergo, I had to remake the screen (which was a PITA since the E & W sprites had weird perspectives.)

:cl: ShizCalev
imageadd: The Nanotrasen logo on modular computers has been fixed, rejoice!
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
https://i.imgur.com/H8PbCbI.gifv

**Comment by DapperMola** [comment]
image

**Comment by DapperMola** [comment]
Working as intended I see.

**Comment by ShizCalev** [comment]
@DapperMola It has to be merged, first.

**Comment by DaxDupont** [comment]
It's amusing to see people complain about things that haven't even merged yet.

**Comment by praisenarsie** [comment]
@DaxDupont people don't know how github works i guess (and tgs too i guess)

**Comment by DapperMola** [comment]
Oh sorry, I've never touched github before, just wanted to report a bug.

**Comment by DaxDupont** [comment]
@DapperMola you want this tab
fbyl23e 1

**Comment by DapperMola** [comment]
In hindsight that makes a lot more sense, thanks.

**Comment by ike709** [comment]
My bad.

**Pull request merged**
