### PR TITLE
Ports Nienhaus's playable guitar and generalizes instrument code.

### PR DESCRIPTION
**Pull request by Boggart**
Ports @Nienhaus's guitar from UristMcStation, the additional sounds are about ~1mb.
Moves most of the code from violin up to instrument and makes violin a child of it. Guitar code is also redone as a child of instrument.
Fixes violins on Metastation and Box due to the repath, adds guitar to both.

**Edit:** [Preview](http://boggart.github.io/mediaplayer/autoplay.htm#https://dl.dropboxusercontent.com/u/83869314/ShareX/2015/04/guitartest.mp3) (May not work with all browsers, if not use [this link](https://dl.dropboxusercontent.com/u/83869314/ShareX/2015/04/guitartest.mp3).)

### CODE REVIEW

**Comment by Incoming5643** [comment]
Somewhat less exciting since someone made the "mute instruments" pref and had it default to on

**Comment by Iamgoofball** [comment]
We should remove the violin and replace it with this.

**Comment by Fox-McCloud** [comment]
I can confirm the guitar sounds infinitely better than the violin and isn't so grating on the ears, even if played for goodness knows how long.

**Comment by SconesC** [comment]
death to the violin

**Comment by Boggart** [comment]
I can remove the violin if that's what's wanted, but there are some songs that sound good on it.

**Comment by stapler2025** [comment]
Best PR 2015 merge immediately

**Comment by WJohn** [comment]
I think we should keep the violin, a lot of people who liked it would be sad, and wed be cutting down on band instrument diversity!

**Comment by stapler2025** [comment]
Remove clown, add guitar

**Comment by Dorsisdwarf** [comment]
Give the service borg a  guitar.

**Comment by Boggart** [comment]
I already did actually, but forgot to mention that in the PR.

**Comment by Boggart** [comment]
Merge conflicts fixed, @Jordie0608.

Does anyone have issues with the filesize?

**Comment by Boggart** [comment]
I did a commit to rename violin.dm before changing it to preserve the git history and fixed the new merge conflicts.

**Comment by volas** [comment]
Maybe something I don't know, but it sounds like a guitar made a year ago by @Bartnixon for Tau Ceti Station (Russian community, we are based on Baystation12 build).
In any case, he would like someday to port it to TG and Bay. However, I regret that he is not mentioned in the authors. I hope @Nienhaus will be able to clarify the situation, or to say that I'm wrong.
You can find our guitar and other instruments (harmonica and another version piano sound) here: http://tauceti.ru/files/musical_instruments.zip

**Comment by Nienhaus** [comment]
Yeah, i got the files from Bart. On Urist a lot of the time we don't talk in this and just use Steam, when I made the first PR for Urist Glloyd knew I didn't make the sounds. I've also said it in the IRC but never hear.

**Comment by Boggart** [comment]
Hm, I might be able to do a PR to edit the changelog entry to add a credit to @Bartnixon for the sounds but at this point I doubt the commit message can be changed. As far as porting the others I'd love a harmonica but I wasn't sure the guitar would even get in since multiple people raised concerns in irc about the additional filesize of the sounds (~1mb).

**Comment by volas** [comment]
No problem, @Nienhaus. I realize that it happened not on purpose.Thanks for answering.

**Comment by Jordie0608** [comment]
I'll edit the changelog entry to credit him.

**Pull request merged**
