### PR TITLE
Nightmare's Light Eater Gets "Critical Hits" (See Inside)

### PR DESCRIPTION
**Pull request by IndieanaJones**
## About The Pull Request

This PR adds a new mechanic for Nightmare, which I've dubbed "critical strikes". If Nightmare stays in jaunt for 15 seconds, its light eater will get a red glow in the inventory, along with a balloon alert which says, "critical strike ready". Visually, it looks like this:
image
If Nightmare hits a mob with the light eater in this state, one of four things will happen:

- If its a carbon that isn't a hulk, the carbon will be stunned for 1 second, dropping their items in the process
- If its a cyborg, the cyborg will be stunned for 2 seconds (twice the health, twice the fear factor required)
- If its a simple/basic mob or a hulk, the mob will take double damage from the strike (50 as opposed to 25)
- If the target is dead, you'll note how you wasted the critical strike, but had fun doing it

While the stun itself is not very long, it will cause crew to drop their held items and be unable to act for a short duration, which should be useful for ambushing lone wolves and causing more prepared crew to have to scramble to get their gear off the floor when caught.

If the Nightmare uses the critical strike, it will go away and require Nightmare to stay in jaunt for 15 more seconds in order to regain it. Manifesting while your critical strike is recharging will also stop and reset the timer.

## Why It's Good For The Game

Nightmare is simple, gory fun, and there's nothing wrong with that. However, Nightmare performs poorly in any scenario where someone has some basic gear, since it lacks the ability to use stun batons, has no armor, and has no stun resistance itself, which means how much a Nightmare can actually do tends to be very little. While some buff proposals seek to add complexity to playing the role, I think this one is clean and simple to use while effectively buffing their proficiency in 1v1 combat (perfect for an ambush playstyle), giving players a reason to be afraid of going up against or getting caught out by the Nightmare alone.

## Changelog
:cl:
balance: Nightmare's Light Eater can now stun targets under certain conditions.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
this should make the crit effect sometimes pop up when it crits, like how lucky .38 bullets do.

Not constantly, I think that'd be really goofy, but just like every so often.

**Comment by IndieanaJones** [comment]
Yeah sure, I can do that (thinking like on a 1/1000 chance so its super rare, maybe add the chance value as a var for admins to mess with (crit-hacking Nightmare event)). I'll also have hulks receive the double damage like simple/basic mobs do when I remember how to tell if someone is a hulk or not.

**Comment by necromanceranne** [comment]
it's a dna check, have a look at scarp I know it has a check for it in the reflect code there.

**Comment by ATH1909** [comment]
15 seconds seems a bit long, especially since nightmares don't inherently have maintenance access and usually need to jaunt past doors if they haven't killed someone with maint access yet. Maybe cut it down to 10?

**Comment by Dorsisdwarf** [comment]
> 15 seconds seems a bit long, especially since nightmares don't inherently have maintenance access and usually need to jaunt past doors if they haven't killed someone with maint access yet. Maybe cut it down to 10?

reliably stunning people and making them drop their gear as the "kills anyone who doesnt have the gear to down them before they smack you 3x" antag sounds pretty powerful, thats probbably guaranteeing the kill against anyone who gets jumped without serious defensive gear. I dont think it needs to be dropped to such a short timer since it seems like the point of this is to empower nightmares to lurk defensively and kill validhunters.

**Comment by SomeoneYouProbablyKnow** [comment]
I assume it's nightmare specific and will not transfer to gamers who steal the armblade but if not ... it really should be.

**Comment by IndieanaJones** [comment]
> I assume it's nightmare specific and will not transfer to gamers who steal the armblade but if not ... it really should be.

I forgot eating the heart gave you JUST the armblade. I'll tie it to the antag datum.

**Comment by IndieanaJones** [comment]
New changes:
- Hulks will receive double damage like simple/basic mobs since they are immune to stuns
- Only wielders of the light eater with the nightmare antagonist datum will get critical hits

**Comment by Admiral-Gigaton** [comment]
Don't think nightmare should get more buffs, they can jaunt away from stuns and by the time you hit em they had hit you and can jaunt, because your light is broken now

**Comment by Deadgebert** [comment]
the stun makes this a guaranteed kill on any random player that is unfortunate enough to get hit by the nightmare. 50 damage already is enough to slow them enough to get chased down. plus i'm pretty sure it's an extremely high chance of weeping avulsion, right? 
nightmare is already extremely rewards for a 'cowardly' playstyle, i dunno if they should be rewarded more with guaranteed kills

**Comment by SomeoneYouProbablyKnow** [comment]
The biggest problem is that hightmares will disable sensors and behead. If they didn't do that and just generated bodies in maints that would be good but oh well

**Comment by IndieanaJones** [comment]
A couple of things to note:

- If by "more buffs" you're referring to that bullet dodge mechanic Jac fixed, it was always a part of nightmare's kit. It was a bug it wasn't working
- Hitting people to disable their lights is finnicky, as there's a lot of ways around it (dragging lights for example)
- It's very likely that natural beheading is going to be removed, so while Nightmare could turn off your suit sensors, beheading you will likely be impossible
- You can still stun Nightmare with a flash or any flavor of baton if you're quicker to the punch
- If you go into maint while there is an active Nightmare without taking proper precautions, I argue its your fault and the consequences (such as death) are deserved. If a Nightmare gets their hands on you and it isn't your fault, that's just the nature of the game in that you don't always win

**Comment by Admiral-Gigaton** [comment]
> A couple of things to note:
> 
> * If by "more buffs" you're referring to that bullet dodge mechanic Jac fixed, it was always a part of nightmare's kit. It was a bug it wasn't working
> * Hitting people to disable their lights is finnicky, as there's a lot of ways around it (dragging lights for example)
> * It's very likely that natural beheading is going to be removed, so while Nightmare could turn off your suit sensors, beheading you will likely be impossible
> * You can still stun Nightmare with a flash or any flavor of baton if you're quicker to the punch
> * If you go into maint while there is an active Nightmare without taking proper precautions, I argue its your fault and the consequences (such as death) are deserved. If a Nightmare gets their hands on you and it isn't your fault, that's just the nature of the game in that you don't always win

as i said previously, nightmare will just jaunt out my ass after i stab them in the balls with a baton, but i didnt know you could just drag a lamp behind you and be space jesus, so this PR is a little more likely, maybe make it a mini crit (haha) if in light, just so theres somewhat a counter so it isnt mega OP?

**Comment by IndieanaJones** [comment]
Even if you're ignorant enough to go in unarmed into maint, you're almost certainly going to have a light, so making it mini-crit people in light would just mean its always going to mini-crit. Considering Nightmare used to be able to use and teleport with stun weaponry with no issues until a change meant for insulated gloves nerfed them, so I don't think it'll be bad. Worst case scenario, Manuel dims down Nightmare's jacked up rate in their config (they have it set to 7, usually its 4 iirc)

**Comment by Admiral-Gigaton** [comment]
> Even if you're ignorant enough to go in unarmed into maint, you're almost certainly going to have a light, so making it mini-crit people in light would just mean its always going to mini-crit. Considering Nightmare used to be able to use and teleport with stun weaponry with no issues until a change meant for insulated gloves nerfed them, so I don't think it'll be bad. Worst case scenario, Manuel dims down Nightmare's jacked up rate in their config (they have it set to 7, usually its 4 iirc). Again, if you don't want Nightmare to kill you, don't go into maints, or at least bring something for some security.

Night vision goggles, nightmare can hit you for minicrit, run, charge crit, and finish you.

or just hit you, run, charge crit, finish job, without waiting 15 seconds to do 10 extra damage in light

**Comment by GuillaumePrata** [comment]
The idea and theme of the PR is fun, but man, adding more stun combat is just sad.

Nightmares being one of the few antags that don't have easy access to click stun was one of the best sides of it, fights would often become a slugfest of players slashing each other when the nightmare ambushes someone that is unprepared, which is just too flavorful.

Now with this, any time the Nightmare scores a stun, the other player will be forced to flee from it because pixel hunting your dropped items to continue the fight is just not a good mechanic.
Ignoring that experienced players will keep their combat gear in their bag to quick pick after the stun... inventory tricks like this are not a good way to reward experienced vs unexperienced players.

If the critical strike always scored a bleeding wound it would be a lot more interesting IMO, interact with more in game mechanics, like mechanical limbs, clotting chems, dismemberment, etc.
While giving more control of the engagement to both sides, it can either use the opening to chase the target, forcing it to fight suffering from bleeding, or try to disengage, letting the target decide if it is worth chasing with a wound.

Slugfests are good, point and click winning a fight is really lame, thanks for coming to my TED talk.

**Comment by IndieanaJones** [comment]
> Slugfests are good, point and click winning a fight is really lame, thanks for coming to my TED talk.

If the nightmare can't stun a solo attacker, the nightmare will just get stunned by them instead. Now, there's a level playing field ideally leaning in Nightmare's favor. While a slugfest is nice in theory, its not what would happen in reality.

**Comment by ExcessiveUseOfCobblestone** [comment]
If you have to manifest first then wait 15 seconds it seems like this wont ever see use except when theres a group and theyre stopping you from jaunting away, If its just one guy either you kill him before the crit or they just run away OR you just sit in the same spot and camp a zone rather than going out and harassing people who are alone in the dark for the sake of the magic stunhit.

The nightmare SHOULD be out scouting and picking off people who are alone, using your ability to find targets (jaunt) nullifying your ability to secure said target doesnt make much sense to me. Heck id argue the jaunt should be the **only** way to progress getting your crit.

**Comment by SomeoneYouProbablyKnow** [comment]
Why would you want jaunt to get you your crits? it's already the thing you're supppsed to be doing. If all your incentives are in one bucket you rob the player of any kind of choice. 

Crits coming from not jaunting is gonna promote more ambushes and not "oi i saw a lone guy time to stab" which is fair but should not the the only thing you do. You can hide in lockers, in front of doors or behind corners with your crit. The fact that it runs counter jaunting around is good.

**Comment by ExcessiveUseOfCobblestone** [comment]
Exactly, because it's part of your activities as a mare. Sitting in a locker or in a corner to buildup your meter for a single gigahit is not practically helpful as the aggressive antag since you cant scout which is arguably your most important tool to pick people off and stay alive. The point of the PR is to make the antag stronger, doing it in only a way that requires "tech" (aka counter to what it SHOULD be doing) is not intuitive. Having you meld into the darkness for your gigahit is thematic and fits with the playstyle mare is shooting for.

The antag works because its straightforward, I dont understand the allure of complicating it by trying to build tradeoffs from NOT utilizing your powers. If you want to hide in a locker with an armblade, play ling. If you want to defend an area and hide behind doors/walls, you can be practically any other antag (like ling, it has an armblade). Blending into the darkness is the defining feature of mare, it makes zero sense why you want to discourage that which is what you do by rewarding the opposite.

**Comment by IndieanaJones** [comment]
I think Cobby's argument makes sense. By not tying gaining crits to the jaunt state, all that does is encourage the Nightmare to stand around as opposed do what's unique to them, and I agree flipping it makes more sense and creates a better and straightforward gameplay flow.  I'll look into changing it tomorrow.

**Comment by GuillaumePrata** [comment]
> If the nightmare can't stun a solo attacker, the nightmare will just get stunned by them instead

There are multiple ways to prevent this without turning the nightmare into another "Who stun first" antag.

We can just go the straightforward way and make them stun immune, every time a nightmare gets tapped by an officer that is dragging a glowstick with their ass cheeks the round loses something interesting and is just a shitty way to end the story.

"I was antagonizing the station and then got tapped by a baton" should not be a common end as it is, especially for 
monsters antags like the nightmare.

**Comment by IndieanaJones** [comment]
PR updated, swapped the requirements around to gain critical hits. Instead of needing to be manifested for 15 seconds, now you gain crits by staying in jaunt for 15 seconds.

**Comment by ExcessiveUseOfCobblestone** [comment]
> > If the nightmare can't stun a solo attacker, the nightmare will just get stunned by them instead
> 
> There are multiple ways to prevent this without turning the nightmare into another "Who stun first" antag.
> 
> We can just go the straightforward way and make them stun immune, every time a nightmare gets tapped by an officer that is dragging a glowstick with their ass cheeks the round loses something interesting and is just a shitty way to end the story.
> 
> "I was antagonizing the station and then got tapped by a baton" should not be a common end as it is, especially for monsters antags like the nightmare.

I think this is a fair philosophy and will probably condone changes lending itself to that later.

That said I like the crit mechanic for btfoing individuals in the dark.

**Pull request merged**
