### PR TITLE
Veil Render Fix

### LINKED ISSUE #12995: Veil Renders are fucking hilarious (but overpowered)
Veil renders make mini Nar-Sies that turn everything into cult tiles and people into harvesters. While this is funny, five of them are not.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Returns classic singularity functions to the wizard nar-sie rather than putting weird walls and making harvesters

Fixes #12995

### CODE REVIEW

**Comment by tkdrg** [comment]
this fixes #12995 right

**Comment by Zilenan91** [comment]
Wait did this literally spawn nar-sie for a time? Holy shit that's hilarious

**Comment by PKPenguin321** [comment]
meme

**Comment by KorPhaeron** [comment]
Someone else changed mini nar sie since I last touched veil render no bully

**Comment by Niknakflak** [comment]
making nar-sie's period is really bad and quite possibly the worst thing to have lel-spawn in a wizard round.

**Comment by KorPhaeron** [comment]
Actually I have a better idea for this I'll do a different PR in a bit

**Comment by Zilenan91** [comment]
@KorPhaeron Are you gonna make it be nar-sie without harvesters?

**Pull request closed without merging**
