### PR TITLE
Un-hardcodes brig timers

### PR DESCRIPTION
**Pull request by Jordie0608**
Cell timers were individually defined with names, ids and pixel shifts as timer 1-6; these are all things that can be accomplished with the base atom being varedited.

### CODE REVIEW

**Comment by pudl** [comment]
why the fuck would you do this without even providing a description

**Comment by Deantwo** [comment]
I think the CondiMaster also have it's name hardcoded in the map.
Can you fix that too or wanna save it for another PR?

**Comment by Jordie0608** [comment]
It should be pretty evident from the diff but alright =P

**Comment by Deantwo** [comment]
Yeah I looked at that after posting.
Still, my other question?

**Comment by Jordie0608** [comment]
Condimasters are a bit of an edge case to be honest, they are hardcoded by the sense of what is being done in this PR, but it's arguably ok in their case.

**Comment by Deantwo** [comment]
I don't know anything about the map, I just know that in the code they are named "CondiMaster 3000".
But the CondiMaster that is located in the kitchen's back room on BoxStation is named "CondiMaster Neo".

**Comment by Stickymayhem** [comment]
Does this mean admins can easily spawn a timer for use in events?

**Comment by Jordie0608** [comment]
You can do that anyway

**Comment by Razharas** [comment]
Merge conflicts

**Pull request closed without merging**
