### PR TITLE
Water wets hide, you can microwave wet leather

### LINKED ISSUE #27539: You cannot wet hairless hide, in order to dry hides on a rack.
Some kind of issue is breaking the production chain of leather, when i tried talking to this to @WJohn , over IRC even with the instructed steps they reported they were unable to complete what they were doing, as the drying rack refused the non-wet hide.

> WJohnston	Fantastic_Fwoosh: yes, i spawned a corgi hide
14:57	used a knife on it
14:57	turns it into a hairless hide
14:57	then i spawned a kitchen sink, and used the hide on that
14:57	it says it washed it
14:57	it was not wet
14:57	tried it again with a water puddle
14:57	same results

This issue is important because it effectively breaks the natural production chain for leather besides getting the stack object solely from the biogenerator.

### PR DESCRIPTION
**Pull request by QualityVan**
:cl: QualityVan
add: Hairless hides now become wet when exposed to water
add: You can microwave wet leather to dry it
/:cl:

Fixes #27539

### CODE REVIEW

**Comment by WJohn** [comment]
So does this allow you to wet the hides using showers, fire extinguishers, and steam?

And can you dry it over a bonfire, since that's related to microwaves apparently?

**Comment by QualityVan** [comment]
Anything that applies water. I know fire extinguishers work, I haven't tested the others. I don't know about bonfires.

**Comment by swindly** [comment]
Perhaps it is time for a water_act proc that is called when water is splashed on things or things are exposed to water vapor or showers.

**Comment by fludd12** [comment]
Note that only bonfires with grills call microwave act.

**Comment by QualityVan** [comment]
Bonfires work if they have a grill on them. Water vapor doesn't work, showers don't work. Looking at showers.

**Pull request merged**
