### PR TITLE
Aiuri, libital, and seiver organ damage buffs.

### PR DESCRIPTION
**Pull request by Higgin**
## About The Pull Request

Increases organ damage from the main cat2 chems: aiuri, libital, and seiver.

Respectively:
Using much more than 30u of aiuri or libital in a stock medical spray without waiting will have consequences. 
Using 30u of aiuri spray results in 18.05 eye damage with natural healing ongoing - nearsightedness kicks in at 20 damage.
Using 15u libital results in 75.1 liver damage with natural healing ongoing - it dies at 100 damage.
Using 15u of 0K seiver results in 58.1 heart damage with natural healing ongoing - it dies at 100 damage.
Using 15u of 1000K seiver results in 71.7 heart damage with natural healing ongoing - it dies at 100 damage.

## Why It's Good For The Game

Irresponsible chem-stacking and being able to run with it practically forever sucks for gameplay. 

One of the ways of balancing for this previously was impurity chems - toxic monomers and chemical isomers would make bad libital even worse to use; aivime, the impurity chem for aiuri, applied a gentle screenblur in proportion to its amount.

...but this resulted in a shitty loop of punishing people for not making 100% pure chems (which you can do by rote.)

The other problem previous to this was that cat2 chems were too potent as weapons. 15u of anything being able to destroy a person quickly and irremediably, even if it's normally good, is a problem when the syringe gun comes out. 

This PR seeks to strike a middle-ground. Nothing in here in testing is quite so potent as old multiver, charcoal, or even syriniver (an underappreciated killer/vomit-causer) - however, the punishment for overusing and uncarefully using the cat2 chems, especially stacking lots of them up over time or in combination with others, is now a lot more real in its ability to bite you in the ass. 

Ask your chemist for some nicer medicine, take your MOD off to patch yourself up the old-fashioned way, or consider taking it a little easier today. 

## Changelog
:cl:
balance: Aiuri, libital, and seiver now cause more organ damage per tick. Sources of these that might risk users taking too much now have warning labels attached. 
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
> Using 15u libital results in 75.1 liver damage with natural healing ongoing - it dies at 100 damage.
> Using 15u of 0K seiver results in 58.1 heart damage with natural healing ongoing - it dies at 100 damage.
> Using 15u of 1000K seiver results in 71.7 heart damage with natural healing ongoing - it dies at 100 damage.

oh sick, it's not like i wanted to do anything challenging or dangerous ever in my life more than once every 15 minutes.

guess i have to put even more emphasis on looking up my instant mix purity document and making two 100u med beakers to last me the entire shift

**Comment by Higgin** [comment]
hey, look - a reason to use the other chems besides "bigger number per tick."

**Comment by starrm4nn** [comment]
doesn't this make libital very potent to for mixing with other shit that kills the liver xd

**Comment by Higgin** [comment]
> doesn't this make libital very potent to for mixing with other shit that kills the liver xd

for killing the liver? yes!

spider toxin, regular toxin, plasma - basically any toxin - any number of things you should now be more cautious about mixing with libital when treating yourself or others.

**Comment by necromanceranne** [comment]
@ExcessiveUseOfCobblestone Remind me, were T2's deliberately meant to not kill at 15u? I feel like there was some attempts to move away from the possibility of weaponizing them.

**Comment by improvedname** [comment]
i think this is a hard nerf to powergameds who buy libital auri from the  chem/wall vendors since this seems oddly targetted towards those this will also cause mediborgs to kill humans quicker then you can saw law 1

**Comment by sylvia-from-fulp-station** [comment]
>Using 15u of 1000K seiver results in 71.7 heart damage
Do you actually think this will be merged?

**Comment by Higgin** [comment]
> > Using 15u of 1000K seiver results in 71.7 heart damage
> 
> Do you actually think this will be merged?

I don't make PRs that I don't - even if they go through healthy refinement first.

Be careful with how you cut your synth patches, and consider that syriniver and pent exist.

**Comment by DaydreamIQ** [comment]
This is gonna unintentionally lead to a lot of borgs accidentally murdering people when they dose up some really hurt guy with 5u too many libtal and cause their liver to explode, even moreso for antag borgs.

**Comment by Higgin** [comment]
if I am being offered a chance to nerf mediborgs here by decreasing their one-time chem storage (perhaps in exchange for faster regen,) make their non-emagged hypos non-silent and require a do_after, or both, call me Chiang because I am ready to be unleashed

**Comment by btcbuster** [comment]
Are you not concerned with how lethal these could be offensively? twenty units to kill someone's heart seems a bit low.

**Comment by Fhaxaris** [comment]
>Using 15u libital results in 75.1 liver damage with natural healing ongoing - it dies at 100 damage.

lmao speedmerge this 11/10

**Comment by Chocodaemon** [comment]
Are powergamers a big enough issue that it's worth pushing this change to make it harder for regular medbay players and mediborgs? Plus wouldn't it be a buff to antagonistic mediborgs if they overdose someone?

**Comment by ZealousZeke** [comment]
In my experience with aiuri, its eye damage is already perfectly annoying.
Seiver and libital definitely could use some kind of organ damage buff when compared to the effects aiuri has.
No clue what the current passive organ heal rate is. This might be excessive.

**Comment by antropod** [comment]
A traitor who is not chemist walks into medbay, he takes a gel for healing just to sustain the fights he's gonna have. He dies from liver damage. Annyoing isn't it?

**Comment by ZealousZeke** [comment]
Could just add an OD that does the extra organ damage and make it a small amount like 6u or something

**Comment by TheRyeGuyWhoWillNowDie** [comment]
fun fact about the organ damage on cat2 chems, they already were stronger in the past and it caused a few things
1: nobody used cat2 chems because total organ failure from a medicine is awful
2: cat2 medicines were just poisons (iirc aiuri would nearly blind you from something stupid like 10u)

**Comment by Striders13** [comment]
this is a huge nerf to all antags, if you're a heretic/tot you HAVE to use the wall sprays because sec is always using lasers. I don't wanna spend 30 mins in chem as antag just so I don't instantly die to lazors

**Comment by Deadgebert** [comment]
This PR just weaponize more of the easy to make chems and heavily nerfs the inexperienced players.

It's really easy to get more than 20 units of chems in someone to cause total organ failure. Foam or smoke will get that quantity in someone's system faster than they can get out of the room. Putting someone on a 200 second timer to go purge enough to not die. There isn't really a great way to purge these 'normally helpful' chems. You can pair seiver with some other beneficial chem and not even multiver will purge it. Most weaponized toxins can be countered in some way like epipen for lexorin or multiver, this cannot.

Other than that, you're just stepping on new players. I don't think you should be trying to make the skill gap larger

**Comment by moocowswag** [comment]
it should clarify to medical borgs that their healing chems are pretty deadly now even when not overdosed.

**Comment by Dawnseer** [comment]
As a mediborg, I would. I'll just make sure to ask before administering. Consent works wonders, considering non consenting surgery is already harm. Just gotta rp instead of silently sting.

**Comment by YuliceTheDruid** [comment]
This would make them insanely deadly, yeah. WAY more ways to weaponize them beyond syringe gun; even then, if a chemist is wily he can get some 50u syringes that fit in a syringe gun for even more fun. Absolutely going to turn "healing" chems into devastating poisons though, and with them not being easily purged outside of pentetic or water/pot, this will be horrendous.

Chem is a mistake in general imo though, so I'm cringe.

**Comment by DaydreamIQ** [comment]
Why use bungotoxin when 30u of seiver does the job better

**Comment by starrm4nn** [comment]
> Why use bungotoxin when 30u of seiver does the job better

seiver, hauntium and bungotoxin foam :face_holding_back_tears:

**Comment by Higgin** [comment]
> In my experience with aiuri, its eye damage is already perfectly annoying. Seiver and libital definitely could use some kind of organ damage buff when compared to the effects aiuri has. No clue what the current passive organ heal rate is. This might be excessive.

It's probably too slow - especially for eyes - and they lack good feedback before nearsightedness kicks in at 20 damage (you don't get less-severe messages about stuff like 'your eyes water and sting a bit' or w/e before that, which is something I'm going to add.)

**Comment by Higgin** [comment]
On the issue of these being used as weapons still: 

If somebody can get enough libital or aiuri into you as a means of killing you or sending you back to med, they can much more easily get chems into you which will much more easily kill you faster in smaller quantities. The medicines they'd be killing you with not only take a long time to have their negative effects - they heal you while you're killing the poisoner in turn. 

If you overload yourself, that's a skill issue and a nudge to diversify your means. That applies to both antags, security, and really anyone here who might otherwise be able to completely ignore med/other healing options in favor of floor libital patches or wall-sprays. 

These are less easy to purge if weaponized - if you have multiples of them. Multiver works to remove single medicines in isolation. Any means of delivery is going to have to cut them up in order to be effective against that counter. 

And again: compared to the other things against which they might be used as weapons, even something like super melatonin (classed as a medicine - not a toxin,) they really don't stand out.

**Comment by Striders13** [comment]
additionally, nukies get libital and auiri in their paid medkits, they will just die if they use to heal during the persistent combat

**Comment by Deadgebert** [comment]
> If somebody can get enough libital or aiuri into you as a means of killing you or sending you back to med, they can much more easily get chems into you which will much more easily kill you faster in smaller quantities. The medicines they'd be killing you with not only take a long time to have their negative effects - they heal you while you're killing the poisoner in turn.

Giving someone enough healing chems to kill them is easier because they're healing chems. You could pass it off as accidental, you could pass it off as trying to help, you get caught by security and you don't have _cyanide_ or _lexorin_ in a beaker/syringe/their corpse. It's harder to spot organ damage than it is to spot the health indicator slowly drop to 0.

The argument of healing you while you fight your attempted murdered is silly. Anyone attempting to kill you with a slow acting poison is probably going to be keeping their distance. Or in the case of seiver/heart failure, their damage is VERY UNLIKELY to be related to toxin damage where passive healing would actually do anything.

> If you overload yourself, that's a skill issue and a nudge to diversify your means. That applies to both antags, security, and really anyone here who might otherwise be able to completely ignore med/other healing options in favor of floor libital patches or wall-sprays.

Why make it a 'skill issue'? Am I really expected to be counting the seconds between application, carrying a health analyzer, or memorizing the 'your heart feels funny' messages in the chat that indicate where my heart damage is at? Antags are usually forced to ignore medbay and don't have many other healing options available to them, they often don't have the option to diversify.

> These are less easy to purge if weaponized - if you have multiples of them. Multiver works to remove single medicines in isolation. Any means of delivery is going to have to cut them up in order to be effective against that counter.

Ah, right, my bad. You can cut it with 4 units of spacecillin from the nearby vendor, sorry, _**24**_ units, not 20. Still more effective at killing someone than nearly every other harmful synthesizable chemical in the game. 

> And again: compared to the other things against which they might be used as weapons, even something like super melatonin (classed as a medicine - not a toxin,) they really don't stand out.

There are definitely far better ways to kill someone. Pure lexorin can kill someone in 8 game ticks, super melatonin puts someone to sleep long enough to kill them with 5 units, double acid piercing darts kills someone in two shots. These are at least suspicious chems and are harder to make than just combining potassium, nitrogen, and aluminum. Just because there exists better options, doesn't really make it reasonable to add more.

**Comment by Rex9001** [comment]
Im not sure about this one, it turns these chems more into weapons over healing chems and this will mainly just impact the people who are clueless, the people who see patch because hurt and apply patch. Not a fan.

**Comment by starrm4nn** [comment]
another issue that pops up from this is a subverted/malf borg doesn't even need to do anything loud to kill people, it can just keep 4 tapping people with libital to kill their livers and blinding them with aiuri

**Comment by FlufflesTheDog** [comment]
Reminder that miners rely to an extent on libital and aiuri healing, via survival pens.

**Comment by Sakamoto4ka** [comment]
ye thats definitely what I wanted to see in the game

**Comment by private-tristan** [comment]
if you use 2 survival medipens as a miner, you'll become nearsighted, if you use a third survival medipen, your liver fails and you have a few minutes to rush to medbay before dying (not to mention that chems stop processing, so you're not actively healing in a situation where you need healing).

**Comment by moocowswag** [comment]
> seiver, hauntium and bungotoxin foam 🥹

Holy shit youre right this is gonna be my nitrous oxide foam gimmick all over again you can easily get enough into everyone to heart kill them.

**Comment by totalglyphiddeath** [comment]
When did this stupid game turn into league of legends that needs to be patched and rebalanced every other week? Calm down, damn. Why does it even matter if people use libital or aiuri to heal their stupid asses? How does it ruin gameplay?

**Comment by Livrah** [comment]
I can weaponize it 👍
btw what nukies should do with the only option of t1 healing patches?

**Comment by Xackii** [comment]
First come up with a reagent that will heal the heart

**Comment by Overuseddart** [comment]
Imagine this, you start a round as an assistant. You get a drink at the bar and get in a fight with another assistant. You get your ass kicked and after the fight is over the assistant gives you some libtal they got from med. You die in maints like 5 minutes later because your liver fails and nobody finds your body.

**Comment by ZealousZeke** [comment]
> First come up with a reagent that will heal the heart

there actually is now with The Inversenning : Superior Healing Medications #79342 PR, which added more inverses. It's an inverse of atropine. Although it isn't easy to make.

**Comment by Higgin** [comment]
I may just have to come back to this by way of changing the balance of their healing instead of their organ damage; improving the other chems; and diversifying the options that don't require you to actually talk to somebody or go out of your way to get meds.

The current state of balance around chem healing - and even within chem healing as between the cat2 chems and others - sucks. 

@Deadgebert the summary answer is that choices should matter, and these chems at present don't really present a choice. Skill and keeping track of your choice to use the very powerful chems should matter because that's part of what makes it rewarding to use them well. I really don't care about the weaponization worries for exactly the reason you mentioned: there are better, and even if it's 'easier to get away with,' you shouldn't necessarily be trusting everyone who runs up on you with a syringe or a spray. Doing so is a choice you shouldn't take for granted and may sometimes pay for - in this case with a very significant delay. 

The workaround with multiver is honestly part of why I think it should be replaced with or supplemented with calomel as the stock public-facing grab-and-go med for purging; but right now, that's a valid concern, as is the lack of feedback and variety of options for some of the roles that rely on chems to be able to go-go-go-go-go as fast as people expect them to right now. 

It's going to upset too much and lead to too many accidental fuckups doing it like this, so I'm going to investigate the other options. Probital, helbital, lent, and even maybe syriniver could use some love, and a more marginal decrease on the effectiveness of these cat2's could probably go down a lot easier.

**Comment by necromanceranne** [comment]
I tried getting his attention about it, but I know cobby has been wanting to keep abreast of a lot of these kinds of changes, so maybe chat with them.

**Comment by ATH1909** [comment]
what if they dealt organ damage based on the amount of damage healed? that would prevent them from being used as a poison (on their own), although it might still screw over miners...

**Pull request closed without merging**
