### PR TITLE
Fixes RCD interaction with lava

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It now builds a floor on it instead of a wall, though its expensive.

### CODE REVIEW

**Comment by GunHog** [comment]
IMO RCD should not work on lava.

**Comment by coiax** [comment]
THIS ISN'T A FIX, IT'S A BUFF! FEATURE FREEEEEEEEEEEEEEZE.

**Comment by Dorsisdwarf** [comment]
Finally, we can do a basebuild event on lavaland which isnt COMPLETE BULLSHIT 
images

**Comment by RemieRichards** [comment]
We really need some kind of ```rcd_act()``` now, with the RCD and the RCD's mode passed as arguments.

**Comment by coiax** [comment]
but RCDs can have multiple modes? Do you mean rcd_destroy_act()

**Comment by RemieRichards** [comment]
@coiax are you blind? 

>"with the RCD and the RCD's mode passed as arguments."

**Comment by coiax** [comment]
but what other forms of interaction are there? 
- space->floor->wall
- x->airlock
- floor->grille->window
-> wall->floor->space

**Comment by RemieRichards** [comment]
* lava->floor->wall (the new one in this PR)

The current setup just isn't nicely extensible, which is why kor adding ANOTHER ```istype()``` is bad.

**Comment by coiax** [comment]
wait, what stops lava->floor->space

**Comment by RemieRichards** [comment]
@coiax I'M stopping it, with the fact that he's adding it in as another shitty ```istype()```, We really need some kind of ```rcd_act()``` <i>now</i>"

**Comment by KorPhaeron** [comment]
How is this a feature.

Building on lava with an rcd builds a wall, which you then have to deconstruct to a floor. This takes out thr extra hacky step.

Remie is right though that the code is not good

**Pull request closed without merging**
