### PR TITLE
Adds an "not_for_loneops" option for uplink items, blocks loneop from buying Overwatch agents and useless equipment

### LINKED ISSUE #84335: Lone Operatives are able to purchase the Overwatch Intelligence Agent support, allowing the lone op to access the Infiltrator and Operative base.
Reporting client version: 515.1640

## Issue Summary

Currently a Lone operative is able to call in an overwatch agent, which has access to a console board to remotely pilot the Syndicate Infiltrator. Normally lone ops have no access to the Infiltrator or the base at all, but by getting their overwatch agent to call in the Infiltrator they can access a wealth of new free equipment in the Infiltrator itself and the operative base that they were never intended to access. Not to mention the powerful infiltrator turrets...

image

## Round ID:
[231102](https://scrubby.melonmesa.com/round/231102)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)
- [Bitrunning: Combat domain](https://www.github.com/tgstation/tgstation/pull/84196)

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

This prevents certain items from being purchased by lone operatives, or from receiving them as discounted items.

- Overwatch Intelligence Agent
- Base Keycards
- Assault Pod targeter

Everything else was untouched with regards to loneop purchasing. I can see a scenario, however unlikely, that a loneop would need to buy, say, a mech repair kit to help an on-station agent with their cause. The stuff I've chosen here either breaks the role's intended gameplay or is straight up completely useless.

This covers the Overwatch Intel Agent, which could send down the shuttle and provide a loneop access to the firebase, and the other items were chosen for being functionally useless. This is so that they don't waste a discount slot or enable a loneop to accidentally waste their limited funds. A loneop doesn't need a discount on a base keycard or assault pod targeter because they should never be on the firebase in the first place.

Loneops may now purchase the station blackout/comms blackout/chameleon noslip items, as they seem like gear that would fit with a loneop having access to them. 
## Why It's Good For The Game

Ensures that discounts offered to a loneop will actually be useful for them rather than just wasting a discount roll. Tightens up the purchases actually relevant to them.

Closes #84335. 12 TC for what I guess is easily 50+ TC worth of gear, in addition to the agent you paid for, is not a fair deal.
## Changelog
:cl: Rhials
fix: Certain items can no longer be purchased or be offered with a discount on a loneop uplink. This is stuff like base cards (functionally useless) or Overwatch Intel Agents (which break the role).
balance: Loneops may now purchase chameleon noslips, station blackout triggers, and station comms failure triggers.
/:cl:

### CODE REVIEW

**Comment by Gaxeer** [comment]
Looks like a crutch. IMO will be better to add new flag like `UPLINK_NUKE_OPS`. But it's my opinion, maintainers will tell what is required ¯\_(ツ)_/¯

**Comment by MrMelbert** [comment]
Shouldn't this be an uplink flag?

**Comment by MrMelbert** [comment]
Oh yeah like the guy above me said. 

You can do it pretty painlessly by doing `#define UPLINK_ALL_SYNDIE_OPS (UPLINK_NUKE_OPS | UPLINKS_LONE_OP)` and doing a find-and-replace of existing `UPLINK_NUKE_OPS` -> `UPLINK_ALL_SYNDIE_OPS`. 

Then manually going into the few items which and changing it to just `UPLINK_NUKE_OPS`

**Comment by Rhials** [comment]
Alright, I've gone and addressed just about every situation this might be able to affect. This touches a lot more files on account of how many of these address clownops in the same breath as regular nukies. I still need to go back and double-check my work, but the short summary I have is:

* There are now 3 new flags, "UPLINK_ALL_SYNDIE_OPS" which includes clown, regular, and lone operatives -- "UPLINK_FIREBASE_OPS" which only addresses operative teams that have access to the firebase (regular/clown) -- "UPLINK_SERIOUS_OPS" which are the teams that are genuine, violent nukies that get their hands on guns instead of cream pies (lone/regular).

* I haven't actually reviewed some of the cases where loneop should be excluded and will get to that later.

* The comms failure/station blackout/chameleon noslips event purchases have been rendered available to loneops, because I feel like they actually benefit from that purchase option in a meaningful way that lines up with how the antag is supposed to play out.

I'm going to take another fresh look at this later, because I know I've probably messed something up in the bitwise math here somewhere. There's a very real chance I've mistakenly blocked off a clownop toy from purchase here by mistake, like in the last two commits I just submitted.

**Comment by Rhials** [comment]
Alright, I think I've gotten everything cleared out, I did a bit of testing and it looks like all of the stuff that should/shouldn't be buyable is/isn't. I'm PRETTY SURE everything is in order now.

**Pull request merged**
