### PR TITLE
The UNREAL sord is now NORMAL

### PR DESCRIPTION
**Pull request by Rowelll**
## About The Pull Request

This pull request FOCUSES on NERFING this unbelievably **STUPID TOOL** which is the UNREAL sord. YOU can't even BELIEVE how angry I AM when I see this ABSOLUTELY disgusting weapon. Everytime I PLAY I can't even PROCESS the level of DISAPPOINTMENT which is WHY i'm doing this PULL request.

## Why It's Good For The Game

Why wouldn't IT? Literally it's THE MOST benefitical FEATURE that could ever EXIST. you SEE, many players DON'T even NOTICE such mistakes AND it goes to the POINT where I can't WITHSTAND such MISERY.

- NOW it's NORMAL
- NOBODY will have problems
- the WORLD is SAVED

## Changelog
:cl: Rowell
balance: unreal SORD is now NORMAL
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
thinking this item is too strong is STUPID. its a fucking chaplain weapon, it desrves to be shis ntrong, theres onykly 1 of it on the STAITON

**Comment by Rowelll** [comment]
you BUFFON, you literally DON'T understand

**Comment by Kylerace** [comment]
As a chaplain main, I can't support the nerfing of my favorite weapon

**Comment by tiramisuapimancer** [comment]
its not poweful enough you need to give it the 413 damage instead  and maybe chaplin will become relevant and  the rp will become more better if you did?

**Comment by interestingusernam3** [comment]
No U fuckin can't do this if this is nrrfrt noone will DUCKIN play shatf miner anymore thsi MUDDERS tendril loot you fukcing GITHUB WORD this MURFERS susgt mimer U kan't do dis

**Comment by duckay** [comment]
IMPproVE not reEMOV!!!!!

**Comment by Rowelll** [comment]
it's a joke pr why isn't it closed already

**Comment by CRITAWAKETS** [comment]
this thing is OP right now... kills in 49 hits instead of 50.

**Pull request closed without merging**
