### PR TITLE
Gives pickaxes proper back sprites.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
kill
me
please

They were just spears before for some reason.

### CODE REVIEW

**Comment by WJohn** [comment]
These are pretty underwhelming and small. Also worn and strapped at a weird angle and spot. Should be more centered around the back, with it being more 45* diagonal rather than what looks to be ~70*. Finally, they should be a tad larger.

**Comment by Bawhoppen** [comment]
needs to be consistent with actual pickaxe sprite

**Comment by TechnoAlchemisto** [comment]
Changed to a better northern sprite.

**Comment by Bawhoppen** [comment]
pictures please

**Comment by TechnoAlchemisto** [comment]
They are already up there.

**Comment by Bawhoppen** [comment]
needs to be shiny like actual pickaxes sprite

**Comment by Bawhoppen** [comment]
or change the normal pickaxe sprite

**Comment by Bawhoppen** [comment]
whicever

**Comment by TechnoAlchemisto** [comment]
I tried to make it match the belt icon, which is not huge, and is also not a huge shiny icon.

**Comment by WJohn** [comment]
Alright, this is better then, good work. :+1:

**Comment by KorPhaeron** [comment]
Sprite man approves

**Pull request merged**
