### PR TITLE
Hostile Animal Projectile Fix

### LINKED ISSUE #12507: Syndicate c20r simple mobs drop nonspent ammo casings
They should drop spent ammo casings because they just fired the bullet.

### LINKED ISSUE #13240: Ranged syndie mobs appear to auto-track projectiles
Is it just me or is their bullets TRACKING you?
On a gateway mission I was moving due to stimulents at the maximum speed possible for humans (pretty sure it was anyways) and I was teleporting when hit from reactive armor
I had 2 of the ranged syndicate mobs tracking me
All of their bullets hit. Even if I teleport 6 tiles perpendicular to the angle they shot it at, they still hit
What is up with that? That seems a bit overpowered as you can't dodge it and the only way to SURVIVE is it somehow close the distance (on the very open gateway map) and make it stop shooting or push something as a shield which doesn't work that well either.

### PR DESCRIPTION
**Pull request by phil235**
Most of this PR is a copy of #13002 by @bear1ake . (with less commits and additional fixes)
- The ammo casings dropped by hostile ranged mobs are now empty as they should. Fixes #12507
- Fixes hostile ranged mobs's projectile auto-tracking the target. Fixes #13240
- Rework OpenFire() and Shoot() procs of simple_animal/hostile a bit to be less shitty.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>Fixes hostile ranged mobs's projectile auto-tracking the target. Fixes #13240

Pretty sure this is intentional, otherwise a ranged mob will never hit a moving target

**Comment by bear1ake** [comment]
:+1:

**Comment by Bawhoppen** [comment]
@KorPhaeron just code them to lead :jack_o_lantern:

**Comment by phil235** [comment]
@KorPhaeron It's a nerf to ranged animals yeah, but I doubt having bullets make a 90 degree turn mid-flight was ever intended.

**Comment by Cheridan** [comment]
If ranged animals are too weak after this we can boost them in ways that doesn't involve teleporting aimbot bullets

**Pull request merged**
