### PR TITLE
(Doesn't) revert goonchem

### PR DESCRIPTION
**Pull request by JJRcop**
## See commit

(also don't merge until just before april fools)

### CODE REVIEW

**Comment by Xhuis** [comment]
having 'april fools' in the changelog ruins it
remove that and we're good

**Comment by ACCount12** [comment]
No actual goonchem revert, 0/10 :-1: 

Better revert goonchem for real, keep it reverted for a week, and then BRING GOONCHEM BACK MUHAHAHAHAHA! That's a better joke.

**Comment by xxalpha** [comment]
How about replacing every chemical with alcohol?

**Comment by Incoming5643** [comment]
I really doubt the changelog will be properly compiled for april fools day.

**Comment by JJRcop** [comment]
@Xhuis But that would be mean! They wouldn't notice it until they highlight it anyway. Should I change it to "not really"?

**Comment by MrPerson** [comment]
Plot twist: PR wasn't accepted in time, point invalid

**Comment by JJRcop** [comment]
Well to be fair I didn't expect all the wacky crazy stuff to be downstream tweaked in, I kinda made this in case there wasn't much for april fools, and since there was, It didn't make much sense having it in if there was the shittening that did make it in.

**Pull request closed without merging**
