### PR TITLE
Tactical Espionage Action

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
You can now pick up potted plants. This will change your appearance to that of a potted plant. It requires both hands to hold said plant.

:cl: Kor
rscadd: You can now pick up potted plants.
/:cl:

### CODE REVIEW

**Comment by lzimann** [comment]
TACTICAL POTTED PLANTS

**Comment by Dorsisdwarf** [comment]
0/10 does not have little feet coming out of the bottom when you move

**Comment by kevinz000** [comment]
time to toss flashbangs at plants

**Comment by Niknakflak** [comment]
Unrealistic

**Comment by optimumtact** [comment]
Yeah I don't think this is a good idea. You should overlay the pot plant sprite on the user instead

**Comment by Shadowlight213** [comment]
Never 4get hiding a gygax behind a potted plant.

**Comment by RandomMarine** [comment]
The plant icon should be overlayed on the holder, shifted up so that their legs are exposed.
Then make attack_hand make them go into proper hiding stance.

**Comment by optimumtact** [comment]
I mean it's okay I guess

**Pull request merged**
