### PR TITLE
Clothing Production Pt 2: there's so much clothing oh my god (WIP)

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
add: A new machine is available in botany for production of various articles of clothing.
add: Cosmetic schematics can be bought from cargo to expand on the machine's choice of attire past generic jumpsuits and general gear.
/:cl:

Autodrobe sprites from WJohnson

Let me just lay out the general idea I'm running with here since this is still WIP:

**General**
The drobelathe starts in botany with the ability to make every type of on-station uniform, backpack, shoes, ect. To get access to things like reinforced uniforms, armor, or the fancier cosmetic stuff you need to purchase design disks from cargo to upload to the machine. Machine gets the same benefits from upgrades as everything else.

**Supplies**
The drobelathe uses cloth, durathread, leather, and a universal dye agent for crafting clothing. The dye will be made by combining every dye reagent (from crayons/rainbow flowers) and plasma as a catalyst. All of this is reasonably obtainable with some effort on Service's half, but there'll also be a cargo crate with supplies (at a premium).

- [x] Drobelathe sprites
- [ ] Dye sprites
- [ ] Recipes for every piece of clothing
- [ ] Material cost for every piece of clothing/balancing said cost
- [ ] Research for producing armor/reinforced uniforms
- [ ] Something to diversify drobe clothing from normal clothing (higher tier parts in machine applies a small moodlet boost for having better made/comfortable clothes?)

### CODE REVIEW

**Comment by Barhandar** [comment]
unnerf the biogenerator clothsheet crafting, black gloves aren't that op

**Comment by MMMiracles** [comment]
One-time purchase for infinite ability to print security-tier armor?

**Comment by Qustinnus** [comment]
or there need to be optional obtainment methods

**Comment by Tlaltecuhtli** [comment]
is that an autolathe copypasted code? tbh make it work in techfabs

**Comment by Tlaltecuhtli** [comment]
if you want to make armor printing balanced here is how much you actually spend for armor from cargo:
- standard armor/helmets 1000 credits -500 creds from crate -200 from supply manifest = 300 credits / 3 armor pieces => 100 credits for 1 armor
 dragging 1 crate from maint to cargo is worth 5 armor/helmets

**Comment by Iamgoofball** [comment]
We'll need to make sure to add a pricetag to these when the lathes are moved over to economy.

**Comment by PKPenguin321** [comment]
>grow your own cloth
>make your own machine to tailor the cloth
>have to pay the machine

???

**Comment by FantasticFwoosh** [comment]
Just make it price biased towards hydroponics (&/or any other relevant access) then

**Comment by ExcessiveUseOfCobblestone** [comment]
Vending machines just need an overhaul so that you can fit stuff inside.

I would do it but >tgui

**Comment by SpaceManiac** [comment]
Marked WIP with no updates for 14+ days, closing as stale, contact any maintainer for reopen.

**Pull request closed without merging**
