### PR TITLE
Boxes hold tiny objects (and makes a lot of items tiny)

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

This PR's main goal is making boxes only hold tiny items instead of small, primarily because they are being used for infinite storage space and a replacement for things like Toolbelts, which is against the whole point of limiting toolbelts in the first place. To counter this change, I made a lot of things that generally makes sense to fit in boxes, fit them. This includes crowbars, gas analyzers, circuit boards, bodybags, spraycans, mail, organs, stock parts, gels, breathe masks and internals, folders, flares, and a few other things.

I don't generally think crowbars should fit in boxes, but I think they're an important tool to fit in them, so I gave them an exception. Also because shaft miners spawn with them.

## Why It's Good For The Game

Mostly explained in the 'about' section. We've put restrictions on toolbelts to limit people's inventories to make them use their surroundings more, but instead it just moved the problem to boxes. This aims to hopefully fix that too, without removing their uses entirely. 
I'd unit test things spawning in boxes to see if they actually fit, but there's some times where they're meant to be exempt (like curator's space suit), but some items that currently spawn in boxes but won't be able to be put back in includes GPS' and Food.

## Changelog

:cl:
balance: Boxes can now only hold tiny items, instead of small.
balance: A lot of items that makes sense to be tiny, is now tiny (examples, not the full list: gas analyzers, circuit boards, bodybags, spraycans, mail, organs, stock parts)
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
ok why were crowbars small.
tiny seems too small for some of these things too, feels like you're straining against the storage system. What is this meant to exclude.

**Comment by skylord-a52** [comment]
...Does this mean you can't fit a small screwdriver into a box, but you can fit an entire human liver? I understand the rationale here from a game design perspective, but it has some very strange consequences from a realism/things-working-as-a-player-would-expect-them aspect. A human set of lungs isn't exactly about the size of a battery, but this PR makes that be the case.

Rather than making a bunch of items tiny and reducing the meaningfulness of that weight class, it would make more sense to me to make certain tools have the NORMAL weight class, like welders, wirecutters, and possibly wrenches.

**Comment by flowercuco** [comment]
the timing of this pr is very funny bc i was just gloating about my characters collection of perfectly labelled boxes. i do think that its silly to be able to sidestep various things via holding enough boxes but currently this would push me away from doing bounties as being able to, for example, have my box with pepper spray or handcuffs for a bounty that i can just turn upside down go away. 

How it affects the storage implant should be considered as well, in that maybe currently its too strong due to letting you put a box in it but maybe you would want to decrease it?

Another concern is that since you've removed a lot food that means that miners need to bring a crate with them if they want to bring a significant amount of meat back with them from the station...

my last personal concern is i think its weird to have roundstart boxes like in offices that have items that you cant put back in when you take it out like in this case the boxes of pdas that i think HoP's start with? theres also obviously a ton of stuff in security that would be like this, and im sure other things that have unique box labels! something would have to be  done so that someone doesnt see that theres a special box for handcuffs and is then confused about that! 

if this is mostly about tools then i do think that changing tools would be better...

**Comment by blackdav123** [comment]
The argument in favor of this is very unclear but seems to be 
1. "infinite storage"
2. invalidates toolbelts
If infinite storage is the issue then I'm sure this should be a bugfix instead of a balance change. As this is clearly not the case, the real argument behind point 1 is just that "people have too much stuff".  Identifying what things people must clearly have too much of and focusing on nerfing those instead of storage as a whole is a much cleaner solution than this sledgehammer approach.
Secondly, boxes never invalidated toolbelts. Whenever I need to use tools quickly, grabbing a toolbelt is my first priority because being able to pull out and put items away via a hotkey is much faster than fumbling around with boxes in my inventory. In the event that my belt slot is full, such as wearing a medical belt or something, I accept the loss of time and slowly use a box of tools instead of a toolbelt.

I dont like the pretending that storage is being "abused" via boxes and I dont like the codifying of stay-in-your lane rules that will be applied to LRP with this change.

**Comment by GuillaumePrata** [comment]
As toolboxes can carry medium sized items since #66900 was merged, pushing more tools to be medium sized could work as an alternative for this PR.
It was my list of things too but imagine not being lazy.

**Comment by JohnFulpWillard** [comment]
> ok why were crowbars small. tiny seems too small for some of these things too, feels like you're straining against the storage system. What is this meant to exclude.

I'll change crowbars back to small, perhaps I'll give miners some foldable crowbar or something for their boxes or just move it to their bag.

> A human set of lungs isn't exactly as small as a battery, but this PR makes that be the case.

I'll move organs back up to normal too, I just scrolled by all medium stuff and changed things I thought be useful but I don't think it's that important for organs.

as for tools, I didn't want to bump them up because then it would bring them back up to the same size as tier 2 tools, unless we'd also make tier 2 tools bulky to not fit in bags. I like the difference because it adds some tradeoff between t1 and t2.

> How it affects the storage implant should be considered as well, in that maybe currently its too strong due to letting you put a box in it but maybe you would want to decrease it?

I think storage implant is fine, it was easily abusable because of boxes, this makes it a little more sane. I think you can implant several to increase the seize of it, so that feature would now be worth more.

> I dont like the pretending that storage is being "abused" via boxes and I dont like the codifying of stay-in-your lane rules that will be applied to LRP with this change.

This is not 'stay in your lane', this is preventing you from being several departments at once. You can swap from a medical belt to a toolbelt any time you want, I just don't think you should have both at once, because you're abusing boxes to be a bagged toolbox.

**Comment by Jackal-boop** [comment]
I really don't like this change. Alot of jobs have trouble managing their inventory already. See engies, atmos techs, miners. This will make it a total pain. Also this is a major antag nerf sense they can't easily stash tools to hack into places now

**Comment by LSommers** [comment]
Horrible PR. Will hurt normal players for inventory management, and will _really_ hurt antags, as stated above. Boxes are already pretty limited, and I can't say I've ever seen any real abuse of them beyond one time where a clown put the nuke disk in a box full of mousetraps in a backpack full of boxes full of mousetraps.

And if you have a problem with that particular example being 'unbalanced', you are not only lame, but mega lame.

**Comment by Shadowflame909** [comment]
I think the theory behind this change is wrong, let along the change at all.

Let me explain, forcing people to stay in their own role by limiting the tools they can have should not be enforced in a game where your role is constantly shifting, changing, and blurring due to the sudden random events and disasters that occur on the station. Everyone carries crowbars because we all know that once literally anything happens and that firelock goes down, you'll be trapped in goodboy jail for an indefinite time that might require admins to take pity on you if you cannot release yourself.

There are times when antags kill a lot of people and your spread more thin, entire departments get bombed so you need to store extra air and extra items. This issue is literally just the effect of how this game is designed, and isn't an issue at all.

To avert the many problems this would cause, (like losing reason to be afraid of lone antags because they can no longer carry all their gear) you would need to litter around tons of storage units containing medikits and toolbelts and food. Like A lot more then we currently have. Or else you're just kind of leaving players stuck with no escape except for DM intervention.

**Comment by JohnFulpWillard** [comment]
> Let me explain, forcing people to stay in their own role by limiting the tools they can have [...]

I'm not forcing people to stay in their own role, I'm limiting abusing inventory space by using 1 sheet of cardboard.

> Everyone carries crowbars because we all know that once literally anything happens and that firelock goes down, you'll be trapped in goodboy jail for an indefinite time that might require admins to take pity on you if you cannot release yourself.

You can still have crowbars in your bag, not sitting in a box. You can also ask the AI to open a firelock, or hit the fire alarm to disable it for a few seconds, or use a maint door if available (which generally is), or just wait because firelocks are meant to prevent people from opening it so bad atmos can spread.

> Edit: I would also like to cite that a good reason a similar PR was closed (Stun batons being bulky) was that maintainers felt it hindered stealth antags too much.

Stealth antags are still able to put tools in their bag, or wear a toolbelt, or hold a toolbox.

> I really don't like this change. Alot of jobs have trouble managing their inventory already. See engies, atmos techs, miners. This will make it a total pain.

How so? Engineers and Atmos techs have toolbelts by default, and regenerative cores/jaunters/mining masks all fit in the box, on top of the crowbar that'll also fit in the box. How is this affecting miners?

**Comment by Mothblocks** [comment]
I don't subscribe to the thought that lots of people having tools is a bad thing, or that hurting that availability would improve the social aspect of the game. Tools are the most diverse ways to act on the mutable world.

Here is a shortlist of common, interesting, and Often Emergent scenarios that I enjoy and would hate to see cast away, and certainly without regard for any department in specific:
- Welding down doors to stop an attacker, or to trap someone in
- Hacking doors to steal something, to attack someone, because you're an antagonist (yes this DOES impact antagonists very heavily), because the room is filling with plasma
- Hacking in general, at the rate, but doors are just the most obviously useful right now. I think more things should have useful hacking
- Welding down walls, for all the same reasons as hacking a door
- Cutting cameras because you think the AI is malf (especially if they're not)
- Healing prosthetic/robotic limbs, or cyborgs
- Using screwdrivers to replace power cells, headset keys, etc etc
- Crafting...in general. A lot of stuff needs tools.

The only thing this PR will do is make scenarios like these less common, which is your express goal, which I very much disagree with.

If you want to make a department like engineering more relevant, the best way to do that is far from making tools more annoying for everyone else. I don't really want engineering's job to be fiddling with tools enough to where that would end up resulting in fun. The best way to do that is by making construction and reconstruction not total ass (the problem is ALWAYS that construction and reconstruction are total ass), and lock the tools for it behind engineering (see: the RAT).

Toolbelts are fundamentally different from tools in boxes in the level of convenience, combined with the fact that many belts can hold things that can't all fit into a box, making the fact that you can only have one more pressing. Quick equip binds are nothing to sneeze at.

**Comment by JohnFulpWillard** [comment]
I understand the need for tools for players but I disagree that it would be not worth a shit to hold onto.

We had made toolbelts bulky for this exact same reason (https://github.com/tgstation/tgstation/pull/66927), and it's been made irrelevant because boxes still hold them, which I disagree with because why would 1 piece of cardboard be the better storage item for tools instead of their respective belts?

Many scenarios you describe would still be able to happen in-game, they would probably not be as common as they are now, but I don't see that as a bad thing either.

Not everyone needs to be able to hack doors on the spot, or escape a plasmafilled room, or cut a camera, or heal a robotic limb. You can prepare in advance to deal with these solutions should they arise, or get tools if it's a problem while it's happening, like normal, but you're sacrificing something in exchange for it, your storage spots. It is fine for you to be in a dangerous situation where you don't have the counter to it sitting on you at all times.

A CMO noticing plasma starting to fill the room and rushing to get the Chemistry toolbox to weld the vents before it's too late is much more interesting than them having one sitting idle in a 0-cost inventory slot

> Toolbelts are fundamentally different from tools in boxes in the level of convenience, combined with the fact that many belts can hold things that can't all fit into a box

Toolbelts can hold t2 tools over Boxes, which isn't that big a problem if you don't have t2 tools in the first place. I also don't see where convenience is coming from, you don't need to hotkey out a welder or circular saw. For Stunbatons and stuff I would agree with, but those don't fit boxes currently anyways.

**Comment by Mothblocks** [comment]
There is a major error in communication here where you are suggesting that I think these would be impossible, but my point is that they would be far far less likely, and I think that is a bad thing. Not "everyone" needs to do those things which is why you still need to go out of your way to do it, but I think dramatically nerfing that does far far far more harm than good

**Comment by SinfulBliss** [comment]
> Toolbelts can hold t2 tools over Boxes, which isn't that big a problem if you don't have t2 tools in the first place. I also don't see where convenience is coming from, you don't need to hotkey out a welder or circular saw.
Since the toolbelt change I've often kept tools in a box. It's significantly less convenient. Hacking takes longer because you need to enter two layers of storage unlike a toolbelt, and a box in your inventory takes up a ton of space.

**Comment by JohnFulpWillard** [comment]
> Since the toolbelt change I've often kept tools in a box. It's significantly less convenient. Hacking takes longer because you need to enter two layers of storage unlike a toolbelt, and a box in your inventory takes up a ton of space.

Except having several toolbelts makes the ones in the bag behave the same way as a box, so there was really no point in nerfing toolbelts at all except for the stunbaton.

**Pull request closed without merging**
