### PR TITLE
ALL HAIL GOD-EMPEROR SINGULOTH

### PR DESCRIPTION
**Pull request by ghost**
singu
# THIS WORLD WILL BURN

Adds a stage six singularity. This singularity is even larger than the stage five singularity, and in order to attain this level of mass must first consume a supermatter shard. Upon consuming a supermatter shard, all mobs in the game world are alerted via a message and sound. This singularity can not only perform the normal things a singularity can but also make all carbon mobs within 25 tiles burst into spontaneous flame. Note: a singularity will _never_ get this big without first consuming a supermatter shard.

Also, I know this code is probably not optimized well. Please give suggestions on how I can reduce feces levels.

:cyclone: :cyclone: :cyclone: :cyclone: :cyclone: :cyclone: :cyclone: :cyclone: :cyclone: :cyclone: :cyclone: :cyclone: :cyclone: 

All credit goes to @SkowronX for both the sprite and the idea.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
H Y P E
Tell me it's also radioactive

**Comment by Xhuis** [comment]
IT'S MORE THAN RADIOACTIVE
### IT'S FIERY

**Comment by WJohn** [comment]
How does this change functionally? The raw power it gets from jumping from stage 4 to stage 5 is gigantic, what'll be the jump from stage 5 to stage 6?

**Comment by Kromgar** [comment]
Massive radiatiion and lights people on fire?

**Comment by Xhuis** [comment]
Huge consumption radius, emits massive bursts of fire that ignite people nearby. In terms of raw destructive potential it's about 1.5x that of stage 5.

**Comment by Kromgar** [comment]
Yeah can you add the option for when two level 6 singuloths collide that it ends reality. Fade to white where everyone is just trapped in a white zlevel with only the server core(for space station 13) which is on fire with them along with an extinguisher

**Comment by Xhuis** [comment]
I was thinking about having two stage 6's colliding just ending the round immediately, in the vein of a nuke going off.

**Comment by Kromgar** [comment]
Have a cutscene where it just shows the space station collapsing in as a supermassive singulo appears

**Comment by RemieRichards** [comment]
>not crediting @SkowronX for his sprite and the concept

for shame.

**Comment by Xhuis** [comment]
I found the sprite on Google images. I'll update the OP for that.

**Comment by RemieRichards** [comment]
@Xhuis it looks like the one Skowron has up is also of higher quality (+ a little white wave animation)
Might want to grab it: http://baystation12.net/forums/viewtopic.php?t=12348

**Comment by SconesC** [comment]
Traitor singularity release plans have an optional additional layer of death. Fun.

**Comment by Xhuis** [comment]
Stage 6 is not possible to contain. It eats the field gens, same as stage 5.

**Comment by SconesC** [comment]
I wish Goof's new upgrade thing let us upgrade field gens to make them perma-anchor

**Comment by SkowronX** [comment]
Mint berry candy

**Comment by palpatine213** [comment]
We really don't need a bigger sing until we fix the current lag issue on the server.

**Comment by JJRcop** [comment]
If you're eaten by it, one of the chapel ambient sounds should play.

**Comment by Dorsisdwarf** [comment]
Sounds like a new and exciting way to cause lag.

**Comment by tedward1337** [comment]
I want this right now

**Comment by PKPenguin321** [comment]
@SconesC Go tell goof in the ideas thread, he's taking requests for more things that should be made into machines

Also, if you were to feed a supermatter to a level 1 singulo, would it immediately jump to level 6?

**Comment by daman997** [comment]
i am fine with this :+1:

**Comment by Lumipharon** [comment]
lag please go.

**Comment by Xhuis** [comment]
Feeding the supermatter to a singularity gives it five times the gain of a normal human. It doesn't immediately stage 6, only grants the ability to make it go stage 6.

**Comment by Stickymayhem** [comment]
So if you fed it a supermatter at level one and then let it go it could grow to level 6?

**Comment by JJRcop** [comment]
@Stickymayhem Yes, it appears so.

**Comment by Fox-McCloud** [comment]
Yeah...I kinda wish there was a way to contain level 5 and beyond, as well; would be nice to be able to push the singulo to insane degrees without it escaping.

**Comment by pudl** [comment]
This is an example of "port it because it's cool" with no actual research into the consequences or what this will mean. The reason that baycode (or is it vgcode?) has a stage 6 singularity is because they use the old version we used to use. In our current code, stage 5 singularity is just as deadly as bay/vg's stage 6. Porting this would only turn the singularity into an even laggier and much worse to deal with death machine that makes any and all rounds totally impossible to recover from.

Thanks, but no thanks. :-1:

**Comment by duncathan** [comment]
@pudl You're saying that as if the chances of the sing reaching stage 6 aren't extremely low. I'll applaud an antag who pulls it off.

**Comment by pudl** [comment]
@duncathan There's an incredibly low chance of a lot of things on SS13, but they happen all the time, because with every single round, and there's got to be at least 20 or 30 a day, there's 3 or 4 traitors and usually at least one will want to release the singularity, and then there's a 13 minute period for the singularity to reach stage 6.
Just saying "This is an awful feature, but it's okay because it probably won't ever happen! lmao!" doesn't cut it.

**Comment by duncathan** [comment]
@pudl My point wasn't what you described in your quotations, though I do see how you could misunderstand that given my fairly vague wording. What I meant was that this stage 6 singularity is only going to be released by an incredibly competent antag who would have had to put a lot of effort into pulling it off safely. I think it's fair, then, that given its difficulty, it can have immense destructive force. Obviously lag will be an issue, but that's an inherent problem with the singulo itself, not with this PR.

**Comment by pudl** [comment]
@duncathan The singularity, under normal circumstances, has been heavily rewritten and calibrated specifically so it would not lag. HG, while rewriting the singularity, likely didn't expect someone to be so stupid or overzealous that they thought a stage 5 singularity, which absolutely will destroy a station with no hope of recovery, wouldn't be enough for one coder. A stage 6 will lag, a stage 5 won't,
Releasing the singularity is effortless, and with that, creating a stage 6 is effortless as well. It's literally a matter of c4-ing into the singularity containment and snipping several wires. That's it. 1 tc and a stolen pair of insulated, along with space gear which I believe is 5 or 6 tc.

**Comment by RemieRichards** [comment]
@pudl 

> A stage 6 will lag, a stage 5 won't.

Objectively false, 5 is laggy as fug, 6 simply adds an extra loop of nearby mobs, it will be marginally laggier than 5, but they are both laggy.

**Comment by freerealestate** [comment]
I just don't think the most powerful killing machine on the station needs buffing. It's already deadly enough.

**Comment by MrPerson** [comment]
That sprite is atrocious

**Comment by Chocobro** [comment]
a few gripes. sure, there's a little bit extra lag. that's normal, it's a singularity. why do we need a stage 6? stage 5 already DEMOLISHES the station. we really don't need another stage that destroys an extra 3 radius. it's already a black hole.
speaking of which, why is it YELLOW? it's a fucking BLACK HOLE. the sprite is horrendously coloured, has unmatching colour contrasts, it's VERY blurry, the edges look embossed for some reason...
all in all, this PR is a bad time. :-1:

**Comment by Firecage** [comment]
I don't really care for this PR myself, considering a Stage 5 singularity already usually ends rounds. Do we really need to make the singularity even more powerful? Besides, the singularity lags a lot at stage 5. Do we really need a stage 6 which will lag even more? Also, the sprite is kinda...well....for such a big sprite it is awfully low quality compared to stage 5.

**Comment by Miauw62** [comment]
This isn't really a buff to the singulo, a loose singulo results in a
shuttle call anyway.
Op 9-jun.-2015 11:03 schreef "freerealestate" <notifications@github.com>:

**Comment by Xhuis** [comment]
@MrPerson The sprite in the .gif is outdated, there's a different sprite currently being used.

**Comment by JJRcop** [comment]
supermatter

**Comment by SconesC** [comment]
It just looks like there is some bad tearing around the edge, not a spiral effect

**Comment by JJRcop** [comment]
@SconesC The ring outside is revolving around the center, which stays still.

**Comment by duncathan** [comment]
@pudl 
> Releasing the singularity is effortless, and with that, creating a stage 6 is effortless as well.
I hadn't realized Supermatter shards were so commonplace to make this effortless.

**Comment by PKPenguin321** [comment]
yo what happened to all the hype
this should hardly lag any more than a stage five considering all it does it increase the size slightly and burns people
the sprite being "awful" is entirely subjective (I think it's great because if I saw it ingame I would shit myself)
the odds of this happening naturally are very low, and to pull it off manually by feeding a singulo a supermatter would be incredibly difficult (mad props to a traitor that can do it)
:+1: to this change from me

**Comment by Psyentific** [comment]
dear god
you crazy motherfucker

**Comment by Loonicus** [comment]
I love how people are actually worried about the lag. If one of these things gets made, lag will be the least of your concerns. If anything the lag accurately represents the singularity starting to pull away at bluespace. 

Besides, as long as its disconnecting people it should be fine.

**Comment by palpatine213** [comment]
@loonicus I seriously hope you're joking, because that is one of the dumbest things I've ever heard.

**Comment by SconesC** [comment]
This looks fine. I don't see how it could be (much) laggier than a current stage 5.

**Comment by Loonicus** [comment]
@palpatine213 "Help! This station ending event is slightly laggier than a normal singularity! Shut it dooooown!" 

Who cares if its a little bit laggier than a normal stage 5, considering:

1. Stage 6 will rarely happen because SM shards are rare and everyone flips out the moment they see the order form on the cargo console.

2. It will hardly lag more than a level 5 singularity will. One extra check will not ruin everything, and even if it does the round is ending anyway. 

3. It easily tops out on the lag/fun ratio

And yes the bluespace part was a joke. I am sorry to inform you that /tg/station is a strictly 18+ server and you obviously have not been around for 18 years if that's one of the dumbest things you've ever heard.

**Comment by GunHog** [comment]
If you are checking for a SM on consume, add a bag of holding please, so that they actually do their job of stopping the singulo.

**Comment by Fox-McCloud** [comment]
Um.....there's already a singularity_act for the bag of holding that decreases how effective the singularity is.

**Comment by GunHog** [comment]
It hardly does anything at all. The singulo is too fast to bring down without several bags thrown in together at once.

**Comment by palpatine213** [comment]
@Loonicus My problem with even more lag, is that it makes adminning a pain in the ass. Having to wait out lag spikes while trying to send PMs is terrible. Current singuloose lag is bad enough. I don't care about fun if it prevents me from doing my job.

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/-tg-station/pull/9882
now stop complaining about lag

**Comment by TheVekter** [comment]
Why hasn't this been merged yet

**Comment by TheVekter** [comment]
Also it needs something a little more panic-inducing than supermatter.ogg

**Comment by pudl** [comment]
this hasn't been merged yet because half of the github thinks its retarded. if you add a feature and say "it doesnt matter if its laggy, we're laggy anyway" then we'll end up playing like goon

**Comment by PKPenguin321** [comment]
i'm going to put this plain and simple
you've been proven wrong
therefore
*you're wrong*

merge please

**Comment by TheVekter** [comment]
New singulo code removes 90% of lag, merge pls

**Comment by pudl** [comment]
i'm going to put this as not so plain and simple
every instance of someone proving me "wrong" was literally exactly what thevekter just posted
basically "lmao! ur wrong! ayy lmao!"
therefore
i haven't been proven wrong, because an argument that consists simply of "im right and you're wrong" is bad

someone close this

**Comment by TheVekter** [comment]
#9982

But hey, pudl being pudl, close everything he hasn't made and turn it into pudl station 13

**Comment by pudl** [comment]
@TheVekter Lag isn't the only issue with this PR.
First off, why? Currently, a stage five singularity completely ends a round with no way to return whatsoever.
Second, what's the point? If the chances of this happening are so ungodly low, and if creating a stage six singularity has no point since it's only marginally more destructive than a force that already destroys everything, why bother?
Third, several people have complained about this being pointless, so clearly there's some sort of disdain for the feature. Merging it just because we can doesn't take into account that a bad feature can be bad, even if it's balanced, non-laggy, etc.
Last, the sprite has also been commented on many times. It's ugly, without a doubt.

**Comment by TheVekter** [comment]
The point is that it's a cool interaction that rewards someone for lengthy
and difficult setup by making the singulo just a bit more murderous. That
and it's really fucking cool.

And yeah, the sprite isn't great, but it's not as awful as you say it is.

**Comment by RemieRichards** [comment]
@pudl Actually all the cases of you being proven wrong were not "ur wrong lmao", I proved you wrong.
I know objectively that it will be minimally more lag than Stage 5.

A Stage 5 lags, A Stage 6 simply adds an extra loop for all mobs in a 20 turf radius, which is similair to the 15x15 view range you already hear in, which is constantly checked for hearing whenever you speak.

The singularity in general needs optimising, This? Won't set back the optimisations at all as any and all made for it will affect Stage 6 also.

On the topic of merging, The majority are either Neutral, Accepting of the change Or Not accepting of the change because of lag (which I've just discredited) there are VERY few who hate it for other reasons (sprite comments which were made with the old artifacted gif, plus art can change easily) or reasons that it shouldn't get a buff (in which it already calls the shuttle so it's a non issue)

**Comment by pudl** [comment]
@RemieRichards

IN FAVOR:

PKPenguin321
RemieRichards
Scones
Tedward1337
daman997
Stickymayhem
Duncathan
Loonicus
TheVekter

NEUTRAL:

WJohn (Leaning against)
Kromgar (Leaning in-favor)
JJRcop (Leaning in-favor)
MrPerson (Leaning against)
Psyentific (True neutral)
GunHog (Leaning in-favor)

AGAINST:

Pudl
Palpatine213
Dorsidwarf
Lumipharon
Freerealestate
Chocobro
Firecage
Miauw

If you were to count neutral support as 0.5, that means 10 people were in favor, and 9.5 people were against it. It's too late now, but this wasn't a feature that was wanted.

**Comment by RemieRichards** [comment]
@pudl are you aware that 10 is more than 9.5?

**Comment by pudl** [comment]
@RemieRichards Even if it's a majority, there was a near equal amount of people against the addition of the feature. Additionally, you discredited people who don't want the feature added because it lags, so could I hypothetically discredit people who want the feature added simply because it's "cool"? I think that's as dumb a reason to like it as lag is a reason to dislike it.

**Comment by RemieRichards** [comment]
@pudl 

I discredited the lag reason as it's false, it's a pointless point, and should not be regarded.

Also:
Dorsisdwarf: Point is based on lag, I already discredited that as false, this should be regarded as neutral or 0 points at all.
Lumi: Point is based on lag, see above
Chocobro: Largely a sprite complaint, Art assets can change easily.
Firecage: Lag and sprite complaint, disregarded for above points
Miauw: More netural, he doesn't say he hates it or likes it, he just says it's not really a "buff"

**Comment by pudl** [comment]
@RemieRichards 

Until they outright post "I've changed my mind, it's okay since it doesn't lag" then I don't think they should be disregarded as they could have other reasons beyond the lag (much like I did.)

And "art assets can be changed" is an argument that Paprika used constantly (such as for his boot resprite) but no one accepted that then, why would I accept that argument now?

Also as a note, I hope this argument doesn't affect out friendship.  ʕ´•ᴥ•`ʔ

**Comment by RemieRichards** [comment]
@pudl Well since i've mechanically stated WHY it shouldn't lag, I feel that's fair enough evidence to justify disregarding their point, if they come back with more points, then of course I'd consider them, but they haven't done so leading me to assume quite fairly, that lag was their only detractor.

While true that doesn't discount how quick we can get art changes, we had the whole sec art change back and forth and if this does need a new sprite, it'll probably only happen once, twice maximum.

Course not, just business rofl.

**Comment by pudl** [comment]
@RemieRichards I just don't view "It doesn't lag" as a good enough reason to justify the addition of a mostly pointless feature, as I and some other users have pointed out. Why would this be added for anything other than rule of cool, when it adds nothing to the game whatsoever, and will likely never be used after the first few weeks, when the awe at it has tided over? There's no significant benefit to going through all the effort to do it, especially when you'll almost definitely die trying.

**Comment by RemieRichards** [comment]
@pudl "it doesn't lag" isn't a reason to add it, it was a counter to the reason "it would lag" which IS a reason against not adding it, I wouldn't have emphasised the point of it not lagging, had lag not already been brought up (unless it brought optimisations with it, it does not however)

Coolness is a factor to consider, but not the sole reason to add something no, I feel this is a rare interaction between two objects both seen in game and in the bits of lore we do have, to be powerful devices for power generation (and murder), so to have them interact with eachother and have no special effect, just the singulo eating the supermatter shard? that's kind of boring, and in SS13, a game full of emergent/hidden/rare things that can happen, I feel it has it's place.

There's not a benefit or a negative to doing a lot of things in SS13, but people still do them.

**Comment by pudl** [comment]
@RemieRichards Lorewise, that's a good point, and that's all I was asking for. A reason to actually have this added.

Although I still don't support the feature, I don't want to argue over it anymore since it's been added, and you gave me what I was asking for.

**Comment by Miauw62** [comment]
)) :boom: :us:

**Comment by Lumipharon** [comment]
>this discussion
I don't know if it's because I'm high, but top kek.

**Comment by Xhuis** [comment]
HE RISES
:cyclone:

**Comment by Psyentific** [comment]
IA! IA! SINGULOTH FHTAGN!

**Pull request merged**
