### PR TITLE
Graphical changes to the Power Monitoring Console

### PR DESCRIPTION
**Pull request by goosefraba19**
I restored vertical alignment (which should've already been fine if BYOND didn't have that bug with \improper) and added color coding for various things in the display.  The colors mimic the coloring scheme for APC displays. 

Here's a screenshot:
image of changes

### CODE REVIEW

**Comment by GunHog** [comment]
This is pretty, but would greatly benefit from auto-updating afforded by the new HTML UI!

**Comment by goosefraba19** [comment]
I'm very new with this codebase, so I don't know about the new auto-updating stuff.

**Comment by phil235** [comment]
It definitely improves the readability of the window.

**Comment by WJohn** [comment]
:+1: x :100: 
A million times better looking, since our current one isn't aligned or anything. Love the colors, too.

**Comment by Aranclanos** [comment]
how was the window previous to the change?

**Comment by clusterfack** [comment]
Hey we use the same UI on /vg/, can we port this to our codebase?

**Comment by goosefraba19** [comment]
Go right ahead, clusterfack.

**Comment by clusterfack** [comment]
Thanks

**Comment by Fox-McCloud** [comment]
@goosefraba19 

Maintainers would have to decide that one; VG isn't AGPLv3, while TG is....so explicit permission would have to be given for this.

**Comment by clusterfack** [comment]
The requirement is explicit permission from the creator himself

**Comment by Fox-McCloud** [comment]
@clusterfack 

I stand corrected!

**Comment by Metacide** [comment]
Nice, this has needed fixing for ages. Color coding's great, too.

:+1:

**Pull request merged**
