### PR TITLE
A New Era of Roleplay and Immersion

### PR DESCRIPTION
**Pull request by Cheridan**
For too long our spacemen have gone unheard. This PR adds audio feedback for human and corgi say messages.

Benefits:
- Maximum immersion. Imagine wandering through maint, and then faintly hearing the chatter of two suspicious individuals in the tunnel ahead. Gasp!
- Easier teamwork and cooperation.
- Makes the station feel more alive.
- I can list Professional Voice Actor on my CV.
- Easier discernment of male and female. No more awkward social situations!

Negatives:
- Literally nothing.

Response has been mixed, so go ahead and vote here to decide what happens with this:
http://strawpoll.me/7265250

### CODE REVIEW

**Comment by Cheridan** [comment]
check my triples

**Comment by lzimann** [comment]
wrong branch ;^)

**Comment by Incoming5643** [comment]
would have been hilarious on the april fools branch, how dare you miss it

**Comment by Durkel** [comment]
Hey buddy I think you got that wrong branch, the april fools club is two prs down.

**Comment by Cheridan** [comment]
excuse me? this is a serious pr

**Comment by CosmicScientist** [comment]
Can we have preferences including for vaguely dwarf-like voices?

**Comment by Cheridan** [comment]
@CosmicScientist Possibly. Do you know any scotsmen?

**Comment by CosmicScientist** [comment]
Not anything convincing, I'm too far south for that.

**Comment by KazeEspada** [comment]
Blah blah ruins disquise memes

**Comment by KazeEspada** [comment]
Also this going to runtime to hell on golems and other gender neutral species.

**Comment by Cheridan** [comment]
disguising is a meme. i'll do some clips for the _non-binaries_

**Comment by PKPenguin321** [comment]
cheridan did you literally just record yourself mumbling "meme" over and over for the sound effects

**Comment by PKPenguin321** [comment]
**LISTEN TO THE SOUNDS HERE BTW:**
- [Male sounds 1-5](http://puu.sh/o2S5N/9041a1c5d1.mp3)
- [Female sounds 1-5](http://puu.sh/o2S6n/b10fa0c62e.mp3)
- [Arf.ogg and Bark.ogg](http://puu.sh/o2S6y/65367c6540.mp3)

**Comment by lzimann** [comment]
we the sims now

**Comment by Cheridan** [comment]
@PKPenguin321 You should consider how your words will effect others before you make baseless accusations like that.

**Comment by CosmicScientist** [comment]
*gasp
The veil has been lifted! I cannot un-hear what I have heard!

**Comment by optimumtact** [comment]
Operator ban this thread

**Comment by Lumipharon** [comment]
The fucking am I hearing.

**Comment by Cheridan** [comment]
Speech clips for Neuter and Plural creatures added.

**Comment by lzimann** [comment]
Can anyone add a nice MP3 like @PKPenguin321 did?

**Comment by JJRcop** [comment]
They sound like they need a little bit of cleaning up. And if you are actually serious about this, maybe a real human shouldn't say it. Get some kind of like "wa waa wa wroaa" that isn't a real voice.

**Comment by Iamgoofball** [comment]
@Cheridan 
i made disguising not a meme tho
i'll make traitor ID cards change your gender with the voice lines

**Comment by Cheridan** [comment]
That works

**Comment by PKPenguin321** [comment]
**THE NEW SOUNDS**
- [Neuter sounds 1-5](http://puu.sh/o30Sj/cd7b620d19.mp3)
-[Plural sounds 1-5](http://puu.sh/o30Ss/5bd5a72ef2.mp3)

**Comment by optimumtact** [comment]
those plural ones are actually disturbing

**Comment by JJRcop** [comment]
I have another idea, two other people also make their own versions of these, then we have male11, male12, male13, male21, male22, male23, etc.

**Comment by Alek2ander** [comment]
>vary = 0

This will sound extraordinarily creepy when several people are talking.
On the other hand, if it's enabled it will sound like an assembly of clowns.

The only winning move is not to play.

**Comment by TrustyGun** [comment]
> golems literally singing the word "meme" with an inflection

Quick merge.

**Comment by Hatfish** [comment]
Please add a preference toggle to disable it.

**Comment by CosmicScientist** [comment]
After the hell of gooncode last night, I'm going to be serious and say no. Silence is golden.

**Comment by Incoming5643** [comment]
To be clear I like this as a meme, not a real thing that someone should actually merge

Some of yall are taking this a little too serious, making me nervous

**Comment by TrustyGun** [comment]
After seeing it in action, I actually somehow like it (Well, at least the male and female sounds. Looking at you, neuter...)

**Comment by GunHog** [comment]
This is why the Test Merge system exists. DO IT CHERI!

**Comment by Saegrimr** [comment]
memememememememememememe meme

**Comment by Shadowlight213** [comment]
@gunhog it's been testmerged for a while on basil. The moment I saw it I knew I had to testmerge it. Sybil was testmerging fasteverything, so I didn't testmerge there.

**Comment by lzimann** [comment]
this is fucking hilarious

**Comment by Shadowlight213** [comment]
Sybil testmerge running now

**Comment by Incoming5643** [comment]
It hurts

**Comment by Incomptinence** [comment]
Aw is bad. I thought people were joking and it was gonna say me me me

**Comment by Core0verload** [comment]
Meme PR tag?

**Comment by Cheridan** [comment]
@Core0verload https://github.com/tgstation/-tg-station/pull/16555#issuecomment-204591015

**Comment by Miauw62** [comment]
having different voices for male and female is bad enough as is for disguising, PLEASE dont add different voice preferences

**Comment by Cheridan** [comment]
If you speak while disguised it gets instantly blown anyway because it shows your name. A final version of this feature would include voice-changer compatibility.

**Comment by Cheridan** [comment]
It seems the majority likes the concept at least, so I'm gonna close this for now and reopen when I've got some improvements to the system.

**Comment by peoplearestrange** [comment]
When this gets remade would it be ok to have a go at the sound samples? Maybe more whispery sounds would be less... annoying. Either that or use sounds of almost English speech but with non-words (but not as shitty as the sims). Also getting a actual women to do the female voices and a man to do the male voices, using actual dog barks/whines, and then modulate the shit out of a voice for silicon's (though the gravely one for golems etc sounds ok).

**Comment by Armhulen** [comment]
please make it so the option is turned off by default and then sneekmerge so I can be the only one who enjoys memememem

**Pull request closed without merging**
