### PR TITLE
AI combat software upgrade gives proper malf abilities

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request
This PR gives combat software upgrades the same abilities that malf AIs have. Right now, the missing ones were:
* Brute forcing message encryption keys
* Taking direct control of turrets
* Emagging borgs via borgo console

## Why It's Good For The Game
It looks like the missing `hack_software = TRUE` is just an oversight. I'd also rather have the combat software update be consistent with malf powers.

## Changelog
:cl: Denton
balance: The AI combat software upgrade now adds missing malf AI abilities, like being able to emag borgs.
/:cl:

### CODE REVIEW

**Comment by Ty-the-Smonk** [comment]
Can’t wait for AI to get paladin law set and combat upgrade and then we just have 6 valid hunting borgs roaming maint

**Comment by CPTANT** [comment]
>Taking direct control of turrets

wait, this is a thing?

**Comment by GunHog** [comment]
Your own turrets, yes. It is really neat.

**Comment by cacogen** [comment]
how long have malf ai's been able to manually control their turrets?

**Comment by GunHog** [comment]
Merged on March 16th. https://github.com/tgstation/tgstation/pull/36154

**Comment by Anonmare** [comment]
@cacogen  A very long time, it's just a niche ability and, to be honest, I think it ought to have been a default ability considering how easy to cheese turret AI is but that's neither here nor there.

**Pull request merged**
