### PR TITLE
Makes methamphetamine blue.

### PR DESCRIPTION
**Pull request by Iamgoofball**
[chemist (2).webm](https://user-images.githubusercontent.com/4081722/206900958-969b9847-4215-456b-b18a-1fe9984f7bdf.webm)

### CODE REVIEW

**Review by Fikou — CHANGES_REQUESTED** [review]
handle this in on_new on meth, and make it only switch color if purity is very high (purity goes from 0 to 1 so like purity >= 0.95 or somethin)

**Comment by Troxonater** [comment]
> handle this in on_new on meth, and make it only switch color if purity is very high

This is the way.

**Comment by ChungusGamer666** [comment]
jedse  we have to cook

**Comment by Autisem** [comment]
meth is not actuely blue, but high purity as a reference would be funny

**Comment by VladinXXV** [comment]
> handle this in on_new on meth, and make it only switch color if purity is very high (purity goes from 0 to 1 so like purity >= 0.95 or somethin)

If anything, make it blue on **low** purity. It'd be more accurate to the reference anyway. The blue meth was made with hotsauce.

**Comment by MrDoomBringer** [comment]
> handle this in on_new on meth, and make it only switch color if purity is very high (purity goes from 0 to 1 so like purity >= 0.95 or somethin)

Should be >=99.1 for the reference

**Comment by bruhman8ghughug** [comment]
tg is saved

**Comment by Fikou** [comment]
goof doesnt want to finish it i think

**Pull request closed without merging**
