### PR TITLE
Revert "Port Custom hotkeys from TGMC"

### PR DESCRIPTION
**Pull request by imsxz**
mod edit: It was tested, your issue doesn't occur for everyone and we're having trouble reproducing it.

claiming no testing was done at all doesn't help anything

### CODE REVIEW

**Comment by imsxz** [comment]
i expect someone to fix the main PR, i just made this for headmins to testmerge while a fix is made

**Comment by optimumtact** [comment]
there's only two issues relating to this

**Comment by optimumtact** [comment]
@IndieanaJones @Yenwodyah etc, if you experienced issues with this can you please explain what you saw, and ideally your byond client version

**Comment by Couls** [comment]
Another known issue is H hotkey for stopping pulling not working

**Comment by optimumtact** [comment]
fixed in #47569

**Comment by imsxz** [comment]
specific issue that i experienced with the PR in question: pressing t, o, or m opened 2 say, ooc, and me boxes respectively

**Comment by Couls** [comment]
need more information, did you try clearing your BYOND cache? are you using a custom skin or macros?

**Comment by optimumtact** [comment]
control freak is on, so nobody should be using custom skins or macros, that would be an unsupported configuration

**Comment by carlarctg** [comment]
> control freak is on, so nobody should be using custom skins or macros, that would be an unsupported configuration

my ahk macros still kind of worked, just really clunkily, so u may wanna look into however cntrl freak works. probably unrelated to this pr though

**Comment by actioninja** [comment]
control freak is unrelated to external macros

**Comment by bobbahbrown** [comment]
throwing out swapping between hotkeys and arrow keys was a mistake because there are no defaults for arrow keys which is a major inconvenience to rebind for any player who actually uses arrow keys

**Comment by kopoba** [comment]
@optimumtact this is my issue https://github.com/tgstation/tgstation/issues/47665

**Comment by optimumtact** [comment]
The defaults are the optimal keyset we want to carry on for the future

**Comment by actioninja** [comment]
not testmerged anywhere anymore, issues are being resolved

**Pull request closed without merging**
