### PR TITLE
fixes paraplegics appearing horizontal when riding animals

### LINKED ISSUE #83342: Paraplegics are horizontal riding raptors (and some other mobs)
## Issue Summary

When you have the Paraplegic quirk, riding some animals makes you somewhere in between being upright and prone. You are able to do some actions you wouldn't be able to do while prone, but not others. This appears to be the case on raptors as well as wolves. You will appear to be horizontal rather than upright.

image

## Reproduction:

As paraplegic, drag yourself onto a tamed raptor. You'll be sideways.

### PR DESCRIPTION
**Pull request by Ben10Omintrix**
## About The Pull Request
paraplegics were becoming horizontal upon riding some animals like wolves, goldgrubs or raptors.

## Why It's Good For The Game
closes #83342

## Changelog
:cl:
fix: fixes paraplegics appearing horizontal when riding animals
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
Link #83342 ples

**Comment by Ben10Omintrix** [comment]
done

**Comment by Loafin34** [comment]
i think it's a cool idea of hanging onto a wolf or horse by your arms

**Comment by Ben10Omintrix** [comment]
> i think it's a cool idea of hanging onto a wolf or horse by your arms

its a cool concept but it looks a bit goofy right now

**Comment by dalmationer** [comment]
good pr!! will this fix also not being able to do some actions, because the game thinks you're lying down?

**Pull request merged**
