### PR TITLE
Prevents colossus from spawning

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Until I have time to make a better prize for it, the black box has gotten out of control on basil

### CODE REVIEW

**Comment by kevinz000** [comment]
you're out of control.

**Comment by PKPenguin321** [comment]
either disable its drops or make this a config option

**Comment by KorPhaeron** [comment]
why would I have a giant pain in the ass boss with no loot that'd just make people sad

**Comment by KorPhaeron** [comment]
@optimumtact

**Comment by PKPenguin321** [comment]
because then it can still come on station and be super cool

**Comment by Archie700** [comment]
more like super lame

**Comment by Kromgar** [comment]
What happened to it on Basil?

**Comment by KorPhaeron** [comment]
It has deathsquad and wizard gear in it.

**Comment by TheColdTurtle** [comment]
the sybil black box has jack shit in it

**Comment by optimumtact** [comment]
nobody on sybil actually has time to fight lavaland mobs because we have bigger problems on station.

**Comment by Repukan** [comment]
No please.


My memes....my effort

**Comment by Iamgoofball** [comment]
why dont you merge the blackboxes between servers

**Pull request merged**
