### PR TITLE
Revert "adds alternate medborg sprites"

### PR DESCRIPTION
**Pull request by Thunder12345**
Reverts tgstation/tgstation#54627

@actioninja do you realise what you have done you madman

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
geez 3 reverts. whats so special about this pr that everyones going nuts over

**Comment by Thunder12345** [comment]
If I tell you the answer you'll regret asking

**Comment by MrDoomBringer** [comment]
i'm sure jared doesn't know

**Comment by Jared-Fogle** [comment]
im a maintainer i need to know about the state of our codebase?

**Comment by MrDoomBringer** [comment]
no

**Comment by LemonInTheDark** [comment]
yes

**Comment by Putnam3145** [comment]
wtf tg does nothing but remove stuff how dare you improve don't remove

**Comment by SweptWasTaken** [comment]
> 
> 
> im a maintainer i need to know about the state of our codebase?

It had voredogs in it. You know the robot dogs that eat people.

**Comment by Jared-Fogle** [comment]
how do you know this? just looks like a dog to me

**Comment by Serxule** [comment]
_unmerge_

**Comment by LemonInTheDark** [comment]
no

**Pull request merged**
