### PR TITLE
that damn CC light

### PR DESCRIPTION
**Pull request by JoshAdamPowell**
## About The Pull Request

There is a FUCKING light in the CC landing area that is not aligned with the rest of them

## Why It's Good For The Game

That light can get fucked

## Changelog

:cl:
fix: CC have got an electrician to sort out the lights in the CC arrival area
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
needs screenshots to show how the shadows lay, this area was really annoying to trim down

**Comment by JoshAdamPowell** [comment]
image

**Comment by JoshAdamPowell** [comment]
image

**Review by LemonInTheDark — APPROVED** [review]
my belothed

**Comment by JoshAdamPowell** [comment]
This bug was pointed out to me by @Darkened-Earth and I damn them to hell for it

**Comment by CCC23** [comment]
not the buggy light :(

**Comment by Darkened-Earth** [comment]
Just imagine if there's more misaligned lights that I'm not telling you about...

**Pull request merged**
