### PR TITLE
Updated miasma canister sprites

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Updated the sprites for the miasma canister

## Why It's Good For The Game

The current sprites for it stand out a little too much - I made them blend in with all the other canisters a little better.

## Changelog
:cl:NewSta:
tweak: updated the miasma canister sprites
/:cl:

### CODE REVIEW

**Comment by mrhugo13** [comment]
n i c e

**Comment by ArcaneMusic** [comment]
Show a sprite?

**Comment by europaisch** [comment]
@ArcaneMusic Check the icon diffs https://github.com/tgstation/tgstation/pull/44539/checks?check_run_id=149088935

**Review by SpaceManiac — APPROVED** [review]

**Comment by ArcaneMusic** [comment]
Looks good to me.

**Pull request merged**
