### PR TITLE
Singularity Hammer gets a sprite after 2 years

### PR DESCRIPTION
**Pull request by ghost**
:heart:

### CODE REVIEW

**Comment by Armhulen** [comment]
image
ya not gettin much more than this

**Comment by Armhulen** [comment]
I wasn't that much against this PR, but OP appears to be retarded. That earns a solid :-1: from me.

**Comment by Durkel** [comment]
I agree.

**Comment by Shadowflame909** [comment]
Does the singulo spin?? If so plus 1

**Comment by ACCount12** [comment]
I wasn't that much against this PR, but OP appears to be retarded. That earns a solid 👎 from me.

**Comment by banthebantz** [comment]
>projecting yourself onto the codebase by making sprites for useless items

s m h

**Comment by WJohn** [comment]
This sprite is really very not impressive. I appreciate there's now an actual unique one for it now, but come on. This lacks proper shading and lighting, detail, and real shape. I'm not expecting an ausops level sprite here like with his sword and hammer, but you could stand to improve this further.

or maybe i'll end up doing it idk, don't count on it

**Comment by Armhulen** [comment]
@Shadowflame909 it spins, and the floating hammer bits float around.

@banthebantz ummmmmm ok?

@WJohn i'll take another look and see what i can do, thanks

**Comment by Armhulen** [comment]
jk lol i have better shit to do than this SURELY

**Pull request closed without merging**
