### PR TITLE
Bags of holding create a tear in reality instead of a normal singulo

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Veil render is dead again and I'd rather not see the sprite go unused. I realize this is completely subjective though so I won't argue this if someone closes it.

This is also technically a nerf to the boh bomb since this singulo doesnt irradiate people or grow any larger.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
I think a sprite for a tear into Bluespace rather than the code tear sprite would work better.
The code sprite fits the wizard render well but :-1: to it being for the bags of holding.

**Comment by Dorsisdwarf** [comment]
:+1: so cool

**Comment by Bawhoppen** [comment]
:-1: That tear in reality should be for wizard memes, not normal gameplay

**Comment by xxalpha** [comment]
The sprite breaks the fourth wall, it doesn't work for this. :-1:

**Comment by daman997** [comment]
give me the memes i need the memes :+1:

**Comment by GunHog** [comment]
:-1: I have seen that singulo in action, it does not look cool, and it is quite immersion breaking. Makes sense for wizards, but not Science.

**Pull request closed without merging**
