### PR TITLE
Fixes a oversight with cummerbund. closes #72357

### LINKED ISSUE #72357: Cummerbund is a gigantic all purpose belt
Yes i'm whistleblowing on storage balance but i've only been back for a few days (which is like 4 high pop rounds) and 3 HOSes had this specific item.
But i guess boxes still exist and item balance is fucked so who cares

### PR DESCRIPTION
**Pull request by jughu**
Turns cummerbund from a full 7 slot belt for any item into a fannypack subtype(which holds 3 items)
Fixes https://github.com/tgstation/tgstation/issues/72357

why is this good for the game?
(That way we dont have powercreeps rushing an all purpose belt 24/7)

:cl: Improvedname
fix: fixes cummerbunds holding 7 items instead of 3(as fannypacks do)
/:cl:

### CODE REVIEW

**Review by san7890 — CHANGES_REQUESTED** [review]
To be courteous to downstreams or other off-repository maps that may have mapped in cummerbunds, please include an UpdatePaths files with your change:

https://github.com/tgstation/tgstation/tree/master/tools/UpdatePaths

Something like:
```txt
/obj/item/storage/belt/cummerbund : /obj/item/storage/belt/fannypack/cummerbund{@OLD}
```
should work.

**Comment by san7890** [comment]
Also, edit your PR Body to say "Fixes #72357" on a line somewhere.

**Comment by jughu** [comment]
like this?

**Comment by san7890** [comment]
yeah looks good to me, thanks

**Pull request merged**
