### PR TITLE
Local Psuedosentient Bird: 'I am growing stronger'

### PR DESCRIPTION
**Pull request by Incoming5643**
Poly is now more impressionable from things he hears in person (in parrot) and will mimic the line 50% of the time (up from 20%)

Poly is now less impressionable from things he hears over the radio (over the parrot) and will mimic the line 5% of the time (down from 20%)

Expands Poly's memory from 20 lines to 500 lines.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
20 to 500 real quick

:+1:

**Comment by ChangelingRain** [comment]
THE BIRD KNOWS

>DEDO O'BTOH

**Comment by Buggy123** [comment]
At this point we should just make Poly a roundstart position.

**Comment by KazeEspada** [comment]
I agree with Buggy, but only if he gets a health buff.

**Comment by Razharas** [comment]
Case the birdtouching, work the datum antags

**Comment by babinsquared** [comment]
Squawk! Viva! Squawk!
Squawk! Gotta lynch the boss! Squawk!

**Pull request merged**
