### PR TITLE
Fixes electric guitars on Linux

### PR DESCRIPTION
**Pull request by SuperSayu**
## About The Pull Request

Linux servers are case-sensitive, and electric guitar files were not properly capitalized.  As a result, electric guitars were not working.  Thanks @Profakos for pointing it out.

## Why It's Good For The Game

Electric.

## Changelog

:cl:
fix: Guitars run on Linux servers again.
/:cl:

### CODE REVIEW

**Comment by Acer202** [comment]
THAT was the problem? What the heck, I didn't think of that. Awesome!

**Comment by SuperSayu** [comment]
I wasn't the one who pointed it out, although I feel like I saw it at some point in the past, frowned at it, and then decided I didn't care.  But I did a hotfix to test it, and it works

**Comment by Mothblocks** [comment]
Renaming files but only case sensitively *always* fucks up pulling and switching branches on Windows. Always always. The system should instead support case sensitive names IMHO, or rename the entire folder.

**Comment by SuperSayu** [comment]
That's fine I will rename the folder

**Comment by Mothblocks** [comment]
That works, while you're at it can it be `electric_guitar`? We're moving away from abbreviating names

**Review by Mothblocks — APPROVED** [review]

**Pull request merged**
