### PR TITLE
MMI ID lock removed

### LINKED ISSUE #11014: Can't emag MMI's
To unlock an MMI, you need to use your ID on it (with robotics access).
This allows you to remove the brain, for whatever purpose.

I would expect the emag would let you do the same thing, but when I deborged a fellow traitor and put his brain into some random chef I kidnapped, I found the emag didn't unlock it.

I had to ask the admins to lend a hand.

This seem unintended, since the emag unlocks everything else that uses an ID check, that I can think of.

### PR DESCRIPTION
**Pull request by Core0verload**
It was pointless anyway. 

Fixes #11014.

### CODE REVIEW

**Comment by Cebasiz** [comment]
man why do they never take my suggestions this fast

favoritism

**Comment by PatchouliKnowledge** [comment]
The ID lock is there so that only the RD and Roboticists could operate MMIs. It's the same reason why the exosuit fabs are ID locked. Saying it's pointless is like saying that having the armory sec access only is pointless.

I'd rather see MMIs emaggable (which makes actual sense) than see this removed.

**Comment by Core0verload** [comment]
Anyone can operate MMI, but only RD and Roboticist can remove a brain from it. That's pointless.

**Comment by Durkel** [comment]
@PatchouliKnowledge  Fabricators haven't been ID locked for over six or so months.

**Comment by xxalpha** [comment]
I hope the next time you're a brain in an MMI an assistant steals you and removes you from the MMI, leaving you unable to speak/call for help.

**Comment by WJohn** [comment]
I actually like this quite a bit. I don't know why you needed a robotics ID to unlock these things and steal a brain, you didn't need one to rip the brain out in the first place.

**Comment by Aranclanos** [comment]
I REMOVED FABRICATORS ID LOCK
COME AT ME

**Comment by Core0verload** [comment]
@Aranclanos, you are a good person and you know it.

**Comment by advomach** [comment]
When the borgs are blown I don't think they'd appreciate having MMI ID locks removed.

Just make them emaggable

**Pull request merged**
