### PR TITLE
Prevents mining mobs killing tendrils

### PR DESCRIPTION
**Pull request by 4dplanner**
:cl: 
fix: goliaths and watchers will no longer smash through tendrils
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
why not just override attack_animal?

**Comment by 4dplanner** [comment]
> why not just override attack_animal for the spawner specifically?

That'd make this specific change smaller, sure, but seems like unnecessary snowflake code

**Comment by 4dplanner** [comment]
> why not just override attack_animal for the spawner specifically?

Honestly, it could be done either way. I just felt this was more easily extensible - for instance, it'd be simpler to let lazarused mobs attack the tendril again if you wanted.

**Comment by 4dplanner** [comment]
> why not just override attack_animal for the spawner specifically?

Second thought : that'd affect all attacks, not just automated ones. Sentient goliaths should be able to smash tentacles.

**Comment by ExcessiveUseOfCobblestone** [comment]
this way adds a proc to every mob to handle a specific object's function.

I think you're trying to reinvent the wheel.

```DM
tendriltype/attack_animal(mob/living/user)
    if(istype(user, lavaland/mob/type) && !user.client)
        return
```

**Pull request closed without merging**
