### PR TITLE
[MDB IGNORE] Wooden Floor Tiles Audit: Adding trim where we need it

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
With this PR, I plan to add trim to the maps (stations) where needed.
The recent tileing left many people skewed with it, but the even more recent sprite update to the wooden floors left most people happy. However, our new wooden floors next to many of our (still) older floors look, really bad. And from a flavor point of view, this'll look better.
Theres also technically two ways to "add trim" to floors, so maybe we can set a firm precedent?

## Why It's Good For The Game
Muh immersion.

<details>
<summary>Some Screenshots</summary>
Delta

image

image

Meta

image

image

</details>
Also making things look better visually is our shared goal, spriters.

## Changelog

:cl: Jolly
qol: Across all station maps that use wooden floors, siding/trim has been added to make the contrast between other tiles not so harsh. This is more evident with older floor sprites.
fix: Some improper turf decals have been rectified as well. This, again, only applies to station maps.
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
I'm not sure if this is sane and I am the least sane mapper we have.

**Comment by Time-Green** [comment]
Do you have some pictures? Not really sure what this does

**Comment by Jolly-66** [comment]
@Time-Green 
Done.

**Comment by Time-Green** [comment]
Oooh, looks neat!

**Comment by Jolly-66** [comment]
I went back to college so my time is a little more finite. I'll return to this if/when I can, or if someone wishes to pick it up for me, that works too.

**Comment by Jolly-66** [comment]
I'll just redo this.

**Pull request closed without merging**
