### PR TITLE
New chems have more reasonable ODs

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

frogenite OD does3  oxyloss a tick and metab rate is sped up by 2 on OD
ferv OD does 3  burn a tick and metab rate is sped up by 2 on OD

## Why It's Good For The Game

incredibly unfair OD, you die very, very quick, and often dont even have time to call out. easily mass produced too so not fun!

## Changelog
:cl:
balance: frogenite and ferveatium have much tamer ODs now, dealing fifth of the former damage, with lesser metab rates
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
currently these chems( and I fuckin timed it) 
each deals 15 damage a tick (one does oxyloss and one does tox)
with the one that deals oxyloss (frogenite) it knocks you unconcious at 8 seconds and kills you at 25
if you do a bluespace syringe with a 30/30 mix of both it still knocks you out but it kills you in 15 seconds from full health.
these chems that are meant for healing are literally the best poisons in the game
also now mediborgs dont even have to be emagged they get this shit roundstart and enough to OD

**Comment by optimumtact** [comment]
im just not even going to accept your PR until you come back with a title that isn't abusive to the original PR maker and maintainer who merged it.

**Comment by Qydra** [comment]
First you guys whined that Chemistry has things that can kill you.  LEXORIN OP, PLS DETELE!!!  I CAN'T HANDLE  BEING HIT BY A CHEM THAT KILLS ME SLOWLY!!

So you decided to fix it by nerfing Lex...and then giving us Frogenite, a chemical that kills THREE TIMES AS FAST AS LEXORIN.

As a chemistry main, I thank you profusely.  Now please go ruin some other job.

**Comment by optimumtact** [comment]
whole new PR wesoda

**Comment by wesoda25** [comment]
@optimumtact better?

**Comment by carshalash** [comment]
> im just not even going to accept your PR until you come back with a title that isn't abusive to the original PR maker

Uhhhhhhhhhh

**Comment by Detective-Google** [comment]
> im just not even going to accept your PR until you come back with a title that isn't abusive to the original PR maker and maintainer who merged it.

might I also add that the maker of the chems in question was literally talking about how they made the original PR to bait cobby 
https://cdn.discordapp.com/attachments/459831208625307649/605946493920346132/unknown.png
and have said they are legimately trying to worsen the TG codebase since they moved to cit.
They dont deserve anything better because I also know they didn't test their fucking shit, they made everyone else test it for them, the chems were even more fucking broken before we pointed this out and they still got merged in the broken ass janky state.

**Comment by optimumtact** [comment]
I don't care

**Comment by wesoda25** [comment]
yo oranges can i please be abusive to the PR maker just a little

**Comment by optimumtact** [comment]
no

**Comment by Detective-Google** [comment]
>PR maker literally trying to fuck up shit and jump ship

oh no but everyone else has to be nice. guys we gotta be nice to the cit people trying to fuck with us no meanie heads allowed

**Comment by wesoda25** [comment]
oh wait you said whole new PR in the sense that you want me to open anew one alr

**Pull request closed without merging**
