### PR TITLE
Do it right first time edition 2. M90GL edition.

### PR DESCRIPTION
**Pull request by LanCartwright**
@steelpoint you didn't remove the bundles.

I can't believe nobody noticed this god damn.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
lmao

**Comment by xxalpha** [comment]
I think nobody cared.

**Comment by PKPenguin321** [comment]
^
whiners on the forums just convinced everybody that they were problematic

**Comment by Steelpoint** [comment]
I only did the change since Kor was going to flat out remove the M90, so I decided to try and smooth out the change.

Not much you can do with a ultimatum above your head.

**Pull request merged**
