### PR TITLE
Moves several clothing-specific flags from /atom to their proper type

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
:cl: Naksu
code: clothing-specific flags are now defined in /obj/item/clothing.clothing_flags
/:cl:

One more step in my plan to get rid of flags_1 and flags_2

### CODE REVIEW

**Comment by ShizCalev** [comment]
Was actually thinking about taking a look at this again earlier.

**Comment by vuonojenmustaturska** [comment]
@Poojawa @Fox-McCloud did you have some flags_1 TG-compatibility things going on in your repos? I remember someone was doing something but I can't remember which repo it was. Anyways, if so this might be of interest to you.

**Comment by vuonojenmustaturska** [comment]
@ShizCalev one problem with this approach is that nothing is stopping pressured mages anymore

**Comment by ShizCalev** [comment]
pressured mages?

**Comment by ShizCalev** [comment]
hahahaha

**Comment by Fox-McCloud** [comment]
@vuonojenmustaturska Definitely not me; I've not touched flags in quite a while.

**Comment by Poojawa** [comment]
I think the only real issue was the mirror bot having a shitfit over it, but other than that, not really.

**Comment by Nabski89** [comment]
I think this is the merge that broke bucket hats.

**Pull request merged**
