### PR TITLE
Places mining scanners above mining satchels in miner lockers. Also minor sprite changes

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
Since you spawn with the ore satchels in your bag, they just got in the way of grabbing your core kit.

This is extremely nitpicky and I am sorry.

Also fixes centering + some color issues on my original bone and sinew sprites.

### CODE REVIEW

**Comment by Ergovisavi** [comment]
>He doesn't carry two satchels

Look at him and _laugh_.

**Comment by TechnoAlchemisto** [comment]
If you don't use an ore box you are a peak shitter and you dont get to talk on my prs Mods please escort this hot head out of here

**Comment by lzimann** [comment]
\>using orebox

**Comment by TechnoAlchemisto** [comment]
eat a DICK

**Comment by Kromgar** [comment]
Orebox holds more than 3 satchels. Your all  shit miners if you dont have a an orebox full of 50 metal, 20 uranium, 20 gold, 20 silver, 75 plasma and 10 diamond

**Pull request merged**
