### PR TITLE
removes the ability to see static for ai detectors and makes their other feature work for the first time in three years

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
ai detectors used to require camera chunks to add two vis_contents to all turfs not seen by cameras just so that ai detectors could see where static is and isnt, which is a wasteful source of maptick for a single traitor item very few people use so i removed it in #59165

then it turned out the static which blocked clicks for the ai also blocked clicks for people using ai detectors and i dont see another way to fix it without adding back the static object that ai detectors used to use, so instead i made the ai detectors actually change their appearance in response to an ai coming closer like they used to before #41108 removed it three years ago and removed the ability to see static with the ai detector entirely

## Why It's Good For The Game
being able to see the static is a detriment now and im not adding the transparent static back. also like i said fixes a long broken feature so the ability to see which tiles arent visible to cameras isnt much better anyways

## Changelog
:cl:
remove: ai detectors no longer see ai static
fix: ai detectors now change appearance when ai's come closer
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I mean, I thought the ability to see where the AI couldn't was insanely useful? It also just put a big red AoE over the AI's camera eye so you could still see it coming anyway.

**Comment by Kylerace** [comment]
> It also just put a big red AoE over the AI's camera eye so you could still see it coming anyway.

Hence why it's not worth the additional vis_contents fucking over maptick

**Comment by YakumoChen** [comment]
yeah but the AI eye detection doesn't tell you if the AI actually gets camera vision, it just tracks the player's viewport

**Comment by YakumoChen** [comment]
also it's helpful to know if the AI still gets camera coverage after disabling a camera

**Comment by maxymax13** [comment]
bruh

**Comment by ATH1909** [comment]
this kinda guts the item, ngl

**Comment by Mothblocks** [comment]
if you guys want to make it work without murdering map tick be my guest

**Pull request merged**
