### PR TITLE
Converted engineering and miner cyborgs can now create Sigils of Transgression

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Converted engineering and miner cyborgs can now create Sigils of Transgression.
/:cl:

### CODE REVIEW

**Comment by ma44** [comment]
ChangelingRain's daily Clockcult buff

**Comment by anconfuzedrock** [comment]
the fuck does the sigil even do

**Comment by ShadowDeath6** [comment]
I thought it was the power rune, why do engiborgs get a meme rune

**Comment by ChangelingRain** [comment]
engiborgs aren't the power borg that's janiborgs
nevertheless, engiborgs and minerborgs were kind of lackluster compared to other converted borgs(peacekeeper and standard come to mind) and this seemed like a good thing to give them as a buff without being ridiculous or giving them something weak like replicant.

**Comment by GunHog** [comment]
Add replicant to the Service borg, they already print money, having a meme borg to go "LOL HERE HAVE MORE SLABS!!!!!!!!!!!!!!!" sounds hilarious.

**Comment by ShadowDeath6** [comment]
give them power runes

**Comment by kevinz000** [comment]
Be aware, if ratvar sets emagged = 1 then pkborg modules will get their hacking overclock functions, as in, they get to have a stunarm and shit, forgot to say.

**Comment by ChangelingRain** [comment]
Ratvar doesn't emag borgs, it just gives them a fancy slab.

**Comment by GunHog** [comment]
An edge case exists with new borgs being slaved to a Ratvar AI. When the AI is converted, all its borgs are converted as well, and also disconnected from it (I personally do not like this, but whatever). However, due to new borgs synced to a Ratvar AI gain the law 0, but not the actual status until the AI converts it. Due to the AI having antagonist status, _it is able to emag borgs before converting them._ This allows them to bypass the loss of emagged modules. 

While I personally would say that borgs converted by a Ratvar AI should remain connected and emaggable by the AI, I am sure you feel differently.

**Comment by ChangelingRain** [comment]
It can't emag them, silly, it converts them.

**Comment by ChangelingRain** [comment]
Letting borgs get BOTH scripture and emagged modules would be... fucking ridiculous, honestly.

**Comment by AdamElTablawy** [comment]
When changelingrain says something about clock cult is overpowered it's gotta be overpowered

but also yes i agree with shadow engiborgs should make power runes not janiborgs

**Comment by ChangelingRain** [comment]
What would you have janiborgs do, then?

**Comment by GunHog** [comment]
Stun runes. Janiborgs are the stuntrap generation bot anyway (the module image is of a man slipping on the floor)

**Pull request merged**
