### PR TITLE
Chemical Dispenser and ChemMaster fixes

### LINKED ISSUE #7083: The portable chem dispenser doesn't have the new chems
They also haven't had their max energy doubled, unlike its bigger brother.
@Iamgoofball

### PR DESCRIPTION
**Pull request by Deantwo**
Fixes part of #7377.

Fixes #7083.

Adds cancel buttons for the Chem/CondiMaster.

### CODE REVIEW

**Comment by Deantwo** [comment]
Working on a few fixes to the ChemMaster.
Closed until done.

**Comment by Deantwo** [comment]
Always been annoyed that you couldn't cancel making a bottle, pill, etc. from a ChemMaster. Now you can!
I still consider this a fix, but I guess it is up to the maintainer.

**Comment by Kromgar** [comment]
Can you fix the portable chem to have the chems needed for all the new basic recipes? Like phenol and oil and shit? Goofball never updated it

**Comment by Deantwo** [comment]
Never used or seen a "portable chem", but sure.

**Comment by Dorsisdwarf** [comment]
Porta-chem dispenser. It's right below the normal chem dispenser in the code, I remember.

**Comment by Kromgar** [comment]
Portable chem is supposed to be a shittier version of chemistries chem masters in the fact that it takes longer to reload and it can't store as much chems but now its  literally worse you can't even do basic recipes due to lack of the new chems added for goon chem

**Comment by Deantwo** [comment]
There, I added the GoonChems to the Portable Chem Dispenser.
But I just tossed them in randomly in the three levels.

If someone wanna sit down and figure out all the possible reactions that can be made at each level and find it to be bad then change it.

**Comment by Miauw62** [comment]
Just FYI, you're not supposed to make a changelog for bugfixes, only for features/tweaks.
Doesn't matter for once, though.

**Comment by Deantwo** [comment]
Ah sorry.

**Pull request merged**
