### PR TITLE
Adds a new severe trauma, Trauma Savant

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Adds a new severe trauma, Trauma Savant! Kronkaine tier sped up action speed, but the recipient is unable to talk or gesticulate. As a byproduct, they also seem to be pretty decent at imitating mimes in ways both natural and not.

Removes an unused trait

## Why It's Good For The Game

> Adds a new severe trauma, Trauma Savant! Kronkaine tier sped up action speed, but the recipient is unable to talk or gesticulate. As a byproduct, they also seem to be pretty decent at imitating mimes in ways both natural and not.

I think this would be a fun little thing to have appear in game. You'd be this super competent worker that can do things nigh instantly, BUT you can't really communicate with others in most ways. Muteness is already a severe trait, this is just taking it to a higher level. If there's worry about them being unable to express their illness to doctors... just PDA. Or write on paper. Or hand them a health analyzer and point at yourself.

It'd be nice if this could be a roundstart trait somehow but it would need some heavy tuning to not make it a troll trait, so that's not on the table here.

Untested, its 3 am gimme a break

## Changelog

:cl:
add: Adds a new severe trauma, Trauma Savant! Kronkaine tier sped up action speed, but the recipient is unable to talk or gesticulate. As a byproduct, they also seem to be pretty decent at imitating mimes in ways both natural and not.
code: Removes an unused trait
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
aww yeah we're back at instant windows!!

**Comment by MrMelbert** [comment]
this quirk has no downsides to the average greytider

**Comment by VladinXXV** [comment]
> this trauma has no downsides to the average greytider

yes it does. how are they gonna say slurs? they can't even "/me kill yourself shitsec"!

**Comment by XDTM** [comment]
Should be a special trauma, since their whole deal is giving benefits with downsides

**Comment by moocowswag** [comment]
i can already think of like 4 ways I can abuse this for combat.

**Comment by Pickle-Coding** [comment]
This should definitely not be a severe brain trauma. Maybe it could be a special brain trauma. The trauma itself just sucks though, regardless of category. If you want to be a savant, just RP as one.

**Comment by carlarctg** [comment]
It'd be nice if there was some way to make action speed modifiers not apply for any combat-relevant do_after tasks, but I don't think that's the case.

If there's consensus that this is too much of a benefit, I can also make it make you unable to understand other players' words at all, like in Rimworld where it sets hearing to 0. 

My argument for not making it a special Trauma is that special traumas are horribly rare and mostly 'magical' whereas this is something verisimilitudey and would be interesting to have happen to you on an uncommon basis rather than once in a lifetime.

**Comment by Arturlang** [comment]
Then, why not make it a special trauma, but then open a PR that increases the chance of special traumas? I feel like they're too rare too

**Comment by carlarctg** [comment]
Uh, okay? If someone is repeatedly bashing their head in to get a funny then of course they can get them. I meant in normal gameplay.

**Comment by jughu** [comment]
nuerowhine is a way to get special traumas easily without drawbacks

**Comment by moocowswag** [comment]
Its not just that.

Alot of powerful and “not fun to play against” things are often locked behind/balanced by a do_after

the reason special traumas are remotely fair is because almost none of them can be used offensively (except for the rng punch one but its literally bathsalts but worse)

a faster do-after means faster

cable cuffing, welding someone in a locker, table climbing, laser musket cranking, amputation sheering, injecting, forcefeeding, stripping, patching, borg tipping, narsie rune drawing, and fortniting

**Comment by jughu** [comment]
anti magic can be used pretty offensively tbh

**Comment by carlarctg** [comment]
> nuerowhine is a way to get special traumas easily without drawbacks

> normal gameplay.

I don't know what you don't understand, if I mean 'normal gameplay' I mean 'gameplay that is not someone farming and powergaming the most autistic aspects of fermichem for 10 minutes like a gacha game'. I mean 'become a trauma savant after the tider caved your head in with a toolbox'

> Its not just that.
> 
> Alot of powerful and “not fun to play against” things are often locked behind/balanced by a do_after
> 
> the reason special traumas are remotely fair is because almost none of them can be used offensively (except for the rng punch one but its literally bathsalts but worse)
> 
> a faster do-after means faster
> 
> cable cuffing, welding someone in a locker, table climbing, laser musket cranking, amputation sheering, injecting, forcefeeding, stripping, patching, borg tipping, narsie rune drawing, and fortniting
> 
> Rather than halving action speed it should be 0.75 x or 0.8x that little boost is massive trust me

Yeah, you're right. I *really* wish there was a way to specify non-combat actions. (Fortniting is extremely funny and I find the concept of a savant being able to combat fortnite amusing so I'd allow that, but the rest is not what I intended in this PR, ever, believe it or not)

The speedup is set to 0.8x, and I made them unable to understand any languages except the brain damage one.

**Comment by jughu** [comment]
but the whole point we added a delay on the stuff for 1/2 seconds on windows etc was litteraly prevent this from happening

does it stack with other action speed decreases like tinkerer gloves?

**Comment by HoodMilk** [comment]
If people using it for combat is a big concern, you could just have the trauma also pacify people who have it. Would stop the tiders trying to get it every round for sure.

**Comment by Jacquerel** [comment]
I'll be honest, I am just not sure I think this concept is very interesting as a thing to suddenly happen to you.

**Comment by YehnBeep** [comment]
I don't think it's great to have a thing that, if it happens, just shuts off your ability to RP or even not RP so much as just... interact meaningfully. If it's just voice, you can at least go mime-mode and it can be something to work around, but flipping off that too... doesn't seem good to me.

**Comment by carlarctg** [comment]
There are other ways to psuedo-communicate, but given that people dislike this concept from basically every level, I'll just close the PR.

**Pull request closed without merging**
