### PR TITLE
Lathe tax checks for access instead of account department

### LINKED ISSUE #66601: agent ids can't get lathe tax exemptions
image
image

### LINKED ISSUE #67009: Getting your job changed still charges you Arconomy protolathe taxes.
## Round ID: 
[183164](https://scrubby.melonmesa.com/round/183164)

## Testmerges:
https://github.com/tgstation/tgstation/pull/65589
https://github.com/tgstation/tgstation/pull/65997
https://github.com/tgstation/tgstation/pull/66657

## Reproduction:

Be assistant.
Go to HoP line, get a job change to medical doctor. Trim changed and access changed.
Go to make surgery tools in medical protolathe. Get taxed 10 credits.
:agony:

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

(also applies to imprinters, techfabs, and the such)

Access requirements for lathes:
Science - R&D Lab
Cargo - Cargo
Security - Security
Engineering - Engineering
Medical - Medical

fixes #67009
fixes #66601

## Why It's Good For The Game

being the captain with my all access and getting taxed by the engi protolathe is silly
also helpful if youre like an assistant-made-scientist by HoP and need to use your protolathe

## Changelog
:cl:
qol: you will not get lathe taxed if your ID has the correct access
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
fixes #67009 ?

**Comment by Jackal-boop** [comment]
Finally

**Comment by Pickle-Coding** [comment]
Paramedic powercreep.

**Comment by YehnBeep** [comment]
I wonder if this could be applied to vending machines too, so you're not paying 50 credits for a departmental headset, another 50 for a jumpsuit, etc etc if you get promoted to a new department? Or 25 per seed packet if you become a botanist midround which adds up fast.

**Comment by JohnFulpWillard** [comment]
The proper fix would be to make job transfers properly update your lathe tax and vending discounts as it was intended to

**Comment by Sealed101** [comment]
which means letting ID consoles select a department for the card and for agent IDs to steal one maybe

or some other way other than the department

**Comment by mc-oofert** [comment]
> The proper fix would be to make job transfers properly update your lathe tax and vending discounts as it was intended to

this wouldnt work with anyone with a lot of access

**Comment by JohnFulpWillard** [comment]
> this wouldnt work with anyone with a lot of access

Idk what this is meant to accomplish.

Captain being excluded from lathe tax can be done separately to fixing the actual issue that updating your ID doesn't update your discounts.
Lathe tax is meant to discourage you from using other lathes (such as paramedic who has access to them all, departmental officers, etc) regardless of access.

**Comment by mc-oofert** [comment]
>Lathe tax is meant to discourage you from using other lathes (such as paramedic who has access to them all, departmental officers, etc) regardless of access.

lathe tax was meant to discourage tiders

**Comment by mc-oofert** [comment]
> What if lathe tax was applied based on the department of the trim of the card whose account is being accessed.

still doesnt solve captains ID

**Comment by ArcaneMusic** [comment]
> The proper fix would be to make job transfers properly update your lathe tax and vending discounts as it was intended to

Fulp is correct here. Access does not mean you report to that department. In the same vein, everyone reports to captain, so that tracks if you wanted them to have a unique flag, but making it access dependant ain't it, dog.

**Comment by mc-oofert** [comment]
your solutions are shit

**Pull request closed without merging**
