### PR TITLE
Tramstation Dorm Rework

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request
Revamps the entire recreation/dorms area to have better flow and put the civilians job more up front. 
## Why It's Good For The Game
Jobs like the chaplain and librarian being on the bottom floor inherently means they've been pushed into a location you have little reason to go down to, while the less useful dorm area was placed front-and-center as one of the first things you see when coming out of arrivals.

This fixes that by swapping their places on the map. 
## Changelog

:cl: MMMiracles
expansion: The tramstation dorms area has been completely revamped to more freely flow and encourage interactions between the library and chapel.
fix: The chapel now has a mass driver for proper burial disposal.
fix: The overhang in the dorm area no longer shows the walls below on the edges.
/:cl:

**Upper Floor**
- The Library and Chapel are now located on the upper floor with a complete revamp of layout.
- Private adult section in the Library with more art/statue spawn locations.
- The chapel is now a more proper house of god with an added mass-driver for proper burials.
- Central Laundry room with costume spawners.

**Lower Floor**

- The lower floor now houses the general recreational area and dorm rooms.
- 18 total dorm rooms, 6 of them being deluxe suites with additional room and a double bed.
- Entertainment room on the right side with laser tag equipment, arcade machines, and a DiY cheap arcade birthday party.
- Dedicated fitness section with custom encouragement signs.
- Large communal restroom with shower rooms.
- The Medical wing now has plumbing for the associated sinks/showers.

fuc
fukme

### CODE REVIEW

**Comment by MMMiracles** [comment]
image

**Comment by unit0016** [comment]
hate to be that guy, but gas is going to just go over the firelocks here
image

**Comment by MMMiracles** [comment]
if you look at the rails closer, you'll see my immensely large brain already accounted for that

**Comment by unit0016** [comment]
> if you look at the rails closer, you'll see my immensely large brain already accounted for that

the gas is just going to fall back down though, bypassing the lower firelocks entirely

**Comment by moocowswag** [comment]
Something about tramstation tells me that the map is supposed to have hazards like this and its actually funny and fitting.

**Comment by Time-Green** [comment]
Really cool! 
Could you maybe also add a recharging station in place of one of the toilets?

**Review by Twaticus — APPROVED** [review]

**Comment by Farquaar** [comment]
I like the new library. It's more space-efficient than the old one.

**Comment by datorangebottle** [comment]
I like the new chapel a lot.

**Comment by MMMiracles** [comment]
Notes of difference from the above image:

- The firelocks below now align with the above glass floor to prevent gas leakage
- The APC in the library's explicit room is on the wall now
- The bottom-right stall in the bathroom is now a recharger unit.

**Review by Maurukas — CHANGES_REQUESTED** [review]
Couple things I found:

<details>
<summary> There's something wrong with your stairs. This needs to be fixed before merging </summary>
Not sure what, but you fall down them and then can't climb back up:

image
image
</details>


<details>
<summary>Recreation area is missing an APC</summary>

image
</details>

**Comment by MMMiracles** [comment]
i forgot the actual stair object that transitions you between floors lol

**Pull request merged**
