### PR TITLE
Improvements to simple animal make_baby and Runtime

### PR DESCRIPTION
**Pull request by optimumtact**
Runtime now only stores the children she actually made, instead of
being the mother of every cat in the mob list like some kind of god cat

make_baby no longer spawns off for 400 seconds to set a flag

### CODE REVIEW

**Comment by optimumtact** [comment]
I need to clean up the alone var so this is in progress

**Comment by Incoming5643** [comment]
Runtime is female

**Comment by X-TheDark** [comment]
Holy Godmother of all cats...one might say...a true `GCAT`

**Comment by optimumtact** [comment]
fixed the bug also the gender!

**Pull request merged**
