### PR TITLE
tesla coil zapping no longer blows up everything

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: tesla coil zapping no longer blows up everything and itself
/:cl:

the tesla_zap() didnt have any flags specified so it was using default settings aka tesla's zaps

### CODE REVIEW

**Comment by Gousaid67** [comment]
so will it stop anything that gets hit from blowing up barring computers and machines? or does it stop booms completly.

**Comment by Tlaltecuhtli** [comment]
it stops the coil's zaps from blowing up every apc/camera/machine/computer it ll act like the tesla revolver's zap + the snowflaked damage from coil code

**Comment by dr-bee** [comment]
Hopefully this will make tesla coils not instantly blow up janitors that happen to walk by.

**Comment by wesoda25** [comment]
I think its funny and should be kept.

**Comment by XDTM** [comment]
Good change, now it can actually be used as a defense system without blowing up everything

**Comment by 81Denton** [comment]
Good change, now they actually zap players instead of making the nearest light switch or airlock explode like a bomb.
I'll test this later today probably

**Review by 81Denton — DISMISSED** [review]
Looks good to me

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
