### PR TITLE
fixes magic extinguisher cabinets

### PR DESCRIPTION
**Pull request by PKPenguin321**
spirits begone

Fixes https://github.com/tgstation/-tg-station/issues/16710

### CODE REVIEW

**Comment by PKPenguin321** [comment]
fuck wait i copypasta'd

**Comment by bgobandit** [comment]
sweet I don't have to do work :+1:

**Comment by AdamElTablawy** [comment]
noooo

this was a harmless fun thing wryyyyy

**Comment by Supermichael777** [comment]
this is why we have the [s] tag

**Pull request merged**
