### PR TITLE
Tweak CIMS to ignore Syndicate Owned crystal.

### LINKED ISSUE #64527: Syndicate Lavaland listening post SM Shard showing up on Station's Engineering NT CIMS
Reporting client version: 514.1575

## Round ID:
[177469](https://scrubby.melonmesa.com/round/177469)

## Testmerges:
- [Subsystems now track their avg and last tick allocations](https://www.github.com/tgstation/tgstation/pull/64448)

## Reproduction:

The Supermatter Shard in the Lavaland Syndicate Listening post is detectable on the space stations NT CIMS. Given that the any Supermatter shards on lavaland also show up it may be less of a bug and possibly just working as intended or an oversight, however, it is labeled plainly on the NT CIMS as "Syndicate Lavaland Experimentation Lab" which may present issues for the ghost roles in the listening post.

### PR DESCRIPTION
**Pull request by Maurukas**
## About The Pull Request

One of the modular chunks the Syndicate comms base contains a stolen SM shard to experiment with. When reviewing this I saw the var edits preventing the crystal from talking on the station radio and believed that visibility of the shard from the station was taken care of. I did not check NT CIMS.

Unfortunately it's visible in NT CIMS. I should have caught this.

Closes #64527

Instead of removing the map I have tweaked CIMS to check who owns the crystal. I have added a var on the base SM crystal based on Mothblock's feedback for this purpose. 

## Why It's Good For The Game

Giving the station roundstart knowledge of a ghost role spawning ruin is not acceptable. Particularly since it's a stealthy ghost role.

## Changelog

:cl:
fix: NT CIMS no longer detects Supermatter crystals and shards that are not owned by Nanotrasen
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
Just make the NT CIMS check for SM's only on z-levels with the STATION_ZLEVEL_TRAIT.  See #63146 for an example of how to do this.

**Comment by Donpedrito** [comment]
Fixes #64527

**Comment by Maurukas** [comment]
> Just make the NT CIMS check for SM's only on z-levels with the STATION_ZLEVEL_TRAIT. See #63146 for an example of how to do this.

I will not do it like this as that will break NT CIMS from working with any crew built engine either on lavaland or off-station Zs. If you want to refactor NT CIMS to specifically ignore syndicate owned crystals and no other crystals, that is an acceptable solution.

**Comment by timothymtorres** [comment]
> > Just make the NT CIMS check for SM's only on z-levels with the STATION_ZLEVEL_TRAIT. See #63146 for an example of how to do this.
> 
> I will not do it like this as that will break NT CIMS from working with any crew built engine either on lavaland or off-station Zs. If you want to refactor NT CIMS to specifically ignore syndicate owned crystals and no other crystals, that is an acceptable solution.

You can also make it so that NT CIMS checks if it's on the station and if it is, look for SMs on the station.  If it's off station, then it just checks the z-level it's on.  Removing the ruin is a bad solution.

**Comment by Mothblocks** [comment]
> If you want to refactor NT CIMS to specifically ignore syndicate owned crystals and no other crystals, that is an acceptable solution.

Sure, that's super easy. I'll get to it today.

**Comment by Maurukas** [comment]
Updated with a new branch. This now just checks for Syndicate ownership in CIMS via radio key.

**Review by Mothblocks — APPROVED** [review]

**Comment by Addust** [comment]
Complaint: Sometimes, syndie lavaland gets CIMS computers in order to monitor the exact status of the Syndicate Supermatter Shard. Thus, you should make it so that only emagged consoles can access the syndie lavaland shard.

**Pull request merged**
