### PR TITLE
Improves Skeleton Hitboxes

### PR DESCRIPTION
**Pull request by WJohn**
Skeletons and plasmamen had incredibly bad hitboxes, with super thin arms and legs and full of holes in their ribcages. A naked skeleton would be extremely frustrating to hit, especially if they were facing left or right.

But no more!

The grey there mimics a regular human's hitbox, yet has an alpha of 1/255, making it pretty much completely invisible. I also took the liberty of having it follow dismemberment rules, so of course cutting off their leg will still result in the (enlarged) hitbox effectively shrinking.

This change affects both skeletons AND plasmamen.

:cl: WJohnston
tweak: Skeletons and plasmamen's hitboxes now more closely match that of humans. They are no longer full of holes and incredibly frustrating to hit, should they run around naked.
/:cl:

### CODE REVIEW

**Comment by dannno** [comment]
smort

**Comment by Militaires** [comment]
nooooooooo!!!

this is actually supposed to be emergent gameplay, while you swing your sword at the skeleton it's only sense that your blade/tool keeps going in between of its ribs instead of at it! it's so BONEY reeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by ShadowDeath6** [comment]
>swing massive claymore at skeleton
passes through him
shoot bullets at skeleton
will always hit if it goes within 1 foot of him no matter what

if you want to have realism you gotta remove double standards tbh

**Comment by optimumtact** [comment]
freeze

**Comment by WJohn** [comment]
Freeze is over now.

**Pull request merged**
