### PR TITLE
PRAISE THE POPE

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: optional name here
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
fix: fixed a few things
wip: added a few works in progress
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
experiment: added an experimental thingy
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
meme pr

**Comment by HankMoodyExperience** [comment]
meme

**Comment by factoryman942** [comment]
praise he

**Comment by optimumtact** [comment]
If you do this again you'll get a github ban

**Comment by Tacolizard** [comment]
@optimumtact wew

**Comment by Cyberboss** [comment]
Isn't this branch a meme at this point?

**Pull request closed without merging**
