### PR TITLE
[S] Virtual Business Trips Are Cancelled

### PR DESCRIPTION
**Pull request by SouDescolado**
## About The Pull Request

I tried to check if someone is in virtual reality but everything got confusing, so I added a helper.

## Why It's Good For The Game

You can be a billionaire in VR if this works

## Changelog
:cl:
add: isvirtual() to check if the user is in VR
fix: if you get rich in the game you get rich in the game
/:cl:

To be honest I didn't even test this (as I don't with any PR I ever made) and it is webpr. I just want to see if travis fails.

### CODE REVIEW

**Comment by SouDescolado** [comment]
Just because it passed checks doesn't mean it works.
Please advise.

If somehow this works, there is no need for #42763. I didn't see any other way to get an ID with an account number in VR other than the place I changed, but that doesn't mean they don't exist.

**Comment by 4dplanner** [comment]
test it you bitch

**Comment by ExcessiveUseOfCobblestone** [comment]
I bet this works and that makes me mad lol

**Comment by ATH1909** [comment]
I think pAIs might be able to still make non-virtual accounts, but I don't see how they'd be able to do so without admin assistance.

**Comment by SouDescolado** [comment]
> test it you wonderful fellow
Nevurr

**Comment by SouDescolado** [comment]
> I think pAIs might be able to still make non-virtual accounts, but I don't see how they'd be able to do so without admin assistance.

Hm, I think for a pAI it would not make sense to make it have an isvirtual() because it is a silicon(I think). It should be able to "work between worlds". Maybe MALF pAI would make sense to figure out that the VR and Real bank accounts work with the same algorithm, making it able to replicate what happens in VR.

So there is it, a lorewise reason that justifies my lack of coding ability.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/6b145d2fbd5ec1237837ddfcd429179d2f116841/code/game/objects/items/cards_ids.dm#L173-L181

Can't handwave an interaction that isn't possible.

**Comment by SouDescolado** [comment]
To be fair I didn't touch that. I think this is some kind of sanity check

**Comment by ExcessiveUseOfCobblestone** [comment]
> To be fair I didn't touch that. I think this is some kind of sanity check

was just explaining the pai interaction isn't possible to begin with because they cannot hold an ID card (which is req to make an account)

**Comment by SouDescolado** [comment]
Oh, I'm dumb, sorry.

**Comment by ExcessiveUseOfCobblestone** [comment]
@SouDescolado is this tested?

**Comment by SouDescolado** [comment]
I will try to test it on the weekend if it is needed. A testmerge would be nice but I think it is too niche to be tested live.

**Comment by ExcessiveUseOfCobblestone** [comment]
Typically we only testmerge PRs that need testing on the live server.

This PR can be tested locally.

**Comment by SouDescolado** [comment]
Just because it CAN be tested doesn't mean that it NEEDS to be tested, amirite? (I'll test my 3 pr's during the weekend)

**Comment by SouDescolado** [comment]
It doesnt. It fails to set the account number. Causes runtime

**Comment by SouDescolado** [comment]
Trying to do an alternative locally, Adding 1000000 instead of adding vr

**Comment by SouDescolado** [comment]
To make this work I need to mess with economy code, because you cannot simply assign a random account number. It needs to be created and I need to make some checks to avoid it being spammy. Closing this for now

**Pull request closed without merging**
