### PR TITLE
Removes a redundant traitor item

### PR DESCRIPTION
**Pull request by carshalash**
With economy soon to be dead, I believe we must kill the crab.

## Changelog
:cl:
del: Kills the crab
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Bad move. The CRAB should just drain research and cargo points.

**Comment by HomocidlePancakes** [comment]
Crab can still cuck cargo.

**Comment by LemonInTheDark** [comment]
Improve don't remove

**Comment by carshalash** [comment]
Funny screaming invincible /biz/ meme isnt good.

**Comment by cacogen** [comment]
I grew to not hate this thing once I realised money didn't matter and you had plenty of time to withdraw it anyway. RIP in shit

**Comment by optimumtact** [comment]
wait until the poll

**Pull request closed without merging**
