### PR TITLE
Adds Gag Handcuffs

### PR DESCRIPTION
**Pull request by TrustyGun**
They act like regular handcuffs, but you can break out of them in only a second.

:cl:
rscadd: Adds gag handcuffs to the prize pool for arcade machines. They act like regular handcuffs, but you break out of them in a second.
/:cl:

### CODE REVIEW

**Comment by Anonmare** [comment]
>not giving a pair to the clown

Shit PR tbh

**Comment by TrustyGun** [comment]
I was considering that, but I think it's better if it's available to everyone. (Plus the clown spawns right next to the dorms anyways.)

**Comment by GunHog** [comment]
The Captain has no use for this, when he has access to normal ones on the bridge. This would probably be better off as a clown item, but then the clown could slip, cuff, and restrain someone. So long as the clown keeps dragging a person, he cannot escape.

**Comment by TrustyGun** [comment]
Sure, why not?

**Comment by TrustyGun** [comment]
untitled

These are the new sprites for the cuffs.

**Comment by bgobandit** [comment]
erp intensifies

**Comment by xxalpha** [comment]
this is totally erp

**Comment by GunHog** [comment]
Now it has my support :+1:

**Comment by TrustyGun** [comment]
what are you talking about, these are clearly for practical jokers

**Comment by Niknakflak** [comment]
> listenimg to gunhogs erp agenda

Bad pr now

**Comment by Bawhoppen** [comment]
:-1: this is too much

**Comment by TrustyGun** [comment]
Okay maybe it was a bit much. Changed the original ones on the station to the original sprite, but made a subtype that has the new sprite and jazz for badmins to spawn.

**Comment by lordpidey** [comment]
Could you add this to the arcade rewards?

**Comment by tkdrg** [comment]
Please no, the pink ones were distinctive, if you make it the normal ones it will just confuse people.

**Comment by TrustyGun** [comment]
Remember, it is meant to be a prank/toy, such as the toy esword or the cap revolver. It is meant to scare and confuse players.

**Comment by tkdrg** [comment]
If it's meant to scare and confuse then don't place it in the captain's locker

**Comment by TrustyGun** [comment]
Alright

**Comment by Iamgoofball** [comment]
# **_WE DO NOT NEED PINK FUZZY ERP HANDCUFFS IN THIS CODEBASE_**

**Comment by Bawhoppen** [comment]
we already have alien handcuffs though

**Comment by GunHog** [comment]
# Big text means my opinion REALLY matters

**Comment by Iamgoofball** [comment]
# This is fact

**Comment by Niknakflak** [comment]
# **Damn, I am so cool**

**Comment by Bawhoppen** [comment]
# advanced

**Comment by optimumtact** [comment]
:+1: this is the future we need

ERP will make tg great again

**Comment by TrustyGun** [comment]
the pink fuzzy handcuffs are (b)admin only, literally 99.99% of people won't see them

**Comment by Anonmare** [comment]
I am ready. Take me Jesus.

**Pull request merged**
