### PR TITLE
Makes mulligan antag check for gamemode required players

### PR DESCRIPTION
**Pull request by ghost**
yep... for some reason it didn't do that?

### CODE REVIEW

**Comment by Cyberboss** [comment]
I think this defeats the purpose of rerolling?

**Review by Cyberboss — APPROVED** [review]

**Comment by MoreRobustThanYou** [comment]
doesn't mulligan usually only roll if a wizard/blob died quickly and is generally unrobust?

**Comment by optimumtact** [comment]
This should be checked IMO, it doesn't make any sense to start a round with less players than the designers think it can support just because it's a mulligan from another round type

**Comment by MoreRobustThanYou** [comment]
Closing and reopening since I think travis has been fixed

**Pull request merged**
