### PR TITLE
Prevent AIs from changing their shell's icon_state arbitraily

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

See title
## Why It's Good For The Game

https://user-images.githubusercontent.com/12817816/215912563-78d1df96-ef48-43f9-9443-104e1709a7d2.mp4

See title
## Changelog
:cl:
fix: AIs can no longer change their shell's icon_state to any image at will
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
literal soul removal

**Comment by rasepretep** [comment]
> Prevent AIs from climbing on tables

Literally unplayable

**Comment by san7890** [comment]
i thought we fixed ais climbing on tables when did that regress. did we never fix it?

**Comment by Kubisopplay** [comment]
Removing minor funny thing that has no major mechanical impact. Shame

**Comment by NamelessFairy** [comment]
This PR makes it so that borgs cannot move until selecting a module. I assume this is un-intended.

**Comment by Kylerace** [comment]
justify this change or im closing this

**Comment by ZephyrTFA** [comment]
> justify this change or im closing this

Because it was a bug that fixed in the past, and it regressed.
And because the AI being able to change the icon_state of their current mob, even if its a shell, shouldn't be a thing?

**Comment by ZephyrTFA** [comment]
I mean if you want the bugs to stay in, that's your choice.

**Comment by Kylerace** [comment]
title and changelog are misleading and should be changed to clarify that they only stop the ai from changing their shells icon_state to any portrait

**Pull request merged**
