### PR TITLE
Adds Pet Collars to autodrobes.

### PR DESCRIPTION
**Pull request by Wilchenx**
Now Heads don't have to get 5k crates with useless animals to rename their pets.

👏

### CODE REVIEW

**Comment by jughu** [comment]
Its not a kinkmachine shezza!

**Comment by The-clown-known-as-Pepe** [comment]
@jughu listen up, i know you've started playing citadel recently but naming your pet as a head after a crewmember then fucking it is still bestiality.

**Comment by Bawhoppen** [comment]
This is actually still creep, even if it's not a balance related thing

**Comment by Iamgoofball** [comment]
@KorPhaeron 
Come on this is straight fetish

@cheridan pls

**Comment by The-clown-known-as-Pepe** [comment]
@Iamgoofball pets are not fetish ))

**Comment by KorPhaeron** [comment]
So make the collars spawn with the pets or in the heads of staff lockers who have pets rather than in the vending machine for human clothing

**Comment by The-clown-known-as-Pepe** [comment]
@KorPhaeron i like the funny implication that it creates along with blindfolds and muzzles.

**Comment by Iamgoofball** [comment]
why are blindfolds and muzzles in the autodrobe what the fuck

**Comment by Bawhoppen** [comment]
@Iamgoofball You realise Cheridan quit right?

**Comment by KorPhaeron** [comment]
Giving catgirls collars to wear from the autodrobe will be more crying and drama than I want to deal with

**Comment by Mercenaryblue** [comment]
How about you add a pet collar to HoP office instead?

**Comment by KorPhaeron** [comment]
There already is one in his locker

**Comment by optimumtact** [comment]
why are you never in irc

**Comment by KorPhaeron** [comment]
I will be on in like 20 minutes

**Pull request closed without merging**
