### PR TITLE
Removes the placeholder alien bed.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR removes the placeholder alien bed and its associated sprite from the game, and replaces its appearance in the snowdin ruin with the actual abductor bed.

## Why It's Good For The Game

Well, placeholders are bad, and unused content is bad.

Also it was ugly.

## Changelog

:cl:
fix: Gets rid of the placeholder alien bed and replaces its appearance in Snowdin with the proper alien bed.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
how the hell does this require 5 reviews

**Comment by tralezab** [comment]
> how the hell does this require 5 reviews

the council will decide your fate

**Comment by ArcaneDefence** [comment]
Two maptainers, two spritetainers. 
You're in their realm, normie

**Review by Twaticus — APPROVED** [review]

**Comment by Fikou** [comment]
its not unused if its used in that away mission 😕

**Comment by CRITAWAKETS** [comment]
> its not unused if its used in that away mission 😕

i mean it was clearly accidentally using it instead of the abductor bed, since it was a crashed alien ship.

**Comment by Fikou** [comment]
> > its not unused if its used in that away mission 😕
> 
> i mean it was clearly accidentally using it instead of the abductor bed, since it was a crashed alien ship.

image
words from the creator of the map

**Comment by CRITAWAKETS** [comment]
Huh. Well this bed still is quite useless and an old remnant, and i dont see why we should be keeping it.

**Comment by Fikou** [comment]
for shits and giggles

**Comment by CRITAWAKETS** [comment]
yeah shit is what it is

**Pull request merged**
