### PR TITLE
[FEATURE] Movable Abandoned White Ship

### PR DESCRIPTION
**Pull request by Steelpoint**
Inspired from the following thread and issue report
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=2593
https://github.com/tgstation/-tg-station/issues/7153

Adds the ability to fly the abandoned white ship to the space station, currently that's the only place you can fly it to and once its on the station you cannot take it anywhere else, but it is easy to add in other destinations.

The White Ship is flipped around so it can fit in the docking area, also the lower arrival doors are now all access.

(I even think I could "ram" it into the station, though that would likely kill a bunch of people)

Image of it attached to the station's arrival docking area.
screenshot 2015-01-19 21 15 13

### CODE REVIEW

**Comment by TZK13** [comment]
Holy shit this is fairly cool. Does this include the little section connected with just lattice at the back?

**Comment by Steelpoint** [comment]
No, that's left behind. It does include the first little section but not the second.

**Comment by AnonymousNow** [comment]
I am pleased and impressed. The potential for this is enormous.

**Comment by AlexCrimson** [comment]
Does this mean you could add custom Z-level locations that only the white ship could reach? Would be a neat way to explore space.

**Comment by Steelpoint** [comment]
In theory you could, I don't currently know the specifics of creating new z-levels.

But yes, you could create areas that the ship, or any ship, can go that you cannot normally access.

**Comment by TZK13** [comment]
It would be nice if the mass driver was moved so that it launches into space from where it's docked instead of point blank at the station.

**Comment by Steelpoint** [comment]
Currently it takes 5 seconds for this ship to get to a destination, I can change that time.

How long do we want the ship to remain in flight before reaching any destination? 

10 seconds? 30? A minute?

**Comment by Anonus** [comment]
Two things; go with 30 seconds, and replace all the diagonal walls inside the ship with full-tile walls because they'll break and look like shit otherwise.

**Comment by Steelpoint** [comment]
I fixed that. I replaced the internal diagonal walls with a new sprite that has both the diagonal wall and the floor in the same sprite.

**Comment by Anonus** [comment]
Works for me!

**Comment by Steelpoint** [comment]
I would like to get the status display's to show the amount of time left until the white ship reaches somewhere, sadly I can't figure out how to tie it to the white ship.

Otherwise its all good.

**Comment by bear1ake** [comment]
Cool! I want it.

**Comment by peoplearestrange** [comment]
(+1) Nice.

On a side note I've noticed the corner space glitch thingy on the escape shuttle. Which is new...

**Comment by Carn** [comment]
close this please

**Comment by ike709** [comment]
:+1:

**Comment by Steelpoint** [comment]
@Carn why do you want me to close this?

**Comment by hornygranny** [comment]
conflicts with fixes carn is working on

**Comment by ike709** [comment]
rip all fun

**Comment by Steelpoint** [comment]
I would have closed this myself if someone informed me of that.

**Comment by AnonymousNow** [comment]
"I felt a great disturbance in the Force, as if millions of voices suddenly cried out in terror and were suddenly silenced."

And just like that, it was gone.

**Comment by Steelpoint** [comment]
Can this be reopened now that Carn's fix PR was merged?

**Comment by RemieRichards** [comment]
@Steelpoint have fun defending this from conflicts until the map is clear to merge it. :)

**Comment by Steelpoint** [comment]
I'll do my best, as always.

**Comment by Steelpoint** [comment]
I'll fix merge conflicts once my other map PR's are finished.

**Comment by Steelpoint** [comment]
I'm going to redo this PR, I noticed that the mapmerger and such has failed to account for changes made to the map even though I would solve merge conflicts.

I'll open a new PR later.

**Comment by nopm** [comment]
Hey, i noticed that BYOND has a easy programming lenguage, so i want to learn my first programming lenguage to do some cool things in BYOND, could someone plase redirect me to somewhere where i can learn my first programming lenguage? thanks in advance

**Comment by Miauw62** [comment]
you should go here for your first progaming guano: http://interactivepython.org/runestone/default/user/login?_next=/runestone/default/index

**Pull request closed without merging**
