### PR TITLE
Revert "Swarmers think the deep fryer is too tasty to eat"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#23931

needs a player poll

### CODE REVIEW

**Comment by Armhulen** [comment]
fucking l o l

**Comment by RemieRichards** [comment]
New player poll: Ban goof
Thumbs this comment to decide.

**Comment by Cyberboss** [comment]
This was merged wtf?

**Comment by Iamgoofball** [comment]
@RemieRichards gave it an upvote

**Comment by RemieRichards** [comment]
Good use of democracy friend

**Comment by kevinz000** [comment]
the retardation is real.

**Comment by optimumtact** [comment]
@RemieRichards please don't close pr's, as per @MrStonedOne 's new direcctives we have to leave pr's open for at least 24 hours before we close them

**Comment by RemieRichards** [comment]
If that's legitimate I hope he's prepared to deal with goofball.
and by deal with I mean remove.

**Pull request closed without merging**
