### PR TITLE
Ventcrawling Fixes

### PR DESCRIPTION
**Pull request by RemieRichards**
tg version of https://github.com/d3athrow/vgstation13/pull/4251
- Fixes moving between pipeline datums not updating pipe vision
- Fixes login() not correctly updating pipe vision.
- Moves `var/datum/pipeline/parent` from pipes and unary, to atmospherics base class (Before you shout at me Aran, it will always be null on the machines that don't use 1 parent (Binaries/Trinaries) changing _nothing_ mechanically, atmos wise)
- Makes pipe vision visible in darkness
- Makes pipes/atmos machines hold their images AND delete the image if it is destroyed, the makes destroyed pipes disappear from the view correctly
- fixes #9311

### CODE REVIEW

**Comment by AlexCrimson** [comment]
Can you do anything about traversing pipes in darkness? You cant see shit when moving through maint pipes or a room without lights.

**Comment by ComicIronic** [comment]
You can by setting the image layer high enough. There's no real way around opacity, though.

**Comment by Chocobro** [comment]
remie what is 'venctawling'

**Comment by Aranclanos** [comment]
about the parent, its fine-ish don't worry, if its needed, its needed.

**Comment by RemieRichards** [comment]
@Aranclanos yeah, I have my reasons and explanations as to why it should be fine above, I just wanted to put it past you since, you know, Atmos is a lot of your work and I wouldn't want to shit it up.

**Comment by Aranclanos** [comment]
You have to do something about last_played_vent though, it shouldn't exist.
And the spawn(1) probably needs some work, its kinda out of place with all the other movement buffs/debuffs etc, Correct me if im wrong here, didn't really researched a lot.

**Comment by MrStonedOne** [comment]
@Cheridan @Jordie0608 since my pr fixing atmo pipes deleting when you unwrench them was absorbed in to this pr, can somebody merge this?

**Pull request merged**
