### PR TITLE
Removes unused code.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Purrbation was disabled.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
can we wait and let people calm down instead of continuously escalating and trolling everyone

**Comment by The-clown-known-as-Pepe** [comment]
but where's the fun in that?

**Comment by AlchemicalGitHub** [comment]
## Kor - Protector of the Degenerates

**Comment by Iamgoofball** [comment]
Sounds good but if we're still disabled in a month I'll PR it again

**Comment by optimumtact** [comment]
we should merge this and lock the cat config to prevent admins editing it

**Comment by MrStonedOne** [comment]
purbation isn't disable, what?

**Comment by optimumtact** [comment]
he means cats, he's just brain damaged

**Comment by MrStonedOne** [comment]
but this doesn't remove the cat code, it removes the admin purbation code, code that still works, and is still enabled.

**Comment by Cyberboss** [comment]
ree

**Comment by MrStonedOne** [comment]
Its like nobody looked at the pr, and just assumed based on current events.

**Comment by The-clown-known-as-Pepe** [comment]
oranges no! you'll lose maintainer again!

**Comment by Supermichael777** [comment]
Read cats

**Comment by Iamgoofball** [comment]
@mrstonedone
Admins are bypassing your config change by forcing it on players who ahelp. Additionally I've heard of edited config vars too.

**Comment by Iamgoofball** [comment]
I figured we should remove methods to bypass it.

**Comment by MrStonedOne** [comment]
I think you have a really odd idea of what admins can and cannot do.

**Comment by Iamgoofball** [comment]
VV config subsystem, edit value for mutant humans.

Right click player, "apply purrbation" in VV menu. Come on.

**Comment by MrStonedOne** [comment]
ya.

But you are assuming those things are not features

They are features

Also you still lied in the pr

`Removes unused code` code removed is used.

The config settings only control if players can become cat girls. they mean nothing about if admins can make people cat girls

**Comment by Iamgoofball** [comment]
fuck

**Pull request closed without merging**
