### PR TITLE
Adds two new biogenerator chemicals to botany.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
This will help ease the burden of justice off of the minds of the wicked, or something poetic like that.

## About The Pull Request
This adds two new chemicals, produced purely by the biogenerator.
**Enduro Grow:**
This chemical ravages a plants yield and potency, but in exchange, it provides an improvement in the plants endurance stat. Something that was difficult to improve with the new system was plant endurance, which was altered by either plant grafting, or by mutations, neither of which enabled a very active way to enable this.  This meant for some plants, you were left waiting for a long time either harvesting multiple grafts to boost a plants endurance average upwards, or waiting for mutations to hopefully raise endurance. By comparison, this chemical will more often then not shave off large portions of the plants potency and yield in order to boost lifespan (Not to self, I should have gone with like a warlock theme for the name)

Liquid Earthquake:
On the flipside, there also exists very few ways to increase the plants production speed as well, outside of saltpetre. I wanted for there to be a self-sustainable way to improve a plants production speed, but come with an applicable downside as well, so I included an increase in both weed change and weed rate to accompany it. 

## Why It's Good For The Game

Both chemicals are working to make good on that promise that turbotany is less reliant on chemistry in order to perform effectively. Both of these chemicals being grown through the biogenerator enables it as a way to allow botany to do more within their own department, BUT, in the spirit of inter-departmental cooperation, there exists a better alternative should you chose to ask for help from chemistry.

In addition, both chemicals have unique and distinct upsides in the new system. Having fast production speed is exceptionally helpful for mass production of plants, but there are no good ways to naturally lower weed rate and chance, so you're trading momentary gain for potential longterm downsides. Having high endurance allows for a greater deal of genetic manipulation of a plant, 

## Changelog
:cl:
add: Adds Liquid Earthquake, a botany biogenerator chem that increases production speed, but increases plant weed susceptibility.
add: Adds Enduro Grow, a botany biogenerator chem that improves a plant's endurance stat, but decreases it's yield and potency.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
while you are here how about a chem that makes plant last longer(making their other stats shit) and add plant pots (subtype of hydro tray)  so we can use grown plants as decorations?

**Comment by ExcessiveUseOfCobblestone** [comment]
mutspeed chem next 😏

**Comment by Krysonism** [comment]
To the limited extent endurance is needed this is handled in a more interesting way by grafting.

The second chem is simply not worth it because high weeds is generally more problematic than high production.

My third point is that the biogenerator is not an interesting way to deliver chemicals, or anything really.

**Comment by adamkad1** [comment]
Idea- Add gene shreas to pod people ruin

**Comment by ArcaneMusic** [comment]
> Idea- Add gene shreas to pod people ruin

Uh, #51343

**Comment by adamkad1** [comment]
> > Idea- Add gene shreas to pod people ruin
> 
> Uh, #51343

Oh, i must have missed it. cool

**Pull request merged**
