### PR TITLE
Reduces HoP job slot cooldown

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: NanoTrasen Human Resources Division
balance: The HoP's console now has a thirty second cooldown for opening and closing job slots.
/:cl:

old cooldown was excessive.

### CODE REVIEW

**Comment by GunHog** [comment]
I may now open clown slots SIX TIMES AS FAST!!!!!!!!!!!!!!!!

**Comment by lzimann** [comment]
Make it at least 30

**Comment by GunHog** [comment]
I...may now open clown slots...twice as fast...

**Comment by Tacolizard** [comment]
@GunHog blame lzimann i only did it out of fear.

**Comment by Cheridan** [comment]
should probably make this a config option so that when whole station is clowns and we need to change this back it'll be easier

**Comment by ShizCalev** [comment]
time for 50 wardens.

**Comment by calzilla1** [comment]
>not 50 clowns
Up yo game

**Comment by Tacolizard** [comment]
kevinz kil me

**Pull request closed without merging**
