### PR TITLE
SOMETHING'S WRONG, I HOLD MY HEAD, BILLY HERRINGTON IS FUCKING DEAD

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: RIP Billy, you'll be the boss of heaven's gym now 😢 
/:cl:

im sad now

puts that jabroni outfit in the lockers since he won the final battle i guess

### CODE REVIEW

**Comment by Iamgoofball** [comment]
https://www.youtube.com/watch?v=2MsxEPqbcp4

**Comment by PKPenguin321** [comment]
o7

**Comment by 81Denton** [comment]
28577708_2123621564541726_7309621084628713472_o

**Comment by Qustinnus** [comment]
i feel like the bee description PR should be re-opened and merged out of respect for our fallen.

**Comment by Iamgoofball** [comment]
actually yeah that's a better idea

**Comment by Durkel** [comment]
Rest in peace, Billy. I'll have to play some gachi to the server for him out of respect.

**Comment by Shadowflame909** [comment]
oh snap this got merged what does  this dooo

**Comment by 81Denton** [comment]
clipboard02
get a load of this jabroni

**Pull request merged**
