### PR TITLE
Fixes #12491 - Simple_Animal Fire/Oxy damage -> Brute

### LINKED ISSUE #12491: Simple Animals: Fireloss = Bruteloss?
Just an oddity I noticed:

https://github.com/tgstation/-tg-station/blob/61d23d8c1112fdc45bce2e8422122ca136aa248b/code/modules/mob/living/simple_animal/simple_animal.dm#L277

Apparently Fireloss is actually bruteloss?

### PR DESCRIPTION
**Pull request by Cheridan**
They can take all kinds now.

### CODE REVIEW

**Comment by Cheridan** [comment]
gimme dat antag token @KorPhaeron

**Comment by Zilenan91** [comment]
So this converts all those sources of damage into brute right?

**Comment by KazeEspada** [comment]
I mean technically they still convert it all to brute.

**Comment by Shadowlight213** [comment]
@cheridan please place the fixes issue in the pr description so the issue is automatically closed.

**Comment by KorPhaeron** [comment]
>simple animal
>made less simple
>add no way for them to actually heal this damage

Denied sorry

**Comment by KorPhaeron** [comment]
Why was that even an issue report in the first place?

**Comment by AnturK** [comment]
This is going to cause a cascade of bugs and inconsistencies.

**Comment by Cheridan** [comment]
@AnturK Yeah I had a feeling

Neat so its not a bug then issue closed

**Pull request closed without merging**
