### PR TITLE
Buffs the clown.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Removes slowdown from clown shoes.

### CODE REVIEW

**Comment by CosmicScientist** [comment]
For in case the previous PR attempting this (Kor left before merge/close) has any useful comments: #11219

**Comment by bgobandit** [comment]
:-1: 

A true clown takes pride in his shoes and his speed.

**Comment by Steelpoint** [comment]
:-1: 

In all honesty I much prefer the current system, the Clown's a sort of hard mode job already and the shoes help emphasize that. Sort of how the Mime can't speak unless he discards his mime powers the Clown can't run fast unless he discards his clown shoe honking.

**Comment by Core0verload** [comment]
:+1: I wanted to re-open this PR myself, but you were faster.

**Comment by Dorsisdwarf** [comment]
Clown does not need buffs, he's too OP already.

**Comment by Core0verload** [comment]
Of course being unable to use combat items is extremely overpowered! How about nerfing it?

**Comment by Dorsisdwarf** [comment]
Confirmed to be a clown player, does not understand "jokes", just like all other ss13 clowns

**Comment by Core0verload** [comment]
It's nice to see another clown player here!

**Comment by Dorsisdwarf** [comment]
Everyone's a clown player on the Internet

**Comment by Aranclanos** [comment]
naaah, I always loved how the clown suit is huge, easier to hit in fights and his shoes make him slow.

I FIND IT CLOWNY

**Comment by Iamgoofball** [comment]
I don't really agree. I feel the clown shoes degrade the clown when it comes to high level competitive play. Right now the Janitor is the better pick when it comes to comp because of the access to noslips and the ability to slip up the floors scot-free. The clown needs a buff to be on par with the other jobs in the scene, and while it may be suitable for casual play, it is not for the tournaments.

**Comment by Aranclanos** [comment]
competitive clown play?
holy shit someone WAKE ME UP

**Comment by bgobandit** [comment]
HONK ME UP INSIDE

https://aberrantkenosis.bandcamp.com/track/bring-me-to-life-bike-horn-version

**Comment by Invisty** [comment]
Woah really? Mimes are already crazy OP with their wall and BOTTLE OF MASSIVE HEALING. What does the clown get? Two slipping objects, disability, and slowdown.

**Comment by CosmicScientist** [comment]
Why not let a traitor mind able to remove the slowdown on the shoes? It's a tad long-winded but not only does it make them faster than the janitor (galoshes give slowdown if I'm not mistaken) but if they're a normal clown it doesn't remove the magic.

**Comment by CPTANT** [comment]
@CosmicScientist 

Special rules for how things work just for antags is horrible.

The whole point of playing traitor clown is to be a walking idiot and still manage to slip the captain, weld him in a locker and toss him out the mass driver.

**Comment by CosmicScientist** [comment]
@CPTANT but you're not a walking idiot, you explicitly lose the clown's clumsiness at roundstart if you're a traitor and unless I'm mistaken, agent IDs require an antag mind to forge. You're a regular crew member with two stuns, one with counter play, the other barely lasting and unless you want to look like a clown clown during your nefarious schemes, you'll just get a costume out of the machine and have zero slowdown. Hell you could even remove player error by asking if the wearer has an antag mind when they're put on.

**Comment by ExplosiveCrate** [comment]
"CLOWN IS RUNNING TO FAST, GET HIM"

**Comment by Aranclanos** [comment]
I'll just step ahead and say no to this PR

**Comment by Iamgoofball** [comment]
the dream is crushed

**Pull request closed without merging**
