### PR TITLE
Changelings: The Changelinging

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
balance: The abilities of changelings have been COMPLETELY overhauled!
/:cl:

I ditched the old Evolution points system for a new one! You start out with 4 evo points... enough for fleshmend and tiring sting or tiring sting and mutesting... You gain more by absorbing people. One absorption = 2 additional evo points. You can't readapt anymore.

Tiring Sting has been added, which is kinda like the Peacekeeper borg's hypospray... but it has some morphine, too.

Also, lings can't revive or fleshmend if on fire.

### CODE REVIEW

**Comment by banthebantz** [comment]
wew

**Comment by MoreRobustThanYou** [comment]
> No because then it will open at the back of the PR list and I don't want to reopen 40 PRs

Responsibility of people who open things during the freeze to reopen them as a new PR

**Comment by ma44** [comment]
>Making a antag grow more powerful over time the more it kills
Murderboning has never been more fun.

**Comment by kevinz000** [comment]
>making antags directly more powerful by murderboning

Dumbest PR of the year.

**Comment by MoreRobustThanYou** [comment]
> giving antags murderbone abilities at roundstart

even dumber feature

**Comment by kevinz000** [comment]
>this guy thinks changelings can't murderbone with only 4 points

lol

**Comment by kevinz000** [comment]
well it might dissuade the less robust players to hold off until they get more absorbs but all this'll do is make the more robust players fucking unstoppable because they'll quickly rack up kills to the point they have all abilities.
get out with your attempted changeling balance that just buffs it for anyone with murderboning experience.

**Comment by MoreRobustThanYou** [comment]
fine whatever

**Pull request closed without merging**
