### PR TITLE
Fixes the horrible injustice of getting too many pets

### LINKED ISSUE #7742: Bug: Critter Crate Numbers
Ever since the butterfly update, all critter crates start out with 2 critters (or more) in them as opposed to 1.

Similarly, critters do not show up on manifests.

### PR DESCRIPTION
**Pull request by Incoming5643**
Fixes #7742

### CODE REVIEW

**Comment by iamgreaser** [comment]
Is the convention (i=0; i < amount; i++) or (i=1; i <= amount; i++)? May want to clarify that.

**Comment by Incoming5643** [comment]
I don't think anyone's been anal enough to enforce that one way or the other yet.

**Comment by Miauw62** [comment]
99% of all coding (not just this game) uses for(i=0; i < amount; i++), BUT that is because proper lists/arrays are 0-based, and BYOND lists are 1-based.

**Comment by bgobandit** [comment]
no fun allowed

**Pull request merged**
