### PR TITLE
Puts the window debris list to where it belongs (in the trash)

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
:cl: Naksu
code: windows no longer hold whole instances of the things that pop out from them hoping for the day some assistant breaks the windows in reebe. 
/:cl:

I want to give plasma glass windows their own shard type and make it produce nicer spears. Separate PR though.

### CODE REVIEW

**Comment by Kagus** [comment]
I believe Goon does/did plasmaglass shards. Plasmaglass spears are nothing to sneeze at.

**Comment by Barhandar** [comment]
And singularity only exists on pubby, so...
>I believe Goon does/did plasmaglass shards. Plasmaglass spears are nothing to sneeze at.

Especially since plasmaglass is _extremely_ durable.

**Review by SpaceManiac — APPROVED** [review]
:pray:

**Comment by vuonojenmustaturska** [comment]
yeah, and if singulos become an issue we can make a pooling system

**Comment by Kagus** [comment]
I'm pretty sure singulos are and will continue to be an issue with or without this PR.

It's just varying degrees of fuckedness.

**Comment by Borisvanmemes** [comment]
Goonstation does in fact have plasmaglass shards but unless i just don't know how you cannot in fact make spears out of glass shards.

**Comment by Kagus** [comment]
Spears on Goon are generally made via a workbench, I'm not sure if those take shards or exclusively full plates. Normally people are too busy making weapons out of exotic arc furnace alloys to be bothered with plasmaglass.

It's been a while since I've been on Goon though, so it's entirely possible that you can't make them out of the shards. I mean, it's also Goon, so it's also entirely possible that there's just some secret handshake method of ghetto crafting one that neither of us knows about.

**Pull request merged**
