### PR TITLE
Makes the taskbar icon the TG thing

### PR DESCRIPTION
**Pull request by AffectedArc07**
## About The Pull Request
This PR changes our taskbar icon from the default SS13 icon to the TG logo triskaidecagon thingymajig.
image

## Why It's Good For The Game
It adds some flair to the server and stands out against the default logo nerds.

## Changelog
:cl: AffectedArc07
tweak: The taskbar icon for the game is now the TG logo
/:cl:

### CODE REVIEW

**Comment by nfreader** [comment]
Do you need a 64x64 version of the icon?

**Comment by AffectedArc07** [comment]
@nfreader I ripped this from the TGS4 files, they had 16x16, 32x32, 48x48 and 96x96. All the sizes except the one I need. If you do have a TG icon with the white backing in this size, I would love that.

**Comment by MrDoomBringer** [comment]
Why not just get the 32x32 and scale it up by 200% in any painting program?

**Comment by wesoda25** [comment]
> Why not just get the 32x32 and scale it up by 200% in any painting program?

Idk sounds like a lot of work to me

**Comment by PKPenguin321** [comment]
this would make sense to be config-able

**Pull request merged**
