### PR TITLE
Adds Grangran Codecluck, the memorial chicken

### PR DESCRIPTION
**Pull request by ghost**
- Adds an HG memorial chicken to Botany
- It has custom attack verbs: "Checks out" for help, "Pushes" for disarm, and "Reverts" for harm
- It has 242 health (HG has 242 commits to the /tg/ repository)
- Long-ass description

### CODE REVIEW

**Comment by bgobandit** [comment]
first meme PR post

**Comment by Aranclanos** [comment]
no player's references, sorry.

**Comment by Xhuis** [comment]
H U G B O X
U
G
B
O
X

**Comment by Incoming5643** [comment]
Obvious work around: never actually play the game

**Comment by MrStonedOne** [comment]
>no player's references, sorry.

Hg isn't a player, they never play.

**Comment by Xhuis** [comment]
Owner's verdict is in, @Aranclanos

**Comment by MrStonedOne** [comment]
"owner"

you got a lot to learn around here boy

**Comment by Xhuis** [comment]
What do you mean I never said that :^)

**Comment by Xhuis** [comment]
### FUCK

**Comment by Xhuis** [comment]
So are we getting this reopened or what

**Comment by Aranclanos** [comment]
whos mso?

**Comment by Dorsisdwarf** [comment]
Will reopen for shekels.

**Comment by tuypo1** [comment]
I like the idea but im against having some silly health amount just make it as strong as a normal chicken or at least make its strength a nice round number don't lete shitty jokes get in the way of balence

**Comment by Shadowlight213** [comment]
Coders don't play. Not a reference.

**Pull request closed without merging**
