### PR TITLE
Removes Tech-Disk Exports

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
balance: Research done on-site is now Centcom property and can no longer be sold to the market.
:cl:

Reason: Technodes cost nothing except arbitrary points that passively generate. Cargo does not need a reliable way to get way over 100K points easily each round from nothing.

Once I take a look at the node numbers I may readd this if I don't ever get to Tycoon Cargo (tm).

also > 500 base money for a disk you can make with small amounts of metal and glass

epic.

I'll close this if someone can provides a reasonable alternative since I plan on bringing them back later on my terms anyways.

### CODE REVIEW

**Comment by Jalleo** [comment]
Havent there been other PR's already trying to remove this and have been closed?

**Comment by ExcessiveUseOfCobblestone** [comment]
If so tell them to play the game lol

**Comment by Kromgar** [comment]
As a shaft miner with a fully upgraded orm i made over 200k cargo points in 5 minutes. 

Shit was cash

**Comment by ma44** [comment]
Should probably deserve a nerf instead of removal, considering that if this were to be killed, cargo would loose 40% or higher of it's income (why is it that high? tech disk powercreeps lul)

**Comment by KorPhaeron** [comment]
Crate prices were made something like 8 years ago when cargo only got a small amount of passive cash+money back for sending crates

Now we have stock markets+mineral exports +random shit exports,, they don't need hundreds of thousands from tech disks on top of that

**Comment by ChangelingRain** [comment]
why don't we have a `kor approved` label? hmm...

**Review by imtakingabreakdontatme — APPROVED** [review]

**Comment by KorPhaeron** [comment]
github has one built in

**Comment by ExcessiveUseOfCobblestone** [comment]
even stockmarkets + exports require some time investment and they both have downsides (stock means you temporarily can't use the money and exporting other items means you can't use that item anymore).

Tech disks cost literally nothing to anyone unless you want to theorycraft that several hours in you eventually run out of map-spawned tech disks which means you have to use metal and glass (god forbid) to make more while you have T4 proto & ORM.

@ma44 make the items from techwebs have export costs then. I plan on eventually doing away with exports and stocks and shifting to a production line (factorio-esque) game for cargo to work with.

**Comment by Tlaltecuhtli** [comment]
thing is cargo being able to order loads of crates is vital in like half of the gamemodes (warops , clocks, revs) when kor first removed it on high pop officers would just go around killing people because lol no mindshield implants during rev

**Comment by Jalleo** [comment]
To be honest there is no easy way to remedy this unless we either do, 
A: Scale prices to the amount of people online and reduce base costs by a factor of ten or more.
B: Feedback loop from the statistics (daily/weekly/monthly) To scale the price of such exported items.
C: Something else
D: All of the above and oh lets add balancing values to a config.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Tlaltecuhtli you don't need 100k to buy mindshields try again.

**Comment by KorPhaeron** [comment]
Mindshields are 1k each so on a 100 person round you actually would but that is insane to balance around

Jalleo is right that we need mindshield availability to scale to pop or something if we ever want sane prices for the rest of cargo

**Comment by Robustin** [comment]
Was mineral exports readded?

**Comment by KorPhaeron** [comment]
Yeah

**Comment by ma44** [comment]
Tech disks giving 500 points was always a thing ever since exports were a thing over 2 years ago. 

https://github.com/tgstation/tgstation/commit/04f1aafa7820ea74ef238ba0831567751313f47b#diff-394b6c00347f43f9fbf1c9597b2cb798R3

It should probably be reworked by allowing **new things** to be ordered whenever you export some research, instead of enjoying powercreeped supply points, while anything that doesn't involve minerals provides not that many supply points. 

**cargo factory when**

**Comment by davethwave** [comment]
It would be interesting if by using a factorio kind of setup and creating machines from the ore or ordering them so you can create products to sell in mass bulk.

**Pull request merged**
