### PR TITLE
Revert "Many Buckled Mobs"

### LINKED ISSUE #16027: Latest master is fugged
Runtimes like multiple times per tick
FOREVER.

"Cannot read  #.len"
Not "null.len" just ".len"

these runtimes are also timestamped? it's weird.

<B>Edit:</B>:
https://github.com/tgstation/-tg-station/blob/master/code/game/atoms_movable.dm#L64
this line apparently, DESPITE NOT OCCURRING IN TESTING (FUG YOU DUNC)

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/-tg-station#15964

Fixes #16027

Master being functioning is more important than buckling multiple mobs, and remie has stated they aren't going to fix it tonight. No clue when a fix will be done.

@MrStonedOne

### CODE REVIEW

**Comment by RemieRichards** [comment]
You are 3000% retarded.

**Comment by Iamgoofball** [comment]
relax we can throw this on the test merge until you fix your shit

**Comment by Buggy123** [comment]
merge posthaste

**Comment by Iamgoofball** [comment]
mso found a better fix

**Pull request closed without merging**
