### PR TITLE
(balanced) hypernob gloves + supermatter immunity trait

### PR DESCRIPTION
**Pull request by azrael-x86**
## About The Pull Request

gloves

this PR adds noblium gloves into the game, a mid-round craftable glove sub-type that protects you from the supermatter and electricity, at the cost of a slight slowdown.

essentially, the noblium gloves are a way to craft an equivalent to the captain/ce gloves. it remains obtainable enough that people won't just dismiss it to buy insulated gloves, but also has enough drawbacks (2 seconds to put on, 0.8 slowdown) to ensure that nobody is totally switching out their arsenal for these bad boys.

along with the gloves, a new trait has been introduced, TRAIT_SUPERMATTER_IMMUNITY. whenever you have this traitor, you'll gain the ability to touch the supermatter as well as pick up supermatter slivers. no antag dropping supermatter slivers on the floor can stop you now!

## Why It's Good For The Game

adds a fun little item as a prize for procuring hyper-noblium crystals from the crystallizer, and also a viable alternative to cap gloves/ce gloves. fun for the whole family!

## Changelog

:cl:
add: adds hypernob gloves and supermatter immunity trait
/:cl:

### CODE REVIEW

**Comment by magatsuchi** [comment]
CONDUCTOR WE HAVE A PROBLEM

**Comment by tralezab** [comment]
hard no on anything that gives supermatter immunity, some things should be left as wholly deadly devices

**Comment by magatsuchi** [comment]
> hard no on anything that gives supermatter immunity, some things should be left as wholly deadly devices

says there should be no supermatter immunity, refuses to elaborate

**Comment by tralezab** [comment]
i'm happy to elaborate on "no supermatter immunity", what do you need elaborated

**Comment by magatsuchi** [comment]
> i'm happy to elaborate on "no supermatter immunity", what do you need elaborated

this got quite positive reception on the other draft PR. why assume that it should be strictly deadly with no means of making it slightly safer? you'll still get dusted if you walk into the sm

**Comment by magatsuchi** [comment]
it only protects you from attacking it, and picking up slivers

**Comment by YakumoChen** [comment]
>and picking up slivers

This is a problem in itself, I think.

**Comment by magatsuchi** [comment]
> > and picking up slivers
> 
> This is a problem in itself, I think.

i could potentially have a sliver dust itself it thrown from hands

**Comment by YakumoChen** [comment]
That would just make even less sense than having a craftable item that lets you toss them in the first place

**Comment by YakumoChen** [comment]
The only viable use for the item is to pick up slivers and we really don't want players being able to do that without the theft objective.

**Comment by tralezab** [comment]
> > i'm happy to elaborate on "no supermatter immunity", what do you need elaborated
> 
> this got quite positive reception on the other draft PR. why assume that it should be strictly deadly with no means of making it slightly safer? you'll still get dusted if you walk into the sm

because we still have to have wholly deadly elements in the game with no protection beyond entire avoidance. Same reason singulos don't have a teleporter that jumps you to safety if you got too close. It just has to be a standard I maintain for the main engine and huge sabo target that it itself is volatile and cannot be tamed

**Comment by Mothblocks** [comment]
GBP

**Comment by Wallemations** [comment]
That glove sprite...
image

**Pull request closed without merging**
