### PR TITLE
Robot hats fix and addition

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 

:cl: Dax Dupont
fix: You no longer hit borgs with hats you want them to wear.
add: Viva la borg, engieborgs can now wear hats
add: Borgs can now wear more hats.
/:cl:

[why]: Fixes a bug and engie borgs look just as silly as other borg with hats.
Technically it isn't on the head head, but rather ontop of the borg which works for me since it's a perfect place to put a hat.

dreamseeker_2018-03-20_00-03-05
dreamseeker_2018-03-20_00-03-01
dreamseeker_2018-03-19_23-45-32

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
> rather onto of the

**Comment by CitrusGender** [comment]
Absolutely.

**Comment by Tlaltecuhtli** [comment]
pic of each borg please

**Comment by DaxDupont** [comment]
@Tlaltecuhtli hard hat on each borg or what?
All borgs except the engiborg already had hats.

**Pull request merged**
