### PR TITLE
Resprites and animates 10 sprites from device.dmi

### PR DESCRIPTION
**Pull request by ghost**
## Explain your PR

Resprites 10 old sprites from the devices.dmi page. Two of which where recently resprited which i was not aware of, the botany and dna scanners, and one of which i really hate looking back on ( the nanotrasen autoimplanter ) so im gonna fix those, push that, and then it'll be ready for merge. Probably also resprite and animate the health sensor.

## Why it's Good for the Game

Good sprites means good game. Not that my sprites are good.

## Changelog

:cl:

:imageadd: Adds hydroponics scanner, camera bug, radio jammer, genetics scanner, genetics scanner recharging, desynchronizer, desynchronizer off, syndicate pinpointer, autoimplanter, and syndicate autoimplanter resprites and animations.
/:cl:

### CODE REVIEW

**Comment by tommysalami3** [comment]
well i just spent 5 hours spriting so i am going to go to bed and wake up and see if i fucked any of this up

**Comment by necromanceranne** [comment]
You're merging from master so yes.

**Comment by SmArtKar** [comment]
0 files changed, you PRed from wrong branch my friend. And yeah, Genetic and hydroponics scanners are already resprited

**Comment by tommysalami3** [comment]
I'll merge from branch and fix the stuff listed in PR when I get back in a few hours today. I'll just close this in the meantime and reopen a new PR when its fixed later today since I don't want to clutter github and I want to resprite a few other things in devices.dmi anyways.

**Pull request closed without merging**
