### PR TITLE
Corrects an inaccurate description on ling eyes

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

The old description used the term "thermal vision" and "improved light detection" which implies it was thermal like the syndie thermal goggles, or boosted eyesight in dark areas. This description has been changed to make it clearer that it's x-ray with no bonus nightvision.

## Why It's Good For The Game

Less confusion

## Changelog
:cl:
spellcheck: Changed the description on ling augmented eyes to be more accurate to their actual functionality
/:cl:

### CODE REVIEW

**Review by SpaceManiac — APPROVED** [review]

**Comment by ATH1909** [comment]
In addition to making this change, we should add a new, separate thermal vision power (that gives you thermal vision instead of night vision) and move the light sensitivity drawback and flash protection mode to that power. Note that this would mean that acquiring the x-ray+thermals wombo-combo using ling powers alone would cost 4 points (and make you weak to flashes while using your thermal vision), which I think is a fair price.

**Comment by MegaEmpirical** [comment]
... I never realized it was dycjign xray since I never took it.

**Comment by knacker48** [comment]
> dycjign
...what?

**Comment by KomradeSpectre** [comment]
> 
> 
> > dycjign
> 
> ...what?

They probably meant 'Discount' if you count the letters, they're one short, but the d and n are in the right place.

**Comment by PKPenguin321** [comment]
Isn't them being xray a bug or was that formalized

**Comment by actioninja** [comment]
> Isn't them being xray a bug or was that formalized

It's possible it's unintentional but I would prefer the description be accurate, it can always be updated later if it's changed.

**Comment by ExcessiveUseOfCobblestone** [comment]
sure

**Pull request merged**
