### PR TITLE
Allows players to pick some /basic(!!!)/ roundstart clothing items

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus, paid for by Mickyan
add: Allows players to pick some /basic/ roundstart cosmetics
/:cl:

This PR adds the ability to select the following at roundstart:
a hat
glasses
a neckwear

these are currently limited to only a few items for obvious reasons but its not hard for players to add more if they want to, besides this, items that come with a job outfit (for example, the captains hat) will take priority over these preferences. See the video for examples

https://streamable.com/yhhyb (Old vid which still has suit and pocket slots which are now removed)
```
HAT
/obj/item/clothing/head/beanie/black            "black beanie"
/obj/item/clothing/head/soft/grey            "grey cap"

EYE
/obj/item/clothing/glasses/eyepatch            "eyepatch"

NECK
/obj/item/clothing/neck/scarf/black            "black scarf"
/obj/item/clothing/neck/tie/black            "black tie"
/obj/item/clothing/ears/headphones            "headphones"


```

### CODE REVIEW

**Comment by Cyberboss** [comment]
:-1: makes vendors redundant

**Comment by ExcessiveUseOfCobblestone** [comment]
Should have made a preference for assistant jumpsuit color instead lol

**Comment by Qustinnus** [comment]
I'm personally kinda neutral on it but the only things vendors are good for right now are goofconomy and thats a bad meme anyways.

**Comment by Qustinnus** [comment]
also it does not replace job items so its not like captains can go full snowflake at roundstart, if anything most headroles can get a pocket item at best.

**Comment by optimumtact** [comment]
:-1: makes vendors redundant

**Comment by coiax** [comment]
I like the idea, but you're adding a new var for each slot, and in reality, you should just have people select a list of items, and either they would be equipped or put in the backpack or on the floor.

**Comment by Nickkoranda** [comment]
>goodconomy gets ported
>makes autodrobe too expensive to the people who actually use them
>only snowflake heads or mimes/clowns buy clothes now
>b-but this makes vendors redundant!

**Comment by Mickyan** [comment]
@Cyberboss I have specifically chosen a few very common items that are trivial to acquire, most of which exist outside of vending machines and all around the station. You have dozens and dozens of better looking items available in the vending machines. 
The implication that being able to spawn with a hat makes vendors redundant is as absurd as saying donuts spawning in the courthouse makes the chef obsolete. Saying that clothes vendors are somehow a pillar of the economy is just kind of delusional.

This is meant to give players some very basic characterization without having to raid dorms every round for it and it's no different than being able to choose which kind of backpack they want. Remember how satchels used to only spawn in dorms?

**Comment by Qustinnus** [comment]
this makes chairs non-tactical

**Comment by Qustinnus** [comment]
`	desc = "You are nearsighted without prescription glasses, but spawn with a pair."`

**Comment by PKPenguin321** [comment]
Yeah and that's fine since that trait has the downside of making you nearsighted, but just getting glasses with no downside doesn't

**Comment by Qustinnus** [comment]
i dont think glasses are like, the pinnacle of powerful items.

**Comment by Mickyan** [comment]
They're mostly there cause there's no real "normal" glasses in the code and I planned to swap them out for a version that doesn't correct nearsightedness.

I don't really think it's an issue but they can be removed if that's a concern. Same applies for other items. I never wanted this to have the slightest bearing on game balance.

**Comment by MACIEKBAKI** [comment]
if you can get a fedora as a hat that'd be fun

**Comment by zxaber** [comment]
Seems to me the point of nearsightedness is to _require_ the glasses to see correctly and thus prevent use of HUDs, mesons, and welding goggles. I don't think the glasses themselves are that important.

There is literally a whole box of prescription glasses in medical.

**Comment by anconfuzedrock** [comment]
how will I screwdriver people if everyone spawns with glasses?

**Comment by PKPenguin321** [comment]
>i dont think glasses are like, the pinnacle of powerful items.

i know, but the point is that "glasses > no glasses"
eyestab immunity, nearsighted immunity, pepper spray immunity, pocket sand immunity, for free with no downside. that's more than enough for a player who's not interested in cosmetics at all but wants to minmax to always take it

**Comment by Tlaltecuhtli** [comment]
paid code

**Comment by Grazyn** [comment]
If this is merged it means economy as a system has failed and coders have no intention to improve it any further than its currenty state.

**Comment by anconfuzedrock** [comment]
Fuck, grazyn has spoken guys what do we do his word is law

**Comment by Qustinnus** [comment]
@PKPenguin321 @anconfuzedrock 


Removed both pocket and suit slots, and prescription glasses.

**Comment by Grazyn** [comment]
@anconfuzedrock the coder literally says "goofconomy is a bad meme anyways" to show he knows it does affect economy but he doesn't care. Money right now is only good for cosmetics and crates. Crates are too expensive unless you're a head, this leaves cosmetics, and this PR gives you those for free.

**Comment by Cyberboss** [comment]
Willfully ignoring a feature that should be being deeply integrated with the game isn't winning anyone any points here

**Comment by Qustinnus** [comment]
1. I'm not all the coders, I'm literaly just one coder and dont represent a group
2. If you want goofconomy to be more interesting locking cosmetics behind it is not the way to go, it should have interesting interactions such as fun ways to gain money and cool things to spend it on (Such as by having merchants)
3. You can't really get mad at me for thinking goofconomy is a bad meme when its an unsupported feature that got dropped like it was hot by its original coder, and me allowing players to pick a hat, tie or eyepatch do not affect goofconomy at all, and if it does, that only proves my point that it is a bad meme.


how about i make a seperate PR that actually adds some interesting content for goofconomy so I can show you guys what kind of interesting stuff we need for goofconomy instead of "cosmetics should cost money"

**Comment by Mickyan** [comment]
@Cyberboss In how many ways do I have to say this is not meant to bypass the economy

Things that I wanted to have available at roundstart:
1. Things freely available in station lockers
2. Very cheap things (beanies are 10 fucking credits) that even assistants can buy at roundstart. For literally everyone else it's basically pocket change
3. Tiny pixels nobody would ever buy, even in a world where the economy is relevant and people want to  make money to buy cosmetics (this is not the world we live in). Literally the only example of this right now is the eyepatch which can be removed if that's such a big deal.

I have done PRs in the past that added to the economy and I have more things I want to add to it in the future. I do, in fact, like the economy. I don't want to bypass it. 
But to say the economy hinges on an assistant having to spend 10 credits to buy a beanie when you have hundreds of other more desirable items is ridiculous, people that are willing to go through the trouble of making money are going to buy the good stuff, not this.

**Comment by Qustinnus** [comment]
no goof mentioned he'd get 40 bucks when it got merged

**Comment by Mickyan** [comment]
that's actually a good point because thanks to the economy now assistants can buy temporary insulated gloves at roundstart

but sure, having to pay for scarves is what's truly going to kill the assistant job

**Comment by Cyberboss** [comment]
Disregarding the economy thing. I'm not in favor of giving people roundstart items unrelated to their job. Quirks are the exception to this and I don't want to add more.

**Pull request closed without merging**
