### PR TITLE
DonutStation North research maint fixes

### LINKED ISSUE #49558: Donut station blast door jail mapping issue.
In donut station you or others can get trapped in a ring of blast doors and have no escape. As a borg i happened to press the button but didn't realize there where doors that would close on the inside blocking me in. Remove the inside doors or add a button so you can escape.

https://i.imgur.com/zggpfYa.jpg
image of the mapping error.

### PR DESCRIPTION
**Pull request by dablusniper**
## About The Pull Request
This PR fixes 3 things:

- The ferry bridge in North research maint on DonutStation has been changed to fix #49558. Buttons have been added on the inside of the bridge, the airlocks have been removed to make the bridge look more consistent (blast doors are still present), and vents have been moved outside the bridge to prevent leaking air into space when the bridge is opened. sync_doors on the buttons has also been set to 0 to toggle the blast doors properly.

- Missing pipes South of the holodeck have been added to connect North research maint pipes to the rest of the station pipenet.

- An exposed, electrified grille in the middle of a maint tunnel was moved to no longer be electrified.

**Before and after photos available [here](https://imgur.com/a/zr91htn).**

## Why It's Good For The Game
It fixes oversights.

## Changelog
:cl:
fix: you can no longer get trapped inside the ferry bridge on donutstation as new buttons have been added on the inside
fix: the ferry bridge now opens and closes properly
tweak: moved vents in ferry bridge to no loner leak air into space when the bridge is open
tweak: removed airlocks from the ferry bridge to make it look better
fix: added missing pipes South of holodeck to connect North research maint to the donutstation pipenet
tweak: moved an exposed electrified grille in maint so it's no longer electrified
/:cl:

### CODE REVIEW

**Review by uomo91 — APPROVED** [review]

**Comment by uomo91** [comment]
You should update your changelog for this as suggested here.
https://github.com/tgstation/tgstation/pull/50116

**Comment by uomo91** [comment]
Also, you should be specifying which map this pertains to, in the changelog.

Tested everything in game, all working as intended.

**Comment by dablusniper** [comment]
Thanks, fixed

**Comment by kriskog** [comment]
Well, donut always wanted to be quirky so I guess this is fine.

**Pull request merged**
