### PR TITLE
Fixes a parallax runtime, prevents multiapplying parallax handlers

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

The z parallax component didn't clear away old mobs fully, so it would often have registrations for clients depsite the clients not existing anymore.

It also didn't track to the hud's mob, instead tracking the hud mob's first client

So if you switch mobs, you'd collect a bunch of different parallax handlers listening to just your mob. Messy

I've just removed it, since its role is filled nicely by my eyetracking system. Solved the runtime with a basic client check
I think I did a bad job guiding on this one, the component is a bit hairbrained. sorry maga.

## Why It's Good For The Game

less runtimes

### CODE REVIEW

**Comment by Tastyfish** [comment]
@LemonInTheDark The client check revealed another issue with eye code: eyes passed to `/datum/hud/proc/eye_z_changed()` aren't necessarily a mob despite calling `update_parallax_pref()`.

If the eye is an obj, the `(!viewmob.client)` in `update_parallax_pref()` now runtimes out and causes movement to completely fail.

For a prime example, as a mob, enter a disposals chute and you hard eject to the turf with a runtime stemming down to the forceMove() caused by that check.

I'm not sure what the exact nature of the parallax issue was, so I'm scared to just add an istype() in case the logic needs to be more complex than that.

**Comment by LemonInTheDark** [comment]
gggggggg

**Comment by LemonInTheDark** [comment]
I bet you could have solved it fine.
image
the trouble was this line. but if we don't pass in a mob, the following code will just assume we're talking about ourselves.
image
this may or may not be complete but this should do

**Comment by LemonInTheDark** [comment]
#71072

**Comment by Tastyfish** [comment]
> I bet you could have solved it fine.
> image
> the trouble was this line. but if we don't pass in a mob, the following code will just assume we're talking about ourselves.
> image
> this should do

For some bizarre reason I didn't see that it defaulted to mymob. I'll blame the two-hour meeting I was in earlier today.

**Pull request merged**
