### PR TITLE
New roundend sound from orange

### PR DESCRIPTION
**Pull request by TheBoondock**
## About The Pull Request
This pr adds the wyci from our very own beloved headcoder @optimumtact 

## Why It's Good For The Game
I am sadden to see that we have a roundend clip from mothblock but not the best headcoder orange so here it is

## Changelog

:cl:
soundadd: added a new roundend wyci clip
/:cl:

### CODE REVIEW

**Comment by TheBoondock** [comment]
dont know why the integration test for icebox failed when i didnt touch maps but whatever

**Comment by Jolly-66** [comment]
> dont know why the integration test for icebox failed when i didnt touch maps but whatever

Blame mappers

**Comment by Iamgoofball** [comment]
@Mothblocks yes but it adds it to our repo standard files

**Comment by tralezab** [comment]
Eh, I don't really think it fits well enough to stand as an example

**Pull request closed without merging**
