### PR TITLE
Removes venus map traps

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
yes I'm salty I got chainstunned through a wall for ~10 minutes along with 5 other people and told it was a feature via ahelps

> fix it don't remove it!

If someone wants to fix them so they don't just AoE stun people with no way to save them then go for it, they're completely broken and unplayable right now.

### CODE REVIEW

**Comment by coiax** [comment]
Kor was denied greentext via a feature. Better remove it.

**Comment by lzimann** [comment]
yea it is ridiculous, i got stunned and i was 10 tiles away from it, oh, and it grabbed me through the wall/windows

**Comment by Cheridan** [comment]
Reminder that while "i ded" is a funny meme, dying to something that's bullshit doesn't magically make it not bullshit.

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/tgstation/issues/13757

This was reported 6 months ago, nobody has fixed it. If someone cares enough they can fix it and they can spawn again.

**Comment by HattersGonnaHat** [comment]
Venus human traps have unlimited vines. The vines go through walls. They completely entangle and stun you, and drag you towards the venus trap. They can do this outside of your field of view, essentially a mobile heat-seeking artillery that goes through walls. The venus trap is capable of significant movement, even outside the range of kudzu. They do loads of brute damage a hit. This costs nothing but some time, knowledge, and a bit of chemistry resources. It's total BS. At the absolute minimum it should be made separate from kudzu so you don't have to deal with loads of venus traps coupled with max potency space vines, which is basically a death sentence for anyone that isn't immune to grapple/stun/knockdown.

**Pull request closed without merging**
