### PR TITLE
[s] Prevent filesystem access

### PR DESCRIPTION
**Pull request by Cyberboss**
How hard is it really?

### CODE REVIEW

**Comment by alexkar598** [comment]
Remember when i made a message about it on coderbus with a fix over a month ago and that bee ported.

**Comment by boodaliboo** [comment]
> Remember when i made a message about it on coderbus with a fix over a month ago and that bee ported.

lol

**Comment by TheVekter** [comment]
Fuck up of the year 2020

**Comment by Cyberboss** [comment]
Granted, this proc has existed literally forever

**Pull request merged**
