### PR TITLE
New Mining Cyborgs!

### PR DESCRIPTION
**Pull request by GunHog**
:cl: Gun Hog
rscadd: Nanotrasen has completely redesigned the mining cyborg to be more compact and lighter, based on experimental drone designs.
rscadd: Additional prototype designs have been released for mining cyborgs to fit them with thrusters. Please complete this research for Nanotrasen!
rscadd: New module hardpoints have been provided for potential night-vision meson sensors and lifeform analyzers.
/:cl:

Sprites by @WJohn!
- Code for custom borg panels as the new sprites are too small to support the current ones.
- Removed mining cyborg transformation animation pending a new sprite for it.
- Upgraded cyborg floats, bypassing lava and tables (chasms to come later). They have magpulse so that they are not blown around by space wind. The Ion Thruster upgrade is still required for space movement.
- Mining borg thermals are the same cost as the thermals implants for humans, as a separate item.
- Mining borg NV mesons replace the previous meson item, with the same reqs as the human one.

Mining Cyborgs, even when upgraded, gain no defensive abilities, meaning they are intended as glass cannons, emphasizing hit-and-run tactics.

The upgraded cyborg sprite is animated in both idle and moving states, but my recording software is too low quality to properly capture it.
- Note: The upgraded cyborg is meant to support chasms as well, but that will be in a later PR as it requires code outside the scope of this PR.

**Left: Upgraded, floating borgs. Right: Default, treaded borgs.**
screenshot 2016-07-02 22 22 59

### CODE REVIEW

**Comment by RemieRichards** [comment]
Don't like the sprites :-1:

**Comment by Niknakflak** [comment]
so hard to even see the sprites in that picture

**Comment by kevinz000** [comment]
I think we need additional pylons?

**Comment by InsaneHyena** [comment]
They look like protoss sentries, far more fitting Ratvar than NanoTrasen.

**Comment by Armhulen** [comment]
>they fly
> can't fly through space

**Comment by coiax** [comment]
Planes and birds can fly, but I wouldn't expect them to be able to fly perfectly through space.

I'd like to see more of the sprites before we make a judgement on them. I do really like the sort of dark green/black sprite we have for mining borg currently, would be sad to lose that.

**Comment by xxalpha** [comment]
I prefer the current miner sprite.

**Comment by ChangelingRain** [comment]
I really don't like these, they're tiny and don't look like a station thing, they're more like dangerous robot mobs.

**Comment by GunHog** [comment]
Comments on the sprites will be forwarded to @WJohn. Yes, they are modeled after Protoss Drones!

>they fly
can't fly through space

That is a balance reason. It would make the Ion Thrusters item obsolete for mining cyborgs.

**Comment by Aloraydrel** [comment]
ss13 rts soon

**Comment by Cebasiz** [comment]
they're really small..

i don't know, it seems like a mining borg should be more robust looking. 

can you make them bigger or something?

**Comment by WJohn** [comment]
That would require another complete resprite which I'm really not keen on doing right now. Although the kotor mining droids do look pretty cool. Perhaps I'll make it look like those at a later date.

**Comment by GunHog** [comment]
What do you want me to do about these ones now, WJ?

**Comment by KorPhaeron** [comment]
This doesnt seem very popular

**Comment by GunHog** [comment]
Only the sprite set is unpopular, no one seems to care about any of the other changes at all, according to this feedback. If you can whip up a flying version of the current mining borg, @WJohn, I think we can satisfy the people who are against it, Kor.

**Comment by Zilenan91** [comment]
I don't mind them. They look like probes from Starcraft, though yeah they are a bit out of place if not nearly as drastically out of place as peacekeepers already are.

**Comment by xxalpha** [comment]
For once I agree with Zilenan, make them look like those mining droids.

These starcraft sprites don't really fit the NT cyborg look.

**Comment by GunHog** [comment]
Was hoping for some temp sprite for the upgrade item until then.

**Comment by WJohn** [comment]
Alright then I'll probably resprite em into kotor mining drones. Though I'll have to figure out a way to make them look good when turned into flying versions, since they're basically spider-shaped bots.

**Comment by KorPhaeron** [comment]
Reopen it when it's ready then, not 100% sold on ignoring all terrain for free anyway

**Comment by GunHog** [comment]
I cannot open it again if you close it, Kor...

**Comment by Zilenan91** [comment]
Could probably do a little jump jet thing on the bottom of the robot spider legs to make them fly?

**Comment by KorPhaeron** [comment]
well not free, but I think having to toggle boost mode or something to manage battery might be better. Either way just bug me to reopen when new sprites exist

**Pull request closed without merging**
