### PR TITLE
Expands service channel access to HoP-reporting jobs.

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request

Gave service headsets to Curator, Chaplain, Clown, and Mime
Gave lawyers a Law and Order serv/sec hybrid headset and encryptionkey, with custom sprites.

## Why It's Good For The Game

> Service Radio Headset: Headset used by the service staff, tasked with keeping the station full, happy and clean.

- Service goes beyond cleaning and feeding. Social services are provided by the Chaplain, Curator, Lawyer,  Clown, and Mime. They cover the "Happy" of "Full, Happy, and Clean". People request shuttle calls out of boredom, and this is more or less the fault of the HoP and Service department for failing to provide entertainment.

- Every other department can have all members communicate on their departmental channel, and by extension to the head of the department that they work in.

- Solidarity within the department. Service doesn't even have it's own banner. The theater and the dressing room are a part of the bar and are therefore somewhat important when it comes to securing the space. This would contribute to the development of flavor and culture for the department.

- Like literally, if I was running a bar or responsible for running a bar, I would want to be able to get in touch with the entertainment. Even if they are clowns.

- Some of these roles don't have much to do outside of social RP, so improving ease of communication between them could produce situations such as a fully staffed cafe with waiters (we have waiter costumes in the ChefDrobe and Autodrobe in the dressing room), or remodeling construction spaces with Curator access. 

- Might improve Clown and Janitor relations but after they stop messing with each other they may team up to create a slipocalypse...

- For real though I know that Clown and Mime can be really irresponsible roles but adding them to an actual department channel might inspire respect and camaraderie. Let's make service great together!

## Changelog
:cl:
add: Chaplain spawns with service headset
add: Curator spawns with service headset
add: Clown spawns with service headset
add: Mime spawns with service headset
add: Lawyer spawns with new "Law and Order" headset
add: New service/security hybrid "Law and Order" encryption key
del: Removed Lawyer spawning with security headset
balance: All service jobs that report to the HoP can now communicate with one another on the service channel.
/:cl:

Many Thanks to @AnturK for walking me through the PR process on git bash!!

### CODE REVIEW

**Comment by knacker48** [comment]
Great, now the mime can talk on... oh wait

**Comment by RaveRadbury** [comment]
At least they can hear what's happening.

**Comment by habader** [comment]
Oh Servicia...

**Comment by FloranOtten** [comment]
the Serviet Union

**Comment by Barhandar** [comment]
Ooooh nooooo, that one channel that nobody ever used because all jobs that had it are in direct vicinity to each other and never have to leave their department is now actually usable!

**Comment by HomocidlePancakes** [comment]
Noone will use it because it has a fugly color.

**Comment by Fikou** [comment]
give servicelathe access to those jobs too

**Comment by RaveRadbury** [comment]
@Fikou, you're giving away the secret next step, but I guess I could go through with that now~!

**Pull request merged**
