### PR TITLE
Runtime is now on Runtime Station

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

Runtime is now on runtime station in the medical area.
image

## Why It's Good For The Game
1. Cat
2. Having a simplemob already on the testing station for testing purposes is probably good(?)
3. ???
4. Profit

## Changelog

:cl:
qol: A simplemob is now on available on the runtime station for testing purposes.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
can you buckle it to a bed or something, these things move around and get in the way

**Comment by Son-of-Space** [comment]
Fikou drinking haterade
image

Not sure if I can buckle it to a bed, let me tinker with it a bit.

**Comment by Son-of-Space** [comment]
I don't think I can buckle them to the bed because I think buckling requires signals but I can throw them in the corner with their bed so there is an option to buckle. Updated main picture.

**Comment by tralezab** [comment]
I'm really tied here because I don't want a simplemob to be on that map but also I don't want there to not be runtime on this map... I really don't like it though.

**Comment by optimumtact** [comment]
this is a developer testing map

**Comment by Ryll-Ryll** [comment]
This allows for testing simple mobs loading, I'm willing to give this another shot if another maint is also for it

**Comment by Fikou** [comment]
> This allows for testing simple mobs loading, I'm willing to give this another shot if another maint is also for it

we have unit tests for that

and we already have a simplemob on runtime, the circuit drone

**Comment by Son-of-Space** [comment]
I think developers deserve a companion while they test.
Also circuit drones are lame.

**Pull request closed without merging**
