### PR TITLE
Adds x-ray turrets to syndicate infiltrator

### PR DESCRIPTION
**Pull request by Buggy123**
Alternative to #36254

closes #36254

:cl: 
tweak: Take caution, the Syndicate have recently upgraded the perimeter defense turrets on their infiltrator stealth ships!
/:cl:

### CODE REVIEW

**Comment by Buggy123** [comment]
This was suggested by @WJohn

**Comment by Qustinnus** [comment]
There's bug fixes in there. No reason to close the PR if this gets merged, it would mean he'd have to make changes at best.

**Comment by kevinz000** [comment]
image

**Comment by Buggy123** [comment]
Why was this closed?

**Comment by Poojawa** [comment]
Buggy's meme PRs are less funny than Goof's. and that's terrible.

**Comment by Buggy123** [comment]
b-but this isn't a meme pr

**Comment by Poojawa** [comment]
a more *sensible* alteration is to buff the turret range to 12, rather than the 9 they're at now. just enough to start plinking at people.

a faster refire rate and maybe more integrity to make up for the slow as fuck bullet speed.

**Pull request closed without merging**
