### PR TITLE
Doubles the amount of hide needed to make ash drake armor.

### PR DESCRIPTION
**Pull request by Repukan**
:cl: Versus
balance: Doubled the amount of hide needed to make ash drake armor.
/:cl:

Ash drake armor is a huge bonus for those that manage to kill a drake early or later on. However, it is hidden behind the easiest megafauna beast to kill, and it makes two miners nigh unkillable and invulnerable to the one of the biggest environmental dangers in lavaland.

By doubling the amount of hide needed to craft a set of armor, the value of it will increase due to scarcity, and this will also lower the amount of heavily armored miners and only reward the hunter.

### CODE REVIEW

**Comment by Armhulen** [comment]
yeah, i like this a lot.

**Comment by Arianya** [comment]
Disencourages co-operation on killing the drake, and nerfs one of the least offensive lavaland loots that you can pick up and use as a non-antag without getting bwoinked.

Not to mention that megafauna are one of those things which seem really easy from the inside, but from the outside most players can't kill it in a pair of two, let alone... well, alone.

**Comment by Repukan** [comment]
>Disencourages co-operation on killing the drake
This is absolutely ridiculous. In my entire play time in the server, and from personal first-hand observation and second hand accounts, it was known that fighting megafauna alone is better because it allows an easier pacing of attacks. Even without that, people often fight it alone since most are afraid of having their round ended prematurely with no chance of being revived easily.

>nerfs one of the least offensive lavaland loots that you can pick up and use as a non-antag without getting bwoinked.

One of the strongest armor sets in the game, which being able to produce two for the price of one was one of the most glaring examples of powercreep in the department.

>Not to mention that megafauna are one of those things which seem really easy from the inside, but from the outside most players can't kill it in a pair of two, let alone... well, alone.

http://www.byond.com/games/TgstationHub/TgstationStatsHub#tab=scores
Of all megafauna, the drake is the one that is consistently killed more often, and in a much bigger quantity. From both the inside and outside, most players can kill it both together and alone.

**Comment by Doppeltongue** [comment]
Aren't there multiple ash drakes on lavaland, while legion, bubblegum, and hierophant are all limited to one? Also, colossus gives pretty bad drops, so nobody really goes for it. If you think about it, ash drakes are the only megafauna that give decent loot, while the other 4 often either give horribly situational loot or stuff that is useless unless you're an antag. Most of the time they're killed just for the sake of killing them.

**Comment by Repukan** [comment]
>Aren't there multiple ash drakes on lavaland, while legion, bubblegum, and hierophant are all limited to one? Also, colossus gives pretty bad drops, so nobody really goes for it.

Their drops (aside from BG) are more situational and niche rather than pure enhancements. Hierophant allows for quick teleportation and escape to a safe area if you put the beacon down somewhere cozy. Colossus allows you to quickly disarm a mob or widespread heal a group post-implant, with the crystal being useful for breaking down environmental defenses or providing healers in some cases.

>If you think about it, ash drakes are the only megafauna that give decent loot, while the other 4 often either give horribly situational loot or stuff that is useless unless you're an antag.

While megafauna being hard to beat is the reasoning for powerful loot to be hid behind their death, it should also be situation to not be a pure enhancement. This is because pure enhancements are the worst kind of powercreep, hard to balance when measured against other metrics. Drake gives too many good drops, and with more than one being able to spawn per round, this means that more people can disrupt a round flow by being almost invincible to most forms of damage. Although making better, creative drops to the other megafauna is a more thorough solution, increasing the scarcity and availability of one of the best armors in the game doesn't hurt the miners hunting for the drakes, it only hurts those hunting for their scraps.

All in all being able to receive two suits of fireproofing, high brute high burn damage resisting armor is too much in my opinion, and has been for my entire length of play-time.

**Comment by uraniummeltdown** [comment]
The vast majority of players already find fighting megafauna extremely hard
The armor is already valuable as it is, and anyway you can still stun and cuff anyone wearing it to kill them. They're not unkillable, the armor is a harmless reward

**Comment by Repukan** [comment]
Jokes on you bitch I can't play.

And the stats, which is hard numbers, prove your statement false. Drake is the easiest megafauna to kill and them gibbing is not an excuse to powercreep their drops. They are personal challenges that should carry an appropriate reward. Which one armor vest for the killer should be.

**Comment by BeeSting12** [comment]
I agree with this change. Drakes are so easy that I can kill one and I play mining almost never- got it on my 2nd try.

**Comment by Ergovisavi** [comment]
Here's the thing. Yes, if you examine the ash drake and its loot in a vacuum, the rewards are overpowered for the effort. I say that both as a designer and a player.

However, keep this in mind. The ash drake is (prior to the introduction of the blood drunk miner), babby's first megafauna. Making the rewards more valuable than they should be incentives miners to go and start trying and failing to kill them. And they do. And they fail. A lot. People get killed by ash drakes plenty. Just because myself, repukan, and others can probably kill them blindfolded does not mean that people should be held to that same standard all the time. That leads to a very bad place.

What does the ash drake armor really do? Gives you melee resistance, but you already had that with the standard explorer suit, and you can upgrade it with goliath plates. No, the real benefit is that you are now fireproof. That's the only massive upgrade over just the explorer suit. It doesn't protect from lava, and NOTHING on lava land lights you on fire except from, you know, lava. Which the default explorer suit already protects you for a damn long duration on anyway.

How often do people get killed by ash storms? I mean, really. You're given a pod that will save your life in seconds. You can then pick up an extra 3(4?) via the mining lockers because they come inside of them. Hell, you can get FIVE for yourself if you pick up one of the voucher bundles.

The reality is that the ash drake armor is nothing more than a nice convenient bonus and is completely useless in actual combat due to lolstuns, and that this change is, in my opinion, misguided. If the armor actually did anything but act as a glorified firesuit, I'd be more convinced it's out of line.

>this means that more people can disrupt a round flow by being almost invincible to most forms of damage

armor = list(melee = 70, bullet = 30, laser = 50, energy = 40, bomb = 70, bio = 60, rad = 50, fire = 100, acid = 100)

Strip out the laser, bullet, and energy protections. Problem solved. There is absolutely nothing wrong with incentivizing miners to help each other take down a megafauna instead of the frankly awkward and clumsy "whoever can click on something" shit.

**Comment by Repukan** [comment]
>However, keep this in mind. The ash drake is (prior to the introduction of the blood drunk miner), babby's first megafauna. Making the rewards more valuable than they should be incentives miners to go and start trying and failing to kill them. And they do. And they fail. A lot. People get killed by ash drakes plenty. Just because myself, repukan, and others can probably kill them blindfolded does not mean that people should be held to that same standard all the time. That leads to a very bad place.

Except I'm not holding people to yours, mine, or Durkel's level of play. It's why I checked with normal players (in the months I was playing) and checked the medal stats to measure how difficult the drake is. In fact due to the slowness of its attacks and patterns, I'd argue it is a lot less relentless and difficult than the BD Miner.

>What does the ash drake armor really do? Gives you melee resistance, but you already had that with the standard explorer suit, and you can upgrade it with goliath plates. No, the real benefit is that you are now fireproof. That's the only massive upgrade over just the explorer suit. It doesn't protect from lava, and NOTHING on lava land lights you on fire except from, you know, lava. Which the default explorer suit already protects you for a damn long duration on anyway. You can make an argument that ash drakes light you on fire but I mean you just killed an ash drake without the armor, why do you need the armor?

Drake can be killed roundstart for a plethora of armor values without having to hunt other three monsters for exclusively more brute resistance. The real benefit is that you are fireproof, you can survive plasma fires, you can use fire as a weapon reliably (BIG plus due to clothing damage.) Ignoring its uses and effects on station is nonsensical, sorry. 

>How often do people get killed by ash storms? I mean, really. You're given a pod that will save your life in seconds. You can then pick up an extra 3(4?) via the mining lockers because they come inside of them. Hell, you can get FIVE for yourself if you pick up one of the voucher bundles.

>Just because myself, repukan, and others can probably...does not mean that people should be held to that same standard all the time.

??

>The reality is that the ash drake armor is nothing more than a nice convenient bonus and is completely useless in actual combat due to lolstuns, and that this change is, in my opinion, misguided. If the armor actually did anything but act as a glorified firesuit, I'd be more convinced it's out of line.

It's actually extremely good at combat because it allows you to use a debuff and just run and light people with few ways for them to counteract both clothing damage and high temperature slowdown. Running itself being a counter to the stun meta, with its hard counter being anti-stun chems.

**Comment by KorPhaeron** [comment]
Design Lead Ergosavi said No

**Comment by Repukan** [comment]
Shame.

**Comment by Ergovisavi** [comment]
I'm still of the opinion that yes, a change to the effectiveness of on station weaponry against the drake armor is a strong and reasonable argument, I just don't think preventing one of the few "coop" moments on mining is a good solution to said issue.

**Comment by Repukan** [comment]
What coop, what a fucking meme.

We both know nobody hunts megafauna together unless they bring a minebot.

**Comment by Bawhoppen** [comment]
Speak for yourself

**Comment by Repukan** [comment]
Sure, the 1% of cases that probably happen.

I've played mining since before the other two megafauna were added and even then, as I followed it's development as an observer, I could see that everyone save two outliers every once in a blue moon hunted together. The extra suit ends up being a hand me down for the other miner that's still alive after the first storm.

**Pull request closed without merging**
