### PR TITLE
Adds handholding

### PR DESCRIPTION
**Pull request by nervere**
## About The Pull Request

This pull request adds the ability to "hold hands" with another player by targeting the left or right arm and pulling them.

## Why It's Good For The Game

It's a small addition that adds more flavor to player-on-player interactions.

## Changelog
:cl: Nervere & kevinz000
add: You can now hold hands with another player by targeting their left or right arm and pulling them.
/:cl:

### CODE REVIEW

**Comment by plapatin** [comment]
YAMERO

**Comment by Shadowflame909** [comment]
first gamer becomes a catgirl


then he adds hand-holding


Reddit isnt going to like this

**Comment by danzargar** [comment]
i come on TG in the first time in weeks and i see this shit pop up while i am beating up nerds with boxing gloves BEGONE THOT

**Comment by subject217** [comment]
go back to hippie danzargar

**Comment by wesoda25** [comment]
GOD I want to hold hands with scurra bardus

**Comment by Wilchenx** [comment]
image

**Comment by Qustinnus** [comment]
nervere was a cool clown main back on ftl13

now he is a degenerate catgirl on tg


really makes you think

**Comment by zxaber** [comment]
Man, I'm gonna forget to change my targeting thing after augmenting someone's arm and then grab someone later and send all the wrong signals.

**Comment by nervere** [comment]
> nervere was a cool clown main back on ftl13
> 
> now he is a degenerate catgirl on tg
> 
> really makes you think

I don't play a felinid, and those details aren't relevant to this PR anyways.

**Comment by SpinnerMaster** [comment]
fucking LEWD

**Comment by bobbahbrown** [comment]
closed

**Comment by imsxz** [comment]
speedmerge this please

>3 people credited in the changelog for a 1 line edit

**Comment by Jordie0608** [comment]
nervere

**Comment by subject217** [comment]
lol

**Comment by DinkleNH** [comment]
gay

**Comment by granpawalton** [comment]
REEEEEEEEEEEEEEEEEEEEEE

**Comment by Twaticus** [comment]
based

**Comment by Magikarpet** [comment]
we did it reddit

**Comment by Nickkoranda** [comment]
based

**Comment by HideAndSeekLOGIC** [comment]
Fetish content BEGONE

**Comment by Jordie0608** [comment]
extra betrayal

**Comment by zxaber** [comment]
Next step is hand-holding creep objective, then?

**Comment by Jujumatic** [comment]
i thought you guys always knew that something has always been wrong in oranges' head

**Comment by waterwater1212** [comment]
the joke is on you filthy catgirls. orange man strikes again

**Comment by Gylifi** [comment]
The absolute state of headmins.

**Comment by MrDoomBringer** [comment]
image
he's attoned for his sins

**Comment by Jordie0608** [comment]
double_betrayal

**Comment by Gousaid67** [comment]
all dem spicy memes.

**Comment by DinkleNH** [comment]
God has left the server
-------- Original message --------From: Erik <notifications@github.com> Date: 2/1/19  1:06 AM  (GMT-08:00) To: tgstation/tgstation <tgstation@noreply.github.com> Cc: DinkleNH <Nickham101@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [tgstation/tgstation] Adds handholding (#42596) 
all dem spicy memes.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tgstation/tgstation","title":"tgstation/tgstation","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/tgstation/tgstation"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Gousaid67 in #42596: all dem spicy memes."}],"action":{"name":"View Pull Request","url":"https://github.com/tgstation/tgstation/pull/42596#issuecomment-459654604"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tgstation/tgstation/pull/42596#issuecomment-459654604",
"url": "https://github.com/tgstation/tgstation/pull/42596#issuecomment-459654604",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by subject217** [comment]
hello??? are you okay???

**Comment by DinkleNH** [comment]
No

**Comment by FantasticFwoosh** [comment]
> 
> 
> Next step is hand-holding creep objective, then?

Good point, Hand Holding is the weapon of choice for unwanted encounters.

**Pull request merged**
