### PR TITLE
Revert "wzhzhzh": speedmerge

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#53366
I love the wzhwzh but 24 hour rule >:(

### CODE REVIEW

**Comment by Jack7D1** [comment]
Doesn't fix the crappy break statement. Neither goof nor shaps wants to fix it.

**Comment by Iamgoofball** [comment]
Stylemistake says that 4 approvals bypass the 24 hour requirement, I believe him.

**Comment by Jack7D1** [comment]
I won't use my psychic powers to make you self close next time if you fix the break statement

**Comment by Jared-Fogle** [comment]
tk is so bugged out it works on github too

**Comment by wesoda25** [comment]
You’re lame

**Pull request closed without merging**
