### PR TITLE
Emitters announce when they've lost power

### PR DESCRIPTION
**Pull request by BroseidonMOO**
:cl: grimreaperx15
add: Emitters will alert the Engineering radio channel when they lose power, but not if turned off normally.
/:cl:

[]: # Hopefully this will provide a bit of warning that containment is about to fail if the engine is wired wrong or anything like that, and prevent the engine from being released due to pure incompetence. It only applies if the emitter loses power, and not if it is turned off, so a traitor can still emag and disable the emitters manually to avoid triggering any form of alert.

### CODE REVIEW

**Comment by ma44** [comment]
Git Gud and check on the engine

**Comment by MrStonedOne** [comment]
I don't think you understand how spammy this will be

**Comment by Cyberboss** [comment]
Hugbox.pr :-1:

**Comment by MrStonedOne** [comment]
All powernet rebuilds (mouse eating a wire) would trigger this.

The amount of false positives are high enough that i actually suggest we allow this (under the caveat that the "bug" is documented as a feature).. it wouldn't be useful

**Comment by PKPenguin321** [comment]
You know how poly has that line, "check the engine you chucklefucks"

That used to not just be a meme

**Comment by Kromgar** [comment]
Seriously its been so fucking many rounds of 5 minutes in ITS LOOSE


It's also way too easy to release it. Just snip 2 wires and *BOOM* or *SLURP*


I say the best solution is making them grow and move way more slowly until like 20 minutes in

**Comment by MrStonedOne** [comment]
aww... but now it won't have any false positives.

Like I'd actually be ok with this if it had the false positives

**Comment by Repukan** [comment]
Kromgar that's my idea tm

Pay me bitcoins for the right to suggest it or you're breaking the NAP

**Comment by ShizCalev** [comment]
@Kromgar 
Open 3 valves and the station is being filled with plasma.
Open 2 valves and change one filter and the station's o2/air storage tanks are forever filled with plasma.

Just curious, if an emitter is blown up, would it trigger the squak?

Also if people are constantly releasing it because they have no clue what they are doing when setting up one of the most dangerous and critical assets to the station, there is always the jobban button. We have a wiki with a step by step guide, a video based guide, and two ingame books that details exactly what you need to do step by step to not ruin the round for everybody.

**Comment by Kromgar** [comment]
@ShizCalev 

Plasma floods can be fixed. Can't put a singulo or tesla back in containment.

**Comment by BroseidonMOO** [comment]
If the emitter is destroyed, no, it's done in the process proc, so it shouldn't trigger if the emitter is straight up deleted for some reason. Second, I'm not an admin and the ban logs aren't public, so I don't know if people are getting jobbanned and new people just keep fucking up, or if they're not and its the same people or what, I just know that I see it get loose a lot without antag intervention.

**Comment by ShadowDeath6** [comment]
make it so poly has omniscense and sometimes correctly announces when the engine starts failing with the chucklefucks line

**Comment by ExcessiveUseOfCobblestone** [comment]
> plasma floods can be fixed

yeah if the person who did the plasma flood doesn't know atmos or is an AI.

**Comment by Haevacht** [comment]
This is dumb. You are supposed to check on the engine as poly and people have said, and turning off the emitters is lazy, noticeable sabotage.

Play engi if you are having this much trouble with it.

**Comment by Tofa01** [comment]
The super matter shard announces over the station wide radio when it is de-stabilised so i don't see how this is much different, though in my opinion when someone sabotages the super matter shard the effects are not recognised or announced straight away as the damage can sometimes take some time to occur allowing for the saboteur to get away without being insta-busted. Personally i would be ok with this if it had a five or so second delay to allow for less false positives and to not make it virtually impossible to release the engine.

**Comment by jughu** [comment]
Good luck checking the singulo when the 2 wires are cut emitters powered down good luck powering the emitters up without being pulled into tge containtment

**Comment by SgtxRootbeer** [comment]
@jughu we have magboots to prevent stuff like that from happening.
maybe we should make this a poly device.
ex, polly will yell in caps (so we know its a real alert)
"oh god its loose"
or
"check the singulo you chucklefucks"
whenever the containment starts to fail.

**Comment by Chnkr** [comment]
HUGBOX

**Comment by jughu** [comment]
I thought singulo pulled you in despite of having magboots

**Comment by xxalpha** [comment]
Hugbox plus the spamming potential. :-1:

**Comment by PKPenguin321** [comment]
>I thought singulo pulled you in despite of having magboots

Was changed a while back now it makes you singulo pull proof

**Comment by alexkar598** [comment]
And what would you do with people who build emitters outside of engineering

**Comment by CPTANT** [comment]
You can scream hugbox, but the bottom of the line is that it is impossible to stop someone from releasing the engine. Having the most destructive traitor action on the station also being one of the easiest is just boring design. There is no scheming or preparation, you just snip the wires and the sing is loose.

Again.......

At least it takes effort to perform a decent plasma flood.

**Comment by MrStonedOne** [comment]
>And what would you do with people who build emitters outside of engineering

**Comment by BroseidonMOO** [comment]
I'd like to clarify a few things, namely this only happens if the emitter loses power due to being disconnected from the powergrid for several seconds, hopefully long enough to avoid any issues with the grid being rebuilt. If the emitter is turned off by hand, there is no alert. It just turns off normally. I'm not entirely sure what you mean by what I would do with people who build emitters outside of engineering. If an antaqg wants to use this to fuck with the Engineers, more power to them?

**Comment by kevinz000** [comment]
Why are you making a hugboxy change get engis to do their jobs.

**Comment by BroseidonMOO** [comment]
If any other department doesn't do their job, there are no real downsides beyond not getting whatever resource they'd produce. Botany doesn't grow plants? Not really an issue. Science doesn't do R&D or build borgs? Inconvenient at best. And so forth. If Engineering doesn't do their job, the entire station turns off. If they fuck it up, the entire station is entirely destroyed with no possibility of repair.

**Comment by bgobandit** [comment]
more importantly, emitters lose power randomly. the admins deal with this kind of spam, trust me, you don't want it

**Comment by BroseidonMOO** [comment]
bgobandit, as I said earlier, this shouldn't suffer from that issue, and it'll stop spamming the admins as well. The powergrid has to be not providing any power for 4 consecutive processing ticks before it'll tell the admins, or make a message over the radio.

**Comment by Kraseo** [comment]
solars are the smart man's choice of power

**Comment by Xhuis** [comment]
H U G B O X
U
G
B
O
X

**Review by MrsTonedOne — APPROVED** [review]
After having given this a lot of thought, I'm ok with it.

You can still get past this by blocking the emitter path, turning the emitter off manually, or disabling the engineering channel in tcoms.

**Comment by Magikarpet** [comment]
I don't get how it's hugbox to actually force people to put effort into using the biggest round-ender in the game short of an admin force-restarting the round, work for your chaos and revel in it rather than snip 2 wires to instantly waste 30 minutes of everyone's time because ;ENGINE LOOSE 10 minutes in

I get engineering needing to do their jobs but most people couldn't be bothered to even set up the PA let alone maintain the engine. As commonly said, power is binary and short of gloating purposes there is no reason to bother with it. Addressing all of the issues with engineering would be a huge pr that would either have to encourage experienced engineers to play the biggest chore role in the game or change the engine to something that isn't an instant GG like the sing/tesla

that or just run off with the PA computer and destroy it permanently and force the engineers to set up solars unless they bitch to cargo long enough for a PA computer

**Comment by KorPhaeron** [comment]
I have a crazier idea and will revisit it if mine doesn't pan out, stay tuned

**Comment by optimumtact** [comment]
This shit is gonna blow your mind I promise

**Comment by Xhuis** [comment]
absolute fucking madman

**Pull request closed without merging**
