### PR TITLE
Removes Shamebrero Penguin

### PR DESCRIPTION
**Pull request by ghost**
like, five seconds in var editing for the same thing, made specifically for one admin to have fun with and it seems really dumb.

closes #31623

### CODE REVIEW

**Comment by Armhulen** [comment]
i'll get the icon out soon too

**Comment by Armhulen** [comment]
"haha i take the sprite of sombero and i take the sprite of penguin and 5 seconds of icon editing and wow!! i have admin secret joke!!!!"

when will they learn?

**Comment by Militaires** [comment]
alphonzo asked for it

**Comment by Militaires** [comment]
im innocent

**Comment by MrAlphonzo** [comment]
You are a sick, sick man.

**Comment by kevinz000** [comment]
sigh people who don't know how to admin abuse smh

**Comment by Armhulen** [comment]
@Militaires this bone i pick is not with you

@MrAlphonzo i drink your milkshake, I DRINK IT UP.

**Comment by Cyberboss** [comment]
mmm, no.

**Pull request closed without merging**
