### PR TITLE
Rebalances nuisance cell lines for Cyto

### PR DESCRIPTION
**Pull request by EuSouAFazer**
## About The Pull Request

Makes the cockroach and blob spore cell lines easier to suppress in Cytology.
Making fun stuff with Cytology already is very hard with how you have to build your own setup in most maps and somehow get all the reagents you need. 

## Why It's Good For The Game

All of the fun recipes with Cytology require at least 1 of Organic Slurry or Growth Serum. Sometimes both. And roaches are hard to suppress and thrive on that. That means that if your cell line includes roaches you are forced to throw it out. This change makes roaches at least able to be dealt with by making them not grow as much from these fun reagents and having a easier to find reagent to suppress them (salt).

Blob spores were already on a relatively balanced state where in some petri dishes you could ignore them and in others you couldn't. I wanted to preserve that fun aspect of figuring out if you should or not care about blob spores based on what you see so I didn't touch its supplementary reagents. However suppresing them was really hard so if you did decide that you have to deal with them in the dish you had to throw the entire petri dish away. This PR adds a way to deal with them; it's not the easiest to get but it can be obtained with the chemist's help or (more interestingly) the Psychologist's help since they spawn with psicodine pills (iirc), making for a very nice interdepartmental cooperation and giving a lil love to the Psychologist.

## Changelog

:cl:
balance: Nuisance cell lines are easier to deal with in Cytology;
Cockroaches:
Salt  N/A -> -2

Growth Serum +2 -> +1
Organic Slurry +4 -> +2

Immature blob spore:
Psicodine: N/A -> -2

/:cl:

### CODE REVIEW

**Comment by EuSouAFazer** [comment]
Mantainers DON'T MERGE THIS, I'm currently reading the cytology code in-depth and holy shit

**Comment by EuSouAFazer** [comment]
Alright, it can be PR'd. I found some code that wasn't documented on the wiki about spaceacillin helping with Cytology; it's helpful but doesn't help make these nuisance cell lines still too much of a hassle (+ now you'd have to go get spaceacillin to do Cytology, another thing in the large conga line of to-do stuff) so I think the nerf is still warrented.

**Comment by GPeckman** [comment]
Its worth noting that sometimes people _want_ to grow cockroaches. There's an experiment for scanning a roach grown with cytology and roaches can be used with the DNA infuser in genetics.

**Comment by EuSouAFazer** [comment]
RE people wanting to grow roaches, this would make it more interesting to do so, as with these nerfs it makes it a slight challenge to do so. It helps round out the cytology pool; the common consensus on roaches is that if your petri has roaches you're either making roaches or gonna have to throw away the petri dish. With this you can still work around the roach cells; it's an actual choice between going through the work to suppress them or looking for another petri dish. Before, the choice was obvious: go look for another petri dish.

**Pull request merged**
