### PR TITLE
I got high and made a thing that was broke and 3 years, 2 months, 17 days later I get high and fix it.

### LINKED ISSUE #26156: "The midnight rollover macro doesn't work"
Revision: 6e720cf807cf64f544b212ace6bb31fbdf426e03 
loadtimes

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Fixes realtimeofday, ends midnight rollover bugs

:cl:
fix: Midnight server time will no longer confuse the server, we hope, maybe™
/:cl:

fixes #26156 

I forgot, do we know how the changelog shit will handle unicode/utf? Lets find out.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
are we sure this was actually broken, midnight rollover breaks are usually very obvious immediately

**Comment by MrStonedOne** [comment]
what the fuck goofball?

read the code and see for yourself. It's literally two lines of change that make both the bug and the fix obvious to anybody.

smh can't even logic, must be higher then I am.

**Comment by Iamgoofball** [comment]
this is byond, broken shit works and working shit breaks

**Review by SpaceManiac — APPROVED** [review]

**Review by Cyberboss — APPROVED** [review]
*slaps knee*

HA

**Comment by optimumtact** [comment]
I told you this  never wroked REEERERERWREWRWE NO WONDER TIMERS BREAK

**Comment by MrStonedOne** [comment]
Well ya, I kept getting high and looking at the macros. The macros are fine.

**Pull request merged**
