### PR TITLE
You know all those sound effects and music we don't have legal rights to that we illegally distribute?

### PR DESCRIPTION
**Pull request by Iamgoofball**
chrome_2017-05-30_20-43-55

Everytime your gamemode gets played, OOC gets large amountss of vocal negative feedback I am rating your gamemode a Mistake and reverting it.

Democracy!

### CODE REVIEW

**Comment by optimumtact** [comment]
I actually agree with this PR, clockcult is like a resprited cult but with more confusing mechanics, I don't think it's worth keeping as a gamemode, but the sprites and stuff can be used in cult or a new gamemode

**Comment by YakumoChen** [comment]
>goof makes a poll to remove clock cult

>majority votes don't remove

>goof claims democracy works and tries to remove it anyway

**Comment by Shihrt** [comment]
wew http://poal.me/j2nkzc

**Comment by SgtxRootbeer** [comment]
i actually agree with this PR also. i want the extra alottment to be given to bloodcult.

**Comment by duncathan** [comment]
http://poal.me/h8lub5

**Comment by Pascal125** [comment]
Yeah... When i voted No, the No votes were at Nine, the yes votes were at Seventeen. Then suddenly it swapped around???

Not lying, here.

**Comment by sawrge** [comment]
bloodcult is probably worse

**Comment by duncathan** [comment]
@Pascal125 it appears that you can change your vote on this site so that may be why

**Comment by Shadowlight213** [comment]
Can you make a pr that compiles, first?

**Comment by Iamgoofball** [comment]
Will update this

**Comment by PKPenguin321** [comment]
Clock cult could use work, I do think it's one of our most boring modes, but outright removal is dumb

**Comment by optimumtact** [comment]
just like gang right pk, yeah that's working out so well

**Comment by InsaneHyena** [comment]
About fucking time. Clock cult is cult, but much worse - it's boring, it's tedious, the mechanics are overly and needlessly complicated, even the lore is shitty. The only thing that clock cult has for itself is sprites, but I don't think a gamemode is worth keeping just because the sprites are fancy. 

>Improve, not remove
We've had a year of constant fiddling with it, it wasn't improved at all. It doesn't work by design - it was designed to be cult, but with less action and more base building, and with all of the good features locked behind forty minutes into the round mark. Clock cult can be improved only by replacing it utterly with cult, because they are essentially the same gamemode - just one of them much worse than the other.

I don't believe this PR will actually get anywhere - the division is absolute, and some of the mantainers will die before letting their pet project get removed - but it's very important that we at least raise the issue.

**Comment by RandomMarine** [comment]
Blood cult
Clock cult
Spraypaint cult

I hate all of those modes.

**Comment by Steelpoint** [comment]
Just make it all one cult game mode but it randomly picks the sprites. So one round you have a blood themed cult, the next you get a mechanical themed cult.

**Comment by InsaneHyena** [comment]
>Tainting the actually good gamemode with shitty Ratvar lore

One hell of a compromise.

**Comment by fludd12** [comment]
Clock cult is about a thousand and a half times more interesting than blood cult, imo. If you're removing clock, at least make blood cult less boring.

**Comment by kevinz000** [comment]
How about no goofball?

**Comment by CPTANT** [comment]
Clockcult is fine.

The largest problem with it is that it is yet another conversion mode.

**Comment by Thunder12345** [comment]
Remove Clockcult?
Yes: 8
No: 13
Abstain: 1
Did not vote: 29

Bagil just now

**Comment by Militaires** [comment]
im lovin it TM

**Comment by Militaires** [comment]
you slowly begin to take off your shirt do you wish to continue yes or no?

you make it very hot very spicy very nice do you wish to continue yes or no?

my lizard begin to show, the lizard spit at you, you feel very good do you wish to continue yes or no?

the holy spirit fly from within me and go in your nostril do you wish to continue yes or no?

**Comment by sawrge** [comment]
Say whatever u want about clockcult, bloodcult is still a fucking awful mess and by no means "well designed"

**Comment by Nilons** [comment]
I agree with this pr

**Comment by Haevacht** [comment]
3 polls that say no, don't remove it.

Goof status: Probably asleep.

**Comment by Nilons** [comment]
@Haevacht 3 polls you made without saying where they were posted or who participated.  But yeah 2 polls with 26 and 27 votes totally completely represents what everyone who plays tgstation wants

**Comment by Haevacht** [comment]
None of the polls were made by me, the 2 I posted were from goof, trhe thumbs here and thunder's server poll.

Polls are pathetic, but not even they are on goof's side.

**Comment by Nilons** [comment]
@haevacht that still doesn't change that 27-53 people do not represent what the entire playerbase wants, if they felt strongly about it we would see a lot more defense of clockcult here.  As well as one of those polls being literally worthless because of a meme option.  And while polls are pathetic and so is goof they should not inherently be on his side nor should the fact that they're not somehow increase their validity

**Comment by Steelpoint** [comment]
Depends on which in game poll we are talking about.

The one's that occur in the middle of a round and last 60 or so seconds are a pretty worthless metric, its hard to call a 60 second vote a good measure of a feature's popularity.

The more long term votes, the one's that can be left to take days or a up to a week are a much better metric, since they let you pop into vote any time.

**Comment by KorPhaeron** [comment]
I am never going to take poal.me or strawpoll seriously because anyone with a phone can vote unlimited times

**Comment by GuyonBroadway** [comment]
@Nilons what kind of silly logic is that? _"This poll that says our sample size does not want clock cult removed is not representative of our whole player base, therefore we should remove it."_

Now most of my time is spent on hippie and before you send me scurrying back to my box lemmie tell you than even when trying to shepard the ADHD Kleptomaniac murderbone cats that is our playerbase clock cult still remains one of the more mechanically interesting game-modes there is. 

When people say it's mechanics are "confusing" what they mean is that the conversion button ability is not very well explained so cults end up petering out real quick as the fuck up the conversion. 

You could make clock cult so much better if you changed the text in the slabs to make more sense. It's confusing because nobody is quite sure what anything does, heck just rename script/revenant/application/etc.. to tier 1, 2, 3, 4, and watch as people suddenly get how it works. 

Throw in a little "you must stand still while chanting" message anytime you chant and suddenly things work a lot better.

Rename the Proselytiser to "clockwork RCD" and suddenly you'll see bases. Rename the cogscarabs to "Clockwork fabrication drones". A lot of it boils down to it not making much sense, so it dies off fast, so people never get a chance to play it so they never learn HOW to play it so the next time clock cult is rolled its just as bad and the cycle continues.

**Comment by McBawbaggings** [comment]
I thought this was a joke PR because there's no changelog. I assumed everyone was on board since no one even pointed out the lack of a changelog despite the whole gang fiasco.
Am I going daft here or is something else.

**Comment by duncathan** [comment]
this pr in its current form is a joke and couldn't get in for several reasons (changelog, build failure, etc) but the conversation is worth having nonetheless

**Comment by Nilons** [comment]
@guyonbroadway You literally came to a conclusion and pretended I came to it while quoting something that didn't even kind of resemble what I said.  Nothing about the polls being invalid was an argument why we should remove it, only that the polls were worthless.  Hippie has an entirely different list of rules and a different community to ours.  The over complication of clockcult is specific to it and while true it could be semisolved with more small changes to it the fact remains it is a victim of egregious bloat in features due to its place as a pet project for a maintainer.  BUT the overarching  problem that is being addressed with this PR is the way conversion gametypes are negatively impacting tgstation with tgstation policy and rules.  Clockcult is just the weakest gamemode of our conversions.

**Comment by GuyonBroadway** [comment]
@Nilons In a sense you did make that argument though.  Haevacht said that three polls all had a majority in favour of keeping clock cult and you said that these polls are not representative of the player base.  I mean to me that looks like you were using that point in favour of this PR, especially seeing as you stated that you agreed with this PR.

It also seems to be a common point in this here discussion that these polls do not represent the player base, ergo this PR is acceptable. And its true the polls might not be accurate, they DO indicate an underlying attitude.

I see one of two things here, either the community was not properly polled, therefore you can't claim to know what they want, or they were properly polled and from what I have seen here, they want to keep clock cult.

**Comment by Haevacht** [comment]
I'm with dannnnnnnnnno

**Comment by KorPhaeron** [comment]
Does anyone have the clock cult lore document I can't find it

**Comment by Armhulen** [comment]
Sorry, clockcult. It's shadowling's time to shine now!

**Comment by Nilons** [comment]
@GuyonBroadway My opinions on this PR and my opinions on the polls are mutually exclusive.  You've twice now taken it upon yourself to come to a conclusion for other people "ergo this PR is acceptable. And its true the polls might not be accurate, they DO indicate an underlying attitude."  "therefore we should remove it.".  You're arguing against things you have decided other people are saying, instead of what they're saying.  I will not be held responsible for what you decide to think I say if it's not what I say.

**Comment by loqoman** [comment]
One of the big contrasts that the wiki highlights is that the BLOOD cult is based off of cahos, and running around the station haphazard-like, and that clockwork cult is supposed to be focused around building a base and defending it. At the end of the day both cults have elements of base building in them, and that is just due to the innate strategy of being in a group. 

HOWEVER, I like the contrast. Blood cults should be about cahos, and the clockwork cult should be about base building. I think that here we have an issue of execution. This PR might not be so much about removing the cults vs just making each cult vastly different from each other. 

I DO have a cult bias, I rarely play them, but when I do its a blast. I do not want either cult removed, I think they are fantastic game modes, and is the only other game mode involving magic other than wizard.

MAKE CULTS GREAT AGAIN!

**Comment by ShadowDimentio** [comment]
To the people saying we should improve instead of remove: We've had clockcuck for a year. A whole fucking year of virtually nonstop changes, and it's STILL SHIT.

We've tried fixing it and it's still shit, it's time to take it behind the shed and put 'er down.

**Comment by Militaires** [comment]
kor if u put xhuis down in a shed for trying to add slings and rip your dick off when u hear conversion in a new gamemode design doc

why did u let clock cult in?????????????//////////////////

**Comment by Militaires** [comment]
> and is the only other game mode involving magic other than wizard.

devil.

**Comment by KorPhaeron** [comment]
Because he removed shadowling to add this

**Comment by loqoman** [comment]
Well I guess there are demons and such, but they aren't major game modes.

**Comment by lzimann** [comment]
I say no just because you didn't let me remove gang

**Comment by Militaires** [comment]
but shadowling was better

**Comment by Grazyn** [comment]
Why does this need a poll to be removed? Was there a poll when they removed ERP? When they removed gang? When they removed shadowling? When they removed cats?

Asking for polls is just a desperate ploy to avoid responsibility. It's up to design lead or headmins to make the call.

**Comment by loqoman** [comment]
@Grazyn Well, based on the commit he just wants to straight up nuke the file. 

I have no idea why, you have a very legit point

**Comment by Armhulen** [comment]
Fucking reeee gimmie my slings

**Comment by Armhulen** [comment]
Clock cult is whatever but you know what it isn't: sling

**Comment by Iamgoofball** [comment]
Quite frankly if we're going to do this I want to bite the bullet and remove all conversion modes

**Comment by lzimann** [comment]
Same, but it's never actually happening, I am even willing to sacrifice rev, which is a decent mode, to have it.

**Comment by Iamgoofball** [comment]
@lzimann I need to recode gamemode probs anyways, that'd be a good time to do it over the freeze

**Comment by loqoman** [comment]
@Iamgoofball  What is the issue with conversion modes? Is it just players hate it?

**Comment by MrStonedOne** [comment]
>running these unscientific polls.

**Comment by MrStonedOne** [comment]
I'll run some game polls

**Comment by MrStonedOne** [comment]
I setup a poll for removing clock cult, as well as a IRV poll for ranking the game modes by how enjoyable they are.

**Comment by Qbopper** [comment]
mso saves the day once again

**Comment by jughu** [comment]
But will he save the future

**Comment by Robustin** [comment]
I don't support this except for the purpose of showing how the staggering hypocrisy of Joan as she spent months doing whatever the hell she wanted with Blob and Clockcult despite both being widely panned and if you had ever stopped her and said "Joan OOC really doesn't like your changes I think you should stop" she would assume you were telling some kind of joke.

So I'm baffled as to why, after she "accidentally" left a bugged testmerge up for 24 hours, she felt that OOC shitposting merited closing my PR within a few hours of me committing a fully functioning version. 

Anyway @MrStonedOne is doing the right thing. The amount of speculation done about if something is liked/disliked/good/bad in Coderbus is just stupid. We have relatively easy access to polls yet they are done rarely, designed poorly, and dismissed swiftly. **The fact that we have a Headmin and Maintainer who closes a major PR because of OOC comments when she has the ability to create server polls is just terrible.**

**Comment by sawrge** [comment]
The vox populi is fucking retarded in any case, but she is a maintainer and headmin and within her right to close it.

**Comment by MrStonedOne** [comment]
She opened this can of worms thou, if ooc not liking a change is grounds for that change not happening, then i guess fat sprites, sanic speed, and stun gloves is back on the menu boys!

**Comment by KorPhaeron** [comment]
>then i guess fat sprites, sanic speed, and stun gloves is back on the menu boys!

Finally

**Comment by sawrge** [comment]
She (presumably) acted on her own feelings and used OOC to rationalize them. Trying to justify your own opinions with those of others' isn't really uncommon.
Why does coderbus have any sort of hierarchy at all when everyone tries to circumvent it anyway

**Comment by Nilons** [comment]
MSO comin in here dropping truth

**Comment by Robustin** [comment]
Ironically all this debacle did was get a poll to affirm CC (the players will almost never vote to remove a mode, just alter its weighting) which Joan will appreciate, while Gang War will continue to rot until I can get some kind of affirmation that trumps OOC shitposting.

But its a start, and the ranked mode preference vote is going to be a godsend for intelligent discussion rather than "I really liked/dont like _____________, ergo most people probably feel this way too".

**Comment by loqoman** [comment]
> MSO comin in here dropping truth



Ill drink to that

**Comment by optimumtact** [comment]
@Robustin actually suprisingly it's really fucking hard to get anyone to create polls for us

**Comment by optimumtact** [comment]
@sawrge what heirarchy?
it's flat, with cheridan right at the top

**Comment by Magikarpet** [comment]
https://docs.google.com/document/d/1Lkp-7MyzX3_BG1Gi7pDMJMZNE5SJTI0cCKlBIyrRXEI/edit#heading=h.5or1u1myu0h9

design doc

**Comment by InsaneHyena** [comment]
>I setup a poll for removing clock cult, as well as a IRV poll for ranking the game modes by how enjoyable they are.

Nice.

**Comment by sawrge** [comment]
@oranges I'm sticking my dick somewhere it doesn't belong anyway but do the maintainers not have some level of authority themselves 
Like Cheri > maintainers > coders

**Comment by MrStonedOne** [comment]
>@Robustin actually suprisingly it's really fucking hard to get anyone to create polls for us

Joan is a headmin, and can create polls using the verb. The same verb I used.

**Comment by optimumtact** [comment]
@sawrge well we don't really consider "coders" to be part of the establishment, since any rando can rock up.

I'ts basically cheridan > maintainers (who may or may not listen to each other depending on day of the week and respect level) > everyone else

**Comment by optimumtact** [comment]
@MrStonedOne I meant from my perspective, it usually requires a week or so of begging in adminbus to get anyone to run me a poll

**Comment by optimumtact** [comment]
I'm also the only maintainer who's ever bothered with polls afaik, honestly most of the time it isn't worth it because people will still ignore the poll results anyway and just accuse me of pushing my own agenda somehow

**Comment by optimumtact** [comment]
here's a good example of that https://tgstation13.org/phpBB/viewtopic.php?f=9&t=9598&start=50#p278443

**Comment by loqoman** [comment]
While we are on the subject of bureaucracy, anyone know of a list of the current authoritative positions?

**Comment by optimumtact** [comment]
For coderbus or for the server admins?

**Comment by MrStonedOne** [comment]
yes

**Comment by Qbopper** [comment]
@loqoman https://tgstation13.org/wiki/Administrators usually up to date, might miss the occasional admin but otherwise is good

**Comment by Armhulen** [comment]
wait a second i'm not on there!

**Comment by lzimann** [comment]
[Here](https://tgstation13.org/parsed-logs/basil/config/admins.txt) is an always updated list of everyone that has any access in game(it says bagil, but the file is shared between both servers).

**Comment by loqoman** [comment]
@Qbopper  Thanks.

**Comment by Steelpoint** [comment]
So the new conspiracy was to drive goofball mad so he would close the clock cult revert PR.

**Comment by InsaneHyena** [comment]
Open it now, reeeee

**Comment by Armhulen** [comment]
You failed us goof

**Comment by loqoman** [comment]
Either way, I think we are due for some follow up in terms of balance.

**Comment by Kromgar** [comment]
@Iamgoofball repopen this do it

**Comment by YakumoChen** [comment]
>remember all the copyrighted stuff?

...like Freon?

**Pull request closed without merging**
