### PR TITLE
pubby  cargo (and nearby) update

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
add: pubby cargo has been expanded
add: pubby illegal maint distillery/ botany
add: pubby disposal station
add: pubby maint robo
add: pubby commissary room
/:cl:
 
- pubby cargo has always felt super small and caustrophobic now it has a decent sized comparable to the rest of the maps, an export outlet for people to use export scanners etc , a conveyour autolathe input/output to transfer bulk things to the outside and custom vendors because why not
 
- pubby didnt have a commissary room so i added one near cargo
 
- disposal station, reachable only by transit tubes  usefull for a concealed place where do evil things
 
- there was no ghetto robo or ghetto hydro so i added em

### CODE REVIEW

**Comment by Maurukas** [comment]
Many good things here. I think this may be even nicer than Meta's.

A back door into the cargo warehouse would be appreciated. It usually has one.

**Comment by Iatots** [comment]
I don't like it. it effectively cuts maint in two during chases since the pod will usually not be waiting to be jumped in. What is left of it north of cargo is very small, and south just became a long corridor.

**Comment by MrMelbert** [comment]
the sec outpost and the cargo bay itself seem a little excessively large for what is supposed to be 'the lowerpop station' (though i realize playing stations based on pop doesn't really happen anymore) 

other than that the cargo department seems pretty well done 

only other concerns I would see is with maint, pubby's maint is already know for being mediocre and I don't know if these changes necessarily help or harm that problem, but splitting east maint into three distinct sections will probably annoy some people

**Comment by KathrinBailey** [comment]
You could run distro pipes under the transit tubes on the catwalks, the gas won't be affected by space, would be nice if it had functional atmos.
Also consider that people may disposal a corpse, and now that room is filled with miasma.
It does look nice though.

**Pull request closed without merging**
