### PR TITLE
Removes syndicate bombs from purchase outside of nukeops

### PR DESCRIPTION
**Pull request by silicons**
# https://tgstation13.org/phpBB/viewtopic.php?p=271916#p271916 WITH https://tgstation13.org/phpBB/viewtopic.php?p=271911#p271911 BEING MAIN POST.
THERE IS YOUR REASONING
IM ONLY MAKING THE PR
Well I hate it too, but hey.

# Here have a strawpoll http://www.strawpoll.me/12589589

### CODE REVIEW

**Comment by Incoming5643** [comment]
As my first real feature I ever added to the codebase I am emotionally obligated to stop this. 

Syndicate bombs haven't been a huge headache for years and suddenly they're worse than the zombie virus? 

They only end rounds because people are too lazy to try and carry on. Don't encourage "stubbed my toe call the shuttle!" with stuff like this.

**Comment by kevinz000** [comment]
yet they will result in a shuttle call if they hit an important area because no one will give a crap about fixing it yes it's a player issue but sometimes you just have to say that the code is encouraging that issue when traitors can get for 11 tcs something to instantly lessen the round timer. 
if this change is blocked i'll code the original poster's timelock idea.

**Comment by Incoming5643** [comment]
That's not a great idea either. If you wanted to slow this kind of stuff just have TC accrue slowly up to 20 over the first X minutes of the round.

**Comment by YakumoChen** [comment]
(Actually you'd want to start at a high number and have it slowly decrease to the original price)

**Comment by Grazyn** [comment]
Removing syndiebombs basically doubles as giving scientists their own role-specific traitor item, I kinda like this

**Comment by LaharlMontogmmery** [comment]
Timer isn't just "halved", smart traitors will detonate the bomb payload using C4, resulting in instant booms.

I don't know how to feel about this PR tho...And thats after being on the end of such early bombs.

**Comment by Incoming5643** [comment]
If something messed with the pacing of the timer recently I did not know about it. Just double the timer if this is true (we have done this before).

**Comment by XDTM** [comment]
The other issues still stand, it's about how they're used, not just them being too fast.

**Comment by jughu** [comment]
You dont even need c4 plus payload shooting the payload itself with a gun even works

**Comment by Militaires** [comment]
# the explosion isnt that big anyways they're easy as fuck to fix stop being lazy

**Comment by Dorsisdwarf** [comment]
What kind of retarded biased poll is that, you genital.

**Comment by anconfuzedrock** [comment]
HE SAID IT BOYS HE SAID IT

**Comment by CPTANT** [comment]
Calling the shuttle at the first sign of trouble is not a player issue, it is a fundamental design flaw in the game.

Fixing problems is not rewarded in any way, so why would people bother?

**Comment by BeeSting12** [comment]
There's no reward for engineering besides the satisfaction of fixing the hole. Therefore the hole never gets fixed. This leads to a neverending cycle of holes, shuttle call, and then noone wants to fix it because "the shuttle is called anyways." Even if engineers do fix it, the area is rarely returned to roundstart condition or even usable condition. Oftentimes they leave the pipes out and wiring out, don't bother fixing machines. They just patch it and walk off. This is partially a player issue but also a code issue, and Syndicate bombs aren't the problem. Also I forgot my forum account password so I'll post this here @YakumoChen. Taking TTVs roundstart is shit. Boris is not shitty, you are for taking the TTVs at roundstart. Just telebaton him the minute he leaves the lab with bombs jeez.

**Comment by Cebasiz** [comment]
>mekhi removing bombs 

FINISH THE JOB MEKHI REMOVE TOXINS

**Comment by GunHog** [comment]
I think we should stop things like this right here and now before we start de-fanging powerful mass destruction weapons. If we let this one through, it will set precedent for removing similar things. Why would we be okay with toxins bombs if we do not allow Syndie bombs? What about minibombs? Would we look at further reducing the destructive power of the engine as well?  

I would much rather let Robustin give Engineers space cars before we resort to this. On a more serious note, having engineers be more engaged and better able to fix wires, air, and pipes would be quite nice. Wires especially, because there is only one (viable) way to repair wiring; That one way is tedious to the point where most would not want to bother.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Want long rounds
> Want items that people register as 'time to call the shuttle'

You can't have both in a server that doesn't patrol antag actions [which I'd never suggest, but that's the state of affairs].

**Comment by Dorsisdwarf** [comment]
Hey, if planetstation turns out not to be an early april fools joke, there should be no issue with bombs. Just paper over the gaping pit and tell people not to jump up and down.

**Comment by xxalpha** [comment]
I completely disagree with this, bombs were only really a problem in DA where a consistently high number of bombs were used.

**Comment by Repukan** [comment]
Toxins can make bombs bigger and worse in the first 5 minutes of the game. 

It is preposterous to buff science traitors by removing other job traitors ability to blow shit up.

**Comment by bgobandit** [comment]
I always hated syndicate bombs being added. It's among the worst examples of spoonfeeding antags things they should be interacting with the station to make. If you want bombs, learn how to make bombs and find a way to get into science to do it, like an actual traitor, instead of having it spoonfed to you.

**Comment by Incoming5643** [comment]
Many traitor items are "here's easy access to a thing that you could create with great effort on the station" style things. You can't single out bombs on this metric.

**Comment by bgobandit** [comment]
I agree, and I also hate those uplink items, however, they are not the ones under discussion here

**Comment by Cebasiz** [comment]
all types of bombs are terrible because there is no real ability to stop them.

science bombs are arguably worse than syndibombs though, due to greater explosive power, ease of use, insta-det and numbers.

i've never liked bombs in general just because shutting toxins bombs is """"""meta"""""" so no one ever bothers. syndibombs at least are identifiable and don't fuck over 90% of the station irreparably in one button press.

**Comment by PKPenguin321** [comment]
Shit poll, no "leave them alone" option

**Comment by PKPenguin321** [comment]
Oh but that's not to say I don't support the time gate idea on bombs I think roundstart bomb rushes are lame as fuck but that's still a pretty lame poll

**Comment by Bawhoppen** [comment]
The solution is to make it easier to fix stuff if you have the right equipment, not need destructive power

**Comment by kevinz000** [comment]
@PKPenguin321 eh when I made it I was assuming the don't do anything vote would be GitHub downvotes.

**Comment by lzimann** [comment]
@tgstation/commit-access Thoughts?

**Comment by Incoming5643** [comment]
Again if you remove an item that forces shuttle calls only because of player mentality you are reinforcing that mentality.

**Comment by Bawhoppen** [comment]
Did I get put on ignore again? The solution to destructive items balance, is to make it easier to fix things given the right equipment

**Comment by Bawhoppen** [comment]
Give engineering repair drones or some shit

**Comment by GunHog** [comment]
Perhaps you should take a look at all the Robustin PRs!

**Comment by optimumtact** [comment]
I better not, I might end up closing them.

Anyway this doesn't have support of the players, or the support of senior people who I trust, so that's a no.

**Pull request closed without merging**
