### PR TITLE
[WIP]Mining rework

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
New mining with ore processing, machines and ore multiplication.
DOC HERE 
[Mining Rework (Ghilker version).odt](https://github.com/tgstation/tgstation/files/6464878/Mining.Rework.Ghilker.version.odt)
Online version
[Hackmd](https://hackmd.io/@Jbp1Mdt4QSGuE6nkQddKEw/Sk0EKfFdd)

The PR adds several new machines that will allow a new way to handle ores from lavaland.
Lavaland has also been slightly changed to balance this change.

Starting from the bottom.
--Lavaland Changes--
- Mineral Walls now will deliver low to no ores
- New structures will spawn around the region, those are ore veins.
- Upon discovery you can use a scanning tool (mining or the adv version) to gain point and to know what kind of ore the vein has
- You'll be able to place a mining drill on top of the vein by using a special package that will be available roundstart and from mining/cargo lathe after sci research
- The drills will be controlled from the control panel on the station, it will display all drills, the coordinations, the type of ores, the amount of ores and the state of the drill (powered/operational)
- The drills will send the ores directly to a machine on the station (the ores exit port)

--The machines--
- All the machines can be rotated and they are already equipped with a conveyor belt on the input side (the output is on the opposite side)
- The machines are divided in 4 tiers, with tier 0 available roundstart.
- Each machine will have its own function and it own requirements.
- The machines are
TIER 0 (1:2) (ore directly or dust) (roundstart) The Furnace
Use 2 ores or 1 dust to make 1 sheet
2 ores = 1 sheet

- TIER 1 (1:1) (create dust from ores and dirty dust) The enrichment chamber
Uses 1 ore to create 1 dust or 1 dirty dusts to make 1 dust
1 ore = 1 dust = 1 sheet

- Middle (create dirty dust from clumps) Crusher
Uses 1 clump to make 2 dirty dusts

- TIER 2 (2:1) (create clumps from ores and shards) The purification chamber
uses 1 ore to make 1 clumps or 1 shard to make 2 clumps
1 ore = 1 clump = 2 dirty dusts = 2 dusts = 2 sheets

- TIER 3 (4:1) (create shards from ores) The chemical injection chamber
uses 1 ore to create 1 shard
1 ore = 1 shard = 2 clumps = 4 dirty dusts = 4 dusts = 4 sheets

The purification chamber (TIER 2) requires Plasma gas to function
The chemical injection chamber (TIER 3) require Sulphuric Acid to function
The others just require the correct item

The furnace uses ores directly or dusts to make sheets
The enrichment chamber uses ores directly or dirty dust to make dusts
The crusher uses clumps to make dirty dusts
The purification chamber uses ores or shards to make clumps
The chemical injection chamber uses ores to make shards

To close the line there is the sheet input port that will send the sheets directly to the silo

All the roundstart processing machines will be located in engi since it will be an engi job to expand the line of processing and add more machines and make the whole line more efficient

The machines will have interfaces that will allow fine tuning of the speed of the machine, the power consumption and the efficiency.

The normal orm will still work, but it has the yeld down to 1/3 

## Why It's Good For The Game
A new and more engaging way of processing ores, a factory style job for engineering and mining

## Changelog
:cl:
add: Mining Rework, factory style ore processing.
add: Lavaland walls yeld way less ores but there will be ore veins to be used with the deployment of drills
add: 4 tiers of ore processing machines, from tier 0 (available roundstart) to tier 3, each with different requirements
add: The furnace uses ores directly or dusts to make sheets
add: The enrichment chamber uses ores directly or dirty dust to make dusts
add: The crusher uses clumps to make dirty dusts
add: The purification chamber uses ores or shards to make clumps
add: The chemical injection chamber uses ores to make shards
add: The purification chamber (TIER 2) requires Plasma gas to function
add: The chemical injection chamber (TIER 3) require Sulphuric Acid to function
/:cl:

### CODE REVIEW

**Comment by InsaneRed** [comment]
lets machinize and automize everything guys it will surely not make people bored

**Comment by Kylerace** [comment]
"All the roundstart processing machines will be located in engi since it will be an engi job to expand the line of processing and add more machines and make the whole line more efficient" 

eh, im not sure about this. cargo should be the one creating and delivering mats. engi should be a consumer

**Comment by itseasytosee** [comment]
haha, "new and engaging"

**Comment by Qustinnus** [comment]
this doesn't look fun nor does it solver the issues mining has. You might as well go with oranges idea of removing mining entirely, atleast it's not a bandaid.

**Comment by optimumtact** [comment]
If you can't leave feedback that is useful and contains information that can be acted on, restrain yourself to using the emojii so I can rightly ignore your ramblings

**Comment by Qustinnus** [comment]
ok act on this:

This doesn't solve the problem that getting ores isn't interesting, so you might as well replace mining with buying ores on the cargo console because atleast there's interactions with getting money.

this is just a system that isn't fleshed out or has any depth, and will not make players engage with mining. If you want that you either need to flesh it out more than this or just remove mining entirely.

**Comment by optimumtact** [comment]
>This doesn't solve the problem that getting ores isn't interesting

This assertion is completely unsupported with further analysis about why

>this is just a system that isn't fleshed out or has any depth

You provide no justification for this

2/10, this is your final warning

**Comment by Qustinnus** [comment]
do it

**Comment by optimumtact** [comment]
I'd like to see a detailed design document about what you are intending to achieve with this change.

**Comment by necromanceranne** [comment]
So, for starters, there is a couple of problems that stand out to me that hint that this might need more time in the oven.

Firstly, the fact that the ORM is a strictly inferior method of gathering ores is a little absurd and I question why this is even an option available in the first place. If the correct ore processing method is via the engineering machinery, that should be the _primary_ method from the beginning with no alternatives (other than I suppose hand smelting with a welder). You should not be adding noob traps into a rework like that, even if it is to allow for early ore redemption. There are plenty of ways to do this, like the aforementioned hand smelting. (also double check to make sure that raw ores deposited into an autolathe isn't giving more sheets than when deposited into the orm)

Secondly, the means of gathering ores requires research tech? That's kind of weird by most job standards. I don't think any other job in the game has next to no means of performing their duties without tech progress. Even roboticists can create more borgs from living crew at least from the get-go, even if 90% of the job is in tech nodes otherwise. Without that tech, miners just have to do what exactly?

Well, any initial trek out into lavaland by miners is strictly exploration to find the veins or fighting monsters, which actually seems to be the part that is counter to previous discussions about the direction of mining and the game as a whole. It puts more emphasis on the off-station venturing and removes the on-station gruntwork from miner involvement. Which means, at a certain point, miners _only_ exist to fight monsters. There is a hard cuttoff point where the entire point of their job is done for them by other people and they have an absurd amount of free time to just go get powered up on gamer gear.

As such, I don't agree with the decision to take away miner involvement in the ore processing. That should be their job, because that is going to keep them, even briefly, involved with the station and hopefully occupy a decent chunk of their time. I also think it is a slightly missed opportunity to simply have the ores mined by the drills teleport onto a machine on the station. I think the transportation of ores and delivery of ores in a safe and efficient manner could be an interesting aspect of a mining rework. Even if that means getting engineers involved in the job as well, and requiring some level of lavaland construction to achieve. Personally, I'd love to see at least something giving purpose to building and construction, since it is a part of space that is maybe it's strongest element, and lavaland is a fantastic blank slate for construction.

This rework could also really do with a design doc.

**Comment by ilikesaying** [comment]
The reduction of ores from normal mineral rocks and the nerfing of the ORM will just lower the overall material gain from mining from early on, forcing the crew to be conservative with their material use as well as holding the station at the mercy of the roboticists who can and will spend horrendous amounts of materials on whatever they want.

Giving engineers access to the mining machinery does help with the problem of there being a lack of miners on lowpop, as engineers can set up the SM engine then start using the machinery to obtain materials without risking death.

**Comment by LetterN** [comment]
is this just factorio mining + mekanism ore processing? for reference: https://wiki.aidancbrady.com/wiki/Ore_Processing

**Comment by ATH1909** [comment]
also, won't this make the station's ore input very lopsided?

like, if you don't set up at least one drill on EACH type of ore vein, won't you be severely lacking in the ores that you haven't found a vein for yet?

**Comment by CRITAWAKETS** [comment]
Feel like this should be split between ore veins and the ore processing, so we can test how good both mechanics are. Also, the furnace should just be the ORM.

**Comment by SmArtKar** [comment]
Don't think that marking all comments you don't like as spam will fix this PR

**Comment by necromanceranne** [comment]
> also, won't this make the station's ore input very lopsided?
> 
> like, if you don't set up at least one drill on EACH type of ore vein, won't you be severely lacking in the ores that you haven't found a vein for (or don't have a drill for) yet?

better question, is there any reliance on there being a vein of each type on lavaland, or is it possible to completely luck out and get zero bluespace/diamond/etc veins?

**Comment by SkeletalElite** [comment]
Not a big fan of this. When I play miner I want to kill monsters not  spend 30 minutes building a load of converyor belts. 

I think our current mining system sort of works in that miners tend to passively get materials as they travel around to look for tendrils and fauna to kill, which is the real reason to play miner,

I have a feeling this will encourage mining players to just do the minimum amount of mining they need to do for the essentials (crate keys, med pens) and then just ignore mining entirely, at least with the current system, by the time miners reach this point, science has given them bluespace miner satchels which basically allows them to treat the ore gathering part of the job as secondary and just do a quick dump every time they return to station.

**Comment by Time-Green** [comment]
Could you provide images/a video of the system in progress?

**Comment by davethwave** [comment]
Perhaps have the mining points linked to the miners via a passive income dependent on how much ore is going on station as well as depending on what kind of ore is being brought up? That or just a pot of cash for every vein they link to the mining system and not when they are scanned so they actually get the incentive to put a drill down rather than ignoring the vein after scanning it. Then after they put the machine on the vein they could swipe their id to link it to it and them only so it encourages at least a bare minimum of resource collection since the keys for said loot chests are locked behind mining points. There's a machine that the bartender uses that does something similar that could be used as a bit of a guide if need be. The passive system would also encourage the miners to get more drills down to get the points as soon as possible as well I believe.

**Comment by ArcaneMusic** [comment]
As it stands, mining is about a miner going out and killing animals on lavaland, or breaking rocks to return ores for the station. Your change is exclusively focused on the mineral aspect of lavaland, so I'll focus on that for now. As it exists, the intent is simple, break rocks, scan for ores, explore ruins, and earn mining points to get either upgrades or to fuck around on station (Again, ignoring the PvE focus). Your swapping out the "mining" aspect for more of an exploration based gameplay loop, which is fine on its own. 

My problem is that this hasn't made mining more engaging, but rather just installed a rather rudimentary gameplay loop around the mineral processing, and that loop _appears like a tracking complexity nightmare at first glance_. I've re-read the PR body about 5 times now and I still don't follow why you need shards OR dust of the ores themselves. I'd imagine the intent is that different materials would require different processing to fully extract, like crushing down iron ore to remove impurities, or getting certain minerals combined at certain ratios to make given alloys. And this would be neat and all, but there's a rather glaring issue with this. Implementing something like this works for a game like factorio or mindustry, because each "processing" unit is simple and fast to implement. Building a single machine in SS13 takes too long to warrant it being a major part of gameplay. Chemistry suffers from a similar problem, and while that works around it with the plumbing tools, it's not... amazing.

I'll hold on any more comments past this until I can see a design document, but I'm already flummoxed.

**Comment by Ghilker** [comment]
[Mining Rework (Ghilker version).odt](https://github.com/tgstation/tgstation/files/6464877/Mining.Rework.Ghilker.version.odt)

**Comment by Cyprex** [comment]
For the processing having a static optimal design makes things rather repetitive as it's just about building the same setup every time once you've figured it out. I'm not sure how to solve this.

**Comment by Moose1002** [comment]
I like the idea of having cargo/engineering handle the ore processing since that makes the most since of who would do it, but I see what people mean where that could make playing miner boring. But I think if you're going for a factory system like this since miners aren't actually directly breaking the rocks and collecting the ore anymore, they should have a new job, here's what I'm thinking.

**Moose's Epic Miner Rework Suggestions**
- If you're going for something similar to Factorio just let shaft miners do what you do in Factorio, where you can still mine normally, but since you have machinery that will mine for you, your main focus is to defend that machinery.
- Tweak the enemies on Lavaland or Icemoon or whatever to find all drills miner's have built and attempt to attack the drills together with other enemies.
- Lots of shaft miner's enjoy the combat and fighting the enemies and bosses found on the surface, so with this rework the shaft miner's job will go from breaking rocks, to exploring and defending area's around the map.
- Defending would work similarly to TGMC where miner's would fortify the area around the drills with barricades, and special defensive machinery like turrets.

With these changes, the shaft miner would still have the combat and exploration aspects, but the game play of "Break rock, take rock back to shuttle, get points, spend points, go break more rock" would instead be replaced by more of a defensive combat/building role. And if you do still want to keep the point system, instead of buying things to help in breaking rocks and such, you could instead spend points to unlock blueprints which would let you build better things (or if you don't want the buy one blueprint and build as many as you want as long as you have the materials system, you can just do points to buy a crate with that machine/defense in it)

**A couple ideas for the miner's to get you started**

**Active Defense - Turrets and Such**
- The gun turret - A basic turret where when fed ammo will shoot at any hostiles around it
- The laser turret - A basic turret that fires lasers instead of physical ammo, this does however take power, so a electrical cable ran from the mining base, or a PACMAN if you're far away would be needed to keep the thing running.
- The mortar - Requires human aiming and firing, but with the ability to shoot shells at much farther distances than normal turrets.
- The flamer turret - Basically just like the flamethrower but with AI targeting, give it a flammable gas like you would with a flamethrower and let it do it's thing (This might take some Co-Op with the engineering department)

**Passive Defense - Barricades**
- Sandbags - TGMC style, grab some empty sandbags, grab a shovel, and fill them up, then show them down around your drill
- Metal Barricade - Like a sandbag but made from metal in the metal crafting menu
- Plasteel Barricade - Like the metal barricade but better (This could be done like they do it in TGMC where the barricade can act like a door)
- Barbed wire - Attach to any barricade and when something attacks it they will get injured

**Utility - Support from the Station**
- Mining PACMAN - A special version of the PACMAN that produces more power and with better fuel efficiency when in low pressure environments
- Floodlight - When plugged into power will light up the area around the light
- Emergency Request Beacon - Talk with the Quartermaster, have him prepare some supplies for you and then load it into a teleporter or orbital launcher or something, and then launcher it down to wherever the beacon is located
- Emergency Return Pod - Talk with the Quartermaster, load a person into the pod, have the Quartermaster beam his back up to the station, where he can be brought to wherever he needs to go (probably medbay)
- Portable Telecomm relay - Allows you to talk with cargo (more specifically the QM) whenever the station comms are offline, requires power
- Portable Electric Furnace - A more basic electrical furnace that doesn't produce as efficiently as the station based ones, but can be used to smelt metal for more buildings, requires power
- Bluespace Drill Teleporter - Lets you quickly teleport between active drills (Must be placed next to a drill, and the drill must be running)
- Enemy Proximity Analyzer - Whenever an enemy gets within a certain radius of the drill an alarm will go off notifying you over comms that a drill is under attack (can be combined with the bluespace drill teleporter to quickly defend and maintain different drill bases)
- Miner Statue - Lets the enemies awe in your wealth

Thats all I can think of at the moment but this is just a starting point, I'm sure a bunch of other cool components could be added to make shaft miner a really fun job to play.

**Comment by SuperNovaa41** [comment]
This shouldnt be an engineers job.

**Comment by MLGTASTICa** [comment]
I don't think this fits at all due to how short current rounds last. Rounds rarely go over 1-2 hours, i believe this content would be good if it was like a side-thing for miners to do if theres too many of them or if engineering has nothing to do , but as the main focus of miners , it doesn't seem engaging or fun for players at all , even if they arguably only want to kill monsters and get gamer loot.
Theres also the consideration that SS13 is not persistent at all , the amount of work it would take to setup all of this along with conveyor belts could likely be spent better just smelting at 33% efficiency, assuming that setting up all of this would take 20-30~ ish minutes.
I actually believe that a much better fix to the issue is to let miners spawn with bluespace mining bags and have procedurally generated caves that get constantly deleted and re-generated(every 20-30 minutes), said caves should be filled with ore caches that miners can use a drill to acquire 10-25 ores of that type , this way they could also have ruins with likely bad loot overall, or rare treasures to keep them exploring.

**Comment by dondonpow** [comment]
This seems pretty interesting, so once it's finished even just a test merge would be nice, just to see how it would change how science/engineering would have to interact with miners.

**Comment by davethwave** [comment]
I would support at least a test merge before we decide anything on this and see how the playerbase sees this. It's a major change and while this has it's upsides and downsides. The biggest downside being that now instead of worrying about miners doing their job, we now have to worry about engineers upgrading the mekanism processing plant as well. I believe that this can be pretty interesting to see as well as nice for giving engineers a bit more responsibility beyond the SM and general repairs. I'm just personally worried that there will be a lot of rounds that will be stifled due to inaction on either part of mining and more so especially on engineering's part upgrading the processing area which at this moment can easily be copied round per round and like a template. Such gameplay could easily get boring and could lead to the processing area untouched on a large amount of rounds when it shouldn't be. 
The biggest improvement I can see in this pr for the engineering side is to perhaps make it a challenge to optimize the processing machinery. Such as different gasses having different effects for different materials. Such as while plasma gas would increase the yield range for metals, it would lower it for non metallic materials such as bluespace crystals, glass, and diamonds. Nitrogen being pretty neutral would have a more balanced yield of materials on the other hand oxygen would decrease the amount of metallics such as iron due to oxidization and would naturally generate from the plasma gas so there would need to be a way to filter it out of the piping before problem arise.

**Comment by RandomGamer123** [comment]
~~The machine names sound copied from Mekanism in Minecraft~~ 
If the drill boxes are easy to access (especially roundstart, so I would say removing the tech limitation for printing drill boxes would be a good idea), I would say that that part is mostly fine, as theoretically even a cargo tech or an assistant can set it up. 

However having each drill make only one material seems like that would cause issues as rarer ores might not be found at all if the miners go fight megafauna and die instead of actively looking for rare ore deposits. Having drills be capable of mining every ore, even at low chances (upgradable drills could also be a thing) would help prevent the station having 0 or close to of certain rarer materials (and running out of stuff like uranium or diamonds is actually not that uncommon even nowadays, making the ORM give 1/3rd the output won't help)

**Comment by ilikesaying** [comment]
Maybe give both cargo/engineering access to the machinery in a small room/the warehouse with shutters that can be opened if the engineers are too busy doing engineering stuff and there are no miners/miners are dead

**Comment by the-orange-cow** [comment]
The changes seems like an arbitrary complexity increase.  It also seems like it will lead to massive delays on ore to the station unless everyone is on their game, crippling numerous departments.

**Comment by Fikou** [comment]
To clarify: Talking about balance on the Github in a purely objective way counts as technical analysis. Furthermore, if the person behind the PR invites discussion, it is fine as long as it does not fall into a series of comments mimicking an editorial. Keep it clean, technical, and objective.

Please refrain from using Github as an editorial. It is not meant for expressing your opinion on gameplay. Unless it is for code review or technical analysis, please refrain from commenting, as we have seen multitudes of people abusing the Github and creating unncessary drama and hate against other players, not to mention it makes it harder to find relevant comments that are pertinent to what Github is for. In fact, please be aware that people outside of our community often participate in the comments to drive a wedge between players. Not everyone has good intentions.

**Comment by Qustinnus** [comment]
can you finish the hackmd so we actually know what you're trying to do

**Comment by notfrying1pans** [comment]
ah yes engineering is now responsible for mining which takes longer

**Pull request closed without merging**
