### PR TITLE
[s] Webedit about my previous send2adminchat PR

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
#54757 fixed nothing (I was foolish thinking angle brackets would stop embedding), so we are using grave accents (code quotes).

## Why It's Good For The Game
Other alternative is removing the bot perms.

## Changelog
N/A.

### CODE REVIEW

**Comment by willox** [comment]
Can the message contain its own ` characters or backslashes to cancel out yours?

**Comment by willox** [comment]
I'm still not sure this stops somebody from just putting ``` into a message to cancel out your code block.

**Comment by Ghommie** [comment]
It shouldn't cancel out the links code blocks now, yea.

**Comment by Cyberboss** [comment]
@bobbahbrown

**Comment by bobbahbrown** [comment]
this is a nice solution to what i mentioned to you before, but i think you should just strip all grave characters outright; they will only cause problems as there is no nice handling of them within codeblocks.

**Comment by Cyberboss** [comment]
Bruh, what if I want a .md code block

/s

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
