### PR TITLE
cleans up delta incinerator 

### PR DESCRIPTION
**Pull request by Red-byte3D**
## About The Pull Request
before
image
after
image

cleans up delta incinerator 
## Why It's Good For The Game
piping has given me aids, better piping, and for some reason somone has deciced to put an EXTRA EXPLOSIVE TANK IN THE ROOM WHERE YOU OPERATE WITH BURNING GASES

## Changelog
:cl:
qol: Delta turbine has been cleaned up and changed to look easier on the eyes and give more space for atmosians to work with also adding a thermomachine for faster setup times!
/:cl:

### CODE REVIEW

**Comment by WarlockD** [comment]
...Why this hasn't been done in 5 years I will never know.  Good job.

**Comment by LemonInTheDark** [comment]
Why yeet this bit? lack of need?
image

**Comment by InsaneRed** [comment]
> Why yeet this bit? lack of need?
> image

from my own experience those glasses and canisters/rack only take up unnecessary space

**Review by Maurukas — CHANGES_REQUESTED** [review]
Can you re-add the manual pipe dispenser machine back, either into atmos proper, or in the atmos work area?

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
