### PR TITLE
Craftable and dyeable bandanas

### PR DESCRIPTION
**Pull request by Ebb-Real**
## About The Pull Request

This PR makes basic colored bandanas dyeable, and adds the white bandana which is craftable from 2 pieces of cloth. Also adds the white bandana to white clothing closets.

image

## Why It's Good For The Game

More consistency in dyeable clothing, bandanas are more customizable and easier to get. Bandanas are useful for concealing identity especially with the blindness cone on gas masks now.

## Changelog

:cl:
expansion: Bandanas are now dyeable.
expansion: You can now craft a white bandana from 2 pieces of cloth.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
real

**Comment by Ebb-Real** [comment]
i wanna see if i can do GAGS with this

**Comment by Fikou** [comment]
nice dub

**Comment by Ebb-Real** [comment]
closing this so i can reopen another about this later since i've changed a lot.

**Pull request closed without merging**
