### PR TITLE
Optimizes changing z level as a ghost by something like 85%

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Optimizes hud image addition/removal on z change

We were doing a lot of repeated work here, not to mention all the proc calls.
So I pushed the "operate on loops" behavior into its own proc, so I could ensure we only do some of this stuff once

This plus some removal of safeties saves 75% of the cost of z level transitions as a ghost

Prevents double on_changed_z_level calls from ghosts and shuttles

Reacting to z changes used to be done off doMove or one of those children, timber moved it to Moved, but did not remove the calls that assumed things like abstract_move wouldn't trigger it

This means that moving up/down as a ghost was causing a double call of the whole z move stack. Suprised this never broke anything tbh

Makes csv stat tracking actually encode numbers properly, cleans up an indev comment from plane group code

## Why It's Good For The Game

Speed, and fixes

### CODE REVIEW

**Review by spookydonut — APPROVED** [review]

**Comment by timothymtorres** [comment]
Teleporting to ruins now causes a runtime and gitblame brought me here.

Code_yJTDTL4hx3

**Comment by LemonInTheDark** [comment]
What's its active hud list?

**Comment by timothymtorres** [comment]
Code_p7GfSphwWB

**Comment by LemonInTheDark** [comment]
I guess this is off |=null. maybe it's weird images stuff

**Pull request merged**
