### PR TITLE
Marginally to Mildly Improves Vending Machine, Burger, and Donut sprites.

### PR DESCRIPTION
**Pull request by JStheguy**
[Changelogs]: 
:cl: JStheguy
imageadd: Vending machines now have more complex shading and are rigged with next-gen flickering technology, a couple have either a partial or complete facelift. Maintenance panel overlays have been fixed on machines where they were seemingly left unchanged when the switch to 3/4ths was made.
imageadd: Burger buns are bigger and more detailed.
imageadd: Donuts have been totally redrawn.
/:cl:

[why]: Well, it just makes some assets look at bit prettier, hopefully.

Here are the sprites to compare:
ss13_vemding_tweak
Well, time to crawl back into the depths of hell from whence I came, see you all in another couple of months.

### CODE REVIEW

**Comment by newfren** [comment]
All those burgers look so good holy shit.

**Comment by Therapist1** [comment]
DONKNIED

**Comment by Iatots** [comment]
I like everything except the roburger.

**Comment by epochayur** [comment]
10/10

**Comment by JStheguy** [comment]
export
How about this? It even screams for help in morse code.

**Comment by Kromgar** [comment]
Still think you should add two eyes and another antennae

**Pull request merged**
