### PR TITLE
Cult Rework

### PR DESCRIPTION
**Pull request by ghost**
This is an experimental PR, I don't expect this to actually get fullmerged.

Made in response to Orange's criticisms of the cult mode. This PR removes almost all special powers given to cultists.

Goal: Make a mode that is a unique experience for the crew with as few new mechanics as possible.

Theme: Cult that sacrifices people then conducts a ritual to summon their god

Mode Desc:
A moderate-sized group crewmembers become cultists at roundstart, with the following powers
- Communion: mostly the same, a few less restriction to encourage communication
- Vote for leader: Same as before but the leader only gets big communion text
- Sacrifice: Stand still next to a body with a sharp object to husk it and grant the sacrificer some passive buffs (1 sacrifice-Night vision, 4-some stun resistance, 9-some damage resistance)
- Summon Nar'Sie rune: Once the target (selected same as before) is sacrificed, a global sound is played and this spell can be used to draw a Nar'Sie summon rune in one of the summon locations (same as before). The drawing of the rune is much quicker, and does not alert crew.

Nar'Sie rune invocation: 
- Starting the ritual gives the old centcomm message with the rune location, and triggers red halos.
- Now, the rune must be invoked repeatedly to charge it up. 
- Every 10s, you can invoke it and the rune gains power based on the number of nearby cultists. At max power, Nar'Sie is summoned. 
- Time to summon ranges from 200s (1 cultist) to 60s (9+ cultists). 
- The rune can be erased with a null rod or bible with a 10s wait.

Other changes:
- Since the cult has less powers, the cultists per crew size ratio has been dropped to 6.
- Holy water does nothing to cultists now.

This PR is pretty much finished, but I'm still combing through for missed unused code, oversights, and refactors. I have some concern about the cult being too weak, but that can be fixed by changing the cult/crew ratio or passive powers. But, they may be fine considering they have very few tells now.

Video:
https://drive.google.com/open?id=1HCINwLz1lVsM0cT_QP7gjT41D5CZidZw

### CODE REVIEW

**Comment by Akrilla** [comment]
I'm all for a cult rework but you've literally gutted the gamemode.

**Comment by AarontheIdiot** [comment]
so how does conversion work? is it still the same?

**Comment by nemvar** [comment]
There's no conversion. Have you even read this? Conversion less cult is a good idea, but I think you overdone some of the nerfs.

**Comment by py01** [comment]
Conversion is gone, since oranges was annoyed that cult was revs with baggage, instead the cult gets more poeple roundstart

**Comment by Detective-Google** [comment]
hmm lets just make cult completely shit except for the one robust guy that can now solo carry the cult on his own

**Comment by AarontheIdiot** [comment]
hahahahaha this is shit

**Comment by redmoogle** [comment]
This isn't a rework this is a more of a removal and a way to drastic nerf

**Comment by py01** [comment]
The cult's main power now is that they have no tells until they start summoning, so its pretty reasonable for the cult to only be discovered once summoning starts, then the crew has 1 minute to handle it if everyone is at the rune

**Comment by Detective-Google** [comment]
this PR implies that ripping out conversion makes cult no longer revs+ but in reality the main problem with cult is cultists not bothering to convert and just murderboning and this literally just makes that the only way to play

**Comment by loserXD** [comment]
this is not how

**Comment by redmoogle** [comment]
yeah this isn't a rework this is just gutting a main feature

**Comment by Detective-Google** [comment]
> yeah this isn't a rework this is just gutting a main feature

if you're gonna remove a game mode just fucking remove it don't sodomize and then sterilize it.

**Comment by py01** [comment]
Cult is intentionally gutted because of its bloat, the goal is to make a more elegant mode that pushes the antagonists to use station side features instead of meme powers.

**Comment by bigfatbananacyclops** [comment]
this isn't a rework, there is no new features, i only see removals and nerfs. this is just like revs, not a unique experience, current bloodcult has different shit and weaponry you're gonna counter, are you just bored and want new content?
there isn't even a way to revive other cult mates, so you can technically kill this cult by killing them all. cloning is the only way.

revs is already a gamemode that uses station features, i dont see why there is so much importance for antagonist powers compared to station features.

**Comment by Maciekkub** [comment]
It'd be just better to erase this pr from existence

**Comment by nemvar** [comment]
How the fuck is this like revs? There's no bloody conversion.

I will give my completely honest opinion on this. Completely remove the bloody cult with no traces left and let someone who has passion and a vision for it rebuild it. This isn't it.

It feels like this was done to fullwill the ideaguying of oranges instead of actually thinking about what would be a fun mode to play. This is overthrow 2.0.

**Comment by optimumtact** [comment]
the original cult is like revs cause it's conversion based, although it had a slight detour into construct based instead.

This however, aint it chief

**Comment by wesoda25** [comment]
It wasn’t perfect but I thought it was kinda interesting. It’d be really nice if cult lost a lot of content, simply because its very punishing for new players. I hope something along these lines gets PRed at a later date.

**Comment by KyleFN** [comment]
Conversion-based == revs

**Comment by ATH1909** [comment]
I'd say that the better thing to compare this PR's version of cult to would be blood brothers, but there are more blood brothers and they get the nuke codes and the objective to nuke the station (oh yeah and they get a few passive powers if they bother to screw around with some corpses).

**Pull request closed without merging**
