### PR TITLE
Add's a mini dsl for construction/deconstruction and replaces all construction recipes

### PR DESCRIPTION
**Pull request by optimumtact**
This replaces all if type tool spam with a small text based minidsl that is parsed when the server starts up

Advantges:
no more attach hand if tool checks

Disadvantages:
none

### CODE REVIEW

**Comment by optimumtact** [comment]
admit it you looked

**Comment by optimumtact** [comment]
wrong branch

**Comment by duncathan** [comment]
What's a dsl

**Comment by RemieRichards** [comment]
@duncathan domain specific language

a mini language designed for use within a program for a specific task.
think about how NTSL was a language for Telecomms message modification.

**Pull request closed without merging**
