### PR TITLE
Byond 509

### PR DESCRIPTION
**Pull request by RemieRichards**
## SS13 Dev:
- Min Compiler Version is now 509
- Travis now compiles with byond 509.1300 (the latest build of 509 atm)
## SS13:
- Weapon hit indicators no longer colour/rotate/match the alpha of the atoms they are attached to
- Progress bars no longer colour/rotate/match the alpha of the atoms they are attached to
- Screen objects now ignore everything except alpha. They probably aren't affected by Transform/Colour anyway, but let's cover ourselves for the future.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Rofl Travis is outdated for this PR, honk.

**Comment by MrPerson** [comment]
Prob a good idea to updoot travis

**Comment by Iamgoofball** [comment]
# OH MY GODDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by Alek2ander** [comment]
>APPEARENCE

**Comment by RemieRichards** [comment]
@Alek2ander derp.

**Comment by Core0verload** [comment]
509 is still unstable.

**Comment by MrPerson** [comment]
Yeah, that's why this shit is all being kept on a separate branch for now.

**Comment by optimumtact** [comment]
>caring about stability

we 509 now

**Comment by Core0verload** [comment]
fuckfuckfuck

**Pull request merged**
