### PR TITLE
Removes the slowdown from mining spacesuits

### PR DESCRIPTION
**Pull request by Aranclanos**
come at me

### CODE REVIEW

**Comment by bear1ake** [comment]
:-1:

**Comment by MrPerson** [comment]
The best hardsuit does not need a buff

**Comment by Dorsisdwarf** [comment]
:-1:

**Comment by Razharas** [comment]
Miners already have speed drugs, why make them sanic?

**Comment by Aranclanos** [comment]
because ika added this stupid slowdown and we all agreed that miners should not have it but then nobody did anything and now we're here where people are scared of change but its just because they are to new and reeeeeeeee

**Comment by optimumtact** [comment]
:-1: I hate hardsuits

**Comment by Fox-McCloud** [comment]
Maybe reduce it by 1 instead of removing it?

**Comment by Aranclanos** [comment]
thats not how movement works

**Comment by Fox-McCloud** [comment]
I'm saying that it should be 
`slowdown = 1' instead of the currnet slowdown amount of 2.

**Comment by Aranclanos** [comment]
it still doesn't work like that

**Comment by Fox-McCloud** [comment]
Uh, yes it does.

Time to cross from one side of central primary to another: ~5-6 seconds
Time with a hardsuit on (varedited to 1--can also use a firesuit, etc):  ~8-9 seconds
Time with a hardsuit on (slowdown 2): ~12 seconds


It absolutely does work like that; just tested this out.

**Comment by Steelpoint** [comment]
Eh, have there be some kind of rare monster drop or hard to get RnD item that lowers a suits movement from 2 to 1.

**Comment by Durkel** [comment]
Make it so it moves faster in a area without atmos, that way you're not slow as fucking balls on the asteroid.

**Comment by Shapsy** [comment]
What about making ephedrine more effective for reducing the suit's slowdown?

**Comment by SconesC** [comment]
:-1: Space riot suit

**Comment by AlexCrimson** [comment]
*cough* Just reminding people that a long time ago i suggested giving Miners some special Magboots that remove the speed penalty from Mining Spacesuits when used in zero gravity areas. Could cost like 3k-4k points from the reward machine or something. *cough*

**Comment by Fox-McCloud** [comment]
@AlexCrimson 

That's a really nice idea.

**Comment by Shadowlight213** [comment]
Yeah. Make it work like the ripley, where it's faster on the asteroid.

**Comment by PKPenguin321** [comment]
\>giving the best armor in the game that is also already spaceworthy a buff
what the fuck are you doing reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by bustygoku** [comment]
Why do people care so much about this?

Are you afraid people will actually play miner?

Remove the QM's mining EVA access if theft is a problem.

**Comment by Fox-McCloud** [comment]
@bustygoku 

That would be dumb and akin to taking away barman office access from HoP because he might steal the shotgun.

If it's really that much of an issue, then just give the QM his own mining hardsuit.

**Comment by Aranclanos** [comment]
Kinda sad how everyone thinks on only the 'fights' balance though. 
But at the same time nobody probably plays miner either, so the change doesn't affect them directly.

**Comment by PKPenguin321** [comment]
>Why do people care so much about this?

clearly you have never seen traitor miners coming to the station and killing absolutely everything with gibtonite, an energy cutlass, superarmor, and whatever else they got on their PDA

**Comment by bustygoku** [comment]
Call me a sucker for violence but that sounds fucking awesome.

Also, their superarmor doesn't block stuns or disablers, the most powerful ranged weapons on the station, and they can be gunned down by security's new bullet guns because their armor has a measly 5% bullet damage reduction.

I think this PR should really spark more of a debate on mining. If that upgraded crusher still exists that shits out ore, miners are basically worthless. Miner borgs also move much faster than them and it's a little depressing.

**Comment by Core0verload** [comment]
slowdown = 1 must be perfect.

**Comment by phil235** [comment]
slowdown = 0 is just terrible, make it at least 1.

**Comment by PKPenguin321** [comment]
@bustygoku alright man, i agree that we do need more robust traitors, but let me tell you that this shit used to happen every round. i don't remember who it is anymore but there was a guy who was famous for coming back from mining with all of this insanely good shit and blowing up the malf AI/killing every single cultist/being a traitor and killing half the station. 

i just don't think we should give a non-sec job armor that is a straight upgrade to all forms of sec armor AND is spaceworthy yet another buff by removing the slowdown on it (which is really its only drawback).

what is even the point of this, is aran just salty because he got killed by a mining mob? they're really not that hard to kill, but if anything can't you just tweak the suits to not have slowdown *while you're on the asteroid* instead of while you're validhunting/murderboning

**Comment by bustygoku** [comment]
Honestly @Ergovisavi can correct me here but I thought the point of mining mobs were dangerous and you're not actually supposed to hunt them as part of your job, thus the warning signs. I figured you're supposed to mine safely or mine around them and try to avoid them, until you get the upgrades and are a bad enough dude to take them on. I don't know why miner hardsuits need melee armor at all if this is the case.

**Comment by Razharas** [comment]
I vote slowdown 1
@Aranclanos 
You are what you post

**Comment by wflagg** [comment]
remove the slowdown when on asteroid, and leave it as is for everywhere else maybe?

Gives miners a nice buff while doing their job, but doesnt help for running around murdering the station.

**Comment by MrPerson** [comment]
Just for the record, the change I'd rather see is just do this with every hardsuit

**Comment by Zilenan91** [comment]
We gonna lock this or what

**Comment by Razharas** [comment]
https://github.com/tgstation/-tg-station/pull/12608
Is merged - close

**Pull request closed without merging**
