### PR TITLE
[NO GBP] bumps auxlua to 1.4.4

### PR DESCRIPTION
**Pull request by Y0SH1M4S73R**
## About The Pull Request

This should be the very last version of auxlua I need to release before its byondapi-based replacement

## Why It's Good For The Game

Some people still want to use lua scripting while the new library is yet to be ready for release

## Changelog

:cl:
fix: lua scripting should work on BYOND 515.1633
/:cl:

### CODE REVIEW

**Comment by Y0SH1M4S73R** [comment]
lua scripting fails to init in CI because it runs on 1627, which the latest auxtools commit doesn't work on (but it works on 1633)

**Comment by SyncIt21** [comment]
Does vs code debugger work with this one?

**Comment by Y0SH1M4S73R** [comment]
> Does vs code debugger work with this one?

You're thinking of the auxtools debug server, but it should be (if it isn't already) updated to the newest version of auxtools, which itself works with 1533.

**Comment by SyncIt21** [comment]
Fixes #80578

**Comment by san7890** [comment]
> lua scripting fails to init in CI because it runs on 1627, which the latest auxtools commit doesn't work on (but it works on 1633)

🤓: actually it's failing to init in CI because it's running on 1630

**Comment by SyncIt21** [comment]
Debugger still not working.

Auxtools by default is disabled for so i enabled it in `config/auxlua.txt` file but it still didn't do anything

**Comment by Absolucy** [comment]
@SyncIt21 spaceman-dmm hasn't cut a new release with the updated debug server iirc; you have to compile dm-langserver yourself with the updated debug server embedded

**Comment by SyncIt21** [comment]
> @SyncIt21 spaceman-dmm hasn't cut a new release with the updated debug server iirc; you have to compile dm-langserver yourself with the updated debug server embedded

Damn it. Thanks for the heads up though

**Comment by Absolucy** [comment]
@SyncIt21 can compile it urself like this, tho: 
image

**Comment by san7890** [comment]
can you post that code snippet in a copypastable code block in github because i am not going to type that out by hand

**Comment by Absolucy** [comment]
the commit hash doesn't actually matter i think it's only just spat out to the log anyways

**Comment by san7890** [comment]
lol

**Pull request merged**
