### PR TITLE
Made new_player mobs use the base Login() proc

### LINKED ISSUE #12851: Players sent back to lobby keep Ghost hud.
The buttons dont do anything however

### PR DESCRIPTION
**Pull request by Menshin**
Fixes #12851.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
This should be done in ghost logout so its more generic

**Comment by Menshin** [comment]
The _client_ is apparently already gone when _Logout()_ is called by the ghost mob.
It could find its place in _new_player/Login()_ if we really want genericity here.

**Comment by MrStonedOne** [comment]
That would be ideal then, It's why ghosts going into other mobs don't have that issue, they clear it on login.

In fact, you might want to move that to mob's base login(), as long as you make sure everything else calls ..() before adding hud icons.

**Comment by Menshin** [comment]
Funny thing was that _new_player_ mob was the only mob to not use the base _Login()_.
I had to objectify some part of the base _Login()_, but it's now universally used, with minimal overhead.

**Comment by MrStonedOne** [comment]
:+1:

**Pull request merged**
