### PR TITLE
Changes the alien queen maidify prompt to an action button

### PR DESCRIPTION
**Pull request by Militaires**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)
[]: # (See here for how to easily make a changelog: https://github.com/tgstation/tgstation/wiki/Changelogs. An example changelog has been provided below. Please edit or remove)

:cl: Basilman
rscadd: The Donor prompt for becoming an alien queen maid is now an action button instead, and can be toggled on and off.
/:cl:

cmon motherfuckers cmon

### CODE REVIEW

**Comment by GunHog** [comment]
Wait, so you can just swap sprites on-the-fly?

 I wish you would scrap the donor thing on the fly, but that is not going to happen, so I am just going to recommend a long, several minute cooldown for this, because this absolutely should not be spam-able.

**Comment by Militaires** [comment]
@GunHog  it's like taking clothes on and off, because it literally IS taking clothes on and off, why do you want a cooldown on that.

**Comment by GunHog** [comment]
Because the player should just choose the preferred skin once or twice at the most, and be done with it. The way you have it set now, a player could happily spam the button while spouting nonsense into hivemind chat.

**Comment by ChangelingRain** [comment]
If they're spamming the button and spamming nonsense i doubt they'd really do anything different without the button.

**Pull request merged**
