### PR TITLE
replaces janitor pet with Edmin

### PR DESCRIPTION
**Pull request by ghost**
:cl:
 add: Adds a new companion for the janitors, Edmin the janitor mouse.
/:cl:

I think janitors are overdue for a similar-thinking pet such as Edmin. He even has a cute little janitor hat. The janitor got him for free somewhere.

Replaces the lizard pet.

image

### CODE REVIEW

**Comment by nervere** [comment]
based

**Comment by JJRcop** [comment]
does edmin have an opinion about the mousetraps in the custodial closet?

**Comment by Tlaltecuhtli** [comment]
edmin the dedmin

**Comment by Qustinnus** [comment]
edmin considers himself above other mice and does not mind murder of his kind aslong as he is on top of the foodchain.

**Comment by Difrit** [comment]
Weird obsession with giving every role their own pet

**Comment by Qustinnus** [comment]
its more that I like joke references.

**Comment by JJRcop** [comment]
This PR needs map merge.

**Comment by Qustinnus** [comment]
wtf I swear to god I map merged why does that stupid shit always break

**Comment by anconfuzedrock** [comment]
not only do we have wags, perma already has tom. why do we step on two toes at once?

**Comment by PKPenguin321** [comment]
because edmin is cute

**Comment by Qustinnus** [comment]
Lizards drool Tom is unepic

**Comment by JJRcop** [comment]
If you don't have the pre-commit hook setup, make sure the .backup files for the maps come from master

**Comment by wesoda25** [comment]
Idk if mouse code already does this but if it doesn’t, you should make him eat trash and shit.

**Comment by optimumtact** [comment]
1) add it to every map you lazy shit

2) remove the lizard

**Comment by JJRcop** [comment]
here is a 30 day map merge trial Qustinnus/tgstation#16

**Comment by bgobandit** [comment]
don't fucking remove wags what hte fuck

**Comment by JMoldy** [comment]
why are you replacing Wags :(

**Comment by Qustinnus** [comment]
@JJRcop  a what

**Comment by Qustinnus** [comment]
@bgobandit @jmoldy i was gonna keep him but oranges disagrees

**Comment by bgobandit** [comment]
also misleading PR title

**Comment by optimumtact** [comment]
you can have one or the other, but not both

**Comment by Qustinnus** [comment]
i just hadnt changed it chill out lol

**Comment by ATH1909** [comment]
Wait, is Tom a pet mouse in perma? If so, I'd rather keep two "departments" from having the same type of pet (even though that Edmin sprite is really cute).

**Comment by Qustinnus** [comment]
im pretty sure tom isnt a pet but was supposed to be a rare mouse that you could find.

**Comment by bgobandit** [comment]
as lizard I would also adopt wags for my lizard house

**Comment by anconfuzedrock** [comment]
tom only spawns in perma, is a pet in all but name. why would we need more mice?

**Comment by PKPenguin321** [comment]
Cute hat house

**Comment by carlarctg** [comment]
we already have tom and waggy this is bad

**Comment by ExcessiveUseOfCobblestone** [comment]
# savewags

**Comment by Tlaltecuhtli** [comment]
put wags in gulag where lizards belong

**Comment by bgobandit** [comment]
only you can save wags

https://twitter.com/i/status/1168626421847252992

**Comment by actioninja** [comment]
boooo keep wags

**Comment by fludd12** [comment]
Move wags to perma. Its where lizards are destined to go, anyway,

**Comment by FloranOtten** [comment]
Keep wags his tail. I wouldn't mind wags being moved, though.

**Comment by Potato-Masher** [comment]
Don't kill off wags, move him to perma or somewhere else. No reason to take out our small lizard friend.

:[

**Comment by coiax** [comment]
Why not make Election Season a holiday, and have Edmin replace Wags during that holiday?

**Comment by ExcessiveUseOfCobblestone** [comment]
god save the queen, Lady Wags

**Comment by optimumtact** [comment]
give edmin to the lawyer

**Comment by optimumtact** [comment]
and give him a lawyer tie

**Comment by Qustinnus** [comment]
ok good deal

**Comment by Qustinnus** [comment]
wait how the fuck do lizards wear ties

**Comment by optimumtact** [comment]
along their back dont' question it

**Comment by Iatots** [comment]
What do you mean how do lizards wear ties?
The mouse, edmin, will wear the tie because wags, the lizard, stays with the janitor.

**Comment by optimumtact** [comment]
make a new pr with one or the other replaced

**Pull request closed without merging**
