### PR TITLE
Makes spellbook datum-based.

### LINKED ISSUE #7046: The spellbook is getting ungainly
You know I'm all about more wizbiz, but the spellbook spells page is getting really long as a result.

Someone (maybe me) should look into ways to cut the book into more manageable screens either by introducing more subdivisions (the easy solution) or a more robust datum based spellbook (the cool solution)

### PR DESCRIPTION
**Pull request by AnturK**
spellbook

Fixes #7046

### CODE REVIEW

**Comment by Xhuis** [comment]
nice

**Comment by Iamgoofball** [comment]
THAT UI

**Comment by Incoming5643** [comment]
Thank you for doing what I wanted so much but could never be arsed to do.

I bequeath the honorary title upon yon pull, "Magic Mania 1.9: Sins of a Shitty Encylopedia"

**Comment by WJohn** [comment]
I was kinda hoping it'd receive the nano UI treatment like everything else, but this is nice too.

**Comment by PKPenguin321** [comment]
sexy as hell UI even without a wizard theme

**Comment by HoaxIT** [comment]
Not NanoUI :-1:

**Comment by Incoming5643** [comment]
NanoUI is station aligned UI, wizard needs WizardUI

**Comment by Iamgoofball** [comment]
:+1: I love this sexy as fuck UI

**Comment by Miauw62** [comment]
nanoui is pretty laggy tbh, not everything needs it you faglords.

ON THE OTHER HAND, consistency is nice.
vOv

**Comment by xxalpha** [comment]
If NanoUI is used it needs new image assets. The book of spells having Nanotrasen logos would be dumb.

**Comment by AnturK** [comment]
I don't think spellbook needs nanoUI. There's nothing that needs tracking in real-time here. And i'd have to change nanoUI to use it here since i believe the basic nt/eye/whatever template is always included.

**Comment by xxalpha** [comment]
Yeah, it's really not necessary.

**Comment by AnturK** [comment]
Bump ?

**Pull request merged**
