### PR TITLE
Adds Look up and Look down verbs

### LINKED ISSUE #79966: There is no way to look up without using hotkeys
I tried to use one of those emergency ropes on Icebox for the first time today. In the desc it says to look up using hotkey 'L'... I don't play with hotkeys (that is, I have classic hotkeys enabled so it doesn't mess with the textport). Is there literally not just a verb to look up? I could not find one in any tabs, nor by guessing verbs in the textport.

Please fix this so classic hotkeys works again.

### PR DESCRIPTION
**Pull request by Vermidia**
## About The Pull Request

Fixes #79966

Adds IC verbs for looking up and looking down
## Why It's Good For The Game

Means you don't need hotkeys to look up or down.
## Changelog
:cl:
add: You can now look up and down through the IC menu
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
i don't know how i feel about this though

**Comment by Iamgoofball** [comment]
verbs bad

**Review by ZephyrTFA — CHANGES_REQUESTED** [review]
I don't like this.
I don't want them to be verbs.

**Comment by MrStonedOne** [comment]
They should be verbs, only verbs can be typed in the bar.

They should also be key bindings, only key bindings can be used for fluid keyboard usage.

They should also be 1/4 sized hud icons. only hud icons can be easily pressed with the mouse.

There is no reason why it has to be just one of those.

**Comment by san7890** [comment]
Yea I hate verb spam as much as the next guy but this:

A) Adds a better user experience by allowing more leverage of the BYOND text bar (like it or not, its meant to be a functional part of the engine). I mostly use verbs instead of keybindings still.

B) has close to no technical debt associated with it. It just uses the same procs we already had.

Im still feeling meh on this because I think adding to the number of junk in the IC verb panel isn't neat either, but making it a hidden verb means that it doesn't get the same visibility to users. Hrm

**Comment by Vermidia** [comment]
I made them verbs because they were the easiest to do, but if they don't go through at least making them buttons or something would work.

Since everything that uses Living would need it, it would be a lot of sprite work (which I cannot do), but it would also deal with the issue of looking up/down being only keybinds.

I don't know if there's a better place to put them otherwise, since you aren't going to need them all the time, but when you need them they should be easy to get to.

**Pull request merged**
