### PR TITLE
Refactor crew manifest in lobby and ghost actions

### PR DESCRIPTION
**Pull request by celotajstg**
## About The Pull Request

The crew manifest has now been converted to TGUI for lobby and ghost players.

Default width / height:
image

Resized window to show all departments:
image

## Why It's Good For The Game

Converting more elements of the user interface to TGUI is a good thing. It also just looks way better than the current implementation.

## Changelog
:cl: Celotajs
refactor: The crew manifest has now been converted to TGUI for lobby, ghost, AI and pAI players.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
i gave my 2 cents on coderbus but I'll re-post it here; I think a 2 column layout probably looks more concise with most monitors.

**Comment by wesoda25** [comment]
Odd color for medical, I feel a light blue would work well

**Comment by celotajstg** [comment]
Sure, I've updated the colors to make them closer to the way they are in the chat. Yellow seems to fit command well too, now that I think of it.

image

**Comment by celotajstg** [comment]
Rebased to one commit.

**Comment by Sinestia** [comment]
Should have columns, most people have widescreen 

At worst it's as bad as its always been though, I suppose

**Comment by celotajstg** [comment]
Will take a look tomorrow to see what I could do with making it have columns.

**Comment by celotajstg** [comment]
Update - removed override that makes ranks right-aligned

**Review by stylemistake — APPROVED** [review]

**Comment by celotajstg** [comment]
Change - made it be used for AIs and pAIs.

**Comment by celotajstg** [comment]
Made a rebase just to force re-running integration tests after one broke down for a reason unrelated to these changes.
Overall, the only changes that has been made since approval is adding this TGUI for AIs and pAIs.

No further changes are planned, I intend to keep the 1 column layout.

This PR can now be merged.

**Review by stylemistake — APPROVED** [review]

**Comment by SinfulBliss** [comment]
Sexy.

**Pull request merged**
