### PR TITLE
Time-Green: Adds extendo arm mutation to genetics 

### PR DESCRIPTION
**Pull request by Militaires**
https://youtu.be/_PbfCJ8rnJg Demonstration
Adds a new mutation to genetics I meant to add a while ago but kinda forgot about.

Allows you to shoot your arm out to grab and put down items. The arm is skincolored for max immersion.
You can also kinda use it to interact with your surroundings. Pulling out lights, opening lockers and airlocks etcetera.
A very important thing is that you can use it to interact with others. All intents work just fine with your extended arm. Yes you can supersonic tableslam people with your extended arms.

If your arm gets stuck it'll eventually detach so don't get it stuck. Also if your arm flies too far it'll get ripped of.

:cl: Time-Green
add: Adds extendo arms mutation to genetics. Have fun flexing on your inferior colleges with your extended arms.
/:cl:

**im re-PRing this cause last time oranges closed time's pr because of other people (me) being rude, and that's extremely unfair towards time.**

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
🔬 >> 🤖

**Comment by Militaires** [comment]
@Time-Green ill send you the updated projectiles.dmi file over discord, substitute your current file with that file so it's resolved.

**Comment by Militaires** [comment]
hmmmmmmmmmmmmm

**Comment by optimumtact** [comment]
as far as Im concerned you can get lost bman

**Comment by Militaires** [comment]
image

**Pull request closed without merging**
