### PR TITLE
Swaps the scanner and photocopier icons

### PR DESCRIPTION
**Pull request by ChangelingRain**
The new one really bugs me so I'm swapping them around.
new
This is the book scanner icon now.
old
This is the photocopier now.

### CODE REVIEW

**Comment by duncathan** [comment]
What the fuck who let a black border in
That sprite would be 100x better without it

**Comment by duncathan** [comment]
Ooh also the new sprite should be moved down to be in line with existing library machinery

**Comment by Anonus** [comment]
This is not my sprite and I'm not bothering to edit it, I'm just giving it to the librarian, patron of shitty sprites.

**Comment by bgobandit** [comment]
i-i like the new sprite :(

**Comment by freerealestate** [comment]
don't a lot of sprites have black borders/aren't we inconsistent about that

**Comment by Ricotez** [comment]
:+1: makes more sense for the photocopier to have a bigger body than the book scanner since it also has to hold printing equipment

**Pull request merged**
