### PR TITLE
Removes Obsessed

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Removes obsessed

## Why It's Good For The Game

Nobody likes them. Typical feedback looks like this
image
image
image

And I don't have any great ideas for improving obsessed without removing the main idea behind why I added them. Sorry

## Changelog

:cl:
del: Obsessed are gone
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
yes, open more threat up for more interesting antags

**Comment by JohnFulpWillard** [comment]
“Seth said so” is a terrible argument for a removal of a good and interesting antagonist. There’s complaints about every antagonist ever, obsessed’s criticism isn’t unique to them.

**Comment by SuperNovaa41** [comment]
This sucks obsessed is great.
Sidenote that discord user is a massive troll that complains about every single feature and he should not be taken seriously

**Comment by GuillaumePrata** [comment]
Obsessed is a "non antag" mostly because there really isn't any development on their end, every round they play the same, it has been mostly the same gameplay loop for years.

People don't code things for obsessed because it is not open to cool murderfest designs like Heretics or whatever random gadget you can shove into the pile of crap that is the uplink.

Removing one of the most unique antagonists design we have instead of trying to build it up would just be another push to homogenize our antagonists as recolors of "kill people with your free antag gear" which is just sad for a sandbox game.

**Comment by Iamgoofball** [comment]
you're lucky I'm not an issue jannie or I'd close this PR right now

**Comment by tralezab** [comment]
This is not the reaction Thief got. I'll keep it open a little longer for sake of discussion but @GuillaumePrata has some interesting ideas

**Comment by Time-Green** [comment]
Please update your "why it's good for the game". Saying "no one likes it" with a cherry-picked opinion of 1 player is a false generalisation and honestly ridiculous

**Comment by YakumoChen** [comment]
Suggestion time

Obsessed should have different, randomly selected objective sets like Malf AI with different themes
(Like how sometimes malf can spawn with the Yandere objective, Strand + Protect) 

Examples:
Jealous Obsessed (the current one. Spend time around target and kill a coworker)

Kidnapper (cuff target and spend as much time as possible with them while cuffed, take pictures with both of you together, etc)

Nice Boat (spend time with them while they must be unrestrained and free

**Comment by ilikesaying** [comment]
Yandere Therapy

**Comment by Shadowflame909** [comment]
space yandere must stay dont listen to the haters on this one arm

**Comment by Mothblocks** [comment]
i like obsessed

**Comment by Mothblocks** [comment]
> yes, open more threat up for more interesting antags

interesting antag = another traitor clone that kills everyone

we need more things like obsessed to fill out the low impact pool. this pr wouldve just added more nightmares and sleeper agents and zzzz

**Comment by Iamgoofball** [comment]
>we need more things like obsessed to fill out the low impact pool. this pr wouldve just added more nightmares and sleeper agents and zzzz

that is the explicitly stated intention of the person who was harassing armhulenn to get obsessed removed in the discord, you missed them saying it

i warned you that your decision to throw thief under the bus would result in this, and you didn't listen

**Comment by Mothblocks** [comment]
> i warned you that your decision to throw thief under the bus would result in this, and you didn't listen

would result in what. the pr didnt get merged

**Comment by Mothblocks** [comment]
also im probably not coming back to the tg discord for like 2-3 months minimum ill forget about this by then

**Comment by Iamgoofball** [comment]
>would result in what. 

I told you very clearly that greenlighting the thief removal would embolden assholes to harass our coders into removing content they made that the assholes don't like, as you can clearly see in the OP of this thread they did so and it only didn't work this time because we intercepted it and made sure it didn't work

Just because you glossed over what I wrote doesn't mean it's false or wrong.

pretending that there's no problem and plugging your ears because one instance of it getting stopped doesn't mean the problem doesn't exist and it definitely doesn't remove your culpability for signaling to these people that this is okay by rubberstamping, greenlighting, and letting the thief removal go through

>also im probably not coming back to the tg discord for like 2-3 months minimum ill forget about this by then

You not being present for discussions in the codebase doesn't make the discussions not happen and it doesn't make the ramifications of those discussions go away. This is absurd behavior from someone who's supposed to be a community leader looking out for our developers in the codebase.

**Comment by Mothblocks** [comment]
theres no problem no

**Comment by Iamgoofball** [comment]
You are unqualified for the headcoder position and it is painfully obvious. Please resign.

**Comment by Mothblocks** [comment]
so true

**Pull request closed without merging**
