### PR TITLE
[WIP]Mutant bodypart config refactoring and blacklists

### PR DESCRIPTION
**Pull request by Shadowlight213**
Changing how mutant bodyparts are handled so people with remote can manually disable certain ones if they want.
Mostly done, just need to rework the naming so it's unique.
Also fixes some oversights with wing pref handling.

### CODE REVIEW

**Comment by Kromgar** [comment]
The memes jack

**Comment by kevinz000** [comment]
i stil lwant to be a cat

**Comment by KorPhaeron** [comment]
Is this some kinda shitpost

**Comment by Shadowlight213** [comment]
No it isn't

**Comment by Shadowlight213** [comment]
Ok, the way I'm doing it right now, is just basing it off of the name. I'm wondering if there is a better way to handle it somehow.

**Comment by FantasticFwoosh** [comment]
Its funny here that catpeople are literally just abnormal with body parts. So a argument is raised that they aren't cat-people at all and the AI should listen to them (that's unless we're being picky).

**Comment by Shadowlight213** [comment]
Will work on this later probably.

**Pull request closed without merging**
