### PR TITLE
Reduced file size of TIMEPARADOX2.ogg

### PR DESCRIPTION
**Pull request by Jordie0608**
Reduced the size of TIMEPARADOX2.ogg from 690KB to 37KB by removing four seconds of silence and probably some other stuff Audacity did that I don't understand.
It sounds the same however so ¯_(ツ)_/¯

### CODE REVIEW

**Comment by Supermichael777** [comment]
SNAKE YOU CAN"T DO THAT! The future will be changed, you've created a time paradox!
But seriously lower filesizes are beter.

**Comment by Iamgoofball** [comment]
why doesn't this have a 1% chance to play time warp

**Comment by Chocobro** [comment]
because of copyright or something

**Comment by Iamgoofball** [comment]
fair use length :^)

**Pull request merged**
