### PR TITLE
Delta, Icebox, and Meta Atmos QoL, parity, improvements, fixes, etc.

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
I remapped the atmospherics department to use the actual intended pipes instead of the manifold4w that is used on all but meta. 
I also added a waste release to delta, giving it parity with meta and box.
Rerouted box incinerator to use pure instead of mix.
Reinforced the usage of double pipe bridges to avoid possible null `returned_air` runtimes.
Switched the location of pumps and pipes on the nets leading up to pumps. Someone suggested this in the forums, I was inclined to agree.

PR is mostly ready, but there is one runtime on the DMM when loading icebox. I'll investigate this later.
I've tested all the maps I've altered and fixed most of the issues there, but there might be a few that missed my eye. I'll recheck them again later.

Pics if the actions doesn't work:
Delta:
image
image

Meta:
image
image

Ice:
image
image

## Why It's Good For The Game
Fixes, perhaps. Easier to discern what a pipe in atmospherics does, improves maintainability. Brings parity to delta and box with meta. QoL fixes that aren't powercreep.

## Changelog
:cl:
qol: atmospherics dept on delta, icebox, and meta got cleaned up. Pipes and pumps near the tanks got switched. Incinerator on box rerouted. Delta waste release added.
fix: Removed instances of duplicated pipes in icebox atmos.
/:cl:

### CODE REVIEW

**Comment by vincentiusvin** [comment]
Oh there is one right there on delta. Ugh.

**Comment by dragomagol** [comment]
Would you mind using the wall mounts (lights, light switches etc) found in #58809 ? I'm trying to kill off a bunch of varedits and prepare for giving wall mounts dirs.

**Comment by optimumtact** [comment]
parity is not an argument for change

**Comment by vincentiusvin** [comment]
It seems like the compilation errors were on master, I suppose this PR is ready for review.

> Please use the wall mounts (lights, light switches etc) found in #58809 ; I'm trying to kill off a bunch of varedits and prepare for giving wall mounts dirs.

I didn't change any of the apc, lighting, etc, but i will keep that in mind if I'm going to.

**Comment by vincentiusvin** [comment]
I think this overwrites some previous commits, give me a minute.

**Comment by vincentiusvin** [comment]
I'll try and see if i can circumvent the massive LoC changes. Give me some time.

**Pull request merged**
