### PR TITLE
Decreases the minimum age to -4,294,967,295, overflowing it to a positive value of 4,294,967,295

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

This PR decreases the minimum age to -4,294,967,295.

## Why It's Good For The Game

A future where unaccountable megacorporations rule the solar system and collective action is illegal would logically mean the return of all the horrors of the gilded age, though more severe.

One of those horrors were of course:

# super mega child labour

Therefor, in the interest of building an interesting and believable setting for our game, SS13 should also have super mega child labour.

## Changelog
:cl:
balance: Decreased the minimum character age to -4,294,967,295.
/:cl:

### CODE REVIEW

**Review by Kylerace — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
Byond does not have under or overflows how many times do I need to tell you ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by tralezab** [comment]
CITATION FROM THE JOKE POLICE WAHHH

**Comment by LemonInTheDark** [comment]
PEOPLE KEEP SAYING IT UNIRONICALLY HUMOR CAN MISLEAD REEEEEED

**Comment by ArchieBeepBoop** [comment]
_Unironically adds an overflow to byond integers_

**Comment by interestingusernam3** [comment]
the

**Pull request closed without merging**
