### PR TITLE
[Ready] Adds atmos circuits

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
:cl: McDonald072
add: A few new circuits for dealing with atmospherics have been uploaded to your local printers.
/:cl:

Essentially makes it possible to create programmable atmospherics for your autism fort. The package includes:
- Atmopsheric analyzer: Use it to scan the atmosphere and atmos things around the circuit. It gives information such as the gases present, their amount, temperature, pressure, and volume.
- Gas pump: Transfers gases between tanks and portable atmos stuff like canisters.
- Gas vent: Transfers gases between the environment and whatever you want to store them in.
- Integrated connector: Attaches tanks and portable atmos to connector ports.
- Gas filter: Filters out one gas from a mixture.
- Integrated tanks: Small gas tanks.

### CODE REVIEW

**Comment by Ratvar** [comment]
Bots that mix bombs for you
Bots that let out plasma and sparkle
Bots that depressure rooms

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
> Mix bombs
If someone made a circuit that pulls all canisters into place, waits until the mix is done burning then fills the tanks for you, while also chilling and filling the oxygen somehow, I'd be mad impressed. I'd wager that doing everything by hand would be faster.
> Let out plasma and sparkle
If a bot farted in your face and lit you on fire it'd be hilarious
> Depressurize rooms
The pumps in circuits are half as fast as normal pumps, you'd be better off breaking a window or using a portable pump. Could be turned down even more if the need arises.

**Comment by Grazyn** [comment]
It took years but we finally have a way to attach a signaller to pumps and canister. You're gonna see some real shit very soon

**Comment by fludd12** [comment]
I can picture this going _horribly right_.

I can't wait.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
It is. Do I ping a maintainer or mark this as ready in some way?

**Comment by davethwave** [comment]
add a (ready) or something to the title, perhaps it would give it more attention since there's a WIP tag on the pr still.

**Comment by optimumtact** [comment]
@tgstation/commit-access unless one of you wants to fight for this I'm gonna close it in ~24 hours

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
If nobody wants this, can I just cut out everything but the analyzer?

**Comment by optimumtact** [comment]
Sure

**Comment by SpaceManiac** [comment]
Humor me, I don't really know circuits. Is putting the analyzer in an assembly then pulsing "scan" with a multitool supposed to be sufficient to show gases in the information window? If not, what's the minimum circuit I can use to test that this works?

**Comment by PKPenguin321** [comment]
That should work. Leaving the input ref as null is supposed to return the air of the tile it's on.

**Comment by Hate9** [comment]
Aww crap, I really wanted this.

**Comment by SpaceManiac** [comment]
Merge conflict.

As I mentioned previously, I haven't been able to get the circuit to work, but this may be up to my ignorance of circuits. Let me know if you have instructions or something so I can test the PR.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
It broke somehow... I'll try to fix it

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
To test this @SpaceManiac :
1. Use a circuit printer to print any assembly and the atmos analyzer (bottom of input category), and obtain a circuit debugger.
2. Insert the analyzer and a battery into the assembly.
3. Use assembly in hand and click on the analyzer in the list.
4. Hold the circuit debugger in hand and click on "scan". Result of scanning with a null or non-air-containing target will look similar to this:
image
5. Use the debugger in hand and select "ref". Walk over to a canister of some kind and click on it, then click on "target" in the circuit window, then scan. Result of scanning a plasma canister:
image

**Review by SpaceManiac — APPROVED** [review]
Works in testing.

**Comment by fludd12** [comment]
Yesssss time to make automated airlocks.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Oh crap I didn't change the changelog

**Comment by SpaceManiac** [comment]
"one" is "a few", right?

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Not really...

**Comment by Hate9** [comment]
It seems to me like the VAST majority of people commenting and voting on this wanted it. Why did it get all but disabled?

**Comment by ninjanomnom** [comment]
Because the majority isnt in control of the code

**Comment by Hate9** [comment]
But the majority IS still the group that matters, isn't it?
If three people hate an idea, and eleven love it, does it really matter who the three are?

**Comment by ninjanomnom** [comment]
In short no.

Maintainers are free to require changes or close prs based on any code or gameplay problems they feel it has. Most maintainers to some extent take into account the popularity of a change but they are not required to.

**Comment by recurracy** [comment]
I'm sorry, but why exactly is the gas analyser the only thing that has been merged? What gameplay problems would these circuits provide to the server?

**Comment by optimumtact** [comment]
[21:40] oranges: actually we keep them gimped because they're not a very interesting or engaging mechanic to anyone but programmers
[21:40] oranges: if there was actually a good interface to them that was visual/physical/tangible
[21:40] oranges: they might be allowed to bloom

**Comment by recurracy** [comment]
Yeah, we've been talking about it in Discord, heh. I'll make a topic on the TG forums later today, should make it easier to discuss how circuits in general could use a change for the better.

**Comment by Hate9** [comment]
For the record, someone made a PR to implement the PDA/genetics/whatever else interface in circuits.
https://github.com/tgstation/tgstation/pull/39148
Looks like it's implemented now, too.

**Comment by SpaceManiac** [comment]
that PR makes the circuit printer look prettier, it doesn't change functionality at all

**Comment by Hate9** [comment]
@SpaceManiac What kind of a change to the printer's functionality did you mean, then?

**Comment by SpaceManiac** [comment]
@Hate9 I don't understand what you meant by:

>For the record, someone made a PR to implement the PDA/genetics/whatever else interface in circuits.

The PR you linked doesn't do that.

**Comment by Hate9** [comment]
@SpaceManiac You're right, it applies it to the printer. My mistake.
Now, it's your turn to answer my question.

**Comment by SpaceManiac** [comment]
I don't know what you're referring to by your question

**Comment by Hate9** [comment]
What kind of a change in functionality were you looking for?

**Comment by ninjanomnom** [comment]
They never implied they wanted a change in functionality

**Comment by Hate9** [comment]
Spacemaniac did:

> that PR makes the circuit printer look prettier, it doesn't change functionality at all

**Comment by Hate9** [comment]
Stating that something doesn't change functionality kind of does imply that whether or not it does change functionality is somehow relevant to the conversation, and since I didn't bring up functionality, it sort of IS implied that Spacemaniac wanted it.

**Comment by ninjanomnom** [comment]
You brought up the pr first as if it were relevant, SpaceManiac chimed in about that. You're trying to read too hard into their words and this is a dumb conversation.

**Comment by Hate9** [comment]
Regardless of whether Spacemaniac was implying anything or not, I can definitely agree that this is a dumb conversation.

**Pull request merged**
