### PR TITLE
Two new electric powers for genetics

### PR DESCRIPTION
**Pull request by PKPenguin321**
Insulated - You become shock immune, basically innate insulated gloves. 25 genetic instability means that this takes a whole 1/4th of your space for mutations by itself, though

Shock Touch - Electric punch! You get a wizard-like touch spell that does burn damage, confuses, disarms, and jitters. Has a 10 second cooldown and can only be created by combining Insulated with Radioactive. Kind of weak at the moment... not sure how or if I should buff it. I definitely don't want to add a stun, since that would just be stun gloves 2.0, but I would like to stick to the electricity theme.

:cl: PKPenguin321
add: New genetics power: Insulated - You become shock immune, basically having innate insulated gloves.
add: New genetics power: Shock Touch - Electric punch! You get a wizard-like touch spell that does burn damage, confuses, disarms, and jitters. Has a 10 second cooldown and can only be created by combining Insulated with Radioactive.
/:cl:

Why:
These powers are cool, Goon has Insulated and it works for them (though I only noticed this after writing my code), and having more mutations in genetics is what will keep everything balanced (because the more mutations, the less you can get).

Side notes: Moved some sprites around for touch spells to keep them that much more organized. The inventory and inhand sprites for the shock touch are recolors of ei nath that I made frame by frame. The action button sprite for shock punch is just the cartoony silhouette-human-with-skeleton-showing thing that we already have in-game.

### CODE REVIEW

**Comment by ATH1909** [comment]
Can you make these have the same relationship with ethereals that the firebreath mutation has with lizardpeople (I think they always will have it unawakened in their genetic code or something; I haven't looked too closely)?

**Comment by Shadowflame909** [comment]
If this gets merged, I'm going to make a high geneticist alt with only one gimmick.


SUPERHERO STATIC SHOCK

**Comment by Cyprex** [comment]
Note that we also have experimental surgerys as a source of shock immunity, I believe it's nerve grounding surgery.

**Comment by OverlyGeneric** [comment]
> Note that we also have experimental surgeries as a source of shock immunity, I believe it's nerve grounding surgery.

oof

**Comment by PKPenguin321** [comment]
>Note that we also have experimental surgerys as a source of shock immunity, I believe it's nerve grounding surgery.

This should neither conflict nor stack.

**Comment by PKPenguin321** [comment]
>Can you make these have the same relationship with ethereals that the firebreath mutation has with lizardpeople?

Cool idea, but I'd rather give ethereals something else

**Comment by OverlyGeneric** [comment]
> Cool idea, but I'd rather give ethereals something else

Give them the power become a flash people and cause them to lose nutrition + stamina.

**Comment by ATH1909** [comment]
> > Cool idea, but I'd rather give ethereals something else
> 
> Give them the power become a flash people and cause them to lose nutrition + stamina.

So like an AoE flash, but as an action button that costs a lot of nutrition to use?

I like it. Maybe there could be one that replicates the hypno-flash's AoE effect as well (note that the hypno-flash's AoE effect does NOT hypnotize people/put people into a hypnotic trance, so it wouldn't let you start a hypno-cult (on its own, at least)).

**Comment by subject217** [comment]
why have stungloves when you could have STUNHANDS

**Comment by PKPenguin321** [comment]
>why have stungloves when you could have STUNHANDS

funny you mention it because i was aware of this possibly being the case and was really careful not to make it too strong. not i think that shock touch is too weak so i'm still trying to think of a way to make it better without making stun gloves 2.0

**Comment by anconfuzedrock** [comment]
zap could be a tesla shock like the one in the wiz spell that doesn't stun but still chains

**Comment by PKPenguin321** [comment]
For Shock Touch, I ended up switching the flat brute to electrocute_act(). This plays the "cartoony visible skeleton" animation when you get shocked. I also upped the damage and confusion by 1.5x and lowered the instability by 10. I feel that's a reasonable buff, though it still may be weak compared to something like hulk. Oh well.

**Comment by subject217** [comment]
i want to give people the big static shocc

**Comment by necromanceranne** [comment]
I can't wait to play a faux wizard through genetics with all these powers getting added.

**Comment by Shadowflame909** [comment]
If you take too many powers, you get ashes and become uncloneable, Colossus style. Good way to kill targets.

**Comment by PKPenguin321** [comment]
Yeah, new genetics has "instability" which, if you exceed 100, will rapidly kill you. We can have lots of new powers now without worrying about them being stacked and stacked and stacked. In fact, having more powers means others are rarer, so a large amount of different and unique powers means that you likely won't see the same ones each round.

**Comment by PKPenguin321** [comment]
Just added these to the wiki. Almost forgot to do that

**Pull request merged**
