### PR TITLE
Remade sechud icons to be more colourful

### PR DESCRIPTION
**Pull request by Sparkezel**
## About The Pull Request
I remade all of sechud icons to be more colourful. Here are the examples:
https://imgur.com/a/rlT41cU

## Why It's Good For The Game
More colourful icons look better than old flat colours.

## Changelog
:cl:
imageadd: added some icons and images
Remade sechud icons
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
im not a fan, they are simple holographic icons to instantly recognize what job someone is, not shiny plastic buttons
they also use a shitton of colors for such a small sprite and it will make adding new ones harder

**Comment by MrDoomBringer** [comment]
Agreeing with @Fikou here. Also, some of these icons are pretty iconic and appear on things like 'official' merch - not saying we shouldn't ever change the sprites, but I don't really see a clear enough improvement here.

**Comment by Sparkezel** [comment]
I have no problem with that, I just wanted to make them to look prettier to look at but its just from my perspective, is there something that I could do to improve them?

**Comment by Cyberboss** [comment]
Discourse aside, we are currently in a feature freeze. See #54733

**Comment by optimumtact** [comment]
How would this be considered a feature? it doesn't add new sprites.

**Comment by Fikou** [comment]
> How would this be considered a feature? it doesn't add new sprites.
> 
> The code equivalent is a refactor, which is allowed

whats balance then

**Comment by TheBonded** [comment]
> im not a fan, they are simple holographic icons to instantly recognize what job someone is, not shiny plastic buttons

same with the old ID card sprites, which were simple diagonal sprites to instantly recognize what access level it would have, not shiny framed pictures. And yet, the sprites were remade, and they look great now.
> they also use a shitton of colors for such a small sprite and it will make adding new ones harder
This is true; however, I'm sure it wouldn't be too difficult to make new sprites, since it's one core colour that fades into a lighter variant at the top left and bottom right corners.

**Comment by Fikou** [comment]
>same with the old ID card sprites, which were simple diagonal sprites to instantly recognize what access level it would have, not shiny framed pictures. And yet, the sprites were remade, and they look great now.

except thats not true at all they all used the same icon for everyone

**Comment by TheBonded** [comment]
> > same with the old ID card sprites, which were simple diagonal sprites to instantly recognize what access level it would have, not shiny framed pictures. And yet, the sprites were remade, and they look great now.
> 
> except thats not true at all they all used the same icon for everyone
> dont get me wrong the sprites look good but i dont think they fit for huds at all

fair enough, I will admin they are a bit flashy. however, if this pr is merged, it might convince people to start revamping some of the other older blander sprites to look nicer.

**Comment by optimumtact** [comment]
@Twaticus

**Comment by MrDoomBringer** [comment]
Sprites don't need to look 3d/embossed/have a million colors imo. Sometimes flat transitions are fine as long as the colors are good
this 
image
isn't necessarily an improvement over this
image

**Comment by Twaticus** [comment]
sorry its gonna be a no from me. while normally a bit of shine and shade is preferred, you need the huds to be as clear as possible when looking at them quickly and these mess with that clarity

**Pull request closed without merging**
