### PR TITLE
Add advanced fire extinguisher to techweb

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
This adds the advanced fire extinguisher to the `Experimental Tools` node.

## Why It's Good For The Game

There are several advanced engineering tools in this node.  This is an item that is considered a better version of a regular fire extinguisher for atmos techs.  It makes sense to put this with the other upgraded tools in techweb, since ya know, it's technically an advanced version.  It does spawn empty, so it needs to be refilled with a foam tank dispenser.

## Changelog
:cl:
qol: Add advanced fire extinguisher to techweb
/:cl:

### CODE REVIEW

**Review by Fikou — CHANGES_REQUESTED** [review]
needs to be a subtype that doesn't start with any foam.

**Comment by timothymtorres** [comment]
> needs to be a subtype that doesn't start with any foam.

Done, thanks for pointing it out.

**Comment by private-tristan** [comment]
How do you even refill the extinguisher outside of going to cargo and buying a tank?

**Comment by timothymtorres** [comment]
> How do you even refill the extinguisher outside of going to cargo and buying a tank?

There is a foam tank that spawns in atmos.  Only the advanced fire extinguishers can use it.

**Comment by Jackal-boop** [comment]
> > How do you even refill the extinguisher outside of going to cargo and buying a tank?
> 
> There is a foam tank that spawns in atmos. Only the advanced fire extinguishers can use it.

only on tramstation

**Pull request merged**
