### PR TITLE
Adds a new beard style. Broken Man.

### PR DESCRIPTION
**Pull request by Militaires**
:cl: Basilman
add: Added a new beard style, Broken Man.
/:cl:

image
image
image

### CODE REVIEW

**Comment by Repukan** [comment]
Looks painful

**Comment by Militaires** [comment]
@Repukan 

it does, i worked harder to get to this level of painfulness.

**Comment by ExcessiveUseOfCobblestone** [comment]
@MrStonedOne

**Comment by Supermichael777** [comment]
REFERENCE TO INCREDIBLY META SHIT DETECTED

**Comment by Militaires** [comment]
@Supermichael777 @ExcessiveUseOfCobblestone 
i didnt actually mean it to resemble mso but i can see where the difference lies.

the reference is from elsewhere though.

**Comment by FantasticFwoosh** [comment]
Warning, godlike beard growth may require addictive substances to maintain

> reeffeeeerrrnnnceeesss

**Comment by Kraseo** [comment]
I've got the Joy, Joy, Joy, Joy down in my heart...

**Comment by Militaires** [comment]
@kraseo

do you know why gary the hot soup is so weak when you first meet him.

the soup was not ready.

**Comment by Repukan** [comment]
SOUPS ON BABY

**Pull request merged**
