### PR TITLE
Fixes russian revolver

### LINKED ISSUE #66142: Russian Revolver is not working
## Reproduction:
Step 1: Load a russian revolver with 6 bullets and spin the chamber.
Step 2: Shoot yourself.
Expected result: You get shot...
Result: The revolver does not shoot.

### PR DESCRIPTION
**Pull request by robbertapir**
## About The Pull Request
Fixes #66142.
Stuff was runtiming because of a missing argument.

## Why It's Good For The Game
The russian revolver works now.

## Changelog

:cl:
fix: The Russian revolver now works again
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
does this work with named args? if yes please use them for readability

**Comment by robbertapir** [comment]
It works.

**Comment by GolfinhoVoador** [comment]
maintainers moment

**Comment by ExcessiveUseOfCobblestone** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=5&t=31505

**Pull request merged**
