### PR TITLE
Silicons can no longer take brain damage

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
fix: Silicons can no longer take brain damage
/:cl:

### CODE REVIEW

**Comment by davethwave** [comment]
I think I actually saw a Borg who had brain damage, wonder how it happened but it did.

**Comment by AnonymousNow** [comment]
Presumably a person with brain damage gettin' borged?

**Comment by Anonmare** [comment]
Don't borgs have max brain damage constantly? The health analyzer registers them as having non-existent brain activity

**Comment by MoreRobustThanYou** [comment]
borgs are pretty retarded

**Comment by awesine** [comment]
borgs have brains
brains can get brain damage
close now

**Comment by davethwave** [comment]
There would be 2 classes of Borg's then, one with a mmi and the other would be a posibrain. If you don't want to remove it then perhaps have a way to implement brain damage to Borg's and another way to repair it.

**Comment by davethwave** [comment]
For instance ion rifles and emp weaponry would give brain damage to posibrain's while due to the organics of the brain radiation based weaponry or rad storms would give mmi's brain damage.

**Pull request merged**
