### PR TITLE
Night of the living deathwands

### PR DESCRIPTION
**Pull request by Delimusca**
hitting a gun/wand/banana-thrower with a bolt of animation will now create a ranged mimic, which will fill you with lead slugs and death beams instead of biting your shins.

demonstration

### CODE REVIEW

**Comment by Anonus** [comment]
100/10, both amazing and terrifying
animate the armory to stun everyone forever!

**Comment by PKPenguin321** [comment]
So you could, say, animate a staff of chaos and it would fire chaos at people on it's own?

**Comment by Incoming5643** [comment]
The staff of animation is already really good, so yeah keeping weapons with finite ammo (read, nearly everything except other staves) is pretty dang important

**Comment by Iamgoofball** [comment]
animate a staff of change/10 :+1:

**Comment by Incoming5643** [comment]
An animated staff of change/chaos with instant summons attached would be pretty foolproof, since you could just leave it laying around as a trap and summon it back to you every so often in case it was defeated. Mind that costs more than half a wizard's spells to do, so I don't think it'd really be overpowered.

**Comment by Delimusca** [comment]
@Incoming5643 the whitelist was indeed horrible, i chopped that out quick. if i can figure out how to check for null var existance i could cut this down by 66% and fix everything. might try making zapgun and kin into lists or something. the weapons are in the mobs contents so checking them directly should be entirely possible.

**Comment by AndroidSFV** [comment]
The check for a null var is  if(!var)   correct?

**Comment by Delimusca** [comment]
null vars are uninitialized, so if(!var) would return var not found. well, thats how my fights with the byond compiler usually go anyways.

**Comment by Razharas** [comment]
Make it so you can animate stuff of animation so it can animate while you animate

**Comment by Delimusca** [comment]
alright i removed the shotsleft stuff and made the mimics directly check and modify their internal gun's ammo. working on making empty weapons retreat and changing the ballistic gun checks, and then this will probably be done. i may have to rebranch or something though because i manually updated animation bolts like a scrub and broke everything

**Comment by Delimusca** [comment]
removed the retreat proc since i couldn't get any mob step procs to work, and ranged mobs already retreat. also got empty casing drops working right mostly, and fixed the icons not updating. this should be pretty much done now, unless anyone wants improvements done or i missed anything.

**Comment by Miauw62** [comment]
The ranged mimics should probably qdel() their guns on Destroy()

also, the code doesn't seem to be working, it just creates a mimic/copy, but not a ranged mimic.

**Comment by Miauw62** [comment]
it werks

**Pull request merged**
