### PR TITLE
Bans fox poaching

### PR DESCRIPTION
**Pull request by MrMelbert**
## Changelog

:cl: Melbert
del: The poaching of foxes is now outlawed. No more fox DNA infusers for you.
/:cl:

### CODE REVIEW

**Comment by norsvenska** [comment]
1984

**Comment by Striders13** [comment]
WE HAD A GOOD RUN FOXBOYS

**Comment by Ghommie** [comment]
DNM Until you provide the reason to why this is being removed, that's all.

**Comment by DaCoolBoss** [comment]
You really should put in what this PR actually does. For people who don't want to check, it removes the fox ears from putting a fox in the DNA infuser.

**Comment by Jacquerel** [comment]
Oranges did not request this and even if he did "a headcoder wants it" does not suffice for a PR justification even if it has an entire design document, which this does not. Fill in your PR body
image

**Comment by MrMelbert** [comment]
well that discord comment is a lie because both the tail and the ears were approved together

**Comment by MrMelbert** [comment]
he just couldn't figure it out

image

**Comment by Jacquerel** [comment]
thats between you and oranges, you removing this is done on your own intiative

**Comment by atlasle** [comment]
reopen this, STAT

**Comment by CCC23** [comment]
its yo ho hover

**Pull request closed without merging**
