### PR TITLE
Makes dust remains cleanable with acid.

### PR DESCRIPTION
**Pull request by ShizCalev**
🆑 ShizCalev
tweak: Remains left over by dusting or soul-stoning a mob are now dissoluble with acid.
/🆑

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by KorPhaeron** [comment]
I guess this is nitpicky but isn't soap and water to remove a skeleton a bit silly

Pretty big buff to cult as well if they can cover their tracks like this

**Comment by davethwave** [comment]
Perhaps make a new chem that acts as a cleaner that uses sulfuric acid or something then?

**Comment by ShizCalev** [comment]
Revised, now you can clean them using acid (Fluorosulfuricor & Sulphuric.)

**Comment by davethwave** [comment]
Nice

**Comment by KorPhaeron** [comment]
@ShizCalev Thanks

**Comment by GunHog** [comment]
Are cleanbots able to target and clean these remains as well? Cleanbots spray acid on trash items, then clean the resulting goop.

**Comment by ShizCalev** [comment]
hng

**Comment by ShizCalev** [comment]
Actually I wasn't entire happy with it just getting qdel'd. It now turns into a puddle of green goo on the ground after being acid'd and gives a little feedback.

**Comment by AnturK** [comment]
Can't you just do it in acid_act ?

**Pull request merged**
