### PR TITLE
You can now buckle to bar stools

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request

https://github.com/user-attachments/assets/9184fc20-e114-42ff-b442-a491692a388b
## Why It's Good For The Game
Sitting with a pixel offset on bar stools will further the bar RP experience, it'll also show the barkeep that you're here to drink or talk.
## Changelog
:cl: grungussuss
add: You can now buckle to bar stools
/:cl:

### CODE REVIEW

**Comment by BumbertoEko** [comment]
someone finally did it thank you

**Comment by DrAmazing343** [comment]
it's peak. thank GOD finally.

**Comment by Sadboysuss** [comment]
> idea: shoving somebody off of one knocks them down, unbuckles them, and makes the stool into an item as when picked up and dropped.
> 
> great feature all the same

cool idea but then I'd need to do it to chairs as well so maybe another time

**Comment by Sakamoto4ka** [comment]
What about red chairs?

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
