### PR TITLE
Fixes improper static list declarations + adds grep for it

### PR DESCRIPTION
**Pull request by vinylspiders**
## About The Pull Request

I randomly came across a `var/list/static` in the code, which does not actually do what was intended, and thought it was silly. A ctrl+f revealed that this was a fairly common mistake, so I went and fixed all the instances of it I could find.

~~Including one in lighting code, which it looked like they were trying to create a global list to cache generated lighting sheet values for speed, but it was just a normal list that got created each time pointlessly. Now those values are actually being cached (using a global var, because a `static` list was not the right thing to use there in the first place).~~

Nevermind, it seems that this was in fact being cached even if it shouldn't have been, because byond. Just rearranged it there seeing as it works either way.

## Why It's Good For The Game

Code that does what it's supposed to

## Changelog

:cl:
fix: fixes a bunch of improper static list declarations
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Maybe lintable?

**Comment by LemonInTheDark** [comment]
> @LemonInTheDark would like your opinion on the caching of lighting sheets thing, yay/nay.

lmao
it's meant to be cached. I had it static to avoid people messing with the cache outside this proc, or admins fucking lighting up.
it is a useful learning tool though so I am ok with this change

**Comment by LemonInTheDark** [comment]
also I thought it was? it looked that way in profiles

**Comment by LemonInTheDark** [comment]
image
it always worked, though it should not have

**Comment by LemonInTheDark** [comment]
your understanding is wrong look at the printout

**Comment by san7890** [comment]
in case you need a list of statics

**Comment by LemonInTheDark** [comment]
> in case you need a list of statics

none tell him

**Pull request merged**
