### PR TITLE
AI uploads can no longer be printed from a circuit imprinter 2.0.

### PR DESCRIPTION
**Pull request by Zattarra**
## About The Pull Request
This PR simply prevents AI and cyborg uploads from being printed by circuit imprinters. (Redo of #73473)

## Why It's Good For The Game
Tiding into science to build a maints upload isn't particularly fun for the person tampering with the AI, the AI, and the crew. This change makes the existing boards actually important along with making the upload itself more relevant while making it tougher to tamper with / fix one of the station's most important assets. If every board is hidden or destroyed (a feat in itself) you could always go hit the AI core with law change modules as a last resort.

## Changelog
:cl:
add: Adds an extra upload board to the RD's locker.
del: Removes the ability to print AI and cyborg uploads from circuit imprinters
balance: Not allowing uploads to be printed changes the balance of this game.
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
Antag RDs are the one's onehumaning the AI most of the time though..

**Comment by ThePyroTechnician** [comment]
This is just going to result in a whole bunch of dead AIs when law changes can't be fixed because someone stole the boards.

**Comment by Ryusenshu** [comment]
(ill just copy what i wrote last time)

Absolutely Bad Idea

The only thing that makes this harder is FIXING an ai

**Comment by TheSmallBlue** [comment]
I actually kinda like this. Its true that its EXTREMELY easy for ANYONE to just tide into science, print two silly boards, and ruin the AI's entire round "Just cus'".
I've seen some people worry that if both the round-start upload and the extra board are gone, then the AI is fucked up forever. But you can always change the AI's laws by slapping boards on its core, so I think it's a good trade-off.

**Comment by TheSmallBlue** [comment]
OH do take it out of the RD's locker though, that's an awful idea, put it in like secure tech storage

**Comment by Ryusenshu** [comment]
> I actually kinda like this. Its true that its EXTREMELY easy for ANYONE to just tide into science, print two silly boards, and ruin the AI's entire round "Just cus'". I've seen some people worry that if both the round-start upload and the extra board are gone, then the AI is fucked up forever. But you can always change the AI's laws by slapping boards on its core, so I think it's a good trade-off.

to slap on the ai you have to get to the ai
fighting through the entire sat because some joker uploaded a one human from maint/solars is not very good

a subverted ai just wont let you go in there to fix them, they will likely kill to defend themselves

this pr is honestly such a backwards approach , better would be limits on upload locations , notice from where you got the law change and/or trackers on boards itself

**Comment by VladinXXV** [comment]
> OH do take it out of the RD's locker though, that's an awful idea, put it in like secure tech storage

There is already one in secure tech storage. If someone stole one from tech storage, you think they'll just leave the other there?

**Comment by TheSmallBlue** [comment]
> to slap on the ai you have to get to the ai fighting through the entire sat because some joker uploaded a one human from maint/solars is not very good
> 
> a subverted ai just wont let you go in there to fix them, they will likely kill to defend themselves

If an antag one-human'd the AI then I think its fair to fight through the core to un-do it. It's not that hard to be honest, you can just grab the reflective best and blamo all of the AI's protections are doneso, either that or just. shoot at the turrets. 
If an antag didn't one human the AI and its instead just a jokester doing jokester things they should get fucking banned and the AI should be reset by admins and the boards should get spawned back in, so that shouldn't be an issue

**Comment by MrrFiish** [comment]
> OH do take it out of the RD's locker though, that's an awful idea, put it in like secure tech storage

There already IS one in secure tech, this just adds a new one to RD locker. Maybe adding another somewhere else would be good but I have no clue where.

**Comment by Mothblocks** [comment]
I think this is a bad idea because I've had a significant amount of interesting rounds with AI uploads being publicly accessible, but somewhat out of the way. This limits it way too bad and would not improve the game. I'm still fine with one use upload boards

**Pull request closed without merging**
