### PR TITLE
Cover me I'm reverting

### PR DESCRIPTION
**Pull request by optimumtact**
**COVER ME I'M REVERTING**

Fixes #14059

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:
**DOWN-VOTING, WATCH MY BACK**

**Comment by optimumtact** [comment]
**INSULTING GOOF, BACK ME UP**

**Comment by Iamgoofball** [comment]
**DECLARING LOGICAL FALLACIES, CHECK YOUR CORNERS**

**Comment by Zilenan91** [comment]
**TOO MANY MEMES, FALL BACK!**

**Comment by Jalleo** [comment]
CALLING @KORPHAERON WE NEED BACKUP.

**Comment by Zilenan91** [comment]
DO THE * * MARK NO SPACE FOR **BOLDNESS!!**

**Comment by duncathan** [comment]
**COVER ME, I'M CLOSING**

**Comment by duncathan** [comment]
memes

**Comment by Lumipharon** [comment]
what, why are you closing this?

**Comment by Cheridan** [comment]
Combat formation bravo. Stay close to the walls.

**Comment by KorPhaeron** [comment]
**REINFORCEMENTS ARE ENROUTE, CLEAR THE LZ**

**Comment by Cheridan** [comment]
Tactical nuke incoming.

**Comment by Zilenan91** [comment]
**ENEMY AC130 ABOVE!**

**Comment by Lumipharon** [comment]
why are we closing fixes to literal IC meme spouting shit?

**Pull request closed without merging**
