### PR TITLE
Makes milo soup taste better

### PR DESCRIPTION
**Pull request by carshalash**
Miso soup is pretty decent, I had it with tiny clams in it once and it was really nice. 

:cl:
tweak: Removes the gross attribute of 'milo' soup
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
milo soup sounds pretty tasty too

**Comment by carshalash** [comment]
> milo soup sounds pretty tasty too, also is this pr serious?
> 
> This is milo soup, not miso

Milo soup is literally just miso soup but along the years someone changed the s to an L, I have no fucking idea why and its like this on every code base.

**Comment by optimumtact** [comment]
this is milo soup though

**Comment by MCterra10** [comment]
I concur, Milo is pretty great and tastes more nutty than vegetablely

**Comment by TheVekter** [comment]
Get his ass

**Comment by cacogen** [comment]
what sort of milo are you drinking it tastes like vegetables

**Comment by 81Denton** [comment]
What the fuck is a milo

**Comment by Ohagi-Chan** [comment]
I was thinking the Milo brand of powdered milk supplement.

**Comment by optimumtact** [comment]
I thought it was milo de venus

**Comment by carshalash** [comment]
Venus de milo soup contains no similarities to the ingredients in game for milo soup.

Also why the fuck did some melvin name it milo soup all those years ago?

**Pull request merged**
