### PR TITLE
Readds roundstart freon canisters

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#20382

The lag is fixed by the fix to the logging spam

### CODE REVIEW

**Comment by Kraseo** [comment]
It's not healthy to let an ocean make a bugfix, though.

**Comment by Iamgoofball** [comment]
# ITS FUCKING STUPID

**Comment by calzilla1** [comment]
Live by the speed merge, due by the speed merge

**Comment by FlavoredCactus** [comment]
It's a shame the PR title isn't in the commit message, would of been a nice addition to see on
https://twitter.com/gitlost

**Comment by Cheridan** [comment]
I don't have faith that your lag fix actually fixed the lag though.

**Comment by calzilla1** [comment]
#gooftotheshed2016AD let's make history people

**Comment by Archie700** [comment]
do we have a ban request for github

**Comment by FlavoredCactus** [comment]
@Archie700 I only browse this git for goofmemes though, what is tgstation without goofmemes?

@Cheridan excuse me of my ignorance because I haven't really kept up on GOOFGAS, the issue is that its lagging from many slips() adding the same log to logging.. if the logging for freon is disabled? the issue is solved?

**Comment by optimumtact** [comment]
I have cleaned this PR, pray I do not clean it further

**Comment by FlavoredCactus** [comment]
Goof put the pen down, you have so much to live for. So many memes unmemed.

**Comment by matillo** [comment]
Remove freon.

**Comment by Niknakflak** [comment]
posting in this for the record

**Comment by Dorsisdwarf** [comment]
:-1: 

fuck freon

**Comment by Chocobro** [comment]
i'm not sure why goof is surprised bad things happen when the majority of the time he's cursing somebody out on the internet

**Comment by AdamElTablawy** [comment]
i like freon though

**Comment by matillo** [comment]
that is a damned lie, nobody likes spacelube gas

**Comment by KorPhaeron** [comment]
Have you fixed it being impossible to get freon out of the mix tank yet?

**Comment by Iamgoofball** [comment]
It's not impossible. Set up a filter on the mix line filtering Freon.

**Comment by Wyzack** [comment]
I think we should have some sort of rule about adding new gasses that function as literally nothing but extra antag grief tools. I think that Freon (and also BZ) should have some use, however small. Also while i am sure Freon could have interesting traitor applications i have never seen anything other than basic boring hallway release that maybe kills a person but is otherwise just mildly inconvenient

**Comment by Iamgoofball** [comment]
So gaseous plasma isn't just a grief tool?

**Comment by matillo** [comment]
Plasma is used in what, every single engine? Freon in the halls is more deadly by quite a bit, plus it's really anti-fun being space lube. It also doesn't thaw when temperatures are restored AND will do stupid shit like freeze plasma fires solid. It literally trumps plasma.

**Comment by Wyzack** [comment]
Yeah Plasma is fuel for the engines, not to mention the station is a plasma research station, and not a station to research the merits of an ancient CFC gas outlawed for refrigeration use in the late 80s.

**Comment by Dorsisdwarf** [comment]
The Goof Ball doesn't use plasma though, because of goofball's plasma allergy

**Comment by Wyzack** [comment]
Also guess what FREON is a trademarked name for a series of chloroflurocarbon based gasses, if we readd it the Chemours Company might sue us!

**Comment by GunHog** [comment]
You need to remap Atmos to fully support Freon (a roundstart filtering tank like the rest of the gases). It is not a full implementation until you have done that.

**Comment by FlavoredCactus** [comment]
BZ too

**Comment by KorPhaeron** [comment]
Lets just remove BZ since it isnt mechanically or visually interesting like freon.

And we need to think of a better solution than "people can remodel atmos to deal with a roundstart gas otherwise the default method of gas removal (scrubbers) will instead poison the air"

But obviously having to remap 7 maps to have a bigger atmos isnt sustainable either

**Comment by Wyzack** [comment]
Yeah at least Freon does something new, BZ is just an easier to use mindbreaker toxin

**Comment by optimumtact** [comment]
Atmos does need a waste gas outlet with a filter, so you can choose to exhaust gases into space.

Also lets traitors drain things from the atmos loop

**Comment by Iamgoofball** [comment]
Yeah

**Comment by Dorsisdwarf** [comment]
>Yeah at least Freon does something new, BZ is just an easier to use mindbreaker toxin

@Wyzack And water vapor? It's literally a gas which spills a bunch of water on the floors constantly. Compared to, say, BZ, a gas that gives hallucinations to everyone nearby, and is hard to detect before you get the hallucinations. Not to mention the fact that BZ, being invisible, results in paranoia every time someone gets hallucinations.

**Comment by PKPenguin321** [comment]
"paranoia"
"clients crashing"

**Comment by Dorsisdwarf** [comment]
?

**Comment by PKPenguin321** [comment]
Nobody falls for most of the hallucinations and some people on the forums complained a while back that hallucinations caused their client to crash

**Comment by Iamgoofball** [comment]
so the problems with adding a new tank amount to "we dont have the room on all 7 maps"

i might be replacing the gas tanks entirely, however

**Comment by FlavoredCactus** [comment]
@Iamgoofball what do you have in mind specifically?

**Comment by Dorsisdwarf** [comment]
@PKPenguin321 I meant it introduces uncertainty into the _cause_ of the hallucinations. Is it a BZ flood, is it a changeling stinging you, did the chemist put space drugs in the food?

**Comment by PKPenguin321** [comment]
That is still kinda not true since air alarms will tell you that it is BZ 100% of the time and are in literally every room

**Comment by Dorsisdwarf** [comment]
Yeah but has anyone ever checked those before yelling "HELP LINGS" or "BZ IN AIR ATMOS ROGUE HELP"?

**Comment by KorPhaeron** [comment]
If you add a simple waste to space pipe I'll merge this and you can figure out a long term atmos remap later

**Comment by Iamgoofball** [comment]
alright, i'll do that in another PR tho cause this is just an automatic revert

**Comment by KorPhaeron** [comment]
Sure

**Comment by phil235** [comment]
whyyyyyyyyyy

**Comment by optimumtact** [comment]
Do you not feel the freeze phil baby?

**Comment by lzimann** [comment]
Lame meme gas

**Comment by optimumtact** [comment]
:sob:

**Comment by Iamgoofball** [comment]
mix to incinerator

**Pull request merged**
