### PR TITLE
Macros multi-z code, removes the false premise of manual offsets

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

[Removes the pretense of relative multiz levels](https://github.com/tgstation/tgstation/pull/76248/commits/0293fdc2bd8c8af7a0d18da33265e060789c71f7)

Our multiz system does not support having a z level that is only connected one way, or which goes down backwards or anything like that.

That's a fiction of the trait system, the actual backend has never really supported this.

This pr removes the assumptions we were making backend around this, and uses that to save cpu time.

I am also converting multiz_levels from an assoc list to a pure one, which saves significantly on access times and cleans up the code somewhat.

Also I'm making the get_below/get_above procs into macros, for the sake of cpu time.

[Converts the starlight disease to use BYOND's directional defines instead of our own](https://github.com/tgstation/tgstation/commit/7d698f02d991eb4e1bde56314c657cf6e48ceb5d)

To some extent spurred on by https://github.com/DaedalusDock/daedalusdock/pull/298, tho it was known before

## Why It's Good For The Game

Faster multiz code, faster init, etc etc etc

### CODE REVIEW

**Comment by Kapu1178** [comment]
Kevinz is satan (real)

**Comment by Maurukas** [comment]
>Our multiz system does not support having a z level that is only
>connected one way, or which goes down backwards or anything like that.

Well that explains why I could never get it to work.

**Comment by LemonInTheDark** [comment]
it's something I could in theory support with refactoring, is that something you'd want vire?

**Comment by Maurukas** [comment]
What I really want is complete control over both horizontal and vertical z-linkages. I want to be able to specify that any loaded z-level is adjacent to any other loaded z-level in the N/S/E/W/Up/Down direction.

**Pull request merged**
