### PR TITLE
Change +everything admin flag to not use ALL define

### PR DESCRIPTION
**Pull request by Jordie0608**
Bitwise operators changing to be 24 bit messes with admin ranks using `~0` as their max expected value as it's no longer `65535`. This broke headmins, hosts, gamemasters etc. checking for rights against another rank and the admin backup file because of byond's automatic conversion to scientific notation.

Now instead `+EVERYTHING` uses a define for the sum of all other admin permissions. At the end of the round ranks with `R_EVERYTHING` in any flag will now update the row's value to `R_EVERYTHING` if it doesn't match.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Wrong solution, please fix db ranks to handle 24 bit.

Mainly everywhere that hard codes a check for `65535` should be using the everything define.

**Comment by Jordie0608** [comment]
This is just a bandaid mostly for the sake of using with the bsql testmerges until I get to making a way to handle the max permissions changing update the db rank's values so we'll be safe if more flags ever get added.

**Comment by Jordie0608** [comment]
Got around to actually working on this; at the round of the round ranks with `R_EVERYTHING` in any flag will now update the row's value to `R_EVERYTHING` if it doesn't match. Not entirely confident in the backup file but loading and saving it worked when I was testing.

**Comment by optimumtact** [comment]
@Jordie0608 so it's ready now?

**Comment by Jordie0608** [comment]
Not stale, missed comment, is ready.

**Pull request merged**
