### PR TITLE
Silicons can play stock broker

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
tweak: AI's can now be your banker by manipulating the stock machine.
/:cl:

This is consistent with other machinery. AI's should be allowed to use / sabotage it.

This may be a fix, I don't even know.

### CODE REVIEW

**Comment by Armhulen** [comment]
THEY KNOW

**Comment by Iamgoofball** [comment]
:-1:

I intentionally didn't enable this because I didn't want AIs to completely take over cargo's job.

**Comment by ExcessiveUseOfCobblestone** [comment]
Law 2 stop touching my stocks.

Law 1 touching the stocks will put me in debt so I will starve and therefore die, please do not touch the darn stocks ai

**Comment by SgtxRootbeer** [comment]
gookbol, you forget, 90% of cargo is moving crates onto and off of the shuttle, the borgs and ai can operate the cargo console. hell, the mining borg can run cargo completely on their own, by mining the plasma for the points they need, and pulling the crates to whomever needs crates.

**Comment by bgobandit** [comment]
Does this log properly on the console

**Comment by ExcessiveUseOfCobblestone** [comment]
>Does this log properly on the console

It should

**Comment by ExcessiveUseOfCobblestone** [comment]
FUCK PARENTHESIS

**Comment by Haevacht** [comment]
A more descriptive title would be great, I expected romans.

**Comment by RandomMarine** [comment]
AIs generally have more pressing matters to deal with than fooling around with stocks @Iamgoofball

**Comment by coiax** [comment]
Can borgs also use stocks? If we're enabling AIs.

**Comment by ExcessiveUseOfCobblestone** [comment]
I kinda want to say they should be able to use them now if they're right beside it.

**Comment by ExcessiveUseOfCobblestone** [comment]
oh attack_ai and attack_robot are 2 different things.

ffs

**Pull request merged**
