### PR TITLE
Global Variables Subsystem

### PR DESCRIPTION
**Pull request by silicons**
Puts most of the globalvars onto a non-firing subsystem for varediting purposes.
By most I mean the ones that have any interest to admins, as in nothing that would present a security risk, or things that would irreversibly fuck up the game if edited and or things that won't really help in events when edited.

Most of this can be done via SDQL but this is for when people don't want to screw around with SDQL to select things.

tl;dr enables admin aboose

### CODE REVIEW

**Comment by kevinz000** [comment]
oh yeah i didn't test this yet so brb

**Comment by RemieRichards** [comment]
I don't support this.

**Comment by kevinz000** [comment]
What's wrong with it?

**Comment by RemieRichards** [comment]
Having to access an object for global variables is only acceptable in languages without real global variables.
Also, if you MUST do this, anything defined with ```/global``` is available as ```global.VARNAME```, so you should try to use that instead.

**Comment by kevinz000** [comment]
Uh, how would that be different than just using the name and a subsystem to keep track of it? What do you mean by using global.VARNAME? Like making the init portion of the subsystem use that instead of just its name?

**Comment by RemieRichards** [comment]
@kevinz000 I'm saying the idea of a global object to hold all global vars already exists, so you should try to use that instead, such as allowing VV to access the global object, as opposed to a whole new subsystem.

**Comment by kevinz000** [comment]
Things like the server comms key shouldn't be allowed to be accessed tho..

**Comment by XDTM** [comment]
wasn't global.varname the same as static.varname?

**Comment by RemieRichards** [comment]
@XDTM no because ```static.X``` is not a thing you can do, but barring that, functionality is largely the same.

**Pull request closed without merging**
