### PR TITLE
Fixes atmos techs being unable to open engineering storage

### LINKED ISSUE #64321: Door to room with lathe can't be opened by atmos techs on delta station
Reporting client version: 514.1569

## Round ID:
[177053](https://scrubby.melonmesa.com/round/177053)

## Reproduction:
The door to the lathe room in the new delta engineering layout can't be opened by atmospheric technicans

### PR DESCRIPTION
**Pull request by ReinaCoder**
## About The Pull Request
closes https://github.com/tgstation/tgstation/issues/64321
image
Deltastation engineering storage couldn't be opened by Atmos Techs. This is because it was set to 35 instead of 32, meaning it was hydroponics access instead of construction :D

## Why It's Good For The Game
Issues bad and atmos techs are supposed to have acccess.

## Changelog

:cl:
fix: Atmos Techs now have access to engineering storage on Deltastation
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
#64292

**Comment by ReinaCoder** [comment]
> #64292

THEY DIDN'T LINK THE ISSUE

**Comment by ReinaCoder** [comment]
My merge rate 😭

**Comment by MrMelbert** [comment]
ok well my pr was made before the issue so not my problem

**Pull request closed without merging**
