### PR TITLE
Adds proper armor for security plasmamen.

### PR DESCRIPTION
**Pull request by Helg2**
## About The Pull Request
It's kinda strange that security plasmamen has no proper armor and you can just bully them with bottlesmashes. Literally.
Also suits had no wound armor for some reason, which considering that mold dies without hand kinda silly too.
And helmets just had no armor besides 1 melee armor.
## Why It's Good For The Game
Plasmamen security won't die that easilly. I mean, still easy to kill them, but not that much.
## Changelog
:cl:
balance: Security Plasmamen now have Security armor. No bullying them with bottlesmashes anymore.
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
#58318 Gave better helmets for the Atmos/CE plasmamen so they don't need to swap their clothing to keep up with the job's standard protection.

Any security plasmamen haseasy access to swap their armorless clothing for the default armored version, this mostly lets them keep their plasmamen uniform on so medbay realize they can't be fully stripped, which end in round removal for most plasmamen that end up like that at medbay...

**Comment by moocowswag** [comment]
At the end of the day an armored plasmameme sec officer will be much worse off against someone who is using any decent amount of armor penetration so I dont see anything wrong with this pr.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
https://github.com/tgstation/tgstation/blob/54523c8e37522d71f8e97f15d7c84073b37eba5a/code/modules/clothing/head/jobs.dm#L182-L191

Please subtype from the respective sec armor datum so we

1) can visually tell whats being changed from normal HoS
2) do not have to change both values if we ever decide to mess with say hos melee for instance.

**Comment by ExcessiveUseOfCobblestone** [comment]
i just need to look at the det sprites you gave it to see if im ok with it looking like that but having det armor

**Comment by Helg2** [comment]
> i just need to look at the det sprites you gave it to see if im ok with it looking like that but having det armor

Maybe i should just make it subtype of white envirousit but dunno

**Comment by Helg2** [comment]
> 

It's used for bartender and psychologist.

**Pull request merged**
