### PR TITLE
Adds some antag alerts

### PR DESCRIPTION
**Pull request by Cuboos**
:cl: New Antag Alert sounds
soundadd: added sounds that alert players to their antag status 
soundadd: Blood cult has a new alert sound
soundadd: Clock cult has a new alert sound
soundadd: changeling has a new alert sound
soundadd: Malf/traitor AI has a new alert sound
soundadd: Nuke Ops has a new alert sound
soundadd: Ragin' Mages has a new alert sound
soundadd: Traitor has a new alert sound
/:cl:

This is a continuation of an old PR made by Paprika (this one #6301) that was canceled for various reasons.

Due to the nature of how antags are triggered this is mostly untested, i'd like to request a test merge to see if this works and gauge a reaction to the sounds from the player base. 

You can preview these sounds at this link: https://www.dropbox.com/sh/m9rqczkfvj1g0xf/AADHHy0czSu7MxJgLKOR3KAka?dl=0

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Please replace the clockcult alert with one fitting the description: "You hear the whooshing steam and clanking cogs of a billion billion machines."

**Comment by PKPenguin321** [comment]
Idk Joan I think it sort of already feels like that in a more abstract way. Literal "CLANK" spam would sound way worse. Plus it sounds really cool already

**Comment by Cuboos** [comment]
i can always count on PKPenguin to stand up for me

**Comment by ChangelingRain** [comment]
I hear no steam, no clanking cogs, only Ratvar.

**Comment by PKPenguin321** [comment]
Can we change the fluff message to "an overpowering, impossibly loud whirring of machinery" instead because the sound is good

**Comment by ChangelingRain** [comment]
That sound still isn't 'whirring'!

**Comment by Cuboos** [comment]
I honestly tried to find some cog sounds... but all i could find were sounds of cheap ass cuckoo clocks and shit.

**Comment by PKPenguin321** [comment]
I really think it's a good sound Joan

**Comment by Cuboos** [comment]
Yay! all checks passed!

**Comment by Dorsisdwarf** [comment]
Is it just me or is the bloodcult one crackly and saturated

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Like no seriously you've gotta make the clockcult sound something I like, and just using two of the existing ratvar sounds(ratvar_attack.ogg and ratvar_reveal.ogg) is not doing it.

**Comment by Cuboos** [comment]
@ChangelingRain why do i need to appease you specifically?

**Comment by Metacide** [comment]
I think the clockcult one sounds great, really. Rest seem broadly OK but the bloodcult one is a bit weird.

**Comment by ChangelingRain** [comment]
I maintain clockcult and have final say on changes to it that I'm not doing myself.

**Comment by Metacide** [comment]
Fair enough then. The raginmages one is also super piercing, I get that's part of the joke but ouch.

**Comment by Cuboos** [comment]
I'm going to need more than just ChangelingRain to justify changing the clock-cult sound, i'm getting more likes than dislikes towards it. Besides, this is a test PR anyway, it's suppose to be removed later once we figure out if it even works or not.

**Comment by Cuboos** [comment]
There, it's been changed, remove request please

**Comment by ChangelingRain** [comment]
Mocking me will not make me more amicable, you cuckoo.

**Comment by Cuboos** [comment]
Just for reference, this PR needs testing because testing most antags on my own isn't practical, a few of these are just place holders

Bloodcult, Changeling and Ragein' Mages are placeholders and will definitely be changed once we make sure this will work 

Nuke Ops is subject to change depending on if i can get in contact with the intended voice actor 

Malf will not be changed, this one has received the most amount of praise and a lot of people have already stated they want this particular sound 

Traitor may be changed if there is enough dislike for it.

That status of Clock Cult remains up in the air due to drama.

**Comment by Armhulen** [comment]
But i like the changeling one even though it will scare the shit out of SOME PEOPLE

**Comment by duncathan** [comment]
Joan is in charge of clock cult cuboos please listen to her

**Comment by Cuboos** [comment]
I did change it though, it says so in the third commit.

**Comment by lzimann** [comment]
are you still doing this

**Comment by Cuboos** [comment]
@lzimann yes, i just haven't had a chance to work on it, i should be able too later today.

**Comment by Iamgoofball** [comment]
@Cheridan can @ChangelingRain tell our only sound designer who is an expert on sounds to ignore their years of work on the subject and do their bidding about clockcult because I think the old one sounds better

**Comment by Iamgoofball** [comment]
also on that logic you could say I maintain chemistry but I don't get to veto people's PRs over it

**Comment by RemieRichards** [comment]
@Iamgoofball by that logic anyone who commissions some sound work must immediately accept the first version given to them, which is dumb and you know it.

**Comment by Armhulen** [comment]
Traitor is okay
Ling is good
Bloodcult is okay
clockcult is good
malf is great
ragin mages is bad
nuke ops is bad

**Comment by lzimann** [comment]
ping when you do the thing and want this reopen

**Comment by Cuboos** [comment]
@lzimann i'd like to reopen this please, i just finished with the updates

**Comment by Cuboos** [comment]
Hey @ChangelingRain is the new sound up to your standards?

**Comment by ChangelingRain** [comment]
since I can't listen right now, I'll answer that in the morning, when I can.

**Review by ChangelingRain — APPROVED** [review]

**Comment by ChangelingRain** [comment]
The clockcult one is good I have listened to none of the others have fun

**Comment by lzimann** [comment]
fuck sounds

**Pull request merged**
