### PR TITLE
Infiltration Gamemode

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Infiltration Gamemode
add: With infiltrators, 3-5 syndicate infiltrators, armed with stealth gear, are to infiltrate Space Station 13.
add: The current infiltrator-only objectives are: power stealing, kidnapping, or hijacking the AI.
/:cl:

# **Please keep this open, and allow the community to decide if they like it. Do not close it based on my past, I apologize for my former actions, I only wish to contribute now.**

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
I only wanna contribute, guys. Love ya'll, no matter how much you hate me. ❤️

**Comment by MoreRobustThanYou** [comment]
Fixing conflicts right now.

**Comment by 81Denton** [comment]
Hey man I loved your movie

adsasdadsda

**Comment by MoreRobustThanYou** [comment]
@81Denton that's actually pretty funny

**Pull request closed without merging**
