### PR TITLE
Fixes adamantine armour

### LINKED ISSUE #42555: Fireproofed jumpsuit from chill burns still
Issue reported from  Round ID: 100954 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

End of round, my fireproofed jumpsuit burnt off

### PR DESCRIPTION
**Pull request by 4dplanner**
## About The Pull Request
Adamantine armour sets flags_inv correctly

## Why It's Good For The Game
Stops a bunch of runtimes

## Changelog
:cl:
fix: adamantine armour no longer screws up clothing protection
/:cl:

### CODE REVIEW

**Comment by Shardj** [comment]
Ah sick, so that's what was causing it

**Comment by ExcessiveUseOfCobblestone** [comment]
NONE is 0 and it's not a list variable.

**Comment by Shardj** [comment]
Yeah I know about primative data types, I meant which bit of code takes flags_inv and fails when it's set to an empty list, vs why it then works when set to None.

**Comment by 4dplanner** [comment]
In check_obscured_slots the full coverage is built up by repeatedly ORing a value that will hold all covered slots with the coverage of the clothing (flags_inv). This crashes with adamantine armour because it can't or the total value, which is a number, with the flags_inv, which is a list

**Comment by 4dplanner** [comment]
I think this might be a multi-part bug, though, so still verifying fixing just this bit works.

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
