### PR TITLE
Resprites SpacePol Uniforms (And accessories)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Hello ancient sprite how u doin today :)
image

One de-souling later: [Long Scream - Sound Effect - Youtube](https://youtu.be/qWaGVtBEt4g?si=TZ_x6h3MFi1_efau)
image

---
Full and in-depth Changelist since there's a bit of random semi-related digging:
- Removes redundant `/datum/armor/warden_red` and strip_delay from `/obj/item/clothing/head/hats/warden/red` - the armor values were the exact same as those of `/datum/armor/hats_warden`, which it'd inherit anyways alongside the strip_delay
- Removes a comment I left forever ago when I re-did Trek uniforms. I never actually pushed the commit referenced by the comment. It's just been sitting there, lying to anybody who read it. _I know this is 100% unrelated to the PR but it was a comment I left that's a lie. I don't mean to lie D:_
- Gives the Mafia Warden outfit the red hat, to match the red jacket it wears
- Adds an extra pixel to the `spacepol` mask so it actually covers the nose on the side-state
- Resprites `spacepol` uniform
- Removes entirely unused `police` uniform obj icon_state
- Recolors `policehelm` hat to match the new palette
- Tweaks and Recolors `warden_alt` suit to match the new palette and have more consistent shading with the other warden jacket
## Why It's Good For The Game
WOOP WOOP ITS DA SOUNDA DA POLICE (Screenshot is slightly outdated, missing the new buttons, but it's still mostly accurate)
image
image

And since the Warden reuses that hat, his jacket's been tweaked to match it's tweaks. Along with shading adjustments to have less 'banding' as somebody on discord put it (idk spriting terms I assume that I fixed it)
image
## Changelog
:cl:
image: the SpacePol bounty hunters have finally had a new run of Uniforms made, bringing them back to the forefront of enforcement fashion! Wardens will find their Police Jackets/Hats have been updated match SpacePol's new look as well.
fix: fixed the Mafia Warden having a hat that didn't match his jacket, and fixed SpacePol masks not covering the nose
/:cl:

### CODE REVIEW

**Comment by OrionTheFox** [comment]
I think IconDiffBot threw a fit again :c

**Comment by atlasle** [comment]
keep the buttons!! it made them look like Nakategawaimage

**Comment by OrionTheFox** [comment]
> keep the buttons!! it made them look like Nakategawa

image
I'llllll come back to it tomorrow, might need a bit more tweaking bc it's hard to see them with the new shading AND the badge. T'was the main reason I didn't put them on it, but I definitely do wanna yea

**Comment by Wallemations** [comment]
Why did you do the warden change in the same PR as your sprite change? What does it have to do with spacepol?

**Comment by OrionTheFox** [comment]
> Why did you do the warden change in the same PR as your sprite change? What does it have to do with spacepol?

Warden's Police hat is the same item as the SpacePol hat (which i recolored), so to keep the Warden's police jacket consistent with the hat I kept it in the same PR

The redundant variables/mafia fix are just because I saw them on the warden jacket while I was already glancing over it - I can move those to another PR if needed

**Pull request merged**
