### PR TITLE
New Underwear

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

**Adds 3 new underwear options.**

- Men's Midway Boxers - slightly longer than the already in-game boxers
- Men's Long Johns
- Women's Halter Swimsuit

ftgtrgtrdh

## Why It's Good For The Game

More character customization good. Also the midway boxers and halter top will work well for the
upcoming summer ball.

## Changelog
:cl:
add: New underwear
imageadd: Midway Boxers, Long Johns, Halter Swimsuit
/:cl:

### CODE REVIEW

**Comment by Twaticus** [comment]
tlal STOP downvoting all my PRs NOW

**Comment by cacogen** [comment]
ok

**Comment by FantasticFwoosh** [comment]
Who has a summer ball in august? these are ok, sun's still out. All good.

**Comment by wesoda25** [comment]
i dont like how you named the commit undies twaticus

**Review by actioninja — APPROVED** [review]

**Comment by bigfatbananacyclops** [comment]
we arent on a beach

**Pull request merged**
