### PR TITLE
[WIP] Bureaucracy Mech

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

"when are we getting a company employee mech that has a built in paper bin, mech-powered pen, and copier that only breaks every other day?"
Now.

The mech itself is fast, not airtight, you can see the person inside, and the only things it can carry are, well, just see for yourself.

Ultra-pen 2000. any color, multiple fonts(i'll make sure this is possible when I look at it), and all that in any size.

Mecha-Paper fabricator 2000. You're gonna need a lot of paper for the job, and for a very small amount of power this mech can get that for you.

Mecha-ID interface. Switch IDs, print new IDs, all from the iron shell of your mech.

Mecha-stamp 2000. Okay do I really have to do this it's a stamp jesus

And a photocopier.

## Why It's Good For The Game

Bureaucracy hop is genuinely good gimmick and if you disagree you must be a greyshirt who wishes to turn the hopline into some kind of chaos lottery of access and debauchery.

Roboticists only get to mess with mechs early on if the miners want to waste time with a ripley they don't need or cargo wants to waste time with a mech they only need slightly more than the miners. This way, the hop can get themselves a giant hulking business suit mech to stamp shit and dispense paper (and order, across the lawless badlands that is the hallway, etc)

PS. will take sprites if you have them
todo:
- [ ] get all of the equipment coded and sprited
- [ ] get the mecha body parts
- [ ] move all of this into its own file
- [ ] ???
- [ ] profit!

## Changelog
:cl:
add: Bureaucracy mech Bureaucracy mech
/:cl:

### CODE REVIEW

**Comment by terranaut1** [comment]
If anybody uses ressources on this while I or anybody else is trying to build something useful I'm going to space them without saying a single word to them.

**Comment by HomocidlePancakes** [comment]
Ok. This is epic. We need a good name for this thing

**Comment by ATH1909** [comment]
I can't wait to slap a concealed weapons bay into this baby and scattershot people in style.

**Comment by HomocidlePancakes** [comment]
image

Liturally the definition of orange man bad

**Comment by necromanceranne** [comment]
Boo, this was funny. Even as just an Admin spawned mech.

**Comment by RaveRadbury** [comment]
Needs paper plane launcher

**Comment by tralezab** [comment]
@optimumtact could you reopen if I make it a ruin mech (on the crashed mech transport) so it doesnt become roboticist troll bait and is still fun space loot

**Comment by HomocidlePancakes** [comment]
He didn’t even bother to tell the reasoning behind his decision so no way this will be reopened

**Comment by tralezab** [comment]
i mean look at this pr, you gotta know going in this didn't have much of a chance

**Comment by PKPenguin321** [comment]
>still no botany mech

**Comment by RaveRadbury** [comment]
Yet we have assets for a botany bot and borg

**Pull request closed without merging**
