### PR TITLE
Mobile camera consoles, attempt 2

### PR DESCRIPTION
**Pull request by EvilJackCarver**
Trying this again, since the TGUI update from Denton got merged and I've finished what I wanted to before reopening a PR:

:cl: EvilJackCarver
add: NTNet has added a camera monitor to the modular consoles! You can now view cameras anywhere you want with your laptop, or on your modular console in Research without needing the board. (Sorry, tablet users, that excludes you.)
/:cl:

I'm also not that great with coding, so if you see something that you feel is a bit of a hack-together, it probably is and any suggestions on fixing that are more than welcome.

# Overview
Adds security camera monitoring to the list of programs on NTNet. You can now watch the armoury get raided from the comfort of your own porcelain throne, if that's the sort of thing that suits your fancy.

### Motion checks
There are a few checks, where you will automatically get kicked off the feed to deal with whatever you need to deal with, if certain situations arise:

* When **holding a laptop** in your hand: If you move, fall incapacitated or become blinded.
* When **using a computer that is stationary** such as a laptop on a table: If you move *out of range* of the computer, fall incapacitated or get blinded.
* If the **camera is cut**.

### Camera lists/details
* List screen shows on the button if the camera is active or not.
* You can filter by camera networks by going into "Help and Settings" > "Change Networks..." - the input expects a comma-separated list; **no spaces**, The default is `ss13,mine`.
  * This means you can filter only your secret camera network that Security probably can't see (but the AI probably can).
* The camera details screen shows the camera's location (vague area + coordinate location), status (online/cut), and active networks.

# Debugging information

* Calling the `force_error()` proc inside the camera console program will 'crash' it and kick anyone watching a camera out of it, as well as generate a runtime for the logs.

# Known issues/todo

- [x] ISSUE: The UI header icon for the camera monitoring program is a placeholder.
- [X] ISSUE: There will sometimes be a camera or two with a blank tag and no GPS coordinates; need to add a `if(c_tag)` check to the camera list rebuild code.
- [X] Add in code to allow someone to filter cameras by network (private camera networks, anyone?)
- [X] Make "Close Feed" button take you back to the camera list instead of the home menu
- [x] Add a note to the UI that cameras can be quickly searched by using Ctrl-F
- [x] Fix the comments in the console DM file 
- [ ] There might be an inherent performance issue in TGUI when trying to load lists that are 200+ entries long.

# Screenshots 
Everything past here is screenshots only.

## Main screen
grafik

## Camera list
grafik

## Camera details
grafik

## Viewing a feed
grafik

## 'Feed disconnected' screen
(AKA the screen you see if you get kicked off the feed)
grafik

## Help and Settings screen + "Change networks..." prompt
grafik

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
As someone who believes clunkiness does act as a balancing mechanic, I don't think we should purposefully add clunkiness to a feature to make it balanced.

Simply consider not adding the feature if that's the only sane way to curb its power.

**Comment by EvilJackCarver** [comment]
The only intentional clunkiness inside the program as it currently stands is the large filesize, and that's only to punish those who use the bare minimum components. Using an advanced wireless network adapter (whatever their in-game name is) over the bog standard NIC that tablets start with halves the time it takes.

(Using hardwired Ethernet over the bog standard wireless makes it go 4 times as fast, with the caveat that it wouldn't be mobile.)

**Comment by ExcessiveUseOfCobblestone** [comment]
So the click tetris to get to the actual feed is unintentional?

**Comment by ExcessiveUseOfCobblestone** [comment]
If you pick between coords or areas (I don't really think you need both for a "free" app) you can just append it to the names on the second image.

**Comment by ExcessiveUseOfCobblestone** [comment]
Personally I don't understand the benefit of giving them area/coords and, if such information was actually beneficial, it should also be sabotagable in some way.

Even the dedicated computer console doesn't have that information, why does the mobile app need it?

**Comment by EvilJackCarver** [comment]
The only benefits the coordinates have are coincidental; mainly for conversion antagonists wanting to cut all cameras in a certain area to see if they missed one and where it is.

The area information isn't absolutely necessary, but during testing I noticed there were non-autoname cameras in the camera_list and put it on the list in the event that the area name didn't match the camera name (e.g. mining).

That information isn't strictly *necessary*, but helpful to have and helps balance against the inherent clunkiness of having to use TGUI + the added clunkiness of the menus as they stand right now.

**Comment by GunHog** [comment]
This makes me wish that the mini-map stuff worked properly. You could just click on the spot you wanted to view, and the UI would show you the camera closest to that spot.

**Comment by EvilJackCarver** [comment]
grafik

@ExcessiveUseOfCobblestone thoughts?

**Comment by ExcessiveUseOfCobblestone** [comment]
That's nice actually

**Comment by EvilJackCarver** [comment]
I'll commit it when I get back home

---
~ G. A. WILMBROKE

On mobile; typos are my own.

**Comment by EvilJackCarver** [comment]
@ExcessiveUseOfCobblestone re: your edit: I don't know about right-aligning the name, but the brackets I can certainly do. I only did them because of the new-player-options screen has it as [ Ready | Not Ready | Observe].

I'll remove the brackets, compile, then commit changes.

**Comment by ExcessiveUseOfCobblestone** [comment]
The second one looks rad af.

I was thinking right-aligning not to the screen but relative to the longest name, but that left align looks just as nice if not better!

**Comment by JStheguy** [comment]
>(Using hardwired Ethernet over the bog standard wireless makes it go 4 times as fast, with the caveat that it wouldn't be mobile.)
Actually, couldn't you use a data disk to transfer to program over to a laptop from a computer?

**Comment by ShizCalev** [comment]
Left align, no brackets.

**Comment by EvilJackCarver** [comment]
That's the version that is committed, yes

---
~ G. A. WILMBROKE

On mobile; typos are my own.

**Pull request closed without merging**
