### PR TITLE
The Cratening: Several crates for several corps!

### PR DESCRIPTION
**Pull request by YesterdaysPromise**
## About The Pull Request

Originally wanted to include those with syndicate-corp themed gear for nukies, but... I think this might be an useful thing for mappers in general, and with the wallening hitting, I reckon they will be going around stuff a lot, so!

most of them pictured!
Interdyne 1

## Why It's Good For The Game

Adds representation of several lesser known corporations and a nice touch of flavour to add to places for mappers!

## Changelog

:cl:
add: Added crates of the following varieties; Interdyne, Interdyne freezer, Tiger Co-Op, S.E.L.F. MI13, A.R.C., Cybersun (4 colour variants), Waffle Corp, Donk, Gorlex, Gorlex weapons, DeForest, Nakamure Engineeing, Robust Industries
/:cl:

### CODE REVIEW

**Comment by DaCoolBoss** [comment]
Some designs are a little too busy (gorlex green/white, tiger & SELF especially) and it's a little weird for MI13 and SELF to have their own branded crates, but overall most of this looks great. Only real reccomendation is any decoarations on the "front" side of the crate should be either very simple or functional, so snip stuff like the snakes but keep the stripes and initials. That's mostly where the busyness is coming from.

**Comment by TheVekter** [comment]
> Some designs are a little too busy (gorlex green/white, tiger & SELF especially) and it's a little weird for MI13 and SELF to have their own branded crates, but overall most of this looks great. Only real reccomendation is any decoarations on the "front" side of the crate should be either very simple or functional, so snip stuff like the snakes but keep the stripes and initials. That's mostly where the busyness is coming from.

I agree about the initials, hard disagree about the snakes. The Gorlex crate fucks _severely_.

**Comment by Dawnseer** [comment]
Finally, some S.E.L.F representation

**Comment by gorillion** [comment]
could these spawn for syndicate surplus kits, changing depending on what "type" of traitor you got?

**Comment by Twaticus** [comment]
is there a place to read the lore for these random corporations cause none of these seem necessary and i dont really like these in general so unless theres a really good reason to add 30+ sprites that will rarely be used then yknow..............

**Comment by YesterdaysPromise** [comment]
> is there a place to read the lore for these random corporations cause none of these seem necessary and i dont really like these in general so unless theres a really good reason to add 30+ sprites that will rarely be used then yknow..............

Yes. It's called https://github.com/tgstation/common_core

**Comment by YesterdaysPromise** [comment]
> Some designs are a little too busy (gorlex green/white, tiger & SELF especially) and it's a little weird for MI13 and SELF to have their own branded crates, but overall most of this looks great. Only real reccomendation is any decoarations on the "front" side of the crate should be either very simple or functional, so snip stuff like the snakes but keep the stripes and initials. That's mostly where the busyness is coming from.

Tiger Co-Op is meant to feel bit over-designed, they are religious nutjobs. SELF I imagine is as, sure, they don't really have their own tech exactly, but it's kinda like with furries, where a lot of them are suspicously rich and keen to comission techy gadgets. Spy equipement for MI13 agents has to come in something you know; its the only crate of these without a logo or the name on it, though, to maintain bit of stealth. The snakes and the dog on the ARC crate extend to the bottom bit of the crate so they can be readable; don't think I can really remove them from there without removing them from the whole crate.

**Comment by Wallemations** [comment]
Are these just for mapping or are they used anywhere else?

**Comment by YesterdaysPromise** [comment]
> Are these just for mapping or are they used anywhere else?

I added a couple to cargo where it made sense, like DeForest surgery tray now actually comes in DeForest tray. I also plan to use them later for special corp themed nukie bundles.

**Review by Wallemations — APPROVED** [review]
Sounds good

**Comment by Wallemations** [comment]
There's a bunch of map changes so idk if I'm allowed to merge this or not

**Comment by YesterdaysPromise** [comment]
> There's a bunch of map changes so idk if I'm allowed to merge this or not

the map changes in question are just swapping one crate variant for another

**Review by ArcaneMusic — APPROVED** [review]
Fine for now but I reserve the right to re-assess about the crate types that don't show up in regular gameplay

**Pull request merged**
