### PR TITLE
Links to the round on atlanta's site in the issue template

### PR DESCRIPTION
**Pull request by Cyberboss**
Helps people find what they're looking for

@nfreader

### CODE REVIEW

**Comment by nfreader** [comment]
Looks good to me. I might change the URL scheme at some point in the future, but I'll try to make sure that all of these old links get caught and redirect properly.

**Comment by optimumtact** [comment]
We are technically independent (I know) and we shouldn't bless any one implementation, not sure about this

**Comment by nfreader** [comment]
Oranges makes a good point as well. Perhaps this isn't such a good choice? Or maybe some of the statbus functionality can be rolled into the tgstation13.org website code itself?

**Comment by lzimann** [comment]
Nothing against ned's website but we really should avoid any third party linking, so I am not really a fan of this.

**Pull request closed without merging**
