### PR TITLE
redpills metastation

### PR DESCRIPTION
**Pull request by pudl**

### CODE REVIEW

**Comment by GunHog** [comment]
You need to provide a description and a screenshot of what you changed.

**Comment by Bawhoppen** [comment]
its literally the rules

**Comment by KorPhaeron** [comment]
@metacide your call

**Comment by Cheridan** [comment]
12:23 AM - pudl: its actually a fix
12:23 AM - pudl: whenever metastation's xenobio was moved over for the shuttle
12:23 AM - pudl: by accident the bottom left cell was made 2x3
12:24 AM - pudl: instead of 2x2
12:24 AM - pudl: i mean
12:24 AM - pudl: 3x3
12:24 AM - pudl: so i changed it to 3x3 again

**Comment by KorPhaeron** [comment]
@Cheridan 

Please stop metacomms

**Comment by coiax** [comment]
That wasn't an accident, I squashed the cell on purpose to expand the dock size.

**Pull request closed without merging**
