### PR TITLE
Fix message appearing when attempting to enter disposals while restrained

### LINKED ISSUE #30336: You can't climb into the disposal unit while restrained.
title.

If this is on purpose then don't close this as there is a consistency issue too. When you attempt to climb into the unit it'll say "You start climbing into the disposal unit..." yet there's no progress bar and you pretty much do nothing.

yes this is an i ded

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #30336

### CODE REVIEW

**Comment by XDTM** [comment]
You're supposed to be able to jump in them while cuffed though

**Comment by Bluespace** [comment]
^
Have multiple memories of escaping in bins.

**Comment by AnturK** [comment]
I agree this is pretty standard method of escape when cuffed, the issue goes the other way.

**Comment by KorPhaeron** [comment]
@AnturK 

Is there any simple way to override the do_after failing on handcuffed?

**Comment by KorPhaeron** [comment]
If someone wants to figure out how to re-add getting into disposals with handcuffs on that'd be desirable but until someone does we may as well not have the message appear

**Comment by AnturK** [comment]
Not right now, should be trivial to add. (Also with the amount of arguments do after has some docstring would be nice)

**Pull request closed without merging**
