### PR TITLE
Add cockroach guts to cleanbot target list

### LINKED ISSUE #14140: roach guts can't be cleaned by cleanbot or cleaning foam

### PR DESCRIPTION
**Pull request by optimumtact**
whitelists are such a meme

fixes #14140

### CODE REVIEW

**Comment by GunHog** [comment]
Roaches are decals? Huh

**Comment by optimumtact** [comment]
No their remains are

**Comment by swankcookie** [comment]
Is there a reason that it doesn't just clean all /decal/ children?

**Comment by optimumtact** [comment]
there's probably a decal on a wall that it get's stuck targeting or something

**Comment by swankcookie** [comment]
I think I'm just gonna run a test on that. Whitelisting is the bane of feature addition.

**Comment by AnturK** [comment]
Cleanbots have exclusion list for decals they can't reach to and they don't try to repath like other bots, so it shouldn't be an issue

**Comment by phil235** [comment]
This fixes 14140 entirely since the rest of the issue was a misunderstanding.

**Comment by tkdrg** [comment]
I guess I'll just merge this and if @swankcookie finds out that the whitelist can be removed then he can make another PR.

**Comment by swankcookie** [comment]
will do

**Pull request merged**
