### PR TITLE
Adds canned laughter

### PR DESCRIPTION
**Pull request by PKPenguin321**
**[Check out the educational video!](https://www.youtube.com/watch?v=uLeNHUgZJ8g)**

Adds canned laughter, an item the clown starts with in his backpack. It contains 50 units of Laughter, a chemical that instantly metabolizes once inside you that makes you laugh (I recommend watching the video if you wanna see what this is like).

_Known issues:_
- [x] I need to find where the sprites for crushed cans are stored, and make one for Canned Laughter
- [x] Laughter reagent should be pink or something, not black

~~Maybe todo:~~
- ~~Make an adminspawnable clustergrenade that fires laughing gas~~

:cl: PKPenguin321
add: Added Canned Laughter for the clown. Hehehe
/:cl:

Merge Token: https://github.com/tgstation/tgstation/pull/18550
Sounds are all from Freesound.org and are good to use. Find them [HERE](https://www.freesound.org/people/sagetyrtle/sounds/44884/) and [HERE.](https://www.freesound.org/people/MentalSanityOff/sounds/218308/)

### CODE REVIEW

**Comment by optimumtact** [comment]
Slightly terrifying

**Comment by Giacom** [comment]
I looked at the FreeSound.org links and I noticed the [last link](https://www.freesound.org/people/Ch0cchi/sounds/15288/) you have to give credit.

[Here's the requirements](https://creativecommons.org/licenses/by/3.0/)

**Comment by PKPenguin321** [comment]
Actually, I just remembered I never actually used that sound. I was going to originally but it was much too quiet when I actually tested it, so I removed it.

>Slightly terrifying

As clowns generally are.

**Comment by Metacide** [comment]
Looks delightful. :+1:

**Comment by Fox-McCloud** [comment]
I...what.

**Comment by GunHog** [comment]
Also known as the portable audience bomb. Probably the only laughs most clown players will ever get! :+1:

**Comment by tedward1337** [comment]
Yes. Make an admin spawnable laughter grenade please
P l e a s e

**Comment by RemieRichards** [comment]
:+1:

**Comment by PKPenguin321** [comment]
So I looked into making the cluster bomb, I got some code down but unfortunately it's not working quite right and making custom smoke grenades with code is surprisingly difficult. I think I'll save it for another PR, so that it doesn't hold this one back.

**Comment by GunHog** [comment]
Future feature request for PKP after this one is merged: Make *laugh emote for humans also have sounds!

**Comment by PKPenguin321** [comment]
I considered that, but I imagine it would have the same problem that screaming having a sound would, in that it would be spammed all the time

**Comment by AnturK** [comment]
Is this ready for merge or still want to add something ?

**Comment by PKPenguin321** [comment]
It's good to go

**Comment by demonfiren** [comment]
Tell me this stuff can be mixed.

**Comment by PKPenguin321** [comment]
no, but making it mixable shouldn't be too hard. i don't know what the ingredients should be though

**Comment by demonfiren** [comment]
Colourful reagent, lube and banana juice.

**Comment by jughu** [comment]
+ salt

**Pull request merged**
