### PR TITLE
fixes distro on metastation

### LINKED ISSUE #59293: MetaStation air loop is missing some pipes
Reporting client version: 514.1554

## Round ID:
[162847](https://scrubby.melonmesa.com/round/162847)

## Testmerges:
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)
- [Integrated Circuits (Wiremod)](https://www.github.com/tgstation/tgstation/pull/59232)

## Reproduction:

There are a few pipes missing in the northeast corner of MetaStation's atmos (underneath the windows) that mean air is not going into distro by default. This means there's no air in the pipes to refill rooms with.

### PR DESCRIPTION
**Pull request by Red-byte3D**
## About The Pull Request
fixes: #59293
## Why It's Good For The Game
bugfix
## Changelog
:cl:
fix: Metastation's supply is now linked properly
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
I feel like this doesn't fix the issue

**Comment by InsaneRed** [comment]
> 
> I feel like this doesn't fix the issue

im pretty sure its fixed i removed the cyan pipes for smart 4w pipes

**Comment by InsaneRed** [comment]
image

**Comment by InsaneRed** [comment]
nope you were right for some reason we have 50 diffrent types of pipes

**Comment by InsaneRed** [comment]
its properly fixed now 👍

**Comment by Ghilker** [comment]
Please use the directional sprites to show the behaviour of the pipes and not the 4w ones

**Comment by InsaneRed** [comment]
the man who caused the bug fixed it

**Comment by InsaneRed** [comment]
> the man who caused the bug fixed it

nevermind he did not

**Pull request closed without merging**
