### PR TITLE
Modular computers' UI overlay variable addition (I reappeared edition)

### PR DESCRIPTION
**Pull request by Stalkeros2**
## About The Pull Request
Adds a new variable icon_overlays that, if set, replaces the modular computers' overlays with the ones from a different file; if not, defaults to the initial icon file's overlays.
Readjusts some of the update_overlays proc code to better accommodate the change, and by the requests splits program overlays (and modular computer overlays in general) into different files.
## Why It's Good For The Game
Makes it easier for admins, players and downstreams (see: removes the sheer amount of needless copypasted screen states like the image below) to implement custom modular computers.
image
Like, really, this is horrible. :(
## Changelog
:cl: Stalkeros
code: Modular computer overlays' can now be properly edited.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
oh for fucks sake

**Comment by SyncIt21** [comment]
Did you address @JohnFulpWillard request https://github.com/tgstation/tgstation/pull/78463#pullrequestreview-1639350927  in the previous PR?

**Comment by Stalkeros2** [comment]
> Did you address @JohnFulpWillard request [#78463 (review)](https://github.com/tgstation/tgstation/pull/78463#pullrequestreview-1639350927) in the previous PR?

Unless I've terribly misinterpreted it, -and I doubt that "split [item] file into different [item] screen files" can be-, I did.

**Comment by Stalkeros2** [comment]
Actually, it'll be way easier for me to just *not* add a PDA downstream.

**Pull request closed without merging**
