### PR TITLE
Cyborg Blueprints

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
So engineering cyborgs can do fun blueprint related things like name all the main halls DICKS

:cl: Kor
rscadd: Engineering cyborgs now have internal blueprints.
/:cl:

### CODE REVIEW

**Comment by RandomMarine** [comment]
[Security] Officer Beepsky says, "Arresting level 6 scumbag Assistant McGriefpants in GREAT HALL OF DICKS."

**Comment by bgobandit** [comment]
so if a traitor gets borged and goes engi can they still greentext

**Comment by coiax** [comment]
@bgobandit how? They'd still count as dead for survive, and would have to have the steal blueprints objective, and I'm not even sure if they're part of the inventory of the cyborg

**Comment by KorPhaeron** [comment]
They actually do count as stealing the blueprints yeah.

I mean they're dead so they won't win, but they'll have finished that objective.

**Comment by RemieRichards** [comment]
This also lets them see the blueprint layout to fix better :+1:

**Comment by bgobandit** [comment]
if a traitor has steal the blueprints and die a glorious death they can do it

**Comment by Supermichael777** [comment]
That should never hapen

**Comment by Zilenan91** [comment]
This also lets the cyborg set the name of every room to Xenobiology Lab so that xenobiologists can spew slimes all across the station :+1:

**Comment by Iamgoofball** [comment]
@bgobandit whats the problem here?

**Comment by RandomMarine** [comment]
@bgobandit Cyborgification does not count for dying a glorious death.

**Pull request merged**
