### PR TITLE
Swag outfit added

### PR DESCRIPTION
**Pull request by c420-o**
## About The Pull Request

This Pull Request adds an o̶v̶e̶r̶p̶r̶i̶c̶e̶d̶ lavish Swag outfit along with a pair of baller Swag Shoes to go with it. They can be found in the clothesmate premium section, the perfect outfit for any spessman lacking in the style department.

image
image

Swag Shoes sprited by TWATICUS#0784
Swag Outfit sprited by Dawson#8115
Coded by Jimmy the Suicidal Maniac#3652

## Why It's Good For The Game

Now anyone can secure some bitches. Better yet, maybe the admin will PM your hot ass and stop fuckin' with whatever nukie or captain they're PMing. Also happens to look really cool.

## Changelog
🆑
add: swag outfit available in clothesmate
add: swag shoes availble in clothesmate
resprite: changed swag shoes icon to the one twaticus made.

/🆑

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
them's some fresh kicks doe

**Comment by Fikou** [comment]
shouldnt this be a suit? it will probably cause weird overlapping sprite issues as a jumpsuit

**Comment by Qustinnus** [comment]
isn't this meme dead already?

**Comment by dawsonkeyes** [comment]
> shouldnt this be a suit? it will probably cause weird overlapping sprite issues as a jumpsuit
might, but it's got no inherent armor and will be properly hidden by anything like hardsuits or spacesuits

**Comment by Investigator77** [comment]
Speedmerge this holy fuck best PR since Lavaland.

**Comment by itseasytosee** [comment]
I hate this meme but this is brilliant.

**Comment by Nistishere** [comment]
Nice drip

**Comment by maxymax13** [comment]
> 
> 
> isn't this meme dead already?

memes are best immortalized in the game when dead, see: crazy hamburger

**Comment by D4C-420** [comment]
> isn't this meme dead already?

> > memes are best immortalized in the game when already dead, see: crazy hamburger
also see gondola.

**Comment by Qustinnus** [comment]
the difference is that gondola's stay marginally funny and have a long shelf life, while this meme has about as much memorability as the average meme on tiktok

**Comment by c420-o** [comment]
> the difference is that gondola's stay marginally funny and have a long shelf life, while this meme has about as much memorability as the average meme on tiktok

Everyone make way for the meme magistrate

**Comment by bluetshirtguy** [comment]
this meme sucks

**Comment by Low3** [comment]
Bad, overused meme, not epic.

**Comment by interestingusernam3** [comment]
>isn't this meme dead already?

>memes are best immortalized in the game when already dead

Reddit

**Comment by Fikou** [comment]
> > shouldnt this be a suit? it will probably cause weird overlapping sprite issues as a jumpsuit
> 
> might, but it's got no inherent armor and will be properly hidden by anything like hardsuits or spacesuits

its thicker than all jumpsuit sprites in the game though, and spacesuits and hardsuits arent the only thing in suit slot

**Comment by cacogen** [comment]
Those naked women signal braindead to me which I'm assuming wasn't your intention

**Comment by ShibaInuLord** [comment]
gondolas are based, this is not

**Comment by Twaticus** [comment]
silly overpriced cosmetics to spend money on is good 👍

**Comment by Twaticus** [comment]
the shoes werent doing it for me, would you be interested in these?
image

**Comment by optimumtact** [comment]
drippin oranges
certified fresh PR

**Comment by c420-o** [comment]
> the shoes werent doing it for me, would you be interested in these?
> image

Just added them. they look great! Thank you, TWATICUS!

**Comment by 2Lucky-Luther** [comment]
> isn't this meme dead already?

it just seems like an expensive item assistants to work toward. in conjunction with the spacepods it could be a fun goal for an assistant.

**Comment by LemonInTheDark** [comment]
I don't like this, but I think oranges will beat me to death if I close it

**Comment by Krysonism** [comment]
I like have more fancy clothing options.

**Comment by notfrying1pans** [comment]
Drip Station 13

**Comment by dawsonkeyes** [comment]
and so the drip that cheated death on reddit cheated death once again, and /tg/station was forever changed

**Comment by maxymax13** [comment]
success

**Comment by Low3** [comment]
This memery got merged, but my book fix is still ignored. God hecking damnit

**Comment by maxymax13** [comment]
i'm pretty sure there being a transparent hole for the hand is not how jumpsuit sprites are supposed to work, this will just look stupid for anyone with no arms/differently shaped arms

**Pull request merged**
