### PR TITLE
Upstream fix

### PR DESCRIPTION
**Pull request by Pyko1**
The files from upstream mirror https://github.com/HippieStation/HippieStation/pull/6002#issuecomment-358724201 with less conflicts.

### CODE REVIEW

**Comment by praisenarsie** [comment]
nice job pyko

**Comment by Pyko1** [comment]
opps wrong repo

**Comment by Pyko1** [comment]
Even tho hippie becaming the upstream would solve so many issues :3

**Comment by ninjanomnom** [comment]
Except we don't want hippie's shit so good luck on that one

**Pull request closed without merging**
