### PR TITLE
Adds a new BEPIS Major Reward, "Australicus Security Protocols"

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

This adds in a new BEPIS major reward tech, called Australicus Security Protocols. The tech contains 2 new-ish items. First one is the OZtek Boomerang, formerly known as the SCAM boomerang from my first feature PR [here](https://github.com/tgstation/tgstation/pull/43477) (#43477). It works off of the same boomerang effect from the bananium shield, but on hit it applies a stunbaton hit. The version from the original PR was coded before the stun/stamina rework, but I've retooled it to work with the new stamina damage batons deal. The most important feature here is that by using this, you're turning your stunbaton into a thrown ranged weapon, and can be caught not only by yourself, but also by the person you're trying to stun, in addition to the possibility of hitting yourself, because it's a boomerang. High risk high reward.

Second item is another item originally from another PR, the Outback Firing Pin, which was originally the Explorer's Firing Pin from [this](https://github.com/tgstation/tgstation/pull/48011) PR (#48011), with permission given by EOB. As a firing pin, it works only while off the station's Z-Level, but that gives security a way to print and hand out guns to crew without the worry that they'll start world war 3 in cargo ~~before they buy a firing pin crate anyway~~.  Plus, it benefits gearing crew up for away missions, ruins, megafauna, ya know, exploration stuff.

Also, before anyone asks, "Australicus Sector" is the name on the gold slime spider item, so I'm working off established lore.

image

## Why It's Good For The Game

For the boomerangs, I liked the original idea, and from the (Brief) testmerge it had last year during april fools, it was actually quite fun to use, plus it gave an interesting amount of counterplay to and against security. If used aggressively and with excellent timing, you can quickly baton a room full of people within medium range, but one false step and you'll stun yourself just as easily. Keeping in mind that a single baton hit is only enough to force you to crawl, it works well as a late-game alternative to the stunbaton, as long as you get the hang of its usage.

For the Outback Firing Pin, I know from my experience that arming the crew for threats/events/what have you is always a daunting task, because the moment you say that the armory/seclathe items are fair game, even if it's for an admin event or an away mission, you are NEVER getting those guns back. Firing pins give security that extra edge at keeping order, and mindshield pins do an excellent job of that, but this would incentivize security to consider arming the crew more often if the opportunity presents itself.

## Changelog
:cl:
add: A new technology has been implemented into the B.E.P.I.S, Australicus Security Protocols, after our lab boys cracked open a cold one with those mates from a couple sectors south.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
Let's fucking expand on this australicus lore that I shat out while drunk hell yea

**Comment by MCterra10** [comment]
AuStation gang approves this PR

**Comment by Arathianen** [comment]
As a spiderlover, I need Australicus to be so embedded in the lore that removing my spoders would be like removing the clown, so I approve :^)

**Comment by necromanceranne** [comment]
AUSTRALICUS AUSTRALICUS AUSTRALICUS

WHERE'S MY SPACE JIM BEAN?

**Comment by GuyonBroadway** [comment]
Each point in Australicus tech adds %10 to the length of the VB bottle neck.

**Comment by AdamElTablawy** [comment]
boomerang should also damage giant spiders

**Pull request merged**
