### PR TITLE
Virus healing symptoms work on slimepeople

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Virus healing symptoms' tox healing is now forced, so it works on slimepeople.

## Why It's Good For The Game

I think it's unreasonable to damage a player for a virus they most likely did not willingly recieve. I also think it's unhelpful to blame the Virologist, or put any amount of blame on them if they decided to spread a 100% beneficial no-drawbacks virus. I don't think that adds anything to the game.

Also, plasma fixation hurts slimes? Huh? Come on.

## Changelog

:cl:
qol: Virus healing symptoms' tox healing is now forced, so it works on slimepeople.
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
There was a pr that tried this in the past I believe it was timberpoes that said that "if its not intended before it is now"


But at the end of the day its an admin/policy headache since you are pretty much given a right to lynch someone for making a virus self spreads and can kill you.

**Comment by HalfPunch** [comment]
> 100% beneficial

100% beneficial - kills xenobiologists. Now that is a benefit

**Comment by CRITAWAKETS** [comment]
atleast plasma fixation should have it be forced healing, it's a bit strange how the plasma symptom kills slimepeople

**Comment by deathrobotpunch** [comment]
> It's actually not. It remove plasma from your blood stream and lungs. Slimepeople heal from plasma and gain blood volume, so it's logicaly acurate that they take damage from it. Atleast for me. But i really hate when viros make their "OmG nO dRaWbAcK gOoD vIrUs. LeTs SpReAd It!!!11)))0" and then you die

well what do you want them to do spread a harmful virus to heal slime people only? if you are deciding to be a slime person just ask the virologist to create a vaccine before they release a helpful virus because most rounds people do not decide to be slime people.

**Comment by san7890** [comment]
> I think it's unreasonable to damage a player for a virus they most likely did not willingly recieve.

then what's the point of any virus? i think the person who injects the slime gene into themselves should realize that other players can fuck them up once they assume that negative race trait.

**Comment by moocowswag** [comment]
> can you find a link to this PR

It took me like 20 minutes to find it apparently it was mothblocks  #60627

**Comment by Mothblocks** [comment]
i agree with me from 2 years agoi guess

**Pull request closed without merging**
