### PR TITLE
Halloween tile decals

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Adds orange and black tile decals for the Halloween holiday.

<details>
<summary>Screenshot</summary>
  
image

image

</details>

## Why It's Good For The Game

It's Halloween, compliment the visual filter recently added to the holiday.

## Changelog

:cl: LT3
image: Added Halloween themed floor/tram tiles
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I dunno

**Comment by Wallemations** [comment]
I'll be honest I can barely see them lmao

Also you said "and black" but I only see orange

**Comment by lessthnthree** [comment]
COLOR_DARK could be a bit darker. Changed.

https://user-images.githubusercontent.com/83487515/276858044-36ac0d48-fe89-4f15-b9f7-bc55cb0f0de1.png

https://user-images.githubusercontent.com/83487515/276858751-fa409d3e-004e-45e3-97b3-05f9244fbf13.png

**Comment by san7890** [comment]
i'll go bananas if someone makes a "lively" color filter and makes all of the tiles on the station red, green, and white for Christmas but Halloween is such a buggy clusterfuck time of year that i think it's okay to just futz around super hard.

**Comment by lessthnthree** [comment]
> i'll go bananas if someone makes a "lively" color filter and makes all of the tiles on the station red, green, and white for Christmas but Halloween is such a buggy clusterfuck time of year that i think it's okay to just futz around super hard.

Yeah I am going to look at Christmas, see how it looks without the filter and go from there.

**Pull request merged**
