### PR TITLE
Optimize GIF and PNG images

### PR DESCRIPTION
**Pull request by celotajstg**
## About The Pull Request

Decided to try optimizing the GIF and PNG images in the repository with gifsicle and tinypng, and had some pretty good results. The changes are not noticeable visually, however the file size has been reduced.

## Why It's Good For The Game

Peak efficiency.

## Changelog
:cl:Celotajs
qol: Ass scans, stamps, UI icons and other .gif and .png images have been optimized to peak efficiency.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
they are 100% not noticeable visually right? there isnt random anti aliasing, pixel changes or anything?

**Comment by celotajstg** [comment]
From what I have checked, there should not be any issues, yes. Further optimization passes did lead to visual changes in mapbase1024.png however, which is why I decided to do only one optimization pass for all images.

**Comment by coiax** [comment]
I should point out that because of how git stores history, this will only reduce the size of the media bundle that your Byond client downloads. It will actually make the checked out repository size BIGGER.

**Comment by celotajstg** [comment]
I guess that is up to maintainers, though peak efficiency for clients is a good thing.

**Comment by Mothblocks** [comment]
> this will only reduce the size of the media bundle that your Byond client downloads

That's more important than repository size.

**Comment by Mothblocks** [comment]
Did a scan over to make sure nothing was out of the ordinary, looks good to me.

**Pull request merged**
