### PR TITLE
/proc/fully_heal now checks for admin_revive for conditional mood events

### LINKED ISSUE #40110: Admin heal/Legion core use permanently removes special permanent negative moodlets
Issue reported from a round on a personal server

Reporting client version: 512

There are special, permanent negative moodlets in the game.  Examples include the HULK SMASH! moodlet obtained from gaining the Hulk mutation, as well as the negative moodlet obtained from breaking your vow of silence as a Mime.  These moodlets, under normal circumstances, never go away and are intended to persist the rest of the round unless you become another character entirely (become a golem, etc.) or meet special criteria for their removal (re-swearing your vow of silence as a mime).

However, if you are admin healed or use a Legion core obtained from a defeated Legion, you're not only fully healed and satiated to neutral hunger, but also any negative moodlets affecting you are removed.  Since these permanent negative moodlets aren't meant to go away, and are only applied once when you meet the circumstances for obtaining them, their removal means they aren't ever coming back.  This lets you enjoy a normal emotional spectrum even when you shouldn't.

Possibly the same issue or related to #40083

### Reproduction Steps:

1. Obtain a permanent negative moodlet via some means (obtaining hulk mut, breaking mime vows, etc.)
2. Check mood - you should see the negative moodlet
3. Obtain and use a Legion Core
4. **Problem Behavior:** _Check mood - you should see that the negative moodlet is now gone._
5. Wait any length of time
6. **Problem Behavior:** _Check mood - no matter how long you waited, that negative moodlet is never coming back._

**Here's my moodlets upon using a Hulk DNA injector:**

image

**And this is what happens after I use a Legion Core while still a Hulk:**

image

**Here's the whole chatscreen so you can see I'm not skipping anything between the two:**

image

### PR DESCRIPTION
**Pull request by granpawalton**
:cl: Granpawalton
fix: /proc/fully_heal now checks for admin_revive to determine if it should heal conditional mood events.
/:cl:

[why]: This makes it so legion cores do no longer remove conditional mood modifiers such as "HULK SMASH!" or breaking your vow as mime, this also puts an unused parameter to use as octareenroon91 first pointed out. I checked for any other times this proc would effect mood and some other notable one was the healing wand.

Gives each mood_event its associated string used in SEND_SIGNAL as name

fixes #40110

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
The issue is not that it removes moodlets, the issue is that it removes _permanent_ moodlets.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
L437 needs to be `= FALSE` instead of `= 0`

That and every proc under it that has a second argument.

**Review by Cyberboss — DISMISSED** [review]

**Comment by Barhandar** [comment]
Does it correctly update moodlets from the rest of the state (e.g. hunger moodlets)?

**Comment by granpawalton** [comment]
My bad i thought the consensus was that we didnt want legion cores to effect mood at all because of immersion i can handle it then, i know it updates hunger regardless of whether of admin_revive can you think of any similar thing i could check for?

**Comment by Qustinnus** [comment]
i think this PR makes sense, legion cores shouldn't just fix moodlets, especially not ones that are on/off like mime vow

**Comment by granpawalton** [comment]
If i missed any moods that shouldn't be effected by heal then please tell me i only prepared for broken vow and hulk.

Also if there is a better method of doing what I did then please tell me so i can change it.

**Comment by octareenroon91** [comment]
clown shoes

**Comment by octareenroon91** [comment]
This PR is threatening to become a snowflakey mess.

I suggest you look back to `code/datums/components/mood.dm`. Non-expiring mood events have timeout var equal to zero, so you can identify by code instead of coding in what's basically a whitelist.

**Comment by ExcessiveUseOfCobblestone** [comment]
^

**Comment by Qustinnus** [comment]
Loop through mood events,

check if they have no timeout

sendsignal remove mood event

**Comment by granpawalton** [comment]
@Qustinnus thats what ive been trying to do since octareenroon91 said it but to do the sendsignal remove i need the appropriate string such as "vow" for broken_vow

` SEND_SIGNAL(H, COMSIG_CLEAR_MOOD_EVENT, "vow") `

what ive tried to do is attaching a name to each mood_event such that i can do

>		for(var/i in mood.mood_events)
>			if(mood.mood_events[i].timeout)
>				SEND_SIGNAL(src, COMSIG_CLEAR_MOOD_EVENT, mood.mood_events[i].name)

but ive been running into issues when trying that to do that.

Again i get the creeping feeling there is an better way to do this but i don't know one, i tried playing around with qdel but made no progress there.

**Comment by Qustinnus** [comment]
just reverrt it and do wha you originally did

**Comment by Qustinnus** [comment]
no just dont remove the moods lol just keep it aheal only, using names wont resolve the problem and just make the code more confusing. do what you did when you first made the PR

**Comment by granpawalton** [comment]
This does work as intended but it adds name to each mood_event. I can remove this if thats what you think is better but in my opinion it is a lot easier to find its appropriate string in ` mood_events/target_mood.dm ` 
 when it comes to readability.

**Comment by ExcessiveUseOfCobblestone** [comment]
This ID system is icky

**Comment by Qustinnus** [comment]
It isn't but you need to specify what you're deleting, I can change it but I'm not home

**Comment by Qustinnus** [comment]
Also just don't delete moods when legion core is used

**Comment by granpawalton** [comment]
i could just delete the ones with negative mood_change if thats what you mean

**Comment by ExcessiveUseOfCobblestone** [comment]
he wants the mood removal only on adminheals with no changes to mood whatsoever on non-adminheals.

also the id system of moods will forever be gross but i'm too lazy to handle that

**Comment by Qustinnus** [comment]
there's no id system lol

**Comment by ExcessiveUseOfCobblestone** [comment]
whatever you want to call the string argument for it to refer to the appropriate type is the thing i dislike.

**Comment by Qustinnus** [comment]
there's no such thing except when he tried to add it.

what you probably mean is how moods are saved in an assoc list with string - mood event values, which actually has several benefits and makes the code better

**Comment by octareenroon91** [comment]
Make a no-effect deletion mood event with `timeout = 1` . Inject it on top of anything that will be deleted.

**Comment by Qustinnus** [comment]
why do we need so much odd hacks

**Comment by octareenroon91** [comment]
>why do we need so much odd hacks

Option 1: change one or two files. it's a bit of a hack, hopefully tidy, clever, and understandable.

Option 2: change a dozen files, hope you get merged before a conflict hits. the whole system is better behaved if it ever merges. if.

**Comment by Qustinnus** [comment]
or you dont write some stupid hack to remove moodlets when a legion core is used or you ask me to make a reasonable way to remove all non-permanent moodlets lol

**Comment by Cyberboss** [comment]
Do it then @Qustinnus

**Comment by Qustinnus** [comment]
I will once my other prs are merged lol

**Pull request closed without merging**
