### PR TITLE
Allows Strange Plants to distill into Unstable Mutagen

### PR DESCRIPTION
**Pull request by ArcaneMusic**
Yeah yeah, I know, another 1 line Botany Buff. Bare with me for a second here.

## About The Pull Request

Came to me during the recent discussions about botany balance on the discord. I understand that most people's concerns are in regard to Botany being Reliant on Strange Seeds/ Advanced Chems/ Cooperation, and I am also aware that MANY, MANY PRs before me have attempted to add unstable mutagen as a reward to the biogenerator before me. In avoiding those pitfalls, I starting thinking about a VERY underutilized mechanic that botany has exclusively: Fermentation. Since Strange Seeds are almost synonymous with botany being able to do the most exceptionally cool things within their department, I considered something different: giving botany an incentive to actually grow strange seeds once they gain access to them.

To do this:
Plants have a variable called distill_difficulty (default is zero) that's added to the barrel's specific distill_speed (default 1). This means that you can at least have a bit more control over how quickly different plants distill in the future, as currently only the barrel determine's fermentation speed, not the plant. Other plants maintain their old distill speeds and reagents, but this at least allows more expansion for easy use. Strange Plants have a very high distill_difficulty, putting them between 1:30 and 2:15 to distill into mutagen. With default, newly spawned strange seeds, if grown and then fermented, it will distill into 12.5 units of unstable mutagen each (ON AVERAGE), in addition to the strange plant's random reagent. This is increased/decreased with the plant's potency as per usual (Not changed).

## Why It's Good For The Game

I have been repeatedly reassured that in almost all cases, unstable mutagen would be faster to be obtained by growing blumpkins and glowshrooms than by fermenting any number of strange plants. In a worst case scenario, where perhaps a player doesn't have access to chemistry in-round for whatever reason (Medbay being bombed quickly, Chemists being snobs, Horrible antisocial behavior, etc.), that botanists would still have a way to access the 80% of botany content gated behind mutagen, but at an exceptionally slower rate. This to me feels like the right balance for interdepartmental balance, You don't have to make it impossible, but exceptionally faster to reward teamwork.

## Changelog
:cl:
add: Strange Plants can now be fermented into unstable mutagen.
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
Oh boi there we go again
1. You can get umstable mutagen production trough plants
2. You can have chemistry access.
3. You can build a unstable mutagen factory with plumbing
4. Theres a spare chem dispenser board in tech storage
5. You can print the boards in engineering/medbay
6. Strange plants already have a small chance including mutagen

**Comment by HomocidlePancakes** [comment]
>You can get umstable mutagen production trough plants
You can have chemistry access.
You can build a unstable mutagen factory with plumbing
Theres a spare chem dispenser board in tech storage
You can print the boards in engineering/medbay
Strange plants already have a small chance including mutagen

Oh boi, if you’ve actually read a bit, then you would know that this supposed to be low effort/low reward option, and looking through your list, I don’t see a method that fills that niche.

Also, you’ve just made a list. What was supposed to be your argument? I have my guesses, but still, would like to know the exact reasoning as to avoid miss-communication.

**Comment by improvedname** [comment]
Convience creep for the sake convience

What next gaining research points for constructing machines?

**Comment by CRITAWAKETS** [comment]
Good lord what is with people hating botany PRs but never actually knowing anything about botany.

This seems pretty nice as a last resort for if you cant get any mutagen.

**Comment by Tlaltecuhtli** [comment]
at this point lets remove genetic plants and make vegetables increase your stats  by 0.01 every time you eat one

**Comment by ArcaneMusic** [comment]
Alright, so, after some testing and code diving, fermenting plants is actually, pretty exceptionally fast. More so than I would have previously thought, being that it's... fermentation. So, I made some changes to the PR body, but the new highlights are:

Plants have a variable called distill_difficulty (default is zero) that's added to the barrel's distill_speed (default 1). This means that you can at least have a bit more control over how quickly different plants distill. 
Strange Plants have a very high distill_difficulty, putting them between 1:30 and 2:15 to distill into mutagen.
Other plants maintain their old distill speeds and powers.

I should also probably add wooden barrels to the stack crafting menu, since  _APPARENTLY_ they're only in the tablecrafting menu under tribal.

**Comment by Shadowflame909** [comment]
Arcane

Strange Plants die. **REALLY REALLY REALLY REALLY** fast. Like no joke, just walk from botany to the bar and it'll already be on the verge of death.

Or should I say have the maximum weed value.

If someone can play spam click cultivator simulator to keep this strange plant alive. They're no-lifing ss13.

**Comment by improvedname** [comment]
> > You can get umstable mutagen production trough plants
> > You can have chemistry access.
> > You can build a unstable mutagen factory with plumbing
> > Theres a spare chem dispenser board in tech storage
> > You can print the boards in engineering/medbay
> > Strange plants already have a small chance including mutagen
> 
> Oh boi, if you’ve actually read a bit, then you would know that this supposed to be low effort/low reward option, and looking through your list, I don’t see a method that fills that niche.
> 
> Also, you’ve just made a list. What was supposed to be your argument? I have my guesses, but still, would like to know the exact reasoning as to avoid miss-communication.

Ironically enough this is more effort then just getting one of the things from the list

**Comment by ExcessiveUseOfCobblestone** [comment]
does fermentation care about the reagents inside the plant? seems kinda odd the plant known for being wildly different on a per seed basis reliably gives the same reagent when fermented. 

also bee farms can dupe reagents, rip bees...

**Comment by ArcaneMusic** [comment]
> does fermentation care about the reagents inside the plant? seems kinda odd the plant known for being wildly different on a per seed basis reliably gives the same reagent when fermented.

It does factor in the reagents of the plant itself as well. In my testing, it fermented into unstable mutagen, as well as all the fun random reagents (mine were Dry Ramen and Quantum Hair Dye).

**Comment by Ohagi-Chan** [comment]
When I have tested fermenting green grapes the resulting mix contained more nutriment than cognac.

Something to consider with this PR is that hacking tools are looking to get rarer anytime soon while strange plants mostly rely on hacking to aquire.

**Comment by ATH1909** [comment]
12.5u of unstable mutagen is basically nothing. It's 2.5 shots at a 10% chance to mutate your plant's species.

Make this 50u per strange seed, and then _maybe_ some less experienced botanists who don't know how to make chem dispensers _might_ use it.

Alternatively, make this give you 12.5u of strange reagent instead of unstable mutagen, which could be relevant with the upcoming removal of cloning.

**Comment by ArcaneMusic** [comment]
> 
> 
> 12.5u of unstable mutagen is basically nothing. It's 2.5 shots at a 10% chance to mutate your plant's species.
> 
> Make this 50u per strange seed, and then _maybe_ some less experienced botanists who don't know how to make chem dispensers _might_ use it.
> 
> Alternatively, make this give you 12.5u of strange reagent instead of unstable mutagen, which could be very useful once cloning gets removed (it's already quite useful, of course, especially if someone kills a beloved station pet).

Keeping in mind, that's 25 Mutagen at 100 potency, each. Considering this is meant as a slower, last resort method, I don't mind how little you're getting, but if you're farming 100 potency strange plants, that's still a fairly decent amount of mutagen.

Also, Strange Reagent is exceptionally powerful. Probably not a good idea to consider making that a hydroponics chemical until that whole issue has settled down a bit.

**Comment by FantasticFwoosh** [comment]
> Strange Plants die. **REALLY REALLY REALLY REALLY** fast. Like no joke, just walk from botany to the bar and it'll already be on the verge of death.

If you dont genetic edit your strange plants with perfect survivability with a mutation modifier of 0, maximum yield and no weed chance over a gaia tray, i would support this statement but i don't.

**Comment by ExcessiveUseOfCobblestone** [comment]
it doesn't make sense to me that the plant (although I think it's more of a way to handwave different species of plants without typing each one) known for having a bunch of different reagents consistently poops out mutagen.

If you need plants mutated and the cooperation gods hate you, you can use L4Z. EZ also has a small chance to mutate plants.

**Pull request closed without merging**
