### PR TITLE
curators no longer get triggered from lizard talking

### PR DESCRIPTION
**Pull request by ghost**
closes #35017

whenever a lizard talked, the term "hiss" was part of their verb 'hisses' so they would get triggered. hilarious!

i don't believe there is an issue up for it right now but this is a fix

### CODE REVIEW

**Comment by Anonmare** [comment]
I didn't know librarians were afraid of danger noodles. I should hide nope ropes in their department more.

**Comment by Shadowflame909** [comment]
I feel like as soon as this happens to me. It gets a PR hmmm.

**Comment by ShizCalev** [comment]
should this be line 50 instead?

**Comment by Shadowflame909** [comment]
Artificers, Wraiths and Shades all Hiss with speaking. whoever made this be a brain trauma word is a bad-bad person.

**Comment by ExcessiveUseOfCobblestone** [comment]
`closes  #35017` in pr body please.

**Pull request merged**
