### PR TITLE
Removes tinyfans from omega/delta tcomms

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
remove: Removed the tiny fans from Omega/Delta tcomms.
/:cl:

This PR removes the last remaining tiny fans from inappropriate areas (Omega/Delta tcomms).

### CODE REVIEW

**Comment by DaxDupont** [comment]
Changelog and also is this allowed in the freeze

**Comment by 81Denton** [comment]
Tiny fans are horrifying crimes against atmos so my best bet is yes

**Comment by ExcessiveUseOfCobblestone** [comment]
You're fixing an oversight from previous prs that wanted to remove tinyfans so I'd assume so.

**Comment by Arianya** [comment]
I must be out of the loop, why do we hate tinyfans now

**Comment by ExcessiveUseOfCobblestone** [comment]
they're copouts for not closing the doors

**Comment by 81Denton** [comment]
They're p much reserved for areas that can't refill airmix (spess/lavaland ruins) or mass drivers.

**Comment by Arianya** [comment]
I thought their main use was stopping certain rooms (like tcomms) being a hazard to the rest of the station just because you opened their door momentarily but hey whatever

>You're fixing an oversight

Uhhhh,

>A few were left in in places like the telecomms server room, the toxins launcher, and the old containment area since it seemed okayish to leave them.

Straight from #28890

**Comment by 81Denton** [comment]
>We have tons of methods for controlling atmos, tiny fans need to go

Straight from #28890 🤔

**Comment by Arianya** [comment]
I'm just saying it's not an oversight, no real thoughts on the PR itself.

**Comment by ExcessiveUseOfCobblestone** [comment]
"tiny fans need to go" but it doesn't remove all tiny fans isn't an oversight?

I understand that the specific pr explicitly left some out but it's pretty clear the direction of full removal of them from the station was intended and that was an ease into that direction. If you're using that explicit pr for sole reference, see:

> For ruins, and such tinyfans are perfectly fine, as they don't have a way to replenish their air supply usually. On a fully functioning station, it's just silly.

From the creator of the PR within that very same PR.

Regardless, the maintainer said they need to go from the station fully in the PR so this fixes the issue of them still remaining, regardless if you want to call it oversight or not.

**Comment by Arianya** [comment]
The maintainer also merged that PR without any further change requests.

As I say, I don't have any strong feelings on the tinyfans on station, but to call it an oversight is just trying to find an excuse to PR it during a feature freeze.

**Comment by Cyberboss** [comment]
Tinyf ans are bad and those who add them should feel bad

**Review by Cyberboss — APPROVED** [review]

**Comment by yoyobatty** [comment]
There is always going to be air or supercooled nitrogen in the middle airlock. The tiny fan prevents the room temperature air from getting cold nitrogen and the supercooled nitrogen room from getting air. Considering tcomms does not have an atmos system hooked up and the air scrubbers in the normal room do not detect nitrogen as a harmful gas, I find this will reintroduce problems that the tiny fans took away, such as allowing tcomms to be set on fire. Intended as normal use, aka Engineers/Borgs doing work, the tcomms room should never have oxygen in it, and if a traitor wishes to, he can smash the glass windows to introduce oxygen. Not to mention it increases the amount of atmos processing calls which increases strain on the server. -1

**Comment by 81Denton** [comment]
@Bawhoppen Those exist for most incinerators and are honestly pretty great. I'll look into adding them to tcomms after the freeze, it's just a bunch of work since you need to place pipes etc.

cgewergcvevcrgvgre

**Comment by 81Denton** [comment]
Actually, those wouldn't work properly since they don't distinguish between a proper airmix and pure N2. Hmm...

**Comment by Arianya** [comment]
Does tcomms being full of supercooled N2 actually do anything or is it purely there as flavour because its a ~server room~

**Comment by DaxDupont** [comment]
@Arianya fluff and to prevent people from sabotaging it more easily.

**Pull request merged**
