### PR TITLE
Items can now react to being constructed by autolathes

### PR DESCRIPTION
**Pull request by RemieRichards**
This can be used for things like:
- Air tanks spawning without magically creating air
- Cells starting empty
- Hacked autolathes increasing the damage of things
- ...and more!

Currently does:
- Nothing!

### CODE REVIEW

**Comment by Supermichael777** [comment]
Currently the only two things I can think of are fire extinguishers and welding tools.  Other implementations can wait.

Also fun fact the welding tool thing is a blob mode crew nerf.

**Comment by Jalleo** [comment]
and also the exofab

**Comment by Iamgoofball** [comment]
>cells starting empty

No

**Comment by Jalleo** [comment]
@iamgoofball it gives a reason to actually upgrade stuff.

**Comment by Iamgoofball** [comment]
That's fucking dumb, forcing people makes it not-fun, i put a lot of work into making upgrades fun recently and making it 100% required is dumb as shit

**Comment by Razharas** [comment]
Maybe we need to unite it with aftercrafting proc somehow since its pretty much the same thing but for different things, and the source of creation being an argument maybe

**Comment by optimumtact** [comment]
>Currently does nothing

please read the PR before commenting.

**Comment by Firecage** [comment]
Goofball, please read the PR before commenting. Remie said that is what this COULD be used for, not what the PR currently does.

Besides, powercells starting empty from the autolathe makes sense.

**Comment by Fallcon** [comment]
This is just annoying as fuck. No.

**Comment by RemieRichards** [comment]
@Fallcon learn to read.

**Pull request merged**
