### PR TITLE
Adds a script to fix the tgstation-server submodule if it's deleted

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by optimumtact** [comment]
The kind of people who accidentally delete a submodule don't know how to run a bash script and will use windows

**Comment by MrStonedOne** [comment]
Submodules are useless.

They don't auto-update, they don't always auto fetch, they have issues, existing repos don't always get them when they get added.

It's a mess, even my limited use of submodules (the one in byond-cdn) is likely to get replaced by something else when i have time.

What are we using this submodule for?

**Comment by Jordie0608** [comment]
Has this happened before?

**Comment by Cyberboss** [comment]
@MrStonedOne it's tgstation-sever

@Jordie see the linked PR it's also happened before that too

**Comment by optimumtact** [comment]
just delete it? anyone using the server module will know how to get it and anyone who doesn't is not going to be able to set it up anyway?

**Comment by MrStonedOne** [comment]
>@MrStonedOne it's tgstation-sever

That doesn't answer my question.

Why is it a submodule at all? Does code need to be able to access this folder at this path?

**Comment by Really-Good-Soda-Flavor** [comment]
The fact that it needs a PR to update it means that it probably shouldn't have its own repo.

**Comment by Iamgoofball** [comment]
yeah this wouldn't work for me anyways, windows 10 here

**Pull request closed without merging**
