### PR TITLE
increases the player skill gap

### PR DESCRIPTION
**Pull request by MMMiracles**
if you don't know what a whetstone is then maybe you should play a more casual game.

### CODE REVIEW

**Comment by Qbopper** [comment]
it's like I'm playing wurm online

**Comment by KazeEspada** [comment]
Now make the sprite look like 
http://vignette2.wikia.nocookie.net/monsterhunter/images/f/f3/ItemIcon024a.png/revision/latest?cb=20100611131254
and we have a deal.

**Comment by GunHog** [comment]
Thank you. I was completely dismissed when making that suggestion. :+1:

**Comment by PKPenguin321** [comment]
Hands off my codebaby normie

**Comment by MMMiracles** [comment]
If you were a better parental figure I wouldn't of had to step in and fix your mistakes.

**Comment by Fox-McCloud** [comment]
:+1: 

This is the proper name for it----if people couldn't be bothered with a 2 second Google search or a quick ahelp asking what it is...

**Comment by tkdrg** [comment]
sure whatever

**Comment by Chocobro** [comment]
@Qbopper it's not wurm online unless the whetstone decays in three minutes

**Pull request merged**
