### PR TITLE
Removes & Adds some chemicals from the disease cure list

### LINKED ISSUE #74220: Some sentient diseases can luck out and become uncurable
Similar to https://github.com/tgstation/tgstation/issues/68209 but was closed for not being a bug

Sentient diseases can roll things like Happiness and Haloperidol. Problem is, Happiness is a Drug, and Haloperidol purges drugs (5 units per tick).
This means that the sentient disease can't get cured, because one cure chem will purge the second.

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Removes Anacea from the list of potential disease cures because it's a chemical purger, making them nearly impossible to cure from Sentient Disease.
Removes Spaceacillin because it's easily achievable from the Chem vendors and is the way to prevent infections, so it's unfair to also make it a cure.

Moves Haloperidol to a low-level chem, so it won't roll with Sentient Disease.

I didn't remove Multiver because it's at a low level, so Sentient Diseases can't roll it.

In exchange, I added some other reagents to replace them:
- Acetone - Low level chem on the same level as Bromine/Lithium
- Miners Salve - Prevents people from telling their own health
- Acetaldehyde - Requires Formal, therefore Silver, making a cure reliant on Paramedics/Miners
- Pentaerythritol - Same as above, but requires more of it and Lye, this is ranked higher
- Tirimol - This replaces Anacea because it can put you to sleep, delaying the person from making Vaccines
- Chloral Hydrate - This replaces the spot Haloperidol was in (as it was moved to a low-level chem). This is pretty much Tirimol but much easier to make and being more obvious/counter-able.

I also moved Haloperidol one level lower so I can put diphenhydramine in level 10 instead, and moved Oil down because it's incredibly easy and the drawbacks are "a little bit of toxin damage".

## Why It's Good For The Game

There is a massive difference between chemicals having side effects so risking yourself or other people to make a cure, and one cure literally purging the other.

This closes https://github.com/tgstation/tgstation/issues/74220 - I took this approach to it so it's not a complete nerf to Sentient Diseases.
Cures relying on things not in the chem dispenser, or putting you to sleep, is much more interesting and reliant on player ability/cooperation, than just a disease that can't be cured because of pure RNG luck.

## Changelog

:cl:
balance: Sentient Diseases (and diseases in general) can no longer roll Anacea, Haloperidol & Spaceacillin as their cure, however they've been replaced with chemicals that are either harder to make, or have larger drawbacks (such as putting you to sleep).
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
Spaceacillin is still the preset cure to tuberculosis and many other premade diseases. 

image

**Comment by JohnFulpWillard** [comment]
@BlueMemesauce if the disease intentionally wanted spaceacillin then I'm not gonna remove it, I'm just removing it from RNG

**Comment by BlueMemesauce** [comment]
> @BlueMemesauce if the disease intentionally wanted spaceacillin then I'm not gonna remove it, I'm just removing it from RNG

yea I realized that and I deleted my comment before you replied, sometimes i try to reply too fast

**Comment by Helg2** [comment]
> * Acetaldehyde - Requires Formal, therefore Silver, making a cure reliant on Paramedics/Miners

Just disassemble surgery table.

**Comment by JohnFulpWillard** [comment]
image
image
image

**Comment by JohnFulpWillard** [comment]
> Just disassemble surgery table.

That's fine and fair, I don't have a problem with it, it means medbay has one less surgery table to use.

**Comment by Helg2** [comment]
> That's fine and fair, I don't have a problem with it, it means medbay has one less surgery table to use.

They are used rarer than the station has no miners.

**Comment by Iamgoofball** [comment]
this is because players lack the knowledge of upgraded surgeries

**Comment by Helg2** [comment]
> this is because players lack the knowledge of upgraded surgeries

Because they are never researched.

**Review by san7890 — COMMENTED** [review]
could you alphabetize each nested list that would be so freakin epic

**Comment by Sealed101** [comment]
> image image image

this still means halving the chemical purge either way and in-game that was almost always enough to cure a patient. though yeah that is also rng based since it ain't guaranteed to decrease the disease's progress by a stage on each life tick. it's not exactly uncurable, just an additional step to take to cure it.

**Comment by JohnFulpWillard** [comment]
halving the chemical purge only to have it purged even faster by pentetic or just having the anacea purged itself lol

**Comment by san7890** [comment]
i will merge this the second you alphabetize all of the individual lists. anyone else can merge it at their leisure but i really think it should be done

**Comment by JohnFulpWillard** [comment]
you're

**Pull request merged**
