### PR TITLE
Update comment for `joined_player_list` to state that it contains ckeys, not clients.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
=\

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
But why is it a list of ckeys?

**Comment by ChungusGamer666** [comment]
> But why is it a list of ckeys?

Nevermind, i just found out GLOB.clients exists

**Comment by tralezab** [comment]
Shouldn't this be autodoc'd with `///` anyways?

**Comment by MrStonedOne** [comment]
> Shouldn't this be autodoc'd with `///` anyways?

They all should be. but i didn't want to change just one and changing all of them was kinda out of scope

**Comment by Mothblocks** [comment]
theres `//!` but i dont like the inconsistency

**Pull request merged**
