### PR TITLE
Minor tweak to space drugs

### PR DESCRIPTION
**Pull request by Cyberboss**
Updated with scientific name

### CODE REVIEW

**Comment by deathride58** [comment]
Speedmerget his

**Comment by Mark9013100** [comment]
dude weed lmao

**Comment by Dorsisdwarf** [comment]
who deleted the meme pr tag

**Comment by Cyberboss** [comment]
This ain't a meme, son.

**Comment by duncathan** [comment]
Space drugs are not weed; please refer to the ambrosia family

**Comment by duncathan** [comment]
@dorsisdwarf use the obvious bait tag instead

**Comment by deathride58** [comment]
If space drugs are not weed, then why is a significant part of cannabis space drugs?

**Pull request closed without merging**
