### PR TITLE
Balance: Removes anti-drop implants for nukies

### PR DESCRIPTION
**Pull request by JupiterJaeden**
## About The Pull Request

Removes anti-drop implants being available in nukie implants. Also rebalances the cybernetic implants bundle to cost 20 TC (value of 24 TC) since anti-drop has been removed from it. 

## Why It's Good For The Game

This is one of the rare few nerf PRs where I was not the one who got KILLED by the broken OP shit but rather the one using it. I recently played a nukie round (after hearing that anti-drop had been added) where I took modsuit shield, dsword, and anti-drop. I got separated from my team and then proceeded to solo murderbone half the fucking station, resist MULTIPLE disarms that would have otherwise been successful, get the disk alone, and nuke. I only had to stop to heal _once_ and honestly I probably would have been fine if I didn't.

Anti-drop dsword is _insanely_ powerful. Shielded dsword nukies were already strong enough but were at least somewhat balanced insofar as there were several ways you could still reliably disarm them and therefore open them up to more attacks. But now (after https://github.com/tgstation/tgstation/pull/77330 which added the anti-drop implants to nukie uplink) you can have shielded anti-drop dsword nukies. Add stims and some explosives to deal with any static fortifications the crew might make (like firelock crush relays), and with a semi-robust player you essentially have a murderbone machine who can't be killed by any regularly accessible crew counters short of point blank suicide bombing. We should not have a default nukie loadout that can only be reliably, regularly countered by a fucking bomb. Especially since the crew's main easily accessible ballistic is now being nerfed as well. (https://github.com/tgstation/tgstation/pull/78235) 

EDIT: I'd also like to point out that we already don't allow hulks to use dswords for many of the same reasons.

## Changelog

:cl:
balance: removed anti-drop implants from the nuclear operative uplink
balance: removed anti-drop implant from the nukie implants bundle and changed its cost to 20 TC
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
anti drop was not added in that pr unless im going senile

anti drop does not stop a bomb
anti drop does not stop a bodythrow + shotgun blast for shields
anti drop while does help against slips does not help against the knockdown
anti drop does not help against smoke nades
anti drop does not help against tackles

anti drop does help against your own stupid decisions and maybe stun batons

this is a wildly misguided pr because the crew on a warops round always has the upper hand provided they know how to use the time they're given to prepare. it doesn't have to take effort from like more than ten crewmates to curb nukies, either. 
one on one combat should favor nukies because they get the uplink toys. otherwise what's the point?

**Comment by CRITAWAKETS** [comment]
> anti drop was not added in that pr unless im going senile

image
i am so sorry you had to learn this way

**Comment by Sealed101** [comment]
lies

**Comment by JupiterJaeden** [comment]
> anti drop does not stop a bomb
Already addressed, point blank bombs are basically uncounterable except for xenobio bullshit but they should never be the ONLY counter to something

> anti drop does not stop a bodythrow + shotgun blast for shields
Yes it does. You will not drop your dsword from the bodythrow. The dsword + shields will not only block most of the shotgun pellets (not to mention the high bullet armor that nukies get anyways) but improvs are also getting nerfed too.

> anti drop while does help against slips does not help against the knockdown
No-slip is 2 TC.

> anti drop does not help against smoke nades
I forgot about like acid nades but I really just put those in "bomb" category. Bombs should never be the ONLY counter to a default easily accessible nukie loadout

> anti drop does not help against tackles
Yes it does, you don't drop the dsword. 

> one on one combat should favor nukies because they get the uplink toys. otherwise what's the point?
It already does. Shielded dsword nukies are already _plenty_ strong without needing anti-drop. Anti-drop just turns them into fucking murderbone gods

**Comment by Livrah** [comment]
Strongest no-drop desword nukie vs 674 plasma tank in the pocket of every Terry assistant.

**Comment by moocowswag** [comment]
doesnt emp force you to drop items when you are using anti drop implant

**Comment by JupiterJaeden** [comment]
> doesnt emp force you to drop items when you are using anti drop implant

Nukies already get some emp shielding and I believe they can purchase the stronger version of the emp shield, I've never seen EMPs used against nukies but maybe it's effective? That's something I'd have to test

**Comment by moocowswag** [comment]
its definitely something that should be tested, also emp shielding i think is for the modsuits which drain battery charge to protect you so id imagine if it did do anything to protect no drop it would mean you need extra shots from the ion gun.

**Comment by JupiterJaeden** [comment]
> its definitely something that should be tested, also emp shielding i think is for the modsuits which drain battery charge to protect you so id imagine if it did do anything to protect no drop it would mean you need extra shots from the ion gun, the question is how many?

Just tested this on private server. Unloaded full ion rifle into a shielded anti-drop elite modsuit nukie. Some bolts were deflected by dsword, some were stopped by modsuit shields, and the rest did nothing. Also tried using an emp grenade, did nothing.

**Comment by carlarctg** [comment]
The impulse is to dismiss this as a kneejerk PR but honestly it's not fun at all to face a stims + dsword + shield + noslip + nodrop syndie. You're just screwed. The main issue here IMO is on the energy shield module which is just awful and should be removed. Now you actually have a chance of hitting them!

**Comment by JupiterJaeden** [comment]
> The impulse is to dismiss this as a kneejerk PR but honestly it's not fun at all to face a stims + dsword + shield + noslip + nodrop syndie. You're just screwed. The main issue here IMO is on the energy shield module which is just awful and should be removed. Now you actually have a chance of hitting them!

Actually IMO I think dsword/eshield + modsuit shield would be a LOT better if attacks FIRST hit the modsuit shield and THEN, once those were all down, started interacting with the dsword/eshield deflections and block chances.

**Comment by carlarctg** [comment]
> > The impulse is to dismiss this as a kneejerk PR but honestly it's not fun at all to face a stims + dsword + shield + noslip + nodrop syndie. You're just screwed. The main issue here IMO is on the energy shield module which is just awful and should be removed. Now you actually have a chance of hitting them!
> 
> Actually IMO I think dsword/eshield + modsuit shield would be a LOT better if attacks FIRST hit the modsuit shield and THEN, once those were all down, started interacting with the dsword/eshield deflections and block chances. But that isn't really related to this PR.

Ah so that's what the big deal is all about, then? 75% of attacks get blocked and the last 25% get absorbed by the shield? That's clearly the issue then, not nodrop

**Comment by JupiterJaeden** [comment]
> > > The impulse is to dismiss this as a kneejerk PR but honestly it's not fun at all to face a stims + dsword + shield + noslip + nodrop syndie. You're just screwed. The main issue here IMO is on the energy shield module which is just awful and should be removed. Now you actually have a chance of hitting them!
> > 
> > 
> > Actually IMO I think dsword/eshield + modsuit shield would be a LOT better if attacks FIRST hit the modsuit shield and THEN, once those were all down, started interacting with the dsword/eshield deflections and block chances. But that isn't really related to this PR.
> 
> Ah so that's what the big deal is all about, then? 75% of attacks get blocked and the last 25% get absorbed by the shield? That's clearly the issue then, not nodrop

Nodrop is definitely still an issue since it means nukies can just have a flat 75% block chance... always, no matter what you do to them, and they will always reflect lasers (main accessible crew weapon) again no matter what you do to them.

**Comment by improvedname** [comment]
Powerfist bypasses modsuit shield and dsword energy shield checks

**Comment by optimumtact** [comment]
don't say that or someone will fix it.

**Comment by moocowswag** [comment]
> > its definitely something that should be tested, also emp shielding i think is for the modsuits which drain battery charge to protect you so id imagine if it did do anything to protect no drop it would mean you need extra shots from the ion gun, the question is how many?
> 
> Just tested this on private server. Unloaded full ion rifle into a shielded anti-drop elite modsuit nukie. Some bolts were deflected by dsword, some were stopped by modsuit shields, and the rest did nothing. Also tried using an emp grenade, did nothing.
> 
> Update: okay so the emp does actually stun you for a bit (standing stun like the goliath) but you dont drop the dsword or lose your modsuit shield. Make of that what you will. I still think the combination is way too busted.
> 
> Update update: If you take advanced emp shield module (only 5 TC), emps do nothing, do not stun or cause you to drop dsword or affect the suit.

Lol i think this shit needs changes if anything.

**Comment by AyamePup** [comment]
Giving nuclear ops anti-drop is definitely overkill in my opinion. Jupiter has already said most of my points above, so I wont add to the clutter by repeating it, but I certainly agree with them.

**Comment by GPeckman** [comment]
> anti drop does not stop a bodythrow + shotgun blast for shields

Buckshot got removed (from crew access, at least) and there's a PR open to remove improvised shells.

> anti drop does not help against tackles

Tackles need a ton of prep to be viable in _any_ situation, and even if you do prepare or get lucky and land a max tier tackle, you still need to follow it up with something. And that something will likely get blocked by the dsword and/or energy shield, since nodrop will let them keep holding the dsword.

**Comment by Shadowflame909** [comment]
I say keep it but raise the TC price so the nukie is screwed if his implant gets countered by an EMP on non-war ops.

Nukies are supposed to be strong, no?

**Comment by JupiterJaeden** [comment]
> Nukies are supposed to be strong, no?

There is a difference between "strong" and "can literally only be dealt with by point blank bombing them". Shielded dsword nukies were already PLENTY strong without anti-drop.

**Comment by Sealed101** [comment]
ion bolts have aoe and crew can make emp nades; with enough emp you just disable the suit by draining the battery. ion carbines are a thing by the way
no slip does not protect from space lube and i think iced floors
improv shells aren't being removed but rather nerfed in damage while the projectile count does not seem to be the victim of that pr. for shield removal you need damage instances not damage amount
any knockdown when executed properly makes a nukie an easier target for any of the options I've listed. a very good knockdown can let you fuck their day up with cuffs or legcuffs. 

anti drop doesn't seem like the core issue of your perceived meta nukie loadout, but rather the high chances for the shields + dsword combo to negate damage. i think you'd get away with eswords not being able to deflect ion projectiles like they don't with thermal rifle projectiles

**Comment by DaydreamIQ** [comment]
> anti drop was not added in that pr unless im going senile
> 
> anti drop does not stop a bomb anti drop does not stop a bodythrow + shotgun blast for shields anti drop while does help against slips does not help against the knockdown anti drop does not help against smoke nades anti drop does not help against tackles
> 
> anti drop does help against your own stupid decisions and maybe stun batons
> 
> this is a wildly misguided pr because the crew on a warops round always has the upper hand provided they know how to use the time they're given to prepare. it doesn't have to take effort from like more than ten crewmates to curb nukies, either. one on one combat should favor nukies because they get the uplink toys. otherwise what's the point?

You do realise the desword bundle now comes with noslips and a meth pen.
Body throw doesn't disarm the nukie
A shotgun won't disarm the nukie, and they can block the pellets
A body throw won't disarm the nukie, and they can block any follow up hit
Smoke won't stop a nukie using thermals 

The anti drop removes any and all counterplay that isn't "lmao just maxcap them" and anyone down voting this is just salty that they won't have a free win kit. I've been on both sides of this situation and yeah, it's broken and incredibly annoying to face as someone who thinks desword haters just have a skill issue

**Comment by SimplySmiley123** [comment]
> anti drop was not added in that pr unless im going senile
> 
> anti drop does not stop a bomb anti drop does not stop a bodythrow + shotgun blast for shields anti drop while does help against slips does not help against the knockdown anti drop does not help against smoke nades anti drop does not help against tackles
> 
> anti drop does help against your own stupid decisions and maybe stun batons
> 
> this is a wildly misguided pr because the crew on a warops round always has the upper hand provided they know how to use the time they're given to prepare. it doesn't have to take effort from like more than ten crewmates to curb nukies, either. one on one combat should favor nukies because they get the uplink toys. otherwise what's the point?

Well with what weapons they can have in that time, it's often a War Ops sweeping the station clean and nuking it unless they are the dumb ones.
With laser and energy guns becoming the only viable guns, it's extremely easy to counter them, with de-sworders only really having to look out for body throws and chad tackle users that gamble with their head, with shield module countering batons on top of the ridiculous block chance.

**Comment by JupiterJaeden** [comment]
> ion bolts have aoe and crew can make emp nades; with enough emp you just disable the suit by draining the battery. ion carbines are a thing by the way

You can just get full emp protection for 5 TC.

> no slip does not protect from space lube and i think iced floors

Even if you slip on lube with anti-drop you won't drop the dsword...

> improv shells aren't being removed but rather nerfed in damage while the projectile count does not seem to be the victim of that pr. for shield removal you need damage instances not damage amount

In my experience one point blank hit with a shotgun doesn't actually take down all modsuit shields immediately (for some reason) but even if it did they still have an un-removable 75% block chance and high bullet armor against further shots. With improvs being nerfed down to 30 damage point blank, after armor and block chance you're literally talking about like <5 damage per shot lol  

> any knockdown when executed properly makes a nukie an easier target for any of the options I've listed. a very good knockdown can let you fuck their day up with cuffs or legcuffs.

You cannot cuff someone just because they are in knockdown. You _might_ (VERY BIG MIGHT) be able to if you shovestun them but not only do nukies have stims which I'm pretty sure reduce shovestun times, shovestuns are also blocked by modsuit shields AND by the 75% block chance on the dsword. (shovestuns working through modsuit shields and block chances with combat mode off is a bug so don't cite that). Also you can only shovestun them if you don't knock yourself down too which would be quite hard with lubed floors or tackles. Also remember while you are trying to pull off this shovestun cuffing they still have a fucking dsword in their hands they will presumably be hitting you with. 

Also... nukies can get freedom implants. 

When you have to start thinking of these super specific, rare, extremely difficult to execute scenarios that might feasibly possibly be a way to fight against this loadout that any nukie can get with 0 effort, maybe we should accept that the loadout is way too overpowered for how accessible it is. The obvious exception is point blank bombing, but I've already addressed that I don't think that should ever be the ONLY option left.

> anti drop doesn't seem like the core issue of your perceived meta nukie loadout, but rather the high chances for the shields + dsword combo to negate damage. i think you'd get away with eswords not being able to deflect ion projectiles like they don't with thermal rifle projectiles

The problem is not really that the dsword has a high block chance + energy projectile reflection, the problem is that the dsword has a high block chance AND becomes basically impossible to disarm with anti-drop.

> oh yeah full emp immunity for 10 tc doesn't sound right either, might look into that too
 
 It's 5 TC

**Comment by Sealed101** [comment]
yeah some of those were far fetched
i never said anything about knocking the sword out of the nukie's hands, i meant knocking down the nukie is already a strong lever for the crew to just fucking mob them while they're down. 
emp is underused if anything and nukies having a full blown immunity for 5 tc is hilarious, this shit needs to be checked

i still think the issue here is the shield+sword combo mostly, as a sword could easily block shit for long enough to let the shields regen, thus extending the nukie's combat time span drastically. the supposed no-bruteforce-counterplay against a desword just sounds bogus to me considering the fact that those combatants used to be dealt with eventually just by shooting or toolboxing them enough times

not to say i advocate for this combo to remain unaffected, i just want to see the anti drop remain in the nukie arsenal - it's only really troubling with eswords and maybe eshields i suppose, for every other weapon it would play its role of a dumbass safeguard well enough

**Comment by DaydreamIQ** [comment]
There is the possibility of adding a check that stops you from activating a desword while nodrop is active like hulk apparently has. The issue is mostly that no matter what you do to stun the guy using it, they can just tank the hit 75% of the time because of its inherent block chance against pretty much everything that isn't a laser which it blocks 100% of the time. Though even if the desword itself gets nerfed people will just start using the handheld shield + sword combo which has a lower physical block but still guarantees laser immunity

**Comment by nukularpower** [comment]
Disagree with this because its certainly possible for crew/sec to get anti drops and it should not be just for them

**Comment by moocowswag** [comment]
> Disagree with this because its certainly possible for crew/sec to get anti drops and it should not be just for them

Its actually not you need tens of thousands of research points to get them due to military tech prequisites and the shuttle will usually dock at round 30ish pre 30 minutes regardless of what nukies do.

**Comment by Fikou** [comment]
I already expressed I didn't like this to anne

**Comment by SimplySmiley123** [comment]
> The impulse is to dismiss this as a kneejerk PR but honestly it's not fun at all to face a stims + dsword + shield + noslip + nodrop syndie. You're just screwed. The main issue here IMO is on the energy shield module which is just awful and should be removed. Now you actually have a chance of hitting them!

The problem is normally this nonsense would get countered by ballistics (WT and the shotguns when they weren't pointless or at point blank range with improvised shells), which unlike lasers, can't be infinitely reflected 100% of the time and drain the shield module super fast.

Instead now, crew is forced to either use lasers, which get countered either way, or go into melee range against a de-sworder and try baton them. With tackles and body throws only really being worth it if you are absolutely certain the nukie does not have anti-drop implant, especially tackling, as you often will end up delivering yourself to the nukie for a swift decapitation.

**Pull request merged**
