### PR TITLE
Fixes 2 drone console UI issues

### LINKED ISSUE #62838: Cargo drone console "remove item" buttons are unaligned
## Round ID:

[173080](https://scrubby.melonmesa.com/round/173080)

## Reproduction:

image

### LINKED ISSUE #63498: The exoscanner array control console's UI scaling is  incredibly wonky
Reporting client version: 514.1568

## Round ID:
[175051](https://scrubby.melonmesa.com/round/175051)

## Reproduction:

image

The UI for the scanner array control console scales incredibly wonky, and seems to be a different size every time you open the UI.

No image editing is done in that above screenshot. It was only cropped. It genuinely looks like that.

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
1. Exoscanner array console did not have a height / width set ( ͡° ͜ʖ ͡°)
2. Drone console had strange button placement / clipping issues

## Why It's Good For The Game
Fixes #62838
Fixes #63498

## Changelog

:cl:
fix: Clipping and sizing issues on drone consoles have been fixed.
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
File additions/deletions: Mostly due to my linter. I run prettier => eslint (which has preset tg values).

**Comment by stylemistake** [comment]
Stop ruining existing interfaces with prettier

**Comment by Cyberboss** [comment]
>ruining with prettier
image

**Comment by jlsnow301** [comment]
> Stop ruining existing interfaces with prettier

i hate that we must squabble over this and my prs won't get accepted unless the the whitespace is correct
it's really whatever, i disabled it and went back through it

**Pull request merged**
