### PR TITLE
Fixes an issue with sentient diseases and darkness

### LINKED ISSUE #50694: Sentient Diseases have an darkened screen.
## Round ID:
[135607](https://scrubby.melonmesa.com/round/135607)

## Testmerges:
#50608: '[Ready for Testing] Runechat: 'Runescape-like' Chat Message Overlays (It's back!) ' by bobbahbrown at commit 909e23d5b8

## Reproduction:
spawn in as sentient disease, all of your screen is darkened. @LemonInTheDark 
image
Probably because of hud layers being set to the wrong thing, as the same with #50444 .

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

see_invis is used to show/hide the lighting plane. This fixes #50694 

## Why It's Good For The Game

image

## Changelog
:cl:
fix: Fixes an issue with sentient diseases and darkness
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
10 hours of my life down the drain

**Comment by LemonInTheDark** [comment]
If this happens with blobs I'm gonna cry

**Comment by AnturK** [comment]
From quick glance blob has it unset too, so get some tissues and add this to this PR please.

**Comment by Rohesie** [comment]
Add to bleb

**Comment by LemonInTheDark** [comment]
This is a dark day. Bled add soon

**Pull request merged**
