### PR TITLE
Alphabetises Phobias

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Alphabetises some lists, json, and type paths related to phobias

## Why It's Good For The Game

It's neat and tidy

## Changelog
Not player facing

### CODE REVIEW

**Comment by Overuseddart** [comment]
I thought this was adding a phobia to code…

**Review by Mothblocks — APPROVED** [review]

**Comment by TheVekter** [comment]
Alphabetizes*

**Comment by Thunder12345** [comment]
> Alphabetizes*

God Save the King

**Comment by JohnFulpWillard** [comment]
san7889 rolling in his bed rn

**Comment by Thunder12345** [comment]
> san7889 rolling in his bed rn

You mean ans

**Pull request merged**
