### PR TITLE
[wip]blueaspace ship beacon

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

blueaspace ship beacon allow to jump docker camera to it

## Changelog
:cl:
add: blueaspace ship beacon that allow ship to fly to it
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
ok

**Comment by habader** [comment]
is the ship blocked by walls and shiet?

**Comment by Dennok** [comment]
This is beacon for custom destination placing so it now can be placed only in the clear space.

**Comment by FloranOtten** [comment]
I can't tell if you're doing a meme accent or are actually retarded

**Comment by Dennok** [comment]
what?

**Comment by FloranOtten** [comment]
>If you vant test it

I mean really, I get spoken w=v but come on

**Comment by Dennok** [comment]
Oh...

**Comment by Arathianen** [comment]
Tovarisch, thiz very good pr. All village proud.

**Comment by ninjanomnom** [comment]
This won't work, shuttles need the data on a stationary dock in order to properly move. Also no more WIP prs that aren't at least ready for testing are allowed

**Comment by Dennok** [comment]
This work not as docking port. it work as target for camea jump for docker.

**Comment by ninjanomnom** [comment]
Oh that's what you're intending for. Seems like a bad idea to grant that to all custom dockers.

Regardless though I can see this is not ready for live testing. Let a maintainer know to reopen this when it's more complete or open a new pr, as you will.

**Comment by Dennok** [comment]
Reopen this please

**Comment by ninjanomnom** [comment]
You force pushed so you'll need to make a new pr

**Pull request closed without merging**
