### PR TITLE
Fixed issues with drones wearing chameleon gear, added admin-spawn snowflake drone headgear

### PR DESCRIPTION
**Pull request by coiax**
The drone camogear GUI
[Demonstration video of the GUI buttons](https://youtu.be/8FLm1Rp4nzk)

:cl: coiax
tweak: Fixed issues with drones wearing chameleon headgear.
rscadd: Added admin-only "snowflake drone" (also known as drone camogear) headgear.
/:cl:

A lot of changes under the hood to make this possible, including making the chameleon items more modular, (possibly setting up for a later EMP-to-randomise PR), allowing item action buttons to have different icons than the item, and fixing a missing proc in drone's inventory and icon code.

### CODE REVIEW

**Comment by Supermichael777** [comment]
can you make it list both hats and masks? drones can wear masks too

**Comment by coiax** [comment]
Yeah, this idea has already been proposed. I'm gonna make a drone verb that toggles the equipped camo item, since it's NODROP.

**Comment by PKPenguin321** [comment]
Fuck snowflake drones

**Comment by coiax** [comment]
Don't worry, I'll be adding the ability for drones to have customisable trails in a future PR. Say hello to drones that trail ions, glitter, sparks or quality memes.

**Comment by optimumtact** [comment]
This just kinda makes having hats not fun or interesting because the discover/rareness aspect is gone

**Comment by PKPenguin321** [comment]
^

**Comment by KorPhaeron** [comment]
I agree with oranges

**Comment by RandomMarine** [comment]
Also kills using functional hats, like hardhats with lights.

**Comment by coiax** [comment]
Christ, can't win. Drones are "thieving griefers", and when we put in PRs to make them less annoying, it's "taking away discovery and uniqueness".

**Comment by PKPenguin321** [comment]
Drones being theiving griefers often refers to them taking metal and BoHs and shit, not hats

Jesus Christ I can't believe we have a drone fetishist

**Comment by Bawhoppen** [comment]
oranges is right, half the fun was that drones could find and use rare hats, not just get them for free
if you saw a drone with a deathsquad hat then he was doing something right, but now it takes away the fun

**Comment by Shadowlight213** [comment]
Major :-1: losing hardhat lights is probably going to kill drone for me, as it's such a pain to see shit.

**Comment by octareenroon91** [comment]
How about buffing drone light?

**Comment by JJRcop** [comment]
H-hi~~ Um.. coiax sempai.. Y-you may.. not have noticed me, I-.. Iaddeddronehatssoimayhavesomeformofsayonthematterandidontreallylikeit!! P-please d-don't scold me!~~

**Comment by TankNut** [comment]
Eeeh I'm kind of agreeing with @Bawhoppen. I enjoy finding hats to wear and if you get to pick whatever it's going to get mundane very quickly.

Imagine the amount of syndie hardsuit helmets that'll be worn.

**Comment by PKPenguin321** [comment]
Yeah, it's not like drones wear the hats to look cool. It's basically just for showing off the whackiest/rarest hat.

**Comment by Lumipharon** [comment]
This is dumb and snowflake.

**Comment by Niknakflak** [comment]
Yep :-1:

**Comment by coiax** [comment]
So I literally thought of this as I was falling asleep, which I think may neatly solve a lot of the issues: HAT SCANNERS.

1) Set up a whitelist of hats and masks for the drone camogear, and make it start empty for a player.
2) Drone hat scanners. Drones have this built into their "drone tools", allowing them to scan a hat (taking a wee bit of time) to add it to the players headgear database (which is maintained round to round). From that point forward, the hat/mask is added to the whitelist for their camogear, allowing them to pick it that round and on future rounds.
3) The drone camogear is togglable off if you want to wear a REAL MAN'S HAT with lights, but starts on by default.

**Comment by coiax** [comment]
ALTERNATIVE IDEA: Extradimensional PunPun Hat Storage

Drones have infinite hat space to store headgear and hats, but it's not infinite or magical. If you put 1 hat in, you'll get 1 hat out. If you end a round wearing a hat, it'll be added to your hat space, but otherwise no dice.

MEANING:

Killing a drone means they will drop a hat as normal, and they won't be able to replace it without getting a new one (if they have any left in hatstorage or any are in the round).

**Comment by PKPenguin321** [comment]
Just close your PR instead of complicated hat black hole magic
It works fine as is jesus christ

**Comment by Bawhoppen** [comment]
yea no those are bad ideas too

**Comment by coiax** [comment]
Well, I've still tidied up a lot of code relating to chameleon gear and drones, so I'll just make the items adminspawn only and move the drone verb into an action for the item itself.

**Comment by coiax** [comment]
Right, this is ready for review/merge.

**Pull request closed without merging**
