### PR TITLE
The AI can recall the shuttle.

### PR DESCRIPTION
**Pull request by Incoming5643**
The AI can recall the shuttle.

:cl: incoming5643
rscadd: The AI can recall the shuttle.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
use periods nerd

**Comment by daman997** [comment]
no

**Comment by Zilenan91** [comment]
Fuck off, this makes traitor AIs even more cancerous.

**Comment by Bawhoppen** [comment]
for normal rounds this is going to be dumb but for malf ais it will actually make it so people need to go kill it

**Comment by swankcookie** [comment]
:+1: agree with Baw.

**Comment by Zilenan91** [comment]
Or the AI kills everyone/gets subverted and keeps recalling it for two hours so nobody can ever leave. This is awful.

**Comment by Incoming5643** [comment]
But malf AI COULD always recall. Look at the changes, I literally just took it off the malf tab.

**Comment by Bawhoppen** [comment]
thats why admins exist? besides all it takes is one guy to kill it if hes smart
and if admins aren't on theres always restart vote
I don't see any basis for your logic

**Comment by dumpdavidson** [comment]
>it doesn't even need a console to recall

That's even worse than what I thought when I read the title.

**Comment by Zilenan91** [comment]
Malf AI could do it, but they never did because it costed resources so it was not worth it. Now since it's free why not do it, why not make everyone suffer because lol antag

**Comment by Bawhoppen** [comment]
thats the same as some random guy calling it anyways
just gives AI the same option

**Comment by Zilenan91** [comment]
Yeah, but some random guy doesn't have secborg servants they can hack to have functionally infinite ammo laser guns and stuns, 3 thick rwalls, and turrets protecting him. The random guy also needs to have a comms board, and you can bet your ass people are gonna be watching if that thing gets stolen.

**Comment by Bawhoppen** [comment]
you can easily defend just as much as an AI
AIs are stationary and they only have a limited range of weapons to use
humans can use just about anything and run around like a nerd
comms board is not a problem really either

**Comment by Incoming5643** [comment]
Practical Effects of this:

Asimov: People can law 2 shuttle recalls as effectively as others can law 2 calls. Command can upload a 4th law to avoid this or kill the AI if they're being intentionally shitty. They can also just chase down the chuckle fuck law 2ing recalls.

Paladin: AI can't recall the shuttle if the crew is suffering. AI will probably recall if some chuckfuck breaks into the bridge and calls it because they're not legitimate authority.

Tyrant: AI can fuck with the shuttle if they don't respect the caller

Corporate: AI will only allow shuttle calls once it becomes obvious that nothing valuable is being done for the station anymore

Robocop: Come Quietly or there'll be... trouble!

**Comment by Incoming5643** [comment]
Also why are you arguing the merits of this for malfs? They've had this power, for free, for MONTHS.

**Comment by Zilenan91** [comment]
Get this meme out, AIs are not stationary. They can be moved literally effortlessly by any of their borgs. 

Also the issue here is for AIs in general, subverted or not. The fact that this PR is allowing a situation in which an AI can recall for a stupid amount of time just because they feel like it or because they can grief because antag/non-asimov and that this REQUIRES admin intervention to deal with is awful. Get that "crew can go kill it" outta here, because if the crew is literally so desperate as to ask the AI of all people to call it, shit is fucked beyond all belief that nobody is ever going to be able to actually kill the core.

**Comment by Bawhoppen** [comment]
Like I said, same thing with actual humans

**Comment by Zilenan91** [comment]
The AI is not a human. The AI has built in all access and a remote defib in the RDs office. Please close this, this will be horrible and hated I can guarantee it.

**Comment by Anonus** [comment]
Give it a yes/no prompt so the Ai doesn't accidentally recall.

**Comment by Incoming5643** [comment]
Spessmen can, and quite frequently do, ask the AI to call the shuttle the moment its done refueling. 

Sometimes it's valid, sometimes it's not. But I'm getting sick of slower play antags getting forced into rush mode lall the time because some random lizard in the bar sent the AI a PDA'd law 2 request saying they might have seen a cultist. It ruins escalation and renders a good number of rounds absolutely pointless.

@anonus good ideas

**Comment by Zilenan91** [comment]
You do realize the AI recalling the shuttle when cultists are confirmed would be a bannable law 1 violation right? I mean, I dunno about you guys but it's totally okay by Asimov to recall the shuttle and trap your entire crew in with a bunch of crazy death cultists.

This is going to create a lot of admin problems.

**Comment by Incoming5643** [comment]
If there are cultists running around sacing people in broad daylight then yes it'd be bad if the AI recalled and worth a bwonking, but that's not the kind of situation I'm talking about here. I'm talking about slower play antags, just getting their roots down when the shuttle is done refueling.

What your suggesting is the moment anyone suspects even the slightest chance of the round not being extended (and there's a 97% chance it's not) that the shuttle should be called. I think that's the wrong way to handle this. I think there should be subjectivity here, some IC oversight. I think this game plays best when it's allowed to actually play out. It's not always practical, but often it is.

**Comment by Zilenan91** [comment]
There's a difference between "oh hey there was a husked body in maint, we should call the shuttle as soon as it's available" and "oh hey there are some remains in the vacant office we should call the shuttle as soon as it's available"

You can kill the ling, you can't kill the cultists, so you leave. That's just how it is, if people are bad an get discovered early it should not be up to the AI to decide to help them out OOCly by recalling it.

**Comment by Incoming5643** [comment]
It's not the AI's job to validhunt aliens or pitch a fit and leave if they can't.

**Comment by Zilenan91** [comment]
It IS the AIs job to validhunt aliens because they're the single most powerful thing on the entire station. If the AI does not help sec kill lings who are very clearly non-human and harming other humans then they have a ban coming their way.

If the AI cannot prevent the antags from spreading to the point of being uncontrollable, it is time for them to leave. End of story. Massive human harm etc etc

**Comment by Incoming5643** [comment]
I disagree emphatically

**Comment by Zilenan91** [comment]
Do you play command/sec? Antag power will get to a point where you HAVE to leave or everyone will die. Allowing the AI to le law 2 recall for le infinite murderbone and le ahelp when the AI doesn't do it are going to happen and are going to be the epitomy of shittiness.

**Comment by Cebasiz** [comment]
i play AI constantly and don't even want this power

it's going to just mean law 2 shuttle ping-pong 90% of the time and the other 10% it's going to be an un-resolvable law one grey area ten thousand miles wide

pls no

**Comment by Incoming5643** [comment]
It's not a crisis if a bunch of people die, some rounds are supposed to go that way.

As far as I'm concerned the way most rounds are supposed to go is:

1.) Discover presence of antags
2.) Fight to beat/contain/destroy antags
3.) Call the shuttle if things are going too badly to recover from
4.) Leave

I feel like some players like to skip step 2 here.

I'll say it again

<b>Stand and fight!</b>

**Comment by GunHog** [comment]
I used to main AI before NTSL was gutted, and it is my opinion that this is not a wise idea, due to the nature of Asimov and that any subverted AI is going to make the crew suffer. 

I do not recommend this being given to any AI except Malfunctioning ones (if given their own mode again).

**Comment by Zilenan91** [comment]
Incoming, you very very clearly don't play sec or command at all.

**Comment by Incoming5643** [comment]
I only don't understand why people seem to only want to play this game to run away from it.

**Comment by Cebasiz** [comment]
while i do think that the shuttle call is usually way to early (and many times to "win" the round as if that actually matters) let's stay on topic about why it is a terrible idea to give the AI the ability to recall the shuttle, for many reasons including "lol plasma fire keep recalling :^)" and "i am subverted after the station has been murderboned and my master keeps telling me to recall time for 2 hour ghosttopia round"

**Comment by Incoming5643** [comment]
But muderboners with an comms console can already do that, and that requires admin intervention anyways. This isn't me causing a new problem, this is me not fixing an unrelated problem.

Players are always going to occasionally be terrible, but then that's why admins exist. It's not a proper argument against this.

**Comment by Cebasiz** [comment]
that is not the point, the point is what is the benefit?

i know i will see complaints in a month about "AI powercreep pls nerf" that will get more of the things i depend on to do my job as AI axed in favor of keeping something that is useless to me.

what is the benefit of giving the AI this power, because there is an opportunity cost of whining i'll have to listen to.

i don't see any benefit.

**Comment by Incoming5643** [comment]
I used to rely on the administration to know when a call was premature, they used to recall some of these calls, for the sake of the round. At some point this stopped happening. People kept clamoring for shorter and shorter rounds for quicker payoffs and more antags rolls However by allowing this it's railroaded much of round progression and made things painfully predictable in many cases.

Given this lack of agency from the playerbase and administration I started to look for code solutions to this problem. A lot of my bigger projects (Mulligan Antag, Various round scaling considerations, and in the furture Datum Antags) are at least partially designed to solve this problem. 

One of a few things simply needs to happen at some point:

1. The shuttle becomes harder to call.
2. The shuttle becomes easier to recall.
3. The shuttle becomes less important to round progression.
4. The playerbase collectively realizes that calling the shuttle to rush out rounds is damaging to the quality of the round. (This one is unlikely)

This is just another one of my "well maybe this fairly easy to impliment solutions can help" PRs. I want to conscript the AI to do the job that the Admins and the command staff are <b>supposed</b> to be doing.

**Comment by Zilenan91** [comment]
Incoming none of these things will EVER happen unless we get a higher standard of RP. OOCly I don't give a shit if Hanz Leonid has to work here because he can't get a job anywhere else because I don't feel like sitting around for 2 hours on a station with nobody else who RPs

**Comment by Incoming5643** [comment]
I feel like rain follows the plow in this case, if we give people more of a reason to think that their time on the station won't just be a 35 minute blip of nothing they might start at least giving a cursory effort to RP again, but I literally can't solve that problem.

**Comment by Zilenan91** [comment]
If we want more RP we need a more advanced medical system that aren't just people being flour sacks of health.

**Comment by Incoming5643** [comment]
Not my department.

Regardless even if people had really good arguments against this, we live in an era of test PR merges, and I'd like to see how it plays out in practice.

**Comment by Cebasiz** [comment]
but under asimov the AI can't even fucking recall, which means that this will never happen in practice

assistant: law 2 call shuttle

law 1 recall? how?

not only is it going to get complained about but unless the station is totally destroyed and the AI is subverted it will simply NOT EVEN BE POSSIBLE

**Comment by Cebasiz** [comment]
if lowtime instashuttlecall rounds are your concern you shouldn't touch AI. what needs to be touched is shuttle call time, difficulty of releasing singulo/tesla, antag progression and actually adding content that is accessed later than 15 minutes. not adding a hacky AI recall which can't even be used.

**Comment by Incoming5643** [comment]
Any AI that follows "Law 2: call the shuttle!" should follow "Law 2: recall the shuttle!".

I'd mess with the shuttle call time, but that's a server configuration.

Working on those other things.

**Comment by Cebasiz** [comment]
while that's true, it still means i'm going to spend many rounds pressing like 2 buttons and saying a reason over and over and over

i might as well be under orders to count floor tiles, except i can't refuse.

**Comment by Fox-McCloud** [comment]
>for normal rounds this is going to be dumb but for malf ais it will actually make it so people need to go kill it

Didn't think you could call the shuttle during Malf.

Also, I've personally seen this in action; it ends up being horrible---the AI recalling when it thinks the heads don't have any legitimacy to do so and traitor AI's spam recalling endlessly until their objective is complete.

**Comment by Zilenan91** [comment]
We don't have malf anymore here on /tg/, we rolled most of the functionality into traitor AIs, but people still call them malfs. Either way this is ping pong the pr and bad

**Comment by Incoming5643** [comment]
there's nothing intrinsically wrong with a little pong

**Comment by Zilenan91** [comment]
Yes there is. When the shuttle is called, it is time for the round to end. By recalling, people are extending the lifeline of an already dead round, leading to boredome, admin fuckery, and very likely an admin complaint because of them listening to the loads of dead people.

**Comment by Bawhoppen** [comment]
Like I already said, this can be done by a human just as easily as an AI if not easier, 
let it have the ability to recall so we can add more interesting situations

**Comment by Cebasiz** [comment]
there was a really terrible round on sybil like an hour ago that was artificially drawn out by the captain zeela takk

there was a critical loss of station integrity, attention span and situational awareness by the first 10 minutes due to a mass emagging and general chaos. i was AI and i basically stopped affecting the round about 20 minutes in because there was absolutely zero idea in my head or any of the people i asked who was the bad guy, who was the good guy, who was rogue etc. etc. 

some rounds just should not last past twenty minutes. once the heads and the AI start to lose control the station slides into anarchy quickly, and not really the interesting kind of anarchy where it's possible to act, interact with others or do anything. it's just random chaos and nobody knows or can affect the situation anymore at all.

basically, once a critical amount of situational awareness is lost the round becomes almost pointless for most of the station. dragging these sorts of rounds out when the station is a mess but NOTHING IS GETTING DONE due to general incompetence serves nobody.

**Comment by Bawhoppen** [comment]
that round in specific I think that the cap was justified in that recalling, there really wasn't anything THAT much wrong except a few blood stains on the floors

**Comment by Zilenan91** [comment]
Literally every door on the entire station was emagged open

**Comment by Bawhoppen** [comment]
they're fixable?????????

**Comment by Cebasiz** [comment]
yeah, every door was emagged, half the station was set to arrest, nobody on sec or any of the heads knew anything about who was even guilty of any crimes, station power was failing all over the place and engineering was doing fuck all to fix anything.

>emagged airlocks >fixable

technically. but fixing one door is like a 5+ step process and engineering was doing fuck all, as usual.

basically the situation was unsalvageable. no one knew what was going on and SA on everyone's part was totally nonexistent.

i have played and enjoyed 2 hour + rounds, but like i said once it becomes that helter-skelter nothing interesting happens anymore.

**Comment by Bawhoppen** [comment]
thats one round anyways
like I said, if a player is being a shitter with recalls thats what an admin is for
should not restrict game mechanics based on the rules

**Comment by Zilenan91** [comment]
So what you're saying is that admins should be forced to spawn spiders or ERTs or DSs every single time somebody ping pongs rather than eliminating their way of ping ponging wholesale? You do realize how angry people get when their antag round gets ended by an ERT right?

**Comment by GunHog** [comment]
It is really sad how eager everyone always is to restart the round. GOTTA HAVE DAT ANTAG ROLL! You are going to meet strong resistance given the current mentality of the players. Those who are not antag want a chance to roll for it again, those who are dead want the round over so they play again.

Until you break the overwhelming desire to call the shuttle for anything (including boredom!), you will have problems implementing things that extend round lengths.

**Comment by Zilenan91** [comment]
That above mentality will not happen unless /tg/ gets a higher standard of RP, which I do not see happening anytime soon. OOCly, nobody wants to die, and nobody wants to be bored, so we call the shuttle to stop both of these things, no regard for our characters because our characters do not exist in a lowRP environment.

**Comment by Buggy123** [comment]
Maybe if we weren't dead-set on keeping people from re-entering the round as fully-fledged humans after death people wouldn't want the shuttle to be called 10 minutes into the round. People are reluctant to even add in synths, when making each one is a shitton of work because you have to fully augment someone.

Honestly we should just enable respawns - if anyone takes advantage of information from their past life just ban them. That would probably fix 90% of the "I DED CALL IT" attitude. Seriously, what is the downside? People can already metafuck someone via posibrains or even drones if they want to, the only thing not enabling respawns does is forcing anyone who dies to stop having fun.

**Comment by Nanotransistor** [comment]
Please no, its already bad that the AI can call it.

**Comment by Incoming5643** [comment]
> Please no, its already bad that the AI can call it.

Lierally the only reason I haven't tried "the AI can't call the shuttle at all" is because it'd leave a hole in the AI UI that I'm not sure how to fill

**Comment by Anonus** [comment]
replace it with the bot interface so you don't need to go to the tab to use bot control, obviously

**Comment by YakumoChen** [comment]
What if the AI Recall had a 15 minute cooldown to prevent recall spam?

**Comment by Jazaen** [comment]
That would most likely work.

**Comment by Shadowlight213** [comment]
Why not just let the AI use the comms console to recall?
If you really need the shuttle to stay called you could just cut the cameras or decon the console.

**Comment by GunHog** [comment]
I agree with Shadowlight's suggestion there. It is a good way to stop the AI recalling without having to kill it. Whereas a <b>Malfunctioning/Traitor</b> AI has it built in (I am not sure if this is still true, @KorPhaeron please confirm). Of course, if the AI declares Delta, the shuttle does not leave anyway (Kor please confirm that as well)

**Comment by Bawhoppen** [comment]
just put it built in, seriously it will only be for good of rounds

**Comment by GunHog** [comment]
I am worried that the Anti-Silicon Brigade will complain endlessly about this until AIs are nerfed in other ways to compensate. They have no interest in the AI player's round quality or experience. I do not want this to be a talking point in their arguments to get AIs gutted or removed.

**Comment by KorPhaeron** [comment]
Delta stops the shuttle. Forgot to give them the malf recall though.

**Comment by Dorsisdwarf** [comment]
:-1: 

I detest the idea of actually having to recall the shuttle when someone shouts "; AI RECALL NOW NOW NOW" instead of being sarcastic at them

**Comment by optimumtact** [comment]
:-1:

**Comment by Incoming5643** [comment]
I forgot this was open :facepunch:

**Pull request closed without merging**
