### PR TITLE
Beefs up door security

### PR DESCRIPTION
**Pull request by ShizCalev**
Implements better door security across the station.

Doors with access to sensitive equipment, such as the Gravity Generator, the Supermatter Engine, the Armory, and Telecomms, will all now take a few extra steps to hack into.

Doors with security protection levels beyond AIRLOCK_SECURITY_METAL will now also have their wiring randomized.

Adjusted the time it takes to hack into a higher security airlock (delay is decreased by toolspeed);

**OLD**
AIRLOCK_SECURITY_METAL = 4 seconds
AIRLOCK_SECURITY_PLASTEEL_I = 12 seconds
AIRLOCK_SECURITY_PLASTEEL_O = 20 seconds
AIRLOCK_SECURITY_PLASTEEL = 21 seconds _(only used by CENTCOM zlevel & vault doors)_

**NEW**
AIRLOCK_SECURITY_METAL = 4 seconds
AIRLOCK_SECURITY_PLASTEEL_I = 10 seconds
AIRLOCK_SECURITY_PLASTEEL_O = 16 seconds
AIRLOCK_SECURITY_PLASTEEL = 17 seconds _(only used by CENTCOM zlevel & vault doors)_

:cl: ShizCalev
balance: Due to an increased threat of hostile presence across Nanotrasen stations, the security levels of doors onboard all stations has been increased. In some cases, internal wiring of such doors will also now be randomized to further heighten their security.
/:cl:

Also corrected a few incorrectly named airlocks / windoors in a couple locations.

### CODE REVIEW

**Comment by Buggy123** [comment]
What do you mean exactly by "a few extra steps"? Instead of screwdrivering to open the circuitry, you have to, say, wrench+welder+screwdriver?

**Comment by ShizCalev** [comment]
@Buggy123 Yes.

**Comment by ShizCalev** [comment]
AIRLOCK_SECURITY_METAL = Welder
AIRLOCK_SECURITY_PLASTEEL_I = Welder, Crowbar, Welder
AIRLOCK_SECURITY_PLASTEEL_O = Welder, Crowbar, Welder, Crowbar, Welder
AIRLOCK_SECURITY_PLASTEEL = = Welder, Crowbar, Welder, Crowbar, Welder, Wirecutters

**Comment by ACCount12** [comment]
>Doors with security protection levels beyond AIRLOCK_SECURITY_METAL will now also have their wiring randomized.

This is too much. Having a massive delay on hacking is bad enough as it is.

**Comment by RandomMarine** [comment]
But why?

**Comment by ShizCalev** [comment]
@RandomMarine 
So the entire station isn't just a game of memorize power wire and crowbar the door open for full access. Now airlocks take a few more moments to open up, and in the case of super-high-security-areas, figure out which wire actually opens them up.

**Comment by ACCount12** [comment]
Tgstation's favorite game of balance: trying to solve the ingame issues with mechanics, and failing miserably.

I don't see how this change is any good for the game, especially the "random wires" part. It just makes airlocks much more annoying for everyone. Given how often I, as engineer or security officer, have to hack into things just to keep the station from spiraling even deeper into the abyss, it doesn't look good at all.

**Comment by PKPenguin321** [comment]
Yeah this is too much

**Comment by 81Denton** [comment]
That's not terrible, I mean you usually just find a random door, pulse it until you hit the aux power wire (bolts too if you're feeling generous) and basically have all access until the end of the round.

Even reinforcing airlocks with metal/plasteel is currently pointless, who's gonna try to break them if you can just pulse a wire and crowbar?

**Comment by ACCount12** [comment]
Reinforced airlocks are NOT HACKABLE until you remove the reinforcing plates. That's why I say that just reinforcing them is more than enough.

**Comment by Tlaltecuhtli** [comment]
rcd rofl

**Comment by CPTANT** [comment]
This places too much power on having an rcd versus not having one.

**Comment by arsserpentarium** [comment]
Hacking should be reworked. But not sure how. And not this way,I think.

**Comment by Jalleo** [comment]
@ShizCalev Everyone forgets that you can set it so each department and high security doors in general have different wires. This would make hacking much more difficult.

**Comment by KorPhaeron** [comment]
The harder you make it to sneak into places or break into places the more it pushes players towards lazily clicking on people with a double esword

**Comment by ShizCalev** [comment]
@korphareon
You can't afford a double esword if you have to buy an emag to get into the armory quicker though :^)

**Comment by Cyberboss** [comment]
The random wires does seem to be overkill imho

**Review by Cyberboss — APPROVED** [review]

**Comment by Tlaltecuhtli** [comment]
this encourages antag maxcapping doors to open them

**Comment by Robustin** [comment]
What Kor said. Most people don't even bother with hacking as it is because insulated gloves + tools are only readily available to a handful of crew.

What convinced you that the bar needed to be raised even higher? At that point I would just remove my toolbelt and use an RCD for hacking.

**Comment by KorPhaeron** [comment]
@shizcalev

I can just double esword the door down though

**Comment by Durkel** [comment]
I knew the moment that increased door security was merged that this day would eventually come. All this is going to do is piss off players.

**Comment by epochayur** [comment]
TG station, more like Time Gate station, amirite

**Pull request closed without merging**
