### PR TITLE
Adds persistent trophy cases

### PR DESCRIPTION
**Pull request by Profakos**
I got permission for it, so I remade and tweaked version of #22312 

Tweaks from the previous PR:
When a new item is inserted into a trophy case, it will be added to the old_trophy_list, to be saved at the end of the game. The global list of trophy cases is still required to set them up though, we just don't need to poll them anymore. I suppose they can still be used for a possible Reroll Trophy Cases admin button in the future. 

If the case gets enough damage, instead of breaking, it will always deconstruct. If the item inside was a roundstart showpiece, it will crumble to dust, otherwise you can recover it.

Saving uses JSON instead of strings! It also logs the ckey of the person who  placed the item inside.

Trophy cases also have a burglar alarm because it felt thematic.

Also updates display cases to use Initialize and QDEL_NULL where needed.

I thought about using the persistence_replacement type of saved items, but the only relevant item that would causes issues, the nuclear authentication disk, can not be placed there in the first place, thanks to the cargo blacklist.

:cl: Kor, Goof and Plizzard
add: Adds persistent trophy cases. They are not on any map yet.
/:cl:

### CODE REVIEW

**Review by lzimann — DISMISSED** [review]
I really dislike the idea of persistance in this game in any way. So this is a big no from me.

**Comment by Iamgoofball** [comment]
@lzimann it's literally pure cosmetic you fucknizzle and @KorPhaeron wanted it

**Comment by lzimann** [comment]
Then kor can come here and merge it, which he will probably do.

**Comment by optimumtact** [comment]
Don't use reviews unless you have code related stuff you meme

**Comment by KorPhaeron** [comment]
What a hero

**Comment by bgobandit** [comment]
what happens with:
- the nuke disk
- gamebreaking traitor items
- all of the above in bags of holding

**Comment by KorPhaeron** [comment]
>If the case gets enough damage, instead of breaking, it will always deconstruct. If the item inside was a roundstart showpiece, it will crumble to dust, otherwise you can recover it.

**Comment by optimumtact** [comment]
When they come back in a new round, are they the original item's type path or do they just have it's icon as a fake item or similar?

there are a couple of things that might shit the bed if there are more than one of them

**Comment by Profakos** [comment]
They use the original item's path, but you are right, on further thought this is unsafe. Not mentioned things that add themselves to global lists, like GPSs. I'll soon update this with a dummy item.

**Comment by Profakos** [comment]
Made the showpiece dummy. I am not sure if I used initial properly.
Anyways, looks like I have to fix the check for illegal items: it only checks the item that is placed in, and won't examine the contents, so you would be able to insert folded up bluespace bodybags with people in them. I need to change it to check contents too.

**Comment by KorPhaeron** [comment]
:tada:

Thank you for finishing this

**Comment by Profakos** [comment]
No problem. Let me know if there are any issues. 
Also right now they are not ID locked, but hiding them behind directional windows and a windoors could solve that.

**Pull request merged**
