### PR TITLE
Fixes a very common runtime involving incorrect proc signature on MakeSlippery overrides

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
If you use named args you gotta have the arguments in your proc signature otherwise the code just breaks. This time the results are invisible to the players since the overrides are for making the proc do nothing, which runtiming instantly also facilitates.

```
[19:52:48] Runtime in , line : bad arg name 'min_wet_time'
proc name: MakeSlippery (/turf/open/space/MakeSlippery)
```

:cl: Naksu
code: Fixed an incorrect signature in MakeSlippery causing runtimes
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
@kevinz000

**Comment by kevinz000** [comment]
Sorry!

**Comment by optimumtact** [comment]
god this shit annoys me, I wish it was a compile error

**Comment by praisenarsie** [comment]
then make travis whine about it

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
