### PR TITLE
telescopic baton left right click swapped, yet again code improvements

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

code improvements on not using params anymore but the new alt attack procs. Also, moved the batons into their own file as there was actually a good few items that branch from the police baton originally.

~~needs #56663 merged first~~ merged!

Also, switches the left click action to the right click.
more talk about that on #56686 

## Why It's Good For The Game

Literally has the same problem as stunbaton but arguably worse because you're a wimpy RD who will then get beaten up by assistants who just dinged off the validness of your baton crack

## Changelog
:cl:
tweak: telescopic baton knockdown has been moved to right click
/:cl:

### CODE REVIEW

**Comment by Pugie** [comment]
satanic evil and awful

**Comment by Fikou** [comment]
why would you do "more talk on #56686", if both arent merged at the same time it will be shittily inconsistent it should be in 1 pr

**Comment by tralezab** [comment]
I'm atomizing, fikou. look it up!

**Comment by Fikou** [comment]
ITS NOT ATOMIZING ITS MAKING IT SHITTY POOPY CRAPPY

**Comment by RaveRadbury** [comment]
This is a bad idea, the harm is a **secondary** feature, the primary feature is non-violent stunning. You're making more work for admins dealing with newfriends with this change.

**Comment by tralezab** [comment]
Harming has and is the primary feature on 99% of the items in the game, randomly and arbitrarily deciding to make the harm button and nonharm button swap for a few items is the exact opposite of fixing the issue you're mentioning here.

**Comment by RaveRadbury** [comment]
> Harming has and is the primary feature on 99% of the items in the game, randomly and arbitrarily deciding to make the harm button and nonharm button swap for a few items is the exact opposite of fixing the issue you're mentioning here.

Yeah but this is the 1% that it **isn't** the intention for. We have _granularity_ for these subtleties, otherwise they would all be default and you wouldn't be trying to make this change in the first place.

**Comment by tralezab** [comment]
I don't really follow on your point there, why nearly all items should be consistent with eachother except for these couple. Even the base system has harm on left click and a disarm move on right click, I can't see it as anything but confusing

**Comment by RaveRadbury** [comment]
Primary click should do primary function. Monkey brains know this, and the monkey brain overrides during times of stress. I see where you're coming from on it, ultimately I guess there's no good solution, both sides have flaws imo. Glad I'm not the maintainer deciding on this.

**Comment by willox** [comment]
am i an idiot or does nothing in this thread explain what the behaviour is being changed to? i'd just read the diff if it wasn't an entire file change

**Comment by tralezab** [comment]
@willox drat I was just typing out a long explanation

**Comment by necromanceranne** [comment]
> Harming has and is the primary feature on 99% of the items in the game, randomly and arbitrarily deciding to make the harm button and nonharm button swap for a few items is the exact opposite of fixing the issue you're mentioning here.

The batons literally ARE the exception to the rule of all the melee weapons in the game. This only makes sense if batons followed the games standard pattern for weapons. But they don't. 

The classic baton's primary effects and abilities are entirely in the non-harmful attack, otherwise they wack with no extra effects. 

Stun batons will stun regardless, but they have an internal cooldown for their next stun attack, otherwise they're just wacking for a small amount of brute and only apply their effects once the cooldowns are off.

This isn't arbitrary, it's by literal design that they are the exception to the rule. You are trying to fit a square block through a round hole.

**Comment by tralezab** [comment]
"If it helps, think in terms of 'I'm pressing left click when I want to complete a fight or takedown, I press right click when I want to set up for a takedown or apply some other effect adjacent to bringing the fight to a close'."

Surely you realize that this is a bong rippingly insane thought train to come up with, and nobody wants to be going through that veteran's day mental battlefield mid fight. This is only going to stick out more and more as more items gain special abilities and otherwise flushed out controls on their right click. I'm putting forward changes that nip this issue in the bud before we make it le actual painful debate far into the future where the wikis, players, coders, whathaveyou say "oh but some dudes were shittin' n' sittin' so while most items work how you expect these ones won't. sorry new player" And some people who now have learned and stuck with the combat mode will ape about any changes

<details>
  <summary>My point</summary>
  
  
  image
  
</details>

**Comment by RaveRadbury** [comment]
Now you're just being a dick.

**Comment by tralezab** [comment]
It's a little humor for the poor souls who have to scroll past our beams of pure bike sheddery

**Comment by RaveRadbury** [comment]
Idk, man, it looks like you sticking your fingers in your ears and mocking people who disagree with you but took the time to share their thoughts. People who also care about the game and think about it as much as you do.

**Comment by tralezab** [comment]
And I'm not sharing mine? In the end a maintainer will end this debate for us both by picking. There's a difference between not listening and not being convinced, and i'm safely in the second group on this.

**Comment by RaveRadbury** [comment]
There's disagreeing with someone or saying that an idea is bad, then there's calling their thoughts "bong rippingly insane" and putting however much effort as you did into making that really mocking meme. I guess you feel like you're under attack and need to defend yourself, but we're all a community here and I feel really hurt by what you did with my words.

I'm sorry if I've made you feel bad with my criticism, it was never my intention.

**Comment by tralezab** [comment]
Alright that is my bad, contributing for long enough on github will turn what you intend to be neutral comments with a little fun-to-read flair into something that comes off as pretty hostile. I mean you and I are on good terms so I shouldn't be smack talkin' like you're any old github commenter out for contributor blood

**Comment by RaveRadbury** [comment]
I appreciate that, thank you.

**Comment by necromanceranne** [comment]
> Surely you realize that this is a bong rippingly insane thought train to come up with, and nobody wants to be going through that veteran's day mental battlefield mid fight. 

I'm trying to liken this to your own train of thought. If you want to assume 'harm is left click, disarm is right click', then unfortunately batons just don't follow that pattern because they do both in the same attack. 

They're doing damage AND disarming, AND disabling all in the same click, because the attack proc is overloaded as hell. That's my point.

**Comment by cacogen** [comment]
The stun baton's primary attack is stun, so left-click should be stun.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Same feedback as last one. Left click is not always harm, stop thinking in terms of intents.

Left click is primary action, the one you usually want. Right click is the secondary action. You'll *usually* want to stun with this.

**Comment by ATH1909** [comment]
> Same feedback as last one. Left click is not always harm, stop thinking in terms of intents.
> 
> Left click is primary action, the one you usually want. Right click is the secondary action. You'll _usually_ want to stun with this.

but the stun attack is the special attack/special function that batons get that normal weapons don't, so it should be on right click.

**Comment by tralezab** [comment]
not worth GBP cost

**Comment by cacogen** [comment]
I know right talk about perverse incentives

**Pull request closed without merging**
