### PR TITLE
can't answer calls 'cause i'm baseballin - adds a baseball recipe to leather

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
baseballs can now be crafted with 3 leather

## Why It's Good For The Game
throwing interactions (correct me if i'm wrong but you literally can't get these out of mail goodies, outside of having the throwing arm quirk or the holodeck)

## Changelog

:cl:
add: Baseballs can now be crafted with 3 leather.
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
Isn't this the second recipe for basket ball? The basket ball DLC Pr added one for 20(wtf) leather

**Comment by Hatterhat** [comment]
> Isn't this the second recipe for basket ball? The basket ball DLC Pr added one for 20(wtf) leather

this is for the baseball, not the basketball

**Comment by newfren** [comment]
this seems like kinda a lot of leather

**Comment by Hatterhat** [comment]
> this seems like kinda a lot of leather

yeah i guess it is. maybe i should drop both the basketball and baseball to slightly more reasonable amounts considering they're just things for spacemen to play with

**Comment by timothymtorres** [comment]
Hi.  I specifically did not want people to be able to spam basketballs without going through a little effort which is why the material costs are high and hoops require durathread.  Almost required air to be pumped as a requirement but ran out of time developing it.

I'd argue your leather costs are too low and make producing them a really cheap time investment.

**Comment by Hatterhat** [comment]
> Hi. I specifically did not want people to be able to spam basketballs without going through a little effort which is why the material costs are high and hoops require durathread. Almost required air to be pumped as a bonus requirement but ran out of time developing it.
> 
> I'd argue your leather costs are too low and it will be a really cheap time investment to mass produce them.

i can't see a problem that comes to mind in regards to mass production of what is literally a 0-throwforce 0-force ball. i mean i guess if you want people to not just scam a basketball game by bringing two basketballs of their own (and then probably get beat up by the other assistants) then sure that cost is fine, but - these are baseballs. as far as i know you can't really acquire these outside of the holodeck sim or by having the throwing arm quirk. i don't see the harm in letting spacemen have a ball to throw at their fellow spacemen (or dogs. or cats. or other suitable things to throw a baseball at)

**Pull request merged**
