### PR TITLE
Adds a new clown mask skin

### PR DESCRIPTION
**Pull request by CRTXBacon**
[Changelogs]: Adds a new Deltarune inspired mask for the clown

:cl: CRTXBacon & Nepeta33Leijon
add: New clown mask skin that CRTXBacon totally wasn't forced to help with.
/:cl:

[why]: Nepeta forced me to do this help he's holding me against my own will

### CODE REVIEW

**Comment by epochayur** [comment]
yikes!

**Comment by 81Denton** [comment]
yikes!

**Comment by CRTXBacon** [comment]
I regret helping to make this

**Comment by MrDoomBringer** [comment]
this aint it, chief

**Comment by Repukan** [comment]
Yikes

**Comment by MrDoomBringer** [comment]
image
pic of it cus for some raisin op didnt provide

**Comment by ChahutMaenad** [comment]
i tried my best but jevil just was never meant to be drawn on such an unnaturally small scale 
jevilfeels

**Comment by fludd12** [comment]
Chaos, CHAOS!

**Comment by MrDoomBringer** [comment]
i can do EVERYTHING

**Comment by Militaires** [comment]
the game sucks shit

**Comment by FantasticFwoosh** [comment]
I think someone will look back at this someday and think what in the hell are we doing chasing this burnt out meme. Still i support it for variety.

**Comment by ChahutMaenad** [comment]
i tried to add a candy corn horn headband a while back but got ree'd at by people for apparently being a harbourstation dev alt

thanks

**Comment by CRTXBacon** [comment]
can we ignore this and pay attention to my actually good PR

**Comment by ChahutMaenad** [comment]
no

**Comment by Anonmare** [comment]
I can do anything

**Comment by evsey9** [comment]
@Anonmare  can you merge this pr, then?

**Comment by ExcessiveUseOfCobblestone** [comment]
yes but she chooses not to

**Review by SpaceManiac — APPROVED** [review]
image

**Comment by 81Denton** [comment]
the absolute madman

**Comment by CRTXBacon** [comment]
Helping make this was a mistake and I heavily regret doing so.

**Comment by CRTXBacon** [comment]
image

**Comment by epochayur** [comment]
\>tfwnsgf

**Comment by ExcessiveUseOfCobblestone** [comment]
With this character's death, the thread of prophecy is severed. Restore a saved game to restore the weave of fate, or persist in the doomed world you have created.

**Pull request merged**
