### PR TITLE
Kinetic accelerator cannon

### PR DESCRIPTION
**Pull request by MadmanMartian**
A ripley-mounted PKA.

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl:
add:  Adds a mech-mounted kinetic accelerator cannon. Fires 3 kinetic projectiles at a time.

/:cl:

[why]: Somebody suggested something similar to it in the discord, so I thought I'd give making a mecha weapon a shot.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
don't remember pressing for a review. Odd.

**Comment by Repukan** [comment]
Fuck no

**Comment by XDTM** [comment]
It's automatic if you touch certain files

**Comment by MadmanMartian** [comment]
Oh. Seems like it'd become a pester, but I guess that's what you do here.

Wasn't sure where to put it in the techweb, so put it with the drill. I can put it somewhere else if needs be.

**Comment by Repukan** [comment]
Not sure why you're giving a MINING mech more combat prowess than the Phazon, Durand and Gygax

**Comment by Ratvar** [comment]
Because miners need some way to kill all megafauna just by outdamaging it, maybe? Anyone can check if shielded-regenerating mech can shoot bubblegum down first?

**Comment by ExcessiveUseOfCobblestone** [comment]
Remove the plasma cutter and i'm interested ;)

**Comment by MadmanMartian** [comment]
Holy crap, maybe I should've done more research into the mech weapons here.

**Comment by XDTM** [comment]
Tbh mining weapon balancing is all kinds of fucked because someone decided that lavaland monsters needed to be killed only with mining weapons, but the mining weapons must in turn not be stronger than normal weapons in other contexts.

If someone were to drop the health/resistances of lavaland mobs as well as remove/reduce the lavaland weapon bonus damage on low pressure, you wouldn't end up with KAs being top of the line space fighting equipment. And as a bonus guns would actually be somewhat viable for hunters if they get their hands on some.

**Comment by GunHog** [comment]
Is it possible to make this weapon equal to the standard KA, except with more space for adding upgrades?

**Comment by optimumtact** [comment]
Mining balance is broken because of how many mining weapons and options there are.

Fix the core game loop first before trying to add more to mining

**Comment by MadmanMartian** [comment]
Specifically what would need fixing in that regard?

**Comment by optimumtact** [comment]
I believe that there are now too many mining weapons. They all need to be gutted back to the KA and maybe the crusher as the melee option.

All other weapons should be removed and replaced with a comprehensive system of module upgrades from mining vendors so there's actually a reason to get points.

**Comment by MadmanMartian** [comment]
Rightio

**Pull request closed without merging**
