### PR TITLE
Allows hardsuit helmets to be used for internals.

### PR DESCRIPTION
**Pull request by Kelenius**
## About The Pull Request

Allows ~~spaceproof~~ hardsuit helmets to be used for internals. Some code cleanup; fixed a few places where breathing tube wasn't respected.

## Why It's Good For The Game

QoL change.

## Changelog
:cl:
add: Hardsuit helmets can now be used for internals without a mask.
/:cl:

### CODE REVIEW

**Comment by Kelenius** [comment]
> This probably needs to be its own flag unless you want people to breathe through their hard hats

Well today I fucking learned that it's fine to go into space in a simple hard hat that doesn't even cover your face.

I'll fix it.

**Comment by Fhaxaris** [comment]
i like dis cuz with it i am able to partake in smoking whilst bearing hardsuit or eva

**Comment by tmtmtl30** [comment]
smoking while helmeted should cloud up your view until eventually it becomes completely opaque and taking your helmet off produces a smoke cloud

**Comment by optimumtact** [comment]
I dis like this because it's a buff and powercreep

**Comment by Doosteroni** [comment]
I did like orange’s opinion because vaping in a Hardsuit is awesome

**Comment by Doosteroni** [comment]
What if we like......removed space so no one needs air. Problem solved.

**Comment by Tharcoonvagh** [comment]
might as well just remove breath masks
powercreep

**Comment by Kelenius** [comment]
Consider that hardsuit helmets are much rarer than masks (and literally every crew member starts with one), and also that if your helmet is removed for some reason while you have no mask, your internals will be interrupted, so it's still safer to have a mask under the helmet.

**Comment by Kelenius** [comment]
Gib merge

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> I dis like this because it's a buff and powercreep

**Pull request closed without merging**
