### PR TITLE
Adds sprite for .50 incendiary magazine.

### PR DESCRIPTION
**Pull request by Helg2**
## About The Pull Request
It was just invisible which wasn't quite cool.
Its mostly coder sprite so suggestions accepted.
image
image
image
## Why It's Good For The Game
It wont be invisible.
## Changelog
:cl:
image: .50 incendiary magazine now has sprite.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Oh that's weird, I thought I had one for it. It definitely existed during testing. Must have been lost in a branch update.

**Comment by ShizCalev** [comment]
Incendiary definitely did have a sprite before.

**Comment by Helg2** [comment]
I'll take some time to think up to making it better.

**Review by Wallemations — APPROVED** [review]

**Comment by Wallemations** [comment]
> Incendiary definitely did have a sprite before. Time for more unit tests! :3

Do you want me to not merge this so you can figure out what happened, or just go ahead with it?

**Pull request merged**
