### PR TITLE
[WIP] Cosmetic Changes for KiloStation

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This pull request aims to provide cosmetic improvements to Kilo by changing floor decals to match a few design principles:

Caution Strips will now only be around hazardous objects or heavy machinery
Trimlines will designate entrances to departments and primary workstations
Old floor decals will designate secondary workstations or storage areas
Box decals will designate places with trip hazards, disposal units, or storage for heavy/dangerous objects.

These design principles will not sacrifice the high contrast design of Kilo, but will instead work to highlight a lot of the great work that Okand has put into the map. I do not intend to edit anything other than decals or minor objects which need to move a tile or two.

As an example of what I've done already with Science:

Old:
Science1Old
Science2Old

New:
Science1New
Science2New

AI:
AI Old
AINew

## Why It's Good For The Game

Better decaling on the map will make it easier for players to understand where things are and what is dangerous.

New trimlines will help develop a sense of order and visual appeal without sacrificing the high contrast design.

## Changelog
:cl:
add: KiloStation has received a floor decal facelift
/:cl:

[Okand has approved of me making these cosmetic changes]

### CODE REVIEW

**Comment by wesoda25** [comment]
God bless you

**Comment by CAPTTLasky** [comment]
Also, I know that the decals for science are PINK instead of purple. That's a sprite issue but I'll see what I can do to make them match the department closer.

**Comment by CAPTTLasky** [comment]
I also intend to work on this superfast and get it done tomorrow or Saturday to prevent map merge conflicts because I am very afraid of them.

**Comment by tralezab** [comment]
thank you jesus

**Comment by Dorsisdwarf** [comment]
priority merge

**Comment by actioninja** [comment]
We changed policy on WIP prs but considering this is a map and it could theoretically be tested at any time I'll let it slide.

**Comment by 81Denton** [comment]
He was a good man... *lip smack* 
What a rotten way to die

**Comment by wesoda25** [comment]
???

**Pull request closed without merging**
