### PR TITLE
Syndicate Armblade Injector

### PR DESCRIPTION
**Pull request by Time-Green**
A geneticist/CMO only traitor specific item. 
It's a mutation and can be replicated and given to others. It's a concealed weapon to everything but the DNA console.
Also people might mistake you for a real changeling wich is fun.
Costs 9tc
:cl: Time-Green
rscadd: Adds a job specific traitor armblade mutation injector for the Geneticist and CMO
/:cl:
why?: It's another cool job specific item and can fuck with people by making them think you're a changeling. There's also no others mutations in the syndicate uplink so let's change that.

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Does it do as much damage as the real Arm-Blade?

**Comment by Time-Green** [comment]
Yeah, 25 damage. I'll change that to 20 since otherwise it's infinite esword injector

**Comment by Time-Green** [comment]
I could go for an inbetween

**Comment by Borisvanmemes** [comment]
E-swords do 30 damage, i'd say that lowering the damage of this is kinda a bad idea due to the fact that it already costs one more.

**Comment by anconfuzedrock** [comment]
eswords do 30 + deflect shit, duals do 34.
I think this is just bloat, armblades can already be made with an emagged limb grower too.

**Comment by Tlaltecuhtli** [comment]
emagged limb grower does a really similar thing

**Comment by HomocidlePancakes** [comment]
You can't conceal the one from limbgrower and you need someone to attach it to you

**Comment by OverlyGeneric** [comment]
Wouldn't it be easier to e-mag a limb grower and lie that you got an e-mag from a traitor going SSD?

I've gotten away with that several times.

**Comment by Time-Green** [comment]
I’ll raise damage back to 25
This blade is concealable, can easily be given and taken and does not need a second person

**Comment by PKPenguin321** [comment]
Just curious, where in the code is this excluded from DNA scanners?

**Comment by Time-Green** [comment]
Nowhere. Unless you mean it not showing up in the gene pool, wich is locked = TRUE

**Comment by optimumtact** [comment]
I don't like this, it's just a changeling item ported to another job
lazy effort imo.

**Comment by zxaber** [comment]
It's more interesting than changelings, and giving the whole crew hidden armblades sounds like a fun gimmick.

**Comment by optimumtact** [comment]
it doesn't sound like a fun gimmick, it sounds boring, like the rest of them

**Comment by tralezab** [comment]
At least out of all of those. My point was that the arm blade is everywhere and has lost its charm

**Comment by nicbn** [comment]
Reusing armblade everywhere is unoriginal, and "lol they will think I'm a ling" won't work because everyone will realize traitors can get armblade too

**Comment by necromanceranne** [comment]
Xenobio can produce a lesser armblade with consistency even. They even can become lings.

**Pull request closed without merging**
