### PR TITLE
Grammar Fix

### PR DESCRIPTION
**Pull request by AliiTea**
https://github.com/tgstation/-tg-station/issues/10692
Fixed the grammar issue with the Hugbox.

### CODE REVIEW

**Comment by Memendia** [comment]
Thanks WJohn

**Comment by ike709** [comment]
"Fixes #10692" in OP

**Comment by daman997** [comment]
the desc for the orange is "It's an tangy fruit" gamebreaking bug pls fix

**Comment by Memendia** [comment]
@daman997 This pr is for the hugbox not the orange..

**Pull request merged**
