### PR TITLE
Fixes a negative sqrt

### PR DESCRIPTION
**Pull request by Cyberboss**
The following runtime has occurred 4 time(s).
runtime error: illegal: sqrt(-14.000000)
proc name: Choke (/datum/symptom/choking/proc/Choke)
  source file: choking.dm,51
  usr: null
  src: Choking (/datum/symptom/choking)

### CODE REVIEW

**Comment by MrPerson** [comment]
Our imaginary spessmen can't deal with imaginary numbers

**Comment by Shadowlight213** [comment]
Huh. I swear a pr was made fixing this already.

**Comment by XDTM** [comment]
There's plenty of sqrts in virology code

**Comment by ChangelingRain** [comment]
MADISON

**Comment by ChangelingRain** [comment]
MADISON SAID THIS WAS FINE GOD DAMN IT MADISON

**Pull request merged**
