### PR TITLE
Adds lizard tail wagging

### PR DESCRIPTION
**Pull request by RemieRichards**
Lizards can now start and stop wagging their tails
- Adds wag emote, sets tail to wag forever
- Adds stopwag emote, stops tail wagging

Modified (sprite adjustments to suit our lizards better, plus greyscale not blackscale) port of: https://github.com/ParadiseSS13/Paradise/pull/987

gif:
poop

this umm.. shit this one... fixes... realism? cuteness?

### CODE REVIEW

**Comment by Man-Shroom** [comment]
>This over dismemberment code that is over 50 years old

**Comment by Fox-McCloud** [comment]
So glad to see my tail-waggin' goin' places =p

:+1:  x :100:

**Comment by Incoming5643** [comment]
Horrifying, a gross perversion of the fledgeling mutant_bodyparts system.

:+1:

**Comment by Iamgoofball** [comment]
:-1: please no

**Comment by Incoming5643** [comment]
seriously though if @WJohn ever gets around to greyscaling those lizard bits he keeps making animated tails would increase how much would have to be added, like, a lot.

**Comment by WJohn** [comment]
I don't know how to feel about this.

**Comment by Stickymayhem** [comment]
disgustingly adorable

**Comment by daman997** [comment]
im ok with this

**Comment by Stickymayhem** [comment]
>this umm.. shit this one... fixes... realism? cuteness?

Confirmed fix please merge ignore freeze.

**Comment by GunHog** [comment]
WHEEEEEEEEEEEEEEEEEEEEEEEEE :+1: SWINGS-HIS-TAIL CAN BE TRUE TO HIS NAME!

**Comment by ZomgPonies** [comment]
Why didnt you port the catbeast tailwagging at the same time? *Adds fuel to powderkeg*

**Comment by RemieRichards** [comment]
@ZomgPonies because we don't have the catbeeests and that'd only aggravate goofball more :P

**Comment by GunHog** [comment]
Add Cat-people pl0x. Trolling furry haters is ALWAYS worth it.

**Comment by RemieRichards** [comment]
The only cat people I'd add is normal humans but with permanent kitty ears + tails :3

**Comment by GunHog** [comment]
>The only cat people I'd add is normal humans but with permanent kitty ears + tails :3

I am 100% okay with that!

**Comment by Supermichael777** [comment]
honestly are we even respecting the freeze any more?

**Comment by Iamgoofball** [comment]
sod off @Supermichael777

**Comment by ZomgPonies** [comment]
@RemieRichards He tried removing ponies from Paradise, the least I can do for him is try to get catbeasts added to tg :laughing:

**Comment by Thunder12345** [comment]
>The only cat people I'd add is normal humans but with permanent kitty ears + tails :3
*throws money at screen*

**Comment by Fayrik** [comment]
Bring back corgi people when.
Corgi people may not have tails to wag, but that's beside the point.
I miss being able to roleplay as Barf.

**Comment by Dorsisdwarf** [comment]
The up/down wag looks bad, look at spacecarp for an idea of how to do side/side wagging.

Oh also this is a terrible idea, unless you give humans an emote that lizards can't do. (I vote '*signs_up_as_a_command_role')

**Comment by WJohn** [comment]
Yeah I'm not a fan of movement on otherwise static sprites, especially when nothing else moves in this game. It also prevents us from ever having lizard-specific tail clothing in the future, or severely limits it since it'll need all these animations no one will want to do.

**Comment by Dorsisdwarf** [comment]
@Miauw62 
You instaclosed #9406 'till the end of the month for disrespecting the feature freeze, remember to treat all PR's equally.

**Comment by Miauw62** [comment]
i have no fucking idea of what to do anymore since cheri slaps dnm tags on everything instead of closing it but vOv

**Comment by SconesC** [comment]
This looks horrid especially considering we have no other idle animations on players

**Comment by Xhuis** [comment]
onz

**Comment by Cheridan** [comment]
@Miauw62 In the past people have expressed that they don't like temporary closing because it doesn't update the PR with new commits while closed

**Comment by demonfiren** [comment]
Side to side wagging is probably preferrable, here.

Still, it is good to see the mustard rice get the attention it deserves.

**Comment by Steelpoint** [comment]
Personally I think it would be nice if we could find a way to 'mirror' clothing onto someone's tail for exosuit clothing.

So wearing a Space Suit would cover your tail in a space suit.

Either way this is a amusing change that furthers the divide between Humans and Non-Humans. I'm sure I could bullshit a essay about the connection between SS13 and real life racism.

:+1:

**Comment by peoplearestrange** [comment]
:+1: cuteasfuck

**Comment by Miauw62** [comment]
people complain about not being able to disguise as anybody but casually suggest "wearing a space suit as a lizard should display a space suited tail so you can be a snowflake in any clothing"

**Comment by Cuboos** [comment]
I need this.

**Comment by xxalpha** [comment]
I can't.
:-1:

**Comment by WJohn** [comment]
I'm still personally against this from a sprite-quality and future-workload perspective, even if it's adorable.

**Comment by RemieRichards** [comment]
@WJohn I have 0 idea what work of yours this would hinder that has any actual chance of addition.
Your custom lizard VVing each round isn't even affected as you use humans for that, and humans don't have species.

**Comment by WJohn** [comment]
Yeah that's true, but for incoming's future customizable lizards in the character setup or in casae we ever do any sort of lizard-based clothing, it'll certainly increase the work-load there.

**Comment by GunHog** [comment]
Wait, Incoming is going to do that? Well, that saves me the work, then!

**Comment by d3athrow** [comment]
>making this

>not the dismemberment PR that's been sitting forever

**Comment by RogerWilcoBeep** [comment]
why
do we really want to humor the scalies any further

**Comment by Cuboos** [comment]
https://www.youtube.com/watch?v=tQLKc3zSLdU

**Comment by Chocobro** [comment]
FREEZE IS OVER
IT'S TIME

**Comment by WJohn** [comment]
Welp. Incoming's either gonna have to revert this change or I'm gonna have to make this happen with every tail sprite from now on.

Tail-clothing is also basically off limits for good, now.

**Comment by Miauw62** [comment]
rip tgstation

**Comment by dannno** [comment]
>please no we shouldn't validate the lizardbeest erpers any more

mfw goofball is right for once in his life

**Pull request merged**
