### PR TITLE
>2 cost for 4 second stun per sharp item held, instant aggro grabs, theft of items from hands into your own hand, 3 second stun on harm long distance, pudge hook on help

### PR DESCRIPTION
**Pull request by Iamgoofball**
what the fuck is this cancerous bullshit

### CODE REVIEW

**Comment by Kromgar** [comment]
meemeeees

**Comment by Shadowlight213** [comment]
Did you remove the emporium entry as well?

**Comment by kevinz000** [comment]
this is the only goof meme pr that is actually good.
because i got completely destroyed by some shitposting nerd called improvedname
and being robusted is UNACCEPTABLE :^)

**Comment by ExcessiveUseOfCobblestone** [comment]
why not just up the cost?

> the same guy who throws hissyfits over removing his own code has no problem with removing others

hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by Shadowlight213** [comment]
@ExcessiveUseOfCobblestone hit it on the nail

**Comment by Iamgoofball** [comment]
Explain close

**Comment by Haevacht** [comment]
Oh you tried it 3 times nice.

**Pull request closed without merging**
