### PR TITLE
tgui: MIT License

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

All relevant source code now contains copyright headers, that explicitly assert copyright and license for every file.

This has been done to prepare TGUI for wider adoption. Goon station devs are interested in using TGUI, and hopefully this will result in a nice collaboration and improvements to both codebases.

The following files were relicensed under MIT:

- `code/controllers/subsystem/tgui.dm`
- `code/modules/tgui/*.dm`
- `tgui/**/*.js`
- `tgui/**/*.scss`

The following files were kept untouched:

- `tgui/packages/tgui/interfaces/**/*.js`
- `tgui/packages/tgui/styles/interfaces/**/*.scss`

Project is still basically AGPL-3.0 under **/tg/station**'s parent license (with added MIT texts), but allows importing MIT code into MIT-compatible codebases.

image

image

image

Please comment.

<details> 
<summary>License section in README</summary>

## License

Source code is covered by /tg/station's parent license - AGPL-3.0 (see the main README), unless otherwise noted.

Some files are annotated with a copyright header, which explicitly states the copyright holder and license of the file. Most of the core tgui source code is available under the MIT license.

The Authors retain all copyright to their respective work here submitted.

</details>

### CODE REVIEW

**Comment by steamp0rt** [comment]
can individual interfaces be re-licensed if the dev so wishes?

**Comment by stylemistake** [comment]
Yes.

**Comment by Qustinnus** [comment]
can we make it use the everyone but GPL loopholers license

**Comment by stylemistake** [comment]
@Faerdan

**Comment by Faerdan** [comment]
I wrote the original "NanoUI" code which TGUI was based on. I am happy to relicense whatever of my code remains, is there anything in particular I need to do?

**Comment by stylemistake** [comment]
Nothing, except your stance on the copyright. Shall I keep it to myself?

**Comment by Faerdan** [comment]
Oh I am fine with that, whatever best supports the project.

**Comment by d3athrow** [comment]
>can we make it use the everyone but GPL loopholers license

@Qustinnus I will port whatever i want and challenge any dmca

**Review by actioninja — DISMISSED** [review]
I would add a small notice to the main readme which mentions code being under GPL as saying "GPL unless otherwise indicated" or something like that. It's a little unclear.

**Comment by optimumtact** [comment]
@d3athrow it's a shame you can't port players am I rite lmao

**Comment by d3athrow** [comment]
@optimumtact as if there were any players were worth porting.

**Pull request merged**
