### PR TITLE
Add a goliath emojii to ooc chat

### PR DESCRIPTION
**Pull request by MMMiracles**
goliath
ohmygod

### CODE REVIEW

**Comment by ChangelingRain** [comment]
wrong sprite would not :goliath:

**Comment by MMMiracles** [comment]
the original is always better

**Comment by Bill-Luxe** [comment]
> goliath

**Comment by optimumtact** [comment]
Can you explain this please

**Comment by MMMiracles** [comment]
goliath

**Comment by optimumtact** [comment]
Please, explain what this is or I'm going to close it.

**Comment by MMMiracles** [comment]
i just did, its a tiny goliath emoji

**Comment by jaxy15** [comment]
There was an issue with the server or something where everything was completely silent, because every time a sound was **supposed** to play, it instead created a Goliath in nullspace. Whenever there was an announcement, there was also a message saying "goliath".
It's a lot like the cleanbot thing.

**Comment by optimumtact** [comment]
How does it work if you're just adding a sprite?

**Comment by MMMiracles** [comment]
emojis are set up so all you need to do is create the sprite inside the emoji.dmi and they work.

**Comment by JJRcop** [comment]
Think say code tag is invalid: this has no code in it at all.

**Comment by optimumtact** [comment]
OH yeah, well, your'e INVALID

**Comment by ChangelingRain** [comment]
Fastmerge sprite prs today

**Pull request merged**
