### PR TITLE
New Contractor Sprites.

### PR DESCRIPTION
**Pull request by Mey-Ha-Zah**
## About The Pull Request

Resprites the Contractor Suit and Baton

## Why It's Good For The Game

They were showing their age and as the person who made them, it was up to me to replace them.
image

## Changelog
:cl:
image: Revamped Contractor Gear. You'll stand out more now, but hey, that's why the syndicate contracts out work in the first place.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
image

Is this jus icon diff bot being weird again?

**Comment by Mey-Ha-Zah** [comment]
yeah, sprites are fine, just bot being weird

**Comment by CCC23** [comment]
:(

**Comment by LSommers** [comment]
damn, the syndicate's really out here giving people full meteor armor sets

**Comment by Admiral-Gigaton** [comment]
dont really like how fat the legs look but it looks great otherwise

**Comment by projectkepler-ru** [comment]
> damn, the syndicate's really out here giving people full meteor armor sets

advanced energy gun is just the meteor lasergun

**Pull request merged**
