### PR TITLE
Fixes weird lizard feature issues

### LINKED ISSUE #13783: Double Tailed Lizards
d10_icon

Not sure how this occurred but I saw a lizard with two tails, one properly used and the other stuck in its southern facing sprite in all dirs.

Later when the lizard got tail removal surgery, they lost both tails, but only one dropped.

### LINKED ISSUE #13794: Lizard pop out of the cloner without any features
Whatever #13561 was trying to do to preserve features post tail mutilation has backfired, and now post cloning lizards are basically weirdly colored humans.

Nobody tested this~

### PR DESCRIPTION
**Pull request by Incoming5643**
Fixes #13783

Removes special handling for mutant features on cloning. It didn't work and is inconsistent with how the rest of cloning works (it takes a snapshot of how you looked at the moment of scan, including things that might not strictly be "genetic" like dyed hair color). Fixes #13794 

Also depriciates *stopwag. *wag is now a toggle instead.

:cl: incoming5643
bugfix: the terror of double tailed lizards and featureless clones should now be over
rscdel: the emote *stopwag no longer works, just *wag again to stop instead
/:cl:

### CODE REVIEW

**Comment by Incoming5643** [comment]
What was happening is for some reason the smooth lizard tail sprite wasn't defined in four directions, but rather one.

**Comment by bgobandit** [comment]
ayyyy thanks for saving me doing actual work

:+1:

**Comment by Incoming5643** [comment]
don't thank me yet https://github.com/tgstation/-tg-station/issues/13794

**Comment by bgobandit** [comment]
wait so

the cloning thing was there for a reason

**Comment by KazeEspada** [comment]
Merge this ASAP. THE LIZARD KHANS DEMAND IT.

**Pull request merged**
