### PR TITLE
Removes Hand of God gamemode.

### PR DESCRIPTION
**Pull request by AnturK**
Mode is unmaintained.

Leaves the items and structures in mostly untouched state for admin events/ruins.

### CODE REVIEW

**Comment by optimumtact** [comment]
but I LIKE IT

**Comment by lzimann** [comment]
rest in pieces

**Comment by ShadowDeath6** [comment]
it had potential :^(

**Comment by Iamgoofball** [comment]
:-1:

**Comment by Cheridan** [comment]
i'd prefer the items to get gone too. at least consolidate the structures under the /fluff subtype

**Comment by TechnoAlchemisto** [comment]
Good riddance, not once have I had fun as a HoG God or cultist

**Comment by ExcessiveUseOfCobblestone** [comment]
HoG is the best gamemode

**Comment by ShadowDeath6** [comment]
f

**Comment by ExcessiveUseOfCobblestone** [comment]
🙏 you came to the wrong nexus, pal 🙏

**Comment by AnturK** [comment]
I'll see about the repathing Cheridan,mostly did it this way since it's easier on mapedits.

**Comment by Cheridan** [comment]
@AnturK good reasoning but is any of this stuff on any maps?

**Comment by lzimann** [comment]
@cheridan CTF map uses a HoG trap

**Comment by lordpidey** [comment]
While I agree that HoG as is is a bad gamemode, I would like to see it remain.

I'm willing to help maintain it some, if some people will tell me what's broken/wrong/unfun/etc...

**Comment by optimumtact** [comment]
Are you really motivated enough to do that? Hand of God basically needs actual finishing + balancing and development and fleshing out of all it's features and there are no design docs to guide you.

Consider how many clockcult pr's were made, several months of activity, and still the occasional tweak, you'd need to commit to a time frame of that scale of responding to player feedback, watching rounds in progress and debugging issues.

Making a gamemode is quite a task that you have to be highly motivated to complete.

**Comment by lordpidey** [comment]
To answer the question:  Probably.  I'm going across the country to a 10 week training program, where video game consoles aren't allowed on campus.

I'll have a LOT of free time.

**Comment by Cheridan** [comment]
well if pidey gets it fixed it up later he can readd it but for now its just bloat. mergin

**Comment by lzimann** [comment]
oficially rip

**Comment by Chocobro** [comment]
@lordpidey they will probably see a computer as a video game console

**Comment by Chocobro** [comment]
also rippers hog

**Comment by lordpidey** [comment]
@Chocobro considering that it's a computer programming training thing, I highly doubt that.

**Comment by Chocobro** [comment]
@lordpidey herein lies the challenge; code a game without a computer

**Pull request merged**
