### PR TITLE
Fixes basic spiderlings becoming ice spiders

### LINKED ISSUE #14242: Generic spiderlings can grow up as ice spiders
By itself nothing bad since they're not stronger than standard ones, but it probably skews hunter/nurse ratios.

### PR DESCRIPTION
**Pull request by ShizCalev**
fixes #14242

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Wont this mean ice spiders will create regular spiders?

**Comment by ShizCalev** [comment]
Yes, the snowflake ice spiders (which are unique to the snowdin away mission) will still create normal spiders (as they did before.)

**Comment by DoctoreMad** [comment]
Ice Spiders creating ice spiderlings when?

**Comment by Grazyn** [comment]
>Yes, the snowflake ice spiders (which are unique to the snowdin away mission) will still create normal spiders (as they did before.)

I think ice spiders can also spawn from golden slime cores, so either remove them from gold cores or make them able to breed ice spiders for consistency. 

btw ice spiders are MUCH better than regular spiders because they're immune to cold damage. Cold is extremely deadly to regular spiders because it kills them in seconds without warning.

**Pull request merged**
