### PR TITLE
Tend Wounds replacement fix.

### LINKED ISSUE #45732: Tend Wounds adv not clearly combo.
BYOND Version: 512.1475
Server revision compiled on: 2019-08-05
Master commit: 7ead350057378af24248e8325b96fd28fd4af69b

image

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
Tend Wounds replacement fix.
fix#45732
image

## Why It's Good For The Game
Bugs bad.

## Changelog
:cl:
fix: Tend Wounds correctly replaced on upgrade.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
IIRC this was intentional: The combo healing is objectively better than both HPS wise.

**Comment by Dennok** [comment]
> IIRC this was intentional: The combo healing is objectively better than both HPS wise.
https://github.com/tgstation/tgstation/blob/803138114997db247374888c60e6282dbc8dfe5f/code/modules/surgery/healing.dm#L102-L103
and
https://github.com/tgstation/tgstation/blob/803138114997db247374888c60e6282dbc8dfe5f/code/modules/surgery/healing.dm#L137-L138
vs
https://github.com/tgstation/tgstation/blob/803138114997db247374888c60e6282dbc8dfe5f/code/modules/surgery/healing.dm#L175-L177

**Comment by ExcessiveUseOfCobblestone** [comment]
Healing PER SECOND

Yes they're lower numbers, but combo surgeries are 2.5x faster.

https://github.com/tgstation/tgstation/blob/803138114997db247374888c60e6282dbc8dfe5f/code/modules/surgery/healing.dm#L169

**Comment by ExcessiveUseOfCobblestone** [comment]
The proper "fix" would be to convey this information in the surgery description.

**Comment by Dennok** [comment]
Yes but ..

**Comment by ExcessiveUseOfCobblestone** [comment]
just change the desc of the surgeries in the same file lol

**Pull request closed without merging**
