### PR TITLE
Engraved messages UI and fixes

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Engraved messages now have a UI, which any player, living or dead
can access. See when the message was engraved, and upvote or downvote
accordingly.
add: Admins have additional options with the UI, seeing the player ckey,
original character name, and the ability to outright delete messages at
the press of a button.
/:cl:

- If we were to move to a system where higher rated messages would be
more likely to be selected, this provides the ability to get those
ratings.
- Ratings are by ckey, so character independent.
- Authors cannot upvote or downvote their own messages.
- Did I mention that admins can just now delete the message, instead of
mucking around varediting them?

### CODE REVIEW

**Comment by optimumtact** [comment]
I don't like this like/dislike thing, it's weird, why do engraved messages come bundled with a facebook ui, it doesn't make any ic sense.

**Comment by coiax** [comment]
It's not entirely IC UI, given it's available to all, including ghosts.

**Comment by Armhulen** [comment]
heavily disliked comments should get destroyed, heavily liked appear golden.

**Comment by Iamgoofball** [comment]
@optimumtact it's how DS messages work

**Comment by optimumtact** [comment]
So? darksouls is a shit game for people who like to hit themselves with whips.

**Comment by MrStonedOne** [comment]
Don't call it likes/dislikes, call it upvotes and downvotes, use arrows, make them contrasting colors, one popular contrast is the [Orange Blue Contrast](http://tvtropes.org/pmwiki/pmwiki.php/Main/OrangeBlueContrast)

**Comment by Thunder12345** [comment]
I smell sewage leaking from reddit

**Comment by Xhuis** [comment]
@optimumtact YOU TAKE THAT BACK

**Comment by Militaires** [comment]
@optimumtact sounds like someone was a skrub

git gud

**Comment by kevinz000** [comment]
github upvotes ss13 edition.

**Comment by coiax** [comment]
@optimumtact I have updated this PR, please reopen.

**Comment by optimumtact** [comment]
This doesn't remove the grammar thing

**Comment by coiax** [comment]
I know. I'm giving the grammar thing a trial for a few weeks, see how it pans out.

**Comment by coiax** [comment]
DNM while #23909 is open.

**Comment by ExcessiveUseOfCobblestone** [comment]
can I get the lmao tbh fam rating for messages with the laughing in tears emoji?

**Comment by Xhuis** [comment]
😂 😂 😂 👌 👌 👌 💯 💯 💯

**Comment by Haevacht** [comment]
@Iamgoofball DS messages only have a +1 button in the good games.

No -1. It's just hey i like this message +1 and actual good ones accumulate a ton because of that alone.

**Comment by Xhuis** [comment]
@Haevacht how dare you call ds3 bad fite me irl

**Comment by Haevacht** [comment]
Sure I'll just bring a longsword and stunlock you to death. Hit r1 5 times I win!

**Comment by Xhuis** [comment]
land one hit
land two hits
oh look you're parried
oh look I have the hornet ring
oh look I have an upgraded dagger
oh look
YOU DIED

**Comment by optimumtact** [comment]
So what are the differences now

**Comment by coiax** [comment]
>add: Engraved messages now have a UI, which any player, living or dead
can access. See when the message was engraved, and upvote or downvote
accordingly.
>add: Admins have additional options with the UI, seeing the player ckey,
original character name, and the ability to outright delete messages at
the press of a button.

**Pull request merged**
