### PR TITLE
Donutstation Tweaks

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles (Donutstation)
add: Added a plumbing section below Medical
add: Several waypoint markers have been adding around key locations to help alleviate trouble when exploring the map.
del: To make room for plumbing, the lower section of Medical's maintenance was stripped to an extent.
tweak: Original chemistry has been rebranded to the Pharmacy with access levels adjusted
tweak: Chapel now has pews instead of stools for proper communion
tweak: Genetics is slightly more science-y colored.
fix: Fixes a few spots that was missing disposal/piping in the main loop
fix: Surgery B now has a camera
/:cl:

image

I have a lot of background work on this map related to multi-z but that probably won't see the light till openspace gets a visual upgrade in some regards. I've been meaning to keep this map more maintained but actual work took priority for a couple months and now I'm back to fix shit.

Got a problem that isn't addressed in the forum thread or issue count? Post it here! I'll be happily working on this in the meantime if anything pops up.

### CODE REVIEW

**Comment by MMMiracles** [comment]
tweaks are done unless something else comes up

**Review by kriskog — CHANGES_REQUESTED** [review]
Whiskey bottle in space by AI sat, otherwise looks good

**Comment by MMMiracles** [comment]
@kriskog the whiskey bottle is a reference please come back

**Comment by BadSS13Player** [comment]
Isn't it called Apothecary in other maps?

**Comment by MMMiracles** [comment]
Internally its called pharmacy, so I just went with it.

**Comment by kriskog** [comment]
They were rebranded to pharmacy since this isnt the 1800's

**Review by kriskog — APPROVED** [review]

**Pull request merged**
