### PR TITLE
Readds jetpack object verbs

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Stop removing object verbs.

Borgs need them.

And i don't see why we can't have both.

@neersighted

### CODE REVIEW

**Comment by optimumtact** [comment]
:-1:

**Comment by GunHog** [comment]
Borgs cannot use action buttons?

**Comment by MrStonedOne** [comment]
They don't have them, action buttons are a carbon thing unless thats changed.

**Comment by WJohn** [comment]
Maybe jetpacks should actually work for cyborgs if you click on them in the first place. Last I checked it was something handled in the right click menu, up until we added action buttons, too.

**Comment by neersighted** [comment]
Wait, how do borgs use/need jetpacks? I was not aware they had to use them. Regardless, wouldn't it be better to add action buttons to borgs?

**Comment by tkdrg** [comment]
Syndiborgs need to use their jetpacks.

**Comment by neersighted** [comment]
dreamseeker_2016-02-09_10-39-04

**Comment by Bawhoppen** [comment]
:+1: verbs are infinetly better that those shitty annoying buttons

**Comment by RemieRichards** [comment]
Wow I did not think Bawhoppen could get any stupider.

**Comment by GunHog** [comment]
+1000 :+1:  for inbuilt thrusters

**Comment by Bawhoppen** [comment]
I had a really brutal retort but since I'm so nice I won't even use it

**Comment by neersighted** [comment]
I Win

**Comment by optimumtact** [comment]
checkmate atheists

**Comment by duncathan** [comment]
Continue removing object verbs

**Comment by neersighted** [comment]
Please update the description to not reference borgs as that issue is fixed separately in #15360.

**Comment by Cheridan** [comment]
object verbs must die

**Pull request closed without merging**
