### PR TITLE
[READY] New Space Dragon textures.

### PR DESCRIPTION
**Pull request by Nebulacrity**
## About The Pull Request
I have improved Meyhazah's Space Dragon textures further. 
They look like this: 
ss13SpaceDragon

I have also updated the dead Space Dragon texture, which Meyhazah didn't touch as all.
It looks like this:
ss13SpaceDragonDead

## Why It's Good For The Game
It looks better.

## Changelog
:cl:
imageadd: Improved all of Space Dragon's textures.
:cl:

### CODE REVIEW

**Comment by IndieanaJones** [comment]
Space dragon getting a lot of sprite love all of a sudden.

**Comment by Nebulacrity** [comment]
> Space dragon getting a lot of sprite love all of a sudden.

I saw him getting a new coat of paint and wanted to help out too. 
His original textures made him look more like an overgrown larva than a dragon.

**Comment by nicbn** [comment]
What in Oblivion was that?!!

**Comment by ExcessiveUseOfCobblestone** [comment]
space eel w wings

**Pull request merged**
