### PR TITLE
Fixes spam after admin event cancellation adds feedback

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
?

**Comment by Cyberboss** [comment]
```
ADMIN LOG: Random Event triggering in 10 seconds: Anomaly: Bluespace (/datum/round_event/anomaly/anomaly_bluespace) (CANCEL)
ADMIN LOG: Durkel/(Tim Ebow) cancelled event Anomaly: Bluespace.
ADMIN LOG: Random Event triggering in 10 seconds: Anomaly: Hyper-Energetic Flux (/datum/round_event/anomaly/anomaly_flux) (CANCEL)
ADMIN LOG: Durkel/(Tim Ebow) cancelled event Anomaly: Hyper-Energetic Flux.
ADMIN: Cyberboss/(Maximillian Ryder) (FLW): weird 
ADMIN LOG: Random Event triggering in 10 seconds: Anomaly: Gravitational (/datum/round_event/anomaly/anomaly_grav) (CANCEL)
ADMIN LOG: Durkel/(Tim Ebow) cancelled event Anomaly: Gravitational.
ADMIN: Durkel/(Tim Ebow) (FLW): hahah 
ADMIN LOG: Random Event triggering in 10 seconds: Anomaly: Pyroclastic (/datum/round_event/anomaly/anomaly_pyro) (CANCEL)
ADMIN LOG: Durkel/(Tim Ebow) cancelled event Anomaly: Pyroclastic.
ADMIN: Cyberboss/(Maximillian Ryder) (FLW): HMMMM 
ADMIN: Durkel/(Tim Ebow) (FLW): fucking perfect(?|F) 
ADMIN LOG: Random Event triggering in 10 seconds: Brand Intelligence (/datum/round_event/brand_intelligence) (CANCEL)
ADMIN LOG: Durkel/(Tim Ebow) cancelled event Brand Intelligence.
ADMIN: Cyberboss/(Maximillian Ryder) (FLW): I'll look into this 
ADMIN: Durkel/(Tim Ebow) (FLW): Wait, that last one worked 
ADMIN: Cyberboss/(Maximillian Ryder) (FLW): yeah thats why its weir 
```

**Comment by Cyberboss** [comment]
It's looping through all the events and doesn't stop till the end or one returns TRUE

**Comment by PKPenguin321** [comment]
Oh, that's a bug?

**Pull request merged**
