### PR TITLE
Atmosia ruin fixes

### PR DESCRIPTION
**Pull request by ZAMODA**
## About The Pull Request
There were a couple missing pipes as well as well as some pipes and connectors being underfloor instead of overfloor like I intended

All changes circled below
image
### Mapping March
Ckey to receive rewards: N/A

## Why It's Good For The Game
Fixed things are always better than broken things

## Changelog
:cl:
fix: Minor touchups on the atmos ruin that I didn't catch when making it.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
oh i didn't see this PR but you also had active turfs here that needed to be fixed: #74379

it's okay because i've already fixed it in the best way possible.

**Comment by ZAMODA** [comment]
> btw you should really make a new branch for every PR you make

I tried making a new branch, most likely used wrong thing considering I used the second option when creating said new branch. I'm learning as I go though, and will keep this in mind!

**Comment by san7890** [comment]
> Wait I should probably add a GPS to this ruin shouldn't I?

yeah that would be okay

**Comment by san7890** [comment]
if you rebase off master you can make your commit history look a lot less ugly (no need to do this though)

**Comment by ZAMODA** [comment]
alright, GPS added!

**Comment by san7890** [comment]
fyi don't hit the PR's "merge master" button in case you get conflicts you will be in hell trying to fix them

always merge master from your git client with git hooks installed https://hackmd.io/@tgstation/SyVma0dS5#Git-Hooks

**Comment by san7890** [comment]
btw when you merge master can you load the ruin using `always_place = TRUE` in the map template datum and ensure no active turfs show up? thank you

**Comment by ZAMODA** [comment]
Im gonna open a whole new PR since that would be alot easier then fixing whatever is causing these merge conflicts, luckily i didn't change much!

**Pull request closed without merging**
