### PR TITLE
Asteroid Station fixes

### LINKED ISSUE #13578: Asteroid station disposal systems are broken
Medbay disposal by storage goes outside right where it starts, theatre disposals stops right outside in medbay.

Pretty much entire system on map is broken.

Solution: remove map from rotation.

### LINKED ISSUE #13642: asteroid station's holodecks buttons don't work
Had a AI player complain the buttons did nothing and turns out they don't respond to any clicking.

### LINKED ISSUE #13890: Asteroid Station escape shuttle area
bugs

### LINKED ISSUE #13894: Asteroid station lawyer privacy shutter button doesn't work.
What it says on the tin.

### LINKED ISSUE #14533: Asteroid Station Botany Windoor requires wrong access
The windoor in asteroid station batony doesn't open with batony access.

### PR DESCRIPTION
**Pull request by lzimann**
Fixes #13578
Fixes #13642 
Fixes #13890 
Fixes #13894
Fixes #14533 ~~I tested and I could open normally as botanist roundstart.~~ I can't read and confused desk with the delivery windoor.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Stealing my easy cheribucks

**Comment by KorPhaeron** [comment]
The only thing I fixed that you might have missed in this is the excess droppers inside the science walls for some reason

**Comment by lzimann** [comment]
I'm pretty sure I fixed it, I was doing something in science and saw that and removed

**Comment by lzimann** [comment]
Just realized that map merger didn't work somewhere, fuck, my bad.

**Comment by lzimann** [comment]
Remaking pr

**Pull request closed without merging**
