### PR TITLE
Plasma cutter nerfs to prevent cutterspam vs. stationside antags: lavaland only, others pending

### PR DESCRIPTION
**Pull request by Barhandar**
It's still replaceable normally, but you now need actual firing pin to be able to use plasmacutters as a weapon on station. Does not otherwise nerf plasma cutters, for now.

:cl: Barhandar
balance: Following safety complaints, plasma cutters now come with special mining firing pin that only allows shooting the weapon while on Lavaland.
/:cl:

Because nerfing plasmacutters as weapons globally (see #40324) sucks for miners **and does not even affect the issue of being able to equip everyone with them**, and limiting them to lavaland doesn't while still preventing easy xeno/blob obliteration. They're still very potent weapons on station, if you can snag some good firing pins, but they're no longer unlimited supply, and there are better options to use pins on (for example, beam rifles).

### CODE REVIEW

**Comment by XDTM** [comment]
If they require a pin outside of lavaland you might potentially reduce or remove the pressure requirement, since its only purpose is to prevent its use as a weapon on station.

**Comment by Barhandar** [comment]
Pressure damage loss still makes sense and still applies on lavaland (mining station itself, various airtight ruins...).

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't think this addresses the issues of the plasma cutter but rather just hides it from the non-mining players so they won't put up a nerf PR.

If it's dumb on-station then it's certainly dumb on lavaland where you're dealing with the "intelligence" of AI. Replace blob or whatever antag with goliaths,basils, and hivelords (wait for it...) and the same still applies.

**Comment by Kagus** [comment]
Yeeaaaah, I don't think you're gonna get very far arguing that an advanced plasma cutter is comparable to a _spear_.

**Comment by Barhandar** [comment]
Embedded spear and plasmacutted limb _are_ fairly comparable, because you can't fix either without surgery. APCs are reusable unlike the spear, yes.

But then again, if ash lizards want to attack someone with superior equipment (and miners are _guaranteed_ to have superior equipment), they better fucking have superior tactics.

**Comment by Therapist1** [comment]
While this does add a few extra steps, (Removing pin, installing a new one) I don’t think this is enough. The ammo should be dealt with, (Give it actual printable magazines with reasonable ammo count), and keep the range, but add drop off after two tiles, for damage and dismemberment. If you don’t want the cutter nerfed into near oblivion, you need to actually address its balance issues in a better manner than the other PR. Giving it 2 range isn’t the right answer, and neither is pushing it back behind a pin, though it is one step to make it non-mass-producible.

**Comment by ExcessiveUseOfCobblestone** [comment]
I've seen (Advanced) plasma-cutters used all the time as primary weapons, i'm assuming due to dual-wielding. That said, I'm not exactly buying the sidearm comment, and I'm further believing this PR just sweeps the issue under the rug.

I'm still on team remove their mining capabilities completely and toss it into KA mods so you can spec your KA between mining or damage

**Comment by Bombpants** [comment]
I just like being able to cut through rocks like butter...

**Comment by Barhandar** [comment]
>The ammo should be dealt with, (Give it actual printable magazines with reasonable ammo count)

That prevents recharging on the go on lavaland itself. Also, energy actual-weapons can be _very easily_ recharged by dragging a weapon charger to the location of the fight - by the time you can print either you're going to have upgraded chargers with extremely quick operation, so _ammo is not relevant_.

>If you don’t want the cutter nerfed into near oblivion, you need to actually address its balance issues

Which are? Usability as weapon is dealt with by this PR - by effectively turning it into _actual_ weapon. Recharge is comparable due to upgraded rechargers; mags would be a separate PR.  
I can further reduce their damage to emphasize "mining" and "dismembering" part so they're not as efficient against the non-human enemies.  
I can also make them require actually non-negligible amount of materials to print.

>I'm still on team remove their mining capabilities completely

That would be rather stupid, they _are_ mining tools. Removing damage capabilities is better.

**Comment by iskyp** [comment]
this is a dumb nerf for many reasons
mainly that all it does is delay the inevitable "WTF PLASMA CUTTER OP" prs instead of actually balancing the thing

**Comment by davethwave** [comment]
Do realize that you do have to hit someone 20 times in order to crit them in a pressurized area. Also, don't nerf the mech stuff as well please, or at least put it in the PR description.

**Comment by davethwave** [comment]
One last thing, electronic pins are very rare as it is.

**Comment by Barhandar** [comment]
>One last thing, electronic pins are very rare as it is.

That's exactly my point that I keep repeating.

**Comment by Therapist1** [comment]
100 shots that instantly recharge just by putting 1 bit of plasma in, a no flash welder that can cut through walls at no ammo cost that has a 5 tile range with 28 damage (the code says you changed this to 18?) a 20% chance to dismember, and no drop off. a firing pin alone doesn’t fix this.

**Comment by davethwave** [comment]
That and to print a weapon with a pin in it already costs quite a bit so in a way the are gated in 2 ways, time for weapon research, and the mats themselves unless they break into sec or bribe them somehow.

**Comment by davethwave** [comment]
Also you forgot the important part, 28 in a pressurized environment.

**Comment by Kagus** [comment]
Or they order firing pins via cargo, which mining can bust open in moments.

As for dismemberment, it was my understanding that dismember chance wasn't tied exclusively to the "dismemberment" variable, but was rather a calculation based on weapon damage vs. limb health, which was then modified by said variable. So while plasma cutters have a better probability, I didn't think it was a flat 1-in-5 chance to lop the limb off regardless of being in pressurized environment or not.

And please don't make the ammo into a manufactured thing, being able to easily reload on lavaland is _really_ nice... Heck, it doesn't even really fix the issue of the thing's usability as a weapon on-station, since they'd have _better_ access to craftable ammo on the station than while mining on lavaland...

However, if you could make a mod for the KA that let its shots cleave through rock the same way as the cutter does now, I'd be all for that. But as it stands, the current AoE mods don't really cut it for turning the KA into a proper mining tool.

**Comment by Barhandar** [comment]
>a no flash welder that can cut through walls at no ammo cost

It does have ammo costs for welding. Lack of flash is out of scope.
>firing pin alone doesn’t fix this.

Does because the issue isn't even its usability as a weapon, it's _being spammable against antags that do not have dismemberment and cannot rapidly move around_. And it fixes it a lot bettter, that is, at all than gimping range on the other PR.

**Comment by ExcessiveUseOfCobblestone** [comment]
> it's being spammable against antags that do not have dismemberment and cannot rapidly move around.

If that's the issue then uh... doesn't this explain literally every mob on lavaland barring ashwalkers?

>That would be rather stupid, they are mining tools. Removing damage capabilities is better.

Only _relatively_ recently have they became mining tools, they used to be purely infinite welders.

**Comment by Barhandar** [comment]
>If that's the issue then uh... doesn't this explain literally every mob on lavaland barring ashwalkers?

These aren't player-controlled, unlike xenos/blob, so there's no issue.
>Only relatively recently have they became mining tools, they used to be purely infinite welders.

#8587, 3.5 years.

**Comment by SgtxRootbeer** [comment]
I feel like this is a bit too aggressive a Nerf, considering the apc has been in the game for years with no substantial issue

**Comment by Kagus** [comment]
> I feel like this is a bit too aggressive a Nerf, considering the apc has been in the game for years with no substantial issue

This is kind of a faulty argument though. Just because there's no singularly large issue report or discussion thread about it (which, seeing as it's been in the game for years, it's entirely possible that there actually _is_ such a report/thread, but we're all too lazy to go and check) doesn't mean that there aren't any inherent problems with how it's implemented.

Like, you could just as well say that **The Entire Science Department** doesn't need a nerf, because it's been in the game for years with no substantial issue.

**Comment by FantasticFwoosh** [comment]
Plasma cutters are helpful tools first, mining implements second, here's a list of non-mining features.

- Plasma cutters can weld vents very quickly in a plasma flood without igniting a fire like a welder.
- Plasma cutters can cut away walls & girders.
- Plasma cutters are sharp and can butcher bodies & cut lavaland plants.
- In space enviroments, plasma cutters are fully effective versus blobs & xenomorphs.

With a lavaland only pin you would _cough_ underpin its usefulness without actually handling key points that need changing like its 'ammunition charge' and that it doesn't cost plasma to weld like in the above bullet points because a projectile wasn't shot in the process.

**Comment by Barhandar** [comment]
>without actually handling key points that need changing like its 'ammunition charge' 

The complaint was it being spammable against xeno/blob. This PR handles that by limiting amount of plasmacutters to amount of firing pins on station, and then you're better off with a weapon that can shoot _from offscreen_ like lasers or beameme. The other PR doesn't handle that because 2 tiles or 5, you can still give entire crew plasmacutters.

The pin doesn't affect its usability for mining. The rest of points (charge, people actually using APC as a welder instead of other tools) I'll need to gather _actual player feedback_ on because the fraction of people using Github doesn't particularily align with "people who actually play the game".
>and that it doesn't cost plasma to weld like in the above bullet points because a projectile wasn't shot in the process.

It _should_ cost plasma to weld, there's relevant and not commented out code. It doesn't, therefore there is a bug.
>Plasma cutters are sharp and can butcher bodies & cut lavaland plants in the place of a explorers knife or bone dagger.

That's a clearly intended QoL for miners, same as kinetic crusher being able to butcher.
>Plasma cutters can cut away walls & girders. (no eyeflash, no restrictions on wall material like advanced plasma welders required for alien alloy, useful for material reclaimation from ruins)

That's, uh, "Fwoosh doesn't play as miner" problem, but can be just rolled up into PR fixing welder use.

**Comment by zamolxius** [comment]
pls nerd im ded

**Comment by imsxz** [comment]
reason kinetic accelerator is fine and not in jeopardy of nerf PR: mostly limited, theres reasonable ways to print more but you cant get them by the hundreds with. 40 brute damage/1.6s with no pressure penalty, 70 brute damage/1.6s generally. Can't be dual wielded effectively.

reason adv cutters are retarded: first mining load can generally print 50-60 adv cutters, more if RND bothered to upgrade anything(most miners end up upgrading their own shit if science doesnt). 28 brute/1s generally, 56/s when dual wielded.

in 3 seconds, an adv cutter can do 168 damage, KA can do 140 at best. Combine this with the fact that you can easily supply every crewmember+crewmembers dog with 2 adv cutters each, shit like blob/xeno(near space most of the time) and other large threat antags that end up getting obliterated by this garbage that they cant even prevent because god knows at least 3 people are dual wielding them already and probably the cargo staff too.

That said, this PR isn't the best change, neither was tlal's. In my opinion, the simplest change that would keep their original purpose(godlike mining tools) while toning down their combat ability would be to just keep their damage really low in general and keep them exclusively made for their mining abilities.

Call this an "i ded pls nerf" situation but god damn the only things i've felt more bullshitted by than plasma cutters are the fuckin RNG getting a grenade exploded out of my hand and playing vs unsynced borgs as a rogue AI. Nothing else feels quite as unfair as getting demolished by 15 people all holding 2 advanced plasma cutters, meanwhile the god damn stations actual armory of lethal gear is collecting dust because they're entirely outclassed by cutters against quite a few common threats.

**Comment by Barhandar** [comment]
>first mining load can generally print 50-60 adv cutters,

And they'll only be usable on lavaland with this PR, or you'll have to use firing pins you could use on lasers (20 damage, but burn instead of brute and can shoot from offscreen -> inaccessible to blobbernauts and tackles), beam rifles (shoot from other end of station for AoE explosion) or other weapons like scattershot riot shotgun aka "metastun: the weapon". Also by the usual point the xenos/blob spawn station can build mechas that kill them far more reliably than a bunch of vulnerable people.
>Combine this with the fact that you can easily supply every crewmember+crewmembers dog with 2 adv cutters each

You can't if they compete with actual weapons. You can't if they just have reduced range/damage. Reusable ranged weapons are still reusable ranged weapons even if they do only 6 damage a hit.

Also your PR is bad because it removes dismemberment and then plasma cutters have exactly 0 deal being called plasma cutters.

**Pull request closed without merging**
