### PR TITLE
Revert Smart Cables.

### PR DESCRIPTION
**Pull request by pireamaineach**
I almost feel bad just because of the sheer amount of effort that went into making smart cables, but then again this might not get merged anyway.

Currently probably not functional, if anyone could help by pointing out why that is, please do.
Before I pour too much time into this I want to make sure this's what people want.

## About The Pull Request

Reverts the Smart Cable P.R. and fixes, updates following.

## Why It's Good For The Game

The new system is infinitely less useful, as much as is simplistic. While it's easy to understand once you look at how it works the sprites, which are necessitated by the actual way it functions, are really deceptive and look awful. The old system functioned perfectly fine, and while it was complex for mappers it allowed you to do some fairly neat things with it. It was a fairly intuitive system that didn't need changing.

I'm willing to except that maybe this is me just subconsciously not liking change.

## Changelog
:cl:
del: Reverts https://github.com/tgstation/tgstation/pull/44899
del: Reverts https://github.com/tgstation/tgstation/pull/44784
del: Reverts https://github.com/tgstation/tgstation/pull/44828
del: Reverts https://github.com/tgstation/tgstation/pull/44265
/:cl:

### CODE REVIEW

**Comment by spessbro** [comment]
haha no, the new wires are great and i don't see why we would ever need to go back

**Comment by pireamaineach** [comment]
Because they're not.

**Comment by spessbro** [comment]
in what way? I haven't seen any major lag issues since the change.

**Comment by actioninja** [comment]
I assumed this was going to be about how broken as hell it is, but no, you're just reverting over "it look bad hurr durr"

**Comment by pireamaineach** [comment]
Why is everything circles? The new system also makes wires really weird just because they're all basically connected if they're next to eachother. It's simultaneously intuitive and far less intuitive if you know you're doing.

**Comment by pireamaineach** [comment]
Also yes, it look bad is a fair argument considering that the shit sprites are basically necessitated by the system.

**Comment by actioninja** [comment]
They aren't. It could use old sprites just fine if that's really your issue. "it look bad" is such a monumentally fucking stupid argument for entirely removing something.

**Comment by pireamaineach** [comment]
I mean it's not even just "it look bad." 

It's just a dumb system. It's not any more intuitive than the last system, it's just jarring and you have far less freedom with it.
It's like removing piping layers and directions and just making it "pipe here" and they connect to eachother.
Why?

**Comment by actioninja** [comment]
Ah, I see, so this is a "this is different so it's bad" situation.

Name a single situation in the game where running two wires next to each other or crossing over is needed.

**Comment by spessbro** [comment]
this is someone that actually tried to wire solars
22ls42fa3ex21
stop trying to make it so engineering takes reading a book to figure out what you're doing

**Comment by pireamaineach** [comment]
Yeah that's obviously not true. They fucking put a heart in there, they're memeing.

**Comment by actioninja** [comment]
Oh, so even stupider, this isn't the "I'm doing weird uneeded complexity in wiring setups that I can't do anymore" this is literally "I can't do shitty solar wiring anymore so this is bad."
Glad to know I can ignore this.

**Comment by HomocidlePancakes** [comment]
Bruh, people wire solars like that on purpose.

**Comment by spessbro** [comment]
being 100% honnest the only thing i dislike is the fact that you don't make nodes to make grilles electrified and even there i'd say it's kind of a nitpick. Also your point that the smart cables are like removing pipe layers is wrong in the sense that wires are much specific in how you use them.

**Comment by pireamaineach** [comment]
It's not even shitty wiring it's just more freedom you have when wiring.

Is there any reason to have 2 disconnect sets of wires? Not really, total current's the same, anyway, but at the same time, does this help anyone by removing that option?

**Comment by SgtxRootbeer** [comment]
i actually like this pr, because i enjoy the complexity. engineering isnt a book, its just
click on tile you arent standing on to go from center-your direction.
click on tile you are standing on to go from center-your facing direction

**Comment by SpaceManiac** [comment]
I am kind of curious why different colored wires were removed at the same time

**Comment by pireamaineach** [comment]
I don't know this P.R. is broken to hell right but I'll fix it, I swear. I just need to know people approve is all. I get nothing but support in O.O.C. then I get on github and I get called a retard for wanting to revert this.

**Comment by actioninja** [comment]
Laziness mostly. I plan to bring it back eventually but it wasn't really needed.

**Comment by SgtxRootbeer** [comment]
well, @pireamaineach, the issue is that the coders on github dont actually play the game, and the players dont code for the game either.

**Comment by pireamaineach** [comment]
c*der man bad

**Comment by spessbro** [comment]
i honestly don't see in what situation you would need the old cables that would be impossible or very inconvenient  with the new ones

**Comment by actioninja** [comment]
Was your sample size "3 retards on terry" or something like that? I've had the vast majority of people tell me it's a lot better.

**Comment by pireamaineach** [comment]
~~Having wires that don't look like shit.~~
~~Long-standing meme solars tradition.~~
Having two separate grids that pass over eachother at all. I know that's not exactly necessitated, ever, but it's something you can't do anymore, aswell as wire-art. (I know the pipe cleaners exist.)
It's just removing freedom and style for a system that play any better.
It's just worse for no reason.

**Comment by actioninja** [comment]
It does play way better unless you have a mental deficiency.

**Comment by pireamaineach** [comment]
> Was your sample size "3 retards on terry" or something like that? I've had the vast majority of people tell me it's a lot better.

I've had a single person on Sybil say the new system is better, everyone one else just thinks it looks bad and wants it gone. Obviously that's not my only gripe with it but it's certainly a problem.

**Comment by spessbro** [comment]
> 
> 
> Was your sample size "3 retards on terry" or something like that? I've had the vast majority of people tell me it's a lot better.

same with me, most people are just like "k whatever" cause they don't care about engineering and only a small size of engi mains are mad about it cause they can't do very specific shit while the rest is quite happy about it cause wiring solars is a breeze and makes for a much more safe power source in case the sm chokes and dies.

**Comment by pireamaineach** [comment]
It doesn't play any better. Honestly because of how bad the sprites are I've seen more people confused by it. "Why circle."

**Comment by spessbro** [comment]
but people being confused by old wires is a meme in itself because it was so common

**Comment by pireamaineach** [comment]
Yeah, new players tend to get confused. Welcome to Space Station 13.

**Comment by pireamaineach** [comment]
I've just seen it more prevalent with new wires.

**Comment by SgtxRootbeer** [comment]
@actioninja oldwires just required you to do a little bit of research, but thats the same for xenobio, or atmo, or viro, or genetics, or chem, or bartending, or cooking, or...

my point is that oldwires are easy, just not braindead-easy, and most jobs require some knowledge in the game before you are fully-capable in the position. why do we have to make engineering the one you can do braindead?

**Comment by spessbro** [comment]
you could be an old player and still have cables be a pain.

**Comment by pireamaineach** [comment]
If you don't play engineering I guess?

**Comment by pireamaineach** [comment]
I once had a problem with wires. Never again.

**Comment by spessbro** [comment]
yeah and new wires help you get into engi and not have something look wired but not actually be because you clicked 2 pixels to the right too far

**Comment by actioninja** [comment]
Oh, so your standard of whether people like it was "they look ugly."
Incredible.

**Comment by pireamaineach** [comment]
What?

**Comment by pireamaineach** [comment]
> Oh, so your standard of whether people like it was "they look ugly."
> Incredible.

Mate I get you put a lot of effort into it but just not any better. It's soley a downgrade.

**Comment by actioninja** [comment]
And I think you're a fucking idiot for many reasons and I'm going to leave it at that.

**Comment by pireamaineach** [comment]
I mean, why is this any better? You're not making any arguments. There's no reason for the new system, it doesn't improve anything, it looks like shit, it limits freedom. It's not even any more intuitive. It's just utterly vapid.

**Comment by spessbro** [comment]
alright here's why the new cables are good
1.they're much easier to use because you can at worst trial and error before figuring it out
2.they require much less precise clicking
3.they limit people being bonobos and wiring stuff like retards cause "hehe funni solars look like dick"

**Comment by actioninja** [comment]
It's way more intuitive and easy to use. I don't know how you could think otherwise besides "It's not how it used to be so it's bad." It's literally one cable per tile, they autoconnect. How is that not intuitive? You're saying I'm not providing any arguments but all you're saying is "boohoo old wires worked fine and totally weren't confusing," which they were. I remember from when I first started playing the first time I placed cables I thought to myself "wow that's a stupid ass way of designing that" that and my opinion never changed after playing engineer for a shitload of time. Old wires were fucking stupid. I understood how they worked, never had an issue with using them, but they were just stupid as hell and a pain to work with every time I needed to.
"Freedom" isn't needed for this. What do you need the freedom for? So you can do your epic shitty solar wiring memes? I don't give a shit.
"It looks ugly" is a stupid argument for removing anything and always will be.

**Comment by pireamaineach** [comment]
1. Not really.
2. Not even that hard it's not like cables are tiny.
3. Limiting people isn't a positive thing, at least not here.

**Comment by pireamaineach** [comment]
> It's way more intuitive and easy to use. I don't know how you could think otherwise besides "It's not how it used to be so it's bad." It's literally one cable per tile, they autoconnect. How is that not intuitive? You're saying I'm not providing any arguments but all you're saying is "boohoo old wires worked fine and totally weren't confusing," which they were. I remember from when I first started playing the first time I placed cables I thought to myself "wow that's a stupid ass way of designing that" that and my opinion never changed after playing engineer for a shitload of time. Old wires were fucking stupid. I understood how they worked, never had an issue with using them, but they were just stupid as hell and a pain to work with every time I needed to.
> "Freedom" isn't needed for this. What do you need the freedom for? So you can do your epic shitty solar wiring memes? I don't give a shit.
> "It looks ugly" is a stupid argument for removing anything and always will be.

It's just not any more intuitive almost entirely because it looks like utter shit. It's just as confusing to look at and requires the same amount of bare-minimum effort studying that the previous had. It doesn't help anyone, it only limits people, it looks worse.
If you wanted to rework wiring, why this drastic of a change?

**Comment by pireamaineach** [comment]
Anyway I probably need to make this actually-- y'know-- work, so. Even if it's not merged I'd like a shot.
Orange man's a tad unpredictable but I have a feeling he's not going to side with me on this one, we'll see.

**Comment by actioninja** [comment]
Again you just fall back to "it looks bad"
This is fucking stupid, and is going to get closed anyways.

**Comment by pireamaineach** [comment]
I mean you keep laying into that one as if it's my only argument, and as if it's not valid.

Looking awful is a valid complaint.

**Comment by spessbro** [comment]
guys after doing some "extensive research" i've figured out that most of the issues concerning the new cables are related to smes and the fact that they new wire fucks with them so maybe we should fix that and keep the new wires ^-^

**Comment by pireamaineach** [comment]
Not the place, different P.R.

**Comment by spessbro** [comment]
i know but instead of trying to remove the wires let's just make them good. :/

**Comment by pireamaineach** [comment]
It's kind of the system's fault. I guess you might be able to but it's very difficult to make it look good with the way they're forced to connect. At the very least you could have less circles, but again, "it look bad" isn't the only problem.

**Comment by pireamaineach** [comment]
Perhaps this time, Orange man will look favourably on me.
Perhaps.

**Comment by CPTANT** [comment]
> Having two separate grids that pass over eachother at all. I know that's not exactly necessitated, ever, but it's something you can't do anymore, 

Easily solved by adding different wire colours that don't auto connect.

**Comment by pireamaineach** [comment]
> > Having two separate grids that pass over eachother at all. I know that's not exactly necessitated, ever, but it's something you can't do anymore,
> 
> Easily solved by adding different wire colours that don't auto connect.

Clever idea, not what I want to do. I prefer the old system, through and through. I actually gave myself a few days just in case it was uh... me not liking change, as most people don't, and it really never grew on me in the slightest.

**Comment by CPTANT** [comment]
Old wires were unintuitive as hell and I never want to go back. Even making a straight line felt awkward because you had to place one half first and then use another position or action to place the second half.

**Comment by pireamaineach** [comment]
I mean you have to do the same thing now.

**Comment by CPTANT** [comment]
On the same tile?

**Comment by pireamaineach** [comment]
You have to click once on the same tile instead of twice. Change of the century.

**Comment by CPTANT** [comment]
If you use the stand next to the tile method you had to click, then relocate 2 tiles up and click again. For each tile.

If you use the Ctrl click method (which is also completely unintuitive) you had to stand on the tile, face one direction, CTRL click, face the other direction and CTRL click again. 

Instead of just clicking once.

**Comment by pireamaineach** [comment]
Orange man said no. I'll work on resprites or something. Once layers come out sure it'll be "fine."
Can't help but be upset, I guess.

**Comment by optimumtact** [comment]
\>old system was fairly intuitive
No it wasn't
\>The old system allowed you to do more complex things
Yes but colour separation and layering is coming, which will allow for N^M complexity, just like the new plumbing
\>The old system is fun
no it really fucking wasn't
\>the new system isn't better
It's miles fucking better, both from not being based soley around pixel hunting and knowing exactly what tile and direction to face on to get a working wire network

The only difference is you can't do wire layouts next to each other yet, and that's being solved, and was barely ever used in all of our existing maps because it was such a pain in the ass to make any complex wiring work at all.


I don't see any path that ends in me reverting smart cables

**Comment by pireamaineach** [comment]
Orange man stop he's already dead.

**Comment by optimumtact** [comment]
Yeah but I'd like to give my reasons

**Comment by pireamaineach** [comment]
Orange man please I just want to sulk in peace.

**Comment by pireamaineach** [comment]
Fair, though. I think uh... I'll work on fixing the circles or something, I don't know.

**Comment by optimumtact** [comment]
given that you don't have to pixel hunt any more, the junctions and three way and four way joins can be completely overhauled in visual look.

**Comment by optimumtact** [comment]
also if you're upset with the existing connection/auto join logic you can make it way smarter where it considers the second ring of tiles around it as well.

There's nearly infinite possibilities to make that improved.

**Comment by pireamaineach** [comment]
Yeah but it's all just trying to imitative the old system, which visually worked fine and had a fair amount of complexity to it. I actually felt accomplished when I wired things in the old system.

**Comment by pireamaineach** [comment]
I don't know if that's valid for the direction of the codebase but I can't help but feel like shit about it. It's just sad, I'm going to miss old wires.

**Comment by CPTANT** [comment]
>I actually felt accomplished when I wired things in the old system.

Because it took way more effort than necessary.

**Comment by pireamaineach** [comment]
> > I actually felt accomplished when I wired things in the old system.
> 
> Because it took way more effort than necessary.

It really didn't. It wasn't effort it was just knowledge. I felt accomplished because I actually had to know something to do it, it wasn't just **wire under grille.**

**Comment by optimumtact** [comment]
it worked fine visually, and it didn't work fine in any other respect.

Wiring is a small line detail as part of a bigger thing, which is usually rebuilding or fixing rooms, which never happened becuase of how annoying wiring, piping and other building actually really is.

Whatever sadness you are feeling will pass, and you'll instead enjoy actually building new rooms without taking 300 hours and having the shuttle called before you even get the wiring in.

**Comment by pireamaineach** [comment]
I wired rooms now and then, and I was atmos tech. Wires are neglected mostly because of a lack of insuls and lack of engineers actually helping people. Wiring is actually fairly simplistic in the base station, I know very few things besides grilles and APCs that are wired.

**Comment by optimumtact** [comment]
yes I wonder why the wiring is simplistic.


Think of the possibilities enabled now!

Add layering and colours, and I can finally remove APC's and actually put power to every individual machine in a room

**Comment by pireamaineach** [comment]
oh god oh fuck oh no

**Comment by optimumtact** [comment]
Imagine if a power network was actually that, a power network.

IMagine if there was different voltage networks for different station equipment

**Comment by CPTANT** [comment]
> > > I actually felt accomplished when I wired things in the old system.
> > 
> > 
> > Because it took way more effort than necessary.
> 
> It really didn't. It wasn't effort it was just knowledge. I felt accomplished because I actually had to know something to do it, it wasn't just **wire under grille.**

I just broke down how the old system literally required 5 times as much actions to place a single straight line.

**Comment by pireamaineach** [comment]
That'd actually be made worse by this because making that visually look good would be a nightmare on this system.

**Comment by optimumtact** [comment]
If you want complexity I can fucking drown you in complexity, I don't need wires being hard and fiddly to place to do that

**Comment by optimumtact** [comment]
@pireamaineach and yet it can be done, becaus eyou can put 7 wires on one tile and have a logical power bus and it will look amazing in maint

**Comment by CPTANT** [comment]
> 
> 
> yes I wonder why the wiring is simplistic.
> 
> Think of the possibilities enabled now!
> 
> Add layering and colours, and I can finally remove APC's and actually put power to every individual machine in a room

I don't know if that ideal, APC's give control over turning of equipment in an area.

**Comment by pireamaineach** [comment]
Honestly with the old system you could've managed that and it would look nice, to boot.

**Comment by pireamaineach** [comment]
At the same time, "Why?"

**Comment by optimumtact** [comment]
@CPTANT so add a switch to your in room wiring network where it crosses over from maint.

Hell the APC could still exist for that function

**Comment by optimumtact** [comment]
\>Why
You literally just argued that you felt accomplished when doing wiring.

Think of how massively more rewarding this will feel

**Comment by pireamaineach** [comment]
It won't because I don't make it.

**Comment by pireamaineach** [comment]
Imagine mapping that in Dream Maker.

**Comment by optimumtact** [comment]
Imagine a noob engineering connecting the inner room network to the high voltage maint network and every machine in the dept blows a fuse and needs repairing.


IT's going to be awesome

**Comment by optimumtact** [comment]
and just wait until I introduce the data network

**Comment by pireamaineach** [comment]
Blowing an APC actually just makes it give the equipment in that room unadulterated power.

**Comment by optimumtact** [comment]
HOO BOY if you thought electricity was going to be a complex network, I have news for you

IM talking an 8 bit, signalling network, with a custom 8 bit mips based asm language for writing computer equipment

**Comment by optimumtact** [comment]
It's going to blow your fucking socks right off

**Comment by pireamaineach** [comment]
alright now make a simulation of java and make us have to write in that

**Comment by pireamaineach** [comment]
all machines are uncoded roundstart

**Comment by pireamaineach** [comment]
Nano-Trasen uses Java:tm:

**Comment by optimumtact** [comment]
NT uses rust :tm:

**Comment by pireamaineach** [comment]
Nano-Trasen would use Q#, realistically.

**Comment by pireamaineach** [comment]
My favourite programming language.

**Comment by spessbro** [comment]
oranj to the rescue

**Comment by pireamaineach** [comment]
Implying this had a strong chance of getting merged.

**Comment by optimumtact** [comment]
holy shit imagine if lights required cables

man this is going to be awesome

You could even flicker the lights by playing with the lighting circuits

**Comment by SpaceManiac** [comment]
the lights in a room briefly dimming when power usage spikes would be an unironically good feature if it wasn't likely to be a performance sink

**Comment by YakumoChen** [comment]
how would malf AI work without APCs?

**Pull request closed without merging**
