### PR TITLE
Add warning about list creation time at startup and the hidden init proc overhead

### PR DESCRIPTION
**Pull request by optimumtact**
Prevent further savaging from lummox

### CODE REVIEW

**Comment by Core0verload** [comment]
Just don't let it turn into micro-optimisation madness like it happened with itypeless loops.

**Comment by MrStonedOne** [comment]
>micro-optimisation meme meme.

**Comment by optimumtact** [comment]
@Core0verload if something takes you a few extra seconds to do and reason about it, it's worth doing, even if the speedup is not much, it will add up over time.

**Comment by Core0verload** [comment]
Putting all the list creations in new would wreck readability.

**Pull request merged**
