### PR TITLE
resprites the genesploicer

### PR DESCRIPTION
**Pull request by CoiledLamb**
## About The Pull Request
i found this ugly sprite in the files and the shape was interesting enough to make me want to try updating it.
image
the name also made me laugh a little. now you can laugh too:
image
## Why It's Good For The Game
less cruft is good. this can also be used as a reference to learn how to sprite certain greebles like keyboards, screens, rounded edges, and raised stands. or the sprite can be used for another device in game. i'm not picky
## Changelog
:cl:
image: resprites the genesploicer.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
the display being bigger looks better than it being small with (very) thick borders

**Review by Wallemations — APPROVED** [review]
idfk what a genesploicer is but good sprite

**Comment by CoiledLamb** [comment]
> idfk what a genesploicer is but good sprite

maxresdefault

**Comment by Ghommie** [comment]
These are definitely better. Alas, the "genesploicer" icon states are currently unused and may as well be removed from the `.dmi` file, tho the [unused sprites repository](https://github.com/tgstation/SS13-sprites) might appreciate this contribution. It's a shame the game won't be seeing these new sprites anytime soon.

**Pull request merged**
