### PR TITLE
License Buff/New Title Screen for Metastation

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Wanted to add a new title screen for metastation, but don't want to add it under the commercial license and we've been talking about changing it for a while anyway (though since goon is all NC who knows if we were even allowed to change it in the first place).

These PRs should probably be atomic, but I'd rather try updating the license rather than adding a single snowflake license line for one image.

title

:cl: spessmenart
add: Added a new titlescreen for metastation.
/:cl:

@tgstation/commit-access

### CODE REVIEW

**Comment by Jordie0608** [comment]
Quite a significant change just for one file; i think it'd be smarter to list this as -NC and have a PR for changing the codebase's licence elsewhere.

**Comment by KorPhaeron** [comment]
We've had this PR several times before (and Cheridan/oranges/Remie all seem to want it) so I thought it made more sense to just get this over with than add an exception

**Comment by Jordie0608** [comment]
Says the guy who closed PRs earlier today for not being atomic =P

**Comment by Incoming5643** [comment]
It's mildly dangerous to downstream servers to suddenly change image licensing going forward. It might turn some greedy people off.

**Comment by Incoming5643** [comment]
Just as a thought we could just make title screen selection a proper server config (it really should be anyways) and then run the -NC images locally but not have them here on the codebase. 

I don't know where on the site you'd put that sort of license notice, but it feels kosher to me.

**Comment by optimumtact** [comment]
I don't want to alarm you but it's likely that bundling non commercial sprites is a violation of the AGPL license as it requires the bundled work is allowed to be sold with a dollar value attached and no bundled item can limit or reduce that license with it's own license.

not a lawyer but that's my understanding

**Comment by optimumtact** [comment]
From further reading it's not clear on the compatibility of the licenses and it hasn't really been tested (it bounds on if the images/art are a component of the game or not)

I would be iffy about the relicense going forward but limited assets under CC-BY-NC-SA

not that our licensing situation is particularly clear anyway

**Comment by optimumtact** [comment]
https://www.linux.com/news/trouble-artwork-and-free-software-licenses is the clearest discussion I have found.

**Comment by AnturK** [comment]
So if i'm reading this correctly we already have incompatible licenses.

**Comment by optimumtact** [comment]
not a lawyer and the line is fuzzy because it's not our code doing the transformation and display of the icons, it's actually the byond runtime vm and client which of course is a completely closed license.

In short better to not think about it and just assume it's all under the stated licenses and that no commercial entity would want to touch it with a 500 foot pole (which is a good thing imo)

**Comment by coiax** [comment]
Why is this a title for metastation and not the others?

**Comment by Incoming5643** [comment]
update I am now actively working on the idea I had in https://github.com/tgstation/tgstation/pull/24544#issuecomment-282963607

**Comment by anconfuzedrock** [comment]
I don't understand this but it seems like a bad idea

**Comment by Cyberboss** [comment]
If you're going to do map specific titles, can we put the NAME of the station in the image please?

**Comment by optimumtact** [comment]
if you don't understand then don't comment

**Comment by coiax** [comment]
I mean, why can't it just be an image for all the stations?

**Comment by KorPhaeron** [comment]
People would flip out if we actually replaced the title, and I think it would be nice if you could tell which map you were on based on which titlescreen.

Variety is nice as well

**Comment by coiax** [comment]
I think the picture is pretty and thematic... but I don't understand why it's bound to meta specifically. Is it supposed to be from a specific vantage point on Metastation?

**Comment by PKPenguin321** [comment]
i tried my hand at photoshoping another boarder on the left to make it more border-y for a title screen
shitty edit

**Comment by KorPhaeron** [comment]
@coiax 

Well it's gotta be bound to something, and meta is one of the three main maps, so figured I may as well start with that one. It's also loosely inspired by the meta maint bar

**Comment by KorPhaeron** [comment]
@PKPenguin321 

Perspective is wrong now

**Comment by Incoming5643** [comment]
@KorPhaeron if you haven't looked at #24563 you should now. I've gotten it to the point where you could get that image uploaded locally, tie it to metastation, and sidestep all these licensing changes if you want.

(please no speed merges guys, once a license changes, it can't exactly change back.)

**Comment by KorPhaeron** [comment]
Yeah sure, thanks

**Pull request closed without merging**
