### PR TITLE
Reremoves Freon from the maps

### PR DESCRIPTION
**Pull request by ChangelingRain**
Also removes BZ from several locations where it was still on the maps despite supposedly being removed (#20510)

### CODE REVIEW

**Comment by optimumtact** [comment]
Could you actually provide proof of the link or are you just guessing like everyone else?

If it's as bad as you say it should show up in the logs

**Comment by ChangelingRain** [comment]
kor asked me to do it because we keep getting player reports of lag, and admin reports of lag, and servers refusing to restart due to lag, so,,,

**Comment by optimumtact** [comment]
I mean If I get a bunch of people to say that stuns are crashing and lagging the server does that mean I get to remove stuns?

**Comment by PKPenguin321** [comment]
hello darkness my old friend

**Review by optimumtact — APPROVED** [review]
alright, I'm suitably convinced thanks to TheSteveo who pulled a profile during the lag and it point conclusively to slip code

**Comment by optimumtact** [comment]
https://file.house/Sx4s.txt

**Comment by Iamgoofball** [comment]
CAN YOU GUYS GIVE ME SOME TIME TO ACTUALLY FIX THE CRASH INSTEAD OF JUST TRYING TO INSTANTLY REMOVE IT EVERY TIME I GET A FUCKING LEAD ON THE FIX

**Comment by KorPhaeron** [comment]
You've had two weeks to fix it, daily crashes are not acceptable

**Comment by Iamgoofball** [comment]
HOW DO I FIX SOMETHING WITH NO REPRODUCTION STEPS

**Comment by Iamgoofball** [comment]
I GOT THE INFORMATION TODAY

**Comment by optimumtact** [comment]
that doesn't matter, we have to act to bandaid the problem until you can get a fix in, irrespective of if you have reproduction steps or not.

It's literally bringing the server to it's knees

**Pull request merged**
