### PR TITLE
Adds a new lobby song.

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Jordie0608** [comment]
I listened to a few seconds of this and now my ears have fallen off thanks goof.

**Comment by TechnoAlchemisto** [comment]
bad

**Comment by TechnoAlchemisto** [comment]
bad goofball

**Comment by Shadowlight213** [comment]
Holy fuck my ears.
Auditory assault.

**Comment by Mervill** [comment]
some people don't instantly mute the lobby audio?

**Comment by GunHog** [comment]
This must how drunken singing sounds...

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
Can you make the song not suck.

**Comment by AnturK** [comment]
Write a config loaded lobby music if you want to add more, let's not bloat sounds filesize more. (Especially for this one)

**Pull request closed without merging**
