### PR TITLE
Revert "Add the ability to use blips as your character's voice"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#77640

Discord_iPE1cmuUrY

This is causing big problems right now and we've agreed to a, at minimum, temporary revert so that we can re-approach this at a later date and do things properly

@MrStonedOne pls i need that TTS repo im begging you pls

### CODE REVIEW

**Comment by Rex9001** [comment]
Yeah this is for the best, the blips are so bad that it made me turn tts off.

**Comment by Inari-Whitebear** [comment]
Ah nice, I was actually about to turn it off, good to know. Though I'm not sure what this "future proper implementation" will be like.

Like, sure, I don't like many of the voices for one reason or another, but.. eh, I just pick one ultimately

**Comment by CliffracerX** [comment]
This isn't appropos to the PR persay but I'd like to second Goof's request for the TTS repo so I can actually set up a full version for testing & development on my local.

**Comment by Watermelon914** [comment]
You can already do that if your intention is to do testing.

Go to tools/tts and follow the instructions laid out in the readme.
The TTS server that MSO has is more so the production version that runs on a GPU server.

**Comment by CliffracerX** [comment]
> You can already do that if your intention is to do testing.
> 
> Go to tools/tts and follow the instructions laid out in the readme. The TTS server that MSO has is more so the production version that runs on a GPU server.

I'm aware; I was able to set up the regular version without (much) issue, but the RVC variation used on live that supports voice pitch alteration & similar requires files that aren't currently available & lacks the documentation to generate your own.

**Comment by Mothblocks** [comment]
goof reverting the fixes to the dockerfile that made it actually work at all probably doesnt help

**Comment by CliffracerX** [comment]
I'd already fixed the dockerfile on local, neither this nor the original PR touches the tts_rvc code that production uses.

**Pull request merged**
