### PR TITLE
add lizard gas station to icebox ruins

### PR DESCRIPTION
**Pull request by EEASAS**
## About The Pull Request
Adds a new ruin to the game, on Ice Box.
It is based off the Lizard Gas ruin that appears in space.
## Why It's Good For The Game
More ruin equal more better
## Changelog
:cl:
add: Added a new ruin to Ice Box Station, Lizard Gas Station
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
pretty low efgort to havw the same thing

**Comment by zxaber** [comment]
What do you expect, it's a franchise.

**Review by Jolly-66 — COMMENTED** [review]
I'm not a maintainer but I do like giving mappers feedback!

<details>
<summary> Feedback images </summary>

You need `/area/template_noop` and `/turf/template_noop` surrounding your ruin.
image

Also you should make a custom area rather than using the root /area/ruin.
image

We don't run anything through walls usually.
image

Your wire set up isn't exactly how you think its going to work. Machines and lights are wired "magically" by the APC. Wires are only there to connect power producers to APCs.

The only thing of major note is the PACMAN, which I don't believe will work directly on top of the APC. Someone else can correct me if I'm wrong here.
image

This crate is inaccessible without deconstructing the table or gas tank.
image

These are grill+pane spawners. You're looking for `/obj/structure//window/spawner/directional/`.
image

Same here, use `/obj/machinery/door/window/directional`.
image

This vent won't connect.
Also this is just a small nitpick but you could make these air pipes blue :)
image

You're missing a wall!
image

These grills you're using will either be grills or turn into trash, just as a heads up! `/obj/effect/spawner/random/strucutre/grill` may be what you're looking for? They can spawn as assembled grills OR broken ones.
image

Regular plating under your windows.
image

This entire backroom is going to have different atmos than the rest of the store. Make a new type that have the same initial gas mix as the other floor tiles you've used.
image

You also don't have an air alarm anywhere :(
No one will be able to tell if the atmos is safe or not.

If you don't know a damn thing I said please feel free to poke me on Discord! I'll happily walk you through.

</details>

**Comment by EEASAS** [comment]
maintenainer 's dont merge yet im mexiangfh fgh with the map thing im WOrking on ghubuhdf

**Comment by EEASAS** [comment]
ok merge now

**Comment by EEASAS** [comment]
@san7890 didn't you want to review them separately or something

**Review by Maurukas — CHANGES_REQUESTED** [review]
Main issues I see are two the Jolly already hit remaining:

- Custom areas are needed for the ruin. Currently everything is indoors and under generic `/area/ruin`. A custom area should be created and added to the code/game/area/areas/ruins/icemoon.dm file. If you're not familiar with how to do this, please ask in mapping general.
- You have atmos devices, but no air alarm.

**Comment by EEASAS** [comment]
> Main issues I see are two the Jolly already hit remaining:
> 
>     * Custom areas are needed for the ruin. Currently everything is indoors and under generic `/area/ruin`. A custom area should be created and added to the code/game/area/areas/ruins/icemoon.dm file. If you're not familiar with how to do this, please ask in mapping general.
> 
>     * You have atmos devices, but no air alarm.

done

**Review by Maurukas — APPROVED** [review]
Sorry for the delay, I lost track of this one.

**Pull request merged**
