### PR TITLE
Custom sprites for relics

### PR DESCRIPTION
**Pull request by DaCoolBoss**
## About The Pull Request
These items never had sprites of their own, they just reused sprites of seemingly random assemblies as placeholders since they were added 9 and a half years ago. So now they do. New sprites are based heavily on the placeholders and designed to look like crude gadgets jury-rigged out of common items in maints.

Old:
the old sprites

New:
the new sprites
## Why It's Good For The Game
This looks better I believe.
## Changelog
:cl:
image: Relics ("strange objects") now have unique sprites.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
the guntitool......

**Comment by Loafin34** [comment]
could you add back the orange box thing?

**Comment by DaCoolBoss** [comment]
You mean the plasma tank or the igniter?

**Comment by atlasle** [comment]
> You mean the plasma tank or the igniter?

both

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
