### PR TITLE
radiation pulses now affect multiple zlevels

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Rad pulses affect multiple zlevels

## Why It's Good For The Game
More features for multiz maps, rads are no longer safe when used on other station levels

## Changelog

:cl:
balance: radiation pulses will now affect other z levels too
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
Noting down what I wrote on discord:
My concerns with this are that 

- The Z levels above/below the engine and torus would be remapped to be blocked off. This means that the only way this feature would interact with people is either in case of bad mapping or when someone puts a bunch of radiation sources above/below another Z level to kill people with no counterplay.
- Getting irradiated is already extremely unfun, with this change you'd have to check up to two other Z levels (instead of just nearby maint) when your hair randomly starts falling out.

I'm all for more cross Z level interactions, but radiation is probably the worst feature to pick for that.

**Comment by Ghilker** [comment]
I agree, radiations are not great to deal with, but is better to be consistent and have all three types of "pulses" interact with other zlevel as i did in #61360 and #61351

**Comment by MMMiracles** [comment]
rads bleeding through floors is going to be cringe on any multi-z map, so unless you plan on adding something to help against that it'll be lame as hell and kill off any potential tower-like designs

**Comment by 170141183460469231731687303715884105727** [comment]
Lol R.I.P tram medbay.

**Comment by CPTANT** [comment]
Invisible death field, now with more undetectable!

**Comment by Ghilker** [comment]
As i and other people said in the discord, this won't be much different from having a rad source behind a wall

**Comment by LemonInTheDark** [comment]
I don't like this. consistency isn't worth invisarads to me. Our game wasn't made with multi levels in mind. There's too much stuff that just doesn't mesh with it well at all. Not in terms of not supporting it, but in terms of not being designed for it.

Can't see the radiation source, have no way of knowing about the bomb, etc etc.

**Comment by moocowswag** [comment]
What about a sort of grace period in the form of rads from lower z levels only effecting floor tiles or something and then it has to spread from that other more visible source to effect you.

**Comment by LemonInTheDark** [comment]
Especially given that this would absolutely destroy the one map we have that's properly mutliz, I don't think this is a good idea.
In this series of prs, radiation strikes me as the most aggressively bad, explosions are meh, and emps are fine.

Can't just be breaking our maps, I'm not too much of a fan of how this is implemented either, that and the prospect of tripling ssrad's cost under high load. It's certainly not feasible currently

**Comment by Ghilker** [comment]
Aight I'll close this for now since there might be a rad removal in the future so this feature will become obsolete fast, please don't forget about the other two prs

**Pull request closed without merging**
