### PR TITLE
Adds an entity input to the GPS component

### PR DESCRIPTION
**Pull request by TheSmallBlue**
## About The Pull Request
Title. Wanted to make this after my fix PR got merged due to my low score, but yesterday I heard of the august code freeze, so I thought I'd try and PR this since I think it'll work excellently with the other active PR's like #60557 / #60527.

## Why It's Good For The Game
Allows for more advanced traitoring, cooler automated systems (like for example a machine that automatically sets a culprit to arrest and teleports them to jail (though it'd be tough to do since the culprit could easily outrun the teleporter while its in its cooldown)) and generally completes the entity info trifecta of name, health and location.

## Changelog
:cl:
expansion: Added an entity input to the GPS component
/:cl:

### CODE REVIEW

**Comment by Gurkenglas** [comment]
make it only work when the circuit sees the entity.

**Comment by TheSmallBlue** [comment]
Gonna work on this a bit further since Watermelon made me realize that this is very overpowered. I'll aso take this opportunity to stall until my fix pr gets merged so that my gbp isn't as bad

**Comment by Mothblocks** [comment]
this is absurdly overpowered yes 😛

**Comment by TheSmallBlue** [comment]
20 tiles is a round a department's size, which I think is a fair size for something like this. Big enough for fun, not big enough for straight up unfairness.

**Comment by Gurkenglas** [comment]
i dont think that counts as in sight. you could make it global but make it only work if the entity emits a GPS signal, and make people with the Antennae mutation emit a GPS signal.

**Comment by TheSmallBlue** [comment]
I intend for this to be some sort of help for traitors, if I make it in sight then I might as well just stand there an follow the person with my eyesight

**Comment by Gurkenglas** [comment]
yes thats the point, the target is supposed to have some sign of whats coming

**Comment by TheSmallBlue** [comment]
Fair enough, I'll change it from 20 tiles to 10, which is akin to normal player vision

**Comment by MrDoomBringer** [comment]
what no 
listen to @Gurkenglas is saying
the target is supposed to have some sign of whats coming
make it based on sight

**Comment by TheSmallBlue** [comment]
Honestly I'm a bit scared of doing sight because I have no idea how to, but how's that?

**Comment by Mothblocks** [comment]
Going to close this just for now, not on grounds of it as an *idea* (except that it absolutely should be checking for sight and the victim should know they've been spotted), but that you are at negative GBP and we are in a code freeze, and the tracker needs cleaning.

**Comment by TheSmallBlue** [comment]
Fair enough

**Pull request closed without merging**
