### PR TITLE
Syndicate Bomb Core Payloads Can Only Be Triggered via the Bomb

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Basically, you can't extract the bomb core, slap a 10-second c4 on it/on the shell/and run off having triggered an incredibly powerful explosion. This is accomplished by having the syndicate bomb override ex_act (it will be deleted if the explosion goes off), as well as the payload itself being subtyped into something resistant to bombs and burning.

In-universe, this is described as the shell being quite resistant to forms of external explosive force- but if any explosive force comes from within the bomb's shell: kabloom. The bombcore itself has been redesigned (in a rare moment of non-ineptude) by Donk Co., who has redesigned the bomb core payload from the ground up- meaning that it can only be detonated electronically by an impulse from the bomb machinery. Cutting the wrong wire and attempting to get rid of the bomb by hitting it with an axe or something will still cause it to blow up, but you know how those things can be.
## Why It's Good For The Game

I feel like the point of the syndicate bomb is to be a threat for the crew to match up against. I want a clown in bomb squad gear to head out to the site and sweat trying to figure out which wire it is, until.... KA-BLHONK: red mist. Or, I want some "helpful" assistant to interrupt someone's session by going "I KNOW WHAT WIRE IT IS", and having those odds of either blowing everyone around them up or actually saving the day.

Being able to detonate something that was balanced and designed to have _at least_ one minute and a half in **10 SECONDS** is just so injurious to the game. You can buy a shitload of these bombs, extract the cores, slap c4 on it and go around the station doling out some serious explosions. You can run into medbay, wrench it down, slap a c4 on it AND NO ONE CAN DO ANYTHING ABOUT IT! They can't cut wires, they can't figure it out to save the day, all they can do is run. Running from danger is fine and acceptable, but it's just completely stacked against the crew in a way that I feel needs to be rectified somehow.

I like the idea of purposefully fucking with the wires on the spot so you sacrificially kill everyone, that feels quite fair to me. I just simply don't like the fact that you can waltz around the station punching huge gaps in the hull (remember, putting c4 on the bomb core itself would cause it to go kabloom) with nearly nothing as far as risk. It's way too rewarding for something very easy to accomplish (there's a reason why it's 90 seconds- it's not meant to be easy to accomplish).

This doesn't affect base bombcore behavior, just the explodey ones that come standard in syndicate bombs.
## Changelog
:cl:
balance: After an unfortunate event occuring when some nuclear operatives took the ship to a Fireworks Store, the Syndicate have re-engineered their bomb cores to only explode when electronically triggered by the bomb shell itself. The payload inside a standard syndicate bomb can not be exploded with another explosion, you must keep it in the bomb machinery for it to actually do some explodey stuff.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
I completely agree with the "Why It's Good For The Game" section

**Comment by ArcaneDefence** [comment]
This also bodies nukies putting a syndiebomb payload in a storage implant that will detonate on death/deliberate activation of their microbomb implant

**Comment by ATH1909** [comment]
> This also bodies nukies putting a syndiebomb payload in a storage implant that will detonate on death/deliberate activation of their microbomb implant

true, might be worth explicitly mentioning in the changelog

**Comment by ATH1909** [comment]
should this affect emp bomb cores?

**Comment by san7890** [comment]
> > This also bodies nukies putting a syndiebomb payload in a storage implant that will detonate on death/deliberate activation of their microbomb implant
> 
> true, might be worth explicitly mentioning in the changelog

i've never heard of anyone doing that but i'll write a bit about that.


> should this affect emp bomb cores?

EMPs don't gib. they're annoying, but you can recover (or get picked off without communications). i'm not interested in making that change at this time or in this PR, i'm mainly concerned about destruction.

**Comment by Serxule** [comment]
does this affect chain reactions/planting c4 on the bomb itself? i dont really like this change

**Comment by SkeletalElite** [comment]
So if I were to say drag a welding fuel tank over a bomb, and then welder bomb the bomb. Is it possible the welderbomb can destroy the bomb without it going off? Can I reduce the bomb to basically nothing by just setting off a smaller relatively harmless explosive on top of it? What about with a high capacity weling fuel tank

**Comment by timothymtorres** [comment]
Can you pulse the wires on the bomb core?  If so, this can be bypassed by just slapping a signaler on it and then remotely detonating it.  Also I do believe nuke ops have the remote denotation switch.  Just something to think about.

**Comment by san7890** [comment]
> Can you pulse the wires on the bomb core? If so, this can be bypassed by just slapping a signaler on it and then remotely detonating it. Also I do believe nuke ops have the remote denotation switch. Just something to think about.

okay but at least you can not c4 the bombcore itself

> does this affect chain reactions/planting c4 on the bomb itself? i dont really like this change, especially since things like singletanks and maxcaps are way easier to mass produce in a shorter time, one bomb is 12tc

yes. making a singletank/maxcap requires skill however, and there is some risk (someone seeing you with that bulky ass fucking bomb and tackling you before you can get to use it)- or at least even more risk than just having a c4 and bomb core in your backpack and being able to assemble something incredibly destructive in relatively very little time. 

> So if I were to say drag a welding fuel tank over a bomb, and then welder bomb the bomb. Is it possible the welderbomb can destroy the bomb without it going off? Can I reduce the bomb to basically nothing by just setting off a smaller relatively harmless explosive on top of it? What about with a high capacity weling fuel tank

If you're doing that you're going to injure yourself setting off the welding tank, so I don't really care. It returns on `ex_act()` though, so anything that explodes (which all uses the same common framework) has no effect

**Comment by SkeletalElite** [comment]
> If you're doing that you're going to injure yourself setting off the welding tank, so I don't really care. It returns on `ex_act()` though, so anything that explodes (which all uses the same common framework) has no effect

not if you have a laser

**Comment by B00tz** [comment]
> You can buy a shitload of these bombs, extract the cores, slap c4 on it and go around the station doling out some serious explosions.

I don't know if this is true, or atleast as someone who has 4000+ round I don't think I've ever seen someone be able to buy more then 2. Wiki says it costs 11 TC and since you'll need 1 to buy the c4 that makes this combo a 12TC combo. Like if you got a round where you saw someone buying "a shitload" of them and just cuban pete'in it up I'd love to see it. 

I'd rather see a change in the TC cost rather then a removal of a cool play on game mechanics.

**Comment by Serxule** [comment]
> > You can buy a shitload of these bombs, extract the cores, slap c4 on it and go around the station doling out some serious explosions.
> 
> I don't know if this is true, or atleast as someone who has 4000+ round I don't think I've ever seen someone be able to buy more then 2. Wiki says it costs 11 TC and since you'll need 1 to buy the c4 that makes this combo a 12TC combo. Like if you got a round where you saw someone buying "a shitload" of them and just cuban pete'in it up I'd love to see it.
> 
> I'd rather see a change in the TC cost rather then a removal of a cool play on game mechanics.

regardless, the most you'd be able to buy at the end of a 1.5hr round is maybe 4-6, if you grind traitor objectives the entire time, and depending on rng, the most i've never gotten in total (including 20 roundstart) is 70 but that was once, i generally get at most around 50tc in total (including 20tc roundstart), considering it takes longer than something like maxcaps/singletanks and is massively less mass-produceable i dont think it should be nerfed, syndibombs are an easy way to destroy something later on, and should stay that way

**Comment by itseasytosee** [comment]
This is cool. It's still possible to to a quick detonation through hacking, which was the more interesting method regardless.

**Comment by Overuseddart** [comment]
If this change goes through will there be a compensation buff or decrease in price? It seems the only thing people do with these bombs is c4 them because they take so long to explode and you can just make a maxcap or singlecap then wrap it with less risk.

Also I think badmin bombs shouldn’t be effected by this change, they’re already more of a joke bomb.

**Comment by san7890** [comment]
> If this change goes through will there be a compensation buff or decrease in price? It seems the only thing people do with these bombs is c4 them because they take so long to explode and you can just make a maxcap or singlecap then wrap it with less risk.

That can be done in another PR, I don't want to pass those in here nor argue them here.

> Also I think badmin bombs shouldn’t be effected by this change, they’re already more of a joke bomb. 

Admins can just VV Edit the timer settings to be 10 seconds or something- this isn't an issue.

Besides, base bombcore behavior is not touched, you can still burn/explode those bomb cores (if an admin spawns one in, that is: previous behavior had badmin cores delete themselves if you tried to remove it from a bomb)

**Comment by EyEy69** [comment]
this might fix the "problem" or rapidly denotated bombs but it still leaves Bomb diffusing /unbolting stupidly easy for anyone with a pulse.

**Comment by san7890** [comment]
> this might fix the "problem" or rapidly denotated bombs but it still leaves Bomb diffusing /unbolting stupidly easy for anyone with a pulse.

that's fine

**Comment by EyEy69** [comment]
> > this might fix the "problem" or rapidly denotated bombs but it still leaves Bomb diffusing /unbolting stupidly easy for anyone with a pulse.
> 
> that's fine, because i don't think that's an issue

Shame then, because this was the only time i've seen non max-cap bombs actually kill someone in years.

**Comment by private-tristan** [comment]
🦀 No more assistants dropping a backpack with a box contained in medbay and walking out, causing all of medbay to become a hole 15 minutes into the round with no way of knowing without looking through every single storage item 🦀

**Comment by san7890** [comment]
> > > this might fix the "problem" or rapidly denotated bombs but it still leaves Bomb diffusing /unbolting stupidly easy for anyone with a pulse.
> > 
> > 
> > that's fine, because i don't think that's an issue
> 
> Shame then, because this was the only time i've seen non max-cap bombs actually kill someone in years.

you can still sacrifice yourself to take out medbay or if you're a nukie you can use the big red button. there's lotsa fun that can be had still

**Comment by itseasytosee** [comment]
> > > > this might fix the "problem" or rapidly denotated bombs but it still leaves Bomb diffusing /unbolting stupidly easy for anyone with a pulse.
> > > 
> > > 
> > > that's fine, because i don't think that's an issue
> > 
> > 
> > Shame then, because this was the only time i've seen non max-cap bombs actually kill someone in years.
> 
> you can still sacrifice yourself to take out medbay or if you're a nukie you can use the big red button. there's lotsa fun that can be had still

San did you forgor about remote signalers.

**Comment by san7890** [comment]
> San did you forgor about remote signalers.

no i didn't, see here:

>> Can you pulse the wires on the bomb core? If so, this can be bypassed by just slapping a signaler on it and then remotely detonating it. Also I do believe nuke ops have the remote denotation switch. Just something to think about.
> okay but at least you can not set a signaller on the bombcore itself or somehow compel the bomb core to go off in a very compact manner.

**Comment by Helg2** [comment]
The fuck is this skill issue

**Comment by SaingItsMe** [comment]
He is fucking removes features, and you like it????

**Comment by Toastgoats** [comment]
I only noticed this really late, does this mean syndicate bomb cores cant be used inside crafted bomb shells?
And by extension does that include base self destruct payloads?

**Pull request merged**
