### PR TITLE
Fix for the missing Exofab modules for mining borgs

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

When the big nice rework went through i think an oversight happened and the PKA upgrades were lost to the void even though they could be researched, this just re-adds them back to the exofab. The values were taken from pre-change so nothing really changed from a cost/time perspective.

Old n busted
--
image

No longer old n busted
--
image

Sidenote: Why do borgs take longer to make than mechs when they cost so littlle compared to some of em? Mfw waiting for a shell to just be built by the exo and the robo completes 3 Ripley's and halfway through the next before the borg parts were done.

## Why It's Good For The Game

Brings back the PKA tools that were missing, trying to mine at the moment with an unupgradable PKA is a pure test of sanity.

Sidenote: Why do borgs take longer to make than mechs?

## Changelog

:cl:Zergspower
fix: Fixes a possible oversight that prevented PKA upgrades being unable to be printed for borgs
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
> Sidenote: Why do borgs take longer to make than mechs when they cost so littlle compared to some of em? Mfw waiting for a shell to just be built by the exo and the robo completes 3 Ripley's and halfway through the next before the borg parts were done.



we don't like them

**Comment by Zergspower** [comment]
alright yeah im gonna need help - scratched my brain and tried various manners but i cant get rid of the runtime _and_ have it show in the mechfab

**Comment by JohnFulpWillard** [comment]
These already exist, you just have to find the design in code and make them also show up in MECHFAB

**Comment by Zergspower** [comment]
> These already exist, you just have to find the design in code and make them also show up in MECHFAB

I did... the only way i got them to show in the Mechfab was to add them to the mechfab printer dm. the problem is for whatever reason the miners are printing borg upgrades for their PKA's and have been for years.

**Comment by Zergspower** [comment]
found the issue with Mothblock's help, wasnt added to the techweb - also made the ID's follow the same formatting as the other upgrades with borg_upgrade_

**Pull request merged**
