### PR TITLE
Cult Spell Balances (Cult Stun to Cult Silencer edition)

### PR DESCRIPTION
**Pull request by Hoolny**
## About The Pull Request
https://hackmd.io/@4DLPlbnvQ3iI_XRdBhqvaQ/SkPhUoov2
image

## Why It's Good For The Game
There is a decent chunk of reasoning behind this changes so I plead to read the hackmd https://hackmd.io/@4DLPlbnvQ3iI_XRdBhqvaQ/SkPhUoov2

In a Summary of a Summary this is good for the game because it makes cult stun less powerful in combat while retaining its ability to help convert people by generally decreasing its stun time while largely increasing its muting and stuttering effects 
## Changelog
:cl:
balance: Decreases Cult Stun, stun duration from 16 to 8 seconds
balance: Increases Cult Stun, mute duration from 15 to 30 seconds
balance: Increases Cult Stun, cult slur duration from 30 to 60 seconds
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
Keep in mind, 4 seconds leaves little room for cuffing and the stun time is really long to allow room for error so even complete newbies can convert people.

So by doing this youre gonna mostly delete the skill floor of a conversion antag that already suffers npc syndrome.

**Comment by uaioy** [comment]
i dunno much about this but wouldnt it be better if it was a lower stun (1-2 seconds?) but also cuffed the person instantly with shackles that are easier to remove?

**Comment by Pickle-Coding** [comment]
This just makes conversion more sweaty by giving less time for cuffing. Most lategame cult combat is usually using a variety of other gear, so I don't think this design doc is entirely accurate.

**Comment by Peliex** [comment]
> Cult stuns are widely known as some of the most annoying things to deal with in combat, and they have received some backlash for their general design on servers and even in games at times.
I dislike this argument, it is provided as half of the reason of implementation yet there is no logs, photographs, or accounts from anyone agreeing with this statement.

**Comment by Livrah** [comment]
4 times the nerf?
I'd understant if this only affected mindshielded crew. 90% of the round cult will face total magic immune crew via Hol Melons, nerf this first.

**Comment by Helg2** [comment]
Cuffing with shadow shackles lasts 3 seconds, and you're making stun last 4 seconds?

**Comment by Bluedino1025** [comment]
I love this as the funny hand is just an instant win button, however maybe the stun time should be increased from four seconds to seven or eight?

**Comment by Mothblocks** [comment]
4 seconds is nothing

**Comment by jughu** [comment]
make the stun 8 seconds its enough for 2 cult hands to make it 16 4 forces too much cult hand empower spam you have to count the fact that smoking etc can reduce the stun time due nicotine

**Review by Mothblocks — CHANGES_REQUESTED** [review]
4 seconds is absolutely nothing and is just going to raise the skill floor needed to be a cultist and i'm already not happy with where it is. if you want to nerf it go down to something like 8-10 secnods

**Comment by DaydreamIQ** [comment]
While I agree that cult stun really needs a nerf to reduce its effectiveness in combat, I much prefer how paradise did it where you need a follow up stab with the dagger to get the full stun

**Comment by SethLafuente** [comment]
> 4 seconds is absolutely nothing and is just going to raise the skill floor needed to be a cultist and i'm already not happy with where it is. if you want to nerf it go down to something like 8-10 secnods

that would be a more reasonable step into the right direction for the spell sure

**Comment by Peliex** [comment]
To disregard new players in an antagonist role where a new player is likely to be forced to at one point or another, be a cultist midround, is flawed.  Increasing the barrier to entry on a forced antagonist role is a bad idea.

**Comment by SethLafuente** [comment]
> To disregard new players in an antagonist role where a new player is likely to be forced to at one point or another, be a cultist midround, is flawed. Increasing the barrier to entry on a forced antagonist role is a bad idea.

now is changed to 8 seconds so that might have changed your opinion not sure anyways new players will be bad at the game as new players are you can give them all the over power stuff you want and they will still die its normal for so to happen currently new players with all these cult spells still die and it isn't due to them not being strong enough and more of them lacking general game knowledge

**Comment by SethLafuente** [comment]
> 4 times the nerf? I'd understant if this only affected mindshielded crew. 90% of the round cult will face total magic immune crew via Hol Melons, nerf this first.

I was considering nerfing holy melons but that sounds more like two Prs also you can very much counter holy melons the current issue with them is that you cant see when people are holding them so people tend to do spells on those people which will be fix very soon with another PR, Ill see how this change goes and Ill change holy melons based on so

**Comment by Livrah** [comment]
Honestly it will lead to crit or kill as preferable way to "convert", cos runes take ages to scribe.

**Comment by SethLafuente** [comment]
> Honestly it will lead to crit or kill as preferable way to "convert", cos runes take ages to scribe. 

Or just make an offer rune before hand? There are spells to hide them even if common practice to make one before trying to convert someone why wouldn't you

**Comment by Serxule** [comment]
what i'd suggest is once there's enough cultists for there to be halos, have it be nerfed like this, making it not an instawin hand meaning cults nigh-unstoppable if they've gotten enough people, but still allowing cults to actually be able to convert and not always lose a few minutes in

**Comment by SethLafuente** [comment]
> what i'd suggest is once there's enough cultists for there to be halos, have it be nerfed like this, making it not an instawin hand meaning cults nigh-unstoppable if they've gotten enough people, but still allowing cults to actually be able to convert and not always lose a few minutes in

that wouldn't be really fixing the actual issue you are just taking a half-measure the problem is that cult stun lasts for 16 WHOLE SECONDS you can recognize how that's way too much time compare it to any other stun and weapon in-game proportionally that's just a ridiculous number 8 seconds is more reasonable and at best reduced to 4 seconds against mindshielded people in the future if this goes well in game

**Comment by Helg2** [comment]
Lesser stun against mindshielded people sounds a lot better, because mindshielding when cult usually just leads to you being a shade till the nar-sie summon without any advantage.

**Comment by SethLafuente** [comment]
> Lesser stun against mindshielded people sounds a lot better, because mindshielding when cult usually just leads to you being a shade till the nar-sie summon without any advantage.

That would be better but the thing is I want the base of cult stun to be not 16 seconds that is an unreasonable amount of time by any metrics even with it being 8 seconds a one hit insta stun is still plenty powerful that probably needs a bit more balancing mechanics around it like lessen on mindshields and some change on how it interacts with holy melons

**Comment by Helg2** [comment]
Leaving from the stamcrit is 10 seconds `#define STAMINA_REGEN_BLOCK_TIME (10 SECONDS)`
And it doesnt quiet matter if stun is in 1 or 2 hits because in most cases it still takes 1 hit and a shove (batons).

**Review by Fikou — CHANGES_REQUESTED** [review]
Your changelog does not tell anything to a player that logged onto the game without visiting the GitHub every single day.

**Comment by jughu** [comment]
Halving the stun would also not fix the issue because everything it does is just make people buffer more stunhands though it also would be nice if holy water deconverted faster cult can snowball harfer in conveeting but you can't snowball back cause you have to babysit them in earlh stages so  cuz they dont have red eyes/halo's yet and when they do have halos the deconverting is already out lf the window theres also a lot of cult counters in factor lets name a couple of them

Botanists growing holy melons at 100 potency thye can stop 3 cult hands where every cultist can only have a max of 4 cult hands.

Chemists/other people can neurowhine roll which gives you a random trauma aslong the reagent is in your system this includes anti magic trauma this has 0 indictators why your magic doesn't 
work beside a chatbox message nobody would read because in the heat of the moment(should really need a balloon pop up)

Genetics can use Hulk which is immune to any form of stun so cult hand simply wouldnt work
Genetics can use Void magnet which is a underused gene power you can use it to stall for time to get out of a stun like cult stun hand(or stunbaton stamcrit)

Chaplain has holy weapon which is just anti magic
Lavaland has ruins and legion oot with holy weapon

Hop can open more chaplain which will increase the number of holy weapons on the station.

**Comment by moocowswag** [comment]
mothblocks repeated what i said but louder.

**Comment by Jezzared** [comment]
> Hop can open more chaplain which will increase the number of holy weapons on the station.

No? There's one Null Rod per station. Chaplains don't start with one in their bag, so opening more chaplain slot would only mean easier holy water (which you can already have three giant tanks of).

**Comment by jughu** [comment]
> > Hop can open more chaplain which will increase the number of holy weapons on the station.
> 
> No? There's one Null Rod per station. Chaplains don't start with one in their bag, so opening more chaplain slot would only mean easier holy water (which you can already have three giant tanks of sitting in the brig).

except they do if therea more slots

**Comment by Helg2** [comment]
> No? There's one Null Rod per station.

If i dont misconsider, chaplains spawn with nullrod if roundstart one was already picked up.

**Comment by Helg2** [comment]
> yes but all chaplains after that come with their own anti magic weapon

I mean cult still has 30-35 damage and 50 block and reinforced bolas, so anti-magic won't quite help.

**Comment by jughu** [comment]
then the issue doesn't lie at the stun hand but the coinflip blockchance swords + better then captains armor and if they built up a little blood they have full heals aswell

**Comment by jughu** [comment]
a buff would mage anti magic stop rbolas and that would already help alot

**Comment by ExcessiveUseOfCobblestone** [comment]
do we really need 30 seconds of silence if someone cant put you, a helpless individual, on a nearby rune within 8 seconds without chains?

**Comment by jughu** [comment]
meth+synapatizine+nicotine gets you out said stun instantly

**Comment by ExcessiveUseOfCobblestone** [comment]
> meth+synapatizine+nicotine gets you out said stun instantly

skill issue just kill them then.

**Comment by jughu** [comment]
more like local chemist makes a passive chemfactory for everyone and then they can skill issue the whole cult

**Comment by private-tristan** [comment]
> more like local chemist makes a passive chemfactory for everyone and then they can skill issue the whole cult

 a cult can easily just... emp/destroy chem APC or kill the chemist (bolas still work and cult can create cult bolas). not very different from botany creating holymelons.

**Comment by jughu** [comment]
cult wont destroy the factoriew because it benefits them just as hard the crew but its to get the point across how it coule potentionally ruin most converts theres a reason why most things tagged as adrenaks only regen stam

**Comment by Mothblocks** [comment]
It doesn't look like anyone is interested in merging this

**Pull request closed without merging**
