### PR TITLE
The AI or its dominated mech must be in the AI chamber to doomsday.

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Prevents the AI from activating the doomsday device if it has been moved out of the AI chamber or is dominating a mech that is not in the chamber. Doomsday is also halted if the AI subsequently leaves the chamber.

Included is the removal of a horrific piece of code that does nothing but spam text and add a needless delay to going delta

## Why It's Good For The Game

Doomsday is an optional round ender for malf AIs, and so should have some level of difficulty. Currently, the AI can hide its core or hijack a mech and hide that, then doomsday where nobody without a pinpointer will ever find it. Since many players are unaware that pinpointers are capable of tracking the AI, this means a near guaranteed victory unless one of the pinpointers is held by one of the limited group who know what to do with it.

This PR requires the AI to stand its ground in the core in order to doomsday, so as to force interesting gameplay that does not consist of the AI going AFK while most or all of the crew are unable to do anything about it. With this change, successfully using doomsday will require more skill, as you have to fortify and defend your core against the crew, who are more likely to participate in the attempt when they know their work breaking into the core is not going to be pointless.

## Changelog
:cl: Thunder12345
balance: The secret doomsday device your station AI does not possess can no longer function if the AI is not in the AI chamber.
tweak: There is no longer a delay before the doomsday countdown begins.
tweak: Doomsday device text no longer refers to itself and not the station nuke.
/:cl:

### CODE REVIEW

**Comment by KathyRyals** [comment]
The nerf is good but you should leave the text before it starts, I think it adds amazing flavour.
I was in the terry round that lead to this PR. For those that wants to know, a malf AI shunted into a gygax and started the doomsday from a really remote location (behind the testing site), which leads to them getting the doomsday off practically free of troubles.

**Comment by Nistishere** [comment]
> Since many players are unaware that pinpointers are capable of tracking the AI, this means a near guaranteed victory unless one of the pinpointers is held by one of the limited group who know what to do with it.

Sounds like people should consider securing those if there are suspicions of malf ai.

Personally I think it's a bad idea. AI core room is the least secure platform to do anything from. It's vulnerable, it's weak, and it takes 0 effort to remove a malf Ai that is in the core room. here are _some_ things that I've seen most malf AI's are powerless (or near powerless) to stop. Most of those are done from OUTSIDE the core room itself.

-Mechs
-Bluespace launchpad TTVs
-Hiero staff
-Thermite into bombing
-Singlecaps
-EMP spam
-Hulks just walking in

If you want to stop AIs from hiding somewhere, make crew pinpointers lock on to nukes and AI deltas, instead of landlocking the AI to the most vulnerable room in the game. It's not fun to be landlocked to the weakest spot on the station because ided pr.

Also keep the flavor text, it's fun to hackertime.

**Comment by wesoda25** [comment]
This is honestly just a problem with pin pointers being so rare. imo AIs are at more of a disadvantage outside of their core since they don’t get its protection.

**Comment by Thunder12345** [comment]
@Nistishere most of the things you've listed can also be mitigated by acting to prevent them before you get outed. Hijack traitors can be very similarly fucked over if the station gets a ton of high end goodies, the solution is to not let them the goodies. Doomsday is entirely optional, so if you want to do it then it's up to you as the player to preemptively remove threats against you.

**Comment by Nistishere** [comment]
@Thunder12345 Disagree. Most of the thigns can't be counterplayed as malf AI unless you really know what you're doing. The average malf doesn't tend to check all of those. Hell, most of those are unexpected, and half of them are literally "Build machine, put beaker, do thing." There is no counterplay to it unless your APM is off the roof and your ping is perfect, and even THEN, you can't really counterplay EMPs or Launchpads. People used to be able to EMP you from the station without any issue, now all they have to do is move a bit closer and spam EMPs. Hell, only mechs are really "late game" stuff. The rest of those are doable fairly early in the round.

Again, landlocking the doomsday is a bad idea. Consider reworking how all pinpointers work before chimping on AI by pointing to the weakest room on the station and saying "Sit here while I delete you".

**Comment by TheVekter** [comment]
Mechanically it's whatever, but that flavor text is fantastic and I have no idea why you'd want it gone.

**Comment by TheMidnightRose** [comment]
You say that some of that can be countered by a smart AI but barely? the basic EMP grenade punches through the core walls and shuts down any AI instantly due to it just barely hitting the edge of the AI Chamber APC.

**Comment by TheMidnightRose** [comment]
If you want to do something. Make an announcement two minutes into Delta of the blueprint location of the AI. Or a generally direction from the center of the station to the AI from Centcom.

**Comment by SkeletalElite** [comment]
Unnecessary, pin pointers lead to the AI when it activates doomsday.

**Comment by MrMelbert** [comment]
👎 just because you removed the awesome flavor

**Comment by ExcessiveUseOfCobblestone** [comment]
just have the pinpointer say something like "now tracking alternative target" so people go oooo wonder what that is and it turns out to be the AI, the ai going into the mech should replicate the ai shunting, at least with APCs they dont move and they certainly cant phase through walls or shoot missiles/lasers at you.

**Comment by trerri** [comment]
What if instead of nerfing everything to the ground you made it more accessible instead? I barely see this philosophy used on tgstation ever. My idea:

1. Make pinpointers printable from sec lathe of they aren't already fabricable.
2. Add a check if the AI is in the chamber and if it returns false make an automated stationwide announcement that the malfunctioning AI the kill signal was traced from cannot be located, but the crew can track it using a pinpointer.

Is this really so hard?

**Comment by wesoda25** [comment]
It’d be better if you could print pin pointers if the station is on delta alert, not whenever

**Comment by TerraGS** [comment]
I would suggest going the route of cult summoning and have the malf alert give the AI's location at the time it activates doomsday.
Another idea is changing doomsday activation from a timer to a charge based mechanic so that the AI has to be connected to a supply of power to hit the threshold. Wouldn't stop space hideouts but portable generators won't give the same supply as the station's power net which a wise crew could disrupt as a means of counter-play.

**Comment by ATH1909** [comment]
> What if instead of nerfing everything to the ground you made it more accessible instead? I barely see this philosophy used on tgstation ever. My idea:
> 
> 1. Make pinpointers printable from sec lathe if they aren't already fabricable.
> 2. Add a check if the AI is in the chamber and if it returns false make an automated stationwide announcement that the malfunctioning AI the kill signal was traced from cannot be located, but the crew can track it using a pinpointer.
> 
> Is this really so hard?

That first one was an idea for a PR that I was planning to do for a while, except I'd have let people print them from both seclathes AND autolathes. In general, I think this quote describes a much better solution.

**Comment by ATH1909** [comment]
> I would suggest going the route of cult summoning and have the malf alert give the AI's location at the time it activates doomsday.
> Another idea is changing doomsday activation from a timer to a charge based mechanic so that the AI has to be connected to a supply of power to hit the threshold. Wouldn't stop space hideouts but portable generators won't give the same supply as the station's power net which a wise crew could disrupt as a means of counter-play.

Generally, I don't hide my malf AIs in space; instead, I just wall them into a 1 tile space in maint along with the only two pinpointers on the station. Making the malf alert give the AI's location would run into the problem of AIs popping delta JUST before they teleport themselves, misleading the crew into thinking that they're still on their sat.

**Comment by zxaber** [comment]
The fluff text for doomsday is perhaps the best we have in the entire game and really shouldn't be removed.

Pinpointers already give you the location of the AI, and are generally held by the two most influential members of the crew. Getting rid of them is essential for a hide-n-doomsday, but also is usually rather difficult to do quietly.

**Comment by ATH1909** [comment]
^ I made an alternative PR.

**Comment by ATH1909** [comment]
> Pinpointers already give you the location of the AI, and are generally held by the two most influential members of the crew. Getting rid of them is essential for a hide-n-doomsday, but also is usually rather difficult to do quietly.

Nah, as someone who's done it quite a few times, it's actually surprisingly easy.

The HoS, if you even have one, often doesn't even bother to take the pinpointer from his locker, so you can just zip in and snatch it. The captain will sometimes also leave his pinpointer in his office, but even if he didn't do that, you can just find out who he gave his pinpointer to, have a hacked borg strap that pinpointer-holder to themselves, and then detonate the hacked borg to obliterate the pinpointer (and gib the pinpointer-holder).

**Comment by 81Denton** [comment]
removing the flavor text is cringe

**Comment by ExcessiveUseOfCobblestone** [comment]
if you want to add a nudge nudge to the existing pinpointers then ok, but i dont like either change.

if you cant coordinate with typically 2 high-profile individuals assuming the captain keeps his instead of gives it to another individual, then I think it is perfectly fine to make it more difficult for the crew.

**Pull request closed without merging**
