### PR TITLE
Adds a mass driver computer to the chapel instead of a button

### PR DESCRIPTION
**Pull request by Buggy123**
FEEDBACK ONLY

Exactly what it says in the title, puts a mass driver computer a-la the derelict's in the chapel.

For now this is feedback only because I can't figure out why copying-pasting one thing from the derelict suddenly causes the game to crash while starting, AND why my SORD pr absolutely refuses to stay out of this no matter how much I pull from master/origin, AND why the commits stay and aren't squashed anymore.

IGNORE THE COMMITS, FOR THEY ARE RESILIANT VERMIN I HAVE YET LEARNED TO EXTERMINATE

### CODE REVIEW

**Comment by hornygranny** [comment]
map merger

**Comment by neersighted** [comment]
Your SORD stuff is there because you commited to master, reset your branch.

**Comment by KorPhaeron** [comment]
Considering the mass driver computer on the derelict is completely non functional, please test this thoroughly

**Comment by neersighted** [comment]
How about you tgui it? ^^

**Comment by Bawhoppen** [comment]
im crying and i dont even know how to git very well

**Comment by Buggy123** [comment]
The mass driver computer on the derelict absolutely works, I literally used it on the main server yesterday, it's just bugged in that the outer door is unpowered so you have to crowbar it open. It should work fine on the main station.

As for resetting the branch - I did that, I pulled from the remote (this), then pushed to origin, and then redid the map edit on a new branch entirely,  and the sord changes were STILL there.

**Comment by neersighted** [comment]
Reset as in `git reset --hard upstream/master`, and then make your changes (or cherry-pick them from the reflog)... Ask @optimumtact to walk you through it.

**Comment by Buggy123** [comment]
Well that worked. I'll remake this later.

**Pull request closed without merging**
