### PR TITLE
Ore silo will put machines off its level on hold, instead of disconnecting

### LINKED ISSUE #69863: Nonstation ore silos that are mounted on shuttles lose connection to lathes when shuttle moves
Reporting client version: 514.1585

## Round ID:
[190361](https://scrubby.melonmesa.com/round/190361)

## Testmerges:
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:

1. shitcode
2. take ore silo
3. put on whiteship
4. use KC13 boards to make ancient lathes
5. link to whiteship silo
6. lathes are on whiteship, alongside silo
7. ship move
8. lathe disconnect
9. what

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

There's a problem where people would try to rebuild a whiteship and use an Ore Silo for it. However, it would automatically unlink everything when moving, because it's checking for z level as soon as it changes z level itself, before the Ore silo has 'moved' as well.

~~To fix this, I'm now only disconnecting ore silos when a shuttle moves. This mostly does the same as before, but technically you can sync an unwrenchable connected machine and bring it to space with you (without using a shuttle) to stay connected, but I don't see this as a problem, and my original point of the PR was to prevent Lavaland ORMs.~~

I decided against this, instead I've made it so machines that aren't on a valid level (either both on the same z level or both on the station level) will be considered 'on-hold', much like if the QM has set it to hold through the silo directly. This means that machines no longer disconnect from the Ore silo on moving, they just can't access the materials in it. This affects gameplay in 2 ways:

1. You no longer need to resync when you bring the machine back
2. It won't unsync itself every time you move station z-level with its silo (such as on a whiteship).

I also made disconnecting from an ore silo actually remove them from the ore silo's list of connected machines.

## Why It's Good For The Game

Closes https://github.com/tgstation/tgstation/issues/69863

## Changelog

:cl:
balance: Machines (such as ORM and Techfabs) will no longer unsync from Ore silos when it moves Z-level, instead it will prevent materials from being used, as if it was on hold.
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
Won't people just find a way to teleport the machine down to lavaland with a handheld teleporter or something?

**Comment by ZephyrTFA** [comment]
At this point, just make it to where machines can only connect to a silo that is on station levels if they are also on a station level. And machines not on a station level can connect to any silo also not in a station level

**Comment by zxaber** [comment]
Arguably, the ORM could keep its silo link always, and check if the silo is within range at deposit time. Then you'd only really need a `if(z = silo.z || (is_station_level(z) && is_station_level(silo.z)))`

**Comment by JohnFulpWillard** [comment]
> Won't people just find a way to teleport the machine down to lavaland with a handheld teleporter or something?

That's true, maybe we should check for teleporting too

> At this point, just make it to where machines can only connect to a silo that is on station levels if they are also on a station level. And machines not on a station level can connect to any silo also not in a station level

Flying ship to and from the station z level would still break it in this case

> Arguably, the ORM could keep its silo link always, and check if the silo is within range at deposit time.

I'd like this but it sounds confusing to players to see their ORM remain synced when bringing it down, then disconnecting randomly when trying to put mats in.

**Comment by JohnFulpWillard** [comment]
Zxaber mentioned this on discord and wanted to bring it up

> You could have the ORM say/bubble a "cannot connect to silo" error if someone passes an ore in front of it while the Z levels are different. That should be enough hint of why it's not working.

I like the idea of giving a warning, and thought of something that would perhaps be better for all sides.
I think it would be best if we allowed materials to be deposited while on another z-level, but was unable to take points out of it, with a warning message on why it would be the case.

This is a video demonstration
https://cdn.discordapp.com/attachments/326831214667235328/1101032745590857738/2023-04-27_02-26-51.mp4

**Pull request merged**
