### PR TITLE
Bandanas can be adjusted with alt-click.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/tgstation/issues/25078.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
doesn't it become a hat if you use it inhand though

**Comment by ExcessiveUseOfCobblestone** [comment]
I read that as bananas

**Comment by bgobandit** [comment]
using a bandana inhand should just adjust mask

**Comment by ExcessiveUseOfCobblestone** [comment]
> doesn't it become a hat if you use it inhand though

yes

**Comment by ShadowDeath6** [comment]
If it turns into a hat when you alt+ click it what happens if you alt+click it while it's on mask or something?

**Comment by dannno** [comment]
I originally had this I'm pretty sure
if not the alt-clicking I had it be a mask no matter what state it was in but someone didn't like that and made me change it, idr who

**Comment by bgobandit** [comment]
ok but given that the proc is adjustmask where does it turn into a hat

**Comment by dannno** [comment]
really the reported "consistency" issue isn't actually valid because flipping caps and toggling bandanas aren't the same thing, bandanas change slot type when you toggle them

**Comment by ExcessiveUseOfCobblestone** [comment]
> ok but given that the proc is adjustmask where does it turn into a hat

adjustmask is the proc that turns it into a hat.

**Comment by ChangelingRain** [comment]
You can altclick it while it's on you, yes, and given that the times where it's not on you are:
- In your hands, where you can click normally to swap it
- Somewhere else, like in a bag or on a table, where it has to pass through somebody's hands to be placed on you

So as such I'm closing this and the issue, as it doesn't really do anything but cause a bug.

**Pull request closed without merging**
