### PR TITLE
Cryo tubes alert of dying patients

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Medstaff will be alerted when the cryo tube is damaging someone instead of healing
## Why It's Good For The Game
Cryo tubes can be really dangerous, especially with the cryoxadone nerf. This aims to help make it at least slightly less deadly when the intern is tasked to set up tubes and makes a hyperefficient death machine instead.
## Changelog
:cl:
qol: cryotubes alert of dying patients
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
makes sabotaging them less useful

**Comment by thgvr** [comment]
Cryo tubes damage you with just cryoxadone in them, locking you in the tube for all eternity because you have 1-2 burn damage. I don't think this is a good solution, I think the effects of cryoxadone should be bumped up or cryo shouldn't be so cold. I think it may have to do with n2o holding heat better, who knows.

**Comment by etherware-novice** [comment]
> Death by cryo tube by accident or by sabotaging chemicals is fun, please don't.

it does nothing to prevent your death, just alerts medstaff theres a corpse in their tube. if nobody happens to be in medbay youre still 100% dead

**Comment by Valorium-RB** [comment]
> > Death by cryo tube by accident or by sabotaging chemicals is fun, please don't.
> 
> it does nothing to prevent your death, just alerts medstaff theres a corpse in their tube. if nobody happens to be in medbay youre still 100% dead

How often is literally no one in medbay? Cryo is usually only used when medbay is overwhelmed and needs some passive healing (with the remaining usage being to treat cellular, etc.) Even if somehow you are the only medbay staff member, cryo is visible to the main hallway on some maps, making it even easier for people to notice some fuckery afoot.

**Comment by SethLafuente** [comment]
> makes sabotaging them less useful

Cryo tubes are for god damn healing they aren't made for the purpose of sabotage dying to a cryo tube and staying there for the entire shift is something that happens regularly I sure love always taking the risk of being permanently removed from the round when I ask a medic to put me in a cryo machine to remove my wounds for them to leave me there 

Ridiculous comment

**Comment by SethLafuente** [comment]
> > > Death by cryo tube by accident or by sabotaging chemicals is fun, please don't.
> 
> > 
> 
> > it does nothing to prevent your death, just alerts medstaff theres a corpse in their tube. if nobody happens to be in medbay youre still 100% dead
> 
> 
> 
> How often is literally no one in medbay? Cryo is usually only used when medbay is overwhelmed and needs some passive healing (with the remaining usage being to treat cellular, etc.) Even if somehow you are the only medbay staff member, cryo is visible to the main hallway on some maps, making it even easier for people to notice some fuckery afoot.

Im tragically a medic main you have no idea of the general incompetence of the medical staff they could see a pile of 10 corpses standing on the corner while they try to force heal someone at 95% health until it escalates into them dying 


Medics leaving death people in cryo because they don't know they are death or they just aren't paying enough attention is a regular thing and it seems like a design flaw to not give off an alert or throw the patient when they are death

**Comment by etherware-novice** [comment]
i can confirm ive died so many times in cryo

**Comment by msgerbs** [comment]
I'm conflicted. On one hand, I just avoid cryo altogether because I've been left to die in it so many times. On the other hand, I kind of like cryo not being very good because frankly cryo is boring as hell and I've never really understand how it managed to survive all the other med changes intact. It sucks having people come into medbay and just demand to be put in cryo instead of letting you do literally anything else to them. That being said, I don't like cryo existing as a noob trap silent death machine so I guess this is a good change.

**Comment by Overuseddart** [comment]
The medstaff will still somehow not see it, some of those docs are blind to anything not on a stasis bed

**Comment by etherware-novice** [comment]
its a radio message, similar to the ejection and tending injuries messages

**Comment by Valorium-RB** [comment]
> its a radio message, similar to the ejection and tending injuries messages

Honestly, that's just as bad, because now the need to even walk a few tiles to check on the cryo pods or even be vaguely in the same department is automated out.

**Comment by Overuseddart** [comment]
Mandatory Hugbox comment

**Comment by MrDoomBringer** [comment]
Just give cyrotubes a USB port so people can make their own cyro alert ICs if they want

**Comment by Mothblocks** [comment]
dumb, no

**Pull request closed without merging**
