### PR TITLE
fixes attempt two

### LINKED ISSUE #13536: beer-goggles, armor, and beanbags don't spawn in the bar backroom
Quite a problem for late-joining bartenders being without everything they need but their gun (which probably got stolen by the clown by that point)

### LINKED ISSUE #13897: Cable pieces outside box
Two cable pieces out in space south of arrivals.

Boxstation

### PR DESCRIPTION
**Pull request by Bawhoppen**
fixes #13897 (I think thats what he meant) 
there were cable coils in space on box but I don't even know what he meant

fixes #13536 
bartender has beanbag slugs in a box now in his backpack, and his locker has an armor, spare shells, and beer goggles.

goof did i make you proud

:cl: 
add: Nanotrasen bartenders now come standard with extra ammo stored in a box, as well as a bandolier in their locker.
/:cl:

### CODE REVIEW

**Comment by Aranclanos** [comment]
explain what do you do in your prs, its the most basic info that we ask

**Comment by Bawhoppen** [comment]
what

**Comment by Aranclanos** [comment]
that beside of saying 'fixes ###' say briefly what the bug was, makes your pr faster to understand/read and it helps when you have to go through 25 other prs.
Just explain what you did

**Comment by Bawhoppen** [comment]
I mean it was pretty small thing so it probbaly didn't matter much

**Comment by Aranclanos** [comment]
just do it senpai

**Comment by Bawhoppen** [comment]
theres always a next time but this one was just fixing the bartender's latejoin gear and shit

**Comment by duncathan** [comment]
Just edit op pls and be more descriptive with your ops in the future

**Comment by Bawhoppen** [comment]
fine. I edited it

**Comment by duncathan** [comment]
Thanks bb

**Comment by Bawhoppen** [comment]
just close https://github.com/tgstation/-tg-station/issues/13897 theres not even anything there

**Comment by Bawhoppen** [comment]
I'm going to remove that from mine

**Comment by Bawhoppen** [comment]
ok you know what that probably works its OKAY!

**Comment by tkdrg** [comment]
Why did you replace the beanbags with rubbershot

**Comment by Bawhoppen** [comment]
thats what it is? its just in a box now

**Comment by Bawhoppen** [comment]
ok I thought they were the same thing but I guess not
He now has a box of 6 beanbag slugs instead, and a bandolier in his locker cause bandoliers are cool

**Pull request merged**
