### PR TITLE
Fixes being able to "stomp out" sigils with telekinesis

### LINKED ISSUE #29733: Telekinesis can be used to stomp out clockwork sigils from a distance
Round #74302, clicking a sigil from a distance with telekinesis active will let you 'stomp' the sigil and remove it.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #29733
You can still hit them with something, but just clicking won't work.

### CODE REVIEW

**Comment by DoctoreMad** [comment]
You know I legitimately don't know why that wouldn't work, you can project psychic force, what do you mean you can use your force on objects but can't use your force on whatever composes the sigils

I realized halfway that its probably a balance issue but I'll ask it anyways

**Comment by optimumtact** [comment]
yeah this doesn't seem like a fix at all, why would these not be attackable by a tele-kinetic force

**Comment by ChangelingRain** [comment]
It's not strong enough to destroy them without some object.

**Comment by Iamgoofball** [comment]
@optimumtact 
TK is supposed to just be ranged hands

**Comment by DoctoreMad** [comment]
You can stamp out Rat-Var sigils with your bare hands but not your ranged hands then?

**Comment by lzimann** [comment]
If you can hit and stomp with bare hands then this is a balance change, otherwise this is a fix.

**Comment by ChangelingRain** [comment]
It doesn't show a message near the sigil, so it's a bug. This is the fix.

**Comment by DoctoreMad** [comment]
I am half tempted to argue that's a horribly wrong way of fixing it, half tempted to break open the smug anime girl folder.

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
It's easy enough to hit them with something in TK

**Pull request merged**
