### PR TITLE
Shuttle Engine Sprites

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/d3athrow/vgstation13/pull/13550

adds /vg/'s version of Eris' shuttle engine sprites
tgengine

:cl:
add: Shuttle engines have new sprites.
/:cl:

### CODE REVIEW

**Comment by Haevacht** [comment]
Okay but are the east and west actually correct because we have an issue with that in ours. If you've fixed that it's gonna need map editing to apply properly.

**Comment by uraniummeltdown** [comment]
Yeah they're correct, I'll try to fix the dirs on the maps

**Comment by WJohn** [comment]
This will fix #23821 once the map changes have been made. You only need to change the engines which already start east/west, north/south do not need tweaking.

**Comment by uraniummeltdown** [comment]
I can't seem to mapmerge correctly, so I'll just flip east/west and let someone else swap the dirs in another PR

**Comment by uraniummeltdown** [comment]
DNM until the mapmerger problem is fixed so I can fix the dirs

**Comment by anconfuzedrock** [comment]
I like the sprites but it looks a little weird with the top bit of the engine.

**Comment by Thunder12345** [comment]
The rest of the engine parts need to match it

**Comment by WJohn** [comment]
Those can be done in the future, or perhaps these sprites can be turned into 3/4th perspective as well. All this can be done later.

**Comment by uraniummeltdown** [comment]
Here are Eris' shuttle heater sprites in case anyone wants to improve these 
[heata.zip](https://github.com/tgstation/tgstation/files/785170/heata.zip)

**Comment by uraniummeltdown** [comment]
ok we can fix the engine dirs later

**Pull request merged**
