### PR TITLE
Apply jetpack nerf to implantable thrusters

### LINKED ISSUE #85165: "Implantable thrusters set" moves at pre jetpack nerf speed
Reporting client version: 515.1641

## Issue Summary
Revival of https://github.com/tgstation/tgstation/issues/85148 @Jacquerel 

image

https://github.com/user-attachments/assets/1c55aa4b-6a2c-4a05-8e80-82480e04ff68

## Round ID:
Reproduced locally on latest /TG/station master

## Reproduction:
Equip an "Implantable thrusters set" and use it in space

### PR DESCRIPTION
**Pull request by Jewelry-x**
## About The Pull Request

Fixes https://github.com/tgstation/tgstation/issues/85165.
## Changelog
:cl:
fix: jetpack nerf is now applied to implantable thrusters
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
This was already fixed someone just forgot to link/close the issue

**Comment by carlarctg** [comment]
Also what is this 'fix'? If the movespeed mod is unused remove the definition

**Comment by SmArtKar** [comment]
iirc this was confirmed to be intentional by jimmyl, so its a balance change - not a fix

**Comment by Jewelry-x** [comment]
> iirc this was confirmed to be intentional by jimmyl, so its a balance change - not a fix

In the issue have linked the PR to, it is mentioned as an oversight, because whoever did it said they just forgot that the implantable thrusters exist. This PR is intended as a fix rather than a balance change. If it is the latter, I will close the PR.

**Comment by Sadboysuss** [comment]
> iirc this was confirmed to be intentional by jimmyl, so its a balance change - not a fix

It's not intentional:
Screenshot_20240923_010726_Chrome

@mc-oofert

**Comment by mc-oofert** [comment]
> > iirc this was confirmed to be intentional by jimmyl, so its a balance change - not a fix
> 
> It's not intentional:
> Screenshot_20240923_010726_Chrome
> 
> @mc-oofert 

that literally says I forgot ( => oversight/something not considered)

**Comment by Dawnseer** [comment]
I will miss zooming about at high speeds with my (almost) exclusive jetpack during no grav

**Comment by Sadboysuss** [comment]
The issue has been fixed by a different pr now

**Comment by Jewelry-x** [comment]
> The issue has been fixed by a different pr now

Which one? Because when I tested it the speed was unchanged. If you post the link I will just close the PR.

**Pull request closed without merging**
