### PR TITLE
Fixes runtime when mineral scanning

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
Fixes this

Screenshot (384)

## Changelog
:cl:
fix: fixes runtime when mineral scanning, passes right argument for scanner in golem eyes
/:cl:

### CODE REVIEW

**Review by ArcaneMusic — APPROVED** [review]

**Comment by Ghommie** [comment]
What the peter... that line resetting transform matrix of the scanner has no reason to exist to begin with. Moreover: https://github.com/tgstation/tgstation/blob/1defdd960a9951ad749263e181b5771773ac97da/code/modules/surgery/organs/internal/eyes/_eyes.dm#L285-L287. The proc is called here too, but the scanner arg is the action datum itself rather than the user.

**Comment by SyncIt21** [comment]
Fair enough. I'll remove the scanner arg and all usages entirely from this proc.

Drafting for now

**Comment by SyncIt21** [comment]
So i can't remove the scanner arg because the proc uses it to compute distance from the scanner to the nearest vent/ore. We also need it to reset the matrix so that it can repeat the shaking animation.

I'll just fix the scanner arg being the datum

**Review by Ghommie — CHANGES_REQUESTED** [review]
The spasm animation was fixed by #80793. That line I mentioned has to go.

**Comment by SyncIt21** [comment]
Done

**Pull request merged**
