### PR TITLE
Revamps Metastation's Xenobiology department

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

It's about damn time I did this.

StrongDMM_KwRG7aFCad

Metastation's Xenobio department has always had two major flaws - it needs more pens and the location for the kill room _sucks_. So I remedied this. Replacing the R-walls between pens buys us enough room for 2 more, one of which is used up by the new kill room. So we're at 7 pens and a significantly less painful cold room. Had to shrink the containment pen by one, but not a big deal.

The old cold room has been converted to a small maint room off cameras that can be used for ~~hiding your dead bodies or cult runes~~ getting away from the department for a bit.

## Why It's Good For The Game

Usability upgrades as well as bringing it in line with what we have on Box. Looking towards making this design the standard on other stations as well.

## Changelog
:cl:
add: The Xenobiology department on Metastation has been revamped with a better cold room and an extra slime pen.
/:cl:

### CODE REVIEW

**Comment by LordSaladin** [comment]
containment pen should have one rng mob when it's not a xeno egg round

**Comment by EdgeLordExe** [comment]
image

**Comment by TheVekter** [comment]
Yeah okay that could be a problem. Fixing it.

**Comment by EdgeLordExe** [comment]
also i think like having double reinforced glass windows would look better, and it would be potentially safer.

**Comment by TheVekter** [comment]
image
Better, I think.

**Comment by Twaticus** [comment]
hell yeah looks awesome.
just 1 floating camera tho :eyes: 
chrome_nka5F9N6Nu

**Comment by TheVekter** [comment]
Fixed, nice catch.

**Comment by RaveRadbury** [comment]
Changing to a visually open floorplan like this feels kind of weird. Is this easier for slimes to break out of? The maint loop feels pretty without purpose now that the freezer is gone.

**Comment by TheVekter** [comment]
Not really, unless they're sentient. NPC slimes don't attack windows or actively try to break out, though I'm not 100% sure what they'll do if they're pissed. And yeah, the maint loop isn't necessary, but I don't want to take xenobiology away as a 'cool place to hide sketchy activities' on meta.

**Comment by RaveRadbury** [comment]
> Not really, unless they're sentient. NPC slimes don't attack windows or actively try to break out, though I'm not 100% sure what they'll do if they're pissed. 

They weren't able to destroy structures until sometime last year. They'll break out if they get hungry, I've seen it happen.

I'm going to miss the claustrophobic feeling the current layout has, with the cells being more separate and your RD walking the full length of the hallway to make sure you're not up to something.

**Comment by ExcessiveUseOfCobblestone** [comment]
Is the plasma icon in the maint room below a helper or is it actual plasma? If it's the latter remove it please, seems very cheeky to add a dedicated (no one else can go to this maint but xenobio) plasma spawn for the department that just so happens to lock interactions behind plasma.

**Comment by TheVekter** [comment]
Laaaaame. I'll replace it with something else when I get home.

**Comment by WarlockD** [comment]
Yea I have seen it before, the slimes breaking out of box or even meta.  Basically you put a monkey in the middle, and once they get hungry, they will hit a window.  Boof.  A few seconds tick by, boof.  It takes a good 10 min on a single pain of reinforced glass though, so they won't break out if someone is watching them.

**Comment by TheVekter** [comment]
Appveyor failed because of Github bullshit, not my build.

**Pull request merged**
