### PR TITLE
CentCom Uniforms Redesign

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About The Pull Request

For 3 years, CentCom uniforms have been sitting gathering dust. Well, here I am to fix this issue. I soften the textures, and shading a bit with a more comfortable-coloring. Keeping the classic colors, but changing the shading technique. Adds several new items, along with additions to existing job outfits. Keeping that luxurious look.

This **mainly** just softens the colors, changing them slightly, by changing the silver buckles, changing the green saturation, as well as mainly changing the gold colors entirely. Just makes them feel more pretty to look at.

Credit for the turtlenecks is to Halcyon.
The others are assets from this codebase.

## Why It's Good For The Game

It'd be good for the game considering CentCom's normal uniforms look old, with an untextured gold trimming, and a odd looking green color. This fixes them, and also adds some missing drip for CentCom Officials.

## Changelog

:cl:
add: CentCom Official Turtleneck, CentCom Commander Tactical Turtleneck, CentCom Head Intern Uniform, CentCom Replicas, CentCom Carapace, CentCom Gloves.
fix: Fixed descriptions of CentCom clothing.
image: Changes sprites of all CentCom clothing, and adds sprites for new clothing.
spellcheck: Fixed lack of descriptions.
code: Changed code of most CentCom clothes. As well as sort them better.
/:cl:

image
image

Captain Carapace, Gloves and Sabre [CentCom Variants]
image

CentCom Official Turtleneck [Inspectors or Civil Personnel]
image

CentCom Head Intern Uniform [Polo Shirt with Pants instead of Shorts]
image

CentCom Replica [Identifiable with lack of belt, and fake, lighter colored pants]
image

CentCom Commander Turtleneck [Silver Insignia along the turtleneck]
image

### CODE REVIEW

**Comment by optimumtact** [comment]
```
> overhaul
> look inside
> just a resprite
```

**Comment by ChromeFoxxity** [comment]
> ```
> > overhaul
> > look inside
> > just a resprite
> ```

Well, it's not as much of a overhaul, as it is just.. Rework.

**Comment by ChromeFoxxity** [comment]
> ```
> > overhaul
> > look inside
> > just a resprite
> ```

If I want to "OVERHAUL" it I would use some sprites around here and there.

**Comment by LSommers** [comment]
Not a fan of the saddlebag pants on the turtleneck, nor whatever's going on with the little indent in the chest and back.
Everything else looks good though!

**Comment by san7890** [comment]
i like the gold instead of the yellow

**Comment by ChromeFoxxity** [comment]
> Not a fan of the saddlebag pants on the turtleneck, nor whatever's going on with the little indent in the chest and back. Everything else looks good though!

The pants are just the syndicate combat uniform pants.

**Comment by OrionTheFox** [comment]
🙏 appreciate the credit, but I cannot accept it. I just recolored turtleneck sprites made by Halcyon. The sprite credit should go to him.
I love the colors picked for this though, it looks really nice with the darker gold and the green blends very well

**Comment by ChromeFoxxity** [comment]
> 🙏 appreciate the turtleneck credit, but I cannot accept it. I just recolored turtleneck sprites made by Halcyon. The sprite credit should go to him. I love the colors picked for this though, it looks really nice with the darker gold and the green blends very well

Oh, sorry. Thank you for reminding me.

**Review by Wallemations — CHANGES_REQUESTED** [review]
I'll be honest that I prefer the old turtleneck

**Comment by ChromeFoxxity** [comment]
> I'll be honest that I prefer the old turtleneck

It was extremely flat, and had some pretty poor shading. These ones are more utilized to not look like you're wearing a striped shirt.

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
Dawg did you just take my sprite I made on shiptest, which in turn was made by @Ebin-Halcyon, lazily recolor it, and try to pass it as your own on /tg/? I don't know what the hell you're smoking thinking I'd allow this to get merged here when I can do something about it.

Blocking this until you can make an original design.

image-1
image-2


Not to mention you're the exact same dude from a Voidcrew downstream who has the notorious habit of stealing sprites from Shiptest, recoloring, pretending it's your own, and not crediting the original artists you take it from until called out on it. What the fuck dude.

**Comment by Admiral-Gigaton** [comment]
Yeah I was gunna say I liked the pocketsand belt, but the line in the middle made it look like a dad bod, but now that it turns out you plagerised! Go fuck yourself, not cool man.

**Comment by Loafin34** [comment]
i like old one more. also you stopped putting in the before and after and i dont like how head intern actually looks intimidating.. they should be puny

**Comment by ChromeFoxxity** [comment]
> Dawg did you just take my sprite I made on shiptest, which in turn was made by @Ebin-Halcyon, lazily recolor it, and try to pass it as your own on /tg/? I don't know what the hell you're smoking thinking I'd allow this to get merged here when I can do something about it.
> 
> Blocking this until you can make an original design.
> 
> image-1 image-2
> 
> Not to mention you're the exact same dude from a Voidcrew downstream who has the notorious habit of stealing sprites from Shiptest, recoloring, pretending it's your own, and not crediting the original artists you take it from until called out on it. What the fuck dude.

Actually. No. I Recolored the turtleneck with my own colors, it has a softer green, and a better gold color. I credited the owner of the turtlenecks, and added the combat pants. I may have also copied a Blueshield's turtleneck design with the silver designs on it. There's not really much you can do with a turtleneck. I did NOT pass it as my own.

**Comment by ChromeFoxxity** [comment]
> Yeah I was gunna say I liked the pocketsand belt, but the line in the middle made it look like a dad bod, but now that it turns out you plagerised! Go fuck yourself, not cool man.

I credited the owner of the turtleneck, it wasn't plagiarism.

**Comment by ChromeFoxxity** [comment]
> Dawg did you just take my sprite I made on shiptest, which in turn was made by @Ebin-Halcyon, lazily recolor it, and try to pass it as your own on /tg/? I don't know what the hell you're smoking thinking I'd allow this to get merged here when I can do something about it.
> 
> Blocking this until you can make an original design.
> 
> image-1 image-2
> 
> Not to mention you're the exact same dude from a Voidcrew downstream who has the notorious habit of stealing sprites from Shiptest, recoloring, pretending it's your own, and not crediting the original artists you take it from until called out on it. What the fuck dude.

If you're gonna claim plagiarism, make sure I didn't fucking credit the owner of the turtlenecks next time. Because I FUCKING DID.

image

**Comment by ChromeFoxxity** [comment]
Not like I can fucking change the color of the pants when it's already CentCom's colors for their pants bruv.

**Comment by ChromeFoxxity** [comment]
The voidcrew incident is when I didn't know how to work Github, I couldn't figure out who those turtlenecks were.

**Comment by xXPawnStarrXx** [comment]
>"Credit for the turtlenecks is to Halcyon."

> Yeah I was gunna say I liked the pocketsand belt, but the line in the middle made it look like a dad bod, but now that it turns out you plagerised! Go fuck yourself, not cool man.

You're the one who's very clearly not being cool here. They've clearly explained that the sprites are someone else's, they like their work and want more people to experience it. They've passed over all credit, that was just uncalled for.

**Comment by ChromeFoxxity** [comment]
> > "Credit for the turtlenecks is to Halcyon."
> 
> > Yeah I was gunna say I liked the pocketsand belt, but the line in the middle made it look like a dad bod, but now that it turns out you plagerised! Go fuck yourself, not cool man.
> 
> You're the one who's very clearly not being cool here. They've clearly explained that the sprites are someone else's, they like their work and want more people to experience it. They've passed over all credit, that was just uncalled for.

I thank you for being reasonable. I should have made the credit more obvious.

**Comment by norsvenska** [comment]
i love the colour palette used here, the colours all mesh together really well.
i'm confused about the shading on the turtleneck, though. it looked like a turtleneck already, and i'm not quite sure how putting a line in the middle makes it look more like one.

**Comment by ChromeFoxxity** [comment]
> i love the colour palette used here, the colours all mesh together really well. i'm confused about the shading on the turtleneck, though. it looked like a turtleneck already, and i'm not quite sure how putting a line in the middle makes it look more like one.

That's fair. I could probably remove it. I'm not exactly too sure.

**Comment by optimumtact** [comment]
> Do you expect me to dig every time into something, and expected to know literally everyone's sprites

yes that is the expectation when you're adding sprites here, that you know where they came from and their license

**Comment by ChromeFoxxity** [comment]
> > Do you expect me to dig every time into something, and expected to know literally everyone's sprites
> 
> yes that is the expectation when you're adding sprites here, that you know where they came from and their license

Well, it's what I already did. I credited them far before this was even a problem.

**Review by Twaticus — CHANGES_REQUESTED** [review]
dont need all these extra outfits/accessories

**Comment by ChromeFoxxity** [comment]
> dont need all these extra outfits/accessories

You might not think so, but this is really just for downstreams, or just for design purposes.

**Comment by Twaticus** [comment]
> You might not think so, but this is really just for downstreams

**Pull request closed without merging**
