### PR TITLE
Finishes something I should of done a long time ago.

### PR DESCRIPTION
**Pull request by KazeEspada**
Makes dead mice edible. That way you monsters can kill mice to survive when your starving to death slowly in maint.

### CODE REVIEW

**Comment by calzilla1** [comment]
make it have a 1/100 chance of giving you a disease

**Comment by JJRcop** [comment]
mmmmmap files!

**Comment by PKPenguin321** [comment]
i am also certain this will break some chef recipes

**Comment by KazeEspada** [comment]
I wrote this in less then 5 minutes because I was bored at work. Sue me.

**Comment by KazeEspada** [comment]
Who put dead mice on maps? Why not just a living mouse?

**Comment by Supermichael777** [comment]
code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm:251:error: /obj/item/trash/deadmouse: undefined type path

code/game/objects/items/weapons/storage/bags.dm:382:error: /obj/item/trash/deadmouse: undefined type path

code/game/objects/effects/spawners/lootdrop.dm:47:error: /obj/item/trash/deadmouse: undefined type path

File:line:error:errortype

**Comment by ExcessiveUseOfCobblestone** [comment]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> a dead mouse is part of some lootdrop

**Comment by Supermichael777** [comment]
the loot for Mice yes.

**Comment by optimumtact** [comment]
fix
ur
shit

**Comment by anconfuzedrock** [comment]
make it possible to starve to death

**Pull request closed without merging**
