### PR TITLE
Improved and safer check for localhost admin

### PR DESCRIPTION
**Pull request by optimumtact**
My paranoia makes me worry that byond can be tricked into setting a
null address

### CODE REVIEW

**Comment by optimumtact** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/admin/IsBanned.dm#L4

thanks to @Jordie0608

**Comment by MrStonedOne** [comment]
actually, i'm the one that added that, because you can trick byond into setting a null address

**Comment by optimumtact** [comment]
my creeping sense of paranoia grows

**Comment by JJRcop** [comment]
I believe that this will disable DreamSeeker hosted .dmbs, as they have a null address in tests. But if you can really trick BYOND into nulling out the address, it's proabaly nessecary.

**Comment by Bawhoppen** [comment]
paranoia~~~ :ghost: :worried: :fearful: :ghost: :worried: :fearful: :ghost: :worried: :fearful: :ghost: :worried: :fearful:

**Comment by Jordie0608** [comment]
I'm paranoid about why this keeps getting opened and closed.

**Comment by optimumtact** [comment]
Because noone will merge it

**Comment by FlavoredCactus** [comment]
Your paranoia got the best of you cause now this doesn't work.

When i join my own game via DMB my client.address is null.

**Comment by MrStonedOne** [comment]
You should not be testing via that method anyways, there are differences in
lag and performance and certain byond bugs have only shown up in one vs the
other.

I fully support the movement away from ds hosted games.

**Comment by optimumtact** [comment]
Well the perfect solution would be a config that defaults to on but can be disabled by server administrators, but this wasn't my feature

**Comment by JJRcop** [comment]
I think a config would make this too complex. If DreamSeeker hosted single-user testing is not going to be supported, then I'm fine with that. I just want this to be a pretty much default guaranteed thing hard coded into SS13, that the localhost gets admin no questions asked. It's not all that difficult to just add dream daemon into the testing pipeline. When you're devving, have DD open and ready to host when compiling finishes. No biggie.

If there was a 100% accurate way to figure out "this is being hosted with DreamSeeker", then I would use that instead. But I don't trust world.address, world.port, etc. Seems like it's possible to get either of those to be null even when using DreamDaemon.

**Comment by Jordie0608** [comment]
@optimumtact the current autoadmin config? Or do you mean something different here?

**Pull request merged**
