### PR TITLE
Big Batch of PotPourri Updates for Delta

### PR DESCRIPTION
**Pull request by Okand37**
Fixed a number of bugs, issues, and oversights related but not limited to:
Cargo access doors
Cargo conveyor belts
Putting appropriate access windoors on desks
Adding power to the SM scrubber air injectors
Virology air system connected to its air tank and connector port
Virology air injector powered

### CODE REVIEW

**Comment by Kromgar** [comment]
Adding power to the air injectors? Fuck you dont even need em the supermatter can run perfectly fine without any sort of coolant system. Only if peopl

**Comment by Mervill** [comment]
If your not already aware, I removed the golden statue of the HoS from the vault to add the credit machine

**Comment by jughu** [comment]
What does a gold hos statue in vault if nobody can see it doesnt that defeat the point of a statur?

**Comment by Mindustry** [comment]
Delta is not Pubby, lmao

**Comment by KingPhilipIII** [comment]
You need to construct additional AI pads.

**Comment by ExcessiveUseOfCobblestone** [comment]
There's no axe in atmos

**Comment by Okand37** [comment]
Around what areas does the AI need additional pylo- I mean, holopads?
I'll add a fireaxe to atmos, thought I did already, woops!

**Comment by KingPhilipIII** [comment]
Nevermind. Upon further inspection I realize I'm just an idiot. I had the poor luck to be trapped in a room without a holopad and no radio so I assumed upon realization I was locked in the most boring room on the map that it had the same issue pubby did when the same thing happened. 

There isn't a need for more pads, just for me to not run through successive open doors and promptly get locked in.

**Comment by Okand37** [comment]
Oh alright, if it was a non-maintenance room it should've had an intercom in it, do you know what room it was?

**Comment by Militaires** [comment]
have some suggestions

- a dank fucking shithole-looking secret area in maint for the stoners in us
- if you have an SM engine have it use two corgis breeding and plastic flaps to filter the baby corgis out and use them as supermatter stimuli instead of just an emitter it'll be hilarious
- meme rooms in maint, including and not limited to citrus room, chess room, and such.
- more dirt in maint

delta is sweet as fuck but sometimes it feels *too sweet and sleek and perfect*
too perfect, TOO PERFECT.

**Pull request merged**
