### PR TITLE
Consolidates bot assemblies under one parent, fixes bot parts switching types when the bot is destroyed

### LINKED ISSUE #34156: Destroyed bots drop left arms and can only be built with right arms
the bots were originally built with right arms so what sort of magic turns it left?
intended or overlooked?

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #34156
Removed `/obj/item/toolbox_tiles_sensor` path since it was redundant with the `build_step` var under the new `/obj/item/bot_assembly/floorbot` type.
Also fixed the same issue for a number of other bot parts.
  
:cl: ShizCalev
fix: Constructed security/honk/ect bots will now drop the correct parts when destroyed.
/:cl:

### CODE REVIEW

**Comment by Razharas** [comment]
Do not forget to change the crafting recipe for them

**Comment by ShizCalev** [comment]
Crafting recipes don't have to be changed since they don't do anything with assemblies.

**Comment by ShizCalev** [comment]
This'll totally enable future PRs so you get special things when you say, build a medbot with a rad laser health analyzer. :)

**Comment by MrROBUST** [comment]
Do we really need this defines?
```
#define ASSEMBLY_FIRST_STEP 	0
#define ASSEMBLY_SECOND_STEP 	1
#define ASSEMBLY_THIRD_STEP     2
#define ASSEMBLY_FOURTH_STEP    3
#define ASSEMBLY_FIFTH_STEP     4
```
'step' var is self explanatory for me as just a number.

**Comment by YPOQ** [comment]
#12267

**Comment by ShizCalev** [comment]
Doesn't effect #11267 since that's an issue with table crafting

**Pull request merged**
