### PR TITLE
The Ark of the Clockwork Justicar will gradually convert objects near it

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: The Ark of the Clockwork Justicar will gradually convert objects near it with increasing range as it gets closer to activating.
/:cl:

Half a buff, half a nerf; it means it autoconverts doors and walls and such, but it also means its location is much more apparent, and it WILL convert rwalls, so rwall-secured areas become more vulnerable.

### CODE REVIEW

**Comment by Thunder12345** [comment]
WINTER'S ICY GRIP IS UNBREAKABLE

**Comment by ma44** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by coiax** [comment]
won't this convert people

**Comment by ChangelingRain** [comment]
no

**Pull request merged**
