### PR TITLE
Alcohol Bottle Resprite

### PR DESCRIPTION
**Pull request by JStheguy**
:cl: JStheguy
imageadd: Most alcohol bottles have been resprited, as well as a poster that used one of the current bottles as part of it's design.
/:cl:

I believe these new sprites should be somewhat of an improvement over the current ones.
image

### CODE REVIEW

**Comment by ChangelingRain** [comment]
How do these look when broken?

**Comment by JStheguy** [comment]
@ChangelingRain 
Like this
image

**Comment by WJohn** [comment]
Very nice!

**Comment by calzilla1** [comment]
IDK, they all look so... generic. The absinthe one can stay because the OG model is a bit shit

**Comment by WJohn** [comment]
Sprite changes are okay during the freeze. I don't think these look generic at all, more that they're artistically consistent, because they're all made by the same guy who also knows how to sprite much better than the host of people who made the original sprites.

**Comment by dannno** [comment]
it always annoyed me that some bottles looked like they were from a different thing entirely than others

**Comment by Niknakflak** [comment]
These old bottle sprites are nostalgic as fuck for me but the more I look at them, the more I realize how horrible they are.  I do wish the sprites were bigger though.  Bigger sprites just seem to fit to me

**Comment by Dorsisdwarf** [comment]
the ones from git's to.. cognac? look much worse than the originals, but the rest of these are great

**Comment by dannno** [comment]
I just noticed
the old sprites were just pictures of fucking actual bottles someone scaled down to 32x32 I think

what the fuck?

**Comment by JStheguy** [comment]
@dannno 
Hey, that's the quality work of our elders, don't you dare diss it!

**Comment by Tacolizard** [comment]
FINALLY SPACE BEER ACTUALLY LOOKS LIKE A BEVERAGE

**Comment by Tacolizard** [comment]
overall these sprites loose a lot of detail and, dare I say, 'character', but due to the more consistent and clear art style I must admit these are a lot better.

**Review by Cyberboss — APPROVED** [review]

**Comment by WJohn** [comment]
Tacolizard is right on how there's less detail going on with the pictures there, I think it'd be nice if you went and added a few extra touches. Notice how the whiskey and vodka have pictures and details on them? A lot more interesting to look at, even if badly done.

**Comment by pubby** [comment]
These look like condiment bottles and them being unbranded makes them look cheap. Also, the shapes of some bottles were lost in translation.

Pic related.

**Comment by JStheguy** [comment]
image
Redid some of the labels on some of the bottles

**Comment by calzilla1** [comment]
Can you make them doible the size of the beer bottles? Because beer bottles hold 50u and liquor bottles hold 100u

**Comment by WJohn** [comment]
Very nice! And calzilla that would require a total resprite of just about everything he's done here so that can wait for a future PR.

**Pull request merged**
