### PR TITLE
completely removes swarmers and related content from the game 

### PR DESCRIPTION
**Pull request by trerri**
## About The Pull Request

Self-explanatory

## Why It's Good For The Game

Antag that instead of being engaging or interesting, eats all of your QoL first, then upon attempting to fight it neuters you without a fight and/or runs away unscathed.

## Changelog
:cl:
del: Swarmers
/:cl:

### CODE REVIEW

**Comment by trerri** [comment]
pardon the abysmal commit hygiene i suck at git

**Comment by IndieanaJones** [comment]
I know the motto "Improve not remove" is something which has developed into more of a joke than anything, but I definitely want to argue it here.  Along with this, most of times we have removed antags is when they have devolved into a buggy mess and nobody is willing to make changes to them.  However, as #51558 shows, Swarmers are still in active interest and being maintained.  I say if you have a problem with the antagonist, you should go through the proper channels to discusses changes you'd like to see to the antagonist instead of outright removal.  I'd be more than willing to hear anyone out on the subject, but I am directly against outright removal of Swarmers.

**Comment by Daundra** [comment]
I would like to make the argument that xenos are so incredibly similar to swarmers (neurotoxin/disablers, both ventcrawl, both can and probably will break your ORM, infectious reproduction in different way, etc. etc. etc.) that if your reasoning for removing them is their sheer capability to ruin a round, that same argument would fall on more than just swarmers.

I guess what I'm trying to say is I am totally acknowledging the fact they pretty much 100% necessitate a shuttle call and are incredibly difficult to fight back against truly but I don't feel that is grounds enough to remove them, anyways. It would actually pain me to see more ghost roles get removed because while many people will absolutely disagree with me I think swarmers are interesting and fun and could be balanced and repurposed into something that'd fit the game vision rather than just axed.

**Comment by trerri** [comment]
tomorrow when i find out why travis is whining im gonna expand this to remove xenos too, they have the same problems + copyright + rape theming which makes me very uncomfortable

**Comment by spessbro** [comment]
> tomorrow when i find out why travis is whining im gonna expand this to remove xenos too, they have the same problems + copyright + rape theming which makes me very uncomfortable

remove stunbatons too, for the copyright thing obviously

**Comment by Daundra** [comment]
I guess we should remove wizard, blob, shadowling, and all the other antags that'd leave you and the station with more than a hello kitty bandaid

**Comment by trerri** [comment]
closed for acting like a fucking retard 👌

**Comment by Timberpoes** [comment]
image

**Pull request closed without merging**
