### PR TITLE
Adds Rice to the MegaSeed Servitor

### PR DESCRIPTION
**Pull request by SconesC**
It's been in the code, not sure why it was not in the machine

### CODE REVIEW

**Comment by Chocobro** [comment]
check mutation code, it should be a mutation of wheat.

**Comment by SconesC** [comment]
>check failed

i giv eup

**Comment by KorPhaeron** [comment]
You left out the first / in the object path for seeds you dork

**Comment by Miauw62** [comment]
>rice is a mutation crop

wot

**Comment by Thunder12345** [comment]
Doesn't even make sense, the other mutation crops tend to be a different variety of the same crop, or a shitty joke like eggplants and egg plants. Wheat and rice are only related by both being grains...

**Comment by SconesC** [comment]
Why is rice a mutation crop? It's only used in food with no special effects.

I don't see the harm in putting it in the vendor.

**Comment by Jordie0608** [comment]
If you're adding it to the vendor you should probably remove it as a mutation.

**Comment by phil235** [comment]
Yeah, removing it as a mutation would be better.

**Comment by Chocobro** [comment]
rice is a mutation crop since cheridan asked me to make mutations of every plant. pretty sure removing it as a mutation will mean wheat doesn't have one and i have to think up another plant.

i don't personally mind the removal as a mutation and just putting it in the seed vendor, but i'm entirely too disillusioned from doing two hydroponics expansions to be doing Just One Last Plant

**Comment by phil235** [comment]
Wheat can still mutate into oat.

**Comment by Chocobro** [comment]
in that case :+1:

**Comment by SconesC** [comment]
Sorry I was on a plane

ILL CHANG EIT

**Comment by Cheridan** [comment]
rice should mutate into condoleezza rice

**Comment by Cheridan** [comment]
@SconesC Are you still working on this? You haven't removed it from the mutation list yet, like you said.

**Comment by SconesC** [comment]
I SAY IM GOING TO DO THINGS BUT I NEVER REALLY MEAN IT

**Comment by Cheridan** [comment]
:V

**Comment by SconesC** [comment]
troled

**Pull request closed without merging**
