### PR TITLE
Captain's gun now shoots hellfire lasers

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
This PR changes the Captain's antique laser to fire hellfire lasers instead of normal ones, which for those who don't know, deal much more grievous burn wounds and slightly more damage (25 burn vs 20). Originally this PR let the Cap's gun switch between normal lasers at the normal energy cost and hellfires at 30% more energy cost, but coiax suggested just making it shoot hellfires only so here we are.

## Why It's Good For The Game
This gives the Cap's gun more personality and utility than just being a smaller advanced energy gun without disablers. Hellfire lasers and burn wounds work best against unarmored targets (like, say, a swarm of assistants breaking into your office), so this gives the wielder an extra edge against rowdy crewmembers who need to be brought back into line.

It also works out fluff-wise, since hellguns are supposed to be really old laser guns that were so gruesome that NT limited their power to avoid the bad PR that comes with selling war-crime guns, so an antique from before that change would still have them. Plus I think it's funny that the Captain gets a gun that specializes in maiming and disfiguring people.

## Changelog
:cl: Ryll/Shaps
balance: The Captain's antique laser now fires more powerful hellfire lasers rather than normal lasers
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
>This gives the Cap's gun more personality and utility than just being a smaller advanced energy gun without disablers

Uh, the self-recharge is *pretty* unique

**Comment by Ryll-Ryll** [comment]
> > This gives the Cap's gun more personality and utility than just being a smaller advanced energy gun without disablers
> 
> Uh, the self-recharge is _pretty_ unique

Except for the advanced energy gun, which I explicitly named in your quote, silly

**Comment by RaveRadbury** [comment]
> Except for the advanced energy gun, which I explicitly named in your quote, silly
image

**Comment by CRITAWAKETS** [comment]
> ## Changelog
> 🆑 Ryll/Shaps
> tweak: The Captain's antique laser can now switch between regular lasers and hellfire lasers
> /🆑

i swear to god if i see someone labelling another balance change as a tweak im going to PM everyone on discord who does this with just "twink"

**Comment by RaveRadbury** [comment]
> Except for the advanced energy gun, which I explicitly named in your quote, silly
image

**Comment by ATH1909** [comment]
> > ## Changelog
> > 🆑 Ryll/Shaps
> > tweak: The Captain's antique laser can now switch between regular lasers and hellfire lasers
> > /🆑
> 
> i swear to god if i see someone labelling another balance change as a tweak im going to PM everyone on discord who does this with just "twink"

you gotta think about the GBP, man

**Comment by bluetshirtguy** [comment]
looks cool but do we really want to power creep?

**Comment by Sparkezel** [comment]
YES

**Comment by joookschad** [comment]
> looks cool but do we really want to power creep?

yea

**Comment by Dorsisdwarf** [comment]
Im constitutionally against ever giving the capain a reason to crack open their display case outside of emergencies but the court of github opinion has long been against me so shrug

**Comment by Tlaltecuhtli** [comment]
can you make the hellfire laser icons different?

**Comment by necromanceranne** [comment]
I think it should shoot only hellfire, personally.

**Comment by coiax** [comment]
> 
> 
> I think it should shoot only hellfire, personally.

Why would you ever not have it in hellfire mode as a captain?

**Comment by D4C-420** [comment]
> Necromanceranne is right; why would you ever not have it in hellfire mode as a captain? Captains that break their display case are clearly rogue and evil types.

Everyone knows that in the Pokémon like Evolution path players take Captain is just the final form of assistant.

**Comment by necromanceranne** [comment]
> > I think it should shoot only hellfire, personally.
> 
> Necromanceranne is right; why would you ever not have it in hellfire mode as a captain? Captains that break their display case are clearly rogue and evil types.

Well I mean that and why would I bother using the inferior shot type. I'm not making arrests with a laser, I'm killing the bastard. Who cares if it wounds them as a result. They hopefully will cease living soon anyway.

**Comment by D4C-420** [comment]
> Well I mean that and why would I bother using the inferior shot type

Ammo. Oh sure it recharges but is that fast enough for the fight you are in? A bit if wiggle room with one's aim goes a long way to making sure the man lying dead on the floor is not the person who takes only 3 seconds to steal captains spare and not 2 minutes.

**Comment by TheBonded** [comment]
what if it had a once use pulse rifle mode that uses all ammo and breaks the gun on use? maybe it would explode in the user's hand, like how changing the det's revolver makes it shoot once and stun the user, except in the case of the cap's gun it would do a lot more damage

**Comment by Pumpkinoe** [comment]
> what if it had a once use pulse rifle mode that uses all ammo and breaks the gun on use? maybe it would explode in the user's hand, like how changing the det's revolver makes it shoot once and stun the user, except in the case of the cap's gun it would do a lot more damage

permanently breaking a high risk item that traitors are meant to steal? 😶

**Comment by Jared-Fogle** [comment]
i still cant tell if this is stupid enough to merge

**Comment by coiax** [comment]
> 
> 
> i still cant tell if this is stupid enough to merge, this feels like the most obvious example of power creep you could have and yet im so mesmerized by it

The only thing stopping me from merging it is why you need to be able to toggle the captain's laser between maim-mode and regular mode. If it was 100% maim mode, I'd already have merged it.

**Pull request merged**
