### PR TITLE
Makes cautery a lot quieter

### PR DESCRIPTION
**Pull request by maxspells**
## About The Pull Request

Fixes the extremely loud cautery sound effect I made that was added here: [#65578](https://github.com/tgstation/tgstation/pull/65578). When I originally made the sounds, I made it quieter in the code, but now that it uses variables it's better to just redo the sound effect quieter since it works as is and will just make the sound file take up less space as well.

## Why It's Good For The Game

The cautery sound is way too loud. I lowered it by like 65%, so its much more in line with the other surgery sound effects, plus the file is smaller too.

## Changelog

:cl:
soundadd: Changed a cautery sound effect to be quieter.
/:cl:

### CODE REVIEW

**Review by LemonInTheDark — APPROVED** [review]

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Your changelog is inadequate.

Please change it to describe what has changed **to players**. They should not reference filenames.

**Comment by maxspells** [comment]
I changed it, is it okay to just write it like that?

**Comment by Mothblocks** [comment]
Yeah, 'cept you don't need sounddel there

**Comment by Mothblocks** [comment]
I changed it to this:

> soundadd: Changed a cautery sound effect to be quieter.

**Pull request merged**
