### PR TITLE
Removes R&D chem dispensers

### PR DESCRIPTION
**Pull request by Iamgoofball**
1. R&D already makes all the guns, all the armor, all the mechas, all the simple_mob armies, and all the bombs
2. they dont need to make all the chemicals too, we have a department for that

"m-muh sulphuric"
go to chemistry
"b-but it needs upgrades"
repeat after me:
👏 time 👏 gates 👏 aren't 👏 balance 👏

### CODE REVIEW

**Comment by kevinz000** [comment]
time to c4 chem dispensers every round

**Comment by MoreRobustThanYou** [comment]
> chemists are non-existent / exploded / retarded / busy making meth

TOUGH LUCK SCIENCE

**Comment by ACCount12** [comment]
Now show on this doll, where the R&D players touched you?

**Comment by Iamgoofball** [comment]
@ACCount12 can i point at the entire game

**Comment by YakumoChen** [comment]
A large part of research is being able to replace station machines if needed as well, like cloning.

**Comment by Iamgoofball** [comment]
@YakumoChen and there's a reason not everything should be reproducable

@MoreRobustThanYou dont blow up the lab

@kevinz000 cool

**Comment by YakumoChen** [comment]
Next you are going to argue that science can make a personal cloning machine and that's overpowered so it should be removed, right?

Science can make AIs, AIs are powerful, remove more AIs

I could go all day with this

**Comment by MoreRobustThanYou** [comment]
@Iamgoofball all it will take is one greyshit with either a wrench or LAW 2 OPEN to run into chemistry and potass+water BOTH the chem dispensers. Trust me, i've did it before.

**Comment by Partheo** [comment]
If the chemistry department is gone or incompetent, station shouldn't have chemistry. Pretty simple.

**Comment by Iamgoofball** [comment]
@YakumoChen are you starting to realize the problem with R&D now

they dont need to leave R&D after they get the chem dispenser because they can make every department themselves

**Comment by Buggy123** [comment]
GOOD. LET THEM.

Every department has a niche. Science's is being a jack of all trades, master of none, with effort required.

**Comment by kevinz000** [comment]
@Partheo a different codebase + server with rules saying not to powergame has nothing to do with our github, stop.

**Comment by Slignerd** [comment]
@Partheo That's a terrible mentality if I've ever seen one.

**Comment by calibraptor** [comment]
I was about to ask on what map and where in science is there a fucking chem dispenser but realized you were referring to the one that R&D can build.

Whilst doing this would make science more reliant on chemistry and less overpowered, this would also leave the station SOL if the chem dispensers get C4'd or something.

I'd honestly recommend you try to bring the other departments up to science's level rather than trying to bring science down.

**Comment by Bawhoppen** [comment]
I'll remind you all that we tried to add fucking prebuilt ones to xenobio and people cried when I got those removed. Don't get drunk on your powergame people.

**Comment by GuyonBroadway** [comment]
>R&D already makes all the guns,

Not after what you tried.

**Comment by Partheo** [comment]
@kevinz000 This has nothing to do with Yogs whatsoever. Don't look at me as a Yogs person.

**Comment by YakumoChen** [comment]
@Iamgoofball we should not be making station machines unbuildable, a lot of work has gone into the codebase already making things easier to build so that the station can maintain a relative level of sameness in the event of disaster.

Punishing chemists (or literally any other job) by making their job completely unplayable with no recourse if their tech is sabotaged is not the way to handle the game.

**Comment by Iamgoofball** [comment]
oh come on you all know R&D doesnt fucking replace chemistry machines they use this shit to make their own acid

**Comment by YakumoChen** [comment]
I have never had a chemist ask me for a new machine, so it's on them for not trying to get a new one. Departmental interaction is a thing.

**Comment by Iamgoofball** [comment]
>I have never had a chemist ask me for a new machine,

THEN PEOPLE AREN'T NEEDING TO REPLACE THEM

**Comment by YakumoChen** [comment]
Maybe because sabotaging chemistry is a low priority task?

The point is that the option needs to exist because departments need to be rebuildable. 

I have rebuilt cloning dozens of times and even added extra pods to cloning because _It turns out improving the station is a thing science can and does do_

**Comment by Iamgoofball** [comment]
IF SABOTAGING CHEMISTRY ISN'T OCCURING

WHY IS IT SO CRUCIAL IT GET REPLACED

**Comment by Iamgoofball** [comment]
the option does not NEED to exist

it was a quality of life thing that got misused completely

**Comment by GuyonBroadway** [comment]
Why is it so crucial it be removed?

**Comment by YakumoChen** [comment]
Buildable chem dispensers has never been a QOL thing, it's always existed

**Comment by Iamgoofball** [comment]
chrome_2017-11-08_18-56-15
tenor

**Comment by YakumoChen** [comment]
goof have you ever considered most antags don't like to wait around for 30 minutes for stuff in science to be built when they can just start in the job and make antag shit themselves

**Comment by GuyonBroadway** [comment]
I say otherwise, being able to build or rebuild damn near any part of the station awards effort and robustness with custom bespoke solutions or enchancements.

**Comment by Iamgoofball** [comment]
what the fuck does that have to do with anything here

**Comment by YakumoChen** [comment]
what the fuck is the problem with buildable chemistry machines?

**Comment by YakumoChen** [comment]
untitled

**Comment by Iamgoofball** [comment]
because it means science is completely independent with the exception of minerals which have no purpose other than going to R&D, which will always happen because ORM processing

after they get their first batch they can batten down the hatches and never leave the lab again, they have everything, nutrient pumps for food, robo limbs for healing, chem dispensers that are better than what chemistry has roundstart, infinite acid to print with 

also if you fuckers try to argue "WELL SCIENTISTS ALWAYS UPGRADE STUFF" while simultaneously telling me in the other pr "PLAYERS NEVER HELP OTHER PLAYERS", you're scum

**Comment by YakumoChen** [comment]
I don't see the problem with players putting the effort in to make things so they can make more things

**Comment by YakumoChen** [comment]
untitled

**Comment by optimumtact** [comment]
I'm going to time this conversation out for a few hours

**Comment by Grazyn** [comment]
@Iamgoofball why not make the dispenser ID locked so that only chemistry can use it? And while we're at it, ID lock every other machine scientists are abusing, like the fabricator or the camera console

**Comment by Unknown-as-Captain** [comment]
wtf I love goof now?

**Comment by DoctoreMad** [comment]
>Science's is being a jack of all trades, **master of none**

Science is better at killing antags than security and can be more destructive than a wizard(Though they need prep time for bombs/mechs compared to Wiznerd's bullying), can supply the station with things better than cargo(though its not explicitly better at supplying the station and needs mining materials to do so), is 100% better than medbay at their job(Bombs/Mechs are better than Hulks at destruction, has better surgery tools, the rarely used Odysseus can be a chemical powerhouse, can make more sleepers), am I missing something? Let go over the other two roles.

Its debatable but a smart scientist can strong arm people into doing what they want better than command since they actually have candy to give as a reward for people that obey them. Then again, there aren't many smart scientists, so probably a non-issue.
Worse at engineering due to not having hardsuits, still has some engineering goods than them.

**Comment by 81Denton** [comment]
> Worse at engineering due to not having hardsuits

Flight suits have 75 rad resistance and are heat-, fire- and acidproof.

**Comment by FantasticFwoosh** [comment]
> also if you fuckers try to argue "WELL SCIENTISTS ALWAYS UPGRADE STUFF" while simultaneously telling me in the other pr "PLAYERS NEVER HELP OTHER PLAYERS", you're scum

The job/responsibility you are given is just a meaningless pre-round loadout, the player is free to derelict jobs that aren't enforced (command, sec, engineering mandatory) at whim and follow self interest to their own goals. Science can just brick themselves up and ignore the rest of the station while actually doing little to no science as you say, regardless of what people tell you.

Any greyshit or halfway ashwalker caveman with the resources that people taking jobs either start with or have ID access & tools to can do whatever you can by default, your job isn't anything at all.

- Goon, bay and other servers have individual skillsets that make you good/worse at one thing or another, and all default people peform badly at specialist task but can be trained in a game way that doesn't rely on metaknowledge (**or just tough shit, work hard to revive the guy who knew how to do that**)

Worst that will happen will be your ID & workplace objects are stolen (**see chemistry**) and that admins will just be complicit with 'IC retribution' as your char gets lynched by fellow station crew.
_______________________________________________

Personally i would not remove it, i would remove the ability to make it any better than the existing chemistry dispenser machines and/or **find a way to not bottleneck all industrial** (not botany related) **chemicals into two wrenchable & destroyable machines without a backup**.

I am sure people downstream would just ignore this PR anyway and not mirror.

**Comment by Bawhoppen** [comment]
Fwoosh please stop posting

**Comment by FantasticFwoosh** [comment]
Tell me i am wrong in my analysis.

**Comment by epochayur** [comment]
don't like it, better remove it

**Comment by Buggy123** [comment]
I still don't think these should be removed.

@DoctoreMad nah

**Comment by XDTM** [comment]
Time gates and material cost aren't buzzwords.

Would you say that traitors getting tools 20 minutes after they press the button is the same? Or that tc cost is irrelevant?

**Comment by Slignerd** [comment]
> 100% better than medbay at their job (Bombs/Mechs are better than Hulks at destruction...)

Medbay's job is healing people, not destroying the station.

**Comment by Iamgoofball** [comment]
we'll do this later when we decentralize the communist R&D

**Pull request closed without merging**
