### PR TITLE
fixes metastation black door things being reinforced

### LINKED ISSUE #25612: Metastation Chapel doors have protective plasteel on the wiring
Why?

### PR DESCRIPTION
**Pull request by anconfuzedrock**
fixes #25612 did I do it right
also in general I think I mightve made a mistake of some form I hope I didn't

### CODE REVIEW

**Comment by KorPhaeron** [comment]
No map edits please

**Comment by optimumtact** [comment]
Yes stop using the centcom door type and replace it with a new type (if required) or one of the normal station doors.

**Comment by anconfuzedrock** [comment]
that sounds hard I don't know how to do that I'll just give up then

**Comment by Haevacht** [comment]
JFC rock

**Comment by Penguaro** [comment]
@KorPhaeron Can you elaborate on what you meant by > No map edits please
before I make a fix that uses different and less secure doors?

**Comment by Jordie0608** [comment]
He means rather than editing every  `/obj/machinery/door/airlock/centcom` on the map to have `security_level = 0` a new type should be made with that var set in the type definition.

**Comment by Penguaro** [comment]
@Jordie0608 I had a hunch that was the reason but wanted to be sure. Thanks.

**Pull request closed without merging**
