### PR TITLE
Paradox bag resprite and rework

### PR DESCRIPTION
**Pull request by Sheits**
## About The Pull Request

Paradox bags can now be worn on the belt slot instead of the back, while being able to carry less (it can still fit inside bags). 
Adds new sprites for the icon and belt.
image
image

## Why It's Good For The Game

Before, paradox bags could hold a stupid amount of stuff and fit inside a bag like a smugglers satchel (attached image is what it could hold). I felt since it can already fit in your bag there's no point in wearing it on your back slot so I moved it to the belt slot and made sprites for that too while reducing the maximum weight it can carry by 4 times. I'm really surprised I'm the only one who's been abusing the shit out of this.
image

## Changelog
:cl:
balance: Reduces the maximum weight paradox bags can hold
imageadd: Adds paradox bag icon and belt sprites
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
good idea, that way it will be nerfed now everyone knows about it

**Review by Rohesie — APPROVED** [review]
Code and nerf are good. It now just depends on approval from the art nerds.

**Comment by Sheits** [comment]
> Code and nerf are good. It now just depends on approval from the art nerds.

Yeah I think I made the icon sprite a tiny bit big so it looks weird on the ground but I like how it looks inside bags, also there's a lil' glowy animation I didn't include in the screenshots.

**Comment by Nexofas** [comment]
Most of tendril rewards are either useless or batshit powerful. Making useless ones have proper use and rebalancing the overpowered ones are needed. 
Paradox bag is weird in its current state where it can fit into satchels and be used as a weird storage item.

**Comment by Sheits** [comment]
> Paradox bag is weird in its current state where it can fit into satchels and be used as a weird storage item.
I feel the same way, however its useful as fuck for sharing a storage with someone, maybe it could even make a good wiz item but who does wizard steal objs anyways. The best thing iv'e used it for so far is sharing meds with someone but I could imagine a cap using it to transport the nuke disk or something gimmicky.

**Comment by Shadowflame909** [comment]
> > Paradox bag is weird in its current state where it can fit into satchels and be used as a weird storage item.
> 
> I feel the same way, however its useful as fuck for sharing a storage with someone, maybe it could even make a good wiz item but who does wizard steal objs anyways. The best thing iv'e used it for so far is sharing meds with someone but I could imagine a cap using it to transport the nuke disk or something gimmicky.

Imagine if the wizard had a spell that could link other peoples bags with his. top tier stuff

**Comment by Gorionus** [comment]
> 
> 
> > > Paradox bag is weird in its current state where it can fit into satchels and be used as a weird storage item.
> > 
> > 
> > I feel the same way, however its useful as fuck for sharing a storage with someone, maybe it could even make a good wiz item but who does wizard steal objs anyways. The best thing iv'e used it for so far is sharing meds with someone but I could imagine a cap using it to transport the nuke disk or something gimmicky.
> 
> Imagine if the wizard had a spell that could link other peoples bags with his. top tier stuff

Or give it to one of aprentinces (preferably healing one, or teleporting one)
it would be nice addition to non offensive wiz aprentinces

**Comment by maxymax13** [comment]
remove the back sprites if youre planning on making it belt only

**Review by Krysonism — APPROVED** [review]
I think it looks pretty cool.

The animation in particular is nice.

approved

**Comment by Sheits** [comment]
> remove the back sprites if youre planning on making it belt only

pretty sure you cant wear it on your back anymore and the old version just used the chaplain's bag sprite

**Comment by godspeedfunnyman** [comment]
shift + e doesn't work anymore while using the paradox bag, please fix

**Pull request merged**
