### PR TITLE
Revert "adds alternate medborg sprites"

### PR DESCRIPTION
**Pull request by LemonInTheDark**
Reverts tgstation/tgstation#54627

Uhhhhhh something something speedmerge

### CODE REVIEW

**Comment by TiviPlus** [comment]
tgstation server added Do not merge

**Comment by Jared-Fogle** [comment]
@actioninja thoughts?

**Comment by Jared-Fogle** [comment]
geez 3 reverts. whats so special about this pr that everyones going nuts over

**Comment by MrDoomBringer** [comment]
If I tell you the answer you'll regret asking

**Comment by LemonInTheDark** [comment]
Closed in favor of one of the other ones

**Pull request closed without merging**
