### PR TITLE
Expunges part of TOS breaking username in the changelog

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

All instances of Jared-Fogle are now just Jared. I'm okay with further changing it if you guys think that's a better idea, but "Jared" for now seems fine to me

## Why It's Good For The Game

If it's an individual's account, that's up to Github to work on that. But if it's in our codebase, we become responsible. Looking to avoid Newt 2: electric boogaloo

### CODE REVIEW

**Comment by Fikou** [comment]
what did a handkerchief, especially one made of silk do to you?

**Comment by LemonInTheDark** [comment]
Changing the changelog feels... weird

**Comment by Jared-Fogle** [comment]
Replace it with Mothblocks then.

**Comment by Iatots** [comment]
It's the subway advertisement guy IRL.

**Comment by tralezab** [comment]
Lemon, it's definitely been done in the past to solve issues. Take a look at this:
https://github.com/tgstation/tgstation/pull/33626

which reminds me to edit the yml

**Comment by tralezab** [comment]
@Jared-Fogle sure, i'll do that. it's 100% nothing against you just that github deleted our entire repo last time with no warning, so we have to be paranoid about it

**Comment by LemonInTheDark** [comment]
I see whatcha mean. As I recall the log got edited when we changed meatballs too.

**Comment by optimumtact** [comment]
I don't believe there is a ToS violation.

It's not a crime to have a name that is the same as someone else and I'm sufficiently happy that the actual @Jared-Fogle is not acting in bad faith.

**Comment by tralezab** [comment]
Me neither i love @Jared-Fogle as i said above. if you don't think it'll be an issue, then i'll trust you on that

**Pull request closed without merging**
