### PR TITLE
Various admin improvements

### PR DESCRIPTION
**Pull request by Jordie0608**
This adds some features requested by admins:
*Investigate logs seconds in time stamp
*Follow command in notifications instead of Jump-to-Mob
*Buttons to set security level and toggle nuke
*Logging for flamethrowers

Also standardizes many uses of logging name and ckey to use key_name() and key_name_admin()

More to come

### CODE REVIEW

**Comment by TheVekter** [comment]
based Jordie

**Comment by Ausops** [comment]
thank you you are my greatest ally

**Comment by peoplearestrange** [comment]
:+1: All Hail! King of the lose-... admins.

**Comment by peoplearestrange** [comment]
11/10 FWL button is amazingly useful. Thanks agaiN!

**Pull request merged**
