### PR TITLE
Gives Omega its own arrivals shuttle

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
add: Omegastation now has its own arrivals shuttle.
/:cl:

Omega is using the Delta arrivals shuttle, which is way oversized for that small map and forces the docking bay to be huge.

I made a smaller arrivals shuttle for Omega, it looks like this:

omega shuttle

### CODE REVIEW

**Comment by 81Denton** [comment]
8 chairs is more than enough for a lowpop map, even the Pubby shuttle has as many.

**Comment by Kromgar** [comment]
What would happen if all the chairs were occupied?

**Comment by MimicFaux** [comment]
If all the chairs are filled, people just spawn in over top.

**Comment by PKPenguin321** [comment]
that can happen even if not all chairs are occupied, since the chair you spawn into is just random

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
