### PR TITLE
Energy Weapons with rechargeable magazines (WIP)

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Rechargeable magazines for energy weapons.

TODO: Sprites, actual gun stat instead of the placeholder testing pistol, figuring out why caseless ammo is still leaving casings (would appreciate if someone could tell me why it's breaking)

### CODE REVIEW

**Comment by Boredone** [comment]
Not an expert, but I'd do a quick test with the Gyro pistol to test if its also leaving casings, as its the only other non-reusable caseless ammo. That way ye can confirm if its something wrong in general, or just your new casing.

**Comment by KorPhaeron** [comment]
That is what is bugging me, gyro works fine

**Comment by AlexCrimson** [comment]
Dat power creep.

**Comment by RemieRichards** [comment]
@KorPhaeron gyro has it's ```process_fire()``` arguments set up to not eject casings
it's literally

```
/path/to/gun/process_fire(eject_casings = 0, stuff)
..()
```

**Comment by Steelpoint** [comment]
@AlexCrimson If this is more a thing that needs to be orderd from cargo then I don't see a problem.

If you take all the spare auto rifle mags as well and make it that you have to order cargo crates to have spare mags/cells then this adds a unique aspect to the game.

Hell it even now allows someone to disarm weapons, maybe some antag decides to loot all the laser cells but leave the lasers behind.

**Comment by Dorsisdwarf** [comment]
Isn't the point of this so that sec can have laser weapons instead of autorifles?

**Comment by KorPhaeron** [comment]
@Dorisdwarf 

Point of it is that people have been requesting this for years and that I coded it anyway for lavaland.

If I was gonna do sec rifles though then there'd only be 1-2 and be on back only like the ion.

@Alex Crimson

How is it powercreep if there are no stats yet? The basic laserguns/eguns remain unchanged, this I'd just framework for a new weapon type.

**Comment by KorPhaeron** [comment]
@RemieRichards 

Oh, thanks Remie. I thought it was something to do with the ammo (as its named caseless, after all), not the gun itself.

**Comment by Robertha89** [comment]
Paradise had replaceable power cells for energy weapons for a while. It did not end well.

**Comment by Razharas** [comment]
Over month old with no progress - closed

**Pull request closed without merging**
