### PR TITLE
adds a mining equipment storage to the mining base

### PR DESCRIPTION
**Pull request by AarontheIdiot**
## About The Pull Request

 adds mining storage back to mining base underneath the bathroom and dorms. It contains 3 secure mining lockers, 2 ore boxes, a mining vendor, and a nice view of the lava.
## Why It's Good For The Game

 I think it would be worth bringing back. Could be useful to miners, or maybe newly recruited miners, to have some extra things on the base. I'm not even totally sure about this one, so i figured i'd PR it to see what people think.

## Changelog
:cl:
add: adds an equipment storage to the mining base with 3 extra mining lockers, 2 ore boxes, and a vendor. It's south of the base, next to the bathroom and dorms.
/:cl:

### CODE REVIEW

**Comment by AarontheIdiot** [comment]
eh people might just be able to use conscription kits i guess. Didn't think of that.

**Comment by MrFluffster** [comment]
I already wanted to add that in #45166 but was told to change it so this is probably not gonna get in either.

**Comment by AarontheIdiot** [comment]
oof. ill wait and see i guess.

**Comment by Whoneedspacee** [comment]
If we could have a dumbed down locker with no extra survival capsule and other stuff miners insta-loot then it’d be a good change for the game I think.

Since this is a PR addressing only this issue shouldn’t be hard to just make it like that I think.

**Comment by knacker48** [comment]
@Whoneedspacee Were miners ever taking anything other that the survival capsule? Almost everything else in the mining lockers were things that you only needed one of like mesons and the seclite

**Comment by Whoneedspacee** [comment]
Yeah pretty much just the capsules as far as I know in my hundreds of hours.

ask @imsxz too.

**Comment by Dawson1917** [comment]
Bluespace capsules are the only thing worth taking, since nobody enjoys paying cash for the luxury of sitting out ashstorms. Everything else you only need one of unless you lost it in lava or w/e

**Comment by Dennok** [comment]
I like take more satchels.

**Comment by ExcessiveUseOfCobblestone** [comment]
Buy the conscription kits.

**Comment by Dennok** [comment]
Cant to buy it on start. And 1500 for one satchel?

**Comment by InhumanPwnage** [comment]
Just wanted to point out, actually, some of us (including me) used to also loot an extra PKA. I don't mind spending 750 credits for an extra PKA, it's negligible even with my first haul back.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Cant to buy it on start. And 1500 for one satchel?

If you have an issue with it's balance, balance it yourself.

Don't skip over it entirely by adding mechanisms that give you (the items you care about) for free.

**Pull request closed without merging**
