### PR TITLE
Updates the alpha of the 8 newest ghost sprites to match the older ghost sprite.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Old;
FUCK THIS FUCK YOU FUCK YOU DON'T DO WHAT THESE DID
New;
THIS HONESTLY ISN'T BETTER BUT GODDAMN DON'T DO THAT
Most are much lower alpha, except for rainbow, blazeit, and mellow, which are slightly higher alpha.

### CODE REVIEW

**Comment by Anonus** [comment]
Relatedly, fuck whoever did the alpha for these. Fire was uniformly 138, Funkypurp had checkerboard patterned alpha, and Camo had practically random alpha.

**Comment by Supermichael777** [comment]
the fith one seems too faint.

**Comment by MrStonedOne** [comment]
>and Camo had practically random alpha.

I think that was the point.

On some of them, it looks like doing this loses too much detail.

**Comment by Anonus** [comment]
The pinksherbert ghost seems faint, but that's the background, it's all light colors so it blends in with the white.

On detail, well, there kind of wasn't much detail there in the first place, just high alpha and many different colors.
Incidentally, here is the alpha of the funkypurple ghost before edits and after edits.
uh yeah

**Pull request merged**
