### PR TITLE
Resprites Clown

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

image

No this isn't an April Fool's joke :)

## Why It's Good For The Game

:)

## Changelog

:cl: axietheaxolotl
imageadd: brand new sprites for clown mask, suit, shoes, and backpack
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
It had never occurred to her that God would cry, but of course that was wrong. God would be crying all the time. He would cry and cry and never stop. - Justin Cronin

**Comment by magatsuchi** [comment]
matthew 25:30

**Comment by Zonespace27** [comment]
Something something soul, something something ruining TG

**Comment by Ebin-Halcyon** [comment]
I am going to strangle you. It is my god given right.

**Comment by Spc-Dragonfruits** [comment]
In becoming the universe God abdicated, he destroyed himself as God. He turned what he had been, his true self, into nullity and thereby forfeited the Godlike qualities which pertained to him. The universe which he has become is also his grave. He has no control in it or over it. God, as God, is dead.

**Comment by TheBonded** [comment]
i love how the new sprites keep the original feel and theme of the old sprites while updating them to be a little nicer on the eyes. well done!

**Comment by Wallemations** [comment]
This only resprites the main set at the moment, correct?

**Review by Imaginos16 — APPROVED** [review]
But the Lord laughs at the wicked, for he knows their day is coming.

-Psalms 37:13

**Comment by TerraPlanet** [comment]
I like the current clown asthetic. I just really wished that you would include a set in the autodrobe that kept the old clown look. Then I could agree with this.

**Comment by TerraPlanet** [comment]
Wished there would be a set in the autodrobe that kept the old clown look.

**Comment by TerraPlanet** [comment]
If you could, I'd really love if you could add a set in the AutoDrobe that includes the old clown sprite.

**Comment by Crushtoe** [comment]
You have taken away my friends
and made me hateful in their sight.
Imprisoned, I cannot escape;
my eyes are sunken with grief.

I call to you, Lord, all the day long;
to you I stretch out my hands.
Will you work your wonders for the dead?
Will the shades stand and praise you?

Will your love be told in the grave
or your faithfulness among the dead?
Will your wonders be known in the dark
or your justice in the land of oblivion?

**Comment by Tennessee116** [comment]
> Beloved, do not trust every sprite but test the sprite to see whether they belong to the clown, because many false spriters have gone out into the world. This is how you can know the sprite of the clown: every spriter that acknowledges the old sprite come in the flesh belongs to the clown, and every spriter that does not acknowledge the old sprite does not belong to the clown. This is the spirit of the anti-clown that, as you heard, is to come, but in fact is already in the repository. You belong to the clown, children, and you have conquered the soulless, for the one who is in you is greater than the one who is in the spriting community. They belong to the codermonkeys; accordingly, their teaching belongs to the codermonkeys, and the codermonkeys listens to them. We belong to the clown, and anyone who knows the clown listens to us, while anyone who does not belong to the clown refuses to hear us. This is how we know the spirit of honking and the spirit of deceit.

1 Speckles 4:1-6

**Comment by D4C-420** [comment]
These are much better than the clown deserves.

**Comment by GolfinhoVoador** [comment]
What is love?
Baby, don't hurt me
Don't hurt me no more

Baby, don't hurt me
Don't hurt me no more

What is love?

Yeah, yeah

anyways complicated clown

**Comment by JinGiant** [comment]
soulless

**Comment by Farquaar** [comment]
I'm scared.

**Comment by MetalClone** [comment]
It's nice but it barely looks like it fits normal tg-style or this 'nu'-tg-style we keep seeing bleed over from skyrat. The eyes being green instead of blue feels wrong. The wig hair is too orange-reddish which makes it blend in with the dark colored costume too much and it's too heavily shaded. The nose mouth thingy lacks too much contrast. The shirt also blends in together too much, from the normal in-game distance it looks mostly red rather a distinct bright red and pink. The only things I like is the lack of a hard outline on the shirt and shoes and the poofy goofy clown pants not being an amorphous blob of randomly shaded dreammaker garbage pixels. And we're also talking the iconic image of a clown in ss13, it should be loud it should be proud, it should contrast with the rest of the game because they're a clown in outer space.
clown

**Comment by Farquaar** [comment]
> The shirt also blends in together too much, from the normal in-game distance it looks mostly red rather a distinct bright red and pink.

Tbh this is the only thing I think really ought to be fixed with this sprite. The stripes are an important part of the costume, and should be clearly visible.

**Comment by Jolly-66** [comment]
Could we at least get the old mask as an alt to the new one as well?

**Comment by Serxule** [comment]
> i love how the new sprites keep the original feel and theme of the old sprites while updating them to be a little nicer on the eyes. well done!

it really doesnt, its dark and grungy, whereas the old sprite is bright and silly

**Comment by B00tz** [comment]
I don't like how it looks like their arms are abit more slumped. Clowns should always be tense, ready to slip whoever crosses their path.

**Comment by Serxule** [comment]
this takes the clown from being bright, garish, and silly, to dark, boring, and grungy. this is not the iconic clown we know and love

**Comment by interestingusernam3** [comment]
This is your clown on drugs.

**Comment by Fikou** [comment]
poopdark clown

**Comment by newfren** [comment]
https://www.youtube.com/watch?v=euWfTiYwRB0

rest in piece soul

this looks nice

**Comment by RikuTheKiller** [comment]
I honestly dislike it due to the fact it's just a lot darker than our usual clown, though, as previously said, the amorphous mass of the pants is fixed and I also like the expansion of the golden thing on the boots to fit the entire leg.

**Comment by AdipemDragon** [comment]
Not gonna lie, I genuinely think it's a downgrade, because, while it does some things right, I think it also does some things wrong, and _man_, that just bums me out. (yeah yeah this is gonna be an opinion piece, boo hoo)

Firstly, the right things! 
- Actually giving the shoes colored outlines to match the main color's gradient.
- Changing the suspenders and belt around so they're more distinct when paired with the obligatory Giggles backpack. (The yellow is better than the blue for the suspenders, anyway)
- Speaking of, Giggles is nicer to look at! An actual face! Lovely.
- Making some of the features more distinct, like making the cuffs on the sleeves actually _cuffs_ and not just a thing that happened because the outline happened to touch a red stripe in the pattern.

But _man..._
- Cleaning up the neck-chest area by removing what was going on in there, while nice, kind of made a new problem, which is that the new added chest zone gives it the room to have one more pink stripe, which, because it's continuous with the arm stripeage, makes it feel like one amorphous blob, like wearing a form fitting poncho instead of a suit. This wasn't a problem when the sprite was objectively wonky Because there was Something there, whatever it was(was it a deeper v-neck?), to disrupt the pattern. This could be fixed by switching around either the arms or the bodypiece by swapping the red and pink around.
- Speaking of the red and pink! What is happening there. Due to the shading using a visually continuous pallete between the red and the pink, _and_ because you added a zipper that you... sure did some shading around, it just kind of makes the muddyness of it more pronounced.
- Which leads me to: What did you do to the palletes? Why is everything devoid of the Bright Coloring a clown is known for? Why is everything on the suit parts desaturated and not fun to look at?
- The hair, man oh man the hair. While the previous was how it is, the new one just _doesn't_ fall in line with how hair looks ingame, instead opting for a 3 tone Very Harsh shadded mass. It just kind of makes the whole mask like it's a cheap plastic extrusion mold instead of a mask with 2 puffs of "hair" attached to 'em. And it's not even bright and cheerful hair, it's visibly toned gray, or even dare I say brown! 
- No, seriously, I'm giving the palletes another point on the list because those new color picks are the iffiest part in my eyes. Yes, anything is better than eye-searing pure colors, but you can do more than making the main colors look washed out, gray and just a little deflated.

That's not even poking into the minor bad things I think of it, about how:
- The belt, while good that it's a different color along with the suspenders now, doesn't work well when paired with the pink stripe next to it, now that it's yellow, Maybe switching it back to blue just to see how it looks would do it, if not switching around the strips on the body part of the suit like how I suggested earlier.
- On the sideview, I'm unsure if this was a thing on the old shoes but the feet/socks are poking through the one lowered pixel, that seems avoidable.
- On the old sprite, while bad, there was half of an attempt to make the folds in the pants sort of look like that, giant pants, if even a little bit. You instead opted for making it all orbular no matter which dirrection you're looking in on. Congratulations you turned giant puffy clown pants into a big bubble dress.
- It's so minor, buy why the change on the eyes from blue to green? And if anything, it's not the color that bothers me, but the decreased contrast due to the green being lighter than the blue. That, together with you painting the whole "around the eyes" area yellow instead of just the verticals makes it more like weird swimming goggles, honestly.

It takes courage to go straight for the most recognizable sprites, espetially if they're bad(genuinely, imagine if minecraft changed its creeper sprite back when that whole gamewide resprite happened, it's that kinda situation here I think). But for me, at least, this ain't it, chief. There's good, and then there's "mmmmmcouldbehandleddifferent".

If this resprite is genuine, that is.

**Comment by Pepsilawn** [comment]
I like the design changes minus some gripes with the palette and shading but why was the legs part of the pants removed while the rest of the shape kept? It makes it look more like a skirt/puffy dress than these large clown pants you see around, I don't know if the original sprite was misunderstood or if its an intended design change and im really interested in hearing the reason
image

<details>
<summary>large picture spoilered for the sake of not hogging up the discussion</summary>

image
</details>

**Comment by Twaticus** [comment]
i do like this resprite. the overall shading details, the mask, especially the backpack and shoes i think are very cleaned up. nothing here stops me from looking at it and saying "yes this is the ss13 clown". that being said, some concerns brought up are pretty agreeable. particularly the pink stripes and clown hair, and slightly so the eyes and pant definition.

the pink stripes should be bumped up a bit, as it stands it blends in with the red too much. while i dont think its completely lost that classic pink and red design, itd be better toned back closer to the original.
the clown hair can definitely be lightened. i like the blocky shading style choice, just needs to be brighter overall.
as for the eyes honestly fuck hardcoded eyes it should be eye cutouts. you want a blue eyed clown then make your eyes blue.
the pants are missing that leg definition to feel just right. either making the shoes have red on top to simulate the pants or cutting a dixel or two out

my one actual personal nitpick is that the mouth makeup is too dark paired with the nose honk

**Comment by drIcepop** [comment]
Why IS this good for the game? What was wrong with the old clown sprite, it wasn't low quality or anything. If you're going to make a PR that some people won't like, at least put SOME effort into the fucking "why it's good for the game".

**Comment by TerraPlanet** [comment]
Another thing I'd like to say, is, I feel like the current clown sprite makes them look goofy. And this just makes it look like it came from CoD or something.

**Comment by Victor239** [comment]
> clown

God the current sprite is horrific close up. The quality of the new sprites are better overall, however a few changes should be made to copy the soul of previous:
- The trousers are a blob in the new sprite, make it tapered around the ankles
- The orange hair a pixel too high, move it down one so it's better aligned behind the white mask
- On the shirt remove the vertical line dividing the middle, and make the horizontal stripes pinkish again

**Comment by cacogen** [comment]
TOUCAN SHOES

**Comment by bruhlookatthisdood** [comment]
uhhhh something something sucking soul out of tg, something something.

**Comment by trollertroll** [comment]
im gonna post this on ledditz and get some much upvotes for stealing SOVL

**Comment by notfrying1pans** [comment]
it's too pale, clowns are meant to be as bright and obnoxious as possible.

**Pull request closed without merging**
