### PR TITLE
Water bottles can be used in chemical grenades.

### PR DESCRIPTION
**Pull request by MarioWizard119**
## About The Pull Request

Makes water bottles usable in grenade construction.

## Why It's Good For The Game

Consistency and QoL.

## Changelog
:cl:
tweak: Water bottles are now compatible with chemical grenades.
/:cl:

### CODE REVIEW

**Comment by Fhaxaris** [comment]
soda cans or no

**Comment by Angustmeta** [comment]
This is a bugfix.

**Comment by wesoda25** [comment]
its easier to make large beakers than water bottles so no need to downvote

**Comment by optimumtact** [comment]
thog not see real justification

**Comment by MarioWizard119** [comment]
Figured it’d be nice for chemists who bothered to set up a plastic factory to actually be able to use the plastic bottles in any way beakers can, but stealing all the mats it is then I guess.

**Pull request closed without merging**
