### PR TITLE
Respriting the experimentor

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
The base icon was made by someone going by the username of Skilets on Discord. All I did are the states for when the machine is loading/ejecting stuff and when active.

## Why It's Good For The Game
Better icons without the oblique projection. The design is very much in line with lathes and similar machinery.

## Changelog

:cl: Skilets
image: Resprited the experimentor.
/:cl:

### CODE REVIEW

**Comment by YesterdaysPromise** [comment]
mind postin' the sprite 'ere, it'd be nice 'n proper if you deed, innit?

**Comment by Ghommie** [comment]
immagine

**Comment by Sadboysuss** [comment]
> mind postin' the sprite 'ere, it'd be nice 'n proper if you deed, innit?

Icondifbot?

**Review by Wallemations — APPROVED** [review]
I don't think I've ever actually seen the experimenter use most of the alternative sprites, save for the insertion one, does it?

**Pull request merged**
