### PR TITLE
tgui: adds tgui npm library

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
As a side project I've been building an npm library for tgui components. ~~I'd like to see if it works~~. It functions as a straight one-line replacement for interfaces and, if fully implemented, allows you to totally delete your tgui/components and tgui/styles/components folders

This is a test of 10 mostly random UIs

>[!NOTE]
>Link to the repo:
>https://github.com/tgstation/tgui-core
>
>Link to the npm package
>https://www.npmjs.com/package/tgui-core

## Why It's Good For The Game
This is nice because it allows us to easily distribute the gospel of TG to downstreams without them having to sift through our PRs and code (as much as I want to make them) just to assess parity. With tgui-core you're getting the most up-to-date TGUI components without having to fiddle with integrating them or copy pasting.

It also allows me and other TGUI(tm) contributors (all 2 other people maybe) to collectively work across borders on improving and maintaining tgui without causing significant deviations and requiring upstream/downstream ports to fix them.

EDIT: Someone asked how would this allow them to make their own custom versions. You still can, and you can even use both interoperably, by simply changing where you're importing the component from. It's opt in to use tgui-core components.

## Changelog

n/a these are identical tgui components

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
don't really want to excise the components into a npm package

**Comment by jlsnow301** [comment]
> don't really want to excise the components into a npm package

any reason behind this

**Comment by ZephyrTFA** [comment]
self containment

**Comment by ZeWaka** [comment]
> don't really want to excise the components into a npm package

i think your opinion is wrong

at goon at least, we've wanted to upstream improvements we make to components but it's somewhat of a nightmare to separate out everything - this would also be massive for downstreams, and would encourage us to stay up-to-date and be more involved in contributing upstream

**Comment by ZeWaka** [comment]
Probably would be best to have tgui-core under the tgstation org, for at the very least discoverability? Or spacestation13 if you're feeling spicy.

**Comment by stylemistake** [comment]
`@tgui` or `@tgstation13` namespace?

**Review by stylemistake — APPROVED** [review]

**Comment by stylemistake** [comment]
made some suggestions on discord, but this can be merged as is, very nice

**Pull request merged**
