### PR TITLE
Fireaxe cabinet update

### PR DESCRIPTION
**Pull request by Jordie0608**
This is a recode/rework of fire axe cabinets that makes them not children of closets, less bloaty, and to use overlays.

Not a refactor as functionality has changed: Only 10 force is needed to damage the glass, down from 15. Glass uses hp track instead of 'hitstaken', higher force weapons/projectiles will break glass quicker. Glass can be open and closed when smashed. Cabinet comes with a light to indicate locked status. Aliens can no longer take fireaxes from smashed cabinets.

lockreset and lockenable were identical sounds, I've made them into a shorter version since the soundbites lasted much longer than the lock/unlock delay.

WIP until i figure out how to draw broken glass that doesn't look bad.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
If this is the case, you'll need to refact the rest of the wall closets. I think fire extinguisher closets also work like this.

**Comment by Supermichael777** [comment]
so you can finally get the fire ax out of the cabinet without needing the fire ax multitool or welder. Cool.

**Comment by Jordie0608** [comment]
@Dorsisdwarf Nah, it's just fireaxe cabinets.

**Comment by PKPenguin321** [comment]
>400 lines changed for fireaxe cabinets

jesus christ

**Comment by optimumtact** [comment]
@Jordie0608 soon :smile:

**Comment by optimumtact** [comment]
@Jordie0608 please

**Comment by phil235** [comment]
@Jordie0608 Is this still WIP?

**Comment by Jordie0608** [comment]
Seems I totally forgot about this; will be unable to work on anything for a short while however but I'll see about finishing this up once I'm back.

**Comment by Jordie0608** [comment]
@phil235 All done

**Pull request merged**
