### PR TITLE
Fixes AI dating

### LINKED ISSUE #35669: valentine objectives bug
Bagil station, Round id: 83607
[Testmerges]:  #35660  #35609  #35535

So, apparently, this can happen

thank coderbus

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #35669

### CODE REVIEW

**Comment by optimumtact** [comment]
I predict kor will close this with "luv can bloom" comic

**Comment by Repukan** [comment]
Something something blade runner

**Comment by coiax** [comment]
Why wouldn't you want the AI to be on a date with a person

**Comment by AnturK** [comment]
Please read the code.

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
I mean, you could make a better title.

**Pull request merged**
