### PR TITLE
Circuitry Lab Testmerge: Report ALL BUGS HERE

### PR DESCRIPTION
**Pull request by Iamgoofball**
@arsserpentarium is the coder here, I just mapped

this is to consolidate comments + mapping

>Special thanks for :
Jammer 312 for help.And sorry for my pestering.
ImGoofball for help with subsystems and other issues.
Kevinz000 for help with improvement of code
GUN_HOG for testing and feedback.
Maintainers for fast work and proposals,how to fix issues. Also for capablity of think, if feature is needed BEFORE code has been written.

### CODE REVIEW

**Comment by DoctoreMad** [comment]
@Iamgoofball Why are you opening the PR for something big again? You have merge anxiety so that's not recommended for you...

**Comment by ike709** [comment]
pics

**Comment by Qustinnus** [comment]
pics of what

**Comment by ike709** [comment]
@Qustinnus 
image

**Comment by The-clown-known-as-Pepe** [comment]
image

**Comment by Iamgoofball** [comment]
old pic but yeah

**Comment by KorPhaeron** [comment]
Did you just delete toxins

**Comment by Iamgoofball** [comment]
it's replaced for now yeah

**Comment by Arianya** [comment]
Why would you remove a fully functional department instead of, I dunno, the EXPERIM.E.N.T.O.R.?

**Comment by Iamgoofball** [comment]
because fuck you and die, this is where I thought we were putting it as per @duncathan @ninjanomnom were saying

**Comment by The-clown-known-as-Pepe** [comment]
@Arianya this is a testmerge, there is a reason for toxins not being there.

**Comment by WJohn** [comment]
but... we have a misc test lab on almost all maps that goes unused.

???????????????????

**Comment by DoctoreMad** [comment]
This is fine because fuck toxins.

**Comment by KorPhaeron** [comment]
>because fuck you and die

Can you have bare minimum politeness when being the public face of someone elses work? I know you can't resist self sabotaging your own PRs by getting in huge fights but arsserpentarium doesn't deserve that

**Comment by Arianya** [comment]
It seems weird to map something in a specific place just for the testmerge but I'll defer to the maintainers who indicated it should do such

**Comment by KorPhaeron** [comment]
They didn't indicate he should do that he is hallucinating

**Comment by Iamgoofball** [comment]
thats a fair point

@KorPhaeron 
i could of sworn the plan was always "hey we'll move toxins to atmos and put circuits there"

fucking mandela

**Comment by Iamgoofball** [comment]
@WJohn when i tried to turn that lab into a chemistry lab awhile back people got angry for some reason

**Comment by WJohn** [comment]
or maybe throw out the experimentor? is it even tied into R&D techwebs? if not it could easily be removed.

**Comment by Okand37** [comment]
If I am unmistaken, the experimentor was planned to be tied to techwebs. Out of curiousity, near the bottom of the image is that an autolathe and a modular computer or something in specific?

**Comment by Qustinnus** [comment]
Someone made a HONK spamming machine, like huge font too.
I didn't know how to unlock more circuitry on my printer.
There's RCDs in the engivend in the lab.

**Comment by newfren** [comment]
What does this actually... do though?

**Comment by Supermichael777** [comment]
Its traditional to have some description in the OP

**Comment by deathride58** [comment]
What the fuck

The required machinery for circuitry can be produced in the protolathe like any other item

Circuitry does not need its own sub-department, having the required devices to mass-produce all sorts of game-breaking machines roundstart without ever touching the RnD consoles would be pretty bad.

The only circuitry thing that should have a spot in the map roundstart is the exonet server.

**Comment by Iamgoofball** [comment]
@deathride58 you realize we're replacing R&D with circuitry right

**Comment by Repukan** [comment]
No big loss with toxins removal tbh

**Comment by Shadowlight213** [comment]
\>toxins deleted
I :100: support this pr. Finally the worst department is gone.

**Comment by Qustinnus** [comment]
toxins will come back it'll just be in atmos instead

**Comment by Supermichael777** [comment]
I worked for several minutes trying to figure out how to use the interfaces but was arrested before I could turn my alarm clock into a bomb. 1/10 too much water -IGN

**Comment by Supermichael777** [comment]
Realtalk though the grenade primer does not seem to store a reference to its grenade. Intentional?

**Comment by Anonmare** [comment]
tbh you should look up Pubbystation's map as they have toxins storage shared with atmospherics

**Comment by Bawhoppen** [comment]
Don't anyone dare suggest removing the Experimentor. It's literally the only part of science that isn't pure powergame and actually has some unique dynamic mechanics to it. (All it needs is a little love to actually become a great feature)

**Comment by Anonmare** [comment]
Kor what the heck I was offering a suggestion

**Comment by KorPhaeron** [comment]
I don't want people to think circuits is actually removing toxins so I don't want to confuse people by having discussion of moving to toxins to atmospherics in this PR

**Comment by davethwave** [comment]
Just saying but I think moving toxins to atmos will be a improvement

**Comment by Supermichael777** [comment]
Okay i cant seem to scan for mobs or humans in general

**Comment by Iamgoofball** [comment]
supermichael use the debugger

**Comment by Supermichael777** [comment]
The ranged sensor doesnt seem to pulse

**Comment by Supermichael777** [comment]
im getting the hang of it

almost got a ghetto grenade launcher setup

**Comment by Supermichael777** [comment]
The debugger and constants cant write to bools

**Comment by Qustinnus** [comment]
aren't bools just numbers on this..?

**Comment by MMMiracles** [comment]
The locator can't find items picked up or put in a container, maybe they should be able to at least see items held by a person?

**Comment by Iamgoofball** [comment]
there's an advanced locator which can do that

**Comment by Iamgoofball** [comment]
@Supermichael777 multitools can toggle bools too

**Comment by MMMiracles** [comment]
I was using the advanced locator, it kept saying it couldn't find the item.

**Comment by Qustinnus** [comment]
it might be kind of expensive to check contents of everything

**Comment by MMMiracles** [comment]
Probably but it'd totally be worth it.

**Comment by Supermichael777** [comment]
huh the sensor can see walls but the examiner cannot

**Comment by Supermichael777** [comment]
also gheto grenade launcher works

**Comment by Supermichael777** [comment]
Once you get over the HOW DOOOO? this is actually really engaging. 10/10

working with and around the 'Constrained but not limited" toolset is fun

**Comment by MoreRobustThanYou** [comment]
capture

**Comment by Supermichael777** [comment]
Their does not seem to be a way to store lists

**Comment by Spaceinaba** [comment]
why put a machine that scientists dont have access to in science

**Comment by Supermichael777** [comment]
lists seem broken in general (No visible way to generate a list, appending to a len = 0 list produces a len = 0 list)

**Comment by Sarcalogo** [comment]
Do you need real life experience with basic circuits, breadboards, etc to use this? It looks pretty complex..

**Comment by Qustinnus** [comment]
you need basic programming / visual scripting knowledge

**Comment by Qustinnus** [comment]
this is bait for programmers to start playing again

**Comment by MMMiracles** [comment]
EPv2 circuits don't seem to work? Setting an address to send data to and pulsing 'send data' does nothing to the receiving EPv2 circuit.

**Comment by ike709** [comment]
Is an exonet node actually mapped in?

**Comment by Qustinnus** [comment]
no

**Comment by MMMiracles** [comment]
No, one isn't apparently. Maybe one should be placed in telecomms round-start, or should it be left to be built?

**Comment by Qustinnus** [comment]
it should be in telecomms apparently. but goof just forgot or wasn't told.

**Comment by Qustinnus** [comment]
Also, potentially make drag and drop work as a way to open the UI. I feel it's clunky to pick up the item, open the UI, and dropping it again.

**Comment by duncathan** [comment]
circuits isn't truly removing toxins ninja and i are just using the science dep makeover as an excuse to push our agenda

**Comment by ninjanomnom** [comment]
The Engineer Secret Autist Society will buff engineering department to previously unthought levels of powercreep beyond your wildest dreams.

**Comment by davethwave** [comment]
ha ha, true

**Comment by Grazyn** [comment]
What are those circuits good for? Can you make like, an Arduino board and build a hallway-long alarm clock with floor lights?

**Comment by Qustinnus** [comment]
you can make machines and connect them through psuedo internet connections to do that yes

**Comment by outbools** [comment]
is this too hard to describe what this PR does
repoban goof when

**Comment by arsserpentarium** [comment]
Thanks for feedback.
1.Grazyn.It's good for not very complex(yet) automation.
2.Qustinnus,okay.drag'n'drop is good idea.But also you can just examine opened machine.
3.Supermichael777,strange. lists was working in all the tests.Maybe you did smth wrong?
but yes. there is a way to store list,but crutchy. maybe I should fix it.
ref scan for grenade possibly will be implemented later.
I think,I'll remake it a bit next time.
4.MMMiracles,I am not planning to make contents scan.too gamebreaking.

**Comment by praisenarsie** [comment]
COMPILE TGUI
COMPILE TGUI
COMPILE TGUI
COMPILE TGUI
COMPILE TGUI
COMPILE TGUI
COMPILE TGUI

**Comment by Supermichael777** [comment]
nah i got the launcher to work, just had to treat the primer as a disposable piece

**Comment by arsserpentarium** [comment]
praisenarsie ,I am planning to make better interface for circuits,but Html.Can't into tgui.

**Comment by Supermichael777** [comment]
its  not storing lists i just cant figure out how to generate one

**Comment by arsserpentarium** [comment]
check it. prototype of farmbot,which oly uproots weeds and harvesting plants.also it must have direct access to trays. otherwise it will stuck if will collide with obstackle.

```start.assembly{{*}}electronic drone=-=Plant Combine{{*}}components^%^delete circuit=-=Try List Smp^%^list advanced locator=-=list advanced locator^%^delete circuit=-=delete circuit^%^at circuit=-=at circuit^%^len circuit=-=len circuit^%^less than gate=-=less than gate^%^plant manipulation module=-=plant manipulation module^%^integrated plant analyzer=-=integrated plant analyzer^%^one-sec delay circuit=-=One-sec Delay Circuit New Tray^%^tesla power relay=-=tesla power relay^%^locomotion circuit=-=locomotion circuit^%^basic pathfinder=-=basic pathfinder^%^examiner=-=examiner^%^less than gate=-=Less Than Gate Weed^%^equal gate=-=Equal Gate Harvest^%^one-sec delay circuit=-=One-sec Delay Circuit New Scan^%^memory chip=-=Memory Chip Harvest^%^memory chip=-=Memory Chip Weed^%^less than or equal gate=-=less than or equal gate^%^one-sec delay circuit=-=One-sec Delay Circuit Motion^%^starter=-=starter{{*}}values^%^1i1:+:list:+:hydroponics+tray=&soil=^%^2i1:+:list:+:hydroponics+tray&soil^%^2i2:+:num:+:8^%^3i1:+:list:+:%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref^%^3i2:+:num:+:1^%^4i1:+:list:+:%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref^%^4i2:+:num:+:1^%^5i1:+:list:+:%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref&%2fdatum%2fweakref^%^6i1:+:num:+:12^%^6i2:+:num:+:1^%^7i2:+:num:+:0^%^11i1:+:num:+:5^%^14i1:+:num:+:1^%^14i2:+:num:+:0^%^15i1:+:num:+:0^%^15i2:+:num:+:1^%^17i1:+:num:+:0^%^18i1:+:num:+:1^%^19i1:+:num:+:2.23607^%^19i2:+:num:+:1.5{{*}}wires^%^2i1=-=1o1^%^3i1=-=2o1^%^3i1=-=3o1^%^4i1=-=2o1^%^4i1=-=3o1^%^5i1=-=2o1^%^5i1=-=3o1^%^6i1=-=5o1^%^7i1=-=4o1^%^7i2=-=17o1^%^7i2=-=18o1^%^8i1=-=4o1^%^11i1=-=12o1^%^12i1=-=4o1^%^13i1=-=4o1^%^14i2=-=8o11^%^15i1=-=8o16^%^19i1=-=13o5^%^1o1=-=2i1^%^2o1=-=3i1^%^2o1=-=4i1^%^2o1=-=5i1^%^3o1=-=3i1^%^3o1=-=5i1^%^3o1=-=4i1^%^4o1=-=8i1^%^4o1=-=13i1^%^4o1=-=7i1^%^4o1=-=12i1^%^5o1=-=6i1^%^8o11=-=14i2^%^8o16=-=15i1^%^12o1=-=11i1^%^13o5=-=19i1^%^17o1=-=7i2^%^18o1=-=7i2^%^1a1=-=16a2^%^1a2=-=2a1^%^2a1=-=1a2^%^2a2=-=5a1^%^2a3=-=16a1^%^3a1=-=9a2^%^3a2=-=5a1^%^4a1=-=6a3^%^4a2=-=8a1^%^5a1=-=2a2^%^5a1=-=3a2^%^5a2=-=6a1^%^6a1=-=5a2^%^6a2=-=16a1^%^6a3=-=4a1^%^7a1=-=19a2^%^8a1=-=4a2^%^8a1=-=20a2^%^8a2=-=13a1^%^9a1=-=13a3^%^9a1=-=15a3^%^9a2=-=3a1^%^11a1=-=12a2^%^12a1=-=19a3^%^12a2=-=11a1^%^12a2=-=20a1^%^13a1=-=8a2^%^13a2=-=14a1^%^13a3=-=9a1^%^14a1=-=13a2^%^14a2=-=18a1^%^14a3=-=15a1^%^15a1=-=14a3^%^15a2=-=17a1^%^15a3=-=9a1^%^16a1=-=6a2^%^16a1=-=2a3^%^16a1=-=21a1^%^16a2=-=1a1^%^17a1=-=15a2^%^17a2=-=19a1^%^18a1=-=14a2^%^18a2=-=19a1^%^19a1=-=17a2^%^19a1=-=18a2^%^19a2=-=7a1^%^19a2=-=20a1^%^19a3=-=12a1^%^20a1=-=12a2^%^20a1=-=19a2^%^20a2=-=8a1^%^21a1=-=16a1{{*}}end```

**Comment by KorPhaeron** [comment]
Test happened

**Comment by Qbopper** [comment]
so can someone summarize what this is? I missed the test

**Comment by calzilla1** [comment]
Eta on when this will be made to mine bitcoin?

**Comment by Supermichael777** [comment]
are the % intentional? if so my bomb drone is
`start.assembly{{*}}electronic drone=-=electronic drone{{*}}components^%^text-to-speech circuit=-=Meme Emitter^%^adjacent locator=-=Target Proximity Sensor^%^locomotion circuit=-=locomotion circuit^%^grenade primer=-=grenade primer^%^fast ticker=-=Motion Timer^%^basic pathfinder=-=basic pathfinder^%^EPv2 circuit=-=EPv2 circuit^%^reference decoder=-=reference decoder^%^string to number=-=string to number{{*}}values^%^1i1:+:text:+:OVER HERE!^%^3i1:+:num:+:1^%^4i1:+:num:+:1^%^5i1:+:num:+:1^%^8i1:+:text:+:35431c40454a4f4344532e^%^9i1:+:text:+:1{{*}}wires^%^2i1=-=8o1^%^3i1=-=6o1^%^5i1=-=9o1^%^6i1=-=8o1^%^8i1=-=7o2^%^9i1=-=7o3^%^6o1=-=3i1^%^7o2=-=8i1^%^7o3=-=9i1^%^8o1=-=2i1^%^8o1=-=6i1^%^9o1=-=5i1^%^1a1=-=8a2^%^2a1=-=5a1^%^2a2=-=4a1^%^3a1=-=6a2^%^4a1=-=2a2^%^5a1=-=6a1^%^5a1=-=2a1^%^6a1=-=5a1^%^6a2=-=3a1^%^7a2=-=8a1^%^7a2=-=9a1^%^8a1=-=7a2^%^8a2=-=1a1^%^9a1=-=7a2{{*}}end`

targeter
`start.assembly{{*}}electronic assembly=-=electronic assembly{{*}}components^%^toggle button=-=Drone Safety Switch^%^EPv2 circuit=-=EPv2 circuit^%^reference encoder=-=reference encoder^%^Ranged sensor=-=Ranged sensor^%^number to string=-=number to string{{*}}values^%^2i1:+:text:+:fc00:ce5e:bc2b:684c:b7ae^%^2i2:+:text:+:35431c40454a4f4344532e^%^2i3:+:text:+:1^%^4i1:+:num:+:1^%^5i1:+:num:+:1{{*}}wires^%^2i2=-=3o1^%^2i3=-=5o1^%^3i1=-=4o1^%^5i1=-=1o1^%^1o1=-=5i1^%^3o1=-=2i2^%^4o1=-=3i1^%^5o1=-=2i3^%^1a1=-=5a1^%^2a1=-=3a2^%^3a1=-=4a1^%^3a2=-=2a1^%^4a1=-=3a1^%^5a1=-=1a1{{*}}end`

**Comment by MMMiracles** [comment]
I slightly fear that this might become similar to NTSL where you have a few people who actively made scripts for it while the majority just copy/paste the good shit without doing much experimentation themselves.

**Comment by imsxz** [comment]
Add advanced machine interaction so I can make a bot that does RND, takes minerals from the ORM, upgrades the station, prints itself an AEG, and begins validhunting.

**Comment by Anonmare** [comment]
It'd be a good idea to include an ingame book with some basic machines you can make. It's very overwhelming for those who aren't versed in the concept and having some examples to experiment from would be grand

**Comment by davethwave** [comment]
Agreed

**Comment by Bawhoppen** [comment]
Aren't ingame books just links to the wink though anyways?

**Comment by Qustinnus** [comment]
they are

**Comment by newfren** [comment]
It'd be nice to have a wiki page.

**Pull request closed without merging**
