### PR TITLE
Makes lethal injection size syringes unable to be loaded into a syringe gun

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request

This is an ided pr from a long time ago that's now socially acceptable given the climate.

## Why It's Good For The Game
I dunno

## Changelog
:cl: itseasytosee
tweak: lethal injection syringes can no longer be loaded into syringe guns, the wizard federation rejoices.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
use your epi pen stupid

**Comment by ATH1909** [comment]
ided

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/pull/55642 specifically accounted for lethal syringes existing (which factored into its justification for why bluespace syringes could be safely removed):
> Syringe guns in general can continue to chamber 50u lethal injection syringes which are limited in quantity on any shift and only available from secure areas.

**Comment by ArcaneDefence** [comment]
> 
> 
> use your epi pen stupid

For reference, this does not stop the lethal injection execution mix in any capacity, and you will still be put to sleep for a substantial period of time if it's a chloral hydrate subtype.

**Comment by necromanceranne** [comment]
> use your epi pen stupid

Fun fact: Epipens potentially make it worse by introducing more formaldehyde into your system, which comes preloaded in lethal injection syringes and acts as a natural counter to epipens, since more formaldehyde means more histamine which means more likelihood of histamine overdose, which will wreck your shit.  

Epinephrine does nothing unless you're actually in crit. Epipens are for use on other people, not you, or if you know you're within arms reach of medical help and you're just caught out in the open. And they don't prevent killmixes from ticking over.

Epipens will not save you from 50 units of a kill mix out in the open and away from medical help.

Even if this is a meme, it bears repeating that there are very few ways of readily stopping chems murdering you if you have excessive quantities of the chems in your body unless you specifically have the stronger purging agents, and those are just running the toxins out of your system before they kill you, not reversing the damage or preventing it from happening. Some mixes could kill you through pentetic regardless, like a syringe loaded with all the caustic acids for frontloaded damage upon injection.

**Comment by wesoda25** [comment]
Guys why do epipens have 3 units of formaldehyde instead of 1 (or even less 😯)?

**Comment by Tlaltecuhtli** [comment]
> Guys why do epipens have 3 units of formaldehyde instead of 1 (or even less 😯)?

cause you dont read liver code

**Comment by wesoda25** [comment]
Yeah ik it purges less than 3 but it surely doesn’t do that when you are DEAD right?? Chems won’t metabolize so you don’t need much!

**Comment by Jared-Fogle** [comment]
so you can pop it in you right before you die and not have to worry about your liver eating it up if it takes a bit longer than expected maybe

**Comment by wesoda25** [comment]
That’s dumb players shouldn’t have control over their dead bodies organs, that should be something other players can choose to administer if available.

**Comment by Timberpoes** [comment]
Ahhh let me think. No.

> 
> 
> #55642 specifically accounted for lethal syringes existing:
> 
> > Syringe guns in general can continue to chamber 50u lethal injection syringes which are limited in quantity on any shift and only available from secure areas.

**Comment by itseasytosee** [comment]
Yeah thats cool

**Pull request closed without merging**
