### PR TITLE
Fixes suffocation damage and healing for reagents

### PR DESCRIPTION
**Pull request by RikuTheKiller**
## About The Pull Request

This fixes a hidden side effect of the "refactor" in #73147 that actually caused ALL existing suffocation damage dealing/healing chemicals to not work on species that breathe gases other than oxygen.

This is also good for future code since if you want a chemical to not affect a specific species or such, you should explicitly define that, it shouldn't be implicitly done for you in the background with 0 implication.

Also reverts #74247 since it's no longer needed.

## Why It's Good For The Game

First off, the change was unintended. It was intended to be a refactor.

Second, the change is unfun and isn't explained anywhere. It isn't very fun to sit on the floor in medbay while even the most experienced doctors can't figure out why the strongest suffocation healing chemicals in the game aren't working. Cue this on repeat for 30 minutes. I've personally experienced this like 10 times now and even I didn't know why it was happening.

Even if you know the change exists, it's still extremely convoluted to get around. You have to do CPR on a plasmaman at the speed of an average cheetah or abuse the brute/burn revival method.

## Changelog

:cl:
fix: Suffocation-handling reagents work on all species once more.
spellcheck: Added a previous tip for handling plasmaman suffocation back into the game.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
To clarify on what the nightmare for plasmamen in medbay is:
Defibrillators revive you at a set health total (somewhat deep into crit), dealing oxyloss damage to you if you would be revived above that health total. This is normal, it prevents defibbed people from immediately popping up after being revived.

Normally, doctors use CPR and/or healing chems to heal off this oxyloss damage. Since plasmamen wear helmets and need internals in order to breathe, chems are the natural solution.

However, because of the aforementioned "refactor", salbutamol, convermol, and even cryoxadone do not heal the oxyloss of plasmamen. This information is not relayed to the player via any in-game source.

As such, the correct solution for healing the oxyloss of plasmamen is to *perform CPR on them*. Y'know, the medical technique that moves air from your lungs to your patient's lungs, which works regardless of what kind of air either of you breathe.

And if your medbay personnel have a self-respiration virus, rendering them unable to perform CPR... you better make an oxyloss (or advanced) medibot, buddy. Alternatively, you can intentionally brutalize the corpse of a plasmamen you want to revive so that they'll come back with more treatable brute/burn damage and less untreatable oxyloss damage.

I see two feasible resolutions to this problem:
1. Handwave that our fictional healing chemicals that work in undefined ways can heal oxyloss regardless of lung type for gameplay reasons.
2. Make CPR require compatible lung types for the sake of consistency/muh realism, making plasmamen revival even more jank and unintuitive than it already is.

I would much rather choose 1.

**Comment by Jacquerel** [comment]
Just as a future note people make oversight bugs with changes all the time and it isn't necessary to be passive aggressive about it across multiple PRs.

**Comment by RikuTheKiller** [comment]
I'm more passive aggressive than I normally would be because I interpreted one of our previous convos as you defending this change for no real reason.

**Comment by RikuTheKiller** [comment]
> > I'm more passive aggressive than I normally would be because I interpreted one of our previous convos as you defending this change for no real reason.
> 
> I'm sorry this is causing so much strife. I'm the one behind the 'refactor' you speak of. The change was not unintended, it was very much intended, and the reasons why are explained in the PR that you yourself linked. However it was part of an incomplete series of PR's.
> 
> The plan was to work on an update of medicines that will affect plasmamen and other species with different respiration_types, since it doesn't make sense why they would be able to be healed by oxygen drugs. This goes in hand with them not being affected by organic toxins (and conversely, organic antitoxins).
> 
> Since that hasn't happened yet however setting it to `ALL` seems the best course of action in the meantime until that update comes around. I should have done that myself foreseeing this being an issue. But alas. Mistakes happen. Thanks for taking care of it for now.
> 
> @RikuTheKiller if you'd like to be involved in this medicine update let me know, it'd be nice to get some input from someone who actually plays plasmamen. : )
> 
> @ATH1909 you are welcome to join in as well.

I still disagree with doing this rework at all.

**Pull request merged**
