### PR TITLE
(TM ONLY) Doubles the speed of all projectiles (that matter)

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

What it says on the tin. There might be some missed (colossus projectiles I deliberately ignored), but who cares.

## Why It's Good For The Game

I'm really curious to see what the effects of increasing the projectile speed broadly will have. People often complain about the fact that you can, in many circumstances, outrun bullets due to baseline move speed being so high..

 Many others argue that this is an important balancing point, as not being able to avoid projectiles will make ranged weapons simply too good and removes an aspect of skill expression to engagements in being able to avoid shots.

Let's see what happens.

## Changelog
:cl:
balance: All projectiles have had their flight speed increased by nearly double their original speed.
/:cl:

### CODE REVIEW

**Comment by Holinka4ever** [comment]
It will be interesting to implement hitscan weapons on the basis routine.
I am actually in all hands up to see how it work out, even as test merge, we will get all valid information to work with!

**Comment by SmArtKar** [comment]
> It will be interesting to implement hitscan weapons on the basis routine. I am actually in all hands up to see how it work out, even as test merge, we will get all valid information to work with!

There's been a TM of that ~2 years ago - didn't work that well.

**Comment by Loafin34** [comment]
disabler meta

**Comment by SomeoneYouProbablyKnow** [comment]
Honestly double current speed might be the sweet spot. Not so slow you can walk out the way but slow enough you can juke some of it.

But let's be real the reason why people dodge bullets is our insane base movespeed. It's also the reason running up to a guy and wacking him with a telebaton is oft easier than aiming anything. Or just running of screen from someone shooting you.

And the hitscan TM was really funny so i'm happy to see this.

**Comment by ju45he** [comment]
Insane revolver buff, sec team gone in seconds by projectiles that hit their target.

**Comment by Eronymun** [comment]
> Insane revolver buff, sec team gone in seconds by projectiles that hit their target.

Insane regal condor nerf... hitscan has never been slower...

**Comment by necromanceranne** [comment]
so the servers kind of too dead to do tests with right now and also smartkar let me know that there is a nonzero chance this will just cause lag right now until a projectile refactor happens, so maybe let's hold off for a little bit, we can come back later, this is only a test pr after all

**Pull request closed without merging**
