### PR TITLE
Space ruin - All American Diner soda machine fix

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

Super small fix that i think was just an oversight but has bugged me everytime i've gone to that ruin, the ultra important and urgent fix for moving the soda machine!

image

## Why It's Good For The Game

You can now actually walk around the kitchen without an invisible wall getting in the way

## Changelog
:cl:
fix: Space Ruin - All American Diner - Soda Machine now is scooted out of the way
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
The PR title is very misleading. I thought it was a new space ruin by the way it was worded.  I'd recommend you name your fixes accurately in the future. Something like, `Fix soda machine on space ruin` makes a lot more sense.

**Review by Fikou — COMMENTED** [review]
(not a maptainer review)
i'd rather you just var edit it to not be dense than place it on the wall turf

**Comment by Zergspower** [comment]
> The PR title is very misleading. I thought it was a new space ruin by the way it was worded. I'd recommend you name your fixes accurately in the future. Something like, `Fix soda machine on space ruin` makes a lot more sense.

i generally format my PR's by first what i'm touching (e.g. space ruine) Then by what's being done

**Comment by Zergspower** [comment]
> (not a maptainer review) i'd rather you just var edit it to not be dense than place it on the wall turf

i was mostly tryin to keep the visual appeal - tbh i can prolly just make a small tweak to give it an inlay table if anything

**Comment by Fikou** [comment]
> > (not a maptainer review) i'd rather you just var edit it to not be dense than place it on the wall turf
> 
> i was mostly tryin to keep the visual appeal - tbh i can prolly just make a small tweak to give it an inlay table if anything

if you make it not dense that doesnt change anything about the visuals

**Pull request merged**
