### PR TITLE
/TG/C EXPANSION UPDATE 2564: BUY MORE CARDS

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
HEY KIDS! DO YOU LIKE THE **Nanotrasen™ TACTICAL GAME CARDS®** GAME? WE HERE AT **Nanotrasen™ Nanotainment®** ARE PLEASED TO ANNOUNCE THE LATEST EXPANSION CONTENT FOR THE **Nanotrasen™ TACTICAL GAME CARDS®** GAME!

**EXPAND YOUR GAME™** WITH THE /TG/C® Coreset™ 2564: PACKED WITH VERSATILE CARDS TO FIT ANY DECK!

DELVE INTO FORBIDDEN SECRETS WITH THE /TG/C® Expansion Set: Blood and Stone™!
- TWO NEW FACTIONS: UNLOCK THE SECRETS OF THE NECROPOLIS, OR DISCOVER ELDRITCH MAGICKS WITH THE BLOOD GEOMETER
- EXCITING NEW KEYWORDS TO EXPAND YOUR TACTICS, INCLUDING NECROTAINT AND BLOOD PAWN
- COMPLETE WITH A NEW CARDBACK FOR YOUR COLLECTION

image

EMBRACE THE POWER OF TECHNOLOGY WITH THE /TG/C® Expansion Set: TechnoShock™!
- TWO NEW FACTIONS: SEEK HUMANITY'S END UNDER THE ROGUE AI, OR HARNESS ENDLESS TECHNOLOGICAL COMBINATIONS WITH NAKAMURA ENGINEERING
- EXCITING NEW KEYWORDS TO EXPAND YOUR TACTICS, INCLUDING EXTERMINATE AND MODULAR
- COMPLETE WITH A NEW CARDBACK FOR YOUR COLLECTION

image

JOIN THE XENO WARS WITH THE /TG/C® Expansion Set: Resin Frontier™!
- TWO NEW FACTIONS: FIGHT FOR HUMANITY'S FUTURE WITH THE TGJMC, OR ASSIMILATE WITH THE XENO MENACE
- EXCITING NEW KEYWORDS TO EXPAND YOUR TACTICS, INCLUDING OO RAH AND HIVEMIND
- COMPLETE WITH A NEW CARDBACK FOR YOUR COLLECTION

image

**AND THAT'S NOT ALL!**
- OVER 40 NEW KEYWORDS TO AMP UP YOUR GAME
- INTEGRATION OF ERRATA TO CLEAR UP MISCONCEPTIONS
- ACROSS-THE-BOARD REBALANCE
- MORE DEFORESTATION IN CALIFORNIA
- AND **SO MUCH MORE™**!!!

AND EVEN MORE! WE WANT YOUR FEEDBACK!
THAT'S RIGHT, **YOUR FEEDBACK!**
WE WANT TO MAKE THE **Nanotrasen™ TACTICAL GAME CARDS®** GAME THE BEST IT CAN BE, AND SO WE WANT YOUR THOUGHTS!
PLEASE MAIL YOUR FEEDBACK TO THE FOLLOWING ADDRESS:
**Nanotrasen™ Nanotainment®**
PO Box 900
Los Angeles
California
90212

(OR LEAVE IT IN THE HANDY PR COMMENTS **BENEATH THIS VERY POST**)
AND WE PROMISE TO READ IT!
THAT'S RIGHT, WE PROMISE WE WILL READ YOUR FEEDBACK!

(Turning off hype narrator mode for a second here, I'm making this PR at a very early stage primarily to gather feedback on the balance; with the number of cards being introduced and changed I know that I can't balance it myself, and so I need to know how it plays in vivo- so seriously, if you have feedback on the balance or how the game plays, I want to hear it)

**Nanotrasen™ TACTICAL GAME CARDS®: BUY MORE CARDS™**
## Why It's Good For The Game
YOU CAN'T BUY MORE CARDS IF THERE AREN'T MORE CARDS TO BUY
Also, these have been in the oven for like, 3 years now, and if TCG is ever going to be a full fledged feature it's going to need this kind of balancing, and way more cards; besides, it's fun!
## Changelog
:cl:
add: THREE NEW CARD SETS HAVE LANDED FOR THE /TG/C GAME: BUY MORE CARDS
balance: /TG/C HAS RECEIVED AN EXTENSIVE BALANCE OVERHAUL ACROSS THE CORESET 2560 AND RESIN FRONTIER: BUY MORE CARDS
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
add a coder pack

**Comment by Loafin34** [comment]
i can't believe TCG is finally getting an update. can you make the cards when in the holodeck able to attack players automatically so that it's faster?

**Comment by DaCoolBoss** [comment]
Only complaint is that I think the card backs should remain the same regardless of what set it's from, so mixed-set decks look consistant Real life TCGs rarely change card backs, if ever.

**Comment by deathrobotpunch** [comment]
WOO TGC SERIES 2 IS FINALLY OUT!O

**Comment by deathrobotpunch** [comment]
list of all cards and rulesets (so far)

https://docs.google.com/document/d/10rScsFCk2GoUuYmkV0AQJdVbFTVxIYFviU4drImgowE/edit

**Comment by L0pz** [comment]
I WILL CONSUME THE COLLECTIBLE PRODUCTS!!!!!

**Comment by Exester509** [comment]
> list of all cards and rulesets (so far)
> 
> https://docs.google.com/document/d/10rScsFCk2GoUuYmkV0AQJdVbFTVxIYFviU4drImgowE/edit

It's set to private so we can't actually read it

**Comment by deathrobotpunch** [comment]
> > list of all cards and rulesets (so far)
> > https://docs.google.com/document/d/10rScsFCk2GoUuYmkV0AQJdVbFTVxIYFviU4drImgowE/edit
> 
> It's set to private so we can't actually read it

oops

**Comment by deathrobotpunch** [comment]
I think with the current TGC cards I would like to see prisoner be a sec department card. and psychologist to be a medical type card with the correct subtype

**Comment by Iamgoofball** [comment]
@ninjanomnom can you re-open this

**Pull request closed without merging**
