### PR TITLE
Removes the shuttle named "I'm fed up with this world"

### PR DESCRIPTION
**Pull request by Anonmare**
[Changelogs]: Oh hi Johnny I didn't realise it was you

:cl: 
del: Removes The Room
/:cl:

[why]: Jokes are meant to be funny

### CODE REVIEW

**Comment by KorPhaeron** [comment]
This is a serverside config thing, appeal to headmins if you want it gone

**Comment by Supermichael777** [comment]
Mad cus bad

**Comment by QualityVan** [comment]
YOU'RE TEARING THIS MAP APART, LISA

**Comment by lzimann** [comment]
change title so it actually says what the pr is

**Comment by Iamgoofball** [comment]
:-1: only shuttle with lore

**Comment by praisenarsie** [comment]
it's still a baad shuttle and you would only be buying this shuttle if you want to kill your crew.

**Comment by Iamgoofball** [comment]
negative, it's a cheap way to get a shuttle bar

**Comment by KorPhaeron** [comment]
This PR would runtime anyway its not even complete there is no reason to leave it open for 24 hours

**Pull request closed without merging**
