### PR TITLE
remove revenant from dynamic.json

### PR DESCRIPTION
**Pull request by buffyuwu**
## About The Pull Request

removes revenant from dynamic.json, which I think controls midround spawning

## Why It's Good For The Game

revenants are hilariously unbalanced and exist to ruin the fun of others, they need either a gigantic nerf or to be removed altogether

## Changelog
:cl:
del: removes revenant from spawning midround
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
This is absolutely gonna get a do not merge tag. Even if people were on board with this change, this is not the way to go about it. You don't alter the configs via PR, you get the headmins to change the configs.

**Comment by Jacquerel** [comment]
As GPeckman above says, this will have no effect as config is controlled by head admins and is not a copy of the config on the repo. If you want to remove revenant you would have to remove its code. Also if you did that I would close that PR anyway unless you had way better reasoning than what was provided for this one.

Closing in 24 hours just in case anyone has something even slightly insightful to say about it.

**Comment by buffyuwu** [comment]
> As GPeckman above says, this will have no effect as config is controlled by head admins and is not a copy of the config on the repo. Additionally, this removal is actually _adding_ revenants to the game. In the config present they are disabled with a weight of 0, by removing them from the config you are restoring their default >0 weight. If you want to remove revenant you would have to remove its code. Also if you did that I would close that PR anyway unless you had way better reasoning than what was provided for this one.
> 
> Closing in 24 hours just in case anyone has something even slightly insightful to say about it.


https://github.com/tgstation/tgstation/assets/42501819/1f108204-7dfb-4083-8ae9-8d8f165b3b9f

**Comment by Time-Green** [comment]
> > As GPeckman above says, this will have no effect as config is controlled by head admins and is not a copy of the config on the repo. Additionally, this removal is actually _adding_ revenants to the game. In the config present they are disabled with a weight of 0, by removing them from the config you are restoring their default >0 weight. If you want to remove revenant you would have to remove its code. Also if you did that I would close that PR anyway unless you had way better reasoning than what was provided for this one.
> > Closing in 24 hours just in case anyone has something even slightly insightful to say about it.
> 
>  fellas.mp4

Yeah this is joke

**Comment by buffyuwu** [comment]
> > > As GPeckman above says, this will have no effect as config is controlled by head admins and is not a copy of the config on the repo. Additionally, this removal is actually _adding_ revenants to the game. In the config present they are disabled with a weight of 0, by removing them from the config you are restoring their default >0 weight. If you want to remove revenant you would have to remove its code. Also if you did that I would close that PR anyway unless you had way better reasoning than what was provided for this one.
> > > Closing in 24 hours just in case anyone has something even slightly insightful to say about it.
> > 
> > 
> > fellas.mp4
> 
> Jacquerel was nice, but you’re just trying to waste everyones time


https://github.com/tgstation/tgstation/assets/42501819/7a55f0bc-edd3-45de-90a0-a85be40c8210

**Pull request closed without merging**
