### PR TITLE
Server v.1 (Game Option Tweaks)

### PR DESCRIPTION
**Pull request by cmpietz**
Tweaks:
-Set rounds to guaranteed secret extended
-Enabled ghost interaction
-Enabled flypeople, mothpeople, shadowpeople, jellypeople, iron golems, adamantine golems, plasma golems, diamond golems, gold golems, silver golems, uranium golems, abductors, skeletons, zombies, slimepeople, and podpeople as roundstart races
-Disabled hard checks on felinids
-Enabled roundstart human mutations
-Set assistant clothing to grey
-Increased lavaland budget to 100
-Increased space budget to 25
-Enabled integrated circuit printing

### CODE REVIEW

**Comment by PepperPrepper** [comment]
feels bad

**Comment by PepperPrepper** [comment]
@cmpietz  I'm sorry to say it but you've pushed to the wrong repo (unless you wanted to push upstream)

You should make sure that whatever form of git you use is pushing to your repo and not upstream.

**Comment by Couls** [comment]
oh sweet slime people round start

**Comment by Timonkeyn** [comment]
The NERVE

**Pull request closed without merging**
