### PR TITLE
Fixes magazine desc

### LINKED ISSUE #14497: gun magazine desc
the desc of most magazines is still bugged calling it "a box of ammo"
same with speedloaders

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes #14497

### CODE REVIEW

**Comment by Cheridan** [comment]
FUCKING SPAMMER

**Comment by Incoming5643** [comment]
:tanabata_tree:

**Comment by Arquebusier** [comment]
????

**Comment by PKPenguin321** [comment]
travis fucked up

**Comment by Cheridan** [comment]
I don't think it's his fault, I think the spammer fucked things up with travis. Lemme get a handle on it

**Comment by Bawhoppen** [comment]
hurray

**Pull request merged**
