### PR TITLE
buffs mining tools

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

buffs drill damage from pickaxe's 15 to 17, diamond drill from 15 to 19 and jackhammer nerfed from 15 to 10

## Why It's Good For The Game

a drill should do more damage than a pickaxe
jackhammer is griff tool and deservess less power
silver and diamond pickaxes deal more damage than regular pickaxe but drill variants always stay the same??

## Changelog
:cl:
balance: mining drills deal more damage, jackhammer deals less
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
jackhammer used for wallgrief will now serve even better for killing people who don't take kindly to you busting down walls

it should do crowbar-tier damage to mobs, it bashes walls with sonic frequencies adjusted to walls specifically and should do jack shit to mobs. needs to be more of a tool than a hulk-tier griff item + robust weapon

**Comment by nemvar** [comment]
Can we please keep knives better weapons than mining implements? Thanks.

**Comment by Fikou** [comment]
> Can we please keep knives better weapons than mining implements? Thanks.

the reason why knives are good is they are a tiny (or small i dont remember) sharp item that fits in boots, diamond pickaxe and silver pickaxe already deal more damage than knives

**Comment by nemvar** [comment]
Mate, what is the actual reason for this?
> a drill should do more damage than a pickaxe

This is absolute nonsense from a realism perspective. Pickaxes are a better weapon IRL because they have better reach and are easier to maneuver. Drills are specifically designed to destroy immovable objects and are more likely to push a living thing out of their way instead of inflicting mortal wounds.
From a gameplay/balance perspective there is also no reason for this buff, miners don't struggle with having good melee weapons and are already pretty high on the powerlevel scale. This is being made because?????

**Comment by daklj** [comment]
joke pr

**Comment by Ratvar** [comment]
Why It's Good For The Game?

**Comment by ExcessiveUseOfCobblestone** [comment]
remove all pickaxes except in gulag and just use KAs instead smh.

mining tool bloat is real.

**Comment by Tlaltecuhtli** [comment]
sharpness III diamond pickaxe

**Comment by OverlyGeneric** [comment]
time to do 'em dirty like jason did in part 2.

**Comment by Shadowflame909** [comment]
Does anyone even use these tools

bloat

**Comment by bigfatbananacyclops** [comment]
drills would probably become the cheap murder weapon meta if this happens, it isn’t hard to get a drill. 19 is close to the damage a survival knife does. players with experience tend to go for the circular saw because of its damage (or fire axe)

**Comment by Fikou** [comment]
> drills would probably become the cheap murder weapon meta if this happens, it isn’t hard to get a drill. 19 is close to the damage a survival knife does. players with experience tend to go for the circular saw because of its damage (or fire axe)

drill is same damage as silver pickaxe
diamond drill is same damage as diamond pickaxe
they only fit on belt, also not sharp

**Comment by YakumoChen** [comment]
I thought this was a change to mining speed for a second and was confused.

Why are drills supposed to be good weapons even slightly?

**Comment by actioninja** [comment]
This is a bad idea.
Pickaxes are already pretty strong of weapons, and drills are really easy to get. Circular saws are popular "meta weapons" as is and they only do 15.
I agree with that pickaxes should be paired down heavily as well, mining tools besides the KA or plasma cutter are pointless.

**Pull request closed without merging**
