### PR TITLE
New advances in trash-disposaling efficiency: a janitorial blob strain

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
## About The Pull Request

This PR adds a new blob strain into the game that mainly eats garbage and spits it out when attacking. I have some ideas on how to expand on this but I don't know how strong the current mechanic is, so I'm opening the PR up for comments.

## Why It's Good For The Game

More blob strains = More better

## Changelog
:cl: Naksu
add: Added a new blob strain that grows inside the station and eats garbage
/:cl:

### CODE REVIEW

**Comment by Mickyan** [comment]
Beware of The Blob, it creeps
And leaps and litters all
Across the floor

**Comment by Tlaltecuhtli** [comment]
the blob tiles should create miasma

**Comment by habader** [comment]
Just make the nodes act like turrets or soen

**Comment by OverlyGeneric** [comment]
Can it eat people and spew the organs and limbs out at its attackers?

**Comment by YakumoChen** [comment]
This will be interesting if the blob eats, say, a stack of rods.

**Comment by vuonojenmustaturska** [comment]
or a bunch of shards

**Comment by Shadowflame909** [comment]
Call it the Pneumatic Blob

**Comment by ohsshoot** [comment]
introducing the friendly blob, it just eats trash and leaves the crew alone

**Comment by YakumoChen** [comment]
Push lizards and assistants into the blob, they'll be at home with it

**Comment by Shadowflame909** [comment]
your vore code snuck past the orange man. For now...

**Comment by Angustmeta** [comment]
@vuonojenmustaturska Tested this blob. The manual expansion attacks seem to only deal 5 brute on naked humans. Is this intended? 

I also never successfully managed to make it throw an item at someone (tested by eating stuff and then clicking a human in melee), and I never managed to make it steal a melee weapon (wirecutters), neither by attacking the person holding them, or having the person attack the blob with the weapon.

**Pull request merged**
