### PR TITLE
Glove sounds

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
Introduces a default glove sound for equipping and drop/pickup

https://github.com/user-attachments/assets/b3479587-a9fc-4867-9619-c11faeae82ba
## Why It's Good For The Game
muh immersoin
## Changelog
:cl: grungussuss
sound: gloves have equip, drop and pickup sounds.
/:cl:

### CODE REVIEW

**Comment by dessysalta** [comment]
Just an idea: alt click equipped gloves to snap them against your wrist like a mad doctor?

**Comment by DrAmazing343** [comment]
^^^^^^ PLEASE

**Comment by Sadboysuss** [comment]
5 laugh emojis legally obligates me to do this now, *sigh*

**Comment by Sadboysuss** [comment]
I just can't bring myself to come back to this and change it, sorry.

**Comment by dessysalta** [comment]
> I just can't bring myself to come back to this and change it, sorry.

https://github.com/user-attachments/assets/4310b2c9-ed5f-4217-86b5-aa8ab7dc9efc

**Pull request merged**
