### PR TITLE
Move the definition of which node unlocks which circuit component to the component.

### PR DESCRIPTION
**Pull request by Gurkenglas**
Also tweaks SSresearch to support this.

## Why It's Good For The Game

Adding a component should not require one to touch two central files. And this way it's 1 line instead of 5 per printable component.

## Changelog
:cl:
refactor: Circuits components now define their own unlocking research node.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
lmao

**Comment by Time-Green** [comment]
> lmao

Good luck

**Comment by Watermelon914** [comment]
this is more of a code improvement than a refactor.

**Comment by AMonkeyThatCodes** [comment]
calling it an improvement is too far because de-centralizing a centralized system is just going to make it impossible to figure out what nodes do what.

**Comment by Mothblocks** [comment]
@AMonkeyThatCodes Can you explain what you mean?

Would appear to me this significantly lowers surface area.

**Pull request closed without merging**
