### PR TITLE
cap on how many people you can transform as a ling

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Lings can now transform 3 people max. This number increases with every ling they absorb.

## Why It's Good For The Game

#49384 was really radical, but someone transforming the entire crew is just annoying grief. Lings need to moderate a bit better who they transform.

Transformation Sting might be decreased to two points as a result, open to suggestions.

## Changelog
:cl:
balance: Transformation sting can now only transform 3 people, this number goes up with each ling you absorb. 
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
should probably fix my master

**Comment by kriskog** [comment]
Yeah, imagine being an antag and griefing people with looking different

**Comment by wesoda25** [comment]
¯\_(ツ)_/¯ its annoying my guy

**Comment by Time-Green** [comment]
Make it curable instead? Capping it feels kinda random. You could very well make the sting give the person a mutation that could be removed by a geneticist, wich is what most people try to do anyway.

**Comment by wesoda25** [comment]
actually might have had my blackout glasses on this pr is bad

station should really just police it themselves

**Pull request closed without merging**
