### PR TITLE
Nerfs Kevinz000

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Based on player feedback I think this is a critical balance decision

### CODE REVIEW

**Comment by kevinz000** [comment]
PLAYER REFERENCE!!!

**Comment by kevinz000** [comment]
NO!!!

**Comment by lzimann** [comment]
just remove his +sound lol

**Comment by KorPhaeron** [comment]
This is a more long term solution

**Comment by kevinz000** [comment]
SELF REEOOPPPEEEEEENNNNNN!!!!!!!

**Comment by KorPhaeron** [comment]
What if he gets headmin some day we need to plan ahead

**Comment by Aloraydrel** [comment]
Look i'm all for kevinz000 but we cannot give him the +sound codes

**Comment by TrustyGun** [comment]
merge posthaste

**Comment by InsaneHyena** [comment]
Not gonna lie, former Mekhi supporter here. This is fucking hilarious watching him crash and burn. But in all seriousness we can't let this guy get the MIDI codes.

**Comment by AnturK** [comment]
I agree but this goes into config.

**Pull request closed without merging**
