### PR TITLE
Removes standard borgs zipties

### PR DESCRIPTION
**Pull request by anconfuzedrock**
:cl: rock
:del: standard borgs need to be hacked to gain zipties.
/:cl:
I think this is better than reducing flash stun time or fucking up with slaps being added somehow

### CODE REVIEW

**Comment by Kraseo** [comment]
😅

**Comment by uraniummeltdown** [comment]
is this because of the "Lifeweb Baron" borg

**Comment by anconfuzedrock** [comment]
yes but thats irrelevant ok

**Comment by anconfuzedrock** [comment]
gunhog would you rather I nerf flash stun time because you are basically mad because I am stopping standards from being secborgs here

**Comment by RandomMarine** [comment]
Borgs need to stop being sad jokes. While I don't think standards should have cuffs, this is a step in the wrong direction.

**Comment by anconfuzedrock** [comment]
"while I don't think standards should have cuffs, you shouldn't remove standard cuffs"
other option is to reduce the flash stun or accept standards as our new secborgs. which one do you want?

**Comment by Anonmare** [comment]
You kind of need default stuns and/or restraints in order to do the malf robot army objective. The robo factory will only convert living things (and you better pray the person you're dragging isn't salty enough to go braindead) and robots made from a converter do not start off as hacked. 

And if the robo console is RIP then any borgs made from it are going to be extremely ineffective (they only get the 5-7.5K power cells) and the default loadouts are abysmal for combat/stunning besides the flash.
And flashes can burn out randomly so they're not a reliable way of keeping someone down while you're taking them to a converter.

I figured the flash buff was a way of actually making it possible to do that objective without having to rely on people throwing themselves into the converter on purpose.

**Comment by anconfuzedrock** [comment]
fair point, I'd give engiborgs cable ties when emagged but people would be mad at me anyway.

**Comment by KorPhaeron** [comment]
Have you considered putting on any of the thousand items that block flashes, or failing that, not getting hit in melee?

**Comment by anconfuzedrock** [comment]
aight cable ties didn't work out this did though

**Comment by Armhulen** [comment]
rocksux

**Comment by coiax** [comment]
The only reason you pick standard borg is for cableties and the emagged esword.

**Comment by KorPhaeron** [comment]
git gud

**Pull request closed without merging**
