### PR TITLE
improves VERY RAGIN' BULLSHIT MAGES

### PR DESCRIPTION
**Pull request by Iamgoofball**
based on hornygranny and I's testing that one round

this is done with studies to prove this is how you meme it up

improves ragin' mages

makes admins get laid when they use it

### CODE REVIEW

**Comment by PKPenguin321** [comment]
heyooo

**Comment by Shadowlight213** [comment]
THIS PR HAS IMPROVED MY SEX LIFE BY 69%!

**Comment by Iamgoofball** [comment]
Razharas's sex life also improved by 420% when he hit the merge button.

**Comment by duncathan** [comment]
0 + 420% is still 0 :^)

**Comment by Iamgoofball** [comment]
We didn't ask for your sex stats.

**Pull request merged**
