### PR TITLE
Going stealth mode now drops your orbiters, and blocks people from orbiting you. 

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request

Going stealth mode now drops your orbiters and blocks you from being orbited.

As part of an exchange program between me and @Timberpoes TODOs.

## Changelog

:cl:
admin: Going stealth mode now drops your orbiters and blocks you from being orbited.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
is the Toggle Orbability verb available to players?

**Comment by Mothblocks** [comment]
No reason it can't be made into a ghost verb now that I think about it

**Comment by Mothblocks** [comment]
Dunno @Timberpoes requested it, if he has a good answer

**Comment by JohnFulpWillard** [comment]
if any player has this ability, admins should be able to observe them regardless of it.

**Comment by Kubisopplay** [comment]
But that will stop me from annoying admins by orbiting them for entire round :(

**Comment by Timberpoes** [comment]
The original intent was to make sure stealthmin could drop existing observers and block new ones. For very, very obvious reasons.

Prior to this you'd have to corrupt the state of your orbiter component (set the list of orbiters to a string or something that'll runtime on += operations with datums)

I figured if we're adding that functionality anyway, might as well extend it to an admin verb too. Any admin can just add the trait anyway through VV.

Sometimes I don't want people orbitting my ghost when setting up for events, when tracking players as part of tickets, when I have stalkers who just orbit me the second I observe, etc. However, I also don't want the side effects of steathmin relaying ahelps, hiding from awho etc.

It doesn't have to be a verb. I can just add the trait via VV.

**Comment by Mothblocks** [comment]
I'll gut it later then as much as I want to hear admin trainers say orbitability

**Comment by Bawhoppen** [comment]
This has never been a problem before despite the server running for over a decade, and adds another increment towards fostering a culture of exclusivity, prerogative, and even to some degree impunity among admins. Strongly oppose.

**Comment by Mothblocks** [comment]
To what? The toggle orbitability verb is getting removed when I get the chance, and stealth mode is supposed to make you completely disappear.

**Comment by Bawhoppen** [comment]
Well, it was unclear exactly what state this was going to be in. As Timber said, you'd be leaving in the option to var-edit, which is semantically the same as leaving the verb in for admins (which will get very frustrating very fast for players as admins do so). 
Either way though, I do not believe the intended existence or role of stealthmin has ever been for them to be totally invisible. Yes, it hides your appearance from the adminwho, but as far as I'm aware the primary function was just to watch for people who might only be willing to break the rules if they see no admin only (or occasionally was to cover up if you ever had perceived a conflict of interest in ahelps). Its purpose was never to hide that you exist totally, which limiting orbits does significantly. I cannot think of a single legitimate scenario where it is justifiable to deny the playing public the ability to observe the admins and hold them to account (remember, this is just **orbits**, not anything to do with IPs or sensitive info or anything like that). This is a social game and everyone is present in it, admins included... If it's mainly about being bothered by people watching secret events, then that's not really a reasonable cause for this. 
Adding simplified functionality like I believe will also sizably increase the number of stealthmins in a given round... which is bad for reasons I'm sure you can guess.

**Comment by Mothblocks** [comment]
Only thing I want to take care to comment on is this:

> As Timber said, you'd be leaving in the option to var-edit, which is semantically the same as leaving the verb in for admins (which will get very frustrating very fast for players as admins do so).

It's a trait, so it being VV-able is included in the package. It would be hostile to administration to try and limit VV tooling for something not security impactful like this.

**Comment by Timberpoes** [comment]
@Bawhoppen You can confirm your conspiracy theories that stealthed admins are breaking all the rules and running roughshod over admin conduct. Go to the public game logs and look at all of the publicly logged admin actions that you are not doubt fully aware aware of from reading our public open source game code and noting that stealth mode doesn't change logging.

I think my point is made.

We do still have hackers whom are able to see ghosts and stealth mode is one of the tools admins use to try and counter that. Hackers, multi-keyers, metacommers and evaders.

I don't think you grasp the full scope of what admin teams occasionally have to investigate and what tools bad actors have to defeat those attempts.

I have absolutely no interest in requiring any contributor to limit the admin team's capability to administrate the servers on behalf of conspiracy theories.

**Comment by Mothblocks** [comment]
I keep forgetting to update this I'll do it later

**Comment by Mothblocks** [comment]
*burp

**Pull request merged**
