### PR TITLE
New crates

### PR DESCRIPTION
**Pull request by MTandi**
crates_flat

## About The Pull Request

Updates the sprites of existing crates and adds some new ones.

TODO:

- [x] Make syndicrate sprite work with its dual lock
- [x] Map for bitrunning, robo, etc.
- [x] Specify the new crates in cargo orders

## Why It's Good For The Game

More crates variety.

## Changelog

:cl:
image: Crates got new sprites
image: Added more crate styles
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
swag

**Comment by mc-oofert** [comment]
though i feel the O2 crate might be a little too bright?
same with security crate

**Comment by MTandi** [comment]
> though i feel the O2 crate might be a little too bright? same with security crate

I got the colors from the oxygen tanks and the security uniform. Will check if too bright and tune down if they are.

**Comment by Profakos** [comment]
Looking fresh and cheerful, less washed out and grungy. Though the lower halves outlines might be a bit too bright, I would only keep only the lid's bright outline. Might be just me though.

**Comment by Jacquerel** [comment]
Looking good
I think though that the syndicate crate with the two locks you have resprited had that because it requires two people to open, which is a detail lost here

**Comment by OverwatchVoice** [comment]
They look like crates, which is already better than what we've got right now, I like

**Comment by SyncIt21** [comment]
Love the ice in the new freezer crates. cool vibes

**Comment by AseFantome** [comment]
Good job

**Comment by MoffNyan** [comment]
They're so cute!! I love the freezer crate with the ice, and I wanna take it to the beach gateway for a picnic! Also the ridges on the military and swat crates look amazing
I also worry that the lines might be a little too bright/low contrast but it's hard to tell without seeing it in game, overall awesome

**Comment by OmegaDarkPotato** [comment]
Yoooo!! These look really nice, and I especially appreciate what you've done for medical's crate. Back to white and baby blue medical, here we go!

**Comment by Thelolswat** [comment]
This looks really good, I appreciate that you went the extra mile when making the crates easy to identify and colorful without having to sacrifice elsewhere

**Comment by kinneb** [comment]
these look amazing

**Comment by iwishforducks** [comment]
god damn these are good.

im not sold on the nuclear crate with the hazard stripes around the edges- but im not really sure what else it could be. regardless, it still looks good!

**Comment by Wallemations** [comment]
Might wanna work on that nuke crate, but this is otherwise a very solid resprite
Has the best of current and previous crate sprites, nice work

**Comment by SomeoneYouProbablyKnow** [comment]
Honey wake up it's time for your yearly crate resprite. (they look good)

**Comment by Timberpoes** [comment]
Crisp. Clean. Stylish. I prefer this perspective too. I like 'em.

**Comment by Livrah** [comment]
Amazing sprites.
Soul/10

**Comment by carlarctg** [comment]
change....good?

🎉

**Comment by junkgle01** [comment]
loving the mining and bitrunning crates

**Comment by LSommers** [comment]
Further proof that you can keep SOVL even with new sprites..... 

Jokes aside, thank you so much for making a crate resprite to fix the uh, current issue. The current issue that we all know about but can't really address lest we poke a hornet's nest. The crate issue. 

Love the restoration of the freezer crate to "NanoTrasen is so cheap it's just a goddamn beach cooler" instead of the tanning bed we have right now. Fantastic work as always.

**Review by DATA-xPUNGED — CHANGES_REQUESTED** [review]
I wish they leaned a bit more on the current crate's dimensions (except the "military" ones because this shape is more accurate to their real life counterparts) but other than this not-a-huge-deal issue, some of them look a tad too bright.

**Comment by EricZilla** [comment]
They look a bit plasticy but that's only a lore issue, they look very tasty

**Comment by LSommers** [comment]
> They look a bit plasticy but that's only a lore issue, they look very tasty

this man eats crates
cargo hates him!
learn his secret for only 299 credits

**Comment by ChungusGamer666** [comment]
this PR is blessed

**Comment by Bawhoppen** [comment]
I still prefer the original crates (but 3/4ths-ified), but if we can't have those back, these are a vast vast improvement over the current ones :thumbsup: x :100:

**Comment by MTandi** [comment]
> I wish they leaned a bit more on the current crate's dimensions (except the "military" ones because this shape is more accurate to their real life counterparts) but other than this not-a-huge-deal issue, some of them look a tad too bright.

Like this?

image

**Comment by mc-oofert** [comment]
> Like this?
> cool image

i think the bottom one is cooler

**Comment by Dorsisdwarf** [comment]
Delighted to see white colouration returning to the crate spriteset instead of a colour range that maxes out at dull grey midtone

**Comment by Fikou** [comment]
can you show how they look ingame?

**Comment by DATA-xPUNGED** [comment]
> > I wish they leaned a bit more on the current crate's dimensions (except the "military" ones because this shape is more accurate to their real life counterparts) but other than this not-a-huge-deal issue, some of them look a tad too bright.
> 
> Like this?
> 
> image

Yeah, the top ones, look slick. This is all just a suggestion though

**Comment by Isratosh** [comment]
I am a huge fan of these, specifically how much lighter they are and easier to differentiate (please don't make them darker). I really like the stripes and I think they match really neatly to our current locker sprites.

**Comment by KathrinBailey** [comment]
let's not forget that going taller than 32x32 also means it's easier to click on the lid to close the crates instead of picking up something instead

**Comment by MTandi** [comment]
> can you show how they look ingame? 

image

**Review by Ghommie — APPROVED** [review]
Now, these are the actual crates people wanted to begin with! I'd merge without a second tought, if it weren't that I'm not a sprite-tainer.

**Comment by TheVekter** [comment]
AH CHRIST HERE WE GO AGAIN

Actually these slap severely, well fucking done. I greatly prefer the lighter shading and how much easier they are to read than our current sprites.

**Review by Twaticus — APPROVED** [review]
🙏

**Comment by SimplySmiley123** [comment]
Yeah no these are good.
Better looking _and_ readable at a glance.

**Comment by MTandi** [comment]
> also what if you made the locked stuff an overlay instead of a whole different sprite?

The chests sprites are broken right now when it comes to interaction with locks and airlock electronics.

Previous PR made the lock follow the lid, while before that, every chest had a place for the lock on their sprite, without providing the framework for conversion between secure and non-secure crates.

This resulted in the following issue:

dreamseeker_3LSQrgmM01

I noticed this only later into this PR. And it needs some complex solution with an overlay as you said. I'll leave it for a separate PR or for someone else to resolve.

**Comment by EricZilla** [comment]
Just have the green and red overlays add the lock to the crate, no need for new overlays, just make the current ones more in depth

**Comment by ArcaneMusic** [comment]
Brings back some soul. I like it!

**Comment by HerCoyote23** [comment]
Looks good, but the security crate looks too syndicate-y to me. It's pretty easy to mistake that S to be for syndicate, rather than security. Maybe replace it with an NT to make it clear it's a sec not synd crate?
Also the double locking synd crate would look better with two locks imo, like it has at the minute.

**Comment by nikothedude** [comment]
image
holy shit dude this is the most celebrated pr ive ever seen

**Comment by Bawhoppen** [comment]
> image holy shit dude this is the most celebrated pr ive ever seen

It's relatively easy to make a new highly celebrated PR when it's reversing the outcome of a previous highly despised PR

**Pull request merged**
