### PR TITLE
Revert "Revert "[READY] Easy hosting of roundend sounds (#33618)""

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/tgstation#33908

wtf why'd you revert this

### CODE REVIEW

**Comment by coiax** [comment]
Because you made a PR that broke things, and then when people complained, then said it was their fault for not fixing the mess you made.

**Comment by ninjanomnom** [comment]
try reading what was said on the revert

**Comment by MoreRobustThanYou** [comment]
merge this when someone is able to fix the folder structure then

**Comment by Cyberboss** [comment]
This PR:

- STILL doesn't allow for updating without breaking the sounds
- STILL is illegally licensing the title music

Thanks for playing please try again

**Pull request closed without merging**
