### PR TITLE
Emagging the anomaly compressor will eject the bomb the next time someone tries to use it.

### LINKED ISSUE #66635: Anomaly refinery can eject live bombs
Reporting client version: 514.1583

## Round ID:
[182417](https://scrubby.melonmesa.com/round/182417)

## Testmerges:
- [Makes it possible to speed up the tram](https://www.github.com/tgstation/tgstation/pull/66348)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Keep mutating filenames when the cdn is disabled midround.](https://www.github.com/tgstation/tgstation/pull/66550)
- [Remove data/ from /datum/asset/json url mapping](https://www.github.com/tgstation/tgstation/pull/66549)

## Reproduction:

This is a race condition so some speed/timing is necessary.  I suspect the original case I witnessed more likely had two people hitting the button in a short space of time, but I managed to reproduce it with just myself.

Spawn a /obj/machinery/research/anomaly_refinery
Spawn a /obj/item/raw_anomaly_core/pyro
Spawn a /obj/effect/spawner/newbomb/tritium   (( /plasma one seems harder to trigger.  or i just had bad luck, failed with plasma 3 times, worked first time with trit.  but also such are race conditions.  ))
Shove the anomaly core and bomb into the refinery
Spam the implode button

If you get the timing right you can trigger this:

> You insert the tank transfer valve into the anomaly refinery
> You insert the raw pyro core into the anomaly refinery.
> The anomaly refinery beeps, "Beginning compression test. Opening transfer valve."
> ADMIN LOG: Bomb valve opened in Thunderdome Arena (168,48,1) (JMP)
> 
> The bomb's most recent set of fingerprints indicate it was last touched by Iain0/(Bob Stange)(?) (FLW)
> 
> The anomaly refinery beeps, "ERROR: Transfer valve malfunctioning. Items ejected."
> The anomaly refinery beeps, "ERROR: Missing equpment. Items ejected."
> ADMIN LOG: Explosion with size (Devast: 5, Heavy: 10, Light: 20, Flame: 0) in Thunderdome Arena (168,48,1) (JMP). Possible cause: the oxygen tank. Last fingerprints: *null*(?) (FLW).
> Your eyes sting a little.
> Bob Stange has died at Thunderdome Arena.
> You have died. Barring complete bodyloss, you can in most cases be revived by other players. If you do not wish to be brought back, use the "Do Not Resuscitate" verb in the ghost tab.
> You feel slightly disoriented. That's normal when you're just a brain.

And seen originally in round 182417

> (F) [Common] The anomaly refinery beeps, "Beginning compression test. Opening transfer valve."
> ADMIN LOG: Bomb valve opened in Ordnance Mixing Launch Site (134,75,2) (JMP)
> 
> The bomb's most recent set of fingerprints indicate it was last touched by Madrus/(Key Phillip)(?) (FLW)
> 
> (F) [Common] The anomaly refinery beeps, "ERROR: Transfer valve malfunctioning. Items ejected."
> ADMIN LOG: Explosion with size (Devast: 1, Heavy: 3, Light: 7, Flame: 0) in Ordnance Mixing Launch Site (134,75,2) (JMP). Possible cause: the plasma tank. Last fingerprints: ahmadsan/(Derek Conrad)(?) (FLW).
> (F) [Common] The tachyon-doppler array states coldly, "Explosive disturbance detected."
> (F) [Common] The tachyon-doppler array states coldly, "Epicenter at: grid (134, 75). Temporal displacement of tachyons: 0 seconds."
> (F) [Common] The tachyon-doppler array states coldly, "Factual: Epicenter radius: 1. Outer radius: 3. Shockwave radius: 7."

The co-ordinates 134,75,2 are the (former) location of the anomaly refinery on metastation.

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About The Pull Request
Fixes #66635 and moves the behavior behind emagging. It's funny, but probably shouldn't be something you can do by accident simply by spamming the start compression button.

## Why It's Good For The Game
Canonizes funny behavior that would otherwise get squashed in the name of gbp.
One more part of the station for antags to sabotage. Optimally this would be near every part of the station, but we can work on that.

## Changelog

:cl:
fix: Spamming the start compression test button will not make the anomaly refinery eject a live TTV.
add: That's what the emag is for.
/:cl:

### CODE REVIEW

**Comment by exymian** [comment]
i love you for this lmaoo

**Comment by antropod** [comment]
I have seen people nuke themself

**Comment by CourageTheCat** [comment]
holy FUCK this is terrifying

**Review by tralezab — APPROVED** [review]

**Comment by tralezab** [comment]
beware the bug to feature pipeline

**Pull request merged**
