### PR TITLE
Sentinel's Compromise will no longer heal toxin damage on slimepeople

### PR DESCRIPTION
**Pull request by ChangelingRain**
The downside is supposed to be... a downside, and not something you can avoid with a bit of xenobio work. Clockwork floors will, of course, still heal the toxin damage done.

### CODE REVIEW

**Comment by Kraseo** [comment]
how did i not think of this

**Comment by ChangelingRain** [comment]
I know at least a few people commented on this so ???

**Comment by AnturK** [comment]
This should probably be a force argument on adjustX procs.

**Comment by SgtxRootbeer** [comment]
So if I run around with a air tank with a 50/50 plasma oxygen mix, I can compromise all I want... Gotcha.

**Comment by ShadowDeath6** [comment]
Slimepeople being better plasmamen than plasmamen

**Pull request merged**
