### PR TITLE
Prevents APC placing in large areas to stop lag

### LINKED ISSUE #9905: LAG: Placing an APC frame on the asteroid can lag out a server for well over an hour.
After attempting to place down the APC, the entire server froze.

### PR DESCRIPTION
**Pull request by maartenberg**
Fixes #9905 
The exact limit is 8192 tiles, 1/8th of a z-level, is that big enough?

Also fixes some grammar errors in the APC error messages

### CODE REVIEW

**Comment by Aranclanos** [comment]
remove areas REMOVE AREAS

**Comment by RemieRichards** [comment]
>remove areas

yeah, like we can work around them @Aranclanos

**Comment by Aranclanos** [comment]
also what cause the lag?

**Comment by RemieRichards** [comment]
given it's:
1. About power
2. About areas with large sizes

SURELY it's powernets.

**Comment by spasticVerbalizer** [comment]
@Aranclanos 
The lag is caused by get_apc(), it checks every turf in the related area for an apc, and with area sizes around 30032 in the asteroid it takes a while

**Comment by Supermichael777** [comment]
there is surely a less autistic method of doing that.

**Comment by RemieRichards** [comment]
I'm working on a new ```get_apc()``` that *shouldn't* (trademark, patent pending, all rights reserved) lag on areas of any size.

**Comment by spasticVerbalizer** [comment]
@RemieRichards Should I close this then?

**Comment by RemieRichards** [comment]
@spasticVerbalizer not until I've confirmed it works, rofl.

**Comment by RemieRichards** [comment]
@spasticVerbalizer it works, 0 lag, I did it reddit.
Closing this now.

**Pull request closed without merging**
