### PR TITLE
Makes plasmaman envirosuits actually impermeable.

### LINKED ISSUE #61423: Viruses that spread via touch can be spread through a full Plasmaman Envirosuit
## Reproduction:

Playing as a plasmaman virologist, and I gave myself an Inorganic Biology virus allowing the effects of the virus to effect me. Transmission stat was at 8, allowing the virus to spread via touch.

Upon grabbing a monkey, I noticed via the Health HUD that the monkey was instantly infected, despite my plasmaman wearing a full envirosuit (helmet, gloves, suit) which is supposedly fully sealed as to not cause a fire/leak of plasma from the suit. So how exactly does this make sense?

I haven't played around with touch viruses as a human to notice this, but either this is just an issue regarding viral protection from plasmamen gear, or maybe this issue affects every instance with protective clothing. Dunno. I'll either update this issue or make a new one if I find out.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
Fixes #61423 

## About The Pull Request

Plasmaman envirosuits now have a permeability coefficient of 0.05, making them resistant to touch diseases.
This is to fix the fact that a fully impenetrable envirosuit with 100% airborne disease resistance somehow lets diseases pass right through if its via touch.

Also you can tell its a consistency fix when the gloves already have a 0.05 coefficient.

## Why It's Good For The Game

Envirosuits actually protect you from diseases now, even if in most cases this can be a negative as infecting plasmamen requires inorganic biology.

## Changelog

:cl:
fix: Plasmaman envirosuits now have impermeability on them.
/:cl:

this is like the weird middle point between a balance change and a fix because it changes balance a bit but its also a clearly intended thing that was missing

### CODE REVIEW

**Comment by ATH1909** [comment]
sad, I like being a typhoid mary as a plasmaman with an inorganic biology + vomiting disease

**Comment by optimumtact** [comment]
this was definitely for balance reasons

**Comment by GuillaumePrata** [comment]
0.05 for gloves is quite common, the insulated gloves have it and the latex ones that are easily accessible go even lower at 0.03.
Now for uniforms, the standard is 0.5 with the medical uniforms.
Having these uniforms be that low make them work as a quite efficient bio suit with no slowdown while you can keep another set of armor on top of it.
The plasmamen uniform already is an upgrade above most others on the station. Having it at 0.5 would be a good change, a plasmaman doctor is worse against infections than a skirt doctor and this is quite silly...

**Comment by CRITAWAKETS** [comment]
in general this is a bad idea to be honest

**Pull request closed without merging**
