### PR TITLE
[s] Censor the right BSQL call

### PR DESCRIPTION
**Pull request by Cyberboss**
Das my oof @MrStonedOne

### CODE REVIEW

**Comment by Jordie0608** [comment]
Tfw you can't merge a security fix because github has been semi-down for 14 hours and when the PR isn't busy slipping in and out of existence it fails to ever resolve mergeability checks.
ok spidey

**Comment by Arianya** [comment]
Do we get to apply fuck up the year to this after its merged and I can openly talk about what this did?

**Comment by Iamgoofball** [comment]
Can we declare this Schrodinger's PR

**Comment by Cyberboss** [comment]
No you can talk about it, only people with raw log access can see it and I guess mso already changed it

**Comment by SouDescolado** [comment]
Github is borked

**Comment by Arianya** [comment]
So for those not in the loop:

This one change meant that the raw logs (which actually aren't "raw", they do have *some* censoring) which the admins access we're leaking the connection info and password for the MySQL database. Which theoretically means anyone with access to those logs could theoretically fiddle with the db.

Fun stuff.

**Comment by Arianya** [comment]
(They wouldn't actually be able to for a variety of reasons but still not good info to leak)

**Comment by Cyberboss** [comment]
GitHub is still shit, just look at the commit

**Comment by Cyberboss** [comment]
You can talk about it I guess, only people with access to the raw logs can
see it

**Comment by Cyberboss** [comment]
^ Sent those emails hours ago

**Pull request merged**
