### PR TITLE
c4 now takes 3 seconds instead of 5 to plant

### PR DESCRIPTION
**Pull request by 4dplanner**
:cl: 4dplanner, robustin
fix: c4 has always taken 3 seconds to plant, and you are not allow to believe otherwise
/:cl:

His is missing stuff, and making the same PR over and over again does nothing

closes #27651

### CODE REVIEW

**Comment by 4dplanner** [comment]
https://www.youtube.com/watch?v=eBDi0iM2kcU

**Comment by 4dplanner** [comment]
I am also going to refactor c4 a little later, because that code is shit

**Comment by Cyberboss** [comment]
Why is the github diff lying to us.

**Comment by Robustin** [comment]
I understand enough to say that you merging the c4 files in middle of my PR is the cause @Cyberboss

**Comment by 4dplanner** [comment]
I believe the reason is that robustin was replacing a line by itself, so it used his version of the previous history to make the diff - and his version was from way back.

**Comment by Iamgoofball** [comment]
can we get a speedmerge on this @Cheridan 
this has been approved and merged 4 times, but git keeps fucking up and reverting it

**Comment by ChangelingRain** [comment]
If it's outdated git should fucking throw a merge conflict warning or something.

**Comment by 4dplanner** [comment]
@iamgoofball - it was never reverted, what happened was:
robustin changes grenade/plastic
grenade/plastic/c4 is added
robustin did not change plastic/c4, and it does not show up on his repo because outdated
Because he submits the same PR multiple times, the diff shows him changes the value for grenade/plastic from 50 to 30, but it is already at 30 (I checked)

**Comment by 4dplanner** [comment]
And I believe no merge warning was given because there were no conflicts, because it wasn't actually changing anything past the first one

**Comment by Iamgoofball** [comment]
fuck

**Pull request merged**
