### PR TITLE
[TESTMERGE] New wall sprites

### PR DESCRIPTION
**Pull request by Core0verload**
This PR changes regular and reinforced wall sprites. New ones are made by MR_R.
walls
I want to see it testmerged to measure how negative the player feedback would be.

### CODE REVIEW

**Comment by Zilenan91** [comment]
Oh wow nice :+1:

**Comment by ChangelingRain** [comment]
Immediate issue; does not include rusted walls.

**Comment by Core0verload** [comment]
Rusted walls are unused, and stupid, and this is a test merge anyway.

**Comment by PKPenguin321** [comment]
:mask: oh god **HURRRRRK** kill it

**Comment by Zilenan91** [comment]
They're all over Dreamstation

**Comment by ChangelingRain** [comment]
Also revenants produce rusted walls, and I think efficiency and one or two of the various ruins use them.

**Comment by PKPenguin321** [comment]
PLEASE don't merge this jesus christ i want to die looking at this

**Comment by GunHog** [comment]
I prefer Hippie's walls myself.

**Comment by Bawhoppen** [comment]
this is so horribleeeeeeeeeeeeeeeeeeeeeeeee
worst pr of the week cumfirmed

**Comment by Incoming5643** [comment]
I don't get why they have to change. I'm quite taken with our minimalist walls, it helps to draw the eye away from them and towards the rooms themselves.

**Comment by TechnoAlchemisto** [comment]
not smooth

**Comment by TrustyGun** [comment]
these could look way better if you remove the lines between tiles

**Comment by Dorsisdwarf** [comment]
This looks bad, like all the servers where every goddamn walll sprite is a mess of boxes

**Comment by WJohn** [comment]
These actually look pretty good, though I'd say remove the little connecting lines between smooth walls, as that breaks things up unnecessarily.

**Comment by Aloraydrel** [comment]
Eww

**Comment by optimumtact** [comment]
Without rusted walls :-1: 

With rusted walls :neutral_face:

**Comment by Fox-McCloud** [comment]
Agreed with @WJohn 

Remove the connecting line and add in rusted walls, then this probably will be decently nice.

**Comment by Metacide** [comment]
I think these look great as-is. Rwalls particularly, the current sprites are terrible.

**Comment by RemieRichards** [comment]
>I think the current sprites look great as-is.  these look terrible.

**Comment by Bawhoppen** [comment]
yes these look worse than hippie's even

**Comment by Dorsisdwarf** [comment]
I mean, the Rwalls are just about okay, but the normals look so bad

**Comment by PKPenguin321** [comment]
These are poopoo peepee garbage remove this PR from the face of the earth

**Comment by Dorsisdwarf** [comment]
This is probbably big enough a change to warrant an actual player poll, with merge/close dependent on opinion.

**Comment by Iamgoofball** [comment]
@dorsisdwarf No, we should not ever give them the thought that polling and democracy is involved in the PR process. As soon as you introduce that element all productivity drops by 80%. Just ask any coder for a democractic codebase and ask how annoying it is to code something and have your feature or sprite you worked long and hard on denied because of votes that can easily be spoofed, instead of actual feedback on the feature or the code quality.

**Comment by Dorsisdwarf** [comment]
@Iamgoofball What code quality? This is an unpopular sprite PR you immense mongoloid and it seems like the sort of thing that should have a forum poll in order to prevent Massive Shitstorm 2556

**Comment by Iamgoofball** [comment]
Bikeshedding.

**Comment by PKPenguin321** [comment]
Please close this pr

**Comment by TrustyGun** [comment]
just remove the connection lines

it will make this pr 100% better

**Comment by Zilenan91** [comment]
I like the sprites better :+1:

**Comment by Razharas** [comment]
I agree old sprites are better

**Comment by PKPenguin321** [comment]
Based raz

**Pull request closed without merging**
