### PR TITLE
Wizard can't cast shout or whisper spells when he is unable to speak

### PR DESCRIPTION
**Pull request by AutomaticFrenzy**
[Changelogs]:

:cl: 
tweak: Wizard cannot cast spoken or whispered spells while mute
/:cl:

[why]: # Before, only the muzzle stopped the wizard from casting spells with spoken components, now anything that stops speaking, like chemicals or surgery, will stop those spells

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by KingPhilipIII** [comment]
Chemistry powercreep. Now memechems will include silencing components in the rare event the wizard doesn't immediately die.

**Comment by Mercenaryblue** [comment]
Chemistry was always the biggest counter to wizard anyway. I approve.

**Comment by XDTM** [comment]
I can't wait for someone with a voice of god telling the wizard to SHUT UP

**Comment by AutomaticFrenzy** [comment]
What do people think about touch attacks with spoken components? Currently they aren't blocked because I only block on casting the spell with words, not activating the touch attack, but it'd be an easy change

**Comment by XDTM** [comment]
Should be blocked, the EI NATH is a crucial part of the spell.

**Comment by Firecage** [comment]
Mmm, I am kind of conflicted. I know I did enjoy that one round with the Mime Wizard.

**Comment by AutomaticFrenzy** [comment]
Well, Mime wizard can still cast spells with "none" or "emote" style invocations

**Comment by AutomaticFrenzy** [comment]
Fixed touch spells being castable when mute, but made me find this issue #31039

**Comment by FantasticFwoosh** [comment]
Attach muzzle, parade the defeated and tied wiz to security and gloat triumphantly.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
