### PR TITLE
Fixes a really dumb mistake with Delta atmos that i'm surprised no one's found for this long

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

<details>

<Summary> Removes these pipes on the left side hidden under grilles </summary>

image

</Details>

## Why It's Good For The Game

Shouldn't be there

## Changelog

If no one noticed for this long no one will need a CL

### CODE REVIEW

**Comment by msgerbs** [comment]
Copypasta moment

**Comment by Mothblocks** [comment]
@LemonInTheDark Anything we can check on those pipes in CI for?

**Comment by LemonInTheDark** [comment]
you could ci for pipes with no inputs connected, but that would improperly throw if a mapper made something "destroyed"
It's not a bug, more of a mapping mistake. Not sure how you'd 100% catch it

**Review by san7890 — APPROVED** [review]
If #65866/#65576 is anything to go by, it's that those grilles over reinforced walls make it REALLY hard to see some of this sorta stufff.

**Comment by msgerbs** [comment]
> If #65866/#65576 is anything to go by, it's that those grilles over reinforced walls make it REALLY hard to see some of this sorta stufff.

Why do those even exist? Is it supposed to make them tougher somehow?

**Comment by san7890** [comment]
> > If #65866/#65576 is anything to go by, it's that those grilles over reinforced walls make it REALLY hard to see some of this sorta stufff.
> 
> Why do those even exist? Is it supposed to make them tougher somehow?

Holdover from Box? They look cool, maybe it's like meteor proofing since the meteor will exert it's destructive force on the grilles and not immediately breach and kill the entire oxygen supply (or would at least require two meteors to do so)??

**Comment by Mothblocks** [comment]
> you could ci for pipes with no machines connected, but that would improperly throw if a mapper made something "destroyed" It's not a bug, more of a mapping mistake. Not sure how you'd 100% catch it

Sounds like those could be a subtype you explicitly opt into, since apparently this has happened quite a few times before.

**Pull request merged**
