### PR TITLE
Using fishnets will make fishing easier

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Wearing any of the three kinds of fishnet socks options will lower fishing difficultly equivalent to that of using bait.

image

Note that this admin log will not be in the final version, its just there to show me that it worked.

image
## Why It's Good For The Game

Fishnets are a practical tool for catching fish, why else would they be called **fish** **nets**?
## Changelog
:cl:
add: Wearing fishnets will lower fishing difficulty
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
I love this but I’m not convinced selecting a piece of underwear should ever give you an in-game advantage, because why ever wear anything other than fishnets?

**Comment by Paxilmaniac** [comment]
"Because why ever wear anything other than fishnets" is the funniest thing I have seen someone unironically say.

**Comment by PCPort** [comment]
> why ever wear anything other than fishnets?

I refuse to believe that this wasn't written by Diavolo
diavolo-reveal

**Comment by Farquaar** [comment]
Instead of giving you a bonus to fishing, why not just display a silly message instead? Something like "hey, not **that** kind of fishnets!" or something similar

**Comment by JohnFulpWillard** [comment]
we're all waiting for the next episode of femboy fishing you're not special

**Comment by Sealed101** [comment]
killjoys

**Comment by Mothblocks** [comment]
why ever wear something other than fishnets

**Pull request closed without merging**
