### PR TITLE
Quirk limit now only applies to positive quirks

### PR DESCRIPTION
**Pull request by Cyberboss**
Hardmode unlocked

:cl:
tweak: You may now take unlimited neutral and negative quirks
/:cl:

Debate on positive quirk limit

### CODE REVIEW

**Comment by Wilchenx** [comment]
2-3 seems fair to me

**Comment by Tlaltecuhtli** [comment]
handicaptain time

**Comment by Mickyan** [comment]
So I have a few issues I have with this:
1. Some neutral traits are more akin to positives or negatives that are so minor they aren't worth a point, but having a trait limit makes neutral perks less appealing to take "just because" if you're looking to min/max.
2. Picking a whole bunch of traits adds a lot of noisy text when you inspect someone (while ghosting, using a health analyzer, inspecting yourself). There needs to be better visual distinction for readability.
3. At this point in time there aren't nearly enough traits for this to be warranted other than for someone doing a gimmick once in a blue moon and just upping the limit a little bit would do fine if there's really demand for it.

**Comment by ExcessiveUseOfCobblestone** [comment]
If traits are balanced appropriately in both macro (point cost) and micro (the trait itself) then should there even be a limit on positives?

**Comment by iskyp** [comment]
i'm going to take every single negative quirk ty

**Comment by Cyberboss** [comment]
@Mickyan then maybe a rescaling is in order so these minor buffs/nerfs cost a point and double the cost of everything else

**Comment by Mickyan** [comment]
@Cyberboss Yeah I've been thinking of doing that along with doing a bit of rebalancing for some of them, although I'm still a bit worried that this will make stacking a whole bunch of minor negative quirks the powerplayer option over using any of the major ones. We'll see how it goes

**Pull request merged**
