### PR TITLE
Initialize Refactor

### PR DESCRIPTION
**Pull request by Cyberboss**
Shouldn't break anything, stops warning spam, logs errors qdel style at the end of the game.

Initialize now expects a hint to be returned, one of:
INITIALIZE_HINT_NORMAL - Does nothing, returned by the root proc
INITIALIZE_HINT_LATELOAD - Call atom/proc/LateInitialize
INITIALIZE_HINT_QDEL - Calls qdel on the atom

LateInitialize currently defaults to the old re-calling behavior so there should be no issues with that.
Things that didn't return a hint or fucked up somehow will be logged less loudly than they were before

No more world start warnings!

### CODE REVIEW

**Comment by AnturK** [comment]
How long unitl LateLateInitialize.

**Comment by XDTM** [comment]
Finalize

**Comment by Cyberboss** [comment]
```
var/depth = 1
for(var/depth = 1; result == INITIALIZE_HINT_LATELOAD; ++depth)
    var/Late = ""
    for(var/I in 1 to depth)
        Late += "Late"
    result = call(A, Late + "Initialize")()
```

**Comment by optimumtact** [comment]
Ready?

**Comment by Cyberboss** [comment]
Yeah

**Pull request merged**
