### PR TITLE
Mice won't chew wires in debug mode

### PR DESCRIPTION
**Pull request by Cyberboss**
Alternative to #26133

### CODE REVIEW

**Comment by xxalpha** [comment]
Both PRs are retarded and attention seeking. If you want to test powernets alter the code to remove all mouse mobs on start up, you don't need to bloat the code for something like this.

**Comment by MMMiracles** [comment]
Asking mappers to temporarily comment out/remove code to make sure stuff works properly is dumb. I don't see the issue with having it attached to debugging.

**Comment by xxalpha** [comment]
>delete all instances of mouse

This is a map editor feature, it takes no effort.

**Comment by coiax** [comment]
@xxalpha you don't seem to understand, there are no mice on the maps anymore, they're dynamically and randomly placed at roundstart.

**Comment by coiax** [comment]
@Cyberboss I appreciate the support, but I still don't see what's wrong with a config option.

**Comment by Cyberboss** [comment]
Neither do I tbh

**Comment by xxalpha** [comment]
Are you dumb? The maps are loaded from map files, go to the map files and remove the mice.

**Comment by Cyberboss** [comment]
No @xxalpha , it was changed some time ago https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/squeak.dm

**Comment by xxalpha** [comment]
Sounds like you fucked up with that feature.

**Comment by coiax** [comment]
@xxalpha doesn't work, mice will often still bite wires before people have a chance to mass delete them.

**Comment by Iamgoofball** [comment]
@xxalpha 
whats wrong with having this feature for debug mode

**Comment by optimumtact** [comment]
feature freeze, please stop

**Comment by xxalpha** [comment]
Here's what's wrong goof, disabling features in debug mode when it's never documented or made clear the features are disabled will just bring more trouble in the future when someone is trying to debug the game because they will think they are playing the exact same game from live servers but they aren't, they're playing an unclear debug version of it. It's rather minor with in this specific case, but it sets what is in my opinion a bad precedent.

**Comment by Core0verload** [comment]
Make mice eating wires a config option. This way, both debugging setups and servers that hate the annoying "hunt down mice" roundstart minigame would be able to disable it.

**Comment by duncathan** [comment]
this should've been a config option in the first place; this shit sucks for small downstreams

**Comment by coiax** [comment]
@duncathan then reopen #26133

**Comment by Cyberboss** [comment]
Yeah that's the better option

**Pull request closed without merging**
