### PR TITLE
Research queue

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

2dZbpr8MK1

Added an ability to queue up to one node per player in a techweb for an automatic research.

You can queue up a node only when all requirements are met, but there are not enough points.

People can't research when there is something in the queue, only add things to the queue. So a 40 points node can't be researched if someone queued up a 200 points node ahead of it. 

When a node is enqueued by RD, it is placed in front of the queue.

The research button is available when the queue is empty.

TODO:

- [x] Bypass queue when the node cost is zero

## Why It's Good For The Game

No need to stay at the console to wait for the points. No "Research" button spamming.

## Changelog

:cl:
qol: Research nodes can be queued, one per player. RDs can place their node at the beginning of the queue.
/:cl:

### CODE REVIEW

**Comment by Vect0r2** [comment]
Can the RD get rid of queues or if the HOS queues up a 200 point research we gotta wait for that?

**Comment by MTandi** [comment]
> Can the RD get rid of queues or if the HOS queues up a 200 point research we gotta wait for that?

No, the node enqueued by RD will be placed in front of the queue. No deletion in the queue allowed.

**Comment by EuSouAFazer** [comment]
Deleting the queue feels like something that should be possible but at a cost. Maybe the RD can do it in the server room, to make that room more used (and not literally in the console itself)

**Comment by moocowswag** [comment]
total circuit/niche tech death

**Comment by the-orange-cow** [comment]
It is my understanding that these days, certain nodes cost zero points once the experiment is done.  Would 0 cost nodes be required to wait in queue?

**Comment by carlarctg** [comment]
bro why we got so many cows

**Comment by TheVekter** [comment]
Few notes:

- RD should have permission to purge the queue. We've historically given RD outright authority on what can and can't be researched and they should be permitted to reset things if need be. I'm not sure if you're hesitant to removing individual nodes due to some balance reason I'm not considering, but resetting the whole queue should be allowed. I'm already imagining a scenario where some idiot runs in and researches everything going to clown tech and now the RD has to babysit the console again.
- This is going to start _so many fights_, I can see it now. I don't think that's a negative for this being merged, but it should be kept in mind.
- I have some nebulous vibes-based concerns about not interacting with the system in general but I think the fact that you can't queue something unless you have the requirements should fix that.

**Comment by AtomTheProphet** [comment]
>     * This is going to start _so many fights_, I can see it now. I don't think that's a negative for this being merged, but it should be kept in mind.


I feel like if anything this should reduce the number of fights, since people can just queue up a research project and wait for it to get done instead of having to constantly check the research console to see when there's enough points to do it.

**Comment by MTandi** [comment]
> It is my understanding that these days, certain nodes cost zero points once the experiment is done. Would 0 cost nodes be required to wait in queue?

No, I still need to adjust the logic to make a "research" button available for those and make them automatically researched if they're in queue but receive a discount.

**Comment by carlarctg** [comment]
I really like the concept of RD having priority but not delete permissions. Heads are often shitters, so this limits their ability to be annoying to being constantly on top of ongoing research.

**Comment by MTandi** [comment]
> I really like the concept of RD having priority but not delete permissions. Heads are often shitters, so this limits their ability to be annoying to being constantly on top of ongoing research.

Yeah, that's why I'm against deletion as well. Seen one particular RD removing console access on the server just to research stuff for his personal project. Don't really want to give a full control just because someone was more lucky in rolling the RD role.

They already can force-queue their stuff, essentially having full control over the research queue. 

So with this PR they have even more control than before, because people no longer can spam the research button to win the race with RD.

**Comment by TheVekter** [comment]
> > I really like the concept of RD having priority but not delete permissions. Heads are often shitters, so this limits their ability to be annoying to being constantly on top of ongoing research.
> 
> Yeah, that's why I'm against deletion as well. Seen one particular RD removing console access on the server just to research stuff for his personal project. Don't really want to give a full control just because someone was more lucky in rolling the RD role.

This shows a very fundamental misunderstanding in what the purpose of the RD role (and heads in general) is. 

My issues with not having a function for resetting the queue are:

- Other heads have historically had full control over how a department is run. Quartermaster has IC control over what is and isn't ordered. CMO has full control over what kind of drugs the Chemist is making. To a lesser degree, CE has control over what projects are worked on outside of maintaining the station. This is a built-in intended design point of how the command structure works - there are checks in the rules for this, players have historically been empowered to demote people who go against them, this isn't new. Heads that are "shitters" are empowered from both an IC and OOC standpoint to have full control over their department; _however_, this also puts them at risk of being demoted by the Captain if they overstep their bounds and we've historically supported players leading a mutiny against their department head if they're being unreasonable/acting against the best interest of the crew. If it's a repeated issue, it would be an administrative problem, not something code would solve. This is good, interesting, organic conflict - the kind of conflict we actually want, because it creates interesting stories and RP opportunities.
- It doesn't make sense from a design standpoint in relation to other similar functionality in the game. Anyone with Cargo access can remove items from the cargo order system before the shuttle leaves for Centcom. Anyone with Robotics access can modify the exosuit fabricator queue. This is the only system that won't have that built in and I'm not sure how it differs beyond it being a permanent selection as opposed to something you can do multiple times, in which case, just limit it to RD and Captain access.
- It's going to be a pain in the ass to everyone involved when someone invariably researches something nobody needs or wants and the RD has to sit there babysitting the console until whatever the crew actually needs is done.

I feel like the lack of this functionality kind of generally harms whatever usefulness the queue concept has for the sake of some nebulous idea of "RDs are assholes actually" despite the fact that the vast majority of RDs actually don't _want_ to obsess over what's being researched, to the point where when we put the research console in their office and removed the semi-public one, most RDs just moved it back because they couldn't be bothered.

At the absolute bare _minimum_, please add a function where the person who queued something can remove it for basic usability purposes.

**Comment by MTandi** [comment]
>I feel like the lack of this functionality kind of generally harms whatever usefulness the queue concept has for the sake of some nebulous idea of "RDs are assholes actually" despite the fact that the vast majority of RDs actually don't want to obsess over what's being researched, to the point where when we put the research console in their office and removed the semi-public one, most RDs just moved it back because they couldn't be bothered.

Prior to this PR people can just spam the research button on consoles or in the PDA app and screw over the plan of RD to research something. I made a change that gives more control to RD over what is researched next and people can't prioritize their stuff when RD actually wants something.

And you're saying that I should've buffed RD even more?

>At the absolute bare minimum, please add a function where the person who queued something can remove it for basic usability purposes.

It already works this way, you can see the "Dequeue" button on the screenshot.

**Comment by TheVekter** [comment]
> > I feel like the lack of this functionality kind of generally harms whatever usefulness the queue concept has for the sake of some nebulous idea of "RDs are assholes actually" despite the fact that the vast majority of RDs actually don't want to obsess over what's being researched, to the point where when we put the research console in their office and removed the semi-public one, most RDs just moved it back because they couldn't be bothered.
> 
> Prior to this PR people can just spam the research button on consoles or in the PDA app and screw over the plan of RD to research something. I made a change that gives more control to RD over what is researched next and people can't prioritize their stuff when RD actually wants something.
> 
> And you're saying that I should've buffed RD even more?
> 
> I agree that RD shouldn't be overseeing the research too much, so the queue that works on a "first come first served" principle is the most fair one.

The intent has always been that RD should have final say on what is and isn't researched. This matches how every single other member of command works; RD doesn't magically not get that right because you got mad that one was an asshole one time.

We don't strip basic fucking functionality from features because one guy might abuse it sometimes. I would expect players to handle it the way they would any other member of command that's power tripping - get the Captain involved, if he refuses, bash the RD's skull in.

If you're really that concerned it's going to be an issue, we can revert that functionality later if it ends up being a problem, but you're going to make the job harder for a lot of the reasonable RDs just because one might be mean.

On a slightly unrelated note, I wish I understood why people get so eye-wateringly pissed about research nodes in general. It's not that deep yet people can and will murder someone for researching one thing over another.

**Comment by EuSouAFazer** [comment]
> > I really like the concept of RD having priority but not delete permissions. Heads are often shitters, so this limits their ability to be annoying to being constantly on top of ongoing research.
> 
> Yeah, that's why I'm against deletion as well. Seen one particular RD removing console access on the server just to research stuff for his personal project. Don't really want to give a full control just because someone was more lucky in rolling the RD role.
> 
> They already can force-queue their stuff, essentially having full control over the research queue. 
> 
> So with this PR they have even more control than before, because people no longer can spam the research button to win the race with RD.

This isn't even ided territory, we're well on "I didn't ahelp" territory. If RDs are being assholes with this ahelp them; their only job is to coordinate research. If they're being shifters then they get banned from the role it's that simple; denying basic functionality from the PR because of your ahelp issue is silly.

**Comment by JohnFulpWillard** [comment]
> I really like the concept of RD having priority but not delete permissions. Heads are often shitters, so this limits their ability to be annoying to being constantly on top of ongoing research.

We are in this perpetual argument between "Heads are shitters so we can't give them the ability to command their department" and "We want heads to have the ability to command their department and not be instantly assumed to be antag". Giving these tools and setting these expectations on command is one way of giving direction to the player as to what they should be doing, therefore "bad" heads of staff that actually impacts the round will either encourage them to learn and improve either by lynching, admins, etc, or other people who play RD properly to start trying to roll it, which either way means better command players, which is way better than not giving heads any direction other than the ability to demote IDs and grant access as it currently is.

**Comment by MTandi** [comment]
Nevertheless, RD couldn't prevent people from clicking the "Research" button in an unlocked console, so this PR gives more control over the research to RD than before. If someone has concerns about it, please let me know.

The goal of this PR is neither nerf nor buff of the RD, but a QOL tool for regular rounds where multiple people are waiting for points. Before they could fight next to the console for the right to click "Research". Now there is a fair queue.

**Comment by TheVekter** [comment]
With all due respect, I don't think we should be merging a feature that is missing important functionality. Regardless of your belief as far as RD responsibility and behavior, lacking the ability to reset the queue makes this a non-starter for me due to other similar systems having it implemented. You are asking us to add an incomplete feature.

**Comment by TheVekter** [comment]
> Nevertheless, RD couldn't prevent people from clicking the "Research" button in an unlocked console, so this PR gives more control over the research to RD than before. If someone has concerns about it, please let me know.
> 
> The goal of this PR is neither nerf nor buff of the RD, but a QOL tool for regular rounds where multiple people are waiting for points. Before they could fight next to the console for the right to click "Research". Now there is a fair queue.

I have voiced multiple concerns and you have ignored the majority of them. I like this feature, I would like to see it added, but I don't like that we continue to add things with some intent about trying to make command have less power in general over their departments. Yes, this is better than it was before, but it's still half-realized without some way for the RD to remove or reset what's queued.

**Comment by optimumtact** [comment]
You're asking them to do more than is strictly required when you review what control the RD has right now, when you could easily do a follow up PR about these ideas you strongly believe in.

**Comment by optimumtact** [comment]
I'm super keen to see the R&D get the rights to manage the queue btw, that will be a big step up in their authority.

**Pull request merged**
