### PR TITLE
Adds tram whiteship to the list of potential whiteships

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
See title. 

## Why It's Good For The Game
The Tramstation was added to our collection of shuttles but there's no chance for it to spawn on its own like the other ships. This fixes that. 

## Changelog
:cl:
fix: The Tram whiteship now has a chance to spawn!
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
what does tram whiteship even look like? (and does it have a mini tram on board?)

**Comment by dragomagol** [comment]
image

This is the Tram Whiteship

**Comment by newfren** [comment]
I seem to remember that this was always spawning in transit space instead of a reachable z-level, is that fixed?

**Comment by dragomagol** [comment]
> 
> 
> I seem to remember that this was always spawning in transit space instead of a reachable z-level, is that fixed?

This one specifically? I heard this issue about the Kilo Shuttle but I don't think this fixes that. If you see it again, please open an issue report with the round number and I can take a peek.

**Comment by TheBonded** [comment]
> image
> 
> This is the Tram Whiteship

holy shit it actually has a tram on it? I was just joking but that's sick

**Pull request merged**
