### PR TITLE
Fixes the intergalactic stock market crash by removing the speculation/performance modifier

### LINKED ISSUE #37566: All stocks are at a value of 10; number of stocks available are non-integers less than one, or are zero.
Round ID: # 87211 on Sybil

Testmerges: #37399 is testmerged but it's doubtful that something touching sprite loading has anything to do with the stock market.

#37416 is probably the full-merged PR most relevant to this issue report.

Reproduction: I found this as a janitor 15 minutes into the round. I went onto the stock computer and found that all stock values were 10 and the number of available stocks were non-integers less than one or at zero. The history of the stock market's price indicates to me that the price was this way since the start of the round. The history, however, as verified by the variables of one example stock (see image 3), shows that the price is actually 5, contrary to the displayed value of 10.

Stock main screen:
https://ibb.co/hnKJtc

History of one stock in particular, the one named "State".
https://ibb.co/gk4ezH

Variables of the stock named "State". Note that, while part of the "values" list is cut off, all other entries were also "5".
https://ibb.co/eoncmx

There were no abnormalities as far as I could see with the stock market events, but I didn't examine it very thoroughly.

This issue is probably caused by replacing the += operator with = as seen in #37416

### PR DESCRIPTION
**Pull request by deathride58**
TFW you try to fix random stocks ascending to a higher plane of existence, and instead end up accidentally the entire stock market

:cl: deathride58
fix: Fixed the intergalactic stock market crash. The speculation/performance modifier has been removed completely.
/:cl:

Fixes #37566

### CODE REVIEW

**Comment by pigeonsk** [comment]
Band-aid fix, and believe me when I say this doesn't fix the issue. You've only delayed the round-start crash to a steady 5-minute crash.

**Comment by Iamgoofball** [comment]
@pigeonsk proof?

**Comment by pigeonsk** [comment]
@Iamgoofball Test it yourself.

**Review by Cyberboss — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
It's still at perma- 10, at least it was last night on sybil.

**Comment by Iamgoofball** [comment]
was le server updated since merge?

**Pull request merged**
