### PR TITLE
Adds even more foods!

### PR DESCRIPTION
**Pull request by MidoriWroth**
## About The Pull Request

This is part two of my previous food additions, this time with much more variety. This will add:

**Chips and salsa**: An item I have long wanted to see on the list of things you can make, and a staple of Mexican dining.
**Fish tacos**: Adds more variety to seafood menus, and of course, because fish tacos.
**French toast**: Another addition I have wanted to see for a long time. The raw version will be prepared and then be required to cook on a griddle.
Updated stuffed cabbage/pierogi sprites, because I wasn't too pleased with my previous ones.
**Seaweed sheets**: Made at a biogenerator and are used for making sushi.
**Vegetarian sushi**: Straightforward vegetarian option for sushi, can be sliced into four pieces.
**Spicy filet sushi**: An omnivore specific sushi with a bit of spice, can be sliced into four pieces.
**French silk pie**: A decadent desert that finally adds a form of chocolate pie. Sliceable.

image

## Why It's Good For The Game

More food variety adds more interesting menus that chefs can create, plus the introduction of sushi is something I personally have seen long-desired.

## Changelog

:cl:
add: Adds 7 new foods! The power of chefs continues to grow.
add: Updated pierogi and stuffed cabbage sprites.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
I love these prs, you got a plan to start fixing that GBP balance?

**Comment by MidoriWroth** [comment]
> I love these prs, you got a plan to start fixing that GBP balance?

What does that mean?

**Comment by MrDoomBringer** [comment]
You currently have a negative GBP balance of -7. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by MidoriWroth** [comment]
> You currently have a negative GBP balance of -7. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

I don't really use github often so I don't exactly know what that means.

**Comment by MrDoomBringer** [comment]
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#good-boy-points

**Comment by MidoriWroth** [comment]
> https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#good-boy-points

Ohhh, gotcha. I'm not the best at coding, but I can update some sprites and fix some grammar/formatting to bring it higher.

**Comment by MidoriWroth** [comment]
That's not good, could this be merged please?

**Comment by MidoriWroth** [comment]
Let's try once more!

**Comment by tralezab** [comment]
sorry for the wait!

**Review by tralezab — APPROVED** [review]

**Pull request merged**
