### PR TITLE
Adds new chair sprites!

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request

Resprites some of the chairs!

Specifically resprited:
- Stool
- Bar stool
- Wooden chair
- Wooden chair (with wings)
- Comfy chair
- Office chair (light & dark)
- Plastic chair

image

image

Credit goes to @Crumpaloo

## Why It's Good For The Game

Reworking old sprites to look better is a good thing.

## Changelog

:cl: Crumpaloo
imageadd: Resprited some of the chairs.
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
Do you have a screenshot of the side sprites?

**Comment by SuperNovaa41** [comment]
> Do you have a screenshot of the side sprites?

Let me get them

**Comment by MTandi** [comment]
Can you please also include the previous version for comparison? It's hard to tell because they look similar. 

image

I liked the previous back of the office chair more.

**Comment by Likteer** [comment]
~~I wish I could offer something constructive but I'm tired and hate nearly all of these. Sorry mr Nova.~~
Wooden ones are nice. Comfy and tall bar stool are plausible. Regular stools and plastic are very meh. Office chairs are stunted.
It's clear you know how to sprite, but could you try something else when applicable?

**Comment by Twaticus** [comment]
i dont like a single one

**Pull request closed without merging**
