### PR TITLE
Adds colored lighting for Ratvar and Nar-Sie

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
imageadd: Ratvar and Nar-Sie now have fancy colored lighting!
/:cl:

The lights expand out 15 tiles. I'm aiming to have them go through walls but I don't know if it can.

prefix spess junk two 2017-03-04 163802

prefix spess junk two 2017-03-04 163824

### CODE REVIEW

**Comment by francinum** [comment]
:+1::+1::+1:

**Comment by KorPhaeron** [comment]
I don't think we should make the automatic revert button not work for /vg/ lighting until see if the memory leak is actually gone

**Comment by KorPhaeron** [comment]
lighting is busted

**Comment by Xhuis** [comment]
Really? As in, it broke? Damn, that was fast. Any idea what happened?

**Comment by KorPhaeron** [comment]
@Xhuis 

Can't reopen because branch is deleted

**Comment by Xhuis** [comment]
Oh, did the memory leak get fixed? Or was it just a Byond issue anyway? Branch is restored.

**Comment by Jordie0608** [comment]
It's a byond issue that's been fixed and will be in the soon-to-come v 11.1377, meanwhile we've done a work-around fix of our own. http://www.byond.com/forum/?post=2220974

**Pull request merged**
