### PR TITLE
[WIP] New co-op mech for robotics

### PR DESCRIPTION
**Pull request by tralezab**
# [VIDEO](https://youtu.be/LkOKKWUKpco)

## About The Pull Request

This is the new co-op mech. You can either get in the movement cockpit or the weapons cockpit. Because of this, the mech moves a bit faster and is a bit better at killing.

- [ ] Code for taking weapons off, and probably other inconsistencies
- [ ] shared status and integrity
- [ ] Finish the actual sprite (current is a WIP made simply to demonstrate two cockpits)
- [ ] Add it to robotics

## Why It's Good For The Game

More job content, I've always wanted a two person mech

## Changelog
:cl:
add: Two person mech, for you and your robotics pal to ride together!
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
all the basics work, like:
getting in either
getting out either
shooting
attaching weapons
movement
the problems most likely lie in edge cases and other hidden away mecha features

**Comment by MCterra10** [comment]
absolutely based and redpilled, time for metagang robo

**Comment by MrDoomBringer** [comment]
image

**Comment by MrDoomBringer** [comment]
piloting the mech should share your memories/notes with the other person

**Comment by TheVekter** [comment]
And here I was struggling for ideas for a new mech. Very, very nice.

Also gives me an idea for a traitor item, but antag freeze.

**Comment by Iamgoofball** [comment]
No posibrain. That's cheating. Find a real friend.

**Comment by PKPenguin321** [comment]
Posibrain copilot would basically be like the dummy plug, so it should make you kill your friends

**Comment by HomocidlePancakes** [comment]
Posibrains are not allowed to harm by their fluff, so have fun with that.

**Comment by TheVekter** [comment]
> Posibrains are not allowed to harm the crew by their fluff, so have fun with that.

Where's it say that

**Comment by Ohagi-Chan** [comment]
Off topic for this PR but relevant to this talk of posi/brain mechs.
Currently posi/brain pilots lack two pretty important features that human pilots have and it basically ruins the experience. It would be nice if you looked into these while working on your mech.
1) brain pilots can not interact with machines or consoles in any way. This causes issues for Ripleys trying to move to lavaland. Would be nice if they got an R2D2 attachment to safely interact with these instead of punching.
2) brain pilots can not eject themself from the pilot seat and neither can anyone outside. To escape their mech, it has to be destroyed.

**Comment by TheVekter** [comment]
> 1. brain pilots can not interact with machines or consoles in any way. This causes issues for Ripleys trying to move to lavaland. Would be nice if they got an R2D2 attachment to safely interact with these instead of punching.

I don't see why not.

> 2. brain pilots can not eject themself from the pilot seat and neither can anyone outside. To escape their mech, it has to be destroyed.

This is by design so people can't steal mechs from a brain.

**Comment by Tharcoonvagh** [comment]
Robocop 2: electric boogaloo

**Comment by necromanceranne** [comment]
Pretty exciting! I look forward to what might come of this mech.

**Comment by HomocidlePancakes** [comment]
@TheVekter As I said, it’s in their fluff. Let me quote it for you.

><b>You are a positronic brain, brought into existence aboard Space Station 13.\n\
	As a synthetic intelligence, you answer to all crewmembers and the AI.\n\
	Remember, the purpose of your existence is to serve the crew and the station. Above all else, do no harm.</b>"

**Comment by shellspeed1** [comment]
maybe make it so you can emag posibrains to enable harm mode?

**Comment by zxaber** [comment]
> 
> 
> > Posibrains are not allowed to harm the crew by their fluff, so have fun with that.
> 
> Where's it say that

Specifically in the flavor text;
`Remember, the purpose of your existence is to serve the crew and the station. Above all else, do no harm.`

An AI co-pilot, on the other hand...

**Comment by tralezab** [comment]
i'll disable posibrains, it goes against the spirit of the mecha

**Comment by zxaber** [comment]
I mean, it's still another player that you have to coordinate with. Seems fine enough to me.

**Comment by MrDoomBringer** [comment]
There's a lot less room for paranoia, backstabbing, and needing trust when you allow posibrains. In other words, no roboticist would ever choose something other than a posibrain because they know the brain won't be an antag and backstab them. 

I say to keep the requirement to being two carbon crewmembers.

**Comment by IllotAFV** [comment]
Alright,what will be an outcome of the viral bruteforce from the malfunction AI? That pretty forgotten ability,which ejects a current mech pilot,allowing AI to control the mech directly?

**Comment by zxaber** [comment]
I would argue there's already not a lot of that here. You're not going to be directly attacking the other cockpit while inside (I assume, anyway), and if you pull anything there's a witness you're joined with at the hip to sing your deeds over common. A non-ally won't keep driving you around once you make your intent known (and there's not a whole lot to do as the driver). Best case senario, the driver gets atmos control and you can walk the two of you into space and wait for them to expire.

This is a neat idea because it requires teamwork between players, not because there are backstab opportunities between the two crewmen.

**Comment by Ty-the-Smonk** [comment]
Please add a positive mood let to both of the pilots

**Comment by HomocidlePancakes** [comment]
>Please add a positive mood let to both of the pilots

What? Why?

**Comment by Shadowflame909** [comment]
tfw no darling in the franxx metaphor for sex mecha gf

**Comment by tralezab** [comment]
video added of how it looks (pretty much how you expected)

**Comment by PKPenguin321** [comment]
You can control two dudes in two separate windows in a local server if you log into your BYOND account, connect to local, then log out and connect again as guest

**Comment by HomocidlePancakes** [comment]
I was hoping the second pilot will be on the back or on top. Sad

**Comment by tralezab** [comment]
sure i can make a few edits to put him on the back

**Comment by Shadowflame909** [comment]
What happens when the Malf AI hijacks this mech?

Does it just lock crew in, but stops them from using any controls?

**Comment by tralezab** [comment]
as an update: i have unpushed changes but i'm trying to finish the sprite before i go back to fully finishing this

**Comment by necromanceranne** [comment]
Have a strong feeling this will get weird with malf ai dominate. Hopefully it just dumps the AI into the pilot seat and doesn't just nullspace the poor bastard.

**Comment by tralezab** [comment]
i kinda give up on trying to make this mecha look decent in the context of fitting in with other mechs, maybe i'll try again when i'm any good at spriting but i've been at this for way too long and i'm not really getting anywhere

**Pull request closed without merging**
