### PR TITLE
Revert "In-code key handling system, Take 2"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#32751

If this pr is closed. I'll transfer the servers over to a new repo.

Breaking input for a third of the playerbase and not even taking it seriously is not ok.

### CODE REVIEW

**Comment by Thunder12345** [comment]
Coderbus: Supporting fundamentally broken features since forever

**Comment by optimumtact** [comment]
wasd is superior duh

**Comment by Qustinnus** [comment]
lol that 1/3rd must be hippie players if they don't use WASD

**Comment by ninjanomnom** [comment]
@Qustinnus it was a tg poll

**Comment by Qustinnus** [comment]
hippie is infiltrating

**Comment by deathride58** [comment]
How *exactly* is input broken for non-hotkey mode players?

It'd be better to fix it rather than revert it. The new input handling is far, far more robust than byond's input handling, and helps pave the way for all sorts of neat features.

**Comment by deathride58** [comment]
Return focus to the input box when keys are released while hotkey mode is disabled, then. You don't have to revert the entire PR to fix it.

**Comment by epochayur** [comment]
I think the point is that if it's not being properly maintained now, it likely won't be in the future

**Comment by ninjanomnom** [comment]
that's not as simple as you think @deathride58

**Comment by deathride58** [comment]
Actually, wait. What proc is it that causes the focus to be reset to the game window? It should be as trivial as not changing the focus if hotkey mode is disabled.

**Comment by ninjanomnom** [comment]
there's no proc, it just happens automatically through byond

**Comment by RemieRichards** [comment]
the proc is winset()

**Comment by banthebantz** [comment]
glad we didn't merge this LOL

**Comment by deathride58** [comment]
Gimme like 30-60 minutes while I push out some shitcode, then. Should only take two lines to fix everything.

**Comment by optimumtact** [comment]
@banthebantz I told you man

**Comment by banthebantz** [comment]
@optimumtact The maintainer /tg/ needs but doesn't deserve

**Comment by KorPhaeron** [comment]
Alright so MSO says he might have a potential fix he'll be able to complete in the next ~week that would solve his issues with this without having to revert

In the meantime we'll testmerge this on the servers

**Comment by Cyberboss** [comment]
PR doesn't need to be open to be testmerged and the servers are smart enough to keep it on

**Comment by optimumtact** [comment]
he told you not to close it

**Comment by Cyberboss** [comment]
@MrStonedOne Confrictur

**Pull request closed without merging**
