### PR TITLE
Removes changeling tentacle stun

### PR DESCRIPTION
**Pull request by silicons**
Out of everything that could be done to make tentacles less overpowered, I feel like this is the best change. With the stun you can instakill basically anyone you want if you also have an armblade. Without it they still have a CHANCE of escaping. This turns it from ebow changeling edition into something that while still power is able to be countered.

### CODE REVIEW

**Comment by Kromgar** [comment]
So does this mean you can still armblade them with your tentacle pull?

**Comment by kevinz000** [comment]
@Kromgar to get this through i wanted as little balance implications as I can and the first step to me is removing the stun.
Unless you're loaded up with massive fucktons of 6 different kinds of stims, the default stun with an armblade will ensure your death, as the stun is long enough to crit you with the armblade after the initial damage with full health.

**Comment by XDTM** [comment]
There are like 4 different tentacle nerf prs open and none has removed impaling yet

**Comment by kevinz000** [comment]
@XDTM the stun is the worst part, impaling does a fuckload of damage yeah but the stun ensures your death above all else.

**Comment by XDTM** [comment]
I'm currently supporting @Robustin's idea of mostly making it a ranged, a bit more powerful, unarmed attack.

**Comment by Robustin** [comment]
Yea I prefer having the ranged just be a pure damage ability with no pull and keep grab as a pull + modest stun (no inherent damage though). Keep in mind the stun starts ticking at the beginning of the pull so weaken(2) means a very limited stun, just enough for one melee attack - which is about the same level of surprise as, well, popping out an armblade and hitting someone.

**Comment by kevinz000** [comment]
@Robustin plain armblade doesn't force you to drop all weapons and isn't ranged

**Pull request merged**
