### PR TITLE
Regal Rat resprites by GulDreggrod

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Regal rats have a new look, that looks less ugly! tada!

## Why It's Good For The Game

holy shit that front facing sprite. dear god. looks like the rat just ate a giant cinder block WHOLE

## Changelog
:cl: GulDreggrod
imageadd: new regal rat resprite!
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
pictures shortly!

**Comment by tralezab** [comment]
# OLD
image
image
# NEW
image
image

**Comment by nicbn** [comment]
The shading on the side sprite is off, it looks too flat

**Comment by tralezab** [comment]
@Twaticus

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
