### PR TITLE
Assembly bombs will now simply heat the gases in the tank, and make the tank process. Also makes assembly bombs bulky.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
Changes assembly bomb functionality. The assembly bomb will release a spark into the tank, delivering 7.5kJ (for reference, plasma filled to 2.533MPa in a 70L tank has a thermal energy over 4MJ) of thermal energy per litre of the tank, and having a heat capacity of 7.5J (or 2.5kJ if condenser) per litre of the tank. The tank will then process as normal, with the extra energy transferred to it which can lead to an explosion.

A room temperature oxygen tank with oxygen filled to 2.533MPa can create a 0, 0, 1 explosion. An oxygen tank filled to 2.533MPa at 2.7 Kelvin can create a 1, 2, 5 explosion. It is possible to create a maxcap if it is filled with antinoblium, if it has a tritium/hydrogen and oxygen gas mixture, or a tritium and nitrogen gas mixture with a condenser assembly.

Assembly bombs are bulky when created with a tank larger than 6L. Assembly bombs will always ignite and heat (or cool) the gas regardless of whether it is welded or not. The gas will escape before it can explode if it isn't welded though.

## Why It's Good For The Game
The assembly bomb was filled with a forest of stacked if checks that did hardcoded explosions based on random temperatures and strengths. The only way a person could find the best mixture (673.16 Kelvin plasma at max pressure) was to codedive, or have a codediver tell them the mixture, which isn't very interesting. Changing the functionality to instead heat the gas in the tank, and let the tank process allows people to use their knowledge of toxins/atmospherics to design their bomb and allow them to share an explanation on their mixture outside of "because the if check says so".

This change does make it possible to create a maxcap, so I decided to make the assembly bombs bulky so people can't carry a concealed maxcap in their bag.

## Changelog

:cl:
balance: Assembly bombs will heat the gas tank with 7.5kJ of thermal energy per litre of tank with a heat capacity of 7.5J (or 2.5kJ if a condenser is used) per litre of the tank, and let the tank process.
balance: Assembly bombs no longer do hardcoded explosions based on random conditions.
balance: Assembly bombs are bulky if created with a tank larger than 6L.
/:cl:

### CODE REVIEW

**Comment by calliophis-maculiceps** [comment]
them being bulky is a way more important change and it not being reflected in the PR title isn't good

**Comment by Pickle-Coding** [comment]
I will need to add a big obvious sprite, as the current one is really small, and hint what it does with its description in an IC way.

**Comment by MrDoomBringer** [comment]
Would be cool if the assembly bomb size correlated to the max explosion size, so I could fit an assembly-bomb-grenade into my backpack, but not a assembly-bomb-mininuke. Though I know this might be easier said than done.

**Comment by Pickle-Coding** [comment]
It would need to simulate 2 gas reactions. I think I could allow it to not be bulky if it's used from a small internals tank (no more than 6L) instead, as those would produce smaller explosions.

**Comment by MrDoomBringer** [comment]
As long as we know small internals can't make maxcaps, I think that would be great! Could keep the current sprite for small-tank-bombs, and use the new sprite (tbd) on bombs made with large tanks

**Comment by Jackal-boop** [comment]
Also WTF ANTI NOB CAN COMBUST??????

**Comment by Jackal-boop** [comment]
> Would be cool if the assembly bomb size correlated to the max explosion size, so I could fit an assembly-bomb-grenade into my backpack, but not a assembly-bomb-mininuke. Though I know this might be easier said than done.

This would be nice if possible.  I commonly use low yield single tanks as make shift c4

**Comment by SovietJenga** [comment]
yo can you also make it so assembly bombs actually care if it has an igniter or condenser in the assembly (I need my trit/n2 bombs )

**Comment by Pickle-Coding** [comment]
When I figure out how assemblies work.

**Comment by Pickle-Coding** [comment]
For some reason the forceMove fails after the latest commit, but I'm not sure why.

**Comment by Pickle-Coding** [comment]
It's possible to create a maxcap with hypernoblium formation even in 3L tanks. Considering the pressure required for a maxcap is only four times higher than the requirement to even let a tank explode, which doesn't give a lot of room, I'll rebalance tank explosions first before reworking assembly bombs.

**Comment by LemonInTheDark** [comment]
I worry about giving people easily triggerable explosions, it's part of why ttvs exist

**Comment by Pickle-Coding** [comment]
What if I make assembly bombs gigantic (regardless of tank volume), so someone would have to haul that by dragging it, and add a 90 second fuse for the igniter to trigger it?

**Pull request closed without merging**
