### PR TITLE
Nerfs crawling speed by 50%

### PR DESCRIPTION
**Pull request by silicons**
slowdown 2 --> slowdown 4
config option soon

### CODE REVIEW

**Comment by HydroFloric** [comment]
Bullshit, how am I supposed to yakety sax around on the ground dodging lasers now?

**Comment by Vidiveni** [comment]
A 100% crawling speed nerf would make you completely immobile. This buffs slowdown by 100%.

**Comment by XDTM** [comment]
nerf it by 200% so you crawl backwards

**Comment by PKPenguin321** [comment]
give crawling skateboard physics

**Comment by davethwave** [comment]
Another funny thing I've noticed is that ephedrine makes you crawl faster.

**Comment by subject217** [comment]
meth crawling for ultimate projectile immunity

**Comment by Tlaltecuhtli** [comment]
surgery to replace arms with legs for full speed crawling when

**Comment by Mickyan** [comment]
I'm not sure if it's intended but you can move away from grabs while crawling (couldn't do that in regular soft crit)

**Comment by YakumoChen** [comment]
It still seems really fast watching people crawl around on bagil with the PR active.

**Comment by FantasticFwoosh** [comment]
Local grudgecoder has ankles bitten off by crawling assistants. I didn't notice the crawl change particularly but isn't it forced walkspeed or is it just bad code to start with?

**Pull request merged**
