### PR TITLE
Blood brothers is now a single person conversion antagonist

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Instead of choosing 2-3 brothers, *one* person will be selected and given a flash which can convert one other person over. In accordance to the existing 10% chance for 3 members, there is a 10% chance that the first person converted will receive a flash of their own.

Expectation is people will flash a friend or a robust guy or whatever. My intent is primarily to see if this kind of blood brothers is more enjoyable to play with/against, and if their inclusion in a round increases the general chaos of it. My theory is that since most likely blood brothers will be people who know each other, that it can become more consistently interesting to the rest of the crew. That or they just murderbone together idk

Fikou and head admins said they wanted this to replace rather than add which I agree with.

## Why It's Good For The Game
Keeps the sandboxy aspect of blood brothers (no uplink) while likely making it more enjoyable to play. Conversion is equally as simple as revs for the user, and is just as intuitive to the one being converted since there are no new mechanics thrown in your face.

Blood brothers is currently disabled everywhere on the main servers except for MRP. I think this form will be more appealing to all rulesets. If left enabled, Dynamic now has more antagonists to make rounds diverse with and I want that

## Changelog

:cl:
add: Instead of teaming up random people together, blood brothers will now start out with one player and let them convert a single other person over to blood brother using a flash.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
i originally blocked head of staff but intentionally left them back in after a brief ask in coding general. i could easily be convinced through playtesting to put it back in

**Comment by moocowswag** [comment]
Ive been wanting this for a long time, blood brothers that can pick their friends would be super fun.

**Comment by itseasytosee** [comment]
I don't like how this supports meta thinking. Seems like people will always pick their buddy or the strongest guy on the server.

**Comment by Mothblocks** [comment]
the intent is that by letting people self select they will not only have more enjoyable rounds together but also the consistency of blood brothers' impact on the round will be stronger, which cannot be said for something like traitor or especially current blood brothers

**Comment by DaydreamIQ** [comment]
I for one absolutely love this idea. No longer will I be left up to rng on whether I get a good partner or a complete npc

**Comment by JohnFulpWillard** [comment]
my bad

**Comment by Mothblocks** [comment]
:(

**Comment by Jackal-boop** [comment]
I think the point of BB should be unlikely allies. This is an RP game and you should put aside any differences when you are antags to have fun and complete your objectives. If someone's mad they got a new player or someone they don't like as a BB politely show them the door

**Comment by Mothblocks** [comment]
who said anything about people being mad

**Comment by DrDiasyl** [comment]
Main concern of me beside what was already said about metathinking, is that any flashing done by evil people will be immediately thought to be revolution by Security. And fake revolution leads to a lot of shit.

Also, maybe make it so mindshielded cannot be converted?

**Comment by Mothblocks** [comment]
also that problem will change as time goes on and people adapt. it could even make for interesting cases in the vice-versa--real revolution that security members underplay

**Comment by EuSouAFazer** [comment]
> I think the point of BB should be unlikely allies. This is an RP game and you should put aside any differences when you are antags to have fun and complete your objectives. If someone's mad they got a new player or someone they don't like as a BB politely show them the door

If everyone is mad, angry and dissapointed you can't say it's their problem for not enjoying the mechanic, then it's the mechanic's fault.

**Comment by wesoda25** [comment]
Not a fan of the potential problems that choosing your antag partner carries but this will without a doubt make blood brother way more fun.

**Comment by DATA-xPUNGED** [comment]
I feel like a lot of BB right now is how your partner can be anyone, from any job, which adds a lot of randomness to it. I'm worried that people will metagame the best BB to flash based on job and shit. Not to mention that this already makes the chance for characters with disabilities to even *get* the antag to be pratically halved

**Comment by SomeoneYouProbablyKnow** [comment]
It would be nice to see some benefits to converting lower ranking crew members instead of just the RD every round who is the objectively best head to convert.
Maybe you can play with the extra conversion odds here. Something high if you convert an assistant and essentially 0 if you go for a head of staff.

Honestly the metapals are worth it for the positive impact on regular BBs. Half the time metapals just antag check each other and team up anyway.

**Comment by Mothblocks** [comment]
> Something I was wondering is what happens if you flash somebody with BB's turned off? Or another antag?

same as cult etc. it converts

> Would it be possible in anyway for a feature to shatter the flash for a random partner? That way we get the best of both worlds.

seems weird to include as a first class feature. why not flash the first person you see or something?

**Comment by SomeoneYouProbablyKnow** [comment]
> seems weird to include as a first class feature. why not flash the first person you see or something?

That's a very biased distribution. The first person you see is going to be someone from your department or a layabout assistant.
You won't get combos like atmosian and cook or chemist and QM just like that. 

Which is a fine tradeoff but just flashing the first person you see is not the same.

**Comment by deathrobotpunch** [comment]
tried this twice during the test merge rounds and had no issues with it at all, most of the time people just flash their coworkers instead of someone specific

**Comment by Vect0r2** [comment]
The best part of BB is being paired with Joey the atmospherics wizard, then having to make speed gasses to kill the head, or being paired with a paramedic and stealing your victims corpse. The best part of BB is the roll of the dice as others have said.

**Comment by Mothblocks** [comment]
so then why is it disabled everywhere

**Comment by plutori** [comment]
Although it's a good balance change, I don't really think the name "Blood Borthers" really works out when you can pick and choose who you convert to your team.

Perhaps a renaming would be in order for this?

**Comment by relativelysmalllebowski** [comment]
> Expectation` is people will **flash a friend** or a robust guy or whatever
do you not see the problem

**Comment by SuperNovaa41** [comment]
I really like it. Should definitely be play tested for a bit first though.

**Comment by RaveRadbury** [comment]
I think this is a great concept but I'm uncertain about using a flash to make it happen, as I think it gets a bit weird in the space of "willing conversion". Additionally BB has been a well-known disrupt to the sec meta because there are no tells for it, adding a flash removes that. I think it would be better if they could just pick from a list of candidates, while that isn't super great IC the idea is that this was all planned ahead of time anyway so we could handwave it as a sleeper cell thing.

**Comment by Mothblocks** [comment]
> > Expectation` is people will **flash a friend** or a robust guy or whatever
> > do you not see the problem

No

**Comment by Jezzared** [comment]
> > Something I was wondering is what happens if you flash somebody with BB's turned off? Or another antag?
> 
> same as cult etc. it converts

I well and truly don't like that, if that's an outcome with this PR. Disabling an antag should opt you out of needing to be in the most strenuous role of that antag. Disabling revs makes you not a headrev (at least not a starter one where you need to try and get converts without being caught), disabling cult means you're not one of the first few guys needing to set up circles and abducting people and you can just unga when the cult goes loud.

Disabling blood brothers and then being forced into a two-man antag duo that you explicitly opted out of seems like it would be a shitty feeling.

**Comment by wesoda25** [comment]
just ahelp fam

**Comment by Jezzared** [comment]
> just ahelp fam

This should never be a fix for bad design.

**Comment by wesoda25** [comment]
ngl thats all admins are

**Comment by Jezzared** [comment]
> ngl thats all admins are

I fundamentally disagree with this take but I am not about to fight with you on github about it.

**Comment by CMDR-Gungnir** [comment]
> > ngl thats all admins are
> 
> I fundamentally disagree with this take but I am not about to fight with you on github about it.

I am. Denny's parking lot, 3AM

**Comment by Jezzared** [comment]
> I am. Your PR's are stinky, nerd >:c
> 
> Edit: I went over like 3 different punchlines, chose the worst one initially, and then forgot to actually give my opinion;

Personally i liked "3 AM Denny's parking lot"

**Comment by Mothblocks** [comment]
> > > Something I was wondering is what happens if you flash somebody with BB's turned off? Or another antag?
> > 
> > 
> > same as cult etc. it converts
> 
> I well and truly don't like that, if that's an outcome with this PR. Disabling an antag should opt you out of needing to be in the most strenuous role of that antag. Disabling revs makes you not a headrev (at least not a starter one where you need to try and get converts without being caught), disabling cult means you're not one of the first few guys needing to set up circles and abducting people and you can just unga when the cult goes loud.
> 
> Disabling blood brothers and then being forced into a two-man antag duo that you explicitly opted out of seems like it would be a shitty feeling.

Feels like itr'd be shittier to remove you entirely from the round when the conversion method is so simple (and has to be)

**Comment by SomeoneYouProbablyKnow** [comment]
Why is it always 3 AM? The parking lot i get but damn you gotta be psychotic to do it at 3 AM.

**Comment by SimplySmiley123** [comment]
Honestly kinda liking the idea of this?
Would actually help Blood Brothers be a threat with, dare I say it, smart choice being made for picking your partner.
And actually give BBs a reason to take so much threat out of the round, again, dare I say it, with the BB putting that little bit of thought into who they want as their partner. Hell, you can actually pick people who you just _click_ with and can cooperate with well.
Again, making this antag role an actual threat for once.

Plus this fixes the issue of both _completely_ new players and shitters wasting the BB roll by charging security without a plan then disconnecting the instant they get smacked in the face with a baton.

**Comment by Jezzared** [comment]
> > I well and truly don't like that, if that's an outcome with this PR. Disabling an antag should opt you out of needing to be in the most strenuous role of that antag. Disabling revs makes you not a headrev (at least not a starter one where you need to try and get converts without being caught), disabling cult means you're not one of the first few guys needing to set up circles and abducting people and you can just unga when the cult goes loud.
> > Disabling blood brothers and then being forced into a two-man antag duo that you explicitly opted out of seems like it would be a shitty feeling.
> 
> Feels like itr'd be shittier to remove you entirely from the round when the conversion method is so simple (and has to be)

Then don't make it do that? I dunno gurl you're in charge of how it functions, you don't need to make it offer your body up or whatever. Just make it not work in some way if the other person doesn't have BB selected.

Perhaps instead of a flash you could give the starter Brother a "Blood Bond" ability that does the same thing but just silently fails if the target is a restricted role or doesn't have BB on. Then it's still a flavor win and it doesn't bypass preferences.

Plus if it's a generic "You don't feel a brotherly connection to this person!" You could restrict it from converting antags without being a tell, if you wanted to do that for balance reasons.

**Comment by excalisword** [comment]
Can blood brothers convert other antagonists like wizard or space ninja?

**Comment by Mothblocks** [comment]
yes just like revs and cult

**Review by Fikou — APPROVED** [review]
name sucks

**Comment by SinfulBliss** [comment]
Pretty cool. Personally I'd enjoy it a lot but I feel a bit bad for the players who will be missing out on antag because they're not part of a metagroup/aren't very good (although that's true for cult and revs too, less so because conversions are cheap and unlimited).

Other thing is it would be cooler if the conversion mechanic was something unique as opposed to just a flash. Something a bit more on-par with the theme like you get their blood or something IDK.

**Comment by Mothblocks** [comment]
it has to be a one click conversion or else it sucks. tattle suggested epi pens which i like but i want to observe my hypothesis on how this affects flash revs callouts for a while first

**Comment by itseasytosee** [comment]
At least the bros are back <3

**Comment by Mothblocks** [comment]
from discord, for posterity...

changes i wouldnt mind seeing afterwards:
- blocking command, if theyre too common and too busted
- unblocking security (but still blocking mindshield) for consistency
- changing flash to an epi-pen

**Comment by Mothblocks** [comment]
fair enough

**Comment by Admiral-Gigaton** [comment]
hey, i know this is merged, added, all that, but what if a blood brother flashes another antag? what if john blood flashes chang ling, and now its fucking unstoppable, even worse if one was a head of staff, and the worst if one was a head of staff/both were, and they got a third flash, getting another guy who was a traitor?? or a head of staff?? please tell me john blood cant turn chang ling the RD into a ling blood bro, please

**Comment by EuclidianGeometer** [comment]
I'm pretty sure changelings are conversion immune? If not, nice, you got a cool bro and they were already an antag so like, it's not like you've really made it That much more threatening. Seems like a way to have some fun stories and roleplay.

**Pull request merged**
