### PR TITLE
Fixes emergency lights literally never working

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: Emergency lights now function correctly.
/:cl:

Whoops.

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by WJohn** [comment]
These don't actually work. Or at least, not in ruins.

**Comment by RemieRichards** [comment]
@WJohn 
>It is turned off.

**Comment by Xhuis** [comment]
If there's not an APC with emergency light fallback enabled, they won't turn on. If the charge meter was ticking down, it strikes me as a lighting bug, since they seem to work fine for me.

**Comment by WJohn** [comment]
there are definitely APCs in these ruins, which have emergency fallback turned on. these lights are just off, for some reason. the charge meter is trickling down.

**Comment by Xhuis** [comment]
That's weird, I'm not sure what might be causing it besides an issue with the li- actually, this was an issue caused by someone else after this PR was merged, I just realized. Someone opened a fix PR at #34796. :P

**Pull request merged**
