### PR TITLE
Adds O as the OOC hotkey for cyborgs, and Ctrl+O as an any mode hotkey for humans and borgs.

### LINKED ISSUE #11157: Humans have an ooc hotkey but cyborgs don't.
I don't understand why but this seems to be the case. i cant find if they conflict because i cant locate where hotkeys are defined.

### PR DESCRIPTION
**Pull request by Supermichael777**
Yell at me if i did a bad thing.
Fixes #11157 my own issue report.
The salt is never more than a key-combo away

### CODE REVIEW

**Comment by SconesC** [comment]
:-1: Don't change the hotkey

**Comment by Supermichael777** [comment]
Not changing the hotkey. Their was no hotkey previously in these modes. This is purely additive. if you have an issue with any of the additions or I'm a massive screw-up who missed a critical step in the hotkey addition then please state them. Ctrl+O was added because I was their and everyone gets it because the code literally swaps between absolute lists so to be any mode they have to go in every list.

**Comment by optimumtact** [comment]
:+1:

**Comment by freerealestate** [comment]
Might want to add a changelog to let players know

**Comment by Supermichael777** [comment]
I'm still figuring out how to git, forgive me.

**Pull request closed without merging**
