### PR TITLE
Minimap is gone

### PR DESCRIPTION
**Pull request by Jalleo**
Removes the minimap subsystem since its not actually used for anything as I know of.

### CODE REVIEW

**Comment by Jalleo** [comment]
I will need to clean up my local master of these commits.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
https://github.com/tgstation/tgstation/blob/3a69327744e9afd2f0ddff7c940adeec0ccee928/config/config.txt#L355-L357

**Review by ShizCalev — APPROVED** [review]

**Comment by Jalleo** [comment]
@MrStonedOne your opinion?

**Comment by praisenarsie** [comment]
@Jalleo you might as well remove crew monitor consoles OR readd the ui to them but just without the map as there is a ui 'missing' for the consoles.

**Comment by MrStonedOne** [comment]
Lets actually wait on removing this. I need to see if the new byond changes fixed the minimap generation and if so we can start using it again.

**Comment by MrStonedOne** [comment]
Testing this now. I have a version of the code set to loop reboot world on the first real fire of the MC. it should yield any crashes

**Comment by MrStonedOne** [comment]
I was unable to get the crash to trigger, minimaps can be reenabled and we can start using them again.

**Comment by Jalleo** [comment]
Wahey. At least that is sorted.

**Pull request closed without merging**
