### PR TITLE
Adds space ruins to Northstar

### PR DESCRIPTION
**Pull request by DaydreamIQ**
## About The Pull Request
Adds three z-levels to explore on northstar (Assuming I did this right)
## Why It's Good For The Game
Chesh (The map creator) said it was fine to, and asked me to do it now that the support for ruin generation based on number of z levels exists.
## Changelog
:cl:
add: Ruins are now available in the region around the Northstar, Curators are now no longer jobless!
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
@optimumtact Has your stance on this changed since https://github.com/tgstation/tgstation/pull/74719 ?

**Comment by san7890** [comment]
Ah my bad mobile github cropped out the about this pr and i was rash

**Comment by Cheshify** [comment]
Backing PR creator's statement as true

**Comment by nukularpower** [comment]
and there was much rejoicing

**Comment by Cheshify** [comment]
Yeah anyone could have done this when the fix PR was in. DaydreamIQ is just built different.

**Comment by Pumpkinoe** [comment]
> DaydreamIQ is just built different.
ChadreamIQ?

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
