### PR TITLE
added botanical belt to botanist lockers

### PR DESCRIPTION
**Pull request by Peliex**
## About The Pull Request

Adds botanical belts into the hydroponics lockers at roundstart.
## Why It's Good For The Game

Botanists are shoving tools in their bags and it's not well known enough that you can create a belt early, up for debate but this was literally just one line so I made the PR
## Changelog
:cl:
qol: added a botanical belt into all hydroponics lockers
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
These are supposed to be a reward for getting at least some items into the biogenerator i don't think I like this
:-1:

**Comment by san7890** [comment]
i find myself agreeing with oranges, they're literally a few steps away from getting it by doing their job. kinda like science and the RPEDs. @MrMelbert do you have any interest in this?

**Comment by Peliex** [comment]
> i find myself agreeing with oranges, they're literally a few steps away from getting it by doing their job. kinda like science and the RPEDs. @MrMelbert do you have any interest in this?

There was good considerations from both sides. I am indifferent either way because making the belts is indeed easy.  Some thoughts were that now that you can create leather in the biogen instead of belts, it is less accessible to players who don't know they can make it.  There are probably other ways to address this too rather than adding belts to the lockers, but also the capacity of botanists is regularly 5, and there is not ever more than 3 botany lockers inside the department.
image

**Comment by san7890** [comment]
the only concern that i find myself agreeing with is players not knowing that they need to generate leather to create the botany belt, that does seem unintuitive considering that every other belt doesn't require leather to craft and is instead automagically fabricated via the biogenerator, especially for new players.

i think a better solution to bring it in line with RPEDs and stuff like that would be to cut the leather middleman out and make the belt be able to be fabricated directly from the biogenerator. Then you aren't as reliant on the wiki or having to have it be spelled out to you by other players.

**Comment by Peliex** [comment]
Yeah, you can no longer print them on the biogen, i will look at alternative solutions to hinting to players that they can create belts, maybe even putting a strip of leather on one of the tables in the department could be sufficient.

**Comment by Peliex** [comment]
Closing this to search for alternatives. Thank you for the input!

**Pull request closed without merging**
