### PR TITLE
Outpost 45 update

### PR DESCRIPTION
**Pull request by Yobrocharlie**
## About The Pull Request

Outpost45 is as of now, over eight years old, and after so much time it has gotten very, very little attention, this fixes that and completely changes the gateway destination to have much more than it currently does both in terms of area to explore, story to learn, and stuff to grab.
## Why It's Good For The Game

As of right now outpost45 sat at a spot where people would wait to see what the gateway destination is, see its outpost45 by the ominous purple glow, and then immediately back away knowing that outpost45, in a casual conversation in a ticket I was talking with an admin and they said "Well then if you don't like it anybody can contribute" and so I did. (Extreme thank you to pumpkin0, vekkter, and jolly for helping me learn how to PR, how to github, and how to map.)
## Changelog

Adds two new areas complete with their own threats and rewards,
Adds an old crowbar to the engineering storage
Generally makes the gateway have a much more engaging story
:cl:
add: Added more content to outpost45, including incentives to go there.
/:cl:

### CODE REVIEW

**Comment by Yobrocharlie** [comment]
give me a minute to fix all of the failing checks

**Comment by Yobrocharlie** [comment]
okay there is one failing check and i dont know how to fix that one

**Comment by Pumpkinoe** [comment]
I think your 'why it's good for the game' should be more than just 'People see outpost45 and don't like it'
Why don't they like it? How does this PR improve upon outpost45 that makes it good for the game?

**Comment by Pumpkinoe** [comment]
Also your CL needs fixing - you've just got 'adds more content' in the changelog and all the actual changes are above what will be displayed in the CL

**Comment by Cheshify** [comment]
Screenshots too!

**Comment by Yobrocharlie** [comment]
Oh yea screenshots i actually have those on hand

**Comment by Yobrocharlie** [comment]
outpost45-2
outpost45-3
outpost45-4

**Comment by Yobrocharlie** [comment]
no wait thats older screenshots one moment

**Comment by Yobrocharlie** [comment]
outpost45-6
outpost45-5

**Comment by san7890** [comment]
image

your gateway atmospherics is failing CI, please fix

**Comment by Yobrocharlie** [comment]
> image
> 
> your gateway atmospherics is failing CI, please fix

aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Yobrocharlie** [comment]
fixed a few things and removed the waystation corpses because they dont really belong and replaced them with normal NT bodies

**Review by Maurukas — CHANGES_REQUESTED** [review]
You've got a few failing unit tests due to objects in walls and some active turfs
```
[01:55:22] Runtime in stack_trace.dm,4: tiny shards spawned in a bad turf (the wall) at UO45 Caves (81,97,12) in UO45 Caves. Please remove it or allow it to pass NeverShouldHaveComeHere if it's intended. (code/game/objects/effects/decals/decal.dm:12)
[01:55:22] Runtime in stack_trace.dm,4: tiny shards spawned in a bad turf (the wall) at UO45 Caves (81,93,12) in UO45 Caves. Please remove it or allow it to pass NeverShouldHaveComeHere if it's intended. (code/game/objects/effects/decals/decal.dm:12)
[01:55:24] Runtime in stack_trace.dm,4: ashes spawned in a bad turf (the wall) at UO45 Caves (95,95,12) in UO45 Caves. Please remove it or allow it to pass NeverShouldHaveComeHere if it's intended. (code/game/objects/effects/decals/decal.dm:12)

There are 587 active turfs at roundstart caused by a difference of the air between the adjacent turfs. To locate these active turfs, go into the "Debug" tab of your stat-panel. Then hit the verb that says "Mapping Verbs - Enable". Now, you can see all of the associated coordinates using "Mapping -> Show roundstart AT list" verb.
```

**Comment by Yobrocharlie** [comment]
> You've got a few failing unit tests due to objects in walls and some active turfs
> 
> ```
> [01:55:22] Runtime in stack_trace.dm,4: tiny shards spawned in a bad turf (the wall) at UO45 Caves (81,97,12) in UO45 Caves. Please remove it or allow it to pass NeverShouldHaveComeHere if it's intended. (code/game/objects/effects/decals/decal.dm:12)
> [01:55:22] Runtime in stack_trace.dm,4: tiny shards spawned in a bad turf (the wall) at UO45 Caves (81,93,12) in UO45 Caves. Please remove it or allow it to pass NeverShouldHaveComeHere if it's intended. (code/game/objects/effects/decals/decal.dm:12)
> [01:55:24] Runtime in stack_trace.dm,4: ashes spawned in a bad turf (the wall) at UO45 Caves (95,95,12) in UO45 Caves. Please remove it or allow it to pass NeverShouldHaveComeHere if it's intended. (code/game/objects/effects/decals/decal.dm:12)
> 
> There are 587 active turfs at roundstart caused by a difference of the air between the adjacent turfs. To locate these active turfs, go into the "Debug" tab of your stat-panel. Then hit the verb that says "Mapping Verbs - Enable". Now, you can see all of the associated coordinates using "Mapping -> Show roundstart AT list" verb.
> ```

I’ll fix the decals but the active turfs I’m 99% sure are intended and are just the unique outpost45 atmosphere

**Comment by MMMiracles** [comment]
> > You've got a few failing unit tests due to objects in walls and some active turfs
> > ```
> > [01:55:22] Runtime in stack_trace.dm,4: tiny shards spawned in a bad turf (the wall) at UO45 Caves (81,97,12) in UO45 Caves. Please remove it or allow it to pass NeverShouldHaveComeHere if it's intended. (code/game/objects/effects/decals/decal.dm:12)
> > [01:55:22] Runtime in stack_trace.dm,4: tiny shards spawned in a bad turf (the wall) at UO45 Caves (81,93,12) in UO45 Caves. Please remove it or allow it to pass NeverShouldHaveComeHere if it's intended. (code/game/objects/effects/decals/decal.dm:12)
> > [01:55:24] Runtime in stack_trace.dm,4: ashes spawned in a bad turf (the wall) at UO45 Caves (95,95,12) in UO45 Caves. Please remove it or allow it to pass NeverShouldHaveComeHere if it's intended. (code/game/objects/effects/decals/decal.dm:12)
> > 
> > There are 587 active turfs at roundstart caused by a difference of the air between the adjacent turfs. To locate these active turfs, go into the "Debug" tab of your stat-panel. Then hit the verb that says "Mapping Verbs - Enable". Now, you can see all of the associated coordinates using "Mapping -> Show roundstart AT list" verb.
> > ```
> 
> I’ll fix the decals but the active turfs I’m 99% sure are intended and are just the unique outpost45 atmosphere

If the tiles are set up correctly, you won't be getting roundstart atmos differences. There's a reason the warning exists. Open the map in a local server, enable mapping debug tools from the debug list and check roundstart AT. These gotta be cleaned up.

**Pull request closed without merging**
