### PR TITLE
captain can no longer steal cargo goodies

### PR DESCRIPTION
**Pull request by flowercuco**
## About The Pull Request

Last night while messing around with some cargo order stuff I used the captains ID while inside its PDA and saw an unfamiliar box.
image

Then I experimented and found out the following.
The Captains PDA can open cargo goodies.
The EMAG can also open cargo goodies.
When it does these things, the code goes through to the parent of the order lockboxes and runs the /lockbox/attackby which means it goes through access which means that it recognizes that the captain has access and lets the captain open it.
This also updates their sprites into icon_unlocked and icon_broken which don't exist for the secure briefcase that is used for cargo goodies.

image
In this PR I added in a icon_broken because I think that it is fine to emag goodies and that if so it should be consistent with the other emag'd locked boxes.

I then made a small change that stops the captain from being able to open goodies that do not belong to them, where it now reads the ID inside of the PDA (or wallet) to compare bank accounts instead of returning to the parent's version of the code.

Then I added screentips where if you have an ID (or something that contains an ID) you can attempt to unlock a lockbox, it doesn't check if you actually CAN unlock it because it's probably fine for screentips to not be smart like that.

## Why It's Good For The Game

I think that the captain should not be able to steal cargo goodies and it is against the spirit of how cargo goodies are coded. Emaging them is fine, but it shouldn't turn into a completely different item if it is emag'd. 

Also personally I don't think that only being able to open cargo goodies with the ID in hand is like, compelling enough to stay.

Screentips. 

## Changelog

:cl:
qol: lockboxes have screentips,
qol: cargo goodies can be opened with your ID even if it is inside a PDA or Wallet
fix: captain can no longer open cargo goodies
imageadd: secure lockboxes have a broken sprite when emag'd
/:cl:

### CODE REVIEW

**Comment by Overuseddart** [comment]
Lore wise it makes sorta sense, the captain controls everything on the ship and his wish is the crews command. But probably good to be fixed.

**Comment by dalmationer** [comment]
plucky shit in this downstream

**Comment by Xeltronix** [comment]
The cap should be able to open cargo containers. if there is an emergency that requires them to open them. I do not think that This PR is required as it does not make thematical sense

**Comment by flowercuco** [comment]
this is specifically about goodies that come in the small little lockboxes the captain isnt going to steal valentines cards and NT mugs

the captain's id (specfically the ID) **_already can not open cargo goodies_** the captains id inside of a PDA being able to open cargo goodies is a bug, and it is a bug because it causes the sprite to break

**Comment by JohnFulpWillard** [comment]
What's with holybook

image

**Comment by flowercuco** [comment]
> What's with holybook

i dont have a goddamn clue how that got there? i guess something weird happened when i was working with downstream stuff but i dont know how bc nothing else from the downstream is in that branch?

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
