### PR TITLE
SECURITY RESPRITE - DARE.

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

image

image

Brand new sec sprites. Done by yours truly. Revival of #68024.

**Resprited Items:**
- Security Jumpsuit
- Security Skirt
- Warden Jumpsuit
- Warden Skirt
- HoS Jumpsuit
- HoS Skirt
- HoS Formal Uniforms
- Armour Vest
- Security Winter Coat
- Warden Jacket
- HoS Coat
- HoS Parade Coats
- HoS Wintercoat
- Security Belt

I also added sec-specific armour vests, and jackboots. Why? It looked good.

[Soundtrack for these sprites is: DARE, by Gorillaz.](https://youtu.be/SZP0NFRKBbs)

## Why It's Good For The Game

We like stuff to look good, don't we?

## Changelog

:cl:
imageadd: A complete overhaul of security sprites. See #69948 for more details.
spellcheck: Replaced all instances of "Jumpsuit" and "Jumpskirt" within sec items to be "uniform" and "skirt" respectively.
/:cl:

### CODE REVIEW

**Comment by ForestCranked** [comment]
i'm sorry but i thought your pfp was someone in enclave power armor for a second-

**Comment by axietheaxolotl** [comment]
> i'm sorry but i thought your pfp was someone in enclave power armor for a second-

What th- Who the- Who the fuck is this? I should kick your fucking ass, who is this?

**Comment by optimumtact** [comment]
```
>the year is 2028 
>I am moderating the 3000th hateful comment on the latest security resprite, the rate of resprites has reached 5 a year.
>I contemplate what my life has become
```

**Comment by Sealed101** [comment]
oh god fucking damn it that's why the HoS winter hood is missing, hilarious
please mention it in the changelog though

**Comment by GuillaumePrata** [comment]
Since the basic HoS winter coat was removed, the `/obj/item/clothing/suit/armor/hos/trenchcoat/winter` should be moved out of `code/modules/clothing/suits/wintercoats.dm` and `icons/obj/clothing/suits/wintercoat.dmi` to avoid future headaches.

Makes no sense to be grouped there when it shares almost no similarities with the standard winter coats.

**Comment by Thunder12345** [comment]
The security resprite war is back on

**Comment by DemoCrack** [comment]
Nice, PASGT style helmets.

**Comment by CRITAWAKETS** [comment]
looks _really_ good but probably would look even better with a slightly expanded color palette!

**Comment by Jackraxxus** [comment]
Am I blind or did the first few rows' east/west models forget their arms at home?
I'm glad the booba is still there 10/10 spritework.

**Comment by AdipemDragon** [comment]
(speaking of the minorest of minor tweaks), like in the last pr, I see that the west facing sec helm is still 1 pixel too pushed into the face, or is the east facing one 1 pixel too pulled off of the face? One of them is different from the other, and that difference's gotta collapse somewhere
(unless that's what that commit fixed to begin with and I'm just lookin like an asshole here)

**Comment by B00tz** [comment]
I really like the extra fluff showing from the hos winter coat.

**Review by Mothblocks — APPROVED** [review]

**Comment by bruhman8ghughug** [comment]
i like it but the old parade cap looks better

**Comment by bruhman8ghughug** [comment]
please i beg you to keep the old parade hat it would literally look so good with the fur coat you made i beg you ah

**Review by Imaginos16 — APPROVED** [review]
Is this going to be a monthly thing?

**Pull request merged**
