### PR TITLE
Adds logging for the blood contract

### LINKED ISSUE #29381: Blood contract doesn't log
What the fuck. (Bubblegum drop doesn't log who marked the person for death)

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #29381

### CODE REVIEW

**Comment by DoctoreMad** [comment]
Holy shit

**Comment by Cyberboss** [comment]
You can look it up using fingerprints, this just makes it easier

**Comment by KorPhaeron** [comment]
I hope admins dont take the logging message as a prompt to ban people

**Comment by monster860** [comment]
Ree your description has 2 words fix the description now and apologize for not putting a description ree

(/s)

**Comment by Kromgar** [comment]
Its fine to use contract when your not antag right?

**Pull request merged**
