### PR TITLE
Moves the Evidence Boxes from the SecVendor to the DetDrobe

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

Splits the Evidence Boxes purchasable in the SecVendor between it and the DetDrobe. Four are now in the latter while two remain in the former.

## Why It's Good For The Game

It makes very little sense to have the Evidence Bags, which will be used primarily by detectives, be sold in a vendor they don't have access to. Having them on the DetDrobe is more appropriate and good QOL.

## Changelog

:cl:
qol: Moved the Evidence Box from the SecVendor to the DetDrobe

/:cl:

### CODE REVIEW

**Comment by oklews** [comment]
can you keep atleast a few in the secdrobe? I like securing a crime scene for a detective.

**Comment by FernandoJ8** [comment]
> 
> 
> can you keep atleast a few in the secdrobe? I like securing a crime scene for a detective.

Wdym by "securing"?

**Comment by oklews** [comment]
> > can you keep atleast a few in the secdrobe? I like securing a crime scene for a detective.
> 
> Wdym by "securing"?

Grabbing a piece of evidence without getting my fingerprints or fibers on them, blocking it off, stuff like that.

**Comment by FernandoJ8** [comment]
Sure

**Comment by LemonInTheDark** [comment]
This pr is a little weird given the recent changes. Doesn't really effect much. I don't think a det will end up needing 40 backup bags either.

**Pull request closed without merging**
