### PR TITLE
gives the chaplain a shotgun

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Chaplains now can reskin their null rod to the super shotgun replica! 
It does 12 damage instead of the usual null rod 18, but can throw away opponents like a baseball bat and makes FUN sounds!
(it doesn't shoot bullets)

## Why It's Good For The Game

fun stuff for chaplains with their deity being a gun god or for people who have doom religions

## Changelog
:cl:
add: Super Shotgun replica! now available as a null rod reskin.
/:cl:

### CODE REVIEW

**Comment by LordSaladin** [comment]
DOOT, BFG when

**Comment by EgorDinamit** [comment]
You disliked my PR so I will do the same.
---------------------
**Actually**, it's a good idea, but baseball bats can stunlock people which is quite overpowered.
You might also add Doom-like suit for chaplain too since you probably will never get HECK suit from miners.

**Comment by fatted50** [comment]
> ## You disliked my PR so I will do the same.
> **Actually**, it's a good idea, but baseball bats can stunlock people which is quite overpowered.
> You might also add Doom-like suit for chaplain too since you probably will never get HECK suit from miners.

only if it's the classic marine and not the praetor suit

**Comment by Survivioboi** [comment]
Don't. Chaplain already has a possibly OP melee weapon, a bible which can destroy runes, and holy water which deconverts cultists. All this was added to make the chaplain special, like chef, bartender, and librarian. They all have special shit that makes them more powerful and gives them more a purpose. The bartender already has a shotgun. If you adding something, at least not a shotgun. Keypoint, Make it original.

**Comment by Fikou** [comment]
> Don't. Chaplain already has a possibly OP melee weapon, a bible which can destroy runes, and holy water which deconverts cultists. All this was added to make the chaplain special, like chef, bartender, and librarian. They all have special shit that makes them more powerful and gives them more a purpose. The bartender already has a shotgun. If you're adding something, at least not a shotgun. Keypoint, Make it original.

today i will not read a pr body

**Comment by ATH1909** [comment]
> You disliked my PR so I will do the same.
> 
> **Actually**, it's a good idea, but baseball bats can stunlock people which is quite overpowered.
> You might also add Doom-like suit for chaplain too since you probably will never get HECK suit from miners.

Chaplains can just deconstruct the wooden tables in the chapel to make baseball bats anyway.

**Comment by ATH1909** [comment]
Is there a way that you can make this check bullet armor instead of melee armor for the purposes of its damage?

**Comment by Pumpkinoe** [comment]
make it make a gun noise everytime you hit sumfing with it
also, feels like a noob will click on the shotgun reskin expecting to start firing shells from their face
any way you could clarify that it does not shoot boolets

**Comment by Fikou** [comment]
> any way you could clarify that it does not shoot boolets

"super shotgun **replica**"

**Comment by optimumtact** [comment]
things the chaplain doesn't need

more null rod resprites

**Comment by LordSaladin** [comment]
You know this could replace one of them.

**Comment by optimumtact** [comment]
I suppose it probably could

**Pull request closed without merging**
