### PR TITLE
Prevents more prisoner positions from being opened

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request
When I made prisoners I didn't blacklist them like heads and silicons so clever people would open up slots for prisoners to latejoin.

## Why It's Good For The Game
Removes unintended gameplay

## Changelog
:cl:
fix: prisoner slots can no longer be opened on the HOP console
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
What fresh hell is this.

**Comment by Iamgoofball** [comment]
honestly i like this idea, but make 'em spawn in the permabrig

**Comment by Capsandi** [comment]
If mid-round prisoners ever do become a thing we need em to be pod launched at the permabrig

**Comment by RaveRadbury** [comment]
image

**Comment by nianjiilical** [comment]
add a cargo event like the russian party/spider clan events where centcom ships prisoners to the station

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Pull request merged**
