### PR TITLE
Reverts #20046

### PR DESCRIPTION
**Pull request by ma44**
Growing cash is more fun than making hundreds of IEDs and giving them out to everyone

### CODE REVIEW

**Comment by PKPenguin321** [comment]
w r e c k e d

**Comment by ma44** [comment]
7 seconds, a new record?

**Comment by PKPenguin321** [comment]
not sure, i think @Bawhoppen or @Iamgoofball have the record?

**Comment by Iamgoofball** [comment]
Baw holds the record at 2.3 seconds

**Comment by YakumoChen** [comment]
>players obviously don't want this nerf
>Coders refuse to improve it instead of removing

**Comment by Jalleo** [comment]
Its the REDACTED saga. A fair few people know the cause. No point to point it out now really.

**Pull request closed without merging**
