### PR TITLE
One use portals will only become used up when they successfully teleport

### PR DESCRIPTION
**Pull request by spiders24110**
## About The Pull Request
Makes one use portals self-qdel only when they confirm that whatever tries using them has teleported.

## Why It's Good For The Game

One use portals were very frustrating to use, as they delete themselves when a ghost clicks them, or anything that can't even be teleported bumps into them.

...not that I've seen anyone use them except me
## Changelog
:cl:
fix: permanent one-use portals will no longer get used up when clicked by a ghost
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
Aah alr

**Comment by Wallemations** [comment]
Shouldn't you label this as a fix in the changelog? Having ghosts able to affect a portal sounds like a pretty big oversight to me

**Comment by Striders13** [comment]
> Shouldn't you label this as a fix in the changelog? Having ghosts able to affect a portal sounds like a pretty big oversight to me

nothing in game uses those portals as far as I'm aware, but sure.

**Comment by Wallemations** [comment]
> > Shouldn't you label this as a fix in the changelog? Having ghosts able to affect a portal sounds like a pretty big oversight to me
> 
> 
> 
> nothing in game uses those portals as far as I'm aware, but sure.

If nothing in the game uses the portals then why are they in the code?

**Comment by Striders13** [comment]
> If nothing in the game uses the portals then why are they in the code?

they are a mapping tool

**Review by MrMelbert — APPROVED** [review]
Approved but the checks are wonky so send a blank commit

**Pull request merged**
