### PR TITLE
Suicide txt fix

### PR DESCRIPTION
**Pull request by AliiTea**
Ayy another tiny fix that isn't even important..  also why don't you listen >:I

### CODE REVIEW

**Comment by bgobandit** [comment]
fucking hell I knew I missed something fuck

**Comment by RemieRichards** [comment]
That's a trippy cursor.

**Comment by Memendia** [comment]
Thx no idea how I got it this way

**Comment by Memendia** [comment]
Ayyy finally merged :D

**Comment by Chocobro** [comment]
@Memendia in future make a branch on your local repo. saves a headache if you don't get a PR merged.

**Pull request merged**
