### PR TITLE
Stun arm rebalance

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Rebalances emaged borg stunarm to... not be an instant stun, because insta stuns suck ass. Basically, before it was just a funny thing that applies a 10 seconds paralyze on a target, and in  this PR i made that instead of being an insta stun item, now it is something like a knockdown baton on steroids. Hitting someone with it will deal 65 stamina damage to the targets chest, and apply a 2 seconds knockdown(if the target has TRAIT_BATON_RESISTANCE trait, it will still get a knockdown, but it will be shorter. Unlike with knockdown batons the knockdown here is necessary, so the stunarm will still able to save the borg from flashes or something like that.). If the target will have more then 60 stamina damage, instead of a knockdown and stamina damage it will get a 10 seconds paralyze(1 if with baton resistance trait) and sluttering speech.

## Why It's Good For The Game

Insta stuns are unfair to play against, and this PR aims to make the stun arm less cancer, while still keeping it still usefull. 

## Changelog

:cl: SuperSlayer
balance: Cyborg stun arm is no longer an insta stun
balance: Cyborg stun arm now knockdowns and applies stamina damage, and if the target has more then 60 stamina damage paralyzes it.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
you can't do this as long as flashes are an instant stun it takes no time at all to pull it out

**Comment by Mothblocks** [comment]
@LemonInTheDark you have talked about not wanting the stun completely removed from the past (and i tend to idly agree). feel free to give thoughts here

**Comment by SuperSlayer0** [comment]
> you can't do this as long as flashes are an instant stun it takes no time at all to pull it out

Borgs are in many things are better then humans, like they don't have damage slowdown, have all acess and etc., so getting insta stuned by flashes for them is a reasonable downside. Yes, you can instantly pull your flash out, but that types of borgs what have stunarms would always have them in their inventory, humans can just not have the flash, or forget to pull it out because of panic. Also borgs have 3 arms, their items can't be kicked out of their hands, can repair themselves if they are engiborgs, and mostly have advantage of surprise. With my changes their stunarm still is a usefull and powerfull weapon(still better then a telebaton since it doesn't have a cooldown and paralyzes), but is just more fair to play against. Basically it is still an item then allows you to win in one click, but you can't now just run into a group of people and solely slaughter them all.

**Comment by SuperSlayer0** [comment]
Also flashes can burn out, and stun arms can be spammed easily

**Comment by Pickle-Coding** [comment]
Malfunctioning borgs are supposed to be scary.

**Comment by SuperSlayer0** [comment]
> Malfunctioning borgs are supposed to be scary.

They still will be scary, they, like, disarm, deal stamina damage and knockdown you in one hit, while ideally stunlocking you after the second one.

**Comment by anclandor** [comment]
If you are nerfing the baton to require more than one hit to stun, you should also decrease the power cost, because it is very expensive, especially for a borg created with the borg factory that has a basic battery.

**Comment by NamelessFairy** [comment]
Personally not a fan of this when combined with the previous stun-arm nerf (63917) this would effectively halve the number of full stuns you have at your disposal down to a maximum of 5 for the average borg, given you likely need more than 10 seconds to get someone to the borging machine you'll end up getting through a few more  in that situation. 
However personally I never found the stun arm to be really any issue, borgs are already susceptible to one of the most brutal and commonplace hard stuns in the game and in order to get the stun arm is not an easy feat as it relies on another antagonist buying a specific item or a malf AI who hasn't destroyed the robotics console yet.
I'd also add something here about borg combat uniqueness but Lemon has been pinged and they'll probably explain it better then I could.

**Comment by SuperSlayer0** [comment]
> Personally not a fan of this when combined with the previous stun-arm nerf (#63917) this would effectively halve the number of full stuns you have at your disposal down to a maximum of 5 for the average borg, given you likely need more than 10 seconds to get someone to the borging machine you'll end up getting through a few more in that situation. However personally I never found the stun arm to be really any issue, borgs are already susceptible to one of the most brutal and commonplace hard stuns in the game and in order to get the stun arm is not an easy feat as it relies on another antagonist buying a specific item or a malf AI who hasn't destroyed the robotics console yet. I'd also add something here about borg combat uniqueness but Lemon has been pinged and they'll probably explain it better then I could.

Decreased the cost to 750. Also it doesn't halve the number of stuns you can make, since you still can paralyze your target again after paralyzing it once. The only issue is stamina regeneration, but it still isn't so horrific to deal with.

**Comment by MrDoomBringer** [comment]
>  humans can just not have the flash, or forget to pull it out because of panic.

This is not a proper justification, as soon as a malf borg is confirmed, most people start carrying around a spare flash or two. 
 Like Pickle said, borgs are supposed to be scary, and malfunctioning borgs are supposed to be able to reliably kill a crewmember in 1:1 combat, not just new players who forgot to have a flash during a malf AI round.

**Comment by SuperSlayer0** [comment]
> This is not a proper justification, as soon as a malf borg is confirmed, most people start carrying around a spare flash or two. Like Pickle said, borgs are supposed to be scary, and malfunctioning borgs are supposed to be able to reliably kill a crewmember in 1:1 combat, not just new players who forgot to have a flash during a malf AI round.

They still are able to win 1v1 fight, and have, mostly, same chances to win it as before, since the stun arm attack guarantees to kick their current item out of their hands, slowdown them and unlike stunbatons it doesn't have a cooldown and in 1v1 fight it still be something like a one-click win. This just makes it harder to fight against large groups of players.

**Comment by zxaber** [comment]
A big point of the stun is to combo into a borg machine. So the end result needs to be a stun of some real length, not just to allow time for dragging to the machine but also because the machine has a 60 second cooldown between uses.

The stun arm was nerfed recently-ish to have massive power draw. Does this PR address that at all?

**Comment by SuperSlayer0** [comment]
Ok one more downvote and I close this

**Comment by LemonInTheDark** [comment]
I think this is dumb
I love it when my problems solve themselves, I'm glad I've indoctrinated you all into my opinion

**Pull request closed without merging**
