### PR TITLE
Adds Improvised Jetpacks

### PR DESCRIPTION
**Pull request by Cw3040**
-requires two RED oxygen tanks (they have to be RED goddamnit), one fire
extinguisher, three pipes, and thirty cable coils.
-volume less than 1/3 of regular jetpacks
-starts empty
-looks like a red jetpack
-you move at hardsuit jetpack speed

developments:
-thanks to @obscolene for the sprite
-added 1/250 chance per tile for engine cut-out
-got yelled at a lot for making it red tanks only

 :cl: Cw3040
add: Added Improvised Jetpacks, with approx. 2/7ths of the volume of a normal jetpack, acts like a hardsuit jetpack in terms of speed and can cut out at random!
imageadd: Sprite by obscolene
   /:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
I would have said this would be stupidly strong, but that you only get hardsuit jetpack speed and that it requires red oxytanks(?) to work means it's a little bit challenging to get it set up, and not *too* strong. I do want to see how this affects things like ops (especially shitters trying to enter the ship now that they can maneuver out of the way of the bullets) and space ruin exploration.

**Comment by Cw3040** [comment]
We do need a unique sprite for this, for now it's using the (currently unused outside of admin intervention) sec jetpack sprite.

**Comment by Carbonhell** [comment]
nice idea but a ghetto-like icon could be really nice yeah

**Comment by Cw3040** [comment]
the problem with me doing code shit: i can't sprite worth a damn

**Comment by Qustinnus** [comment]
should have something like a chance to malfunction tbf

**Comment by Cw3040** [comment]
it's already basically the emergency oxy tank of jetpacks b

**Comment by bobbahbrown** [comment]
malfunctioning improvised jetpacks when

**Comment by Cw3040** [comment]
when i learn how to actually code instead of make varedit meme items

**Comment by bobbahbrown** [comment]
/obj/item/tank/jetpack/proc/allow_thrust(num, mob/living/user) might be usable for such a purpose

**Comment by Qustinnus** [comment]
`prob(chance)
  return false`

done

**Comment by Qustinnus** [comment]
jk thats shit dont do that l o l

**Comment by Cw3040** [comment]
i'll see what i can do tomorrow, for now it's sleep time

**Comment by Bawhoppen** [comment]
Why does it require only red tanks? Is it because of personalcrafting not being able to accept multiple types of inputs? If so, we really need to make it so it can.
Also it probably should get a proper sprite for it.

**Comment by obscolene** [comment]
here's a shit sprite if you want it


[on gif](https://i.gyazo.com/cc25cb13a63f7d43c232e26f78c26a79.mp4)

[dmi](https://cdn.discordapp.com/attachments/386702723623550987/486109582238810112/tank.dmi)

**Comment by Cw3040** [comment]
>  Is it because of personalcrafting not being able to accept multiple types of inputs?
yes

**Comment by Cw3040** [comment]
ready for merge

**Comment by Cw3040** [comment]
wyci

**Comment by PKPenguin321** [comment]
the need for specifically red oxy tanks is kinda lame

**Comment by Cw3040** [comment]
bring it up with whoever made personalcrafting pkp

**Comment by Qustinnus** [comment]
or the person who made this PR and made the req obj/item/tank/internals/oxygen/red instead of obj/item/tank/internals/oxygen

**Comment by Cw3040** [comment]
nah that guy is cool

**Comment by Qustinnus** [comment]
@Cw3040 you literaly said "go yell at the guy who made crafting" as if its their fault.

**Comment by Cw3040** [comment]
@MrDoomBringer updated the shit and gave credit outside of a dumb commit

**Comment by MrDoomBringer** [comment]
@Cw3040 nice. make sure to follow the changelog formatting tho. should look like:
🆑 Cw3040
add: Added Improvised Jetpacks, with approx. 2/7ths of the volume of a normal jetpack, acts like a hardsuit jetpack in terms of speed and can cut out at random!
imageadd: Sprite by @obscolene
/🆑

**Comment by Cw3040** [comment]
Thanks, updated.

Actually never had to use CLs before since the only codebases I've done work for don't use it.

**Pull request merged**
