### PR TITLE
Removes some shitty lavaland ruins

### PR DESCRIPTION
**Pull request by ChangelingRain**
this is bad
This specific ruin was:
- Boring
- Full of super weak skeletons, as if they were threatening to miners at all
- For loot, contained a honk render, arcane tome, and spellbook of charge, also some minerals and misc weaponry
- Had absolutely no theming and was just thrown together from existing assets
- Banana peels under the doors because oh yes that'll make this any better

Also removes the automated trade outpost, a tiny cube full of vending machines.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
- Also the walls are indestructible

**Comment by LanCartwright** [comment]
who added this ruin.

summarily ban them.

**Comment by ChangelingRain** [comment]
- But my clown theming!
 - No, fuck that, your clown theming is done much better by the clown planet ruin

**Comment by DfourC** [comment]
Put Honkrender in the clown planet ruin I guess.

**Comment by lzimann** [comment]
did it really have a honkrender, i don't think i've ever seen, space wind gets a bit shit in this ruin making everything go to lava

**Comment by Anonmare** [comment]
#20000 get

Also yeah delete this ruin, it's pretty naff

**Comment by Ergovisavi** [comment]
I dunno I like the ruin, I like the honk render and I usually just throw the charge book at a security member.

Plus, skeletons are always nice to see. Just wish space wind wasn't so dumb in this ruin.

**Comment by PKPenguin321** [comment]
VERY wasted get

**Comment by WJohn** [comment]
Please remove the trade outpost and all sin vaults too.

:+1:

**Comment by Kromgar** [comment]
Trade outpost is 10/10 you scrub WJohn

**Comment by JJRcop** [comment]
The get is rather not so honorary after all: #19999 #19998 #19997

**Comment by ike709** [comment]
>wasting #20000 on something other than a joke that could've been potentially a good feature but wouldn't have ever been finished anyways

:-1:

**Comment by Iamgoofball** [comment]
Remember when I did that for 10000 and people demanded I get repobanned

**Comment by Cheridan** [comment]
yeah but people demand you get repobanned all the time

**Comment by MMMiracles** [comment]
>Banana peels under the doors because oh yes that'll make this any better

if it managed to upset people then mission accomplished

anyway the ruin is shit but there was design reasons behind the choices (indestructible walls to prevent breaking into the side rooms for easy loot, room being regular pressure to make miner's KAs useless). 

also yes remove the trade outpost while you're at it seeing how it is literally a box with vending machines in it.

**Comment by ChangelingRain** [comment]
See, making the room regular pressure doesn't actually do anything to make miner KAs useless, unless the mobs cannot actually be lured out of the ruin.
If the mobs can be lured out of the ruin, that thing will happen, they'll be out of the ruin, and miners will ruin them.

**Comment by ExcessiveUseOfCobblestone** [comment]
the thing about the KA though doesn't matter when the ruin gives you a shield and spears [which 2h the spears 1hit them iirc]

**Comment by ChangelingRain** [comment]
I checked and the skeletons have 40 health, that's basically nothing to miners

**Comment by AdamElTablawy** [comment]
the pressure also pushes all the loot into the lava

**Comment by ChangelingRain** [comment]
frankly even if you fixed the pressure with tiny fan abuse it'd still be a shit ruin and it should go

**Pull request merged**
