### PR TITLE
Explodes device.dmi

### PR DESCRIPTION
**Pull request by YesterdaysPromise**
## About The Pull Request

I woke up today and thought 'what would be easy thing  to do today so I can say I've done something?'. Then I remembered I saw several gangtool usages the time I split radio up, and I could remedy those. 7 hours later, device.dmi is split in a folder of its own, and I've also given unique sprites to door remotes and landing desginators.

## Why It's Good For The Game

The device.dmi was kind of a mess.

## Changelog

:cl:
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Seems like you should atomize the new sprites out and keep this PR to just file organization

**Comment by YesterdaysPromise** [comment]
> Seems like you should atomize the new sprites out and keep this PR to just file organization

I got bit hanged up, that'd be right. But going back to do it according to your suggestion would be more trouble than its worth.

**Comment by Wallemations** [comment]
I'll be honest, I don't think I'm a fan of any of those door remotes.
They feel way too small & their color choices aren't great either.

**Comment by Dorsisdwarf** [comment]
New door remotes look kinda small and noisy, like when you downscale a sprite in nearest-neighbour? Are they based on multitools now? Not sure I like them.

Landing designators look nice.

**Pull request merged**
