### PR TITLE
Adds audio tags, for voice memos

### PR DESCRIPTION
**Pull request by RazorManager89**
## About The Pull Request
Adds audio tags!
image
(Big chonker codersprite - feel free to resprite)
Audio tags are tiny, independent audio recorders and players. Like the universal recorder, minus having to deal with all the unspooling nonsense! Available at your local PartMart or autolathe. (Please do not attempt to remove the disk media.)
## Why It's Good For The Game
Adds some flavour! You might need some note-keeping, and the universal recorder is considered Security gear. Audio tags are more tailored for the rest of the station. Plus, who wants to deal with having to spool cassette tape back in?
## Changelog
:cl:
add: Audio tags, small consumer-grade voice memo recorders!
/:cl:

### CODE REVIEW

**Review by Wallemations — CHANGES_REQUESTED** [review]
I get you're saying it's just a codersprite but I legit can't tell what that's meant to be
The desc says it's meant to be some sort of "small independent disk" but it looks more the size of a vinyl than a disk, shoved into a boombox of some sort
If you want it to be smaller than the tape recorder at least make it smaller visually
Hell you could even take the existing tape recorder sprite and chop it in half to insert a DVD-sized disk into it, that way people could visually connect its functions. That also has the added benefit of being far easier to do than going from scratch.

**Comment by timothymtorres** [comment]
We already have holopads, holodisks, and tape recorders.  Not sure how this is any improvement over a tape recorder? I'm also pretty sure tape recorders are obtainable from the library and autolathe.

**Comment by RazorManager89** [comment]
> I get you're saying it's just a codersprite but I legit can't tell what that's meant to be The desc says it's meant to be some sort of "small independent disk" but it looks more the size of a vinyl than a disk, shoved into a boombox of some sort
They're based on the audio logs from System Shock 2, which were available to basically every crew member. I didn't take size into account when making the sprite, so I'll try to craft together a smaller version. The black disk is supposed to be like the one on the inside of a floppy disk - since CDs/DVDs aren't part of the retro-futuristic guidelines. I could be wrong on this, so feel free to correct me.
> Not sure how this is any improvement over a tape recorder?
I considered giving it more runtime than the tape recorder, since cassettes can't store as much data as a floppy drive.
> I'm also pretty sure tape recorders are obtainable from the library and autolathe.
They are available in the library indeed. It could be replaced by the tag (and perhaps, by extension, made exclusive to Security's techfab), to really cement it as a 'security thing'.

**Comment by RazorManager89** [comment]
Eh, it's fine. Good learning experience, but ultimately pointless.

**Pull request closed without merging**
