### PR TITLE
Fixes timer bug (again) (maybe) (blame byond) (this is why arrays should start at 0)

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Aw, yes, you've had first off by one error, but what about second off by one error?

@kevinz000

### CODE REVIEW

**Comment by optimumtact** [comment]
one does not simply count from 0

**Comment by JJRcop** [comment]
There are 2 kinds of programming languages: Those that use 0 based arrays, those use 1 based arrays, and those that don't know what arrays are.

**Comment by Iamgoofball** [comment]
I start all my arrays at 2 like God intended.

**Comment by MrStonedOne** [comment]
While test merged it turns out this broke some things. investigating.

**Comment by vuonojenmustaturska** [comment]
Currently testmerged on bagil, seems to work fine. I'll give it a few more rounds.

**Pull request merged**
