### PR TITLE
The clown can now send a PDA message to everyone

### PR DESCRIPTION
**Pull request by ghost**
:cl: ShiggyDiggyDo
tweak: The clown can now message every crewmember at once! HONK!
/:cl:

The clown can now send a picture of his butt to everyone on the station

### CODE REVIEW

**Comment by Anonmare** [comment]
Clowncreep

**Comment by epochayur** [comment]
make it techweb

**Comment by ShiggyDiggyDo** [comment]
What if we spawn all crewmembers naked and they first have to research their clothes and equipment via T E C H W E B S ?

**Comment by epochayur** [comment]
>hurr durrrrr hurr durr

wow, good point dude, really blew me out

**Comment by ShiggyDiggyDo** [comment]
I really don't see the point in adding this to techwebs

**Comment by uraniummeltdown** [comment]
they shouldn't get bwoinked for spamming PDA messages, it should be solved ICly

**Comment by ShiggyDiggyDo** [comment]
Well there is a difference between spamming

**Comment by ShiggyDiggyDo** [comment]
Oh fuck

**Comment by ExcessiveUseOfCobblestone** [comment]
epic

**Comment by Ratvar** [comment]
The mime can now send a PDA message to nobody!

**Comment by ExcessiveUseOfCobblestone** [comment]
mimes should not be able to break vow, write, or pda.

don't @ me

**Comment by Anonmare** [comment]
Lawyer already gets the send all function and he basically is a clown without makeup

**Comment by PKPenguin321** [comment]
steal the lawyers spare cartridge

**Comment by vuonojenmustaturska** [comment]
Recommend that you follow @PKPenguin321 's advice here

**Pull request closed without merging**
