### PR TITLE
Adds some basic scaling, ~10% of crew, to shadowlings.

### PR DESCRIPTION
**Pull request by Incoming5643**
OOC: Drovidi Corv: I'm not sure why someone hasn't already added scaling
OOC: Amelius: Drovidi Corv, it's what I heard from Sticky and another admin, don't count on what I said being 100% correct. It could be people are just lazy.
OOC: Amelius: Maybe everyone thinks someone else is gonna do it
OOC: Incoming: that's why I haven't done it
OOC: Amelius: Just do it mate, it's gonna take like all of 5 seconds to do a flat 1/10 scaling.
OOC: Incoming: that and I don't really know what would be good balancing for it and I don't want to get accused of cocking things up
OOC: Amelius: According to Sticky, 1/10 works best.
OOC: Drovidi Corv: The rounds that have gone well have been 1/10 scaling
OOC: Amelius: And he runs SL modes every day usually
OOC: Amelius: Or every other
OOC: Drovidi Corv: It's even a pretty balanced winrate IIRC
OOC: Incoming: 1/10, what about number of thralls
OOC: Incoming: always 15?
OOC: Amelius: Flat 15 for onw.
OOC: Drovidi Corv: Flat 15's worked
OOC: Incoming: well alright if you guys say so give me a few moments here

### CODE REVIEW

**Comment by GunHog** [comment]
Will it actually be added to rotation, then?

**Comment by PKPenguin321** [comment]
If sticky doesn't back out of his [promise](https://github.com/tgstation/-tg-station/issues/9797)

**Comment by Stickymayhem** [comment]
I'll add it to the rotation when this gets merged and someone reminds me.

Thralling 15 people is very hard once anyone has gone loud. The number of shadowlings often doesn't factor into it all that much since they die off so quickly so a flat 15 works best yeah.

**Comment by Stickymayhem** [comment]
Oh it'd be nice if the console bug could be sorted too though. #9794

**Comment by SconesC** [comment]
90 man round
9 shadowlings

you shitting me?

**Comment by Xhuis** [comment]
thumbsup

**Comment by SconesC** [comment]
yes this need thrall scaling because you can have half of the shadowlings converting like 2-3 people win, jesus christ

**Comment by Fox-McCloud** [comment]
divisor should probably be 15-20

**Comment by AlexanderUlanH** [comment]
More people on a server means shadowlings need to convert fewer people per shadowling, but it also means more people period.  That means more people to find you while you're thralling, more people to fix lights, more people to kill thralls, and more people patrolling maintenance with flamethrowers.  Overall, I think a static number's fine.

**Comment by GunHog** [comment]
Agreed with Alex. High pop is extreme, it also means that Sec will be fully staffed, and maint will be PACKED with greyshirts and engies. Shadowling is not an easy mode for the antagonists. There are very few safe locations, and those places are easily removed with portable light sources, and even one that spreads on its own. Also, once your cover is blown, you have very little time to win, as the mode allows ALL crew and jobs to have a part in taking you down.

**Comment by SconesC** [comment]
>sec will be fully staffed

dude i wish but

this isnt true and we should stop using it - i've seen so many rounds where there is nosec on 80 players, it's absurd. people dont want to play a role that consists of getting shit on by people who dont like security and admins who want you on a tight leash

**Comment by AlexanderUlanH** [comment]
I haven't seen any high-pop rounds with no sec, but even if there are enough that it's a problem, high-pop rounds with no security are a problem we should be trying to fix, not something we should be balancing antagonists around, least of all the most security-resistant antag since wizard.  Sec doesn't need to be fully staffed because all you need is a flamethrower, a torch, some glowshroom, yellow slime cores, or a flare to fuck up a shadowing, especially when the number of thralls you have is dwarfed by the number of un-thralled crewmembers even when you're approaching 15.

From the games I've been in, 15 has never been an easy number to reach regardless of population.  It seems like Sticky agrees.  We're only going to get a better idea of whether we're wrong by actually playing the gamemode and collecting stats and feedback.

**Comment by Stickymayhem** [comment]
Thralls do not need scaling. 

First of all 90 people rounds aren't a thing. We have a 65 population cap. 

Secondly, I've been running various combinations of shadowling and it's well beyond 80% of shadowlings at minimum to convert a single person. Shadowlings have no dedicated stun until they hatch and it's a conversion time that leaves you vulnerable. When they do hatch they all die in the light before they can get anything done.

**Pull request merged**
