### PR TITLE
Supermatter now always spawns a singularity or tesla ball when failing

### PR DESCRIPTION
**Pull request by CPTANT**
The supermatter rarely meets the requirements for spawning a singularity or tesla ball and the standard explosion is kinda boring. This PR makes it so the supermatter failing will always produce a singularity (and a small explosion). 

:cl: 
tweak: Failing supermatter crystals will now always result in a gravitational singularity.
/:cl:

Edit: I put the tesla back, at high power the result is once again a tesla ball (and a huge explosion), at low power the result is a singularity.

### CODE REVIEW

**Comment by XDTM** [comment]
Worst of both engines, now it's hard to understand AND round-ending.

**Comment by Cyberboss** [comment]
Just reduce the requirements then, the intention was for every outcome to be able to happen

**Comment by CPTANT** [comment]
"Hard to understand"

Please stop this meme

**Comment by CPTANT** [comment]
@Cyberboss Yes but it's not an interesting system. The failure is almost completely uncontrolled anyway, the explosion is boring and personally I don't really care if it spawns a tesla ball or sing. The sing is more iconic.

**Comment by XDTM** [comment]
The whole point of it is that if it's just a fuckup you'll pulverize engineering and it stops there, if you put effort and planning in sabotaging it you get the round enders. Which limits the amount of rounds that are doomed at roundstart due to incompetence.

**Comment by ninjanomnom** [comment]
Personally I find it interesting and like all three to stay as possibilities. Though I do agree the non explosion results could stand to have a slightly increased weight.

**Comment by XDTM** [comment]
Also the sing is cool and iconic, but it also used to be way too frequent, the result being that is was a source of annoyance rather than awe. Making it rarer also makes it have more impact when it happens.

**Comment by CPTANT** [comment]
@the explosion is a round ender anyway, nobody is going to bother fixing that shit. It is just a boring one since nothing else will happen.

**Comment by Anonmare** [comment]
Now I can't make it go tesla

**Comment by Arianya** [comment]
The explosion isn't a round ender most of the time, since it's relatively easy to seal off the exposed area and  the solars can power what remains of the station.

Singularity is both boring and always ends a round, especially since the singularity spawns a powered up one.

:-1:

**Comment by Anonmare** [comment]
Plus the explosion is bigger if the crystal had more energy. If you put in the effort, you can make the explosion take out an entire section

**Comment by CPTANT** [comment]
thread: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=16271

**Comment by CPTANT** [comment]
I guess we can add the tesla spawning at high energies back in, its only the explosion that is truly boring for how long the SM takes to delaminate.

**Comment by Arianya** [comment]
I like the SM being unpredictable in how exactly it'll meltdown.

I like it sometimes just exploding, creating a giant hole that is an obstacle to the crew without necessitating an immediate shuttle call.

I like the engine requiring some effort to sabotage in a way that will generate a horrific black hole rather then it just being the default.

**Comment by CPTANT** [comment]
It takes ages to let that thing explode in the first place. I think any form of succesful SM sabotage has proven enough effort for creating a singularity.

**Comment by CPTANT** [comment]
Put the tesla ball back for high power delamination.

**Comment by 81Denton** [comment]
>I think any form of succesful SM sabotage has proven enough effort for creating a singularity.

you can just shoot the thing with a revolver for like 2 seconds and it goes pop
or abuse one of the 20 SME bugs that allow you to delam it within two minutes

**Comment by CPTANT** [comment]
Come on, those bugs should just be fixed, they aren't an argument for determining SM delamination results.

**Comment by ShadowDimentio** [comment]
>Now it's round ending

I've literally never once seen anyone ever bother rebuilding engineering after the engine blows. Why would they? It takes three times as long as calling the shuttle and leaving, at least with this the round end is more exciting.

**Comment by kevinz000** [comment]
Imagine making a PR to satiate shadowdimentio

**Comment by 81Denton** [comment]
@CPTANT Fair point, but so far the SME is balanced around the whole "low effort sabotage = small explosion" thing. As long as you don't get high moles/energy, the result will just be an explosion instead of automatically round-ending.

If anything I'd just lower the mole threshold for singulo delamination since it's harder to pull off and arguably less lethal than the tesla one.

**Comment by PKPenguin321** [comment]
what is cooler:
gay explosion -> round ends
or
badass black hole -> round ends

think about it

**Comment by XDTM** [comment]
gay explosion -> round not ending early

**Comment by PKPenguin321** [comment]
except that... it does in very many cases

if youre going to argue that people dont immediately call the shuttle every time well that happens with the singulo too. it tends to fuck off into space with minimal damage pretty often

**Comment by XDTM** [comment]
The difference is that with the singulo you have the overbearing knowledge that _eventually_ it's gonna come back and put an end to whatever you were doing, so people won't waste effort into anything long-term and everything fizzles off. At least an explosion happens and it's done, if the damage is limited enough you have nothing more to be worried about.

**Comment by PKPenguin321** [comment]
*calls the shuttle after sm explodes anyways*
thanks heads of staff

**Comment by Iamgoofball** [comment]
just make it a 50/50 chance of singulo or energy ball regardless of power level dude

**Comment by 81Denton** [comment]
>300 IQ traitor pulls out a revolver and shoots the big glowy rock candy
>creates a round ending event in under two seconds

th-thanks

**Comment by PKPenguin321** [comment]
correct 81denton that is in fact the current functionality

**Comment by davethwave** [comment]
Honestly if it's a round with not a lot of people and this situation happens I would probably have fun rebuilding engineering. Besides the problem is not always just solars, A lot of wiring that would have been connected are blown to bits so you would have to repair the cabling for the station as well.

**Comment by optimumtact** [comment]
No thanks, this doesn't fit with my vision of the game.

**Comment by PKPenguin321** [comment]
bruh

**Comment by demonfiren** [comment]
>oranges
>vision

**Comment by juanototo2** [comment]
@Cheridan 

>>>>>>>>>""""""""""""""Muh vision"""""""""""""""""

**Comment by ninjanomnom** [comment]
I was going to close this at 24h if oranges hadn't done it early anyway

**Comment by optimumtact** [comment]
Cheridan can't save you now

**Comment by PKPenguin321** [comment]
ye now its @KorPhaeron i think

**Pull request closed without merging**
