### PR TITLE
Omegastation Updates & Fixes

### PR DESCRIPTION
**Pull request by Okand37**
Basically does what it says in the changelog. The aesthetic overhaul includes changing of maintenance tiles and adding of rusted walls here and there, along with some other tile replacements. I should note I also removed all instances of /obj/effect/decal/cleanable/dirt

:cl: Okand37
add: Overhauled aesthetic of some portions of Omegastation
add: Overhauled Omegastation's departure lounge, fitting it with the rest of the station's theme
add: Replaced the personal closets with wardrobes in Omegastation's Lockerroom
add: Made Omegastation's engine room floortiles reinforced
add: Replaced the cola and snack machines with their random counterparts on Omegastation
fix: Fixed Omegastation's self destruct console being a doomsday device
fix: Fixed Omegastation's chemistry shutters not all being synced and rearranged the chemmaster.
add: Added a small technology storage in maintenance near departures on Omegastation
add: Added additional loot and emergency supplies to maintenance on Omegastation
add: Added the X-01 Multiphase to the Captain's Locker, Blueprints to Vault, Reactive Teleportation Armor to Server Room and theHypospray to Medical Storage on Omegastation
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
Adding the missing head items is really good. Are the CE magboots already available on Omega?

**Comment by Bawhoppen** [comment]
More resourcecreep isn't really what we should be doing...

**Comment by Okand37** [comment]
@81Denton I figured I was missing something and I guess that would be it. I'll make sure to add those in later!

**Review by ShizCalev — CHANGES_REQUESTED** [review]
will PR a cleaned version on your branch tomorrow.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
https://github.com/Okand37/tgstation/pull/1

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
