### PR TITLE
Prevents changelings from zombie interactions

### PR DESCRIPTION
**Pull request by Cyberboss**
Currently, you get the zombie revival message, but then nothing happens.

:cl: Cyberboss
fix: Changelings are no longer affected by zombism at all
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
Means they can't blend in.

**Comment by coiax** [comment]
@Cyberboss I have an alternate idea for a PR.

**Comment by coiax** [comment]
Changelings should revive as zombies if they have the infection, it may be interacting with the FAKEDEATH flag that they sometimes self apply.

**Comment by Cyberboss** [comment]
Lings aren't human though, they never actually even die

**Comment by coiax** [comment]
They're just humans with a bunch of spells and special organs. At least, codewise. And I'm pretty sure they can die. They just come back after a bit (assuming enough chems).

**Comment by Supermichael777** [comment]
lore wise they cannot die and their brains are fake

**Comment by KorPhaeron** [comment]
coiax has a better one

**Pull request closed without merging**
