### PR TITLE
Readds the Drain Life rune

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Added the 'Drain Life' rune to the runes cultists can make. It will drain life from all creatures on the rune, healing the invoker.
imageadd: The 'Astral Communion' rune has a new sprite, made by WJohnston.
/:cl:

sprites
Drain Life on the left, Astral Communion on the right.
Astral Communion rune sprite made by @WJohn

### CODE REVIEW

**Comment by WJohn** [comment]
Oh lordy I drew that like 4 years ago now.

**Comment by Kromgar** [comment]
Why was drain life ever removed?

**Comment by AdamElTablawy** [comment]
drain life is a strange combination of useless and overpowered.

you can easily make a giant spambase of drain life runes, all invisible, leading to your base, so that anyone passing over them unawares can get blooddrained to dead. 

But other than simply spamming the rune everywhere, it's absolutely useless aside from rare gimmick situations.

It'd be nice if the rune had a bigger range, or something.

**Comment by ChangelingRain** [comment]
Drain life doesn't do the chaining thing, and hasn't actually done so for about a year(at least for the time it actually existed)

**Comment by Kromgar** [comment]
All i ever used it for was to drain monkeys

**Comment by ShadowDeath6** [comment]
If you had willing ghosts, you could use it to fullheal with extremely little effort, if this is the same as blood drain. Since pylons and stuff were added it really isn't as useful considering it needs a ghost to manifest

**Pull request merged**
