### PR TITLE
Changeling gametype improval: Removal of blood spiders

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

Uhh, I remove blood spider ability from changeling. Please clap.

## Why It's Good For The Game

Even after the poison number change blood spiders are just too dumb, they have gotta go. The original spread infestation ability was made with NPC mobs in mind, making them sentient and self-healing was silly. 

## Changelog

:cl:
del: Removes changelings spider ability
qol: Changeling antag role is less horrible.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
>removing one of the only tools changelings have outside of murderbone and confusion

This is the beginning of the end...unless we get armlings/goonlings.

**Comment by carshalash** [comment]
> > removing one of the only tools changelings have outside of murderbone and confusion

How are blood spiders not boning?

**Comment by Spookuni** [comment]
Blood spiders seemingly exist to give changelings (an antagonist which is both incredibly difficult to isolate if they don't do something stupid themselves, and also requires hard round removal to ever contain) a method to become a stationwide threat without ever revealing themselves or putting themselves at risk. I can only speak to the experience on MRP where I primarily play, but it is an absolutely miserable one there. They're a defacto way of enabling a normal antagonist type to murderbone while also still allowing it to hide behind roleplay rule 6 because you never have to actually do anything that anyone can reasonably stop you from doing in order to become an incredibly difficult to find and extremely difficult to kill stationwide threat (Catatonics and monkeyhumans work for the three absorb requirement, whoop do whoop). I really don't see any loss to the game from getting rid blood spiders, and they're an absolutely miserable experience as they are now.

**Comment by ANAME593** [comment]
not a big fan of lings but ling spiders are actually pretty weak removing it doesnt really change anything it just reduces the amount of things they can buy at roundstart

**Comment by exymian** [comment]
so obvious that its an ided pr

"reasoning; they are too strong for me and i keep dying to them, they have to go. clap for me please"

Changeling is a solo antagonist that gets revealed to everyone whenever they use any single ability. They get ganged on and round removed as soon as they reveal themselves.

Blood spiders require a not so light amount of DNA points, lots of chemicals for them to use which always removes the option for another helpful ability to use instead and puts you on high risk in such cases.


The eggs are visually distinctive with a red color which can be destroyed, spiders are very easily dealt by security with their disablers and a low healthpool and the spiders always spawn solo not to mention they target lings as well. They can be heard from great distance so it all comes down to your incompotence to die to them.

The ability adds action to the round, a distraction to security if they are dealt with while taking place  of other usefull abilities that the lings can have.

**Comment by carshalash** [comment]
> so obvious that its an ided pr

This is you.
image

**Comment by ANAME593** [comment]
> so obvious that its an ided pr
dont worry despite everything thats been said oranges will see it and it will get merged

**Comment by ANAME593** [comment]
> How are blood spiders not boning? 
blood spiders being used to bone is very unwise they are very weak its more of a sabotage thing

**Comment by CMDR-Gungnir** [comment]
> The eggs are visually distinctive with a red color which can be destroyed, spiders are very easily dealt by security with their disablers and a low healthpool and the spiders always spawn solo not to mention they target lings as well. They can be heard from great distance so it all comes down to your incompotence to die to them.

Yeah they're supposed to, but don't. Which means you've got an army of like 30 spiders which can kill you in three bites and can fullheal themselves very quickly.

**Comment by JohnFulpWillard** [comment]
I already coded an alternative if you want to balance it instead https://github.com/fulpstation/fulpstation/pull/429

**Comment by jughu** [comment]
I remember when you could only use this ability when you absorbed 5 people and not dna extracted 5 people lol

**Comment by SuperNovaa41** [comment]
your why its good for the game sucks, give an actual reason (or just like fix it since the things you said are silly are a 2 second fix)

**Comment by IndieanaJones** [comment]
I'd rather just see them rebalanced or alternatively replaced with goon's limb thing.  The original version of this ability sucked because the AI spiders did jack diddly squat and weren't really a threat to anyone.

**Comment by ATH1909** [comment]
> This is you.

did you just unironically try to win an argument by depicting someone as a soyjack

**Comment by jughu** [comment]
> > I remember when you could only use this ability when you absorbed 5 people and not dna extracted 5 people lol
> 
> wait when (if ever?) did that restriction get removed?

https://github.com/tgstation/tgstation/pull/1054 it didn't really get removed removed back then aborbtions were only absorbtions like husking people, and not dna extract stinging 5 people thats why theres a requirement on people instead of haha i sting 5 people(and that point such restriction is useless)

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Blood spiders suck, but I'd rather see some changes before a straight up removal

Increases the required DNA strands and add a `do_after` to making eggs maybe?

If they're still awful after balancing then they can go

**Comment by moocowswag** [comment]
They are actually the only type of spider that can travel in space by constantly stopping to heal themselves making them really good at sabotaging the station (like the sm cooling loop)

Due to this they are EXTREMELY more powerful than they are portrayed when you play more like a space carp and just avoid direct combat and work on spacing rooms and sabotaging the station in general. (I`ve gotten shuttle called after delamming sm and destroying tcomms in ai sat then spacing most of the departments as a spider)

This is like a 10x better reason to remove them or at least rework them, they arn`t actually that good at direct combat but they are amazing at sabotage.

**Comment by squi1-rasb** [comment]
> > so obvious that its an ided pr
> 
> This is you. image

Very nice

**Comment by IndieanaJones** [comment]
> This is like a 10x better reason to remove them or at least rework them, they arn`t actually that good at direct combat but they are amazing at sabotage.

Perhaps then a suggestion for a nerf would be to make their heal cancel if they take damage during it, or prevent them from healing if their temperature is below their damage threshold?

**Comment by CMDR-Gungnir** [comment]
> > This is like a 10x better reason to remove them or at least rework them, they arn`t actually that good at direct combat but they are amazing at sabotage.
> 
> Perhaps then a suggestion for a nerf would be to make their heal cancel if they take damage during it, or prevent them from healing if their temperature is below their damage threshold?

I'd just remove the heal, personally.

**Comment by jughu** [comment]
make this require 10 DNA absorbs and make it a endgame changeling objective

**Comment by Burgermancoding** [comment]
hugboxification of tgstation

**Comment by Coastfront** [comment]
I once saw someone say that /tg/'s robustness level is reflected by how many ided pr's there are and man they are slowly becoming more and more right.
IIRC, The original requirement was absorbs and it got hugboxxed to being easier. 
When spiders were npc's, as with all of everytime someones gives antags npc's as a reward for doing something, it was useless since our npc code is dogshit bad and they just sit around waiting to see someone. 

When they were player controlled, that could be used to give the perma dead people the ling absorbed something to do, Reducing the issue lings have of being an antagonist build on silent round removal before murderboning.

Absorbs, Are a semi hard thing to get en masse. They require you to incapacitate, or more likely kill someone, transport the body somewhere that people wont show up, and be still for multiple minutes. 
This either means you suck it up and wait a bit for bluespace body bags to be researched to make it easier, which can take awhile and usually means the round has gone on for long enough for the crews tech to ALSO be more than strong enough to curbstomp the spiders. Or the changeling robusted several people and ate them. Whether its through camping somewhere and killing people who shows up, which both relies on hoping that not alot of people show up, a nosey assistant doesent show up mid sucking, or local paramedic player who has spent the last 5 minutes staring at the suit sensors screen doesent show up exactly 5 seconds after you dealt 10 brute damage to your victem. If a changeling manages to accomplish several absorbs early in the round without getting caught and punished by sec, Then they probably were going to murderbone the station WITHOUT needing spiders.

Absorb requirement being hugboxxed created an artifical issue that we can avoid by unhugboxxing it. Removing this ability, exacerbates the issue with lings of "They arent that fun, All they are is stealth murderbone before doing an actual murderbone". It's already dissapointing enough to die to a ling at any point in a round, and then have to sit in deadchat until the next spawn event. Removing things lings can do to bring players back into the round is just dumb. It's similar to why goon has that thing changelings can do where they shit out their ass to be an asstagonist. Its so that the people who get round removed have something to do, While also not kneecapping the ling.

Not only is this not an improval, it actively makes the antag type worse by making everything bad about it more apparent, and if you're doing the fucking horseshit that every other coder and their mother does of "IM JUST GONNA ADD A REPLACEMENT FOR IT LATER" Fuck off. Either make a replacement now so that we dont fucking sit on a content gap for 5 years when nobody bothers to replace it, Or dont even touch it if all you plan on doing is selecting a segment of code and hitting backspace.

Just because you died to a fucking spider doesent mean the instant best idea is removing it.

**Comment by carshalash** [comment]
> I'd rather just see them rebalanced or alternatively replaced with goon's limb thing. The original version of this ability sucked because the AI spiders did jack diddly squat and weren't really a threat to anyone, by making it a ghost role it was intended to give the people the changeling killed something to do. Ideally, a PR that were to remove blood spiders would provide a replacement.

Nearly every time people try to nerf spiders you make a PR to buff them back.

**Comment by carshalash** [comment]
> Blood spiders suck, but I'd rather see some changes before a straight up removal
> 
> Increases the required DNA strands and add a `do_after` to making eggs maybe?
> 
> If they're still awful after balancing then they can go

I changed their toxin level damage in #63117 and they're still awful.

**Comment by IndieanaJones** [comment]
> Nearly every time people try to nerf spiders you make a PR to buff them back.

I want examples of this.

**Comment by jughu** [comment]
could be worse, could be mooncows which inject pax every hit

**Comment by carshalash** [comment]
#57452

**Comment by carshalash** [comment]
I'm just going to close this instead of having it nerfed and rebuffed forever.

**Comment by IndieanaJones** [comment]
The PR you linked is only has one buff, which was to give broodmothers and nurses a projectile from a suggestion given to me by fikou or armuhlen.  I'm very curious what PR it was made in response to though.

**Pull request closed without merging**
