### PR TITLE
Removes pets from possible staff of change transforms

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It's really not fun to get turned into a butterfly or the like. You're basically out of the round in a single projectile. Even EI NATH lets you get healed if someone grabs your brain.

### CODE REVIEW

**Comment by Incoming5643** [comment]
It's not supposed to be fun. What's the point of taking the staff of change if not a single form in the staff of change doesn't actually neutralize an attacker?

**Comment by KorPhaeron** [comment]
@Incoming5643 

Originally the benefit was that the crew would end up murdering each other as they turned into aliens.

Maybe they need a big red "you're a monster now you can do whatever you want"

**Comment by Niknakflak** [comment]
:-1: one bad change after another kor, dang

**Comment by Shadowlight213** [comment]
:-1: staff of change should have a chance to fuck peoole over. Making it ALWAYS turn you into something that can go murder people is kinda shit. What next? Make borgs always be emagged or remove regular borg and make it syndieborg only?

**Comment by Lumipharon** [comment]
Yeah this is dumb. Why would you even buy this if all you can turn people into are either humanoids or shit that will immediately try to murder you?

**Comment by GunHog** [comment]
:-1: The staff is supposed to be risky, but if the only thing that results is the risky part, it is not worth using.

**Comment by Incoming5643** [comment]
Also lest we forget you got rid of the other "you assuredly aren't going to stop the wizard like this" form back in https://github.com/tgstation/-tg-station/pull/12416.

Seriously there's nothing left after this that's really even bad to be.

**Comment by The-Albinobigfoot** [comment]
:-1:

**Comment by KorPhaeron** [comment]
The idea behind the soc was that it would create more antagonists, not remove people outright.

Doesnt seem popular though

**Comment by Incoming5643** [comment]
I can tell you that at least on sybil people who turn into animals/xenos/slimes/syndiborgs generally don't start killing anyone but the wizard these days. Occasionally there'll be a free spirit who realizes what he can do, but usually people are (rightly) aware that in a protracted fight against the station they'll just get dunked.

**Comment by KorPhaeron** [comment]
I think some people got banned for killing after they got intentionally changed so the issue probably isnt 100% clear cut from a rules perspective either.

**Pull request closed without merging**
