### PR TITLE
Fixes / new magic shoes sprite

### LINKED ISSUE #58722: Marisa magic shoes are missing an icon
Reporting client version: 513.1533

## Round ID:
[161013](https://scrubby.melonmesa.com/round/161013)

## Testmerges:
- [Makes the explosive compressor and blastcannon actually use the TTVs they're given + the explosion changes to support that.](https://www.github.com/tgstation/tgstation/pull/58015)

## Reproduction:
image

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Fixes #58722

Sprites new star-powered magical shoes, for laser-shooting ordinary witches.

## Why It's Good For The Game

GAGS oversight

## Changelog
:cl:
imageadd: Fixes magic shoes and gives them a magical twinkling star decal.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
fuck

**Comment by celotajstg** [comment]
I think there is one or two even extra white pixels here, and I don't see why there should be two frames here
image

Considering the only difference from the standard black sneakers here is the star, please convert this to a GAGS icon. Look at the wheelys shoe icon for reference.

**Comment by YakumoChen** [comment]
The shoes are supposed to be black regardless so I dont see the point of doing that. I would also need to split it from being a child of wizard sandals.

The pixel doesn't show up for me, so that might be a GitHub thing

**Comment by celotajstg** [comment]
Nah, you would not need to split it, and the shoes base is now in GAGS. Please change accordingly.

**Comment by maxymax13** [comment]
making everything GAGS won't solve your life problems celotajstg, one icon existing that could be split into three isn't the end of the world

**Comment by YakumoChen** [comment]
> 
> 
> Nah, you would not need to split it, and the shoes base is now in GAGS. Please change accordingly.
> 
> EDIT: If you want, I can do it, since I might fix another oversight later

You are not a maintainer. I'd rather have the shoes be a child of sandals and have its own dedicated sprite (like many other shoes in the code) then be a very snowflakey GAGS sneaker just because it happens to use the shoe sprite in its design.

**Review by Twaticus — CHANGES_REQUESTED** [review]
agreed with @celotajstg , use GAGS please. information can be found here https://github.com/tgstation/tgstation/tree/master/code/datums/greyscale

**Comment by celotajstg** [comment]
> > Nah, you would not need to split it, and the shoes base is now in GAGS. Please change accordingly.
> > EDIT: If you want, I can do it, since I might fix another oversight later
> 
> You are not a maintainer. I'd rather have the shoes be a child of sandals and have its own dedicated sprite (like many other shoes in the code) then be a very snowflakey GAGS sneaker just because it happens to use the shoe sprite in its design.

Just to clarify, you do not necessarily need to make it a sneaker, however you do need to provide the correct initialize and greyscale configurations for it.

**Comment by YakumoChen** [comment]
This is an agonizing amount of extra code bloat and work I will have to do just to add a special snowflake star to a character reference shoe.

I need the GBP but is it really adding value to the code to do it this way?

**Comment by YakumoChen** [comment]
@celotajstg 
This is an agonizing amount of extra code bloat and work I will have to do just to add a special snowflake star to a character reference shoe.

I need the GBP but is it really adding value to the code to do it this way?

**Comment by YakumoChen** [comment]
I ended up having to just change them to extremely snowflakey sneakers and editing every instance that spawned them because I didn't want to figure out how to learn JSON from scratch and just copying everything I could from wheelys

**Comment by YakumoChen** [comment]
this subsystem makes me GAG. Haha. Get it?

**Comment by YakumoChen** [comment]
Does this count as a refactor? Do I get GBP for that too?

**Comment by YakumoChen** [comment]
@Twaticus

**Review by Twaticus — APPROVED** [review]

**Comment by YakumoChen** [comment]
@Mothblocks moth boy can I get a merge? The other GAGS fix PR was the only thing really conflicting with this so I'm not surprised it was merged first

**Comment by celotajstg** [comment]
iss conflicting again

**Comment by YakumoChen** [comment]
haven't had time to fix it especially since @celotajstg keeps making new PRs that conflict and nobody merges it before the next conflict

**Comment by Mothblocks** [comment]
u couldve just clicked the resolve conflicts button like i did

**Pull request merged**
