### PR TITLE
Changes default chat preferences for new players

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request
New players will no longer have ghost ears, ghost sight and ghost whispers on by default.

## Why It's Good For The Game
This information is usually overwhelming and the first thing a new player will do upon dying will be to try and turn these settings off. We should just have them off by default and let players toggle them on if they really want to know what everyone is saying at all times.

## Changelog
:cl:
qol: New players will no longer start with ghost ears, ghost sight and ghost whispers on by default.
/:cl:

### CODE REVIEW

**Comment by kawoppi** [comment]
WAIT WHAT YOU CAN TURN THAT OFF?

**Comment by nikothedude** [comment]
people turn these off? im surprised by the idea that people apaprantly beeline to disabling them, ive never heard anyone actually be disturbed by them

**Comment by Jacquerel** [comment]
> people turn these off? im surprised by the idea that people apaprantly beeline to disabling them, ive never heard anyone actually be disturbed by them

As people were talking about this on Discord and there was some misunderstanding I should elaborate:
These settings do not disable seeing or interacting with ghosts.
The settings that Watermelon is suggesting as default (and I agree it's sensible) render it such that ghosts only see global radio chat and all text output by everyone on the screen they are viewing, vs ghosts seeing all text output by every source in the game at once (including every vending machine and random emoting mob).

**Comment by nikothedude** [comment]
oh. i had no idea those were default yeah that maekes sense

**Pull request merged**
