### PR TITLE
Changes station time to real time rate multiplier from 24 to 12

### PR DESCRIPTION
**Pull request by silicons**
night shift will therefore change every 1 hour from the first shift.
requested by optimumtact

### CODE REVIEW

**Comment by Cyberboss** [comment]
So can you confirm if this makes night shift 15mins or 1 hour of real time?

**Comment by kevinz000** [comment]
this makes 1 hour 12 hours, night shift occurs at 7:30 pm to 7:30 am station time, so in theory it'll make it tick every 1 hour instead of every 30 minutes.

**Review by Cyberboss — APPROVED** [review]

**Comment by arsserpentarium** [comment]
why 30 min?it was 1 hour if multiplier was 24.night only once per day.

**Comment by Cyberboss** [comment]
Yeah, I don't think @optimumtact fully understood how in-game time changed when he requested this 👎

**Comment by 81Denton** [comment]
Yeah, if it changes every hour you'd only ever see a cycle on Terry.

**Comment by kevinz000** [comment]
@Cyberboss time is randomzid on roundstart so it's possible it's already in nightshift in roundstart

**Comment by BeeSting12** [comment]
I'd rather it go 1:1 instead. Night shift is just based on what time the roundstarts.

**Comment by optimumtact** [comment]
I thought the time was tied to real time on the underlying physical server, so that you could play two, three rounds and the time would slowly change over all of them

**Pull request merged**
