### PR TITLE
Return cat tail and ears

### PR DESCRIPTION
**Pull request by qwaszx000**
add: Returned cat tail and ears.
You can roll it from random body.

### CODE REVIEW

**Comment by Cyberboss** [comment]
From what I can tell all this does is add cat parts to EVERY human, instead of just the ones who selected in their prefs, regardless of the config setting too.

Cat parts will never be on regular random humans, and we won't be overriding the config ever because of political reasons.

**Comment by Cyberboss** [comment]
Bear in mind, nothing currently prevents you from selecting cat ears and tails if said server enables it. If you're vying to get it enabled on the official servers, talk to the headmins.

**Comment by 81Denton** [comment]
So this is... the power of webediting....

**Comment by Thunder12345** [comment]
@Cyberboss they're already enabled on bagil at least

**Pull request closed without merging**
