### PR TITLE
An Exploration Into Lame Jobs - Syndicate Listening Post Remap

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

_Have you ever been bored at your job? A job where you can't scheme something up to get you up to date? Stranded at your job? Alone at your job? Has the job ever asked you a lot of question? Like I am right now? Should I stop?_

---

Anyways, I decided to think about it, and I remapped the Syndicate's Space Listening Post. How nice! Here's some screenshots:

image

You may be wondering "why is the outside decorated in Nanotrasen style?" Camoflague, of course! Never fails. 

You also may be wondering: "why are some parts of the base nice but some parts of the base suck?" There's _LORE_, do not fret (you could open up the Files for this PR and read it in the chronological order, but I wrote it to kinda "blend" into the map).

And yes, the bomb is real:

image

I also rebalanced the odds for a space-comms-agent to spawn to be 15% now.

## Why It's Good For The Game

image

The old Syndicate Communication's Base was old, and sucked. I tried to touch it up a bit, but I got fed up with just how fuck-huge that asteroid was, and moved on. Let's excise the fat, and try and get something _different_ in the mix. We've been giving the syndies too much nice stuff lately, let's lame it down a bit (with a pinch of paranoia).

## Changelog

:cl:
add: Nanotrasen has finally tracked down an elusive signal that's been haunting them over all of their broadcasts... there appears to be a new Syndicate Listening Base commissioned. 
balance: The odds for a Syndicate Communications Agent (the Space kind) is now at an 15% chance to spawn.
/:cl:

### CODE REVIEW

**Comment by private-tristan** [comment]
how will this effect the shuttle that can dock at the entrance (the one with 4 turrets that spawns in the pirates ruin)
the entrance seems a bit too small for it to dock in there.

**Comment by san7890** [comment]
> how will this effect the shuttle that can dock at the entrance (the one with 4 turrets that spawns in the pirates ruin) the entrance seems a bit too small for it to dock in there.

Good question. This is where the docking spawnpoint is on the map.

image

The old base did something similar like this near the airlock, but now there's a longer passageway "into" the base itself carved out.

**Comment by Elli-Skala** [comment]
> how will this effect the shuttle that can dock at the entrance (the one with 4 turrets that spawns in the pirates ruin)
> the entrance seems a bit too small for it to dock in there.

To add to this the old base has cable leading out it's entrance 
This made it so that when the fighter docks with the comms base it'll hook up to the based's power system and start to charge the fighter's APC

**Comment by san7890** [comment]
> > how will this effect the shuttle that can dock at the entrance (the one with 4 turrets that spawns in the pirates ruin)
> > the entrance seems a bit too small for it to dock in there.
> 
> To add to this the old base has cable leading out it's entrance  This made it so that when the fighter docks with the comms base it'll hook up to the based's power system and start to charge the fighter's APC

Did not know this was an interaction. I'll look at this in the next day and probably re-work the design a bit to accomodate.

**Comment by Colovorat** [comment]
for the love of god move relay away, my ears getting destroyed is not a fun experience when i sit at cameras

**Comment by Fikou** [comment]
6 nt logos next to each other is a bit much

**Comment by san7890** [comment]
I have since updated the map to the following (will await more feedback before doing a full compile and updating the PR body).

**Comment by Colovorat** [comment]
image
syndicate balloon in a wall?

image
i suppose that's a medical, but maybe put a bed at least? blood transfer without bed is not RP

image
where am i supposed to eat? no table and chair, muh immersion

just a small funny things i noticed 😄

**Comment by san7890** [comment]
> image syndicate balloon in a wall?

That is the asteroid baseturf spawner. It looks like a syndicate balloon for reasons.

> image i suppose that's a medical, but maybe put a bed at least? blood transfer without bed is not RP

it's meant to be lower-quality (aside from the medical cabinet) but i'll think about that

> image where am i supposed to eat? no table and chair, muh immersion

you can figure that one out :)

**Comment by Colovorat** [comment]
>it's meant to be lower-quality (aside from the medical cabinet) but i'll think about that

Maybe something like dirty matress, like in maints.
Lower quality :)

**Comment by ZAMODA** [comment]
Untitled39

**Comment by san7890** [comment]
> Untitled39

Why does this base need an autolathe? The old one didn't have one

**Comment by san7890** [comment]
what the fuck where'd my map go

**Comment by Son-of-Space** [comment]
<details>
  <summary>These guys spawn with a chameleon ID and aren't used anywhere else except away missions</summary>

image
image

</details>

<details>
  <summary>If you're going to give them supplies to mine the asteroid, you should give them some wood to make a campfire so they can smelt the metal. Maybe some small pockets they know are safe? Some ghetto space suit supplies? (firesuit and coffee or something similar)</summary>

image

</details>


<details>
  <summary>I think this little NT area has a lot of potential. Maybe add a button on the bad boy side to lock down the area and another button (or filter) to pump in some knock out gas? That sounds very syndicatey to me, especially as a tactic for someone who's alone.</summary>

image

</details>

<details>
  <summary>I really like this little maintenance area. It gives really strong crowded vibes. I think you should move the tools and such onto the spaces next to the structures instead of over them since we can't do that in-game.</summary>

image

</details>

<details>
  <summary>This airlock without a wall on the other side of it looks worse than the errored out black shoes.</summary>

image

</details>

<details>
  <summary>Keep in mind that players can't make these small floor subtypes, so when they go to restore the area they'll frustratingly have to pick up all the small tiles and put them in a dedicated area. On another note, for the lore, I don't think there's nearly enough trash in here. Or crazed scribbles either.</summary>

image

</details>

<details>
  <summary>I agree that the number of signs is a little overkill (even still). These are the ones I would remove to make it sensible.</summary>

image

</details>

<details>
  <summary>I think you should give them a small little cubby around here to grow basic foods since they've run out of supplies and remove one of those donk pocket boxes. Probably with dirt.  Maybe a bit of unstable mutagen, as a treat..</summary>

image

</details>

<details>
  <summary>Adult bookcase instead of random? Too far?</summary>

image

</details>

<details>
  <summary>I think this little area would be an ideal space to practice ghetto surgery if they recover that body outside.</summary>

image

</details>

<details>
  <summary>If you aren't interested in my other entrance defense suggestion, might I suggest adding a shield barrier setup here? Gibbing: Fun for the Whole Family!</summary>

image

</details>

<details>
  <summary>You should add a camera here if you're going to have a photo album. I would even go so far as to add a listeningstation version so we can have a persistent catalogue of people being miserable or puking all over themselves in here.</summary>

image

</details>

<details>
  <summary>Space plating instead of catwalk here</summary>

image

</details>

Other Notes:
1. No air alarm in the maintenance area.
2. The actual syndicate balloon should absolutely be a version that has lost all its helium and drags limply behind you, but that's absolutely out of scope.

**Comment by san7890** [comment]
Thanks for the feedback. As stated in the PR Body: "We've been giving the syndies too much nice stuff lately, let's lame it down a bit (with a pinch of paranoia)."

<details>
<summary> All points addressed</summary>

> These guys spawn with a chameleon ID and aren't used anywhere else except away missions

I made a new subtype with a different uniform to lessen the amount of gamer gear they can get.

> If you're going to give them supplies to mine the asteroid, you should give them some wood to make a campfire so they can smelt the metal. Maybe some small pockets they know are safe? Some ghetto space suit supplies? (firesuit and coffee or something similar)

That sort of gear is more meant for the wandering space traveller to be able to leverage should they choose so (remember, there's only a 15% chance for a comms agent to spawn in), _because we absolutely do not want to facilitate the comms agent leaving that base!_

> I think this little NT area has a lot of potential. Maybe add a button on the bad boy side to lock down the area and another button (or filter) to pump in some knock out gas? That sounds very syndicatey to me, especially as a tactic for someone who's alone.

It's not meant to be developed, it's meant to be scuffed. I was playing around with the concept of having a bolted door for the comms room but I didn't like the way it was handled on playtests.

> I really like this little maintenance area. It gives really strong crowded vibes. I think you should move the tools and such onto the spaces next to the structures instead of over them since we can't do that in-game.

I just replaced one of the excess tanks with a rack and put it all there.

> This airlock without a wall on the other side of it looks worse than the errored out black shoes.

Intentional, it's in the "worse" part of the base. The flow is such that the part that the Syndicate doesn't "care" about is extremely dilapidated, and has horrible aesthetics.

> I agree that the number of signs is a little overkill (even still). These are the ones I would remove to make it sensible.

I removed the one next to the passive vent.

> Keep in mind that players can't make these small floor subtypes, so when they go to restore the area they'll frustratingly have to pick up all the small tiles and put them in a dedicated area. On another note, for the lore, I don't think there's nearly enough trash in here. Or crazed scribbles either.

Honestly when you mentioned the thing with the small floor subtypes, I thought it was clever to have it be an "outdated" style that they'll have to work around. This is not meant to be easy street. As far as "crazed scribbles" for the lore, they burn all the stuff. Good point on the trash, though, I murked that up a bit.

> I think you should give them a small little cubby around here to grow basic foods since they've run out of supplies and remove one of those donk pocket boxes. Probably with dirt. Maybe a bit of unstable mutagen, as a treat..

I gave them a mound of soil in the nanotrasen room and a pack of potato seeds (ha ha). There's also now a water tank (no plumbing sorry) and a water bottle. I'm not certain how well anyone can abuse botany to make them space-proof in any way, so I don't want to chance it. 

> Adult bookcase instead of random? Too far?

Yeah, disagree.

> I think this little area would be an ideal space to practice ghetto surgery if they recover that body outside.

I'm confused, why would you want to recover that body and do surgery on it?

> If you aren't interested in my other entrance defense suggestion, might I suggest adding a shield barrier setup here? Gibbing: Fun for the Whole Family!

Nah, I don't want to "give it away".

> You should add a camera here if you're going to have a photo album. I would even go so far as to add a listeningstation version so we can have a persistent catalogue of people being miserable or puking all over themselves in here.

I copy-pasted that from the original listening station, but that's a good idea. I mapped a new subtype in with a camera.

> No air alarm in the maintenance area.

It doesn't have scrubbers nor vents, so I don't believe it needs any.

> The actual syndicate balloon should absolutely be a version that has lost all its helium and drags limply behind you, but that's absolutely out of scope.

That'd be funny.

>Space plating instead of catwalk here

FUCK.

> Oh, also there is no scrubber here and the passive vent isn't attached to anything.

That's intentional, it's meant to be a "work-in-progress".

</details>



That's what it looks like now.

**Comment by Addust** [comment]
merge this.

**Comment by Addust** [comment]
WHY IS THIS NOT MERGED

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
