### PR TITLE
gives salt shakers a suicide_act

### PR DESCRIPTION
**Pull request by PKPenguin321**
“No! I must kill the salty ghosts” he shouted
The radio said “No, John. You are the salty ghosts”
And then John was a salt.

merge token: https://github.com/tgstation/tgstation/pull/17983

### CODE REVIEW

**Comment by tedward1337** [comment]
Finally

**Comment by PKPenguin321** [comment]
I don't want to change the ID

**Comment by PKPenguin321** [comment]
so this is good to go

**Comment by optimumtact** [comment]
FEED ME SALT OF PLAYER

**Pull request merged**
