### PR TITLE
Fixes the lack of cameras in drone bays across maps

### LINKED ISSUE #58030: Explorer drone rooms don't have cameras
## Reproduction:

The explorer drone rooms on Meta and Delta don't have cameras installed roundstart. Unconfirmed for Tram and Kilo.

Also: the Deltastation drone room has no firelock between it and the cargo bay.

### PR DESCRIPTION
**Pull request by Red-byte3D**
## About The Pull Request
Fixes:  #58030
## Why It's Good For The Game
Drone bays need cameras since they are a part of the department
## Changelog
:cl:
fix: Fixes the lack of cameras in drone bays across maps you may now operate your drones safely.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Armoury is the british spelling, changing it would be against coding guidelines.

**Comment by InsaneRed** [comment]
> Armoury is the british spelling, changing it would be against coding guidelines (we don't enforce spelling british/american and discourage people changing other's spelling to suit their preferences)

i did it because again the inner camera is called armory when the outer is called armoury so its for consistency rather then spelling but if its that big of a problem i will revert it?

**Comment by YakumoChen** [comment]
Yeah it just leads to bikeshedding, keep the original spelling

>be me, HoS
>drinking tea and eating chips at bar
>suddenly trouble at sec, rush over
>armoury broken into, someone wrote "red is gay color" on wall
>seethe
>beat wanker with night sticks, have to spend 20 minutes fixing mistake
>soon all is right with the world
>message on wall now reads "red is gay **colour**
>God save the Queen

**Comment by BootlegBow** [comment]
"Grammar and Formatting"

**Comment by InsaneRed** [comment]
agony

**Pull request closed without merging**
