### PR TITLE
Ants can now be synthesized

### PR DESCRIPTION
**Pull request by Y0SH1M4S73R**
## About The Pull Request

Adds the `REAGENT_CAN_BE_SYNTHESIZED` flag to ants, allowing strange seeds to create ants, maint pills to contain ants, and Odysseus syringe guns to produce ants.

## Why It's Good For The Game

https://www.youtube.com/watch?v=UpPx7E27Bc8

## Changelog
:cl:
balance: Ants can now be produced by plants, maintenance pills, and the Odysseus
/:cl:

### CODE REVIEW

**Comment by Ryll-Ryll** [comment]
Has science gone too far?

**Comment by KittyNoodle** [comment]
He he, ant plant.

**Comment by Time-Green** [comment]
This will also inadvertantly add ant geysers

**Comment by Y0SH1M4S73R** [comment]
> 
> 
> This will also inadvertantly add ant geysers

That's a weird way to say anthill.

**Comment by Kylerace** [comment]
how is this a fix

**Comment by Blevruz** [comment]
> 
> 
> how is this a fix

being unable to synthesize ants is a glaring oversight & ruins my immersion

**Comment by Kylerace** [comment]
not a fix

**Comment by KittyNoodle** [comment]
> This will also inadvertantly add ant geysers

Good

**Comment by Rohesie** [comment]
Odysseus producing it? Let's not.
Seek a maintainer to approve it beforehand if you want to re-open it.

**Comment by TheBonded** [comment]
> Odysseus producing it? Let's not.
> Seek a maintainer to approve it beforehand if you want to re-open it.

Yes, because odysseus producing felinid mutation toxin, lexorin, and cyanide are fine, but the chem that takes like 200 units to crit someone is too far.

**Pull request closed without merging**
