### PR TITLE
Arena Shuttle

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Killing bubblegum now unlocks a new shuttle for purchase.
/:cl:

Here I go pushing the boundaries of good taste again

The shuttle has four portals in the place of airlocks when you attempt to board it.

The portals take you to an arena filled with necropolis/lava turfs and arms you with the doomslayer chainsaw (leading to you seeing demons, regenerating health, etc).

To escape the arena (and actually board the shuttle) you have to bump the escape portal while dragging a severed head.

This means at least half the crew will die if they want to escape.

Why I think this will be a good idea:

Doom chainsaw fights are fun

Players like to blow off steam after a long round

It will be a rare treat. There are only around 10 players who have even killed bubblegum more than once.

People who really, really don't want to participate can take the pods.

Headmins can always just turn it off and leave it admin only if this somehow happens every round.

http://i.imgur.com/VhMIjYa.png

### CODE REVIEW

**Comment by lzimann** [comment]
add to the unbuyableshuttles txt aswell please

**Comment by Supermichael777** [comment]
make sure to make the entry portal remove any heads brought along for the ride(NO CHEATING).

**Comment by InsaneHyena** [comment]
> Buy this shuttle as a captain
> Get headbanned for killing a lot of people as nonantag

**Comment by Kromgar** [comment]
I want to know what the ash drake, legion, and colossus shuttle will be like.

**Comment by MimicFaux** [comment]
pictures please.

**Comment by SweaterKittens** [comment]
@Supermichael777 I feel like if the crew can coordinate well enough to both gather heads, restrain themselves from free valids, AND survive the arena and come out on the other side, they should damn well be able to.

**Comment by KorPhaeron** [comment]
Need to make it less dark in the shuttle, need to fix landmarks not moving with the shuttle

**Comment by Supermichael777** [comment]
robotics can literally print heads

**Comment by Iamgoofball** [comment]
Maybe if people didn't hate death so much

**Comment by calzilla1** [comment]
Post pics

**Comment by Niknakflak** [comment]
How will (mostly new) people know what to do?

**Comment by KorPhaeron** [comment]
It tells you what to do when you go through the portal

**Comment by ExcessiveUseOfCobblestone** [comment]
pics?

**Comment by calzilla1** [comment]
>pics?

**Comment by PKPenguin321** [comment]
Kor"no pics"Phaeron

**Comment by SweaterKittens** [comment]
>I think it should stay as a surprise. We already know how it functions, it'll be way better if it's a mystery the first time we step foot on it.

**Comment by ChemicalRascal** [comment]
Yeah but what if it's garbage

**Comment by SweaterKittens** [comment]
Kor does good work, I have faith.

**Comment by KorPhaeron** [comment]
Alright it has a picture of the random walls and lava in a large room I hope you're happy

**Pull request merged**
