### PR TITLE
Ghost Camera!

### PR DESCRIPTION
**Pull request by RemieRichards**
- Adds a special camera that can see ghosts (if the ghost is orbiting something then they are NOT shown, to avoid power/meta gaming)
- Chaplains spawn with a ghost camera
- Ghost cameras can be tablecrafted with a camera and some holywater (10 units)

GhostCamera

### CODE REVIEW

**Comment by GunHog** [comment]
Tasty :+1:

**Comment by KorPhaeron** [comment]
Viral marketing for fatal frame 5

**Comment by as334** [comment]
So much yes :+1:

**Comment by PKPenguin321** [comment]
>;GHOSTS, IF YOU CAN HEAR ME, STAND ON TOP OF THIS CHAIR IN FRONT OF ME IF DICK MCTRAITORSON IS A TRAITOR!
>*click*
>THERE'S A GHOST IN THE PICTURE! KILL HE!

**Comment by Dorsisdwarf** [comment]
>trusting a ghost

Yeah right. If you wanna kill a guy based on what the consequenceless dead have to say, thats on you

**Comment by Metacide** [comment]
Sounds pretty cool, thanks. :+1: 

I like to think Dorsisdwarf is right about the meta too.

**Comment by RemieRichards** [comment]
Well originally Goof wanted me to not even add the "if ghost orbiting dont show in picture" and just leave it ALL to admins, and tbh I don't think that's fair, hence why I made ghosts orbiting things not appear.

I think dealing with someone trusting those from beyond is something the admins could do easily with minimal effort.

**Comment by Nienhaus** [comment]
Just make it black and white or slightly green and we can be true Ghost hunters!

**Comment by Metacide** [comment]
Black and white +/- green tint could certainly make ghost photos stand out and look nice and spooky. Would be pretty neat if it's reasonably possible.

**Comment by PKPenguin321** [comment]
i'm not saying that i don't like this feature, because i do like this feature
but basically any interaction with the dead can be used to metagame, which is an unfortunate reality

**Comment by as334** [comment]
That's why we *ban* for metagaming

**Comment by Razharas** [comment]
@RemieRichards

**Comment by RemieRichards** [comment]
Son of a

**Comment by Saegrimr** [comment]
Hey~
what about... you know... 

Librarian

GHOST REPORTER

**Comment by RemieRichards** [comment]
@Saegrimr you can craft one.

**Comment by Saegrimr** [comment]
Yeah I suppose, but having it that easily craftable makes it less interesting.

**Comment by RemieRichards** [comment]
Holywater is both rare enough but not too rare, it's at that "you can get some if you want to" level, which is about the same level the camera should be at.

**Pull request merged**
