### PR TITLE
[S]Revert "Dismemberment "

### PR DESCRIPTION
**Pull request by Shadowlight213**
Causes merge conflicts with prs. Was controversial tbh.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
u make me sick

**Comment by Shadowlight213** [comment]
Dismemberment crashed server. Rip

**Comment by hornygranny** [comment]
ban this sick filth

**Comment by Aliannera** [comment]
help

**Comment by Robustin** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: x :100:

**Comment by Dorsisdwarf** [comment]
Wowsers.

Why did it crash live and not during the testmerge, I wonder

**Comment by Incomptinence** [comment]
I'm conflicted. I wanna chop chop but its a mess.

**Comment by ChangelingRain** [comment]
did not actually crash server/10

**Pull request closed without merging**
