### PR TITLE
Adds additional holocarp colours

### PR DESCRIPTION
**Pull request by coiax**
- Adds the Sand, Seashell, Coral, Salmon, Sunset and Riptide colours
  to the holocarp colour pool.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
What purpose does this serve?

**Comment by coiax** [comment]
It... adds colours to the holocarp colour pool?

**Comment by Dorsisdwarf** [comment]
Is the game improved by having sunset-colored holocarp?

**Comment by coiax** [comment]
Holocarp currently have a much smaller colour pool than the other themes for guardians; which really increases the chance of a duplicate colour selection, which really sucks given their theme as existing in a shoal.

**Comment by Dorsisdwarf** [comment]
Fair enough.

**Pull request merged**
