### PR TITLE
Exit from mecha in zero gravity now instant.

### LINKED ISSUE #44024: space fly abort mecha exit
## Round ID:
108663

## Reproduction:
try exit from mecha when it fly in zero gravity

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
fix#44024
Exit from mecha in zero gravity now instant.
## Why It's Good For The Game
Bad when you cant exit from spacedrifting mecha.
## Changelog
:cl:
fix: Now you can exit from mecha drifting in zero gravity.
/:cl:

### CODE REVIEW

**Comment by AcapitalA** [comment]
This issue is VERY overlooked, considering you can GBJ yourself this way. Good to see a fix being PR'd for this issue.

**Comment by ExcessiveUseOfCobblestone** [comment]
basically when you move it resets the do_after right?

**Comment by GunHog** [comment]
Yes, a mech drifting in space will reset the exit timer, effectively trapping a pilot in the mech.

**Comment by ExcessiveUseOfCobblestone** [comment]
sorry I was having trouble with the engrish and wanted to make sure I was on the same page.

**Pull request merged**
