### PR TITLE
[MDB Ignore] Make shuttle windows deconstructable

### LINKED ISSUE #58558: Shuttle windows cannot be deconstructed
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
/obj/structure/window/shuttle can no longer be deconstructed like regular reinforced/regular windows. Using a welder with combat mode off you try to fix the window, and smack the window if combat mode is off. Other tools you just smack the window regardless of intent or right/left click.

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
-renames shuttle windows to /window/reinforced/shuttle in all files so that it inherits normal deconstruction
-I also renamed window/plasma/reinforced  to window/reinforced/plasma because window/reinforced is the main of reinforced deconstruction. This allowed me to delete a few chunks of copy pasted code 
Fixes: [#58558](https://github.com/tgstation/tgstation/issues/58558)

## Why It's Good For The Game
-something that should have been decon'able now is
-window names in code make more sense now (at least to me?)

## Changelog

:cl:
add: shuttle windows can now be deconstructed
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
is this... not inherited from normal windows?

**Comment by Mooshimi** [comment]
> is this... not inherited from normal windows?

no. play a round and try. the pod windows aren't deconstructable

**Comment by newfren** [comment]
Also if you build a window out of titanium glass, it's also not deconstructable.

**Comment by Mooshimi** [comment]
> Also if you build a window out of titanium glass, it's also not deconstructable.

image
that's actually what this is, a shuttle window

**Comment by ATH1909** [comment]
okay, I did some codediving and found the actual problem here

image

shuttle windows aren't subtypes of reinforced windows, but they have the reinf variable set to TRUE

image

the code for deconstructing normal windows is skipped over if reinf is TRUE and you're not in one of the deconstruction states that reinforced windows share with normal windows

image
shuttle windows start in a reinforced window-exclusive deconstruction state due to their reinf variable being TRUE

image
but the code for deconstructing windows in the reinforced window-only stages is only in the code for subtypes of /obj/structure/window/reinforced

which /obj/structure/window/shuttle isn't

**Comment by ATH1909** [comment]
in summary, a quick fix for this would involve just removing the reinf = TRUE line from shuttle windows, and a longer fix for this would be doing some refactoring to window deconstruction code so that some clueless dev down the line won't cause this bug to crop up again by setting reinf to TRUE for a window that isn't a subtype of /obj/structure/window/reinforced

**Comment by Mooshimi** [comment]
> okay, I did some codediving and found the actual problem here
> 
> image
> 
> shuttle windows aren't subtypes of reinforced windows, but they have the reinf variable set to TRUE
> 
> image
> 
> the code for deconstructing normal windows is skipped over if reinf is TRUE and you're not in one of the deconstruction states that reinforced windows share with normal windows
> 
> image
> shuttle windows start in a reinforced window-exclusive deconstruction state due to their reinf variable being TRUE
> 
> image
> but the code for deconstructing windows in the reinforced window-only stages is only in the code for subtypes of /obj/structure/window/reinforced
> 
> and /obj/structure/window/shuttle is not a subtype of /obj/structure/window/reinforced

The reason it's under reinforced I think is logically because it's a "shuttle" and "pods" window. While not iron rod reinforced, it is reinforced with titanium. It also needs the longer decon path or it would be untellably easy to sabotage all of the pods.

**Comment by necromanceranne** [comment]
That doesn't change the fact that this isn't exactly intuitive and you should honestly refactor the code, the code comments even say about as much and this is still skirting around the issue that holy fuck this is a lot of copypasted code jesus christ.

**Comment by Mooshimi** [comment]
> That doesn't change the fact that this isn't exactly intuitive and you should honestly refactor the code, the code comments even say about as much and this is still skirting around the issue that holy fuck this is a lot of copypasted code jesus christ.

okay done if this is what you meant

**Review by Mothblocks — CHANGES_REQUESTED** [review]
add the path change here

https://github.com/tgstation/tgstation/tree/master/tools/UpdatePaths

**Comment by Mooshimi** [comment]
> add the path change here
> 
> https://github.com/tgstation/tgstation/tree/master/tools/UpdatePaths

did this

**Review by Mothblocks — APPROVED** [review]
Balls in your court now: @EOBGames @Maurukas, has been test merged for a bit without causing problems

**Comment by EOBGames** [comment]
> Balls in your court now: @EOBGames @Maurukas, has been test merged for a bit without causing problems

well, it all seems to be in order, and if it's been testmerged without issue it should be fine

**Pull request merged**
