### PR TITLE
Makes the flightsuit not a straight upgrade from the CE/Engineer hardsuits

### PR DESCRIPTION
**Pull request by Iamgoofball**
R&D doesnt need to be able to print hardsuits that are immune to acid/fire/viruses/75% of radiation

including the no slowdown on the suit + 20% damage resist across the board

### CODE REVIEW

**Comment by Iamgoofball** [comment]
dont even get me started on the fact these retarded things have a whole processing subsystem and 1K lines of code

**Comment by KorPhaeron** [comment]
They cost as much as a mech its reasonable to expect they'll be better than something you spawn with

**Comment by Iamgoofball** [comment]
Is this before or after t4 material cost reductions kor?

**Comment by KorPhaeron** [comment]
well a mech would cost less with t4 parts as well so that suggests the t4 parts are the problem

**Comment by Iamgoofball** [comment]
If you'd like me to nerf R&D's production across the board because we gave them free engineer gear then sure

**Comment by KorPhaeron** [comment]
It isn't free though? It has (had?) mineral costs before we added upgrades that eliminated mineral costs for some reason

**Comment by Iamgoofball** [comment]
we all know materials are free after you upgrade the miners gear the first time

**Comment by KorPhaeron** [comment]
I think given a choice between things being expensive and worth building and things being cheap and not worth building players would prefer the former

**Pull request closed without merging**
