### PR TITLE
Removes dreamstation Z5

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
As dream now uses lavaland, doesn't seem worth having an extra asteroid map.

@ChangelingRain are you okay with this?

### CODE REVIEW

**Comment by ChangelingRain** [comment]
yeah sure nothing on it is important
the only thing that matters is the floor coloring and that's not too important/hard to replicate

**Comment by KorPhaeron** [comment]
@ChangelingRain 

Isn't your gulag blown up as well?

**Comment by ChangelingRain** [comment]
The shuttle doesn't exist so it doesn't matter a lot

**Comment by Jordie0608** [comment]
I called this ( ͡° ͜ʖ ͡°)

**Pull request merged**
