### PR TITLE
Deja Vu

### PR DESCRIPTION
**Pull request by 4dplanner**
## Changelog
:cl:
add: The deja vu effect (previously only used by rewind camera) now resets all your limbs and damage to the point it was added after 10 seconds (as well as the original position reset)
add: The deja vu effect cannot resurrect the dead, but will heal their corpse 
add: New limbs fall off, old ones re-attach
add: Regenerative sepia cores add a deja vu effect before healing instead of a timestop
add: The rewind camera rewinds 2 times to distinguish it from the regenerative core
/:cl:

### CODE REVIEW

**Comment by 4dplanner** [comment]
whoops I based this on the wrong branch

**Comment by ATH1909** [comment]
I KNOW I'VE BEEN IN THIS PLACE BEFORE

**Comment by Repukan** [comment]
Welcome to the True Man's World

**Comment by knacker48** [comment]
You didn't clarify last time. how long is the gap between you using the regen sepia and its effect taking place? Also does this revive you if you die before it takes effect?

**Comment by 4dplanner** [comment]
@knacker48  adjusted the changelog to clarify those points

**Comment by MimicFaux** [comment]
The 'heal body, not revive' is good.

**Pull request merged**
