### PR TITLE
Makes the Icebox Cursed Spring an underground only ruin

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

This PR makes it so the cursed spring can only spawn in the lower levels of Icebox. 

## Why It's Good For The Game

The cursed spring... is not very good. 
Here's a playback of what happens in LITERALLY every round the spring is generated on the top level.

- Assistant finds it 5 minutes in
- Every tider who didn't roll antag jumps into it
- They self-antag with their transformation.
  - Morph
  - Changeling Headslug
  - Ash Drake
  - Statue
  - Blobbernaut

Every. Time. 

The concept is cool but it's wayyy to abused currently.

At the very least, by moving it to a lower level only, it makes it much more difficult and dangerous to find. 
This way not every crewmember who didn't roll antag can make a pilgrimage to the pool to antagroll.

Also it's a pool of water there shouldn't be open space underneath it. That doesn't make sense. Checkmate

## Changelog

:cl: Melbert
balance: Icebox's cursed spring now only spawns on the lower levels of the moon.
/:cl:

### CODE REVIEW

**Review by Maurukas — APPROVED** [review]

**Comment by Shadowflame909** [comment]
> They self-antag with their transformation.
> * Morph
> * Changeling Headslug
> * Ash Drake
> * Statue
> * Blobbernaut

This is against the rules.

Ahelp and start banning!

**Comment by Ryusenshu** [comment]
Better would be to remove these forms from the pool instead of making it useless and only for miners to accidentally fall in.
Though i dont see the problem here, tiders jump in cause they either dislike icebox, are bored or want to have fun as a creature.

Also what Shadow says holds weight: 
They dont gain Antag Status, if they do shit bwoink em

**Comment by Shadowflame909** [comment]
> Better would be to remove these forms from the pool instead of making it useless

I'm a big polymorph advocate and I can already say, this pool was super nerfed to even get added. All roundtype altering stuff got removed, and you can only use it once at all. So your more likely to turn into one of the multi dozen friendly mobs like a bat, Ian or butterfly then anything that can do any damage.

Nerfing it again would be pointless, like a d20 without the 20. It's just a removal or nothing at this point

**Comment by thgvr** [comment]
It was against the rules to self-antag with drones, too. Now look where we are.

**Comment by Maurukas** [comment]
@MrStonedOne Minor config update. This file exists for downstreams to disable ruins.

**Comment by Shadowflame909** [comment]
How many maintainers do we have???

**Pull request merged**
