### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by optimumtact** [comment]
include the revision heading people always forget to grab it

**Comment by MrStonedOne** [comment]
knowing the revision has literally never been helpful

**Comment by optimumtact** [comment]
k

**Comment by duncathan** [comment]
:-1:
What problem is this PR solving?

**Comment by optimumtact** [comment]
I think I've come around to mso's side on this, the issue template does just create noise

**Comment by Iamgoofball** [comment]
stop remaking PRs when you get told no

https://github.com/tgstation/-tg-station/pull/15981

you dont get special treatment for being host

**Comment by optimumtact** [comment]
this is a different approach

**Comment by Iamgoofball** [comment]
no, it's removing the issue template and expecting a little note to be more specific to work

we've asked players many times to be specific in their reports

asking politely obviously doesn't work, as shown by the time before issue templates

**Comment by duncathan** [comment]
@tgstation/commit-access 
I won't make a decision on this cuz mso gets pissy when I "rage maintain my own code" so it's up to y'all

**Comment by phil235** [comment]
@MrStonedOne We have people who can't even be bothered to follow a template that has four bolded single-sentenced simple question. What do you think is going to happen with a three lines paragraph between parenthesis titled "Note". 
People are going to see two paragraphs named "Note" and "Admin" with contents between parenthesis, they're going to shrug and delete all of it without caring about what they say.

**Comment by PKPenguin321** [comment]
yes, this will certainly unbalance the delicate issue reporting meta.

**Comment by Cheridan** [comment]
After skimming through some issues, most people either ignore the template and delete it, or just add snarky comments like

**Why is it a problem, or what should have happened?**
BLOODY OBVIOUS M8

More information is nice in theory but I'm kind of with YotaXP in that they mostly just generate extra noise and don't really help people give constructive reports.

**Pull request merged**
