### PR TITLE
Adjusts Dark Gygax Equipment and stats, gives nukies a mech support bag.

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Since the gygax was so heavily nerfed beyond just losing it's stun actuators, the Dark Gygax is an overpriced piece of shit that is lucky to kill even one person, let alone multiple people due to it's incredibly terrible loadout, lack of actual damage output, no real advantages in any situation over what an assault borg could bring in the same situation for nearly half the price, and most of it's equipment rendered useless or unusable due to a combination of immunities and power restrictions the dark gygax never could overcome due to having only a hyper capacity power cell and base parts. As a result, I've adjusted some of the stats to more heavily emphasize it's speed and desire to get in close and personal with people. 

Additionally, the ammo bag it would have had is now replaced with a mech support bag. This bag contains a toolbelt with tools and some ammunition for the mech. The toolbelt contains an inducer and the highly illegal combat wrench.

The dark gygax:
Has better deflection (15 -> 20)
Has higher punch values (25 -> 30)
Has a scattershot shotgun
Has both armor modules.
Has a bluespace cell. So you can go fast.

The support kit comes with:
Four scattershot reloads.
A toolbelt with a special syndicate inducer and a combat wrench.

**Edit:** Thanks to zawo for making a new combat wrench sprite when I was having trouble figuring out the shape of an energy wrench.

Here is my attempt:
Screenshot 2020-02-03 14 04 05

Here is what we ended up with:
39e5af2efa

A pipe wrench. Which probably explains why it's normal sized.

## Why It's Good For The Game

Imsxz once told me he was impressed I even killed people in this mech, and I'm admittedly surprised too.

## Changelog
:cl:
add: A mech support bag.
add: Combat wrench.
balance: Made the dark gygax significantly better by adjusting equipment and stats.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
actual state of admins in 2020 making a PR like this, absolute audacity of it

**Comment by Tharcoonvagh** [comment]
❄️ ???

**Comment by Ryll-Ryll** [comment]
Mech support bag should have sticky notes in it that read "DON'T ABANDON THE MECH" to post on your teammates' faceshields

**Comment by HomocidlePancakes** [comment]
Look at that nerd not knowing the antag freeze is over.

Any chance we can get back the SPEEDY STUNS?

**Comment by necromanceranne** [comment]
No.

**Comment by necromanceranne** [comment]
@Ryll-Ryll I'll do you one better and make a separate pr for motivational stickers to tell people they're doing a good job.

**Comment by itseasytosee** [comment]
Yikes

**Comment by PKPenguin321** [comment]
I would die for the combat wrench

**Comment by trollbreeder** [comment]
Friendship ended with medical wrench
Now combat wrench is my best friend

**Comment by carlarctg** [comment]
combat wrench looks really dumb. i recommend just respriting it to be a blood red monkey wrench (what the tf2 engineer uses)

**Comment by necromanceranne** [comment]
It's finish and all, go away bot!

**Review by kriskog — APPROVED** [review]
Okay, lets give it a go.

**Pull request merged**
