### PR TITLE
Removed blood brother flashes

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

Blood brothers no longer gets flashes
They now dap up whoever they wish to convert

https://github.com/tgstation/tgstation/assets/70376633/3aabb6ab-330d-4220-8630-25ed633e1dab

(accidentally recorded this with audio muted but picture there was a quiet slap sound)
## Why It's Good For The Game

Its more discreet and cant be used to easily antag check someone by just pickpocketing them roundstart and guessing whether their role has super easy access to a flash roundstart
also its pretty funny

## Changelog
:cl:
add: Blood brothers get an action button/spell/whatever you wanna call it to dap up an adjacent target to convert them into a Blood Brother
del: Blood brothers no longer get a flash to convert
/:cl:

### CODE REVIEW

**Comment by Metekillot** [comment]
Wuts the mattuh? Dee CIA got you pooshing too many pehncils?

**Comment by improvedname** [comment]
I don't like this since you can convert people without them having a say against it, it could essentialy lead people who normally have protection from you by flashing into a forced position to be forced to play with you with them having no way to respond to you

if people are pickpocketing you for your flash and then conclude your a bloodbrother and valid you then thats them playing in bad faith and thats a admin issue.

**Comment by DrDiasyl** [comment]
Flash was visible in hand while this "action" is not, which means people cannot predict that you're going to try and convert so they can try to run away if they want to.
Maybe make it a pseudo-item? Like a slapper hand?

**Comment by mc-oofert** [comment]
imagine complaining about receiving free antag

**Comment by DrDiasyl** [comment]
> imagine complaining about receiving free antag

This still doesn't remove the fact it lacks any feedback of something happening or about to happen.

**Comment by mc-oofert** [comment]
> > imagine complaining about receiving free antag
> 
> This still doesn't remove the fact it lacks any feedback of something happening or about to happen.

if you watched the video there is feedback about the former

**Comment by DrDiasyl** [comment]
> > > imagine complaining about receiving free antag
> > 
> > 
> > This still doesn't remove the fact it lacks any feedback of something happening or about to happen.
> 
> if you watched the video there is feedback about the former

What about the other?

**Comment by mc-oofert** [comment]
> > > > imagine complaining about receiving free antag
> > > 
> > > 
> > > This still doesn't remove the fact it lacks any feedback of something happening or about to happen.
> > 
> > 
> > if you watched the video there is feedback about the former
> 
> What about the other?

not every antagonist should have a loud tell that "guys im valid come at me or run from me"

**Comment by Wallemations** [comment]
WHAT IS UP MY DIGGITY DOG!!!!

image

**Comment by MatrixOne500** [comment]
> imagine complaining about receiving free antag

I don't enjoy playing antag so being BB'd is always a feels bad moment because it derails my shift and forces me to do stuff I don't want to do in order to not leave the other person hanging.

It's a funny PR but it doesn't really make sense and you get even less of a warning, I'm not a fan of the change from the mechanical level.

**Comment by mc-oofert** [comment]
> > imagine complaining about receiving free antag
> 
> I don't enjoy playing antag so being BB'd is always a feels bad moment because it derails my shift and forces me to do stuff I don't want to do in order to not leave the other person hanging.
> 
> It's a funny PR but it doesn't really make sense and you get even less of a warning, I'm not a fan of the change from the mechanical level.

what do you think of Revolutionary, Blood cult, and Hypnosis

**Comment by Dawnseer** [comment]
> what do you think of Revolutionary, Blood cult, and Hypnosis

Don't forget the heretic lunatics

**Comment by DrDiasyl** [comment]
> > > imagine complaining about receiving free antag
> > 
> > 
> > I don't enjoy playing antag so being BB'd is always a feels bad moment because it derails my shift and forces me to do stuff I don't want to do in order to not leave the other person hanging.
> > It's a funny PR but it doesn't really make sense and you get even less of a warning, I'm not a fan of the change from the mechanical level.
> 
> what do you think of Revolutionary, Blood cult, and Hypnosis

The point is that you can notice them (revs and hypnotics will take out the flash, cultists will take out the funny hand) so you have at least some time to react. While in this situation you are silently tapped and are instantly converted.

**Comment by DrDiasyl** [comment]
Also just found that there is a dap-up in the emotes, it's *dap (person name). I might make this play when using it for more feedback.

**Comment by mc-oofert** [comment]
> Also just found that there is a dap-up in the emotes, it's *dap (person name). I might make this play when using it for more feedback.

it has no sound nor any cool text

**Comment by DrDiasyl** [comment]
> > Also just found that there is a dap-up in the emotes, it's *dap (person name). I might make this play when using it for more feedback.
> 
> it has no sound nor any cool text

You can add one!

**Comment by MatrixOne500** [comment]
in a perfect world you could accept or reject the dap the same way you would a high five, and then you'd only get BBs who want to help. If they reject they'd be not allowed to talk about the attempt IC. And it's a bro moment to actually get your dap accepted. I think it'd be cool.

Obviously, that's a perfect world scenario and in reality you'd just get validhunted.

One nice thing about the dap is that there's a *dap emote already so it's way less conspicuous to do a dap attempt than to try and flash them (to do the emote currently you type *dap <name> from what I know). So maybe a rejectable dap conversion might be worth at least a test. It's not great IC grounds to arrest and brig you for trying to fist bump someone.

**Comment by DustanHache** [comment]
While this definitely is more in flavor AND is safer for BB, there needs to be some kind of safety mechanism in place for people who have BB bans so that 1) people who dont want to play blood brother dont get blood brother and 2) people who have actually betrayed/been banned from it for other reasons don't keep passing it on.
This is a current issue with the flash conversions too, and it's not like downstreams have yet to fix it either.

**Comment by DrDiasyl** [comment]
> While this definitely is more in flavor AND is safer for BB, there needs to be some kind of check in place for people who have BB bans so that 1) people who dont want to play blood brother dont get blood brother and 2) people who have actually betrayed/been banned from it for other reasons don't keep doing it. This is a current issue with the flash conversions too, and it's not like downstreams have yet to fix it either.

Oh yeah, just make it not convert anyone who has BB enabled, this will solve all the problems to be honest.

**Comment by DaydreamIQ** [comment]
Does it still have a % chance to get a 3rd or 4th blood brother?

**Comment by mc-oofert** [comment]
> Does it still have a % chance to get a 3rd or 4th blood brother?

yes

**Comment by CCC23** [comment]
MA MAN

**Comment by DustanHache** [comment]
> If you get converted to a conversion antag you're banned from, your body gets ghost roled. We already have measures in place to handle bad actors who get converted.

I can tell you, with multiple Ahelp tickets to prove it, that if it is present it is NOT functioning for BB.

> Part of SS13 is adapting to circumstance or losing. Sometimes you don't get to build your chem factory because the SM exploded so you have to do maintenance chemistry. Sometimes you get converted to antag when you wanted to chill. That's part of the game.

Unrelated, but still true.

**Comment by moocowswag** [comment]
> I can tell you, with multiple Ahelp tickets to prove it, that if it is present it is **NOT** functioning for BB.

its not working for any conversion antags, cult and rev also fail to ghost you

**Comment by ZephyrTFA** [comment]
dap me up brudda

**Review by ZephyrTFA — CHANGES_REQUESTED** [review]
since there is zero tell to this ability it needs to respect them having BB disabled in prefs

**Comment by Loafin34** [comment]
> > I can tell you, with multiple Ahelp tickets to prove it, that if it is present it is **NOT** functioning for BB.
> 
> its not working for any conversion antags, cult and rev also fail to ghost you

it ghosts me ever since i asked for a cultban and i usually ahelp if its lowpop to ghost me out of it anyways

**Comment by ZephyrTFA** [comment]
This just in, slap is actually louder than a flash

**Review by ZephyrTFA — APPROVED** [review]

**Comment by Jacquerel** [comment]
> since there is zero tell to this ability it needs to respect them having BB disabled in prefs

I will block a PR which does this, BB should not be turned into a voluntary antagonist.
The conversion must be function on both the willing and unwilling to exist in the game.

**Comment by optimumtact** [comment]
> since there is zero tell to this ability it needs to respect them having BB disabled in prefs

As far as I am aware are no instances of antag prefs applying for in game conversions and it's not our intention to let people opt out of conversion through OOC means other than ghosting after ahelping, the risk for the converter is simply too high, so it needs to be managed contextually by an admin deciding if it's okay and a ghost can assist the converter.

**Comment by DustanHache** [comment]
> > since there is zero tell to this ability it needs to respect them having BB disabled in prefs
> 
> 
> 
> As far as I am aware are no instances of antag prefs applying for in game conversions and it's not our intention to let people opt out of conversion through OOC means other than ghosting after ahelping, the risk for the converter is simply too high, so it needs to be managed contextually by an admin deciding if it's okay and a ghost can assist the converter.

That's not the concern, the concern is that it is going through active antag bans (which is not goodness when compared with other conversion antags.)

**Comment by optimumtact** [comment]
There is nothing about zephyr's comment that indicate it has anything to do with antag bans given they clearly said preferences, antag bans must be respected in all cases.

**Comment by ZephyrTFA** [comment]
> > since there is zero tell to this ability it needs to respect them having BB disabled in prefs
> 
> As far as I am aware are no instances of antag prefs applying for in game conversions and it's not our intention to let people opt out of conversion through OOC means other than ghosting after ahelping, the risk for the converter is simply too high, so it needs to be managed contextually by an admin deciding if it's okay and a ghost can assist the converter.

this was hashed out with jacq, pr good as is and I've been semi yelled at

**Comment by ZephyrTFA** [comment]
> > > since there is zero tell to this ability it needs to respect them having BB disabled in prefs
> > 
> > 
> > 
> > As far as I am aware are no instances of antag prefs applying for in game conversions and it's not our intention to let people opt out of conversion through OOC means other than ghosting after ahelping, the risk for the converter is simply too high, so it needs to be managed contextually by an admin deciding if it's okay and a ghost can assist the converter.
> 
> That's not the concern, the concern is that it is going through active antag bans (which is not goodness when compared with other conversion antags.)

If by go through antag bans you mean ghosting the idiot who got antag banned

**Comment by Deadgebert** [comment]
the whole point of the original BB flash PR was so you could be antag buddies with people you like to play with. what i've seen is that people usually just grab the most robust player they can find and use them for green text. this was okay because there was some form of counterplay.
i don't want to be randomly dapped on by a player i've never spoken to before with zero counterplay.

just don't get your flash pickpocketed?

**Comment by mc-oofert** [comment]
> the whole point of the original BB flash PR was so you could be antag buddies with people you like to play with. what i've seen is that people usually just grab the most robust player they can find and use them for green text. this was okay because there was some form of counterplay. i don't want to be randomly dapped on by a player i've never spoken to before with zero counterplay.
> 
> just don't get your flash pickpocketed?

this PR changes nothing about what you said

**Comment by Deadgebert** [comment]
> this PR changes nothing about what you said

sorry, i wasn't very clear. dapping bypasses eye protection, it has no sound queue, it has no object associated with it in hand. there is no way to see if someone is going to try to dap you, there is no way to prevent it, there is nothing that can be done.

also on a semi-related note. is it possible to dap a nukie? 🤔

**Comment by DrDiasyl** [comment]
Can you dap up Command or Security as well?

**Comment by mc-oofert** [comment]
it is as previously not possible to dap up security, the mindshielded, other blood brothers and also your objective targets

**Comment by zxaber** [comment]
BB is lower priority than cult and I believe revs, but beats Traitor. I have no idea about Nuke Ops, but in all likelihood Ops and BB objectives coincide anyway.

If the only reason we hate flash conversion is roundstart metachecks, we could just give BBs an action button to silently bluespace in the flash to their hand whenever they're ready for it. This PR has a lot of work put in for it, but how flashes interact with the rest of the game is nice.

**Comment by Mothblocks** [comment]
> Its more discreet
Not a benefit, the non-discreetness is intentional

> and cant be used to easily antag check someone by just pickpocketing them roundstart and guessing whether their role has super easy access to a flash roundstart

Admins should be dealing with this

>  also its pretty funny

I guess so

**Comment by mc-oofert** [comment]
its over guys

**Comment by Gaxeer** [comment]
> BB is lower priority than cult and I believe revs, but beats Traitor. I have no idea about Nuke Ops, but in all likelihood Ops and BB objectives coincide anyway.
> 
> If the only reason we hate flash conversion is roundstart metachecks, we could just give BBs an action button to silently bluespace in the flash to their hand whenever they're ready for it. This PR has a lot of work put in for it, but how flashes interact with the rest of the game is nice.

Or implant flash in BB's hand.

**Comment by EuclidianGeometer** [comment]
could this maybe be reworked to be less discreet? playing a loud sound effect or something? I like the flavor a lot and i think it makes more sense than it being brainwashing like revs- surely the complaint of 'it's too discreet' can be addressed?

**Pull request closed without merging**
