### PR TITLE
Fixes not being able to interact with windows

### PR DESCRIPTION
**Pull request by lzimann**
This restores the old adjacency check. I'm not sure if it has any side effect, but on testing it worked fine.

Closes #24994

### CODE REVIEW

**Comment by xxalpha** [comment]
Note https://github.com/tgstation/tgstation/issues/25036

**Comment by lzimann** [comment]
Not related to this.

**Comment by AnturK** [comment]
Why this way ? I feel this is more hacky solution, logically you check adjacency of the user to the object not the other way around.

**Comment by xxalpha** [comment]
Yeah, didn't phil make an entire refactor for adjacency flags?

**Pull request closed without merging**
