### PR TITLE
Some cult fixes

### PR DESCRIPTION
**Pull request by ChangelingRain**
Converting only heals 75% of brute and burn damage.
The offer rune will actually glow now.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
"fix"
"balance change"

**Comment by ChangelingRain** [comment]
My pr got merged before I could adjust it reeeee

**Comment by PKPenguin321** [comment]
misleading tags maintainer abuse reee

**Comment by TechnoAlchemisto** [comment]
good change but it is a balance change

**Pull request merged**
