### PR TITLE
Adds friendly commendations

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
Adds a config option to enable little kindness commendations, disabled by default. When enabled and the emergency shuttle launches back towards centcom near the end of a round, the game polls random players who joined (5% recommended) on if there was a character who they noticed being kind. They can then name the character, and if they're found and still around, they get anonymously commended!
[](https://i.imgur.com/upB0WUm.png)
_note: i removed the ability to leave messages, ignore that part_

Commended players get a little heart next to their name in OOC for the next 24 hours, though they can disable it early in the OOC preference menu. Admins can also anonymously commend people through the player panel for the end of the round, though it does ask to please use it sparingly.

## Why It's Good For The Game
I like giving people little opportunities to spread positivity, and 24h of having a little heart icon next to your name seems like the perfect level of petty where it's nice to get it, but not significant enough to try gaming the system for. <3

## Changelog
:cl: Ryll/Shaps
add: Adds a config option for OOC kindness commendations! When enabled, a small percentage of the crew gets asked if anyone made their round better, and those people will get a little heart next to their name in OOC for 24h!
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
you should make this a leaderboard so the guy who is multi-logging to cheat the random hardcore leaderboard multi-logs to compliment people lmao

**Comment by Ryll-Ryll** [comment]
The thought of people being obsessively nice just to score internet points did appeal to me, but then i remembered people would probably spend half an hour on deadpop servers to farm it and i died inside a bit

**Comment by Qustinnus** [comment]
our players depress me

**Comment by ATH1909** [comment]
yet more favoritism towards staticnamers smh my head my head

**Comment by ATH1909** [comment]
if they make a typo in the name of the character, does the notification thingie tell them that?

what if two people have the exact same name? can I name myself "Ryan Cobb" to steal Ryan Cobb's internet points?

**Comment by Ryll-Ryll** [comment]
It just loops through suggesting names of people who have minds and clients until it runs out, then it lets you try again. You get 3 tries to name and confirm who you want

also disturbing seeing all these thumbs up but only one :heart:

**Comment by Iamgoofball** [comment]
dont default stuff to off by default, default it to on by default if it's a new feature

**Comment by Ryll-Ryll** [comment]
There's no point to having it on for lowpop 5 person servers, large servers can enable it

**Comment by Shadowflame909** [comment]
A powergamers ultimate tool.

Tfw you compliment the guy in the mech so they have to exit out another pop up while you're blasting them at end game.

Good PR though

**Comment by wesoda25** [comment]
I sort of dislike the OOC heart, sort just makes me think this will end up being a popularity contest. Should just be a nice little moment when you see one pop up at round end.

**Comment by Fikou** [comment]
24 hours for a commendations is way too high i think, should just be for the duration of next round or 1 hour

**Comment by HomocidlePancakes** [comment]
I don’t get it, literally why? If there is a guy that I liked I won’t do some stupid anonymous commendation, I’ll go in OOC and say “Hey, Clown, I think you were pretty based this round”.

This is fucking stupid.

**Comment by Qustinnus** [comment]
homocidal is this the only way you can express your opinion because I can tell you it's not how you'd get one of these commendations you grumpy fart

**Comment by HomocidlePancakes** [comment]
*angry grumbles intensify*

Ok
1)I like grumbling
2)Dedicated feature for saying “Thank You” is silly
3)If this gets merged, I want a dedicated feature for farts.

**Comment by Qustinnus** [comment]
deal

**Comment by Qustinnus** [comment]
but im not adding i'll get accused of brapposting again

**Comment by HomocidlePancakes** [comment]
Ok, I took the screenshot of this conversation. Gonna do the PR within this month.

**Comment by optimumtact** [comment]
@HomocidlePancakes talked a lot of shit and ya quit

adios

**Pull request merged**
