### PR TITLE
My disappointment is immeasurable, and my day is ruined. Renames the power-fist to power-puncher and removes "fisted" from the attack verbs

### PR DESCRIPTION
**Pull request by Iamgoofball**
```
[no] ATTACK: John Doe(jondoe69) power fisted The Suspect(suspect_the) with The power-fist (NEWHP: 78) (captain's office)
[no] EMOTE: suspect_the/(The Suspect) : <b>The Suspect</b> appears visibly aroused. ((captain's office)
```

You lost your power fisting privileges. This was a shameful display from all involved. Names censored to avoid harassment of users as one user in this was not consenting to the ERP that occurred.

### CODE REVIEW

**Comment by Arianya** [comment]
:-1: Do not punish the masses for the actions of the few. That is the act of a tyrant.

**Comment by bubberducky2** [comment]
fists you

**Comment by Iamgoofball** [comment]
@Arianya The power-puncher is a family friendly replacement.

**Comment by Arianya** [comment]
Power-fist is a household name and this change diminishes the amusing item substantially. It's like changing a hoover to be a sucke- _ooooh..._

**Comment by Therapist1** [comment]
MSO goof is doing the thing again

**Comment by Ziiro** [comment]
250px-sneed s_feed_and_seed

**Comment by Iamgoofball** [comment]
@Therapist1 i thought we could trust the players to keep it to giggling about "lol, fisted", but no, players had to take it too far

**Comment by Tlaltecuhtli** [comment]
this is actually to prevent getting dmca'd from todd
also dont mind me if i leave this link here
https://store.steampowered.com/bundle/6527/Skyrim_Special_Edition__Fallout_4_GOTY/

**Comment by Arianya** [comment]
I'm pretty sure a Games Workshop exec somewhere just vomited at the insinuation that Fallout invented power fists.

**Comment by deathride58** [comment]
Git gud

**Comment by Iamgoofball** [comment]
oh man games workshop is gonna sue bethesda now

**Comment by fludd12** [comment]
perhaps we should start a petition to remove cyberboss as a maintainer because cyber is a term used for sexting

**Comment by BebeYoshi** [comment]
I can't believe /tg/ has so much fetish content...

**Comment by zamolxius** [comment]
how about powerglove

**Comment by Cyberboss** [comment]
@fludd12 you just made my list

**Comment by fludd12** [comment]
@Cyberboss oh god i was joking

**Comment by Arianya** [comment]
I think my favourite part of this PR is a hippie player also telling goof to get fucked from an entire different repo.

**Comment by PKPenguin321** [comment]
@ziiro what did they mean by that?

**Pull request closed without merging**
