### PR TITLE
Makes every emote keybindable

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: ninjanomnom
add: You can keybind any emote
/:cl:

image

### CODE REVIEW

**Comment by Shadowflame909** [comment]
break dancing is now a skill

**Comment by RaveRadbury** [comment]
We're dark souls now

Seriously though, how difficult would it be to have like 5 or so blank emote keybinds so players can assign *clap and other emotes as well?

**Comment by TheVekter** [comment]
Thank fuck. Best change so far. Speedmerge.

**Comment by necromanceranne** [comment]
I'm binding flip to my mouse 1 so I can flip as I make spessmen horizontal.

**Comment by optimumtact** [comment]
you boomers were all complaining about keybinds a second ago

**Comment by necromanceranne** [comment]
Lol I'm a hotkey zoomer so I didn't even notice any changes at all

**Comment by Tlaltecuhtli** [comment]
is *fart next?

**Comment by MCterra10** [comment]
Based and redpilled, now do it for *deathgasp

**Comment by carlarctg** [comment]
add a spin hotkey too wtg

**Comment by nicbn** [comment]
Tactically flip midcombat to avoid being clicked
>stonks

**Comment by CRITAWAKETS** [comment]
*wag hotkey when

**Comment by Quartich** [comment]
I already had macros bound to my mouse for \*flip and \*spin

**Comment by ninjanomnom** [comment]
I realized after I went to bed I should just make all emotes automatically get a keybinding datum rather than do them one at a time like this. Expect that in a bit

**Comment by Couls** [comment]
_notices kiss emoji 😳_

**Comment by TheVekter** [comment]
Okay for real, deathgasp being bound is asking for trouble. Maybe let's not do that one.

**Comment by cacogen** [comment]
inb4 emote cooldowns as i spam clap at the speed of light

**Comment by PKPenguin321** [comment]
you can already do this with external macros :V

**Comment by Tharcoonvagh** [comment]
WHAT HAVE YOU DONE

**Comment by RaveRadbury** [comment]
It's missing *wag and the silicon emotes.

**Comment by wesoda25** [comment]
> It's missing *wag

feature

**Comment by optimumtact** [comment]
if you wanted to do species specific emotes you'd probably need another interface of some kind

**Comment by ninjanomnom** [comment]
Those should be in there, the image just isn't able to show them all because they didn't fit on the screen

**Comment by Tharcoonvagh** [comment]
Add a cooldown so people won't spam your face and ears and won't act like a budget singularity by binding *flip to wasd

**Comment by cacogen** [comment]
@Tharcoonvagh 

If only anybody tested pull requests (other than the authors, ~~some~~ most of the time) before they were merged. This one will probably add the necessity of an emote cooldown, if only because of the ones with sound. I remember *flip lost its `John Fagtron flips!` text because of spam (which I guess was before repeat messages were condensed).

**Note:** I fully support this pull request.

**Comment by ShizCalev** [comment]
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE

**Comment by ShizCalev** [comment]
while this looks good on paper, past experience dictates that this absolutely will be abused. 

hard no from me.

**Review by ShizCalev — COMMENTED** [review]
while this looks good on paper, past experience dictates that this absolutely will be abused. 

hard no from me.

**Comment by MCterra10** [comment]
What exactly is abusable about emotes? With borgs spin might be but that's up for debate. In addition, if you're the type of person who is going to abuse emotes (if they can be), you're the type of person who will just use an AHK script to achieve the same thing

**Comment by optimumtact** [comment]
you can already spam emotes with ctrl + up and enter

**Comment by Tharcoonvagh** [comment]
This is why I'm worried, @cacogen

**Comment by Couls** [comment]
me after the PR was merged:

ezgif-2-a1f4e6140047

**Pull request merged**
