### PR TITLE
Properly removes an unused plant

### PR DESCRIPTION
**Pull request by nianjiilical**
## About The Pull Request

Back when I made #46986, I was originally going to add electric limes, then cut them based on feedback. Apparently they're still in the code, though, because people reported spawning them via xenobiology.

## Why It's Good For The Game

remove ghost lime

## Changelog
:cl:
fix: Properly removes an unused plant.
/:cl:

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
time to not play xenobio ever again

**Review by optimumtact — APPROVED** [review]
I will miss the electric lime

**Comment by nianjiilical** [comment]
well now i feel bad for removing it

**Comment by cacogen** [comment]
add clockwork oranges we can make it make senes

**Pull request merged**
