### PR TITLE
adds EVA to common access

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

HoP (or anyone with id console access) can give EVA access to non-command crewmembers

## Why It's Good For The Game
Its a bit weird that the HoP can't give EVA access to non-command crewmembers since people always tide in or ask the AI or a head of staff to open the shutters for them when they plan on exploring space, Also this gives the HoP more stuff to do

## Changelog
:cl:
qol: EVA can be given now in common access slots for non-command crewmembers.
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
Disagree with this. EVA usage is something command would want logged. It allows crew to take important equipment to perform activities outside the station. Doesn't make sense for an ordinary crew member to be able to access and distribute that without a special ID.

**Comment by SomeoneYouProbablyKnow** [comment]
Oh. It's just the access category. Neat. One the one hand tiny access creep but on the other silver IDs are not hard to come by, if you have access to the console 90% of the time you have at least one ID to open the shutters with

**Comment by starrm4nn** [comment]
> Oh. It's just the access category. Neat. One the one hand tiny access creep but on the other silver IDs are not hard to come by, if you have access to the console 90% of the time you have at least one ID to open the shutters with

Yeah but giving a silver ID just for EVA is pretty overkill and most of the time the shutters are open so no harm in giving the access to crew :p

**Comment by moocowswag** [comment]
EVA storage is socially common access / not high security, even most sec players will not do as much as raise an eyebrow when someone breaks into EVA storage

It contains materials that kickstart the round and allow the station to take off on every map except birdshot because for some reason the person that designed birdshot decided they wanted it to be a map with no materials and a much slower start/waste of time.

**Comment by EricZilla** [comment]
Hop QOL buff hell yeah, I hate having to get silver IDs just for this, and having to ruin the clown's ID

**Comment by DrDiasyl** [comment]
Gateway was placed in Common access for the same reason - to allow crew members to explore without breaking in.

By giving EVA access you can log the person whom you gave it. Right now AI/HoP just opens the shutter round start making it extremely jarring to find out who got access to Space.

Knowing who has access to Space is rather important as Security, as you can now pinpoint who is that unknown with a EVA suit bombing Armory

**Pull request merged**
