### PR TITLE
[READY] Flashbangs now ignores same-tile protection properly

### LINKED ISSUE #21493: Flashbangs not ignoring protection on same tile
I'm too lazy to fix this myself
Flashbangs aren't stunning people with protection who are holding them or on the same tile
Kinda takes away the skill ceiling of timing them.

### PR DESCRIPTION
**Pull request by silicons**
Title.
:cl: Mekhi
experimental: Flashbangs now properly ignore protection if they are on the same tile as you. Learn to time grenades.
\:cl:

Fixes #21493

### CODE REVIEW

**Comment by kevinz000** [comment]
@lzimann  rude

**Comment by kevinz000** [comment]
why the hell is a nerf PR on the most overpowered item in security getting downvotes?

**Comment by PKPenguin321** [comment]
memesters and sec players

**Comment by kevinz000** [comment]
SECURITY PLAYERS GET OFF MY PR YOU GUYS NEED TO TIME YOUR GRENADES INSTEAD OF USING A BUG AS A CRUTCH.

**Comment by KorPhaeron** [comment]
This is a bugfix and I will be merging it, worry about the code not the emojis

**Comment by kevinz000** [comment]
yeah well I'm going to test it later as I can't switch branches while fixing flightpack conflicts

**Comment by PKPenguin321** [comment]
also i thought flashes ignored protection if you were on the same tile *or* you were within 1 tile

**Comment by CPTANT** [comment]
This used to already be the case, I have no idea why you could suddenly just stand on top of flashbangs again without worry.

**Comment by PKPenguin321** [comment]
kevinz that wasnt a joke

**Comment by kevinz000** [comment]
Meh, it only did it if you're on the same tile :^)

**Comment by PKPenguin321** [comment]
it's a buff after all

shut it down

**Comment by TechnoAlchemisto** [comment]
CL it as a fix "have been nerfed" is way to vague

**Comment by kevinz000** [comment]
My initial code made the flashbang ignore protection in a 3x3 centered on itself, but I just changed it to only ignore protection for the tile ontop of itself. Ready to merge and tested.

**Comment by PKPenguin321** [comment]
Rrrreeeeeee

**Comment by jughu** [comment]
Just make it 3x3 @kevinz000 so i can time it and defeat the captain by exact precision :^)

**Comment by PKPenguin321** [comment]
Yeah leave the 3x3

**Comment by PKPenguin321** [comment]
Triggered

**Pull request merged**
