### PR TITLE
Ash drake armor and explorer suit slot now fits crusher

### PR DESCRIPTION
**Pull request by ItsTisme**
## About The Pull Request

you can now put your crusher inside drake armor and explorer suit

afbeelding

## Why It's Good For The Game

Why not? modsuit fits it and the pka fits so why not the axe?

## Changelog
:cl:
balance: crusher fits inside suit slot of ash drake armor now
balance: crusher fits inside suit slot of explorer suit now
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
OH NO, YOU ADDED ONE LINE OF INSIGNIFICANT BUT QUALITY OF LIFE CODE, /TG/ IS FALLING APART, WAHT HAVE YOU DOOOOOONE good work thanks blud its hard to ball on the megafauna if i cant carry anything due to having too much baller pwr gamer miner loot

**Comment by Cheshify** [comment]
Isn't the crusher a bulky, massive axe you need to hold with two hands?

**Comment by Overuseddart** [comment]
> Isn't the crusher a bulky, massive axe you need to hold with two hands?

You’d need to attack with two hands using a two handed axe, due to the design of the axe not necessarily the weight

**Comment by Autisem** [comment]
> Isn't the crusher a bulky, massive axe you need to hold with two hands?

it fits in your mod suit so. Also i'd not say its any larger then the O2 tank you can carry inside of it so

**Comment by DaydreamIQ** [comment]
Considering the crusher does less damage than the other axe variants and can't break windows I really don't see why this hasn't already been a thing

**Comment by 1393F** [comment]
why not the HECK suit too?

**Comment by CRITAWAKETS** [comment]
> powercreep

to be honest it fucking needs it, the crusher is hilariously bad nowadays

**Comment by GuillaumePrata** [comment]
The crusher being a giant weapon that you can't carry comfortably around is flavorful as fuck and a good balance lever, we were allowed to add *A LOT* of power to the crusher trophies because of this limitation.

The wendigo trophy as an example, a 40 damage weapon you can easily carry around is not something any crewmember has access to for good reasons.

Making crushers more portable is a mistake in the long run as we won't have as much freedom when designing upgrades.

**Comment by castawaynont** [comment]
> The crusher being a giant weapon that you can't carry comfortably around is flavorful as fuck and a good balance lever, we were allowed to add _A LOT_ of power to the crusher trophies because of this limitation.
> 
> The wendigo trophy as an example, a 40 damage weapon you can easily carry around is not something any crewmember has access to for good reasons.
> 
> Making crushers more portable is a mistake in the long run as we won't have as much freedom when designing upgrades.

Implying lavaland has gotten anything but a couple of ruins and nerfs to every piece of gear imaginable

**Comment by DaydreamIQ** [comment]
> The crusher being a giant weapon that you can't carry comfortably around is flavorful as fuck and a good balance lever, we were allowed to add _A LOT_ of power to the crusher trophies because of this limitation.
> 
> The wendigo trophy as an example, a 40 damage weapon you can easily carry around is not something any crewmember has access to for good reasons.
> 
> Making crushers more portable is a mistake in the long run as we won't have as much freedom when designing upgrades.

Most of the trophies do jack shit if the target isn't a mob so its really only an issue against antags like Dragon and Spiders who lets be honest, if you're in melee range of a dragon and you aren't dead, The dragon is already going to die. And Wendigo is only available on ONE map out of the many we have so that's not really the best example.

**Comment by GPeckman** [comment]
> The wendigo trophy as an example, a 40 damage weapon you can easily carry around is not something any crewmember has access to for good reasons.

The Wendigo trophy requires you to kill Wendigo, the megafauna with an AoE attack around itself every time it moves, with the crusher, a melee weapon. The death bolt attack makes it hard enough to kill already, I don't think this is going to happen often enough to be a concern.

**Comment by Autisem** [comment]
> Making crushers more portable is a mistake in the long run as we won't have as much freedom when designing upgrades.

you dont anyway? its already non-conspicous for a shaft miner to carry it and if he wants to murder with it hes not gonna be disqauted because it fits in his shit for combat armor(high melee armor sure but exceptionaly weak bullet and NO wound armor)

If THIS is what makes it OP its already OP and you just thought about it for the first time

**Comment by GuillaumePrata** [comment]
> you dont anyway?

What? We can't design powerful upgrades to it?

> also aside from the wendigo trophy, no trohpy effects non lavaland mobs so even if you have every trophy it does not matter

Even if that was the case, which it is not, we should push the crusher to be a monster killing tool on the station too IMO. Making it portable tool takes away from its flavor *and* makes it harder to add interesting upgrades too it without becoming an issue.

> If THIS is what makes it OP its already OP and you just thought about it for the first time

And you completely misunderstood my point, I want the Crusher to be more powerful, especially on the station.
I don't want it to get a boring buff like this one tho.

**Comment by Fikou** [comment]
i added holding the crusher as a specific feature of the berserker suit, as the specific melee suit, giving it more niches as the one that can hold all of a miner's melee weapons, this feature was then brought to the modsuit as it was the "utility" suit and the fact that you couldnt hold items in ball mode made crusher basically impossible

letting the ash drake armor which is already just a straight upgrade to the explorer suit and is made every single round where the miners are competent enough to kill an ash drake (or its ice box) hold it is just power creep and also indirectly makes the hecksuit less useful, which im not a fan of

**Pull request closed without merging**
