### PR TITLE
Makes radiaton and bomb good helmets have the FOV effect...... its not my fault

### LINKED ISSUE #80917: Radiation Hood is the new old biosuit hood
Reporting client version: 514.1589

## Issue Summary

I am aware of the nerf to the biohood as they were the get all against biohazard and facehuggers. I see their sprites are the same ish. Are the radiation hood not ment to have the vision blockers?

#consistency
Screenshot_840
Screenshot_839

## Testmerges:
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)

### PR DESCRIPTION
**Pull request by Hoolny**
## About The Pull Request
Fixes Radiation hood having normal vision 

Closes #80917 
image
## Why It's Good For The Game
It isnt but it must be done in order to remove github issues
## Changelog
:cl:
fix: Fixes Radiation Hood not having FOV blockage
/:cl:

### CODE REVIEW

**Comment by Xackii** [comment]
now no one will wear them

**Comment by SethLafuente** [comment]
> now no one will wear them

Literally every single hat with fov I dont want this but we need to shorten the amount of issues we nearly have 2,000.

do a PR that remvoes FOV

**Comment by cnleth** [comment]
I think that if you have to apologize for making a PR, you did something wrong... You're picking low-hanging fruit with this PR and I don't think closing issues is about adding something literally nobody wanted just to make a number go down.

**Comment by Exester509** [comment]
Radiation hoods have a big visor panel. Gas masks have two small circles to see through. I think there's quite a difference deserving of not having FOV

**Comment by jughu** [comment]
I wouldnt't really call it a fix we just adress these issues half adsed one time goof adds it to bio then the othet time we add it to bomb hood because same thing at this point if we gonna do it for every seperate helmet its just a GBP farm can you atleast try to check all the helmets that cover vision and if they have FoV

**Comment by SethLafuente** [comment]
> I wouldnt't really call it a fix we just adress these issues half adsed one time goof adds it to bio then the othet time we add it to bomb hood because same thing at this point if we gonna do it for every seperate helmet its just a GBP farm can you atleast try to check all the helmets that cover vision and if they have FoV

Well now your bringing a new issue into this we are only talking about https://github.com/tgstation/tgstation/issues/80917

**Comment by SethLafuente** [comment]
but sure ill add it to bomb hood why not

**Comment by Admiral-Gigaton** [comment]
> I wouldnt't really call it a fix we just adress these issues half adsed one time goof adds it to bio then the othet time we add it to bomb hood because same thing at this point if we gonna do it for every seperate helmet its just a GBP farm can you atleast try to check all the helmets that cover vision and if they have FoV

now, im not saying its a perfect solution, and by no means is it, but what if when you have the hood down, you need oxygen? otherwise you are kind of wearing a bag over your head, and suffocating yourself?. or something like that, theres always better solutions to it. (this is not adding to the PR specifically, this is adding to the conversation about the FOV nerf)

**Pull request merged**
