### PR TITLE
Nuke op costume: Battlemaid

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Nuke ops can now purchase a Battlemaid costume.
/:cl:

I saw it in a round, I thought it was a good additional costume idea.
Suggestions for additional items welcome.

### CODE REVIEW

**Comment by Militaires** [comment]
put me in the screenshot

**Comment by Iamgoofball** [comment]
okay no what the fuck

can you guys stop injecting your maid fetish into literally everything

**Comment by deathride58** [comment]
Neat

**Comment by optimumtact** [comment]
Yeah, the uplink really isn't for you to put your outfits into

add a costume vendor to the syndicate ship

**Comment by coiax** [comment]
But... we literally already have a bunch of costumes in the uplink

**Comment by optimumtact** [comment]
well they should be moved out of there, it's not a scaleable solution to just keep adding costumes to it

**Comment by Iamgoofball** [comment]
have you stopped to think that maybe the nuke ops dont need costumes to begin with

**Comment by coiax** [comment]
#34487

**Comment by optimumtact** [comment]
I think the costumes are fine I just think they should be moved to a vendor so we don't make the uplink list huge.

If you've used the traitor one, it's super annoying

**Comment by Iamgoofball** [comment]
additionally you gave them a chameleon kit with that PR you linked coiax, you dont need to add costumes because they can just do dressup with the kit

**Comment by coiax** [comment]
Do you read? It's not a functional chameleon kit, it doesn't WORK.

**Comment by Iamgoofball** [comment]
so why are you giving nuke ops a delib. broken item?

**Comment by coiax** [comment]
@Cyberboss

**Comment by AlexTheSysop42** [comment]
If the costumes are moved to a vendor it would be hard to make them cost TC

**Comment by optimumtact** [comment]
They don't need to cost TC, they're mostly cosmetic so I don't see why we should trick players into wasting valuable crystals on it.

**Comment by AlexTheSysop42** [comment]
Eh, makes sense, but the centcom one could be used to gain an advantage

**Pull request closed without merging**
