### PR TITLE
Adds a new false alarm event

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl:
rscadd: We've been picking up garbage signals from other galaxies.
/:cl:
:^)

### CODE REVIEW

**Comment by chanoc1** [comment]
why tho

**Comment by Iamgoofball** [comment]
bust metagamers

**Comment by TechnoAlchemisto** [comment]
Kor stipulated quite clearly that fake nuke ops war announcements are a no-go to the point of forbidding admins to do it.

So unless his opinion changed I don't think there is much hope for this.

**Comment by Iamgoofball** [comment]
@KorPhaeron

**Comment by PKPenguin321** [comment]
Maybe make it throw another centcomm announcement after a slightly random duration declaring that it was a false alarm?

**Comment by KorPhaeron** [comment]
How is it "busting metagamers" when the entire tradeoff of war ops is that the crew is explicitly given permission to meta/have prep time

**Pull request closed without merging**
