### PR TITLE
Boxstation rework: Multi-Z Edition

### PR DESCRIPTION
**Pull request by Iamgoofball**
Trying out this draft PR thing.

## About The Pull Request

This PR will refactor Boxstation into a new, Multi-Z experience with maintenance sub-levels, departmental stair-wells, and full multi-z support.

## Why It's Good For The Game

Box is old. Extremely old. Veeeery extremely old. Oldest map we have.

It's also extremely buggy, and we've got this brand new multi-z station system to try out and develop with.

As such, I am refactoring box to utilize it, redoing every department from the ground up. Trying out this Draft PR feature too, since its a map and it's gonna take a long ass time to do.

# THE PREP LIST:

- [X] Strip out maintenance.

- [ ] Archive each department as a separate map file.

- [ ] Strip out all piping/wiring. (bug Monster to add a button to do this to FastDMM2)

# THE CHANGE LIST

- [ ] Expand box to 4 Z-levels.

# ZLEVEL 4: The Main layer

- [ ] The main hallways.

- [ ] Arrivals.

- [ ] Escape.

- [ ] Departmental entrances.

# ZLEVEL 3: Public Access, Light Maint

- [ ] Maintenance hallways for Z-Level 4. Hallways run underneath the main hallways.Fairly well lit, mostly tiles, some plating. Minor equipment spawns.

- [ ] Power and atmos sub-station for all of the hallways.

- [ ] Public access sections of departments, and public desks. Stuff like the Bar, the Library, the Medbay Lobby, the Chemistry Desk(but not chemistry itself)

- [ ] Entrance to Departmental Stair-wells.

# Z-LEVEL 2: Private Sector, Normal Maintenance

- [ ] Maintenance hallways for Z-Level 3. Hallways run under the main rooms, and the maint hallways above. Looks like normal maintenance. Sparsely lit. More random junk

- [ ] Private areas of departments where actual work occurs. Research, Chemistry, Medical, Cargo Shuttle docking, etc.

- [ ] Power and atmos sub-station for the public departmental areas.

# Z-LEVEL 1: The Hellmaint

- [ ] Completely unlit maintenance. You are likely to be eaten by a grue.

- [ ] Power and atmos sub-station for the private departmental areas.

## Changelog
:cl:
refactor: BoxStation is now multi-z.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
how is a full grounds up re-work comparable to boxstation?  I suppose it looks more like a box if it's actually 3 dimensional, but I feel like this wont resemble box at all anymore

**Comment by actioninja** [comment]
image

**Comment by Iamgoofball** [comment]
i was significantly lied to about how far along we are on multi-z, oh well, back into the "things ill get around to when the frameowrk is done" pile

**Comment by Iamgoofball** [comment]
>when ninja beats you to the close cuz ur typing the comment

**Comment by trollbreeder** [comment]
This was a step in the right direction, but i'm not sure if it should've been box.

**Comment by Dennok** [comment]
>Archive each department as a separate map file.

Nice idea. I think about idea, make tower station. 1 or 2 z lvl's belongs to one department. And big maintenance z lvl's between it.

**Comment by Tharcoonvagh** [comment]
4 Z L E V E L S

**Comment by Dennok** [comment]
Command
Security
Service
Science
Engineering

**Pull request closed without merging**
