### PR TITLE
Adds an improved first aid kit for medical staff

### PR DESCRIPTION
**Pull request by Mickyan**
## About The Pull Request
CMO and MDs start with a first aid kit with slightly increased capacity and basic surgery tools

## Why It's Good For The Game
Doctors need tools for doctoring in the new medical landscape, also makes the starting medkit a bit more worth holding onto

## Changelog
:cl:
add: Medical staff now spawns with a first aid kit with increased capacity and basic surgery tools
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
👏 medical 👏 lathe 👏  can 👏  print 👏 surgery 👏 tools 👏  roundstart 👏  with 👏  metal 👏  and 👏  glass 👏  why 👏  add 👏  more tools👏

**Comment by Mickyan** [comment]
No

**Comment by GuyonBroadway** [comment]
The engineers can build tools with their protolathe too, why do they need loaded toolbelts!

**Comment by Shadowflame909** [comment]
we must buff the syndicate medikit to be as worth it as this is


Medical Mains in roundstarts carry saws

what do you carry gamers?

**Comment by Ratvar** [comment]
Add free shit because people are too thick to learn, and, no matter if they're dumb, we need to milk them so they better the round by doing actual medical job.
That they already can get infinite protolathe saws, then getting one roundstart does nothing but quality of life them: it's like not giving engineers tools because they can print them

**Comment by Shapsy** [comment]
Engineers get tons of free shit, it's time to spread the wealth

I feel like just making the improved medkit a more spacious box will have some kind of knock-on effect of people valuing them for general shit storage though

**Comment by Shadowflame909** [comment]
I'll trade you my medical doctor medikit for a pair of insuls

Also what Shaps says is true. Does anyone else realize how engineering has so much coveted stuff? Can put that entire department on the same level as the captain.

Lets get some bartering around here.

**Comment by Tlaltecuhtli** [comment]
this medkit is also a 14 slot box which can fit normal sized items which is op for not medical reasons
and if you are going by that argument why dont engineers spawn with yellow gloves or rcd or materials? why does sec have to gear up at brig and not spawn with all the things already?

**Comment by Shadowflame909** [comment]
says that when sec officers spawn with a limited ranged weapon at roundstart that you otherwise have to go into the depths of the armory to get,

**Comment by ExcessiveUseOfCobblestone** [comment]
can we limit medical boxes to medical items if we are plan on using the medkit for surgery holding?

also would be nice if the medibelt also held surgical tools (like a toolbelt of sorts!)

**Comment by Mickyan** [comment]
I can do that

The medibelt does hold surgery tools btw

**Comment by ExcessiveUseOfCobblestone** [comment]
mfw I never tried to put them on the belt, just assumed they didn't work and carried aduffle bag all this time

i'm never playing ss13 again jesus

**Comment by Fhaxaris** [comment]
> 👏 medical 👏 lathe 👏 can 👏 print 👏 surgery 👏 tools 👏 roundstart 👏 with 👏 metal 👏 and 👏 glass 👏 why 👏 add 👏 more free shit for no reason👏

Engineers can print their own tools, the same logic can be applied to that.
> Add free shit because people are too thick to learn, and, no matter if they're dumb, we need to milk them so they better the round by doing actual medical job.

What do you mean people are too dumb? Too dumb to use the auto-lathe? Pretty sure everyone knows how to use that thing, if revolution is anything go by with the number of circular saws being used.
>them: it's like not giving engineers tools because they can print them/get from vendor

Yes it is, you spotted the flaw in your argument, good job.

Good QoL PR

**Comment by Ratvar** [comment]
"flaw in your argument"
I was kind of supporting the PR

**Comment by ExcessiveUseOfCobblestone** [comment]
Ben Shapiro OWNS github posters with FACTS and MEDICAL KITS

**Pull request merged**
