### PR TITLE
[s]64x64

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
I'm ready

**Comment by Bill-Luxe** [comment]
))))

**Comment by Cheridan** [comment]
Does it still make the map editor not work

**Comment by Iamgoofball** [comment]
MSO and I are still testing things

**Comment by WJohn** [comment]
Alternatively we could use fastdmm which does work with 64x64, or so I hear.

**Comment by Iamgoofball** [comment]
That too

**Comment by xxalpha** [comment]
Let's not use that just yet.

**Comment by Iamgoofball** [comment]
Give a good reason

**Comment by xxalpha** [comment]
It's fairly obvious.

**Comment by Iamgoofball** [comment]
Fuck off and come back when you get your head out of your ass

**Comment by Bawhoppen** [comment]
like I said still doubt this is happening

**Comment by GeneralGoose** [comment]
why 64
go for 4k spessmen experience

**Comment by Incoming5643** [comment]
Forcing people to use software in beta is bad form

**Comment by Iamgoofball** [comment]
>forcing

What the fuck are you saying

**Comment by Shadowlight213** [comment]
If this doesn't work with the inbuilt dmm editor, it's kind of a bad idea.

**Comment by WJohn** [comment]
yeah but the inbuilt dmm editor is trash

all hail fast dmm

**Comment by Shadowlight213** [comment]
@WJohn sure it can be trash, but requiring an external editor is horribly unintuitive.
I mean, think about if we switched to a new code format that was way faster and ran in dream daemon, but required an external compiler.
How horrible would that be for anyone trying to learn the code?

**Comment by Cheridan** [comment]
Yes, abandoning the built-in map editor and leaving it in a non-functional state, even if it isn't as good as a third party editor, is a major problem.

**Comment by Iamgoofball** [comment]
we should see if lummox is willing to fix the existing map editor then

if he wont, we can't let outdated tech hold us back when we have available alternatives

**Comment by xxalpha** [comment]
We don't have available alternatives.

**Comment by Iamgoofball** [comment]
did you miss the whole "there is a new map editor available that is literally an available alternative" bit

**Comment by optimumtact** [comment]
@xxalpha it seriously annoys me when people play 20 questions and riddles on Github.

This isn't a forum for showboating and roundabout sarcasm, make a clear technical comment, always try to be explicit as possible about what you mean and what your reasoning is.

Subtleness helps no one and only leads to misunderstandings and PR clutter.

**Comment by WJohn** [comment]
Here I sprited a toolbox in about 5 minutes using the new color palette. The palette definitely saves some time, I can say that much. Probably need to make the toolbox bigger but I have no real idea how big anything needs to be relative to humans at the moment.

**Comment by Iamgoofball** [comment]
Perfect, I'll grab the color palette, make some recolors, and get that implemented for the next test.

**Comment by Kromgar** [comment]
I really hope we can get this in. Having higher resolution sprites would be amazing.

**Comment by optimumtact** [comment]
Believing that it will get in when byond clearly isn't ready to support it is a jest of the highest proportions.

**Comment by Iamgoofball** [comment]
its supported by the client the only problem we had was literally DM being a shit

**Comment by optimumtact** [comment]
That's not true goof
http://www.byond.com/forum/?post=2127717

**Comment by Supermichael777** [comment]
wow a toolboxthat actualy looks like metal

**Comment by optimumtact** [comment]
stale and byond just isn't ready

**Pull request closed without merging**
