### PR TITLE
fixes BVAK injectors having salburol instead of perficilin

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: the TB antidotes injectors now actually cure TB and have some omnizine so you dont die from perfluoride
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
How the hell do you butcher the names so bad when you have them spelled correctly right there

**Comment by vuonojenmustaturska** [comment]
isn't that 200 seconds of omnizine healing

**Comment by Tlaltecuhtli** [comment]
omnizine is the only thing that counters pref from giving you poisoning and has the same metabolization rate

**Comment by ExcessiveUseOfCobblestone** [comment]
was this a merge conflict or something? I specifically remember fixing this TWICE reeeee

**Comment by nemvar** [comment]
Why 20 units of omnizine and 15 of perf? Feels weird because salbu had 20 units.

**Pull request merged**
