### PR TITLE
Harvesters are more fun to play

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan, Robustin
rscdel: Harvesters can no longer break walls, construct walls, convert floors, or emit paralyzing smoke.
rscadd: Harvesters now remove the limbs of humans when attacking, can heal OTHER constructs, have thermal vision, and can move through cult walls.
rscadd: Harvesters can now convert turfs in a small area around them and can create a wall of force.
tweak: Harvesters are now cultists.
rscadd: When Nar-Sie is summoned, she will convert all living non-construct cultists to harvesters, who will automatically track her.
/:cl:

Harvesters are not fun right now. They break everything, emit smoke that disables SOME enemies but can't disable anyone with a mask, that smoke keeps them from seeing where the enemy is to drag them to Nar-Sie, they don't know where Nar-Sie is....
It sucks.

So, instead, they cut off limbs, can heal each other, can convert to get into areas instead of breaking walls, have some ability to corral enemies, can see mobs through walls, and know where Nar-Sie is at all times.
Like 90% of this is stolen from @Robustin's pr but less exclusive and more fun.

### CODE REVIEW

**Comment by Robustin** [comment]
Ugh, honestly this is such a tiny change from mine I don't care but at the same time it's such a small difference I can only ask... why?

I would've added these features to normal harvesters but I couldn't get a consensus from anyone.

**Comment by Armhulen** [comment]
I'd let this go through moreso than robustin's PR

**Comment by Repukan** [comment]
Don't get rid of wall breaking pls

**Comment by Repukan** [comment]
Niceu

**Comment by CPTANT** [comment]
also, can they please get night vision? 

demonic entities being hindered by not having a flashlight nearby always kinda bothered me.

**Comment by ChangelingRain** [comment]
Constructs actually do have nightvision already.

**Comment by Robustin** [comment]
I gave them (working) Night vision in my construct HUD PR. 

Joan I'll find you on  IRC and figure this out because I'd rather just let you handle this harvester stuff so I can focus on my new ending.

**Comment by ChangelingRain** [comment]
You have a point about them not looking like they'll rip your limbs off in seconds, but they have a perfectly good sprite already, and my concern is more making things fun for the harvesters than it is for making it fun for the extremely doomed remaining crew.

**Comment by FantasticFwoosh** [comment]
This is pointless @ChangelingRain objectively you've made it worse by creating immobility between non converted turf tiles.

My suggestions would be
> Keep wall smashing & building functions and add a jaunt ability
> Give Harvesters nightvision because they can't see in darkness
> Wall of force & conversion is pointless when Nar Nar is going to kill them anyway
> If not the first bulletpoint, why dont you have harvesters actively change walls & floors in a 5x5 radius to cult like a anomalous crystal, so the harvesters can have fun converting bits of the station Nar Nar missed.

**Comment by Nabski89** [comment]
If they can go through cult walls but not break them down, how do they get the harvested limbless victim back to Nar-Sie. The victims can't wallwalk too.

**Comment by ChangelingRain** [comment]
A: They can convert an area around them, letting them make spots to go through
B: They HAVE nightvision already I said that before
C: The victims can wallwalk if they're being dragged by a harvester

**Comment by Robustin** [comment]
@ChangelingRain 

The sprite I made isn't a masterpiece but its literally just an altered version of the current sprite that looks more menacing.

I never was a fan of the current sprite, it did a good job of conveying that harvesters were cancerous fart spamming floating turds but they aren't that great.

**Comment by Niknakflak** [comment]
being a human cultist is 100000% more fun than being instantly converted to a harvester.  I don't care if its your PR or robustins, both are bad ideas.

**Comment by ChangelingRain** [comment]
I can't change it away from Nar-Sie eating her cultists. Kor will murder me.

**Comment by Robustin** [comment]
Ignore @Niknakflak they don't even play the game, let alone cult, and harbor some insane delusions that sitting on an escape pod as a cultist waiting to be prodded to death is somehow "loads of fun".

**Comment by XDTM** [comment]
From the tone of his comment i think he'd rather be a cultist _and_ not be molested by prodders

**Comment by Robustin** [comment]
@XDTM 

Niknak made it clear in my thread he prefers the current system of being molested by prodders, and Kor has already declared war on anyone who tries to make the endgame survivable for cultists so this is the compromise.

**Pull request merged**
