### PR TITLE
Vent-spawned wendigos no longer create one-way portals

### LINKED ISSUE #84119: Vent spawned Wendigos drop the one way portal
Reporting client version: 515.1640

## Round ID:
[230762](https://scrubby.melonmesa.com/round/230762)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [tgui: adds tgui npm library](https://www.github.com/tgstation/tgstation/pull/83789)
- [basic firebots refactor](https://www.github.com/tgstation/tgstation/pull/83861)
- [Adds a new power storage type: The Megacell. Drastically reduces power cell consumption/storage. [MDB Ignore]](https://www.github.com/tgstation/tgstation/pull/84079)

## Reproduction:
image
This ain't really a huge issue but it seems extremely redundant and probably makes taking boulders out manually harder

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Creates a vent-specific wendigo subtype that will not spawn a portal upon death

## Why It's Good For The Game

Fixes #84119

## Changelog
:cl:
fix: Vent-born wendigos no longer create one-way portals
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
CI tests are failing because I'm adding a simplemob subtype, not because of actual issues.

**Comment by ShizCalev** [comment]
Since this is practically a one line fix, add it to the test so we can actually get this merged.

**Comment by Ghommie** [comment]
Sure, go ahead.

**Review by ArcaneMusic — APPROVED** [review]
We ball (But add it to the test first)

**Pull request merged**
