### PR TITLE
Adjust Engine Cameras / Monitors

### LINKED ISSUE #24635: Meta & Box CE singulo camera monitor not connected
[Note]: 41bb3a6d32cf2a05ed60c2c1f9a2423bbdcef12d 

New engine cameras aren't set on the CE's camera monitor.

### PR DESCRIPTION
**Pull request by Penguaro**
:cl: Penguaro
add: Added Cameras for Supermatter Chamber (to view rad collectors and crystal)
tweak: Adjusted Engine Camera Names for Station Consistency
fix: Adjusted Monitor Names / Networks to view the Engine Cameras
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
With the addition of the Supermatter Engine, many of the monitors and cameras were missing, misnamed, or pointing to incorrect networks. This Fixes #24635.

### CODE REVIEW

**Comment by Penguaro** [comment]
Maintainers, I can do this for each Map Separately if you believe that will be easier to manage.

**Comment by AnturK** [comment]
This is fine.

**Comment by Penguaro** [comment]
@AnturK - Alright, Then I'll add the other maps as well here.

**Comment by Penguaro** [comment]
Updated PR to identify original Issue.

**Comment by AnturK** [comment]
You need to have literal Fixes #... or Closes #... for github autoclose to work.

**Comment by Penguaro** [comment]
Thanks for letting me know that. I've used Git for years and am new to Github.

**Pull request merged**
