### PR TITLE
reenables fusion

### PR DESCRIPTION
**Pull request by praisenarsie**
fusion is innocent!

mso said on irc its some db problem unless you know fusion actually, really, for real crashed the server @KorPhaeron ?

### CODE REVIEW

**Comment by duncathan** [comment]
there's no harm in leaving it disabled as is

**Comment by praisenarsie** [comment]
but assmo technicians will ree

**Comment by KorPhaeron** [comment]
assmos technicians are the ones who asked me to disable it

**Comment by evsey9** [comment]
there goes any fun from traitor atmos

g'bye engi department

**Comment by CPTANT** [comment]
The fuck why is fusion removed if it doesn't crash the server

**Pull request closed without merging**
