### PR TITLE
Revert "GIANT INTENT REFACTOR (separates it into 4 different harm, help, disarm and grab procs)"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#20787

Literally broken code

https://github.com/tgstation/tgstation/pull/20787/files#diff-d6d8be3f9607785d675a459ea0eceedfR940

### CODE REVIEW

**Comment by Iamgoofball** [comment]
sad-clown

**Review by Iamgoofball — APPROVED** [review]
sad-clown
sad-clown 1
sad_clown_by_naughtyowlking-d4yi46c
3bc0c453fd528cb2a3686420da8ff556

**Comment by PKPenguin321** [comment]
nice

**Comment by optimumtact** [comment]
@Jordie0608 said he would fix it so blame him when the bugs appear

**Comment by Militaires** [comment]
@optimumtact @Iamgoofball 
exactly mfw

**Pull request closed without merging**
