### PR TITLE
Raised maximum pressure output of air pumps.

### PR DESCRIPTION
**Pull request by nullbear**
:cl: nullbear
tweak: Maximum output of air pumps has been raised.
/:cl:

as discussed in coderbus IRC.

### CODE REVIEW

**Comment by duncathan** [comment]
:+1:

**Comment by GunHog** [comment]
LET THE PLASMA FLOOOOOOOOOOOOOOOOOOOOOOOOOOOOW!!

**Comment by CPTANT** [comment]
Does this affect only portable pumps?

**Comment by nullbear** [comment]
Yes. I considered making it affect canisters, and then decided, why not make people use air pumps if they wanna pump the extra air in there.

**Comment by CPTANT** [comment]
ah, this will be pretty significant for bomb making.

**Comment by nullbear** [comment]
@CPTANT, you can already get tanks to 3039+ with canisters as it is with the setting at 1039, it just takes a bit more time.

**Pull request merged**
