### PR TITLE
You have to add pictures to PRs which are sprite/map changes

### PR DESCRIPTION
**Pull request by Buggy123**
TBH I'm getting a bit tired of people making PRs which literally only change sprites or maps but don't include pictures. I don't want to start up dreammaker just to see one fucking sprite change.

### CODE REVIEW

**Comment by praisenarsie** [comment]
no, we have icondiffbot and mapdiffbot

**Comment by Buggy123** [comment]
Oh shit I completely forgot that existed nevermind

**Comment by Rockdtben** [comment]
@Buggy123 This is not an issue. Please clarify what you want.

image

**Comment by Buggy123** [comment]
>Oh shit I completely forgot that existed nevermind

**Pull request closed without merging**
