### PR TITLE
Adds a default ban severity

### PR DESCRIPTION
**Pull request by zzzmike**
## About The Pull Request

Defaults ban severity to high so people fail their bans less due to no severity selected. I don't really care if it's high/medium/low as long as it's something.
## Why It's Good For The Game

People fail their bans less due to no severity selected.
## Changelog

:cl:
admin: changed default ban severity to high so people fail bans less often
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
This seems like a bad idea, people forgetting to set a severity is something we should catch, not silently let through

**Comment by zzzmike** [comment]
> This seems like a bad idea, people forgetting to set a severity is something we should catch, not silently let through

I see what you're saying and I would agree if not for severity being only cosmetic.

**Comment by Mothblocks** [comment]
It's technically cosmetic but practically important for admins to eyeball a person's record, we have a system at least within tgstation

**Comment by Mothblocks** [comment]
Yeah I don't think I want this sorry

**Comment by wesoda25** [comment]
Severity definitely effects how I view stuff. Lots of green and blue is "whatever" and lots of yellow and red is "oh no baby what is you doin." Not just cosmetic!

**Pull request closed without merging**
