### PR TITLE
[Dirtystation] The janitors were execu-er... educated...

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixed dirtystation vomiting all over everything.

### CODE REVIEW

**Comment by Penguaro** [comment]
Honestly, I don't mind the vomit or random spills. I'd like to see them have a chance of virus in them giving a reason to clean up.

**Comment by Repukan** [comment]
Does this also get rid of the random noises in lavaland?

I actually quite liked it even if I had to turn my music up because I was getting spooked.

**Comment by ShizCalev** [comment]
@Repukan Those are ambient sounds defined in areas/mining.dm. This doesn't affect them.

**Comment by Repukan** [comment]
Really? I only recently started hearing sounds like a faint colossus shooting and others, thought I was going crazy.

**Pull request merged**
