### PR TITLE
Changes some world.timeofday to time_stamp() so it properly formats the time

### PR DESCRIPTION
**Pull request by lzimann**
`World loaded at 510220` to `World loaded at 11:18:47`

### CODE REVIEW

**Comment by RemieRichards** [comment]
>he cant read the time.

**Comment by lzimann** [comment]
\>she can't markdown

:^)

**Comment by RemieRichards** [comment]
I can though? I'm the one who does most of the markdown for people's OPs...
I also choose to allow the \> to become a quote, because it colours it (granted, not green)

**Comment by lzimann** [comment]
no fun

**Comment by RemieRichards** [comment]
I'll kick ur ass

**Pull request merged**
