### PR TITLE
Soap now has inhand sprites

### PR DESCRIPTION
**Pull request by epochayur**
see title, addresses #35089

:cl: Epoc
fix: Soap now has inhand sprites
/:cl:

image image image

alright uhhh first sprite PR, pretty sure I did this correctly, tell me off otherwise, but if this works out then I'll start spriting some other missing inhands stuff

constructive criticism on the sprite itself is welcome too, not much to work with on 3x3 tho

also, is there a way to upload this to the webeditor without having to delete the original first?

### CODE REVIEW

**Comment by DaxDupont** [comment]
This kills the greytide

**Comment by Bawhoppen** [comment]
Why did you only add the green variant? Anyways I'm not WJ, but as an inhand this should be acceptable.

**Comment by epochayur** [comment]
@Bawhoppen laziness, I'll update this with the other soaps

**Comment by ShizCalev** [comment]
should probably throw them in inhands\equipment\custodial instead too.

**Review by WJohn — DISMISSED** [review]

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Use the specific inhands file

**Comment by Spaceinaba** [comment]
this is a very good pr

**Comment by epochayur** [comment]
@cyberboss moved it all to equipment/custodial, also includes the other soap styles, changed clown_items.dm to use the proper sprites

**Comment by KorPhaeron** [comment]
Thanks, point an admin online to this comment and tell them you add owed an antag token

**Comment by epochayur** [comment]
yusssssss

**Pull request merged**
