### PR TITLE
PanD.E.M.I.C 2200 Unique Sprite

### PR DESCRIPTION
**Pull request by Cheshify**
### Freeze Bypass approved by Mothblocks

Gives the Pandemic 2200 it's own unique sprites. Includes a unique animation, and sprites for all possible states (empty, full, broken, depowered) 

Thanks to Imaginos for teaching me to sprite well

pandemic (1)
image

## Why It's Good For The Game

Because having 3+ machines with different functions looking exactly the same is kinda wack

## Changelog

:cl:
imageadd: The PanD.E.M.I.C 2200 is now visually different than the ChemMaster
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
For clarity, you didn't need my permission for this--updating sprites to be better is in line with all freezes.

**Comment by Cheshify** [comment]
> For clarity, you didn't need my permission for this--updating sprites to be better is in line with all freezes.

Appreciate the clarity, I wasn't sure if it was or not.

**Comment by cacogen** [comment]
it fits the artstyle well

**Comment by Imaginos16** [comment]
Cool stuff!

**Pull request merged**
