### PR TITLE
Add: Diabetic Quirk

### PR DESCRIPTION
**Pull request by Floofies**
## About The Pull Request

This draft PR adds a new negative quirk named "Diabetic", which provides **-6** quirk points.

- Diabetics spawn with a small bottle of insulin pills, sugar pills, and a blood sugar analyzer.
- Diabetics process sugar at a very slow rate (0.02) and thus retain excess sugar in their blood for a very long time.
- When the Diabetic quirk holder runs out of sugar in their blood, they contract the "Hypoglycemia" disease.

The added Hypoglycemia disease progresses in 3 stages. The final stage may ultimately kill the quirk holder.

1. Headache, jitters (high heartbeat), hunger.
2. Dizziness, confusion, speech slurring.
3. Drowsiness, brain damage, seizures.

## :construction: Draft Status :construction:

**Still implementing and tweaking things based on community suggestions.**

:pushpin: **TODO:**
- [ ] ~Stop sugar metabolization when insulin is present in blood.~
- [ ] **Consider gradually increasing sugar instead of changing minimum/maximum.**
  - **IRL Diabetics reported to me that this is a more accurate reflection of how the illness actually behaves.**
- [ ] Add Hypoglycemic Shock as the OD effect for Insulin, and as a side effect of consuming it without sugar in the blood.
- [ ] Consider adding Diabetes disease to quirk holder so it's more apparent on health analyzers.
- [ ] Consider adding a chemistry recipe for insulin.
- [ ] Balance the side-effects and their progression a bit better.
- [ ] ~Add unique minimum and maximum sugar volumes for the quirk holder.~
- [x] Add blood sugar tester, a subclass of the wound analyzer.
- [x] Add sugar/glucose pills to the quirk holder.

:pill: **Possible new chemistry reaction for insulin, pending discussion:**

- Optimal pH: 7
- **1x Phenol**
- **2x Virus Food** (Virus Food recipe is milk + sugar, which makes sense for insulin production)
- **1x Probital** (Metabolizes into peptides, which is a heavy healing component for Probital use!)

## Why It's Good For The Game

Provides the Diabetic quirk as a new negative quirk with meaningful roleplay/personal impact. The quirk is meant to add another layer of challenge to the game to justify the quirk points as much as possible, and isn't really that fun to live with!

image
image

## Changelog

:cl: A.C.M.O.
add: Add Diabetic as a negative quirk.
add: Add Hypoglycemia as a disease.
/:cl:

### CODE REVIEW

**Comment by CCC23** [comment]
https://youtu.be/m6CeGgzaGSE?si=HJO2FuKFzpu3LTHV

**Comment by StarHorder** [comment]
this is so preem.

**Comment by projectkepler-ru** [comment]
Emia meaning presences in blood

**Comment by Floofies** [comment]
Still working on this! Only a few more tweaks.

Someone with diabetes informed me of some tweaks I can make, such as gradually increasing sugar over time.

**Comment by Admiral-Gigaton** [comment]
make sure normal med scanners also report blood sugar, seeing as wound scanners are just shitty med scanners, and med scanners do the same thing as wound scanners, they (or at the very least the upgraded variant) should be able to check the husk's blood sugar level. also, should the blood sugar scanner check for hypoglycemia? 

insulin+sugar medipen variant?

"QUICK, DOCTOR, WE NEED SOME INSULIN AND SUGAR IN THIS MAN!"

*shoots corpse with syringe gun full of everything but insulin and sugar*

**Comment by ExcessiveUseOfCobblestone** [comment]
is this waiting on review or something?

**Comment by Floofies** [comment]
@ExcessiveUseOfCobblestone This is a work in progress! It's almost done.

Unfortunately the feature freeze policy states you can not even work on a feature PR during a freeze. So I have been working on other things.

I will get back to working on this when it's convenient for me.

**Comment by Ghommie** [comment]
I wish someone would have told you before that pull requests before the freeze are exempt from the freeze. It's even written in the PR comment. :(

**Comment by ExcessiveUseOfCobblestone** [comment]
> @ExcessiveUseOfCobblestone This is a work in progress! It's almost done.
> 
> Unfortunately the feature freeze policy states you can not even work on a feature PR during a freeze. So I have been working on other things.
> 
> I will get back to working on this when it's convenient for me.

In the future, you CAN work on a feature during a freeze IF it was PRd beforehand (which this was). You CANT start a new feature or continue a project that hasn't been PRd. 

I thought you PRd this specifically to bypass the freeze haha :) 

If you want you can close this and rePR when you are ready to contribute to it again.

**Comment by Floofies** [comment]
Thank you! With a few more changes I will be ready to publish the PR.

**Comment by Floofies** [comment]
Still working to finish this! I will try to get this ready for review this week

**Pull request closed without merging**
