### PR TITLE
Adds 2% xeno egg spawners to all maps

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: All maps, not just Meta, have a 2% chance of receiving a xeno
egg in their Xenobiology areas. As with Meta, command receive a
classified update two minutes into the shift if an egg has been
delivered.
/:cl:

Why Metastation should be the only one with an egg spawner is beyond me.

- Most of the line chaff is with Delta, where the map merger REALLY wants to move some `{,` around.

### CODE REVIEW

**Comment by lzimann** [comment]
I honestly don't think xenos are interesting to, even if it's a small chance, spawn in every map like this.

**Comment by PKPenguin321** [comment]
Delete the changelog telling players to meta the classified announcement

**Comment by coiax** [comment]
But it was already mentioned in a changelog

**Comment by Niknakflak** [comment]
I think it should be removed from meta personally

**Comment by PKPenguin321** [comment]
That doesn't mean you need to mention it again

**Comment by xxalpha** [comment]
2% is too high in byond rng, make it 0.5

**Comment by Bawhoppen** [comment]
Slippery slope

**Comment by coiax** [comment]
@Niknakflak I look forward to seeing your removal PR.

**Comment by PKPenguin321** [comment]
% should probably be lowered. Before since it was just meta which is something like 1/5 maps, you have to first roll that map, then roll the 2% chance for xenos. This sneakily increases the odds significantly by removing the map roll

Also fix the CL!

**Comment by Kromgar** [comment]
I dunno 1% is  still pretty rare.

Also if you do it right you can begin a xeno human hybridization program its really quite effective

**Comment by WJohn** [comment]
To nobody's surprise, I'm okay with this 👍

**Comment by coiax** [comment]
Increasing the chances of this happening is the point.

**Comment by Haevacht** [comment]
why

**Comment by bgobandit** [comment]
you do realize that if you don't want xenos you can just murder the fuck out of the spawn

**Comment by Niknakflak** [comment]
I'll make the removal PR tomorrow @coiax

**Comment by Supermichael777** [comment]
the map merger did a hatchet job on delta

**Comment by coiax** [comment]
Given that an attempt to remove Metastation's egg spawner just got closed, I don't know why we're letting Metastation (which has no particularly strong xeno themes), be the sole origin of this. I like consistency.

**Comment by optimumtact** [comment]
I'm against it, in general xeno are better suited to being introduced when admins are available to guide the round. The fact that it exists on Meta is entirely down to Metacide obviously liking the idea or being influenced by someone who did.

That does not give it any reason to be extended to all our maps. In general we give mappers as much leeway as is possible with their own maps in terms of deciding how a round will play out within the map and only closely keep an eye on Box (being mostly a shared map).

**Comment by coiax** [comment]
Except the alien infestation event fires without admin intervention on a weight of 10?

**Comment by optimumtact** [comment]
Yes I agree the alien infestation event is garbage.

**Comment by Kromgar** [comment]
@optimumtact 

Its true coderbus has a hateboner for xenos

**Comment by KorPhaeron** [comment]
I don't care much either way but other maintainers seem to dislike it.

Having little quirks on each map is what makes having different ones in rotation as well.

**Pull request closed without merging**
