### PR TITLE
Added a larger afro hairstyle

### PR DESCRIPTION
**Pull request by Cruix**
## About The Pull Request

It's exactly 6 months from April 1st, so this is a date for very serious PRs only.

We've all seen that one tip at the beginning of the round:
tipoftheround

So the afro must be really big, right? Having one must be a very large sacrifice in the realm of pixel-based combat, right?

WRONG.
oldAfro
This is the largest afro currently available. Absolutely pathetic. It's not even the largest hairstyle in terms of pixel volume.

Here's a bigger one.
afros_comp
Afros

The sprite overlaps the tile above by 6 pixels, which is noticeable, but not enough to interfere significantly with gameplay (apart from having a sacrificially larger hitbox).
Afros2

This could already be done by creating a new .dmi file with larger, non-square pixel bounds, but that's a less than elegant solution. Instead, added a y offset var to hair sprite accessory datums.

## Why It's Good For The Game

The self-expressive merits of having more hairstyles should be self-evident, so I will make a mathematical argument here.

Everyone knows that the coolness of an afro is determined by its volume. As a 2-D sprite, the closet equivalent we have is area. An afro is, approximately, a circle, so the area can be calculated as πR^2, with R being the maximum distance from the top of the head to the top of the sprite bounding box.

The current largest afro has a height of 6 pixels. This new afro has a height of 12 pixels. As a result, impressiveness increases by a factor of 4:

```math
coolness_{new\ \ afro} \over coolness_{old\ \ afro}
```
```math
π12^2 \over π6^2
```
```math
12^2 \over 6^2
```
```math
144 \over 36
```
```math
4
```

This means that, for the intrusion of a mere 6 pixels into our northern neighbor's bounding box, we get **quadruple** the coolness.

## Changelog

:cl:
add: Added Afro (Huge) hairstyle
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
As funny as it is, I think we are in a hair style freeze.

**Comment by RedBaronFlyer** [comment]
Players with this hairstyle should be unable to wear hats/helmets in exchange for such a stylish hairstyle.

**Comment by Time-Green** [comment]
This is why we need barber

**Comment by atlasle** [comment]
sleepy salar?

**Comment by Jacquerel** [comment]
we need hat offsets for big hair

**Comment by itseasytosee** [comment]
Opposing this is enforcing a double standard because of that stupid floor-length hairstyle that increases your hitbox by 75% that we already have in the game.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
show me what this looks like in the prefs menu next to everything near it

**Comment by Cruix** [comment]
spritesheet

Huge afro is on the upper right.

**Review by Ghommie — APPROVED** [review]
Amazing, but I wish the button didn't crop off a chunk of this beautiful hair style (and many others), considering the buttons have plently of space to fit even the biggest of hair and beards.

**Comment by Ghommie** [comment]
Resolve the conflicts.

**Pull request merged**
