### PR TITLE
Adds a brand new, completely original map (with multiZ!)

### PR DESCRIPTION
**Pull request by Kmc2000**
:cl: Kmc2000 + Satan
add: Added a new map for /Tg/erry! It's called cram station, a station that comfortably fits into dorms on Box.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

With that explanation of this feature over, here's what it looks like!
Here's a demo video of it!
https://gyazo.com/7efbcf2af51a9d6bca50b5c6f88cbd5a

That's it, that's literally the entire map.

If you merge https://github.com/tgstation/tgstation/pull/39337 then I can replace the solars with excercise bikes as the primary source of power.

It works on highpop :^)

### CODE REVIEW

**Comment by Kmc2000** [comment]
Arrivals and escapes are fully functional, just take the MULTI-Z IMPLEMENTED LADDER

Beat you to it planetstation.

**Comment by CitrusGender** [comment]
would be a nice meme

**Comment by ninjanomnom** [comment]
This is almost beautiful.

**Comment by Kmc2000** [comment]
This is a serious buff to the freerunning trait, so please do take that into consideration :)

**Comment by Spyroshark** [comment]
METEORS HAVE BEEN DETECTED ON COLLISION COURSE WITH THE STATION

**Comment by Keekenox** [comment]
This needs to be played on high pop.

**Comment by Kmc2000** [comment]
I concur, Keek

**Comment by DaxDupont** [comment]
There's even a bed so the captain can ERP

**Comment by Kmc2000** [comment]
Dorms is tinted so the dastardly traitors can purchase their evil items

**Comment by XDTM** [comment]
Is cryo connected to the cooler? The pipe in front of it seems missing

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
they look connected, it's just that the pipe is under the floor

**Comment by Kmc2000** [comment]
@XDTM It's all connected up yeah

That's what it looks like in DM

**Comment by praisenarsie** [comment]
SMES is blocked.

**Comment by Kmc2000** [comment]
@praisenarsie you have a toolbox with tools to move the vendor in the crates, otherwise break in from the brig

**Comment by ike709** [comment]
Wasn't there already a map called efficiency station?

**Comment by Kmc2000** [comment]
Wasn't aware of it, it was either that or cramstation

**Comment by ike709** [comment]
@Kmc2000 https://tgstation13.org/wiki/EfficiencyStation

**Comment by ike709** [comment]
Call it tinystation or something.

**Comment by Kmc2000** [comment]
Nice

I'll rename it

**Comment by CitrusGender** [comment]
testmerging this on sybil next round

**Comment by Qustinnus** [comment]
fuck you @Kmc2000 literaly scammed me

**Comment by Iatots** [comment]
This already existed sans z-level a long time ago. Nice to have it back.

**Comment by Kmc2000** [comment]
https://i.gyazo.com/f2527ebede3df0e04a004deb1b2faea8.mp4

**Comment by Gumbo954** [comment]
the round on it was fun

**Comment by Bawhoppen** [comment]
Needs a tinted glass window maint tunnel so traitors can do their traitor-ing.

**Comment by Kmc2000** [comment]
merge please

**Comment by Takahiru** [comment]
this is needed.

**Comment by ninjanomnom** [comment]
We've had discussions recently around some major changes to how maps get added to the game and this map is a perfect example why. In short we want weird maps like this to be possible and encouraged but not force the maintenance of them by putting them in the main repository.

Eventually we'll probably move to remove all but one or two official maps and make it easier for servers to use unofficial maps. How we do that exactly is still being discussed.

**Comment by Capsandi** [comment]
yo replace the chem dispenser with a grinder, you can grind tons of stuff into any base chem

**Comment by Iamgoofball** [comment]
Not everything is available like that.

**Pull request closed without merging**
