### PR TITLE
Removes liver unfailure and makes alcohol do the killing thing sometimes

### PR DESCRIPTION
**Pull request by DaedalusGame**
:cl:
balance: livers don't unfail automatically every second life cycle you have to get a new one or get some corazone stat
balance: increased liver damage from alcohol significantly because apparently your liver regenerates faster than you can chug unless you drink 100 liters of bacchus blessing
fix: fixed cyber livers thinking they should fail at half durability
/:cl:

if you take too much liver damage your liver turns into a dieer haha i'm so funny also this will probably kill people from alcohol poisoning
i bet i missed something because i'm touching mobcode two hours after waking up

okay over the span of the last few hours I've learnt many things about being drunk in this game and apparently liver damage and drunkenness is based on how much alcohol is in you at the time. You can likely still safely drink shots of vodka but if you down the whole bottle (100u) you're setting yourself up for coma. Most high volume alcohol decays at regular metabolism speeds (2.5 cycles or ~5 seconds per unit) and isn't that dangerous, the obvious exception is bacchus blessing, which is really bad for your liver even at 30u.

Ideally this change will mean things like antihol and corazone will become more prominent and liver replacements might actually be beneficial especially if hearty punch's boozepwr gets upped to 90.

feedback welcome

### CODE REVIEW

**Comment by DaedalusGame** [comment]
THIS MAKES YOUR LIVER FAIL INSTANTLY

**Comment by epochayur** [comment]
we hendrix now

**Comment by DaedalusGame** [comment]
to give people liver damage?

**Comment by DaedalusGame** [comment]
No, every human has the same liver and flypeople have a weaker liver. There is a cybernetic replacement liver that has double the health as I mentioned.

**Comment by YakumoChen** [comment]
will the amount of time and research it takes to create and install a cyber liver from the department lathe that literally never sees use make it worth the chance to drink yourself into less of a coma?

**Comment by DaedalusGame** [comment]
I'm not sure if significant design flaws in terms of departmental whatevers and material distribution are really relevant for this but the upgraded cybernetic liver gives you:
- 5 times the resistance to liver damage from alcohol (doesn't affect how drunk you get)
- double max health (aka how much liver damage you can take before it fails)
- the ability to purge 1u of each toxin in addition to normal metabolism up to the toxin tolerance it has (15u, regular liver has 3u)
- 40% less liver damage from toxins past the toxin tolerance
- EMPs deal heavy damage to the liver

**Comment by newfren** [comment]
Give the bartender an upgraded liver in his locker.

**Pull request merged**
