### PR TITLE
Book binder can be unanchored with wrench

### PR DESCRIPTION
**Pull request by phil235**
Requested in https://tgstation13.science/phpBB/viewtopic.php?f=10&t=2446&sid=f9cc02cb446da3ea733b1eb015282783&start=350#p180139

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Freeeeeeeze

**Comment by Iamgoofball** [comment]
it also fixes some bugs

this is also a quality of life fix t b h

**Comment by pudl** [comment]
fyi phil you dont have to use .science anymore, and the .science forum is a bit behind on the updates

**Comment by optimumtact** [comment]
Fine to merge since it has some fixes and cleanup as well.

**Pull request merged**
