### PR TITLE
Crafting now transfers reagents from ingredients to final product

### LINKED ISSUE #80143: Toasted Seeds lack nutrients and cannot be eaten.
## Round ID:
 219990

## Reproduction:

Make Toasted Seeds
Try to eat Toasted Seeds
Realize you can't
Grind it up
Nothing in the beaker

E: After further testing, both seeds harvested from a grown plant and seeds straight from the vendor produce the same result. Other people also are unable to eat the toasted seeds.

### LINKED ISSUE #80381: Constructed Dango are not edible.
## Issue Summary

Dango that have been hand-made by cooks/whoever seem to be inedible at the moment. When var inspected it will still show them at having normal reagents and quantities, but upon grinding you will just get the metal rod back.
image

When spawning dango through the verb, they seem to work as intended.
image

## Testmerges:

None

## Reproduction:

Prepare 5 rice, 5 sugar, 2 orange juice, 2 grenadine and a rod
Construct Kasei Dango
Be unable to eat or serve this tasty treat

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
- Fixes #80143
- Fixes #80381

Based on the ingredients required reagents of the final product can differ. It now transfers the olive oil from the bottle to the toasted seeds & the orange juice and grenadine reagent from the ingredients into the kasei dango.

Snow cones are now also edible

## Changelog
:cl:
fix: crafting now transfers reagents from ingredients to final product making previously inedible foods (toasted seeds, kasei dango & snow cones) edible. Other crafted food products/items now differ in reagents based on the ingredients required.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
>Don't know why they wanted to clear the reagents after crafting. Made no sense, remove this line and it makes sense again.

The crafted food gains complexity, giving stronger speed buff, and should not make reagents out of nowhere

It was balanced out by the botany giving ingredients above 50% purity, making grown items more nutritious.

This is not a fix.

These recipes should get reagents from their ingredients, so we should give nutriments to the seeds and to whatever the dangos are made from.

**Comment by MTandi** [comment]
Another point is that people just dont bother to balance the nutriments of new food they add, making some simple food ridiculously nutritious.

I pointed out to this example when the PR was up, but it got merged regardless.

```
/obj/item/food/meatloaf
	name = "meatloaf"
	desc = "A mixture of meat, onions, and garlic formed into a loaf and baked in an oven. It's covered in a generous slathering of ketchup. Use a knife to cut it into slices!"
	icon = 'icons/obj/food/meat.dmi'
	icon_state = "meatloaf"
	food_reagents = list(
		/datum/reagent/consumable/nutriment/protein = 40,
		/datum/reagent/consumable/nutriment/vitamin = 32,
		/datum/reagent/consumable/nutriment = 32,
	)
```

Now these values apply only to map/adminspawn versions of these food items, so we are safe from the ridiculously high `food_reagents` defined.

**Comment by xXPawnStarrXx** [comment]
Is this part of what's causing snowcones to become inedible?

**Comment by SyncIt21** [comment]
> These recipes should get reagents from their ingredients,

Luckily toasted seeds require olive oil(which contains vitamins) and dango require orange juice and some other ingredient(which also contains reagents). Sure I can transfer them and see if it works.

> Is this part of what's causing snowcones to become inedible?

I think so. Haven't tested it yet.  Will let you know

**Comment by SyncIt21** [comment]
Ok reagents are now transferred from the ingredients to the final product. Also this does make snow cones edible again so that's fixed

**Pull request merged**
