### PR TITLE
Chasm fall sound

### PR DESCRIPTION
**Pull request by CreationPro**
[Changelogs]: # Added a fall sound for mobs falling into chasms, as well as a fall sound.

:cl: CreationPro
soundadd: Added a fall sound for mobs falling into chasms. You will no longer disappear silently!
/:cl:

[why]: # Making a sound while falling will vastly improve player experience, as well as make bag of holding explosions more entertaining.

### CODE REVIEW

**Comment by Time-Green** [comment]
It better be the fucking looney tunes JODELADIEHEHAHEHAHHHEAHEHAHHAHHEHAH

**Comment by Tlaltecuhtli** [comment]
nice stealth admin.txt edit

**Comment by Dorsisdwarf** [comment]
How about fuck no, it's just an ear-splitting synth buzz

**Comment by Iatots** [comment]
Why not a slide whistle?

https://www.youtube.com/watch?v=bMoJrpvqA0M&t=98s for reference.

**Comment by MrDoomBringer** [comment]
@Tlaltecuhtli its a game master line change you doofus. Its used for testing stuff, not actual admin powers on the servers.

**Comment by CreationPro** [comment]
@Time-Green Link me to it and I'll fucking do it
@SgtxRootbeer Infinite falling bug? Not sure I've seen that happen in-game, which one are you referring to?
@latos That could work. They sound kinda cartoony though. e.g. https://www.dropbox.com/s/co9x8srm5hu0cgd/slideWhistleFall.ogg?dl=0

**Comment by Time-Green** [comment]
@CreationPro i've tried adding it myself before, but I legit could never find the sound anywhere

**Comment by Ratvar** [comment]
willhelm scream g major

**Comment by CreationPro** [comment]
@ratvar https://youtu.be/f2Wf268mmp8?t=58s
Wilhelm fell down all the way into hell. 
Anyhow, that wouldn't quite work for this PR because I made all mobs make a sound, and hearing Ian do a human scream while falling down, while hilarious, would be a little out of place.

**Comment by WJohn** [comment]
yeah this chiptune thing sounds terrible. nothing like the rest of the game.

https://www.youtube.com/watch?v=XCDKJQ3Z8bU
now *this* is the right kind of sound.

just don't steal it outright, of course.

**Comment by Militaires** [comment]
make it the mario waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by epochayur** [comment]
https://www.youtube.com/watch?v=2uhxrPhVO8Y

**Comment by CreationPro** [comment]
https://www.dropbox.com/s/gtw9ox3re3ftkgg/fall2.ogg?dl=0
@WJohn How about this one?

**Review by Cyberboss — CHANGES_REQUESTED** [review]
This sounds way too retro arcade for spessmens

**Comment by ninjanomnom** [comment]
The only possible way I could see this being a feature is if mobs screamed on their way down and there was different screams per mob. If you want to set that up but provide only screams for species types that would be acceptable.

**Comment by CreationPro** [comment]
I'm actually gonna go with what ninjanomnom suggested and split this into several PRs. Closing this for now.

**Comment by ninjanomnom** [comment]
I didn't suggest that but ok

**Comment by CreationPro** [comment]
To phrase it better, I am going to add forced scream sounds in a seperate PR and then build the chasm fall sound on top of that.

**Pull request closed without merging**
