### PR TITLE
Gulag usability changes

### PR DESCRIPTION
**Pull request by ghost**
- Adds a Worker Quarters area, where prisoners can sleep, eat, and be free from Prison Ofitser's tyranny
- Safety pickaxes and shovels have been replaced with cushioned pickaxes, which have the same stats but are a subtype
- Mining scanners can now be found in the equipment room
- There is now a tiny connection between the main asteroid and the gulag asteroid outside of having to dig around the curve

Screenshots:

You may ask why there are no firelocks despite there being a fire alarm. Nanotrasen is legally required to remind you that Prisoner Protection Act 39-C does not cover heat damages and thus we are not required to include firelocks in our construction.

You may also wonder why there are windows that show nothing but rock. This is a psychological hint that is supposed to represent all the freedom that prisoners are allowed to experience while spending their time at the Nanotrasen Humane Station Contribution Workers' Camp.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Wow. 10/10 op. So descriptive

**Comment by Anonus** [comment]
The best usability change would be REMOVE GULAG

**Comment by Jordie0608** [comment]
You should probably update all the other z5s with this.

**Comment by Zilenan91** [comment]
So cushioned pickaxes are exactly the same as regular pickaxes gameplay wise, with the only difference being in the code?

**Comment by Bawhoppen** [comment]
I don't like this, I don't think it fits that well imo

**Comment by Xhuis** [comment]
@Zilenan91 Yes, just like the safety pickaxes they have now.

**Comment by WJohn** [comment]
Xhuis that piping is atrociously bad, what the hell? We have four way manifolds now, and even then you don't need to have pipes branching out from that early in there.

**Comment by Xhuis** [comment]
It's intended to be atrocious, actually. Everything about the gulag is supposed to reflect "lowest bidder", hence the spattering of rusty walls I threw in.

**Comment by pudl** [comment]
I don't believe that it's intended to be atrocious and you're just defending yourself from criticism, but either way I don't think a single crowbar will ever make it to gulag, ever, and thus having shit piping is pointless. Just fix it.

Also, I suggest you replace the Russian vending machine with a sustenance one. The labor camp is shit, but it's not an outdated piece of shit. NT isn't a Russian company anyway, the derelict was an experiment by Russia. So it's literally impossible for NT to even have one.

And last, put plating under the windows. Just dirt makes no sense, and it isn't valuable to the aesthetics. There's a difference between intentional, well performed ugliness, and just shit that's ugly and cobbled together.

**Comment by Xhuis** [comment]
There doesn't seem to be a whole lot of support for this, and the only criticism besides @pudl's is just "gulag is shit in general", so I'm gonna close this.

**Comment by Zilenan91** [comment]
I wouldn't mind if you reopened this, it would make the gulag way more fun as not only an inmate, but as an antag since if you could get to the gulag you could make a little base in the dorms area since it won't depressurize as easily. Would be great and also hilarious if cultists used this.

**Comment by Xhuis** [comment]
ok

**Comment by Zilenan91** [comment]
Jeez that was fast

**Comment by Zilenan91** [comment]
Can you also add some cable coils and bandanas stashed around in random places so that the gulag inmates can start riots and form gangs against the sec officers

**Comment by Xhuis** [comment]
tfw conflicts and too lazy to fix

**Pull request closed without merging**
