### PR TITLE
Revert "Ports /vg/'s datum component system"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#29178

PR didn't explain what the fuck this is.

So I hate it.

@Cyberboss 

also, @tgstation/commit-access CAN YOU PLEASE STOP MERGING PRS WITH NO DESCRIPTION

Here is the pr where I rewrote the mc: https://github.com/tgstation/tgstation/pull/9231

Notice how I was able to detail how this was implemented?

Here is the pr where I rewrote the mc again: https://github.com/tgstation/tgstation/pull/17987

Notice how I was able to detail how this was implemented?

Here is the pr where I rewrote how timers worked: https://github.com/tgstation/tgstation/pull/22933

Notice how I was able to detail how this was implemented?

This is a recurring issue with @Cyberboss's PRs. He doesn't detail shit.

### CODE REVIEW

**Comment by optimumtact** [comment]
it's an entity component system

**Comment by MrStonedOne** [comment]
What the fuck is a entity component system

**Comment by optimumtact** [comment]
http://lmgtfy.com/?q=what+is+an+entity+component+system%3F

**Comment by MrStonedOne** [comment]
How does that relate to byond, ss13, datums and atoms, etc?

How was it implemented in tg?

I understand the concept, but not how it relates to us.

**Comment by optimumtact** [comment]
http://ss13.moe/wiki/index.php/User:N3X15/Components

**Comment by MrStonedOne** [comment]
Why was none of this included in the pr description?

**Comment by optimumtact** [comment]
the file is 105 lines long

**Comment by MrStonedOne** [comment]
Not all of it has to be in the pr description.

**Comment by DoctoreMad** [comment]
Sorry MSO, here's a description of it.
https://pastebin.com/sGXkGdf1

**Comment by optimumtact** [comment]
calling cyberboss a better coder than the person who literally wrote our current game loop seems like a stretch

**Comment by MrStonedOne** [comment]
Here is the pr where I rewrote the mc: https://github.com/tgstation/tgstation/pull/9231

Notice how I was able to detail how this was implemented?

Here is the pr where I rewrote the mc again: https://github.com/tgstation/tgstation/pull/17987

Notice how I was able to detail how this was implemented?

Here is the pr where I rewrote how timers worked: https://github.com/tgstation/tgstation/pull/22933

Notice how I was able to detail how this was implemented?

This is a recurring issue with @Cyberboss's PRs. He doesn't detail shit.

**Comment by DoctoreMad** [comment]
I thought cyberboss only ported it.

**Comment by MrStonedOne** [comment]
It's his PR, it's his responsibility to detail how it works, and what it is.

**Comment by DoctoreMad** [comment]
I'm replying to Optimumtract. No comment on your security regulations here.

**Comment by MrStonedOne** [comment]
oh, duh

**Comment by Jalleo** [comment]
It does need documentation to help people understand it.

**Comment by MrStonedOne** [comment]
No @Jalleo 

Maintainers need to stop merging PRs without a implementation specific description.

**Comment by outbools** [comment]
@N3X15 provided only brief description for his system but you always can fucking contact Cyberboss in pm or mention him in merged PR topic to ask description. Why the fuck you would ever revert PR because you dont understand it and can't fucking ASK ABOUT IT FIRST?. Did you fucking forget how to speak with your own team?

**Comment by DoctoreMad** [comment]
>N3X15 provided only brief description for his system

http://ss13.moe/wiki/index.php/User:N3X15/Components

**Comment by outbools** [comment]
This is how brief description looks like

Now take this fucking guide and make some components out of it without looking into vgcode

**Comment by Fox-McCloud** [comment]
As @MrPerson pointed out; I seriously doubt anyone is really going to bother to use this system, anyway. It's interesting, conceptually, but it does make working with some things a lot more difficult.

**Comment by outbools** [comment]
Oh there is only 3 component PRs and they were made in 3 VARIOUS WAYS. Amazing guide!

**Comment by outbools** [comment]
@Fox-McCloud elaborate on this. How does it happen to make something difficult with modern game programming pattern used by modern popular game engines? I agree there is a lot of boilerplate code but thats can be solved by good guide and reference.

>you can switch components on runtime
>AI code but 3x shorter
>Life() code not painful

This is what it brings to codebase. Cons?

**Comment by Fox-McCloud** [comment]
The downside is that if it's not well documented or well supported, you can end up having a monolithic amount of systems built around it that are difficult to modify (or no one wants to), and if the few people who do understand it leave, then you're left with a problem.

TGUI is a prime example of this; it's hugely overcomplicated and a performance hog; I routinely hear complaints about it, but it's a "damned if you do, damned if you don't scenario"; it's a massive amount of work to rip it out/overhaul it, but not a whole lot fully understand the backend either....andddd the sole person who worked on the backend is longgg gone.

If a system is poorly documented (the last time the documentation for this was updated was in February...and even VG doesn't really utilize this system much..), but forced onto everyone else by 1-2 people, then everyoen ends up worse off if those 1-2 people leave or become inactive.

**Comment by outbools** [comment]
@Fox-McCloud yeah that's the actual problem.

**Comment by outbools** [comment]
@Cyberboss you need to clarify how to use it and why it's different from /vg/ impementation and wiki reference

**Comment by outbools** [comment]
https://github.com/tgstation/tgstation/blob/bcb85acb1e6a7e064cf14841dfb63cf96eef2bf7/code/datums/components/component.dm
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/components/component.dm

Why there is no datum/component_containers?

**Comment by Jalleo** [comment]
@MrStonedOne That too.

**Comment by Tacolizard** [comment]
@DoctoreMad stop shitposting, you don't even code. Yes, that is a brief description.

**Comment by optimumtact** [comment]
That is rich

**Comment by optimumtact** [comment]
Loosely adapted from /vg/. This is an entity component system for adding behaviours to datums when inheritance doesn't quite cut it. By using signals and events instead of direct inheritance, you can inject behaviours without hacky overloads. It requires a different method of thinking, but is not hard to use correctly. If a behaviour can have application across more than one thing. Make it generic, make it a component. Atom/mob/obj event? Give it a signal, and forward it's arguments with a `SendSignal()` call. Now every component that want's to can also know about this happening and can react to the behaviour

## API

### Vars

1. `/datum/var/list/datum_components` (private)
    * Lazy list of all components a datum has   (TODO: Make this a typecache with longer paths overwriting shorter ones maybe? It'd be weird)
1. `/datum/component/var/enabled` (protected, boolean)
    * If the component is enabled. If not, it will not react to signals
    * TRUE by default
1. `/datum/component/var/dupe_mode` (protected, enum)
    * How multiple components of the exact same type are handled when added to the datum.
        * `COMPONENT_DUPE_HIGHLANDER` (default): Old component will be deleted, new component will first have `/datum/component/proc/InheritComponent(datum/component/old, FALSE)` on it
        * `COMPONENT_DUPE_ALLOWED`: The components will be treated as seperate, `GetComponent()` will return the first added
        * `COMPONENT_DUPE_UNIQUE`: New component will be deleted, old component will first have `/datum/component/proc/InheritComponent(datum/component/new, TRUE)` on it
1. `/datum/component/var/list/signal_procs` (private)
    * Associated lazy list of signals -> callbacks that will be run when the parent datum recieves that signal
1. `/datum/component/var/datum/parent` (protected, read-only)
    * The datum this component belongs to

### Procs

1. `/datum/proc/GetComponent(component_type(type)) -> datum/component?` (public, final)
    * Returns a reference to a component of component_type if it exists in the datum, null otherwise
1. `/datum/proc/GetComponents(component_type(type)) -> list` (public, final)
    * Returns a list of references to all components of component_type that exist in the datum
1. `/datum/proc/GetExactComponent(component_type(type)) -> datum/component?` (public, final)
    * Returns a reference to a component whose type MATCHES component_type if that component exists in the datum, null otherwise
1. `GET_COMPONENT(varname, component_type)` OR `GET_COMPONENT_FROM(varname, component_type, src)`
    * Shorthand for `var/component_type/varname = src.GetComponent(component_type)`
1. `/datum/proc/AddComponent(component_type(type), ...) -> datum/component`  (public, final)
    * Creates an instance of `component_type` in the datum and passes `...` to it's `New()` call
    * Sends the `COMSIG_COMPONENT_ADDED` signal to the datum
    * All components a datum owns are deleted with the datum
    * Returns the component that was created. Or the old component in a dupe situation where `COMPONENT_DUPE_UNIQUE` was set
1. `/datum/proc/RemoveComponent(datum/component/C)` (public, final)
    * Sends the `COMSIG_COMPONENT_REMOVING` signal to the datum
    * Deletes the passed component
    * Component deleting must use this
1. `/datum/proc/ComponentActivated(datum/component/C)` (abstract)
    * Called on a component's `parent` after a signal recieved causes it to activate. `src` is the parameter
    * Will only be called if a component's callback returns `TRUE`
1. `/datum/proc/TakeComponent(datum/component/C)` (public, final)
    * Properly transfers ownership of a component from one datum to another
    * Singals `COMSIG_COMPONENT_REMOVING` on the parent
    * Called on the datum you want to own the component with another datum's component
1. `/datum/proc/SendSignal(signal, ...)` (public, final)
    * Call to send a signal to the components of the target datum
    * Extra arguments are to be specified in the signal definition
1. `/datum/component/New(datum/parent, ...)` (protected, virtual)
    * Forwarded the arguments from `AddComponent()`
1. `/datum/component/Destroy()` (private)
    * Use `RemoveComponent()` instead of `qdel()` to properly delete a component
    * `qdel()` still works but it suppresses the `COMSIG_COMPONENT_REMOVING` signal and is not intended behavior
1. `/datum/component/proc/InheritComponent(datum/component/C, i_am_original(boolean))` (abstract)
    * Called on a component when a component of the same type was added to the same parent
    * See `/datum/component/var/dupe_mode`
1. `/datum/component/proc/OnTransfer(datum/new_parent)` (abstract)
    * Called before the new `parent` is assigned in `TakeComponent()`, after the remove signal, before the added signal
    * Allows the component to react to ownership transfers
1. `/datum/component/proc/_RemoveNoSignal()` (private, final)
    * Internal, clears the parent var and removes the component from the parents component list
1. `/datum/component/proc/RegisterSignal(signal(string), proc_ref(type), override(boolean))` (protected, final) (Consider removing for performance gainz)
    * Makes a component listen for the specified `signal` on it's `parent` datum.
    * When that signal is recieved `proc_ref` will be called on the component, along with associated arguments
    * Example proc ref: `.proc/OnEvent`
    * If a previous registration is overwritten by the call, a runtime occurs. Setting `override` to TRUE prevents this
    * These callbacks run asyncronously
    * Returning `TRUE` from these callbacks will trigger a `TRUE` return from the `SendSignal()` that initiated it
1. `/datum/component/proc/ReceiveSignal(signal, ...)` (virtual)
    * Called when a component recieves any signal and is enabled
    * Default implementation looks if the signal is registered and runs the appropriate proc

@Fox-McCloud your strawman about tgui doesn't apply, and in fact appears wildly misinformed, tgui's backend subsystem is easily understandable, as is the api for deliver data to the frontend templating system. The buggy unuseable and slow part is the front end templating language ractive.js which is not an optimal solution for tg's needs. Irrespective of that the entire ECS component system is 103 lines long and is trivial to understand.

Those of you who think this is complex or confusing need to reexamine.

**Comment by outbools** [comment]
yo got bamboozled kids

**Comment by MrStonedOne** [comment]
So I don't know if anybody's noticed, but github didn't even revert this right

**Comment by PJB3005** [comment]
@Fox-McCloud if I didn't move to SS14 and stuff I'd have refactored all machinery code to use it by now on /vg/. 

Also it can't ever get worse than current SS13 code.

**Pull request closed without merging**
