### PR TITLE
Adds 2 performers outfits.

### PR DESCRIPTION
**Pull request by Shadowlight213**
meme
meme2
Courtesy of Kor's Gf.

:cl:
imageadd: 2 new performer's outfits have been added to the autodrobe
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
:confused:

**Comment by jughu** [comment]
F u c k i n g w e e b s

**Comment by lzimann** [comment]
bad

**Comment by Militaires** [comment]
bad

**Comment by GunHog** [comment]
Look at the bright side of this: Any clown players that try to RP in them will have a significantly increased chance of being beaten! Clowns make pained honks when hit, and play a sad trombone noise when they die! Are you saying you do not want more opportunities to torture clowns???

**Comment by ExcessiveUseOfCobblestone** [comment]
are these Hatsune Miku and Merguine Luka outfits by chance?

**Comment by RemieRichards** [comment]
@ExcessiveUseOfCobblestone Megurine, not Merguine, but yes

**Comment by ExcessiveUseOfCobblestone** [comment]
sorry I need to brush up on my vocaloid lore

**Comment by RemieRichards** [comment]
you do, you do.

**Comment by ExcessiveUseOfCobblestone** [comment]
[Next PR I will replace the sad trombone with this](https://www.youtube.com/watch?v=dF6OdELPaak)

**Comment by KorPhaeron** [comment]
bloat

**Comment by Cheridan** [comment]
where's goof when you need him

**Comment by jughu** [comment]
T-triple b-baka!

**Comment by bgobandit** [comment]
NO REFERENCES

**Comment by KorPhaeron** [comment]
References are fine, straight up adding stuff from unrelated mediums with no subtlety is weird

**Comment by RemieRichards** [comment]
@KorPhaeron Oh sure, mr "toki wo tomare", or is it mr "za warudo"?

**Comment by dannno** [comment]
fuckkong OWNED kor

**Comment by Iamgoofball** [comment]
# ITS TIME TO STOP

Sorry @cheridan I was sleeping in

**Comment by Iamgoofball** [comment]
@RemieRichards those are at least relevant and funny

**Comment by jughu** [comment]
download

**Comment by RemieRichards** [comment]
@Iamgoofball purely subjective.

**Comment by KorPhaeron** [comment]
@RemieRichards 

Obviously I'm a hypocrite, but wizards using magic isn't the same as the clown dressed as miku because miku

**Comment by RemieRichards** [comment]
@KorPhaeron it's fine to add these things, it's not fine to be hypocritical about it.

There's the fact these are just costumes, they're not a mechanical intrusion to the game, like all (?) the jojo refs (Timestop, Stands)

**Comment by KorPhaeron** [comment]
I think it's the other way around. At least mechanical things (hopefully) have a benefit in the form of fun gameplay. This is just miku's outfit because ???

And being a hypocrite is fine when our reference policy is "do maintainers like the thing it's referencing/think it will be good to have" since it's all entirely subjective

**Comment by RemieRichards** [comment]
No, I don't think that if you're doing X you can shit on people for also doing X.

And no, Mechanical intrusions can't be avoided as easily, so the reference becomes a deeper part of the game, which makes it more obvious, costumes are just that, costumes: optional clothing.

**Comment by Iamgoofball** [comment]
Okay so I can just add all the animes and it'll be fine now I guess because you're all weebs

**Comment by RemieRichards** [comment]
Well I mean you're just as bad goof, you made a shuttle out of "the room", how the hell is that relevant? Miku's atleast a synthesised voice + a hologram, two things we know exist in SS13 (the AI, pAIs, Holoparas, etc.)

**Comment by KorPhaeron** [comment]
I don't think I'm "shitting on" anybody, I cut these sprites up and put them into dmis for him, I'm just saying I think it's silly

And I still think it's fine to say "I like reference A but not B" otherwise we'd be obligated to have ponies because we made the mistake of adding 2001 void suits to our space game.

**Comment by KorPhaeron** [comment]
goof however adds gay porn memes while yelling about degeneracy so yeah he's nuts ignore him

**Comment by RemieRichards** [comment]
@KorPhaeron Nowhere did I say you had to like this, but there's a difference between "I don't like this because X, Y and Z" and "this is bloat,  I'm just here to shit on the idea without explaining"

**Comment by lzimann** [comment]
the real question is: why is nanotrasen not firing people for not wearing the company's uniform during work time?

**Comment by Shadowlight213** [comment]
I asked about the outfits originally because I thought they would be funny.
I made the pr, because they turned out really well made and are adorable.

Also kor being a hypocrite is doubled because he asked me if I was going to pr it when he showed it to me, so he's probably just trying to cover his ass :^).
As for reference policy, I'd like to point out we have the cueball outfit from homestuck because ???.
Plus, the vocaloid concept fits well into a sci-fi space station setting. In the future, singing would likely be primarily done by AIs, which vocaloids pretty much are.

**Comment by Iamgoofball** [comment]
This is still retarded

**Comment by optimumtact** [comment]
We dont' have a reference policy you fucking numpties, it's a PLAYER REFERENCE POLICY AND THE LAST TIME I CHECKED WE DIDN'T HAVE ANY VOCALOIDS AS PLAYERS

**Comment by KorPhaeron** [comment]
I'm miku

**Comment by ExcessiveUseOfCobblestone** [comment]
miku frost 


miku = vocaloid with blue hair
frost = a thing typically represented by the color blue

the jig is up desu!

**Comment by Cheridan** [comment]
>As for reference policy, I'd like to point out we have the cueball outfit from homestuck because ???.
No way, I removed those ages ago. Did the suit get readded? Because who cares, that's just a white suit

**Comment by ChangelingRain** [comment]
The helmet got readded at some point

**Comment by ExcessiveUseOfCobblestone** [comment]
so you were the culprit, and here I thought pap was to blame. 

Shame on you!

**Comment by KorPhaeron** [comment]
@Cheridan 

https://github.com/tgstation/tgstation/pull/21488

**Comment by Cheridan** [comment]
wow, that stupid cueball is awful

homestuck is a gross old stale meme at this point anyway, remove again.

**Comment by Arianya** [comment]
I'm not sure how much older a meme you can get then Jojo :^)

**Comment by Iamgoofball** [comment]
@cheridan I told them you were the remover but they didn't listen

**Comment by jughu** [comment]
The megurine one is a good suit in general even for a meme or reference on the other hand hatsune miku clothing us schoolgirl cancer tier

**Comment by KorPhaeron** [comment]
goofwasright

**Comment by Arianya** [comment]
To be fair old borg sprite is awful.

**Comment by jughu** [comment]
I liked it tbh but its just nostelgia

**Comment by KorPhaeron** [comment]
I don't think liking a consistent art style requires nostalgia. I'm sure the visual quality of the models in TF2 have improved over the years, but that doesn't make bright pink camera beards any better for theme

**Comment by jughu** [comment]
Cant we add old cyborg skins for nostelgia

**Comment by Militaires** [comment]
@korphaeron

everything i will not discuss under any circumstances.

@jughu

they exist service borgs use them.

**Comment by jughu** [comment]
i mean ALL old cyborg skins doofus

**Comment by dannno** [comment]
as much as I like costumes kor is right when it comes to consistency

**Comment by Iamgoofball** [comment]
@dannno this is what they said for everything

**Comment by KorPhaeron** [comment]
Also a last thing in my defense: Holoparasites were pretty obviously stands, but there was still an attempt to give them their own look and lore that fit in with the universe, I didn't just slap Star Platinums sprite in the game

**Comment by PKPenguin321** [comment]
The slope slippens

**Comment by Militaires** [comment]
@KorPhaeron the truth, you can never know the truth.

is there even a point in trying to reason

**Pull request merged**
