### PR TITLE
Xeno acid blood refactor + acid blood melts you

### PR DESCRIPTION
**Pull request by RemieRichards**
- Xeno blood and Xeno gibs are now subtypes of blood and gibs.
- Xeno acid blood will now call acid_act() on the atoms that cross it
- When a Human crosses Xeno acid blood it will attempt to destroy their shoes (and only their shoes)
  and deal 10 Burn damage if they are shoeless
- Adds unacidable to some shoes deemed sturdy enough to survive acid.

### CODE REVIEW

**Comment by tkdrg** [comment]
@RemieRichards are you still working on this?

**Comment by tkdrg** [comment]
@RemieRichards are you still working on this?

**Comment by RemieRichards** [comment]
this r kill.

Sorry, been busy with other things.

**Comment by tkdrg** [comment]
RIP

**Comment by GunHog** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO :(

**Pull request closed without merging**
