### PR TITLE
Fixes pandemic bluescreen

### LINKED ISSUE #65028: PANDEMIC Machine throwing bluescreen when one virus cured/one virus uncured blood is inserted.
Reporting client version: 514.1578

## Round ID:
[178695](https://scrubby.melonmesa.com/round/178695)

## Testmerges:
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)

## Reproduction:
I made a virus, someone came in with the virus I made and also the common cold. I cured the common cold, but my virus was still alive and well. 
The PANDEMIC machine bluescreened when the patient's blood was inserted (with one cured virus and one active virus).
See the error log posted below.

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Unable to get property 'symptoms' of undefined or null reference
   at s (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:1109138)
   at Ie (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179474)
   at Anonymous function (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179720)
   at Te (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179584)
   at Anonymous function (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179720)
   at De (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:180768)
   at Te (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:180607)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"stiix","interface":"Pandemic","window":{"key":"[0x200b111]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-2562

### LINKED ISSUE #65047: PANDEMIC Machine throwing bluescreen when one virus cured/one virus uncured blood is inserted.
Reporting client version: 514.1578

Round ID:
[178695](https://scrubby.melonmesa.com/round/178695)

Testmerges:
[Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
Reproduction:
Silkie made virus, someone comes in with the virus Silkie made and also common cold. Silkie cures common cold, but Silkie's virus is still alive and well. The PANDEMIC machine, when the blood of someone with one cured virus and one active virus is inserted, shows a bluescreen error, which is posted below.

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation.
TypeError: Unable to get property 'symptoms' of undefined or null reference
at s (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:1109138)
at Ie (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179474)
at Anonymous function (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179742)
at Le (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179720)
at Te (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:180573)
at Le (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179584)
at Anonymous function (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179742)
at Le (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179720)
at De (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:180768)
at Te (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:180607)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"stiix","interface":"Pandemic","window":{"key":"[0x200b111]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-2562

@tgstation/commit-access 
@tgstation/issue-managers 
https://github.com/tgstation/tgstation/issues/65028#issuecomment-1046298555

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
[GBP No Update please]
Adds more checks onto the Pandemic & removes the use of usesharedstate (literally just saved the tab)

In jlsnow301's great and infinite wisdom he did not predict a situation where a viro would actually cure a second virus then look back into the machine (the sharedstate would be null)

## Why It's Good For The Game
Bug fixes
Fixes #65028
Fixes #65047

## Changelog

:cl:
fix: Fixes a blue screen in the Pandemic from loading multiple viruses.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
@jlsnow301 if you add 
```
Fixes #65028
Fixes #65047
```

To the PR body it will autoclose the linked issues when the PR is merged.

**Comment by LemonInTheDark** [comment]
Do you have any ideas on how the pandemic machine might have ended up with a null in that list? Rather then silencing the error it seems more useful to cut it out at the root

**Comment by Mothblocks** [comment]
image

I'm so tempted

**Comment by jlsnow301** [comment]
> To the PR body it will autoclose the linked issues when the PR is merged.

I'm really not certain that it addresses it, I can't get a blue screen even with the steps

I suppose they can just reopen...

**Comment by jlsnow301** [comment]
> Do you have any ideas on how the pandemic machine might have ended up with a null in that list? Rather then silencing the error it seems more useful to cut it out at the root

I'm actually thinking it may be related to shared states. A user would have tabbed to another virus then swapped to a specimen containing one virus (the initial value would then be null)

**Review by stylemistake — APPROVED** [review]

**Pull request merged**
