### PR TITLE
private security officers get a nanotrasen hud icon

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
title
also removes prisoner from the get all job icons thing because i told rave to do that but he never did and that was very mean of him

## Why It's Good For The Game

yo ding ding man, ding dong, ding dong yo

## Changelog
:cl:
tweak: nanotrasen private officers now have nanotrasen hud icons
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
isnt private security force like, not NT

**Comment by trollbreeder** [comment]
fun fact the private security officers at centcom are cardboard cutouts

**Comment by itseasytosee** [comment]
You can even pick them up! Simple mob when?

**Comment by Fikou** [comment]
> isnt private security force like, not NT

they are nanotrasen private security force

**Pull request merged**
