### PR TITLE
Cleans up shitty paintjob on airlocks.

### PR DESCRIPTION
**Pull request by WJohn**
At the request of xxalpha, this gets rid of the ugly little runny drop of paint on every airlock: LEARN TO USE GITHUB FLAVOURED MARKDOWN

### CODE REVIEW

**Comment by Anonus** [comment]
If you're touching engineering, security, and command airlocks can you move the letter on each down a single pixel so they align with the stripes properly?

**Comment by WJohn** [comment]
Yeah sure, I'll do that in a second.

**Comment by Cheridan** [comment]
But I like the drip

**Comment by xxalpha** [comment]
That's not a drip, that's an imperfection of the sprites.

**Comment by Miauw62** [comment]
a paint drip would look cool on some airlocks imo.
this is still a good change though :+1:

**Comment by WJohn** [comment]
I fixed up the lights for hatch doors like on the AI sat, they weren't supposed to be that bright. Furthermore I reduced its intensity so it doesn't cover the ENTIRE door, just most of it.

**Comment by CosmicScientist** [comment]
I thought that drip was on maintenance doors for a nice dirty look. I never saw them on the other doors.

**Comment by WJohn** [comment]
@CosmicScientist Yes, I got rid of that little imperfection too.

This is all at xxalpha's request, and he might be the only guy who dislikes the drip. I personally have no preference.

**Comment by xxalpha** [comment]
Dislike is not a strong enough word.

**Comment by CosmicScientist** [comment]
@WJohn Could you do what xxalpha just said? Leaving it on maint doors only? I'll offer a +1 if it's done like that.

**Comment by WJohn** [comment]
Done.

**Comment by CosmicScientist** [comment]
:+1:

**Pull request merged**
