### PR TITLE
[RED LABEL][TESTED][SINGLE][READY][2][MINGLE] Adds an Supplypod Launch Bay specifically for ERTs or Deathsquads

### PR DESCRIPTION
**Pull request by MrDoomBringer**
## About The Pull Request
Adds an option for admins to clear Supplypod bays. Also, adds another centcom supplypod loading bay specifically made for ERTs/Deathsquads/etc.

## Why It's Good For The Game
Adds some useful tools to the centcom supplypod launcher to make admining easier. Now if you spawn in ERTs, etc. they dont have to trek across centcom to make it to the launch bays.

## Changelog
:cl:MrDoomBringer
admin: Added a Drop Pod bay conveniently close to the CentCom ferry, useful for ERTs or Deathsquads who want to arrive in style!
admin: The CentCom-Supplypod-Launcher now has an option to clear a bay of any mobs and objects.

/:cl:

image

### CODE REVIEW

**Comment by Fikou** [comment]
ugly :(

**Comment by MrDoomBringer** [comment]
@Fikou u right, ill try to fix it later tonight

**Comment by MrDoomBringer** [comment]
@Fikou updated the OP with a _slightly_ less shit version

**Comment by Fikou** [comment]
yeah that looks nice

**Comment by qbmax32** [comment]
TACTICAL COMBAT DROP

**Comment by Jordie0608** [comment]
bfabc6cd9ecef5c8369a3443dced4a85

**Comment by MrDoomBringer** [comment]
@Jordie0608 get that RED LABEL off my PRISTINE PR

**Comment by MrDoomBringer** [comment]
@Jordie0608 
image

**Comment by Jordie0608** [comment]
Ok sure thing bud.

**Comment by MrDoomBringer** [comment]
@Jordie0608 
image

**Comment by lordsaladin** [comment]
@MrDoomBringer why not allow ert/death-squad to titanfall onto the station,wait why is there no janitor mech?

**Comment by MrDoomBringer** [comment]
@lordsaladin i mean anyone can use the drop pod room, even if you're in a mech, so you already can sorta

**Comment by Jordie0608** [comment]
I forgot to actually merge this.

**Pull request merged**
