### PR TITLE
Cytology techweb tweaks and microscope crafting recipe

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

The swabs and petri dishes were available in the Basic Tools, but you couldn't do much with them without vat grower. And the vat grower was available only in Sci Plumbing RCD that is deeper in the tech tree compared to the Chemical Plumbing RCD that has more recipes. Now swabs, petri dishes, and both Plumbing RCDs are listed in the Basic Medical Equipment node. And the main RCD now also has the vat grower recipe to avoid confusion when people can't find it because they got wrong RCD.

And the microscope is an QOL tool that is not required for cytology when you have wiki. So it should be available without relying on cargo shuttle or xenobio access. 

Also moved operating computer circuit board to Basic Medical Equipment node because it previously required a human dissection experiment that can't be completed without an operating computer. This seems like an overlook to me.

## Why It's Good For The Game

Cytology and xenobio are independent, so people should be able to work on it without xenobio access, which is the only place where the microscopes spawn. With this PR, cytology should be more available to public. You can dig into it as a Chemist with reagents/plumbing knowledge, which is a more fitting job for it rather than a Scientist.

## Changelog

- Cytology tools are no longer scattered around the tech web nodes.
- Fixed the operating computer requirement to unlock itself. Issue #63326
- Added microscope crafting recipe.

:cl:
add: Added microscope crafting recipe
balance: Techweb: Moved cytology tools to a single node from different nodes
balance: Techweb: Operating computer now available before the experiment that requires it
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Now it's feeling like the baseline of a job!

**Comment by MTandi** [comment]
> Now it's feeling like the baseline of a job!

Cell hunting is still non-intuitive, as you can't get mold bacteria from moldy things for instance. We need more things with bacteria. Looking into it.

**Comment by datorangebottle** [comment]
finally, the botanist can grow horrible monstrosities in their back room.

**Comment by Mothblocks** [comment]
> Also moved operating computer circuit board to Basic Medical Equipment node because it previously required a human dissection experiment that can't be completed without an operating computer. This seems like an overlook to me.

This is actually a pretty sizable balance change and not necessarily an oversight, so I'm removing the fix label (and merging anyway, because I guess I agree with it) but other than that I don't really know anything about cytology so meh

**Comment by timothymtorres** [comment]
@MTandi please make sure you [tag issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) that are fixed in the PR properly so they autoclose.  Thank you!

**Pull request merged**
