### PR TITLE
Gives shades directional sprites

### PR DESCRIPTION
**Pull request by anconfuzedrock**
damn it image

### CODE REVIEW

**Comment by jughu** [comment]
I STILL REQUIRE PICS

**Comment by anconfuzedrock** [comment]
image

**Comment by ShadowDeath6** [comment]
Sorry I'm so robust I've never ever died, what does a ghost look like?

**Comment by Supermichael777** [comment]
like Casper but not bald

**Comment by SgtxRootbeer** [comment]
Yes bald, if character is bald or is lizard.

**Comment by Repukan** [comment]
This is a slight buff to shades.

Side sprite is smaller and harder to hit

**Comment by anconfuzedrock** [comment]
image

**Pull request merged**
