### PR TITLE
Changes graffiti letters 

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
imageadd: graffiti letters and numbers have received a makeover
/:cl:
The current sprites were a relic of the past and very clumsy to use for writing anything longer than a couple letters long, I made them much smaller and more chunky so you can vandalize in more creative ways

graffititest

### CODE REVIEW

**Comment by praisenarsie** [comment]
these look like they were inspired by goon's

**Comment by Mickyan** [comment]
I've never played on goon

**Review by vuonojenmustaturska — APPROVED** [review]
looks good to me

**Comment by Dorsisdwarf** [comment]
these look great, but not like something that's being drawn with a crayon.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
