### PR TITLE
Renames files under code/ with naughty characters

### PR DESCRIPTION
**Pull request by coiax**
Like seriously, don't use spaces in file names, this is a codebase,
they're annoying. Hopefully Github will show these renames correctly.

### CODE REVIEW

**Comment by pudl** [comment]
autism

**Comment by AnturK** [comment]
It's fine, makes it easier on linux. I'd name food&drinks food_and_drinks though, makes it more readable in my opinion.

**Comment by optimumtact** [comment]
Oh my god I love you

**Comment by PKPenguin321** [comment]
Death to spaces

**Pull request merged**
