### PR TITLE
Plasmamen fixes

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
ERT/Deathsquad/Centcomm Official all set themselves to human on spawn. This prevents silliness with plasamen burning up (and letting filthy lizards have jobs that outrank the whole station despite being barred from captain)

Shadowling godmode moved to before the sleep() in the chrysalis sequence, to stop them burning to death during the transformation

### CODE REVIEW

**Comment by Stickymayhem** [comment]
PLASAMEN

**Comment by ParadoxSpace** [comment]
PLAZAMEME

**Comment by Incoming5643** [comment]
we already rejected removing liz ops once :-1:

**Comment by Stickymayhem** [comment]
SOME SPELLING CHECKS HAVEN'T COMPLETED YET

**Comment by PKPenguin321** [comment]
:+1: shouldn't have been rejected last time

**Comment by KorPhaeron** [comment]
@Incoming5643 

This doesn't include removing lizops

**Comment by lzimann** [comment]
still need a fix to nuke ops, or are you doing in another PR?

**Comment by Cheridan** [comment]
>letting filthy lizards have jobs that outrank the whole station despite being barred from captain

imo this should be dependent upon the config

**Comment by KorPhaeron** [comment]
@Cheridan 

Okay it uses config now

**Pull request merged**
