### PR TITLE
RD-restricted traitor item: Good old unnerfed reactive teleportation armor

### PR DESCRIPTION
**Pull request by silicons**
Why the fuck not.

### CODE REVIEW

**Comment by Armhulen** [comment]
> : |

**Comment by SweaterKittens** [comment]
It was overpowered before, and gating it behind TC doesn't really make it any less broken my man.

**Comment by kevinz000** [comment]
🤡

**Comment by PKPenguin321** [comment]
stupidly strong to the point that it is not fun to play against and doesnt fit traitor theme no thanks

**Comment by Armhulen** [comment]
"fuck you goof!!!"

"lol lets just add this because it's funny miright guys"

**Comment by Cheridan** [comment]
https://github.com/tgstation/tgstation/pull/23719#issuecomment-277546603

**Pull request closed without merging**
