### PR TITLE
Partially adds resonance cascade, WIP

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

A diversion of #48935, not fully ready yet, opening here so I have a place to talk to OFQ and get feedback.
Not really balanced until after said pr is merged/reworked, but I can't hold up the fixes in #48935  anymore

Currently, if the SM explodes while it has too much energy, it turns into a tesla ball. If it explodes while it has too many moles of coolant, it turns into a singularity. If it has both, it just does singuloth.

This PR makes it so that you instead get a 'resonance cascade' in that scenario, a reference to Half-Life 3-2. This spawns a variety of mobs across the station including, but not limited to, newly-added headcrabs (similar to a facehugger which is also a hostile mob), lavaland fauna, asteroid fauna, various other hostile creatures, and non-sentient xenomorph larva.

(Shamelessly stole the description off Buggy)

## Why It's Good For The Game

Adds resonance cascades to the super-matter. Also crabs.

## Changelog
:cl:LemonInTheDark, with thanks to OFQ for his sprites and anyone else who shot ideas my way.
add: Adds a new delam to the supermatter. Give it a shot some time.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
And it fails on compile.
One sec.

**Comment by LemonInTheDark** [comment]
@JAremko New home of crabby

**Comment by zxaber** [comment]
A resonance cascade! You're supposed to be scientists. Use some common sense.

**Comment by JAremko** [comment]
[animal.zip](https://github.com/tgstation/tgstation/files/4173870/animal.zip)

Rearranged a couple of pixels of flying sprites

**Comment by trollbreeder** [comment]
PR theme: https://www.youtube.com/watch?v=-RlkhPRY02k

**Comment by Iamgoofball** [comment]
https://www.youtube.com/watch?v=pZCN2T1XDt8

**Comment by Buggy123** [comment]
For anyone who doesn't know what this does:

Currently, if the SM explodes while it has too much energy, it turns into a tesla ball. If it explodes while it has too many moles of coolant, it turns into a singularity. If it has _both_, it just does one of those two (singularity takes precedent, i think).

This PR makes it so that you instead get a 'resonance cascade' in that scenario, a reference to Half-Life 1. This spawns a variety of mobs including, but not limited to, newly-added headcrabs (similar to a facehugger which is also a hostile mob), lavaland fauna, asteroid fauna, various other hostile creatures, and non-sentient xenomorph larva.

**Comment by Anonmare** [comment]
Freeman you fool!

**Comment by LemonInTheDark** [comment]
> 
> 
> For anyone who doesn't know what this does:
> 
> Currently, if the SM explodes while it has too much energy, it turns into a tesla ball. If it explodes while it has too many moles of coolant, it turns into a singularity. If it has _both_, it just does one of those two (singularity takes precedent, i think).
> 
> This PR makes it so that you instead get a 'resonance cascade' in that scenario, a reference to Half-Life 1. This spawns a variety of mobs across the station including, but not limited to, newly-added headcrabs (similar to a facehugger which is also a hostile mob), lavaland fauna, asteroid fauna, various other hostile creatures, and non-sentient xenomorph larva.

I'ma just..... take some notes off this for the pr description, just realized I never mentioned any mechanics.

**Comment by JAremko** [comment]
@Buggy123  yeah also (its planned) that with a small chance spawns will be replaced with https://user-images.githubusercontent.com/1898905/73110782-55384880-3f10-11ea-821b-eea44dcddcad.png

**Comment by Tharcoonvagh** [comment]
Make it open wormholes as well

**Comment by JAremko** [comment]
> Make it open wormholes as well

yeah I made something similar to R&M portals for it https://github.com/tgstation/tgstation/files/4117567/portal.zip

**Comment by Buggy123** [comment]
Something to keep in mind while balancing: a tesla or a singulo are often round enders and, with luck or preparation, can destroy the entire station utterly.

A resonance cascade is harder to make than _either_ of those. The severity should be scaled thuswise.

It definitely needs to be at least several times stronger than a normal portal storm event, because those just end up spawning mobs in a handful of locations, which smash a few things and maybe kill a person or two total before they get killed.

**Comment by JAremko** [comment]
> A resonance cascade is harder to make than either of those. The severity should be scaled thuswise.

I proposed to make it extra special by replacing SM explosion with a blob spawn in the place of SM. It can be extra special SM meter/bananium blob strain that can spawn portals around the station and spread via them (like cores). You will have to defeat it to end the portal storm and, if the damage too great - call the shuttle.  So it will have less initial destruction potential than even a usual SM explosion but will quickly spin out of control if left unchecked.  And for the crew size scaling we already have blob resource generation rate.

**Comment by Buggy123** [comment]
>I proposed to make it extra special by replacing SM explosion with a blob spawn in the place of SM.

I like the idea, it sounds interesting. I could work on it but I can't sprite worth a damn.

**Comment by JAremko** [comment]
I'll give it a try :thinking:

**Comment by CRITAWAKETS** [comment]
If the SM turns into tiberium, make it so that if you hit the big boi (tm) crystal with a BSA it just immediately ends the round and coats the station in tiberium

**Comment by ATH1909** [comment]
IMO, the spawned xeno larvae should be allowed to be sapient; this is supposed to be a round-ending event, after all.

Hell, maybe we should let ghosts possess ANY of the spawned mobs, even after they've spawned, sort of like how ghosts can possess spiders (that have been created via certain means).

**Comment by JAremko** [comment]
@LemonInTheDark  I think it also should spawn had crab zambies with randomized bodies :thinking:

**Comment by JAremko** [comment]
> If the SM turns into tiberium, make it so that if you hit the big boi (tm) crystal with a BSA it just immediately ends the round and coats the station in tiberium

But Kane lives anyway :thinking:

**Comment by Shadowflame909** [comment]
> 
> 
> IMO, the spawned xeno larvae should be allowed to be sapient; this is supposed to be a round-ending event, after all.
> 
> Hell, maybe we should let ghosts possess ANY of the spawned mobs, even after they've spawned, sort of like how ghosts can possess spiders (that have been created via certain means).

To do this, all you would have to do is trigger the "possessing ghosts" random event as soon as resonance cascade triggers.

**Comment by optimumtact** [comment]
this is a cool idea but keep it simple, what you have right now is fine.

Too much creep will slow your pr down

**Comment by Spepbuthewranglesgithub** [comment]
making the EZ infinite energy rock more interesting? absolutely lovely.

**Comment by JAremko** [comment]
REEEEEEEEE

**Comment by LemonInTheDark** [comment]
Mood
1 Sec

**Comment by LemonInTheDark** [comment]
and it conflicts. End me.

**Comment by LemonInTheDark** [comment]
Fucking shoot me

**Comment by LemonInTheDark** [comment]
Question not the evil I have done

**Comment by LemonInTheDark** [comment]
Eyyy man sorry for the shitfest, should be fixed for now.

**Comment by LemonInTheDark** [comment]
Aight just need to add zombie functionality and hitting it off your head and we should be good.

**Comment by LemonInTheDark** [comment]
Brah. I'll be back soon, I should have all the spritework I need, await further pr's.

**Comment by optimumtact** [comment]
make new pr

**Comment by LemonInTheDark** [comment]
once I figure out a bug, will do boss.

**Pull request closed without merging**
