### PR TITLE
Clown PDA slips stuns again.

### PR DESCRIPTION
**Pull request by ghost**
🆑 Clown
tweak: The Clown PDA now slips-stuns again like it did before. Reskinned PDA's do not slip you.
/:cl:

[why]: clowns, their cornerstone _was_ being able to dish out more slips than your average shitter, or atleast, thats the impression I got from it as the clown has a slipping PDA which slips you for a significant amount of time.

### CODE REVIEW

**Comment by 4dplanner** [comment]
This should make clear that it is a stun, it already slips.

**Comment by duckay** [comment]
whoops my bad

**Comment by Gousaid67** [comment]
i dont know to be honest, a stun of 120 seconds is nothing to scoff at, im remaining neutral on this

**Comment by duckay** [comment]
> i dont know to be honest, a stun of 120 seconds is nothing to scoff at, im remaining neutral on this

the 120 is not in seconds i think, i counted 11-12 seconds

**Comment by 4dplanner** [comment]
it's not 120 seconds lol

**Comment by 4dplanner** [comment]
BYOND time is in deciseconds, so it's 12

**Comment by Gousaid67** [comment]
woops sorry, one 0 too much lol.

**Comment by duckay** [comment]
im up for suggestions but id very much stick with 12 seconds.

**Comment by Gousaid67** [comment]
8 seconds wouldnt be too bad, still enough time to really fuck up someone but still not an instant ggnore.

**Comment by 4dplanner** [comment]
Why not make it 4 second stun, 12 second knockdown?

**Comment by Gousaid67** [comment]
that seems good. 4 sec stun it is.

**Comment by GuyonBroadway** [comment]
It needs to be long enough to remove someone's shoes.

This is a critical feature.

**Comment by 4dplanner** [comment]
Also consider that it's easier to get through buffs than nerfs - it's better to leave it slightly too weak until we see how it plays out than too strong.

**Comment by duckay** [comment]
> It needs to be long enough to remove someone's shoes.
> 
> This is a critical feature.

this is the criteria i want to meet without angering the tg pros

**Comment by GuyonBroadway** [comment]
Here's a simple bit of brain thinkey stuff to work out ideal time.

Time it takes to remove shoes+time it takes to open the other mobs inventory and press the button + lag accounting time.

Assuming it takes 4 seconds to remove shoes it can take a seasoned robuster about 2-3 seconds to open the menu and click shoes.

But how long it takes to swipe shoes I dunno for certain.

**Comment by wesoda25** [comment]
Make it half a second shorter than the time it takes to cuff someone.

**Comment by ExcessiveUseOfCobblestone** [comment]
how does lowering a number make it stun now

**Comment by ExcessiveUseOfCobblestone** [comment]
also use 

https://github.com/tgstation/tgstation/blob/master/code/__DEFINES/time.dm#L41-L45

**Comment by duckay** [comment]
> how does lowering a number make it stun now

what do you mean

**Comment by ExcessiveUseOfCobblestone** [comment]
oh you added the slip duration at the end i cannot read

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
time defines

**Comment by duckay** [comment]
> time defines

not sure what you mean

**Comment by Cyprex** [comment]
You can type (6SECONDS) and it will work, note that you need the brackets and no whitespace between 6 and SECONDS.

**Comment by 4dplanner** [comment]
whitespace should be fine in (6 SECONDS).

**Comment by Cyprex** [comment]
This isn't something you can simply do repeatedly as the victim can easily just pick up your PDA.As such I believe it should be a decent stun.

**Comment by optimumtact** [comment]
I have denied this before, and will again.

**Comment by GuyonBroadway** [comment]
Keep making unpopular decisions like this and yer gonna get another reddit callout thread lad.

And you'll probably whine about in in discord like you did the last one.

**Comment by optimumtact** [comment]
do not threaten the tribunal, you don't know what you meddle with

**Comment by GuyonBroadway** [comment]
When my time comes and I am judged for what I have done if all I need do is repent for my actions here today I shall give god the two fingers on both my hands and walk backwards into hell.

**Pull request closed without merging**
