### PR TITLE
Icebox Mining Adjustments and Major Fixes

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

This is an adjustment to Icebox Mining that resolves several issues stemming from the copy-paste of the Lavaland Mining Base, and the nature of icebox genturfs adjacent to doors. 
Bwraah What
This is bad. 

## Why It's Good For The Game

This does some extensive mapping work on Icebox's Mining Basement Z's in order to bring them in line with mapping standards. 
- Reworks the Basement Z of Icebox Mining. This enabled it to be hooked up to the Stations power and Atmos Networks. 
- Icebox's mining basements are now integrated with each other, and you can now move ore from Level 3, to Level 1. Towing Ore Boxes between Z-levels like this was not possible before, and essentially discouraged miners from exploring the main exploration Z on level 3. 
- When the Lavaland Mining base was added to Icebox, so were its pipes, which were on layers 3 and 4. /tgstation/ plumbing dictates that Supply and Scrubber air networks utilize layers 2 and 4 respectively. 
- Mining B-2, as pictured above barely accomplished what it needed to (basically serving as a mining access point to the B-2 exploration Z. It's been fully reworked in order to avoid genturf blocking off its ingress/egress points, and the area from being devastated by hostile mobs.
- Some alterations to Station Maint on the ground level in order to facilitate the exchange of power/plumbing. 

Provided Below are images containing the alterations.
B-1:
New Icebox Mining Basement Midlvl
B-2:
New Icebox Mining Basement

## Changelog

:cl:
fix: The Icebox Mining Basement Levels now utilize power and air provided by the main station. Some areas were changed to accomplish this.
fix: The Icebox Mining Basement Levels now utilize pipe layers 2 and 4 instead of the improper 3, and 4. 
fix: You can now use the B-2 level of Icebox mining safely and reliably, a new, quaint layout affords miners easy access to the B-2 exploration Z.
fix: Due to the extent of the alterations on for mining's B-2 level, the B-1 level has received some upgrades as well. Please look forwards to them.
/:cl:

### CODE REVIEW

**Comment by Maurukas** [comment]
I am loving all these fantastic additions to icebox we're getting. Overall: great detailing, and a much needed expansion and overhaul to an area that desperately needed it. Really, the variety of floor tiling, use of dirt, decals and edging is top notch here.

Now for all the minor issues, in no particular order:

These two areas are missing APCs:
/area/cargo/warehouse
/area/mine/production

There are no newscasters anywhere on the lower two levels. Scatter a handful around, maybe in the lounge area, or in other spots players might loiter?

I don't think these firelocks will work unless the tiles above them are floored.

image


Your bathroom extends past the floor above, and has no roof. This vents at roundstart and causes active turfs:

image

Additional active turfs here:

image

Bad corner here, this injector port is also not connected to anything. Please remove it if it's not needed:

image


The mining ladder has broken. Is your intent to use only the stairs in the cargo bay area?

image
This is the tile directly beneath it:
image

**Comment by Zytolg** [comment]
@Maurukas changes are done. There might be a lingering active turf over by the tree where you indicated them. That's centered on genturf so it's strange that it's generating something other than ICEBOX_AIR.

**Comment by newfren** [comment]
for the record, it was and is certainly possible to drag mining boxes up and down ladders, just as you'd drag anything else up or down a ladder.

**Comment by Zytolg** [comment]
If Mad Diff Bot still shows that this somehow has dusted the Icebox Chem-Z, **DO NOT MERGE**. I'll update this Comment once the renders are done.

**Pull request merged**
