### PR TITLE
DO NOT REMOVE PRESSURE PROOFING, but reworks HN crystals into a grenade.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
DOESNT REMOVE THE ATMOS DEVICE REACTION STOPPERY EITHER!

Now that we got the important things out of the way.

This PR turns the HN Crystal into a Gas Grenade that spawns 90 mols of HN gas in a 3x3 area around the grenade. Meaning it can stop reactions on a 18 tile area.

The goal is to make HN a more available tool for ATs to use against whatever gas reaction they/others are working on and went haywire.
HN flamethrowers are soul, but also not something commonly or easy to use and security might get mad if you are waving a weapon around, even if the goal was not murder.

Since the grenade spawns 90 mols of HN, I had to increase the HN used on the recipe from 85 to 100 to prevent HN duping and it is just a rounder number to deal with.

I wanted to make it spawn more HN to make it more useful but would need to increase the recipe value's further and I don't want to deal with pressure proofing balance memery.

"He sneaked a nerf into the PR, maintainers get him!!!"
## Why It's Good For The Game
The HN Crystal's pressure proofing has a few issues that I will totally ignore on this PR.

They are basically useless for ATs since they have multiple pressure proof suits at roundstart and need them to do the bulk of their work.
Now they have a use for any janitor-like AT that goes out to deal with gas issues around the station.
## Changelog
:cl: Guillaume Prata
add: Hyper Noblium crystals now work as a grenade and spawn up to 90 mols of HN around the detonation area.
balance: HN crystal's recipe HN cost was increased from 85 to 100, to prevent HN dupping.
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
I think it might still be possible to duplicate hypernoblium. Quality loss can be negative.

**Comment by TheVekter** [comment]
The point of the pressure proofing isn't to pressure proof your stuff as an atmos tech, it's to do it for other members of the crew.

I don't know enough about atmos to say whether or not this is truly useful, but to my knowledge, most of the gas interactions happen pretty damn fast. How valuable is this actually going to be? It feels less like we're trying to find creative uses for the item and more like we're shoehorning additional functionality into the item for the sake of it.

**Comment by Pickle-Coding** [comment]
I think it might be better if you could attach a flamethrower to a canister to directly feed from it and also quickly refill the tank. That way the transferring gas problem can get solved for any mixture instead of specific crystals for specific gases. Could use the canister's output pressure and whatever releasing/pumping proc they use to determime gas output so you can more efficiently transfer room temperature gas.

It might be more work, but you could make a gas sprayer that's basically a flamethrower but isn't called a flamethrower, doesn't ignite gases and doesn't have a flame if you are worried about getting arrested over it. The flamethrower could be a subtype of it that simply ignites the gases.

**Comment by GuillaumePrata** [comment]
> I think it might still be possible to duplicate hypernoblium. Quality loss can be negative, so the moles consumed can be less than advertised.

I forgot quality is a thing to the crystallizer, I will go figure out what is the discount cap and see if it needs to be changed further.

**Comment by GuillaumePrata** [comment]
> The point of the pressure proofing isn't to pressure proof your stuff as an atmos tech, it's to do it for other members of the crew.

I know, it doesn't change the fact it is useless for ATs so they have no reason to make it, outside of wanting to help others ignore atmos issues passively.
Now that is a tool the ATs themselves might desire, more likely for them to make the crystals and give leftover ones for the crew, or make for the crew and have leftovers for themselves.

Both sides win.

> It feels less like we're trying to find creative uses for the item and more like we're shoehorning additional functionality into the item for the sake of it.

Honestly, I'm shoehorning into the HN crystal and it is the best way to do it.
HN grenades have potential to be a nice addition, I could add a new item to the game and now we have 2 different HN crystals to just confuse the players, I could rename the original HN crystal into HN potion or whatever, but again, confusing to players...

This is the cleaniest way to achieve it.

**Comment by Pickle-Coding** [comment]
> > I think it might still be possible to duplicate hypernoblium. Quality loss can be negative, so the moles consumed can be less than advertised.
> 
> 
> 
> I forgot quality is a thing to the crystallizer, I will go figure out what is the discount cap and see if it needs to be changed further.

85% reduction at maximum. The crystal would pretty much be useless if you make it account for that without changing mechanics.

**Comment by TheVekter** [comment]
> I know, it doesn't change the fact it is useless for ATs so they have no reason to make it, outside of wanting to help others ignore atmos issues passively. Now that is a tool the ATs themselves might desire, more likely for them to make the crystals and give leftover ones for the crew, or make for the crew and have leftovers for themselves.

We don't code things explicitly around their use for the individuals involved. If Atmos techs weren't making them at all, I would understand where you're coming from, but they get made in most rounds I'm involved in. I see them a lot.
 
> Honestly, I'm shoehorning into the HN crystal and it is the best way to do it. HN grenades have potential to be a nice addition, I could add a new item to the game and now we have 2 different HN crystals to just confuse the players, I could rename the original HN crystal into HN potion or whatever, but again, confusing to players...
> 
> This is the cleaniest way to achieve it.

Is there an explicit reason you're trying to generate new uses for an item that already _has_ interesting uses instead of just making a new one? I brought up my previous point because this seems less like you're trying to do something interesting or give players something cool to get and more like you don't like what HN crystals do now and want to remove that functionality later.

**Comment by GuillaumePrata** [comment]
> Is there an explicit reason you're trying to generate new uses for an item that already has interesting uses instead of just making a new one?

I already explained why the other options are more confusing than just adding extra functionality for the item players already have *and* create on a good percentage of rounds is the best design decision if we want HN grenades.

> I brought up my previous point because this seems less like you're trying to do something interesting or give players something cool to get and more like you don't like what HN crystals do now and want to remove that functionality later.

I have been hearing about pressure potions and most space proofing features being removed soonTM since I joined the game almost 5 years ago.
This is not me wanting to remove the functionality later, I just won't wait another 5 years for the soonTM to be merged and open up room for other Hyper Noblium features.

**Comment by GuillaumePrata** [comment]
> 85% reduction at maximum.

So you mean the 100 requirement becomes 15?
Because if that is the case, we should just throw the fear of dumping out of the window (I'm assuming some other grenades already dupe with that much discount) 
We can't design things around such a massive discount...

**Comment by Pickle-Coding** [comment]
I think I'll remove the discounting/extra consumption thing later on. Not really a good UX to have gases deleting or duplicating. Some crystal formations could have an extra effect that consumes extra to turn into waste gases from quality loss to keep things interesting.

**Comment by Erol509** [comment]
Pressureproof ability on hypernoblium crystals was really nice, and I honestly always made them exactly for that. They remove the need to use MODs which slow you down. Not sure if it related to only downstream Im playing at, but they also give you temp resistance. Turning into granade will make it another useless item which might never be used, like other grenades. But stoping fire, refilling room is easy as always, and thoes special effects  of proto nitrate nades etc.. are never used.

**Comment by LemonInTheDark** [comment]
I am in theory fine with this. are you still up for working on it?

**Pull request closed without merging**
