### PR TITLE
Clown ultra final

### PR DESCRIPTION
**Pull request by Comxy**
## About The Pull Request

This is my second PR. I am not good at coding in this language and barely understand it, but I made some functional clowns. All objects added are related to the added clown mobs. The things added are simple but it doesn't need to be more than that in my opinion.

FAQ (by me):

Why did it take so long?
It was a long battle but I managed to fight through the bytes. Also I had merge conflicts, and those where nightmares.

Why not add it to an event?
Because I don't know how to make one, and this already cost enough time. I thought I would finish this before I would leave it as another lost project.

This poll adds;

- a bunch of new sprites
- 3 new clown mobs
- 4 new spells
- 3 new foods
- 2 new bullets
- 1 new carpet tile
- 1 new wizard staff
- 2 new things to buy as a wizard
- a bunch of fun

## Why It's Good For The Game

New things are always good for the game in my opinion. This update will add new spells and new mobs. I don't know what more we want. I could add there to an triggering randomly in game event, but someone else can also do so if they find it interesting enough to trouble themselves with a wall of code.

promo_1
promo_2
promo_3

## Changelog

:cl:
add: Added three new clown mobs including four new spells.
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
SS13: The Painful

**Comment by Comxy** [comment]
I don't know why the integration tests failed. When I play with it on my local server it works fine. If anyone knows what is wrong feel free to tell me.

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]
I'm not totally sure this is something I want, especially since it's totally inaccessible in game. I guess we already have clown mobs like that, so I can't complain too much.

Have a code review, I found the reason your tests are failing

**Comment by TheBonded** [comment]
why not put these into cytology and the clown bomb?

**Comment by D4C-420** [comment]
At least one of these spells should be accessible by wiz seeing as wiz has a lack of clown based gimmicks

**Comment by LemonInTheDark** [comment]
> 
> 
> It couldn't find the element type path so I just kept it in the bullet file. Also integrations keeps failing, I am not sure why, but it works when I play locally so it should be fine.

They're failing because of runtimes caused by non mobs getting passed into those heal/hurt blocks

> 
> 
> I'll just close this. I am not going to work on this any further since I don't know what I am doing though I have learned a bit more about how the code works. All my code is copied and modified from other similar concepts I found interesting like lava for my carpet tiles. I'll just work on another PR if I find something interesting to add in the future.

That's totally understandable. I hope you learned something from it, and I look forward to what you do next. This may have not had great chances, but practice makes perfect.
I've gone through and responded to your questions in the reviews, sorry about the delay there, I was on break for the weekend and missed some. You don't need to respond if you don't want to, but I hope they go some way towards explaining what I was saying, and maybe teach you something about byond

**Pull request closed without merging**
