### PR TITLE
Settles the sabre/rapier debate once and for all

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: spessmenart
imageadd: The captains sabre no longer looks like a rapier.
/:cl:

sabrescreencap

I had my scaling wrong in the picture so I've put the item sprites below

sabre 1

sabre3

The rapier sprites have been renamed and left in the dmis if anyone wishes to use them for anything else

### CODE REVIEW

**Comment by RandomMarine** [comment]
I can't tell if the curving part of the sprites look wonky because they are, or if your screenshot suffers from uneven scaling.

Either way it's the better solution than renaming it all.

**Comment by ExcessiveUseOfCobblestone** [comment]
Why not let the captain decide by alt-clicking the sord?

**Comment by pubby** [comment]
:-1: on the blade pixels looks bad

**Comment by KorPhaeron** [comment]
sabre 1

**Comment by pubby** [comment]
:+1: on the blade pixels looks good

**Comment by RandomMarine** [comment]
bruh
 @KorPhaeron

**Comment by KorPhaeron** [comment]
Though if it consistently gets messed up because of scaling or whatever then I guess the sword might be to be resprited to be straight

**Comment by KorPhaeron** [comment]
@RandomMarine 

Thanks

**Comment by calzilla1** [comment]
That looks ugly as shit

**Comment by juanototo2** [comment]
yeah, let him decide via alt clicking the sword if he wants it to be a sabre or rapier but you'd probably deny it under "it's going to be chap null rod bloat 2.0"

**Comment by Iamgoofball** [comment]
@KorPhaeron 

just make it look like a rapier

when using it, you can only fight other rapier users, like so:
i9zsxtczsvlqodefhhm9

**Comment by WJohn** [comment]
Why not both? :thinking:

**Comment by KorPhaeron** [comment]
@wjohn

Because we had like 6 prs over whether its realistic for rapiers to dismember

**Comment by AnonymousNow** [comment]
Iunno. I prefer it to be a sabre, but that vertical sprite makes it look more like a katana somehow.

Maybe we should start taking melee weapon inspiration from another grid-based game with melee weapons - Crypt of the Necrodancer.

**Comment by nicbn** [comment]
Leave it as is and tell rapier people to shh.

**Comment by KorPhaeron** [comment]
@anonymousnow

Probably because they are both curved blades translated into maybe 10 pixels

**Comment by sawrge** [comment]
is that a sky rim reference LOL kor *gamer brofists*

**Comment by PopNotes** [comment]
The rapier sprite looks so much better than this.

**Comment by Arianya** [comment]
this sprite is shit and ruined my commisioned artwork >:(

**Pull request merged**
