### PR TITLE
Gets defines in line.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Literally. Gets almost all defines in an orderly line. I think I only missed components.dm.

Also adds a pair of brackets somewhere in the ishelpers because there should be one.

## Why It's Good For The Game

I think it's nicer to look at.

## Changelog
:cl:
code: Defines are now in an orderly line.
/:cl:

### CODE REVIEW

**Comment by RandolfTheMeh** [comment]
A lot of these files aren't perfectly lined up, though they are a lot better. Going to assume you ran through this a program. If not, bless your weary fingers for all the times you had to hit tab. But yeah, it's a lot more straight, though random defines will have one too many/too little indents, with the problem getting worse as you go further through the files changed. Doubt this is a complaint with any weight, but it's just a heads up.

**Comment by kriskog** [comment]
Did you have a stroke 10 files in?
image

As Randy said, there are a large amount of non-orderly indents and it seems to get worse the further down you get.

**Comment by Jordie0608** [comment]
Github diff viewer doesn't always display whitespace properly, it's fine if you look at the file itself
https://github.com/tgstation/tgstation/blob/08fcd477789839191c5327a275b470abc6205725/code/__DEFINES/research.dm

**Comment by kriskog** [comment]
Huh, the more you know :eyes:

**Comment by nemvar** [comment]
Yep, they don't look right on github, but the actual files are fine.

**Comment by SpaceManiac** [comment]
it's because they are tabbed assuming a tab width of 4 and the diff viewer sometimes uses a tab width of 8 depending on its mood. Guess I need to undo my tab width=2 userstyle ...

**Comment by optimumtact** [comment]
trying to align indents with tabs is a recipe in stupidity.

why should I care to merge this?

**Comment by ShizCalev** [comment]
while my ocd is bothered by this, i feel this is ultimately needless code churn.

**Pull request closed without merging**
