### PR TITLE
Reverts #12165 and make stat() responsive again.

### PR DESCRIPTION
**Pull request by ghost**
See title.

This change might have a very small negligible impact, but being able to click on a panel and have it update instantly instead of delaying you for a few seconds is much better IMO.

Reverts #12165

### CODE REVIEW

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
No.

Having this update 20 times a second isn't tenable

**Comment by Razharas** [comment]
Its time to let go of stat panel and start to use browser tabs with tgui inside

**Comment by Chnkr** [comment]
@MrStonedOne having to wait multiple seconds when switching between stat panels isn't really workable either.

**Comment by MrPerson** [comment]
Splitting the difference would be having all this outputted on the stat panel but not in Stat(). Wizard spells and alt-click do it, for reference.

**Comment by MrStonedOne** [comment]
A 5 sleep is 0.5 seconds. what are you on about, multiple seconds.

Am I missing something?

**Comment by MrStonedOne** [comment]
Remove the sleep from atom, and just have it in client/Stat(), should fix that. (and that sleep in atom is most likely increasing the performance cost of stat and not actually decreasing it.

**Comment by Chnkr** [comment]
Yeah sure.

**Pull request closed without merging**
