### PR TITLE
IceBox Sec Revamp Pt. 2/3 - Corporate Press Release

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This PR is part two of three of my IceBox Sec rework. Part three will focus on the gulag.

Nanotrasen has spent a significant amount of its PR budget to revamp its permabrig after several hit pieces were released on prison conditions on a certain asteroid. Prisoners on IceBox will enjoy several new amenities including:
<details>
<summary>A New Workroom!</summary>

image

</details>

<details>
<summary>Library!</summary>

image

</details>
<details>
<summary>Per--Zzztt REDACTED - 3RD PARTY FUND REQUESTING ANONYMITY</summary>

image

image

image

</details>
<details>
<summary>Workout Area!</summary>

image

</details>
<details>
<summary>Full Rec Room!</summary>

image

</details>
<details>
<summary>Chapel!</summary>

image

</details>
<details>
<summary>Meditation Area!</summary>

image

</details>
<details>
<summary>and Fully Stocked Kitchen!</summary>

image

</details>
<details>
<summary>Don't worry, our prison refit's cost is offset by the ability for several corporate sponsorships!</summary>

image

</details>
<details>

<summary>Full Pictures:</summary>

image

image

image

</details>

Notable changes include separation of the powernet for the security and "public" sides of sec, as well as some interesting new ways to play in the space like cytology. A lot more food is available than normal and there are several extra toys to play with on the verge if not actually contraband.

## Why It's Good For The Game

Provides increased variation to the prison experience that will hopefully inspire others to make the prisons unique on each map. Gives players more to work with and play around with while in the prison as well as provides unique escape opportunities based on the supplies that prisoners find or make. Gives prisoners more incentive to make money by providing them with special vendors.

## Changelog

:cl:
add: NT Investors have built a new perma brig on IceBoxStation for the purpose of press releases.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
you can just draft the PR instead of putting [draft] in your title

**Comment by Zytolg** [comment]
Neato
My main criticism is that it appears that your prison only has 3 cells (discounting the isolation chamber). If I treat the special cell as a special cell (let's reward favoritism here), then that means there are 2 standard cells in the prison. I'm worried that this iteration of icebox's prison may become overwhelmed during the rare event that results in there being several prisoners inserted. 
There are some other minor aesthetic aspects don't work that well to me, such as the benches being placed without their edge counterparts (they look incomplete), but this is a draft and you're going to buffer most of those out before this opens up fully. 
Otherwise, this a very strong design that plays into icebox's strengths. It's labyrinth-like, and sprawls downwards which is something I tried and failed to do when I tackled this very area late last year. I look forwards into how you play this into Gulag in Part-3.

**Comment by Son-of-Space** [comment]
There are four cells total if you count the special cell. I agree it's a little low. I'll look into how I might add another two.

**Comment by wesoda25** [comment]
Yesss, directional windows!

**Comment by ATH1909** [comment]
what are the drink vendor options in this prison?

**Comment by ATH1909** [comment]
lowkey, this prison looks a bit _too_ fancy. maybe that can be a distinguishing feature of icebox's prison, though.

**Comment by ATH1909** [comment]
image
this region looks easy as piss to break out of, especially if you're a roundstart prisoner with an emergency oxygen tank and mask (IIRC)

**Comment by Fikou** [comment]
do we even support more than 1 altar of god

**Comment by Zytolg** [comment]
> There are four cells total if you count the special cell. I agree it's a little low. I'll look into how I might add another two.
> 
> If you have any other minor aesthetic nitpicks please list them. I agree about the benches as well.

I couldn't open up the Bottom Level Diff since it seems to be registering changes across the entire Z, but I did a little diagraming on the above level, and the nitpicking on Z-2 is about the same for Z-3. Now excuse my mousewriting. 

Delcaling the Sec Prison

Most of it is decaling, I think the prison currently lacks that distinct flavor of red. Now if you want to keep things minimal, that's certainly fine, but I'd at least advise some decaling adjacent to the doors. Let them know it's still Sec. You know about the benches, but to elaborate, I think they work best in minimums of 2 (consisting of both sides) and maximums of 4. 1x1 benches look incomplete, and 4x4 benches begin to look comically large. I think your smaller rooms are fine. The Library is a bit fancy for my tastes, but that's opinion speaking, and doesn't matter as much as just making the whole area coherent.

If we look at the bottom-z, I think there are more areas that could benefit from the usage of siding to illustrate a better separation of areas / land use. I don't think your pacification hallways agree with the rest of the prison's design, but they might work better with some extra turf decals to ease the transitions between them and adjacent/adjoining rooms. The canteen feels a little bit cramped, to the degree that it feels a tad claustrophobic. As for the place of worship, it might benefit from some plotted plants placed in the corners behind the benches. 

Anywhere I didn't mention probably could just benefit from some extra detailing work to make them really pop. As I said before, it's overall a strong design, it just lacks that extra oomph factor to really drive the changes home.

**Comment by Son-of-Space** [comment]
<details>
<summary>
Upper Floor
</summary>

image

</details>

<details>
<summary>
Lower Floor
</summary>

image


</details>

**Review by san7890 — CHANGES_REQUESTED** [review]
I went through some of the design stuff with you on Discord so that's fine, but here's a few things I noticed on this latest pass.
<details>
<summary>Images within</summary>

image

Benches don't work like this. Unfortunate. Also, please put a camera in that corner.

image

Weird camera stuff here due to the frosted windows, would you mind placing another one in this room since this should probably be a monitored area.

image

Camera watching the stairs should be placed.

image

These multi-layer pipe connectors aren't hooked up to anything.

image

I also don't think these multi-z adaptors also are working properly, notice that line in the scrubber between them? Might be that the dir is in the opposite direction. I know I'm (probably) not insane because I got the following issue:

`Unconnected red scrubbers pipe located at Labor Shuttle Dock (118,178,4) (JMP)
Unconnected blue air supply pipe located at Labor Shuttle Dock (118,178,4) (JMP)
One-way connection in blue air supply pipe located at Labor Shuttle Dock (118,179,4) (JMP)
One-way connection in red scrubbers pipe located at Labor Shuttle Dock (118,179,4) (JMP)
`

image

Are these racks meant to have stuff? It's alright if the answer is no.

image

You can't unlock these fridges without access.

image

I don't think tinted windows are best here.

image

Maints has a fire alarm but no firelock in that room.

image

Microwave looks... off... try pixelshifting it up a bit to see if that helps, maybe.

image

The tables also blend here, doesn't really look too good with the contrast against the windows.

image

I think you borked your trapdoor, might wanna look into that.

</details>

On other stations, prisoners typically have a window in their cell facing the hall... would you want to put one in or were you specifically avoiding that design pattern? Let me know, I can go either way on that if it's justified.

Also, no intercoms anywhere. We have a special subtype for perma intercoms, please do map a few of those fellas in.

Irregardless, good work. Tram had the most unique perma section out of all the stations with the other four being... a sort of afterthough, but I do genuinely enjoy the thought and creativity that you mapped all of this with, it really adds another layer of depth to IceBox that I think it was  severely lacking. Thank you!

**Comment by Son-of-Space** [comment]
Moved some stuff to those racks and gave the prisoners posters to decorate with.
removed the maint firelock
removed the bench in the hallway for now
made the rest of the requested changes

**Pull request merged**
