### PR TITLE
Modifies the Xeno Kill Chamber to use cold air instead of vacuum [Box]

### LINKED ISSUE #13313: Xenobio kill chamber is broken
The vaccum tiles only work if the door never opens, and someone always fucking opens it, so it doesn't work.

### PR DESCRIPTION
**Pull request by Strathcona**
Since the previous chamber just would vent air if opened, eventually ruining the killing effect, I've replaced it with a cold air loop like the one in the server room.

Cold by itself is less lethal to humans since there's no pressure damage from a vacuum. It's also hooked up to a freezer so it will never run out of cold air as the vent pumps recirculate it.4

I'm not sure about the implementation, so suggestions are welcome.

Fixes #13313

image

### CODE REVIEW

**Comment by duncathan** [comment]
:+1:

**Comment by GunHog** [comment]
The original configuration of Xenobio, before the addition of the slime kill chamber called for the hallway to be separated from the southern maintenance hallway with space. I believe it to be an evacuation point for Xenos.

Perhaps you could maintain the separation somehow?

**Comment by Strathcona** [comment]
Could probably move the whole maint hall down since there's plenty of room. I didn't want to do something that big unless there was reason to but it'd be pretty easy.

**Comment by tkdrg** [comment]
Well, if you _really_ wanted to use vacuum, you could have just replaced a couple floor tiles with lattice, or a couple windows with grille. But this looks fine either way.

**Comment by Strathcona** [comment]
I think it's preferable since it's less lethal to humans and only to slime which makes working with the chamber easier. I think I'll add a winter jacket in there as well.

**Comment by GunHog** [comment]
You use the consoles to teleport the slimes to the chamber, then the dead ones to you for processing. The only reason to enter the chamber is if the workers are working by hand.

**Comment by Strathcona** [comment]
This is what it looks like now

image

**Comment by Incoming5643** [comment]
I don't think that freezer is doing anything, you've got two vents (which expel air) and no scrubbers (which intake air). The chamber air never makes it into the pipes to be cooled.

**Comment by GunHog** [comment]
Huh. The red vents are the ones that intake, right? That is an easy fix.

**Comment by Anonus** [comment]
A slime that hid in the pipes would still die, due to the cold air in the pipes, though it would be a lot of work to retrieve the corpse.
Also, the syphon vents don't appear red in the editor unless you edit the icon state.

**Comment by Strathcona** [comment]
You can var edit vent's pump direction to make them intake.

**Comment by KorPhaeron** [comment]
Why not just remove the door in the current chamber?

**Comment by Strathcona** [comment]
*Murder*. Also just the whole design philosophy of SS13 maps which prioritize theme and RP over pure efficiency at times. I mean, you can just as well ask why the server room is cooled since the servers don't even generate heat.

**Comment by Iamgoofball** [comment]
actually I'm willing to bet that the server rooms and tcomms had plans to actually emit heat and overheat but they never got implemented

**Comment by KorPhaeron** [comment]
@Iamgoofball 

They used to emit heat but atmos lag was horrible back then so I removed that from the machines

**Comment by Shadowlight213** [comment]
@Strathcona replace the 3 rwalls at the bottom of the xenobio hall there with rwindows lIke hownit was originally. Being able to look into xenobio from that maint tunnel is pretty nice and it makes it feel less closed off.

**Comment by Bluespace** [comment]
Ensure the room has full camera coverage please, or the xenobiology cameras won't be able to use it.

**Comment by Dorsisdwarf** [comment]
Xenobio is deliberately able to be seen into from outside. It's the station's defense against CULT GOLEM WAVE

**Comment by Strathcona** [comment]
Windows and camera are added. Merge conflict tho.

**Comment by Strathcona** [comment]
Heyo, we're all good to merge.

**Comment by Cheridan** [comment]
Were the vents ever fixed?

**Comment by Anonus** [comment]
SYPHON VENTS APPEAR LIKE NORMAL VENTS IN THE MAP MAKER

**Comment by Cheridan** [comment]
THANKS BRO

**Pull request merged**
