### PR TITLE
Adds a sound effect to casting Stop Time

### PR DESCRIPTION
**Pull request by Iamgoofball**
it's actually a sound this time, preview here
https://file.house/I38n.ogg

:cl: Iamgoofball
admin: Your next line is, "stop adding jojo references without watching the show"
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
it sounds like someone is farting into the mic really loudly at the beginning

**Comment by Xhuis** [comment]
There's already a sound effect; the sound is played on the creation of the time stop object.

**Comment by Dorsisdwarf** [comment]
pretty shitty quality also the whole spell is already a reference

edti: I forgot there's already a much less awful za warudo sound for stoptime

**Comment by Repukan** [comment]
Fix time stop first

**Comment by Iamgoofball** [comment]
@Xhuis mine is better so I'll replace it then, fuck

**Comment by WJohn** [comment]
I much prefer the one we have now.

**Comment by PKPenguin321** [comment]
I like the current sound
***voomp*** *tick tick tick tick*

**Comment by Xhuis** [comment]
I also think the existing one is better. The proposed sound is very intense in the beginning and doesn't really get the point across except for the tiny bit of ticking in the latter third or so, whereas the existing one includes very obvious and distinct ticking.

The current one also plays in reverse when timestop expires, so you'd have to replace that too.

**Comment by Bawhoppen** [comment]
MY EARS DEAR GOD TURN IT DOWN I DIDN'T EXPECT TO ALMOST FAINT FROM OPENING THE FILE

**Comment by PKPenguin321** [comment]
Oh but I listened to this sound and I like it too
Good thing it doesn't replace the old sound just adds a new one 👍

**Comment by KorPhaeron** [comment]
The timestop effect itself already makes this sound when it spawns

**Comment by KorPhaeron** [comment]
Goof and everyone who thumbed up this PR is being repobanned for not actually playing this game goodbye friends

**Pull request closed without merging**
