### PR TITLE
Gives medical doctors skeleton crew access to the coroner's office

### PR DESCRIPTION
**Pull request by TJatPBnJ**
## About The Pull Request
Medical doctors get access to the coroner's office on lowpop.
## Why It's Good For The Game
Medical doctors no longer have to break into their own department to get their research done on lowpop.
## Changelog
:cl:
balance: Medical doctors now have access to the coroner's office on lowpop
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
this makes sense to me wbu @JohnFulpWillard

**Comment by Comxy** [comment]
Maybe I am seeing things wrong but I think you should add it under extra access instead of minimal access

**Comment by TJatPBnJ** [comment]
it's the only job where extra access comes first 😃 
Thanks for spotting that

**Comment by JohnFulpWillard** [comment]
I didn't see this PR sorry. 
Currently access is given to Coroner, Detective, HoS, HoP and CMO. Skeleton crew gives access to roboticists and psychologists. I intentionally excluded medical doctors from it because it is part of the role's flavor. It was brought up in the past that lack of access was a problem and Roboticists were the middleground that we chose to give the access to, so I have no interest in giving MDs it as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
why psych lol

**Comment by JohnFulpWillard** [comment]
> why psych lol

they are the other med/serv job with limited slots, and they are meant to work together. Coroner has psych office on skeleton pop as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
mental (hence why they need to go to psych)

**Pull request closed without merging**
