### PR TITLE
Makes result of decal painter and tile sprayer not cleanable like the map-start decals

### PR DESCRIPTION
**Pull request by Tastyfish**
## About The Pull Request

The decals from decal painters and tile sprayers are identical to the ones from roundstart, except they're washable. This is good for if you need to undo or erase mistakes. Or to janicart clown nonsense quickly. But it sucks if you're trying to cement some proper borders and queue arrows and whatnot in.

So, they now are not washable, but instead you crowbar the floor tiles up, just like with map-start decals.

- Also added ink level meter for toner cartridges.
- Also, replaced my previous half-effort "white" and "black" tile sprayer colors with neutral and dark. Makes neutral and bar burgundy use the correct unusual alpha values as with the real ones.

## Why It's Good For The Game
So that these aesthetic improvements aren't accidentally wiped by the janitor cleaning up.

As well, the extremely common neutral tile overlays can now be painted.

## Changelog

:cl:
add: The results of the tile sprayer and decal painter can now only be removed by crowbarring the tile, just like map-start.
fix: Tile sprayer's "white" replaced with "neutral", the most common tile overlay color.
/:cl:

### CODE REVIEW

**Comment by iwishforducks** [comment]
This is seriously so cool looking.

**Review by Twaticus — APPROVED** [review]

**Comment by Twaticus** [comment]
whats the reason for making a new object rather than having the decal painter do this by default

**Comment by Tastyfish** [comment]
> whats the reason for making a new object rather than having the decal painter do this by default

I figured the reason it's currently cleanable is for ease of undoing a mistake. Granted I suppose crowbaring and replacing isn't too much trouble either, unless the tile design is unreplaceable.

If I made that the default for the decal painter, I would also completely eliminate CLEAN_TYPE_PAINT as it would no longer be necessary. (The weird plasmaman helmet interaction can be switched to CLEAN_TYPE_HARD_DECAL with no change in functionality)

**Comment by Twaticus** [comment]
> @Twaticus Would you rather the decal painter just produce decals that act this way by default? I can just do that.

my question was from a player perspective and not maintainer or requesting change or anything, i just approved the sprites cause theyre nice :) 
but from that perspective in mind yeah i think it would be cooler if it was inherit to the decal painter. since its pretty general knowledge that if you want to remove a decal, you gotta crowbar the tile. would make sense to have the decal painter be "permanent" unless crowbar'd to keep it consistent and to avoid having to mess with a new object.

**Comment by Tastyfish** [comment]
@Twaticus I was only hesitant to make the leap and cut the tool because I also liked my own icon and shoot graphic, but you're right. The tool outputs now just acts like round-start decals to begin with. Also made the neutral tile color actually match the one in-game, which was a whoopsie on my part when I earlier made the tile sprayer.

**Comment by Tastyfish** [comment]
Oh, I also removed `CLEAN_TYPE_PAINT` as it no longer serves any function. I changed the weird plasmaman function to use `CLEAN_TYPE_HARD_DECAL` for no change in user-facing functionality.

**Comment by Twaticus** [comment]
@Tastyfish to be fair your graphic was definitely cool so i hope you can find a use for it somewhere! i think this is a good change though :)

**Review by itsmeow — CHANGES_REQUESTED** [review]
Paint sealer icon was left in despite being removed

**Comment by Tastyfish** [comment]
> Paint sealer icon was left in despite being removed

You're right, fixed.

**Pull request merged**
