### PR TITLE
Improves the Smoke Machine sprite

### PR DESCRIPTION
**Pull request by MrDoomBringer**
:cl: MrDoomBringer
imageadd: All stations have been outfitted with brand new Smoke Machines! They have nicer sprites now!
/:cl:

because the old sprite hurt my eyes.  [updated](https://i.imgur.com/u1rlldO.png)

[older version](https://i.imgur.com/m8L9eCI.png)
[original sprite](https://i.imgur.com/f0E8Ese.png)

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
I wasn't that much against this PR, but OP appears to be smoke machine. That earns a solid 👎 from me.

**Comment by epochayur** [comment]
thank god, I have no idea what the fuck the old one was supposed to look like

**Comment by GunHog** [comment]
Looks like an improvement to me! What happened to the diff bot?

**Comment by WJohn** [comment]
Only thing I'd really like to see changed are the cables, and how they connect to that large cylinder in the center there. Could use additional detail like connecting ports.

**Comment by MrDoomBringer** [comment]
@WJohn updated sprite! [new](https://i.imgur.com/PEfMff2.png) vs [old](https://i.imgur.com/m8L9eCI.png)

**Comment by ACCount12** [comment]
I wasn't that much against this PR, but OP appears to be really good at spriting. That earns a solid 👍 from me.

**Pull request merged**
