### PR TITLE
Redoes centcom + reskins recovery ship

### PR DESCRIPTION
**Pull request by Okand37**
A complete makeover for our beloved cardboard centcom! Expands the local and otherwise underused cardboard centcom into a more satisfactory and usable headquarters. 

A full map of the new, lively centcom can be found here https://drive.google.com/file/d/0B67Y0cE3wQneT3lYeVdRUnhibXM/view
A picture of the reskinned transport recovery vessel can be found here
http://i.imgur.com/AtnqY1w.png

Additionally, the title screen and abductor ships have been moved more towards the lower left corner, and the ninja holding facility has been moved below the templates.

### CODE REVIEW

**Comment by Mervill** [comment]
Nicely done!

**Comment by dannno** [comment]
the nanotrasen floor is a really nice touch

**Comment by Incoming5643** [comment]
Centcom used to be more like this, but a lot of the machinery and suchs were cut out (or turned into functionless props) for performance issues.

I don't know if that's really changed.

**Comment by Bill-Luxe** [comment]
> tgstation.mdme.dmb - 100 errors, 0 warnings (1/3/17 7:55 pm) (max count reached)>

🤔

**Comment by Okand37** [comment]
Oh, woops. I did this all yesterday and forgot to run a test compile. I'll take a look at it.

**Comment by Armhulen** [comment]
centcom :+1: :+1: :+1: 
recovery ship :-1: it just looks really bland imo

**Comment by Okand37** [comment]
Looks like it managed to get corrupted while I was preparing it for merging. No worries, I had a backup!

@armhulen I'm not sure what you mean, I left the recovery shuttle more or less the same other than editing the floor tiles and re-arranging a few things.

**Comment by Armhulen** [comment]
@Okand37 I know, I just think the one we have now is bland and this doesn't really do much to fix it

I guess what i'm trying to say is that centcom has a look that the space station doesn't- it looks extemely high security and clean and foreign compared to the madhouse that is the station

so when you get what is a cargo shuttle with different floor tiles and a sleeper it just breaks my heart

**Comment by Okand37** [comment]
Ill fix this tomorrow or something

**Comment by Jordie0608** [comment]
@Incoming5643 The added processing time at roundstart should be negligible (unless there's something broken here)
Is that the alternate escape shuttle below the big fancy nanotrasen symbol? I believe it'll need a fair bit more empty space around it.
Also what looks to be some sort of Admiral office near the admin shuttle dock has some cabling and piping that doesn't go anywhere, whats up with that? Why does just that one area have underflooring?

**Comment by coiax** [comment]
1) This is gorgeous design.
2) I hate tiny fans, because they symbolise that we don't have any decent airlock code.
3) Can you put in a docking port for the white ship somewhere?
4) again, this is super gorgeous.

**Comment by Bawhoppen** [comment]
actually after looking further into it, not many fake doors, you need to add more

**Comment by Thunder12345** [comment]
@Okand37 YOU FORGOT THE BAR

**Comment by KingPhilipIII** [comment]
You know. In all my days of SS13 it never occured to me that Central Command is supposed to be an ENORMOUS facility and we only ever see a small part. Mind. Blown.

But yea I like the new Central.

**Comment by Okand37** [comment]
@Jordie0608 I originally made the administration office out of boredom and it ended up spiraling into this. I'll likely add underflooring to the rest of centcom later, if everyone wants it.
@Thunder12345 I don't think I get what you mean. There's a bar and kitchen on opposite sides of the thunderdome observation area.

**Pull request merged**
