### PR TITLE
Box and Meta now have weight machines; machines have more functionality

### PR DESCRIPTION
**Pull request by harmonyn**
:cl: bandit
add: Nanotrasen has installed weight machines on all "Box" and "Meta" station models. Now there really is no excuse to be a lazy fuck!
add: Rumors that Nanotrasen-issue weight machines can be sabotaged with a screwdriver are fake news spread by the Syndicate.
/:cl:

* Adds weight machines to the fitness rooms of Box and Meta. Technically I could only add one to Box without major remapping or removing VRs. (It's where the stool used to be, RIP the stool)
* Weight machines can now be unwrenched. 
* They can also be sabotaged with a screwdriver, causing users to be knocked down and take a small amount of brute damage until it gets fixed. There is no animation for this currently but I'm sure it would be doable to use the animation stuff they already have to hack something up

Why: Because it's inconsistent that the two main stations do not have these when the others do, especially since there's a mood-boosting component to it now, and it adds another small form of on-station sabotage people can do.

EDIT: oh god what did I do with the map line count

### CODE REVIEW

**Comment by epochayur** [comment]
is there a way to tell from looking at them that they've been sabotaged?

**Comment by bgobandit** [comment]
Not currently, otherwise there'd be no point in sabotaging them. There are plenty of antag things (injecting plasma into shit, door charges, etc) that don't have a visual cue

**Comment by optimumtact** [comment]
you need to use the map merger tool

**Comment by ShizCalev** [comment]
conflict.

**Comment by Bawhoppen** [comment]
I don't think we should allow map inconsistency to be a valid reasoning for a PR. While this specific change is fairly benign, wasn't the whole point of having different maps be so that they play out differently and have their own drawbacks/benefits? Having random PRs by everyone to just equalize everything, kind of defeats that purpose.

**Comment by bgobandit** [comment]
it's more like a map just straight up not having a feature that seems odd to me

also this isn't stale I just forgot how to use the map merge tool

**Comment by nicbn** [comment]
Use map merge

**Comment by zamolxius** [comment]
LIGHTWEIGHT BABY!!!

**Comment by ExcessiveUseOfCobblestone** [comment]
If your map has to be competitive by monopolizing certain features you probably want to improve the map.

**Comment by SpaceManiac** [comment]
The merge conflict has not been resolved in two weeks, closing this as stale. Contact any maintainer if you want it reopened.

**Pull request closed without merging**
