### PR TITLE
 Adds Rest hud button, adds small delay to getting up 

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Added a Rest button to the HUD. It allows the user to lie down or get back on their feet.
balance: Getting back up now takes a second, to avoid people matrix-ing bullets.
/:cl:

Rest is an important enough part of the game that it deserves a hud button (I mean, if _creating new areas_ has one). It's placed where the Resist button currently is, since that spot is right above the movement button, while the resist button has been moved above intents.
I believe the reason it was kept off the HUD so long is that it could be used to wavedash projectiles in combat, and keeping it as a verb was unwieldy enough to not be too usable while also managing the rest of movement/aiming.

Of course, balancing through clunkiness sucks, especially when macros exist, so i'm trying out a different solution; since resting is generally meant for peaceful use anyway, adding a small cooldown to getting up shouldn't matter in those situations. If you instead you want to use it in combat, you _can_ use it to dive from a bullet, but it means that generally the shooter will manage to get closer afterwards, so it's not a completely free dodge anymore.

### CODE REVIEW

**Comment by AlexTheSysop42** [comment]
It already had a long enough delay to give a pursuer a chance to catch up

**Comment by XDTM** [comment]
zero?

**Comment by AlexTheSysop42** [comment]
Somewhere between half a second to a quarter of a second even when spamclicking it, enough to make a fairly large difference

**Comment by XDTM** [comment]
One second is significant enough to make it a large tradeoff imo, plus there's the whole fact that you're getting up from a horizontal position, you weren't just ducking.

**Comment by Mickyan** [comment]
I'm not opposed but kinda gimping an interesting mechanic though

Maybe if it worked like an actual dive when you press it while moving in a direction (can byond even do that) instead of just dropping on the spot would still make it interesting to use for dodging even with a cooldown

**Comment by cacogen** [comment]
I've wanted this for awhile actually. Provided there isn't a delay resting, it'll allow you to duck projectiles which I think is pretty cool. I think resting also fools turrets as well.

**Comment by Dorsisdwarf** [comment]
getting up from a rest already has a delay, doesnt it?

**Comment by epochayur** [comment]
pix

**Comment by PKPenguin321** [comment]
Shout out to wavedashing

**Comment by XDTM** [comment]
By the way, the balance change is because i'm fairly sure wavedashing was the reason it was relegated to verbs; if wavedashing is not a concern i'll just remove that part and keep the HUD button.

**Comment by Enzarel** [comment]
Dear GOD people, stop trying to add delays to things. It's already frustrating enough when vital actions, like pumping a shotgun, have delays while you're in the middle of combat, let's not also add delays to everything else.

**Comment by XDTM** [comment]
I mean, those delays exist for the exact same reason, aka not making combat about who can click the buttons faster (or get a macro to do it)

**Review by Cyberboss — APPROVED** [review]

**Comment by CosmicScientist** [comment]
But combat is about who can click buttons faster and also who can click more accurately.

**Comment by DaxDupont** [comment]
this change is bad and you should feel bad

**Comment by XDTM** [comment]
:< tell me why at least

**Comment by AlexTheSysop42** [comment]
>stunned and aggressive grabbed (chaintable is the most common reason)
>try to resist
>accidentally rest because resist was moved
>cant get up while stunned
>they can drag you too
>cant escape or do literally anything
>die

**Comment by DaxDupont** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=18703&view=unread#unread

**Pull request merged**
