### PR TITLE
Removes the "proximity crew pinpointer" (the ones parameds spawn with), paramedic PDAs start with the lifeline app instead

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Removes the proximity crew pinpointer. 
- Paramedic PDAs now start with the lifeline app instead
- Replaced the empty spot in their belt with a bottle of Calomel

## Why It's Good For The Game

- Removes the proximity crew pinpointer. 
  - This pinpointer was fairly useless and also unintuitive. Did you know that the circle grew SMALLER the FURTHER you were from your target, and LARGER the CLOSER? I sure didn't until reading the code. It also goes back to being the smallest circle if you are on the same turf as the target. 
  - When's the last time you've seen a paramedic not throw away the pinpointer roundstart?
  - There are still valid arguments to be said about keeping the proximity pinpointer as "backup pinpointers", and fixing their untuitiveness, for situations in which you somehow lose your PDA and also can't print a real pinpointer. I'm still undecided on the full removal vs just removal from the paramedic kit. I'll see based on response to this PR
- Paramedic PDAs now start with the Lifeline app instead
  - Prior to the PDA rework, there was still a good argument to keep the prox pinpointer, as the only way to get a Lifeline app was to buy a modular tablet. But now, since everyone starts with one as their PDA, there is 0 reason not to just install the pinpointer app and use it instead of the prox pinpointer.
- Replaced the empty spot in their belt with ~~a bonesetter~~ a bottle of Calomel
   - I figured it'd be awkward to leave a spot empty, so I replaced it with ~~a bonesetter~~ a bottle of Calomel. 

## Changelog

:cl: Melbert
add: Paramedic PDAs now start with the Lifeline pinpointer app
add: Replaced the "proximity crew pinpointer" in the paramedic's belt with a bottle of Calomel
del: Removed the "proximity crew pinpointer"
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
just delete it it's so fucking difficult to use and when I need to I instead research the nice one and print that

**Comment by Shadowflame909** [comment]
Thank you. I thought its sprite sucked on purpose.. Wish it was more like a pinpointer for people, but I understand how someone could think thats OP

**Comment by GuillaumePrata** [comment]
Suit sensors are a quite powerful tool ~~to validhunt~~ so making the bulk of it be dependent on Tcomms being functional and killing the weaker version and moving into PDAs is nice.

**Comment by Ryusenshu** [comment]
i like this pr, but im against a full removal
Having a backup is good

**Comment by necromanceranne** [comment]
I literally see no reason for why you should want a prox pinpointer when normal pinpointers are not that deep into the tech web. By the time having one is relevant, there should probably be plentiful access to the full power one.

**Comment by Mickyan** [comment]
Something's gone wrong in the powercreep department if prox pinpointers are useless now, as they were added to make regular pinpointers more rare because of how strong they are

> * This pinpointer was fairly useless and also unintuitive. Did you know that the circle grew SMALLER the FURTHER you were from your target, and LARGER the CLOSER? I sure didn't until reading the code. It also goes back to being the smallest circle if you are on the same turf as the target.
Things look bigger the closer you are, I think this more intuitive than the opposite

**Comment by JohnFulpWillard** [comment]
Instead of giving them a bonesetter, why not give them their calomel bottle back?

The reason for removal was the addition of bone gel and surgical tape in https://github.com/tgstation/tgstation/pull/50558 - which originally removed Formaldehyde, but was re-added and removed Calomel instead in https://github.com/tgstation/tgstation/pull/51786 
Since we got a spare slot, maybe we can give back this Paramedic-useful chem? Would encourage use of new chemicals that aren't usually made.

**Pull request merged**
