### PR TITLE
Converts slowdown from lacking limbs into a movespeed modifier

### PR DESCRIPTION
**Pull request by ninjanomnom**
More movespeed mods and movement_delay removal

:cl: ninjanomnom
fix: Chopping off all your legs and growing a few dozen arms no longer turns you into the fastest monstrosity this side of the milky way
fix: Lacking legs/arms no longer slows you down if you're weren't using them to move anyway
/:cl:

### CODE REVIEW

**Comment by Couls** [comment]
Missing a leg no longer slows you down?

**Comment by Tharcoonvagh** [comment]
Are you against people with disabilities

**Comment by ninjanomnom** [comment]
@Couls ah I meant if you're not on the ground. I removed it slowing you down if you can fly/float/whatever

**Comment by Couls** [comment]
This means losing an arm and a leg will slow you down even if you’re not crawling

**Comment by ninjanomnom** [comment]
Ah yeah I forgot to check arms only if 0 legs

**Pull request merged**
