### PR TITLE
Adds 2 new maintenance ambience tracks.

### PR DESCRIPTION
**Pull request by Capsandi**
## About The Pull Request

Check em
ambimaint6.ogg
https://voca.ro/18Z7uzi10WEu
ambimaint7.ogg
https://voca.ro/1kRJ2akcYxdy

both around the same length as the other ambimaint tracks

theres no attributions bcuz all samples used are of my own creation 

## Why It's Good For The Game

I have heard that maintenance ambience as it stands is considered repetitive and in need of more clanky clonky sounds

## Changelog

:cl:
sound: 2 new ambient tracks for maintenance tunnels
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
~~So which 2hue song are these from~~

Anyway, very thematic.

**Comment by EricZilla** [comment]
You should attribute them to yourself, it will help others in the future properly credit stuff

**Review by Ghommie — APPROVED** [review]

**Comment by Jacquerel** [comment]
> You should attribute them to yourself, it will help others in the future properly credit stuff 
Do this, future contributors and interested parties will thank you. Plus, our repo is open source so other places may use them in their SS13 projects and wish to attribute you.
Then I'll merge it.

**Comment by Capsandi** [comment]
will do

**Comment by Capsandi** [comment]
licensing info added for these tracks as well as ambispace4 added in #75379

**Pull request merged**
