### PR TITLE
Box Atmos Waste Line Addition

### PR DESCRIPTION
**Pull request by Cyberboss**
Really we just need a space exit point **inside** atmos, not half-way to the AI sat

:cl: Cyberboss
add: The waste line now has a digital valve leading to space (off by default) along with a port on it's far side
/:cl:

untitled

Pic outdated. Circles 1, and 3 have been reverted. And the manual valve has been changed to digital

### CODE REVIEW

**Comment by Supermichael777** [comment]
might be too good if disposal loop is clogged with hot gas

still beter

**Comment by Iamgoofball** [comment]
Thanks dude :+1:

**Comment by TehPear** [comment]
That or leave it alone as atmospherics techs can easily modify the waste line and filter line to actually capture freon, water vapor, and BZ by just putting filters on and attaching a connector with a canister to it. I've done this plenty times and it has worked well thus far. Make other atmospheric techs do their damn job as it isn't suppose to be fully optimized and it gives them additional duties.

**Comment by CyberbossJHCB** [comment]
@TehPear If you're talking about the end of filtering I kinda agree with you, now that I think about it. The main purpose of this PR was to give atmos access to a space air injector (Instead of having to use the one north of the AI sat). I'll probably scale it back.

**Comment by ExcessiveUseOfCobblestone** [comment]
I wouldn't mind having some more "cells" for Freezon and Watervapor though.

**Comment by CyberbossJHCB** [comment]
@ExcessiveUseOfCobblestone Me too, but thats a major atmos rework in all maps

**Comment by Shadowlight213** [comment]
@CyberbossJHCB
Make it a digital valve instead of a manual one so silicons can use it.

**Pull request merged**
