### PR TITLE
Fixes #31897 , cryo base disappearing

### LINKED ISSUE #31897: Screwdrivering open cryotube base makes it vanish.
bug - cryo tube base vanishing

I was trying to help, and I made something vanish from this dimension.

### PR DESCRIPTION
**Pull request by QualityVan**
Medbay: vanishing point edition.

Fixes cryocell's icon being set to something that doesn't exist, makes cryocells update icon when the maint hatch is opened, gives failure feedback for trying to open the main hatch when you can't.

[outdated]Caused by #31356 but I think the panel didn't show up when screwdrivered before that anyway. Looking at the old sprites, the wiring panel seems like it was supposed to act like an overlay but there's nothing in cryo code to support that. Added a sprite which is the closed cryo pod with the not-overlay applied.

Fixes #31897

### CODE REVIEW

**Comment by lzimann** [comment]
<details><summary>icons/obj/cryogenics.dmi</summary>
Key | Old | New | Status
--- | --- | --- | ---
pod-o||pod-o|Created
pod-o1||pod-o1|Created
pod-o3||pod-o3|Created
pod-o2||pod-o2|Created
</details>

**Comment by Cyberboss** [comment]
@lzimann this was the original borked comment:

**Comment by Cyberboss** [comment]
<details><summary>icons/obj/cryogenics.dmi</summary>
Key | Old | New | Status
--- | --- | --- | ---
pod-o||pod-o|Created
pod-o1||pod-o1|Created
pod-o3||pod-o3|Created
pod-o2||pod-o2|Created
</details>

**Comment by Cyberboss** [comment]
<details><summary>icons/obj/cryogenics.dmi</summary>
Key | Old | New | Status
--- | --- | --- | ---
pod-o||pod-o|Created
pod-o1||pod-o1|Created
pod-o3||pod-o3|Created
pod-o2||pod-o2|Created
</details>

**Comment by QualityVan** [comment]
@lzimann your bot captured the wrong sprites, not sure why

**Comment by lzimann** [comment]
I don't have internet right now so can't fix/debug it.

**Comment by nicbn** [comment]
It wasn't caused by #31356 if the problem is at the dmi file.

**Comment by nicbn** [comment]
>there's nothing in cryo code to support that.

`add_overlay("pod-panel")`

Also you didn't modify the code, so there isn't any reason for this sprite to show up.

**Comment by QualityVan** [comment]
Yeah, but I'm not seeing where panel_state - oh it's in machine's screwdriver deconstruction. The break was changing default_deconstruction_screwdriver(user, "pod-off", "pod-off", I) to default_deconstruction_screwdriver(user, "pod-o", "pod-off", I) , which since pod-o didn't exist gave the base a nonexistent sprite. I'll doublecheck the panel thing though.

**Pull request merged**
