### PR TITLE
Makes the pronoun helper proc names less horrifyingly long

### PR DESCRIPTION
**Pull request by ChangelingRain**
Emotes now actually check pronouns instead of using the unreliable byond macros
Also removed some duplicate emotes
Added more helpers

### CODE REVIEW

**Comment by xxalpha** [comment]
I think they were better named before. p_their makes no sense.

**Comment by ChangelingRain** [comment]
Consider that if you're using them in a string it's a huge goddamn line of characters. `You have an overwhelming desire to kill [L]. [L.p_they(TRUE)] [L.p_have()] been marked red! Go kill [L.p_them()]!` is more readable to me than `You have an overwhelming desire to kill [L]. [L.they_pronoun(TRUE)] [L.get_has()] been marked red! Go kill [L.them_pronoun()]!`

**Comment by ike709** [comment]
I agree with xxalpha, it made more sense before this change.

**Comment by ChangelingRain** [comment]
My concern is more readability than how much sense the proc name makes, especially given that a pretty good chunk of the uses are going to be inline, like in the examples I provided up there.

If someone doesn't understand what the proc does from context(which should make it relatively obvious in most cases), I'd hope they'd at least look it up.

**Comment by pudl** [comment]
Yeah theres no reason to shorten these names, theyre about as long or even shorter than a lot of pronoun names. Sometimes clarification is better

**Comment by optimumtact** [comment]
confrictu

**Pull request merged**
