### PR TITLE
Goliaths can no longer tentacle rape through the solid floors/walls

### PR DESCRIPTION
**Pull request by Core0verload**
I saw one of those rape miners at mining base, somehow spawning the tentacles on plasteel floors and metal walls. It didn't made much sense. The same is happening on the space turf, and it makes even less sense there.

Fixes goldgrubs digging into the station floor and disappearing.

### CODE REVIEW

**Comment by Robustin** [comment]
Core you've lost whatever respect I had left for you.

**Comment by Core0verload** [comment]
ha ha ha ha ha
i'm laughing at you Robustin
retards with a balance fetish are actually pretty funny when you stop taking them seriously

**Comment by KazeEspada** [comment]
You could make them damage the floor.

**Comment by KorPhaeron** [comment]
Cheridan commented on Mar 15
its really just opening a portal to the lava dimension, like how Cyclop's eye lasers work

**Comment by TechnoAlchemisto** [comment]
I always assumed that they were digging under the earth, then popping up and grasping the ankles. So it could work through walls, just not on space.

**Comment by Incoming5643** [comment]
If you really wanna see some shit bring a gold grub to the station then scare it

**Comment by Core0verload** [comment]
Yeah, I guess I'll fix gold grubs digging into the station floor too.

**Comment by Robustin** [comment]
Core you've lost whatever respect I had left for you.

**Comment by KorPhaeron** [comment]
Anyway shitposting aside I don't really like this PR

Makes indoors very safe while also ruining the traitor lazarus injector

**Comment by Core0verload** [comment]
Goliath is less of a murder machine on station now, but it still packs a punch. It's deadly in melee, and the most common ranged weaponry (your 20 burn laser) isn't going to work well on it. It lost it's ability to trip people, but it was mostly useful against singular targets, and on station it's usually fighting a mob.

**Comment by PKPenguin321** [comment]
:-1: you have clearly never experienced the horror of a goliath breaking into your survival pod just when you thought you were safe from the ash storm, or the glee of siccing a lazarus'd goliath on the crew. This PR makes both less fun.

In buzzword terms: HUGBOX

**Comment by KorPhaeron** [comment]
I just saw a miner cowering in their pod, saying their goodbyes as they watched rocks break towards them, followed by the whole pod wall coming down, a locky dodge past the tentacles into the one free corner of the room, and finally a sprint through the burning storm into the safety of a nearby friends pod. I like goliaths being scary like that.

**Pull request closed without merging**
