### PR TITLE
Tweaks the Chameleon mutation

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: If you die with the Chameleon mutation, you now become fully visible.
tweak: Chameleon now fades out smoothly instead of jerkily.
tweak: You now become visible if you fall unconscious with the Chameleon mutation.
/:cl:

* Going invisible is now smooth and looks much better.
* Dying or falling unconscious will cause you to fade to full visibility over three seconds. You cannot fade out if you're dead or unconscious and will instead remain at full visibility.
* Moving still instantly brings you to full visibility for balance reasons.
* Also adds an `on_death` proc for human mutations, called when their owner dies. This is necessary to support the new changes.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
but why

**Comment by kevinz000** [comment]
stop nerfing me chamo + healing virus was the best
also this is a buff because dying with it was one of the drawbacks but i like the change kek

**Comment by Xhuis** [comment]
@KorPhaeron Dying and then being unable to be found for the rest of the round is awful. If I had to keep one thing in this PR it would be that.

**Comment by KorPhaeron** [comment]
But now it is just another no brainer passive buff that is 100% desired in every possible situation

**Comment by Xhuis** [comment]
And? There are very few genetics mutations that have drawbacks. While I'd love it to be balanced, this isn't deliberately attempting to change the balance in any way besides making dying with it less damning. If you have suggestions for balancing I'll take them, but permanent round removal in the majority of cases is something I will never accept.

**Comment by XDTM** [comment]
Unlike heat resistance, TK, xray and dwarfism

**Comment by KorPhaeron** [comment]
@XDTM 

Those are also bad

**Comment by XDTM** [comment]
I agree to be honest, but to fix that the whole of genetics should be reworked tbh

**Comment by Xhuis** [comment]
What he said. I don't care if those are bad for this PR because it's not relevant. This is just a minor change to improve quality of life.

**Comment by KorPhaeron** [comment]
>quality of life

There is that phrase again

**Comment by Xhuis** [comment]
Yep. There it is. Good to know we're all literate here.

**Comment by Kromgar** [comment]
Dwarfism has a downside... glass tables

**Comment by Shadowlight213** [comment]
Leave chameleon making you invisible when dead. It was a good drawback. You died and couldn't be found, rip you. It's almost as if death is part of the game.

**Comment by Aloraydrel** [comment]
>every mutation shouldnt have drawbacks

Meme genetic lottery strikes again

**Comment by Kromgar** [comment]
Didnt warmth used to make cryo not work on you?

**Comment by Aloraydrel** [comment]
Its suppose to

**Comment by Xhuis** [comment]
How's that make any sense? Cryo is for cold stuff, you doofus.

Anyway, since people seem to dislike this, I'll close it. I still don't agree with it, but I won't fight what the majority wants.

**Pull request closed without merging**
