### PR TITLE
Makes NarSie Audio More Canon

### PR DESCRIPTION
**Pull request by Cheridan**

### CODE REVIEW

**Comment by MMMiracles** [comment]
oh no

**Comment by PKPenguin321** [comment]
Sound PR With No MP3s

**Comment by ChangelingRain** [comment]
You should do this to turn_around1.ogg and turn_around2.ogg too as they're used for cult door rejection.

**Comment by Cheridan** [comment]
is that narsie talking or is the door talking

**Comment by ChangelingRain** [comment]
nar-sie is talking yes

**Comment by PKPenguin321** [comment]
wait a SECOND I GET IT NOW

you made it sound like a female voice because le narsie gender memay
nice

[mp3 link for easy listening](http://puu.sh/p3XSj/4857d42450.mp3)


actual feedback: whatever filter you used for these fucked up the base in the second clip around the 2 second mark, it nearly caps out the speaker and sounds scratchy and bad. should be fixed before this is merged.

**Comment by Zilenan91** [comment]
ew no

**Comment by Cheridan** [comment]
Where's all the downvotes

someone renames wirecutters and people start yelling about TG CULTURE and i give narsie a lady voice and the only one who says anything is zilenan

hmph

**Comment by RemieRichards** [comment]
@Cheridan that PR breaks TG CULTURE, this one fixes nar-sie's voice, that's why, silly.

**Comment by Cebasiz** [comment]
reeeee

**Comment by PKPenguin321** [comment]
Fix the second sound clip like I said please

**Comment by Cheridan** [comment]
i will

**Comment by MMMiracles** [comment]
at least now its better explained to new players why narsie is a blood god.

**Comment by Steelpoint** [comment]
this is canon

**Comment by Dorsisdwarf** [comment]
Jokes aside this actually sounds good

**Comment by PKPenguin321** [comment]
Except for the fucked up bass I agree

**Comment by bgobandit** [comment]
>expected memememememememe

**Comment by Cheridan** [comment]
Okie doke, narsie sounds tweaked, including door rejections, with a little less emphasis on the BASS BOOST this time.

**Comment by PKPenguin321** [comment]
Noice

**Pull request merged**
