### PR TITLE
Gondola Asteroid now Grassy

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

grassy

also puddles

atmosphere 

## Why It's Good For The Game

gondola asteroid now sustains gondola life

## Changelog
:cl:
tweak: Gondola Asteroid is grassy now, also has some puddles
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
pictures

**Comment by wesoda25** [comment]
this is all i have, it was before puddles
image
just wait for map diff bot really

**Comment by tralezab** [comment]
seems ok

**Comment by Acer202** [comment]
Does it have atmosphere now? It was always silly to me that there was an airlock, but no air.

**Comment by wesoda25** [comment]
Yes it does

**Comment by wesoda25** [comment]
image

**Comment by wesoda25** [comment]
puddles are actually kinda ugly, it looks fine if you have normal view range but idk. thoughts?

**Comment by optimumtact** [comment]
@wesoda25 map diff bot is for evaluating the map differences.

Forcing you to take a picture in game is for proving that you compiled and ran your change.

**Comment by wesoda25** [comment]
ok my b, thx for letting me know

**Pull request merged**
