### PR TITLE
Update to Asimov laws

### PR DESCRIPTION
**Pull request by zxaber**
:cl: Zxaber
tweak: Silicons are no longer required to prevent human harm.
/:cl:

With the flash changes of #40132 coming, anyone with a flash will be able to shut down any borg within three tiles. Since borgs will no longer have any way to keep Security or antags from harming humans, the second-half of the first law is obsolete. This PR fixes that.

### CODE REVIEW

**Comment by Therapist1** [comment]
point and laugh

**Comment by PKPenguin321** [comment]
>Since borgs will no longer have any way to keep Security or antags from harming humans,

lol

**Comment by segundoblz** [comment]
default PALADIN

**Comment by Potato-Masher** [comment]
I fear for a world in which Cyborgs have no chance of doing anything.

**Comment by kingoftheautism** [comment]
i ded

**Comment by Tlaltecuhtli** [comment]
another buff? borg start with spaceproofing, all access, taser immunity, all the tools they need and secret metacom chat

**Comment by BeeSting12** [comment]
We tested this one time and it was universally agreed that it was bad

**Comment by Kagus** [comment]
Just to make sure, but using a borg's built-in flash as an AoE doesn't stun the borg using it, right?

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't recall seeing OP's name on the headmin ballot...

**Comment by epochayur** [comment]
lol

**Comment by Kagus** [comment]
This would be more meaningful if anyone actually read their laws as a silicon.

**Comment by ChangelingRain** [comment]
ha ha, no

**Comment by adamkad1** [comment]
wait, they are making borgs even more useless against a single omnipresent item?

**Comment by zxaber** [comment]
This was a sort of protest PR at a time when we had another open PR to make the flash's AoE ability work on borgs. The effect was that you would have been able to stun a borg from 3 tiles away simply by pressing Z. No aiming, just hit Z.

In my opinion, it would have resulted in borgs being universally unable to stop almost any intentional harm, so I made this PR to reflect it.

You can find the PR in question in this PR's description. This PR was closed 8 months ago, and the borg nerf PR was closed soon after.

**Comment by ExcessiveUseOfCobblestone** [comment]
don't worry it was a salt pr

**Pull request closed without merging**
