### PR TITLE
[READY] buffs crayon contents and removes black crayon frlm the crayon box

### PR DESCRIPTION
**Pull request by jughu**
Cmon just a little more grind results for my green beer beer beer
Also removes black crayon because black isn't a color.

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
dont remove my black crayon

i love throwing it in the washing machine with my insulated gloves

🖕

**Comment by jughu** [comment]
I HAVE A IDEA FOR THAT IN THE NEXT PR JUST WAIT FOR IT CHEMIST CRAYON MAKING MAN

**Comment by MoreRobustThanYou** [comment]
yes hello i have a nitroglycerin nade just for your face

**Comment by jughu** [comment]
Ok  hai

**Comment by jughu** [comment]
Oke auctally MRTY I PROMISE U YOU LOVE MY NEXT PR

**Pull request closed without merging**
