### PR TITLE
Goof Economy 2.0: A Bold New Way to Access Airlocks!

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
A bold new airlock access method has been developed!

## Why It's Good For The Game

It's great to reward players for engaging with the economy, while providing a means for less wealthy individuals to get around!

## Changelog
:cl:
qol: A bold new airlock access method has been developed, brought to you by Space Cola!
/:cl:

### CODE REVIEW

**Review by stylemistake — APPROVED** [review]

**Review by Kylerace — APPROVED** [review]
sounds good

**Comment by Shadowflame909** [comment]
One "Dump Et" and it all becomes a nightmare...

Speed merge

**Comment by Kylerace** [comment]
cool pr

**Comment by Kylerace** [comment]
i changed my mind

**Pull request closed without merging**
