### PR TITLE
Ausops Turfs

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
learntoembedkor

When it tells me to look at the git shell to debug why it wont make a commit I just start over sorry oranges

### CODE REVIEW

**Comment by TehZombehz** [comment]
What all is included in this exactly? Not even the original PR explained it in detail. I see some flora, a nice fancy table with stuff on it, and nice looking new turfs.

**Comment by Ausops** [comment]
http://pastebin.com/dX72vLdT

**Comment by Bawhoppen** [comment]
@TehZombehz thank you for describing the picture

**Comment by Dorsisdwarf** [comment]
Its a sprite PR that reworks how some icon stuff works too

**Comment by TehZombehz** [comment]
>Because everything in the picture is straight forward >Because a picture always shows 100% of what's in a PR >Because every PR around here is nice enough to include a picture >For all I know this is clown planet 2.0

**Pull request merged**
