### PR TITLE
Replaces the accounting machine with all IDs having their own bank account by default.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

This PR makes it so that all blank ID cards start out with an unassigned job, bank account.
That means that if you lose your ID card, or don't have access to an ID card, you automatically start out with the same type of "savings" bank account that the accounting machine would give you. These bank accounts are overwritable so that if you were to for some reason need to attach your bank account to it, it would merge your ID card with the savings account.

image
_An example of a blank ID card being used as a bank account with these changes._

As a consequence, the accounting machine is basically useless with this change, and has been removed from the techweb, as it's job is performed automatically. Not to mention that since the accounting machine wasn't available by default on current maps, I don't see a reason for it to hang around. One side affect however is that new ID Cards won't be able to create new bank IDs, so if there's strong enough sentiment I can try to retool that here.

This also adds additional protections to the unassigned job to prevent all jobs from starting with money as a consequence, so we can use it as, ya know, an unassigned job.

## Why It's Good For The Game

Bank accounts and their handling are a colossal pain in the ass from a code perspective, since when you create a new, non-round start mob, they may spawn with an ID card, but that ID card will not come with a bank account. We only started offering giving mobs a new bank account over a year ago with the accounting machine, but it's finicky, and quite honestly not intuitive to get new IDs to behave like round start IDs.

This also improves baseline interact-ability with economy locked systems by giving everyone an ID that can be used with payments or similar. It means that as long as a player has their ID, we can place an assumption that they have a bank account, which we have to check for ***every time*** something is added with economy integration.

## Changelog

:cl:
qol: All ID cards have been given a basic, standalone bank account. Not just for crew, new and old, but also for IDs fresh out of the box.
del: The accounting machine has been retired from station use, as accounts come with a default bank account now.
/:cl:

### CODE REVIEW

**Comment by Ryll-Ryll** [comment]
Blessed, this shores up a lot of my concerns with the lathe tax

**Comment by Fryzzie** [comment]
How does this interact with the mining id given to golems and via the mining conscription bag?

**Comment by ArcaneMusic** [comment]
> How does this interact with the mining id given to golems and via the mining conscription bag?

This shouldn't have any effect on their vending, as the mining ID they have is given a custom trim containing their access, but would have a bank account in addition to the ability to hold mining points. They would also not come with credits by default. So, not much would change.

**Comment by ArcaneMusic** [comment]
DNM for the moment, I learned a critical balance breaking bug during testing which I'm glad my sleep deprived brain caught.
image
Basically this will break inflation in half like bane did to batman

**Comment by ArcaneMusic** [comment]
image
Crisis averted, nice job me 🤝

**Pull request merged**
