### PR TITLE
fix fire alarm spam

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
fix this
image
it happened on simple gas release without fires before, during or after.

## Why It's Good For The Game
not having this is good
image

### CODE REVIEW

**Comment by MacBlaze1** [comment]
this is entirely potatos fault

**Review by LemonInTheDark — APPROVED** [review]
lmao lol

**Comment by Palpetinus** [comment]
So fire alarms don't just break the sanity of the crew members, but also the server itself

**Comment by GoldenAlpharex** [comment]
The hero we really needed.

**Comment by LemonInTheDark** [comment]
Doesn't fix the actual expense fully, but is good regardless, thanks

**Pull request merged**
