### PR TITLE
Replaces mice with something better (APRIL FOOLS)

### PR DESCRIPTION
**Pull request by MelokG000**
## About The Pull Request
cheesemaus1
## Why It's Good For The Game
because yes
## Changelog
:cl:
image: mice are now funny
/:cl:

### CODE REVIEW

**Comment by xKREKSx** [comment]
miceese

**Comment by Jacquerel** [comment]
you know he ate a cheese

**Review by Wallemations — APPROVED** [review]
You should make mice-shaped cheese

**Comment by TheSmallBlue** [comment]
cheesed to meet you

**Pull request closed without merging**
