### PR TITLE
Basic Mob Carp: Retaliate Element

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Adds an Element and AI behaviour intended to replicate the "retaliate" behaviour which made up an entire widely-populated subtype of simple mobs.
The behaviour is pretty simply "If you fuck with me I fuck with you". Mobs with the component will "remember" being attacked and will try to attack people who attacked them, until they lose sight of those people. They don't have very long memories so breaking line of sight is enough to remove you from their grudge list.
The implementation unfortunately requires registering to 600 different "I have been attacked by X" signals but c'est la vie.

It will still be cleaner than `/mob/living/simple_animal/hostile/retaliate/clown/clownhulk/honcmunculus` and `mob/living/simple_animal/hostile/retaliate/bat/sgt_araneus`.

I attached it to the pig for testing and left it there because out of all the farm animals we have right now, a pig would probably get pissed off if you tried to kill it. Unfortunately it's got a sausage's chance in hell of ever killing anyone.

## Why It's Good For The Game

It doesn't have much purpose yet but as we make more basic mobs this is going to see a **lot** of use.

## Changelog

:cl:
add: Basic mobs have the capability of being upset that you kicked and punched them.
add: Pigs destined for slaughter will now ineffectually attempt to resist their fate, at least until they lose sight of you.
balance: Bar bots are better at noticing that you're trying to kill them.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
image

**Comment by Elli-Skala** [comment]
They aren't basic mobs yet but this would go well on slimes when they eventually are ported over

**Comment by Mothblocks** [comment]
I can see us wanting to reuse this behavior outside of AIs, like having a vending machine throw stuff back at the person who attacked it/threw stuff at it. Could we split off the "registers to every signal and gets you the attacker" thing into its own element that fires its own signal, then have the AI retaliate behavior use that?

**Comment by Jacquerel** [comment]
Split the big signal aggregator into a different component, and used it for monkeys and bar bots.
I didn't use the ai blackboard element for either of them because they both have slightly different behaviour for that, but Mothblocks' suggestion resulted in something which _did_ work and should ensure that they're easily kept up to date with everything else regardless of how many other `COMSIG_ATTACK_BUNGO` signals we add.

**Comment by Jacquerel** [comment]
Tested that the element works on non-mob atoms, Undrafting now.

https://user-images.githubusercontent.com/7483112/205307754-b5271525-d80a-43fa-9501-ba1256ae1c7c.mp4

**Review by Mothblocks — APPROVED** [review]
LGTM, @tralezab can you give a pass on AI stuff?

**Comment by Time-Green** [comment]
I’m not an AI expert but it looks fine, if there’s anything seriously wrong tralezab can give a review in retrospect

**Pull request merged**
