### PR TITLE
This probably helps.. something?

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## About The Pull Request

does things
so it not warnning anymore in vscode

## Why It's Good For The Game

uhhh
the warnings are gone

## Changelog

:cl:
code: fixed some warnings, code better now?
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
i hate my life i hate my life i hate my life i hate my life i hate my life

**Comment by LemonInTheDark** [comment]
wrong master brother :(

**Comment by LemonInTheDark** [comment]
SeviYummy-1501974396566740993-img1

**Comment by MetalClone** [comment]
eevees suck

**Pull request closed without merging**
