### PR TITLE
Fixes doppler arrays

### LINKED ISSUE #27896: Tachyon array is broken
It doesn't say anything if you set off an explosion.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #27896

### CODE REVIEW

**Comment by loqoman** [comment]
The Travis build has been running for two hours... Is this normal?

**Comment by francinum** [comment]
Exorbitantly long queue.

**Comment by Supermichael777** [comment]
its passing unless you somehow looped the build tools

**Comment by francinum** [comment]
@Supermichael777 according to travis the buildtools haven't even started.

**Comment by Supermichael777** [comment]
yeah its weird

**Comment by ike709** [comment]
image

**Comment by loqoman** [comment]
Oh, I guess they had some sort of issue.

**Comment by loqoman** [comment]
> Should get CI guys working on TGstation

**Pull request merged**
