### PR TITLE
Adds bomb cap modifier and halves single tank explosive cap

### PR DESCRIPTION
**Pull request by ohnopigeons**
Adds a maxcap modifier argument for the explosion proc/datum and sets it to 0.5 for tank explosions without a TTV (single tank bombs).

:cl:
balance: halfcaps single tank explosions
/:cl:

you put in half the volume you get half the boom

Closes #43823

### CODE REVIEW

**Comment by optimumtact** [comment]
this is such an odd fix.

either we remove the ability to do single tank bombs, or we change the recipes on them again to make them even harder.

I don't think this is the right fix

**Comment by deathride58** [comment]
This doesnt even nerf actual onetanks, all it does is nerf suicide mixes, which as the name implies typically results in the user's death anyhow. Actual onetanks are already capped to 3dev

**Comment by pigeonsk** [comment]
I'm fine with removing the ability but it does fill an interesting niche that would be a shame to remove entirely. I'd also be hardpressed to explain why two tanks with a tube in between can function as a bomb but a single tank can't.

And balancing and constraining atmos development around an incredibly niche mechanic which is either ignored or abused seems like an insane idea and the worst fix of the three.

**Comment by pigeonsk** [comment]
@deathride58 [link](https://sb.atlantaned.space/rounds/106869/map)

**Comment by Whoneedspacee** [comment]
i don’t know of a certain way to fix singlecaps because of how things work, but I can tell you that tritiums energy constraints will never work.

i don’t think theres a world where snowflake code doesnt exist to prevent singlecaps and where you also have tritiums weird as fuck burn rate where it massively increases because some magic 50-50 threshold was crossed.

**Comment by pigeonsk** [comment]
I've acknowledged the only feasible way to use singletanks is to spam them in the forums, and the only way to stop that would be to remove it entirely. This PR was an attempt to save the idea of singletank mechanics and carpet bombing, but to be less station-devastating like the round I've linked <sub>(that you were responsible for)</sub>.

I don't really see why you consider this unrealistic when this was the most realistic solution I could find. You have the same pressure but you have comparatively less volume to the TTV bomb, in what universe would the same but smaller bomb not have a smaller yield?

**Comment by HomocidlePancakes** [comment]
Weren’t onetank maxcaps pretty much removed after the trit nerf? Haven’t seen anyone carpet bombing station with then after theat

**Comment by Nickkoranda** [comment]
@HomocidlePancakes https://sb.atlantaned.space/rounds/106869/map
It's still possible, but the mixes are less known and not widely spread (yet).

**Comment by optimumtact** [comment]
maybe we can just wait

**Comment by GuyonBroadway** [comment]
Adding a half modifier due to half volume is kinda reduntant as atmoscode already does that, it's just that bombcode lets you reach the cap absurdly easily.

**Comment by pigeonsk** [comment]
@GuyonBroadway This is the problem, ideally the max cap doesn't exist in the first place and explosions are governed purely by atmoscode instead of artificial constraints. But we live in a society and server culture where bomb mixes reaching the maxcap is the expected norm and Toxins research handsomely rewards RnD points for going above and beyond the maxcap.

Certain added gases (read: tritium) are especially at fault for trivializing the maxcap. I hear Toxins don't even bother with regular plasma & oxygen mixes anymore because tritium mixes are ironically easier to mix and max.

**Comment by GuyonBroadway** [comment]
So this is just a bandaid fix to part of the larger issue that is toxins in general.

Then again the bombcap itself was always a bandaid fix to how trivially easy it was to erase the station. It rather does feel like we need to gut bombcode back to it's core and start again.

**Comment by pigeonsk** [comment]
@optimumtact The cat's already out of the bag. No matter how clever or secretive the method, a single person should not be able to destroy the _entire_ station from space, especially in such a controlled manner, and leaving virtually no survivors except himself by repeatedly bombing escape and the shuttle with a portable air pump and a bag full of tanks.

If you really dislike this solution I'd be happy to open a PR disabling single tank explosions entirely.

**Comment by GuyonBroadway** [comment]
I did like the idea that singletanks rapidly dumped thier gas contents so you could flood a room with freezing cold co2 for some falling down funtimes

**Comment by vuonojenmustaturska** [comment]
Maybe if the gameplay mechanic is only good when people don't know the magic number you've hidden in the code, the gameplay mechanic simply isn't good.

**Comment by pigeonsk** [comment]
@vuonojenmustaturska What magic number are you exactly referring to?

**Comment by ExcessiveUseOfCobblestone** [comment]
All gasses should be based around the 20dev maxcap, being able to get 100+ devrange is sooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo silly

**Comment by Barhandar** [comment]
The real solution is to remove tritium's delayed explosions. Make it so you have _very_ little time to throw it like a grenade and GTFO, or it explodes and erases you from existence, like how plasma-oxy singletanks were.

**Comment by optimumtact** [comment]
im open to someone reworking the bomb dev scale to go from zero -> 20 dev max, with that requiring the perfect mix

**Comment by pigeonsk** [comment]
Power roughly equivalent to d(V*P)/dt, and the code bases explosions of off dP/dt. The "perfect mix" would be an infinite dP/dt, and as such the only scaling equation that can handle infinity inputs would be C(1-e^-(x/k)), with C = 20. [This isn't functionally different from the already existing max cap.](https://www.wolframalpha.com/input/?i=20*(1-e%5E(-x))+from+x%3D0+to+5)

So you have the same problems you do with the max cap with the scaling solution.

**Comment by GuyonBroadway** [comment]
@optimumtact

So what you are asking is to make bombs harder but can make a bigger hole if you manage it? I can get behind that, but it would be nice if toxins had a use that wasn't explicitly traitorous.

**Comment by optimumtact** [comment]
no im saying make it actually hard to reach the maxcap limit we have

**Comment by pigeonsk** [comment]
You can already do that by increasing TANK_FRAGMENT_SCALE

**Comment by optimumtact** [comment]
sure, although I would prefer making it harder via adding more recipe components though

**Comment by Jalleo** [comment]
https://github.com/tgstation/tgstation/pull/43823#issuecomment-489536881
This is the best method. It is the only method to make this shit actually not exponential.

**Comment by pigeonsk** [comment]
@Jalleo tritium bombs are well past 100dev and would still maxcap 20dev. Single tanks would be slightly reduced but still have more explosive power in that solution than this one.

**Comment by optimumtact** [comment]
The best solution I think is to nerf tank fragment scale so reaching maxcap is just hard

**Pull request closed without merging**
