### PR TITLE
Add tgui license/asset licenses

### PR DESCRIPTION
**Pull request by neersighted**
Thanks to @YotaXP for CC licensing his syndi logo

Clarifies the licensing status of tgui (the clientside, which is all original code from me/contributors).

As the serverside is a fork of NanoUI, it remains AGPL.

Possible because I wholely own almost all of tgui.
Please merge only if okay with @tkdrg and @AnturK.
MIT is compatible with AGPL; tgui is separately licensed as it is a subproject potentially useful in other codebases/other games.

### CODE REVIEW

**Comment by Jordie0608** [comment]
May want to add this to the end of readme.md as well

**Comment by Chnkr** [comment]
\o/ yessssssssssssssssssss

**Comment by tkdrg** [comment]
Yeah sure I don't really care my contributions to this are like 6 lines total eitjet way.

**Comment by AnturK** [comment]
Sure, go ahead.

**Pull request merged**
