### PR TITLE
uncapitalizes families game mode

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

its now uncapitalized like every other mode so it doesnt stand out when the round starts and it shows possible gamemodes

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:

Rename the other gamemodes to be capitalized instead.

**Comment by Qustinnus** [comment]
why goof

**Comment by Iamgoofball** [comment]
It looks better captialized.

**Comment by optimumtact** [comment]
They should all be capitalised yes, that's just basic grammar.

**Pull request closed without merging**
