### PR TITLE
Adds Fix Air verb for admins

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Adds a Fix Air verb for admins to quickly reset the air in a radius to what its default composition would be. It's used by right-clicking the floor and entering a number to be used as a radius. All credit goes to nichlas0010 for coding it, and to Flatgub for porting it to AuStation.

## Why It's Good For The Game

It provides a much faster and simpler way to clean an area's atmos than the usage of buildmode > mapgen. Most common uses are for when a nonantag "accidentally" leaks plasma/superheated gas into the air, when a sillymin breaks atmos in an area, or when a hallway scrubber was mysteriously set to siphon an hour ago.
Buildmode is also cumbersome, contrary to the beliefs of _some_ 
image

## Changelog
:cl:
add: Ported the Fix Air verb from Yogstation. Admins can use it to quickly reset an area's atmos to its default composition.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Right click verbs are a taboo

**Comment by KomradeSpectre** [comment]
As a person that was on Yog for a while, I can tell you they have a slew of really good ideas mixed into really messy code. Thumbs up for this QoL.

**Comment by optimumtact** [comment]
This is already a thing in the build mode area gen

**Comment by optimumtact** [comment]
you could at least share the code between the two

**Comment by Dawson1917** [comment]
> 
> 
> This is already a thing in the build mode area gen

It's much slower and clunkier through buildmode IMO. Always prefer the verb

**Pull request merged**
