### PR TITLE
Make the BOH warning slightly more helpful

### PR DESCRIPTION
**Pull request by duncathan**
https://tgstation13.org/phpBB/viewtopic.php?f=7&t=6277&view=unread#p164590

let it be known that the coders care about admin concerns

### CODE REVIEW

**Comment by Supermichael777** [comment]
still too vague to be honest the dnd reference is lost on the pubbies

**Comment by duncathan** [comment]
I suppose. I wanted to avoid outright saying "this will spawn a singularity" but if people want me to I'm happy to accommodate.

**Comment by TrustyGun** [comment]
I mean, if they go ahead with it after being explicitly told that this will have dire consequences, they probably should be banned in the first place.

You could always add "to the station" on the end of it to make it even more clear.

**Comment by Shapsy** [comment]
I will gladly ban anyone who sees this text and puts two BoH's together and then claims ignorance, this looks fine to me :+1:

**Comment by duncathan** [comment]
There, now there's no way someone can read that and think it's fine to do as a non-antag.

**Comment by hornygranny** [comment]
:+1:

**Comment by optimumtact** [comment]
You know we could just make it create a gimped singularity that only lasts a few ticks or something instead of just making a weird and ugly alert.

**Comment by AdamElTablawy** [comment]
No, we can't, because that's fucking dumb, optimum.

**Comment by optimumtact** [comment]
It's better than a fucking immersion breaking popup that messes your screen with it's ugly boxyness

**Pull request merged**
