### PR TITLE
Rust-Rework (DRAFT)

### PR DESCRIPTION
**Pull request by EnterTheJake**
## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Vect0r2** [comment]
Could we have a description of what this does?

**Comment by Jacquerel** [comment]
Did you forget to write the PR before posting it?

**Comment by Xander3359** [comment]
> Did you forget to write the PR before posting it? I would usually assume "oh they clicked post by accident" but that was 30 minutes ago.

I had them post it as draft because I had to pull the code to show them how to fix it.

**Comment by EnterTheJake** [comment]
> Did you forget to write the PR before posting it? I would usually assume "oh they clicked post by accident" but that was 30 minutes ago.

yeah sorry i wanted to pass the code to xander to help me fix a few things.

**Comment by Jacquerel** [comment]
> > Did you forget to write the PR before posting it? I would usually assume "oh they clicked post by accident" but that was 30 minutes ago.
> 
> yeah sorry i wanted to pass the code to xander to help me fix a few things.

You don't need to open a PR to send someone a branch, just link them to the branch on your fork.
I'm going to close this, reopen it when it is ready for PR 👍

**Pull request closed without merging**
