### PR TITLE
Adds the new Self-Destruct Mechanism to the vault

### PR DESCRIPTION
**Pull request by TheVekter**
*Adds @Dorsisdwarf's new Nuclear Self-Destruct Mechanism (from #7685) to the vault.
- Made a few small edits to the vault. Lights are brighter in there now and the tiles around the nuke have been updated to fit more in-line with the feel of a self-destruct mechanism.
- Tiles around nuke actually change when it's armed. Gif soon.

### CODE REVIEW

**Comment by ike709** [comment]
would nuke again/10

**Comment by TheVekter** [comment]
I left the fucking disk in the vault like an idiot

**Comment by ike709** [comment]
nice

**Comment by phil235** [comment]
:+1:

**Comment by Mandurrrh** [comment]
:+1:

**Comment by Dorsisdwarf** [comment]
Floor tile pulsing looks real good, :+1:

**Comment by francinum** [comment]
Would look better if the Vault was extended north a tile, just looks odd with the 3X3 against a wall.

**Comment by dannno** [comment]
eh, it doesn't really look odd at all imo.

**Comment by Steelpoint** [comment]
Looks good :+1:

**Comment by TheVekter** [comment]
Thank you sir

**Comment by Metacide** [comment]
Very nice, will add to MetaStation as soon as I can. :+1:

**Pull request merged**
