### PR TITLE
Balances some megafauna exports and adds some new ones

### PR DESCRIPTION
**Pull request by jughu**
I was honestly drunk when adding the first ones so im adding these from a more thought process

:cl: Improvedname
tweak: adds a few new exports
balance: balances a few prices
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Ausops** [comment]
It takes a lot more effort to part with megafauna or even just tendril drops than mine a little over 100 plasma. It's also very easy to do the latter.

**Comment by 81Denton** [comment]
No sane miner would sell 99% of all lavaland loot. I doubt the sale price has ever impacted a round tbh.

**Comment by Armhulen** [comment]
NOW YOU WILL FEEL MY PAIN!

**Comment by FantasticFwoosh** [comment]
Research it (needs coder input), use it or sell it @81Denton else its just decorative trash for the curator to hoard.

**Comment by jughu** [comment]
yes but wasnt the idea to move away from cargo selling everything ore wise atleast friendly miners can contribute their useless thrash they dont want :) or well doubles...

**Comment by KorPhaeron** [comment]
>You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by praisenarsie** [comment]
harmless pr closed because of gbp, shameful

**Comment by KorPhaeron** [comment]
It's harmless and our codebase can live with or without it, so what better time to enforce the rules?

**Comment by jughu** [comment]
@KorPhaeron can i atleast add the crusher trophies ones then

**Pull request closed without merging**
