### PR TITLE
Icebox Murals: AI Upload and RD Office

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Ignore branch name, I decided there was no way to improve upon the box bridge's design without a complete redo, which would take away it's charm.

Redoes the Icebox upload slightly. Adds murals to the upload and RD's office. Also compresses the tile decals on the bridge.

The Upload, based on the matrix waterfall effect:
image

The RD's Office, based on Conway's the game of life:
image

## Why It's Good For The Game
Murals are fun ways to implement art into spaces, whether they commune something or are just there to look nice. It's weird we don't have any in-game already.

## Changelog

:cl:
add: On Icebox, The RD's office and the AI's upload have received murals.
balance: That one table in the middle of the Icebox upload is gone. Yes, this is a balance change.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
That diff scares me, what the fuck

**Comment by san7890** [comment]
Might be nice to have a fluff note/explanation mapped in so people can appreciate it and not think it's just "ugly". Granted, they might still think that irregardless, but at least you can point them towards a good trailhead.

**Comment by unit0016** [comment]
> Might be nice to have a fluff note/explanation mapped in so people can appreciate it and not think it's just "ugly". Granted, they might still think that irregardless, but at least you can point them towards a good trailhead.

Plaque in the RD's office could be cute to explain that. 
As for the upload, uhh. Honestly, dunno how I could explain that one.

**Comment by unit0016** [comment]
Tried that out, liking it. I have a dumb idea for how to make the upload land.

**Comment by unit0016** [comment]
I've added one iron pill and hid it in plain sight in the upload. It's blue.
That's the joke.

This PR is dumb, but it's the fun kinda dumb.

**Comment by notfrying1pans** [comment]
just a side-note, icebox was forked from box before a bridge change was made, meaning it never showed up in box 
#50315

**Comment by unit0016** [comment]
For the record, If we get turf decals for the (16x16 smooshed into 32x32 metatiles) tiles, I'd like to redo this with those.

**Pull request merged**
