### PR TITLE
Removes the supermatter shuttle

### PR DESCRIPTION
**Pull request by Niknakflak**
This shuttle is incredibly lethal.  For a meme shuttle, people always get dusted and irradiated before they can even get in a rad suit.  This was discussed in coderbus in-dephtly before and @KorPhaeron even agreed with it's removal at the time.

### CODE REVIEW

**Comment by InsaneHyena** [comment]
Fun removal. It can only spawn due to adminfuckery anyway.

**Comment by Niknakflak** [comment]
Adminfuckery shouldn't be instant death

**Comment by coiax** [comment]
I've seen people survive it before, and it has a large fan following.

**Comment by Niknakflak** [comment]
and?

**Comment by Dorsisdwarf** [comment]
I thought you already made this PR

**Comment by Niknakflak** [comment]
That was removing lots of shuttles, this is removing only this one, the only one that other agreed actually should be removed.

**Comment by kilkun** [comment]
>adminfuckery shouldn't be instant death

ur gonna have a lot more to remove than just a shuttle then, lad

**Comment by jughu** [comment]
Supermatter shuttle is the perfect prize for murderboners

**Comment by optimumtact** [comment]
Uhm, so don't use it then?

**Comment by as334** [comment]
It's a good thing it's entirely admin's choice to use the shuttle, and not the default one or randomly selected.

**Pull request closed without merging**
