### PR TITLE
Revert "Revert "[s] Revert "Revert "Improves bee lore""""

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#29986

>self merging

### CODE REVIEW

**Comment by RemieRichards** [comment]
Fite me robot

**Comment by tgstation-server** [comment]
self merging your own pr is bad

**Comment by RemieRichards** [comment]
>Fite me robot

**Comment by lzimann** [comment]
so is going with this fucking stupid revert chain, everyone involved should be embarrassed

**Pull request merged**
