### PR TITLE
Fixes backpack violence

### LINKED ISSUE #22121: Attempting to put an item into your backpack will cause you to hit the backpack with the item
Probably works with belts, webbing, etc. as well

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
fix: The internal rage of the crew has been suppressed, and they will no longer attack their own backpacks when opening them.
/:cl:

Fixes #22121

### CODE REVIEW

**Comment by kevinz000** [comment]
This affects to all things that insert, including shotguns and shells, plox fix ty fam

**Comment by HankMoodyExperience** [comment]
fucking merge this already christ fuck sick of breaking my toolbelts, boxes and backpacks

**Comment by PKPenguin321** [comment]
Can be temporarily worked around by opening your backpack with an empty hand, holding the object you wanna put away, and using the equip hotkey (E or Ctrl+E)

**Comment by HankMoodyExperience** [comment]
pkpenguin this grey shit is trained to fuck your mouth

**Comment by PKPenguin321** [comment]
Thanks

**Comment by optimumtact** [comment]
Please dont' copy paste the proc, make it a function and call it from both obj/item attackby and obj attackby

**Comment by XDTM** [comment]
@optimumtact Done

**Comment by coiax** [comment]
BUILD FAILED, FIX IT, PEOPLE ON SERVERS ARE WHINING IN OOC A LOT

**Comment by XDTM** [comment]
SHIT

**Comment by XDTM** [comment]
go travis go

**Pull request merged**
