### PR TITLE
Hallucinatory Anomalies now produce hallucinatory decoys of itself, and hit a wider area

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

This "buffs" the hallucinatory anomaly by giving it a bit more impact and flair. This affects both the detonate effect and what happens when one initially spawns.

When a hallucinatory anomaly spawns, it will spawn surrounded by "decoy" hallucination anomalies -- Illusions meant to distract you from the real one. The idea is that these are not actually there, and that they are the result of reality getting muddy in proximity to the anomaly. Scanning one of these will provide a message, either of nothing happening or a minor hallucination as your character suffers from the real anomaly's effects.

Using an anomaly neutralizer on a decoy will do nothing. There's nothing to neutralize, because nothing is there. You're losing your grip on reality.

Now, the detonate effect will affect people at a wider radius, through walls. This is done with a second helper different from `visible_hallucination_pulse()`, which does affect the blind and ignores walls, `hallucination_pulse()`.
## Why It's Good For The Game

Hallucinatory anomalies are easily the most underwhelming and understated anomaly in the group. They have the impact of a dry fart on a round, rarely affecting anyone and vanishing without anyone noticing or caring.

It makes little sense for the detonate effect to impact only those who can see it. Anyone with a pulse can make the connection between the "hallucination anomaly" vanishing and Bubblegum bodyslamming them less than a second later. By affecting those out of sight, in a wider range, there's a higher chance the detonation will not only catch people off guard, but lead to more chaos on comms.

As for the illusory decoy anomalies, it was just a neat idea I had to differentiate how people typically deal with them. It makes for a more trippy experience for whoever has to deal with them, and adds confusion (which is the whole shtick with hallucinations -- confusion).

So, overall, more snazziness and personality, and more of an impact when left alone.
## Changelog
:cl: Rhials
balance: Hallucinatory anomalies now have a wider range, and will spawn hallucinatory decoys of itself to mislead you.
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
Having it make hallucinatory fakes of itself is pretty funny and on-theme, I like it.

**Comment by Jacquerel** [comment]
I'll be honest I thought the detonate effect already globally effected every player in the game, I am surprised to learn that it was so limited.

**Comment by Time-Green** [comment]
Do borgs also see the decoy?

**Comment by Rhials** [comment]
> Do borgs also see the decoy?

Yes.

**Comment by moocowswag** [comment]
Would be a welcome buff to reactive hallucination armor if anyone gets around to it after this pr.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
