### PR TITLE
Removes all nosmooth walls

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

These are basically impossible to implement with wallening, and I can't bounce map edits back and forth. Plus honestly they're a bit silly, and barely used

### CODE REVIEW

**Comment by Rex9001** [comment]
I think you are missing a few maps that use these

**Comment by LemonInTheDark** [comment]
which ones?

**Review by ZephyrTFA — APPROVED** [review]
nothing of value was lost

**Comment by AdipemDragon** [comment]
mmmno, plenty of value was lost, yes it was something that wasn't availible to anyone building manually but Still. sucks to have it go cause of the wallening, fuck anything on inside corners I guess

**Comment by Jacquerel** [comment]
This will chiefly make several shuttles uglier

**Comment by ArcaneMusic** [comment]
> mmmno, plenty of value was lost, yes it was something that wasn't availible to anyone building manually but Still. sucks to have it go cause of the wallening, fuck anything on inside corners I guess

3 walls over 2 maps

**Comment by Rex9001** [comment]
> which ones?

I believe these were present on the faceoff? At least the plastitanium version. I might be wrong

**Comment by AdipemDragon** [comment]
> 3 walls over 2 maps

yeah, there's like none pre-existing ones but it sure is useful when admin-building compact stuff on the fly. 
at least the fake walls still act like them before being screwdrivered in proper

**Comment by LemonInTheDark** [comment]
> > 3 walls over 2 maps
> 
> yeah, there's like none pre-existing ones but it sure is useful when admin-building compact stuff on the fly. at least the fake walls still act like them before being screwdrivered in proper

It's kinda unclear to me what your usecase here is, is it the see through edges thing?

**Comment by EEASAS** [comment]
what is a nosmooth wall exactly?

**Comment by LemonInTheDark** [comment]
this question is answered by the code I removed.
In short tho, walls that do not use smoothing, and instead display only the "wall" sprite which is meant to look sorta like a shuttle wall with no connections

**Comment by AdipemDragon** [comment]
> mmmno, plenty of value was lost...
> ...walls that ... display only the "wall" sprite which is meant to look sorta like a shuttle wall with no connections

I'd like to rectify my comment from 2 days ago, when i was still sleepily waking up and reading the upcoming PR's like the morning news. I genuinely fully thought you meant the nodiagonal ones

**Pull request merged**
