### PR TITLE
Remove absurdly old libmysql.dll from the repo

### PR DESCRIPTION
**Pull request by optimumtact**
This thing has benefited from none of the improved code or security patches made in the last like 3 years and is probably highly dangerous to use.

### CODE REVIEW

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
Because of how the server updater works, removing this would remove mysql support on sybil/bagil

Update this or bust.

**Comment by optimumtact** [comment]
good god

**Comment by Jordie0608** [comment]
Isn't this required for mysql to work with the code?

**Comment by optimumtact** [comment]
Yes but you shouldn't be using a version that is three years old

**Comment by optimumtact** [comment]
oh shit it's over 6 years old, I miscalculated.

**Pull request closed without merging**
