### PR TITLE
Adds some lacking changelogs

### PR DESCRIPTION
**Pull request by Jordie0608**
Made some changelog entries for recent merged prs that should've had them from the past 7 days; basically anything that'd noticeably affect players.

Provided someone doesn't do it before me, I'll compile these to the master log once I figure out how to do that.

### CODE REVIEW

**Comment by Incoming5643** [comment]
the lack of a changelog for mine was an intentional choice, as a more active meta-buster.

**Comment by Jordie0608** [comment]
Anyone who looks at github, asks in ooc or spends a round with the shuttle called during rev/blob/etc. would be able to find out.

**Comment by Deantwo** [comment]
Should maybe hold back on @steelpoint's changes till after #7509.

**Comment by Razharas** [comment]
Welp changelog pr no need to wait 24 hours

**Pull request merged**
