### PR TITLE
Removes hygiene

### PR DESCRIPTION
**Pull request by ghost**
yeah I realized, Hygiene is not really something we need on TGstation so I made sure it is no longer something we have to worry about.

### CODE REVIEW

**Comment by habader** [comment]
nobody likes hygiene and everyone complains about it the moment its brought up

how the fuck is this an april fools?

**Comment by SpaceManiac** [comment]
the PR's contents mismatch its title

**Comment by habader** [comment]
gah

**Comment by redmoogle** [comment]
N I C E almost got fooled

**Comment by ondrej008** [comment]
Merge this, now.

**Comment by PKPenguin321** [comment]
back at it again

**Comment by Shadowflame909** [comment]
not gonna like it got a good chuckle out of me when I read the commits and realized that this would only increase the miasma and showering problem

**Pull request closed without merging**
