### PR TITLE
Internal radio implant

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Adds an internal radio implant, allowing the use of the radio if
you expect to have your headset removed. Or if you don't have any ears
or hands. It can be purchased for 4 TC from any Syndicate uplink.
add: Nuke ops now buy special "syndicate intelligence potions" that automatically
insert an internal radio implant when used successfully. Cayenne can now
participate in your high level discussions.
/:cl:

Modifies saycode at the /mob/living/proc/radio level to check for a
radio implant, and talk into it if the implant is present and the radio
is on. This takes priority over an ear headset for humans, so you'll
have to turn off the internal radio to use a headset.

Why? Well, the main usecase I have in mind is giving it to Cayenne, so
the loyal nuke op fish can participate in all those delightful planning
conversations. But I'll also make it purchasable by regular traitors,
which means that their secret syndicate communications will only be
revealed by intrusive surgery.

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
JUST MAKE RADIOS A COMPONENT ALREADY

**Comment by JJRcop** [comment]
Should be able to add or remove keys from the implant like normal radios.

**Comment by kevinz000** [comment]
@MoreRobustThanYou you do it

**Comment by MoreRobustThanYou** [comment]
@kevinz000 no i'm half asleep

**Comment by The-clown-known-as-Pepe** [comment]
@kevinz000 you do it 🤗

**Comment by arsserpentarium** [comment]
Wait. Isn't radio already a component?

**Comment by Cyberboss** [comment]
Radios are a very obvious candidate for componentization, someone just has to do this.

**Comment by arsserpentarium** [comment]
You mean with telecomms?

**Comment by arsserpentarium** [comment]
If someone will tell me,how tcomms work,I'd be grateful.

**Comment by ExcessiveUseOfCobblestone** [comment]
> the main usecase I have in mind is giving it to Cayenne, so
the loyal nuke op fish can participate in all those delightful planning
conversations.

If you want an actual unit to be a part of the team you buy an actual unit and not the fishies. The reason you buy fishies is for memes, they aren't meant to be a serious component to the team.

A much less balance-intrusive suggestion would be to set a directive on the potion by active handing it that prints in the mobs memory and login text so they know what to do if you're afraid of them buggering off.

> But I'll also make it purchasable by regular traitors,
which means that their secret syndicate communications will only be
revealed by intrusive surgery.

or you could just keep it as is? Traitors certainly don't need a near-hivemind chat, they already have codespeak. If you are afraid of getting caught then work alone.

I am not a fan of this pr, at least on the basis of what slopes it wants to put space lube on.

**Comment by SgtxRootbeer** [comment]
Could this also go to medical/rnd as a way for people to get protection from flashbangs (by using in Conjunction with earmuffs to make a ghetto Bowman headset)?

**Comment by FantasticFwoosh** [comment]
## Obvious conspiracy to save space for kitty ears.

- **Real talk** - Expect security to open you up looking for a implant if you start muttering to yourself in italics within your cell after your earpiece has already been confiscated.

**Comment by coiax** [comment]
@ExcessiveUseOfCobblestone actually Cayenne is more useful than just for memes. A stun proof simple mob that has unlimited space movement, the ability to door smash, and very little to distract it can be surprisingly useful.

Also, either the fish is a meme, and thus the radio won't help, or it's a serious part of the team, in which case the radio DOES help.

It's not a hivemind, it's just a radio, which they can't use when unconscious, which they lose if they're killed and cloned, and can be extracted surgically if security suspect them of having illegal implants.

**Pull request merged**
