### PR TITLE
Fixes some antags missing from roundend report

### LINKED ISSUE #34098: Traitors don't always show up in end report
Issue reported from Round ID: 81371 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

[Round ID]: # 81371

[Testmerges]: #34005 #34061 

[Reproduction]: # Play entire round as a traitor. Was Threads-The-Needle, I had to get some research and escape alive. At the end round panel, I wasn't there. No idea how to reproduce

### PR DESCRIPTION
**Pull request by AnturK**
This is just a hotfix, proper fix pending. Uplink logs need to be rewritten from ground up. They're linked through key not mind, not working properly and get deleted along the uplink.
  
Fixes #34098

### CODE REVIEW

**Comment by Cyberboss** [comment]
>get deleted along the uplink

I swear i specifically made this not happen

**Comment by Cyberboss** [comment]
Like there's this proc, which is meant to merge purchase logs when keys somehow get more than one uplink

https://github.com/tgstation/tgstation/blob/b2b3f7f7c0cbb357a5452bc6f31e3f8ee2b7d9ab/code/modules/uplink/uplink_purchase_log.dm#L25

**Comment by AnturK** [comment]
Was that before or after kevinz made them components.

**Comment by Cyberboss** [comment]
kevinz actually based off my code so it's mostly mine

**Pull request merged**
