### PR TITLE
Removes "Code Improvement" and "Atmospherics" being categories

### PR DESCRIPTION
**Pull request by Iamgoofball**
1. Code Improvement can just be rolled into Refactoring.
2. Atmospherics isn't super complex anymore, anyone with basic math and physics knowledge can grasp it, why does it get 4 bonus points over everything else?

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
1. refactor is for more BIG BOY code improvements, normal code improvement just removes/cleans code
2. prove it by fixing some of the atmospherics issues

**Comment by Cyberboss** [comment]
The idea is to get people to do SOMETHING positive for the code base, code improvement is staying because that's the easiest way to do that and there's a FUCK TON of code that needs improving. PR balance doesn't actually mean anything unless it goes negative.

**Comment by Iamgoofball** [comment]
Just give people Refactor points instead of Code Improvement points.

**Comment by CPTANT** [comment]
I think stupid fights like this are exactly the reason why PR balance was a bad idea.

**Comment by RemieRichards** [comment]
the only bad idea here is goof.

**Comment by Cyberboss** [comment]
This is not a refactor: #30670
This is a refactor: #30462 

It's really not anything to bikeshed over

**Comment by optimumtact** [comment]
go away goof, you're not welcome to touch this file, only maintainers are

**Comment by pubby** [comment]
@optimumtact 

reopen this honestly

I can tell maintainers are being hesitant towards adding the atmos tag because they don't want to hand out easy points. But that just makes the tag arbitrary and less useful. I'd rather have PRs tagged and easy to search than drama and decisions made over useless points.

**Comment by optimumtact** [comment]
None of you are welcome to touch that file period.

**Pull request closed without merging**
