### PR TITLE
Updates to envirosuit's virus protection values.

### LINKED ISSUE #61423: Viruses that spread via touch can be spread through a full Plasmaman Envirosuit
## Reproduction:

Playing as a plasmaman virologist, and I gave myself an Inorganic Biology virus allowing the effects of the virus to effect me. Transmission stat was at 8, allowing the virus to spread via touch.

Upon grabbing a monkey, I noticed via the Health HUD that the monkey was instantly infected, despite my plasmaman wearing a full envirosuit (helmet, gloves, suit) which is supposedly fully sealed as to not cause a fire/leak of plasma from the suit. So how exactly does this make sense?

I haven't played around with touch viruses as a human to notice this, but either this is just an issue regarding viral protection from plasmamen gear, or maybe this issue affects every instance with protective clothing. Dunno. I'll either update this issue or make a new one if I find out.

### PR DESCRIPTION
**Pull request by remuluson2**
## About The Pull Request
Fixes #61423
Updated plasmaman clothing to provide protection from infection equal to medical clothing.

## Why It's Good For The Game
Consistency mainly. Also now the plasmaman clothing is better than being naked.

## Changelog

:cl:
add: Added antivirus-protection to plasmaman suits and all its variants(the entire set).
/:cl:

### CODE REVIEW

**Comment by remuluson2** [comment]
Fixes #61423

**Comment by ATH1909** [comment]
relevant: https://github.com/tgstation/tgstation/pull/61691

**Comment by ATH1909** [comment]
I can see why you'd want to tweak the values for the undersuit version of the envirosuit, but why should a plasmaman space suit protect you from viruses less than a normal space suit would?

**Comment by remuluson2** [comment]
because its a roundstart item that every plasmaman has access to. It didn't protect too well without any protection on head and other parts of the outfit but with new values it would mean that you just dont get sick even more than the medical staff.

**Comment by SgtHunk** [comment]
> because its a roundstart item that every plasmaman has access to. It didn't protect too well without any protection on head and other parts of the outfit but with new values it would mean that you just dont get sick even more than the medical staff.

no its not
the plasma eva suit is cargo only

**Comment by remuluson2** [comment]
wait what. oh shoot hold on. gonna fix this crap

**Comment by remuluson2** [comment]
> 
> 
> > because its a roundstart item that every plasmaman has access to. It didn't protect too well without any protection on head and other parts of the outfit but with new values it would mean that you just dont get sick even more than the medical staff.
> 
> no its not the plasma eva suit is cargo only

yeah, yeah. I had no clue there was a eva version for them.

**Pull request merged**
