### PR TITLE
Ports ZAS

### PR DESCRIPTION
**Pull request by MrsTonedOne**
When we activate a new turf while spreading, we just avg out the contents of all connected active turfs.

:^)

### CODE REVIEW

**Comment by duncathan** [comment]
You think he's kidding but this actually works

**Comment by KazeEspada** [comment]
Is it as fast as ZAS?

**Comment by GunHog** [comment]
Does not seem to work for me. Gas spread appears normal.

**Comment by MrStonedOne** [comment]
I'm only checking to see if this has merge conflicts after 1 year.

**Comment by MrStonedOne** [comment]
it does

**Comment by Cyberboss** [comment]
It's be really easy to implement this today, but I'm not seeing what the performance increase is?

**Comment by MrStonedOne** [comment]
Basically, excited groups track any set of connected atmos tiles that are active, the command that calls basically equalizes the entire group out on spread, so shit is active for far less.

**Comment by MrStonedOne** [comment]
But this was also an april fools joke, it's rather lame.

**Comment by jughu** [comment]
22 days too late mso

**Pull request closed without merging**
