### PR TITLE
Payday Guns Bundle (Adds gloves, clown mask, suit to the guns syndicate bundle)

### PR DESCRIPTION
**Pull request by drynwyn**
Adds nitrile gloves, clown mask, and a suit to the Guns bundle.

As suggested by Balut on the fora.
image

### CODE REVIEW

**Comment by TZK13** [comment]
>No surgical drill.

**Comment by drynwyn** [comment]
The surgical drill is actually a useful item though, it has a high melee force. Also a Mining Drill would be closer to the drill.

**Comment by Steelpoint** [comment]
> Not making a drill that takes 5 minutes to open the vault's safe

Pretty neat overall :+1:

**Comment by Miauw62** [comment]
neat :+1:

**Comment by drynwyn** [comment]
> Not making a drill that takes 5 minutes to open the vault's safe
Next project: Add this functionality to mining drills.

**Comment by dannno** [comment]
You could make it part of some assembly to create a battery-powered stationary drill which takes a minute or two to pop open doors/safes.

**Comment by ChangLing** [comment]
So basically the pAI's doorjack, but on a drill?

**Comment by dannno** [comment]
I guess.

**Pull request merged**
