### PR TITLE
Fixes borg names.

### LINKED ISSUE #38710: Borg name problem part 2, Round start name fixed, the borgs created by crew have the name fucked....
Issue reported from  Round ID: 89997 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Testmerges]: #37922: '[WIP] [Near Completion] Nanites 2' by XDTM at commit 6c75ffbb4b

So the round start Borg name was fixed, but now the borgs created by crew have the default-cyborg-xxx name and not default of the preferences, and even after choosing module. 
[Reproduction]: just be create a Borg put a brain in it without changing it's name and it will get default-cyborg-xxx

Unless is intended

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #38710

Personally i prefer nameless borg masses but bug is a bug.

Also renamed `rename_self` to `apply_pref_name` the old name wasn't really representative of what it does now.

### CODE REVIEW

**Comment by zaracka** [comment]
I like using a default name sometimes, but there's no obvious way to revert the preference to a blank state. Can you fix that by somehow incorporating the option?

**Comment by AnturK** [comment]
Sure, i'll take a look at it in a moment.

**Comment by CitrusGender** [comment]
opps, my bad.

Thought the mob got pushed through that proc for some reason.

**Comment by AnturK** [comment]
Added way to set to default naming scheme, it's bit ugly i'll have to clean the default name retrieval later.

**Pull request merged**
