### PR TITLE
Watchlist alert now includes a timestamp of when it was created

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Requested by a couple of admins to help deal with ancient watchlist entries just spamming us forever

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
😏

**Comment by lzimann** [comment]
what if we made watchlist entries automatically expire? around 6 months should be enough

**Comment by vuonojenmustaturska** [comment]
This is something that can be done now, automatic expiration can be done in a follow-up PR

**Comment by Jordie0608** [comment]
Well this is fine but the same timestamp has always been in the notes panel.

**Pull request merged**
