### PR TITLE
Head Beating no longer deconvert gangsters

### PR DESCRIPTION
**Pull request by Ikarrus**
I've seen enough rounds where security just goes full Hitler and beats everyone, gangster or no, to death and just leaves their corpse in the brig afterwards.

Gangs have implant breakers and security still has implants. Head beatings are no longer needed and just encourages shitcurity.

### CODE REVIEW

**Comment by kevinz000** [comment]
Sometimes it's not for deconversion, rather to end the life of gangsters when there is too many
I doubt it will change security's bodycount every time it gets to the point where they don't have implants

**Comment by Ikarrus** [comment]
It was better before when the head beating meta hasn't settled. Now that it has it's pretty awful to watch.

**Comment by SconesC** [comment]
It's rarely for deconversion

It's because the gamemode is team deathmatch

**Comment by Actionb** [comment]
Using two loyalty implants to keep some guy visibly on your (security's) side is very expensive. Most ex-gangsters that have simply been deconverted via implant, will just go back to their former gang and request reconversion.
If anything, security will kill even more people due to the lack of implants.

**Comment by Firecage** [comment]
Action kinda has a point. Sec runs outoff implants faster, and what makes it worse, is that it is basically two gangs at the same time.

**Comment by Shapsy** [comment]
so instead of security beating people's heads in to try and deconvert them, they'll just beat their heads in to kill them because they don't have enough implants to deconvert/implant everyone?

**Comment by Ikarrus** [comment]
That's what they already do though. The difference would be they won't be able to use it as an excuse.

**Comment by SconesC** [comment]
s-security just needs to stop killing people who are shooting up the station and vandlizing it!!!!! gangs dindunuffin!!!!

**Comment by Steelpoint** [comment]
When you have seemingly half the station killing the other half its more effective and time saving to just execute them now and let god sort them out.

Right now its too much trouble, and resource consuming, to deconvert gangsters and throwing them in perma takes even more time to do. When its balls to the wall sec is forced into executions just to survive as there's no viable alternative.

**Comment by Robustin** [comment]
Ikarrus I'm disappointed you aren't listening to the people who actually play security about this.

You bwoinked me during a Gang War yesterday when during a chaotic multi-person arrest, one of the arrestees who had personally attacked me had been deconverted immediately after when one of my officers was using a harmbaton to make the arrest. I didn't notice and proceeded to shake them up some more at the brig and I suspect they succumbed (I had just brought them out of crit and they died after 5 or so more thwaks), but I wouldn't have let them go until we got more implants either.

When you brought it up, disgusted by what had happened, I guess you didn't believe me when I said that without beating deconversions I would've just emptied my laser into him on the spot since implants had run dry and they come slowly and inconsistently even on the best of rounds. This isn't a case of where I'd be happy to give someone a 10 minute sentence but decide to beat them to death instead, this is the case of where I'm prepared to perma/execute someone but give them a chance at skullcrack roulette. There is absolutely no way I'm going to let people off easier after this change, anyone who I'm willing to beat into crit as HoS is someone I'm willing perma/execute instead.When you've got 3-4 people sitting in brig waiting for implants and the AI tells you that we dont even have points for another crate yet, either we can use beatings as a release valve to prevent brig from overflowing and sec entering genocide mode, or we just send the order out to laser everyone we catch doing gang shit. 

I can't fathom how you imagine this is going to HELP with the problem you're trying to solve. I don't even think its that much of a problem, if I get caught with a spraycan/gun/whatever during gang war and implants are out, I'm expected perma or execution... why should I (or anyone) be upset if they take one last shot at redeeming your soul and keeping me in the round. It's an act of mercy compared to the treatment confirmed antags usually get from sec. I'll always take a beating with even a small chance of staying in the round over a nice "clean" death that involves being stuck in a perma cell for the rest of the round.

**Comment by Ikarrus** [comment]
I want to give it a try. If it turns out to be awful we can easily reverse it, like I did with implants.

**Comment by Robustin** [comment]
My only issue with that is that if you truly believe that sec murderbone went up when we got an efficient non-lethal way to keep gangsters in the round, what are you going to tell yourself when you watch rounds post-change?

**Comment by Cebasiz** [comment]
eh i think one of the problems with the mode is that the gangs have a very hard time actually engaging with each other. it seems to me like gangs should spend most of their efforts fighting each other rather than sec, and attacking sec should be a generally secondary goal. that way gangsters captured by sec would probably go down, which would allow sec to step away from the final solution style mass execution they currently favor out of necessity.

this change i'm not sure about, i suppose the worst it could do is change nothing.

**Comment by Robustin** [comment]
We've gone there Cebaiz, there's a good consensus that this is as good as Gang War has been.

When security and gangs had no reason to fight each other, the rounds were extremely anti-climatic. Sec had no reason to go around busting balls just for spray cans and so one gang would just snowball in size and suddenly the round ends when enough tags had gone up.

**Comment by Miauw62** [comment]
robustin

**Comment by Core0verload** [comment]
>Also, I drink urine.

@Robustin, did some jerk edited your comment?

**Comment by Core0verload** [comment]
Well, now it's gone.

**Comment by Steelpoint** [comment]
Just in case anyone missed it Miawu posted this hilarious image before he (likely) deleted it.

**Comment by Aranclanos** [comment]
its kinda shitty because its the same text over and over, it would be cool to do some collage of all his autism across a bunch of posts

**Comment by bustygoku** [comment]
Yeah there's so much material to draw from and you copy paste the same message!

**Comment by Kelenius** [comment]
If you have trouble reading that, you must be fucking illiterate.

**Comment by Ikarrus** [comment]
It's called a [poorly edited] joke.

**Comment by Miauw62** [comment]
>effort

**Pull request merged**
