### PR TITLE
turns the AI icon selection menu into a radial

### LINKED ISSUE #41004: green AI sprite is invisible
what it says on the tin

### PR DESCRIPTION
**Pull request by Amelia0010**
Fixes #41004

https://github.com/tgstation/tgstation/pull/40961 except I remade it after https://github.com/tgstation/tgstation/pull/40761

image

:cl: Amelia0010
tweak: the AI icon-selection menu now uses a radial.
/:cl:

Also removes "green" from the global list, since there's no AI display called green, and renames "wierd" to "weird", so it works properly

### CODE REVIEW

**Comment by ShizCalev** [comment]
Oh right, forgot I was going to rename weird to green lol

**Review by Cyberboss — APPROVED** [review]

**Comment by optimumtact** [comment]
yeah how many screens do you have to cycle through?

**Comment by nichlas0010** [comment]
6, I think. There’s 36 options abd 7 on each radial, so round that up from 5.something to 6

**Comment by optimumtact** [comment]
hrmm, can you make the radius bigger to add more options or is the radial system not that flexible?

Ideally I'd want 2/3 max

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
You can do the thing I said to get more options yeah

In all honesty, a menu that worked similar to a radial but was just a densely packed rectangle of options instead of a circle would be much more suited for some things

**Comment by optimumtact** [comment]
@vuonojenmustaturska add a square grid version of this :hugs:

**Comment by SpaceManiac** [comment]
Looks good, feel free to iterate in a later PR if you want

**Pull request merged**
