### PR TITLE
Gives the .38 "slowdown." (Small amounts of stamina damage.)

### PR DESCRIPTION
**Pull request by pireamaineach**
Gives the .38 small amounts of stamina damage, making it slowdown on the first shot. By the time you would get them into stamina crit with the 15 damage a shot they're already in crit from the brute. Note is 15 less half as effective as a disabler.
:cl:
balance: Gives the .38 15 stamina damage.
/:cl:

### CODE REVIEW

**Comment by imsxz** [comment]
reminds me of m1911 from the space ruin which just had stamina damage removed from its bullets because ballistic stuns are cancer

**Comment by pireamaineach** [comment]
By the time this is even a stun you're in crit from the brute.

**Comment by pireamaineach** [comment]
Keep in mind, this is exactly 0.30769230769x the stamina damage that was on old .45.

**Comment by subject217** [comment]
you could make it apply an actual slowdown effect instead

still an unnecessary buff

**Comment by pireamaineach** [comment]
I want the slowdown to stack if you can land many consecutive shots, and be very, very negligible on the first shot.
Stamina damage just works for this.

**Comment by necromanceranne** [comment]
I feel like this is already handled by icebox ammo.

**Comment by HomocidlePancakes** [comment]
Lower the brute damage

**Comment by 4dplanner** [comment]
"Very, very negligible on the first shot"

This just isn't how our slowdown system works. Once you pass the 40 damage threshold it's already significant.

**Comment by GuyonBroadway** [comment]
The .38 is supposed to be for self defence, not "that thing powergamers always try to steal cus it's really good".

It's had a long history of being part of the "magboots, RTA, Spare ID, meth pills" council of the powergamer/muderboner become unbeatable movement.

Removing its stunning effect was a good step, adding it back sounds like a step in the wrong direction.

**Comment by knacker48** [comment]
Its fine for some weapons not to have slowdown. Besides the .38 is suppose to be a self defense weapon isn't it? It should be more lethal then say a normal laser

**Comment by pireamaineach** [comment]
Just ignore that this is half as effective as a disabler and by the time you'd be in stam crit you're already in crit from the brute.
This is not better than a disabler, this is can barely be classified as a stun.

**Comment by pireamaineach** [comment]
Now, I will consider lowering the stamina damage if someone explains how the brute damage threshold works.
If you have 50 brute and 20 stamina damage and that gives you decent slowdown, then I could knock the stamina damage down to 10.

**Comment by pireamaineach** [comment]
Right so as is this actually just makes it slowdown on the first shot, and gives it stronger slowdown on the second.

**Comment by 81Denton** [comment]
Iceblox ammo already covers this by lowering the body temperature of any perps hit by it.

**Comment by PKPenguin321** [comment]
Wasn't the stam damage on this JUST removed, and the brute increased to compensate? Now you're just adding the stam back

**Comment by pireamaineach** [comment]
No, no it wasn't.

**Comment by PKPenguin321** [comment]
I might be thinking of a different gun

**Comment by pireamaineach** [comment]
> I might be thinking of a different gun
> 
> Is .38 not the detective's ammo?

It is but you're still wrong.

**Comment by PKPenguin321** [comment]
No, I'm right: https://github.com/tgstation/tgstation/pull/39891

The stamina damage was explicitly removed so that this gun was a raw "shoot-them-into-crit" type deal, see oranges' comment in that PR

**Comment by pireamaineach** [comment]
> No, I'm right: #39891
> 
> The stamina damage was explicitly removed so that this gun was a raw "shoot-them-into-crit" type deal, see oranges' comment in that PR

You are still very wrong. This is nowhere the same, the old .38 had 50 stamina damage and 60 knockdown.

**Comment by optimumtact** [comment]
they're right and you're wrong

**Comment by ExcessiveUseOfCobblestone** [comment]
aim better or icebox

**Comment by pireamaineach** [comment]
You monster. How could you ask this of me?

**Pull request closed without merging**
