### PR TITLE
Adds a new bar sign, The Lightbulb (take 2)

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Added a new bar sign, The Lightbulb.
/:cl:

Someone in Discord gave me this idea when we were discussing moths, so I added a moth-themed bar sign. It looks like this, though the in-game version is slightly different and animates better. The B also looks different.

The Lightbulb

The square at the top represents a common light fixture, with the blobs of fluttering light being cute fuzzy moffs flying around it.

### CODE REVIEW

**Review by ShizCalev — DISMISSED** [review]

**Comment by nicbn** [comment]
That's a tube not a bulb

**Comment by Xhuis** [comment]
Anything is a bulb with enough squinting.

**Comment by Armhulen** [comment]
THE B

**Comment by Xhuis** [comment]
I wanted to squish down the text and stylize it that way. If you know how to do a better :b: with that style, let me know!

**Comment by Armhulen** [comment]
cmon give it one more pixel he needs it

**Comment by nicbn** [comment]
The lightrulr

**Comment by nicbn** [comment]
The lightrule

**Comment by epochayur** [comment]
you could either just make it 5-blocks high or make it a lower-case for legibility

**Comment by Xhuis** [comment]
Changing the B as per request and suggestions:

**Review by ShizCalev — APPROVED** [review]

**Comment by Armhulen** [comment]
HE FIXED THE B

verr nic

**Comment by Cyberboss** [comment]
Total time is > 24hrs

**Pull request merged**
