### PR TITLE
Adds Gold And Silver To Appropriate Vault Crates On Delta Station

### LINKED ISSUE #23607: delta station gold crate contains no gold
It's called a GOLD CRATE. HAVE GOLD IN IT.

### PR DESCRIPTION
**Pull request by JohnTheDonut**
## **Adds Gold And Silver To Vault Crates On Deltastation**
Adds three bars of gold to the gold crate located in the Vault on Deltastation, This also adds five silver coins to the silver crate this is to make the crate names correspond and match what the crates actually contain. And also follow in accordance and other maps standards with what they have inside their vault crates.

## **Changelog**
:cl: Tofa01
Add: [Delta] Removes space money from gold crate replaces with 3 Gold Bars Gold Wrestling belt is still there.
Add: [Delta] Removes space money from silver crate replaces with 5 Silver Coins.
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
The silver crate usually contains silver coins, and the gold crate usually contains a wrestling belt; look at another map to see what i mean.

**Comment by Tofa01** [comment]
Hm weird how did this fail Travis?

**Comment by Tofa01** [comment]
I see, fixing now.

**Comment by Tofa01** [comment]
Fixed uploaded the commit and updated PR body.

**Pull request merged**
