### PR TITLE
Clockwork manacle sprites

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Fury
add: Added sprites for clockwork manacles.
/:cl:

There are (as of now unused) sprites for regular manacles included as well.

### CODE REVIEW

**Comment by Xhuis** [comment]
You may want to replace the icon in `actions_clockcult.dmi` for Hateful Manacles with that too, since it otherwise probably won't be seen much.

**Comment by WJohn** [comment]
Gud sprites.

**Comment by optimumtact** [comment]
conflicted

**Comment by KorPhaeron** [comment]
Icon conflicts are such a pain

**Comment by Xhuis** [comment]
Once the feature freeze is over, I'll include these in the clockcult patch I'm working on.

**Pull request closed without merging**
