### PR TITLE
Removes lavaland completely

### PR DESCRIPTION
**Pull request by Iamgoofball**
GOING FOR A SUB SIX SECOND RUN can we DO IT YES WE CAN 8======D

### CODE REVIEW

**Comment by PKPenguin321** [comment]
FIRST

**Comment by PKPenguin321** [comment]
FUCKING SHIT FUCK OFF KOR REEEEEEEEEEEE

**Comment by duncathan** [comment]
I almost want to merge it

**Comment by Zilenan91** [comment]
I THINK HE MADE THE WORLD RECORD HERE FOLKS

**Comment by kevinz000** [comment]
merge it merge it

**Comment by Zilenan91** [comment]
IT'S A BIG DAY ON THE /TG/STATION CODEBASE

**Comment by Armhulen** [comment]
TEST MERGE, I NEED TO SEE HOW THIS AFFECTS THINGS

**Comment by Zilenan91** [comment]
IAMGOOFBALL SIR WHAT DO YOU HAVE TO SAY FOR YOURSELF?

**Comment by Bawhoppen** [comment]
goof is still in second place my steak pr holds world title

**Pull request closed without merging**
