### PR TITLE
Removes the mob mouse from maintenance from maps

### PR DESCRIPTION
**Pull request by nicbn**
The mices that are spawned by code aren't affected.

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Nabski89** [comment]
Why?
They exist to fuck up some wires and give the engineers something to do, they're cute, and if a wizard takes mouse shapeshift they help him hide ever so slightly.

**Comment by Cyberboss** [comment]
>The mices that are spawned by code aren't affected.

**Comment by Nabski89** [comment]
Well that's an excellent reason.

**Comment by ACCount12** [comment]
As if engineers don't have anything to do.

**Comment by nicbn** [comment]
I didn't remove the ones from permabrig, should I?

**Comment by Bawhoppen** [comment]
Those are special pets, don't

**Comment by Cyberboss** [comment]
There should be zero mobs on maps. Only spawners

On Nov 29, 2017 6:58 PM, "bawhoppen" <notifications@github.com> wrote:

Those are special pets, don't

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/33179#issuecomment-348037218>,
or mute the thread

**Comment by nicbn** [comment]
Well there actually are a lot of pets on the maps so I'm not sure

**Comment by Cyberboss** [comment]
Do what you can atomically, save the rest for another PR

**Comment by ShizCalev** [comment]
all the monkeys, pets, cows, slimes, crabs, secbots, cockaroaches, mulebots, carp, cows, butterflies, chickens, parrots, cleanbots, lizards, aliens, crabs, bees, bears, skeletons, NPC enemies, ect ect are all mobs directly places on maps.

**Comment by ShizCalev** [comment]
image
>never done

**Comment by CosmicScientist** [comment]
You didn't get rid of Jerry, did you?

**Comment by nicbn** [comment]
No and his name is Tom

**Comment by Bawhoppen** [comment]
@Cyberboss I meant he should make sure to replace them with spawners if he needed to

**Comment by Cyberboss** [comment]
SSsqueak handles mouse spawning, so mice should never be mapped in
nowadays, spawner or no.

**Comment by Bawhoppen** [comment]
But the permabrig one has a special name and desc. Is that covered under it?

**Comment by ExcessiveUseOfCobblestone** [comment]
you are smarter than this baw

**Comment by nicbn** [comment]
Ok I don't need arguments I need an answer
Remove the mouses from permabrig or no?

**Comment by Bawhoppen** [comment]
@ExcessiveUseOfCobblestone I don't see problems with anything I said. Please explain because I want to better myself.

**Pull request merged**
