### PR TITLE
Adds a satchel alternative for mime.

### PR DESCRIPTION
**Pull request by Mandurrrh**
Adds a mime satchel can be selected in character setup before round start as their backpack option..

mimeedit

### CODE REVIEW

**Comment by pudl** [comment]
thats a terrible sprite, just make it a white satchel

**Comment by ColonicAcid** [comment]
better yet make it invisible.

**Comment by Mandurrrh** [comment]
@pudl you leave the same comment on every one of my prs and yet they still go through. Shhh its okay now no tears.

**Comment by pudl** [comment]
because coders have no fucking clue what sprites are

**Comment by Ahammer18** [comment]
It does need to be a bit more subtle, the straps are kind of an eyesore.

**Comment by dannno** [comment]
the sprite is really quite abrasive.

**Comment by pudl** [comment]
fucking owned

**Comment by Atskadan** [comment]
just take the normal mime sprite and give it a satchel strap, like every other satchel besides the brown leather one
also >not using the marcel marceau joke
please

**Comment by optimumtact** [comment]
The only people who can prevent a pull going through on a sprite basis is Wjohn or Nienhaus

**Comment by WJohn** [comment]
I'm not a big fan of the sprite, but I think it could be improved by making the strap a much darker red (both when worn and when on the floor), so that it matches the red of the beret and suspenders better.

**Pull request closed without merging**
