### PR TITLE
Human Skin Hats

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

Adds human skin hats, craftable from human skin (obviously). It doesn't look great, but nothing screams 'psychopath' better than wearing the skin of your enemies on top of your head.

Sprite made with the help of @Krysonism 

## Why It's Good For The Game

It's funny in RimWorld, it'll be funny here.

## Changelog
:cl: YakumoChen
expansion: You can now wear the suffering of others on your head with just a sheet of human skin!
imageadd: Human skin hats, touched up by Krysonism
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
image

**Comment by MrDoomBringer** [comment]
top one with the face

second just looks like a weird straw hat

**Review by Kylerace — APPROVED** [review]
code is good

**Comment by YakumoChen** [comment]
image

**Review by Krysonism — CHANGES_REQUESTED** [review]
I think you could shade the item sprite a little bit better.

The highlight reaches all the way to the edge which makes it look a bit flat.

The band is also shaded a bit weird.

Here is a quick edit i made with some improvements. Feel free to use it if you want.

hatedit

bild

**Comment by YakumoChen** [comment]
thanks, I know my sprite is kinda shit and I'm not really equipped to better it myself.
though I have no idea how to translate that into a DMI

**Comment by YakumoChen** [comment]
Replaced sprite and tried to make the on-mob sprite a little better as well (it even has a little face on it!)

**Pull request merged**
