### PR TITLE
Better Plumbing Pipe Icons

### PR DESCRIPTION
**Pull request by Kerbin-Fiber**
## About The Pull Request
Makes the plumbing pipes better by not making them super clunky.

I dunno how to make it look at fancy shmancy so I just threw to file into imgur

https://imgur.com/a/xG4oeIX

## Why It's Good For The Game
It LOOKS better.

## Changelog
:cl:
tweak: Plumbing pipes aren't as clunky anymore.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Screenshot on this? Diff bot doesn't seem to have picked it up.

**Comment by ArcaneMusic** [comment]
While you're touching that up, would you mind throwing in custom_materials onto stacks of duct so they can be recycled in the autolathe?

**Comment by Kerbin-Fiber** [comment]
Yeah, also, someone told me I was missing the input output pipes, which is true since they're in a separate file

**Comment by ExcessiveUseOfCobblestone** [comment]
New
image
Old
image

**Pull request merged**
