### PR TITLE
Nukie Rework Part 1: Removes some stuff from nukie uplink, adds it as keycard bonuses instead.

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Removes the following items from the nukie uplink:
Power Fist
Flamethrower
Biohazard Sprayer
Dart Pistol
Instead they are given in the nukie base, Power Fist and Flamethrower are available in the Ordnance room, the Dart Pistol is in the Chemistry lab and the Biohazard Sprayer replaces the syringe gun in the bioweapon lab
Adds a box of syringes in the chemistry lab too

## Why It's Good For The Game

Most of these weapons are useless, at least without prep, and nukies would rather just use their normal guns to kill people easily than mess with chems, by giving them as freebies we can encourage buying keycards and also remove these sort of noob trap options from the uplink, and instead put them as options for people that do want to prep, and make a mix for their dart pistol, or a good burnmix for their flamethrower.

## Changelog

:cl: Fikou, NecromancerAnne
balance: The Biohazard Sprayer, Power Fist, Flamethrower and Dart Pistol are no longer in the nukie uplink, instead being given as bonuses in the keycarded parts of the base.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
> You ever see a nukie unlock the xenobio lab and do xenobio for an hour so they could get good slimes before they nuke?

Yes, actually. They managed to convince their fellow teammates to let them build an army of
Golems, which they did. 

This is only memorable because that's how I learned that golems inherit the master's antag datum (the same datum that forces any nuclear operative to be a human.) This would mean that every golem a nuclear operative spawned in would turn into a human immediately on creation.

It was funny so I didn't say anything except like once in Discord. The admin online forcibly changed them back into golems. What's even funnier is those golems made golems, but now _these_ golems didn't inherit the nukie datum. So, they were shredded
to bits by the ship (but also weren't human).

This is pretty much a long winded way of me saying that I've definitely heard of this behavior on production, as well as a few interesting bugs to "prove" it.

**Comment by VladinXXV** [comment]
While I can agree with most of this, I think the biohazard spray doesn't deserve to be removed. It comes preloaded with fairly effective chemicals. It doesn't particularly require any preparation to be effective, and I HAVE seen it used more often than the other items in this PR (still on the lower end of useage, yes, but I think it's in a good spot as is.)

**Comment by Wallemations** [comment]
Next level nukies: removes Nukie uplink, adds all Nukie gear to Black Market uplink

**Comment by VladinXXV** [comment]
i somehow forgot it cost so much, nevermind

**Comment by necromanceranne** [comment]
We'll replace it in the uplink down the line, but like as a freebie its literally whatever. A much larger capacity spray bottle doesn't hurt anyone currently. (Tragically)

**Pull request merged**
