### PR TITLE
Constructs can now invoke runes

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Cultist constructs, and shades, can now invoke runes by clicking them.
rscdel: This does not include Manifest Ghost, Blood Boil, or Astral Journey runes.
/:cl:

I checked, and as it happens, none of the runes assume the user is human.

### CODE REVIEW

**Comment by KazeEspada** [comment]
No reason to convert any more if constructs can summon Nar Nar into the world. Construct cult is back(*cough* NewCult(at least part of it) *cough*)!

Also: Replace arty magic missile with rune creation when?

**Comment by Fox-McCloud** [comment]
This is just going to encourage murderbone cult.

**Comment by KazeEspada** [comment]
Also any animal cultist should be able to use runes

**Comment by coiax** [comment]
only if drones are immune to being converted. I don't think the station deserves cultist drones outside of badminry.

**Comment by drynwyn** [comment]
This is fine, they still need humans to actually draw the runes.

**Comment by PKPenguin321** [comment]
drones shouldn't be letting themselves get converted in the first place

**Comment by coiax** [comment]
Drones can be tased, stunned and EMP'd. It's not like they're immune to stuns.

**Comment by KazeEspada** [comment]
I didnt think drones could be converted

**Comment by AdamElTablawy** [comment]
What wkuld be the point of a cult drone anyway they couldn't do anything due to drone laws aside from shouting PRAISE NARSIE in drone chat

**Comment by KazeEspada** [comment]
Narsie is not a being per say

**Comment by RemieRichards** [comment]
@KazeEspada she is a god, are gods not beings?

**Comment by ChangelingRain** [comment]
Runes definitely aren't beings but I'm not going to condone cult drones because that'd be an admin clusterfuck and nobody wants to get attacked by a drone.

**Comment by AdamElTablawy** [comment]
Can't talk to or obey other cultists, convert, sacrifice, steal, ect the cult. Even listening to a cultist screaming 'GET AROUND THE RUNE' is breaking 'do not interact'

**Comment by Robustin** [comment]
Not a fan of this. One of the biggest distinctions between cult and construct is the former's ability to invoke the runes. This is going to open the door to a lot of uncounterable strategies that will frustrate players if the cult ever masters them.

Example: You can flashbang/gas cultists gathering around a blood boil rune, but what if its 3 juggernauts? There's just no way to stop that. Not saying constructs can work independently, but now you can really do have some unbeatable tactics. I know id be more than a little salty if artificers were camping in a closed room, no way to flush them out, and when you go in they MM + convert you by themselves.

**Comment by KazeEspada** [comment]
One, Nar Nar has no gender, it is an alien other thing so foreign to our thoughts that we can't even begin to comprehend what it is.

Well, my argument is all cultists regardless of form should be able to use runes. That being said, during a normal round this will only be humans, monkeys(geneticists), and constructs.

However, if badmins drop a wizard, or decided for DRONE CULT. Than they should be allowed. The check should really be on the convert rune to make sure only humans join the cult.

**Comment by RemieRichards** [comment]
she's a girl, it used to be 50/50 what the code+flavourtext calls her but it was changed (by Aran?)

**Comment by RemieRichards** [comment]
she's a girl, it used to be 50/50 what the code+flavourtext called her but it was changed (by Aran?)

**Comment by RemieRichards** [comment]
she's a girl, it used to be 50/50 what the code+flavourtext called her but it was changed (by Aran?)

**Comment by ChangelingRain** [comment]
It was mostly changed by me except for maybe one message?

**Comment by RemieRichards** [comment]
Could have swore it was Aran... anyway the point is it was made this way deliberately and now it's canon!

**Comment by KazeEspada** [comment]
Not that I am against a female diety, but I always thought Nar-Sie was supposed to be more lovecraftian?

**Comment by ChangelingRain** [comment]
Because I say so.

**Comment by AdamElTablawy** [comment]
i'm still concerned about xenobio getting bored on a cult round and unleashing cultist statues, ect

**Comment by drynwyn** [comment]
All the messages really indicate is how Nar-Sie's followers VIEW nar-sie, it's a fucking giant black-red-squid-golem-thing, it doesn't have genitalia one way or the other

**Comment by KorPhaeron** [comment]
I was gonna merge this because not being able to use telerunes always annoyed me but constructs spamming blood boil sounds gross

**Comment by Robustin** [comment]
Cultists can tele constructs now. i just dont like that comstructs could be self sufficient if someone drew them runes in advance. People should be able to tell what kind of threats the cult presents. Lettiing constructs invoke runes really blurs that line too far for my tastes.

**Comment by ChangelingRain** [comment]
Constructs can't make blood boil runes on their own, and if you have a human to make a blood boil rune they can invoke it, so the theoretical construct boil spam is more or less impossible without a human to assist.

**Comment by Incomptinence** [comment]
It's about time.

**Comment by Robustin** [comment]
It's not terrible hard, or uncommon, to leave a bunch of runes in your base and then head out to abduct people or whatever while your constructs stay on defense. Having those constructs be able to sac/convert/bloodboil people just seems like they're stepping too far into human territory. 

Conversion should be something with a human touch.

**Comment by ChangelingRain** [comment]
Alright, constructs don't get to manifest ghosts, astral journey, or blood boil. They still count as invokers for the last one, but can't invoke it.

**Comment by ChangelingRain** [comment]
If needed it's super easy to make conversion/sac also unable to be invoked.

**Comment by KorPhaeron** [comment]
Alright I get the argument of humans and constructs should be separate, but the cult winrate is already abysmal, and constructs are often super fucking boring to play since they just tell you to hide in the base for 20 minutes until they're ready to swarm.

**Pull request merged**
