### PR TITLE
[s] It all returns to crackers

### PR DESCRIPTION
**Pull request by Incoming5643**
Those who remain close to the bird will become the bird.

d10_icon

Parrots as a mutant race are occasionally forced to say using the same speech bank poly uses. They also occasionally lay eggs because why not.

Can provide a cure to the horrors of another pull currently in the april fools branch...

### CODE REVIEW

**Comment by RemieRichards** [comment]
jesus christ

**Comment by PKPenguin321** [comment]
>Tell Poly "I'm a traitor" 10,000 times

>Parrot men get lynched in the streets

Lmao

**Comment by YotaXP** [comment]
What?  No tail feathers?

**Comment by TrustyGun** [comment]
You're sure about that?

**Comment by Supermichael777** [comment]
25% on life for every mob its close to is a bit high

**Comment by Incoming5643** [comment]
@YotaXP the sprites are pretty damn low effort, since it's a one day joke pr and 90% of the people who see it are only ever gonna see the face anyway, especially since the guys most likely to get affected by it are the ones with ready access to masks and hardsuits.

@Supermichael777 kinda has to be, if poly doesn't get the CE before he leaves his office people are pretty unlikely to even notice this is a thing.

**Comment by KazeEspada** [comment]
Their beak will stick out of hardsuits, masks, etc.

**Comment by Incoming5643** [comment]
If you can believe it the beak isn't any further out than the standard human nose, so if layering problems exist at all they're extremely minor. I could make the beaks a mutant body part that's hidden by masks like lizard snouts, but again. That's more effort than this frankly deserves.

**Comment by Chocobro** [comment]
IT WAS INCOMING'S PLAN THE WHOLE TIME

**Pull request merged**
