### PR TITLE
[WIP] Say dialog box rework

### LINKED ISSUE #8999: Using Say Hotkey lets you Talk without being interupted
Basically, ye know how you can get interrupted if you get hit hard while typing somethi-oof!
If you use the say HotKey, it makes a window pop up, which can't be interrupted.
So you could use it to utterly ignore the interruption getting attacked can cause to yell out whatever you want.

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl: NicBN
tweak: Using the T hotkey will now focus the input bar for you, prefixing it with "say". You can still use the old behaviour by toggling it on Game Preferences. After talking on the new behaviour, press TAB (for hotkey mode) or ENTER to quit the input bar.
/:cl:

I've removed the buttons tothe right of the input bar.

The original intention was to have the input bar defocused as soon as the message is sent, but I was unable to accomplish it. This way works fine anyway, so let's give it a try.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
the input bar doesn't support arrow keys or home/end without a modifier (control) and barely support copy and paste, and don't support control+a for select all.

All things I've used on the dialog prompt.

I think it might be better to make this a pref toggle defaulting to on for new prefs and off for existing prefs because it will have huge usability improvements for some but huge usability setbacks for others.

**Comment by nicbn** [comment]
I want to completely remove the prompt so forcesay will no longer be avoidable.

I believe that if you are in a circumstance in which you have time to stop walking so that you can send a message, you have time to use your mouse to move the input pointer or to select the text. It's a little annoying, of course, but I believe it's better than keeping the prompt.

**Comment by MrStonedOne** [comment]
The solution is to remove the forcesay

**Comment by MrStonedOne** [comment]
or make a html window with a forum dialog box.

this would have to be done where the html window is in the skin and opened via a client side command to not add lag to pressing t/o/m.

**Comment by MrStonedOne** [comment]
Regardless, not degrading usability will be number one in my mind. so this is a no from me as long as the issues I mentioned are present.

The proper way is either do the html input window opened and closed by client side macros, or the preference fix that defaults to existing behavior for existing preference files, and defaults to new behavior for new preference files. Something we have the framework to do.

**Comment by nicbn** [comment]
For now I'll be just removing the dialog box. If anyone wishes to bring it back later using HTML forms or anything, feel free to do it. Until that, the players will have to live without spamming chat using Ctrl+A at lightspeed.

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
Either do the html input window opened and closed by client side macros, or the preference fix that defaults to existing behavior for existing preference files, and defaults to new behavior for new preference files. Something we have the framework to do.

**Comment by nicbn** [comment]
Well, hold on then.

**Comment by nicbn** [comment]
* Right now, everything works fine. But there is no dialog box.
* You can move the cursor by using Ctrl+Arrow keys.
* Ctrl+C and Ctrl+V works

So the only thing that MSO wants and you can't do is selecting via Ctrl+A. Is this really worth creating a form?
I personally think that the way it is right now is perfectly fine and even better than a form, but if y'all want a input box so badly I'll try to code it.

**Comment by MrStonedOne** [comment]
I'm never going to support a reduction in usability for existing users.

even if its minor.

**Comment by Armhulen** [comment]
i always use dialog boxes so this pr deeply hurts me

**Comment by nicbn** [comment]
I believe it's an increase in usability as you're now able to walk while talking. But ok I'll try to do the form.

**Comment by nicbn** [comment]
I think that the thing that's not worth the tradeoff is the box, not the current bar thing. The only advantage of having the box is Ctrl+A to spam, and the code for the bar is actually very clean and neat.

**Comment by nicbn** [comment]
Ok I won't do the custom form thing. I'll leave the default, avoids-forcesay box as is for now.

**Comment by fludd12** [comment]
I wonder if it's possible to make a special box thing, that can return output at will...

**Comment by nicbn** [comment]
I need to work a little more on that

**Pull request closed without merging**
