### PR TITLE
Offense To Artists Incarnate - tries to clean (desoul) the new IDs

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

With the recent merge of https://github.com/tgstation/tgstation/pull/78761 I'm sure there's mixed opinions somewhere, but feedback is generally positive. I also agree that the spritework is top-notch and, in fact, bussin. The only gripe I heard and was able to personally make was that the sprites were 'too busy', and had a lot of visual clutter despite their high quality. Let me preface this by saying that I'm **not** a professional spriter, and this PR is made in no offense or with intended ill will to the original creator(s) of these sprites.

I've made the very subpar, mediocre, and half-assed attempt to remove some of the visual noise from these sprites, attempting to increase their consistency with one another, and somewhat reducing their shading and inadvertently making them appear a bit 'flatter' intentionally. I've also removed the CRT-like overlay from the trims, given that they were originally supposed to be animated but now appear (imho) a bit strange with the horizontal gradient across everything being static. All across, this does make the IDs a bit closer to the old ones for better or for worse, but to some degree I've attempted to maintain the artstyle and overall intent.

I feel pretty bad making this PR so soon after the new updates were put in place though. 😞

Capture

Lastly, I made a half-assed attempt to new-spriteify the battlecruiser caller, alongside reducing some of the flickering on the doorjack and emag so as to make them hopefully less distracting. I originally modified these sprites to use downstream where the artstyle clash was more readily apparent, but figured I'd may as well at least try to take it upstream and see if people here like it, or if there's any feedback to improve them.
## Why It's Good For The Game

IDK. Better on the eyes?????????? I think in particular the gold ID and emag/doorjack (due to their flickering) was really discomforting to look at, but that's just me.
## Changelog
:cl:
image: modified the ID sprites to make them a bit less visually noisy, and ironically reducing their visual fidelity
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
I like how the ID’s don’t look like large bricks anymore, though I wish the ID’s were animated a tiny bit

**Comment by EricZilla** [comment]
Overall looks good! I just PRd for the original guy so I didn't wanna change too much with the first pass. The door jacks new animation is a lot cooler.

My only criticism  is if you gotta change the door jack from a gold can you at least make it a silver, the joke was that it was an all access ID, but also part of the idea behind it was it was using the code from the higher access id for Mysterious Bullshit

**Comment by YakumoChen** [comment]
The silver colour is really close to the grey, it has been increasingly hard to tell the difference between the two.

**Comment by zeroisthebiggay** [comment]
> My only criticism is if you gotta change the door jack from a gold can you at least make it a silver, the joke was that it was an all access ID, but also part of the idea behind it was it was using the code from the higher access id for Mysterious Bullshit. Though I only changed it in the first place because people wanted to be easier able to tell them apart at a glance in tense situations

Yeah I thought about visual recognition and I'll dwell on it if I get any good ideas.
I might revert it back to gold but I thought it looked a bit garish IMHO.

> The silver colour is really close to the grey, it has been increasingly hard to tell the difference between the two.

Unfortunately it was like that before. I think they're visually distinct enough what with how they usually have the dark blue trims that it's not super big of an issue though.

**Comment by zeroisthebiggay** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

FUck you

**Comment by zeroisthebiggay** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

FUck you

**Comment by san7890** [comment]
@tgstation/sprite-team please review this PR within the coming week or i will close this PR cheers

**Comment by captainfrost20** [comment]
These are much, much better.

**Comment by san7890** [comment]
unfortunately this has gone 16 days without any interest from the sprite team so i think we're just gonna have to call it a wash - would encourage reaching out to them via discord or something and agreeing on if this is good for the art direction of the game before you open a new PR so you don't end up staleing out for two weeks straight

**Pull request closed without merging**
