### PR TITLE
Bowling For protolathes

### PR DESCRIPTION
**Pull request by Orchian**
## About The Pull Request

Adds various kitchen/bar items to the service protolathe

## Why It's Good For The Game

Increases convenience when replacing misplaced, destroyed, and/or stolen equipment

## Changelog
:cl:
qol: We've added various bartending and cooking utensils to your service lathes to make the lives of the starving culinary artist easier! ...Wait
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
Strikes me as more of a buff/balance than a "QOL", also isnt protolathe knives a heretic buff? Probably should acknowledge that.

**Comment by Orchian** [comment]
> Strikes me as more of a buff/balance than a "QOL", also isnt protolathe knives a heretic buff? Probably should acknowledge that.

I would not know, as I have never touched Heretic

**Comment by optimumtact** [comment]
Buff disguised as QoL

**Comment by SuperNovaa41** [comment]
> Strikes me as more of a buff/balance than a "QOL", also isnt protolathe knives a heretic buff? Probably should acknowledge that.

You can make heretic blades with a plastic knife, which is already in the service protolathe

**Comment by Orchian** [comment]
> Buff disguised as QoL

I still

**Comment by Orchian** [comment]
I accidentally closed the PR, FUCK

**Comment by CRITAWAKETS** [comment]
not really a QoL change, should be marked balance because there's always that one crazy person that takes advantage of some minor change to balance in order to murderbone the whole station

**Comment by SuperNovaa41** [comment]
> not really a QoL change, should be marked balance because there's always that one crazy person that takes advantage of some minor change to balance in order to murderbone the whole station

Hmm yes today I will kill the entire station with a bowl

**Comment by CRITAWAKETS** [comment]
> Hmm yes today I will kill the entire station with a bowl

SS13 is just that one scene from kingsman and you know it

**Comment by Orchian** [comment]
> > Hmm yes today I will kill the entire station with a bowl
> 
> SS13 is just that one scene from kingsman and you know it

bal is the prefix for balance change right? Or was it just balance?

**Comment by SuperNovaa41** [comment]
> > Hmm yes today I will kill the entire station with a bowl
> 
> SS13 is just that one scene from kingsman and you know it

I'm going to murderbone with a bowl now and it's all your fault

**Comment by jwc1015** [comment]
> > Strikes me as more of a buff/balance than a "QOL", also isnt protolathe knives a heretic buff? Probably should acknowledge that.
> 
> You can make heretic blades with a plastic knife, which is already in the service protolathe

Also - glass shivs count as knives, which is just cloth + glass shard (cloth can be gotten from just wirecutters on bedsheet) so knives for heretic blades are really incredibly easy to get.

**Comment by RaveRadbury** [comment]
Some of this seems like power creep. 

We've been making the chef and bartender buy materials out of their vendors. Handing it to the lathes short-circuits that.

**Comment by Orchian** [comment]
> Some of this seems like power creep.
> 
> We've been making the chef and bartender buy materials out of their vendors. Handing it to the lathes short-circuits that.

They only hold so many extras, no?

**Comment by RaveRadbury** [comment]
> > Some of this seems like power creep.
> > We've been making the chef and bartender buy materials out of their vendors. Handing it to the lathes short-circuits that.
> 
> They only hold so many extras, no?
> I would like it if you elaborated on this point.

Yeah, so you order more from cargo.
The point I'm actually trying to make is that vendors cost money. You're giving the stuff away for free now.

**Comment by Orchian** [comment]
> > > Some of this seems like power creep.
> > > We've been making the chef and bartender buy materials out of their vendors. Handing it to the lathes short-circuits that.
> > 
> > 
> > They only hold so many extras, no?
> > I would like it if you elaborated on this point.
> 
> Yeah, so you order more from cargo.
> The point I'm actually trying to make is that vendors cost money. You're giving the stuff away for free now.

Ah, I was not aware that you could order extra utensils from cargo. Are there any items in particular you'd like to see off the lathe?

**Comment by RaveRadbury** [comment]
> Ah, I was not aware that you could order extra utensils from cargo. Are there any items in particular you'd like to see off the lathe?

Anything that you can buy from their vendors as a start. Keep in mind also that setting up an autolathe in service isn't too hard and also something that happens from time to time.

This might be something that you should lock behind a tech node rather than just handing out at the start of the shift.

**Comment by Orchian** [comment]
> > Ah, I was not aware that you could order extra utensils from cargo. Are there any items in particular you'd like to see off the lathe?
> 
> Anything that you can buy from their vendors as a start. Keep in mind also that setting up an autolathe in service isn't too hard and also something that happens from time to time.
> 
> This might be something that you should lock behind a tech node rather than just handing out at the start of the shift.

Could you list them? I can't recall exactly what is and isn't available in the vendors. As for the tech node... I'm thinking biological processing?

**Comment by RaveRadbury** [comment]
Looks like it might be... everything... tbh. You should spin up a local and double check, or code dive.

**Comment by Orchian** [comment]
> Looks like it might be... everything... tbh. You should spin up a local and double check, or code dive.

I'll look into it

**Comment by SuperNovaa41** [comment]
> > Looks like it might be... everything... tbh. You should spin up a local and double check, or code dive.
> 
> I'll look into it
> 
> Edit: Looks like just Kitchen knife, metal fork, metal spoon, bowl, serving tray, and the shot and drinking glasses,
> 
> I would also like to know your thoughts on the suggested tech node (biological processing)

If that's the techweb that unlocks other kitchen equipment that would probably be fine

**Comment by Orchian** [comment]
> > > Looks like it might be... everything... tbh. You should spin up a local and double check, or code dive.
> > 
> > 
> > I'll look into it
> > Edit: Looks like just Kitchen knife, metal fork, metal spoon, bowl, serving tray, and the shot and drinking glasses,
> > I would also like to know your thoughts on the suggested tech node (biological processing)
> 
> If that's the techweb that unlocks other kitchen equipment that would probably be fine

That's the one, yeah.

**Comment by Orchian** [comment]
Closing for now pending response

**Pull request closed without merging**
