### PR TITLE
Fixes ayylien experimentation machine not finding the gland in the speciment

### LINKED ISSUE #11060: The experimentor machine for ayyliens doesn't work.
It won't scan people, despite having done the surgery and put in the ayylien organ. This means you aren't able to get points, or really do anything with the guys you've abducted.

Pretty much game breaking from their perspective since they rely entirely on being able to actually finish their experiments.

### PR DESCRIPTION
**Pull request by phil235**
Fixes #11060.

### CODE REVIEW

**Comment by Jalleo** [comment]
:+1:

**Comment by Core0verload** [comment]
Thanks. I'm not sure who decided that internal organs should be stored in nullspace instead of mob's contents, but I already hate myself for not changing it.

**Comment by Fox-McCloud** [comment]
There's a few runtimes related to the organ scanner as well, I believe. Not sure what they are off the top of my head though.

**Comment by Fox-McCloud** [comment]
@Core0verload 

That's a simple one; anything that drops all contents will also drop people's organs as well, if you do that.

**Comment by RemieRichards** [comment]
Merging as a Hotfix

**Pull request merged**
