### PR TITLE
Changes the heretic sac from gib to spill all your organs and kills you

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request

Heretics no longer gibs their target, instead spill all their organs and killing them.

## Why It's Good For The Game

Gives heretic the choice to round remove people or let them be revived eventually. Round removing an organless body isn't so hard, and it's a choice you decide to make. The previous sac forced you to gib your target and moving away from forcing such powerful consequences is better for the game health, especially on MRP where gibbing someone should be rare.

## Changelog

:cl:
balance: Heretics no longer gib their target when sacrificing them, instead outright killing them and spilling all their organs everywhere in a gruesome manner.
/:cl:

### CODE REVIEW

**Comment by KathyRyals** [comment]
GBP bot is boutta yell at me- there it is.

**Comment by theta006** [comment]
the brain is still there its not round removing

**Comment by Mothblocks** [comment]
it basically is

**Comment by KathyRyals** [comment]
It takes a lot of effort to fix someone from just a brain, and they lose their appearance more often than not.

**Comment by theta006** [comment]
just put it in a new body and its fine

**Comment by KathyRyals** [comment]
It's not the same. Putting you in a new body means you lose your old name and such, plus that takes a lot more effort than slotting new organs and reviving someone.

**Comment by theta006** [comment]
the heretic can still rip someones head off and stuff it in maint

**Comment by CRITAWAKETS** [comment]
honestly the best part about this PR is that it makes playing heretic less braindead murderhobo mode because you actually need to hide the bodies

**Comment by GoldenAlpharex** [comment]
Good change.

**Comment by Mothblocks** [comment]
@theta006 Someone going through the effort of ensuring round removal is better than it just happening by default

**Review by Mothblocks — APPROVED** [review]

**Comment by Fritzlschnitzel** [comment]
Sus

Actually a flesh heretic buff as it lets you sacrifice and thrall them now.

**Comment by ATH1909** [comment]
> Sus
> 
> Actually a flesh heretic buff as it lets you sacrifice and thrall them now.

but this will also make it much harder to get components for your rituals, which expect you to be able to have arms and legs and stuff on hand from your sac victims

**Comment by Krysonism** [comment]
> it basically is

No, that is a skill issue . Just make a monkey man and transplant the head.

Hugbox change

**Comment by Krysonism** [comment]
> It's not the same. Putting you in a new body means you lose your old name and such, plus that takes a lot more effort than slotting new organs and reviving someone.

Irrelevant as heretic sacrifice drops head, not brain.

**Comment by o0cyann0o** [comment]
> but this will also make it much harder to get components for your rituals, which expect you to be able to have arms and legs and stuff on hand from your sac victims

I think making them go out of their way for parts is a good change tbh, makes people work for their summons rather than being able to spam 30 of them passively as an afterthought 
Plus thralls>>>simplemob minions anyways

**Comment by EdgeLordExe** [comment]
+1

**Comment by SoreYew** [comment]
> > Sus
> 
> > 
> 
> > Actually a flesh heretic buff as it lets you sacrifice and thrall them now.
> 
> 
> 
> but this will also make it much harder to get components for your rituals, which expect you to be able to have arms and legs and stuff on hand from your sac victims

Heretics already abuse monkey cubes constantly. this would only reinforce that meta, which is a better solution than the obnoxious soft gib that only this antag has

**Comment by KathyRyals** [comment]
> > Sus
> > Actually a flesh heretic buff as it lets you sacrifice and thrall them now.
> 
> but this will also make it much harder to get components for your rituals, which expect you to be able to have arms and legs and stuff on hand from your sac victims

Thank you ATHATH for voicing your concerns about this. I can assure you that delimbing the gutted corpse is of course very possible, and is also quite easy considering heretics almost always carries a sharp object very capable of cutting off limbs - Their blade. Additionally, I believe that the flavour of a mad, old god worshipper hacking frantically at a corpse with a crescent blade to take its limbs to transmute is much cooler flavour than just "ahah boom goes the corpse".

**Pull request merged**
