### PR TITLE
Remaps meta's ordnance

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
<details closed>
<summary> Raw image </summary>

</details>

<details closed>
<summary> Distro and waste hidden </summary>

</details>

<details closed>
<summary> Areas </summary>

</details>

Primary goal is to make things slightly more intuitive map-wise and somewhat more segmented. I don't want folks to get overwhelmed by toxins immediately and then not revisit them at all. 

Tried to do this by making a simple route from top left to bottom right that most scientists will take when they want to do an experiment. 

Expose one area at a time, and then let them trek along the map as they finish each step.

### Lets go over them
<details closed>
<summary>1) A scientist should spawn here, at the top left.</summary>

And immediately be greeted by the monitor, since that will be their debriefer. I plan to add a disk containing the NT frontier program right there by the table too. Kinda opposed to immediately adding it as a prereq downloads, might as well teach folks how to operate the file manager while we're here. Not very critical to be honest.
</details>

<details closed>
<summary>2) Then move south, where they get equipped and can prep the mix.</summary>

Increased the amount of o2 gas by around 5k moles to 15k here. IIRC most maps had 6 cans of o2, with 1.8k each, totalling to just under 11k. Most of the pressure tanks are actually empty, filled the room with it just because it looks better :)
Let me know if you have any objections to this. Scarcity seem to be something a number of maintainers are keen upon.
</details>

<details closed>
<summary>3) They then move northeast, and are free to route the mixed gas to the next room.</summary>

</details>

<details closed>
<summary>4) Opened the airlocks to the west and then they are finally greeted with the chambers.</summary>

This might be a bit more contentious. Adding an extra chamber with cooling loop on top is a quite a significant upgrade to the workplace. But I reckon the sense of direction that this gives new players will be worth it. 

Non atmos players are not supposed to know that the most efficient way to make BZ is with an open turf chamber with HE pipes. They wont know that nob and halon are also made very easily that way. They wouldn't get the hint to print 8 plasmarglass from the lathe, stack them together, and then screwdriver + crowbar them after they finished the plumbing. At least not without being told or looking this up in the wiki. By doing this, we at least give them a hint to do some reactions openly, similar to the chambers in delta atmos but with some more upgrades.

This setup still has a few inefficiencies. We still have only one fire chamber scrubber, the cooling chamber cant cool down to nob, and it is still plated with regular tiles and can melt if folks try to rebel a bit. Freezer count is also cut down to one. Deliberately did this so rushing toxins ASAP is a tad more annoying. Still easier than what it used to be though.

Also the monitors are varedited and cant be reconstructed. Might add a subtype later.

</details>

<details closed>
<summary>5) With the gas collected, they can assemble the tanks by going west again.</summary>

</details>

<details closed>
<summary>6) And watch the fireworks if they're doing bombs by going south.</summary>

</details>

## Why It's Good For The Game
This is one of the oldest images of toxins i could find on our wiki. It's dated to 2014. It's pretty much the same as our current setup.

<details closed>
<summary>Click me</summary>

https://tgstation13.org/wiki/File:Toxins_Lab.png
</details>

It's time for a touchup, make the layout actually reflect what we want folks to be doing.

In case you skimmed, more reasoning can be found in the "About the PR" section.

## Changelog
:cl:
expansion: Meta's ordnance got remapped and segmented.
fix: Fixed meta's burnmix chamber not being vacuum.
/:cl:

### CODE REVIEW

**Review by san7890 — COMMENTED** [review]
Hey there,

I took a quick peek through and noticed a few things that you'll probably want to address.

Firstly: APCs. None of them have wires.

image

image

image

image

I don't think your Ordnance Hall area even _has_ an APC. Do correct that.

Here's some more nitpicky ones:

image

There's no particular reason to have that set of walls be reinforced without the rest of the launch area be reinforced. May be a hold-over from the old setup? Do let me know.

image

Aft/Starboard Maintenance should own those two sets of walls, but it's fine to have the door be owned by the Mix area.

image

It would be nice for this room to have another air alarm.

All in all, I really like what you've done. It's a really unique design, and I think it's interesting to have multiple types of mixchambers pre-made for utilization. The new placement of the Launch Area is fine, and it uses a lot of interesting new design choices (read: anti-Box) that I really find interesting. Good work.

**Comment by Son-of-Space** [comment]
Really good redesign. I like that you're playing with the idea of having traditionally cordoned off areas be exposed to maintenance.

My favorite part is that you're clearly showing the player the purpose of each of the areas and have a strong flow for how the workspace functions. That gives it an automatic A in my book. Looks like these areas add some extra utility to the workspace as well by helping the player naturally organize their space. Very very good.

**Comment by Son-of-Space** [comment]
<details><summary>You might want to remove the wall chicken here. I just did that on Box.</summary>
image

</details>

<details><summary>Not sure how I feel about there being no maintenance access for toxins. I would add a maint door and move some of the tanks around to keep the balance here similar..</summary>
image

</details>


<details><summary>No more psychokiller mask? Very very sad.</summary>

image
</details>

**Comment by vincentiusvin** [comment]
Most of them addressed.

Afraid I cant really add another door to the gas storage, makes it look bad. Folks will have to make do with breaking in from the oxygen side.
Cyborg outfit added to hydroponics instead.

Thanks for the sage advice folks.

**Comment by Inari-Whitebear** [comment]
So little hallway space... only one freezer? Damn, will make it a pain to repipe it

**Comment by Inari-Whitebear** [comment]
As someone who regularly plays ordnance I really can't see many good points about this?
Only one freezer, so it'll either be a pain to separately cool gases or I'll have to build another one. Feels like even less space to repipe stuff than the current layout has. In big part because the area available never goes above 3 in one dimension.

I mean, I'll probably figure something out overall, but feels like a downgrade overall.

**Comment by vincentiusvin** [comment]
I've never really agreed with the lack of space claim, both in atmos and toxins. You have two more unoccupied layers. Space is plenty for pipes, just use manifolds. 

One manifold on the pump (which you should always do anyway since trit is scarce)
image
Would let you remove the connector port right above it and put a freezer in l2 which is immediately hooked to the waste. And then add a volume pump in l1, l3, or l5.

A bit more open about the freezer one. I can readd it if you can find me a nice place to plop it down at.

**Comment by vincentiusvin** [comment]
I plan to redo the toxins on all maps anyway, I can almost promise that they will be larger than this one. Variety is interesting.

**Comment by Inari-Whitebear** [comment]
> I've never really agreed with the lack of space claim, both in atmos and toxins. You have two more unoccupied layers. Space is plenty for pipes, just use manifolds.
> 
> One manifold on the pump (which you should always do anyway since trit is scarce) image Would let you remove the connector port right above it and put a freezer in l2 which is immediately hooked to the waste. And then add a volume pump in l1, l3, or l5 and expand westwards or eastwards.
> 
> A bit more open about the freezer one. I can readd it if you can find me a nice place to plop it down at. Doesn't have to be connected to the scrubber line or anything as long as its hooked to the waste and in the main chamber room. Main reasoning to not add freezers is because it looks ugly.

It's not quite that easy though. Some of the space is taken up by vents/scrubbers, can't put anything put pipes there. Then there's the terrible freezer piping in some stations where you have to look at where their layer adapters and stuff are placed and the like.

**Comment by Zytolg** [comment]
As the original Author of the updated Toxins of this map, I am fairly against these changes. Immediately what jumps out to me is the sectioning off of the Toxins Storage away from maint which in terms of the game design is a little too safe for my liking, while also functionally cutting it off from the rest of science/the station. Toxins is the primary point of response when it comes to cleaning up gas spills (unga scrubbers) and it's a bad idea to leave it so cut off as it is. 

The main thing that really irks me however, is that I very intentionally routed maint up and adjacent through science in order to present more interesting avenues to approach subterfuge. This redesign largely discards those alterations, and largely because of this, I'm going to oppose this change. This reverts this specific area of science back towards something similar to what I designed it away from. You point out the same thing in your PR text, and ironically, I find that this redesign is more similar to that than what is currently available. 

I'm not saying that there aren't bad ideas here. It more boils down to me finding the implementation lacking.

**Review by Maurukas — COMMENTED** [review]
Sorry this has taken so long to get to. I try to have at a chunk of time to try out area and department reworks, and that hasn't been happening for the past week or so.

The layout feels cramped by Metastation standards - there are doors between small areas that have to be opened repeatedly as you move back and forth. This takes away a good chunk of round start equipment, but ends up with less space . The additional walls, windows and doors really frustrate any effort to substantially modify the piping. I also ran into some issues with temperature leaking from the freeze chamber - though that may have been my own fault.

I don't have any objection to streamlining toxins, but having tried to use this - I think this layout is too cramped for Meta.

**Pull request closed without merging**
