### PR TITLE
Fixes not being able to put items inside secure storages.

### LINKED ISSUE #20761: Secure Storages [Wallsafes / SecureBriefcase]
When trying to put in an item into a wallsafe or secure briefcase, the item just stays in your hand, making these items useless in terms of storage.

### PR DESCRIPTION
**Pull request by lzimann**
Fixes #20761 
It had two attackby procs.

### CODE REVIEW

**Review by phil235 — APPROVED** [review]
:+1:

**Comment by optimumtact** [comment]
Don't you need to move the emag handling up into the other attackby or did you just consider it irrelevant

also my understanding was that this was valid byond functionality and it did some magic to ensure all the procs were run

**Comment by lzimann** [comment]
I removed the whole fluff message about emagging. After removing this it started working again perfectly. I can add the message again if you really want.

**Comment by optimumtact** [comment]
no it's fine

**Pull request merged**
