### PR TITLE
buffs head slugs a bit

### PR DESCRIPTION
**Pull request by Incoming5643**
Head slugs are now actually controlled by the ling who burst
Head slugs can now vent crawl (they're so tiny why didn't they already have this?)
Head slugs can stumble around for 10 seconds after they lay their egg so they don't die super obviously right next to their infected corpse

### CODE REVIEW

**Comment by Man-Shroom** [comment]
:+1: , but also make them player-controlled.

**Comment by Incoming5643** [comment]
they aren't already?

**Comment by WJohn** [comment]
Yeah I was wondering why the hell we even have them. It seems incredibly last-resort.

**Comment by Man-Shroom** [comment]
Anturk didn't make them PC because he thought it'd be too OP. Which, while a good attempt at balance, makes them lean a bit in the opposite direction.

**Comment by Incoming5643** [comment]
Well I mean there's underpowered and then there's "in order for this to work you need to be sure it spawns in a room with a corpse, no one to step on it, and no one to take the time (three minutes!) to remove the egg".

I think they deserve a fighting chance here.

**Comment by pudl** [comment]
making it ling controlled is a bit too much, imo. i think that making the egg time 1.5 minutes, and maybe making the slug take 2-3 steps to kill instead of 1 would be much better.

**Comment by Man-Shroom** [comment]
Making it not a buggy NPC is too much, but letting a ling gib living players at will is fine?

**Comment by AnturK** [comment]
Yeah,  they were originally player controlled but i removed that because it made slugs strictly superior to lesser form in 90% escape situations

**Comment by Incoming5643** [comment]
I don't see it like that, you can still regenerate in lesser form, you can still get a second chance if someone is incompetent or you manage to vent crawl somewhere before your finished off.

With head slugs death is IT, legitimate true death for a ling. Not to mention they have ten times less health at maxhealth = 20. That's one laser. OHKO antag ender then and there. Not even the cloner/debraining/podperson seeds can save a dead simple animal. They don't really have the means to defend themselves and a savvy crew has the ability to defeat the egg even if the slug manages to make it out of whatever room they spawned in (which would be hard without hands or ventcrawler like monkeys do). Especially with the big red flag camera trackable slug corpse helpfully pointing at the specific infected to target.

If you ask me lesser form is more a utility thing, useful for getting into places and retaining most skills, also it's easily reversible.

Head slugs are straight up escape, there's no other reason to use it. All items destroyed, ya blew it, hope you hid a corpse somewhere to use mode.

**Pull request merged**
