### PR TITLE
ERT Buff

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

This PR aims to make the ERT for the most part not necessarily stronger in *combat*, but more tidy and prepared for other problems. Right now, code amber ERT medics don't even have a toxin-healer, other than their medbeam.

I intend to fix that, and help make ERTs ready for any threat, be it related purely to medical, engineering, or security manners. 

## Why It's Good For The Game
ERTs right now, like I said,  are just too weak. Their equipment feels like it was just coded in with the very bare basics by someone 2 years ago and never touched again, which results in them often being ill-suited to real emergencies onstation.

I'm making a draft PR to get feedback, since I don't want it to be merged right now.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
do ert count as antags

**Comment by Qustinnus** [comment]
actually they are antags, I'm inclined to press close but I'm only an issue jannie so I'll let an experienced button masher do it for me >:^)

**Comment by carlarctg** [comment]
reeeeeeeeeeeeeeeeeeee

**Comment by carlarctg** [comment]
turns out going against the spirit of the freeze but not the rules is still not allowed, woweeee

**Comment by knacker48** [comment]
How the hell are ERT antags?

**Comment by actioninja** [comment]
Lol why are you listening to floyd

**Pull request closed without merging**
