### PR TITLE
New movement modes, sneak/walk/run. Stamina based running and proper walking.

### PR DESCRIPTION
**Pull request by flopppi**
## About The Pull Request

Discussed [in this discord post](https://discord.com/channels/326822144233439242/1162004816785063936)

Okay, this ones a doozy.
This PR is inspired by the swing combat testmerges, where they made movement generally slower. I liked it, but in general there were a couple complaints from people. I feel this is a good, and realistic, compromise.

I'm drafting this PR for now because there are couple coding problems that need to be resolved, and numbers need to get tweaked based on what people say. Correction: A LOT of problems in general, namely balance, that need to get resolved.

### **The movement intents have been reworked. There are now 3 movement intents: sneak, walk, and run.**
- Sneaking takes the place of walking as it currently stands. It prevents you from slipping, makes you quite, and is.. incredibly slow.
- Walking is the new default movement intent, that is notably slower then running. Ideally, you shouldn't need to move faster if you're in, lets say, your department doing things like toxins or moving boxes in cargo. However, traversing large stations would be awful at this speed. While walking, you only have a 50% chance to slip on every wet tile you step on. (You will always slip on lube, of course.)
- Running requires stamina to do, and has the same speed as running as it currently stands. You can only run if you have more then half your max stamina, and if it drops below, you will just walk like normal and regain your stamina. It is ideal for moving around the station, when you got someplace to be, and the stamina loss is not intended to be a problem in this context.

For reference, you can take 2.5 laps around metastation's bridge before becoming too exhausted to run as it stands. (half to stamina crit)

### Controls
There are 2 new bindings. The default, at the moment, it is hold shift to sprint. Similar to throwing, there is an extra binding for toggling rather then holding to sprint. 

The controls for cycling walking/sneaking have not changed, and still rely on the basic move intent keybinds.

https://github.com/tgstation/tgstation/assets/75865592/cb78e49c-ab0c-4307-8a86-1debe60b4d15
*Walking around cargo*

https://github.com/tgstation/tgstation/assets/75865592/48027f75-9f5a-468c-b0f3-8d96b32d3557
*Slipping chance*

https://github.com/tgstation/tgstation/assets/75865592/b6a2481f-66cc-41e7-8f15-81e46da8e306
*Running between departments*

## Why It's Good For The Game

Alrighty. Here we go.

### **There is a sentiment that the movement speed is simply too much.**
Stated in the discussion by multiple people, the movement speed is simply too much. It is incredibly gamey, everyone is zipping around like madmen, because the only alternative is to move at a snails pace. Literally.
### **There are RP implications** (This is not the focus of the PR, however)
The fact that continuously running around your department even for a couple of tiles sounds incredibly silly. I would love to leisurely walk around in my downtime, or leisurely walk to that computer over there, but I'm consistently stuck running at full speed like I drank *far* too much coffee in the morning or something.
### **It is easier to react to things.**
I am a cargo main. I move boxes. More often then not, we will get pushed, run into people, and otherwise lose our grip on our crates because someone came barreling in from off-screen or suddenly switched direction and we had no time to react. Not only does this make cargo as a whole easier, it has other reaction-based implications in many other areas of the game, aswell.

## Changelog
:cl:FIoppie
add: Movement intents are reworked. There is now sneaking, walking, and running. Sneaking takes the place of walking, walking is actual walking at a brisk pace, useful if you just need to get to that computer over there, and running is, well, running. Running costs stamina, but is ideal for getting from A to B around the station.
/:cl:

## TODO:
- Get a fucking design doc
- Really solidify the values for walking/running speeds. See if any increases should be added or not.
- Address the issues with miners
- Test and address possible issues with telebatons/stun batong
- Address the issues with how it plays into stun combat
- More stamina icon states
- Address several coder problems (namely sprinting in place taking stamina)
- Figure out why cant slip on banana???
- A billion more problems that need to be sorted out and concerns that need to be addressed

### CODE REVIEW

**Comment by RunKittenzRComing** [comment]
One of my primary concerns at the moment is that I was unable to figure out how to tell if a mob is actively moving, so at the moment, if you hold to run but don't move, you still take stamina damage. Would appreciate insight.

**Comment by Gary412** [comment]
No, keep this shit in TGMC, mood and hunger slows are terrible enough.

**Comment by GuillaumePrata** [comment]
Sneaking has the same speed as the previous walk?

I love the idea of the PR and hate how our melee combat is headless chicken jousting, but I think it might be a good idea to bump the no slip to walk instead of sneak.
Mostly for janitor reasons, telling people to sneak to not slip on puddles just sounds too weird and if the sneak speed is slower than our walk speed now, it will make playing Janitor without galoshes even more annoying.

This would hurt slip combat A LOT I assume, but if we are reworking combat to be more interesting by slowing it down and the swing combat added it, I think it is more than fair to remove easy slips from the equation and keep it mostly as a tool for when you are being chased.

**Comment by RunKittenzRComing** [comment]
> No, keep this shit in TGMC, mood and hunger slows are terrible enough. Spessmen are genetically modified to be extremely fast, the only hinderance to their speed being mood hunger and stuns, making spessmen go even slower makes stam crits easier, and is not good for the game at all.

I am not a TGMC player. This system, as far as I know, works fundamentally different.
Also, I don't mean this patronizing, do you actually eat? I don't remember the last time mood/hunger effected my speed outside of losing all of my limbs.

**Comment by RunKittenzRComing** [comment]
> Sneaking has the same speed as the previous walk?
> 
> I love the idea of the PR and hate how our melee combat is headless chicken jousting, but I think it might be a good idea to bump the no slip to walk instead of sneak. Mostly for janitor reasons, telling people to sneak to not slip on puddles just sounds too weird and if the sneak speed is slower than our walk speed now, it will make playing Janitor without galoshes even more annoying.
> 
> This would hurt slip combat A LOT I assume, but if we are reworking combat to be more interesting by slowing it down and the swing combat added it, I think it is more than fair to remove easy slips from the equation and keep it mostly as a tool for when you are being chased.

I agree with you there. I was worried about obliterating slipping as an inconvenience entirely, but I believe it *would* be within the restraints of this PR to make it a rare chance to slip, if any at all while walking.

**Comment by Mickyan** [comment]
Interesting, you should explain in the description how the controls for switching intents will work

As one of the pitfalls of old intents was that cycling through multiple states was very janky, ideally we wouldn't want to run into (heh) the same problem with this now that there is an extra state

**Comment by RunKittenzRComing** [comment]
> Interesting, you should explain in the description how the controls for switching intents will work
> 
> As one of the pitfalls of old intents was that cycling through multiple states was very janky, ideally we wouldn't want to run into (heh) the same problem with this now that there is an extra state

Alright, edited to include. How it would control was a major focus of mine, and I think splitting the move intent keybinds into 2 seperate cycle keybinds (cycling sneak/walk and cycling walk/run) is a decent solution.

**Review by san7890 — CHANGES_REQUESTED** [review]
Make a design document about this, I don't want to look at discord messages to piece together all your thoughts. Your thoughts in the PR body are a good starting point, but I need something really fleshed out with goals/anti-goals, future design direction, etc. This is because as the codebase involves, people will need to add onto this feature, and it is far easier to look at a design doc with all of the hot and nice bullet points rather than staring at a github pr body (and github pages tend to be really bulky on mobile especially as we inevitably give you 10000 review things to fix)

You can read about making one here: https://hackmd.io/@tgstation/BkzmU9EyK

**Comment by san7890** [comment]
also even though the swing combat PR is still vaporware i would greatly desire it if we were to give that a month or so to breathe before we burden players with more debuffs and the like

**Comment by DaydreamIQ** [comment]
I was personally never a fan of this system in TGMC (And yes it works pretty similarly where running uses up stamina) and I forsee this becoming a huge sec buff as people they're chasing will be forced to either move slowly and get caught up to with a baton, or run at full speed and be dropped in just a couple disabler shots by their pursuers

**Comment by optimumtact** [comment]
san if you're blocking PR's please apply the relevant labels.

**Comment by plutori** [comment]
I really do not like this change. It sounds good from an RP perspective, but I don't think anyone actually seriously wants to walk across the entire station.

I really think this is a case where the game should come before realism.

**Comment by SomeoneYouProbablyKnow** [comment]
Yay less crackhead speed is good no doubt. But
I don't see the point of sneak, most people would just crawl at this point and 3 options is a cycle when 2 options is a toggle.
Sprinting in combat might get very annoying, instead of slower fighting you might end up with people micro sprinting for speed boosts midcombat which might not be something we want.
Chases scenarios are gonna be overpowered by any group of 2 players who know how to pull each other and sprint in turns

**Comment by dieamond13** [comment]
I think it's a pretty good idea but since running uses stamina I feel it should be slightly faster than our current run speed. Maybe then it could use even slightly more stamina just since 2 laps around all of Meta is still a lot.

**Comment by ZeWaka** [comment]
lol called it

**Comment by RunKittenzRComing** [comment]
> I really do not like this change. It sounds good from an RP perspective, but I don't think anyone actually seriously wants to walk across the entire station.
> 
> I really think this is a case where the game should come before realism.

As stated in the PR, this is why running exists as actual running. It has the same speed as running does right now, and you can run 2 full laps around the primary hallway on metastation before running out of stamina.

Keep up with the concerns/suggestions, goofy of me to not write a design doc but I should be (ideally) responding to each concern in it when I do write it.

**Comment by optimumtact** [comment]
For a variety of reasons the default move speed is very controversial to edit, and you should not have changed it in this PR.

It can be adjusted very slowly over time to reduce the negative impact people associate with immedate changes in the movement speed.

If you intend to make this PR for the long term, I advise you not to modify the default movement speed itself, this means pinning your "walk" to run speed.

However this value can be adjusted after the fact, very slowly, by server administrators which reduces the negative connotations people associate with it.

So this would work better as a two step situation, but you will need to get headadmins on board for such changes.

**Comment by MrMelbert** [comment]
> i would greatly desire it if we were to give that a month or so to breathe before we burden players with more debuffs

For the record I would be interested in seeing this before Swing is done because I think this can be a great benefit to Swing by lowering the pacing (we experimented with lowering movespeed last test)

**Comment by IndieanaJones** [comment]
Also, is the common concenus about speed being too high only with regards to using chems? Or also in regards to the normal speed people move? Because I can agree chem speed can be awful, but a lot of things about chems are awful. And, if sprinting under the proposed PR has faster sprinting than our current run, and you could do it for 2.5 laps around meta, wouldn't this be worse for people who think we move too fast currently?

**Comment by san7890** [comment]
> san if you're blocking PR's please apply the relevant labels.

I was under the presumption of "Design Doc Needed" being some sort of warning label to other maintainers. I have not yet made my mind up yet on blocking this PR once a design document has been made.

**Comment by RunKittenzRComing** [comment]
> Is this supposed common concenus about speed being too high only with regards to using chems? Or also in regards to the normal speed people move? Because I can agree chem speed can be awful, but a lot of things about chems are awful. And, if sprinting under the proposed PR has faster sprinting than our current run, and you could do it for 2.5 laps around meta, wouldn't this be worse for people who think we move too fast currently?

Sprinting is not faster then our current run, as it stands in the PR.

**Comment by Namwty** [comment]
Might want to take a look at mining and what not, this might be rather big impact when it comes to fighting megafaunas.

**Comment by RunKittenzRComing** [comment]
> Might want to take a look at mining and what not, this might be rather big impact when it comes to fighting megafaunas.

Mining is on my to-do. Someone mentioned saying something under the lines of "Indecipheres has lower gravity then normal" and thus would give miners/anyone on lavaland exception from stamina drain. Something to think about.

**Comment by Wallemations** [comment]
If you're going to tie movement that heavily to stamina then the stamina bar will need more than just the 8 icon states it has at the moment, since in the vid it barely looks like it moved

**Comment by RunKittenzRComing** [comment]
> If you're going to tie movement that heavily to stamina then the stamina bar will need more than just the 8 icon states it has at the moment, since in the vid it barely looks like it moved

I do agree it needs more icon states. I'll add that to my to-do.

**Comment by RunKittenzRComing** [comment]
I really wish I could post on the forum to talk about the discussion happening there, but alas, I am not cool yet (apparently).

Overall, this PR mostly resulted from encouragement in the discord to give "goon sprint" a shot (even though I hate calling it that), but after discussing this with so many people and hearing many different POVs on the PR I'm closing this and redoing it as a whole as more of an extra option with no extreme functional difference like as the PR stands right now. 

While I still whole-heartedly think that TG runspeed is too fast, throwing in stamina drain to the mix is *not* the solution to this problem, atleast in my context. Doing that not only requires fundamentally reworking the movement system as a whole, it requires fundamental changes to how the *entire game is balanced*. Due to the sheer number of points that needs to be addressed, this PR is out of my scope and is getting closed.

I went from a goofy moth PR to something that fundamentally changes the game, and I don't think I'm ready for something so monumentally extreme like this, either.

Expect a new PR in the future that should be less controversial and significantly less game-impacting, and actually have a design doc like something like this should. Sneak, walk, run will exist, but running will be default and walking will be there for flavor. I feel like it has reason enough in itself, which will be explained further in the design doc further down the road.

Thanks guys, and see you soon!

**Comment by EuclidianGeometer** [comment]
It's definitely a ton of work, but i still think the core idea of this PR is good and *should* be gone through with, if you feel up to it in the future.

**Comment by Xackii** [comment]
Nobody forbids you to walk if you don’t want to look like a person who drank a lot of coffee.

**Comment by EricZilla** [comment]
If we are going to a 3 speed system, I'd rather go with the Walk is the same, run is decreases somewhat but costs no stamina, and having a option to dash by holding shift that is just a bit faster than current runs peed.

Having going below 50 Stam ALSO put you at Walk speed is brutal

**Pull request closed without merging**
