### PR TITLE
Makes earmuffs and null rods protect from Voice of God, adds earmuffs to autolathe

### LINKED ISSUE #22785: Cultists/Servants don't get the fancy text from the Voice Of God
As in, I used it as a servant and my text wasn't fancy and ratvar-y, it might fix itself when used a second time but I wasn't able to test as the round ended.

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Earmuffs and null rods protect against the Voice of God.
add: Earmuffs are now buildable in autolathes.
tweak: Voice of God stuns have a longer cooldown.
/:cl:

Also adds some logging to both admins and the log when VoG is used.

Fixes #22785.

Reason: I've been told that it makes murderboning really easy since it lets you deal the first stun in a fight against security, after which you can simply stun them with a taser or baton to win the fight. This adds a couple counters beyond deafening yourself.

### CODE REVIEW

**Comment by Arianya** [comment]
Personally I'd think putting protection on a item that requires you remove your headset (earplugs?) would still make an effective counter without making the Voice of God near-pointless against sec/HoS/Captain

Also, in the eventuality that someone has obtained a VoG (a boss item from killing collosus) and another assured stun (tazer, baton, etc), shouldn't they, from a balance point of view, have the upper hand as they've gone through greater preparation compared to the sec officer who only has the tazer/baton/etc?

**Comment by RemieRichards** [comment]
yeah it should be ear protection (like the ear muffs in engineering) instead of mindshields.

**Comment by GunHog** [comment]
Ear protection and null rod, perhaps? The chaplain does not bow to any god except his own!

**Comment by SweaterKittens** [comment]
Mindshields is perfectly fine as it makes Voice of God a fun and interesting reward with unique mechanics instead of another badmin-tier weapon to murderbone the station with. Mining rewards are overpowered as is, they don't need an AOE uncounterable KO on top of all the other bullshit they inevitably dredge up. I think this is excellent as is.

**Comment by improvedname** [comment]
Yeah make earnuffs prevent the effect but you still should be able to hear what they (in tiny size)) since the voice is loud rite?

**Comment by XDTM** [comment]
Earmuffs were definitely intended to protect from this, but if they don't deafen then i'll have to fix that as well.

**Comment by XDTM** [comment]
Earmuffs now properly protect from VoG

**Comment by SweaterKittens** [comment]
I was going to say that making earmuffs so easily accessible would be a nerf to flashbangs and a buff to team antags like rev and cult - but I'm realizing that they take your ear slot so you're sacrificing comms for it, which seems like a reasonable trade-off to me.

**Comment by Hatfish** [comment]
Couldn't you just add the same protection to bowman headsets?

**Comment by XDTM** [comment]
Anyone who starts with an implant starts with a bowman headset, so it wouldn't be very different in distribution.

**Comment by RemieRichards** [comment]
you should make a pre filtered list, and loop that.
saves adding the boilerplate to every single command word.

**Comment by XDTM** [comment]
I am doing that already on generic filters like deafness, but i want mindshielded people to only resist a few commands, not all of them.

**Comment by Arianya** [comment]
@SweaterKittens The flashbang concern might be still relevant for cult, since they have a non-headset form of communication, but as I recall its the flash of the flashbang that causes the stun/knockdown, not the bang, right?

**Comment by XDTM** [comment]
Both, actually. And clockcult has flash-protection goggles, which would give flashbang immunity.

**Comment by Arianya** [comment]
I think things still even out if earmuffs give "deafness", but admittedly I only say that because I prefer this idea to "anyone with a mindshield"

**Comment by GunHog** [comment]
I guess that is a "No" on the null rod suggestion?

**Comment by XDTM** [comment]
Me too, honestly. Also i guess i can throw in the null rod immunity, after all it protects against false gods already.

**Comment by XDTM** [comment]
No more mindshield, earmuffs are buildable, null rods protect.

**Comment by Arianya** [comment]
Earmuffs are total protection yes? Or just diminished effectiveness noted above?

**Comment by XDTM** [comment]
Total and absolute.

**Comment by KorPhaeron** [comment]
Should probably just remove SLEEP

Also while this is a feature it is balancing for something that was added as the freeze started, so I think tweaking should be allowed in this case

**Comment by Arianya** [comment]
@XDTM Remember to edit your changelog

**Comment by XDTM** [comment]
Changelog already edited, don't worry, also thanks Kor

**Comment by Arianya** [comment]
My bad, didn't refresh and github doesn't update edited posts on the fly. 🦆

**Comment by Firecage** [comment]
The Null Rod makes 110% sense.

**Comment by bgobandit** [comment]
finally, earmuffs are not total shit

**Comment by XDTM** [comment]
Sunglasses + earmuffs are already ghetto flashbang protection, so they are at least worth something.

**Comment by Kromgar** [comment]
>mfw cult can now protect itself from flashbangs 


glory be

**Comment by XDTM** [comment]
Now? Always been like that, @Kromgar

**Comment by XDTM** [comment]
I added logging to VoG. It shows the user, the message, the affected listeners and the multiplier, but not exactly what effet took place. Still, it's something.

**Comment by XDTM** [comment]
Bundled in a fix for narsie and ratvar spans when speaking as a cultist.

**Pull request merged**
