### PR TITLE
New Table Sprites!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
The ride never ends, keep yourself buckled!

**IN THIS PR**, tables including:
- Metal
- Reinforced
- Reinforced Glass
- Reinforced Plasmaglass
- Titanium Glass
- Plastitanium Glass
- Greyscale
- Glass
- Plasma Glass
- Wood
- Poker

Have been entirely redone, including their respective table frames!
image
image
image
image

Of course, merely a few thunderdome screenshots are not good enough for someone to appreciate the new aesthetics, so...

<details><summary>I've compiled a series of screenshots of DeltaStation with those tables featured in them!</summary>
<p>

image
image
image
image
image
image
image

</p>
</details>

Credits to: @TripleZeta and @SomeAngryMiner for helping me with the metal and reinforced tables.

## Why It's Good For The Game
Me and Twaticus have agreed, that in retrospect, the Sunset Station tables we've ported were not up to the standards we want to head towards. Still a long road ahead, chairs for instance are something that truly gives me conniptions, but we're getting on the right track!

## Changelog

:cl: PositiveEntropy, TetraZeta, Azlan
imageadd: Metal, Reinforced, Reinforced Glass, Plasmaglass, Reinforced Plasmaglass, Titanium Glass, Plastitanium Glass, Wood and Poker tables have been updated!
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
are we going to have really really long tables with only 4 legs that somehow magically withstand being 3x3

**Comment by CRITAWAKETS** [comment]
Is it normal for the iron tables to be rounded in the south but sharp on the north?

**Comment by Imaginos16** [comment]
> Is it normal for the iron tables to be rounded in the south but sharp on the north?

Yeah that was a small error, simple fix.

**Comment by Imaginos16** [comment]
> are we going to have really really long tables with only 4 legs that somehow magically withstand being 3x3

Its a perspective thing. You could test it out later and it looks pretty fine since I accounted for that.

**Comment by Imaginos16** [comment]
Main picture appropriately updated to reflect recent tweaks.

**Comment by GoldenAlpharex** [comment]
The sprites are very nice, although I feel like the corners are too sharp. It's one of the few things that I think gave some polish to the older sprites, and are why the wood tables look better than the rest.

**Comment by Fikou** [comment]
not a fan of the lighter color

**Comment by CRITAWAKETS** [comment]
Personally I feel as if the reinforced table is lacking some more "central" top detail, and the glass window's shine effect needs tweaking, especially with the lack of paler outlines at the ends of it.

**Comment by zxaber** [comment]
I dunno, looks way more top-down than 3/4 perspective. Unless the tables are like really short.

Maybe there's nothing that can be done about it.

**Comment by timothymtorres** [comment]
This look really nice +1

**Comment by SuperSlayer0** [comment]
How do sole tables look like?

**Comment by Imaginos16** [comment]
> I dunno, looks way more top-down than 3/4 perspective. Unless the tables are like really short.
> 
> Maybe there's nothing that can be done about it.

They're about the same if not slightly taller than the previous tables. Its more so an issue with sizes really. I made it 4x4 tiles on the screenshot so people could see the tables meshz

**Comment by Imaginos16** [comment]
> How do sole tables look like?

I'll include a photo with that later.

**Comment by Mooshimi** [comment]
please show the reinforced tables, like reinforced glass and plasma, and mineral tables not pictured, ie diamond/titanium/plastitanium

**Comment by Imaginos16** [comment]
> please show the reinforced tables, like reinforced glass and plasma, and mineral tables not pictured, ie diamond/titanium/plastitanium

Reinforced glass table types were not changes.

The yellow table is a gold table, AKA a mineral table, same with the meat table. I did not want to do a bunch of other ones when in their essence is effectively a color filter over a greyscaled table.

**Comment by Mooshimi** [comment]
> > please show the reinforced tables, like reinforced glass and plasma, and mineral tables not pictured, ie diamond/titanium/plastitanium
> 
> Reinforced glass table types were not changed.
> 
> The yellow table is a gold table, AKA a mineral table, same with the meat table. I did not want to do a bunch of other ones when in their essence is effectively a color filter over a greyscaled table.

i think this may look a bit janky if you don't do all the tables in the same style, including reinforced glass

**Comment by Imaginos16** [comment]
> > > please show the reinforced tables, like reinforced glass and plasma, and mineral tables not pictured, ie diamond/titanium/plastitanium
> > 
> > 
> > Reinforced glass table types were not changed.
> > The yellow table is a gold table, AKA a mineral table, same with the meat table. I did not want to do a bunch of other ones when in their essence is effectively a color filter over a greyscaled table.
> 
> i think this may look a bit janky if you don't do all the tables in the same style, including reinforced glass

You know what? You right. Give me a bit.

**Pull request merged**
