### PR TITLE
Fix bundle: borg module, thermite, chairs

### LINKED ISSUE #16744: Thermite continues to melt a wall forever.
-Pour Thermite on a wall and light it on fire

-Watch how the wall continues to burn despite the model being melted under the hotspot

-Can't walk through it

### PR DESCRIPTION
**Pull request by phil235**
- Fixes runtime when thermiting a wall. Fixes #16744
- Fixes not being able to put down a chair on a tile with a border window.
- Fixes Borg module cycling not working when the first module is empty.

### CODE REVIEW

**Comment by LatD** [comment]
Does the thermite change fix  #16744 too?

**Comment by phil235** [comment]
Yes, I'll add that to the OP.

**Comment by Razharas** [comment]
SEPARATION BETWEEN NON_ATOMIC PRS AND MERGE IS ABSOLUTE

**Comment by Cheridan** [comment]
bug bundles are ok

**Pull request merged**
