### PR TITLE
Adds an overlay indicator to venting

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

pic1

## Why It's Good For The Game

I think the action didn't have enough clarity, and this telegraphs the action much better to other players.

## Changelog

:cl:
balance: Venting now has an indicator
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Sus.

**Comment by Moltovz** [comment]
Sus.

**Review by Mothblocks — APPROVED** [review]
looks nice

**Comment by SuperNovaa41** [comment]
I think this would be better if you just confined it to be within the vent sprite, this looks a little obtrusive

**Comment by theOOZ** [comment]
> I think this would be better if you just confined it to be within the vent sprite, this looks a little obtrusive

I made it a little obtrusive or obvious because on the downstream it should be like a combat indicator, as an antagonist venting while officers are chasing or holding them greenlights a mechanical combat state.

**Comment by Mothblocks** [comment]
...who are you quoting?

**Comment by theOOZ** [comment]
> ...who are you quoting?

SuperNovaa who had deleted their comment

**Comment by Mothblocks** [comment]
@SuperNovaa41 😠

**Comment by SuperNovaa41** [comment]
> @SuperNovaa41 😠

😄 (i misread what the purpose of this overlay was for and gave a meaningless comment)

**Pull request merged**
