### PR TITLE
Wizard's Deja Vu tweaks

### LINKED ISSUE #85737: Wizards can Deja Vu back to their ship.
## Issue Summary

Wizards can return back to their ship using the Deja Vu park.

## Round ID:
Tested locally only
## Reproduction:

1. Buy the Deja Vu perk.
2. Buy something to break engines with. (Only fireballs/lesser summon guns work, none of the melee weapons do enough damage to actually damage them)
3. Break an engine and step 1 tile into hyperspace.
4. You're now in a different area (not `/area/centcom/wizard_station`), so Deja Vu activates and records that location.
5. From now on, every 60 seconds you will be teleported back to your ship and fully healed.

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request
Deja Vu perk now blacklists all centcom areas, not just the ship itself. It also now teleports you to where you were before the teleport, instead of teleporting you to the same spot every time.

Closes #85737

## Why It's Good For The Game

In its current implementation it makes you borderline immortal as it stores your health, but also makes it impossible to escape the station as you will be teleported to where you first arrived on the station, stealing your greentext. This way its gives the player a more balanced, but riskier experience

## Changelog
:cl:
balance: Deja Vu perk now teleports you to where you were before the last teleport, instead of where you arrived on the station
fix: Deja Vu can no longer be used to return to the wizard ship
/:cl:

### CODE REVIEW

**Comment by YesterdaysPromise** [comment]
Feels a bit against the idea of the gimmick?

**Comment by SmArtKar** [comment]
> Feels a bit against the idea of the gimmick?

I mean, the description says "Every 60 seconds, teleport back to where you were 60 seconds ago", right now its "Every 60 seconds, teleport to where you were when you TPd to the station" I'd say its actually far more fitting

**Comment by Exester509** [comment]
Ah, so this is what it was intended to be. I assume now it works something like this?
1. Buy the perk at wizard's den
2. Teleport to the station, state 1 saved
3. 60 seconds pass, state 2 saved
4. Go back to state 1
5. 60 seconds, state 3 saved and go back to state 2...

This is much more interesting than a permanent anchor you'll keep returning to

**Comment by SmArtKar** [comment]
> Ah, so this is what it was intended to be. I assume now it works something like this?
> 
>     1. Buy the perk at wizard's den
> 
>     2. Teleport to the station, state 1 saved
> 
>     3. 60 seconds pass, state 2 saved
> 
>     4. Go back to state 1
> 
>     5. 60 seconds, state 3 saved and go back to state 2...
> 
> 
> This is much more interesting than a permanent anchor you'll keep returning to

yeah now its pretty much that

**Pull request merged**
