### PR TITLE
Silicons can toggle open state of shutters and blast doors by clicking them

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
title 
## Why It's Good For The Game
- since they can do it to airlocks, why not shutters and blast doors?
- more possibilities for silicons to kill people
## Changelog
:cl: grungussuss
add: Silicons can now remotely close or open shutters and blast doors by clicking on them.
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
How does this work with buttons? Does this mean that silicons can permanently (until another silly cone fixes them) put some shutters or blast door out of sync with others?

**Comment by githubuser4141** [comment]
Isn't the whole point of blast doors and shutters that they are only controlled by a hard wired connection? And since we don't have actual wires, it's a wifi link. But it's still attached to a physical button. Therefore disconnecting the button prevents a silicon from being able to open/close it. This is just completely removing that.

**Comment by moocowswag** [comment]
Airlocks have an ai wire that can be disabled, blast doors and shutters only respond to a single type of signal from a blast door controller.

they are simply explicitly to prevent being subverted, no interface to hack, no other signals to listen for.

**Comment by xzero314** [comment]
Cool change. Cool to see Sillicons get more things inline with being connected to all the stations devices

**Comment by SomeoneYouProbablyKnow** [comment]
Yea blast doors are blast doors. It's annoying whem you see em and crew loves shutting them down for no reason but... that's the point. Letting borgs just open em for no reason is iffy

**Comment by Sadboysuss** [comment]
okay

**Comment by moocowswag** [comment]
> How does this work with buttons? Does this mean that silicons can permanently (until another silly cone fixes them) put some shutters or blast door out of sync with others?

If there are blast doors or shutters out of sync, the next activation will have only some of them toggled and automatically resync them.

**Pull request closed without merging**
