### PR TITLE
Icebox Radstorm Fix and Service Hallway QoL

### LINKED ISSUE #62756: Icebox Lower Service Floor Door to the Outside does not follow proper convention for going outside, and does not signpost that it goes outside at all
Discord_jvYhdPVdV9
People die all the time because they go through this thinking it's a normal internal airlock and then accidentally let 15 wolves and other assorted megafauna into the hallway.

### LINKED ISSUE #63441: Radiation storms on Icebox irradiate the entire second level
## Testmerges:
The following pull requests are currently test merged:
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1

## Reproduction:
Go out into the snow on icebox's 3rd or first level during a radiation storm
you're fine
go out into the snow on icebox's 2nd level during a rad storm
everything is green

the area of snow directly outside botany on the second level is fine for whatever reason, but the little maint area in the public mining outpost isn't rad protected

### PR DESCRIPTION
**Pull request by MassacreDemigirl**
## About The Pull Request
Makes the Icemoon Underground Area immune to Radstorm event due to it being a Station Z Level thus cooking Miners alive. Paints a maints area in 2nd level mining to actually provide radstorm prodection.
Makes the service hallway exit into a proper cycled and marked exit to outside. 
icemoonmaint
icemoonexit

## Why It's Good For The Game
Closes #63441 and closes #62756

Miners not getting turned into microwavable meals in Second Level Mines is pretty good.
So is preventing the janitor/clown/cook let the entire icemoon fauna inside is ok-ish.

## Changelog

:cl:
fix: Makes the IceBoxStation Underground (Level 2) wastes immune to radiation and also paints the maintenance as such to let you take shelter.
qol: Makes the IceBoxStation Service Hall Exit into a properly cycled airlock system.
/:cl:

### CODE REVIEW

**Review by Maurukas — CHANGES_REQUESTED** [review]
Please add an APC to the area. There's a borg charger in this area that was previously pulling from the mining production APC. As it stands this has infinite power.

This area also contains atmos vents which were previously under the control of mining production air alarm. Please remove those as well.

**Comment by ErdinyoBarboza** [comment]
something has gone terribly wrong here

**Comment by LemonInTheDark** [comment]
you ok there?

**Comment by ErdinyoBarboza** [comment]
@LemonInTheDark i have no idea what github did.
sorry for mass requesting entire maintainer base

**Pull request closed without merging**
