### PR TITLE
Ports a lot of baymed concepts from bay [DNM]

### PR DESCRIPTION
**Pull request by optimumtact**
as a meme for retards

### CODE REVIEW

**Comment by Aranclanos** [comment]
322 memes

**Comment by optimumtact** [comment]
Actually DMN, I'm gonna make how the retardation messages stuff works.

**Comment by swankcookie** [comment]
:+1:

**Comment by Cheridan** [comment]
isn't PORT BAYMED already a retardation quote?

**Comment by optimumtact** [comment]
lol it is

Don't worry, I'm still gonna refactor the gibbering

**Comment by Dorsisdwarf** [comment]
Oranges your memes are getting so unsubtle they're actually bad now.

**Comment by Aranclanos** [comment]
I don't know

**Comment by optimumtact** [comment]
I haven't finished my overhaul aran

**Comment by Aranclanos** [comment]
i just don't know

**Pull request closed without merging**
