### PR TITLE
Makes viruses varedit friendly

### PR DESCRIPTION
**Pull request by AnturK**
Makes the viruses copy their properties over on spread.

### CODE REVIEW

**Comment by palpatine213** [comment]
:+1: Thank you so much!

**Comment by Iamgoofball** [comment]
remember to remove viruses from the "varedit blocked" list then

**Comment by Stickymayhem** [comment]
God yes

**Comment by palpatine213** [comment]
Viruses are on varedit blocked? As a trialmin I can edit them just fine

**Comment by Miauw62** [comment]
Would probably be better to copy over all vars using the vars list and add exceptions for holder and affected_mob.

**Comment by phil235** [comment]
Yeah, it's a bit ugly tbh.

**Comment by AnturK** [comment]
Sure,  can switch this around.  Wanted to make it explicit.

**Pull request merged**
