### PR TITLE
Removes Shotgun Ability

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
#49990 was originally supposed to include shotgunning canned beverages by piercing them so you could chug them super quick, but I ended up axing that part of the PR. Apparently, the code never got the memo that it got axed, so this finishes that job

## Why It's Good For The Game
Shotgunning wasn't supposed to be added and is not at all balanced or properly done

## Changelog
:cl: Ryll/Shaps
del: You can no longer shotgun canned beverages
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1: extremely un bro like, dude

i am like, straight up not having a good time right now

low key, I'm kinda tripping about this

**Comment by Ryll-Ryll** [comment]
broh

**Comment by Doosteroni** [comment]
Aw man, I enjoyed doing this until I fucked with my nanites and died. I mean, it isn't THAT bad (aside from the fact a few cans can be a lethal weapon). But I dunno much about it except I drained an entire soda machine chugging colas one round.

**Comment by necromanceranne** [comment]
**CHUG**

**Comment by TheVekter** [comment]
bull fuckin' shit

**Comment by boodaliboo** [comment]
dumb stupid pr i like drinks

**Comment by ArcaneDefence** [comment]
While I love the spirit of what's being removed, it's unfortunately jank. You can smother people in public with little indication of what's happening, using breath loss, which is an obnoxious to treat condition.
You can be killed because someone held a pierced soda can filled with a fluid in your general direction. 

If people really wanna keep it there's issues to deal with.

**Pull request merged**
