### PR TITLE
blacklists grilles from tesla

### PR DESCRIPTION
**Pull request by PKPenguin321**
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=30&view=unread#p246958

### CODE REVIEW

**Comment by Cyberboss** [comment]
Booooooooooo :-1:

**Comment by Kromgar** [comment]
So... why does the tesla have a propensity for always going east? 

Every map box, delta, and meta the thing always go as far east as it possibly

**Comment by PKPenguin321** [comment]
@Kromgar see https://github.com/tgstation/tgstation/issues/21092#issuecomment-255231403

**Comment by PKPenguin321** [comment]
:thinking:

**Comment by PKPenguin321** [comment]
This can be merged if you guys wanna unclog the PR tracker a bit

**Pull request merged**
