### PR TITLE
Grill plate (teppanyaki table)

### PR DESCRIPTION
**Pull request by MTandi**
image

## About The Pull Request

PR adds a subtype of griddle that can be placed on top of tables.

image

## Why It's Good For The Game

For situations when you want to have a griddle facing north or if you want to make a teppanyaki style restaurant.

## Changelog

:cl:
add: Added tabletop griddle variant 
/:cl:

### CODE REVIEW

**Comment by Mey-Ha-Zah** [comment]
Oh thats cool and immersive.
Now the better question is, do we have chopsticks to hold food and dipping bowls?

**Comment by MTandi** [comment]
> Oh thats cool and immersive. Now the better question is, do we have chopsticks to hold food and dipping bowls?

That's sarcasm? You think it's and unneeded shit?

**Comment by Sealed101** [comment]
bro chill it ain't sarcasm

**Comment by MTandi** [comment]
> bro chill it ain't sarcasm

The thing is that I myself think it's shit and I should've explored smoothing groups for regular griddle instead of this.

**Comment by EricZilla** [comment]
That's a shame I quite like this

**Pull request closed without merging**
