### PR TITLE
Cleans up leftover Hand of God gamemode references

### PR DESCRIPTION
**Pull request by ShizCalev**
Cleans up some code leftover from a gamemode that got removed.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@ExcessiveUseOfCobblestone btfo

**Comment by AnonymousNow** [comment]
Would we consider future redevelopment of this gamemode?

**Comment by Iamgoofball** [comment]
not in current /tg/ playerbase

**Comment by Kerbin-Fiber** [comment]
I thought Arm was reworking this and making it different.

**Comment by ExcessiveUseOfCobblestone** [comment]
@KorPhaeron AHHHHHHHHHHHHHHHHHH

**Comment by Armhulen** [comment]
@Kerbin-Fiber very funny

**Review by Cyberboss — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
oh that means i have to darn.

**Comment by ExcessiveUseOfCobblestone** [comment]
is removing the best gamemode remnants REALLY code improvement???

**Comment by ShizCalev** [comment]
Savage

**Pull request merged**
