### PR TITLE
Adds IRC smites

### PR DESCRIPTION
**Pull request by Cyberboss**
:^)

:cl:
admin: You can now smite players from your admin chat. Players beware...
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
remote badmin

**Comment by Hatfish** [comment]
someday we will advance to the point where admins have a bot to autosmite ahelpers so they never even have to log on to the game.

**Comment by lzimann** [comment]
Admins being able to do this from irc is stupid, punishing people without even entering the game will only lead to situations where everyone is annoyed.

**Comment by kevinz000** [comment]
lzimann has a point
sdqls from irc when?

**Comment by Iamgoofball** [comment]
@kevinz000 should be fairly easy

**Comment by Qbopper** [comment]
@Hatfish you're onto something my dude

**Comment by Iamgoofball** [comment]
Sdqls are just a string right

**Comment by Shadowlight213** [comment]
Does this mean I can revive my pr allowing triggering events from irc? :^)

**Comment by KorPhaeron** [comment]
I think this is a bad idea to let people who may not even log into the game anymore randomly kill players and will be closing it unless arm and ausops both vote yes for it

**Comment by Ausops** [comment]
<ausops> i don't think there would ever be a legit use for
<ausops> there is no ahelp i have ever seen bad enough to require it that i also want to be lazy in giving negative attention and reinforcement to

**Comment by KorPhaeron** [comment]
2/3 headmins say no, sorry gamer

**Pull request closed without merging**
