### PR TITLE
New hood/hardsuit helmet system

### PR DESCRIPTION
**Pull request by ghost**
HARDSUITS: including engineering/CE/atmos/sec/mining/med/wizard will require you to wear the suit before equipping the helmet, which is stored inside the suit.

tumblr_m7ht0tdpol1qgfw5eo1_400

This is also how the winter coat hoods and the chaplain's hoodie works, and it will work for future casual hoodies if someone wants to make them. Big pathing change.

**HOLY SHIT THIS PR NERFS SHIT PAY ATTENTION**
EVA storage space suits have a new path: space/eva. They are lighter weight than hardsuits now, which allow you to move faster in them, but their helmets do not have flash or welding protection and do not hide your identity as they did previously. They also have less rad protection than they did before.

Old space suits are now the parent space suits again if someone wanted to spawn them for muh nostalgia. They still have flash protection and welding protection.

Gone are the days of powergaming by running around wearing just helmets, rejoice, based paprika grudge nerfing everything, etc.

### CODE REVIEW

**Comment by Blopster** [comment]
Awesome gif
But please make it look as nice as nookawps.
So is it gonna be like nookawps thing where you click on a HUD icon?

**Comment by CocaneStyle** [comment]
Space helmets should function as gas masks for internals if they don't already.

**Comment by RemieRichards** [comment]
You didn't commit ```code\modules\clothing\suits\toggles.dm```

**Comment by paprka** [comment]
Sorry.

**Comment by Fox-McCloud** [comment]
:+1:

I'd suggest re-allowing hardsuits (perhaps all space suits) to hold large tanks with this.

**Comment by Chocobro** [comment]
:+1:
bonus points if there's a neat animation to it

**Comment by dannno** [comment]
tight as fuck, sick animation would make it perfect :+1:

>I'd suggest re-allowing hardsuits (perhaps all space suits) to hold large tanks with this.

at least for miners, for the love of god montresor

**Comment by AnonymousNow** [comment]
I second the fixing of the oxygen tank storage nerf.

Also, when you say the old spacesuits, do you mean the chunky suits or the version of spacesuits we have now, before this PR?

**Comment by dannno** [comment]
The baggy ass space suits I think.

**Comment by paprka** [comment]
yeah the parent space suits (suit/space) are the old style fat baggy nasa ones. However, the EVA space suits, basically light weight ones for emergencies (which is what we have now are (suit/space/eva) and their helmets don't have flash protection or welding protection so space suits are only used for space and not le welding visor with no downside!!

**Comment by RandomMarine** [comment]
paprka, have you tested if this affects goliath hide plating on the helmets?

**Comment by RemieRichards** [comment]
@RandomMarine from a read of Paprika's code if you upgrade your helmet and then toggle it back into the suit, it is still the exact same helmet object so it retains it's upgrades.

**Comment by Anonus** [comment]
THE INFAMOUS PAPRIKA STRIKES AGAIN
people will hate this but it's good and necessary
:+1:

**Comment by dannno** [comment]
I don't even think people will really hate this that much, it's good as fuck

**Comment by paprka** [comment]
Also keep in mind helmets cannot be stripped. I might raise the strip delay on hardsuits a bit, but we'll see.

**Comment by Kromgar** [comment]
Yeah... why would anyone hate this exactly? And i usually hate the shit Pap does

**Comment by GunHog** [comment]
Because it IS a nerf (you cannot have the helmet without the suit), but a nerf wrapped in the coolness of Dead Space.

**Comment by Deantwo** [comment]
They can just use gas masks instead.
Or stop taking their suit off to get out the movement penalty.

**Comment by dannno** [comment]
>Because it IS a nerf (you cannot have the helmet without the suit)

an extremely good nerf that I find it very difficult to argue against.

**Comment by paprka** [comment]
well the EVA suits being nerfed arguably might be a bad idea but I want to see how it turns out

I'd really like it if EVA had a lot more suits, but they're very baseline 'space' suits with no special features. Space is a little more deadly now to people without suits or chemicals so EVA really needs to be the 'no hardsuits left' or the 'HOLY FUCK EVERYTHING IS BOMBED' area of the station. I don't want space suits in EVA to be appealing for their powergame flash/welding protection, because it's less of a big deal if people take them during emergencies and stuff when they aren't as valuable.

That said, they do move slightly faster than hardsuits since they aren't uparmored and all that, so we'll see how things turn out ingame. If i need to make them the same speed as hardsuits are I will, but I really want to see how a low-weight space suit with next to no other advantages will turn out in game.

**Comment by Fox-McCloud** [comment]
Technically speaking, doesn't Captain's suit and the NASA void suit now need to be children of the EVA suit to avoid the same exact powergamy behavior? It's rather trivial to get a VOID suit and wear just the helmet---Cap's suit, I can understand being the way it is, seeing as there's only one and in the possession of someone who can't be antag/is loyalty implanted/already has flash protection.

**Comment by paprka** [comment]
the cap's suit and the void suit aren't in such giant numbers.

**Comment by paprka** [comment]
Fixed some conflicts here

**Comment by Fox-McCloud** [comment]
Fair enough, I figured that's the reason; I do generally agree with your assessment of making these more common--there's really not too much powergamy benefits to wearing an EVA suit 24/7 other than virus protection and a potential breach, especially since it still slows you down.

I'd still suggest that all space suits (RIG, regular, and EVA) all be allowed to hold large tanks now.

**Comment by paprka** [comment]
i'm not doing that in this PR

**Comment by Fox-McCloud** [comment]
@paprka 

Fair enough!

**Comment by dannno** [comment]
God I hope someone makes animations for these, I would bust my nut

**Comment by Chocobro** [comment]
i'll try and fuck around with the hardsuit sprite today, see if I can get anything good

**Comment by TZK13** [comment]
The blood-red hardsuit needs to be fixed, because it's a child of the engie hardsuit when you toggle it you get the engie hardsuit's helmet instead of the syndie exclusive functionality intended for it. I also got a runtime error when I used the toggle on the blood-red hardsuit helmet by itself.

**Comment by paprka** [comment]
Oh, good find. I thought I fixed the syndicate hardsuit so it doesn't do that. I'll test it again.

Don't merge this until then please.

**Comment by paprka** [comment]
Fixed the bugs with the syndicate hardsuit. Also removed the medical hardsuit helmets on z3.

Medical hardsuits don't conceal your identity anymore nor do they provide flash/welding protection, but they move faster than any other hardsuit, much like the EVA suit.

**Comment by paprka** [comment]
This is really ready to go now by the way

**Comment by Chocobro** [comment]
couldn't get an animation to look good, in any direction. if somebody wants this animated in the future they're gonna have to ask someone more skilled like WJ. sozzle!!!!!!!!!!!!

**Comment by GunHog** [comment]
To be honest, this should not be merged without an animation, else this PR is not cool enough to justify the nerf aspect of it.

**Comment by Deantwo** [comment]
How much of an animation are you expecting anyway? I mean have you looked at how small most of SS13's sprites are?
So unless it is a really really slow animation I don't see it mattering much.

**Comment by Miauw62** [comment]
or maybe its a one piece suit

**Comment by TZK13** [comment]
It's fine without an animation, it comes with a neat sound.

**Comment by dannno** [comment]
It's completely fine without animation, it's a cool feature, merge this shet
animation in the future would be banging though

**Comment by dannno** [comment]
why is not merge

**Comment by Miauw62** [comment]
i literally didn't test this.

**Comment by Steelpoint** [comment]
I would do a animation sprite, though I have no idea how to get it to play on the mob without it replacing the current helmet sprite.

**Comment by paprka** [comment]
I could do that

**Pull request merged**
