### PR TITLE
Glowshrooms have a less saturated glow

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Glowshrooms now have a less saturated glow.
/:cl:

Closes #27201
Old:

New:

### CODE REVIEW

**Comment by TrustyGun** [comment]
Perhaps even less saturated?

Either way 👍❌💯

**Comment by ChangelingRain** [comment]
If it needs to be even less saturated, I have

**Comment by lzimann** [comment]
Still makes your screen/game look really bad.

**Comment by Dorsisdwarf** [comment]
If we're gonna have glowshrooms glow, it should be that last one instead of looking like botany's hit you with Jarate

**Review by Cyberboss — APPROVED** [review]

**Comment by Iatots** [comment]
It's free light.

**Pull request merged**
