### PR TITLE
Bitrunning "Clown Planet" Mission Fix

### PR DESCRIPTION
**Pull request by Singul0**
## About The Pull Request
I hate this ruin with passion. HOW ARE YOU SUPPOSED TO DO IT WITHOUT A CROWBAR?!? but I digress. this fixes runtimes when the code tried to spawn pre-/basic/ clown typepath and missing baseturf. you can't space the VDOM with mining bananium anymore
## Why It's Good For The Game
less bugs good, gbp good.
## Changelog
:cl:
fix: Fixes missing baseturfs and clowns in mining planet VDOM..
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
You can do a ore box right before the door with chute, so it consumes it instead of you. Or just use another bitrunner/miner, or deconstruct the wall.

**Comment by mc-oofert** [comment]
shouldve ran updatepaths loser

**Comment by Singul0** [comment]
I wouldn't fault a coder for not using updatepaths honestly. it's only ever used by mappers to port old maps because of how unwieldy it is to use, you wouldnt use it every time you have a mid-term map project to PR.

**Comment by Serxule** [comment]
> You can do a ore box right before the door with chute, so it consumes it instead of you. Or just use another bitrunner/miner, or deconstruct the wall.

there are no tools nor an orebox afaik

**Pull request merged**
