### PR TITLE
Volcanic Rocks

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
The decorative "flora" kind. Sprited by WJ.

Maybe one day they can have actual functionality, but for now they'll just look pretty.

### CODE REVIEW

**Comment by Incoming5643** [comment]
Make em items and give em force.

If two miners were on the asteroid and one killed the other with a rock would that be fucked up or what?

**Comment by WJohn** [comment]
Perhaps they could be mined, with a guaranteed ore inside them?

**Comment by optimumtact** [comment]
PICURETURES

**Comment by Jordie0608** [comment]
Remove the unnamed icons from the dmi; no point adding in sprites that aren't being used.

**Comment by KorPhaeron** [comment]
@Jordie0608 

I didn't add them, had no idea what they were so I left them alone

**Comment by tkdrg** [comment]
If they aren't being used, why not just remove them?

**Comment by Cheridan** [comment]
might use them later
you can go "muh git history" but realistically who bothers doing that

**Comment by tkdrg** [comment]
W-Well I do that
But sure, the headcoder has spoken

**Pull request merged**
