### PR TITLE
Fixes the effects of a missing liver

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Fixes carbons not suffering ill effects from a removed liver.

## Why It's Good For The Game

Bugs are bad

## Changelog
:cl:
fix: A missing liver will now hurt you again.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Alright. The core of the issue was that #42247 broke livers. This should fix it. Please yell at me if I'm being retarded.

**Comment by QualityVan** [comment]
What's the reason for the changes to carbon/alien? They look superfluous at a glance.

**Comment by nemvar** [comment]
Because aliens do not have dna but can process reagents. That's the reason why this bug existed in the first place.

**Comment by nemvar** [comment]
Closing this because someone who actually has a clue what they are doing should probably take a shot at this. My version will probably instakill alien larvas due to not having livers. Webedit man bad.

**Comment by nemvar** [comment]
Screw that. I was overthinking it hard. It works all fine.

**Comment by ATH1909** [comment]
Damn, I was hoping this wouldn't get noticed before I got a chance to test it out/play with it a bit.

Unfortunately, since finals week is coming up soon and I need to study/finish my final projects, I won't be able to play SS13 until well after this PR gets merged.

**Comment by nemvar** [comment]
You shouldn't have told me on discord.

**Pull request merged**
