### PR TITLE
New spell type - Pointed spells

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR brings a new type of spells - Pointed. These spells use a direct mouse guidance to find its target instead of using the clumsy input menu. So far, there is only one spell in this category - Blind. Instructional video below:

JBd8cdrZQL

## Why It's Good For The Game

Better handling of the spells.

## Changelog
:cl: Arkatos
add: Added new type of spells - Pointed, which use direct cursor guidance to find its target!
add: Blind spell is now pointed spell. No more clumsy input menu.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Makes the spell slower and harder to aim when moving though...

**Comment by Time-Green** [comment]
> Makes the spell slower and harder to aim when moving though...

How is the input list not hard to move with? You literally have to stop and look what your targets name is and then select it from a list

**Comment by XDTM** [comment]
Are you planning on porting other targeted spells to this system? It'd be nice for mindswap

**Comment by ATH1909** [comment]
What happens if you click on an invalid target, like the ground? Will it "waste" the casting of the spell? Will it require you to click the button again?

**Comment by Arkatos1** [comment]
@Shadowflame909 I would not say so. When using Blind spell via input menu, it will automatically focus on the input menu and forces you to stop if you were moving. If you want to move, you must re-focus by clicking on the game again. The new way does not force you to stop at all, so you can use the spell on your pursers without a stopping for a moment.

@XDTM I could look into it if this is merged.

@ATH1909 Nope, if you click on an invalid target, you will get proper warning message, in this case "You can only blind living beings!" and spell simply wont go off at all. You wont have to turn it on again either, it will still be active until you click on the proper target, or you deactivate it via clicking the action button again. If you deactivate it there is no cooldown either, naturally.

**Comment by HomocidlePancakes** [comment]
Please tell me it doesn't disable itself if you miss the click.

**Comment by SkeletalElite** [comment]
> Are you planning on porting other targeted spells to this system? It'd be nice for mindswap

Would also help with mindswapping stuff you cant see shenanigans. Like mind swapping your slaughter demon after spawning them. Unless that was already fixed.

**Comment by tralezab** [comment]
love it.

**Comment by Fikou** [comment]
> love it.

gotta love it.

**Comment by evilcyborgmrt** [comment]
Can you select a target via right click? For people hiding their sprite or whatever

**Comment by ExcessiveUseOfCobblestone** [comment]
it works like any other left click function so no unless you can altclick the tile

**Comment by ATH1909** [comment]
Can this spam you with messages if you're trying to click on someone in combat and keep accidentally clicking on the floor? Will accidentally clicking on the floor count as a click for the purposes of click cooldowns and such?

**Comment by Iamgoofball** [comment]
This rules and will be super useful for the wizard rework.

**Comment by ArcaneMusic** [comment]
I literally found myself wanting something like this for the rat king a few hours ago.
Solid idea.

**Pull request merged**
