### PR TITLE
Implementing unused hydroponics code and some other botany tweaks.

### PR DESCRIPTION
**Pull request by MisterTikva**
Added Separated Chemicals trait to glowberries. 
Added Densified Chemicals trait to redbeets. 
Added 0.2 water production to watermelons, because it was quite stupid to have holy water in holymelons but no normal water in watermelons.
Reduced blumpkin chlorine production to 0.1, because it was only causing annoyance when making mutagen blumpkins.
Now plants with Liquid Reagents trait will squash all over you if you slip on them.

:cl: MisterTikva
add: Nanotrasen informs that certain berry and root plants have been infused with additional genetic traits.
add: Watermelons now have water in them!
add: Blumpkin's chlorine production has been reduced for better workplace efficiency.
add: Squishy plants now obey the laws of physics and will squash all over you if fall on them.
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
> ***MANIC LAUGHTER***

Excellent PR good chap

**Comment by AlexCrimson** [comment]
So... Tator Botanists will be able to make 100s of deadly plant mines? Seems a little silly. Or do you just mean they will explode, but not transfer the reagent?

**Comment by MisterTikva** [comment]
> So... Tator Botanists will be able to make 100s of deadly plant mines? Seems a little silly. Or do you just mean they will explode, but not transfer the reagent?

It is identical to being thrown at. And yes, they can, but when was the last time you saw a competent botanist, nevermind traitor. A competent scientist/chemist/miner can fuck up the station in a similar if not bigger way, i think. But if people will dislike it i am totally fine with removing it.

**Comment by MisterTikva** [comment]
Plus for those mines to be halfway effective you need 100 potency, which makes them very visible.

**Comment by AlexCrimson** [comment]
Id say Botanists are pretty high up there on the scale of fucking shit up. They can make vines that devour half the station, mobs that can move freely in those vines and soon plant mines that can kill you very fast. The best part? They can store all this deadly stuff in plant bags by the 100s and run around spamming it.

You know, its not like a deadly plant is THAT obvious. Botany has access to that traitor poison that has delayed activation. At max potency its more than enough to instantly kill a person with zero warning a few minutes after its ingested via a random plant on the floor. At least throwing requires you to be on the same screen as the target and have line-of-sight.

**Comment by XDTM** [comment]
It does not put reagents inside you, this only affects acid and blood plants

**Comment by PKPenguin321** [comment]
>mix water making genes with potassium genes from bananas
>other botanist goes to harvest your drop
>explodes violently

Good stuff

**Comment by MisterTikva** [comment]
> Good stuff
You can do facid sacid cond capsaicin trap weed too xD

**Comment by Armhulen** [comment]
when are we adding random gene additions and removals when you use unstable mutagen

**Comment by MisterTikva** [comment]
> when are we adding random gene additions and removals when you use unstable mutagen

That would make botany a mess IMO. Ability to irradiate certain genes to change their values would be nice though, but then we are facing a tad too much powercreep.

**Comment by FantasticFwoosh** [comment]
> WELCOME TO THE EXPLODING RICE FIELDS!

**Comment by XDTM** [comment]
you can put water and potassium in a noreact plant and have some sweet mines/hand grenades

or just grow firelemons

**Comment by ExcessiveUseOfCobblestone** [comment]
how do you even create mines when they react on harvesting?

**Comment by XDTM** [comment]
>noreact plant
The Separated Chemicals trait added here gives noreact to plants... until they squash and mix the reagents. I think.

**Comment by FantasticFwoosh** [comment]
Teslium shock (teslium & water) landmines ahoy.

**Comment by fludd12** [comment]
Water in watermelons finally completes my dream of ready-to-consume ambrosia Gaia with zero downsides.

**Comment by FantasticFwoosh** [comment]
@fludd you can do that already with synaptizine but yeah, more effective ways of doing it.

**Comment by XDTM** [comment]
Synap doesnt heal brain damage, only confusion effects

**Pull request merged**
