### PR TITLE
fixes the flags of some shocks

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

The shocks from the shock touch mutation now ignore insulated gloves, because you're touching your victim's body, not giving them a handshake.

The shocks from punching charged energy fields (special holosigns from emagged cyborgs) now DON'T ignore insulated gloves, because you're literally punching them with your hand.

The shocks from running into charged energy fields now DON'T ignore insulated gloves, to be consistent with things like electrified doors.

The shocks from the on_mob_life() effect of liquid electricity now ignore insulated gloves, like the shocks from the on_mob_life() effect of teslium do (thanks for pointing this out, Angustmeta!).

## Why It's Good For The Game

Logical sense and consistency in what forms of protection shocks check for are good things, I think.

## Changelog
:cl: ATHATH
fix: The shocks from the shock touch mutation now ignore insulated gloves.
fix: The shocks from punching or running into charged energy fields now DON'T ignore insulated gloves.
fix: The shocks from liquid electricity now ignore insulated gloves.
/:cl:

### CODE REVIEW

**Comment by TiviPlus** [comment]
Nice balance PR

**Comment by Angustmeta** [comment]
Liquid electricity reagent should ignore insuls as well imo.

**Comment by ATH1909** [comment]
I've incorporated Angustmeta's suggestion.

**Comment by Angustmeta** [comment]
You accidentally put the nogloves thing in the wrong row.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
