### PR TITLE
Airlocks animate faster

### PR DESCRIPTION
**Pull request by PopNotes**
🆑 PopNotes
tweak: Airlocks animate faster. This doesn't change the time it takes to pass through an airlock, but it does visually match up much better so you don't just appear to glide through the airlock while it's half-open.
/🆑

### CODE REVIEW

**Comment by PopNotes** [comment]
lol oops

**Comment by PopNotes** [comment]
forking is shit, you can't have a fork from an original repo and a fork of a fork at the same time

**Comment by DoctoreMad** [comment]
@Cyberboss ???

**Comment by deranging** [comment]
uhh

**Comment by optimumtact** [comment]
@PopNotes you'd be better of asking github to cleave hippie off like they did with vg

**Pull request closed without merging**
