### PR TITLE
Makes a projectile shield element for colossus, and makes living bullet_act call parent

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Requested by Fikou
Simple animals and living doesn't actually call parent so COMSIG_ATOM_BULLET_ACT is never actually sent to be registered, which is a major problem for things like monkey retaliation, honorbound evil declaration, and stealth module

Here's proof actually that it doesn't work atm
image
image

## Why It's Good For The Game

Elements and actually sending signals that are supposed to be on you, are both likely good ideas.

## Changelog

:cl:
fix: Fixed some problems with bullets (Not making you guilty to Honorbound, Monkeys wouldn't retaliate against you, and Stealth MODsuits wouldn't react at all).
/:cl:

### CODE REVIEW

**Review by Timberpoes — CHANGES_REQUESTED** [review]
Can you describe and where appropriate update the changelog with all of the functional changes that simplemobs now inherit from the parent call that they didn't before?

**Comment by JohnFulpWillard** [comment]
> Can you describe and where appropriate update the changelog with all of the functional changes that simplemobs now inherit from the parent call that they didn't before?

I didn't actually think of that, I'll get to it in a moment

**Comment by JohnFulpWillard** [comment]
> Can you describe and where appropriate update the changelog with all of the functional changes that simplemobs now inherit from the parent call that they didn't before?

run_armor_check doesn't change anything since simplemobs dont wear anything
apply_effects() doesn't do anything from my testing of shooting seargent araneus with tazers
check_projectile_dismemberment() just returns false on the /mob/living level

So this doesn't really change anything, from what I can see. At most I think this will change some text with projectile's on_hit actually letting you block it, though no simple animal actually can.

**Comment by Ryll-Ryll** [comment]
Appreciate the rename for clarity

**Pull request merged**
