### PR TITLE
3/4ths-ifies the Suit Storage Units

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin! Credit to Retlaw34 in her PR: [Suit storage resprite 2: Vengence #713](https://github.com/shiptest-ss13/Shiptest/pull/713) In Shiptest
image

## Why It's Good For The Game
For the upcoming wallening project, structures should ideally be in a 3/4ths perspective!

## Changelog

:cl: PositiveEntropy, Retlaw34
imageadd: Resprites the Suit Storage Unit into a 3/4ths perspective!
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
somehow it fits well on shiptest and doesnt fit here im confused

**Comment by Imaginos16** [comment]
> somehow it fits well on shiptest and doesnt fit here im confused

To be fair I think it'll fit better when the walls make the full perspective change

**Comment by cacogen** [comment]
These are good sprites I just personally don't like how they're cylinders

**Comment by Sealed101** [comment]
> 
> To be fair I think it'll fit better when the walls make the full perspective change

what a grand and intoxicating innocence

**Review by Twaticus — APPROVED** [review]
wonderful

**Pull request merged**
