### PR TITLE
Allows chaplain traitors to praise Ratvar

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

This PR adds a new chaplain-only uplink kit: Justiciar's Follower Kit. It contains a helmet and a set of armor, both of those can't be removed after being equipped. Wearing the suit gives you a special martial art: Justicar's Light, which allows you to: throw magical brass spears at your foes, mark enemies for consistent burn damage, use a special heresy combo which deals burn damage and sets target on fire if they were marked previously and create a brass skewer underneath your opponents, either piercing them after 1 second or whoever walks over it.

## Why It's Good For The Game

We have forgotten armor, now we need propper Ratvar chaplains

## Changelog
:cl:
add: Added a new syndie kit for chaplains, containing Ratvar armor that gives you martial art
add: Added a new martial art: Justicar's Light
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
lame, this will make it confusing whos valid with forgotten armor, and the martial art doesnt evoke anything from clock cult, nothing related to the traps or watch or anything

**Comment by Pugie** [comment]
> lame, this will make it confusing whos valid with forgotten armor, and the martial art doesnt evoke anything from clock cult, nothing related to the traps or watch or machinery and power or anything

is dark blessing bad too then?

**Comment by D4C-420** [comment]
> lame, this will make it confusing whos valid with forgotten armor, and the martial art doesnt evoke anything from clock cult, nothing related to the traps or watch or machinery and power or anything

> >is dark blessing bad too then?

Don't forget the light/dark eswords. Not to mention this gives tot chaps something more interesting to spend tc on than his grace.

**Comment by Potato-Masher** [comment]
Lemme say, I'm all for cool clockwork shit, but I definitely don't remember clockies getting fire kungfu.

**Comment by itseasytosee** [comment]
Rat-var is rolling in his grave.

**Comment by necromanceranne** [comment]
Why is this a martial art. Most of ratvars stuff was equipment providing the magic. 

Wouldn't it make more sense to have, iunno, a spear conjuring item like the one they had so you can huck stunspears at people over and over? Or like gear that does the various powers the clockboys used to have?

Maybe the ability to make brass?

**Comment by Coastfront** [comment]
Gonna be honest this feels less like clockcult and more like just a martial art.
Clock cult wasnt iconic for martial arts as others have pointed out, infact they had none of those things.
They were iconic for stuff like their spiketrap, spear-throw stunning, marauders.
I think was necromanceranne would probably be better than this, like letting them spit out the traps or build a marauder

**Comment by SmArtKar** [comment]
> Why is this a martial art. Most of ratvars stuff was equipment providing the magic.
> 
> Wouldn't it make more sense to have, iunno, a spear conjuring item like the one they had so you can huck stunspears at people over and over? Or like gear that does the various powers the clockboys used to have?
> 
> Maybe the ability to make brass and brass traps?

Hmm, maybe throwing a brass spear as a projectile instead of repulse and adding a new spell that creates a brass skewer?

**Comment by Coastfront** [comment]
> > Why is this a martial art. Most of ratvars stuff was equipment providing the magic.
> > Wouldn't it make more sense to have, iunno, a spear conjuring item like the one they had so you can huck stunspears at people over and over? Or like gear that does the various powers the clockboys used to have?
> > Maybe the ability to make brass and brass traps?
> 
> Hmm, maybe throwing a brass spear as a projectile instead of repulse and adding a new spell that creates a brass skewer?

That would definetly feel more like clockcult yeah. you could also have their ember attack thing which was their main method of stunning, it was a super shortrange projectile.

**Comment by SmArtKar** [comment]
> > > Why is this a martial art. Most of ratvars stuff was equipment providing the magic.
> > > Wouldn't it make more sense to have, iunno, a spear conjuring item like the one they had so you can huck stunspears at people over and over? Or like gear that does the various powers the clockboys used to have?
> > > Maybe the ability to make brass and brass traps?
> > 
> > 
> > Hmm, maybe throwing a brass spear as a projectile instead of repulse and adding a new spell that creates a brass skewer?
> 
> That would definetly feel more like clockcult yeah. you could also have their ember attack thing which was their main method of stunning, it was a super shortrange projectile.

well, that's gonna be too much for a martial art. And yeah, it's called kindle

**Comment by Zytolg** [comment]
Back when we had Clock Cult, it was first a different flavor of Blood Cult, and then it became the defensive opposite to the offense oriented other cult. Then it got removed. I think this is a good idea, and gives a better spin on what Clock Cult is without making it a full gamemode. However, I think it should somewhat resemble what Clock Cult was in the weeks before it was removed- Clock Themed items that have a defensive orientation. Also these should be differentiated from what might currently be available as lavaland loot, and under the consideration that other non-traitor Chaplains may run a religion praising Ravtar (just to a lesser degree. Maybe the Traitor Chaplain was of higher standing in the Clock Cult). I'd also loose the martial for the same reasons others have stated.

I look forwards to seeing your good work in the name of the Lord, brother/sister of the Clock.

**Comment by AndroidMK2** [comment]
Please test merge this without the matial arts stuff but like other people said the spear stun throwing and traps, cool thing would be to add a ranged ability that either stuns or damages people. If coders don't merge this I will say the b word which is "bruh"

**Review by Twaticus — APPROVED** [review]

**Comment by Jared-Fogle** [comment]
martial arts are boring and i don't like them, other commenters are right that this isn't really reminiscent of clock cult at all either

**Pull request closed without merging**
