### PR TITLE
Adds realism to paychecks

### PR DESCRIPTION
**Pull request by ghost**
:cl:
balance: Paychecks are now more realistic, and take into account the character's economic class
/:cl:

### CODE REVIEW

**Comment by Injazz** [comment]
can you see the ceiling ss13?
No, because it's A GLASS CEILING

**Comment by YakumoChen** [comment]
tg doesn't need shitty politics memes, we already have enough racism

it's not even a good meme, it's just "HA HA RACISM GETS YOU PAID MORE"

**Comment by ShizCalev** [comment]
no.

**Comment by NoxVS** [comment]
Should have just made it discriminate against nonhumans.

**Comment by WaterStBlues** [comment]
For real, lizards should be paid less, moths should be paid less unless at a science/med job (in which case they are very smart) and catpeople should be paid in kibble

**Comment by optimumtact** [comment]
it's also inaccurate

**Pull request closed without merging**
