### PR TITLE
adds a new brand of raisins for prisoners, 4 Raisins!

### PR DESCRIPTION
**Pull request by XRandomXManX**
## About The Pull Request

adds a new brand of raisins, 4 raisins! these are only available in the Prison Food Vendor and contain 4 units of Beepsky Smash. They have the description, "You know what you did...".

## Why It's Good For The Game

giving prisoners another thing to do is always a good thing, and now https://github.com/tgstation/tgstation/pull/51811 (where I was banned 4 Raisins) can live on forever!

## Changelog
:cl: Radacitus
add: Added 4 Raisins
add: Added 4 Raisins to the Sustenance Vendor
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
no unique sprite? lame

**Comment by XRandomXManX** [comment]
time to add unique sprite, I guess

**Comment by Pumpkinoe** [comment]
nice

**Comment by XRandomXManX** [comment]
I added a period instead of a slash in one of the files, do not merge until I fix this tomorrow

**Comment by XRandomXManX** [comment]
this is being closed so that i can move it to another, bigger pr in the future

**Pull request closed without merging**
