### PR TITLE
[WIP] Protector and Assassin tech stands have special icons

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Protector stands are now very big, with their metal plates looking more like a suit of armor. It's hands are massive shields used to protect against attacks and bash away attackers.

The Assassin stand, on the other hand, has dropped all of its armor to be stealthy. It wields two powered blades to eviscerate any foes that survive it's surprise attack.

## Why It's Good For The Game

The Protector and Assassin stands have the most and least resistances to attacks respectively, and so showing it in their sprite may encourage people to target properly.

## Changelog
:cl:
imageadd: The Protector and Assassin Holoparasite have unique sprites
/:cl:

- [x] give the protector stand shield arms, make it face more left or right when looking east and west
- [x] assassin east and west sprites, add the crystal to the assassin's back, and change attack sounds
- [ ] create icon states and code for all of the colors, not just red
- [x] longer protector arms

### CODE REVIEW

**Comment by tralezab** [comment]
this should really be a draft, my bad

**Comment by Tlaltecuhtli** [comment]
will they look different if they are a holopara or a guardian?

**Comment by tralezab** [comment]
hell maybe i'll revisit and make a BUFF ASS HOLOCARP and guardian but for now i'm just sticking to holoparasites

**Comment by ExcessiveUseOfCobblestone** [comment]
for easter we need bunny stands

**Comment by Borisvanmemes** [comment]
Maybe make the Assassin's stand blades way thicker and curved?

**Comment by tralezab** [comment]
I like that idea, definitely have to try that out

**Comment by Potato-Masher** [comment]
TBH stands probably should have always had a visual difference from each type from the start to make identification and threat assesment easier. I'm all for this.

**Comment by tralezab** [comment]
Alright, which do you think is best?

option 1: blade hands AKA what we have now
image
option 2: normal hands, wrist blades
image
option 3: same as above but both downward
image
 option 4: hands hold scimitars downward
image
option 5: both scimitars held inwards
image
</details>

**Comment by tralezab** [comment]
giving every stand an icon would be doing it justice, and right now the icons for guardians is extremely silly for doing things like this. above that, it limits the creation of future stands because they would require a unique skin

**Pull request closed without merging**
