### PR TITLE
Adds shower to Box medbay

### PR DESCRIPTION
**Pull request by topham1**
Babby's first PR and absolutely a band-aid fix, but it's something. Added two showers and a mirror to Box's medbay and rearranged shit to compensate, similar to Meta. Also fixes some lighting issues so that the patient recovery room is no longer a dark, depressing corner.

Edit: Reverted the layout back to original with only slight lighting and camera tweaks, a single mirror, and a single shower.

image

### CODE REVIEW

**Comment by Bawhoppen** [comment]
pictures? also you mean the bar backroom? thats supposed to be very dark

**Comment by coiax** [comment]
Loading up the map now, should specify it's Box in the title. I'll get some images.

**Comment by coiax** [comment]
the proposed Box medbay

**Comment by Bawhoppen** [comment]
in that case very :-1: 
you completely removed the patient recovery ward, theres only 1 fucking bed (the shower is bigger than the actual purpose of the room), 
the shower in the sleeper room doesn't make much sense, and having IV drips over there clutters up that hallway

**Comment by coiax** [comment]
> patient recovery ward

**Comment by Bawhoppen** [comment]
thats literally was the door is named, something very close to that

**Comment by TheWiznard** [comment]
@Bawhoppen oh no, one of the rooms that _might_ be slightly more used than the library

**Comment by Jalleo** [comment]
Just add a lot of the roller beds all folded up. 5 should be way more than enough

**Comment by TechnoAlchemisto** [comment]
You only need the one shower near the sleepers, removing the ERP huts is unnecessary

**Comment by topham1** [comment]
The problem I had with adding just the one shower was that either the IVs have nowhere to go or the patient closet has nowhere to go, even if you do pretend that people actually use that closet. Besides, these beds are stationary and why would we bother with stationary beds aside from the two patient rooms that **already exist** and that **nobody uses** for anything more than storing braindead doctors.

If you are all okay with removing just one of the beds, I could fit it all in. Give me a bit.

**Comment by topham1** [comment]
Better? It still feels a little cluttered, but it's basically the same thing as before other than the single shower and the lighting/camera fixes.

image

**Comment by lzimann** [comment]
Looks really better now.

**Comment by topham1** [comment]
Thank god. If this doesn't get merged - which would be surprising, considering it's basically no difference at this point - I'll make a separate PR anyway for the changes in lighting and camera visibility. I see no reason to leave the patient recovery room as dark and depressing, medbay's already morbid enough.

**Comment by Dorsisdwarf** [comment]
Backroom being the medbay backroom, right?

**Comment by topham1** [comment]
Yeah, fixed the original to be more specific.

**Comment by optimumtact** [comment]
We are totally running out of space on box, needs to be remapped to make all the departments bigger

**Comment by topham1** [comment]
I thought that the point of Box was to be a highly functional and very
compact station, hence the crammed feeling and lack of explorable territory
and such. An overhaul to turn box into Meta 2.0 seems a bit much. That's
why I like Meta better tbh, it feels a little roomier. Also that dank loot

**Comment by optimumtact** [comment]
Both maps are actually roughly the same size, and I'm not suggesting box loses it's compactness, I'm saying we've added so much stuff that's becoming cramped and not compact

**Comment by optimumtact** [comment]
also box is love and life

**Comment by lzimann** [comment]
meta is kinda having the same problem in some departments even though meta feels bigger than box

**Comment by topham1** [comment]
Box is overrated birdboat4lyfe

How is it that meta feels so more open though I don't understand??? Maybe
later I can take a look at them both

**Comment by Bawhoppen** [comment]
also why did you want a shower anyways now that cryos been fixed? just use the virology's one

**Comment by jughu** [comment]
Because powercreeps bawhoppen they dont want to sleep a while in cyro and rage how doctors left in on manual and then forget about them

**Comment by coiax** [comment]
Also, hospitals have emergency medical showers, for washing off chemicals or blood or something. Regardless, these small map tweaks are fine. Have a :+1:

**Comment by topham1** [comment]
Wait what do you mean cryo was fixed? I mean I would still suggest an
emergency shower anyway but?

**Comment by Zilenan91** [comment]
So what's up with this

**Comment by topham1** [comment]
i guess it died, i dunno. i went for a trip for a few days so that may be why.

was cryo actually fixed? i can't find where it was.

**Comment by Bawhoppen** [comment]
I fixed it, read the changelog

**Comment by coiax** [comment]
Still no objections to medbay getting a shower, it makes RP SENSE, and adds a little flexibility in emergency situations.

**Comment by Zilenan91** [comment]
It also lets MDs clean greyshirt blood off of themselves

**Comment by topham1** [comment]
OHHHH man i've been looking for that changelog entry. still, i do think adding the shower makes a hell of a lot of sense, and i like the little tweaks in lightbulb and camera placement that i did.

**Comment by coiax** [comment]
Medbay already had a sink for blood cleaning, but a shower in a medbay makes sense anyway.

**Comment by Cheridan** [comment]
should be k

**Pull request merged**
