### PR TITLE
Create SpaceMelody.mp3

### PR DESCRIPTION
**Pull request by pxlsr**
## About The Pull Request
https://vocaroo.com/1f25Na5p6YB2
A new melody I created for tgstation/SS13. Not sure where it fits in terms of sound. But it's available for anyone to use. Music is public domain.
## Why It's Good For The Game
I think it adds some quite colorful character in terms of sound, I'm just not sure what context this music would be good for. Perhaps a title song or emergency shuttle departure music?

Edit: I've moved it into the jukebox folder.

### CODE REVIEW

**Comment by atlasle** [comment]
could you post a vocaroo link with the song

**Comment by SamuelRowe** [comment]
https://vocaroo.com/1f25Na5p6YB2

**Comment by Mothblocks** [comment]
This PR doesn't actually hook it up to anything so I'm not really sure what you want us to do here

**Comment by SamuelRowe** [comment]
> This PR doesn't actually hook it up to anything so I'm not really sure what you want us to do here

You're right, I just wanted to move the file into the repo for now. I could push another PR later, but I need feedback on where it would work

**Comment by Iamgoofball** [comment]
put it in the jukebox

**Comment by SamuelRowe** [comment]
> put it in the jukebox

I'll do that. It looks like theres a good framework there if I want to add more, too

**Comment by SamuelRowe** [comment]
> I don't think I really like this song. It doesn't follow any kind of rhythm or beat, it's just a bunch of chaotic bips and bops with a heavy drum. I don't know much about music theory, but maybe if it had more 'structure' or something? I'm sure someone who's more of a musician can elaborate on what I'm saying.

That's perfectly fair critisicm. I had a feeling not having any changes in the song made it pretty boring, it was just an arpeggio over two octave ranges using C E G in random. Originally I just wanted it to be low volume space ambience but then someone said it was probably too high energy so I tried to salvage it into something else. I kinda brought this on myself by not studying song progression yet. Maybe I should spend more time before I make ambitious leaps like this. I've only been playing keyboard/synth for a few months, sorry guys

**Comment by Cheshify** [comment]
> > I don't think I really like this song. It doesn't follow any kind of rhythm or beat, it's just a bunch of chaotic bips and bops with a heavy drum. I don't know much about music theory, but maybe if it had more 'structure' or something? I'm sure someone who's more of a musician can elaborate on what I'm saying.
> 
> That's perfectly fair critisicm. I had a feeling not having any changes in the song made it pretty boring, it was just an arpeggio over two octave ranges using C E G in random. Originally I just wanted it to be low volume space ambience but then someone said it was probably too high energy so I tried to salvage it into something else. I kinda brought this on myself by not studying song progression yet. Maybe I should spend more time before I make ambitious leaps like this. I've only been playing keyboard/synth for a few months, sorry guys

I didn't mean to hurt any feelings, so I really hope I didn't. Keep at the music work I really want to hear what you can make, and what you're capable of is far better than me!

**Pull request closed without merging**
