### PR TITLE
Adds framework for cult constructs having the ability to make runes

### PR DESCRIPTION
**Pull request by ChangelingRain**
For @Robustin so he can maybe just jam random runes onto constructs.

Rune colors are now defines, excluding some talisman colors.
Adds break_do_after_checks(), for using as a callback to break a do_after if the mob takes damage or takes an action that doesn't move it.
Moves a bunch of cult effects to cult_effects.dmi
Moves `/obj/effect/overlay/temp` out of overlays.dm as preliminary work for renaming the shit out of them

### CODE REVIEW

**Comment by Armhulen** [comment]
New construct magus inbound

**Comment by Robustin** [comment]
Thanks, break do after is something I've looked for multiple times before.

**Comment by YakumoChen** [comment]
Feels like an unneeded buff to cult, since constructs are already pretty powerful and not being able to rune with them (thus highly discouraging murderbone) is sort of good balance.

**Comment by Robustin** [comment]
Im coding a cult """nerf""" right now.

Im bretty gud at balancing and this is just the framework that will be needed down the road.

**Pull request merged**
