### PR TITLE
Fixes space heater power usage

### LINKED ISSUE #82228: Space heater cell drains near instantly
## Issue Summary

After https://github.com/tgstation/tgstation/pull/82197 the space heater consumes its cell nearly instantly.

## Reproduction:

15c change, hyper cell

Before https://github.com/tgstation/tgstation/pull/82197

https://github.com/tgstation/tgstation/assets/83487515/e2dcc9ad-0d1c-4125-a065-59076d29787b

After

https://github.com/tgstation/tgstation/assets/83487515/2b15d03b-b78a-428d-9520-834cb80f4e17

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Related to https://github.com/tgstation/tgstation/issues/82196 fixes the space heater power cell usage relating to power per tile heated.

Space heater calculates the amount of power required to heat a tile, but only uses power at the end of the processing loop. Fixes so the power consumption matches the calculated usage per tile.

Reverts changes to space heater power efficiency in https://github.com/tgstation/tgstation/pull/82197 that causes the heater to instantly drain the cell.

Fixes https://github.com/tgstation/tgstation/issues/82228

## Changelog

:cl: LT3
fix: Fixes Schrödinger's space heater, where a space heater both consumes a power cell instantly while also not consuming power when heating adjacent tiles
/:cl:

### CODE REVIEW

**Review by san7890 — COMMENTED** [review]
image

treating `delta_temperature` as a boolean is already disgusting, but we should make this be an early return since there's no reason for the indentation to be ugly anymore, so just do something like `if(delta_temperature == 0); return` and put the for-loop after that.

**Comment by SyncIt21** [comment]
Have you tested this locally? How fast does the cell drain compared to before? If a turf has 8 adjacent turfs then the cell is consumed 8 times faster with no additional benifit.

**Comment by lessthnthree** [comment]
> Have you tested this locally? How fast does the cell drain compared to before? If a turf has 8 adjacent turfs then the cell is consumed 8 times faster with no additional benifit.
> 
> The heating effects should be less for adjacent tiles and less power should be consumed for the same

15c change with a hyper cell consumes ~1% in 30 seconds.

https://github.com/tgstation/tgstation/assets/83487515/ed464410-6507-4dfb-a265-234d3ff27f12

**Comment by SyncIt21** [comment]
> 15c change with a hyper cell consumes ~1% in 30 seconds.

This data is presently unreliable because the space heater power consumption wasn't scaled up after that power refactor.

Try testing this change with #82197 locally and come back with new findings

**Comment by lessthnthree** [comment]
> > 15c change with a hyper cell consumes ~1% in 30 seconds.
> 
> This data is presently unreliable because the space heater power consumption wasn't scaled up after that power refactor.
> 
> Try testing this change with #82197 locally and come back with new findings

My finding is that #82197 breaks the space heater, causing its cell to drain near instantly; before the proposed changes in this PR are applied. What did you find in your testing of #81297?

**Comment by SyncIt21** [comment]
> My finding is that https://github.com/tgstation/tgstation/pull/82197 breaks the space heater, causing its cell to drain near instantly; before the proposed changes in this PR are applied. What did you find in your testing of https://github.com/tgstation/tgstation/pull/82197?
> 
> Given the power drain is broken there, it points to a problem with the space heater consumption in general after that change, not the increase from consuming cell per tile which is the fix of this PR.

After #81579 was merged the standard capacity of cells was increased by 1000. My PR scaled up the energy usage of space heaters by that amount so they use the same energy from their cells as before.

This is why your PR is a problem because with the corrected usage rates for something like 8 tiles it can drain the heater very quickly. If you still want adjacent tiles to use energy then you need new math to decide how much energy to divide per turf.

**Comment by SyncIt21** [comment]
> No, because I am aware of that and the test was performed on a build of master from 3 days ago, where https://github.com/tgstation/tgstation/pull/81579 is merged and your PR https://github.com/tgstation/tgstation/pull/82197 is not.

My PR got merged just a few hours back. Look it up

**Comment by lessthnthree** [comment]
> > No, because I am aware of that and the test was performed on a build of master from 3 days ago, where #81579 is merged and your PR #82197 is not.
> 
> My PR got merged just a few hours back. Look it up

I did. I ran the test on master as of this hour, which has your PR and not this PR. Compare it to a branch from before your PR. That's why I'm asking if you tested the changes in yours, because that would be a different issue.

**Comment by Pickle-Coding** [comment]
> Ok so i did overlook one element of space heater. Its default heating power
> 
> 
> 
> https://github.com/tgstation/tgstation/blob/0c35d0b8a92edb51fa5c56cd7b341a649ca992d4/code/game/machinery/spaceheater.dm#L31
> 
> 
> 
> Change this to `40 / (1 KILO JOULES)` because efficiency applies our multiplier of 1000 already. Also rename to heating energy and you should be good. If it fixes it you can link your own issue

Don't change the heating power. That gives an effect on how much thermal energy it can change in the air. Could rename it to 40 KILO JOULES if you like. Just undo the scaling of efficiency because I already scaled it correctly.

**Comment by SyncIt21** [comment]
> Don't change the heating power. That gives an effect on how much thermal energy it can change in the air. Could rename it to 40 KILO JOULES if you like. Just undo the scaling of efficiency because I already scaled it correctly.

Fair enough i don't know what's scaled anymore. I guess MrMelbert mistook space heaters to be broken

**Comment by lessthnthree** [comment]
Reverted efficiency changes implemented in #82197.

**Pull request merged**
