### PR TITLE
Shuttle Burning No Ugly

### PR DESCRIPTION
**Pull request by Cheridan**
Makes shuttles not ugly when they get burnt/broken. Moves shuttle floors into floors.dm with all the other floors.

Remotes unused Unsim folders/files.
If you're a mapper who has broken shuttle tiles just edit the Instance and add the world _shuttle_ in front of _floor[1,2,3,4]_. Easy fix.

Need to upload the rest of the fixed maps for Box still thanks to #10300

### CODE REVIEW

**Comment by Cheridan** [comment]
are you serious

**Comment by optimumtact** [comment]
>headcoder

**Comment by Miauw62** [comment]
sprites?

**Comment by Miauw62** [comment]
pics?

**Comment by Cheridan** [comment]
@Miauw62 It's the same damaged/destroyed graphics as other floor tiles. Currently when shuttle tiles get damaged they turn completely black.

**Comment by Aranclanos** [comment]
yolo

**Pull request merged**
