### PR TITLE
ID related mob sprite changes

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Changes PDA mob icon in ID slot to use the PDA mob icon in belt slot, making the PDA mob icons consistent.
Moves mob IDs to the opposite side of PDAs and makes them smaller, balancing and reducing visual clutter.
PDA-ID
Changes wallet mob icon to sit on waist.
Adds directional to PDAs belt mob icon.
Tablet mob icons unchanged.
dreamseeker_vrYYc70iWS
centcom, deathsquad, gold, retro, prisoner, silver, doorjack, wallet w/ grey, emag

## Why It's Good For The Game

The blinking square + block of colors on the chest felt so unnecessary. I originally wanted to just remove IDs showing up on mob completely, but felt satisfied trying out the color strip instead. Plus we already had a perfectly fine PDA icon that sits on the belt. We can still go the route of removing the IDs showing on mobs if needed.

## Changelog

:cl:
imageadd: Makes mob ID sprites smaller, mob PDA sprites more consistent
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
> imageadd: Makes mob ID sprites smaller, mob PDA sprites more consistant

isn't it's consistEnt, not consistAnt

**Review by Krysonism — APPROVED** [review]
This is a much needed change as the noise added by PDAs and IDs has made every single outfit in the game look so much worse.

**Comment by Twaticus** [comment]
> > imageadd: Makes mob ID sprites smaller, mob PDA sprites more consistant
> 
> isn't it's consistEnt, not consistAnt

sorry im illitarete

**Comment by Timberpoes** [comment]
@optimumtact What are your views on removing the requirement for ID card sprites being clearly visible on the mob?

It is by far one of the changes I got the most flak for when I originally implemented nu IDs.

Getting a clear and recognisable representation of the ID card on the player sprite is genuinely not practical at the scales were working with without making it ugly or ruining fashion.

I think I started at 3x5 in the original implementation, then i think it got reduced further by an actual sprite, and now we're condensing it down to a barely legible 1x3 strip of pixes.

With the older changes to increasing ID card visibility on examine, would you be willing to relax the on-sprite requirement? At this point I don't think a 1x3 strip of pixels clearly clearly represents anything and may as well be removed.

**Comment by optimumtact** [comment]
ok, make surey ou update the documen

**Comment by optimumtact** [comment]
Timberpoes doing you dirty

**Pull request merged**
