### PR TITLE
[MDB IGNORE] You can have your cake and eat it too. Remake of #66406 (Splitting up areas.dmi + code related stuff)

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request

Remake of #66406 because a merge got fucked up and I didn't know how to rectify it.

## Why It's Good For The Game
This PR is mostly coder facing, but any bugs that arise will be player facing.

All this does is slice areas.dmi into multiple, smaller files. This makes navigating area turfs much more friendly and easy, instead of combing the behemoth that was 400 icons. This also cleans up the object tree (yay!) so mappers can now view the /turf/ tree without a billion things bombarding them.

## Changelog

Not needed, per SuperNovas comment.

### CODE REVIEW

**Comment by TheBonded** [comment]
👎 I thought this was a chef update that added new cake sprites and flavours

**Review by san7890 — APPROVED** [review]
Imaginos said the sprites looked good on the older version of this PR, reduces RSC bloat since we don't have 100+ icons in the same DMI, I would have done this change myself, etc. etc.

 There's an update paths, and everything compiles. This will conflict literally every mapping PR currently being made, but it's simple enough to fix when people go into `tools/UpdatePaths` and drag and drop the file you introduced in this PR (`turf_updates.txt`) and have that automatically work it's way through.

The older PR was up for about a week before it was catastrophically rendered useless, so I'll merge this post the 24-hour mark when I am able (and hopefully it doesn't hugely conflict with anything else that could get merged in this timespan). I've been withholding some of my wanted area changes in anticipation for this PR, and it'll be nice to see it finally come into effect.

Thank you for your work doing this: I know that it certainly could not have been an easy task.

**Comment by SuperNovaa41** [comment]
None of your changelog is relevant to players, so you don't need it

**Comment by san7890** [comment]
FYI: If this PR caused merge conflicts, I wrote a short guide on using UpdatePaths to fix them: https://hackmd.io/koZLICNhTBa9mhb7Ts_wqg#UpdatePaths-And-You-

**Pull request merged**
