### PR TITLE
Completely removes overthrow from the game.

### PR DESCRIPTION
**Pull request by anconfuzedrock**
:cl: 
rscdel: Removed the entirety of the overthrow gamemode.
/:cl:

[why]: Overthrow has no benefit to the server whatsoever and showed me everything about how not to make a mode:
It's extremely slow paced. once objectives are done, teams have no other motivation.
It's extremely confusing. The goal is to get the most "points" which are never explained. you can't even see how many points your team got unless at roundend your team won
Not even the creator knew what he was doing, considering how one of the objectives works (each team gets rewarded based on whether  the head of staff was executed or exiled. each team is rewarded. each team wants to get a higher score than the other teams. if every team is rewarded, none are. this objective is entirely useless to follow)
Lmao the ais laws are so badly done I've had ais subverted to a different team obey mine
Did I mention that it's literal metagangs yet?

### CODE REVIEW

**Comment by Iamgoofball** [comment]
If this stays reverted I'll bring back my gang and Integrate it with economy.

**Comment by anconfuzedrock** [comment]
I jus don't like overthrow man I just hope this even WORKS

**Comment by duckay** [comment]
did you really pr a removal without fully understanding the mode

**Comment by anconfuzedrock** [comment]
what do you mean by understanding cuz lemme tell you I understand the mode better than the creator the only thing I could not understand is whether or not I removed it RIGHT

**Comment by duckay** [comment]
whats tgstation wiki

**Comment by anconfuzedrock** [comment]
Duckay if you wanna keep being a smart ass keep it up

**Comment by duckay** [comment]
[](https://tgstation13.org/wiki/Overthrow)

**Comment by fludd12** [comment]
This has the strong scent of an `im ded` PR...

**Comment by anconfuzedrock** [comment]
I guess you could say that fludd. my team won overthrow with every member dead, so I decided this game mode was broken a long time ago.

**Comment by Potato-Masher** [comment]
I have not been in a single round of Overthrow (somehow), but I can see where the entire round may stall. There's no real objective that results in the round moving forward; the antagonists can go 100% undetected if careful and after the conversions are done there's not much else to do. Plus, it just seems like a weird Polymerization of Traitor/Gang/Rev or something along those lines. At least Hivemind has some sort of originality going on.

**Comment by Carbonhell** [comment]
If you have an idea on how to improve it just ask, the idea on paper looked fine for both me and naksu, not my fault if it ended up as a bad idea smh

**Comment by optimumtact** [comment]
If you toss code over the wall and don't stick around to make changes to it, do not expect it to stick to the game

this is why paying for things doesn't really work unless you have a clear outcome and goal and do not need a long tail of reaction

**Comment by HydroFloric** [comment]
@Carbonhell First off, during prior interactions with your a was kinda hostile over all this so just a apology about that firstly. On to your statement for how to improve the mode you can probably try to fix the issues brought up in this PR firstly. 

Namely

> Its very slow paced with teams doing their objectives and sitting on their asses turning it into extended.

>Team points are poorly explained with no way for teams to see theirs, or other teams points.

>All teams are rewarded when a objective is fulfilled nullifying the entire purpose of having it as a competition between teams.

So those are just some starting things which could be done.

**Comment by bgobandit** [comment]
it's funny you mention the tgstation wiki since I literally had to bitch at the creator to get it to exist

**Comment by Carbonhell** [comment]
I am not a tg player, noone contacted me so i assumed everything was fine, I do not think i was hostile to anyone who pmed me for stuff/general help ever...
Anyway, regarding the issues:
1)It is at the antagonist's discretion to speed stuff up and go wild over other teams, or play the stealth card, they choose how to do it, if you have any idea on how to generally speed stuff up it's welcome
2)If you could see the points, they could be used to metagame and know when a head gets killed or such. If you truly think this is better, I can add it. I just do not think it is, but players may know better. Your choice, it should take at most some minutes to make a PR for this.
3)The point of the gamemode is both to be teams vs crew and team vs team, that is why there is a mechanical way for multiple teams to benefit from one objective. Two teams can ally to exile a head instead of converting it, then one could instead change idea and convert it and start a war with the other team, for example. Maybe more points should be given to the team who actually does the task? Not sure how to properly handle detecting murder, codewise though.

**Comment by anconfuzedrock** [comment]
if you don't play our server, why do you care if it gets removed? are you worried you'll have to give your money back?

**Comment by Qustinnus** [comment]
@anconfuzedrock holy shit shut up brainlet hes a downstream maintainer which means keeping this mode in upstream is beneficial if he wants it downstream. stay on the server and off the github please

**Comment by anconfuzedrock** [comment]
Fair enough

**Comment by subject217** [comment]
removal is premature here tbh

**Comment by Repukan** [comment]
>If you toss code over the wall and don't stick around to make changes to it, do not expect it to stick to the game

Clockcult removal when?

**Comment by wesoda25** [comment]
Wow it’s almost like no one likes overthrow or assimilation. 

We sure did need the poll for that (pessimism aside the poll was needed).

**Comment by ExcessiveUseOfCobblestone** [comment]
assim is fine frick off

**Comment by anconfuzedrock** [comment]
This pr isn't about assimilation.

**Comment by sagattyy** [comment]
the new gamemodes are bad

**Comment by optimumtact** [comment]
@Repukan when you make a PR for it

**Comment by Iamgoofball** [comment]
wasn't clockcult already removed?

**Comment by Repukan** [comment]
No, only removed from rotation

**Comment by PKPenguin321** [comment]
The mode was removed along with Reebe, meaning the gamemode doesn't work at all. It still has stuff in the code but it's more than just removed from the rotation

**Comment by SouDescolado** [comment]
To be fair, I only played overthrow once. I became a borg, and was following AI orders, BUT I couldn't see who we were obeying (There is already an issue about it open), where we had to keep asking the AI wtf to do and who to obey, since we couldn't even know who was syndicate. Then we got an order to meet someone, on the way the team changed, and we killed the guy who we were going to meet in the first place.

There was a point that I had no idea what to do so I went to where I had spaced HoS body and kept hitting it. On the escape shuttle, the AI decided to tell it's laws, because why not?

There are lots of things to be fixed. There are ways to try to avoid metagame while making the game fun. But right now, considering I only saw the borg side of this mode, it is kinda a mess.

There are at least 4 issues that are valid about overthrow(To be fair one was opened recently). Maybe they should get assigned to @Carbonhell to make it easier for him to see what is going on.

Now, about being paid code, it is not the first time someone get paid for a code and do not maintain it. But the money is not leaving my wallet, so if this isn't a problem for who is paying, so be it.

**Pull request closed without merging**
