### PR TITLE
Adds a holo-fan and two emitter and thermomachine boards to syndicate base.

### PR DESCRIPTION
**Pull request by TheNobodyofimportance**
## About The Pull Request
This is my first PR. Adds a holofan, two emitter boards, and two thermomachine boards to the engineering crate in the engineering room of the lavaland syndicate base.
## Why It's Good For The Game
The lavaland syndie base has no holofan and is limited to two thermo machines and no emitters (four thermomachines and one emitter if SM shard room spawns) which is severely limiting to atmospheric gameplay within the base. By adding the boards and holofan, you can create better atmospheric and SM set ups with more machines and less walls needed, simplifying it and allowing greater freedom of gameplay and experimentation. 
## Changelog
:cl:
add: Holofan and two thermomachine and emitter boards in lavaland syndicate base.
/:cl:

### CODE REVIEW

**Comment by Vect0r2** [comment]
Screenshot 2024-07-12 3 58 58 PM
can we get a good first PR here along with the don't merge from master warning

**Comment by Sadboysuss** [comment]
You should make a branch of your master and make your changes there for next time. You can ask in coding gen how to do that.

I think it's an interesting challenge to have a limited supply of equipment, but it's not like it changes too much, so I think it's fine.

**Comment by TheNobodyofimportance** [comment]
> You should make a branch of your master and make your changes there for next time. You can ask in coding gen how to do that.
> 
> I think it's an interesting challenge to have a limited supply of equipment, but it's not like it changes too much, so I think it's fine.

Thanks, I'll keep that in mind for next time.

As for why: I believe the syndie base should be a sandbox ghost role with access to top of the line equipment such as T4 parts, gold and plasma (also 3 crates of donk pockets... wow). The lack of a holofan when station starts with one didn't make much sense to me, as well being limited to one emitter and four thermomachines split between two rooms at maximum.
If we're looking at poverty ghost roles we have charlie station for one, we could also add a new ghost role if you feel we lack a niche.

**Comment by TheNobodyofimportance** [comment]
closing this PR because of merging with master, see #84934 for correctly formatted PR from a branch.

**Pull request closed without merging**
