### PR TITLE
Fixes away missions [Ready for Review/Merge]

### PR DESCRIPTION
**Pull request by Shadowlight213**
This is an attempt to bring all the away missions up to current code so they work correctly.
All were tested and they compiled and ran.
I apologize for the large diffs. Map merger broke for me.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
ALL DEAD NO HOPE

**Comment by Miauw62** [comment]
godspeed, you glorious bastard
o7

i might actually revive my old admin-triggered away missions

also add away missions to travis pretty pls

**Comment by Jalleo** [comment]
Remove tge really bad maps though.

**Comment by KorPhaeron** [comment]
@Jalleo

Completely subjective considering a very vocal minority talks constantly about how bad the death missions were, but they were objectively so popular that we had to disable them to stop everyone leaving every round.

**Comment by Miauw62** [comment]
all of the away missions except the ones wj made are shit tho

**Comment by Shadowlight213** [comment]
Content balance is outside the scope of this PR. This is purely to get them to the point where they compile and run.

@miauw62 I thought adding stuff to Travis was restricted to maintainers. If not, how would I do that?

**Comment by Zilenan91** [comment]
So the gateway works by someone with I'm assuming captain access getting in there, activating it, and then jumping in it?

**Comment by Shadowlight213** [comment]
@zilenan91 sort of. Gateway room has its own access level. The gateway itself needs no access to open.
Possible away missions are set by the host, and there's a config option for a delay before the gateway can be used.

**Comment by Zilenan91** [comment]
So say one guy enters, this means that there's a cooldown before more people can enter? Or is the delay where it can't be entered after switching to a new mission?

**Comment by Shadowlight213** [comment]
Delay is from roundstart. The mission is loaded at the beginning of the round. Once it's open, there's no delay.

**Comment by Shadowlight213** [comment]
More fixes! Some more turf icons have been fixed and a bunch of runtime errors were solved!

@MrStonedOne I've added a line to the space_levels.txt which is needed to avoid runtimes when running away missions. If they are disabled, the line isn't needed, and actually needs to be commented out to avoid runtimes.

**Comment by KorPhaeron** [comment]
@Shadowlight213 

Make the line died to the config option.

**Comment by Shadowlight213** [comment]
@KorPhaeron Not sure how to do that, but I'll give it a shot.

**Comment by Shadowlight213** [comment]
Ok, things should be good to go now. I've ran and tested all the away mission maps.

@Miauw62 Away missions aren't loaded like other maps so I cant add it to travis normally.

**Comment by optimumtact** [comment]
:-1: unless these are made into a proper roundtype so they don't shit on other game modes.

**Comment by Shadowlight213** [comment]
@optimumtact Away mission gateway opens after 40 minutes. The round usually would get stale by then. Also these aren't enabled by default. The host has to enable them.

**Pull request merged**
