### PR TITLE
Nuke Op Loot Pinata Tweaks

### PR DESCRIPTION
**Pull request by Cheridan**
Tweaks nuke op hardsuits. They function very similarly to before, but instead of the helmet being a separate item they're now up-to-date with other hardsuits. Clicking the Helmet's action button toggles between Combat and Travel mode for both the helmet and suit.

MOST IMPORTANTLY, while the hardsuit's helmet is equipped, neither the suit nor the helmet can be taken off. Since this covers other pieces of equipment, it also protects those from getting looted if the op gets captured. The wearer of course can remove the helmet and then take off the suit.

People said Explosive Implants were too expensive to consider so they're now down from 9 to 6.

Note: op hardsuit Combat mode was resprited because the old sprites had sections cut away. If I wanted jumpsuits to show up under those cutaways I would have had to "uncover" them using the flag, which would allow people to strip the jumpsuit. The helmet is probably a better indicator in the first place anyway.

### CODE REVIEW

**Comment by TheVekter** [comment]
So in what instances would the suit be lootable and when wouldn't it? Does taking off the helmet activate combat mode, or is it a separate toggle?

**Comment by Lumipharon** [comment]
What happens if you melt their helmet off with acid, or is it acid proof?

Also this still leaves the bag (and belt I think?) open to loot.

**Comment by Cheridan** [comment]
@Lumipharon If your helmet would be melted, it looks like you can toggle your helmet "off" and back on to spontaneously generate a new one. You won't get stuck with unremovable armor or anything.
Note that the only way for this to happen is acid smoke grenades which will melt every other item off you anyway.

And yeah the things that aren't covered by the suit are still available, but this at least prevents people from getting the suit itself as well as the headset, compromising comms. Those were the biggest things I saw people complain about.

**Comment by hornygranny** [comment]
:+1:

**Comment by Kromgar** [comment]
Can't you make the headpiece immune to acid?

**Comment by Lumipharon** [comment]
I meant more like, if you wack someone in the head with deathnettle enough, will it melt their helmet off, letting them loot you?

Also semi related, if you get your ling armor helmet melted off, you can NEVER toggle your ling armor off or on  again, so you're just stuck with the exosuit but no helmet.

**Comment by Cheridan** [comment]
@Kromgar I could, which would probably make more sense than spontaneous regeneration (NANOMACHINES!!), but it would be inconsistent with the actual hardsuit's acid protection. 
Unless I made that acidproof as well?

@Lumipharon Nah, your suit will still be technically toggled on even if your helmet is missing because reasons. They'll be able to get to whatever was under the helmet though. :construction_worker:

**Comment by Lumipharon** [comment]
Honestly acid is retardly OP at this point, so I don't think anyone would be upset (except the chemists) if they got acid protection. It would be better if acid got fixed though (and I don't mean goof's change to smoke...)

**Comment by kevinz000** [comment]
But but how will we get suits and pointers to fite the nukeops?

**Comment by Cheridan** [comment]
captains quarters and EVA :^)

**Comment by Thunder12345** [comment]
Seems pretty cheap to make fluke ops completely unlootable under any circumstances. At least give some way to remove the suit given time, and probably tools.

**Comment by Cheridan** [comment]
The goal of the previous functionality (mandatory explosive implants) was to make them completely unlootable under any circumstances.

**Pull request merged**
