### PR TITLE
Remove borg jetpack, give them ion thrusters instead

### PR DESCRIPTION
**Pull request by neersighted**
Remove gas-based, item jetpacks from cyborgs as they required snowflake and didn't need to be items anyway.

Instead, they are replaced with ion thrusters, which functionally are the same but work based off of charge and are built in instead of being a module. There is a hud button available to turn them on an off. They cost `50` charge a step, allowing 500 steps on a default cell.

Ion thrusters come standard on syndiborgs and may be equipped to any other borg as an upgrade. The upgrade has the same research and material requirements as the (removed) mining borg upgrade.

Removes jetpack stabilizers (they only cost extra when moving and did nothing to borgs, which made no sense). Instead, adds jetpack turbo mode, so you can move normally in space or go at sanic speed (old jetpack speed) for the same cost as stabilizers.

Now has snazzy sprites thanks to @WJohn, see the last screenshot for the HUD button position and style.

Also clean up jetpack human movement because wow that code was messy
Its still bad but its better (tm)
Partially invalidates/resolves #15347 by fixing the initial issue of cyborgs not being able to use their jetpacks without verbs.

:cl:
del: Remove all cyborg jetpacks... They were awful...
add: Adds borg ion thrusters, which are available as an upgrade module for any borg.
del: Jetpack stabilizers are always on, but now we have...
add: Jetpack turbo mode, to move at sanic speed in space.
/:cl:

THIS IS SHITTY
I WIN
WITH SPRITES

### CODE REVIEW

**Comment by GunHog** [comment]
That is a BEFORE image, where is the AFTER image?

**Comment by neersighted** [comment]
Whoops wrong image

**Comment by GunHog** [comment]
Alrighty :) I hope WJ makes a good sprite for ye! Can the pressure / drain still be tracked?

**Comment by tkdrg** [comment]
Also, can it be reloaded? You could fill borg jetpacks by clicking a tank with them.

**Comment by neersighted** [comment]
Refilling it was removed when canisters were refactored as too snowflake, they refilled in a recharger. As these are **ion** thrusters they consume charge.

**Comment by neersighted** [comment]
Sprites added!

**Comment by MrStonedOne** [comment]
>Closes #15347 by resolving the initial issue

Fuck off with taht shit, i still want object verbs to remain.

**Comment by neersighted** [comment]
@MrStonedOne Well your justification was borg jetpacks being broken. Here I present an alternate solution. If that PR is not related to borgs but rather personal preference please edit it accordingly.

**Comment by Bawhoppen** [comment]
verbs are way better man, don't take them away when most of us prefer them

**Comment by neersighted** [comment]
This PR has nothing to do with verbs, please discuss that elsewhere.

**Comment by Bawhoppen** [comment]
I was supporting mso

**Comment by MrStonedOne** [comment]
@neersighted I CLEARLY FUCKING STATED BOTH REASONS AS WHY, NEXT TIME READ THE FUCKING PR

**Comment by MrStonedOne** [comment]
As long as your PR says it closes mine it has everything to do with verbs

**Comment by neersighted** [comment]
Description has been updated for detail/accuracy.

**Comment by Cheridan** [comment]
object verbs must die

**Comment by KorPhaeron** [comment]
Jetpacks are fucking terrible now jesus

**Comment by Core0verload** [comment]
I'll try to revert that jetpack nerf soon.

**Pull request merged**
