### PR TITLE
Removes birdstation and related files.

### LINKED ISSUE #12880: BirdBoat suit sensors map icons are misplaced
e6f4d1c3da8adbc426e6dec133a63177
Everyone is in space, except not.

### PR DESCRIPTION
**Pull request by Tokiko1**
Was asked to remove this due to maintaining issues it causes and unpopularity. Helps with #13132.

Also fixes #12880 I guess.

### CODE REVIEW

**Comment by SweaterKittens** [comment]
Sad to see it go :(  :-1: :-1: :-1:

**Comment by Firecage** [comment]
:-1: It's a fun map.

**Comment by Aranclanos** [comment]
>Was asked to remove this due to maintaining issues it causes and unpopularity. 

by who

**Comment by Shadowlight213** [comment]
:-1: all of bagil seems to love the map. Who asked to remove it?

**Comment by Iamgoofball** [comment]
:-1: because it pisses people off

**Comment by KorPhaeron** [comment]
I love this map please dont

**Comment by Firecage** [comment]
Also, I don't see it causing much more maintainability issues than any other map does.

**Comment by KorPhaeron** [comment]
Yeah, the maintaining issue will still have all the space Z levels, away missions, and other stations.

We need an overall fix not to just axe a random map

**Comment by newfren** [comment]
No birdboat is my bae

**Comment by bgobandit** [comment]
what kor said

**Comment by Hatfish** [comment]
All the unpopularity is just a meme, don't take it seriously.

**Comment by Supermichael777** [comment]
bird is an actually fun and playable station, unlike mini which feels cramped at 10 people
those things are both not the fault of the map but rather due to a problem with git-hubs changing method and suit sensors maps being fucked up

**Comment by GunHog** [comment]
:-1: Do not merge.
It is a fantastic low pop map. Your map differs greatly in design philosophy and that it is a dedicated low population map with many jobs disabled. 

It is currently being used incorrectly on Sybil, being run with populations greater than 20-30.  You cannot please everyone, Tokiko, and the ones who are not will yell the loudest. I do not believe your map is as unpopular as it seems. It does, however, need a maximum population cap.

**Comment by Jazaen** [comment]
Wait, isn't there a pop cap system in place for that?

**Comment by Cebasiz** [comment]
i liked it

**Comment by Strathcona** [comment]
Keep it in! Map diversity is one of the best things that's happened to tg in a while. Your map is different and a breath of fresh air, especially for low pop!

**Comment by Razharas** [comment]
It seems maintained
Only reason for a map removal is its lack of maintenance
Everything else is fixable with maintenance
Thus denied

**Comment by ike709** [comment]
Thank you for Razharasing.

**Comment by Aranclanos** [comment]
but who told you to remove it

**Comment by Iamgoofball** [comment]
^ yeah can you answer this op

**Pull request closed without merging**
