### PR TITLE
Just saiyan armor

### PR DESCRIPTION
**Pull request by TheTeenyTiny**
## About The Pull Request
To add a costume saiyan armor to game

## Why It's Good For The Game
Because it's fun and it matches the medhud

## Changelog
:cl:
add: new sprite for item
add: new code for item
code: changed some code in autodrobe.dm
/:cl:

### CODE REVIEW

**Comment by TheTeenyTiny** [comment]
sorry, wrong code base.... again...

**Comment by Tharcoonvagh** [comment]
wow

**Comment by ExcessiveUseOfCobblestone** [comment]
at least post a pic incase we want to steal smh

**Comment by TheTeenyTiny** [comment]
dreammaker_5J1DaZEJe8


Here, this is what it'll look like

**Comment by ExcessiveUseOfCobblestone** [comment]
lol based

**Pull request closed without merging**
