### PR TITLE
Removes the Gamer Cube in Delta Cargo

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
EDIT: I've altered this since the initial text came off as far more hostile than I wanted.
Changes up Delta cargo to remove the gamer cube, since it stands out too much from the surroundings. (Also, directional glass is something we should really be aiming to get rid of in most cases, especially when it's free standing panes such as it is here)
Old:
cube
New:
nocube

## Why It's Good For The Game
Keeps Delta cargo sensible- while gimmicky stuff isn't bad, it's preferable that it fits into its environment.

## Changelog
:cl:Inept
fix: Removed the gamer cube in Delta cargo.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Removing gamer cave 👎

**Comment by ATH1909** [comment]
Eh, I dunno, I think it has charm.

**Comment by bluetshirtguy** [comment]
no wage cage? unbased

**Comment by Serxule** [comment]
why do we want to get rid of directional windows?

**Comment by EOBGames** [comment]
> why do we want to get rid of directional windows?

really the simple reason is that it looks pretty bad- in cases like this, it would generally be better served with nothing at all rather than a stark thin wall. additionally, with some planned upcoming changes to visuals, directional windows are probably going to end up even worse in this regard, so it's best we try and remove most of them before that happens

**Comment by TheBonded** [comment]
Better idea, replace the directional windows with tinted directional windows from meta's nanite room

**Comment by Mothblocks** [comment]
border objects are annoying as shit in code

**Comment by Fikou** [comment]
> Better idea, replace the directional windows with tinted directional windows from meta's nanite room

those are so incredibly shit, you combine directional object code with opacity and you get a clusterfuck

**Comment by Acer202** [comment]
Don't you dare get rid of the funny cubicle before I get a chance to do a silly Office Space RP gag from it!

**Comment by Time-Green** [comment]
> Don't you dare get rid of the funny cubicle before I get a chance to do a silly Office Space RP gag from it!

To be fair, you can extremely easily construct it yourself with some gloves (minus the windoor)

**Review by Timberpoes — CHANGES_REQUESTED** [review]
Since this is a Maptainer PR I'm not going to dig too deeply behind the veil of this change.

Inept can't self-merge, so I'll be merging this at some point after 24h when the merge conflict is handled.

**Comment by Farquaar** [comment]
"Directional windows are ugly"
"From my point of view, the fulltile windows are ugly!"
jedi

**Review by Timberpoes — APPROVED** [review]

**Pull request merged**
