### PR TITLE
Adds a minimum account age for drones

### PR DESCRIPTION
**Pull request by tkdrg**
Currently two weeks. Experience on basil has proven the need for this.

### CODE REVIEW

**Comment by Shapsy** [comment]
:+1::+1::+1::+1::+1:

**Comment by bgobandit** [comment]
:+1:

**Comment by Bawhoppen** [comment]
goddamn hubbies ruining everything

**Comment by duncathan** [comment]
Pubbies are better for the server than Bawhoppen is but :+1: regardless

**Comment by Iamgoofball** [comment]
:-1:

drop it to 1 week please

**Comment by Cheridan** [comment]
2 is fine

**Pull request merged**
