### PR TITLE
More Window Flashing

### PR DESCRIPTION
**Pull request by ghost**
Added window flashing preference, added window flashing to a few procs like notify_ghosts and similar like notify_ghost_cloning, and pollCandidates. Now your ss13 window will also flash when an event triggers that alerts ghosts (rod, borers, swarmers, "do you want to play as X") and when you're put into a DNA scanner for cloning, defibbed, or SR'd.

:cl:
add: Window Flashing is now a preference
add: Your game window will flash when alerted as a ghost. This includes being revived by defibs/cloning and events such as borers, swarmers, revenant, etc.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>more fucking preferences

**Comment by Kromgar** [comment]
We need more preference tabs to hold all these prefs

**Comment by ShadowDeath6** [comment]
Add a preference to seperate your preferences into multiple tabs

**Comment by lzimann** [comment]
This will tie adminhelps/roundstart to the flashing, I don't mind these, but I hate those notifications about cloning/defibbing/whatever and I don't want yet another annoying thing for this(there's already the annoying sound + annoying in-game notification + the chat notification).

**Comment by ExcessiveUseOfCobblestone** [comment]
Next PR make SS13 unable to be closed if there's a notification.

Next PR make computer start and ss13 play if there's a notification.

**Comment by uraniummeltdown** [comment]
I could make adminhelps/PMs and roundstart ignore window flashing pref, that way you could have it disabled and still get flashes for those

**Comment by optimumtact** [comment]
I think that's a good idea, do that and I'll merge this, ti's a good feature

**Comment by uraniummeltdown** [comment]
@optimumtact done

**Comment by optimumtact** [comment]
I uh can't merge this anymore, ask @KorPhaeron or @AnturK

**Comment by ShadowDeath6** [comment]
F

**Pull request merged**
