### PR TITLE
Fixes food crafting lag.

### LINKED ISSUE #18025: Crafting menu now annoying to use.
Each items part is now overly large and the crafting menu now feels overly clunky to and annoying to use. And a few times when I tried to go to the foods subsection, the crafting menu just decided to stop working and crashed.

### PR DESCRIPTION
**Pull request by Iamgoofball**
By splitting up all the food items into separate categories, you're not trying to format a list of 300+ datums at once. I guess it's cheating to call this a fix but honestly this is the best solution. Also, it's actually organized now for cooking so quality of life.

:cl: Iamgoofball
fix: Fixed the lag when opening the foodcrafting menu by splitting everything up into categories.
/:cl:

Fixes #18025

### CODE REVIEW

**Comment by Incoming5643** [comment]
:-1: on principle because this just masks the problem and also makes people less likely to optimize Tgui

**Comment by Iamgoofball** [comment]
@Incoming5643 the actual problem is we have too many fucking food items

**Comment by TechnoAlchemisto** [comment]
that's a stupid reason to thumbs down something, let the players fucking cook don't leave an entire job unplayable just because you think someone won't fix TGUI because it lets people use the cooking menu.

thanks goof

**Comment by Fox-McCloud** [comment]
:+1: 

Not like this can't be changed back once it's optimized (though personally I think multiple food categories is better anyway).

**Comment by Iamgoofball** [comment]
lost the election, campaign PRs closing down

**Comment by Iamgoofball** [comment]
https://www.youtube.com/watch?v=_wldE_4xjVQ

**Comment by KorPhaeron** [comment]
This isn't really a fix but neersighted is dead so oh well

**Comment by PKPenguin321** [comment]
Oh that's why the other pr was closed

**Pull request merged**
