### PR TITLE
Converts the new span_ procs to macros, fixing a few oversights/errors along the way

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

This is a partial re-implementation of https://github.com/tgstation/tgstation/pull/59645

image
image

oranges has expressed a desire for the span_ procs to instead be macros.

I agree. Even though it's a small micro-optimisation, a well contained macro can be self-linting. I've already caught one edge case thanks to this in launch_pad.dm:
image

Similarly, there was an edge case where a `[` was escaped inappropriately (that errored out) in watercloset.dm and a case where a `]` that should probably have been escaped actually wasn't in robot_defense.dm

I have opted to make an exception to the ALLCAPS convention for these macros.

I have guaraded these macros in parenthesis. In doing so, additional error states can be captured as part of the build process as malformed inputs will then cause errors and prompt further investigation.

## Why It's Good For The Game

Negligible difference or not, there are benefits to using macros that I believe outweigh their detriments.

It IS a micro-optimisation for avoiding proc overhead, but also macroifying these procs also catches a number of semantic errors that would have otherwise gone missed.

## Changelog
:cl:
fix: Chat feedback is improved when setting down briefcase launchpads.
fix: Urinals no longer alert you about the letter "i" being stuck to your hand in certain edge cases.
/:cl:

### CODE REVIEW

**Comment by Timberpoes** [comment]
@ninjanomnom You'll be interested in this in any event since I know you expressed various arguments for why procs are beneficial.

I tried looking back in your message history on Discord to see if you outlined your pro-proc reasoning in a digestable format, but I'm too smooth brain to connect all the various dots.

I'm interested to see the arguments for having them as procs laid out here. You didn't seem to get a chance to outline your thoughts on procs vs. macros in the former PR (linked at the top of the body) before it was merged.

**Comment by Arokha** [comment]
No obvious solution to this, but I will say that for whatever reason, the compiler does not optimize macros like this despite them being static, so these are slower than just strings, I guess because it's determined to invoke some kind of variable interpolation routines or something, I dunno. Maybe it doesn't understand how to do this sort of 'inside-out' static optimization that it would take to wrap the macro's static string around the places it's used? I have no idea.

For example:
```
#define SPAN_WARNING(str) ("<span class='warning'>[str]</span>")

// Less ops at runtime
world << "<span class='warning'>Warning!</span>"

// More ops at runtime
world << SPAN_WARNING("Warning!")
```

Between procs and macros, I'm sure macros are faster, but just mentioning in case the unintuitive performance loss of even using macros is not apparent.

**Comment by LemonInTheDark** [comment]
You can think of using the define as like wrapping a string insert with a string insert
so 
`"<span class='warning'>[test]!</span>"`
becomes
`"<span class='warning'>[[test]]!</span>"`
I assume this is because defines do the formatting at runtime, instead of merging the strings as a part of the compile process. Why they do this, I have no idea.

**Comment by Timberpoes** [comment]
> 
> 
> You can think of using the define as like wrapping a string insert with a string insert
> so
> `"<span class='warning'>[test]!</span>"`
> becomes
> `"<span class='warning'>[[test]]!</span>"`
> I assume this is because defines do the formatting at runtime, instead of merging the strings as a part of the compile process. Why they do this, I have no idea.

There is actually a variant of the macro I can use that is pure text substitution with none of the downsides.

See the following research from http://crucible.lulzsec.co.uk/

Test code:
```
#define MACRO_SUBSTITUTE_VARIANT(str) "<span class='someclass'>[str]</span>"
#define MACRO_STRING_CONCAT_VARIANT(str) "<span class='someclass'>" + str + "</span>"

/proc/proc_variant(str)
    return "<span class='someclass'>[str]</span>"

/world/New()
    world.log << "<span class='someclass'>words and stuff go here</span>"
    world.log << MACRO_STRING_CONCAT_VARIANT("words and stuff go here")    
    world.log << MACRO_SUBSTITUTE_VARIANT("words and stuff go here")
    world.log << proc_variant("words and stuff go here")
```

I get the following output
```


// path: /world/New
// display/inheritance name: New
// signature (WIP): /world/New()
	GETVAR subvar world field "log" // L8 (world.log << "<span class='someclass'>words and stuff go here</span>")
	PUSHVAL "<span class='someclass'>words and stuff go here</span>"
	OUTPUT
	GETVAR field "log" // L9 (world.log << MACRO_STRING_CONCAT_VARIANT("words and stuff go here"))
	PUSHVAL "<span class='someclass'>words and stuff go here</span>"
	OUTPUT
	GETVAR field "log" // L10 (world.log << MACRO_SUBSTITUTE_VARIANT("words and stuff go here"))
	PUSHVAL "words and stuff go here"
	OUTPUT_FORMAT "<span class='someclass'>ÿ</span>" 1
	GETVAR field "log" // L11 (proc_variant("words and stuff go here"))
	PUSHVAL "words and stuff go here"
	CALLGLOB 1 "/proc/proc_variant"
	OUTPUT
	END
```

So I can actually go ahead and use a string concat variant macro and potentially have it decompile into the same as if I'd just used a direct string.

Want me to try this?

**Comment by LemonInTheDark** [comment]
I hate byond
Yes

**Comment by Timberpoes** [comment]
image

Everything seems to work on the face of it with string concat macros.

**Comment by LemonInTheDark** [comment]
I wish to unknow this information

**Comment by Timberpoes** [comment]
> 
> 
> I wish to unknow this information

Would you like to unsubscribe from Byondfacts~~?

**Comment by Arokha** [comment]
> So I can actually go ahead and use a string concat variant macro and potentially have it decompile into the same as if I'd just used a direct string.
> 
> Want me to try this?

THIS is good to know. I'll change ours to this.

**Comment by Watermelon914** [comment]
> > You can think of using the define as like wrapping a string insert with a string insert
> > so
> > `"<span class='warning'>[test]!</span>"`
> > becomes
> > `"<span class='warning'>[[test]]!</span>"`
> > I assume this is because defines do the formatting at runtime, instead of merging the strings as a part of the compile process. Why they do this, I have no idea.
> 
> There is actually a variant of the macro I can use that is pure text substitution with none of the downsides.
> 
> See the following research from http://crucible.lulzsec.co.uk/
> 
> Test code:
> 
> ```
> #define MACRO_SUBSTITUTE_VARIANT(str) "<span class='someclass'>[str]</span>"
> #define MACRO_STRING_CONCAT_VARIANT(str) "<span class='someclass'>" + str + "</span>"
> 
> /proc/proc_variant(str)
>     return "<span class='someclass'>[str]</span>"
> 
> /world/New()
>     world.log << "<span class='someclass'>words and stuff go here</span>"
>     world.log << MACRO_STRING_CONCAT_VARIANT("words and stuff go here")    
>     world.log << MACRO_SUBSTITUTE_VARIANT("words and stuff go here")
>     world.log << proc_variant("words and stuff go here")
> ```
> 
> I get the following output
> 
> ```
> 
> 
> // path: /world/New
> // display/inheritance name: New
> // signature (WIP): /world/New()
> 	GETVAR subvar world field "log" // L8 (world.log << "<span class='someclass'>words and stuff go here</span>")
> 	PUSHVAL "<span class='someclass'>words and stuff go here</span>"
> 	OUTPUT
> 	GETVAR field "log" // L9 (world.log << MACRO_STRING_CONCAT_VARIANT("words and stuff go here"))
> 	PUSHVAL "<span class='someclass'>words and stuff go here</span>"
> 	OUTPUT
> 	GETVAR field "log" // L10 (world.log << MACRO_SUBSTITUTE_VARIANT("words and stuff go here"))
> 	PUSHVAL "words and stuff go here"
> 	OUTPUT_FORMAT "<span class='someclass'>ÿ�</span>" 1
> 	GETVAR field "log" // L11 (proc_variant("words and stuff go here"))
> 	PUSHVAL "words and stuff go here"
> 	CALLGLOB 1 "/proc/proc_variant"
> 	OUTPUT
> 	END
> ```
> 
> So I can actually go ahead and use a string concat variant macro and potentially have it decompile into the same as if I'd just used a direct string.
> 
> Want me to try this?

This was actually my original implementation. It's also because you can use these in constant string expressions because they automatically evaluate into a constant expression.

**Pull request merged**
