### PR TITLE
C20r Buff | M90 Removal

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR is a alternative to Kor's M90 Carbine removal PR located here: https://github.com/tgstation/-tg-station/pull/15730

This PR effects the following changes.
- M90 Carbine is removed from the Operative Uplink. Is now a admin only item.
- C20r SMG is buffed to compensate.
- C20r bullets now deal 30 damage per round, taking it to a four hit crit down from a five hit crit. This in conjunction with the 2rd Burst makes two bursts needed to crit a target.
- C20r has lost its stamina damage, if you want to stun a target take a Donksoft weapon or Taser Slug rounds for the Bulldog (or steal a taser).
- Price remains unchanged.
- Ammo bumped up to 24 rounds a mag.

Again, this is a alternative to the M90 removal, and is meant to simply buff up the C20r to be more competitive as a long arm as well as make the weapon consistent with stun weapons. Its also something I've wanted to do for a while.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Ehhh
Not fond of this either

**Comment by Steelpoint** [comment]
I also wanted to look at adding a cheap and expensive grenade launcher to the uplink (cheap for single shot, expensive for multi-shot) as well as slightly buffing the SAW by removing its two-handed requirment.

But the former is likely past my coding abilities and the latter can be for another PR if this is accepted.....

**Comment by Lumipharon** [comment]
how does this address the actual issue?
ie: cheap guns and excessive tc's?

**Comment by Steelpoint** [comment]
The only problem with Ops is their low pop and high pop win rate. I don't think adjusting TC's is the right way to fix the issue. I think scaling op population is the only real answer to this issue.

I've been planning this PR for a while but I was going to wait until my other PR is closed/merged. But this is better time than any to put it forward and it addresses my concerns with a ballistic gun having a stun ability. It also buffs the c20r to be competitive and removes the extra bloat of two longarms.

**Comment by Steelpoint** [comment]
Honestly the only time, stats wise, Ops is a issue is twenty to thirty people range, and the sixty to eighty people range.

**Comment by SweaterKittens** [comment]
To be honest, I kind of like having both the M90 and the C20 side by side on the uplink. While most people will opt for the M90, I still always go for the C20, being a nostalgic bastard. It's nice that you have the choice between brute firepower and being able to down someone so as to easily finish them.

**Comment by Steelpoint** [comment]
The problem is the SAW should be the choice for overwhelming firepower.

Right now we have two weapons, the M90 and the SAW, that both compete for being that raw firepower dealer.

its just that right now there is no incentive to use the SAW over the M90 at all. Your only advantage being you get 50 rounds to the M90's 30.

But in return you get a weapon that is one handed, has a underslung grenade launcher that will pretty much kill anyone on contact, as well as being far more economical to buy and support than the SAW.

This is why I would like to buff the SAW if this PR gets the go ahead. But right now I think the M90 is the best Op gun in the game and trumps all other choices. The reason you took the Bulldog was because it was free and it was still powerful by itself, but with that gone now you can afford (and have to) the M90.

I think slightly buffing the C20r to be a bit more powerful, increase its ammo a bit, is a good choice.

**Comment by SweaterKittens** [comment]
Oh that's true, fair enough. I certainly wouldn't mind seeing one of my favorite guns getting a little stronger, although I really like the stamina damage aspect of it. However, I certainly don't think the L6 needs a buff, in the right hands it's already a two-shot crit with a near-limitless supply of ammo. The fact that the M90 is competing for that spot is indicative of how good it is. Perhaps, like the silencer attachment for the C20/Stetchkin, we could get an aftermarket grenade launcher attachment? That way we're not trying to balance prices/firepower around a gun that comes stock with a grenade launcher.

**Comment by Steelpoint** [comment]
The SAW is currently a three shot crit weapon, with it dealing 45 damage per bullet.

**Comment by Supermichael777** [comment]
the saw is an instant kill if you hit with the whole burst.

**Comment by KazeEspada** [comment]
Saw won a lategame nukeops because it shredded the captains durand.

**Comment by Lumipharon** [comment]
SAW is a 2 handed shitshow.
M90 not only is single handed but the noobtube is actually genuinely useful in a lot of situations (ie: blasting a group of nerds through a doorway or around a corner) this isn't something that is available through another gun.

The m-90 is also not comparable to the c-20r. The C-20r is not a killing weapon (if you use it this way it's highly inefficient), it's for the quick takedown with 2 hit stun, which also cripples movement.

While I do agree that the m-90 is objectively better then both the c-20r and SAW, this is due to it's almost identical cost of the c-20r, and the SAW's huge ass nerf to damage/2handed shit etc.

This buff to the c-20r literally just makes it a slightly weaker m-90 without the tube.

And finally, there is a pr up for adding op number scaling, but it's closed because bugs. And ops got given 50tc extra by default WHICH IS a signiciant deal at low pop, so yes that is an issue.

**Comment by Cebasiz** [comment]
literally not necessary

the C-20R is not the M90 because it has no grenade launcher; these two things are not alike and removing a niche is totally pointless.

if it's too strong, just increase the cost. what is with all of these crazy "oversolutions" to a problem that's barely fucking there in the first place

if you want to buff the SAW fine go for it it really needs the help but the SAW is not the M90 either so

**Comment by Lumipharon** [comment]
Why.

**Pull request merged**
