### PR TITLE
Adds a 15 TC uranium bottle for traitor virologists

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Added a 15 TC uranium bottle for traitor virologists
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
upvoted own pr

i hate this pr now

**Comment by Togopalis** [comment]
not very creative for a job-specific traitor item, just an easier way to spread deadlier viruses at the start of the round

**Comment by Mey-Ha-Zah** [comment]
Why not design a new chem that allows the virus to spread through a new way, or new symptoms

**Comment by Buggy123** [comment]
Why not a box full of a comprehensive array of virus foods and other useful reagents?

**Comment by XDTM** [comment]
You can make symptoms with a reserved tier range and restrict it to a special chem if you wanted to do what @Mey-Ha-Zah suggests.

Thing is, the whole set of harmful symptoms is pretty much traitor-only already due to policy; i don't think traitors should get any extra help when producing viruses, since the harmful symptoms are already designed with traitor use in mind and screwing with the timing means viruses too deadly too early.

If you want to add viro-only traitor gear look into giving more avenues of spreading disease.

**Comment by Armhulen** [comment]
@The-clown-known-as-Pepe you wanna say something say it to my FACE

**Comment by calzilla1** [comment]
Isnt it like a tator item policy that it cant be something you can get on station?

**Comment by Mey-Ha-Zah** [comment]
Like a T item for virologists could be carrier strain. A simple bottle with something that makes you a carrier of your virus, but not affected by it.

**Comment by DaedalusGame** [comment]
Is this kudzu for botanists and omnilathe for researchers part deux

**Comment by BeeSting12** [comment]
spoon feed me please

**Comment by Iamgoofball** [comment]
this is the biggest waste of 15 tc I've ever seen

**Comment by Iamgoofball** [comment]
it takes like 5 minutes to get uranium fever satisfied

**Comment by lzimann** [comment]
if you are going to add job-specific uplink items, at least make sure it's something unique and not just something to speed up the job like you are doing here

**Pull request closed without merging**
