### PR TITLE
Fixes new regal rat sprite & removes duplicate file

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Did you know that we had a `mob/animal.dmi` and a `mob/simple/animal.dmi`?
Meyhazah didn't, someone messed up some icon organisation I think!

Proof that nothing used this path:
image

## Why It's Good For The Game

Actually implements the new sprite and removes a fun trap someone put in as spriter engagement.

## Changelog

:cl:
fix: Removes a duplicate file which was preventing the new regal rat sprite from being used.
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
Thanks sprite files. God I hate it when this happens.

**Comment by Jacquerel** [comment]
Ok hold on while I restore some lost icon states

**Comment by Jacquerel** [comment]
Should be good now

**Comment by Mey-Ha-Zah** [comment]
well don't I feel stupid

**Comment by Jacquerel** [comment]
> 



> Screenshot tests failed!
> 
> [Download zip file of new screenshots.](https://file.house/3aaR.zip)
> ## Diffs
> See snapshot diffs
> ## Help
> What is this?
> I am changing sprites, it's supposed to look different.
> This is a false positive.

This is proof that it worked this time

**Pull request merged**
