### PR TITLE
Adds cooldown to vending machine purchase messages

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #https://github.com/tgstation/tgstation/issues/43535
:cl: ShizCalev
fix: Spamming purchases at a vending machine now won't spam chat as well.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
There's a guy in that issue report that likes this "issue" and uses it to help them know how much stuff they've bought for mining. I say we leave it in.

**Comment by 81Denton** [comment]
That guy can just count his clicks or right click the pile instead

**Review by 81Denton — APPROVED** [review]

**Comment by OverlyGeneric** [comment]
@ATH1909 /tg/ doesn't like bugs, even ones that can be considered unintended features.

**Comment by HomocidlePancakes** [comment]
@OverlyGeneric /tg/ doesn’t like fun. /tg/ can’t balance.

**Comment by Daxxed** [comment]
If it soothes them to have it otherwise I dont mind adapting, I survived all the controversial PRs this will be fine

**Pull request merged**
