### PR TITLE
replaces nukie tablet sprite with PDA

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Replaces the nuclear operative tablet icon with a GAGS PDA one, entirely deleting the modular tablet DMI file as this was the last place it was ever used.

Looks like this
image

tablet for reference
image

## Why It's Good For The Game

Follow up to https://github.com/tgstation/tgstation/pull/71507 - Removes a DMI file and the need to resprite apps yet another time (down to 3 now) for every NTos program, replacing it with the tablet instead.

## Changelog

:cl:
imageadd: Nukie tablets are now using PDA sprites w/ GAGS instead of tablets.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
actually inversed it to make it closer to the tablet version

image

tablet for reference
image

**Comment by SkeletalElite** [comment]
Does the Disk tracker's on sprite pointer still work with the new sprite?

I believe part of the reason it kept the tablet is that tablet's support the on sprite pointer for the tracker in addition to the UI and PDA sprites dont.

**Comment by JohnFulpWillard** [comment]
I show off all icons for the programs on all 4 hardware types in my linked PR, yes it does work, and no the reason for keeping it wasn't that app it was because it was the only required tablet with no alternative sprite.

**Comment by unit0016** [comment]
might be good to replace the PDA with a detomatrix on it with just a detomatrix disk as well?

**Comment by JohnFulpWillard** [comment]
I think that ironically hides the fact its there to new players, who don't know that *this* specific PDA spawns with a cartridge, but finding them together is a great way to show that it's there.

**Pull request merged**
