### PR TITLE
Changing contents of the safe

### PR DESCRIPTION
**Pull request by TheVekter**
- Added shot glasses to the game, ported over from NT. Spawns in the Booze-o-Mat at round start. (We had the sprite, why has no one else done this)
- Changed the contents of the safe to something a bit more appropriate - kept the bear pelt, added a bottle of top-shelf vodka, 2 shot glasses, a Russian revolver, and a .357 speed loader.
- Added a new premium style of vodka. Can only be obtained from safe. (Thanks to @Nienhaus for the sprite!)

### CODE REVIEW

**Comment by Iamgoofball** [comment]
only problem with this is you can't open the safe reliably

**Comment by dannno** [comment]
it's not like this is worse than before
add shot glasses to the bartender's vendor

**Comment by TheVekter** [comment]
You can, it just takes some doing. If there's a problem with the safe code we should fix it in another PR.

@dannno Will do as soon as I figure that part out.

**Comment by vista-** [comment]
@Iamgoofball, there is a method that can open the safe all the time.

not telling :^)

**Comment by paprka** [comment]
this pr literally only adds shot glasses, wtf

**Comment by TheVekter** [comment]
>WIP

I'm working on it, having problems with the map.

**Comment by TheVekter** [comment]
alright there, now we're just waiting on the sprite from quilty and we'll be in business.

**Comment by TheVekter** [comment]
Heh, I must've added the vodka to the safe earlier tonight, then tried to do it again. My bad. Anyway, we're g2g now.

**Comment by paprka** [comment]
Can you list the contents of the safe now?

**Comment by TheVekter** [comment]
Updated in OP.

**Comment by Lumipharon** [comment]
I can't remember, did the russian revolver get babby nerfed to only work on yourself? ( I remember a PR for that was around), or was it simply removed from the map(s)?.

If it was only removed, I have a hilarious mental image of powergamers rushing the safe with stethoscope in hand to get the gun.

**Comment by TheVekter** [comment]
It does only work on yourself (tested 2 days ago, tells you it will only
fire if you shoot yourself).

**Pull request merged**
