### PR TITLE
lead pipe

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request

https://github.com/user-attachments/assets/209f8e0b-4202-4e06-8b6d-e5d1f659824b
## Why It's Good For The Game
image
## Changelog
:cl: grungussuss
sound: lead pipe has sound
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Look. This is funny. I would garrote myself if I had to endure this ingame.

**Comment by Sadboysuss** [comment]
> Look. This is funny. I would garrote myself if I had to endure this ingame.

lead pipe is a rare maint spawn and there is like 5 mapped in instances throughout all maps so should be fine

**Comment by SmArtKar** [comment]
> Look. This is funny. I would garrote myself if I had to endure this ingame.

The sound isn't even that jarring, the hit ones are pretty good - maybe make the drop sound exclusive to a rare subtype/variable (prob(1)?)?

**Comment by notfrying1pans** [comment]
i dont like the hit sound to be honest, i do agree with smartkar though the drop sound should be rare

**Comment by GPeckman** [comment]
> > Look. This is funny. I would garrote myself if I had to endure this ingame.
> 
> The sound isn't even that jarring, the hit ones are pretty good - maybe make the drop sound exclusive to a rare subtype/variable (prob(1)?)?

I think bluespace RPEDs have something like this already, so it wouldn't be unprecedented

**Comment by EricZilla** [comment]
Maybe it should only make the horrible clanging noise if you get disarmed to drop it, not intentionally drop it?

**Comment by DrAmazing343** [comment]
If it annoys you, IC issue. Take It From Them. The Lead Pipe is an object of Assistant honor. It is unbaggable. There is no suit slot that can accommodate such a formidable weapon. If you mention objects containing "Bluespace" and "Holding" within their name I will hit you over the head with The Lead Pipe. If you do not enjoy the sound, dishonor the Assistant by disarming them of The Lead Pipe, and do as you will with it.

I would adore this sound being added. Fuckin' lov me pipey.

**Comment by nianjiilical** [comment]
okay now whens the l4d2 frying pan

**Comment by ZephyrTFA** [comment]
How do I delete someone else's pr

**Pull request merged**
