### PR TITLE
Sec armor nerf: Eternal controversy edition

### PR DESCRIPTION
**Pull request by Bawhoppen**
:cl:
tweak: Sec armor is now mildly worse.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
NO

**Comment by Bawhoppen** [comment]
my problem is that steelpoint made regular sec gear as good as what swat gear was before and then left swat gear the same and now they refuse to merge me buffing swat gear as compensation

**Comment by TechnoAlchemisto** [comment]
im sorry you're sad

**Comment by Cheridan** [comment]
>it's a "lets crap on sec just so that stuff cargo techs can order will be better than them" episode

**Comment by Bawhoppen** [comment]
don't give me that cheri thats a nonsense argument

**Comment by Cheridan** [comment]
it's literally what you're doing?

**Comment by Bawhoppen** [comment]
its a legitimate change to the dynamic of security power and their armor, not powercreep

**Comment by PKPenguin321** [comment]
It's also nerfing sec so cargo can order better gear than them

:+1: either way

**Comment by MMMiracles** [comment]
I thought the whole point of security's armor was to make them resilient against regular crew but still be vulnerable to antag items (the whole point of shit like the esword or revolver having high AP)?

Isn't nerfing the armor just kinda making it useless even against regular crew?

**Comment by KorPhaeron** [comment]
Lets not do this again

**Pull request closed without merging**
