### PR TITLE
Causes malfunctioning AIs who leave the station to lose the round

### PR DESCRIPTION
**Pull request by ghost**
Simply put, if _all_ malfunctioning AIs are off the station, then they will fail the round. Theoretically, this will not interfere with mulligan (it uses the same code that the AI dying uses). This is to prevent balance issues that have occurred en masse in the past.

Fluff-wise, the AI's connection to the system is detected and severed by exiting the station. They can then no longer flood the system with runtimes like they do if they override.

Also fixes some kekworthy grammar in the messages.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
while i support this, it may be a controversial change and a feedback thread might be a good idea before this is merged

**Comment by vista-** [comment]
inb4 metagaming HoS / Captain demands the AI to unbolt from the floor and tosses it into the Minisat teleporter set to Mining for good measure

**Comment by PKPenguin321** [comment]
that is some intense meta which would be outright bannable
not an issue with this pr in particular

**Comment by Jalleo** [comment]
This only solves a problem of the bigger issue though we need to rework the entire mode.

**Comment by Cheridan** [comment]
@vista if you're at that point then you've already lost Malf mode

**Pull request merged**
