### PR TITLE
Un-codersprited fishes and the aquarium.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
I cannot make features and the such this month, so I may as well take some time to improve AnturK's abysmal codersprites. Some came out decent, some pretty good. Hopefully you can guess that's a catfish now.

This PR includes a small bit of code changes concerning the aquarium and one of its props, both pretty bad-looking. I had to modify a dozen lines of code so that the aquarium stuff is aesthetically layered correctly (splitting it in multiple icon states), while also replacing the 'rock floor' prop with 'sand' because it looked pretty bad and hard to read.

The lanternfish, goldfish and pufferfish still need to be resprited. I'll get to it in a later PR.

## Why It's Good For The Game
So, I've recently checked out the sprites for fish on Goonstation, and remembered how bad ours are. I drew inspiration from the "googlier" eyes some of their fishes have, though nothing was copied. Hower, I'm still crediting Goonstation for reminding me how awful our codersprites are.

Here's the after and before (angel fish missing from the latter 'cuz I was distracted):
 new_ones

 old_ones

In-game screenshot coming later, I need to update/downgrade my byond venrion because 1624 and 1625 are busted.

## Changelog
:cl:
image: Resprited several fishes, and the aquarium.
/:cl:

### CODE REVIEW

**Comment by Vect0r2** [comment]
Can

**Comment by Loafin34** [comment]
I don't think the donkfish is smiling, but it still looks pretty good.

**Comment by RikuLeinonenVuoksi** [comment]
> I don't think the donkfish is smiling, but it still looks pretty good.

I don't mind the smile on the new sprite, but yeah those are clearly gills, there's even a tiny mouth on it further in the front.

**Comment by Ghommie** [comment]
I know that wasn't a smile on the ol' donkfish. I just took the liberty of respriting things from scratch, often disregarding their previous looks, take for example the catfish or the plasma tetra (the little fishie to its right), overall it's a bit of characterization.

**Pull request merged**
