### PR TITLE
Adds green version of the plaid skirt.

### PR DESCRIPTION
**Pull request by TehZombehz**
Adds a green version to the plaid skirt set (currently has blue, red, and purple versions) to the Clothesmate vendor.

This is my first attempt at a PR.

### CODE REVIEW

**Comment by Niknakflak** [comment]
Posting for the record

**Comment by ShadowDeath6** [comment]
Kawaii~

**Comment by WJohn** [comment]
:+1: On sprites.

**Comment by TehZombehz** [comment]
I was told to close and reopen it, so I did.

**Comment by Jordie0608** [comment]
Who by and why?

**Comment by Incoming5643** [comment]
to restart travis I'd wager

**Comment by KorPhaeron** [comment]
They asked me how to restart travis, and I told them there was a proper way to do it involving the travis website, but that I personally am I a lazy shit and close/reopen

**Comment by Jordie0608** [comment]
It's just a single button to restart travis you scrub

**Comment by Chocobro** [comment]
:+1:

**Pull request merged**
