### PR TITLE
Adds radio jammer

### PR DESCRIPTION
**Pull request by AnturK**
## Radio Jammers
- 10 TC
-  7 tiles range (aka whole screen)
-  Mangles outgoing radio messages ~~and speaker.~~ (message only for consistency with processor failure)

Very simple traitor item. As a alternative to emp , this is specialized tool.
Might be bit too strong for the price, i'm open to any suggestions.

Also need some opinions if moving this to flag turf and making tracking more involved is worth the performance.

Non-codersprites welcome.

:cl:
add: Traitors now have access to radio jammers for 10 TC
/:cl:

### CODE REVIEW

**Comment by Steelpoint** [comment]
Interesting idea.

However, the moment any sees scrambled comms from a unknown person is instantly going to telegraph to the crew that there is a Traitor on board who has likely just killed someone, and has a radio jammer on them.

**Comment by RemieRichards** [comment]
I'm not sure of the exact effect, but I know a telecomms setup with one of the machines missing produces garbled comms, it may be the ```stars()``` proc as used here, but I forget.

if you can make this the same as the tcoms' one, then you've cut out the meta.

**Comment by Steelpoint** [comment]
Unfortunately that never practically happens in game, as soon as garbled comms are seen then everyone is going to know what's going on, 99.9% of the time its going to be a radio jammer.

**Comment by RemieRichards** [comment]
It's still an improvement over "this is guaranteed to be a traitor"

**Comment by Steelpoint** [comment]
That takes it from 'guaranteed to be a traitor' to 'its near 100% guaranteed to be a traitor'.

In the past several months since I started playing SS13 again I've yet to see any garbled comms in game.

I'm not trying to suggest that the meta will make this item worthless, the fact it stops people from communicating their postion, and hides their name, might make it a worthwhile item on its own.

**Comment by AnturK** [comment]
I'll take a look how garbled comms are done currently , probably good idea to make these indistinguishable.

**Comment by AnturK** [comment]
Dropped the voice garbling, processor failure does not change names right now.
Should the jammer do it ? Knowing who says the garbled message would make this less effective

**Comment by GunHog** [comment]
Why make it garble? Just block them entirely. If I can pay 2TC for several screen wide, radio killing tools, why would I pay 10TC for something that has a strong tell?

**Comment by XDTM** [comment]
On the other hand, @GunHog, this gives no tell to the victims, has no side effects, is always on, and is not consumed while using it.

**Comment by Cebasiz** [comment]
EMP is so plentiful making it consume is pretty useless anyway

10 tc is way, way too much for a range-limited comms blocker imo.

**Comment by jughu** [comment]
>when a garbled message would come it instantly know its traitor
>implying they would scream HELP X IS TRAITOR anyways

**Comment by GunHog** [comment]
>when a garbled message would come it instantly know its traitor
implying they would scream HELP X IS TRAITOR anyways

Which makes the device kind of pointless, no?

**Comment by Anonmare** [comment]
For 2TCs I can get an EMP flashlight that disables a person's headset AND any energy weapons/flashes they're carrying and they're extra fucked if they're augged or have certain implants.

**Comment by jughu** [comment]
Altough still add this we could use it for gateway missions and such or special admin events

**Comment by GunHog** [comment]
>>Why make it garble? Just block them entirely. If I can pay 2TC for several screen wide, radio killing tools, why would I pay 10TC for something that has a strong tell?

>For 2TCs I can get an EMP flashlight that disables a person's headset AND any energy weapons/flashes they're carrying and they're extra fucked if they're augged or have certain implants.

Yep. We should really make it block instead of garble.

**Comment by AdamElTablawy** [comment]
Either make it block or reduce the price significantly. An EMP implant or flashlight accomplishes the same, for cheap.

**Comment by AnturK** [comment]
Aw, i didn't get to update << to to_chat

**Pull request merged**
