### PR TITLE
Atmos holosigns have powercells

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
This PR adds upgradeable power cells to atmos holosigns creators, for each holobarrier made the power consumption increase untill it goes to zero.

Also this PR adds a new "machine" that can hold the holobarrier creator and powers it up by using power from the APC, it is made with just 5 sheets of metal and can be deconstructed by using a welder.

## Why It's Good For The Game
Infinite barriers that can stop heat and air for no cost is bad

## Changelog
:cl:
add: power cells to the atmos holosign creators
tweak: increased the amount of barriers atmos projector can make
add: holosign creator holder that can hold one atmos holosign creator to power it up as long as there is power in the APC
/:cl:

### CODE REVIEW

**Comment by trerri** [comment]
Raise the cap on atmos barriers

**Comment by Tlaltecuhtli** [comment]
remove the cell needs from stuff that gives no ingame advantage (jannie, doc)

**Comment by MrDoomBringer** [comment]
image
why not just use a recharger??

**Comment by Barhandar** [comment]
Idedplsnerf
> why not just use a recharger??

Can rechargers even be used for this without messing them up?

**Comment by Ghilker** [comment]
holosign creators can't be used in rechargers, also the holder is to have an easy way to maintain a barrier by using the station power instead of the cell without the pain of building the necessary machine frame, boards and all the component to make a recharger.

**Comment by wesoda25** [comment]
This kinda feels like an unnecessary over-complication of a straightforward item.  Just make it so that they can be recharged through rechargers.

**Comment by Jared-Fogle** [comment]
> Infinite barriers for no cost is bad

Why?

**Comment by Ghilker** [comment]
> > Infinite barriers for no cost is bad
> 
> Why?

Because that's the bad thing, how they produce those holobarriers? by magic? They use power cells at least.

**Comment by Barhandar** [comment]
So, you have no game design justification for this change, just "MUH REOLEESM"?

**Comment by CRITAWAKETS** [comment]
adding stationary versions of the barrier projectors that draw off APC power would be really good to add after this PR

**Comment by itseasytosee** [comment]
Seems annoying. Could you please elaborate more on why this is good for the game.

**Comment by Ghilker** [comment]
Consistency, things need power to work, now holosigns need power to be on.

**Comment by Jared-Fogle** [comment]
Space Station 13 is a video game, it's not real life. I don't see a point to giving everything power cells. If you want to nerf the atmos holosign, just do that--this doesn't need to be applied to everything.

**Comment by MrDoomBringer** [comment]
fun game design > realism
also this is hardly a consistency change as there are probably more things that technically should use power cells but don't currently

**Comment by itseasytosee** [comment]
Tons of things in this game use should probably use power but don't for convince.
Such as
-CE's tools
-flashes
-laser tag guns recharge forever
-flashlights
-pdas
-launch pads
-radio headsets
-emergency radios
-escape pod computers
-lighter never run out of fuel
-Camra
-Universal Recorder
-Light Replacer
-All the assembly items
-Vapes
-Health anylyzers
-Huds
-mourge trays
You gonna add bateries to all of these?

**Comment by Ghilker** [comment]
-CE's tools : much more used and they don't have a "only walk through" option
-flashes : internal battery, one use
-laser tag guns recharge forever : special battery or just a small laser that consumes nothing
-flashlights : you can see better. many flashlights can be active for hours
-PDAs : they consume little power
-launch pads : connected to station powernet
-radio headsets : minibattery or radiowave powered
-emergency radios : minibattery
-escape pod computers : escapepod battery
-lighter never run out of fuel : lighers don't use battery
-Camera : literally attached to the wall
-Universal Recorder : small battery dont consume much
-Light Replacer : mecanical
-All the assembly items : small battery, little power
-Vapes : who the hell added those
-Health analyzers : small battery
-Huds : small battery
-mourge trays : powernet

now example: holofan, can stop heat and air at no cost for as long as you want
another: janitor barriers, can't run through it and it stays forever
another: medical barriers, can't go through if you are infected, easy spot of fake viruses and easy medbay containment

**Comment by itseasytosee** [comment]
Whose experience is this gonna make better? Whose immersion is this gonna un-break?

**Comment by Jared-Fogle** [comment]
>  another: janitor barriers, can't run through it and it stays forever

Who cares? Why is this an issue?

>  another: medical barriers, can't go through if you are infected, easy spot of fake viruses and easy medbay containment

Yes? Why does this need a nerf? Nobody uses these anyway.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
I don't think "magical power sources" is an issue because we are playing a video game, and adding real power sources doesn't make the game more fun. If you want to nerf atmos projectors (which our conversation in Discord seemed to suggest), I'd rather you do that than an all encompassing change for a nonissue.

Someone suggested making it so that if the projector item itself moves too far away from the fans, they go away. That sounds interesting to me, but I'll leave that to you.

**Comment by Ghilker** [comment]
I'll remove the cell need and make the holosigns shut off if the projector moves too far. Should I'd do it only for atmos? Or this would be good for every type?

**Comment by Jared-Fogle** [comment]
Works for me :+1:

**Comment by MrDoomBringer** [comment]
> holosign creators can't be used in rechargers

why not? The correct solution here is to make holosign creates usable in rechargers, not to create your own snowflake recharger that only works with the holosign projector.

Just having the atmos one use a cell is a good change, though.

**Comment by LemonInTheDark** [comment]
Can you elaborate more on what the goal here is?

**Comment by Ghilker** [comment]
nevermind on this, the idea was to nerf the holobarriers, but i think this is not the right way to do it

**Pull request closed without merging**
