### PR TITLE
Autoevac time no longer always 25 minutes; war ops autocall

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: The automatic evacuation triggered by the destruction of all communication consoles and AIs is now ten minutes (reduced from twenty five minutes) plus any round start shuttle delay (so you can't get around the shuttle's refueling time).
add: A declaration of war by Nuclear Operatives will automatically call the shuttle (delay to refuel time included), providing both sides with a timer. The operatives will (with normal config options) be able to arrive on the station at the ETA 15:00 mark. The shuttle is not recallable when a declaration of war has been made.
/:cl:
### Balance implications
- Station crew on war ops can no longer get a red alert shuttle, in exchange for reliably having a timer for victory and the window when the ops will be arriving. (Regular war ops timings will be evacuation shuttle docks at 35 minutes after roundstart, op window opens at 20 minutes after roundstart.)

### CODE REVIEW

**Comment by kevinz000** [comment]
its funnier when you're one of the only survivors in a singularity torn station, and the shuttle is 17 minutes away, and someone screams that  the singularity is approaching where everyone is hiding, and everyone panics hard.

**Comment by Iamgoofball** [comment]
@kevinz000 then the singulo hits and everyone's waiting ~~16~~20 (counting travel times) minutes for the round to restart even though everyone's already dead

**Comment by MrStonedOne** [comment]
this is a really bad change.

**Comment by coiax** [comment]
This was @KorPhaeron's idea

**Comment by MrStonedOne** [comment]
\>An assistant can now call the shuttle and prevent recall using a screw driver and a crowbar

\>Good change

Even with an ai, all it has to do is wait for the ai to disconnect, maybe even pda it and say "law 2: reconnect your systems (enter your file menu and hit reconnect)"

**Comment by coiax** [comment]
autoEvac isn't called by AI.Logout.
Could change the unrecallable state to after five minutes though.
And wouldn't an assistant breaking into the bridge and the captain's office to force a call fnr be 1) vaild 2) boinkable

**Comment by coiax** [comment]
Alternatively we CAAAAAAN get rid of the setting of the no recall for autoevac, and make only for war ops.

**Comment by MrStonedOne** [comment]
forcing a call is fine, but any mechanic the prevents recall for the cost of a few tools is bad.

hell it takes 2 people in sync to red alert.

>2) boinkable

They could be antag, and it would still be bad to allow them to force the round to end for no cost or effort, as then everybody would be doing it during low pop where there isn't an AI.

There is no mechanic right now that prevents recalls outside of narnar/others spawning. anything somebody can do to make recalling hard CAN be undone with enough effort or thought. from making a new coms console with the board in tech storage to r&d printing new boards emmass to killing the asshole so they can stop calling it.

adding such a mechanic is a balance nightmare, and it's guaranteed to have abuses that are still technically within the rules.

Furthermore, having the timer be set to 25 minutes is to prevent people from abusing autocall for easy shuttle calls in lowpop where there tends to be no AI, as a way to cuck past the ID requirements.

It also gives the station the time to decide not to go home.

**Comment by Incoming5643** [comment]
Miserable, shortens round length for no real reason

**Comment by coiax** [comment]
Based on feedback, I've removed the noRecall from autoevac, kept it for war ops

**Comment by coiax** [comment]
I have a better idea for dealing with all of this.

**Pull request closed without merging**
