### PR TITLE
Nerfs the recycler.

### PR DESCRIPTION
**Pull request by Iamgoofball**
It now can't produce diamond or plasma. Mining is still needed for diamond, plasma, and uranium.

It'll still make gold and silver and bananium.

Before you say "remove bananium too":

Bananium production has been in for about a month now. Everyone knows it makes bananium. I'm not removing it.

"muh honker"

I haven't seen people building honkers every other round. Maybe a clown will show up and sacrifice his gear for a honker once in awhile but people aren't just churning out honkers 24/7.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
remove bananium too

muh honker

:+1:

**Comment by GunHog** [comment]
Ah, well, it had to happen eventually. Please do keep the bananium though. HONK!

**Comment by PKPenguin321** [comment]
this only changes a very few select things, like now you can't get gygaxes as easily
with one good haul and an upgraded ore machine mining can still bring you over fifty diamonds, a few hundred plasma, and more than enough uranium
still though, it's a good change, :+1:

**Comment by ExcessiveUseOfCobblestone** [comment]
Could it be possible to instead of removing the ability to attain diamonds and plasma altogether, just giving them a small chance to be salvaged if the recycler is at T4? This forces RD and Mining to cooperate since T4 stock parts require diamonds and still gives RnD the benefit of having that extra sheet of diamond/plasma once they've reached max levels in most sections.

**Comment by Durkel** [comment]
The board to build this is called the recycler, but the machine itself is called a crusher. Can you change one of them to match?

**Comment by Razharas** [comment]
1 - what durkel said
2 - make it not the lowest possible research level
@Iamgoofball

**Comment by Iamgoofball** [comment]
can this be merged yet

**Comment by Jalleo** [comment]
Whoo mining has a reason to exist again!

**Pull request merged**
