### PR TITLE
Removes the ability to configure mutant humans at roundstart

### PR DESCRIPTION
**Pull request by optimumtact**
Removes ability to select as a cat without being put on purrbation

### CODE REVIEW

**Comment by Iamgoofball** [comment]
coderbus_closed

**Comment by YakumoChen** [comment]
NO

**Comment by Iamgoofball** [comment]
crying weeb detected

**Comment by kevinz000** [comment]
lol fuck off goofball

**Comment by kevinz000** [comment]
this is a config issue not a codebase issue.

**Comment by Iamgoofball** [comment]
# crying weeb detected

**Comment by Iamgoofball** [comment]
uh oh they deployed the config defense

whatever shall I do????

**Comment by Iamgoofball** [comment]
oh wait

# configs don't matter get fucked weeb trash

**Comment by kevinz000** [comment]
goofball:
iamgoofball

**Comment by Iamgoofball** [comment]
# w e e b

# t r a s h

**Comment by FantasticFwoosh** [comment]
Good. Thanks, the amount of catpeople/mutant self entitlement and self reference to neko's is insane.

Removing catpeople from the config would have been the best second option but don't look a gift horse in the mouth and all.

**Comment by improvedname** [comment]
I thought goof couldnt do more then threaten about copyrights and posting goatse's when somoene get banned by his pr

**Comment by Iamgoofball** [comment]
>says the guy with a furry avatar

**Comment by improvedname** [comment]
Sorry i couldnt hear you over #coderbus

**Comment by RemieRichards** [comment]
Woops my finger slipped

**Comment by Iamgoofball** [comment]
@Cheridan

**Comment by Iamgoofball** [comment]
@RemieRichards weeb detected purge with prejudice

**Comment by FantasticFwoosh** [comment]
fight fight fight fight!

**Pull request closed without merging**
