### PR TITLE
Mining & mine-related chem changes

### PR DESCRIPTION
**Pull request by ghost**
**Important chem changes:**
- GOTTAGOFAST flag now removes !!ALL!! slowdown effects on someone instead of just speeding them up. This includes hardsuit slowdown, damage slowdown, hunger slowdown, freezing temperature slowdown, etc. Allows for people who are wounded to get a burst of speed without being 2sanic4u. 
- Stimulant virus affected by the above, also amount of chems given with stimulant virus toned back so you don't get fucking addicted to ephedrine.
- Stimulant virus will now simply remove any slowdown effects you have rather than making you 2fast2furious. Still, you can be hungry, freezing cold, near-death, and have 99 stamina damage, with a hardsuit on and you still won't move any slower than the default runspeed. It's still an immensely powerful virus.

**Mining changes:**
- Removed lanterns from mining lockers
- Extremely buffed the light that emits from the dual-floodlights on the miner's hardsuit helmet. No more holding lanterns in your pocket for light. Also buffed ERT helmets since they have dual floodlights as well.
- Removed diamond drill from emagged borgs. Made it a separate module.
- Rebalanced mining tools a lot into two classifications:

**Traditional mining tools** mine slowly but can mine as many turfs as they want. Pretty much what you've come to expect.
- Default pickaxe: 40 delay (standard issue)
- Plasma cutter: 30 delay (RnD, doubles as unlimited welding tool in some circumstances)
- Diamond pickaxe: 20 delay (purchased from mining equipment vendor.)

**Powered mining tools** require battery power (they take normal cells) but mine much faster than traditional mining tools. The higher tech the mining tool, the faster they mine, but the more power they consume. This is because the assumption is when you make faster power tools, you make higher capacity cells as well. These can be charged using normal rechargers, and I will add some to the mining outpost eventually so you don't have to replace cells and shit.
- Default drill: 30 delay (Voucher. 80 mineral walls worth of power. Almost a direct upgrade.)
- Diamond drill: 10 delay (RnD, ~60 walls worth of power. Great use of diamonds.)
- Sonic Jackhammer: 5 delay (RnD, 50 walls worth of power. Much more expensive and research intensive.)

**Other changes:**
- In addition to the above changes, I've removed the ability for diamond drills to break down walls. Sonic Jackhammers will now break down walls/rwalls/etc instead, at high power cost. It makes more sense for a jackhammer to double as demolition equipment, and it allows the jackhammer to fill the role of extremely robust mining endgame while allowing the diamond drill to function purely as a fast mining tool for upgraded cyborgs.
- Tweaked RnD prices for mining equipment to accommodate their new power. Diamond drill will require about 1 diamond, sonic jackhammer requires about 2 and some silver, and maxed research in some areas.
- Nerfed resonator to only crush walls once the resonator field ruptures so it doesn't act as a pseudo speed drill. What the fuck ergo.
- Buffed resonator fields in low pressure to do 50 damage, up from 45.
- Rebalanced a lot of equipment pricings in the mining equipment vendor, added diamond pickaxe.
- Buffed advanced scanner to ping much quicker.
- Removed leporazine medipen, replaced it with coffee in the stimpack medipen. The stimpack will now heat you up and make you move quickly on mining turfs (removing all slowdown penalties) so it can double as a "GET THE FUCK OUT" tool and a way to counter basilisks. Removed the negative chem from stimpacks.
- Changed a bunch of little descriptions and stuff as I saw them, feel free to comment on the line if you see one. I probably am forgetting something, sorry.

### CODE REVIEW

**Comment by pudl** [comment]
why not also make the powered tools able to be used on a charger, with chargers in each outpost? makes a long term goal to actually use the small outposts more often

**Comment by paprka** [comment]
i did that, but I didn't include map changes to add chargers to the outpost yet, this pr will probably be rotting for a long time

**Comment by WJohn** [comment]
:+1: x :100: 
Awesome work.

**Comment by TheVekter** [comment]
Does this do anything to the mining shotgun?

**Comment by Fox-McCloud** [comment]
Effectively this is returning hyperzine (and other stimulants) to their original status.

In any event, this inevitably means that Meth (and a few other chems) will need a separate flag---or maybe this flag should be renamed to something like "unencumberable" since you're really not boosting speed so much as preventing a slowdown.

**Comment by Iamgoofball** [comment]
i give the chem changes a :+1:

proceed forward

**Comment by paprka** [comment]
ok sorry for the air horn sticking around in this pr even though i removed it from the mining vendor but i forgot about it and it is harmless and goofball improved it.

**Comment by Miauw62** [comment]
Could you please make it so that the stimulant chems have a "gofast" var that is set and then loop through the chems list ONCE and check for said var instead of having to loop through it four times to compare 4 different strings? IIRC it actually has quite a bit of impact on performance.

**Comment by RandomMarine** [comment]
>diamond drill to function purely as a fast mining tool for upgraded cyborgs.
Part of the reason why d-drill was an emag item was to allow a rogue minerborg to demolish walls throughout the station.

>Nerfed resonator to only crush walls once the resonator field ruptures so it doesn't act as a pseudo speed drill. What the fuck ergo.
This was intentional. Resonator miners need that ability to dodge goliath tentacles in cramped areas. Please do not do that.

**Comment by paprka** [comment]
@Miauw62 No I don't know how to do that, you can PR it to my branch if you want it.

@RandomMarine Yes but nobody played mining borg for the emag items. Borgs can get through basically any airlock in the station, and the engie borg can do that while also having things like welding tools for healing friendly borgs and disassembling things. This allows mining borgs to have a better endgame and mine even more sanic than they regularly do.
 
Resonators are an extremely fast mining tool without that second nerf to resonators. If I revert it, they won't be a voucher item and will go completely unused like they are currently. The idea is for the KA/resonator to be combat tools versus wildlife, or slower mining tools, not the best of both worlds.

**Comment by RandomMarine** [comment]
Between the changes here and the buffs to the KA in #7539 and #7720. We're never going to see a resonator used, ever.

Did you know that they used to do 60 damage on rupture, even?

**Comment by TheVekter** [comment]
How much do they do now?

**Comment by RandomMarine** [comment]
This pull changes them from 45 to 50.

**Comment by paprka** [comment]
The resonator is a shit item because it relies on timing. I'd rather just remove it honestly but people would get even more butthurt. It's not balanced for mining, it's not balanced for combat, it's garbage. It should rupture fields when monsters ENTER them, not based on timing stupidity that's really clunky in caves.

But I'm not making those changes, too lazy, ergo fucked off again so I have no obligation to make his shitty items better.

**Comment by TheVekter** [comment]
Fine, fuck it, I'll take a whack at it. Don't make a change to an item if
you think it sucks AND you don't intend on fixing why it sucks.

**Comment by paprka** [comment]
But I did fix why it sucked. It mined faster than a diamond drill and was available from roundstart.

**Comment by TheVekter** [comment]
No, you just said it was a shit item because it relies on timing. You even
had an idea to fix it but refused to because it's not your code/you're lazy.

**Comment by TheVekter** [comment]
I mean yeah, fair nuff you fixed it being overpowered for mining but now no
one's going to use it. It doesn't really fix the problem.

**Comment by paprka** [comment]
OH NO NOBODY IS GOING TO USE A SHITTY ITEM, THIS IS CLEARLY MY RESPONSIBILITY TO FIX IT

except it's not, that's not how coding works, fuck off vekter.

**Comment by RandomMarine** [comment]
Overpowered? Resonator digs instantly, yes, but with a cooldown of two seconds before it can be used again.

Other tools can dig any number of turfs you can reach at the same time, with dig times ranging from 4 seconds at the most basic, to .5 seconds with the strongest tool.

The response to an item being shit isn't to nerf the **one, single good thing** it has going for it.

**Comment by paprka** [comment]
2 second delay is as much as the diamond pickaxe.

**Comment by RandomMarine** [comment]
>2 second delay is as much as the diamond pickaxe.

But it can't dig more than one turf at once, unlike normal tools.

If you're so adamant about nerfing it, just raise the cooldown a bit. It needs the insta-dig for goliath fighting, y'know, the one thing is was designed for in the first place.

**Comment by Cheridan** [comment]
Making drills unable to dig sand seems like a pointless reduction in usability.

**Comment by paprka** [comment]
I'm removing shovels if they can dig sand, there is virtually no reason for both of them to exist.

**Comment by paprka** [comment]
- Pickaxes, drills, etc can all dig now, but the shovel is a better dig tool until you get the diamond pickaxe/diamond drill/jackhammer. This allows it to not be a complete waste of space.
- Resonators can now be tweaked with a screwdriver so their fields detonate at either 5 or 3 seconds.
- Resonators now can have up to 3 simultaneous fields at once.
- Resonators can be upgraded with diamond sheets to have their field limit buffed (up to 8 fields)
- Resonators readded to vouchers
- Resonators are the most expensive mining weapon available from vouchers, but they are still a sidegrade from kinetic accelerators which beat them in terms of range, but not overall damage.
- Goliath tentacles now STUN you instead of weakening you/knocking you over, to simulate the tentacle grabbing you in place.
- Goliath tentacles can do up to 15 damage when they stun you now as well
- Walking onto a tentacle will no longer trigger the tentacle stun, so you don't have to dig into a wall to escape from goliath tentacles. Holy shit this was bad gameplay.

Resonator fields still need to detonate to crush rocks, but they can be tweaked to be as fast as a mining drill. The only real downside is that you don't have to clickspam with drills, and they can dig dirt where the resonator cannot.

I buffed the resonator so it does 15 damage when hitting things but I reverted that as well and nerfed it, 8 damage is fine since most of the damage lies in the fields and it shouldn't be a pseudo pickaxe. It also fits in backpacks, so.

**Comment by TheVekter** [comment]
Bam. Paprika kicks ass when he's not being lazy. Looks great.

Is there any way at some point to make it where mining borgs can use
Goliath plates? Not in this PR but in general.

**Comment by paprka** [comment]
Pff, that would be cute. Yeah, it wouldn't exactly be a hard thing to implement, just have it apply the plates as a borg module like the vtec/taser cooler/diamond drill upgrades do, and have it reduce damage or whatever, and make it apply overlays.

**Comment by TheVekter** [comment]
I'll look into getting that done.

**Comment by paprka** [comment]
- Changed borg diamond drill so it requires just as much diamond as a normal diamond drill since it no longer goes through walls.
- Adding a diamond drill will remove the shovel module as well since it digs faster than the shovel anyway.

**Comment by paprka** [comment]
The only thing I'm afraid of here is goliaths being a bit of a pushover, but that 'walk on a tentacle and it stuns you' dance-dance revolution bullshit was absolute garbage and never fun. Mining is intrinsically about mining, and the rewards you get from killing monsters isn't that big of a deal. They're still a threat and all that but they aren't so annoying that every encounter with a goliath could be the end of your round, that's just not fun.

**Comment by TheVekter** [comment]
Goliaths are stupid easy to kill if you kite them to an open area and use
the kinetic.

**Comment by palpatine213** [comment]
Emagged mining borg drill going through Rwalls is a fairly robust ability, considering that you can do it pretty silently.
The idea of no one going a borg type for some sort of emag modules is a really silly notion. Unless the AI is malf or a traitor, you don't know if you are going to be emagged or not. I mean the only borg usually chosen for the emagged modules is secborg.

**Comment by paprka** [comment]
Can someone please review this?

**Comment by ACCount12** [comment]
How about porting my plasma cutters update from NT? I'm too lasy to do it.

**Pull request merged**
