### PR TITLE
adds toast sandwich

### PR DESCRIPTION
**Pull request by epochayur**
## About The Pull Request

Adds toast sandwich to the game.

image

## Why It's Good For The Game

Gives our UK players a little taste of home :)
Also it's funny

## Changelog

:cl: Epoc
add: Toast sandwich
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Finally, some good fucking food

**Comment by DATA-xPUNGED** [comment]
This should instantly kill lizards (can't eat grain)

**Comment by Twaticus** [comment]
you added a white pixel to butteredtoast

**Comment by ChungusGamer666** [comment]
> you added a white pixel to butteredtoast

yes, and?

**Comment by epochayur** [comment]
whoops shit, lemme fix that

**Pull request merged**
