### PR TITLE
For your consideration: OOC heart commendations changed to random plushie emojis

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

OOC commendations are now plushie emojis, they change with reboots and relogs.

also, made all the procs generically and uniformly refer to themselves as commendations. it was a bit inconsistent and didn't make sense when I changed it to plushies

touched up a bit of documentation that was missing and gave it the chad doc format

## Why It's Good For The Game

I really think the heart emoji is lame and i LOVE 😍 plushies :)

## Changelog
:cl:
add: Heart commendations are now PLUSHIES!
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Tfw you get commended and the blood god shows up next to your name for a day

**Comment by tralezab** [comment]
The narsie emoji is horribly blurry so I left it out (I'M SORRY!!!!)

**Comment by Jared-Fogle** [comment]
:(

**Review by Mothblocks — CHANGES_REQUESTED** [review]
gonna be honest...i odnt like the plushies

please just keep this to your code cleanup changes

**Comment by tralezab** [comment]
I don't wanna bother splitting apart this stuff, F the code improvements 😤

**Pull request closed without merging**
