### PR TITLE
Adds in asexual-themed socks.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

Adds in the asexual socks, called the ace socks because i like the abbreviation as it makes it sound cooler.
Also fixes bee socks being ordered improperly in the code.

## Why It's Good For The Game

The socks look cool, also can be used to show that you follow rule 8.

## Changelog
:cl:
add: Added in a new sock type, Thigh-high and Knee-high ace socks.
fix: Bee socks are now properly ordered in the code.
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
asoxual

**Comment by wesoda25** [comment]
_feature freeze ends_
Coders:

**Comment by Farquaar** [comment]
Y tho?

**Comment by CRITAWAKETS** [comment]
> The socks look cool, also can be used to show that you follow rule 8.
cmon man its right there in the pr

**Comment by Valorium-RB** [comment]
Good and based.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
