### PR TITLE
adds skill to grabs

### PR DESCRIPTION
**Pull request by UncleBourbon**
kevinz got salty he got tabled and removed skill so he can powergame with RTA. so im adding it back lol

### CODE REVIEW

**Comment by kevinz000** [comment]
image

**Comment by UncleBourbon** [comment]
image

**Comment by Hatterhat** [comment]
image

**Comment by kevinz000** [comment]
image

**Comment by UncleBourbon** [comment]
image

**Comment by kevinz000** [comment]
image

**Comment by Hatterhat** [comment]
image

**Comment by Hatterhat** [comment]
in other news, best pr 2017, down with the tyrannical rule of @kevinz000

**Comment by UncleBourbon** [comment]
image

**Comment by kevinz000** [comment]
It's not your codebase. It's our codebase. You can imply soft power as much as you want, but you don't have it. Division between the server and project is absolute. I'm not interested in reading dezzmont platitudes for the billionth time and won't be checking back in this thread.

**Comment by Hatterhat** [comment]
image

**Pull request closed without merging**
