### PR TITLE
Fixes That /One/ Tramstation Bin. You know the one.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
So, today I found out *through circumstances that'll remain mysterious, cough cough* that one disposal bin in security - you know the one - is bait for antagonists to screw themselves over in. And doesn't actually. Connect to the disposals network.

This was clearly intended as there's pipes leading to it, but there's not a trunk under the goddamn bin.

This fixes that.

## Why It's Good For The Game
Fluked too bad (don't get too close)

## Changelog

:cl:
fix: The brig disposal bin on Tramstation is now actually hooked up. Because of course it wasn't.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
WRONG BRANCH

**Comment by unit0016** [comment]
Whookay, I blame my GIT UI and not myself being hazy as hell

reverted the irrelevant stuff and reopened on that

**Comment by timothymtorres** [comment]
It was noob bait.  You should have rerouted the bin to perma or the gas chamber.

**Comment by unit0016** [comment]
> It was noob bait. You should have rerouted the bin to perma or the gas chamber.

Funny as the latter'd be the chamber was never actually implemented on tram. Pour one out

**Pull request merged**
