### PR TITLE
AI APC hacking improvements

### LINKED ISSUE #19063: Malf AIs hacking APCs get stuck if the APC they are in the process of hacking is destroyed
...such as being eaten by a singularity. The APC will never register as being completely hacked, so the malf AI will not be ever able to hack a new one. 

Reported by a player, needs testing/reproducing, also imma put feature requests here:

(F) DEAD: Loves-The-Lizards says, "An ability to be able to stop hacking an APC would be nice though"
(F) DEAD: Loves-The-Lizards says, "and even better, knowing which APC i'm actually hacking, I lose track"

### PR DESCRIPTION
**Pull request by coiax**
image

:cl: coiax
add: AIs get a notification when hacking an APC, which can be clicked to jump your camera to the APC's location. AIs also get notification sounds when a hack has completed or failed.
/:cl:

Fixes  #19063

### CODE REVIEW

**Comment by GunHog** [comment]
Awesome sauce

**Comment by coiax** [comment]
The icon is just the blue APC icon on top of the base AI alert icon, so if @WJohn wants to add a better icon to their never ending stack of todo items, that'd be fine with me.

**Comment by GunHog** [comment]
I am out of Xeno tokens, so I cannot ask him to do it until I code mode.

**Comment by Zilenan91** [comment]
The icon looks fine to me. Tells you what it is without you having to think about it.

**Comment by Anonmare** [comment]
Looks fine to me. It's simple and gets the point across which is what alerts should be.

**Pull request merged**
