### PR TITLE
Better Ghost Event Selection

### PR DESCRIPTION
**Pull request by 13spacemen**
my poor attempt at PORT OF https://github.com/ParadiseSS13/Paradise/pull/13710. with my own improvements and some bugfixes

Replaces the annoying tgui alert popup "Do you want to be X? | Yes | No | Never for this round" that is hard to read and steals window focus, with a nice clean alert in the top right that counts down. If it's the same event/mob they stack with 2x, 3x, etc. It also shows how many candidates/ghosts are signed up.

## Full Description

- adds a new subsystem SSpolling
- poll_candidates type procs all use the new subsystem
- polls make an alert button with the icon and name of the role
- alert button has a countdown, stack number, number of candidates signed up
- alt-click alert button to set 'never for this round' (if possible)
- ctrl-click alert button to jump to the mob in the alert (if possible)
- polls of the same type stack together, signing up to one signs up for them all
- also prints a big message in chat to candidates, clickable links in the chat too

## Other Code Changes

- added new helper to capitalize the first letter of every word in a string
- screentips can be shown to ghosts if atom has ghost_screentips = TRUE
- removed unused "priority candidates" system

PICS:
newghostalertpic

OUTDATED:
newghostalert

You click the alert to sign up for the role, you can click it again to un sign up. Alt-click to set "never for this round" or unset it.

# To-do

- [x] Make sure it's complete
- [x] Possibly rename SSghost_spawns to SSpolling or something, and have it also handle living candidates
- [x] add the alert icons for every role
- [x] proper role names
- [x] add ability to alt-click to set "never for this round"
- [x] Misc improvements I can think of/suggested

## Weird Bugs (NO LONGER HAPPENS POST-EVENT MENU REWRITE)
~~If an admin forces events too fast (thereby cancelling events) and causing a call stack runtime "!random_event overridden", SSghost_spawns will no longer work and won't create any more polls or event buttons.
This doesn't happen with random events, since they don't cancel on their own, but if you force events too fast like clicking "Blob" twice very quickly, this happens. Not sure how to fix it or why it even happens. This bug happens on Paradise too, if you force events too fast as an admin. SSghost_spawns stops working and doesn't make alerts anymore.~~

:cl:
qol: When an event triggers for ghosts, they will get a nice clickable box alert in the top right instead of a hard-to-read TGUI alert. Click the box to sign up for ghost role, alt-click to set "never for this round".
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
needs better commit descs

**Comment by 13spacemen** [comment]
@LemonInTheDark will fix that soon

**Comment by LemonInTheDark** [comment]
stg gonna toss you into the sea

**Comment by 13spacemen** [comment]
@LemonInTheDark going to force push a proper commit when i get the time to write up something, i couldn't get this PR to work properly for a while so i almost abandoned it which is why everything is "wip"

**Comment by MrDoomBringer** [comment]
commit_v5_final_FINAL

While you're at it, do you think you could add a small number that shows how many ghosts have currently signed up for the role? It can be super helpful to know at times. If there's multiple of the same event stacked, you can just sum up total signees.

**Comment by 13spacemen** [comment]
@MrDoomBringer coming right up 🧑‍🍳

**Comment by optimumtact** [comment]
What the fuck is this mystery meat navigation?

Add the name of the ghost event to it, why is everything a poorly designed icon

the fact you think that is somehow easier to read than a tgui alert when it doesn't HAVE ANY TEXT ON IT MAKES ME WONDER IF YOU THOUGHT THIS PR THROUGH AT ALL

**Comment by 13spacemen** [comment]
@optimumtact the name shows when you hover over it
also, the icon shows what role it is, if it's blob it shows a blob, if it's regal rat it shows that, etc.

**Comment by LemonInTheDark** [comment]
I do not understand how this is better, or rather how it is more clear. It seems like one of those user interfaces that says more info at a glance to experienced users, but is just gibberish to everyone else. Don't like that

Basically I agree with oranges I guess

**Comment by 13spacemen** [comment]
with the new alert system:
* prints to deadchat AND shows an alert
* shows icon of the ghost role
* shows countdown in obvious numbers
* same type alerts stack, if there are 2 blob rolls, you can sign up for both with 1 click. with the tgui the tguis would overlap and you wouldn't even know there were 2 rolls
* shows how many ghosts signed up for it
* you can unsign up
* you can cancel 'never for this round'

This system is already in use on Paradise and SS220 Russian Paradise. SS220 gets even more players than TG and they don't even speak English. These servers are permanently on the hub and full of new players who have no problem with this system and prefer it to the old alert dialogs. It's much more user friendly than the current system

**Comment by VladinXXV** [comment]
I do not like status-effect-esque ghost role alerts. When multiple happen things tend to push each other around and it can result in clicking the wrong thing. It helps that these stack with those of the same type, but what I want to know is where do new ones show up? If they appear at the top of the list and push things down, that sucks. If they appear at the bottom of the list, without shuffling things, I think that would be much better.

**Comment by MrDoomBringer** [comment]
Honestly after giving this some thought, the proper solution is a dedicated ghost event menu UI. We can keep the alerts to show the type of midround antag, but clicking them should open this UI that lets you sign up, displays a description of the role, etc.

**Comment by 13spacemen** [comment]
@MrDoomBringer the alerts already show the description of the role on hover and prints it to dchat. hovering over the alert shows a screentip telling you how to sign up and alt-click
having a dedicated UI is pointless because the vast majority of the time there will only be 1 ghost role available anyway. the only way for the alerts to 'spam you' is if an admin starts spamming the force event button, and even then roles of the same type will stack. there's no benefit to having a separate UI everything can be shown with tooltips and screentips and overlays

**Comment by optimumtact** [comment]
These need to be changed to show the name of the ghost roles in text without having rollover, I'm not willing to budge on that point

**Comment by optimumtact** [comment]
These now have readable map text as per latest update from them in discord, on that basis I'm happy for the change to go ahead.

image

**Comment by 13spacemen** [comment]
taking a break for a while

**Pull request closed without merging**
