### PR TITLE
Fixes supermatter getting power from non-engineering staff.

### PR DESCRIPTION
**Pull request by Iamgoofball**
alt title: stops bans for supermatter suicide

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
:ok_hand:

**Comment by PKPenguin321** [comment]
Sucks

**Comment by Iamgoofball** [comment]
@PKPenguin321 well this lets people supermatter suicide without getting banned annd follows the same rules of the singulo so

**Comment by PKPenguin321** [comment]
No it sucks

**Comment by Iamgoofball** [comment]
people were getting banned for releasing the engine cause they suicided into it tho from what i hear

**Comment by PKPenguin321** [comment]
Suuucks

**Comment by Iamgoofball** [comment]
would you rather people get banned

**Comment by PKPenguin321** [comment]
They get banned because it releases rads when it melts something not because it gets power

This doesn't fix that and also removes delaminating the supermatter by dragging it through the halls and robusting everybody

**Comment by ExcessiveUseOfCobblestone** [comment]
I also ban for getting people killed when you're trying to suicide with electric grilles!

**Comment by Iamgoofball** [comment]
@ExcessiveUseOfCobblestone at this point it stays

**Comment by Cheridan** [comment]
a particularly elaborate suicide that requires engineering access?? just don't let them in.

**Comment by PKPenguin321** [comment]
Sucks!

**Comment by AnturK** [comment]
Stop opening these passive aggressive PR's and just open a policy thread for your salt.

**Comment by Iamgoofball** [comment]
I CAN'T OPEN POLICY THREADS

**Comment by Iamgoofball** [comment]
@cheridan this is supposedly becoming a legit problem

**Comment by Iamgoofball** [comment]
also singulo only gets power from engineers why does this get an exception

**Comment by Iamgoofball** [comment]
like the suicide is still in it just doesn't make the SM explode unless you're an engineer

**Comment by ShadowDeath6** [comment]
How much power did singlo get when somebody fell in though

**Comment by Iamgoofball** [comment]
200

**Pull request closed without merging**
