### PR TITLE
Removes PDA chatrooms

### PR DESCRIPTION
**Pull request by tkdrg**
Nobody used them, and they were cluttering PDA Topic() needlessly.
Rest in peace, my child. You were too good for this world.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
;-;7

i've had some good moments with them, but out of 100s of rounds, i could probably count those moments on one hand

goodnight sweet prince

**Comment by Zilenan91** [comment]
In the near six months I've been playing I think I've seen literally one person ever who was using one of these.

**Comment by MMMiracles** [comment]
Maybe the issue is nobody really knows about it? I forgot it even existed honestly.

**Comment by Zilenan91** [comment]
The issue is that it's pointless, not that nobody knows about it.

**Comment by MMMiracles** [comment]
Its the only PDA-based communication that can get past the telecomms snooping an AI/CE can do with their password. I've seen a cult and rev do it before for sneaky group-chat (the rev one hilariously enough got caught because their room name was 'rev').

I think its more of an issue that literally nobody knows about it rather than it being pointless.

**Comment by tkdrg** [comment]
The AI/CE can snoop chatrooms too, the same way they can snoop PDAs, but nobody ever does it. It's just multi-user PDA messaging, except clunkier.

**Comment by Shadowlight213** [comment]
Improve not remove!
If you could opt in to be notified of ALL Ntrc messages, and have this be enabled by default, that would drastically make it used more.

**Comment by bustygoku** [comment]
Improve this dick in your mother you memespouting shit

**Comment by Shadowlight213** [comment]
Wow. Rude. I was actually being serious. I've used this as a head of staff during a revolution with a compromised AI.
As I said, if there was a notification for Any message sent it would be used more.

**Comment by freerealestate** [comment]
really good idea, shame they received no use

**Comment by Steelpoint** [comment]
Honestly I think this feature is nice but its not well known, thus its unused.

I would like to keep it, but if its making a mess of the code in a bad way then eh.

**Comment by tkdrg** [comment]
They're not _good_, but they're not as bad as the _rest_ of PDA code. They're also about 10% of PDA code. In retrospect, I think they just offer little to no advantage over PDA messaging. They have the same function, they can be overheard the same way, they can be sabotaged through the same machine. It's just redundant.

**Comment by CPTANT** [comment]
improve not remove is an awful meme to leads to nothing but cluttering the game with redundant trash. 

get rid of redundant shit.

**Comment by ike709** [comment]
Meh, I kinda forgot it existed.

**Comment by bgobandit** [comment]
improve don't remove

I use this shit all the time

**Comment by freerealestate** [comment]
who do you erp wi i mean talk to

**Comment by Shadowlight213** [comment]
I just tested the ping, and all it does is make their PDA beep. No indication of what it it like the PDA messages.
No wonder it was never used.

**Comment by Aranclanos** [comment]
the children should be the one burying the father

**Comment by Bawhoppen** [comment]
i think ayyran has a grudge against it

**Pull request merged**
