### PR TITLE
Implements small labels to abductor glands to see what they do.

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

Abductors and observers will now be able to see what organ's do upon shift-clicking them. Also uhhhhhhhhhhh, it's 2022 in Australia so this isn't breaking the freeze. Checkmate Americans. 

## Why It's Good For The Game

Uhhh, who the fuck thought having to check the wiki for every organ was a good idea? This allows for a better experience for abductor scientists and curious ghosts wanting to see what happens next.

## Changelog

:cl:
qol: Adds description to abductor glands upon shiftclick. 
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
This is already a thing with the gland's true name, only problem is that it requires the wiki. Could just place it there instead.

**Comment by Mothblocks** [comment]
> Also uhhhhhhhhhhh, it's 2022 in Australia so this isn't breaking the freeze. Checkmate Americans.

The freeze ends when the PR is closed

**Comment by Mothblocks** [comment]
My PR I mean

**Comment by carshalash** [comment]
> My PR I mean

Too late, you closed the PR, now the freeze is over for everyone mothblocks.

**Pull request closed without merging**
