### PR TITLE
Red Wizard Hat enabled on Corgis

### PR DESCRIPTION
**Pull request by coiax**
:cl: Mercenaryblue
rscadd: Allowed all corgis to wear red wizard hats.
/:cl:

I stole the commit from #17048.

### CODE REVIEW

**Comment by KazeEspada** [comment]
Black Wizard hat that turns Ian into a skeleton and makes him rattle and scream "RISE!"

**Comment by Mercenaryblue** [comment]
I'm alright with this. You're a hero.

**Comment by coiax** [comment]
@Mercenaryblue If you're gonna do that, make a branch from upstream's master this time.

**Comment by Mercenaryblue** [comment]
Yeah coiax, I learned my lesson.

**Pull request merged**
