### PR TITLE
Corrects some stacked turf

### LINKED ISSUE #34575: box circuit lab is  borked
#34526

http://take.ms/yTzXx

### PR DESCRIPTION
**Pull request by ShizCalev**
Gets some missed in #34562 
Fixes #34575

### CODE REVIEW

**Comment by SpaceManiac** [comment]
<details>
<summary>Stacked turfs report based on HEAD of this commit</summary>
<pre>
_maps/RandomRuins/LavaRuins/lavaland_surface_cultaltar.dmm
    at (8, 10, 1): found 2 turfs
    at (6, 8, 1): found 2 turfs
    at (10, 8, 1): found 2 turfs
    at (8, 6, 1): found 2 turfs
    stacked turfs: 2
_maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
    at (12, 3, 1): found 2 turfs
    at (12, 1, 1): found 2 turfs
    stacked turfs: 1
_maps/RandomRuins/SpaceRuins/caravanambush.dmm
    at (50, 24, 1): found 2 turfs
    stacked turfs: 1
_maps/RandomRuins/SpaceRuins/crashedship.dmm
    at (53, 16, 1): found 2 turfs
    stacked turfs: 1
_maps/RandomRuins/SpaceRuins/derelict6.dmm
    at (15, 21, 1): found 2 turfs
    at (16, 21, 1): found 2 turfs
    at (8, 20, 1): found 2 turfs
    at (9, 20, 1): found 2 turfs
    at (10, 20, 1): found 2 turfs
    at (11, 20, 1): found 2 turfs
    at (17, 20, 1): found 2 turfs
    at (18, 20, 1): found 2 turfs
    at (6, 19, 1): found 2 turfs
    at (19, 19, 1): found 2 turfs
    at (20, 19, 1): found 2 turfs
    at (21, 19, 1): found 2 turfs
    at (4, 18, 1): found 2 turfs
    at (5, 18, 1): found 2 turfs
    at (6, 18, 1): found 2 turfs
    at (22, 18, 1): found 2 turfs
    at (20, 11, 1): found 2 turfs
    at (21, 11, 1): found 2 turfs
    at (16, 10, 1): found 2 turfs
    at (19, 10, 1): found 2 turfs
    at (20, 10, 1): found 2 turfs
    at (19, 9, 1): found 2 turfs
    at (18, 8, 1): found 2 turfs
    at (15, 7, 1): found 2 turfs
    stacked turfs: 6
_maps/RandomZLevels/caves.dmm
    at (212, 232, 1): found 2 turfs
    at (213, 232, 1): found 2 turfs
    at (214, 232, 1): found 2 turfs
    at (215, 232, 1): found 2 turfs
    at (216, 232, 1): found 2 turfs
    at (217, 232, 1): found 2 turfs
    at (221, 232, 1): found 2 turfs
    at (222, 232, 1): found 2 turfs
    at (223, 232, 1): found 2 turfs
    at (224, 232, 1): found 2 turfs
    at (225, 232, 1): found 2 turfs
    at (226, 232, 1): found 2 turfs
    at (212, 231, 1): found 2 turfs
    at (221, 231, 1): found 2 turfs
    at (226, 231, 1): found 2 turfs
    at (212, 230, 1): found 2 turfs
    at (217, 230, 1): found 2 turfs
    at (221, 230, 1): found 2 turfs
    at (226, 230, 1): found 2 turfs
    at (212, 229, 1): found 2 turfs
    at (217, 229, 1): found 2 turfs
    at (221, 229, 1): found 2 turfs
    at (226, 229, 1): found 2 turfs
    at (212, 228, 1): found 2 turfs
    at (213, 228, 1): found 2 turfs
    at (214, 228, 1): found 2 turfs
    at (216, 228, 1): found 2 turfs
    at (217, 228, 1): found 2 turfs
    at (221, 228, 1): found 2 turfs
    at (222, 228, 1): found 2 turfs
    at (224, 228, 1): found 2 turfs
    at (225, 228, 1): found 2 turfs
    at (226, 228, 1): found 2 turfs
    at (217, 221, 1): found 2 turfs
    at (218, 221, 1): found 2 turfs
    at (219, 221, 1): found 2 turfs
    at (220, 221, 1): found 2 turfs
    at (221, 221, 1): found 2 turfs
    at (217, 220, 1): found 2 turfs
    at (221, 220, 1): found 2 turfs
    at (217, 219, 1): found 2 turfs
    at (221, 219, 1): found 2 turfs
    at (206, 218, 1): found 2 turfs
    at (213, 218, 1): found 2 turfs
    at (214, 218, 1): found 2 turfs
    at (215, 218, 1): found 2 turfs
    at (216, 218, 1): found 2 turfs
    at (217, 218, 1): found 2 turfs
    at (218, 218, 1): found 2 turfs
    at (220, 218, 1): found 2 turfs
    at (221, 218, 1): found 2 turfs
    at (222, 218, 1): found 2 turfs
    at (223, 218, 1): found 2 turfs
    at (224, 218, 1): found 2 turfs
    at (225, 218, 1): found 2 turfs
    at (228, 218, 1): found 2 turfs
    at (232, 218, 1): found 2 turfs
    at (206, 217, 1): found 2 turfs
    at (232, 217, 1): found 2 turfs
    at (206, 216, 1): found 2 turfs
    at (217, 216, 1): found 2 turfs
    at (221, 216, 1): found 2 turfs
    at (206, 215, 1): found 2 turfs
    at (206, 214, 1): found 2 turfs
    at (210, 214, 1): found 2 turfs
    at (213, 214, 1): found 2 turfs
    at (214, 214, 1): found 2 turfs
    at (215, 214, 1): found 2 turfs
    at (216, 214, 1): found 2 turfs
    at (217, 214, 1): found 2 turfs
    at (221, 214, 1): found 2 turfs
    at (222, 214, 1): found 2 turfs
    at (223, 214, 1): found 2 turfs
    at (224, 214, 1): found 2 turfs
    at (225, 214, 1): found 2 turfs
    at (228, 214, 1): found 2 turfs
    at (206, 213, 1): found 2 turfs
    at (210, 213, 1): found 2 turfs
    at (217, 213, 1): found 2 turfs
    at (221, 213, 1): found 2 turfs
    at (228, 213, 1): found 2 turfs
    at (206, 212, 1): found 2 turfs
    at (210, 212, 1): found 2 turfs
    at (212, 212, 1): found 2 turfs
    at (213, 212, 1): found 2 turfs
    at (214, 212, 1): found 2 turfs
    at (215, 212, 1): found 2 turfs
    at (216, 212, 1): found 2 turfs
    at (217, 212, 1): found 2 turfs
    at (221, 212, 1): found 2 turfs
    at (222, 212, 1): found 2 turfs
    at (223, 212, 1): found 2 turfs
    at (224, 212, 1): found 2 turfs
    at (225, 212, 1): found 2 turfs
    at (226, 212, 1): found 2 turfs
    at (228, 212, 1): found 2 turfs
    at (232, 212, 1): found 2 turfs
    at (206, 211, 1): found 2 turfs
    at (210, 211, 1): found 2 turfs
    at (228, 211, 1): found 2 turfs
    at (232, 211, 1): found 2 turfs
    at (206, 210, 1): found 2 turfs
    at (210, 210, 1): found 2 turfs
    at (228, 210, 1): found 2 turfs
    at (232, 210, 1): found 2 turfs
    at (206, 209, 1): found 2 turfs
    at (210, 209, 1): found 2 turfs
    at (228, 209, 1): found 2 turfs
    at (232, 209, 1): found 2 turfs
    at (206, 208, 1): found 2 turfs
    at (210, 208, 1): found 2 turfs
    at (212, 208, 1): found 2 turfs
    at (213, 208, 1): found 2 turfs
    at (215, 208, 1): found 2 turfs
    at (216, 208, 1): found 2 turfs
    at (217, 208, 1): found 2 turfs
    at (221, 208, 1): found 2 turfs
    at (222, 208, 1): found 2 turfs
    at (223, 208, 1): found 2 turfs
    at (224, 208, 1): found 2 turfs
    at (225, 208, 1): found 2 turfs
    at (226, 208, 1): found 2 turfs
    at (228, 208, 1): found 2 turfs
    at (232, 208, 1): found 2 turfs
    at (217, 207, 1): found 2 turfs
    at (221, 207, 1): found 2 turfs
    at (232, 207, 1): found 2 turfs
    at (217, 206, 1): found 2 turfs
    at (221, 206, 1): found 2 turfs
    at (232, 206, 1): found 2 turfs
    at (206, 205, 1): found 2 turfs
    at (210, 205, 1): found 2 turfs
    at (211, 205, 1): found 2 turfs
    at (212, 205, 1): found 2 turfs
    at (213, 205, 1): found 2 turfs
    at (214, 205, 1): found 2 turfs
    at (215, 205, 1): found 2 turfs
    at (216, 205, 1): found 2 turfs
    at (217, 205, 1): found 2 turfs
    at (221, 205, 1): found 2 turfs
    at (222, 205, 1): found 2 turfs
    at (223, 205, 1): found 2 turfs
    at (224, 205, 1): found 2 turfs
    at (225, 205, 1): found 2 turfs
    at (226, 205, 1): found 2 turfs
    at (227, 205, 1): found 2 turfs
    at (228, 205, 1): found 2 turfs
    at (232, 205, 1): found 2 turfs
    at (232, 204, 1): found 2 turfs
    at (232, 203, 1): found 2 turfs
    at (206, 202, 1): found 2 turfs
    at (232, 202, 1): found 2 turfs
    at (206, 201, 1): found 2 turfs
    at (207, 201, 1): found 2 turfs
    at (208, 201, 1): found 2 turfs
    at (209, 201, 1): found 2 turfs
    at (210, 201, 1): found 2 turfs
    at (211, 201, 1): found 2 turfs
    at (212, 201, 1): found 2 turfs
    at (213, 201, 1): found 2 turfs
    at (214, 201, 1): found 2 turfs
    at (215, 201, 1): found 2 turfs
    at (216, 201, 1): found 2 turfs
    at (217, 201, 1): found 2 turfs
    at (221, 201, 1): found 2 turfs
    at (222, 201, 1): found 2 turfs
    at (223, 201, 1): found 2 turfs
    at (224, 201, 1): found 2 turfs
    at (225, 201, 1): found 2 turfs
    at (226, 201, 1): found 2 turfs
    at (227, 201, 1): found 2 turfs
    at (228, 201, 1): found 2 turfs
    at (229, 201, 1): found 2 turfs
    at (230, 201, 1): found 2 turfs
    at (231, 201, 1): found 2 turfs
    at (232, 201, 1): found 2 turfs
    at (217, 200, 1): found 2 turfs
    at (221, 200, 1): found 2 turfs
    at (217, 199, 1): found 2 turfs
    at (206, 197, 1): found 2 turfs
    at (217, 196, 1): found 2 turfs
    at (221, 196, 1): found 2 turfs
    at (217, 195, 1): found 2 turfs
    at (221, 195, 1): found 2 turfs
    at (203, 194, 1): found 2 turfs
    at (215, 192, 1): found 2 turfs
    at (224, 191, 1): found 2 turfs
    at (228, 189, 1): found 2 turfs
    at (210, 187, 1): found 2 turfs
    at (211, 187, 1): found 2 turfs
    at (224, 187, 1): found 2 turfs
    at (230, 187, 1): found 2 turfs
    at (207, 186, 1): found 2 turfs
    at (212, 186, 1): found 2 turfs
    at (230, 186, 1): found 2 turfs
    at (205, 185, 1): found 2 turfs
    at (214, 184, 1): found 2 turfs
    at (217, 184, 1): found 2 turfs
    at (221, 184, 1): found 2 turfs
    at (214, 183, 1): found 2 turfs
    at (230, 183, 1): found 2 turfs
    at (214, 181, 1): found 2 turfs
    at (227, 181, 1): found 2 turfs
    at (226, 179, 1): found 2 turfs
    at (226, 178, 1): found 2 turfs
    at (221, 177, 1): found 2 turfs
    at (222, 177, 1): found 2 turfs
    at (224, 177, 1): found 2 turfs
    at (219, 176, 1): found 2 turfs
    at (220, 176, 1): found 2 turfs
    at (218, 175, 1): found 2 turfs
    at (216, 174, 1): found 2 turfs
    stacked turfs: 2
_maps/RandomZLevels/centcomAway.dmm
    at (34, 96, 1): found 2 turfs
    at (38, 96, 1): found 2 turfs
    at (46, 96, 1): found 2 turfs
    at (50, 96, 1): found 2 turfs
    at (34, 92, 1): found 2 turfs
    at (50, 92, 1): found 2 turfs
    at (35, 91, 1): found 2 turfs
    at (49, 91, 1): found 2 turfs
    at (47, 81, 1): found 2 turfs
    at (46, 80, 1): found 2 turfs
    at (39, 77, 1): found 2 turfs
    at (45, 77, 1): found 2 turfs
    stacked turfs: 2
_maps/RandomZLevels/moonoutpost19.dmm
    at (109, 108, 1): found 2 turfs
    at (111, 108, 1): found 2 turfs
    at (99, 107, 1): found 2 turfs
    at (98, 106, 1): found 2 turfs
    at (98, 102, 1): found 2 turfs
    at (99, 101, 1): found 2 turfs
    at (109, 100, 1): found 2 turfs
    at (111, 100, 1): found 2 turfs
    stacked turfs: 2
_maps/RandomZLevels/research.dmm
    at (145, 151, 1): found 2 turfs
    at (150, 151, 1): found 2 turfs
    at (146, 150, 1): found 2 turfs
    at (149, 150, 1): found 2 turfs
    stacked turfs: 4
_maps/RandomZLevels/spacebattle.dmm
    at (77, 145, 1): found 2 turfs
    at (82, 145, 1): found 2 turfs
    at (78, 144, 1): found 2 turfs
    at (81, 144, 1): found 2 turfs
    at (189, 138, 1): found 2 turfs
    at (194, 138, 1): found 2 turfs
    at (190, 137, 1): found 2 turfs
    at (193, 137, 1): found 2 turfs
    stacked turfs: 7
_maps/templates/medium_shuttle1.dmm
    at (6, 13, 1): found 2 turfs
    at (6, 3, 1): found 2 turfs
    stacked turfs: 2
_maps/templates/medium_shuttle2.dmm
    at (8, 12, 1): found 2 turfs
    at (6, 11, 1): found 2 turfs
    at (5, 9, 1): found 2 turfs
    at (5, 5, 1): found 2 turfs
    at (6, 3, 1): found 2 turfs
    at (8, 2, 1): found 2 turfs
    stacked turfs: 2
_maps/templates/medium_shuttle3.dmm
    at (5, 18, 1): found 2 turfs
    at (8, 18, 1): found 2 turfs
    at (10, 18, 1): found 2 turfs
    at (13, 18, 1): found 2 turfs
    at (15, 18, 1): found 2 turfs
    at (18, 18, 1): found 2 turfs
    at (5, 15, 1): found 2 turfs
    at (18, 15, 1): found 2 turfs
    at (5, 13, 1): found 2 turfs
    at (18, 13, 1): found 2 turfs
    at (5, 10, 1): found 2 turfs
    at (18, 10, 1): found 2 turfs
    at (5, 8, 1): found 2 turfs
    at (18, 8, 1): found 2 turfs
    at (5, 5, 1): found 2 turfs
    at (8, 5, 1): found 2 turfs
    at (10, 5, 1): found 2 turfs
    at (13, 5, 1): found 2 turfs
    at (15, 5, 1): found 2 turfs
    at (18, 5, 1): found 2 turfs
    stacked turfs: 4
</pre>
</details>

**Comment by ShizCalev** [comment]
fuck a duck

**Comment by SpaceManiac** [comment]
Some of them are the same tile over and over again so they could be corrected in the dictionary, it's a matter of which turf you want to keep

**Comment by ShizCalev** [comment]
Yeah I took a look at it, will have to wait till my current broken & burn PR is merged before I can fix it.

**Pull request merged**
