### PR TITLE
you can make the autolathe print on the tiles around it + doesnt print all at once (like chemmaster)

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
you can make the autolathe print on the tiles around it + doesnt print all at once (like chemmaster)

https://github.com/tgstation/tgstation/assets/70376633/a7e18c02-4442-432c-b612-466aaae57535

## Why It's Good For The Game

its convenient and cool

## Changelog
:cl:
add: clickdragging an autolathe changes its output direction
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Will it start spawning items in the walls if you clickdrag it to it?

**Comment by mc-oofert** [comment]
> Will it start spawning items in the walls if you clickdrag it to it?

yeah

**Comment by Serxule** [comment]
can the clickdrag be added to the exosuit fab too? it desperately needs it

**Comment by mc-oofert** [comment]
> can the clickdrag be added to the exosuit fab too? it desperately needs it

im pretty sure it vaguely already does so

**Comment by Serxule** [comment]
> > can the clickdrag be added to the exosuit fab too? it desperately needs it
> 
> im pretty sure it vaguely already does so

i've never found a way to be able to change the direction other than it being done in mapping

**Pull request merged**
