### PR TITLE
Adds the ability to flip disposal mail junctions with a screwdriver

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request
You can now screwdriver mail sorters to switch their output direction between the side exit and the straight exit.

## Why It's Good For The Game
image

## Changelog
:cl: MMMiracles
qol: Mail sorters can now be screwdrivered to swap their output directions for more varied disposal setups.
/:cl:
not a feature not a mechanic im fixing a limitation caused by current disposal code okay its an IMPROVEMENT

### CODE REVIEW

**Comment by san7890** [comment]
i'm okay with this but if any other maintainer wants you to remove the screwdriver aspect because it's player-facing, i would still want this PR in a code/map only form in order to address some fucked concerns we've been having with disposals on maps lately.

**Comment by LemonInTheDark** [comment]
This is a feature, why do you need it now?

**Comment by MMMiracles** [comment]
i posted the example reason, that kind of layout is currently impossible with current restrictions and i happened to run into it while actively mapping

the current alternative is placing every mail_sorting mapping helper apart from the ones you actually want sorted to get the same functionality on live

**Comment by tralezab** [comment]
i'd allow it but if someone tells you to remove the screwdriver interaction i wouldn't necessarily disagree

**Comment by MMMiracles** [comment]
good talk guys this thread was really enlightening for me

**Comment by LemonInTheDark** [comment]
Pr this later yeah?

**Pull request closed without merging**
