### PR TITLE
[READY]recycler buff

### PR DESCRIPTION
**Pull request by arsserpentarium**
:cl: selea
tweak: Now recycler can butcher mobs and saw tree logs.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
leave the security system unchanged please.

**Comment by arsserpentarium** [comment]
It can't gib human, as it used to be.It just will kill human without ID

**Comment by ExcessiveUseOfCobblestone** [comment]
It shouldn't be killing humans at all unless it's been tampered with.

**Comment by ExcessiveUseOfCobblestone** [comment]
These should be atomized anyways imo

**Comment by arsserpentarium** [comment]
atomized changes in one file?

**Comment by kevinz000** [comment]
it should not be killing humans without being emagged, id or not.
it destroys all your items, just no.

**Comment by Cyberboss** [comment]
The two changes should be atomic. Also, we're not removing the natural safety checks of the recycler

**Comment by arsserpentarium** [comment]
Now humans are safe until emag

**Pull request merged**
