### PR TITLE
fixes a locate and adds job checks to download objective

### LINKED ISSUE #38183: Robotics can get the Research Levels traitor objective, which is too easy
>walk in neighboring RnD department
>get ez text

or even better

>screwdriver your personal research console board
>instant research access

### PR DESCRIPTION
**Pull request by Amelia0010**
Fixes #38183

:cl: Nichlas0010
fix: You now can't get multiple download objectives!
tweak: RDs, Scientists and Roboticists can no longer get download objectives!
/:cl:

[why]: # @SpaceManiac

### CODE REVIEW

**Comment by Kromgar** [comment]
Download is like a free objective breaking a window is sll that it needs

**Comment by chesse20** [comment]
whats the point of down load objectives

**Comment by AnturK** [comment]
This really should be per objective type property

**Review by SpaceManiac — APPROVED** [review]
Would be great to see a general system for this, but this PR also fixes bad syntax so in it goes until that general system gets made.

**Pull request merged**
