### PR TITLE
Adds the CMO belt. Rework the CMO's roundstart gear.

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request

Introduces the CMO's belt, complete with experimental tools and lovely golden accents. Moves the advanced health analyzer from the locker to the belt.

image

Left is CMO, right is normal medical belt.

## Why It's Good For The Game

Adds more incentive to play a head role. Adds cool tools for the CMO to use, just like the CE. Adds a cool looking belt. Remove some of the free stuff from the CMO's locker.

## Changelog
:cl:
add: Added the CMO's medical belt, complete with advanced tools and lovely golden accents. Moved some of the CMO's gear around to compensate.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
I'm not a fan of people choosing to play a certain head of staff just for the gear, and not to be a leading command member. 

The CE suffers terribly because of this, most people that play CE, do it for the gear, rather than to be the leader of Engineering. They'll do their own things rather than delegate tasks to the workers of their department like a HoS or CMO would.

**Comment by KathyRyals** [comment]
If someone plays head of staff just for the gear and does not put in the minimum effort that we ask for, that's not a code issue.

**Comment by InsaneRed** [comment]
this is good also literally nobody listens to their head unless they are sec

**Comment by Mothblocks** [comment]
power creep

**Comment by InsaneRed** [comment]
i think the  toolbelt can repalce the compact defib untill you can print it from the lathe

**Comment by Krysonism** [comment]
CMO already has a belt, the compact defib.

**Comment by KathyRyals** [comment]
The CMO can have both, as a treat.

**Comment by ATH1909** [comment]
> The CMO can have both, as a treat.

except you removed their expanded capacity medkit, making going with the belt defib worse than it was before this PR

**Comment by Sealed101** [comment]
removing the medkit seems a bit too much for me, as it's widely used by competent mds and cmos for storing the entire medbay in a single normal slot in their bag. the belt doesn't provide much capacity outside the advanced tools drapes and a bonesetter. imo keep the medkit but with no tools in it. also i suggest making the sprite less like the same medbelt but with darker outline. make it red for example, as in regular medkit - advanced medkit.

**Comment by KathyRyals** [comment]
I have entertained the thought of keeping the medkit but without tools. I'll wait a bit to see if a maintainer interested in this PR requests it before changing anything though.

**Comment by Draggeru** [comment]
I would gladly trade the extra large med kit for round start advanced tools. Why the fuck would you carry around a lot of sutures and meshes when you can literally wound tend on people both standing up and even in a fireman carry? Just get a normal sized medkit.

**Comment by KathyRyals** [comment]
Medkit is back.

**Comment by maxymax13** [comment]
> 
> 
> this is good also literally nobody listens to their head unless they are sec

can confirm, give heads remote buttons to activate electroshock ankle bracelets when the qm refuses to listen to me for the 17th time

**Comment by Jhyrachy** [comment]
> > this is good also literally nobody listens to their head unless they are sec
> 
> can confirm, give heads remote buttons to activate electroshock ankle bracelets when the qm refuses to listen to me for the 17th time

Life as CE:
"You, random engineer, do solars!"
'No, fuck you'
>engi proceed to get insuls/belt and leave department for the shift

**Comment by GuillaumePrata** [comment]
> Life as CE:
"You, random engineer, do solars!"
'No, fuck you'
-engi proceed to get insuls/belt and leave department for the shift

Life as Atmos Tech
"The SM is in hellfire, everything is green and there is 4 grav anomalies there, CE we need your hardsuit to fix this mess"
-CE never responds, busy trying to kill abductors for the last 20 minutes after they kidnapped him from his Mech factory in maints

We already have a lot of CMOs that play just because of the AA at medbay and powergear like EMPed Defib or deathmix Hypo, adding incentives for those kind of players to play head roles will just push this issue of people not trusting Head players because they are often a random powergamer and not someone that is good at their department.

**Comment by KathyRyals** [comment]
Like I stated earlier, if a head of staff plays head of staff without putting in the minimum effort to be a head of staff, it's not a code issue.

**Review by Twaticus — APPROVED** [review]

**Comment by optimumtact** [comment]
> power creep

**Comment by optimumtact** [comment]
if the admin team wants heads to be respected they are going to have to back up the chain of command ooc.

**Comment by KathyRyals** [comment]
Absolutely. Not relevant to the PR anyway.

**Pull request closed without merging**
