### PR TITLE
Several further tweaks to AI camera balance.

### PR DESCRIPTION
**Pull request by theOperand**
- Camera alarms will now trigger when the first EMP runs out.
- Bullets can now damage cameras.
- Makes the force required to damage cameras >= 10 instead of > 10.
- Adds three camera-related tips.
- Camera alarms now trigger when the camera is disabled with brute force or bullets.
- Tracking will no longer spam the AI with "unable to track" messages when the target is outside of camera range.

comes with a changelog!

### CODE REVIEW

**Comment by Midaychi** [comment]
Send an alarm ping to the ai and to security consoles when cameras are destroyed with gun instead of disabled with tools, with general area and damage type.

That way it's not stealthy at all, but you can also use it to ambush people who respond.

**Comment by Miauw62** [comment]
updated.

**Comment by Kelenius** [comment]
Cue the greytiders breaking camera and AI remaining permanently blind because nobody gives a shit about cameras.

**Comment by GunHog** [comment]
Acceptable :+1:

**Comment by SconesC** [comment]
what a holocaust

**Comment by PKPenguin321** [comment]
>Cue the greytiders breaking cameras and AI remaining permanently blind because nobody gives a shit about cameras.

just as i had hoped :smiling_imp:

**Comment by freerealestate** [comment]
Kind of wish you didn't have to unscrew the panel to interact with cameras. It makes a fiddly job even fiddlier, and slows down repairs. No panel and a short (1.5s?) delay might be better.

**Comment by GunHog** [comment]
Miauw, why??

**Comment by phil235** [comment]
@Miauw62 Is this merge ready?

**Comment by Miauw62** [comment]
i actually havent tested this. ill do that now

**Comment by Miauw62** [comment]
@phil235 Should be good now.

**Comment by Miauw62** [comment]
its tested

**Pull request merged**
