### PR TITLE
Updates Greyscale Colors of PDAs and Gives QM a Survival Pen since I was in there anyway.

### PR DESCRIPTION
**Pull request by EricZilla**
## About The Pull Request

Hallo! This is part two of my PDA update, where I take the old hokey colors that were just left in to not rock the boat, and changes them to better fit the current aesthetic of the game. It also makes the captain's PDA have some more fanfare, without even adding a sprite, I just did a funny trick with the layers.

In addition to that, I have updated the sprite for the survival pen, and made it so QMs start with one in their PDA.

bespoke final
peen

## Why It's Good For The Game

The old PDA colors on the new PDA sprites were odd in a few places, this fixes that. I spent about a week or so going to different players of the different jobs and departments getting their input on what colors they'd like their PDAs to be, and now the best looking options that make sense, will be added in! Woo!

Also I just think the QM having a emergency shovel is kind of cool, and its a really neat item that deserves just a little more love, so why not?

## Changelog
:cl:
expansion: Updated old GAGS colors for the PDAs based on user feedback
imageadd: Updated appearance of the Survival Pen
expansion: The Quartermaster now starts with a Survival Pen because its flavorful. Survival Pen has also been updated to use the fancy font, since, its fancy.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
bepis powercrepe :/

**Comment by EricZilla** [comment]
> bepis powercreep :/

Not sure if this is a joke or not but the survival pen is hot nasty trash stat wise lmao, but if people genuinely think giving one to the QM is a bad idea, I'm happy to change it, I asked around and no one told me it was a bad idea so far

**Comment by maxymax13** [comment]
why did you make the survival pen soulful again

**Comment by EricZilla** [comment]
> why did you make the survival pen soulful again

Implying its currently not?

**Comment by jughu** [comment]
Giving qm bepis gear without having them use bepis
What did b.e.p.i.s every do to you?

**Comment by necromanceranne** [comment]
> Giving qm bepis gear without having them use bepis
> What did b.e.p.i.s every do to you?

be another fad content dump

**Comment by maxymax13** [comment]
make the qm have a subtype with the fountain pen sprite and font rather than all of them

**Comment by EricZilla** [comment]
> make the qm have a subtype with the fountain pen sprite and font rather than all of them

I was thinking maybe I make it a Prototype Survival Pen and get it some fancy flavor text, that way its not the bepis item exactly, but not sure its worth the trouble.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
