### PR TITLE
Removes SNPCs 

### LINKED ISSUE #7041: Interactive humans can pick up items through closed windoors.
Example: put item behind a closed windoor, the interactive human can pick up the item through it, without having to open the windoor first. It's basically not checking whether the mob and item are truly adjacent and not separated by a single pane window or windoor.

### LINKED ISSUE #18678: Various snpc bugs
All of these occurred last night.
Snpcs were staying in crit and not dying from oxy loss or other damage. (There was one that got grenade spammed by another snpc and fell into crit, stayed in crit for at least 15 minutes, then got attacked by a emagged cleanbot, then finally I var edited 200 brute to them and they still were in crit) however a different snpc got lasered and died correctly.

Traitor Psycho snpcs can spam grenades while in crit (they just drop the primed grenade)

Traitor brute (assasinate) snpcs can target lavaland simple mobs (one had their target be a goldgrub)

Snpcs can have their body sprites go invisible.

### LINKED ISSUE #30348: SNPC speech broke somehow
They don't talk even if I jack up their chattyness variable. I don't know how recently this broke.

### LINKED ISSUE #33894: wHAT THE FUCK KIND OF ABOMINATION DID THESE ABDUCTOR ORGANS MAKE
image
image
It was still moving while dead, and delimbed, and cuffed, and buckled, and stunned. It couldn't die no matter what, it couldn't be stopped, and it randomly liked to move to one specific spot for some reason.

Roundid: 80930

I think the ayy organ makes a snpc but WHY IS IT MOVING WHILE DEAD AND DELIMBED AND WHY CAN'T IT BE STOPPED?!

### LINKED ISSUE #34403: Interactive humans can open windoors they don't have access to
Maybe related to #7041

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Closes #34403
Closes #33894
Closes #7041
Closes #30348
Closes #18678

They're unused, they're unmaintained and they're buggy, and no-one new wants to fix them.

:cl: Naksu
del: SNPCs have been removed.
/:cl:

@RemieRichards @Iamgoofball

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
Consider this a webeditor PR as I typed it at work. I only know it compiles.

**Comment by Cyberboss** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by RemieRichards** [comment]
Why of all the people to tag, did you tag myself and goof?
It's @sawu-tg 's work.

**Comment by Ordonis** [comment]
>Cyberboss
Honestly that comment deserves a repoban on its own, absolutely shamefur dispray

**Comment by vuonojenmustaturska** [comment]
@RemieRichards goof has been against removing these as they will supposedly feature prominently in the GOAP thing you and goof worked on. It's gonna be ready any day now, you see.

**Comment by RemieRichards** [comment]
As far as I can recall the examples goof wrote for my GOAP framework were simple animals, I don't recall there EVER being compatibility between GOAP and SNPCs, and if there were I certainly didn't write it.

**Comment by vuonojenmustaturska** [comment]
Ah.

Well, that makes things a lot simpler then.

**Comment by RemieRichards** [comment]
Also, in regards to "It's gonna be ready any day now, you see.", the only way that's happening is if goof has rewritten the GOAP framework from scratch, I already retracted the license for mine from him/tg.

**Comment by vuonojenmustaturska** [comment]
As you probably guessed, this PR reflects my faith in goof actually delivering on GOAP

**Comment by RemieRichards** [comment]
At least that we can agree on.

**Comment by arsserpentarium** [comment]
Maybe you shouldn't? And it could be fixed?

P.S. I've delved into bot code recently. It's horrible.

**Comment by Poojawa** [comment]
porting this instead when https://github.com/PolarisSS13/Polaris/pull/3103

**Comment by vuonojenmustaturska** [comment]
@Poojawa that looks fine, and doesn't rely on SNPCs. Porting it wouldn't be that simple, though, since it predates my NPC idling changes. Also, we want to remove the relationship between typepath and AI behavior.

It might very well be that I'll (or someone else in case they get started before me) use Polaris's simple animals AI as a basis for AI datums instead of our existing stuff. There's a lot of jank in our simples, particularly the retaliate-path is a clusterfuck.

**Comment by Cyberboss** [comment]
@arsserpentarium snpcs are fundamentally broken, you can't fix them

On Feb 27, 2018 9:17 AM, "arsserpentarium" <notifications@github.com> wrote:

Maybe you shouldn't? And it could be fixed?

P.S. I've delved into bot code recently. It's horrible.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/36016#issuecomment-368891954>,
or mute the thread

**Comment by Poojawa** [comment]
I actually started porting at it, then hit the brick wall with the NPC subsystems, got distracted, and been doing other things.

Basically the handful of NPC idle stuff just has the additional modes (8 lists of behaviour reee) and followed up with replacing the emotes, etc.

**Comment by Buggy123** [comment]
:+1: snpcs are broken as all fuck, which wouldn't be a issue except _someone decided to make it possible to encounter them during normal gameplay_, namely abductor glands.

Good riddance you hyper-broken pieces of crap, may you never befuddle me for a entire round again.

**Comment by Iamgoofball** [comment]
Yeah sorry remie that's not how licenses work and you know it

**Comment by DaedalusGame** [comment]
abductor glands that make snpcs are deleted, buggy

**Comment by RemieRichards** [comment]
@Iamgoofball Yes it is, I provide a license for my work to /tg/, it never got added, thus it never actually fell under AGPL, only under my personal extension to both /tg/, and to you (so you could work on it) the literal only part you can take without my permission now is the examples you made using the system (now essentially useless), and the 2-3 lines of fix you applied.

**Comment by Iamgoofball** [comment]
The code did indeed go agpl as it was integrated into an AGPL repo, your previously mentioned "personal extension to /tg/"

**Comment by RemieRichards** [comment]
It was not integrated into an AGPL repo, it was a pr to an AGPL repo, which would have become AGPL if it were merged, which it was not.
A test merge does not count.

**Comment by deathride58** [comment]
AGPL is AGPL is AGPL is AGPL is AGPL is AGPL is AGPL.

The AGPL license cannot be revoked. When you upload something to github, that thing is automatically licensed under the repo you uploaded it to, no exceptions, no "but"s, etc. Therefore, your code is AGPL.

**Comment by RemieRichards** [comment]
@deathride58 
>When you upload something to github, that thing is automatically licensed under the repo you uploaded it to

Cite your sources or fuck off, I agree entirely for it being ADDED MERGED INTO A PROJECT, which would make it legally part of the 'work' licenses discuss, which it never was.

**Comment by deathride58** [comment]
@RemieRichards https://help.github.com/articles/github-terms-of-service/#d-user-generated-content

Read the ToS, lol

**Comment by PKPenguin321** [comment]
😢 these were fun to spawn now and then

**Comment by MrStonedOne** [comment]
So you agreed to have your work included in a agpl repository?

Knowing that agpl would require the work be licensed as agpl?

Therefore you agreed to license your work under agpl?

>All rights granted under this License are granted for the term of copyright on the Program, and are irrevocable provided the stated conditions are met.

When goofball finally finishes GOAP I should warn you that all dmca requests have to sent to /tg/stations registered DMCA agent. You may find this information here: https://dmca.copyright.gov/osp/

Good day.

**Comment by vuonojenmustaturska** [comment]
image
@AnturK populate world restored, the outfits it generates are pretty random but good enough for testing probably

**Comment by RemieRichards** [comment]
Section 6, no mention of merging at all

```
6. Contributions Under Repository License
Whenever you make a contribution to a repository containing notice of a license, you license your contribution under the same terms, and you agree that you have the right to license your contribution under those terms. If you have a separate agreement to license your contributions under different terms, such as a contributor license agreement, that agreement will supersede.
```

>Whenever you make a contribution to a repository

I have made no contribution, as the PR was never merged.

**Comment by MrStonedOne** [comment]
So goofballs fork isn't a repository?

**Comment by RemieRichards** [comment]
Did I pr it to his? If so, then fine, I agree, I thought I PR'd it here separately.

**Comment by deathride58** [comment]
```
5. License Grant to Other Users
... If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking).
```

**Comment by RemieRichards** [comment]
@deathride58 that's not at all relevant, that's a right to view not a right to use.

**Comment by deathride58** [comment]
@RemieRichards 
```
You grant each User of Github a nonexclusive, worldwide license to ***use***
```

**Comment by RemieRichards** [comment]
Actually, I never PR'd it anywhere, I personally handed him a ZIP.
That's fine then, whatever.

Know I'm not happy with it (you already know), but continue.

**Comment by RemieRichards** [comment]
@deathride58 yes, because I can definitely just grab a piece of an AGPL work on github and put it in my MIT project because "Oh hey, section 5!!!!"

**Comment by deathride58** [comment]
@RemieRichards Now read the next bit of the same sentence.

```
... through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality...
```

Basically, so long as both your project and the project with code you want to take from are both public repositories on GitHub, you have a nonexclusive right to take code from that other repository and that other repo has the nonexclusive right to take code from yours, as outlined in the ToS. Licenses may restrict usage outside of GitHub, but by having your code on a public GitHub repo, you agree that any repository that's also on GitHub can use your code freely.

You can talk about this with a lawyer, and they'll tell you the exact same thing.

**Comment by JJRcop** [comment]
get this discussion off this pr please

**Comment by RemieRichards** [comment]
@deathride58 that still doesn't allow them to use it, why are you still trying? you got what you want asshat.

**Comment by Iamgoofball** [comment]
@vuonojenmustaturska i dont think we're going to get anything useful out of this, could you please lock?

**Comment by Robustin** [comment]
# Disclaimer:

Please note that my thumbs down emoji (hereinafter "The Emoji") on Comment "[369006477](https://github.com/tgstation/tgstation/pull/36016#issuecomment-369006477)" (hereinafter "The Comment") does not constitute individual legal advice. The Emoji represents a publication on a legal topic pursuant to 7.1(r) of the New York Rules of Professional Conduct. Specifically, the Emoji is a symbolic representation of my view that the Github Terms of Service do not function as described in The Comment.

This publication is not intended to provide legal advice but to provide general information on legal matters. Transmission is not intended to create and receipt does not establish an attorney-client relationship. Readers should seek specific legal advice before taking any action with respect to matters mentioned in this publication.

**Comment by optimumtact** [comment]
I assume you developed your code within the context of the /tg/station codebase?

**Comment by Cyberboss** [comment]
>Unsubscribe

**Comment by deathride58** [comment]
@Robustin Please seek mental help before you're only capable of speaking legalese.

But aye, read over section D3 of GitHub's ToS. By accepting GitHub's ToS, having your code public on GitHub is more or less granting GitHub and other GitHub users the license to use your code for other projects on GitHub, having a license that's incompatible with this is against the ToS. And that's not even getting into the additional layers of complexity that AGPL and other open-source licenses add into the mix.

This discussion would be best taken away from this PR, though. The point of "Hey, this specific code is legal for us to use" has already been made, proven, etc. Discussing this further in this PR isn't very productive for this PR.

**Comment by Buggy123** [comment]
B E G O N E T H O T S

**Comment by RemieRichards** [comment]
@optimumtact as was explained above, there was no PR at all, I simply handed goof a zip.
The code was made in a clean byond environment, so no, not really in the context of tg anyway.

**Comment by PKPenguin321** [comment]
rip botany snpcs
You were too funny for this world

**Comment by optimumtact** [comment]
well I'm no lawyer but it what if when you gave goof the code there was some kind of unwritten implied contract formed

**Comment by Iamgoofball** [comment]
The code was provided with the understanding that it would be fixed up and integrated into my /tg/station repository, as seen at the original GOAP PR.

capture

**Comment by RemieRichards** [comment]
@optimumtact which I already yielded above.

**Pull request merged**
