### PR TITLE
[NO-GBP] Optimizes rad nebula

### PR DESCRIPTION
**Pull request by Time-Green**
I applied rads to objects thinking it was fine, since it was fine on local
image, but high-pop couldn't handle it that well.

This caused SSradiation to get slowed and not rad people very fast in space, since we applied it to the tile and if there's even slight lag, we'll already be of the tile by the time we pulsed radiation

Instead, adds a new element: Radioactive exposure! It doesn't pulse and instead starts a countdown with some rng and starts applaying the radiation directly. Also, instead of spamming your chat, you get a yellow hud alert that you're going to melt soon

image

:cl:
fix: Makes radiation nebula space work on high-pop by applying the radiation more directly
balance: Internal nebula storm no longer gives 10 seconds of immunity and has a very, very small chance to apply mutations
balance: Rudes nebula rad immunity from 10 seconds to 6 seconds (shouldn't differ too much since we use a different system now)
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
I might get back to this tomorrow and just ditch the whole radioactive element, and just do what radstorms do

**Comment by AtomTheProphet** [comment]
> I might get back to this tomorrow and just ditch the whole radioactive element, and just do what radstorms do

That just seems like it'd take out what was interesting about it, honestly.

**Comment by Time-Green** [comment]
> > I might get back to this tomorrow and just ditch the whole radioactive element, and just do what radstorms do
> 
> That just seems like it'd take out what was interesting about it, honestly.

Don’t worry, you wouldn’t be able to tell in-game. I mean as in without a clumsy element that kinda does what I want but not really

**Comment by Time-Green** [comment]
I changed the behaviour to work better on laggy rounds, so the balance also changes slightly, and should have less cases of people moving fast in laggy rounds just being radproof

**Pull request merged**
