### PR TITLE
Fixed slaughter demon exit speed boost

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
fix: Fixed slaughter demons not getting a speed boost when exiting a
pool of blood. Fixed slaughter demon giblets not being visible.
/:cl:

- Also switches some spawn() to timers, and got rid of a var on
slaughter demon previously tracking speed boosting.

### CODE REVIEW

**Comment by necromanceranne** [comment]
Oh they're supposed to have a speed boost? Oof.

**Comment by Borisvanmemes** [comment]
iirc it's more that they get a slow down the longer they're out of blood.

**Comment by Tlaltecuhtli** [comment]
give it a cooldown on getting in and out of blood

**Comment by coiax** [comment]
That is out of scope for this PR.

**Comment by Jordie0608** [comment]
Conflict

**Review by Cyberboss — CHANGES_REQUESTED** [review]

**Pull request merged**
