### PR TITLE
Adds a new hat for seasoned fishermen (but this time I didn't fuck up the pr! Are you proud of me dad?)

### PR DESCRIPTION
**Pull request by Bytube**
## About The Pull Request

Adds a new hat to ClothesMate vending machines, perfect for the inner angler in you! (Now with 100% less commit fuckups!)

## Why It's Good For The Game

Adds a cool new hat

## Changelog
:cl:
add: Adds fishing cap to ClothesMates
imageadd: adds fishing cap sprites
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
(I am proud of you yes)

**Review by Twaticus — APPROVED** [review]

**Comment by MrStonedOne** [comment]
@tgstation/commit-access

**Comment by optimumtact** [comment]
Pretty uncompelling PR to be honest, no associated mechanics, just a sprite.

No wonder it's been ignored

**Review by Kylerace — APPROVED** [review]
code is good

**Comment by LemonInTheDark** [comment]
I don't like the joke

**Comment by Farquaar** [comment]
Am I the only person who thinks this doesn't look like a fisherman's cap in the slightest? It's literally just a white baseball cap/trucker hat with green accents.

A fisherman's cap should look something like this, in my mind:

Or this:
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.alamy.com%2Fstock-photo%2Ffishing-hat-with-flies.html&psig=AOvVaw3ZoOSxQhctPYpkNPnhAWDG&ust=1629486056255000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCKj_lfDivfICFQAAAAAdAAAAABAa

**Comment by ArcaneMusic** [comment]
That's why it's called a fishing hat, not a fisherman's hat.

enthusiasm vs professionalism.

**Comment by LemonInTheDark** [comment]
should closed this earlier, but man, I don't think the joke fits the game I'm sorry
still proud tho

**Comment by Bytube** [comment]
> should closed this earlier, but man, I don't think the joke fits the game I'm sorry
> still proud tho

That's fair. Oranges also had a fair criticism about there not being much content either, so if I ever revisit this to your dismay I'll probably include it in a larger pack of new clothing than just it by itself

**Comment by MrStonedOne** [comment]
@tgstation/commit-access don't delete my comments!

**Comment by LemonInTheDark** [comment]
image

**Pull request closed without merging**
