### PR TITLE
Updates Round End News Message for when Nuclear Operatives succeed to be more gender-neutral

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

On the tin. Hopefully the comedic timing isn't TOO gadzonked from this, but I think it feels OK.

## Why It's Good For The Game

It just doesn't make sense to have the gender-neutral "he" for this game when you could have someone playing a female character (or anything else). I shrug my shoulders and ride off into the sunset.

## Changelog

:cl:
fix: The Nanotrasen News Network has updated their news tickers for when a station horrifically blows up to be more accommodating towards the person directly responsible for making sure it didn't horrifically blow up.
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
We clearly need a global var that represents and tracks the current canonical captain's gender

**Comment by san7890** [comment]
> We clearly need a global var that represents and tracks the current canonical captain's gender

code it then

**Comment by newfren** [comment]
they?

**Comment by san7890** [comment]
> they?

No, I just removed the pronoun entirely.

**Comment by SuperNovaa41** [comment]
this flows better anyways

**Comment by LemonInTheDark** [comment]
> > We clearly need a global var that represents and tracks the current canonical captain's gender
> 
> code it then

Sounds like a lot of work. Plus, this is better

**Comment by san7890** [comment]
> > > We clearly need a global var that represents and tracks the current canonical captain's gender
> 
> > 
> 
> > code it then
> 
> 
> 
> Sounds like a lot of work. Plus, this is better

👍

**Pull request merged**
