### PR TITLE
Adds a low-grade virus control crate to cargo

### PR DESCRIPTION
**Pull request by ghost**
Crate contents:
1. Box of latex gloves
2. Box of sterile masks
3. Two health analyzers
4. Two spaceacillin pills
5. One low-grade cure pill (cures magnitis and the common cold)
6. A bar of soap for sterilization
~~7. A coil of rope for hanging the virologist~~

Each crate contains a relatively small amount of supplies. It's only enough to _stop_ diseases that are already trivial in both effects and curing (the common cold and magnitis) but it can also be effective in controlling the spread of more debilitating diseases as well as diagnosing them.

The latex gloves and sterile masks are primarily intended for the civilian crew so they can have at least somet sort of defense from an outbreak. A competent medbay usually distributes these anyway during an outbreak.

They're meant to be ordered in bulk during big virus outbreaks and in singles during smaller ones. It also provides an alternative to chugging Star-Kist when you catch a cold and wasting Chemistry's entire stock of iron when you catch magnitis.

Also adds the pills used in the crate since they weren't in the code by default.

### CODE REVIEW

**Comment by tkdrg** [comment]
I don't see the point of this. This is basically useless in big disease outbreaks, and will probably end up being ordered just for being the easiest way to get soap. And why magnitis? Why not the cold and the flu (which would make a lot more sense)?

**Comment by Xhuis** [comment]
It _does_ cure the cold. I don't see why people would order it for the soap at any rate, but I could possibly remove it.

The point of it is to be an aid in larger outbreaks and to make tiny diseases that commonly infect the crew not a pain in the back to cure.

**Comment by AlexanderUlanH** [comment]
>isolation of infected patients.
Good one.
Virology has a spaceacillin syringe.  Each medivend has tons.  They're never used because by the time someone realizes they've gotten a disease and makes it to medical, they've spread it to half the crew.

**Comment by Jordie0608** [comment]
Changelog

**Comment by Xhuis** [comment]
Gonna close this since support seems low and I don't see a reason to go through with it

**Pull request closed without merging**
