### PR TITLE
Rocket Boots 2: ASCEND

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
#56609 but I remade it also I made shitty flame decals on the boots so it looks cool
Adds Rocket Boots, a black market pair of jump boots that makes you slam into walls (or people) up to 20 tiles away. SHAZBOT!

[YES I DID TEST IT THIS TIME OK](https://i.imgur.com/Fqnu9sV.png)

## Why It's Good For The Game
So people can give themselves <s>brain damage</s> fractures in a different way than meth while they avoid the popo.

## Changelog
:cl: TribesChen
add: Rocket boots, a bad idea from the black market that hurls you 20 tiles in the direction you're facing. Beware of walls and people.
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
I have a VERY important question from all my friends angry about icebox.
Can you use the rocket boots to go from one zlevel to the one above?

**Comment by YakumoChen** [comment]
No, they're just edited Jump Boots that let you go farther and it hurts more when you slam into things.

**Comment by D4C-420** [comment]
still not sure what the black market but i mean this will be fun on tram

**Comment by YakumoChen** [comment]
Black Market is a shop you can access through a crafted recipe item (it needs a telecomms part, a wire, and an analyzer iirc). It has a per-round selection of black market items, and you can buy it through a couple methods that are generally unreliable (depending on the method you might not get the item at all or it teleports to a random spot you have to get to before its stolen)

Black market items are generally some kind of contraband or something that stands out, but they're nowhere near as good as traitor gear.

**Comment by D4C-420** [comment]
> Black Market is a shop you can access through a crafted recipe item (it needs a telecomms part, a wire, and an analyzer iirc). It has a per-round selection of black market items, and you can buy it through a couple methods that are generally unreliable (depending on the method you might not get the item at all or it teleports to a random spot you have to get to before its stolen)

thanks. could not find it on the wiki

**Comment by itseasytosee** [comment]
Actually making the black market uplink is a bit annoying in my experience. The telecoms part needs research to be built and people don't tend to research telecom stuff.

**Comment by YakumoChen** [comment]
Just steal it from tech storage I guess /shrug

That's a problem for someone else's PR, not my awesome ROCKET BOOTS PR

**Review by Twaticus — APPROVED** [review]

**Comment by TheBonded** [comment]
Finally, a black market item to rival the combat medic hardsuit!

**Comment by maxymax13** [comment]
to obtain them you must punch pchoo into a data disk and put it in an autolathe :trollface:

**Comment by TheBonded** [comment]
Normal jump boots only send you 4 tiles, these are 5 times as strong.

**Comment by YakumoChen** [comment]
Jump boots are for Llamas

**Comment by TheBonded** [comment]
Maybe add these to a BEPIS research as well, so there's multiple ways of getting it?

**Comment by YakumoChen** [comment]
While the potential for Tribes13 would be **extremely** funny, I think it's best to keep it as a black market item. Feel free to make your own additional PR if you think otherwise

**Comment by YakumoChen** [comment]
@Mothblocks

**Pull request merged**
