### PR TITLE
Makes sleepypens refillable

### PR DESCRIPTION
**Pull request by Iamgoofball**
2ol23dl
read title, there was support for this on the forums so I coded it

### CODE REVIEW

**Comment by Supermichael777** [comment]
dont let your dreams be memes, JUST DO IT.
:+1: :-1:

**Comment by TechnoAlchemisto** [comment]
I can think of a lot of horrible things this could lead to but i'm a sucker for it

**Comment by WJohn** [comment]
I thought this was already the case.

Huh.

Neat, anyway :+1:

**Comment by PKPenguin321** [comment]
right now they're so, so, soooo bad
now they'll be useful and maybe, just maybe, lethal again
:+1:

**Comment by Iamgoofball** [comment]
@PKPenguin321 the code says radio icons should work but they dont so probably miauws fault

**Comment by Cheridan** [comment]
>on the other hand this was removed for a reason.

Because chloral existed?

**Comment by Zilenan91** [comment]
Are these abusable? Yes. Would they be powerful? Yes. :+1:

**Comment by Tokiko1** [comment]
:+1: 
We already have dart pistols, which are ranged, reuseable, silent chem injectors. Might aswell make sleepy pens useful too.

**Comment by Lumipharon** [comment]
with a traitor chem kit you can make 1 click (extremely fast) kill pens.
Judge as you will.

**Comment by Dorsisdwarf** [comment]
Still weaker than a parapen :+1:

**Comment by CPTANT** [comment]
how much does it transfer per prick? And does this mean you can also take out the chemicals already in the pen when it is bought?

**Comment by Miauw62** [comment]
Radio icons were removed before I rewrote saycode because people metagamed
them.

Also, I find it hilarious how people think sleepypens are weak. They're
still incredibly BS.
If you're doing this, just do away with the initial pen content. Not that
this will ever see interesting uses beyond "i stab u loose xd", but hey.
Op 3-nov.-2015 02:57 schreef "Iamgoofball" <notifications@github.com>:

**Comment by Nanotransistor** [comment]
This will be interesting in combination with the poison kit.

**Comment by Iamgoofball** [comment]
@Miauw62 I'm cool with making it start empty, actually. Encourages more creativity.

@CPTANT It injects the contents all in 1 go, and you can't manually remove reagents. Just inject into a monkey to purge chems like I did in the screenshot.

**Comment by Iamgoofball** [comment]
Also miauw: I found the line where it SHOULD be doing radio icons(it already has the \icon[radio] macro and shit) but it doesn't work for some meme reason

**Comment by SweaterKittens** [comment]
I agree with making them start empty if you're to do this. As goof said, it encourages creativity, and if someone is buying this (especially with a toxins kit) you're going to have PLENTY to fill it with.

**Comment by CPTANT** [comment]
though in that case it would still be nice to have access to the crypto + whatever cocktail there is in the pen now.

**Comment by Zilenan91** [comment]
Yeah it'd be nice to have this start empty if we want to make it refillable.

**Comment by CPTANT** [comment]
hmmm looking at this, doesn't the open container also make you able to extract from it with a syringe?

**Comment by Lumipharon** [comment]
starting empty also makes it useless unless you get the traitor kit, or have access to a chemdispenser.
Enjoy your empty pen from RNG crates and bundles.

**Comment by Zilenan91** [comment]
Lumi that's literally what the rapid fire dart gun from the uplink does already. It's just a faster firing syringe gun with nothing in it.

**Comment by Lumipharon** [comment]
I know, and that's fine. I'm just pointing out that the pen as it stands doesn't depend on other things to have a use.

**Comment by Fox-McCloud** [comment]
:+1: 

Might I suggest just making it have morphine or something like that? Has a bit more counterplay that way unless someone puts effort into making silencing chems.

**Comment by PKPenguin321** [comment]
@Fox-McCloud do you even [know how to look at code you nerd](https://github.com/tgstation/-tg-station/pull/12827/files#diff-c24c3459969061941d417de536b58472R83)

**Comment by Fox-McCloud** [comment]
I think you misinterpreted what I said. Since it's *refillable* and that makes it objectively better, then have it so the ONLY reagent it has is morphine.

**Comment by Cheridan** [comment]
let's try it

**Pull request merged**
