### PR TITLE
tram fixes pt. 

### LINKED ISSUE #64910: TramStation Mine Apc  (Lower Service Maint) is wrongly placed and wont charge
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Screenshot_2

### LINKED ISSUE #64936: New tram med - multiple issues
## Reproduction:
```
- Be chemist
- Enter pharmacy
- No lights
```
```
- Be doctor 
- Go to buy chems from the vendor
- No chem vendor
```
```
- Be paramedic
- Try to grab a medhud
- no spare huds
```

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request

- Adds 3 medhuds to medstorage tables as well as an additional one in each medical locker.
- There is a nanomed in the treatment center and one in the main hall in the top right
- A chem vendor is now in medical storage, the meddrobe has been moved close outside near the pharmacy.
- The pharmacy now has lights (how the fuck did I forget these I literally added a light switch but not the lights)
- Robotics now starts with 3 module cores
- The research test lab has been updated to include the circuit/module duplicators.
- Engineering has 2 modules in their storage room
- The perma hydroponics now actually has tools + a nearby sink for plant watering.

## Why It's Good For The Game

~~part of my scheme to purposefully push un-finished map PRs with improper labeling to tank my GBP and then slowly rebuild it via fix PRs~~ i'm becoming forgetful with old age and can't remember to put lights in a room i put a light switch in

## Changelog

:cl: MMMiracles
fix: Tramstation now has equipment for MODSUITS(2021)
fix: The pharmacists have had their lighting budget re-instated.
fix: Nanomeds now exist in the treatment center and the main medical hallway.
fix: Genpop prisoners can now actually garden.

/:cl:

Fixes #64936
Closes #64910

image

### CODE REVIEW

**Comment by Colovorat** [comment]
aight i will write it here
Tram perma hydroponics has 0 shit in it, hydroponics crate only has seeds. No tools, no bucket, no water tank nearby

**Comment by MrMelbert** [comment]
the white medkits in med storage are empty subtypes btw

**Comment by MMMiracles** [comment]
what the fuck did i do

**Comment by MMMiracles** [comment]
lol im not fixing this branch

**Pull request closed without merging**
