### PR TITLE
Cyberboss vs LICENSE round 27

### PR DESCRIPTION
**Pull request by Cyberboss**
If this doesn't work, I concede

### CODE REVIEW

**Comment by nicbn** [comment]
Maybe you should name it `OLD_LICENSE-GPLv3` without the txt extension?

**Comment by Cyberboss** [comment]
The problem is "LICENSE" in the title judging by my convo with GitHub support

**Comment by CPTANT** [comment]
What problem does this solve?

**Comment by Cyberboss** [comment]
I'm trying to get github's license detector working on the repository

**Pull request merged**
