### PR TITLE
Magical Animations Update Part 2: Staffs

### PR DESCRIPTION
**Pull request by Nabski89**
:cl: Magical Animations Update Part 2: Staffs

imageadd: Added animations for the following magical staffs: Nothing, Change, Animation, Door, Chaos, Lava, Healing.

/:cl:

[why]: # Magical Animation is cool. I didn't do the banana staff because I don't like it.
staves Staff of nothing is not pictured because I forgot about it.

### CODE REVIEW

**Comment by Shadowflame909** [comment]
The healing staff is basically advanced electricity? It's a super defib!

**Comment by SpaceManiac** [comment]
I like the new looks. It seems like the errors fall from *undoing* with this PR what your animated spellbooks PR did.

**Comment by Shadowflame909** [comment]
THAT'S NOT A KEY NABSKI. IT'S A SPEAR. A SPEEEEEEEEEAR.

**Comment by Nabski89** [comment]
Key-blades and key staffs are silly. I made one but then decided I like the nature staff more.

**Comment by Nabski89** [comment]
I used the web version to drop the current library.dmi files for that commit, so I don't understand how it's still conflicting.

**Comment by SpaceManiac** [comment]
For various reasons it's not really possible to resolve conflicts in binary files (such as images) in the web interface, you have to use the command line.

If you're really stuck I can take a stab at it for you.

**Comment by SpaceManiac** [comment]
Overview of how to handle some of this stuff from the CLI, more info is on google:
* Make sure you have two remotes
  * `origin` to `git@github.com:Nabski89/tgstation`
  * `upstream` to `tgstation/tgstation`
* When updating your master
  * `git checkout master`
  * `git pull upstream master`
* When starting a PR
  * Update your master
  * `git checkout -b pr-branch-name`
  * Make changes, commit
  * `git push -u origin pr-branch-name`
* When updating a PR to latest
  * Update your master
  * `git checkout pr-branch-name`
  * `git merge master`
  * If needed, resolve conflicts and `git commit`
  * `git push`


Applying that to this situation:
* Update your master
* `git merge master` - begin the merge, it will pause due to conflicts
* `git checkout master icons/obj/library.dmi` - resolve the conflict by accepting the version of `library.dmi` from master
* `git commit` - now that conflicts are resolved, finish the merge
* `git push`

**Comment by optimumtact** [comment]
pssh don't listen to that guy, just follow my guide and you'll be rich in no time

https://github.com/tgstation/tgstation/wiki/Resolving-icon-conflicts-for-fun-and-profit

**Comment by TBartl** [comment]
In my unbiased opinion this should be speed merged.

**Review by SpaceManiac — APPROVED** [review]
That last one was just to make sure GitHub wasn't going to do anything funny when I merged it

**Comment by Nabski89** [comment]
Thank you, both of you for the help.

**Pull request merged**
