### PR TITLE
[s] Limits tgui topic calls

### PR DESCRIPTION
**Pull request by lzimann**
Topic calls will now have a 5 ds cooldown.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Change 5 to a preference pickable option, including no delays, for those of us who TGUI doesn't murder.
(this also lets people who it royal fucks set it to something higher like, 20)

**Comment by lzimann** [comment]
This is not to prevent lag or anything. This is to limit spam(maybe not the best way but couldn't think of anything else)

**Comment by Chnkr** [comment]
This is a terrible solution

**Comment by lzimann** [comment]
Feel free to suggest something better(or a pr of your own for this) then.

**Comment by rainbowjose** [comment]
NJose much appreciated

**Comment by Incoming5643** [comment]
@RemieRichards off topic but the horrible performance issues with TGUI are related to the initial load, topic call refreshing is actually fine.

**Comment by kevinz000** [comment]
Pls 1 ds so I can hack faster

**Comment by lzimann** [comment]
MSO did a better job with #23478

**Pull request closed without merging**
