### PR TITLE
resprites fire extinguishers

### PR DESCRIPTION
**Pull request by pudl**
resprites the fire extinguisher. credit to wjohnston

http://puu.sh/gij8C/6575ae3534.png

### CODE REVIEW

**Comment by Antimattercarp** [comment]
ucv0otd
http://i.imgur.com/ucV0otd.png
Found these on r/ss13 , might be better

**Comment by fj45** [comment]
I am the one who requested those, I would recommend using the top water extinguisher with the thin nozzle as its a little clearer and very few water extinguishers use a wider nozzle. 

I requested all the other types in-case anyone wants to code a few other fancy extinguisher types.

**Comment by pudl** [comment]
@fj45 i asked wjohnston what sprite he wanted used and he said thick nozzle.

**Comment by dannno** [comment]
thick nozzle looks dumb

**Comment by WJohn** [comment]
It's personal preference, but if the players want a thinner nozzle then I say let them choose.

**Comment by Fox-McCloud** [comment]
Concur with WJ that the thick nozzle would be best, especially given how wide the spread is on the water spray.

Ideally it would be the thick one without the black band.

**Comment by fj45** [comment]
No nozzle design could account for the insanity that is the fire extinguishers spray pattern. 

Crazy idea, have all the extinguishers across the station randomized between the different colours and nozzle types. Even without any mechanic change between them.

**Comment by Fox-McCloud** [comment]
One unified sprite would be better since every single one utilizes water; different styles would infer different types of extinguishers, which there obviously is not.

**Comment by fj45** [comment]
I can agree with that. Randomized nozzle type then?

**Comment by pudl** [comment]
you are literally a joke

**Comment by pudl** [comment]
can this be merged some day

**Comment by pudl** [comment]
@Nienhaus @WJohn

**Comment by WJohn** [comment]
:+1:

**Comment by pudl** [comment]
merge when

**Comment by Nienhaus** [comment]
WJohn can't merge his on sprites iirc :D

**Pull request merged**
