### PR TITLE
Implements RCL radial wiring menu

### PR DESCRIPTION
**Pull request by Flatgub**
## About The Pull Request

This PR adds additional functionality to the Rapid Cable Layer (RCL), adds a subclass of radial menu and fixes a small bug.
image
The primary feature of this PR is the fast wiring menu, a toggleable radial menu for the RCL that allows the player to both place and link wire knots directly at their feet in all 8 directions. 
imageimage
The fast wiring menu will filter out which knots to wire from based on colour to allow easy layering of wires via colour
image

This PR adds a subclass of `radial_menu` called `radial_menu/persistent` which doesn't automatically close, instead persisting on the screen until manually closed and fires a callback each time an element is clicked.
The lack of a wait loop does however prevent it from doing automatic checks and so the menu must manually be kept track of and destroyed by its owner.

This PR also fixes an undocumented bug with the RCL which caused the change cable colour button to not have any affect until the player had laid one unit of cable by walking. 

## Why It's Good For The Game

Due to the fact that players can only face four directions, but wires can be placed in 8, diagonal wiring has previously required a lot of side stepping and in general wiring at your feet has been cumbersome. The functionality added in this PR makes the RCL more useful and makes fancy or intricate wiring much faster to do.

## Changelog
:cl:
add: Added RCL wiring menu
fix: RCL change cable colour button now applies changes immediately
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Will the menu update automatically with new options if I move to a different tile while having the menu open?

**Comment by Flatgub** [comment]
Yes, the preview is based on wires currently at under your feet, if you move to a different tile the menu will update.

**Comment by Cyprex** [comment]
This seems incredibly cool, could this be applied to regular wires as well?

**Comment by Flatgub** [comment]
In theory, yes, but it would require adding a lot of code to cable coils for them to be able to update automatically. The RCL already had the groundwork for this functionality in a way that cable coils don't and also as a _rapid_ cable layer, I think the feature being specific to it suits it well.

**Comment by Fikou** [comment]
place one RCL in the chapel so chaplain can make advanced wire art

**Comment by Flatgub** [comment]
These changes also apply to the ghetto RCL, which is craftable, so the chaplain should be able to make on with relative ease

**Comment by ATH1909** [comment]
> with relative ease

https://ytcropper.com/cropped/rW5cd47c23b7cf1

**Comment by Majick1** [comment]
+1 pretty wires

**Comment by optimumtact** [comment]
thanks for the PR

**Pull request merged**
