### PR TITLE
Better alert/announcment sounds and Status displays

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
**Simplified version of #72179**

### SOUNDS

Changes next sound files:
- airraid.ogg
- bloblarm.ogg
- alert.ogg

Adds next sound files:
- notice3.ogg
- announce_syndi.ogg

Now `announce.ogg` plays when a Captain joins round, and `announce_dig.ogg` for Requests Console announcements.
The `announce_syndi.ogg` plays when an announcement is made through an emagged communications console. It also plays when the evacuation shuttle is fully hijacked or Cultists fully corrupt the evacuation shuttle.
You can listen to them all here:

https://github.com/tgstation/tgstation/assets/42353186/10c5e597-6db7-464a-b693-f5a2672dc3d0

_All of the sound files are either made by me from existing sounds in the game or taken from freesound.org and properly credited._

### STATUS DISPLAYS
Status displays are fully replaced with the addition of a few new ones.
<details>
<summary>Status display monitor</summary>

monitor
logo

</details>
<details>
<summary>Misc displays</summary>

biohazard_big
lockdown_big
radiation_big

</details>
<details>
<summary>Alert displays</summary>

greenalert_big
bluealert_big
redalert_big
deltaalert_big

</details>

Now the communications console Status Display menu replaced the "Red Alert" display option with the "Current Alert" which showcases the current alert display.
Also, the Status Display menu has an additional "Radiation" display option.
## Why It's Good For The Game

I believe this Pull Request is a good game for a couple of reasons:

1. It better conveys the gravity of emergency situations, such as Code Red, by utilizing a more intimidating and recognizable sound. This gives more weight to these situations, making them feel more urgent and important in the game. Players always tend to not notice that it's in action.
2. The replacement of the old and outdated Status Display sprites with newer, more eye-catching ones is a great improvement. This helps to emphasize the importance of emergency situations even further by making them more noticeable. Status Displays was one of the last wall-mounts using ancient sprites.
3. The Captain's arrival using another sound effect from other announcements gives more status to the Captain as the ultimate head of the station.
4. Heads announcement using `announce_dig.ogg` makes the sound itself more used outside of SM cascade, and also makes Head announcements more noticeable.
5. Emagged console using `announce_syndi.ogg` making Traitor announcements more noticeable. Also, it is played after evac shuttle is fully hijacked or corrupted by Cultists giving a more ominous effect
## Changelog
:cl:
sound: Adds/modifies next sound files: airraid.ogg, bloblarm.ogg, alert.ogg, notice3.ogg, announce_syndi.ogg
sound: Code Red, Delta, and other extreme emergencies now possess more unique alarm sound effect
sound: Captain's arrival now is announced by Captain's announcement sound, but not for Acting Captain's
sound: Making Captain announcement through emagged console; hijacking or fully corrupting evacuation shuttle now plays more ominous sound
sound: Making announcements through Requests Console now plays a more noticeable sound
image: Status Displays sprites have been fully changed. Now they include displays for every Security Level
qol: The "Red Alert" button in the Communications console status display menu has been replaced with a "Current Alert" button showing the current station Security Level display on Status Displays
qol: Communications console status display menu got a new "Radiation" button which shows radiation symbol on Status Displays
/:cl:

### CODE REVIEW

**Comment by DrDiasyl** [comment]
> The blobalarm is REALLY intense for just a radiation storm, but otherwise super enthused about this

It is used in some other situations, like SM having EXTREMELY LOW integrity.

**Comment by Wallemations** [comment]
Does the monitor line up with the rest of the visuals/text that can appear on it still?

**Comment by DrDiasyl** [comment]
> Does the monitor line up with the rest of the visuals/text that can appear on it still?

Yes.

**Review by Wallemations — APPROVED** [review]

**Review by Ghommie — APPROVED** [review]

**Comment by Ekaterina-von-Russland** [comment]
Yes! He did it, he didn't let the idea die! He came back stronger than ever and we'll all be better off for it! Good job!

**Pull request merged**
