### PR TITLE
Fixes a runtime with headcrabs controled by non changeling players.

### PR DESCRIPTION
**Pull request by phil235**

### CODE REVIEW

**Comment by Incoming5643** [comment]
Any headcrab spawned monkey should be a changeling, that status should probably be hardset on monkey creation if the mind didn't already have it (only possible when gold slime cores are used or admin spawned on the map.)

That said any more safeguards against the monkey apocalypse is always good.

**Comment by GunHog** [comment]
This allows us to create non-antagonist changelings, right? Or that is to say, due to the nature of the potions, "allows us to create changeling slaves".

**Comment by Incoming5643** [comment]
Station aligned changelings yes.

Keep in mind it takes several end tier slimes, a lot of RNG luck, and some know how on how to use head slugs. I've only ever seen it done once or twice in a number of months, and ironically never during a changeling round.

**Comment by WJohn** [comment]
Yeah in order to make these you need gold and pink slimes, as well as a corpse and a lot of time to let it manifest.

**Comment by GunHog** [comment]
I love the idea. I would love to be a station aligned Changeling!

**Pull request merged**
