### PR TITLE
Effects can no longer trigger landmines

### LINKED ISSUE #55382: Mines are set off by directional lighting
## Reproduction:

1). Grab a  `/obj/effect/mine` of any type
2). Get a light source and turn it on (for your directional lighting of course)
3). Go towards the mine with your handy dandy light
4). Your directional lighting will set off the mine, and can be seen as doing so in the chat feed.

Probably has to do with its triggering check.

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
This PR makes it so /obj/effect's can no longer trigger landmines since things like directional lights and countdowns shouldn't be doing that
Fixes: #55382

## Why It's Good For The Game
Flashlight lights shouldn't be triggering landmines

## Changelog
:cl: Ryll/Shaps
fix: Effects like flashlight lights will no longer trigger landmines
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
Not a fan of the way this is done.

**Comment by Ryll-Ryll** [comment]
> Not a fan of the way this is done.

@actioninja would changing it to checking /obj/effect/abstract work? Directional lights are basically the only atoms that cause these issues, so I'd rather not overengineer some new flag for everything to check for this

**Comment by actioninja** [comment]
I take issue with that it's a type check in the first place. I am unsure of what a better way of doing it would be, hence the ambiguous statement and not "do it this way."

**Comment by LemonInTheDark** [comment]
Optimally effects themselves would deny something like this, so people don't need to put `iseffect()` in each thing that they fuck up. Doing it this way will lead to code bloat, and someone somewhere will forget to do this and break everything.

**Pull request closed without merging**
