### PR TITLE
Enforces Minimal Usage of Byond Verbs

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
Cobbytainer 2020

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by kachnov** [comment]
verbs should never be used 👍

**Comment by ExcessiveUseOfCobblestone** [comment]
@KorPhaeron @optimumtact @vuonojenmustaturska

**Comment by tgstation-server** [comment]
No

**Comment by MrStonedOne** [comment]
[3:02 PM] Kor: yeah I hate the AI clutter
[3:02 PM] Kor: and find it all confusing
[3:03 PM] Kor: I stopped playing AI when I came back and saw that

Action buttons are not a 1:1 replacement for verbs, verbs have a name, a label, a bit of text that tells you what each button does without having to hover. Action buttons do not. furthermore verbs can be typed, auto completed, etc. All features action buttons are lacking.

**Comment by KorPhaeron** [comment]
Action items for objects are still 100% better though, its hell to track what your stuff does otherwise

**Comment by MrStonedOne** [comment]
No they aren't.

A new player can tell what "Toggle helmet lights" does at first glance, they can't tell what an icon of a helmet does at first glance.

**Comment by optimumtact** [comment]
stop abusing the bots to close a pr, just ask someone, otherwise we'll have to fuck about with civil war

**Comment by ExcessiveUseOfCobblestone** [comment]
A lot of AI functionality is on both verbs and buttons so if the issue is specifically with AI then that can be addressed.

If this is enforced already (it is), I don't see the benefit in people wasting their time coding verbs only to then be told they should change it to action buttons anyways when we could just preemptively tell them to not code verbs unless they must.

@MrStonedOne you can change the icon to something better, like a light powerswitch or something that visually represents what the button actually does. It's only poorly visually represented because of the lack of spriting the button icons, not necessarily because there's some inherit flaw with the system (although that might be true as well in some other form).

**Pull request closed without merging**
