### PR TITLE
Fire and water particle effects for mobs (sick)

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Mobs on fire and wet mobs get cool particle effects

## Why It's Good For The Game

https://user-images.githubusercontent.com/82850673/230459326-184b5553-17db-49df-997f-8db4c87df601.mp4
fire particles (big fire)
small fire just reduces the spawn rate of particles to 20% of this

https://user-images.githubusercontent.com/82850673/230468680-b831e557-bb0a-4489-8aef-4fefdfc14e43.mp4
wet particles

sick

## Changelog

:cl:
add: Mobs on fire get particle effects (it looks sick)
add: Wet mobs get particle effects (it looks sick)
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
draft because i'm adding wet particles too i think that would be cool

**Comment by Edelor68** [comment]
Does it change based on the stage of fire? Or is it just for the max amount?

**Comment by ChungusGamer666** [comment]
> Does it change based on the stage of fire? Or is it just for the max amount?

it's always the same if you're on fire
i don't really plan to change it because i'm lazy

**Comment by ChungusGamer666** [comment]
nevermind, i'll make it change the spawn rate to be lower depending on the icon state

**Comment by ChungusGamer666** [comment]
yeah its done yippie

**Pull request merged**
