### PR TITLE
Attacking will break stealth/invisibility

### LINKED ISSUE #13303: Attacking with chameleon mutation doesn't break Invisibility
Doesn't make sense seeing how moving breaks it, but swinging a weapon/shooting doesn't.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes #13303

### CODE REVIEW

**Comment by Bluespace** [comment]
Please ensure using TK doesn't break invisibility, as you don't need to move to stab someone to death with your mind.

**Comment by Anonus** [comment]
Do it properly, ninja suits have a var checking if invisibility is on and this won't toggle that off.

**Comment by tkdrg** [comment]
Yeah just setting alpha to initial(alpha) every single attack animation is wasteful and bug prone. It would make more sense to deal with this in a generic yet specific way (for instance, adding an on_attack() hook to mutations if one doesn't exist already, and setting alpha to 255 on that).

**Comment by KorPhaeron** [comment]
I'll redo this eventually maybe then

**Pull request closed without merging**
