### PR TITLE
Removes delay from AddEmploymentContract

### PR DESCRIPTION
**Pull request by Cyberboss**
Github hates this file

### CODE REVIEW

**Comment by lordpidey** [comment]
The point of the delay is to allow post-creation effects to happen.  I remember without it, clowns had their non-clown name show up.  But that has since been refactored, so it might be fine.

Double check the following things:

Contracts still exist in the cabinet.
Contracts still buy back souls.
Contracts can be copied in a copier.

**Comment by Robustin** [comment]
Which is stupid because the cabinet itself fills missing records anyway when you open it.

**Comment by lordpidey** [comment]
It only does that upon first opening.

**Comment by Robustin** [comment]
From what I saw it happened with every AttackHand

**Comment by lordpidey** [comment]
Nope.

https://github.com/tgstation/tgstation/blob/master/code/modules/paperwork/filingcabinet.dm#L214

**Pull request merged**
