### PR TITLE
fireball starts at 8 tile range, increases 2 for every level

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
balance: fireball starts at 8 tile range, increases 2 for every level
/:cl:

shooting a fireball in a straight hallway is really op

### CODE REVIEW

**Comment by nemvar** [comment]
ided

**Comment by Qustinnus** [comment]
heded

**Comment by Dawson1917** [comment]
fireballs are the SRM-8 of wizard rounds

**Comment by Swagile** [comment]
fire ball is already dangerous to use, why nerf it?

for every 1 wizard that knows how to actually use it, time it correctly, and deactivate it when others get near, there are 9 wizards that instantly die to point blank fireball, hitting a wall next to them, or panicing as someone gets close and forgetting they had it activated

**Comment by wesoda25** [comment]
Everyone downvoting is upset that there is now some modicum of talent required to be a fireball wizard

**Comment by MMMiracles** [comment]
show us on the doll where the wizard fireballed you

**Comment by OverlyGeneric** [comment]
will the wand of fireballs lack this restriction or not?

then again, that may require you creating a separate projectile for the wand of fireballs.

**Comment by PKPenguin321** [comment]
Getting fireballed from down a hall is pretty lame, but this makes it a tad too easy to avoid fireballs by just moving away from them until the wizard goes off screen. I'd give it maybe 1.5x the range

**Comment by Shadowflame909** [comment]
Fireball is a meme diceroll in itself. The gimmick is that it sucks because it auto-homes to the person closes to you and completely ignores what direction you're pointing your spell in.

Therefore if there's a simple mob-like right behind you while shooting it. It'll Ohko you and even instant crit you/delimb you.

**Comment by Dorsisdwarf** [comment]
Really? When did it get changed from throwing?

**Comment by Shadowflame909** [comment]
I think that's the way its always been Dwarf.

It is cheap because of It-Auto homes to the person nearest to you. If there's no one close to you, then it'll shoot down the direction you're asking it to shoot down.

But if you take any damage from it yourself, you're as good as screwed.

**Comment by bigfatbananacyclops** [comment]
can you make the fireball upgrade raise the radius, that’ll make it better, you may want to change the wizard mob fireball too so people cant avoid them easily

**Comment by Tlaltecuhtli** [comment]
oh i misread range for radius
well have a range increase on spell level instead

**Comment by bigfatbananacyclops** [comment]
@tlaltecuhtli i actually meant range, im dumb

**Comment by Tlaltecuhtli** [comment]
good thing i misread it then it does range

**Comment by actioninja** [comment]
Fireball is such a ridiculously strong ability for so cheap that it's pretty much the sole reason why other less powerful but more interesting abilities never get bought.
This isn't even that heavy of a nerf.

**Comment by Narcissisko** [comment]
You mean you aren't worried about ei nath? lol

**Pull request merged**
