### PR TITLE
Makes the butcher cleaver a normal-sized item

### PR DESCRIPTION
**Pull request by ghost**
The butcher's cleaver is insanely robust because it can fix in your pockets whilst still doing 15 brute damage. In addition, due to this, you cannot cut bread or cake because you just slide it into the food. This fixes both of these problems.

Also makes the butcher's cleaver a subtype of kitchen knife and changes the file path in all related code.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Probably need to happen; you can't put kitchen knives in your pocket; these are much larger than kitchen knives and much more robust.

Also, once dismemberment goes through, this weapon will be even *more* powerful, so this is a good pre-emptive nerf.

**Comment by paprka** [comment]
Doesn't the hatchet fit in pockets as well

**Comment by Xhuis** [comment]
Yes, but generally from the sprite I imagine that as a sort of hand-sized thing. You could just slide it into your pocket handle-first. A butcher's cleaver is obviously not like this.

**Comment by paprka** [comment]
Hatchets are easier to find and do the same damage though

**Comment by Xhuis** [comment]
Mainly, it would make the lives of botanists harder because, from what I've seen, most botanists keep hatchets in their pockets. In addition, it does 12 damage rather than 15, and that does make a good difference, meaning it takes 2-3 more hits to crit.

Also, the butcher's cleaver was unable to cut things because it just fell into the cake/bread. Hatchets cannot cut and thus do not have this problem.

**Comment by paprka** [comment]
Nevermind then, I could have swore hatchets were 15.

**Comment by hornygranny** [comment]
@Xhuis the butcher's cleaver should just be a child of the kitchen knife, or not exist

**Comment by Xhuis** [comment]
I was going to make them a subtype but I was afraid it might break any instances in which the old path was used. I'll see what I can do though.

**Comment by hornygranny** [comment]
it's not a good idea
@Agouri you will never live this down

**Comment by Xhuis** [comment]
this merges for boxstation but not on metastation/ministation
because neither of these are ever used i am not spurred to fix it

**Pull request merged**
