### PR TITLE
Makes Syndicate Operative base look more evil

### PR DESCRIPTION
**Pull request by AarontheIdiot**
## About The Pull Request

 Replaces the indestructible riveted walls on the Syndicate Nuke Op base with indestructible plastitanium walls. Also replaces the windows with indestructible plastitanium windows.

## Why It's Good For The Game

This PR will make the Nuke op base look more evil and syndicatey, kinda like the lavaland base. But indestructible.

## Changelog
:cl:
tweak: Changed the walls in the Nuke Op base to look more evil.
/:cl:

### CODE REVIEW

**Comment by AarontheIdiot** [comment]
https://imgur.com/a/ZUw8euT here is an image if anybody wants to see it with their own eyeballs.

**Comment by wesoda25** [comment]
The moment I clicked that link was just amazing, I’d never seen as evil looking a structure before! 

But I can’t think of what we have rn off the top of my head, does this just make it darker (not that thats a bad thing).

**Comment by WJohn** [comment]
that's uh

not really a significant improvement at all

also, map merger, bucko

**Comment by AarontheIdiot** [comment]
fuck i forgot map merger

**Comment by AarontheIdiot** [comment]
all this PR did, by the way, was make the nukie base look more aesthetically evil

**Comment by ishitbyabullet** [comment]
Make a new wall. It looks like the shuttle and steel rain pod. Try recoloring the old walls or something.

**Pull request closed without merging**
