### PR TITLE
Armory fix + reorganization

### PR DESCRIPTION
**Pull request by pudl**
In #12263 @Steelpoint noticed that #12202 had caused some issues with the armory. As opposed to him including the fix in an otherwise unrelated PR, I've made this to fix those issues. Additionally, since we are free of autorifles, I didn't see the need to have Steelpoint's design minus the rifles, as it's a pretty ugly design anyway.

General fixes:
- Security again has 3 flashers
- Security again has 2 riot shotguns
- The armory again has a desk into the security equipment room.
- The bulletproof helmet and vest have returned.
- The useless Tac button has been removed from the warden's table.

Changes:
- The secway is now public to everyone.
- The contraband locker has two spawners inside of it, similarly to Metastation.
- The armory now has the important weapons in the center, ordered from left to right from most situational to least situational. 

As shown in the PR, the design is simply a slightly smaller version of the pre-autorifle armory, with the secway moved into security equipment, and the suiting up door removed, as I saw it to be pointless. On that matter, however, I wanted to hear other people's feedback: why readd the door when no suiting up in needed anymore? Is the warden being able to hand out equipment and have an actual level of interaction with security officers not a valuable tradeoff to the convenience of the shutters?

An issue raised by @RemieRichards in a private conversation we had was that the stairs into the armory would create an elevation inconsistency between the security office and the armory. When I offered the explanation of slanted flooring, she find that to be proper justification. What do you guys think?

At the requests of @Xhuis and @Miauw62  respectively, evidence storage has remained in tact and the windows into the armory are no longer shocked.

Merge conflicts are the result of Steelpoint's PR addressing these fixes, which is agreed to be inappropriate and needed in a separate PR.

Tiny note: My ign has changed to Quiltyquilty, so I removed my old name and put that in.

### CODE REVIEW

**Comment by Xhuis** [comment]
# \>another fucking armory update

**Comment by pudl** [comment]
@Xhuis Maybe your update shouldn't have had so many issues?

**Comment by Xhuis** [comment]
\>blames me for having issues
\>makes an entire other armory instead of fixing said issues

**Comment by pudl** [comment]
I fixed your issues, and I didn't make an entire other armory, I just reverted the original armory change that Steelpoint made in the first place. There was no reason for us to be using Steelpoint's design minus the autorifles, when everyone was fine with the old one.

**Comment by Niknakflak** [comment]
the stairs look nice but if it's "technically" going "up" into the armory, how is there a table to the other room at the same level.  This triggers me.

**Comment by RemieRichards** [comment]
@pudl SEE? @Niknakflak agrees with me!

**Comment by optimumtact** [comment]
those stairs look fucking retarded.

**Comment by optimumtact** [comment]
@Niknakflak the table would just be higher on side than on the other.

**Comment by pudl** [comment]
@optimumtact I put them there because the alternative of extending the caution tiles down looks ugly.

**Comment by PKPenguin321** [comment]
isn't this the original armory we had before meme rifles?
if so then it's fine, it's already been proven to work

**Comment by pudl** [comment]
@PKPenguin321 Yes, except the racks are now in a line instead of a 3x2 area, and the guns are better organized.

**Comment by Steelpoint** [comment]
The guns being too far forward makes them not only easier to steal but more likely to be destroyed in a explosion.

Also as Lumi will surly point out (if not already) the lack of a windoor+table on the right side makes getting into the armoury harder for antagonists or security.

**Comment by pudl** [comment]
They won't be damaged by C4, and being 2 tiles further forward doesn't make them easier to steal. And there is a windoor+table on the right side.

**Comment by Lumipharon** [comment]
windoor/desk to sec room is good for handing out a couple of things/breaking in.
The shutter is good for when shit hits the fan and you need all of sec geared to shit asap - handing out 8 guns and armour sets is slow and shitty, so is constantly opening warden office doors for sec officers.

Just have both.

Also what the fuck happened to the bulletproof armour?
That shit is very useful in nuke and gang.

**Comment by Zilenan91** [comment]
Quick question, by there being 2 spawners in the evidence locker "like there is on meta," does this mean that the armory will now spawn with two random ballistic weapons in there?

**Comment by pudl** [comment]
@Lumipharon I will add the door, and the bulletproof armor back. I didn't remove that, someone else did. And I'm not going to include balance changes in this pr, so no to lethals.

@Zilenan91 They spawn with 1 random engineering/other nice item like yellow gloves, and 1 random traitor weapon. This means the best gun that can appear is an FK-69.

**Comment by Zilenan91** [comment]
So by traitor weapons does this mean things like eswords, ebows, throwing stars, syndicate cigarettes... because traitor weapons is a bit of a nebulous way to describe the stuff they have.

**Comment by Supermichael777** [comment]
The armory windows should be shocked. It realy doesn't stop anyone but noobs who don't know how to throw and fits thematically with secure areas. like how there is no longer a win-door into an underused room made it TOO easy to break in. Now you need actual traitor gear or TOOLS instead of an air tank and a suit.  Honestly whenever anyone handing shit out its in a dufflebag carting it to the hot zone or over the wardens counter by special request. Letting people in just seems to make them atracted to the most stuatonaly worthless guns.(Lasers and disablers in nuke ops, shorties and the fucking ion rifle in blob. Never let anyone have free range of the armory)

**Comment by Lumipharon** [comment]
@Zilenan91 If it's the same as meta station, it's something like 40% chance of combat shotgun, 40% stechkin, 10% deagle, 10% mateba.

**Comment by pudl** [comment]
@Supermichael777 No.

**Comment by Zilenan91** [comment]
okay that's much better than I thought it was.

**Comment by Cookiesndip** [comment]
Didn't read the current comments, just going off the picture:

- Stairs look ugly.
- Guns might be too far forward.

Why not just move it to the original design? I.e. remove the rglass below it and shift the armory down one tile flat out? I mean, if the area where the stairs looks awkward, then just remove that space, it doesn't affect the rest of the design.

By the way, why can't we just go back to the original armory instead of redesign after redesign? Hell, go back to the original armory and add the shutters in conjunct with the desk. No one had a problem with it.

**Comment by pudl** [comment]
I'm going to be changing the stairs. Everything else you said is either wrong or missing the point.

**Comment by optimumtact** [comment]
Looks good to me :+1:

**Comment by pudl** [comment]
@optimumtact Thanks, your approval is appreciated.

**Comment by Lumipharon** [comment]
Why was it closed?

**Comment by Steelpoint** [comment]
If I had to guess, merge conflicts.

**Pull request closed without merging**
