### PR TITLE
Fixes runtimes related to blowing up 25 vending machines at once

### PR DESCRIPTION
**Pull request by Mervill**
[log before this pr](http://pastebin.com/vD8NhMT4)

[log after this pr](http://pastebin.com/ehTUJBuM)

More correctly, this is an issue where `/obj/item/throw_impact(atom/A)` can receive a null atom in some instances, for example during a catastrophic vending-machine based explosion

### CODE REVIEW

**Comment by Mervill** [comment]
Also, this runtime cropped up after the fix
```
runtime error:
[10:39:04]Cannot execute null.GetAtmosAdjacentTurfs().
[10:39:04]proc name: spread smoke (/obj/effect/particle_effect/smoke/proc/spread_smoke)
[10:39:04]  source file: effects_smoke.dm,77
[10:39:04]  usr: null
[10:39:04]  src: the smoke (/obj/effect/particle_effect/smoke)
[10:39:04]  src.loc: null
[10:39:04]  call stack:
[10:39:04]the smoke (/obj/effect/particle_effect/smoke): spread smoke()
[10:39:04]the smoke (/obj/effect/particle_effect/smoke): spread smoke()
```

**Comment by Supermichael777** [comment]
Looks like smoke in null-space

**Comment by WJohn** [comment]
how do people find these?

**Comment by optimumtact** [comment]
The runtime logs are publicly available @WJohn 

@Mervill this is okay, although when I spoke to mso about it he reckoned it woudl be better to clean up the throwing datum itself when the object is deleted/destroyed.

Also I think you should probably check !qdeleted(A) as well

**Comment by Mervill** [comment]
Yeah I figured there was a more systemic problem but this seemed like the easy way out

**Pull request merged**
