### PR TITLE
Updates Prima and Omni gang tags.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Better, probably.
sanic
overwatch

### CODE REVIEW

**Comment by SconesC** [comment]
no more OMNI OWNS YOU

oh well i like the new ones

**Comment by WJohn** [comment]
:+1:

**Comment by Xhuis** [comment]
Omni seems too neat for something a gang would spray on the wall. Prima's fine though.

**Comment by PKPenguin321** [comment]
rip omni owns you

**Pull request merged**
