### PR TITLE
Makes the Wedding Dress a suit

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

Title. Swaps the Wedding Dress into a suit slot.

## Why It's Good For The Game

The original wedding dress didn't hide the shoes. Also (not including the shoe hiding), the ability to have the Wedding Dress as an exosuit can lead to comedic oppertunities.

## Changelog

:cl:
expansion: The Wedding Dress has been moved to a suit slot.
fix: The wedding dress no longer shows the shoes.
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
oh
joys

**Comment by francinum** [comment]
From a visual stacking perspective this makes things a lot cleaner.

**Review by Twaticus — APPROVED** [review]

**Comment by thestubborn** [comment]
:)

aaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by thestubborn** [comment]
i'm too lazy to fix this

**Pull request closed without merging**
