### PR TITLE
Make round ID nullable in bans and tickets

### LINKED ISSUE #61984: Round ID being null causes you to be unable to ban any players.
## Testmerges:

#61917: 'Rad collectors gone, tesla coils to generate power' by Ghilker at commit e1951df4b7

## Reproduction:

You can't ban any players if the round ID is null for a round

Round ID can be null if the database fails to connect when the server is created.

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Make round ID nullable in bans and tickets. Fixes #61984 

## Changelog

:cl:
fix: Fixed a bug where bans could not be applied if the database connection was not immediately established, even after a re-establish.
server: Updated database schema to allow for null round IDs in bans and tickets.
/:cl:

### CODE REVIEW

**Comment by MrStonedOne** [comment]
should do the rest too. =P

round id is in death, connection_log, legacy_population, library, citation, messages (notes and co), and twice in player.

**Comment by Mothblocks** [comment]
That's what I said before 😄 

Sure, I'll get to it

**Comment by MrStonedOne** [comment]
ya, and what i said was i was only gonna change the key ones needed for administrative function on live and wait until somebody made a pr to change over the rest =P

**Comment by Mothblocks** [comment]
yeah yeaaaah im just having some fun

**Review by Jordie0608 — DISMISSED** [review]
Update the prefixed schema too (we'll kill it one day), you missed one in `admin_log` table and increment the DB_MINOR_VERSION define https://github.com/tgstation/tgstation/blob/master/code/__DEFINES/subsystems.dm#L23

**Review by Jordie0608 — CHANGES_REQUESTED** [review]
You missed `admin_log` table in the `tgstation_schema.sql` again =P
Everything else is all good.

**Review by Jordie0608 — APPROVED** [review]

**Pull request merged**
