### PR TITLE
Adds more syndie-kits! 3 of them to be exact.

### PR DESCRIPTION
**Pull request by Singul0**
## About The Pull Request
Adds 3 syndie-kits, two are in the special pool and the other in the tactical pool. Below are the kits content:

Tactical:
1. Revolutionary (28TC), which contains:
- Hypnotic Flash (7TC)
- Radioactive Microlaser (3TC)
- LSD pills (~1TC)
- Sleepypen (4TC)
- Nagant Revolver (13TC, Comparable to 357. Revolvers (far harder to get ammo though))
- Megaphone
- Revolutionary bedsheet
- Russian warcoat
- Ushanka
- Contraband poster boxes
image

Special:
2. Prophunt (29TC), which contains:
- Chameleon Projector (7TC)
- Doorjack (3TC)
- Stealth Implant (8TC)
- Makarov (7TC)
- Thermal Glasses (4TC)
image

3. Sam Fisher (32TC), which contains:
- Spec Ops suit (~6TC comparable to infiltrator suit)
- Night Vision Googles (~3TC)
- Assault belt with assorted items (18TC, refer to image)
- Combat Gloves + Krav Maga (5TC)
image
## Why It's Good For The Game
I use syndie-kits a lot whenever I roll traitor, always found them to be a quick and easy way to figure out what i'm going to do for the traitor round. but there's only so much kits that eventually you'd get bored of getting the same old kits. This PR fixes that! adds 3 different syndie-kits each with their own little unique gimmick that weren't present in the kits before.

 more kits = more gimmicks = more fun and engaging gameplay

The Revolutionary kit is centered around it being a budget revolutionary, you're given a hypnoflash and various other gadgets to help you get your own small army to do your bidding, also comes with a drippy (do anyone still use that word anymore?) russian armor and revolver for self defense.

Prophunt kit is self-explanatory, be the little gremlin you are, stealing and sneaking your way through a greentext.

Meanwhile the Sam Fisher kit essentially allows you to be an spec ops agent, getting a myriad of gear that's designed for sabotage and quick assasinations. comes with a cool armor set
## Changelog
:cl:
add: Adds 3 new kits into the syndie-kit spawn pool, 2 for special and another for tactical
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
Haven't rolled tot in eternity cuz I have been maining miner, so I don't know what certain new items are, but

That mini egun with the green bar on top and what looks like a silencer, I think I saw the pr for that but I don't remember what it was. What is that gun? (Not the ballistic ops gun)

**Comment by EuclidianGeometer** [comment]
the sam fisher kit should get the silenced gun that only works to blow up lightbulbs, imo.

**Comment by Singul0** [comment]
> the sam fisher kit should get the silenced gun that only works to blow up lightbulbs, imo.
It already does

**Comment by Admiral-Gigaton** [comment]
> > the sam fisher kit should get the silenced gun that only works to blow up lightbulbs, imo.
> 
> It already does. Actually the reason why I made the PR, since I figured it should have been in a syndiekit instead of being locked away in an obscure mechanic and isnt even guranteed to spawnn

yeah, so instead, its locked behind that mechanic, and now a second, less obscure, but even more unlikely chance to spawn
(joke, very cool PR)

**Comment by Singul0** [comment]
> yeah, so instead, its locked behind that mechanic, and now a second, less obscure, but even more unlikely chance in this second mechanic (joke, very cool PR)

You got me, at least it's now has 2 sources, both from obscure mechanics. That's doubled!

**Comment by Admiral-Gigaton** [comment]
I feel like EMP doesn't really fit the stealthy vibe, maybe chameleon projector, or some kind of martial art book/gloves? (Advanced combat gloves with Krav maga?) Something one could use to RP interrogation and silent takedown

Also, normal combat suit would probably work better, because then you don't have bright ass white and red rings on your hands and can he easily spotted while you try to assassinate the captain's weird ass dog, renault

**Comment by another-expler** [comment]
I think we need two or one magazines for makarov in prophunt pack. And thia pack is too ordinal for special kit category

**Comment by another-expler** [comment]
New idea to replace champrojector.
Experemental chameleon projector. Work like an ordinaty one but  you can now move freely and act with spare hand, inclucluding shooting. When you in prop form you have big human hitbox, or i dunno

**Comment by bigfatbananacyclops** [comment]
The kits are great but i don't understand what a single LSD pill might have of use. Even if its for rp purposes.

**Comment by Singul0** [comment]
> The kits are great but i don't understand what a single LSD pill might have of use. Even if its for rp purposes. The revolutionary kit could probably use some different tools like mindslave implant.

the LSD-pills can be used to easily brainwash people, since you need them to be high or asleep to flash and hypno them. Hell. you can crush the pills up and use it in conjuction with the sleepy pen

**Comment by Jezzared** [comment]
> The kits are great but i don't understand what a single LSD pill might have of use. Even if its for rp purposes. The revolutionary kit could probably use some different tools like mindslave implant.

it says LSD pills as in plural. Plus, it's just another way to put people into a state for hypnosis, like the microlaser and the sleepy pen. In this case, druggy.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
