### PR TITLE
Extensively improves various sprites.

### PR DESCRIPTION
**Pull request by WJohn**
This is gonna be fun, isn't it?
Folders

Hand labeler, clipboard, paper bins, various papers.

Pens and energy dagger.

Cabinets

Pamphlet, newspaper, crumpled papers, paper airplane, various documents.

EDIT: V2

V1
http://i.imgur.com/DXj26yC.png

:cl: WJohnston
imageadd: Improved/resprited Paper, stamps, folders, small fires, pens, energy daggers, cabinets, newspaper and other bureaucracy related items.
/:cl:

### CODE REVIEW

**Comment by Niknakflak** [comment]
Folders have wayyy to dark of a border

**Comment by PKPenguin321** [comment]
I think they look fine. Paper bins look like they are too thin on the sides however

**Comment by ChangelingRain** [comment]
Wait, how do you activate the energy dagger if the clicky bit is where the blade comes out?

**Comment by WJohn** [comment]
I mean they're bins. Why would they need thick walls? Also no idea how with the dagger. Maybe the hook thingie?

**Comment by PKPenguin321** [comment]
well because at the moment they're indistinguishable from an outline

**Comment by WJohn** [comment]
Welcome to 3/4th.

**Comment by Militaires** [comment]
sexy

**Comment by Cheridan** [comment]
saturation on the folders is too high, the existing sprite shade is more like dyed cardboard. this is more like colored plastic

**Comment by AdamElTablawy** [comment]
ugh

UGH

JESUS CHRIST WHAT IS THAT EPEN THE ENERGY BLADE LOOKS LIKE THE ESWORD EQUIVALENT OF A MICROPENIS

TOO THIN

**Comment by Iamgoofball** [comment]
but it's literally the esword equivalent of a micropenis

**Comment by nullbear** [comment]
> Wait, how do you activate the energy dagger if the clicky bit is where the blade comes out?

Only traitors know how to activate it without losing their thumbs.

**Comment by pubby** [comment]
The stamps look an awful lot like joysticks. Here's a quick tweak:

**Comment by HankMoodyExperience** [comment]
just steal goonsprites while you're at it

**Comment by WJohn** [comment]
Alright, I'll edit the stamps, and I'll see if there's anything I can do about the folder. Note that most of these literally cannot get less saturation due to the color palette I'm using.

**Comment by WJohn** [comment]
There, how's this?

**Comment by Militaires** [comment]
make sure to update g a n g pens

**Comment by TechnoAlchemisto** [comment]
the coloured handles are what is making them look like joysticks

**Comment by WJohn** [comment]
The handles were already colored, and as vividly as these.

**Comment by TechnoAlchemisto** [comment]
weird

**Comment by Cheridan** [comment]
> Note that most of these literally cannot get less saturation due to the color palette I'm using.

gee its almost like limiting yourself to certain colors is fucking retarded and leads to bad sprites

**Comment by WJohn** [comment]
This is why I wanted ausops to help me with the palette.

**Comment by pudl** [comment]
This looks like goon's sprites but worse, some of these aren't "improvements" as much as they are resprites to fit your idea of what the game should look like. Leave the cabinets, folders and paper bins alone.

**Comment by WJohn** [comment]
The art director has a vision for what the game should look like and tries to change the inconsistent art style created by dozens upon dozens of people who have little-to-no experience spriting by making his own stuff?

I know my sprites aren't the best by any stretch of the imagination, ausops is far better than me at this but he's not around to help me with this kind of stuff, and there's basically no one else at the minute.

**Comment by pudl** [comment]
I prefer the inconsistent art style to this shit

**Comment by PKPenguin321** [comment]
Pudl u are wrong

**Comment by Supermichael777** [comment]
Improve walls doors and floors next please

also fuck off pudl if you want it to look different produce better sprites.

**Comment by WJohn** [comment]
Doors and walls are likely not going to be improved for a long, long time. There's lots to do first before I get to those.

**Comment by Supermichael777** [comment]
doors are okay just a bit flat tbh the two main types of walls are my main complaint.

**Comment by PKPenguin321** [comment]
walls need to be plain because theyre like the most common shit ever and take up a lot of your screen at almost all times, too much detail on them makes them an eyesore

**Comment by nullbear** [comment]
walls will be hard to improve for three reasons:

Nostalgia. No matter what he does to them, it will be met with opposition. And it'll be extremely hard to find out what needs improving because 'no matter what, it'll just be wrong."

4 Directional Wall-Item states. Should walls be made so that they match the view angle? If they are, then they would technically hide stuff from the player. Specifically stuff like apc's and wall-mounted objects.

Smoothwall code would need to be updated. And probably add a completely new set of logic for non-top-down walls.

**Comment by WJohn** [comment]
Smoothing should actually function decently with new 3/4th walls, for the most part. It's designed to allow any random, albeit repetitive texture on the "inside" part. Still, there will need to be code in place to hide the top of the walls when you're above them or to their side. xxalpha has a working prototype but he's being limited some old line of sight bugs that come with byond.

**Comment by RemieRichards** [comment]
Two high walls really aren't happening WJ.

**Pull request merged**
