### PR TITLE
Remove botany "mines" trait as it is sadly too powerful

### PR DESCRIPTION
**Pull request by optimumtact**
Also secondary concern but it's explosions can cause admin log spam

### CODE REVIEW

**Comment by ma44** [comment]
How to counter: walk around plant

**Comment by ExcessiveUseOfCobblestone** [comment]
http://pastebin.com/FZFxzKnr

**Comment by ma44** [comment]
:(

**Comment by ExcessiveUseOfCobblestone** [comment]
It would have been alright had the gene manipulator not been a thing.

**Comment by kevinz000** [comment]
@optimumtact best coder :D

**Comment by Chnkr** [comment]
Solution: don't log these explosions.

**Comment by XDTM** [comment]
Could someone tell me what happened with those? I think i'm missing a fun story here

**Comment by MisterTikva** [comment]
> Could someone tell me what happened with those? I think i'm missing a fun story here

Looks like somebody dumped a bunch of potassium-water plant mines and somebody stepped on them

**Comment by Supermichael777** [comment]
whew

every tile in escape hall gets made a garden and then someone puts down combustible lemons with the tomato squash gene.

**Comment by PKPenguin321** [comment]
this didn't fix the bomb spam issue, it can still be done with tomatos

**Comment by optimumtact** [comment]
so fix it

**Pull request merged**
