### PR TITLE
Removes grey tide barsign

### PR DESCRIPTION
**Pull request by ghost**
Hey

This is awful

Don't do it again

Thanks in advance

### CODE REVIEW

**Comment by Mandurrrh** [comment]
Why

**Comment by Anonus** [comment]
Grey tide bar wide

**Comment by GunHog** [comment]
Pointless and biased change :-1:

**Comment by Iamgoofball** [comment]
:-1: how is it awful

**Comment by paprka** [comment]
"biased against rule breaking"

The fact that this got in is another example our maintainers simply do not give a fuck

**Comment by Razharas** [comment]
I dont understand what is bad in a bar sign

**Comment by RemieRichards** [comment]
Yet another pointless change from paprika.
Yet another maintainer-bashing, from paprika.
*sigh* can the world get any darker?

**Comment by RemieRichards** [comment]
Requested Lock.

**Comment by Cheridan** [comment]
I think he has a point. Greytiding is banned behavior, so why reference it like this in-game, glorifying it?

**Pull request merged**
