### PR TITLE
[no gbp] removes signpost from icebox

### LINKED ISSUE #83271: Infinite random teleport bug with raptors and signposts
## Issue Summary
While riding a raptor if you interact with a signpost and move in a direction it will teleport you back to signpost you used to teleport randomly.

## Round ID:
[229002](https://scrubby.melonmesa.com/round/229002)

## Reproduction:

https://github.com/tgstation/tgstation/assets/154919526/21855c61-0b40-47d7-8d70-60bff68d93da

### PR DESCRIPTION
**Pull request by Ben10Omintrix**
## About The Pull Request

Closes #83271

 i didnt know this item existed in the game but seems it got mapped in by mistake and can teleport u around

## Why It's Good For The Game

 fix silly mistake

## Changelog

:cl:
remove: removes signpost from icebox 
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
we really need to add a "don't map this in" flag we can unit test for

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Use `no_effect_signpost` (because OOP is a meme) 

image

**Comment by Iamgoofball** [comment]
WHY DOES A SIGNPOST TELEPORT YOU

I THOUGHT IT WAS A SIGN, THATS MY BAD

**Comment by newfren** [comment]
I believe this signpost is used in the clown planet ruin (and another spaceruin?) to teleport you back to the station.

**Pull request merged**
