### PR TITLE
Move disk verification into skillchip

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
tweak: The knowledge of nuclear disk serial numbers is now stored as a
skillchip installed in captains, death squad members and nuclear
operatives.
/:cl:

Captain gone braindead, lost the pinpointer, and you need to work out if
a given disk is legitimate? Just cut out the skillchip from their brain,
and install it for knowledge of that horrendously long serial number.

---

Moving the TRAIT_DISK_VERIFIFER from an innate mind trait from the job,
to a skillchip allows for some more in-game methods to gaining access to
disk verification, including the chameleon skillship.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
how do you cut the skillchip from the brain??

**Comment by brotherbeyondd** [comment]
scalpel on brain

**Comment by kopoba** [comment]
Nuke ops have Chameleon Skillchip will it conflict with chip from this PR?

**Comment by coiax** [comment]
You should still be able to use chameleon skillchips as well.

**Comment by Pugie** [comment]
I thought it was impossible to salvage a skillchip intact since their implementation? Once they're in brain they stay there or are destroyed upon removal or did that change?

**Comment by coiax** [comment]
> 
> 
> I thought it was impossible to salvage a skillchip intact since their implementation? Once they're in brain they stay there or are destroyed upon removal or did that change?

No, skillchips have always been removable with a scalpel applied to the brain. The library skillstation can also remove them.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
