### PR TITLE
Minor meta mapping fixes

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Fixes a disconnected APC on the metastation AI satellite
also fixes a very minor area error.
Rolling the var cleanup into the other PR.

## Why It's Good For The Game

fixes mapping errors

## Changelog
:cl:
fix: Fixed a disconnected APC on the meta map satellite.
add: Added a scrubber to the meta engineering lobby.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
can you put a scrubber in the engi hall? it has no scrubbers

**Comment by actioninja** [comment]
Huh, it really doesn't.

**Comment by FloranOtten** [comment]
Seeing as the map diff bot is still gone, can pictures be posted?

**Comment by actioninja** [comment]
No pics for any change but the scrubber. They aren't visible.
image

**Comment by FloranOtten** [comment]
Mostly interested in which APC you connected? There's one in the metastation sat that's supposed to be disconntected roundstart.

**Comment by actioninja** [comment]
Why should it be disconnected roundstart? That seems like an error.

**Comment by SpaceManiac** [comment]
The APC being disconnected is a mistake, the intent is that the cable between the station and the satellite should be missing a link, which it is.

Any note on whether the SMES is supposed to not be connected to anything? I don't know if it was like that before smart-cabling.

**Comment by actioninja** [comment]
> The APC being disconnected is a mistake, the intent is that the cable between the station and the satellite should be missing a link, which it is.
> 
> Any note on whether the SMES is supposed to not be connected to anything? I don't know if it was like that before smart-cabling.

I believe it was? It's kind of an odd choice but I think that's actually how it was before. I'd have to ask wjohn to be sure, the mapping side wasn't really my doing.

**Review by SpaceManiac — APPROVED** [review]
Alright, looks fine to me in that case

**Pull request merged**
