### PR TITLE
Revival surgery is no longer an advanced surgery

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR makes the revival surgery a basic surgery that's available at roundstart. You no longer need an operating computer or the like to perform it.

## Why It's Good For The Game

The removal of defib timers (which was a great change) kind of made the revival surgery obsolete/niche, only really being useful for plasmamen, abductors, and reviving people without a defib. Unfortunately, you needed both a defib (or a taser (haha, no) or a stun baton) and an operating computer to perform it, and if you have access to an operating computer, you probably also have access to a normal defib.

This PR gives revival surgery an additional niche of being a "in the field" way of reviving people if you don't have access to a defib or an operating computer, especially if you're a ghost role.

## Changelog
:cl: ATHATH
balance: The revival surgery is now a basic surgery instead of an advanced one, so you can now perform it without needing an operating computer (or the Advanced Surgery tech).
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
nice. i was wondering what the point of this surgery was

**Comment by ExcessiveUseOfCobblestone** [comment]
I think I made it so the advanced type doesn't even need to exist anymore lol, should move it out to the normal surgeries in the file tree.

**Comment by ATH1909** [comment]
> I think I made it so the advanced type doesn't even need to exist anymore lol, should move it out to the normal surgeries in the file tree.

I would, but I don't know how to change which folder the file's in.

**Comment by Tharcoonvagh** [comment]
>ghost role
Do they have access to either a stun baton or a defib?
Dont think so

**Comment by ArcaneDefence** [comment]
This allows me to make a genuine attempt to revive someone with an epi-pen, a bedsheet, a shard of glass, a screwdriver, wirecutters, a hatchet, a stun prod, and a glass of liquor. Finally lets me break away from the oppression of defibs. I like it.

**Comment by ATH1909** [comment]
> > ghost role
> > Do they have access to either a stun baton or a defib?
> > Dont think so

They have access to cattleprods, which count, IIRC.

**Comment by Tlaltecuhtli** [comment]
when the officer beats a man to death and then uses the same baton to resurrect him

**Comment by evilcyborgmrt** [comment]
Still think we should rename it to surgical revivification. Cause it sounds cooler

**Comment by improvedname** [comment]
Lifestatis beds freeze the defib timers tho

**Comment by ATH1909** [comment]
> Lifestatis beds freeze the defib timers tho

Defib timers got completely removed.

**Comment by ExcessiveUseOfCobblestone** [comment]
pull it out of the advanced folder and ill merge

**Comment by Dennok** [comment]
> > Lifestatis beds freeze the defib timers tho
> 
> Defib timers got completely removed.

But organs get damage over time, so we have another border.
That can be bypasset by organs replacement.

**Comment by ATH1909** [comment]
Thanks, spooky.

**Comment by ExcessiveUseOfCobblestone** [comment]
force them to leave their webbit safezone!!!!

**Pull request merged**
