### PR TITLE
Fixes ore vents floating after a tendril collapses nearby.

### LINKED ISSUE #84463: Ore vents resist chasming, but their boulders don't
Reporting client version: 515.1640

## Issue Summary
If you can somehow get an orevent to be close enough to a tendril and it collapses, then the vent becomes un-viale, albeit fully functional, if chasm'd, since the boulders just drop down instantly.

## Round ID:
[231335](https://scrubby.melonmesa.com/round/231335)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:
Sink the ground under a vent:
image

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Ore vents now provide a trait to the turf they spawn on, TRAIT_NO_TERRAFORM, which does exactly what it says on the tin, preventing the turf from being able to change into something else, like a chasm. Ore vents already have `move_resist = MOVE_FORCE_EXTREMELY_STRONG`, so they shouldn't be movable by any other means anyway, resulting in them being stuck in the turf that they spawned without admin tomfoolery.
image

## Why It's Good For The Game

Fixes #84463. Reasonably, too, we'll one day have other uses for something that needs to avoid the turf changing on it as well such as this.

I also sorted the turf traits because they were starting to get non-alphabetical and I know that'll drive someone crazy if I don't fix that while it's still early.

## Changelog

:cl:
fix: Ore vents that are caught in the cross-fire of a lavaland tendril collapsing will now spare the ore vent and it's associated turf.
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
Question, how do we get to the turf now?

From the screenshot there is no way to get to the turf without falling in, it's just floating in mid sir.

Maybe make all connected turfs leading to the ore vent chasm proof so there is a path to the vent?

**Comment by projectkepler-ru** [comment]
> Question, how do we get to the vent now?
> 
> From the screenshot there is no way to get to the turf without falling in, the ore vent is just floating in mid air.
> 
> Maybe make all connected turfs leading to the ore vent chasm proof so there is a path to it?

can't you metal rod over the chasm or RCD it?

**Comment by SyncIt21** [comment]
> can't you metal rod over the chasm or RCD it?

Yes you can, but not all miners carry an RCD on them, waiting till you get your hands on one can be a problem when the vent is somewhere deep in lavaland. Also an ore vent floating in space in general looks weird

**Comment by GPeckman** [comment]
> Yes you can, but not all miners carry an RCD on them, waiting till you get your hands on one can be a problem when the vent is somewhere deep in lavaland. Also an ore vent floating in space in general looks weird

You can throw iron ore onto lava to smelt it into sheets, then drag the (now burning) sheets out of lava and extinguish them.

**Comment by SyncIt21** [comment]
> You can throw iron ore onto lava to smelt it into sheets, then drag the (now burning) sheets out of lava and extinguish them.

No more improvised solutions please. I just want realistic behaviour like having a tendril not even spawn near an ore vent and thus preventing this situation from ever happening

**Pull request merged**
