### PR TITLE
Does what goof says in the solution to a few OP chems

### LINKED ISSUE #8787: You can scan any reagent passed down from human meat.
This includes any unobtainable reagents, such as the new reviver implant nanites that are OP as shit. Anyone who does this effectively becomes unkillable.

Steps to reproduce:
1. Inject chem into human
2. Gib human with gibber
3. Get odysseus mech
4. Scan meat
5. Replicate OP chems

### PR DESCRIPTION
**Pull request by Jalleo**
Fixes #8787
It actually works this time because git?
Can someone please tell me how to fix my commits they are a bit fucked.

Edit: added a few chems more chems to the blacklist: all blob reagents, gluttonytoxin, nanomachines, xenomicrobes and romerol.
Admins can still change the var for each reagent in game if they want to let someone replicate one of these chems.

If anyone wants any other OP chems from being replicated in the odysseus state them now or forever store your salt.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:-1: for all these except adminordrazine

**Comment by optimumtact** [comment]
This will be merged because the original reagent creators never intended you to be able to synthesize these - they're only created because we had no status effects system before.

**Comment by PKPenguin321** [comment]
i dont think it even matters for the gluttony, xenomicrobe, and nanomachines ones anyways

**Comment by optimumtact** [comment]
Then why are you upset?

**Comment by PKPenguin321** [comment]
im not really i just think it's lame

what's the downside for being able to synthesize blob chems just curious

**Comment by Jalleo** [comment]
It has no benefits. And I dont think @Iamgoofball wanted people to synth them.

**Comment by PKPenguin321** [comment]
i thought @ChangelingRain was our blob guy

**Comment by Iamgoofball** [comment]
i coded chemblob before, they weren't originally actually injected into people

they are not supposed to be obtainable

**Comment by PKPenguin321** [comment]
sure but it's a blob round anyways so it's not like the crew is going to be using their blob chem based deathmixes on each other

**Comment by Iamgoofball** [comment]
Some random chem spawn shit uses can_synth, so disabling that prevents it from showing up outside of the intended locat

**Comment by Jalleo** [comment]
@PKPenguin321 event blob.

**Comment by XDTM** [comment]
Can we keep the nanomachines synthable? They're hard enough to get in xenobio, and no more lethal than the more easily made black slime toxin

**Comment by ChangelingRain** [comment]
Blob chems are actually just an abstraction for a bunch of blob mechanics and absolutely shouldn't be obtainable.

**Comment by Jalleo** [comment]
@XDTM there is still bees. Which I am leaving because its broken and I dunno who will fix it.

**Pull request merged**
