### PR TITLE
Adds some more moth wings & antennae

### PR DESCRIPTION
**Pull request by redguy999**
## About The Pull Request
Ports some sprites from fulpstation. Credit to PapaporoPaprito for the original sprites.

Untitled3
Untitled4
Untitled
Untitled2

## Why It's Good For The Game
Cause why not add a few more moth icons?

## Changelog

:cl: PapaporoPaprito's sprites
add: ports some moth wings & antennae from fulp (credit to PapaporoPaprito for the original icons)
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
Show pictures of moths with these wings

**Comment by theta006** [comment]
all moths are evil we need to stop giving into this madness

**Comment by optimumtact** [comment]
>Cause why not add a few more moth icons?

because they cost bandwidth and rsc space?

**Comment by thgvr** [comment]
modsuits and other prs have a ton more sprites, this is less than 10kb

**Comment by optimumtact** [comment]
they also do things of value

**Comment by StoneMason** [comment]
You should probably credit that this is a port and the original artist for these wings is PapaporoPaprito.

**Comment by tralezab** [comment]
No credit, for shame....

**Comment by redguy999** [comment]
> You should probably credit that this is a port and the original artist for these wings is PapaporoPaprito.

Ah, thanks, I knew these were from fulp but I couldn’t figure out who the original creator.

**Comment by redguy999** [comment]
Credit has been given to the original creator.
I’ll get the pictures up here once I can get on my laptop, which should be in 4-5 hours.

**Comment by redguy999** [comment]
Actually I have one (albeit small and blurry) picture I can show of one of them.
BFBD1385-8687-4D1F-BB05-AAE316536947

**Comment by Imaginos16** [comment]
> Actually I have one (albeit small and blurry) picture I can show of one of them. BFBD1385-8687-4D1F-BB05-AAE316536947

If you could run the server privately, take a few captures with a snipping tool and edit that into the PR body, that would be good enough for an approval. We just need to be sure it works in game.

**Comment by LemonInTheDark** [comment]
I really wish you'd justify this further, since there are actually reasons to not just add more wing styles and such

**Comment by GuillaumePrata** [comment]
When I offered to port these wings to TG a long time ago the artist said they wanted it to stay as a Fulp exclusive thing.
I don't know if they still think like this or how important that would be for the Spritainers, just wanted to bring it up since credit wasn't given at the start.

**Comment by redguy999** [comment]
@Mothblocks 
This good?
image

**Comment by redguy999** [comment]
> When I offered to port these wings to TG a long time ago the artist said they wanted it to stay as a Fulp exclusive thing. I don't know if they still think like this or how important that would be for the Spritainers, just wanted to bring it up since credit wasn't given at the start.

If this is still true, I'm fine if you all close the PR since this wasn't hard to make.

**Comment by LemonInTheDark** [comment]
Well go ask them about it

**Comment by SmArtKar** [comment]
> When I offered to port these wings to TG a long time ago the artist said they wanted it to stay as a Fulp exclusive thing. I don't know if they still think like this or how important that would be for the Spritainers, just wanted to bring it up since credit wasn't given at the start.

from legal point of view we can do whatever we want regardless of their opinion

**Comment by LemonInTheDark** [comment]
That's nice

**Comment by Paprito** [comment]
Original artist here, go ahead and use em, other servers already use them so they’re not exclusive in any way at this point anyways.

**Comment by optimumtact** [comment]
> Original artist here, go ahead and use em, other servers already use them so they’re not exclusive in any way at this point anyways.

Thank you very much.

**Comment by Mothblocks** [comment]
@redguy999 Can you put that in the PR body as well?

It'd be *perfect* if you used the prefs menu preview to show the moths at all sides, by the way.

**Comment by redguy999** [comment]
@Mothblocks is it good now?

**Review by Mothblocks — APPROVED** [review]
Yeah, perfect. Art lead domain now.

**Pull request merged**
