### PR TITLE
Changes eye blur to use byond 512 filters

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Blurry eyes now actually blur instead of an overlay.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Credit goes to @FlattestGuitar for the code.

Cool pic

https://img.spaceball.cf/HyB9rYbuF2.mp4

### CODE REVIEW

**Comment by deathride58** [comment]
It might be a good idea to make the effect scale depending on how much eyeblur you actually have, like I've done over at Citadel https://github.com/Citadel-Station-13/Citadel-Station-13/pull/7727
We had to deal with quite a lot of screeching before we made the effect scale, since one single lethal laser shot meant your view was equivalent to that of someone who just lost their glasses

**Comment by yoyobatty** [comment]
I'll look into that actually, thanks for the response.

**Comment by zxaber** [comment]
This replaces the flour-covering-your-screen effect, right?
If so, a good change.

**Comment by yoyobatty** [comment]
Yeep

**Comment by actioninja** [comment]
Is there any way to apply this only to certain sections of the screen?
You could potentially turn this into a nearsighted/farsighted replacement as well. Or make more intense of eye blurs blur more the further away, etc.

**Comment by anconfuzedrock** [comment]
fuck, now I'm going to have to care when someone jizzes all over my screen, which is a good thing.

**Comment by yoyobatty** [comment]
Possibly with adding a filter to old overlay or some vignette? I'll try it.

**Comment by zamolxius** [comment]
can you make nearsighted people have this without glasses? would be cool

**Comment by deathride58** [comment]
@actioninja Sadly, 512 doesn't offer a way to apply the filters only to specific regions of a planemaster, as there's currently no way to apply masking as a filter. The effect is plausible in 512 with clever use of color matrices, but it'd require every single sprite in the game to only have one single color channel. If BYOND supported the ability to define custom HLSL shaders, then it'd be pretty easy to do in the context of SS13

**Comment by SpaceManiac** [comment]
Cool feature. I noticed in your video that you manually proccall after editing the `eye_blurry` variable. You can set this up to happen automatically; check out other types with `vv_edit_var` overrides.

**Comment by optimumtact** [comment]
This needs a test merge

**Pull request merged**
