### PR TITLE
Saline-Glucose IV drip blood replacement.

### PR DESCRIPTION
**Pull request by lordpidey**
This adds the ability to use an IV drip of saline glucose to treat bloodloss.

It is more effective the lower the patients blood level, so it is bad for topping off, but good for treating critical patients.

It is never as effective as actual blood though.

It also can only be done by injection, so either stand there with a syringe, or use the IV drip, because pills won't cut it.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

**Comment by WJohn** [comment]
Neat :+1:

**Comment by Supermichael777** [comment]
new meta cut in 50 percent salgluc to make the blood-bags last longer and work better

**Comment by bustygoku** [comment]
Isn't that what doctors do IRL?

**Comment by Chocobro** [comment]
@bustygoku yep. critical patients or patients unable to eat receive increased saline into their veins. it's enough to keep them alive, but they'll often be in too much pain to eat solid food. yogurts are what saved my life when i was in that state.

**Pull request merged**
