### PR TITLE
Completely Redoes Underground Outpost 45 Atmospherics

### PR DESCRIPTION
**Pull request by san7890**
Merging this is required for #76245

## About The Pull Request

Hey there,

Every time this away mission got loaded, we got some really wacky runtimes like the following:

```txt
[2023-06-22 04:38:37.613] RUNTIME: runtime error: list index out of bounds
 - proc name: set pipenet (/obj/machinery/atmospherics/components/set_pipenet)
 -   source file: components_base.dm,167
 -   usr: null
 -   src: UO45 Mining omni air scrubber ... (/obj/machinery/atmospherics/components/unary/vent_scrubber/on)
 -   src.loc: the floor (136,101,12) (/turf/open/floor/iron)
 -   call stack:
 - UO45 Mining omni air scrubber ... (/obj/machinery/atmospherics/components/unary/vent_scrubber/on): set pipenet(/datum/pipeline (/datum/pipeline), the red scrubbers pipe (/obj/machinery/atmospherics/pipe/smart/manifold4w/scrubbers/hidden))
 - /datum/pipeline (/datum/pipeline): build pipeline blocking(UO45 Gateway omni air scrubber... (/obj/machinery/atmospherics/components/unary/vent_scrubber/on))
 - Atmospherics (/datum/controller/subsystem/air): setup pipenets()
 - Atmospherics (/datum/controller/subsystem/air): Initialize()
 - Master (/datum/controller/master): init subsystem(Atmospherics (/datum/controller/subsystem/air))
 - Master (/datum/controller/master): Initialize(10, 0, 1)
 - 
[2023-06-22 04:38:37.637] RUNTIME: runtime error: addMachineryMember: Nonexistent (empty list) or null machinery gasmix added to pipeline datum from �UO45 Mining omni air scrubber T2AiT which is of type /obj/machinery/atmospherics/components/unary/vent_scrubber/on. Nearby: (136, 101, 12) (code/modules/atmospherics/machinery/datum_pipeline.dm:134)
 - proc name:  stack trace (/proc/_stack_trace)
 -   source file: stack_trace.dm,4
 -   usr: (src)
 -   src: null
 -   call stack:
 -  stack trace("addMachineryMember: Nonexisten...", "code/modules/atmospherics/mach...", 134)
 - /datum/pipeline (/datum/pipeline): add machinery member(UO45 Mining omni air scrubber ... (/obj/machinery/atmospherics/components/unary/vent_scrubber/on))
 - /datum/pipeline (/datum/pipeline): build pipeline blocking(UO45 Gateway omni air scrubber... (/obj/machinery/atmospherics/components/unary/vent_scrubber/on))
 - Atmospherics (/datum/controller/subsystem/air): setup pipenets()
 - Atmospherics (/datum/controller/subsystem/air): Initialize()
 - Master (/datum/controller/master): init subsystem(Atmospherics (/datum/controller/subsystem/air))
 - Master (/datum/controller/master): Initialize(10, 0, 1)
```

I'm going to chalk it up to how absolutely goreifying the old UO45 atmospherics was, so I just redid it to modern standards. Should be a lot cleaner now, may have missed a few things so let me know.
## Why It's Good For The Game

Looks way cleaner, actual modern mapping standards for a map that hasn't been touched in a _long_ while, less runtimes!!!
## Changelog
man does anyone even like this away mission? it's not player changing enough i fear

lmk if i missed something, but it stopped generating runtimes so i'm calling it epic swag

### CODE REVIEW

**Comment by Maurukas** [comment]
This will probably cause issues in #76029, but that one's stuck on hold for a few weeks and will probably stale out. This looks like it fixes a lot of the issues that are cropping up there anyway.

**Review by Maurukas — CHANGES_REQUESTED** [review]
Bunch of minor atmos plumbing issues. These either runtime or show up on check plumbing:
* Disconnected pressure tank (need layer adapter or layer change) at 98,113
* Doubled pipe at 120,125
* Disconnected scrubber at 119,155
* Wrong layer passive vent at 156,122
* Disconnected port at 158,116
* Disconnected port at 150,117 and 149,117
* Multiple disconnected scrubbers/vents in crew quarters near 125,127:
image

**Comment by Yobrocharlie** [comment]
> This will probably cause issues in #76029, but that one's stuck on hold for a few weeks and will probably stale out. This looks like it fixes a lot of the issues that are cropping up there anyway.

this PR if merged would require me to individually go to each unique gas mix tile and replace them with the proper tiles,
But that wouldn’t be so bad

**Comment by Yobrocharlie** [comment]
If anything this would cause me to have to re-do what I have already done (if relevant which it’s probably not),

meaning probably the re-addition of the dark gygax simplemob boss and better work in other areas.

**Comment by san7890** [comment]
> Bunch of minor atmos plumbing issues. These either runtime or show up on check plumbing:
> 
> * Disconnected pressure tank (need layer adapter or layer change) at 98,113
> * Doubled pipe at 120,125
> * Disconnected scrubber at 119,155
> * Wrong layer passive vent at 156,122
> * Disconnected port at 158,116
> * Disconnected port at 150,117 and 149,117
> * Multiple disconnected scrubbers/vents in crew quarters near 125,127:
>   image

forgot about this verb thanks

**Review by Maurukas — APPROVED** [review]

**Comment by Yobrocharlie** [comment]
Death

**Pull request merged**
