### PR TITLE
Cold resistance mutation no longer also provides pressure resistance

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: The cold resistance mutation no longer provides pressure resistance.
rscadd: Biosuits, radsuits, and bombsuits now provide pressure resistance in the same manner as a firesuit.
rscdel: The cold resistance mutation no longer provides an extremely weak passive burn heal.
/:cl:

The first one is important and will force cold resist users to actually wear pressure-resistant clothing, including firesuits and the added pressure-resistant clothing.
The second one is not important but I'll bet a dollar that people will complain anyway.

### CODE REVIEW

**Comment by Armhulen** [comment]
>biosuit provides pressure resistance


??????

**Comment by ChangelingRain** [comment]
It's a sealed suit it makes *exactly* as much sense as the firefighter helmet that doesn't even cover your face providing pressure resistance

**Comment by Shapsy** [comment]
the firefighter helmet provides pressure resistance???

**Comment by TechnoAlchemisto** [comment]
Adding pressure resist to fire gear is bad

**Comment by ChangelingRain** [comment]
Yes. Don't ask me how it works I'm just pretty sure that a sealed biosuit has as much reason to resist pressure as that helmet does.

**Comment by Mooseykins** [comment]
I say remove the pressure resistance of a firesuit instead.

**Comment by PKPenguin321** [comment]
>rscadd: Biosuits, radsuits, and bombsuits now provide pressure resistance in the same manner as a firesuit.
rscdel: The cold resistance mutation no longer provides an extremely weak passive burn heal.

both fine but leave CR pressure resist alone

**Comment by jughu** [comment]
>nerfing the whole reason cold resistance exist
Welp.i might aswell swallpw down cyrox and wear a firesuit to be space proof

**Comment by XDTM** [comment]
Cold resistance is meant to be space resistance afaik

**Comment by jughu** [comment]
This been like 10 years and only now we get balance changes :^)

**Comment by KorPhaeron** [comment]
Why?

**Comment by KorPhaeron** [comment]
"Cold resist" includes pressure because the power predated the introduction of pressure damage by half a decade, it was always meant to provide space flight.

**Comment by Firecage** [comment]
Why?

**Comment by Fox-McCloud** [comment]
👍 to removing the passive heal from cold resist
👎 to removing the pressure protection from cold resist

**Comment by ChangelingRain** [comment]
Why? To put it simply; so you can't wear armor while you're wandering around outside the station, hunting for antags, probably with the rest of the genetics powers.

**Comment by PKPenguin321** [comment]
Literally who cares when half the space suits are already crazily armored? Sounds like you just died to a geneticist again.

**Comment by Fox-McCloud** [comment]
@PKPenguin321 does have a point; hardsuits got armored to a ridiculous degree semi-recently.

**Comment by PKPenguin321** [comment]
Plus captain hardsuit, sec hardsuits

**Comment by ChangelingRain** [comment]
Hard/space suits are also relatively limited, there's usually only like 12-16 per map and people usually aren't willing to give them up, while genetics can effectively just print free hardsuits that don't use a slot, not to mention all the other powers.

Though i guess since kevinz000 added flightsuits science can also print hardsuits...

**Comment by XDTM** [comment]
Can we just rename it "Space Adaptation" or something like that, it's the whole point of the mutation, as Kor said

**Comment by optimumtact** [comment]
The firesuit having pressure resistance is a call back to older server culture, not sure if I want to introduce more space worthy suits other than hardsuits, spacesuits and the firesuit

Irregardless this PR obviously needs tweaks to compromise based on the feedback it's gotten so far.

**Comment by ChangelingRain** [comment]
@optimumtact I think you're spouting buzzwords there's no feedback here, just "fuck off". And there's really no compromise possible, either...

**Comment by Cheridan** [comment]
if people dont like it and there's no compromise possible then there's only one option i'm afraid

**Comment by optimumtact** [comment]
I was gonna do that but I thought I'd try being polite instead

**Pull request closed without merging**
