### PR TITLE
fuck it: removes tendril GPS signal

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

on da tin

## Why It's Good For The Game

im not thinking straight but when i was thinking straight for a LONG WHILE before this and this PR should have been made ages ago

fuck you
## Changelog
:cl:
del: removes Necropolis tendril GPS
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Merging from master is not good practice!

**Comment by MrDoomBringer** [comment]
image
image

**Comment by Jared-Fogle** [comment]
image

**Comment by Jared-Fogle** [comment]
re-open this when you're sober pal. i'm here for it

**Comment by wesoda25** [comment]
let me explain:

all of us rational human beings are displeased with the fact that miners B-line for loot and ignore mats

NOW

I did not know that tendrils even HAVE GPS signals until like maybe 3 weeks ago

what does this mean?

wtf are you guys doing, this should have been merged ages ago

**Comment by wesoda25** [comment]
@Jared-Fogle dude not cool

**Comment by DinkleNH** [comment]
retarded retard makes retard pr and has retarded. go home wesoda your on the sauce

**Comment by Jared-Fogle** [comment]
no the pr is good. i just want him to be sober

**Comment by DinkleNH** [comment]
pr sucks balls whats the point of a tendril if you cant find it

**Comment by Jared-Fogle** [comment]
go mining and walk around

**Comment by DinkleNH** [comment]
better change would be making all the mining level gps names the same so you have a equal chance to run into a shithead collosus or blood red baby

**Comment by Jared-Fogle** [comment]
youll just walk away

**Comment by DinkleNH** [comment]
your about to get suplexed fr

**Comment by JohnFulpWillard** [comment]
These comments are joyful to read through, but I do like this PR. Now miners have to actually mine to stumble on tendrils, rather than just mine straight towards it, missing so many possible mats. 
This possibly could've even been an alternative PR to the one that removed ORM upgrades

**Comment by Pinkufeck** [comment]
Just make tendrils harder.

**Comment by DinkleNH** [comment]
unironically facts double their spawnrate and health and miners without upgrades AKA miners who havent mined wont be able to kill them

**Comment by Jared-Fogle** [comment]
he went to bed so i'm reopening it

**Comment by Fikou** [comment]
AJAJJJAJHAJHAJJAA

**Comment by Jared-Fogle** [comment]
do need to fill out the "why its good for the game" part with something meaningful though

**Comment by Fikou** [comment]
i think some method of knowing at least how many tendrils did spawn roundstart would be nice though

**Comment by Livrah** [comment]
Isnt tendrils loot was already nerfed like 3 times? Add more and better rewards for mining points if "miners dont mine" is a problem. With this PR miners will spend entire round blindly looking for tendrils and not coming back.

**Comment by TemporalOroboros** [comment]
Honestly. As someone who plays miner a lot, I approve. Besides, if you want tendrils that badly you can just gridmine.

**Comment by Jared-Fogle** [comment]
> With this PR miners will spend entire round blindly looking for tendrils and not coming back.

miners arent malicious, just speedrunning. i don't think we'll see miners jumping into lava or something because they couldnt find a tendril.

have a bit more faith in the players will ya

**Comment by Sparkezel** [comment]
Just make the goddamn necropolis chests locked, that you need to buy keys for 1000 or so mining points 😎

**Comment by ardentarclight** [comment]
i mean, are miners beelining even an issue? in my experience, miners still go through enough rock even when speedrunning that they bring a decent amount of mats back once the first trip is done. if anything, literally just make tendrils spawn deeper into lavaland so miners bring back more ore naturally for going to them, or have to mine and get cutters. you could probably also just make ores be included in chests if mats not making it back to the station is such an issue

**Comment by D4C-420** [comment]
If you want miners to mine rocks don't make it so tedious to do so. Any miner worth their salt is going to mine for mining points simple because they need the damn healing. Any time a miner is not handing in ore its not because they are not mining its because either 1. they all died (as if goliaths still hard and chain stun). 2. they are just slow (with a pka it takes time to get through rocks and going to and from the ore takes time. using and advance plasma cutter and holding satchel lessens this but going to and from the orm still takes time) 3.  They legitimately have fucked off (it does happen but the majority of the time they have found a cool gamer ruin or have gone with the free golems).  If you take out tendrils your still going to have the same problem with miners beelining to megafauna and becoming more likely to die. 

Also like 70% of tendril loot is either just bad or has no real use on lava land. Making some of it not completely useless to miners or anyone on station is not a bad idea.

**Comment by optimumtact** [comment]
this shit still doesn't compile, make a new PR that works first time off

**Comment by MrDoomBringer** [comment]
image
one bad gloop

**Comment by ExcessiveUseOfCobblestone** [comment]
@DinkleNH dont say the r word or you can get banned from GitHub (no involvement on our end)

**Pull request closed without merging**
