### PR TITLE
Fixes non rustable turfs from being rusted

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request
Water, sand, rocks, grass, etc should not be rusted. Let me know if i
missed anything.

## Changelog

:cl:
fix: Fixes non-rustable turfs from becoming rusty.
/:cl:

### CODE REVIEW

**Review by MrMelbert — APPROVED** [review]
kinda wish rust immunity was a turf flag (or something), but this works

**Comment by SuperNovaa41** [comment]
I could do that instead if you want

**Comment by MrMelbert** [comment]
This is an alternative to #65361 now

**Comment by SuperNovaa41** [comment]
I hate feature coders

**Pull request merged**
