### PR TITLE
Line change to fix monkeys never devolving into humans if they started as a monkey

### LINKED ISSUE #55997: Monkeys cannot be transformed into humans (genetics console AND mutadone)
Reporting client version: 513.1533

## Round ID:
[153698](https://scrubby.melonmesa.com/round/153698)

## Testmerges:
- [[DNM] Revert move type refactor, fixing the constant server crashes](https://www.github.com/tgstation/tgstation/pull/55913)

## Reproduction:
Put a monkey in a genetics console, press scramble DNA. The console says transforming but the monkey doesn't transform.

Discover monkified and change one of the letters to something invalid. The console says transforming but the monkey doesn't transform.

Inject monkey with mutadone. The monkey -> human animation plays, but after it finishes the monkey falls over, still a monkey. The animation plays over and over while it still has mutadone in its system.

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

I wondered if this would be a problem when I originally made https://github.com/tgstation/tgstation/pull/55844 since I only tested on humans devolving into monkeys and back, but not monkeys into humans if the monkey spawned as one. Nyoops.

## Why It's Good For The Game

fixes https://github.com/tgstation/tgstation/issues/55997

## Changelog
:cl:
fix: Line change to fix monkeys never devolving into humans.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
did u test it

**Comment by necromanceranne** [comment]
I get what you're doing but yes I tested this interaction specifically. I test all my prs but sometimes I miss details I hadn't anticipated. Monkeys initialize with an activated monkey gene, so they always have their original_species set to monkey. I was testing for humans to monkeys and back, not for monkeys to humans. Some things get missed, and technically the new version of the pr was merged the same day I put it up, so I had little time to figure out my mistake.

Does that answer your question?

**Comment by Qustinnus** [comment]
i was not trying to come off as rude, i just know the mutation code is ass and i ran into the same issues with this stuff when monkeys were TM'd

**Comment by ShibaInuLord** [comment]
dont merge this to cuck geneticists

**Pull request merged**
