### PR TITLE
Removes His Grace from purchase

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
del: His Grace was dropped into a lava filled volcano and was never seen
again.
/:cl:

Closes #24977.

His Grace is a tool only for murder that shortens rounds and adds
nothing to the game.

At least, I'm told this.

@kevinz000 please use your words and explain why this should be merged.

### CODE REVIEW

**Comment by kevinz000** [comment]
Goofball get off coiax's account.

**Comment by Kraseo** [comment]
with ascension removed it has no more purpose other than being a double energy-sword that just gets more force damage the more people you kill

**Comment by kevinz000** [comment]
You've missed the point completely.
I said that it should not be an unremovable hazard to the station that encourages murderbone and shortens round time because you tried to make it STATION_LOVING or whatever the flag is called.
You took it as "Remove this item it adds nothing to the game/encourages murderbone/shortens round times".
 Did I ever say to completely remove it?
As I've just said in OOC, there's a thin line between hugbox and making it two dimensional call of duty, and that PR alone is on the latter's side.

**Comment by Iamgoofball** [comment]
yeah just re-add ascension

**Comment by ChangelingRain** [comment]
Ascension is bad and has no good gameplay results reeeeeeeeeee

**Comment by coiax** [comment]
Man, I get cranky sometimes.

**Pull request closed without merging**
