### PR TITLE
Fixes some simple animal maxhealths

### LINKED ISSUE #17438: Farm animals don't start with their max health
Farm animals have only their health defined in 
https://github.com/tgstation/-tg-station/blob/2881b4a09e5739cb64ac067567d285ab887c161b/code/modules/mob/living/simple_animal/friendly/farm_animals.dm

This causes them to start with that health but they all have default max health of 20, defined in
https://github.com/tgstation/-tg-station/blob/2881b4a09e5739cb64ac067567d285ab887c161b/code/modules/mob/living/simple_animal/simple_animal.dm

Health huds are showing these simple mobs in weird healths when they're spawned because chick for example has 1/20 hp when spawned. It should have 1/1 hp. Cows have 50/20 hp when spawned which is over their max health.

Should be easy fix to add the max healths to that farm animals file.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #17438

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I believe the simple animal Xenos have a few issues in this regard, too.

**Comment by Cheridan** [comment]
might be better to not worry about health var declarations at all, just have it set health == maxHealth in simple_animal/New()

**Comment by phil235** [comment]
@Cheridan What if we want to add var edited mob that does not have full health on a map?

**Comment by ChangelingRain** [comment]
Doesn't work unless you edit the damage vars; you need to set one of the damage vars or it'll just be full health.

**Pull request merged**
