### PR TITLE
Adds a few new experisci experiments involving going out and scanning people for Science, Genetics, and Medical to complete

### PR DESCRIPTION
**Pull request by MrMelbert**
I finally figured out the experiment API after like 1.5 years

## About The Pull Request

- Adds a new category of experiment to complete: **"Human Field Research**. These experiments involve scanning a person (`/human`s), often with a mind (other players) to progress the experiment. 

image
image

The following changes have been made: 

- Xeno-organ biology no longer requires a cytology or slime experiment. Now, it can be fulfilled by a new experiment which requires you scan 4 different crewmembers (minds required) of the roundstart races.

- Advanced Surgery's price has increased from 1500 to 5000. Advanced surgery can now be discounted by a new experiment which requires you can 12 points worth of wounds from different crewmembers (minds required). Higher severity wounds are worth more, and a person with multiple wounds will all count towards it. 

- Experimental Surgery is discounted less by the botanical traits experiment, but can now be discounted by a new experiment which requires you scan crewmembers (minds required) who have a trauma from a random selection of traumas.

- Alien Surgery is now discounted by dissecting an abductor. 

- Genetic Engineering's price has increased from 2500 to 3000. Genetic Engineering can now be discounted by scanning test subjects who have a combined mutation in their DNA.

- Alien Biological Tools is no longer discounted by xenobiology hard. It is instead discounted by either scanning 2 abductors or by scanning one of each slime species. 

## Why It's Good For The Game

Brings some more variety into experiment scanning. 

These experiments should provide some fun new methods of doing science. Notably many of them require you scan crewmembers, and not mindless mobs like hu-monkeys. This is chosen so scientists actually have to test on each other, or allow medbay to test on patients that arrive. For example the wound experiment, I think it'll be fun to say "Hey, want to get your legs broken for science?" - which even opens up some new antag shenanigans possibly. 

Cost for nodes were adjusted due to the presence of these new experiments to discount them.

## Changelog

:cl: Melbert
add: Adds a few new experiments to science which require the scientists go out and scan members of the crew for things like species, brain traumas, mutations, or wounds. Some nodes are now discounted by these experiements. 
add: Adds Abductor dissection experiment. 
add: Medical Kiosks can complete experiments which require human scanning. Alt-click the scanner wand to select experiments. 
qol: Screentips and examine text for Experiment Handlers
qol: Screentips for the medical kiosk
/:cl:

### CODE REVIEW

**Comment by Vect0r2** [comment]
Honestly, scientists shouldn’t have to scan shit in other departments. The DEPARTMENTS should have to.

**Comment by Sealed101** [comment]
most of these seem like experiments for the sake of having an experiment but the potential prospect of medbay/RnD purposefully inflicting wounds to assistants "for the bit" is hilarious

also fun idea - turn the stationary health scanner into an experiment handler, so medbay can scan wounds on people with the scan wand

**Comment by DATA-xPUNGED** [comment]
"Hey, want to get your legs broken for science?"
God imagine a scientist just coming up to you, saying that, then breaking your kneecaps with a baseball bat

**Comment by Vect0r2** [comment]
> ok

All I am saying is the dissections for med tech are amazing, as medical staff can do them. I like them, just food for thought.

**Comment by the-orange-cow** [comment]
> Honestly, scientists shouldn’t have to scan shit in other departments. The DEPARTMENTS should have to. Scanning 13 different engi tools so engi can get the EPIC MINER DRILL and you get nothing isn’t fun.

Although its beyond the scope of this pull, i would agree.  Every department getting a few experisci scanners shiftstart could help with that.

More on point to this pull, I love the idea that medbay will be turned into a ragecage for research.

**Comment by optimumtact** [comment]
These are fetch quests and they are everything wrong with experiment design

strong no from me.

**Comment by Vect0r2** [comment]
> okay maybe the roudnstart species one is a fetch quest but the mutation / wound / traumas are done with experimentation (the wound one especially, inflicting harm on your fellow man)

Yeah, I love the wounding one, as medical does it for medical tech, not a scientist doing it for medical tech

**Comment by TheSmallBlue** [comment]
> also fun idea - turn the stationary health scanner into an experiment handler, so medbay can scan wounds on people with the scan wand

If we were to implement this at all I think the best way to go around it is for these experiments to only be scannable via health analyzers or surgery consoles.

While it would be fun to go around destroying people's tibias for points, It'd be extremely annoying to everyone but you, and as much as it pains me I do agree with Oranges, we don't need more experiments that are just fetch quests.
If we made it so that these experiments complete themselves naturally, it'd remove both the fetch quest aspect and the "harming people for funsies" aspect. And to do this, the "scanning" should be implemented into medical equipment that doctors use. For example, moth with a Third Degree Burn shows up, you as a MD go "bingo, I can get the Moth experiment and a few points for the burn experiment!"

I still dont like this though, human surgery and non-human surgery are the kind of medical experiments we should be striving for, stuff that medical can pitch in with science to "give a hand" and get a sizeable reward (the tech they want)

**Comment by optimumtact** [comment]
> okay maybe the roudnstart species one is a fetch quest but the mutation / wound / traumas are done with experimentation (the wound one especially, inflicting harm on your fellow man)

@Mothblocks @ninjanomnom

**Comment by Mothblocks** [comment]
- Wounds one is probably fine, though also looks pretty difficult and might need to be toned down at some point. Conceptually okay, I don't see it as a fetch quest but more something that will be passively done alongside medbay work. In the future would be cool if the health analyzer told you if you're scanning a wound that hasn't been scanned yet
- Xeno-organ biology one is lame but is better than what we have now I think? I don't care about this one either way but wouldn't want to see it stick around
- Experimental surgery one feels like it's pretty lame and also would never get completed, I don't like that one

**Comment by DustanHache** [comment]
> Off the dome:
> 
> * Wounds one is probably fine, though also looks pretty difficult and might need to be toned down at some point. Conceptually okay, I don't see it as a fetch quest but more something that will be passively done alongside medbay work. In the future would be cool if the health analyzer told you if you're scanning a wound that hasn't been scanned yet

I would like to point out that you can create weeping avulsions rather easily with aggrograb, harm, and target the head with a sharp object.  assuming the points scale with tier, this is *very* easy and only requires the scanner and someone who knows how to use the right ends of a scalpel and cautery. essentially the same as xeno-organ biology with extra steps.

> * Xeno-organ biology one is lame but is better than what we have now I think? I don't care about this one either way but wouldn't want to see it stick around
> * Experimental surgery one feels like it's pretty lame and also would never get completed, I don't like that one
Both of these are cheap enough in my eyes that they wouldnt be world-ending uncompleted. the former is also rarely if ever used (because nobody fucking constructs organ printers when cybernetics exist) and the latter is almost solely for zombie surgery and brainwashing, which are rather antagonistic in their design.

**Comment by Mothblocks** [comment]
> I would like to point out that you can create weeping avulsions rather easily with aggrograb, harm, and target the head with a sharp object. assuming the points scale with tier, this is very easy and only requires the scanner and someone who knows how to use the right ends of a scalpel and cautery. essentially the same as xeno-organ biology with extra steps.


This is the exact gameplay that sucks with experiments, though, this is an argument against the feature more than it is in favor of it

**Comment by moocowswag** [comment]
Does all of this require using an experiscanner? It seems pretty silly that medbay will operate even slower because of this.

"Hey, my patient has t3 wounds, dont fix them until i come back with an experiscanner"

**Comment by DustanHache** [comment]
> > I would like to point out that you can create weeping avulsions rather easily with aggrograb, harm, and target the head with a sharp object. assuming the points scale with tier, this is very easy and only requires the scanner and someone who knows how to use the right ends of a scalpel and cautery. essentially the same as xeno-organ biology with extra steps.
> 
> This is the exact gameplay that sucks with experiments, though, this is an argument against the feature more than it is in favor of it

i am neither for nor against this PR, and am only pointing out that your assumed difficulty is lower than you expect outside of MRP.

**Comment by Mothblocks** [comment]
In my head the wounds thing would be part of the health analyzer innately

**Comment by JohnFulpWillard** [comment]
heed my warning
image

**Comment by Sealed101** [comment]
assigning experiments to departments + departmental experiment handlers seems like a different project altogether. not only do we not have enough experiments to make such categorization make sense, the experiments currently available are underwhelming uhhh somehow? im not sure from what i've seen players just see tedium and do not do any experiments past the industrial tech scans

also this PR makes the medical kiosk's scanning wand an experi-handler, which should be accessible enough for medbay crew to use

**Comment by Mothblocks** [comment]
I'm not sure I like needing to go out of your way to do the experiments, that's why I like them being attached to the health analyzer

**Comment by Jacquerel** [comment]
Passively unlocking this as a result of scanning people coming into the medbay sounds kind of fun, I have to echo the idea that attaching it to a tool doctors aren't already carrying around seems like it's mostly going to speedbump people without much benefit.

**Comment by optimumtact** [comment]
This is the same as the toilet scannign experiment everyone makes fun of so merge this crap at your own risk.

**Comment by Wallemations** [comment]
boutta strap a scientist to a chair and smash their skull in with a toolbox to get some wounds to scan

**Comment by the-orange-cow** [comment]
> boutta strap a scientist to a chair and smash their skull in with a toolbox to get some wounds to scan

New antag meta:  "no officer, you see, I was just trying to complete research"

**Pull request closed without merging**
