### PR TITLE
Refactors Human Explosion Damage

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Refactors human explosion damage to use `take_overall_damage` (which applies damage to all valid external organs). Instead of having a snowflaked method of dealing damage.

This also has the added benefit that explosion damage will not decrease, should a limb be hypothetically missing (I know, not supported here...yet).

### CODE REVIEW

**Comment by Iamgoofball** [comment]
remove organ damage when

**Comment by tkdrg** [comment]
> yet

So hopeful. Also conflicts.

**Comment by Fox-McCloud** [comment]
loveellyyy, followed normal procedure to fetch upstream and something went horrendous wrong. Not going to bother fiddling; will just re-upload.

**Comment by optimumtact** [comment]
some kind of line ending issue it looks like

**Pull request closed without merging**
