### PR TITLE
Readds percentagecalc as default_display_in_results

### PR DESCRIPTION
**Pull request by Jordie0608**
The prompt and name hopefully indicative of the actual function of this column.

Don't merge this until @MrStonedOne makes the table change.

### CODE REVIEW

**Comment by Jordie0608** [comment]
@nfreader now you can do the thing

**Comment by nfreader** [comment]
👍 Ready when you are

**Comment by MrStonedOne** [comment]
[15:57:18] <~MrStonedOne> it is such a lame change.
[15:57:35] <~MrStonedOne> default_display_in_results
[15:57:45] <~MrStonedOne> it has nothing to do with display
[15:57:55] <~MrStonedOne> and everything to do with calculating percentages
[15:58:10] <~MrStonedOne> precentagecalc is more descriptive
[15:58:31] <~MrStonedOne> I'm just not going to make the change

**Comment by Jordie0608** [comment]
;-;

**Comment by Jordie0608** [comment]
@Cyberboss is ready.

**Comment by MrStonedOne** [comment]
>not updating the title of the pr

**Pull request merged**
