### PR TITLE
Telescopic Baton Resprite

### PR DESCRIPTION
**Pull request by maxymax13**
## About The Pull Request

myeyes the pain doesnt stop

Resprite of telescopic batons by Flareguy to look like telescopic batons instead of a blurry.. thing.

## Why It's Good For The Game
look at this dude
look at it

i get the multi segment thing it was going for but that just doesn't work in pixel art (without making it really fat), and it was also really, really hard to see inside inventories, and the anti alias thing was really artifacted and just doesn't work on most backgrounds

this is how it looks inside an inventory
image

(as opposed to)
image

## Changelog
:cl: Flareguy
imageadd: Telescopic batons are now a discernible shape
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
might as well center the collapsed state while we're here
looks great tho 👍

**Comment by maxymax13** [comment]
the way the sprite is set up is in a fucked up middleground between centering the collapsed sprite or keeping it in place like an esword, idk whil side to fall into

**Comment by MrDoomBringer** [comment]
eh leave it as it is and we can center all the closed telescopic items in one fell swoop later

**Comment by Tlaltecuhtli** [comment]
cant be a cyberpunk baton without leds

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
