### PR TITLE
Bombs are no longer capped on the mining z level

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Explosions are no longer capped on the mining z level.
/:cl:

### CODE REVIEW

**Comment by Shadowlight213** [comment]
OOC: Digdugxx: here comes the race to destroy the entire z-level with one bomb

There is no way this can go badly

**Comment by Dorsisdwarf** [comment]
!()[http://puu.sh/sbjtk/f625d70fe8.png]
!()[http://puu.sh/sbjH4/8c4637b25a.png]
!()[http://puu.sh/sbjIq/5b136a8ee5.png]

**Comment by phil235** [comment]
Did you test how laggy a very large bomb is?

**Comment by Dorsisdwarf** [comment]
Top right corner of last is bottom right of middle

**Comment by KorPhaeron** [comment]
@phil235 

Dorsidwarf just did it live on server, didn't seem terrible

**Comment by CPTANT** [comment]
Hmmm now to get my bombs beyond 7/15/30

**Comment by Dorsisdwarf** [comment]
That was 20/50/90, by the way.

**Comment by XDTM** [comment]
abductor ships are pretty sturdy

**Comment by Shadowlight213** [comment]
Same with the ash walker dens. How did that take like NO damage??

**Comment by Dorsisdwarf** [comment]
Oh I spawned that afterwards. That wouldn't have survived that was5 tiles from Ground Zero

**Comment by ExcessiveUseOfCobblestone** [comment]
killing savages with a 20,50,90 sounds like the best feature on lavaland since lavaland.

For Reference:
https://www.youtube.com/watch?v=2av9SQsMIi8

**Comment by Incoming5643** [comment]
1. Should be a config toggle so downstreams with less robust servers can choose not to choke to death on 255/255/255/255 bombs

2. Maybe the max cap should be tied to how thin the atmospherics of the blast zone is? Just musing but it seems less arbitrary and may in fact have some basis in physics (don't quote me on that).

**Comment by CPTANT** [comment]
next feature: nuke actually spawns a 40,100,180 explosion and obliterates the entire station.

**Comment by Core0verload** [comment]
Better to make cap on mining Z 2/3/4 times higher than on station. Having no limits at all can and would end badly.

**Comment by GunHog** [comment]
Now Toxins has a VERY good reason to give miners bombs! Remember to ask for bombs, Miners!!

**Comment by Fox-McCloud** [comment]
Yeah, I can see this ending very badly, long term, mostly with it becoming the standard meta once min-maxed bombs become standard knowledge.

**Comment by A-t48** [comment]
Yeah, won't they just use this to nuke all the mobs in mining at once and collect all the glorious loot?

**Comment by jughu** [comment]
One bomb to destroy hell!!! ONE BOMB TO COLLECT THE LOOT ONE BOMB FOR A GLORIOUS VICTORY!!! ANF ONE BOMB TO STAY OFF LAVALAND SINCE ITS A BIG BOOM

**Comment by Dorsisdwarf** [comment]
Please remember that that bomb I used is very close to the theoretical maximum bomb possible (I believe it was worked out to be 32/60/120 , not close to the average bomb. Traitors can TC-trade for bombcap removal and the station isnt a smoking crater every round (Well it is but not from bombcapless bombs)

**Comment by GunHog** [comment]
UNLEASH THE FULL FURY OF TOXINS!!!

**Comment by PKPenguin321** [comment]
>tfw you cant use bombs to mine anymore since you WILL get caught in the blast

**Pull request merged**
