### PR TITLE
Removes vine floors and their sprite

### LINKED ISSUE #18517: Kudzu generated floor interacts weirdly when a shuttle arrives
Kudzu can generate a /turf/open/floor/vines beneath it. When a shuttle arrives, that tile is replaced by space (along with removing the vines), making large holes in the shuttle.

### LINKED ISSUE #29694: When bomb explode kudzo vine floor it create metal
bugg

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Fixes #29694
Fixes #18517

Actually fixed in @ExcessiveUseOfCobblestone 's kudzu nerf in #30084, however he forgot to remove the spacevine turf that stopped being a thing used in the game after spacewalking kudzu was removed.

[Changelogs]: 
[]: 

:cl: Naksu
del: Removed unused vine floors and their sprite.
/:cl:

[why]: 
Closes issues, turf and sprite is unused in /tg/station codebase after the kudzu nerf.

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
whoops accidentally committed my devbox admins.txt, don't merge that one

**Comment by vuonojenmustaturska** [comment]
I should really learn to stop fucking with the same codebase using three different git-aware tools. I removed the mis-committed admins.txt just in case someone does something unsavory while drunk.

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
Go ahead and add yourself to the .txt

**Comment by lzimann** [comment]
You can add yourself to the txt, we actually encourage people to do it.

**Comment by ExcessiveUseOfCobblestone** [comment]
hahaha hehehe

**Pull request merged**
