### PR TITLE
Combat messages in first person

### PR DESCRIPTION
**Pull request by kingofkosmos**
So you can have a random name every round, forget your name and still realize if you're being attacked in the escape shuttle. Plus immersions, more polished look on the game and such.

_Before:_
You and everyone saw: **"John Doe punches Anders Andersen!"**

_Now:_
John sees: **"You punch Anders Andersen!"**
Anders sees: **"John Doe punches you!"**
Bystanders see: **"John Doe punches Anders Andersen!"**

_This is still a WIP! To do list:_
- [x] Find all combat messages and add the var/othermob and var/othermob_message to them.
- [x] Change combat messages to use the present tense.
- [ ] Figure out how to make simple_animals have several different time tenses in the attack verbs (so there's no "John Doe punch the goat").
- [ ] Fix the /atom/proc/visible_message to work as well.

### CODE REVIEW

**Comment by xxalpha** [comment]
Also try to uniformize the combat messages. Some weapons display messages in the format of "X attacks Y" and others in the format of "Y is attacked by X" and it's really shitty.

:+1:

**Comment by Fayrik** [comment]
This is second person, not first person.

Also, "You're punched" should be "You have been punched" or even better "John Doe punches you".
Just read this aloud: "You are punched."
Yeah.

**Comment by phil235** [comment]
I personnally would prefer "John Doe punches you" instead of "You're punched by John Doe!". We've standardized attack messages to show the attacker first (and not use "has been attacked by") so let's try to keep it simple. See #6130 and https://tgstation13.org/phpBB/viewtopic.php?f=9&t=1903 .

**Comment by kingofkosmos** [comment]
Good points, I'm changing it to "John Doe punches you!".

I've encountered a problem that every [response_help] or grab/disarm/harm e.g. "pets" needs a counterpartner [response_help2] = "pet". Is that ok or is there an easier way to do that? There are quite a few of those.

**Comment by kingofkosmos** [comment]
I'll put this project on hold since I don't even.

**Pull request closed without merging**
