### PR TITLE
Mobility refactor

### PR DESCRIPTION
**Pull request by Rohesie**
## About The Pull Request

The idea is to move the different status changes (stat, mobility_flags, eventually health and whatnot) away from processing loops such as `life()` or the several `update_thing()`, and towards them updating properly on change. This makes things more responsive, removes superfluous checks and allows us to register on these events (status changes) to react to them.

Furthermore, it makes checks a bit more granular, so you can check for more specific things. If you want to check if the mob can grab something you don't need to check if it's alive. If it's not then it can't do it. You just check for the ability to pick up things, pull or use things on hands.

* `update_mobility()` nuked. Mobility updates as it changes, if the stat changes to `UNCONSCIOUS`, for example, then proper traits will be applied to block voluntary movement, standing up or item manipulation.
* `mobility_flags` now represent the mob's potential for things. Traits are the method to add or remove temporary impairments, as we can track the sources.
* Changed several checks to remove superfluous ones. If hands are not blocked then user is conscious, for example, no need to re-check.
* Lying refactored: `lying_angle` represents the mob's angle rotation, only relevant for humans. Some old legacy checks of it removed. `body_position` tells us if they are standing or prone. This should make things with mobs that don't follow the human sprite logic a bit easier.
* restrained() dismembered into a trait and a macro check for being neckgrabbed.
* `resting` represents the position the user is looking to achieve, not the actual one it is in. If they are resting, they'll drop to the ground after unbuckling from a chair or will try to get up after being stunned, for example.
* Added two lazy list to track functional arms and legs, not to have to loop through the bodypart list every time.
* `incapacitated()` turned into a trait.

There's a ton of local testing I still need to do, but reviews are very welcome.

Feedback is welcome.

## Changelog
:cl:
tweak: Resting is now a stance, like a preference, you can turn on and off at any time. The mob will try to lay down or get up according to it, as soon as able to.
refactor: Refactored mobility code.
/:cl:

## Why It's Good For The Game

The only change I expect the players to notice is turning resting, crawling and standing into stances, so you select what you want to be and your mob will try to get to that position whenever possible. If you get slipped you'll get up after the stun (unlike on several cases now), and if you are crawling and someone buckles you you'll go back to crawling once you resist.

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
Make sure speed potions and legion cores and stable red slime cores are correctly removing slow downs before you finish this.

Slow down removal items aren't currently working properly.

**Comment by HomocidlePancakes** [comment]
>Make sure speed potions and legion cores and stable red slime cores are correctly removing slow downs before you finish this.

Don’t forget about space

**Comment by mkikt4743** [comment]
this gonna make us faster? y'all move so slow on tg

**Comment by Rohesie** [comment]
No, this should have no effect on gameplay beyond mobs trying to get up or lay down after stuns and blocks, respecting the resting button's preferred stance.. Hopefully.

**Comment by optimumtact** [comment]
has this progressed?

**Comment by kevinz000** [comment]
i can probably do something regarding this if this goes too stale and is closed, not that i want to touch mobility (lmao god 2000 files changed time) but uh yeah ping me i guess sometime if anyone remembers to

**Comment by Cyberboss** [comment]
Bot should ignore draft prs tbh

**Comment by optimumtact** [comment]
draft pr's open for this long should not be submitted in the first place.

It's pull request, not WIP review

**Comment by SpaceManiac** [comment]
Closing as stale. Contact a maintainer if work continues.

**Comment by kevinz000** [comment]
***probably*** continuing this after movespeed modifiers.

maybe

**Pull request closed without merging**
