### PR TITLE
Marine ID Access Change

### PR DESCRIPTION
**Pull request by Steelpoint**
This change affects a minor change to the Marine's ID Card access.

The card no longer has all access to centcom. While a edge issue, but someone with the ID can send a docked centcom ferry back to centcom, thus giving them full access to centcom. This PR changes the access to a generic away mission ID which is unused. 

:cl: Steelpoint
tweak: Iron Hawk Marine no longer has Centcom all access. My mistake.
/:cl:

### CODE REVIEW

**Comment by Repukan** [comment]
>Access to mining base

Absolutely fucking not

**Comment by Steelpoint** [comment]
One issue I've seen and been told by players is that some marines will blast their way into the mining base. This not only depressurizes the base, but causes a whole bunch of issues and sets the marine against the miners. 

It's likely one of the bigger issues and causes for marine oriented violence to the crew.

**Comment by Repukan** [comment]
Tell them to eat shit. They actually benefit from the low Atmos

**Comment by Repukan** [comment]
Other roles require miners to open the door for them, don't make Marines fucking snowflakes

**Comment by Steelpoint** [comment]
My proposal stands. This is to help stop issues that can occur.

**Comment by Grazyn** [comment]
What Repukan said, the marine can either wait for a miner to open the door or break in and seal the breach if he's in a hurry. And use his fucking tongue to talk to the miners instead of beelining for the station, unless you gave him some kind of unique marine language.

**Comment by Steelpoint** [comment]
I don't even want that change but it's based on feedback. I'll keep the proposal in for now but I'll remove it later unless I get more people here supporting it.

**Comment by lzimann** [comment]
Ghost roles should not have access to the mining base. Yea sure they can blast it open, but that also means miners blasting THEM open. So, if you want mining access, either interact with miners or fight them.

**Comment by Steelpoint** [comment]
Well either way the centcom access change is necessary. As I said I'll take out the marine miner access unless I get a lot of support for it here.

**Comment by MMMiracles** [comment]
You probably won't.

**Comment by Steelpoint** [comment]
I don't care what you think.

I keep my word.

**Comment by Steelpoint** [comment]
Misconstrued what @MMMiracles said. 

Either way I'll just remove it now to avoid hassle.

**Comment by Repukan** [comment]
That's fine man chill don't take it personal

**Comment by optimumtact** [comment]
>unless you gave him some kind of unique marine language.

Wat

**Comment by Niknakflak** [comment]
old war rambling

make it happen

**Comment by InsaneHyena** [comment]
Remove snowflake mining access.

**Comment by Steelpoint** [comment]
Perhaps you did not read the OP, the marine does not have mining access.

**Comment by FantasticFwoosh** [comment]
I dont see how this is not pointless when other roles break into the mining

The PR should be addressing the situation that the only thing the marine has to do is to EMIGRATE AND GRIEF/STOP & LOOTDROP.

> Unique language for marine = No thank you don't add a metacomm language for yourself or the librarian which is only shared by 1 role
> Access = No thank you strip the marine of ID altogether
> Marine is a powercrept shitty grief-hermit/prisoner hybrid with a even bigger gun and more ammo = No thank you revert please.

People use this to greif, the only objective is to get to the station using meta-knowledge, you shouldn't be as worried about HOW they will do that as WHY they will do that.

**Comment by Grazyn** [comment]
Any lavaland ghost role with the explicit objective to reach the station is going to be bad, because you can just scout the area and figure the shortest way before spawning. However, marine is already merged and this PR is just fixing the centcomm ID access, further discussion should probably move to the forums.

**Pull request merged**
