### PR TITLE
[s] redpills this pr

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by as334** [comment]
forgot the [s]

**Comment by PKPenguin321** [comment]
but now if an admin gives a cookie it'd be like giving a revive and also you could grind the cookie so nobody would give cookies :(

**Comment by as334** [comment]
Thats why the admins can't know.  keep it on the DL. delete your comment.

**Comment by MrStonedOne** [comment]
thats only if they knew, DELETE YOUR COMMENT

**Comment by Aloraydrel** [comment]
time to never spam SC :^)

**Comment by MrStonedOne** [comment]
COVER BLOWN

**Pull request closed without merging**
