### PR TITLE
Extra mutantrace parts won't hold color if the body gets husked

### LINKED ISSUE #8930: Lizard tails and mouthes do not turn grey when husked.
What it says on the tin. These should be grey, really a lack of a feature but it's quite ugly. @Incoming5643

### PR DESCRIPTION
**Pull request by Incoming5643**
In a great stroke of luck the husk grey and the default base grey for mutant races were fairly close and I didn't really have to do anything to it to make it look decent.

fixes #8930 

Point of note to maintainers who think this is controversial somehow because of all the comments, it's not, we're just discussing coloring mechanics in here.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Picture for reference?

**Comment by Incoming5643** [comment]
d10_icon

With a little squinting you can tell where the nose overlay takes over from the husk sprite, but during normal play I really doubt it'll be something noticible

**Comment by RemieRichards** [comment]
@Incoming5643 well given the game is rendered at 32x32(if you're weird) 64x64, or stretched, it's probably difficult to notice.

the only thing that annoys me is the dark outline of husks not continuing to the mutant part.
But that would require unique icon states which Idk if we need.

**Comment by Incoming5643** [comment]
It'd be easier to fade the outline from the husk base. Husk sprite is OLD and I don't really think anything else in terms of mob spites has such a cuttingly sharp border like that

**Comment by RemieRichards** [comment]
That's also an option, yeah.
Up to the art guys @WJohn @Nienhaus on that one.

**Comment by Incoming5643** [comment]
Also while your staring at this @WJohn if you want to send me all those custom lizard sprites you keep making some of their parts would mesh pretty easy with the system I happen to be touching right here as optional style stuff.

(the wings might be a bit much to swallow though)

**Comment by RemieRichards** [comment]
@Incoming5643 if you're referring to using the accessories system for lizard accessories, I tried making species specific ones about a week ago, and it's either:
A. Compromise clean code to get it to work (Ala Bay, no offence meant here but their method isn't nice)
B. Dont get it at all.

The issue being that 90% of accessories and stuff are chosen by the player while they're a /mob/new_player, which of course has no dna or dna.species

**Comment by Incoming5643** [comment]
species being in dna tends to muddle up a lot of things, it's got me to wondering if it wouldn't just be easier to make species its own thing and then give new_player a species datum to copy over to their character at roundstart.

**Comment by RemieRichards** [comment]
If species was moved down to /mob (I believe that's the lowest point in the tree new_player and carbon share) then that solves the issue I was having.

The problem is you're putting something predominantly for /human all the way down on /mob.
I mean it's all over the codebase already so you're not shitting it up any more on the grand scheme of things.

I'm sure you'll come up with something good.

**Comment by Cheridan** [comment]
Is there anything stopping you from just making new_player a carbon mob?

**Comment by WJohn** [comment]
I've got a few of these available, but I'm not really sure how these should be handled. I've got stuff like frills which have membrane, and those have colors of their own that I'd rather not have be struck by the same greyscale everything else is. Perhaps consider it a type of hair? I dunno.

**Comment by Incoming5643** [comment]
I was thinking added a secondary (tertiary?) color var so we could still have some vibrancy. Each "piece" doesn't have to be a single image, it can be composed of multiple chucked colored in different ways.

**Comment by WJohn** [comment]
I'm mainly worried about greyscaling. I know people are using something other than ye olde color var that you can edit in game, as that clearly caries the grey over into anything you do. I'm not seeing this happen to lizards though, who are actually grey, and I really want to know what's being done here and if there's any way I can reliably produce this myself.

**Comment by Incoming5643** [comment]
There's nothing special about how lizard sprite colors are generated. It's a grey base (same color as what you see when players don't set their configs) with the color var touched. Colors below a certain vibrancy are disallowed from alien color specifically because the additive effect of color var would begin to make them look washed out or solidly dark. For comparison hair doesn't have this restriction, and you can certainly see cases where detail is lost due to color choice.

One of the actual benefits of using just greys as a base is that you can basically turn the base sprite into a shading guide for the colors that come later.

I can try to set up a photoshop layer that nearly mirrors how the color var works with a little trial and error and give you that so you could tell how the sprites would look yourself.

**Comment by WJohn** [comment]
That'd be great for future work as so far I've basically been working with neary full-bright colors where grey is a necssary evil that I had to avoid (remie's dismemberment PR has these sprites). I'd definitely like to make better use of greyscaling.

**Comment by Incoming5643** [comment]
It can't be done strictly as a layer apparently, but I made this little guide on how to easily replicate how it would look in game given only the base grey sprite. (Download [click raw] it to get the layers and all that)

https://github.com/Incoming5643/-tg-station/blob/deep_fried_lizards/tools/Spriting%20Resources/previewing_color_in_photoshop.psd

I've made the somewhat cocky decision to commit that PSD to the project because it seems like a question that could come up a lot when new spriters try to come in on the project.

**Pull request merged**
