### PR TITLE
Attn: Feature Freeze going into effect November first, ending december first

### PR DESCRIPTION
**Pull request by optimumtact**
In honor of Nerf November, we will not be accepting new features, balance changes (unless strictly necessary to stop servers expoding) for all of November.

We will be accepting fixes and code refractors only.

The person who makes the best fix as determined by the maintainer team will get a prize, which I will make up later.

### CODE REVIEW

**Comment by Cyprex** [comment]
Are logging, debug visualizations and similiar additions fine?

**Comment by fludd12** [comment]
This might coincide pretty well with the whole [Hacktoberfest](hacktoberfest.digitalocean.com) thing, I think.

**Comment by MrDoomBringer** [comment]
refactoring supplypods to a component here it comes

**Comment by ExcessiveUseOfCobblestone** [comment]
As with other freezes, if I see evidence of working on a feature-oriented PR during the freeze that PR is subject to being closed even if you PRd it after the freeze is over.

The point of the freeze is to get people to shift their attention away from features, it becomes extremely less useful if people are going to "ride it out".

**Comment by Jared-Fogle** [comment]
> Are logging, debug visualizations and similiar additions fine?

Not sure what the precedent is, but I'd say yes.

**Comment by Dennok** [comment]
What about things that already PR'ed?

**Comment by Jared-Fogle** [comment]
@Dennok Doesn't apply. However, starting November 1st, only fixes and refactors.

**Comment by actioninja** [comment]
@Cyprex yes

**Comment by PKPenguin321** [comment]
>As with other freezes, if I see evidence of working on a feature-oriented PR during the freeze that PR is subject to being closed even if you PRd it after the freeze is over.

>The point of the freeze is to get people to shift their attention away from features, it becomes extremely less useful if people are going to "ride it out".

This seems poorly thought out

**Comment by optimumtact** [comment]
nobody asked you

**Comment by PKPenguin321** [comment]
nobody asked you

**Comment by Jared-Fogle** [comment]
@PKPenguin321 Part of the reason for doing a freeze like this is to relieve some stress from maintainers. Reviewing features is hard, basic fixes much less so. If people ride it out, then it just means that the hard work is just being put off to December, PLUS whatever features people make afterwards.

**Comment by optimumtact** [comment]
Now nobody has to ask you

**Comment by Moja10** [comment]
Oh god! November is here! The ice is creeping up my veins! As I type the code for the new gamemode, my fingers start to shiver and slow... I'll work on a smaller PR, adding new items to the uplink, but alas my palms begin to freeze... I will just add a new food to the kitchen, but my joints begin to lock in place... Perhaps I create a single line to add an existing item to clown... but my hands... they do not move. Nothing creeks in this barren frigid wasteland. But then, a warmth, I could just nerf meth again! It now does double brain damage, I feel the heat of life! I'm back to being a /tg/ coder.

**Comment by Jared-Fogle** [comment]
unfortunately for you nerfing meth would also be under the freeze

**Pull request closed without merging**
