### PR TITLE
Food health system

### PR DESCRIPTION
**Pull request by sawu-tg**
- Added a "Food Health" system. The closer a food is to it's wanted temp, the 'Healthier" it is
- Foods that are left out will begin to rot and become toxic
- Added some configurable serving stations to the Kitchen that warm and cool food
- Refrigerators will instantly cool food.

kitchen1
kitchen2
kitchen3

### CODE REVIEW

**Comment by paprka** [comment]
pics, also run map merger

**Comment by Iamgoofball** [comment]
>didn't run mapmerge

rip

**Comment by WJohn** [comment]
@phil235 
You okay with this? Maybe it should tie in to nutrition and your metabolism system.

**Comment by sawu-tg** [comment]
@WJohn This is entirely seperate from metabolism/nutrition systems.

This manages food reagents and their existence, not the reagents effects on people.

**Comment by Incoming5643** [comment]
Silly side effect of this system: The safest strategy for feeding people becomes lovingly crafting dishes then immediately blending them into a liquid and having people suck it out of condiment bottles.

**Comment by Iamgoofball** [comment]
@Incoming5643 if the entire station takes up a nutrient shake diet i'm going to fucking laugh

**Comment by sawu-tg** [comment]
@Incoming5643 Food starts with 0 reagents in it, and will only have reagents in it when cooled/heated to the right temperature. The moment it's taken off a cool/hotplate, it begins to lose it's reagents.

@paprka Mapmerge refuses to run. I will try to fix it but I'm not good with git stuff.

**Comment by Incoming5643** [comment]
That doesn't really make a whole lot of sense, you'd think stuff coming out of a microwave would be hot to begin with.

**Comment by sawu-tg** [comment]
@Incoming5643 That was something I forgot to add, I will do that right now.

**Comment by sawu-tg** [comment]
I dun goofed my branches up, closing this and making a new PR when I fix it all.

**Comment by sawu-tg** [comment]
#7148

**Pull request closed without merging**
