### PR TITLE
Sexy Solar Sprites

### PR DESCRIPTION
**Pull request by ghost**
dreamseeker

New solar panel sprites from Goon, not Polaris

:cl:
imageadd: Solar panels have new sprites
/:cl:

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Review by Jalleo — APPROVED** [review]
Looks better. Thats all I can say

**Comment by Buggy123** [comment]
Okay, that's nice, but could you put up a picture of the solars so we can see it without starting up dreammaker please?

**Comment by uraniummeltdown** [comment]
i will put up pictures tomorrow, too lazy to do it now

**Comment by praisenarsie** [comment]
DISCREPENCY DETECTED

these sprites are from goon

https://github.com/praisenarsie/goonstation-2016/blob/master/icons/obj/power.dmi

**Comment by uraniummeltdown** [comment]
Yeah the PR on Polaris said they got it from some Russian Paracode server, but you're right it is from Goon
I'll put it into the goon folder later

**Comment by Bawhoppen** [comment]
Can't you just view it in the icondiffbot???

**Comment by Supermichael777** [comment]
The broken sprite needs to be more obvious

**Comment by nicbn** [comment]
STOP PRING GOON SPRITES WE LIKE TO HAVE OUR OWN SPRITES

**Comment by Noahnoah55** [comment]
Goon sprites are objectively better in every way.

**Comment by WJohn** [comment]
These look great, yeah. I've always been in favor of goon's solars.

**Comment by Iamgoofball** [comment]
@nicbn fuck off

**Comment by nicbn** [comment]
Go away Iamgoonball

**Comment by awesine** [comment]
Isn't /tg/ license incompatible with goonstation's license? I remember reading this a while back.

**Comment by nicbn** [comment]
It is

**Comment by awesine** [comment]
then close this kek

**Comment by Iatots** [comment]
remove the dumb solar floor tile from the game pls

**Comment by MoreRobustThanYou** [comment]
@awesine that's why the goon folder exists, it's a different license

**Pull request merged**
