### PR TITLE
Fix for Seed Extractor not working and update to tgui

### PR DESCRIPTION
**Pull request by WarlockD**
## About The Pull Request
Fixes issue #50907, although I knew about it much earlier.   Fixed the storage system to use associated lists than to search all the piles for property matches and updated to use tgui.  Added a few features like sorting the lists of seeds but didn't change the design of the ui to be much different than the original.

## Why It's Good For The Game
The seed extractor now works!  And the tgui makes it quicker and easyer to use

## Changelog
:cl:
fix: Fixed extractor and tgui
fix: Ran webpack so it would work:P
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
Is this the 'seeds with certain characters in their name cannot be removed from the seed extractor' bug?

**Review by stylemistake — COMMENTED** [review]
Very nice. Clean up weird spaces in tags, like `<Table.Cell >`, and try `yarn install` and rebuild again, because travis can't reproduce the build, something is off.

**Comment by WarlockD** [comment]
> Is this the 'seeds with certain characters in their name cannot be removed from the seed extractor' bug?

Honestly I don't know.  When I saw the implementation of how seeds were binned I knew it was going to have a bunch of errors one way or another so I chucked it.  That would explain why it would work sometimes and not others

**Comment by WarlockD** [comment]
> Very nice. Clean up weird spaces in tags, like `<Table.Cell >`, and try `yarn install` and rebuild again, because travis can't reproduce the build, something is off.

Humm wierd ok.  Let me do that reall fast

**Comment by WarlockD** [comment]
That's weird, ran yard install and everything was uptodate and ran tgui to rebuild and github didn't detect changes

**Review by stylemistake — APPROVED** [review]

**Pull request merged**
