### PR TITLE
Ninja Invisiblity Fixes

### LINKED ISSUE #8249: Cloaked Ninjas fire cloaked projectiles
Cloak as ninja
Fire egun/laser/disabler

Invisible

Hilarious, but totally broken

### LINKED ISSUE #8691: Ninja invisibility is unstoppable.
Their weapons are invisible, you can't force them out of it, you don't even get a hint as to where they might be.

I suggest we make anything they hold visible, and having them be stunned should disable their invisibility so that they're not completely unbeatable.

### LINKED ISSUE #8756: Ninja stealth doesn't turn off at 0 power, can be used whenever
Though it drains the battery, there's nothing stopping ninja stealth from draining it into negative numbers and so it can effectively be left on forever if you don't mind never using any other powers.

Even if you turn it off you can turn it back on even if you have no/negative power.

### LINKED ISSUE #10148: Ninjas don't unstealth when they reach 0 energy
And they're at alpha 0, so they're invisible murder machines that can only be bombed.

### PR DESCRIPTION
**Pull request by RemieRichards**
- Ninja invisibility now turns off when charge is <= 0
- Ninja invisibility now only turns on if the cell has charge
- Ninja cloaking/uncloaking effects moved from ancient anim() proc to byond's animate() proc

Fixes #8756
Fixes #10148 
Fixes #8249 - Well not really, but this isn't true any more (at all?)

### CODE REVIEW

**Comment by Anonus** [comment]
Does not fix 8691; they're still alpha=0, thus unfindable, and can shit armor-ignoring stars.

**Comment by WJohn** [comment]
should make em alpha 1/255 or something, at the very least so you can click on them.

**Comment by Anonus** [comment]
You CAN click on them at 0 alpha, but there's literally no indication of where they are and that's hilarious bullshit.

**Comment by Dorsisdwarf** [comment]
Remie, this fixes #8756 as well

**Comment by Razharas** [comment]
@RemieRichards Please adress anonus worries

**Comment by phil235** [comment]
I removed the reference to 8691 in the OP.

**Pull request merged**
