### PR TITLE
[MAP] Replaces The White Ship With Meta's Recovery Ship

### PR DESCRIPTION
**Pull request by Steelpoint**
This might be a contentious PR.

This PR replaces the abandoned White Ship with Metastation's Recovery Ship.

Ingame image of the Rec Ship.
screenshot 2015-07-28 00 38 57

Changelog Included

### CODE REVIEW

**Comment by Xhuis** [comment]
I quite liked rounds where the white ship was renovated and put back to use. That said, I think that Sybil's playerbase prefers new constructions rather than being able to do a few changes and have a fully running ship again.

**Comment by Steelpoint** [comment]
Link to feedback thread: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4278

**Comment by WJohn** [comment]
Please stop with all these map edits you're only hurting yourself when older stuff will get merged and you'll have to fight conflicts.

**Comment by Cheridan** [comment]
white ship is iconic and thematic and archetypal!

**Comment by Steelpoint** [comment]
This PR only touches the fourth Z-level.

My other PR touches the station z-level and the mining z-level.

They do not overlap and thus won't cause problems when/if they are merged/

**Comment by Miauw62** [comment]
i actually prefer the white ship. this one is already really crowded, white ship takes more work and has more space.

**Comment by Steelpoint** [comment]
In game I think the ships actually quite nice to move around in.

As I stated on the feedback thread, if we think there's too many items on this ship I can remove some of them.

**Comment by Jalleo** [comment]
Remove some of the machines, all the vendors and some of the crates at least.
Scattering about the items and essentially emptying the tiny eva section could help make it better.
Have you test how well it docks with the station?

**Comment by Lumipharon** [comment]
The box white ship is quirky, but it's an autistic and retarded layout.
Meta ship is much nicer, but it's cluttered with way too many machines/crates/etc.

Also I've never seen anyone but me bother to fully setup the box white ship, so I don't think that's an issue.

Lastly, on meta, this ship doesn't actually replace the box white ship.
They both co-exist on z4, but the box one cannot move on meta.

**Comment by optimumtact** [comment]
Why can't we have both?

**Comment by freerealestate** [comment]
I'm kind of attached to the white ship, despite it being ugly and having few purposes.

This ship just looks like you're giving players too many items, accessed a lot easier than they'd be on-station.

**Comment by Jordie0608** [comment]
You'll have to change the airlocks at the whiteship's dock on Box, they don't align very well with this ship itself. When moved to the asteroid level there's also only a single tile of empty space between this ship and the asteroid itself, it may be prudent to move the port over a bit. All the other z's ports with this ship do fit however.

**Comment by Lumipharon** [comment]
Please merge.
The box white ship sucks poop - if people have issues with the content of the ship or whatever, that can easily be changed after the fact, if people start rushing the ship every round to get a space suit (in space) or whatever.

**Comment by Razharas** [comment]
Cheri said old shit is iconic
Miauw said he prefers old too
None else cares
So - denied

**Pull request closed without merging**
