### PR TITLE
Removes intentional ling check in health analyzer

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Advanced health analyzers have an intended ling check which tells you if the scanned body is faking death (is in regen stasis), which is at odds with the rest of the codebase (which actively removes unintentional ling checks and blocks the addition of intentional ones).

This PR removes it (making advanced analyzers unable to determine if the target is faking death). 
Also tweaks some code around it in general.

## Why It's Good For The Game

I'm actually like 50/50 on whether this should actually be removed or not, so I opened the PR for discussion.

On one hand I think it's kind of interesting to have a doctor look at the results *closely* and realize something is wrong here.
On the other hand, ling check bad?

## Changelog

:cl: Melbert
del: Advanced Health Analyzers can no longer be used to determine if a body is faking death (like a changeling) 
/:cl:

### CODE REVIEW

**Comment by zoomachina** [comment]
Streisand effect

**Comment by timothymtorres** [comment]
What about regen coma?

https://github.com/tgstation/tgstation/blob/858d488990f22c3a7f05574d29d1aa46b205103f/code/modules/mob/living/status_procs.dm#L526-L538

**Comment by MrMelbert** [comment]
it's the same effect

**Comment by timothymtorres** [comment]
So the ling check isn't 100% but it's still pretty much a smoking gun indicator unless Viro has released a healing virus to the masses.

**Comment by Bibarra** [comment]
Not sure how the check survived this long. Why on earth would you ever want a dead giveaway that the person is a ling? They kinda have it bad enough as it is...

**Comment by ExcessiveUseOfCobblestone** [comment]
Id rather just say no exceptions, antag tests are bad.

I hate combat lings so I dont want to squash a ling making use of their more flavorful mechanics.

**Pull request merged**
