### PR TITLE
Adds a revolutionary conversion stinger

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

Adds an antagonist gain stinger for Revolutionaries, created with inspiration from the obsessed/traitor conversion sounds.

https://user-images.githubusercontent.com/28870487/235028674-170a4f9e-a873-4938-a700-536f005e539f.mp4

Raw audio:

https://cdn.discordapp.com/attachments/440978216484732934/1101964419203862548/revolutionary_tide.ogg

_A distant, hypnotic whistling. The heavy footfalls and clamoring voices of an approaching crowd. The unstoppable revolutionary tide breaks its waves upon an unsuspecting station._

I wanted to try and make something that felt like it fit in with the other antagonist stingers we already have. Let me know what you think!

## Why It's Good For The Game

Gives a bit more flavor, and helps set the mood for the upcoming bloodbath. 

## Changelog

:cl:
sound: Revolutionaries now have their own stinger that plays upon becoming that antagonist.
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
We were going to just add the internationale audio file #65885, but this is much better and really fits the game

**Comment by san7890** [comment]
it's really shrill...

**Comment by DrDiasyl** [comment]
I would say this is too eerie for a revolution, I would've preferred something more, well, _revolutionary._ But this is better then nothing so like anyway

**Comment by BlueMemesauce** [comment]
A crowd of people shouting seems pretty revolutionary to me. And the dark tone of it fits the gamemode as it's the syndicate hypnotizing people to fight to the death. 
What else would be more revolutionary in audio form? There's the Internationale but we tried that already, there's no good copyright free version of it that isn't just a midi file.

**Comment by DrDiasyl** [comment]
> A crowd of people shouting seems pretty revolutionary to me. And the dark tone of it fits the gamemode as it's the syndicate hypnotizing people to fight to the death. 
> What else would be more revolutionary in audio form? There's the Internationale but we tried that already, there's no good copyright free version of it that isn't just a midi file.

We can just make our own version using the midi, at least I can

**Comment by Cheshify** [comment]
God the high tones in that are agonizing on the ear, can you find a different sound or remove that really harsh tone?

**Comment by Rex9001** [comment]
The starting high tone is very very shrill, like soulpiercingly shrill

**Comment by SomeoneYouProbablyKnow** [comment]
Yeah the whistle is just too much. I feel like the crowds are enough and they don't give you ear damage. But yea good idea

**Comment by BlueMemesauce** [comment]
Maybe I just have good headphones but you guys are kind of exaggerating, remember this just plays once you become a revolutionary. Yes if it played over and over like fire alarms it would be annoying but that doesn't mean every other sound also has to be a low pitched drone.

**Comment by DrDiasyl** [comment]
> Maybe I just have good headphones but you guys are kind of exaggerating, remember this just plays once you become a revolutionary. Yes if it played over and over like fire alarms it would be annoying but that doesn't mean every other sound also has to be a low pitched drone.

We really should care for the health of our ears, even flashbangs are not that high pitched.

**Comment by Iamgoofball** [comment]
@Rhials any chance we can mix the internationale in there

**Comment by HoodMilk** [comment]
the rev stinger should should like yugoslav war music or some national anthem

**Comment by BlueMemesauce** [comment]
> > Maybe I just have good headphones but you guys are kind of exaggerating, remember this just plays once you become a revolutionary. Yes if it played over and over like fire alarms it would be annoying but that doesn't mean every other sound also has to be a low pitched drone.
> 
> We really should care for the health of our ears, even flashbangs are not that high pitched.

image

Flashbangs are MUCH higher pitched

**Comment by DrDiasyl** [comment]
> > > Maybe I just have good headphones but you guys are kind of exaggerating, remember this just plays once you become a revolutionary. Yes if it played over and over like fire alarms it would be annoying but that doesn't mean every other sound also has to be a low pitched drone.
> > 
> > We really should care for the health of our ears, even flashbangs are not that high pitched.
> 
> image
> 
> Flashbangs are MUCH higher pitched

Just the flashbang has the whole spectrum, while this sting has only high pitches making it really sharp

**Comment by celulamp** [comment]
it should just be like che guvera talking

**Comment by Addust** [comment]
playing on turf means that if anyone's resting on your tile and dynamic suddenly says 'FUCK YOU ANTAG' then suddenly they know you are indeed collaborating with the syndicate coalition to attempt to destroy or take over the station, or in north star's case a ship, or in icebox's case a piece of shit chunk of metal in siberia

**Comment by BlueMemesauce** [comment]
Not really a problem with this pr its just following what the other antags currently do. But we should definitely change that if its an actual issue

**Comment by Iamgoofball** [comment]
playsound_local only plays to the person who is receiving the sound; the location is to set the sound's position in 3d space for the 3d audio

**Review by san7890 — CHANGES_REQUESTED** [review]
the whistle itself isn't so bad anymore but the crowd yelling and chattering just gets really bad especially near the end sadly

**Comment by BlueMemesauce** [comment]
> the whistle itself isn't so bad anymore but the crowd yelling and chattering just gets really bad especially near the end sadly

that's because of their recording software btw

**Comment by san7890** [comment]
> > the whistle itself isn't so bad anymore but the crowd yelling and chattering just gets really bad especially near the end sadly
> 
> Alrighty, idk how much of that is a result of my recording (the audio in the video sounds noticeably worse than the actual .ogg to me and this website won't let me upload that file format) but I'd rather not add something if it might be considered grating. Back into the oven this goes.

do you not have https://file.house access? ask oranges or something (even though I can download it through github, i believe it will embed in the browser via his CDN?). i based it off the video

**Comment by san7890** [comment]
you could even just use the cdn discord link

**Comment by Shadowflame909** [comment]
Anyone else think this was a changeling buff that allowed them to cause some paranoia by temporarily and revolutionizing folks via a stealth stinger that'd wear off very quickly? Just me?

Still cool though.

**Comment by san7890** [comment]
yeah it's less annoying than when i was viewing it through the screen recording but the portion when the crowd is speaking from 0:05 to 0:08 becomes way too discordant to be a fun cool stinger that settles you into the role. it just feels bleaugh in that aspect, especially in comparison to the really cool and straight-lined traitor stinger "WEW LAD" (as well as the similar nukie one) or the cult stinger, which has a lot of weird writhing noises with some high peaks while still managing to be very atmospheric and interesting. it walks a _very_ straight line.

the whistle at the beginning of the stinger is pretty cool and the impending marching footsteps are really neat, but man oh man i just can't get past that six-second mark. listening to the rest of the stingers, they're very simple yet good. they typically don't have more than two overlaying sounds, and each different "segment" in that stinger has it's own crispness that doesn't really make that unpleasant "collision sound". Like it's the drums bang-bang-banging, while the robotic voice slowly spits out "Whiskey... Echo... Whiskey...", or the changeling one where it plays a really high (and shrill) tone with squelching and screaming of the slug playing over it. however, it paces itself out. it has the background tone and then screams/hisses/squelching/etc. everything is taking it's time...

i don't know if/how you can make it work with what you want with desiring the chants of an overlapping crowd, but it just really detracts from how straight-laced the rest of the stingers are... because i think the overlapping cacophony (just describing what i think of it) just isn't that great... maybe instead of discordant and plastered yelling, you could have the crowd chanting? or something like phrases like the malf ai stinger? i'm not really certain on all of this myself but i do know that there is a certain design direction that's been done with stingers so far (backings with only one sound effect layered on top (i think)) and the ones used for that patch in the middle just aren't my thing really.

i don't have any hearing disabilities for the record, in case some people are wondering about that

**Comment by san7890** [comment]
simple things when executed well are great

**Comment by Rhials** [comment]
Picked this back up because it sort of slipped my mind and I didn't want it to die

I ditched the overlapping yelling because I couldn't really make it sound any better or less messy. I think it works fine with just the whistle, drums, and marching

Lemme know what you think

https://cdn.discordapp.com/attachments/440978216484732934/1108131923689222245/revolutionary_tide.ogg

**Comment by san7890** [comment]
yeah that's way better now. if you ever want to make it more intricate at a later date go ahead

**Pull request merged**
