### PR TITLE
Durathread and loom changes.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Some durathread recipes can now be made with stackcrafting.
Durathread is no longer a cloth subtype.
The fabric variables have been removed from sheets. They are now exclusive to cotton sheets and it's subtypes.
The loom can now be unwrenched.
Fixed a bug where you get more cloth with the loom than you should have.

## Why It's Good For The Game

Makes the loom and its products just a little less cluncky to use. Slighly improves code quality.

## Changelog
:cl:
add: You can now unfasten the loom.
code: Various changes to the loom and its products.
fix:  You can no longer get more cloth from the loom than you should be able to.
/:cl:

### CODE REVIEW

**Comment by Yttriums** [comment]
Would be cool if durathread could get a buff to bullet resistance so botanists might mass-produce it for war ops. I'm not sure if it's supposed to be kevlar-style fabric though.

**Comment by nemvar** [comment]
Buff it yourself. I'm out of the balance department for now.

**Comment by WaterStBlues** [comment]
Test to make sure this doesn't fuck with golems

**Comment by nemvar** [comment]
I already made sure that durathread golems can still be made. Not sure what else could possibly break.

**Pull request merged**
