### PR TITLE
Removes usage of set background

### PR DESCRIPTION
**Pull request by Cyberboss**
We don't use it

### CODE REVIEW

**Comment by optimumtact** [comment]
\>we don't use it

isn't it clear that it's at least set, how do you determine it's not being used

**Comment by Cyberboss** [comment]
BACKGROUND_ENABLED has been 0 forever so none of those matter. The things that do have it set is 1 crappily written SNPC proc and some garbage stuff that's only enabled in TESTING but has world.loop_checks set to FALSE so it wouldn't matter anyway. I could care less about SNPCs

**Comment by optimumtact** [comment]
okay

**Comment by MrStonedOne** [comment]
`set background = 1` inserts a `sleep(-1)` to the body of every loop in the proc.

that's all it does. 

sleep(-1) seems to only sleep once world.tick_usage gets to anywhere between 450%  and 1350%

**Pull request merged**
