### PR TITLE
Revert "Prevent people from setting FILE_DIR"

### PR DESCRIPTION
**Pull request by Shadowlight213**
Because new people setting FILE_DIR once is way less annoying than people having to deal with a BYOND internals file that changes every single time you use Dreammaker being tracked by the repo and trying to get commited.

### CODE REVIEW

**Comment by JJRcop** [comment]
Funny, ```*.int``` is in the [.gitignore](https://github.com/tgstation/-tg-station/blob/e036b084dc95ca2abfa958a913044a1fe2d82658/.gitignore) file not once but twice.

**Comment by Shadowlight213** [comment]
Jordie added it accidentally.

**Comment by JJRcop** [comment]
Just kinda weird how uh, it's not supposed to track tgstation.int because of the file, does it keep happening?

**Comment by Jordie0608** [comment]
See #12288, the ignore doesn't work for commited files it seems.

**Comment by optimumtact** [comment]
Also travis will complain if they ever do set it.

**Comment by Giacom** [comment]
Might be worth trying:

>[git update-index --assume-unchanged](https://git-scm.com/docs/git-update-index#_using_assume_unchanged_bit) tgstation.int

But I recommend you test it in the currently workflow to make sure it doesn't break anything.

**Comment by optimumtact** [comment]
@Giacom that only works locally, so the setting isn't carried across forks and other peoples repositories unfortunately.

**Comment by JJRcop** [comment]
We could always make something that stops compilation if there are FILE_DIR definitions in tgstation.dme. Doesn't even need to be a travis thing, so that way you just flat out will never be able to compile with FILE_DIRs.

**Comment by MrPerson** [comment]
How? I've tried #if defined(FILE_DIR) but it's always set

**Comment by optimumtact** [comment]
just rely on travis

@RemieRichards @Aranclanos @Cheridan @Giacom @Ergovisavi @Razharas MERGE LIKE THE WINDOW

**Comment by JJRcop** [comment]
I mean more... scanning tgstation.dme
might sound ugly but

**Pull request merged**
