### PR TITLE
Makes medkits SOULLESS

### PR DESCRIPTION
**Pull request by bigfatbananacyclops**
Closes #45276 
## About The Pull Request

Resprites medkits to fit with the new sprite's dimension.
Removed the other medkits with different symbols.

Centcom has ordered a change to the medkits due to them looking ugly & very unreinforced, the cases KEEP breaking!!

Now with reinforced durable corners to protect the medkit from any blast,(they are also... quite.. big.. not much tbh)

## Why It's Good For The Game
I kept the old medkit sprites if anyone is going to use them, their name begins with old, but anyways, i resprited them so the medkits can fit with the new dimension sprites, they're now soulless.

I also wanted to state the reason i removed the kits with symbols, the most common mark for a aid is the +, the rad symbols look very strange on the kits and i'd assume some medical amateurs or new players could confuse this and not know what it meant.

i will post a pic of how they look in game soon
## Changelog
:cl:
imageadd: revamped medkit sprites
/:cl:

edit: made medkits sprites smaller, this are the results, i also made some kit's colors brighter.

reinforced kits

pixil-frame-0 (10)
pixil-frame-0 (11)
pixil-frame-0 (12)
pixil-frame-0 (13)
pixil-frame-0 (14)
pixil-frame-0 (15)
pixil-frame-0 (16)
pixil-frame-0 (17)
pixil-frame-0 (18)
pixil-frame-0 (19)
pixil-frame-0 (20)
pixil-frame-0 (21)
pixil-frame-0 (9)

### CODE REVIEW

**Comment by Detective-Google** [comment]
These sprites look really good 10/10 ow ouch oof my soul

**Comment by actioninja** [comment]
I'm fucking banning you for delete soul, awful, 0/10

**Review by actioninja — DISMISSED** [review]

**Comment by Dawson1917** [comment]
These look less like medkits and more like health pickups from a 90s shooter

**Comment by YakumoChen** [comment]
at least sprite the alt symbols instead of just deleting them

**Comment by MrPerson** [comment]
Please get rid of the red cross on the berserk kit.

**Comment by wesoda25** [comment]
I honestly think they are good sprites, but I don't think they match the tg aesthetic at all. They are like dark and moody sprites, which would look good on a server like CM, but not on tg. It just clashes too much with all of our bright sprites.

**Comment by bigfatbananacyclops** [comment]
What about the red cross?

**Comment by Dawson1917** [comment]
They look too rugged and combat-ready for what SHOULD be general medical supplies for accidents on a totally safe and maintained space station. You could probably drive a car over one of these without denting the case

**Comment by bigfatbananacyclops** [comment]
They’re meant to be chunky plastic kits

**Comment by MrPerson** [comment]
Two reasons. One, Doom itself actually patched the berserk kit to look different. Two, more importantly, using a red cross like that [violates the Geneva Convention](https://www.digitaltrends.com/gaming/video-game-red-cross-health-pack-emblem/)

**Comment by bigfatbananacyclops** [comment]
@MrPerson sure ill change it

**Comment by bigfatbananacyclops** [comment]
Replaced the bezerk kit with a black kit containing a dark blue cross

**Comment by FloranOtten** [comment]
Looks far to reinforced. If these sprites are merged I expect Doctors to be able to craft an empty kit into makeshift body armour.

**Comment by ExcessiveUseOfCobblestone** [comment]
Would be nice if we could replace the blue cross with little icons that depict what damage it heals.

At the very least the radiation kit should have it (as it did previously) since red is associated more with brute.

**Comment by Dorsisdwarf** [comment]
I dont like the shading on the yellow one but the rest are alright

**Comment by bigfatbananacyclops** [comment]
@excessiveuseofcobbleatone which icons?

**Comment by bigfatbananacyclops** [comment]
@ExcessiveUseofcobblestone im not sure with what icons i could use for brute & rad tbh

**Comment by MrPerson** [comment]
While having icons to represent things is good in general, that might be a more generalized discussion for later on

**Comment by PKPenguin321** [comment]
Could just do a bandage for brute and one of these for rads:
image

**Comment by Krysonism** [comment]
> 
> 
> Could just do a bandage for brute and one of these for rads:

Do we have enough pixels?

**Comment by PKPenguin321** [comment]
Also just my personal opinion but these would look better without the weird shaded corners, they add a lot of visual clutter on what should be a simple container
I did a quick repaint of the brute one to show what I mean (I understand it's really flat looking but it's not supposed to be a final draft, made it in like a minute)
flat
comparison

**Comment by YakumoChen** [comment]
wait, is it a companion cube reference now?

**Comment by bigfatbananacyclops** [comment]
final fucking edit, made reinforced corners little shorter, made it a little more wide, now im gonna sit and just see results and see who wins

**Comment by ExcessiveUseOfCobblestone** [comment]
I plan on merging the other one, but do you mind PRing these to

https://github.com/tgstation/SS13-sprites

so someone can add these later if they find a good use for them?

**Comment by bigfatbananacyclops** [comment]
sure

**Pull request closed without merging**
