### PR TITLE
Adds My Bar Sign From The Contest

### PR DESCRIPTION
**Pull request by kaylexis**
## About The Pull Request

adds "the rune" bar sign i created for the bar sign contest
 
## Changelog

:cl:
add: Cool bar sign
/:cl:

therunebarsign

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
very cool animation!

**Comment by JohnFulpWillard** [comment]
Lol, lmao

**Comment by jughu** [comment]
Screenshot_20231105-234719_Discord

**Comment by DrDiasyl** [comment]
Literally 1984

**Comment by optimumtact** [comment]
For anyone reading this was closed because the guy making it was kind of a dickhead in the chat channels.

**Pull request closed without merging**
