### PR TITLE
Adds a unique background for admin TGUI menus

### PR DESCRIPTION
**Pull request by ghost**
:cl:
admin: Admin only menus now have a new SVG background
/:cl:

I figured admin UIs could use a unique SVG background. I think it really represents the admin spirit

image

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Make it so we can toggle between that and the NT one and we've got a deal :^)

**Comment by AMonkeyThatCodes** [comment]
umm-no-kenan-thompson

**Comment by Thunder12345** [comment]
I love it it’s perfect

**Comment by Timberpoes** [comment]
Screenshot_20210915-140655_Discord

Democracy has spoken.

**Comment by AMonkeyThatCodes** [comment]
the secret admin cabal picked my side for once

**Pull request merged**
