### PR TITLE
Modular shield gen tweaks, feedback, and now interacts with explosions

### PR DESCRIPTION
**Pull request by moocowswag**
## About The Pull Request
Shield itself now has explosion block of 3

Explosions now have potential to do massive damage to the shield (upwards of 800 on a large explosion depending on how big/flat the shield is)
I wanted to make it so explosions dont go through the shield unless they destroy it but thats not possible with the way explosions are currently done, i took a deep dive into explosion code and its...due for a rework that even i might try.

Scaling on regen is up by 20% , max strength up by 25%, flat increase to max radius by 2 (Please see justifications for this and offer ideas for stat changes of your own if you want)

Description of the shield tiles and attack feedback are updated to make it more clear that you can in fact go gorilla mode on them.
## Why It's Good For The Game
Okay so modular shield generators have been in the game for a week these are my observations at how they have been performing within the game.

What im happy with currently
+ Its very hard but possible to make a very large forcefield and the penalty to the regeneration rate makes it a tradeoff, large forcefields will also be more susceptible to explosions because they are flatter and easier to hit multiple shield tiles with the dev and heavy parts of an explosion.

+ Its not something you can easily cook book. Even I dont know the perfect ratios of how many relays i should have to chargers at each radius setting if i want to get the perfect regen rate.

+ Its not hard to improve an existing shield generator just expand in a direction that has space and fill empty spots to a node, many people can cooperate with building one.

+ People found it cool and interesting without it being something that involves killing/round removing

What I`m not happy with
 + People keep thinking that its immortal because there isnt enough tell tale signs that its actually vulnerable and even fragile.
   
  I addressed this by giving the shield a better description and better feedback when you hit it.

 + Its too daunting for players to learn how to use it, especially when committing to it is both resource and time intensive.
    
I addressed this by buffing the starting max radius value by 2 to make it so players won`t have to learn how to build and connect relays to it in order for it to be any useful against meteors. Relays are still necessary for protecting a large area but individual generators should be at least somewhat viable to raise the skill/knowledge floor.

+ I underestimated not only the damage everyone is capable of doing to the shields due to them being subject to obj damage/demolition modifiers, I also underestimated the actual cost and time to build a shield that rivals even something as weak as glass.

    I upped the scaling on the max health and regeneration slightly, its probably not enough but I dont want to do anything other than small increments.
## Changelog
:cl:
balance: Modular shield generators are now slightly more potent and able to interact with explosions, while also being more clear about how fragile they are.
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
do not merge unless https://github.com/tgstation/tgstation/issues/75793 is fixed and I test it afterwards or else it will break explosions.

**Comment by moocowswag** [comment]
Fix pr is merged ill test later today

**Comment by moocowswag** [comment]
confirmed the blast protection properly updates on gain/loss of the shield.

**Comment by moocowswag** [comment]
https://github.com/tgstation/tgstation/assets/62126254/4c775060-5a78-43cf-9f01-47976b3b780e


https://github.com/tgstation/tgstation/assets/62126254/4e40642c-eb7f-4eea-9754-4fdcb0e69e19

proof of testing

**Comment by Sealed101** [comment]
not exactly in the scope of a balance PRbut there were some runtimes going around with the modular shields, round 208399

hi

**Comment by moocowswag** [comment]
So there is issues with having one on a shuttle?

**Comment by moocowswag** [comment]
Anturik said i should work on the damage procs themselves to deal with the "without leaving a mark!"

**Comment by moocowswag** [comment]
im gonna just atomize this some more and revisit it later.

**Pull request closed without merging**
