### PR TITLE
Remove xylophone skeleton ribcage playing

### PR DESCRIPTION
**Pull request by MrPerson**

### CODE REVIEW

**Comment by Incoming5643** [comment]
:-1:

**Comment by GunHog** [comment]
Why are you removing this? You have not even provided a reason!

**Comment by Nienhaus** [comment]
Did you like, keep the sounds in the files for no reason?

**Comment by Miauw62** [comment]
literally removing fun :-1:

**Comment by hornygranny** [comment]
it's shitcode

**Comment by Fox-McCloud** [comment]
:-1: 

it's shitremoval

**Comment by Iamgoofball** [comment]
:-1:

**Comment by MrPerson** [comment]
If someone wants to rewrite this in an object oriented way, be my guest, but I'm not. Basically, the mutation should be in charge of handling the xylophone music playing, not the mob.

**Comment by Iamgoofball** [comment]
I'll check it out then.

**Comment by kevinz000** [comment]
I see its no fun allowed.
:-1:

**Comment by Incoming5643** [comment]
optimally the removal pull and the recode should just be the same pull

**Comment by Steelpoint** [comment]
I think its a amusing feature :-1:

**Comment by PKPenguin321** [comment]
:-1: 
improve not remove
if it's shitcode then fix it

**Comment by stapler2025** [comment]
woohoo removing things for the sake of removing them.

really tired of coderbus removing things rather than fixing things, let alone things that aren't broken.

**Comment by optimumtact** [comment]
s/coderbus/MrPerson/g

Thank you very much, I'm against this as much as you are

**Comment by Chocobro** [comment]
:-1: no thanks

**Comment by Giacom** [comment]
Ha, I remember when Erro coded this. Everyone was complaining about it back then too. I think it was back in SVN days so there weren't any code reviews.

I think trying to implement triggers for the mutant datums, instead of removing the feature, would be in everyone's interest.

**Comment by Aranclanos** [comment]
:+1:  I also remember, but listen to gia

**Comment by optimumtact** [comment]
I think Gia did have the right idea here, removing it just seems petty

**Comment by PKPenguin321** [comment]
>removing instead of fixing

literally why

**Comment by hornygranny** [comment]
mutation triggers is on the agenda after april fools

**Pull request merged**
