### PR TITLE
Fixes some awful defines to not be hacks

### PR DESCRIPTION
**Pull request by MrPerson**

### CODE REVIEW

**Comment by tkdrg** [comment]
I don't mind these, honestly.

**Comment by MrStonedOne** [comment]
na, leave these be, defines shouldn't stretch byond syntax

**Comment by optimumtact** [comment]
It makes it non obvious that the array is 2d

**Comment by duncathan** [comment]
ur awful
if another maintainer disagrees feel free to reopen

**Comment by duncathan** [comment]
lemme give a better explanation
The defines are like this to save the effort of typing out several defines just to get one value. Yes, it hides the dimensions of the list, but I don't believe that this info is needed to the average coder using the list. The internals of listmos aren't something everyone cares about or needs to see. If someone is changing how it works, these defines will mean they only really have to change one spot instead of many all over the code.

**Comment by MrPerson** [comment]
But if someone does want to edit the list, it's better to have all the information readily accessible instead of needing to decode the defines.

Just for reference, dupe of #14820 and #14821

**Comment by duncathan** [comment]
They'd need to look at the defines regardless of whether this change goes through.

**Comment by optimumtact** [comment]
kinda feels like you're rage maintaining your own code

**Comment by MrStonedOne** [comment]
>kinda feels like you're rage maintaining your own code

**Comment by MrPerson** [comment]
Doing the "var accesses" this way makes them incredibly confusing to read. I know you can't tell because the system is "simple" to you because you wrote it, but I assure you that obfuscating the code like this to save you a minute or two is in no way worth it.

**Comment by Razharas** [comment]
Code should be as self-explanatory as possible
This includes showing the dimentionality of a list
Every time

**Comment by Razharas** [comment]
@Cheridan 
We have a maintainer conflict of opinions, please decide

**Comment by Cheridan** [comment]
I agree with @oranges and @MrPerson

**Pull request merged**
