### PR TITLE
FIXES A COMMENT IN HIGHLANDER CLAYMORE NOT BEING IN ALL CAPS!!!!

### PR DESCRIPTION
**Pull request by Fikou**
## ABOUT THE PULL REQUEST

ON THE 18TH OF SEPTEMBER 2019 SPOOKYDONUT BROKE THE SACRED RULE OF HAVING ALL COMMENTS ON THE HIGHLANDER CLAYMORE BE IN ALL CAPS
I WILL FIX WHAT HAPPENED ON THIS SAD DAY WITH THIS PR

## WHY ITS GOOD FOR THE GAME

WE MUST RESTORE BALANCE TO THE WORLD

### CODE REVIEW

**Comment by trollbreeder** [comment]
FOR SCOTLAND!
FOR VALHALLA AND GLORY!!!

**Comment by mrhugo13** [comment]
SMH SPOOKYDONUT YOU CAN'T EVEN DO YOUR JOB RIGHT

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by Iamgoofball** [comment]
I DUNNO ORANGES IT LOOKS LIKE HE EXPLAINED WHAT HE DID IN THE PR DESCRIPTION

**Comment by optimumtact** [comment]
luckily that's not the only thing this template covers

**Pull request merged**
