### PR TITLE
Dynamic configuration file (also fixes prefs&ban checks).

### PR DESCRIPTION
**Pull request by TheChosenEvilOne**
## About The Pull Request
Added JSON configuration loading for dynamic ruleset settings. This allows changing dynamic ruleset settings without having to modify the code itself to change it.
Also added an example configuration file with default traitor configurations.

## Changelog
:cl:
add: Dynamic now loads server specific configurations from a defined configuration file.
fix: Antagonist preferences and bans work correctly again in dynamic.
config: DYNAMIC_CONFIG_ENABLED has been added to game_options.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Why is this json, we have a config system already and it's a lot easier to write config options in it than making formatted json, this seems a little lazy to me

**Comment by TheChosenEvilOne** [comment]
> 
> 
> Why is this json, we have a config system already and it's a lot easier to write config options in it than making formatted json, this seems a little lazy to me

I don't really want to make an entry for every single variable that can be edited and even more so when there are ruleset specific variables.

**Comment by Jordie0608** [comment]
Why a config for location of the file? Is this to permit changing the config by swapping out the file? It's not bad but I'm doubtful that would get used much.

**Comment by optimumtact** [comment]
you are a double chumbis my friend

**Comment by TheChosenEvilOne** [comment]
> 
> 
> Why a config for location of the file? Is this to permit changing the config by swapping out the file? It's not bad but I'm doubtful that would get used much.

Well, I will just remove it then.

**Pull request merged**
