### PR TITLE
Makes reinforced floors shinier.

### PR DESCRIPTION
**Pull request by WJohn**
So ultimately I think these really were better, because after looking at the current ones in game for a while it's actually kind of hard to notice the hexagon pattern because it's all very dark. These have that little bit of flare to help sell them as *metal.*

:cl: WJohnston
imageadd: Reinforced floors are now shinier.
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
I feel like it'd be better to make them lighter, to closer match the old floors, instead.

**Comment by MrDoomBringer** [comment]
noooo they look wet

**Comment by WJohn** [comment]
These are the same ones as last time in #39782

**Comment by Iamgoofball** [comment]
@MrDoomBringer spritebot does it for you

**Comment by TheDreamweaver** [comment]
Hopefully we can convert reinforced walls over to this art style soon as well.

**Pull request merged**
