### PR TITLE
Allows StockParts to be Created by Medical and Cargo

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Allows StockParts to be Created by Medical and Cargo

## Why It's Good For The Game
It's never made sense to me that medical has access to certain circuits but is unable to build them themselves. Forcing medical staff to go back and forth from science to retrieve stock parts.

This will now allow medical and Cargo to customize their workspace.

## Changelog
:cl:
Allows StockParts to be Created by Medical and Cargo
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
The point is so that medical and science departments talk to each other and cooperate.

**Comment by ShizCalev** [comment]
No here for the same reason as well.

**Comment by Winterous** [comment]
I'd say they should only get the basic parts, if at all.

**Comment by Axanthic** [comment]
I get that but I think that it would give medical more to do, I think the part system is already a pain in the ass.
What does a sleeper bed need? Well unless you put the circuit in and examine you better have it memorized.

Should Sci do multiple upgrades whenever a new tier of stock parts come out?
I think the fact it's rare to see anything built in medical along with chem dispensers upgraded is evidence that the current inter-department cooperation is too heavy.

Compared to botany and chemistry working together where it's a one time thing and always the same need I think this puts too much of a strain on medical.

**Comment by Jared-Fogle** [comment]
>  I think the fact it's rare to see anything built in medical along with chem dispensers upgraded is evidence that the current inter-department cooperation is too heavy.

This is a player problem, not a code problem. I regularly am able to coordinate with science on building things like stasis beds.

**Comment by ATH1909** [comment]
Only giving them access to basic stock parts would be fine, IMO.

**Comment by Tlaltecuhtli** [comment]
autolathe can print em 
 you can also buy them from the vendomat if you need 2-3 parts in the case of cargo, engi , sci happened to be nuked

**Comment by Pugie** [comment]
god imagine stock parts only printable at sci and engi, specific boards printed at techlathes and circuit imprinters outright removed... sounds like a heaven game

**Comment by nightred** [comment]
> god imagine stock parts only printable at sci and engi, specific boards printed at techlathes and circuit imprinters outright removed... sounds like a heaven game

Sounds like a single player game.

**Comment by qlpt** [comment]
A better solution would be to add a machine next to the R&D front desk that can be loaded with parts and will dispense them for money. The money goes into R&D's department budget. This allows players from other departments to get their hands on upgraded stock parts easily, while still requiring R&D to make them available. It also forces players to leave their department to get the parts, which is always a good thing. At round start it should be stocked with T1 parts. 
Oh, and it would make money more important which is always a good thing.

I also think it would be a good thing to put T1 (and only T1) stock parts in the other techlathes, but since they're available from the vendomat already it's not hard to get them on a doctor's salary.

**Comment by Axanthic** [comment]
> A better solution would be to add a machine next to the R&D front desk that can be loaded with parts and will dispense them for money. The money goes into R&D's department budget. This allows players from other departments to get their hands on upgraded stock parts easily, while still requiring R&D to make them available. It also forces players to leave their department to get the parts, which is always a good thing. At round start it should be stocked with T1 parts.
> Oh, and it would make money more important which is always a good thing.
> 
> I also think it would be a good thing to put T1 (and only T1) stock parts in the other techlathes, but since they're available from the vendomat already it's not hard to get them on a doctor's salary.

> The point is so that medical, cargo and science departments talk to each other and cooperate, big no from me.

The other problem with this is you need a large amount of inventory space to transport the parts. Let alone open the wiki or begin building to determine the parts you need.



> > I think the fact it's rare to see anything built in medical along with chem dispensers upgraded is evidence that the current inter-department cooperation is too heavy.
> 
> This is a player problem, not a code problem. I regularly am able to coordinate with science on building things like stasis beds.

The thing is the effort involved is massive both ways, either sci has to be let in and out of multiple rooms and make changes that were unasked for by medical themselves or medical has to make a list of parts they'll need and hope someone from sci is willing give them said components.

This becomes more of a pain as the tech tree is unlocked causing multiple trips if you want to keep medical up to date with the best stuff.

Medical staff frequently afks when they're not injured people to heal. This would give them something else to do in the down time.

**Comment by qlpt** [comment]
You can just print the board and examine it to see what parts you need.

**Comment by Axanthic** [comment]
Fuck oranges
image

**Comment by ShizCalev** [comment]
re inventory space:
use a crate or closet.

**Pull request closed without merging**
