### PR TITLE
New Tactical Syndicate Bundle: Recon

### PR DESCRIPTION
**Pull request by ghost**
The purpose of this PR is to add a bundle with a unique play-style to spice things up, and to get players to use one criminally under purchased item: The briefcase launchpad. Also adds a new item, x-ray goggles.
Bundle contents:
1. Briefcase Launchpad
2. X-ray goggles (Same as traitor thermals but x-ray, and has no chameleon functionality. (Obviously syndicate on examine, distinctly red, reduces flash protection, and blinds on EMP))
3. Binoculars
4. Syndicate encryption key
5. Red space suit
6. Two frag grenades

The kit's play-style involves scouting out areas with x-ray and binoculars, then using the briefcase launchpad to invade or perform thefts. Two grenades are included, for self-defense in a pinch, or can be armed then teleported onto stationary targets.

### CODE REVIEW

**Comment by optimumtact** [comment]
I feel like we have enough kits already

**Comment by imsxz** [comment]
they got split into 2 groups recently so adding more to each isnt that bad imo

**Comment by OverlyGeneric** [comment]
> I feel like we have enough kits already

it's completely randomized. one for actual use and one for gimmicks because we need to limit the absolute fucking imagination of players.

**Comment by Eaglendia** [comment]
The special bundle is pretty inoffensive, though, especially since TC trades aren't exactly reliable if you want to try to do something really special, and there's plenty of shit in the uplink that barely gets used at all as-is. 

I'm all in favor of anything that speaks the gospel of Briefcase Launchpad.

**Comment by Tlaltecuhtli** [comment]
why not add something cool like a sniper rifle

**Comment by py01** [comment]
There is already a sniper bundle. Also, I wanted to make a kit that that promoted something other than the standard methods of combat- Point and click to make spaceman horizontal.

**Comment by Shadowflame909** [comment]
@optimumtact we need more things that aren't e-bow and e-sword


this is pretty great for that

**Pull request merged**
