### PR TITLE
nerfs mulebots

### PR DESCRIPTION
**Pull request by Iamgoofball**
okay so to be fair this was karmic retribution when I died but

> 3 hits to instant death

why would I ever not emag a mulebot with a pAI

### CODE REVIEW

**Comment by PKPenguin321** [comment]
overkill + feature freeze

**Comment by MMMiracles** [comment]
i could of sworn pAI-controlled mulebots had their run-over damage taken away for exactly this reason.

what mad man actually reverted that feature?

**Comment by PKPenguin321** [comment]
non-player mulebots should still be murdermonsters, player mulebots only should have significantly less damage (or a super short stun)

**Comment by Shadowlight213** [comment]
@MMMiracles iirc the issue was that PAI mulebots became sentient beepsky with just the stun but no damage.
Honestly, the best way to do it, is to make disabling safeties do nothing when the mulebot has a PAI, not when it has a client, like a previous pr. That way, sentient murdermule is still there for events, but it nerfs the pai.

**Comment by Jazaen** [comment]
Yeah, you could say that wen the safeties are disabled and if there is a pAI it just uses it's safeties. Or something.

**Comment by pudl** [comment]
Fun removal

**Comment by Core0verload** [comment]
How about we already add "no, mulebots are not getting nerfed" to our code policy?

**Comment by evsey9** [comment]
pAIs are already rare enough, let them shine for a bit.
Also, humans are faster than mulebots.
Bullets are surprisingly good againist mulebots.
Borgs can easily defeat mulebots.
Mulebots are weak in open spaces.

**Comment by MMMiracles** [comment]
mulebots have a guaranteed stun on anyone it hits followed by a 3-hit kill followup that you can literally do nothing about but bend over and accept the mule.

it isn't nearly as bad on non-sentient mulebots because it either requires someone manipulating the path system to drive it somewhat, if not at worst you'll get hit once by it and be left badly hurt to limp to medbay.

mulebots with sentience are like mobile crushers without the clothes shredding.

**Comment by phil235** [comment]
The issue is not the mulebot damage or stun amount, it's that the mulebot can be player controlled.
The damage and stun amount that the mulebot currently have is balanced for a use where the mulebot is not player controlled.

**Comment by callanrocks** [comment]
>  The damage and stun amount that the mulebot currently have is balanced for a use where the mulebot is not player controlled.

Then make it so player controlled mulebots don't get to bloodlust and can only give free rides?

**Comment by phil235** [comment]
>Then make it so player controlled mulebots don't get to bloodlust and can only give free rides?

Yeah, except this should've been done by the guy who made bots player controlled.

**Comment by Core0verload** [comment]
Except this is "i ded" at it's worst. How many times PRs like this were opened because someone got his ass raped by a mulebot-riding traitor?

We should start closing "i ded" PRs that already were denied. Because now you can just spam github with dumbass "i ded" nerfs until someone merges them.

**Comment by PKPenguin321** [comment]
this pr was opened immediately after goof went on a murder rampage with an admin only item he added to the game only to get killed on the shuttle by a mulebot so yeah it's literally "i ded"

**Comment by KorPhaeron** [comment]
This doesnt even fix the issue which is the bumpstun while ruining non player mulebots

**Comment by callanrocks** [comment]
> this pr was opened immediately after goof went on a murder rampage with an admin only item he added to the game only to get killed on the shuttle by a mulebot so yeah it's literally "i ded"

Premium goofcoding.

**Comment by Iamgoofball** [comment]
@callanrocks 
the wrasslin belt was SUPPOSED to be a traitor item but they didn't merge it until I made it admin only so rip

**Comment by Iamgoofball** [comment]
but yeah premium goofcoding

**Pull request closed without merging**
