### PR TITLE
Portals can no longer be frozen.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/tgstation/issues/21698.

Suggestions requested for

- Other stuff that shouldn't freeze
- Whether I should make FREEZEPROOF a define like lavaproof, and if so whether to do it under resistance flags or elsewhere, and if so how the fuck to do that

### CODE REVIEW

**Comment by AnturK** [comment]
The latter sounds like a reasonable solution

**Comment by Iamgoofball** [comment]
Stop doing realism """fixes""" only disable freezing on shit that has literal bugs

**Comment by XDTM** [comment]
Just because it doesn't affect gameplay doesn't mean it should be freezable

**Comment by ShadowDeath6** [comment]
when will GOOFPROOF be a variable?

**Comment by Mervill** [comment]
#define GOOFPROOF 512

**Comment by bgobandit** [comment]
it's a wormhole

why would it be frozen

it's a w o r m h o l e

**Comment by ChangelingRain** [comment]
Fire shouldn't freeze!

**Comment by optimumtact** [comment]
>Whether I should make FREEZEPROOF a define like lavaproof, and if so whether to do it under resistance flags or elsewhere, and if so how the fuck to do that

Yes

**Comment by bgobandit** [comment]
that doesn't answer the latter two parts

**Comment by optimumtact** [comment]
rebalance or feature

**Pull request merged**
