### PR TITLE
Hazard vest and rad suit resprite

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
Redoing my [last PR](https://github.com/tgstation/tgstation/pull/49662) since I'm apparently too much of a brainlet to fix that branch. This changes the hazard vest and rad suit sprites to better looking ones.

Old hazard vest:

New hazard vest:

Old rad suit:

New rad suit:

This is a port of [this PR](https://github.com/BeeStation/BeeStation-Hornet/pull/572). 

## Why It's Good For The Game

It look better than current sprites. 

## Changelog
:cl:
change: Changed hazard vest and rad suit sprites. 
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
You still haven’t fixed the radsuit sprite. It’s sidesprites are one pixel shorter than front/back.

**Comment by HomocidlePancakes** [comment]
Also, you haven’t closed your old PR, you goof.

**Comment by Victor239** [comment]
Ah gimme a min, it's closed now. Also I'm not a spriter I just hate looking at the current awful sprites.

**Comment by HomocidlePancakes** [comment]
This one pixel line triggers me so fucking much man.

**Comment by Rohesie** [comment]
Very nice. Post when you think the PR is ready, in case you are going to do changes.

**Comment by Victor239** [comment]
Alright I fixed the pixel line, but if this has a merge conflict again I swear to god..

**Pull request merged**
