### PR TITLE
[READY] Revamps PubbyStation Commons

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request
This pull completely revamps the Pubbystation commons area, turning it into a place that people will actually interact with.

It adds many different rooms and slightly expands the available area to add more roleplay opportunities and to make certain activities relevant (like doing the commissary). It also is the first PR (to my knowledge) to add in Armhulen's cool automated transit tubes.

Before I showcase the rooms individually, here's a screenshot of the whole thing:
image

And now individual areas

Brand new central meeting area attached to a commissary and a smoking lounge:
image

A decently sized recreations hallway with windows into the holodeck:
image

A new vault, semi-attached to the station along with a full Music Room, Theater, Laundry room, and small public garden.
image

A larger set of maintenance complete with a spacious abandoned bar:
image

And a whole set of customized dorm rooms, each with their own character!
image

I've also moved and redid a set of solars, and changed the commissary by arrivals into a vacant office.

I've done a playtest of this server side and have also debugged it. Everything should have its place.

## Why It's Good For The Game

Adding more unique flare to Pubby is a long-term project that I hope to continue in the near future. This PR adds a lot of new ways to interact with the commons area and gives Pubby more character. By diversifying this area of the station, I hope to bring more traffic to it and make it worthwhile to stick around that area to do some of the more roleplay oriented activities.

## Changelog
:cl: Son of Space
add: PubbyStation's Commons area has been given a massive facelift. Check it out!
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Could you put locks on the bathroom doors?

**Comment by KathrinBailey** [comment]
Holodeck console room could do with normal glass, no reason for the added security of reinforced glass considering the extra construction steps they have now.
Having such an overwhelming amount of windows and great visibility into main is also a little weird. Pubby has a lack of maintenance space for antagonists to use, so the added visibility kinda makes it useless.
The dorms hallway could use some decoration. Some extra turf_decals to spruce the place up would be appreciated.

**Comment by Cartographer-D** [comment]
I will add locks to the doors and replace those windows with regular ones.
Not sure yet how I'm going to decal up the hallways, but I'm going to give it an attempt.
I'll consider removing some of the windows into maint, but it's also really easy to obscure yourself in there. I placed the lights in a way that they don't illuminate very far in, giving off that spooky vibe.

**Comment by Tlaltecuhtli** [comment]
i think the central bloc is what needs some changes, omegastation had the bar open north and south which made it a wide area traversable, maybe have it this way instead of the cringe cock and ball torture "maint"

**Comment by LemonInTheDark** [comment]
removes tactical stripper pole 
image

**Comment by Cartographer-D** [comment]
> 
> 
> removes tactical stripper pole
> image

It's there

**Comment by LemonInTheDark** [comment]
Dear god I take it all back 👍

**Comment by Cartographer-D** [comment]
> 
> 
> i think the central bloc is what needs some changes, omegastation had the bar open north and south which made it a wide area traversable, maybe have it this way instead of the cringe cock and ball torture "maint"

Not in the scope of this project, but may be investigated later.

**Comment by Cartographer-D** [comment]
Also changed some windows to regular windows and removed some windows into maintenance.

**Comment by Cartographer-D** [comment]
Have to add a motion tracking camera to the AI sat

**Comment by sergeirocks100** [comment]
I like what you've done here, but i'm not sure if it would be so wise to do this when Pubby might be removed soon in favor of Kilo. (#54588)

**Comment by Cartographer-D** [comment]
> 
> 
> I like what you've done here, but i'm not sure if it would be so wise to do this when Pubby might be removed soon in favor of Kilo. (#54588)

See my reply on that PR.

**Comment by EOBGames** [comment]
Well, Pubby has been removed, so this PR is now, unfortunately, obsolete. Apologies for this, I had intended to merge this but didn't get to it before the trigger was pulled on Kilo.

**Pull request closed without merging**
