### PR TITLE
Removes Partial Credits for Already Discovered Seeds + MoneyTree Potency Edit

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: 
del: Reverts getting partial credit for discovered seeds.
tweak: Tweaks Money Tree Potency Values [For instance: 1000 Space Cash requires 98-100 Potency]
/:cl:
## Lemon Tree Potency Rework:

Math: 1+2+3...+8 = 36 / 100 = ~2.8

$1 = 2.8 \* 8 = ~22 = 0-22
$10 = 2.8 \* 7 = ~20 = 22-42
So on.

### CODE REVIEW

**Comment by ma44** [comment]
Cargo did not influence the round at all during that blob round ;-;

**Comment by ExcessiveUseOfCobblestone** [comment]
Money Tree Farming will not go away unless we simply remove money trees or Money4Points, neither of which is necessary [imo]. It wouldn't make sense for a 1000 dollar bill to be worth 500 or whatever, so I have no intention on doing that.

However, this system encourages you to use the money lemon to produce **one** set of bills [depending on potency, which was tweaked in this pr] instead of upgrading the seed machine to get a 200%+ profit increase by turning that one lemon into multiple seeds. Even without upgrades the seed machine would still be more profitable for the most part. If anything this is a very small nerf since you CAN open the moneylemons. 

Reminder though, this PR also tweaks the Lemon potency. If you potency is below 98, you're losing 50% of profit.

**Comment by ma44** [comment]
So your encouraging money exports
Also if your bulk seed exporting, you do not use the seed machine as it will waste so much of your time
So instead of getting 20 seeds, i can just open those 20 lemons instead and i can get 20,000 points instead of 1000 points

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes, which is better than putting those seeds into an [upgraded] seed extractor to suddenly turn that 20K into 20-40K+

If there IS an issue with exporting money, then that can be tackled in a separate PR. That shouldn't dilute the objectively larger exporting of moneyplant seeds.

Also note that once you sell a 100 potency seed every non-100 seed will be sold cheaper than 50 relative to its potency. Meaning a 10 potency seed will become 5 and anything below 3 potency will probably be unexportable.

**Comment by ma44** [comment]
The only way to get space cash is in it's non seed form

Also seed extractors aren't the problem, if your using them to make a profit your doing it wrong

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't think I am if I'm making more money than peeling the lemons, which only grows when I get upgrades  >:(

**Comment by ma44** [comment]
@ExcessiveUseOfCobblestone you can easily make a lot more money much more faster by mass producing lemons and using the port seed extractor

**Comment by ExcessiveUseOfCobblestone** [comment]
I uh... I think you need to test this on a private server [before this pr] and come back with the data.

**Comment by ExcessiveUseOfCobblestone** [comment]
After doing some more ingame testing, I found that I was off by a factor of 10 on the before PR minmaxing.

**Comment by ma44** [comment]
what do you mean off by a factor of 10, does that mean minmaxing only gives 12,500?

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes.

I overthought the equation. It's just Rarity * 2.5 * Potency Difference [No Potency only component].

However, minmaxing is still there.

I'm gonna pull the "i'm still new to coding" card here :^)

**Comment by ma44** [comment]
>factor of 10 difference
Your just encouraging people to use space credits, which brings a much more higher return (See stats exports cost)

**Comment by ExcessiveUseOfCobblestone** [comment]
I've already discussed with you how Space Credits from said $lemons brings lower returns than using a large seed extractor [especially with upgrades] and simply getting seeds. 500*3 or 500*4 > 1000 [and a lot easier than having to peel every single lemon if you had a portable seed extractor or plant bag]

The Factor of 10 difference was ONLY applicable to a seed with higher potency than the highest seed you've put in so far.

Yes, it is still very possible to make large sums of money by keeping potency above 98 and peeling every-single-lemon. However, if the money exports are STILL problematic after this PR I'll try to tackle space cash itself [although I'd rather not do that since it makes sense thematically that money is worth... well... money].

**Comment by ma44** [comment]
You can't put cash lemons into a bag and just click on the large seed extractor, you have to put it in ONE by ONE, you can't use a plant bag to simplify this process. Using the portable seed extractor will always result in a 1/2 loss compared to space credits

**Comment by Core0verload** [comment]
Fuck, I'm too lazy to read this, but long post about a simple problem feels like balance retardation. Just remove non-new seed export and nerf money tree a tiny bit.

**Pull request merged**
