### PR TITLE
Adds megaphones and shock grilles to head offices.

### PR DESCRIPTION
**Pull request by WJohn**
What it says on the tin. All head offices have electrified window grilles and megaphones in their lockers. The electrified grilles are only like that on boxstation.

:cl: WJohnston
rscadd: All heads now start with megaphones in their lockers, and their windows are electrified.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
I shall **YELL AT EVERYONE WHILE CONVULSING ON THE GROUND!**

**Comment by ChangelingRain** [comment]
Map edits aren't features kor

**Comment by Shapsy** [comment]
Please don't, the CMO office has nothing in it to justify how much of a pain in the ass/hazard shocked grilles are

**Comment by KorPhaeron** [comment]
Giving electric grilles to everything is definitely balance nonsense

**Comment by WJohn** [comment]
I dunno, metastation does it borderline religiously, so I don't see the problem with doing it here, too.

**Comment by KorPhaeron** [comment]
Also WJ I am not sure if you have seen the tesla grilles yet

**Comment by ChangelingRain** [comment]
CMO office shouldn't have shock grilles, they're the weak head and it's thematic.

**Comment by optimumtact** [comment]
I don't like it

**Comment by PKPenguin321** [comment]
:-1:

**Comment by Iamgoofball** [comment]
@ChangelingRain 

>>>>>>>>>>>>>weak

say that to my face

oh wait you cant because i'm hulked out got a healing virus and stuffed chems so far up your AnUs3 with foam and smoke that you're dead in 2 seconds flat

**Comment by Durkel** [comment]
Why don't we just make all the grilles shocked and remove insulated gloves? Fuck the balance, you want a death trap here we go.

**Comment by Cheridan** [comment]
haha durkel haahahah

anyway if one head gets electrogrilles then its only fair that they all do.

**Comment by Thunder12345** [comment]
What is there in the CMO's office that needs electrified grilles to protect it?

HoP has them to slow down the tide trying to get all access
RD has them to protect the borg console
CE and HoS have them because their offices present easy access to high risk area
Captain doesn't have them because only the finest reinforced walls are good enough for our Glorious Leader
CMO has them because... Runtime might get out? Heretics might touch the sensor console?

**Comment by Archie700** [comment]
>adding tesla grills to head offices
>not a feature

It's literally a rebalance.

**Comment by Archie700** [comment]
@Thunder12345

The hypospray I guess?

The hardsuit? A redheaded CMO?

Yeah I really don't get it either.

**Comment by Shapsy** [comment]
It's not even that, shock grilles are just more dangerous than normal grilles now. With a normal grille it just acts as a way to hold people back and prevent them from getting in, but now shocked grilles are just an easy way to kill anything around them by throwing shit at them. The CMO's office is small enough where pretty much any tile there is in range of a shock grille if someone triggers a shock, and it just turns into an easy way to get cornered and fried

**Comment by GunHog** [comment]
Would you guys be happy with it if we excluded the CMO?

**Comment by Shapsy** [comment]
As a head of staff I'd feel less safe with shock grilles, especially as the CMO or HoP where it'd just get used to kill you. CE gets a pass since he has gloves and a hardsuit, plus a lockdown button

**Comment by bgobandit** [comment]
shaps the HoP already has shocked grilles

**Comment by Shapsy** [comment]
Not on box it doesn't

**Comment by Lumipharon** [comment]
>add tesla grilles to all offices
>offices small enough to fry anyone inside

Ebin.

**Comment by Cheridan** [comment]
also stop sperging about freeze violations omg maps and sprites have literally always been exempt

**Comment by Zilenan91** [comment]
Not with tesla grilles, this is awful with those things. :-1:

**Comment by PKPenguin321** [comment]
Freeeeeeeezeeeeee

**Comment by KorPhaeron** [comment]
Dead pr

**Pull request closed without merging**
