### PR TITLE
Revert "Stun is now a status effect"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#28654

`(E) (C) (M) duration = 40045.5 `

### CODE REVIEW

**Comment by Jordie0608** [comment]
@ChangelingRain is just trying to compensate for the previous PR making kockdown super-short.

**Comment by GunHog** [comment]
And this is why you test things!

**Comment by Kromgar** [comment]
15000 HOURS OF TESTNG

**Comment by Tacolizard** [comment]
40045.5 hours of testing

**Comment by ChangelingRain** [comment]
Hi yup #28696 fixes this

**Pull request closed without merging**
