### PR TITLE
Insuls grammar fix

### LINKED ISSUE #48363: Insuls grammar
No round id

That's some insulated gloves. 
These gloves will protect the wearer from electric shock. 
>grug protec u from bad electric

### PR DESCRIPTION
**Pull request by Tharcoonvagh**
Hey this is my first pr
Fixes #48363

## Changelog
:cl:tarchonvaagh
spellcheck: insuls description
/:cl:

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by trollbreeder** [comment]
Hahaha no
You're a nonnative, you dont speak english very well ("But surely this is how it's correct") and the insuls description is perfectly fine.
(Singular) An electric shock. (Plural) Two electric shocks. (Infinitive) Electric shock.

**Comment by RaveRadbury** [comment]
Why would you derisively laugh at someone contributing to the repo for the first time? Especially considering that you've never contributed?

**Comment by trollbreeder** [comment]
> > Hahaha no
> > You're a nonnative, you dont speak english very well ("But surely this is how it's correct") and the insuls description is perfectly fine.
> 
> Why would you derisively laugh at someone contributing to the repo for the first time? Especially considering that you've never contributed?

I've been tainted by reading almost all of goof's PRs, haven't i? Sorry.

**Comment by Tharcoonvagh** [comment]
:((((

**Comment by trollbreeder** [comment]
I feel bad. Merge this.

**Comment by trollbreeder** [comment]
Well done with your first PR then.

Also, bad man travis angry at glasses
`[11:26:28] Runtime in unsorted.dm,1183: /obj/item/clothing/glasses/meson/engine does not have a valid icon state, icon=icons/obj/clothing/glasses.dmi, icon_state="trayson-meson"([0x600c3ee]), icon_states="glasses"([0x600089c]), "sun"([0x60069d3]), "meson"([0x6001886]), "nvgmeson"([0x600c3e8]), "thermal"([0x600bcfb]), "material"([0x6003aa4]), "blindfold"([0x60009b1]), "blindfoldwhite"([0x600c42c]), "monocle_old"([0x60325a4]), "eyepatch"([0x600c40f]), "thermoncle"([0x600c434]), "leforge"([0x60325b6]), "night"([0x600c40e]), "healthhud"([0x600c3b7]), "securityhud"([0x600a059]), "monocle"([0x600c3e3]), "sunhudsec"([0x600c3d2]), "sunhudmed"([0x600c3ba]), "purple"([0x6000548]), "thermalimplants"([0x603247b]), "bigsunglasses"([0x600c425]), "jensenshades"([0x60325b7]), "hipster_glasses"([0x600c3ac]), "welding-g"([0x600c427]), "welding-gup"([0x60325b8]), "healthhudnight"([0x600c3b4]), "securityhudnight"([0x600c3dc]), "hudpatch"([0x600c3cf]), "cold"([0x6000bd6]), "heat"([0x6000cae]), "garb"([0x600c3d6]), "gars"([0x600c3d5]), "supergarb"([0x600c41d]), "supergars"([0x600c3d9]), "supergar"([0x600c423]), "gar"([0x600c420]), "garm"([0x600c3ea]), "trayson-"([0x602e278]), "trayson-meson"([0x6032657]), "trayson-t-ray"([0x600c3fa]), "trayson-radiation"([0x6032658]), "trayson-shuttle"([0x600c3fc]), "diagnostichudnight"([0x600c3c5]), "diagnostichud"([0x600c3c2]), "doublegodeye"([0x600c448]), "godeye"([0x600c446]), "orangeglasses"([0x600c440]), "medsechud"([0x60325bd]), "redglasses"([0x600c443]), "jamjar_glasses"([0x600c3aa]), "sunhuddiag"([0x600c3c8]), "circle_glasses"([0x600c3af])`

**Comment by Tharcoonvagh** [comment]
What is this witchcraft

**Comment by Farquaar** [comment]
As a native speaker, let me assure you that the original description is perfectly grammatically correct, and while your new description is also correct, the old one is better in my view.

In this case, shock is used to represent the body's reaction to a stimulus. Electric shock, like anaphylactic shock, or asphyxiation, is a response of the body that results in harm or death. While you could change "shock" to a plural, it sounds like it was written by an ESL speaker.

**Comment by Tharcoonvagh** [comment]
@farquaar yea i changed it to something else, imo it sounds better now:
>These gloves provide protection against electric shock.

**Comment by Farquaar** [comment]
Cool. I read the change earlier but only was able to reply then. The new version is good.

**Comment by kriskog** [comment]
I added it for you, but putting Fixes #48363 in the PR body makes the issue autoclose on merge.

**Pull request merged**
