### PR TITLE
Give the pulse rifle an on back sprite

### LINKED ISSUE #47173: Pulse rifle has no on back sprite
Tested with an offline build. Was a pulse rifle from an arcade machine if it matters

### PR DESCRIPTION
**Pull request by ghost**
adds the missing back sprites and thus completes my tale of sadness.
I noticed that there are old versions of the pulse rifle sprite in the files but I choose to make my own. The only drawback is mine don't show the guns charge though I think that's what messed everything up in the first place
images:
front

back

lside

rside

OH I IF YOU NOTICE THE PIXELS THAT ARE COVERING THE HAND DON'T WORRY I REMOVED IT I'M JUST LAZY AND NEVER GOT AROUND TO GETTING A NEW PICTURE

:cl: PepperPrepper
add: Back sprites for the pulse rifle

/:cl:

Fixes #47173

### CODE REVIEW

**Comment by nemvar** [comment]
You can put something like "Fixes #47173" or "Closes #47173" into the description of the PR so the issue gets automatically closed when this gets merged.

**Comment by PepperPrepper** [comment]
> 
> 
> You can put something like "Fixes #47173" or "Closes #47173" into the description of the PR so the issue gets automatically closed when this gets merged.

Ah right okay, Thanks for the help!

**Comment by ExcessiveUseOfCobblestone** [comment]
im gonna beat u up if you don't embed ur images

**Comment by PepperPrepper** [comment]
leaf me alone I'm learning

**Pull request merged**
