### PR TITLE
Kinetic Accelerator Overhaul [Not WIP]

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
This PR removes all the variants of the kinetic accelerator in favour of a single modular gun.

You'll be able to customize said gun to get range/damage/aoe/recharge/dual wielding bonuses etc (and probably other effects as well).

Right now a KA can hold two mods, and the mods themselves do not have stats yet.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>removes the paragraph desc
good riddance

**Comment by KorPhaeron** [comment]
I plan to have It has [modkit] installed in examine, so it needs to be readable unfortunately.

**Comment by kevinz000** [comment]
can we make all guns modular now :^) everything is tied into vars :^)

**Comment by lzimann** [comment]
you beat me into doing but whatever :+1:

**Comment by callanrocks** [comment]
@kevinz000 modular RnD guns yes/yes?

**Comment by Ergovisavi** [comment]
One problem I fundamentally have with this is that you're still going to end up in a world where you're carrying around multiple KA's. One modded for digging, and one modded for combat, and the scientists are still going to be confused, etc, but I suppose it isn't the worst option.

**Comment by Iamgoofball** [comment]
I actually had this before but then you guys removed it because "ugh OP"

then you replaced it with equally OP upgraded versions

**Comment by lzimann** [comment]
The idea is to not have all the "op" upgrades hyper KA gives you at once, but to make you choose what you want and that being limited.

**Comment by lzimann** [comment]
wasnt this WIP..

**Comment by KorPhaeron** [comment]
lmao

**Comment by KorPhaeron** [comment]
@Cheridan 

Are you okay

**Comment by PKPenguin321** [comment]
haha what

**Comment by Cheridan** [comment]
i'm ok

**Pull request merged**
