### PR TITLE
Rough Metal Walls

### PR DESCRIPTION
**Pull request by AnturK**
Adds the ability to build the unused metal mineral walls.
5 rods to make one.

I feel kinda bad about adding to that if pile, so will possibly rewrite this a bit soonish.

space station 13 2015-10-12 234805

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Pics?

**Comment by AnturK** [comment]
It's the unused mineral one, one sec i'll get some

**Comment by tuypo1** [comment]
is that gas meter still not fixed

**Comment by Steelpoint** [comment]
It should have been but the nature of map PR's is that its easy as crap to accidently over right other changes.

**Comment by Dorsisdwarf** [comment]
Or that his branch isn't completely up to date

**Pull request merged**
