### PR TITLE
imcreases chemical costs of changeling powers on the following(spread infestation, Combat Tentacle OwO)

### PR DESCRIPTION
**Pull request by jughu**
Following chemical costs are increased for the following reasons

Spread infestation:ya know... you used to absorb 5 people to even get this ability but you can just dna extract them 5x and infinitly shit these spiders out WHICH will bring the round easily to a end without even being found since these little spiders crawl everywhere and shit around its increased to 75 so if they shit out the spiders near nearby people or recently they need to regain their chems before they can combat and even if the spiders attack their owner the ling can just regen our smash out a  cocoon

Combat tentacle:too strong at its current stage even creactor XTDM agreed on a chem increase

:cl: hyena
tweak: Raises chemical cost of spread infestation to 75
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) HELLO DO YOU WANT A CUP OF SPIDERS?

### CODE REVIEW

**Comment by Haevacht** [comment]
I ded PR.

**Comment by Magikarpet** [comment]
just remove the stun on tentacle and it'll be reasonable as either a gapcloser/guncloser tool

**Comment by jughu** [comment]
@haevacht i-i didnt d-die

**Comment by jughu** [comment]
Lings are supposed to be stealth antags who need to move carefully and coordinate not turn into war machines

**Comment by XDTM** [comment]
As the creator of the tentacle, definitely remove impaling at least.

**Comment by jughu** [comment]
@xtdm ok ok that be a seperate pr i guess im still triggered about this spider thing

**Comment by InsaneHyena** [comment]
> Lings are supposed to be stealth antags who need to move carefully and coordinate not turn into war machines

Who told you that

**Comment by XDTM** [comment]
Keep the tentacle cost increase, it's probably too cheap now. Maybe 15?

**Comment by jughu** [comment]
Well if the creator says to i guess it be 👌

**Comment by AnturK** [comment]
Stop reopening the PR please.

**Comment by jughu** [comment]
😢

**Comment by KorPhaeron** [comment]
atomize your PRs please

**Pull request closed without merging**
