### PR TITLE
Don't teleport anchored objs

### PR DESCRIPTION
**Pull request by Archemagus**
## About The Pull Request
Fix telepad's bug, that make able to teleport anchored objs.

## Why It's Good For The Game
image

## Changelog
:cl:
fix: Telepad can't move airlocks and other anchored objs!
/:cl:

### CODE REVIEW

**Comment by Archemagus** [comment]
image
¯\_(ツ)_/¯

**Comment by 81Denton** [comment]
No worries, that's unrelated to your PR

**Comment by Ty-the-Smonk** [comment]
Travis strikes again

**Comment by ATH1909** [comment]
Wait, does this mean that a teleport pad can currently teleport the SM crystal?

**Comment by Archemagus** [comment]
Yup and station's self-destruct too

**Comment by Fhaxaris** [comment]
feature

**Pull request merged**
