### PR TITLE
Removes random junk from Metastation evidence closets

### PR DESCRIPTION
**Pull request by Bawhoppen**
Random stuff being in there makes me not want to put any other stuff in because I don't want to mix up unrelated stuff together.

### CODE REVIEW

**Comment by praisenarsie** [comment]
>evidence bags
>random stuff

???

**Comment by Bawhoppen** [comment]
They're more clutter in my opinion.

**Comment by DoctoreMad** [comment]
Discard your own joke opinion.

**Comment by Bawhoppen** [comment]
I thought I was the only one who even cared about actually using evidence lockers

**Review by Cyberboss — APPROVED** [review]

**Comment by DoctoreMad** [comment]
No you're right the rubbish in the lockers are... rubbish, but the evidence bags are useful.

**Comment by Qbopper** [comment]
I think I see what they were going for with spawning shit in there, but that would be more fitting if this wasn't a multiplayer game where the point is that you're the one generating those stories or whatever

like, you can't really say "gee I wonder what happened that ended up getting this item in an evidence locker" because you know it was just rng putting it there, this isn't divinity or whatever

**Comment by Bawhoppen** [comment]
@DoctoreMad You're thinking of the wrong type of evidence bags. These are just renamed backpacks. You can get the plastic little evidence bags in sec vendors.

**Comment by Militaires** [comment]
idea: add persistence to evidence lockers

**Comment by Qbopper** [comment]
that would be kinda neat

**Pull request merged**
