### PR TITLE
Re-assesses 99% of vending prices through Arconomics to match player resources and round-length.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
Just the once, Arm, I'll say the thing.

## About The Pull Request

So, as I was working on #54161, as I'm wont to do, and especially from testmerge feedback, I came to a pretty strong conclusion that, holy shit, vendors have got to be one of the most depreciated features in-game in terms of how prices were assessed.

Vendors and their prices are almost uniformly determined arbitrarily, as some vendors have prices far higher than any one player would make over the course of half an hour, while other vendors I came to realize have a far more significant issue. See, back in 201x when vendors were first added, and far before the in-game economy was PR'd by goof, vendors were added as a way to reduce locker clutter in-game, namely as a level of abstraction to hold objects without needing to map in a massive locker hallway in every department like in the brig. While some departments still kept this to a basic degree, in areas like costumes, clothes, etc, it made far more sense to stick these items in a vendor and keep everything from spilling out in a single explosion.

Back to the present: This means that most vendors have an un-even split between the items they should be offering for free or dirt-cheap as part of a job's standard resource kit, versus items that should really be offered for a nominal fee to replace possible missing supplies in one's department, as well as the other extreme which is premium purchases of goods in the vendors themselves as straight upgrades or side-grades to existing equipment.

As a result, I came up with an excel document to break down the prices and expected resources of each department as well as each relevant job-paygrade, in order to develop a functional payment breakout chart of where prices should sit, to keep a maximum of about 10 purchases of in-department goods before running out of funds. On the flipside, this also frees up money for players to interact with each-other, without feeling obligated to purchase a full layout of equipment as opposed to using that money for RP or dynamic gameplay reasons.
image
_A primary breakdown of prices, with the current in-game prices on the left, and the changed expected in-game prices on the right._

Additional footnotes:
Several items that had individually assessed prices previously have had those prices assessed to better match the amount of money players will have available, or was changed to match the prices after the expected price-hike at roundstart due to inflation. This means that if things still feel expensive at roundstart, they may be far easier to purchase later in the round assuming players are spending their income.

Several items and classes of items have a designated uniform value range, like how clothes vendors keep uniforms, jumpsuits, etc., typically around about 50 credits for the purposes of simplicity. See the above spreadsheet for the assumed price tiers for major groupings of items.

The medical vendor has been split up into 2 vendors now, as it was basically a whole medbay in a box previously, and no single price metric was going to make that work. Now there's a NanoMed vendor, as well as a NanoDrug vendor, to make the individual pricing of objects between the 2 vending machines far easier to manipulate and balance for the future. Mapping will be required, and I will check that off below when it's completed.
- [x] Have I mapped in Nanodrug Vendors yet? 
- [x] Have I made the refills actually obtainable because I should do that too?

Likely needed in tandem with the above income changes, but preferably this is done first to make the lack of passive income actually bearable. 

## Why It's Good For The Game

Prices, outside of individual items obtained in vending machines, is literally one of the most arbitrary things balanced in the game. I can tell that even before the changes I made to income, prices have literally been just randomly slapped onto shit without even considering the level of income that individual jobs require, or any of the associated factors outside of exclusively time gating content, because after all, eventually, they'll be receiving that thing for free anyway from income.

The most balance in this PR is with people purchasing things outside of their own department or in department-less vending machines in-game. The goal in the associated income PR is to replace the free cost of many of the deparment specific resources with instead a discount to the price of the products in question rather than just handing them out, but that's not possible without this 62+ file change, and so I felt the need to atomize that out separately to keep the kicking and screaming down for review purposes.

This also steps a precident about where we want prices to be for vendables in-game going forward, with cheap, dispensable items being half the price of general purchasable supplies, and premium items being either double the general rate or assessed based around a standard of 10 regular purchases per round max, so that excess funds are available for inter-player interaction.

## Changelog
:cl:
add: The Medical NanoMed vending machine has been split into two, with the all new NanoDrug vending machine taking most chemical medicines.
balance: Literally everything purchasable in a vending machine has had it's prices adjusted to better suit players to buy more things, while still enabling them to interact with each other using money.
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
I know there's an issue with the vendors displaying discounted items as free. Can you fix that? It's unpleasant to suddenly run out of funds when you're bulk-purchasing drinking glasses from the bar vendor.

**Comment by ArcaneMusic** [comment]
> 
> 
> I know there's an issue with the vendors displaying discounted items as free. Can you fix that? It's unpleasant to suddenly run out of funds when you're bulk-purchasing drinking glasses from the bar vendor.

That is specific to 54161, this doesn't do any backend mechanical changes to how vending machines work, just changing the base prices of items instead.

**Comment by Maurukas** [comment]
The medical and engineering department vendor prices look reasonable, taking into account the 80% discount from 54161. This looks very good. I've played quite a few rounds with that PR test merged, and these prices would be quite reasonable in that scale of credits. This would also push many bounties that are currently not worth doing, into being interesting. Doing one will get you enough cash for a couple of basic vendor items.

One concern I have is that it's going to be a challenge to fit another full tile vendor into many of the Medbay storage rooms. You may want to consider adding them to treatment areas instead, as these tend to have more space. Nanomeds are also mapped into virology, and that may also require a some tweaking.

**Comment by bluetshirtguy** [comment]
Just curious but are any vendors not previously effected by inflation now effected, is anything changed in that regard?

**Comment by Losenis** [comment]
In which category do the PTech vendors and computer parts vendor fall?

**Comment by ArcaneMusic** [comment]
> In which category do the PTech vendors and computer parts vendor fall?

PTech falls under the command catagory technically, so the prices for that vendor make sense to an extent so as to keep them unchanged.
Computer parts, on the flipside, fall under the science paygrade, as well as are reinforced by the computer parts export values.

**Comment by optimumtact** [comment]
the prices should be expressed as a ratio of average salary or something, so the ratios dont' drift over time (They will)

**Comment by LemonInTheDark** [comment]
Poke?

**Comment by ArcaneMusic** [comment]
> Poke?

Working on oranges review, just had to wait until the weekend to get a second to rewrite the prices again.

**Comment by optimumtact** [comment]
good work :+1:

**Pull request merged**
