### PR TITLE
[WIP] Adds Traitor Heists

### PR DESCRIPTION
**Pull request by Robustin**
Traitor needs some fresh ideas. We already have a pretty lame folder objective that identifies another traitor for you and lets you optionally cooperate for greentext. 

But swapping folders is boring and who cares about greentext.

A traitor heist is assigned if there are a sufficient number of traitors and if RNG selects it instead of an exchange objective. 

This idea is ripe for expansion but its first form will just have a 2-person team. The two traitors will have the same objective: Complete the mission and escape alive. They will only start with 6TC each - but will each have a syndicate key in their inventory at roundstart.

At this point each traitor can fuck off, beat the nearest assistant to death, and then space themselves. But since most traitors would prefer to work with more than a petty 6TC, they will have an incentive to complete the heist and earn a bonus of 20TC each (subject to change).

The heists will all be designed to be sufficiently overt and disruptive that people will care about their undertaking and generally be opposed to the activity, they will also be sufficiently unique that people should be able to distinguish them from general greytide shenanigans. While some may require using force against the crew, most will be oriented to require minimal bloodshed. While these heists will be challenging, they shouldn't be so onerous that it feels like a punishment 

Some heists will simply be a single, relatively difficult task - like draining the maximum amount of power with a power sink, stealing the entire station's credit balance, or gathering a large quantity of body parts, or collecting every head of staff jumpsuit - some can be sillier like collecting dozens of units of Corgi Meat  , photographing 5 different (living) crew members and at least one head of staff handcuffed and dressed as a clown, or honking at least X% of crew members with a bike horn while they are stunned. 

These are just a few ideas, I'm definitely open to more as I code them. I firmly believe this will produce some very unique and entertaining rounds and breathe a little more variety into traitor mode. 

Edit: I will probably take @Bawhoppen's advice and make this a preference option. I don't think anyone wins if a dude who just wants to murder everyone around him gets thrust into a team role when there's several other traitors who might prefer that role. 

I may also consider giving unique rewards in lieu of TC, or a mix of both. Ex: A clown-themed heist would reward 10TC + Staff of Honking instead of 20TC, etc.

### CODE REVIEW

**Comment by Militaires** [comment]
nice quads

**Comment by BeeSting12** [comment]
This is the sort of thing that will make traitor fun, not adding fluff texts and restrictions to go with them.

**Comment by ma44** [comment]
Brb rushing B with emag then buying romeral and a crossbow with that sweet TC (and maybe adrenalines cause that's fun)

**Comment by Repukan** [comment]
Catching people in a disposal loop.

Statues out of minerals (highly disruptive)

Weapon hoarding.

**Comment by Robustin** [comment]
I originally had a weapon hoarding one but I realized that if youve got 2 traitors with access to several guns, they probably don't care that much about earning TC.

The other 2 sounds good though, tracking how many people get caught in a loop would be difficult though.

One addendum: The viability of many heist ideas (e.g. Corgi meat) kind of falls apart when you account for Null crates. If you have enough control over cargo to mass order and slaughter corgis, why not just order several null crates and get 100+ TC in equipment instead?

Given that null crates are now the most popular item ordered in cargo (check our stats), I think its due for a nerf.

**Comment by cedarbridge** [comment]
X credits of spess cash

Suddenly people give a shit about the vault being robbed

**Comment by Repukan** [comment]
How about stealing technology boards/levels

Or breaking/deconstructing certain amount of doors

**Comment by Robustin** [comment]
@Repukan 

Last 2 arent really interesting. Nobody cares if you make a bunch of tech disks, and its not especially hard to wipe the RND server. 2nd one is basically "spam emags" which isn't really interesting and produces kind of cancerous rounds.

**Comment by Repukan** [comment]
No I mean actually remove the doors.

Be it by breaking with a weapon or using RCDs

**Comment by Repukan** [comment]
And by boards I mean the roundstart ones.

So you have non operating RnD and Robotics because two dipshits broke in and stole all the boards.

Or the chef is riding Pete and hunting with knives in his hands the person that stole his microwaves.

**Comment by Robustin** [comment]
Not sold on the door thing but I could see a heist requiring you to bring in a bunch of boards that would be found in various areas (microwave, gulag, medivendor, exofab, etc.)

**Comment by Bawhoppen** [comment]
It needs to have a preference. People don't want to have their antag roll fucked over by even more RNG (and as much as I'm against the antag roll mentality myself, this isn't the relevant fix for that)

**Comment by Jalleo** [comment]
antag roll mentality solution make everyone else a protagonist. Clean floors fixed doors etc etc. Oh wait people dont want that.

**Comment by Robustin** [comment]
@Bawhoppen 

I was considering having it be a prompt and you can reject the assignment, but preference WOULD work smoother but I kind of worry about preference bloat.

**Comment by Qbopper** [comment]
This certainly sounds interesting, though the hardest part will be to convince players to cooperate imo

I'm in favor though

**Comment by Iamgoofball** [comment]
@Robustin no preference

adding a preference is basically like adding a button to throw your work out the window

**Comment by Robustin** [comment]
@Iamgoofball 

But if you get dedicated murderboners who get thrown into the objective and never want to do it, for all intents and purposes it might as well be off. 

I could make it a prompt but that gets messy for its own reasons.

**Comment by PKPenguin321** [comment]
These aren't really heists as much as they are 'you get less TCs at random and if you do a snowflake objective you'll get more and also here's a free other traitor to team with'. Not really that exciting now that I look at it in depth, I can't see myself wanting to do this over just regular traitor

**Comment by Robustin** [comment]
@PKPenguin321 

That's the biggest question I'm facing right now. I want to keep it more heist-themed, but there are very few "natural resources" that the crew even cares about and stealing stuff like the armory would be a little to straightforward and yet I can't exactly make it difficult without implicating all the other rounds. I could make some of the objectives a little heistier by giving the syndies a black market transport they can summon to arrivals and will have to move a bunch of bulky goods onto it.

So either I have to add new mechanics or just focus on making interesting objectives that aren't all that heisty.

I want these to be fun for the traitors obviously but even if its kind of a wash for them (teaming up is fun, having to work for your TC's isnt) it would still produce more interesting rounds for everyone else than shatting out an ebow + esword as roundstart.

Maybe if @kevinz000 could get off his fat ass and finish the PTL, that would make for a solid heist, but if he doesn't I could just throw together a hacky version thats just a powersink+BSA combined.

I do appreciate that concern though @PKPenguin321 but if I'm going to make them all truly heist-themed I need more ideas. Otherwise I'm fine with it being a mix of actual heists and new oddball objectives.

**Comment by PKPenguin321** [comment]
What I would do is let them keep their starting TCs so regular traitor play is still available, and give a few extra TCs for completing the objective, but make the objectives more significant/difficult. What you have is sort of the other way around, where you get less at the start but win more for doing the objectives but the objectives are way easier (honking people? Seriously?). The hangup here is of course what the actual objectives would be, like you said. Maybe since they're team objectives you could do something similar to old teamling objectives, like "be in possession of at least two head of staff IDs," only now people will maybe actually do them because they have extra TCs on the line.

Personally I'd close this PR for now, maybe make a thread asking for more ideas for actual objectives, then come back to this once there's more substance to work with.

**Comment by Robustin** [comment]
Im making the missions into a datum, that will adjust the starting TC and reward depending on the difficulty.

I did try making a thread for engipoints, got minimal feedback, and we know how that turned out. This PR will be making steady progress once I wrap up the cult master (sometime this weekend).

**Comment by Lumipharon** [comment]
Speaking of null crates, is there away to restrict the amount purchasable in a given round?
There are plenty of ways to get assloads of points, and it never made much sense that the syndicate could (and would want to) send effectively limitless amounts of their kit to the station.

Even being able to order a single crate of free syndie kit is massive value for money.

**Comment by Robustin** [comment]
What the fuck is going on with compiling. I compile it locally and I get errors if I move from ticker to SSticker.

But when it compiles on Travil I get errors I use ticker instead of SSticker.

Fuuuuuuck.

**Comment by PKPenguin321** [comment]
Compilers might be using different BYOND versions?

**Comment by Nilons** [comment]
I think that using tc rewards as incentive to get traitors to actually do their objectives is fucking genius, good on you robustin I hope this gets in

**Comment by Qbopper** [comment]
I don't think bonuses for doing it bloodless would go over smoothly because of the whole "antags drive the round" thing (as much as I'd like to see that)

**Comment by Nilons** [comment]
That's true, but I can see in a lot of situations it being more of an incentive not to remove people from the round unnecessarily.  Even if they go loud as fuck and are on the run from sec I can see players going out of their way to use stuns because of the promise of extra Griff points.  I don't think on high pop a heist could happen without drawing hot and therein driving the round

**Comment by Qbopper** [comment]
Fair enough, I usually consider lowpop because >sybil but that's true

**Comment by Robustin** [comment]
Bloodless objectives have always been a catch 22. Objectives are pointless unless the crew are opposed to you completing them. That's why the old "Steal a Jetpack" or the current "Steal a slime core" are pretty atrocious objectives. If you complete them "flawlessly" then you weren't even an antagonist and added nothing interesting to the round. 

I tried to strike a balance with my heists so far, and I'd consider a bonus but it would just honestly be too hard to check because theres so many ways to indirectly kill people. Honestly the biggest roadblock is that it's really hard to test these heists with 2 clients on a local server.

**Pull request closed without merging**
