### PR TITLE
[Drama] Screwdriver eyeball spam NERF

### PR DESCRIPTION
**Pull request by freerealestate**
- Increases the amount of stabs it takes to make a character nearsighted (from 3-5 to 5-10)
- Decreases the amount of blurriness received from eyeball stabs (previously it could reach the hundreds within thirty seconds, and take between five or ten minutes to remove)
- Fixes getting the nearsighted or blind message while already nearsighted or blind
- Adds a hitsound of the same volume as screwdriver stabs to other body parts
- Lowers the chance to get stunned by stabs from 50% to 20%
- Makes it so you can't stun people with stabs who are already stunned
- Lowers the chance to go blind from eye stabs by half

I've tested this extensively, but I'm a new coder so it could very well contain mistakes.

**Edit:** I've changed the title from "fix" to "NERF" to avoid upsetting Aranclanos for making a pull he disagrees with.

**Some background on the needless drama surrounding screwdriver spam, because why not:**
<Aranclanos> that guy surely is mad for dying
<Ikarrus> I didnt think it would kick up such a controversy
<Ikarrus> but I guess I should have known better
<Aranclanos> I don't like how he titles the PR as a fix when he's actively nerfing it
<Aranclanos> the attitude
<Aranclanos> I hate his attitude
<Cheridan> I've shut down like how many screwdriver nerfs
<Cheridan> 2-3?
<mso> lul
<Aranclanos> is there a precedent on any actions against that
<mso> I'd say close that one for deceptive titleing
<Aranclanos> people opening PRs for personal agenda or something
<Aranclanos> trying to slide changes
<Cheridan> https://github.com/tgstation/-tg-station/pull/1901 mostly from kaze
<Cheridan> https://github.com/tgstation/-tg-station/pull/1895
<Aranclanos> >closed by me
<Aranclanos> oh bby

### CODE REVIEW

**Comment by Cheridan** [comment]
The fixes and stuff are good and the code looks fine... but as far as balance-wise, I don't think screwdrivers need a nerf. Many crew members are going to have eye protection or mask covering as a matter of course, which makes the screwdriver useless. It trades general effectiveness for special effectiveness in limited circumstances.

**Comment by PKPenguin321** [comment]
\>makes issue that it's OP
\>told to go to feedback forum
\>outright says no and makes a PR to nerf it himself without addressing the forums at all
[ayyyyyyyyyyyyyy lmao](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=3151&p=102660#p102660)
:-1: 
leave balance out of the PR and just focus on the bugs, please.

**Comment by freerealestate** [comment]
I personally think it's overpowered for what it is, as it allows you to chainstun people and cause blindness that takes between 5 and 10 minutes to get fixed. Most crewmembers don't have eyewear or an eye-covering mask, and shouldn't have to metagame being stabbed in the eyes by equipping a mask each shift to avoid it.

This pull doesn't stop it from being an effective weapon, it just nerfs it a little.

**Comment by PKPenguin321** [comment]
>I personally think it's overpowered
>I personally think
>personally

how about you take your opinion and put it in the feedback forums

**Comment by Falamazeer** [comment]
It shouldn't be silent, that's kinda retarded. Not as bad as old briefcases/rolling pins not giving any attack logs outside of the the hitee and hitter but you get me. 

but your grasp of the balance of the eye stab is flawed, Unless you're stunlocked, you're fully capable of taking back control of the situation. and if you are stunlocked, well.. you were kinda fucked anyways weren't you?

**Comment by freerealestate** [comment]
I was being charitable when I used the term "personally", it should be pretty obvious to most people that it's overpowered for what it is.

> Unless you're stunlocked, you're fully capable of taking back control of the situation

If you're blinded, and bleeding, and slow from wounds, how are you fully capable of taking back control of the situation?

>and if you are stunlocked, well.. you were kinda fucked anyways weren't you?

Uh, yeah. That's why I changed it.

>It shouldn't be silent, that's kinda retarded.

Are you referring to the removal of the stun message? Because other melee weapons don't send you a message when you're stunned, the stun itself is the message. I removed it to make it consistent, however I wouldn't care about adding it back in.

**Comment by PKPenguin321** [comment]
>s-stop disagreeing with me! m-muh forums oppression! DRAMA!

you realize that if the players on the forums (read: our playerbase) disagrees with a change, that's literally the playerbase disagreeing with a change? i'm not "intimidating you with the people of power," i'm trying to tell you that these aren't necessarily desirable changes and you're trying to force them on people anyways

**Comment by freerealestate** [comment]
Why are you assuming I'm trying to force changes on people? I've proposed a change to the code, it's up to people to decide whether or not they agree with it, and state their reasons for or against. The only thing I take issue with is the shittalking and prejudice in coderbus that already shows an unwillingness to consider this change for what it is.

**Comment by Kelenius** [comment]
"Overpowered thing that is countered easily but obliterates you if you don't have that thing" is shit design, so IMO the nerf is worth it.

However.

@freerealestate stop being a ln idiot, make a separate PR with fixes and a poll on the forums for the nerf, Aran's reaction is pretty typical for him.

**Comment by Falamazeer** [comment]
Yeah, of course you're blind bleeding and slow from wounds after you already got fucked up, I'm saying it's not as stronk as you seem to think it is, When you go down, spam click disarm until you get back up, then robust the motherfucker as best you can, screwdriver doesn't even consistently beat fire extinguisher assuming same conditions of no helmet.

**Comment by SconesC** [comment]
These are dumb and weird snowflake code

**Comment by freerealestate** [comment]
>These are dumb and weird snowflake code

It is, but I don't have the knowledge to fix it and nobody else is making an effort to. A small improvement is better than nothing

>I'm saying it's not as stronk as you seem to think it is, When you go down, spam click disarm until you get back up, then robust the motherfucker as best you can,

This is an easy thing to say and to understand, but between lag and yakkety sax, it has a high possibility not to work out.

>make a separate PR with fixes and a poll on the forums for the nerf,

I'm just not interested in doing that. After extensive testing, this is what makes the most sense to me. Design by committee doesn't work.

>Aran's reaction is pretty typical for him.

I don't dispute that, and yet it's still prohibitive to improving the game that coders have to weather his tantrums and hypocrisy.

Anyway, I'm closing this pull because I don't have the coding knowledge necessary to make this code consistent with other forms of attack, nor the patience necessary to consider everyone's opinion knowing a lot of players don't care about balance if it means they have access to overpowered stuff. I tried to improve this, and I'm sure once enough people accept screwdrivers are overpowered a better coder will fix the problem.

What a fun piece of coderbus drama.

**Comment by Tokiko1** [comment]
Eyestabbing was already nerfed recently. Aside from the hitsounds I don't like this change. Eyecover completely disables this weapon and is readily avaible in many places. Does this really need another nerf?

**Comment by Cheridan** [comment]
um, the only one generating drama here is you

**Comment by freerealestate** [comment]
The pull hadn't even received its first comment and you were already
denigrating it in IRC and attacking me for making it. Take some
responsibility.

**Pull request closed without merging**
