### PR TITLE
Indestructible turfs don't get destroyed by singularities

### PR DESCRIPTION
**Pull request by MMMiracles**
Indestructible turfs that are actually destructible aren't very indestructible, one could argue.

I fix.

### CODE REVIEW

**Comment by evsey9** [comment]
singularity eats all

**Comment by MMMiracles** [comment]
read the typepath again then go away ok thank you

**Comment by evsey9** [comment]
SINGULARITY EATS ALL

**Comment by MMMiracles** [comment]
image

**Comment by evsey9** [comment]
# SINGULARITY EATS ALL

**Comment by Dennok** [comment]
If you want you can code SUPER SINGULARITY what can eat INDESTRUCTIBLE turfs and objects.

**Comment by Militaires** [comment]
evsey has a homestuck avatar it's ok dont listen to him

**Review by SpaceManiac — APPROVED** [review]

**Comment by Qustinnus** [comment]
you could argue that being sucked into a singulo doesnt destroy the turf, just sucks it up into the singularity and condense it a bit ;^)

**Pull request merged**
