### PR TITLE
Adds mothperson plushie

### PR DESCRIPTION
**Pull request by ArcaneDefence**
## About The Pull Request

Adds a mothperson plushie into the arcade loot table

This is what it looks like.
image

Credit to cybersaber101 for the sprite

## Why It's Good For The Game

It's adorable, and fits alongside other plushies. 

## Changelog
:cl:
add: Arcade machines have been stocked with a new toy- A moth plushie!
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
More quality code. +1 rep.

**Comment by Fikou** [comment]
why is a naked moth popping out of the arcade

**Comment by Tumesuo** [comment]
Now i can live out my lifelong dream of making a moth and a lizard kiss and then make them have babies

**Comment by Tlaltecuhtli** [comment]
why is it naked

**Comment by bluetshirtguy** [comment]
> Kind of weird to add a plush for a race if you think about it
> I mean imagine if someone irl made an "african plush"

Someone irl made bodypillows, not just weeb shit on them too.

**Comment by Anonmare** [comment]
@PKPenguin321 It's okay, non-humans aren't people

**Pull request merged**
