### PR TITLE
Fixes heavy armor not having damage resistance

### LINKED ISSUE #15649: Heavy armor doesn't have damage resistance
/obj/item/clothing/suit/armor/heavy does not have any actual armor, because it doesn't list damage resistances, /obj/item/clothing/suit/armor doesn't list any, and /obj/item/clothing/suit doesn't list any.

It doesn't have any armor values, and it's subtypes don't either, so it's useless.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Fixes #15649

### CODE REVIEW

**Comment by Thunder12345** [comment]
You even stole my additional fixes for the other two armours

**Comment by Iamgoofball** [comment]
Yup. Tough luck, sorry your PR broke!

**Comment by Thunder12345** [comment]
I'm in the process of trying to fix it, don't be a shit just because you want to prove something about the system

**Comment by Razharas** [comment]
WHy you care thunder your pr is earlier thus 24 hour mark for it will come before his
Unless something really bad happens

**Pull request closed without merging**
