### PR TITLE
Yee-haw Update: Code Spaghetti Western Edition

### PR DESCRIPTION
**Pull request by Farquaar**
## About The Pull Request

[Previous PR](https://github.com/tgstation/tgstation/pull/62926) (Closed Because I'm a Git Newbie)
https://youtu.be/AFa1-kciCb4

Ever wondered why we had cowboy boots in the autodrobe and clothesmate, but no hats? 
Ever wanted to start a posse but the fluorescent lighting was beating down on your head? 
Ever wanted to run your bar like an old-timey saloon but you were too ashamed of your bald spot? 
Ever wanted to say "See you Space Cowboy" and actually mean it? 

This is the PR for you! 

image
Left to Right: Desperado Hat, Drifter Hat, Sheriff Hat (with Sheriff Vest), Ten-Gallon Hat, & Deputy Hat

All hats are craftable using two sheets of leather. The vest can be crafted with four sheets, and can be attached to jumpsuits.
The drifter hat and the ten-gallon can be found in the clothesmate. The others can be found in the autodrobe.
Every item has in-hand sprites!

This PR does not alter fugitive bounty-hunter items in any way.

## Why It's Good For The Game

It always puzzled me that we had so many western-themed items, clothing, and references, but no hats to back it up. Now we can run cowboy gimmicks to our heart's content, and admins have more than enough to cobble together an event straight out of the old-space-west.

## Changelog

:cl:
imageadd: Due to lobbying pressure from the Yee-haw Conservation Society, Nanotrasen vending machines now stock five new cowboy hats and an old-west vest.
/:cl:

### CODE REVIEW

**Comment by Toastgoats** [comment]
With the headmins seemingly movie to ban wgw, the woody cosplay seems like a nice sendoff.

**Comment by o0cyann0o** [comment]
yes... ha ha ha... YES

**Comment by NanoCats** [comment]
> With the headmins seemingly moving to ban wgw, the woody cosplay seems like a nice sendoff.

But WGWing was always a "you're getting bwoinked AND the crew is free to hunt you down to murder you immediately"

**Comment by NanoCats** [comment]
~~Also the HOS should get a sherrif badge~~

**Review by Kylerace — APPROVED** [review]
code is good

**Pull request merged**
