### PR TITLE
Fixes people dusting themselves with TK on the SM

### LINKED ISSUE #25870: you can touch sm with tk and it'll dust you
kek

### PR DESCRIPTION
**Pull request by coiax**
Fixes #25870.

:cl: coiax
fix: You can no longer dust yourself by using TK on the supermatter.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
farming fixes

**Comment by Thunder12345** [comment]
Feature

**Comment by lzimann** [comment]
No fun allowed

**Comment by RemieRichards** [comment]
It should instead dismember and dust their head, and only their head.

**Comment by Militaires** [comment]
This is not a bug, the lore is as follows, and it is as appears in "Roadside Picnic"

>The supermatter has a form of consciousness, an S-Consciousness, because a conscious is metaphysical, you do not need to physically contact the SM. In a way or form, your consciousness is absorbed and "indoctrinated" into the S-Consciousness, this common consciousness is what causes the strange effects around the engineering, it's not the radiation at all, but the power of the S-Consciousness influencing the mortal minds around it.

>When the S-Consciousness  is awakened **using stimuli!** or the addition of another consciousness into its "database", the strange effects around the engine room manifest. The SM's movement when active is also a sign of the S-Consciousness physically influencing air pressures around  the SM, moving it in the way it wishes.

>One individual consciousness has almost no effect, but the S-Consciousness, being many different consciousnesses bound together, contains a huge amount of power that must be released periodically in any form of emission, usually radiation, and in higher amounts of power, **Anomalies**.

>As such, due to the fact the the sphere of Human Thought (mob layer) is above the Geosphere (obj layer) and does not require physical contact for its effects to manifest on any visible plane.

**Comment by RemieRichards** [comment]
morphogenic fields

**Comment by optimumtact** [comment]
Sorry but Remie's one is funnier and since I was in the round that the person dusted themself in and just about died laughing I support it.

**Pull request closed without merging**
