### PR TITLE
Adds a new crime to the stock market

### PR DESCRIPTION
**Pull request by Iamgoofball**
i forget where I read this but g o d d a m n

### CODE REVIEW

**Comment by ComicIronic** [comment]
Altered Carbon

**Comment by KorPhaeron** [comment]
@ComicIronic 

I've always wanted to replace cloning with stacks and resleeving

**Comment by ComicIronic** [comment]
>you will never ride the reaper to escape thermal detection while you sneak into the captain's sleeving facility to virus bomb his stack backup before blackmailing him using his permanent mortality

Meths strike again.

**Comment by Supermichael777** [comment]
add tampered with a fire alarm to.

**Comment by Jalleo** [comment]
What about deleting sys32 on a stock market server.

**Pull request merged**
