### PR TITLE
Noir Ambience: Take Two

### PR DESCRIPTION
**Pull request by TrustyGun**
_"The Clown walked through my door like an assistant walking into the bridge; suspicious, but with a story to tell. Her orange hair bounced the way the park trees would sway during the summer. Without even looking, I lit my cigarette and turned towards her. She wanted to tell me about one thing: the Mime."_

Adds two new ambience tracks that play in the detective's office, both by Kevin Macleod:

[ambidet1.ogg](https://www.dropbox.com/s/nuqiofro53fjuyc/ambidet1.ogg?dl=0), Fast Talking.

[ambidet2.ogg](https://www.dropbox.com/s/0pdx1opaehp0k9a/ambidet2.ogg?dl=0), Night on the Docks, Piano.

### CODE REVIEW

**Comment by duncathan** [comment]
Please include license information. I'm pretty sure that because they're Kevin MacLeod it should be fine, so just find the license and include it/attribute if need be and all that.

**Comment by TrustyGun** [comment]
They are both [CC BY 3.0](http://creativecommons.org/licenses/by/3.0/).

**Comment by Ricotez** [comment]
mspa-office-print
:+1: :+1: :+1: :+1: :+1:

**Comment by Niknakflak** [comment]
Ambiance 1 doesn't start very cleanly.

**Comment by PKPenguin321** [comment]
holy fuck this is lovely :+1: :+1: :+1:

**Comment by xxalpha** [comment]
I like the idea and the music, but they're long and 1MB just for the detective's office. I suggest cropping both files.

**Comment by Cheridan** [comment]
better use of MB than vox is

**Pull request merged**
