### PR TITLE
Fixes syringes and droppers being able to transfer banned reagents into certain containers

### PR DESCRIPTION
**Pull request by Sometinyprick**
Intended to stop people from filling up spray bottles with acid.

### CODE REVIEW

**Comment by Delimusca** [comment]
shouldn't this check be in trans_to instead of all the afterattacks?

**Comment by Sometinyprick** [comment]
Probably should, but it works like this.

**Comment by RemieRichards** [comment]
If you're duplicating it in so many places, you should make it a proc ```reject_bad_chem()```

**Comment by Sometinyprick** [comment]
Yea your right
I have no idea how to do that but I suppose I will learn.

**Comment by RemieRichards** [comment]
```
/proc/reject_bad_chem(var/obj/item/weapon/reagent_containers/RC)
	if(istype(RC))
		for(var/bad_reg in RC.banned_reagents)
			if(reagents.has_reagent(bad_reg, 1))
				user << "<span class='warning'> A chemical in [src] is far to dangerous to transfer to [RC]!</span>"
				return 1

```

then replace those checks with ```if(reject_bad_chem(target)) return```

**Comment by Sometinyprick** [comment]
Thanks, I will do that now and make a new pr.
(with less retarded commits)

**Comment by RemieRichards** [comment]
Thanks @Sometinyprick

**Comment by Sometinyprick** [comment]
eh running into a bunch of issues
BYOND is stating I have a undefined variable on 
user << "<span class='warning'> A chemical in [src] is far too dangerous to transfer to [RC]!</span>"
and I'm not sure why.

**Comment by RemieRichards** [comment]
user doesn't exist there, sorry, add a user argument to the proc and set it appropriately.

**Comment by Sometinyprick** [comment]
Ah did that, It takes a while to compile for me so I will test it to make sure I did everything properly.
Thanks for the help, It's made procs a lot less confusing for me.

**Comment by RemieRichards** [comment]
Happy to help.

**Comment by Sometinyprick** [comment]
Actually I'm dumb and have no idea what I fucked up.
I put the proc at the end of [code\modules\reagents_containers] dm and added (var/obj/item/weapon/reagent_containers/RC,mob/user)
I then put the check on three locations where it was before
When I tested it the syringe wouldn't it transfer to anything. 
The dropper wouldn't get reagents
So yeah I'm probably being really dumb and doing something obvious wrong but I have no idea what it is.

**Comment by Sometinyprick** [comment]
So yeah @RemieRichards I have no idea what I'm doing wrong here, I suppose I need to learn a bit more before I start doing shit like this.
Sorry, although this has helped I'm doing something else wrong and I need to figure out what.

**Comment by RemieRichards** [comment]
perhaps, if you put your code up on a pirate pad somebody in coderbus will be able to debug it before you can say "Hi my code is borked"

**Comment by Sometinyprick** [comment]
I will try that, thanks.

**Comment by RemieRichards** [comment]
sorry I couldn't help you myself, I'm tired.

**Comment by Sometinyprick** [comment]
Oh no it's fine.
I'm sure someone will be able to help

**Pull request closed without merging**
