### PR TITLE
Allows spacemen to use age-appropriate drugs by making it so you can now huff N2O to get high. 

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Allows spacemen to use age-appropriate drugs by making it so you can now huff N2O to get high. 

## Why It's Good For The Game

please do not do whippets IRL

## Changelog

:cl:
balance: Allows spacemen to use age-appropriate drugs by making it so you can now huff N2O to get high. 
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
Stop intentionally mislabelling PRs

**Comment by lizardqueenlexi** [comment]
looking forward to a solid 30 seconds of drugginess when there's inevitably slightly too much n2o in the air in the surgery rooms

**Comment by Wallemations** [comment]
30 seconds seems like a LOT

**Comment by GuillaumePrata** [comment]
This buffs the funny aspect of the new clown internals.

Good PR!

**Comment by FlufflesTheDog** [comment]
Hypothetically this makes sense, but in practice it's going to be a huge annoyance because of how little it takes to activate, and how difficult it is to remove trace gasses from a room. 

Doing a single surgery with anesthetic will release enough n2o into the room that everyone there will be giggling for the rest of the shift. Even if someone bothers to set the scrubbers to contaminated for such a minor incident. And this activates at the same percent that giggling does.

**Pull request merged**
