### PR TITLE
Disables kudzu

### PR DESCRIPTION
**Pull request by ghost**
Kudzu is currently quite broken due to some bugs. Needs to be rebalanced or removed.

### CODE REVIEW

**Comment by Kromgar** [comment]
Is this the growth bug?

**Comment by XDTM** [comment]
Grows way too fast and doesnt seem to respect the cap

**Comment by ma44** [comment]
Another option would be to make this into a traitor item, as it doesn't server as anything other than a station destroyer.

**Comment by Kromgar** [comment]
@ma44 people seriously try to argue kudzu can be used for good

**Comment by bobdobbington** [comment]
I hate to say it, but this is needed until the growth and mutation rates are drastically rebalanced. As it is right now it's worse than a singularity when you plant one (juan) max potency seed.

**Comment by bgobandit** [comment]
for fuck's sake we do not need to make MORE things traitor only

**Comment by Arianya** [comment]
As it currently is, kudzu breaks the MC of the server pretty frequently when it spirals out of control. Agree with disabling.

Also just let me use Plant-B-Gone on Kudzu already gosh.

**Comment by kevinz000** [comment]
@bgobandit yeah we need to remove this thing.

**Comment by jughu** [comment]
Something something fire...
Something something pete...
Something something weed killers...
Something something scythes...

We clearly need to buff these things :^)

**Comment by XDTM** [comment]
If it gets reworked it definitely needs some more positive traits

**Comment by KorPhaeron** [comment]
We should gitban people who object to removing things that crash the server

**Comment by Kromgar** [comment]
@KorPhaeron I don't think anyone is arguing for keeping it except ma44.

**Comment by ma44** [comment]
@Kromgar You did thumbs up my post on making it a traitor only item, so you should be gitbanned as well! /s
http://i.imgur.com/y6fChoo.png
Backup image if you decide to unthumbs up my post

**Comment by ma44** [comment]
@Kromgar By that logic then you should be gitbanned as well, as you did thumbs up my post to agree for it to be a traitor only item

http://i.imgur.com/y6fChoo.png

**Comment by CPTANT** [comment]
Or you can fix the bug instead of removing all dangerous things.....

**Comment by XDTM** [comment]
Until someone fixes it i'd rather not let botanists nuke the station

**Comment by Cyberboss** [comment]
Improve don't remove :-1:

**Comment by KorPhaeron** [comment]
@CPTANT 

So fix the bug and it can be readded, easy

**Comment by AdamElTablawy** [comment]
there's no reason not to remove it atm

remove

fix

re-add

it's not fuckin' hard here people it's not like he's shouting that it'll never be re-added

kudzu is a server-fuckin-crashing bug come on

**Comment by bgobandit** [comment]
I'm fine with it being removed if it ever gets fixed because I feel bad bwoinking people who basically annihilate the station without knowing

**Comment by Cyberboss** [comment]
Why not keep the round event if we just don't want people using it?

**Comment by Arianya** [comment]
@Cyberboss Because the broken cap would still happen and it would still kill the server

**Comment by PKPenguin321** [comment]
Nobody thought to tag @optimumtact about this yet? I am guessing https://github.com/tgstation/tgstation/pull/22192 is related to this

**Comment by optimumtact** [comment]
no and also this pr is stupid

fix the fucking bugs or remove the code completely, don't waste my time

**Comment by vcordie** [comment]
oranges has spoken

**Pull request closed without merging**
