### PR TITLE
[DNM] Allows miners to actually see station chat, by clipping spurious *click* messages

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Snick nik nok

:cl: Naksu
tweak: Reduced gun-related chat spam
/:cl:

I thought about removing the message altogether, but it might help out someone who is deaf or has byond audio disabled

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Buggy123** [comment]
You offload the ores beneath you into your ore box.
You offload the ores beneath you into your ore box.

**Comment by RemieRichards** [comment]
to chats should generically handle duplicate messages.
with goon chat being a HTML window, can't we locate the message and stick a 'x2', 'x3' on it?

**Comment by vuonojenmustaturska** [comment]
I believe goon actually has this

**Comment by vuonojenmustaturska** [comment]
DNM this while i take a look at goonchat

**Comment by vuonojenmustaturska** [comment]
The goonchat approach is the right one but trying to do anything wrt goonchat is a massive pain in the ass since if your code decides to not run in the byond environment there's absolutely zero information you can pull from it.

If anyone else wants to waste their time, be my guest. I'm not going to bother.

**Pull request closed without merging**
