### PR TITLE
Removes the sine pope

### PR DESCRIPTION
**Pull request by ChangelingRain**
# Hades is gone.

### CODE REVIEW

**Comment by Repukan** [comment]
how about the cosine and acute priests?

**Comment by KorPhaeron** [comment]
But what about the cosine pope?

**Comment by optimumtact** [comment]
Sawu said please don't they'll fix it.

**Comment by Core0verload** [comment]
-1 to shitcode amount. :+1:

**Comment by Shadowlight213** [comment]
Leave the pope mob itself. remove the map and the seed and all the other shit.

**Comment by Firecage** [comment]
Whats the point of this actually?

**Comment by optimumtact** [comment]
it's unused, basically ninjav2

**Comment by Firecage** [comment]
Optimum. Except, its not unused. Fun Wizard rounds are when the Wizard buys a Dark Seed. And works to eventually use it to summon Hades.

**Comment by optimumtact** [comment]
I said basically unused, that is not the same as unused.

Random wizard rounds every now and again are not enough of a criteria to maintain code where the og developer has gone.

**Comment by Archie700** [comment]
Dark Seed is pretty much a buffed disintegrate, so it's not even fun.

**Comment by Xhuis** [comment]
Will this be addressing the cosine pope?

**Comment by Shadowlight213** [comment]
Just make the pope a megafauna. It's interesting enough honestly.

**Comment by kilkun** [comment]
Stripping features because they aren't the meta is quite possibly the worst reasoning for anything I have ever heard. This isn't counter-strike.

**Comment by KorPhaeron** [comment]
what if I'm stripping it because I think it's unfun

**Comment by ChangelingRain** [comment]
depoped

**Comment by kilkun** [comment]
thats a much better reason, actually.

but with wizard when has the question ever been about what's "fun" for the crew. who cares about the crew, there's a fucking space wizard look how cool he shoots fireballs and explodes people with a wink.

**Comment by Shadowflame909** [comment]
I wish I had a chance to try this. YOU LIED TO ME WIKI YOU SAID IT WAS DEPRECIATED.

**Pull request merged**
