### PR TITLE
Steal objective can now be cashed out early for less reward as soon as you place the bug on. Removes smuggling objective and adds a new 'Destroy Machinery' objective

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

Steal objective can now be cashed out early for less reward, but completing the time in its entirety will give extra TC and reputation.
The smuggling objective has been removed and replaced with the 'Destroy Machinery' objective, which focuses on disrupting workflow by destroying stuff like protolathes, telecomms and research servers.
Made the easier steal objectives worth slightly less TC

## Why It's Good For The Game

Smuggling objective had a problem of just being high risk for very little reward, not to mention being extremely repetitive and not open-ended at all. It was a good idea, but was too limited in execution.
The 'Destroy Machinery' objective will focus on destroying important machinery and creating actual sabotage of sorts.
The steal objective's timer was decently long, being up to 15 minutes of a wait where a player would be locked out of doing another objective. The ability to skip this timer at the cost of having a reduced reward lets players who have nothing better to do to be able to continue doing objectives if they so wish.

## Changelog

:cl:
add: Adds a new 'Destroy Machinery' traitor objective that focuses on destroying various important pieces of machinery around the station.
add: Traitor steal objectives can now have their timer skipped as soon as the bug is placed onto the target item. However, doing so will give reduced rewards.
del: Removes the smuggling traitor objective
balance: Low risk steal objectives reward slightly less TC
/:cl:

### CODE REVIEW

**Comment by exymian** [comment]
Thank you for adding my suggestion, very cool 👍🏻

**Comment by DaydreamIQ** [comment]
What kind of machinery gets targeted in this instance? And what exactly stops people from building said machinery only to 'destroy' it?

**Comment by Watermelon914** [comment]
> What kind of machinery gets targeted in this instance? And what exactly stops people from building said machinery only to 'destroy' it?

the very fact that you can't print these boards off. Additionally, when the objective gets generated, it takes a list of the current machinery that exists, so building new instances and destroying them will not work.

**Comment by MetalClone** [comment]
So long as destroy objectives never return after the machine is rebuilt it won't be that big of a problem. Otherwise this will just bring more attention to self-security action in departments to defend their machinery as no one wants to just stand there and watch and then have nothing to do for the next 30 minutes as they said for a busy cargo and command to go out of their way to get an ore silo link. There should be a circuit printer on the bridge that allows boards to be reprinted.

**Comment by Watermelon914** [comment]
> So long as destroy objectives never return after the machine is rebuilt it won't be that big of a problem. Otherwise this will just bring more attention to self-security action in departments to defend their machinery as no one wants to just stand there and watch and then have nothing to do for the next 30 minutes as they said for a busy cargo and command to go out of their way to get an ore silo link. There should be a circuit printer on the bridge that allows boards to be reprinted.

Sabotage is supposed to be traitor's thing, so they should be defending their department stuff

**Review by tralezab — APPROVED** [review]
actually quite clean through and through

**Pull request merged**
