### PR TITLE
Covering your mouth when you cough/sneeze now stops the spread of germs.

### LINKED ISSUE #37347: Sneezing escapes bio suits
Server revision compiled on: 2018-04-15

If you're wearing a bio suit and you sneeze, others can be infected.

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #37347

:cl: ShizCalev
fix: Covering your mouth when you cough/sneeze can now help stop the spread of germs.
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
Do medical masks cover the mouth too?

**Comment by ShizCalev** [comment]
@Barhandar Yes they do.

Changed it to also check the mask's bio armor value.

**Comment by XDTM** [comment]
This prevents airborne spread caused by shedding pathogen, like the combustion threshold bonus

**Comment by ATH1909** [comment]
Isn't this a massive nerf to sentient diseases (and to diseases in general?)?

**Comment by SouDescolado** [comment]
Considering that this is a buff for people, it should have a downside. Could it be that when people speak with their face covered it gets muffled unless you are close (maybe up to 1 or 2 squares). I recommend 2, since then you would be able to talk with the HoS if he was at his table, but not if he was inside doing something else, giving an incentive to remove the mask.

**Comment by ShizCalev** [comment]
Current downside is that it checks for bio armor from what you're wearing (and as a note, breathmasks and gasmasks don't have bio armor, so you'll be vulnerable if you're wearing them. Tradeoff is that surgical masks and such don't support internals.)

**Comment by SouDescolado** [comment]
Didn't read the code, sorry. Thanks for clearing that.

**Comment by XDTM** [comment]
checks the bio armor for the sender, but if the receiver is breathing through internals they'll still be immune

**Comment by epochayur** [comment]
what the hell are you guys smoking where you think this needs a nerf/buff

the more common-sense mechanics like this we get, the better IMO

**Comment by nicbn** [comment]
Gasmasks should have bioarmor, also maybe make any mask protect you as long as you're on internals?

**Comment by nicbn** [comment]
nvm

**Comment by optimumtact** [comment]
Adding muffling when you cover your mouth would be cool too though :+1:

**Pull request merged**
