### PR TITLE
New Shields and Sprites for them

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
Updates shield sprites to new more polished and 3/4 perspective ones.

<details>

shielding show

</details>

Adds 2 new shield types:
- **Improvised Shield.** Made out of 10 iron sheets and 2 sticky tape pieces. Weaker then buckler shield and breaks after 2 gunshots or 4 baton hits, but has a 50% (BASE FOR ALL OTHER SHIELDS) blocking chance instead of 30% that buckler has. Bulky
- **Ballistic Shield.** Printed at Security Techfab for a lot of titanium after getting weapon research. Strong against projectiles, but weaker than riot shield against melee. Bulky

Both of these shields break, and both of them are their own subtype. As such you can still only craft strobe shield with a riot shield.
## Why It's Good For The Game

The sprites of shields were very ancient and extremely flat, this gives them a more refreshed look.

Ballistic Shield is added because Riot Shield was weakened against projectiles, Ballistic Shield gives the crew a way to get access to protection against projectiles at some point in the round.
Improvised Shield adds a second improvised shield in the game (after Buckler Shield). It's balanced by being weaker than Buckler, but higher block chance, this adds an interesting choice for players on which shield to craft.
## Changelog
:cl:
add: Adds 2 new shields to the game! Ballistic Shield - researched by Science, and Improvised Shield - made out of iron and sticky tape
image: Riot, Strobe, Telescopic, Energy shields got new less flat sprites!
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]
sprites look good to me

**Comment by DrDiasyl** [comment]
Well, these failed checks are completely unrelated to what I did so I guess it's like this for everyone.
Stupid monkey business lol

**Comment by Jackal-boop** [comment]
50 block chance for an easily make able item is insane.

**Comment by Loafin34** [comment]
>assistants parrying disabler and laser shots using plates of iron and a crate
sounds good

**Comment by DrDiasyl** [comment]
> 50 block chance for an easily make able item is insane.

It's piss weak and bulky.

Dies from 2 laser/bullets, or 4 baton hits.

**Comment by SomeoneYouProbablyKnow** [comment]
Sproits - Neat
Ballistic shield - Neat but it's RnD locked so you'll never see it

Improvised shield.. Weird. It is kinda insane. Fights don't last long enough for the shield's health to matter. Especially if you're crewside. It's just gonna be another mechanic you can abuse to validhunt better if you know it. 

Also say goodbye to all plastic flaps on the station, just like you can't get an inducer anymore because of the crossbow.

**Comment by SomeoneYouProbablyKnow** [comment]
Oh yea Bucklers are funny. But when i say abused i don't mean everyone gonna have one. i mean the select few people who have 100 item roundstart gearup checklist are going to use it and benefit from it. 
There aren't many people willing to spend time abusing chemistry but you shouldn't be helping the half dozen who already make a personal box of high tier meds each round.

**Comment by SimplySmiley123** [comment]
> 50 block chance for an easily make able item is insane.

Breaks from a breeze tho

**Comment by SomeoneYouProbablyKnow** [comment]
> > 50 block chance for an easily make able item is insane.
> 
> Breaks from a breeze tho

Have you seen the nuckie shield module? It too only protects you from 1 or 2 hits. Obviously not comparable but something running out of juice fast isn't really the end of the world when it lets you not die.

**Comment by SimplySmiley123** [comment]
> > > 50 block chance for an easily make able item is insane.
> > 
> > 
> > Breaks from a breeze tho
> 
> Have you seen the nuckie shield module? It too only protects you from 1 or 2 hits. Obviously not comparable but something running out of juice fast isn't really the end of the world when it lets you not die.

And it infinitely recharges passively without having to craft anything, nor do you have to keep that shield in-hand (it's your suit after all), and blocks anything and everything bar explosions guaranteed 100% instead of it being up to RNG wether something gets blocked by it.

Yeahhh doesn't compare.

**Comment by Jackal-boop** [comment]
50 block chance is still insane and will decide many fights. Tune it to 30

**Comment by SomeoneYouProbablyKnow** [comment]
30 is the buckler. At this point might as well say not to add it

**Comment by DrDiasyl** [comment]
> 50 block chance is still insane and will decide many fights. Tune it to 30

50% is the base percentage of all shields other than buckler.
If I make it 30% for improvised shield, there will be no point in building it as it would just be buckler but way worse.

**Comment by bigfatbananacyclops** [comment]
something looks wrong with how plain the eshield look from side

**Comment by Admiral-Gigaton** [comment]
can i make my valid hunter extreme flash shield out of improv shield?

now we just need a deployable shield, then we be playin battlefield fr

**Comment by DrDiasyl** [comment]
> can i make my valid hunter extreme flash shield out of improv shield?
> 
> now we just need a deployable shield, then we be playin battlefield fr

NO, you **CAN'T** make a strobe shield out of an improvised shield.

Making a strobe shield requires a riot shield.

**Review by Ghommie — CHANGES_REQUESTED** [review]
These are an improvement, however I've seen a more badass candidate for the ballistic shield sprites downstream:
wew

[the PR that added it](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14085)

Should you use them instead, thank 'em in the CL ig.

EDIT: Oh, make sure remove the cross from the shield icons above, could be a lil' eh for a generic ballistic shield.

**Comment by DrDiasyl** [comment]
> These are an improvement, however I've seen a more badass candidate for the ballistic shield sprites downstream:
> wew
> 
> [the PR that added it](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14085)
> 
> Should you use them instead, thank 'em in the CL ig.
> 
> EDIT: Oh, make sure remove the cross from the shield icons above, could be a lil' eh for a generic ballistic shield.

But my ballistic shield sprite was already approved by @Wallemations , why we can't just use it? This one really breaks out from the rest of my resprites by design.

**Comment by DrDiasyl** [comment]
Also I find this just slightly insulting ngl.

**Comment by Ghommie** [comment]
I had a hunch you would be too proud of your own sprites, like you spent too much time making them and don't want to walk back to it. 😔

**Comment by Stalkeros2** [comment]
> [the PR that added it](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14085)

hiiiiiii :3
It's an Eris sprite I've modified a little bit (literally just added the cross) so it might be out of place by a wide margin.

**Pull request merged**
