### PR TITLE
Fix RCL sprites

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
fix: RCL and Ghetto RCLs are no longer invisible
fix: RCL action button now has a sprite
/:cl:

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
@tgstation/commit-access Please merge this ASAP, it's annoying having invisible RCLs as nobody sees them

**Comment by octareenroon91** [comment]
What's an RCLagain?

**Comment by MoreRobustThanYou** [comment]
Rapid Cable Layer

**Comment by lordpidey** [comment]
You messed something up with git.  There's no reason for this to be 8 commits.

**Comment by MoreRobustThanYou** [comment]
True, but that doesn't affect the pr itself

**Comment by lordpidey** [comment]
Fair enough, the PR can be quashed, but it still raises concerns.

**Pull request merged**
