### PR TITLE
Allows for removing lightbulbs w/o gloves (burns hands) and adds time for lightbulb removals (3 seconds for resisting heat, 25 for tk and 10 for bare hands)

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

you can remove a lightbulb from its fitting without any protection after 10 seconds, does 20 burn damage, now with tk it takes 2.5 seconds and with protection 3 seconds

## Why It's Good For The Game

its easier to escape permabrig than regular brig, which there is no way of without another person's help/some implants and stuff. this can obviously be stopped by the sec team/warden, just gives a chance to the single guy in brig without a timer set when all of sec are going somewhere

## Changelog
:cl:
balance: nanotrasens brand new mk.2 light bulbs allow you to remove them without any protection, although they do take some time now
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
this isnt tested but i hope it works it better do

**Comment by Tlaltecuhtli** [comment]
the hand burning is shit because 95% of the time its you clicking on anything and it happens to catch the giant light bulb sprite, about brig just remove the light bulb damage else wardens are gonna round start remove light bulbs, you can easily escape by asking the greytiders outside or random borgs walking around or by sec inefficiency to remove your toolbelt

**Comment by ExcessiveUseOfCobblestone** [comment]
wtf is gbj

**Comment by MrPerson** [comment]
Gay baby jail. An impossible to escape jail. Come on grandpa, get with the times.

**Comment by ExcessiveUseOfCobblestone** [comment]
oh in that case stop being a """"gb"""" if u don't wanna go to gbj

**Comment by Shadowflame909** [comment]
>All those dislikes

Maybe I wouldn't be trying to break out of my temporary cell if you chucklefucks didn't drag me around for 10 minutes and then after my constant screaming because I've been sitting in a cell with an unset timer for 5 minutes. You set it to the maximum 20 because I'm annoying you

Well, I wouldn't annoy you if you just let me out already.

**Comment by Teepeepee** [comment]
I, as a sec player, welcome the challenge

**Comment by ninjanomnom** [comment]
While I've got nothing against the idea of letting people take out the hot bulbs by hand, the random chance seems arbitrary. Perhaps make it use a do_after and burn you more than currently if you actually go ahead and unscrew it the whole way?

**Comment by PKPenguin321** [comment]
If this gets merged sec will just remove all the light bulbs from the cells and then I'll be forced to wallow in darkness like a chump

**Comment by Fikou** [comment]
> While I've got nothing against the idea of letting people take out the hot bulbs by hand, the random chance seems arbitrary. Perhaps make it use a do_after and burn you more than currently if you actually go ahead and unscrew it the whole way?

that sounds better chief i did it

**Comment by ishitbyabullet** [comment]
It sounds like lightbulbs now do more damage when  removed. **_How about that isn't a thing_** so hallway combat doesn't turn into HAH LOOK AT DUMBASS HE CLICKED THE SPRITE NOW HE'S SLOW AND HE WILL NOW DIE

I've never heard of the legendary lightbulb breakout method however I feel like there's far superior solutions such as nerfing the lightbulb damage, making all the lightbulbs in brigcells be more weak than real lightbulbs, etc. The increased timer is fine however it is not fine for there to be a random fucking instant 20 damage structure out in the hallways.

**Comment by ishitbyabullet** [comment]
Oh, it doesn't just fucking gank you anymore for being the loser who decided to try and punch someone in the hallways.

I feel like just making brigcell lightbulbs weaker or some shit would work however I'm glad the fear of touching a lightbulb and then being fucked over is gone.

**Comment by bigfatbananacyclops** [comment]
i think this would just make the warden feel worse because he would have to check on prisoners he completely stripped too, specially if theyre tides, people constantly breaka out other people from jail and some are usually left with some tools allowing them to escape and with their locker too. Im pretty sure people on brig has plenty of many options, its rare to see a warden reinforce brig cells for extra protection, the warden haves a whole brig to check and its not even hard at all for the brig to get robbed, even the armory.

**Comment by optimumtact** [comment]
power crepe

**Pull request closed without merging**
