### PR TITLE
Returns medical jumpsuits for medical doctors and CMO

### PR DESCRIPTION
**Pull request by iwishforducks**
## About The Pull Request

Gives medical doctors and CMOs back their jumpsuits. Additionally removes their surgery cap from their starting gear.
Surgical scrubs and surgery caps are still available in vending machines and in other places.
Coroner still has their scrubs.

## Why It's Good For The Game

The scrubs have never made sense to be as part of a medical doctor's starting gear. Scrubs are meant to be put on for one surgery and replaced afterwards, not to be worn 24/7. Also, in my opinion, they look goofy as hell. Especially when doctors are wearing lab coats over them.

[_Being a medical doctor does not inherently mean you're doing surgeries either._](https://www.youtube.com/watch?v=8byiwOY5XM0)

## Changelog

:cl:
image: Medical doctors and CMOs now start with their jumpsuits rather than surgery scrubs and caps.
/:cl:

### CODE REVIEW

**Comment by iwishforducks** [comment]
Comparison screenshots:

dreamseeker_nOooWCgMJa
dreamseeker_56d9cRKHDS

**Comment by GuillaumePrata** [comment]
The best thing about the previous Medbay resprite was that it moved doctors into their own recognizable uniform.

If we revert back to jumpsuits, chemists and doctors will go back to looking the same and if it wasn't for the fact virologist is kill, they would also fall on the same issue of triple lookalike jobs under the same department.

If anything, doctors should lose their labcoat to move further away from looking like a chemist and give everyone at medbay their own distinct look that fits their unique job.

**Comment by Fikou** [comment]
chemists are orange while doctors are blue i think its pretty distinct

**Comment by GuillaumePrata** [comment]
> chemists are orange while doctors are blue i think its pretty distinct

Yes, for 10 pixels in their uniform.

**Comment by iwishforducks** [comment]
If the issue is that the jumpsuits (and lab coats) between medical doctors and chemists are too similar then we should make the sprites for those more unique. I’ll see what I can workshop sometime later today.

For the record, I don’t necessarily disagree that chemists and doctors look similar from a glance. Chemists only have a stripe of orange on their coats to differentiate them right now. There could be a lil more on both chemists and doctors to help them stand out from each other.

With the virologist being removed and any medical doctor able to work viro on top of working the pharmacy then I see every need to move away from surgical scrubs when it’s clear that medical doctors do more than just surgery.

**Comment by Wallemations** [comment]
I'll be honest that I prefer the scrubs due to them being unique & the fact that most people aren't going to quick-swap into scrubs for surgery

It makes sense for chemists to have jumpsuits but I think a medical doctor would be doing a lot of surgery anyways

The jumpsuit should be the one in the wardrobe imo

I have no strong feelings about the cap though

**Comment by MatrixOne500** [comment]
There isn't much to say that's not expressed adequately with the ratings on the post - the surgery cap is horrific first of all, it ruins everyone's hair and also ruins the security records depiction of all medbay staff when trying to see how people look. The scrubs look like adult diapers, are strange, bottom heavy, and make no sense as scrubs are worn once and disposed of to prevent contamination. The white starting gear and jumpsuit is perfectly adequate and the scrubs options are not removed so people can still customize their look. Great change.

The case for making chemists and doctors look more distinct is not without merit but not really a part of this PR, and I never had issues distinguishing a chemist. The orange vs blue accents are very distinct even if they're just a few pixels.

You can really see how important this change is when you look at the shuttle around midround, and it's full of discarded surgery caps.

**Comment by norsvenska** [comment]
I can get behind removing the surgical caps from the roundstart equipment. I like them, but I don't like having my character's hair hidden by default in the records.

As for the jumpsuit change, I'm not a fan of how bland it makes everyone look. The scrubs at least added a little bit of color in an otherwise completely white outfit. Yes, the scrubs are still available in the vendor, but many people I run into make minimal changes to their outfit. I dunno. I get it makes more sense from a realism perspective to have everyone in a jumpsuit most of the time, but this is SS13 we're talking about.

That's just my take on it.

**Comment by axietheaxolotl** [comment]
I originally wanted to make the surgical cap hide the hair, as that drastically it improves how it looks. However, the FLBH Mafia put a toe in my mailbox so I had to backpedal on it.

**Comment by iwishforducks** [comment]
> I originally wanted to make the surgical cap hide the hair, as that drastically it improves how it looks. However, the FLBH Mafia put a toe in my mailbox so I had to backpedal on it.

the surgical cap does hide the hair? unless you're talking about a different item.

**Comment by ShizCalev** [comment]
Screenshot_20240520_005557_Firefox

**Pull request merged**
