### PR TITLE
Dismemberment tweaks

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Burn weapons that are large enough can dismember, but they ash the limb they take off.

Armour penetration factors into dismemberment, so eswords dismember much more quickly than other weapons.

Limb max damage lowered a bit so limbs might actually come off before crit sometimes.

Reasoning behind this: Dismemberment is cool but it almost never happens outside of bombs or surgery (or the guy already being dead). I realize that dismemberment too often will be awful as well, so I plan to testmerge this and play with the numbers until people are happy with it.

:cl:
rscadd: Burn weapons can now dismember, and they reduce the limb to ash in the process
rscadd: Weapons with high AP values will now dismember limbs much easier. These values are subject to change depending on how things play out over the next week or two.
rscadd: Various weapons with high AP values had them lowered (chaplain scythe, energy sword, dualsaber) to prevent them taking limbs off in a single hit.
rscadd: The chaplain has two new weapons (they are mechanically identical to previous weapons, before anyone gets upset about balance). One is dismemberment themed, the other is related to a new antagonist.
/:cl:

### CODE REVIEW

**Comment by Aloraydrel** [comment]
ayy

**Comment by MMMiracles** [comment]
Burn damage ashing limbs doesn't seem to carry to projectiles, unless I read something wrong.

Laser cannon ashing limbs off would be super cool.

**Comment by KorPhaeron** [comment]
Can projectiles dismember at all? I need to go look at that code

**Comment by MMMiracles** [comment]
I mean projectiles are under /items, the proc calls for anything under /items, but I'm pretty sure there's no projectiles with a weight class above 3.

**Comment by LatD** [comment]
I thought the damage numbers were already pretty low. A small explosion can easily take out some limbs and cause the victim to go into crit. Before dimemberment the victim gets healed from crit fast and he could return to work but must now spend another 10 minutes trying to get robo limbs before he can actually do anything.

**Comment by KorPhaeron** [comment]
@LatD 

The explosion damage is low right now, you have to deal 75 damage to a single limb before it will come off currently, which is very unlikely to happen without critting them first (from missing and hitting the chest a couple times)

**Comment by AdamElTablawy** [comment]
projectiles dismembering is a bad idea because that'll just devolve to shotgun head explosions and laser cannon misfires accidentally evaporating heads during blob

**Comment by Anonmare** [comment]
Shouldn't an e-sword and burn damage dismembering cauterise the wound?

**Comment by PKPenguin321** [comment]
>shotgun head explosions and laser cannon misfires accidentally evaporating heads during blob

Sign me the fuck up

**Comment by demonfiren** [comment]
I am now even more afraid of gatling memes.

**Comment by Core0verload** [comment]
Will burning the limbs destroy organs in them? I don't think it's a good idea.

**Comment by KorPhaeron** [comment]
@Core0verload 

Things automatically drop their contents when they burn up

**Comment by kevinz000** [comment]
No...
We don't even have enough ways of FIXING limb damage
No need to have RNG knockouts when aimed for head and RNG knockdowns when aiming for chest become RNG GGNORES aiming at anything.

**Comment by KorPhaeron** [comment]
Mekhi please read the PR there is no RNG involved at all

**Comment by PKPenguin321** [comment]
^

**Comment by KorPhaeron** [comment]
@RemieRichards @AnturK @phil235 @Jordie0608 @ChangelingRain @Cheridan 

Please merge its been up all day and I don't think anyone even noticed it

**Comment by KorPhaeron** [comment]
Actually I'm gonna just combine the HF blade PR into this one since its along the same lines and I'll probably conflict with myself otherwise

**Comment by KorPhaeron** [comment]
@RemieRichards 

Lowered the esword AP

**Comment by PKPenguin321** [comment]
kor please do the "shotgun head explosions and laser cannon misfires accidentally evaporating heads during blob" thing now

**Comment by KorPhaeron** [comment]
After the current gun PRs sure

**Pull request merged**
