### PR TITLE
Moves His Grace's sprites to weapons.dmi

### PR DESCRIPTION
**Pull request by ChangelingRain**
NOT A TOOLBOX

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
but it makes sense to be in the toolbox area bexause it's a green toolbox

**Comment by Militaires** [comment]
what @ExcessiveUseOfCobblestone , this will just make things more confusing and tbh it's useless

**Comment by ChangelingRain** [comment]
It's not a toolbx and doesn't have toolbox latches right now. I'm giving it its latch back.

**Comment by ShadowDeath6** [comment]
"why is a toolbox in weapons when there's a file that contains every other toolbox"

**Comment by ChangelingRain** [comment]
what is not actually a toolbox for 500

**Comment by Militaires** [comment]
holy fuck nobody gives a shit about your stupid headcanon stop making this more confusing when they shouldnt be

**Comment by ChangelingRain** [comment]
It is literally not a toolbox it's a unique weapon and it goes in weapons.dmi, simple.

**Comment by Militaires** [comment]
@CHANGELINGRAIN BECAUSE IT'S A TOOLBOX PEOPLE WILL SEARCH FOR IT IN STORAGE.DMI FIRST JOAN STOP MAKING THIS DIFFI

**Comment by dannno** [comment]
who cares lol

**Comment by ShadowDeath6** [comment]
This pr does kind of hinder changes made since you wouldn't look in weapons.dmi for an esword that looks like a backpack or something

**Comment by RemieRichards** [comment]
Anyone sensible would look at the item's definition to see what file it's assets are in, not just assume "lol it's a toolbox so it's clearly with the others"

**Comment by ChangelingRain** [comment]
As a 'compromise' i've put `icon = 'icons/obj/weapons.dmi'` below the icon_state/item_state so anyone who looks at the file knows exactly what icon file it's using.

**Comment by dannno** [comment]
so much debate for something that doesn't really matter that much
"i can't find his grace, where is it?!?! someone help"
"weapons.dmi"
"oh ty"
"np np"

**Pull request merged**
