### PR TITLE
Better conscription kit, public lavaland mining vendor

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
With the removal of the extra miner gear on lavaland and addition of public mining access, I feel the conscription kit needs to include a pka. If someone buys you a kit it should be an upgrade to the public gear, but it currently gives you a pickaxe. Bumped the vendor price up slightly to compensate, and the cargo price slightly down since you can buy them cheaper in the vendor using the budget card.
Also added a public mining vendor, I don't think we should be encouraging breaking into the mining wing to spend their hard earned mining cash.

## Why It's Good For The Game
Conscripting miners gives them actual starting level mining equipment. 

## Changelog
:cl: Skoglol
tweak: Mining conscription kits now cost 1500, but has a PKA and a survival knife. Cargo cost reduced to 2000.
tweak: Added public mining vendor to lavaland base.
/:cl:

### CODE REVIEW

**Comment by Swagile** [comment]
and a sec lite maybe, because you can add the sec lite to the PKA for actual light

**Comment by 81Denton** [comment]
2000 is a good price, this way it's the 1500 base price plus 500 for the crate.

**Comment by CRITAWAKETS** [comment]
The only issue i've noticed with this is the fact that you can just buy yourself a conscription kit and gain access to mining without the permission of the HOP. At the same time, the HOP doing his job basically never happens.

**Comment by kriskog** [comment]
> 
> 
> 2000 for the cargo pack is a good price, that way it's the 1500 base price plus 500 for the crate.

Thats what I did

**Comment by 81Denton** [comment]
@CRITAWAKETS That also applies to the mining vendor ever since it's no longer using miner points.

**Comment by ExcessiveUseOfCobblestone** [comment]
The only reason the cargo version exists is because conscription was pointblocked instead of cashlocked.

I don't really see why both need to exist when they're literally the same thing with a 500 adjustment for the crate that we'll have to maintain.

**Comment by kriskog** [comment]
Anyone with QM access or an emag can buy and use the cargo one, only someone with cash on their card can use the one in the vendor. This might happen if a QM hasnt arrived, and the budget card isnt available. I think we should leave the cargo one, as it has uses.

**Comment by ExcessiveUseOfCobblestone** [comment]
We need to move dept IDs to the lockers so we aren't getting btfo'd because people didn't join a certain job yet.

**Comment by Tlaltecuhtli** [comment]
there is no orm in lavaland, how are they gonna get money to spend

**Comment by Akrilla** [comment]
Massive +1 for public mining vendor

**Comment by kriskog** [comment]
> 
> 
> there is no orm in lavaland, how are they gonna get money to spend

I reckon we could hook the smelter on lavaland up to some point redemption kinda like on the gulag shuttle. When someone codes it, that is. For now I assume they ask to be let into cargo.

**Comment by ExcessiveUseOfCobblestone** [comment]
smelter should be phased out in favor of ORM, there's no benefit to using the smelter outside of wanting the mechanic to "feel" more old fashioned than the ORM.

**Pull request merged**
