### PR TITLE
Scannergates 2.0

### PR DESCRIPTION
**Pull request by MrsTonedOne**
## About The Pull Request
 XGWvtJbPH9

Scanner Gates can now have assemblies attached to them! Allow you to trigger anything you want with them!

There are 5 wires on them now.
Successful Scan
Failed Scan
Toggle Signaling
Disable Signaling
Enabling Signaling

## Why It's Good For The Game
Imagine the possibilities! Traps! Security Checkpoints!

## Changelog
:cl: Axanthic
add: Scanner Gates can now trigger assemblies!
/:cl:

### CODE REVIEW

**Comment by MrStonedOne** [comment]
¯\_(ツ)_/¯

Seemed like the code is all there and ready

**Comment by Iamgoofball** [comment]
take his name off the changelog tho lmao

**Comment by Iamgoofball** [comment]
@Axanthic

**Comment by Axanthic** [comment]
> take his name off the changelog tho lmao
That's pretty scummy, go ahead. Between you and oranges being verbally abusive you're just further cementing I should of never touched TG and won't in the future. Clearly it's too much to be ask for. Enjoy porting my future work.

Saves time for me. Bee has monstermos so it doesn't run like trash, not to mention they're less afraid of implementing changes such as monstermos.

**Comment by MrDoomBringer** [comment]
image
😏

**Comment by MrDoomBringer** [comment]
image
image
😏

**Comment by Axanthic** [comment]
> 😏
"Who let this dog off his leash"
"Hippie players deserve to banned and bullied"
"Good luck getting anything approved by me"
and he was rude when discussing circuit requirements as well as when I had asked him another question in the past.

Those are just the times off the top of my head, then he kicked me from the discord.
But that's acceptable due to my github posting history or something? Ok

**Comment by Iamgoofball** [comment]
perhaps next time you shouldn't ping maintainers to request a merge alongside a "joke" about the Holocaust

**Comment by Axanthic** [comment]
> perhaps next time you shouldn't ping maintainers to request a merge alongside a "joke" about the Holocaust

Literally never mentioned that. Also isn't the nword allowed on tg station.

**Comment by Axanthic** [comment]
I've reached out to everyone regarding this to smooth things over - Please don't merge this as I have an update for this I'm going to push out.

**Pull request closed without merging**
