### PR TITLE
Autodoc documentation, general META doc refactor and tidy.

### PR DESCRIPTION
**Pull request by optimumtact**
todo
guide on documentation

### CODE REVIEW

**Comment by Qustinnus** [comment]
does this mean i dont have to do it for my materials pr




(thats a joke)

**Comment by optimumtact** [comment]
NO REFUNDS, NO RETURNS, NO COMMENTS, NO SERVICE

**Comment by JJRcop** [comment]
Meta docs or: docs about docs or: how to doc

https://github.com/SpaceManiac/SpacemanDMM/blob/d304549816989dee8891ba2496ae7c8d00d0405b/README.md#documentation-generator

**Comment by optimumtact** [comment]
Please add dm autodoc to your code
examples

https://www.oranges.net.nz/~oranges/dmdoc/code/modules/mob/mob_movespeed.html
```
/*! How move speed for mobs works
Move speed is now calculated by using a list of movespeed modifiers, which is a list itself (to avoid datum overhead)
This gives us the ability to have multiple sources of movespeed, reliabily keep them applied and remove them when they should be
THey can have unique sources and a bunch of extra fancy flags that control behaviour
Previously trying to update move speed was a shot in the dark that usually meant mobs got stuck going faster or slower
This list takes the following format
\`\`\`Current movespeed modification list format:
        list(
            id = list(
                priority,
                flags,
                legacy slowdown/speedup amount,
                movetype_flags
            )
        )
\`\`\`
WHen update movespeed is called, the list of items is iterated, according to flags priority and a bunch of conditions
this spits out a final calculated value which is used as a modifer to last_move + modifier for calculating when a mob
can next move
Key procs
* [add_movespeed_modifier](mob.html#proc/add_movespeed_modifier)
* [remove_movespeed_modifier](mob.html#proc/remove_movespeed_modifier)
* [has_movespeed_modifier](mob.html#proc/has_movespeed_modifier)
* [update_movespeed](mob.html#proc/update_movespeed)
*/
```
https://www.oranges.net.nz/~oranges/dmdoc/datum.html#proc/Destroy
```
/**
  * Default implementation of clean-up code.
  * 
  * This should be overridden to remove all references pointing to the object being destroyed, if
  * you do override it, make sure to call the parent and return it's return value by default
  * 
  * Return an appropriate QDEL_HINT to modify handling of your deletion;
  * in most cases this is QDEL_HINT_QUEUE.
  *
  * The base case is responsible for doing the following
  * * Erasing timers pointing to this datum
  * * Erasing compenents on this datum
  * * Notifying datums listening to signals from this datum that we are going away
  *
  * Returns QDEL_HINT_QUEUE
  */ 
/datum/proc/Destroy(force=FALSE, ...)
```

You can run this tool yourself by downloading the stand alone exes
https://github.com/SpaceManiac/SpacemanDMM/releases
dmdoc.exe for windows and dmdoc for linux. Note the default output folder is dmdoc, so you may want to rename the dmdoc exe itself, or move it to a location outside of the repo.

It can be run from the cli in the top level of the tgstation code
`/path/to/dmdoc` and will put the html into the tgstation/dmdoc folder.


It has full markdown support.

Please spend some time documenting the change you're adding, as well as adding an overall module document that explains how the system overall works roughly

You can also document vars with either `/** */ or ///`

**Comment by PKPenguin321** [comment]
I'm assuming smaller changes won't require this

**Comment by optimumtact** [comment]
You assume wrong, I expect most methods and vars to be documented. even if self explanatory a one liner is still required

///Does stuff

**Comment by JJRcop** [comment]
At that point it's not much to write ///Special subtype for lolipopstation

**Comment by SgtxRootbeer** [comment]
i understand its likely handled by now
but

>ALL PR'S ABOVE THIS MUST HAVE AUTODOC
>TODO: GUIDE ON HOW TO AUTODOC

**Comment by nicbn** [comment]
> even if self explanatory a one liner is still required

I stand against this. This breaks DRY, most (good) code is self-documenting.

[Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Function_Argument_Comments)
> Do not state the obvious. In particular, don't literally describe what code does, unless the behavior is nonobvious to a reader who understands C++ well. Instead, provide higher level comments that describe why the code does what it does, or make the code self describing.

I'd rather see a function like `delete_items()` than a function like `delete_items() /// Deletes items`. The extra statement is just distracting.

**Comment by PKPenguin321** [comment]
that and things like "changes 1 character typo" PRs don't need to be in a documentation manual

**Comment by optimumtact** [comment]
The autodoc won't generate a reference for the proc unless it's commented, comments must be made

**Comment by bgobandit** [comment]
but why

**Comment by Jared-Fogle** [comment]
in the distant future ask for test coverage too

**Review by Tlaltecuhtli — CHANGES_REQUESTED** [review]
bloat

**Cobby Note:** Don't use the review system for 2cent-ing

**Comment by actioninja** [comment]
> that and things like "changes 1 character typo" PRs don't need to be in a documentation manual

PR title: ALL PR's ABOVE THIS PR MUST HAVE AUTODOC ON ALL NEW METHODS
pretty sure that "changes 1 character typo" PRs aren't going to have new methods.

**Comment by Akrilla** [comment]
Commenting on each function, even if it's just a short line is fairly standard.

**Comment by Akrilla** [comment]
> I'd rather see a function like `delete_items()` than a function like `delete_items() /// Deletes items`. The extra statement is just distracting.

The docs are for function definitions, not calls.

**Comment by nicbn** [comment]
> The autodoc won't generate a reference for the proc unless it's commented, so there must be at least a one liner comment

What about "private" methods and fields? And what about inheritance? It's not ergonomic to write `/// does initialization` every time you just want to override an `Initialize()`.

> The docs are for function definitions, not calls. That's a bad comment anyway. Why are you deleting these items, what items, etc all could be used to make that a better explanation.

But I am talking about definitions. Imagine this is a proc for some kind of structure, like a linked list, the items could be anything. It's just an example.

**Comment by MrStonedOne** [comment]
Can't say I'm surprised.

Let's just add a new requirement BEFORE finishing the documentation and guides on understanding how to meet that requirement. 

Because actually giving a fuck about developer ease of use is apparently only something I do.

**Comment by Whoneedspacee** [comment]
> > even if self explanatory a one liner is still required
> 
> I stand against this. This breaks DRY, most (good) code is self-documenting.
> 
> [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Function_Argument_Comments)
> 
> > Do not state the obvious. In particular, don't literally describe what code does, unless the behavior is nonobvious to a reader who understands C++ well. Instead, provide higher level comments that describe why the code does what it does, or make the code self describing.
> 
> I'd rather see a function like `delete_items()` than a function like `delete_items() /// Deletes items`. The extra statement is just distracting.

yeah im kind of worried this is just going to make shit look ugly as fuck

this is like one of the first things you learn in coding to not do

**Comment by optimumtact** [comment]
@MrStonedOne since when have you cared about dev ease of use? youre still mandating we support ie8 :joy:

**Comment by optimumtact** [comment]
@Whoneedspacee don't worry your code is already ugly as fuck so there will be no difference

**Comment by optimumtact** [comment]
oh and just so we're clear, I do care about the dev experience.

But the experience I care about in this case is new devs, not that you have to take an extra 30 seconds to add a comment to a method.

**Comment by MrStonedOne** [comment]
@optimumtact Did I fucking say anything about the actual requirement?

No

I pointed out that its kinda shitty to add the requirement before completing and finalizing the documentation on that requirement.

In fact this should have been a pre-announced thing, with a finished document, that devs could look at, and ask questions on, so we can make sure it can be understood and refined it based on those questions.

This isn't 2012 anymore my dude. /tg/Station is not the small project it used to be. We can't be doing these unannounced things.

**Comment by optimumtact** [comment]
dmdoc took me 20 minutes max to pick up and figure out, if you're incapable of figuring out how to write a block comment at the top of a method then it won't matter how much documentation we add after the fact to help you out or not. You are still going to flunk grade school.

**Comment by optimumtact** [comment]
@Jared-Fogle maybe one day

**Comment by Whoneedspacee** [comment]
>dude we gotta help the new devs and document shit

>also haha fuck new devs cant figure shit out

why even add this dude

**Comment by Whoneedspacee** [comment]
>@Whoneedspacee don't worry your code is already ugly as fuck so there will be no difference
 
too predictable

**Comment by optimumtact** [comment]
\>new devs can't figure out 7 years of ss13 cruft due to a lack of docuemtation

\>new devs can't figure out how to block comment a method from a PR already containing multiple examples of how to document a method

You could insulate your house with all that straw

**Comment by Whoneedspacee** [comment]
that being said i’m not against this, obviously, just requiring it for every method is a bit unnecessary, would be great for some of the lower level procs. this just needs a bit more work put into it.

**Comment by Whoneedspacee** [comment]
my arguments not even close to a strawman so i’m not sure how to respond to that.

**Comment by nicbn** [comment]
> Also lets not pretend any of you actually gave a fuck about "code look" or "Googles DRY Coding requirements". Because if you did you would be documenting your methods in the first place, instead of looking like a bunch of hypocrites because all of a sudden you have to do extra work.

Nice argumentum ad hominem.
I do recognize that SOME methods (mostly helper methods and methods that are supposed to be overriden) should be documented, even if a one-liner just for the autodoc to work, I've got it now, but surely not all of them. And surely not all of the fields.

A better requirement would be something like "if you expect this method/field to get called somewhere else than this file documentation is requirement", and of course documentation should also be used when the method needs better explanation and all (but that's a little subjective to be a requirement I think).

**Comment by Whoneedspacee** [comment]
i think oranges problem with that is

>coders

>excuse to not document by “accident”

>more work for maintainers

honestly it isnt much effort to document but yeah i think it looks ugly as fuck

**Comment by ninjanomnom** [comment]
Autodoc on every proc definition makes sense but subtypes shouldn't be necessary. What we'd want there is for proc overrides to automatically inherit documentation of the parent. Additionaly a tool to do this manually would be useful for when you want to have all the same doc comments as the parent but want to add something.

```
///documentation required
/some/type/proc/dothing()

///<inheritdoc=/some/type/.proc/dothing>
///documentation optional
/some/type/other/dothing()
```

**Comment by SpaceManiac** [comment]
Marked stale for 10 days WIP with no updates

**Pull request closed without merging**
