### PR TITLE
Avoid creating string list of turf platings, rename some of the APIs, and improve focused test support - 160ms+ (more on prod) of init savings

### PR DESCRIPTION
**Pull request by Mothblocks**
Looking at some stuff that uses `Join` right now as targets, this one's pretty straight forward.

`/turf/open/floor/Initialize`, called 20,000 times without ruins, creates a string list of the broken and burnt states. This carries the fixed cost of `Join`, which is very expensive, as well as some (not crazy, but not negligible) proc overhead.

These vars were used for effectively nothing, and have been replaced with just using the list when necessary, which only adds an extra millisecond of cost to update_overlays.

This was also used to automatically set `broken` and `burnt` at runtime. However, this looks like it has gone completely unused. Adds a unit test which adds it as a static field to the only type that cared about it, which was abductor tiles, which is wrong anyway, but Whatever. I want to support people making a subtype of floor tiles that are pre-broken without it messing up stuff silently, so the test is there.

While I'm at it, renames `setup_broken_states` and `setup_burnt_states` to remove `setup_`, since they don't really do that anymore (and never did).

Also also, adds support for `PERFORM_ALL_TESTS` to work with multiple focuses. 

For reviewing, basically all of the changes are in floor.dm, aside from test stuff, which is unit_test.dm.

### CODE REVIEW

**Comment by Mothblocks** [comment]
@tgstation/commit-access

**Comment by Mothblocks** [comment]
let me see if theres any new ones in the meantime

**Comment by LemonInTheDark** [comment]
Whoop didn't read that last one

**Comment by Mothblocks** [comment]
@LemonInTheDark that was me updating the branch, it not erroring means its fine

**Pull request merged**
