### PR TITLE
Revert "increases toolbox size :D" for making an undocumented change to another sprite

### PR DESCRIPTION
**Pull request by MrsTonedOne**
it changed the hisgrace sprite for no raisin.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
hisgrace is a toolbox too though???????????????????

**Comment by ExcessiveUseOfCobblestone** [comment]
MSO what do you think the fourth picture is?

!img[https://camo.githubusercontent.com/a5eb85d91982e0214325342f300d665829ed8881/687474703a2f2f692e696d6775722e636f6d2f78614d465070532e706e67]

**Comment by dannno** [comment]
what did I do to you, you fuck

**Comment by Supermichael777** [comment]
its clearly the botany toolbox

**Comment by dannno** [comment]
am I missing something
Is His Grace not a toolbox
What am I missing here

**Comment by Kromgar** [comment]
100% salt not weed

**Comment by Supermichael777** [comment]
The sprite is better though

**Comment by MrStonedOne** [comment]
\>somebody says the pr changes "his grace"

\>mentions something about stupid looking red confetti

\>open dmi up

\>no state named "his grace"

\>see bible state with stupid looking red confetti called scrapbook

\>"hey, his grace sounds kind bibley, that must be what they are talking about"

\>"why did he edit the bible in a toolbox pr"

\>pr was merged

\>wtf

**Comment by dannno** [comment]
Is your fucking brain turned on?

**Comment by Shapsy** [comment]
what happened in this PR

**Comment by Durkel** [comment]
Remember kids, don't smoke and code.

**Comment by MrStonedOne** [comment]
\>one of the few times I'm sober.

\>remember kids, don't smoke and code.

You know what, fuck you i'm reopening this.

**Comment by dannno** [comment]
I DON'T DESERVE THIS

**Comment by Supermichael777** [comment]
why tho

**Comment by MrStonedOne** [comment]
\>I DON'T DESERVE THIS

\>Is your fucking brain turned on?

Its like they have no self awareness.

**Comment by dannno** [comment]
I say that all the time it was a joke I assumed we were on good terms, jesus

**Comment by calzilla1** [comment]
MERGE

**Comment by Kromgar** [comment]
He on cocaine

**Comment by Metallusions** [comment]
>it's just a prank bro

**Comment by RussellTalbott** [comment]
# dude weed lmao

**Comment by dannno** [comment]
unironically yes it was a prank lol holy fuck

**Comment by dannno** [comment]
TIL weed jokes are apparently off the table??
I apologize on Durkel, Russell, and my own behalf?

**Comment by Iamgoofball** [comment]
going to revert this revert

**Comment by optimumtact** [comment]
Nailed it

**Comment by dannno** [comment]
*bangs head on table so hard screams so loud*

**Comment by MrStonedOne** [comment]
alright, i've had enough fun with dannno.

**Comment by ShadowDeath6** [comment]
Good pr even if the motives were a bit distorted

**Comment by dannno** [comment]
all it would have done is made them smaller again LOL

**Comment by Yoshmaster** [comment]
looks like ya GOT GOT, danno

**Comment by dannno** [comment]
SHUT THE FUCK UP

**Pull request closed without merging**
