### PR TITLE
Adds new spookier lavaland ambience

### PR DESCRIPTION
**Pull request by Niknakflak**
Old sounds: 
https://file.house/mhSi.ogg

New sound:
https://file.house/yZy_.ogg

### CODE REVIEW

**Comment by GunHog** [comment]
Dark. Foreboding. Evil. Fits perfectly.

**Comment by MMMiracles** [comment]
You should probably leave the mine ambience in, it still gets used on places that still use the old asteroid.

**Comment by Niknakflak** [comment]
The asteroid and lavaland areas are different though

**Comment by MMMiracles** [comment]
You see, I don't bother looking past the first change so I just automatically assumed the sound itself was removed as well.

**Comment by WJohn** [comment]
This is much, much better.

**Comment by Niknakflak** [comment]
Ambilavalong.ogg
https://file.house/DVbb.ogg

???

**Comment by WJohn** [comment]
That's better 👍

**Comment by Niknakflak** [comment]
Longer version is now the version that's in.  The filename is the same

**Pull request merged**
