### PR TITLE
Remove QDEL_HINT_IWILLGC

### PR DESCRIPTION
**Pull request by Cyberboss**
Literally the same thing as QDEL_HINT_LETMELIVE and almost nothing used it

See https://github.com/tgstation/tgstation/search?utf8=%E2%9C%93&q=QDEL_HINT_IWILLGC

### CODE REVIEW

**Comment by Shadowlight213** [comment]
@MrStonedOne I assume this won't break things?

**Comment by JJRcop** [comment]
I'm not MSO but it will not. The PR description describes it perfectly. The only thing that used QDEL_HINT_IWILLGC was the timer subsystem, and QDEL_HINT_IWILLGC and QDEL_HINT_LETMELIVE have exactly the same function with no difference whatsoever.

**Comment by JJRcop** [comment]
Also @Cyberboss don't comment it out, just remove the code.

**Comment by MrStonedOne** [comment]
I added it so that programmers working with the function later would know the difference between an object that is guaranteed to GC, and an object that sticks around on qdel.

If you come up and see a Destroy() that returns LETMELIVE you would assume that the thing never gets deleted. If it says IWILLGC you know it's just telling qdel not to bother to check it actually qdeleted.

That being said, I CAN give each a different functionality now. For one, IWILLGC should get added to the queueforqueueing but not the queue, in order to space out the softdeletes.

Two, IWILLGC should be getting marked as qdeleted, but LETMELIVE should now.

I'll make a PR with those changes.

**Comment by Cyberboss** [comment]
Closed then

**Pull request closed without merging**
