### PR TITLE
Fixes poppyseed mutating into tomato seeds instead of geranium/lily

### LINKED ISSUE #9641: botany mutations
Poppies mutate into tomatoes.

### PR DESCRIPTION
**Pull request by phil235**
Fixes #9641

### CODE REVIEW

**Comment by Chocobro** [comment]
:+1:

**Comment by Incoming5643** [comment]
:tomato:

**Comment by Firecage** [comment]
Phiiiil...but you broke this in the first place :(

**Comment by phil235** [comment]
Yeah that was my bad, I guess that's what happens when you're not careful with copy/pasting code.

**Pull request merged**
