### PR TITLE
Rad Collectors are now blacklisted from tesla.

### LINKED ISSUE #37348: Radiation collectors are affected by tesla shocks
Server revision compiled on: 2018-04-15

The tesla can explode radiation collectors, which is a problem since rad collcetors are now mapped adjacent to the field.

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: FrozenGuy5
Rad Collectors are no longer affected by the tesla's shocks.
/:cl:

Fixes #37348

### CODE REVIEW

**Comment by DaxDupont** [comment]
fuck beat me with 30 seconds.

**Comment by praisenarsie** [comment]
get beaned

**Comment by Poojawa** [comment]
`hugbox`

**Comment by Repukan** [comment]
Just take them out of the containment area.

**Comment by Barhandar** [comment]
@Repukan Pubby alleges it's not possible due to RADIATION REWORK making them not work if they're outside containment area.

**Comment by Poojawa** [comment]
But

If you're using the singulo. They don't explode from Tesla shocks that don't exist.

If you don't use the Lord Singuloth, then you'd be moving the singularity trigger out already??

It's quite literally people being lazy for this PR. move the rad collectors, build more tesla researchers.

**Comment by Iamgoofball** [comment]
hey hey hey did someone forget GROUNDING RODS ARE A THING

**Comment by Iamgoofball** [comment]
20<Iamgoofball>30 Can someone close this? It's straight useless
20<Iamgoofball>30 1. tesla prioritizes tesla coils over everything else
20<Iamgoofball>30 2. if it cant find a coil, it'll prioritize grounding rods before everything else
20<Iamgoofball>30 unless SOME IDIOT broke that
20<Iamgoofball>30 i dont see a reason for this PR to exist

**Review by Cyberboss — APPROVED** [review]

**Comment by ninjanomnom** [comment]
Upon a cursory glance there doesn't appear to be an anchored check in that code @Iamgoofball

**Comment by ExcessiveUseOfCobblestone** [comment]
I think he meant the tesla coils.

**Comment by optimumtact** [comment]
not a bug

**Pull request closed without merging**
