### PR TITLE
Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request
--- 

The Space Tram is currently spaced. This is a known issue with not the map, but Trams in general. The Space Tram is a Space Tram to encourage a fix. Until then, the Space Tram is a maint tram that's an actual hazard but cannot directly kill anyone, including lizards. Enjoy the commodity as you zip from secmaint to medmaint. 
-------------------------------------------------------

I... really don't know if I should be proud of myself here. This whole process has been akin to a fever dream and it has only been little over a month since I first created the .dmm for this. What started as a simple yet humble reimagining of Birdboat has turned into an entirely new station, and blown past Metastation sized proportions. This has been my most expansive project yet, and somehow it's also been my quickest. So without further ado, I unveil Birdshot - Successor to Birdoat. 

-------------------------------------------------------

**Due to recent cost expenditures on Icemoon projects, and a growing need for orbital research stations, Nanotrasen has decided to pull Birdboat Station out of mothball after nearly 5 years of abandonment.**

Since then, the station has seen a variety of changes at the hands of the various vagabond lawless scum and villains that have decided to make the abandoned station their home. Do not fret though, a Nanotrasen Operation has secured the companies rightful property for corporate use once again, though you'll need to be the stewards of the remaining cleanup operation. 

------------------------------------------------------

Now, as you might have guessed by now, Birdshot is heavily based on Birdboat station. Many of the decisions here follow the original layout, and what had to be modified or moved still tries its best to replicate and imitate what bird being said. At least, that was the idea initially. This has very much grown into its own beast and as such, while the main inspiration has been Birdboat, there are a lot of new ideas thrown into the mix that really give this station its own unique and deserving identity. Maybe it's not perfect, but I've been inspired by @MMMiracles own performance with Tramstation to keep working on Birdshot and updating it with better and improved faculties. For now, though the station is in a playable state, and that means I'm making a PR. If I had to borrow the words of the good MMM, I would call this **Birdshot: Season 0**

BirdSHOTFULL2-26-S

See the image in more detail here: https://imgur.com/iT5Vi8k

## Why It's Good For The Game

We've been with the same 5 maps for a while now. @san7890 jokingly said that I could sacrifice Metastation back in November if I remade Birdboat but modern. Obviously that wasn't going to happen, yet I was spurred on by the idea. When I began this in earnest early this January, @EOBGames  said that a Birdboat sized map would replace Kilostation in the rotation. Interestingly we're not a small map anymore so I honestly have no clue where this goes. Maybe that ephemeral 6th map slot that's been rumored. 

What I can say, is that Birdshot is wholly unlike anything else that is currently in rotation. It's got an engineering section that feels way too small for a station of that size, almost evocative of Cere. Cargo is blessed with a Boutique that makes use of @Fikou's new mannequin dolls. Command is outfitted with a Corporate Guest Suite, and Officials sent from Nanotrasen can embark from their ferry into the safety of their own Corporate Dock. Elements of Cerestation are present, yet not in a way that makes traversal annoying. Furthermore we have **2 Trams** (that I have yet to get functional but we'll get there) on Birdshot, that's right 2. One Security Prison Tram, and then other, a Space Tram. Both Novel in their own ways. Departments on Birdshot twist and turn, and there's an abundance of Maintenance Tunnels to cut through everything, for the brave and the bold that is. And there's plenty left to discover, but I'd rather let Birdshot speak for itself. I'm proud of this one. 

If you want something new, this is something that is almost the complete opposite of Chilled Station - Explicitly Designed to send you back to the metal death trap that is:    **Space Station 13.** 

## Changelog
:cl:
add: Birdshot station has been pulled out of Mothball.
add: New station areas and places to visit. A Mix of Kilo and Delta maints with winding shortcutting paths.
add: A host of new shuttles to support this bold endeavor to reclaim something that really shouldn't be reclaimed.
add: Two Trams, Two Trams.
add: For the last time Bob, the gaping hole is a **feature.** Use the breach shutters or have the virologist make starlight. 
add: A smiling salute to stations past...
add: Secrets.

/:cl:

### CODE REVIEW

**Comment by DAKKA-WAAAGH** [comment]
Finally, the Meta killer.

**Comment by Detective-Google** [comment]
jesus wept 

jokes aside, I love how this keeps the soul of birdboat without being a direct recreation. I eagerly await the HoPline suicides because people can't handle a map that isn't strictly optimal. 

I'm curious about the seeming lack of details in the halls. Is this a design choice? (It may also just be the case that I can't really see them with the resolution of that image- mapdiffbot hasn't given a full res one yet.) interested to see how that plays out; I imagine it'd cut down on the sensory overload of this layout, but might also contribute to players getting lost. maybe that's the point. either way, always happy to see new maps :) I still have fond memories of playing birdboatstation when I was new to SS13.

**Comment by Mothblocks** [comment]
its failing a lot of tests

**Comment by Mothblocks** [comment]
Will look into maplint failure. You failed a lint but there's also a bug in maplint itself

**Comment by Mothblocks** [comment]
```
- Error parsing _maps/map_files/Birdshot/birdshot.dmm (line 37648): (in pop rcr) (at (97, 190, 1)) Typepath /obj/machinery/door/window/left/directional/east has a banned variable (set to access shutter): name. Must not match .*\s(?!of|and|to)[a-z].*
  Please upper-case your door names.
- Error parsing _maps/map_files/Birdshot/birdshot.dmm (line 5220): (in pop cBc) (at (97, 189, 1)) Typepath /obj/machinery/door/window/right/directional/east has a banned variable (set to access shutter): name. Must not match .*\s(?!of|and|to)[a-z].*
  Please upper-case your door names.
- Error parsing _maps/map_files/Birdshot/birdshot.dmm (line 44271): (in pop tWB) (at (97, 188, 1)) Typepath /obj/machinery/door/window/right/directional/east has a banned variable (set to access shutter): name. Must not match .*\s(?!of|and|to)[a-z].*
  Please upper-case your door names.
```

**Comment by Zytolg** [comment]
Thanks Mothblocks

**Comment by private-tristan** [comment]
the 2x3 SM is the most cursed part of this map

**Comment by bluetshirtguy** [comment]
Botany and the kitchen being so far away, I weep for all the time wasted spent walking back and forth.

**Comment by Mothblocks** [comment]
If you merge #73528 into your local branch (or nag some maintainers that aren't me) you'll be able to see the maplint problems

**Review by Maurukas — COMMENTED** [review]
First pass:

This station lives up to the goal of being a nonsensical metal deathtrap. It's impressive, and it's extremely anti-Metastation in terms of design. Sometimes it feels like it's being deliberately mildly frustrating. It's different. 

The SM is different. It's not indefinitely stable, but set up correctly it will run stably for several hours. It is extremely difficult to manage in a delamination, for several reasons. You might want to consider a 'purge' pump on the exhaust tank that allows it to be dumped into the waste loop - The atmos filters will crap out once pressure in the waste tank hits 4500 kpa. Under optimal circumstances it will hit this at about 2.5 hours.

If there are excursions outside of optimal SM conditions then things get less pretty. If you start a fire in the waste tank then you are very nearly guaranteed a delam.

<details>
<summary>Amp Check is wired into the wrong grid</summary>

It needs to be wired into the post SMES grid
image
</details>

<details>
<summary>Layering issue in the library </summary>

image
</details>

<details>
<summary>Unwired APC in theater greenroom</summary>

image
</details>
<details>
<summary>Roundstart ATs in telecomms, check turf subtypes</summary>

image
</details>
<details>
<summary> Disconnected atmos devices in cytology, looks incomplete </summary>

image
</details>

<details>
<summary>Unwired APC in cargo mining office</summary>

image
</details>

<details>
<summary> Cryo needs a CO2 filter connected to the waste loop </summary>

image
</details>

<details>
<summary> Virology airlock is missing controls</summary>

image
</details>

<details>
<summary> Vacant Commissary shutter controls are accessible from the hall outside </summary>

image
</details> 

<details>
<summary> Disconnected vent + no scrubber in aft + starboard bow solars </summary>

image

image
</details>

<details>
<summary> Disconnected scrubber in QM's quarters under the copy machine </summary>

Why are the fax and copier in his bedroom anyway?
image
</details>
<details>
<summary>Ordnance airlock vent is not hooked up to anything </summary>

image
</details>
<details>
<summary> Unwired APC in funerary driver</summary>

image
</details>

<details>
<summary>Unwired terminal in garden.
</summary>

image

</details>

<details>
<summary>Unwired terminal in corporate guestroom
</summary>

image
</details>

<details>
<summary> There is a missing cable here in atmos
</summary>
Is this intentional? It leaves the far east side of the station hanging off a very long, lengthy cable run through maint.

image

</details>

Odds and ends:
* There are no external controls for the AI chamber turrets
* Plumbing is missing all materials, including the plumbing constructors. Is the intent to make players make plastic and fabricate them?

**Comment by Zytolg** [comment]
All of these save an SM purge should be addressed. I'll get to doing something about it, and I think I may have a solution.

**Review by Maurukas — COMMENTED** [review]
Pass 2, another few hours of poking around. This was reviewed from [29733ee](https://github.com/tgstation/tgstation/pull/73502/commits/29733ee58f23cca90e7a134dd4d69e259ac956bd) so I may not have all the latest changes

Love the cubicle farm.

* Cryo still does not have a CO2 filter - it looks like a straight pipe has been placed over it that leads to waste, but no filter is present hooking the two systems together.
* Medbay front shutters are upside down
* Medbay shutters do not cover the north east entrance, but do cover the window next to it?
* The random statue spawner can give plasma statues. Are you aware of this?
* Gravity Generate door is misnamed as Gateway Atrium
* The gravity generator's control panel is inaccessible - you have to remove a reinforced wall to reach it to switch it on or off
* Power cable under a wall at 150,162
* HOP office disposals destination is not working (gets shredded)
* CE's bedroom has no access set
* Multiple sorting pipes for RD office, the one at 191,116 is disconnected and throws the RD's mail into the hall
* Nitrous Oxide tank in atmos has an NO2(Nitrium) filter 
* Plasma tank in atmos is straight piped to yellow at roundstart with no intermediate pump
* Janitorial tagged mail comes out the trash chute into the shredder instead of out the disposal chute

Suggestions:
* A disposal chute somewhere in the theater/dining area - there's one reachable by the cook, but none by guests
* Consider adding the new coffee makers
* Cargo front office could use a copy machine - currently the only one in the department is in the QM's office.

**Comment by MrrFiish** [comment]
AI SAT has a button that does nothing called AI Core Shutters Control, think its supposed to connect to the N2O shutters.

**Comment by ophaq** [comment]
Congratulations, you nearly gave me a headache looking at this. Cool station though, it does feel like a death trap.

**Comment by nickup9** [comment]
Seems that sec comms don't work round start, unsure if this is intended or it's a bug.

**Comment by wesoda25** [comment]
No comment on anything else but the redundant (functionality wise) space hallway below kitchen/bar seems like it has a lot of potential for goofyness. Look forward to trying this out

**Comment by Gameandglitch3** [comment]
the tram is spaced when it goes through space

**Comment by Baskett55** [comment]
Some of the security record consoles are unusable computers in the brig
dormitories door is called dormatories
And i dont know if you intended it or not but the russians in the maint bar drop a revolver and mosins

**Comment by Derpguy3** [comment]
Some feedback with the station from my first few rounds with it.

1. The trams (Assuming the perma-brig one as well) don't seem to close their doors when moving between the spots.
2. The AI sat seems to be lacking access requirements, letting anyone in assuming the doors are not bolted.
3. Morgue seems to lack the body spawners that other stations have.
4. A camera is missing from the exterior of the AI upload/sci hallway.
5. The light fixtures in the terrariums in medical's treatment bay cannot be accessed easily. (Without smashing the glass at least.)
6. Cubie is aggressive. (Are they meant to be aggressive?)
7. Brig entrance doors don't cycle with the other doors. This makes it pretty easy to waltz in when somebody with access goes through.

**Comment by Zytolg** [comment]
Thanks for the feedback I'll look into all of this right away!

**Comment by Zytolg** [comment]
Linters should only be failing on Slimes because of Kor, and Nuke Cinematic because apparently the game doesn't like the Vault Location.

**Comment by Darknesshaz** [comment]
I have some complaints and I was told to paste it here. 1: medbay starts with atmos alarms going off instantly. 2: it requires medbay access to leave that funky area, which I give, is actually cool. 3: disposals is in janitor closet, which is valid, but isnt set to let people out so you're kinda just stuck: 4. what the fuck is up with the tiles, like what the fuck? why cant it just be fine at roundstart?

**Comment by Astrogem2** [comment]
one of the shutters in captains office doesn't close when the button shutter is pressed unreal

**Comment by MrrFiish** [comment]
Oh yeah also when I was AI I couldn't find any AI displays, the ones that let you set their face and stuff, only status displays.

**Comment by Vect0r2** [comment]
upload got no cams outside of it, but I really do like the map!

**Comment by magmabee** [comment]
Camera coverage in the station is very, very poor. Also the cremator by brig/chapel does not work.

**Comment by YakumoChen** [comment]
birdboat is my all time favourite map for being an absolute trashfire, looking forward to its return.

**Comment by Baskett55** [comment]
The pack of cigarettes in the cargo front desk is of the xenobiology variety, which have 20u of regenerative jelly per cig. wasnt sure if it was intended.

**Comment by Ekaterina-von-Russland** [comment]
Cool concept. Medbay really needs the "all access from inside" feature, and the station needs more cameras, as others have already pointed out.

**Comment by CourageTheCat** [comment]
YIPPEEEE!!!!!

**Comment by ophaq** [comment]
The biggest thing that bothers me so far on this station are the broken floor tiles that exist over current ones which need to be smashed with a toolbox or something to remove. I wish you could just remove them with a crowbar, but you can't.

**Comment by rageguy505** [comment]
Toxins is missing the mass driver controls

**Comment by rageguy505** [comment]
Tachyon doppler array is also facing south, so it cant scan explosions
also i dont think theres any carp spawns

**Review by Maurukas — COMMENTED** [review]
Third pass through I think now.

I like the changes to the general damage and dirtiness to the station. It feels a little more balanced. It also feels like you're going to get stabbed when you wander into the more run down parts of the station.

<details>
<summary>Duplicate/mispositioned newscaster in maint </summary>

image
</details>

<details>
<summary>This filter in the SM loop is nonfunctional</summary>

image
</details>

<details>
<summary>This freezer is not connected to anything</summary>

image
</details>

A few other things for consideration:

* There are no gas pressure monitors on any parts of the SM loop except the chamber intake/outakes. This will make it very difficult to see what is happening in the engine.
* All the emitters are unanchored. Is this intended? It's fine if it is.
* The northmost emitter is hotwired into the SM grid. It cannot fire unless the SM is active and generating power.
* There are 3 x 30 stacks of plasma near the SM - one in maint, one by the SMES, and one in the previous SMES room. This is kind of a lot. Also two of them are varedits instead of the `plasma/thirty` subtype.

**Comment by Addust** [comment]
spacetram becomes depressurised in transit

**Comment by Addust** [comment]
no whiteship dock set

**Comment by Jacquerel** [comment]
> spacetram becomes depressurised in transit

This is unfortunately just how trams work, I'd suggest adding a passenger structure which works like an air-filled closet or some such now that the freeze is over.

**Comment by BangingDonk** [comment]
Prisoner main here, got to say that I really like the bones of the permabrig you've made here. It's EXTREMELY secure, which is both a positive and a negative, and also has an appealing look to it.

That being said, it could use a little bit of love in a couple of specific ways:

- An AI holopad would be nice to have somewhere in a centralized location, maybe the kitchen.
- There seems to be a lack of prison intercoms or station intercoms in the brig as well, which leads to a lot of isolation
- The kitchen lacks utensils in the form of cutlery, glasses, serving trays, or bowls, which severely limits food and drink options.
- The sink in the kitchen area is attached to a glass window, which looks kinda weird
- I can't believe I'm saying this, but it might be better to replace the fryer with a microwave. There still are a couple of foods here and there that require it, and nothing requires the fryer. The fryer could be potentially very funny, and there's enough room for both honestly.
- There's no nutrislop bins, which almost feel like a perma tradition at this point

It was a short round, but that's just a couple of things I noticed off the cuff. I look forward to seeing how the map develops, though!

**Comment by Derpguy3** [comment]
Some additional feedback after playing a few more rounds.
- The confession booth in the chapel lacks the confessional intercom for both sides of the booth.
- A large number security cameras don't seem to be properly showing up on camera monitor consoles, there's plenty of them in hallways and other departments but they don't seem to show up on the list.
- The disposals/mail network needs to be checked. I'm not quite sure what it is specifically, but things going into the disposals is ending up coming out of public bins or departments delivery chutes. (The trash from science came out of the public bin in the image.)
Screenshot 2023-03-03 194935
- The disposals bin in robotics augmentation theater seems to be missing a trunk(?).

**Comment by dessysalta** [comment]
Some feedback:

- Nukies (at least, the battleship variant) can't travel to the station by ordinary means. You're unable to set the ships by the station for whatever reason. Dunno what's causing it, but worth mentioning. 
- This is a nitpick, but _wow,_ this station is filthy. Like...how did this even pass Nanotrasen inspection?

**Comment by Loafin34** [comment]
love it, just concerned about the maintenance loot. an avid greytider does wonders in a station, but a bottle of thermite roundstart? a double barreled shotgun? I'm all for diversity in the loot, but this seems like a bit much.

**Comment by LSommers** [comment]
There's no way to open the armory shutters from outside, you have to go through the warden's office to the interior button.
That and the disposals routing issues other people mentioned are all I've noticed so far.

_So far._

**Comment by dessysalta** [comment]
> love it, just concerned about the maintenance loot. an avid greytider does wonders in a station, but a bottle of thermite roundstart? a double barreled shotgun? I'm all for diversity in the loot, but this seems like a bit much.



Not just a double-barreled shotgun, but a Nagant revolver and Mosin Nagant to go along with it if you kill the Russians to the right. You can be a death machine in as little as 5 minutes.

**Comment by iamcooldan** [comment]
as much as I love the look of the public garden, the lack of a biogen, seed vendor, nutrimax, and seed extractor renders its existence pretty much null for anyone trying to get a few plants without botany

**Comment by Derpguy3** [comment]
More feedback, but for medbay
- Medbay gets blood coated really quickly, and they lack the supplies to clean it up.
- There are no spare boxes of latex gloves or sterile masks around the medbay.
- There are no lockers for the medical doctors.

**Comment by Addust** [comment]
> This map seems to make my ping spike, for some reason. I also wanted to report that the maintenance tram's door does not close, making it so you receive pressure and oxygen damage for a second as you pass through. Not sure if intended, but putting it out there.

atmos is turf based so on that matter you're fucked, door open or closed

**Comment by Draggeru** [comment]
Xenobiology does not start with plasma. Also, why is there a BZ canister round start? I thought all of them were removed for a reason.

**Comment by theSkymonster** [comment]
The airlocks of the AI satellite seem to be tagged with either Maintenance or no restrictions, because an Assistant could open all of them.

**Comment by TheSmallBlue** [comment]
Had a round with changelings yesterday and we found out the hard way that the incinerator just doesn't turn on. You press the button; nothing happens

**Comment by Zytolg** [comment]
> Emergency Hull Breach Supply storage in tool storage has "Collectible Welding Helmets" and not real welding helmets which are utterly useless, also what's the access on that door? Feels like no one can get in

I'll take a look when I get home in 4 hours-ish

> Also does the telecomms setup still have no Automated Announcement system and thus not announce late joins

Ditto

> I know the default Supermatter engine setup isn't supposed to be perfect but the default setup currently will delaminate immediately if turned on because the filters are backwards (by default the waste goes back into the loop, and the cooling gas is vented). This seems like a yuge noob trap.

Yes. I'll include some wiki edits when this fullmerges. 

> I think the cremator in the crematorium isn't properly linked to the cremator button. I tried to cremate someone one round and it didn't work with me, despite having ample power.

I'll take a look at it. 

I'm gonna get keyholders to update birdstation to the commit below this comment so that everything is up to day. I noticed that servers haven't been able to experience a functional bot network as of yet and I added that in with a slew of other changes starting from last week. Lots of stuff lots of stuff but the polish efforts are paying off.

**Comment by Richie9999** [comment]
Looks like permabrig is on a seperate grid from the rest of the station? without someone coming by to set up Perma's solars or wiring it to the rest of the station's grid it loses power.

**Comment by Derpguy3** [comment]
Science related feedback
- The cubical room is a nice touch to science.
- The augmentation room is missing a cautery, body bags and MMIs for borging.
- The robotics lab is missing a shutters button.
- The conveyors in robotics seem to be missing a control lever.

**Comment by saprasam** [comment]
worlds only lawyer player here
1. lawyers cannot access any of the brig hallways because of how it's designed
2. lawyers get no sunglasses, map RUINED.

**Comment by BangingDonk** [comment]
Prisoner's do not have access to leave the prisoner-access side of the gulag when you successfully turn in all your mining points.

**Comment by Zytolg** [comment]
Dude who broke the trams

**Comment by Addust** [comment]
whiteship critique:
overspace titanium wall bad
TWO CARGO AND ENGINE AREAS? no, stinky, make seperate areas
otherwise really cool

**Review by spockye — COMMENTED** [review]
image

missing pipe (starboard primary hall)

image

missing pipe (sec transfer)

image

missing cable (sec locker room)

image

missing cable (construction area)

image

disposals wackery ( central medbay maintenance)

image

missing disposals ( chemistry ) 

image

missing disposals pipe (recreation hall)

image

nearstation on space

image

War crime

image

missing solar zone

image

nearstation on spess

birds are pretty cool

**Comment by TheVekter** [comment]
Zytolg spoders can't spawn on your station please fix

> ADMIN LOG: No valid spawn locations found in GLOB.generic_maintenance_landmarks, aborting spider spawning...

**Comment by YehnBeep** [comment]
image


The navigation aid app thingie doesn't seem to work anywhere on this station. Just shows "nearest way up" seemingly no matter where you are on the station.

**Comment by Singul0** [comment]
most of the directional windows are gone??

**Comment by DrDiasyl** [comment]
It seems like there is no captain's medal box on the station, it's just not placed.

Captain's medal box unlike heads medal box doesn't automatically spawn in the closet, it must be manually placed on the map in his office.

**Comment by YehnBeep** [comment]
This map does not have the room for even rudimentary chem setup and gameplay.


image

image

image



Please consider improvements.

**Comment by BlueMemesauce** [comment]
Issue #74928
All members of security are unable to access the doors labeled "Brig Cells" that lead to the room in security with the cells. 
The Captain is able to access them, so the doors must have been accidently set to some access outside the security department.

**Comment by newfren** [comment]
xenobio needs syringes (and ideally beakers) to function

**Comment by EOBGames** [comment]
Welcome to the rotation, birdshot

**Pull request merged**
