### PR TITLE
Sorts the majority of the rest of the unsorted chat

### LINKED ISSUE #55431: Admin Observer OOC doesn't filter into the right chat category
## Reproduction:
in main tab, with OOC filtered out:
image
in OOC tab, with only OOC filtered:
image

### LINKED ISSUE #58471: Setting OOC color for all players screws with tabs
Reporting client version: 513.1536

## Round ID: 
[160376](https://scrubby.melonmesa.com/round/160376)

## Testmerges:
 N/A

## Reproduction:
Be admin, set the OOC color of all players, suddenly the tab dedicated solely to OOC stops working and it becomes linked to the IC tab. What?
image

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

- added alertsyndie to the warnings filter
- adamantine reverberations > radio (added resonate class to radio filter)
- all (you hear ....) > info (added hear class to info filter)
- adds warningplain to warning filter, associated various messages are filtered into warningplain
- add ghostalert to dchat filter
- add holoparasite to info filter
- medibot places tools back inside > info (code\modules\mob\living\simple_animal\bot\medbot.dm)
- points at the > local (code\modules\mob\living\living.dm)
- emotes not on screen as ghost > local (code\datums\emotes.dm)
- examining > info (code\modules\mob\mob.dm)
- memories > info (code\datums\mind.dm)
- show roundend report again > info (code\__HELPERS\roundend.dm)
- round has ended > info (code\__HELPERS\roundend.dm)
- many OOC things > OOC (added oocplain class, code\modules\client\verbs\ooc.dm)
- ignore players > info (code\modules\client\verbs\ooc.dm)
- server revision > info (code\datums\helper_datums\getrev.dm)
- cultmaster greet > info (code\modules\antagonist\cult\cult.dm)
- heretic greet > warning (code\modules\antagonist\eldritch_cult\eldritch_cult.dm)
- ERT greet (and all the others in the file, what the fuck) > warning (code\modules\antagonist\ert\ert.dm)
- fugitive greet (WHY ARE YOU USING SO MANY TO_CHAT()'S) > warning (code\modules\antagonist\fugitive\fugitive.dm)
- nukeop greeting > warning (code\modules\antagonist\nukeop\nukeop.dm)
- mafia greeting > warning (code\modules\mafia\roles.dm)
- you are the (job) > info (code\controllers\subsystem\job.dm)
- mob_spawn/human/exile/special > info (code\game\objects\structures\ghost_role_spawners.dm)
- You feel an off sensation in your voicebox. > info (code\datums\mutations\speech.dm)
- tip of the round > ooc (code\controllers\subsystem\ticker.dm)
- welcome to x station > info (code\controllers\subsystem\ticker.dm)
- gamemode text > info (code\game\gamemodes\game_mode.dm)
- single flick of x, x lights the x with x > info (code\game\objects\items\cigs_lighters.dm)
- applies the [medical] on x > info (code\game\objects\items\stacks\medical.dm)
- sending resources > info (code\modules\asset_cache\transports\asset_transport.dm)
- cyborg camera text > info (code\modules\photography\camera\silicon_camera.dm)
- fire extinguisher the safety is x > info (code\game\objects\items\extinguisher.dm)
- cyborg hugging module power increased > info (code\game\objects\items\robot\robot_items.dm)
- show/hide OOC > info (code\modules\client\preferences_toggles.dm)
- show/hide income updates > info (code\modules\client\preferences_toggles.dm)
- show/hide login/logout messages > info (code\modules\client\preferences_toggles.dm)
- toggle intent selection style (why is this a thing still lmao) > info (code\modules\client\preferences_toggles.dm)
- show/hide ghostsight > info (code\modules\client\preferences_toggles.dm)
- show/hide ghostlaws > info (code\modules\client\preferences_toggles.dm)
- hear/silence MIDIs > info (code\modules\client\preferences_toggles.dm)
- hear/silence end of round sounds > info (code\modules\client\preferences_toggles.dm)
- hear/silence ambience > info (code\modules\client\preferences_toggles.dm)
- hear/silence announcements > info (code\modules\client\preferences_toggles.dm)
- hear/silence combat mode > info (code\modules\client\preferences_toggles.dm)
- hear/silence lobby music > info (code\modules\client\preferences_toggles.dm)
- hear/silence instruments > info (code\modules\client\preferences_toggles.dm)
- hear/silence ship ambience > info (code\modules\client\preferences_toggles.dm)
- toggle midround antagonist > info (code\modules\client\preferences_toggles.dm)
- show/hide ghostears > info (code\modules\client\preferences_toggles.dm)
- show/hide ghostradio > info (code\modules\client\preferences_toggles.dm)
- show/hide ghostPDA > info (code\modules\client\preferences_toggles.dm)
- show/hide ghostwhispers > info (code\modules\client\preferences_toggles.dm)
- toggle deathrattle > info (code\modules\client\preferences_toggles.dm)
- toggle arrivalrattle > info (code\modules\client\preferences_toggles.dm)
- toggle GhostHUD > info (code\modules\client\preferences_toggles.dm)
- hear/silence adminhelps > info (code\modules\client\preferences_toggles.dm)
- do/don't announce login > info (code\modules\client\preferences_toggles.dm)
- toggle split admin tabs > info (code\modules\client\preferences_toggles.dm)
- show/hide deadchat > info (code\modules\client\preferences_toggles.dm)
- show/hide prayers > info (code\modules\client\preferences_toggles.dm)
- reset asay color fail > info (code\modules\client\preferences_toggles.dm)
- cryopod unfiltered messages > info (code\game\machinery\cryopod.dm)
- mob spawner messages > info (code\modules\awaymissions\corpse.dm)
- holoparasite communication > local (code\modules\mob\living\simple_animal\guardian\guardian.dm)
- the round will start in x > info (code\modules\admin\admin.dm)
- keybinding conflict > warning (code\modules\client\preferences_savefile.dm)
- advertising other servers > system (code\modules\client\verbs\ooc.dm) (fuck you, you can't escape the message, bitch)

If you want me to expand my changelog to include all of this, fuck you, but also okay I'll do it.

Fixes #55431, fixes #58471.

## Why It's Good For The Game

UNSORTED CHAT MESSAGES ARE BAD.

## Changelog
:cl:
fix: many of the toggle preferences in preferences_toggles.dm going into the unsorted chat log
fix: many of the role greetings from sending to the wrong chat filters/ to unsorted
fix: miscellaneous other strings getting sent to the unsorted chat filter
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Hero

**Comment by maxymax13** [comment]
tip of the round should go in ooc

**Comment by MrMelbert** [comment]
Probably fixes #55431, maybe fixes #58471 ?

**Review by stylemistake — APPROVED** [review]

**Comment by Seris02** [comment]
yes it fixes both of those, and yes I'll put tip of the round into ooc

**Pull request merged**
