### PR TITLE
Fix slot machine server freeze

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl:
fix: You can no longer crash the server with the slot machine by getting large payouts
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
this is a bad fix, just dispense a holochip if the payout amount is large

**Comment by Cyberboss** [comment]
Someone else can do it, I'm low on bandwidth

**Comment by optimumtact** [comment]
Actually the code is just bugged, coin value is set via

```
	for(cointype in typesof(/obj/item/coin))
		var/obj/item/coin/C = cointype
		coinvalues["[cointype]"] = initial(C.value)
```
but the value of a coin is not set at compile time, it's set by
```
/obj/item/coin/set_custom_materials(var/list/materials, multiplier = 1)
	. = ..()
	value = 0
	for(var/i in custom_materials)
		var/datum/material/M = i
		value += M.value_per_unit * custom_materials[M]
```

**Comment by Cyberboss** [comment]
#51584

**Pull request closed without merging**
