### PR TITLE
[NOT READY] Updates the Boxstation Bridge and Firelocks

### PR DESCRIPTION
**Pull request by Hanador**
First PR, had some trouble with the mapmerger so look over this with more scrutiny than usual and let me know if I fucked up somewhere.

Changes the Boxstation Bridge to have darker tiles similar to the standards of other stations (meta, delta, etc.) also slightly expands the entranceway allowing for more decals.

Secondly the double layer of firelocks a holdover from the ancient era when directional firelocks were used in the main hallways of box have been removed.

Secant Lab 33 2020-03-14 105152
Secant Lab 33 2020-03-14 105201
Secant Lab 33 2020-03-14 105210

Central Hallway APC shifted slightly.
Secant Lab 33 2020-03-14 105226

Double Firelocks changed. Only one layer of firelocks now.
Secant Lab 33 2020-03-14 105229
Secant Lab 33 2020-03-14 105239
Secant Lab 33 2020-03-14 105256
Secant Lab 33 2020-03-14 105301
Secant Lab 33 2020-03-14 105326

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Looks like your mapmerge worked. Nice job!

**Comment by GuillaumePrata** [comment]
No more dancing in and out under firelocks opening and closing with the crowbar so you dont get smashed, god this is good.

**Comment by Twaticus** [comment]
Looks good! A nice start to updating box :+1:

**Comment by Rohesie** [comment]
Bad news, merge conflict.

**Comment by Hanador** [comment]
Alright working on the merge conflicts might take me a couple days.

**Comment by Hanador** [comment]
Having extreme trouble. I'm just going to split this into two smaller PR's one removing firelocks and one updating the bridge as that seems much easier with my current skillset.

**Pull request closed without merging**
