### PR TITLE
Revert "New Coffin Sprite"

### PR DESCRIPTION
**Pull request by praisenarsie**
Reverts tgstation/tgstation#34995

i was angry at sexy solars being merged because >get rid of the goon folder but these coffins suck arse because they aren't even the right way around, plus it's not that really of a good sprite imo (yes ik wjohn is the art director)

Closes #35108

### CODE REVIEW

**Comment by nicbn** [comment]
* The sprite is oriented on the wrong axis
* It is from closed source
* It looks almost identical to what we have

**Comment by Cyberboss** [comment]
Other PR is better

**Comment by Cyberboss** [comment]
I retract my statement

**Comment by Spaceinaba** [comment]
how can you be a maintainer if you cant maintain your sanity

**Comment by nicbn** [comment]
@Cyberboss you know that we had a previous coffin sprite that was 3:4, horizontal and didn't look shit right?

**Comment by Bawhoppen** [comment]
We have a no knee-jerk reverts rule...

**Comment by WJohn** [comment]
I only said okay to the solar sprites and co because kor gave the okay. I like the sprites, but I'm not sure about what's going on with the license and whether we're allowed to use them.

**Comment by Cyberboss** [comment]
Newer PR is better

**Pull request closed without merging**
