### PR TITLE
Corrects the bug introduced in #395ce00bb161c0cff528db50fba4bd378da3e1cd.

### PR DESCRIPTION
**Pull request by kyrahabattoir**
Easy mistake really.

### CODE REVIEW

**Comment by Hatterhat** [comment]
ebic

**Comment by ACCount12** [comment]
Bug of the year, fix of the year. Give this guy [Priorty: CRITICAL], he deserves it.

**Comment by lzimann** [comment]
corrects the bug of pr being open

**Comment by kyrahabattoir** [comment]
@lzimann Good boy @optimumtact will give you a gold star :)

**Pull request closed without merging**
