### PR TITLE
Fixes wizards being unable to talk smack

### LINKED ISSUE #41128: wizard ship intercoms are useless
What it says, he cant hear whats said on station with them and he cant speak to station using them, why are they even there?

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: optional name here
fix: Added a telecomms mainframe to the wizard shuttle so that wizards can use their intercoms.
/:cl:

fixes: #41128

I added an all-in-one tcomms machine so that the wiz shuttle intercoms work properly.

### CODE REVIEW

**Comment by ShizCalev** [comment]
Wouldn't this mess with the one on the Syndie ship?
https://github.com/tgstation/tgstation/blob/90bda1452ba77412295cd43e341062a03bbb36af/code/game/machinery/telecomms/machines/allinone.dm#L13

**Comment by 81Denton** [comment]
If I read this right, it shouldn't since the nuke ops one is only listening to `FREQ_SYNDICATE`. I'll test it in a little bit though.

**Comment by 81Denton** [comment]
Yeah, it messes with the Syndicate one. I'll close this and figure out a fix for the bug some other time.

**Comment by adamkad1** [comment]
shame

**Comment by PKPenguin321** [comment]
Could just slap down a station bounced intercom next to the camera console like in the olden days

**Pull request closed without merging**
