### PR TITLE
It is now possible to survive the Mansus 

### LINKED ISSUE #79113: Mansus gate dodge minigame is impossible to survive
Reporting client version: 514.1589

## Round ID:
[217084](https://scrubby.melonmesa.com/round/217084)

## Reproduction:
It seems that when people are sacrificed they're sent to one of the gates. Only to stay in crit and die to the hands before they can even react

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Fixes #79113

There were a handful of bugs with the Mansus realm, this PR fixes them.

Firstly an most importantly, a refactor to damage handling touched the "unholy determination" effect incorrectly (and I'm not even sure why?), causing it to damage you instead of healing you most of the time. This damage was not avoidable, so most people would be crit shortly after entering the area and stay there.

Secondly, some of the heretic realms were unlit. A change to when lazyloaded template atmosphere initialises means that the bonfires were trying to light themselves with no air. Now they do this in late_initialize instead, giving time for air to arrive.

Thirdly, the spooky hands were runtiming when passing through transit tiles outside of the bounds of the heretic map. They shouldn't be effected by shuttle drag anyway, so now they aren't.

Fourthly, I removed a row of empty space at the edge of the heretic map, just because it annoyed me slightly.

Finally, while I was touching the heretic buff I made it heal you 1/4 as much as it originally did. This is a balance change rather than a fix, I'll atomise it out if it is controversial but I don't really expect it to be.
In the future I would like to come back to these and make each realm more specific to the path, because I think we could make these both more exciting and more characterful.

## Why It's Good For The Game

Once it is working properly, the hand dodging minigame is actually extremely forgiving, even if you don't move very much and get frequently hit. This means some of those hits might actually add some tension.

## Changelog

:cl:
fix: You should be revived properly when entering the mansus realm following a heretic sacrifice
fix: The buff which is supposed to heal you in the mansus realm will now do that instead of unavoidably damaging you
balance: The mansus realm's healing buff heals for 25% as much as it did before it was broken
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
My first time being sacrificed, i thought that was just some sort of drawn out execution, until i read the flavour text a MINUTE after and realized i could dodge the hands, so yeah this is very fair

**Comment by Bibarra** [comment]
If you're making the minigame a bit harder, I don't mind, but can you remove the bonfires out of the minigame spaces that have them? It's a bit silly that you have something like a 2/5 chance to just accidentally set yourself on fire and burn to death depending on the type of heretic you get sacrificed by.

**Comment by MrMelbert** [comment]
>  It's a bit silly that you have something like a 2/5 chance to just accidentally set yourself on fire and burn to death depending on the type of heretic you get sacrificed by.

just.. don't step on them?

**Comment by Jacquerel** [comment]
Unholy Determination extinguishes fire stacks on you, so while you will still take more damage than if you did not set yourself on fire it probably won't kill you.

**Comment by SimplySmiley123** [comment]
> > It's a bit silly that you have something like a 2/5 chance to just accidentally set yourself on fire and burn to death depending on the type of heretic you get sacrificed by.
> 
> just.. don't step on them?

Try to avoid 4 bonfires when dodging the hands, add lag into the mix and yeah no you're likely gonna get set on fire by 'em.

**Comment by ZephyrTFA** [comment]
> > > It's a bit silly that you have something like a 2/5 chance to just accidentally set yourself on fire and burn to death depending on the type of heretic you get sacrificed by.
> > 
> > 
> > just.. don't step on them?
> 
> Try to avoid 4 bonfires when dodging the hands, add lag into the mix and yeah no you're likely gonna get set on fire by 'em.

Skill issue

**Pull request merged**
