### PR TITLE
Revert "Map config cleanup (#32132)"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This reverts commit fba7e224b92071632f5a584780eadf34220786f4. (#32132(@Cyberboss))

Broke map config.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
<details><summary>config_error.log</summary>
## WARNING: /tg/station 13 uses many file operations, a few shell()s, and some external call()s. Trusted mode is recommended. You can download our source code for your own browsing and compilation at https://github.com/tgstation/tgstation
Loading config file comms.txt...
Loading config file config.txt...
Unknown setting in configuration: 'maprotationchancedelta'
Unknown setting in configuration: 'log_hrefs'
Unknown setting in configuration: 'useircbot'
Failed to validate setting "" for fps
Unknown setting in configuration: 'log_runtimes'
Loading config file dbconfig.txt...
Loading config file game_options.txt...
Failed to validate setting "GANG 2" for probability
Failed to validate setting "BLOB 2" for probability
Failed to validate setting "GANG" for continuous
Failed to validate setting "BLOB" for midround_antag
Unknown setting in configuration: 'join_with_mutant_race'
Loading config file maps.txt...
map_config not found: _maps/tgstation2.json
Failed to load map config for tgstation2!
Unknown command in map vote config: 'friendlyname'
transition_config is not a list!
map_config failed to validate for above reason: _maps/metastation.json
Failed to load map config for metastation!
Unknown command in map vote config: 'friendlyname'
transition_config is not a list!
map_config failed to validate for above reason: _maps/pubbystation.json
Failed to load map config for pubbystation!
Unknown command in map vote config: 'friendlyname'
transition_config is not a list!
map_config failed to validate for above reason: _maps/deltastation.json
Failed to load map config for deltastation!
Unknown command in map vote config: 'friendlyname'
transition_config is not a list!
map_config failed to validate for above reason: _maps/omegastation.json
Failed to load map config for omegastation!
Unknown command in map vote config: 'friendlyname'
map_config not found: _maps/cerestation.json
Failed to load map config for cerestation!
Unknown command in map vote config: 'friendlyname'
Database connection established.

</details>


<details>
<summary>maps.txt</summary>
This file contains a list of maps for use in map rotation.
This feature requires you are running a Windows OS (or can other wise run .bat files) and that you are using the tgstation-server toolset in tools/
#Lines starting with # are ignored.
Lines not inside map blocks are also ignored
Duplicated entries use the latter one.
All whitespace at the start and end of lines is ignored. (including indentation, thats just for show)
Format:
#map [map name] (name of .dm file in _maps folder without the .dm part)
	friendlyname [name] (name shown to players)
	minplayers [number] (0 or less disables this requirement)
	maxplayers [number] (0 or less disables this requirement)
	default (The last map with this defined will get all votes of players who have not explicitly voted for a map)
	voteweight [number] (How much to count each player vote as, defaults to 1, setting to 0.5 counts each vote as half a vote, 2 as double, etc, Setting to 0 disables the map but allows players to still pick it)
endmap

map tgstation2
	friendlyname Box Station
endmap

map metastation
	friendlyname Meta Station
endmap

#map ministation
#	friendlyname Mini Station
#	maxplayers 20
#endmap

#map birdstation
#	friendlyname Bird Boat Station
#	maxplayers 30
#endmap

#map dreamstation
#	friendlyname Dream Station
#endmap

#map efficiencystation
#	friendlyname Efficiency Station
#	minplayers 25
#endmap

map pubbystation
	friendlyname Pubby Station
	maxplayers 50
endmap

map deltastation
	friendlyname Delta Station
	minplayers 50
endmap

map omegastation
	friendlyname Omega Station
	maxplayers 35
endmap

map cerestation
	friendlyname Cere Station
	minplayers 50
endmap
</details>

**Comment by MoreRobustThanYou** [comment]
classic @MrStonedOne -- reverts rather than fixes

**Comment by Jordie0608** [comment]
Reverts can be testmerged to immediately patch a major issue like this, fixes take longer to emerge.

**Comment by optimumtact** [comment]
plus it convinces the person responsible to make a fix

**Comment by duncathan** [comment]
this is SOP for major bugs

**Pull request closed without merging**
