### PR TITLE
Makes wizard a high impact ruleset

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

See title

## Why It's Good For The Game

Wizard has a big effect on the round, it should be a high impact ruleset so that it can't be chosen at a threat level lower than 90 if there's a cult, nukies, malf AI, revs or any other high imapct ruleset.

## Changelog

:cl:
balance: Makes wizard a high impact ruleset.
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by Mothblocks** [comment]
Wait change midround wizard too

**Comment by Watermelon914** [comment]
> Fuck. I'm gonna miss those once in a blue moon War Ops vs Wizard vs Traitors and commie wizard rounds that made dynamic so charming. 😢

those still exist, they happen at 90 threat

**Comment by wraith-54321** [comment]
oh goody of boy now black orbit is even more fun

**Comment by SethLafuente** [comment]
Honestly I don't think this is a good chance mostly for the fact that most of the time wizards aren't a big impact and die pretty quickly to crew for what I have seen their pretty rare anyways and a round with wiz cult and nukies is highly improbable and at the rare chance it happens it will be one hell of a fun round if I say so myself 

also I though nukies and wiz can't spawn together

**Pull request merged**
