### PR TITLE
The physical blackbox object no longer stores feedback data

### PR DESCRIPTION
**Pull request by ChangelingRain**
instead it's just a datum and shouldn't have multiples or fuck up

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
How this piece of crap survived as long as it did is beyond me.

Also, who in the ***hell*** thought it was a good idea to make this an in world actual object as opposed to a controller or datum to begin with?

**Comment by Jordie0608** [comment]
Take a guess https://github.com/tgstation/tgstation/commit/e6aa3fc0b12615ffcd9a21725cf6623f3bd571b9
Bonus points for being relative pathed.
<sub><sup>To be fair it was 6 years ago coding standards weren't really a thing nor was compiling your code.</sup></sub>

**Comment by MrStonedOne** [comment]
>How this piece of crap survived as long as it did is beyond me.

>Also, who in the hell thought it was a good idea to make this an in world actual object as opposed to a controller or datum to begin with?

The entire point was to make it meme well with "black box" as an object. the idea being that all in game stats go thru the stations blackbox recorder as a nice easteregg.

And its lasted 6 years because every time somebody tries to change it, I'm in here, defending it.

**Comment by optimumtact** [comment]
MSO this isn't tablecrafting and in this case it's a bit silly to have our feedback relying on a physical object that other people insist on breaking all the time.

**Comment by MrStonedOne** [comment]
Actually, this has only been broken once.

When qdel was added.

This wasn't a new bug at all, it was just that del(src) also acts as a return and that wasn't changed when it was changed to qdel()

The bug existed since then.

**Comment by MrStonedOne** [comment]
Not to mention that I would love to make an ability to actually delete this object, and i mean truly delete it, to wipe all stats for the round.

**Comment by MrStonedOne** [comment]
Like that can be a feature.

**Comment by MrStonedOne** [comment]
And the idea that it would be a facade, and it would really just flip some switch to not report them feels cheap.

**Comment by MrStonedOne** [comment]
If i added such a feature, what do you think players would find more cool?

"doing it just tells the game not to report the stats"

"doing it actually deletes the stats because the black box recorder actually is involved in storing/tracking the stats"

It's a subtle difference, but one is more cool.

**Comment by nfreader** [comment]
>Not to mention that I would love to make an ability to actually delete this object, and i mean truly delete it, to wipe all stats for the round.

Just so long as it's clear what happened to that round in the DB so I can work around it. It should, at the very least, report server, map, start time, end time, and then throw a flag that the blackbox was disabled/destroyed.

**Comment by coiax** [comment]
@MrStonedOne can we change the blackbox to something linked to the global datum, rather than storing it. Then the blackbox can be a reference, and have an admin switch or something. I always liked the idea of Centcom full of "admin machinery".

**Comment by optimumtact** [comment]
no because disabling something we are ostensibly using to make game balance decisions is a stupid idea.

mso please, you won, slap crafting is still in the game, there's no need for this

**Comment by MrStonedOne** [comment]
I haven't won because people still think removing the blackbox as the tracker of feedback stats is a good thing.

**Comment by ChangelingRain** [comment]
Wow, look, petty!
Hey, guess what, you _can_ delete the feedback data if you want, probably via sqdl or something, but that's fucking stupid.

I want stat logging even if it's from stupid admin bullshit; at worst, maybe a toggle to mark a round as admin bullshit so you can filter that out if you want, but I don't want to lose stat info.

**Comment by ChangelingRain** [comment]
>I haven't won because people still think removing the blackbox as the tracker of feedback stats is a good thing.

with that as your opinion you aren't going to win

**Comment by MrPerson** [comment]
Why would we bother gathering stats and then not report them? Clearly our "internal" stats should still record the round no matter what.

Add some sort of IC use for the stats and then filter out lost rounds from that. Our stats should record all rounds no matter what, period.

**Comment by Iamgoofball** [comment]
# compromise

the PR stays as-is, making sure our back end tracking stays solid and we can properly balance.

the blackbox becomes a tracker of generic stuff on station similar to what it does now, but it's used to compile a round-end report displayed to players at the end of the round, and can be accessed from in game via a button or something on the lobby screen showing past rounds

if it's destroyed, specific data becomes unavailable and only the most basic information is available from the lobby and round-end report

**Comment by ChangelingRain** [comment]
As long as you /always/ get stat info, OOC, I don't care what you do with the black box.

**Comment by optimumtact** [comment]
Same opinion as @ChangelingRain here

**Pull request merged**
