### PR TITLE
Fixes inability to construct walls with shuttlemetal

### LINKED ISSUE #15621: Walls cant be constructed using the /fifty metal subtype.
Had someone try to build a wall using metal sheets obtained from the shuttle. the stack spawned on the shuttle is the 50 subtype, which didn't work, while a regular stack did.

### PR DESCRIPTION
**Pull request by lordpidey**
Fixes #15621

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by KazeEspada** [comment]
:-1:

**Comment by RemieRichards** [comment]
This is a bad fix :-1:

**Comment by xxalpha** [comment]
this whole code
hqdefault

**Comment by tkdrg** [comment]
it's still awful but at least it fixes the bug

**Pull request merged**
