### PR TITLE
[READY] New recipe: deep fried butter on a stick

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Apparently people actually unironically do this, as shown by this video. It's nasty and gross, i don't suggest you watch it but here you go: https://www.youtube.com/watch?v=rUJjW3I65e4

~I was making it because I remember watching a video a long time ago where a kid comes into a restaurant and orders deep fried butter on a stick and we already have a deep frier so i just had to add this small thing to create the abomination that is the deep fried butter on a stick.~
[actionninja helped me find it](https://www.youtube.com/watch?v=dP0cudotB6g) 

## Why It's Good For The Game

There are chefs who try to make the most beautiful set of dishes in the game and they display them proudly. Then there are the chefs who make deep fried deep fried deep fried deep fried meatballs and throw them at any passerby they see. This is an appealing food craft for the latter group of chefs.

## Changelog
:cl:
add: You can now stick butter on a rod.
/:cl:

### CODE REVIEW

**Comment by bgobandit** [comment]
should cause a heart attack, we have that code in game

**Comment by tralezab** [comment]
i'm worried about balance problems and i want it to be a viable option to be the butter stick salesman

**Comment by KetasDotepasto** [comment]
5 percent chance of hert attack the first time you eat it, then 10, 15, etc. Each time you exercise, removes a fried butter.

**Comment by Tlaltecuhtli** [comment]
ame*ican food

**Comment by knacker48** [comment]
I really want someone to eat a bunch of these and get a heart attack. Suicide by butter

**Comment by PKPenguin321** [comment]
We already have food that blows off your arms, what's a heart attack gonna do?

**Comment by CRITAWAKETS** [comment]
Make this as the only food on the station. Russian Roulette for your nutrition.

**Pull request merged**
