### PR TITLE
No more low pop nuclear emergency

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
If/when someone comes up with proper scaling we can change the number back, but until then it's not really very much fun for skeleton crews to be stomped on by something that is arguably as strong as the deathsquad.

http://www.ss13.eu/tgdb/tg/latest_stats.html#mode_nuclear_emergency

### CODE REVIEW

**Comment by Steelpoint** [comment]
My problem is that according to the stats a population of 40+ people is when the Ops start getting only a 10% win rate. The 30-40 is the sweet spot of gameplay win rate wise of around 50%.

**Comment by Steelpoint** [comment]
Scratch that I'm a eeijet.

45+ is ok but is still pushing Ops towards losing more on average.

**Comment by Robertha89** [comment]
45 is a bit high tbh, since you can just throw bodies as the ops till they run outta ammo, or get disarmed. having 15 players on station is a bit low, but 40 is too high, so set the minimum to like 30.

**Comment by Steelpoint** [comment]
Round pop of 20 to 30 people is the main issue needing addressing, according to the stat's page Ops win those at around a 80% rate.

30 to 50 people is fine as is, with the win rate being around 50% for the Ops.

Its 50+ people where the Op win rates falls to 27% then to 7% past 60 people. That also need's addressing.

-----

The two big issues are rounds with 20 to 30 people and rounds with  50 to 60 people, with both giving a 80% win rate and a 20% win rate respectively to the Ops.

**Comment by KorPhaeron** [comment]
Added the stat link to the OP

**Comment by Core0verload** [comment]
:-1: Low pop needs some love, not outright removal. Remember, not every server that runs /tg/ codebase has 50 players normally.

**Comment by MMMiracles** [comment]
@Core0verload 
Wouldn't it make more sense to have the required players number be a config option per gamemode, anyway?

**Comment by KorPhaeron** [comment]
So give it some love then. No reason to leave it dysfunctional while we wait for someone to do it

**Comment by Steelpoint** [comment]
Nuke Ops has needed a scaling Op pop for a long time, but sadly no one's really been able to step up and code a solution.

This is really the end game if no solution is forthcoming.

**Comment by SweaterKittens** [comment]
I agree that lowpop Ops is truly awful, but 45 seems a bit high. if 30-50 is the golden 50% W/L ratio area, why not change the lower limit to 35, leaving 30 players on the station?

**Comment by Shapsy** [comment]
There's no point of having ops if the population is low enough that you can't generally depend on there being security and a captain

**Comment by Steelpoint** [comment]
Even with 40 crew men there's no guarantee there will be enough Security to even put up a token fight.

**Comment by Cebasiz** [comment]
scale based on sec/command pop when thank you

**Comment by TheNightingale** [comment]
I quite enjoy lowpop Ops when they don't just kill everything and nuke the station. In lowpop, it's much easier to have fun gimmicks (disk inspector, pizza delivery, poker ops, etc.), since there's less people who'll want to validhunt the Operatives.

**Comment by duncathan** [comment]
It sucks to see this go, but I understand why it has to leave
I want more game modes for extreme low pop

**Comment by CPTANT** [comment]
Ops should just scale at lowpop and start with 3 ops.

**Comment by Steelpoint** [comment]
@CPTANT That's what we all want but no one has come forward with a code solution, thus here we are.

**Comment by Cheridan** [comment]
until ops are fixed to scale backwards better this is the best solution

**Pull request merged**
