### PR TITLE
Resprites Donut Boxes

### PR DESCRIPTION
**Pull request by kinneb**
## About The Pull Request
Resprites the donut boxes to look better. and to be more accurate since the resprites of the actual donuts.
image
image
Old sprite for reference
image
image

## Why It's Good For The Game
I think it looks better, and it removes some very old sprites. Also shifts the sprite to be in 3/4ths.
## Changelog
-Changes all sprites for the donut box, and relating to the donut box.
:cl:
imageadd: Resprites Donut Box, and all sprites for donuts in it.
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
✅ for code

**Review by Imaginos16 — APPROVED** [review]

**Comment by Farquaar** [comment]
The sprite's a bit too big I think. I like tucking my donut box in the corner of my desk. This one takes up a whole counter tile.

**Comment by CRITAWAKETS** [comment]
the donuts need more depth shading to them, right now they look flat. then again, they _are_ donuts in space, so who knows what NT's doing.

**Comment by Helg2** [comment]
Donuts in this box look like donk-pockets.

**Pull request merged**
