### PR TITLE
Add smoke particles to fireplace

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
Adds some smoke particles to the fireplace while it's burning.

## Why It's Good For The Game
dreamseeker_PyMQFJc8Gz
## Changelog
:cl:
qol: Add smoke particles to burning fireplace
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
Please replace them with the fire particles. Fireplaces are designed to remove the smoke away, so it looks weird when you see it spewing it.

**Comment by Jacquerel** [comment]
Yeah the fireplace sprite actually does have a chimney attached, so smoke pouring out of the front is a little weird 😅

**Comment by timothymtorres** [comment]
Moved the particle position higher so that it's on the chimney.

dreamseeker_PyMQFJc8Gz

**Comment by timothymtorres** [comment]
That bug should be fixed with #79417

**Pull request merged**
