### PR TITLE
Adds a sprite for rubbershot and the rubbershot box

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

What it says on the tin. Give the rubbershot shell a blue stripe.

## Why It's Good For The Game

My sleepy brain (like the brain I have right now) confuses these two so sometimes I see beanbags and think 'ah yes this is the rubbershot I'm looking for"

ye

## Changelog

:cl:
imageadd: Gives rubbershot and rubbershot boxes a new sprite to differentiate them from beanbags.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Could you give the rubbershot (or beanbag) something more noticeable than a dot of a lighter green, like a stripe? They hardly look any different right now.

**Comment by necromanceranne** [comment]
That's a dot of blue and not green. Tell you what. When I get up tomorrow I'll make it full pink :3

**Comment by NanoCats** [comment]
image

I  had to blow these up waaaay big to tell the difference. Am I blind? ;-;

~~my personal thought is that they should just be a unique color~~

**Comment by necromanceranne** [comment]
It's just a really blendy colour. I'll fix it up no worries.

**Comment by NanoCats** [comment]
Well that certainly is more distinct

**Comment by EricZilla** [comment]
I kind of like the blue stripe on the green, consider adding that to beanbags?

**Comment by necromanceranne** [comment]
Sure, why not.

**Comment by Imaginos16** [comment]
Looks fine!

**Pull request merged**
