### PR TITLE
Digitigrade clothing sprites (feat. GAGS and 0 sprite bloat) 

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Use GAGS to auto-generate digitgrade leg sprites based off of 1 basic template + color sampling.
Icons are cached relatively aggressively, like female sprite variations. So no need to worry about that. 

The result: All of these sprites with only **3** icons added (the base template, and the masks)
Obviously it's not perfect - some of the sprites (like the engineer's jumpsuit) lose some "luster", but it does the job if I do say so myself.

image

Only applied to undersuits, for now. 

## Why It's Good For The Game

- Allows Lizards to show off their handicap, rather than hiding it or necessitating they use skirts. 

- (Ideally) leads to an uptick in Digitigrade abuse (due to being easier to identify), which is also a net positive.

- Implemented without any common issues revolving alt bodytype clothing sprites (those being maintainability and sprite bloat)

## Changelog

:cl: Melbert
add: Auto-generated digitigrade clothing sprites for most jumpsuits
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
very impressive

**Comment by MrMelbert** [comment]
Also here's a cursed image discovered in testing 

image

(has since been patched to look like normal clown garb, don't worry)

**Comment by MrMelbert** [comment]
Template updated slightly

image


image

**Comment by Kapu1178** [comment]
> Template updated slightly
> 
> image
> 
> image

old one looks better ngl

**Comment by thgvr** [comment]
> > Template updated slightly
> > image
> > image
> 
> old one looks better ngl

Old one was shaded very strangely and added a bunch of redunant colors to the pallette

**Comment by Wallemations** [comment]
I wonder if it'd be possible when sampling the colors to check if there's any colors that pop out from the main ones and mark that as a secondary color for a stripe or something

**Comment by MrMelbert** [comment]
well the latter part would certainly be possible, but i don't know how to programmatically pick out an "outlier" color from a list of hex colors

**Comment by theselfish** [comment]
> Also here's a cursed image discovered in testing
> 
> image
> 
> (has since been patched to look like normal clown garb, don't worry)

This is Clown if being silly was illegal...

**Comment by projectkepler-ru** [comment]
does this still allow sprite to be manually used to replace in digit case?

**Comment by MrMelbert** [comment]
yes, this is just another option

**Comment by projectkepler-ru** [comment]
> yes, this is just another option

ohhh nice

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
Merge conflicts tho.

**Pull request merged**
