### PR TITLE
medborgs get autopsy scanners

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

medborgs get autopsy scanners

## Why It's Good For The Game

them being able to do autopsy is good incase of no coroner and crew being too lazy to just walk and buy an autopsy scanner
and also like investigative medbay shenanigans and stuff

## Changelog
:cl:
add: medical cyborgs have autopsy scanners
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
i'm not fond of furthering making cyborgs into super duper truper good workers that undermines another job's contents, what are your thoughts @JohnFulpWillard

**Comment by AdamElTablawy** [comment]
The agony of screaming for SOMEONE to do dissections for the required biomedical research is really getting grating, especially when the coroner never does it and never has an interest in doing it

**Comment by the-orange-cow** [comment]
> The agony of screaming for SOMEONE to do dissections for the required biomedical research is really getting grating, especially when the coroner never does it and never has an interest in doing it

This.  The scanner effectively functions as a gate on getting basic med research done.  Access to the scanner was restricted, which leads to someone needing to break into the coroners office and shell out 100 cred in about 50% of shifts.

Giving mediborgs a scanner isn't turning them into superbots, its marginally reducing the bottleneck that was only recently introduced.

**Comment by excalisword** [comment]
To be honest, we should just give the mediborg's scanner the capabilities of the autopsy scanner instead since it's not capable of being upgraded.

**Comment by ATH1909** [comment]
I'd maybe make this an upgrade that can be printed at roundstart instead of an addition to their default kit.

Mediborgs already have a bloated inventory, and this adds an extra bit of clutter that ceases to be relevant once the coroner dissection surgeries are done.

Locking it behind a roundstart upgrade adds an extra barrier that discourages mediborgs from barging into the morgue and doing dissection surgery before the coroner has their shit together, but still makes it possible for mediborgs to do this surgery if there aren't coroners (or willing MDs/CMOs).

**Comment by ATH1909** [comment]
Maybe this could be an upgrade that's available at roundstart? Then again, begging a human to install an upgrade is about as annoying as begging a human to buy an autopsy scanner and do the surgery themselves...

**Comment by JohnFulpWillard** [comment]
make it work like the defib that you can just insert into a borg instead

**Comment by chemistrymain2** [comment]
maybe we should just remove the dissection requirement for autopsies to get literal basic medical research done huh

what if we did that

**Comment by mc-oofert** [comment]
> make it work like the defib that you can just insert into a borg instead

this undoes what is fixed

**Comment by mc-oofert** [comment]
also coroners sole job is to do a dissection roundstart theres literally nothing else valuable for them to do idk what content youre talking about

**Comment by JohnFulpWillard** [comment]
ok well i have no interest in arguing for this for the 3rd time https://github.com/tgstation/tgstation/pull/76406 - https://github.com/tgstation/tgstation/pull/75205

**Pull request closed without merging**
