### PR TITLE
Spraytan Nerf

### PR DESCRIPTION
**Pull request by Robustin**
MFW I sacrifice my hard-earned GBP to make the game a better place. Was having some chemistry hijinx earlier when someone taught me that spraytan can easily permastun you. Fellow chemist stunned themselves for over 5 minutes, honk. 

:cl: Robustin
balance: Spray tan no longer stuns when ingested.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
Don't remove it entirely, just nerf it

**Comment by PKPenguin321** [comment]
Nah this is fine, it doesn't really need the stun at all

Maybe have it deal a little toxin

**Comment by Doppeltongue** [comment]
Sprays to the eyes are supposed to stun, but it makes no sense for this chem to stun.

**Comment by kevinz000** [comment]
now do it to salve

**Comment by Supermichael777** [comment]
miners slave dosn't stun anymore. Memed those ops good for a while thou

**Pull request merged**
