### PR TITLE
Creates an ambience global list for icebox and adds 10 new tracks to the exterior! (THANK YOU JOHN WILLARD!)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Creates an ambience global list for icebox and adds ten new tracks to the exterior. Among the tracks are 5 instrumental stings, 4 microsong melodies, and 1 thematic song.

HUGE thanks to John Willard for managing the coding aspect of this. All the music is my creation, but without him, it'd just be sitting on my hard drive. Love the guy.

## Why It's Good For The Game

Differentiates lavaland and icebox stylistically in their tones, key, and musical instrumentation. Makes the world feel more alive!
If you want to add more ambient tracks for the zone, all of the tracks come in the following keys:
G# HARMONIC MINOR
G# NATURAL MINOR
Db NATURAL MINOR

## Changelog

:cl:
add: Ambient tracks for icebox.
add: Independent global_list for icebox.
/:cl:

### CODE REVIEW

**Comment by tommysalami3** [comment]
Message me if you want to be mass-sent the .ogg files. A high-quality, uncompressed reupload of all the music will be put onto my channel at a later point, with the main theme already being on it.

**Comment by san7890** [comment]
can you just use something like vocaroo in the interim so i can just listen to a quick cut of it without downloading the files? thanks

**Comment by tommysalami3** [comment]
I'll send them to you on discord, no download needed. They all easily fit in the size reqs

**Comment by EricZilla** [comment]
Love the theme a lot

**Comment by tommysalami3** [comment]
https://youtu.be/JM2bKzap5l4

**Comment by tommysalami3** [comment]
Link of the songs!

**Pull request merged**
