### PR TITLE
Removes junk files and sets gitignore for CreditsTool

### PR DESCRIPTION
**Pull request by TiviPlus**
## Nothing to see here

I wonder why this is here we will never know who added it

## Why It's Good For The Game

None of your business citizen

### CODE REVIEW

**Review by Rohesie — DISMISSED** [review]
This has never happened.

**Comment by willox** [comment]
Should this be gitignored the same way MapAtmosFixer is?

https://github.com/tgstation/tgstation/blob/e17ea62611ac981e68f083bf424c85e00d42bdde/.gitignore#L199-L200

**Comment by TiviPlus** [comment]
The tools deprecated actually so this is a removal now

**Comment by Jared-Fogle** [comment]
huh weird.......no files changed.....like if nothing was ever here....

**Review by Rohesie — DISMISSED** [review]

**Comment by Qustinnus** [comment]
Credits code is still in the repo so removing this without removing credits is weird. Unless I'm mistaken and credit code is gone

**Comment by Rohesie** [comment]
Are there other traces of that code in the repo?

**Comment by Qustinnus** [comment]
yes, credits.dm.

**Comment by TiviPlus** [comment]
Yea its there guess it should be gitignored
someone else can remove credits since  they're disabled

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Either CreditsTool should stay or `credits.dm` should go

**Pull request merged**
