### PR TITLE
Food expansion 5: The big one!

### PR DESCRIPTION
**Pull request by MidoriWroth**
## About The Pull Request

This is my 5th food expansion PR, adding and changing quite a few food-related things.
This PR will:
- Add 32 new foods
- Refactor how rice works, making the water/rice reaction no longer need a bowl.
- Foods that make use of rice bowls now instead require boiled rice and a bowl.
- Allow vinegar to be made from equal parts water/sugar/wine
- Add hard-shell tacos which can be used to make custom tacos and some of the foods listed

image

**First row:** Baked potato, buttered baked potato, loaded baked potato, raw calzone, meat calzone, vegetarian calzone, Philly cheesesteak, raw meatloaf, meatloaf, meatloaf slice

**Second Row:** Peanut butter brownie batter, peanut butter brownie sheet, peanut butter brownie, chocolate truffle, caramel truffle, peanut truffle, peanut butter cup, uncooked rice, boiled rice, crunchy peanut butter tart

**Third Row:** hard taco shell, classic hard-shell taco, plain hard-shell taco, meat chimichanga, vegetarian chimichanga, refried beans, Spanish rice, cheese pierogi, meat pierogi, chicken noodle soup

**Fourth Row:** Custom taco example, corn chowder

If you see anything that looks like it needs a change or any suggested additions, please let me know!

## Why It's Good For The Game

Adds more creativity and depth to the cooking system, allowing for more food options and easier access to ingredients you should be able to make yourself. For rice in particular, the previous way to make it was annoying and time consuming, and recipes that used boiled rice that did not make use of a bowl consumed the bowl afterwards. This PR will fix that by making rice not require a bowl to begin with, and recipes that require it have the bowl as an ingredient now.

## Changelog
:cl:
add: Adds 32 new foods!
add: You can make vinegar from equal parts water/sugar/wine
add: Tortillas can now be grilled to make hard-shell tacos, which can be used to make the new tacos or custom tacos all-together.
balance: Uncooked rice is now made from mixing 10 units rice/water in any container, no longer requiring a bowl to do so. Recipes that previously used bowls of rice now need boiled rice and a bowl, instead.
/:cl:

### CODE REVIEW

**Comment by Oranggu** [comment]
Yummy update....

**Comment by Serxule** [comment]
some of the sprites are a pretty messy and nondescript (i thought the buttered baked potato was a fried egg on a tortilla) but otherwise nice

**Comment by newfren** [comment]
vinegar might want universal enzyme as a catalyst? we use it for wine and grappa making already

**Comment by MidoriWroth** [comment]
> vinegar might want universal enzyme as a catalyst? we use it for wine and grappa making already

not a bad idea

**Comment by dragomagol** [comment]
It hurts me greatly that our misc food dm is over 1000 lines long.

**Comment by MidoriWroth** [comment]
> It hurts me greatly that our misc food dm is over 1000 lines long.

Yeahhh, I know. I'd really like to see sub-menus for everything to make it a bit more organized, but I dunno how to do any of that.

**Comment by MTandi** [comment]
> > It hurts me greatly that our misc food dm is over 1000 lines long.
> 
> Yeahhh, I know. I'd really like to see sub-menus for everything to make it a bit more organized, but I dunno how to do any of that.

I think we need some food expansions that reduce the number of recipes instead of adding more. I'm certain that we have a lot of recipes that are never crafted even once in a month.

**Comment by MidoriWroth** [comment]
> > > It hurts me greatly that our misc food dm is over 1000 lines long.
> > 
> > 
> > Yeahhh, I know. I'd really like to see sub-menus for everything to make it a bit more organized, but I dunno how to do any of that.
> 
> I think we need some food expansions that reduce the number of recipes instead of adding more. I'm certain that we have a lot of recipes that are never crafted even once in a month.

You're right, I might squeeze that into this update, actually.

**Comment by dragomagol** [comment]
If you're removing recipes that should be in a separate PR. This PR is already pretty hefty. 

Additionally the easier way to reduce the files is to separate them into different .dms instead of putting them all into misc

**Review by dragomagol — APPROVED** [review]
Code-wise seems all right, just waiting for a +1 on sprites

**Comment by MidoriWroth** [comment]
what the heck happened lmao

**Comment by dragomagol** [comment]
That error's not your fault; once #71990 gets merged you should pull master and it'll fix

**Comment by MidoriWroth** [comment]
it's been a few days approved now, could a spriter approve this soon please?

**Comment by EOBGames** [comment]
> Additionally the easier way to reduce the files is to separate them into different .dms instead of putting them all into misc

Should be a simple enough change- if nobody's handled that prior to my next change to food, I'd be happy to tackle it myself.

**Pull request merged**
