### PR TITLE
Swarmer rev 2 fixes/changes | Some hostile mob range attack tweaks

### PR DESCRIPTION
**Pull request by Ergovisavi**
- Removed ability for swarmers to pass through mobs on harm, retained their ability to pass through other swarmers

> The yakety sax was unreal. Swarmers already have the ability to spit out traps and disablers behind them, this was a bit much and should help regular crew members pin them down a tiny bit easier. Swarmers still pass through other swarmers because otherwise STOP FUCKING BUMPING ME IM TRYING TO TELEPORT HIM etc
- Removed ability to eat Telecomms, Gang signs, cult runes

> Keeping Swarmers out of telecomms is basically impossible and repairing it is just unfun. It also completely stops the crew from rallying against them, as they tend to have no idea where they are afterwards. I also believe that the handling of telecomms should be delegated to the current round antagonists.
> 
> Gang signs and Cult runes removed because no fun allowed, but more importantly I want swarmers to focus on eating objects or the environment, and having THAT interfere with other antagonists, not directly sabotaging their mechanics.
- Added a 1 second cast time for Barricade, EMP now destroys swarmer structures instantly

> Barricade was just a hundred times better than trap, and was spammed as a reactionary measure instead of a precautionary one. A barrier was better than a trap in almost any situation, so I'd like to experiment with this. You basically just can't use it on the run anymore, but you can still fortify a position fairly quickly. Also, the Ion rifle should have some use against Swarmers.
- Changed the effects used by some swarmer abilities (Removed sparks)

> I think good visual feedback is a cornerstone of good game design, and helps flesh out mechanics. People were getting confused thinking that they were consuming things like vomit for resources when in actuality they were just destroying it. In addition, sparks could cause fires if there was plasma in the air, and while you can still generate sparks by disintegrating lights or other things, now it has to be deliberate, you won't set off a fire just eating the place.

Swarmer stuff
- Traps now stun borgs

> I like borgs being scary to swarmers, but the complete lack of counterplay was a little depressing. This should make things more interesting.
### OTHER STUFF
- Fixed hostile mobs being unable to shoot people lying down on the ground
- Fixed hostile mobs not being able to use projectiles they fire to change their velocity in space (Clientless mobs do not have this feature as it would screw up their pathing too much)
- Fixed an issue where Swarmers could cause pressure leaks/hull breaches in select portions of the map

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:+1:

**Comment by Steelpoint** [comment]
That animation really goes a long way in conveying what it is the swammer is doing, both to the swammer and to a observer.

:+1:

**Comment by Bluespace** [comment]
A couple requests.
Can you fit swarmer door eating in this?
Can some text feedback be given on items that can be destroyed but take a lot of crtl clicks to do so? (IE: You can EVENTUALLY destroy watertanks, but get no feedback you're doing so.) 
Swarmers need to be able to tear up and demolish floor tiles for one material point. Plating really gives an area a "deconstruction" feel.

**Comment by Ergovisavi** [comment]
I'll add door eating.,, since it seems everyone and their mother demands it for some reason.

The text feedback part isn't realistically possible without adding in text description for literally every item in the game. It uses ex_act() to destroy things, which is set per object without a var, so there's no way to actually tell if something is possible or not to be destroyed in a such a fashion.

As for the floor tile thing, I agree with you from a feeling standpoint by far, but design wise I don't think that's a step in a good direction. Eating objects, destroying walls and machine, etc, all of those things are negative for the station as a whole. Eating a floor tile doesnt really impact things, and I don't want to see swarmers eating floor tiles all day instead of doing things like ripping holes in departments or eating the cloner.

**Comment by sirnat** [comment]
Add ways to do things to borgs instead of being ran over by them!

**Comment by Ergovisavi** [comment]
Forgot to state that traps now weaken borgs. So, you can't directly attack them, but you can counterplay it a little bit.

**Comment by Stickymayhem** [comment]
You're such a good designer Ergo all this stuff is great.

It might be nice to give the option of tearing up floor tiles even if it doesn't actually add to resources. Swarmers are so satisfying to play mainly because you're reducing the area you eat to a husk.

**Comment by Razharas** [comment]
Is this ready @Ergovisavi ?

**Comment by Ergovisavi** [comment]
This is merge ready. I can add door eating in another PR, but at the moment MGSV has all my attention.

**Pull request merged**
