### PR TITLE
Cargo can now order empty supplypods through the express console

### PR DESCRIPTION
**Pull request by MrDoomBringer**
## About The Pull Request
Adds an empty supplypod order that sends a single bluespace pod with nothing in it. This is 100 credits more expensive than ordering the "empty crate" pack and refunding the crate, and as a bonus is guaranteed not to leave a normal supplypod lying around after.

People would also sometimes use the cheaper funeral crate to do this, so the price for that has been increased to compensate.

Also, this:
 - ~removes the strange ability to undo the emag effect on the board with a multitool~ @Timberpoes convinced me to not do this!
 - allows ordering contraband stuff without having it be launched all over the station. Syndicate gear and special items are still restricted to the cargo shuttle.
 - tweaks some supplypod / expressconsole timing values. Empty supplypods reload faster!

## Why It's Good For The Game
Allows cargo to send in supplypods with dubiously-malicious intent (ie executing a cargo tresspasser buckled to a chair, using the emagged express console) without completely cluttering the station with a bunch of empty crates and opened supplypods lying around everywhere. People doing this is cool and emergent gameplay, but right now the leftover pods and stuff are pretty annoying.

## Changelog
:cl:
add: Empty supplypods can now be bought from your local express console!
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
McAirstrike buff.

**Review by Timberpoes — CHANGES_REQUESTED** [review]
Please don't remove the multitool removing the board's emag effect. Because the console should (when my PR fixing it gets merged) inherit the emagged status of the circuit, unlike other machines where you can deconstruct and rebuild it to remove the emag effect there's no way to do that here.

It's also undocuemnted in your CL and you've failed to justify why that change in particular is good.

**Comment by MrDoomBringer** [comment]
@Timberpoes i didn't realize other machines could have the emag effect removed by board removal! thought it was meant to be a permanent issue that just fried the board, hence the change. Sure I'll revert it

**Comment by Timberpoes** [comment]
> 
> 
> @Timberpoes i didn't realize other machines could have the emag effect removed by board removal!
> I thought it was meant to be a permanent issue that just fried the board, hence the change. Sure I'll revert it

Thanks!

And it's just unique to this machine. Every other emaggable `/obj/machine`-type including computers will have the emag effect cleared on deconstruction/rebuilding because the emag status is just a part of the machine itself.

Supply and express supply consoles are unique in that you can actually emag/multitool the board and building the machine (should, when the PR fixing it gets merged) inherit this status from the board.

**Comment by MrDoomBringer** [comment]
dumb stupid

**Comment by MrDoomBringer** [comment]
this is ready to merge btw

**Comment by MrDoomBringer** [comment]
pwned by the bot :(

**Pull request merged**
