### PR TITLE
Hotfix for Xeno saycode.

### PR DESCRIPTION
**Pull request by Razoozle**

### CODE REVIEW

**Comment by Niknakflak** [comment]
Get rid of that comment, it's obsolete due to current policy anyway.
:-1: :-1:

**Comment by Ultimate-Chimera** [comment]
I just copy-pasta'd but sure.

**Comment by Incoming5643** [comment]
don't merge this right away I can probably fix the issue pretty painlessly.

**Comment by Ultimate-Chimera** [comment]
Done @Niknakflak

**Comment by Niknakflak** [comment]
:+1:

**Comment by PKPenguin321** [comment]
let incoming handle it instead of making hacky kneejerk fixes

**Comment by Ultimate-Chimera** [comment]
@PKPenguin321 This works, I'm not sure why he needs to call all of this stuff as he just removed the sound from their main saycode file. It still works for other mobs with the tongue. But he can fix it his way, I guess.

**Comment by Incoming5643** [comment]
the idea is to have the tongue do the work so if you move it somewhere else the behavior follows it.

**Comment by Ultimate-Chimera** [comment]
#16864

**Comment by Ultimate-Chimera** [comment]
@Incoming5643 Yep, it makes sense. If you surgically remove their tongue, they shouldn't be able to hiss.

**Pull request closed without merging**
