### PR TITLE
Adds walterje's PDAs

### PR DESCRIPTION
**Pull request by ghost**
Palm pilot edition.
Credit to https://tgstation13.org/phpBB/viewtopic.php?f=11&t=1659

pda

### CODE REVIEW

**Comment by Chocobro** [comment]
:+1: these sprites are so fucking cool.

**Comment by vista-** [comment]
NanoUI for PDA when??

**Comment by paprka** [comment]
never

**Comment by pudl** [comment]
these are really really bad

**Comment by ike709** [comment]
these still aren't as bad as the current ones

**Comment by dannno** [comment]
I like them but I also like the current ones immensely, especially since they fit more since they don't have Nanoui. I don't think these should be added without also implementing Nanoui

i mean it's probably unreasonable but it's what I think

**Comment by pudl** [comment]
the current ones are WAY better than these. these literally look like a nintendo game accessory

**Comment by paprka** [comment]
the current ones are xbox huge and look like shit

**Comment by pudl** [comment]
these are barely any different in size, and the current doesn't look like shit at all.

**Comment by paprka** [comment]
keep your bad opinions to yourself

**Comment by Lumipharon** [comment]
They look alright, but the current ones are more functional - they're easier to distinguish because of the larger coloured areas.

**Comment by PKPenguin321** [comment]
What Lumi said, I like these a lot but since these sprites give less room to the unique colors of a PDA they're harder to identify what job they go to.

**Comment by WJohn** [comment]
These looks pretty good, though as others said it'd be nice if the outlines were made a bit darker and the job-specific fill a bit brighter.

**Comment by TZK13** [comment]
Meh, I prefer the current sprites over these, especially in regards to actually distinguishing between them.

**Comment by Cheridan** [comment]
The new cartridges are neat, but I agree with the sentiment that the current ones are easier to distinguish and look better in general.

**Comment by paprka** [comment]
How about sec getting those nifty palm pilots with the cases then?

**Comment by Steelpoint** [comment]
I like these PDA's.

Maybe only given them to Heads of Staff and Security for the cool factor (Buddying up with Centcom has to have its perk's sooner or later).

**Comment by paprka** [comment]
yeah i guess it makes sense to go that route instead of replace all of them

Ideally all PDAs will look different in the future, IE how the librarian gets one with a keyboard

**Comment by spheretech** [comment]
Nonsense, these are 1000 times better than the originals the hells up with you people

**Comment by paprka** [comment]
I'll just add some of them so everyone can be happy

**Comment by dannno** [comment]
It might just end up looking disjointed and weird to have some people have extremely different looking PDAs but w/e

**Comment by Delimusca** [comment]
there's something off about that colour text on those grey screens, but i love the shells themselves.

**Comment by paprka** [comment]
Due to how the overlays for recieving a message works I cbf with this and making certain Pdas look different because lazy

**Pull request closed without merging**
