### PR TITLE
"Freshness Jars full of Natural Bait" is now a goodie and costs 200 instead of 2000

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
All other fishing-related packs (fishes are considered livestock) are goodies, and none of them costs anywhere this much.

## Why It's Good For The Game
That's some overpriced jar of ~~kronkaine pills (1u)~~ fishing baits.

## Changelog

:cl:
balance: "Freshness Jars full of Natural Bait" is now a goodie and costs 200 credits instead of 2000
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
should be 500 (hank gives jack 5 bucks for the freshness jars)

**Comment by Ghommie** [comment]
> should be 500 (hank gives jack 5 bucks for the freshness jars)

Pffft, that's a bit too *high*, man, especially when the crew paycheck averages out at a tenth of that amount.

**Comment by necromanceranne** [comment]
It was actually 20 bucks. So why not make it 200 credits, you've not got a crate to worry about.

**Review by ArcaneMusic — APPROVED** [review]
Seems fine

**Pull request merged**
