### PR TITLE
March into Mapness-Pod crash (Don't pda and pod)

### PR DESCRIPTION
**Pull request by Rex9001**
## About The Pull Request

Adds a new ruin displaying the tragedy that befalls those who choose to pda and pod.
SDMM:
Skärmbild 2023-03-20 181332

Ingame:
Skärmbild 2023-03-20 181607
### Mapping March
Ckey to receive rewards: N/A (Already made a map :) )

## Why It's Good For The Game
Adds a smaller ruin without much loot, really its just a small ruin that showcases some light lore
## Changelog
:cl:
add: the pod_crash.dmm ruin
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I like this concept a lot but I am afraid that (at least to me) I am not sure that scrambling the tiles creates a good approximation of a crash in-engine, because of the pristine walls it ends up sort of looking like an intentional but weird construction with a small enclosed space and individually placed pillars rather than a collapsed hull.
You might be better off just making a pod with holes in it? Maybe use broken grilles, wall girders, or some tile decals to give the destroyed wall effect?

**Comment by Rex9001** [comment]
Skärmbild 2023-03-20 190544
New Image based on Jacquerels feedback. Thumb down if you prefer the old look.

**Comment by Addust** [comment]
make the girders displaced

**Comment by Sealed101** [comment]
some lattices to simulate torn out hull around the single wall tiles would make it look much more natural, otherwise good ruin 👍

**Comment by MMMiracles** [comment]
Small gripe: Use the turf/area passthrough ('/turf/template_noop' and '/area/template_noop') where you currently have space tiles. How you currently have it won't really effect anything but it keeps consistency with the rest of our ruins and prevents overlap issues if it ever manages to occur.

Otherwise, fix your conflicts and this should be good to merge.

**Comment by Rex9001** [comment]
> Small gripe: Use the turf/area passthrough ('/turf/template_noop' and '/area/template_noop') where you currently have space tiles. How you currently have it won't really effect anything but it keeps consistency with the rest of our ruins and prevents overlap issues if it ever manages to occur.
> 
> Otherwise, fix your conflicts and this should be good to merge.

Great! Was just wondering if I should wait for sans The Flattening pr

**Comment by Rex9001** [comment]
Nvm merge conflict fixed

**Pull request merged**
