### PR TITLE
Ore is now immune to lava

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Ore is now immune to lava. You might have trouble getting it back OUT of the lava, but hey.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I'm not sure I understand why you would need this?

**Comment by Ergovisavi** [comment]
Free Golems or people accidentally dropping bananium into lava, I would assume.

**Comment by optimumtact** [comment]
I'm not sure that just making ore immune to lava makes much sense, the issues you are referring too seem like human error?

lava is an environmental hazard and dealing with it should be an interesting challenge for the players.

**Comment by ChangelingRain** [comment]
It makes using bombs not worthwhile because all the ore gets blown into the lava and that's boring

**Comment by KorPhaeron** [comment]
hugbox

**Comment by TechnoAlchemisto** [comment]
as someone who has used bombs to mine, it's not that big of a problem

**Comment by Bawhoppen** [comment]
make ore smelt when thrown into lava

**Pull request closed without merging**
