### PR TITLE
Beanbag buff, syndie hardsuit nerf

### PR DESCRIPTION
**Pull request by ghost**
I've done some testing on beanbag shells vs syndicate hardsuits. Since the only ranged counter to eshields is beanbag shells or the detective's revolver (barring protolathe guns), they did a pitiful amount of stamina damage to syndicates.
- Lowered the bullet resistance of syndicate hardsuits to 30 (same as the laser resistance)
- Raised the stamina damage of beanbags to 98

It will now take two beanbag shells to weaken a nuke on in a hardsuit, since they're clunky to use to make up for it.
They will also stun unarmored people in one hit, unless they're 100% healthy.

### CODE REVIEW

**Comment by Ergovisavi** [comment]
Keep in mind that when you're nerfing the syndie hardsuits, you're also increasing the effects of friendly fire amongst the syndies.

**Comment by Lumipharon** [comment]
Shotgun slugs/pointblank buckshot becomes awfully strong against ops after this.

Also yeah, getting shot by tard ops in the back will suck a lot more after this.

**Comment by Steelpoint** [comment]
It takes four disable shots to stun a nuke ops. If we go with the RNG deflection for shooting a eshield it could take anywhere between 4 to 20 shots to stun a nuke op.

If I shoot a Op with a weapon, it should either hit, or be deflected. No RNG bull.

**Comment by Fox-McCloud** [comment]
I feel nerfing the armor to 35-40 and buffing the shotgun shells to 85 would be much more doable; it still means 2 hits to down an op (51 stamina and 3 regular damage), but retains the "two shots to down" mechanic for everyone else too; if beanbag shells do 98 damage, then they're back to an instant stun for the barkeep and riot-shotgun users again.

**Comment by Jordie0608** [comment]
Changelog

**Comment by paprka** [comment]
Disabler shots go through eshields?

Eshields are supposed to be a straight 100% deflect on all energy projectiles, they're ridiculously expensive.

**Comment by Lumipharon** [comment]
No, I'm saying destroyer projectiles from pulse rifles/destroyers CAN go through e-shield. I duno if it's even intended or not, but if you keep shootin a guy with an e-shield (like another squid), although a lot DO bounce, some go through. Just suggesting if disabler shots did the same, sustained disabler fire could be an alternative solution to e-shields. It would take a load of shots considering reflect/block chances and armor, but sec would atleast be not entirely defenceless lambs against an e-shield.

**Comment by paprka** [comment]
Sec can always rush them with stun batons but I like the idea of the warden/detective having to whip out their specialty weapons to take down e shield ops.

**Pull request closed without merging**
