### PR TITLE
Makes vodka able to clean floors

### PR DESCRIPTION
**Pull request by zenek123**
Its the most usefull feature of the century

### CODE REVIEW

**Comment by bgobandit** [comment]
>coding on master

**Comment by MMMiracles** [comment]
@bgobandit that's how confident he is the pull will be accepted.

**Comment by zenek123** [comment]
sorry , i am new to github ,and i have no idea how this works

**Comment by Iamgoofball** [comment]
:+1: good PR

**Comment by KorPhaeron** [comment]
There should probably be a better way than snowflake checks for 3 specific chems but I dont want to crush a new coders first PR

**Comment by Cheridan** [comment]
@Kor it wouldn't be hard at all to just make it a var and have it check that instead

**Pull request merged**
