### PR TITLE
Cleans up some chemmaster varedits

### LINKED ISSUE #30786: You can walk over/on top of chem masters
see title

### PR DESCRIPTION
**Pull request by ShizCalev**
fixes #30786

### CODE REVIEW

**Comment by msgerbs** [comment]
... Why would somebody do this in the first place?

**Comment by ShizCalev** [comment]
@msgerbs lazy copypasta from other maps.

**Comment by Mark9013100** [comment]
I'm fairly certain the density 0 chem masters on delta and omega are for placing meds in the chem fridge.

**Comment by ShizCalev** [comment]
@Mark9013100 You can put things into it, just have to open the window to access it.

**Comment by msgerbs** [comment]
You shouldn't have to open the window though, that's part of the point of the smart fridges.

**Comment by ShizCalev** [comment]
That's weird considering the chemmaster on Delta isn't even adjacent to the smartfridge (meaning this doesn't affect it at all.)

**Comment by ShizCalev** [comment]
tahvcb4
Moved the chemmaster on Omega to be between the chairs, resolving the complaint above.

**Pull request merged**
