### PR TITLE
initial hygiene tweaks

### PR DESCRIPTION
**Pull request by ghost**
:cl: floyd / qustinnus
tweak: Hygiene now lowers slower when you are clean, and dirtiness rates for some clothing items have been nerfed.
tweak: some more clothes are okay to shower with now.
tweak: only 20% as much miasma is produced by low hygiene
/:cl:

a small PR that will atleast alleviate some grievances, while I work on a bigger PR to sort the other problems out.

miasma rates are lowered by 80%
you can now shower with shoes, heasdsets and gloves because they're neglectable at best.
you only lose 25% as much hygiene when youre clean as you did before
shoes gloves and hats have lowered hygiene draining rates when bloody as compared to before

### CODE REVIEW

**Comment by coiax** [comment]
Gonna be only Qustinnus, I'd replace the miasma emission with just a gradual series of mood penalties. In addition, when someone is truly stunk, they give negative moodlets and messages to everyone around them, (additional messages if someone with low hygiene gives you a hug, a la The Sims). I'd also consider making the green smoke less obvious, more subtle, give dirty people messages that they feel grubby.

Also, give people examine messages to see how dirty they feel.

**Comment by Qustinnus** [comment]
im also thinking of removing miasma emission and creating my own, weaker, disease system thats less potent than miasma. I think mood penalties will probably be added but not too strong. besides that I'll make the smoke more transparent and add more feedback in the form of text (chat and examine).

most of that is planned for a bigger PR as mentioned in the OP, I just wanted something out quick so I can stop getting pitchforks yeeted at me.

**Comment by Qustinnus** [comment]
people told me it was dumb that people could shower with their clothes on so I removed the ability to shower with your clothes on.

I also think that getting attacked in the shower when youre weak is one of the few interesting ways an antag can get you without just murderboning you in the hallway, theft is also interesting. I do see a problem for security being robbed by greyshits and a segregated sec shower might be a good idea, (tfw bullied so hard you get a seperate shower)

**Comment by zxaber** [comment]
I can agree on the need to remove clothing to shower, both for the good mood and to remove the stank thing, but I still think it's stupid to have a *negative* moodlet applied when you shower with clothes on. Having a moodlet that says "I sure am an idiot for showering with clothes on" rather than, y'know, "I sure am glad I'm *no longer on fire*" seems weird.

**Comment by hazamaitsuru** [comment]
I was looking through the shower code earlier today and if I'm not missing something, showers don't extinguish mobs anymore. So it doesn't matter if you're burning or not!

**Comment by zxaber** [comment]
So it's impossible to do surgery on a plasmeme now?

**Comment by tuypo1** [comment]
fuck no coiax both mood and hygine are already dumb enough without bringing them together.

**Comment by Tlaltecuhtli** [comment]
shouldnt athletic shorts and swimsuits be showerfriendly too?

**Comment by dr-bee** [comment]
> 
> 
> shouldnt athletic shorts and swimsuits be showerfriendly too?

Would help with the nevernudes. There are dozens of us. DOZENS!

**Comment by Cyberboss** [comment]
>you can shower with shoes

Yes, officer, this PR right here

**Comment by Qustinnus** [comment]
ok but people cried about it so what should i do cyberboss

**Comment by erwgd** [comment]
I recommend you add showerokay to breath masks. A small mask would be fine, as IRL people on oxygen do shower while wearing a mask or cannula. 

Consider making plasma envirosuits showerokay since they're similar in look and function to bio suits. 

Wearing a bio suit lets you wear anything else for a good shower, even if you're wearing a mask and/or glasses. You should need to wear a bio hood if you want to wear headgear in the shower.

**Comment by subject217** [comment]
image

**Comment by Tlaltecuhtli** [comment]
@Qustinnus dont listen to forum plebians, you can shower with athletic shorts just fine

**Pull request merged**
