### PR TITLE
Removes mailbombs

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

When mail was first added, its creator specifically specified that things like mail bombs weren't included in the system because they would encourage people to simply not interact with mail at all.
#75390 added a way to sabotage mail by placing objects inside which would activate themselves upon opening the envelope. During the PR several people expressed concern that merging this would lead to people simply not opening their mail (similar to old issues with PDA bombs, where people would simply disable or dispose of their PDA messenger every round to avoid their PDA exploding).
Three months later, I have seen multiple people noting that they now never open their mail any more, after experiencing opening a letter and having it kill them and delete several of their items.

## Why It's Good For The Game

While this seems like a cute addition to a sandbox, this feature is secretly self-defeating.
The ability to put instant gib devices in letters simply encourages people not to open _any_ letter. Encouraging people not to open letters encourages them not to buy this item.
Eventually you end up with a system people have been trained not to interact with, caused by an item which nobody buys because that item has trained people not to use the system it interacts with.

## Changelog

:cl:
balance: Removed the traitor kit which allows you to place arbitrary explosives inside of letters.
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
image

**Comment by mikederkan** [comment]
gonna b real the same case can be made for any object that can hold a mousetrap/prox sensor assembly grenade. also pizza bombs but they have a label

**Comment by cnleth** [comment]
I have never seen any people refuse to open mail in-game just because it can explode. Not on tg Terry, at least. Some people don't open mail because they don't care about the contents and that's it, but I've never seen anyone be enough of a tryhard to not open mail directly given to them just because it can explode. Maybe I'm just lucky with recipients, but I think the people claiming that they will no longer open any mail are just a small group of people on discord who are very vocal about their opinion and I don't think deleting a fun feature because of several people is right.

**Comment by Toastgoats** [comment]
Anecdotal but I still open letters and I'm sure the people that don't are mostly outliers. To prevent items from being deleted I'd suggest reducing the power of the explosive to something that can delimb as opposed to kill, like explosive kudzu tier.

I think not opening mail at all falls under players going out of their way to avoid risk which is a different issue entirely.

**Comment by Toastgoats** [comment]
> If it's that much of an issue why not just make it so that fake mail has a different label / desc like the pizza bomb does?

That's actually a pretty good idea.

**Comment by mc-oofert** [comment]
LAME AND IDED

**Comment by SomeoneYouProbablyKnow** [comment]
A) A system where no one buys this item leads to people opening letters and back to the item being viable. It's gonna have ups and down but it's not gonna disappear.
B) If instant gibs are the problem it's simple to add like a 1 second delay on the item.

**Comment by Fikou** [comment]
> B) If instant gibs are the problem it's simple to add like a 1 second delay on the item.

that's not how the item works lol

**Comment by Jacquerel** [comment]
> Anecdotal but I still open letters and I'm sure the people that don't are mostly outliers. To prevent items from being deleted I'd suggest reducing the power of the explosive to something that can delimb as opposed to kill, like explosive kudzu tier.

The reason we cannot adjust explosion intensity or delay is because the function of this item is that it allows you to place _any_ item inside a letter, and then activates it upon opening the letter as if you clicked it in your hand. It isn't a bespoke "mail bomb" which is adjustable, it's chem grenades or c4 or syndicate minibombs.

**Comment by mc-oofert** [comment]
> The reason we cannot adjust explosion intensity or delay is because the function of this item is that it allows you to place _any_ item inside a letter, and then activates it upon opening the letter as if you clicked it in your hand. It isn't a bespoke "mail bomb" which is adjustable, it's chem grenades or c4 or syndicate minibombs.

its literally 1 if check

**Comment by SimplySmiley123** [comment]
To be honest a looooot of people ignored mail completely even before mail bombs became a thing.
Really, unless you're a cargo tech (they apparently get a mosin in mail sometimes) or medical doctor (they can get graylien organs and do fun stuff with them) you ain't getting anything cool from it, maybe some credits if you're lucky.

**Comment by Pickle-Coding** [comment]
I don't think we should care about the minmaxers to be honest. They're not playing the game correctly to enjoy it properly. Unexpected explosions and crazy shit is what this game is known for. I think the people you mention forgot about what drawn them into the game in the first place.

**Comment by Dorsisdwarf** [comment]
I thought the stupid mailbomb item PR got denied specifically because it encourages people to just ignore the mail system...

**Comment by HWSensum** [comment]
Hello, creator of that feature is here. It is kinda sad that this feature offers lots of possibilities for contraband, sabotage, etc. Maybe we can save this feature by some tweaks? What about 100% defuse chance so people can safely check their mail?

**Comment by epochayur** [comment]
This absolutely reads like an IDED. I have never seen anyone refuse to open mail because of potential mailbombs. 
Just make it a descriptor like pizza.

**Comment by ExcessiveUseOfCobblestone** [comment]
The mail bomb meme is either too difficult to see through so people just end up not using mail or its too easy and no one ever actually uses it and it rots as an eye-roller when you pick a random item from the pool. 

If mail wasnt intended to be a cute little "gives cargo a fun job" aspect then id might be able to see the light, but it just taints what was a perfectly fine feature for a very miniscule amount of traitor gimmicks that are also being tainted by people who just use it to send no fun allowed bombs.

Paying 1tc for an item that offers no counterplay outside of powergaming will continue to be stinky, especially when the dial is upto the traitor who will obv crank it to high as possible. A dedicated mailbomb item that could be controlled for lethality would be slightly better in that regard.

**Comment by RedBaronFlyer** [comment]
> 



> To be honest a looooot of people ignored mail completely even before mail bombs became a thing.
> Really, unless you're a cargo tech (they apparently get a mosin in mail sometimes) or medical doctor (they can get graylien organs and do fun stuff with them) you ain't getting anything cool from it, maybe some credits if you're lucky.

The mail system actually has a pretty big pool of items to draw from, with the more quirks you have, you get a bigger pool of items. Plus, mail can give you two items sometimes now.

https://tgstation13.org/wiki/Quirks#List_of_Quirks

Granted, like 75% of the time it’s just credits. I have the introvert quirk and every single book I’ve gotten in the mail has been full on pornography. One time it was even WGW.

**Comment by SimplySmiley123** [comment]
> I don't think we should care about the minmaxers to be honest. They're not playing the game correctly to enjoy it properly. Unexpected explosions and crazy shit is what this game is known for. I think the people you mention forgot about what drawn them into the game in the first place.

Is it incorrect though? They are free to do whatever they want (as long as it's not supremely shitty, common sense applies still) and a lot of people see no point to mail from what I seen in-game. Again beyond medical doctors and cargo techs pretty much nobody cares about the stuff you can get from mail, even roleplayers.

**Comment by SimplySmiley123** [comment]
> > 
> 
> > To be honest a looooot of people ignored mail completely even before mail bombs became a thing.
> > Really, unless you're a cargo tech (they apparently get a mosin in mail sometimes) or medical doctor (they can get graylien organs and do fun stuff with them) you ain't getting anything cool from it, maybe some credits if you're lucky.
> 
> The mail system actually has a pretty big pool of items to draw from, with the more quirks you have, you get a bigger pool of items. Plus, mail can give you two items sometimes now.
> 
> https://tgstation13.org/wiki/Quirks#List_of_Quirks
> 
> Granted, like 75% of the time it’s just credits. I have the introvert quirk and every single book I’ve gotten in the mail has been full on pornography. One time it was even WGW.
> 
> I like the idea of mail bombs but at the same time I get why it’s mega stinky to get instantly atomized because someone put a department ruining bomb into an envelope.

Often feels like credits and a random remotely job related item are the only things you ever get, again, unless you are a med doctor or a cargo tech, one getting something unique they can toy around with and make someone roll their identity every once in a while while other just straight up gets a gun.

**Pull request closed without merging**
