### PR TITLE
New RCD Sprites, ammo counters, and actual yellow flashing lights!

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
add: Added ammo counters for RCDs
add: Added actual flashing yellow light for RCDs
imageadd: added new RCD sprites including inhands
imagedel: deleted old RCD iconstate, but not the inhands
/:cl:

dreamseeker_2018-03-10_14-44-57

This PR will replace regular RCD sprites with new ones that have ammo counters and proper flashing yellow lights. There is also a new recolored sprite for industrial RCDs

The color scheme of the regular sprite fits in rather seamlessly with the engineering theme.

dreamseeker_2018-03-10_14-41-00

The ARCD has been left untouched, along with the old RCD inhands. (the following are outdated screenshots)
dreamseeker_2018-03-09_19-15-18

arrceedeegif

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
👌

**Comment by Michiyamenotehifunana** [comment]
They _do_ seem to be a somewhat greener hue and brighter shade, now that you mention it.

**Comment by XDTM** [comment]
Beautiful, great job

**Comment by Spaceinaba** [comment]
10/10

**Comment by AlexTheSysop42** [comment]
Industrial RCD?

**Comment by cebutris** [comment]
Engineering ERT guys get industrial RCD's, if I'm not mistaken. They have a much higher ammo capacity

**Comment by ExcessiveUseOfCobblestone** [comment]
Really nice sprites.

**Comment by Michiyamenotehifunana** [comment]
Yeah, high alert ERT engineers get Industrial RCDs, with a max capacity of 500 units and the ability to deconstruct reinforced walls. They seem to be called combat RCDs in the code, oddly enough. The admin spawn version with infinite capacity is also based off the industrial RCDs.

**Comment by Jalleo** [comment]
Can you make the sprites a bit smaller and make a version for the other RCDs?

**Comment by epochayur** [comment]
i didn't know how much we needed these until I saw them
👍

**Comment by Bawhoppen** [comment]
I guess I didn't realise how large they were in the discord. They probably should be smaller.
Also I don't know how far @WJohn reviewed them, but he has to approve this PR anyways.

**Review by WJohn — DISMISSED** [review]
Yeah, I'm with bawhoppen on this one. They're kind of on the large side, taking up most of the entire tile. This also has the negative effect of causing quite a few large, undetailed spaces across your sprite, and it would benefit all around from being made smaller. I also think perhaps a bit of orange in the darker tones would be nice instead of just a muddy yellow (look into using hue ramps, they make everything look worlds better).

**Comment by XDTM** [comment]
A larger sprite size might be good to convey the fact they're normal-sized; at first i kept trying to pocket RCDs because they seemed tiny.

**Comment by WJohn** [comment]
I'm not saying make them as small as our current RCDs, because those are actually tiny, but somewhere in between would be nice.

**Comment by Bawhoppen** [comment]
@Michiyamenotehifunana By the way, your ingame images seem a little blurry in some spots, what is your icon scaling set to?

**Comment by Michiyamenotehifunana** [comment]
Ah, that'd be me running the game in 4K and with Point Sampling, I think.

**Comment by Michiyamenotehifunana** [comment]
Now with approximately 25% smaller sprites!

**Comment by MrDoomBringer** [comment]
@Michiyamenotehifunana pictures?

**Comment by KomradeSpectre** [comment]
Absolutely approve of this sprite upgrade. Good work!

**Comment by Michiyamenotehifunana** [comment]
@MrDoomBringer the first two images in the OP have the smaller sprite, with the last two having the old, oversized sprite.

Also, I'd like to take a moment to thank everyone for their feedback. I appreciate it.

**Comment by duncathan** [comment]
can you give RPDs a new sprite that fits the atmos colour scheme next pls

**Comment by Michiyamenotehifunana** [comment]
I'll see about that.

**Comment by Doppeltongue** [comment]
New size seems about perfect for a fairly bulky device. The old ones were way too small.

**Comment by Brimcon** [comment]
Inhands seem to be based on the older, bigger sprite with the black bits under the "Barrels"

**Pull request merged**
