### PR TITLE
Mining MODsuit Rework

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

makes dropkey deactivate device modules
fixes speed potion being fucky
fixes doubled up balloon alerts
makes some cell code better i think
makes the gps module open the gps tgui for you, instead of putting a gps in your hand
the loader suit can now hold mailbags

Reworks the mining modsuit.
The suit is no longer cold-proof (this can be mitigated by using module space for thermal regulators)
The suit fits less modules than standard suits, but cant burn in lava.
In suit storage it can carry ore bags, resonators and kinetic crushers.
It features a storage, gps, ore bag, drill, clamp and by default comes with a plasma core, being recharged with plasma ore rather than by power cell.
Features two new modules:
- Ash Accretion, it gathers dust from basalt (or snow) you walk on to create a layer of ash around the suit, acting as armor and a speed up that quickly drains when you walk on other terrain.
- Sphere Transform, turns you into a fast moving ball that can travel past lava, you cannot use your hands when in this form, but you can launch aoe mining bombs to attack or mine

Video for the modules: https://streamable.com/hjsmcj
Lastly, it features a new sprite!
image

## Why It's Good For The Game

now its something actually worth using and buying, while not being overpowered on station

## Changelog

:cl: Fikou, Imaginos, Azlan, Nerevar
qol: you can deactivate modsuit device modules with drop key
qol: the cargo modsuit can now hold mail bags
fix: fixes modsuit speed potion being fucky
qol: makes the gps module open the gps tgui instead of putting a gps in your hand
balance: Reworks the mining MODsuit, the full suit is bought from the mining vendor.
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
Samus mining suit

**Comment by Shadowflame909** [comment]
Fikou

This is awesome fikou

**Comment by CRITAWAKETS** [comment]
looks pretty useless in comparison to the absolutely powercrept state of lavaland armor, but also looks to be fun to use anyway.

**Comment by Stalkeros2** [comment]
Do hope it uses both plasma ores and plasma sheets.

**Comment by WhateverDimeIs** [comment]
> Do hope it uses both plasma ores and plasma sheets.

sadly, only ore

**Comment by Stalkeros2** [comment]
Also, I do feel like it's lacking any marks that'd denote the wearer as a miner, because, honestly, it currently looks like Stalker's SEVA-Exosuit mashup rather than something mining. Even the explorer suits have the purple stripes on both their shoulders and the hood, albeit it's almost invisible to the wearer's eye, and the best suit ever/mining hardsuit/old mining modsuit also had quite a lot of khaki-purple colors.

**Comment by drIcepop** [comment]
happy birthday!

**Comment by ATH1909** [comment]
happy birthday!

**Comment by CourageTheCat** [comment]
will the old version still be in as a MOD paint skin? I feel like it matches better with the other mining tools with the purple trim

**Comment by bluetshirtguy** [comment]
awesome stuff fikou!

**Comment by catrock31** [comment]
this makes me orgasm, though I would like paint option for the old sprite

**Comment by Fikou** [comment]
> this makes me orgasm, though I would like paint option for the old sprite

here you go ig

**Comment by OrionTheFox** [comment]
Why take away the cold protection? Does it still have enough to protect you on Ice?

**Comment by Fikou** [comment]
> Why take away the cold protection? 

i think its fun to make people need to spend complexity on it, with miner suit's decreased complexity maximum

> Does it still have enough to protect you on Ice?

yes

**Pull request merged**
