### PR TITLE
[CI Fix] The Demonic Frost-Miner will not attack corpses.

### LINKED ISSUE #79147: Multiple errors in flaky test monkey_business
Flaky tests were detected in [this test run](https://github.com/tgstation/tgstation/actions/runs/6598097689/attempts/1). This means that there was a failure that was cleared when the tests were simply restarted.
Failures:
```
monkey_business: [15:17:34] Runtime in life.dm,540: Cannot execute null.metabolize().
proc name: handle dead metabolization (/mob/living/carbon/proc/handle_dead_metabolization)
src: Cherette Lewis (/mob/living/carbon/human)
src.loc: null
call stack:
Cherette Lewis (/mob/living/carbon/human): handle dead metabolization(2, 28)
Cherette Lewis (/mob/living/carbon/human): Life(2, 28)
Cherette Lewis (/mob/living/carbon/human): Life(2, 28)
Mobs (/datum/controller/subsystem/mobs): fire(1)
Mobs (/datum/controller/subsystem/mobs): ignite(1)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop(2)
Master (/datum/controller/master): StartProcessing(0) at life.dm:540
monkey_business: [15:17:34] Runtime in life.dm,457: Cannot execute null.has reagent().
proc name: handle organs (/mob/living/carbon/proc/handle_organs)
src: Cherette Lewis (/mob/living/carbon/human)
src.loc: null
call stack:
Cherette Lewis (/mob/living/carbon/human): handle organs(2, 28)
Cherette Lewis (/mob/living/carbon/human): Life(2, 28)
Cherette Lewis (/mob/living/carbon/human): Life(2, 28)
Mobs (/datum/controller/subsystem/mobs): fire(1)
Mobs (/datum/controller/subsystem/mobs): ignite(1)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop(2)
Master (/datum/controller/master): StartProcessing(0) at life.dm:457
```

### PR DESCRIPTION
**Pull request by lizardqueenlexi**
## About The Pull Request

Fixes #79147.

Prevents the Demonic Frost-Miner from shooting at corpses by returning early from `OpenFire()`. Also adds the "gutted" status effect to the corpses in its arena so it won't try to gut them.
## Why It's Good For The Game

#78826 introduced an unfortunate bug by placing corpses in the Frost Miner's arena. There were a combination of three factors at play here: that the Miner attacks corpses, that it happens to use colossus bolts in its attacks, which dust corpses, and that some unfortunate quirk of life code causes runtimes if, as far as I can tell, a life tick goes off when a mob is at the wrong point in the dusting process. The time this process takes happened to perfectly coincide with the Monkey Business unit test (being the first test that takes a significant period of time), causing it to randomly fail.

So, this fixes a flaky test that has been a pain in the ass for the last five days, is the big thing.

Also, it can't possibly have been intended for the Miner to run around obliterating the aesthetic corpses in its arena within the first 15 seconds of any given round. Completely ruining the mood!

I'll point out that this particular boss may have been forgotten in #77731, which set out to make only the colossus still gib/dust you, but even were that not the case I think it would be a bit silly for the Miner to be busy shooting lifeless corpses when a player shows up to challenge it, rather than standing in its scary ritual circle.
## Changelog
:cl:
fix: The Demonic Frost-Miner will no longer run around destroying the corpses in its arena the moment the round begins.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
If you remove this behaviour, does it still gut corpses of people it has recently killed?
If not you may need a different strategy, like adding the "I have already mauled this" trait to the corpses in its arena.

**Comment by lizardqueenlexi** [comment]
With more testing I'm seeing some incredibly confusing behavior from the Frost Miner - namely, that megafauna seem to already ignore clientless mobs, _but_ the Miner will still aggro on the corpses that spawn in its arena. Why, I have no idea. It's particularly strange because it's not supposed to use its special attacks at all on mobs that it's eligible to devour, but it's simply not doing that and dusting them instead...

**Comment by lizardqueenlexi** [comment]
I still have no idea why it's doing that, but I made it just cancel `OpenFire()` if its target its a corpse, and I made the corpses in the arena pre-gutted so it ignores them. This has the intended effect without actually changing any notable behavior.

**Comment by GPeckman** [comment]
And the monkey business test is failing. How ironic.

**Comment by Jacquerel** [comment]
> And the monkey business test is failing. How ironic.

Yes unfortunately while we have a fix for the most common failure reason in PR (alongside three other less common ones) it isn't necessarily the _right_ fix yet 😅

**Pull request merged**
