### PR TITLE
[NO GBP] Some more code maintenance for reagents

### LINKED ISSUE #78890: Reaction in plumbing creates empty chems and gets in reaction loop
Complex plumbing factories breaks after some time, the more complex they are the faster they breaks. 
Sometimes there are 0 units of chem that can't be unloaded but reaction chamber tries to do that. Sometimes there are bugged reactions that keep reacting without any chems except in what they reacted into.
About week ago same layout factory worked perfectly fine without a single problem.

Round ID: [216387](https://scrubby.melonmesa.com/round/216387) and 216388

First factory:
  chemical synthesizers: welding fuel, carbon, hydrogen, chlorine, water, nitrogen, sulfuric acid, sodium, oxygen, aluminium, bromine, lithium, potassium.
  Reaction chambers: Oil, ammonia, phenol, seiver, libital, aiuri, salicylic acid, oxandrolone, salbutamol.
  press chamber with 30 units pill consists of 5units of each seiver, libital, aiuri, salicylic acid, oxandrolone, salbutamol.
(screenshot from second round because I forgot to make one in first but layout is same. Reaction chamber on the right just filters out chems for press chamber)
Main

Bugged after 2 or 3 cycles, reaction chamber plunging helped with 0 chems for a few cycles until it broke again
Some chemical synthesizers got chemicals above 5 which I also have never seen before.
After multiple tries to make it work by plunging it, unsecuring and wrenching back and rewriting chemical reactions I tried to make simplier factory just for libital and seiver - it worked for more cycles but bugged out in similar way
Seiver+libital

Tried to make my main pill factory on next map, got same problems with infinite reactions, chem synthesizers overflow and 0 chems.

Random clown from first round also have seen that there is something wrong with chemical reactions after I asked if I fucked something up or not(Clown didn't mention anything about plumbing though, just chemistry and phantom chemicals. I got this bug only in plumbing, basic chemistry didn't show anything unusual)

### LINKED ISSUE #78912: Code for syringes with multiple reagents is slightly broken
## Reproduction:

I became aware of this bug when someone said that triacid (an equal mixture of sulfuric, fluorosulfuric, and nitric acid) was doing far less damage than expected. Upon being injected, the whole mix should instantly inflict about 45 brute damage, and then burn and toxin damage over time. Upon testing, the mix dealt only about a third of the expected brute damage. I believe I have  figured out why.

This is part of the code that controls the transfer of reagents from syringes to humans:
https://github.com/tgstation/tgstation/blob/7bf2f5551269a618b20aa7312d695920dde03b41/code/modules/reagents/chemistry/holder.dm#L613
`r_to_send` is the list of reagents that are being exposed. In this case, a list of the 3 acid types, each with a value of 5, their volume. However, there's another relevant variable: `part`. This is passed as the volume modifier, so `expose_reagents` will multiply the volume of all the reagents by it.

`part` is defined up here:
https://github.com/tgstation/tgstation/blob/7bf2f5551269a618b20aa7312d695920dde03b41/code/modules/reagents/chemistry/holder.dm#L581
We have 3 reagents, so `part` is equal to 1/3. And that is the problem: Each reagent already has a volume of 5. Because `part` is passed as the volume modifier, the volume actually becomes 5/3, which results in only a third of the damage being dealt.

### LINKED ISSUE #78920: Barrels empty out equal amounts of reagents, rather than proportion to how much of each is in them.
## Round ID: [216472](https://scrubby.melonmesa.com/round/216472)

Barrels seem to empty out weirdly when you try to remove their contents with a beaker. Rather than removing reagents with the proper ratios based on how much of it is in the barrel, it spits out equal amounts of all reagents. Previously, if I made a wine, I would add multiple medicine reagents in small proportions to give it slight healing effects, but that's not feasible, as they come out in equal proportions.

image
image

## Reproduction:

ferment some plants in a barrel.
Add a small volume of another reagent
use a beaker on the barrel.

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request

1. Removes the `round_robin` approach of transferring reagents.  This was only used by chemical plumbing devices and it's logic was faulty. To understand let's take an example 

      Say we have a beaker containing the following reagents
      
      >  iron = 10
      >     water = 15
      >     ethanol = 20 
      
      If we use the `round robin` approach say to transfer 15 units of this total solution the end result would be
      
      >  iron = 10
      >    water = 5
      
      
      Ethanol would not be transferred because we already transferred 15 units before getting to it.
      
      This is wrong because we were able to "separate" reagents from the original solution during the transfer operation. Reagent separation usually requires specialized mechanisms such as the chemical splitter, chem master etc and it should not happen when we are just trying to transfer a solution from 1 pipe/beaker to another.
      
      In the future if coders rely on the `round_robin` mechanism of transferring reagents they could find missing reagents in the final end result and they would think it was something wrong in their logic without realizing this method of transferring reagents was flawed to begin with.
      
      The original author of plumbing wanted to use this method because they didn't want to deal with decimal values having 10 places but a quote from my last PR #78637
      
     > The number is then quantized i.e. we do round(amount, CHEMICAL_QUANTISATION_LEVEL) so we don't deal with numbers having 10 decimal places or something like that
      
      will ensure that won't happen. Also, it's fine if we don't get exact amount of each reagent when transferring and we end up with some incorrect math, there is no such performance criteria to be achieved, this is much better than having missing reagents altogether & less code to debug overall so it's a win.

      This also Fixes #78890. In the above mentioned PR 1 miscalculation was made in the round robin technique when computing amount of reagents to transfer
I'm not gonna specifically point out which since I'm removing it altogether but if the above issue re emerges then we'll see

2. Add's some more rounding operations when adding & removing reagent volumes just to be sure we properly enforce the 1st point. Droppers & beakers will round the amount transferred to 2 decimal places before displaying to chat for easy readability

3. Cleans up plumbing component & reaction chamber component code to better adjust to 
the new transfer mechanism. Also brings back proportional method of working with reagents not equal distribution which means this
- Fixes #78920
- Fixes #78912

5. Examining individual reagents up close will display their volumes up to 4 decimal places for accuracy

6. Improves the performance of `update_total()`, `clear_reagents()`  & `del_reagent()` procs

## Changelog
:cl:
code: removed round robin method of transferring reagents which would result in some missing reagents after transferring.
code: added some more rounding for reagent operations.
code: cleaned up some plumbing & reaction chamber code
code: improves the performance of `update_total()` , `clear_reagents()` & `del_reagent()` procs
fix: plumbing setups will no longer output 0 or more than maximum available volume of reagents.
fix: removing, copying, transfering reagents is now done proportionally and not equally again.
refactor: examining individual reagents up close will display their volumes up to 4 decimal places for accuracy.
qol: droppers & beakers round the amount of reagents transferred before displaying them to chat for easy readibility
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
There is no GBP for this but still make sure to add the fix & refactor label for anyone who is interested in this as i specified those tags in the changelog.

**Comment by rdragan** [comment]
Can you please fix `/datum/reagents/proc/remove_all` too? It's removing an equal amount of each reagent instead of removing a proportional amount as it's supposed to.

**Comment by SyncIt21** [comment]
> Can you please fix `/datum/reagents/proc/remove_all` too? It's removing an equal amount of each reagent instead of removing a proportional amount as it's supposed to.

It isn't documented anywhere that this is the expected behavior. As the proc suggests it's purpose is to remove n units of the entire solution and the only way to do that is to remove an equal amount from each reagent. But if you do it proportionally it will exceed the requested amount.
Unless any bugs come out of the current behavior there isn't any reason to change it

**Comment by GoldenAlpharex** [comment]
I need to point out that, currently, there's some issues with floating point errors, where reagents are reaching something like `49.999` in the machines and everything grinds to a stand-still in the factory. Shit just stops moving around, and then you see some `0 units of X` in some other machines.

No runtimes attached to those errors, that I could see at a quick glance, but yeah, it's been quite annoying, and it's since your previous PR.

**Comment by rdragan** [comment]
> > Can you please fix `/datum/reagents/proc/remove_all` too? It's removing an equal amount of each reagent instead of removing a proportional amount as it's supposed to.
> 
> It isn't documented anywhere that this is the expected behavior. As the proc suggests it's purpose is to remove n units of the entire solution and the only way to do that is to remove an equal amount from each reagent. But if you do it proportionally it will exceed the requested amount. Unless any bugs come out of the current behavior there isn't any reason to change it

I... 
Honestly I'm not even gonna bother to explain why this is supposed to work like that.

Here's your bug:
waterpills

**Comment by SyncIt21** [comment]
You right I'll revert it back.  I thought equal amount of stuff would be kind of be expected but yeah I'll put it back

**Comment by SyncIt21** [comment]
Alright proportional transferring is back. Now i remember why i did equal distribution method it's because we get rounding errors like this when taking reagents from a beaker via a dropper
Screenshot (318)
Now i just rounded the results before displaying it to chat so the average player will never know heh heh... i mean nothing we can do about it and it's not a big deal so whatever

>  reaching something like 49.999 in the machines and everything grinds to a stand-still in the factory

No worries proportional transfer fixes the job Yeah
Screenshot (319)

> 0 units of X in some other machines.

I have also addressed this by rounding the reagent volume's to 4 decimal places rather than 2 and displaying it as 0
https://github.com/tgstation/tgstation/blob/fa3ecddd7fdc677bf107dba6cffda7292ab5be51/code/game/atoms.dm#L677
This is useful only for detailed analysis as average players usually won't care about this but now you will know if something is off during examining

**Comment by MidoriWroth** [comment]
cant wait for this to merge 😭

**Comment by GoldenAlpharex** [comment]
> Alright proportional transferring is back. Now i remember why i did equal distribution method it's because we get rounding errors like this when taking reagents from a beaker via a dropper Screenshot (318) Now i just rounded the results before displaying it to chat so the average player will never know heh heh... i mean nothing we can do about it and it's not a big deal so whatever
> 
> > reaching something like 49.999 in the machines and everything grinds to a stand-still in the factory
> 
> No worries proportional transfer fixes the job Yeah Screenshot (319)
> 
> > 0 units of X in some other machines.
> 
> I have also addressed this by rounding the reagent volume's to 4 decimal places rather than 2 which would displaying it as 0
> 
> https://github.com/tgstation/tgstation/blob/fa3ecddd7fdc677bf107dba6cffda7292ab5be51/code/game/atoms.dm#L677
> 
> 
> This is useful only for detailed analysis as average players usually won't care about this but now you will know if something is off

When it's X.9999, can't you just force it to round up to X+1 instead, to avoid those rounding errors?

**Comment by SyncIt21** [comment]
> When it's X.9999, can't you just force it to round up to X+1 instead, to avoid those rounding errors?

That's what i did. upon normally examining anything it the result will be rounded up and display it upto 2 decimal places so 0.9999 will become 1. Only when you are a ghost and you want a thorough examination of each individual reagent do i round it to 4 decimal places instead mostly for debugging purposes.

You don't have to worry about values like X.9999 occurring anymore because the proportional transfer logic will ensure it won't happen. Off course you can test locally to confirm this

**Comment by SyncIt21** [comment]
> grinds to a stand-still in the factory

@GoldenAlpharex I have a question regarding the chem factory and your [comment](https://github.com/tgstation/tgstation/pull/78884#issuecomment-1756470612) . Now with this PR the plumbing factory outputs clean 50 units, and you don't see any more 0 units of chems, but the factory comes to a standstill even after that i.e. Once the final output gate reaches full 50 units it does not draw any more reagents from the rest of the factory so everything halts. Even after reverting my previous PR, I observed the same behaviour.

This means it's expected right? That's why you have to use a plunger occasionally to clear the reagents & restart the machines or am i missing something here?

**Comment by DoomAngelBlade** [comment]
> This means it's expected right? That's why you have to use a plunger occasionally to clear the reagents & restart the machines or am i missing something here?

If that is expected behaviour of all the machines(and in factory you can have like 20 of them) - then there's no reason for it to exist except for cases when you are doing one or two simple reagents.

Plumber is mostly used for one case - you FUCKED UP.
Cases like - connecting reagents before setting up recipe
Connecting storage or something that has any storage without proper filtration
Inputting a wrong reagent in chamber/filter
etc.

Right now my factory outputs a med two times before I have to seek what machine clogged up because it has 0 and doesn't have anywhere to output.

By the way. There's a way to bypass all of this but this is cancer. You have to add a reaction chamber with all chemicals that are guaranteed every tick in your system AND THEN add a separate reaction chamber for each chemical that MIGHT be in your system(e.g - oil, phenol) - this way there is almost always something that will consume those 0.00001 something and eventually it will unclog.

**Pull request merged**
