### PR TITLE
Removes telescience entirely

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
del: Telescience is no more.
/:cl:
Goof gave up a while ago, so let's finish the job.

### CODE REVIEW

**Comment by obscolene** [comment]
rnd needs those teleporter boards you sick fuck

**Comment by kevinz000** [comment]
:'(

**Comment by Incoming5643** [comment]
Fun stuff you don't get at round start that people will actually bother to make is a preciously small category already. It doesn't need to get any smaller.

**Comment by ChangelingRain** [comment]
Including telesci in the category of fun stuff is stretching it.

**Comment by vcordie** [comment]
telesci is like enchanting in skyrim. boring, and overpowered as fuck.

**Comment by ninjanomnom** [comment]
I'd be willing to pick up where @Iamgoofball left off https://github.com/tgstation/tgstation/pull/25925#issuecomment-292266936

Though I'd not want to do the same changes, instead:
Can only move mobs
Initiating a teleport to or from anywhere takes time
A glowing effect at the destination and source, possibly with a noise

Meaning it's no longer easy to just go and steal everything from everywhere and anyone nearby will see/hear it happening.

**Comment by SgtxRootbeer** [comment]
is this all you do, LZI? just remove stuff from the codebase?
sometimes we need that for later.

**Comment by bgobandit** [comment]
the lziard is on a rampage, someone put it back in teh cage

**Comment by Iamgoofball** [comment]
:+1:

**Comment by PKPenguin321** [comment]
What's the reasoning this time

**Comment by Repukan** [comment]
Good.

**Comment by KorPhaeron** [comment]
Are you just trying to make as many people as possible mad there is no reason to do this now when its already inaccessible

**Comment by optimumtact** [comment]
Kor please, I said quite clearly it would be removed if goof didn't do his overhaul

**Comment by SgtxRootbeer** [comment]
it hasn't been a month since the end of the feature feeze
@optimumtact 
YOU DIDN'T HONOR THE DEAL!!

**Comment by vcordie** [comment]
yeah but goof said he's not going to do the overhaul anymore.

**Comment by SgtxRootbeer** [comment]
then i guess its time for me to fail at trying to do my own overhaul

**Comment by vcordie** [comment]
you've got 2 days. good luck.

**Comment by RandomMarine** [comment]
A revamped telesci can always be added later regardless of whether this is merged or not.

**Comment by Repukan** [comment]
Just kill it and let it die

**Comment by Bawhoppen** [comment]
Why do we have to remove it? Sometimes it's nice to have stuff left in the fucking game that isn't part of the standard 30-minute round antag grind.

**Comment by uraniummeltdown** [comment]
bring telesci back

**Comment by FantasticFwoosh** [comment]
Time to make the upstreams mad.

**Comment by xxalpha** [comment]
It is a cool feature, but in hindsight players shouldn't have this kind of power, and it's made worse by the convenience of it. If you want telesci just make it from scratch to be a better feature.

**Comment by BeeSting12** [comment]
>all the science mains downvoting

**Comment by kevinz000** [comment]
that's not all of the science mains you doofus

**Comment by Iamgoofball** [comment]
yeah i dont have the time nor do i care enough to actually do this

**Comment by MrPerson** [comment]
I hate to say I told you so but

who am I kidding, I love saying I told you so.

**Comment by vcordie** [comment]
>all the science mains downvoting
>the two biggest powergaming science mains are the strongest supporters of removing it
?????????

**Pull request merged**
