### PR TITLE
Puts a Player minimum on the Ebow

### PR DESCRIPTION
**Pull request by Timonkeyn**
:cl:
balance: added a 25 minimum player count to the ebow
/:cl:

[why]: because ive seen some peeps complain about low pop murderboning involving this bad boi some time ago

### CODE REVIEW

**Comment by ike709** [comment]
i ded

**Comment by Timonkeyn** [comment]
pls restart

**Comment by lolman360** [comment]
based pr

**Comment by kevinz000** [comment]
i ded

**Comment by Tlaltecuhtli** [comment]
i ded

**Comment by Timonkeyn** [comment]
PLS RESTART ALREADY

**Comment by 4dplanner** [comment]
@Timonkeyn you haven't actually pushed another commit

**Comment by Poojawa** [comment]
why is it even possible to population-lock items.

what even is the logic behind it besides hugboxing

**Comment by Timonkeyn** [comment]
@4dplanner wdym?

**Comment by FrostyFridge** [comment]
i ded

**Comment by Therapist1** [comment]
i ded

**Comment by PKPenguin321** [comment]
Ebow + emp light = the easiest lowpop murderbone setup of all time

**Pull request closed without merging**
