### PR TITLE
Animate pointing to move from the pointer to the pointed

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
point

## Why It's Good For The Game
This not only just looks better than an arrow instantly appearing, but it also makes it more obvious when something is pointed to. Occasionally I will ask where something is, someone will point, and I will just look around my screen to find it. With this, ideally it'll catch your eye faster.

## Changelog
:cl:
add: Pointing will now animate starting from you to the object you pointed at.
/:cl:

### CODE REVIEW

**Comment by KathyRyals** [comment]
Amazing, I love the look of it. It makes sense too.

**Comment by wesoda25** [comment]
It’d be epic if the arrows faced the direction you point in

**Comment by Jack7D1** [comment]
Mof does the point

**Comment by TerraGS** [comment]
Next we create a pointer gun that fires arrows that embed in people

**Pull request merged**
