### PR TITLE
changes mech sprites!

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

removes old mech icons, adds new ones!
the mech icons in question can be viewed via icon diffs bot, I don't have a full scene image of them, yet.
note that mech construction sprites are not done professionally/have been manually edited by me, and not the actual spriter, so results may vary in quality.
Credit to INFRARED_BARON for 100% of the base sprites.

## Why It's Good For The Game

Much nicer, chonkier mech icons.
Adds polar hide specific sprites, but lacks the code required to use these, sadly.

image

## Changelog

:cl: by INFRARED_BARON
image: Changes icons of: Gygax, d-gygax, durand, ripley variants, firefighter statue, phazon & odysseus. Adds new icons for polar hide item.
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
Where are the in-game screenshots? Video also is needed for this specific case

**Comment by zxaber** [comment]
Based and mechpilled.

- Looks like a few sprites didn't get updated correctly. Phazon's animation, among others.
- Paddy's siren light overlay needs to be updated to match where the lights are now (and possibly match the new style). I didn't see it in the changes.
- I can't tell from the icondiff, but Paddy's cockpit is supposed to be open, like the Ripley MK-I.
- You re-added the Firefighter's sprite, which is based but Fikou might yell at you.

**Comment by mc-oofert** [comment]
image

**Comment by Exester509** [comment]
Yeah, slim ripley really doesn't feel right

**Comment by EEASAS** [comment]
broken durand sprites are... broken they show up as a rotating gygax

**Comment by EEASAS** [comment]
actually now that i see, a lot of sprites in mecha.dmi are broken

**Comment by Admiral-Gigaton** [comment]
as others have said, slim ripley does look goofy, but if thats the case...

> Yeah, slim ripley really doesn't feel right

>best pic i could find from checks because the rest were having a stroke
> 
> but by god does slim ripley and bess not sit well with me

i present to you... the TGMC Ripley sprite

(side profiles unavailable, not online and I had to scavenge it from their wiki)

image

**Comment by githubuser4141** [comment]
> image best pic i could find from checks because the rest were having a stroke
> 
> but by god does slim ripley and bess not sit well with me

This iconview is bugged for some reason, some of those mechs are probably showing the construction sprites and therefore look a bit bad

**Comment by githubuser4141** [comment]
> as others have said, slim ripley does look goofy, but if thats the case...
> 
> > Yeah, slim ripley really doesn't feel right
> 
> > best pic i could find from checks because the rest were having a stroke
> > but by god does slim ripley and bess not sit well with me
> 
> i present to you... the TGMC Ripley sprite
> 
> (side profiles unavailable, not online and I had to scavenge it from their wiki)
> 
> image

So? I've seen the sprite already, imho it it's too demanding to look at, and if you guys don't like slimripley why didn't you SAY SO on discord when sprites were posted? Wallmations one of the spritetainers that approved
 should've showed you, or you should've seen it? And oranges was the one who requested it to be styled after the Aliens power loader which isn't a square brick.

**Comment by EricZilla** [comment]
You guys know the ripley is meant to be the loader from alien right?
5a74db7952fadc6a85773e4a59947c27

**Comment by Jackal-boop** [comment]
Wonderful. Now we just nerd to add mechs from Lancer.

**Comment by githubuser4141** [comment]
Added a screenshot, and support for polar hide attachment.

**Comment by DaCoolBoss** [comment]
The non Ripley ones are good, like those a lot. I don't mind the 'thin ripley' but the arms seem a lil off to me, colours on the claws are too high-contrast I think. Paddy's police lights look weird there and I'd prefer them on top of cage. Apart from those they're great.

**Comment by dawsonkeyes** [comment]
Where are the Mauler, Marauder, Seraph, and Reticence? The presence of the Death Ripley means surely those four should be resprited too, especially given the Mauler is an actively used nukeops mech like the Dark Gygax

**Comment by Sadboysuss** [comment]
> Where are the Mauler, Marauder, Seraph, and Reticence? The presence of the Death Ripley means surely those four should be resprited too, especially given the Mauler is an actively used nukeops mech like the Dark Gygax

Probably out of scope, it's already a lot of effort in this pr

**Comment by Admiral-Gigaton** [comment]
> Where are the Mauler, Marauder, Seraph, and Reticence? The presence of the Death Ripley means surely those four should be resprited too, especially given the Mauler is an actively used nukeops mech like the Dark Gygax

not death ripley, thats paddy, the security ripley mech

**Comment by Iamgoofball** [comment]
People can cope, the authentic loader ripley is A++ and I love it

**Comment by githubuser4141** [comment]
> People can cope, the authentic loader ripley is A++ and I love it

Cool, sadly I can't get the armor plate stuff to work on local so I'm assuming it's broken, will just try to ship the sprite changes without code changes.

**Review by Imaginos16 — APPROVED** [review]
Had to double-check that IDB was just having a goof and it wasn't an error with the DMI.

Other than that, excellent work! Baron's always been consistently amazing with his sprites and I'm happy to see his work here.

**Comment by githubuser4141** [comment]
I wonder if it's goobing out because it's expecting frames where there aren't? The new Gygax wreck sprites aren't animated for instance.

**Comment by KeRSedChaplain** [comment]
my one comment is that I think the durand's visor should be a bit more visible/brighter green, since I always imagined it to be either a glass visor or a singular version of the lights the gygax has

**Comment by Livrah** [comment]
I think I know why there was no comparison to the old sprites here.

**Comment by Nidvex250** [comment]
> I think I know why there was no comparison to the old sprites here.

probably because they done it already on their discord and we're just downstreamers looking up not bothering to check their discord, lol
It's sprite rework so it'll always be a mixed bag of opinions.
The Ripley mech looking like, well, the exosuit loader that Ripley piloted to beat up a Xeno Queen is A+ though.

**Comment by LSommers** [comment]
The... shading? The way the colors are laid out on the sprites is odd, especially compared to other stuff from TG (and no I'm not soulposting, look at current crates/lockers as an example). It's not quite as obvious in the screenshots here, but encountering them ingame is jarring to say the least. There's large swathes of color that just seem to simplified and indistinct- which is a shame because honestly I can get behind powersuit-style RIPLEY, except that it's the worst and most easily spotted offender of this particular visual issue.

The claws. Something about them just looks off, even compared just to the rest of the new mech sprites. Maybe making the claws either a single, solid color, or using a more gradual transition from the brighter to darker metal sections?

**Pull request merged**
