### PR TITLE
 Hardcore random characters may have random phobias.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Hardcore random characters can now have a random phobia.

## Why It's Good For The Game
Phobias are a pretty encumbering maluses and have little reason to be a neutral quirk, buuuuuuuut because the type can be chosen vin the preferences, people would always pick the least crippling one anyway... Though they still make good candidates for hardcore randoms since they really shouldn't be picky about what quirks they get.

## Changelog
:cl:
add: Hardcore random characters may have random phobias.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
dunno why people are disliking this when it can blind and stun you, especially if its something really common

**Comment by Fikou** [comment]
> dunno why people are disliking this when it can blind and stun you, especially if its something really common

u pick the phobia you can get 3 points for looking at something that you just wont see 9/10 rounds

**Comment by Timberpoes** [comment]
See https://github.com/tgstation/tgstation/pull/60568#issuecomment-890134366

Again, a very strong no.

You choose your own phobia. Concerns from the original PR (#46524) are things I still believe hold true today. Pick a nice, low-impact phobia and you're good to go. It's not something I want to encourage players taking - If they want to RP a specific phobia, this quirk helps provide some code-level !!fun!! to it.

**Comment by tralezab** [comment]
maybe 1 is better than 3 for point value

**Comment by Serxule** [comment]
you choose your own phobia? it used to be random i thought

**Comment by RaveRadbury** [comment]
> you choose your own phobia? it used to be random i thought

Hasn't been random for like over a year now

**Comment by Serxule** [comment]
doesnt really make sense to choose your own, especially since it doesnt give you anything in return

**Comment by tralezab** [comment]
Honestly I think this has a lot more roleplay value so i'd keep it as a neutral quirk.

Though that being said! A random version would be awesome for hardcore randoms

**Comment by Ghommie** [comment]
Umh, I agree. The ability to choose the phobia type, while providing the same value, really ruins it as a negative quirk.
I'll keep the hardcore random bit though.

**Comment by Time-Green** [comment]
Can’t wait to play hardcore random and roll this for only 10 HC random points and spent my round either completely unaffected or completely fucked because I got a phobia for lizards/felinids/moths/security/medical at which point I might aswell just stab my eyes out

**Comment by Serxule** [comment]
> Can’t wait to play hardcore random and roll this for only 10 HC random points and spent my round either completely unaffected or completely fucked because I got a phobia for lizards/felinids/moths/security/medical at which point I might aswell just stab my eyes out

Wow it's almost like... Its supposed to be **hardcore**

**Comment by Serxule** [comment]
> > Can’t wait to play hardcore random and roll this for only 10 HC random points and spent my round either completely unaffected or completely fucked because I got a phobia for lizards/felinids/moths/security/medical at which point I might aswell just stab my eyes out
> 
> Wow it's almost like... Its _supposed_ to be **hardcore**

**Comment by Time-Green** [comment]
Hardcore != cancer

This’ll just force you to self-isolate. Have you ever played with a phobia like lizard phobia? It’s just random stuns, extreme mood downs and blindness whenever I dare to walk the halls. At least social anxiety only affects speech

Interaction restricting quirks are not fun to play. Deafness and social anxiety are is my least favorite quirks to roll, because it just cripples my attempts to interact with others. Blindness, junkie and bad back at least have redeeming qualities in that they make fun RP opportunities (and some other stuff)

I have 4k+ points in hardcore random, there’s a difference between hard and tedious

**Comment by Ghommie** [comment]
I'll take your word on it. You played the mode more than all of us.

**Pull request closed without merging**
