### PR TITLE
rot and miasma removal

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
This PR removes the rot component from remains of carbon life and the miasma gas

## Why It's Good For The Game
The rot component is causing performances issues caused by the recurring activation of the turfs. Best explained here
dasdasd
Miasma is going too because without the rot component there won't be a meaningful way to obtain it if lavaland doesn't have it and also because in my atmos rework it doesn't have a place since this gas doesn't have any interactions with the atmos reactions and systems. 
If anyone will find a better way to fix this issue i'll close the PR.

## Changelog
:cl:
del: Rot Component
del: Miasma Gas
/:cl:

### CODE REVIEW

**Comment by Winterous** [comment]
Could you make it so that decaying corpses stink up the zone they're in? Or even just have an aura of stink around them? Surely that would be a far less demanding thing.

**Comment by brotherbeyondd** [comment]
I'll miss having to ask the AI to put the kitchen air alarm onto contaminated...

**Comment by Jared-Fogle** [comment]
look gary there i am

**Comment by LemonInTheDark** [comment]
If I can't get miasma to behave we're gonna go with this

**Comment by ATH1909** [comment]
An alternative solution could be keeping the miasma in the game, but removing corpse rotting, making lavaland and corpse flowers the only ways to obtain miasma.

**Comment by TheVekter** [comment]
If you're going to remove this, we need to add back some kind of negative modifier for leaving corpses around.

**Comment by wesoda25** [comment]
> If you're going to remove this, we need to add back some kind of negative modifier for leaving corpses around.

Rimworld here we come

**Comment by GuillaumePrata** [comment]
What about a limit of Miasma each corpses produces? I have no idea how demanding it would be to calculate it but it looks better than full removal, at least I like the interactions Miasma has in a round.
1 monkey corpse making miasma forever is kinda silly in itself, they would decompose fully after a while.

**Comment by LemonInTheDark** [comment]
The issue is the generation in the first place. A decay rate might help, but I'm not sure about it

**Comment by Jared-Fogle** [comment]
To those giving thumbs down emojis, please let me know why miasma is more important than helping performance on atmospherics (regularly our laggiest subsystem).

**Comment by LemonInTheDark** [comment]
To be totally clear, it's not a massive help, but it will cut down on active turf buildup over a round. And if 50 turfs might be the difference between atmos staying on top of things and not, I'm fine with that.

**Comment by kriskog** [comment]
Why remove miasma then, and not just the rot? There are other sources of miasma, and the gas itself has some uses and interactions.

**Comment by kassori** [comment]
optimize game by removing features make good game?

**Comment by Jared-Fogle** [comment]
@kassori https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md

**Comment by LemonInTheDark** [comment]
> 
> 
> Why remove miasma then, and not just the rot? There are other sources of miasma, and the gas itself has some uses and interactions.

Do you think corpse flowers and lavaland are worth it? I'm ambivalent to them personally, I just want the rot component to stop shitting on my lawn

**Comment by Ghilker** [comment]
I always wanted to remove miasma since it really has no atmos interests, the only use there is with this gas is cargo cashing in thousands of points without much effort

**Comment by Jared-Fogle** [comment]
Miasma is slightly interesting for medical. Without miasma, you know the second you start sneezing that it's going to be terrible and you should get to curing it immediately (or get to yelling at the viro about learning how to neuter). With miasma, people accept the occasional sneezing fit, and doctors need to make a choice about whether or not to care about vaccines or not.

With all this said, it's not interesting enough for me to want to keep with performance problems. It's just why I mentioned the area var thing in the first place.

**Comment by LemonInTheDark** [comment]
Could we tie corpse infection to crossing a tile with one, ect? I agree with the idea behind the feature, but again, the amount of active turfs it makes bothers me. I'll try tweaking it in a testmerge and see how things go.

**Comment by Jared-Fogle** [comment]
That sounds fine to me, we can bikeshed specifics based on whatever implementation you go for.

**Comment by AutisticFroggy** [comment]
This was removed on yogs and can confirm it was great for performance, and people didn't really care or notice any disease-related difference. Slap in a disease mechanic for corpse crossing or whatever and this will be golden.

**Comment by kriskog** [comment]
Miasma is a fun gas to fuck around with, and it has antag applications. Its worth fuck all after the economy changes, so thats not a very good argument. Gas doesnt have to be an atmos job related only thing.

**Comment by Krysonism** [comment]
This is like one of the few gases people who do not play atmos tech get to interact with.

**Comment by Timberpoes** [comment]
Big buff to genetics. Speedmerge it.

**Comment by FloranOtten** [comment]
I'll miss cheap gas mining

**Comment by Ghilker** [comment]
I'm sorry but i'm not going back on this unless there is a PR fix on rot and miasma rework

**Comment by GuillaumePrata** [comment]
Testing how this changes would do performance wise is way above what I can possibly do now so I will just give a shitty suggestion here...
After X minutes a corpse produces a small amount of Miasma at room temperature over 30 seconds and stops so the room won't keep updating forever.
Make breathing a small amount of Miasma more dangerous and add it to the the scrubbers at round start like CO2, I assume CO2 is there for the same reason, stop atmos from being active forever.
This should stop the issue of a room being active forever, but a corpse in maintenance can still be a dangerous thing for you to find if you don't have internals.

**Comment by LemonInTheDark** [comment]
Adding to scrubbers would actually make things worse, but the rest of that idea is good. 

Whether the atmos subsystem dies or not depends on if it can keep pace with the amount of diffs players create. Because players unfortunately do not run on a subsystem, as soon as it dies it's dead for good. It has a very hard time coming back from a massive slowdown over a long period of time. So lowering the amount of redundant diffs processing at once helps the atmos system run better in the worst case scenario. This all relies on how fast I can make atmos process in the first place, so the pr really isn't fit for review yet as we are missing important details.

**Comment by LemonInTheDark** [comment]
Talked about it with moth and ghil, closing this for now until I can figure out how bad it really is.

**Comment by Doosteroni** [comment]
bRuH mOmEnT

**Pull request closed without merging**
