### PR TITLE
Buffs the voodoo doll

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

This item is underused and could use a buff to make mainstream players appreciate it.

## Why It's Good For The Game

There's a lot of negative talk about this feature, and I feel that we can improve it. Let's try buffing it and seeing if it connects with audiences during a test screening.

## Changelog
:cl:
balance: Buffed the voodoo doll.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
advanced logic, goof, I'm sure someday I might understand it.

**Comment by TheBonded** [comment]
What parts did you buff?

**Comment by rdragan** [comment]
> What parts did you buff?

The parts that needed buffing

**Comment by TheBonded** [comment]
> > What parts did you buff?
> 
> The parts that needed buffing

Can't argue with that, I guess

**Pull request closed without merging**
