### PR TITLE
NERF TOURETTES

### PR DESCRIPTION
**Pull request by Mothblocks**
:cl:
balance: Tourettes will now stun you less often and for less time.
/:cl:

AAAAAHHHH THIS IS A GRUDGE PR!!!! WHY SO FUCKING OFTEN IM STUNNED FOR 20 FUCKING SECONDS IF I HAVE TOURETTES!!!!!!! I LOST MY TRAITOR ROUND I'M SO MAD!!!!!!!

### CODE REVIEW

**Comment by chesse20** [comment]
Smack this update in please

**Comment by iskyp** [comment]
~~i ded~~

**Comment by Jared-Fogle** [comment]
@iskyp half i ded half its FUCKING STUPID

**Comment by PKPenguin321** [comment]
Freeze

**Comment by Jared-Fogle** [comment]
@PKPenguin321 not sure what this means but this isnt a feature its a balance whatever

**Comment by iskyp** [comment]
> **What is not allowed:**
> Any kind of feature
> Any kind of tweak/balance change
> Map edits with the intent of modifying topology
> Feature removals
> Reverts that don't fix immediate issues

**Comment by Jared-Fogle** [comment]
so gay

leave this up then if you can until the freeze is over

**Comment by iskyp** [comment]
it's a two line change just close this do it after the freeze

**Comment by Jared-Fogle** [comment]
whens the freeze end

**Comment by iskyp** [comment]
https://github.com/tgstation/tgstation/pull/36569

**Comment by Jared-Fogle** [comment]
its back and im still mad

**Comment by Cyberboss** [comment]
Freez

**Comment by Jared-Fogle** [comment]
i saw the changelog on sybil and thought it was over, whoops

**Pull request closed without merging**
