### PR TITLE
Reverts PR #46905

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR reverts PR #46905 which made it so that biogenerators could not dispense reagent containers, along with not being able to dispense empty bottles.

## Why It's Good For The Game

#46905 was a nerf to botany that was completely unnessesary, and also removed some interdepartmental cooperation (Which is what we want in the codebase) by making it so that botany could not hand out their super special 50u empty bottles with 1u and 2u dispensing, meaning that aside from omnizine and earthsblood, botany has nothing to give to chemistry in exchange for all the chemicals it often requests. Also it can give the omnizine and earthsblood by itself.

## Changelog
:cl:
balance: Reverts PR #46905, now botany can produce reagent containers from the bio-generator once more.
/:cl:

### CODE REVIEW

**Comment by CatDerpington** [comment]
If anything botany needs to be nerfed further.

**Comment by ishitbyabullet** [comment]
I hate this PR title.

**Comment by CatDerpington** [comment]
> 
> 
> I hate this PR title.

Boomers. Gonna Boom.

**Comment by FancyCyclops** [comment]
Ok Alt.

**Comment by wesoda25** [comment]
more verified than an athath PR

**Comment by CRITAWAKETS** [comment]
So what was the reason for closing the PR?

**Comment by cacogen** [comment]
the pr you're reverting sucked, oranges hates botany for growing oranges and please learn how to squash your commits/not suck at Git it's the easiest part of coding

**Comment by Krysonism** [comment]
This was a good PR and it was probably not closed for any sensible reason.

**Pull request closed without merging**
