### PR TITLE
Adds new reagent container sprites!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin, with no bells and whistles!

This Pull Request ports the Hypospray, Combat Autoinjector, Pestle, Mortar and Dropper sprites from the Shiptest codebase (as seen in PR: [Resprites and Beaker (and Bottle) lids #31](https://github.com/shiptest-ss13/Shiptest/pull/31)

It also adds a pill bottle sprite made by yours truly and @Krysonism long ago!

Image:
image

## Why It's Good For The Game
mmmmmmyes pretty sprites yes please

## Changelog
:cl: PositiveEntropy, Kryson, TetraZeta
imageadd: Ports new Hypospray, Combat Autoinjector, Pestle, Mortar and Dropper sprites from Shiptest!
imageadd: Adds a new sprite for pill bottles!
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
that commit history lmao

**Comment by SmArtKar** [comment]
Sprites are nice, but have ya heard about _**feature freeze**_?

**Comment by Imaginos16** [comment]
> Sprites are nice, but have ya heard about _**feature freeze**_?

As long as you're not making a PR that has the label of balance/rebalance or Mechanics, its a valid thing to do. Meaning, respriting old sprites is 100% fine and not a violation of the feature freeze.

**Comment by maxymax13** [comment]
> 
> 
> Sprites are nice, but have ya heard about _**feature freeze**_?

yeah what about it

**Review by Twaticus — APPROVED** [review]

**Comment by Fikou** [comment]
the pestle seems impossible to click on

**Comment by PetMudstone** [comment]
> 
> 
> the pestle seems impossible to click on

The new pestle is the same size.
MortPestDemo

Regardless if it is still too small to click on it would be possible to add alpha pixels to make clicking on it easier, no?

**Comment by bluetshirtguy** [comment]
please make sure you can easily tell the different amounts of reagents in the containers by eyesight

**Pull request merged**
