### PR TITLE
Fixes Ministation Chef issues

### LINKED ISSUE #14373: Ministation Chef doesn't have bar/chef access.
Ministation chef can't move from his starting room or even get back in because his access is wrong.

### PR DESCRIPTION
**Pull request by swankcookie**
Chef was uninitialized. Problems arose.

Fixes #14373

### CODE REVIEW

**Comment by Jordie0608** [comment]
Ministation isn't meant to have a chef according to
https://github.com/tgstation/-tg-station/blob/master/_maps/ministation.dm#L23

**Comment by swankcookie** [comment]
Huh. I havnt actually played on mini in a while, i was just going off the issue ticket.

**Comment by KazeEspada** [comment]
Well, then the issue is wrong. It should more be: Chef spawns on Ministation.

**Comment by swankcookie** [comment]
@KazeEspada  It's your issue! change it!

**Pull request closed without merging**
