### PR TITLE
Prevents holy melons from defending against magic

### PR DESCRIPTION
**Pull request by 4dplanner**
:cl:
balance: holy melons are no longer anti-magic
/:cl:

Antimagic is a ridiculously strong ability to be able to mass-produce as easily as botany can mass-produce holymelons.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
its the only purpose of them though, a nerf in like any other way like size would be better.

**Comment by Nickkoranda** [comment]
Make it based off potency if you want to nerf it. Wizard and culties have plenty of other ways to use non-magic to murderbone.

**Comment by 4dplanner** [comment]
They also produce holy water, which is useful for making strange reagent without a chaplain. Otherwise, if they're still totally useless other than being ridiculously powerful against certain antags they should be totally removed.

**Comment by 4dplanner** [comment]
Holy water production is also useful in the rare cult round without a chaplain

**Comment by kriskog** [comment]
This has been discussed at length on ooc/dchat, and one suggestion that keeps coming up is to make them limited use as opposed to the null rod that is permanent. IE, holy melon blocks one spell before disintegrating. Maybe based on potency? There are options to just a straight removal of the anti-magic properties.

**Comment by Therapist1** [comment]
What kriskog said makes a lot of sense, a limited use magic shield. Also, 4d, put some space between these st PRs, man.

**Comment by kriskog** [comment]
Another alternative is a percentage based chance to block.

**Comment by Vidiveni** [comment]
Increase their size so you can't keep one in your pocket. I don't think the pocket protection was intentional, since the PR that added the antimagic to them mainly spoke of holding holymelons in your hand. 

Also making them splat when used is a good suggestion.

**Comment by Kawaii-Big-Boss** [comment]
The real question is, why was this added to begin with? Was it really necessary to nerf Wizard by making some items outright negate his spells instead of just, I dunno, making spammy defensive spells that make killing the wiz a chore to begin with less powerful, or having some form of requirement/counterplay? Or not having lichdom in the game?

Potency is easy to break so I wouldn't have the melon use a set number of hits before it splats. Having the melon be one-use makes more sense, with the block chance being based off of the potency. So what kriskog said, basically.
I still don't know why this is a feature that's in the game, but okay.

**Comment by tralezab** [comment]
using the term "prevents x" to describe your balance nerf pr is such a hilariously deceitful coder thing to do

but if you are really gonna do this, #41649 is an issue you can close with this pr, whether this gets merged or not. you should add it to the op

**Comment by XDTM** [comment]
My solution would be to make them not protect inside storage, only inhand.
If you go for the one-time only protection, you should probably add an argument to the antimagic signal to check if the spell is significant enough to consume a charge, or you'll get stuff like a clockcult's belligerent blowing up a melon per second on everyone around the caster.

**Comment by Steelpoint** [comment]
I've only ever seen Holy Melons be relevant once in a cult round. They also take quite some time to grow so it does require commitment. 

I'd suggest just making the melon disappear after one use.

**Comment by coiax** [comment]
@XDTM that sounds like a feature; some spells/abilities are more effective at consuming one use protection than others, a la Linken's Sphere

**Comment by XDTM** [comment]
Yeah but that'd be like necrophos popping linken's by being somewhat close

**Comment by 4dplanner** [comment]
To me, this all sounds like making a bad feature less bad - it doesn't make it good. Someone else can PR the Linken's idea, but I won't.

**Comment by AdamElTablawy** [comment]
To be fair, an easily massproducable source of antimagic that can be obtained with trivial ease is basically the same reason that null rods aren't orderable from cargo.

Making a bunch of these and distributing them will make a wizard have an awful time and stop a cult in its tracks-the one time use is a better idea, as otherwise these are literally just null rods that can be made to deconvert cultists on throw or a variety of other effects, depending on the botanist, and you can harvest fifty of them with not much effort.

Then again, ridiculously strong plants for little to no effort is par for the course for botany, so.

**Comment by Nickkoranda** [comment]
Null rods do a lot more than just be anti-magic. They are a robust weapon in many flavors, possibly sharp, possibly nodrop, and remove cult runes. Holymelons are just anti-magic.

**Comment by PKPenguin321** [comment]
Fighting the chaplain as wizard is already an exercise in futility, having this mass producable is awful. :+1:

**Comment by ninjanomnom** [comment]
I prefer the alternative to this in #41739

We can revisit this balance problem if it still proves an issue.

**Pull request closed without merging**
