### PR TITLE
Two new official posters

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Adds two new official posters to the game.

image

One poster teaches the crew about common 'kill words' they can use to defeat enemy agents, the other teaches the crew to keep corporate secrets where they belong: in the company. You wouldn't download a gun, right?

## Why It's Good For The Game

These feel like thematically appropriate additions you might see on a corporate-created poster, and are good references to space stations past, and our favorite copyright memes.

## Changelog

:cl:
imageadd: Two new corporate themed posters.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
space stations past?

**Review by Imaginos16 — APPROVED** [review]
Cute.

**Comment by YakumoChen** [comment]
> space stations past?

"boombox" is a notorious word from an old time in which a nukeops team keyed a bomb to the word "boom" only for someone on the station to ask where a boombox was.
Needless to say, they didn't manage to nuke the station.

**Comment by Serxule** [comment]
the sprite quality isnt... the greatest, but they're still neat (and can always be resprited to be higher quality anyways)

**Comment by BlueMemesauce** [comment]
You can't add too much quality to a poster sprite because they're only a couple of pixels. Posters have to be kept simple otherwise they will end up looking indecipherable like the Safety Moth posters.

**Pull request merged**
