### PR TITLE
[NO GBP] Apply multiplier correctly when transferring reagents.

### LINKED ISSUE #79083: Medical cryo cell is transferring far too much cryoxadone
Putting someone in the cryo tube is consuming almost the entire beaker of cryox, and transferring insane amounts to their body.

image

## Reproduction:

Put someone in the cryo cell, turn on.

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
- Fixes #79083 

The multiplier should be applied per reagent volume & not on the requested amount as a whole.

## Changelog
:cl:
fix: cryo and stuff that transfers reagents with a multiplier should transfer correct volumes as expected.
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
This fixed transferring too much cryox into the patient, but it's still consuming the entire beaker.

**Comment by SyncIt21** [comment]
This was the  faulty change i made in the "General code maintenance for reagents PR" . I'm just putting back the original code. Not sure what to do after this.

**Comment by SyncIt21** [comment]
> 10 units out of beaker, 10 into patient. 10 units out of the beaker expected result would be 250 units into the patient.

I don't understand this math how did 10 units become 250 all of a sudden? Can you elaborate?

**Comment by SyncIt21** [comment]
> and magically 

Now I'm convinced this is no longer my problem. If you can show in code where this "magic" happens then I can start debugging from there.

This already sounds messed up

**Comment by lessthnthree** [comment]
> > and magically
> 
> Now I'm convinced this is no longer my problem. If you can show in code where this "magic" happens then I can start debugging from there.
> 
> This already sounds messed up

```
beaker.reagents.trans_to(occupant, (0.04, 25, methods = VAPOR)
```
was achieving this before all the changes.

**Comment by SyncIt21** [comment]
Ok now i understand and can fully explain what's going on.

In the original version of `trans_to` before my PR #78637 was merged this proc was actually bugged and the cryo was actually taking advantage of that bug for the longest time so it needs to be refactored. I'll elaborate

These are the changes i made in the original PR. when adding reagents it first multiplied the transfer amount with the multiplier as expected
Screenshot (327)

Now one would expect that since the transfer amount with the multiplier applied was added to the target. the "EXACT SAME" amount with the "multiplier" applied should also be removed from the source only then the transfer operation works correctly so that no "magic" reagents can be created from "thin air".

Unfortunately that was not the case
Screenshot (326)

This is what i fixed and my PR only exposed it with the cryo. So the cryo chemical effectiveness needs to be adjusted because now `trans_to` will no longer "magically" create chemicals from thin air via the multiplier which was actually stupid now looking back at it.

The cryo was just taking advantage of this bug and i put an end to it.

**Comment by lessthnthree** [comment]
Yeah that makes sense, the cryo cell will have to probably start multiplying the reagent itself before sending it to the proc, I'll have a look.

**Comment by SyncIt21** [comment]
> Yeah that makes sense, the cryo cell will have to probably start multiplying the reagent itself before sending it to the proc, I'll have a look.

Rather than multiplying the amount(which can cause serious balance implications as someone with a syringe can simply milk much more cryodixine from a mob after they come out from the cryo).

A better solution would be to simply amplify the effectiveness of cryo maybe make it 25 times better than before(still balance but less significant than the above case)

**Comment by lessthnthree** [comment]
> > Yeah that makes sense, the cryo cell will have to probably start multiplying the reagent itself before sending it to the proc, I'll have a look.
> 
> Rather than multiplying the amount(which can cause serious balance implications as someone with a syringe/plumbing iv drip can milk much more cryodixine from a mob after they come out from the cryo).
> 
> A better solution would be to simply amplify the effectiveness of cryo maybe make it 25 times better than before(still balance but less significant than the above case)

Agreed. I haven't looked at exactly how it applies on metabolism yet. (I found when transferring only small amounts the person was suffocating in the tube) so other values in it may need to be changed as well.

**Comment by FlufflesTheDog** [comment]
> Rather than multiplying the amount(which can cause serious balance implications as someone with a syringe/plumbing iv drip can milk much more cryoxadone from a mob after they come out from the cryo).

There's no way that I know of to harvest non-blood reagents from a mob's blood, or am I misunderstanding the problem?

**Comment by SyncIt21** [comment]
> There's no way that I know of to harvest non-blood reagents from a mob's blood, or am I misunderstanding the problem?

Umm... you are misunderstanding something. i was talking about how the `trans_to()` magically multiply reagents(in this case cryodixine) inside a mob and later how a syringe/plumbing iv drip can be used to harvest it out.

This PR does not touch on the harvesting mechanism's it only prevents the "magic multiply"

**Comment by ATH1909** [comment]
> > Rather than multiplying the amount(which can cause serious balance implications as someone with a syringe/plumbing iv drip can milk much more cryoxadone from a mob after they come out from the cryo).
> 
> There's no way that I know of to harvest non-blood reagents from a mob's blood, or am I misunderstanding the problem?

you can shove them into a meat grinder and then grind up their meat to get non-blacklisted reagents

but yeah it's not a huge problem, and IIRC, the reagent multiplication is an intentional feature of cryo. I'd recommend consulting maintainers before trying to change that (and/or splitting that into its own PR).

**Comment by SyncIt21** [comment]
> reagent multiplication is an intentional feature of cryo.

It's actually not. It was an Bug that became an accidental feature. You can understand why from the above discussions

The issue I linked in the PR is literally complaining about reagent multiplication

**Comment by SyncIt21** [comment]
> Agreed. I haven't looked at exactly how it applies on metabolism yet. (I found when transferring only small amounts the person was suffocating in the tube) so other values in it may need to be changed as well.

@lessthnthree if you need to amplify the effectiveness of cryodixine then the right place to start would be here 
https://github.com/tgstation/tgstation/blob/4d750241ee5f9f3e1bd2f84a2d95d9c43bf2a246/code/modules/reagents/chemistry/reagents/medicine_reagents.dm#L155

You can buff the power as a whole or you can only buff it when the mob is inside the cryotube something like this

```
if(istype(affected_mob.loc, /obj/machinery/cryo))
   var/obj/machinery/cryo/cryo_tube = affected_mob.loc
  //Now amplify power if the cryo tube is on and operational 

```

I haven't figured out how to adjust the power so you get the same results as before so I leave that to you

**Comment by FlufflesTheDog** [comment]
> > reagent multiplication is an intentional feature of cryo.
> 
> It's actually not. It was an bug that became an accidental feature. Please read [#79084 (comment)](https://github.com/tgstation/tgstation/pull/79084#issuecomment-1769091571)
> 
> The issue I linked in the PR is literally complaining about reagent multiplication

I'm rather inclined to believe the opposite. As much as it may seem silly, that seems to be how it worked for as far back as tg's github goes (here for example, where the remove and addition are a single line apart, with only the add having the multiplier, 11 years ago)
https://github.com/tgstation/tgstation/blob/88be87e8d3d03e7f92912b3c6689e15a99f89820/code/modules/reagents/Chemistry-Holder.dm#L112-L113

Or deep fryers, which use the multiplier to add extra oil to foods, with a comment outright explaining the behavior
https://github.com/tgstation/tgstation/blob/a7665516a6ce8e17ede7be4ccbb4ce108d6738d9/code/modules/food_and_drinks/machinery/deep_fryer.dm#L142

Finally, I want to question what the purpose of a multiplier argument even is, if not changing the ratio of input to output. If it's simply a multiplier on the input AND output, then well, you can just do your change at the call site and remove the argument entirely.

**Comment by SyncIt21** [comment]
> Finally, I want to question what the purpose of a multiplier argument even is, if not changing the ratio of input to output. If it's simply a multiplier on the input AND output, then well, you can just do your change at the call site and remove the argument entirely.

Yeah that's a really good point.  I find it weird that it's simply ok to multiply reagents out of no where and everyone is just ok with it.

But there is also a balance implication to this. What my problem was is that say we have 10 unit's of cryodoxane. If we multiply it(in this case the cryo tube does it by 25) and inject it to the mob the mob will have 250 unit's in their bloodstream.

Now a chemist can grab a hold on this mob and extract this 250 units from the mob via syringe/plumbing iv drip. So you see the problem here? Even though the chemist spent a lot of work creating those 10 unit's he can just put it in cryo, put a monkey inside cryo and wolla get 250 units of free cryoxadone in a matter of seconds from the monkey.

I just want to know why nobody sees this as a problem? If you can convince me then yeah I'll put back the original code.

**Comment by SyncIt21** [comment]
Ok after doing some quick experiment's i realized that cryoxadone actually metabolizes very rapidly and there isn't enough time to extract even a small of it from the mob before it vanishes so it's not a feasible solution and so it's no a big problem than i initially thought it was.

Also after reading this comment

> //Fried foods gain more of the reagent thanks to space magic 

I have confirmed this game is cursed so whatever. Let reagents multiply to whatever amounts i say. I'll put back the original code.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
