### PR TITLE
Adds the DET.ekt Skillchip, upgrading the detective's sense of taste.

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Gives the Detective a roundstart skillchip which allows them to unlock the hidden potential of their tastebuds. With this, they can identify chemicals by taste, and even identify bloodtypes in the same way.
## Why It's Good For The Game
IMG_4060

I've been watching a lot of detective stuff and I think it's really funny how often they stick their fingers into random goo/blood and taste/smell it. 
The idea of a detective chugging a glass of unidentified liquid to identify that there's a lethal chem mix in there is equally funny to me.
Imagine you're recovering from a mugging in the medbay and the detective comes in, takes a blood sample from you, and downs it in one go.
## Changelog
:cl: Wallem
add: The detective now starts with the DET.ekt Skillchip, which allows them to identify chemicals and bloodtypes by taste.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
A hint of licorice... yep, the perp's definitely got O-. Check the records, that's not a common bloodtype.

sir that blood sample had gbs

**Comment by Donglesplonge** [comment]
"ah yes this tastes like lexorin" is gonna be my favorite new bit to see detbros won

**Comment by alien3301** [comment]
Would be cool if it told you not just blood type but DNA of the blood. Det already got a scanner for that and without access to sec records that info is useless so it doesn't sound gamebreaking.

**Comment by 00-Steven** [comment]
oh shit nice, this is so good
funnily enough I was also already most of the way through making a skillchip letting you taste exactly what you sipped

**Comment by SomeoneYouProbablyKnow** [comment]
Why am I laughing? Apologies, my friend. It’s just that as an INTJ, these illogical actions of yours…well, I find them to be amusing.

What’s that? A free sample of some chemicals? Not necessary. I’ve already calculated its flavor in my head. Mmm…perhaps a little more Chloral Hydrate next time…

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
