### PR TITLE
Axes the robotic fabricator (not the exofab)

### PR DESCRIPTION
**Pull request by 81Denton**
robofab

This poor thing isn't used anywhere and doesn't have any functionality other than printing borg parts.

Completely redundant with the exofab around, not to mention that it doesn't have stock parts, a circuit board, doesn't connect to research, etc etc.

### CODE REVIEW

**Comment by Jalleo** [comment]
I believe this is gooncode.

**Comment by improvedname** [comment]
Dont remove legacy code make it a spess ruin

**Comment by 81Denton** [comment]
Ok waiting on your PR

**Comment by Fox-McCloud** [comment]
Make this a child of the mech fabricator, instead.

Not that hard.

**Comment by 81Denton** [comment]
Why bother

**Comment by ExcessiveUseOfCobblestone** [comment]
when someone wants to add it to the ruin they can first revert the PR.

**Pull request merged**
