### PR TITLE
Next round of shuttle fixes at the cost of a small piece of my sanity

### LINKED ISSUE #31667: Shuttles take certain structures and machinery with them in their bounding boxes.
...but not inside of their shuttle area. Isn't the shuttle area thing the whole point of being what's under their influence and what's not? With the exception of other shuttles under a child area in that bounding box, nothing should be getting grabbed outside the shuttle's area. Yet it's selectively picking and choosing certain objects, structures, and machinery. Why does it take consoles but not  airlocks? Why does it take grilles and lattices but not girders? WHO KNOWS?

https://i.imgur.com/ydEwxyy.png
https://i.imgur.com/JHc14jq.png

### LINKED ISSUE #31755: Turfs are not rotated by shuttles
image

Also, I suspect but have not confirmed that turf decals are not rotated correctly either.

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: ninjanomnom
fix: Fixed turfs not rotating
fix: Fixed stealing structures you shouldn't be moving
/:cl:

Also stopped the custom docker from letting you land directly on the map edge.

Warns admins when a shuttle would land or launch in a location with null turfs (aka map edge)
This will leave people trapped in transit space until helped but is better than the alternative, and hopefully raises some awareness to get maps with the issue fixed.

fixes #31755 
fixes #31667

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Turf decals still aren't being rotated. 
image

**Comment by ninjanomnom** [comment]
What isn't being rotated in that picture?

**Comment by SpaceManiac** [comment]
Left side, underneath the engines and heaters, those decals are on the south side of the tile initially and thus should be on the west side at this rotation.

**Comment by ninjanomnom** [comment]
Oh ugh turf decals.

This will take a bit of effort to get a framework for.

**Comment by ninjanomnom** [comment]
Actually no that has to wait for the next pr, the best way to fix that is with a minor rotate rewrite.

**Pull request merged**
