### PR TITLE
Portal guns doesn't do anything to mobs anymore

### PR DESCRIPTION
**Pull request by silicons**
:cl:
experimental: Portal guns no longer hit mobs without a direct click, and will not do anything to mobs even if they directly hit one.
/:cl:
 It is my belief that science weaponry should exist but not be "just better energy guns/whatever". Right now, portal guns are actually pretty powerful, as their random teleport can space people (especially if they have bohs), and actually does burn damage, albeit very little. I want to make scilathe weapons into useful utility things that can be weaponized if you use it right and in somewhat niche scenarios.
This PR will make wormhole projectors into more utility than combat.

EDIT: HITSCAN REMOVED.

### CODE REVIEW

**Comment by Kromgar** [comment]
Removing the best feature of portal guns... boooo

**Comment by kevinz000** [comment]
@Kromgar It is my belief that science weaponry should exist but not be "just better energy guns/whatever". Right now, portal guns are actually pretty powerful, as their random teleport can space people (especially if they have bohs), and actually does burn damage, albeit very little. I want to make scilathe weapons into useful utility things that can be weaponized if you use it right and in somewhat niche scenarios.

**Comment by Wilchenx** [comment]
leave my griffguns alone

**Comment by Shadowflame909** [comment]
In this direction, we're going in. It feels like the only thing that should get closed to any non-lethal ranged blasters is security and security only. I'd personally be more down for a cooldown then this. Yet, I can't really say that I even use it as a viable teleporter anyways. Unless I'm like hijacking and just handed out BOHS to everyone.

**Comment by Dorsisdwarf** [comment]
I am against making portal guns hitscan, its just wrong

**Comment by ninjanomnom** [comment]
Split up the portal gun change from the refactoring. If it needs the refactor then just do it later.

**Comment by Bawhoppen** [comment]
Hitscan slippery slope. No reason for portal guns to be hitscan, when in actual Portal they weren't, and don't make sense to be in ss13 either, especially considering that lasers and bullets aren't.

**Comment by ExcessiveUseOfCobblestone** [comment]
boo

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by RogueSteampunker** [comment]
Science has something useful in it besides the portal gun? (^:

**Comment by ninjanomnom** [comment]
Really not a fan of the hitscan, turning the portal gun into less of a direct damage dealer sounds fine though.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Take off the hitscan for now, that can be debated in another PR

**Comment by kevinz000** [comment]
@Cyberboss done

**Comment by ExcessiveUseOfCobblestone** [comment]
title...

**Comment by kevinz000** [comment]
woops done

**Pull request merged**
