### PR TITLE
[READY]Refactors storage handling from /obj/item/storage to a component.

### PR DESCRIPTION
**Pull request by silicons**
Remake of #33166 old one had far too much stuff that isn't even related as the PR was split into two for ease of review
/obj/item/storage storage/inventory procs removed.
/datum/component/storage now handles all storage. It handles mob interaction with storage like insertion, taking things out, viewing, and emptying it out.
Several component signals added for interaction with storage. Any atom can now be storage.
This does not refactor contents/whatnot, all things are still stored in atoms, not the storage datum itself. The storage datum just handles accesses by mobs and signals.
Anything that detected storage and interacted with it with istypes have been changed to use component signals to detect and manipulate storage.

### CODE REVIEW

**Comment by DaxDupont** [comment]
Good luck!

**Comment by ExcessiveUseOfCobblestone** [comment]
starting strong!

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Jalleo** [comment]
Have you tested the sheet snatcher?

**Comment by kevinz000** [comment]
sheet snatchers fixed btw

**Comment by zaracka** [comment]
Round 86081.
I think the inventory was my roundstart internals box.

This is what my inventory looked like when I crashed:
inventory bug 1

This is what it was supposed to look like:
inventory bug 2

Round 86118.
The inventory was my roundstart satchel.

Inventory background disappeared and I also crashed then.

**Comment by kevinz000** [comment]
in the future specify server too please.

**Comment by kevinz000** [comment]
runtimes from those rounds fixed in latest commit.

**Pull request merged**
