### PR TITLE
Removes the antimatter engine as it's not used

### PR DESCRIPTION
**Pull request by ChangelingRain**
No, it's not staying in unless someone makes it work. It's bad.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
It did work though??
I've used it before. All it's missing is decent sprites and ways to spawn parts.

**Comment by optimumtact** [comment]
This is fine though

**Comment by Shadowlight213** [comment]
@optimumtact It does work though.

**Comment by optimumtact** [comment]
If it's missing sprites then how can you say it works?

**Comment by Shadowlight213** [comment]
@optimumtact It isn't missing sprites. The current sprites just look like shit.

**Comment by optimumtact** [comment]
I see, well it's disingenuous of @ChangelingRain to claim it's broken then.

**Comment by Shadowlight213** [comment]
@optimumtact also, it's not an item, it's an entire engine. I tested it just now, it works perfectly fine.
This is what the sprites look like btw.
Am engine

**Comment by Anonmare** [comment]
Goddamn that looks old.
How power efficient is it?

**Comment by Shadowlight213** [comment]
@Anonmare It's actually not as old as you think. It's younger than the TEG!
TEg
Also, power output depends on the size you make it. More size means more cores, (the blue squares) which means more efficiency.
You also can just increase the antimatter injection rate, which gives more power, but at the cost of possibly damaging it and lowering stability. If stability hits 0, the engine explodes with a huge blast.

**Comment by PKPenguin321** [comment]
That's actually cool. Aside from sprites, why aren't we using this?

**Comment by Iamgoofball** [comment]
what he said

@WJohn @Nienhaus @ausops @Cheridan @KorPhaeron we could use some rad sprites for this meme

**Comment by Anonmare** [comment]
@Shadowlight213 So it's a little like the SM engine (in that it if you increase the emitter rate, the more radiation the SM produces but the more likely it'll start getting unstable).

If it were added as a proper engine, and that's a pretty big if, how would more antimatter be produced? I assume using the PA in some capacity. And how would the antimatter itself work? Cause rupturing a tank of antimatter sounds like it'd be pretty damn devastating if it's anywhere near matter.

**Comment by Iamgoofball** [comment]
HADRON COLLIDER

**Comment by Shadowlight213** [comment]
Looking at how it seems to be designed, expansion packs and antimatter seems to have been intended to be cargo orderable. The antimatter is contained in the little bottle in the picture.
However, having AM be a byproduct of the PA does sound interesting.
Actually a byproducts system that makes things useful for other departments sounds like something design document worthy.

**Comment by PKPenguin321** [comment]
Did you know that one kilogram of antimatter encountering one kilogram of matter will annihilate in an explosion equivalent to 43 million tons of TNT?

**Comment by lordpidey** [comment]
How about instead of the PA producing antimatter as a byproduct, have PAs produce antimatter when a PA beam hits another PA beam?

"Aright new engineer, your job is to jump into this area BETWEEN firings and grab the antimatter.  Don't worry, it's safe as long as you time it right."

**Comment by PKPenguin321** [comment]
To compare to my previous comment, the nuke dropped on Nagasaki only had the force of 20,000 tons of TNT.

**Comment by Bawhoppen** [comment]
@PKPenguin321 the intense muon piezo-gravitational effect in the region of space the station orbits in causes an immense trans-space diffusion of energy from the anti-matter collision

**Comment by PKPenguin321** [comment]
My underlying point was that if we had antimatter as a product you could extract from this, it could be easily weaponized as a massive bomb. I'm assuming we're still spitballing ideas for this engine.

**Comment by Anonmare** [comment]
@PKPenguin321 I assume the antimatter tanks couldn't just be valve-released or else they'd be like instant suicide maxcap bombs. That said, if the tanks rupture on a non-space tile and/or there is atmosphere present they ought to give a maxcap explosion + small amount of radiation fallout. Antimatter also should only be able to be placed in the specialized tanks since, you know, it'd react with the tank's matter. The special tanks would need to be magnetic containment units to keep the antimatter gas contained.

If you overload the antimatter engine, I think it should explode like SM does + much larger radiation fallout. Plus it should be obvious that there's something wrong with the engine if it's being overloaded, like a warning siren or it changes colour or anything akin to that.

**Comment by PKPenguin321** [comment]
So antimatter would be to supermatter as Tesla is to singulo, then. I like it.

**Comment by Cheridan** [comment]
ok i guess this is getting revived now so

**Pull request closed without merging**
