### PR TITLE
Slotfix

### PR DESCRIPTION
**Pull request by ghost**
Fixes the slotmachine credit duplication bug.
Bug related to duplicating currency via inserting credits and deconstructing slot machine.
## About The Pull Request

Added a line of code to fix the duplication inbetween 73 and 74, All that was changed was adding (balance=0) at the end of it to prevent it from spawning two credit chips.

## How This Contributes To The Nova Sector Roleplay Experience

Prevents potential issues during gameplay where credits may be created with no easy way to destroy them

## Proof of Testing
<details>
<summary>
Screenshot 2024-04-27 215831
</summary>
  
</details>

## Changelog
:cl:
fix: fixed a few things
/:cl:

### CODE REVIEW

**Comment by Profakos** [comment]
My mistake for assuming Give Payout actually deducted from balance.  😔

**Comment by SomeRandomOwl** [comment]
Should at least removed some of the nova stuff from pr description, but yea, we told them to take this one upstream since its technically a bug to abuse the economy. You should probally fix the pr description as the changelog since at the moment it just says `fix: fixed a few things`

**Comment by SyncIt21** [comment]
This isn't the right fix. The problem goes deeper with how computers are deconstructed. Anyway this PR can be closed as the slot machine is fixed in the above linked PR

**Comment by SilverWolvesjpg** [comment]
> This isn't the right fix. The problem goes deeper with how computers are deconstructed. This PR can be closed now as the slot machine is fixed in the above linked one.

ah.. thank you, This was my first time trying to fix a bug, I didn't even realize it was related to computers deconstructing twice, as I hadn't observed it occurring anywhere else.

**Comment by SyncIt21** [comment]
> ah.. thank you, This was my first time trying to fix a bug, I didn't even realize it was related to computers deconstructing twice, as I hadn't observed it occurring anywhere else.

No worries. Thank you though for bringing up the issue and even the fix as I wouldn't have located the problem without your input.

You can close this PR yourself now by clicking the button on bottom left of your screen.

**Pull request closed without merging**
