### PR TITLE
Gives a few drink sprites a facelift. I love alcohol I love alcohol.

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

In the drink respriting some of the drinks had some... 'creative liberties' taken when they were made it seems, These are the three that I've seen the most confusion/disdain over so I had a whack at improving them.

image

**Alexander Amaretto**: I, really don't know what the green is meant to be. While it's not ugly or anything, it doesn't really fit in this kind of drink. I choose to go with a darker brown than the original to signify it is dusted with cocoa powder this time instead of nutmeg
**Grasshopper**: I honestly have no idea what this is meant to be, I made it a typical green grasshopper
**Martini**: I think the spriter thought of a dirty martini while making this and chose to make it green to imply there is brine, these are **VERY** different drinks so it was made to be clear to show it is the original.

## Why It's Good For The Game

Did you see that old grasshopper sprite?

## Changelog

:cl:
imageadd: Sprites of the grasshopper, martini and alexander amaretto have been touched up.
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
Not a fan of the top two for different reasons

From what I can tell from pictures it looks like the Alexander is served with cinnamon or a similar brown powder on top, and while your image seems to have gotten rid of (what I assume to be) the lime peels inside, the brown dots you put do _not_ present a very tasty-looking cinnamon dust topping. If you could find a way to make the top look like it has a nice film of dust rather than the sort of brown chunks it looks like it has now, I feel it would benefit.
image

As for the grasshopper, this was stated in the spriting channel, but it just looks boring without a flourish of some sort, and in the grasshopper's case it would be a small pile of brown in the center. I will agree that the original has a bit too much brown throughout, but yours having absolutely none feels a bit much. A neat pile in the center would suffice in my opinion.
image

There are others in the spriting channel and server that are far more qualified to be talking shop about drink sprites than I am to you, so I highly recommend turning to them on pointers if you need any.

**Comment by carshalash** [comment]
image

image

A subtle swirl was used for the amaretto alexander, the grasshopper **KINDA** has a pile of chocolate in the middle.

I honestly would have preferred a mint leaf garnish but people seem to really want a chocolate pile.

**Comment by carshalash** [comment]
Pls respond.

**Review by Imaginos16 — APPROVED** [review]
yea ok sure

**Pull request merged**
