### PR TITLE
Revert "Add DB index"

### PR DESCRIPTION
**Pull request by callanrocks**
I'm pretty sure this will fix library crash.

Maybe.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Nope, it won't

**Comment by Chocobro** [comment]
hopefully it'll at least fix the lag. if not, we may need to completely scrub out the book list.

**Comment by MrStonedOne** [comment]
This change most likely lowered the lag. indexing may increase memory usage, disk usage, and time for inserts, but it doesn't do anything other than reduce select times. and thats where the lag is

**Comment by callanrocks** [comment]
Wrong one then.

**Pull request closed without merging**
