### PR TITLE
Aliens can now open blastdoors.

### LINKED ISSUE #48515: Xeno door opening inconsistency
Xenos can only force open airlocks. They can’t force open anything else, like a windoor (which doesn’t really matter) or a depowered blastdoor.

### PR DESCRIPTION
**Pull request by ShizCalev**
🆑 ShizCalev
fix: Aliens can now attempt to open closed blastdoors.
/🆑

Fixes #48515

### CODE REVIEW

**Comment by knacker48** [comment]
Powered or unpowered? Cause if they can break open powered doors its gonna make the blast doors in xenobio pretty much useless

**Comment by ShizCalev** [comment]
@knacker48 To clarify, this is for player controlled aliens. They can open powered ones after 15 seconds.

**Comment by redta1l** [comment]
https://cdn.discordapp.com/attachments/546561121226719256/673416222347624478/1135670591.flamedramonex20.alienbodybuilders.jpg

**Comment by itseasytosee** [comment]
I don't believe this qualifies as a fix
>antag freeze

**Comment by HomocidlePancakes** [comment]
@ShizCalev Can you test out #48515 but with ling armblade? I have a feeling it will have the same problem.

**Comment by Arathianen** [comment]
>Also, blastdoors can be destroyed with xeno acid afaik

You know wrong. Blastdoors are immune to acid.

This is a bad change. Benos are supposed to be contained by a couple things, blast doors being one of em.

**Comment by ShizCalev** [comment]
comment on the issue report as well tbh, i'm just fixing an inconsistency report.

**Comment by Taylorkills2** [comment]
> > Also, blastdoors can be destroyed with xeno acid afaik
> 
> You know wrong. Blastdoors are immune to acid.
> 
> This is a bad change. Benos are supposed to be contained by a couple things, blast doors being one of em.

No, blast doors can indeed be destroyed by acid. It takes a long time, but destroyed they can be. I know they can be since I've personally acid destroyed one as a xenomorph queen to escape xenobio.

**Comment by ishitbyabullet** [comment]
I'm worried about this being used to cheese away missions.

Can you make it not a thing on the indestructible blast doors?

**Comment by kriskog** [comment]
You got powered containment to contain aliens, doing the same thing pretty much no risk and without a notable power requirement with blast doors is silly.

**Pull request merged**
