### PR TITLE
Adds air canister to Bluespace Capsule room

### PR DESCRIPTION
**Pull request by swankcookie**
It doesn't make any sense for a "space shelter" to not have a source of oxygen
:cl:  Swankcookie
rscadd:  Bluespace Capsule room now contains a air canister, for easier breathing.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Picture?

It already has air in it.

**Comment by Dorsisdwarf** [comment]
Yeah, but the air will leave if you go in it. Fastmos, remember.

**Comment by KorPhaeron** [comment]
It wont, because the threshold tile blocks air

**Comment by swankcookie** [comment]
I'm setting blocks_air to 0, It is inconsistent with like every other airlock in the game, and it's only purpose was to make a space that shouldn't have been habitable... habitable. Which is now fixed.

**Comment by KorPhaeron** [comment]
You've made them literally unusable then. The first time you open a door the pod will be empty of air, and the second time the canister air will go.

All for the sake of adding s big ugly canister that there is no room for

**Comment by KorPhaeron** [comment]
This also removes the donk pockets while keeping the microwave because ???

**Comment by swankcookie** [comment]
1. It's for the sake of getting rid of an invisible magic unexplained gas forcefield.
2. Since when is gas behaving as it should in ss13 a bad thing?
3.the donk pockets are not removed, they're on the other table. I'm not a monster.

**Comment by KorPhaeron** [comment]
>It's for the sake of getting rid of an invisible magic unexplained gas forcefield.

So give the tile some dumb icon and fluff if it bothers you that much. It's already a magical house in a pill.

>Since when is gas behaving as it should in ss13 a bad thing?

Since the feature in question doesnt actually work if you simulate gas, nor is it needed.

**Comment by duncathan** [comment]
It doesn't need to make sense; it's got bluespace in the name

This is dumb and I'll close it when it hits 24 hours unless you convince me otherwise

**Pull request closed without merging**
