### PR TITLE
Adds some privacy shutters for qm.

### PR DESCRIPTION
**Pull request by Helg2**
## About The Pull [Request]
So, since qm is part of command and a head of cargo, it is logical that he will have some privacy. My choice of shutters was made from shutters in hop office on different maps.
I also changed door with windows on common doors because they dont give you privacy feeling, yeah...
IceBox
Meta
image
Delta
Delta2
Kilo

## Why It's Good For The Game
Dunno.
## Changelog
:cl:
add: Adds privacy shutters for quartermaster. Shutters on Kilo/IceBox and blastdoors on Meta/Delta/Tram. Also changed doors with glass to common ones.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
https://github.com/tgstation/tgstation/pull/73188#issuecomment-1415661144

**Comment by Helg2** [comment]
> [#73188 (comment)](https://github.com/tgstation/tgstation/pull/73188#issuecomment-1415661144)

Shit. xd

**Comment by Helg2** [comment]
Seems like a cant hide images under a spoiler, lame.

**Comment by NamelessFairy** [comment]
This is a map only PR which should be fine to re-open during the freeze btw.

**Comment by Helg2** [comment]
Kinda confusing tbh.

**Comment by improvedname** [comment]
those aren't shutters those are industrial blast doors 😝

**Comment by Helg2** [comment]
> those aren't shutters those are industrial blast doors 😝

Thats what privacy shutters are.

**Comment by Zytolg** [comment]
Could you reduce those privacy shutters to being actual shutters? Some heads need the blast doors, but the QM is definitely not on that list. I'd also suggest doing this only on a few select maps to maintain variability.

**Comment by Helg2** [comment]
> Could you reduce those privacy shutters to being actual shutters? Some heads need the blast doors, but the QM is definitely not on that list. I'd also suggest doing this only on a few select maps to maintain variability.

Done, i took hop's office as a reference, because he's kinda useless and dont has many to steal. So kilo and icebox now have common shutters.

**Comment by YakumoChen** [comment]
The QM will never be a true head of staff

**Pull request merged**
