### PR TITLE
Being happy no longer makes you obese.

### LINKED ISSUE #36555: Something is making people fat without eating (Maybe moodlets?)
[Round ID]: 85238

[Reproduction]: Many people have been reporting this in various different rounds, but I noticed it myself today when I was doing botany with a super happy mood, all of a sudden I just turned fat when I hadn't even eaten all round.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
fix: Being happy no longer makes you obese.
/:cl:

Okay so DecreaseSanity(-0.5) is a double negative, which means if you call that, its actually increasing it by 0.5. I called that every time you had more sanity than you were allowed to at the time, which meant you only went further away from the limit, getting more and more sanity as you go.

Because the function for calculating how much hunger you get makes you need less food the more sane you are, it actually went into minus, meaning you'd be so sane you'd be gaining nutrition, instead of losing it.

lesson of the day: to become happy means to become fat.

closes #36555

### CODE REVIEW

**Comment by Qustinnus** [comment]
kevinz was right sorry for doubting you this time @kevinz000

**Comment by yorii** [comment]
speedmerge candidate?

**Review by Cyberboss — APPROVED** [review]

**Comment by Kraseo** [comment]
please speedmerge this or it's going to be really annoying to have to make lipolicide 24/7

**Comment by Iamgoofball** [comment]
you know this is actually pretty funny I say we keep this in

**Comment by Shapsy** [comment]
Laugh and grow fat

**Comment by Anonmare** [comment]
>Santa Claus is fat
>Santa Claus is jolly
>Jolly means to be happy
>Happiness causes obesity

We've cracked the code

**Pull request merged**
