### PR TITLE
Replace dorm lights with lamp random spawners

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This removes the default light from dorm private area and replaces it with a lamp random spawner.  This gives the crew the ability to toggle the lights without outside help.

The chance for light bulbs to spawn broken is 5% so the lamp spawner reflects that.

## Why It's Good For The Game

Now you can sleep in peace.

## Changelog

:cl:
qol: Replace dorm lights with lamp random spawners
qol: Remove non-lamp item from lamp random spawner and give it a 95% chance to spawn (light bulbs have a 5% to spawn broken)
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
Problem is the lamp spawner has a chance to spawn `/obj/item/phone` which is just a "red phone" that doesn't light up or do anything.

**Comment by timothymtorres** [comment]
I was already aware of this but it's a small 10% chance.  Considering that station lights can randomly break at the start of the round, the chance to have no light spawn should still exist.

**Comment by Cheshify** [comment]
The North Star dorms are each their own area and have light switches, you didn't need to change anything. Also, if you're going to PR something that changes lighting in each dorms room, maybe it would be best to ensure your spawner doesn't just throw a random useless red telephone in some of the rooms depriving people of lighting?

**Comment by Cheshify** [comment]
image

**Comment by RaveRadbury** [comment]
> I was already aware of this but it's a small 10% chance.  Considering that station lights can randomly break at the start of the round, the chance to have no light spawn should still exist.

I you're gonna do this don't half-ass it

**Comment by Cheshify** [comment]
Random spawners are best used when they keep rounds fresh by proving new hurdles or rewards to players (see: tram maint). All that's being done is needlessly changing the dorm rooms by adding random lamps (which might not even give you a LAMP) instead of just adding lightswitches, which in the case of the North Star, isn't even an issue.

**Comment by timothymtorres** [comment]
The lamp random spawner has been updated to reflect the 5% chance of broken light bulbs spawning and the northstar changes have been reverted.

**Comment by RaveRadbury** [comment]
A phone isn't comparable to a broken light. Can we even construct lamps in-game?

**Comment by timothymtorres** [comment]
I removed the phone from the spawner.  The lamp has a 5% chance to not spawn, which is consistent with the light break chance at roundstart. (not even taking account the additional chance for a blackout event)

I think you guys are missing the main point here.  Players shouldn't have to be smashing a light with a fire extinguisher to turn off the light for a dorm room.  Some maps already have **only** lamps in their dorm rooms and I'm making this consistent. 
 While northstars dorm rooms light switch is nice, I don't think having a separate APC + area for each dorm is ideal map design.

**Comment by timothymtorres** [comment]
I'll just leave it in the current state.  If someone wants a dorm area dark, smashing the light takes half a second, and they can always steal a lamp from somewhere else.

**Pull request closed without merging**
