### PR TITLE
New Librarian traitor item: Haunted Magic Eightball

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Toy magic eightballs can now be found around the station in
maintenance and arcade machines. Ask your question aloud, and then
shake for guidance.
add: Adds new Librarian traitor item, the Haunted Magic Eightball.
Although identical in appearance to the harmless toys, this occult
device reaches into the spirit world to find its answers. Be warned,
that spirits are often capricious or just little assholes.
/:cl:

- [x] Do most of the coding
- [x] Testing
- [x] Sprites 
image

- [x] Add toy versions to maint spawn, arcade machines and toy crates
- [x] Make purchasable in uplink, not sure on price yet

How it works: Eightballs have a pool of twenty answers. A toy version just picks them randomly, while the haunted version polls the ghosts and picks the most popular. To use, it must be shaken for 15 seconds after you've spoken your question aloud, and then has a ~~90~~ 180 second cooldown between uses. Haunted and toy eightballs are indistinguishable except in the quality of their answers.

### CODE REVIEW

**Comment by Robustin** [comment]
Neat concept but Chaplains are already way too snowflakes. Give it to the librarian or someone else.

**Comment by PKPenguin321** [comment]
>ghost popup every 90 seconds

Maybe make it like 3 minutes or something

**Comment by optimumtact** [comment]
The chaplain has his grace, make this librarian only please.

I think one special item per job role will be sufficient for now

**Comment by RandomMarine** [comment]
Something like this will definitely need a "don't ask again this round" option for the ghosts.

**Comment by kevinz000** [comment]
[03:07] <kevinz000> .8 coiax
[03:07] * beerobot shakes the magic 8 ball... It is certain
[03:07] <kevinz000> .8 coiax good coder
[03:07] * beerobot shakes the magic 8 ball... Don't count on it

**Comment by coiax** [comment]
@RandomMarine you're right, but we currently don't have the ability to ignore events. I could remove the sound playing, then it shouldn't be too intrusive.

**Comment by coiax** [comment]
@ExcessiveUseOfCobblestone how do you feel about toy eightballs very very occasionally being haunted?

**Comment by ExcessiveUseOfCobblestone** [comment]
yeah sounds good, only other concern is RandomMarine's. Just don't tie a sound to it preferably.

**Comment by InsaneHyena** [comment]
Xhuis is going to finish the arcane tome item for librarians any second now, so they should get an actually powerful item. 8-ball, meanwhile, is 2tc and it's decent for it's cost.

**Comment by dannno** [comment]
nigga is that straight up a solid black circle with an 8 on it

**Comment by Doppeltongue** [comment]
Librarian has something similar on some stations in the Ouija Board. Also, this is more of a mysticism object than a worship object, so it doesn't really fit the Chaplain role thematically.

**Comment by coiax** [comment]
@dannno yes well done, you have correctly identified that it is a shitty coder sprite.

**Comment by bgobandit** [comment]
can the 8-ball be changed to something more space-like

**Comment by coiax** [comment]
@bgobandit Except it's just an eightball, it's a toy. A toy so popular apparently that it lasted five centuries mostly unchanges.

I mean, if you can think of anything better, then sure.

**Comment by Militaires** [comment]
MAKE IT LIBRARIAN ONLY

**Comment by optimumtact** [comment]
Neat concept and execution is clean and well developed :+1: more of this

**Pull request merged**
