### PR TITLE
Add messenger program to cyborg tablet

### PR DESCRIPTION
**Pull request by ghost**
## Why It's Good For The Game

I see no reason for them not to have it considering every other job (even the AI) has it.

## Changelog
:cl:
add: Cyborgs can now receive and send PDA messages
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
https://github.com/tgstation/tgstation/pull/66921

**Comment by Ryusenshu** [comment]
Gonna say no to that
We have silliconnect that is able to communicate to borgs

Also a Malfs Robofactory will be dead when suddenly all the default borgs show up on everyones pda
... not even speaking of borgs made hidden or syndie borgs

**Comment by Ryusenshu** [comment]
> > not even speaking of borgs made hidden or syndie borgs
> 
> Looks like syndieborgs get the messenger program without this change already

Which isnt intended and it a bug

**Comment by zxaber** [comment]
The messenger app was intentionally removed from borgs.

Unlike borgs, the AI deals with multiple crewmembers at once, remotely. AI serves as the human-silicon interface, and in many ways acts as cyborg dispatch. This is why the AI has Messenger access and shares the binary radio channel with the borgs.

If you *need* to message a borg direct, use Siliconnect's message function.

**Comment by JohnFulpWillard** [comment]
I'm closing this PR because like Zxaber said, we had removed this app intentionally, after it was given to borgs accidentally, which you can see my reasoning for in the PR I have linked above.
I left this PR open stay for an extra day for any input from other maintainers or any points against the PR I had linked, but none had come up.

syndicate borgs getting the app is an error and its removal should be in a separate PR.

**Pull request closed without merging**
