### PR TITLE
removes the northstar arcship from the codebase

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
image

closes https://github.com/tgstation/tgstation/issues/87888
## Why It's Good For The Game
The gods have spoken
## Changelog
:cl: grungussuss
del: The northstar arcship has been removed. :(
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
> what do you mean remove nebulastation.dmm....

wait FUCK

**Comment by EEASAS** [comment]
and also hey uh dont forget to delete the arrivals/evac/cargo shuttles for the map

**Comment by Helg2** [comment]
Probably could leave Northstar as one of the buyable shuttles, similar to other old station shuttles.

**Comment by ElGitificador** [comment]
> what do you mean remove nebulastation.dmm....

could remove that one as well tbh

**Comment by DATA-xPUNGED** [comment]
> and also hey uh dont forget to delete the arrivals/evac/cargo shuttles for the map

Wait, why are we removing these? We still have the old shuttles for kilo and pubby in the code, for example.

image

**Pull request merged**
