### PR TITLE
Fixes that one white pixel on bodyparts

### PR DESCRIPTION
**Pull request by ChangelingRain**

### CODE REVIEW

**Comment by Jordie0608** [comment]
( ͡° ͜ʖ ͡°)

**Comment by Jordie0608** [comment]
For real however, what does this refer to?

**Comment by ChangelingRain** [comment]
Cut off bodyparts with a dir of SOUTH have a single white pixel floating near them this fixes that

**Comment by ChangelingRain** [comment]
it's this pixel it removes that white pixel
THIS one

**Pull request merged**
