### PR TITLE
Removes wings

### PR DESCRIPTION
**Pull request by Shadowlight213**
Climbing out of the slippery slope.

Feedback seemed to me like people didn't like it.
I agree, it doesn't fit the SS13 theme at all.
I'm leaving the flight system in for @kevinz000. His system is much more thematic than mine.

:cl:
del: Angels and the flight potion have been removed
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
leaving a system up to me is a horrible idea but ok :^)

**Comment by Iamgoofball** [comment]
:+1:

**Comment by ShadowDeath6** [comment]
lavaland doesn't really fit the theme of ss13 anyway imo.
personally I liked the idea of an "organic" type of jetpack, maybe it'll be done better elsewhere.

**Comment by nullbear** [comment]
could be kept as a costume item.

**Comment by Militaires** [comment]
good

**Comment by Bawhoppen** [comment]
no don't remove what do you mean it doesn't fit the theme this is nonsense ( I have no idea how they worked mechanically but anything is good in this game that doesn't ruin balance)

**Comment by Hatfish** [comment]
Xhuis was working on a lavaland sci-fi retheme a few months ago and he did a pretty good job of overhauling wings, maybe you could prod him into finishing it or something.

**Comment by Shadowlight213** [comment]
I wanted to move these into organs at one point.
Also will be needed for inevitable overmeme mode. (I mean, we have the meathook, medgun and the reactive armor sprite already)

**Comment by ShadowDeath6** [comment]
>>>>>>>>>implying the medgun is a reference to oversnowflake

**Comment by Militaires** [comment]
@ShadowDeath6 tf2 baybeee

**Pull request closed without merging**
