### PR TITLE
MiiyaBot's HairTweaks 2

### PR DESCRIPTION
**Pull request by MiiyaBox**
## About The Pull Request

1. **Two** new hairstyles, fitting more punk/messy needs.
2. Changing the shading (and a pixel) on Jade
3. Renaming and fixing odd way it ended on the side view of "Marginally shorter Yet Long Bedhead".
(From "Marginally Shorter Yet Long Bedhead" to "Shorter Bedhead")
4. Changing the name of "BedHead 4X", and slightly making it darker around the face as it was a very weak contrast.
(From "BedHead 4X" to "BedHead 4x")

## Why It's Good For The Game

While Adding two more short hairstyles that are about being bold and punk it gives a little more love to jade to be used with the other hairs! While also fixing some small oddities from my last changes.
Like odd pixels and way it ends with Marginally shorter yet long bedhead, and, Changing it's name to a more normal one as the last one was a joke about the way I described it every time I said I wanted a shorter version. and while I still like that joke.
I believe it would at least lightly annoy someone due to it being too big and disturbing the alphabetical order that the list tries to follow.

Here's a example of it all in-game(with comparisons): 
All_in_one

## Changelog

:cl:MiiyaBot
add: Two new hairstyles! ("All the Fuzz" & "Over Eye (Izutsumi)")
spellcheck: Renamed "Marginally shorter yet long bedhead" to "Shorter Long Bedhead"
spellcheck: Renamed "BedHead 4X" to "Bedhead 4x"
fix: Slight changes to "Jade", "Shorter Bedhead", "Bedhead 4x"
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
The hairstyles look great, but I humbly suggest it would be better if their names described the hairstyle. People know what a "Bowlcut" looks like- but what is an "Izutsumi" haircut?

**Comment by MiiyaBox** [comment]
> The hairstyles look great, but I humbly suggest it would be better if their names described the hairstyle. People know what a "Bowlcut" looks like- but what is an "Izutsumi" haircut?
> 
> EDIT: You said you're looking for name suggestions. I'll try to think some up.

When I first started it, it looked like...
image
But personally I don't feel it is like it after so many changes. that is even why it is called "Izutsumi". since it was the character who I was trying to replicate. And I just couldn't think of a cool name for it after the changes.

**Comment by Farquaar** [comment]
Over Eye 2 maybe? Since that seems to be a defining feature of the sprite

**Review by Twaticus — APPROVED** [review]

**Comment by JohnFulpWillard** [comment]
Does the hair style really have to mention "Izutsumi", no other hairstyle does so

**Comment by MiiyaBox** [comment]
> Does the hair style really have to mention "Izutsumi", no other hairstyle does so
If you want it gone, I can do that in a snap of fingers.

**Review by MiiyaBox — COMMENTED** [review]
Hold up- 2 Errors? Not sure why...? Did I screw up something here on my side...? I didn't see anything weird with what I wrote.
Edit: Seems it really was not something on my side. as the error from above and under have now been deemed alright.

**Pull request merged**
