### PR TITLE
Did you remember to install Counter-Strike Source? Adds emergency fallbacks for the most commonly edited DMIs that get icon states programmatically to help with development and bug reporting.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

unknown

If you equip clothing without correct icons, the game will now inform you that the clothing is broken. Please file bug reports if you see missing textures or error models.

ERROR

Added the error model to the DMIs with the highest likelihood of people accidentally doing minor misspellings to icon_state names, so that issues with missing icons get reported more often.

## Why It's Good For The Game

I got really annoyed when dealing with dmi issues during Families 3.0 development, and it's honestly a huge pet peeve of mine that so many things just default to invisible if the icon breaks. This allows you to still interact with the item in game as it'll at least have an icon to click.

Players also report broken assets more when they look like the source engine broken asset visuals. Like, I ain't even kidding, when I was doing development on a project people reported missing textures and shit way more when I made missing textures do the source engine purple/black checkerboard. Same with the error model.

Everyone and their mom knows what these visuals mean, it's crazy.

## Changelog
:cl: FuryMcFlurry, Yeeye
imageadd: Missing textures and error models are now visible if an item has a broken icon. If you see broken assets in game, report it!
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
lmao icon diff couldn't handle it

**Comment by Fikou** [comment]
this is epic but won't this increase the codebase size a bunch by adding something to all the icon files

**Comment by 81Denton** [comment]
Is there a way to handle this without manually adding error textures to a lot of DMIs? 
I can see this get really annoying when 1) people assume that all DMIs have the error texture fallback (but they don't) and 2) people add new DMI files and someone has to check that all of them contain error textures.

**Comment by Qustinnus** [comment]
adding a icon to like 100 files is not a good implementation for this

**Comment by Iamgoofball** [comment]
@81Denton I only added the error texture to DMIs that
1. determine the used icon_state programmatically
2. has a ton of icons in it
3. is edited pretty often

i can scrap the action button stuff but I figured they could use it the most

the clothing and stuff is staying though cuz that's what this was made for originally

this is also not dmi bloat, this is maybe 100 kilobytes, tops, for what is an extremely useful tool to prevent us dealing with missing icons that nobody ever reports

**Comment by Iamgoofball** [comment]
like, to clarify i did not put this in every single dmi file we own

**Comment by Shadowflame909** [comment]
We already have floortiles. Now we just need walls.

**Comment by 81Denton** [comment]
@actioninja I'd prefer for this to be reverted and test merged on a single server so the whole playerbase doesn't have to deal with dozens of huge blinking ERROR signs until someone fixes them a couple of weeks later. Once those are taken care of, we can full merge.
What do you think about it?

**Comment by Iamgoofball** [comment]
@81Denton The point of the merge is for the players to find the blinking error signs for us. If you make a revert, I will revert your revert.

**Comment by 81Denton** [comment]
@Iamgoofball Odd, I don't recall you being a maintainer.

**Comment by PKPenguin321** [comment]
Seems broken? Players are walking around with small pink dots everywhere where there is no sprite to be missing

image
weird pink earring looking this, floating white pixel at the bottom left only on my south sprite, for example. others have belts of pink on only some directions?

**Comment by Iamgoofball** [comment]
a bugfix was made and merged for the floating white pixel, servers just need to update

**Comment by actioninja** [comment]
@81Denton most of the more egregious issues are already being corrected, it's just cosmetic anyways.

**Comment by pireamaineach** [comment]
This PR fails to take into account that many things are unsprited intentionally.

**Pull request merged**
