### PR TITLE
Buffs laserpointers

### PR DESCRIPTION
**Pull request by Anonmare**
[Changelogs]: Catpeople can now be incapacitated by laser pointers

:cl: 
balance: Laserpoitners now incapcitate catpeople
/:cl:

[why]: Nerfs Kevinz

### CODE REVIEW

**Comment by praisenarsie** [comment]
sadly, freeze.

**Comment by AnturK** [comment]
Above, otherwise i'd open it myself. Also you ate some tabs in there.

**Comment by kevinz000** [comment]
YOU CAN'T STOP ME

**Comment by Anonmare** [comment]
Lame

**Comment by AnturK** [comment]
You can do it.

**Comment by kevinz000** [comment]
ANTURKEY EVIL!!

**Comment by Qustinnus** [comment]
we could use an IsCat() helper.


Or honestly just move catpeople out of the fucking shitty loop where they are humans, but theyre really mutants, but they're really another race. and just make them a seperate race.

**Comment by duncathan** [comment]
idk what people mean about catpeople being a separate race; it's well defined in code and afaik understood in policy that they are just mutant humans

**Comment by calzilla1** [comment]
YES

**Comment by KorPhaeron** [comment]
Reopening freeze prs is dumb they end up visibly open for like an hour before they hit the 24 hour mark

**Comment by obscolene** [comment]
we did it reddit

**Comment by Screemonster** [comment]
ahahahah you absolute fucking madman

**Comment by optimumtact** [comment]
@KorPhaeron my bad

**Comment by BlueNothing** [comment]
Why'd we do this, again?

**Comment by optimumtact** [comment]
because it is humorous

**Pull request merged**
