### PR TITLE
Adds an extra slot(another c38 speedloader) for detectives holster

### PR DESCRIPTION
**Pull request by RiskySikh**
## About The Pull Request
image
It's not a game breaking change, nor does it gave the detective any "boosts" or advantages. It's just that it adds an extra item slot for the detectives holster which is another speedloader. Before, the detective had three item slots, but now it has four.

## Why It's Good For The Game

In my opinion, I feel that the detective doesn't have enough ammunition with and they usually run out. Which is why I added another item slot to give the detective more ammo. It doesn't change the game, nor does it give any unfair advantages. It just gives the detective another speedloader in their holster. I understand that there are concerns since some detective players are known to shoot people for minor offenses, but regardless of the amount of speed loaders they have. It only depends how they act, and how they play. Essentially instead of your usual three C38 speed loaders including one in the revolver. now it has four. It just gives the detective an extra speed loader to defend themselves during drastic situations. 

## Changelog
:cl:
add: One extra item slot for the detectives holster(another c38 speedloader)
/:cl:

### CODE REVIEW

**Comment by RiskySikh** [comment]
I understand that the space endings change, but it doesn't affect the code, and it works perfectly fine. It's just that my visual studio code automatically does that.

**Comment by Qustinnus** [comment]
you still need to fix that though

**Comment by RiskySikh** [comment]
> 
> 
> you still need to fix that though

I know, but how do I fix that.

**Comment by Pugie** [comment]
Now det holster can hold 4 disablers instead of 3!

**Comment by SpaceManiac** [comment]
@RiskySikh if on windows, `git config core.autocrlf true` and set VSC to use CRLF line endings (it's one of the bottom-right status icons). if on linux, `git config core.autocrlf input` and set VSC to use LF line endings. What I just described is the default.

**Comment by RiskySikh** [comment]
> 
> 
> @RiskySikh if on windows, `git config core.autocrlf true` and set VSC to use CRLF line endings (it's one of the bottom-right status icons). if on linux, `git config core.autocrlf input` and set VSC to use LF line endings. What I just described is the default.

Thanks a lot man for helping me, I appreciate it a lot. Have a good day

**Comment by ExcessiveUseOfCobblestone** [comment]
if it doesn't change anything why make the PR?

It DOES change something, it's just that people don't care about storage creep.

The point of ballistics is that they can have a much larger ammo capacity than their energy counterparts but have to trade off in storage ~~unless you cheat and use trashbags~~

Prob gonna close this, if you cba to resupply after spending 18 shots then you should have to "waste" inventory slots. That's assuming det is meant to have an active role in which he needs to be using his gun with frequency 😏

**Comment by Pugie** [comment]
You guys aren't even ready for my mindblowing pr that lets you load 357 bullets in 38 loaders

**Comment by RiskySikh** [comment]
> 
> 
> if it doesn't change anything why make the PR?
> 
> It DOES change something, it's just that people don't care about storage creep.
> 
> The point of ballistics is that they can have a much larger ammo capacity than their energy counterparts but have to trade off in storage ~unless you cheat and use trashbags~
> 
> Prob gonna close this, if you cba to resupply after spending 18 shots then you should have to "waste" inventory slots. That's assuming det is meant to have an active role in which he needs to be using his gun with frequency 😏

Sorry my bad for the misunderstanding. I was trying to explain, that most detective mains I come across tend to have active roles instead of investigating, which is why I feel an extra c38 speedloader in the detectives holster seems proper. That's the change, it just adds an extra slot in the detectives holster and gives them another c38 speedloader. It's hard to explain it, but I hope this will make it less confusing.

**Comment by optimumtact** [comment]
The detective is not supposed to be playing super cop.

For that reason, I see no reason to increase how much of an ammo load they can carry

**Comment by RiskySikh** [comment]
understood

**Comment by cacogen** [comment]
What he needs is more bag space for the huge amount of shit he has to carry compared to other roles.

**Pull request closed without merging**
