### PR TITLE
Fixes vent_clog bad chem id runtime

### PR DESCRIPTION
**Pull request by ShizCalev**

### CODE REVIEW

**Review by SpaceManiac — DISMISSED** [review]

**Comment by DaxDupont** [comment]
Salt is supposed to be salt. But I think salt might be sodium chloride in the reagent ids

**Comment by DaxDupont** [comment]
My bad though, made an assumption

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
`sodiumchloride`

**Review by SpaceManiac — APPROVED** [review]
I think what needs to happen long-term is replacing chem IDs by their datum typepaths. Same for techweb designs really.

**Pull request merged**
