### PR TITLE
Adds strobe shields

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: By crafting a wall mounted flasher frame (can be ordered via cargo), a flash, and a riot shield, you can now construct a strobe shield. The strobe shield combines the functionality of a riot shield and a flash, and can be reloaded with flash bulbs.
/:cl:

### CODE REVIEW

**Comment by Mervill** [comment]
How does the flash get activated exactly?

**Comment by anconfuzedrock** [comment]
haha he actually did it the absolute madman

**Comment by GunHog** [comment]
Can I use a tele riot shield to make it?

**Comment by KorPhaeron** [comment]
@GunHog 

yeah

**Comment by anconfuzedrock** [comment]
haha classic gunhog

**Comment by DrPillzRedux** [comment]
@Mervill 

Trigger on the handle that you hold the shield with.

**Comment by FantasticFwoosh** [comment]
Quick question, but in the hands of revheads does this convert? (if it flashes)

**Comment by calzilla1** [comment]
It should

**Comment by Cheridan** [comment]
powercreep 👮 🔦

**Comment by Okand37** [comment]
Looks like the GSG 9 have made it to SS13. Guess its time for a tactical **blitz**krieg.

**Comment by KorPhaeron** [comment]
@FantasticFwoosh 

Yeah

**Comment by Mervill** [comment]
For the record

> You use the shield inhand like you would a flash

Was the answer I was looking for

**Comment by jughu** [comment]
I can wait to see cargonia with flashshields and combat shotguns

**Pull request merged**
