### PR TITLE
Adds the Warranty Void Clause to Bug Report Template

### PR DESCRIPTION
**Pull request by Iamgoofball**
if you varedit the nuke to explode and then it explodes when the clown hits it with his bike horn, please dont make an issue request

### CODE REVIEW

**Comment by Zilenan91** [comment]
Do we really need this much bloat to EVERY issue report rather than just making people use common sense

**Comment by Iamgoofball** [comment]
you're intended to delete it before making your issue report

**Comment by Shadowlight213** [comment]
Add "However, you are free to ban the responsible coder for the duration of the time it takes for them to fix your issue. The previous statement about not making the report still applies. Let them figure out the request in the ban appeal."

**Comment by duncathan** [comment]
@shadowlight213 we're not obligated to fix shit when you're the ones who break it.

**Comment by Shadowlight213** [comment]
honk.

**Comment by optimumtact** [comment]
this is literally the stupidest thing I have seen

**Comment by Giacom** [comment]
Maybe the notice could be placed in CONTRIBUTING.md, since it will say to read it before posting issues.

**Comment by Cheridan** [comment]
does anyone actually read it though?

**Comment by duncathan** [comment]
I had a better idea for this I'll do it when I get home

**Comment by tkdrg** [comment]
if we wanna do this duncs PR is strictly better

**Pull request closed without merging**
