### PR TITLE
Venture - a (yet another) Emergency Shuttle

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
Adds a new emergency shuttle, the "Venture"
Named after some randomass starsector ship because i couldnt think of a cool name
Based on a BYOS build on /tg/ sybil

Roughly 49 seats (+ 1 Wheelchair) in total (7 in sec, 5 in command)

## Why It's Good For The Game

Variety is nice

## Changelog

:cl:
add: Added a new emergency shuttle, the Venture
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
god dammit i hit the wrong button

**Comment by YakumoChen** [comment]
Add more chairs to the central area so it feels more like a crew transporter? At least around the walls.

**Comment by BlueMemesauce** [comment]
>Variety is nice
Do you have any more justification? There's not much variety here, it's just a basic shuttle identical to any of the other default ones. I get that's kind of what you were going for but I don't really see a need for it.

**Comment by Bawhoppen** [comment]
It's important to have the fundamentals, not everything needs to be flashy and crazy like we've had in the past few years 👍 

(Though there are limited chairs that is true)

**Comment by mc-oofert** [comment]
honestly watching people fight over seats while most just stand and then get a skull frac is hilarious but sure i will add more chairs

**Comment by mc-oofert** [comment]
> >Variety is nice
> 
> Do you have any more justification? There's not much variety here, it's just a basic shuttle similar to any of the other default ones. I get that's kind of what you were going for but I don't really see a need for it.

Keyword "I", also any layout change has its own gameplay implications anyway for example 
some dude just fortifies shuttle medical so you break through storage

**Comment by mc-oofert** [comment]
also the central space is there for some chef to set up their foodcart or some assistants fighting and killing eachother
or bartender setting up a shop..
engineer projects and all that

**Comment by Toastgoats** [comment]
It's nice but it's begging for a gimmick, something that sets it apart from the other "titanium" shuttles.

Think, what would make this shuttle different to _play?_

My thoughts? Go all in on the "venture" idea, and by that I mean make it a venture _capitalism_ shuttle.
Add in different plots of empty space with a few essentials like tables and vendors, and then let the crew set up shops and trade the stuff they made during the shift?

**Review by san7890 — CHANGES_REQUESTED** [review]
image

this whole section (and the others to a lesser extent) just feel so _barren_. I don't know if decals would fix it, or doing more with the empty space (to re-making the whole seating arrangement), but it just feels completely bland and uninteresting.

some people are mentioning a "lack of a gimmick", but i don't think shuttles _need_ to have a gimmick... they just need to be unique or at least modern. this just doesn't feel like it was mapped in 2022, it feels like it was mapped six years ago and forgotten with just how lacking in actual space utilization. if you want to start again, i would advise rethinking the shape of the shuttle, and really think on how you can minimize empty space (or, maybe fill in empty space with decal artwork? your call).

apologies if i'm coming off as dickish, but it just doesn't really look appetizing or at a solid level of mapping. just either:

- Rework the space you have to be less empty, including more decalling (no shame in going back to iron floors), and make it decidely interesting.

- Figure out what you really like from this design, and give the whole shuttle a new form factor (circular, ovally, etc.) while leaving the rest behind

- Brainstorm a cool new gimmick and start from scratch. I can forgive all the blandness in the world if there's something uniquely interesting about the shuttle that'll eventually pique people to decide "This shift, I'm _going_ to get that shuttle at all costs." This might be hard to do though, just a suggestion.
-

**Review by san7890 — CHANGES_REQUESTED** [review]
image

you're forgetting a green corner tile here (muh ocd)

image

This intercom (and other wall mounts (like lights) on the same tile as lockers) just look bad to me, spread out your wall mounts a bit? You've got plenty of space. Would also be nice to add niceties like posters if you really want to (not a requirement).

medbay looks quite empty. maybe some stretchers and a defib mount would fill it out (maybe even a cheeky wheelchair)? up to you though.

thanks for sticking with the process, sorry i haven't been as on top of this.

**Review by san7890 — CHANGES_REQUESTED** [review]
Whoops, almost forgot one thing. Can you add your map to the config at https://github.com/tgstation/tgstation/blob/master/config/unbuyableshuttles.txt ? I think we've been forgetting to do that lately, but should really be on top of that (brownie points if you can get some alphabetization sorter extension and alphabetize the entire list as well). Should be good to merge after that!

**Comment by mc-oofert** [comment]
> Whoops, almost forgot one thing. Can you add your map to the config at https://github.com/tgstation/tgstation/blob/master/config/unbuyableshuttles.txt ? I think we've been forgetting to do that lately, but should really be on top of that (brownie points if you can get some alphabetization sorter extension and alphabetize the entire list as well). Should be good to merge after that!

done

**Pull request merged**
