### PR TITLE
You can now choose from ten random names in plastic surgery, and abductors can give their victims creepy subject names

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: Plastic surgery now lets you choose from a list of ten random names, so you can pick the one that you prefer.
tweak: Abductors performing plastic surgery can now give their target spooky subject names, with one normal name available for standard plastique.
/:cl:

#35646 was closed because it granted *complete* freedom in the naming schemes, but someone suggested adding choosing from a list of random names, which I thought was a good idea, so I added it.

I also made it so that abductors can choose from one of nine "subject names", with the tenth name being a normal one. The scheme is as follows:
`Subject ("i" if male, "o" if female)-(randomly picked between a, b, c, d, or e)-(number between 10000 and 99999)`
So a name for a male subject might be:
`Subject i-b-58391`

### CODE REVIEW

**Comment by Armhulen** [comment]
yeah!

**Comment by Shadowflame909** [comment]
THIS IS WHAT I WANT. GOOD MEME FEATURES, REE NOT THAT REMOVAL JUNK

**Comment by Bawhoppen** [comment]
Not sure so about the abductor change. The whole meme is that after you're abducted you only vaguely remember even being abducted and nobody is supposed to believe you. Having your name changed is silly and breaks this.

**Comment by PKPenguin321** [comment]
they don't have to use it

**Comment by Xhuis** [comment]
From the PR body:
`with the tenth name being a normal one.`

**Comment by fludd12** [comment]
I still think there should be some degree of direct choice, since I really hate the pregenned names

**Comment by ExcessiveUseOfCobblestone** [comment]
then setup your character preferences properly :^)

**Comment by Bawhoppen** [comment]
@PKPenguin321 Yea the abductors don't, but the person getting to done to them doesn't exactly get the choice. And I'm saying that abductors shouldn't have the choice either because it breaks the spirit of the event and will make the round seem strange.

**Comment by zamolxius** [comment]
i love this, but add increased weight for David Icke

**Comment by ExcessiveUseOfCobblestone** [comment]
rule 10 also applies to your character's identity.

**Pull request merged**
