### PR TITLE
Real Emojis

### PR DESCRIPTION
**Pull request by ghost**
Actuallypassestravisandmakeseveryonehappy edition
emoji
listemoji

Adds twitter emojis (twemoji) to the game, can be used in OOC, ASAY, ADMINPM. Can be toggled off in chat settings. Also added a verb to OOC that lists the SS13 emojis from emoji.dmi. The key for SS13 emojis has not been changed.

:cl:
add: Added 1400+ Twitter Emojis to chat! Can be toggled off in settings.
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
you didn't do everything.

**Comment by Spaceinaba** [comment]
DELETE THIS IDIOT

**Comment by uraniummeltdown** [comment]
It passes Travis now, does not change the ss13 emoji key, does not remove the OOC safety check thing. We're good to go fam

**Comment by praisenarsie** [comment]
you missed a crucial thing.

**Comment by uraniummeltdown** [comment]
@KorPhaeron @MrStonedOne @Cyberboss Passes Travis now and doesn't override the SS13 emojis, please reopen this

**Comment by praisenarsie** [comment]
>asking mso and cyberboss about game design

**Comment by uraniummeltdown** [comment]
This doesn't even affect the game, if you dislike emojis you can toggle them off

**Comment by praisenarsie** [comment]
just wait for kor and stop complaining

**Comment by Cyberboss** [comment]
24Hours

**Comment by lzimann** [comment]
was already closed before on #35567

**Comment by uraniummeltdown** [comment]
This PR fixes what was wrong with the old one

**Comment by PKPenguin321** [comment]
yeah reopen this

**Comment by KorPhaeron** [comment]
So @optimumtact says the code is not worth maintaining, @vuonojenmustaturska thinks it might be if we can integrate our old emojis into it, what say you @Rockdtben

**Comment by MrStonedOne** [comment]
It doesn't actually need to be maintained. it's mostly self contained, uses static versions of the js, and responds simply to a css class. The hook client side could be moved to some more generic system but one would have to be made and that would likely have to be its own pr anyways.

**Comment by Cyberboss** [comment]
>So optimumtact ~~says the code is not worth maintaining~~ agrees with leoz

**Pull request closed without merging**
