### PR TITLE
Monkey gamemode overhaul

### PR DESCRIPTION
**Pull request by ghost**
OOK OOK!!

* Infected monkeys now have a hivemind. Beware, this is NOT silent, as you will audibly chimper sometimes when communicating through it!
* The roundstart infectees are "leaders" now, who are designated with large hivemind text and a "heart of freedom", which will give them a small stimulant injection and a tiny bit of healing if they reach ~10 health... provided it hasn't activated within the last 10 minutes!

### CODE REVIEW

**Comment by Qustinnus** [comment]
we waz kangs

**Comment by The-clown-known-as-Pepe** [comment]
*smacks lips*

**Comment by The-clown-known-as-Pepe** [comment]
WE

**Comment by KorPhaeron** [comment]
Freeze

**Pull request closed without merging**
