### PR TITLE
goonchem tweaks v3

### PR DESCRIPTION
**Pull request by pudl**
-adds colors to every medical chemical
-buffs styptic, silver sulf and synthflesh
-changes some fluff messages
-changes brute and burn patches to only have 20u
-makes patch max volume 40
-gives geneticists their own neurological damage first aid kit
-removes a nanomed i accidentally added to virology
-resprites patches
-first aid kit names were inconsistent, fixed
-added more descriptive first aid kit descriptions
-changes names of a lot of pill bottles i made to be consistent with handmade pill bottles
-adds mix messages to a lot of chemicals
-changes patch description to say what chemical it contains

http://puu.sh/fiWSN/ff8cc5091c.png

### CODE REVIEW

**Comment by dannno** [comment]
:-1: to resprite, shit doesnt feel right when it's bigger than bruise packs/ointment/bottles/pills/every single other piece of medical shit

**Comment by paprka** [comment]
:-1: just stop touching things you two

**Comment by pudl** [comment]
@paprka the only reason you're thumbs downing is because you want goonchem to stagnate and be removed. this literally fulfills a shit ton of requests i've gotten, it's for the players, so quit shitposting

**Comment by paprka** [comment]
I'd rather someone experienced that isn't fucking garbage at game balance fix goonchem

Or like, goofball, since it's his project and not yours and all you do is fuck it up and expand it into the rest of medical when this is a fucking chem overhaul, not a medical overhaul.

Maintainers need to stop accepting these fucking stupid PRs because they're making us look worse and worse.

**Comment by pudl** [comment]
the problem with the goonchem overhaul in the first place is people being upset about the fact that chemistry is being integrated with medical.
the biggest "overhaul" to med is the fact that first aid kits have different contents. medical doctors not having bruise packs and ointments was at first bad because first aid kits were utterly useless, but here i am, i fucking fixed that issue. patches are now just as effective as a bruise pack or ointment. patches are not an "alternative" to bruise packs, they're a replacement, bruise packs are insta click-to-heal with the "balance" being having to click on limbs, while patches are 18 seconds to heal with the balance being that it's 18 fucking seconds instead of instantly.

goonchem itself, when it was added to goon, wasn't just a chemistry overhaul. the system completely changes chemistry, its interaction with medbay, and medbay's interaction with people. if you actually played goon instead of being horrendously xenophobic you would have seen this coming from the start and made more of an effort to stop it.

**Comment by paprka** [comment]
"goonchem itself, when it was added to goon, wasn't just a chemistry overhaul."

Nobody cares, nobody wants goon med, we want our own med, so please stop. Thanks. This is not goonstation, it never will be goonstation, but I'm not opposed to us porting things. Fundamentally changing our medical to goon's medical which is for a DIFFERENT PLAYSTYLE is fucking retarded, so leave it alone.

**Comment by pudl** [comment]
the big flaw in this entire fucking this is that, in the end, medical doctors have no reason to exist. there is no "tg medical system" and there is no "goon medical system" because medical doctors are absolutely useless in every way regardless of what we have. the only two non-chem dependent medical things we have in game are bruisepacks/ointment and sleepers, and sleepers still magically generate chems. and you're removing those.
the medical system revolves around the proper usage of chemicals, and very very rarely surgery. for example, this is how a doctor treats certain things.
BRUTE
(tg med) bruise packs, if those aren't available bicardine.
(goon med) healing patch, if that's not available saline-glucose/salicyclic
BURN
(tg med) ointment, if that's not available kelotane or dermaline
(goon med) burn patch, if that's not available atropine
TOXIN
(tg med) dylovene
(goon med) charcoal
OXYGEN
(tg med) dexalin or dexalin plus
(goon med) salbutamol or perflu
CLONE
(tg med) cryox or clonex, sometimes both
(goon med) mannitol
RADIATION
(tg med) hyronalin, or arithrazine
(goon med) potassium iodide, or pentetic acid

so what if your patient needs surgery? oh wait, goon surgery is the same as ours except it doesnt take time to do each step, and we're not even porting that!
medical doctors are nothing but people who fucking shill out the stuff chemists produce! they do nothing else! the only thing unique to tg med is fucking bruise packs and ointment, and those are COMPLETELY REPLACED BY PATCHES! BECAUSE THEY'RE SHIT! GAMEPLAY!

**Comment by Iamgoofball** [comment]
And all the work in the piratepad to get all 3 of us to a stalemate goes down the drain

**Comment by WJohn** [comment]
Love the new border on the patches :+1:

**Comment by paprka** [comment]
I'm trying to move medical away from purely chem-based and you're trying to shove chemistry into everything. Brute is the most common type of damage and shouldn't just be 'give him some chems that magically stitch his wounds back together'. At least bruise packs for brute trauma make sense versus magical wound stitching chems in their blood stream.

Who cares this will probably be merged anyway because nobody cares if quilty wants to domineer all of medical to fit his goon fetishes since he's such a huge fan of goonstation. This is a complete joke.

**Comment by Deantwo** [comment]
Only part of this that I really wanna see added right now is the first one listed.

> -adds colors to every medical chemical

Need to actually look at the rest, but at least I don't like the resprite.

**Comment by pudl** [comment]
it only changes the description of pre-spawned patches in medkits so someone knows what chemical it uses, not all patches
also, even if it did add it to every patch, i'm not going to change my pr to fit your not even fucking merged prs, lol

**Comment by Deantwo** [comment]
Just saying that because as far as I know, #7402 is a goal we want to reach with chemistry at some point in one way or another.

But ok then that part I also like, your description is far from clear on a lot of your points.

**Comment by AlexCrimson** [comment]
I like the different kinds of patches, but arnt they too big? Looks like you would need two hands to apply that monster of a patch.

**Comment by babinsquared** [comment]
I agree that the patches are too big. From a presentational perspective, they look goofy huge. From a practicality perspective, they'll make it hard to click things underneath, which is a pain when you're dealing with large amounts of both patches and tiny pills (which is a large part of chem's job). They should be comparable in size to bottles, not to sheets of paper.

**Comment by dannno** [comment]
yeah the sprite we have right now is fine as it is.

**Comment by pudl** [comment]
as the person who made the current sprite, i am legitimately ashamed of it and i want it removed.
i could care less if large patches obscure tiny pills, because chemists being allowed to just leave out stacks of pills and patches is shit.

**Comment by babinsquared** [comment]
If leaving patches and pills out is shit, then that's a balance issue. I suppose I could toss them in the med vendor and let the doctors take them out. Needless complexity is fun! (not). It also interferes with other parts of the chem office, like covering up beakers after you eject them from the patch-making machine.

The new sprite still looks bad and is about two or four times larger than it needs to be. It's almost the size of the medkit, jeez.

**Comment by paprka** [comment]
"as the person who made the current sprite, i am legitimately ashamed of it and i want it removed."

lel good luck people hate any sprite changes even if you made the original one.

**Comment by Dorsisdwarf** [comment]
The new sprite is big because pudl wants to think he's on Goon, which has massive sized patches.

**Comment by paprka** [comment]
epic

**Pull request closed without merging**
