### PR TITLE
Added the Janitorial Console

### PR DESCRIPTION
**Pull request by Cruix**
Inspired by #40141

:cl:
add: Added the advanced janitorial console to the custodial closet. Use it to clean without ever having to leave your closet!
/:cl:

Added an advanced camera console that can clean and pick up trash. Starts with access to the custodial closet and most hallways. New areas can be accessed by using advanced sanitation permits, found in the janitor's vending machine, while standing in the area you want to clean in.

When xenobio was difficult and time consuming, it got a camera console. Why not the janitor too?

### CODE REVIEW

**Comment by IllotAFV** [comment]
This sounds a little bit overpowered. Any all access jobs can just take this console,reconstruct it somewhere safe,open all areas and spy on people,like AI does. AI,however,doesnt have arms to validhunt that antag,that it has found. AI view also can be detected with that completely not useless traitor multitool. 
Janitor is now Warden 2.0,but without guns.

**Comment by MrDoomBringer** [comment]
janidrone

**Comment by XDTM** [comment]
I could see a remote-controlled janidrone for cleaning departments where nobody opens the door for you, although it should be handheld and with limited range

**Comment by FantasticFwoosh** [comment]
Um. I think application of consoles could be better applied rather than having the janitor stick out a existance hiding away in the maintenance closet. 

- Why not give one of these machine consoles to engineering who are required to patrol fixing damages as a secondary duty to engine maintenance and emergency repairs (or just to let people without space suits fix breaches)

Janitor-borgs being a solid second to the most efficient way to clean besides going outside yourself, this gives Janitors even less incentive before cyborg mechanisation eventually removes their jobs to do anything themselves.

**Comment by lolman360** [comment]
mopboots that clean floors you walk over when?

**Comment by optimumtact** [comment]
for obvious reasons

**Comment by Cruix** [comment]
What happened to the 24 hour rule? The code works, there has been constructive feedback, and it does not violate any stated policies.

**Comment by XDTM** [comment]
If it was a serious PR it would lead to really bad gameplay, good code or not; if it was just a jab at xenobiology powercreep then it wasn't meant to be merged in the first place.

**Comment by Iamgoofball** [comment]
@Cruix He's a head coder. It's his right.

**Comment by Cruix** [comment]
If a maintainer can just close a pr "because I don't like it", what is the point of even having the 24 hour rule? All it does is create false expectations.

**Comment by optimumtact** [comment]
sorry that you felt you had a chance of getting this PR merged

you did not

**Comment by cacogen** [comment]
make this for engineering

**Pull request closed without merging**
