### PR TITLE
Gives Mining Hardsuits the same fire protection as Explorer suits

### LINKED ISSUE #18870: Mining Hardsuit is not fire immune like Explorer's Suit
I assume this is a bug. If its a design decision then why the fuck does the explorers suit have fire immunity and not a hardsuit designed for mining?

PS: Please make the Mining Hardsuit ashstorm proof

### PR DESCRIPTION
**Pull request by swankcookie**
fixes #18870

### CODE REVIEW

**Comment by Kromgar** [comment]
Cheers.


Shit got me killed fighting an ash drake

**Comment by jughu** [comment]
No why no its space resistant dont make it fire resistance let kor make goliath playes add fore resistance screee

**Comment by swankcookie** [comment]
@jughu make the last part of that legible, and i will respond.

**Comment by jughu** [comment]
Dont add the same fire resistance on mining hardsuits
Just make goliath plates add fireproof on it so they have to work for it

**Comment by swankcookie** [comment]
But they don't have to work for their current suits, so that just presents an unnecessary barrier to an item that's not even currently anywhere on the map.

**Comment by Kromgar** [comment]
Yeah you need to spend 2000 points to get the hardsuit it should atleast be as decent as an explorer suit

**Comment by jughu** [comment]
A hardsuit is for cold space and not hot storms

**Comment by Cheridan** [comment]
counterpoint: CE's hardsuit is fireproof 
:fire: :space_invader:

**Comment by jughu** [comment]
But ce fight fires miners not 🔥

**Comment by swankcookie** [comment]
well obviously they do in some capacity or this PR wouldn't exist :smiling_imp:

**Comment by jughu** [comment]
If you want to be ash proof augment yourself takes like 5 minutes

**Comment by drynwyn** [comment]
>augmentations stop ash storms from hurting you

this is incredible

**Comment by TheColdTurtle** [comment]
But can you install legion souls in an augmented body?

**Comment by jughu** [comment]
Yes

**Comment by jughu** [comment]
All organs work in augmented bodies

**Comment by jughu** [comment]
Booo

**Comment by swankcookie** [comment]
Make a revert PR if it bothers you this much.

**Pull request merged**
