### PR TITLE
F2 works for quick screenshotting again

### LINKED ISSUE #34412: F2 and Shift+F2 act the same
F2 is supposed to be "Quick Screenshot", which works when you select it in the "File" menu, but pressing F2 brings up the save-file prompt same as Shift+F2 does.

@ninjanomnom

b413546bc0711faa0400af278236c9911c3d758c

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request

This has been an issue for almost 4 years
pretty sure BYOND changed it's client commands and forgot to update all documentation

Fixes https://github.com/tgstation/tgstation/issues/34412

## Why It's Good For The Game
a quick keybind for screenshots is nice

## Changelog

:cl:
fix: F2 works for quick screenshotting again.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Shift F2 doesn't seem to call this hotkey at all, from what I've tested.

**Comment by SuperNovaa41** [comment]
just tested it on local and it works fine

**Comment by SuperNovaa41** [comment]
yeah so apparently Shift + F2 is just like.. a default keybind now? and also the client commands have fully changed so now `.screenshot auto` is actually just `.auto`

**Comment by TheBonded** [comment]
>This has been an issue for two years

january 2018 was nearly 4 years ago man...

**Comment by SuperNovaa41** [comment]
> > This has been an issue for two years
> 
> january 2018 was nearly 4 years ago man...

time is a son of a bitch

**Comment by Mothblocks** [comment]
damn this gonna be annoying when i accidetanlyl press f2

**Pull request merged**
