### PR TITLE
I18n translation system

### PR DESCRIPTION
**Pull request by AddRaiser**
## About The Pull Request

Adding a translation system to SS13 TGUI with possibility of adding more languages in future

## Why It's Good For The Game

Now we will have a possibility to translate TGUI without dying trying to solve merge conflicts

:cl:
qol: New translation system for TGUI
/:cl:

image
image

### CODE REVIEW

**Comment by Mothblocks** [comment]
This is really cool, but I don't think there's a chance that a codebase both at our scale and with maintainer being a volunteer job that we:

1. Ever enforce using these
2. Ever actually vet the translation strings going in
3. Which means that tg itself probably shouldn't have any of the strings, meaning the option is useless

Ideally you would have a system like this on your own downstream that is modular and based on like, generated XPaths that you vet, but I don't see a world in which we can actually support this.

I'm closing this at 24 unless someone thinks I'm crazy

**Comment by AddRaiser** [comment]
> This is really cool, but I don't think there's a chance that a codebase both at our scale and with maintainer being a volunteer job that we:
> 
> 1. Ever enforce using these
> 2. Ever actually vet the translation strings going in
> 3. Which means that tg itself probably shouldn't have any of the strings, meaning the option is useless
> 
> Ideally you would have a system like this on your own downstream that is modular and based on like, generated XPaths that you vet, but I don't see a world in which we can actually support this.
> 
> I'm closing this at 24 unless someone thinks I'm crazy

Honestly I didnt thought that you should enforce using these
Just accepting translations from us cause as I see its the only reasonable way of making a translation without shooting at upstream support

**Comment by JohnFulpWillard** [comment]
this looks cool but it would have to be way more in-depth than this, and I don't see it as viable.
or maybe I'm just biased because knowing french would be useful for the first time in my life

**Comment by Mothblocks** [comment]
I don't think there's any way we can blindly accept translations from a language none of us speak

**Comment by AddRaiser** [comment]
> I don't think there's any way we can blindly accept translations from a language none of us speak

What if I could make it so you could only store "en" translation file and downstreams could add their own files?

**Comment by Iamgoofball** [comment]
@Mothblocks there is no reason we shouldn't support localization when the biggest SS13 servers are foreign language, it's stupid to completely ignore the majority of ss13 players by volume being non-english speakers

at the very least, this lowers the barrier of entry for codebases catering to foreign language speakers

**Comment by Iamgoofball** [comment]
@ninjanomnom @optimumtact requesting a headcoder vote on this

**Comment by Mothblocks** [comment]
> > I don't think there's any way we can blindly accept translations from a language none of us speak
> 
> What if I could make it so you could only store "en" translation file and downstreams could add their own files?

We still wouldn't be able to enforce using these, meaning I'm not sure how much value you would get out of it.

**Comment by Iamgoofball** [comment]
@Mothblocks we can just lint for it

**Comment by Mothblocks** [comment]
You definitely can't broadly lint for this. You can lint for it in raw text form only, which doing so would require an enormous migration over, but dynamic text isn't so simple, like dropdown entries.

And on that note, anything that is being passed from the game world (which in tgui, is a lot) is fundamentally untranslatable in this setup

**Comment by Mothblocks** [comment]
It's not so much a "don't let perfection be the enemy of good" thing more than it is that conceptually this just doesn't work with our engine or our crew

**Comment by Iamgoofball** [comment]
while that's true, this still covers a very large amount of text

**Comment by optimumtact** [comment]
i actually dont mind this, i have to do it for work i may as well do it here too.

**Comment by AddRaiser** [comment]
> I see a few other technical issues:
> 
> * Implementation requires importing translations into every single file; or maintaining separate translations per each UI. This boilerplate could be avoided if you had an external file with all the translations, then `i18n()` function could be used with zero arguments.
> * You should design it with translation tools in mind, like [Transifex](https://www.transifex.com/) or [Locize](https://locize.com/). They make it easier for players to contribute. Maintaining separate translations per each UI makes it harder to use these tools.
> * `t()` should support text-to-text mapping in addition to key-to-text, this would enormously help in translating dynamic content (but not all of it, which is still an issue if we want full localization).
> * When changing language, UI should re-render, not sure where this happens in your code, you should ideally have something like I18nProvider which would use `context` to store all the necessary state and re-render when it changes.

Actually Ive added "localization" for a specific file just cause I wanted to avoid using external programs for this and still be able to easily find strings. So it sounded better than 1 big external file. But a tranlation tool would be better tho ofc

Do you mean that it should also work with text _instead_ of a key? Like
t("My best string")
Just because as I can see it could break it all cause someone would change it a bit and it translate

And it rerenders already on language change you dont have to reopen windows :)

**Pull request closed without merging**
