### PR TITLE
Add kahki pants to the sec wardrobe

### PR DESCRIPTION
**Pull request by optimumtact**
:cl: oranges
add: Sec now has khaki pants for tacticoolness
/:cl:

I like pants

### CODE REVIEW

**Comment by lolman360** [comment]
very good

**Comment by Shadowflame909** [comment]
Sec pants. I am now anger!

**Review by praisenarsie — CHANGES_REQUESTED** [review]
update the vending refill

**Comment by ma44** [comment]
Slippery slope

**Comment by optimumtact** [comment]
@praisenarsie no this is a limited time offer

**Comment by GuyonBroadway** [comment]
Now add mall ninja turtlenecks.

**Comment by epochayur** [comment]
you guys complain about powercreep then go and make a PR like this

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
