### PR TITLE
[READY]make all those annoying brackets be gone

### PR DESCRIPTION
**Pull request by Shdorsh**
it's the last eyesore I need to remove from circuit printers. Who even came up with this eyecancer idea?

[Changelogs]: # These brackets looked ugly anyway. Now the printers should be ok.

:cl: Shdorsh
spellcheck: removed ugly useless brackets from printers
/:cl:

[why]: # So that my eyes can rest again.

### CODE REVIEW

**Comment by Shdorsh** [comment]
Will just be merged with #40129 for the sake of making it pass quicker. Don't feel like waiting a few months for this.

**Comment by Cyberboss** [comment]
>Pull requests must add, remove, or change only ONE feature or related group of features. Do not "bundle" together a bunch of things, as each change may be controversial and hold up everything else. In addition, it's simply neater.

**Comment by Cyberboss** [comment]
Also no pull request is merged before 24 hours pass. The smallest and least controversial PRs get merged the fastest

**Comment by Shdorsh** [comment]
No probs, folks.

**Pull request closed without merging**
