### PR TITLE
Adds Bitter Shandy drink

### PR DESCRIPTION
**Pull request by fleure**
~~I literally have no idea what a "Snow White" is and neither does Google, and I've even worked behind a bar for a time, so renamed the beer+lemon-lime drink to its most obvious equivalent, a shandy.~~

Also added a bitter shandy, ale+lemon-lime.

These snowflake reagents are something, huh?

Sprite by Nurdock:

### CODE REVIEW

**Comment by tkdrg** [comment]
@fleure are you still working on this?

**Comment by fleure** [comment]
Not much I can really tweak. If people want it and are okay with the sprite, merge away, else Nurdock needs to update the sprite or PR gets closed if no one wants it.

**Comment by pudl** [comment]
it's not the size, it just needs to be skinnier

**Comment by fleure** [comment]
Closing this PR, not too much interest in it.

**Pull request closed without merging**
