### PR TITLE
Adds minimum to space pirate payoff event

### PR DESCRIPTION
**Pull request by kriskog**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Skoglol
tweak: The space pirates will no longer ask for pocket change.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

The space pirates event can currently ask for a very low amounts of credits, which will almost always lead to them being paid off by the crew. There is no lower limitation, so when cargo buys guns for all the cash you get offers like 4 credits or you'll walk the plank. This sets it to 20 000 credits. 

Feedback on the minimum amount appreciated.

### CODE REVIEW

**Comment by nicbn** [comment]
Make it half of current station funds, floored to be a multiple of 1000. If funds are below 1000, make it 1000.

**Comment by kriskog** [comment]
With budgets how they are now, reducing the max payoff is not something I am willing to do. I like the flooring though, makes it neater.

**Comment by 4dplanner** [comment]
Why not do this with the max function?

**Comment by ExcessiveUseOfCobblestone** [comment]
you could just clamp the value between X and Y lol.

Personally I think it should scale with living players and an offset to avoid using it for meta info but not my PR :)

**Comment by kriskog** [comment]
> And max always takes two arguments

Incorrect, max() takes 1 or more arguments.


>you could just clamp the value between X and Y lol.

Clamp is just wasteful. In this case it runs a min and a max for something a max does just as well.

With budget and cargo money from starting crates being fairly constant, I don't really see the need to scale by players. Having to pay the pirates off should hurt in any situation.


I guess max is easier to read if you are not used to ternary if, but it's not a new concept and both are widely used in the codebase. But fine, I will change it to use a max instead.


As for my performance question, I would still like to know.

**Comment by ExcessiveUseOfCobblestone** [comment]
if you want to know then run the profiler.

Also, again, this is only ran ONCE on announce. If there's good reason to do so (readability,gameplay,etc.) then performance is secondary.

**Comment by kriskog** [comment]
I know it is only ran once. The performance question is still important for future applications that are not though, which is why I would like to know. I will take a look at the profiler, thanks for the tip.

**Comment by 4dplanner** [comment]
> Incorrect, max() takes 1 or more arguments.
You're right,  I got confused and was thinking of other languages

**Comment by Tlaltecuhtli** [comment]
fixed numbers are bad and relying on volatile code as mean of balance is bad, make it rand(1/3 of all money on station , 2/3 of all the money), also increase the timer as u cant physically get the money in time

**Comment by nicbn** [comment]
>relying on volatile code as mean of balance is bad

It's actually the best way of balance as it will always adequate to the round circumstances, and `rand` using all money in station is still relying on volatile code.
And we need a fixed "magical number" minumum so if the station funds are null or negative there will be a minimum at all.

**Comment by 4dplanner** [comment]
> fixed numbers are bad and relying on volatile code as mean of balance is bad, make it rand(1/3 of all money on station , 2/3 of all the money), also increase the timer as u cant physically get the money in time

Fixed numbers are like the entire point of this PR, wtf.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's a tlalt post lol!

**Comment by ninjanomnom** [comment]
For your information max is faster but even if it weren't it would be by such a minimal amount that you should use it regardless in 95% of cases because it's more clear what's happening.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
