### PR TITLE
Updates the book scanner sprite

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
You see this?
aaaaaaaaa
Slanted. Tilted. Isometric.
scannergg-export
scanner-export

Unbothered. In its lane. Happy. Focused. Flourishing.

Thanks to imaginos for ironing it out

Also adds a sound when it scans, courtesy of [freesound.org](https://freesound.org/people/Omar%20Alvarado/sounds/199544/)

https://user-images.githubusercontent.com/66052067/184714042-09d732d3-b23a-48f3-ac3b-6c50b3d942c2.mp4

## Why It's Good For The Game
Removes another isometric sprite from the game.

## Changelog

:cl: Wallem, Imaginos
imageadd: Improves the book scanner sprite
soundadd: Adds a sound when scanning a book
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
I just realized I don't think there's anything in the code to use that animated sprite

Why was there an animated sprite just sitting in the .dmi files

I guess I'll try to figure out a good place to add it in or something, maybe if there's a book in the machine? Or when you scan the book?
I'll have to do that later.

**Comment by Comxy** [comment]
There is a light pixel missing at the top of the light animation

**Comment by Wallemations** [comment]
> There is a light pixel missing at the top of the light animation 

Good catch, I'll fix when I get back home

**Comment by Wallemations** [comment]
Turns out I'm being dragged somewhere tomorrow, and I'm not at my main computer at the moment, so I'll be unable to fix any of this for like

A day?
I'll do it when I can. Not like there's any rush lmao

**Comment by Imaginos16** [comment]
very cool PR, me likey.

**Pull request merged**
