### PR TITLE
Multiple Color Clown Costumes!

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑
The Clowns at Clown Planet have recently shipped over some new colored outfits for the clown to use!
/🆑
This pr adds new clown costumes that come in a variety of colors including blue, green, yellow, purple, orange and now rainbow! so now clowns can go out in the station in the latest clown style!

### CODE REVIEW

**Comment by fluffe9911** [comment]
clown

Clown suits in action

**Comment by bgobandit** [comment]
honk

I approve

**Comment by fluffe9911** [comment]
Now with Rainbow Clown Outfit!

**Comment by Bombpants** [comment]
Clock cult and blood cult themed suits? NT and syndicate suits? The possibilities are endless.

**Comment by fluffe9911** [comment]
Yes but sadly my lack of spriting skills can only get me so far

**Comment by ExcessiveUseOfCobblestone** [comment]
that's why you just greyscale the suit and overlay abuse :^)

**Pull request merged**
