### PR TITLE
Removes Gang from rotation.

### PR DESCRIPTION
**Pull request by LanCartwright**
:cl: 
tweak: Chance of Gang rounds in random rotation is now 0.
/:cl:

[why]: # Rounds do not contribute anything of value to the average gameplay of /tg/station13. The gamemode is unfun, uncreative and it's elements is a combination of an unsolvable player problem and gameplay problem. Adding more guns and clunky mechanics has not made the rounds any different or more fun, and thus this buggy TDM mode should go.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Serverside config doesn't update when the codebase config does, so this is pointless

**Comment by LanCartwright** [comment]
Oh. alright.

**Comment by KorPhaeron** [comment]
If you want to stop gang from appearing on the server you have to convince the headmins to change the config or just outright remove the mode again

**Comment by Anonymous583** [comment]
I support this proposal regardless.

**Comment by Robustin** [comment]
There's a poll up right now, go cast your votes. YAY DEMOCRACY. 

My PR wasn't even merged for the round that induced this salt from Cartwright.

**Pull request closed without merging**
