### PR TITLE
Fixes DeltaStation Holodeck Critical Area Failure

### LINKED ISSUE #67124: Deltastation's holodeck causes a breach whenever you load a simulation
Reporting client version: 514.1568

## Round ID:
[183389](https://scrubby.melonmesa.com/round/183389)

## Reproduction:

- Go to the holodeck on Deltastation
- Load a program
- The lower side wall is immediately breached and the holodeck instantly dies

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

image

Lol, lmao. Areas do matter.

## Why It's Good For The Game

image

Much better.

Fixes #67124.

## Changelog

:cl:
fix: The holodeck on DeltaStation will no longer vent all of its atmospherics into space when a program is switched. Whoops.
/:cl:

### CODE REVIEW

**Comment by Kylerace** [comment]
what have they done to my boy

**Comment by san7890** [comment]
> what have they done to my boy

I'm so sorry

**Comment by Kylerace** [comment]
`/obj/machinery/computer/holodeck/LateInitialize()//from here linked is populated and the program list is generated. its also set to load the offline program
	linked = GLOB.areas_by_type[mapped_start_area]
	if(!linked)
		log_mapping("[src] at [AREACOORD(src)] has no matching holodeck area.")
		qdel(src)
		return

	bottom_left = locate(linked.x, linked.y, src.z)`
image

**Comment by Son-of-Space** [comment]
Me pictured above

**Pull request merged**
