### PR TITLE
Adds a Syndicate Bluespace Bodybag to the uplink

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Adds a Syndicate Bluespace Bodybag to the uplink. It behaves identically to a normal bluespace bodybag, but it looks sus.

image

It costs 6 TC.
## Why It's Good For The Game

I think this could be a fun addition to stealth for traitors. You can get this pretty early on, without the suspicious paint, but you can also spend 6 TC to get it quickly and easily - which is what the uplink is all about, getting objective items without spending 15 minutes doing busywork.

The reason I think this might be good is in how much it can help with stealth, but there's of course other uses that are worthy of being brought up in the discussion. Carrying TTVs sneakily (though you can do this with wrapping paper or even burgers), it being too easy to threetap the captain and hide them on you, etc. This is partly part of the sandbox and partly potentially a concern, but I think the high pricetag makes up for it. If you bought a revolver and the bodybag you only have enough money for one speedloader.
## Changelog
:cl:
add: Adds a Syndicate Bluespace Bodybag to the uplink
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
> You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

noooooooo

**Comment by Xkallubar** [comment]
Too expensive for a reskin of an item that you can get 15 minutes into the round if sci and mining puts in a minimal effort towards doing their jobs.

**Comment by SomeoneYouProbablyKnow** [comment]
It's kinda sad seeing an uplink item that's literally just "this rnd thing" without any kind of twist to it. It doesn't trap you when you walk on it, it's not connected to a identical bag you can stash, it doesn't explode when you point at it it's literally just an item from rnd.
And i'm sure some uplink items are like that but it being identical is just... a shame.

**Comment by SimplySmiley123** [comment]
> It's kinda sad seeing an uplink item that's literally just "this rnd thing" without any kind of twist to it. It doesn't trap you when you walk on it, it's not connected to a identical bag you can stash, it doesn't explode when you point at it it's literally just an item from rnd. And i'm sure some uplink items are like that but it being identical is just... a shame.

Honestly a bodybag acting as a trap to catch and kidnap visually impaired crew would be amazing.

**Comment by Xackii** [comment]
> If you bought a revolver and the bodybag you only have enough money for one speedloader.
>
revolver costs 13 tc + speedloader costs 4 tc

**Comment by Xackii** [comment]
The price is too high. I understand that this can be used to quickly steal a corpse and all that, but in my opinion it is more useful for carrying a lot of large objects for gimmicks and something like that. in both cases 6 tс is too much, I can just take a basic bodybag in medbay.

**Comment by Time-Green** [comment]
GBP too low 😔
Also it's just really lazy (not you, the traitor). It's expensive to counteract the fact that it's lazy, but I'm not sure if that's something we want to encourage?
I do think more stealth tools don't hurt, but I don't think this is it

(sprite is cool though)

**Pull request closed without merging**
