### PR TITLE
Auto Rifle Autolathe Ammo

### PR DESCRIPTION
**Pull request by Steelpoint**
The Auto Rifle is the only mainline weapon in the game where you cannot print bullets for it from a hacked autolathe, almost every other ballistic weapon, from shotguns, sketchins, SMGs to traitor Revolvers and C20rs can have their ammo printed off. This was a conscious decision on my part due to the massive controversy that surrounded the addition of auto rifles to the game and that denying the rifles the ability to get more ammo printed was a compromise I made.

I believe the rifle has been in the game long enough that I believe it should be only right to finally allow autolathes to print ammo for it, since the weapon I believe failed to live up to the OP expectations. 

You still need RnD's cooperation to print off the more valuable magazines, such as the toxin tipped or armour piercing magazines. 

--------

The box of bullets costs the same amount as all other bullet boxes do in terms of metal cost, in addition the box only holds 20 bullets.

Also, the autolathe must be hacked, a bit inconsistent since its a legitimate/legal weapon but that's besides the point. 

Thank you.

:cl: Steelpoint
add: Auto Rifle, standard, bullets can now be printed from hacked Autolathes. 
/:cl:

### CODE REVIEW

**Comment by xxalpha** [comment]
>This was a conscious decision on my part due to the massive controversy that surrounded the addition of auto rifles to the game and that denying the rifles the ability to get more ammo printed was a compromise I made.

So after you say this you still decide to make this PR because "the rifle has been in the game long enough"? How does that make undoing your compromise okay?

**Comment by Steelpoint** [comment]
At the time many people claimed the weapon would prove to be too powerful that it needed this restriction, amongst others, in place to limit it.

I think the weapon has proven itself to not be as crippling powerful as some people feared, thus I believe I can justify allowing bullet production for the weapon.

**Comment by FantasticFwoosh** [comment]
RnD can also still print ammo for a nanotren SMG that isn't printable anymore, i don't really see the objective point for this. Least you're not approaching this in a logical way by just adding it to often public autolathes.

> This feels like for lack of knowledge of other answers you're trying to fundamentally bend the game to have more bullet projectiles when nanotren is laser technologically focused. Relfective in how we only have two sets of bulletproof armor.

**Comment by Steelpoint** [comment]
The objective point is that the auto rifle is a case of a gun you can't print bullets for when a majority of projectile guns that the crew can get access to, even syndicate ones, can be printed. 

The crew can print off rounds for syndicate Revolvers, Sketchins and C20rs, but they can't print rounds off for a legal gun they can order from round start?

The gun is still very expensive to order and is not the be all, end all for in weapons. Combat Shotguns remain the go to Cargo weapon and lasers are very cheap to order and free to recharge en mass. Auto Rifles are a more niche weapon.

**Comment by FantasticFwoosh** [comment]
The problem is bullet production then, we were just talking about it on IRC since you helped raise the subject, if bullets were more out of reach via a bullet-lathe or special hacking functions on default autolathes, this wouldn't be such a obtuse problem.

> Detective asks the warden to print off some bullets at the brig desk from a preconfigured bullet lathe.

The critical problem i see here is that you've introduced a conceptual weapon piecemeal after compromising setback that is effectively incomplete without this PR to bring it to full. If people cared to actually own this gun which i have never seen the warden using they would just order the crates with no questions.

> Cut the power or physically destroy laser recharging stations with your melee weapon and lasers can't recharge and are rendered useless.

A bog standard pistol with a similar caliber to the detectives pistol would also get the job done of what the security sec-rifle does, even contraband guns in the locker that have a small chance to spawn are often good alternatives.

**Comment by Steelpoint** [comment]
I legitimately do not understand the point you are trying to make.

**Comment by Steelpoint** [comment]
I think me adding a bullet autolathe to the armoury would be a very resisted addition and is wholly not what I am trying to do.

People don't care to own the gun due to it both being very expensive to buy, and very expensive to resupply with ammo. The gun and spare ammo has to be bought separately. Whereas right off the bat Security spawns with laser guns, energy guns and riot shotguns, with the shotguns being free to resupply from cargo with extra shells.

That's why the Auto Rifle is rarely seen. FIrst you have to buy the guns, then you need to buy the magazines from cargo. When you run out you then need to buy more ammo at a premium cost, whereas if you use your Shotgun you can resupply for free.

Maybe if this addition goes through, the Auto Rifles will be more popular since you can get more ammo far easier and cheaper.

**Comment by FantasticFwoosh** [comment]
You have a gun you only really managed to shove 1 inside a locker of because the pr was unpopular and when you start the PR with...

> This was a conscious decision on my part due to the massive controversy that surrounded the addition of auto rifles to the game and that denying the rifles the ability to get more ammo printed was a compromise I made.

And now you need to actually give it bullets from a broken system where ammo is producible from **public** dispensaries. Which is feeding into the problem Instead of looking at existing assets like the Nanotren saber SMG ammo that is in science you could just change a few lines of code for to turn it into your security ammo type, and encourage the warden to contact science to provide ammo for a gun they cannot print to help the station securely.

Shotguns are better (beanbag shots down unarmored e-sworders in 2), pistols are better if not the same, the rate of fire of a machine gun is so controversially over the top you were only allowed to add one with one magazine to a singular job role's locker.

**Comment by Steelpoint** [comment]
I never added that auto rifle to the Warden's locker, that was metacide's doing. 

The NT Sabr is a direct upgrade to the Auto Rifle, while damage is consistent but it has a much larger ammo capacity and I kept that intentionally. 

I'm not debating the finer points of the rifle, I'm simply wishing to allow the crew to print off ammo for the gun like they can do for virtually any other gun in the game.

**Comment by FantasticFwoosh** [comment]
But this inclusionist rule is not enough to literally override your previous compromise because "**the system we supply bullets is bad, therefore I should be able to do this because.**"

**Comment by Steelpoint** [comment]
I never claimed the bullet production/supply system is bad. The compromise was put in due to me wanting to get the rifle merged and I felt that if I added that drawback it would increase the odds of me getting the rifle accepted and kept in the game at the time.

Don't forget that at the time people were, in protest, going out of their way to buy and murderbone with the weapon in a attempt to prove a point.

I believe that a sufficient amount of time has passed that the drawback I added is no longer required. The drawback was never really intended as a balancing mechanic, it was a true compromise to get the gun added in the first place in a climate of massive dislike towards the gun, more so since it was originally going to be a security issue armoury weapon, not the fact the weapon exists in the first place. 

--------------

If I were to re-do the scenario again, I would make the gun deal less damage, such as ten damage per bullet, but increase its mag supply to around 25 rounds. To promote the weapon as a more sprayer weapon that lacks the damage of energy weapons but compensates by more available ammo.

**Comment by FantasticFwoosh** [comment]
I thought you weren't going to discuss the points of the rifle in account to balance, you've just contradicted yourself with your 'scenario'. So you're admitting there is a problem with it but are still going through with this PR when you could just PR a secrifle nerf later today and get it more generally accepted by the community, and make it safer to do bullets from wherever later.

> What kind of reasoning is this?

**Comment by Steelpoint** [comment]
That was a off the cuff point I made in passing, I highly doubt people would accept a sec auto rifle even if I do nerf it.

This is what I get for debating when I'm tired.

**Comment by FantasticFwoosh** [comment]
You might believe this is a good time to do this, but backing it up with forum or even OOC opinion polls would be a good step. I personally have few opportunities or incentives to use a sec rifle regularly in the round whilst playing warden, and hence have a negative if bording on indifferent opinion on it.

You'd be suprised how people's attitudes change when people actually fix problems with features rather than hammer bad features home with DIY PR's, this PR seems to just make you appear kind of stubborn on the concept that only your opinion of the sec-rifles further development in the game matters.

**Comment by Steelpoint** [comment]
I'll mull the idea of a revised Sec Auto Rifle/Bullet Production over, I doubt it'll go anywhere.

**Comment by FantasticFwoosh** [comment]
Appreciate it, no hard feelings this is just Github business.

**Pull request closed without merging**
