### PR TITLE
Makes the CMO not the only person that has to suffer with their turtlenecks.

### PR DESCRIPTION
**Pull request by Draggeru**
## About The Pull Request

Moves the RD's and HOS's turtlenecks to the cargo order console to reside with the CMO turtlenecks. 

## Why It's Good For The Game

It is NOT fair that only the CMO has to go through this unnecessarily extensive process to obtain their turtleneck uniform when the other heads of staff with turtlenecks have said clothing items readily available. I would prefer to both have the turtlenecks be orderable and one set is spawned round start in the garment bag but the funny orange man said no.

## Changelog

:cl:
balance: Makes the CMO, RD, and Hos have to order their turtlenecks, instead of just the cmo.
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
+1 Good to keep consistency, doesn't make sense that one turtleneck is locked behind cargo

**Comment by Draggeru** [comment]
I HONESTLY want to add the crates and add the turtlenecks to the CMOS garment bag, because I hate losing my RD uniform. At least they can be re-obtained with this method.

**Comment by Serxule** [comment]
why not just, give the cmo their turtleneck? thats more mainstream when 2 other heads already have theirs.

**Comment by Draggeru** [comment]
> why not just, give the cmo their turtleneck? thats more mainstream when 2 other heads already have theirs.

Because oranges wont let me.

**Comment by kawoppi** [comment]
What if there was a basic turtleneck in the ClothesMate that you could color with GAGS to fit whatever department you want? Although that solution couldn't be used for the HOS one because it has armor if I remember correctly.

**Comment by Pinkufeck** [comment]
Why.

**Comment by Pinkufeck** [comment]
> What if there was a basic turtleneck in the ClothesMate that you could color with GAGS to fit whatever department you want? Although that solution couldn't be used for the HOS one because it has armor if I remember correctly.

GAGS suck.

**Comment by VladinXXV** [comment]
There's no reason to make things worse for the other heads. The CMO turtleneck is only the way it is because orange man said it had to be that way. I'd have much rather just put it in the garment bag like any sensible person would.

**Pull request closed without merging**
