### PR TITLE
Remove job change .dm files in favor of JSON changes

### LINKED ISSUE #39933: TODO: Remove all map_change.dm files and refactor what they do into the map jsons
Eventually we want to be able to load maps solely from the .json and .dmm at runtime alone

Will pay 10$USD if someone else does this

### PR DESCRIPTION
**Pull request by Cyberboss**
Used the .dm files [here](https://gist.github.com/SpaceManiac/3cf56dda8292be6aec65423f1333cfdd) as a test bed.

Closes #39933 <== literally free 10$ from me that no one took

Here's an example of what the new `job_changes` key in map jsons looks like
```json
{
  "job_changes": {
     "/datum/job": {
       "supervisors": "your mum"
     },
     "/datum/job/hop": { 
        "add_access": 47,
        "add_min_access": [47],
        "outfit": {
           "add_backpack": {
             "/obj/item/soapstone": 3
           },
           "var_changes": {
              "box": "/obj/item/storage/box/survival_mining"
           }
         },
         "var_changes": {
            "spawn_positions": 10,
            "total_positions": 20
         }
     },
     "/datum/job/captain": {
        "var_changes": {
          "access": [1,63,42,66,5,10,15,16,18,19,21,12,25,26,32,6,27,28,31,34,50,41,35,38,46,22,37,47,48,53,54,57,59,60,62,64],
          "outfit": "/datum/outfit/job/hop"
        }
     }
   }
}
```

### CODE REVIEW

**Review by AnturK — COMMENTED** [review]
Looks alright, just some nitpicks.

**Comment by AnturK** [comment]
Also could use a readme in map directory

**Comment by optimumtact** [comment]
@SpaceManiac @Cyberboss hello

**Comment by AnturK** [comment]
So what's going on here @Cyberboss

**Comment by Cyberboss** [comment]
Laziness, that's what

**Comment by SpaceManiac** [comment]
Code looks good just reading it but I've been too swamped to test it

**Comment by Cyberboss** [comment]
I still need to document the format as well

**Pull request closed without merging**
