### PR TITLE
Reading a newspaper conceals your identity

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

dreamseeker_T49SJcwCEf
While you are reading a newspaper with a free hand you will hold it up in front of your face and ID, rendering you as "Unknown" to anyone who examines you (although it does not conceal your voice).

If you don't have a free hand you can still read the paper but it won't do these things.
I don't want to have to care about the balance of people hiding a gun behind their newspaper, even if that is also pretty funny.

Inspired by a forum post:
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=35650

## Why It's Good For The Game

I think that it's pretty funny.

## Changelog

:cl:
add: Reading a newspaper will conceal your identity.
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]

**Comment by Xkallubar** [comment]
Rare coder making idea post real occurrence

**Comment by Singul0** [comment]
ideaguys, we are so back!! :)

**Comment by Jacquerel** [comment]
> Rare coder making idea post real occurrence

you can also thank the tgstation ideas subforum for tongs

**Comment by Likteer** [comment]
Muchas gracias, senor!

**Pull request merged**
