### PR TITLE
Adds "shiny" variants of lavaland mobs

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Common lavaland mobs now have rare mutations! Keep an eye out for rare Poke- err, monsters.
/:cl:

I feel as though the lavaland tunnels currently aren't that diverse and get samey to hunt through time after time, so I decided to spruce them up a little. Common mining mobs now have a 1% chance on initialize to gain a new appearance and potential new stats (this is 5% for legions.) The current mutations are below.

* **Watchers** become:
  * Magmawing watchers (75% chance) that have 15 more health and shoot scorching blasts instead of freezing blasts
  * Icewing watchers (25% chance) that have 50 less health and fire shots 33% more often, as well as dropping 5 diamonds and no sinew
* **Goliaths** become precursor goliaths, which use the old goliath sprite. They also drop the goliath hide directly (meat and bones are still through butchering) as an homage to the asteroid goliaths.
* **Legions** become dwarf legions, which have 20 less health but move slightly faster.

Feedback and suggestions welcome! This doesn't currently apply to megafauna.

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
As much as old goliaths sound nice for nostalgia, they look outdated for lavaland. Unless it's a super rare chance for them to pop up, I guess it's ok.

**Comment by Xhuis** [comment]
1% chance per goliath for them to spawn. It's definitely meant to be a "woah, what?" kind of thing.

**Comment by ExcessiveUseOfCobblestone** [comment]
will they drop special l00t

**Comment by Xhuis** [comment]
They don't currently, as I don't like having unique loot locked behind a very rare chance. I could maybe make the normal loot they drop be recolored though, i.e. magmawing sinew is colored orange.

**Comment by ExcessiveUseOfCobblestone** [comment]
it doesn't have to be something unique, maybe just more of the usual drops

**Comment by MMMiracles** [comment]
Should also have legion check for the dwarfism trait when turning people, so the dwarf legion description isn't just fake fluff.

**Comment by Arianya** [comment]
Did you check to see if lazarus injectors revive them as their shiny selves or base selves

**Comment by Arianya** [comment]
Asking for a friend who wants a pet dwarf hivelord

**Comment by Armhulen** [comment]
Hivelords will drop bodies, right?

**Comment by Xhuis** [comment]
@Arianya Lazarus injectors revive them as shiny, yeah.
@Armhulen Due to how legions work, they don't leave behind corpses, no; they leave behind a human mob.

**Comment by Kromgar** [comment]
@Xhuis maybe you could make shiny mobs drop monster organs. That have to be surgically installed imagine your trying to assassinate the captain when suddenly he shoots a scorching or freezing blast from his eyes/mouth! Or you find out he's extremely resistant to brute damage due to a goliath exoskeleton.

**Comment by Bawhoppen** [comment]
Rename the special goliaths to something else, as it stands they're not really a mutation/variant, but an entirely different creature

**Comment by DoctoreMad** [comment]
I don't know the feelings of everyone else here but I'd rather have those as just unique "Oh that's cool" monsters instead of special loot bags.

**Comment by Iamgoofball** [comment]
hold the phone, lemme get the actual shiny chance

**Comment by Bawhoppen** [comment]
it's like 1/9128 or something

**Comment by DoctoreMad** [comment]
Actually it got higher lately because of tricks like mating pokemon that have different language settings causes a higher chance of a shiny appearing.

**Comment by DoctoreMad** [comment]
Of course I realize I will be thrown at the stake for mentioning something past gen 1

**Comment by Shadowlight213** [comment]
That, and there's the shiny bangle for filling up the national pokedex that increases the chance as well.

**Comment by Arianya** [comment]
If you wanted a non-balance upsetting difference, could make shinies have a higher/certain chance of dropping Kinetic Crusher trophies, since hunting rare/albino animals has a long history.

**Comment by RandomMarine** [comment]
Classic goliaths should have classic stun-on-`crossed()` tentacles.

**Comment by Grazyn** [comment]
>Classic goliaths should have classic stun-on-crossed() tentacles.

"Woah" =/= "Why am I dead?"

**Comment by FantasticFwoosh** [comment]
Shiny and/or unique mobs like this if they don't drop anything different inherently should insta-spit out 2 necropolis charges (for ashwalkers) because they are sacred animals. (or some fluff)

These mobs do have a high likelyhood otherwise of completely wrecking ashwalkers.

**Comment by DoctoreMad** [comment]
>Classic goliaths should have classic stun-on-crossed() tentacles.

The goliaths will always put the empty spot of their + on a area with a wall on it.
I legitimately guarantee it. It will happen every single time.

**Comment by Ergovisavi** [comment]
To be fair, that's why you can instantly mine that tile out with your mining tool. If you were dumb enough to waste your shot instead of baiting the attack, you got punished for it.

That said, the old crossed() functionality shouldn't come back though, lava land emphasizes free movement too much for that to be a thing and we have visual language problems if they're reintroduced.

:+1: On this change, I suppose.

**Comment by Xhuis** [comment]
Shiny mobs now have an additional 1% chance to drop crusher trophies, as a small side bonus!
Additionally, humans with dwarfism will appropriately become dwarf legions when infested.

**Review by Cyberboss — APPROVED** [review]

**Comment by AnonymousNow** [comment]
This sounds like fun, and I'd like to see similar additions in the future.

I miss Basilisks, to be honest.

**Comment by Ratvar** [comment]
Hulk Legion that smashes you down with 20brute melee punches instead of running away?
Overgrown legion skull that can float over lava, chasms and infect corpes into legion on his own without dying?
Stealthy Marrow Weaver with colours of ash floor that has low health?
Thendrill that uses goliath tentacle attack to defend itself? Thendrill that stunlocks anyone walking near in melee range and spawns more such thendrills on kill? No spawning mobs, but if anyone runs near with something giggly on his tail-ded.
Ashwalker thendrill without lavaland base? Make them into enemy of base ashwalkers, aka gang/vs/gang teamfights.
Thendrill that spawns slowing down meaty floor resin around it? Chance to drop resin sack alien organ?
Marrow that draws nutriniment from you on hit, forcing you to eat lava cooked goliaths to regain speed?
Brass watcher that attacks you with burn damage for as long as you see it, slowly, and has a chance to drop brass tools?
Lava watcher that lives only in rivers and throws chl3 shards that ignite?

**Comment by DoctoreMad** [comment]
(I haven't played Miner lately but) All lavaland mobs can already pass lava.
Its tendril not thendrill.

For everything else, calm down.

**Comment by AnonymousNow** [comment]
Wild idea making is fun to do and fun to witness.

**Comment by KorPhaeron** [comment]
Down the slippery slope into even sillier lore for lavaland but the gameplay sounds fun

**Pull request merged**
