### PR TITLE
Blocks Proto-Nitrade/BZ Reactions from occuring inside pipes.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Closes #65212

## About The Pull Request

Fixes being able to irradiate the station via pipes, the other PR kicks the can down the road while this PR definitively stops the issue.

## Why It's Good For The Game

It's like being back in old radiation all over again

## Changelog

:cl:
fix: Fixes irradiating the entire station via pipes.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
Why block the whole reaction rather than just the radiation?

**Comment by Iamgoofball** [comment]
If the radiation is supposed to be a byproduct of the reaction it'd be weird if you could make the reaction effect but minus the radiation by using pipes as a cookpot.

**Comment by Pickle-Coding** [comment]
Could just make the location null or something if it's a pipenet and not release radiation if it's null. This doesn't solve the other proto nitrate response reaction either, and doesn't solve tritium fires (people could do that but they simply haven't yet).

**Comment by MacBlaze1** [comment]
This probably wouldn't be too bad, considering waste radiation is a pain in the ass and has no tangible benefits except making atmos techs careful enough to not get plasma into waste.

**Comment by Ghilker** [comment]
This is the issue with new rads, you can't tweak the strength of the pulse.

Before you could've just divided the pulse strength by the size of the pipenet so that big ones released negligible amounts, but new rads don't allow that.

**Comment by LemonInTheDark** [comment]
I don't think it's worth being this heavy handed with it, especially since turbo is working on a fix. If it fails and none can think of anything else it'd be feasible, but the guy's trying to do something, I don't think it's bad to accommodate that

**Comment by LemonInTheDark** [comment]
Closed in favor of https://github.com/tgstation/tgstation/pull/65212

**Pull request closed without merging**
