### PR TITLE
oxigen dangerous at high partial pressures

### PR DESCRIPTION
**Pull request by Ghilker**
### Warning before putting the downvote read the PR
This is a little change that won't affect much of the gameplay of spessmen, what this does is make o2 dangerous if breathed at over 50 kpa (the number is in partial pressure). This means that atmosians can't just refill a room with only o2 and call it a day, but they have at least to put some effort and put an inert gas (n2) to lower the p.p. of o2 (making air in the room). 
No, breathing thanks are not affected, you can still breathe pure o2 regulated to 16-49 kpa.
_The change to mob/living/carbon/life.dm where i added the n2 to the assert gases is to fix a weird thing that was happening with air tanks where the composition in % of the mix was changing over time since n2 wasnt getting breathed at all_ nevermind all of this

## Why It's Good For The Game
Make air great again

## Changelog
:cl:
add: O2 is toxic if breathed at a partial pressure of over 50 kpa (o2 tanks are still fine don't worry)
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
based?

**Comment by Ghilker** [comment]
very much

**Review by ghost — CHANGES_REQUESTED** [review]
humans breathe using lungs and dont run this proc, please test PRs :^(

**Comment by Ghilker** [comment]
well nevermind life.dm then, just the lungs.dm change for humans

**Comment by Ghilker** [comment]
nevermind, closing this. i'm blaming the bad 1AM pr man for making me doing this

**Comment by LemonInTheDark** [comment]
Nightcode man good

**Pull request closed without merging**
