### PR TITLE
Updates the soapstone sprite

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard
imageadd: cheetos have been removed from the game.
/:cl:

old:

new:

to the people who are downvoting I ask:

Please explain how the original sprite is better. It literally looks like a cheeto. It's supposed to be a chisel. Also I have no idea what the rope-looking stuff at the top is.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
It's a dark souls reference.

**Comment by Tacolizard** [comment]
@ChangelingRain well it does a terrible job of looking like its reference material

**Comment by Chronitonity** [comment]
this just looks like a shitty baseball bat/something you'd put in your ass

**Comment by ChangelingRain** [comment]
[I mean it doesn't, really](darksouls.wiki.fextralife.com/Orange+Guidance+Soapstone)

**Comment by Kromgar** [comment]
@Tacolizard give up this is never getting merged

**Pull request closed without merging**
