### PR TITLE
3/4-ify SM shard

### PR DESCRIPTION
**Pull request by MTandi**
image

## About The Pull Request

Adjusted the SM shard sprite to look 3/4.

## Why It's Good For The Game

Not flat.

## Changelog

:cl:
image: SM shard sprite updated
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
For completeness, can you show it in-game?

**Comment by lessthnthree** [comment]
Looks good, just I think the crystal needs to be 3/4 too. Looks like a flat crystal on a 3/4 base.

**Comment by Jackal-boop** [comment]
I wanna take a bite of it

**Comment by Bawhoppen** [comment]
A 2023 3/4ths sprite PR that doesn't suck?
People claimed it was impossible...

**Review by ZephyrTFA — APPROVED** [review]
I'm not a spritetainer but I like this

**Comment by MTandi** [comment]
> For completeness, can you show it in-game?

image

>Looks good, just I think the crystal needs to be 3/4 too. Looks like a flat crystal on a 3/4 base.

image

I tried, but it looked like shit, so I decided to leave the original crystal, just adding volume by shifting the bottom. Looks volumous to me.

**Comment by Jolly-66** [comment]
I like the detail of the old, is there any way you could try to reincorpeare that in the new sprite? New one feels a lil flat

**Review by Wallemations — APPROVED** [review]

**Comment by MTandi** [comment]
> I like the detail of the old, is there any way you could try to reincorpeare that in the new sprite? New one feels a lil flat

It didn't look good when I tried

**Pull request merged**
