### PR TITLE
Pen click sound

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request

https://github.com/tgstation/tgstation/assets/96586172/c9561de7-bae1-4c00-a57c-eb5ae030ee85
## Why It's Good For The Game
The previous sound didn't fit at all.
## Changelog
:cl: grungussuss
sound: pen click now has a proper sound
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
why have it vary instead of having a different sound for extending it and retracting it

**Comment by Sadboysuss** [comment]
> why have it vary instead of having a different sound for extending it and retracting it

extending and retracting a pen sound the same

**Comment by SmArtKar** [comment]
click click click
sounds great

**Comment by JohnFulpWillard** [comment]
pens dont sound the same what no way

**Pull request merged**
