### PR TITLE
Fixes black carpet sprites.

### PR DESCRIPTION
**Pull request by WJohn**
Black carpets had a nasty black line on vertical slices from being too long. This fixes that. It also makes regular catwalks have opacity so there aren't a million holes with which to accidentally click on space with.

:cl: WJohnston
imageadd: Black carpets no longer have an ugly periodic black line in them. Regular catwalks are now totally opaque so you won't accidentally click on space when trying to place wires or tiles on them.
/:cl:

### CODE REVIEW

**Comment by CPTANT** [comment]
Actually you often need to press the space tile beneath a catwalk.

For example to place a floor with a RCD.

**Comment by WJohn** [comment]
Why not have it where you can use the RCD on lattice/catwalks and still have it work, then? I'm not able to code that myself, however.

**Comment by CPTANT** [comment]
I would actually very much like that.

**Comment by duncathan** [comment]
@CPTANT until then just alt click

**Pull request merged**
