### PR TITLE
Watcher wreaths; Normal and Icewing varieties

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Adds Watcher Wreaths. An item that makes it look like you have a slightly floating thorn crown that you can make from some of their material parts (and the icewing crusher trophy for the icewing variant).

The wreath has emissives. They don't do anything mechanically, they're just for show.

wreath

image

image

## Why It's Good For The Game

I really like the whole thing with turning lavaland monsters into trophies and cosmetics. Going down and coming back up looking like someone who just crawled through a horror movie and took some souvenirs is great. Stuff like the trophy accessories, bone and drake armor and many of the various lavaland items have this quality, and it always amuses me when a tech sees a dressed up miner and just goes 'holy shit, where did you get that'?

Drip is the ultimate reward for playing miner. Nobody can tell me otherwise. this is the endgame every miner craves. And I crave a goddamn crown made from the broken remains of my enemies.

## Changelog
:cl:
add: Watcher wreaths. Made from the mangled remains of a watcher, now a handsome accessory for you to wear a few inches behind your head. Comes in Normal and Icewing variants.
add: Some bounties for the two variants of watcher wreaths.
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
> [drip] is the endgame every miner craves.
This is the truth and I'm glad we're getting more to slave away for. It's PEAK!

**Comment by the-orange-cow** [comment]
Probably outside the scope of this PR, but it would be cool if watchers became friendly to people wearing these.

**Comment by necromanceranne** [comment]
Personally, I think it should make them angrier. They're already so ornery, and you're wearing their fellow watchers as an accessory.

**Comment by newfren** [comment]
as a crusher user this won't actually be a problem for me, but it's kind of annoying to not be able to craft these at all without using the crusher

**Comment by MercuryArrow** [comment]
> as a crusher user this won't actually be a problem for me, but it's kind of annoying to not be able to craft these at all without using the crusher

The crusher requirement doesn't bother me personally as Watchers are probably easier to take down than even legions after the basic AI changes, but another potential avenue for people who don't want it tied to the crusher but still preserving an element of rarity would be to tie it to the butchering bonus mechanics so it requires a certain butchering score on the tool used to have a chance of dropping - can't be cutting off those delicate arterial wings with a shard, after all.

**Comment by Fikou** [comment]
VGHHHHHHHHHHHHH

**Comment by necromanceranne** [comment]
I removed the wing requirement for the basic wreath

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
