### PR TITLE
Shadowpeople heal more in the dark

### PR DESCRIPTION
**Pull request by ghost**
Shadowpeople are so much worse than podpeople it's almost insulting. They're one of the hardest races in the game to acquire requiring end game xenobiology, cooperation from either cargo or the chaplain and chemistry. They have to sabotage their own workplace to live in it and their healing doesn't give them nutrition like pod people do. SPEAKING OF POD PEOPLE, pod people require either green slime and something from the botany dispenser, heal all damage types in the LIGHT, don't burn in the darkness and they don't get hungry ever. I was considering giving shadowpeople a spell that damages them but fires a bolt of darkness at other people. Might be fun, but that sounds like a lot more of a balance headache than this.

### CODE REVIEW

**Comment by Armhulen** [comment]
They're commonplace now, but when halloween ends they'll go back to the sad sack of shit race that is never used.

**Comment by DoctoreMad** [comment]
>I was considering giving shadowpeople a spell that damages them but fires a bolt of darkness at other people

Oh great more characters that can "control the darkness"

**Comment by Armhulen** [comment]
thats why i didn't do it

**Comment by XDTM** [comment]
could go overboard and give them armor/stun reduction while in darkness

**Comment by Armhulen** [comment]
i could

**Comment by Armhulen** [comment]
since reminder you need dark matter holy water and advanced mutation toxin to create these
and you can get only slightly weaker (BUT DON'T NEED TO LIVE IN DARKNESS) races using less time

**Comment by Armhulen** [comment]
shadowpeople are...
don't breathe
no blood
rad immune
virus immune
they heal the same as pod people but only half of the damage types

you need holy water, stable reagent plus dark matter and advanced mutation toxin

**Comment by Armhulen** [comment]
pod people are...
heals all four types of damage in the light
never gets hungry in the light

they can be made 5 minutes into the round or if you're paranoid they're **NORMAL TOXIN** AND PLANT FOOD

**Comment by JJRcop** [comment]
Want to bring up #31912 for your attention

**Comment by Armhulen** [comment]
slightly more healing and it's a race earned from killing a nightmare i don't see anything terribly wrong

**Comment by KorPhaeron** [comment]
This is probably more of a nerf overall, 4 damage a tick is brutal and going to kill you way more often than the healing will save you

**Comment by Armhulen** [comment]
3,3 is really strong healing, so

**Comment by KorPhaeron** [comment]
In most scenarios where someone is trying to kill you they will

A) Have a light so you will be taking 4 damage a tick instead 

B) Be using a single damage type, so even when you somehow are fighting in the dark its only 3

C) Will probably just stun you anyway

This will mostly just get more nightmares killed when they tumble through a wall into a lit room and shadowpeople more fucked up by incidental flashlight damage

I agree shadow people are boring right now, just dont think this is the way to make them better

**Comment by Armhulen** [comment]
i could turn the damage per tick down to 1,1, or, if you have any other ideas i'm all ears

**Comment by Bawhoppen** [comment]
The best balance changes aren't usually from changing numbers around, but are from dynamic mechanical changes

**Comment by Armhulen** [comment]
I was considering giving shadowpeople a spell that damages them but fires a bolt of darkness at other people
Oh great more characters that can "control the darkness"

**Comment by Armhulen** [comment]
people don't want that i guess

**Comment by DoctoreMad** [comment]
It was a joke
(Though I'm not for the darkness beamo, why are you making a combat mechanic? That would be silly as dullahan 25 brute head throws.)

**Comment by DoctoreMad** [comment]
Aaand then I realize my complaint of giving races random pro-combat mechanics is silly because of the codebase I'm in
Whatever then

**Comment by Armhulen** [comment]
hey if you got an idea shoot

**Comment by DoctoreMad** [comment]
Well first thing is that they're messing with shadow, why not go all the way with light/shadow manipulation?
Press a button to spawn a item on your hand, its based on the darkness of the area you are in. If you're in a bright area, it'll spawn a orb that radiates light in a rather large radius(About seclite tier). If you're in the dark, It'll generate a orb that is VERY good at impeding surrounding light, allowing you to walk hallways for a bit in case a problem arrives.
As a bonus, maybe make it so the new shadowlings can't break created light orbs? It would make shadows more useful to security.

Give it a cooldown that doesn't let you have a orb 24/7 of the time up while you're at it.
Should be simple since the item is just a flashlight with a timer.

**Comment by Armhulen** [comment]
i kinda like it sure

**Comment by PKPenguin321** [comment]
isnt this supposed to be a penalty species that you'd get for making an evil wish

**Comment by JJRcop** [comment]
Maybe podpeople need a nerf instead?

**Comment by Cyberboss** [comment]
changelog

**Comment by DoctoreMad** [comment]
>i kinda like it sure, dunno what they'd be doing with light orbs though.

Sometimes you do things for other people. Shadowpeople themselves have no use for a light orb.

**Review by Cyberboss — APPROVED** [review]

**Comment by KorPhaeron** [comment]
@Armhulen I dunno yet I'll try to think of something !!FUN!! though

Someone (robustin?) suggested letting them make a black smoke cloud at some point, maybe that

**Comment by Anonmare** [comment]
Why not let them make a cocoon like shadowlings used to prior to hatching? As an emergency way of healing in darkness

**Pull request closed without merging**
