### PR TITLE
New Fox Sprite

### PR DESCRIPTION
**Pull request by ghost**
I created a new fox sprite over the last two days with the guidance of WJohnston (thank you):
new fox9 big
_(The above is no longer in the file)_

It's designed to replace this old one:
fox big

How much do I care? Enough to have 14 iterations of this fox, here's the newest one I think is fit for purpose:
new fox14 big
_(The above is no longer in the file)_

**_New again!_** Fixed the outline of the one above because grawr too dark:
new fox some number

### CODE REVIEW

**Comment by ike709** [comment]
:+1:

**Comment by Nienhaus** [comment]
I just made this new one.
nsboquq

**Comment by ike709** [comment]
I like the OP's better Nienhaus

**Comment by Fox-McCloud** [comment]
This has a lot less detail on it than Niens----furthermore, it gets a few colors wrong--for instance, the ears.

also, ditching whiskers :-1:

**Comment by Supermichael777** [comment]
looks more like our curent pets like ian :+1:

**Comment by Lumipharon** [comment]
Uptail looks cuter.

**Comment by PKPenguin321** [comment]
the head looks noticeably more rectangular when facing forwards and back

**Comment by Dorsisdwarf** [comment]
Sprite looks disgusting and oversaturated

**Comment by CosmicScientist** [comment]
@Fox-McCloud it'd be nice to know what other colours are wrong too so I might be able to fix it.

@Lumipharon sorry.

@PKPEnguin321 I'll see if I can sort that.

**Comment by Dorsisdwarf** [comment]
The same color as the fox currently is. 

Or if you have a really strong desire for light-haired foxes, the colors of Nien's second version

**Comment by CosmicScientist** [comment]
Alright I'll try putting a darker shade on it then and put a preview up for that.

**Comment by Core0verload** [comment]
:-1:

**Comment by Fox-McCloud** [comment]
@CosmicScientist 

For one, the ears need to be darker than the rest of the body; whatever color you decide to make their legs ears needs to be the same colors.

Literally the only thing I like better about your sprite is that the legs are black, over brown.

**Comment by CosmicScientist** [comment]
@Core0verload could you say why? I'm getting lovely feedback from everyone else.

**Comment by pudl** [comment]
This sprite is awful. :-1:

**Comment by optimumtact** [comment]
:+1: we don't have enough resolution to do good whiskers, so they make a sprite look shit. OP has done a good job with the limited space

I also like the brighter colours.

**Comment by CosmicScientist** [comment]
Second version is shown at the top (third image down).

@optimumtact thank you (for the first one, here's hoping I didn't wreck it with the second one) and also thank you for putting into words what I couldn't about adding whiskers.

**Comment by CosmicScientist** [comment]
I do have a slight niggle, I don't really know if the harsh line on the back end just above the tail is... good. I have a mock up of what it could be:
Image of Fox

**Comment by pudl** [comment]
it still fucking sucks

**Comment by CosmicScientist** [comment]
@pudl what excellent feedback you offer.

**Comment by Fox-McCloud** [comment]
The back line, I agree, is a bit harsh---colors are a hair bit light, but the details are better.

Still want dem whiskers--but the style of this sprite doesn't lend itself to that being applicable.

**Comment by pudl** [comment]
it still lacks the detail and actual talent of nien's (remade) sprite. literally just remove the whiskers from his and it would be perfect. yours is bright, ugly colors, awful anatomy, and absolutely no actual gradient from fur color to fur color. it's a product of lack of skill

**Comment by duncathan** [comment]
>gradient
>low-res pixel art

@pudl at least try to pretend you know what you're talking about

**Comment by pudl** [comment]
Look at Nienhaus' sprite, in the exact same dimensions, and tell me that there isn't a gradient there from white to black.

**Comment by CosmicScientist** [comment]
I'm pretty much finished with this now.

**Comment by WJohn** [comment]
Well it's better than what we have now, I'm fine merging this. If someone else like nienhaus wants to update the sprite again, go ahead.

**Comment by Nienhaus** [comment]
Naw I'm good. If someone wants to go out of their way feel free.

**Pull request merged**
