### PR TITLE
[WIP] Organ Damage System/Refactor

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard Forever
refactor: Organ damage has been refactored.
/:cl:

WIP pr to make all organs share the ability to be damaged, with common procs for working with organ damage, to reduce snowflake code used for handling organ damage. posting here so i can dodge the freeze and get help with stuff, as well as direction from members as to how this should be designed.

This PR will also move a lot of organ handling stuff from carbon\life.dm onto their respective organs.

potential of this PR:
- we could implement internal organ damage from combat, which is something I've heard that lifeweb does. 
- it will be really easy to create new organs with damage mechanics
- organ damage can be modified and interacted with in a fairly uniform way for all organs

this will need a lot of testing when finished

todo:

- [x] fix compile errors
- [ ] port existing organ damage systems to new system
- - [x] liver
- - [x] ears
- - [ ] eyes
- - [ ] brain
- - [ ] heart
- [ ] refine new system
- [ ] test locally and fix runtime errors
- [ ] clean up code (remove commented out code, etc)
- [ ] get testmerged, test for bugs

### CODE REVIEW

**Comment by kevinz000** [comment]
besure to test

**Comment by Tacolizard** [comment]
1 5 0 H O U R S

**Comment by XDTM** [comment]
Brain should be straightforward enough

**Comment by Tacolizard** [comment]
yeah i think porting should be easy, there's just a ton of testing to do. I'll work more on this tomorrow

**Comment by BeeSting12** [comment]
arent you the guy that broke livers that one time? if so i have full faith in this code

**Comment by Spaceinaba** [comment]
add kidneys so I can do the classic movie attack where you KIDNEY PUNCH KIDNEY PUNCH KIDNEY PUNCH

**Comment by Tacolizard** [comment]
@BeeSting12 I'm the guy who created livers

😎

**Comment by Tacolizard** [comment]
closing this pr for a couple of reasons

1. brains have an ungodly amount of procs for getting and setting damage, and the math is pretty confusing and I'm worried I could never port it correctly, especially because the new system I implemented keeps track of damage, but brains were designed around keeping track of integrity.

2. there's no point in implementing a new damage system specific to organs, if instead I could just use the existing obj_integrity system, it would be much easier.

i may end up making a new pr that does something similar to this, except based on obj_integrity.

**Pull request closed without merging**
