### PR TITLE
removes nuclear emergency

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I'm helping

### CODE REVIEW

**Comment by optimumtact** [comment]
STOP IT

**Comment by TehZombehz** [comment]
I joined as security and it turned out there were nuke ops and I didn't want to do it so like remove nuke ops okay

**Comment by optimumtact** [comment]
How about a nice github ban instead.

have a nice day

**Comment by FantasticFwoosh** [comment]
least replace it with something else.

**Pull request closed without merging**
