### PR TITLE
Removes Revenant scriptures entirely

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Removes Revenant scriptures entirely.
/:cl:

These are the win more scriptures. You use them only while winning, and they cause you to win more than you already were.
That sucks. Clockcult doesn't need to win more if it's already winning.

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Were winning so much were gonna get sick of winning. 2017

**Comment by obscolene** [comment]
itt: joan removes a feature that literally nobody uses, ever, so she can buff clockcult with no downsides

**Comment by KingPhilipIII** [comment]
Actually I've seen plenty of cultists use Revenant scriptures to really finalize things. Global hallucinations and brain damage is nothing to blow off, nor is invulnerability during a seccie raid.

**Comment by DoctoreMad** [comment]
Shhh in the actual game revenants were supposed to be summoned as actual player character things.
Now if that got added in the state clockwork cult is in(IE: Buffed to fuck), then they would REALLY win every time.

**Comment by Armhulen** [comment]
Time to make clock cult into blood cult 2

**Comment by KingPhilipIII** [comment]
Well. I mean people constantly bitch about what's wrong with clock cult, a lot of which being where it diverges from blood cult.

I guess Joan is just giving the masses what they want.

**Comment by Robustin** [comment]
The effects were all fairly balanced and unique but I agree, they need to be worked in elsewhere, if at all, there wasn't a single round where I cast a revenant scripture that didn't end with an easy CC victory.

**Comment by ShadowDeath6** [comment]
Replace all the scriptures with one that just summons a revenant that can't use any abilities except for overload lights

**Comment by Grazyn** [comment]
It's funny because this is actually a buff. Revenant scriptures are useless, but there are always one or 2 newbs that use them and waste components, thus delaying or even jeopardazing cult victory.

**Comment by Kromgar** [comment]
Secret buff because now you just need to get where revenant used to be to summon var rat

**Pull request merged**
