### PR TITLE
removes cardboard golem's wanker cramp arm (resprites the massive right arm to be smaller)

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

cardboard golem has one HUGE arm that is really ugly, i removed it

## Why It's Good For The Game

what, you don't know what wanker's cramp is? we obviously live different lifestyles then. ok but seriously it does not look good

## Changelog
:cl:
imageadd: changes some things around with the cardboard golem limb sprites
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
SOULLESS

**Comment by trollbreeder** [comment]
Error 666
No soul found
Please enter soul to continue and merge

**Comment by ExcessiveUseOfCobblestone** [comment]
IM GONNA

IM GONNA

IM CARDBOOODING

**Comment by MrDoomBringer** [comment]
Its a cardboard golem. let them be clunky and misshapen as if they were made out of a box (rather than a skintight cardboard suit shaped exactly like a human)

Also, did you try to see what this would look like ingame? from your sprites it seems like the directions are messed up.

**Comment by tralezab** [comment]
doombringer is probably right, even if i can't stand it maybe that's the point and all that

**Comment by ExcessiveUseOfCobblestone** [comment]
right about the sprite design or not seeing how they look ingame 😏

**Pull request closed without merging**
