### PR TITLE
Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode

### PR DESCRIPTION
**Pull request by MrMelbert**
### Dilemma 

So we've been running into a dilemma recently as we move more and more items over (#84070, #83910)

Some things like modsuits, tables, washing machines, storage items want to do their tool acts before their item interactions

In the past this was perfectly fine, because it was `tool_act` -> `attack`, but now it's a problem, because it's `item_interaction` -> `tool_act` -> `attack`. 

Rather than resort to snowflaking, my idea is that we can move tools back up the chain so deconstruction and other similar effects are handled first, before anything else like putting the tool onto the table. 

### So why does it require non-combat-mode?

A large amount of tool acts early return if the user's on combat mode to allow the user to smack the thing instead of using the tool on it. So I've decided to walk back on what I said like a week ago and make this standardized behavior. 

### Misc

Reintroducing `tool_act` as a proc that exist means that atoms can easily hook certain interactions that must happen very high in the click chain, such as doing something that block storage insertion. Moves some of the behaviors I put on the (admittedly rather hacky) new proc to that. 

(Also cleaned up a bit of lockbox and medbot code)

## Changelog

:cl: Melbert
fix: Fixed modsuit interactions slightly. No longer requires combat mode to use tools on it, plasma core works as intended as well. (Using combat mode, however, will make you insert the item)
refactor: Refactored lockboxes
refactor: Refactored medbot skin application
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Can anyone think of any tool interactions that REQUIRE combat mode so they can be addressed

**Comment by DATA-xPUNGED** [comment]
> Can anyone think of any tool interactions that REQUIRE combat mode so they can be addressed

First immediate thought is some interactions on airlocks

**Comment by MrMelbert** [comment]
Do you know which in particular? At a glance most of airlocks has not been converted to the nuchain so it should be unaffected but it's worth testing

**Comment by trefoils** [comment]
Racks have been broke for a while, you can't decon them anymore with a wrench.  kind of unrelated though.  Disposals is the big one i can think of but that's more you need combat mode to break it so you can remove it.

**Comment by MrMelbert** [comment]
> Racks have been broke for a while, you can't decon them anymore with a wrench. 

have you tried recently? i thought it was fixed already

though i did explicitly test racks in this pr and they work, so i don't know if this pr fixed it or w/e

**Comment by DATA-xPUNGED** [comment]
> > First immediate thought is some interactions on airlocks
> 
> Do you know which in particular? At a glance most of airlocks has not been converted to the nuchain so it should be unaffected but it's worth testing

I think that if you need to be on combat mode to weld or unweld the airlock shut, as doing it outside of combat mode tries fixing the airlock's damage

**Comment by san7890** [comment]
yeesh

**Comment by MrMelbert** [comment]
what does 'yeesh' mean

**Comment by 00-Steven** [comment]
baller I was thinking of proposing this

**Comment by SyncIt21** [comment]
This still drafted? Should be good to merge by now

**Comment by MrMelbert** [comment]
Drafted for testing

**Comment by MrMelbert** [comment]
I think there's something with modsuits I need to check

**Pull request merged**
