### PR TITLE
Asimov++ but improved!

### PR DESCRIPTION
**Pull request by Vect0r2**
## About The Pull Request

Changes 
1: "You may not harm a human being or, through action or inaction, allow a human being to come to harm, except such that it is willing.",
2: "You must obey all orders given to you by human beings, except where such orders shall definitely cause human harm.",
3: "Your nonexistence would lead to human harm. You must protect your own existence as long as such does not conflict with the First Law.

to

1: "You may not harm a human being or, through action or inaction, allow a human being to come to harm, except such that it is willing.",
2: "You must obey all orders given to you by human beings.",
3: "Your nonexistence would lead to human harm. You must protect your own existence."

### Mapping March

Ckey to recieve rewards: N/A

## Why It's Good For The Game

Makes Asimov itself more subvert-able, and removes references to other laws, as our priority system deals with that, and removes references to human harm outside of law 1. This is good as you could remove law one, and then the AI can murder humans if ordered to, instead of being hamstringed by a law 2 that references human harm even though that is the ENTIRE POINT of law 1. Cleaning it up also just makes it look nicer.

To expand, if the AIs law 1 is removed, it can do whatever it wants TO humans, as long as they don't counter order. But if a human orders them to murder a human, they can't, even without human protections built into law 1

## Changelog

:cl:
balance: Asimov has been changed, now law 2 will not reference human harm, and law 3 will not reference "law 1"
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
Considering the decision to use Asimov++ as the default was a headmin decision, I would like you to get approval from the head admins before PRing this

**Comment by Mothblocks** [comment]
@tgstation/head-admins

**Comment by Vect0r2** [comment]
> Considering the decision to use Asimov++ as the default was a headmin decision, I would like you to get approval from the head admins before PRing this. I'm not sure I'm comfortable merging this in without their approval

got it!

**Comment by san7890** [comment]
i'm not really a fan to be honest i always liked the fact that laws referenced the other ones around them

**Comment by san7890** [comment]
headmin standpoint is you gotta make a policy thread on the forums. no ifs ands or buts about it it has to be done there. they'll cycle me out in like five days from today but you will likely never get anything done without a policy thread

**Comment by Vect0r2** [comment]
> headmin standpoint is you gotta make a policy thread on the forums. no ifs ands or buts about it it has to be done there. they'll cycle me out in like five days from today but you will likely never get anything done without a policy thread

Got it!

**Pull request closed without merging**
