### PR TITLE
Holodeck Upgrades [MAP]

### PR DESCRIPTION
**Pull request by SuperSayu**
The holodeck code has been updated.  These upgrades can allow multiple holodecks on the same ship, or different holodecks on different maps.  Holodecks also allow machinery and draw power; the power is drawn from the APC that powers the holodeck control computer, rather than needing its own.  Area copy code is also slightly improved.

Holodeck area types (the alpha holodeck has been renamed /area/holodeck/rec_center) are used to get a list of available programs, eg, /area/holodeck/rec_center/dodgeball, /area/holodeck/rec_center/basketball, etc.  These areas are only added to the computer if they are mapped when the holodeck initializes (at roundstart), so if areas are defined in code but mappers remove stuff them Z2, it will not show up broken on the computer.

This does not go so far as to make constructable holodeck computers, much less building holodecks from scratch.

I also added four additional programs, pictures later.  They are:
- The classic lounge (quiet sitting room with card tables)
- The pet center (spawns a bunch of harmless pets)
- The emergency medical center (Some various medical machines, beds, and a surgery table - note that these holo-weapons do stamina damage unless the holodeck is emagged)
- Emag only: The holdout room (Foamed metal and glass wall on the entrance, a set of laser guns, and a couple rechargers)

In native Sayustation code I added another holodeck on top of the theater, which contained a bunch of floors for the theater staff.  With the map transition things, I am pretty sure you can now add non-connected z-levels aside from 2, and put holodeck stuff there for each map.  You could also put holodecks in, I dunno, xenobiology, security (coutroom / shooting range / more cells / meeting room / syndicate evilroom).  Just thoughts off the top of my head.

### CODE REVIEW

**Comment by Niknakflak** [comment]
:+1: I'm obsessed with holodeck stuff, I love it and I like this!

**Comment by WJohn** [comment]
Dude map merger, come on.

**Comment by PKPenguin321** [comment]
>The emergency medical center (Some various medical machines, beds, and a surgery table - note that these holo-weapons do stamina damage unless the holodeck is emagged)

do the medical machines actually function? can you do real surgery with fake tools?

**Comment by Zilenan91** [comment]
Can you take the equipment out of the holdout room?

**Comment by Dorsisdwarf** [comment]
probbably not

**Comment by Jalleo** [comment]
Emagged stuff can be taken out

**Comment by SuperSayu** [comment]
I did use the map merger, then I had to pull to fix conflicts and I failed to do so the next time around.  I will fix it this evening.

Emagging makes things not disappear when they leave, but they will disappear when the program changes or the holodeck loses power.  This goes for holocarp (and holopets) as well as medical stuff and guns in the room.  In short, stuff from the holodeck has at least two hard counters: non-suborned AI (if the camera is operable so you can see the computer) and anyone who can destroy the fitness room APC, or whatever powers the holocomp on other maps.

The medical machines operate and draw power as normal.  The surgical tools are real, they just get a damage type nerf if the holocomputer is not emagged.

The medical machines are two sleepers, a grinder and chemmaster, and a PANDEMIC.  No chemicals are supplied, but you have everything else you need including holobeakers and holosyringes.  Keep in mind that they disappear when you leave (subject to the above) so they are not useful for treating people outside the holodeck.  There is also a washing machine and some spare holoclothes, because blood.

**Comment by SuperSayu** [comment]
A couple notes to myself before I forget--

Need to make the AI un-emag button switch off emag effects including turning off emag programs.
Upgrade derez to be weirder when emagged
Might make a holodeck that just shows the stars, just for flavor.
Holocard-spawning effect can make weapon-type cards when emagged I guess.
I think the holowindows were making shards, I need to fix that again

**Comment by Dorsisdwarf** [comment]
make us more snpc modules

**Comment by Lumipharon** [comment]
Wait so you can get a bunch of lasers round start with an emag now?
Keep in mind the AI can only stop this if the camera hasn't been disabled, which is 1 click with a tool.
And it also requires that people know that the lasers you are shooting people with are from the holodeck.

**Comment by SuperSayu** [comment]
The holodeck program is very noticeable, and camera tampering alerts the
AI.  You can also take out power to nullify everything--it's on the fitness
room APC, and the AI can access that if they can't see the computer.

If it becomes a problem, it's not hard to remove the program.  I thought it
would be an interesting addition

**Comment by PKPenguin321** [comment]
>camera tampering alerts the AI

not actually true if you have screwdriver/wirecutters

**Pull request merged**
