### PR TITLE
Fixed some oversights on icebox.

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request

List of things fixed :
- Swapped the AI Integrity Restorer console with a R&D console in the RD office.

RD_office_console

- Added a supply console in the cargo bay.

Supply_console

- Added an altar and a bible to the chapel.

chapel

- Moved some things around in the detective office to make room for a detrobe. Left is before, right is after.

Det_office

## Why It's Good For The Game

Making things more consistent between maps is good.

## Changelog
:cl:
add: Added a supply console to the cargo bay in IceBox.
add: Added an altar and a bible to the chapel in IceBox.
add: Added Detrobe to detective office.
tweak: Changed the detective office layout slightly in IceBox to make room for the Detrobe.
tweak: Swapped the AI Integrity Restorer console for a R&D console in IceBox.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
If you’re willing: could you add a suit sensor console to medbay? The only console is in the CMO’s office and it feels like an oversight

**Comment by Cyberboss** [comment]
Conflicts

**Comment by KathyRyals** [comment]
Ah fuck. I'll look at it

**Comment by KathyRyals** [comment]
Closed by #51856 , as they integrated my changes so we don't make multiple PRs.

**Pull request closed without merging**
