### PR TITLE
Nerfs myself

### PR DESCRIPTION
**Pull request by Cyberboss**
I've been at this for 5 hours

### CODE REVIEW

**Comment by PKPenguin321** [comment]
epic

**Comment by Anonmare** [comment]
Powercreep and fun removal :-1:

**Comment by SpaceManiac** [comment]
image

**Comment by 81Denton** [comment]
Sorry only @kevinz000 can get away with web editor PRs

**Comment by Cw3040** [comment]
@81Denton I got away with it faget, iirc one of my commits from the jetpack PR was webeditor

**Pull request closed without merging**
