### PR TITLE
Fixes the wizards pet dying every round

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**

### CODE REVIEW

**Comment by lzimann** [comment]
Doesnt this mean that creatures spawned in xenobio are all invunerable to vaccum then?

**Comment by KorPhaeron** [comment]
@lzimann 

Yeah

**Comment by Steelpoint** [comment]
The problem here was that I made the Wiz ship before Fastmos, meaning it would take hours for the Monster to die of lack of oxygen, yet now it takes minutes.

Fortunately this only occurs due to the monster bordering next to tiles that are exposed to space but have a shield to cover it.

**Comment by KorPhaeron** [comment]
@Steelpoint 

Actually the tiles it spawns on are airless as well

**Pull request merged**
