### PR TITLE
Autolathe Nerfs

### PR DESCRIPTION
**Pull request by actioninja**
:cl: actioninja
balance: Due to stricter NT regulations, autolathes can no longer print multitools, kitchen knives, circular saws, surgical drills, hatchets, large beakers, or health analyzers.
tweak: Most dinnerware is now available in the service lathe under the "Misc. Machinery" category.
tweak: Syringes and pill bottles are now available in the medical lathe.
/:cl:

Autolathes have too much in them that really should be harder to get.
This is intended as an alternative to removing all public autolathes. ~~If both of these get merged it'll be really funny to see the greytide salt do it orange man.~~

Also some bonus stuff in the service autolathe that really should have been in there to begin with, and some other stuff in the medical lathe that also should have been there to begin with. 

Since some people don't seem to realize this, multitools are already available from the engineering lathe and surgical tools, large beakers, and health analyzers can already be made in the medical lathe. This PR doesn't remove the ability to produce anything from lathes, just locks it behind some doors.

### CODE REVIEW

**Comment by KomradeSpectre** [comment]
I get what you're saying and all, but shouldn't dinnerware be instead in the "Weapon" section of the service lathe if anything? It makes much more sense.

**Comment by actioninja** [comment]
I wouldn't consider a shaker a weapon. Most of dinnerware doesn't fit any of the categories.

**Comment by Timonkeyn** [comment]
so do i have to run to medical every time i want large beakers?

**Comment by actioninja** [comment]
Didn't consider that the autolathe is generally in front of science. I could add beakers to the science lathe as well.

**Comment by Tlaltecuhtli** [comment]
cant print a beaker but can print bullets

**Comment by Eskjjlj** [comment]
Why remove multitools though.

**Comment by nicbn** [comment]
Multitools are really powerful, they make hacking much safer and easier
If greyshirt wants it they gotta work hard for it

**Comment by DaxDupont** [comment]
What a retarded pr

**Comment by tortellinitony** [comment]
Honestly, I don't think these things create much of a problem. This is stupid.

**Comment by yoyobatty** [comment]
Multitools should be available at minimum under the engineering protolathe.

**Comment by Vidiveni** [comment]
Droppers are unobtainium some longer rounds. I'd like them to medical, science and service protolathes. 

And I feel supply crates become an optional way to get more things than now, like multitools (if this gets merged), mutagen and XL-beakers. Make cargonia more relevant.

**Comment by anconfuzedrock** [comment]
Off, this won’t even fix shit, there will always be at least one autolathe item like the rcd. Spray cans are unfair stunburns for assistants that can give the janitor a stroke and make all windows opaque, this just makes things more arbitrary for awkward balance instead of the logical solution of moving autolathes. Same as how awkward it is for resting people to be hit by stray lasers now.

**Comment by PKPenguin321** [comment]
How to hugbox
1. Make all lathes public, removing any challenge or tension that may have been needed to get items from them
2. Remove conflict-causing or high risk items from lathe, as it's now too easy to get them
3. Now instead of there being occasional high-risk items made, there are none with no replacement. Congratulations! You've removed yet another source of conflict

**Comment by ExcessiveUseOfCobblestone** [comment]
tfw the circular saw can be made a traitor target

**Comment by Nickkoranda** [comment]
\>Be assistant
\>Year 2019, only one toolbox on the station for tools now
\>Greytiding triples because people want tools
\>Esculation policy now allows you to kill people if they don't give you tools
\>Engineers don't even set up SM/solars anymore, they join for roundstart free tools

**Comment by ExcessiveUseOfCobblestone** [comment]
If the public autolathe map PR gets closed then we can look at this PR as an alternative.

**Comment by zxaber** [comment]
>circular saws

Look, bucko, it's already bad enough when some greyshit steals my saw and I don't realize and I have to go make a new one mid-debrain operation. This is just another nerf to borging people, isn't it?

Also this is stupid overall and autolathes are fine as is.

**Comment by actioninja** [comment]
> Why remove multitools though.

> Multitools should be available at minimum under the engineering protolathe.

> And I feel supply crates become an optional way to get more things than now, like multitools (if this gets merged), mutagen and XL-beakers. Make cargonia more relevant.

> How to hugbox
> 
> 1. Make all lathes public, removing any challenge or tension that may have been needed to get items from them
> 2. Remove conflict-causing or high risk items from lathe, as it's now too easy to get them
> 3. Now instead of there being occasional high-risk items made, there are none with no replacement. Congratulations! You've removed yet another source of conflict

> Look, bucko, it's already bad enough when some greyshit steals my saw and I don't realize and I have to go make a new one mid-debrain operation. This is just another nerf to borging people, isn't it?
> 
> Also this is stupid overall and autolathes are fine as is.

With the power of meme magic, I just directly ported your complaints into the game. You can now print multitools from the engineering protolathe and surgical tools from the medical protolathe.
Since this was done via meme magic, you can go ahead and test it in game immediately.

**Comment by Tlaltecuhtli** [comment]
werent tools and surgery tools in protolathes already

**Comment by actioninja** [comment]
> werent tools and surgery tools in protolathes already

They weren't until I just made them retroactively exist in the game via meme magic.

**Comment by ExcessiveUseOfCobblestone** [comment]
@actioninja it's my strawman I can build it how i please jerky!

**Comment by Grazyn** [comment]
What happened to "we are gonna make autolathe items cost money"

**Pull request closed without merging**
