### PR TITLE
Adds Frostbite (Burn Wounds, but for Cold)

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Exposure to the cold can now give you Frostbite variations of the burn wounds.

## Why It's Good For The Game

Adds more danger to space walking and cold environments, which was previously not threatening in the slightest.
Mechanically, they're reskinned burn wounds because it's the same damage vector, just reversed, and a lot of the end results of Frostbite IRL are similar to burns.

## Changelog
:cl:
expansion: Frostbite wounds can now occur from the cold.
/:cl:

todo: write scar descriptions

@Ryll-Ryll

### CODE REVIEW

**Comment by Mothblocks** [comment]
Waiting on input from Shaps

**Comment by necromanceranne** [comment]
I'm not shaps, and maybe they changed their mind over time, but I remember that burn wounds were never meant meant to be applied through environmental effects. It had to be attacks. I think the concern was that fires would be too lethal, and superheating rooms would turn people into bacon too easily.

Also, I'm not quite sure I agree with cold not being very threatening. Maybe with previous versions of atmos, but the current version makes cold actually a lot faster at killing you than heat can be. Heat is kind of crap, and being on fire sort of a joke.

(Also space doesn't freeze you yadda yadda this is so unrealistic yadda yadda where is my dessication from exposure to a vacuum yadda yadda)

**Comment by Ryll-Ryll** [comment]
I ended up being fine with fire causing burn wounds since they're generally pretty slow to overtake you, but I'm against this PR because

1. Atmos is already extremely strong and dangerous, and there are very few deaths more frustrating than trying to struggle through a depressurized/exposed part of the station, nearing the exit, then falling into crit and dying on the spot, hoping that someone eventually finds you. Throwing a bunch of wounds onto the body for their trouble just feels like adding insult to injury in a way doesn't really serve the game, especially since it's not like there are other sources to get them like there are burn wounds with lasers/emitters/welders/etc.
2. Burn wounds are already kinda mechanically barren, and I really don't think that copy pasting them into the game again will add new or interesting depth to the game.

**Comment by Iamgoofball** [comment]
It's not about being mean to players, it just gets very boring treating folks who only have brute/burn damage and no wounds, because wounds are fun to treat.

**Comment by wesoda25** [comment]
Plenty of other sources of injury if that's your interest.

**Pull request closed without merging**
