### PR TITLE
Some reworks to the trait system

### PR DESCRIPTION
**Pull request by Lufferly**
## About The Pull Request

Removes point values of all quirks completely, each player can now choose any quirks, so long as they do not conflict.
Implications of this:
- Medical scanners show all quirks
- Quirks are all grouped together in medical applications
- Files reorganized to reflect the removal of points, now they are sorted as no, low, and high impact.

To cope with this change apathetic, self aware, and night vision had to go. Additionally jolly's effects were heavily nerfed.

## Why It's Good For The Game
There are a couple of reasons I decided to do this
<details><summary>The current quirk system is a little ableist</summary>
<p>

The current way we "give" points for quirks has always felt gross and ableist to me. By assigning a negative point value to real world disorders, such as blindness and paraplegic, it implies that these people are worth "less points" and are "negative". We should strive to try and remove these cultural stigmas when playing, a blind spaceman is not worth less than a not-blind spaceman. This applies to how we sort the code too, I don't really like how we use negative language to describe certain quirks, all of it just felt kinda wrong. So now they are sorted by their gameplay impact, which I think is a better way to approach quirk design anyway.

Unfortunately this is not a complete fix, hardcore mode still assigns points much the same way the old point system did. As much as I hate taking half measures, this is untouched for now, I don't really think I can replicate the gameplay people who play hardcore mode are looking for, and for now it is a hidden stat, though removal or a rework should be something that is looked into in my opinion.
</p>
</details> 

<details><summary>The current quirk system does not fit well with this type of game</summary>
<p>

It has always been strange to me that our quirk system is closer to that of CDDA (though I think it was changed in https://github.com/CleverRaven/Cataclysm-DDA/pull/64697) and project zomboid than the story generators of rimworld and dwarf fortress that I think this game is closer too. This system has its upsides, it encourages players to get benefits at the cost of some downsides, and tries to keep the quirkless option as the optimal one. However I think ultimately letting the players choose any three traits is better and allows for more interesting stories.
For one I don't think the limiting function of the current quirk system works very well. I think players tend to disinvest points from areas of the game they already don't interact with (see pacifist, bad touch, and allergies) in order to trade these "points" in for some gameplay benefits in parts of the game they do interact with (see night vision and self aware). Though with this system player will be able to get some benefits for free, I don't really think any traits are offensive enough that this is a problem, and it will open up a lot of the previously "negative" traits to be more roleplay centered, which is what ultimately the quirk system should be encouraging.
Furthermore the current quirk system feels a little overwhelming at the moment, by allowing the player to pick any three quirks, I hope that its more of a fun character building thing that encourages roleplaying as a character than a stressful pros and cons ttrpg experience.
Some of the more "flat buff" quirks were removed to make this system less gameable
- Apathetic allowed for the player to just kind of ignore the mood system
- Self aware is just a straight upgrade without any real roleplaying interest
- Night vision is also a straight buff that is not really interesting story wise
- Jolly was nerfed heavily, but still gives a point

</p>
</details> 

I hope that this rework allows for quirks to be an assist in roleplaying, with some mechanical changes, than what they are currently for many players, which is pick the "negative" traits you can ignore and load up with the benefits you want.

## Changelog

:cl: Seven
balance: The quirk system has been slightly reworked, all quirks are worth the same, and you can choose any three quirks.
balance: To reflect the complete removal of "points" from quirks, the quirk tab is now sorted completely alphabetically.
balance: Medical computers and health analyzer now show all quirks in the same field.
removal: Apathetic, self aware, and night vision quirks have been removed.
balance: Jolly quirk nerfed by a substantial amount.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
powergaming! woo!

**Comment by carshalash** [comment]
What did he mean by this?

**Comment by Serxule** [comment]
also i should add, 99% of the positive quirks have absolutely 0 rp impact and are purely mechanical that nobody else will notice

**Comment by Rex9001** [comment]
I don't really like a 3 quirk maximum, it feels like a shitty restriction for characters

**Comment by Lufferly** [comment]
All of these points are fair, though I still dislike how we assign negative value to real world disabilities, perhaps that could be alleviated by swapping the point system. If the goal of the current quirk system is to lead to more specialization and unique gameplay, I think some of the lower value negative quirks probably need to made a little more impactful (see bad touch).

**Comment by Bluedino1025** [comment]
i get your point, but if you asked a blind person if they liked being blind, odds are they'll say no!

**Comment by Wallemations** [comment]
I always associated the negative point values with an increase in difficulty rather than some sort of "lower value as a person"
While many deaf people are proud of being deaf and wouldn't want to change it, it's not really up to argument that they're going to find some aspects of life more difficult.

**Comment by Jezzared** [comment]
If it's simply a framing thing, perhaps have the negative traits give you points instead of removing them, and have the positive quirks take away from that balance?

Functionally identical, because that's already how it works, we just have a negative sign over a bunch of them for some reason. I've always found that odd.

**Comment by optimumtact** [comment]
yes the other part of the argument I didn't address much as i think there are likely things that can be done within the framework of the points buy system to rename or reframe them to not hold the same connotations and I don't think anyone would mind a PR on that basis.

E.g change negative to be named high impact in player facing ui's and similar so it's focusing clearly on the gameplay impact.

**Comment by Lufferly** [comment]
Alright, ill do that, thanks

**Pull request closed without merging**
