### PR TITLE
Removes a rogue period from the sliver theft objective

### LINKED ISSUE #29571: rogue period on the supermatter sliver objective
Objective #2: Steal a sliver of a supermatter crystal. Be sure to use the proper safety equipment when extracting the slive**r!.**

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
spellcheck: Removed an improper period from the supermatter sliver theft objective's name.
/:cl:

Fixes #29571.

To get around this, I added an `ending_punctuation` variable to objective item datums, so that you can have periods, exclamation points, question marks, and anything in between.

### CODE REVIEW

**Comment by Armhulen** [comment]
that was fast!

**Comment by lzimann** [comment]
what, this is kinda awful, just put the correct punctuation in the name

**Comment by Xhuis** [comment]
This makes it less tedious, I feel like. Is one var important enough to warrant removing it to manually put the punctuation in every name, do you think?

**Comment by lzimann** [comment]
feels lazy and pointless over two or three objectives having a different punctuation...

**Comment by Xhuis** [comment]
vOv

**Comment by Jalleo** [comment]
Why not instead having a check for the danger rating so everything above 15 gets a ! instead of adding it to every line?
It also makes it seem like stealing 50 gold bars is a big thing because we all know how big it used to be.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
