### PR TITLE
Strength and stimmed buff 2: Chemical Strongaloo

### PR DESCRIPTION
**Pull request by trollbreeder**
## About The Pull Request
Second attempt at PRing this. See #50149 

This adds functionality to strength and stimmed, so they're not just craftgenes.
Strength allows you to carry and drag mobs and lockers without being slowed down. Very useful for would-be paramedics, as long as you stop the bleeding. Nyoom.
Stimmed is what i hope will become used often, maybe even a must-have like space adap. It removes toxic reagents slowly but consistently from the user. Dap on the chemist as you shrug off their chloral hydrate cyanide nitric acid fluorosulfuric acid lexorin deathmix! Drink sulfonal as a party trick! Etc etc..

## Why It's Good For The Game

Fun new mutations to play with, no more throwing away these craftgenes after being used to make a better mutation. Now they have actual purpose to be injected into you, which is good.

## Changelog
:cl:
add: The strength mutation now allows dragging heavy objects with ease.
add: The stimmed mutation now slowly purges toxic reagents.
balance: Stimmed and strength have been given instability
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
Appveyor man bad

**Comment by GravitronBlue** [comment]
> Dap on the chemist as you shrug off their chloral hydrate cyanide nitric acid fluorosulfuric acid lexorin deathmix!

Chemist: _*Laughs in heated Nitrous Oxide cyrosyringe gun*_.

I'm pretty sure though that you can just wrap most heavy objects (i.e. lockers) and they become quick to move, also shame on paramedics who don't use bandages/rollerbed/fireman-carry when moving injured people.

**Comment by trollbreeder** [comment]
> I'm pretty sure though that you can just wrap most heavy objects (i.e. lockers) and they become quick to move, also shame on paramedics who don't use bandages/rollerbed/fireman-carry when moving injured people.

Strength covers fireman carrying someone this time, so you won't get slowed down by that.
Wrapping heavy objects to move them quickly is omega based and out of scope for this PR

**Comment by optimumtact** [comment]
these are designed to make good mutations harder to get

Do not buff them, that defeats the entire point.

**Comment by optimumtact** [comment]
What are you confused about? These are artificial difficulty limiters, if you change them, you break the entire design of the damn things.

**Comment by trollbreeder** [comment]
This is not "it's exactly like this but they do less" like thermal vision, they're "oh it does this and you can combine this and that to make this new thing!".

**I am adding functionality to filler mutations, i'm not breaking the design of genetics by making strength hulk but slightly less good. They have unique functions.**

**Comment by optimumtact** [comment]
If you add functionality (especially this powerful) to the filler mutations, it no longer becomes a tradeoff to research these and head for hulk instead of focusing on immediately useful mutations.

That is the reason why they do nothing.

**Comment by trollbreeder** [comment]
You can't focus on them because you don't know what mutation you're decoding before it's decoded. You see mutation 35 and you see a couple 3 XX's. It can be space adaption, or it can be acid flesh.

**Comment by adamkad1** [comment]
If you add function and instability to them, that means less space for better muts if you decide to use those, so people wont pick up the same mutation combos every damn time

**Pull request closed without merging**
