### PR TITLE
Fixes grammar on Hot Cocoa

### PR DESCRIPTION
**Pull request by ghost**
I am fucking APPALLED that this game has had this for so long. Shame on you people for not catching this mistake.

:cl: overly sensitive grammar person
spellcheck: Hot Coco is now Hot Cocoa
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
Have fun with my merge conflict, jim!

**Comment by QualityVan** [comment]
that's not grammar though

**Review by ShizCalev — APPROVED** [review]

**Comment by CosmicScientist** [comment]
There is no grammar label.

And now there will be no more coco, hot or not:
hotter cocos are a google away

**Comment by Tlaltecuhtli** [comment]
slippery slope

**Comment by CosmicScientist** [comment]
I haven't seen this said about ss13 before

**Comment by optimumtact** [comment]
this is a reference

**Comment by iskyp** [comment]
You can call your hot chocolate hot coco ICly if you want, but there is literally no reason the game should force the meme on people who aren't interested in it, or openly find it uncomfortable to be around.

I end up throwing all of the hot chocolate on station down disposal at the start of every assistant round in disgust, myself, and just sticking to regular mops.

**Comment by optimumtact** [comment]
why did you close it if you care so much?

**Comment by iskyp** [comment]
I don't

**Comment by CosmicScientist** [comment]
The game had a meme?

**Pull request closed without merging**
