### PR TITLE
Excluded some search paths for vs code

### PR DESCRIPTION
**Pull request by Donkie**
## About The Pull Request
You often get a crapton of search matches in the maps folder and changelogs, despite them not being much useful. This both cleans this up, and improves the search speed.

If you have any other ideas for exclusions I'll gladly add them.

## Why It's Good For The Game
Better development environment

## Changelog
:cl:
code: Added some default Visual Studio Code search exclusions
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
development stuff is still relevant, changelog it

**Comment by Rohesie** [comment]
Code_AvYK8jR2c3

This are the exclusions I use: `*.dmm, *.dme, *.yml, *.java, *.bat, *.md, *.github, .gitattributes, *.sh, *.py, *.txt, *html`
`.dmm` is sometimes useful to search for, though.

**Comment by Donkie** [comment]
> Code_AvYK8jR2c3
> 
> This are the exclusions I use: `*.dmm, *.dme, *.yml, *.java, *.bat, *.md, *.github, .gitattributes, *.sh, *.py, *.txt, *html`
> `.dmm` is sometimes useful to search for, though.

`.dmm`'s being excluded was the main purpose for my PR. You can click this little button to toggle the exclude setting:
image

**Comment by Donkie** [comment]
Added changelog but not sure how to trigger the changelog bot @Iamgoofball

**Comment by Iamgoofball** [comment]
It does it automatically on merge

**Comment by kriskog** [comment]
image
🤔

**Comment by Donkie** [comment]
:thinking: I believe this is still something that should be a default workspace setting for new users.

Can't include only dm because we have js and scss files etc.

**Comment by Fikou** [comment]
looking for dmm is important when youre repathing something

**Comment by Donkie** [comment]
Yeah yeah alright I'll just do this myself then, no worries

**Pull request closed without merging**
