### PR TITLE
Birdstation fixes and rebalances.

### PR DESCRIPTION
**Pull request by Tokiko1**
A bunch of changes and fixes for birdstation, see the commits for a full list. 

First time using mapmerger, let's hope I didn't break anything.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
You really should remove the skrub-trap toxins medibot IMO

**Comment by Tokiko1** [comment]
The medibot was made a lot less dangerous in this PR.

**Comment by Bawhoppen** [comment]
Rather than making it weaker, I say to make it start off or something.

**Comment by Tokiko1** [comment]
Would be nice to have this merged soon, especially for the shuttle change PR.

**Pull request merged**
