### PR TITLE
Revert "Moves hands to a new sprites, uniforms no longer need holes (…

### PR DESCRIPTION
**Pull request by optimumtact**
…#34782)"

This reverts commit 58053d35af820488189b47822d0b8fcc683234a9.

Please test merge this we have no arms

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Clever. Very clever.

**Comment by WJohn** [comment]
I just approved the original PR because the sprite work looked good, I can't say whether or not the *code* actually *works* or anything.

**Comment by nicbn** [comment]
I'll fix that

**Comment by nicbn** [comment]
Also they have arms just no hands

**Pull request closed without merging**
