### PR TITLE
Makes Harm Alarms not doable anymore

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
makes health circuits hella expensive to the battery charge
## Why It's Good For The Game

backpack harm alarms are bad
Closes #60270
## Changelog
:cl:
balance: make health circuits use 20 charge
/:cl:

### CODE REVIEW

**Comment by Watermelon914** [comment]
this is a change I support because it means health circuits that constantly check health will only last about 5-6 minutes with a high capacity cell.

It encourages people to make event-based circuits instead of being able to constantly check health and report if it goes down.
If the numbers need to be tweaked in the future, they can.

**Comment by coiax** [comment]
This seems a quick knee jerk reaction to something that might not even be a problem.

**Comment by Iamgoofball** [comment]
This was the requested value by Walter, coiax

**Comment by Watermelon914** [comment]
I told coiax that I didn't really care if he closed the PR or not.
I'm not really a maintainer and I don't control the balance aspect of circuits so I recommended it as an alternative to removing it. I can never guarantee a PR you make about circuits will be merged, and coiax does have a point here, it's a very specific change that only applies to one circuit component.

You could, if you wanted to, go around and rebalance the power outputs of interacting with the physical world, rather than just targetting the health component specifically.

**Comment by Watermelon914** [comment]
P.S. I also still need to change how power usage is done so that you don't drain such enormous amounts of power if you aren't actually requesting something to be done

**Pull request closed without merging**
