### PR TITLE
Material Resprites by Imaginos & PestoVerde

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Swaps out many of our material sprites with ones made by @Imaginos16 and @PestoVerde322 

image
## Why It's Good For The Game
A lot of the material sprites were isometric or just generally crusty, Pesto and Imaginos' work polishes much of those issues. Also the bluespace & telecrystal sprites just look pretty I mean cmon man look at 'em, just makes you wanna 
ezgif com-gif-maker (5)

## Changelog
:cl: PestoVerde, Imaginos, Wallem
imageadd: New material and ore sprites by PestoVerde & Imaginos
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
I misspelt his name that's extremely embarrassing

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
I'm dissatisfied with the shading and style of this port PR. Setting this on DNM until I find a good way to resolve it.

**Comment by Wallemations** [comment]
> I'm dissatisfied with the shading and style of this port PR. Setting this on DNM until I find a good way to resolve it.

I think that my personal opinion is that the strongest resprites in the bunch are the bars of gold, silver, sandstone, snow, and the telecrystal & bluespace crystals. If the lot as a whole isn't accepted, I feel like those would at least be beneficial to have.

Also a runner-up for this list was the diamonds just because the comically large diamond from before was a little wacky for my tastes

**Comment by Bawhoppen** [comment]
I don't understand why the DNM, these fit our style more than many sprite PRs

**Comment by CRITAWAKETS** [comment]
Could you like, resprite the uranium a little? It looks pretty bad, but apologies if it's not possible. Could probably just edit it with some noise since right now it looks like glass or bamboo rods where as noise would make it look more like rock or metal.

**Review by Imaginos16 — APPROVED** [review]
Much better.

**Review by Twaticus — APPROVED** [review]

**Comment by adamkad1** [comment]
Please make bananium more banana like

**Comment by SethLafuente** [comment]
love this but why does bananium not look like a banana

**Comment by SethLafuente** [comment]
also why does raw bluespace crystal dont accumulate with the more it has like the other ores

**Comment by SethLafuente** [comment]
and the tele crystals feel like to round they look more like rubies shouldnt they be like bluespace crystals but red

**Comment by Wallemations** [comment]
> love this but why does bananium not look like a banana

It is literally a banana bunch

> also why does raw bluespace crystal dont accumulate with the more it has like the other ores

Raw bluespace crystals don't exist in TG. Bluespace Polycrystals are their own weird thing, which existed exactly the same way that these do. I didn't change how bluespace crystals stack, I simply swapped the sprites.

As for the telecrystals, your preference for them not being round is noted, however I personally believe that the telecrystals are one of the best parts of the batch of sprites I was given.

**Comment by adamkad1** [comment]
> > love this but why does bananium not look like a banana
> 
> It is literally a banana bunch

Nope, cant tell

**Comment by LSommers** [comment]
The wood sprites look like a goddamn pile of Twix bars.
Bannanium looks like a generic yellow crystal.
Silver ore was _completely untouched_.

Many sheets, ores, and refined ores have overall lost their graphical distinction, making it harder to ID what they are at a glance- one of the worst offenders (recently _slightly_ improved via a fix PR) is Iron/Titanium/Titaniumglass. 

There are a number of things that are actually pretty good with this, like how the bars in reinforced glass/plasmaglass sheets are finally diagonal like the actual windows made with them, but it needs some serious work. Especially the Twix wood. _Please, lord, the Twix wood._

Also, if that one sprite is meant to be Runite, it had the shape it originally had because it was a Runescape reference, so it really should remain that particular shape for that same reason.

**Comment by Wallemations** [comment]
> The wood sprites look like a goddamn pile of Twix bars.

I'd have to agree it's currently one of the worst offenders yea. I'm at a loss personally on how exactly we'd fix it though. Perhaps going lengthwise on the sprite instead?

> Bannanium looks like a generic yellow crystal.

I'm personally a big fan of the new bananium, so I won't personally be doing anything about it.

> Silver ore was _completely untouched_.

Genuine oversight, it's on the list

> Many sheets, ores, and refined ores have overall lost their graphical distinction, making it harder to ID what they are at a glance- one of the worst offenders (recently _slightly_ improved via a fix PR) is Iron/Titanium/Titaniumglass. 

As you reference, iron has previously been fixed up, but the titanium issue is one im trying to figure out. My current thought process was to swap the color of the glass to the one the Wallening is using for their windows; a more black-ish tint. The issue there is that when you build the windows in-game, they won't have the same tint then.

> Also, if that one sprite is meant to be Runite, it had the shape it originally had because it was a Runescape reference, so it really should remain that particular shape for that same reason.

That's adamantite

**Pull request merged**
