### PR TITLE
Slimeperson quality of life changes

### LINKED ISSUE #18353: Cloning an abductor loses its species vars
Specifically, ayys store their team, and scientist/agent status in their species datum.

This has likely never come up before because there is, generally, only one ayy team operating, it's the agent that dies, and there are no agent exclusive items.

To replicate:
Kill an ayy scientist
Clone
Watch as you are unable to use the science tool

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Adds a new UI to slimepeople, allowing them to select more easily which body to swap to
add: Slimepeople swapping consciousness between bodies is now visible to onlookers
/:cl:

image
- Fixes bug where slimepeople would alter all of their clone's skin colour when splitting
- Fixes #18353, the species datum instance is now given to the new clone

Slime "families", made up of one or more bodies/dupes are tied to the body, not the mind. Cloned slimepeople will keep the same slime family. Having two active minds in a single slimefamily will probably cause !FUN! behaviour, but shouldn't happen... outside of the possessing ghosts wizard event, and also admin memes.
- One annoying bug is occasionally TGUI will "forget" the interface, and then insist that it can't find "slime_swap_body". I don't know what it's caused by, or how to fix it.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
It should be easy to check if the bodies have a mind, and accordingly prevent swapping to them.

**Comment by coiax** [comment]
I think I've done a variety of weird hacks though to make the UI panel still usable when you swap into a different body. I'm not sure if the origin usr when pressing buttons is correct.

**Comment by coiax** [comment]
For example, ui_act takes a (mob/user) var, but that changes to null after the first time its called (when it's just refreshing the window), so I have no way of knowing who pressed the "Swap into this body" button, which is why the code currently just iterates through all the slimefamily and then stops on the first mind it finds.

**Comment by Incoming5643** [comment]
hnnngh good ideas but perpetuation of tgui

C O N F L I C T I O N

**Comment by Kromgar** [comment]
Why do you hate the new ui?

**Comment by Incoming5643** [comment]
It has a load time measured in multiple seconds for people with older machines.

And since this is a game from 2003, it tends to draw people with older machines.

Lets not get off topic though.

**Comment by X-TheDark** [comment]
If you don't mind me asking a sort-of-unrelated question, what was changed in `tgui.js` file?

**Comment by coiax** [comment]
TGUI stuff. It's autogenerated whenever we change tgui interface things, so I assume it has the meat and potatoes to make all the ui work.

**Pull request merged**
