### PR TITLE
Drone fixes

### PR DESCRIPTION
**Pull request by JJRcop**
## About The Pull Request
Extracts the fixes from #48456 without features or balance

Corrects some misspellings

Documents drone tree

## Changelog
:cl: JJRcop
fix: Drone hacking is now fixed
fix: Fixed drone reactivation
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
nice

**Comment by ArcaneMusic** [comment]
I'm gonna kick your ass

**Comment by TiviPlus** [comment]
It's a message
Free Drone 2020

**Comment by ike709** [comment]
#50000

**Comment by SweptWasTaken** [comment]
🍾✋ 50K 🤚🎈

**Comment by Fikou** [comment]
can you fix the problem where if a drone wears a 32x64 hat it doesnt show up correctly
(i think that might be a chameleon hat problem and not a drone problem, maybe both but drones get chameleon hats)

**Pull request merged**
