### PR TITLE
North Star Medbay Rework

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request
Completely renovates the North Star Medbay to be more in line with what TG medbays require to operate. This also makes more of Virology's shutters stay open on roundstart, and makes sure that the abandoned medbay above the CMO office will actually spawn with reinforced plating.
f4

Basically nothing in the asylum or chem factory was changed.
There's now a maintenance route to access the morgue, useful for robotics.
## Why It's Good For The Game
The original medbay was enjoyable but it couldn't handle everything TG had to throw at it. I think this rework may slightly detract from the strength of surgery rooms, but it makes up for it in aesthetics, passive roleplay space, and functionality, while still retaining much of the original's design.
## Changelog
:cl:
add: The North Star's medbay has been fully renovated.
fix: The CMO's office ceiling is now properly protected on the North Star.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
If you can please make the coroner’s skeleton look like it’s watching over the surgery table because I wanted it to look like some surgery skeleton sidekick

**Comment by Cheshify** [comment]
> If you can please make the coroner’s skeleton look like it’s watching over the surgery table because I wanted it to look like some surgery skeleton sidekick (which I couldn’t do on all maps)

Abso-fucking-lutely that is very funny.

**Comment by Cheshify** [comment]
Skellington Menace Increased
image

**Comment by MMMiracles** [comment]
image
pipe/wires that lead into the door, leftover from the original design

image
don't see an associated button for these shutters

image
overlapping wall mounts in patient will look poopy to our 10 AI players, probably should move one of them up a tile

image
pharmacy isn't actually connected to the power grid or distro, just the waste loop

paramedic dispatch lacks air alarm

chemistry, pharmacy, paramedic dispatch, front lobby, patient room, both surgery rooms, cryogenics, medical office, medical storage, psych office, break room lacks a fire alarm


fix that stuff and it should be good to merge

**Comment by Cheshify** [comment]
Appreciate the review, requested changes have been made!

**Pull request merged**
