### PR TITLE
adds support for tones to tgui say [WIP]

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
basically, the chat bubble will linger for an extra few seconds and show that you've ended your sentence with !, ?, neither, or pressed ESC.

## Why It's Good For The Game
tonal indicators are already there in talk.dmi, this makes use of them and lets chat bubbles fade out a little more organically

## Changelog

:cl:
add: End-of-sentence tonal indicators for tgui say
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Can you add pictures/a video when you can plz?

**Comment by Wallemations** [comment]
Remember to delete the part of the sign language tongue code that does this
Also if you're lowering it to a second the frame lengths for the sign language ones might need to be lowered too

**Comment by jlsnow301** [comment]
> Remember to delete the part of the sign language tongue code that does this Also if you're lowering it to a second the frame lengths for the sign language ones might need to be lowered too

i was thinking about the time that rune chat stays up. more than a second

**Comment by Wallemations** [comment]
> i was thinking about the time that rune chat stays up. more than a second

That should work fine then, though the first part about the tongue is important. I don't wanna accidentally overwrite your system lmao

**Comment by Wallemations** [comment]
What would Indecisive be? Wouldn't that require you to just put in a blank input?

**Comment by jlsnow301** [comment]
> What would Indecisive be? Wouldn't that require you to just put in a blank input?

I'm thinking if they press ESC the bubble pops?

**Comment by Wallemations** [comment]
> > What would Indecisive be? Wouldn't that require you to just put in a blank input?
> 
> I'm thinking if they press ESC the bubble pops?

Oh that's cute
I'll have to think of how to make that make sense for the sign language ones
Maybe I'll just make an emoji pop or something
Trying to think of an ASL sign that would fit is hard
"Sorry" involves the chest so that won't work
Maybe just a wave, since that's closest I can get to "nevermind"
I'll have to mull it over

**Comment by Wallemations** [comment]
Hoping you finish this eventually, since I noticed a bug with my implementation of it.

**Comment by optimumtact** [comment]
stale closed

**Comment by Wallemations** [comment]
Aw, I was looking forwards to this one.
One day, maybe

**Pull request closed without merging**
