### PR TITLE
Fixes naming consistency for Departmental Protolathe/Techfab boards

### PR DESCRIPTION
**Pull request by ghost**
Service Techfab machine board has a name unlike the others, this simply fixes that. Why is it good the for the game? Consistency.

## About The Pull Request

All the techfab boards follow the naming format: 
Departmental Techfab (Machine Board) - Department
Except the Service department's board. This fixes that.

## Why It's Good For The Game
Naming consistency, thats about it.

## Changelog

:cl:
fix: Fixes Naming Consistency of Techfab boards
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
It's customary for most machine and computer boards to put the parentheses tag at the end of the name, right? Maybe the other techfab boards should change to match Service's instead?

**Comment by tnekohue** [comment]
It could be done either way, as long as its consistent. Maybe we could get some people to vote on what they would like to see? Or have a higher-up weigh in on this kind of decision.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Machine board should be at the end. Fix the others instead please.

**Comment by tnekohue** [comment]
Changes have been made, instead now departmental techfab boards have a naming scheme that matches other types of machine boards in general

**Review by ShizCalev — COMMENTED** [review]
/obj/item/circuitboard/machine/protolathe/department/security
	name = "Departmental Protolathe (Machine Board) - Security"

mind hitting these too? they're all in the same file.

**Comment by tnekohue** [comment]
Got em, squashed commits.

**Pull request merged**
