### PR TITLE
Rebalances armor to make each type fit better in their niche

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Nanotrasen Security RnD Team
tweak: Changed the descriptions on some armor to better explain their properties.
balance: Bulletproof and Riot armor have been rebalanced to better protect against projectile and melee damage, respectively. To compensate, protection against damage types outside of their niches has been reduced.
balance: Because of the new upgrades in protection, riot armor and bulletproof armor now provide a minor slowdown.
/:cl:

This PR aims to make different types of armor better serve their roles. Previously, bulletproof and riot armor provided very mediocre protection against the damage they were meant to protect against, and also provided small protection against types of damage that really made no sense for them to be resistant to. 

Now, both armor types are significantly better in their niches, but provide a narrower range of protection. 

**This change will make these armors both more viable and make picking the correct type of armor for your situation a more important decision.**

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]
inb4 shitstorm

**Comment by Tacolizard** [comment]
preparing to scree at all the haters.

**Comment by KorPhaeron** [comment]
>50% damage reduction

>effectively double HP

>mediocre protection

lmao

**Comment by Tacolizard** [comment]
when was the last time bulletproof armor actually saved your life Kor?

**Comment by KorPhaeron** [comment]
I don't remember because most times people just tase you and then take your armour off or shoot you in a limb.

I do remember a while back tanking all of the stetchkin magazine @Robustin shot at me in gang though when I was HoS

**Comment by Tacolizard** [comment]
@KorPhaeron you were probably wearing HoS armor then.

**Comment by Repukan** [comment]
It's enhanced not enchanced.

Also fuck that slowdown.

**Comment by Dorsisdwarf** [comment]
Isnt this basically just undoing all the changes to specialist armor from the last like, 3 years?

**Comment by Tacolizard** [comment]
@Repukan where did I misspell it?

**Comment by Repukan** [comment]
HoS armor desc

**Comment by Tacolizard** [comment]
oh that wasn't actually my misspelling i guess that was already there.

**Comment by Repukan** [comment]
Add me to the screenshot

**Comment by KorPhaeron** [comment]
>armour shouldnt protect against one of the most common and most powerful attacks

>but we need to nerf weaker attacks further

**Comment by Tacolizard** [comment]
@KorPhaeron I don't understand what you're referring to. Can you explain?

**Comment by Shapsy** [comment]
Esword probably

**Comment by Tacolizard** [comment]
so he's saying that all attacks except esword are weak?

**Comment by Shapsy** [comment]
Also no one will use the armor if it has slowdown

**Comment by KorPhaeron** [comment]
You just said armour shouldnt protect against stuns, which is a one hit kill, while also justifying nerfing melee/laser/bullets because "armour doesnt save you anyway" (because of stuns)

Tasers already win you the fight in a single hit vs a sketchkins 5. If you put on current bulletproof they have to hit you 10 times and you still need to tase them once.

With your proposed change they would need to stechkin you 17 times before you tased them once.

Why do you want to nerf weapons so badly?

**Comment by Tacolizard** [comment]
it's not because i want to nerf weapons, it's because armor should actually be useful. If you see an officer with bulletproof armor, mabye you should think twice about using a stetchkin.

**Comment by Robustin** [comment]
Only armor I support buffing is riot armor. I think there should be a class of armor that just says "fuck you you're either gonna have to strip me, or try a different damage type because for once in this game stun + toolbox isn't going to get the job done".

**Comment by Tacolizard** [comment]
@Robustin same reasoning behind buffing bulletproof armor. "for once in this game you're gonna have to try a different damage type because spamming a stetchkin isn't gonna work.

The goal of this PR is ultimately to make combat more interesting by providing hard counters to specific damage types that require strategic choice of what type of damage you want to negate, instead of an armor that just generally reduces all damage.

**Comment by KorPhaeron** [comment]
@Tacolizard 

If you don't consider double HP useful then you have a poor grasp of both game design and basic math

Make bulletproof cover limbs so it is no longer 0% armour if you really want to buff it

@Robustin 

Yeah but stun + cablecuff + toolbox would be the same thing even then.

**Comment by KorPhaeron** [comment]
@Tacolizard 

People being near immune to other peoples attacks isn't interesting. Heavily punishing people for using weapons other than a taser/ebow/baton isn't interesting.

**Comment by Tacolizard** [comment]
@KorPhaeron being able to use the same ballistic or melee weapons to take down anyone regardless of how well they prepared isn't interesting

**Comment by KorPhaeron** [comment]
>being able to use the same ballistic or melee weapons to take down anyone regardless of how well they prepared isn't interesting.

Do you want full immunity then or something? How is literally double effective HP not already a huge incentive to use a different weapon type?

**Comment by AlexCrimson** [comment]
All this bitching about stuns. Just sayin', removing ranged stuns was the best thing yall ever did, then you reverted it.

**Comment by Steelpoint** [comment]
Don't bother buffing armour, you won't get anywhere except frustration. No one can agree on how to change armour so it never gets changed from where it is now.

Right now most armour is simply a holster for your gun.

**Comment by Steelpoint** [comment]
Though to be honest I'm fine with this PR.

Most of it is simply expanding the descriptions of present armour to better explain what they do to the reader.

It only alters three armour types, the Bulletproof armour, the Riot armour (both of which are underused) and the laserproof armour.

------

BulProof Current - melee = 15, bullet = 60, laser = 10, energy = 10, bomb = 40
BulProff New - melee = 5, bullet = 70, laser = 5, energy = 5, bomb = 60

Riot Current - melee = 50, bullet = 10, laser = 10, energy = 10
Riot New - melee = 70, bullet = 5, laser = 5, energy = 5

Las Current - melee = 10, bullet = 10, laser = 60, energy = 50, fire = 100, acid = 100
Las New - melee = 10, bullet = 5, laser = 70, energy = 50, fire = 50, acid = 50

------

Effectively. Wearing the Bulletproof armour boosts your bullet defence from 250 effective hp to 333hp.

The Riot Armour boosts from 200hp to 333hp.

The las proof armour boosts from 250hp to 333hp.

But they all lower their non-designed defence to minimum/non-existent levels. 

I still think this is going to go nowhere except PR hell. But at minimum I do think the descriptions should be kept.

**Comment by Steelpoint** [comment]
The problem with armour right now is a lot of high level antags have weapons that outright ignore armour significantly.

This would not be a issue if armour was strong enough in the first place, but on /tg/ our armour is worth spit unless your a Deathsquad or Nuke Op.

**Comment by Haevacht** [comment]
this is bad and you should feel bad

**Comment by Robustin** [comment]
Yea better melee armor doesn't mean "you can't kill me" it just means I get more than 10 seconds to scream on radio before im dead.

**Comment by KorPhaeron** [comment]
Yeah, and having double HP gives you more time to scream on the radio.

**Comment by Steelpoint** [comment]
Considering most antag weapons have so much armour penetration, this will mostly affect low level antags or idiots who charge a guy unprepared. 

I fail to see how 'screaming over the radio' is a counterpoint. Unless your gun kills in two bullets or so (SAW, Revolver (both of which I think have armour pen so a moot point)) then your victim is almost always going to be able to scream for help before they go into crit.

**Comment by KorPhaeron** [comment]
Most antag weapons do not actually have armour pen. Even if they did, "lets buff armour and its okay because to balance it we'll make our weapons ignore armour!" seems kind of silly.

>unprepared

You mean not having a stun? Having a battery taped to a stick is already a stronger weapon than magdumping a handgun into someone or hacking away with a chainsaw, why do we need to nerf the handgun/chainsaw again?

**Comment by Armhulen** [comment]
thank god

**Comment by Armhulen** [comment]
adding slowdown to these was an insult

**Pull request closed without merging**
