### PR TITLE
M(i/a)crobomb Adjustments

### PR DESCRIPTION
**Pull request by ChangelingRain**
Increases microbombs to 2 telecrystals.

Changes micro and macro bombs to have a delay based on the number of implants.
One microbomb is instant but scales up to 7 seconds of delay at 10 microbombs.
Decreases the explosion size of m(a/i)crobombs to 4/8/16 at 10 microbombs or one macrobomb.

Macrobombs no longer stack.
I didn't test this at all but I don't give a shit~
(no seriously I did this shit in the github editor I am not responsible for any bugs or implants not working, and I don't give a shit unless they're failing by exploding hugely)

### CODE REVIEW

**Comment by Iamgoofball** [comment]
What the fuck are you doing i already have a pull request up

**Comment by Fox-McCloud** [comment]
:-1: To adding a delay and increasing TC cost.

There's not a whole lot of difference between someone blowing themselves to bits with a max size toxin's bomb in their backpack and using a macrobomb to do it, other than job access--this just seems like a reactionary nerf to a new item in play.

TC Cost? They're meant to be a cheap "screw you" to kill yourself or someone else who's already incapacitated--this seems to fit in better the recent policy shift of "SS13 isn't lethal enough", not to mention it undermines the "filler" nature of microbombs.

**Comment by Iamgoofball** [comment]
@Fox-McCloud he upped the individual bonuses of each microbomb

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

I know; it's not their maximum potential I dislike, it's the undermining of the basic principal of "cheap filler item".

**Comment by Anonus** [comment]
I mostly changed the TC cost so it'd be easier to buy somewhere between "tiny self gib" and "all of cloning is gone"

**Comment by Fox-McCloud** [comment]
@Anonus 

I can understand that, but the fundamental point of the microbomb is "cheap screw you if validhunted" and "ok filler item for various shennanigans when you only have 1-2 TC left."

**Comment by Lumipharon** [comment]
The thing I noticed with microbombs, at 1 or even 2 tc, they can still be used to gib 20 or 10 crew members respectively. All you need is a stun weapon, implant the person, then beat them to death and they gib.

**Comment by Iamgoofball** [comment]
@Lumipharon And? Valid tactic.

**Comment by Fox-McCloud** [comment]
@Lumipharon 

And not shockingly scientists, chemists, and anyone with access to a chem dispenser has been able to do that since...forever.

**Comment by Lumipharon** [comment]
Because taking the time to make a 100u blackpowder nade is comparable to spawning an item and clicking them with it?

This is exactly the same as what I said about macrobombs. Now that macrobombs are getting removed, sooner rather then later, people are going to realise how many people they can gib with microbombs.

We nerfed c4 for this exact same reason ages ago.

**Comment by WJohn** [comment]
Since nuke ops now start actually implanted with microbombs, I'm actually okay with increasing the cost by 1 TC, since it prevents you from completely obliterating all dead bodies so easily.

**Pull request merged**
