### PR TITLE
Significantly slows down broken bar sign animation as to prevent possible seizures

### PR DESCRIPTION
**Pull request by Bawhoppen**
Someone in OOC said that the animation for the broken bar sign was flashy enough to be able to cause seizures in epileptic people. I'm not really an expert on the topic, but better be safe than sorry.

### CODE REVIEW

**Comment by davethwave** [comment]
Better safe than sorry I guess. Good work by the way.

**Comment by Bawhoppen** [comment]
Thanks!

**Comment by GuyonBroadway** [comment]
Photo sensitive epilepsy can be triggered by any sudden change in light so a flash could set them off. Not to mention the glitched displays on the AI screen.

Don't get me wrong I appreciate what you are doing and why but its real hard to make a game epilepsy friendly without doing it from the get-go cus there are many kinds with varying sensitivities and intensities.

**Comment by Cyberboss** [comment]
@GuyonBroadway is right. This is fine though

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
