### PR TITLE
Line Ending Apocalypse: The Revenge of .gitattributes

### PR DESCRIPTION
**Pull request by optimumtact**
Nah just kidding, just a reword of the warning about line endings

### CODE REVIEW

**Comment by MrStonedOne** [comment]
>tonne

**Comment by optimumtact** [comment]
https://github.com/tgstation/-tg-station/blob/master/CONTRIBUTING.md#enforced-not-enforced

>English/British spelling on var/proc names

**Comment by ike709** [comment]
Actually the correct usage in this scenario would be "ton", because it is used  to describe a large amount, while "tonne" is not (or technically shouldn't be). Cultural spelling is irrelevant. It holds different meaning in this case.

See: Merriam-Webster dictionary

**Comment by optimumtact** [comment]
Actually you nerd this is the kiwi spelling

checkmate

**Comment by ike709** [comment]
fix the grammatical errors

**Comment by optimumtact** [comment]
no

**Comment by Jordie0608** [comment]
Can confirm tonne is applicable

**Comment by ike709** [comment]
>merging this travesty of grammar

**Pull request merged**
