### PR TITLE
Fix some runtimes related to SS currentrun vars

### PR DESCRIPTION
**Pull request by Cyberboss**
@MrStonedOne 

This is to be paired with #23666 so proc call overhead doesn't them to shit

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Nope. I'd rather have the runtimes then the overhead. Or we could make these thing remove from currentrun on qdel

**Comment by Cyberboss** [comment]
@MrStonedOne What about now that we removed the istype overhead?

**Comment by MrStonedOne** [comment]
it could work

**Comment by MrStonedOne** [comment]
I still think the proper solution is to remove from currentrun on delete

**Pull request closed without merging**
