### PR TITLE
Makes solars on TramStation functional

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

Makes solars functional on TramStation.

Because the solars were close to walls (asteroid) and because the area was set to mining, solars on TramStation never got sunlight and thus couldn't function. I confirmed with MMM that this was not intended.

To fix this, I've remade the two sets of solars and placed them a bit further away from the asteroid.
Fore Solars:
image

Aft Solars:
image

## Why It's Good For The Game

Gives function to a piece of the map that was intended to be functional. Improves intended balance by creating alternatives for power after engine failure, station disconnections, power sinks, etc.

## Changelog

:cl:
fix: Engineers have finally solved for the reason why their solar setups on TramStation never worked.
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
Didn't include the meteor shielding on the left side of aft solars in the original post: 
image

**Comment by Son-of-Space** [comment]
image

**Review by Maurukas — CHANGES_REQUESTED** [review]
This fixed in the latest master. Could you merge master and make sure this no longer shows up? 

Holes in security:
image

We've had a lot of weird mapmerge cruft creeping back in and I'm being a little extra paranoid about it.

Other than that looks good.

**Comment by Son-of-Space** [comment]
Looks like it's good.
image

**Pull request merged**
