### PR TITLE
Tool Resprite?

### PR DESCRIPTION
**Pull request by maxymax13**
## About The Pull Request

*Very* heavily modified port of https://github.com/BeeStation/BeeStation-Hornet/pull/2487.
dreamseeker_0VoXDgqF0j

View full icon changes in the checks tab > icondiffbot.
Keep in mind a lot of the comments on this PR from when I used a lot more ugly original bee sprites.

## Why It's Good For The Game
Make game prettier yes?

## Changelog
:cl: maxymax13, PositiveEntropy, Kryson, Flareguy
iconadd: Tools have been resprited.
iconadd: The powergame crowbar in the shuttle ruin has been given an unique sprite!
iconadd: Caravan tools are now unique sprites instead of regular tools dunked in red food coloring.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
I don't like the pipe wrench but the rest don't look too bad.

**Comment by maxymax13** [comment]
drafting until we get the final few tools done

**Comment by notfrying1pans** [comment]
crowbar is too horizontal

**Comment by RaveRadbury** [comment]
Current tools will kind of spiral/fan out when stacked on top of each other. Does this follow that? Might be hard to click on stacked tools.

**Comment by maxymax13** [comment]
> 
> 
> Current tools will kind of spiral/fan out when stacked on top of each other. Does this follow that? Might be hard to click on stacked tools.

not really that much of an issue, random pixel spread should make them pretty spread out normally. and in most places that you find tools stacked there's enough garbage that you just end up right click menu finding it instead

**Comment by RaveRadbury** [comment]
> not really that much of an issue, random pixel spread should make them pretty spread out normally. and in most places that you find tools stacked there's enough garbage that you just end up right click menu finding it instead

Going from an elegant and _intentional_ spread is that much of an issue, imo. I like the current stuff better.

**Comment by maxymax13** [comment]
using the old upgraded welders at the request of twaticus

**Comment by Sparkezel** [comment]
some of the sprites like the hand drill feel much too small in my opinion, same with jaws, it just makes them... not feel like themselves anymore

**Comment by RaveRadbury** [comment]
Here's some screenshots to illustrate what I'm trying to get at
Current tools
image
image

New tools
image
image

It's way messier, the wrench and crowbar were intentionally set at diagonals and I think this is some thing that should be preserved.

Please set the new wrench and crowbar at opposing diagonals.

**Comment by maxymax13** [comment]
on it, will try and fix

**Comment by maxymax13** [comment]
image
does this satiate you

**Comment by cacogen** [comment]
This is more changing decent-looking, well-established sprites to uglier ones or ones that don't fit the art style for no reason instead of updating the actual bad and in some cases ancient sprites the game has

**Comment by maxymax13** [comment]
> 
> 
> This is more changing decent-looking, well-established sprites to uglier ones or ones that don't fit the art style for no reason instead of updating the actual bad and in some cases ancient sprites the game has

ok if you say so

**Comment by CRITAWAKETS** [comment]
these look awful, way too much contrast. Doesnt fit any sort-of artstyle and i'd even say it looks bad no matter the art style.

**Comment by maxymax13** [comment]
image
KRYSON COMING IN CLUTCH

**Comment by cacogen** [comment]
The supermatter crystal is an example of a good sprite with an art style that makes it look completely out of place. I'd say these neither fit the art style the majority of sprites still have nor look good themselves.

**Comment by maxymax13** [comment]
> 
> 
> The supermatter crystal is an example of a good sprite with an art style that makes it look completely out of place. I'd say these neither fit the art style the majority of sprites still have nor look good themselves.

maybe these sprites would fit the style of the sprites around them if people like you didn't dunk on resprites like these

**Comment by cacogen** [comment]
>maybe these sprites would fit the style of the sprites around them if people like you didn't dunk on resprites like these

I think you're saying that if people are given carte blanche to change sprites as they see fit this will guarantee that eventually by the time the game is superseded by SS14 or UnityStation or we are swallowed by the tides we will have an updated, uniform art style that looks better than the old sprites that make up the majority currently. But we can already see that while some of the new sprites are better, most are worse, and most don't fit the existing art style but don't match each other either. They're just unnecessary changes to decent, instantly recognisable sprites that have been in the game forever without complaints. And there are bad sprites in the game that have been there forever and set the bar so low that any change would be an improvement. But it always has to be the most visible sprites for some reason.

**Comment by maxymax13** [comment]
image
how's this

**Comment by maxymax13** [comment]
image

**Comment by cacogen** [comment]
They just look worse and more impressionistic I want to say, like you did an oil painting of the originals. If the wrench had better proportions I might consider it an improvement though given it looks a lot more familiar to me than the original.

**Comment by maxymax13** [comment]
> 
> 
> They just look worse and more impressionistic I want to say, like you did an oil painting of the originals. If the wrench had better proportions I might consider it an improvement though given it looks a lot more familiar to me than the original.

you're very hard to please, you know that right

**Comment by maxymax13** [comment]
was pressured into drafting while we fine tune the wrenches to avoid premature mergies, tool resprite will return shortly

**Comment by cacogen** [comment]
I like the wrench. It looks more real than the current one and doesn't look out of place. After looking at them on Google Images I think I was wrong about the proportions, actually.

**Comment by maxymax13** [comment]
it's more about the shading

**Comment by maxymax13** [comment]
image
image

**Comment by maxymax13** [comment]
dreamseeker_0VoXDgqF0j
palette adjust

**Comment by RaveRadbury** [comment]
image
looks like there's a lot of overlap between the wirecutters and screwdrivers here.

**Comment by maxymax13** [comment]
> 
> 
> image
> looks like there's a lot of overlap between the wirecutters and screwdrivers here.

old sprites had that too

**Comment by RaveRadbury** [comment]
> > image
> > looks like there's a lot of overlap between the wirecutters and screwdrivers here.
> 
> old sprites had that too

old sprites didn't make me have to pixel hunt _between_ pixels of the wirecutter handle to pick up a screwdriver.

**Comment by maxymax13** [comment]
tired over bikeshedding over sprite positions, let's go

**Comment by maxymax13** [comment]
i meant medical but w/e, the joke was that it was literally a penlight on top of a wrench

**Review by Twaticus — CHANGES_REQUESTED** [review]
thanks for all the work thats been done on this, just a few inhand issues

tools_righthand:
inducer-engi, inducer-sci, inducer-syndie right directionals are missing pixels near the arm/hand
drill back directional is offset

everything else looks great

**Comment by maxymax13** [comment]
playing spess rn, will fix shortly

**Comment by maxymax13** [comment]
done

**Review by Twaticus — APPROVED** [review]

**Comment by Mothblocks** [comment]
i dont really like them but i'll get used to it

**Comment by maxymax13** [comment]
victory is ours

**Comment by cacogen** [comment]
I have to say it why would you add a blurry oil painting impression of the original sprites (and a passable wrench resprite) that you don't even like

**Pull request merged**
