### PR TITLE
fixes awakened his grace not shaking

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

fixes awakened his grace not shaking anymore, i dont know when it happened, but the awakened icon lost the animation somehow

## Why It's Good For The Game

the shaking adds SOUL
also the rumbling toolbox has no sense without shakage

## Changelog
:cl:
fix: His Grace shakes again.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
haha OOPS guess i need to get a new items and weapons dmi

**Comment by Fikou** [comment]
how does it still conflict

**Comment by nemvar** [comment]
From what I understand, his grace used animate to get its animation. If you are gonna do that with the icon instead, remove the code from his grace that was supposed to handle this.

**Comment by Fikou** [comment]
wtf windup toolbox wasnt touched when that happened

**Pull request closed without merging**
