### PR TITLE
Updates blueshift sec sprites.

### PR DESCRIPTION
**Pull request by WJohn**
Nienhaus wanted me to update these, so I did. Our current ones looked really bad anyway.

:cl: WJohn
imageadd: Improved blueshift sprites, courtesy of Nienhaus.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Nice
Half life station 13 when

**Comment by Armhulen** [comment]
I kinda like the old armor plate more but oh well

**Comment by Steelpoint** [comment]
Security sprite wars go.

On topic, these sprites are nice.

In before we get a PR to change this to the default sec uniform.

**Comment by KorPhaeron** [comment]
Touches lots of common files, sprites are better, obviously art lead approved, no need to have open for 24 hours

**Comment by darkpaladin109** [comment]
Add these as alt officers in the sec lockers when?

**Comment by Nienhaus** [comment]
Hopefully never ;D

**Comment by Mindustry** [comment]
Can't you order them from cargo?

**Comment by Nienhaus** [comment]
Pretty sure it's only on some away mission @Mindustry unless I'm mistaken.

**Pull request merged**
