### PR TITLE
Slimes may now be ordered to attack

### PR DESCRIPTION
**Pull request by RemieRichards**
- Slimes may now be ordered to attack, they will not attack their Friends, other slimes, the person who ordered them to attack or themselves.
- `#define`'d Slime friendship levels.
- Made Slimespeak more Baby-ish, because it's cuter. lil babbu slimes.

Merge Token (1/2 Tokens): https://github.com/tgstation/tgstation/pull/18068

:cl:
add: Slimes may now be ordered to attack! You must be VERY good friends with the slime(s) to give this command, asking them to attack their friends or other slimes will result in them liking you less so be careful!
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
babbu slimes yes

**Comment by X-TheDark** [comment]
What about slime people? Will slime people have special slime-commanding privileges (seeing as they're slime and all) or slime protection (again, seeing as they are sort-of slime, but not recognized by isslime() command).

**Comment by RemieRichards** [comment]
@X-TheDark Slimepeople, as always, are immune to slime attacks, so they're immune to this order too

**Comment by LatD** [comment]
Did you check that this works? There's a bug that slimes aren't obeying any commands. #9128

**Comment by tedward1337** [comment]
Babbu slimed git

**Comment by RemieRichards** [comment]
@LatD I tried all commands, they all work fine?

**Comment by LatD** [comment]
Last time I tested them (early this year maybe) they still didn't work. Did you test it locally or on Sybil? There might be some weird npc lag involved that's causing the bug. If it's working on Sybil I guess that issue can be closed and there's no problem here.

**Comment by RemieRichards** [comment]
@LatD locally. There should be no difference between local and Sybil, nothing about slimes is in the config, and thus, is uneditable.

**Pull request merged**
