### PR TITLE
BYOS shuttle restrictions (Shuttle changes #1)

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: The Build your own shuttle kit can only be bought in the first ten
minutes of the shift.
/:cl:

- BYOS restriction is to avoid grief.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
I think this is an incredibly small window for what is the most popular shuttle among both players and admins.

**Comment by coiax** [comment]
It's a 5 minute window (same window as the station charter), construction and pressurising of the shuttle takes a minimum of 10 minutes, and in our current climate of ultra short rounds, I'm not comfortable it being bought much later.

What timing do you suggest?

**Comment by ChemicalRascal** [comment]
I don't feel like we really have ultra-short rounds all the time, I find they generally last half an hour if antags don't stomp (or are stomped by making incredibly bad choices in the first five minutes).

On the other hand, BYOS seems to work as a great "oh shit we were cocky and thought the shift would be quiet and now we're fucked because we're bad engineers" mechanic, which does make it a super-easy way to grief later in the shift.

Maybe making this equal to the shuttle fueling time (or whatever it is at the start of the round, it's fifteen minutes I think) would make more sense. That's plenty of time for the heads to have a chat and the Cap to come to a decision, but it's wide enough that if they're waiting to see if major antag shenanigans are kicking off too quickly, a smart Captain won't get wrecked.

Similarly, this might encourage team antags to stealth it for the first fifteen minutes to bait a BYOS, which would be a neat sort of tactical decision I think.

TL,DR: kick it up to 15 mins maybe idk

**Comment by ChemicalRascal** [comment]
Also, might I suggest not moving those defines? From a code-design/code-"smell" perspective, bits of code outside the nuke ops shouldn't really be using them. An example being your own code: There's no (stated) reason why the limit on buying the BYOS should be the same as the war-declaration limit (or, for that matter, the station-naming limit). Sure, there's nothing wrong with them being the same, but _defined_ as the same they should not be, IMO.

more importantly moving the defines outside the modules they're used in only makes this already-horrific codebase all the more difficult to navigate so

**Comment by PKPenguin321** [comment]
Maybe extend the window to at least 15 minutes?

**Comment by francinum** [comment]
Make the baseplate the size of the delta shuttle as well, as it stands now it's strangely shaped.

**Comment by coiax** [comment]
I'll kick it up to 10 minutes.

**Comment by kevinz000** [comment]
how about no?

**Comment by coiax** [comment]
@kevinz000 we've discussed this at great length on IRC, I'd be interested to know your input to avoid BYOS being griefy.

**Comment by kevinz000** [comment]
input is not required i see.

**Comment by optimumtact** [comment]
not yours, you lost that right with all your shitty changes

**Pull request merged**
