### PR TITLE
SQL Schema Version 5.11 / Add indices for ticket table to support Statbus operations

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request

Adds indices to support searches on the tickets table. Improves performance of operations that search them considerably.

## Why It's Good For The Game

We like performance.

## Changelog
:cl: bobbahbrown, MrStonedOne, Jordie0608
server: Added indices to improve support of searching through the tickets table, updated schema to 5.11.
/:cl:

### CODE REVIEW

**Comment by Doosteroni** [comment]
bruh momento, I don't know what this is, but I am first

**Comment by bobbahbrown** [comment]
authors note: these changes are already applied on tgdb, mso did that earlier today and suggested that I PR them

**Comment by Jordie0608** [comment]
I think you can have more performant indexes than these, but I'll have to get some data off ned to test with first.

**Comment by Jordie0608** [comment]
I made the following indexes:
```
INDEX `idx_ticket_act_recip` (`action`, `recipient`)
INDEX `idx_ticket_act_send` (`action`, `sender`)
INDEX `idx_ticket_tic_rid` (`ticket`, `round_id`)
INDEX `idx_ticket_act_time_rid` (`action`, `timestamp`, `round_id`)
```
And from my not very extensive testing of a 700k row table got the following times in seconds using no indexes, bobbah's and my own respectively:
```
getActiveTickets
no index	12.766, 12.781, 12.718
bobbah index 	0.110, 0.109, 0.110
jordie index	0.000, 0.000, 0.000

getTicketsForRound
no index	1.468, 1.484, 1.469
bobbah index	0.016, 0.016, 0.015
jordie index	0.016, 0.016, 0.016

getSingleTicket
no index	0.266, 0.250, 0.281
bobbah index	0.015, 0.015, 0.015
jordie index	0.015, 0.016, 0.016

getTicketsForCindex
no index	17.078, 17.171, 17.094
bobbah index	0.015, 0.016, 0.016
jordie index	0.016, 0.016, 0.015
```

I think the 0.015/0.016 times are limited due to the database engine putting together joins and unioning indexes so I'm not sure an index won't really speed that up anymore. The first query I'm doubtful of the accuracy but despite multiple attempts I couldn't get it to return anything but 0 so I guess it's fine?

Either way this is one less index on the table so that's better.

**Comment by AnturK** [comment]
@bobbahbrown What about jordie version ?

**Comment by bobbahbrown** [comment]
oops sorry brain fart, i for some reason assumed jordies changes automagically went into my branch ill do that now

**Comment by bobbahbrown** [comment]
@MrStonedOne assuming all looks good with the changes i just committed you will want to drop the indices i added for ned and toss up those indices that jordie proposed (that are now in this pr)

**Comment by AnturK** [comment]
This is minor db bump so i'll just merge this now.

**Pull request merged**
