### PR TITLE
Improves box sprites

### PR DESCRIPTION
**Pull request by TrustyGun**
:cl:
imageadd: Box sprites are improved.
/:cl:

This PR is intended to be a alternative to #24425, so if that is merged this should be closed and vice versa.

image
image
image

These sprites are modifications of the original ones made by @Militaires, intended to address complaints made about them (too flat and detail loss mainly). 

Please give crictism

### CODE REVIEW

**Comment by sawrge** [comment]
:+1:

**Comment by CakeQ** [comment]
sexy

**Comment by Cheridan** [comment]
make sure the sprite is actually centered too please

**Comment by CakeQ** [comment]
Yeah if possible move the box sprites up a bit so that they don't appear to be falling off of tables

**Comment by Armhulen** [comment]
I like them but the syndicate boxes should look way more syndicate-y

**Comment by Kromgar** [comment]
Syndicate boxes don't look red and black enough

**Comment by Ausops** [comment]
they look about as good as you can get for what it is

im not sure how ss13 boxes open up but a line on top might make it just a bit more recognizable as a storage device otherwise pretty good

**Comment by OtherDalfite** [comment]
Darker syndie box please! Other than that they are far better than the current new box sprites.

**Comment by dannno** [comment]
I'm not really a fan of the rounded corners, personally
Cardboard isn't really like that

**Comment by Kromgar** [comment]
@dannno

After my mail carruer gets done with my boxes they are rounded

**Comment by Ausops** [comment]
being mishandled and abused in spacemen bags will do that too

10/10 attention to lore

**Comment by TrustyGun** [comment]
New syndie box:

image

**Comment by Aloraydrel** [comment]
That's a lot better

**Comment by WJohn** [comment]
I'm okay with these.
👍

**Comment by Militaires** [comment]
i was gonna do full on ISOMETRIC with massive indentations ausops style but here you come, like a madman, and edit the existing boxes' sprites to be rounded at the corners and cuter and everyone changes their mind.

absolut madmin

thank you trustygun you are my trusty gun

ss13 boxes dont open from the top that red strip is the flap that goes inbetween the doubled layer of cardboard

**Comment by Militaires** [comment]
also: im not a fan of the completely cyan abductor box maybe have it darkish purple like abductor glean metal.

also: make sure to follow spaceman 1.6 palette

**Comment by dannno** [comment]
you don't have to follow the palette it's not enforced, and it's not even finished

**Comment by TrustyGun** [comment]
i decided not to use the palette because i feel it is a little bit too limiting for my tastes

**Comment by XDTM** [comment]
Abductor box should probably be black/dark pink with the panel in green.

**Pull request merged**
