### PR TITLE
Adds two new changeling abilities

### PR DESCRIPTION
**Pull request by ghost**
Changelings now have Augmented Eyesight and Strained Muscles.

**Augmented Eyesight** costs two DNA points. When active, it lets the user have thermal vision and night vision, similar to a xenomorph.

**Strained Muscles** costs one DNA point. When active, it lets the user run at hyperzine speeds but take rapid stamina damage. Standard weight restrictions still apply. Stamina damage increases over time.

I was considering not making this PR but I accidentally clicked the "create" button and I've been meaning to PR it for a while so I decided not to close it instantly.

Possible change: Make augmented eyesight do eye damage while active? Would make it more balanced so they can't just have infinite night/thermal vision.

Tested and works fine. Augmented Eyesight _might_ cause problems but in my latest few tests it hasn't.

### CODE REVIEW

**Comment by Anonus** [comment]
These are probably actually worth two and one points, respectively, as augmented eyesight isn't nearly good enough to have a three-point cost(for comparison, the spacesuit is 2 points) and strained muscles has a huge downside.

**Comment by Xhuis** [comment]
The fast-movement one I can understand, but I was really reluctant to have a low cost for the eyesight because it's such a powerful asset. I'll see what other people think and if they agree I'll lower the cost.

**Comment by Perakp** [comment]
If you want to have a downside to passive abilities, you can use chem_recharge_slowdown like mimic voice and the spacesuit mutation do. Taking damage for using your abilities is kinda annoying.
These costs look fine, but I wouldn't object if they were 2 and 1, either way is fine.

**Comment by AlexCrimson** [comment]
Thermals? Yeah that is quite overpowered. I swear ling is becoming more and more like Traitor every time it gets an update. Next i guess lings will have some ability to detach part of themselves and turn it into a bomb?

**Comment by Anonus** [comment]
Ling currently can't just be ling because nobody knows what that is or how to make it more like that, so we're just making it weak nonhuman traitor instead.

**Comment by AlexCrimson** [comment]
Ling is a stealthy alien that impersonates and only kills when necessary, i thought. considering we now have much easier methods to clone husked bodies i dont see why we cant just re-add para sting.

**Comment by GunHog** [comment]
Yes, I like the idea of Predator vision - although I do agree with lowering the cost to 2, nothing else costs 3 points! The Strained Muscles power is balanced by its significant drawback, as stated before me. It is probably fine at its current cost, though.

**Comment by Xhuis** [comment]
Will push a new commit soon.

**Comment by Xhuis** [comment]
Reduced the cost of the abilities to 2 and 1 respectively.

**Comment by GunHog** [comment]
Yay! :+1: Murge pl0x

**Pull request merged**
