### PR TITLE
[s]fixes qdel lag from computers in chasms

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This might need a quick merge, but i'll test it first.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
good to go

**Comment by Core0verload** [comment]
Did you tested it? AFAIK computer parts remove themselves on qdel.

**Comment by MrStonedOne** [comment]
yes

**Comment by MrStonedOne** [comment]
There might be some hickup with something not qdeling properly, I'm not ruling that out at all, but it doesn't cause the server to use 500% cpu and tick a frame every 3 seconds.

I'll leave the rest to somebody who knows more about this system then i do

**Pull request merged**
