### PR TITLE
[NEEDS SPRITE] Adds an achievement for bladeless heretic ascensions

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This adds a new achievement, "While You Studied The Blade...", for ascending as a heretic without crafting or using a blade.

This is tracked somewhat thoroughly, with a "used_blade" flag on the heretic antag datum, which will be set if you ever complete a blade crafting ritual - and, to prevent potential cheesing by having another heretic craft and give you blades - the flag will also be set if you ever attack with a heretic blade, or smash one to teleport.

***I NEED A SPRITE FOR THIS, MARKED AS DRAFT UNTIL THERE IS A SPRITE***

## Why It's Good For The Game

it's a fun challenge.

## Changelog
:cl:
add: Added a new achievement for ascending as a heretic without crafting or using a blade at any point.
/:cl:

### CODE REVIEW

**Comment by Absolucy** [comment]
okay so I've been given so many good name ideas and I can't decide, so here's a strawpoll lol https://strawpoll.com/e7ZJaY8JGg3

**Comment by Jacquerel** [comment]
I will be honest I don't really see the value to having this in the game.  
Achievements themselves are of course kind of pointless but I think generally we'd want achievements for things which are impressive to do, that we want players to try, or that are funny or interesting in some other way. I don't think this really checks any of those boxes.

It's certainly more challenging than _using_ a heretic's blade but refraining from doing so isn't like... interesting in any particular way? You just use any of the many other weapons that exist in the game and otherwise don't do very much else. 
Why this and not like... "without using the spooky hand" (something else that I think is largely a boring and meaningless challenge)? Personally I don't want to see a proliferation of pointless and largely unintersting self-imposed challenges added to the game.

**Comment by Time-Green** [comment]
I don’t think I can do this anymore

**Comment by the-orange-cow** [comment]
It would be funnier if you could only do this via Blade ascension.

**Comment by EnterTheJake** [comment]
Doesn't seem to be fun or interesting for either the crew or the Heretic honestly.

It's not even that difficult of an achievment in and on itself, lots of heretics already use sec gear instead of blades due to how powerful the Grasp + Baton combo is.

**Comment by Loafin34** [comment]
no blade break.

**Comment by Absolucy** [comment]
@the-orange-cow Actually, yeah. That's. A really funny idea.

**Comment by LemonInTheDark** [comment]
you bothered cause you thought it was cool 4head, it's ok to thinks things are cool/funny

**Pull request closed without merging**
