### PR TITLE
Nerfs cryo's effect on necrotic burns so it doesn't instantly remove it, and instead slowly heals its necrosis

### LINKED ISSUE #59001: Cryo cell with cryoxadone can heal burn wounds with infection level maximum
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Have someone with burn wound that has infection level: "The bodypart has suffered complete sepsis and must be removed. Amputate or augment limb immediately." 
Put him to cryo cell that is working properly and wait for it to end healing.
Check your speciment with health analyzer and realise that he doesn't have burn wound.

I think thats a bug as no description in game tells about healing complete sepsis and wiki doesn't contain such information either.

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Cryo no longer removes burn wounds where sepsis has set in, instead slowly healing the sepsis until it has reached normal levels - very slowly, mind you, to incentivize just chopping that limb off/augmenting.

Closes https://github.com/tgstation/tgstation/issues/59001

Needs https://github.com/tgstation/tgstation/pull/78124

## Why It's Good For The Game

It's always really bugged me how something so intense and hard to get (you'll only really see it at T3) is so easy to remove. While I understand the need to have some way to recover from it, I also think you should be heavily incentivized to just augment the limb or chop it off to stop the toxin damage.

As it stands, the urgency of burn wounds is heavily reduced by the fact you can just cryo someone and be totally done with it. While you can still DO this, it takes a LOT longer, especially at higher severities, ESPECIALLY at roundstart setups. 

## Changelog

:cl:
balance: Burn wounds can no longer be removed by cryo if necrotic. Instead, they will slowly remove necrosis at a heavily reduced pace
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
haha forget this was a branch of my refactor

**Comment by nikothedude** [comment]
needs https://github.com/tgstation/tgstation/pull/78124

**Comment by GPeckman** [comment]
I still think that tier 3 burn wounds are way too common for how hard they are to fix (without cryo). And they'll only become more common; the damage from being on fire is likely going to be buffed soon.

**Comment by HoodMilk** [comment]
You should be able to fix them with synthflesh somehow.

**Comment by GPeckman** [comment]
Yeah, it is definitely weird that tier 3 burns are harder to fix then literally being husked.

**Comment by YehnBeep** [comment]
Cryo is already glacial, locking people away and unconscious for so long. I don't think slowing it down even more makes for compelling gameplay, particularly when it being used tends to mean medbay isn't going strong to begin with.

**Comment by nikothedude** [comment]
I would like to remind everyone that burns can be immediately and permanently fixed via augmentation/amputation

**Comment by nikothedude** [comment]
> I would like to remind everyone that burns can be immediately and permanently fixed via augmentation/amputation
> 
> IN fact, this is my ideal: I remember a time where burns were scary, because you had to race against the infection so you didnt have to augment. Allowing cryo to heal it is frankly a stopgap in my eyes, but a necessary one since augments arent always guaranteed, and the head/chest can be infected

I may at some point rebalance wounds to be based off this principle while maintaining the current loop for heads/torsos

This principle being: Race against the infection to try and save the limb, but amputate through ghetto or proper means if it gets too bad

**Comment by Sealed101** [comment]
closes #59001

**Comment by Pickle-Coding** [comment]
> You should be able to fix them with synthflesh somehow.

That sounds dumb. Just cut off your leg and get a new one. If your chest gets those burns, chop off your head and put it on someone else's body. If your head gets those burns, pull your brain out and put it on someone else's head. That was the intended solution if you let sepsis take over.

**Comment by moocowswag** [comment]
This just punishes the players who got hit by captain spraying wildly into a crowd of people trying to kill an individual tider with longer gay baby jail.

**Comment by nikothedude** [comment]
Ill let a maintainer have the final say on this PR

**Comment by moocowswag** [comment]
Atleast this pr makes spaceacillin more relevant but thats the only upside i can think of

**Comment by RikuTheKiller** [comment]
I'd rather have the cryo healing replaced by a more innovative healing method.
Being augmented just because some dude shot you with a laser gun a couple times is... well... not very fun.
Especially if your entire body got locked up by a plasmafire. No-one likes bodyswaps.
Maybe something to do with synthflesh? Maybe just slow down the burn healing based on necrosis?
Hell, you could make this PR work much better simply by making the necrosis heal fairly quickly instead of just extending their "unconscious in tube" sentence to the rest of the round.

**Comment by MercuryArrow** [comment]
Adding to the din of negative responses here. T3 burns once they go septic are effectively the most annoying thing in the codebase to heal currently without cryo, with most targeted burn healing methods and surgeries simply failing to address the problem.  Slowing this even further to incentivise augmentation or replacement is only compounding a problem that most people despise to begin with and particularly impacts antagonists who may not have the luxury of walking into robotics to ask for a replacement or lowpop rounds with limited medical and robotics staff.

**Comment by Moonlit2000** [comment]
Sepsis wounds not healing from cryo would be fine if augmentation actually healed them properly, half the time augmenting the limb doesn't seem to actually fix the sepsis somehow, also in the one in three chance that it's on the chest or head, medbay doesn't have the stuff to augment those anyway.

**Pull request closed without merging**
