### PR TITLE
Fixes shuttles killing AI camera eyes

### LINKED ISSUE #19279: Shuttle docking deletes ai camera eye mob and possibly prevents it from respawning until undocked
Server revision compiled on: 2016-07-11
8493c7ac9018e0ed93f9682349f4ac7747d97e95 

I was the AI and I had the center of my screen (which is where the ai eye mob is) over one of the mining shuttle ripples before it docked at the station. When it docked my screen went black and I was forced back into my core vision.

When the mining shuttle first docked and it blanked out my screen, it looked just like the screenshot in #18906 , but it quickly returned to my core view like when you're not looking through the cameras. 

Nothing I did could fix it, re-logging, cancel camera view, view core ; When the mining shuttle left again though I got this message "Error: Eyeobj not found, creating a new one..." or something very similar to that and then my vision returned and I could move again. 

@Niknakflak said something about it deleting my camera eye mob

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #19279

this wasn't even my bug but because mso is an ass I fixed it

### CODE REVIEW

**Comment by coiax** [comment]
put a comment in, explaining why

**Comment by MrStonedOne** [comment]
Or how about asshats can not change shit without understanding why things are the way they are..

**Comment by coiax** [comment]
Difficult to understand the way things are if they're not declared

**Comment by coiax** [comment]
tbh I'm amazed there's a /mob that's not /mob/dead or /mob/living.

**Comment by MrStonedOne** [comment]
Sorry shit doesn't fit into your narrow minded expectations, but there exists other states of mob then living or dead. mob means moveable object. in byond it means player controllable object.

Maybe you should have understood shit better before changing types.

**Comment by ChangelingRain** [comment]
mso get the fuck out of my pr and stop being an ass

**Comment by optimumtact** [comment]
@MrStonedOne no need to approach this that aggressively, please keep feedback professional, it will greatly improve the experience for everyone.

**Pull request merged**
