### PR TITLE
Nuclear bombs are now points of interest

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: Nuclear bombs are now points of interest. Never miss a borg
steal a nuke from the syndicate shuttle again!
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
poi bloat is gonna be a problem in a few months

**Comment by PKPenguin321** [comment]
is it possible to only make them a POI if they're armed?

**Comment by Incoming5643** [comment]
could just make a dedicated PoI list soon

**Comment by xxalpha** [comment]
Minimap POI when?

**Pull request merged**
