### PR TITLE
Fireproofs holofans

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
I'd like it to go on the record that i sacrificed 8 gbp for this.

Please give me no gbp update if them melting is unintended, i seem to get conflicting reports on whether they should melt or not.

## Why It's Good For The Game
Nicer to use

## Changelog
:cl:
balance: atmos holofans are now fireproof
/:cl:

### CODE REVIEW

**Comment by capsaicinz** [comment]
grandiose thumbs down from me, holofans shouldn’t be an easy instant solution to containing fires if that’s what you mean to do w/ this

**Comment by Snowyypanda** [comment]
lovely change, i like it, keep up the good work!

**Comment by GuillaumePrata** [comment]
Holofans are an answer to too many Atmos game loops but at least you need to be cautious with them if fire is involved.

They are powerful if used preemptively but you can't just slap one in the middle of a burning SM and call it a day.

**Comment by LemonInTheDark** [comment]
@ExcessiveUseOfCobblestone yes honey

This isn't really intended per say? They're meant to block heat from moving across them, but that has nothing to do with them being fireproof.

Why do you wanna change it?

**Pull request merged**
