### PR TITLE
Phantom Maid Halloween costume

### PR DESCRIPTION
**Pull request by BLUREMOTE**
## About The Pull Request

Add the "Phantom Maid" costume set for halloween, inspired by the main character of "Phantom Rose". The whole set is made of:
The uniform: The Phantom Maid Uniform
The suit: The Phantom Maid Apron
The headgear: The Phantom Maid Headband
The eyewear: The Phantom Maid Eyes
The shoes: The Phantom Maid Stilettos
The neckwear: The Phantom Maid Scarf & Shoulder neckpiece
The gloves: The Phantom Maid gloves
The item: The Toy Red Knife (can be stored in the apron suit storage)
phantommaidpreview1
image

## Why It's Good For The Game

More costume for halloween is always nice.

## Changelog
:cl:
add: Phantom Maid Costume set
add: phantom maid uniform
add: phantom maid apron
add: phantom maid headband
add: phantom maid eyes
add: phantom maid stilettos
add: phantom maid scarf and shoulder neckpiece
add: phantom maid gloves
add: toy red knife
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
so while this is a good outfit is it really worth changing to fulpcode

**Comment by BLUREMOTE** [comment]
forget that pull, I dropped it in the wrong place

**Comment by CosmicPhoenix** [comment]
Smh all these newbie toothpasters PRing to /tg/ instead of Fulp

**Comment by AtlasRules** [comment]
Haha you fell for the same mistake as me Blu

**Pull request closed without merging**
