### PR TITLE
New xeno queen and praetorian sprites.

### PR DESCRIPTION
**Pull request by WJohn**
:cl: WJohnston
tweak: Queens and praetorians have new sprites!
/:cl:

So I was never happy with my original queen and praetorian sprites.
Long story short, they come from a _very_ long line of cleanups, improvements, and partial redos over the years.

So I decided to just murder that line entirely and make brand new ones from scratch.

...

So here they are!

Queen: Old on top, new on bottom.

Praetorian: Old on top, new on bottom.

Also fixes 3rd stage larva sprites by removing some dupes of the old ones that took precedence.

### CODE REVIEW

**Comment by GunHog** [comment]
WJ is an absolute MADMAN.

**Comment by WJohn** [comment]
This only took at least 40 hours.

**Comment by ATDoop** [comment]
I like it. They look bonier and creepier.

**Comment by SpyroZeppeli** [comment]
+1 approve

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by Nienhaus** [comment]
Alien queen maid dress when Mr. J?

**Comment by PKPenguin321** [comment]
hahahaha why are their heads so skinny from the sides
xenos are secretly flatfish confirmed?

**Comment by WJohn** [comment]
The queen actually has an extremely thin head, as does the praetorian.

The original sprites were way overly bloated. Everything about them just felt *fat*.

**Comment by SpyroZeppeli** [comment]
Going off https://parttimemonster.files.wordpress.com/2015/04/xenomorphqueen.jpg it actually should be a little bit bigger, but it's not important tbqh

**Comment by WJohn** [comment]
The scale and design are actually largely based on this http://static.comicvine.com/uploads/original/11111/111118857/4571431-school_project___xenomorph_study_by_scootaloopox-d4q3w2t.jpg
Though I had to tone the queen down just a tad because even that would be too big to fit in 64x64.

**Comment by SpyroZeppeli** [comment]
Shit like this makes me wish SS13 wasn't dependent on Byond

**Comment by Core0verload** [comment]
Side views lack depth/perspective.

**Comment by WJohn** [comment]
You can blame our flat in front style for that one, there's only so much I can do to make something look deep when you are not allowed to have angles.

**Comment by Core0verload** [comment]
Even the old ones have more depth.

**Comment by Bawhoppen** [comment]
WJ why must you ruin all the xeno fun

**Comment by SpyroZeppeli** [comment]
I don't know what you guys are on about, apart from the front/back view arms on both of them, these look way better. The arms look a bit off, though I'd merge this.

**Comment by PKPenguin321** [comment]
>I don't know what you guys are on about

have you tried looking at the east sprite's head

**Comment by SpyroZeppeli** [comment]
Still looks better than the old one

**Comment by Nienhaus** [comment]
Looks better :+1:

**Comment by Cheridan** [comment]
>no more phat xeno queen booty

um excuse me what are you doing

**Pull request merged**
