### PR TITLE
Buffs Lizards

### PR DESCRIPTION
**Pull request by KazeEspada**
Lizards now consume space bees. I intended to do this earlier but Remie made me remember to do it.

### CODE REVIEW

**Comment by bobdobbington** [comment]
We're gonna need more lizards

**Comment by RemieRichards** [comment]
:-1: lizards can't beat bees.

**Comment by KazeEspada** [comment]
Wags-His-Tail can eat plasteel if you make him.

**Comment by RemieRichards** [comment]
but not bees.

**Comment by KazeEspada** [comment]
Please leave your bias outside and review the code.

**Comment by optimumtact** [comment]
Lizards cannot eat bees, this pull will be closed

**Comment by KorPhaeron** [comment]
Which is stronger?
Lizards: 1
Bees: 20

THE PEOPLE HAVE DECIDED

**Comment by KazeEspada** [comment]
Memes, literal memes.

**Pull request closed without merging**
