### PR TITLE
Shadowshrooms are much less powerful

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Shadowshrooms of lower potency are much less able to blanket the station in darkness.
/:cl:

Also, logging.
New pics;

One seclite

Two seclites

### CODE REVIEW

**Comment by XDTM** [comment]
blueshrooms

**Comment by ChangelingRain** [comment]
Just as a note the pictures are max-potency shrooms and full coverage, which I didn't wait around to get, will still produce darkness, but it won't be as able to totally eliminate light.

**Comment by WJohn** [comment]
BLUUUUUEEEEE

Should probably not be THAT blue, jesus.

**Comment by uraniummeltdown** [comment]
Don't give in to them, this isn't necessary, players love shadowshrooms as they are.

**Comment by Xhuis** [comment]
[i'm shroom da ba dee](https://www.youtube.com/watch?v=68ugkg9RePc)

**Comment by PKPenguin321** [comment]
>spawn in arrivals late as detective
>step out and it's pitch black
>turn on PDA light but it's still completely 100% dark
>realize slowly that it's shadowshrooms
>start dying to a pressure hazard I can't see
>can't go through halls because of barriers (firelocks?) I can't see
>eventually stumble into maintenance
>stack a flare, flashlight, cigarette, and welder for light
>can now barely make out half of my characters face if I'm close enough to a light fixture in the hallway
>die a minute later to spiders I can't see

**Comment by uraniummeltdown** [comment]
Goof has a great suggestion of making weedkiller/pest spray (chem is atrazine?) instantly kill shrooms. That was chem grenades can get easily clear an infestation

**Comment by jughu** [comment]
When will glowcaps grow red? 😏

**Comment by ShadowDeath6** [comment]
putting it at 1/4 of what it was seems kind of a big change

**Comment by PKPenguin321** [comment]
It's reasonable because darkness stacks, so when a shadowshroom spreads one time its darkness power has effectively doubled. When they spread again, their collective darkness level has effectively quadroupled, then x8, then x16, x32, etc.

The fact they were as strong as they were in the first place seems like an oversight

**Comment by XDTM** [comment]
i think that shrooms had a check to prevent them from growing too close to each other, did they always cover all tiles?

**Comment by Armhulen** [comment]
Just make shadow emission on another plant, and remove shadowshroom. They should NOT be able to spread with like 10 mins of botany work.

**Pull request merged**
