### PR TITLE
Fixes being able to run into your own bullet 

### LINKED ISSUE #10315: You can run into your own bullet really easily
if you run forwards while shooting, you'll hit yourself. A lot.
untitled

I assume it's only a real issue with burst fire weapons, but I'm sure someone else will know more then me, but I was hitting myself with 2/3 shots per burst, which is pretty retarded.

### PR DESCRIPTION
**Pull request by phil235**
(both as a mob or inside a mech).
Fixes #10315

Remove the mech immobilization when firing.

### CODE REVIEW

**Comment by WJohn** [comment]
So you can no longer collide with your own bullets? I thought the original "fix" with mechs was to increase the time it took before you could start walking again.

**Comment by phil235** [comment]
The mech fix wasn't enough, you'd have to immobilize the mech for the entirety of the burst to prevent the issue that way.
With this new fix, I could technically remove the immobilization time entirely I think.

**Comment by WJohn** [comment]
Yeah, it'd make burst weapons slightly better, and I'm all for a bit more lethality like that.

**Comment by Dorsisdwarf** [comment]
It also means that the gatling gun can rise again!

**Comment by Firecage** [comment]
Huh, I thought the bug of running into your own bullet was fixed long ago?

**Pull request merged**
