### PR TITLE
trainship hijack deathmatch map

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

image

https://github.com/tgstation/tgstation/assets/70376633/7fad8e32-71df-40dd-afd7-fb4524d5a187

adds the Trainship Hijack deathmatch map

it is a few flying trains in Tizira being boarded and stuff by cowboys its pretty cool i think

also allows changing turf reservation type of lazy templates

## Why It's Good For The Game

deathmatch was lacking some rootin'-tootin' wild west shootout

## Changelog
:cl:
add: trainship hijack deathmatch map
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
pretty cool

**Comment by HoodMilk** [comment]
It should make the goofy scream when u fall off the train but otherwise very nice

**Comment by carlarctg** [comment]
stolen from tf2

**Comment by mc-oofert** [comment]
> stolen from tf2

I havent played TF2 for 4 years

**Comment by Toastgoats** [comment]
Now I want a gas giant station with this background, with moths. Saturniidae if you will

**Pull request merged**
