### PR TITLE
Fixes only mimes being able to scream

### PR DESCRIPTION
**Pull request by nervere**
:cl: Nervere
fix: Fixed only mimes being able to scream. Now everyone can express their existential dread... except for mimes.
/:cl:

@Qustinnus dummy

### CODE REVIEW

**Comment by InsaneKatrina** [comment]
speedmerge

**Comment by wesoda25** [comment]
feature

**Comment by DapperMola** [comment]
I Have No Mouth And I Must Scream.

**Comment by Tlaltecuhtli** [comment]
fuckup of the year?

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
