### PR TITLE
Disables radiation contamination.

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Sets #RAD_MINIMUM_CONTAMINATION to INFINITY, effectively making radiation unable to contaminate anything.

Also gets rid of uranium radiation, since uranium sheets are handheld and can be hidden in a bag.

## Why It's Good For The Game
The biggest underlying issue with radiation is that it can contaminate other objects. Irradiated objects are supposed to glow green, but an item hidden in a bag (or even held in a hand) will not be visibly radioactive to other players. Allegedly there's also a possibility of organs becoming contaminated, which sounds like not fun for anyone involved.

Contamination ought to be either completely reworked or completely removed. However, we're on a short window to make radiation not terribad or we risk losing all of radiation completely. With this change, only objects specifically coded to release radiation will do so, and nothing else will be put into that state. This means standing next to an active supermatter with no gear on is bad for your health, but you won't drag medbay down with you.

## Changelog

:cl:
balance: Radiation no longer spreads to objects in its best attempt to out-do virology as a death plague.
balance: Uranium sheets are no longer radioactive.
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
This PR does not remove the green glow. The green glow signifies contamination. This PR removes the ability to contaminate things. Anything contaminated by design will still glow green (the SM is not contaminated, by the by, it just produces rads).

The lack of green glow is supporting evidence that this PR works as intended. If you glow green, you're putting out rads and possibly harming other people.

**Comment by Bawhoppen** [comment]
I think this helps fix the issue of radiation's unknowability by limiting it to where you might expect it to originate from: piles of uranium in the hallway and reactor cores. This preserves the intrigue of having the ambient and terrifying threat that radiation poses, while eliminating the cheese and broken-ness of the spreadable contamination mechanic.

**Comment by Bawhoppen** [comment]
@ATH1909 Oh I didn't even notice that. Well the idea is the same either way.

**Comment by KittyNoodle** [comment]
Your modification to uranium effect more than just sheets, it makes anything not made out of uranium not radioactive.
Also the super matter does not emit rads anymore, so the HFR and chem is the only way to make contaminating radiation.

**Pull request closed without merging**
