### PR TITLE
"Actually on second thought and some testing these really aren't as significant as I thought they were" buffs to smoke and foam.

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About The Pull Request
This PR buffs smoke and foam in two ways.
- It increases the hardcap on carried reagent volume for smoke to 1000u. This is on par with foam, which also has a reagent multiplying effect that smoke does not have.
- It permits reactions within both smoke and foam. This could be more dangerous as it could allow for smoke/foam to make more smoke/foam, but these reactions would consume the contents of the smoke and foam so it shouldn't cause too much trouble.

### What this means for you.

In all honesty these changes won't make chemical weapons significantly more powerful than their current state.

While you would think that doubling the carrying capacity of smoke would make a significant difference in reality it really doesn't. The vast majority of chemical delivery methods had payload capacities too low to run up against the old hardcap. Of the ones that could only chemical payloads really have the capacity to take full advantage of it and when was the last time you saw an antagonist actually use a chemical payload with smoke? I don't think I ever have. For those still concerned about balance: a smoke mix with a 500u blend of acids optimized for damage deals 52.35 total damage each tick on an unprotected target. The same mix at 1000u deals 53.1 total damage each tick. This is a difference of 1.5%, hardly enough to notice.

On the other hand, the change to make foam mixes allow reactions within the foam _would_ be a massive change..... but reactions have already been allowed within smoke for months now. That's probably been the case since #56019 dropped actually. All this PR does it allow them within foam as well. On that note, after some testing foam is significantly less potent than smoke in this manner for a few reasons. Firstly, foam is blocked by a multitude of common objects that smoke simply isn't: tables, lockers, and crates for a start. Secondly, foam divides the reagents used to make the foam by the range* of the foam when it is initially created. As such it is necessary to cram about twice as much reactant into the foam to get the same effect as the same mix (but smoke) with a lower dispersal range.

## Why It's Good For The Game
First off, the fact that smoke and foam have carry volume hardcaps at all is not well communicated. To my knowledge it is not mentioned anywhere in game or on the wiki. Essentially the only way to figure out that they exists is either to code dive or to build high density smoke chemical payloads and notice that they are somewhat less effective than they should be. I cannot remove the hardcaps entirely so the next best thing is making sure that both hardcaps are in the same place.

Secondarily, I have been enjoying applying delayed-reaction smoke for about a month now and haven't really seen a reason for it to be blocked in foam as well. I would like for other chemists to try to also use delayed-reaction smoke as well because I find it interesting and I'm pretty certain I haven't fully explored what is possible using it. After doing some testing this should not notably effect game balance as foam is significantly less effective than smoke in this manner of application.

## Changelog

:cl:
balance: Improvements in the smoke powder formula have resulted in a doubling of the maximum possible carry density for the resulting clouds. This brings it to par with the fluorosurfactant formula in this area.
balance: Fluorosurfactant no longer acts as an arbitrarily powerful accelerating catalyst in an emulsified state. Research into foam based thermobaric weaponry has begun.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
so things can react/combine in smoke/foam? oh hell yeah mass destruction time

**Comment by TemporalOroboros** [comment]
> so things can react/combine in smoke/foam? oh hell yeah mass destruction time

They already can in smoke. That's why the changelog only mentions adding it to foam. Don't ask me how that's happening. I have no idea.

**Comment by LemonInTheDark** [comment]
The limit is a sanity thing, I am uncomfortable with removing it

**Comment by Ryll-Ryll** [comment]
[](https://i.imgur.com/1e1N5A8.png)

Considering both oranges and potato (as well as myself) seem against this, I don't think it stands much chance getting merged

**Comment by TemporalOroboros** [comment]
> The limit is a sanity thing, I am uncomfortable with removing it

I'll can scrap the limit changes. Give me a bit.

**Comment by TemporalOroboros** [comment]
> The limit is a sanity thing, I am uncomfortable with removing it

I've reinstated the limit. They are now both limited to 1000u of carried reagents.

**Comment by Ryll-Ryll** [comment]
Can you talk some more about the practical effects of the changes in this PR and why they're good for the game? Because as-is, it's very unclear what differences this makes (how much more deadly are hellfoam/hellsmoke grenades?), and why they're good for the game.

**Comment by LemonInTheDark** [comment]
Relaxing the DNM, agree with ryll

**Comment by TemporalOroboros** [comment]
@Ryll-Ryll, @LemonInTheDark 

After some testing the buffs are actually a lot less potent than I thought they would be.

The volume buff on smoke barely affects the mixes I decided to test with it. An acid smoke mix optimized for damage at the hardcap hits 52.35 overall damage per tick on an unprotected target with the old hardcap. With the new hardcap that gets bumped up to 53.1 overall damage per tick. That's a 1.5% increase, which is hardly worth noticing. Maybe there are other mixes that have more of an effect, but the difference between having 50 units of toxins and 100 units of toxins crammed into your bloodstream is the difference between being very dead and being slightly more very dead.

Allowing reactions in smoke is just about as minimal. It's already possible to make a mix that reacts within a smoke cloud, this just extends that to foam. On that note, I've tested it and foam is actually significantly less potent when used that way. The range divisor is applied the instant the foam is created so you actually have a fraction a (at most 1/3) of the reactants you put into the payload being spread around by the foam. As a result you need at least 3 times as much payload to cause the same effect as you can with smoke for the same range.

Overall this mostly just removes some unintuitive differences between smoke and foam. Neither the hardcap nor the reaction difference are communicated anywhere ingame or on the wiki so this should reduce overall code-diving.

**Pull request merged**
