### PR TITLE
Make PKA and PKC fireproof

### LINKED ISSUE #83851: Miners on fire will burn their tools to ash even if they're wearing fireproof armor
## Issue Summary
After #83616 was merged, items held in hand while on fire will also catch fire. This applies to Proto-kinetic crushers and accelerators, the two main methods of dealing damage to mobs available to miners. This is in spite of the fact that there are multiple sets of fireproof armor that miners can obtain, meaning that using said armors for their intended purpose comes with a high chance that your weaponry will burn away mid-fight (as well as all of the trophies you've painstakingly gathered in the case of crushers). I doubt that this is intended behavior, since what would the point of fireproof armor be if your primary tool gets destroyed anyway?

## Reproduction:
1. Wear any fireproof set of armor (Ash drake, H.E.C.K. suit, Godslayer, etc.)
2. Hold your trusty PKA/Crusher in hand.
3. Set yourself on fire.
4. Wait for it to crumble to ash between your fingers (may be nearly instant or take up to around a minute to happen).

### PR DESCRIPTION
**Pull request by Goat-Real**
## About The Pull Request
adds a `resistance_tag = FIRE_PROOF` to both the PKA and PKC

## Why It's Good For The Game
Miner equipment should be fireproof. The explorer suit does not burn so their weapons should not either.
fix #83851 

## Changelog
:cl: Goat
qol: Mining's PKAs and PKCs are now fireproof.
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
I tested this earlier today, and I could not cause a PKA to ignite solely from a bonfire. I suspect that lava is how it got ignited in the issue report, and I don't think this change will do anything to affect that.

**Comment by LePiromano** [comment]
jesus christ thank god if my crusher with one-in-a-shift trophies burnt to a crisp one more time i was going to actually cry

**Comment by improvedname** [comment]
hugbox

**Comment by GPeckman** [comment]
Oranges just reverted the PR that allowed held items to burn in the first place so... I think this PR is unnecessary?

**Comment by Goat-Real** [comment]
maybe? I saw in coder-general however that we're keeping this open.

**Review by Jacquerel — APPROVED** [review]

**Pull request merged**
