### PR TITLE
Cargo can order stamps; camo stamp has action button

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
tweak: Added action button to chameleon stamp
rscadd: Added APPROVED and DENIED stamps to Bureaucracy Crate
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
chamo stamp should be like the agent ID in that only traitors know how to use it, that way it can't be so easily metagamed

**Comment by coiax** [comment]
It's only obtainable in the camo box which is literally full of action item camo buttons.

**Comment by Iamgoofball** [comment]
@PKPenguin321 yeah chameleon functionality is just an action button because it allows me to add chameleon functionality to any obj in the game without any hassle

**Comment by Chocobro** [comment]
ok you do this and wax seals still don't have a pr ok ok ok ok

**Comment by Iamgoofball** [comment]
@Chocobro soon

**Pull request merged**
