### PR TITLE
DELTASTATION: Atmopsherics revamp, engineering touch-up (+Beefs up service maintenance)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

This PR completely overhauls a good chuck of Deltastation's engineering department, returning a good portion of service maintenance lost in the Service overhaul. 

Notable changes:
- Atmospherics is completely redone.
- The engineering lobby is also completely redone.
  - As a part of this, the CE's office, the transit tube, and the grav gen were shifted around as well.
  - Shared storage and the breakroom were also nudged a bit.
- Engineering proper received numberous tweaks. 
  - Decal work, some minor layout changes. 
  - Overall adjustment of the amount of gear given. 
- Service maintenance now has three more rooms and an alternative path.
  - An old atmospherics room, an abandoned garden, and an art room.
- Engineering-science maintenance also received very very minor changes. 

L_deltaatmosperhaps

<details> 
<summary>(Pipes and stuff shown in this dropdown): </summary>

deltaatmosperhaps2 5

</details>

## Why It's Good For The Game

Deltastation's atmos is... very old. And the project room addition did it no favors. 
There was no consistent style between the two rooms, and none of it really meshed well. Delta's atmos was really designed with the SM being adjacent and it's obvious. 

Deltastation's engineering itself has not fared much better. It as so much resource creep, weird decalling, inconsistencies... This seeks to unify it with atmos.

Service maintenance lost a lot with the service revamp, it's something I was fully aware of and wanted to fix. So this gave me the opportunity to restore a bit of maintenance variety lost. 

## Changelog

:cl: Melbert
expansion: Deltastation: Atmosphics, Engineering, and Service Maintenance revamp!
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
I'm gonna miss the neat and orderly emitter room.

**Comment by Colovorat** [comment]
First of all I personally don't like that atmos big gas chambers are just in one big line, I liked that gases needed for air placed further from plasma/co2/etc
Secondly grav Gen would be pain in the ears for CE office, and even maybe room with lathe
Everything else is pretty pog, just some personal concerns

**Comment by MrMelbert** [comment]
> atmos big gas chambers are just in one big line

Unfortunately they was just no room to keep them on opposite sides of the room.

> Secondly grav Gen would be pain in the ears for CE office

Testing it, the grav gen is barely audible by the CE's locker, and quiet when sitting in their chair. Though i'm not against moving it back a bit.

**Comment by exymian** [comment]
very nice, thank you for adding a layer adaptor before a gas pump on the output pies of each gas chamber.

its looking great

**Comment by MrMelbert** [comment]
image

Gave a space gap between the CE's office and the grav gen so it's not too annoying.

**Review by Maurukas — CHANGES_REQUESTED** [review]
<details>
<summary>You have used partial undertile pipes for the public atmos hookups. This looks a little weird. Is it intended?</summary>

image
</details>


<details>
<summary>This storage room has no lighting</summary>

image

</details>

<details>
<summary>Two doubled wires</summary>

image

</details>

<details>
<summary>This door is set to maintenance access. This provides direct access to the interior of atmospherics from maint</summary>
This should probably be Atmos (24) not Maint (12)

image

</details>


<details>
<summary>The CE's office is disconnected from the main grid</summary>

image
</details>


There is a ton of work done with atmospherics piping here and I cannot find any flaws, disconnected pipes or incorrect connections. This tackles one of the oldest, most difficult areas of Deltastation that has been neglected for quite some time, and gives it a very unique, very usable atmospherics. This is incredibly impressive and I like the work you've done.

**Pull request merged**
