### PR TITLE
Pull Request That Makes You Say Yes

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Adds Powder That Makes You Say Yes

## Why It's Good For The Game

Yes

## Changelog
:cl:
add: Powder That Makes You Say Yes
/:cl:

### CODE REVIEW

**Comment by plapatin** [comment]
Yes

**Comment by TheChosenEvilOne** [comment]
Yes

**Comment by TooFewSecrets** [comment]
Yes.

**Comment by Magikarpet** [comment]
Yes

**Comment by Jalleo** [comment]
No

**Comment by cynic716** [comment]
Yes

**Comment by Tharcoonvagh** [comment]
No

**Comment by Nebulacrity** [comment]
Yes

**Comment by Tharcoonvagh** [comment]
But yes

**Comment by Tharcoonvagh** [comment]
Or neither

**Comment by optimumtact** [comment]
no

**Comment by Tharcoonvagh** [comment]
Lol

**Comment by ATH1909** [comment]
Yes

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes

**Comment by AcapitalA** [comment]
Yes

**Comment by Grantteen** [comment]
yes

**Comment by Twaticus** [comment]
yes

**Comment by MCterra10** [comment]
Stolen from hippie

**Comment by dootdoom** [comment]
No

**Pull request closed without merging**
