### PR TITLE
Mothmen who examine lit suspicious lanterns without flash protection now get hypnotized

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Suspicious lanterns are 2 TC moth-only traitor items that basically function as brighter than normal lamps. Since you're shelling out 2 TC for these things (and because a traitor moth getting hypnotized by their own syndicate lamp sounds like it'd be funny to see happen), I figured that I'd give them an additional ability: If a carbon with a negative amount of eye protection (as in, you need to be a moth or wear NVG or thermals or something to be hypnotized by this ability) and no mindshield examines a syndicate lamp (by shift+left clicking on it or the like; you can't just shove a syndicate lamp in a moth's face to hypnotize them), they will fall into a hypnotic trance similar to that caused by a hypnotic flash (note that the visible message for entering this trance is different from the normal "X stands still as their eyes seem to focus on a distant point" one (and the message given to the victim is also different)).

An extra parameter has been added to the trance status effect's on_creation proc; you can set it to false to remove one (is it technically two?) of the messages given by that status effect.

Suspicious lanterns have had their names changed to be "suspicious-looking lantern", and a hyphen has been added to their descriptions

An admin-only version of the suspicious-looking lantern (called the VERY suspicious-looking lantern) that can hypnotize people with just a non-positive amount of eye protection (and no mindshield implant) who examine it has also been added to the game, in case a moth traitor wants to do a 20 TC trade for it or something.

## Why It's Good For The Game

Suspicious lanterns aren't really worth 2 TC right now, and this is a cool, hard-to-activate effect that could lead to some interesting gimmicks (destroy lights around the station and distribute NVG, then trick people into examining your lamp, perhaps?).

## Changelog
:cl: ATHATH
tweak: Changed the suspicious lantern item's name to "suspicious-looking lantern".
tweak: Added a hyphen to the suspicious lantern's description.
add: Carbons with a negative amount of eye protection (mothmen who aren't wearing sunglasses or the like, for example) and no mindshield effect on them now get hypnotized when they examine a suspicious-looking lantern.
add: Added an admin-only version of the suspicious-looking lantern called the VERY suspicious-looking lantern that functions like the suspicious-looking lantern, but can hypnotize people who have an eye protection value of 0 (such as humans who aren't wearing any eye protection) too.
add: Added an extra parameter to the trance status effect's on_creation proc that will disable some of its messages.
/:cl:

### CODE REVIEW

**Comment by bobbahbrown** [comment]
unironically gives a big buff to the mothpeople metaclique

**Comment by ATH1909** [comment]
why is stuff breaking aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by shellspeed1** [comment]
rip using it to bribe moths

**Comment by CRITAWAKETS** [comment]
i kinda dont like how this makes negative flash cause the hypnosis instead of just moff people. Last time i checked i wasnt attracted to the lamp near my desk

**Comment by AdamElTablawy** [comment]
Since it's negative flash this means that lings with eye thermals will be hypnotized by this

This means that changelings are actually part moth and should be updated accordingly

**Comment by Shadowflame909** [comment]
No idea how this item will play out in action

Maybe moths will stop examining other moths

Don't really feel too good about having another version of the hypnotic flash in the traitor uplink

**Comment by ATH1909** [comment]
> No idea how this item will play out in action
> 
> Maybe moths will stop examining other moths
> 
> Don't really feel too good about having another version of the hypnotic flash in the traitor uplink

It should only apply to you examining the lamp DIRECTLY (as in, you can see its description), not just you examining a moth holding the lamp.

**Comment by ATH1909** [comment]
Would you guys prefer it if I added an ismoth() check to this?

**Comment by Shapsy** [comment]
But if the item name is literally "suspicious-looking lantern"... And you can see that that's the name by hovering your mouse over it, which is necessary to examine it... And it has a distinct syndicate lamp sprite... Doesn't that mean that you don't really have an excuse to explicitly examine it other than wanting to let yourself get brainwashed? Given that I usually only see experienced players play moth, I feel like seeing people actually fall for this would throw up a big metagame or self-antagging red flag for admins

**Comment by wesoda25** [comment]
This’ll just cause a ton of issues for admins and make the sybil moth metagang 10x more intolerable as now they’ll all be traitors together. Not just that, >hmm yes today i play a moth > oooh lantern lets buy that > hmm what does it do lets examine > “huhh duhhhhh im pepWonniiiiii” > heehee 

Its a fun idea athath but I think it’ll cause more problems than its worth

**Comment by ATH1909** [comment]
> This’ll just cause a ton of issues for admins and make the sybil moth metagang 10x more intolerable as now they’ll all be traitors together. Not just that, >hmm yes today i play a moth > oooh lantern lets buy that > hmm what does it do lets examine > “huhh duhhhhh im pepWonniiiiii” > heehee
> 
> Its a fun idea athath but I think it’ll cause more problems than its worth

Yeah, you make a good point. Maybe some day I'll come back to this and turn this into a component that can be applied to RPG loot items (since people tend to recklessly examine those a lot), sort of like the bane property. If the code works out right, it might even be able to be applied to mobs or something.

But yeah, this idea (a syndicate lamp that hypnotizes basically only moths, and can basically only hypnotize them if they don't know about this interaction or are voluntarily being hypnotized) is fundamentally flawed in its current iteration, so I'm going to close this PR now.

**Pull request closed without merging**
