### PR TITLE
Felinid Meowing and Purring Emotes pt.2

### PR DESCRIPTION
**Pull request by ValuedEmployee**
## About The Pull Request
Adds emotes for meowing and purring. Only players with felinid tongues can use these emotes and they mirror the new cat emotes exactly. If a player does not have a felinid tongue, then a text warning will tell the player they can't make the sound.

This revision from the original pr makes it possible to surgically implant the ability to meow and purr into someone.

Head Coder approval granted by @Mothblocks 

[2024-10-10 19-30-04.webm](https://github.com/user-attachments/assets/0d0c40e2-2299-4cce-ba96-6427ecae15b1)
## Why It's Good For The Game
There is currently a popular demand from felinid players to use these emote noises for silly cat sounds. Recently a PR allowed all mobs to meow, but it was patched to only cats from now on. Emulating the noises a cat makes as a felinid has given a lot of enjoyment to those playing from my own observations in-game. Cats are awesome!
:cl:
add: New purr and meow emotes for players with felinid tongues
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by carlarctg** [comment]
civil war

**Comment by DrAmazing343** [comment]
Thank you for helping make the People's wishes real.

**Comment by OHJ4Y** [comment]
tgstation has fallen...

**Comment by Hardly3D** [comment]
We're so back

**Comment by necromanceranne** [comment]
hell yeah

**Comment by Blacklist897** [comment]
DOOMSDAY HAVE ARRIVED

**Comment by Nicolai904** [comment]
So peak

**Comment by Loafin34** [comment]
i vote nay. too cute. now a hairball emote that i can get behind

**Comment by Sadboysuss** [comment]
You did what I couldn't do, congratulations.

**Comment by Yttriums** [comment]
guess we're cutting out tongues now

**Comment by Yobrocharlie** [comment]
IMG_0749

**Comment by 0ri-0ri** [comment]
kot

**Comment by ElGitificador** [comment]
delete felinids

**Comment by DrAmazing343** [comment]
> delete felinids

cope

**Comment by necromanceranne** [comment]
hell ye

**Comment by DATA-xPUNGED** [comment]
We are so fucking back

**Pull request merged**
