### PR TITLE
changes `spawn() throw_at` to `throw_at_fast set waitfor = 0`

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Set waitfor = 0 has massively less overhead then spawn() but still does basically the same thing.

It causes the first sleep in the stack from that point on to make the set waitfor = 0 proc return . then continue on as if it was spawn()'ed, but it doesn't have to copy over the local vars of the proc so a lot less overhead

http://pastebin.com/kx538RqS

### CODE REVIEW

**Comment by Giacom** [comment]
Is there any documentation on what "set waitfor" does?

**Comment by WJohn** [comment]
What a branch name.

**Comment by MrStonedOne** [comment]
It used to be documented, but when spawn() became a thing, it was removed from the documentation.

I did some testing to play with it.

It causes the first sleep in that proc or any called procs to make the set waitfor = 0 proc return . then continue on as if it was spawn()'ed.

http://web.archive.org/web/20061208103304/http://bwicki.byond.com/ByondBwicki.dmb?UndocumentedFeatures

**Comment by Giacom** [comment]
Oh I see.

**Comment by MrStonedOne** [comment]
set waitfor = 0 used to be the default, and if you wanted current behavior, you did set waitfor = 1.

when they changed this, shortly after spawn() became a thing, so that the default is set waitfor = 1, they decided to obsolete the feature.

Back in byond 225 http://web.archive.org/web/20060722121013/http://developer.byond.com/docs/notes/225.html

**Comment by RemieRichards** [comment]
we discussed this, but you never gave me a straight answer.
Do they still work simultaneously? if not it's a huge :-1:, regardless of performance, because moving items 1 at a time is HIDEOUS, I'd rather the feature be removed than have that mess.

**Comment by MrStonedOne** [comment]
yes, they still work simultaneously....

**Comment by RemieRichards** [comment]
Alright then, :+1:  :x: :100:

**Comment by MrStonedOne** [comment]
http://pastebin.com/U7323XFC

**Comment by Cheridan** [comment]
why the heck would byond depreciate a feature and add in a few one that's less optimized :anguished:

**Comment by MrStonedOne** [comment]
I updated this and added a bunch of things I saw using spawn() throw_at and replaced them with throw_at_fast

**Pull request merged**
