### PR TITLE
Removes Corporate Species

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Removes the Corporate species. this is a 3 file pr and one is the dme, that should tell you enough

## Why It's Good For The Game
###species change given the go ahead by nemvar and anturke

Unmaintained piece of shit admin toy, but not even admins use it since it's just so garbage

## Changelog
:cl:
del: Goodbye corporate species. I can't even pretend like you were good at all.
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
don't forget about their sprites in the human file, I think?

**Comment by tralezab** [comment]
I'll do that too, yeah

**Review by Cyberboss — DISMISSED** [review]

**Comment by ishitbyabullet** [comment]
arm, you can't just remove capitalism from the code smh

**Comment by Doosteroni** [comment]
Nooooo that's communism

**Comment by tralezab** [comment]
okay, sprites are gone too

**Pull request merged**
