### PR TITLE
Addition of antidotes and a slight redesign of reagent/toxin code

### PR DESCRIPTION
**Pull request by Djiq**
## About The Pull Request

In this PR i changed how you treat toxins (anything defined under reagents/toxin) . Antidotes is a new system! Every toxin has an antidote, when antidote is administered the toxin will stop doing anything and purge itself out quickly. I also massively nerfed most of chem purging chemicals across the board to make antidotes a prefered method of dealing with toxins. I also redsigned how reagent/toxin code works, to make it clear and easy to add new ones the same way it was prior , but also to add the necessary antidote code

## Why It's Good For The Game

I added it mainly because it adds another way of dealing with toxin. It raises the ceiling cap of MD's while also adding a simple way of dealing with weaker toxins on the fly. Now if you want to kill someone you will also have to account the fact if a single epi pen will cure them, making creating lethal syringes slightly harder. Also purging power of antidotes is based on the toxins toxpwr

Antidote 'levels'
1st - Iron and Epinephrine
2nd - Multiver
3rd - Atropine
4th - Syrniver
5th - Penthrite
6th - Anacea

## Changelog
:cl:
add: Added a new system of dealing with toxins: Antidotes!
balance: Major nerf to all (excluding anacea) chem purging chems
balance: Slight buff to Musivier
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
cant wait to murderbone with an oversight antidote that deals 30 damage per tick

**Comment by EdgeLordExe** [comment]
> cant wait to murderbone with an oversight antidote that deals 30 damage per tick

hm which one ?

**Comment by wesoda25** [comment]
Unless I misread this, did you just make anacea an antidote? The chem intended to be paired with poisons?

**Comment by EdgeLordExe** [comment]
> Unless I misread this, did you just make anacea an antidote? The chem intended to be paired with poisons?

yes, anacea actually doesnt deal that much damage and purges, so i decided that the most potent potions will also have a tricky and risky antidote

**Comment by wesoda25** [comment]
Also you might want to extend anacea to purge antidotes as well as medicines. To preserve what it  is intended for at least, whether or not its a good idea idk.

**Comment by Tlaltecuhtli** [comment]
why have tiers? just give ones that make sense for the damage like salbutimol for lexorin and rare chems(plant) for traitor only poisons

**Comment by EdgeLordExe** [comment]
> Also you might want to extend anacea to purge antidotes as well as medicines. To preserve what it is intended for at least, whether or not its a good idea idk.

i actually havent touched anacea's purging properties so it still purges chems quite quickly

**Comment by wesoda25** [comment]
> yes, anacea actually doesnt deal that much damage and purges, so i decided that the most potent potions will also have a tricky and risky antidote

But anacea is not only a toxin itself, its sole intention is to harm, not heal. It does not make sense to make it do the exact opposite of what is intended. I suggest haloperidol or pentetic instead.

**Comment by EdgeLordExe** [comment]
> why have tiers? just give ones that make sense for the damage like salbutimol for lexorin and rare chems(plant) for traitor only poisons

coz 

1. Making it that way is simpler to understand 
2. I wanted antidotes to be universal for many chems. there are only few snowflakes like UM

**Comment by EdgeLordExe** [comment]
> > yes, anacea actually doesnt deal that much damage and purges, so i decided that the most potent potions will also have a tricky and risky antidote
> 
> But anacea is not only a toxin itself, its sole intention is to harm, not heal. It does not make sense to make it do the exact opposite of what is intended. I suggest haloperidol or pentetic instead.

i thought about it for a very long time , but i think that having the most powerful antidote deal slight tox damage makes it more interesting gamplay wise. i agree tho, i might change penthrite to pentetic

**Comment by wesoda25** [comment]
No I don't think you understand, anacea isn't an antidote and that is the polar opposite of its intention. It explicit purges medicines and is meant to be added to death mixes and the like, to prevent a patient from getting healing. 

Heres the purge chems that I know of
Anacea: purges medicine
Haloperidol: purges drugs
Pentetic: Purges everything i think
Antihol: just alcohol

probably some new cobby chem stuff im forgetting

**Comment by EdgeLordExe** [comment]
> No I don't think you understand, anacea isn't an antidote and that is the polar opposite of its intention. It explicit purges medicines and is meant to be added to death mixes and the like, to prevent a patient from getting healing.
> 
> Heres the purge chems that I know of
> Anacea: purges medicine
> Haloperidol: purges drugs
> Pentetic: Purges everything i think
> Antihol: just alcohol
> 
> probably some new cobby chem stuff im forgetting

var/remove_amt = 5
	if(holder.has_reagent(/datum/reagent/medicine/calomel) || holder.has_reagent(/datum/reagent/medicine/pen_acid))
		remove_amt = 0.5

it slows down when pentetic is present

**Comment by EdgeLordExe** [comment]
> No I don't think you understand, anacea isn't an antidote and that is the polar opposite of its intention. It explicitly purges medicines and is meant to be added to death mixes and the like, to prevent a patient from getting healing.
> 
> Heres the purge chems that I know of
> Anacea: purges medicine
> Haloperidol: purges drugs
> Pentetic: Purges everything i think
> Antihol: just alcohol
> 
> probably some new cobby chem stuff im forgetting

if you really want i can replace anacea with crank or meth , but i dont think you want that do you ?

**Comment by EdgeLordExe** [comment]
> ## About The Pull Request
> In this PR i changed how you treat toxins (anything defined under reagents/toxin) . Antidotes is a new system! Every toxin has an antidote, when antidote is administered the toxin will stop doing anything and purge itself out quickly. I also massively nerfed most of chem purging chemicals across the board to make antidotes a prefered method of dealing with toxins. I also redsigned how reagent/toxin code works, to make it clear and easy to add new ones the same way it was prior , but also to add the necessary antidote code
> 
> ## Why It's Good For The Game
> I added it mainly because it adds another way of dealing with toxin. It raises the ceiling cap of MD's while also adding a simple way of dealing with weaker toxins on the fly. Now if you want to kill someone you will also have to account the fact if a single epi pen will cure them, making creating lethal syringes slightly harder. Also purging power of antidotes is based on the toxins toxpwr
> 
> Antidote 'levels'
> 1st - Iron and Epinephrine
> 2nd - Multiver
> 3rd - Atropine
> 4th - Syrniver
> 5th - Penthrite
> 6th - Anacea
> 
> ## Changelog
> 🆑
> add: Added a new system of dealing with toxins: Antidotes!
> balance: Major nerf to all (excluding anacea) chem purging chems
> balance: Slight buff to Musivier
> /🆑

**Comment by wesoda25** [comment]
Do you not get what I'm saying?

Anacea is not a beneficial chemical, not in the slightest. If you make it an antidote, it will completely negate its original purpose of _aiding_ toxins. If thats actually what you want its your design vision, whatever, but I don't think you understand what anacea is supposed to do. 

If you want a purge chemical in this highest tier, pentetic or possibly haloperidol are the only logical replacements, since they are designed as beneficial chemicals. Or, since you said you want the best tier to have drawbacks, why not create a new chem, that deals something like 1 brute damage for every 2 reagents of poison it purges. Just throwing out random numbers but you get the idea.

**Comment by AdmiralPancakes1** [comment]
so you've taken away the functionality of chem purgers and moved it to SEVEN arbitrary reagents that only work on their own tiny set of toxins

why is this needed?

**Comment by EdgeLordExe** [comment]
> so you've taken away the functionality of chem purgers and moved it to SEVEN arbitrary reagents that only work on their own tiny set of toxins
> 
> why is this needed?

i mainly added it to nerf toxins. previously chem purging chems are  antidotes or are better at healing tox damage. why nerf? coz now if you get hit by for example nitracid you inject epinephrine and you are good

**Comment by Tlaltecuhtli** [comment]
lol

**Comment by carlarctg** [comment]
calomel would work too

**Comment by AdmiralPancakes1** [comment]
> i mainly added it to nerf toxins. previously chem purging chems are antidotes or are better at healing tox damage. why nerf? coz now if you get hit by for example nitracid you inject epinephrine and you are good

you can do exactly this right now with a multiver pill

also, consider that not all harmful reagents are "toxin reagents", and by nerfing chem purgers you're making all of these stronger

**Comment by swindly** [comment]
Food for thought:
_Panacea_ ("all cure") but without the first letter is _anacea_ ("no cure").

**Comment by ExcessiveUseOfCobblestone** [comment]
It is very odd the "oh fuck I lost my heart" chem and the stealth poison is somehow higher-tiered than the dedicated "fuck you toxin" chems.

I'm not sure if I like this.

**Comment by EdgeLordExe** [comment]
> It is very odd the "oh fuck I lost my heart" chem and the stealth poison is somehow higher-tiered than the dedicated "fuck you toxin" chems.
> 
> I'm not sure if I like this.

it is all a subject to change

**Comment by EdgeLordExe** [comment]
> Food for thought:
> _Panacea_ ("all cure") but without the first letter is _anacea_ ("no cure").

actually yeah ill change those antidotes a lil bit

**Comment by AdamElTablawy** [comment]
this is a good idea with a terrible execution

you remove functionality from dedicated chem purgers in favor of adding an arbitrary tier reagent system that has no correlation to any of the chemicals themselves because it's 'easier to understand'

no, it's not 'easier to understand', and it's also going to fuck with new doctors who can't figure out that they're supposed to poison someone with anacea just to heal them, and you _also_ forget that deathmixes have multiple chems in them, which means you'll need to arbitrarily have a wide set of your bizzare 'antidotes' ready to treat someone who's been poisoned, which isn't viable given how quickly most serious toxins kill.

you could have gone with the option of leaving chem purgers as effective as they are and having antidotes neutralize the effect of the poison in you, and having the antidote correspond to the poison thematically, but instead what you did is basically just add 7 new chem purger chems that only work on specific toxins. that's not a feature, and it's not a 'nerf to toxins' as you said either. it's just idiotic.

**Comment by EdgeLordExe** [comment]
> this is a good idea with a terrible execution
> 
> you remove functionality from dedicated chem purgers in favor of adding an arbitrary tier reagent system that has no correlation to any of the chemicals themselves because it's 'easier to understand'
> 
> no, it's not 'easier to understand', and it's also going to fuck with new doctors who can't figure out that they're supposed to poison someone with anacea just to heal them, and you _also_ forget that deathmixes have multiple chems in them, which means you'll need to arbitrarily have a wide set of your bizzare 'antidotes' ready to treat someone who's been poisoned, which isn't viable given how quickly most serious toxins kill.
> 
> you could have gone with the option of leaving chem purgers as effective as they are and having antidotes neutralize the effect of the poison in you, and having the antidote correspond to the poison thematically, but instead what you did is basically just add 7 new chem purger chems that only work on specific toxins. that's not a feature, and it's not a 'nerf to toxins' as you said either. it's just idiotic.

actually i agree with ya this needs a little bit morr work. ill get to it today

**Comment by kriskog** [comment]
What worries me a bit about this is that you nerf the chem purgers, but dont touch the medicine overdoses. Some of those are just as bad as toxins, and this leaves you without a way to quickly get rid of them.

**Comment by ExcessiveUseOfCobblestone** [comment]
My only concern with this on a design pov is that our toxins aren't always toxic. They can do a wide variety of things that aren't bound within the toxin damage (IE Lexorin). 

So now, instead of say calomel and the appropriate anti-damage chem (convermol/salbu for lex), you now have to make a wide variety of chemicals to appease different toxins.

To me it seems like the difficulty to make a poison then put it in someone is far less difficult than it is to be able to address the poison, vs now where you just make 2 chems (1 of the antitoxs, 1 of the damage reduction meds you probably already made).

If toxins were more difficult to obtain I could easily be on board with this, but right now it's piss easy. WAY EASIER than having to make 5 different chems to address various toxins on top of damage reducing meds on top of antitox meds if it has a toxicity associated to it.

We're getting to the point where if we want to make chemistry more """interesting""" and give it more vertical depth (aka not just throwing more chems in), we need to address the machine that IS the department.

**Comment by EdgeLordExe** [comment]
I ill close this and once better chemistry mechanics are introduced ill reopen and try again

**Pull request closed without merging**
