### PR TITLE
Fixes things that are IS_SHARP not being able to slice wires

### PR DESCRIPTION
**Pull request by Haevacht**
Comes with the standard risks of slicing powered wires. If it can turn a goliath corpse to plates it can cut a wire. And probably zap you while doing it.

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
So using a non-conductive glass shard shocks you?

**Comment by RemieRichards** [comment]
if it's sharp, check that it has the conduct flag first, otherwise as said above, nonsensical objects will conduct electricity in 1 situation where they don't in 100s of others.

**Comment by SgtxRootbeer** [comment]
Actually, on second thought, let's have it shock you, for 2 reasons.
1 apparently throwing items at grills is enough to trigger an arc of electricity. We could have using non-conductive items generate an arc to the user and all nearby.
2, all of a sudden, assistants will be running around, breaking windows so they can have a tool which allows them to ransom power to the hop office, without needing gloves.

**Comment by jughu** [comment]
uses glass wouldnt shock you but still cut your hands :^)

**Comment by MimicFaux** [comment]
Agreed, keep shock in. We don't need to give assistants more of a reason to smash windows

**Comment by Mindustry** [comment]
Throwing glass shards at an electrified grille causes it to occasionally arc and shock you.

**Comment by WJohn** [comment]
So will sharp items only be able to cut wires on the ground? Or will they also be able to cut wires in doors?

**Comment by optimumtact** [comment]
cable on the ground and cable in doors are completely different things in the code WJohn

**Comment by Haevacht** [comment]
First, WJ, can't be used on door cables. You could probably shove a sword in there and cut random wires but that'd be a feature.

Secondly, everyone reading sound off on which thing you prefer: No conduct checking (glass shards will zap you) , simple conduct checking (glass shards will not zap you) or w_class && conduct checking (if it's small it'll still zap you because it's hard to cut cables with, but big things without conduct will cut fine)

**Comment by optimumtact** [comment]
rebalance or feature

**Pull request closed without merging**
