### PR TITLE
changes your cursor to an eye when you are holding shift to indicate you will examine

### PR DESCRIPTION
**Pull request by ghost**
:cl: qustinnus
add: changes your cursor when you are holding shift to indicate you will examine
/:cl:

simple UI change. icon sucks dick so I need to find a better one

### CODE REVIEW

**Review by Mothblocks — DISMISSED** [review]
icon is terrible but code is good

**Comment by Qustinnus** [comment]
i tried ok :(

**Comment by Ryll-Ryll** [comment]
👁️

**Comment by Qustinnus** [comment]
image
 which one is better? 🚀 for magnifying glass and 👀 for well, eye

**Comment by Jared-Fogle** [comment]
I think the outline on the eye looks a bit weird but it's better than the magnifying glass.

**Comment by nicbn** [comment]
holy fuck this icon will give me nightmares

**Comment by Qustinnus** [comment]
image
third option. use 👍 to vote for this i guess

**Comment by zxaber** [comment]
That's a better eye sprite than the one with a red glow.

**Comment by Qustinnus** [comment]
andd another one by Kryson

image

heart to vote for this one

**Comment by Jared-Fogle** [comment]
If it's not too much trouble, can you show what they look like over an SS13 scene?

**Comment by trerri** [comment]
the one from goon is still my favorite because it's in the exact same style as the cursor. goon has a lot of these cool icons

**Comment by Dorsisdwarf** [comment]
Does this trigger for AIs or other things that have non-examine things tied to Shift?

**Comment by Jared-Fogle** [comment]
Looks like the answer is yes. @Qustinnus Can you make it so this is only on non-sillys?

**Comment by Qustinnus** [comment]
want me to add a TRAIT_DUMB check?

**Comment by Jared-Fogle** [comment]
I'm not sure TRAIT_DUMB is what you want here. Not only am I not certain silicons have that trait to begin with, but there's also ways to get that that don't block you from examining things.

If your concern is that you feel an `issilicon` check is unclean, feel free to add a new trait for this behavior.

**Comment by Qustinnus** [comment]
`non-sillys?` `TRAIT_DUMB `

**Comment by Jared-Fogle** [comment]
silly-cones. silicons

**Comment by nemvar** [comment]
Why no Kryson sprite????? @Qustinnus

**Review by Mothblocks — DISMISSED** [review]

**Comment by Qustinnus** [comment]
rdy

**Review by Twaticus — APPROVED** [review]

**Comment by Tumesuo** [comment]
why
i hate you

**Comment by Jared-Fogle** [comment]
go on

**Pull request merged**
