### PR TITLE
Revert "Changes the shuttlebar back to pre-revert state"

### PR DESCRIPTION
**Pull request by coiax**
Reverts tgstation/tgstation#18948

### CODE REVIEW

**Comment by optimumtact** [comment]
doot

**Comment by Supermichael777** [comment]
Can mommy and daddy stop fighting?

I would suggest we pick a third design everyone is happy with but everyone knows what happens then: doot

**Comment by KorPhaeron** [comment]
wake me up

**Comment by lzimann** [comment]
why so much fighting over a shuttle

**Comment by Niknakflak** [comment]
There has no reason to exist as its only opened out of spite and saltyness, requesting it be closed.

**Comment by coiax** [comment]
You can say exactly the same thing about the PR that this reverts.

**Comment by Niknakflak** [comment]
This can be closed in favor of #18999 now

**Pull request closed without merging**
