### PR TITLE
Adds greyscale filling for bloodpack

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
fix: Bloodpacks will have their colors defined by the reagents
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
>fix

**Comment by Iamgoofball** [comment]
@improvedname yeah this fixes everey reagnet being red in the packs

**Comment by Iamgoofball** [comment]
No

**Comment by nicbn** [comment]
Looks like ShizCalev is building something on GBP...

image

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
