### PR TITLE
Buffs peacekeeper borgs

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR gives peacekeeper borgs the following additional items, with the following justifications for their additions:
Miniature welding tool: for repairing yourself after bodyblocking the shotgun pellets from an overzealous officer's unilateral execution attempt
Cyborg gauze: for pausing bleeding so that you can safely drag the victims of harmbatonning/reckless shotgunning to Medbay
A pepper spray sprayer with a reduced chemical capacity (only 20u): gives you a stun option in case you've been EMP'd since you last visited a recharging station (it's also quite in-theme for a riot-control cyborg)

In addition, this PR also makes the peacekeeper's flash burn out less easily and makes the peacekeeper's flash's AoE effect (the one where you use it in-hand instead of clicking on someone with it) affect everyone within 7 tiles instead of everyone within 3 tiles (like a normal flash).

This PR also gives each clown borg a peacekeeper flash (because they're basically peacekeeper borg reskins) and a miniature welding tool, although I could be persuaded to not give them these items if someone makes a persuasive enough argument.

Finally, this PR tweaks how the burnout_resistance variable works (it wasn't even set to anything other than 0 on any flashes, so this is a pretty minor change), modifies a bit of AoE flash code to make the bigger AoE effect of the peacekeeper borg's new flash work, and lowers the damage from lit emergency welding tools to 10 (from 15). Other kinds of welding tools are unaffected; this is just to keep peacekeeper borgs from using their new emergency welding tools to kill people faster instead of to heal themselves.

## Why It's Good For The Game

Quite frankly, peacekeeper borgs currently are a joke- intentionally so, if what I've been told is correct. This PR attempts to preserve the jankiness of the peacekeeper borg (two of the new tools (the flash+ and the pepper spray can) are based on underused sec mechanics) while enabling them to actually do their job competently. Seriously, who the fuck thought it was a good idea to not give a RIOT CONTROL/COMBAT-PREVENTION borg a way to heal themselves? I'm pretty sure an angry tider that will try to beat you to death for trying to keep them from killing a human is much more of a threat than random mobs on lavaland would be, and yet mining borgs get self-healing while peacekeeper borgs do not.

## Changelog
:cl:
add: Gives the peacekeeper borg four new items: An advanced flash (which replaces the peacekeeper borg's normal flash, being a superior version of it) with a lessened chance to burn out and a massively increased range for its AoE blinding effect, an emergency welding tool, gauze, and a pepper spray sprayer with a reduced chemical capacity (only 20u). Clown borgs each get an advanced flash and an emergency welding tool too, now.
balance: Reduces the force of lit emergency welding tools from 15 to 10. This change does not affect the other kinds of welding tools (including normal ones).
tweak: Makes some minor changes to how flash code works that shouldn't really be noticeable in gameplay.
/:cl:

### CODE REVIEW

**Comment by MacBlaze1** [comment]
As a bit of shameless advertising, and a warning my pepperspray rework would make the peackeeper borg much more effective #46342

**Comment by ATH1909** [comment]
> As a bit of shameless advertising, and a warning my pepperspray rework would make the peackeeper borg much more effective #46342

After looking at your PR again, I've decided to lower the chem capacity of peacekeeper borg pepper spray sprayers to a mere 20u, which should only be enough for 4 or so sprays.

**Comment by Dawson1917** [comment]
>Miniature welding too

huge powercreep.

>Cyborg gauze

powercreep and circumventing that borgs are only meant to be good for ONE SPECIFIC thing. don't encroach on mediborg. prevent harm, not treat it.

>pepper spray

have you ever been pepper sprayed? it might not do damage ingame but it's very human harmies

**Comment by zxaber** [comment]
Yeah, I'm not sure about the flash and the welding tool. I'd hate to see it used as reasoning to later on nerf borgs even more.

Gauze seems fine; Peacekeeper is supposed to keep the peace, as hinted by their items that help break up fights. Fights often result in bleeding, so this seems acceptable for a sort of first-responder role.

Dunno how powerful pepper spray is, or is gonna be, so I can't really comment on that.

**Comment by Geikkamir** [comment]
> Miniature welding tool
One of the big reasons that borgs are so fucking obnoxious is the fact that they suffer no slowdown from damage, so you can beat the everliving shit out of a borg only for it to yakety-sax away unhindered if you don't kill it outright. Engie borgs are even more obnoxious because after they do so, they can heal themselves without even needing help from anyone else.

If we're deciding that allowing the crew to have access to easy healing without needing help from anyone else is bad for the game, why in the world should _borgs_ be allowed to have it?

> A stun option that circumvents borg's intended weakness to EMP
> Fullscreen repeatable AoE blind AND it burns out LESS slowly
What are even you thinking

**Comment by ReplicantTerry** [comment]
> One of the big reasons that borgs are so fucking obnoxious is the fact that they suffer no slowdown from damage, so you can beat the everliving shit out of a borg only for it to yakety-sax away unhindered if you don't kill it outright

I play a lot of borg and I see this thrown about a lot, but I've never really found it to be the case in practice- borgs get chainflashed and they die. I do however think that hat the inter-borg co-operation that arises from only some modules being able to heal is great and I think it'd be a shame if that was lessened by borgs being less dependant on other borgs/organics, so for that reason I'd say it'd be better if the welding tool wasn't given to peacekeepers.

The pepper spray is a good idea. I think that if the pepper spray is present, then the flash doesn't need to be buffed. Crowd control as a borg isn't difficult, provided that no one has flash protection. The moment one person has gamer glasses on is when controlling a crowd becomes an issue. An AoE flash doesn't change that. The pepper spray however does allow borgs options in the event of someone wearing flash protection which is a big buff to peacekeepers, big enough that it makes them actually viable at doing their job instead of just a funny egg that shouts human harmies.

**Comment by Cyprex** [comment]
Cyborg gauze hardly encroaches on mediborgs, all it does is stop bleeding, this doesn't help you with the damage dealt at all. This isn't healing, merely stops bleeding temporarily.

**Comment by 81Denton** [comment]
These changes move peacekeeper borgs into validhunt territory. They're not meant to take people down secborg style, which is why their tools (flash aside) just impair or annoy others.
The welding tool is just plain powercreep, if peacekeeper borgs get blasted they can ask crew or engineeeing borgs for repairs.

**Comment by Krysonism** [comment]
I like the pepperspray and flash changes. The welding tool is probably too powerful sadly.

**Comment by CPTANT** [comment]
Honestly I think no borg should be able to repair itself.

**Comment by PKPenguin321** [comment]
The full ApE flash and the gauze are alright but everything else is bad. Self heals suck and pepper spray is in a nebulous place right now where it may well get buffed soon

**Comment by zombiegums** [comment]
I love eggborgs but this makes them too strong. I do think they could do with an expanded kit, but I'm not sure what would be thematically appropriate and fun without straying into validhunting territory.

**Comment by Ratvar** [comment]
I think thematically appropriate would be to nerf all other borgs instead.

**Comment by optimumtact** [comment]
you tried but you failed

**Pull request closed without merging**
