### PR TITLE
Adds some spawnable shuttle templates for admin memery

### PR DESCRIPTION
**Pull request by MMMiracles**
Adds some FTL-inspired shuttles for spawning in via template system.

s1
s2
s3

can't be feature-frozen IF I'M FASTER THAN LIGHT

### CODE REVIEW

**Comment by coiax** [comment]
Will need to put an entry in datums/shuttle.dm. Also make sure that it only contains a mobile docking port, and that the docking port is timid=1. None of these things are possible until #17436 is merged

**Comment by optimumtact** [comment]
What killed the dinosaurs?

THE ICE AGE

**Comment by MMMiracles** [comment]
These aren't exactly for the shuttle system, they're made for the template system as there's almost nothing pre-made for admin events.

also DAMMIT TANGERINE

**Comment by Jordie0608** [comment]
You might as well make them work with both if you want to spend the time.

**Comment by MMMiracles** [comment]
I mean the main issue here is that it kinda isn't possible without ditching the FLT-design entirely.

**Comment by Supermichael777** [comment]
yeah our docking ports are made for squares.

**Comment by coiax** [comment]
Not true, you can make these compatible with the shuttle system, they don't won't have the docking ports directly touching. 

Actually that gives me an idea for an energy gangway.

**Comment by MMMiracles** [comment]
I mean if you add a way to automatically create a pathway on docking so people aren't jumping past space to get in then sure.

**Comment by Jordie0608** [comment]
The shuttles will only be changed as a result of admins. They can just fix up any errors due to shuttle shape themselves, if they're feeling generous.

**Comment by Anonmare** [comment]
@Jordie0608 You're making a lot of assumptions about the generosity of admins.

**Comment by Cheridan** [comment]
these are pretty bad as far as shuttles go, they lack any of the consoles that the bridge usually has and are basically blank.

**Comment by coiax** [comment]
Well, without mobile docking ports, they aren't actually shuttles, just structures. So a console wouldn't do anything.

**Comment by MMMiracles** [comment]
they're meant as templates for admins to spawn in reeeeeee

**Comment by Bawhoppen** [comment]
these are so shit, 
ever heard of using original assets to actually make them interesting?

**Comment by MMMiracles** [comment]
I honest to god can't tell if you're shitposting or not but you are bawhoppen so

**Comment by Bawhoppen** [comment]
how is that shitposting in any way shape or form

**Comment by MMMiracles** [comment]
Truly based.

**Comment by KorPhaeron** [comment]
Freeze

**Comment by Thunder12345** [comment]
I thought maps weren't included in the freeze?

**Comment by KorPhaeron** [comment]
Well it got the freeze tag so

**Pull request merged**
