### PR TITLE
Introduces atmos tech cyborg variant of engineering cyborg while being functionally the same.

### PR DESCRIPTION
**Pull request by Blacknas**
## Why It's Good For The Game
Upon stumbling on a tracked variant of the engineering cyborg I decided to repurpose it as a atmospherics textured tracked cyborg. Adding this sprite will make it easier to distinguish those who are more experienced in atmospherics than engineering and vice versa. This will make it easier for new players to become engineering cyborgs without seeming like they must know both atmospherics and construction.

## Changelog
:cl:Balky Goat
imageadd: Added an alternate engineering cyborg sprite with an atmospherics design pattern
/:cl:

### CODE REVIEW

**Comment by JJRcop** [comment]
Please update your PR title, it makes no mention of a cyborg

**Comment by CyoTheProtogen** [comment]
Very cool yes yes

**Review by Twaticus — APPROVED** [review]

**Comment by Fikou** [comment]
the borg reskin list is getting quite bloated, ideally it should be refactored to be generic instead of a hardcoded proc on each borg

**Comment by InsaneRed** [comment]
while this is a cool idea i dont really know if its necessarry to add another sprite just for atmos borgs? most definetly if you know atmos to a point where you can dedicate being an entire atmos borg for a round you will most definetly have the basics of the sm,construction,and atmos so i feel like just give engi borgs a holofan and call it a day

**Comment by Blacknas** [comment]
> while this is a cool idea i dont really know if its necessarry to add another sprite just for atmos borgs? most definetly if you know atmos to a point where you can dedicate being an entire atmos borg for a round you will most definetly have the basics of the sm,construction,and atmos so i feel like just give engi borgs a holofan and call it a day

While it is true that knowing how to do atmospherics requires knowledge in engineering, the opposite is not always the case, especially for new players. This sprite helps new players who select engineering to be less burdened with the idea that all engineering cyborgs must also know how to deal with atmospherics.

The opposite is also true: Players who select atmospherics show that they will probably know both how to deal with engineering issues and how to deal with atmospheric issues since dealing with atmospherics also requires at least basic engineering knowledge, as you mentioned before.

**Comment by dragomagol** [comment]
In fairness we already have a bunch of reskinned borgs in code that aren't used anywhere anyway. This is very cute, thumbs up

**Comment by Jhyrachy** [comment]
> while this is a cool idea i dont really know if its necessarry to add another sprite just for atmos borgs? most definetly if you know atmos to a point where you can dedicate being an entire atmos borg for a round you will most definetly have the basics of the sm,construction,and atmos so i feel like just give engi borgs a holofan and call it a day

yes please, give borg holofan so it can do funny stuff

**Comment by Mothblocks** [comment]
image

Since your sprite is just a recolor, this can theoretically be accomplished without increasing the size of the RSC with the new [GAGS system](https://github.com/tgstation/tgstation/blob/master/code/datums/greyscale/README.md), though it'll take some good knowledge of code.

**Pull request closed without merging**
