### PR TITLE
Adds hand cannon for nuke op leader

### PR DESCRIPTION
**Pull request by Thunder12345**
Adds hand cannon revolver for nuke team leader:
-Five round cylinder
-115 brute per shot
-2 second delay between shots
-Screen shake on firing
-Is heavy weapon, extra recoil and chance of dropping on one handed
firing
-No way to get more ammo
-Brand new gunshot sound just for this, much more menacing than regular
gunshots

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Give it a 'safety' you have to toggle off in the attackby or something. When you're blasting out 115 brute per shot and you dont get to reload, it should be easier to avoid friendlyfire.

**Comment by WJohn** [comment]
Should probably require two hands, also.

**Comment by Thunder12345** [comment]
If someone has a better sprite, I'll do it. I just made the mateba bigger.

**Comment by vista-** [comment]
>115 brute per shot

At least give that fukken captain/clown a chance.

**Comment by RemieRichards** [comment]
Full health: 200
Crit begins: 100

Full health + this gun = 15 damage deep into crit.
What the sweet jesus.

**Comment by dannno** [comment]
i'm wondering if you might actually be retarded thunder

**Comment by Thunder12345** [comment]
Clown doesn't have a chance, captain won't be critted in the first shot. There's only ever five bullets too, and a bulletproof vest reduces the damage to about 20 brute. Not like you should already have given some guys bulletproof armour or anything already. It's all damage on one limb too, unlike burst fire, do you can run up to a guy with one bruise pack and heal him instantly. Not to mention there's a 2 second fire delay, so even if you down one guy you have to run or risk return fire downing you.

**Comment by Lumipharon** [comment]
or shoot them in the chest and one hit crit.
As captain I never wear armor, but even that aside, yeah, naw.

**Comment by Thunder12345** [comment]
It one hit cries wherever you shoot them, in fact chest is where you want to be shot, since the bulletproof vest goes there

**Comment by PKPenguin321** [comment]
lol merge it
this is gonna get "i ded pls nerf"'d at least three times within the day it's released and it will be hilarious

**Comment by Thunder12345** [comment]
Yeah, if you're gonna go down with this, throw it to another op, or mag dump it into your attackers so they can't use it against you. The biggest risk for the ops in having such a deadly gun is what happens when the crew get their hands on it.

**Comment by dannno** [comment]
this is so stupid thunder what the fuck

**Comment by vista-** [comment]
Being an old-school gun and not containing a syndie firing pin, allowing the crew to get their hands on it (and use it) seems like a good downside for an OP gun like this. Damage still needs lowering, though.

**Comment by SconesC** [comment]
this is hilarious

**Comment by Iamgoofball** [comment]
I'd say no lower than 80 damage. Since that flat 80 would slow you down landing a second shot wouldn't be hard, but they get a small chance to make it out alive.

**Comment by Jordie0608** [comment]
Changelog

**Comment by spheretech** [comment]
Why would you give nuke ops an instakill weapon? They have plenty of firepower already..

**Comment by Dorsisdwarf** [comment]
I really like this. It's the ultimate anti-rambo 'I CAN KILL A NUKE OPS TEAM BAI MAISEEEELF'

Don't forget that this won't 1-shot-crit anyone but assistants/clowns/botanists with stunprods and validkills in their brains.

**Comment by Atskadan** [comment]
im pretty sure the ultimate anti-rambo gun is every gun nuke ops get because the only good ones either stun or kill you faster than you can do anything

**Comment by Cheridan** [comment]
Having something with such massive damage is terrible based on how often nuke ops shoot each other by accident. 
Gameplay-wise this is just comparable to a oldstyle parapen... BUT RANGED. AND WITH FIVE TIMES AS MANY USES.

This also completely throws off the design of nuke-op scaling. The intent of it is for it to scale both ways -- low pop rounds get fewer TC so they're less armed. By giving them a facerollingly powerful gun for free you're throwing it right out the window.

**Comment by Thunder12345** [comment]
Removed it from nuke ops for now. Now sure whether to leave it as adminspawn or put it on the ops uplink.

**Comment by killerfgs** [comment]
Mebbe buyable for like 35 TC with damage lowered to 70 with no syndie pin

**Comment by Cheridan** [comment]
A slightly-better-than-default-pistol firearm for Nuke Op leaders is fine, a powerful sidearm with an appropriate TC cost is also fine. :) Just keep the rest of the game in mind when making additions.

**Comment by Dorsisdwarf** [comment]
killerfgs, are you fucking serious?

That's ridiculously expensive for what is essentially a revolver you can't unload. 35 TC is like, 'assault-rifle-with-a-grenade-launcher' levels of expensive.

**Comment by WJohn** [comment]
@Dorsisdwarf the assault rifle is actually just 18 TC for its 30 shot magazine (each round doing 35 damage) and comes loaded with 1 grenade.

**Comment by Dorsisdwarf** [comment]
So yeah. This gun being '35 TC with damage lowered to 70 with no syndie pin' would make it objectively the absolute worst thing you could possibly buy from the uplink in terms of cost-effectiveness. A revolver that fires every 2 seconds has 2 fewer shots and is unreloadble. Mmm, sounds useful.

**Comment by vista-** [comment]
I'm in for something unique for the nuke op leader other than the choice of
team name. I think the best solution would be to have a gun that is able to
deal potentially critting damage to unarmored guys but be ineffective
against those with armors (e.g. sec, captain) - an anti-shitler/powergamer
weapon.

**Comment by Dorsisdwarf** [comment]
So, uh, exactly like this weapon?

115 won't crit anyone with even an armor vest, since they have like 20 bullet. It'd do around 85 or so to the captain probbably, and even less to a guy in the bulletproof vest. And it can't get around that by shooting them in the limbs because limbs can only take 75.

**Comment by Thunder12345** [comment]
23 damage against bulletproof in testing. Not like you shouldn't be wearing that shit in nuke anyway ever since they lost their last energy weapons

**Comment by Lumipharon** [comment]
Amazing as it is, people don't always have a chance to put on bulletproof armor, especially considering 95% of ops bomb tcomms and/or armory off the start.

I still really don't agree with this weapon, it's just a dumb ggnore weapon against most of the crew. If you want things that are 'effective against crew but not sec', that's what shit like vicerator nades/flashbangs are for.

Or you can get a chem sprayer and wreck everyone down a corridor, although there's a PR that is nerfing that up.

**Comment by Dorsisdwarf** [comment]
Yeah, but a normal armor vest stops you from being critted. It also has the slowest fire rate of any gun in the game, slower than a laser cannon or an L6 SAW by far. 1 shot every 2 seconds.

**Comment by Thunder12345** [comment]
Plus the recoil makes you effectively defenceless for another half second or so while your screen shakes like there's an earthquake. You also can't shoot with a shield or anything, otherwise the recoil's even worse and there's a chance of dropping to gun.

**Comment by Dorsisdwarf** [comment]
@Cheridan merge conflicts, needs a tag

**Comment by WJohn** [comment]
http://i.imgur.com/kXLCb6j.png

http://www.mediafire.com/download/ath1s9e992eg5lm/Sprites_Request_11.0.3p.rar

I made a new sprite for the handcannon, to make it more beastly.

**Comment by Razharas** [comment]
Any progress?
@Thunder12345

**Comment by pudl** [comment]
can this be closed yet

**Comment by SconesC** [comment]
no but i liked this idea

**Pull request closed without merging**
