### PR TITLE
Drone dispenser's cooldown now in a var

### LINKED ISSUE #10071: Drone dispenser cooldown cannot be modified
The dispenser cooldown is hardcoded rather than a var. This inconsistent with almost every other thing that has a cooldown, and makes it so the cooldown time between drones is impossible to modify.

### PR DESCRIPTION
**Pull request by ghost**
Implements feature request/consistency fix of #10071 as how #10153 was going to.

@ike709 like this? Fixes #10071

### CODE REVIEW

**Comment by Shadowlight213** [comment]
:+1:

**Comment by ike709** [comment]
"Fixes #10071" in the OP or else it won't autoclose.

**Comment by AlexCrimson** [comment]
...theres a drone dispenser?

**Comment by CosmicScientist** [comment]
@AlexCrimson yes, dunno where though.

**Comment by Shadowlight213** [comment]
@CosmicScientist It's admin spawn only currently, mainly because no one has added it to any of the maps yet.

**Comment by ike709** [comment]
Yes, like that.

**Pull request merged**
