### PR TITLE
Removes the damage deflection from reinforced windows

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR removes the damage deflection that actioninja added to reinforced windows in his recent PR (https://github.com/tgstation/tgstation/pull/45609). It does NOT remove/revert the damage deflection that plasmaglass windows were given, the extra armor given to reinforced windows, or the additional step that was added to the deconstruction process of reinforced windows.

## Why It's Good For The Game

Reinforced windows (now) already effectively have 750 health against non-armor piercing melee attacks, which I think is enough to discourage players from causally breaking down reinforced windows.

The damage deflection is completely unnecessary, seeing as how even an armor piercing-less force 10 weapon (just below the damage deflection threshold) would require a whopping 75 whacks to break down a reinforced window if the damage deflection wasn't there anyway.

The presence of this damage deflection on reinforced windows unfortunately can create a few rare/accidental GBJ (gay baby jail, a term for an inescapable (without outside help, which you may or may not be able to contact) prison cell) situations ("'oh no, the power went out in this room and I have no crowbar, guess I'll just sit here and wail over comms (if they aren't down as well) until I'm rescued"). The force threshold for this damage deflection is so low (even a red toolbox bypasses it) that I don't think that it will stop (m)any tiding incidents, and to be honest, it doesn't look like it will ever really come up EXCEPT for in GBJ situations.

This damage deflection on reinforced windows has an almost entirely negative impact on this game's quality and does very little to stop the "problem" that it was added to solve (unlike the extra deconstruction step and extra armor that were added in the same PR that added damage deflection to reinforced windows), which is why I believe that it should be removed.

## Changelog
:cl: ATHATH
del: Reinforced windows no longer have damage deflection (they still have their increased armor and extra deconstruction step, though). Plasmaglass windows still have damage deflection, however.
/:cl:

### CODE REVIEW

**Comment by KetasDotepasto** [comment]
Taking out the damage deflection would make it possible to break out of perma again.

**Comment by Dawson1917** [comment]
> 
> 
> Taking out the damage deflection would make it possible to break out of perma again.

You already can, by smashing machines to make a spear

**Comment by PKPenguin321** [comment]
I like the technical breakdown of what a GBJ is

**Comment by Tlaltecuhtli** [comment]
windows are stronger than walls

**Comment by MCterra10** [comment]
Not really, last I checked you couldn't break walls with a toolbox

**Comment by Tlaltecuhtli** [comment]
hit a window 750 times vs weld and wrench

**Comment by Ratvar** [comment]
screw and crowbar window out vs get welding sunglasses or you are blind

**Comment by KetasDotepasto** [comment]
@Ratvar That changed, the current deconstruction is welder, screwdriver, crowbar, wirecutter, wrench.

**Comment by Ratvar** [comment]
Stop, that balance change added *welder* to list of window tools?

**Comment by Dawson1917** [comment]
> 
> 
> Stop, that balance change added _welder_ to list of window tools?

image

from the pr^

**Comment by MMMiracles** [comment]
I appreciate that simpleflips is relevant enough now for GBJ to be a more common term used. 

Also what the fuck are those deconstruction steps? Walls are easier to break apart now in comparison??

**Comment by CPTANT** [comment]
This is not a solution, the time required to bash windows down is prohibitively long even without the deflection.

With a toolbox it already takes TWO MINUTES of non stop bashing to crack a window.

**Comment by ATH1909** [comment]
> This is not a solution, the time required to bash windows down is prohibitively long even without the deflection.
> 
> With a toolbox it already takes TWO MINUTES of non stop bashing to crack a window.

Aye, that was the intention of actioninja's PR. If that's the direction that the maintainers want to go in, who am I to stop them? I'm merely trying to refine a PR slightly, not undo it completely.

**Comment by ExcessiveUseOfCobblestone** [comment]
those decon steps lmao

**Comment by optimumtact** [comment]
Im happy with how windows are right now

**Comment by wesoda25** [comment]
bro have you experienced the change yet? I'm all for windows not being a joke to break through, but they are basically just as strong as walls in their current state.

**Comment by ATH1909** [comment]
@optimumtact I literally just encountered an actual GBJ situation with reinforced windows on Bagil: https://cdn.discordapp.com/attachments/326826573951008769/610687754082189322/actual_gbj_situation.PNG

How can you be "happy" with this?

**Comment by optimumtact** [comment]
because it's pretty short work to remap the escape to have non reinforced windows

**Comment by ATH1909** [comment]
> because it's pretty short work to remap the escape to have non reinforced windows

*arrivals

I just... don't see how you see the damage deflection as adding to the intended reinforced window experience. How exactly is it supposed to help achieve the goal of the reinforced window buff?

**Pull request closed without merging**
