### PR TITLE
Fix dwarfism and gigantism to affect tables, lockers, and disposals

### LINKED ISSUE #67643: Dwarfism Inconsistencies
## Reproduction: 
1-Get mutation Dwarfism
2-Notice you can run "under" tables but your sprite goes over them
3-run "under" a glass table but it shatters

(Oranges said this is a bug...)

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
Fixes #67643

Gaining the dwarf or giant mutation will now change the `mob_size` category appropriately.  This affects a few things:

- Dwarfs no longer break glass tables when traveling across them
- Giants don't fit inside lockers or crates
- Giants don't fit inside disposal bins

## Why It's Good For The Game
Less bugs and better consistency.

## Changelog
:cl:
fix: Fix dwarfism and gigantism to affect tables, lockers, and disposals
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
It would be funnier if someone else can stuff you in a container and it makes a squish noise.

**Comment by Donglesplonge** [comment]
a consistency update is great and all but doesn't this just make dwarfisms one downside nonexistent and makes gigantism even worse by comparison?

**Comment by ATH1909** [comment]
> a consistency update is great and all but doesn't this just make dwarfisms one downside nonexistent and makes gigantism even worse by comparison?

big big chungus big chungus big chungus

**Comment by necromanceranne** [comment]
You've significantly changed the functionality of these mutations. Unless you can demonstrate that this was always intended to work like this, I don't see how this isn't a balance change. A maint can slap me upside the head if they think I'm overstepping here.

Also, Tim, please tell me you tested this.

**Comment by timothymtorres** [comment]
chrome_vynVUL8g7A

**Comment by necromanceranne** [comment]
And can you run under the tables with this change?

**Comment by timothymtorres** [comment]
Dwarfism always allowed people to run under tables but for glass tables it would trigger the break glass proc.  I'm not marking this as balance since this was a bugfix specifically wanted by a headcoder.

**Comment by moocowswag** [comment]
The gigantism might actually have balance implications in niche scenarios, like does it prevent using bci chamber?

**Review by MrMelbert — COMMENTED** [review]
This doesn't fix all of https://github.com/tgstation/tgstation/issues/67643 , part of the issue is that dwarfs are supposed to go underneath tables and not overtop them

And I'd really like to not get rid of glass tables breaking dwarf legs until that aspect is fixed

**Comment by necromanceranne** [comment]
CRUSHER TIME

So, this PR would make anyone with gigantism susceptible to crushers.

**Pull request closed without merging**
