### PR TITLE
Janitors have basic access to Cargo, Medical, Science, Engineering

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
balance: Janitors now have basic access to the Cargo, Medical, Science and
Engineering departments. Because broken lights and spills happen everywhere!
/:cl:

I feel that janitors should have more access than just Assistants + Janitor room.
After all, a clean station is an efficient station.

### CODE REVIEW

**Comment by XDTM** [comment]
Crazy idea: protect janitor role from being antag, like sec, to lean onto the trope of janitors being uncaring bystanders in the chaos of the station. Antags could still disguise themselves as a janitor to abuse that trust.

**Comment by coiax** [comment]
@XDTM Definitely not in scope for the PR. But it sounds memelicious. You should PR it.

**Comment by Steelpoint** [comment]
If not a single person in a department cares to ask/let the Janitor in to clean up a mess or fix broken lights, let it be on their heads.

**Comment by ExcessiveUseOfCobblestone** [comment]
The respective heads can give him permanent access via their own console, which I'd rather they opt into rather than having to force the ID off the janitor to get the access revoked.

**Comment by Garen7** [comment]
Mfw janitors get more access than sec & command, speaking of this is a balance PR not a feature

**Comment by MACIEKBAKI** [comment]
i love this crazy idea makes my greytide better as jani

**Comment by Adanps** [comment]
Makes sense to me, janitors usually have access to all but the most secure of areas, since otherwise they need to constantly bother people to open doors so they can do their job. Making the janitor a high priority target for antags is also funny.

**Comment by Arianya** [comment]
Buffs to my favourite job are 👍

**Comment by yoyobatty** [comment]
It's not like the janitor isn't an upgraded assistant or anything. Lets look at examples of stuns, anti-slips and upgraded storage; soap, bear traps, mousetraps, galoshes, trash bag (aka literal second backpack).

**Comment by Potato-Masher** [comment]
>Sec Mcgurst says, "Janitor! Let us into science, we need to catch a criminal that is wreaking havoc in there!"
>Mops-the-Floor says, "I have obtained more power than the average sssecurity officer.

Hilarious. Station security doesn't have proper shift-start access to most departments.
... but sure, the Janitor can come in. He's a bro.

**Comment by subject217** [comment]
people have all these fun ideas about "how do we make janitor more fun?" but the reality is that the janitor is just a greytider with free slips and every janitor buff just makes him more of a greytider

**Comment by lolman360** [comment]
departmental janitors when

janitor squad

**Review by Jalleo — COMMENTED** [review]
Instead I suggest cargo, mining excluding eva, medical, service areas and only to engineering lobby if there is such a suitable access.
Why? Engineering is technically almost instant access to the engine. 
Science access to just walk in might be okay. Honestly it could be better to add in a service door at mechbay when which can be bolted on science side.
You could do a joke of giving them meeting room access if possible. Just for that one time there is a meeting and the janitor walks in to clean and listen in.

**Comment by ExcessiveUseOfCobblestone** [comment]
Having access != being welcomed, and I think having people opt in to giving the janitor access or having someone escort them averts issues from that distinction.

If you want to encourage a clean station and make janitor more "fun", put the ball in people's courts by giving consequence to dirty areas and/or rewards to clean ones. The miasma from other sources is a good start to this imo.

**Pull request closed without merging**
