### PR TITLE
Adds Tajaran to the game.

### PR DESCRIPTION
**Pull request by Iamgoofball**
gklfnpi

Adds a new race to the game, Tajaran.
They cannot be authority roles.
They roll their Rs when they speak.

### CODE REVIEW

**Comment by daman997** [comment]
REMOVE YOURSELF

**Comment by Zilenan91** [comment]
is this memes

**Comment by Iamgoofball** [comment]
It's just cosmetic. If you don't like it, don't use it.

**Comment by Anonus** [comment]
tbh better than catears

**Comment by WJohn** [comment]
This is the second time you do this. Let's see how quickly this gets shut down!

**Comment by PKPenguin321** [comment]
why

**Comment by Iamgoofball** [comment]
I don't see any controversy here.

**Comment by Aranclanos** [comment]
?

**Comment by Iamgoofball** [comment]
Re-open this pull request, please.

**Comment by duncathan** [comment]
I will reopen this once and once only

**Comment by duncathan** [comment]
Lol

**Comment by Zilenan91** [comment]
Since I genuinely can't tell if goof is memeing, why not let him see it through?

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by ZomgPonies** [comment]
*grabs popcorn*

**Comment by duncathan** [comment]
Goof is memeing, but he's memeing to make a point

**Comment by Steelpoint** [comment]
Its Catpeople or Lizardmen, you can't have both.

**Comment by Techhead0** [comment]
>Its Catpeople or Lizardmen, you can't have both.
You've obviously missed the joys of making the cats and lizards fight for the humans' amusement.

**Comment by Steelpoint** [comment]
What are we fucking Elder Scrolls now?

Lizardmen were tolerable due to them being in the game forever as admin only and at least they look somewhat alien like, but damn Cat people are even more generic.

If you want more Aliens, make actual bloody Aliens instead of ripping off some poor animals head and sticking it on the body of a grey looking Human body.

**Comment by demonfiren** [comment]
Actually, let's do this. I need a race that even the daftest human recognises as inferior to lizardpeople.

**Comment by Firecage** [comment]
Steelpoint. The thing is, due to current understanding, there might actually be aliens who resemble some of Earth's animals, mostly due to the fact that we have a planetary evolution sample of...one.

**Comment by Firecage** [comment]
@Aranclanos Also, why not just leave the PR open? If it does get merged, it doesn't mean it will be enabled ingame. If anything, it will remain disabled, but admins would be able to funmin with it like they did with Lizardmen at a time.

**Comment by Steelpoint** [comment]
Except a humanoid cat is not very original, creative or is necessarily going to be a positive impact.

Lizards are just obnoxious and bring these massive arguments and flame wars over RP or not to RP, not to mention those shitty memes about ERPing Lizards and other bad gimmicks that it brings, what will happen if we introduce a even more base, uninspired, boring, stereotypical alien race that is not even a unique one?

I'm not sold that the benefits of even having Lizards as a playable race outweigh the negatives, but I accept it due to many people wanting them (seemingly) but also that they are the only boring Alien race we have on by default.

Fly people are more unique than Cat people in my opinion, at least they are under-represent and horrid looking to not appear like a Human just glued long ears on them and went for a swim in grey paint.

**Comment by Xhuis** [comment]
Goofball has finally lost it ,everyone.

**Comment by Aloraydrel** [comment]
Can't wait to have my special snowflake "Tajaran"(tm) to play with :^)

**Comment by Nienhaus** [comment]
:+1:

**Comment by Miauw62** [comment]
please re-maintainer me so i can re-open this and then close it again.

**Comment by duncathan** [comment]
Got your back miauw

**Comment by Miauw62** [comment]
thx bby

**Comment by demonfiren** [comment]
Just make it happen, for memes' sake.

**Pull request closed without merging**
