### PR TITLE
The blood loss change everyone's been raving about

### PR DESCRIPTION
**Pull request by Robustin**
Blood loss now scales linearly on a body part once you take 20 brute damage for that part.

Oxygen damage from blood loss now starts at 85% instead of 90%. 

**This brings some much needed sanity to blood loss. Where getting shot in the face/chest/leg would currently mean ZERO blood loss, but 3 shots to the chest would mean you're taking blood loss damage (pale/dizzy/oxyloss/etc.) after 30 seconds.** 

You'll see a little more light bleeding with this change but light bleeding is just that, LIGHT, you can safely ignore it for many minutes before it begins affecting you. To Kor: Its still 2 Goliath hits to the same body part before Miners start bleeding.

### CODE REVIEW

**Comment by obscolene** [comment]
the blood loss change nobody asked for TM

**Comment by Robustin** [comment]
Really now? 

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=10760

**Comment by BeeSting12** [comment]
this is a good change

**Comment by Armhulen** [comment]
the comment nobody asked for TM

**Comment by PKPenguin321** [comment]
Scaling is fine, but 20 damage from 30 is godawful

**Comment by XDTM** [comment]
the bleed at 20 is less than a quarter of the previous base bleeding speed, which was low of its own

**Comment by Robustin** [comment]
Yea PKP, blood loss at 20 is practically cosmetic and it seems like a sensible amount of damage where people would start bleeding (stechkin bullet, fire axe, etc.).

**Comment by PKPenguin321** [comment]
Hmm
Well if that's true and it's a one number change then whatever let's try it

**Comment by Shapsy** [comment]
>Spoiler Alert: The title is "BLOODLOSS FUCKING SUCKS ASS"

And everyone called him a retard

**Comment by Robustin** [comment]
Because his bitching was aimed at the wrong issues. Instead of whining about being dependent on medbay for blood, the real underlying issue was how losing a fistfight with an assistant would have you losing blood like 1) a leaky faucet or 2) a bad guy in Kill Bill depending on which arbitrary numbers were reached by RNG limb targeting. 

Now it should do a much better job of matching player expectations.

**Comment by Qbopper** [comment]
I went into the PR expecting something retarded but was pleasantly surprised, seems reasonable

Dunno how it'll work in execution but it certainly won't hurt to try

**Comment by KorPhaeron** [comment]
PRs that violated the freeze have to wait a week longer to be PRd or else people will keep opening their feature PRs during freezes

I'll merge this PR in a week though its a great idea. Would not be fair if I left this open after nuking all the others just because I liked it though

**Comment by Bawhoppen** [comment]
did this even violate the freeze

**Comment by KorPhaeron** [comment]
Yes

**Comment by Robustin** [comment]
Kor you fucking shit I talked about it in Coderbus for like half an hour and didn't get any objections, a LeoZ "I'll leave it open" comment was all I had to go off of. I figured it was a refactor and would work just fine. I even left the blood level change from 90 to 85% out of the previous one to avoid balance implications.

Sheesh.

**Comment by ExcessiveUseOfCobblestone** [comment]
but the freeze is over hence why there's several balance prs?

**Comment by KorPhaeron** [comment]
Oh right Leo baited you into opening it because ???

I guess I cant hold that against you

**Comment by Bawhoppen** [comment]
you just wanted an excuse to reopen it

**Comment by QualityVan** [comment]
I still don't think oxygen loss needs to have its breakpoints changes. That only changes what happens between 85 and 90% blood, which is basically nothing anyway.

**Comment by Robustin** [comment]
I made this PR for the purpose of making blood loss feel more in line with player expectations. Part of that was "why is someone pale and taking oxygen damage when they're only missing 10% of their blood".

I agree it's not a big deal, but its there to reduce pressure on players to immediately heal every cut and helps reinforce that when you do actually hit the pale/whoozy breakpoint that it's something you need to pay attention to (though 80% might be a better number for that, I didn't want to make it too drastic).

**Pull request merged**
