### PR TITLE
Adds Protagonists!

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Revival of #59898, but with some changed flavor to appease loremasters. Also, there's a new protagonist to join.

Protagonists are selected as neutral station traits. Antagonists will have extra weight towards assassinating them, making them a VIP-esque role.

### Legendary Craftsman

A legendary craftsman known for his masterwork-ful craft has arrived at the station, looking for INSPIRATION! ...And materials. Nothing's for free, you know? In return, they promise to create some art for your station.

* Starts with a suit of techy armor that is designed to look like knight armor.
* Can craft things that give special bonuses e.g. beauty, maybe fantasy modifiers, just general items that spice up the round
* Loses mood when he hasn't crafted cool items for a while
* Dies slowly from low sanity
* Has to create the ultimate masterwork item (gets those dwarf fortress stars around it for laughs)
* Escape alive

### Prince

Being from the same kingdom, but a member of high royalty, the pish posh prince holds their heirlooms from the past close. Maybe too close, because the dude's a bit unhinged.

* They come equipped with many heirlooms. Their heirlooms are named after ages from the past.
* They fear the supernatural, may the gods not smite them.
* They cannot use guns, they are magical weapons beyond their comprehension
* They cannot wear badbacks. Their backs are frail from the luxuries of their life.
* They look great, expect them to really make any room look good.
* They speak in an ancient accent, only god knows what half of the words they say are.

### Nanotrasen Superweapon

* They come equipped with very little, just some scrubs.
* They are very frail, having much less health and a chronic cough.
* They suffer from a bad backs.
* They have a special mutation, which activates every 20 minutes and makes them metamorphose. Metamorphosis grants some permanent bad mutations but generally makes them stronger. The set of mutations is themed, and will visually transform them!
* They have additional objectives to fully metamorphose. This will leave them... well, not AS terrible as they start, but they will be retaining their very low health pool.

## Why It's Good For The Game

Something like this can put a twist on the normal cloak and dagger gameplay of SS13 by revealing one crucial detail: Who the potential target might be. This gives security an active idea of who to protect but also can open up interesting challenges for people who have played a lot of antagonist roles before.

## Changelog
:cl:
add: Added protagonists, the first two being the prince and the nanotrasen superweapon
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Lexia Black is NOT a protagonist

**Comment by IndieanaJones** [comment]
Are you sure Superweapon is an apt term for what you've made there?

**Comment by moocowswag** [comment]
Sounds more like a bio weapon thats meant to be nanotrasen`s attempt at making their own variant of a changeling except where changeling`s have almost full control of their own anatomy, this creature is made to evolve and adapt passively, regardless of the host`s consent, along with reduced vitality to support this.

Its also fitting for nanotrasen to not want to give their experiments full control of themselves even if they could.

My main concern is, if their health is capped at 50, does that mean batons will oneshot them into stam crit?

**Comment by Valorium-RB** [comment]
Are you looking for additional concepts for the Protagonist role? Beyond these two?

**Comment by tralezab** [comment]
hit me up on discord armhulenn#9821

**Comment by PKPenguin321** [comment]
the prince is a lore disaster and would be better themed as some high ranking centcomm officer

**Comment by tralezab** [comment]
I've already conceded that after discussing on discord, I'm going to change them into something but I need to find an interesting replacement

**Comment by PKPenguin321** [comment]
My idea would be to make it a relative of a centcomm high-up and randomly generate a tiny bit of family tree and centcomm managerialbabble, like "Third Cousin of the Chief Central Supply Officer" or "Distant Nephew of the Lead Death Squad Inspector." This lets you basically keep the defacto-royalty thing (that you're ripping off from Rimworld btw) while keeping it in-universe.

They can even still have the same fancy armor and sword but it would be like, explicitly not-medieval. "Decorated Bulletproof Cuirass - This space-age armor is functional, but disgustingly gaudy. Only the most desperate or the most spoiled-from-birth elite would go through with wearing it." The captain already has a sword so maybe they could also just have something like that, just something distinguishing of their rank rather than a literal ancient claymore (this can have as much effort as a new sword based off of the one the captain has or as low as just changing the desc of what you already have). Instead of being from ancient times where "gun spooky gun bad ook ook" they could instead just be so pampered and sheltered that such weapons are completely alien to them, or below their status entirely.

**Comment by AndroidMK2** [comment]
I got an idea, there could be a protagonist called
 „Deep-space explorer”, he would arrive with a  makeshift revolver (similar to a detective revolver) but it can only be loaded with one or 2 bullets at a time and you can't quick reload it with the revolver magazines (the ones that are used in det's revolver and syndie one) so you would have to hold the bullets individually to reload.
Either SWAT helmet with armor vest or hardened EVA suit that grants 20 bullet, 10 laser, 0 bio, 0 rad, 10 energy, 15 melee, 35 fire, explosive 20 and space proof
Old combat uniform (grants no protection)
Worn out combat gloves (slightly decrease electric shock damage and nothing more)
Toolbelt (only with crowbar and wrench)
Worn out combat boots (grants no protection)
Satchel/backpack with survival box and large air tank
Can/will arrive implanted with mindshield implant to avoid problems with possibly being culted or rev'd to not be too op for those antags.
His primary objective could be like a one-man law enforcer.

**Comment by Time-Green** [comment]
Since we’re all submitting our own OC’s for protagonists:

Golden Lizard

Lore: A nanotrassen breeding facility has been under fire by “lizard sympathizers” for the imprisonment of lizards (even though they signed away their rights as hatchlings) and their attempts to use these lizards to breed a special “golden lizard”. To show everyone how happy and free the golden lizards are, nanotrassen has graciously allowed these lizards to take a vacation to one of their state of the art space stations. 

Description: A golden digitgrade lizard with a slight shine. Has extremely valuable golden lizard skin and will periodically drop valuable golden scales (more when overfed). Their hugs and presence give great mood boosts. They’ve never seen the outside world and never really cared for it either, since they never knew any better.

Equipment: 
Comes wearing a collar reading: PROPERTY OF NANOTRASEN (EXPENSIVE)
Has a tracking implant
Comes with a baggie of dried mice 
Scared button: A small device they can press in-case they’re scared (will alert medbay and sec with location)

(Also yes I will eventually code these myself but it’ll be after the feature freeze)

**Comment by Bawhoppen** [comment]
There's a million good ideas- definitely can't actually be a highranking official themself, but a relative of one though. 
For the superweapon, I feel like a bit better flavor is in order somehow. Like superweapon is too blatant, though experiment would be too generic. Something worth thinking on by everybody.

**Comment by interestingusernam3** [comment]
> Comes wearing a collar reading: PROPERTY OF NANOTRASEN (EXPENSIVE)

sus

**Comment by Malgover** [comment]
So basically, mime and clown with extra steps lol?

**Comment by Fikou** [comment]
> So basically, mime and clown with extra steps lol?

yeah except completely different

**Comment by Malgover** [comment]
> > So basically, mime and clown with extra steps lol?
> 
> yeah except completely different

Extremely gimmicky roles that exist only to be gimmicky and disrupt the round with their annoying antics sound exactly like the mime and the clown.

**Comment by tralezab** [comment]
I certainly cannot do this until after the freeze IMO

**Comment by Time-Green** [comment]
NNOOOOOOOOOOOOOOOO

**Comment by EuclidianGeometer** [comment]
i hope you come back to this some day, i think this would be a really, really fun little station trait.

**Comment by Time-Green** [comment]
@tralezab freeze is over you can continue now

**Pull request closed without merging**
