### PR TITLE
idi nahui(no russians allowed)

### PR DESCRIPTION
**Pull request by Iamgoofball**
# anti-russian picture:
official_portrait_of_president_reagan_1981

### CODE REVIEW

**Comment by kevinz000** [comment]
fuck you

**Comment by Iamgoofball** [comment]
fuck you

**Comment by ExcessiveUseOfCobblestone** [comment]
Is it that time of the month goofy?

**Comment by Iamgoofball** [comment]
yes

**Comment by ElfLeaderMike** [comment]
fuck you

**Comment by Iamgoofball** [comment]
mccarthy

**Comment by optimumtact** [comment]
make a pr with real comments and a proper description

**Pull request closed without merging**
