### PR TITLE
Fixes pump UIs not respecting max_pressure/max_rate setting

### LINKED ISSUE #53659: Atmospherics devices cannot have transfer rate set above half (200L/s) in the ui
## Round ID:
[146148](https://scrubby.melonmesa.com/round/146148) but not relevant

## Testmerges:
none relevant

## Reproduction:
Volume based atmospheric devices were changed to have a maximum transfer rate of 400L/s in #52981. This is reflected in their values at roundstart/creation via rpd/alt+clicking or using the max button in their ui. However attempting to set values above 200 with the slider/ typing it in fails. Also applies to atmospherics supply tank consoles.

### PR DESCRIPTION
**Pull request by Donkie**
## About The Pull Request
Fixes #53659 

Also fixes the same issue with the new pressure valve. The tgui for some reason had hardcoded the max_rate/max_pressure despite them being readily available.

## Why It's Good For The Game
Bugs

## Changelog
:cl:
fix: Fixed max transfer rate/max output pressure in the gui of atmos devices not working correctly
/:cl:

### CODE REVIEW

**Review by Rohesie — DISMISSED** [review]

**Comment by stylemistake** [comment]
Can you do this for all atmos devices?

**Comment by Donkie** [comment]
What do you mean? This UI is shared by all relevant atmos devices

**Comment by stylemistake** [comment]
https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosTempPump.js
https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosTempGate.js
https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosControlConsole.js
https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosFilter.js
https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosMixer.js

**Comment by Donkie** [comment]
> https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosTempPump.js
> 
> https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosTempGate.js
> 
> https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosControlConsole.js
> 
> https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosFilter.js
> 
> https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/AtmosMixer.js

Ah, I'll implement for them as well soon

**Comment by Donkie** [comment]
@stylemistake done

**Pull request merged**
