### PR TITLE
Fixes admin pref for ignoring cult summons, renames IsAdminGhost

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
to quote garfield, whoever made IsAdminGhost a check for the admin AI interaction option WITHOUT EVEN MENTIONING IT IN THE PROC DESC should be dragged out into the street in shot

## Why It's Good For The Game
i can go back to alt tabbing without getting cult summoned as god intended

## Changelog
:cl: Ryll/Shaps
admin: Fix admin pref for ignore cult summons
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
to quote garfield?

**Comment by saprasam** [comment]
this pr was made because beatrix kept orbiting me while playing helltaker while i was cheesing out cult ghosts

**Comment by Ryll-Ryll** [comment]
> to quote garfield?

https://www.youtube.com/watch?v=W3kdle-juSA

**Review by kriskog — CHANGES_REQUESTED** [review]
Changing the behaviour of IsAdminGhost is going to cause issues when people who didnt get the memo tries to use it. While the new use is more in line with the name I would rather you rename the new proc to make it clearer that it is in fact a new proc, to avoid confusion. The renaming of the AI proc is fine.

**Pull request merged**
