### PR TITLE
Bartender Drink Sliding: Intrinsic to Extrinsic

### PR DESCRIPTION
**Pull request by Incoming5643**
Moves the rarely utilized bar drink flinging ability from an intrinsic bartenders are born with to an extrinsic book that anyone can learn the art from. Bartenders start with the book but it's also available from cargo. Also allows the ability to toggle where as previously bartenders were just stuck with it.

:cl:
add: The ability to throw drinks without spilling them has been moved from something bartender's just know how to do to a book that they spawn with, the ability has also been made into a toggle.
add: Any number of people can read the book to learn the ability, and it can also be ordered in the bartending crate in cargo. Bartenders are encouraged to keep their trade secrets close to their stylish black vests.
/:cl:

[why]: # When it comes to special job based abilities, seperating the player from the skills is useful because it:

A. Gives people something to covet / steal.

B. Doesn't deny people who changed into the job the ability.

C. Helps to remind people that these abilities exist.

### CODE REVIEW

**Review by ChangelingRain — APPROVED** [review]

**Comment by WJohn** [comment]
Hmm, would it maybe be better if everyone could do this simply when they are next to a table? I don't know if there's any great way to prevent drinks from being "slid" onto a table with a gap between you, if you stand next to another table.

**Comment by Incoming5643** [comment]
Well I mean another benefit of making it extrinsic is that if people don't think they'll use it and don't want the action bloat on their screen they can just not read the book. Get what you're saying though.

**Comment by coiax** [comment]
I understand the intention in removing stuff being somehow intrinsic to your role name, but I don't really like it being toggleable or action button.

Why not just giving the barkeeper a pair of "barkeeper's gloves", or let anyone with beer goggles do it?

**Comment by ExcessiveUseOfCobblestone** [comment]
they want all the benefits of intrinsic without just making it intrinsic silly

**Comment by ExcessiveUseOfCobblestone** [comment]
also why not just put this under the bartending shades?

**Comment by ExcessiveUseOfCobblestone** [comment]
cough cough components cough cough

**Pull request merged**
