### PR TITLE
pink belt fix

### LINKED ISSUE #50892: missing sprite: PDA in belt slot.
Issue reported from  Round ID: [136312](https://scrubby.melonmesa.com/round/136312) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

This occurs with all PDAs as far as I can tell.

### LINKED ISSUE #50894: Missing stunbaton texture when put in belt slot
Issue reported from  Round ID: [136312](https://scrubby.melonmesa.com/round/136312) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

### PR DESCRIPTION
**Pull request by Fhaxaris**
fixes stun batons and PDAs and probably a bunch of other crap from being purple lol
resolve #50892
resolves #50894

**this only fixes the stuff with sprites that just aren't being used correctly.**

## Changelog
:cl:
fix: purple belts
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this is not the proper fix

**Comment by Fhaxaris** [comment]
explain further

**Comment by nemvar** [comment]
>Setting isinhands to TRUE when the item isn't inhands
yikes
I appreciate the initiative but this isn't it chief.

**Comment by Fhaxaris** [comment]
is it better now also:
https://github.com/tgstation/tgstation/blob/4ac1d9f77a7a4a38435912e01254ee473cdecfd2/code/modules/mob/living/carbon/human/update_icons.dm#L507-L508
the only purpose is to make it use the item state.

**Comment by nemvar** [comment]
The thing is, item_state is literally ONLY supposed to be used for inhands. ONLY belts use item_state for their mob overlay. The proper fix would be to make the behaviour consistent with everything else, aka, use icon_state for mob overlay.

**Comment by Fhaxaris** [comment]
for example, take the stun baton. it switches between icon_states, "stunbaton" and "stunbaton_active". it uses the separate item_state "baton" for the in-hands and the character display because otherwise, you would need two icons for each active and inactive state for the stun_baton.

likewise, the PDA works the same way. there are a ton of different PDA icon_states, but they all use the item_state "electronic" for showing on your character.

Using icon_state for mob overlay with belts/suit slot would make it so items with multiple states like the PDA or stun baton would now need multiple sprites for each icon state. I agree that this solution is better and makes things more consistent and less confusing. But my pr doesn't break belts that are already set up the correct way like the officer's saber sheath and fixes belts that are broken like the stunbaton and PDA.

**Comment by optimumtact** [comment]
thog think you have a dented brain

**Comment by ShizCalev** [comment]
not quite what's needed here, sadly.

**Pull request closed without merging**
