### PR TITLE
Roundstart Animation

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl: Cyberboss
imageadd: Added roundstart animation
/:cl:

Will record later, it's the same thing as the round end animation except it fades out the splashscreen during 'Welcome to the station crew' and locks players in place for the 3 second duration

This gives players a moment to get their bearings/catch up if they're lagging before things get hectic

### CODE REVIEW

**Comment by coiax** [comment]
Traditionally engineering needs at least 30 seconds to release the singularity.

**Comment by Niknakflak** [comment]
:+1:

**Comment by KingPhilipIII** [comment]
Now I have a moment to get my bearings before that mad dash and fight to the death for the insulated gloves/toolbelt in tool storage.

**Comment by Cyberboss** [comment]
Depends on #24370

**Comment by Cyberboss** [comment]
Video in 2 hours or so

**Comment by coiax** [comment]
I DEMAND A VIDEO OF "TITLE FADES TO STATION", I AM INCAPABLE OF IMAGINING IT

**Comment by optimumtact** [comment]
This depends on a pr you closed

**Pull request merged**
