### PR TITLE
redesigns the bar

### PR DESCRIPTION
**Pull request by pudl**
:cl: Quiltyquilty
rscadd: The bar has seen a redesign.
/:cl:

This is a bar redesign
- The bartenders poker table has been exchanged with two small ones. The money has been moved into the back room
- Another slot machine has been added
- The instruments in the dorms have been moved to the theater
- The left side of the bar now has shuttered windows w/ a bar behind the bar table
- Theres now an extra deck of cards and a premium cigar in the bar
- The metal glass and cable coils have been moved into the formal closet
- Two lamps (one green one grey) have been added to the formal closet

MERGE TOKEN #18145

### CODE REVIEW

**Comment by coiax** [comment]
No poker table. Bad.

**Comment by Bawhoppen** [comment]
:-1: does not need a changelog

**Comment by KorPhaeron** [comment]
I've never seen anyone play the slot machines, but I have seen people play cards

**Comment by pudl** [comment]
Poker table was ugly as shit

**Comment by Bawhoppen** [comment]
also its a shit change too

**Comment by PKPenguin321** [comment]
To be honest the cheridan bar has grown on me

**Comment by Cheridan** [comment]
looks like i win again

**Comment by Iamgoofball** [comment]
remove 2 of the dining tables and put a poker table setup

**Comment by MMMiracles** [comment]
bring back my poker table you smuck

**Comment by TrustyGun** [comment]
i would like this a lot better if the poker table and cards were added back

**Comment by Supermichael777** [comment]
cut the theter and add a poker table there

**Comment by optimumtact** [comment]
Looks like you redpilled yourself

**Comment by Zilenan91** [comment]
%100 yes this is so much better than what we have now :+1:  :+1:  :+1:  :+1:  :+1:

**Comment by pudl** [comment]
@Zilenan91 Im not going to give the bartender kitchen access sorry

**Comment by Iamgoofball** [comment]
@pudl he has it on all the other maps

**Comment by pudl** [comment]
@Iamgoofball Box is not like other maps

**Comment by Iamgoofball** [comment]
dont pull that shit you know it's not true

**Comment by pudl** [comment]
Look. Its never gonna happen

**Comment by TrustyGun** [comment]
okay this is better :+1:

**Comment by Zilenan91** [comment]
He actually doesn't have kitchen access on other maps. On Meta he only has access to the bar and his back room. The only maps he has access to the kitchen are the ones where he takes over the job of both the Chef and Bartender.

**Comment by GunHog** [comment]
Okay, it is properly "redpilled", now!

**Comment by pudl** [comment]
Remove the tag i have a merge token now

**Comment by Niknakflak** [comment]
I always disliked the half poker table, half bar thing.  It was ugly.  Sorry Cheridan.
Maybe set up a poker table next to the windows or something? I dunno.

**Comment by Zilenan91** [comment]
Yeah it was ugly. It also wasn't functional and people would go and wrench them and break into the bar.

**Comment by pudl** [comment]
TELL EM NIKNAK
TELL EM

**Comment by coiax** [comment]
I withdraw my objection. The lamps in the wardrobe closet are weird though, feels like they'd be better stored in a crate rather than with the outfits.

**Comment by Iamgoofball** [comment]
@optimumtact you realize cheridan put the DNM on right

**Comment by pudl** [comment]
@Iamgoofball I specifically asked cheridan to put on dnm because i was redesigning the bar from my original design. oranges removed it because i finished my redesign

**Comment by Iamgoofball** [comment]
ale mao

**Comment by optimumtact** [comment]
if cheridan doesn't want a pr merged, they can close it

**Comment by TechnoAlchemisto** [comment]
>not mentioning the blast doors at all in the PR

nice nice

**Pull request merged**
