### PR TITLE
Kudzu Rebalances v2

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
- Increases kudzu's maximum mutation severity to 25 from 20.
- Event-spawned kudzu now will have a flat +10 bonus to its maximum severity, meaning that it'll now range from 27 to 35 to compensate for it not being manually made.
- Explosive kudzu mutation is now classified as maximum severity.
- New "Temperature stabilisation" SEVERITY_AVERAGE mutation as a compensation for coldmos and the worry that cold environments can be too harsh to kudzu without the coldproof mutation by offering another alternative. It has the same power  as the space heater at 40000J per atmos tick (101.325 kPa of air mix at 293.15K has 2079J/C of heat capacity, so around 20C change to that turf per atmos tick, even larger if its depressurised).
- Nerfs the venus human trap's vine throw by making it have the cooldown of a regular baton (4 seconds vs previously 3), since the knockdown is only 1 second long this should be fair in exchange for keeping the 85 stamina damage in.
- Doubles the mutativeness scale factor, meaning that the probability of kudzu mutating in general has been doubled.
- Also adds some previously missing #undef's at the end of the file.
- **NEW CHANGES:**
- Kudzu spread rate has been changed, event kudzu is now guaranteed to spread at least 3 times per second (which is now actually adjusted for delta_time), and in general kudzu now gets a boost when it just spawned to help it not die instantly. A graph of the new formula is https://www.desmos.com/calculator/ynvbzspkmo.
- Slightly more documentation to some of kudzu's variables

## Why It's Good For The Game
I nerfed kudzu a bit too hard in #64675 , this rebalances it slightly by implementing some of the ideas from #65124 , especially with event kudzu it has been nerfed a bit too hard with a hull breach or crew being next to it instantly killing it.

## Changelog

:cl: RandomGamer123, some ideas from the-orange-cow & cacogen
balance: The explosive mutation for kudzu is now classified as a severe instead of just above average mutation
balance: Venus human trap vine throw cooldown increased to 4 seconds
balance: Kudzu's maximum mutation severity in general has been increased
balance: Event-spawned kudzu's maximum mutation severity has been further increased
balance: Kudzu now mutates twice as often in general
balance: Event-spawned kudzu now has its minimum spread rate tripled
balance: Newly spawned kudzu in general has its starting spread rate buffed
expansion: New temperature stabilisation mutation for kudzu as a semi-alternative to cold proof and being a beneficial kudzu mutation in general, effectively functions as a space heater with the target temperature being 20C
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
does this add a cooldown for the vine pull, or just the vine throw?

**Comment by RandomGamer123** [comment]
> does this add a cooldown for the vine pull, or just the vine throw? it looks like it hits both, which is pretty sad, bc the vine pull is cool thematically but near-useless if it competes with the vine throw and can only pull someone one tile every 4 seconds

Vine pull has half the cooldown of vine throw like before, so vine pull would get slightly increased from 1.5 seconds to 2 seconds

**Comment by cacogen** [comment]
Kudzu needs to be changed to grow rapidly in the very beginning because it's almost always come across early and killed in its infancy, to the point the event has no effect but to give people the kudzu seeds for killing it which they probably aren't even allowed to use.

**Comment by RandomGamer123** [comment]
> Kudzu needs to be changed to grow rapidly in the very beginning because it's almost always come across early and killed in its infancy, to the point the event has no effect but to give people the kudzu seeds for killing it which they probably aren't even allowed to use.

That's a good suggestion I'll mess with different functions for spread_multiplier

**Comment by RandomGamer123** [comment]
bump

**Review by tralezab — APPROVED** [review]
not much to review here, its number gahbage. let's see if your number garbage works though >:)

**Comment by TheSilverNuke** [comment]
Is there a chart of the traits with the corresponding level of severity? That way you can mix and match ahead of time. The wiki for Kudzu hasn't been updated in awhile.

**Comment by RandomGamer123** [comment]
Not before this, so I just made one
And I'll update the wiki as well
kudzuchart

**Pull request merged**
