### PR TITLE
adds bronze windows and airlocks

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds bronze windows and fulltile bronze windows, they are like normal windows but with clock sprites
adds bronze airlocks, same as regular airlocks but have clock sprites

## Why It's Good For The Game

bronze stuff is one of my favorite things as chaplain, and now being able to make some windows and airlocks is cool, they are pretty much harmless too, not reinforced and just have cool sprites

## Changelog
:cl:Fikou
add: You can now make bronze windows and airlocks
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
[Verified]

**Comment by Fikou** [comment]
hello mr bot where is my label

**Comment by Time-Green** [comment]
you should add flesh doors, floors and walls aswell if you like chaplain that much

**Comment by Fikou** [comment]
> you should add flesh doors, floors and walls aswell if you like chaplain that much

floyd is already doing meat datum mat :^)

**Comment by Qustinnus** [comment]
don't add more shit to the old crafting system. the entire point of mat datums is that you dont do shit like this anymore.

**Comment by davethwave** [comment]
Finally, I can FULLY revamp the chapel in brass.

**Pull request merged**
