### PR TITLE
Revert "Dominators now require a significant amount of open turf around them"

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
Because robustin cannot into circles, it is physically impossible for a gang to have enough space visible to dominate.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Also test your shit @Robustin for fucks sake

**Comment by GunHog** [comment]
## MATH

**Comment by ohnopigeons** [comment]
Did someone say math

**Comment by KorPhaeron** [comment]
STOP :clap: MERGING :clap: UNTESTED :clap: ROBUSTIN :clap: PRS :clap:

**Comment by Mey-Ha-Zah** [comment]
What kor said

**Comment by Cyberboss** [comment]
Keep this fucking label

**Comment by GunHog** [comment]
> STOP :clap: MERGING :clap: UNTESTED :clap: PRS :clap:

I fixed it for you.

**Comment by ohnopigeons** [comment]
I think I found the problem

Ironically it's not even his fault.

Except for the testing part. That is entirely his fault.

**Comment by ohnopigeons** [comment]
`for(var/turf/T in circleviewturfs(center=A,radius=3))`
A = π\*r\*r = 28 approximately

`if(open < 40)`

Where do spacemen learn their maths?

**Comment by ohnopigeons** [comment]
`_ _ @ @ @ _ _`
`_ @ @ @ @ @ _`
`@ @ @ @ @ @ @`
`@ @ @ @ @ @ @`
`@ @ @ @ @ @ @`
`_ @ @ @ @ @ _`
`_ _ @ @ @ _ _`

37

**Pull request merged**
