### PR TITLE
[WIP] Spacepods

### PR DESCRIPTION
**Pull request by ghost**
NO THEY'RE NOT MECHS. AND NO THE VEHICLE COMPONENT CAN'T BE USED FOR THIS, THAT'S MADE FOR SEGWAYS/BIKES/SCOOTERS!

# if this is merged, SQUASH IT. GITHUB HAS A SQUASH OPTION

:cl: More Robust Than You
add: Spacepods have been added, which can be built via a spacepod fabricator. Spacepods can be equipped with many things, including lasers, disablers, kinetic accelerators, and plasma cutters!
/:cl:

see https://nanotrasen.se/wiki/index.php/Space_Pods for how they work

yooray

**Podbays mapped in**
All podbays have a pod fabricator, the materials to build a basic pod, tools, a spacepod tracking computer, and an research server for syncing with RnD. Also, armories now have two pieces of security spacepod armor and two pod lock busters.

## Box podbay
box
## Meta podbay
meta
## Delta podbay
delta

**Credits:**
@GunHog - fixing tgui and being a good beta tester!
@ShizCalev - mapping podbays onto delta
@pubby - mapping podbays onto box and meta
"not dichard but rick" on the Hippie discord for spriting the action buttons
and everyone on #coderbus for helping me do this!

### CODE REVIEW

**Comment by Buggy123** [comment]
Finally

**Comment by deathride58** [comment]
Rebase and squash commits

**Comment by MoreRobustThanYou** [comment]
@deathride58 duh

**Comment by nicbn** [comment]
Please no

**Comment by Tlaltecuhtli** [comment]
code seems working

**Review by Tlaltecuhtli — APPROVED** [review]

**Comment by epochayur** [comment]
PR of the century

**Comment by MoreRobustThanYou** [comment]
pinging @kevinz000  ---- i need some spacepod related tech nodes

**Comment by Kerbin-Fiber** [comment]
I mean like, yay for space pods but... What the fuck is up with the consistency of the placement of the bay for them? It's in the Aux Base for Box, Engineering Foyer for Meta and Atmos(?) on Delta?

**Comment by praisenarsie** [comment]
if people actually expect this to get accepted then i'm surprised

**Comment by MoreRobustThanYou** [comment]
closed so i can actually bother to rewrite these

**Pull request closed without merging**
