### PR TITLE
Add a note about non human races

### PR DESCRIPTION
**Pull request by optimumtact**
Alright, this has gone on long enough.

Offically codebase policy from this point:

* no new races unless they are really, really really unique and interesting (that means no ports of existing races)
* Cat people won't change from their current status quo as human mutation items for ears and tail

Can you please stop making these PR's now? That goes for all sides of the debate.

### CODE REVIEW

**Comment by Arianya** [comment]
Goof just got BTFO

**Comment by Iamgoofball** [comment]
:-1:

the players expressed that they wanted it

**Comment by dannno** [comment]
you genuinely wonder why people treat you the way they do, goofball

**Comment by Arianya** [comment]
There really is a label for every opportunity.

**Comment by Jordie0608** [comment]
We can make them on the fly, and delete them because stop adding dumb labels.

**Comment by Archie700** [comment]
>the players expressed that they wanted it

I'm apparently the entire player base now.
As the player base I say we add erp verbs and turn this into lifeweb/newfallout13.

For real, we should just punish grudgecoding in general.

**Comment by Arianya** [comment]
Archie you have to understand, any change Goof wants is "the playerbase wants this!!". Any change Goof hates he will never bring up player opinion because it doesn't help his political PRs.

I make the motion that before goof can make Feature PRs he needs to get a player poll on each one to clearly show a mandate for a change 📯

**Comment by lzimann** [comment]
when are we going to remove all non-human races

**Comment by Supermichael777** [comment]
Please understand that cat-man won a 2 week player vote.  This is literally just the opinion of oranges.  Hes so triggered by cats that me adding a tongue to the actual cats as a joke triggered his slippery slope ptsd.  This man can not keep his personal bias out of his official duties, hes never been able to do that, WHY DID YOU GIVE HIM POWER?

**Comment by dannno** [comment]
Can you actually come up with something meaningful and worthwhile that "cat people" would contribute to the game
Maybe that's a stupid ask considering some things in the game as is but I feel like you and oranges are both getting uppity over something that doesn't even matter that much

**Comment by Supermichael777** [comment]
> I'm unhappy my preferred option lost a player vote and wish to bury the feature.

Nice meme, where did you find it?

**Comment by lzimann** [comment]
they need to RP their snowflake anime girl, that's why they want catgirls

**Comment by Supermichael777** [comment]
this is literally just so he can block fixes until he can say ROIGHT IT TO BROKE GOTA RIP IT OUT.

**Comment by Ricotez** [comment]
It uses the race accessory system, so it's unlikely to break without lizards breaking as well.

**Comment by Arianya** [comment]
Plus "don't add new features" isn't the same as "don't fix bugs on this feature"

**Comment by Archie700** [comment]
@Arianya I was making a jab, I know very well about goofball.

**Comment by optimumtact** [comment]
@Archie700 I assume they were referring to @Supermichael777 

I'm not sure where their salt is coming from but I have no strong opinions on cat people, they were added as the exemplar items for the mutations framework and the admins chose to enable them.

I added them as the second rule because the fact they exist might lead people to believe we implicitly support an actual non human feline race, when that is not the case.

**Comment by Archie700** [comment]
@oranges I was referring to Arianya's post after me when I made a quip about making erp verbs because Goofball said I was the playerbase.

**Comment by coiax** [comment]
Putting policy stuff in a coding contributing file is ugly

**Comment by Grazyn** [comment]
@optimumtact so are they human or non-human in regards to silicons?

**Comment by optimumtact** [comment]
@Grazyn what, that's a matter of server policy, it has nothing to do with what is going on here?

@coiax there's nowhere else we really have to put these things as the codebase is pretty informal for most things

**Comment by Super3222** [comment]
The philosophy about nonhuman races that we have on Yogs is that every individual race carries legitimate traits that make its authentic, and creates a whole new experience compared to being a human. So basically no snowflakey type of shit or a case where we enable two different plant type of species.

But seriously, why would you want to have a bunch of resprited humans that have nothing special about them? It's unappealing, bland, and boring. Unless you attach RP to them on an RP server like Vox on paradise, than maybe players would get a kick out of them.

**Comment by kevinz000** [comment]
@Super3222 because I want cat ears so I can be more of a meme then I already am :^)

**Comment by Supermichael777** [comment]
i could make a full neko race and force space ninjas to be cat weebs.

**Review by Razharas — APPROVED** [review]
I approve

**Comment by KorPhaeron** [comment]
It's more or less the rule we've already been operating under, feels weird to add in response to shitposting PRs though.

Feels like it will be used as an excuse for more shitposting in the future when someone inevitably makes an interesting new race and someone accuses of us of breaking the rules by merging it (and then makes another PR about merging ponies/tajaran to "prove a point")

I also hope it doesn't stop someone from making something interesting because they find the rule discouraging.

I guess I'm ambivalent on it since the rule is vague enough to provide an out later.

**Comment by optimumtact** [comment]
Well I have to be the bad guy either way

**Comment by KorPhaeron** [comment]
Yeah basically

**Pull request closed without merging**
