### PR TITLE
Changes to the crew monitoring computer

### LINKED ISSUE #10498: Proposed changes for the crew monitoring computer
Alright, let's attempt to make everybody happy (see https://github.com/d3athrow/vgstation13/issues/5297).

* If there is sufficient room expand the health indicator to show the full health statistics in addition to the indicator. i.e., if the player increases the width of the crew monitoring computer it'll show the additional statistics. **done**
* Hovering over the area shows the X and Y coordinates in a tooltip. Clicking on the area should copy the coordinates to the clipboard. (This may be natively possible, otherwise you'll have to perform an additional CTRL-C which I'm sure is not a problem since you'd have to do that anyway.) **done, click copies to clipboard (don't ask)**
* Functionality to switch z-levels, with a compile flag to disable this behavior so /tg/ doesn't get this change. **WontFix, this is up to /vg/ to implement in their own branch if they want it IMO**
* Map zooming/scaling. This has actually been suggested before but I hadn't given it much priority. (In my eyes you'd use the mouse wheel to zoom in/out, but you'd receive scrollbars as the map wouldn't fit on the entire screen anymore.) **done**
  * When hovering over a person in the table center the minimap around the player (if applicable) **done**
* Unsure on what to do with AI. Should it be able to view the health? Doesn't this make the AI too powerful? We need to settle on this once and for all. **AI can view health proper again; delay of 5 seconds between updates**

### PR DESCRIPTION
**Pull request by nullquery**
This PR introduces the following changes:
- procqueue: Added the ability to schedule proc execution. This is used by the crew monitoring computer to delay updates by 5 seconds (50 ticks)
- Refactored the javascript and css files in the html_interface module, moving them to their own subfolder.
- Bug fix: The Nanotrasen layout was overriding a core html_interface module function. (Thanks to @D3athrow for pointing this out.)
- Crew monitoring: The minimap now supports scaling. You can zoom in and out using the buttons. Hovering over an entry in the table centers the minimap on that part of the screen.
- Crew monitoring: If the window is wide enough the health indicator will expand to show full health data (if available).
- Crew monitoring: Clicking on the area name will now copy the coordinates to your clipboard.
- Crew monitoring: The AI can view health information again, but there is a 5 second delay between updates for everyone watching.

See https://github.com/tgstation/-tg-station/issues/10498 for the accompanying issue.

**IMO PR can be merged without issues, but you may want to test the crew monitoring computers first to see if it works in across all platforms/cases.**

Resolves #10498

### CODE REVIEW

**Comment by Chocobro** [comment]
>ZOOMABLE MAP
okay it's official I have thirty boners how can people hate this

**Comment by Iamgoofball** [comment]
:+1: x :100:

**Comment by Miauw62** [comment]
can you please fix the crew monitor working on z2?

**Comment by GunHog** [comment]
So much delicious! :+1:

**Comment by d3athrow** [comment]
geeze noobs vg's had this for like 2 whole days

**Comment by duncathan** [comment]
@d3athrow Yeah, because your players shat on nullquery.

**Comment by d3athrow** [comment]
@duncathan They didnt shit on nullquery, they shit on the thing he made which was a direct downgrade of what we had already. I'm sorry if you can't understand that we don't care about your feefees so i'm sorry if you got your feelings hurt that somebody was unhappy with the result!

**Comment by ike709** [comment]
please add "Resolves #10498" or "Fixes #10498" so the issue will be closed automatically.

**Comment by freerealestate** [comment]
Size of the map and lack of visible health information were a couple of the few drawbacks I'd had with this :+1:

**Comment by nullquery** [comment]
@Miauw62 Not sure what's going on with z-level 2. Will have to look into it, but I don't have much time at the moment. If someone else wants to take a look feel free to do so, you can create a PR on my hi-extended branch on nullstation/-tg-station.

**Comment by GunHog** [comment]
Merge this!

**Pull request merged**
