### PR TITLE
Medicine Sans Frontiers [For testing purposes, DNM]

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Removes the virologist, chemists, geneticists slots.

Gives access to all of medbay to Medical Doctors (who have an appropriate number of slots to compensate for the other jobs being missing).

It worked for science, lets see if it works for medbay.

Intended to be test merged, so I didn't actually remove the jobs, just dropped their available slots to 0. I also didn't rename Medical Doctor to anything more general (like Medical Staff) because I want this to fuck with save preferences/jobbans as little as possible if it's going to be a temporary thing.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@Iamgoofball

**Comment by PKPenguin321** [comment]
>tfw all your doctors want to do virology

**Comment by Iamgoofball** [comment]
You need to make the map changes involving renaming the spawn points for these jobs to Medical Doctor so they work properly. Either that or drop Medical Doctor spawn points on the same tile.

**Comment by KorPhaeron** [comment]
@pkppenguin321

I'm more worried about chem honestly.

But people manage to divide labor fine in science, even toxins, so no harm in trying. 8 people with viro access might mean killer diseases actually get released

**Comment by Iamgoofball** [comment]
Worst case scenario, we remap medbay to support 3-4 people in each job room.

**Comment by Lumipharon** [comment]
Friendly reminder that lowpop gives med staff access to the different med workplaces, and high pop doesn't ned this since they should be filled.

**Comment by Iamgoofball** [comment]
Friendly reminder that isn't relevant to the discussion at hand.

**Comment by pudl** [comment]
Thank you so much. I see no idea why virology and chemistry needed job slots, however, genetics I think should stay its own job, since it's a half-way ground between research and medbay.

**Comment by Iamgoofball** [comment]
@pudl science has no reason to ever enter genetics except for when they're escaping from science.

they're under the jurisdiction of the CMO, and if we polled players I'm willing to bet at least 70% would agree it's more a medical department than a research department.

**Comment by pudl** [comment]
The only reason that people view Genetics as a medical department is because of its side function of cloning. Meanwhile, the actual research part of it that is the scanners operates identically to something you would normally see thrown into the gigantic broiling pot of classic research bullshit. Two computers, fucking around with monkeys, using radiation, etc. People have just come to associate genetics with cloning so much that they think the only reason it exists is for medical.

**Comment by Iamgoofball** [comment]
Under that logic, Virology should be research too.

They fuck around with injecting monkeys with viruses, they have to discover symptoms, and they mutate virus cells to get new symptoms.

**Comment by pudl** [comment]
Yep.

**Comment by KorPhaeron** [comment]
Dont forget botany and chemistry

**Comment by Iamgoofball** [comment]
and technically Chemistry would be too, they have to mix chemicals and then test them on players or monkeys

if you say it isnt because they follow a set route that doesn't change, neither does actual R&D.

**Comment by pudl** [comment]
Chemistry, genetics, and virology all fall under medical research. They're medical departments but they research things. Genetics is the only one that's official, so they get their special connection.

**Comment by Fox-McCloud** [comment]
I don't like this, at all. It's going to inevitably lead to infighting for Viro, chemist, and genetics to a ridiculous degree...not to mention it pretty much removes even the remotest sense of secrecy and privacy for some jobs.

**Comment by pudl** [comment]
Lmao people fighting over who gets to go to virology. I would rather fight to NOT have to go to virology.

**Comment by optimumtact** [comment]
:-1:

**Comment by Bawhoppen** [comment]
Yea, I don't like the idea of this change. It works for science but I don't think it would work for medbay.

**Comment by Iamgoofball** [comment]
# why don't we test run it first with the fancy new PR test run system designed for this shit

**Comment by Bawhoppen** [comment]
Test it but it better be getting fucking reverted if its shit (which is will likely be)

**Comment by Iamgoofball** [comment]
# what is "we dont need to revert a testing PR because it isn't merged in"

**Comment by Bawhoppen** [comment]
I MEAN IT BETTER NOT BE ACTUALLY MERGED AFTERWARDS HOLY FUCK GOOFBALL YOU AND YOUR SEMANTICS

**Comment by Miauw62** [comment]
certainly worth trying, this might actually make deadly diseases viable as something else than a way to get lynched :+1:

**Comment by Fox-McCloud** [comment]
@Miauw62 

How does that even make sense? Since anyone can trounce into Viro and not just the CMO now, it makes it MUCH less viable to work covertly in viro.

The larger pool doesn't make up for the lack of privacy and much easier cure generations on a mass scale.

**Comment by Miauw62** [comment]
yes and if you release a virus as it stands now the first thing that happens is "LYNCH VIROLOGIST"

**Comment by Fox-McCloud** [comment]
While I agree that's problematic, so is losing most of your secrecy, control over easy cure distribution, and lack of oversight, which is pretty much the only thing that the job has going for it at the moment.

**Comment by bustygoku** [comment]
Virologists are the roboticists of medbay. Please keep it to one slot. Let MDs revive people and pump out chems, but viro should remain the NEET weirdo everyone laughs at when he comes out of his cave.

**Comment by Nanotransistor** [comment]
Not a fan, and it's a reason i don't play science at all. Science has like 4 offices? From which only two are worth using, and every time you spawn as a scientist you need to hope that either you spawned in the office you wanted, or that someone else didn't get there first.

That said,  having each office separated into specific jobs not only is more organized, it prevents anyone to easily get access to dangerous substances like those found in viro, genetics and chemistry. It's also annoying when random people keep entering your workplace and disrupting what you are doing.

**Comment by Shapsy** [comment]
I can't WAIT for there to be no accountability for what people do in chem anymore and for people to constantly pump out lube to give to the clown

At least with 2 dedicated chemists you had a 50/50 for which one of them was giving out lube

**Comment by Incoming5643** [comment]
"it worked for science" is a bad arguement. The codebase never had science seperated out into seperate jobs in the first place. It's always been just "scientist", and never "researcher" "xenobiologist" and "toxineer"

If anything splitting science into those jobs is the more interesting experiment here, but people would get so maaaaad.

**Comment by pudl** [comment]
Incoming, r4407 only had robotics in medbay, and science was purely toxins and a very early version of chemistry. So you have it backwards, because medbay was three jobs (genetics, doctor, robotics) and science was one.

**Comment by Miauw62** [comment]
wait, we actually implemented our horrible, broken, horrible. horrible, RD system *ourselves*?

**Comment by pudl** [comment]
@Miauw62 It was added around July 2013, that's all I know. And it wasn't a port.

**Comment by Incoming5643** [comment]
Science being "feature creep: the job" doesn't really invalidate my point

**Comment by Fox-McCloud** [comment]
@Miauw62 

Yes. Originally, medbay was Viro+genetics+robotics+doctor with the CMO/Chief Surgeon heading it all up.

RD headed up toxins+Chemistry+artifact/anomally research.

That said, the RD had access to every single department in medbay (especially robotics and genetics).

**Comment by Iamgoofball** [comment]
Yeah, R&D and Medbay were butt buddies back then.

**Comment by Miauw62** [comment]
i wasnt trying to invalidate a point, just expressing surprise at the fact that its not goonshit

**Comment by Fox-McCloud** [comment]
@Miauw62 

Neither was I; just trying to provide a bit of SS13 history/info =3

**Comment by Iamgoofball** [comment]
nope miauw R&D is 100% pure mport tg shitcode

**Comment by Steelpoint** [comment]
Virology, the map, is built assuming one person is in there.

Not to mention I would miss the peace of virology.

I'm not a fan of this proposal

**Comment by pudl** [comment]
Speak for your own map. Metastation is built for two. It would be easy to expand.

**Comment by Steelpoint** [comment]
More does not mean better.

I prefer Virology being a one man job and I prefer it being kept isolated and kept so only three people by default can get in there, that being the Viro, CMO and Captain.

Genetics warrents multiple job positions simply to increase the odds of there being more people with knowledge of cloning and genetics to help those being cloned, Virology really gains nothing from having more people aside from RNG maybe giving one Viro a better run of luck than the other.

**Comment by tuypo1** [comment]
@Iamgoofball 
>Friendly reminder that isn't relevant to the discussion at hand.
how is it in any way not relevant

**Comment by Iamgoofball** [comment]
because we're not talking about lowpop access

**Comment by Lumipharon** [comment]
It's relevent depending on the reason behind this PR.

While it wasn't said in the OP, generally the argument for merging the jobs is ensure there are people to do every job in a given round.

If it's low pop, all of med shares access (except for maybe viro, not sure). So it's not an issue at lowpop.
At high pop, you'll be hard pressed to find a round where you don't have a person in all of the med jobs, so short of people going awol/dying, it's again, not an issue.

**Pull request closed without merging**
