### PR TITLE
Fixes being able to scribe the nar-sie rune in space

### PR DESCRIPTION
**Pull request by ChangelingRain**
mmmmmmmmmmmmmm

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this has to be the third time we've fixed this

**Comment by coiax** [comment]
@ChangelingRain also, if you're thinking of a recent round where the cultists scribed the rune in the middle of space with energy shields for walls, I'm not sure if this will cover that case.

See, they built their structure in the middle of the supermatter crater, which would still be covered in old area, despite the lack of structure.

**Comment by BeeSting12** [comment]
@coiax The message for the rune being placed said they were in space.

**Comment by ToadStar** [comment]
Yep, it was like, 8-9 tiles off from where atmos' crater was, so. Nobody would've been able to guess it.

**Pull request merged**
