### PR TITLE
Adds  5 unstable mutagen bottles to a hacked NutriMax botany vendor

### PR DESCRIPTION
**Pull request by MisterTikva**
:cl:
add: Nanotrasen Security Division reports that some bottles with strange green liquid have been contrabanded to the botany vendomat
/:cl:

Enough to kickstart botany if you know what you are doing, but not enough to run longer than a few minutes if you don't.
Because messing with chemists who are too busy making some ClF3/incompetent/braindead is the WORST part of botany and only causes general frustration.

### CODE REVIEW

**Comment by Chocobro** [comment]
:+1:
although i'd personally prefer 3 instead of 5

**Comment by MisterTikva** [comment]
@Chocobro 5 is just to ensure that RNGesus doesn't own you in the ass with blumpkins mutation.

**Comment by Chocobro** [comment]
make game hard imo
anyway i'm fine with this oranges merge he

**Comment by TehZombehz** [comment]
This is nice, but it still kinda reduces player interaction. Isn't that something that we make a big deal about: player interaction? Don't get me wrong, though, I like it.

**Comment by Arianya** [comment]
Reduces inter-department interaction and reasons to leave your department in order to get chemicals/get access to chemistry/get a chem dispenser board from R&D/other resolution. :-1:

**Comment by MisterTikva** [comment]
@TehZombehz Player interaction is awesome, but only when both parties want to interact. Around 4 out 5 times i have to get mutagen myself because there are no chemists or they just flat out ignore you.

**Comment by Arianya** [comment]
@MisterTikva Remember that the other point of botany not having everything they need within their department is that it forces them to leave their department, exposing them to crew with no access. This is down right essential for antag roles, such as tator target, cult sacrifice target, etc.

Just another factor as to why a department shouldn't have everything they want available.

**Comment by MisterTikva** [comment]
@Arianya You still need to get out to grab a multitool, insulated gloves, you need to distribute your plants somehow, botany is one of the easiest departments to break into(you have to go through 1 glass table and a non-reinforced window). Also most chemists are just assholes and will kick you out even if you have chem access. And chemistry itself is quite self sustained within medbay plus they have shutters all around, doesn't  seem fair for two departments with almost equal potential.

**Comment by FantasticFwoosh** [comment]
**Not required unfortunately**, you can grow mutagen naturally if you know how.

> Hack the machine for glowshroom, take the stats (because good stats) & grow more, meanwhile grow gene edited pumpkins with production 1.

> Apply left4zed mutation chemical on the pumpkins and wait, collect harvests until it turns into blumpkins with atleast yield 1 (variable because mutations)

> Add radium & phosphorus to your new blumpkin seed & edit the stats to be a new plant (also remove the nutriment & ammonia from the blumpkin for more efficient harvest) the units will combine without 'seperated chemicals' trait on harvest and you can just put through a grinder for free scaling mutagen.

Easy infinite mutagen, made much easier by gaia trays for no upkeep.

**Comment by Supermichael777** [comment]
an hour into the round

**Comment by MisterTikva** [comment]
@FantasticFwoosh It is all nice, but then it just takes 2000 ticks more than using mutagen even if RNGesus is generous to you and doesn't make your yield 0 in the process. Why not remove some stupid and not enjoyable RNG if it doesn't even affect balance at this point?

**Comment by FantasticFwoosh** [comment]
@Supermichael777 if you know what you're doing you can do it MUCH sooner, hydroponics is not a rushed job anyway.

@MisterTikva its also infinite mutagen, and can be done twice as fast by just getting mutagen from chemistry to mutate the blumpkins, set the new plant to be base gene disk potency 50, 10 yield and production 1 and it'll make (with robust harvest) 300+ units every 3 and a half minutes in harvest thanks to production 1.

> With mutagen pre-supplied from chemistry, and blumpkin created you can just put the disks onto a plant with better maturation time to grow & then harvest that instead. Only waiting required is plant growing, which is usually no more than 5-7 minutes.

Recently rebalance of blumpkin's got merged so now its a perfect amount without the excess chlorine.

**Comment by MisterTikva** [comment]
@FantasticFwoosh  I'm talking about exaclty getting blumpkins with that added mutagen, because half of the time chemists are  just assholes or ignore you.

**Comment by FantasticFwoosh** [comment]
@MisterTikva read my original content please, left4zed can mutate INTO plants, the RNG isnt as bad as you make out to be, especially with blumpkins being the ONLY thing pumpkins mutate into. Mutations via chemicals are a part of how hydroponics works when set to anything but robust harvest (which stops mutations from all other sources)

> based off production time which is VERY quick with production 1, left4zed fires and with RNG you can get blumpkins mutagen free on the first go or the 10th go which likely if the production stat survives (or if you have multiple pumpkins, just keep rolling.) 

> left 4 zed mutates twice every time the plant is ready to harvest, leave it on pumpkins gene edited with production 1 and wait & harvest to trigger multiple mutations in quick succession.

With or without mutagen is not a issue because when it is done you will never have to rely on chemists ever again, same as the PR suggestion of just giving 5 bottles (150 units) of mutagen to botanists anyway to rush blumpkins and do the infinite mutagen method.

**Comment by MisterTikva** [comment]
@FantasticFwoosh I just tried that left4zed method, for the first 3 times production speed remained 1 then it got to 3, then to 4, then to 6. That is the RNG i'm talking about. At this point it is easier to bore that chemist to death and get your mutagen.

**Comment by FantasticFwoosh** [comment]
@MisterTikva The trick is that if it spirals too wildly, to dig up with a spade and replant a new plant via gene editing the stats back to optimal levels or having lots of the seeds pre-supplied.

You got unlucky.

**Comment by MisterTikva** [comment]
@FantasticFwoosh Then you are just outright wasting even more time. That is why i am suggesting to add that mutagen, making everybody happier. I will make a large scale test and come back to you.

**Comment by MisterTikva** [comment]
So i got 3 blumpkins from 10 trays in the time it took glowshroom to grow and production speed went to shit on all of them instantly. Kinda bad IMO.

**Comment by FantasticFwoosh** [comment]
Use the gene editor to just set it back to  production 1, thats the point.

Speed mutate to blumpkin and extract seeds - genetically alter in the additional components and reset stats then plant for free mutagen.

**Comment by PKPenguin321** [comment]
player interaction reduction meme, please cease

**Comment by jughu** [comment]
Change into radium

**Comment by jughu** [comment]
Radium: Same chance to mutate plants, but you need 10 units, they also damage the plant and add toxicity.

**Comment by optimumtact** [comment]
Reduces inter department interaction.

please stop making these pr's

**Pull request closed without merging**
