### PR TITLE
[s] Improves the Clown for April Fools

### PR DESCRIPTION
**Pull request by Iamgoofball**
honk

### CODE REVIEW

**Comment by GunHog** [comment]
Make them spawn with a few bananium sheets! They can pool them to build HONKS!

**Comment by Kromgar** [comment]
This is just stupid

**Comment by Niknakflak** [comment]
it's stuff like this that runs the day and meme into the ground into not being fun anymore

**Comment by Iamgoofball** [comment]
@Niknakflak this is the most april fools PR out there

just make more people who make jokes and pranks

**Pull request closed without merging**
