### PR TITLE
Adds NVG Mesons

### PR DESCRIPTION
**Pull request by GunHog**
Adds Night Vision Optical Mesons Scanners to R&D.
- Requires Materials 5, Electromagnetic Spectrum 5, and  Engineering 4.
- Made using Uranium and Plasma (Combining the costs of mesons and NVG)
- Sprites by @Mandurrrh! <b>They are animated, but I am too lazy to make a gif</b>
- Also adds inhands for standard mesons.

*Note: I was originally going to add a negative flash protection (welding with them REALLY hurts) to all night vision equipment, but I will save it for a PR after this one.

screenshot 2015-02-19 14 57 26

### CODE REVIEW

**Comment by TheVekter** [comment]
:+1:. Any chance you could make mining borgs start with these?

**Comment by GunHog** [comment]
I feel that I would need head-coder approval for such a thing. I support it myself, but I am likely to get pushback as it was not too recently removed from them.

**Comment by TheVekter** [comment]
I would like at least a mesons for them that doesn't have to be constantly equipped. They're already super strained on modules for mining as it is.

**Comment by WJohn** [comment]
Note that the difference between these and regular mesons is that regular mesons still won't reveal what's past a few tiles, even if "darkness" isn't shown.

**Comment by paprka** [comment]
Regular mesons don't reveal past the tile the mob is on, period.

**Comment by WJohn** [comment]
Though the lighting they bring with them helps.

**Comment by phil235** [comment]
Both the meson and NVGmeson have no inhand icon. change item_state to "glasses" for both, or add new sprites.

**Comment by Mandurrrh** [comment]
Yay!! Sorry for the wait lol

**Pull request merged**
