### PR TITLE
Fixes mapped in closed firelocks to actually start closed

### LINKED ISSUE #64524: Mapped in Closed Firelocks are Inconsistent
## Round ID:
Tested locally

## Reproduction:

While trying to figure out why the hell Charlie Station (old station) has so many active turfs, I've ran into another issue (so I'm closing that other report in favor of this; see for #64426 more info).

For whatever reason, mapped in firelocks seem to just be incredibly inconsistent. Old Station has 16 mapped in firelocks that are closed, but only 4 are ever active. They ALL generate active turfs despite having the correct aired turfs. As for the ones going directly to space, they create active turfs ON the firelock turf and the turf adjacent (airless). This is not true for the 10 firelocks closed that don't border space, they generate active turfs ON their turf.

Through testing, putting airless turfs under the firelocks (or adjacent) opens the firelocks, or doesn't Whatevers going on is incredibly inconsistent and rather annoying, especially for future mappers/adminbus events, which would require an airlock to be closed.

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Fixes #64524 
All this does is make the mapped in closed firelocks STAY closed upon the game booting. Currently, on live, they open up as soon as the world initializes. 

## Why It's Good For The Game
Mappers can be happy, also consistency is good.

## Changelog

:cl:
fix: Mapped in firelocks that are closed will STAY closed.
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Got something to add; Will do tomorrow

Thanks @Timberpoes and Zxaber

**Comment by Jolly-66** [comment]
nvm i had time

**Comment by Jolly-66** [comment]
I PROMISE this compiles and works.

This was before I made #64630

**Comment by LemonInTheDark** [comment]
Pull master and update the pr

**Comment by Jolly-66** [comment]
> Pull master and update the pr

Will do the next time I'm on my PC

**Pull request merged**
