### PR TITLE
Adds instagib mode to CTF

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
rscadd: Capture the flag now features a high speed instagib mode, with guns courtesy of MMMiracles.
/:cl:

The guns have infinite ammo and kill you in one hit. Everyone moves at super speed.

Admins can proc call instagib_mode() on one of the machines to set all active machines to have the instagib gear/shorter respawn.

Thanks for the guns @MMMiracles

### CODE REVIEW

**Comment by Shapsy** [comment]
But does it actually gib you?

**Comment by KorPhaeron** [comment]
Yes

**Comment by Shapsy** [comment]
Amazing

**Comment by StormAGeddonz** [comment]
:thumbsup: :thumbsup: :thumbsup: :thumbsup: :thumbsup: :thumbsup: :thumbsup:

**Comment by Chocobro** [comment]
we UT99 now boys

**Pull request merged**
