### PR TITLE
New Holopad Sprite!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
I'm on a roll that is not going to stop any time soon!

This PR resprites holopads, much like how the title says!
image
holopadringing
holopad
image

Due to the nature of this object, I can't exactly screenshot it or record it in action live, but I have tested it privately and it works like a charm!

## Why It's Good For The Game
Another extremely old and crusty sprite from the r4407 era bites the dust! What's not to love?

## Changelog

:cl: PositiveEntropy
imageadd: Holopads are now shinier and more elegant!
/:cl:

### CODE REVIEW

**Review by Twaticus — APPROVED** [review]

**Comment by Farquaar** [comment]
Considering how common these are around the station, this is an upgrade that we'll see a lot of.

**Comment by Likteer** [comment]
You can record it in action with holodisks but I doubt i'ts necessary. 
Is the bug where the screwed open sprite (last one in the screenshots) flashes, then reverts to regular, still a thing?

**Comment by Imaginos16** [comment]
> You can record it in action with holodisks but I doubt i'ts necessary.
> Is the bug where the screwed open sprite (last one in the screenshots) flashes, then reverts to regular, still a thing?

When I tested it didnt happen, I'll test later today to make sure its not a fluke

**Comment by Imaginos16** [comment]
> You can record it in action with holodisks but I doubt i'ts necessary. Is the bug where the screwed open sprite (last one in the screenshots) flashes, then reverts to regular, still a thing?

Tested recently, seems the issue you mentioned does still happen in this version. I wonder what causes it...

**Pull request merged**
