### PR TITLE
New Muzzle Flash + Temperature gun Baking beam change

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
Now there are new muzzle flash sprites for the guns. There are 3 types:

**BALLISTICS**

https://github.com/tgstation/tgstation/assets/42353186/82d7b285-fcf0-4780-8479-143691641e0a

**BLUE**

https://github.com/tgstation/tgstation/assets/42353186/331c926d-8556-4715-ab61-9a4998dd93d2

**RED**

https://github.com/tgstation/tgstation/assets/42353186/c814646d-6d56-4426-bde7-b7a7a06caa39

Also, now temperature gun "BAKE" mode beams have different sprites from the "FREEZE" beams:

https://github.com/tgstation/tgstation/assets/42353186/c78363ac-ad04-4534-9323-dc13ba017823
## Why It's Good For The Game

Muzzle flashes were one of the most oldest effect sprites in the base, and are rather bad and bland looking.
This makes them more good-looking. Also gives variety, previously there only been Ballistic and Energy one, and they weren't even different.

Temperature gun "BAKE" mode beam having a different colour will help distinguish what the hell you're being shot with.
## Changelog
:cl:
image: Muzzle flashes got a new sprite, each direction included!
image: Temperature Gun "BAKE" beams are now lava colored
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Good work as always Diasyl.

**Comment by mc-oofert** [comment]
i think the ballistics muzzle flash is less detailed than the prior one

**Comment by DrDiasyl** [comment]
> i think the ballistics muzzle flash is less detailed than the prior one

The previous muzzle was a circle which slightly expanded, lacking variety, but this shape has more detail.

**Comment by mc-oofert** [comment]
wait am i misremembering what sprites we had for the muzzle flash i need to check hold on

**Comment by mc-oofert** [comment]
image
these

**Comment by DrDiasyl** [comment]
> image these

They seem less detailed to me. But you can have your opinions.

**Review by Wallemations — APPROVED** [review]
I like it

**Pull request merged**
