### PR TITLE
Prevent people from setting FILE_DIR

### PR DESCRIPTION
**Pull request by ghost**
This makes it easier, and prevents new people from accidently setting FILE_DIR

### CODE REVIEW

**Comment by Chnkr** [comment]
@MrPerson @MrStonedOne

**Comment by MrPerson** [comment]
I tried doing something like this by commenting out the FILE_DIR stuff in the .dme but byond didn't want to play ball. I made a fr on the byond forums.

I didn't want to do this under the assumption it would cause conflicts with people pulling but it should work too.

**Comment by Chnkr** [comment]
https://github.com/Baystation12/Baystation12 uses the same method to prevent this, this should resolve a lot of the problems.

**Comment by Razharas** [comment]
Is this legit?

**Comment by Razharas** [comment]
@Chnkr

**Comment by Chnkr** [comment]
This is legit @Razharas

**Comment by Shadowlight213** [comment]
This is causing so many goddamn issues as byond is using this file for internal stuff and its keeping track of this file when trying to commit. Causing more problems than its worth.

**Pull request merged**
