### PR TITLE
Lavaland Syndicate Base fusion

### PR DESCRIPTION
**Pull request by Naloacisamazing**
##  About The Pull Request

The Syndicate base on lavaland has been for learning roles yet their was no way to actually do fusion in current set up yet its one of the harder things to learn and its normally taken up by an atmos tech whos already working on it.

image

This adds a co2 area to actually get started and a few freezers to help.
## Why It's Good For The Game

Allows people to learn a pretty hard aspect of the game without being a bother to anyone else, or having another atmos tech just take over.

## Changelog
:cl:
add: Added a co2 area to allow fusion to be done.
add: few freezers and pipes to help
del: Removed old things
/:cl:

myfirsttimeusinggithub and themajorityofthisstuffdontbullypls
although please do shout at me if I fucked it all up.

### CODE REVIEW

**Comment by wesoda25** [comment]
yes yes yes good first pr

**Comment by FloranOtten** [comment]
This also seems to fix the atmospherics in general, as up until now the plasma tank just did not work

**Comment by imsxz** [comment]
shit

**Comment by HomocidlePancakes** [comment]
One freezer blocks the other one.

**Comment by ErwinSnowden** [comment]
**fucking based**

give the lavaland syndies radiation collector boards to make nuclear energy collectors if they want to, somewhere in the storage too, it'll be epic, also give them more radsuits cause half of the base will be encompassed in radiation unless plastitanium blocks rads?

**Comment by Detective-Google** [comment]
Really good add, syndie lavaland is great for learning new things, and this is a great addition to that! also means that atmos techs just doing fusion memes don't HAVE to create super dangerous fusion canisters on station, and won't get uber-bwoinked if they accidentally fuck it up, big 👍

**Comment by Naloacisamazing** [comment]
image
added some rad collectors to allow people to see the POWER of fusion.

image

Moved the computer for plasma up one to allow better access to the freezers. 

Three total rad suits incase someone fucks everything up and one syndicate hard-suit incase someone wants to set up a heat pipe inside the burner.

**Comment by Naloacisamazing** [comment]
@ErwinSnowden I tested doing fusion a few times and it didnt really seem to be a problem unless you where running around with the canister spreading rads everywhere.

**Comment by TheSilverNuke** [comment]
Very cool, give it to a tot to take to the station, along with an RPD for fun times.

**Comment by Ty-the-Smonk** [comment]
Cant wait for someone to contact a syndie boy on lavaland and release autism fusion everywhere

**Pull request merged**
