### PR TITLE
Removes capitalism and communism golems [the sun sets on freedom] [fall of the iron curtain]

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Removes commie and cappy golems, and all connected parts and features.

## Why It's Good For The Game

You're downloading 5 mb of capitalist and communist songs and talk sounds every time you log into a server, which makes it take much longer to actually join the game. While this was a good meme and became even better when cappy golems would fight the communist ones, they are:

1. Really really underused for what they are
2. Really really boring and simple without all the special sounds
3. Really really not worth keeping gutted

## Changelog
:cl:
del: Capitalism (golem) and Communism (golem) are dead.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Species change approved by oranges, https://discordapp.com/channels/326822144233439242/326831214667235328/7704537867114250

**Comment by wesoda25** [comment]
Not even adding fascist golems to fill the void??? 😡:-1:

**Comment by Losenis** [comment]
> fascist golems
Shitsec is already a thing

**Comment by Time-Green** [comment]
Farewell, my child

**Comment by Farquaar** [comment]
If the problem is the size of the audio files, why not just remove the songs?

**Comment by Time-Green** [comment]
They're slaughtering your child also @fluffe9911

**Review by 81Denton — APPROVED** [review]
Yeah, these are good for aprils fools at best and still low quality content

**Comment by ATH1909** [comment]
Is there any way to save space with the songs? What if we used, like, a 144p version of them, or even a MIDI? An incredibly shitty midi of the Soviet anthem (and that song that plays for capitalist golems) could be even funnier than what we had before, and we could probably hijack instrument code to do it.

Like, you'd just write a pre-written midi in a file somewhere and have whatever system instruments use to produce the sounds they make run with the "sheet music"(/whatever we program instruments with) read the data from that file. Hell, you don't even have to do anything fancy with restricting the sound from the phantom instrument to only being hearable by a single golem, as multiple golems just cruising around with unsynced midis (or even synced versions, if you do some coding magic) of the Soviet anthem just emanating from them sounds amazing.

**Comment by EOBGames** [comment]
Golems are quite possibly one of our most egregious examples of bloat, and these two in particular are some of the least interesting that are available. Perhaps after this an eye could be cast to the rest of the golem varieties, and see if there's some fat that could be trimmed there too?

**Comment by 81Denton** [comment]
@EOBGames Most are pretty unremarkable, but I like the general theme of "stick random material in a golem shell, receive random weird golem". Kind of like how we have stretchy plastic golems and snow golems that can create snowballs.
I'd rather make the bland, generic ones like titanium/silver/gold more interesting, but that's just my opinion and I have no ideas for a rework (yet).

**Comment by EOBGames** [comment]
> @EOBGames Most are pretty unremarkable, but I like the general theme of "stick random material in a golem shell, receive random weird golem". Kind of like how we have stretchy plastic golems and snow golems that can create snowballs.
> I'd rather make the bland, generic ones like titanium/silver/gold more interesting, but that's just my opinion and I have no ideas for a rework (yet).

That's definitely also an option. Just anything other than the dozen near identical material golems we have clogging up the admin list and being boring as fuck in terms of mechanics and gameplay.

**Comment by brotherbeyondd** [comment]
the arm that slew communism

**Comment by cacogen** [comment]
Better to keep the golem types and remove the sounds than remove them outright. Also converting the music to a .midi or whatever is a good idea

**Comment by tralezab** [comment]
Farquaar and Cacogen, I did look at just removing the sounds and the golem becomes pretty insanely bland. It's just my opinion that it wasn't worth it

**Review by Rohesie — APPROVED** [review]

**Comment by fluffe9911** [comment]
very sad

**Pull request merged**
