### PR TITLE
Gang Pen Is now Stealthy

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
balance: The Gang pen is now stealthy. Stab away!
/:cl:

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=9146#p264836

You can obviously still see the pen, but it won't be as easy of a tell as a big red "OH THIS GUY BESIDE ME IS A GANG HEAD" notification.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Won't matter much because security has a low cost, 0 downside way to simultaneously check for and provide immunity to conversion.

So personal stealth wont help if sec sees a single spray tag and implants the whole crew.

**Comment by KorPhaeron** [comment]
Probably a positive change though

**Comment by ExcessiveUseOfCobblestone** [comment]
Agreed, this is less so about combating the boys in ~~blue~~ red as it is going against the guys that heads  don't have a tell for prior to attempting to convert: Other gang members.

**Comment by PKPenguin321** [comment]
Does this actually remove the tiny prick message?

**Comment by Jordie0608** [comment]
Yes https://github.com/tgstation/tgstation/blob/master/code/modules/paperwork/pen.dm#L93

**Comment by PKPenguin321** [comment]
Neat

**Pull request merged**
