### PR TITLE
Modern violence/fix#19596

### LINKED ISSUE #19596: Photocopier not copying correctly and eating the original
Currently very hard to properly play HoP, if you copy a paper with writing on it, the copied paper will use the blank sprite, not the one with lines on it (The text itself is copied properly, though, just the sprite thats wrong).

Also, the photocopier doesn't give back the original paper when pressing "eject paper". It seems to eat it. This is too close to real life and potentially triggering.

### PR DESCRIPTION
**Pull request by ModernViolence**
:cl: Fix #19596 
fix: Fixed taking originals out of photocopier.
fix: Fixed sprite for new copies of not empty papers.
:cl:

Testing done:
1. Copying papers, photos, employment contracts works properly.
*Copies of employment contracts have correct path - _/obj/item/weapon/paper
/contract/employment_ and correct contents.
2. Taking out originals works properly for humans and silicons (for silicons the original must not be put in their hands).
3. Insertion of papers, photos, employment contracts.

### CODE REVIEW

**Comment by optimumtact** [comment]
Instead of using usr, update the do_insertion call on line 258 to pass through the user variable, look like that was just an oversight.

**Comment by ModernViolence** [comment]
Is there any way to fix remove_photocopy like that?
I don't know if /obj/machinery/photocopier/Topic(href, href_list) has any user variable to pass into remove_photocopy.

**Comment by optimumtact** [comment]
in that case you can do this in the topic call

    remove_photocopy(copy, usr)
    remove_photocopy(photocopy, usr)
    ... etc

and update the remove_photocopy function to be

    remove_photocopy(obj/item/O, mob/user)

it's not ideal but we try to avoid the use of the usr var outside of topic calls since it's not clear to people where it set or comes from.

**Comment by ModernViolence** [comment]
Force pushed changes and done the same testing.

**Comment by optimumtact** [comment]
Should be good to go once the 24 hour review period is over, thanks.

**Comment by lordpidey** [comment]
Could you also test this with employment contracts?

**Comment by ModernViolence** [comment]
Where can I get employment contracts? I cannot spawn them for reasons unknown (through using /obj/item/weapon/paper/contract/employment and its child nodes).
However, since this fix works for photos and paper AND I've updatet all the usages of do_insertion and remove_photocopy...I suppose it works for contracts, too.

**Comment by lordpidey** [comment]
They should be in the filing cabinet in the lawyer's office.

Please also check the path of the copied contracts, make sure they're actually contracts, not just paper with the contract text on it.

**Comment by ModernViolence** [comment]
Copies of employment contracts have path _/obj/item/weapon/paper
/contract/employment_
Contracts are inserted/removed from copier properly.

**Comment by optimumtact** [comment]
LGTM

**Pull request merged**
