### PR TITLE
The chef is also a cook

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
:cl: Naksu
add: The chef is now trained for working under siege
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
understanding the basics of culinary quarters combat.

**Comment by feemjmeem** [comment]
this is absolutely necessary

**Comment by Spaceinaba** [comment]
upvoted, liked, saved, shared, and subscribed

**Comment by Iamgoofball** [comment]
With the amount of assistants jacking his shit this is needed

**Comment by Xhuis** [comment]
I play chef pretty often and usually knife-fu  shutterslamming, and tableshoving is enough to keep the tide back, but this is funny so I don't mind.

**Comment by arsserpentarium** [comment]
cook martial art needs instant neck grab.To help shove some fucker on spikes or gibber.

**Comment by davethwave** [comment]
This sounds like fun

**Comment by outbools** [comment]
[i am the cook](https://www.youtube.com/watch?v=aJozK6lsQHE)

**Comment by Iamgoofball** [comment]
censorship
https://www.youtube.com/watch?v=aJozK6lsQHE
https://file.house/__XE.png

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
