### PR TITLE
Fixes the new office chair sprites

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Title.

## Why It's Good For The Game
Yeah this ain't it chief.

1. Fixes the state names
2. Fixes "officechair_white" (dark) having a light side state
image

## Changelog

:cl: Jolly
fix: Light office chairs and Dark office chair colors are, now actually reflective of the name.
fix: Left/Right office chairs should be symmetrical and no longer be one pixel off when flipped.
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Honestly quite incredible

**Comment by VladinXXV** [comment]
matter of perspective

**Comment by OneAsianTortoise** [comment]
same colour

**Comment by Helg2** [comment]
image

**Pull request merged**
