### PR TITLE
Fixes Some Incredulously Fucked Up Recycler Behavior

### LINKED ISSUE #57969: Clothes on character (sprites) stay on even if recycler deletes them
## Testmerges:
The following pull requests are currently test merged:
#57877: 'Sec officers now only get PDA'd if the new member is of the same department' by Mothblocks at commit 592b2c028f

## Reproduction: 
I jumped into disposals and there was a emagged recycler, every item was destroyed but clothing on the character stayed (there wasn't actually any clothing), i also retained the security hud from sechuds.

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there!

Did you know that if you toss someone into a recycled emagger, that we delete _all_ of that mob's contents? You probably didn't because this shit is broken broken. Like, ow.

image

Literally nothing suggested that! The uniform, pointing to nullspace, was still associated to the mob! After four hours of stepping through a debugger, I figured out that it was behavior introduced in #48711.

That's because we manually moved an item to nullspace, which caused a _slew_ of odd behavior in the Destroy chain for `obj/item` since it moves it to nullspace at a very specific point in time and makes all of it's assumptions on when you move the thing to nullspace. If it's in nullspace before you call qdel, you would shit out the ass with hanging references stuck on the mob (like `w_uniform` pointing to something in nullspace, like the image above).

I'm not sure if we were moving stuff to nullspace at the time of that linked PR (hence the confusion between the PR author and ninjanomnom's suggestion), but this shit has likely been broken since 2020.

All fixed now, though.

## Why It's Good For The Game

image

Fixes #57969.

We recycle and deleted literally all of the contents on the mob, yet absolutely nothing reflected that we did that. Even if you were to strip them, you'd strip nothing because it was qdeleted and in nullspace. Silly stuff, and now it's fixed.

Here's a snippet of the unit test running on current master:

image

## Changelog

:cl:
fix: When a human went through an emagged recycler, they would have literally everything on them chewed up in the recycler. However, they still appeared to have all of their stuff on them due to some faulty code. When you now punt that tider into the chewer-of-death, they should now appropriately reflect that all of their clothes have been deleted.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
draft because i think i'll write a unit test because i was fuming for four hours straight trying to figure this out

**Comment by san7890** [comment]
> Fixes #57969?

yes

**Comment by msgerbs** [comment]
Dare I ask what happens if a mob that's wearing a mobholder goes through the recycler?

**Comment by san7890** [comment]
> Dare I ask what happens if a mob that's wearing a mobholder goes through the recycler?

What _should_ happen is that for every single item (even those in a backpack) `living_detected` flips to true and we handle the mob properly from there.

**Pull request merged**
