### PR TITLE
Changes brass filament sprite

### PR DESCRIPTION
**Pull request by DaedalusGame**
Purges ~~all untruths~~ licensed assets that we can't use.

### CODE REVIEW

**Comment by raymoo** [comment]
Don't you mean unlicensed?

**Comment by DaedalusGame** [comment]
ok i admit it's a meme license

**Comment by uraniummeltdown** [comment]
old sprite is better :-1:

**Comment by DaedalusGame** [comment]
shame we can't use it huh

**Comment by Thunder12345** [comment]
Shame it's stolen from Immersive Engineering wires

**Comment by WJohn** [comment]
New sprite looks fine.

**Review by WJohn — APPROVED** [review]

**Comment by Potato-Masher** [comment]
I always thought it was hilarious that they had the Immersive Engineering wire texture.

**Comment by Xhuis** [comment]
Um, actually, brass filaments aren't used anywhere. This was a leftover icon from a concept I scrapped early on in the defenses patch. You can safely remove that.

**Comment by DaedalusGame** [comment]
well i already made a replacement, now we just need to add a concept

**Comment by raymoo** [comment]
@DaedalusGame Time for somebody (not me) to port IE to tgstation.

**Comment by Buggy123** [comment]
>Immersive Engineering

Time to spend 30 minutes building a huge, awesome looking machine that does the work of a single 1-tile machine but at half the speed!

(I love IE but I swear there's no point using outside of specially designed packs, aside from aesthetics.)

**Comment by raymoo** [comment]
@Buggy123 Or if you don't play with a huge pack with multiple overlapping tech mods every time.

**Comment by Buggy123** [comment]
Fair enough, I wanna play something really organized like PO2 but I don't want to go back that many versions, so i'm waiting until PO3 comes out.

**Comment by raymoo** [comment]
I haven't played too much with tech mods recently except with rotarycraft (and related memeka mods)

**Comment by nicbn** [comment]
## Welcome to /tg/station GitHub

GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside millions of other developers.

Things /tg/station GitHub are:
* An open community for pull requests and issues, and discussion about them.

Things /tg/station GitHub aren't:
* A Minecraft mods forum

**Comment by DaedalusGame** [comment]
Blame Xhuis for that

**Comment by Buggy123** [comment]
Rude

**Comment by francinum** [comment]
@Buggy123 because fuck future cube.

**Pull request merged**
