### PR TITLE
Penetrator rounds for sniper rifles

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
They do a bit less damage than the normal rounds, and they don't stun, but they can pass through walls/mobs like an xray beam.

@RemieRichards do you have objections this since its your thing

This could serve as an alternate AI kill without having to buy a syndiborg

:cl: Kor
rscadd: Nuke Ops can now purchase penetrator rounds for their sniper rifles.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
They should have a limit to how many walls they can punch through - just flying through 50 r-walls seems a bit silly. Also, do they pass through mobs (ie: hit 50 guys lined up) like xrays do?

You should also call them TURBO penetrator rounds, because vindicare.

**Comment by KorPhaeron** [comment]
I mean its effectively 100% armour pen cause nothing has above 50 bullet resist but DS but sure

**Comment by Lumipharon** [comment]
Oh, is bullet proof armour still nerfed to shit?

**Comment by KorPhaeron** [comment]
Oh I forgot bulletproof is like 80 again

**Comment by WJohn** [comment]
Can we please rename this thing to bluespace or ghost round or something? Penetrator sounds like something with very high piercing that could go through people, not through walls.

**Comment by RemieRichards** [comment]
@WJohn "...Can pierce walls and multiple enemies."
from the description of the ammo.

**Comment by WJohn** [comment]
Yeah, the description is accurate of what it does, to me though the name doesn't quite fit with what it's able to do.

**Comment by KorPhaeron** [comment]
It penetrates things

**Comment by RemieRichards** [comment]
Your complaint is that it sounds like it could go through people, IT CAN GO THROUGH PEOPLE.
and as Kor says, it Penetrates things, the name is valid.

**Comment by Bawhoppen** [comment]
Make it so you can't use the rifle with a silencer on if you use this kind?

**Comment by optimumtact** [comment]
themeatically naming it related to bluespace fits with the other bluespace equipment that works through walls and solid objects.

**Comment by KorPhaeron** [comment]
Thmatically syndies steal bluespace though it wouldn't make sense for them to have even better bluespace tech than nanotrasen

**Comment by RemieRichards** [comment]
@KorPhaeron Syndies stole Cyborg tech too and Syndiborgs are pretty good.

**Comment by Lancer411** [comment]
What about penetrating mech hull and killing killing mech operator?

**Comment by KorPhaeron** [comment]
@Lancer411 

Would require a rewrite of how hitting mechs works (to take into account armour pen and forcedodge projectiles) and is outside the scope of this PR. Would be whole other balance discussion as well

**Comment by Steelpoint** [comment]
Note for Bulletproof armour.

The helmet only has whatever the nerfed values was (30 to 40), so just aim for the head like everyone already does.

**Comment by Iamgoofball** [comment]
Rename it to Farsight Rounds and/or add the Farsight XR-20 to the game with these rounds

**Comment by KorPhaeron** [comment]
I aim for the chest for superior knockdown

**Comment by tkdrg** [comment]
I'm a bit unsure about the balance of this, but it's worth a shot, I suppose. If it turns out to be imba we can always rebalance it.

**Pull request merged**
