### PR TITLE
Buffs RCD Disable Malfunction ability

### PR DESCRIPTION
**Pull request by GunHog**
- RCDs now <b>EXPLODE!</b> (Minor explosion, with one-tile flash/flame)
- Halfed cost to 25 processing power
- Can now be used multiple times!
- 10 second cooldown (you should not need to use it often, unless Engis vend more/print from autolathe.
- Will not affect cyborg RCDs.
- Fixes the feedback message not showing.
- Fixed mech RCDs not being affected by the power.

<b>Subject to change. Provide feedback if you feel this is too strong/weak a buff.</b>

### CODE REVIEW

**Comment by SconesC** [comment]
Honestly I was hoping it would make them explode

**Comment by GunHog** [comment]
I am not against that...if I were to add such a function, how would you feel I should go about it? Explosion size, warning method, if any (loud buzzing noise perhaps?), etc

**Comment by Anonus** [comment]
Just 0/0/3 with brief delay.
Also you should buff machine overload, it's 0/0/1 and less effective than machine override.

**Comment by Jalleo** [comment]
Explosion after 5 seconds from a loud buzzing when the RCD is next used. Explosion strength triple of a welding tank.

**Comment by Cebasiz** [comment]
this is really necessary, unfortunately traitor AIs will still get punked by one engineer in 30 seconds moonwalking through the satellite but oh well

the sound of doom approaching

click click click click click click click click click click

**Comment by GunHog** [comment]
I will add explosion stuff a bit later, and check for adjustments needed.

- Malf AIs need this because they will always be acting alone (Cyborgs are to be considered one with their AI), and are the primary focus of the round.
- Traitor AIs can work with other traitors with the power of <b>friendship</b> gained through the use of the Syndicate channel, which they get by default.
- Subverted AIs are the weakest of all, but are expected to be protected by their master(s). They are also the likely to have the most cyborgs.

**Comment by Alek2ander** [comment]
It should disable the RPD as well, because of the disposaloutlet turret blocking shenanigans.

**Comment by GunHog** [comment]
Added minor explosion to RCDs with 5 second warning!
Also made me conflict...WITH MYSELF.

**Comment by GunHog** [comment]
Should this include <b>Rapid pipe dispensers</b>? Apparently these are also used to "cheese" the AI. Thoughts?

**Comment by Jalleo** [comment]
I would since it has occured with me once or twice as a traitor or subverted AI

**Comment by GunHog** [comment]
This is still alive, needs a maintainer's opinion!

**Comment by Miauw62** [comment]
i think that ei nath should be removed or nerfed

**Comment by Jalleo** [comment]
Ya know what he means miauw also i believe miauw dosent like the reuse aspect.

**Pull request merged**
