### PR TITLE
removes conspiracy theory

### PR DESCRIPTION
**Pull request by MMMiracles**
syndicate mobs spawn with swat helmets, helmets say they have the NT-brand logo on them.

SYNDICATE = NANOTRASEN?????

### CODE REVIEW

**Comment by AlexanderUlanH** [comment]
Doesn't the sprite still have the logo?

**Comment by duncathan** [comment]
:-1: i will fight tooth and nail until this orwellian society of corruption and censorship is finally overthrown
(:+1:)

**Comment by SconesC** [comment]
swat

Kind of?

What ever happened to using that red/black version that nuke ops had back in the day

**Comment by MMMiracles** [comment]
i found the sprites for the red/black variant on the nt-station branch so I put it back in. It looks better with their gear anyway IMO.

**Comment by SconesC** [comment]
:+1: 

I miss those helmets tbh

**Comment by Cheridan** [comment]
plasma can't melt steel tiles

**Comment by KorPhaeron** [comment]
Could you give them the pressure flag while you're at it? They used to function as space helmets

**Pull request merged**
