### PR TITLE
Brings some unary devices closer to the present

### PR DESCRIPTION
**Pull request by duncathan**
The completely unused oxygen generator, cold sink, and heat sink have had their icons updated so that if someone were to make them constructable, it wouldn't take as much effort. Their connected pipes now work like virtually any other unary device.
Heat exchangers now update their color to match their node.
All of these devices are no longer dense.
screenshot 2015-06-13 02 49 49
The PR also reorganizes the atmos icons a wee bit.

### CODE REVIEW

**Comment by Jalleo** [comment]
Wait there is a way to make oxygen?

**Comment by Miauw62** [comment]
theres an unused oxygen generator machine thing that you cant make except
through admin fuckery.

**Comment by duncathan** [comment]
In a future PR I plan to make these three unary devices constructable like normal devices and add them to an admin-only RPD. Sure, the cold sink and heat sink are redundant because of freezers and heaters (which are actually just children of the cold sink/heat sink) but it'd still be nice for consistency.

**Comment by duncathan** [comment]
This is merge ready.

**Comment by AlexanderUlanH** [comment]
What's the difference between a heat sink and a freezer?

**Comment by duncathan** [comment]
Very little. Freezers are children of cold sinks.

**Pull request merged**
