### PR TITLE
Fixes #7767, Readds shuttle areas for teleporting

### LINKED ISSUE #7767: Ghost-teleport to "escape pod 1" takes you to several places that aren't pods
to name and shame, it takes you to: nukeop/syndie shuttle, white ship, escape shuttle

### LINKED ISSUE #9625: Gulag shuttle shows arrival pods
When moving on the Gulag shuttle, since it is on the same zlevel as the arrival pods(when moving), you can see the bottom of them when moving in space. (also interact with the doors as a cyborg)

### PR DESCRIPTION
**Pull request by Jordie0608**
See #9573

I got tired of tortoise not finding any diffs when pulling from master due to ?!? so here's a new pr that'll hopefully work better.

Also fixes #9625

### CODE REVIEW

**Comment by Firecage** [comment]
Will this still work effectively with the new way shuttles are handled?

**Comment by optimumtact** [comment]
code/world.dm:68:error: process_ghost_teleport_locs: undefined proc

code/modules/shuttle/shuttle.dm:173:error: area: undefined var

code/modules/shuttle/shuttle.dm:173:error: shuttle: undefined var

**Comment by Jordie0608** [comment]
Derp

@Firecage This is just for teleporting mobs, the mechanics of shuttles are unaffected.

**Comment by Firecage** [comment]
Ah, cool. Just thought that there was a specific reason for the areas being removed originally. And I thought ghosts could still teleport to the shuttle areas since it magically makes it own areas? Like the White Ship making the NT Medical Ship area in game even though it has no area on the map

**Pull request merged**
