### PR TITLE
Fixes missing icons for the janicart upgrade designs.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title.

## Why It's Good For The Game
these warnings showed up on dream deamon whenever I run tgstation locally:
```
## WARNING: design /datum/design/buffer_upgrade with icon 'icons/obj/items_and_weapons.dmi' missing state 'janicart_upgrade'
## WARNING: design /datum/design/vacuum_upgrade with icon 'icons/obj/items_and_weapons.dmi' missing state 'janicart_upgrade'
```

## Changelog
:cl:
fix: Fixed missing icons for the janicart upgrade designs.
/:cl:

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
finally, this has been noted like a month ago lol

**Comment by SmArtKar** [comment]
and thus we made gags janicart upgrades useless

**Comment by bobbahbrown** [comment]
image

image

this is the kind of untested contribution that should remove gbp

the underlying issue here is that the design system is not accounting for GAGS, the route you have taken to fix this at a surface level is, as noted above, a terrible approach as it (poorly) attempts to circumvent the GAGS system outright.

**Comment by Ghommie** [comment]
The PR mentioned above does it better.

**Pull request closed without merging**
