### PR TITLE
Plasma cutters will mine further but will go less distance in open air

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
balance: Swapped how far plasma cutter blasts go when going through rock and in open air. This means blasts through air will go 4/5 tiles, but will mine 7/10 tiles, for normal/advanced plasma cutters, respectively.
/:cl:

Effectively, they're shorter-ranged and less safe for fighting monsters, but way, way better for strip mining the entire hell world.

### CODE REVIEW

**Comment by 4dplanner** [comment]
@Repukan, would that mean this approach would work if the "air range" was the same as the KA?

**Comment by Repukan** [comment]
I'd say, if it's possible, some code like the opposite of accelerator cannon. In that you could keep the present damage but the longer it travels, the damage falls off exponentially

**Comment by ChangelingRain** [comment]
>The problem is that it surpasses the KA in terms of overall safety-range, thus making lavaland a walk in the park. Nerf the damage or amp up the fire resist megafauna and mobs in lavaland have.

This makes it only have 1/2 tiles more range than the (base) KA. Also it does brute damage, not fire.

**Comment by SgtxRootbeer** [comment]
Can we have the Ripley's plasma cutter air distance still have decent range? Mecha movement is slow and chasing megafauna isn't fun.

**Comment by ChangelingRain** [comment]
Slightly more than screen range for ripley plasma cutters, though not quite as far as the current distance.
You won't really be able to tell the difference.

**Comment by Kromgar** [comment]
why is it 4/5 tiles?

**Comment by Kromgar** [comment]
@Repukan 10/10 you thought it did fire.


Did you not realize this is based off deadspace's cutter right?

**Comment by SgtxRootbeer** [comment]
Advanced or normal plasma cutter

**Comment by Kromgar** [comment]
@SgtxRootbeer You son of a bitch now he's gonna nerf the advanced cutter now

**Comment by SgtxRootbeer** [comment]
No, I mean the 4/5 number is for the normal/advanced cutters

**Comment by Kromgar** [comment]
What's funny is repukan bitches about cutters but ignored that ka's have upgrades

**Comment by ChangelingRain** [comment]
I can also nerf those!

**Comment by kevinz000** [comment]
:^) do it

**Comment by Kromgar** [comment]
@ChangelingRain well definitely the strongest is the no pressure that makes it so kas do 40 damage indoors. Then pump in 2 damage mods to do 60 damage a shot

**Comment by jughu** [comment]
Then just make it able to add upgrades to the cutter?

**Comment by 4dplanner** [comment]
@Kromgar: Doesn't it take 2 pressure mods to make it do 40 damage?

**Comment by Kromgar** [comment]
@4dplanner Pressure mod negates the pressure disadvantage entirely im pretty sure?

**Comment by ChangelingRain** [comment]
Nope, you need two to negate the disadvantage.

**Comment by Bawhoppen** [comment]
what's with all the mining changes?

**Comment by Kromgar** [comment]
Still 50 damage a shot for infinite ammo is still insane

**Comment by ChangelingRain** [comment]
pressure mods exist basically entirely to murderbone so that's no surprise

**Comment by 4dplanner** [comment]
How are you getting 50 damage a shot?

**Comment by Dorsisdwarf** [comment]
2x pressure 1x dam+ I assume

**Comment by 4dplanner** [comment]
Pressure takes up 40/100, and damage 30, so that should be impossible

**Comment by Repukan** [comment]
Yeah you can't get anything besides 2 pressure.

How about making pressure mods cost 10 tc for traitor miners?

**Comment by Repukan** [comment]
Also you can nerf the KA but it's all around an unnecessary nerf to all roles that depend on it.

But on that topic, would it be better to make them more expensive to mass produce through RnD and make them a better commodities buy in the vendor?

**Comment by Hatfish** [comment]
@Repukan Making them more expensive isn't a bad idea if what you want to prevent is early murderbones (though I can't remember the last time I've seen a miner murderbone with pressure mods before).

**Comment by Repukan** [comment]
It's usually lost in the bombings and such, it's a potent almost non flashy weapon so it doesn't get noticed as much.

**Pull request merged**
