### PR TITLE
Nukes Hyper-Sensitive and Light Drinker, makes their effects base-kit for spacemen

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Nukes Hyper-Sensitive and Light Drinker, makes their effects base-kit for spacemen.

## Why It's Good For The Game
image (97)

Light Drink and Hyper-Sensitive are the most picked modifier quirks in the game, indicating our players heavily enjoy their effects on the gameplay experience. This frees up more design space for unique quirks like Family Heirloom and such that have unique effects rather than simply being a modifier that players enable to make boring features more fun.

## Changelog

:cl:
balance: Nukes Hyper-Sensitive and Light Drinker, makes their effects base-kit for spacemen
/:cl:

### CODE REVIEW

**Review by ZephyrTFA — APPROVED** [review]

**Comment by thatguythere03** [comment]
My brother in christ those are the free point perks

**Comment by deathrobotpunch** [comment]
so is this getting removed or are these default perks?

**Comment by Formerxboxgamer** [comment]
Making them default is trash. Nuking things because people like them is truly backwards

**Comment by anclandor** [comment]
People just use these to get points though.  Anyway what percentage of the playerbase is this actually?  Don't want to get forced to never be able to drink ever just because people like to powergame.

**Comment by Iamgoofball** [comment]
>Making them default is trash. Nuking things because people like them is truly backwards

what kind of logic is this

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]
This is stupid
People don't pick these quirks cause they like them, and you know that. I do not respect the way you are arguing here.

**Pull request closed without merging**
