### PR TITLE
Clockwork armor cannot be equipped to people if you do not serve Ratvar

### LINKED ISSUE #19740: You can check if someone is a ratvar cultist by trying to put ratvar armor on him
If it fits he's valid!

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #19740 
stop goddamn metaing shit aaaaaaaaugh I will ruin you

### CODE REVIEW

**Comment by Core0verload** [comment]
stop trying to restrict every single fucking antag items to antags

**Comment by TechnoAlchemisto** [comment]
just make everyone able to wear it

**Comment by Xhuis** [comment]
I never really understood the armor restriction tbh. It's just armor. There's nothing that's supposed to be special about it in any way other than the fact that it's made of Ratvarian alloy. Not to mention, they're probably mass-produced so Ratvar couldn't worry about _every single one_.

**Comment by PKPenguin321** [comment]
>just make everyone able to wear it

**Comment by optimumtact** [comment]
See #19750 for why this is getting merge.

**Pull request merged**
