### PR TITLE
Fixes Morphine So that it can be made.

### PR DESCRIPTION
**Pull request by Ordonis**
:cl:  Ordo
tweak: Replaced nitrogen with ethanol in morphine recipe. The recipe now has a lower yield.
/:cl:

### CODE REVIEW

**Comment by DaedalusGame** [comment]
Did you test this

**Comment by Ordonis** [comment]
Works_on_my_machine.dmm.dme.tiff.tga.mp4.wav.midi.vir.tgz.7z.exe
But yes, I poured reagents in beaker, heat beaker, morphine comes out. Recipe just requires ethanol now. Adding that to changelog now that I think of it.

**Comment by arsserpentarium** [comment]
Maybe morphine synth should be harder?

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball 

Also is the reason it's "bugged" is because it turns the nitro into ammonia? You could probably get around that by reordering your inputs :^)

**Comment by ExcessiveUseOfCobblestone** [comment]
also remove the : before each bugfix

**Comment by Iamgoofball** [comment]
@ExcessiveUseOfCobblestone you know I intentionally didn't give morphine a recipe right you fucking cunt

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball I agree with you, I just tag you cuz you're chemistry's SME

**Pull request merged**
