### PR TITLE
[s]You can't power all of lavaland from one apc

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
!

### CODE REVIEW

**Comment by GunHog** [comment]
RIP having working airlocks in the Lizard den :(

**Comment by KorPhaeron** [comment]
the lizar den is its own area and lizards cant build apcs anyway

**Comment by GunHog** [comment]
But the airlocks DID work. I am sad to lose that, but it is not really any reason against the fix itself.

**Comment by KorPhaeron** [comment]
like outside or in the den itself?

**Comment by GunHog** [comment]
Inside the den itself.

**Comment by KorPhaeron** [comment]
This pr will not impact that

**Comment by RemieRichards** [comment]
@GunHog power is ```/area``` based, that's why they're AREA power controllers (APCs), most lavaland ruins have their own ```/area``` (whether to avoid the ash weather effects, to have power or any other reason)

**Pull request merged**
