### PR TITLE
Updated MetaStation.v40D.dmm to MetaStation.v41A.dmm

### PR DESCRIPTION
**Pull request by Metacide**
Added (provisionally) a public autolathe to the RD lobby
 Added (provisionally) a set of chemistry machines to xenobiology (aka secure lab)
 Added (provisionally) another independent set of shutters in the HoS office protecting the upper space viewing window
 Added (provisionally) two drones to the derelict station, as well as some metal, glass, fuel, two duffel bags and an airlock painter
 Added more gear to the vault safe including an anonymous identity and a silenced pistol
 Added insanity wing to the prison, rearranged it slightly, neatened reeducation room
 Added derelict auxiliary atmospherics chamber just outside the atmos external airlock, for burn-chamber construction etc.
 Added a disposal unit to the lower chemistry lab desk and rearranged it to be more usable
 Added a box of silver IDs to the HoP's room
 Added two shot-glasses to the maint. bar
 Added eggs to the Recovery Shuttle kitchen
 Added fully-functioning biogenerator to the Recovery Shuttle on roundstart
 Added throwing-stars to the armoury random contraband gun spawner
 Added teleport computer and missing air alarm to bridge
 Added collectable HoP hat to the corporate showroom
 Added heater to maintenance medbay
 Added basketball to maintenance
 Added suit storage unit to HoS' office
 Added hammer and gavel to the courtroom
 Updated a lot of item paths - banana pies, brig door timers, most pets, and roundstart secure lab slimes
 Updated syndicate shuttle, station, and CentCom to current Boxstation versions
 Improved NT recovery shuttle (white ship) - it can now dock at mining, has a transit effect, and a slightly altered central room
 Removed non-functional gun charger from the shuttle bridge
 Rearranged robotics to give it more open space
 Rearranged R&D slightly, removed incorrect "mineral storeroom" designation
 Rearranged lower chemistry machines to be more usable
 Replaced biohazard containment blast doors around toxins with shutters to stop obscuring open doors
 Replaced one of the newscasters in the chapel with a notice board
 Renamed chapel 'mortuary' to funeral parlour
 Fixed soulstone shard in chaplain's office being cult/wizard use only - now anyone can use it again
 Fixed not being able to hide behind plants
 Fixed ERT response room having incorrect map
 Fixed overlapping air alarm and fire alarm between showroom and gateway
 Fixed overlapping no smoking sign and alarm in R&D
 Fixed overlapping station intercom and map south of gateway
 Fixed vendors on recovery and emergency shuttle being depowered
 Fixed incorrect area designations in atmospherics
 Fixed duplicate science satchels in scientist lockers
 Fixed broken point redeemer consoles on the labour camp shuttle

Full image: https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-04-07%2013-31%20MSv41A%20Full.png 
Files: https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-04-17%2013-58%20MSv41A%20Files.zip
Wiki: https://tgstation13.org/wiki/MetaStation

### CODE REVIEW

**Comment by pudl** [comment]
why the redesign of the lower left solars? its pretty ugly

**Comment by Metacide** [comment]
It's so the white ship can fit, I'll see if I can't improve it with the next update.

**Comment by SconesC** [comment]
Combat Shotguns, Mateba, Desert Eagle: Still in the contraband rotation?

Godammit

**Comment by pudl** [comment]
remember: you don't HAVE to have four solars of equal size and symmetrical layout. efficiency station had one weird solar, eff 2 only had 3 solars, and eff 3 only had two huge ones.

**Comment by Metacide** [comment]
Thanks very much :+1:

**Comment by Lumipharon** [comment]
We had a real big shitfest when goof tried to put chem equipment into science, just saying.

**Comment by optimumtact** [comment]
Thankfully nobody cares enough about meta :smile:

**Comment by CorruptComputer** [comment]
@Metacide Could you attach the solars here instead? http://i.gyazo.com/3ce7a4f13c3e6a3bfcf5eb0e9a9d5a1a.png

**Pull request merged**
