### PR TITLE
Fix incorrect proc signature for /mob/living/proc/Life

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

#52981 changed how Life() procs were called.

It also forgot to re-define the Life proc signature after doing so.

This gives Life the appropriate signature.

The part that changed which broke breathing via Life()
image

What we currently experience on live. `times_fired` is null and `null % anything` is always TRUE.
image

After the fix, expected behaviour restored.
image

## Why It's Good For The Game

Our intended breathing mechanic of once every 4 life ticks became every single life tick, effectively making mobs breathe 4 times as often as they should. Oh, my dear Atmos subsystem, how you must be crying in pain!

## Changelog
:cl:
fix: Living things should no longer hyperventilate 24/7 and will once again breathe at more leisurely pace.
/:cl:

### CODE REVIEW

**Comment by msgerbs** [comment]
Thank you jesus! This was driving me nuts.

**Comment by Donkie** [comment]
Whoops 🙄😬😜

**Review by Rohesie — APPROVED** [review]

**Comment by Timberpoes** [comment]
If this gets merged, #53560 can have the DNM label removed.

**Comment by ATH1909** [comment]
speedmerge

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
