### PR TITLE
If ratvar is alive, turning clockwork floors into clockwork walls is fast

### PR DESCRIPTION
**Pull request by ChangelingRain**
fast.

### CODE REVIEW

**Comment by Nabski89** [comment]
Why is this needed?

**Comment by ChangelingRain** [comment]
if ratvar is alive everything you do is fast and you are basically unkillable that's why

**Comment by Nabski89** [comment]
Why do we even have component costs after Ravtar's summoned then?

Why is it still slow to channel stuff abilities?

**Comment by ChangelingRain** [comment]
nothing costs anything when ratvar is summoned tho, the costs still 'exist' but they're ignored
because reasons.

**Comment by Nabski89** [comment]
I meant it more as a rhetorical question. I get why it's happening. Everything clock cult is great once you've won.

I meant it more as: How many walls are you building that you need an increased buildspeed for them post summon. A way to wall off that security or ERT (ha yeah right) summoned to fight you on your way to the shuttle?

I mostly just didn't feel like watching it merged without note, another clock feature that half the players will never notice.

**Pull request merged**
