### PR TITLE
[DNM] Experimentor Refactor and Changes

### PR DESCRIPTION
**Pull request by DaedalusGame**
:cl:
refactor: Refactored and modularized the Experimentor
add: Added some extra reactions for the Experimentor
tweak: The Experimentor generates points now instead of just boosting nodes whatever that does
code: Added the ability to change sounds for the clusterbuster, removed a spawn() and made it possible to clusterspawn objects other than grenades (why)
/:cl:

I only have one more commit to finish this or it will ruin the joke
Another step in the ladder to get rid of passive generation.
Experiment Results are now datumized, so new ones can be (and will be) added easily.
Experiment Results also generate points. They will only generate a meager amount of points, and the amount gained from each experiment result diminishes. The formula is `(base_points) / (number of times the result happened ^ 2)`, so full points for the first time, a quarter for the second, one ninth for the third, etc...

### CODE REVIEW

**Comment by YakumoChen** [comment]
can you still make random battery cells from it or is that gone?

**Comment by DaedalusGame** [comment]
That's the transform reaction iirc, I still have to move it over to the new system.

**Comment by epochayur** [comment]
but muh timegate

**Comment by DaedalusGame** [comment]
Get the fuckin timegate outta my house

**Comment by Bawhoppen** [comment]
Finally someone does something with the blood-magic machine. Great stuff

**Comment by AlexTheSysop42** [comment]
You forgot a stage

**Comment by AlexTheSysop42** [comment]
oh I'm dumb the 5th stage missing was intentional

**Comment by optimumtact** [comment]
is this ready?

**Comment by DaedalusGame** [comment]
i'll remove the [DNM] and ping a maintainer when it is, shouldn't be long now but people keep asking me to fix bugs in unrelated things

**Comment by AlexTheSysop42** [comment]
y tho

**Comment by optimumtact** [comment]
stale

**Pull request closed without merging**
