### PR TITLE
Supermatter shards can be unfastened with right click

### LINKED ISSUE #68685: Wrenching a SM shard as a borg instantly kills you when you right click it
## Round ID:
187139

## Testmerges:
[#68599: 'Refactors SM Delaminations to be strategies' by vincentiusvin at commit b95272e164](https://www.github.com/tgstation/tgstation/pull/68599)
[#68241: 'Reworks pAIs' by jlsnow301 at commit e003870995](https://www.github.com/tgstation/tgstation/pull/68241)
[#68444: 'Arachne Borgs' by axietheaxolotl at commit 924e92f215](https://www.github.com/tgstation/tgstation/pull/68444)
[#68632: 'Drastically improved the USB connection for air alarms. Any airlock can now be made into a shell' by Watermelon914 at commit aa11c812e6](https://www.github.com/tgstation/tgstation/pull/68632)

## Reproduction:
- Be borg
- Have a wrench
- See Supermatter shard
- Press right click
- Borg instantly dies

Continuation of:
https://github.com/tgstation/tgstation/issues/67130

You wrench tables and a lot of stuff with right click. Its kinda stupid for a right click to dust you.

### PR DESCRIPTION
**Pull request by strandsofivy**
## About The Pull Request

Title summarizes all.
Closes #68685 
## Why It's Good For The Game

Less people dusting themselves by accident.
## Changelog
:cl:
qol: Supermatter shards can now be fastened with right click too. Now, just don't forget to use a wrench.
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
Is there a screen tip for this? There should be

**Comment by distributivgesetz** [comment]
i dont think there is?

**Comment by SyncIt21** [comment]
You can add tooltips to the shard from inside the component via signals. For example

https://github.com/tgstation/tgstation/blob/cfe13015203480dafaf3fce1589ad6045e708442/code/datums/components/material/material_container.dm#L69-L72

**Comment by distributivgesetz** [comment]
> You can add screentips to the shard from inside the component via signals. For example

I'm already doing that, dw 😅

**Comment by SyncIt21** [comment]
I see. never mind then

**Comment by distributivgesetz** [comment]
thanks for the hint for an implementation still, it saved me from looking up code

**Comment by distributivgesetz** [comment]
I'll ready it up later today

**Comment by distributivgesetz** [comment]
dfgsfdsdf

**Pull request merged**
