### PR TITLE
increases MAX_THROWING_DIST

### LINKED ISSUE #35747: Newton's second law: A object in motion will tend to stay in motion. Unless its in space.
See title, some things will not properly keep momentum, losing it after a seemingly random amount of time flying through space. They don't stop completely, instead just reverting to the normal speed things drift at in space.

Observed examples of this:
1: Bodies thrown into space
2: Bubblegum charging through space.

### PR DESCRIPTION
**Pull request by kachnov**
fixes #35747

### CODE REVIEW

**Comment by Cyberboss** [comment]
This isn't a proper solution, throw objects on station are meant to have a limit

**Comment by Supermichael777** [comment]
else anything that gives extra view lets you throw nades a long distance.

**Comment by kachnov** [comment]
512 is pretty long though

**Comment by kachnov** [comment]
changed the PR according to Supermichael's suggestion

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
