### PR TITLE
Forced dictionary trimming

### PR DESCRIPTION
**Pull request by ShizCalev**
#24160 raised the amount of unused keys cause trimming to kick in to an insane amount, with each key being atleast 6 lines minimum on average, you'll end up with atleast 10k line changes each time it triggers (not even counting everything that gets moved about.)

That number quickly rises if there's more than one object on the tile, especially with var edits.

Note that several of these maps have >50~86k line changes just from forcing the trim early. I don't have a single clue how large those numbers would be if it were left to occur naturally (it would likely be once every year or two.)

This causes issues with alternative mapping programs like fastDMM which -always- prunes unused keys.

It's also leading to fatal mapmerge errors causing map corruption on small maps with tiny dictionaries such as golemship

### CODE REVIEW

**Review by optimumtact — APPROVED** [review]
Good change, we may as well keep trims small and often if we can.

**Comment by optimumtact** [comment]
As an aside, the few times trimming has actually triggered it's just caused people to assume they messed up the map merge more than anything else.

**Comment by MrStonedOne** [comment]
you should never need to trim unused dictionaries since you could just have them be reused by new entries.

worst case you could just make it start to shift changed entries down to unused keys after some point.

**Comment by MrStonedOne** [comment]
this is basically a non-issue, being turned into a issue for no reason.

**Comment by MrStonedOne** [comment]
also, all of this will be moot because byond 512 will reuse keys, removing most of the need for the map merger

**Comment by xxalpha** [comment]
Reusing every time triggers conflicts more often, it only trims after a certain threshold so more edits could be done without conflicts at once. I don't know how useful that has been in practice, but it's done the way it is for this reason.

And until DM lets you format the map output an external tool will be needed to write the map in TGM.

JSON maps when, or was that idea abandoned?

**Comment by Cyberboss** [comment]
Seems the lack of trimming is for a reason.

**Pull request closed without merging**
