### PR TITLE
pAIs and other pets that can be picked up no longer know shadow clone jutsu.

### LINKED ISSUE #69521: You can "duplicate" deadchat controlled pets
## Testmerges:
#68239

## Reproduction:
Its not true duplication of the mob but rather you can duplicate the inhand/clothing version.
Give Ian a deadchat control and orbit them, have a human pick up Ian, using deadchat control while orbiting the Ian and not the player holding them input a direction. Doing this will keep the Ian inhand/clothing item on the person carrying it but will release the mob. The mob can then be picked up again and this can be repeated.
Duplicated Ians teleport the actual Ian to their location when dropped/thrown

### LINKED ISSUE #69815: Ian duplicates while under deadchat control
## Reproduction:

When Ian is controlled by deadchat, if someone picks him up into their hand. If deadchat moves Ian while in their hand, it makes another Ian. Rinse and repeat until you have a ton of Ians.

image

### PR DESCRIPTION
**Pull request by dopamiin0**
## About The Pull Request

Under certain circumstances, mobs that can be picked up (such as Ian, various pAIs, etc) could escape their item forms, leaving behind item clones of themselves that could then be deployed to instantly teleport said mob to you from any distance. This could be repeated multiple times to create entire backpacks full of Ian shadow clones.

## Why It's Good For The Game

Closes #69521 
Closes #69815 

## Changelog

:cl: dopamiin
fix: pAIs and other pets that can be picked up no longer know shadow clone jutsu.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
From what I've looked at, the main problem here is Ian in deadchat controlling, which doesn't call relaymove to actually drop the person. I can't replicate the same for pAIs though.

**Comment by dopamiin0** [comment]
> From what I've looked at, the main problem here is Ian in deadchat controlling, which doesn't call relaymove to actually drop the person. I can't replicate the same for pAIs though.

The fix solves the issue as well as several other edge cases. Even if the deadchat should be seperately fixed, this fix is still a good idea.

**Comment by dopamiin0** [comment]
> Does this fix #61658

doesn't seem so.

**Comment by dopamiin0** [comment]
Closes #69815 as it is a dupe of #69521

**Comment by timothymtorres** [comment]
> Closes #69815 as it is a dupe of #69521

Please put that in the OP otherwise it won't autoclose.

**Comment by dopamiin0** [comment]
> > Closes #69815 as it is a dupe of #69521
> 
> Please put that in the OP otherwise it won't autoclose.

Adjusted, though I believe it's been closed anyways.

**Pull request merged**
