### PR TITLE
Cyborgs cannot weld themselves concurrently

### PR DESCRIPTION
**Pull request by ghost**
A cyborg cannot weld themselves multiple time simultaneously to regain all of their healh at once.
:cl:
balance: Cyborgs weld themselves multiple time simultaneously.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
this has come up before, and we've decided to leave it in in recognition of how slow construction crafting is, so it's unlikely this will be merged.

**Comment by Shadowflame909** [comment]
What's with all the Anti-hacking PRs lately?

RCD's already got removed from the public auto lathe. So I'm not sure how this benefits the game if it doesn't address why it's necessary that it be so inconsistent.

**Comment by PKPenguin321** [comment]
>You can only weld one door/wall at a time

Wow, I absolutely hate it!

**Comment by py01** [comment]
Changed it to just cyborgs self repairing since thats what I actually cared about.

**Comment by HomocidlePancakes** [comment]
Really? You change that, but completely ignore that borgs can be instahealed by other borgs/humies?

**Comment by IndieanaJones** [comment]
Insta-healing from other sources ought to get nerfed before this.  Even then, I'd rather you just nerf how long it takes than prevent them from just doing it all at once.

**Comment by Shadowflame909** [comment]
engineering borgs had it coming

and since the scope has now been reduced. It does now fit with how it takes a good while to heal yourself when augmented/using a brute pack if these still exist. If not then how long it takes to solo heal in general with the tiny amounts of medicine.

**Comment by py01** [comment]
my code is bad and i dont care enough to fix it

**Pull request closed without merging**
