### PR TITLE
The Antique laser no longer fires Hellfire lasers 

### PR DESCRIPTION
**Pull request by ANAME593**
## About The Pull Request
The antique laser gun will NO longer fire hellfire lasers it will only fire normal lasers  - this is my first PR take note 

## Why It's Good For The Game
the antique laser gun can be obtained easily by the cap / acting cap and it's quite powerful for something that can be obtained every round with ease by the cap/acting cap. The gun is still viable seeing as it can recharge & fit in a bag so i think this Change is warranted antique or not.

## Changelog

:cl:
balance: the antique laser gun now fires normal lasers instead of hellfire lasers

/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
Hellfire is stronger, 25 damage x 20, but also costs more energy to fire, 100 x 62.5.
It will go from 10 shots per charge to 16 and increase the damage you can do on a "full reload" from 250 to 320.

Not saying if it is a good or bad change, I just got curious about the values, went to check and I think others might be interested too.

**Comment by san7890** [comment]
This functionality was added in #56625. Can you address the specific points in this PR and let us know why it's not good for the game 14 months later?

**Comment by Fikou** [comment]
> the antique laser gun can be obtained easily by the cap / acting cap

sure
> and it's quite powerful for something that can be obtained every round with ease by the cap/acting cap.

yeah
> The gun is still viable seeing as it can recharge & fit in a bag 

ok
> so i think this Change is warranted antique or not.

why?

**Comment by Shadowflame909** [comment]
just because the captain can obtain an item easily is not a good enough reason to nerf it. They're the captain! What cant they obtain easily??

**Comment by ZerVexon** [comment]
HoS gun seems to be more of a utility option rather than a direct force option. HoS has access to the entire armory, and any sec armaments they want to build/buy, like the xray gun and the thermal pistols. The upside for the HoS gun then comes from having disabler, damage, and ion modes, as just a bag damage pistol would be sorta pointless when they've got a dozen other weapons meant for being beatsticks.

As for this change in particular, I'd say that more lower damage shots is better in this case. Having 10 25 damage shots means if you miss one, you've got less to use. Using normal lasers means you crit in just one more shot, effectively making the antique a Laser Gun that self charges and fits in a bag, which I'd consider stronger than before.

Hellfire lasers have a higher burn wound chance, but since its 4 shot crit it doesnt really mean that much. This is going to make the gun easier to use, especially since it'll charge shots sooner since lower cost to fire.

**Comment by Striders13** [comment]
We should go back to shaming captains for taking the antique gun tbh

**Comment by Dorsisdwarf** [comment]
I think this is a good change because making the captains laser a superior combat option was always silly

**Comment by GuillaumePrata** [comment]
> We should go back to shaming captains for taking the antique gun tbh
Shaming doesn't do anything, now making it bulkier/stronger so it is more of a "Station is fucked, time to go grab my old laser cannon!" instead of doing it on every shift start could be nice.

We got over the era of "It's an antag goal it must be easy to bag/steal" not only with the new way that Traitors work but also with the fact that the Blackbox is a theft goal.

**Comment by ANAME593** [comment]
> Shaming doesn't do anything, now making it bulkier/stronger so it is more of a "Station is fucked, time to go grab my old laser cannon!" instead of doing it on every shift start could be nice.  
if by that you mean make it as heavy as the normal laser gun then it changes nothing.  you can put guns in your belt slot all you need is a jumpsuit + armour isn't hard to get

**Comment by Mothblocks** [comment]
@Ryll-Ryll

**Comment by Pickle-Coding** [comment]
Just because the captain didn't spend their round doing xenobio or whatever for 40 minutes, doesn't mean they don't deserve a strong gun. Some specific people having easy access to one of the more strong weapons in the game means powergaming will be less effective, which is a good thing.

**Comment by thgvr** [comment]
The recharge hardly makes it worth using over a normal laser gun with a charger dragged behind you. I don't think the antique should be relegated to "this is an antag objective" only with how useless it would be post-this-PR.

**Comment by Ryll-Ryll** [comment]
Hellfire lasers are especially effective at wounding people not wearing armor, meaning it's basically tailor made for maiming the shit out of assistants, which I've always thought was hilarious thematically

**Comment by LemonInTheDark** [comment]
> We should go back to shaming captains for taking the antique gun tbh

did you ever stop?

**Comment by Ryll-Ryll** [comment]
> Hellfire is stronger, 25 damage x 20, but also costs more energy to fire, 100 x 62.5. It will go from 10 shots per "full magazine" to 16 and increase the damage you can do on a "full magazine" from 250 to 320.
> 
> Not saying if it is a good or bad change, I just got curious about the values, went to check and I think others might be interested too.

The hellfire laser subtype the cap's gun fires has the same cost as a normal laser

**Comment by SkeletalElite** [comment]
Even if the antique gun captains can still get hellfire lasers, they have the money to buy a hellgun kit and the access to the armory to convert one of its laser guns. I don't see why the cap's gun firing hellfire laser is too strong.

**Comment by Mothblocks** [comment]
i do not think this is a good idea

**Pull request closed without merging**
