### PR TITLE
Fixes problem of the light from lamps and candles not moving when picked up

### PR DESCRIPTION
**Pull request by Shadyyy66**
## About The Pull Request

I've set the light_system vars of lamps and candles to MOVABLE_LIGHT, meaning the light will now move when picked up.
## Why It's Good For The Game

Candles and lamps should be movable light sources anyway. This fixes the issue of lamps and candles having their light sources stay in their previous spot whenever they're picked up.
## Changelog
:cl:
fix: the light emitted from lamps and candles now move with the player when picked up.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Not a massive fan of this.
These things SHOULD have been movable, because well, that's what they are, but static lights should still support moving. if they aren't, that's the real bug.
This is a good change, but I don't like that it papers over the real issue

**Comment by LemonInTheDark** [comment]
> I can't say I really see the point in having static lights that support moving when there already are movable lights that are meant to be moved. If it's a light that can be moved, it should be a movable light, otherwise, static light.
> 
> It seems more of an oversight than a bug, to be honest.

The two are different systems. movable lights have some significant issues with them, like, they just go through walls.
It's hard to notice typically, but with something like the supermatter it'd be a large issue. That's something that is static but should be able to move.
They're also worse at color, and can oversaturate the scene.

Movable lights are an optimization, we should not let the system they sit on top of disintegrate.

It's not to say that this pr is bad, but it is totally a bug.

**Comment by Fikou** [comment]
@LemonInTheDark it's a light on an item, every other light on an item is movable, i dont get what youre saying

**Comment by timothymtorres** [comment]
I didn't see this PR earlier when I started working on #72146 but it provides not only a fix, but several other improvements.

**Comment by LemonInTheDark** [comment]
> @LemonInTheDark it's a light on an item, every other light on an item is movable, i dont get what youre saying

It implies that the static lighting system can never be used with movable things, which is not true.

I don't want to set that precedent, and didn't want to just leave this bug in there while things were non functional

**Comment by LemonInTheDark** [comment]
Also, @Shadyyy66 you need to fix the procs used to change these object's lighting, or this won't pass integration tests 

look into `set_light_range_power_color`

**Comment by ChungusGamer666** [comment]
> I don't want to set that precedent, and didn't want to just leave this bug in there while things were non functional

Addressed by my cool and awesome pr #72148

**Comment by Shadyyy66** [comment]
seems like this PR is pretty redundant when other PRs have better fixes, closing this

**Comment by LemonInTheDark** [comment]
these should be movable, you're right about that. if none of the other prs are doing that I want this too

**Pull request closed without merging**
