### PR TITLE
Removes catpeople from the game

### PR DESCRIPTION
**Pull request by lzimann**
Slippery slope. This really doesn't belong to the game.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
cat people?
Degenerate: 12
Degenerate but I'm attracted to them so enable them anyway: 27

**Comment by Repukan** [comment]
Remove lizards too

**Comment by BeeSting12** [comment]
Lzimann is trigger by adding a few pixels to someone's sprite. And it's not even his. lol

**Comment by Kraseo** [comment]
dreamseeker_2016-11-16_23-01-05

can you fuck off

**Comment by Shapsy** [comment]
one truly wonders what history lzi has with catpeople that gave him this disposition towards them

**Comment by lzimann** [comment]
I am just doing what was asked in the forums.

**Comment by Kraseo** [comment]
at no point was this ever

**Comment by FantasticFwoosh** [comment]
Catpeople don't really bring a lot to the table content wise, at-least lizards have the opt-in opt out digitade legs (but also tails and scaly skins), while fly people constantly vomit everywhere (which is actually the most beneficial thing to a race we ever put in)

I dont know, being able to directly eat/detect mice and small size class creatures? (larva's, headslugs/borers etc) even then i detest the idea of giving them buffs.

**Comment by Kraseo** [comment]
purely cosmetic options with no pros and many cons, why do people complain about it

**Comment by lzimann** [comment]
They are human with anime ears/tail, not exactly a different race.

**Comment by KorPhaeron** [comment]
Why do you care so much though? Basil was fairly content with them for months, then sybil died and you hopped servers and told them to stop having fun wrong.

**Comment by FantasticFwoosh** [comment]
@Kraseo : because for the large point it IS just cosmetic 'degeneracy' for RP rather than anything meaningful to criticise in mechanics. People coded in a weapon that racially biased towards fly people which is literally a giant fly swatter for like 40+ damage a hit.

Arguably the amphibious assistant locked 'glorfs' that never made it out of PR have better popularity. #15760

**Comment by optimumtact** [comment]
This argument was done a long time ago.

Headmins of servers choose what races to enable.

**Comment by FantasticFwoosh** [comment]
Can't stop us trying to change your mind though, we're all entitled to our opinions, as is @lzimann

**Comment by optimumtact** [comment]
You don't have to change my mind, you have to convince your players and headmins.

**Comment by Screemonster** [comment]
Also the headmins of every single downstream, tg isn't the only server that runs tgcode.

**Comment by Iamgoofball** [comment]
@Screemonster none of our downstreams keep up to date

**Comment by Screemonster** [comment]
I'm thinking of the poor fucks who tried to run a bay server (mostly for baymed) and tried updating, only to find that at some point down the line some dipshit not only disabled the clown slot because reeee muh serious arrpee, didn't just comment the code out, but _deleted the code for clowns and honkmechs from the game entirely_ then pitched a screaming fit when asked how to re-enable them. That's not a good thing to try and emulate.

**Pull request closed without merging**
