### PR TITLE
Tweaks stats of 4 virus symptoms

### PR DESCRIPTION
**Pull request by Alomga**
Makes Vitiligo, Revitiligo, Facial Hypertrichosis and Alopecia usefull instead of making your virus worse without contributing anything. Symptom that makes you pale shouldn't have worse stats that one that can kill.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
i cast freeze on this pr

**Comment by 81Denton** [comment]
We got uhhhhhh feature freeze going on right now, you'll most likely have to open the PR again after it's over

**Comment by Alomga** [comment]
I'm not going to hide my complete and utter lack of competence and knowledge and ask what is this feature freeze.

**Comment by optimumtact** [comment]
So, during a feature freeze, we freeze all balance, tweak, feature changes completely, so people are only able to work on changes that are fixing existing bugs.

It's partly to give the maintainers a break from endless balance arguments and mostly to improve the stability and performance of the codebase.

Unfortunately you've landed right smack in the middle of one.

I'll have a chat with @KorPhaeron and we'll probably let you sneak this one in, since it's your first PR here.

**Comment by XDTM** [comment]
I approve, these symptoms are mechanically useless in either direction _and_ give your disease away. A stat buff justifies putting them in sometimes.

**Comment by XDTM** [comment]
Also, while you're there, feel free to remove the headers above the symptoms. If someone is reading code to figure out what things do they can just read it, otherwise everything is already in the wiki.

**Pull request merged**
