### PR TITLE
Fixes Spirit Realm rune spawning braindead cult ghosts

### LINKED ISSUE #38135: Blood Cults manifest rune is broken
[Round ID]: 88627
Server: Sybil

1. Use the manifest rune with patient ghosts. ALL THE MANIFEST BODIES END UP BRAINDEAD.

Holy shit the cult that round literally needed 1 more person to summon but because of this bug they had 20 braindead bodies. wtf is this??

### LINKED ISSUE #38144: You can sacrifice cult ghosts
Saw a round where cultists were somehow able to sacrifice manifested ghosts to get extra revives. They also weren't ashing properly for some reason.

### PR DESCRIPTION
**Pull request by zaracka**
:cl:
fix: The Spirit Realm rune no longer spawns a braindead cult ghost when attempting to summon one after a player reaches the limit.
/:cl:

The limit check should be happening before the mob is created, not after.

Fixes #38135.
Fixes #38144.

### CODE REVIEW

**Comment by Shadowflame909** [comment]
make sure to add fixes #____ in the title.

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
If I'm reading this right this PR increases the ghost limit by 1 due to location of the conditional, can you double-check that?

**Comment by zaracka** [comment]
Hmm... yeah, it does. It seems 4 being the limit is intended though and 3 was an unintentional limit. I can change `var/ghost_limit = 4` to `var/ghost_limit = 3`, so that it stays the same?

**Comment by SpaceManiac** [comment]
Bring it down so it stays the same and this PR is pure fix, feel free to open a separate balance PR afterwards if you think it's deserved.

**Comment by ExcessiveUseOfCobblestone** [comment]
Need to prefix **both** PR numbers with `Fixes`

**Comment by zaracka** [comment]
Sure. Why though?

**Comment by ExcessiveUseOfCobblestone** [comment]
:3

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
