### PR TITLE
Makes AI tolerable again

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I tried to play AI recently and the artificial lag is terrible

:cl:
rscadd: The AI no longer has a tracking delay because artificial lag is the most miserable thing in the world.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:-1: Very bad PR

**Comment by Anonmare** [comment]
Gonna have to go with PK on this one, the lag is necessary for balance.

**Comment by TheWiznard** [comment]
But how can FUCKYEAR know where you are at all times if I can't auto lock on to you the moment you shout ai rogue?

**Comment by Robustin** [comment]
Yea I'm not sure what the issue is. It's necessary to prevent the ol' "click the person's name, immediately jump to location of HARM, bolting all doors in <.5 seconds, etc" meme.

**Comment by Ausops** [comment]
>artificial lag on top of lag

no

**Comment by optimumtact** [comment]
artificial interface difficulty is not good, same thing with the random ass taser delay that I removed.

:+1: 
me_irl

**Comment by KorPhaeron** [comment]
I'd rather add a delay/warning to door bolts starting to lower than have this dumb camera lag

**Comment by optimumtact** [comment]
Remove the ai being able to bolt

its a simple fix

**Comment by Anonmare** [comment]
>Removing the AI's any hope of defence against an unsynced borg

Oranges you're memeing again

**Comment by xxalpha** [comment]
>I'd rather add a delay/warning to door bolts starting to lower than have this dumb camera lag

Yes, do this in this PR as well. If you need help doing it ask me in irc.

**Comment by optimumtact** [comment]
well, let it bolt the ai sat doors then, but no others

**Comment by Ausops** [comment]
kors idea of slow bolting sounds better

**Comment by Robustin** [comment]
If you're going that route, then consider my old suggestion:

- Make "bolting" doors either flash with the emergency lights, blink with the bolt lights, or give some other visual indicator that the AI is bringing the hammer down on your ass.

Make it enough time for a conceivable dash out the door but fast enough that if you're not paying attention/reacting immediately you'll still be trapped.

**Comment by Incomptinence** [comment]
Man where's zile when you need even more self important attempts to raise another AI lynch mob.

**Comment by Jalleo** [comment]
Tbh just making door bolting take time would be better with the removal of this.

**Comment by xxalpha** [comment]
Well there's no point to having both delays.

**Comment by PKPenguin321** [comment]
This delay is so that if somebody says "HE--" over the radio, the person attacking them has a chance to duck into maint or something before harmyeller9000 instantly teleports to him and declares his name valid. :-1:

**Comment by xxalpha** [comment]
Wear a mask.

**Comment by yackemflam** [comment]
HE HAS GREEN HAIR AND BLUE EYES, THE PERP IS URIST MCTRAITOR

**Comment by yackemflam** [comment]
Basically anyone and everyone who doesn't play silicons 24/7 will agree that that this is a pretty stupid thing to remove. There's a reason why this was put in, in the first place.

**Comment by xxalpha** [comment]
People who don't play silicons are baddies, tbh.

**Comment by yackemflam** [comment]
>Have vision over any major parts of the station with a few exception
>Can bolt down any harmful antags at will
>Usually the first to see who the perp is
>Can trigger a man hunt to catch the perp
>If non-human, can shock doors in the way to put the perp in crit if no gloves
>All that and more

**Comment by Robustin** [comment]
Kor can you put in the door bolt delay so that #17483 doesn't fail due to "lol atomizing related changes".

**Comment by Durkel** [comment]
Just going to leave this random complaint here, but currently cutting cameras doesn't have the old snipping sound and instead has the default hitting something with a fire extinguisher sound all items have now. Pls fix and make it stealthy again.

**Comment by AnturK** [comment]
The artificial delay is still worst kind of forced balance. I believe we should look for other solution for the problem.

**Pull request merged**
