### PR TITLE
Unsecures the non-secure tech storage on Northstar. Fills up Z2 maintenance.

### PR DESCRIPTION
**Pull request by spiders24110**
## About The Pull Request
Z1:
Replaced reinforced walls in tech storage with normal ones
изображение
Added some more minor maint loot spawners
Z2:
Added a holopad to AI sat entrance here
изображение
Also fills up Z2 maint with a ton of spawners, changes some consistent spawns to random spawners and adds flavor to some rooms.
## Why It's Good For The Game
non-secure tech storage shouldn't be as secure as secure tech storage cause it doesn't contain things that are dangerous enough to justify it 
## Changelog
:cl:
add: Northstar: non-secure tech storage been made less secure.
add: Northstar: added a holopad to AI sat entrance.
add: Northstar Z2: fills up maint with more loot.
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
Balance PR try to put text in "Why its good for the game" section challenge impossible

**Comment by Striders13** [comment]
> Isn't this a balance PR and should have at least some text in "Why its good for the game" section?

ok

**Comment by Striders13** [comment]
so true

**Comment by Thunder12345** [comment]
image
@Maurukas but this is north star not birdshot???

**Comment by tralezab** [comment]
bad "Why It's Good For The Game" on a pr that affects balance is like my biggest pet PEEVE

image

**Comment by Striders13** [comment]
okay

**Pull request merged**
