### PR TITLE
EngiMarket Part Seven: Indoor Fulton, engi clothes, misc. fixes

### PR DESCRIPTION
**Pull request by Robustin**
All of it remains admin only for now, the only item here I'm even considering adding as a reward is the Fulton to help engineering move heavy equipment (or canisters, see: https://www.youtube.com/watch?v=9MS1TWSqM3E&feature=youtu.be).

The only notable fix is that atmos scans will now scan all gases, not just the main 4. 

I'm been busy on my Grand Finale since multi-seat vehicles didn't impress anyone, that should be done by tomorrow and then the last PR will be deciding what actually is available for rewards.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>bundling fixes with clothes with fultons

**Comment by Robustin** [comment]
Its all admin only, I mean the fulton is pretty much a var-edited fulton anyway. The final rewards thread is where people can argue about whether it gets added 4real. The clothes are just going to collect dust since I don't have a clear use for them atm.

**Comment by AdamElTablawy** [comment]
I'm still annoyed that engineers don't have to build this item dispenser if/when it's given to them.

Like come on. You finally give engineering the chance to shout 'erectin' a dispenser' and you fucking blew it.

**Comment by Robustin** [comment]
I'd be open to any of that Adam if there was a way to do it without just making it feel like a hoop to jump through.

**Comment by ChangelingRain** [comment]
Sorry dude but literally none of the maintainers want to merge this plus the actual design lead doesn't like it.

**Pull request closed without merging**
