### PR TITLE
Adds "cut ai wire" helper; Adds them to the Pirate Shuttle

### PR DESCRIPTION
**Pull request by iwishforducks**
Stops silicons from interacting with the Space Pirate Shuttle's airlocks by cutting the AI wires on the airlocks of the shuttle by default using a new "cut ai wire" helper. Borgs are able to regain control by physically mending the wire of the airlocks.

Note that this does not stop borgs from interacting with other machinery on the pirate shuttle.

## Why it's good for the game

The meta to deal with space pirates is for a single borg to cuck pirates by shocking and bolting all of the doors on the pirate ship. This does not entirely get rid of the meta, as any smart borg can simply mend the wires back, but it means borgs will not longer be able to magically shock doors from windows.

## Changelog

:cl:
add: Cut AI Wires maphelper for airlocks.
tweak: AI wires on the Space Pirate shuttle are cut by default.
/:cl:

### CODE REVIEW

**Comment by Pugie** [comment]
Who cares borgs cant use the gear?

**Comment by ishitbyabullet** [comment]
Now imagine this on the nuke op shuttle as well.

**Comment by iwishforducks** [comment]
> Now imagine this on the nuke op shuttle as well.

I most likely will not apply this to the nuke op shuttle, as nuclear operatives more often than not call in borg reinforcements. On the other hand, pirates never deal with borgs or AIs, so it does not make sense as to why borgs should be able to fiddle with the pirate shuttle.

**Comment by zxaber** [comment]
Nuke ops tend to be fairly shock-resistant, and if you bolt them in they'd just blow the door off and continue as if nothing happened. Probably not a big deal to worry about if the fix prevents syndicate borgs from also using the airlocks.

It'd better  if we had a "permissions" system that prevented syndicate borgs from using station airlocks and vice versa. Perhaps with a function that syndicate borgs could use on an alive station AI to get station airlock authentications.

**Comment by iwishforducks** [comment]
> Nuke ops tend to be fairly shock-resistant, and if you bolt them in they'd just blow the door off and continue as if nothing happened. Probably not a big deal to worry about if the fix prevents syndicate borgs from also using the airlocks.
> 
> It'd better if we had a "permissions" system that prevented syndicate borgs from using station airlocks and vice versa. Perhaps with a function that syndicate borgs could use on an alive station AI to get station airlock authentications.

That is out of scope for this PR but I personally would not be opposed to a permissions system for borgs. (Though that seems to defeat the purpose of borgs getting pseudo AA)

**Comment by iwishforducks** [comment]
For anyone wondering what the sprite looks like:
airlock_cutaiwire
image

**Review by Cyberboss — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Cyberboss** [comment]
Thanks for the PR, welcome to /tg/station 13 contributors!

**Pull request merged**
