### PR TITLE
Fixes a warning that some guy left in freezer.dm code

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

Some guy didn't compile their code and find this warning that would've appeared if they had actually compiled their code (not even test it, just compile it)
PR that did it #60875

## Changelog
:cl:
fix: Fixed freezers protecting their contents after being exploded.
/:cl:

### CODE REVIEW

**Review by Kylerace — APPROVED** [review]

**Comment by Ghommie** [comment]
> 
> Some guy didn't compile their code and find this warning that would've appeared if they had actually compiled their code (not even test it, just compile it)

Uh, I thought I did it... probably I either didn't notice the warning or closed the bat before it actually finished compiling.

**Review by Cyberboss — APPROVED** [review]

**Comment by MrStonedOne** [comment]
@tgstation/commit-access at one point in time, warnings would fail CI.

Was that removed intentionally or did it fall by the wayside during a CI refactor?

**Comment by Cyberboss** [comment]
My guess is it was forgotten because it requires extra parsing and not just error code checking

**Comment by Mothblocks** [comment]
This is annoying me

**Pull request merged**
