### PR TITLE
Rewrites how action buttons icons are generated, makes them layer nicer. Allows observers to see a mob's action buttons. 

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Rewrites how action button icons are generated.
   - Prior, generated an action button icon was fairly simplistic and didn't allow for many changes. Someone recently added the option for overlays to be generated over action buttons, but the framework was very weak. 
   - Now, action button icon generation is split across multiple procs, like atom icon updates. 
      - The background of action buttons are underlays
      - The actual icon of the action button is the icon and icon state of the action button movable
      - The rim / border of the button is an overlay, layered overtop the button. 

- Allows observers to see what action buttons a mob has. They even update in real time! And no, the observers cannot click on them.

## Why It's Good For The Game

- Runechat text of action buttons are no longer hidden behind the actual icon. This was very ugly with cooldown actions, as the cooldown text was hidden behind a lot of spell icons. 
- Cuts down on a lot of icon duplication. 
- Gives much finer control over action button icons
- Saves a bit of processing from generating full action button icons when not necessary. Not implemented in many places, but is in some. 

image

image

## Changelog

:cl: Melbert
add: Observers can now see what action buttons an observed mob has. No, you can't click them. And no it doesn't show EVERY action. 
refactor: Refactored how action button icons are generated. Some actions will now use a colored border when active instead of just turning green. Cooldown text will also appear on the top layer of actions too. If you see any funky lookin' icons (namely their borders), let me know.
refactor: Bluespace Golem's teleport action is now a cooldown action.
fix: Construct actions go to the middle of the screen like expected. 
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
redpilled

**Review by Fikou — CHANGES_REQUESTED** [review]
observers not seeing action buttons is intended most likely. we also dont let them view antag datum moodlets, and every antag has an action button for their antag info

**Review by Twaticus — APPROVED** [review]

**Comment by Fikou** [comment]
> > observers not seeing action buttons is intended most likely
> 
> there is already support for it in the code. it is just broken, and i don't think ever worked
> 
> image

that still makes anti-ghost mood useless, and i would prefer tackling that be a separate pr. could you make actions that dont render to ghosts (and are still properly placed/ordered, so you cant tell that one is missing)?

**Comment by LemonInTheDark** [comment]
> observers not seeing action buttons is intended most likely. we also dont let them view antag datum moodlets, and every antag has an action button for their antag info

it's not actually, I intended it.
didn't think about the antag bit admittedly

**Comment by Fikou** [comment]
> > observers not seeing action buttons is intended most likely. we also dont let them view antag datum moodlets, and every antag has an action button for their antag info
> 
> it's not actually, I intended it. 

it was like that before you were even born

**Comment by LemonInTheDark** [comment]
damn it all

**Pull request merged**
