### PR TITLE
you can now get an advanced camera console

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

you can get an advanced camera console from illegal tech

## Why It's Good For The Game

allows for checking on station better without those shitty ass dropdown menus if illegal tech is obtained
is under illegal tech because only syndies use the consoles and the ai camera upgrade is there so makes sense

## Changelog
:cl:
add: You can now get an advanced camera console from the security lathe after illegal technology has been obtained.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
:eyes:

**Comment by FloranOtten** [comment]
eyes

**Review by actioninja — APPROVED** [review]

**Comment by ATH1909** [comment]
As an occasional warden player, I approve of this PR.

**Comment by Ty-the-Smonk** [comment]
This better make the space comm station one lootable

**Comment by Fikou** [comment]
> This better make the space comm station one lootable

does that one have a syndie console or a normal one

**Comment by bigfatbananacyclops** [comment]
ERP is impossible now for admins

**Comment by SynnGraffkin** [comment]
Would be nice for R&D upgrading via camera and bluespace RPED if gotten early enough.

**Pull request merged**
