### PR TITLE
Tweaks Servant cyborg loadouts

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Changed what scriptures and tools Servant cyborgs get; a full list can be found on the clockwork cult wiki page.
/:cl:

- Standard borgs: Judicial Marker, Linked Vanguard, Tinkerer's Cache, Ratvarian Spear, Cyborg Proselytizer
- Engineering borgs: Replicant, Cogscarab Shell, Soul Vessel, Sigil of Transmission, Interdiction Lens, Cyborg Proselytizer
- Janitor borgs: Replicant, Sigil of Transgression, Ocular Warden, Mania Motor, Tinkerer's Daemon, Cyborg Proselytizer
- Security and Peacekeeper borgs: Belligerent, Judicial Marker, Taunting Tirade, Volt Void, Ratvarian Spear
- Medical borgs: Linked Vanguard, Sentinel's Compromise, Fellowship Armory, Vitality Matrix, Mending Motor, Ratvarian Spear
- Service borgs: Replicant, Tinkerer's Cache, Fellowship Armory, Spatial Gateway, Clockwork Obelisk, Truesight Lens
- Miner borgs: Linked Vanguard, Spatial Gateway, Volt Void, Ratvarian Spear, Truesight Lens

Yes, this is an engiborg nerf. They can only make slabs, tiny asshole scarabs and supply power to structures, instead of being able to downright make a base on their own, which is bullshit, given that they're already the most common borg.

For pretty much everything else, though, this is a pretty big buff; more tools and more immediately useful things.

### CODE REVIEW

**Comment by coiax** [comment]
It looks like standard borg is the "best",  given access to a Proselytizer (worst word to spell) and the ability to make caches.

Also, is there any way that engiborgs would be able to assemble the cogscarab? Maybe like if you have a shell and a vessel on the same tile, and you wrench/screwdriver/crowbar, w/e, they get joined?

**Comment by ChangelingRain** [comment]
Engiborgs have to rely on other people to make scarabs. This is intentional.

**Comment by GunHog** [comment]
At least let them keep ocular wardens...You do not want to wind up pushing Engiborgs too far to the other end of the balance spectrum!

**Comment by ChangelingRain** [comment]
They can already build the FUCK out of defenses, they would be useful and viable with a proselytizer alone. Make a janiborg if you want active defenses, make an engiborg if you want five layers of clockwork walls.

**Pull request merged**
