### PR TITLE
[No GBP] Fixes coin values but for real this time

### PR DESCRIPTION
**Pull request by Momo8289**
## About The Pull Request
Forgot to update the value of the iron coin in #76066, this fixes that
## Why It's Good For The Game
See #76066
## Changelog
:cl:
fix: Had to destroy a lot more of em, but the value of iron coins are now back to normal
/:cl:

### CODE REVIEW

**Comment by Momo8289** [comment]
@ArcaneMusic

**Comment by Helg2** [comment]
Since you here, can you make the mat values use defined value like SHEET_MATERIAL_AMOUNT
`value_per_unit = 5 / SHEET_MATERIAL_AMOUNT`
So no one needs to update it in future if changing the defined value again

**Comment by SyncIt21** [comment]
> Since you here, can you make the mat values use defined value like SHEET_MATERIAL_AMOUNT `value_per_unit = 5 / SHEET_MATERIAL_AMOUNT` So no one needs to update it in future if changing the defined value again

It should actually be based on the old `SHEET_MATERIAL_AMOUNT` amount i.e 2000

So 0.025 would be written as `5/SHEET_MATERIAL_AMOUNT

Same for all other mats, it should be adjusted based on the old values before #76066 was merged

**Review by ArcaneMusic — APPROVED** [review]
Oh right sure yeah

**Pull request merged**
