### PR TITLE
HSSSS, GRRRR, meow: feral edition

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request

https://github.com/user-attachments/assets/8700ba46-b505-4f8b-8977-c20472c72ceb

https://github.com/user-attachments/assets/954b5f3b-7fe4-4ade-9e67-e3ac9bad6550

A collaborative work between sadboysuss/grungussuss and Sothanforax
adds a hiss emote to humans and gives sounds to:
- [X] Lizard
- [X] Ethereal
- [X] Human
- [X] Monkey
- [X] Felinid
~~[ ] Moff get real~~

## Why It's Good For The Game
image_2024-12-06_141858923

## Changelog

:cl: grungussuss and Sothanforax
add: hiss emote
sound: hissssssing sounds
/:cl:

### CODE REVIEW

**Comment by Sothanforax** [comment]
I love hissing into my phone mic

**Comment by DrAmazing343** [comment]
> an assistant and a naked lizard wrestle... what did they mean by this...

Don’t get weird in the GitHub challenge: IMPOSSIBLE

**Comment by ZephyrTFA** [comment]
FAILURE #1: A species type was detected with no changesource flags: /datum/species/felinid at code/modules/unit_tests/species_whitelists.dm:5

**Comment by Sadboysuss** [comment]
> FAILURE #1: A species type was detected with no changesource flags: /datum/species/felinid at code/modules/unit_tests/species_whitelists.dm:5

done, other test fails are unrelated and should be fixed in some pr soon

**Pull request merged**
