### PR TITLE
Movement now works in any client dir

### PR DESCRIPTION
**Pull request by ghost**
:cl:
code: Movement now works even if client dir is changed
/:cl:

maybe someday we can have rotating views.

### CODE REVIEW

**Comment by cacogen** [comment]
Mirroring the station is like a new map

**Comment by spookydonut** [comment]
@Qustinnus rebase/merge commit for working CI

**Review by actioninja — DISMISSED** [review]
I would merge this myself but I bountied it and am not comfortable merging bountied code

**Comment by Qustinnus** [comment]
this is ready btw, travis had a stroke so thats why its red

**Comment by actioninja** [comment]
Rebase for new CI

**Comment by Qustinnus** [comment]
done

**Pull request merged**
