### PR TITLE
Cargo console UI touchup

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Moves requests and cart below the cargo pack list, so you dont need to find the right button after everything you buy. Resized the cargo window, less airy. Added a toggle for buying privately, less buttons should improve performance somewhat.

cargoconsole

## Why It's Good For The Game
Less annoying UI.

## Changelog
:cl: Skoglol
tweak: Cargo console UI touched up a bit. Requests and cart moved below the cargo packs for less button shuffling, buying privately is now a toggle, resized window slightly.

/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
while you are editing the cargo console why not make the "private buy" a cross check that when enabled it makes all crates bought private'd instead of 2 buttons for every crate

**Comment by kriskog** [comment]
Yeaaah,  that wouldn't be a bad idea. Less buttons is preferable for performance.

**Comment by Tlaltecuhtli** [comment]
based and redpilled

**Comment by optimumtact** [comment]
need to recompile tgui to fix the conflict

**Comment by kriskog** [comment]
Done. For future reference, do I even need to include the tgui.js file or is there automatic compile on merge?

**Comment by optimumtact** [comment]
it's not autocompiled

**Pull request merged**
