### PR TITLE
Adds a new Round-End Sound to the game.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

This PR adds a new round end sound to the game, featuring the vocal stylings of a certain maintainer we have on payroll.

What do you mean we don't pay him?

## Why It's Good For The Game
It's quite funny and it's in commemoration of the new GDC talk based on SS13 that dropped this week.

## Changelog

:cl:
soundadd: A new round-end sound is in rotation.
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
(https://www.gdcvault.com/play/1027757/Open-Source-Game-Development-Summit) source for reference

**Comment by Mothblocks** [comment]
these are config now so this won't even work but i'm scared to open this ogg

**Comment by Mothblocks** [comment]
give me like 5 minutes to prepare myself

**Comment by Mothblocks** [comment]
i wish they showed it but nearly the whole crowd raised their hand by the way

**Comment by Mothblocks** [comment]
of like 40ish people

**Comment by Mothblocks** [comment]
i added it to the config so i'll merge this just to mirror

**Pull request merged**
