### PR TITLE
Wizard can no longer choose Fireball spell. Replace apprentice Fireball with Lightning Bolt.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes Fireball spell from the Wizard's selectable spell arsenal.  Replaces the Apprentice Wizard's Fireball spell with Lightning Bolt.   All other ways of obtaining and casting Fireball are unchanged.

## Why It's Good For The Game

Looking at all the Wizard spells as a whole, it seems the intent of Wizard is to cause wacky, odd, and off-beat situations, making the crew deal with problems not found in any other gamemode; not just to be "Murderbone Plus".  Currently, Fireball is strong and reliable enough that most people don't bother trying out other things, locking in Fireball and letting loose the explosions.  Making Fireball a wand-only spell for Wizards gets rid of another (almost) one-shot attack for balance and also will encourage players to try to get out of their comfort zone with Wizard roles.  This change will impel players to try out some of the more interesting Wizard loadouts or create new ones.  There are still plenty of devastating combat moves Wizards can use if they want to--including the much more sensible Wand of Fireball if they _really_ want to use Fireball.

After this change goes through, we can look at expanding the Wizard's arsenal with more mischief-type spells ("Summon Kudzu" or "Lube Beam", anyone?), allowing the wizard to sow more kinds of chaos directly or indirectly in ways that have more interesting roleplay and counterplay than "ONI'SOMA-to-win".

## Changelog
:cl:
balance: The Wizard Federation has run out of Fireball spells!  They can no longer pick Fireball from their starting spellbooks.  They still have plenty of Fireball wands in stock, though!  Apprentices who specialize in Destruction will now get Lightning Bolt instead of Fireball.
/:cl:

### CODE REVIEW

**Comment by Timonkeyn** [comment]
bruh

**Comment by dr-bee** [comment]
Replace it with the wand, that way it is still a powerful tool but is limited.

**Comment by Qydra** [comment]
> Replace it with the wand, that way it is still a powerful tool but is limited.

Yep, that's already available for wizards--the belt of wands contains a Wand of Fireball.

**Comment by necromanceranne** [comment]
Here's an alternative for consideration. Replace baseline fireball with the devil Hellfire version. If it's gonna be bread and butter, it shouldn't be such an 'I win', but it should still exist because it's such a huge part of the wizard identity, and Hellfire is much tamer as far as spells go that can get spammed.

The problem with fireball is A) hellfire is closer in functionality to the iconic version of Fireball from wizard's dnd roots, B) it's a ranged stun that kills you as well and frankly is all you really need to kill everyone on the station because of it.

**Comment by TerraGS** [comment]
Alternatively just make fireball shit like remove the blast so it's just a magical Molotov.

**Comment by wesoda25** [comment]
Fireball was already nerfed via range limit, doesn’t need anything else tbh

**Comment by ATH1909** [comment]
ided

**Comment by OverlyGeneric** [comment]
Isn't the whole purpose of wizards is to be a glass cannon antagonist?

Very strong spells but a very frail body?

The fireball was that sort of spell that had the same chance of murdering the wizard then the wizard's target.

**Comment by ATH1909** [comment]
In my experience, I don't see very many successful wizards choose Fireball. Usually, wizards will either go for a gimmick or take Fireball and accidentally kill themselves/knock themselves out with it.

Fireball is a high risk, high reward spell, and I personally think that it's at a good place right now.

**Comment by Tlaltecuhtli** [comment]
wear a bomb suit next time you wont die to it

**Comment by YPOQ** [comment]
The text here also needs updated https://github.com/tgstation/tgstation/blob/6e44bd3a931238dc473cbed4afd6d11e0c55cbfd/code/modules/antagonists/_common/antag_spawner.dm#L33

**Comment by AdamElTablawy** [comment]
Why people try to make wizard less overpowered is beyond me.

Fireball makes you a glass cannon. Yeah, it’s powerful, but there’s a fair chance you’ll accidentally blow yourself up because there was a cat standing next to you when you fired it.

**Comment by Qydra** [comment]
Pretty much everyone is a glass cannon in this game unless they're in a mech.  In my opinion, having to say, "It's not overpowered if they use it wrong," says bad things about the balance of the mechanic, especially in a game like this where the skilled gamers--the ones who aren't going to screw up the spellcast--are the ones most likely to faceroll the entire station with a mechanic that isn't balanced right.  Sure, you run the risk of blowing yourself up, but the risk isn't _that_ great, and in return you get an AOE ranged attack that stuns and dismembers the target, and the cooldown is short enough that you can teleport or flee into maint and have another one ready to go in no time.  With so many upsides and the only downside being an accident that would rarely happen to a skilled player, why shouldn't the wizard be made to have limited casts or burn a spell slot on Charge?  And remember, the issue is not just that Fireball is strong: it's that it's _so much better_ than the other options that those other options hardly see the light of day.  Wizard has the ability to create a lot of interesting scenarios for the crew, but more often than not it's just Fireball, Fireball, Fireball.  I'd be interested to see the actual pick percentages if they're available.

**Comment by ExcessiveUseOfCobblestone** [comment]
i'm still waiting to try out x5 timestop (10 sec cd when effect lasts for ~9.5ish)

**Comment by Qydra** [comment]
> i'm still waiting to try out x5 timestop (10 sec cd when effect lasts for ~9.5ish)

All that's missing is to roll Wizard on dynamic and kill a traitor for his Gloves of the North Star. 😂

**Comment by Qydra** [comment]
Just spent some time playing around with Fireball on localhost to be sure of myself.  I'm only more confident about this change because of it.  You get 5 shots with a wand, and you can reload every 60 seconds with a Tier 1 Charge spell--that's still TONS of spellcasts.  This nerf will barely register with anyone who mains a Fireball loadout in terms of loss of firepower--they'll just be using a wand instead of their hands.  The only thing that will change is counterplay--they can be disarmed, and they can't spam _quite_ as fast as they used to.

**Comment by nicbn** [comment]
Wizard is already a joke round, that's overbikeshedding

**Comment by Qydra** [comment]
Why should it be just a joke, though?  You make it sound like it's a throwaway game mode.  A creative antagonist wizard could make some truly memorable emergent gameplay.

**Comment by AdamElTablawy** [comment]
They won't and you know it. People who intend to be creative don't pick fireball and bone with it-removing fireball won't force creativity, they'll just go for one of the other million easy spell choices.

There really aren't any issues with fireball I can think of.

**Comment by ishitbyabullet** [comment]
> Looking at all the Wizard spells as a whole, it seems the intent of Wizard is to cause wacky, odd, and off-beat situations, making the crew deal with problems not found in any other gamemode; not just to be "Murderbone Plus". 

Seems like you want it that way. In practice, unless you're able to stay alive for a long period of time while annoying everyone or have a good gimmick, you kinda have to murderbone everyone otherwise there is a chance of the server hating you and thinking you're an absolute retard for making the noob mistake to not kill everyone, be friendly, or not stay alive for a ridiculously long time.

Also, what is this spell even like? Are you just replacing fireball with a taser/better lightning packet or something?

> ("Summon Kudzu" or "Lube Beam", anyone?),

Kudzu sounds boring and not magic at all. Lube beam is a clown thing. Please don't replace the wizard's spells with gimmick only shit though. Some people actually want to roleplay/feel like they're a wizard which is quite hard to do. It would be annoying if they had to actually use non-magic stuff just to fight back DIRECTLY.

**Comment by Whoneedspacee** [comment]
fireball is only a level 3 spell slot tf

**Comment by Shadowflame909** [comment]
It's one dude versus the entire server.

If you don't like that. Try for a game-mode removal. Not a weird nerf.

**Comment by Putnam3145** [comment]
just buff tank wizard (huge amounts of escapes, maybe add an actual defensive spell) instead tbh. sure people will still go for fireball a lot of the time but having various viable strategies even among gimmicks seems fine.

**Comment by SkeletalElite** [comment]
> Looking at all the Wizard spells as a whole, it seems the intent of Wizard is to cause wacky, odd, and off-beat situations, making the crew deal with problems not found in any other gamemode; not just to be "Murderbone Plus"

I don't think you can get much further from the truth than that. Only a few wizard spells do that.

**Comment by SynnGraffkin** [comment]
Ided pr

**Comment by necromanceranne** [comment]
Wait hold on so summon magic still gives the CREW fireball?

I'm sorry but what?

**Comment by blurbo** [comment]
"guys how can wizard have SPELLS!?!"

**Comment by 81Denton** [comment]
Okay what kind of grinch removed the "i ded" label

**Comment by 81Denton** [comment]
>it seems the intent of Wizard is to cause wacky, odd, and off-beat situations

The majority of wizard spells are there to make crew go horizontal, or to assist in making crew go horizontal. IMO only summon events is really wacky, and even that makes crew so miserable that they want to die.

**Comment by necromanceranne** [comment]
I don't even think lightning bolt is a good replacement on its own for apprentices since lightning bolt is good when paired with spells that don't take an age and a half to come back up like Tesla. Tesla and lightning bolt are great combo'd with a mobility spell to just be a real pain in the arse to deal with. On its own it's really, really weak. You would have more success as a bluespace wizard than you would a destruction wizard given the spell uptimes to effect.

Have you considered Arcane Barrage instead?

**Comment by Qydra** [comment]
> Have you considered Arcane Barrage instead?

That would make sense.  Would people like it better if instead we changed Fireball to be more like the devil's hellfire spell, as one commenter suggested?

**Comment by necromanceranne** [comment]
I would also maybe suggest giving it a balance pass. It seems a LITTLE weaker than I thought though it is a blinding effect.

**Comment by wesoda25** [comment]
Hellfire sucks ngl and is way worse than fireball

**Comment by Dawson1917** [comment]
Anyone who reworks explosions to not cause sleepstuns will solve 90% of the problem of fireballs. It's an average DPS spell on its own. It's the stun that makes everybody angry.

**Comment by 81Denton** [comment]
As @Dawson1917 said, the main issue here is the unconsciousness caused by explosions, even if they're not large or not occurring immediately next to the mob.

Instead of removing fireballs, I'd appreciate rebalancing explosions so that unconsciousness doesn't happen anymore and instead gets replaced with knockdown. This wouldn't only solve the fireball issue, but also a lot of other crap related to explosives.

The proc in question is:
https://github.com/tgstation/tgstation/blob/a541f767601c8403a4afbfa85d787783b65b3ab8/code/modules/mob/living/carbon/human/human_defense.dm#L373-L417

**Pull request closed without merging**
