### PR TITLE
Adds crafting recipe for catwalk floor tiles

### PR DESCRIPTION
**Pull request by Colovorat**
## About The Pull Request

Catwalk floor tiles are now craftable

## Why It's Good For The Game

Catwalk floor tiles are now craftable

## Changelog

:cl: Colovorat
expansion: Adds catwalk floor crafting recipe
imageadd: catwalk floor tile object sprite and inhand sprites
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
i'm not a spriter

**Comment by Bawhoppen** [comment]
Maybe it would make sense to give them separate names, to distinguish what they are? Perhaps mezzanine floors, metal walkways, grille plating, something like that.

**Comment by Colovorat** [comment]
> Maybe it would make sense to give them separate names, to distinguish what they are? Perhaps mezzanine floors, metal walkways, grille plating, something like that.

It's called catwalk plating

**Review by Watermelon914 — APPROVED** [review]
Code looks fine, awaiting spritetainer review

**Pull request merged**
