### PR TITLE
Fixes piping sprite/layers

### PR DESCRIPTION
**Pull request by redmoogle**
### About The Pull Request

Fixes the spriting bug where _someone_ added icon states not knowing they're assigned afterwards
This was caused by #45390 

## Why It's Good For The Game

when piping the pipes no longer look like they're connected or different layers don't show another fake pipe.

## Changelog
:cl:
fix: Fixes pipe sprite issues with layering
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
hehe

**Comment by Cyprex** [comment]
Thank you, this bug has been annoying me for a while

**Comment by nicbn** [comment]
Doesn't this mean pipes will no longer be visible in map editor?

**Comment by redmoogle** [comment]
oh hmm let me check

**Comment by redmoogle** [comment]
well shit you're right but this is the fix

**Comment by redmoogle** [comment]
fixed that

**Review by duncathan — APPROVED** [review]

**Pull request merged**
