### PR TITLE
Revert "Material datum chairs & tables and applies materials to all items (Now with less pain for mining & RnD)"

### PR DESCRIPTION
**Pull request by Cyprex**
Reverts tgstation/tgstation#46525
Breaks the game with rads & making lots of stuff explosive. For testmerging until a proper fix is out, since materials datums wasn't testmerged for some reason.

For details, balance dicussion and such please see #46991

### CODE REVIEW

**Comment by Anonmare** [comment]
The radiation is intolerable, it's already hard enough to treat and now it's EVERYWHERE and in everything. Miners constantly come back irradiated to the gils and it's impossible for them to avoid

**Comment by necromanceranne** [comment]
@ExcessiveUseOfCobblestone https://github.com/tgstation/tgstation/issues/46991

For your benefit.

**Comment by FancyCyclops** [comment]
Reminder that radiation used to only happen to engineers.

That's why they have the radiation protection gear.

That's why nobody else has some form of radiation protection at the ready, save science.

**Comment by Qustinnus** [comment]
the ore isn't radioactive anymore. It's explicitely non-radioactive.

**Comment by FancyCyclops** [comment]
> 
> 
> the ore isn't radioactive anymore. It's explicitely non-radioactive.

That's not the problem here. Read.

**Comment by Cyprex** [comment]
Closing in favor of #46994

**Pull request closed without merging**
