### PR TITLE
Component signal feedback/tick usage logging

### PR DESCRIPTION
**Pull request by silicons**
@Cyberboss @MrStonedOne

### CODE REVIEW

**Comment by Cyberboss** [comment]
This feels like it'll be a really heavy thing. Don't forget SendSignal is on tons of low level actions including things like Moved, Entered, Exited, datum/Destroy(), etc...

**Comment by kevinz000** [comment]
tbh this was made for testmerge, just close it if you feel like it'll fuck over performance, as there's like millions of calls and i haven't profiled how much overhead this adds.

**Comment by WJohn** [comment]
could probably be reduced to a supermatter shard.

**Comment by kevinz000** [comment]
@WJohn what?

**Review by Cyberboss — CHANGES_REQUESTED** [review]

**Comment by kevinz000** [comment]
@Cyberboss that check was added because it failed sometimes, when the server was starting. Like two signal sends will happen before GLOB is initialized.

**Comment by Cyberboss** [comment]
I'd like to know what they are, because nothing is supposed to happen
before GLOB

**Comment by ninjanomnom** [comment]
Even a simple var check to see if logging is enabled could easily get expensive fast with how many signals there are. Preferably make this a compile time check

**Comment by kevinz000** [comment]
so i finally had time to be on my computer for a few hours
image

**Comment by kevinz000** [comment]
this was NOT in the in game runtime logs, could only find it via scrolling around on dd.

**Comment by ShizCalev** [comment]
conflict

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Put it behind a define

**Comment by optimumtact** [comment]
stop using the webeditor

**Pull request closed without merging**
