### PR TITLE
Ports storage objects to Initialize

### PR DESCRIPTION
**Pull request by coiax**
All storage objects now populate their initial contents with the
`PopulateContents` proc.

@Cyberboss tells me this is on the path to moving the holodeck to
templates.

- In addition, I refactored cigarettes slightly to have a "brand" var instead of having it rename itself, which caused cigar cases to have "packet" on the end.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
We are scrapping the holodeck anyway

**Comment by coiax** [comment]
we are?

**Comment by KorPhaeron** [comment]
Going to use remies VR sleepers instead I think

**Comment by Kromgar** [comment]
>tfw we move closer from star trek every day

😢

**Comment by octareenroon91** [comment]
But that will kill the oh-so-convenient emergency medical

**Pull request merged**
