### PR TITLE
fixes some spelling

### PR DESCRIPTION
**Pull request by ghost**
cmon now are you fuckin serious

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
You need to recompile tgui you chumboid

**Comment by Armhulen** [comment]
@Cyberboss ??

**Comment by Cyberboss** [comment]
This only changes the tgui source code, you also need to commit the updated tgui.js

**Comment by Armhulen** [comment]
i'm too dumb and busy to learn this right now i'm sorry!

**Pull request closed without merging**
