### PR TITLE
Plexagon Crew Manifest is accessible and free to everyone.

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Plexagon Crew Manifest has been made into a publicly accessible and roundstart installed PDA app instead of being restricted to heads, security and a few odd medical jobs. For this, it lost its major Detomatix resistance which has been added to security records (minor resistance) and status display control (major resistance)

To ensure that noone has to wipe their PDAs roundstart, its size on PDA drives has been halved.

## Why It's Good For The Game

Crew manifest can be easily accessed from the messenger app, but without nice formatting that plexagon has. The app itself does not have any capabilities beyond reading crew manifest and printing it out on paper from consoles, neither of which are something that cannot be already done with ease. I believe this is a remnant from old PDA days and doesn't really deserve to stay.

## Changelog
:cl:
balance: Plexagon Crew Manifest is now a default PDA app for everyone, and is free.
balance: Plexagon Crew Manifest no longer provides Detomatix resistance, but security records and status display control now do.
/:cl:

### CODE REVIEW

**Comment by Crushtoe** [comment]
On the off chance someone is against this, I'd also like to remind that person that anyone can view the manifest at roundstart before they join the game; it's not like the manifest is a super secret only heads know. Anyone who latejoins knows the current staffing from the manifest. Anyone who joins twenty minutes after them knows the state twenty minutes later. There's no exclusivity of information beyond "you did your joining so now the assistants who latejoined after you know more than you do."

**Comment by Dawnseer** [comment]
Roundstart even for borgs, or just crew?

**Comment by ExcessiveUseOfCobblestone** [comment]
I guess the only reason why ou wouldnt want this is because of the updating feature, aka if you get an objective for a miner then you check to see it suddenly changes to say medical doctor then you don't have to check mining you can check medical or the hop office (or bridge/head stuff for an updated manifest).

Personally I think that's pretty minor just trying to understand why its like this currently.

**Comment by SmArtKar** [comment]
> I guess the only reason why ou wouldnt want this is because of the updating feature, aka if you get an objective for a miner then you check to see it suddenly changes to say medical doctor then you don't have to check mining you can check medical or the hop office (or bridge/head stuff for an updated manifest).
> 
> Personally I think that's pretty minor just trying to understand why its like this currently.

Wouldn't that also affect the PDA messenger app? Right now it gives pretty much the same amount of info as crew manifest, its just that manifest is actually formatted.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Wouldn't that also affect the PDA messenger app? Right now it gives pretty much the same amount of info as crew manifest, its just that manifest is actually formatted.

That sounds right, I am too lazy to check 😈

**Comment by alien3301** [comment]
> Roundstart even for borgs, or just crew?

Would be a nice qol to give it to borgs. They have access to sec records anyway so it's not super omega op.

**Comment by ExcessiveUseOfCobblestone** [comment]
Wanna just put it at size 0? If we say the messenger is equivalent and that is size 0 then doesn't really hurt my feefees if we just wanna make this an optional alternative view program.

Not sure what the benefit is that would require opportunity cost over.

**Comment by SmArtKar** [comment]
> Wanna just put it at size 0? If we say the messenger is equivalent and that is size 0 then doesn't really hurt my feefees if we just wanna make this an optional alternative view program.
> 
> Not sure what the benefit is that would require opportunity cost over. 1 would also be acceptable ig if you just wanna go with like the RP reason

other default apps like notepad use memory which is why I gave it a size of 2, but sure I'll remove it

**Comment by ExcessiveUseOfCobblestone** [comment]
> other default apps like notepad use memory which is why I gave it a size of 2, but sure I'll remove it

what the heck lol, I checked messenger and it was free 😭

**Comment by JohnFulpWillard** [comment]
Messenger is free because it's part of the PDA itself, it can't be deleted, downloaded or transferred so making it take space didn't make sense from gameplay perspective.

**Pull request merged**
