### PR TITLE
Reverts #19930

### PR DESCRIPTION
**Pull request by Niknakflak**
Reverts tgstation/tgstation#19930
The gimp suit.

This got in even after the ballgag was removed?
I feel like I need to call @Aranclanos and @Cheridan  and @Giacom for this.

### CODE REVIEW

**Comment by optimumtact** [comment]
Leather club is two blocks down

**Comment by optimumtact** [comment]
I'm sick of puritans like you and goof combing through the game with a fine tooth looking for any possible lewd content.

Go and boil your head in a box

**Comment by TechnoAlchemisto** [comment]
Whenever I make a reference to something niknak invariably goes into fits of heavy breathing and tears.

**Comment by Niknakflak** [comment]
Techno wears gimp suits when he masturbates

**Pull request closed without merging**
