### PR TITLE
Cats have normal genders

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request
This fixes cats from all being male (except for the special cats like runtime and proc) 

## Why It's Good For The Game
Cats work right now.

## Changelog
:cl:
fix: fixed cat genders
/:cl:

### CODE REVIEW

**Comment by IndieanaJones** [comment]
Isn't there a reason cats are like this?  Something with breeding?

**Comment by Pugie** [comment]
There is a canonical reason, all catgirls actually come from female cats.

**Comment by trollbreeder** [comment]
> There is a canonical reason, all catgirls actually come from female cats.

But where do all the catboys come from?

**Comment by Pugie** [comment]
> > There is a canonical reason, all catgirls actually come from female cats.
> 
> But where do all the catboys come from?

i can't say the word but it begins with t

**Comment by interestingusernam3** [comment]
>i can't say the word but it begins with t

Targowica, Ukraine?

**Comment by Couls** [comment]
> i can't say the word but it begins with t

Transylvania, Romania?

**Comment by LemonInTheDark** [comment]
This is a anti catsploshion tool, not a bug.

**Comment by spessbro** [comment]
> This is a anti catsploshion tool, not a bug.

I've tested this and cats have normal babymaking behavior which is capped at 3 children

**Comment by Winterous** [comment]
> 
> I've tested this and cats have normal babymaking behavior which is capped at 3 children

Wouldn't the problem be that those 3 children will proceed to make 3 children with their siblings / parents?

**Comment by Cyberboss** [comment]
Why do I head this project?

**Pull request merged**
