### PR TITLE
Makes some species disease immune

### PR DESCRIPTION
**Pull request by Razharas**
Makes some species disease immune
Fixes https://github.com/tgstation/-tg-station/issues/7775

### CODE REVIEW

**Comment by Incoming5643** [comment]
Since all illness in SS13 is bloodborne you could also just have viruses auto cure on mobs with either NOBLOOD or exotic blood

**Comment by Fox-McCloud** [comment]
isn't there, you know, a VIRUSIMMUNE flag?

**Comment by Incoming5643** [comment]
huh... there is.

Only golems seem to have it right now.

**Comment by Razharas** [comment]
I dont know shit about species and assume it doesnt have virus immune flag since nothing use it for some reason

**Pull request merged**
