### PR TITLE
female clothing variation generalization and lizardbutts

### PR DESCRIPTION
**Pull request by Incoming5643**
Reworks the female clothing variation proc into it's most generalized version yet: generate clothing. It now uses bitflags to allow for multiple alterations at once if needed. This greatly loosens restrictions on what a mob can look like.

In light of that I've made a filter to let lizardspeoples tails be properly visible from the south finally

d10_icon

This filter applies for suits too; fuck the realism, this is both easier to implement and funnier.

### CODE REVIEW

**Comment by Incoming5643** [comment]
Also now that it can be seen clearly, that tail looks like it's positioned too low on the sprite

**Comment by paprka** [comment]
that tail is messed up, there's a random grey corner running through it?

**Comment by Incoming5643** [comment]
there's no female variation on exosuits, it only checks for the lizard tail

**Comment by paprka** [comment]
Jesus christ seriously isn't there a better way to do that

**Comment by Incoming5643** [comment]
It's the only way I've seen to selectively layer a body part over some clothing but not EVERYTHING, yes.

Remember that the way the code works the slower bits are only done the first time the uniform is donned by anyone on the server, any time after that it just pulls up the old icon from the list. It doesn't have to to be the most optimized thing in the world.

---

d10_icon

Here's the lizard back sprite with the masking layer superimposed, you can see the L, it's just how the tail is drawn.

If anyone wants to resprite lizard asses to move the tail up it could be fixed.

**Comment by Dorsisdwarf** [comment]
:-1:  if it makes lizard tails stick out of exosuits, that looks bad.

**Comment by WJohn** [comment]
The tail and snout really ought to be overlays that get hidden under the right conditions.

**Comment by Incoming5643** [comment]
I can make it work to have parts that "bulge" out of humanoid mob models be hidden under certain circumstances. I just honestly didn't think people would want that. I generalized the fitted var to clothing for just such a situation, I just didn't think that's what people would want.

**Comment by Dorsisdwarf** [comment]
Would it be possible to make overlays that go over the tails on hardsuits instead?

**Comment by Incoming5643** [comment]
What I would do/am currently doing is creating a mask in the shape of a standard raceless human body where any pieces outside the standard frame would be clipped from the mob layer when the flag was set by the exosuit. I'm going to have to manually set fitted for all types of exosuits to make sure this only happens when it logically should (like for example, it shouldn't happen with the apron)

**Comment by Incoming5643** [comment]
Status update: Getting this to work is infuriating

**Comment by Incoming5643** [comment]
Trashing this, #7884 is a better version

**Pull request closed without merging**
