### PR TITLE
[s] Just as planned

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by RandomMarine** [comment]
What did he mean by this?

**Comment by MrPerson** [comment]
Everything's falling into place

**Comment by Cebasiz** [comment]
weren't you the guy that was grousing about non-descriptive meme PRs

isn't this exactly that

**Comment by Shadowlight213** [comment]
All going according to plan. Soon singulo shall be under the admin's jurisdiction and all dissent shall be silenced.

**Pull request closed without merging**
