### PR TITLE
Gremlins

### PR DESCRIPTION
**Pull request by ghost**
f00da66a-f6bc-11e6-9a19-125847d66c25

Despite their looks, gremlins have the potential to become the most destructive force that you will ever encounter on this space station. Unlike other monsters, which just eat you, gremlins will set up the singularity engine and then release it, flood the station with N2O, or lock you in a room and shock the door

Gremlins have 20 hp so they die very quickly from any sort of combat activities

Gremlins possess the ability to manipulate some machinery and computers. You'll most commonly see them screwing up APCs, air alarms and airlocks, but they can do much more - for example use  auto/protolathes, manipulate power and atmospherics equipment...

:cl: Thefastfoodguy
add: Gremlins
/:cl:

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
WOOPS, WRONG REPO

**Comment by Armhulen** [comment]
LOL

**Comment by Anonmare** [comment]
Roasted

**Comment by calzilla1** [comment]
What a nerd

**Pull request closed without merging**
