### PR TITLE
[DNM] [Delta] Cleaned up thermo filter line in SM room

### PR DESCRIPTION
**Pull request by ShizCalev**
Cleaned up looping pipes.
Added gas pump so the filter actually has a point.
Moved redundant gas meter to more useful location.
Fixed typo.

### CODE REVIEW

**Comment by Penguaro** [comment]
Any chance you can throw a final picture up?

**Comment by ShizCalev** [comment]
16508543_1291963534198715_7669617668260091754_n-1

**Comment by ShizCalev** [comment]
3kozmjs

**Comment by lordpidey** [comment]
I don't see the point of this loop?  Why would you want to cool only a specific portion of the gas, and then recombine  it, rather than just cooling the original gas.

**Comment by Penguaro** [comment]
The gas pump you added was unnecessary, the pump at the top would pull out the gas regardless. Realistically, using the filter like this is kind of an odd way of diverting out gas to a refrigeration bypass. Basically any chilled air (or heated?) will remix with the non-treated temperature at the other end creating an average temp of the two. Since this is coming from the engine, it's not going to be all that cold.

**Comment by Penguaro** [comment]
@lordpidey Keep in mind, this isn't that different that how Delta was before.

@ShizCalev This section should just be redone, not tweaked.

**Comment by lordpidey** [comment]
@Penguaro

No, the pump on the side has a purpose.  Without that pump, the filter would be pumping both sides out into the same pipenet, negating the entire point of the filter.

**Comment by Penguaro** [comment]
Oh I see, it's intended to stop gas, not pump it.

**Comment by lordpidey** [comment]
What is the point of the gas pump directly in front of the filter?  You can just turn the filter on or off, no need for a pump there.

**Comment by ShizCalev** [comment]
That's how it is on live right now.

Might as well remove it. Give me one sec.

**Comment by Penguaro** [comment]
In my opinion, I would ditch the gas filter altogether and just make two lines; One for freezer/heater and the other to bypass that. I don't play on delta ever so I'm not terribly invested in the outcome of this. Good luck.

**Comment by ShizCalev** [comment]
My git client's completely fucked and won't even revert my fuckup. sweet.

**Pull request closed without merging**
