### PR TITLE
R.I.P. AsteroidStation 2011-2015

### PR DESCRIPTION
**Pull request by CorruptComputer**

### CODE REVIEW

**Comment by Anonus** [comment]
rip ASS teroid
worst station, can go

**Comment by Supermichael777** [comment]
Context.=?
Kinda sad i never got to play this. Is it unmaintained?

**Comment by SconesC** [comment]
goodnight

nothing of value lost etc

**Comment by ike709** [comment]
besides the fact it wasn't maintained much, why all the hate? Asteroid station was my second favorite map.

**Comment by SconesC** [comment]
horrifying designed departments with wasted space, awful layouts, and generally inconvenience-causing shit (1x1 maint hallways for loooong stretches, perma being the most insecure thing in the world, etc)

**Comment by Firecage** [comment]
I will miss this, just wish it was hosted more often.

**Comment by CorruptComputer** [comment]
The map is unmaintained and sadly doesn't even open in dream maker any more. It was actually my favourite map but now it is a broken mess. If someone would rather fix it, put a PR up and I'll close this.

**Comment by optimumtact** [comment]
nice way to buff the line change count

:+1:

**Comment by tedward1337** [comment]
;__;7

**Comment by Dawgas** [comment]
this is good, we should be actively pruning shitty things that aren't up to actual standards, not whatever bullshit we call standards nowadays

when do we remove things that are far beyond the scope of this pr

**Comment by CorruptComputer** [comment]
@Dawgas When you put a PR up. Don't expect other people to do stuff that you want.

**Pull request merged**
