### PR TITLE
MAKED SNIPERS NOT FIT IN BACKPACKS

### PR DESCRIPTION
**Pull request by jughu**
Ever saw somebody putting a whole sniper in their backpack?

:cl: Jughu
tweak:Backpacks can't hold snipers anymore
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
SNIPERS ARENT SO BAD AFTRRALL

**Comment by jughu** [comment]
Ok i change mind

**Comment by jughu** [comment]
No anevermind

**Comment by Jordie0608** [comment]
"An epic tale 5/7" - New York Times

**Comment by kevinz000** [comment]
GO SNIPE YOURSELF

**Pull request closed without merging**
