### PR TITLE
Replaces the Crème de Menthe in Quadruple Sec with Grenadine because mint with triple citrus tastes awful and Grenadine = RED

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Replaces the Crème de Menthe in Quadruple Sec with Grenadine because mint with triple citrus tastes awful and Grenadine = RED

## Why It's Good For The Game

I'm drinking this right now and it's great

## Changelog

:cl:
balance: Replaces the Crème de Menthe in Quadruple Sec with Grenadine because mint with triple citrus tastes awful and Grenadine turns drinks red
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Believe it or not this is a completely valid justification for the change

**Comment by Cheshify** [comment]
Best part is, the drink isn't any easier or harder to make. This is just a perfect, simple change that makes Quadsec a drink I ACTUALLY want to try. Fantastic PR.

**Comment by timothymtorres** [comment]
Bonus points - Grenadine closely resembles grenade... coincidence?  I think not!

**Comment by Livrah** [comment]
It should reduce alco level of quad.

**Comment by anconfuzedrock** [comment]
Do you have any proof that you're drinking this right now?

**Comment by RedSentry27** [comment]
> Do you have any proof that you're drinking this right now?

clearly you're not in the manuel discord
he posted an image there

**Comment by EricZilla** [comment]
Listen its the sec liver that makes it taste good

**Comment by Mothblocks** [comment]
wow, i was not expecting that

**Comment by necromanceranne** [comment]
Oh man he charged himself full price for this PR. Dedication to the cause of good drinks I suppose.

**Pull request merged**
