### PR TITLE
Moves a rivet wall, corrects typos

### LINKED ISSUE #19399: someone dun fucked up
ss 2016-07-19 at 01 58 04

Probably will be fixing this myself while I'm editing basically every map but incase I don't

### LINKED ISSUE #23979: Random rivet wall on lavaland.
Why?

Coords (x,y,z) are 37, 42, 5.

### PR DESCRIPTION
**Pull request by Arianya**
:cl: Arianya
tweak: The Labour Camp rivet wall has been removed!
spellcheck: Fixed some typos in Prison Ofitser's description.
/:cl:

Fixes #23979 
Also Fixes #19399 because no one ever actually fixed that.

Prison Ofitser's description:

> Powered by tears and swet of laborer.

to

> Powered by the tears and sweat of laborers.

The rivet wall has been moved so that it is juuuust in view of the prison shuttle. The place where it originally stood has been replaced with a normal lavaland floor.

There @KorPhaeron I ~~didn't remove your rivet wall waifu.~~ demolished your rivet wall waifu.

Yes I used the map merger no I don't know why it still generated 68k deletions

### CODE REVIEW

**Comment by WJohn** [comment]
Nice map merge.

**Comment by optimumtact** [comment]
you have converted the map to DMM, so in this case you appear to be the dingus?

**Comment by optimumtact** [comment]
you must close dreammaker before using the map merger and comitting your changes

**Comment by Arianya** [comment]
@optimumtact I tried running TGM but it seemingly did nothing (huge numbers of additions and deletions)

I am redoing it now and will use TGM.

**Comment by Arianya** [comment]
As I saw when I originally used TGM, 68k on each side...

**Comment by RemieRichards** [comment]
@Arianya first time conversions to TGM do causes huge diffs.
Check the old version of the map, if the first line doesn't mention dmm2tgm, then this run was this map's first conversion.

**Comment by Arianya** [comment]
The old version has the dmm2tgm first line too.

🤷‍

**Comment by RemieRichards** [comment]
@Arianya I know what it is, the lavaland map is old, so it'll be @xxalpha's updated mapmerger doing a dictionary cleanup, which also produces huge diffs on occasion.

**Comment by Arianya** [comment]
So long as its not my fault I'm okay with it.

**Comment by Arianya** [comment]
@WJohn This needs "Map Edit" too

**Comment by xxalpha** [comment]
It has not been trimmed in this commit, it does not have the header to indicate it.

**Comment by Jordie0608** [comment]
I predict in the future someone will open an issue about a stray rivet wall being just in view of the prison shuttle; just remove it.

**Comment by AnturK** [comment]
Map diff is still big, without any sign of trimming. Something have went wrong.

**Comment by Arianya** [comment]
@AnturK I've retried the map merge several times without any change. I'm happy to try and resolve this but I don't know the way forward.

@Jordie0608 Sure, if that's what's preferred.

**Comment by xxalpha** [comment]
Could it be line endings?

**Comment by Jordie0608** [comment]
Indeed it is, the codebase's file is LF and yours is CRLF.

**Comment by xxalpha** [comment]
You can use notepad++ to replace the line endings, it's a feature.

**Comment by Arianya** [comment]
I'll look at correcting this when home, as well as removing that dumb rivet wall.

Whats caused the change from LF to CRLF in the first place? I only ever opened the map file in Dream Maker.

**Comment by xxalpha** [comment]
Probably on commiting, I am not sure.

**Comment by AnturK** [comment]
Please swap the line endings and this is good to go.

**Comment by Arianya** [comment]
@AnturK Should be good to go. Sorry about the delay.

@xxalpha @RemieRichards @Jordie0608 Thank you for all your help in solving this 👍

**Comment by Arianya** [comment]
I should note I also removed the dumb rivet wall entirely.

Here

**Comment by optimumtact** [comment]
RIP rivet wall, died too soon

**Pull request merged**
