### PR TITLE
Remove /datum/game_mode, we SSdynamic now [again]

### PR DESCRIPTION
**Pull request by Mothblocks**
I don't remember what was hard about this last time it took me like 20 minutes this time so I'm scared.

Removes dynamic simulations, only I have used them and it's a lot more complicated now with this. I plan on making Dynamic simulations a part of moth.fans anyway

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
are we free at last

**Comment by Cyprex** [comment]
Bubberstation downstream here, we use dynamic simulations

**Comment by StrangeWeirdKitten** [comment]
> Bubberstation downstream here, we use dynamic simulations

I don't need them anymore

**Comment by Mothblocks** [comment]
Dynamic is likely to receive a lot of significant changes in the coming months (as per Dynamic 2024 doc) so maintaining the dynamic simulations alongside that is not particularly feasible, but as I said a simulator in moth.fans (repo-agnostic) is a part of that

**Comment by Mothblocks** [comment]
Haven't seen any issues

**Pull request merged**
