### PR TITLE
Ghosts are now alerted when explosions happen so they can go look at the aftermath.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

See title.

## Why It's Good For The Game

Explosions are interesting for observers, and they're cool to look at the aftermath of for observers. Generally, explosions are interesting, and therefore observers should be able to jump to them.

## Changelog

:cl:
qol: Ghosts are now alerted when explosions happen so they can go look at the aftermath.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
the explosions that are interesting (c4, syndie bombs) are already shown to ghosts, we dont need a notification for everytime the staff of storms is used or an assistant puts water and potassium in his stomach to reset his chems

**Comment by TemporalOroboros** [comment]
> 
> 
> the explosions that are interesting (c4, syndie bombs) are already shown to ghosts, we dont need a notification for everytime the staff of storms is used or an assistant puts water and potassium in his stomach to reset his chems

Even so, observers should probably be notified if there's a 'cap somewhere on the station.

**Comment by Iamgoofball** [comment]
There are plenty of explosions that are important that aren't C4 or syndie bombs.

**Comment by peptron1** [comment]
it might help to add a minimum explosion size before it notifies the ghosts.

**Comment by oklews** [comment]
> it might help to add a minimum explosion size before it notifies the ghosts.

A minimum of one dev is reasonable, right?

**Comment by peptron1** [comment]
> > it might help to add a minimum explosion size before it notifies the ghosts.
> 
> A minimum of one dev is reasonable, right?

that would make it only show ghosts fairly sizable explosions yeah.

**Comment by CameronWoof** [comment]
Blacklisting gibtonite explosions would probably boost the signal/noise ratio on something like this considerably, as well.

**Comment by Iamgoofball** [comment]
Gibtonite explosions are pretty big and relevant when they're on station.

**Comment by CameronWoof** [comment]
> Gibtonite explosions are pretty big and relevant when they're on station.

That's fair--and on reflection, blacklisting a source like that doesn't seem like an easy addition. Am I right that this would notify of any explosion, regardless of the z-level it happened on? Is there a simple way to restrict it to only station z-levels?

**Comment by Watermelon914** [comment]
could you make sure to test this so that it works? I don't want to merge something that could be broken right out the gate.

**Comment by KittyNoodle** [comment]
Gibonite explosions should be blacklisted when they are in the rock, but not item form, that should be broadcasted

**Comment by tralezab** [comment]
i want this to happen so i'm removing stale but goof you better resolve that conflict and test the pr

**Review by tralezab — CHANGES_REQUESTED** [review]
*sorry to whomever was pinged* Mann add a min explosion side to be announced

**Comment by tralezab** [comment]
i... copied my discord ping to you and i have no idea who i actually just pinged

**Comment by blutarch** [comment]
> i... copied my discord ping to you and i have no idea who i actually just pinged

It was me. No sweat.

**Comment by Iamgoofball** [comment]
this just doesn't work

**Pull request closed without merging**
