### PR TITLE
Removes sanitize from ghost say

### PR DESCRIPTION
**Pull request by Cyberboss**
This fixes things but may break others

### CODE REVIEW

**Comment by AlexTheSysop42** [comment]
Just wait until someone abuses it to make an admin use everyone is the traitor or popup 20 goatse/rickroll windows for every person in deadchat

**Comment by fludd12** [comment]
What is sufficiently broken that we are removing sanitization from ghost chat completely...?

**Comment by AnturK** [comment]
Please explain, because as said this makes no sense.

**Comment by DaxDupont** [comment]
What

**Comment by Cyberboss** [comment]
This ends up `html_encode`ing dsay messages when using .d Twas @optimumtact's suggestion to just let goonchat sanitize it

**Comment by AnturK** [comment]
And how exactly goonchat is supposed to differentiate span added by player and span added by game ?

**Comment by LetterN** [comment]
imagine the griffing possibilities

**Pull request closed without merging**
