### PR TITLE
Fixes some spelling errors and tweaks some fluff text.

### PR DESCRIPTION
**Pull request by harmonyn**
LOOK GUYS IT'S MY FIRST COMMIT EVER #whoa #wow 

featuring the COMPLETELY CRITICAL GAME-TRANSFORMING CHANGES of fixing a few of your spelling errors, specifically in the wall/falsewall code, because it was the first one I noticed in game idk

also tweaked some flavor text, namely a mineral wall that was inconsistent with the other descriptions and some fluff. 

pretty self-explanatory, as this is mostly practice to see if I can into git, however if I fucked shit up please let me know

### CODE REVIEW

**Comment by xxalpha** [comment]
Good job making your first PR and not fucking up git. :+1:

If you need git help jump in #coderbus, or coding help, or do it anyways.

**Comment by Aranclanos** [comment]
worst ray

**Comment by phil235** [comment]
:+1:

**Comment by Iamgoofball** [comment]
false wall code is horrible

**Pull request merged**
