### PR TITLE
Meta whiteship redesign

### PR DESCRIPTION
**Pull request by WJohn**
Redesigned the white ship for metastation, this one's a salvage/cargo vessel! The salvage pod is currently missing, however, as it doesn't work right now. I'll add it further down the line. This ship is also filled with a few syndies protecting it, one of them is ranged, the others are unarmed melee.

(slightly outdated, doesn't show the syndies)

:cl: WJohnston
add: Redesigned the metastation white ship as a salvage vessel.
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
Yeah, the shutters are a great idea. Maybe they could be segmented so that opening them won't depressurize the whole bay at once?

**Comment by Tlaltecuhtli** [comment]
put tiny fans under the shutters so they dont lose oxygen also can you remove the food processor and put the fridge there instead?

**Comment by WJohn** [comment]
Actually instead of either of these suggestions, I was thinking making it act like centcomm shuttle shutters, where they only open as many as needed when bordering something. I'll need that to be added further down the line, though.

**Comment by ninjanomnom** [comment]
No more fucking tiny fans

**Comment by Militaires** [comment]
beautiful

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
