### PR TITLE
TGUI Limbgrower + Limbgrower refactoring and design expansion

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Gives the limbgrower a neat TGUI interface instead of the wonky HTML it used in the past. (This is my first TGUI project so it might be bad.)

image
image

- Refactors the limbgrower to modernize the code. Now, the limbgrower can accept any type of reagent in limbgrower designs.

- Adds simple plumbing demand to the limbgrower, so you can pipe synthflesh into it.

- Adds monkey tails, felinid ears and tails, lizard digitigrade legs, lizard tongues, fake lizard tails (unusable in lizard-wine and similar recipes), plasmaman organs, and ethereal organs (minus the heart) to the limbgrower via limbgrower design disks. These disks can be printed from the medical lathe once the required technology has been researched.

- Adds a technology node to unlock the limbgrower design disks after advanced biotech, xenoorgan biology. In the future, this could have an experiment requirement - maybe to scan multiple types of species.

## Why It's Good For The Game

The limbgrower is very outdated and uses a 5 year old UI. It hardly prints any organs or limbs and it is quite useless. A fresh UI and some additional limb designs can breathe some life in this forgotten machine, and allow medbay to get creative with their frankenstein-ian creations. 

## Changelog
:cl: Melbert
refactor: TGUI Limbgrower
refactor: Refactored the limbgrower to modernize the code and allow for more types of designs.
add: Limbgrower design disks. Science now has a new tech node after advanced biotechnology, "Xenoorgan Biology" which allows medbay to print new designs for the limbgrower, including various felinid, lizard, plasmaman, and ethereal organs.
add: The limbgrower now supports plumbing ducts.
/:cl:

### CODE REVIEW

**Review by stylemistake — COMMENTED** [review]
Edited the UI file, removed the flex things because they were unnecessary.

Right click on source code in VSCode -> Source Actions -> Organize imports.

Overall looks very good for your first tgui attempt! :+1:

**Comment by Qustinnus** [comment]
ethereal hearts and organs should not be growable because it has balance concerns and it doesn't fit the lore for ethereals well.

**Review by stylemistake — APPROVED** [review]

**Comment by Qustinnus** [comment]
oh i see they're not included now, but I'm worried someone will change that in the future but Ill yell at them once that time comes.

**Comment by necromanceranne** [comment]
Frankensteining alien organs into people is hardly a balance concern, Qust. Limb growers are not roundstart machines and relies on several other people to actually acquire, in no small part to experisci if anything.

**Comment by Qustinnus** [comment]
"its not roundstart so its not a balance concern" is not going to convince me. I specifically made it an organ against my will because I don't want people getting these super easily. And again, they are literaly setpieced as not being producable.

**Comment by necromanceranne** [comment]
Is it specifically the revival ability you're worried about people getting? You could have attached it to the brain, which isn't possible for people to steal, and would allow ethereals to keep that ability solely to them.

**Comment by Krysonism** [comment]
This heavily devalues xeno organs, making them a lot feel cheap and a lot less special.

We should increasing scarcity and be removing these types of machines that print cool or useful stuff for little to no cost instead of expanding them.

**Comment by MrMelbert** [comment]
All the special xeno organs added are locked behind an expensive tech node that is itself locked behind advanced biotechnology, a tech node that needs an experiment done. On top of that to print the more diverse xenoorgans you need additional reagents supplied to the machine. I don't think this will affect the scarcity of xenoorgans much at all, it just gives a late-game way to have some organs replaced.

**Comment by Qustinnus** [comment]
@necromanceranne but its not their brain thats supposed to be doing that and the entire point of it was that people could take the organ from someone else. Being able to mass-produce it however is cringe.

**Comment by brotherbeyondd** [comment]
I swear felinid tails are worth a shitload in cargo?

**Comment by MrMelbert** [comment]
> 
> 
> I swear felinid tails are worth a shitload in cargo?

Cat ears sell for 200 credits and cat tails for 250, if cargo wanted to mass-produce and sell cat parts they can already buy cats to breed

**Pull request merged**
