### PR TITLE
Fixes silicons being unable to disable holodeck safeties

### LINKED ISSUE #62641: AI can't change holodeck safeties
Reporting client version: 514.1561

## Round ID:
[172637](https://scrubby.melonmesa.com/round/172637)

## Testmerges:
- [Revert "Locker based combat, evolved. (#60000)"](https://www.github.com/tgstation/tgstation/pull/62558)
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)

## Reproduction:
1. Be the station's AI.
2. Move your camera to the holodeck.
3. Try to turn off the safeties on the holodeck console. You cannot.
4. (optional) attempt to change the holodeck sim to any of the normally available ones. You can!

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request
read the title

## Why It's Good For The Game
they're supposed to be able to do this
Fixes https://github.com/tgstation/tgstation/issues/62641

## Changelog

:cl:
fix: Silicons can disable holodeck safeties again.
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
this was originally broken in https://github.com/tgstation/tgstation/pull/62549 but it was said to fix it in a different pr so it's good this is being fixed now

**Comment by SuperNovaa41** [comment]
No it wasn't

**Comment by SuperNovaa41** [comment]
It was broken in https://github.com/tgstation/tgstation/pull/62563
that pr added a single line of whitespace to this

**Comment by TheBonded** [comment]
> It was broken in #62563 that pr added a single line of whitespace to this file

ahhh, my bad.

**Review by Kylerace — APPROVED** [review]

**Pull request merged**
