### PR TITLE
Optimizes Box Grav Gen

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

So box grav gen is fixed, but its not ideal. Its seperate from the powernet, so once the SMES goes down, so does grav. SMES is now connected to powernet, it recieves power, but does not give. Heres a pic of it, with the 3 engine SMES sending at 50kw each.
box grav

## Changelog
:cl:
fix: Box Station's grav gen has now been optimized.
/:cl:

### CODE REVIEW

**Comment by TetraK1** [comment]
> The grav gen one on box Im not that sure about, but on other maps there is a generator you can hook up to it to keep grav gen running if power drops without being affected by the entire station. This one, again, should probably not be connected roundstart to allow for grav to drop and have to be fixed. Add a pacman and some plasma, look at how meta/delta does it

From the other pr

**Comment by Tharcoonvagh** [comment]
Why did you disconnect the SMES?

**Comment by Bokkiewokkie** [comment]
> Why did you disconnect the SMES?

This, the SMES is very important for the grav gen as it allows the gravity to stay on for a while if the power dies, isn't set up or if the cables get disconnected (the last of which is quite common on box).

**Comment by wesoda25** [comment]
Actually I think I did this wrong, but not in the way you guys think. I’ll do some testing later.

**Comment by wesoda25** [comment]
Ok so this is what box is with my changes: 
image
SMES is already connected to APC, I didn't even touch that.

**Comment by Tharcoonvagh** [comment]
77815668-231fa000-7093-11ea-8ea5-088f8fe8750c
🤔

**Comment by wesoda25** [comment]
it goes through the back

**Comment by wesoda25** [comment]
Are grav gens actually intended to be completely separate from station powernet, and go down once their SMES runs out of energy? Box as it is is basically identical to Meta, does Meta grav gen eventually have to be hooked up to a generator/station powernet?

**Comment by wesoda25** [comment]
OK I think I figured this out - you need to connect the powernet to the grav gen SMES via its terminal, and then have the SMES connect to the APC - SMES won't send power to station, only recieve, and thus only the APC has access to this power. Box doesn't use this system either, meaning I'll need to update it I think

**Comment by wesoda25** [comment]
I'm just gonna make an entirely new PR, and do this for all the maps which don't have it.

**Pull request closed without merging**
