### PR TITLE
Resprites the Chief Medical Officer

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin. This is a testbed for a new jumpsuit change and overall aesthetic overhaul of the medical department. Thanks to @axietheaxolotl for creating these!
This PR also adds a beret for the CMO as they missed headwear previously.

image

This PR *also* changes the appearance of nitrile gloves (please forgive my airheadedness, the sets do not spawn automatically with nitriles).
image

## Why It's Good For The Game
Initially, I was going to use the regular pastel blue that the CMO was originally known for, until me and Viro came to experiment with using turquoise, to give the CMO a more surgical aesthetic to their clothing. The benefit of that is that they'll look more distinct than they were already, signifying from a glance that they're a top surgeon!

## Changelog

:cl: Axietheaxolotl, PositiveEntropy
expansion: Adds a beret for the Chief Medical Officer!
imageadd: Nanotrasen has now tackled overhauling the visual aesthetic of the Chief Medical Officer, changing their jumpsuits and labcoat, and altering their original pastel blue color to turquoise! 
imageadd: Nitriles now look much more rubbery than before!
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
Leave my Beverly Crusher drip alone!!

**Comment by drIcepop** [comment]
I feel like CMO should be a darker shade of blue.

**Comment by GuillaumePrata** [comment]
The PR that gave every job a Beret was a mistake, now every job without an unique headwear just gets one to fill the void.

**Comment by Imaginos16** [comment]
> The PR that gave every job a Beret was a mistake, now every job without an unique headwear just gets one to fill the void.

So the problem is the beret?

**Comment by GuillaumePrata** [comment]
> So the problem is the beret?

For me, personally, yes.
I know it is kinda petty but every job just getting the same headwear muddies the place.
I can't think of much for the CMO other than an unique Nurse hat... which doesn't make much sense but Beret spam needs to stop somewhere.

**Comment by Imaginos16** [comment]
> > So the problem is the beret?
> 
> For me, personally, yes. I know it is kinda petty but every job just getting the same headwear muddies the place. I can't think of much for the CMO other than an unique Nurse hat... which doesn't make much sense but Beret spam needs to stop somewhere.

I do agree with you to the extent of the beret spam, but then again, there isn't much... Good headwear that would fit a CMO. A nurse hat already exists, but that is gonna be for a different resprite, and its not really associated with surgeons aesthetically. If you *can* provide an actual good example of something a doctor or surgeon would wear, I could see what I can do.

**Comment by Imaginos16** [comment]
Since I wasn't provided one, I shall make my own instead, stay tuned.

**Comment by axietheaxolotl** [comment]
> The CMO's labcoat is made to be the same blue as the coat Beverly Crusher wears in Star Trek: TNG, atleast i think so.

If you actually look at what the supposed reference, the one I made looks much more like it. At least colour wise. It's more accurate than pastel blue.
image

**Comment by CRITAWAKETS** [comment]
> If you actually look at what the supposed reference, the one I made looks much more like it. At least colour wise. It's more accurate than pastel blue. 

There are what seems to be two or three coats that are worn, some with a tiiny bit of a teal side, i'll give it that, but its mostly just blue.

...That said the one in your picture just looks teal on the shadowed side because it's in a very yellow room.

**Comment by jughu** [comment]
give the beret a chance to fall off while doing surgery, and then the beret falls into your chest organs and shit and the cmo closes it up and now u have a beret in ur chest

**Comment by Imaginos16** [comment]
Due to how hair works currently, I'll have to give some time on my planned hat for the CMO. It was supposed to be a head mirror, a piece commonly associated with surgeons, but due to how hair layers, its really really difficult to make it look good for both bald and haired people.

image

I have them saved pending a hair refactor however, so be my guest.

**Comment by Sealed101** [comment]
not everyone has to have headwear, especially berets
the palette shift just feels weird but that might just be me being used to the old colors
nitrile resprite is good though, the gloves needed some love

**Comment by retlaw34** [comment]
Looks great! Are the CMO's shoes blue or is it just in the picture?

**Comment by Imaginos16** [comment]
> Looks great! Are the CMO's shoes blue or is it just in the picture?

By default they use the blue shoes! Its from an older PR and its a trait they share with the paramedic

**Comment by Dorsisdwarf** [comment]
That labcoat is absolutely _hideous_. It's ugly, contrasting, and looks like a 2010 grandfather sprite that was recoloured in 5 seconds with a hue slider.
The jumpsuit is quite nice though!

**Comment by retlaw34** [comment]
> > Looks great! Are the CMO's shoes blue or is it just in the picture?
> 
> By default they use the blue shoes! Its from an older PR and its a trait they share with the paramedic

If i could suggest something, you should change it to a darker color, the shoes blue doesn't look great with the cmo blue

**Comment by optimumtact** [comment]
If you're not willing to say it nicely, don't say anything at all you washed up boomer
@Dorsisdwarf

**Comment by Serxule** [comment]
everything looks good except for the labcoat, looks low effort and like a reskin of the HoS coat, also a darker blue would be good

**Comment by Mothblocks** [comment]
I'm not one to mind references, but surely an entire *color scheme* is a heavy ask to require spriters conform to.

These look pretty, I hope someone gets to the cloaks soon.

**Comment by Serxule** [comment]
oh also, the normal blue shoes dont fit at all with the rest of it, could just have them be plain white shoes, since thats easier

**Comment by VladinXXV** [comment]
Keep the classic light blue, the turquoise doesn't look good.
Gloves are pretty light considering they're nitriles but there are SOME nitriles that looks like that. Most do not, though. Might be good to darken them a little bit.
image

**Pull request merged**
