### PR TITLE
[WIP] CorruptComputer waves, AsteroidStation shudders back to life

### PR DESCRIPTION
**Pull request by CorruptComputer**
It's been 2 years, but it has returned and is better than ever! I've swapped some things around so they make more sense, updated it to actually work with the new code, and am currently re-doing maintenance to be more sensible.

Screenshot: (too large for GitHub and imgur for some reason)
https://cdn.discordapp.com/attachments/129145765049139200/385290291181256704/AsteroidStation.png

Feedback is welcome, and if I missed anything just let me know.

Never done this automatic changelog before, if I didn't do it right just yell at me.
:cl:
add: AstroidStation as a playable map
/:cl:

### CODE REVIEW

**Comment by JJRcop** [comment]
AsteroidStation has died at *least* twice, are you able to maintain it again?

**Comment by CorruptComputer** [comment]
Yeah I am able to maintain it now, and I was thinking about adding the mining ferry to lavaland as an option as well. But, as of right now the only way to lavaland is through the Aux base Construction.

**Comment by optimumtact** [comment]
I don't believe we should add more than the current set of maps, if anything I'm in favour of reducing the set to less

It's a maintainability burden and I find that outside of meta/box most of the maps are hardly picked anyway

**Comment by ike709** [comment]
Aside from meta and box, asteroidstation is way better than most if not all of the current maps.

**Comment by ike709** [comment]
Also you need to change all of the computer directions now that directional sprites exist.

**Comment by Shadowlight213** [comment]
O shit

**Comment by CorruptComputer** [comment]
@ike709 Ah, you're right, doing that now.

**Comment by ACCount12** [comment]
This basically undoes all the hard work put into making the map internals manageable. Cables still have `d1` and `d2` set, disposal pipes have `icon_state`, and there are likely many more things like that.

I agree with @optimumtact in that we need less maps, not more.

**Comment by Armhulen** [comment]
this is good, maybe we should be putting more players out of their comfort zone into new maps instead of caving and giving them the same map over and over

**Comment by CorruptComputer** [comment]
Quick draft of lavaland shuttle: image

@ACCount12 As for cables still having `d1` and `d2`, are those vars just unused and safe to remove?

**Comment by Armhulen** [comment]
>I don't believe we should add more than the current set of maps, if anything I'm in favour of reducing the set to less

why, variety is good

>It's a maintainability burden and I find that outside of meta/box most of the maps are hardly picked anyway

he said he'd maintain it, and that's really a problem with admins caving to box and meta not that i blame them

**Comment by optimumtact** [comment]
It's not a maintainability burden for him that I'm concerned about, it's for everyone else who has to touch a map to repath or update things.

The impact a map has is not limited to the map designer alone.

**Comment by Buggy123** [comment]
I'm not 100% sure how I feel about having asteroid mining back. On one hand, I suppose it's a interesting, peaceful alternative to Lavaland. On the other, I feel like a _Lavaland station_ would be **fucking amazing**.

**Comment by optimumtact** [comment]
Buggy this is a station map to replace the station, nothing to do with lavaland, which should still exist

**Comment by CorruptComputer** [comment]
@optimumtact It is a well played map though, and when it was still alive from what I remember it was fairly popular. Maybe not as extensively playtested as BoxStation, but that's fairly normal for any non-default map. If there are bugs with a map, or something breaks with updates it should be up to the maintainer to fix it, and if they don't in a timely manner just remove the map. I don't really see your problem with adding another map if it is going to be played, maintained, and updated regularly.

**Comment by optimumtact** [comment]
Because unlike you I don't believe that will be the case, maybe I'm bitter and twisted and hurt by past experience or maybe you're naively optimistic.

**Comment by Buggy123** [comment]
No, I get that, I'm just saying that the original idea, "hey, lets put the station inside the mining asteroid", is kind of outdated now that not only is the mining asteroid _gone_, but mining has been almost completely revamped from when it _was_ still around.

Of course, there's way more significance to this than just miners, I was just saying that having a Lavaland Station would be amazing because of how absolutely insane Lavaland can be compared to the tranquil asteroid. I still support the addition of this map, I think having a huge area of rock outside adds a _very_ interesting mechanic, a sort of weird maintenance-space combination where its easier to expand or build or hide in the asteroid than in space, but harder than in maint.


Also, I'm fairly certain that the asteroid emergency shuttle will break TComs every time it lands, because it'll overlap the APC if not some of the machinery.

**Comment by optimumtact** [comment]
also you don't need to ping me every time you comment, I can ascertain that a comment is meant for me

**Comment by optimumtact** [comment]
@ike709 in regards to your comment, which I somehow missed

I'm not saying this map can't be merged, but I'd much prefer it replaced an existing map

**Comment by ike709** [comment]
It can replace probably any map other than box or meta and I doubt anyone would mind.

**Comment by ACCount12** [comment]
@CorruptComputer d1 and d2 are supposed to be phased out. They are set by init code based on icon_state.

**Comment by Okand37** [comment]
I would like to be confident in saying that I believe delta has some place in the rotation list, or at the least that some people actively enjoy it enough for it to be there. I can't speak on pubby's behalf for his map, though I can state that I never quite had the chance to finish omegastation-but it seems fruitless to replace a lowpop (0-to-15~) map with a medium/highpop one.

**Comment by KorPhaeron** [comment]
@armuhelen

Out of their comfort zone because everyone is lost and confused and half the wires and pipes are wrong isnt the good kind of stress to put people under

If the map is basically the same as the other maps (I dont recall it playing any differenr other than cult and blob being bullshit), is it worth asking our players to learn it in a game that already requires a ton of learning/our contributors to have to consider it for every new feature?

**Comment by praisenarsie** [comment]
- what knife is this supposed to be?



- you'll need double airlocks here

- this seems massively unprotected, one welder tool is all it takes to fuck this pipe

- hydroponic trays? in hallways? i think you should just replace some of them with oxy/fire closets

**Comment by CorruptComputer** [comment]
@praisenarsie Thanks for the feedback!

* That's a ritual knife, where someone was obviously sacrificed.
* Will do!
* Actually had that on my list of todos already.
* They have just always been like that, however I have thought about changing it.

**Comment by ChangelingRain** [comment]
asteroid station was bad for multiple reasons; on top of being absolutely shitfuck huge, most of its departments were oddly cramped, it lacked maintenance to the point of absurdity(escape had one maint entrance, and it led to basically a dead end!), and the center singulo, while an interesting idea, meant that there was no chance that it would fuck off into space went it got out.

**Comment by epochayur** [comment]
better than pubby, at least

**Comment by Armhulen** [comment]
Shut the hell up engine variety is cool and gives value to unlinked maps

**Comment by Armhulen** [comment]
unliked sorry phoneposting

**Comment by epochayur** [comment]
know what else is cool? not losing almost half of the station when someone sneezes in the general direction of the engine

**Comment by Buggy123** [comment]
Don't put words in our mouths, I rather like the raw, primal, _uncensored_ destruction that Lord Singuloth brings to the station.

**Comment by optimumtact** [comment]
You are a nobody

**Comment by CorruptComputer** [comment]
Ah forgot to add to that commit, I did change that pipe being in space, it's now safely™ in the station.

**Comment by Kerbin-Fiber** [comment]
I for one want this map to be in the game and I agree With Arm

**Comment by praisenarsie** [comment]
> I for one want this map to be in the game and I agree With Arm

never agree with arm



- you have lots of computers facing south which is kinda bad considering you can't access computers if you are behind them.



- UGLY, either try and get a new sprite for this to look less old or just remove these signs and replace them with different ones



- move the toxins testing area further back. (back as in left/west)



- right i am skeptical about this area as it's great and all for assmos mixing but you can also put an incinerator there OR keep it as a mixing chamber with tank transfer valves.
- also can you make it more connected to atmos as in add in some airlocks from atmos to there so i don't have to trek all the way from that far top left maint door all the way to the mixing chamber
- also if you do plan on giving atmos tank transfer valves, reconsider the toxins area for science and maybe make it more abandoned.

**Comment by CorruptComputer** [comment]
@praisenarsie

* Already fixed.
* Will do!
* Why?
* Was already planning on adding an incinerator engine there as a sort of backup power system. But the expiermentor idea is definitely interesting, might look into that instead.

**Comment by ike709** [comment]
@praisenarsie Actually unless it's changed since I added directional computers, it doesn't matter which direction the computer faces. You can still use it.

**Comment by davethwave** [comment]
perhaps use a https://tgstation13.org/wiki/Thermo-Electric_Generator instead of the singulo/tesla one?

**Comment by Kerbin-Fiber** [comment]
Yes, Science needs a Integrated Circuits Lab

**Comment by CorruptComputer** [comment]
@davethwave I'll look into that, might take a vote to see if people would rather something different.

@Kerbin-Fiber Will do!

**Comment by coiax** [comment]
I always liked AsteroidStation's bar.

**Comment by praisenarsie** [comment]
i like the idea @davethwave as it makes asteroid more unique. of course though that means the TEG will need to go under some rework to be more optimized for asteroid's standards.

also i thought the toxins test area was too close but nevermind.

**Comment by Bawhoppen** [comment]
I'm pretty sure we have a mandate from Kor to use the SM for everything

**Comment by optimumtact** [comment]
yes that is correct

**Comment by Kerbin-Fiber** [comment]
But I want a singulo in the middle of the station, who doesn't like the idea of the constant reminder that the thing powering the station you're living on is a big hole of death?

**Comment by duncathan** [comment]
How long did it take to update every turf path?

**Comment by CorruptComputer** [comment]
@praisenarsie I have no idea how the SM generator works, so that would take awhile for me to learn before making.

@duncathan Not too long, maybe about an hour?

**Comment by Cyberboss** [comment]
Add a link to the photo in the changelog please

**Comment by CorruptComputer** [comment]
@Cyberboss Will do with an updated image, I'll add it when I'm done with the todo list I currently have.

**Comment by SpaceManiac** [comment]
* `/obj/vehicle/secway` -> `/obj/vehicle/ridden/secway`
* `/obj/vehicle/janicart` -> `/obj/vehicle/ridden/janicart`
* Shuttle brig floor needs to be either `/turf/open/floor/plasteel/shuttle/red` or `/turf/open/floor/mineral/plastitanium/brig` to actually count as "in custody" for objectives.

**Comment by CorruptComputer** [comment]
@SpaceManiac Added to my to-do list! It is finals weeks here so I won't be able to get around to all these for a few more days. But when I do it'll be a relatively larger update as I am planning on revamping maintenance as well as the above suggestions.

**Comment by optimumtact** [comment]
I'm just going to deny this and if @KorPhaeron  disagrees they can overrule me

I don't think we have a setup that means we're doing justice to maps other than meta or box

**Comment by CorruptComputer** [comment]
I still think this map should have a fair chance in an active server to test if the players would want it. Maybe a vote after to see what they think. The map is nowhere ready for such a test yet, there is far more testing that needs done (why this was a WIP PR), and I would like to keep this open for discussion and Travis testing.

**Comment by Kerbin-Fiber** [comment]
So uh, any updates on this map? @CorruptComputer

**Comment by CorruptComputer** [comment]
Yeah, I was away on break. Going to work some more on this over the weekend. Problem with the PR being closed is that it won't show any updates to the branch here (there's already been some).

**Comment by Kerbin-Fiber** [comment]
Neato, can't wait to see em

**Comment by Kerbin-Fiber** [comment]
I wonder how Nuke Ops would turn out on this map with the addition of that console that lets you choose your own location for the ship.

**Comment by coiax** [comment]
If we're talking about maps that do something different:

People are talking about moving sub-departments around. So Robotics becoming part of Engineering, and possibly moving Toxins to Engineering instead of science? I dunno.

But if we need novelty to bring back asteroidstation's bar, then we should do that.

**Comment by epochayur** [comment]
asteroid's medbay is top-tier, even if science is a clusterfuck

**Pull request closed without merging**
