### PR TITLE
Adds new disabler sprites

### PR DESCRIPTION
**Pull request by Bawhoppen**
:cl:
add: Disablers now have a new sprite and now can attach flashlights.
/:cl:

Whether or not we remove tasers, couldn't hurt to have a new disabler sprite.

Updated Image:
image

Sprite ported from Bay. Credit to the original creator + WJ for edits.

### CODE REVIEW

**Comment by actioninja** [comment]
Not bad, a bit weird compared to what other sprites look like but it's better than the old one at least.

**Comment by Bawhoppen** [comment]
@actioninja Well, it was originally an egun on Bay. Just thought it would be better than nothing. Someone else was making a custom one from scratch which would probably be preferable, but this is good enough incase they don't finish.

**Comment by WJohn** [comment]
Made the grip a little bigger, it looked too small.

**Comment by wesoda25** [comment]
Whats with the rush to replace all our sprites? Absolutely nothing is wrong with what we have and tbh its questionable that these even look better.

**Comment by Tlaltecuhtli** [comment]
edit the mob icon as it doesnt have a blue line on top

**Comment by nicbn** [comment]
There's no rush to do anything, this is called a community project and we need to add or change things to keep the project going. Also it looks better so this is a yes yes.

**Comment by Bawhoppen** [comment]
@Tlaltecuhtli Good point. Will work on it.

**Comment by imsxz** [comment]
@wesoda25 the disabler sprites we currently have are pretty bad and look like flintlock pistols with neon lights. the sudden rush is that there's a proposed PR to make disablers mainstream which has brought attention to their sprite.

**Review by ShizCalev — COMMENTED** [review]
new inhands to reflect the change would be preferable.

**Comment by PKPenguin321** [comment]
These are for the non-hybrid disablers, right?

**Comment by MrDoomBringer** [comment]
Is it just me or are the red (empty) and blue (full) "energy" highlights a different shade of blue than the ones in the eguns and multiphase?

**Comment by Angustmeta** [comment]
Rip glorious QM-disablers with slick wooden handles.

**Comment by wesoda25** [comment]
But how long until someone decides these are ugly and throws up a PR to change them? Call me nostalgic but I dislike when we change long-standing sprites for stuff like this. Plus random sprite changes are fucky because it doesn’t really make sense, immersion is a joke but still. 

My argument is petty but if the only argument for it is a several people’s opinion that what we have looks bad, then I can reason whatever the fuck I want I guess.

**Comment by anconfuzedrock** [comment]
Waah the inhand looks weird when the gun looks like thiis

**Comment by ExcessiveUseOfCobblestone** [comment]
disablers haven't been in that long to consider them "long standing"

**Comment by Bawhoppen** [comment]
Wj said they'd make some inhands since Bay doesn't have specific ones for it. Also, should I give the ability to attach on flashlights?

**Comment by ExcessiveUseOfCobblestone** [comment]
*shrug*

**Comment by Bawhoppen** [comment]
Alright, disablers have proper inhands now, as well the ability to attach flashlights to them (Also a slight color improvement).

image

**Comment by anconfuzedrock** [comment]
As long as nobody touches my regular taser sprites I will continue to be moist

**Comment by ExcessiveUseOfCobblestone** [comment]
@Bawhoppen is this ok to go?

**Comment by Bawhoppen** [comment]
@ExcessiveUseOfCobblestone Oh yes it absolutely is. Sorry for not clarifying.

**Comment by ExcessiveUseOfCobblestone** [comment]
all good, I didn't want to assume

**Pull request merged**
