### PR TITLE
Red Wizard Hats on Corgis

### PR DESCRIPTION
**Pull request by Mercenaryblue**
:cl:
Enabled Corgis to wear red wizard hats.
:/cl:

### CODE REVIEW

**Comment by Mercenaryblue** [comment]
oh f*cking hell it committed the paperplane changes too.

**Comment by PKPenguin321** [comment]
you made your branch while on your paper plane branch, next time just go in the git bash and type "git checkout -b your-branch-name-here upstream/master"

**Comment by Mercenaryblue** [comment]
No, worst, this is from my master. I first thought I had to do master to master when ready.

**Comment by PKPenguin321** [comment]
get in the IRC

**Comment by Mercenaryblue** [comment]
Will reopen later

**Comment by Mercenaryblue** [comment]
Up to date with paperplane code, so it won't get a conflict.

**Comment by Jalleo** [comment]
Mercenaryblue cant you close this PR and then create a new one on a different branch which dosent have your paper plane code?

**Pull request closed without merging**
