### PR TITLE
Buffs the traitor toxins

### PR DESCRIPTION
**Pull request by Iamgoofball**
For poisons I'm spending TCs on, these are really weak. Overall consensus is they aren't powerful enough, this should make them more used.

### CODE REVIEW

**Comment by AlexanderUlanH** [comment]
Coniine is the diamond in the rough that is the poison kit, and probably doesn't need any buffs.  It knocks out and crits quickly in doses of under 1 unit.  The balancing factor is that it's mostly oxygen damage, but adding all of two extra units makes it crit with toxin damage alone.
Formaldehyde could use a buff, but I'd say it should be buffed in the consistency with which it decays into histamine, because I've seen some poisoning victims killed with only a few units, and some walk away from doses upwards of 15u.

**Comment by Lumipharon** [comment]
formaldehyde can be made by chemists though, keep that in mind.

**Comment by Iamgoofball** [comment]
Yeah, but it was also pretty crap to use.

**Comment by Lumipharon** [comment]
True, I'm just saying I wouldn't expect it to be as good as traitor exclusive ones.

**Comment by babinsquared** [comment]
Formaldehyde in its current state is an unremarkable toxin with slow damage and a pretty obvious tell (sneezing+fogscreen=histamine). It's got a small chance to kill very quickly, but even 15u (a whole syringe) is survivable if the dice roll in the victim's favor. Definitely not worth being a traitor poison in its current state, and chemists can mix many other lethal toxins, many with guaranteed lethality at the 15u mark. Buffing the damage of histamine won't do much (histamine is already super lethal, the main barrier is getting the histamine to exist in the first place), but buffing formaldehyde's own base damage will go a long way to making it respectable. The other options would be reducing formaldehyde's natural metabolism rate (giving more RNG rolls per unit, so that histamine is more likely to hit overdose before all the formaldehyde decays; formaldehyde would be more lethal overall, but still slow-with-a-chance-of-being-fast) or bumping up the chance of it making histamine or the amount produced (raising the odds of it RNGing the target to a super fast death). I like the increased damage because it makes formaldehyde faster overall even without involving dice.

Sulfonal is also chemist-mixable and is already strong. Its extremely low decay rate means that low doses are lethal -- one hit from a full syringe and you WILL die without treatment. I'd prefer that its damage stay low, because the low damage means you can mask its effects with omnizine to keep the victim healthy until they get knocked out, making it a wonderful stealth option. It's one of the few poisons that can be considered stealthy. The small amount needed for a lethal dose means that you can fit it into patches and such without taking up too much reagent space, and the low damage is what allows you to hide the effects until it's too late.

I don't typically take toxin kits because I usually roll with 0TC so I don't have much experience with the others.

**Pull request merged**
