### PR TITLE
Abductors have an antag sound stinger upon being rolled

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

This adds an antag stinger for being selected as an abductor scientist/agent.

https://github.com/tgstation/tgstation/assets/28870487/fb38f63b-3edc-48b7-8652-ff9cdc1016f8

Some nice extraterrestrial whooping with a classic theremin stinger in the background. It's a bit on the longer side but that's only because the second whoop takes a while to peter out.

Both attributions handled in attributions.txt, both were CC0.
## Why It's Good For The Game

The theremin is peak greylian representation. Helpful for getting into the mindset of a spooky ayylien.

I think more antags should have these audio stingers. They invoke a Pavlovian response equal in power to the almighty bwoink.
## Changelog
:cl: Rhials
sound: The abductor team now has their own antag stinger.
/:cl:

### CODE REVIEW

**Review by MrMelbert — APPROVED** [review]

**Comment by Time-Green** [comment]
MASTERPIECE

**Comment by LSommers** [comment]
WE SURVIVIN' SLIM WHITMAN WITH THIS ONE

**Comment by Donglesplonge** [comment]
sounding general truly does produce some masterpieces, may the sun never set

**Review by ArcaneMusic — APPROVED** [review]
I'm arcanemusic and this is my favorite stinger on mothership zeta

**Pull request merged**
