### PR TITLE
Fixes EXCESSIVE VOTE RIGGING on /tg/ servers, Fixes Voter Apathy

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Freedom and Democracy
fix: Fixes EXCESSIVE VOTE RIGGING. Viva la Democracy!
fix: Also fixes voter apathy
/:cl:
https://tgstation13.org/phpBB/viewtopic.php?f=2&t=20333
now the CORRUPT and RIGGED ~~Clinton~~oranges can no longer CRUSH the TG PLAYERBASE with his RIGGED VOTES

### CODE REVIEW

**Comment by PKPenguin321** [comment]
based

**Comment by imsxz** [comment]
546910d8efb16932cd8de521d222f2f0

**Comment by 4dplanner** [comment]
Will this affect restart votes?

**Comment by KetasDotepasto** [comment]
This circumvents a config, since default votes can already be turned off.

**Comment by evsey9** [comment]
If hypothetically there would be a config option for ERP verbs implemented a long time ago, would you still say that removing such would be "REE CONFIG CIRCUMVEBTION!!!"?

**Comment by KetasDotepasto** [comment]
Yes.

Because there is a config, it becomes a political question.

**Comment by evsey9** [comment]
"It's in the config" shouldn't be used to justify bad features

**Comment by KetasDotepasto** [comment]
That is assuming that the default votes are a bad feature, which is highly debatable.

**Comment by 4dplanner** [comment]
So this means if a restart vote is started while I'm busy, I have to either risk dying to vote no or risk it going through?

**Comment by 4dplanner** [comment]
Boo

**Comment by fludd12** [comment]
@4dplanner Why do you care about starting a new round if you're currently busy?

**Comment by cebutris** [comment]
by "busy" I think they mean in combat, or something else that requires their full attention

**Comment by 81Denton** [comment]
Restart voting doesn't even work if an admin is on
This is only gonna affect Terry at best

**Comment by 81Denton** [comment]
orange man bad

**Comment by Potato-Masher** [comment]
>>:^l

**Comment by delaron** [comment]
VIVA!

**Pull request closed without merging**
