### PR TITLE
replaces the punching bag sprite, removing fitness.dmi

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

replaces the old goon punching bag sprites with new ones made by yours truly
image

## Why It's Good For The Game

less goon :-D

## Changelog

:cl: Fikou
imageadd: new punching bag sprites!!!!!!!!!!!!!!!!
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
how are you standing over a chain attached to the ceiling i hate you

**Comment by Paxilmaniac** [comment]
fitness dmi in your mouth

**Comment by Serxule** [comment]
are all punching bags with the nt logo now? i think they spawn in some places where that wouldnt fit

**Comment by SuperNovaa41** [comment]
> are all punching bags with the nt logo now? i think they spawn in some places where that wouldnt fit

Stationside its corporate branding, otherwise its practice against the enemy bro

**Comment by StoneMason** [comment]
petition to make it a standing punch bag for consistency

still good sprite though

**Comment by Farquaar** [comment]
Sprite looks nice, but the animation doesn't seem to convey the same weight as the original. It would be nicer if the bottom was "floppier" than the top if one wants to convey that sort of heaviness.

**Pull request merged**
