### PR TITLE
Reagent Decals 2: Black Powder Boogaloo

### PR DESCRIPTION
**Pull request by Iamgoofball**
- Quite a lot of decals can now be scooped up with a beaker in order to acquire the contents.
  - Light a piece of paper on fire with a lighter, and scoop up the ashes!
  - Scoop up the flour the clown sprayed everywhere as a "joke"!
  - Scoop up the oil left behind by exploding robots for re-usage in chemistry!
  - You can splash the contents of a beaker onto the floor to create a Chemical Pile! This pile can be heated or blown up and have the reagents take the effects. Make a string of black powder around a department in maint. and then heat it with a welder 2day!
- Reagents now can have on_tick() effects.
  - Pyrosium and Cryostal. now feed off of oxygen and heat/cool the beaker without having to be inside of a person!
- Reagents can now respond to explosions!
  - Black Powder now instantly detonates if there is an explosion that effects it. 
- Fire now heats up beakers and their contents!
  - Activate some smoke powder in style by lighting the beaker on fire!
    example of the new decal system in use
    before
    every one of those piles is a 50u Black Powder pile
    I heated the last pile standing next to me a few times with a welder. It sparked, and this was the outcome.
    after

### CODE REVIEW

**Comment by Thunder12345** [comment]
Can you make blackpowder ignite any other blackpowder in adjacent tiles with any amount of it? Would make it actually practical to do powder fuses.

**Comment by Xhuis** [comment]
In addition to Thunder's comment, having decals connect blood-trail style could make for awesome-looking fuses

**Comment by Iamgoofball** [comment]
@Thunder12345 it does, any kind of fire/explosion will ignite black powder and make it go kaboom, triggering the same 

@Xhuis blood trail code is evil

**Comment by Xhuis** [comment]
Mkay, no problem

**Comment by Razharas** [comment]
Give them temperature_expose proc so they can heat up/cool down from the atmos around them even without direct hotspot above

**Comment by Razharas** [comment]
Also you are making chems process durning ambience?
I think it being handled by the reagents datum may be better than trying to do this by adding all possible holders to the process

**Comment by Iamgoofball** [comment]
@Razharas when i tried handling it on the datum itself, we had all sorts of problems such as foam not reacting more then once in a world session, and other weird bugs.

handling it on the holders was the easier and far less broken approach.

i can do temperature expose too.

**Comment by Razharas** [comment]
Holders processing instead of reagents processing is not a good way, it will mean adding these things to all possible holders shall they appear instead of it all being handled naturally by reagents datums themselves without any care about holders themselves
Easy is not always good

**Comment by Iamgoofball** [comment]
@Razharas if you can come up with a solution that doesn't break shit, be my guest and PR it to this branch. I've got no clue where to start on the datums doing the processing because my last 3 attempts didn't work.

**Comment by Dorsisdwarf** [comment]
I think the sprite for that black powder tile is a little dark. It just doesn't look right.

**Comment by pudl** [comment]
goof, blood trails working like decals would mean that you could ingest black powder, bleed everywhere, then set your blood on fire
why would you not want that

**Comment by RemieRichards** [comment]
A Requested review:

I agree with Razh, fix the Process crap, since the Foam stuff wasn't your bug, and these other bugs (if they exist still) are likely not to be related either.

(I know I sent you this on steam already but it's for the record)

**Comment by Iamgoofball** [comment]
yeah we fixed the foam crap so i'm working on process changes now

**Comment by RemieRichards** [comment]
DNM cos of the process crap.

**Comment by Xhuis** [comment]
habbening

**Pull request merged**
