### PR TITLE
New Medical Kiosk Sprite

### PR DESCRIPTION
**Pull request by MrDoomBringer**
## About The Pull Request
image

## Why It's Good For The Game
image

## Changelog
:cl: MrDoomBringer
imageadd:Nanotrasen has released a new version of the medical kiosks! While Nanotrasen has publically boasted numerous improvements over the older models, independent research has shown that the only difference is a flashier outer case, and the internals are, in typical nanotrasen fashion, the exact same.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Part of me kinda liked the old one but, truth be told, it sure as hell doesn't fit the art style. Good shit.

**Comment by wesoda25** [comment]
needs more soul

**Comment by HomocidlePancakes** [comment]
Looks like a vending machine.

**Comment by Iatots** [comment]
This doesn't really look like something whose primary function is scanning people. Looks more like a printer.

**Comment by Tlaltecuhtli** [comment]
whats written on it? sugma?

**Comment by HomocidlePancakes** [comment]
Having the shop from Dead Space as the kiosk would be neat, but I doubt anyone will be bothered

**Comment by MrDoomBringer** [comment]
@HomocidlePancakes @Iatots would you prefer thinner?
image

**Comment by cacogen** [comment]
real nice fuckin sprite ya got there the old one looked like a scalp massager
this one looks like its selling ya the succ

**Comment by Neo-0** [comment]
change the state `open` back to `kioski_open`, or you will probably have issue

**Pull request merged**
