### PR TITLE
custom say emotes, or in other words, radio emotes

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

title

Screenshot 2021-10-15 175819

In order, going from top to bottom, what was said to make those lines:
- ";screams!*"
- ";,o taps his mic before saying*testing, testing, one two, one two."
- ";taps his mic before saying*testing, testing, one two, one two."
- (with forked tongue) ";taps his mic before saying*testing, testing, one two, one two."

it also works when not on the radio as well of course, don't worry.

### The format is:
"[radio keys/language keys/etc][the say emote]*[what should be said]"

## Why It's Good For The Game

fun things?

## Changelog

:cl:
add: custom say emotes, or in other words, radio emotes. The format is for example "screams and shouts*damnit!" with any relevant radio keys, language keys and all that used as normal, for example, ";,o screams and shouts*damnit!" or you can use just the emote, ie, ";screams!*"
/:cl:

### CODE REVIEW

**Comment by Acer202** [comment]
Laugh at your peers from a distance! Cough awkwardly over the microphone when someone says something terrible, blow into the microphone to make everyone angry! I think this is great.

**Comment by kopoba** [comment]
So we can bind some text there? like "HELP TRATTOR KILLING ME IN MAINTENANCE" to one button? or how does this works?

**Comment by Timberpoes** [comment]
Make sure this respects custom emote bans.

How does this interact with mime vow of silence?

**Comment by Mothblocks** [comment]
This syntax seems easy to easily fuck up to me, so I'm going to look through say-logs at some point and figure out if this is common enough in standard speech to warrant a syntax change.

**Comment by Mothblocks** [comment]
Also make damn sure that the emotes are HTML encoded

**Comment by itseasytosee** [comment]
I worry this will allow for some species obscuring possible which is gonna make things hell for the AI.

**Comment by MessoDepresso** [comment]
Do be careful, this breaks the Drunk Slurring and WILL make burps eat the entire message
Source: multiple servers that have used the same * key for ot

**Comment by Seris02** [comment]
it is, don't worry already tested it

my code is better than theirs

**Comment by Seris02** [comment]
> what happens if you accidentally forget the " at the end?

those quotation marks were just to show what the exact phrase is so that people wouldn't have difficulty making it out, they aren't part of the format

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]
Not really sure how I feel about the feature, kinda don't really mind, might be better done as something separate from normal text, so like

("Person" taps their microphone)
("Person" meows: Fuck you john williams)
if that makes sense. Not too big an issue though
Would make language and say text modifiers less of a headache 

Anyway have some code review

**Comment by LemonInTheDark** [comment]
> 
> 
> @LemonInTheDark To be fair, emotes don't play over radio, while these would.

? I think we're talking past each other, not saying the feature is redundant, just that emoting in the same chat message that you can do things like talk in draconic or sing in leads to some annoying issues

**Comment by Ryll-Ryll** [comment]
> Do be careful, this breaks the Drunk Slurring and WILL make burps eat the entire message Source: multiple servers that have used the same * key for ot

`and WILL make burps eat the entire message` this is a really funny sequence of words

**Comment by Mothblocks** [comment]
Looking at the logs maybe tomorrow

**Comment by cacogen** [comment]
I've wanted something like this for awhile but it seems kind of weird that you have to end the custom emote with an asterisk rather than begin it with one. It would be more intuitive if you used a quotation mark to begin the dialogue. e.g. `say ";,o*taps his mic before saying"testing, testing, one two, one two."`

**Comment by Seris02** [comment]
> Does this work with bold/italics/underlined text? For example, if I wrote Gasps +loudly+, before breathing heavily twice and saying*Oh god, oh +_god_+, this was |not| supposed to happen this way, the clown |+escaped+|, call the goddamn shuttle!"
> 
> Would "loudly" be bold, the second "god" be bold and underlined, and would "escaped" be bold and italicized?
> 
> Edit: looks like github took the two underscores around the second "god" and made it italicized, in game two underscores underlines the text

yes

**Comment by Mothblocks** [comment]
@LemonInTheDark busy with life, dont block on me getting logs

**Comment by Mothblocks** [comment]
ctrl shift enter closes. got it

**Comment by Rohesie** [comment]
Very nice feature.

**Comment by LemonInTheDark** [comment]
Update the changelog to properly describe how to use the feature, and we're golden

**Comment by Seris02** [comment]
> Update the changelog to properly describe how to use the feature, and we're golden

is done

**Comment by RuneQuester** [comment]
This doesn't appear to be working on the TG manuel server. I copy pasted exactly one of your examples but nothing happened
image

**Comment by TheBonded** [comment]
are you sure that the manuel server was up to date at the time? it doesn't update during a round, so you'd have to wait for the round to end for the server to update with the pr

**Comment by LemonInTheDark** [comment]
> 
> 
> This doesn't appear to be working on the TG manuel server. I copy pasted exactly one of your examples but nothing happened image

This pr was merged 36 minutes ago. Manuel has not updated, and won't update until a keyholder manually does it

**Pull request merged**
