### PR TITLE
Adds Frieza Midround Antagonist

### PR DESCRIPTION
**Pull request by IndieanaJones**
## About The Pull Request

image

So there's a really angry alien here who's demanding to know why we started hiring Saiyans. When asked about his credentials, he said something along the lines of "Emperor of the Universe" before blowing up the HOP and leaving. Maybe we should handle that.

This PR adds a Frieza basic mob and a corresponding midround antagonist dynamic event. Frieza can:

- Move freely in space
- Shoot lasers from his eyes
- Confound attackers with his tail
- Beat you with his hands very quickly
- Regenerate from damage with his superior healing factor
- Rip through walls
- Pick up and use tools
- Play his iconic walk sound effect when walking
- Kill monkeys
- ...And more!

Since Frieza is superior to any other antagonist in the pool, he gets a weight of 50 so he spawns very often, like a true Emperor of the Universe should. Of course, an admin could always just trigger the event instead if they wanted to.

## Why It's Good For The Game

Somebody has to put the monkeys in their place.

## Changelog

:cl:
add: Added Frieza midround antagonist event. Saiyans beware, he blew up your home world and now he's here for your station too!
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Starting out in his ultimate form?

Dear lord jesus we fucked up

**Comment by ATH1909** [comment]
should he maybe get some way to heal himself?

**Comment by IndieanaJones** [comment]
> should he maybe get some way to heal himself?

He has a self-healing factor don't worry about it

**Comment by moocowswag** [comment]
Can you spin him around by his tail just like lizards?

**Pull request closed without merging**
