### PR TITLE
Extended functionality for Update Paths.bat

### PR DESCRIPTION
**Pull request by Peliex**
## About The Pull Request

this doesn't really effect anything and a few mappers mentioned being able to do all scripts (mostly for running them on older maps which I am all for)
## Why It's Good For The Game

Refactor batch to actually use batch to do batch since a three line file to run python is boring.
Otherwise, it's not. : v)

### CODE REVIEW

**Comment by san7890** [comment]
i'm scared about potential collisions between updatepaths files, have you done a test run?

**Comment by Peliex** [comment]
> i'm scared about potential collisions between updatepaths files, have you done a test run?

It runs and executes yes.  Each script is run in numerical order one after the other.  It takes a godawful long time and running scripts on maps they've already been run on is generally a bad idea.  If somebody tries to run this on all files and then PR it bonk them on the head, you should really only run all of them on old maps.  It modified every single map file in _maps at *least* once.

**Comment by san7890** [comment]
i think we then need to just relegate any scripts that are beyond like 500 PRs before this one to a legacy folder which we don't read from at all, otherwise it's just going to get messy as contributors handle it the wrong way and stuff gets merged anyways. bonking only works when everyone is aware of it, but no one is ever going to be 100% aware of this without being explicitly told

**Comment by Peliex** [comment]
> i think we then need to just relegate any scripts that are beyond like 500 PRs before this one to a legacy folder which we don't read from at all, otherwise it's just going to get messy as contributors handle it the wrong way and stuff gets merged anyways. bonking only works when everyone is aware of it, but no one is ever going to be 100% aware of this without being explicitly told

Actually you bring up a good point, leaving the legacy updatepaths script in place would probably be a better solution.  Do you have a suggestion on a path to place that batch file in?  It will still function as intended since dragging and dropping scripts onto it using absolute paths on windows and nobody I talked to actually did anything else with that script.  Not even run it from CLI.

**Comment by san7890** [comment]
> Actually you bring up a good point, leaving the legacy updatepaths script in place would probably be a better solution. Do you have a suggestion on a path to place that batch file in? It will still function as intended since dragging and dropping scripts onto it using absolute paths on windows and nobody I talked to actually did anything else with that script. Not even run it from CLI.

the updatepaths that we currently have on the repo should be where it is. we should have a new folder in the `UpdatePaths/` directory named something like `RunEveryScript` where this new batch script that you are PRing here will be located. i still think we should work on moving the really old updatepaths to a legacy subfolder somewhere given how a lot of them are just not relevant anymore

**Comment by san7890** [comment]
or just rename it and keep it where it is? i think the subfolder lends itself more to strike that balance between user visibility and "you really don't want to run this if you don't know what you're doing"

**Pull request closed without merging**
