### PR TITLE
Readded Stungloves (balanced)

### PR DESCRIPTION
**Pull request by ACCount12**
Yes, stun gloves!
- 4 stun, can be reduced by energy armor.
- 5000 cell charge per stun (3 stuns with cell from assistant storage).
- Gloves can be blocked by shields.
- You can make stun gloves from non-insulated gloves, but then they would stun you too.
- Stun gloves made from insulated gloves are insulated too.
- You can spot "wired insulated gloves" on examine.
- Removing stun gloves with strip menu is really fast.
- Code isn't shitty anymore. 

So stun gloves are balanced now. How about adding them back?

Remember: STUNGLOVES ARE SHIT BECAUSE THEY ARE STUNGLOVES is not a valid argument. Yes @Cheridan, this is about you.

### CODE REVIEW

**Comment by optimumtact** [comment]
Yes, it's a great idea to antagonise the person who will determine if your PR gets pulled or not.

**Comment by ACCount12** [comment]
This is not my first pull. See #8781. "this is about you" wasnt there before.

**Comment by SconesC** [comment]
>Not balanced for a crew item, can't be disarmed, examined, etc.

They can be stripped quickly, but still not disarmed. Not sure how I feel about that.

**Comment by Alek2ander** [comment]
So instead of a disarmable, easily visible, slightly awkward to use stunprod, you suggest adding an item with no special onmob sprite that is always on you and ready for use, with the only downside of requiring insulated gloves which every greytider worth a damn already gets anyway? Give me ten!

**Comment by ACCount12** [comment]
It's weaker than stunprod, it has 3 charges instead of 6 and insulated gloves are not that easy to get. In can be removed with strip menu in a single disarm push.

**Comment by SconesC** [comment]
does it last long enough to cuff somebody?

**Comment by ACCount12** [comment]
Only if you are hotkey-using speed monster, RNG loves you, there is no lags and targed has no armor.

**Comment by ACCount12** [comment]
I re-pull it. @Cheridan, stop being shithead.

**Comment by Alek2ander** [comment]
>it has 3 charges

Powercells are all over the station.

>

**Comment by ACCount12** [comment]
I actually reduced strip time for stun gloves /4.

**Comment by Antimattercarp** [comment]
I see people like sec stunning, cuffing, stripping, and then asking questions

**Comment by freerealestate** [comment]
>makes stun gloves really shitty and impractical
>still gets closed

¯\_(ツ)_/¯

**Pull request closed without merging**
