### PR TITLE
Switch to jsdelivr for Font Awesome

### PR DESCRIPTION
**Pull request by neersighted**
Fixes some weird as hell SSL problems with maxdn's bootstrapcdn network

@octareenroon91

### CODE REVIEW

**Comment by PKPenguin321** [comment]
at a glance the title of this PR makes it look like you had a stroke

**Comment by duncathan** [comment]
This probably does something good!

**Comment by JJRcop** [comment]
So you've already disappeared for probably ever and this is ~10 months later, but I think the prospect of downloading any file, even css, from an external website we don't have control over, isn't so much a neato thing. Considering tracking all these down and putting them in the repo.

**Comment by neersighted** [comment]
@JJRcop been meaning to get back to it but slammed with school and work; will keep it in mind

**Comment by JJRcop** [comment]
@neersighted Don't worry about it i'm moving them onto the repo right now.

**Comment by JJRcop** [comment]
#21872

**Pull request merged**
