### PR TITLE
Restyles Stat Panel, Adds Subpanel Sub-Categories

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request

I re-styled the CSS for the stat panel in hopes to make it look nice, and I also added the ability to use sub-categories (currently a single level) of verbs using a ``.`` (period), an example being ``Admin.Fun`` instead of the previous ``Admin - Fun``. This now results in a sub-category being automagically generated in the stat panel.

image

image

[You can see video samples of both light and dark mode here on imgur.](https://imgur.com/a/Z4IOqOa)

## Why It's Good For The Game

Significantly improves the styling introduced with the html stat panel's original PR, decreases clutter for admins

## Changelog
:cl: bobbahbrown
add: Re-styled the statpanel for an improved UI experience.
admin: Put all admin buttons under one roof, now with subcategories within the statpanel.
/:cl:

### CODE REVIEW

**Comment by bobbahbrown** [comment]
@SpaceManiac please test on ie8

**Comment by bobbahbrown** [comment]
ok yeah i see why you did that, makes it a bit tidier, thanks for the review chief

**Comment by SpaceManiac** [comment]
the actual problems were .forEach and .textContent, replacing .filter with procedural style was just simpler at the time

**Comment by Rohesie** [comment]
Looks really good.

**Pull request merged**
