### PR TITLE
Brings back clown planet as a space ruin

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request
[Removed](https://github.com/tgstation/tgstation/commit/d5d223f792fc92d12b1cf2d27c7491b40311ac43) at the end of 2012, supposedly to make its return in an away mission, the clown planet is a staple of old /tg/ culture. This returns it to the game for new generations of players to experience, in that old /tg/ tradition of turning old maps into space ruins.

Here it is in 2012 _**(soul)**_:

## Why It's Good For The Game

It is a planet of clowns. There are no clowns. There are average sized banana peels, and armed mousetraps. You can collect $43 in space cash, if you wish to ruin the word "HONK" that is spelled out with it. There are snack machines in case you get hungry. You can teleport back to the station using the signpost.

There is ~34 bananium on the planet. Unlike in 2012, the bananium is encased in stone and must be located with a mining scanner. It is in the same positions now as it was then. It can be used in conjunction with the clown mask, shoes and horn to build a H.O.N.K. mech with enough metal and glass. You will have a small amount of bananium left over. There will not be enough to build another mech.

As in 2012's version, the planet has no dynamic lighting. It is uniformly lit without the need for light sources. It also has oxygen and gravity. It differs from the last version of the map in that it has no perimeter rock. Earlier versions lacked this rock, and I assume it was added because the planet was located on the Centcom z-level and could be used to break into Centcom. The added rock was nearly indestructible, but could still be destroyed with a singularity or teleported through.

"Without the perimeter rock, how does the oxygen stay in?" It's a planet, with an atmosphere. It is simply rendered in what I refer to as Cacogian projection. The main difference between this and standard Mercator is that if you maintain a constant course you leave land and enter space. As they say, the map is the territory.

## Changelog
:cl: Centcom
add: The Clown Planet's orbit has brought it into our sector. The coordinates to teleport to this minor planet were lost in 2552 after the card was eaten by a goat. Because of its proximity you can simply travel there now.
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
The Crazy Clown Comet

**Comment by PKPenguin321** [comment]
Do we not have red asteroid walls anymore? I didn't think they were actually removed, just unused now
You could totally readd them

**Comment by IndieanaJones** [comment]
This is where we exile clowns to when they get too rowdy now.

**Comment by Detective-Google** [comment]
> Do we not have red asteroid walls anymore? I didn't think they were actually removed, just unused now
> You could totally readd them

they're used in the wild west away mission iirc

**Comment by Grazyn** [comment]
Looks a bit plain for a ruin. Yes it's the old map, nostalgia effect etc. but maybe it could've been an opportunity to spice it up a little. A new players seeing this would just say meh

**Comment by Tharcoonvagh** [comment]
Make it a bit more bigger and complex, otherwise it is welcome for me.

**Comment by Fikou** [comment]
ugly

**Review by ShizCalev — COMMENTED** [review]
While do I appreciate the attempt to bring back nostalgia by readding a map from 7 years ago without any changes, I definitely want to see this improved so it looks like something a bit more modern really.

**Comment by cacogen** [comment]
It's a simplistically mapped easter egg. The "Why it's good for the game" section of the PR is meant to be tongue-in-cheek. I did keep it the same for nostalgia and because it wouldn't feel right fixing the flaws in the Mona Lisa. And I suck at mapping.

I may try adding a new opened up area or growth or decay from the passage of time, but it'll prbably look like shit.

With some of the away missions I don't think the standard is that high that this couldn't be grandfathered in.

@PKPenguin321 
@Detective-Google 
The wildwest away mission (an example of grandfathered in bad mapping, much worse than this) uses iron sand for flooring which I think is a different sprite to the walls here, and uses the new generic rock sprite which this uses. It's not like I couldn't bring the old sprites back, it's just that it would look a lot uglier. They wouldn't smooth, for example. The blocky look in the 2012 screenshot is in-game, not in the editor.

**Comment by PKPenguin321** [comment]
Did we really never have smooth red asteroid walls? Coulda sworn we did right before we got lavaland

**Comment by Learner10** [comment]
As a space ruin... it looks rather minimal, even if it does provide the nearly non-existent Bananium Ore in sizable amounts (Clown Tear Soup anyone?)

And well... I think that's what it boils down to... it provides only two things really. Bananium Ore, and a way to immediately bring it back.

Still... space is a big place. Having at least that added in would be nice.

**Comment by cacogen** [comment]
I have not been feeling good recently and don't see any changes being made on this

**Pull request closed without merging**
