### PR TITLE
Adds security jumpskirts

### PR DESCRIPTION
**Pull request by Thunder12345**
:cl: Thunder12345
add: The security wardrobe is now stocked with a skirted variant of the standard security jumpsuit.
/:cl:

image

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
How can you have a jumpsuit with a skirt

**Comment by Thunder12345** [comment]
You replace the trousers half with a skirt, it's that simple

**Comment by LetterN** [comment]
incoming drama bellow

**Comment by Tlaltecuhtli** [comment]
delet

**Comment by KorPhaeron** [comment]
Why?

**Comment by Thunder12345** [comment]
They're fashionable

**Comment by WJohn** [comment]
No. What cop wears a skirt?

**Comment by nicbn** [comment]
Irish cops?

**Comment by Thunder12345** [comment]
Cops on the same station that gives doctors the option of wearing a nurse dress?

**Comment by MMMiracles** [comment]
image
when you're chasing a grayshirt and you accidentally run over an active vent

**Comment by WJohn** [comment]
the nurse dress is probably a bit overkill, too, but it's at least something that *exists*. cops wearing frilly skirts just does not happen, at *most* you get something much more form-fitting with liberal usage of stockings.

**Comment by Qbopper** [comment]
funny but like people have said why would a cop ever wear a skirt

**Comment by Thunder12345** [comment]
Because it's the future and they want to be fashionable?

**Comment by KorPhaeron** [comment]
Why cant a player visit the autodrobe if they want to dress up?

**Comment by Thunder12345** [comment]
Because these are security themed and thus don't belong in the autodrobe?

**Comment by Repukan** [comment]
Fetish material

**Comment by Tlaltecuhtli** [comment]
fetish material

**Comment by Hatterhat** [comment]
fetish content

**Comment by Armhulen** [comment]
And I'm pissed

**Comment by Ratvar** [comment]
only if you remove all other security uniform

**Comment by uraniummeltdown** [comment]
some people have a woman fetish, don't think its worth adding this

**Comment by Spaceinaba** [comment]
FUCK THIS I WANT SEC SHORTS

**Comment by Thunder12345** [comment]
https://upload.wikimedia.org/wikipedia/commons/1/1a/US_Navy_041208-N-0000X-001_The_Navy_introduced_a_set_of_concept_service_uniforms_for_Sailors_E-6_and_below_in_response_to_the_fleet's_feedback_on_current_uniforms.jpg

**Review by WJohn — CHANGES_REQUESTED** [review]
Yeah those ARE more form fitting, they're not frilled. I have no problem with straight skirts (with some stockings). I believe the head of security and possibly the warden already have that, so please do the same.

**Comment by jcll** [comment]
Also from ST if you want a more Sci-Fi take https://i.imgur.com/xyw4BBO.jpg

**Comment by Pascal125** [comment]
If you go this route add security shorts, please.

**Comment by Kromgar** [comment]
COMBAT SKIRTS

**Comment by KorPhaeron** [comment]
WJ does not like the sprite

**Comment by DaxDupont** [comment]
2 4  h o u r s

**Comment by ExcessiveUseOfCobblestone** [comment]
just make them pencil skirts!!!

**Comment by Bawhoppen** [comment]
They need to be a good reasonable sprite, if we're going to add them.

**Comment by Qbopper** [comment]
@Thunder12345 sec is essentially a glorified PMC when have you ever seen a deployed soldier in combat wearing a skirt

**Comment by Iamgoofball** [comment]
@KorPhaeron 
WJ is not allowed to reject sprites without making replacements as we have zero active spriters that don't charge for work.

**Comment by KorPhaeron** [comment]
@iamgoofball

If it was holding up some big feature I would agree with you but since this serves no function outside of being a cosmetic, it is fair for him to reject it on cosmetic grounds

**Comment by Iamgoofball** [comment]
I still feel like it's wrong but that's fair

**Comment by rustledjimm** [comment]
WJ hating on fashionable wear.

**Comment by JohnOxford** [comment]
"WJ doesn't like the sprites"

imagine if it was 300 sprites that were just in a different art style that someone spent 60 hours on

**Pull request closed without merging**
