### PR TITLE
Adds a server admin version of end round now

### PR DESCRIPTION
**Pull request by Incoming5643**
A semi obscure admin tool that came about in the mulligan push but never really got advertised. It will print out a round end report and attempt to database round stats before restarting. Suggested use is when the round has SLOWED down to an unplayable crawl for some reason but the game is still technically responsive. Pressing end round doesn't preclude the use of restart() if it doesn't seem to be working, but end round should usually be tried first.

Removes the 20 second confirmation between prompts for the normal admin version of end round now.

If admins force end a round escape objectives will be good faith greentexted if the antagonists were still in a position to escape alive.

The survival rate will always be printed at round end now, even if the shuttle makes it to centcom (evac rate will be printed too in that case).

### CODE REVIEW

**Comment by Cheridan** [comment]
Wondering if this shouldn't just be the default behavior for rebooting. If the server's totally nonresponsive, the reboot probably wouldn't work either way? It's just a pain having multiple buttons that do extremely similar things.

**Comment by Incoming5643** [comment]
Could be done, but I just remember that at some recent point someone removed the time delay for restart so I figured they might still want that panic button as sensitive as possible

**Comment by MrStonedOne** [comment]
Mind you, all admins have client debugging tools

So they have a little button that sends a restart command directly from DS to DD with no code involved.

**Comment by Aranclanos** [comment]
probably the verb should have a noticeable name difference with the other one

**Comment by Incoming5643** [comment]
the other isn't really a verb, it's a topic call

**Comment by Aranclanos** [comment]
under server tab, called 'restart'
do you really think that admins would make topic calls?

**Comment by Incoming5643** [comment]
set category = "Server"
set name = "End Round"

There was another version of this in existence already that was a topic call, I'm making it a verb on server for visibility.

Or are you saying that "End Round" and "Restart" are too similar in name? I'm not sure how I could make them less similar. "Hard Restart"?

**Comment by Aranclanos** [comment]
hard restart sounds good

**Pull request merged**
