### PR TITLE
Removes the stupid hot pink PDA belt sprite who added this why 

### PR DESCRIPTION
**Pull request by pireamaineach**
stop

hurt eye

After learning that this is an actual intentional feature, slick move by goof, I feel the need to actually explain.

PDAs, and several other items intentionally do not use sprites for on_mobs, since the sprite would be tiny anyway.

I also hear this affects things such as plants, which don't have sprites in early stages of growth, but I have yet to see that.

This could affect many, many more things, but for now I know that it affects PDAs, which is a roundstart issue.

Original P.R.:https://github.com/tgstation/tgstation/pull/50788

## Changelog
:cl:
del: Removed untitled belt sprite which unsprited items default to when placed in the belt slot.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
This is, once again, literally not the fix.

The correct fix is to not generate overlays for items that don't have an icon.

How many times do I have to say it?

**Comment by pireamaineach** [comment]
"Why are people incorrectly fixing my P.R."

If you want to not generate overlays for items that don't have an icon, you can P.R. that.

**Comment by optimumtact** [comment]
bip, you're really really reaching levels of braindead that should not be possible

**Comment by optimumtact** [comment]
if you want the pda's to be invisible, give them an empty alpha sprite and set it in the icon state.

**Comment by Iamgoofball** [comment]
that, or the chad fix of "make icon code not render shit with a null icon state"

**Comment by Iamgoofball** [comment]
i will probably end up doing this myself soon

**Comment by optimumtact** [comment]
I believe a null icon state to be a bug.

We should always aim to be explicit in our thought when doing something.

**Comment by pireamaineach** [comment]
Y'know goof if this fix is so simple, and breaks something visible from the fucking preference menu, why haven't you fixed it in the 21 days since your P.R. was merged

**Comment by pireamaineach** [comment]
Also you can't make it null icon state because it still needs to draw a sprite for the item, it just needs to not have an on_mob.

I mean honestly you can still interact with items without on mobs perfectly fine.

**Pull request closed without merging**
