### PR TITLE
Emergency Shuttle - Hug Relaxation Shuttle

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
adds this thing

This is shuttle contains a pillow fight box, no violence, and a large cozy heart-shaped area for spacemen to sleep in.
Has a medical bay, brig, command. Tons of plushies, instruments, pillows, general cutesy stuff. Contains one (1) pax pill bottle.
Has an oxygen canister for quick repressurization.

Also adds it commented out to the Emergency Shuttle Blacklist, in an alphabetically-correct position

Costs 3200
## Why It's Good For The Game

Has an unique emergency shuttle shape, does not promote violence, looks cozy. And I heard some people like this shuttle so its probably good enough?
## Changelog
:cl:
add: Adds the Hug Relaxation Shuttle as an emergency shuttle
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
this is so going to have a merge conflict

**Comment by krimmity** [comment]
pr closed in 3

**Comment by Pickle-Coding** [comment]
Lol.

**Comment by Rex9001** [comment]
This shuttle just looks comfy, I enjoy it. It was closed last time though but since then I hope you have cooldowned

**Comment by SkeletalElite** [comment]
security is stored in the balls

**Comment by Rex9001** [comment]
Stale, it might be over for us Hug Relaxation enjoyers..........

**Comment by MMMiracles** [comment]
lol

**Pull request merged**
