### PR TITLE
Fixes OOC ban not applying to admins

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes https://github.com/tgstation/tgstation/issues/36241

I'm not sure when this will ever be relevant but it is a reported issue and admins can't bypass other jobbans

@BeeSting12 how did you even find this out, who got banned

### CODE REVIEW

**Review by vuonojenmustaturska — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
@BeeSting12 say goodbye to OOC

**Comment by Iamgoofball** [comment]
@KorPhaeron i totally abuse this when I'm given admin to oversee testmerges to get direct feedback from players without using narrate to bypass the ban

**Comment by optimumtact** [comment]
so hold up, by precedent admins can bypass all bans except an admin ban.

I don't think we should restrict this

**Comment by Cyberboss** [comment]
oranges is correct

**Comment by ShizCalev** [comment]
>person is spamming ICky OOCky
>only admin online can't tell because they're OOC banned
🤔

**Comment by KorPhaeron** [comment]
I don't think admins bypass emotebans/jobbans etc

**Comment by Jordie0608** [comment]
Admins only bypass normal server bans.

**Comment by BeeSting12** [comment]
@KorPhaeron Jerry banned me from OOC as a joke and I evaded.

**Pull request merged**
