### PR TITLE
Paper bins now create paper dynamically, rather than creating thousands of pieces of paper on init every round

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Every paper bin creates 30 pieces of paper. DeltaStation has 87, CentCom has 36, Meta has 66. A round of Delta has 3,690 sheets of paper created.

This fixes that by making it so paper bins lazily create pieces of paper when needed. 

This reduces paper bin initialization time (regularly in the top 5) from ~300ms to about 17.

### CODE REVIEW

**Comment by dopamiin0** [comment]
finding out that this wasn't already true is, frankly, terrifying. I'd assumed this was the entire point of paper bins.

does this preserve functionality with putting in pieces of paper with writing and/or stamps on them? what about paper with items, like C4, attached?

**Comment by Mothblocks** [comment]
once a paper is created, it'll be real forever

**Comment by msgerbs** [comment]
> finding out that this wasn't already true is, frankly, terrifying. I'd assumed this was the entire point of paper bins.
> 
> does this preserve functionality with putting in pieces of paper with writing and/or stamps on them? what about paper with items, like C4, attached?

Looks like this change just makes it create a new paper if the bin would have 0 left, so you should still be able to put papers back into it and it will function as normal.

**Comment by AlamoTurtle** [comment]
This PR puts into perspective how goddang blind I am looking for paper bins on these stations now. My god.

**Comment by cacogen** [comment]
This probably broke the paper bin overlays.

**Comment by Mothblocks** [comment]
dont think so, i definitely remember testing silly stuff like that. more likely its plane shenanigans.

**Pull request merged**
