### PR TITLE
Removes Admin midi pref toggle

### PR DESCRIPTION
**Pull request by Shadowlight213**
> Muting the wonderfullness that is admin midis.

:cl:
del: Removed pointless admin midi pref. Why would you ever mute them???
/:cl:

### CODE REVIEW

**Comment by TheDreamweaver** [comment]
Seems good, lets merge it asap

**Comment by kevinz000** [comment]
no, remove instrumental midi toggle.

**Comment by pudl** [comment]
kill meme prs

**Comment by MrPerson** [comment]
You should also remove the SOUND_MIDI flag outright and the Topic() that results from the link you removed

Assuming this isn't a joke, :+1:

**Comment by Dorsisdwarf** [comment]
👎 
I like to use midis for both memes and atmosphere, but I am aware that a sizeable number of players dont like music and have it turned off by default.

**Pull request closed without merging**
