### PR TITLE
Lavaland Ruin update

### PR DESCRIPTION
**Pull request by Cheridan**
Major revamp of biodome ruin: Now is an actual biodome and not a snowbox.
preview:
cheridanplslearnhowtoembed

Note: Not mapmerged, because mapmerge has a bug in it: #17349

Minor tweaks to Animal Hospital: Adds more internals, another lamp, shuffles some things around and adds some air tanks. 

Minorer tweak to Gym: Just replaced the surrounding with noop templates so that the surrounding lavaland terrain interacts with it better.

(These two are mapmerged)

EDIT:
Ok I rescued Beach Ruin too
remieisafart

### CODE REVIEW

**Comment by KorPhaeron** [comment]
There is another biodome please save it

**Comment by Incoming5643** [comment]
You don't really need to map merge when you're drastically changing a ruin anyways, since it'll just spit out more or less what you gave it.

**Comment by Cheridan** [comment]
Fair enough. And yeah I guess this isn't like the station maps that get modified all the time but it's still good to do.

**Comment by KorPhaeron** [comment]
Last one is clown planet

**Pull request merged**
