### PR TITLE
twaticus will now see MY ICON CHANGES (adds twat to codeowners)

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

twaticus is now in codeowners

/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
unfortunately will not work actually

> The people you choose as code owners must have write permissions for the repository. When the code owner is a team, that team must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.

**Comment by bobbahbrown** [comment]
Twaticus does not have commit access, this PR does nothing unfortunately.

@optimumtact and @Cyberboss might consider such a thing, but that's a discussion they'd have to have.

**Comment by tralezab** [comment]
i'll talk to them about it, they should be pinged for sprite changes if they are the art lead

**Comment by bobbahbrown** [comment]
wait nevermind twaticus does have write access, its just controlled through the [sprite team](https://github.com/orgs/tgstation/teams/sprite-team) instead of commit access team.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/pull/52262/files#diff-5cfb934ca0ec4c1743905a51dc428b84R56

**Comment by ExcessiveUseOfCobblestone** [comment]
Twat said she is fine with this

**Pull request merged**
