### PR TITLE
Limited time energy sword discount

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
rscadd: For a limited time, energy swords are 50% off
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
one of these days I'll code a proper 25/50/75% off system that is randomized every round with 3-5 items getting a discount and being placed at the top of the list

**Comment by Bawhoppen** [comment]
@Iamgoofball should add a special random item of the day too for 20 tc that can give like crap-m1911ps

**Comment by Iamgoofball** [comment]
Yeah, that'd be cool

Add job specific traitor items too and make those in the random item of the day pool for all jobs, and we've got a good meme going.

**Comment by Xhuis** [comment]
I tried to add job-specific traitor items once. It got shot down almost immediately.

**Comment by Thunder12345** [comment]
Kor you madman, this allows the most cancerous combo yet, holoparasite + dualsword

**Comment by KazeEspada** [comment]
Thunder, shoot the parasite, melee disarm the esworder.

**Comment by Lumipharon** [comment]
>dual sword blocks all the ranged shots
>stand pops out and punches you in the dick if you try melee

Have fun.

**Comment by Fox-McCloud** [comment]
This comes across as a bit extreme. 6 Maybe? Still gives 8 to play with if you want to go double-bladed.

**Comment by PKPenguin321** [comment]
:+1: 
B LO O D
F O R
T H E
B L O O D
G O D

traitors having access to high damage weapons without having to sacrifice all their other utilities is good good good, as demonstrated by the e-dagger. i really like this. :+1: :+1: :+1:

**Comment by Dorsisdwarf** [comment]
:-1: Dual eswords + holoparasite = away mission solo + station trbomurder

**Comment by KorPhaeron** [comment]
Guess a star wars joke isnt worth the balance issues

**Comment by Iamgoofball** [comment]
SPOILERS

**Pull request closed without merging**
