### PR TITLE
we can stop using getFlatIcon?

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
This just works? What am I missing?

:cl: Naksu
code: removed unnecessary getFlatIcons from holocalls
/:cl:

### CODE REVIEW

**Comment by fludd12** [comment]
*proceeds to use getFlatIcon everywhere*

**Comment by Dorsisdwarf** [comment]
I wonder if this'll fix the "all holograms have become 2d and cant face directions" thing

**Comment by Cyberboss** [comment]
Just a misuse, still required for html shit

**Comment by chesse20** [comment]
but should we remove them?

**Pull request merged**
