### PR TITLE
Adds Nuka Cola as a premium item for Robust Softdrinks

### PR DESCRIPTION
**Pull request by swindly**
:cl: Swindly
add: Added Nuka Cola as a premium item in Robust Softdrinks
/:cl:

Ever since I was a little boy, I've had a dream that there were contraband and premium items for every type of vending machine, and I think that there are other people who share this dream.

### CODE REVIEW

**Comment by chanoc1** [comment]
i thought licsened stuff isnt allowed

**Comment by swindly** [comment]
It's already in the game.

**Comment by chanoc1** [comment]
proof?

**Comment by KingPhilipIII** [comment]
Nuka Cola better cause rad damage to someone dumb enough to drink it.

**Pull request merged**
