### PR TITLE
Achievement quirks

### PR DESCRIPTION
**Pull request by Time-Green**
Adds a framework for achievement locked quirks. You do something, and boom you can now select a new quirk! Quirks still cost or give points, and they should generally not give an actual advantage, rather just some fun stuff related to what they did.

:cl: Time-Green
feature: Added a framework for achievement locked quirks
/:cl:
There's an example/test quirk, called instant death. Next person that makes something should probably remove that, if they beat me to it. Until then, it's there as an example.

The functions used to give and take quirks are: grant_quirk(bitflag or ref,"because you suck"), take_quirk(bitflag or ref,"i am an asshole")
Take quirk generally shouldn't ever be used, because taking quirks is fucking brutal.

If you want to give someone the death quirk, call grant_quirk(UNLOCK_DEATH,"kill yourself") on their client.

I've got some plans for this myselfs, but it will be a while from now

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
this should be using the medal system.

**Comment by Razharas** [comment]
Now we just need to tie a parteon to this and share this system with the starting appearance and become dogecoin billionaires

**Comment by fludd12** [comment]
Oooh, I have ideas for this.

**Comment by Time-Green** [comment]
@fludd12 it better not be werecorgis

@ExcessiveUseOfCobblestone didn't even know that existed. Either way this is more memory efficient and more focused on unlocking

**Comment by fludd12** [comment]
I'm thinking a full, goon-style achievement system with medal integration and occasional quirk unlocking

**Comment by ExcessiveUseOfCobblestone** [comment]
@Time-Green we need to not have 5 different achievement systems though is my issue.

If medals suck then we should remove their integration before adding a different unlocking system.

**Comment by ExcessiveUseOfCobblestone** [comment]
Also reinforces #36032

**Comment by Time-Green** [comment]
This system uses bitflag for a TRUE or FALSE scenario, and achievements count the amount of times you did something.
Reworking the achievement system(?) seems like a uhh fun job, but I’m really not going to rework an entire system and fuck with safefiles so someone can have three eyes. At least not in the same PR

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact @Cyberboss @vuonojenmustaturska @KorPhaeron  thoughts code-wise?

**Comment by Repukan** [comment]
Kor is out for the summer

**Comment by ExcessiveUseOfCobblestone** [comment]
I guess you could say the slime is in heat?

**Comment by Cyberboss** [comment]
1. Cobby is right, the hub medal system should be our only achievement system

2. I'm not inclined to gate any sort of content behind achievements, it doesn't fit the ss13 spirit

**Comment by fludd12** [comment]
What about stuff like cloaks or such, earned when completing medals? I think having a cool special aesthetic item for each of the lavaland bosses optionally available would be cool.

**Comment by ExcessiveUseOfCobblestone** [comment]
@fludd12 kor was okay with this back in the day (#19360)

**Comment by ExcessiveUseOfCobblestone** [comment]
http://www.byond.com/games/TgstationHub/TgstationStatsHub#tab=scores

**Comment by fludd12** [comment]
I'm suddenly overwhelmed by the urge to make icons for our medals that actually resemble medals.

**Comment by Cyberboss** [comment]
Capes are purely asthetic. Quirks by their nature, however, are game play
changes.

**Comment by fludd12** [comment]
The quirks system can be used for them, though - a la the comfort item quirk. That way, players could toggle if they want their inventory crowding medal items or not

**Comment by Time-Green** [comment]
Like I said before, these quirks wouldn’t be gameplay changing. Just simple stuff like three eyes or becoming a werecorgi. Both purely cosmetic. It’s supposed to give players a feeling of pride and accomplishment for unlocking a rare quick

**Comment by Mickyan** [comment]
Giving incentives to achievement hunt instead of playing the current round sounds like a dangerous road to go down, regardless of what the rewards are

**Comment by Time-Green** [comment]
That’s already the case though with the current achievement system, and it gives players a reason to keep pushing forwards

**Comment by Cyberboss** [comment]
Then quirks aren't the right system for this sort of thing honestly. Functionally, this should be part of general preferences

**Comment by Mickyan** [comment]
Current achievements are out of the way and you're not constantly reminded about them by seeing someone walk by with a fancy item, as such they're not particularly sought after by players that aren't interested in the achievements themselves

They're also entirely based around lavaland which is already more or less it's own separate little game with its own progression and much more static in nature than the rest of the game

**Comment by ExcessiveUseOfCobblestone** [comment]
@fludd12 you shouldn't have new items based on things you did past rounds. Reskins are fine obv and should be a general pref.

Mutant bodypart unlocks should be appended on the mutant bodypart system though rather than jerryrigging quirks to do it. Those are already opt-in.

**Comment by fludd12** [comment]
We already have a quirk to give a different bodypart, and a quirk to give a special item. I don't see why this wouldn't work in that system.

Anyway, if you think it's best, I'll drop the issue :heart:

**Comment by Time-Green** [comment]
If the majority dislikes it because it’s different, then there’s not really any point in keeping it open...
Chainsaw heads it is

**Comment by fludd12** [comment]
>third eye or being a werefurry are two completely different things.

I... what? I was just suggesting making a quirk that gave you an item. A preference does make more sense for it, I guess.

**Comment by ExcessiveUseOfCobblestone** [comment]
who cares if it's just cosmetic lol

maybe people won't take pride in turning people sideways quickly if they just had benign vanity trophies to show off (unlikely but the rose-tints are so nice!)

**Comment by Time-Green** [comment]
If it’s about people being jealous about cosmetics, then you should remove donor benefits aswell
(Unless you weren’t sarcastic, then ignore me)

**Pull request closed without merging**
