### PR TITLE
Adds droppers to medical protolathes and autolathes

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request

Adds droppers to medical protolathes and autolathes 10 glass+ 30 plastic, tech comes with round-start node basic tools. pill bottles now need plastic instead of metal.
## Why It's Good For The Game

You don't need to bug chemistry or virology for droppers 
Dropper banger
Picture is old its now 30 plastic and 10 glass
## Changelog
:cl: itseasytosee
tweak: droppers are now available at autolathes and medical protolathes
tweak: pill bottles now require plastic instead of metal to print
/:cl:

### CODE REVIEW

**Comment by AnonymousNow** [comment]
For something so simple and yet so important to certain jobs (ie. xenobiology), you'd think you could source another of these without needing to take one from another department.

**Comment by itseasytosee** [comment]
>you'd think you could source another of these without needing to take one from another department.
you would be surprised how reluctant some people are to give out real simple things like that.
Also, do you think plastic would be a better choice or is that bringing the issue back to square one?

**Comment by evilcyborgmrt** [comment]
Spray bottles next plz

**Comment by AnonymousNow** [comment]
Plastic and glass are both viable options for droppers, but make sure that existing droppers are made from (and specifically, can be broken down into) the desired material. Seems obvious, but we still have issues with some items.

**Comment by Tlaltecuhtli** [comment]
if you want them a 100% reliable thing to exist do glass as plastic isnt used and you ll 90% just decon the flaps near the lathe for it
doesnt med vending machine sell these?

**Comment by improvedname** [comment]
Use plastic and glass.

**Comment by itseasytosee** [comment]
Alright I have given it some thought and I think it would be good to have another purpose for plastic other than beakers or fun. Ill make it glass plastic mix. If i do a spray bottle PR they will also likely be made out of plastic.

**Comment by itseasytosee** [comment]
Im also gonna make pill bottles plastic

**Review by kriskog — CHANGES_REQUESTED** [review]
Merge conflict, I changed some stuff around and added a basic medical tech node. Add them there instead. Otherwise, looks good.

**Comment by itseasytosee** [comment]
Thanks

**Comment by itseasytosee** [comment]
There you go all fixed up

**Comment by kriskog** [comment]
Almost, we got some rubber duckies in here now

**Comment by itseasytosee** [comment]
My git Kraken is a mess

**Comment by itseasytosee** [comment]
Should be good

**Review by kriskog — APPROVED** [review]

**Pull request merged**
