### PR TITLE
Removes Magicarps from Xenobiology

### PR DESCRIPTION
**Pull request by IndieanaJones**
## About The Pull Request

This removes magicarps from xenobiology, since everything left in their spell pool is just various damage spells, an animation spell, and the door spell.

## Why It's Good For The Game

No point in keeping them in the pool anymore, since they don't offer anything interesting.  Frankly, it's quite amazing how fast the PR's came to quickly remove the fun of magicarps, and despite the like to dislike ratio, got merged, but as someone who wants at least a bit of quality for the gold slime pool, I'm going to finish the job they should have done themselves.

## Changelog
:cl:
del: Xenobiologists have noted that the gold slime reaction no longer seems to spawn magicarp.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
animation + sentient is interesting tho...

**Comment by anconfuzedrock** [comment]
I was thinking "why not remove the carp from the pool since literally everything it has is unfair except bolt of nothing and spellblade" and I still think that, but if this was on the table I feel it would've been done instead of removing the bolt of change. It's not like it's the only gold slime thing that's used for combat and I recall the door bolt being ye famous olde method of getting minerals when you were lucky to have a competent miner so you just had the carp turn walls into ore doores

**Comment by IndieanaJones** [comment]
> animation + sentient is interesting tho...

It's funny around the first time it happens, but the sentient object can't really do anything but smash things.

> 
> 
> I was thinking "why not remove the carp from the pool since literally everything it has is unfair except bolt of nothing and spellblade" and I still think that, but if this was on the table I feel it would've been done instead of removing the bolt of change. It's not like it's the only gold slime thing that's used for combat and I recall the door bolt being ye famous olde method of getting minerals when you were lucky to have a competent miner so you just had the carp turn walls into ore doores

I liked Change carp because it let xenobio get their hands on creatures not allowed in the gold pool, but the remaining bolts don't warrant it to exist anymore, so I think full removal is for the best.  I'll have to think on something to replace it.

**Comment by Learner10** [comment]
If the argument is sentient can't do anything but smash things, then apply that same argument towards xenobiology in general. Many of said creatures are rather simplistic and don't offer anything interesting. I mean, the tree pole doesn't have any fun gimmicks, but it's been kept around, and neither does a bear besides being a bear. In my opinion, keeping a slightly less magical fish around ultimately doesn't ruin anything, regardless of how powerful and interesting it was before.

**Comment by ExcessiveUseOfCobblestone** [comment]
> if I can't instakill, adminheal, or bypass the gold core slime restriction then may as well remove the whole thing

well okay...

**Comment by IndieanaJones** [comment]
> 
> 
> If the argument is sentient can't do anything but smash things, then apply that same argument towards xenobiology in general. Many of said creatures are rather simplistic and don't offer anything interesting. I mean, the tree pole doesn't have any fun gimmicks, but it's been kept around, and neither does a bear besides being a bear. In my opinion, keeping a slightly less magical fish around ultimately doesn't ruin anything, regardless of how powerful and interesting it was before.

https://github.com/tgstation/tgstation/pull/47858

This was a PR I did a while back which gave a number of xenobio mobs unique abilities aimed at crew assistance.  While it didn't touch all of them and didn't remove all the fat, I felt it was a step in the right direction.  I'd like to do something like this again to further improve the remaining creatures at some point.

**Comment by wesoda25** [comment]
Give them other fluff spells like locker

**Comment by OverlyGeneric** [comment]
It was inevitable. All we can hope for is something more interesting.

If anyone adds phoenixes from pyroclastic anomaly cores would be a good addition to the pool.

**Comment by Jessen21** [comment]
maybe you could move at least a single watcher type back in, give sinew gathering back.

**Comment by Tlaltecuhtli** [comment]
sentient guns can shoot

**Comment by nianjiilical** [comment]
what if we just...gave them new spells

**Comment by Shadowflame909** [comment]
You can theoretically do much worse them bolt of death.

If you add bolt of mind wiping and bolt of lockers into the pool. You'll cause so much salt it'll be unreal.

Mind wiping being the scariest. Since it's literally the "offer control to ghosts" button as a wizard spell.

Antags being mad at being staff of changed will be much more mad at losing their antag entirely.

**Comment by IndieanaJones** [comment]
OK, vote on this comment whether or not you want the PR to stay the same or for new bolts to get added.  I'll either keep the PR or change it depending on the results.

**Comment by Shadowflame909** [comment]
Remove it. Unless your planning on adding some helpful projectiles. Nothing you add can backfire on the user and help the opponent.

Chaos Carp in its current state is just a gun with different deadly bullet effects.

**Comment by improvedname** [comment]
If this isn't merged already in 3 days i'll add unique abilities to the carp which isn't from tbe wizard magic list

**Comment by IndieanaJones** [comment]
This PR is way better: https://github.com/tgstation/tgstation/pull/49580

**Comment by improvedname** [comment]
Oh fuck armhulen beat me to it

**Comment by IndieanaJones** [comment]
Unfortunately, the alternate PR was closed and I was requested by the maker of the other PR to open this one again.

**Comment by IndieanaJones** [comment]
Actually, I'm just going to go make this better at a later point.

**Comment by gamefreak2998** [comment]
This PR reeks of salt. Sad.

**Pull request closed without merging**
