### PR TITLE
Converts R&D Machines AND Hydroponics to WJ's Color Palette

### PR DESCRIPTION
**Pull request by Iamgoofball**
Tried to automate it with WJ's color palette from his thread.

Old Hydro:
oldhydro
New Hydro:
newhydro
Comparison:
hydrocompare

New R&D:
newrnd
Old R&D:
oldrnd
Comparison:
comparernd

### CODE REVIEW

**Comment by kevinz000** [comment]
Breddy good sir :+1:

**Comment by Niknakflak** [comment]
barely look different but ok

**Comment by HankMoodyExperience** [comment]
artificial pull score manipulation huh

**Comment by Iamgoofball** [comment]
Uh,why was this closed

**Comment by pudl** [comment]
Because the color palette isn't happening, and even if it was then it'll be done when WJ completely resprites the machines himself

**Comment by nullbear** [comment]
Goof literally asked wjohnston for tips on how to update the pallets of existing sprites so that it could be done faster, and save wjohnston a bit of effort in the meantime tho.

**Pull request closed without merging**
