### PR TITLE
Plonts takke2

### PR DESCRIPTION
**Pull request by xXPawnStarrXx**
## About The Pull Request
Okay; Take two at this ~~because I totally didn't delete my sprites and set myself back when all I had to do was fix a few merge issues and instead decided to entangle myself in adding another plant.~~
This PR aims to add THREE new plants; Pepper-Corn, Saltcane and Butterbeans.
Peppercorn can be ground for black pepper.
Saltcane can be ground for salt or dried into a seaweed sheet replacement.
Butterbeans can be pressed into a small slice of butter, or ground for a small amount of milk/cream and fermented for yoghurt.
I have also added fermentation of Soybeans to produce soysauce... since that's literally how authentic soysauce is made.
image
image
image
image

## Why It's Good For The Game
I personally feel this will be good for the game as it means the kitchen can rely on their botanists to produce higher quality ingredients and don't have to harass other places or hemorraghe money to make good food for the crew. Easier access to condiments allows for easier production of a varied amount of food.

## Changelog
:cl:
add: Three new plants; Peppercorn, Saltcane and Butterbeans.
add: Soysauce fermentation to soybeans.
add: Saltcane can be dried into a replacement seaweedsheet for sushi.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
> I personally feel this will be good for the game as it means the kitchen can rely on their botanists to produce higher quality ingredients and don't have to harass other places or hemorraghe money to make good food for the crew. Easier access to condiments allows for easier production of a varied amount of food.

To some extent we want some recipes to be hard to produce, it provides meaning. I do not want to invalidate using cargo totally, and this worries me since that seems to be your goal here.
Easier for some might be ok but like if it's in a food and it's rare it is likely MEANT to be that way. Botany might be an appropriate middleground but it vibes a bit off.

@EOBGames please advise

**Comment by SimplySmiley123** [comment]
> > I personally feel this will be good for the game as it means the kitchen can rely on their botanists to produce higher quality ingredients and don't have to harass other places or hemorraghe money to make good food for the crew. Easier access to condiments allows for easier production of a varied amount of food.
> 
> To some extent we want some recipes to be hard to produce, it provides meaning. I do not want to invalidate using cargo totally, and this worries me since that seems to be your goal here. Easier for some might be ok but like if it's in a food and it's rare it is likely MEANT to be that way. Botany might be an appropriate middleground but it vibes a bit off.
> 
> @EOBGames please advise

It's literally just salt, pepper and butter, I don't think there's any complicated recipe using those.

**Comment by xXPawnStarrXx** [comment]
> It's literally just salt, pepper and butter, I don't think there's any complicated recipe using those.

Admittedly, there is also cream, yoghurt and soysauce. They're all admitedly createable in botany and the bar, however

**Comment by EOBGames** [comment]
> > I personally feel this will be good for the game as it means the kitchen can rely on their botanists to produce higher quality ingredients and don't have to harass other places or hemorraghe money to make good food for the crew. Easier access to condiments allows for easier production of a varied amount of food.
> 
> To some extent we want some recipes to be hard to produce, it provides meaning. I do not want to invalidate using cargo totally, and this worries me since that seems to be your goal here. Easier for some might be ok but like if it's in a food and it's rare it is likely MEANT to be that way. Botany might be an appropriate middleground but it vibes a bit off.
> 
> @EOBGames please advise

I'd say that everything here isn't really gating anything, they're all easily produced and/or cheap to buy, so I don't see any harm.

**Comment by Mrfilms** [comment]
Nice job, I hope that someone will eventually think of/implement cooking recipes involving the base crops, butterbeans especially could be useful in a number of dishes as is.

**Comment by xXPawnStarrXx** [comment]
> Nice job, I hope that someone will eventually think of/implement cooking recipes involving the base crops, butterbeans especially could be useful in a number of dishes as is.

If they get merged, I already have a plan to make a few dishes with butterbeans. I also plan to make lizard burger variants without grain or dairy.

**Review by LemonInTheDark — APPROVED** [review]
Code's fine, needs sprite review

**Comment by CacheAtWork** [comment]
Oh nice; Now moffic cuisine won't be so hard-locked behind a cargo/cooldown.

**Review by Wallemations — APPROVED** [review]
Sprites seem _fine_, admittedly they're just recolors but a lot of plants are so it's whatever

**Pull request merged**
