### PR TITLE
Birdboat: Stock computers, lavaland

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: Adds some stock computers and lavaland to Birdboat Station.
/:cl:
- Also merges that fucking telecomms stuff into the general codebase.

### CODE REVIEW

**Comment by Cheridan** [comment]
its already getting tgm'd in #18009

**Comment by coiax** [comment]
@Cheridan that's the Z5 of birdboat, not the actual station

**Comment by RandomMarine** [comment]
While you're touching birdboat, could you apply #17678 to it too?

**Comment by optimumtact** [comment]
Changelog, more like coaixlog

**Comment by Jordie0608** [comment]
Whats wrong with the changelog here?

**Comment by coiax** [comment]
I think oranges is implying that I have a lot of changelog entries.

**Comment by optimumtact** [comment]
it's a tribute to their hardwork

**Pull request merged**
