### PR TITLE
Random Requests 1: Weepo: Let me wear a belt while naked.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Weepo
tweak: You can now wear a belt while naked.
/:cl:

Requested by player.
chrome_2017-01-15_20-26-50

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Feature freeze?

**Comment by Iamgoofball** [comment]
Don't care.

**Comment by Ultimate-Chimera** [comment]
I want it though.

**Comment by SgtxRootbeer** [comment]
So do i

**Comment by Ultimate-Chimera** [comment]
This should be considered as a "fix".

**Comment by Mervill** [comment]
What about all the things that can be attached in the belt slot that aren't belts?

**Comment by Ultimate-Chimera** [comment]
rip

**Comment by Haevacht** [comment]
Unequipping a jumpsuit would still drop the belt, do it right.

**Comment by dannno** [comment]
lazy
and that's coming from me

**Comment by Iamgoofball** [comment]
i pushed a fix but the PR was closed so fuck you

**Comment by XDTM** [comment]
When/if you reopen this, remember there is a check on update_icons that removes stuff in the belt slot if you don't have a jumpsuit. I have no idea why it's there, though.

**Comment by XDTM** [comment]
Unless that was the fix you meant

**Comment by Iamgoofball** [comment]
Why the fuck does update icons do it too

**Comment by RemieRichards** [comment]
if you're going to do this, remove the var that species have to get around it and stuff, gut it entirely or not at all, essentially.

**Comment by Iamgoofball** [comment]
wow i hate species code

**Comment by Haevacht** [comment]
This'll probably lead to more mostly naked lizards, where's your slippery slope now goof.

**Comment by Militaires** [comment]
@RemieRichards that var also affects pocket slots

**Comment by Militaires** [comment]
@RemieRichards that var also affects pocket slots

**Comment by KorPhaeron** [comment]
stale

**Comment by PKPenguin321** [comment]
Fix it pls

**Comment by Mervill** [comment]
If you change `species.dm#576` to `if(!H.w_uniform && !nojumpsuit && !istype(I, /obj/item/weapon/storage/belt))` that will allow "true" belts to be worn without a jumpsuit while preventing things that don't make sense (id, pda, etc) being worn on the belt slot without a jumpsuit.

However there's a realllllly strange bug with `human/update_inv_w_uniform()` (`modules\mob\living\carbon\human\update_icons.dm`) where even if you remove this bit:

```DM
else if(!(dna && dna.species.nojumpsuit))
	// Automatically drop anything in store / id / belt if you're not wearing a uniform.
	for(var/obj/item/thing in list(r_store, l_store, wear_id, belt))
		unEquip(thing)
```

Any item in the belt slot will still be automatically removed then you un-equip the jumpsuit

**Pull request closed without merging**
