### PR TITLE
Hitby messages removed, may help with singularity lag from throwing

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by RemieRichards** [comment]
For reference: Byond sucks ass at outputting text.

**Comment by optimumtact** [comment]
So do I to be honest

**Comment by WJohn** [comment]
Honestly this should apply to explosions too. Grilles and people get like a thousand hit messages that completely flood the chatbox. You KNOW that everybody's impaled a hundred times from an explosion, you don't need to flood the chat box on exactly who and how many identical object has done it.

**Comment by Jordie0608** [comment]
@WJohn It does.

**Comment by WJohn** [comment]
Fantastic then :+1:

**Pull request merged**
