### PR TITLE
Fixes dark matter server crashing, retools dark matter to be less bad

### LINKED ISSUE #8034: Chem smoke with dark matter crashes server
Dark matter smoke creates vortex on human touch, so humans keep moving into the clouds, clouds keep moving too creating infinite loop of vortexes and somehow crashing the server in the end
@Iamgoofball

### PR DESCRIPTION
**Pull request by ghost**
Dark matter reaction resulted in a reagent. This is like making a smoke mixture, and while it makes smoke, it also results in 'smoke' reagent. AKA, what were you thinking goof.

I think the point here was you would be able to make dark matter, and then shoot it at people to make them magnetize things into themselves, but this is a really bad, laggy idea as we've seen from the catastrophic smoke + dark matter thing.

Instead of being a reagent, dark matter is now just a reaction, like smoke. Mix dark matter in a grenade to make a dark matter bomb and pull people into polyacid smoke, but you can no longer cause **everyone who touches dark matter smoke, and every turf that dark matter smoke, to make a ton of fucking vortexes.**

Fixes https://github.com/tgstation/-tg-station/issues/8034

### CODE REVIEW

**Comment by Razharas** [comment]
Very very bad shit instamerging no matter the comments in the code

**Comment by Lumipharon** [comment]
this doesn't just effect liquid dark matter. It as far as I could be bothered checking, effects ALL react on mix goonchems.

Most notable, sorium. Sorium smoke when I tested it, while not server crashing, still lagged the ever loving shit out of the server for 20 seconds.

**Comment by Razharas** [comment]
Well issue was server crashing, this fixes the crashing, everything else is secondary

**Comment by Lumipharon** [comment]
Yeah I'm just saying, the server crash issue stems from a bug that effects more then on chem, so the rest needs to be fixed as well, sooner or later.

**Comment by paprka** [comment]
It's okay, goof's heart was in the right place in the proper spirit of hilarious chemicals.

I'm certain that something went wrong here, if goonstation supports dark matter smoke without crashing and has dark matter reagents i'm not sure what the issue here is because i'm not good at chems

**Comment by Psyentific** [comment]
Goofball, this is why you test your code, retard.

**Comment by Lumipharon** [comment]
Pap the logical thing I can guess for why there is the actual reagent, is the goon has stabiliser - which allows the reagen to form, without causing a reaction. But we don't have it, so it can kindly fuck off.

**Comment by paprka** [comment]
oh, i get it.

don't bully goof this reaction is hilarious, but it should probably be harder to make tbh

also, we need a magnitis reagent, a lot of objects use the CONDUCT flag and it should be used for more things

**Comment by Fox-McCloud** [comment]
Pretty sure this may have been an oversight.

LDM on Goon functions like this: 

- Mix the chems->gets a vortext
- Mix the chems+a reagent called "stabilizing agent" (not on TG)-> get LDM; LDM does nothing by itself, except:
- Heat LDM to a certain point and it will create a vortex.

**Comment by Psyentific** [comment]
Well, if a reagent crashes the server, that is lulzy as fuck. But that should be something hard to make, hard to get the ingredients for, and logged. Something dumb like a mixture of clown blood, a ground up Captain ID, a bunch of really obscure chemicals, all splashed on the HoS's trenchcoat.

**Comment by paprka** [comment]
Oh, yeah, that makes a lot of sense. I wonder if goof plans to implement the stabilizing agent? it would make things like this a lot cooler

**Comment by Fox-McCloud** [comment]
hopefully; smoke powder, flash powder, LDM, and Sorium are all things on Goon; they're acquired by mixing the parent chems with stabilizing agent...and the result is always "heat the chem to a certain point and it does what the parent reagent does".

Allows for some really neat interactions.

**Comment by Lumipharon** [comment]
How does smoke code work on goon? Because that's what's directly causing the (server breaking) lag, the specific interaction of smoke + liquid dark matter the reagent.

**Comment by paprka** [comment]
I don't think anyone would know that besides people who have seen the leak and stuff

**Comment by Razharas** [comment]
Our smoke code is not very good

**Comment by Iamgoofball** [comment]
Yeah, I'll implement a better fix ala Black Powder's functionality

**Comment by Fox-McCloud** [comment]
@Lumipharon 

I'm not 100% sure, but I believe it's something like this:

When the smoke reaction takes place, I believe it does something like this first

for(var/mob/living/V in range(get_turf(L),4))

Then check if they're:

(1)wearing a gas mask OR running on full internals without a gas  mask; if they're not, it will directly add reagents to mobs in range; it doesn't proc ingest or anything like that here, as you can utilize styptic powder and silver sulfa to heal people without poisoning them.
(2)Wearing a full biosuit; if they aren't, apply the TOUCH reaction to the mob

How much of the reagent is added to the mob is dependent on how much was in the beaker...with a minimum value of something like 2-3 that can be added (meaning if you have 0.9 of a unit, it's going to add more than this to the mob itself). The latter mechanic (0.9 thing) was recently changed though, but it's a pretty awesome little trick that allows for some really nifty reactions.

It only applies the reagents once; it's not a persistent cloud.

**Pull request merged**
