### PR TITLE
fix alien organ decay

### LINKED ISSUE #48033: xeno eyes and xeno livers can decay
unlike all of the other xeno organs, these organs can decay when outside of a living creature/an organ fridge

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

this fixes https://github.com/tgstation/tgstation/issues/48033

### CODE REVIEW

**Comment by 4dplanner** [comment]
Changelog

**Comment by ExcessiveUseOfCobblestone** [comment]
is there a reason behind doing this as opposed to the flip side which is give the alien organs standard decay?

**Comment by ATH1909** [comment]
> is there a reason behind doing this as opposed to the flip side which is give the alien organs standard decay?

Other cool organs like the cursed heart don't decay, IIRC.

It'd really suck to have a xeno queen's organs rot before you can extract them all and implant them in a human host (yes, organ fridges exist, but you have to extract the organs before they decay in order to put them in an organ fridge and you can't always immediately extract a xeno queen's corpse from a xeno nest after you kill it).

**Comment by ATH1909** [comment]
Actually, looking at the code, I don't know what would make other xeno organs not decay. I think that might have just been a rumor, in which case this PR would be ADDING an inconsistency, not removing it (I wouldn't be opposed to making all xeno organs decayproof, though).

**Comment by optimumtact** [comment]
this doesn't seem necessary as there are in game solutions to your problem
namely a syringe full of `formaldehyde`, which can be shot from a gun.

**Pull request closed without merging**
