### PR TITLE
Mjolnir resprite

### PR DESCRIPTION
**Pull request by ProtivogaSpriter**
## About The Pull Request

Replaces the old Mjolnir sprites with the new Mjolnir sprites.

Old:
Mjolnir

New:
Mjorngirnnir

## Why It's Good For The Game

Makes the Mjolnir less painful to look at.

## Changelog

:cl:
imageadd: Replaced old Mjolnir sprites with new Mjolnir sprites.
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
Per our discord discussion, this is a very solid improvement over your old sprite, good work. 👍

**Comment by ProtivogaSpriter** [comment]
> Per our discord discussion, this is a very solid improvement over your old sprite, good work. 👍

Cheers!

**Comment by AndroidMK2** [comment]
New sprite looks much more sick and not like some electrified blue brick like the old one.

**Review by Twaticus — CHANGES_REQUESTED** [review]
weapons/hammers_lefthand.dmi:
mjollnir0 - front facing offset, back facing offset
mjollnir1 - front facing offset, right directional flipped

weapons/hammers_righthand.dmi:
mjollnir0 - front facing offset
mjollnir1 - back facing missing pixels, left directional flipped

otherwise it looks very cool

**Comment by ProtivogaSpriter** [comment]
> weapons/hammers_lefthand.dmi:
> mjollnir0 - front facing offset, back facing offset
> mjollnir1 - front facing offset, right directional flipped
> 
> weapons/hammers_righthand.dmi:
> mjollnir0 - front facing offset
> mjollnir1 - back facing missing pixels, left directional flipped
> 
> otherwise it looks very cool

Fixed it, i think. Or i think. Notify me if something is off, and next time *please* elaborate on what's offset and where.

**Comment by Krysonism** [comment]
bild

one dir seems to be 1px misaligned, once this is fixed i think i can merge this.

**Review by Krysonism — CHANGES_REQUESTED** [review]
bild

one dir seems to be 1px misaligned, once this is fixed i think i can merge this.

**Comment by ProtivogaSpriter** [comment]
> bild
> 
> one dir seems to be 1px misaligned, once this is fixed i think i can merge this.

Fixed.

**Pull request merged**
