### PR TITLE
Adds policy text options for Obsessed

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

Obsessed hasn't been converted over to use policy text yet. This fixes that.

## Why It's Good For The Game

Actually obeying the documentation for once. This was originally going to make Obsessed's flavor text tell the player they can't murderbone, but this way each server can make their own decision on that.

## Changelog
:cl:
tweak: The obsessed trauma now includes a policy config option like other antagonists.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Might wanna clean up that changelog a bit.

**Comment by Fikou** [comment]
view https://github.com/tgstation/tgstation/blob/master/.github/POLICYCONFIG.md

**Comment by TheVekter** [comment]
> 
> 
> view https://github.com/tgstation/tgstation/blob/master/.github/POLICYCONFIG.md

Oh, that's neat. I'll implement that when I wake up in a bit.

**Comment by TheVekter** [comment]
If I'm reading the MD file correctly, _all_ flavor text goes in the policy define now. So it's gone.

**Pull request merged**
