### PR TITLE
Viruses related fixes

### LINKED ISSUE #7654: Infected blood + IV drip = crasherooni
Same issue as https://github.com/tgstation/-tg-station/issues/7563 basically

Basically it's this proc.

https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/iv_drip.dm#L88

Inject_blood() works perfectly fine in syringe code for blood virus transfers but it's causing server crashes in the IV drips for some reason. I'm thinking since drip() used processing in life() that it's the same issue as before but it honestly doesn't make any sense in this case.

Virus2 uses optimized code but this chunk of code here:
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/carbon/human/blood.dm#L196

..works perfectly fine for syringe transfers, so this obviously isn't the issue. Same for the old issue of blood splatters/blood drips causing server crashes. The virus transfer code was fine but it caused server crashes for some bizarre reason, when it didn't on baycode/goon scheduler.

Maybe we need bay or /vg/'s improved virus transfer procs from virus2? I don't see any runtimes here so it has to be some fucked up process() shit.

### PR DESCRIPTION
**Pull request by Menshin**
- _Fixes exponentially growing number of diseases on iv_drip giving contaminated blood._
  Fixes #7654.
- _Reagents now reacts when given by iv_drip._
  Side effect is that some reagents are _lethal_ that way (the same problem as with syringes).
  I've also added a _show_message_ variable to some reagents reactions, to prevent message spamming on iv transfusion.
- _Viruses now correctly transfer on blood transfusion._
- _Some code cleaning._

### CODE REVIEW

**Comment by Deantwo** [comment]
:+1:

**Comment by paprka** [comment]
Holy fucking shit menshin you are my hero I have basically no idea how virus transfers work.

You tested this with syringes as well as infected blood in IV drips?

**Comment by Menshin** [comment]
It was working right with syringes to begin with (it was using it's own set of procs).

**Comment by paprka** [comment]
I'm pretty sure it uses the same inject_blood proc though as IV drips do. It goes to trans_to which hands it over to inject_blood if there's blood in the injection.

**Comment by Menshin** [comment]
Viruses transferts are handled by:
* the reagent _reaction()_ proc for reagents (i.e direct virus injecting)
* _on_merge()_ usually called by _add_reagent_ in case of blood transfusion.

The problem with _human/inject_blood()_ was, that _on_merge()_ wasn't called in case of incompatible blood (e.g A+ vs B+).

The 'viruses' part of _carbon/inject_blood_ wasn't doing anything (except crash the server).

**Comment by paprka** [comment]
that's sort of hilarious but i probably should have investigated further, thanks

**Pull request merged**
