### PR TITLE
Fixes missing human icon

### PR DESCRIPTION
**Pull request by 81Denton**
`caucasian_m` doesn't exist inside human.dmi, which made all default humans show up as an error icon in Dream Maker. I added a basic human icon to that file.

### CODE REVIEW

**Review by SpaceManiac — APPROVED** [review]

**Comment by DaxDupont** [comment]
https://github.com/tgstation/tgstation/issues/42154 apparently this is related lmao

**Comment by 81Denton** [comment]
Oh fuck me

**Comment by Memendia** [comment]
There is only 1 direction for the sprite.

@81Denton

**Comment by SpaceManiac** [comment]
see #42155

**Pull request merged**
