### PR TITLE
Misc Guardian changes

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Chaos guardians transfer slightly less damage to their summoner.
/:cl:

Now why would I do this now, when these don't ever show up?

### CODE REVIEW

**Comment by KorPhaeron** [comment]
This might actually be stronger

**Comment by ChangelingRain** [comment]
Maybe, but not setting LITERALLY EVERYONE on fire will probably make it a bit less powerful.

**Comment by KorPhaeron** [comment]
This needs to attack log on bump so the victim will have some proof when he inevitably shoots the wrong guy and admins get involved

Fire is way easier to counter than everyone looking the same though

**Comment by ChangelingRain** [comment]
okay in that case I should probably come up with something New and Interesting instead

**Comment by KorPhaeron** [comment]
I think the hallucination is New and Interesting because nothing else does it, just needs proper logging is all

**Comment by ChangelingRain** [comment]
Yeah but giving it logging will result in it absolutely flooding the logs with it, because it's on bump, so it needs something Better

**Pull request merged**
