### PR TITLE
NERFS HULK

### PR DESCRIPTION
**Pull request by Iamgoofball**
speech because that shits spammy yo

### CODE REVIEW

**Comment by Banana-Fist** [comment]
"hulk op pls nerf"

**Comment by YakumoChen** [comment]
:-1: the entire reason it's there is to tell security who they need to laser down for wall-breaking

**Comment by Shadowlight213** [comment]
This is actually a buff.
The speech is there to stop stealth hulks smashing

**Comment by Iamgoofball** [comment]
is there any way we can make this shit less spammy though

**Comment by YakumoChen** [comment]
make it a random chance?

**Comment by Boggart** [comment]
Anyone who shows up to complain about the nerf, read the changes first.

**Comment by Archie700** [comment]
This is a nerf to hulk killers, not the hulk.

**Comment by GeneralGoose** [comment]
misleading title 
20 years in gulag for false adertisement and buffing hulk

**Comment by optimumtact** [comment]
the solution to a hulk spamming this is to laser it into crit.

**Comment by Iamgoofball** [comment]
Nah it has stun immunity and speed chems

**Pull request closed without merging**
