### PR TITLE
removes singletanks

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

removes singletanks from the game

## Why It's Good For The Game

Single-tanks are not good for the game because:
1. They are ludicrously easy to mass-produce (+ really easy to get the mix) and sometimes go near levels of TTV maxcaps
2. Easy in combat because you can stash them in backpacks, and their explosion is delayed

TTVs are kinda balanced because they cannot be stashed or mass produced, while you can literally just go to the/build an autolathe/engineering protolathe and make shitloads of igniters and whatever trigger you want 
TTVs have a distinct inhand sprite, bulky (non-stashable) unlike single-tanks
On the other hand, single-tanks do not have unique inhands, neither are they bulky so one can just carry like 5 singletanks in a normal backpack, and their explosion is somewhat delayed (not sure, from experience?) so you barely need reflexes to throw a singletank unlike opening a valve on a TTV and throwing it

## Changelog
:cl:
del: Removed singletanks
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
What's the point of removing single tanks if you can do the same with chem grenades and even worse?

**Comment by mc-oofert** [comment]
> What's the point of removing single tanks if you can do the same with chem grenades and even worse?

chem grenades need a lot of prep if youre going for the higher tier explosives
chemical payloads need C4 or gibtonite and you still need sci to research you stuff to make it worthwhile
and you need sci to research explosive weaponry and bluespace beakers for same-tier explosion

**Comment by mc-oofert** [comment]
> I rarely see single tanks used ingame

good for you

**Comment by moocowswag** [comment]
Just make it so you can disarm them via wrench or something to release the gas in them. Would you rather deal with a tiny fire or an explosion..

**Comment by BlueMemesauce** [comment]
> I rarely see single tanks used ingame

They've seen a recent spike in usage on Terry which is probably why this PR was made now

**Comment by MTandi** [comment]
> chem grenades need a lot of prep if youre going for the higher tier explosives chemical payloads need C4 or gibtonite and you still need sci to research you stuff to make it worthwhile and you need sci to research explosive weaponry and bluespace beakers for same-tier explosion

You can just grind plasma and make a plasma fire chem grenade, just like the single tank bomb, it doesn't need a lot of prep. Just autolathe is enough. You just need a source of plasma. For grenade you take it from any protolathe and grind. And for singletank you need to find a plasma tank. It's basically the same.

**Comment by MTandi** [comment]
> Just make it so you can disarm them via wrench or something to release the gas in them. Would you rather deal with a tiny fire or an explosion..

Can't you already disarm it by picking up and stopping the timer, or dissasembling it in place to remove signaller?

**Comment by Jackal-boop** [comment]
> 

Yes

**Comment by NamelessFairy** [comment]
Decided to do a quick log dive since I sensed inexperience with actually encountering singletanks regularly in your why its good for the game and felt this was a reactionary ided PR.

Full logs available at [204101](https://tgstation13.download/parsed-logs/sybil/data/logs/2023/04/20/round-204101/)
Logs shown only contain the most severe part of the PR creators chat logs.
image
PR is blatantly a ided PR although it seems like you only intended a nerf until you realized you had a chance to piss off the player who killed you in a meta context and switched it to a full removal (mald PR **to make you mald**). So this isn't exactly an ided PR in the traditional sense but more of a PR with the explicit intent to get revenge on the player who killed you which is particularly nasty.

**Comment by rageguy505** [comment]
> Just make it so you can disarm them via wrench or something to release the gas in them. Would you rather deal with a tiny fire or an explosion..

using a wrench already disarms them

**Comment by mc-oofert** [comment]
> Decided to do a quick log dive since I sensed inexperience with actually encountering singletanks regularly in your why its good for the game and felt this was a reactionary ided PR.
> 
> Full logs available at [204101](https://tgstation13.download/parsed-logs/sybil/data/logs/2023/04/20/round-204101/) Logs shown only contain the most severe part of the PR creators chat logs. image PR is blatantly a ided PR although it seems like you only intended a nerf until you realized you had a chance to piss off the player who killed you in a meta context and switched it to a full removal (mald PR **to make you mald**). So this isn't exactly an ided PR in the traditional sense but more of a PR with the explicit intent to get revenge on the player who killed you which is particularly nasty.

bro pulled up the profile to have a point 💀

**Comment by mc-oofert** [comment]
> > Just make it so you can disarm them via wrench or something to release the gas in them. Would you rather deal with a tiny fire or an explosion..
> 
> using a wrench already disarms them

rushing an about-to-explode explosive is a pretty shitty idea

**Comment by rageguy505** [comment]
> > > Just make it so you can disarm them via wrench or something to release the gas in them. Would you rather deal with a tiny fire or an explosion..
> > 
> > 
> > using a wrench already disarms them
> 
> rushing an about-to-explode explosive is a pretty shitty idea

bomb defusal is usually a pretty shitty idea already without the movie timers the syndi bombs have

**Comment by rageguy505** [comment]
> 

im pretty sure he means plasma tanks as in canisters. Singletanks can be made from any airtank including jetpacks and emergency o2 tanks.

**Comment by mc-oofert** [comment]
> im pretty sure he means plasma tanks as in canisters. Singletanks can be made from any airtank including jetpacks and emergency o2 tanks.

i dont think thats possible to confuse a tank and a canister theyre like two distinct words

(also you can craft canisters for like 10 metal, and a cell if you wanna be fancy)

**Comment by moocowswag** [comment]
> 2. Easy in combat 

Idk man i think you need a wall between you and who youre fighting or else theyll just either disarm it or rush you down.

**Comment by mc-oofert** [comment]
> > 2. Easy in combat
> 
> Idk man i think you need a wall between you and who youre fighting or else theyll just either disarm it or rush you down.

if both of you explode its still a winwin
also if you just throw it down a hallway they would just explode

**Comment by SinfulBliss** [comment]
> > What's the point of removing single tanks if you can do the same with chem grenades and even worse?
> 
> chem grenades need a lot of prep if youre going for the higher tier explosives chemical payloads need C4 or gibtonite and you still need sci to research you stuff to make it worthwhile and you need sci to research explosive weaponry and bluespace beakers for same-tier explosion

incorrect, you can mass produce n2o nades just as fast as singletanks. the explosion is only marginally smaller but they still gib and create like a 2x2 devastation. they're even smaller and you can fit tons of them in your bag. only requires metal to make a casing and two large beakers for the n2o compared to the various components needed in an assembly bomb

**Comment by moocowswag** [comment]
> incorrect, you can mass produce n2o nades just  but they still gib and create like a 2x2 devastation

1x1 with 100u beakers like 5x5 with metamaterial beakers

**Comment by Jackal-boop** [comment]
Balance with a sledge hammer. This completely removes crafty scientists doing ordanance with single tanks. I'd be severely disappointed if this was merged. Especially as its coming from a place of malice

**Comment by moocowswag** [comment]
Keep in mind i do also plan on throwing a massive wrench in explosive balance very soon if maintainers will let me go near it

**Comment by Rex9001** [comment]
Singlecaps are an issue of mass production imo, whilst you can only make about 1-5 maxcaps during the typical war ops round you can make around 30~ singletanks. Singlecaps in their current state function as a great nukie killer akin to espears. Removal should however always be the last option imo and singlecaps could be fine with a few nerfs.

**Comment by moocowswag** [comment]
> Maybe add some randomness to it as for IED, so that it can trigger by accident and kill the attacker. Or not wind up at all akin to mosin jamming. Makeshift weapon vibes.

that would basically subvert the simulation of atmos cooking in the tank until it hits a critical threshhold

**Comment by mc-oofert** [comment]
> Balance with a sledge hammer. This completely removes crafty scientists doing ordanance with single tanks. I'd be severely disappointed if this was merged. Especially as its coming from a place of malice

why would you do ordnance with singletanks

**Comment by mc-oofert** [comment]
> most other explosives can be used with signalers remotely, single tanks you prime and it goes off based on how often the server feels like updating atmos

its often in the attackers advantage

**Comment by MTandi** [comment]
> that would basically subvert the simulation of atmos cooking in the tank until it hits a critical threshhold
> 
> its already makeshift in a sense that youre having atmos cook in a tank and the time it takes is based on the moles, heat, and how well the server is feeling

I'm talking about the igniter Like when you flicker a cheap gaslight, it should have a chance of not producing spark. So you need to restart the timer or send the code once again.

**Comment by mc-oofert** [comment]
> Using explosives like that requires consistently precise timing

just use tripwire

**Comment by mc-oofert** [comment]
> send the code once again.

if people knew it could malfunction and not spark and you would have to send the signal again wouldnt they just spam the "Send Signal" button

**Comment by MTandi** [comment]
> > send the code once again.
> 
> if people knew it could malfunction and not spark and you would have to send the signal again wouldnt they just spam the "Send Signal" button

The igniter has a cooldown

**Comment by SinfulBliss** [comment]
> > incorrect, you can mass produce n2o nades just  but they still gib and create like a 2x2 devastation
> 
> 1x1 with 100u beakers like nearly or about 5x5 with metamaterial beakers
> 
> The refinement/prep of n2o for explosives is slow because you have to adjust the temp in two steps
> 
> And if youre using plumbing any cmo/ai worth their salt will know you have an n2o factory

n2o nades will delimb and instakill if you're next to them. assembly bombs will gib if you're next to them. one is a small item the other is medium sized and specifically a BOMB instead of a grenade so it makes sense for it to be larger

**Comment by ChungusGamer666** [comment]
Quintessential ided PR, congratulations OP

**Comment by mc-oofert** [comment]
> Quintessential ided PR, congratulations OP

what kind of fucking lingo is  quintessential

**Comment by BlueMemesauce** [comment]
*People on terry start mass producing bombs that can gib in a radius and can be made quickly in the round, someones dies to it and realizes it's an issue and makes a pr to fix it* "i ded pr your pr is invalid"

Playing the game and finding issues is how most fixes are created, we cant just magically know everything about the game until we find out about it

**Comment by moocowswag** [comment]
> n2o nades will delimb and instakill if you're next to them. 
 
Delimb maybe instakill no

n2o espear was meta for a reason you gib someone next to you and then you only take heavy which usually just delimbs unless you have sec jumpsuit

**Comment by redlink2579** [comment]
Ah yes what a best way to reduce single tank mass-production problem by remove them entirely

**Comment by Jackal-boop** [comment]
> _People on terry start mass producing bombs that can gib in a radius and can be made quickly in the round, someones dies to it and realizes it's an issue and makes a pr to fix it_ "i ded pr your pr is invalid"
> 
> Playing the game and finding issues is how most fixes are created, we cant just magically know everything about the game until we find out about it

"A pr to fix it". Its not, it's a full removal of an interesting game mechanic

**Comment by mc-oofert** [comment]
> > _People on terry start mass producing bombs that can gib in a radius and can be made quickly in the round, someones dies to it and realizes it's an issue and makes a pr to fix it_ "i ded pr your pr is invalid"
> > Playing the game and finding issues is how most fixes are created, we cant just magically know everything about the game until we find out about it
> 
> "A pr to fix it". Its not, it's a full removal of an interesting game mechanic

""""interesting""""

**Review by ZephyrTFA — CHANGES_REQUESTED** [review]
I'm not sure I can agree with a full removal.
If they are really a problem I think it would make more sense to nerf them over removing them.
Perhaps a explosive power downgrade?

**Comment by san7890** [comment]
@LemonInTheDark @Mothblocks I remember hearing that you both had strong opinions regarding the balance of singletanks (whoops if I'm wrong)- do you think this is a fair step forward in overall game design?

**Comment by Mothblocks** [comment]
i had strong opinions about singlecaps, aka ordinary oxygen tanks and such being used as bombs. the bespoke single tank i don't really have thoughts on

**Comment by san7890** [comment]
Ah, I confused myself then. Apologies

**Comment by LemonInTheDark** [comment]
#### I hate atmos players (STOP CALLING THEM SINGLECAPS)

Before I start, single tanks are a confusing name. These are bombs created with assembly parts (ignitors, etc) and a gas tank of some form.
The explosion they produce is very basic. based off a series of thresholds based off the temperature of the mix (hotter -> better), and the ratio between plasma and oxygen.

image

There is in theory a "best" explosion here, since higher temp means you can fit fewer moles. 
This makes atmos nerds unhappy, since it makes these sorta boring. Not a whole ton to optimize for here.

#### Why I don't like this pr

If memory serves that optimal explosion isn't insanely powerful. I am very unsure on the "close to a maxcap" claim of yours.
The largest explosion produced by a single tank in the nameless linked round was (2, 3, 3, 0)
that is, 5x5 of dev, 7x7 of heavy and light, and 0 of flame

For context, a maxcap (on live, it's config'd) is 5, 10. 20, 20. The dev is close, but everything else is wayyyyy off.

They don't have unique inhands, but they do have inhands, and they only share those sprites with partially built assemblies, which almost none is carrying around.

The argument about delay is silly on all counts, since both ttvs and singletanks support signalers. They're both remote det, and there's no chance of overcooking them in either case.

I don't even like these things, they're boring and hardly ever used, but that's not reason to nuke them, especially when this is very much an IDED thing.

#### Potential future improvements

I'd be open to making them less carry-able (tho that isn't really all that productive), or further reducing their impact range, and maybe making the thresholds more lenient, to carve them out a niche as easy to produce but light explosives for atmos. 
They do suck currently, but mostly because they're really uninspired.

I am not happy with the idea of you making those changes however, since I don't really trust current you to think past your recent experiences with the things, to do anything but nerf them into further irrelevance.

I'm closing this pr for these reasons. Other maints are free to reopen if they thing something productive can be done here, but I honestly think you oughta cool off a bit.

**Comment by moocowswag** [comment]
oh these are the crappy assembly bombs not the single caps?

I thought we were talking about actual single tanks this entire time lol why would that get removed.

**Comment by mc-oofert** [comment]
and so ends our little sisyphean task here

also who the fuck calls them singlecaps????

**Comment by LemonInTheDark** [comment]
NONE YOU FOOL, BECAUSE THEY AREN'T SINGLECAPS
People don't call singletanks singlecaps, they call singlecaps singletanks because the actual singletank is historically so underused that they don't realize it exists

**Comment by mc-oofert** [comment]
> NONE YOU FOOL, BECAUSE THEY AREN'T SINGLECAPS People don't call singletanks singlecaps, they call singlecaps singletanks because the actual singletank is historically so underused that they don't realize it exists

whar

**Comment by nukularpower** [comment]
thank goodness for you Lemon

**Pull request closed without merging**
