### PR TITLE
Nerfs Handcuffs

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
You can open doors while handcuffed. I'm not sure if this is a good idea or not.
 or "realistic" (do our airlocks open like those doors at the grocery store or do they require you to swipe your ID?)

### CODE REVIEW

**Comment by Jalleo** [comment]
Its both.

**Comment by ma44** [comment]
How do the doors work anyway

**Comment by AnturK** [comment]
Does the handcuff delay still apply ?

**Comment by Sj212** [comment]
I think they're like the ones at the grocery store considering they open for animals etc.

**Comment by Lexorion** [comment]
Depends on the area I guess? You could make it similar to walking around with no ID,public access doors still open while department doors won't.

**Comment by Aloraydrel** [comment]
If doors dont require you to swipe then how do you get shocked

**Comment by Jalleo** [comment]
There is enough of a energetic buildup to surpass the required amount for it to reach you.

**Comment by Shapsy** [comment]
You don't notice the door didn't opened and walk face first into it

**Comment by MrPerson** [comment]
Lovely how everyone is focusing on the wrong things. Stop with the fucking realism arguments you cockgoblins.

I'm on board with this. Being handcuffed sucks enough already, but this would make escaping more interesting and fun.

**Comment by lzimann** [comment]
but now escaping from security is super easy and not rewarding :^)

**Comment by Dorsisdwarf** [comment]
Being handcuffed needs to not let you through any doors with an access requirement, so you can escape down public halls but not vanish into somewhere sec has no access to

**Comment by ike709** [comment]
>Being handcuffed needs to not let you through any doors with an access requirement, so you can escape down public halls but not vanish into somewhere sec has no access to

this

**Comment by Supermichael777** [comment]
how about you need to pull out your id every time you need to go through a door
this would prevent prisoners in high access areas from running and solve the inconsistency

**Comment by Sarcalogo** [comment]
KorPhareon your girlfriend is cute.

**Comment by KorPhaeron** [comment]
Thanks

**Comment by optimumtact** [comment]
This is a roundly terrible idea Kor, fleeing and evading is far too easy, please reconsider this.

You can nerf security in many ways but this is the one that will make it nearly impossible to play.

**Comment by KorPhaeron** [comment]
It takes a pretty colossal fuckup to have someone running free once cuffed though, since they are entirely incapable of doing anything once you are pulling them

**Comment by yackemflam** [comment]
I support this really.
Just bucklecuff the fucker if you are scared that he might escape.

**Comment by nullbear** [comment]
As jalleo said. Prevent them from opening any doors that require access. Consider all-access doors 'motion sensored'

**Comment by Jalleo** [comment]
Actually I was saying that the doors can technically auto open from RFID, swiping it or motion sensor (No access doors)

**Comment by PKPenguin321** [comment]
close why

**Pull request closed without merging**
