### PR TITLE
Vending machines now support categories (and premium/contraband is moved there), adds it to the Clothesmate

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
image

CC @Twaticus 

## Why It's Good For The Game
Makes stuff more organized and lets us add more things without making the lists inscrutable.

## Changelog

:cl:
qol: Vending machines now support categories. Premium/contraband is moved to categories, and the ClothesMate has special categories for different levels.
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
thanks mothman

**Comment by SpaceSmithers** [comment]
Will this affect the auto-generated wiki template?

**Review by stylemistake — APPROVED** [review]
Very basic looking UI, but nice.

**Comment by Wallemations** [comment]
Yes!!!!!!!!!!!!!!!!!

**Comment by ArcaneMusic** [comment]
If I could offer some suggestions:
* Could you move the categories below the vending UI's ID section? That way you're following the UI from the top-down when you're looking at items to buy.
* Can you also put the categories within a section block to match with the purchasable items section and the ID section?

Also fantastic work mothblocks

**Comment by Mothblocks** [comment]
> Could you move the categories below the vending UI's ID section? That way you're following the UI from the top-down when you're looking at items to buy.

It would be worse UX because the categories can expand or not show at all, meaning you'd get inconsistent clicks depending on the vending machine

> Can you also put the categories within a section block to match with the purchasable items section and the ID section?

Yeah

**Comment by Mothblocks** [comment]
image

Looks nice @ArcaneDefence

**Pull request merged**
