### PR TITLE
Cuffs and sec clean up

### PR DESCRIPTION
**Pull request by akenworthy87**
Sometime last year sec officers lost one of the two pairs of cuffs they started with (I think its when the adv taser was added on spawn, cuffs used to be in the armor slot and were replaced by the taser but never placed anywhere else)
Seeing as cuffs are the only thing stopping sec officers beating the clown to death, I'm readding them.

I've also done a general clean up on sec lockers, removing the extra standard headset (why the f weren't these just replaced by the bowmans in the first place?), and stuffed the locker contents into the sec belts - because fuck the RSI inducing clickfest that is gearing up.
Reordered some of the contents of lockers, again for less repetitive clicks.

Gave the HoS a proper stun baton (I've notice most HoS's pinch a spare one from an officer's locker).
Swapped the detectives collapsible baton for a classic baton, seeing as they're as shit as collapsible batons now and fit the detective's film noir look better. Also gave him some pepperspray because its terrible enough for him to use.

:cl: Malkevin
tweak: Sec officers have two sets of cuffs again (one on spawn, one in locker)
tweak: Done some optimisation of sec spawn equipment lists and lockers to remove some of the repetitive clicking, sec belts are now preloaded with equipment.
tweak: HoS has a full baton instead of the collapsible one
tweak: Detective has a classic police baton and pepper spray instead of the collapsible baton (someone made police batons shit, so don't get overly happy)
bugfix: pop scaled additional lockers spawned were the wrong type, changed them to the right type which has batons now (actually belts now that I've changed them).
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
:cl: not :CL:

Other than that, looks okay, I think the extra headset was so people could choose between the two (as if anyone would pick the weaker headset anyway)

**Comment by KorPhaeron** [comment]
>(as if anyone would pick the weaker headset anyway)

I dealt with ~100 comments of "I dont like how the bowmans looks on my character" when I put the bowmans from the captains closet onto his head, you never know

**Comment by Malkevin** [comment]
Really? The changelog parser is case sensitive? What is the dos era?

Yeah but Captain's just an assistant thats too lazy to steal his all access, in the game of security you win or you die and then get shoved in a maint locker or tossed out to feed the space carp.

**Comment by Zilenan91** [comment]
I think police batons, if that's the baton we're talking about, have a bugged sprite currently. Please keep them with telebatons.

**Comment by Malkevin** [comment]
It took less time to fix the sprites than it would to change the batons back.

**Comment by KorPhaeron** [comment]
>Gave the HoS a proper stun baton (I've notice most HoS's pinch a spare one from an officer's locker).

He has one in his own locker actually

**Comment by Malkevin** [comment]
Matches sec officers

**Comment by Shadowlight213** [comment]
Sec buffs reeeee.

**Comment by Metacide** [comment]
Looks handy, thanks :+1:

**Comment by Malkevin** [comment]
merge?

**Pull request merged**
