### PR TITLE
New dress jackets for sec, adds HoS trenchcoat to cargo crate

### PR DESCRIPTION
**Pull request by TheVekter**
Added a new dark navy and tan jacket for Sec officer, Warden and HoS. These already existed in the .dmi, but hadn't been implemented.

These can be obtained from Cargo in the security clothing crate.

Also added to the crate was the HoS Armored Trenchcoat. As a balance measure, the crate now costs 35 points.

### CODE REVIEW

**Comment by SconesC** [comment]
Why add the armored trenchcoat? Sounds like an absolutely disgusting powergaming crate that will never be used for anything but that.

Honestly I really like how the HoS starts with only his own coat and the spare in his locker. Have you seen the stats on it? Shit's crazy. Also why would you need to order more. Ever.

**Comment by Dorsisdwarf** [comment]
Yeah. Also this wasn't what they meant when they said "port millitary jackets"

**Comment by TheVekter** [comment]
I figured it'd be worth testing out. And what jackets did the mean?

**Comment by Thunder12345** [comment]
The green camo jacket from NT, I think

**Comment by Cheridan** [comment]
35 points for the best armor in the game is a steal. I don't think it should be added to a crate at all.

**Comment by xxalpha** [comment]
BLUECURITY FOREVER

**Comment by TheVekter** [comment]
I gooooooooofed

**Pull request closed without merging**
