### PR TITLE
The proc that calculates the force of a fish now takes metalgen into consideration.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This is more of a nit than anything. The game is so full of different features, preventing each and every single mechanic from getting in the way of something is a sisyphean task, yet we try, so one must imagine a contributor happy.

## Why It's Good For The Game
Consistency.

## Changelog
It's nothing note-worthy.

### CODE REVIEW

**Comment by nianjiilical** [comment]
fishes' greatest warrior

**Comment by necromanceranne** [comment]
Baller.

**Comment by Loafin34** [comment]
i can't wait to see my titanium swordfish rip through nukies like an esword through a monkey

**Comment by Time-Green** [comment]
You got fish conflicts

**Review by Time-Green — APPROVED** [review]

**Pull request merged**
