### PR TITLE
Makes gender change potions more noticeable

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by Expletive** [comment]
slippery slope

**Review by Cyberboss — APPROVED** [review]

**Comment by The-clown-known-as-Pepe** [comment]
i literally changed kevinz gender yesterday

salty pr :^)

**Comment by Nilons** [comment]
>when you get someone so fucking bad they try to pr a change about it

**Comment by kevinz000** [comment]
try != did

**Pull request merged**
