### PR TITLE
Add syndicate tgui style; overhaul colors

### PR DESCRIPTION
**Pull request by neersighted**
All behind the scenes, but at least I got the syndicate style prototyped.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Needs more black and less dark grey and blue; syndicate colors are black and red with light green(RGB 128, 255, 128) as a secondary lighting color.

**Comment by KazeEspada** [comment]
They also enjoy white. As seen in the syndie balloon.

**Comment by Bawhoppen** [comment]
>syndie balloon

>being used as reference

**Comment by xxalpha** [comment]
Nice.

**Comment by Bawhoppen** [comment]
wait I forgot, this is more fodder for my feature freeze argument

**Comment by neersighted** [comment]
Not a feature, more of a port of the old syndicate style to the new tgui.

**Comment by duncathan** [comment]
This is technically a refactor of something old nano had @Bawhoppen

**Pull request merged**
