### PR TITLE
Captain 2.0: Midnight Blue Edition!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Been a bit since my last foray, but here's a new PR fresh out of the oven!

This PR redoes all of the captain's clothes, updating it to a new and elegant standard!

image

Credit goes to @axietheaxolotl for doing a majority of the work, primarily the jumpsuits, the navy cap, the formal coat (normal and alt), and the main palette!

This PR also makes it so that the laceups are now the default footwear of captains.

## Why It's Good For The Game
The captain was beginning to show their age, and it was time to give it an update in aesthetics as we slowly but surely update the jobs to better visual standards!

## Changelog

:cl: Axietheaxolotl, PositiveEntropy
imageadd: Resprites all of the captain's clothes!
/:cl:

### CODE REVIEW

**Comment by bruhman8ghughug** [comment]
i love the sprites, but i dont like the N on the back of the coat, and can you show the modsuit sprites active instead of just it off on the back slot?

**Comment by YakumoChen** [comment]
the colours are kinda muted

**Comment by Imaginos16** [comment]
> 

If you're referring to the carapace, that's how it looks like. There was never any modsuit on the backslot of any character in the screenshot

**Comment by Likteer** [comment]
Inspired by Captain Stern according to Viro

https://www.youtube.com/watch?v=Lqsg1RE6Jag

**Comment by DaxDupont** [comment]
These are beautiful, thank you

**Pull request merged**
