### PR TITLE
allows badminning what space is made out of 

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by Nabski89** [comment]
Help me out. What fun things can you do with this and how would you do it?

**Comment by Shdorsh** [comment]
Sounds _fun_

**Comment by BeeSting12** [comment]
this allows you to edit the gases on a space tile correct?

**Comment by Time-Green** [comment]
Yeah, you could turn space into miasma now

**Comment by Time-Green** [comment]
You’d probably need the make a datum for most special gas effects, wich could then be globally applied or removed.
No idea how that would affect performance on such a large scale, and I don’t think it would be worth it for badminnery

**Comment by davethwave** [comment]
Huh, when you do the edit perhaps make it only effect the z zone you are in?

**Comment by CthulhuOnIce** [comment]
How would one use this ingame?

**Comment by kingoftheautism** [comment]
No fun allowed boys

**Comment by Shdorsh** [comment]
Should have PRed it to hippie maybe.

**Pull request closed without merging**
