### PR TITLE
Adds custom sushi rolls and gives sushi it's own dm file

### PR DESCRIPTION
**Pull request by Toastgoats**
## About The Pull Request

This pull request uses the overlay added to the vegetarian sushi roll to enable the creation of custom sushi rolls, which can take a maximum of 6 ingredients and work effectively identical to custom bread, albeit with a some attackby crafting instead of baking

To create custom sushi rolls:

sushisheet1
⠀↓⠀⠀ Click on a seaweed sheet with boiled rice in hand.
sushisheet-export
⠀↓⠀⠀ Add ingredients and voila!
sushi

## Why It's Good For The Game

Sushi bar chef is a very good gimmick, and this pr helps to develop on the pull request that added sushi in the first place, while giving chefs another excuse to experiment with sushi even if they lack the ingredients for the current sushi recipes.

Also, moving sushi dishes to their own dm file should allow for a bit more modularity and improve readability when adding future sushi dishes.

## Changelog

:cl:
add: It is now possible to make custom sushi rolls by adding boiled rice to seaweed sheets.
imageadd: Unfinished sushi roll sprite
code: Moved sushi related dishes to a new sushi-specific dm file
/:cl:

### CODE REVIEW

**Comment by Toastgoats** [comment]
I might mark this as a draft if it doesn't compile right, it worked the last time I checked but vscode was being fucky.

**Comment by Toastgoats** [comment]
Never added a new file before so I'm assuming I missed something while working in vscode that github doesn't cover.

**Comment by Toastgoats** [comment]
Oh I missed a var fuck

**Comment by Toastgoats** [comment]
> what does do in regard to #67239 which also added custom sushi

Shit there was already a custom sushi pr?

**Comment by Toastgoats** [comment]
Closed because I didn't think there'd another custom sushi pr, will bring this back later as a sushi expansion with new dishes.

**Comment by MidoriWroth** [comment]
i like the part about the rice being spread over the unrolled sheet though! i'm surprised i didn't think of that. good idea!

**Comment by Toastgoats** [comment]
> i like the part about the rice being spread over the unrolled sheet though! i'm surprised i didn't think of that. good idea!

Thanks! I'll probably bring that aspect back as a new pr sometime if it's cool with you.

**Comment by MidoriWroth** [comment]
> > i like the part about the rice being spread over the unrolled sheet though! i'm surprised i didn't think of that. good idea!
> 
> Thanks! I'll probably bring that aspect back as a new pr sometime if it's cool with you.

yeah 100%!

**Comment by ShizCalev** [comment]
Do itttttttt

**Pull request closed without merging**
