### PR TITLE
[WIP] players can possess only one spider per round

### PR DESCRIPTION
**Pull request by Ghilker**
### THE IDEA IS STILL GOING ON #53685 LEAVE FEEDBACKS THERE
The main scope of this PR is to stop people from abusing the spider ghost role as an easy way to re-enter the round multiple times with an easy antag role, to stop metagaming (many people after dying as spider take another one to go back and finish the job, sometimes even multiple times) and to give the station a chance to fight spiders without having an almost infinite number coming out of the pipes.

## Why It's Good For The Game
See above

## Changelog
:cl:
balance: users can play spiders ghost role only once per round
/:cl:

### CODE REVIEW

**Comment by Jimmius** [comment]
Seems a bit arbitrary, you can take multiple xeno spawns, multiple venus human trap spawns, or any other "round ending sentient team antag". Are spiders so above  the power curve that they need this without applying it as a blanket rule for similar threats? Can they even heal without people putting bruise packs on them like xenos can?

**Comment by Ghilker** [comment]
Well first yes, spiders are above the power curve since they can spawn multiple spiderlings with one player killed while xenos kill one player to spawn one xeno (sure ghosts should only take one body too); other than that i could definetly make all ghost roles like this.

**Comment by vkalls** [comment]
Would a cooldown for when you can join as a spider be possible? That might work a little better to stop the metagaming, but still providing a way for players to rejoin the round.

**Comment by Timberpoes** [comment]
I'm Commander Timberpoes and this is my favourite PR on the repo.

The concept has my approval and I'm happy to implement a "one-player, one-spider" restriction.

However, I am happy to also consider cooldown timers or other suggerstions that may form a compromise.

It is also important to consider that there is a traitor item that may be impacted by this - `Australicus Slime Mutator` - But nobody likes Xenobiologists anyway.

**Comment by Jimmius** [comment]
the traitor item is the ONLY thing impacted by this, event spiders aren't mass sentient, an admin or xenobiologist would have to offer each one to ghosts individually

**Comment by Tlaltecuhtli** [comment]
seems bad as there will be 200 braindead spiders  after the first 10 ghosts suicided on security

**Comment by Ghilker** [comment]
> seems bad as there will be 200 braindead spiders after the first 10 ghosts suicided on security, we can always just remove broken stuff....

That's on them tho.. They could easily bring those brain dead spiders to public hallways while they increase their numbers.

I'm open to suggestions but I don't think that adding a timer is the right way, what would the timing be?

**Comment by Tlaltecuhtli** [comment]
3min?

**Comment by itseasytosee** [comment]
if the issue is spiders are too strong, wouldn't it make sense to nerf spiders? reducing the number of spiderlings created, or having them need a human rather than a monkey? Perhaps spawning brainless spiders from monkeys or something.

**Comment by IndieanaJones** [comment]
This is an extremely disappointing PR.
Out of all the ways you can solve this problem, this is by far the worst solution available.  What this does is essentially make spiders useless, as their entire strength lies in the fact that there's a bunch of them and be sentience'd over again to make use of their very high numbers.  If you limit every person to one spider, it ruins them since you might lose that one spider to something very lame like spawning into a venting room or something like that.  I will not deny that spiders are too strong in their current form, but what spiders honestly need right now is a rework to their mechanics to properly balance their overwhelming nature and stats to be more fitting for a swarm-type monster, along with their reproduction system, but all this PR serves to do is to softly remove them from the game without explicitly doing so.

While this PR serves to nerf spiders, it does so in the most un-fun and "I ded" way possible.  If you truly cared about making it fun for both sides, I feel that you would've taken a more balance/rework-sided approach to this instead of slapping spiders with something as miserable as limiting every ghost to a single spider.  If this gets merged, all it does is effectively make spiders suck until someone who actually cares takes their time to give the proper dedication and thought on how to balance them properly to not only undo the current design flaws, but your crappy 5-minute PR.

**Comment by JenqaDev** [comment]
how mad do you have to be to remove such thing...
someone killed you as spider so now you're limiting them to 1 life? outraging

**Comment by Ghilker** [comment]
exactly the opposite, I was the one corpse swapping while killing people and it was stupidly powerful since these mobs have an stupidly huge amount of health

**Comment by Jimmius** [comment]
Personally, the biggest issue I have with Spiders is that they're very easily able to get literally anywhere on the station. They have decent movement speed, can ventcrawl, and have very high object damage, making locked doors or reinforced windows extremely small hurdles that make locking out spiders almost impossible, even if you weld the vents and arm up. Xenos are comparatively easy to keep out of places  once the vents are secure. 
Indeed, the "meta rush" problem of a spider dying over and over only to take another spawn and come at you again is caused by this- Once they've smashed down all the doors to where you are, they can freely run at you with nothing in their way to make them reconsider. They have the powerful ability to lay webs, effectively "taking territory" in the same way xeno weeds do, except they're never really used because there's no need for slow expansion and area control when you can just find a target in deadchat, smash down everything in between you and them, and then charge them over and over until they run out of ammo or the round ends.
Reducing their ability to just instantly bruteforce their way through anything and trying to encourage a slower spread of the spiders (and also creating a frontline that the crew can push back against) might make them a bit more fun to fight against, or at least reduce the number of people meta rushing the same person over and over

**Comment by MrStonedOne** [comment]
Make it a cooldown, make it a config, default it to 7 minutes.

**Comment by zxaber** [comment]
Do braindead spiders attack the traitor xeno that created them?

**Review by Timberpoes — CHANGES_REQUESTED** [review]
image

I feel that this is a good compromise and it works. We're technically restricting ghost role availability.

I want to see how this looks in code, too. It may be transferrable to other spawner types (potentially without being a config option, we could set per-mob spawn limits with a properly implemented system) which would provide better balancing levers for how ghosts interact with selecting this antag type.

**Comment by MrStonedOne** [comment]
The idea being that in most cases, its still 1 spider life per ghost, but if spiders are out for a long time, ghosts can revive the threat so it can't be treated as something to survive the initial wave of then let it die down.

Also keeps ghosts getting locked out a near round end spider release because they were part of one that happened early in the round.

**Comment by Timberpoes** [comment]
> 
> 
> The idea being that in most cases, its still 1 spider life per ghost, but if spiders are out for a long time, ghosts can revive the threat so it can't be treated as something to survive the initial wave of then let it die down.
> 
> Also keeps ghosts getting locked out of a near round end spider release because they were part of one that happened early in the round.

You're making a lot of sense. Whether config option is the final solution or not I'm not sure (At least @AnturK was against needless config additions) but these are a sound set of arguments.

I'm going to look into this myself. There is a better solution to limiting ghost role re-spawn availability overall, it's just if anyone can/will code it. Ghiliker accomplished just this in like 6 lines of code, so I wonder if there's a more generic solution not too far around the corner.

**Comment by Timberpoes** [comment]
Ghilker's currently concepting ideas to implement this in a better overall way. DNM tagging for now as I watch over him trying new stuff.

**Comment by kriskog** [comment]
See https://tgstation13.org/phpBB/viewtopic.php?f=9&t=23649 for some additional discussion on the topic

**Comment by Timberpoes** [comment]
Standby on this one Ghilker. I'm off to bed, but I got a solution that's ready for a draft PR that should be a decent compromise.

**Comment by ATH1909** [comment]
> Make it a cooldown, make it a config, default it to 7 minutes.

7 minutes is waaaaaaay too long, IMO. The 3 minute (IIRC) rez timer for liches is already agonizingly slow; a 7 minute cooldown timer for spider repossession would be/feel even worse. 2-3 minutes (or even 1 minute) would probably be a much better cooldown timer length.

**Comment by Jimmius** [comment]
what about starting the timer when you spawn as a spider, rather than when you die? That way you're encouraged to stay alive for as long as possible before dying, rather than endlessly bumrushing well armed people.

**Comment by Tlaltecuhtli** [comment]
the cooldown is to combat the meta of dying somewhere remote by 1 dude and returning to the same place to finish him off, 3 min is enough to prevent blyat rushing the same dude over and over

**Comment by Ghilker** [comment]
Aight people, i'm closing this because @Timberpoes has #53685 opened as draft for feedbacks on the implementation. Yes this is still going just on better hands with a better framework as base.

**Pull request closed without merging**
