### PR TITLE
Fixes the Voice of God singling out roleless creatures

### LINKED ISSUE #28976: Voice of God automatically targets things with numbers in their names
Which is, uh, odd.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: The Voice of God no longer specifically targets creatures like constructs and clockwork marauders.
/:cl:

Specific targeting code for the Voice of God only checked to see if the listener's assigned role was in the message. However, because some creatures have `null` is their assigned role, the message would always target them. This fixes that by making sure that the listeners have an assigned role before running the targeting code.

Fixes #28976.

### CODE REVIEW

**Comment by Supermichael777** [comment]
seems like a nerf

Feels frosty in here

**Comment by Xhuis** [comment]
This isn't a nerf at all, it's a bug. The initial code specifically searches for an assigned role, and I highly doubt it was meant to single out people lacking one.

**Comment by Supermichael777** [comment]
but now you cant target them?

seems like the bug is them not having a valid roll in the first place, they should probably get a construct role or a beast role.

**Comment by XDTM** [comment]
Not by role, you can use the name like usual.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
