### PR TITLE
Map fixes

### LINKED ISSUE #29710: random potted plant inside machine on DeltaStation
dreamseeker_2017-08-04_16-37-37

@ShizCalev

### LINKED ISSUE #29715: shitty fire alarm placement on DeltaStation
dreamseeker_2017-08-04_17-56-54
how do you even get to there????

### PR DESCRIPTION
**Pull request by ShizCalev**
fixes #29715
fixes #29710

corrects a tile on box that i missed with #29664

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
forgot to mention that there are also fans to the abandoned engine room in the airlocks in engineering.

dreamseeker_2017-08-04_19-39-54
remove them

**Comment by ShizCalev** [comment]
so demanding

**Comment by ShizCalev** [comment]
@PraiseRatvar those fans should still be there. the reason they were removed on the other maps was because the framework for the singulo area was replaced with the SM, making them pointless to have.

**Comment by PraiseRatvar** [comment]
oright

**Pull request merged**
