### PR TITLE
Slightly* buffs Maint Drones

### PR DESCRIPTION
**Pull request by DragonTrance**
## About The Pull Request
1. Increases drone health from 30 to 45, making it harder to instantly die from some things
2. Lowers the range that drones can't do interactions from 4 tiles to 3 tiles
3. Lowers stun time from 10 seconds to 7 seconds when EMP'd
4. Wait time for when a mob has recently interacted with something has been decreased from 5 minutes to 1 minute
5. Drones can now build near dead mobs, but not interact when right next to them (to prevent pulling)

Also adds a new argument for the shy component that allows interacting near dead bodies, but not right on top of them

## Why It's Good For The Game
This is mainly for the QOL of Drones. I know "maint" is implied in the name of drones, but it sucks that you have to hide in maint for half the shift while all the airlocks are being opened by everyone, being unable to fix the station from explosions. Also even though the range was 4 tiles for interacting next to living mobs, it seemed a bit excessive when you tried to do stuff.

## Changelog

:cl:
balance: Maintenance Drone health changed from 30 to 45
balance: Maintenance Drone stun times from getting EMP'd reduced from 10 seconds to 7 seconds
qol: Maintenance Drones can now interact near dead bodies
qol: Maintenance Drones don't have to wait 5 minutes to open an airlock when someone recently did it. Now they have to wait 1 minute.
qol: Changed distance Maintenance Drones aren't allowed to interact with anything from a nearby mob from 4 tiles to 3 tiles
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
> Wait time for when a mob has recently interacted with something has been decreased from 5 minutes to 1 minute

i think the issue with this is this defined in a large policy dicussion. You might need permission to change that because this may cause administrative issues

**Comment by DragonTrance** [comment]
> i think the issue with this is this was defined in a large policy dicussion

I know there was TONS of gripe, and drone is basically coded-in admin policy now. But why are we making drones wait 5 minutes to open airlocks? 5 minutes is a long time in a laggy 40+ pop server

I also don't want to remove it completely for specifically just airlocks/firelocks because that would arise problems in that area

**Comment by optimumtact** [comment]
has this been cleared with the headadmins?

**Comment by DragonTrance** [comment]
> has this been cleared with the headadmins?

I havent talked to any admins about this and just sorta made the pr. I figured admins could see this when I made it and possibly give feedback if it's not okay

**Review by dragomagol — APPROVED** [review]
As long as drones have all the proper logging that everything else does, I don't see this being an issue.

**Comment by unit0016** [comment]
_Interacting with the egg could violate your laws!_

**Comment by TheBonded** [comment]
FZmwa7Y-1

**Comment by Coastfront** [comment]
Honestly these seem like nice changes, Being unable to actually f i x station damage caused by an explosion because one of the people who happened to die from said explosion is still there, And waiting like 5 minutes to touch something, only for the extremely high likelyhood of another person touching it on highpop within 5 minutes sucks.

**Comment by optimumtact** [comment]
what could go wrong right?

**Pull request merged**
