### PR TITLE
Revert "Firelemon explosion is now delayed"

### PR DESCRIPTION
**Pull request by Niknakflak**
Reverts tgstation/tgstation#21199

That was my original intention to have them have a delay to throw but now kevinz is yelling at me because he died and it was funnier when they were suicide bombs.

### CODE REVIEW

**Comment by kevinz000** [comment]
i didnt die the reactive teleport meme saved my ass when some greyshit tossed one at a rogue bot standing ontop of me.

**Comment by optimumtact** [comment]
@kevinz000 knows how to code, he can do this himself

**Comment by PKPenguin321** [comment]
>removing something becuase it made kevinz mad

all wrong

**Comment by kevinz000** [comment]
meh i'm not salty enough to do it

**Comment by kevinz000** [comment]
and it doesn't really matter since ma44 is the only one who abuses the shit out of it

**Comment by KingPhilipIII** [comment]
Best thing was when I saw a blob defeated by combustible lemons.

**Pull request closed without merging**
