### PR TITLE
Resprites the Limb Grower

### PR DESCRIPTION
**Pull request by kinneb**
## About The Pull Request
Wew, this machine has had it coming for a while now.

Heres some sprites for it up close and personal:
image
image

And heres the old sprite for reference!

## Why It's Good For The Game
I've always disliked the old sprite, and I think this new one looks nice! Thanks to the nice folk at shiptest's spriters club for helping me out a lot making this.
## Changelog
:cl:

image: Resprited the Limb Grower

/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
The Device

**Review by Wallemations — CHANGES_REQUESTED** [review]
The color for the shading on the main machine is really harsh, the indent on the top feels like it could use a darker color in the middle, and the top of the screen having highlights feels a bit wrong.
If you're not using an existing palette, I recommend adding a shade of grey that's somewhere between the two I've put dots on here.
image

**Comment by Wallemations** [comment]
Alternative and easier suggestion to fix up the colors: color-pick the metal colors from smart storage fridges, since those look pretty good.

**Comment by kinneb** [comment]
taking forever because exams, pardon my tardiness

**Comment by ChungusGamer666** [comment]
soul removal
(it's good)

**Comment by kinneb** [comment]
(finally had enough time to updaate it)

**Pull request merged**
