### PR TITLE
rename chem grenades w/ pen

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by GunHog** [comment]
"Rename chemical grenade with a pen."

**Comment by ExcessiveUseOfCobblestone** [comment]
may as well just do this for all grenades

**Comment by kevinz000** [comment]
come the fuck on goofball can you please just name it properly so people who don't have the knowledge/time to read code knows what it does?

**Comment by ChangelingRain** [comment]
if you're not going to take this even 1% seriously I'm going to shitcan you.

**Comment by PKPenguin321** [comment]
Who cares about the title Joan lol

**Comment by Iamgoofball** [comment]
I got told to reopen thiz

**Comment by Cyberboss** [comment]
Rename the PR if it triggers you that much Joan

**Comment by Haevacht** [comment]
The titles goes to the live servers so they should at least see what bullshit goof's trying to pull.

**Pull request closed without merging**
