### PR TITLE
Removes the obsolete Fireproof Core Malf power

### PR DESCRIPTION
**Pull request by GunHog**
:cl: Gun Hog
rscdel: Malf (Traitor) AI's Fireproof Core ability has been removed, as it was entirely obsolete.
/:cl:

AI's Fireproof Core ability has been removed, as it served no purpose.

**Editing Note: This PR has been remade to a removal of the power.**

### CODE REVIEW

**Comment by Zilenan91** [comment]
Is there any way to make the AI immune to fire and not lasers

**Comment by coiax** [comment]
What malf AI has ever been killed by fire

**Comment by KorPhaeron** [comment]
This is not really a fix so much as a balance change.

The fire upgrade was supposed to protect you from environmental hazards, but we gave that to silicons by default eventually anyway.

There needs to be some sort of feedback message that the AI is not taking damage when you're attacking it.

Or just remove the power since it's obsolete.

**Comment by GunHog** [comment]
What if I used a red shield overlay, as silicons have almost nothing for defense code?

**Comment by Anonmare** [comment]
The usefulness of that power is still pretty debatable. If you can get hit by lasers, then chances are good you can get hit by a joker with floor tiles or ballistics or even pinched to death with wirecutters. Or just get carded and deleted. 
Especially for it's cost, 50 cycles is extremely overpriced and you get a lot more usefulness out of two Machine Overloads or Overrides. I wouldn't pay more than 25 for it at most unless it came with EMP resistance and/or an internal power generator.

**Comment by GunHog** [comment]
You are probably right. It is garbage no matter what I do with it. Even with laser proofing, once the chamber is breached, AI death is but a matter of time. I will simply remove it, as I doubt I would be allowed to buff it to make it useful.

**Comment by KorPhaeron** [comment]
Gonna be hard to make a power thats worth taking vs an engiborg just putting down an airlock.

Let me know if you have any ideas though

**Comment by GunHog** [comment]
Well, thanks to immobility, damage reduction or immunity to specific things is only a time buyer. Now, if the AI could create a **barrier** (like breach generators) or something...but that might be considered OP.

**Comment by KorPhaeron** [comment]
Everything is pretty much stalling until the clock runs out yeah

**Comment by coiax** [comment]
I do need to get around to making the AI timer world.time based.

**Comment by Anonmare** [comment]
Bay has that barrier power you mentioned. It looks to be similar to the breaching shield generator but only on a single tile and can be put on a floored tile. It's really weak and goes down in a few hits though but I think the AI can put down a whole bunch to compensate.

**Pull request merged**
