### PR TITLE
Fixes photon torpedo description, fixes more grammar shit.

### LINKED ISSUE #20340: Point blank messages are misleading for mediguns
Punch Nuts points Medical Beamgun at Scuba Gear's head, ready to pull the trigger...
Punch Nuts has decided to spare Scuba Gear's life.

### LINKED ISSUE #22798: photon torpedo desc
ss 2017-01-06 at 09 14 50

### LINKED ISSUE #22820: RCD needs a small grammar update.
"You start building wall" should be "You start building a wall"
https://github.com/tgstation/tgstation/blob/a60172ecf56192b0ab5cf816aa502edf3620607c/code/game/objects/items/weapons/RCD.dm#L347

"You start building floor" should be "You start building a floor"
https://github.com/tgstation/tgstation/blob/a60172ecf56192b0ab5cf816aa502edf3620607c/code/game/objects/items/weapons/RCD.dm#L338

### PR DESCRIPTION
**Pull request by harmonyn**
taking a break from fixing real bugs

Fixes https://github.com/tgstation/tgstation/issues/22798.
Fixes https://github.com/tgstation/tgstation/issues/22820.
Fixes https://github.com/tgstation/tgstation/issues/20340.

### CODE REVIEW

**Comment by Arianya** [comment]
Okay, I like your torpedo text more then my suggestion 👍

**Comment by bgobandit** [comment]
I didn't see your suggestion until I had already pushed

**Comment by KingPhilipIII** [comment]
Well, technically speaking torpedoes in general are short range weaponry, not long range due to the inability to guide it after firing. Guided torpedoes are still often not used for long range because both can be easily seen and blown up by defensive fire from the other vessel.

**Comment by bgobandit** [comment]
even I'm not ocd enough to change that

**Pull request merged**
