### PR TITLE
buffs syndicate simple mobs

### PR DESCRIPTION
**Pull request by Shadowlight213**
I was seeing people wipe them out on the away missions once they killed the first one and got their gear.
:cl:
tweak: Syndie melee mobs have been buffed.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Biggest buff would be letting them hit people in crit so one guy with a medibot cant tank them all

**Comment by Shadowlight213** [comment]
I can try that. I think theres an override var.

**Comment by MrStonedOne** [comment]
Because this changes something in the game, please make a changelog.

You can add it to the PR's body rather then as a file now, see here: https://tgstation13.org/phpBB/viewtopic.php?f=5&t=5157

**Comment by Dorsisdwarf** [comment]
Yes, there's an ovveride var

**Comment by Darkgenerallord** [comment]
Syndicate melee mobs should be buffed, syndicate range should not.

**Comment by Anonus** [comment]
why would you do this

**Comment by Zilenan91** [comment]
Yeah fuck ranged syndicate mobs. Those things are hitler already and don't need a buff.

Would not mind if they could hit people in crit though.

**Comment by Shadowlight213** [comment]
Syndicate ranged mobs become terrible if they are  in a group in any sort of enclosed space, but sure I can undo the health buff there.

**Comment by Iamgoofball** [comment]
why dont we make them snpcs

**Comment by Shadowlight213** [comment]
@iamgoofball Snpc combat is still really buggy though. They often fail to aquire a new target after their first one is dead or crit and just stand over the body. I haven't been able to test their ranged combat abilities that much, but I do know they don't have unlimited ammo and run out really quickly.

**Comment by Iamgoofball** [comment]
then we teach it to find targets better and stop targeting crit people, and teach it to reload guns with the  modules system

**Comment by Shadowlight213** [comment]
@iamgoofball are you offering to do that? It's a great idea but I haven't seen any coder willing to touch them.

**Comment by Aranclanos** [comment]
>content that only work as intended for new players
>balanced for older players

lmfao

**Comment by KorPhaeron** [comment]
Upon further watching them fight, I think the real issue is that once players pick up an esword+eshield they block almost every attack. Flat health wont help that.

Adding armour pen to the mob might though.

**Comment by Shadowlight213** [comment]
@KorPhaeron how much do you thing would be good?

**Comment by Zilenan91** [comment]
if I'm understanding how the armor penetration system works, 10 or 20 would be good.

**Comment by MrStonedOne** [comment]
@Shadowlight213 remove the - in front of the change log entry,

**Comment by KorPhaeron** [comment]
@Shadowlight213 

Like 25-30 maybe.

Why is a PR thats like a one line change unmerged after 16 days

**Comment by Shadowlight213** [comment]
@KorPhaeron I've been busy with shit. I'll add the penetration

**Pull request merged**
