### PR TITLE
Shooting specific wizard staffs as a non-wizard or non-magician now backfires in different ways.

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

If you try using the staff of change, the staff of chaos, the spellblade or the staff of healing as a crewmember, then it'll backfire.
People who can use the staff normally: Apprentices, Wizards, Amateur Magician (from Summon Magic event)

Backfiring is different depending on the staff, each effect is listed below and happens when you try firing the staff.
Staff of change - Wabbajacks the imposter, although they can't become a xeno or a borg.
Staff of chaos - 5% chance to fire the staff at the imposter using it.
Staff of healing - Acts as a medibeam gun to the imposter.

## Why It's Good For The Game

Crew getting access to the Staff of Change tends to end in a lot of people becoming xenomorphs or syndicate borgs. It forces the round into a turn for the worse for all antags as xenomorphs have hardstuns, syndicate borgs have emag, greatly improved healing chemicals and powerful weaponary.
Crew getting access to the Staff of Healing results in death being irrelevant. Killing people is no longer a viable tactic as an antagonist because anyone killed, no matter how damaged their body is, can be instantly healed with this staff.
Crew getting access to the Staff of Chaos is like crew getting access to the staff of change and the staff of healing at the same time, only more unpredictable. It's better if they can't reliably use it to get the spells they want as chaos is implied in the name, it becomes russian roulette trying to get the correct bolt as you can also get shot by a bolt of death, instantly killing you.

This is a better alternative to outright removing the staffs or making them usable only by wizards as it gives a quirky use to trying to use them as a crewmember. Maybe not the staff of healing, but fuck the staff of healing.

## Changelog

:cl:
balance: If you try using the staff of change, the staff of chaos or the staff of healing as a crewmember, then it'll backfire. The Staff of change wabbajacks the user, like the pool of change; this means you can't become a xenomorph or a syndicate borg. The Staff of chaos has a 5% chance of firing the bolt directly at the user using it. The Staff of healing now behaves like a medibeam gun to non-wizards trying to use it.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
Meh, wizard is so rare that it completely changing the direction of which rounds flow, and in which antagonists must act, is part of the appeal to me, I remember having this similar argument against "summon ghosts makes antagonist rounds harder". :-1:

**Comment by CRITAWAKETS** [comment]
might wanna like get rid of the staves from the summon magic pool so that they arent just free drops for the wizard

**Comment by nianjiilical** [comment]
i dont know if im a fan of *completely* removing their use via nonwizards though i do agree that full power staff of change/healing invalidate a lot of the game

maybe just give the staff of change a separate list it can pull from if nonwizards use it that exclude xenos/syndiborgs?

**Comment by ATH1909** [comment]
> tough luck in that case. Also, you only have a 2% chance of getting a staff and they're not completely useless to amateur magicians. You are still able to freely use wands.

Still seems like negligence. Someone will definitely make a bug report about this at some point if this PR gets merged.

> Seccies using emags isn't a valid argument because I don't like that either,

Well, that seems to be a fundamental disagreement between our viewpoints.

> it's like when a sec officer uses a desword to shred through antags that they got off a roundstart boner.

That sec officer managed to get past that desworder without needing any special toys; you have 20 TC (or whatever resources your antag type has) to trump their antag gear with your own.

> Syndicate borgs have way more gear than emags and have no laws, they have advanced healing tools.

Eh, not _really_. Syndicate mediborgs are kind of just mediborgs that are better at healing and a bit better at combat (they don't get emags). Crew-aligned syndicate saboteur borgs are kind of just engiborgs with access to cable cuffs (standard borg my beloved) and disposals travel. Assault borgs get an emag and some combat tools, but not much in terms of utility. Their gear is good (or even dummy good in the case of the grenade launcher), but not round-defining.

> You're also forgetting that you can just keep rolling until you get exactly the transformation you want, it's not like the pool of change on icebox where it's a one time deal and then no more.

You could make all change bolts one time deals instead. 😳

Then again, that'd also keep people from using the staff of change dropped by a dead wizard to return to a humanoid form to recover from being zapped by that wizard while they were still alive. Then again again, this PR prevents that as well.

> This PR is targetted at crew using these tools, not wizards. I don't care what wizards want to do, if they want to be friendly or hostile. The problem is if some wizard apprentice gets this, dies, and now crew have a tool to bypass medical completely. You are also thinking only in the mind of someone who's played this game for a very long time. Most newer players won't know that medical now have a tool to heal people from death within seconds.

But most newer players will know that Medbay can revive dead people, and the overlap of counterplay options for "Medbay that can revive a corpse after 5 minutes" vs. "Medbay that can revive a corpse immediately" is near-perfect. You should be hiding, beheading, or destroying the corpses of your victims anyway, staff of healing or no staff of healing.

> Cool, I don't think crewmembers should have a tool to dismember people at a range that recharges and is infinite.

It's a tool that's always displayed on your person (in a vibrant color), unlike, say, a desword or a syringe gun. You should be securing a source of antimagic upon a wizard being called out anyway, even if they're dead (since people will play with the dead wiz's toys).

> Most traitor weapons are finite if they're ranged and so are the wands.

Name one ranged traitor weapon that you can't acquire more ammo for as a non-antag (and doesn't already have infinite ammo).

> Staff of Chaos was made into a more interesting staff usable by the crew as a more interesting russian roulette option. You don't know what you're going to get but it's going to be random and I bet you it's going to be funny.

But Russian roulette is more fun if you can force other people to participate in it! Also, the bolt of change change I suggested earlier would probably solve most of your issues with the staff of chaos, as the risk of permanently turning someone('s corpse) into, say, a chick might outweigh the benefit gained from performing a quick magical rez instead of a longer mundane rez.

**Comment by ProfessorSniff** [comment]
maybe give it a low chance that it won't backfire, instead of outright blocking non-wizards from using it? It seems a little anti-fun to make them mostly useless.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
even if i don't like this change,  make sure that there's a staff of healing that admins/events can spawn

**Comment by wesoda25** [comment]
Sad but overdue.

**Comment by EricZilla** [comment]
Have you considered instead of having it backfire EVERY time its used, to backfire EVENTUALLY as its used, so it becomes a situation where you have to weigh risk and reward, like slapping down wires with no insuls.

Say like, make is only work 1/3 of the time, and 1/20th the time you use it, it backfires

**Comment by Livrah** [comment]
And now bunch of threat gonna die in a minute and leave no implact for the round.

**Comment by Watermelon914** [comment]
Revisions:
- Spellblade can now be used by non-wizards again with no downsides
- Guardians and skelebros can now use the staffs with no downsides either.
- Staff of chaos now has only a 5% chance of hitting you, so you take a risk every time you shoot it
- Everything else remains unchanged.

**Comment by Watermelon914** [comment]
> And now bunch of threat gonna die in a minute and leave no implact for the round.

If you are relying on wizard staffs to provide most of the impact after they die, then toughie. Summon Ghosts, other wiz items and such are still usable and still provide a big impact on the round.

**Comment by TheBonded** [comment]
Can't you get the spellblade from one of the megafaunas? I think it was bubblegum or colossus?

**Pull request merged**
