### PR TITLE
Buffs Cakehat

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Like 4 years ago Uhangi got killed by the cake hat and got mad and nerfed it I think it's time we finally fix it.

It now does 15 fire damage when turned on (so like a welding tool)

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
#1 blob fighting weapon.

**Comment by freerealestate** [comment]
In three years I never knew you could light it

**Comment by PKPenguin321** [comment]
cakehat new meta

**Comment by Dawgas** [comment]
+1

make /tg/station great again

but I don't think this would fly in the current environment of small babies - but fuck them

**Comment by Dorsisdwarf** [comment]
kor for headcoder

**Comment by Jalleo** [comment]
Make it 10

**Comment by Cheridan** [comment]
make it 60

**Comment by AnonymousNow** [comment]
Neat.

**Comment by TheDreamweaver** [comment]
IF you head butt with it on, does it have the same affect?

**Comment by Fox-McCloud** [comment]
@TheDreamweaver 

Pretty sure that's only a thing on Bay and Paradise.

**Pull request merged**
