### PR TITLE
Roundstart Servants of Ratvar get a link to the wiki page

### PR DESCRIPTION
**Pull request by ChangelingRain**
BUFFING ROUNDSTART SERVANTS

### CODE REVIEW

**Comment by as334** [comment]
Immersion destroyed

**Comment by KorPhaeron** [comment]
Add a wiki link to their slab

**Comment by ChangelingRain** [comment]
where the fuck would you link it in the slab though

**Comment by KorPhaeron** [comment]
more menu options!

**Comment by ChangelingRain** [comment]
kor no that's chaotic evil

**Comment by KorPhaeron** [comment]
what if we added clock research by scrambling the menu every round

**Comment by ChangelingRain** [comment]
kor is chaotic evil we need help SOMEONE SEND HELP

**Comment by InsaneHyena** [comment]
Ratvarcult is the first antag to be so complicated, coders are giving people link to a wiki to make them understand. Really makes you think.

**Comment by ChangelingRain** [comment]
Actually incorrect; shadowling did it first.

**Comment by Aloraydrel** [comment]
menuwork cultists tbh

**Comment by Armhulen** [comment]
complete canon; the slab's screen switches between github the forums the shed and the wiki

**Comment by anconfuzedrock** [comment]
tfw normal cult doesn't even fucking need this but ratvar does

**Pull request merged**
