### PR TITLE
Ice Cream Vat QoL: Elevated surface, placing in hands, not using usr

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
- Ice cream vats now count as elevated surfaces for preventing germs from getting on your ice cream cones.
- Ice cream vats now try to dispense cones into your hands first, and defaulting to regular placement afterwards.
- Put-in-hands behavior for germ-sensitive items has been changed; instead of looking solely for tables, it checks for any suitably elevated surface to put things on, which now includes icecream vats.
- Ice cream vats' HTML no longer uses usr. Not player-facing, simple find-replace. Probably doesn't qualify as code improvement.

Anyways, shoutout to ice cream vats' HTML still using usr. Not sure if what I did to the put-in-hand code is too expensive or not, but it should be fine.

## Why It's Good For The Game
It's probably a good thing for ice cream to not fall onto the floor and become dirty upon being dispensed.
## Changelog

:cl:
qol: Ice cream vats now count as elevated surfaces for preventing germs from getting onto germ-sensitive items (food).
qol: Ice cream vats now dispense cones into your hands first, if possible.
fix: Germ-sensitive items that fail to be placed in-hand now check for all elevated surfaces, not just tables.
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
HAAAAAAAAROLD

**Comment by MTandi** [comment]
>Put-in-hands behavior for germ-sensitive items has been changed; instead of looking solely for tables, it checks for any suitably elevated surface to put things on, which now includes icecream vats.

This may backfire when you craft something and it lands on a griddle and start burning.

**Comment by MTandi** [comment]
Check for all of these then:

```
	/obj/structure/bonfire,
	/obj/machinery/grill,
	/obj/machinery/griddle,
```

**Comment by Hatterhat** [comment]
> Really dislike this exclusion logic. Maybe make that separate list contain whitelist, instead of blacklist. 

if it was a whitelist for prioritizing things it'd be a lot longer of a typecache which doesn't seem like a great idea, but then again as it stands i'm iterating through two lists of turfs again which sucks.

> How do you plan to exclude putting things on fridges?

i mean i *guess* i could make it a whitelist for this other niche thing but that also doesn't seem great. i don't know if i can subtract typecaches from other typecaches but if i could then i'd be less opposed

> Or just make the icecream spawn on top of the vat instead of putting it in hand.

valid but i kind of like not having tables be the only things germ-sensitive items get auto-placed on

**Comment by MTandi** [comment]
Just FYI, this is how it is done in smartfridge.

image

**Comment by san7890** [comment]
FTR `usr` and typecasting it to to `var/mob/user` is redundant in the context of `Topic()` since it's a psuedo-verb... I don't think we really need the safety but it's ultimately w/e

**Comment by Hatterhat** [comment]
> FTR `usr` and typecasting it to to `var/mob/user` is redundant in the context of `Topic()` since it's a psuedo-verb (complex subject, but basically the BYOND documentation/lummox yelling doesn't really apply here given how we use `Topic()`)... I don't think we really need the safety but it's ultimately w/e

thanks byond

**Pull request merged**
