### PR TITLE
[s] PORTS CITADEL CODE(the one with the furrys and vore)

### PR DESCRIPTION
**Pull request by bunny232**
You have been banned by bobdobbington.
Reason: Suspected lizard roleplayer
This is a temporary ban, it will be removed in 1 minutes.
To try to resolve this matter head to https://tgstation13.org/phpBB/viewforum.php?f=7 
Connection died.
What the fuck did you just fucking say about me, you worthless heretic? I'll have you know I graduated top of my class in the Space Marines, and I've led an incomprehensible number of secret raids against the forces of chaos, and I have over 30 million confirmed purgings. I am trained in armored warfare and I'm the top Ultramarine in all the Space Marine Chapters. You are nothing to me but just another heretic. I will wipe you the fuck out with precision the likes of which has never been seen before in this universe, mark my fucking words. You think you can get away with saying that shit to me over the Warp? Think again, fucker. As we speak I am contacting my secret network of spies across the galaxy and your powers are being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bolter. "Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the Adeptus Mechanicus and I will use it to its full extent to wipe your miserable ass off the face of the planet, you little shit. If only you could have known what holy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Your joke execution could use some work

**Comment by bunny232** [comment]
true

**Comment by Armhulen** [comment]
it was okay i smiled

**Comment by bunny232** [comment]
Closed due to minor changes

**Comment by Haevacht** [comment]
You will get shit on for spamming that.

**Pull request closed without merging**
