### PR TITLE
Wardrobe preloads backpack contents

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

`backpack_contents` is a list of typepaths, so this type definition means this loop is doin' nothing. 3 year old bug

### CODE REVIEW

**Review by LemonInTheDark — APPROVED** [review]
I hate this place

**Comment by SyncIt21** [comment]
Changelog? Fixing something that's been broken for 3 years should produce visible changes in game

**Comment by MrMelbert** [comment]
I am certain this will have no visible changes

**Comment by LemonInTheDark** [comment]
> Changelog? Fixing something that's been broken for 3 years should produce visible changes in game

you'd think right? you'd be wrong tho

**Pull request merged**
