### PR TITLE
Removes disc station

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Broken, not being maintained, maintainers asked for it to happen.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Rip

**Comment by francinum** [comment]
RIP Hallstation.

**Comment by swankcookie** [comment]
:+1: pour one out, guys.

**Comment by PKPenguin321** [comment]
rest in good riddance in piece

**Comment by optimumtact** [comment]
Rest in peace dics station

**Comment by hornygranny** [comment]
sorry but this doesn't compile for disc station

**Comment by MrStonedOne** [comment]
edit travis, and remove it from the default maps.txt.

Also somebody ping the maintainer so they came up and be all like "alright i'm back, i'll fix this"

**Pull request closed without merging**
