### PR TITLE
Revert "Readds the walk hotkey"

### LINKED ISSUE #23537: User gets stuck in walk when alt-tabbing w/ Hotkeys enabled
Alt-tabbing toggles you into walk mode, however after tabbing back into the game, you are not returned running. (this is a pretty common issues for programs that have functions with alt that don't continue listening once the window loses focus.) 

Would it be possible to switch the run-toggle to a different key? It's rather inconvenient to tab back into a situation where it's critical that you are running (tator eswording you, bomb exploding, insert terrible thing here) and end up just hobbling away.

### PR DESCRIPTION
**Pull request by Cyberboss**
This reverts tgstation/tgstation#23291
Fixes #23537 

Well that didn't fucking work again

### CODE REVIEW

**Comment by Arianya** [comment]
Change it back to shift reeeeeee

**Comment by Cyberboss** [comment]
THATS WHY IT WAS REVERTED THE FIRST TIME

**Comment by BeeSting12** [comment]
The reason shift was removed is so people can examine things without slowing to a crawl.

**Comment by Hatfish** [comment]
Who holds down shift long enough to get slowed down anyways?

**Comment by ExcessiveUseOfCobblestone** [comment]
If the only issue is the individual is tabbed out and dies because he wasn't paying attention to the game, I don't really see the call for reverting it. You can just press alt again to fix it.

**Comment by Kromgar** [comment]
Oh my god its so fucking annoying on lavaland ill tab real quick because i switch music and then bam SPICE WEASELS

**Comment by ExcessiveUseOfCobblestone** [comment]
use a playlist nerdola, if you were fiddling with your PDA-player and a broodmomma comes out of the woodworks you gotta ACCELERATE instead of default run at the speed of light.

**Comment by optimumtact** [comment]
I don't buy the need for a revert, come back with a pr changing the key to something else instead.

**Comment by PJB3005** [comment]
Ok how do you people legitimately live with this shit?

**Comment by optimumtact** [comment]
By not alt tabbing out of the game while we're playing

**Comment by PJB3005** [comment]
> He doesn't alt tab.

How do you people maintain sanity?

**Comment by PKPenguin321** [comment]
i just toggle Walk back to Run when i alt tab back in

**Pull request closed without merging**
