### PR TITLE
Telecom machines and reagent fixes

### LINKED ISSUE #8715: Disassembling Telecomms Machines
Tested on the Subspace Recievers and Processor Units that start in Telecomms, the crowbar step doesn't do anything, despite saying it does.

>Screwdriver: You unfasten the bolts.
>Wrench: You dislodge the external plating
>Wirecutters: You remove the cables
>Crowbar: You begin prying out the circuit board and components...
You finish prying out the components.

But nothing happens. Machine is unchanged, no parts spawned, nothing.

### LINKED ISSUE #8768: Stabilized flash and sonic powder are extremely weak at any volume
Flash/Sonic powder obtained through stabilizing agent seem to only affect those on the same tile, regardless of the amount used.

Fill a bluespace beaker with 300u of either powder and heat it to 374K. It will react, but only apply the disabling effects to those standing on the same tile. This applies whether you're using grenades or simply heating the beaker in a chem heater.

The unstabilized versions work just fine. 15u aluminum, 15u potassium, 15u sulfur will stun people several tiles away. 45u stabilized flash powder? Not so much.

### LINKED ISSUE #9088: Nicotine overdose is rather deadly
Chainsmoking (as in, consuming a constant stream of nicotine) seems to cause hilariously damaging overdose effects after barely a few cigarettes.

In particular: halfway through the third cigarette, I got spammed with a few dozen "You're smoking too much" messages, puked on the floor a few times, and died. I know smoking kills, but this seems like a slightly overdone aesop.

To reproduce: Chainsmoke.
What I'd expect: Slight overdose effects.
What really happened: Death.
Server revision: b65595a0f1730dc77c3ab787f0243083eeded23d
Other: Guessing it has something to do with the reagent changes from the 20th, since I could chainsmoke just fine yesterday.

### PR DESCRIPTION
**Pull request by phil235**
Reorganized the telecom machines files:
- broadcasting.dm
- machine_interactions.dm
- telecommunications.dm (machinery/telecoms and all its procs defined but no individual machines)
- machines (folder, one file for each telecom machine)
- computers (folder, one file for each telecom computer)

Telecom machines are now deconstructed the same way as all other constructable machines. Fixes #8715 
Adding new sprites for telecom machines with panel open.
Moving telecom machines sprites from stationobjs.dmi to obj/machines/telecomms.dmi
Fixes the effects of smoke/flash/sonic powder when stabilized and then triggered. Fixes #8768 
Removing overdosing on nicotine. Fixes #9088

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Please don't remove nicotine overdosing. Just tune it down.

Chainsmoking really shouldn't be a thing, if all else fails tune down the overdose and up the threshold.

**Comment by optimumtact** [comment]
remove nicotine altogether

**Comment by Iamgoofball** [comment]
Please state your reasoning.

**Comment by phil235** [comment]
There's multiple solutions here: we can nerg the beneficial effects of nicotine, we can readd the overdose but with lower damage effects, or we can add something like `ìf(prob(5)) emote("cough") setToxLoss(max(toxloss, 5))`

**Comment by Lumipharon** [comment]
You have to like, work pretty hard in real life to OD on nicotine man, cigarettes don't have much in them.

**Comment by Iamgoofball** [comment]
@Lumipharon This wasn't intended to be super deadly, it was more intended to be a minor annoyance to prevent people from chainsmoking down 20 cigs to have 200u of nicotine sitting in them just in case.

**Comment by Miauw62** [comment]
so you added an annoying effect to something that was purely fluff so they couldn't abuse it for the good effect you added to it? just remove nicotine so people can be chainsmokers if they want to be.

**Comment by Miauw62** [comment]
also @fayrik

**Comment by Fayrik** [comment]
This telecoms rework looks pretty good. Doesn't look like it breaks anything that I've written in there, so I'm cool with it.
I would try to get a copy to test before it's pulled, but I'm currently sorta busy working on something else right now, so I'm just going to have faith in phil's glorious clean up power.
:+1:

**Comment by GunHog** [comment]
Please test and merge this quickly - I am starting a project that would conflict would this if I were to base it on the current files.

**Comment by Cheridan** [comment]
long live chainsmokers :smoking: :man_with_turban:

**Comment by GunHog** [comment]
Dang it Phil, I think you broke Tcomms for Scripts.

**Comment by phil235** [comment]
Well, I didn't change pretty much anything. The only thing I could think of is datum/comm_log_entry being defined in computers/server.dm instead of the general telecommunications.dm

**Pull request merged**
