### PR TITLE
Resprites bone armor

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Gives the bone and ash drake armors a fresh coat of paint
Full credit  for sprites goes to INFRARED_BARON

## Why It's Good For The Game

Old sprite bad new sprite good
image

## Changelog

:cl: by INFRARED_BARON
image: Changes the sprites of bone and ash drake armor (suit + helmet mob/objs)
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
love the dragon armor sabots.

**Comment by Sadboysuss** [comment]
if the bone armor doesn't cover the head fully, maybe it could also not hide hair?

**Comment by SomeoneYouProbablyKnow** [comment]
My man got those curly toe bone shoes 🔥 🔥 🔥 👟

**Comment by githubuser4141** [comment]
> So what do the digitigrade sprites look like?

Sorry, didn't realise those were a thing - do you know the location of where the sprites are kept?

**Review by Wallemations — APPROVED** [review]

**Comment by carlarctg** [comment]
These sprites are undoubtedly much higher quality and better polished than the originals. 

I do have some things to say though. Look at this comparison face-to-face:

image

The original drake armor and the drake itself share the same color palette, and this new one doesn't. I don't think there's a good reason for it? Armor made from a boss' hide should have that boss' palette, in my opinion.

image

As you can see here, the bone plates of the ash drake and the new sprite don't match in tone at all. It looks out of place.

That's what I believe to be my most objective complaint. However I do also have to say these things:

1. The armor sprites are too similar to each other.
This is kind of an issue, especially in high-octane situations where your brain can't soak in every pixel. The two should be distinctly different, but the boney protrusions of both armors are almost identical, and the drake hide covering underneath isn't visible enough, and easily mistakeable for just a sec/colored jumpsuit. Do remember that the armor user can take down the hood or not wear a bone helmet, which makes the sprites even harder to differentiate.
2. The bone armor isn't boney enough!
It's a meaty yellow color. It looks almost more like Flesh Meat armor than Bone armor. Sinew is red, bone is greyish, but this looks... orange? Doesn't seem right to me.

**Comment by Drayco84** [comment]
> > So what do the digitigrade sprites look like?
> 
> Sorry, didn't realise those were a thing - do you know the location of where the sprites are kept?

Not a clue. I ask because Ashwalkers (lizards) are the ones most likely to be using bone armor and sometimes the ash drake armor.

**Comment by aKromatopzia** [comment]
Hey this is merged and all but wouldn't lizards look silly with this mask squishing their snout down - especially if this pr is allegedly for the ashwalkers?
Screenshot_94

**Pull request merged**
