### PR TITLE
Ventcrawler var now uses a define for it's options

### PR DESCRIPTION
**Pull request by Mervill**
Yeah, the title

```
// Ventcrawling
#define VENTCRAWLER_NONE   0
#define VENTCRAWLER_NUDE   1
#define VENTCRAWLER_ALWAYS 2
```

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
you are a good person

**Comment by PKPenguin321** [comment]
fine change and i dont mind but just out of curiosity, what purpose does this serve?

**Comment by optimumtact** [comment]
@PKPenguin321 it aids developers who are reading code that they may not be familiar with.

Instead of just seeing a 1 and not know what it may necessarily mean they instead see

     VENTCRAWLER_NUDE

which is much more self explanatory

**Comment by Mervill** [comment]
- It makes it clear(er) that `ventcrawler` represents a toggle between X number of states (3 in our case) rather then a number that could be an arbitrary value.

- Makes it easy to redefine these values should we ever need too

- It's also a bit of a hint: finding the definition of `VENTCRAWLER_` will probably lead you to all of the possible options for it.

In computer science jargon this is called an [Enumerated type](https://en.wikipedia.org/wiki/Enumerated_type) or simply an Enum

**Comment by PKPenguin321** [comment]
makes sense, thanks

**Pull request merged**
