### PR TITLE
Did you just assume my species?

### PR DESCRIPTION
**Pull request by Cyberboss**
> How to get

Sorry for the stale meme

### CODE REVIEW

**Comment by optimumtact** [comment]
Banned

**Comment by Cyberboss** [comment]
Worth it

**Comment by PKPenguin321** [comment]
Wasting gets for shame

**Comment by JJRcop** [comment]
yikes

**Comment by JJRcop** [comment]
Much bigger shame since #22999 and this were both made by @Cyberboss in the same minute, :18 past the hour.

**Pull request closed without merging**
