### PR TITLE
stun batons no longer lose charge over time

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by MrStonedOne** [comment]
.... why?

**Comment by Atskadan** [comment]
because its a shit feature lol

**Comment by ACCount12** [comment]
:+1: This was shit.

**Comment by Steelpoint** [comment]
:+1:  x :100:

**Comment by PKPenguin321** [comment]
revert all of paprika's things now that he's gone quick :^)

**Comment by MrPerson** [comment]
This one was not a good feature in any way. Good riddance.

**Comment by optimumtact** [comment]
It's not about it being paprika's feature, it's just not a very fun thing, it doesn't add any interesting play to the round as most security officers make regular trips to the brig anyway.

It's just something you have to remember to keep in mind, so it's cognitive overhead for no real gameplay benefit.

**Comment by kingofkosmos** [comment]
It adds consistent with other things that have energy/fuel and need to be switched on (a.k.a. welders).

**Comment by GunHog** [comment]
:+1: Thank you for this.

**Comment by Incomptinence** [comment]
Will state again that is basically means one lost stun always even if you do what the change wants and toggle religiously.

**Comment by pudl** [comment]
:+1:

**Comment by Cheridan** [comment]
On one hand, yeah this sucks pretty hard.
On the other hand, there really isn't a reason to toggle your baton on-off (unless you're braining people with it which you probably shouldn't do as Sec to begin with) so I did like this a little based on giving the toggle an actual point.

**Comment by optimumtact** [comment]
@Cheridan 
merge plox?

**Pull request merged**
