### PR TITLE
Adds a single pixel to the Destructive Analyser

### PR DESCRIPTION
**Pull request by francinum**
Fixes this:

### CODE REVIEW

**Comment by Chocobro** [comment]
isn't it supposed to be like that

**Comment by francinum** [comment]
If that's intentional, Why.

**Comment by Razharas** [comment]
You fix it to what exactly?
THe pixel always existing or pixel always being deleted?

**Comment by francinum** [comment]
It's only there in the deconstruction animation.

**Comment by phil235** [comment]
:+1:

**Comment by Xhuis** [comment]
thumbsup

**Comment by Incoming5643** [comment]
Whoa now, atomize your pulls, this changes way too much at once!

**Comment by bustygoku** [comment]
>4 commits

**Comment by pudl** [comment]
I think that the pixel being REMOVED would look better. Sharp edges like that is bad spriting.

**Comment by PKPenguin321** [comment]
someone tag this critical priority and merge ASAP

**Comment by RemieRichards** [comment]
@francinum please invert this change, make it so the pixel is never there, instead of always being there. All other machines of a similar shape in research.dmi have their lower left corner pixel removed to form a curved corner instead of a sharp edge.

**Pull request closed without merging**
