### PR TITLE
Adds a new Modular PC vendor

### PR DESCRIPTION
**Pull request by Wilchenx**
## About The Pull Request
Adds a new modular pc vendor that can be found generally near the science departament lobby

## Why It's Good For The Game
Right now modular pcs, even at their most basic state are locked away to only one departament that we all hate and love taking things away from, Science.

So its time for them to share more of their deluxe silicate toys.

This is also a moneysink (its almost like a """""economy""""" where money just keeps flowing in and there are no sinks for it is poorly designed)
## Changelog
:cl:
add: The modular pc vendor
del: minor entities on meta/pubby/box/delta to make room for said vendor
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
a t o m i c p r

add a refill + cargo crate for standarization, add custom prices and make sure modular computers construction even works cause i think they dont

**Comment by Wilchenx** [comment]
@Tlaltecuhtli i tested the construction
it just works

**Comment by nicbn** [comment]
modular computers are bad
This isn't a crafting game, it's a game about interaction and conflict, and I don't see how a build your gaming PC thing adds helps on it

**Comment by necromanceranne** [comment]
You're right. We need to remove construction ASAP to preserve the integrity of /tg/station's code.

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by Wilchenx** [comment]
ooksie senpai owanngee >w<

**Comment by Wilchenx** [comment]
@nicbn if you feel like that then remove them altogether

or try my approach, introduce them to the entire crew as a choice and interest people in improving them

**Comment by Wilchenx** [comment]
Its ready

**Comment by bobbahbrown** [comment]
hmm

why is this in here

**Comment by Wilchenx** [comment]
hm

**Pull request merged**
