### PR TITLE
Adds a colour picker component for circuits

### PR DESCRIPTION
**Pull request by Thunder12345**
:cl: Thunder12345
add: Added a colour picker component for use with circuits.
/:cl:

Technically already possible by entering a hex colour as a string, but this way makes it easier to use.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Doesn't seem to really have a purpose? Text input pad shares identical functionality already

**Comment by optimumtact** [comment]
Yes the input box changes based on the type you expect back from it so this gives a simple color picker.

**Comment by PKPenguin321** [comment]
Oh, I didn't even realize that was default functionality. Nice

**Comment by Thunder12345** [comment]
Yeah, input left me stumped for a while too before I realised it varied based on the type you wanted

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
