### PR TITLE
Adds new pAI holomob options

### PR DESCRIPTION
**Pull request by Niknakflak**
## About
Adds 4 new AI holomob options.   Because I'm now a pAI main and wanted something to do.
Bat, Butterfly, Hawk, and Lizard.  Some don't have rest animations because I edited bat and butterfly to sit on the floor and it looked weird so I just left it as is.  Corgi also doesn't have a rest animation and they just used the same sprite for it so I did the same.  Hawk does have a rest sprite at least.

Accidentally did this on master because I'm great at coding.

Crab coming soon:tm:
image
image

## Why It's Good For The Game
Why not?  Adds more choices and more roleplay options.  Bat and lizard and butterfly are all pretty tame.  If you think hawk or one of them is over the top, just say so or say why.  bat, lizard, and butterfly are all small but not really too much smaller than mouse and pAIs are extremely harmless.

## Changelog
:cl:
add: pAIs may now choose to display their holoform as a bat, lizard, butterfly, or hawk.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
yes very nice

**Comment by Bigboyyo** [comment]
is good

**Comment by cacogen** [comment]
feral creep

**Comment by ExcessiveUseOfCobblestone** [comment]
based clockhawk

**Comment by tralezab** [comment]
i like this a lot but man pais should have never gotten holomobs to start with

**Comment by ExcessiveUseOfCobblestone** [comment]
> i like this a lot but man pais should have never gotten holomobs to start with

I missed when they could pull so they were pocket medics and harmyellers. Probably the only time people used them to great lengths.

**Pull request merged**
