### PR TITLE
Fixes Acoustic Guitar In-hands

### PR DESCRIPTION
**Pull request by SweaterKittens**
## Sprite Mix-up ##

It appears the acoustic guitar in-hands for east and west facing were switched. One looked okay, the other looked wildly out of place. The sprites are still terrible, but at least they look proper now.

Fixes Issue #24028

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@SweaterKittens update the PR please

**Comment by SweaterKittens** [comment]
I don't know how to fix a merge conflict like this.

**Comment by PKPenguin321** [comment]
export the new/changed sprites you added

open a git bash in your local build folder

enter "git checkout upstream/master -- icons/mob/inhands/items_lefthand.dmi" to reset the file in your local repo to the most up to date one from the upstream

reimport the sprite changes you exported in the first step

commit and push

**Comment by KorPhaeron** [comment]
Or recreate the pr and I will just merge

**Comment by PKPenguin321** [comment]
if you're only changing one sprite file, opening a new PR takes about the same amount of effort as just resolving the conflict

**Comment by AnturK** [comment]
Since this is switching two states,easiest way is to just reset to tg master and reapply the fix.

**Comment by SweaterKittens** [comment]
I wasn't able to get to this while I was working all week, should be ready to merge now.

**Comment by AnturK** [comment]
Sorry for conflicts. Forgot i didn't merge this yet.

**Comment by optimumtact** [comment]
Well it's still not ready

**Comment by AnturK** [comment]
I'll fast merge if anyone redoes this.

**Pull request closed without merging**
