### PR TITLE
Storage rebalance

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: Storage
tweak: Backpacks now give slowdown
tweak: Satchels gives no slowdown but have less space.
tweak: Duffelbags are relatively unchanged
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
I do not see the positive change in this. What will this do to improve the game? I feel it would just be a severe annoyance to players that already have significant inventory problems, such as Ops, Sec, Engineers, etc.

**Comment by yackemflam** [comment]
Did you even read the code?
Ops duffelbags are no slowdown.

This is a good change because this will make players have to take decisions on whether to take the small bag and still be the fastest, or take the larger bags and slow down a little.

This'll break the meta on grabbing satchels because there are no downsides to satchels.

**Comment by yackemflam** [comment]
>Downvotes without provided any feedback on why

**Comment by Iamgoofball** [comment]
why did bags need a nerf? they were fine as is

this feels like a way to just slow everyone down for the sake of slowing them down

**Comment by MrPerson** [comment]
Not everything needs to be a major life decision. It's fine to have things that are strictly better than other things if they're used as a progression path.

**Comment by kevinz000** [comment]
no :-1: you're bad.

**Comment by kevinz000** [comment]
also time to pass out bohs every round all day just to make this change irrevelant.

**Comment by yackemflam** [comment]
The nerf is here because you can counter the entire station with a normal backpack and your other storage slots.

>Box with 3 brute/3burn patches and a charcoal patch
>Box of engi tools + flash
>Sec belt with baton, flashbangx2, cuffsx2
>Pocket with extended oxygen tank refilled
>Other pocket with null rod
>Bloodred hardsuit for exosuit if syndie, sec hardsuit if not
>Gasmask
>Combat gloves if syndie/ Yellow gloves if not
>Sec hud
>Sec Bowman
>Gun in exosuit
>5 guns in bag/3 guns + other shit

**Comment by yackemflam** [comment]
@kevinz000 That actually takes work which I'm fine with

**Comment by Core0verload** [comment]
This is a shining example of balance-induced retardation.

**Comment by PKPenguin321** [comment]
This is awful :-1:

**Comment by Aloraydrel** [comment]
Why is this even a thing? Why do people think the balance meme = fun?

**Pull request closed without merging**
