### PR TITLE
Make metastation Tcomms accessible to engineers and CE

### PR DESCRIPTION
**Pull request by Sparkezel**
## About The Pull Request
Compared to all other station only on metastation its impossible for engineers and CE to fix the tcomms without screaming at ai, and most of the time if ai is malf/subverted it makes it completely impossible to fix comms without making a new network/calling the shuttle. This pr fixes that by making it finally possible to enter just from south of the station.
Update:
image
Old meta:
image

## Why It's Good For The Game
Makes tcomms actually possible to access without nagging ai or making others scream at you

## Changelog
:cl: SparkezelPL
qol: Meta Tcomms are easier to access
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
the hub or whatever you moved is now the only tcomms machine in the whole sat to not be on a circuit tile and its really upsetting

**Comment by Fikou** [comment]
also you fucked up
image

**Comment by Sparkezel** [comment]
yeah fixing that

**Comment by Sparkezel** [comment]
I tried to fix that, now it looks like that, pretty much the same
image

**Comment by TerryTehCoder** [comment]
What's with that Greenish Coloring on the tile as soon as you walk in?

**Review by patpol4 — CHANGES_REQUESTED** [review]
You're placing a cam and a lightbulb just hanging on nothing in the middle of the room.
Also the space between the two new airlocks is going to be dark unless you put a light in there.
Also the areas are wonky.

**Comment by Sparkezel** [comment]
> You're placing a cam and a lightbulb just hanging on nothing in the middle of the room.
> Also the space between the two new airlocks is going to be dark unless you put a light in there.
> Also the areas are wonky.

where are they hanging onto nothing? I do agree aboult the lack of lights in the new corridor though, areawise I have no idea

**Comment by Sparkezel** [comment]
image
alright, I hope thats better

**Review by patpol4 — APPROVED** [review]
Looking better

**Pull request merged**
