### PR TITLE
Phazons now use ectoplasm cores

### PR DESCRIPTION
**Pull request by Exester509**
## About The Pull Request

Phazons now use ectoplasm anomaly cores instead of bluespace ones. Text implying otherwise has been changed as well.
Allows ectoplasm cores to be bought via the science supply console.

## Why It's Good For The Game

Bluespace cores are some of the most overused ones in anomalock technology, and often the most desirable ones. Ectoplasm cores, however, have a single gimmicky and mediocre use.
This PR aims to make them more appealing to the crew while reducing machines that rely on bluespace anomalies, so their available number can be more freely tweaked.

## Changelog

:cl:
balance: Phazon mechs use ectoplasm cores now
balance: You can now acquire ectoplasm cores from the science supply interface
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Something worth noting is that at present I don't think you can buy these from cargo.

**Comment by Exester509** [comment]
> Something worth noting is that at present I don't think you can buy these from cargo.

That is correct. I'll make it purchaseable from cargo with a limit of 3 per round if there's no complaint, since its uses are so few.

**Comment by Exester509** [comment]
I chose to keep the limit of 8 for now, since seeing bluespace cores in excess isn't exactly common right now, despite there being mroe incentive than just the phazon. If a maintainer wishes so, I'll reduce their amount

**Comment by CRITAWAKETS** [comment]
Is it really a good idea to make the phazon able to use a core all to itself with a possiblity of 8 phazons in one round? Phazons are already _the_ best anomaly core thing you can make by far. Just pair one up with thermal vision and say goodbye to any threat ever.

**Comment by Exester509** [comment]
> Is it really a good idea to make the phazon able to use a core all to itself with a possiblity of 8 phazons in one round? Phazons are already _the_ best anomaly core thing you can make by far. Just pair one up with thermal vision and say goodbye to any threat ever.

That possibility has always existed, though it required the science department to be dedicated and coordinated (something that isn't really gone here), which is why I kept the 8 core limit. If it becomes a problem or some maintainer is concerned, I have no problems changing it though

**Comment by SimplySmiley123** [comment]
> Is it really a good idea to make the phazon able to use a core all to itself with a possiblity of 8 phazons in one round? Phazons are already _the_ best anomaly core thing you can make by far. Just pair one up with thermal vision and say goodbye to any threat ever.

I would argue Bag of Holding is far better then a Phazon.

Considering one is an item that allows you to carry bulky items you otherwise couldn't on you giving regular crew, stealth antagonists and loud antagonists a lot of potential utility, and the other is a clunky, expensive mech that seeing one is already a miracle which will also get owned by an Ion Carbine or some crackhead assistant that grinded iron and uranium and mixed both together.

**Comment by carlarctg** [comment]
ectoplasm anomalies are very rare so this effectively restricts phazons to refinement only

**Comment by DaCoolBoss** [comment]
Ectoplasm anomolies do nothing presently, right? Or has that changed?

**Comment by DaCoolBoss** [comment]
I meant the cores.

**Comment by Jacquerel** [comment]
On live servers nobody is crafting either phazons or bags of holding despite there being like 8 available bluespace cores so I'm going to go ahead and say that isn't a big problem I am worried about.
Ultimately, though we're definitely not close to being there, we want every core to have some kind of desirable item on it and preferably several competing options.

**Comment by Exester509** [comment]
> I meant the cores.

You can craft a special reactive armor with it, that animates nearby objects to fight for you... By doing low damage to random bystanders. Not really good, and very rarely seen

**Review by MrMelbert — APPROVED** [review]

**Comment by Eronymun** [comment]
Not sure if this was ever fixed but you **cannot refine** ecto anomaly cores at present with bomb refining. Additionally you can't buy these from cargo like Jac said, not that it matters if you can't refine it.

So unless they were made re fineable this restricts the phazon to only being made when someone collapses a ectoplasm anomaly, which is the rarest anomaly in the game.

**Comment by Exester509** [comment]
> Not sure if this was ever fixed but you **cannot refine** ecto anomaly cores at present with bomb refining. Additionally you can't buy these from cargo like Jac said, not that it matters if you can't refine it.
> 
> So unless they were made re fineable this restricts the phazon to only being made when someone collapses a ectoplasm anomaly, which is the rarest anomaly in the game.

They can be bought from cargo now, or at least from the science supply console, which should suffice. As for them being impossible to refine, I guess I'll change that next.

I really don't know why these things need to be so rare. The anomalies I understand, they're goofy and kinda unique, but the cores are almost never used, and as long as they're this exceptionally limited they'll remain this way, and new items using it won't be added.

If any maintainer or headcoder explicitly wants ectoplasm cores to be as rare as they are, though, please do let me know.

**Comment by Exester509** [comment]
> Not sure if this was ever fixed but you **cannot refine** ecto anomaly cores at present with bomb refining. Additionally you can't buy these from cargo like Jac said, not that it matters if you can't refine it.
> 
> So unless they were made re fineable this restricts the phazon to only being made when someone collapses a ectoplasm anomaly, which is the rarest anomaly in the game.

Checking again it doesn't mention raw cores not being refineable at all, in fact they can be randomly selected as roundstart inert cores, so they SHOULD be possible to refine. I'd say the PR is good to go if nobody has any objections

**Pull request merged**
