### PR TITLE
Trauma bug fixes, stalking phantom balance

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
balance: Stalking Phantom brain traumas will no longer stalk or attack people who are not conscious.
/:cl:

It's quasi-real beast made out of a person's fears, they can't fear anything if they're unconscious. Stalking Phantoms are no longer rendered useless by z level hopping or somehow destroying the hallucination.

Speaking of fears, phobias can now be granted according to type, for badminry and easier coding. Specific typed phobias aren't randomly selected to avoid diluting the pool.

This contains the non-cloning trauma based code from #41852.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
>Can't fear anything if you're unconcious.

You've never had sleep paralisys have you?

**Comment by coiax** [comment]
People are conscious while sleep paralyzed, that's the point.

**Comment by GuyonBroadway** [comment]
What about nightmares?

**Comment by zxaber** [comment]
So wait, is the phantom supposed to be in your head (and thus the damage is all fake damage), or is a brain trauma hallucination somehow actually dealing real physical damage just because you believe it is?

**Comment by coiax** [comment]
If you can traumatize a mind in such a way that they're naturally attuned to bluespace fields, why can't they be attuned to horrible dark forces?

**Comment by Borisvanmemes** [comment]
It's under the "magic" brain tramas in the code afaik.

**Pull request merged**
