### PR TITLE
Adds hooray emoji

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]:

:cl: Dax Dupont
add: Added hooray emoji!
/:cl:

[why]: Was requested by @KorPhaeron

### CODE REVIEW

**Comment by Armhulen** [comment]
YES

**Comment by KorPhaeron** [comment]
>hooray instead of tada

**Comment by DaxDupont** [comment]
You asked for hooray

**Comment by deathride58** [comment]
🎉

**Comment by MrStonedOne** [comment]
This is a good change.

**Comment by lzimann** [comment]
name it tada

**Pull request merged**
