### PR TITLE
Removes all budget cards except for cargo card, gives cargo small steady income -- [ACTUALLY WORKS THIS TIME]

### PR DESCRIPTION
**Pull request by genessee596**
Exact same as my earlier PR, but it actually works - [https://github.com/tgstation/tgstation/pull/47212]

## Changelog
:cl:
del: Removed all departmental budget cards except for cargo card
tweak: Cargo now gets 500 credits per paycheck
balance: Cargo can't amass infinite money from other departments
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Sorry, misclicked a dropdown

**Comment by dee-dubya** [comment]
Why exactly do we want to remove the ability for individual departments to order supplies for themselves? Especially with the current state of cargonia, constantly pissing their own budgets away on shit for themselves.

**Comment by SkeletalElite** [comment]
Vending machine prices for premium stuff needs to be dropped now, Especially secvend.

**Comment by genessee596** [comment]
> Why exactly do we want to remove the ability for individual departments to order supplies for themselves? Especially with the current state of cargonia, constantly pissing their own budgets away on shit for themselves.

Because what ends up happening is exactly that -- Cargo blowing money on guns -- except they get the budget cards from the other heads (who don't really care about their cards, since they have no use for their budgets), meaning they can have full SWAT gear 10 minutes into the shift.

**Comment by dee-dubya** [comment]
> 
> 
> > Why exactly do we want to remove the ability for individual departments to order supplies for themselves? Especially with the current state of cargonia, constantly pissing their own budgets away on shit for themselves.
> 
> Because what ends up happening is exactly that -- Cargo blowing money on guns -- except they get the budget cards from the other heads (who don't really care about their cards, since they have no use for their budgets), meaning they can have full SWAT gear 10 minutes into the shift.

Most heads don't give their budgets away like that. I certainly don't when I'm playing a head role.

Just because someone tides their way to getting all the infinity budgets on lowpop doesn't mean we should be removing an otherwise good mechanic.

**Comment by Kaffe-work** [comment]
I mostly dont give my budget away unless it's warops. And while i think they contain too much money, i can't imagine ever building a singulo/tesla/etc as CE if i gotta get that money from cargo - it's hard enough as it is. 

And good luck with warops without guncargo, looking forwards for 80%+ wr. Only real weapon apart from armory that crew can use will be meth/potassium lances, and boy are they not fun to use, either as crew or when facing them as Ops (and wiz for that matter)

**Comment by HomocidlePancakes** [comment]
>meth/potassium lances

Don’t tell him

**Comment by Learner10** [comment]
This PR still ignores all of the issues brought up in your previous PR.
There are a few ways to do it alternatively... maybe just tie the budget to the Department Head's ID account, since no sane person would willingly give their ID card away. Maybe just make the cards intangible and the account accessed by the department ID consoles.

Or maybe start dropping the prices on $600 dollar medkits and armor before such a proposal is brought up.

Maybe raise the price of guns in cargo.

Also RIP Bike.

**Comment by TheVekter** [comment]
I'm not a fan of this without doing something to make departmental vending machines less expensive. In my 20 or so rounds of QM in the last week, maybe... _once_ has someone given me a discount card. Don't remove, retool.

**Comment by jdawg1290** [comment]
One less reason to play the already underpopulated head roles

**Comment by carshalash** [comment]
Thanks for the massive cult and rev buff.. Very very cool

**Comment by bloons3** [comment]
Generally if I'm going CE and want to spice up the SM a bit, I'll blow my budget into the account and buy the shard privately.

**Comment by SynnGraffkin** [comment]
Local Orange man merges buff to antags during freeze, more news at 11.

**Comment by optimumtact** [comment]
#47303

**Pull request merged**
