### PR TITLE
Fix various issues with browser statpanel

### LINKED ISSUE #53298: The alt-click menu no longer includes the turf.
## Testmerges:
- #53263 

## Reproduction:
1. Alt click anything
2. Observe the alt-click menu in the upper right.
3. Realize that the turf isn't listed on it, making it anywhere between a pain(tables) to impossible (supermatter) to lay piping under objects and structures.

### PR DESCRIPTION
**Pull request by SpaceManiac**
- Keep tab buttons in view when scrolled down
- Unfocus tab buttons after click so scrollbar keeps working
- Fix some subsystem stat entries
- Improve key passthrough
- Fix runtimes from nulls in AI connected_robot list
- Add missing info in MC tab for global/config/etc.
- Fix #53298 by including turf in alt-click menu

Addresses @MrStonedOne's grievances. Closes #53261.

### CODE REVIEW

**Review by Couls — APPROVED** [review]
Looks good, i'm gonna PR a few unrelated fixes and key passthrough to your branch in a few minutes

**Comment by RaveRadbury** [comment]
Currenlty "readmin" does not appear for deadmins

**Comment by Couls** [comment]
In this PR specifically or just with the panel, if just with the panel please make an issue report

**Comment by MrStonedOne** [comment]
readmin seems to work on live, i'll test merge this and see

for reference, you can always request an admin hit reload-admins to un-deadmin everybody, or ask anybody with permissions access to manually un-deadmin you via the permissions panel.

**Comment by MrStonedOne** [comment]
Test merged this on terry, random verbs are not snowing up. I think they might be getting hidden by the tabs.

**Comment by MrStonedOne** [comment]
Yes, all the verbs not showing up are early in the alphabet.

**Comment by MrStonedOne** [comment]
Tested on terry, works fine.

**Comment by PKPenguin321** [comment]
Also remember that you can use the autofill feature of the command line ingame to get to verbs faster and avoid issues like these where they may arise in the future

**Pull request merged**
