### PR TITLE
Revert "Browser Status Panel"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#53112

If you scroll the verbs the tabs go out of view, this makes admining insufferable.

I'll be test merging this revert on all servers until this issue is fixed.

For reference, my screen resolutions:

Primary: 1360x768
Secondary: 1280x1024
Portrait 3rd: 1024x1280

My primary is much much bigger but older.

There are alot of things to come out of coderbus in recent months that has been insufferable to use on this type of setup, widescreen with auto zoom would give me a tiny side pane, but at least that was disableable.

### CODE REVIEW

**Comment by alexkar598** [comment]
Just disable the multi line tabs then? it looks a bit ugly but it works fine

**Comment by MrStonedOne** [comment]
>Just disable the multi line tabs then?

The what?

how would that help?

**Comment by MrStonedOne** [comment]
Also, another annoying thing about browser verbs, if you click on a verb tab, scroll stops working until you defocus the verb tab button by clicking in blank area

**Comment by alexkar598** [comment]
oh nvm I misinterpreted a thing

**Comment by optimumtact** [comment]
Primary: 1360x768

wtf, is your primary monitor a CRT?

**Comment by ZeWaka** [comment]
> Primary: 1360x768
> 
> wtf, is your primary monitor a CRT?

Lots of laptop monitors are 1366x768

**Comment by optimumtact** [comment]
It's worse, it's an LED tv

**Comment by Iamgoofball** [comment]
@MrStonedOne Get a standard resolution. Literally all 3 of your monitors are non-standard, holy shit.

**Comment by Iamgoofball** [comment]
Like, this is a PEBKAC issue. If you really don't like it and want to run a non standard resolution, feel free to use your GPU to force set your resolution to something else.

**Comment by Wayland-Smithy** [comment]
> @MrStonedOne Get a standard resolution. Literally all 3 of your monitors are non-standard, holy shit.

"1360x768" was obviously meant to be 1366x768 a standard 16:9 resolution, and 1280x1024 is a standard 4:3 resolution.

Regardless of resolution it is easy to understand why the tabs not being sticky at the top of the status panel could be awful if it is ever long enough to need scrolling. I am glad there is another PR to fix it.

**Comment by Iamgoofball** [comment]
No, this is MSO. He's definitely using that exact number.

**Comment by SpaceManiac** [comment]
Nitpicking resolution numbers helps no-one. Both of MSO's actual critiques are valid and are being addressed by #53263.

**Comment by optimumtact** [comment]
AN LED TV

**Pull request closed without merging**
