### PR TITLE
Adds a new rare mushroom: The odious puffball!

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR adds a new mushroom: The odious puffball.

It is a rare mushroom since the seeds only occasionally spawn in maint.

The plant contains spore toxin and nutriment but most importantly, it is a source of the gaseous decomposition.

odious_puffball

## Why It's Good For The Game

There has for a long time no practical way to introduce the smoke gene into a plant. Which is a shame, because some creative botany strategies are made possible with smoke.

This gives botanists a way to do that, though not reliably.

Since the spores spawn in maint and botanists do not have maint access, this allows enterprising assistants and cargo techs to engage in commerce with the botanists, thus also promoting economical activity.

And finally, spore toxin is a quite funny, unused but low power toxin that is very fitting for the plant.

## Changelog
:cl:
expansion: The spores of a new rare mushroom occasionally spawns in maint: the odious puffball! Gross.
/:cl:

### CODE REVIEW

**Comment by Krysonism** [comment]
bild

**Comment by Krysonism** [comment]
bild

Let the record show this PR was opened 20 min BEFORE when anturk said the freeze would start.

**Comment by AndroidMK2** [comment]
Sprites look very nice and the plant itself is a cool thing to have.

**Comment by BebeYoshi** [comment]
Oh my God, finally space cleaner plants will have an use... Anyways a smoke graft sounds pretty dangerous, I wonder if this will change balance... I surely can think of some dirty combinations that weren't possible as the only way to get smoke trait as of now is through random mutations and strange seeds, but you can't graft them. But it's still pretty random so whatever

**Comment by Krysonism** [comment]
I will try to animate the plant sprites today or tomorrow. 

I did all the sprites in 30 min and they could use some polish for sure.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
