### PR TITLE
Moves away from using GetComponent to delete components.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

This tries to replace the good ol qdel(GetComponent()) with a signal based approach.

## Why It's Good For The Game

This system is better in the way that we no longer delete the component directly and instead tell it to go ~fuck~ delete itself with a signal. This allows for easier deletion of components that can be applied multiple times and could even be used to a system for targeted deletion if you have multiple sources for a component.

### CODE REVIEW

**Comment by MrPerson** [comment]
Does this really need a changelog entry? They're supposed to be for the player's benefit, and you already concede that no players are gonna care about this kind of backend change.

**Comment by nemvar** [comment]
No it doesn't. I put the changelog there so I get the label.

**Comment by ninjanomnom** [comment]
I see no good reason to do this. GetComponent isn't inherently bad, it just has very few good use cases and is indicative of potential problems. Getting a component to delete it is a reasonable use case of GetComponent.

GetComponent is bad generally because when it's used it means some external code to the component is deciding how the component should act. Sending a signal to delete a specific component is identical conceptually to calling GetComponent and deleting it yourself.

We already have a generic system for deleting a component externally and switching to this method just reduces readability.

**Comment by nemvar** [comment]
Fair enough

**Pull request closed without merging**
