### PR TITLE
Makes tails stop wagging when unconscious or stunned

### PR DESCRIPTION
**Pull request by ShizCalev**
You can't start wagging while unconscious, however if you were wagging prior to the unconscious state, you continue to. This fixes it.

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
do you resume wagging once conscious or unstunned?

**Comment by ShizCalev** [comment]
no.

**Comment by kevinz000** [comment]
NO!!!!

**Comment by Spaceinaba** [comment]
this is a good nerf

**Comment by FantasticFwoosh** [comment]
Zipties & anesthetic tanks + airmasks are the best thing ever.

**Pull request merged**
