### PR TITLE
Locks ebow behind a 25-player limit, same as the desword.

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Does as the title says.

## Why It's Good For The Game
The ebow is a pretty easy ranged stun. Takes multiple shots to down you, sure, but that's not very helpful when most roles don't have ranged weapons lying around. Low-pop rounds lack the effectiveness of calling for help, and there's not really enough people to mob together and get a proper counter-force (not to mention sec is almost always empty during these rounds).

## Changelog
:cl:
balance: You can no longer buy an ebow with less than 25 players.
/:cl:

image

### CODE REVIEW

**Comment by Tumesuo** [comment]
Or just delete people who murderbone when player count is less than 30 smh

**Comment by JJRcop** [comment]
We are still in antag freeze, but if a maintainer decides to greenlight this then you're good.

**Comment by Difrit** [comment]
i ded pr

**Comment by Ty-the-Smonk** [comment]
Iirc ebow is kinda shit right now since the stun is not long enough to do anything off of

**Comment by carlarctg** [comment]
> Iirc ebow is kinda shit right now since the stun is not long enough to do anything off of

It's been changed into a disabler+, it fires shots that stun for a second but do 10 tox and 60 stamina damage

**Comment by Ty-the-Smonk** [comment]
> > Iirc ebow is kinda shit right now since the stun is not long enough to do anything off of
> 
> It's been changed into a disabler+, it fires shots that stun for a second but do 10 tox and 60 stamina damage

Ok this ided pr makes a bit more sense now

**Comment by anconfuzedrock** [comment]
only reason I dislike this is because I think the issue with the ebow is it needs a nerf, not that it needs to be restricted. if a traitor at 25pop can't have it, a traitor shouldn't have it at any pop

**Comment by nemvar** [comment]
I agree with this nerf but this really can wait until the freeze is over.

**Comment by necromanceranne** [comment]
If players are murderboning in lowpop that's entirely a player problem. The ebow actually can be defeated by properly armed groups of people, especially since disabler spam is a very powerful method of fighting just about anyone and heavily punishing the ebows cooldown in particular. Unless the population counts are so low (I'm talking dead pop hours of 10 people or something) where that just isn't feasible, then it's actually not going to matter whether they use an ebow or a combat shotgun they brought from cargo or a stechkin, which is cheaper and comes with HP rounds as an option to easily cap anyone in seconds. These last two are also options in lowpop. I've been on the receiving end of 5 minute flat HP stechkin murder. It's really shit. And it's faster than what the ebow can achieve because it's basically a cheap revolver with an even better reload and easy concealability.

The core issue is not the weapon, which is one of the few true cloak and dagger murder tools traitors have. It's that simply put, lowpop of like 20 or less should have a heavier restriction on murderboning. Because they'll move onto a different weapon if it isn't this one (sleeping carp isn't population locked I believe). Curating the traitor's list is really not going to do much good other than giving fewer and fewer options out of the uplink to achieve your goals for the round, because traitors do get murder objectives at these population counts, murder is a means to a goal, and if you can't do it quietly, you inevitably must do it loudly, which forces their hand in having to kill a bunch of people anyway as we inevitability will have people who go to validhunt. It's a punishing recursive cycle that many of these code changes cause that really do make me wonder if we should even have antag rounds at such low populations if people can't take to getting murdered.

If they succeed, they're a bad player because they depopulated the station of a lot of life that came to put them down. If they fail, then the round becomes extended as any resistance the antag could have put up is immeasurable to that of station weaponry. I honestly believe a bunch of assistants with improv shotguns can take out any antag with ease. An ebow man is nothing compared to bodies. And population in the 20's can gather enough people to fight this weapon. It's something I see pretty regularly.

Code changes aren't going to do shit compared to a re-evaluation of whether we should be permissive of the actions of a few problem elements utilizing our antag role to go on killing sprees. Because our rules are permissive of validhunting, the few who aren't looking to go on killing sprees often HAVE to go on them in self defense. The only way to not have that happen is stealth weaponry. AKA the ebow. If they can't stealth, they must go loud as there is no more option open to them. And thus the problem triplicates as the nuclear option (loud extreme violence to end the round quickly) is the only option.

**Comment by carshalash** [comment]
The ebow isn't even really that great anymore, locking it behind 25 players is just weird.

**Comment by Shadowflame909** [comment]
Maybe if it was the old e-bow

But like others said. It's basically a syndicate disabler now. Just call for help

Being able to solo anything an antagonist can bring out is lame

**Comment by Timonkeyn** [comment]
https://github.com/tgstation/tgstation/pull/42054 I tried this before and yall shit posted on it like mongoloids and I'm genuinely mad if this gets merged

**Comment by zxaber** [comment]
To be fair, that was before we were on a crusade against stuns. Now the ebow is an upgraded disabler and is better than any individual item security has.

**Comment by 81Denton** [comment]
This has been greenlit by @optimumtact according to that screenshot

**Comment by Timonkeyn** [comment]
Why esword though

**Comment by Fhaxaris** [comment]
> #42054 I tried this before and yall shit posted on it like mongoloids and I'm genuinely mad if this gets merged

and it gonna happen during the antag freeze feels bad

**Comment by ExcessiveUseOfCobblestone** [comment]
this fixes a really specific issue for very little gain (just use another weapon in the magic goodie bag).

Not sure what the end goal is here but I don't think just blocking this guy disables easy-to-access murderbone tools on lowpop.

**Comment by zxaber** [comment]
Mostly, it's a result of me not really liking that sec has been getting nerfed while antag items come out mostly unscathed. In this case, we have what boils down to a tier 2 disabler with unlimited ammo and is pretty quick to drop people. If nothing else, I feel like it shouldn't be available when the population on the server is so low that you can just walk through the halls ebowing people and offing them without ever worrying that you'll be seen. Most other ranged weapons at least have an ammo resource that has to be managed.

**Comment by Shadowflame909** [comment]
Yeah but disablers just got a buff and this item got super nerfed.

**Comment by Ty-the-Smonk** [comment]
Carp is like 10x worse than this

**Comment by zxaber** [comment]
Perhaps, but at least carp requires you to be within melee range. That gives the victim a chance to fight back, even if it's not a high chance of winning.

**Comment by actioninja** [comment]
> it's a rules issue that you're trying to code around.

we do that a lot here.

**Comment by Shadowflame909** [comment]
Cringe

Coders need the headmin vote again.

**Comment by ExcessiveUseOfCobblestone** [comment]
why don't you code a config option for it then and be the change you want to see 😏

**Pull request merged**
