### PR TITLE
Reverts the recent config changes

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request
Too many things are broken, this needed way too much time in the oven. Overriding config options is borked, so is multientry items. There might be more

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
it made me "mothblocks harrington" the human, and thats just not ok

**Comment by Jared-Fogle** [comment]
merge it once ci passes

**Comment by LemonInTheDark** [comment]
[TFW](https://www.youtube.com/watch?v=YFJAq51e-Dg) config breaks in 3 different ways after a unit test pr

**Comment by MrStonedOne** [comment]
Jesus fucking Christ.

Can we please put the pr being revertted in the fucking pr body so the revert pr shows up on the original pr so people don't port it for no reason

#56602

**Pull request merged**
