### PR TITLE
fixes #22222, and also a costume

### LINKED ISSUE #22222: autodrobe has some items unstocked roundstart
see title, how can I bee a bee without my bee suit

### PR DESCRIPTION
**Pull request by dannno**
:cl:
add: Adds a villain costume to the autodrobe.
fix: Fixes autodrobe failing to stock items.
/:cl:

fixes #22222, and also adds a little costume

RATIONALE: I THOUGHT IT WAS A NICE LITTLE COSTUME FOR CLOWNS TO CLOWN AROUND IN AND IT MIGHT BE FUN

### CODE REVIEW

**Comment by TehZombehz** [comment]
More memes, yay.

**Comment by ExcessiveUseOfCobblestone** [comment]
you done goofed

**Comment by dannno** [comment]
piss in my eyes ill fix the conflicts in a bit

**Comment by Iamgoofball** [comment]
time to add dat boi and harambe and every other meme that shows up now and forever bloat costume files for something no one will use in a week

**Comment by ExcessiveUseOfCobblestone** [comment]
a unicycle is a valid feature though

**Comment by Grazyn** [comment]
LazyTown being a show that is aired in over 180 countries, this reference doesn't require extreme popular culture knowledge to be understood, unlike other much more obscure references like the boss of this gym costume

**Comment by WJohn** [comment]
we added this meme before the spy got it in tf2

think about that for a second

**Comment by Anonmare** [comment]
Now I can do what I want cause a pirate be free.

**Comment by MMMiracles** [comment]
número uno

**Comment by dannno** [comment]
>you done goofed, you made a branch from your mask PR
how would i have done that if i deleted that branch before even making this

**Comment by dannno** [comment]
ok its done haha

**Comment by ExcessiveUseOfCobblestone** [comment]
because github is gitdumb

**Comment by FantasticFwoosh** [comment]
Clear out & replace stock with new vendor internal stock 4 times

= New robbie rotten stealthops.

**Comment by TehZombehz** [comment]
Custom Nuke Op War Declaration:
We are number one!

**Comment by Iamgoofball** [comment]
@Grazyn all I hear is the same argument used for every single one of these stupid one off fads

**Comment by Aurantiaco** [comment]
all I hear is goofball being a cynical gayboy complaining about memes when he himself, along with everything he has coded, is currently coding, or will code in the future being the biggest, spiciest meme to ever grace society and the human condition. give a round of applause to goofball my friends, the master of the ass sticking technique. maybe we could study his anus to see how he does it so effectively, once he gets done with being railed by his 5 black boyfriends, of course. go huff some freon gas and step off of the pier of life, sink to the murky depths, and never darken the door of this, or any other, space station 13 codebase ever again my main man homie g. this place would be better off without your mistakes, motherfuckin' ice gas lookin' ass bitch boy. climb to your chromosome count and jump down to your iq level.

Goofball no goofing.

image

**Comment by dannno** [comment]
i just thought it would be funny

**Comment by TheFriggenSawbones** [comment]
[img]http://i.imgur.com/qrvghRd.png[/img]

**Comment by TheFriggenSawbones** [comment]
goof

**Comment by KorPhaeron** [comment]
Doesn't include any rationale for the change in the OP

**Comment by ExcessiveUseOfCobblestone** [comment]
Is fixing a bug not a rationale?

**Comment by KorPhaeron** [comment]
The absence of lazy town outfits in the game isn't actually a bug believe it or not

**Comment by ExcessiveUseOfCobblestone** [comment]
I was referring to the autodrobe has having unstocked items, the main point of the PR, but yes add a "more cosmetic options are interesting" part to the OP to appease the kor.

Maybe the better thing to do was separate the two tbh.

**Comment by dannno** [comment]
updated with rationale

**Comment by KorPhaeron** [comment]
thats a pretty good rationale

**Comment by dannno** [comment]
ty ty

**Comment by KorPhaeron** [comment]
@Aurantiaco 

godamn I guess I gotta merge it now

**Comment by Iamgoofball** [comment]
i'm printing a copy of that and framing it above my computer

**Comment by dannno** [comment]
ok?

**Comment by ExcessiveUseOfCobblestone** [comment]
i'm sorry for being snide @KorPhaeron

**Comment by jughu** [comment]
Im gonna steal this costume whenever im traitor number one

**Comment by jughu** [comment]
Is your name optional name? - pkpengiun

**Comment by Arianya** [comment]
If its okay for there to be homestuck references, its okay for there to be lazytown references.

**Comment by karlnp** [comment]
idea: remove all homestuck and all refs in general

**Comment by Mervill** [comment]
It's the clown, so I think the no memes rule is a biiiit bendable.

COMPROMISE: Can it be just a striped suit and hair, not a 'villain' costume?

**Comment by Aloraydrel** [comment]
>goof complaining about memes

World is ending

**Comment by dannno** [comment]
good idea @mervill

**Comment by ShadowDeath6** [comment]
wasn't goof the one to add the lavaland gym and the leatherhead thing

**Comment by Iamgoofball** [comment]
Those are finely dated well aged memes.

**Comment by KorPhaeron** [comment]
more bloat

**Pull request merged**
