### PR TITLE
Food now has a lesser impact on mood

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Makes the negatives of going hungry and benefits of being fed less impactful on mood. 

## Why It's Good For The Game

Hunger system is hunger system, mood system is mood system. Theres nothing wrong with them going hand in hand, but not eating is punished by a movement slowdown, and its a kick in the face to make you go insane too. Being starving still does provide a harsh impact, but no where near as debilitating as it was. Now you can go afk for 10 minutes without going insane!

## Changelog
:cl:
balance: Food now has a lesser impact upon mood
/:cl:

### CODE REVIEW

**Comment by YakiAttaki** [comment]
Will this make it harder to get the best mood state by eating food that you love?

**Comment by wesoda25** [comment]
i suppose so please never comment on one of my prs again

**Comment by Shapsy** [comment]
benefits of being food

**Comment by wesoda25** [comment]
> benefits of being food

you get a crazy mood buff if you are an egg based or meat based food very unfair i had to nerf sorry shaps :(

**Comment by optimumtact** [comment]
how long before hunger upsets you now?

**Comment by wesoda25** [comment]
> how long before hunger upsets you now?

Ill do some testing tomorrow

**Comment by Qustinnus** [comment]
I'd say the change is good but these numbers are too big of a difference. make it -6 and -10 and its good.

**Comment by Akrilla** [comment]
After figuring out mood, it's super easy to get to a reasonable mood if you just purposely search for things to improve it. I can go from insane to normal/fine if I just: go to bar > have a drink > eat from kitchen > shower > hug people. You can even throw in book reading and animal petting too. 

I think the issue is more people ignore the mood system entirely then get annoyed when they get the side effects.

**Comment by carlarctg** [comment]
i too, love to go through the List of Alloted Roundstart Hugs before i can move on with my round and do something else more engaging

good PR, instantly going I Am Very Upset at the start of the round is annoying

**Comment by wesoda25** [comment]
After some testing, I don't think satiety level is actually enough to cause you to go insane anymore on its own. If it can, it takes quite a while. I think its a good change.

**Comment by wesoda25** [comment]
Also -6 and 10 are too small a difference

**Comment by Qustinnus** [comment]
lol so -14 to -10 is not too small of a change. it's basically 1/3th.

**Comment by Qustinnus** [comment]
and -6 prevents you from getting into very sad territory while still putting you at the border, which is better.

**Comment by wesoda25** [comment]
Ok dude, thats still not very good. I've done the testing, 4 and 8 are good numbers. Still possible to go insane from starving, but it takes upwards of 30 minutes which is much more realistic (yeah yeah realism doesn't matter, but going insane from being hungry so quick was just ridiculous). I think they're pretty solid numbers now.

**Comment by Qustinnus** [comment]
do you not understand basic english? -10 and -6 do the exact same as -4 and -10 in terms of how long it takes to go insane.

**Comment by wesoda25** [comment]
Thats cool quistinnus because the numbers im going for are -4 -8. It makes 0 sense that being a little hungry would have such a harsh effect on mood.

**Comment by Qustinnus** [comment]
you're starving at the second moodlet, not a "little hungry". hunger used to literaly insta-slow you if you were low on nutrition, I've lowered the slow, made it take ages to actually reach the slow, and yet you're still whining that its too much.

**Comment by wesoda25** [comment]
I know that. Just being hungry is fine at -4, it makes sense. For being starving, -8 is a similarly good number due to the time it takes to go insane. Slow is still in game, thus not being fed already has punishments in the form of mood system. No need to double whammy on the mood system too.

**Comment by Qustinnus** [comment]
????

hunger doesn't slow you down retard. I removed that and replaced it with the effects of mood, which is partially why hunger also effects mood so much, because hunger lost its downside ages ago.

I can't tell if you're trolling or not at times. I made hunger easier to deal with by making the slow
1. take time to kick in
2. way more difficult to get
and yet still you are here acting as if the difference between -8 and -10 will be too immense.

**Comment by wesoda25** [comment]
yeah its too small a change -8 is better and actually changes stuff

**Comment by Qustinnus** [comment]
-8 to  -10 and -4 to -6 set sanity drain to the same value so that's a non-argument. They both change stuff.

**Comment by wesoda25** [comment]
whatever i clearly don't get something and getting called a retard every 5 seconds doesnt help, ill wait it out and see what nemvars changes do or whatever the fuck is supposed to fix what is apparently wrong

**Pull request closed without merging**
