### PR TITLE
Re-areas Xenobiology 2 to allow console placement on the grinders + Blastdoor Fixes

### LINKED ISSUE #56590: Issue with metastation's new xenobio
## Round ID:
[155527](https://scrubby.melonmesa.com/round/155527)

## Testmerges: 
#56509 #56221 

## Reproduction:
 When using the xenobio terminals on metastation's new xenobio (#56354) , there is a wall preventing me from dumping dead slimes picked up into the slime processor, right here, where the firelocks are: 
issue1
There is also an issue with the terminals not being linked automatically like all other xenobios are.
image
This is really annoying.

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

Me on station seeing Xenobio unused: "Why dis unused?"
Me seeing issue on da github: "Oh, dis why".

I fix.

## Why It's Good For The Game

Xenobiologists are used to being able to directly place their slimes, cherry picked by the slime management consoles, into their blenders below. I forgot to map the corresponding area over these grinders in my initial commit. This will reenable that functionality while still maintaining the faux separation of the xenobiology and cytology areas.
Fixes #56590

I've also added blast doors to the windows adjacent to the pens (1 and 8) and to the consoles. For the protection of the scientists. 

## Changelog
:cl:
add: Blast Doors on the windows to the Xenopens adjacent to the management consoles
tweak: Renamed a Blast Door 7 on Slime Pen 8 to reflect that it's on Slime Pen 8
fix: Xenobiologists can drop slimes directly onto both grinders again.
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by nightred** [comment]
Can you fix up these AT's?
Starboard Quarter Solar Array (149,55,2) (JMP) Yes this is solars i know.
Space (171,78,2) (JMP) 
Space (171,94,2) (JMP) 

Also this double wire? (there is more if you like)
Doubled wire at Cytology Lab (159,86,2) (JMP)

**Comment by Zytolg** [comment]
Something went wrong during the last upstream merge, so I'm gonna go in and swap out the Repo with a fresh download and transplant the map.

**Comment by Zytolg** [comment]
But it's still telling me that I have 130k changes. I'll get on that.

**Comment by Zytolg** [comment]
I'm gonna refork and redo the changes. I'm having trouble with my repo so it'll just be faster to remake these few amount of changes.

**Pull request closed without merging**
