### PR TITLE
Scannergates 2.0

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
XGWvtJbPH9

Scanner Gates can now have assemblies attached to them! Allow you to trigger anything you want with them!

There are 5 wires on them now.
Successful Scan
Failed Scan
Toggle Signaling
Disable Signaling
Enabling Signaling

<will attach video>

## Why It's Good For The Game
Imagine the possibilities! Traps! Security Checkpoints! 
 

## Changelog
:cl:
add: Scanner Gates can now trigger assemblies!
/:cl:

### CODE REVIEW

**Comment by WarlockD** [comment]
We cant have a commie station without a checkpoint!

**Comment by Axanthic** [comment]
This shall make my atmos gas chambers at least 40% more effective.

**Comment by Jared-Fogle** [comment]
> 🆑
add: Added new things
add: Added more things
code: changed some code
/🆑

Good changelog.

**Comment by AutisticFroggy** [comment]
Definitely going to port this once it gets merged, looks great!

**Comment by Wayland-Smithy** [comment]
>Good changelog.

@Axanthic Unless you update it to actually reflect your changes or opt not to inform players via the in-game changelog at all and just delete it I doubt it will pass muster. You're meant to edit the text after the `add:` and `code:` describing what was added, and what code changes were made.

Might want to convert to a draft if the PR is still a work in progress.

**Comment by Axanthic** [comment]
@Wayland-Smithy Fixed, IT should be all set to be merged.

**Comment by Axanthic** [comment]
> Definitely going to port this once it gets merged, looks great!
Gross yogstation

**Comment by Doosteroni** [comment]
Yog is NOT pog

**Comment by Axanthic** [comment]
Closing fuck oranges
image

**Pull request closed without merging**
