### PR TITLE
Less is more - Nerfs explosion camera shake

### LINKED ISSUE #34004: SME Delamination gives weird blackscreen visuals then returns to normal.
Round ID: 81184

Server revision compiled on: 2018-01-01

The following pull requests are currently test merged:
33979: 'Implements the Ballmer Peak: Now the bartender can help R&D!' by Iamgoofball at commit aeae5e
33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 49f8a0

Based off origin/master commit: e84a7f

### PR DESCRIPTION
**Pull request by deathride58**
lESS IS MORE JESUS FUCK

:cl: deathride58
tweak: Explosions will no longer give everyone and their mothers motion sickness from a mile away.
/:cl:

closes #34004

### CODE REVIEW

**Comment by praisenarsie** [comment]
test it

**Comment by deathride58** [comment]
Already did.

**Comment by MrStonedOne** [comment]
Give it a diminishing returns curve so admin meme explosions aren't bad either.

**Comment by MrStonedOne** [comment]
Actually, a sqrt() would work perfectly here.

**Comment by vuonojenmustaturska** [comment]
if baseshakeamount is <=0, do not call shake_camera(). It is not a no-op with 0 strength.

**Review by ShizCalev — DISMISSED** [review]
check for baseshakeamount being =<0

**Comment by FantasticFwoosh** [comment]
Now you need a admin button with a var value to set explosion shakeyness from nearly 0 to bucking-bronco

**Comment by MrStonedOne** [comment]
This broke explosions

**Comment by Cyberboss** [comment]
Someone has a fix up

**Comment by deathride58** [comment]
#34091

**Pull request merged**
