### PR TITLE
Prevents the creation of Shadowzombiechangelings

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It is not a good thing when a changeling dna stings a nightmare and then dna stings the whole station and then also romerol gets out

I mean it was exciting once but lets not have it be a regular occurrence

### CODE REVIEW

**Comment by XDTM** [comment]
Told ya

**Comment by demonfiren** [comment]
this is fucking beautiful and makes me regret not playing more

**Comment by MoreRobustThanYou** [comment]
hahahaha

**Comment by SyruseEln** [comment]
Top 10 TC trades gone wrong!

**Comment by Shadowlight213** [comment]
Isn't this already covered by notranssting? Is there a specific reason to block a ling from absorbing them?

**Comment by ExcessiveUseOfCobblestone** [comment]
Why do we hate the memes produced by transform sting so much, yet insist on keeping it in?

**Comment by MoreRobustThanYou** [comment]
@ExcessiveUseOfCobblestone because it's funny to turn everyone into the clown

**Comment by ExcessiveUseOfCobblestone** [comment]
So only when it has no impact on your combat ability :thinking:

**Comment by KorPhaeron** [comment]
@lzimann

**Pull request merged**
