### PR TITLE
Space syndie listening post now uses antur's ruin chances.

### PR DESCRIPTION
**Pull request by WJohn**
It will now spawn at 1/4th frequency. You either get the ruin (which you can now play on guaranteed, the simple animal thing with 10% ghost role chance is gone) or it doesn't spawn at all.

:cl: WJohnston
tweak: Space syndie listening post is now always a ghost role again, however it spawns in at 1/4th its previous frequency.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
But you still haven't said why it's important to duplicate a role into space where nobody can strike back at it

If it's at 10% frequency or 1/4% why do we need it at all when we have the exact same role already in another spot with more stuff and a better chance the crew can do something about it?

**Comment by WJohn** [comment]
Because people enjoy the comms role and being able to direct syndies. It's also nice to make the syndicate encryption key more worthwhile.

**Comment by KorPhaeron** [comment]
Yes but we already have a ruin that did that. The syndicate comms key is already worthwhile.

And the crew enjoys their comms not being an absolute shit show with an invincible syndicate "AI" every round

The lavaland base and the listening post filled two different roles as ruins (one as an antagonist/overwatch/learning area for the crew to raid and destroy, and one as some comms equipment an explorer could screw around with + a little bit of worldbuilding)

**Comment by KorPhaeron** [comment]
Closed for the reasons above+what we discussed in coderbus

**Pull request closed without merging**
