### PR TITLE
RPED and crew pinpointer module upgrades for engi/medical borgs

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Pretty self-explanatory. With more machines becoming buildable and upgradeable, it makes sense to increase the amount of hands being able to upgrade machines. Crew pinpointers for mediborgs have probably been the most-requested module for borgs overall.

Borg RPED has a slightly different sprite so that you can tell it apart from the real deal in robotics.

image

:cl: Naksu
add: Exosuit fabricators can now build RPED and crew pinpointer upgrades for engineering and medical borgs respectively.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by GunHog** [comment]
Could there be the bluespace version of this, requiring both the cyborg node, and the node for the human BSRPED counterpart?

**Comment by vuonojenmustaturska** [comment]
There could, but since borgs do not have any of the problems humans have wrt access and carrying a screwdriver, and this module being somewhat deep in the tech tree already, i don't see much use for one.

**Comment by DaxDupont** [comment]
Eh, it's annoying to mass upgrade without bluespess rpeds.
Imagine having to screwdriver every botany tray to upgrade.

**Comment by DaedalusGame** [comment]
you can do up to 6 at once so i don't see the issue, gamer

**Comment by ExcessiveUseOfCobblestone** [comment]
imagine an upgrade that allows you to bluespace rped all machines in view with 1 click.

**Comment by GunHog** [comment]
The BSRPED has a number of worthwhile advantages:
- Remote upgrades and part scanning through the camera network
- Does not require the machine to be opened
- Up to 400 items stored, whereas the basic one has only 50
- Ability to bluespace-transfer stored parts to other storage containers in range, including the human-held RPEDs

A BSRPED is just as much desirable to a cyborg as it is for a human.

**Comment by DaedalusGame** [comment]
wait what are you telling me it works through cameras???

**Comment by GunHog** [comment]
Yes, it is both intended and the best part of using one. Engineers and Botanists absolutely love you for it.

**Comment by DaedalusGame** [comment]
this sounds dumb to me considering the arcd is range limited

**Comment by GunHog** [comment]
Building and destroying stuff from a distance is significantly stronger than upgrading machine parts. You cannot do anything antagonistic or dangerous with the BSRPED.

**Comment by DaedalusGame** [comment]
🤔

**Comment by GunHog** [comment]
It stands for "advanced":
https://github.com/tgstation/tgstation/blob/d282c60c7d1056a2a98968f6fc00b70fcfb71c21/code/game/objects/items/RCD.dm#L451-L452

An admin-only item is of no consequence anyway; It is not necessary to maintain consistency with something that cannot be normally obtained. If you still consider it significant, then consider doing so with the ARCD. It does not change my position based on the point previously given.

**Comment by DaedalusGame** [comment]
thatwasthejoke.jpeg

**Comment by ExcessiveUseOfCobblestone** [comment]
toucan't just go around and joke about these things

**Review by WJohn — APPROVED** [review]

**Pull request merged**
