### PR TITLE
adds the debug omnitool

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds the debug omnitool, when you use it in hands you get a radial that shows you all the different tool behaviours you can have and you pick one
its also very fast
thank you actioninja for making easy to copypaste radial code with cable layers

## Why It's Good For The Game

good for testing

## Changelog
:cl:
admin: the debug outfit now has an omnitool
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
image
heres how it looks ingame

**Comment by trollbreeder** [comment]
One question though
does it vibrate like a holotool?

**Comment by Fikou** [comment]
> One question though
> does it vibrate like a holotool?

### **STOP FUCKING ASKING IF THEY VIBRATE**

**Comment by V2LenKagamine** [comment]
Good PR is good PR.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
