### PR TITLE
Bygex loading admins and default autoadmin on with GM rank

### PR DESCRIPTION
**Pull request by Jordie0608**
Converts loading and re-adminning of admins to use Bygex. Fixes the rare error of an admin being unable to re-admin if their ckey on config/admins.txt had a space in it.

Changed Auto-admin config to use GameMaster rank and be on by default.
Why? It's designed for testing purposes and to help people not having to edit themselves onto config/admins.txt all the time, but editing a config file to enable it is roughly the same issue as that was. GameMaster rank gives access to a couple of buttons that GameAdmin doesn't have. The config for it has been moved to the top of config/config.txt so it's hard for server owners to miss.

config/admins.txt was all nicely lined up but that seems to have died, thanks git.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
>Added config for automatic syncing of debug access. When enabled this adds any ckeys from config/admins.txt to cfg/debug_access.txt if they aren't there already so it no longer has to be manually synced for servers that keep the two so, like tgstation does.

Protip, we can just get rid of this file now

world.SetConfig("admins") will allow us to control this in game

**Comment by Jordie0608** [comment]
>All this code you did means nothing

A thousand tears ;_;
Sounds cool but I can't be bothered to fiddle with that currently

>Also, we can restrict the restart client side debug tool to those with +server now because reboot() sets usr if the client side debugging tool's server->reboot command is used.

There's been a few times when I used it to force a restart when the reboot buttons weren't working, wouldn't that interfere with being able to do so if you didn't have +server?

>Also, I don't know about bygex loading admins. I don't trust it, and it makes it more complex to modify the format.

The format is almost the same (and actually a fuzzier than specified)

**Comment by MrStonedOne** [comment]
>The format is almost the same (and actually a bit fuzzier than specified)

No, what i mean is code wise, it makes it harder to understand the allowed formatting, it makes it harder to understand exactly how the code would process a given string by reading it, and it makes it harder to expand the format.

**Comment by Jordie0608** [comment]
Oh in that case then yeah I guess. It's probably because I wrote it but I find the code for regex text parsing much easier to read than the native implementation. Can't really comment on the extensibility since I've not used the native, but I don't think it'd be difficult.

Either way learning regex would be required, which was easier than everyone makes it out to be.

**Comment by Jordie0608** [comment]
Played around with SetConfig, while it seems to work I have far too many questions on it's functionality to attempt to implement it right now. In the meantime I've removed the debug syncing changes since there's little point in adding them if the txt slated for removal.

**Pull request closed without merging**
