### PR TITLE
Allows you to directly interact with beakers inserted in a PanD.E.M.I.C. with droppers and syringes

### PR DESCRIPTION
**Pull request by ShizCalev**
## About The Pull Request

Title.

## Why It's Good For The Game

Cuts down on having to insert/remove beakers 50 billion times

## Changelog

:cl: ShizCalev
qol: You can now directly interact with beakers inserted in a PanD.E.M.I.C. with droppers and syringes!
/:cl:

### CODE REVIEW

**Review by MrMelbert — DISMISSED** [review]

**Comment by Wallemations** [comment]
Remind me if there's an option to empty a beaker in a PanDEMIC without taking the beaker out?
I'm like 80% sure there is

**Comment by ShizCalev** [comment]
There is. :)

**Comment by Wallemations** [comment]
Sick

**Comment by CursedBirb** [comment]
What a monstrosity of pr it is. It cuts like half of wasted time. I love this but at the same time it takes more from viro. How? The faster you finish your virus the less you have to do. We really need to change how viruses work

**Pull request merged**
