### PR TITLE
Update to the Android

### PR DESCRIPTION
**Pull request by Myphicbowser**
## About The Pull Request

Just a small little balance, removing the ability to reattach limbs from the ground since who knows what kind of damage you would need to repair for that to come back on, and the heat resistant trait, since over heating is a real issue in robotics and in machines in general, and I kept the inability to catch fire since metal doesn't burn to well but can still be damaged by fire, just a small update so that androids may become playable once again.

## Why It's Good For The Game

Again just a small update, such a neat feature and race in general was just removed from the game, I know a lot of races do exist but the more the merrier am I right?

## Changelog
:cl:
del: Removed TRAIT_RESISTHEAT, and TRAIT_LIMBATTACHMENT
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
It's worth thinking about to figure out a way to make the check more granular rather than straight up remove it. I ran into this problem with IPCs way back when, [my solution was less than elegant](https://github.com/OracleStation/OracleStation/blob/44d0eeb1be73e112c9a71323c6dd659894f020f6/code/modules/surgery/bodyparts/bodyparts.dm#L68) however.

**Comment by Shadowflame909** [comment]
Might want to combine this PR with one that re-adds the race then.

**Comment by Barhandar** [comment]
Cyborgs are fire-immune and the point of androids is to be human-shaped cyborgs (who are also slightly skeleton)

**Comment by zxaber** [comment]
>since over heating is a real issue in robotics and in machines in general

Same for space stations but we don't take kindly to the laws of thermodynamics 'round here.

**Pull request closed without merging**
