### PR TITLE
Replaces pubby whiteship

### PR DESCRIPTION
**Pull request by spiders24110**
## About The Pull Request
Replaces pubby (UFO) whiteship with a different one, NT Research Vessel
white1
Fullbright:
white2
Map:
white3

Semi-cool loot: 3 random bepis tech disks, lazarus
## Why It's Good For The Game
Pubby whiteship, while unique, looks pretty lame. Also medbeam gun is bad, apparently.
## Changelog
:cl:
add: Pubby whiteship replaced with a new one.
/:cl:

### CODE REVIEW

**Comment by Striders13** [comment]
also what do I need to change for docking thing to be centered?
изображение

**Comment by Pumpkinoe** [comment]
AWESOME!! I was thinking of doing this - great work! science ship is epic, and I will now affectionately call it the Egg

**Review by Maurukas — APPROVED** [review]
Very nice work.

**Comment by Addust** [comment]
YOU HAVE MY SEAL OF APPROVAL GOOD SIR

**Pull request merged**
