### PR TITLE
Gibber rebalance

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
balance: The kitchen gibber must be anchored in order to use.
balance: The gibber requires bodies to have no external items or
equipment.
/:cl:

Unanchoring the gibber, running around with it, ebowing people, then
shoving them in is not fun.

As a double check, you REALLY should be stripping them of all that
cloth, it'll jam up the gears.

- Removes the abiotic() proc, it's literally used only in the gibber,

### CODE REVIEW

**Comment by Repukan** [comment]
How does this interact with the organic clothes that can't be removed from lings?

**Comment by Bawhoppen** [comment]
Isn't this like already how it works? I know you can't have abiotic items, but what constitutes those is seemingly random anyways.

**Comment by DaxDupont** [comment]
Soft clothing should be fine like jumpsuits and what not.
Honestly, if that thing can grind meat and bones and even separate the skin, a little bit of flimsy clothing isnt gonna do damage.

The anchoring thing i fully agree with.

**Comment by DaxDupont** [comment]
Also make sure you can still push cuffed people in, having to uncuff a ling first is a bade idea.

**Comment by FantasticFwoosh** [comment]
Armblades & otherwise cursed hand items are a external, least you could have theorycrafted this a little bit better prior.

I see you, rolling for changeling mainster.

**Comment by coiax** [comment]
If anyone would bother to read the actual code, you will see that NODROP items are not included in the assessment of equipment, so grind the changeling fake meat clothes away.

**Comment by Rinoka** [comment]
Dax, typically cloth in shreds is harder to rip up with grinders like this and can wrap around motors, so -- even soft fabrics can present a danger. 

I'd be interested in seeing some minor "fuck you" clause if they're wearing fabrics, like "5% chance to have the gibber grind to a halt & need to be opened and clicked on with your hand to fix" but overall I think this is a great PR. Less ebow-gibber play pls.

**Comment by DaxDupont** [comment]
@Rinoka maybe a regular meat grinder, but something that grinds both is more akin to an industrial shredder.
Slightly nsfw:
https://www.youtube.com/watch?v=VSVmuIWI8fI

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
