### PR TITLE
[March into Mapness] Ah, Maintainers, I hope you're prepared for an unforgettable luncheon! Adds the Forgettable Luncheon space ruin

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Title.

### Mapping March

Ckey to receive rewards: Jolly66

## Why It's Good For The Game

We need more ruins, so, here's my contribution to this month. I know I already made a ctf map but that wasn't counted to this, in fact, I opened it RIGHT AROUND the event started.

Anyhow, I want to address that in code regular burgers have a chance to turn into steamed hams (which this ruin adds EXACTLY ONE of). All we're forgetting now is the Aurora Borealis, localized entirely within this codebase.

The ruin it self *does* contain a small handful of food, and other assorted burger goods (and a treasure trove of burgers tucked away in a corner, as a treat). Any spacefairing assistant shall not go hungry wandering!

You can also find the burger dispenser amongst all the burgers.

<details>
<summary> Map </summary>

</details>

`also because steamed hams is still funny`

goodlord

## Changelog

:cl: Jolly
add: Somewhere out in space, someone forgot to have a luncheon with someone.. And the Steamed Hams were burned!
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
Horrific PR, good job

**Comment by ZephyrTFA** [comment]
Me when branch names don't have limits

**Comment by Sealed101** [comment]
but where is the oven

**Comment by HoodMilk** [comment]
Soul-crushing that the burger dispenser module for modsuits can't be found here

**Comment by Jolly-66** [comment]
Maptainers wait I will now add this new revelation I've been told about.

**Comment by EOBGames** [comment]
Alright, here's your reminder of our discord discussion for later: I'll accept the premise of a steamed hams ruin, but the current design here is a bit eh.

The idea I mentioned was making it two shuttles, partially to make it a bit more interesting and partially to get away from "random buildings in space" syndrome.

Also, for the time being, I'll set this on DNM, just while this is sorted out.

**Comment by Iamgoofball** [comment]
@EOBGames why would a fast food joint be a shuttle

**Comment by Timberpoes** [comment]
> @EOBGames why would a fast food joint be a shuttle

Someone didn't watch The Fifth Element.

https://youtube.com/watch?v=WXzSQ6rbzqE

**Comment by Jolly-66** [comment]
I don't have time or drive to map as of current. I'll come back to this later with EOBs feedback, but it won't be apart of the march mappness funny business.

**Pull request closed without merging**
