### PR TITLE
Adds a debug circuitry printer, along with some assorted circuit fixes and tweaks

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Admins may now spawn a debug circuit printer that can always print circuits, and has infinite metal.
fix: Buttons, number pads, and text pads in integrated circuits now correctly show their labels.
fix: Integrated hypo-injectors can now correctly draw blood.
tweak: The circuit analyzer output has been slightly tweaked and includes usage instructions.
/:cl:

What the new debugger interface looks like: 

I added a debug circuit printer for testing changes quickly and so people can mess with circuits on local servers without having to mess with config settings. The fixes are just that - fixes - and the debugger tweak was included because a scientist mentioned during play that they didn't know how to use the code because it never mentions anywhere that it's used in cloning.

I also moved the advanced light's procs to be next to the advanced light subtype instead of included with the normal light, for readability.

### CODE REVIEW

**Comment by arsserpentarium** [comment]
Thanks.

**Comment by LetterN** [comment]
Oh look. A mini infinite power inducer

**Comment by Tlaltecuhtli** [comment]
only 1 power transfer and it probably produces less power than it consumes

**Comment by Xhuis** [comment]
@LetterN To be *completely* fair, that's just my prototype I whipped up in a few minutes. It's really inefficient and seems to uhh, not work half of the time anyways.

**Comment by Xhuis** [comment]
While messing with circuits locally I found a bug that prevented the blood draw feature from working with integrated hypos. I'll commit it when I wake up, but until then if someone is about to merge this please hold off until I push that fix.

**Pull request merged**
