### PR TITLE
Adds some stone tile walkways to the ash walker den, in case of a lava spawn

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: The ash walker den has some new stone tiles and is no longer doomed from spawning in lava.
/:cl:

Closes #29492.

Dream Maker screenshot (old picture [here](http://i.imgur.com/44Cqoyk.jpg), for reference):

I added some stone tiles to serve as walkways in the case of the ruin spawning in a silly location. It's still not structurally sound by any stretch, and if it spawns in lava it's still going to be harder, but with this change ash walkers can at least move around their den.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
hey xhuis please keep your tiles symmetrical

**Comment by Xhuis** [comment]
...?

**Comment by ChangelingRain** [comment]
also, it occurs to me that there's already a path to the room that has the RCD in it

**Comment by ChangelingRain** [comment]
I'll just do it myseeeeeelf tile placement isn't random, there are specific rules

**Comment by Xhuis** [comment]
¯\_(ツ)_/¯

**Comment by Xhuis** [comment]
Closing this in favor if @ChangelingRain's.

**Pull request closed without merging**
