### PR TITLE
Reagent Foam

### LINKED ISSUE #1961: Foam Bugs (functionality and color)
The bug: Foam does not take on the color OR the properties of the reagents placed in a beaker with it.

What I expect: it to function more or less like smoke, only foam.

What's peculiar about this bug is the premade/spawned grenade, such as the janitor's "cleaning grenade" does work, but if you make a cleaner grenade yourself? it'll fail every time and just make regular foam.

### PR DESCRIPTION
**Pull request by Cheridan**
-Separates kinds of effects into their own folders for organization
-Foam can now carry reagents. This includes metal foam. Foam applies TOUCH reactions upon things in range when spread, and also upon process().

I hated how foam worked, it now runs off process() instead of its own sleep() ticker. It's a little slower now as a result but I think being able to make acidbloodflourplasma foam makes up for it.

chemfoam

Fixes #1961

### CODE REVIEW

**Comment by WJohn** [comment]
YES.

**Comment by Incoming5643** [comment]
It's time: https://www.youtube.com/watch?v=PLmD_69pXpk

**Comment by Deantwo** [comment]
Will you fix smoke next?
Cause this sound awesome!

Question: Does the foam change color depending on the reagents it carry?

**Comment by Cheridan** [comment]
Yes, the foam's color is based on the held reagents. The foam in the screenshot was me testing metal foam + colorful reagent.

**Comment by Deantwo** [comment]
I just love metal foam.
Does metal foam also carry other reagents with it?

**Comment by Cheridan** [comment]
Of course

**Comment by Lumipharon** [comment]
Hm? Couldn't foam always carry reagents? I'm sure I've more then once made an acid foam grenade.

**Comment by Cheridan** [comment]
In those situations, the acid would just have been splashing on people and then the foam would wash over them. Unless you're talking about very old code, then possibly. There were code remnants that suggested that reagents were transferred with foam originally, but they were long broken.

**Comment by paprka** [comment]
>acid foam walls that melt people when they try to break them

**Comment by Thunder12345** [comment]
Frost oil foam that slows an entire room down to a crawl

**Comment by Lumipharon** [comment]
Now I'm really confused.

Isn't cleaner nades just Foam Surfactant + space cleaner?

I have made new ones for janitors and they work perfectly fine, suggesting that either
A: that foam already carries reagents
or
B: The foam magically cleans shit regardless of me putting cleaner in it.

With the acid foam, I haven't done that for a very long time, but I remember it because the foam went through an open airlock and melted everything around the corner, which shouldn't be possible from straight acid.

**Comment by Cheridan** [comment]
Cleaner grenades work via space cleaner splashing onto things. The foam is completely extraneous.

**Comment by Incoming5643** [comment]
well it gives a nice visual indicator of the slip zone at least

**Comment by Deantwo** [comment]
Fixes https://github.com/tgstation/-tg-station/issues/1961?

**Comment by Fox-McCloud** [comment]
@Deantwo 

Yup; that's very much correct.

@Cheridan 
Just to double check, it applies when the foam initially touches the mob; what about when the mob moves onto a foam tile--shouldn't that also make it apply? Also, when the foam "bursts" (it clears on a specific tile), shouldn't it also apply to the mob, as well?

**Comment by Cheridan** [comment]
@Fox-McCloud It applies every process(), so I figured applying reagents on Entered() and others would be overkill.

**Comment by Fox-McCloud** [comment]
@Cheridan 

So if you're standing on foam it's going to apply the reagents to the mob every tick? That's pretty crazy. That mechanics is kinda what makes smoke pretty game-breaking with a lot of reagents (acids, etc).

**Comment by Dorsisdwarf** [comment]
Can you make the colors a little muted? That melts my eyeballs.

**Comment by Deantwo** [comment]
@Dorsisdwarf you talking about the *colorful reagent*? Or the color of the foam?

**Comment by Cheridan** [comment]
Yeah, that's just Colorful Reagent. It was just an example of how reagents and their colors are passed along with the foam. Most other reagents aren't colored as brightly.

**Comment by Jordie0608** [comment]
Changelog

**Pull request merged**
