### PR TITLE
[DNM] Makes everything sec and sec related blue to see what happens

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
Does as the title says, recolors the outfits, doors, lockers, decals, so on for sec to a dark blue instead of red, just to see if it changes anything. I'm only doing this because I saw a strange effect in a team vs team series of events on sybil and bagil a few months ago, where no matter who or what was on blue team, they were always less aggressive than red, thus I want to see if that same effect applies here.

image
(very helpful image that shows some of the things changed)

image
(images of more of the outfits)

## Why It's Good For The Game
It probably isn't

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
would make them seem more like police but then command needs to be something else, (i want purple)

**Comment by Mothblocks** [comment]
show what they look like with the blue clothe son

also what do the coats look like i bet theyre cute

**Comment by LemonInTheDark** [comment]
This will end well

**Comment by tralezab** [comment]
I want to try it

**Comment by Paxilmaniac** [comment]
don't tm this anywhere yet, have to fix something first

**Comment by Paxilmaniac** [comment]
ok NOW you can testmerge it somewhere if you want (ping me on discord if you do)

**Comment by SinfulBliss** [comment]
_deep inhale_
AHHHH!!!!!!!!

Unironically though this looks quite nice.

**Comment by Kylerace** [comment]
id like to see this

**Comment by DickTwister2000** [comment]
i like

**Comment by SmArtKar** [comment]
poggers. Also I suggest recoloring orange stripes on doors and lockers to dark blue or something

**Comment by SinfulBliss** [comment]
Keeping the department itself red might make for a nice contrast.

**Comment by Timberpoes** [comment]
This strongly cements the idea that we're just running a big psychological experiment on the players. I support this scientific study.

**Comment by Mothblocks** [comment]
tests like this do not really give meaningful insight unless done over an extreme timespan like a month i just think its cute

**Comment by Sheits** [comment]
> It'd be cool if sechuds/headset were blue too

They are blue.

**Comment by Sheits** [comment]
I do like it, however the contrast on the huds could be hard to read as opposed to the previous sprites because the blue is very dark and desaturated.

**Comment by maxymax13** [comment]
blue is too friendly inviting and peaceful for my skull crushing on curb secret police

**Comment by Livrah** [comment]
Blue huds look like sci / med. 
Take away the toolbox, fireaxe and fire extinguishers, but leave the red sunglasses be.

**Comment by ike709** [comment]
> I'm only doing this because I saw a strange effect in a team vs team series of events on sybil and bagil a few months ago, where no matter who or what was on blue team, they were always less aggressive than red, thus I want to see if that same effect applies here.

https://pubmed.ncbi.nlm.nih.gov/25972401/
https://pubmed.ncbi.nlm.nih.gov/15902246/
https://pubmed.ncbi.nlm.nih.gov/33519586/

Local SS13 coder discovers color psychology, more news at 11

**Comment by Fhaxaris** [comment]
I have no idea why, but I really prefer this desaturated blue color.

**Comment by AlinaStarkova** [comment]
> > I'm only doing this because I saw a strange effect in a team vs team series of events on sybil and bagil a few months ago, where no matter who or what was on blue team, they were always less aggressive than red, thus I want to see if that same effect applies here.
> 
> https://pubmed.ncbi.nlm.nih.gov/25972401/
> https://pubmed.ncbi.nlm.nih.gov/15902246/
> https://pubmed.ncbi.nlm.nih.gov/33519586/
> ...and so on, there's a lot of these.
> 
> Local SS13 coder discovers color psychology, more news at 11

hahaha yeah, red always makes people more aggressive as red is an "aggressive" color. blue is a passive color. its why many games uses green vs orange, both are neutral colors so neither side feels more aggressive. otherwise games with use explicitly defenders vs attackers will color them blue vs red to encourage defence vs attack

**Comment by thestubborn** [comment]
> 
> 
> would make them seem more like police but then command needs to be something else, (i want purple, like a deep purple, with gold trim)

then what does sci get?

**Comment by AlinaStarkova** [comment]
> 
> 
> > would make them seem more like police but then command needs to be something else, (i want purple, like a deep purple, with gold trim)
> 
> then what does sci get?

they are light purple already with no gold trim. its no different from the fact command is deep blue and medbay is light blue no?

**Comment by optimumtact** [comment]
@Twaticus this kind of visual design choice is your wheelhouse im afraid.

**Comment by notfrying1pans** [comment]
image
funny pixel

**Comment by Paxilmaniac** [comment]
> funny pixel

at least its not like the time i left the entire color palette on the locker

**Comment by Paxilmaniac** [comment]
> image
i can't seem to find the rogue pixel? icondiff bot what are you doing?

**Comment by optimumtact** [comment]
Anyway in my opinion this conflicts with command being blue, so you'd have to recolour them first

**Comment by Krysonism** [comment]
People who are inclined to play aggressively do so no matter which uniform they wear. Perhaps the best evidence for this is that the most pathological valid hunting job is paramedic, both a job that wears blue and is themed as a medical job.

To discard the iconic and oppressive red and black look in favour of boring off-brand blue uniforms would be a huge mistake.

We already have so many blue jobs.

**Comment by Paxilmaniac** [comment]
i don't intend on this becoming permanent, i just wanted to see what happens if you do change their colors

**Comment by Mothblocks** [comment]
then u better be prepared to run this for a while

**Comment by Tumesuo** [comment]
just wants to copy the erp servers smh

**Comment by LemonInTheDark** [comment]
> 
> 
> i don't intend on this becoming permanent, i just wanted to see what happens if you do change their colors

we're gonna be testmerging this pr for months if that's what you want to see

**Comment by Paxilmaniac** [comment]
> > i don't intend on this becoming permanent, i just wanted to see what happens if you do change their colors
> 
> we're gonna be testmerging this pr for months if that's what you want to see

then update the tm on the servers its tm'd on, because there's a bunch of shit missing on the current commit they are on

**Comment by Korusho** [comment]
The security door remote, the barrier projector, and the Krav Maga gloves are all still red. Though I am not sure if the Krav Maga gloves NEED to be blue, it clashes significantly now with the blue uniform. Also, I love you for doing this. Finally, the Warden's uniforms look like someone actually gave them some thought.

**Comment by Pumpkinoe** [comment]
This is cool, but three blue departments is kind of a shame and may need to be changed around so that Command and Medical are visually distinct

**Comment by Paxilmaniac** [comment]
> The security door remote, the barrier projector, and the Krav Maga gloves are all still red. Though I am not sure if the Krav Maga gloves NEED to be blue, it clashes significantly now with the blue uniform. Also, I love you for doing this. Finally, the Warden's uniforms look like someone actually gave them some thought.

this is already fixed, someone just needs to update the testmerges

**Comment by NanoCats** [comment]
I actually really like this, who do I have to bribe to make it permanant.

**Comment by Jamarkus127** [comment]
I personally dont think that there will be less aggression, but there will be a boost in teamwork and smarts.

reds a more wild colour, causing people to act without thinking, blue is calmer which may cause people to make thought out plans.

basically, cooperation will rise, and straight rushing will lower.

**Comment by SmArtKar** [comment]
Airlocks, vendors, lockers have too much contrast. Oh, and security channel is now almost unreadable with dark mode

**Comment by NanoCats** [comment]
> Airlocks, vendors, lockers have too much contrast. Oh, and security channel is now almost unreadable with dark mode

Isn't the sec channel still dark red? or am I colorblind, shit.

**Comment by Mothblocks** [comment]
Test merge might not be updated on all server, but it's dark blue now.

**Comment by Mothblocks** [comment]
[quote]
People who are inclined to play aggressively do so no matter which uniform they wear. 
[/quote]

Colors *absolutely* make a real difference in motivation. It won't stop players who want to be aggressive from being aggressive, but it can definitely influence security *in general* to be less aggressive/threatening.

After seeing it in game--I'm super on board with this even if it's just an experiment (though like I said, you won't really get meaningful data without a very long trial period).

**Comment by LemonInTheDark** [comment]
Personally I don't like the concept, but I both haven't played with it, and it's not really up to me

**Comment by Mothblocks** [comment]
it looks so slick

**Comment by NanoCats** [comment]
> > People who are inclined to play aggressively do so no matter which uniform they wear.
> 
> Colors _absolutely_ make a real difference in motivation. It won't stop players who want to be aggressive from being aggressive, but it can definitely influence security _in general_ to be less aggressive/threatening.
> 
> After seeing it in game--I'm super on board with this even if it's just an experiment (though like I said, you won't really get meaningful data without a very long trial period).

See my big question is how do you know if sec is being better because different shirts or what, what's our metric for "better"?

I am not a psychologist

**Comment by NanoCats** [comment]
Also the HOS' icons need to be a new color, since they were always dark blue, and now you can't tell who's the HOS vs and officer at a glance.

**Comment by Mothblocks** [comment]
That's part of why it's really hard to get meaningful data from this. 

There's a few...bespoke metrics you can try, like how often things like handcuffs are used in comparison to gunning people down, but ultimately most of it is just *feel*.

**Comment by Addust** [comment]
bluesec

**Comment by Addust** [comment]
Attention! Security level elevated to blue

**Comment by JohnFulpWillard** [comment]
> 
> 
> Attention! Security level elevated to blue

What if security jumpsuit colors were actually LED lights that changed depending on the alert level?

**Comment by YakumoChen** [comment]
We've had this sort of thing in downstream for months. 

I can say for certain this doesn't make sec any less aggressive, even with much stricter "high RP" rules. 

However blue is a dark color and muddies up the color palette. Everything is less distinct when it's black and dark blue and it's hard to make anything in the department visually interesting when you only have shades of dark blue to work with.

The radio color had to stay red because the blue was unreadable in dark mode and had zero clarity among other radio channels.

HOS is the only distinct role in security (downstream we have 5 different sec jobs) because they use mostly all black themes and everyone else is various dark blue uniforms that have barely any difference with all the dark colors. 

It's really not as good looking as you think

**Comment by Wayland-Smithy** [comment]
> Airlocks, vendors, lockers have too much contrast. Oh, and security channel is now almost unreadable with dark mode

Totally agree. I'm guessing you use lightmode Paxil and didn't check how it looks on dark? Unreadable sec radio color makes me not want to play any roles that needs to listen to sec channel during this testmerge period.

> no matter who or what was on blue team, they were always less aggressive than red

> hahaha yeah, red always makes people more aggressive as red is an "aggressive" color. blue is a passive color. its why many games uses green vs orange, both are neutral colors so neither side feels more aggressive. otherwise games with use explicitly defenders vs attackers will color them blue vs red to encourage defence vs attack

I'm glad other commenters are not sleeping on this, ctrl+f "psycho" has good results. It's no secret that Red is associated with Aggression, Passion, and Danger! Humans bleed red after-all. However I'm not sure the effects will be so pronounced outside of a competition setting like where you mentioned noticing it as the colors of the teams seemed to be the main distinguishing factor with them having equal footing force wise.

I don't think changing the color of their uniforms, doors. and gear when they are still the only department with an armory full of guns and licenses to carry them is going to make a lick of difference in how they play.

Did you know the opposite occurs in LoL according to a study? (sorry mentioned a moba🤮) where the more passive team usually has the mechanical advantage, so it's better to be blue if you want to win.

**Comment by ExcessiveUseOfCobblestone** [comment]
Of all the colors we have to have another shade of blue :waaa:

**Comment by NanoCats** [comment]
> > Attention! Security level elevated to blue
> 
> What if security jumpsuit colors were actually LED lights that changed depending on the alert level?

 > somebody emags a sec officer and they start RGB-ing

**Comment by Naloacisamazing** [comment]
I dont think losing the very visually distinct colours from the default red will be worth it. Making them hard to quickly the difference between a seccie and anyone else in blue is going to be quite annoying I expect. I hope this is a funny meme thing and not for actual gameplay. I doubt the idea floating around of them being less aggressive will actually happen and it would be hard to track anyway

**Comment by AlinaStarkova** [comment]
> 
> 
> > People who are inclined to play aggressively do so no matter which uniform they wear.
> 
> Colors _absolutely_ make a real difference in motivation. It won't stop players who want to be aggressive from being aggressive, but it can definitely influence security _in general_ to be less aggressive/threatening.
> 
> After seeing it in game--I'm super on board with this even if it's just an experiment (though like I said, you won't really get meaningful data without a very long trial period).

also to be fair, red makes them look like villains, so sec wants to act out the villains

**Comment by DAKKA-WAAAGH** [comment]
Green and yellow sec

**Comment by thestubborn** [comment]
> 
> 
> Green and yellow sec

green and PURPLE sec...or med

**Comment by Sheits** [comment]
what if armbands changed colours based on alert level

**Comment by Paxilmaniac** [comment]
why does this have 59 comments you people are literally mental

also i dont need to leave this open any more, done trolling people with bluesec

**Comment by Bawhoppen** [comment]
does this mean we can have red med again

**Comment by oklews** [comment]
Sad to see such a good PR go, the blue really was pretty.

**Comment by Iamgoofball** [comment]
PR's back up.

**Comment by NanoCats** [comment]
I'd like to propose a user poll for this, just for shits and giggles since this is an experiment.

Something like "do you like BlueSec" maybe a couple other relevant questions.

**Comment by LemonInTheDark** [comment]
It's irrelevant unless the art team wants it. Which I don't think they do, unless twat has strong opinions

**Comment by SinfulBliss** [comment]
If Skyrat does it then it's probably workable from a visual perspective, despite the whole thing with med and command being shades of blue.

A vote would be cool. As a sec player I find a big change like this would be really enjoyable for sec simply due to the novelty alone. Also personally I think it looks better, and a bit less antagonistic. I don't think it'd change how sec plays _too_ much, but at the very least it would discourage getting blood all of your clothes since it can't blend in anymore.

**Comment by Bawhoppen** [comment]
I know it's been a few years since the last one, but I think we've all had enough security sprite wars for our lifetimes.

**Pull request closed without merging**
