### PR TITLE
Saline-glucose changes

### PR DESCRIPTION
**Pull request by QualityVan**
:cl: QualityVan
tweak: Saline glucose now acts as temporary blood instead of increasing blood regeneration
/:cl:

Salglu can only provide as much blood as you have otherwise so you can't refill your entire system with it.
Does this count as a refactor or a balance change, anyway?

### CODE REVIEW

**Comment by RandomMarine** [comment]
Halving metabolization rate is a big buff in itself.

But I think it's okay because salglu is garbage at healing anyway.

**Comment by QualityVan** [comment]
Hadn't actually thought about that, it's a decent point. It does increase the healing per volume, but not the healing per time. Bicaridine and kelotane both do about 5 burn/brute respectively per unit right now, with 2 per tick. At changed rates, salglu would do 1.65 burn and brute per unit and .165 brute/burn per tick. Which is a grand total of about five damage a minute per type, so probably not worth worrying about too much.

It does leave the benefit of salglu being a healing chem that a: always works and b: you can't overdose on, which might be something to poke at. Maybe give it an overdose, but I don't know what would fit.

**Comment by Metallusions** [comment]
Rip ashwalker healing

**Comment by QualityVan** [comment]
How's this matter for ashwalkers?

**Comment by Tacolizard** [comment]
rip people with bloodloss when medbay is out of blood

**Comment by Metallusions** [comment]
@QualityVan  Ashwalkers rely on milking their livestock for saline-glucose for healing, as otherwise they only have a single medkit to share.  With all the melee fighting they do with lavaland miners and critters, they suffer blood loss quite frequently.  They need a blood restorer, not a temporary alternative.  Overdose options would suck, but could be monitored if they held onto the health analyzer and watched their portions.

**Comment by QualityVan** [comment]
@tacolizard People don't use saline glucose for blood replacement right now anyways because it's crap, they use iron.

@metallusions Thanks, that's a solid point. Ashwalkers would still have nutriment options available though, both from mushrooms and cooked meat if you choose to butcher goliaths, and nutriment's way better at blood replacement as salglu. Unless you use an IV, in which case I think nutriment's still better or at least comparable. That does leave the issue of potentially getting fat, of course, but I was planning on changing blood regeneration to work off nutrition instead of being increased by nutriment anyway.

**Comment by swindly** [comment]
A medicine's overdose should always be more than its heal.

**Comment by octareenroon91** [comment]
This is terrible. Salglu is currently designed for a slow infusion to refill blood faster than one huge dose.

Iron is already a superior blood restorative at present.

**Comment by QualityVan** [comment]
Not sure I follow, @octareenroon91 . The basis of this is that salglu is a terrible blood restorative right now, so it's changed from restorative to placeholder. This gives it a separate job, stabilization, instead of having it compete with options which are strictly better in all cases.

**Comment by PKPenguin321** [comment]
Not sure why this is being received negatively, it's neat

**Pull request merged**
