### PR TITLE
Removes meth explosion

### PR DESCRIPTION
**Pull request by Iamgoofball**
People just get banned

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Has this actually happened

**Comment by Iamgoofball** [comment]
idk but with today's culture I can forsee someone getting banned for nuking chemistry if they fuck up meth mixing

**Comment by ma44** [comment]
To be fair, the only way this will happen if
1. Someone does it on purpose
2. Near a chemical heater
3. Throwing meth onto a hotspot

It's literally not going to get nuked unless some person decided to cook 100 units of it at once for some reason.

**Comment by KorPhaeron** [comment]
Lets wait until it actually happens

As a bonus, you get to say "I told you so"

**Pull request closed without merging**
