### PR TITLE
Renames station goal modifier

### PR DESCRIPTION
**Pull request by Iamgoofball**
fucked up my "sta"-space-enter speed roundstart and is severely hindering local testing

### CODE REVIEW

**Comment by lzimann** [comment]
you cna always type star  + space

**Comment by PKPenguin321** [comment]
i am confused at the purpose and contents of this PR

**Comment by Iamgoofball** [comment]
@lzimann sta+space is quicker

thats a good idea tho

**Comment by Shadowlight213** [comment]
fix your changelog

**Pull request merged**
