### PR TITLE
Mech Tracking Beacon Balance Change

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

In the recent mech refactor, the Ripley conversion kit was changed so that it can only be applied if the mech's panel is open. Based on comments in the code, the rationale is that the conversion kit is unremovable, so if the mech is being piloted then someone outside the mech should not be able to unilaterally apply the kit:
https://github.com/tgstation/tgstation/blob/a6d77555776e7f92c6263ab806b25967e2a73020/code/modules/vehicles/mecha/equipment/tools/work_tools.dm#L345-L347

But there is another part, the exosuit tracking beacon, that is also unremovable. However, the beacon can be applied instantly no matter whether the panel is open or not. This PR just makes it work like the conversion kits; if the panel isn't open, the beacon cannot be installed.
## Why It's Good For The Game

Being able to run instantly make a mech lose by running up to it and slapping on an unremovable tracking beacon is pretty lame. Being able to do it to a Mauler or Dark Gygax is _extremely_ lame and doesn't even remotely make sense. I also strongly suspect that it is not even intended to be this way, or else the tracking beacon would be built-in, so to speak.
## Changelog
:cl:
balance: The mech tracking beacon now requires the mech panel to be open to be attached.
/:cl:

### CODE REVIEW

**Comment by Striders13** [comment]
that was the case before the refactor

**Comment by GPeckman** [comment]
I guess I can believe that this is intended for crew-available mechs, but is it really intended to work this way on Maulers and Dark Gygaxes?

**Comment by zxaber** [comment]
>it seems that unremovable upgrades/parts/whatever are not intended to be applied unless the panel is opened.

When I made the MK-I and upgrade kit, I coded the kit to replace the MK-I mech object with a MK-II. That's why it's not removable. Since the MK-II loses movement speed, it's reasonable that someone may not want the upgrade, so I made it require maintenance procedures (since that requires pilot access to enable).

The MK-I was added well before the mech refractor. The beacon has always been duct taped to the side, even back then. If you want to change it, sure, but it's not a fix.

**Comment by GPeckman** [comment]
Alright, it is now officially a balance change.

**Comment by githubuser4141** [comment]
Weird why this has so many downboats. In Yogstation or Beestation there's a similiar feature - either you can't put beacons (or any equipment) on a occupied mech - or there's a delay on attaching equipment which cancels if the mech moves.

**Comment by Loafin34** [comment]
i think it's because generally speaking, this is the safest and most reliable way to krill a mech, and having to deal with a 2(?) second do_after and THEN turning it on kinda fucks it over, making ions or mechrowbar the only way to really go toe-to-toe with an armoured mecha

**Comment by GPeckman** [comment]
I'd argue that if security and/or RD doesn't already know about the mech before its completed and combat-ready, then that's kind of their own fault. If they do know about it, and they don't make sure that a tracking beacon gets put on, then that's _also_ their own fault. Building a combat mech is not a quick or easy process; there is a ton of research that needs to be done, and building each part takes time and a lot of metal. Furthermore, anyone with access to a silo-connected machine can easily stop the construction process just by taking out all the iron.

**Comment by zxaber** [comment]
Back when I did mech EMP changes, I had planned to make combat mechs automatically have a tracking beacon. I was convinced otherwise mostly because beacons were easy enough to just slap on. Since we're changing that, I'm fully okay with combat mechs always having a tracking beacon.

**Comment by GPeckman** [comment]
> Back when I did mech EMP changes, I had planned to make combat mechs automatically have a tracking beacon. I was convinced otherwise mostly because beacons were easy enough to just slap on. Since we're changing that, I'm fully okay with combat mechs always having a tracking beacon.

In that case I'll probably just close this PR soon. There's no point in making the panel change if the mechs that matter have one by default.

I am curious though, did you intend for the syndicate mechs to also have a built-in tracking beacon? Because I can't really see any way that would be workable. It would be like if you could lock down nuclear operative cyborgs with the robotics console.

**Comment by githubuser4141** [comment]
> Back when I did mech EMP changes, I had planned to make combat mechs automatically have a tracking beacon. I was convinced otherwise mostly because beacons were easy enough to just slap on. Since we're changing that, I'm fully okay with combat mechs always having a tracking beacon.

Doesn't that kinda invalidate the entire purpose of a _combat_ mech: to do/participate in combat? It's supposed to fight, but fitting it with a beacon roundstart forbids it from doing so, because it's fighting method relies on shooting, or punching the enemy. Which is not possible when the enemy clicks it to death from a console on the other side of the map. If this becomes a thing, mechs will _only_ be feasible against enemies that can't use consoles.

**Pull request closed without merging**
