### PR TITLE
Gives the Centcom Podlauncher back it's old, sexy, chad UI. Also, prevents all tgui tooltips from FUCKING BLOCKING CLICKS REE

### PR DESCRIPTION
**Pull request by MrDoomBringer**
basically it fixes the underlying issue that caused [this abortion of a PR to exist](https://github.com/tgstation/tgstation/pull/41821)

image

## About The Pull Request
improves centcom podlauncher UI by reverting it to the good old state while removing the issues it had with tooltips blocking shit

## Why It's Good For The Game
makes admins happy

## Changelog
:cl: MrDoomBringer
fix: The centcom podlauncher UI no longer looks like shit
fix: Tooltips will no longer stay around if you hover over them (which would lead to them blocking shit underneath)
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Priority: Hyper Critical

**Comment by Borisvanmemes** [comment]
Wheres the goddamned RED LABEL?

**Comment by VileBeggar** [comment]
image
image

**Comment by Tlaltecuhtli** [comment]
haha laggy new ui

**Comment by Potato-Masher** [comment]
Drop pods are the feature that keeps giving.

**Comment by AnturK** [comment]
Fix the conflicts and this is good to go.

**Comment by MrDoomBringer** [comment]
@AnturK you got it fam

**Pull request merged**
