### PR TITLE
No pAIs to mulebots

### PR DESCRIPTION
**Pull request by LatD**
Mulebot murderbone is happening every single round. I hope this gets merged fast and a possible different solution to this can be decided later at #16924

### CODE REVIEW

**Comment by stapler2025** [comment]
MIGHT AS WELL REMOVE IT RATHER THAN FIX IT



H U G B O X

**Comment by LatD** [comment]
This can be nerfed properly later if enough people want to add the pAI option back in later. But while we think about a good nerf this would prevent mulebot murderbone happening every single round until then.

**Comment by stapler2025** [comment]
literally the entire time we've been able to put pAI's in mulebots til now, this hasn't been an issue.

The shitty playerbase is JUST NOW REALIZING what you can do with it.

It's a "new feature" to them so of course it's going to be abused to high heaven.


Don't remove it because a bunch of people are being shit.  If you must make a change, remove pAI ability to run people over and kill them, just make it knock them over.

**Comment by MMMiracles** [comment]
ill have u know i was observing a round last night and i didn't see a single mulebot murderboner. i think you're exaggerating.

**Comment by coiax** [comment]
@LatD It's likely in the longer term PR that I won't be going the full nuclear option, probably just gradual nerfing down until people are no longer so up in arms. If you think the situation is bad enough to warrant a quick ultra-nerf for now, then go ahead, I trust your player judgement.

**Comment by LatD** [comment]
Personally I'd prefer player control to stay but with proper nerfs. Now we've had I think 3 rounds in a row with murdering mulebots and some rounds earlier too. This would just be a temporary solution so admins wouldn't need to manually disable pAIs etc.

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't care about the VROOM VROOM kill machine, but the free stun it gets is pretty OP.

**Comment by Core0verload** [comment]
Any AI can stop mulebot rampage, as well as any sec with an ion rifle and/or a half of a brain. Git gud, or git the fuck out.

**Comment by AdamElTablawy** [comment]
it's still obnoxiously powerful for something that can be gotten within 5 minutes, not to mention an ion gun is a giant clunky gun that's easy for the antag who hacked the mulebots to disarm off the officer for his buddy murderbone bot to kill

tbh just reduce the stun and add a cooldown to running people over so you can't beep beep all over the HoS's ass, because a player controlled 30 to 90 damage weapon is pretty strong

**Comment by LatD** [comment]
Better to leave the balance discussion to #16924

**Comment by FantasticFwoosh** [comment]
Why not just port the current mulebots to badmin and totally castrate the current mulebots to just have heavy collision. Cut the nonsense.

The badmin mulebots could have monster truck wheels and paintjobs.

**Comment by Robustin** [comment]
I'm fine with this getting merged until we can decide what to do with mulebot balance, then bring back pAI control once its done.

**Comment by KazeEspada** [comment]
Mulebots aren't even that fast. Hell, the only issue with attacking one is the fact that meleeing them is hard.

Even a hacked mule can be avoided by a hardsuited atmos tech as long as there is room to move. If one of these is murderboning in maintence, that's much harder.

**Comment by KorPhaeron** [comment]
I warned you all that mulebots would have to get gutted back when pAI control was being added

**Comment by Core0verload** [comment]
The only thing that needs to be get gudded is our playerbase.

**Comment by optimumtact** [comment]
Adding pAI's to mulebots was a mistake, tear it down

**Comment by AdamElTablawy** [comment]
nobody's denying that in a public hallway a mulebot will get memed on

but mulebot is about as memey as ebow esword in maint-you can't really run from it, stop it, or fight it without getting wewladded by 2hit kills

**Comment by LanCartwright** [comment]
Then cut the head off the snake and the body will die.

The whole reason (aside from the complete clown of a playerbase Sybil is) it's even "strong" is because it's a human controlling it, just like blobbernauts.

Remove PAI and you're done.

**Comment by Shapsy** [comment]
Anyone who defends player murder-mulebots has never seen them in action

**Comment by Archie700** [comment]
A pai mulebot piloted by the captain pretty much ran over a gang hideout in one round.

And also some implanted people. At least one died from friendly fire mulebot.

The captain himself later got ran over in an ironic twist of fate while trying to destroy a gang dominator and succumbed.

Pretty much shows how dangerous a pai mulebot is, especially in lowpop rounds where a traitor can get a pai, break into cargo, and terrorise the station with few sec and an AI, if there is one, to stop him.

**Comment by KazeEspada** [comment]
Yes, but PAI mulebots are literally the best delivery buddies you can have.

**Pull request closed without merging**
