### PR TITLE
Add Missing Persons Poster for security to use.

### PR DESCRIPTION
**Pull request by Rockdtben**
## About The Pull Request

image

Allows security to print out Missing Persons Posters to help the crew find their missing pals.
Security Records Console now has a new button 'Print Missing Persons Poster'

## Why It's Good For The Game

This is a neat little feature which is the start of a more diverse set of poster customization.

## Changelog
:cl:
add: Security can now print out Missing Persons Posters
/:cl:

### CODE REVIEW

**Comment by Onule** [comment]
I wouldn't mind these for medical too, sometimes that one chucklefuck on the crew monitor is dead, but doesn't have suit sensors maxed, so placing these around would be nice.

**Comment by Bombpants** [comment]
Can you make missing posters for Ian or the other pets?

**Comment by Tlaltecuhtli** [comment]
yeah you can do wanted too, you have to create/edit a sec record and upload a photo

**Comment by ATH1909** [comment]
> @Onule The plan is to get this PR merged.
> 
> Medical having access to the printed posters for a future version sounds good.
> 
> Later this week or next week I would then modify the library printer to allow for people to create their own Missing posters using photos.

When can we put them on the sides of milk cartons?

**Comment by optimumtact** [comment]
shiz?

**Pull request merged**
