### PR TITLE
Make transit tube dispenser stations buildable

### PR DESCRIPTION
**Pull request by KubeRoot**
## About The Pull Request

Dispenser stations had some sprite issues due to using wrong icon states and having wrong orientation for flipped versions.

This PR fixes the issues and adds them to the RPD.
I can remove them from RPD construction if you don't want them to be constructible - this was the main motivation for implementing the changes in a downstream.

## Why It's Good For The Game

Bugfixes are good: unanchored dispenser stations now have the correct sprite, terminus dispenser stations render correctly in general.

## Changelog
:cl:
add: Transit tube dispenser stations are now buildable via RPD
fix: Transit tube dispenser station sprite errors have been fixed. The sprites themselves have not been changed, but the names and orientation has been corrected.
/:cl:

### CODE REVIEW

**Comment by Greniza** [comment]
right-facing dispenser tube has a single white pixel during one frame of its animation

literally completely unmergable

**Comment by KubeRoot** [comment]
> left-facing dispenser tube has a single white pixel during one frame of its animation
> 
> literally completely unmergable

Crap... Dream Maker was spazzing out on me, good catch, hopefully fixed

**Comment by Greniza** [comment]
Are there two? Check again, although this one looks like it could be the head of an antenna? This one was carried over from the last one, so I don't blame you, but still. Dream Maker does this sometimes.
image

**Comment by Twaticus** [comment]
the white flashing pixel is an icondiffbot issue with animated icons. the sprite itself has no rogue pixel

**Comment by KubeRoot** [comment]
> the white flashing pixel is an icondiffbot issue with animated icons. the sprite itself has no rogue pixel

I have confirmed the first time the sprite had a rogue pixel, it wasn't even supposed to be modified, will check the second one

**Review by Twaticus — APPROVED** [review]
already did 😎

**Pull request merged**
