### PR TITLE
Alien closets now correctly cost two alloy to make (Fixes #28561)

### LINKED ISSUE #28561: Alien lockers have alien properties
Step 1. Get alien alloy
Step 2. Build alien locker
Step 3.Weld down alien locker
Step 4. Receive more alloy than what you used to build locker

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: Alien lockers now correctly cost two alloy to build, instead of one.
/:cl:

Fixes #28561.

### CODE REVIEW

**Comment by Xhuis** [comment]
Woah, speedmerge? Ah well, I'm not a maintainer here.

**Comment by KorPhaeron** [comment]
Scared?

**Comment by Xhuis** [comment]
Uh, I guess???

**Comment by Jordie0608** [comment]
Kor works in mysterious ways.

**Pull request merged**
