### PR TITLE
[no gbp] Sparks don't ignite furniture (unless you made it out of plasma you fucking lunatic), sparks have a decreasing chance to ignite bigger items, small fix to obj/fire_act() signal

### PR DESCRIPTION
**Pull request by Metekillot**
## About The Pull Request

Even though it's hilarious, sparks currently ignite any flammable thing they touch whatsoever; including gigantic wooden/cloth items, or tables and chairs. Turning areas with wooden furnitures into fields of ash wasn't the intent, so I adjusted sparks to not ignite furniture (you can put welding fuel under them if that's your intent) and items bigger than small items have a steadily decreasing chance to get ignited by sparks (normal is 50%, bulky is 20%, bigger than bulky won't ignite only from sparks)
## Why It's Good For The Game

Even in a death trap space station of the future, sparks aren't THAT much of a fire hazard.
## Changelog
:cl:
fix: Sparks will no longer turn areas with wooden furniture or similar into naught but a field of ashes; they no longer ignite furniture, (unless it's made of plasma(?!)) and have a decreasing chance to ignite items bigger than small size.
/:cl:

### CODE REVIEW

**Comment by Justice12354** [comment]
Was clothing also intended to be affected by this?

**Comment by Metekillot** [comment]
> Was clothing also intended to be affected by this?

Yep! However, I hadn't intended it to be quite so pronounced on turning everything into piles of ash. I just did a rework of the logic to make it quite a bit more reasonable.

**Comment by Metekillot** [comment]
Code is tested now

**Comment by dalmationer** [comment]
When you have the chance, I'd recommend checking out the chef's express order console-- at present, because the food doesn't arrive in a crate, it instantly ignites as soon as the pod lands due to the sparks, so the chef has to keep an extinguisher on them to use it.

**Comment by Metekillot** [comment]
> When you have the chance, I'd recommend checking out the chef's express order console-- at present, because the food doesn't arrive in a crate, it instantly ignites as soon as the pod lands due to the sparks, so the chef has to keep an extinguisher on them to use it.

Mental image of extinguishing the box your supplies came in as part of a bored routine resulting from corporate negligence is very funny

**Comment by AdipemDragon** [comment]
it's also Kind Of Very Much Affecting items dropped in a pod, since the pod Will Spark And Ignite Its Cargo when you don't pick it up, Hopefully this helps

**Comment by Metekillot** [comment]
> it's also Kind Of Very Much Affecting items dropped in a pod, since the pod Will Spark And Ignite Its Cargo when you don't pick it up, Hopefully this helps

Yep

**Pull request merged**
