### PR TITLE
Plating, lattices, and catwalks on mine turfs

### PR DESCRIPTION
**Pull request by ghost**
kek

Now miners have even more of a reason to not come back to the station.
- Allows building of catwalks, lattices, and plating on asteroid turfs for cave forts or dwarf fortress expansions
- Adds a small do_after for placing catwalks on space turfs and asteroid turfs, so that breach repairs don't end up in wasted rods

Idea originally by @d3athrow at /vg/, who I'm under obligation to say is the best idea guy/coder

### CODE REVIEW

**Comment by WJohn** [comment]
I actually quite like the catwalks on asteroid turfs. Looks pretty good there.

**Comment by paprka** [comment]
Lattices smooth with any turf that is not space, so those are gonna look like they do, kinda cut off, but whatever.

The sandstone plating pseudo turfs are the worst offender of asteroid mapping and they need to be fixed I think.

**Comment by Razharas** [comment]
Make them smooth only if the turf they are smoothing to either have lattice on it too or is of different type(icon?) than the current turf lattice

**Comment by Niknakflak** [comment]
So much for the ban.

**Comment by paprka** [comment]
@Razharas that seems awfully expensive

**Comment by dannno** [comment]
>paprika is still making objectively good PRs
>complaining about it

haha why though

**Comment by Steelpoint** [comment]
Cause it defeats the point of a ban if one continues to act as if one does not exist.

**Comment by dannno** [comment]
they're permabanned from the server
the forums
the irc
and they're still making these objectively good PRs even though they really don't have to

i am not going to complain.

**Comment by paprka** [comment]
I put a lot of time into this game, I had these ideas in my head for a while, I'd rather improve the game if I end up playing on a downstream or something.

I wouldn't want to leave you with half finished features like iamgoofball :^)

**Comment by mikecari** [comment]
Paprika you're the hero /tg/ deserves...;_;
I will always love you.

**Comment by paprka** [comment]
Good job sticking up for me in the ban request thread while people constantly attacked my character homie I really appreciate it.

**Comment by Jalleo** [comment]
Paprika I do suggest that you stay like this for a while the reason you were banned is objectively right due to the fact of how out of control you were. If you stay on this level of sensibility you probably would be allowed back but how you were acting was not suitable for most people.
This PR is a good one if you do stay around I suggest you look into remies map generator once its merged would be awesome for mining.

**Comment by paprka** [comment]
all it takes is one grey tide sign and i go back into the episodes, jalleo

visions of short hair 1 Caucasian 1 assistants flooding down the hallways, tabling innocent security borgs, and stripping the HoP

i can't guarantee this won't happen again

**Comment by Jalleo** [comment]
You did not pick your fights correctly and used up all your arguments on everyone you do need to think back on everything that has gone wrong peoplegot rid of you only due to the fact that you were hostile at everyone  one point or another. If this helps you to learn control thats good if not then so be it. You are currently on a request for removal as i know of but github is slow. A apology wont do it for most people you will have to change your act its more than one sign and a laugh at someones act. You are good at doing changes and fixing them but so far your social skills have been a flaw that lead to this.

I can talk more later on a IRC if you want to but i am busy atm.

There is no cant anymore either change or no change from this situation.

**Comment by paprka** [comment]
don't you see why i'm so angry about all this

i shouldn't have to pick any fights

there shouldn't be any fights around my changes or other people's changes, we shouldn't have to engage in forum battles over changes and if you seriously believe i initiated all of those you haven't really been paying attention

**Comment by Jalleo** [comment]
I was not saying you initiated all of the fights and there are good points to what you are saying i am able to talk in probably 40-1h from now on irc ( even the mainly disused buses ). Any more talk on this PR needs to be on topic now so it dosent get more off topic as paprika said.

**Comment by Dorsisdwarf** [comment]
:-1:  unless you find a workaround for lattices. Or just cut them entirely and let you build plating directly onto the 'roid (which makes more sense anyway)

**Comment by Jordie0608** [comment]
http://keepachangelog.com/

**Comment by Razharas** [comment]
Im pretty sure changelog will never happen

**Comment by Dorsisdwarf** [comment]
Does anyone want to take this up?
I think this is neat enough that I'd be happy to changelog and maybe address some of the issues with it in my own PR. If anyone has contacts for paprika it would be handy so I can get a personal authorisation to fuck off from him.

**Comment by Miauw62** [comment]
this causes too many issues to merge in it's current state. if anybody wishes to take it up, feel free.

**Comment by Cheridan** [comment]
@Dorsisdwarf it's fine if you want to take over. I'll close this, then, and wait for your PR.

**Pull request closed without merging**
