### PR TITLE
Syndicate temperature gun. Now without cardinal git sin of making a pull request of master.

### PR DESCRIPTION
**Pull request by ghost**
Adds Syndicate temperature gun. Uplink item for 14 tc. Works in two modes: bake and freeze. In freeze mode each beam decreases temperature of target. Also in slow mode slows target. In bake mode each beam increases temperature of target. Also in bake mode if target temperature is high enough, then sets target on fire. Has completed sprites (beams, sprites of weapon and in hand sprites). Auto recharges itself over time.
It is not boring and generic because:
It has interesting mechanics.
It is really different from original temperature gun. (It adds fixed value to temperature of target, instead of setting temperature of target to fixed value)
Created as weapon for long fights, for idea then traitor needs to escape alone or assassinate HoS.

### CODE REVIEW

**Comment by Ninja137** [comment]
But is it available to normal traitors? Because normal traitors could REALLY use some love here, man. Also, unless that shit just fucking wrecks people, it probably needs a cost decrease. It's sitting up there with the rape-everything SMGs and the Revolver, which can kill in seconds.

**Comment by HunterMaksim** [comment]
It is available to normal traitors.

**Comment by Ninja137** [comment]
How does it compare to the Stechkin/Revolver/E-bow, then? Because the stetchkin can be silenced and kills in about one mag, the revolver crits/kills in ~2-4 shots, and the E-bow stuns and lets you murder people with melee. At 14 TCs, does it merit the cost?

**Comment by HunterMaksim** [comment]
It has 8 shots. One shot does ~40-50 burn damage over time. Shooting additional shoots at the target does quit less damage. Somethin like ~4 freeze shots should be enough to kill target. In freeze mode it also slows target. In heat mode it usually ignites target. Also it recharges itself over time.

**Comment by Ninja137** [comment]
It doesn't have that god-awful activate-in-hand-to-reload thing from the Ebow, right?

**Comment by HunterMaksim** [comment]
Right.

**Comment by Ninja137** [comment]
Sounds neat, then. Once shit gets merged I'll post feedback.

**Comment by HunterMaksim** [comment]
Fixed new version has been made

**Pull request closed without merging**
