### PR TITLE
Ports BeeStation Cloak sprites by Naevii!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin:
image

Credits to Naevii for making the sprites!

## Why It's Good For The Game
They look much, MUCH better than all the cloaks we currently have!

## Changelog

:cl: PositiveEntropy, Naevii
imageadd: Ports BeeStation cloak designs!
/:cl:

### CODE REVIEW

**Comment by KittyNoodle** [comment]
I don’t like how asymmetrical the captain’s cloak looks like compared to the other coats

**Comment by CRITAWAKETS** [comment]
CE cloak and RD cloak reeealllly recieved a regression in color schemes

**Comment by Livrah** [comment]
I like /tg/ CE cloak more (and hate RD's one).
Overall, this ones way better.

**Comment by MrDoomBringer** [comment]
the asymmetrical tassel on the captain's cloak is fantastic, keep it

**Comment by Krysonism** [comment]
> 
> 
> I don’t like how asymmetrical the captain’s cloak looks like compared to the other coats

Yeah, RD and CE players please leave feedback what you think.

**Comment by Imaginos16** [comment]
I wouldn't mind swapping the colors of the RD one to see what people think. I personally think the CE one is a MASSIVE upgrade however, especially if you take into consideration the modsuit design for the CE suit.

image

**Comment by RuneQuester** [comment]
The CE and RD cloaks have gotten a massive upgrade, and so have all the other cloaks. There is absolutely zero reason to not merge this INSTANTLY

**Comment by TheBonded** [comment]
Why not add something similar to det's revolver and the bartender's shotgun that allows you to change the sprite by alt clicking, where you could alt click the cloak to swap between the two sprites. Then there could be alternate styles, like how heads of staff have alternate uniform styles.

**Comment by CRITAWAKETS** [comment]
> image

Needs a tad more contrast. Especially in the lower pixel resolutions that people play at like 2x. Without the contrast its just gonna end up looking like a blob of random clothing.

**Comment by Fikou** [comment]
they r all good but not sure about if rd is an improvement

**Comment by redsunoverparadise** [comment]
Holy shit that sec cloak looks hot

**Comment by Coastfront** [comment]
Honestly  @TheBonded 's det revolver sprite idea seems pretty good, making it so that you can actually pick which coat sprite you want bee's or standard. Since i gotta be honest some of these feel like downgrades.

**Comment by tralezab** [comment]
all of them are way better imo including rd

**Comment by MrMelbert** [comment]
HoP's cloak is gonna look out of place 🥺

**Comment by Acer202** [comment]
My only complaint is the color palette of the new CE cloak. The black, blue, and orange of the old cloak is so iconic to me. Maybe make a spare cloak in the locker for those old-timer CEs, heh.

**Comment by necromanceranne** [comment]
I prefered the old RD colour scheme myself. The RD kinda looks like they stepped out of Saints Row with such a heavy purple. The others are balling.

**Comment by bluezorua** [comment]
the CE cloak was meant to be paired with the bee ce hardsuit, if you are going to do this I reccomend porting that too

**Comment by Imaginos16** [comment]
> the CE cloak was meant to be paired with the bee ce hardsuit, if you are going to do this I reccomend porting that too

It will as per Modsuits. Do not worry

**Comment by Naevii** [comment]
Hello! Let me adress some stuff behind my thought process as a creator. Those cloaks were specifically made for bee to fit our pallette, our old cloaks were absolutely tragic especially if you took a look at them upclose.

Additionally.  Hop cloak didn't receive respite because what we had currently had a good standard and didn't warrant a replacement. And I am against unnecessary changes when it's possible.

**Comment by Imaginos16** [comment]
> Hello! Let me adress some stuff behind my thought process as a creator. Those cloaks were specifically made for bee to fit our pallette, our old cloaks were absolutely tragic especially if you took a look at them upclose.
> 
> Additionally. Hop cloak didn't receive respite because what we had currently had a good standard and didn't warrant a replacement. And I am against unnecessary changes when it's possible.

Hey there! Good work with the sprites by the way, they're lovely. I've messed around with them for a while now, and after running them for a round in /tg/ while running the modsuit testmerge, I thought it was enough of an upgrade to warrant an actual PR here! Personally I feel it fits extremely well with them, especially the CE cloak with the suit!

**Comment by Naevii** [comment]
> > Hello! Let me adress some stuff behind my thought process as a creator. Those cloaks were specifically made for bee to fit our pallette, our old cloaks were absolutely tragic especially if you took a look at them upclose.
> > Additionally. Hop cloak didn't receive respite because what we had currently had a good standard and didn't warrant a replacement. And I am against unnecessary changes when it's possible.
> 
> Hey there! Good work with the sprites by the way, they're lovely. I've messed around with them for a while now, and after running them for a round in /tg/ while running the modsuit testmerge, I thought it was enough of an upgrade to warrant an actual PR here! Personally I feel it fits extremely well with them, especially the CE cloak with the suit!

Thank you so much! Glad they are liked :)

**Comment by Farquaar** [comment]
No HoP cloak?

**Comment by MrDoomBringer** [comment]
image
the never ending story

**Comment by axietheaxolotl** [comment]
Very sexy, very epic. I was gonna do this myself at one point because we already had them on SR, and I wanted them on base /tg/, but I was beaten to the punch. :V

**Pull request merged**
