### PR TITLE
Desouls Hivelord

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

dreammaker_RJz4brjobM

Replaces the sprite of the hivelord with a new one, in my continuing quest to annihilate the old asteroid mob sprites.
A (never completed) asteroid mob resprite was actually my first PR, this one is my 200th.
I am also planning on fucking with basic mob versions of these mobs some time but the sprites can be atomised out.

In addition to replacing the old-ass MSPaint sprites, this PR also adds a short death animation effect to the hivelord brood (from hivelords or legions) which looks nicer than them just vanishing instantly upon death.

Look at this video for an example of the animation:
https://www.youtube.com/watch?v=cKaskN5-y2A

## Why It's Good For The Game

Looks nicer.

## Changelog

:cl:
image: Hivelords have a new sprite.
image: Hivelord and Legion brood have a death animation.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
icondiffbot get your shit together

**Comment by CCC23** [comment]
:( soul....

**Comment by Serxule** [comment]
ehhh they're too bright, thats really the only thing i find off about them, they are garishly pink-purple and weird looking, not that the old ones were good (afaik a solid dark-blue)

**Comment by Likteer** [comment]
Side-by-side for lazy people:
obraz
I liked old hivebot basically being this fucked up indian weapon, 
animated & made angry by unknown forces.
But this is DEFINITELY some high quality worms right there.
obraz

**Comment by mc-oofert** [comment]
the worms look like stone and even then i dont think thats fitting for something surviving in the vacuum of space

**Review by Wallemations — APPROVED** [review]
icondiff shit the bed but I opened the file manually and it all looked great, good work.

**Pull request merged**
