### PR TITLE
resprites salt and pepper shakers

### PR DESCRIPTION
**Pull request by CoiledLamb**
## About The Pull Request
Resprites the empty, salt, and pepper shakers to have a more modern sprite.  you can see the comparison below.
saltnpepperbeforenafter2
and in game screenshot here.
Screenshot (2630)
## Why It's Good For The Game

Salt and pepper are a staple in every kitchen, so why not make 'em look a bit nicer?

## Changelog

:cl:

imageadd: added new salt, pepper, and empty shaker sprites. 

/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
The sprites look good but I kind of don't like how fact they're bigger than the old sprites. I feel like there's been a lot of scale creep with respect to sprites recently.

**Comment by CoiledLamb** [comment]
i don't think scale creep is a huge problem here. the additional pixel of height gives them a nicer silhouette in my eyes, and better readability, so i don't think there's really any reason to hold on to the scale of the old shakers past what i already have.

someone else requested in discord suggested i make them 3/4ths, so i wanna preemptively say here i don't think that's a good idea due to the actual scale creep that would cause. if someone else wants to sprite it that's fine, but i'm satisfied with these, past some tweaks to the empty one i'm working on presently (to make the base more readable)

**Comment by zxaber** [comment]
Actual salt PR

**Comment by Imaginos16** [comment]
A subtle, but welcome change.

**Pull request merged**
