### PR TITLE
Cerestation Tweaks MKV

### PR DESCRIPTION
**Pull request by MMMiracles**
- Fixes cargo disposal section with backwards piping
- Armory now has mindshields, chem, and tracking implants, along with a contraband locker. 
- Added a missing recharger to science's security checkpoint.
- Added missing wiring in cargo asteroid.
- Pushed cargo stamps to top of pile in office to make more obvious. 
- Prison Transfer was moved to the side of the brig and an interrogation room was added where it used to be.
- CE's office has a secondary door in his office that goes directly into Atmospherics so they can quickly move between the engine room and atmos. 
- Every departmental office now has lockdown shutters for their windows, either for privacy or when their underlings decide to start a revolution and want their head on a stick.
- Bridges were redone to be more easily maintained if vandalized/blown up while still keeping roughly the same amount of structural security.

### CODE REVIEW

**Comment by ChemicalRascal** [comment]
Needs to be removed tho.

**Comment by MMMiracles** [comment]
ill remove u in a minute if u keep this up BUCKAROO

**Comment by ChemicalRascal** [comment]
AW SHIT

**Comment by Iatots** [comment]
You did add at least a second pair of insulated gloves for engies this time right?

**Comment by MMMiracles** [comment]
@Iatots spare gloves were added in last patch.

Redid the bridges in a fashion similar to @FantasticFwoosh 's design on the feedback thread, along with some other office-related stuff.

**Comment by GunHog** [comment]
These bridges do not look very nice through a camera view:
image

As you can see, the walls are creating blind spots. You may not care about this, but it does hurt the aesthetic. 

Minor nitpick: The new shutters you have added have buttons named "emergency lockdown", although "privacy shutters" are more appropriate here, because they are shutters and not blast doors.

By the way, the RD's office is missing privacy shutters and the button which is meant to control them instead control the department's blast doors.

**Comment by MMMiracles** [comment]
The shutter button for the RD is under the science lockdown button in their office.

As for the camera view, there really isn't much I can do. Not being able to re-install cameras in the hall is a genuine issue and that's the only real solution.

**Comment by GunHog** [comment]
The shutter button is there, but instead controls the blast doors, you probably forgot to change it when you copied it. 

Putting cameras on the other side of the wall may be a solution. The map feels to have rather poor coverage due to how the map is laid out. I was hoping there could be something done to make it not feel so unfinished in this case.

**Comment by MMMiracles** [comment]
The issue with that is it just adds unneccesary clutter to the camera lists for anyone who wants to use the camera consoles in security. It obviously isn't as much of an issue for the AI as they rarely have to touch this menu, but it'd be hell for people like the Warden who might actually try to watch over the station.

**Comment by Bawhoppen** [comment]
i liked the old bridges don't change them

**Pull request merged**
