### PR TITLE
Probably a bad fix for suicidal simple animals

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Stops simple animals for suiciding down chasms.

Maybe too hacky to be acceptable but I'm not sure how else to do it.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
try [here ](https://github.com/tgstation/tgstation/blob/012eaec1b98b29f4e2f237ccbebcc95be2d08e43/code/modules/mob/living/simple_animal/simple_animal.dm#L139)

**Comment by KorPhaeron** [comment]
Thanks that was the secret goal of this PR

**Comment by KorPhaeron** [comment]
@ExcessiveUseOfCobblestone 

You tricked me thats just for the mob wandering in circles, not path finding to attack people

**Comment by ExcessiveUseOfCobblestone** [comment]
oh hmmmm

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/012eaec1b98b29f4e2f237ccbebcc95be2d08e43/code/modules/mob/living/simple_animal/hostile/hostile.dm#L223

**Comment by Kromgar** [comment]
Don't nerf my sick strats to make goliaths kill themselves.

Would be nice though if you meet a nice combo of legion and goliath and happen to die and your corpse wanders into a chasm

**Comment by RemieRichards** [comment]
@ExcessiveUseOfCobblestone ```MoveToTarget()``` is not what you want to edit, the actual pathfinding is done by DM itself, it can ONLY be "fixed" the way Kor already has. I asked for pathfinding to have a new variable so we didn't have to hack density like this, but lummox said no.

**Comment by coiax** [comment]
@RemieRichards how much more expensive would it be to do the pathfinding ourselves?

**Comment by duncathan** [comment]
@KorPhaeron add a comment explaining the hack for clarity and it should be ok

**Pull request merged**
