### PR TITLE
Adds support for ammunition 'bands' and differentiates between detective speedloaders.

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Adds support for ammunition 'bands', basically intended to be used rather than wholly new sprites for new ammotypes. Additionally, they're (meant to be) greyscale, which allows one overlay to be used for many ammo types. Only implemented on the detective revolver.

From left to right

Default
Tracking (Purple)
Match (Silvery Blue)
Rubber (Blue)
DumDum (Yellow)
Hotshot (Red)
Iceblox (Light Blue)

image

These sprites are damn bad, as I'm not a spriter. I would appreciate it if someone could improve them.

I am also not attached to the specific colors, any alternatives would be appreciated.
## Why It's Good For The Game

Tired of all speedloaders being identical.
## Changelog
:cl:
code: Adds support for ammunition 'bands', basically intended to be used rather than wholly new sprites for new ammotypes. Additionally, they're (meant to be) greyscale, which allows one overlay to be used for many ammo types. Only implemented on the detective revolver.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
I think the sprites would be passable if I made the colors darkened - that way it would just look like 'dark red' for hotshot, 'dark blue' for iceblox, etc. The ammo band won't be as garish then.

**Comment by Helg2** [comment]
Maybe make look differently not the speedloaders but the bullets? Like with shotgun shells

**Comment by carlarctg** [comment]
> Maybe make look differently not the speedloaders but the bullets? Like with shotgun shells

Nah, that'd be even more annoying, because 1. The bullets are more complicated than the speedloader frame and 2. They're hardsprited so I'd have to change six states which is a pain.

**Comment by carlarctg** [comment]
gwuh

**Pull request merged**
