### PR TITLE
Add randomized lawsets to AI upload

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This removes all the current boards and lawsets in the AI upload for all maps and replaces them with:

- x1 reset board on the regular table
- x1 asimov lawset on the regular table
<details>
<summary>x3 randomized harmless lawsets (marked green, no barriers, human-friendly lawset)</summary>

```dm
/obj/item/ai_module/core/full/asimovpp,
/obj/item/ai_module/core/full/hippocratic,
/obj/item/ai_module/core/full/paladin_devotion,
/obj/item/ai_module/core/full/paladin,
/obj/item/ai_module/core/full/drone,
/obj/item/ai_module/core/full/custom, // uses lawsets from config/silicon_laws.txt (defaults to asmiov if no lawsets)
/obj/item/ai_module/supplied/freeform,
```

</details>

<details>
<summary>x3 randomized neutral lawsets (marked blue, windoor barrier, station-friendly lawset)</summary>

```dm
/obj/item/ai_module/core/full/corp,
/obj/item/ai_module/core/full/maintain,
/obj/item/ai_module/core/full/peacekeeper,
/obj/item/ai_module/core/full/reporter,
/obj/item/ai_module/core/full/robocop,
/obj/item/ai_module/core/full/liveandletlive,
/obj/item/ai_module/core/full/hulkamania,
/obj/item/ai_module/supplied/safeguard,
/obj/item/ai_module/supplied/protect_station,
/obj/item/ai_module/supplied/quarantine,
/obj/item/ai_module/remove,
```

</details>

<details>
<summary>x3 randomized harmful lawsets (marked red, brigdoor barrier, antag-friendly lawset)</summary>

```dm
/obj/item/ai_module/core/full/antimov,
/obj/item/ai_module/core/full/balance,
/obj/item/ai_module/core/full/tyrant,
/obj/item/ai_module/core/full/thermurderdynamic,
/obj/item/ai_module/core/full/damaged,
/obj/item/ai_module/reset/purge,
/obj/item/ai_module/zeroth/onehuman,
/obj/item/ai_module/supplied/oxygen,
/obj/item/ai_module/core/freeformcore,
```

</details>

Additionally, I reorganized the AI lawset code and removed an old malfunction lawset code that existed since r4407 but wasn't used anywhere.

---

### Pictures

<details>
<summary>Icebox</summary>

StrongDMM_CBOmNMtsqT

</details>

<details>
<summary>Delta</summary>

StrongDMM_dfTP8lAF0s

</details>

<details>
<summary>Tram</summary>

StrongDMM_gEbWi9UcZN

</details>

<details>
<summary>Meta</summary>

StrongDMM_qy1T2PTDbh

</details>

<details>
<summary>Kilo</summary>

StrongDMM_yzTUPZUyEa

</details>

## Why It's Good For The Game

The same set of lawsets always spawned in the upload every round.  This preference was largely dependent on the mappers taste and the available lawsets when the map was made.  Now all maps pick from the same pool of lawsets randomly.  This means maintaining the AI upload for maps is now easier if new lawsets get added or removed.  

Niche lawsets that were either available only on selective maps or printable from R&D saw little use due to their rarity.  My randomization changes allows them to be more common.  Some of the more OP lawsets are not always guaranteed to spawn and players may be forced to use an alternative.  Seeing the one-human lawset get spammed every round is boring. 
 This should lead to more interesting RP situations when it comes to AIs.  

## Changelog

:cl:
qol: Change AI upload lawsets to be randomized
code: Reorganize AI lawset code and remove deprecated malfunction code
/:cl:

### CODE REVIEW

**Comment by Likteer** [comment]
That **is** impressive, but I'd think some people (me perhaps?) will like if there was a _Why it's good for the game_ section besides the screenshots.

**Comment by timothymtorres** [comment]
> That **is** impressive, but I'd think some people (me perhaps?) will like if there was a _Why it's good for the game_ section besides the screenshots.

Fair comment.  I updated the original post to be more robust.

**Comment by SmArtKar** [comment]
It's not QoL, it's an addition or balance

**Comment by newfren** [comment]
No purge board is a bummer for fixing ais with bad laws or making new custom lawsets.

**Comment by nianjiilical** [comment]
> No purge board is a bummer for fixing ais with bad laws or making new custom lawsets.

i think it'd definitely be fun and make ai law changes more interesting to not have purge/freeform available every round but it might be worth giving them their own individual chance of spawning (50%?) each round just because of how much more important they are to ai gimmicks and unfucking laws

**Comment by timothymtorres** [comment]
Guys you don't need a purge board to fix a broken AI.  The reset module removes any ion, hacked, or non-core lawsets.  Then asimov can be used to remove all remaining core lawsets.  Both of these are guaranteed to spawn in every upload.

Also many lawsets can be printed from R&D if they don't spawn in the upload.

**Comment by newfren** [comment]
I'm pretty certain the reset board doesn't remove hacked laws?

**Comment by timothymtorres** [comment]
> I'm pretty certain the reset board doesn't remove hacked laws?

https://github.com/tgstation/tgstation/blob/5ae7a5d8614a9bb30e168b90a19d5c414f0f7471/code/game/objects/items/AI_modules.dm#L308-L325

**Comment by newfren** [comment]
these fuckers on discord lied to me

**Review by san7890 — APPROVED** [review]
Looks good. Shuffles around some code and add spawners (map-centric), but doesn't really add anything new so we're fine there.

**Pull request merged**
