### PR TITLE
Redpills the brig infirmary

### PR DESCRIPTION
**Pull request by pudl**
:cl:
rscadd: The brig infirmary has received a redesign.
/:cl:

I am gobsmacked at the condition steelpoints brig infirmary was merged in. This pr fixes it. Theres also a small change to the evidence room

Before

After

- Adds a second bed to the brig infirmary. There were originally two in security but steelpoints pr removed the asylum resulting in only one remaining. No bedsheets because this is security not sleepy time land
- Removes a superfluous table dedicated to a lone medkit and moves said medkit to the table with the other one
- Removes another superfluous table dedicated to a completely pointless paper bin and pen. The iv stand that used to be on top of the bed is moved there and given an empty blood pack so security can actually like i dont know use it
- Another table has been added with a medical laptop a la metastation
- The metal tables are now glass
- The two small light bulbs have been exchanged for one large one
- The windoors have been renamed from "Infirmary" to "Brig Infirmary"
- The dedicated air pump and alarm have been removed
- The misplaced floor tiles have been fixed
- The horrible decorative border window by the morgues has been removed
- The intercom has been shifted from y26 to y24 like every other intercom
- A camera has been added with the c_tag Brig Infirmary
- The evidence room is no longer colorless

### CODE REVIEW

**Comment by WJohn** [comment]
The feature freeze is deeeaaad.

**Comment by optimumtact** [comment]
map edits are nto included in the freeze for some reason

**Comment by Cheridan** [comment]
Wow, this is really nice. Good work, pudl.
@Steelpoint should take some notes

**Comment by PKPenguin321** [comment]
before/after pic please

**Comment by pudl** [comment]
@PKPenguin321 SIGH OK WAIT

**Comment by pudl** [comment]
What

**Comment by Steelpoint** [comment]
Its pretty usual for other people to improve on changes I've made.

**Comment by Armhulen** [comment]
HE REMOVED THE ASYLUM??
WHERE WILL I PUT THE CRAZYS???

**Comment by pudl** [comment]
Remove the merge conflict tag

**Pull request merged**
