### PR TITLE
You can no longer pick up cogscarabs

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: You can no longer pick up cogscarabs.
/:cl:

I never thought I'd be doing this as a balance thing but hey it turns out if you pick up a cogscarab and put it in your bag, it can leap out anytime to attack anyone near you. Taking this to the logical conclusion, one man with five scarabs in his bag, rushing at one soon to be very unfortunate security officer.

### CODE REVIEW

**Comment by Kraseo** [comment]
MY ZERG RUSH

NO

**NO**

**Comment by ChangelingRain** [comment]
I'm very sorry but this is too silly of a tactic to live

**Comment by Supermichael777** [comment]
a cogscrab with a bomb in your bag.

get arested

cogscrap pops out

AHAH HU ACKBAR!

**Comment by KorPhaeron** [comment]
Everytime a new var or exception is added for cogscarabs I wonder if they shouldn't be drones

**Comment by ChangelingRain** [comment]
I do the same but drones have everything they happen to need so this is probably still better than any other solution so...

**Comment by Kevak** [comment]
Couldn't rather than preventing picking them up, instead making them Huge/Bulky Items to prevent em from being stored in bags? Would let people pick up one in hands for easy spatial gatewaying but would cut down on the Cogscarab Zerging

**Comment by KingPhilipIII** [comment]
KOR I JUST REALIZED YOUR PICTURE IS A DRONE.

**Comment by coiax** [comment]
Yeah, just make them too big for a bag, so they can only be held in hands or on the head.

**Comment by ExcessiveUseOfCobblestone** [comment]
I would think if someone actually did this they should be applauded for doing something creative rather than breaking out the nerfs.

I personally never thought of this.

**Comment by coiax** [comment]
I've participated as a drone scarab in a bag. It's surprisingly effective.

**Comment by Shadowlight213** [comment]
Ahaha. Well that wasn't the reasoning I expected when I saw the title. I thought it was going to be someone got picked up and thrown into space and was salt.

**Pull request merged**
