### PR TITLE
fixes radiation message

### PR DESCRIPTION
**Pull request by PKPenguin321**
Fixes https://github.com/tgstation/tgstation/issues/20369

### CODE REVIEW

**Comment by PKPenguin321** [comment]
@Jordie0608 the problem was the mention of skin, which robots don't have. robots feeling warm is fine

**Comment by A-t48** [comment]
Robots have a metal skin. AIs on the other hand...

**Comment by Jordie0608** [comment]
@PKPenguin321 No the problem is radiation acting on things that aren't affected by radiation

**Comment by optimumtact** [comment]
Jordie is right.

**Comment by PKPenguin321** [comment]
i maybe fixed it?

**Comment by Jordie0608** [comment]
Aside from not compiling (istype lacks first argument), no. There are more mobs than just silicons who aren't affected by radiation, drones for instance, and hoping to blacklisting them all via istype checks is bad code.

**Comment by PKPenguin321** [comment]
well shoot, i came in here expecting a grammar fix, not a rewrite

**Pull request closed without merging**
