### PR TITLE
Makes space realistic and not transfer heat

### PR DESCRIPTION
**Pull request by Iamgoofball**
...on April Fools.

## About The Pull Request

Makes space realistic and not transfer heat on April Fools.

## Why It's Good For The Game

I asked Ninja how we could make space realistic on april fools and he said that making it not transfer heat would accomplish what we want.

## Changelog

:cl:
fix: Makes space realistic and not transfer heat...on April Fools.
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
Should have blackbody radiation.

**Comment by tralezab** [comment]
Okay this is pretty great

**Comment by Kapu1178** [comment]
It would transfer heat, but it would do so via radiation, not via heat transfer.

**Comment by timothymtorres** [comment]
I like the concept of this PR and wanted to do something like it for a while.  Please don't forget to make space cooling pipes still transfer heat otherwise the SMs will delam all the time.

**Pull request closed without merging**
