### PR TITLE
Re-adds prisoners to the restricted_roles for cultists and revheads.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

This was accidentally done during https://github.com/tgstation/tgstation/pull/63357 where JOB_PRISONER wasn't correctly copied over to restricted_roles as part of turning the code into defines.

I've also formatted the offending lists better to see additions/deletions on GitHub and alphabetised them, but I don't intend to run through and do this for every dynamic ruleset.

If someone else wants to do that, I'll give them a cookie and merge it.

## Why It's Good For The Game

Reverts accidental changes that weren't documented. Cleans up list formatting for uh... 3 lists.

## Changelog

:cl:
fix: Prisoners can no longer roll roundstart revhead or cultist, and can no longer roll latejoin revhead. This fixes an accidental change from an earlier PR.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
Since this is technically a fix I can't really complain, but personally I felt that even conversion antags should be able to start as prisoners. Keeps things fresh, gives some interesting progression as their comrades have to try and bust them out. That sorta thing.

**Comment by BlueMemesauce** [comment]
cultist prisoner can literally just teleport out tho

**Comment by Timberpoes** [comment]
> Since this is technically a fix I can't really complain, but personally I felt that even conversion antags should be able to start as prisoners. Keeps things fresh, gives some interesting progression as their comrades have to try and bust them out. That sorta thing.

The original idea behind prisoners is that they were created as a pure RP role.

RaveRadbury noticed players on Manuel were requesting permas just to sorta vibe in the fancier permabrigs, interacting with sec. It wasn't intended to be a role where people could be genuine antags, as that risk would severely limit security's willingness to interact with prisoners.

I don't personally have much interest in changing that.

On the other hand, permabrigging antags is how you get antag prisoners. So it's still possible, just a little more "emergent".

**Comment by RaveRadbury** [comment]
At the time of PR Maintainers requested that Prisoners start out antag-exempt.

**Pull request merged**
