### PR TITLE
Adds *poo and *fart

### PR DESCRIPTION
**Pull request by Iamgoofball**
...to the gibbering lines.

If oranges can do it I can too

### CODE REVIEW

**Comment by Zilenan91** [comment]
and here I was hoping you'd add farting

**Comment by PKPenguin321** [comment]
and here i was ready for a total shitstorm






get it

**Comment by Niknakflak** [comment]
I mean, I hate when oranges does this but at least his memes are less shitty than this.  Pun intended

**Comment by bgobandit** [comment]
rip reagent farts

**Comment by Cheridan** [comment]
how do you say *

**Comment by Iamgoofball** [comment]
"Asterisk fart"

**Comment by Aranclanos** [comment]
i told you to stop making retarded prs a fuckton of times

**Comment by Iamgoofball** [comment]
Like I said in the OP, I figured that since oranges's gibbering meme prs are okay that this would be fine.

**Comment by ike709** [comment]
It's okay, never let your memes be dreams

**Comment by Zilenan91** [comment]
@Aranclanos 

Why's it okay when oranges does this and not goofball?

**Comment by Iamgoofball** [comment]
He stated why.

**Comment by Zilenan91** [comment]
I did yeah but that's retarded because oranges spews more memes than the comment section on Vine.

**Comment by Iamgoofball** [comment]
It's not my place to argue and neither is it yours.

**Pull request closed without merging**
