### PR TITLE
Improves greentext and spellbook sprites

### PR DESCRIPTION
**Pull request by ChangelingRain**
old
Old sprites.
new
New sprites.

You should click those for less pixellated versions, thanks github.

It's not a significant improvement, but it does standardize the pixel placement and page colors.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
I really really really like the book of blindness one

**Comment by WJohn** [comment]
:+1:

**Comment by swankcookie** [comment]
i always found it offputting how greentext was sized. it made absolutely no sense.

**Comment by WJohn** [comment]
I think it's so people can actually disarm/stun eachother and then grab it, since you have to hold it in your hands.

**Comment by Anonus** [comment]
But that still doesn't make sense, because its previous position would make it harder to click when beneath a stunned person.

**Pull request merged**
