### PR TITLE
You can now repair reinforced walls

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: You can now repair reinforced walls by using the tool you'd use to get to the state they're currently in. Examining will give you a hint as to which tool to use.
/:cl:

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
So , do walls no longer require plasteel to repair?

**Comment by ChangelingRain** [comment]
They actually needed metal, and yes, they no longer require it; you can just use your tools.

**Comment by TechnoAlchemisto** [comment]
Just to make sure, this doesn't make it possible to get infinite plasteel from deconstructing and repairing with tools, right?

**Comment by ChangelingRain** [comment]
It doesn't, no, because all the steps are cosmetic and don't produce stuff.

**Comment by WJohn** [comment]
i thought a couple of steps produced rods, though? do you have to insert those back into the wall?

**Pull request merged**
