### PR TITLE
Bumps auxlua to 1.4.1

### PR DESCRIPTION
**Pull request by Y0SH1M4S73R**
## About The Pull Request

I had to add new Windows signatures to auxtools so it would work on 515. I then had to bump the auxtools lua dependency and push a new release version. This PR bumps the auxlua dependency version.

## Why It's Good For The Game

Fixes admin lua scripting on Windows for 515, for now (it will probably break again as more 515 beta releases come down the pipeline, but what else can you do about it? It's probably still broken on Linux but that's because nobody's found the 515 function signatures on Linux.)

## Changelog

:cl:
admin: Fixed admin lua scripting on Windows-hosted servers running on beta version 515.1602 (the latest version as of this change)
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
keep in mind that 1602 (and all version of 515 before it) have a horrible leaking issue with json_encode so all servers are going to shift up to 1603 when it ships as that has the fix for it. hope you're warmed up to get the sigs for that version since i guarantee no /tg/ production server will be running anything >1603 when it comes out.

**Review by Watermelon914 — APPROVED** [review]

**Comment by Watermelon914** [comment]
> keep in mind that 1602 (and all version of 515 before it) have a horrible memory leaking issue with json_encode so all servers are going to shift up to 1603 when it ships as that has the fix for it. hope you're warmed up to get the sigs for that version since i guarantee no /tg/ production server will be running anything >1603 when it comes out.

This is unlikely to affect much, but we'll see. In any case, auxtools got upgraded with a better versioning system, so making fixes like these should be easier.

**Comment by Mothblocks** [comment]
signatures dont change as often as you might think

**Comment by san7890** [comment]
> signatures dont change as often as you might think

i was under the impression that they broke very often for some reason

**Comment by Mothblocks** [comment]
they do but not every version

**Pull request merged**
