### PR TITLE
Cerestation Tweaks MK VII: BEES edition

### LINKED ISSUE #27108: [CERESTATION] Science checkpoint has an engineering checkpoint locker.
image

### LINKED ISSUE #27125: Cerestation botany has no clothing locker or plant bags
gib muh plant bag reee

### LINKED ISSUE #27158: [CERESTATION] Cargo checkpoint has an engineering checkpoint locker
image
Engie checkpoints for all!

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles (Cerestation)
tweak: Hydroponics has been revamped, adding a few things missing before and adding a bee room in place of the backroom.
fix: Fixed some other stuff.
/:cl:

Fixes #27125
Fixes #27108
Fixes #27158

bee

Reworked Hydroponics to include a round-start bee room with 2 suits and 2 flyswatters, moving the backroom to the corner and making it take up less space. Enjoy beekeeping without turning hydroponics into a death sentence for anyone without a suit, or just remove the windows and do that anyway because why not. Honey-comb frames can be found in the storage room in the hydroponics crate.

### CODE REVIEW

**Comment by Tacolizard** [comment]
my dream comes true 😢

**Comment by Iamgoofball** [comment]
b e e s

should do an airlock style door setup though tbh

**Comment by Iamgoofball** [comment]
also you forgot to mapmerge

**Comment by MMMiracles** [comment]
I did mapmerge.

**Comment by Iamgoofball** [comment]
>39K changes

**Comment by MMMiracles** [comment]
🤷‍

**Pull request merged**
