### PR TITLE
Revert "Heretic spell invocations now use one dead language per path"

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Reverts spell invocation changes.
## Why It's Good For The Game

After seeing this on live for a while, I think it isn't quite worth it. A lot of the spells sound better, but the most common ones don't, so it just ends up being silly overall.
## Changelog
:cl:
del: Revert "Heretic spell invocations now use one dead language per path"
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
Of note is that I'm reverting my own PR.

**Comment by Metekillot** [comment]
ARCH TEE TEE ARCH

**Comment by kawaiinick** [comment]
based

**Comment by CCC23** [comment]
RCT THE TRTH

**Pull request merged**
