### PR TITLE
Removes 2500 point hardsuits

### PR DESCRIPTION
**Pull request by silicons**
@ma44 hardsuit != explorer suits.
Regular space suit crates contain not even a hardsuit and costs 3000 points.

### CODE REVIEW

**Comment by optimumtact** [comment]
good

**Comment by Bawhoppen** [comment]
eva suits crate does get 2 though

**Comment by Armhulen** [comment]
no i like these : (

**Comment by ExcessiveUseOfCobblestone** [comment]
you can still buy these with the mining vendor.

also if you want to be my love mekhi add a flashlight [preferably the seclight] to mining lockers 😉

**Comment by Armhulen** [comment]
oh, i thought you were removing them from the vendor. Yes, do this please

**Pull request merged**
