### PR TITLE
[WIP]Automatic wiring and piping objects for mappers

### PR DESCRIPTION
**Pull request by silicons**
Wire helpers: Automatically connects to wire helpers in adjacent tiles, deleting themselves afterwards. When adminspawned, they stick around and connect automatically to wire helpers that are spawned in near them to assist in admins wiring things.

Piping helpers - Not final: Automatically forms the appropriate pipes to connect to all piping helpers on the same layer and ID next to it, as well as any atmospherics objects with pipe connectors next to it if they share the same connecting face and layer and it is otherwise possible normally in game.

Why: Takes some of the horrible out of wiring and piping maps, hopefully.

STRETCH GOAL: Disposals piping helpers - Probably not though.

STRETCH STRETCH GOAL: Automatically pathfinding wiring helpers, maybe? Probably for another PR.

### CODE REVIEW

**Comment by optimumtact** [comment]
should be done in fast dmm

**Comment by deathride58** [comment]
It'd be much, much better to implement this as a feature in fastdmm. Making it a map object will do nothing but increase load times once beginner mappers start abusing it.

This feature would be fantastic for map prototyping, yeah, but there's quite a few cases where placing wires/pipes manually is a much better option than having them be placed automatically.

**Comment by optimumtact** [comment]
I know, but on the other hand this is here, it solves a real problem for mappers and it's ready to go, whereas fast dmm is kind of abandonware.

If anyone thinks they have the chops to do something like this for fast dmm hit me up and I might pay for the work

**Comment by 81Denton** [comment]
How do the piping helpers deal with multilayer pipes on the same tile? For example, one regular pipe and one /layer3 pipe.

**Comment by 81Denton** [comment]
Also while fastdmm is great to use, it's missing a bunch of features like generating obj instances from directions, showing you coords for selected obj instances, a search function and a minimap. 
(The fastdmm control scheme is a PITA if you're using it with a Thinkpad nub or touchpad, but that's not something that can easily be fixed)

**Comment by praisenarsie** [comment]
@optimumtact fastdmm crashes like 90% of the time out of nowhere

**Comment by kevinz000** [comment]
@81Denton it doesn't conflict with pipes in other layers, or atleast, it's not supposed to.

**Comment by PKPenguin321** [comment]
Really great job, only concern is if this will hit map subsystem startup time

**Comment by optimumtact** [comment]
great job kev you're doing really well

**Comment by kevinz000** [comment]
reopening when done

**Pull request closed without merging**
