### PR TITLE
reverts "Changes Fire Alarm Sound & Makes It Audible"

### PR DESCRIPTION
**Pull request by dannno**
Sorry, but this sound is just awful. No one seems to like it (Haven't seen anyone defend it at least)
Old one is nicer, even if a bit subtle.

### CODE REVIEW

**Comment by francinum** [comment]
It's better than the old one.

**Comment by GunHog** [comment]
You COULD just lower the volume.

**Comment by dannno** [comment]
why would I have to compromise the rest of the game just to compensate for one effect

**Comment by francinum** [comment]
Change the volume in the proc, atleast.

**Comment by Cheridan** [comment]
Just make the alarm sound not loop, it's so aggravating

**Comment by GunHog** [comment]
> why would I have to compromise the rest of the game just to compensate for one effect

I meant lower the volume in the sound proc

**Comment by dannno** [comment]
oh mb

**Comment by Cyberboss** [comment]
The new sound literally blows my ears off

**Comment by Tofa01** [comment]
It would have been NICE at least if someone mentioned me in this, you know instead of going full revert... Fixing this now.

**Pull request closed without merging**
