### PR TITLE
Yet another c2 chem rebalance

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR nerfs the metabolization rate of convermol to 0.2u/tick (up from 0.1u/tick), multiplies the toxin damage healing done by fiziver by 1.5, and fixes some typos in chemical descriptions.

## Why It's Good For The Game

Giving someone a mere 1u of convermol can currently heal them of 137.5 points of oxygen damage, which I think is a little bit too much for a dose that low.

Fiziver is kind of under-performing right now in comparison to chems like syriniver, so I decided to buff how much it heals you. This is partially because I had made a last minute change to my PR that nerfed fiziver that had unintended consequences on its healing rate. A 10u pill of fiziver should now heal around 1.5x as much toxin damage as it did before.

Also, typos bad.

## Changelog
:cl: ATHATH
balance: Fiziver now heals 1.5x as much toxin damage per tick.
balance: Convermol now has a metabolization rate of 0.2u/tick (instead of 0.1u/tick). Before this change, a mere 1u dose (NOT 10u) of convermol would heal you of 137.5 points of oxygen damage over the course of 10 ticks; now you'll need at least a 2u dose to do that. Conveniently, convermol syringes from oxygen deprivation treatment kits inject 2u of convermol at a time (due to their dilution).
fix: Fixed some typos in the descriptions of some chemicals.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
nobody dilutes convermol, all this does is nerf it for the lone gamers out there that dilute it beforehand which is pretty lame

**Comment by Angustmeta** [comment]
Each default syringe of convermol now contains 6u Convermol and 9u Granibitaluri

**Comment by carlarctg** [comment]
what if it had a unique syringe that injected 1u?

**Comment by Krysonism** [comment]
> 
> 
> I still think convermol should share the C2 metab rate and it be properly diluted in the syringe OR the actual healing value lowered (OR both).
> 

Uniformity is not fun. A more interesting solution would like carlarctg proposed would be a special 3u microsyringe that injects 1u at a time

**Comment by ATH1909** [comment]
> I still think convermol should share the C2 metab rate

Wouldn't that get abused by chemists, though?

**Comment by ExcessiveUseOfCobblestone** [comment]
> > I still think convermol should share the C2 metab rate and it be properly diluted in the syringe OR the actual healing value lowered (OR both).
> 
> Uniformity is not fun. A more interesting solution would like carlarctg proposed would be a special 3u microsyringe that injects 1u at a time

sure? If both achieve the end goal of only getting X amount of iterations in I'm not sure how that would break whatever monotony you're referring to though. Just requiring dilution in chemicals breaks the previous notion of just stuffing as much as you can before you hit max volume or OD into a pill/patch.

**Comment by ATH1909** [comment]
travis why ahhhhhhhhhhhhh

**Pull request merged**
