### PR TITLE
Removes the Chameleon Skillchip from the game.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Closes #57581 - Which is incompatible with this PR.

Removes the Chameleon Skillchip as well as the autosurgeon variants that the Chameleon skillchip came with. Includes removing the skillchip's uplink entry and any former #defines that were exclusive to chameleon skillchips and their autosurgeons.

## Why It's Good For The Game

As new skillchips get added, they constantly need to be weighed on the balance of the chameleon skillchip. This limits the design space of skillchips and limits freedom to make them do fun or interesting things for fear of traitors getting simple access to them.

Selectively blacklisting skillchips is an option, but it also defeats the purpose of the chameleon skillchip and still poses some inherent limitations on the power of skillchips if you don't want to blacklist them from the chameleon skillchip.

Increasing the TC cost doesn't change the fact that as more skillchips get added, this chip gets more powerful.

Randomly antag-checking is already a thing that policy handles. Changelings get their own snowflake implementation of skill chips based on the people they're chameleoning, which may or may not need to be looked at in another PR if changelings ability to copy people with skillchips and gain those chillchip effects is also limiting the design space for them.

## Changelog
:cl:
del: The Chameleon Skillchip has been removed from the game entirely.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
while i generally dislike this, its rarely bought anyways and will help most things

**Comment by ArcaneMusic** [comment]
This issue has been brought up since the chameleon skillchip was added to the game.
I'm still shocked that we let the chameleon skillchip work the way it does right now. Chameleon items are supposed to be about visual trickery, so the moment your fake pulse rifle actually shoots like a real pulse rifle it misses the mark IMO.

**Comment by MrMelbert** [comment]
Thanks for pulling the trigger for me.

**Comment by Timberpoes** [comment]
> 
> 
> Thanks for pulling the trigger for me.

Infinite free maintainer GBP is for life, not just for Christmas

**Comment by tralezab** [comment]
I can't even PRETEND to make a scene about this one bye bye ploopy head

**Comment by Serxule** [comment]
this would also close https://github.com/tgstation/tgstation/pull/57593 (funny cqc = best thing)

**Comment by Timberpoes** [comment]
> 
> 
> this would also close #57593 (funny cqc = best thing)

Funnily enough, the PR you believe this should close is also authored by me and I disagree.

#57593 is designed to manage CQCooking issues brought up with CQCooking being buffed by #57503 and address mapper concerns about designing maps when the Cook is able to use CQCooking in other player's workspaces. That PR has nothing to do with Chameleon Skillchips beyond bringing it closer to its pre-buff form - Something I believed would address concerns that the Cook job skillchip was now too powerful to be part of the Chameleon selection without having to blacklist it.

This PR is not related to CQCooking either. I'm not removing the Chameleon Skillchip because of CQCooking, there is a blacklist PR open at #57581 which would have accomplished this instead and I didn't believe the issue is CQCooking being on the Chameleon Skillchip.

Discussions around this all have brought up the idea that the very fact this skillchip exists limits the design space available to coders when coming up with fun, unique, cool or thematic skillchips that give jobs innate benefits. The choices are to either blacklist powerful skillchips - which is not ideal, to increase the TC cost - Which is just kicking the can down the road until more skillchips get added, and removing it entirely - Which is regrettable, because I was the person who originally added them so I can remove them too.

**Comment by Pinkufeck** [comment]
Incredible, another traitor nerf, i've litterally never seen anyone use it for CQC, you could just stick with what chips are available right now and not add the next ones as options for the chameleon. Furthermore, if something is too overpowered for traitors to get for 6 tc, why should crewmembers get it for free ? It's sad that you the first solution you think of when fixing something is deleting it.

**Comment by interestingusernam3** [comment]
>Incredible, another traitor nerf, i've litterally never seen anyone use it for CQC, you could just stick with what chips are available right now and not add the next ones as options for the chameleon. Furthermore, if something is too overpowered for traitors to get for 6 tc, why should crewmembers get it for free ? It's sad that you the first solution you think of when fixing something is deleting it.

Read the fucking PR, it limits skillchip design

**Comment by ArcaneMusic** [comment]
@Timberpoes For the record, is this the sort of thing that's useful to leave in the code EXPLICITLY as a debug item?

**Comment by Ziiro** [comment]
Just go the complete other way with full antag power creep and give it to traitors for free. Easy.

**Comment by coiax** [comment]
> 
> 
> @Timberpoes For the record, is this the sort of thing that's useful to leave in the code EXPLICITLY as a debug item?

Eh, if you have a debug setup, you can just spawn in the specific one you want.

**Comment by YakumoChen** [comment]
Why not change it so it starts with no programs, but you can download skillchips from people / found chips to grow power over time, rather than just starting with all of them, for free?

**Comment by ExcessiveUseOfCobblestone** [comment]
Agent skillchip....

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]
only one person upvoted this, and nearly 500 downvoted. upsetting!

**Pull request merged**
