### PR TITLE
for i in 1 to dildos

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: fucking bad loop shit
/:cl:

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Supermichael777** [comment]
Did someone try to port fortran? what fucking language do you need to do THAT in to make lists work

**Comment by deranging** [comment]
the fuck

**Comment by outbools** [comment]
@Firecage shame on you
https://github.com/tgstation/tgstation/pull/9237
@phil235 @Jordie0608 SHAME ON EVERYONE INVOLVED

**Review by ShizCalev — CHANGES_REQUESTED** [review]
https://github.com/tgstation/tgstation/blob/035bc592c45f318cdd0981cd456256dd68ee9e69/code/modules/mob/living/living.dm#L790

**Comment by Iamgoofball** [comment]
Phil doesn't come here anymore they pay him money at cm

**Comment by ShizCalev** [comment]
Conflict.

**Pull request closed without merging**
