### PR TITLE
Removes Bioterror shells from the Nuclear Emergency uplink

### PR DESCRIPTION
**Pull request by SconesC**
Thread after thread, round after round, never have I seen an item more overpowered and universally hated than the Bioterror darts. Even with an increased cost, they are easily one of the stupidest things in an already unbalanced gamemode. 

Paying any amount of TC for a 1shot unless someone is in a spacesuit (And why would you wear a spacesuit against people doing 90% bullet damage) is just stupid.

Goodnight, Bioterror, I guarantee you won't be missed.

### CODE REVIEW

**Comment by Cebasiz** [comment]
but it's a cool idea why not just nerf it or something sheesh

**Comment by Aloraydrel** [comment]
Bioterror either needs weaker chems or to be removed in my opinion. One shot to crit someone is cray cray!

**Comment by LanCartwright** [comment]
I wouldn't rule the idea of using biochemical weapons out in NukeOps, but for 6 TC to have these kind of darts, it's rediculous.

I'd suggest changing these darts to be empty and requiring the operator to spend that additional 6 TC on a toxins kit and manually loading them with a needle (included in the 12G kit). This balances the costs to 12 TC for 8*30u worth of darts and 12*30u of toxins.

**Comment by SconesC** [comment]
It's been through two nerfs and still totally retarded.

Someone can buff it and re-add it later. We TRIED to improve.

Now we remove.

**Comment by WJohn** [comment]
:+1:

**Comment by Shapsy** [comment]
Reminder that these are just stun slugs with added muting, blinding, and "fuck you this poison metabolizes so slowly that if you can die, get revived and die again with it still in your bloodstream" bullshit

What niche are these even trying to fill, it's anti-everything unless you're wearing a slow ass biosuit for some reason, in which case the op can just whip out his pistol or walk away from you

**Comment by Lumipharon** [comment]
The 'balance changes' to bioterror so far have addressed the actual issue people have with them - they're super fast acting, 1 hit kill weapons. They have a hard counter, but no counterplay.

The obvious solution is to just remove the damaging chems.

Leave it as a stun/mute, and it's still got a useful niche of letting you disable people non lethally, without them being able to raise the alarm.

**Comment by Cebasiz** [comment]
it really should be short term paralyze/mute or something like that. that way you can have the first guy in the line when you're on the way in to tcomms to blow it or something with them loaded, if you run into some random assistant that's about to shout you can hit them with it and retain your stealthy entry.

note: also if you remove the damage you should lower the price to 3 per magazine or something.

they should be niche, not standard issue.

**Comment by SconesC** [comment]
At that point they are a direct upgrade from taser shells in terms of both effect and cost

**Comment by Lumipharon** [comment]
taser slugs cost 3tc per mag as well.
They also work on people with space suits, which is quite significant in spess, and occasionally captains just walk around in their suits.

**Comment by Cebasiz** [comment]
i don't even really understand why taser slugs exist, wouldn't it just be easier to shoot them twice with slugs and permanently incapacitate them rather than shooting something that's a stun but ultimately harmless? i suppose maybe if there was a fire selector so you could switch between magazines but reloading isn't exactly quick. stamina damage on bulldog is huge so eh

offtopic i suppose, but i'd reduce the cost of stun slugs to 2tc and then change bioterror and make it more expensive depending on what you do with it. depending on how much you nerf bioterror, slotting it back into the shotgun duffel might be okay, too.

**Comment by Boredone** [comment]
I believe they exist because the shotties used to be loaded with them by default Cebasiz.

**Comment by Cebasiz** [comment]
ah, you're probably right about that, i think i remember it.

**Comment by Durkel** [comment]
Removing the shotgun and just giving them cr-20s again would be better honestly.

**Comment by Cebasiz** [comment]
bulldog is a great weapon, it just shouldn't be free.

**Comment by daman997** [comment]
why not add like boxes of bioterror darts and you gotta use the syringe gun to shoot them

**Comment by Xhuis** [comment]
reluctant :+1:

**Comment by optimumtact** [comment]
antags should be better geared than station crew, I wish security players would stop coding

**Comment by SconesC** [comment]
@optimumtact Where is line between "better geared than crew" and "unbeatable save extremely specific circumstances" drawn?

**Comment by Shapsy** [comment]
There's only 5 ops at a time (plus a borg most of the time), they're outnumbered as fuck anyway, it's not in their best interests to get into long drawn out firefights. Instead, ops have the advantage of coming in out of nowhere while security's pants are still down, hopefully while the captain is out in the open and unprotected.Trying to balance things in a vacuum where everything is head-to-head and ignoring how asymmetrical the game is is pointless

**Comment by Cheridan** [comment]
@optimumtact nice meme

**Comment by SconesC** [comment]
cancer

We're all ready to move on @Cheridan

**Comment by Jordie0608** [comment]
Merge conflicts

**Comment by SconesC** [comment]
Redundant now that Cheridan chose merge the other PR handling this

**Pull request closed without merging**
