### PR TITLE
Mey's Copious Sprite Update.

### PR DESCRIPTION
**Pull request by Mey-Ha-Zah**
## About The Pull Request

Provides a lot of sprite updates for many items, mostly lavaland related.
image
Original Axe sprite provided by [rlee595](https://github.com/rlee595)

## Why It's Good For The Game

Better Sprites are better to look at

## Changelog

image: modified: Updated a bunch of sprites, mostly lavaland related. Fixes a white pixel. Axe by rlee595

/:cl:

### CODE REVIEW

**Comment by Mey-Ha-Zah** [comment]
Before any of you go: Bring the shoulders back, I removed it cause what I did before was literally a copy paste of the old shoulders onto a terribly re-colored goliath cloak.

No they ain't coming back.

**Comment by Pumpkinoe** [comment]
Herald cloak out here rockin' the https://lisa-rpg.fandom.com/wiki/Dainty_Shawl style

**Comment by EricZilla** [comment]
Monster drops look amazing, particularly the goliath stuff
Not a fan of the new logs, very monotone, and the actual fire part of the bonfire is way too dark, those are the only things that I dislike and they are mostly minor
REALLY like the new cursed katana stuff, old one never felt like a weapon that was cursed, more just a weird blackness

**Comment by Pumpkinoe** [comment]
Forreal though, maybe try making the Herald cloak long, heavy like the old one - and give it a jagged look at the bottom to try and mimic the pose that the Herald adopts.

**Review by Imaginos16 — APPROVED** [review]
No specific thoughts, they're alright.

**Comment by Mey-Ha-Zah** [comment]
> the goliath cloak looks too… _smooth_.. it’s jarring especially when you look at the sprites of the goliaths.

not a goliath cloak...

**Pull request merged**
