### PR TITLE
Fixes moth week dates

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Maybe 2021 will be the year moth week starts when its supposed to.
This should work with these dates: 
image

## Why It's Good For The Game
moff

## Changelog
:cl: Skoglol
fix: Moth week start date fixed
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
we'll get it someday

**Comment by kriskog** [comment]
This also doesnt work, because the last full week can be week 5. I made a mistaken assumption that we counted week numbers differently.

I fixed the weekofmonth function though.

**Comment by tralezab** [comment]
WOW MAINTAINERS WOW. I AM SPEECHLESS

**Comment by kriskog** [comment]
Hi SPEECHLESS, I'm dad

**Pull request merged**
