### PR TITLE
On screen alert system

### PR DESCRIPTION
**Pull request by MrPerson**
Replaces some of the hardcoded HUD icons defined at mob level with a pair of mob procs throw_alert() and clear_alert(). Alerts will appear on the top-right side of the screen.
You can shift-click alerts to get a description of what's wrong and sometimes a tip on how to solve the alert.

Alerts can be given a master, which overlays the master on top of a box and forwards clicks of the alert to that master. Getting buckled will put an alert of what you're buckled to, for example. If it's a chair, you just click the alert and you're unbuckled. The idea I'm shooting for is to replace resist entirely with this kind of stuff.

Making a new alert and using it is a little complicated. This explanation will suck, but this is simpler than I'm making it sound, I promise. Throw_alert() has 4 args, category, id, severity, and obj/new_master. If you don't supply an id, category will be used as id. Only 1 alert per category is allowed; any duplicate will be replaced. Additionally clear_alert() clears alerts by category. Id MUST match a type path of /obj/screen/alert/[id]. That type path is where the alert's name and desc come from. The icon_state of the alert will either be "template" if new_master is set or [id][severity] otherwise. new_master is totally optional.

Examples:
throw_alert("oxy") -- takes name/desc of obj/screen/alert/oxy, icon_state = "oxy" -- clear_alert("oxy")
throw_alert("nutrition","fat") -- takes name/desc of obj/screen/alert/fat, icon_state = "fat" -- clear_alert("nutrition")
throw_alert("nutrition","starving") -- takes name/desc of obj/screen/alert/starving, icon_state = "starving" -- clear_alert("nutrition")
throw_alert("temp","cold",1) -- takes name/desc of obj/screen/alert/cold, icon_state = "cold1" -- clear_alert("temp")
throw_alert("temp","cold",3) -- takes name/desc of obj/screen/alert/cold, icon_state = "cold3" -- clear_alert("temp")

If you pass a new_master, id is only used to get name/desc and still must match a path, but the icon_state is "template" and icon is from the mob's ui preference instead of icons/mob/screen_alert.dmi.

Several unused icons removed, like borg oxygen and temperature alerts. Also some icons were used but now are not and were removed, like the nutrition icon for being well-fed and cyborg charge icon for being fully charged.

Picture 
testing99

### CODE REVIEW

**Comment by optimumtact** [comment]
:+1: systems system systems

I'm gonna do a code pass, to see if anything jumps out

**Comment by Miauw62** [comment]
>magic strings

**Comment by Dorsisdwarf** [comment]
How does this mesh with the Moveable Screen Elements system of RRs?

**Comment by RemieRichards** [comment]
@Dorsisdwarf at the moment it doesn't, but if MrPerson changed his prototype from /obj/screen to one of the 2 movable types (/obj/screen/movable or obj/screen/movable/snapable) they'd work perfectly fine.

Idk, it might be nice to have them default to the top right but movable if they get in your way perhaps.

**Comment by Dorsisdwarf** [comment]
Can we get a picture/gif of some of these in action? Particularly what happens when you have several on-screen at once,.

**Comment by MrStonedOne** [comment]
Gonna need pictures.

**Comment by Razharas** [comment]
>I wish we had better screen object handling

**Comment by MrPerson** [comment]
Making them movable is easy, yeah, but I'm not sure it's worth it. If you have an alert like that, you should be working to make it go away, not worrying about where it is on the screen.

**Comment by Giacom** [comment]
Is the heart beat alert required anymore if the dummy, which tells you where you are hurt, and the bloodstain (SO REAL) is going to tell you basically what the heartbeat HUD is going to say? It could free up some screen space.

**Comment by Cheridan** [comment]
That sliding effect is sexy AAA quality

**Comment by RemieRichards** [comment]
Omg that sliding :+1:

**Pull request merged**
