### PR TITLE
Separates atmosmachinery.dm into several files

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
See title

## Why It's Good For The Game
Procs are easier to find inside the correlated file, future code should be cleaner, preparations for other stuff i want to do

### CODE REVIEW

**Comment by timothymtorres** [comment]
Atmos gang.  Atmos gang.  Atmos gang.

**Review by Cyberboss — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
This is maybe a little bit too granular, could you elaborate on what you want to do in future?

**Comment by Ghilker** [comment]
> This is maybe a little bit too granular, could you elaborate on what you want to do in future?

I want to make some default procs to use with machines, add other changes to connections or just clean up the mess that is connect code. But to do it I need to have this level of clarity where I can focus on one section of the atmosmachinery

**Comment by LemonInTheDark** [comment]
Ahhhhhhhhhhh
I'm alright with things like splitting up a big defines file or something that contains a lot of unrelated procs and such, but I think it's helpful for most of the info about some bit of behavior/an object to be in the same file.

Maybe the difference here is where I place that line? Like, not having turf atmos defies in the same file as lighting makes sense, but splitting up atmos machinery into separate files with a new file for each bit of functionality seems like an overcorrection.

**Pull request closed without merging**
