### PR TITLE
Reverts toolbox sprites to old sprites

### PR DESCRIPTION
**Pull request by silicons**
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=9630
23 vs 3.

### CODE REVIEW

**Comment by optimumtact** [comment]
Don't revert war with the headcoder you dip

**Comment by ChangelingRain** [comment]
Give them a chance!
Let stockholme syndrome set in!

**Comment by WJohn** [comment]
Literally just let stockholm syndrome run its course. It's frighteningly effective.

**Comment by Cheridan** [comment]
the new sprites are objectively better nostalgiatards

**Comment by optimumtact** [comment]
Well that's that then.

**Comment by kevinz000** [comment]
*flames*

**Comment by PKPenguin321** [comment]
if somebody were to VV toolboxes to old sprites every round is that okay

**Comment by optimumtact** [comment]
obviously not but that's a problem for headmins to deal with, not ours

**Comment by Kraseo** [comment]
I DON'T WANT CHANGE AAAAAHHHH AAAAHHHHHHHHHH!!!!!

**Comment by PKPenguin321** [comment]
>I WANT CHANGE AAAAAHHHH AAAAHHHHHHHHHH!!!!!

**Comment by RemieRichards** [comment]
@PKPenguin321 improvements*

**Comment by PKPenguin321** [comment]
implying

**Comment by AnonymousNow** [comment]
Are these Goonsprites newer? Because they're a carcrash.

**Comment by Incomptinence** [comment]
New sprite looks like a biscuit tin.

Both are of real toolbox designs but the non slanted lid just falls apart from a 2 dimensional top down perspective. 

Expect sardines to be held in that not tools. Someone see cheridan to an optometrist their opinion on sprites is increasingly bizarre.

**Comment by AnonymousNow** [comment]
I'd be happy with the new sprites if they were three-dimensional, but unless you count an attempt at tapering at the top, their square-on perspective makes them look completely flat.

**Pull request closed without merging**
