### PR TITLE
Removes hijack objective from traitor

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It seems silly to have something that directly mandates a playstyle that admins consider poor behavior.

https://tgstation13.org/phpBB/viewtopic.php?f=23&t=7404&view=unread#unread

### CODE REVIEW

**Comment by KorPhaeron** [comment]
I'm not sure about this

**Comment by evsey9** [comment]
Do it.

**Comment by Fox-McCloud** [comment]
Everyone has hijack, by default, on TG though---if you roll traitor, you have zero responsibilities outside of high-end server rules--you're free to kill as many as you like and be as insane as you like---seems a bit silly to remove this.

**Comment by Supermichael777** [comment]
greentexting makes me hard

**Comment by GeneralGoose** [comment]
remove traitor

**Comment by MMMiracles** [comment]
Add a population requirement to it so lowpop doesn't get steamrolled by the traitor for their objective and mid-high pop can still enjoy the fun of a murderboner with a purpose.

Outright removing it seems over-the-top and not required.

**Comment by Robustin** [comment]
I love that traitors can work together for hijack. Greentexting hijack with 3-4 other traitors aboard is literally some of the most fun you can have in SS13.

**Comment by GunHog** [comment]
Why is murderbone considered poor behavior? I like murderbone...

**Comment by Jalleo** [comment]
To be honest it should be done as a multi antag objective in mid to high pop as it would: 
1.cause traitors to find their partners which should be DIFFICULT 
2. start a push towards more complex objectives.
3. Be the perfect middle ground as a partial team mode game within a singpe antag game mode.

**Comment by PKPenguin321** [comment]
:-1: A successful hijack is the most badass thing ever, and even without this objective people will still murderbone

**Comment by Incomptinence** [comment]
Remove said admins the hijack is a find challenge and we have admins to spare.

**Comment by Incoming5643** [comment]
kickin' rad place to be :-1:

**Pull request closed without merging**
