### PR TITLE
Scarves can begin surgeries.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Adds the surgery initiator component to 3 types of scarves: neck/scarf, neck/large_scarf and neck/infinity_scarf. 
## Why It's Good For The Game
Heads of staff get cloaks that can begin surgery, and everyone can wear bedsheets to begin surgery, now scarf wearers can be included in the gang of being able to begin surgery on non-moths with their neck wear.
## Changelog
:cl:
add: Scarves can now begin surgery.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
yeah makes sense i guess

**Comment by improvedname** [comment]
lukas beedell lore

**Comment by Farquaar** [comment]
Too fuzzy. Will leave fuzzballs in open wounds.

**Comment by Fikou** [comment]
doesnt make sense

**Comment by calliophis-maculiceps** [comment]
> doesnt make sense

as much as bedsheets

**Comment by Farquaar** [comment]
> > doesnt make sense
> 
> as much as bedsheets

Bedsheets are big enough to cover someone's body, at the very least

**Pull request closed without merging**
