### PR TITLE
Reduces no-slip to have 0 rep cost.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
Reduces no-slips to 0 rep cost. This affects both, no-slip mod module, and no-slip chameleon shoes.

## Why It's Good For The Game
They are shoes, shouldnt be something special in terms of reputation.

## Changelog
:cl:
balance: No-slip mod module and no slip shoes no longer have a reputation lock.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Why do either of these have a reputation requirement, they're shoes

**Comment by Xander3359** [comment]
> Why do either of these have a reputation requirement, they're shoes

Is this maintainer approval to reduce rep cost to 0 for both no-slip and no-slip module?

**Comment by Jacquerel** [comment]
I see the change was in #16807
I'd hope that this is already fixed by limiting the actual weapons with rep instead, although I guess nothing stops you from going ham with lube and a circular saw? The reasoning of "you can always use a clown PDA" to stop a traitor shouldn't be such a big deal now as stun resistance or immunity is much rarer and noslips don't make you immune to disablers.
IDK doesn't seem like it should be a massive issue to me but I've been wrong before.

**Comment by Vect0r2** [comment]
@Xander3359 you might want to update the body of your PR to the fact it takes 0 rep.

**Comment by san7890** [comment]
> I see the change was in #16807 I'd hope that this is already fixed by limiting the actual weapons with rep instead, although I guess nothing stops you from going ham with water and a circular saw? The reasoning of "you can always use a clown PDA" to stop a traitor shouldn't be such a big deal now as stun resistance or immunity is much rarer and noslips don't make you immune to disablers. IDK doesn't seem like it should be a massive issue to me but I've been wrong before.

you can also buy a gun on lowpop and kill the janitor for his galoshes (or just break into the office and steal the galoshes since there's so few people). it don't matter

**Comment by SgtHunk** [comment]
> you can also buy a gun on lowpop and kill the janitor for his galoshes (or just break into the office and steal the galoshes since there's so few people). it don't matter

galoshes also slow you down as much as a space suit, which no-slips don't
if you want to effectively murderbone, being slow is counterproductive

**Pull request merged**
