### PR TITLE
[Meta] Map Playability Tweaks

### LINKED ISSUE #24850: MetaStation Issues
1. There is no way for the chaplain to access their coffins in the chapel unless they deconstruct or break a reinforced window. Should be a windoor there for the Chaplain to access them.

2. It appears engineering isn't given welder supplies lockers or electrical supplies lockers. Likely an oversight when supermatter engine changes occurred.

### PR DESCRIPTION
**Pull request by Penguaro**
Fixes #24850

:cl: Penguaro
del: **Engineering** - Removed Tables, paper bin, and pen
add: **Engineering** - Replaced with Welder and Electrical Lockers
add: **Engineering** - Moved First-Aid Burn kit to Engineering Foyer
tweak: **Chapel** - Replaced one Window with Win-Door for Coffin Storage
/:cl:

[why]: # For Engineering. The Welding and Electrical cabinets were missing. For Chapel - There was no logical way to access the coffins.

### CODE REVIEW

**Comment by Penguaro** [comment]
Merged recent commits to resolve merge issues.

**Comment by Penguaro** [comment]
Updated title of PR and notes. Included a kitchen tweak since it was minor for the map.

**Comment by Penguaro** [comment]
Resolved Merge issues.

**Comment by blobbernaut** [comment]
Removes deep fryer? Fuck you

**Comment by Penguaro** [comment]
It just removes the one deep-fryer. It's not intended to be the end all fix but a work-around for movement in the kitchen. The other deep-fryer on the right side remains.

**Comment by jughu** [comment]
No i want B O T H just remove a table REEE

**Comment by Penguaro** [comment]
There's already so few tables!!!!!

**Comment by jughu** [comment]
Remove the rack with the donk pockets place table there remove table from the left add deep fryer there EASY

**Comment by Penguaro** [comment]
I don't believe you. You're trying to trick me into ERP!

**Comment by jughu** [comment]
DARN IT I WAS SO CLOSE

**Comment by Penguaro** [comment]
In all actuality I'm going to remove the deep-fryer removal and make a separate kitchen PR involving other re-arranging. Who knew a deep-fryer would be a hot issue...

**Comment by Penguaro** [comment]
Returned the Deep-Fryer and edited the PR Description.

**Pull request merged**
