### PR TITLE
Mappers Can Now Stop Railings

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request
I MADE RAILING ENDINGS, before, railings could only have straight lines and curves, meaning that if you wanted to have a seamless rail line, it had to loop into itself. Now you can just end them.

Look at how ugly this is, they just turn and stop!
image
Look at that pleasant termination of the line of railing
image

Amazing!
image

I put a few on the North Star as a tech demo (I also removed a single errant openspace that wasn't supposed to be there)
## Why It's Good For The Game
This PR does nothing but enhance aesthetics for mappers.
## Changelog
:cl:
image: Railing ends now exist.
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Good PR

**Review by Cyberboss — APPROVED** [review]

**Comment by DATA-xPUNGED** [comment]
This will revolutionize railings as we know it

**Comment by Cheshify** [comment]
Alt titles:
Mappers Rejoice: Ending of the Rail
Mappers Can Now Stop Railing
Mappers Can Now Stop Railing Lines

**Comment by EricZilla** [comment]
Alls rail that ends rail

**Review by Wallemations — APPROVED** [review]
Our railings look like dogwater but at least this PR adds some glitter to said water

**Comment by Pumpkinoe** [comment]
i love you

**Comment by Cheshify** [comment]
I don't actually hate how railings look. They're a little outdated sure, but they usually provide an unobtrusive but present barrier that I think really adds to plenty of locations.

**Pull request merged**
