### PR TITLE
Revhead camoHUDs + syndicate thermals are now full camoflage items

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Camoflaged HUDs given to head revolutionaries now function the same
as chameleon glasses in the chameleon kit bundle, giving them an action
button and far more disguise options.
add: Syndicate thermals are also now more like chameleon glasses as well.
/:cl:

- inb4 the revhead runs around with ratvar or cultist blindfolds on

image

### CODE REVIEW

**Comment by vcordie** [comment]
Good change for consistency.

**Comment by jughu** [comment]
This was very needed when security could fish out revheads without trouble

**Comment by Robustin** [comment]
Im almost leaning toward suggesting this be a roundstart implant. Chams have been around long enough that I'm seeing sec arrest people for having sunglasses early in the round.

Nothing shittier than having a rev revealed because the HOS feels the need to stun+search a chef wearing sunglasses.

**Comment by PKPenguin321** [comment]
>Chams have been around long enough that I'm seeing sec arrest people for having sunglasses early in the round.

I haven't. You should ahelp these HoSes when you see them.

**Comment by scoopscoop** [comment]
>You should ahelp these HoSes when you see them.

People know better than to give away that they're powergaming that hard. They'll just suspect you hard and then nab you the instant someone gives away the round type.

**Comment by Fox-McCloud** [comment]
`inb4 the revhead runs around with ratvar or cultist blindfolds on`

MAI IMMERSHUN.

**Comment by SweaterKittens** [comment]
If you see a HoS arresting someone for having sunglasses, feel free to report it and I'll dunk them on the spot.

**Comment by jughu** [comment]
@sweaterkittens but if revs is confirmed sec people can fish out the eye wearing mesons/sunglasses to have easy revheads

**Pull request merged**
