### PR TITLE
Signal define

### PR DESCRIPTION
**Pull request by ninjanomnom**
It's time for another one of those prs I do occasionally where regexes are the real author.

This changes all SendSignals into defines which call on _SendSignal instead. This makes profiling of the thing a bit more meaningful and its call count a bit lower (494657 -> 180046 calls during init)

Should also benefit performance a minor amount.

The ~~regexes~~ authors are:

`([^_\.])SendSignal\((.+?)\)` -> `\1SEND_SIGNAL(src, \2)`
`([\.\w]+?)\.SendSignal\((.+?)\)` -> `SEND_SIGNAL(\1, \2)`

I'll remove DNM when this has been tested enough

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
Testmerged on bagil for two rounds, causes some people to miss items from their inventory:

```
proc name: equip to best slot (/obj/item/proc/equip_to_best_slot)
usr: Mike Murdock (bigfatbananacyclops) (/mob/living/carbon/human)
usr.loc: The floor (69,159,2) (/turf/open/floor/plasteel)
src: the bluespace shelter capsule (/obj/item/survivalcapsule)
src.loc: Mike Murdock (/mob/living/carbon/human)
call stack:
the bluespace shelter capsule (/obj/item/survivalcapsule): equip to best slot(Mike Murdock (/mob/living/carbon/human))
Mike Murdock (/mob/living/carbon/human): quick-equip()
Mike Murdock (/mob/living/carbon/human): key down("E", Bigfatbananacyclops (/client))
Mike Murdock (/mob/living/carbon/human): key down("E", Bigfatbananacyclops (/client))
Mike Murdock (/mob/living/carbon/human): key down("E", Bigfatbananacyclops (/client))
Mike Murdock (/mob/living/carbon/human): key down("E", Bigfatbananacyclops (/client))
Bigfatbananacyclops (/client): keyDown("E")
```

**Comment by ninjanomnom** [comment]
I did that earlier but it was throwing compiler warnings and forgot to figure it out later. I need to investigate the problem a bit more but this *may* have revealed a byond bug.

**Comment by SpaceManiac** [comment]
The [BYOND bug was fixed](http://www.byond.com/forum/?post=2374624#comment24142130), so:
* Add parentheses
* Resolve conflicts
* Travis (and the servers?) on 1427
* testmerge?

Then it's good.

**Comment by ninjanomnom** [comment]
Still waiting on the update to actually happen, then will have to wait for the servers to run 1427 for a little while to make sure it's stable, it's a big update.

**Comment by ninjanomnom** [comment]
Found another bug while updating ( http://www.byond.com/forum/?post=2376366 ) but it has an easy workaround. I'll testmerge this for a while and it should be good to go.

**Comment by ninjanomnom** [comment]
I've not heard any complaints so it should be good to go

**Review by SpaceManiac — APPROVED** [review]
Trusting in the regex and testmerges

**Pull request merged**
