### PR TITLE
Adds extendo arm mutation to genetics

### PR DESCRIPTION
**Pull request by Time-Green**
[Demonstration](https://youtu.be/_PbfCJ8rnJg)
Adds a new mutation to genetics I meant to add a while ago but kinda forgot about.

Allows you to shoot your arm out to grab and put down items. The arm is skincolored for max immersion.
You can also kinda use it to interact with your surroundings. Pulling out lights, opening lockers and airlocks etcetera.
A very important thing is that you can use it to interact with others. All intents work just fine with your extended arm. Yes you can supersonic tableslam people with your extended arms. 

If your arm gets stuck it'll eventually detach so don't get it stuck. Also if your arm flies too far it'll get ripped of.

:cl: Time-Green
add: Adds extendo arms mutation to genetics. Have fun flexing on your inferior colleges with your extended arms. 
/:cl:

### CODE REVIEW

**Comment by SouDescolado** [comment]
This could be a Limb Augmentation from Robotics instead of Genetics. It would make more sense for it to detach and we already have an extendo-hand thing (That already uses a cyborg arm)

**Comment by HomocidlePancakes** [comment]
How does this interact with that surgery which makes you unable to loose limbs?

**Comment by Time-Green** [comment]
You can't use it then

**Comment by HomocidlePancakes** [comment]
How about make it tear you in half instead? Would be funny

**Comment by Shardj** [comment]
Does this interact with tele ok? There's currently a bug related to extendo hand + tele https://github.com/tgstation/tgstation/issues/42743

**Comment by Time-Green** [comment]
They're two completely different things, so they shouldn't interfere with each other at all. I've tested a few things and there's nothing you can do that you couldn't do with them seperately

**Comment by drderp3635** [comment]
It looks awful and I love it

**Comment by Angustmeta** [comment]
Looks fun but how does it interact with gloves graphic-wise? Will you still get shocked by doors if not wearing insulateds?

**Comment by Time-Green** [comment]
gloves fall of due to you technicly having no arm during the stretching, and you will get shocked by touching electrified stuff.

**Comment by Shardj** [comment]
Interaction with handcuffs?

**Comment by Time-Green** [comment]
doesnt work with handcuffs

**Comment by MrDoomBringer** [comment]
image

**Comment by ExcessiveUseOfCobblestone** [comment]
> This could be a Limb Augmentation from Robotics instead of Genetics. It would make more sense for it to detach and we already have an extendo-hand thing (That already uses a cyborg arm)

I know we want to flesh out genetics but this seems more appropriate

**Comment by Therapist1** [comment]
Hell no stretchy arm genes all day all the way

**Comment by PKPenguin321** [comment]
Excuse me but this is the coolest thing ever

**Comment by ExcessiveUseOfCobblestone** [comment]
Agreed, just not as a genetic mutation but rather an augment.

**Comment by PKPenguin321** [comment]
No

**Comment by PKPenguin321** [comment]
Does this look like an augment to you https://upload.wikimedia.org/wikipedia/en/thumb/e/ef/Helen_Parr.png/220px-Helen_Parr.png

**Comment by zxaber** [comment]
Please don't make more augments I hate being begged for the ones we already have.

It's a horrible cycle. People come to me for surgery because they forget medical exists, which makes people stop playing medical, which makes people come to me for surgery. Make it stop.

**Comment by ExcessiveUseOfCobblestone** [comment]
if you take issue with how the augments are robro exclusive why not do something about it instead of putting would-be augments into genetics?

It's more immersive to have a robotic limb that extends out than string bean arms imo.

**Comment by SouDescolado** [comment]
> Does this look like an augment to you

@PKPenguin321 So that means we are going to be able to stretch the neck too? Or the legs? Or change forms? Plz Penguin. It makes sense if it is an augment because it is just the fucking arm.

Also, about detaching, what if I still have another arm? Can I stretch the other arm and be without one?

Again, augment. If the problem is this being on robotics, make it and send them to medical actually do the surgery.

**Comment by Time-Green** [comment]
> > Does this look like an augment to you
> 
> @PKPenguin321 So that means we are going to be able to stretch the neck too? Or the legs? Or change forms? Plz Penguin. It makes sense if it is an augment because it is just the fucking arm.
> 
> Also, about detaching, what if I still have another arm? Can I stretch the other arm and be without one?
> 
> Again, augment. If the problem is this being on robotics, make it and send them to medical actually do the surgery.

IF I were to not have it be a mutation, I would make it some sort of surgical procedure instead. There’s not really many interesting ones.

**Comment by optimumtact** [comment]
this feels silly, thematically speaking

**Comment by PKPenguin321** [comment]
Elastic limb mutations are so ingrained in retro-futuristic settings as a trope [(largely thanks to this guy)](https://static.comicvine.com/uploads/original/4/49448/1695377-mrfantastic.jpg) that Disney modeled Elastigirl after it in The Incredibles (a series of films with a distinctly retro-future theme and setting) and the Venture Bros (an American show that is largely a celebration of all things retro-future) has [a whole character](https://venturebrothers.fandom.com/wiki/Professor_Impossible) with it as his gimmick. It very strongly fits the theme of the game (that is, retro-sci fi/retro-futurism) and saying otherwise shows ignorance to the theme in question.

**Comment by optimumtact** [comment]
mfw some guy from 2014 tries to tell me what the theme of my game is

:nauseated_face:

**Comment by PKPenguin321** [comment]
I seriously hope that's ironic

**Comment by Shardj** [comment]
ss13 is silly

**Comment by Militaires** [comment]
# BREAKING NEWS: ORANGES KNOWS NOTHING ABOUT ""HIS"" OWN GAME.

This week, the local tgstation maintainer "optimumtact" gave a press statement about how the critically acclaimed "Extendo Arm" mutation PR does not fit the theme of "Space Station 13" because of its reported silliness, "I'm literally maintaining a game with clowns and cat ears in it, and I'm calling one good mutation silly and implying it doesn't fit the "theme"", said optimumtact, "I'm a dumb bitch with no taste, I will never improve, I will never change, that is a promise". Our top analysts at BAN (Bitchass News) are still trying to understand what optimumtact meant by this.

**Comment by MrDoomBringer** [comment]
inb4 this comment was marked as off topic

**Comment by MrDoomBringer** [comment]
the nigga who hides the above comment is triple gay

**Comment by SouDescolado** [comment]
Man, why put in genetics. Now it is a random chance that you maybe even get it if the geneticist bothers to give you it. Make it an augment that even ghetto surgery can give it, you just need to make a extendo arm thing that WE ALREADY HAVE

**Comment by SouDescolado** [comment]
Also: "Look, I am genetically modified to extend ONLY MY LEFT ARM". Makes no sense.

**Comment by Time-Green** [comment]
Both your arms are extendo arms

**Comment by ExcessiveUseOfCobblestone** [comment]
_Currently constructing the great wall of genetics..._

**Comment by PKPenguin321** [comment]
>Now it is a random chance that you maybe even get it if the geneticist bothers to give you it.

This is not how genetics works. Learn how it actually works before commenting on it.

**Comment by SouDescolado** [comment]
You have 8 mutations default. You dont choose them, they are random. If you want different ones you need to scramble your DNA, otherwise you get mutations with instability AFAIK.
The geneticist needs to correctly find the pair of AT - TA - GC - CG. Maybe they don't even bother saving that, since there are better mutations anyway, and maybe they just don't even research it as they get something better.
THEN you need the geneticist, CMO or some robust assistant that broke into the genetics to give you the activator or the mutator, to then use it.

Can you please enlighten me on what I do need to learn?

**Comment by PKPenguin321** [comment]
Geneticists can print mutators that are guaranteed to give you a mutation at the cost of genetic instability. It's not random like you said, you don't need the gene already for a mutator to work.

**Comment by SouDescolado** [comment]
It is random considering when this becomes available to "public". It could be the first genetic mutator discovered, it could be skipped, it could be at round end. If it is an augment you also need to bother someone to do the surgery, but the only random factor would be getting someone willing to do it.

Also, how different is this compared to TK?

**Comment by optimumtact** [comment]
you know fuck all you guys for being rude.

Go and stick your head in a blender

**Comment by anconfuzedrock** [comment]
Yeah, that'll show time-green, how dare he have a pr where other people are being rude. Fucking douchebag.

**Comment by CRTXBacon** [comment]
that was extremely rude of you oranges.
You better apologise and learn your lesson, young man.

**Pull request closed without merging**
