### PR TITLE
[s] Revert "Revert "Revert "Revert "[s] Revert "Revert "Improves bee lore""""""

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#29988

Self merging your pr is bad mkay

### CODE REVIEW

**Comment by RemieRichards** [comment]
Don't be a robot

**Comment by RemieRichards** [comment]
Fite me robot

**Comment by RemieRichards** [comment]
the robot is <del>working now</del> cheating

**Comment by ChangelingRain** [comment]
I want this bee meme to stop

**Comment by RemieRichards** [comment]
What part of 'the robot is cheating' did you not get

**Comment by optimumtact** [comment]
just wait 24 hours ffs

**Comment by ChangelingRain** [comment]
[wow that's super hypocritical](https://github.com/tgstation/tgstation/pull/29970)

**Comment by optimumtact** [comment]
Deleted comment

**Comment by optimumtact** [comment]
That was my evil twin brother Yuikio Nagisakihitlerdidnothingwrongu

**Comment by optimumtact** [comment]
you need to wait

**Pull request closed without merging**
