### PR TITLE
[MAP] Doubles Initial Engineering SMES charge

### PR DESCRIPTION
**Pull request by Ikarrus**
- Replaced engineering SMESs with a subtype that starts with 1.5e6 charge
- Engineering now has 4 SMESs
- All other SMESs start with 0 charge

The station has expanded over the years with more and more rooms (and APCs) added that drain the SMES. Moving the emitters to drain the SMES instead of the APCs probably didn't help, either. Engineers don't get nearly as much time as they should these days, with a loose singularity appearing in the first 10 minutes a lot more common, through no fault of the engineers other than they weren't fast enough.

Trying to set up the singularity solo now either takes perfection, or a marathon speed to start it. Both are far too high of a risk for something that can end the round in the first 10 minutes, that needs to be done or it will end in the first 30 minutes.

From my observation as an admin with access to the logs and personal experience as an engineer, I'd say easily more than half of round-start singularities is caused by this. And no, we don't and won't ever ban engineers for making honest mistakes.

ATM engineers have about 7ish minutes to hook up the engine fully before the SMES drain. This doubles that time to give them roughly ~15 minutes.

### CODE REVIEW

**Comment by RemieRichards** [comment]
They don't need that 7ish minutes, due to the pacman generator Engineering spawns with, which is like, 7 minutes they can deploy whenever they want to set up the engine
Plus it's perfectly possible to get done within that time, you can set up the engine alone in like, 4 minutes.

**Comment by MrStonedOne** [comment]
It seems like it might make more sense to add a fourth smes and fix the ocd of peoples every where

**Comment by Ikarrus** [comment]
The issue is that the singularity containment often fails between them starting it up and them actually hooking up the SMES to accept input power. It just drains it way too fast

**Comment by RemieRichards** [comment]
that's a box thing and box sucks @MrStonedOne

**Comment by Ikarrus** [comment]
And I tried that but someone fucked the map merger to make it even more difficult to use so I won't even bother with it.

**Comment by Incoming5643** [comment]
you just have to put the path in at the end, it's not THAT hard

**Comment by phil235** [comment]
:+1:

**Comment by xxalpha** [comment]
What is this a hugbox? Setting up the engine is super easy, if the engineers are too shit to set up the engine, they are too shit to be allowed to play that job anyways.

**Comment by Ikarrus** [comment]
Buzzwords pls. 

If there's only one engineer, or if they're "too shit", apparently nobody gets to play because a singulo in first 10 minutes = short as fuck round for everyone. 

It happens more often than you think.

**Comment by Jalleo** [comment]
We really need statistics again.

**Comment by AndroidSFV** [comment]
Better idea (imo) would be to give the SMESs in Electrical Maint a default charge (map edited to 0), and have engineers wire those in if they take too long setting up the engine.

**Comment by Ikarrus** [comment]
I don't see how adding another time consuming task on the other side of the station is going to help. 

The problem isn't that engineers take too long to get started --that's what the pacman is for. 

The problem is even veteran engineers are having trouble starting it solo without it getting loose because the SMES drains too fast once you have the emitters up. Time needs to be allotted to actually get the singularity started and the SMES configured. 

I don't see anything fun about having the singularity loose at round start, reducing the round to waiting for the shuttle to arrive.

**Comment by PKPenguin321** [comment]
there is literally no conceivable downside to this that i can tell, why are you guys complaining

**Comment by Cheridan** [comment]
It would be cool if SMES automatically filled a certain % based upon the size/drain of the station, so it would scale depending on the map.

**Comment by Jalleo** [comment]
^^^^ I said this yesterday on irc

**Comment by astralenigma** [comment]
Also the pacman is only usable if you get plasma if you have no AI or CE you will have to go to science/mining/Chemistry or Disassemble the secure storage wall (probably more the latter), I also noticed in my server the singularity escaping most of the time or the engineers just saying meh energy has runout call the shuttle.

**Comment by AndroidSFV** [comment]
This should now resolve both #6451 and #4805

**Comment by Jalleo** [comment]
Actually there is plasma in engineering its just not easily visible.

**Comment by astralenigma** [comment]
I guess next time I will have to search a bit more then.

**Comment by Jalleo** [comment]
Its the crate in secure storage.

**Comment by PKPenguin321** [comment]
@astralenigma actually, you can just unlock the engineering APC with your engineer ID, manually disable environment power, then just crowbar open the blast doors on secure storage
then you can re-enable environment power
i do it all the time when there's no CE

**Comment by Ikarrus** [comment]
@Cheridan if you can figure out how much power each APC takes in the first ~15 minutes of a round I'll do it. Because right now powercode is too stronk and I can't crack it.

**Comment by optimumtact** [comment]
:-1: hugbox shit, get fucking good at engineer

**Comment by drynwyn** [comment]
It's easy to set up the engine in under seven minutes, even as a solo engineer, but raising the time you have to do that to 15 minutes hurts LITERALLY NOTHING and will prevent rounds from being complete abortions.

**Comment by advomach** [comment]
Keep the number of SMESs at 3 please, I enjoy placing the generator in the 4th spot so that I don't have to do any wiring

**Comment by AndroidSFV** [comment]
@cheridan did this get reverted in part? SMES in engineering on box are starting at 0 charge (they are not the new subtype you created in this PR)

**Pull request merged**
