### PR TITLE
nerfs the experimental syndie teleporter

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
gives a few nerfs to the experimental syndie teleporter
1. its charging system is now consistent 15 seconds per charge, using a system similar to the doorjack
2. emps instead of giving you a free teleport, just fully drain the charges
3. bumping into a person is a knockdown and a bit shorter rather than a full stun
4. the safety range has been lowered from 3 to 1.

## Why It's Good For The Game
more consistency lets you and the people against you have reliable info on your abilities (if you used the teleporter all four times, you wont regain those charges for a while)
emps draining lets you counteract the item which you cant really do currently, if you emp it they just teleport away and maybe die if youre lucky
bump stun is annoying lol
safety range being 3 completely babifies the item, removing all possible risk, cause these is no way in fuck that every tile in a 7x7 block (even wider than that) is closed. there is zero risk of using the item carelessly unless youre using a boh (lol) or got emp'd unluckily. it being 1 means there is some possibility that if you fuck up a jump into a 3x3 wall (which is already rare) you will die for your silliness

## Changelog
:cl:
balance: the experimental syndie teleporter has gotten a few nerfs
balance: its charging system is now consistent 15 seconds per charge, using a system similar to the doorjack
balance: emps instead of giving you a free teleport, just fully drain the charges
balance: bumping into a person is a knockdown and a bit shorter rather than a full stun
balance: the safety range has been lowered from 3 to 1.
/:cl:

### CODE REVIEW

**Comment by Jezzared** [comment]
I thought this was a salt PR at first because i've never used the teleporter and know it's been a top pick lately.

No, these are all sensible chances and i'm shocked at how lenient it was before. Good nerfs without killing the item. 👍

**Comment by Borisvanmemes** [comment]
Oh god yes.

I think you're misunderstanding how the safeties work though, they can only teleport you sidewards.

**Comment by Fikou** [comment]
> I think you're misunderstanding how the safeties work though, they can only teleport you sidewards.

yeah they can teleport you sideways but 3 tiles of leniency in both side ways will practically never be lethal

**Comment by Pickle-Coding** [comment]
This thing will either be straight up OP, or noob bait because of all the bloated mechanics it has, or even both!

I think it should get removed, but at least this is a step in the right direction.

**Comment by 13spacemen** [comment]
It's not as OP as you think, this same exact item is on Beestation and Paradise which are both MRP servers and their players are much less robust than TG players yet they haven't had a problem with it
The main problem is that TG players follow meta/optimal gameplay (most of the uplink is ignored), nobody plays Sec on TG and it's harder to make EMPs, chemnades, TTVs on TG to counter syndie teleports
People still get gibbed with the current teleporter or run out of charges

A better nerf would be to lower the charge regen probability from 10% to 5%, the doorjack timer thing is lame since part of the fun is that it recharges randomly

Safety range can be 2 tiles instead of 3, making it 1 tile is punishing noobs who haven't memorized the maps

**Comment by 13spacemen** [comment]
> > it's harder to make EMPs, chemnades, **TTVs** on TG to counter syndie teleports
> 
> sorry what? you're expected to use a TTV to counter this item?

No, the official counter is EMP since EMPing disables safety teleports and makes them instagib if teleported into a wall
I just listed TTVs and chemnades as 'counters' since those counter everything by blowing up/burning many tiles

My point is, making lethal instakill stuff to fight antags is much harder on TG since TGchem has the confusing purity pH buffer stuff, and for TTVs making a proper maxcap is more involved than on other servers where you can maxcap with a roundstart freezer/heater plasma oxy

**Comment by optimumtact** [comment]
This thing is overdue a nerf and this looks reasonable to me melbert

**Comment by Fikou** [comment]
lets see how it goes with the fix being merged

**Comment by Colovorat** [comment]
Played against traitor abusing it, it was just impossible to catch them, absurdly OP thing

**Comment by moocowswag** [comment]
Ive yet to actually see this thing in action and now im curious, what exactly is it doing that makes you go "Yep thats broken?"

Like is it too good at keeping their user alive? Are they too mobile? Does it let them get into and out of secure areas too quickly?

A combination of these things?
 
Its really interesting to see mobility recognized as a meta along with the untapped potential that is a combination of the hand tele/circuit launchpad/quantum spin inverter/lumi slime person.

**Comment by Pickle-Coding** [comment]
> > Ive yet to actually see this thing in action and now im curious, what exactly is it doing that makes you go "Yep thats broken?"
> 
> 
> 
> 
> 
> the ability to go in and out of places instantly, avoiding all other mechanics like hacking or whatever that may leave prints or something to go off and the ability to instantly escape very dangerous shit by getting an abnormal amount of distance in a second to the point where fighting you is absolute cancer as long as youre not unlucky as shit and get a charge in (and thats assuming you already spent all your charges (you have FOUR of em))
> 
> 
> 
> bs crystals are fine because they are clunky and uncontrolled, and a technically limited source
> 
> 
> 
> to be honest, i think the item is very flawed from the get go, with its upside being "you can now escape every single thing and get into anywhere" and its downside being "you instantly gib lol" without any interaction. feels very frustrating and unsatisfying for everyone.

It's even stronger and more reliable than the wizard blink spell, lol. No idea how it ever got merged.

**Comment by moocowswag** [comment]
Oh so its really consistent and has very little downtime, kinda like void heretic but post ascension (arnt your cooldowns reduced post ascension?)

So it ends up giving off very small / non existent windows for others to attack them correct? Well thats always gonna be sort of the case since its usually very easy to evade people after you break line of sight 

so im wondering if this nerf isnt hard enough, in the future maybe require you to just manually recharge it at an apc.

**Comment by Fikou** [comment]
> Safety range from 3 to 1 might be a bit much if I understand it right. The teleporter has a 4-8 tile range, so even if you're quite cautious there's a very good chance RNG sends you into a wall. Would make the item a pretty hard sell if there's even a 5% chance using it gibs you, with relatively cautious usage, especially for 8 TC.

it was bugged and did a radius around the safety range, which is why the 3 was insane. that one is fine now probably

**Comment by san7890** [comment]
Please ensure that this PR is about where you want it to be as far as nerfing stuff and undraft.

**Comment by AlamoTurtle** [comment]
I want to see absolute madmen traitors have their murderbone stopped by telefragging themselves into a wall like a Spelunky speedrunner, lol. Good changes.

**Comment by Zevotech** [comment]
As someone who uses this item a lot and has played against it a few times, PLEASE MERGE THIS DEAR GOD ITS TOO POWERFUL. You get infinite, mostly consistent instantaneous teleports that go in a perfectly straight line. No other teleport item does this, even the modsuit teleporter takes some windup and effort to make. Sec's only counterplay is miraculously appearing where you're teleporting and hoping you gib yourself. EMP's being the only way to affect it also sucks, because sec shouldn't have to make and use EMPs that fuck up the station just to HOPE to catch a traitor with a powerful item.

**Pull request closed without merging**
