### PR TITLE
Syndicate Base Fixes

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
-Can now use the toy guns in the range
-Can now use the doors
-Adds uranium to viro
-Divides monkey pen up into four rooms so you dont have to infect them all with one disease

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
speed merge please fucking please i haaaate being limited to ass viruses

**Comment by PKPenguin321** [comment]
Add a bunch of m2h DNA injectors

**Comment by ma44** [comment]
It would also be recommended to add a huge water tank, a bucket/beaker and a vending machine full of monkey cubes so you can have unlimited monkies to play with. You can also modify the machine to have uranium or something so syndicate don't run out of supplies.

**Comment by GunHog** [comment]
Similar to the mutagen dispenser? Yes. While you are touching the map, could you give the viro a pair of Science goggles, or varedit the MedHUD to have scan_reagents = 1? When experimenting with virus chem mixes, I kept getting confused about what I made, and had to go across to the chemist to identify my mixes. 

Although, if you go with ma44's idea of a dedicated dispenser for the base virus chems (virus food, silver, gold, plasma, and uranium), my concern would also be covered!

**Comment by RandomMarine** [comment]
How about instead of a magic dispenser of infinite plasma and uranium, the syndies get a lavaproof drone or borg to go fetch the materials that surround their base?

With custom laws to dictate that goal and keep it from fucking off to validhunt, of course.

**Comment by FantasticFwoosh** [comment]
@RandomMarine holding onto that thought, why don't the syndicate scientists construct the drones (using a robotics lathe with some disks to get the parts in the room as loot) and then they or the telecomms officer remotely pilot the (ash and lava proof) drones.

> Reasonably saying that instead of a ORM the scientists can just use the chem lab to make infinite welder fuel & use a welding mask from the reinforced test lab/ a later built autolathe?

Put four chairs and consoles in the tcomms room for these consoles (so that each ghost role can play when the parts are ready for new drones) and mine for resources that way.

**Comment by KingPhilipIII** [comment]
Remember, this is a tutorial for virology and chemistry. Not The Syndicate Experience: Lavaland Edition.

**Comment by FantasticFwoosh** [comment]
Then it should be inclusive to using those tutorials in a at least applicative way, build chem bombs to mine and uh give yourself self respiration diseases rather than push a workplace in your face and say **Safe Space go play with these toys while the REAL cool kids go play on the station using the chems**

> Golems/Plantpeople (plant-people rarely) dont dig and grow stuff to put inside a display case and say (I know how this works now, i can suicide) they continue with what they were doing and learn via application of the skills they learnt in order to reap the rewards, using a mixture of plants to live outside etc and golems building R&D and actual structures.

> I was only trying to suggest a side activity and somewhat cruicial activity for the ops to do relevant to their need for raw materials (glass/metal/minerals etc) in order to be sustainable with the whole testlab-viro focus.

I make a similar arguement here for bartending ruins that are not central to the ruin mechanic but just to RP needlessly as the whole point of the ruin - https://tgstation13.org/phpBB/viewtopic.php?f=10&t=8700

**Comment by KingPhilipIII** [comment]
I mine as a plant person using space tobacco and exploding lemons.

**Comment by XDTM** [comment]
Real vault podpeople use aggressive spreading kudzu to mine

**Pull request merged**
