### PR TITLE
Day Who-Knows: Bar Gambling Expansion!

### PR DESCRIPTION
**Pull request by Cheridan**
Ordered by Miggles!

EmbedYourFuckingImagesCheri

Bartender gets a nice poker table and a deck of cards. He also gets a nice secure safe with some bills in it.

Space cash converted to stacks.

### CODE REVIEW

**Comment by as334** [comment]
Not a fan of the cafeteria tables :-1:. Couldn't you have just left the tables the way they are and only changed the bar?

**Comment by Cheridan** [comment]
But it is a cafeteria, though. If I left the tables where the where then there would be chairs right next to stools which doesn't look as nice to me.

**Comment by stapler2025** [comment]
If it's a cafeteria then we should remove the open to the hall of the kitchen

**Comment by Nienhaus** [comment]
I really like the idea. :+1:

**Comment by as334** [comment]
What stapler said. I don't think I've ever seen a cafeteria that only sells booze.

**Comment by Cheridan** [comment]
@stapler2025 I do like the sound of that, people eating in the bar rather than out in the hallway, but I don't know if people will go for it.
I mean, the whole point of the door between the kitchen and the bar is so that the service crew can take orders and serve up food but that isn't really how people tend to play.

**Comment by drynwyn** [comment]
>Space cash converted to stacks.

You sir are a true hero.

**Comment by Chocobro** [comment]
why is the poker table poking out towards the bartender's space? it looks odd to me.
:+1: either way

**Comment by Nienhaus** [comment]
It's a good place for where the bartender can play his own cards, like blackjack.

**Comment by Anonus** [comment]
Put an extra vent and an extra scrubber in the bar area, it should have two of each, given its size.

**Comment by tedward1337** [comment]
Is space cash ever going to be expanded on in the future? Is it going to have an actual use?

**Comment by dannno** [comment]
economy when

**Comment by Atskadan** [comment]
also he needs a casino guy outfit like d'arby

**Comment by phil235** [comment]
looks good :+1:

**Comment by Cheridan** [comment]
@Chocobro It's a good spot to put poker pots, the dealer's hand etc etc where the players across the table can't grab them.

**Comment by Jordie0608** [comment]
Is this good to go?

**Comment by Atskadan** [comment]
no he need a fancy red vest cheridan pls ;_;

**Comment by Cheridan** [comment]
I'll add the vest in a second PR that'll be less likely to conflict.

**Comment by Chocobro** [comment]
@Nienhaus @Cheridan oh right i always forget about blackjack because it's a Terrible Game

**Comment by Atskadan** [comment]
:heart: thanks ~~steely~~ cherry dan

**Pull request merged**
