### PR TITLE
Deletes paper/openhelp

### LINKED ISSUE #24789: openhelp for paper
The proc /obj/item/weapon/paper/proc/openhelp(mob/user) in code\modules\paperwork\paper.dm doesn't seem to be used at all in the entire project. That should be fixed by adding a verb to the paper for showing new players on how to write cooler stuff on paper.

### PR DESCRIPTION
**Pull request by Cyberboss**
Closes #24789

### CODE REVIEW

**Comment by RemieRichards** [comment]
No.
no object verbs.
no browse()ing UIs.

**Comment by Iamgoofball** [comment]
I'm not using tgui until it compiles properly again fuck that noise

**Comment by RemieRichards** [comment]
nobody's saying tgui you nitwit.

**Comment by AnturK** [comment]
Doesn't really solve the issue with bbcode not being documented ingame. Some minimal template with ? icon in a corner wouldn't hurt.

**Comment by Davidj361** [comment]
Why not just create a help verb instead?

**Comment by lzimann** [comment]
Is it markdown paper time?

**Comment by Cyberboss** [comment]
Ahh, w/e. Job got too complicated.

**Pull request closed without merging**
