### PR TITLE
Swarmer lights are cyan

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Swarmer lights are coloured cyan.
/:cl:

image

### CODE REVIEW

**Comment by JJRcop** [comment]
Embrace the colored lights, they are the beginning and the end of all.

**Comment by InsaneHyena** [comment]
This is getting out of control

**Comment by XDTM** [comment]
the color revolution can not be stopped

**Comment by MMMiracles** [comment]
every light in the game needs a unique color tint or else we aren't fully utilizing the new lightning visuals.

ravestation13 when?

**Comment by Cyberboss** [comment]
There's a lot of glowy shit in space, OK?

**Comment by ShadowDeath6** [comment]
swarmers will most likely not ever turn on their lights because it's a dead giveaway that there's a swarmer in a room if you see the light

**Comment by coiax** [comment]
Except it actually makes sense that swarmers would be blue, because their whole colour scheme is blue?

**Comment by coiax** [comment]
>swarmers will most likely not ever turn on their lights because it's a dead giveaway that there's a swarmer in a room if you see the light

except when it's dark. Swarmers need light too.

**Comment by ExcessiveUseOfCobblestone** [comment]
big swarmer nerf, which is a plus because they're side antags and obnoxious!

**Comment by coiax** [comment]
But.. how is it a nerf? If the room is already lit, they wouldn't use their light, and if it's dark and they use their light, they're spotted anyway?

**Comment by coiax** [comment]
IT's JUST COLOURED LIGHTS, THEY ARE COOL

**Comment by ShadowDeath6** [comment]
Because it's a dead giveaway and people come in guns blazing rather than thinking "that could be a flashlight"

**Comment by XDTM** [comment]
glowsticks are already metabreakers there tho

**Comment by Aloraydrel** [comment]
When has that ever been the case?

**Comment by Cyberboss** [comment]
Now

**Comment by coiax** [comment]
@GunHog HELP MY PR IS BECOMING CONTRAVERISAL

**Comment by GunHog** [comment]
Just do not add fuel to the fire! Consider any constructive feedback carefully!

**Comment by ExcessiveUseOfCobblestone** [comment]
> glowsticks are already metabreakers there tho

I don't recall a cyan glowstick?

**Comment by PKPenguin321** [comment]
Tfw we get a new lights system and you people are already using it as a way to nerf things subtley

**Comment by GunHog** [comment]
I do not think anyone (except the people reducing the range of the lights) means to use it as a nerf! It looks cool, it does not have to go beyond that.

**Comment by PKPenguin321** [comment]
Oh yeah guys very specific colors for very specific antags that you can see from almost a full screen away and through walls isn't a nerf it just looks cool thanks for clearing that up gunhog

**Comment by KorPhaeron** [comment]
Swarmers are OP anyway they can suck it up

**Pull request merged**
