### PR TITLE
Nerf Irish Car Bomb clown car effect to throwing out all the mobs, without a big explosion

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Frankly this is what I had in my head for the original PR but didn't spend too much time on it

## Why It's Good For The Game
Currently gibs everyone inside the clown car, which sucks considering this is always non-antagonists doing it, also not what I expected it to be when I merged it 

## Changelog

:cl:
balance: The Irish Car Bomb + clown car interaction has been nerfed from a big gibbing explosion to throwing out all the mobs (with the usual chance of spilling out slipping foam)
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
The foam isn't in this video, but it did before

https://user-images.githubusercontent.com/35135081/143814246-427aa678-0e1a-4ec5-a0b1-6e4987a17ea7.mp4

**Comment by moocowswag** [comment]
Does this damage the car? And does it purge the irish carbomb from the people that get knocked out of the car? because i can see clowns getting chain knocked out of it.

**Comment by JohnFulpWillard** [comment]
I had an idea for it that I never got around to actually making, basically Ticking sounds start to play, then everyone in the car (except the clown) would yell about a bomb, before all jumping out and the clown car blowing up, not a big explosion either, probably the same as the clown car just being destroyed.

**Comment by Likteer** [comment]
If someone was upset over easy gibbing, why not reduce explosion power, instead of turning it into a **"hmmm, today I shall kneecap myself"** interaction?

**Comment by Mothblocks** [comment]
> Does this damage the car?

Yes but not really

> And does it purge the irish carbomb from the people that get knocked out of the car?

Yes

> If someone was upset over easy gibbing, why not reduce explosion power

It was me that was upset about easy gibbing and it's because it's not what I wanted anyway

**Comment by realthomas69** [comment]
Yeah the irish carf bomb is really OP and leads to innocent people being gibbed by nonatnags but its so funny i mea nits hilarious every time i see it so pleas do not remove or iw il lcry :(

**Comment by Likteer** [comment]
Hmmm... maybe delay the explosion and throw people out when the timer for it starts?

**Comment by Krysonism** [comment]
This just turns it into a risk free hard counter for a 20 tc item. Awful

At least with the old interaction, you had to give up your life.

**Comment by D4C-420** [comment]
I still believe that the having the car bomb effect only activating at over 800u of Irish car bomb in a person is still the best way to balance it. A impossible amount to drink making it rare enough that it would be funny when it does happen while being hard enough to do that you can't do it every time a car shows up .

**Comment by SuperNovaa41** [comment]
> This just turns it into a risk free hard counter for a 20 tc item. Awful
> 
> At least with the old interaction, you had to give up your life.

yeah but keep in mind you're not just killing the clown and yourself, you're also most likely round removing a load of non antagonists (as a non antagonist)

**Comment by Toastgoats** [comment]
Does it still display a warning that the effect is about to happen? There should be a way to catch it early and eject the carbomber.

**Comment by optimumtact** [comment]
twisted

**Pull request merged**
