### PR TITLE
increases toolbox size :D

### PR DESCRIPTION
**Pull request by dannno**
@PKPenguin321 let us break bread and make ammends

### CODE REVIEW

**Comment by kevinz000** [comment]
ehhh pretty good.
lmao the difference 4px makes.

**Comment by jughu** [comment]
Stop adding depth to my 2d game

**Comment by Haevacht** [comment]
:SMUGAWOO:

**Comment by RemieRichards** [comment]
AWOOSMUG

**Comment by Metallusions** [comment]
The one instance where 'remove don't improve' is applicable

**Comment by Haevacht** [comment]
No meta fuck you.

**Comment by Cheridan** [comment]
enlarge YOUR toolbox in only 3 easy steps

**Comment by RemieRichards** [comment]
@Cheridan engineers LOVE him!

**Comment by dannno** [comment]
:smile:

**Comment by YourNeighborsObnoxiousCat** [comment]
wew

**Comment by gt33** [comment]
TESTMERGE THIS

**Comment by dannno** [comment]
what do you boys think

**Comment by CosmicScientist** [comment]
Two looks like hinges. One looks like a latch.

**Comment by ChangelingRain** [comment]
the single latch design is more familiar but the double latch is sturdier

**Comment by CosmicScientist** [comment]
Nanotrasen isn't known for good design.
Familiarity makes it easier to recognise.

Oh that's an interesting word, familiarity. I'll just leave that there...

**Comment by WJohn** [comment]
I'll go with single latch, personally.

**Comment by RemieRichards** [comment]
Yeah one is better.

**Comment by dannno** [comment]
I am inclined to agree, my friends.

**Comment by dannno** [comment]
I have changed it to a single, powerful latch!

**Comment by cedarbridge** [comment]
Single latches are for tackleboxes.  We aren't fishing here, nerd.

**Comment by dannno** [comment]
You can't comment at this time — your comment cannot be blank.

**Comment by Ausops** [comment]
>Single latches are for tackleboxes. We aren't fishing here, nerd.
>toolboxes being used for anything other than fishing for valids

**Comment by PKPenguin321** [comment]
oh~ them single latch large toolboxes

yes do it

thank you very good compromise right here

**Comment by PKPenguin321** [comment]
although in all fairness another poll is probably in order

**Comment by dannno** [comment]
nope stfu

**Comment by Iamgoofball** [comment]
We need a poll for that poll.

**Comment by dannno** [comment]
ask the poll director about it

**Comment by PKPenguin321** [comment]
wait danno did you put the single latch ones on the PR

**Comment by dannno** [comment]
yes

**Comment by PKPenguin321** [comment]
sick

**Comment by dannno** [comment]
thanks man :))

**Comment by MrStonedOne** [comment]
Replace the image in the op please kthk

**Comment by KorPhaeron** [comment]
toolboxes dont have 2 latches in ss13

what the fuck dano

**Comment by chanoc1** [comment]
this good. also single latch 4 lyfe

**Comment by dannno** [comment]
aaaaaaaahahahahahha ahah ah ahhahahahahahhaha

**Comment by Armhulen** [comment]
WOAH WOAH WOAH WOAH WOAH.

HOLD THE FUCK UP WHY DID YOU EDIT HIS GRACE TO HAVE RANDOM RED PIXELS ON IT. STOP.

**Comment by Cheridan** [comment]
50% chance of double or single latch, with latches applied via overlay

**Comment by Cheridan** [comment]
2% chance of rare fabled triple latch toolbox

**Comment by Armhulen** [comment]
fix his grace's sprites and then i'm 100% on board

**Comment by kevinz000** [comment]
actually i take it back i like old ones better this is too goon.

**Comment by Kromgar** [comment]
So how the hell is this decided which gets merged/reverted? Does Wjohn make the decision?

**Comment by ChangelingRain** [comment]
Don't worry about his grace, I'll deal with that.

**Pull request merged**
