### PR TITLE
Makes regular Sandwich more nutritional than grilled cheese

### PR DESCRIPTION
**Pull request by SIX10**
## About The Pull Request
This makes the regular sandwich option, with meat and lettuce, more nutritional than grilled cheese. This makes it more realistic since meat and lettuce is better than just cheese and bread. Old Nutritional values were:
Grilled Cheese: Nutrition: 7, Vitamin: 1
Sandwich: Nutrition: 6, Vitamin 1

New values are:
Grilled Cheese: Nutrition 6, Vitamin 1
Sandwich: Nutrition 7, Vitamin 1

## Why It's Good For The Game
Adds more realism and makes more sense because grilled cheese is for poor people

## Changelog
:cl:
tweak: swapped nutrition values for sandwich and grilled cheese
/:cl:

### CODE REVIEW

**Comment by Grazyn** [comment]
Meat: 143 kcal/100 g
Cheese: 402 kcal/100 g

**Comment by Angustmeta** [comment]
Tbh the entire food table could use a rebalance. Some higher effort stuff like pies and pastries suck compared to bread, burgers, pizza and such.

**Comment by tralezab** [comment]
If we dont have a system like the bar drink quality for food, we should

**Comment by SIX10** [comment]
> 
> 
> Meat: 143 kcal/100 g
> Cheese: 402 kcal/100 g

Meat Protein: 26 g/100 g
Cheese (cheddar) Protein 25 g/100 g

**Comment by Tlaltecuhtli** [comment]
f o o d b a l a n c e

**Comment by tralezab** [comment]
I want a balanced diet

**Comment by Therapist1** [comment]
Regular sandwich: less nutrition, more vitamin, Grilled cheese: more nutrition, less vitamin

**Comment by Potato-Masher** [comment]
> Regular sandwich: less nutrition, more vitamin, Grilled cheese: more nutrition, less vitamin

**Comment by Angustmeta** [comment]
> f o o d b a l a n c e

Not with that attitude

**Comment by Farquaar** [comment]
I was working on a food balance sheet, but got sidetracked with IRL stuff.
Might finish it in the future though

**Comment by Grazyn** [comment]
>Regular sandwich: less nutrition, more vitamin, Grilled cheese: more nutrition, less vitamin
^ this 

@SIX10 I've always assumed that nutrition refers to calories since you literally get weaker the less nutrition you have (yes you'd get weaker from protein imbalance as well but it would take much much longer time)

**Comment by SIX10** [comment]
> 
> 
> > Regular sandwich: less nutrition, more vitamin, Grilled cheese: more nutrition, less vitamin
> 
> ^ this
> 
> @SIX10 I've always assumed that nutrition refers to calories since you literally get weaker the less nutrition you have (yes you'd get weaker from protein imbalance as well but it would take much much longer time)

I mainly thought "Nutrition" refered to nutrients, which calories aren't apart of (since they are a unit of energy). Wikipedia shows nutrients are fats, carbs, protein, water, etc.

**Comment by Tlaltecuhtli** [comment]
vitamins give nutrition

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
