### PR TITLE
Reduces heart decay, ear damage slightly less bad

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Prerequisite to #48668 

Current heart decay leaves it at completely dead after 3 minutes. requiring surgery before defibbing. Increases that timer to a little under 4 minutes. I don't want to be too heavy handed with this one, as we have a surgery to fix it. This simply extends the time you have to work on someone off stasis before requiring full clothes off surgery, which often requires you to go to the operating theater causing further organ decay.

Also reduced the chance of ears ringing when damaged by 1/3, this has always seemed to happen a bit often, and a bit early.

Defib timer is gone, as is the defib hud icon since all corpses are now defibbable. Also makes fakedeath more convincing since it was missing it.

## Why It's Good For The Game
Allows for more easily reviving people without having to do fully fledged surgery, which is a common reason for cloner use.

## Changelog
:cl: Skoglol
balance: Reduced heart decay, effectively extending the defib timer slightly to a little under four minutes before requiring heart surgery.
balance: Slightly reduced the probability of ear damage causing you to intermittently go deaf.
tweak: Defib timer is gone, its all organ decay now. The defib hud icon is also gone since any corpse is now defibbable, also making fakedeath a bit more convincing. 
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
can_defib() currently checks for the heart's time of death and not organ health:
https://github.com/tgstation/tgstation/blob/f94fb3f5789d57e444db840fa787d5a36117d542/code/game/objects/items/defib.dm#L463-L468

**Comment by kriskog** [comment]
It does both, search do_help for heart.organ_flags & ORGAN_FAILING which is applied when it reaches max damage.
tlimit is 15 minutes, so doesnt get hit for a long time after the heart itself fails.

**Comment by 81Denton** [comment]
Dang, my bad.

**Comment by ExcessiveUseOfCobblestone** [comment]
It should only do decay AMA

**Comment by kriskog** [comment]
Cut the time limit? It doesnt do much anymore, I agree.

**Comment by CRITAWAKETS** [comment]
Why are you putting the ear damage thing in the same PR? It had nothing to do with cloning so just atomize.

**Comment by kriskog** [comment]
This is an organ decay rebalance PR, the ear is an organ.

**Comment by kriskog** [comment]
Okay, I killed the defib timer. At the same time, the defib hud icon also wont show, and fakedeath will be a bit more convincing.

**Pull request merged**
