### PR TITLE
[NO GBP]Material Container Patches & Related UI Fixes

### LINKED ISSUE #72096: Deconstructing ancient protolathe (derelict drone station) destroys materials?
When playing as a drone I wanted to upgrade the lathe before printing more, but deconstructing it seems to just vanish the materials it contains? It wasn't linked to an ore silo yet.

## Round ID:
Hmm sadly can't find the exact ID now

## Reproduction:

Go KS13, build ancient protolathe, stick some materials in, destroy it (before linking it to silo), materials don't pop back out.

### LINKED ISSUE #76151: You can't print things if you have just enough materials
## Reproduction:

Found this after materials rebalance, not sure if this only bs crystals.
Screenshot_165

### LINKED ISSUE #76253: all materials are greyed out in the exosuit fab
## Reproduction: caused by the material refractor stuff 
Screenshot_674

### LINKED ISSUE #76506: RCD silo link consumes excessive material
## Reproduction:

Build, for example, a 10x6 space room using a silo-linked RCD, with the silo containing around 1300 sheets of metal. Not that even just putting down the floors and walling it off will take more resources than the silo has.

I suspect something wasn't changed with the PR that reduced sheets from 2000 material to 100 material, and the RCD is still consuming as if 1 sheet = 2000 silo material.

### PR DESCRIPTION
**Pull request by TommyVinseti**
## Note:  
The original author of 76220 has given me permission to use their branch to create a new PR from it. 

I am not sure why he was banned nor do i care nor judge from it.

Labelling this as NO GBP because i don't want to take credit for his hard work. This fixes RCD silo link and other related stuff which i as an engineer find very useful so i just want this in game that's all

Not that well versed in this codebase, so any reviews on a large PR like this might take some time for me too understand so please bear with me if I'm slow to respond.

Anyway now time for copy pasta

## About The Pull Request
**1. Material container clean-up & refactor**
 
* Replaced `total_amount` var with `total_amount()` proc, this var can be easily computed by summing up all material amounts rather than storing it as a var which is tedious to update & keep track of when materials are added/removed
* Removed unused  procs `transer_amt_to()`, `can_insert_amount_mat()`, and `get_categories()`. These procs are not used anywhere in the codebase so let's remove them & make some space.
* Callbacks are replaced with signals, the callbacks don't need to be explicitly garbage collected & having macros & procs marked with `SIGNAL_HANDLER` makes your intentions more readable & explicit.
* 76151
All material adding, removal, checking operations are "Integer" operations, i.e. the final value is rounded & them made 1 if the final value is 0 using the macro `OPTIMIZE_COST`[coudn't come up with a better name]. No more dealing with decimal value materials
The problem was after the protolathe was upgraded with better parts all the design costs were multiplied with a decimal `efficiency_coeff` value, this means even though in the UI the cost was displayed as 60 bluespace crystals its actual cost was `60.0001` something in the backend causing this check for materials to fail & print the error message.
* Replaced `GetComponent(/datum/component_material_container)` with just a simple ref to the material container when adding the component, so we can save some overhead from calling this proc
* Gave all procs a ton of documentation with documentation having documentation
* 76506 RCD and other devices that uses the silo link upgrade now have the correct material usages
* 72096. It wasn't just a problem with ancient protolathe but with all machines that used `datum/component/remote_materials`  the problem was remote materials would add an instance of   `datum/remote/material_container` if it wanted to use local storage but this component would get added before `datum/component/remote_materials` could be registered i.e. it comes before remote_materials in the component list. So when the machine is destroyed it will first destroy `material_container` & then `remote_materials` therefore destroying the materials before they could get ejected
* Drone dispenser will eject sheets upon deconstruction
* Moved this & remote materials into its own folder for better organization
 
 **2. Material UI Changes**
 
 * Removed the x25 & x50 print buttons from the autolathe, now they just have x5 & x10 buttons like the protolathe, These buttons were of no use since you could just type the exact amount you want to print in the `[Max: <some amount>]` side bar. The code to compute these buttons was just plain right nasty & some of it unused in the UI.
* The material eject button in the material bar does not gray out when you can eject exactly one sheet
*  All material cost are integer values rounded
* 76253 Exosuit Fabricator sends the material container static data to the UI so its material bar is not greyed out when there are sufficient materials to eject
* Component printer material bar sends the material container static data to the UI so its material bar is not greyed out when there are sufficient materials to eject
* Max printable amount of items are now computed & updated correctly in the UI. They were displaying wrong values & now get updated when items are printed, materials are removed
* Silo hold actually works now. When a machine is put on hold it calls this proc
   https://github.com/tgstation/tgstation/blob/e929cf39cded5207d63df1fa8521f41f2816b383/code/datums/components/remote_materials.dm#L78-L87
   
 Notice how the key is `src` so we should be consistent during checking if a machine is on hold using the same `src` var. But for some reason we did dumb shit like this
   https://github.com/tgstation/tgstation/blob/e929cf39cded5207d63df1fa8521f41f2816b383/code/datums/components/remote_materials.dm#L150-L153
   
   What is category? Why do we care for the area the machine is in? None of it made sense so i removed all that junk and just made it check for `src` like it should
 * Removed redundant `removable` & `sheets` var from the material container ui_data. These vars are unused in the UI
 * If an item does not have the required materials then upon clicking that item you will not get any error message but instead nothing happens
 
 ## Changelog
 🆑 
fix: items can be printed from autolathe & protolathe when the exact material amounts are present in them after upgrading
fix: max printable amount now shows the correct value & updates when items are printed, materials are removed in the autolathe & protolathe 
fix: the material eject button in the material bar does not gray out when you can eject exactly one sheet fix: exosuit fabricator material bar is not greyed out when there are sufficient materials to eject 
fix: component printer material bar is not greyed out when there are sufficient materials to eject 
fix: rcd and other devices that uses the silo link upgrade now have the correct material usages 
fix: silo hold actually works 
refactor: printing an item that does not have enough materials will fail silently with no error messages 
refactor: material container & remote materials moved into its own folder
refactor: material container callbacks now replaced with signals
refactor: removed `departmental_tag` var from all machines 
refactor: Drone dispenser will eject sheets upon deconstruction refactor: removed x25 & x50 print buttons from the autolathe 
refactor: All costs are integer values rounded refactor: store material container as a ref instead of calling `GetComponent()` all the time so we save some overhead 
refactor: replaced `total_amount` var in material container with `total_amount()` proc refactor: removed unused procs in material container 
refactor: removed unused ui vars `removable` & `sheets` from material container ui data 
refactor: all add, remove, check for mat operations in the material container are all ceiled(higher rounded) integer operations
 /🆑

### CODE REVIEW

**Comment by TommyVinseti** [comment]
> I am not sure why he was banned nor do i care nor judge from it.

Ok i lied. I know this is out of scope for this PR but i am curious cause he is a close friend of mine so If anyone has any answers that would be appreciated

**Comment by MTandi** [comment]
@TommyVinseti #76577

**Comment by TommyVinseti** [comment]
> @TommyVinseti #76577

Ok i see there is definitely a heated debate. My friend definitely started the arguments there is no defending that. Upon reading all the chats he seems to have ended on a good note in this comment https://github.com/tgstation/tgstation/pull/76577#issuecomment-1628919453 by apologizing to the other guy for being rude and https://github.com/tgstation/tgstation/pull/76577#issuecomment-1629411635 seems to have accepted his apology and finally My friend again seems understanding in https://github.com/tgstation/tgstation/pull/76577#issuecomment-1629463680 so it seem to all have ended on a good note

OHHH ok this comment https://github.com/tgstation/tgstation/pull/76577#issuecomment-1629541475 is where all the controversy started. I told him we would get in trouble for this, it's understandable why everyone was angry at him because it seemed like he was talking like a terrorist cause he had not explained the context in that comment as it was late night and he wanted to go to bed. I promise you he meant no harm to anyone and actually it was the exact opposite as i'll explain below.

This might be Cringe for many people i understand but if you want to understand the full story(which i will share now with his permission) without prejudice then please read carefully below

So a bit of a back story about me and my friend SyncIt21. Both of us are immigrants who settled in the US around 2017 i can't tell from which country for privacy reasons but we came from a rough neighbourhood, a Christian community where people would be persecuted hard. I'm talking about getting fired from your job for believing in the bible to getting lynched for preaching the word. Sadly he too was beaten for preaching the word in our early years but that did not stop him, he became even more bold and preached the gospel to everyone he met, even in his work place and he did get fired for it but that only embolden him.

Anyway both of us have been going to church together since 2018 and we both love talking about End times dreams, visions & prophecies. We always look at the latest news articles and talk to our friends about how the 2nd coming is at hand cause we just like it. Now with this information at hand let me tell you what specifically he was talking about in this comment.
Please don't ban me for posting these articles i am just doing this in his defence
[article1](https://tfiglobalnews.com/2023/05/31/11th-july-the-date-set-by-victoria-nuland-for-wwiii/)
[article2](https://www.reuters.com/world/europe/russia-ukraine-accuse-each-other-plotting-imminent-attack-nuclear-station-2023-07-04/)
As you can see he did not make any of this stuff up in his comment. He was actually talking about the latest news articles being published on this topic. Upon reading these articles he became frightened and wanted to preach about the bible even more to everyone he met more urgently which finally brings us too Why he said what he said.

I just finished talking to him now and he said in that PR he did not hate anyone, but in fact he liked everyone in the chat. After much heated debate and arguments he felt like he could personally connect with everyone there because of so much talking especially this @LemonInTheDark guy. He really talked nice about this 1 person because of how well he explained every decision in detail, In fact he felt really comfortable with this guy so as soon as he mentioned Jesus he felt like he could preach the gospel and everyone would be curious about he said.

And what happened after is that everyone did not understand him...understandably and they thought he was talking like a terrorist and called him mentally sick and everything. Poor guy i mean he even said this in his comment

>  I have told you the truth and nothing but the truth on my soul

He is sincere about what he said and he wanted everyone to look at the latest news reports and talk to him more about it. He really wanted to join the discord and just make friends with everyone there and talk about end times but he just could not find the link lol so he decided why not just use github comments to talk about this and understandably everyone mis-understood him.

@LemonInTheDark i hope you understand he did not threaten you or dislike you in any way. It's because he considers you a close friend that he thought he could preach about the bible and gospel to you so i hope you can forgive him for all this misunderstanding.

@optimumtact i understand if you don't want to unban him. He did definitely cross the line by talking about these things which are off topic but it was from a good place and he never wanted to offend anyone. Ultimately its upto you what happens next

**Comment by optimumtact** [comment]
It's not what he said, it's where he said it, it has nothing to do with the github and the PR's are not a discussion zone for anything that pops into peoples heads, especially current and political events.

if he can promise to keep his intrusive thoughts to himself and not put them in the github comments I don't have any problem with unbanning him.

**Comment by TommyVinseti** [comment]
> Also considering you created your account and showed up today, there is no reason to believe you are anything but an Alt for sync so please drop the act.

That's not fair. I understand people in the past have used this tatic but too accuse everyone of doing that is not right. I play the game on his local server on LAN so we about his PRs daily. Once he told he got banned I thought I could help him out by creating this account and that's the full story 

> It's not what he said, it's where he said it, it has nothing to do with the github and the PR's are not a discussion zone for anything that pops into peoples heads, especially current and political events.
> 
> if he can promise to keep his intrusive thoughts to himself and not put them in the github comments I don't have any problem with 

Thank you soo much I'll tell him this. Since he isn't on discord nor can he comment here is there anyway he can know if he is unbanned? Cause then he can apologize to you personally and I don't have to act as a proxy

**Comment by TommyVinseti** [comment]
> Thank you soo much I'll tell him this. Since he isn't on discord nor can he comment here is there anyway he can know if he is unbanned? Cause then he can apologize to you personally and I don't have to act as a proxy

@optimumtact thoughts?

**Comment by optimumtact** [comment]
is he going to keep his thoughts about politics to himself?

**Comment by TommyVinseti** [comment]
> is he going to keep his thoughts about politics to himself?

He does. No more politics or religion only on topic comments from now on. His reputation on this repo is damaged already because everyone said some uhh not so nice words about him so he will disappear from here for a while, he just wants to apologize, get his last 2 remaining PRs merged and then disappear.

He is very sawry about all this

**Comment by optimumtact** [comment]
they are free

**Comment by SyncIt21** [comment]
@optimumtact thank you soo much. I'm really sorry for all the misunderstanding I started,  Never again 

I like being open about my thoughts but being too open is never a good thing. I learnt a hard lesson on that 

I want to ask 1 last favor before I disappear regarding this 

> get his last 2 remaining PRs merged

Its actually 3 PRs. Can you be kind enough to reopen 
#76713
#76220
And finally 
#76516

These are my last 2 cents I want to contribute to this Repo before I go. I understand if I'm pushing my luck and you don't want to do this but umm. Pretty please?

**Comment by TommyVinseti** [comment]
Glad to see everything worked out. Since this PR is an exact duplicate in the above mentioned list there is no reason to keep it open.

Thank you everyone for being so understanding. Tommy Versiti over and out

**Pull request closed without merging**
