### PR TITLE
Updated: Reduces dominator timer ceiling, changes territory scaling

### PR DESCRIPTION
**Pull request by Robustin**
Old Max: 15m
New Max: 8m

🆑 Robustin
tweak: Gang Dominator max time is now 8 minutes down from 15m
tweak: Gang Tagging now reduces the timer by 9 seconds per territory, down from 12 seconds. 
/🆑

### CODE REVIEW

**Comment by CPTANT** [comment]
I would keep the new minimum at 3m. 2m is pretty short to react and dominator fights are fun, as long as they just don't drag on.

**Comment by optimumtact** [comment]
gang was removed

**Comment by Robustin** [comment]
@CPTANT 

I'll consider it but I believe that long timers are part of the cause for people AVOIDING dom fights by making the dominator almost impossible to reach.

Look at the average Nar'Sie (60s) versus Rat'var (8m?) summon. One gets done in a room with virtually no barricading, no walling, just a straight up brawl with anyone who shows up. The other gets plopped in the most defensible spots on the station, behind layers of r_walls and turrets and doors and the best strategy for winning a fight for your win condition is making sure the fight never really happens at all. 

Dominator falls into the latter trap because the timer is just too long for superior manpower and a solid position, people go overboard and have to make the thing AIRTIGHT because even having a large % of territories still gives someone enough time to craft a bomb from scratch and bring it to the dominator. 

Id like to see what kind of fights we get when the gangs don't feel like they need the dominator to be in Fort Knox before they activate it.

**Comment by ChangelingRain** [comment]
Ratvar's portal is a flat 5 after it has components, for ref.

**Comment by PKPenguin321** [comment]
A good change. 15 minutes was absolutely too much for a finale object, even if it rarely happened.

**Comment by KorPhaeron** [comment]
3 minutes is far too low when you consider R wall spam. It usually takes 3 minutes to even get people gathered up to go raid the target

**Comment by Robustin** [comment]
I mean it was 3 minutes before Kor.

I'm also going to make Doms require more open space. I'm also open to ideas for dealing with R_Walls.

**Comment by KorPhaeron** [comment]
Its late my brain isnt working

2 minutes will suck even worse

**Comment by ChangelingRain** [comment]
Maybe make dominators cause nearby walls to rust or something.
The min time should probably be like 4 minutes imo

**Comment by Robustin** [comment]
Kor I hate r_walls too but it's really an unresolved question as to whether lower times = less pressure to do stupid shit like r_wall the entire area. My experience with blood cult is that if the antags don't feel like absolute security is mandatory, then they don't do it. Laying down r_walls is almost as obnoxious as having to decon them so if people don't feel like they NEED to do it, then I think they'll be less likely to. 

I am putting up a Dom PR soon requiring X tiles of open space around the dom.

**Comment by PKPenguin321** [comment]
They kinda have that, C4

**Comment by PKPenguin321** [comment]
Now that I think about it I agree with kor about the minimum time thing, decrease the max but leave the minimum alone

**Comment by Robustin** [comment]
Fine, I wanted to see if a rapid dom time for the dominant gang would help reduce the fortress meta. If you don't want a gang putting out a fast dom, clean/replace any of the large amount of tags they need to hit that number. 

But it's not a big deal, people think 3m is a good floor so ill tweak the ceilling/scaling.

**Comment by Iamgoofball** [comment]
here's your logic path for dealing with rwalls

if wall is adjacent to a space tile(INCLUDING DIAGONALS), leave it
if not, turn that shit into plating

do this in a 7x7 area to ensure that there is no cheese

**Comment by Iamgoofball** [comment]
actually does atmos spread across diags? someone please check @duncathan

**Comment by Robustin** [comment]
@Iamgoofball 

I already did a 7x7 PR bro, its based on VIEW which works for me.

**Comment by duncathan** [comment]
Atmos certainly shouldn't spread across diagonals but it's hard to make promises about atmos behavior

**Pull request merged**
