### PR TITLE
Ports a slightly edited version of Eris APC sprites

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
imageadd: Ported CEV-Eris's APC sprites.
/:cl:

These are a slightly edited version with larger power indicators and somewhat adjusted colors.

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
I like this even more

**Comment by WJohn** [comment]
I've sent joan some updated sprites where the screens are brighter and more obvious, and has a few more lights to display whether the cover lock is active or not.

**Comment by AnturK** [comment]
Put up some screens how these look on walls please.

**Comment by MoreRobustThanYou** [comment]
@ChangelingRain i prefer the ones in the OP, but the new ones are kinda fine, too

**Comment by ChangelingRain** [comment]
they're the same ones, smart guy

**Comment by MoreRobustThanYou** [comment]
oh

**Comment by Shadowlight213** [comment]
They look extremely blurry. Looks terrible. 👎

**Comment by ChangelingRain** [comment]
Here is an improvement.

**Comment by Shadowlight213** [comment]
Still think there needs to be more contrast for the stuff on the screen.
Just a hunch, but I think that the sprite itself is trying to do a glowing effect, having the colors sort of spill over, leading it to look blurry, at least to me.

**Comment by WJohn** [comment]
You're right, shadow, that's what's happening. I was afraid the screen would appear too small, so I gave it a sort of light spilling out to the surrounding pixels. This DOES end up blurring it, but I think that's only the case for when it's charging (everything's blue). For red and green it looks quite fine.

**Pull request merged**
