### PR TITLE
Fixes some advanced camera issues

### PR DESCRIPTION
**Pull request by AnturK**
actions list was not properly maintained.

### CODE REVIEW

**Comment by Cruix** [comment]
The fact that all of these actions have their own variable seems to imply that they are kept track of well enough to not need an |=

**Comment by AnturK** [comment]
The whole list is redundant, i'm really not sure why it exists. I'll try to get rid of it later.

**Comment by AnturK** [comment]
Hmm, lot of boilerplate now.

**Comment by Cruix** [comment]
That is why it was made in the first place. I was sure the list also handled adding the actions, but apparently it was left this way to allow for special code or something.

**Pull request merged**
