### PR TITLE
Fixes the AI upload having no cameras

### PR DESCRIPTION
**Pull request by ghost**
Undocumented but brought to my attention by @GunHog. Verified in-game to have camera coverage.

### CODE REVIEW

**Comment by Cheridan** [comment]
tbh i like it better this way

AIs always be like "meeeh what laws are you uploading, whiiiiine whiiiiine"

**Comment by Fox-McCloud** [comment]
Kinda with @Cheridan on this one.

**Comment by pudl** [comment]
same with @Cheridan, the worst clause some shitler ever came up with is "BY NOT LETTING YOU CHANGE MY LAWS IM PREVENTING HARM xD"

**Comment by RemieRichards** [comment]
Silicon policy, silicon protections 6, read it folks.
tl;dr The AI is allowed to bolt it's core if it feels a law update coming from an individual would be harmful. (for example a Blood stained HoS carrying an egun can be denied from updating laws)

**Comment by xxalpha** [comment]
No, the cameras are required.

**Comment by Fox-McCloud** [comment]
@RemieRichards 

Pretty sure he'd still be able to bolt, just not see what they're doing while *in* the upload, itself.

**Comment by RemieRichards** [comment]
I bring it up as the only points raised against the cameras are that the AI would complain, where in the policies, *it has full right to complain and prevent it*

**Comment by Iamgoofball** [comment]
is it possible to config option this?

**Comment by Cheridan** [comment]
Config a stupid camera? No, not really. 

Anyway, the AI can still bolt the upload and use the turret controls, it has sight to the bridge.

Also at any rate, the red phone should get readded.

**Comment by Xhuis** [comment]
So you guys are complaining that one of the most sensitive areas on the station has no cameras, and then when I add the cameras, you complain that it shouldn't have any cameras.

Right.

Also @Cheridan red phone may be added in the future

**Comment by Fox-McCloud** [comment]
I think the reason why Cheridan is complaining (I know it is, for myself) is that AI's will literally keep perfectly reasonable requests from high ranking officials "just in case", which tends to lead to ONLY the Captain being able to ever tinker with the AI's laws.

Yes, it's reasonable to deny entry to a wide range of people in a lot of scenarios--but it's really shit when it's denying entry to the RD or Cap because "you MIGHT upload a bad law so I have to prevent it to prevent harm".

**Comment by xxalpha** [comment]
That's not a problem with the cameras.

**Comment by Dorsisdwarf** [comment]
The RD is supposed to be on-par with the captain for "just let him do it" unless the cap's told him not to, IIRC

**Comment by pudl** [comment]
it isn't a problem with the cameras, but it's a problem the cameras can fix.

**Comment by KorPhaeron** [comment]
Subverting AI is basically a round ender, it doesn't need to be any easier.

**Comment by pudl** [comment]
subverting ai is rarely a round ender, it takes some serious incompetence to not fix a subverted ai with ease

**Comment by xxalpha** [comment]
Removing upload cameras makes no reasonable sense.

**Comment by bgobandit** [comment]
If AIs are being unreasonable deal with it in policy, in the meantime, it makes literally no sense for one of the few blind spots in the camera network to be THE GODDAMNED AI UPLOAD.

**Comment by GunHog** [comment]
Please merge?

**Pull request merged**
