### PR TITLE
nerfs ion carbines

### PR DESCRIPTION
**Pull request by ghost**
This seemed to be a popular change I struck on. Changes the ion carbine so its projectile isn't a 3x3 ion, but rather the weakion that's in the ion buckshot.

:cl: vcordie
tweak: Ion Carbines no longer have a large aoe.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
Very popular.

**Comment by vcordie** [comment]
well, kor liked it.

**Comment by Haevacht** [comment]
Kev to be fair, this is the most popular PR vcordie has had.

**Comment by FantasticFwoosh** [comment]
Please stop trying to cause & effect justify your failed PR to ship high grade (even if nerfed) tier 2 ion's to the station without conducting the relevant research & mineral collection to print them off in R&D.

This isn't really constructive and removes whatever point of having advanced ion gun template in favor of R&D just printing off more regular rifles.

**Comment by optimumtact** [comment]
maybe you should touch some other things instead of ion related stuff for now

**Pull request closed without merging**
