### PR TITLE
Miner Style Points: Style on your enemies!

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Adds the style meter, it can be bought from the mining vendor for 1500 points, it is an attachment to your glasses.
The style meter creates a display on your hud, with your recent actions, like attacking enemies, killing them, mining ore etc. Actions like spinning or flipping increase your score multiplier, making you get more points.
Your style meter affects how much ore you get from mining rocks.
https://streamable.com/5afb3t

image

- [ ] More point sources
- [ ] Sound effects
- [ ] Cool effects from having high points
- [ ] Leaderboard

## Why It's Good For The Game

Makes miners bring more ore in a fun way.

## Changelog

:cl: Fikou
add: The mining vendor now has a style meter. This meter gauges your style points and uses them to improve your mining skills.
/:cl:

### CODE REVIEW

**Comment by castawaynont** [comment]
smoking sexy style

**Comment by Imaginos16** [comment]
BLESS ME WITH THE GIFT OF LIGHT

**Comment by MrDoomBringer** [comment]
actually legendary wtf

**Comment by TheBonded** [comment]
does the blood demon faunas crusher trophy increase your style points?

**Comment by Wallemations** [comment]
The one thing higher than SSS
Robust

**Comment by VladinXXV** [comment]
> does the blood demon faunas crusher trophy increase your style points?

please god make this a thing

**Comment by CCC23** [comment]
Amazing

**Comment by DaydreamIQ** [comment]
I'd like whatever the fuck you were smoking to come up with this idea, this is great

**Comment by Shadowflame909** [comment]
Something to surpass metal gear

Thank you fikou you cured my burn out

**Comment by D4C-420** [comment]
Station is Dead
Ore is meds
Lava land is full

Robust Mining

**Comment by ArcaneDefence** [comment]
Would you consider reaching the highest rank give an achievement so that can be tracked akin to other mining goals?

**Comment by waffielz** [comment]
gaming

**Comment by tralezab** [comment]
fikou's finally lost it

**Comment by RuneQuester** [comment]
BEHOLD, THE POWER OF THE NECROPOLIS

**Comment by CRITAWAKETS** [comment]
Something i do note is that the current iteration of the code has extra ore being generated in a low amount even at Dull. I guess it's better to be boring than to be forgotten.

**Comment by SarmentiCampbell** [comment]
It would be nicer to also be able to use the miner voucher to get one of those style meters

**Comment by MetalClone** [comment]
This is the heart and soul of /tg/station. Thank you for this great idea.

**Comment by red-creature** [comment]
this is a draft but i want it to be speedmerged

**Comment by Suspect-One** [comment]
What a creative and amazing way to make playing one job much more interesting. Thanks, Fikou!

**Comment by bluetshirtguy** [comment]
>making binds to spin and flipping 

no thanks

**Comment by CourageTheCat** [comment]
SWORDTRICKGUNROYALG-SWORDTRICKGUNROYALGUASWORDTRICKGUNROYALG-

**Comment by Cartlord** [comment]
What stops people from binding macros to the emotes this tracks (spinning, flipping, any others you may add) for infinite style? Perhaps make it so that, the more consecutive times you perform a single action, the less style you gain from it?

**Comment by TheBonded** [comment]
> What stops people from binding macros to the emotes this tracks (spinning, flipping, any others you may add) for infinite style? Perhaps make it so that, the more consecutive times you perform a single action, the less style you gain from it?

it should be less style per spin flip *on the same enemy*. spin flipping 80 times on one goliath isnt impressive, but spin flipping on every enemy you kill is.

**Comment by Fikou** [comment]
> What stops people from binding macros to the emotes this tracks (spinning, flipping, any others you may add) for infinite style? Perhaps make it so that, the more consecutive times you perform a single action, the less style you gain from it?

spinning and flipping makes you get dizzy and vomit and stunned (and take damage, which removes multiplier and style) respectively. also its a multiplier, not point gain.

**Comment by TheBonded** [comment]
> > What stops people from binding macros to the emotes this tracks (spinning, flipping, any others you may add) for infinite style? Perhaps make it so that, the more consecutive times you perform a single action, the less style you gain from it?
> 
> spinning and flipping makes you get dizzy and vomit and stunned (and take damage, which removes multiplier and style) respectively. also its a multiplier, not point gain.

it only makes you get stunned and dizzy and vomit if you do it too fast, you can easily wait the reuired second or so (about right after your character lands from the flip) to flip spin again with no conseuences

**Comment by Iamgoofball** [comment]
just make this built into miner loadouts tbh

**Review by tralezab — CHANGES_REQUESTED** [review]
I never finished this review but sure I'll throw it out now until I go back for a real one

**Comment by Coastfront** [comment]
Now we just need perfect judgement cut mechanics for mining for maximum style.

**Comment by RuneQuester** [comment]
No, now we just need parries, ricochets and PKA boosting.

**Comment by RuneQuester** [comment]
Also, do we get a list of everything that counts towards style, or do we have to figure that out ourselves?

**Comment by TheBonded** [comment]
> Also, do we get a list of everything that counts towards style, or do we have to figure that out ourselves?

figuring it out yourself is always fun but you can also always look through the code

**Comment by ilikesaying** [comment]
Gibtonite disarming maybe?

**Comment by githubuser4141** [comment]
Does it affect if you're mining with a mech? I hope this doesn't nerf mech mining even more.

**Comment by datorangebottle** [comment]
> Gibtonite disarming maybe?

geyser scanning mid-fight would be pretty funny.

**Comment by Palpetinus** [comment]
> Does it affect if you're mining with a mech? I hope this doesn't nerf mech mining even more.
> 
> Edit. Yes, mech mining is OP IF you're competent. 99% of players in-game will respond to you with "MEHSCS SUKK11!!" if you attempt to bring up the concept of using a mech to mine, however.

How is mech mining OP or good at all? A miner with a mining satchel of holding and an advanced plasma cutter can already nonstop mine at full running speed, so unless your mech is both faster than normal running speed and mining while it's moving without a single interruption, it won't ever be faster than a late game miner.

**Comment by TheBonded** [comment]
> > Does it affect if you're mining with a mech? I hope this doesn't nerf mech mining even more.
> > Edit. Yes, mech mining is OP IF you're competent. 99% of players in-game will respond to you with "MEHSCS SUKK11!!" if you attempt to bring up the concept of using a mech to mine, however.
> 
> How is mech mining OP or good at all? A miner with a mining satchel of holding and an advanced plasma cutter can already nonstop mine at full running speed, so unless your mech is both faster than normal running speed and mining while it's moving without a single interruption, it won't ever be faster than a late game miner.

@Palpetinus a ripley is faster than normal running speed on lavaland and can use plasma cutters + the drill mines in a 3x3, + they can pick up ores in a 3x3 radius around them. so yes, they are in fact better/faster than a late game miner 

the reason miners dont like to use mechs is because a mining oriented mech wont be very good for fauna combat (let alone megafauna combat) compared to a miner without a mech. most people play mining for megafauna fighting, which isnt feasible in a mech.

finally, a bit of nitpicking here, but a miner with a 2 cooldown 1 mining AoE upgrade is actually more efficient than a plasmacutter like you had references as an example, since with max mining skill a 2 cooldown PKA still mines as fast as the miner runs, but the AoE means it mines in a 3x3 per shot allowing you to clear out ore veins faster.

**Comment by githubuser4141** [comment]
> 

Also because after writing the first comment I get downvotes. I think hmm, maybe users on the github think mech mining is overtuned? So I write an addendum that should've appealed to people who think it's too powerful. Apparently that wasn't the issue? That being said since you can't combine a clamp, cutter and PKA anymore it's still easy to simply run away from most wildlife as they can't move very quick.

**Comment by TheBonded** [comment]
> Also because after writing the first comment I get downvotes.

not really downvotes, just people confused why anyone would legitimately use mech mining
 
> I think hmm, maybe users on the github think mech mining is overtuned? So I write an addendum that should've appealed to people who think it's too powerful. Apparently that wasn't the issue? That being said since you can't combine a clamp, cutter and PKA anymore it's still easy to simply run away from most wildlife as they can't move very quick.

I think the 'issue' was that most people play miner because they enjoy the fauna/megafauna killing aspects, and a mech not only is non ideal for that, but cant even utilize any of the loot from mining due to it being, well, a mech.

**Comment by tralezab** [comment]
if you wish to discuss mech mining, talk about it in the context of this feature being in the game, not just this massive random talk about the current state of mech mining which is really off topic.

**Comment by Sealed101** [comment]
some style actions ideas off the top of my head

- premauturely detonating gibtonite by priming it and hitting it again
- if miner modsuit bombs can be detonated prematurely the same way, then use that as well for a style action
- successfully performing burst attacks with the crusher or the resonator
    - bonus points maybe if rare crusher trophies are available
- slapping or circle bopping enemies
- butchering the enemy after the engagement (maybe more style speeds up the butchering?) for a big point boost and maybe a reset of the combo
- popping a legion core or an epen 


there are more on my mind but those would require additional features that would end up out of scope for this pr, like maybe parrying some projectile attacks with PKA blasts.

**Comment by catrock31** [comment]
please update this

**Comment by Fikou** [comment]
> please update this

im busy but in a few weeks probably

**Pull request closed without merging**
