### PR TITLE
i dont know what the fuck im doing

### PR DESCRIPTION
**Pull request by SamDDBS**
## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing thing
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by SamDDBS** [comment]
Conflicting files
html/changelogs/archive/2021-05.yml

fffffffffffffffffffffffffffffffffffff

**Comment by SamDDBS** [comment]
oh god oh fuck

**Comment by SamDDBS** [comment]
sorry :( im very bad at github

**Comment by SamDDBS** [comment]
dont mad at me :((((((((((((((((

**Comment by interestingusernam3** [comment]
clearly he doesn't know what the fuck he's doing

**Pull request closed without merging**
