### PR TITLE
[untested]Separate Double Agent Antag Preference

### PR DESCRIPTION
**Pull request by silicons**
Allows you to select if you want to be a traitor or a double agent or both, instead of traitor being a selection for both.
This uh SHOULD work but I can't actually test this with a test server of 1 person. Testmerge or tell me how maybe?

### CODE REVIEW

**Comment by Incoming5643** [comment]
The reason they use the same toggle is because if they didn't and you only had one on you could meta if you were a double agent or a traitor. 

The fact that people can't immediately tell that a DA round is a DA round is fairly intrinsic to keeping DA from being terrible.

**Comment by lzimann** [comment]
not like people won't figure out in 5 minutes that it's DA

**Comment by ChangelingRain** [comment]
DA is already terrible because it's twice~ the amount of traitors in one round and that's, uh, kind of wild.

**Comment by BeeSting12** [comment]
Any idiot can meta that its DA.

**Comment by kevinz000** [comment]
I meta it by seeing how fucked up the station is in the first 10 minutes
If it's half destroyed, yes, it's DA
otherwise it's tator tots :)

**Comment by KorPhaeron** [comment]
bad

**Comment by kevinz000** [comment]
@KorPhaeron Some people want to play traitor, or DA, but not both.

**Comment by Aloraydrel** [comment]
Why not just remove DA tbh

**Comment by Anonmare** [comment]
DA is me table by the number of objectives, that oughta be addressed as well but outside scope of the PR. I'm ambivalent though I'm of the opinion that anything that breaks meta is usually good.

**Comment by Shadowlight213** [comment]
If you're separating the prefs, then you should also revert hiding that it's DA from traitors, as it would then make the two completely separate distinct gamemodes instead of pretending that it's traitor.
Alternatively, we just do what aloraydrel suggested and remove DA.

**Comment by Archie700** [comment]
@Anonmare It's only metable in Basil.

Sybil has one objective for both DA and Traitor.

**Comment by kevinz000** [comment]
I dunno @optimumtact what do i do fam

**Comment by kevinz000** [comment]
On one side this caters to people who don't want to participate in a traitor deathmatch.
On the other side this kinda enables meta.

**Comment by Supermichael777** [comment]
YOU NERD YOU DIDN'T MAKE PREFERENCES

**Comment by kevinz000** [comment]
Isn't that automatic though?

**Comment by kevinz000** [comment]
@Supermichael777 that's automatic unless I need to do some savefile config editing ...

**Comment by RemieRichards** [comment]
@kevinz000 yes it's automatic, if it's in the special_roles list (which it is) it automatically gets a pref toggle in the menu.

**Comment by optimumtact** [comment]
why should we merge this if you didn't bother to properly test it

**Comment by kevinz000** [comment]
I can't test it as it requires more than 1 person

**Comment by optimumtact** [comment]
so phone a friend

**Comment by PKPenguin321** [comment]
when you're testing locally, log out of byond client once you're in the game and log into the server as a guest. bam, you can test on two accounts at once

**Comment by kevinz000** [comment]
i have no friends but i'l find a way to test this

**Comment by ExcessiveUseOfCobblestone** [comment]
just remove da :^)

**Comment by kevinz000** [comment]
not even worth effort

**Pull request closed without merging**
