### PR TITLE
Removes brains dropping from admin caused gibs and c4 suicide

### PR DESCRIPTION
**Pull request by Shadowlight213**
gibself dropping brains has been a complaint I've heard from other admins
admin gibbing a mob now brings up a prompt for dropping the brain.
c4 suiciding is going out with a bang, not leaving your brain behind to be borged and cucked.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
How does this interact with Gibself?

**Comment by octareenroon91** [comment]
Gibself has had `no_brain = 1` for some time apparently.

A dustself might be nice though.

**Comment by Shadowlight213** [comment]
@Dorsisdwarf it makes gibself not drop a brain, which it currently does. 
@octareenroon91 gibself has dropped a brain ever since the change that made all gibs drop brains by default.

**Comment by lzimann** [comment]
one step closer to remove gibbing dropping organs!

**Pull request merged**
