### PR TITLE
Horribly minor spawner edits, Maybe could include

### PR DESCRIPTION
**Pull request by ZombieTsar**
I play spawner roles too often, and I saw something that'd be nice to add, and I know how to half work the map editor.

*I added an extra sheet of glass and roll of cable to the Old Station   
(it always winds up being one short of both)
*WHOLE FLIPPEN BATHROOM TO OLD STATION
(forgot to add before)
*I added a grey slime extract at the verry end of the gauntlet of HiveMinds on Old Station
(I wanted some sort of progression after completing the gauntlet)
*I added an autolathe to the  Lifebringers vault
(so after a while they can eventually set up a base and spread (Still contemplating where (if I were) to put a science board)

[RUINS MODIFIED.zip](https://github.com/tgstation/tgstation/files/2608989/RUINS.MODIFIED.zip)

### CODE REVIEW

**Comment by subject217** [comment]
Lord almighty that diff.

You have to use the map merger tool to PR map edits on /tg/ station. Also this is a bad change, ghost roles are really supposed to be more like tutorials than something you do all the time.

**Comment by nicbn** [comment]
wrong repo dude

**Comment by Cyberboss** [comment]
Wrong repo

**Comment by ZombieTsar** [comment]
Ok, so I know this might not be seen, but I'm horribly new to community-driven projects, coding or map making, and Github as a whole, so I'm not surprised I screwed this up.

**Pull request closed without merging**
