### PR TITLE
Revert "Fixes movement on boxstation" and properly fixes movement

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/-tg-station#10813

Every airlock that leads to space has these signs, no need to remove one just because somebody doesn't want to properly fix a bug.

I also properly fixed it by removing the step_x step_y object variables manually via notepad++.

### CODE REVIEW

**Comment by WJohn** [comment]
Why not simply fix it in this very PR? It's a one tile change to the map.

**Comment by MrStonedOne** [comment]
>I'll edit the file manually to have it also remove the step_x/step_y

I'm working on that step

**Comment by Incoming5643** [comment]
I had an alterior motive as well: A sign on glass looked dumb to me, because you could smash the window and just leave the sign hanging on nothing.

Of course this is true of wall signs too, just vaguely harder to do by accident.

**Comment by MrStonedOne** [comment]
I don't like the idea of hiding in a change in a critical bug fix pr, know it will get quick merged.

You should know better.

**Comment by Incoming5643** [comment]
I ain't Jesus

**Comment by Incoming5643** [comment]
It was the most painless way of fixing the problem fast. The tile the sign was actually on was actually diagonal from where he wanted to place it, so I couldn't just open the map as a text file to fix it.

**Comment by Cheridan** [comment]
The sign should be there for consistency, if all other airlocks have it. If it's ugly on glass, maybe we can address that by making signs attachable/detachable or something (would be a cool addition for autismfort builders too)

**Comment by MrStonedOne** [comment]
sure you can, see the most recent commit @Incoming5643

**Comment by Incoming5643** [comment]
Ok but see now that sign will act like it's underneath the outer airlock, which means that there's positions you could stand where the sign should be logically visible but isn't because the inner airlock will be blocking it. In fact the sign doesn't really need to be pixel shifted at all, because it's on a transparent window, it could have just been put on the window.

This is a whole lot of nothing as far as points go but I'm just trying to show what happened here.

**Comment by Incoming5643** [comment]
listen can we just merge this so sybil can run boxstation again because apparently my fix isn't good enough to update to because a goddamn fluff sign is missing.

**Pull request merged**
