### PR TITLE
Morgue and Crematorium Resprite 

### PR DESCRIPTION
**Pull request by Chuckleberry-Finn**
Reattempting: #34757

:cl: Jittai
imageadd: New Morgue Tray sprites.
imageadd: New Crematorium sprites.
/:cl:

A continuation of: #2242 and improvement on: #12898.

lirijmh
morgyez

crema old
cerma2

### CODE REVIEW

**Comment by Jalleo** [comment]
I like the new cremator sprites.
One question for another PR if you want to do it. Could you make it so cremators and morgues can be rotated? AKA sprite different dirs for them.

**Comment by ChuckTheSheep** [comment]
I could work on that next, sure.

**Comment by Jalleo** [comment]
Would be great if you do.

**Comment by epochayur** [comment]
https://i.imgur.com/nBRucsN.png

**Comment by ACCount12** [comment]
Crematorium sprites are 👍, but the trays are meh.

You also fucked up your changelog entry.

**Comment by ChuckTheSheep** [comment]
I was considering removing the screens for now; could you clarify on the changelog?

**Comment by ACCount12** [comment]
Changelog lines are formatted that way:
`fix: Message.`
where `fix` is changelog icon ID and `Message.` is a changelog.

**Comment by ChuckTheSheep** [comment]
morgue2

I can edit out the screens for now and open another PR. I'm aware they're a bit different then what people are used to.

**Comment by ACCount12** [comment]
Also, crematoreum tray looks longer than the crematoreum itself.

**Comment by ChuckTheSheep** [comment]
Damn, now that's going to bother me...

P.S.: is there a place where the PR template that appears when you make a PR is written down? Or a guide on the shorthand for changelog?

**Comment by WJohn** [comment]
The new crematorium is certainly much more interesting looking, especially with how its door looks, while the regular morgue itself is not really much different at all from what we have now, and I hold no preference on either version of that, so it's fine with me if it gets added.

Overall, I think this is an improvement if mainly only for the cremator and for the slightly larger lights on the morgue.

**Comment by 81Denton** [comment]
I prefer the large morgue tray screen, it makes it easy to see the status at a glance. Especially on small displays.

**Comment by ChuckTheSheep** [comment]
I'm planning to make it a separate PR and maybe tweak them a bit more.

**Pull request merged**
