### PR TITLE
adds canvases to cloth recipes

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds canvases to cloth recipes

## Why It's Good For The Game

you cant craft canvases to make multiple of beautiful art and its sad

## Changelog
:cl:
add: you can now craft canvases with cloth!
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Beat me to it

**Comment by itseasytosee** [comment]
Beat me to it

**Review by AnturK — APPROVED** [review]

**Comment by Shirbu** [comment]
Speedmerge so we stop having to spawn these in for people. People really like canvases.

**Comment by Farquaar** [comment]
> 
> 
> Speedmerge so we stop having to spawn these in for people. People really like canvases.

Canvases can be ordered from cargo, IIRC
Also, it would make some nice detail if canvases also required a plank or two as well.

**Comment by Fikou** [comment]
> Canvases can be ordered from cargo, IIRC

i removed canvases from cargo when they were disabled so now when they are enabled again you cant buy them
sad

**Pull request merged**
