### PR TITLE
Better Blood Footprints

### PR DESCRIPTION
**Pull request by ghost**
Messier and overall better blood and oil footprint sprites from BAYSTATION TWELVE

UPDATED:
dreamseeker_2018

:cl:
imageadd: Bloody and oily footprints have new messier sprites
/:cl:

### CODE REVIEW

**Comment by DaxDupont** [comment]
Please show all of them ingame

**Comment by praisenarsie** [comment]
why are the xenos' footprints piss yellow

**Comment by Armhulen** [comment]
Gross I hate it jesus

**Comment by uraniummeltdown** [comment]
It's blood, it's supposed to look gross

**Comment by Spaceinaba** [comment]
looks too thick to be blood, like if it was gore specific footprints or something that would make more sense but just for regular blood its a bit excessive imo

**Comment by ShadowDeath6** [comment]
they look too similar to blood trails imo

**Comment by WJohn** [comment]
Please shift them down so the side sprites border the bottom of the tile, like in the old ones. These are back to the center.

Also, I believe these come directly from bay.

**Comment by WJohn** [comment]
Last thing needed is to change the color of the xeno bloody footprints to be a brighter/yellower color. You can see the major difference in color between the footprints and the blood puddle they originate from, and it's jarring.

**Comment by ChangelingRain** [comment]
these have a lot of color difference from the things they originate from in general

**Comment by chaoko99** [comment]
See, what's funny here is that I, a baystation dev, am literally in the process of porting your footsteps.

**Comment by DaxDupont** [comment]
@uraniummeltdown incharge of bad sprites

**Comment by PKPenguin321** [comment]
theyre porting our sprites so why do this is the question

**Pull request closed without merging**
