### PR TITLE
Removes devour mob verb and everything that uses it

### PR DESCRIPTION
**Pull request by BebeYoshi**
[Changelogs]: Removes devour mob verb, which is used by xenos and fat humans on monkeys, it also removes an action that is used when inside a mob stomach. This does not change morphs in any way since consuming is a core mechanic for them

:cl: BebeYoshi
del: Xenos can no longer devour mobs
del: Fat humans can no longer devour monkeys
del: Nanotransen stopped stomach escape training since that cannot happen anymore.
/:cl:

[why]: Devouring mobs is not a core mechanic to any of these mobs, and is just creepy. It also a known fact that this is also pretty strange fetish called "vore" which is very awkard in general.

### CODE REVIEW

**Comment by Jordie0608** [comment]
Xenos eating mobs is functional as a way for them to kidnap people and then ventcrawl back to a sealed off nest to get facehugger'd. This was added way back in 2011, initially only for hunters.
If you're going to remove that ability you should then also remove their regurgitate action https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm#L282

Fat people however I think is just a joke about Mr Creosote from Monty Python.

**Comment by BebeYoshi** [comment]
I will be sure to remove that as well. Xeno hunters already have ton of mobility and stealth ability and the infinite stun with disarm would be enough to bring some easy preys. The other xenos are supposed to stay together so it's also not useful to them.

**Comment by PKPenguin321** [comment]
This shits funny as fuck :-1:

**Comment by SpaceManiac** [comment]
legs are a fetish ,remove walking when

**Comment by Militaires** [comment]
removing the devour verb makes it 200% harder to establish a nest, just rename it to "Kidnap" and change its text and action icon

**Comment by Iamgoofball** [comment]
@Jordie0608 aliens also have an infinite ranged stun baton option and can still use pull/grab, I don't really see what they lose here aside from being able to ventcrawl with people which is kind of douchey to begin with and aliens are OP enough as is.

**Comment by Militaires** [comment]
goof, once you're a queen you're 100% vulnerable until you create even 1 hunter to bring hosts for you and defend you, if you're spotted before you make your nest you'll be overrun and killed. by removing this your force xenos to make their nest in virology every round

**Comment by Jordie0608** [comment]
@Iamgoofball I'm just explaining the mechanical use for xenos as contrary to the PR, wave your balance stick elsewhere.

**Comment by Iamgoofball** [comment]
we must not falter until a full xeno removal occurs

**Comment by Militaires** [comment]
just do what i said and rename it to "kidnap"

**Comment by Barhandar** [comment]
You should also change drake attack verbs because CANT LET FETISH CONTENT LIKE DEVOURING CORPSES BE IN THE CODEBASE OH NO

**Comment by BebeYoshi** [comment]
Drake can just devour corpses and as far as I know it deletes the corpse so it's not creepy at all, the creepy part is a living thing inside a player's stomach. You can still be alive as a ling inside a morph though, but as I said, it's a core mechanic and barely happens since the chances of having lings and morphs together and that one morph (simple mob) kills a ling is also rare. I don't feel like it should be removed.

**Comment by Grazyn** [comment]
Xeno event spawns >1 larvae so it should still be playable after this nerf. Any other instance of lone larva... not so much

**Comment by AdamElTablawy** [comment]
remove the curator's whip

obvious sexual connotations

**Comment by Cyberboss** [comment]
People can find anything to be triggered by

**Comment by Spessman42069** [comment]
Remove vomiting because some people are into that

Remove eating because some people are into that

Remove blood because some people are into that

Remove feet because some people are into that

Oh no, some people are into people that have missing limbs! Remove players

Remove clown car because some people are into cars and technically it vores you so...

Remove clowns because they're really fuckin hot and I just can't help myself with them around

**Comment by Bawhoppen** [comment]
Anyone can find _anything_ disgusting; vore isn't that special.

**Comment by subject217** [comment]
really funny how all the reddit downvotes showed up after this pr was already closed

**Pull request closed without merging**
