### PR TITLE
Adds trekchems to the Sleepers.

### PR DESCRIPTION
**Pull request by Iamgoofball**
requested by literally everyone ever

### CODE REVIEW

**Comment by Chocobro** [comment]
wait what i literally can't tell if this is a joke or not

**Comment by Iamgoofball** [comment]
it's not

**Comment by Dorsisdwarf** [comment]
!!!!!!!!!!!!!!!
Goofball learned a new move! Atomic PR!
It's super-effective!

**Comment by Shapsy** [comment]
Eh I think charcoal should be left in the sleepers since it purges chems in addition to healing toxin damage

**Comment by Iamgoofball** [comment]
@Shapsy so does anti-toxin

**Comment by Iamgoofball** [comment]
redoing gimme a sec

**Pull request closed without merging**
