### PR TITLE
Make fire alarm lighting respect power status

### LINKED ISSUE #66030: Fire alarms give off light, even if the APC is destroyed
Reporting client version: 514.1568

## Round ID:
[181196](https://scrubby.melonmesa.com/round/181196)

## Testmerges:
- [firelocks now automatically open once the alarms are cleared and fixed fire alarms not clearing](https://www.github.com/tgstation/tgstation/pull/65490)

## Reproduction:

- Be a scummy nightmare
- Destroy an APC
- The lights on all the fire alarms still shine red
- hit the fire alarms
- they no longer are lit

### PR DESCRIPTION
**Pull request by Tastyfish**
## About The Pull Request

Fire alarm lightning now shuts off and turns back on depending on `machine_stat` (power outage or being broken) as expected.
Fixes #66030

## Why It's Good For The Game

my immersion

## Changelog

:cl:
fix: Fire alarms no longer magically emit light when they lose power.
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
removei t
please
i hate the red ligthing
actually just remove lighting

**Comment by bluetshirtguy** [comment]
Don't some emergency signs like exit signs use Tritium to create a dull red glow without using power, it's not too unfeasible for a fire alarm to use it. Just a thought.

**Comment by Tastyfish** [comment]
> Don't some emergency signs like exit signs use Tritium to create a dull red glow without using power, it's not too unfeasible for a fire alarm to use it. Just a thought.

The red light turns on and off based on status. The icon state changes too.

**Comment by bluetshirtguy** [comment]
> > Don't some emergency signs like exit signs use Tritium to create a dull red glow without using power, it's not too unfeasible for a fire alarm to use it. Just a thought.
> 
> The red light turns on and off based on status. The icon state changes too.

gottcha gottcha

**Review by spookydonut — APPROVED** [review]

**Pull request merged**
