### PR TITLE
QM has a garment bag now

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Gives the QM a garment bag and moves all their uniform items into it.

And changes the order of a few items to be in the right place, most new clothing added to the bags just got placed on the end of the list.
## Why It's Good For The Game
When the QM was made into Command they didn't get their own garment bag so this just fixes that.
## Changelog
:cl: Guillaume Prata
fix: The Quartermaster has their own garment bag now, like everyone else at Command.
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
i dont think qm deserves a garment bag yet as they don't got too many clothes he just has the qm uniform/skirt wintercoat idk why he even has a firesuit but from that its pretty much his attire

**Comment by Farquaar** [comment]
I approve the garment bag but I'll be one foot in the grave before I'll ever accept the QM as a "head of staff"

**Comment by Serxule** [comment]
QM needs more clothing before this has an actual use ngl

**Review by ArcaneMusic — APPROVED** [review]
Seems fine, leaves room for more anyway.

**Pull request merged**
