### PR TITLE
Revert "Buffs Clogged Vents"

### PR DESCRIPTION
**Pull request by silicons**
Reverts tgstation/tgstation#34949
Requested by Naksu

### CODE REVIEW

**Comment by DaxDupont** [comment]
[17:51] <%Naksu> Dunc: goof didn't address any of the issues i wanted him to touch
[17:51] <%Naksu> also his design in highpop is actually worse than i thought
[17:51] <%Naksu> OOC: Timeisendless: the scrubbers foam had plasma mutation toxin and tb and phlogiston and polonium

**Comment by DaxDupont** [comment]
rip @Iamgoofball

**Comment by DaedalusGame** [comment]
this is the future you created my friends

**Comment by Aurantiaco** [comment]
you roll with those motherfucking punches or you're an unrobust bitchboy
a little plasma mutation and fire never hurt nobody.

**Comment by DaedalusGame** [comment]
400u of meth

**Comment by Wilchenx** [comment]
improve not remove

**Comment by Wilchenx** [comment]
24 hour rule

**Comment by DaedalusGame** [comment]
24 hour rule does not apply to goof prs

**Comment by Wilchenx** [comment]
@DaedalusGame are you a maintainer?

**Comment by DaedalusGame** [comment]
no but i read the contributor guide

**Comment by Wilchenx** [comment]
@DaedalusGame then you would know that there is no 24 hour rule at all

🚪 🚶

**Comment by DaedalusGame** [comment]
that's why it doesn't apply to goof prs

**Comment by Wilchenx** [comment]
You got baited and outsmarted, i've already notified the fruit of your endavours.

**Comment by Wilchenx** [comment]
Further replying to me will only worsen your situation

**Comment by DaedalusGame** [comment]
mfw you win so hard your opponent has to call for kiwi support

**Comment by praisenarsie** [comment]
24 hour rule is technically a thing, it's moreso a recommendation rather than a rule

**Comment by DaedalusGame** [comment]
read the guide my man

**Comment by DaxDupont** [comment]
Also naksu requested it so

**Comment by Wilchenx** [comment]
i m p r o v e 

n o t 

r e m o v e

**Comment by Armhulen** [comment]
you think your whining will help

it will not

**Comment by DaedalusGame** [comment]
why is this a test merge candidate slap that [s] on this

**Comment by Iamgoofball** [comment]
>lower the weight
>reduce the max occurrences to 1
>fix foam vs supermatter 

>"HE DIDN'T FIX ANY OF THE ISSUES"

@DaedalusGame I know you're lucky you're not gitbanned yet but wow, you're a cancerous individual.

**Comment by imsxz** [comment]
a single event of the foam shit caused science to burn down AND spread a TB infection

**Comment by CPTANT** [comment]
Maybe nerf the absolute worst chemicals, but don't revert this.

**Comment by Nabski89** [comment]
Inspired by this, I ran a "there's something in the vents" round on terry.

Didn't manage to see any of the fun things that everyone is complaining about here.

**Comment by DaedalusGame** [comment]
Terry doesn't have enough players to be affected by vent chems and also Omegastation probably has far less vents

**Comment by Nabski89** [comment]
They've actually changed their map preference to meta. I liked that they were always on Omega.

**Comment by Robustin** [comment]
Chem blacklist when, two recent PR's running into a lot of trouble because crazy reagents are getting thrown into the round by RNG.

**Comment by DaedalusGame** [comment]
chem blacklist is already a thing and clearly it's not helping

**Comment by AlexTheSysop42** [comment]
Maybe we should have seperate blacklists for debug chems (which cant be made or replicated in any way except admins) and really deadly chems (which can't be made by random reagent spawning like the vents but can be replicated in other ways, such as an Odysseus or the SCP; also this can include normal mixable chems). This blacklist includes all acids, maybe certain poisons, nanomachines if they get moved here (not the other blacklisted other_reagents, morphtoxin, xenomicrobes, or romerol, because those transformations are too unusual/powerful to be replicable in a balanced way), and the virus reagents like TB.

The current blacklist only includes debug chems, mining nanites, and some transformation chems (morph toxin, nanomachines, romerol, and xeno microbes).

**Comment by Iamgoofball** [comment]
Have you guys considered merging the nerf instead

**Comment by DaedalusGame** [comment]
Having seperate blacklists is basicly making your own blacklist/whitelist, which the old vent event *did*

**Comment by Iamgoofball** [comment]
>Have you guys considered merging the nerf instead

**Pull request closed without merging**
