### PR TITLE
NERFS THE MEATHOOK IN THE GOOD WAY

### PR DESCRIPTION
**Pull request by jughu**
I MEAN IT DOES 25 BRUTE PLUS BLEEDING DAMAGE AND A STUN YOU LAVALAND POWERCREEPS WHO NEEDS COOLDOWNS WHEN YOU CAN PULL BEAT YOUR HEAD IN RUN AWAY PULL AND BEAT YOUR HEAD IN

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Still 20 damage.

**Comment by jughu** [comment]
THIS IS NOW A BRUTE LASERGUN THE WAY IT SUPPOSED TO BE BECAUSE THE STUN IT DOES PLUS BLEEDING DAMAGE NTO FORGETTING THE MEATHOOK IS 18 BRUTE MELEE

**Comment by Kromgar** [comment]
Its still a random drop. You could get the cursed heart instead... which just fucking kills you

**Comment by KorPhaeron** [comment]
>NTO FORGETTING THE MEATHOOK IS 18 BRUTE MELEE

>flags = NOBLUDGEON

**Comment by jughu** [comment]
IT STILL DOES BLEEDING DAMAGE STILL STRONK

**Comment by Arianya** [comment]
I don't suppose we have stats on how many hooks have dropped/been used in killing someone recently do we @KorPhaeron?

**Comment by Kromgar** [comment]
The tendril item pool is pretty large... on the top of my head stands, eye of god, stands, ship in a bottle, i think a spellbook of smoke,

**Comment by KorPhaeron** [comment]
@Arianya 

Unfortunately the number of tendrils killed is not tracked.

However, looking at the logs from Basil in December

-There have been 174 rounds

-Only 8 different people fired the hook

-Only 2 of those people fired the hook on a z level other than lavaland

-One of those 2 people firing it on station was an admin who spawned themselves with it to go attack people evidently

**So only 7 people ever used the hook in 174 rounds (once every 24 rounds) and only one of those people actually went and killed someone on station with it.**

This obviously might vary month to month, but since I have to do this semi manually I'd rather not search forever.

**Comment by Arianya** [comment]
It'd have been interesting to have a full month of data (i.e. November) but I think the data is pretty conclusive, it has less then 1% usage in murders, so its not really desperately in need of a nerf.

If we wanted to give it more of a upside/downside like other lavaland chest items, perhaps it would bind to the arm like armblades do? Its thematically appropriate. @KorPhaeron 

As to this commit, :-1:

**Comment by jughu** [comment]
LAST TIME I MURDERED WHOLE CULT WITH JUST A MEATHOOK AND A SWORD

**Comment by Supermichael777** [comment]
stahp

or I'm gonna go meat-hook and cut down riot shotgun like my oc STREETPIG

**Comment by jughu** [comment]
Powercreeps

**Pull request closed without merging**
