### PR TITLE
Fixes an accidental (???) reversion in mech code

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Mechs no longer explode upon deletion. This allows them to actually leave wreckages and their pilots to not die from mech deletion.

Cars are the only sealed vehicles that explode now upon deletion. This means clowncars continue to explode.

I can't find the pr for the life of me since it's likely lost to our lost indexing but previous behaviour would sleep the pilot and dump them out of the destroyed mech, rather than exploding.

Does it do this now? Yes! Hooray!

## Why It's Good For The Game

This was mostly an oversight but I couldn't convince Tiviplus to fix it so I'm doing it.

## Changelog
:cl:
fix: Mechs no longer explode upon deletion. This was a reversion from previous mech code.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
why is mech exploding and damaging the pilot bad tho? even race car drivers wear environmental protection suits (bomb suits ingame) and you can eject yourself if you feel like you are getting assblasted

**Comment by necromanceranne** [comment]
This is fixing a reversion. At some point we already decided mechs blowing up and taking out their pilots wasn't the way it should work, and the only reason this was reverted was because the parent of mechs, vehicle/sealed, was what was causing the explosion. The mechs even have code for when it should be destroyed and what happens when it does. It's all irrelevant because of inheritance. So the intent is clearly still there to keep those mechanics.

**Comment by TiviPlus** [comment]
It was inherited from sealed destruction so I couldnt care either waz, although I would say its a balance change

**Comment by Rohesie** [comment]
I like the speed racer feature.

**Pull request merged**
