### PR TITLE
Get travis to test changelog generation [DNM]

### PR DESCRIPTION
**Pull request by optimumtact**
Adding a wrapper script to avoid building the changelog for every single map build, ready to merge once that is in and travis is building.

### CODE REVIEW

**Comment by optimumtact** [comment]
DNM till I verify it's building correctly

**Comment by Jordie0608** [comment]
I don't know if it'll help but you can validate the yml here http://lint.travis-ci.org/

**Comment by optimumtact** [comment]
TODO:

finish this

**Comment by optimumtact** [comment]
Redoing the branch to cleanup

**Pull request closed without merging**
