### PR TITLE
New solar panel and tracker sprites

### PR DESCRIPTION
**Pull request by Tastyfish**
## About The Pull Request

Adds new solar panel and tracker sprites, to remove one of the 3 goon files remaining. They are at an angled view, to match the newer sprite style.
- They use a 2.5D effect to work at every angle and not have 1000 custom sprites.
- I added `matrix/proc/Shear()` as that is one of the 3 fundamental affine transform operations but Byond didn't include it. Go figure.

The solar assembly now uses the different base sprite for panel vs tracker.

I also made `/area/solar` actually lit because y'know...it's very specifically supposed to be lit by the sun by definition. Kinda silly for it to be worse lit than everything else outside. My sprites that crossed halfway into `/area/space/nearstation` or whatever also looked terrible under being half lit.

### Sprite demo in a full cycle time lapse
ezgif com-gif-maker

## Why It's Good For The Game

- Kill the goon sprites.
- Kill bad top-down sprites.

## Changelog

:cl: tastyfish
qol: The solar array areas are now lit by the sun.
qol: Solar assemblies now have different sprites for solar panel vs tracker.
imageadd: Solar panels and trackers have new sprites and a 2.5D effect.
/:cl:

### CODE REVIEW

**Comment by OperativeLyn** [comment]
The Goon folder is dying...

**Comment by tralezab** [comment]
This is not qol but my word is this pretty

**Review by Imaginos16 — APPROVED** [review]
https://youtu.be/rY0WxgSXdEE

**Comment by Imaginos16** [comment]
Very very clever use of matrices by the way in all seriousness! It seems that killing the goon folder will be a very realistic goal for 2022!

**Comment by JohnFulpWillard** [comment]
it approaches

**Review by JohnFulpWillard — APPROVED** [review]
yea kill it

**Comment by Farquaar** [comment]
Certainly impressive sprites, but I'm not sure how I feel about them in SS13

**Review by axietheaxolotl — APPROVED** [review]
it's not exactly 3/4ths, but the rotation makes my brain fire off neurons so i can look past it

**Comment by Fikou** [comment]
HOLY BASED

**Comment by Serxule** [comment]
cursed but looks good

**Comment by LemonInTheDark** [comment]
> I also made /area/solar actually lit because y'know...it's very specifically supposed to be lit by the sun by definition. Kinda silly for it to be worse lit than everything else outside. My sprites that crossed halfway into /area/space/nearstation or whatever also looked terrible under being half lit.

What do you mean by this exactly? Solar areas are already lit in the same intensity as other non space turfs. 
They're not for testing, because starlight adds a significant initialization cost, but they are if you enable the starlight config.
image
This clipping is an issue we need to solve, not one to just ignore I think.

Do you mean the solars being in total darkness like this?
image

**Comment by gonenoculer5** [comment]
Sort of semi-related but, since were on the topic of solars, would we be able to nix solar arrays themselves from being a potential Contractor target area? Seeing as one has to literally smash a solar panel or three in order to call down the drop pod to stuff the captive into, it is rather strange and un-intuitive. Thanks! Sorry if thats a bit off topic.

**Comment by Imaginos16** [comment]
> I've always had a personal distaste for mixels, and I fear that having such a persistent effect like this will normalize their regular use. Of course I understand the reason for implementation though, one of the primary reasons solars have stayed unchanged so long is the painful 8-directional states that have made respriting it excessive work. I just personally hope though, that the use of matrice transforming are a temporary solution in solving an issue, and not a next step to regular implementation of similar effects like this across the repo.

Its certainly an exception and will not be the norm going forward, speaking as a spritetainer. The solution being applied here is very functional, and while it may be… Unusual, I think the pros outweigh the cons.

**Comment by AdipemDragon** [comment]
i actually have sort of a suggestion for this one that I think shouldn't be that bad to just tack on, and it should help with the panel looking Infinitely Thin when facing away, but because i'm bad with words i hope an very ugly&quick sketch will be more understandable
image

**Comment by Mothblocks** [comment]
@Tastyfish Do you need the backslashes for animate? You usually don't for procs.

**Comment by Tastyfish** [comment]
> @Tastyfish Do you need the backslashes for animate? You usually don't for procs.

Oh, probably not. I just did the backslashes out of habit.

**Comment by Tastyfish** [comment]
> > I also made /area/solar actually lit because y'know...it's very specifically supposed to be lit by the sun by definition. Kinda silly for it to be worse lit than everything else outside. My sprites that crossed halfway into /area/space/nearstation or whatever also looked terrible under being half lit.
> 
> What do you mean by this exactly? Solar areas are already lit in the same intensity as other non space turfs. They're not for testing, because starlight adds a significant initialization cost, but they are if you enable the starlight config. image This clipping is an issue we need to solve, not one to just ignore I think. It comes up elsewhere, like tram's rock walls
> 
> Do you mean the solars being in total darkness like this? image

Yes, I'm aware of the STARLIGHT config var. The problem is that all other outer space areas have `base_lighting_alpha = 255` *except* for the solar areas currently, where the variable is 0 and thus there is no ambient lighting. Hence the solar areas being randomly half lit, or not lit at all in the case of catwalks.

**Comment by Tastyfish** [comment]
> i actually have sort of a suggestion for this one that I think shouldn't be that bad to just tack on, and it should help with the panel looking Infinitely Thin when facing away, but because i'm bad with words i hope an very ugly&quick sketch will be more understandable image

I might actually experiment with that idea. It would require a second object in `vis_contents` though for it to transform separately, so might not be worth it from a performance perspective.

**Comment by Tastyfish** [comment]
I revised both the matrix math to be accurate to a 45deg plane at 3/4 view to my understanding, and added a bottom edge to make it better looking. Making another time lapse GIF too much effort.

image

**Comment by Tastyfish** [comment]
As a sanity check since there's 24 comments to fish through, is there any open concern I haven't addressed?

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Remove the backslashes

**Comment by Tastyfish** [comment]
> Remove the backslashes

done

**Pull request merged**
