### PR TITLE
Uplink item icons

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Adds icons to the uplink deals.

image

## Why It's Good For The Game

To see what you're bying.

## Changelog

:cl:
qol: Uplink detailed view shows item icons
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
oh my god, YES YES YES

**Comment by Gaxeer** [comment]
@MTandi can you also make only items scrollable, not all page. While you are here :D
If no, than I will do it later myself 🐀

**Comment by MrMelbert** [comment]
how does it look if you put the description in a `<BlockQuote>`?

**Comment by Admiral-Gigaton** [comment]
Can you add a compact version?

**Review by jlsnow301 — APPROVED** [review]
glorious dmicon

**Comment by MTandi** [comment]
> how does it look if you put the description in a `<BlockQuote>`?

image

**Comment by MTandi** [comment]
Decided to change the whole layout

**Pull request closed without merging**
