### PR TITLE
Replaces lavaland mining points with station points

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
## About The Pull Request
This removes mining points and replaces them with money, again. 

## Why It's Good For The Game
Just because I wasn't around doesn't mean their removal wasn't justified the first time.

If there are economic issues to mining vendor stuff being available for cash, then the solution is to fix economy. If there are game balance issues to mining vendor stuff being available for cash, then the solution is to fix the item or adjust the cost, mining is not a separate game.

Ordinary credits will do.

## Changelog
:cl: Naksu
change: replaced mining points with money, again.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
I stole some girl's ID and she had like 100k mining points so I think it was a guy

**Comment by 81Denton** [comment]
Does this PR fix the issue of people just using station cash to buy survival medipens and other mining items that cause issues when they're just available en masse?

**Comment by ninjanomnom** [comment]
They can be nerfed in other prs if it's actually an issue, this shouldn't have been reverted before

**Comment by cacogen** [comment]
orange has said he wants time-gated money (so distributed via payroll) plus mining gives far too many points for them to be 1:1 convertible to credits

**Comment by ArcaneMusic** [comment]
Honestly, a good change, even at the current exchange rate. I'm not going to try and pull a "trickle down economics" here, but trickle down economics with cargo having more funds means that more money gets passed around, cargo can pay crew members to do bounties, science can get funded for the BEPIS, more access to vending machines, etc etc etc.

Lets see how it plays out this time.

**Comment by 81Denton** [comment]
>They can be nerfed in other prs if it's actually an issue, this shouldn't have been reverted before

If this gets reverted, we'll end up with the same situation again where the station balance is broken because mining items are designed to only be used on lavaland and time gated behind mining.

It will be just like last time where nobody properly fixed the issue, because it would either be a half assed bandaid or you'd have to overhaul the majority of lavaland items and associated balance.

**Comment by vuonojenmustaturska** [comment]
they're not really 1:1 convertible to credits because the ORM can no longer be upgraded to purely increase the point value, whereas previously you got 35% more with each tier of upgrade.

**Comment by necromanceranne** [comment]
Technically it has been fixed since then as what was actually happening was departments abusing the department budget cards to purchase those medipens and hardsuits. Now, budget cards no longer exist so the abuse is largely dead.

There is a secondary issue with miners getting credits for ores. They can purchase high value items from cargo with ease. At the moment they might be the only person who can solo fund themselves things like supermatter shards and piles of combat shotguns.

I know one miner who did this on a per round basis. Miners are already incredibly obnoxious for lavaland loot, let alone how badly they'll fuck over the economy by becoming millionaires in less than an hour.

**Comment by ninjanomnom** [comment]
> 
> 
> > They can be nerfed in other prs if it's actually an issue, this shouldn't have been reverted before
> 
> If this gets reverted, we'll end up with the same situation again where the station balance is broken because mining items are designed to only be used on lavaland and time gated behind mining.
> 
> It will be just like last time where nobody properly fixed the issue, because it would either be a half assed bandaid or you'd have to overhaul the majority of lavaland items and associated balance.

I see this as a good thing in how it reveals the current broken balance between mining and the station. Mining points are the bandaid and if we need to rip it off to force change then fine let's do it.

**Comment by Pugie** [comment]
We are striding into an enlightened era. An era where every assistant can rush mining vendor and be guaranteed a bar of plasma-scented Nanotrasen soap.

**Comment by Whoneedspacee** [comment]
I’ll just say once again this is stupid, ores can be directly turned into currency, MORE than is given by turning them into the ORM. One diamond makes many coins which can be turned into 100 credits each.

When this was out I literally never stepped off of lavaland and just got all the upgrades and spammed medipens and cores killing all of the megafauna.

Stop trying to force this in until you fix these issues, mining points are a specific benefit for miners to reward actually mining to bring things back, all this does is circumvent that process for not much gain other than letting random people use mining vendors for some reason.

I don’t see a reason for this to ever be a thing, mining points can already be turned into station currency, mess with that if you want.

**Comment by 81Denton** [comment]
@ninjanomnom Just replacing points with cash and putting the onus of actually rebalancing lavaland content on other people is a little inconsiderate. 
Not to mention subjecting players to janky balance until someone maybe, eventually does the work of rebalancing it.

**Comment by optimumtact** [comment]
I think this is an outdated approach that will require too much work to fix the lavaland power creep.

The correct approach is to properly firewall lavaland from the station.

I have a proposed way to do that, which involves makings mechs the primary way to do lava land stuff, and not letting them return to the station, so mechs could be made fast, have new weapons and damage limits, such that lavaland can be balanced independently of the station, with the only cross flow being the minerals collected by the mining mechs shipping up to the station.

Firewalling them like this means mechs and lavaland fauna can be scaled against each other, and not the station, and only the old direct output (minerals) is actually collected.

Plus the idea of massive building sized monsters scrapping with giant mechs is hella cool.

**Comment by kriskog** [comment]
While getting rid of budget cards did help towards this, mining things will still be way too cheap after vendor prices were normalized to cargo prices. And we cant really increase the mining reward costs without getting the reverse issue of miners either having to work their ass off for simple job necessities or being absolutely loaded.

**Comment by necromanceranne** [comment]
Given we are getting a new mining mech, seems like great timing.

**Comment by bluetshirtguy** [comment]
> I have a proposed way to do that, which involves makings mechs the primary way to do lava land stuff, and not letting them return to the station, so mechs could be made fast, have new weapons and damage limits, such that lavaland can be balanced independently of the station, with the only cross flow being the minerals collected by the mining mechs shipping up to the station.

Mechs are really janky tho? it makes normal combat look smooth as butter. im not sure how its going to be fun.

**Comment by SkeletalElite** [comment]
You cant have lavaland stuff on station without nerfing it but you also cant nerf it without nerfing lavaland. This is why they have mining points and not money and why it needs to stay that way.

**Comment by OverlyGeneric** [comment]
> I have a proposed way to do that, which involves makings mechs the primary way to do lava land stuff, and not letting them return to the station, so mechs could be made fast, have new weapons and damage limits, such that lavaland can be balanced independently of the station, with the only cross flow being the minerals collected by the mining mechs shipping up to the station.

Isolating them further would be very bad for interaction. Hell, it sounds even worse than xenobiology/virology at that point.

It seems like a good idea but it sounds like an entirely different game. 

> Plus the idea of massive building sized monsters scrapping with giant mechs is hella cool.

oranges, you've been watching too many mecha animes.

**Comment by optimumtact** [comment]
Mechs are janky because they're gimped to fit within the station framework, where their high health and strenght make them require massive slowdowns and energy issues to not be rediculously OP.

On station they should be replaced by making hardsuits more modular and do more things (effectively exosuits)

@necromanceranne the focus is on "new" content, existing content such as the existing lavaland mining/exploring/monster hunting loop is free game for overhauling

@OverlyGeneric there will never be a good link between lavaland and the station, it's just not possible, they are two different gameplay loops with different goals.

Cleanly breaking them apart and controlling what content flows between station and lavaland helps deal with lavaland powercreep affecting the core gameplay.

Ultimately I think the approach taken to mining where lavaland was added was the wrong approach, but the issue was decided by people long before me, so I have to work within the constraints of that.

**Comment by Shadowflame909** [comment]
> 
> 
> I think this is an outdated approach that will require too much work to fix the lavaland power creep.
> 
> The correct approach is to properly firewall lavaland from the station.
> 
> I have a proposed way to do that, which involves makings mechs the primary way to do lava land stuff, and not letting them return to the station, so mechs could be made fast, have new weapons and damage limits, such that lavaland can be balanced independently of the station, with the only cross flow being the minerals collected by the mining mechs shipping up to the station.
> 
> Firewalling them like this means mechs and lavaland fauna can be scaled against each other, and not the station, and only the old direct output (minerals) is actually collected.
> 
> Plus the idea of massive building sized monsters scrapping with giant mechs is hella cool.

Mining becoming Mecha is actually pretty cool.

Four mining mechs can combine into one uber mechs to fight the ash drake when?

**Comment by Bawhoppen** [comment]
Maybe some of its contents should be locked behind coupons you have to find in lavaland?

**Comment by Bawhoppen** [comment]
Also I am curious on what the reason is for not changing it to a vending machine? I would've assumed that would be the preferred approach...

**Comment by cacogen** [comment]
>also didnt you people learn from last time? this is powergame central you're enabling EVEN if you triple the price of everything in the vendor right now.

you'd want to adjust the prices downward along with lowering the point rewards from minerals if you don't want mining producing a fuckton of excess cash that enables them to buy whatever they want through cargo and the vending machines on the station
but obviously due to being able to mint coins and sell minerals on the shuttle they already can (as can the general public with the public mining shuttle actually)

**Comment by Spepbuthewranglesgithub** [comment]
please no, i don't want the rock man of medical to nerf my life needles into the ground.

**Comment by Tlaltecuhtli** [comment]
id lock medipens to work only in lavaland

**Comment by cacogen** [comment]
currently a pile of those pens sometimes end up on the medbay front desk, which i imagine cobby loves. dunno how you'd logically justify them only working on lavaland.

**Comment by 81Denton** [comment]
>i sense this is a dumb question but why can't you nerf lavaland stuff to be suitable for use on station? surely it's all relative? if the weapons get a nerf, the mobs get the same nerf?

You can do that, and I'd be fine with this PR if it included these nerfs instead of just the points -> money conversion.

**Comment by Ratvar** [comment]
If there are economic issues to mining vendor stuff being available for cash, then the solution is to fix economy. If there are game balance issues to mining vendor stuff being available for cash, then the solution is to fix the item or adjust the cost, mining is not a separate game.
This PR neither fixes economy nor balances mining equipment, and so is bad by it’s own definition.

**Comment by trollbreeder** [comment]
Raise the prices of all items in the vendor to match the economy we have now if not done already.
Then adjust the prices of certain items that will be abused, like survival medipens.
And adjust the prices of certain items that are underused, like jump boots.

**Comment by stylemistake** [comment]
I think prices are fine as they are. Medipens still end up in medbay if miners contribute to it, even with the mining point system, so there's no point in locking it up.

Nice thing is that QM is able to vend stuff like conscription kits for volunteers with station credits.

I also think mining rewards are too high. One lavaland roundtrip with a cutter is 5K on average, and that money is also made out of thin air. Would be ideal if that money was debited from the station budget, and then sell plasma sheets to centcom to get out of the debt.

**Comment by knacker48** [comment]
I don't see how you are fixing the problems that caused us to go back to mining points after attempting this in the past, those problems being the fact miners would just grab a vendor and drag it to medbay so docs could get medipens and the fact that even without budget cards heads of staff still have access to plenty of money. In order to gate these products from the rest of the station you have to both make these products several times more expensive while also giving miners an appropriate salary/ amount of money from mining which will lead to miners being literal walking bags of money.

**Comment by TheMidnightRose** [comment]
Lock mining vendors to requiring mining access? It would make it at least a little harder for the crew to swamp the station with mining gear. Doesnt solve the point cost/generation issue though.

**Pull request closed without merging**
