### PR TITLE
[READY] Adds a ghost on-screen HUD

### PR DESCRIPTION
**Pull request by tkdrg**
Adds a ghost on-screen HUD.
~~This works but I still have a couple features to do.~~I'll do it eventually hopefully on another PR. ~~PRing this right now mostly because I need sprites.~~

~~TODO:~~ ~~Give ghosts sec/med huds.~~ ~~Give ghosts clickable HUD pop-ups for cloning, drones, parasites, etc~~DONE-ish, still have to replace pollCandidates() but not now

~~screenshot with my horrifying codersprites~~NOW WITH BRAND NEW ANIMATED SPRITES BY RAZHARAS THANK YOU

### CODE REVIEW

**Comment by Supermichael777** [comment]
>sec huds

watch the metagame bloom! Should not have huds they did not have in life.
Medical would be okay.

**Comment by Shadowlight213** [comment]
@Supermichael777 Better than giving them antag huds

**Comment by MrStonedOne** [comment]
no no no no no...

Keep the ghost verbs, make the hub disablable.

Huds look ugly when you change your view range as admin ghost. Especially when you do what I do and set viewrange to 11 then set tile size to 32.

I wouldn't even be able to see these buttons to turn off darkness.

***Keep the verbs.***

**Comment by optimumtact** [comment]
Yeah, you should always keep verbs as a fall back for those who don't want to use the HUD

**Comment by PKPenguin321** [comment]
yeah keep the verbs
i always type in the first few letters and hit space to autofill it and removing verbs is just a nuisance

**Comment by tkdrg** [comment]
Yeah OK I did that. Also removed the right half of the HUD since they're pointless if I'm keeping the verbs. New screenshot on the OP soon. Still need sprites and those other things.

**Comment by Razharas** [comment]
Cant see nothing wrong here

**Comment by Incoming5643** [comment]
Why are the buttons animated

Why

I want to use this feature but I can't because the buttons are so distracting

**Comment by peoplearestrange** [comment]
I thoroughly agree with Incoming. The animation to these buttons is completely unnecessary. Add that to the fact that no other hud buttons are so obviously animated, it just feels so jarring.
Having something constantly flicker at the bottom, specially for admins who spend 99% of their time observing.

**Pull request merged**
