### PR TITLE
Plane Master Refactor + Mutliz Rendering Optimizations (Bigly)

### LINKED ISSUE #43866: Ghost self observe white space
hey when i accidentally observe myself as a ghost space turned white
Screenshot_1

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Aight. My goal here is to reduce clientside rendering cost, with a focus on multiz maps in particular but extended generally.
The focus is mostly around hiding stuff that isn't doing any actual work, there will be a few behavior changes sprinkled in.

Commits are either directly doing one of those things or refactoring the plane backend to better support those things.
I'm gonna go one by one cause there's a bunch of bs here.

 [Actually refreshes the right PMs on AO change.](https://github.com/tgstation/tgstation/commit/ff578e9dba7041147fc6668ee1ed63d2ac3b86c9)

We were refreshing the game plane and nothing else.
This pref applies to the game WORLD plane and runechat, so let's update both of em

[Removes the supermatter_warp_effect type](https://github.com/tgstation/tgstation/commit/fa1af7824c8bc9cdd253597167e4e60fbf8f2291)

It's a copypasta of the warp effect type, which is already reused. No sense keepin it

[Conditionally removes distortion filter based off need (also the plane)](https://github.com/tgstation/tgstation/commit/683b287fc71b4f3066aa44b46f2767f242358238)

Distortion is a pretty meaty effect, and there is basically no point drawing the filter if we aren't using it.

So let's stick a trait on GLOB (I love this pattern bros) that tracks all the unique sources of distortion, and toggle it off if there are
none.

Same goes for the plane master cause why not.

Oh also rejiggles the trait ordering by adding a "global traits" section at the top

[Refactors multiz handling to be done with a proc on plane_master](https://github.com/tgstation/tgstation/commit/a603de0cedc98e55dd289d4bf4c8219fbc691b4a)

This allows plane masters to individually react to multiz and decide how they want to render (for instance, no reason to use full AO on the plane below us.)

[Escape menu plane hides when unused](https://github.com/tgstation/tgstation/commit/da53df9a118fcbd16a63be53990ecfc0c86883e4)

This is just a "we should be doing this" kinda thing.

It requires tracking if the menu is enabled or not on the hud datum (done with a trait)

It does mean plane masters can now react to the escape menu, so I could do some more complex effects more easily.

[Makes the hide_highest_offset component actually work if the parent is just being created](https://github.com/tgstation/tgstation/commit/d39cf54a073a44f22eff16288835534962def00a)

Fuck

[tmp](https://github.com/tgstation/tgstation/commit/52d16d5ed642f8aac6ce7e45b8d72b7c5dc250c9)

I uh, had to stop here for like... a month and a half?
But to insert what wasn't there initially, this is where i reworked ambient occlusion

AO as an effect is a mix of bluring, shifting, and a recolor.
It's also our single most expensive effect. That's not.. great.

It's so expensive mostly because it wants to do a pretty sizable blur, and that costs a bunch of gpu time.

That's an annoying problem, but it's actually pretty easy to solve if we roll our own effect rather then usin the dropshadow filter.
We can transform down the plane master, work on it, then scale it back up.
This reduces the pixel count we need to modify substantially and actually helps with the bluring too. It's all around winning.

I rolled the blur size back SLIGHTLY. I think it still looks fine and it's cheaper but if you disagree we can chat

Old

image

New

image 

[Cleans up parallax code a bit, makes it trait based](https://github.com/tgstation/tgstation/commit/140ddaa81f64a01ccd4e566be27b9241838c64a8)

Refactors parallax to be trait based, gets rid of most of the old for loops in its code. Hopefully this'll make things cleaner in future you know?

Fixes a bug that caused observing to make parallax fullwhite. I fucked up with multiz and didn't understand what the code was doing

[Refactors planemaster backend signficantly](https://github.com/tgstation/tgstation/commit/64db607352bc90934b68d21c0b9811d3f2dfda4a)

Alright, the goal here is to make removing a plane master remove any relays that feed into it.

This is useful both because it'll allow me to disable plane stacks above our current position, and because it makes parallax handling a lot easier.

This is a sort of... hell goal for fucked up dudes tho. 
We need to track relays by their target, relays need to know who their target is by direct ref, etc.

There's a lot of extra stuff here too. 
We track how many relays any plane has so if we end up with none we can render "in place" (IE without relaying, drop the * in the render target).

This is useful because it basically autohandles most cases of effect planes that we need to keep around through multiz culling. It's good.

This introduces a fun new problem though, we're changing the render target so everything that USES render targets needs to be updated.
Updating relays is trivial, but updating filters is fuckin NOT.

The solution I landed on is sending me to the pits someday, we override add_filter and detect any filters that use render_source. 
Then we hook into a signal on the plane master group that detects changes in render targets BY render target. 
Very cursed I am sorry.

Lemme see I removed blend_mode_override since it doesn't seem to do anything anymore.. uhhh

Oh I moved the render relay generating code into _plane_master.dm since that's what it's suited to now

I'm not totally happy with this code, I think it's still kinda... mazelike in a way that's hard for others to pick up on (and also me)

It's a TON better then old multiz culling stuff though, better matches what I think to what I end up writing

[Implements Topculling](https://github.com/tgstation/tgstation/commit/bbdafaea109f27641a3b000464d3f7bd0b062af0)

Enabled by the previous refactor, basically this lets us drop plane masters on the z above us. 
V powerful, saves MASSIVE time on most zs of maps like northstar.

Makes hidden_by_distance into an enum so I can handle having different types of being hidden.

Totally culls shit that's below our cutoff line.

Mostly relevant for like centcom or space exploring. 
May... not work actually now that i think bout it space exploring will need to take into account the zs it borders. hhh.

Fixes up some rendering to support the top cull stuff. 
Lighting needs to always render cause of how area lighting works.

Yeets lighting swapping alpha based off offset (since we just cull it now)

In turn yeets the forced alpha stuff, unused now.

Kills check_outside_bound, unused. 
Could in theory be implemented but it's not required and as bad as the rest of this is proc call overhead sucks

[Unit tests to ensure initial render targets are consistent](https://github.com/tgstation/tgstation/commit/3844b974050b9a70ed8da72b2e0967fdafcc97dd)

I'm like 80% sure we assert this but even if we don't I think it's a good thing to have consistent.

[Removes AO on z layers far from our view](https://github.com/tgstation/tgstation/commit/8f97dc3745dc7420b7aabccbcdab96531dfad5c1)

They don't like, do? anything, so this makes sure we aren't burning cpu time on nothing

Edit:

The above wasn't enough (or functional) on its own. We need to conditionally clear out plane masters that were not in view.

What follows is me doing that.

[Implements a cell system for plane depth](https://github.com/tgstation/tgstation/pull/82419/commits/ad06643db240ade695ea6887a17e362e64a3bc85)

Basically, we store the plane depth required to view all the turfs in a 3x3 square on a cell.
The idea here is to look these up on move and hook into them for changes.

This'll let us semi cheaply detect changes while keeping a consistent track

Of note, I've implemented this under the assumption that turfs will never desync from the cell they're attached to. 
This is due to the scale of the system, and while I would like to avoid it in a perfect world, it does appear to function. 
Have a bunch of shittests to scream if it breaks at least in the ways I can

[Refactors map views to track their "center", visual bounds and if they're rendering only one object or not
](https://github.com/tgstation/tgstation/pull/82419/commits/919c66296a60efd0f4e590979cc7732965948a18)

This will be required to properly implement conditional culling, and it also makes space parallaxed map views possible (Though I have not implemented it here, another time)

[Adds tracking to large client pixel offsets](https://github.com/tgstation/tgstation/pull/82419/commits/5d0f1cc12753482cc67a1d1d7f7354186efe43c7)

This is basically just the scope component, so that's nice (The changes to that file were in another commit, whoopsie)

[Rips out the old hud "our offset" tracking system](https://github.com/tgstation/tgstation/pull/82419/commits/b172e4d160a3877a3d700d89acea5c9e81da64c8)

It was confusing, and I'm implementing a better, per plane group version of it currently

[Implements conditional plane culling](https://github.com/tgstation/tgstation/pull/82419/commits/9b0e65c4f6a0ae45b88123339d0ab85eb64b4eaf)
[9b0e65c](https://github.com/tgstation/tgstation/pull/82419/commits/9b0e65c4f6a0ae45b88123339d0ab85eb64b4eaf)

This involves piping the afformentioned changes together.
We'll pull our desired range from either our client or from the map view we're attached to.

Then we pull all the visibility cells in a given range, check to see if we have them already, and if not readd them.

Then it's just a matter of piping a "high point" into our cutoff work, and badabing badaboom we're culling out all the planes we don't need.

This required a lot of futzing to get right, there were a bunch of issues with existing plane masters which is why you see so many diffs here.

[Adds debug verbs](https://github.com/tgstation/tgstation/pull/82419/commits/fa88ea80443358c509d9ed3e667dc1318284ef7e)
[fa88ea8](https://github.com/tgstation/tgstation/pull/82419/commits/fa88ea80443358c509d9ed3e667dc1318284ef7e)

Adds 2 debug verbs. One displays all existing cells, so you can see what places require extra depth.

image

The other displays the depth level of every turf for a given view range.
This required a little bit of hacking but it's really not that bad, and it's quite efficient for what it is. 
Happy with this.

image

[Fixes mirage rendering, adds visible z layers to tracking](https://github.com/tgstation/tgstation/pull/82419/commits/0881e8856039cf2b64ffb6fecdb7942db530de51)

Basically in order to render z transitions appropriately we need to know what "bottoms" of the world are around us. 
This is cause we need to know where to put like parallax whitifier and such.

The trouble with the current system is it doesn't really give us those.
All we know is our offset, and the offsets around us.

This sorta kinda mostly works right now but would break if we ever introduced like 2 z layer thing next to a 3 z layer thing. 
So that's no good.

What I've done here is refactored cell tracking to also track what z layers are in view. 
This should allow us to pull their depths trivially, and then make decisions based off that

[Sets up the code to be cheap if we're not multiz](https://github.com/tgstation/tgstation/pull/82419/commits/107fdeda2b35e8a6965697648ee61207792f4e01)

S important we aren't charring our performance for no reason

## Why It's Good For The Game

I'm sick of northstar's issues with "lag" being blamed on northstar. It is partially due to the size but most of it is due to my BS.
Also this makes working with "culled" plane stacks WAY easier, which makes this code both more approachable and more functional.

Closes #43866

Before (1 z level)
image

After (1 z level (also sitting at the bottom of northstar))
image

Before (3 z levels)
image

After(3 z levels)
image

Before (4 z levels)
image

After (4 z levels)
image

(I'm like 90% sure my gpu was being throttled here which is why there's such a big disconnect between 4 and 3)

I'm not gonna post the profiles for conditional culling cause they look basically the same. Shit rocks

## Changelog
:cl:
fix: We no longer waste your gpu rendering bits of multiz that we aren't looking at. In BEST case scenarios I expect a >65% reduction, tho that is nowhere near across the board.
fix: Observing other players will no longer lead to a fullwhite space
fix: Changing ambient occlusion settings now actually changes ambient occlusion settings
refactor: Changed a BUNCH about how rendering works, particularly multiz rendering. Throw an issue report if something weird is going on, please please please.
refactor: Reworked how ambient occlusion works, it's a bit less potent but I think it's still fine
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I opened this pr because wrote the pr body then realized I needed to do my pie in the sky thing to make this effect actually work 100% of the time, and I didn't want to accidentally wipe the pr body into dust.

**Comment by LemonInTheDark** [comment]
Alllright, we done

**Comment by LemonInTheDark** [comment]
Testmergin on manuel, we'll see how she does

**Comment by LemonInTheDark** [comment]
Maybe need to add a delay between moving and fully updating in case you move back off. Semi concerned about it causing frame drops, if it's happening at all it's happening on entrance, soooo idk

**Comment by OverwatchVoice** [comment]
https://github.com/tgstation/tgstation/issues/82552
Leaving this here because it's probably related.

**Comment by aaaa1023** [comment]
I don't really like the changes to ambient occlusion and I think that it effects the visuals of the game quite a bit in a negative way. It looks too harsh with the changes, especially around mobs and item in rooms with white tiles like medical and science. The Images in the OP don't really do a good job showing the changes to ambient occlusion because they're taken in a fullbright room with dark tiles, no items on the floor and no mobs in it.

<details>
  <summary>New AO Example 1</summary>
medical ao bad
</details>

<details>
  <summary>Old AO Example 1</summary>
medical ao good
</details>

Example 1 is probably the best spot to show the effects because of the white tiles.


<details>
  <summary>New AO Example 2</summary>
sec ao bad
</details>

<details>
  <summary>Old AO Example 2</summary>
sec ao good
</details>

Still noticeable in Example 2, though old AO is a bit harder to see.

**Comment by MrMelbert** [comment]
> New AO examples

This is why I wanted to see example pictures in the PR not taken in some place with a dark tiling - I think that looks noticeably worse in these pictures

**Comment by dessysalta** [comment]
This causes an issue with the character setup. 

image

Doing the usual shebang of rotating the character, swapping characters, switching jobs, reconnecting, etc. doesn't fix it. On Sybil the character preview works fine, and I don't think this would be caused by the other two (RPG Loot/AI lag fix) testmerges. Of note, clicking character setup after closing the box *will* show the character sprite, but only a tiny version of it for half a second, and then it goes back to the pitch-black.

Currently running most recent drivers on my end (NVIDIA GeForce RTX 4070 ver. 552.12) and using BYOND version 515.1635 (latest) in case that's worth mentioning, but I doubt it.

**Comment by LemonInTheDark** [comment]
> This is why I wanted to see example pictures in the PR not taken in some place with a dark tiling - I think that looks noticeably worse in these pictures

As mentioned in maintainerbus the performance benefit (perhaps because of how I am forced to do this) is not RADICALLY meaningful. May just roll this back

**Comment by LemonInTheDark** [comment]
> This causes an issue with the character setup.
> 
> image
> 
> Doing the usual shebang of rotating the character, swapping characters, switching jobs, reconnecting, etc. doesn't fix it. On Sybil the character preview works fine, and I don't think this would be caused by the other two (RPG Loot/AI lag fix) testmerges. Of note, clicking character setup after closing the box _will_ show the character sprite, but only a tiny version of it for half a second, and then it goes back to the pitch-black.
> 
> Currently running most recent drivers on my end (NVIDIA GeForce RTX 4070 ver. 552.12) and using BYOND version 515.1635 (latest) in case that's worth mentioning, but I doubt it.

This is... odd. The tiny thing has been a problem forever, tho idk why it's pitch black it shouldn't be doing that

**Comment by Chubbygummibear** [comment]
LEMON WHY IT TOOK ME LIKE A MONTH TO UPDATE YOG'S RENDERING WITH YOUR ORIGINAL PLANE CUBE UPDATE

**Comment by cowbot92** [comment]
> LEMON WHY IT TOOK ME LIKE A MONTH TO UPDATE YOG'S RENDERING WITH YOUR ORIGINAL PLANE CUBE UPDATE

only took me 3.9 weeks :^)

**Comment by LemonInTheDark** [comment]
I have fucked myself

**Pull request closed without merging**
