### PR TITLE
Adds a "Jerry" scream as a rare scream for male felinids

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Adds a scream, for catboys
Also adds it to Jerry as a death sound should someone ever map him in again.

## Why It's Good For The Game

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

## Changelog
:cl:
soundadd: Jerry scream, for male felinids (rarely)
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
Freeze

**Comment by EricZilla** [comment]
Jerry is on tramstation I believe

**Comment by YakumoChen** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
Next time just make a new PR

**Comment by Watermelon914** [comment]
Changes to species code requires you to get approval from a maintainer before making the PR. Please re-open once you get a maintainer's approval to make this PR.

**Comment by Acer202** [comment]
I still think this would be funny!

**Comment by YakumoChen** [comment]
unfortunately I'm unable to do this due to copyright

**Pull request closed without merging**
