### PR TITLE
adds drone to maint loot spawners

### PR DESCRIPTION
**Pull request by ghost**
Adds drone shells to maint loot spawners so ghosts can spend 20 minutes checking every inch of maint to spawn as one.

Alternatively, I could just add some to the map, but they might be rushed as soon as the server loads.

### CODE REVIEW

**Comment by Jalleo** [comment]
Remember the chance for one to spawn is a chance at every spawner there is no max limit.

**Comment by AlexCrimson** [comment]
It sure as hell doesnt take 20 minutes to search maint as a ghost. More like 1-2. Whats the point of gating drones behind R&D research if you are just going to put shells in maint?

**Comment by Dorsisdwarf** [comment]
Make them have a chance of spawning in the maint closets instead
That way ghosts cant hop in at roundstart because they're in a closet, but as people go through maint and loot it more become available?

**Comment by Jalleo** [comment]
Thinking about it more just makes this idea worse the core issue is R&D and how things get arbitrarily locked.

**Comment by Iamgoofball** [comment]
@Jalleo thanks for volunteering to rewrite r&d

**Comment by paprka** [comment]
"Whats the point of gating drones behind R&D research if you are just going to put shells in maint?"

I sure as fuck don't know why we didn't go for the bay solution of drone fabricators that ghosts can click on, relying on rnd and robotics is severely unfun

**Comment by dannno** [comment]
yeah for real
why didn't we do that

**Comment by paprka** [comment]
I did this wrong anyway but really we need a drone fabricator otherwise drones are boring thx

**Pull request closed without merging**
