### PR TITLE
Revert "Replace area-wide fire overlay with reddening the lights"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#38366
image

The blood of forks eh?

reopens #35415

### CODE REVIEW

**Comment by kevinz000** [comment]
oh no

**Comment by 81Denton** [comment]
How come?

**Comment by Cyprex** [comment]
PR could be more decriptive, why was this PR opened?

**Comment by Anonmare** [comment]
PARTY WAR NOW

**Comment by Arianya** [comment]
@Cyprex https://tgstation13.org/phpBB/viewtopic.php?f=25&t=18628

**Comment by vuonojenmustaturska** [comment]
The old code has code quality issues and going back to it is not an option I'm willing to entertain. Maybe if someone feels bad enough about the party button's removal they can bring it back.

**Comment by MrStonedOne** [comment]
This wi

**Comment by MrStonedOne** [comment]
This isn't about the party button removal, this is about undocumented changes and oranges' deletion of the thread discussing an undocumented change.

Even if somebody readded party buttons i'd still be opening this pr.

And it will stay open as long as topic 18628 is deleted or locked.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm not entirely sure what's not clear about "Also removes the party alarm because it's shit code" unless that was appended post the merge.

**Comment by MrStonedOne** [comment]
image

**Comment by ExcessiveUseOfCobblestone** [comment]
sad!

**Comment by SpaceManiac** [comment]
Not documenting the removal in the first place was an oversight borne of sloppiness rather than malice. I will try to re-add the party button sometime this week as I alternate between busy and tired. I'm not involved in the forum moderation.

**Comment by MrStonedOne** [comment]
Ya, @SpaceManiac this isn't anything against you. the slipup was a slip up, it happens, its understandable, and it should have been caught by oranges, but his missing it is also understandable.

The issue I have is oranges dismissal of the whole undocumented change as an issue.

Commenting that undocumented changes are allowed, deleting the thread bringing the issue up, and the delete message being intended to taunt me into forking are the primary issues at play, and I will not allow this revert pr to be closed until those issues are resolved.

**Comment by deathride58** [comment]
The party button was practically 100% unused. The only thing it managed to do was make the code for fire alarms an absolute mess. The vast, *vast* majority of players aren't even going to be aware of the party alarm at all, since only admins can spawn it and it was pretty much never used on live servers. The removal of this unused feature was documented in the PR's description. Documentation in a PR's description should be more than enough to satisfy documentation requirements, especially with a feature as insanely obscure as party alarms.

**Comment by MrStonedOne** [comment]
>The removal of this unused feature was documented in the PR's description. Documentation in a PR's description should be more than enough to satisfy documentation requirements, especially with a feature as insanely obscure as party alarms.

That was edited after the fact by cyberboss. it was not documented. Literally anybody can look at the last edited by link and see the edit history, you could have verified this yourself, and a month old pr with a edit from 6 hours ago should have been enough to suggest the edit history should be looked at. Now you look like a fool.

**Comment by Niknakflak** [comment]
Only coders would be so against something so fun

**Comment by ExcessiveUseOfCobblestone** [comment]
@deathride58 as an admin I don't think that's entirely true.

I have NEVER used the party button, but I have frequently used the proc that said button calls.

**Comment by Iamgoofball** [comment]
>MSO fucks with the codebase over a old PR

change the channel, i hate reruns

**Comment by MrStonedOne** [comment]
actually, as i detailed very clearly, i'm fucking with the codebase over a deleted thread.

**Comment by MrStonedOne** [comment]
Its another goofball missing the point episode. change the channel i'm tired of re-runs

**Comment by GunHog** [comment]
It is possible to have multi-colored party lights instead of an overlay?

**Comment by ExcessiveUseOfCobblestone** [comment]
@GunHog i'm sure SpaceManiac is working on a nice solution, this is just here because the lime and the burning bush are in combat

**Comment by kevinz000** [comment]
@GunHog 
>flashing colors with vglighting

me "stares at the lighting subsystem ms"
me "screams"

**Comment by Cyprex** [comment]
@kevinz000 *flips out circuits

**Comment by MrStonedOne** [comment]
Changing a lights color without changing the light strength or position could be optimized away, we already do so for movments and the like, only we could do the reverse and avoid view or list math and just loop thru some corners to change their rgb values and loop thru lighting object to change their color matrix without having to do view() or strength calculations.

**Comment by Iamgoofball** [comment]
is this about threads and codebase journalism

**Comment by Iamgoofball** [comment]
that light optimization sounds good on paper though letss try it

**Comment by optimumtact** [comment]
#39270

**Pull request closed without merging**
