### PR TITLE
Redesigns the Raven Battlecruiser escape shuttle

### PR DESCRIPTION
**Pull request by WJohn**
Hey, look! I ONLY died for about 3 months!

Have a shuttle.

This new shuttle is significantly more usable than the hideous lopsided garbage we had before. The turrets can actually fire at nuke ops and *won't* kill ian anymore. It also has shields you can enable to give you extra protection from boarders or meteors, and the bridge can thoroughly lock itself down with blast doors to enter it, and on the windows. These turrets can also be disabled in the bridge, if you like.

This shuttle now costs 30k, up from 15k, since it's an actually useful shuttle now. Gotta pay for your security!

:cl: WJohnston
add: The Raven Cruiser escape shuttle has been completely redesigned. It now comes with shields, turrets that shoot nuke ops instead of your dog, and a very secure cockpit for important personnel. Its price has increased to 30,000, though!
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
wjohn these shield sprites suck ill send u better ones if u want

**Comment by WJohn** [comment]
Sure, these are just regular shield projectors so they use the standard shield projector sprites. If you want to update them, be my guest. It can be done in a separate PR at your leisure, though.

**Comment by Qustinnus** [comment]
too lazy

**Comment by Time-Green** [comment]
Do the shield projectors by any chance block turrets?

**Comment by nicbn** [comment]
The raven in the floor looks more like some kind of structure standing up, I think it would look better if you added some kind of indication that it's in the floor (maybe make the floor cracks appear slightly over the drawing)

**Comment by WJohn** [comment]
@Time-Green They do, but they start off by default and can be toggled locally. Even "penetrator" lasers or xray lasers don't shoot through these. That'll need a separate PR to let that happen as I'm not really sure how to do that.

**Comment by Tlaltecuhtli** [comment]
what is that thing in the bridge

**Comment by WJohn** [comment]
It's a floor decal I made to make this ship a little bit more unique.

**Comment by davethwave** [comment]
The most impressive looking shuttle in the game so far

**Comment by MMMiracles** [comment]
tfw the shuttle that comes to rescue you has a higher build quality than any station you'll ever work on

**Comment by GuyonBroadway** [comment]
That is one Big Chungus of an escape shuttle.

**Comment by Tlaltecuhtli** [comment]
give the brig a bunch of weapons

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Might need to check some of your `dir`s
image
image

**Review by SpaceManiac — APPROVED** [review]

**Comment by Arianya** [comment]
Pretty

**Pull request merged**
