### PR TITLE
the big slappy is now immutably slow

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
the big slappy is now immutably slow, it cant be sped up by xenobio speed potion (because of how red slime crossbreed works, you can still avoid it with that bullshit, but at least that requires some effort for the xenobiologist to specifically create you one)

## Why It's Good For The Game
30 force
30 block chance
double object damage
throws tha guy away
KNOCKS DOWN FOR 2 SECONDS
and then your ass can literally just walk with it for FREE if you visit xenobio and they gloop out one potion with a slime and water (which if xenobio is staffed at all they probably will have at the point you made it)
image
(also a bit sus that it was added by a xenobio powergamer but thats beside the point)

## Changelog
:cl:
balance: you cant speed up the big slappy with slime potion
/:cl:

### CODE REVIEW

**Review by Ghommie — APPROVED** [review]

**Comment by Y0SH1M4S73R** [comment]
ided pr

**Comment by SomeoneYouProbablyKnow** [comment]
Cannot be an ided PR. No one has ever seen it in action as it requires rounds to go on long enough for xenobio to finish their funny projects

**Comment by xPokee** [comment]
> Cannot be an ided PR. No one has ever seen it in action as it requires rounds to go on long enough for xenobio to finish their funny projects

https://cdn.discordapp.com/attachments/705679956021215264/1141159579695198218/bigslappy.mp4

**Comment by CCC23** [comment]
So your saying I can still get full move speed with the old method :3

**Comment by Jacquerel** [comment]
why did we even merge this item

**Comment by Sparkezel** [comment]
Fikou did you notice it breaks your fucking limbs when you use it. it deals you 10 damage in slap and like 20 in wrench mode or something. it also has LONG ASS FUCKING cooldown

**Comment by Fikou** [comment]
> Fikou did you notice it breaks your fucking limbs when you use it. it deals you 10 damage in slap and like 20 in wrench mode or something. it also has LONG ASS FUCKING cooldown

its 10 / 15 damage which you can counteract with armor and click cooldown doesnt matter until we have swing combat cause you can still just spamclick the floor and it wont activate the cooldown (which is 50% higher) but i dont think that makes esword with knockdown, blocking, armor penetration and launching warranted to also be able to be weightless

**Comment by nukularpower** [comment]
> why did we even merge this item

this ^

Also the self damage hardly matters in the context of getting a slime crossbreed for speed anyways;  if you are going that far, surely you can also grab a couple purple slime cores for infinite regen jelly

**Comment by Shadowflame909** [comment]
Big Slappy should slap anyone who attempts to use regular slime potion on it

**Comment by carlarctg** [comment]
why is merging something'op' a big deal. let things be funny (as long as they are indeed funny), this isn't a competitive game

**Comment by Loafin34** [comment]
big slappy was created to be an antithesis to the regular fire axe. While the fire axe is much better at assaulting, with no slowdown and insane demolition power, big slappy is a defensive weapon. The stun and disarm of weapons is insane at locking down areas, and it's movement slowdown is the sole reason behind it even existing, as it would be too powerful to merge otherwise.

**Pull request merged**
