### PR TITLE
makes virology window larger

### PR DESCRIPTION
**Pull request by silicons**
one of the biggest annoying things about tgui is >you can't fucking resize it.

### CODE REVIEW

**Comment by GunHog** [comment]
But...you can...there is a huge arrow on the bottom right just for that purpose...

**Review by Cyberboss — APPROVED** [review]

**Comment by kevinz000** [comment]
... fuck i thought that was part of the nanotrasen banner

**Comment by Repukan** [comment]
Size creep

**Comment by Tacolizard** [comment]
pics or gtfo

**Pull request merged**
