### PR TITLE
Changes the syndicate black and red to look less chunky and ugly

### PR DESCRIPTION
**Pull request by AarontheIdiot**
## About The Pull Request

 As stated in the title, This PR changes the black and red syndicate with less bulky and ugly looking suits. Also removes the 50/50 chance to get the ugly red suit or ugly black and red suit from space suit boxes in the syndicate uplinks, and now only spawns the new red and black suits

<details>
<summary>Screencap</summary>

</details>

Note: Zawo made the sprites, i just put them in the game.

## Why It's Good For The Game

 current ones are ugly

## Changelog
:cl: Zawo & AarontheIdiot
del: Removed the chance of getting two different softsuits when ordering syndie space suit from uplinks.
imageadd: added SEXY on-character syndie black and red hardsuit
imagedel: removed ugly on-character syndie black and red hardsuit 
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
the sprite is based on the old eva suit for station

**Comment by FantasticFwoosh** [comment]
Dont like it, its too gritty (where does the helmet start?) and i prefered the original given that there's a 'suspicious spacesuit' that isn't strictly the syndie space-suit mirrored made to trick people's gimmick is now redundant.

Since the original picture wasn't added in the OP (its huge) i've cropped it to give a better image (ill remove this bit if anything changes)

**Comment by WJohn** [comment]
yeah no this is worse. the stripes are not clearly defined and are too busy, while the torso looks like a bulletproof vest, this is just sort of really messy, and it also doesn't even change the other syndicate suits, just one of them?

**Comment by Fikou** [comment]
also this doesnt modify inhand, and if it were to be changed it would probably be based on the eva suit we have now since rn its based on the eva suit we had before

**Comment by Eaglendia** [comment]
>while the torso looks like a bulletproof vest

It has 50 bullet protection.

**Comment by HomocidlePancakes** [comment]
This supposed to be a softsuit but it looks like an ERT hardsuit. Also head is scuffed

**Comment by datorangebottle** [comment]
I don't know what you're all complaining about. The new sprites look way better than the other two options. I think you just hate change.

**Comment by Tlaltecuhtli** [comment]
i like the older ones

**Comment by necromanceranne** [comment]
People forget these things are as well armored as the hardsuits. If it looks armored that's a good thing tbh because visually you couldn't possibly tell.

**Comment by Eaglendia** [comment]
I'm in favor of a change but I think this one still needs tweaks. The old black-and-red has always looked fat and doofy, especially for hostile environment EVAs on behalf of an evil corporate coalition in sci-fi 25xx. I don't think it's wrong for the suit to look tactical or armored, as armor-wise it's competitive with the blood-red and generally superior to security hardsuits despite looking like a softsuit. But it also has to be somehow distinguished from the blood-red. I'm not sure what I'd do to tweak this one, is the thing. It looks almost too sleek - like powered armor or an ERT suit - to fit the concept.

**Comment by necromanceranne** [comment]
Worth also acknowledging that the syndicate exosuits are all rather sleek. Elite is bulky due to armor plates/tacticool pouches but the blood red looks more form fitting. Their 'softsuit' (it's literally the same armor as the hardsuit it just doesn't have a combat mode and is in two pieces) probably should match, though I have some colour scheme concerns when contrasted against sec suits. I feel the centre piece needs more red to differentiate it from sec equipment at a glance. Red hardsuits are a dead giveaway but this could cause someone to double take.

**Comment by FloranOtten** [comment]
So wait, where does the head start?

**Comment by ishitbyabullet** [comment]
I think you should change the rest while the current red syndi space suit we have now should be it's own separate thing since I remember hearing that it's the really old nuke op armor so it shouldn't just be deleted imo.

**Comment by necromanceranne** [comment]
Goon still has it as their nukies space suits.

**Comment by optimumtact** [comment]
I'd try reworking this according to feedback and seeing if you get a more positive response.

**Pull request closed without merging**
