### PR TITLE
Fix bodies burning or set on fire while husked

### LINKED ISSUE #78794: Bodies don't stop burning after being husked
## Reproduction:

When a corpse has been ignited so damn badly the entirety of its flesh is ash it should, you know. Stop being on fire. This is like if you lit a plank on fire and the ash stayed ignited forever.

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
Fixes #78794

Bodies now lose fire stacks while husked.

## Why It's Good For The Game
One less bug.

## Changelog
:cl:
fix: Fix bodies now lose fire stacks while husked. 
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
What a chad

**Comment by MrMelbert** [comment]
IMO it'd be a lot neater of a visual effect if you just cranked up fire stack decay while husked to like 2-5 a tick (so when you get husked, the fire quickly peters out, rather than going from inferno -> nothing)

**Comment by MrMelbert** [comment]
Also this has some minor knock-on effects like making it harder for Pyre Sect Chaplains to accrue favor

**Comment by timothymtorres** [comment]
Good idea.  I added a -2 fire stack penalty to being husked so you still burn if in lava or on a bonfire.

**Pull request merged**
