### PR TITLE
Blobs now take damage from particle accelerators

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
balance: Blobs now take damage from particle accelerators
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
if someone sets up a PA to kill a blob core fucking kudos to them.

**Comment by MoreRobustThanYou** [comment]
@kevinz000 yeah this has it's downsides and upsides:

* Pain in the ass to set up
* Deals rad damage to people that get hit by the particles
* Blob can easily destroy it if it gets close enough

**Comment by praisenarsie** [comment]
it better deal a billion damage

**Comment by Armhulen** [comment]
^^^^^^^^^^^

**Comment by AnonymousNow** [comment]
Hope blobs get buffed soon. They feel so feeble right now, and I'm saying that as someone who routinely kills them.

**Comment by DoctoreMad** [comment]
Clearly blobs need a ranged weapon so we can have tower defense.
Goonblobs maybe, ignoring possible "GIVE THE BLOB SLEEP TOXIN" bullshit.

**Comment by KingPhilipIII** [comment]
PA have pretty limited range. So yea. Better do some MASSIVE damage considering the effort needed to set it up,

**Comment by MoreRobustThanYou** [comment]
Strength/damage:

0/3
1/6
2/9
3/30

**Comment by Ratvar** [comment]
MoreRobust, but you just setup strength to max anyway if you want to kill blob with it, snowflakery.

**Comment by MoreRobustThanYou** [comment]
@Ratvar yes but i'll deal rad damage to anyone caught in it's path, so it's a double edged sword

**Comment by KorPhaeron** [comment]
@MoreRobustThanYou what is the range on a PA

**Comment by MoreRobustThanYou** [comment]
@KorPhaeron i don't know, but I made it so it can't pierce blob tiles

**Comment by kevinz000** [comment]
@KorPhaeron 20 max so way worse than emitters for range lmao

**Pull request merged**
