### PR TITLE
[WIP] [DNM] Adds /obj/machinery/atmospherics/components/

### PR DESCRIPTION
**Pull request by duncathan**
What started as a simple "man, some of these atmos devices are silly" turned into a major refactor.
Basically, the way atmos devices were structured made certain applications of OOP impractical. Atmos devices can be pretty easily categorized into two major categories: pipes and components. However, codewise, they're split up into four: pipes, unary components, binary components, and trinary components. Because the three different types of components were children only of /obj/machinery/atmospherics, it meant that the procs and vars used for components only were shared by pipes, too. Obviously, that is not OOP. This PR solves this by making all atmos components children of a new type, /obj/atmospherics/components. 

TODO:
- [x] Move component-only vars/procs to /components/
- [x] Fix types paths in code and in maps
- [x] Make update_icon() actually work
- [x] ~~Figure out why putting welded in /components/ throws compile errors~~ I'm dumb
- [x] Find and move other component-only vars/procs
- [x] General cleanup and OOP-ing
- [x] ~~Clean up pipes after dealing with components~~ not done; for another PR
- [x] Make air flow

### CODE REVIEW

**Comment by MrStonedOne** [comment]
I honestly don't see the need for the extra type path...

**Comment by duncathan** [comment]
There are plenty of component-specific vars and procs that, without the existence of a container type path for components, cluttered up pipes and atmospherics.dm. Lacking a container for components also meant that the only way to do things like a component-specific OOP update_icon() proc (which is part of this PR) is to make it the proc for all atmospherics devices, and then making pipes override.

**Comment by Fox-McCloud** [comment]
same tile distro and waste (like Bay) when?

**Comment by Dorsisdwarf** [comment]
@Fox-McCloud 

If we port any pipe system, it's gonna be that glorious vgstation PR

**Comment by duncathan** [comment]
Regardless, both are out of this PR's scope.

**Comment by duncathan** [comment]
Significant progress is being made in terms of OOP-ing the components. I'm going to bed; I'll continue working on this tomorrow.

**Comment by Razharas** [comment]
Pipes dont even need to be machinery they use nothing from machine code

**Comment by MrStonedOne** [comment]
"pipes" includes vents, filters, mixers, etc. those use machinery's power stuff.

**Comment by duncathan** [comment]
A little more accurately, those are components, which is what this PR is about. Components use stuff from machine code.  Pipes are separate from components but are both children of of machinery/atmospherics. Pipes absolutely must be children of /atmospherics/, while components must be children of /machinery/ and /atmospherics/.

**Comment by duncathan** [comment]
The game's compiling, but I can't figure out why no components are getting their nodes, parents, or airs vars set. I'm probably missing something stupid, but until I fix this nothing works.

**Comment by duncathan** [comment]
Looks like all that's left is to make air flow. Can't be too hard. :^)

**Comment by duncathan** [comment]
I broke something

**Pull request closed without merging**
