### PR TITLE
Carpets can no longer be wetted or lubed

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Carpets no longer can be made wet by water, or be lubed by space
lube. SUPER ABSORBANT!
/:cl:

Also addtimered the MakeDry

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
I dont know how to feel about this, sorta 50/50 for and against.

Making 1 pretty common type of floor so strong is kinda fun and not fun at the same time.

**Comment by Mindustry** [comment]
Might as well remove high traction floors from cargo since chemistry can make them for free now and very easily deploy it to all of the station

**Comment by PKPenguin321** [comment]
Yeah I was gonna say, we have floor for this already

**Comment by Cyberboss** [comment]
You all imply that chemistry has any intent on helping the station

**Comment by optimumtact** [comment]
Yeah this already exists in the form of High Traction floors

**Comment by KorPhaeron** [comment]
Nobody ever gets high traction floors though

**Comment by optimumtact** [comment]
So? They're costly because slipping is an important gameplay element

**Comment by xxalpha** [comment]
Have you tried reducing the cost of high traction floors?

**Comment by KorPhaeron** [comment]
Nevermind the cost, who wants to manually pry up 50 tiles and then click each one again to put down new flooring? 100 clicks to do half a hallway

**Comment by ExcessiveUseOfCobblestone** [comment]
dragging floor tiles on plating that doesn't have a floor tile in its contents should place the floor tile down.

**Comment by ChangelingRain** [comment]
that'd make it impossible to collect up floor tiles by dragging though

**Comment by ExcessiveUseOfCobblestone** [comment]
that's why I said "that doesn't have a floor tile in it's contents"

**Comment by optimumtact** [comment]
Just make putting a floor tile down on a floor switch it out duh

**Comment by Durkel** [comment]
When I was five I was playing in my living room with a bottle of tide detergent. I dropped it and cap fell off leading to the entire carpet being covered in tide. The room turned into a slip and side and I can safely say from experience that a carpet not being slippery after being sprayed with a industrial lubricant makes no sense.

**Comment by PKPenguin321** [comment]
>realism

**Comment by coiax** [comment]
> Just make putting a floor tile down on a floor switch it out duh

**Pull request closed without merging**
