### PR TITLE
Add an asset cache log that logs send assets

### PR DESCRIPTION
**Pull request by optimumtact**
More logging is always helpful and this will help identify when we have people who's asset recv is broken due to ie incompatibility.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
I suspect that IE doesn't obey `<link>` tags that TGUI pumps out for whatever reason. For the RPD, I had to hack it by putting the `<link>` tag in `tgui.html` directly. Doing the same with `spritesheet_pills.css` gets things working.

**Comment by AnturK** [comment]
This log might get moon sized if one of these receive errors happens. Then i guess that's more reason to find the cause.

**Comment by Cyprex** [comment]
asset_loading might be a more descriptive name

**Comment by optimumtact** [comment]
@tgstation/commit-access

**Pull request merged**
