### PR TITLE
Fired projectiles can no longer hit people buckled to the firer, or things the firer is directly buckled to

### PR DESCRIPTION
**Pull request by silicons**
Fixes https://github.com/tgstation/tgstation/issues/34193

### CODE REVIEW

**Comment by imsxz** [comment]
uhh
> >borg getting shot at >borg buckles shooter to themselves >>>>>

**Comment by necromanceranne** [comment]
Oh no

**Comment by kevinz000** [comment]
@imsxz That's already a thing though, although I'll add a check so directly targetting the person you're buckled to still hits them.

**Review by SpaceManiac — APPROVED** [review]
here's to hoping

**Pull request merged**
