### PR TITLE
Adjusts the orientation of some computers and a terminal on BoxStation/Lavaland

### PR DESCRIPTION
**Pull request by hazamaitsuru**
:cl:
tweak: Various computers on BoxStation and Lavaland now face more logical directions.
tweak: BoxStation's gravity generator SMES had its terminal moved out of the wall.
/:cl:

Having computers facing away from the user was bothering me. Also, you don't need to deconstruct the wall to hook up a power cable to the grav gen SMES anymore (it's on the left side now).

### CODE REVIEW

**Comment by optimumtact** [comment]
You need to use the map merger tool https://tgstation13.org/wiki/Map_Merger

Further more, are you sure these face the wrong way in game? they may init to the right direction during roundstart.

Finally cargo's computers are meant to be used from a single spot in the corner, so one person would use both, so they were fine as they were before.

**Comment by hazamaitsuru** [comment]
The computers definitely enter the game facing walls. Cargo makes sense now that you mention it, though. Putting those back.

Working on the map merge now.

**Comment by hazamaitsuru** [comment]
Cargo consoles put back and maps (hopefully) merged.

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
Congrats on getting your first pull request approved. Welcome to the /tg/station 13 codebase!

**Pull request merged**
