### PR TITLE
Adds cosmetic security strap-on dildos

### PR DESCRIPTION
**Pull request by PKPenguin321**
Reasoning:

**Tone:** Tone has long been dead in ss13 and to claim strap-ons of all things are somehow dangerous to the tone is really weird and seems almost like a red herring??

**ERPers:** Multiple server votes have proven that the majority of the playerbase accepts and likes features traditionally identified as being "ERPer" features such as catpeople. Additionally fashion choices tend to appeal to a broad spectrum of players, and have useful gameplay effects since they can result in an item being more highly desired in spite of no mechanical advantage.

**"Intentions"/Other servers would use it** This seems kinda a weird, unfounded argument based off boogeymanning it so I don't really know how to respond to this other then asking for clarification

### CODE REVIEW

**Comment by CitrusGender** [comment]
mad lad

**Comment by Wilchenx** [comment]
To address point 1, the color scheme is the most important aspect of security recognizablity, which is NOT preserved in this sprite.

**Comment by Wilchenx** [comment]
this is one of those things that is not inherently funny in any way. like the ugandan knuckles meme, this is only funny because your peers tell you it is, and in a week it will no longer be funny and you will no longer have any investment in it being in the game.

if the robby rotten suit didnt make it into the clown vendor i dont see why this should make it into sec. flavor of the week meme trash

**Comment by PKPenguin321** [comment]
Looks nice, seems like it shouldn't offend anyone, and anyone who does get offense from it that isn't just funny memeing is yet another slippery slope conspiracist, afraid anything that isn't a buff, nerf, or abusable feature is trying to shove erp into their greytide.

In other words, if this or missed the cit repo two blocks down, a fair few of the posters missed Hippiestation on the other side of town.

**Comment by Wilchenx** [comment]
@RogueSteampunker the vast majority of us will also have no interaction with the strapon other then observing a small collection of pixels on someone elses knob.

**Comment by GuppyLaxx** [comment]
can we see the sprite atleast before it's merged

**Comment by Durkel** [comment]
Now I can get fucked by security in two different ways.

**Comment by pigeonsk** [comment]
Wareware wa

NUDIST

BEEEEEEEEACH

**Comment by Shadowflame909** [comment]
I'm against this PR, nyaa nyaa otaku stuff.

**Comment by Anonmare** [comment]
For real though this is bad faith posting

**Comment by Wilchenx** [comment]
*nuzzles @PKPenguin321 owo wots this?*
*bites security strapon*

**Comment by Ratvar** [comment]
add cursed suit variant

**Comment by Wilchenx** [comment]
add cursed variant to wizard event

**Comment by PKPenguin321** [comment]
@Ratvar @Wilchenx done nyaa~ :3

**Comment by Wilchenx** [comment]
dayofjuicing
this is for when oranges comes here

**Comment by Ratvar** [comment]
Can you use it as mask/muzzle yet?

**Comment by Qbopper** [comment]
bad faith post and pkp is deliberately trying to stir shit

who would have thought that the admin who refuses to use the channels everyone else does would be out of touch

**Comment by Wilchenx** [comment]
@Ratvar wait you mean as in the cock part goes outwards so you can fuck someone with your head or inwards so it blocks your throat?

**Comment by PKPenguin321** [comment]
>bad faith post and pkp is deliberately trying to stir shit

The amount of argumentation this concept has caused has convinced me that our playerbase are all universally suffering from some form of spectrum disorder

**Comment by Ratvar** [comment]
@Wilchenx Yes, praise be

**Comment by Wilchenx** [comment]
@Ratvar that doesn't answer my question at all~

**Comment by Qbopper** [comment]
you can act highh and might all you like, you know what you're doing and you know you're being a shit

not liking secskirts? sure, there might be disagreements over why but okay

making a pr specifically to mock people via quotes and using obviously extreme shit like strap ons? yes this is obviously a well intentioned thing to do and i'm sure you mean the best

if you have to argue your point by being a prick why bother

**Comment by Anonmare** [comment]
@PKPenguin321 Posting claiming you have opinions you don't genuinely have is the definition of bad faith posting tbh
Strawmanning is bad

**Comment by Wilchenx** [comment]
I have to agree with qbopper there.

You are just acting like goof, even he grew out of it.

**Comment by PKPenguin321** [comment]
feel free to start arguing against the reasoning in the OP any time

**Comment by Partheo** [comment]
You guys are fucking hilarious

**Comment by CosmicScientist** [comment]
@PKPenguin321 I'm worried this won't show above the secbelt sprite.

**Comment by Anonmare** [comment]
@PKPenguin321 Violates CONTRIBUTING.md's Banned Lists' Common Sense clause

**Comment by Repukan** [comment]
Can we have a stun baton version.

Asking for a friend.

**Comment by PKPenguin321** [comment]
@Anonmare other servers have similar if not worse, what's so outlandish with adding it here?

**Comment by Anonmare** [comment]
@PKPenguin321 Please do not post in bad faith

**Comment by Shadowflame909** [comment]
Anonmare I actually want this to be a feature, so why don't you stop dissing this PR. let us enjoy what we want, it's just a cosmetic item.

**Pull request closed without merging**
