### PR TITLE
Adds a station trait that brightens up IceBox's surface.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This PR adds a positive trait that brings lights to the outdoors surface areas of Icebox.

## Why It's Good For The Game
Building upon the features of the station traits. This is how it'd look:
It's Always Sunny On IceBoxStation

## Changelog
:cl:
add: Adds an Icebox-specific station trait that brightens outdoors areas on the surface level.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
If only we had the Icebox day/night cycle 😔

**Comment by Ghommie** [comment]
I don't think it'd fit the vertical underground layout of icebox that well. By the by, a night-day cycle would be as easy as gradually changing the base lighting alpha and perhaps the color, which isn't laggy in the slightest.

**Comment by Jacquerel** [comment]
Oh I thought you would be aware 😅 
We have unfortunately tried to add this feature on several occasions but never finished.
#74948 #68239

**Comment by Ghommie** [comment]
Oh, those are quite neat. I see why they'd use a lighting object for more natural transition between outdoors, indoor and underground areas.

**Comment by Iamgoofball** [comment]
We should do the day/night cycles; we've got other planetary maps that could benefit from it, including Lavaland itself.

**Comment by projectkepler-ru** [comment]
This PR is actually cool af.

**Pull request merged**
