### PR TITLE
New RPED sprite

### PR DESCRIPTION
**Pull request by 13spacemen**
## About The Pull Request
New sprite for RPED from CEV Eris by INFRARED_BARON from https://github.com/discordia-space/CEV-Eris/pull/8361

Also removed the special borg RPED sprite (it was just the RPED with an orange stripe), the borg RPED upgrade item uses a circuit sprite like the other borg upgrades
## Why It's Good For The Game
Looks better
Screenshot 2023-12-11 133244

<details>
  <summary>OLD INHANDS</summary>

 Screenshot 2023-12-10 185022

</details>

## Changelog
:cl: INFRARED_BARON
image: new RPED sprites
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Its definitely a nice sprite but at risk of raising the spectre of tg's mythical art style I think it contrasts much more strongly with everything else than the old one

**Comment by Jackal-boop** [comment]
it reminds me of a ghost buster weapon

**Comment by DATA-xPUNGED** [comment]
The outlines seem very harsh compared to everything else around it

**Comment by Jacquerel** [comment]
> It looks fine to me, its an inhand sprite Its just meant to communicate that the dude is holding an RPED. With most inhands its hard to even tell what it is without examining the dude

Yeah but it should at least be the same colour as the item it represents

**Comment by MTandi** [comment]
This is indeed massive, but why are the inhand colors shifted?

**Review by Wallemations — CHANGES_REQUESTED** [review]
Remove all the "massive improvement" parts of the PR and maybe I'll look at it, makes you sound full of yourself and I don't respect that

**Comment by MrMelbert** [comment]
I would say "Massive change" instead

**Comment by MrMelbert** [comment]
>Also removed the special borg RPED sprite (it was just the RPED with an orange stripe)

Kinda cringe

**Comment by Wallemations** [comment]
> I would say "Massive change" instead

It's more the fact that it's in caps and brackets that makes me pissed off
I can accept people saying "I improved this sprite!" But putting it in brackets and caps makes me not respect it

**Comment by MrMelbert** [comment]
> It's more the fact that it's in caps and brackets that makes me pissed off I can accept people saying "I improved this sprite!" But putting it in brackets and caps makes me not respect it

The joke was that I don't see it as a massive improvement, but you sent your change request right before I commented and it makes me look like I was responding to you when I was not

**Review by Wallemations — CHANGES_REQUESTED** [review]
Now that that's settled;
Definitely make the colors on the item match the colors on the inhand sprite.
I'm assuming this is just for the normal one not the bluespace one?

**Comment by Wallemations** [comment]
> > Now that that's settled; Definitely make the colors on the item match the colors on the inhand sprite. I'm assuming this is just for the normal one not the bluespace one?
> 
> yeah just the normal one. i guess someone could do a black and blue palette for this and add an antenna to make a bluespace sprite

I'd rather the bluespace one not just be a recolor of this. The nozzle that the bluespace one has is an aspect I personally really like and would hate to see removed

**Comment by zxaber** [comment]
>Also removed the special borg RPED sprite
The borg RPED upgrade used this sprite too, which was helpful for telling the difference between a borg RPED upgrade and a normal, human-usable RPED.

Does this change the upgrade sprite to use a circuit sprite like other upgrades?

**Comment by intercepti0n** [comment]
Did you ask Infrared Baron and Eris guys for perms to use this sprite?

**Comment by Wallemations** [comment]
> Did you ask Infrared Baron and Eris guys for perms to use this sprite?

This is a good point, did you?

**Review by Wallemations — CHANGES_REQUESTED** [review]
I'll be honest I really still don't feel sold on it
I like the general concept but after having had time to mull it over I really don't think it fits as it is, and the biggest reason for that is the shading.
It's not shaded/colored like a TG sprite, it's shaded/colored like an ERIS sprite, and it just doesn't fit all that well.
For an example on how TG sprites are shaded take a look at crates/lockers, or some various recently updated machine sprites in the shape of boxes. They're less harsh in their contrast and usually follow a pattern of the top being lighter while the side is shaded.
I apologize for having you go through all that previous stuff just to say I'm not a fan, but it was only after really giving it some tough thought that I don't think I can merge this, at least in this state.

I'll leave it up to you whether you'd be willing to change it or just close it.

**Comment by CRITAWAKETS** [comment]
> wallem words here snippity snip

I will say that this shading isn't entirely out-of-touch with /tg/, infact the normal walls in the wallening will use pretty much this exact same shading. Although that's maybe just an issue with that sprite in the wallening too.

**Comment by Wallemations** [comment]
> > wallem words here snippity snip
> 
> 
> 
> I will say that this shading isn't entirely out-of-touch with /tg/, infact the normal walls in the wallening will use pretty much this exact same shading. Although that's maybe just an issue with that sprite in the wallening too.

The wallening sprites are different due to their size imo
The fact this is so small makes this feel odd to me
Really it could just be the palette, but I wouldn't discount the shading being the issue as to why this doesn't look like it fits

**Comment by BlueMemesauce** [comment]
sprite pr when they dont include the previous for comparison
68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f38303234312f323635363537353135393431303934363330302e706e67
I think it looks like it fits fine with the shading it the problem I have with it is that it looks more mechanical than technological if that makes any sense. Like the old one is this refined box with smooth edges while the new one has tons of stuff sticking out of it and those sharp edges at the front for some reason. That doesn't really fit the TGstation style. I think its more of a design style issue than art style.

**Pull request closed without merging**
