### PR TITLE
Removes space bar from ruin list

### PR DESCRIPTION
**Pull request by jughu**
Space bar was never used then other then a fucking bartender teleporting on the station or the scientists being powercreep and taking teleporter crystals every round

:cl: Hyena
del: Space bar is out of bussiness
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)fuck you science

### CODE REVIEW

**Comment by Meowkins** [comment]
-1 support
+1 removal of jughu's pull requesting privlege

**Comment by Cheridan** [comment]
He's right though

**Comment by lzimann** [comment]
It is already a config though.

**Comment by Durkel** [comment]
That awful feeling when we can't have nice things because the amount of people who will use it to rp is significantly lower than those that would use to powergame.

**Comment by TrustyGun** [comment]
there is nothing interesting RP wise for the space bar though. You are essentially a discount bartender who no one even visits.

**Comment by Kraseo** [comment]
*and* requires teleporter access so good luck getting customers haha

**Comment by jughu** [comment]
the only way this ever could work is just having the bluespace beacon here without teleporter and just a signpost anyways but then still it wouldnt be used

**Comment by DanteRU0312** [comment]
Hell no, i like space bar. Just figure something out with teleported that's in it.

**Comment by jughu** [comment]
infact they will mind because quantum pads for easy travel!

**Comment by jughu** [comment]
heres the following points and probaly solution

- Remove the teleporter and add the signpost to the space bar which sends you back to the station 

- Prevent the bartender's ability to leave trough the signpost

- A easier way to get to the space bar itself then teleporter access since most people will grab the hand tele and thats already grand theft

**Comment by cacogen** [comment]
hippie added a no teleport disability to hotel staff to fuck them up if they leave (they forgot to add it to the bartender though)

also the whole idea of having people visit these ruins is pretty dumb if it requires teleporter access

**Comment by KorPhaeron** [comment]
This has never been used except to loot or wait out meteor or establish an antag base on another z level for pseudo extended

**Pull request merged**
