### PR TITLE
Fixes riding vehicles on tables and lying on beds

### LINKED ISSUE #80027: Motorised Wheelchair raises and lowers when climbing tables.
## Round ID: [219717](https://scrubby.melonmesa.com/round/219717)

image

## Reproduction:

Get on a motorised wheelchair, get off of it.
Occasionally it will rise upwards or lower downwards.
I'm not very sure what causes this, but it looks very funny.

### LINKED ISSUE #80050: Laying down on some stuff is bad now
Reporting client version: 515.1620

## Round ID:
[219769](https://scrubby.melonmesa.com/round/219769)

## Testmerges:
- [Changes Virology Rather Than Killing It](https://www.github.com/tgstation/tgstation/pull/79854)
- [Drops ie8 support](https://www.github.com/tgstation/tgstation/pull/79974)

## Reproduction:
slep
Simply put, the beds were already made with the preexisting player offset when laying down, OR they had their own (i.e. operating table)
but now the "standing on top" offset from #79797 doesn't go away when laying down on some of these, so laying down in something like any bed or an open crate just looks kind of weird
Beds (and operating tables, maybe more) are doubly weird, too, since this offset kind of goes in the negative or something?? when you buckle to them, so now the offset's too low.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Fixes #80027. My bad.
EDIT: Also fixes #80050.

## Why It's Good For The Game
See the issues above.

## Changelog
:cl:
fix: Fixed an issue with the offsets of ridden vehicles on tables, and another when buckled to a bed.
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
also while your at it FUCKING MAKE IT SO YOU SLEEP FACING THE PILLOW please it is ruining mah immersion

**Comment by FlufflesTheDog** [comment]
Perhaps related, the elevating effect doesn't seem to go away when a table is deconstructed, you'll continue to become elevated whenever you step onto the now empty tile

**Comment by lessthnthree** [comment]
Tram still sends people into pixel_z hell after this. https://github.com/tgstation/tgstation/issues/80059 Put a runtime in the issue.

**Comment by Addust** [comment]
...you DID account for post-roundstart bed spawning like on lavaland comms guys, right?

**Pull request merged**
