### PR TITLE
Abductor camera console eyes are now visible to ghosts

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Ghosts can now see where an abductor camera console is looking.
/:cl:

I mean, the AI has it, why not abductors?

### CODE REVIEW

**Comment by yoyobatty** [comment]
Shouldn't this also apply to advanced cameras

**Comment by subject217** [comment]
It could apply to ACCs, but is there a point to it? Currently the only thing in the game that uses ACCs is what, the Nuke Ops shuttle?

**Comment by yoyobatty** [comment]
I mean, if there was a way to have this to apply to all camera eyes it would make things a bit interesting

**Comment by coiax** [comment]
I will make it also apply to the nuke ops shuttle. Lemmie go make a black and red coloured reticle.

**Comment by necromanceranne** [comment]
Comms agents use an advanced camera console. So if the ghosts wanna see what the comms agent is looking at I suppose.

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
Can be done in a different PR

**Pull request merged**
