### PR TITLE
No armour for the tacticool

### PR DESCRIPTION
**Pull request by optimumtact**
thanks man

### CODE REVIEW

**Comment by PKPenguin321** [comment]
fixes https://github.com/tgstation/-tg-station/issues/14587

**Comment by Zilenan91** [comment]
Wait why, you can only get one of these by hacking the vendor anyways without reconstructing and rehacking the entire thing. There's especially no real point to this because you could just break into arrivals sec checkpoint and get a sec jumpsuit that's also armored there rather than go through the effort of getting tools & gloves to get it out of the vendor just to have a slightly more stylish version of the sec jumpsuit that doesn't even have sensors on it.

**Comment by Iamgoofball** [comment]
@Zilenan91 i believe arcade machines give them too

**Comment by PKPenguin321** [comment]
@optimumtact you could just leave the pathing alone and make a " 	armor = null" line or something

**Comment by Zilenan91** [comment]
Yeah but that's a super low chance from the arcade machines because of the sheer amount of prizes you can get out of them. At max I've only seen like one out of like 40 toys.

**Comment by Anonmare** [comment]
Leave my turtleneck alone

REEEEEEEEEEEEEEEEEEEEEE

**Comment by Iamgoofball** [comment]
yeah @optimumtact just set the table to 0s across the board

**Comment by optimumtact** [comment]
no, if it's not inheriting anything useful from the syndicate turtleneck why the fuck would I bother makign it a subtype.

**Comment by PKPenguin321** [comment]
because conflicts and extra paths are dumb

**Comment by Bawhoppen** [comment]
>feature freeze

**Comment by optimumtact** [comment]
this is a bugfix

**Comment by Bawhoppen** [comment]
it wasn't a bug??????

**Comment by optimumtact** [comment]
yes it was

**Comment by Bawhoppen** [comment]
if it was originally a bug it intends to stay in cause it makes no sense to remove it

**Comment by tedward1337** [comment]
oranges fix yer shit

**Comment by Fox-McCloud** [comment]
:-1: 

You have to hack to get these or win one at the arcade. 

It's so minor of a benefit that I don't think this is worth addressing; it would be akin to making the insulated gloves in YouTool's be fake insulated gloves.

**Comment by PKPenguin321** [comment]
Not really since half the station (read: Security) doesn't realize they have armor because they're supposed to be a joke item that scares people into thinking you're a nuke op, not a utility like insulated gloves. Not to mention how good jumpsuit armor is since it covers every area but the head.

**Comment by Zilenan91** [comment]
It's only 10 melee armor though, and you have to go through like 1000% more effort to get this than to just break a window and grab a sec jumpsuit from the sec checkpoint in arrivals.

**Comment by PKPenguin321** [comment]
1. it's supposed to be a toy to prank people, not interchangeable with actual nuke op jumpsuit armor
2. a lot of the crew assumes it's already this way and do not expect it to have armor

also, if it's so much harder to get than a sec jumpsuit, why would you care if we nerf it? you'll just be using a sec jumpsuit anyways, right? right? :^)

**Comment by Zilenan91** [comment]
Well yeah, but the tacticool looks way better with sec gear than the actual sec jumpsuit does, so it lacking armor kinda sucks.

**Pull request closed without merging**
