### PR TITLE
Clockwork cult antagonist creation and job bans

### LINKED ISSUE #18622: You can't ban people from clock cult
There's no option to do so in the manual ban panel or player panel -> jobban

### PR DESCRIPTION
**Pull request by ghost**
I haven't ever done jobbans before, so please look over the code thoroughly, as I was unable to test the jobbans here due to them not working on a local server.

Fixes #18622

### CODE REVIEW

**Comment by Xhuis** [comment]
Apparently jobbans didn't save, so I'll do those right now.

**Comment by Shadowlight213** [comment]
You probably need to check to see if the objectives were setup yet and set them up for creating antagonists so the cult doesn't get the default meme objective.

**Comment by Xhuis** [comment]
If you mean that they shouldn't get the "summon Ratvar" objective, it's intended that they do. Right now, they don't have any other objectives.

**Comment by Shadowlight213** [comment]
No, at the moment if you make them with the traitor panel, they get the "ensure the meme levels on the station remain high" objective.
Unless that was changed

**Comment by Xhuis** [comment]
Nice. I'll look into it.

**Comment by Shadowlight213** [comment]
Xhuis that doesn't fix the issue though? The objective is still escape, not summon.

**Comment by Chocobro** [comment]
what is this branch name meme i keep seeing

**Pull request merged**
