### PR TITLE
Resprites for area icons

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Over the years we've accumulated a ton of mish-mashed and clashing area icons. This resprites (almost) every area icon to follow a standard text, design, and general department/section color. Also adds some new unique icons for areas that previously used basic area icons.

Before:
gitkraken_0ANLEkBVnK

 After:
gitkraken_eXOOBUr0S5

Example:
dreammaker_k7N6ijtlnS

## Why It's Good For The Game

Cohesive areas good. Boom Boom Shake The Room bad.

## Changelog
:cl:
imageadd: Resprites for existing area icons
add: Various new area icons
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
>to follow a standard text and design
>doesn't say what the text and design is for people who make icons in the future
>issue continues forever

also the reason areas in the same departments had/have different colors between subtypes was because it was/is much easier to identify areas that are incorrect that way when using dream maker.

**Comment by wesoda25** [comment]
Holy shit based

**Comment by uomo91** [comment]
> since this makes everything harder to identify using byond's editor alone, ergo making it more difficult to work with TG's maps for inexperienced mappers, this gets a no from me.

Inexperienced mappers should NOT be using Dream Maker to make/edit maps, it's a horrible experience and makes nearly everything harder.
Source: am inexperienced mapper.

**Comment by Twaticus** [comment]
> standardizes area text and design
> doesn't say what the text or design is for people who make area icons in the future
> doesn't provide a PSD for people who make area icons in the future
> issue continues forever

Area icons were a free-for-all before. Anyone in the future making a new area icon can look at and reference any of the 300 icons to figure out what it should look like. Im not sure what a PSD would be for, every one of them was made in DM.

> also the reason areas in the same departments had/have different colors between subtypes was because it was/is much easier to identify areas that are incorrect that way when using dream maker since it doesn't have the area border highlighting that's in StrongDMM.
> 
> since this makes everything harder to identify using byond's editor alone, ergo making it more difficult to work with TG's maps for inexperienced mappers, this gets a no from me.

Most subtypes are different though. All of science is purple yes, but each section inside science are different shades of purple and ones that use the same shade of purple have distinct text to easily tell which section is which. DM also has border highlighting its under Options > Frame Areas. The example screenshot was taken in DM.

**Comment by TheVekter** [comment]
A PSD wouldn't even really be necessary. Just post somewhere what font and text size you used, some sort of style guide we can follow to make it easier.

**Comment by ArcaneMusic** [comment]
> A PSD wouldn't even really be necessary. Just post somewhere what font and text size you used, some sort of style guide we can follow to make it easier.

Or hell, just add an icon in the same file that has the ABCs listed out for both upper and lower case and that'll do it.

**Comment by MrPerson** [comment]
I have to wonder how this looks for colorblind people. It might be difficult to differentiate slightly different shades of green if they both look grey, for example. The text is likely good enough though and either way area editing is a very minor deal when mapping so :+1: 

This really didn't need a changelog entry but w/e.

**Comment by RaveRadbury** [comment]
What a powerful PR. This overhaul was needed, Thank you, Twaticus.

**Comment by Twaticus** [comment]
added fonts and base examples for 1-3 word areas

**Pull request merged**
