### PR TITLE
Blob Chemical Reroll

### LINKED ISSUE #8085: Admin spawned blob "stuff" has no icon sometimes
If an admin manually spawns blob stuff like normal, shield, factory, node, or a core using the spawn verb, it will appears colorless (fine) but also sometimes without a proper icon and will have the icon state of "blob_blank" which is invisible.  It always seemed to make nodes invisible but cores would only sometimes be invisible.  One time, when I did this to help out a blob that was getting fucked because it got in it's body late because I had to manually input the ckey into it using vars, apparently all the icons broke because every blob core afterwards had no icon.  
Blob sprites are being weird.  @Iamgoofball

### PR DESCRIPTION
**Pull request by RemieRichards**
- Allows the Overmind(s) to reroll their chemicals at a cost of 50 points
- Blob mobs repathed to /hostile/blob
- Reworks the blob colour system a bit
- Fixes blob cores being invisible (Fixes #8085 , someone Finally reported it)

### CODE REVIEW

**Comment by AlexCrimson** [comment]
What happens when it rerolls? Does the entire blob mass change color, or just new blob tiles it spawns?

**Comment by RemieRichards** [comment]
Original intention was B, but it does A because it *sort of* did A so I fixed it so it does A properly instead.

**Comment by AlexanderUlanH** [comment]
I haven't managed to play as a reagent blob on a server, so:
:+1: if and only if the 50 points worth of cost (That's 10 points away from a whole blob node) is likely to be the value of forcing the humans to re-adapt.
Since the only real adaptation the crew can do is using or not using fire suits or riot suits, I'm skeptical that that's the case.  :-1: if it's going to be pointlessly overpriced, or only worthwhile as a roll for a chemical that's generally stronger than the one you have.

**Comment by Jordie0608** [comment]
Changelog.

**Comment by GunHog** [comment]
In the name of the Emperor, please finish this!

**Comment by RemieRichards** [comment]
@tgstation/commit-access Conflicts Fixed, Changelog added

**Comment by GunHog** [comment]
MERGE NOW! Before another merge conflict!

**Comment by GunHog** [comment]
Aaaaaaaaaaaaaaaand it is too late. Poor RR :(

**Comment by RemieRichards** [comment]
Conflictus Fixus!

Nah I'll do it when I get home though.

**Comment by GunHog** [comment]
Cast it again!

**Comment by Lumipharon** [comment]
So not directly an issue with this change, but is there an reason why people WOULDN'T always change to acid blob? I mean no matter how you look at it, some blobs are objectely way better then others.
Shit like acid, explosive, incendiary and even dark matter.

**Comment by RemieRichards** [comment]
@Lumipharon Cost. If people abuse it, it can be rebalanced further (It's intended as a get out of jail card if the crew adapt to fight you, you do the same) 50 isn't *much* but it's a valuable amount.

**Comment by Lumipharon** [comment]
No I mean like, if I spawn as a shitty blob, there's no reason to NOT reroll as soon as reasonable possible, to one of the objectively better blob types.
Basically it's just an issue of some types are OP and other are UP. This Pr doesn't chage it, it just means people are going to always go for le ebin acid blub.

**Pull request merged**
