### PR TITLE
Lets parrots ride humans again.

### LINKED ISSUE #25293: somebody fuckin broke poly riding people
like if you try it says "poly really can't seem to mount your mom"

### PR DESCRIPTION
**Pull request by silicons**
Fixes #25293

### CODE REVIEW

**Comment by RemieRichards** [comment]
The amusing part of this is:
- I, as a parrot, VV'd myself onto Mehki's shoulder
- I wrote it in as a proper feature
- Mehki breaks it

*sigh*

**Comment by KorPhaeron** [comment]
It's like pottery

**Comment by GunHog** [comment]
>It's like pottery

Because Kev runs in with a sword, breaking them rupees?

**Comment by TheColdTurtle** [comment]
It rhymes

**Comment by Supermichael777** [comment]
why do you want these there just glass

**Comment by polytheparrot** [comment]
RD MANAGED TO GET OUT OF HIS CAGE

**Comment by KorPhaeron** [comment]
I merged this early to help with the testing of the PR mirror if anyone wonders why

**Comment by Chnkr** [comment]
Thanks for that @KorPhaeron 👍

**Pull request merged**
