### PR TITLE
Adds assimilation bans

### LINKED ISSUE #45123: There's no hivemind/assimilation ban
See title, self explanatory, I checked under both names.

### PR DESCRIPTION
**Pull request by Kierany9**
Fixes #45123 and adds hivemind hosts to the banning panel

I have no idea how the admin tools work on the backend so tell me if i've goofed hard maintainers

This is purely admin shit that I'm not sure even needs to have a changelog

### CODE REVIEW

**Comment by ErwinSnowden** [comment]
How do you even get banned from hivemind? Everything I can think of should just be a general ban. It's not a ban from the one mind, but hivemind host, I don't think killing assimilated as the One Mind leader is against the rules anyhow but maybe?

tl;dr why is this needed?

**Comment by Shadowflame909** [comment]
There is no general ban.

An admin will just ban you from a large majority of roles. IE antag roles.

This which was previously unincluded, will not be included.

**Comment by ExcessiveUseOfCobblestone** [comment]
You'd only get banned from hivemind as a general antag ban.

**Comment by ExcessiveUseOfCobblestone** [comment]
on tg at least

**Pull request merged**
