### PR TITLE
Removes dream station

### PR DESCRIPTION
**Pull request by optimumtact**
Unmaintained and unliked, there are better options

### CODE REVIEW

**Comment by Mindustry** [comment]
but muh singularity hammer

**Comment by Keekenox** [comment]
Dear fucking god yes.

**Comment by Iamgoofball** [comment]
Inb4 Joan close

**Comment by peoplearestrange** [comment]
Third times a charm, why remove completely?

**Comment by jughu** [comment]
This is where our dream ends folk

**Comment by BeeSting12** [comment]
this is the only one i want removed tbh. bird and eff can just stay out of rotation unless we want to play them

**Comment by optimumtact** [comment]
@tgstation/commit-access

**Comment by ChangelingRain** [comment]
the result was inevitable
i'm going to keep around my failure as an example to ~~myself~~ ~~others~~

**Comment by optimumtact** [comment]
That doesn't make any sense, why are you keeping a shit map no-one likes around?

**Comment by Cheridan** [comment]
Joaaaan stahp.
the dream is dead

**Pull request merged**
