### PR TITLE
Sleepers put out fires

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl:
tweak: Sleepers put out fires
/:cl:

>You feel cool air surround you

Makes ya think...

### CODE REVIEW

**Comment by optimumtact** [comment]
Ah yes, I often walk into a freezer to stop a fire, because as we all know fires cease to operate when they're exposed to cold temperature, not when they run out of fuel

:-1:

**Comment by WJohn** [comment]
I don't know maybe you get blasted with some sort of cool smokey stuff that chokes out the fire yet remains breathable to you? This makes no sense nevermind.

**Comment by SamSamsonthe3rd** [comment]
It seems natural to me to expect something that says "You feel surrounded by cool air" to cool you down.
Perhaps the bed inside is a cold waterbed or something, and just makes you feel cooler.
Maybe (maybe not) make the sleeper actually cool down the occupant?
The only time I really see this coming into play would be for miners (Or a medbay from hell).

**Comment by WJohn** [comment]
Sleepers should make a water spray (like from a fire extinguisher) effect when opening/closing on their tile. It'll make it more obvious that there's a lot of moisture involved.

**Comment by bgobandit** [comment]
it should fuck up the sleeper and make it require repair

**Comment by SamSamsonthe3rd** [comment]
I picture it more like those pods from Avatar, lined with cooling gel or something futuristic.

**Comment by octareenroon91** [comment]
>Helps Plasmaman be _not on fire_

I support this change

**Comment by Niknakflak** [comment]
step 1. make a sleeper in maint somewhere
step 2. kidnap a plasmaman and take his suit off
step 3. shove him in the sleeper
step 4.  watch and laugh as he either attempts to escape and burns to death crawling towards you
or alternatively
step 4.1 he ghosts out and you laugh at that as well

**Comment by Cyberboss** [comment]
Plasmemes will still be being ignited so they'll die eventually

**Comment by Lumipharon** [comment]
If the sleeper was airtight, the fire would go out extremely fast, but you'd asphyxiate pretty soon after also.

Sleepers should be airtight and have their own air supply that can be turned on and off (or replaced with FUN), then this pr makes sense.

**Comment by Kromgar** [comment]
Why not have the sleepers be full of that gel that you can breathe?

**Comment by InsaneHyena** [comment]
(((Quality of life PR)))

**Comment by Dorsisdwarf** [comment]
I strongly dislike ""realism"" PRs which are unrealistic, so 👎

**Comment by FantasticFwoosh** [comment]
@Gun hog if its keeping the plasmaman alive without a suit by suppressing the flames, its basically a plasmaman iron lung machine.

> Pluck plasmaman out of the cloner immediately stash in the sleeper until you find a suit and keep them safe from people looking to potentially kill them by removing or injecting harmful chems.

**Comment by swindly** [comment]
I literally thought cryo tubes were literally supposed to literally do this.

**Comment by Armhulen** [comment]
literally literally literally literally cryo, dude.

**Comment by AnturK** [comment]
Just don't stuff people on fire into delicate medical equipment.

**Pull request closed without merging**
