### PR TITLE
fix gaping hole in tram lawyer office

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
image
image

due to the modular nature of tram's maints, you can't just go into the maints area to expand departments.
## Changelog
:cl: grungususs
fix: fixed the hole in lawyer's office on tramstation

/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
It's an open office environment, it's modern

**Comment by notfrying1pans** [comment]
I think in the pr you should put that you shrunk the size of the room, not just "patched up the hole"

**Comment by Sadboysuss** [comment]
> I think in the pr you should put that you shrunk the size of the room, not just "patched up the hole"

that's what the mapdiff bot is for, it used to be this size but it was expanded in the goldfish pr

**Review by Maurukas — APPROVED** [review]
I love modular mapping, it is the greatest feature.

**Pull request merged**
