### PR TITLE
Salbutamol overdose now gives severe stamina damage randomly

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: yackemflam
add: Salbutamols overdose randomly makes you feel weaker
/:cl:

Quit powergaming ya fucks

### CODE REVIEW

**Comment by Lexorion** [comment]
Why?

**Comment by yackemflam** [comment]
Name a downside to popping 20 salbutamol pills

**Comment by Lexorion** [comment]
Does a healing chem need a downside? Should we add minor burn damage to brute patches aswell?

**Comment by Kraseo** [comment]
Nice changelog, did you buy it off a chinese shop?

**Comment by MMMiracles** [comment]
@Lexorion I mean the whole existence of the overdose mechanic was to nerf healing chems by making it so you can't throw 1000u of assorted healing chems into yourself for changeling-tier healing.

**Comment by Ninja137** [comment]
To be fair here, the nerf was less to stop you putting a bunch of one chem, and more to stop you putting a bunch of eight different chems and our insane system processing them all at once and letting you outheal a Blob gangbanging your face.

**Comment by Xhuis** [comment]
Was very triggered until I saw that it was overdose.

**Comment by PKPenguin321** [comment]
Sleepers are the deadliest things in the game when upgraded

**Comment by erwgd** [comment]
Clones get loads of salbutamol while in the pod and they'll likely overdose with this.

**Comment by yackemflam** [comment]
And it only deals stamina damage

**Comment by yackemflam** [comment]
Can anyone give me a good reason to not implement this?

**Comment by yackemflam** [comment]
New idea

**Pull request closed without merging**
