### PR TITLE
Adds M1911 crate and single-pack to Cargo

### PR DESCRIPTION
**Pull request by TooFewSecrets**
## About The Pull Request
Adds M1911 crates to Cargo's Armory tab, at 2500 for one and 4500 for two, bundled with a magazine per gun. No option for ordering additional spare magazines to hopefully discourage Gun Cargo abuse like Mosins and WTs tend to get.

## Why It's Good For The Game
Security currently doesn't actually have a reason to ever order anything from Cargo, except in cases of supply shortages; the Armory plus all the guns at round start are always more than enough, with the only exceptions being Combat Shotguns that usually aren't practical except for arming the entire crew on Wizard and Operative round types due to size, and spam-ordering Laser Guns to fight the Blob. The M1911 is a more-powerful alternative to the Laser Gun with the drawback of being a ballistic, and currently is almost nonexistent because it's incredibly rare for someone to find one in deep space and make their way back to the Autolathe to print ammo for it. It would serve as a more-powerful lethal option for Officers when the station starts getting hectic, or as an emergency weapon issued to Heads of Staff for the same reason, while current Cargo-exclusive options are only really good for Gun Cargo - no Officer needs a Mosin Nagant, and no Officer can reasonably even use a Combat Shotgun. The high price point and lack of a magazine crate should discourage Gun Cargo - they'd probably rather just order a Russian crate and get armor bundled with more-powerful Mosins, or the even more powerful and less practical Combat Shotguns.

Yes, I know it's similar to the Stechkin, but size is the major drawback here - same for the researched ebow against the minibow, and a slug-loaded Combat Shotgun against a revolver. Pocket-size is an attractive enough attribute to keep it a reasonable TC buy.

## Changelog
:cl:
add: M1911 pistols are now available at the Cargo Bay thanks to a Nanotrasen salvage initiative.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I sure do like fighting cargo techs armed with weapons that rival what comes out of my uplink at no cost to them but considerable cost to me besides discretion. In a state of the game where budget cards exist and ballistic vests and helmets are cargo ordered, one is left pondering why I would ever bother buying any weapons out of uplink except Sleeping Carp if I could just play cargo and get my weapons that way, or there is some consideration that if I do not wipe the station clean of life as fast as possible I run the risk of these cunts in cargo arming themselves because guncargo is the fat meme nobody will let die. 

I already was abusing null crates as QM long ago and even before budget cards, so it stands to reason that providing a mass producable amount of weaponry that rivals traitor gear using nothing but funny money is not going to be a good idea.

It's bad enough we can mass order combat shotguns and lasers because of the havoc goof's economy system has played on cargo. We should not add a goddamn 30 damage spammable firearm for an entire crew to get and then go hunt antagonists with, whose weaponry is beginning to look a lot less special with every attempt to add one of these. If you want to keep this exclusive to sec, then sec should be the only ones who can order it in the first place.

**Comment by ExcessiveUseOfCobblestone** [comment]
gonna btfo cargo stuff until budgets get fixed

**Comment by TooFewSecrets** [comment]
Delete private ordering, honestly.

**Comment by Fox-McCloud** [comment]
Wasn't there a statement a while back to the effect of "no more ballistics for the crew; the shotguns are already bad enough and the security rifle pushes it sometimes"?

**Comment by SkeletalElite** [comment]
The auto rifle is kinda shit though. The only thing good about the auto rifle is that you can carry tons of ammo for it.

**Comment by Fox-McCloud** [comment]
I think that's the point.

The problem with a *good* ballistic is that it's just lasergun+ that you don't have to worry about ammo as much.

**Comment by nemvar** [comment]
again?

**Comment by Pugie** [comment]
Imagine private ordering lol just emp crates or put them in lava

**Comment by cacogen** [comment]
shoot me in the face

**Comment by optimumtact** [comment]
stop adding indivual guns to cargo

especially fucking ballistics

**Pull request closed without merging**
