### PR TITLE
Made it possible to exit the DNA scanner without help

### PR DESCRIPTION
**Pull request by lizardqueenlexi**
## About The Pull Request

Currently, when placed inside of a DNA infuser, by yourself or by someone else, it's impossible to exit without help - trying to click on it simply prints a "can't reach!" message. This PR changes this behavior in a couple of ways:

- Clicking the DNA infuser from inside will always open it (you still can't turn it on from inside).
- Trying to move while inside will open the door, much like the DNA scanner and other, similar machines.
## Why It's Good For The Game

It feels odd that the DNA infuser is an impenetrable prison if you get shut inside of it - something it's fairly easy to do on your own. Geneticists probably shouldn't be able to permanently imprison someone, accidentally or on purpose, with a roundstart machine. These changes make the behavior more-or-less identical to the DNA scanner - this is likely more intuitive, given that the scanner exists in the same room as the infuser.
## Changelog
:cl:
fix: Made it possible to leave the DNA infuser on your own.
/:cl:

### CODE REVIEW

**Comment by RikuTheKiller** [comment]
What about when it's locked???

**Comment by lizardqueenlexi** [comment]
> What about when it's locked???
> 
> I'd say to make it similar to cryo tubes where resisting will let you out after a while.

I don't believe the DNA infuser has a proper lock on it like the DNA scanner does, so I didn't see any case where you'd need to resist out. However, I _did_ forget to keep you from exiting via movement while the machine is running, so I've fixed that - you're stuck inside until it finishes.

**Comment by RikuTheKiller** [comment]
> > What about when it's locked???
> > I'd say to make it similar to cryo tubes where resisting will let you out after a while.
> 
> I don't believe the DNA infuser has a proper lock on it like the DNA scanner does, so I didn't see any case where you'd need to resist out. However, I _did_ forget to keep you from exiting via movement while the machine is running, so I've fixed that - you're stuck inside until it finishes.

It does have a lock button pretty sure.

Anyways, my take is still to just make it similar to cryotubes.

**Comment by tralezab** [comment]
Fixed in #71605

**Pull request closed without merging**
