### PR TITLE
Combat gloves in the syndie toolbox are now red.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Why not, eh?
@Cheridan

### CODE REVIEW

**Comment by SconesC** [comment]
Gross, no

Ruins the look of nuke ops

Literally why

**Comment by bustygoku** [comment]
why are they not disguised insulateds

**Comment by Incoming5643** [comment]
Because they come with a force 15 weapon and a multitool and still only cost 1 TC

It's the bargain of the century I tell you.

Also this doesn't impact nuke ops, it's literally only the gloves in the toolbox.

**Comment by Core0verload** [comment]
Why? :-1:

**Comment by freerealestate** [comment]
They should be disguised insulateds because otherwise wearing them is an instant announcement to anyone who sees you that "I'm a traitor"

Which means they should be balanced another way, either through increasing the cost of the toolbox or nerfing them

**Comment by Anonus** [comment]
I'm literally only doing this for the pun "caught red handed" 
Also, they used to be red insulateds and those were equally obvious and you're a traitor-y, and both are equally washable.

**Comment by Firecage** [comment]
Just make them yellow or black. Those are common.

**Comment by Core0verload** [comment]
They are black now.

**Comment by bustygoku** [comment]
If having normal colored gloves is a problemw ith the price then just up the price!!!!??????

**Comment by Incoming5643** [comment]
Having cheap items is a good thing, especially when it comes down to just a single TC.

Or do you want more soap?

**Comment by RemieRichards** [comment]
@WJohn opinion, sprite manager?

**Comment by WJohn** [comment]
I personally am not a fan of the gloves being red. The rest of the base syndie attire is all black, so it doesn't really make sense to me to just have red gloves sticking out like a sore thumb.

Also, it'd give away traitors way too easily, and require you to waste time recoloring them to yellow if you've spawned the toolbox in secret, and otherwise add another "I am definitely a traitor" mark to someone who spawned a toolbox to actually escape someplace.

**Comment by freerealestate** [comment]
The black combat gloves still have the problem of immediately outing
traitors wearing them one examine. I'm not sure why they aren't just
regular insulated gloves, or at least combat gloves that are disguised as
insulated ones. Or even better, cham gloves that you can choose a colour
for to suit your uniform.

**Comment by Incoming5643** [comment]
we really don't want "wearing insulated gloves" to become soft meta for "this might be a traitor, search him"

Just don't wear the gloves everywhere, it's not hard.

**Comment by freerealestate** [comment]
Aren't insulated gloves common and desirable enough that there are enough non-engineers running around with them that random searching people with them (which is against /tg/ rules anyway) would be an ineffective way of discovering traitors?





I still prefer the cham gloves idea tbh, as not all uses of insulateds are active

**Pull request closed without merging**
