### PR TITLE
Readds non-persistent contraband filled smugglers satchels

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Smuggler's satchels have been re-added to the game. They no longer keep their contents and transport it into future rounds, but instead contain some random contraband when purchased. Observers will be able to see where smuggler's satchels have been hidden. A handful of satchels will spawn on the station (under the floor, of course) in random locations each round.
/:cl:

Smuggler's satchels have a legitimate purpose for stashing hidden stuff, which was their original purpose. So let's have them back. Also, contraband is fun, so have some free random contraband.

~~In a future PR I will have them spawn hidden on the station each round. Again, not with any persistence features, just to add more hidden fun stuff.~~

Ten satchels are hidden on the station each round.

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
My body is ready

**Review by Tlaltecuhtli — COMMENTED** [review]
what does this pr do? spend 2tcs for random toys and then hide it under the flood and it dosent spawn next round?

**Comment by k-k-karma** [comment]
there's no point to smuggler astchels anymore

**Comment by ArcaneMusic** [comment]
This is a good change, smuggler's satchels are all about building a safe spot to stash your loot mid-round, when the toilet cisterns just won't cut it.

Also, hunting for smuggler's satchels is fun. Sure, you're not gonna somehow find a syndicate reinforcement beacon in one, but who actually needed that?

**Pull request merged**
