### PR TITLE
Fixes lollipops triggering weldertank explosions

### PR DESCRIPTION
**Pull request by silicons**
Fuck.

### CODE REVIEW

**Comment by Bluespace** [comment]
Hahahahahah

**Comment by Arianya** [comment]
Remove lollipops 😠

**Comment by improvedname** [comment]
tumblr_static_tumblr_static__640

**Comment by KingPhilipIII** [comment]
Oh cmon. Lollipop weldertank incidents are hilarious. Definitely a feature.

Atleast keep emagged lollipops able to trigger explosions. If they're fired with enough force to cause considerable harm(think about it. You can die from them) then I think they could puncture a tank and cause a spark.

**Comment by ExcessiveUseOfCobblestone** [comment]
Fun police....

**Comment by kevinz000** [comment]
Emagged still can

**Pull request merged**
