### PR TITLE
[Deleted]

### PR DESCRIPTION
**Pull request by Spess-Rando**

### CODE REVIEW

**Comment by TrustyGun** [comment]
Uh why?

**Comment by TalkingCactus** [comment]
Just make the sprite cover the mouth like a real space/hard suit (and every other one) would.

**Comment by optimumtact** [comment]
There is no justification given for your change (buff) to the captains hardsuit and IMO helmets covering the mouth are an important balancing aspect of them that should not be overlooked and this will simply make the captains gear even more broken and over powered.

Strongly opposed

**Comment by Sligneris** [comment]
It's just misleading for captain's hardsuit helmet to cover mouth, considering the sprite literally does not cover it.

You still need a mask to breathe, so it won't just let anyone eat in space - and as soon as the sprite is changed, this flag can be removed.

**Comment by Steelpoint** [comment]
Or we can just put a few black pixels over the mouth area to cover it.

**Comment by XDTM** [comment]
>space-proof suit that keeps the mouth exposed

**Comment by Sligneris** [comment]
@XDTM That's what the sprite already is anyway, isn't t?

**Comment by XDTM** [comment]
The fix should be on the sprite then, no?

**Pull request closed without merging**
