### PR TITLE
Fix Hanukkah (again) and refactor Moth Week and Beer Day

### PR DESCRIPTION
**Pull request by jacklecroy**
## About The Pull Request

In case nobody noticed, it's Hanukkah right now, but the game doesn't know that.

So it turns out the unit tests I made didn't help since the event subsystem was using a two digit year. This means it was trying to calculate holidays for the year 20 AD rather than 2020. I also forgot to move Beer Day when fixing nth week holidays, and I found that Moth Week could be refactored to use an nth week holiday as well.

Also changing from a two digit year fixes an issue with the Space Station 13 Birthday holiday.

I've deleted the ww argument from holiday.shouldCelebrate since it's no longer necessary.

## Changelog
:cl: That REALLY Good Soda Flavor
fix: Hanukkah and Ramadan should be correct now.
fix: Space Station 13's birthday won't break after 2099.
/:cl:

I think this should be the holiday fixes for now.

### CODE REVIEW

**Comment by jacklecroy** [comment]
Also, there's been some arguments about holidays recently. Would people support converting them to a config json file or something like that?

**Comment by cacogen** [comment]
Ignore agitators. Do what you know is Right.

**Comment by interestingusernam3** [comment]
>Also, there's been some arguments about holidays recently. Would people support converting them to a config json file or something like that?

No.

**Review by Mothblocks — APPROVED** [review]
in some weird sense, despite having testing, i hope you somehow broke moth week again to continue the tradition if it not working literally every year in a row

**Pull request merged**
