### PR TITLE
multi seat vehicle riding

### PR DESCRIPTION
**Pull request by Militaires**
@remierichards what is it you wanted me to do with the passenger index or whatever bullshit? ill do it

### CODE REVIEW

**Comment by Militaires** [comment]
remie wont answer so ill figure it out.

i always do...

**Comment by Robustin** [comment]
Dont die on me. And add a nonlethal version of your Speedwagon damnit.

**Comment by Militaires** [comment]
@optimumtact it's stale

it's almost as if this is not moving forward cause every time i go to coderbus for help it's either full of people who dont code, people who dont want to code, or people who are afk and maintainers who wont reply when i ping them, hmmmmmmmmmmmmm...........................

@Robustin ill close this so citrus cant fuckit

**Comment by Robustin** [comment]
The worst enemy of a good plan is the dream of a perfect plan.

I tested multi-seat riding extensively, and while it had a couple awkward scenarios, it was still a very solid package and this is a really nice feature that's being stifled for silly reasons.

**Comment by Militaires** [comment]
let me get this working

**Comment by Militaires** [comment]
there's something wrong here...

**Pull request closed without merging**
