### PR TITLE
Replace disappointed.ogg with a homegrown tg version

### PR DESCRIPTION
**Pull request by optimumtact**
## About The Pull Request
This replaces the recent events ogg with our own version that everyone is free to use without being harassed by the station formerly known as hippiestation that I will not call hippiestation anymore as that was what admiral hippie requested of people

## Changelog
:cl: oranges
soundadd: disappointment has been reworked
/:cl:

if you are a downstream, feel free to port

### CODE REVIEW

**Comment by optimumtact** [comment]
I have requested a version from voice over pete, but that will take a while to fill the order.

**Comment by LemonInTheDark** [comment]
based?

**Comment by optimumtact** [comment]
based on what?

**Comment by Jordie0608** [comment]
Based on the hippie version.

**Comment by GuyonBroadway** [comment]
This version lacks grumpy old man energy that made the original funny. 

The text itself is actually just garbage, it was the absurdity of the thing that made it funny, you'd be better off just deleting it.

**Comment by optimumtact** [comment]
I can only disagree with you

**Comment by GuyonBroadway** [comment]
It really is just a shitty hippiestationl  in-joke that was only funny cus of the fiver actor yelling in his grumpy old man voice.

If you don't have that it's just a hippiestation in joke and provably not worth keeping.

**Comment by optimumtact** [comment]
I don't want to remove it I want to replace it with voice over pete, but this will do unitl then

**Comment by GuyonBroadway** [comment]
I'll hold my judgement till then but just sayin'

**Comment by optimumtact** [comment]
don't worry, if the normal one doesn't end up good, I'll ask him to make one where he's really angry

**Comment by GuyonBroadway** [comment]
It should sound rather like a Taxi driver who is mearly ready to retire and has been stuck in traffic all day.

**Review by Rohesie — APPROVED** [review]

**Comment by TheVekter** [comment]
I thought Yog was complaining about this, not whatever the fuck Hippie wants us to call it now.

**Comment by Rohesie** [comment]
It's their choice to erase their own legacy, really.

**Pull request merged**
