### PR TITLE
AI VOX announcements are now additionally sent through say(";[message]").

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

AI VOX announcements are now additionally sent through say(";[message]").

## Why It's Good For The Game

Accessibility is good.

## Changelog
:cl:
qol: AI VOX announcements are now additionally broadcasted over the radio.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
makes sense and will actually be pretty funny

**Comment by Mothblocks** [comment]
This could be better but it's also a hell of a lot better than nothing.

Future wishlist:
1. I wish it was possible to defer the text over the cadence of the AI saying it. Like as in, reserve a ton of empty space, then make the text visible word by word as the AI says it. Unfortunately, due to the current way the AI vox works (a serial audio channel), that's not really possible, and certainly won't be possible once I move us over to Festivox when we're all on Linux. So c'est la vie.
2. I wish the special ones like :shonk: etc were replaced with emojis and whatnot.

**Comment by LemonInTheDark** [comment]
Will that changelog entry work?

**Comment by Mothblocks** [comment]
No, I figured people should just use `qol`.

**Comment by cacogen** [comment]
should probably be an announcement tbh

**Comment by AnCopper** [comment]
So what about shonk swhitenoise and scensor?

**Comment by Mothblocks** [comment]
Check #2 on my wishlist

**Pull request merged**
