### PR TITLE
Adds Blob Ability: "Restrain Destructive Expansion"

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Adds this new button to the top of your screen as blob:
image

When you press it, you toggle destructive expansion. You won't smash airlocks and walls in this mode, _unless you manually click on them._

Turned on:
image

And shortly after turning it off again:
image

Tested: (Human) mobs, dense machines, glass windows are all still automatically attacked while in this mode.

**Additional bugfix I discovered with testing:** Automatic attacks against mobs/humans now properly apply reagent strain attacks, instead of a tiny unintentional amount of brute regardless of strain.

## Why It's Good For The Game

Stealthy-ish blob. You can now hide in a room without smashing through the walls and revealing your existence, until you deem it time to do so. /vg/ has this feature too, got the idea from there.

## Changelog
:cl:
add: Added Blob ability: 'Restrain Destructive Expansion'. Toggling it prevents automatic wall and doorsmashing.
fix: Automatic blob attacks against mob/living now applies the proper reagent attack
/:cl:

### CODE REVIEW

**Comment by IndieanaJones** [comment]
Warning you now, this is a massive buff to blob.  It also makes Networked Fibers essentially useless.

**Comment by Tlaltecuhtli** [comment]
time for stealth blob

**Comment by eeSPee** [comment]
Make it a fragile strain?

**Comment by NotRanged** [comment]
> Warning you now, this is a massive buff to blob. It also makes Networked Fibers essentially useless.

In the way that it makes early detection harder, yeah it is (if used properly). But when the alert hits, you're still going to have people combing every room -- especially the big ones. You'll still be found.

Networked fibers is in kinda shit spot anyway rn (imo), might need a slight rework or buff but that's beyond the scope of this PR.

>Make it a fragile strain?

no

**Comment by IndieanaJones** [comment]
> > Warning you now, this is a massive buff to blob. It also makes Networked Fibers essentially useless.
> 
> In the way that it makes early detection harder, yeah it is (if used properly). But when the alert hits, you're still going to have people combing every room -- especially the big ones. You'll still be found.
> 
> Networked fibers is in kinda shit spot anyway rn (imo), might need a slight rework or buff but that's beyond the scope of this PR.


Stealth is the least important part of what this does.  The really strong part of this is being able to use walls for protection, something blob isn't normally allowed to do (and generally for good reason).  If this goes through, a blob can park it in maint and simply flood maint with itself and force the crew to try fighting it in small hallways, where the blob will always win.  Therefore, the crew would need to have tools to disassemble walls, which limits the amount of combatants who can actually fight to a much slimmer number.

**Comment by NotRanged** [comment]
Valid point, will be interesting to see how that plays out.

Luckily, I made balancing blob a lot more straight forward https://github.com/tgstation/tgstation/pull/56306 so if this turns out to be far too powerful (I don't think it'll be *that* bad) just give the define file a balancing smack

**Comment by IndieanaJones** [comment]
> Luckily, I made balancing blob a lot more straight forward #56306 so if this turns out to be far too powerful (I don't think it'll be _that_ bad) just give the define file a balancing smack

I think it'll be too much, mainly because this sounds like its going to make all blob strains into old Networked Fibers, sans the point generation involved but with auto expansion included.  Normally a blob destroys the room it's in, making your starter position and how much space you have important factors, but when walls aren't destroyed you get layers of protection which require special tools to destroy that you wouldn't have otherwise.  While almost all old blob strains were really bad, networked fibers essentially guaranteed a win against even the best of crews, and its ability to keep walls intact was a massive pro for it.

While /vg/ might be able to get away with a change like that, we also gave blob a number of buffs which /vg/ doesn't have, so I do feel this is going to push blob over the edge.  However, nobody else seems to share that sentiment, so might as well do it.

**Comment by LemonInTheDark** [comment]
Could you please elaborate on why stealth blob is good for the game? You skim over it somewhat, but I'd like to hear more justification for it

**Comment by NotRanged** [comment]
> Could you please elaborate on why stealth blob is good for the game? You skim over it somewhat, but I'd like to hear more justification for it

Blobs often die a pathetic quick death when they are discovered early, without putting up much of a fight. This isn't really fun for either side tbh. This gets more prevalent as server pop increases and you just have random people scouring every maint tunnel at all times. Not breaking through every wall and being able to stay within a single room while you build up _some_ infrastructure before having to expand out of it makes you a lot harder to detect in this very vulnerable early phase.

**Comment by Misdoubtful** [comment]
> > Could you please elaborate on why stealth blob is good for the game? You skim over it somewhat, but I'd like to hear more justification for it
> 
> Blobs often die a pathetic quick death when they are discovered early, without putting up much of a fight. This isn't really fun for either side tbh. This gets more prevalent as server pop increases and you just have random people scouring every maint tunnel at all times. Not breaking through every wall and being able to stay within a single room while you build up _some_ infrastructure before having to expand out of it makes you a lot harder to detect in this very vulnerable early phase.

Not to bash on the idea, I like it. But, if the issue is early blob loss wouldn't increasing the `OVERMIND_ANNOUNCEMENT_MIN_SIZE` and/or `OVERMIND_ANNOUNCEMENT_MAX_TIME` for blob solve part of this?

**Review by Mothblocks — CHANGES_REQUESTED** [review]
I don't think stealth blob sounds like a fun idea at all. Blob ends the entire game when it wins, and it wins often enough to where I don't want to give it aide in this manner.

**Comment by NotRanged** [comment]
> I don't think stealth blob sounds like a fun idea at all. Blob ends the entire game when it wins, and it wins often enough to where I don't want to give it aide in this manner.

It still announces when it reaches 75 tiles or x minutes, this just lets it survive the extremely vulnerable earlygame somewhat more regularly.

**Comment by Naloacisamazing** [comment]
Blob is already one of the easiest antags to win as if you know the basic strats for it. This makes it so its much MUCH easier. what normally kills good blob runs is reinforced walls going down meaning the weaker blob nodes have to put up the same ish fight as reinforced walls which costs alot of resources, making it so blob doesnt auto take out these walls is such an incredible blob buff I with no word of exaggeration believe it will cause me to never lose as blob again which isnt exactly fun

**Comment by Jared-Fogle** [comment]
It's a :-1: from me, I don't think blob needs buffs like this, especially in the vein of trying to stay hidden.

**Comment by NotRanged** [comment]
Could it be an option to make it last for the first few minutes only, until announcement, or until a tile gets attacked? To avoid the big balance issues of using walls as cover.

**Comment by Jared-Fogle** [comment]
I really don't think blob needs any buffs, even in its weak beginning state. If it does, this is the wrong way to do it I feel.

**Comment by IndieanaJones** [comment]
I think if you really wanted to do something which would help blob feel better in the current situation, what you could do is make blob scale based on the crew size.  Right now we send the same blob at 20 people as we do 70 people, which is a bit of a problem when you consider that the blob is expected to fight pretty much every other sentient thing in the game to win.  But yeah, if you want to make a solid, constructive blob change, I definitely think that's your best avenue.

**Pull request closed without merging**
