### PR TITLE
Updated the readme!

### PR DESCRIPTION
**Pull request by Petethegoat**
Readme now points to https://github.com/tgstation/-tg-station instead of http://code.google.com/p/tgstation13.

### CODE REVIEW

**Comment by Militaires** [comment]
it all began here.

**Comment by PKPenguin321** [comment]
Very insightful

**Comment by Qbopper** [comment]
he was #1

**Comment by balohmatevz** [comment]
There were about 5700 commits before this, from the SVN era. Here's where it actually began:  https://github.com/tgstation/tgstation/commit/757ea7b077f6b86ab6e4392808e773eea975338d

**Comment by Qbopper** [comment]
You don't understand

[He was number one](https://www.youtube.com/watch?v=RS7mk-UtdjQ)

**Comment by calzilla1** [comment]
So many fucking references

**Comment by deranging** [comment]
oh hi mark

**Comment by AlcaroIsAFrick** [comment]
O_O

**Comment by plapatin** [comment]
necro bump

**Comment by cacogen** [comment]
pete come back

**Comment by Cyberboss** [comment]
Don't ruin a good thing people.

**Comment by interestingusernam3** [comment]
a

**Pull request merged**
