### PR TITLE
adds a new ambience for when you're in space.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
sounadd: adds a new ambience for when you're in space.
/:cl:

I've made the track myself in LMMS.

https://vocaroo.com/1iA1Q0ZmTxAF

### CODE REVIEW

**Comment by optimumtact** [comment]
bro just have both

**Comment by Serxule** [comment]
so i see space is now the ps2 intro...

**Comment by Qustinnus** [comment]
ok

**Comment by Qustinnus** [comment]
image
is this what you were talking about @Serxule

**Comment by wesoda25** [comment]
This sounds pretty good, what part of bad apple is it?

**Comment by Qustinnus** [comment]
none this time.
image

**Comment by MrDoomBringer** [comment]
honestly i kinda like it as an addition 
not as charming as title2 but has metroid prime 1/2 vibes

**Comment by Serxule** [comment]
> image
> is this what you were talking about @Serxule

i made what is known as a joke

**Comment by tralezab** [comment]
you know, reminds me a ton of endless dungeon music

**Comment by CoffeeDragon16** [comment]
Are we certain about it not replacing it? Personally I find robocop to be very loud and tinny. I stop sounds every time I hear it, as it's deafening and doesn't need to be both a menu and space theme.

**Comment by Serxule** [comment]
> Are we certain about it not replacing it? Personally I find robocop to be very loud and tinny. I stop sounds every time I hear it, as it's deafening and doesn't need to be both a menu and space theme.

I'm pretty sure you can change the sound level because I don't find it loud at all

**Comment by CoffeeDragon16** [comment]
Yes, but as far as I know BYOND doesn't have customization for ambiance loudness particularly, so I'd be forced to turn everything else down a lot, or just constantly keep stop sounds on standby when I'm in space. I find this much jankier than the alternative of keeping it in just for the menu.

**Comment by wesoda25** [comment]
Not gonna lie, having robocop come on while I'm in space is one of my favorite things in the game. I find it very nostalgic and atmospheric.

**Comment by MrDoomBringer** [comment]
robocop is not only an absolutely fitting song but such an iconic part of ss13's soundtrack. I feel like you'd be hard-pressed to convince other players on its removal, even if only from space ambiance

**Comment by maxymax13** [comment]
dilbert 3 song very good but this song also good? how?

**Comment by Qustinnus** [comment]
@maxymax13 no i've pr'd a bunch of melodic ones that I implemented for someone that they made themselves.

**Pull request merged**
