### PR TITLE
removes RNG from emagging cyborgs

### PR DESCRIPTION
**Pull request by Iamgoofball**
literally WHY was this a thing oh my god it's so fucking annoying

no other fucking situation can allow me to fail to emag something

this is just retarded in every way, shape, or form

AND THE FACT THAT I CAN FAIL IN 2 DIFFERENT PLACES IN THIS WITH AN EMAG IS HORRIBLE

### CODE REVIEW

**Comment by SeikoTheSeal** [comment]
>no other fucking situation can allow me to fail to emag something

You never tried to emag an APC eh?

**Comment by Iamgoofball** [comment]
@SeikoTheSeal that can go too

**Comment by freerealestate** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
:+1:  x :100: 

Literally the most retarded thing about emags ever.

**Comment by Dorsisdwarf** [comment]
:-1:

**Comment by freerealestate** [comment]
:+1:

**Comment by Thunder12345** [comment]
I thought the point of this was to cut down on drive-by emaggings? Now it's 100% to just hold emag and crowbar, click pgup click pgup click borg emagged, when before there was a risk of failing and getting dunked.

**Comment by xxalpha** [comment]
:+1:

**Comment by Anonus** [comment]
Like APCs randomly not being emagged, this didn't add anything, because if you could emag a borg you could click it enough times to ensue that it did get emagged.
It's not fun to deal with a random, messageless failure on something that can get you brigged or killed.

**Comment by Cheridan** [comment]
good change

**Comment by WJohn** [comment]
Do the same with APCs, there's no reason for there to be a fail chance on a stationary target.

**Comment by MrPerson** [comment]
There are better ways to stop drive-by emagging liek making emagging take time. do_after()!

**Comment by WJohn** [comment]
It's hardly drive-by emagging as-is. The process already requires you to emag the lock, crowbar them (which is VERY noticeable in both the inhands and the borg's own sprite), and then ANOTHER emag to subvert them. This 3 click process would require you to be painfully inactive to miss.

**Pull request merged**
