### PR TITLE
A new map for pubbies by pubbies

### PR DESCRIPTION
**Pull request by pubby**
I put together a map and it's ready to be played.

[Mostly up-to-date image of the map.](https://s9.postimg.org/x8pvxlb1p/pubbystation.png)

The idea was to create a lowpop map derived from my favorite parts of Box and Meta. The design is similar to both of those maps so hopefully that will make it non-controversial and easy to learn.

Anyway, path errors and merge conflicts are a huge pain in the butt so it would be best if this could get looked over and committed sooner rather than later.

:cl: Pubby
add: A new map: PubbyStation. Set it to your favorite in map preferences!
/:cl:

Tagging @MrStonedOne because he's a cool guy.

### CODE REVIEW

**Comment by GunHog** [comment]
Not a bad looking map, I am willing to give it a shot!

**Comment by FantasticFwoosh** [comment]
A area of morgue on that map hasn't been done correctly, re-upload the image please, also im personally keen to see the rest of the test site asteroid, i think its a good idea.

I like most of it, though i have some critical analysis
 
> there are only two solars, located to the west and east, that is 1 less solar array than standard and because the station blocks out (sunlight) there are two blind spots of the north and south making them inefficient, especially with the dense map

> If the cargo security office (or office nearby cargo disposals) was flipped around for coverage of the nuclear vault it would be better as it occupies a blind spot of HOP line and vault (you could also move the corridor doors down past the window. You could substitute the disposals sec door & windows so it all remains attached to cargo and you have a clean wall to put your intercomm and things on (beside a risk of people speedrushing into disposals to emag into that office to recharge use guns)

> EVA maint door access being as concealed as it is, especially near the theatre long discreet maint access is a risk and it would probably gain from having it removed so beside cutting down the reinforced walls its 1 point of entry

> There is no test chamber for toxins to test a mix in a enclosed space, which is pretty pivotal for working out mixes.

Beside from some additional teething issues this shapes up to be a VERY good station. You should feel proud, id happily play here.

**Comment by anconfuzedrock** [comment]
ai core looks a bit too unsecure

**Comment by CyberbossJHCB** [comment]
I agree, should at least be a double r-wall on the space sides, like box.

**Comment by XDTM** [comment]
Science hallway has no vents or scrubbers, but i like the map

**Comment by Shadowlight213** [comment]
I really don't like that you chose the efficiency telecomms design as it's a horrible design for comms. There's no reason to put replacement parts in the same room as the comms systen, since they'll just get blown up along with it.
Plus, telecomms is super remote, easy to get to and break into from space, and super hard to get to from the station.

**Comment by GunHog** [comment]
**AI Satellite:**
- Exterior shell has one R-wall in thickness, but seems to compensate for that with two extra turrets and a hardened internal enclosure. No match for anyone with an RCD or tools though.
- Interesting addition of an exosuit fabricator! It is missing its corresponding console, however.
- The chamber itself is missing a holopad.
- Fire alarm placement  seems weird.
- You have a golden oppurtunity here to pipe the AI Sat into Station Atmos. I obviously cannot tell if you have already done this from the picture though. The ability to plasma flood the Sat could more than make up for the weak defenses of the internal Satellite areas _outside of the chamber itself, which has strong interior defense._

**Science**
- I LOVE the Atmos/Toxins integration you have done here. You can take it a step further by having an atmos access tunnel to the incinerator room (and actually spawning the incinerator)! There may be a little 'disagreement' between Atmos Techs and Scientists on burn mixes, but it can serve as a collaborative effort for providing power to the station (or one side killing the other)

- The bomb range is actually an asteroid! I presume the suit storage there is the prototype hardsuit?
I like the idea, and can be good for some bomb testing in a location they are actually "intended" to be used! 
- The refinery is the obsolete smelter, any Scientist with half a brain will replace it with the superior ORM, which allows them to get more minerals as well as offer points to the miners.
- Why is there a floating, extra air alarm in the security checkpoint?
- The main hallway and entrance are missing atmos systems.
- Why is there a broken console in the RD's office? (CMO has one too)

Overall, and interesting map and things you have done with Science. I would love to see how the interactions work out!

**Comment by pudl** [comment]
Don't just add two r-walls to the ai core, completely redesign it, it's actually the worst AI core I have ever seen on any map.

**Comment by CyberbossJHCB** [comment]
*cough*cough*ministation*cough

**Comment by GunHog** [comment]
Ah, Mini-Station. Just spawn the AI in Tcomms. DERP.

**Comment by PKPenguin321** [comment]
This looks like budget metastation, but at least it isn't dream.

**Comment by pubby** [comment]
Just pushed a commit with some fixed things. I'm not sure why those modular computer consoles were broken though - I don't think it's a mistake with the map.

Here's what the morgue looks like:


I'm taking note of all these suggestions so keep them coming.

**Comment by Militaires** [comment]
remember add crim crams like pens and folders, and almost excessively i swear it adds to much

my only advise i know jack shit about mapping

**Comment by MrStonedOne** [comment]
The build is failing because two rogue step_x got in the map. Having any of these defined in the map will break tile gliding (where byond glides objects when they move only 1 tile) because if you use step_x byond assumes you implemented your own tile gliding and turns off it's built-in one.

You will have to open the map file in notepad++ or some other high end text editor/IDE and find those defined var edits.

**Comment by MrStonedOne** [comment]
````
/obj/machinery/chem_master{
	step_x = 0;
	layer = 2.7;
	pixel_x = -2
	},
/turf/open/floor/plasteel/whiteyellow/side{
	dir = 9
	},
/area/medical/chemistry)
````

**Comment by pubby** [comment]
@MrStonedOne Should be fixed.

**Comment by GunHog** [comment]
Do you have an updated map image?

**Comment by pubby** [comment]
@GunHog No new map image yet, though I've only done very minor changes and so the original image is still pretty up-to-date. I'll compile a new image once the map gets merged.

Larger changes to the map (such as to AI sat and science) will come at a later date. I'm keeping the current changes minimal to prevent introducing new bugs.

**Comment by optimumtact** [comment]
Should this have similar max/min player requirements to bird/mini ?

**Comment by MrStonedOne** [comment]
Test merged on sybil. I'm gonna set it's max player count to 50 for now.

**Comment by MrStonedOne** [comment]
a spot of above botany storage has a broken distro pipe, there is a grill underneath it hiding this fact.

**Comment by PKPenguin321** [comment]
consider putting a second cryo tube where the table with the medical wrench currently is, then putting the table between the sleepers

**Comment by fizbump** [comment]
There don't seem to be any air alarms in the primary hallways, or if there are, they are very well hidden.

**Comment by pubby** [comment]
Latest commit should fix the bugs found during testing.

Wasn't fixed: the emergency pod still doesn't dock at the Centcom ship correctly. It's a harmless bug and the fix is trivial, but it involves modifying z2 and so I'd rather just wait and file a separate PR for that.

**Comment by Tacolizard** [comment]
this looks awesome except for the insecure ai sat and shadowlight's complaints about tcomms. this looks like it will be my new favorite map.

**Comment by CyberbossJHCB** [comment]
The AI sat isn't bad actually, just bolting the doors means traitors have to think of something while being shot and actually functions as a more secure double r-walls.

Here's some things I noticed.
Several camera blind spots, play AI to see them
one camera was turned off
areas without clear air alarms, fire alarms and APCs.
The inner AI core also needs a vent/scrubber so the air alarm can actually work.
The four AI sat rooms probably need cameras
CPH south need more fire door sets
Second cryo tube/oxycan/set of cryox beakers/port please

**Comment by Cheridan** [comment]
I think we have too many maps already. If people are liking this map then having it in sounds good but I think another one should go.

**Comment by PKPenguin321** [comment]
Remove dream

**Comment by Militaires** [comment]
@PKPenguin321 good man.


remove dream.

**Comment by Shadowlight213** [comment]
Remove box

**Comment by optimumtact** [comment]
Over my dead body

**Comment by nullbear** [comment]
remove birb

**Comment by MrStonedOne** [comment]
@pubby if you go to the debug tab, and press debug verbs - enable, there will be some new verbs, including a tab, called mapping, that has some helpful verbs for mapping things out

**Comment by Shapsy** [comment]
Shaft miners are unable to open the front cargo bay door

**Comment by Anonmare** [comment]
The AI satellite ought to have more motion cameras on it, specifically at the teleporter. There's also the issue that the taser turrets can't shoot through the glass so a traitor has a really easy time picking off the turrets behind the glass if he had the foresight to pack a laser weapon. Combined with the lack of motion detectors, you won't know someone's on your sat until they're right at the foot of the chamber.

**Comment by Aliannera** [comment]
The windoor in front of the AI is actually under the AI, effectively making it impossible/very difficult to hit with melee.

**Comment by pubby** [comment]
Posted another update.

@CyberbossJHCB 
I checked the cameras and they *should* all be there. Maybe the disabled camera you saw was one of the ones randomly disabled at roundstart? That happens on all maps. 

@Anonmare I've added heavy firelocks to the core which can block lasers.  Let me know if the motion cameras fail to detect movement. I think they will work a little better now though.

**Comment by CyberbossJHCB** [comment]
Medbay missing latex gloves and masks. Also 2 cryo tubes generally necessitates 2 oxycans

**Comment by Alek2ander** [comment]
Removing chaplain and librarian could mess with some gamemodes.

Possible concerns:
- Captain's office is 2 seconds away from space. Even if the HoS sees a jetpacking nukeop whoosh past the op will be emagging in faster than he could report it.
- The atmos hookup for security has CO2 instead of N2O. I don't think Nanotrasen is _that_ evil.
- Speaking of that area, the opportunities for false walls are immense. You can dismantle the rwall in relative safety from the execution room (no cameras, no traffic)
- Maint connects directly to CMO office, but not to medbay hallways.

**Comment by Supermichael777** [comment]
maint is a little to linear for my taste; ad some redundant pathways and complex sideroom and areas.

Overall the station feels small, but not cramped. the design naturally brings people together when they venture out of departments, while not making escapes impossible.

**Comment by soulgamer** [comment]
Unless this was changed the glass in engineering is single sheets of glass rather than full stacks.

**Comment by MimicFaux** [comment]
Head of Security's office probably shouldn't have normal metal walls. Makes stealing the locker trivial.
Space camera for armoury isn't a bad idea either.

**Comment by PKPenguin321** [comment]
AI still has a windoor on it making it so we have to edit its layer to allow people to interact with the AI. pls fix

**Comment by pubby** [comment]
Glass sheets, HoS office walls, and AI windoor should all be fixed. Maint was expanded a tiny bit.

The map should be stable now and ready to merge (knock on wood).

**Comment by Metacide** [comment]
Wow, this looks great!

Really look forward to seeing it run sometime, hope it gets merged soon to avoid conflict horror.

**Comment by optimumtact** [comment]
The map can't really conflict with anything because nobody else is making changes to it.

At worst it would be type path changes.

**Comment by CyberbossJHCB** [comment]
oh boy

**Comment by KingPhilipIII** [comment]
Hey. Didn't know where to say it, so I figured I'd come here, but Pubby is sorely lacking in AI holopads. I don't think there is a single one in science, and sometimes thats the only way to get a busy AI's attention.

**Comment by CyberbossJHCB** [comment]
On that note, CPH needs more extinguishers

**Comment by optimumtact** [comment]
@KingPhilipIII the best place will be the maps forum thread for pubby station

https://tgstation13.org/phpBB/viewtopic.php?f=11&t=7937

**Pull request merged**
