### PR TITLE
Removes peacekeeper borgs bolas

### PR DESCRIPTION
**Pull request by optimumtact**
These are still causing too much salt.

### CODE REVIEW

**Comment by WJohn** [comment]
So are secborgs being put back in or is this a clever way to have those gone, too?

**Comment by TechnoAlchemisto** [comment]
it just removes the bolas

**Comment by optimumtact** [comment]
oh dear I don't know why github split that over two lines

My deepest apologies

**Comment by coiax** [comment]
Oranges, stop this meme with the inaccurately named PRs.

**Comment by optimumtact** [comment]
it's oranges, and it's perfectly accurately named, I have no idea how that line split got in there sir.

**Comment by jughu** [comment]
If this PR comes trough its truly service borg 2.0

**Comment by Anonmare** [comment]
Too many memes oranges. I am obligated to disapprove of anything you make.

**Comment by Zilenan91** [comment]
Yep :+1: 

I support Mekhi coding but the borg shouldn't have ever been made in the first place.

**Comment by Steelpoint** [comment]
I once saw all of security die because a Peackeeper borg accidently bolaed the only two officer making it impossible for them to dodge the (hooped up on stimulants) traitor with a revolver.

I think bola's are shitty no mater who has them. :+1:

**Comment by PKPenguin321** [comment]
i said this would be an issue in the thread lol

**Comment by TechnoAlchemisto** [comment]
I'm pretty sure #18072 was a fix

**Comment by optimumtact** [comment]
This isn't a feature pr anyway.

It's a code removal so it cannot introduce new bugs

**Comment by coiax** [comment]
If it's a balance or feature PR, then it qualifies boyo. ;)

**Comment by Incomptinence** [comment]
Absolute weakness. 

Can't even take being slowed down.

**Comment by Shadowlight213** [comment]
>oranges tries to game the system
For shame.

**Comment by optimumtact** [comment]
Fixed

**Comment by Cheridan** [comment]
upvotes win looks like

**Pull request merged**
