### PR TITLE
Icebox Cytology Lab

### PR DESCRIPTION
**Pull request by EuSouAFazer**
## About The Pull Request

Adds the Cytology lab to Icebox. Cytology was literally unplayable before - without a roundstart vat you literally can't do Cytology due to https://github.com/tgstation/tgstation/pull/84235 . Icebox lacked a vat, a dedicated pen and a lot of stuff, so the icebox lab was added. In line with the other cytology lab, this one has a few unique advantage over other maps; namely, access to the icebox outside, a corgi (easy recipe for new cytologists) and a dead rat (exceptionally useful). 

Additionally, also adds a soy seed package in Delta's Cytology, to go with their hydroponics tray. In this map rather than a knife for butchering monkeys they instead get the hydroponics tray and soy, for an alternative source of protein.

image
image
image

With Icebox getting its own lab with a survival knife and Delta getting a source of protein via soy this PR makes https://github.com/tgstation/tgstation/pull/84688 redundant. The lack of knife in the Birdshot Cyto standing as a balance for it having several cell lines available inside of the lab.

## Why It's Good For The Game

Cytology is playable on Box again. Delta gets an extra source of protein for Cytology.

## Changelog

:cl:
add: Cytology Lab has been added to Icebox
add: Delta now has soy seeds on the Cytology Lab
fix: Cytology is playable again on Icebox
/:cl:

### CODE REVIEW

**Comment by AdipemDragon** [comment]
can't believe icebox will have 2 cytology labs now, since perma has it already

**Comment by TheVekter** [comment]
> With Icebox getting its own lab with a survival knife and Delta getting a source of protein via soy this PR makes #84688 redundant. The lack of knife in the Birdshot Cyto standing as a balance for it having several cell lines available inside of the lab.

This is acceptable, though I would have preferred you told me you intended to do this instead of just doing it behind my back.

**Comment by EuSouAFazer** [comment]
Does someone know why this is still runtiming?

**Review by Maurukas — CHANGES_REQUESTED** [review]
You are placing baby penguins on turfs with atmosphere they cannot survive, so they are complaining. 

These are controlled by `var/list/habitable_atmos`, `var/minimum_survivable_temperature`, `var/maximum_survivable_temperature`. You'll either need to make a subtype of penguin that can tolerate that atmos, or you'll need to move them to a turf they can breath.

**Pull request merged**
