### PR TITLE
Adds rechargers to the boxstation shuttle

### PR DESCRIPTION
**Pull request by BeeSting12**
See title. It's on the left table in the shuttle cockpit. Tested it earlier and it worked. Nevermind, the burnkit is back. First PR, lemme know if I messed up. 
:cl: BeeSting12
add: Nanotrasen has decided to better equip the box-class emergency shuttles with a recharger on a table in the cockpit.
/:cl:

Why: To recharge weapons obviously.

I'll fix any issues tomorrow afternoon, if any. Knowing me, there will be.

### CODE REVIEW

**Comment by Supermichael777** [comment]
but why do you need a gun on the arrivals shuttle?

**Comment by lzimann** [comment]
It's the escape shuttle.

**Comment by Militaires** [comment]
@Supermichael777 to shoot people who just joined the game

**Comment by Anonmare** [comment]
@Supermichael777 Wrong shuttle.

**Comment by Penguaro** [comment]
I don't see how this doesn't just contribute to end of round griefing...

**Comment by BeeSting12** [comment]
That's not really an argument against it. If it were solely for end of round griefing, then yeah, shit change. But I've had many times playing security where I've needed to recharge my weapon on the shuttle ride home/while I was waiting to leave. I've usually been able to do it, but not on the box shuttle. All other major map's shuttles have at least one recharger. (Not too sure about omega, but I know pubby, meta, and delta, all have a recharger or two.)

**Comment by ExcessiveUseOfCobblestone** [comment]
end of round griefing is not griefing though, so if it did promote that it's an ok change in that right alone.

**Comment by lzimann** [comment]
Can you keep the fire medkit? I believe it is pretty useful to have one there(heck, it even saved my life already once).

**Comment by BeeSting12** [comment]
@lzimann 
I'll get it done by the end of today.

**Comment by BeeSting12** [comment]
okie dokie i placed the burnkit on the table at the right of the cockpit versus the left so it doesn't block the recharger. updating PR title to reflect this.

**Pull request merged**
