### PR TITLE
Surgery-sound-fix

### LINKED ISSUE #65742: [BUG] Improper surgery noises when using ghetto tools
## Testmerges:
Master commit: [aa4551c1008883da8701d5a111cb3a8db63f408e](https://www.github.com/tgstation/tgstation/commit/aa4551c1008883da8701d5a111cb3a8db63f408e)
The following pull requests are currently test merged:
[#65625: 'Pingbus changes and improvements' by Watermelon914 at commit cd8865bb1b](https://www.github.com/tgstation/tgstation/pull/65625)

## Reproduction:
Attempt any surgery that requires a saw, use a knife, scalpel, or other ghetto tool for the sawing step. The sound played for the do_after in the surgery will not be the item used's tool use sound, and will instead always be a circular saw noise.

### PR DESCRIPTION
**Pull request by TheBoondock**
## About The Pull Request
When performing srugery steps that requires a saw, using ghetto tools would play the saw.sound despite the tools not having any motors. This pr fixes that and add some framework for future convertion of preop_sound to list() for fixing future similar cases

Fixes #65742
## Why It's Good For The Game
More consistentcy and code improvement to surgery sound code

## Changelog

:cl:
fix: Fixes ghetto tools playing inproper sounds when used during surgery step that requires saw 
code: add framework for future preop_sound conversion to list() 
/:cl:

### CODE REVIEW

**Comment by TheBoondock** [comment]
Agh why is the conveyor belt fix keep sneaking in

**Comment by TheBoondock** [comment]
I hate git

**Comment by JohnFulpWillard** [comment]
image

**Review by NamelessFairy — COMMENTED** [review]
CTF change review, I'm pretty sure this cause's bugs now post-limb-rework

**Comment by ZephyrTFA** [comment]
assault-in-progress

**Comment by TheBoondock** [comment]
Lets hope this doesnt make it to the milestone

**Pull request closed without merging**
