### PR TITLE
Cat buff: There's cat hair in the vents!

### PR DESCRIPTION
**Pull request by ChangelingRain**
> Cats can now ventcrawl and walk over tables.
> Cats take less damage from lacking air(and will thus survive longer in boxes) and can live in slightly higher and lower temperatures.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
wait why
i'm not disagreeing with this change but what prompted this

**Comment by bustygoku** [comment]
Furries.

**Comment by bgobandit** [comment]
KITTIES :joy_cat: :smile_cat: :+1:

**Comment by Anonus** [comment]
I played a round as Runtime and couldn't ventcrawl.
Cats are agile little shits, they should be able to go over tables.

**Comment by Cheridan** [comment]
sure why not

make sure cats have the evasion feat too

**Pull request merged**
