### PR TITLE
Add new chems to plants that allow foam effects

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This adds the following new chems to plants:

- **5% (5u) Sulphuric Acid to Novaflowers** 
- **10% (10u) Fluorine to Corpse Flowers**

When you combine this with existing chems in plants you can make fluorosurfactant with water that results in 50 unit foam effects when plants are harvested.  If you use Omegaweed with this, multiple those units by x4.  

To acquire all of these chems three different plants must be mutated, so foam won't be available at roundstart.  Also the foam effect only triggers on harvest.

BebeYoshi pointed out that other chems get unlocked as well:

> First, as a side effect of adding Fluorine to botany reagents arsenal, you allow these chemicals to be made:
> 
> Helbital: Does not worry me a lot, however it "allows" Helgrasp to be made, don't know if people would abuse it, but it is certainly interesting
> 
> Syriniver: If you have a gatfruit or randomly got Sulfur in random seed it's possible.
> 
> Convermol.
> 
> Haloperidol: Another brain damage chem, cool.
> 
> ClF3: This one worries me the most, even without using the fireball effect it is a pretty dangerous chemical, safely harvesting them will also be annoying and I believe the insta heat effect can also be abused, with densified chem and 100 potency you can make 26 units of it (I think?), more with omega weed, combine with the already deadly arsenal of reagents and it can get pretty nasty, I might be overreacting to it though...
> 
> Fluorosulfuric acid: You can already get it from deathnettles, I don't think getting more would hurt anything, specially since it already is 50% of the plant volume.

## Why It's Good For The Game

- Fluorine is a really toxic chemical for most plants but it [exists in tea tree plants and coffee plants.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4808922/#:~:text=Fluoride%20accumulates%20mostly%20in%20the,from%20drinking%20water%20%5B8%5D.)
- Sulphuric Acid is fitting for novaflowers since it causes burn damage

Having foam effects for plants should lead to some interesting possibilities both for grief and for silly gimmicks.

## Changelog

:cl:
add: Added new chems for plants.  Novaflowers now have Sulphuric Acid and Corpse Flowers now have Fluorine.  Combine these chems with a Carbon Rose to create foam effects on harvest.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Fluorine shouldn't be in the tea or coffee plants, can we put them elsewhere?

**Comment by the-orange-cow** [comment]
> Fluorine shouldn't be in the tea or coffee plants, can we put them elsewhere?

Deathweed, Corpse Flower, and Shadowshroom all have relatively few reagents for plants that usually need a hacked vendor and a branching mutation, and are somewhat thematically fitting for a deadly substance.

**Comment by timothymtorres** [comment]
Upon ingestion:
- Fluorine does 0.5 ToxLoss.
- Teapowder does 0.1 ToxLoss
- Coffee does 0.5 ToxLoss

https://github.com/tgstation/tgstation/blob/cf77fd39cfe294173762fb67c84971a5d76bfb64/code/modules/reagents/chemistry/reagents/other_reagents.dm#L939-L940

https://github.com/tgstation/tgstation/blob/2ff790863981eda4e2cf1fe2dcdc65040497f0b2/code/modules/reagents/chemistry/reagents/toxin_reagents.dm#L480-L497

https://github.com/tgstation/tgstation/blob/2ff790863981eda4e2cf1fe2dcdc65040497f0b2/code/modules/reagents/chemistry/reagents/toxin_reagents.dm#L21-L25

Both the tea leaves and the coffee do not produce fluorine when grinded.

https://github.com/tgstation/tgstation/blob/38f12b1052bb20e1bc2bb9e5aeefc22d00ad8b2a/code/modules/hydroponics/grown/tea_coffee.dm#L39-L44

https://github.com/tgstation/tgstation/blob/38f12b1052bb20e1bc2bb9e5aeefc22d00ad8b2a/code/modules/hydroponics/grown/tea_coffee.dm#L88-L93

I don't think these chems need to be apart of any other plant.

**Comment by BebeYoshi** [comment]
This PR is interesting but I have some observations:
First, as a side effect of adding Fluorine to botany reagents arsenal, you allow these chemicals to be made:
*Helbital: Does not worry me a lot, however it "allows" Helgrasp to be made, don't know if people would abuse it, but it is certainly interesting
*Syriniver: If you have a gatfruit or randomly got Sulfur in random seed it's possible.
*Convermol.
*Haloperidol: Another brain damage chem, cool.
*ClF3: This one worries me the most, even without using the fireball effect it is a pretty dangerous chemical, safely harvesting them will also be annoying and I believe the insta heat effect can also be abused, with densified chem and 100 potency you can make 26 units of it (I think?), more with omega weed, combine with the already deadly arsenal of reagents and it can get pretty nasty, I might be overreacting to it though...
*Fluorosulfuric acid: You can already get it from deathnettles, I don't think getting more would hurt anything, specially since it already is 50% of the plant volume.
Now that we know that combinations are possible with this PR, feel free to use this info to further discussion. Also I would like to add some of my opinion regard the other reagents being added to some plants:
Personally I don't like carbon being added to red onions, I like it being exclusive to Carbon Roses and Gatfruit, both aren't particular hard to get and this does not change balance in any way I think. 
Not a huge fan of adding acid to Novaflowers and Combustible Lemon, Lemons being mostly a meme plant and wielding fuel makes a lot of sense to be in it and Novaflower does not fit the acid but might be just me.

**Comment by the-orange-cow** [comment]
I'm also not a huge fan of some of the microdoses of reagents(the 1% and 2%s), but I suppose it doesn't really hurt anything.

For what it's worth, I don't think you can make Helgrasp  purely via plant synthesis.  I discussed this with someone who understood chem code a while ago, but it may have changed since then.

**Comment by timothymtorres** [comment]
I'm not very familiar with chemistry so I don't know how ph levels and purity come into play when harvesting and mixing chems from plants.  I based it on the assumption that each chem is "pure" and the rest of it gets ignored.

> This PR is interesting but I have some observations: First, as a side effect of adding Fluorine to botany reagents arsenal, you allow these chemicals to be made:

Thank you for making this list.  

I was focused on producing the foam and did not take into consideration that it opens the door to other chems.  If needed, I can just simplify this by making a plant produce Fluorosurfactant directly.  I did want to make it hard to achieve by requiring 3 mutations instead of 1, since plant foam can result in a powerful effect.

> ClF3: This one worries me the most, even without using the fireball effect it is a pretty dangerous chemical, safely harvesting them will also be annoying and I believe the insta heat effect can also be abused, with densified chem and 100 potency you can make 26 units of it (I think?), more with omega weed, combine with the already deadly arsenal of reagents and it can get pretty nasty, I might be overreacting to it though...

At max potency, Tea makes 10u of Fluorine and Blumpkins make 10u of Chlorine.  This results in 3u of ClF3 with the `Exothermic Activity` trait that only activates on harvest.  (that trait also requires mutated ghost chilli)  I don't think this is as potent as Meth explosions from Omegaweed but I could be wrong.  Also densified chemical does not double the chem.  It doubles the _capacity_ of the plant.  Instead of a plant having storage for 100 units of chems, it now has 200 units storage.

> Personally I don't like carbon being added to red onions, I like it being exclusive to Carbon Roses and Gatfruit, carbon roses aren't particular hard to get and this does not change balance in any way I think. Not a huge fan of adding acid to Novaflowers and Combustible Lemon, Lemons being mostly a meme plant and wielding fuel makes a lot of sense to be in it and Novaflower does not fit the acid but might be just me.

Carbon can be added to any plant since it's a universal ingredient apart of all plant life.  I picked red onions because it didn't look like it had any other useful chems for a mutated plant.

My goal with this PR was to have two doses of the same chem available for two different plants:

- A microdose (1u/2u)
- Big dose (5u/10u)

This allows creation of a big foam effect or a small one.  Nettle already has 50u does of acid, but I didn't like that it takes up a large percentage of a plant's chem reagents so I choose to give other plants acid in smaller doses.

**Comment by timothymtorres** [comment]
I slept on it and you guys convinced me.  It's very rare for other plants to use microdoses, and you can just alter a plant's potency to get a smaller dose.  Furthermore, tea and coffee plants already have a unique chem on them, and carbon exists for the rose so:

- Added Fluorine to Corpse Flowers
- Removed Acid from Combustiable Lemons
- Removed Carbon from Red Onions
- Removed Fluroine from Coffee and Tea
- Removed the microdose amounts

Updated OP with information.

**Comment by the-orange-cow** [comment]
"lynch botanist, spray tan medbay"

**Pull request merged**
