### PR TITLE
Halloweeeeeeeeeeeen costumes from Yog

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request
image
Tis the season to be spooky!
This adds costumes for the season, as well as some alternate forms for the clown to morph into.

GRU from https://github.com/yogstation13/Yogstation/commit/f4184e406b4a693c3dbc1149aff36af1fe81f56e#diff-82947a3c7d4a9df8ec5482da04bf2353f232e059a85b6dcbc943c42cf95f525b

jester, trickster, harvey, zoot, facebook, beaker, fez, penguin and basically all of them from https://github.com/yogstation13/Yogstation/pull/4893/files

artist from: https://github.com/yogstation13/Yogstation/pull/9966
## Why It's Good For The Game

It's October! Apparently, the amazing work that @Iamgoofball and his amazing crew done wasn't enough. So I trudged through other places to bring you costumes for the season!

Also something about gimmicks or whatever.

image

## Changelog

:cl:
expansion: Four item sets, nine individual costume pieces and a new costume crate have been added.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
reminder to make some fixes soon

**Comment by thestubborn** [comment]
> 
> 
> reminder to make some fixes soon- future prs with a negative gbp will be closed until you fix your balance

descs for the families items will count as fixes right?
lol

**Comment by necromanceranne** [comment]
> > reminder to make some fixes soon- future prs with a negative gbp will be closed until you fix your balance
> 
> descs for the families items will count as fixes right? lol

ye

**Review by Watermelon914 — APPROVED** [review]
code is fine, needs spritetainer review

**Comment by Wayland-Smithy** [comment]
I was hoping this would get merged in time for the toolbox event, but if not would you mind @thestubborn if I copied this to my repo?

**Comment by thestubborn** [comment]
> 
> 
> I was hoping this would get merged in time for the toolbox event, but if not would you mind @thestubborn if I copied this to my repo?

go ahead

**Comment by Twaticus** [comment]
they arent very good

**Pull request closed without merging**
