### PR TITLE
Removes gondola round end sound

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
del: Removed the Gondola round end sound.
/:cl:

It's just pure ear rape and about as funny as root canal surgery.

### CODE REVIEW

**Comment by imsxz** [comment]
speedmerge

**Comment by wesoda25** [comment]
see we want this because its so fucking awful and cringey

**Comment by Timonkeyn** [comment]
My ears ded pls restart

**Comment by GuyonBroadway** [comment]
Rather than just... Ya know, use audacity to level off the ear-rape bit?

**Comment by tuypo1** [comment]
It only gets you once, after the first time you have plenty of time to be ready for it before the ear rape kicks in.

**Comment by Shadowflame909** [comment]
if past revisions are correct maintainers will speed close


ear rape is apart of the maintainer direction they'd like to go in

**Pull request merged**
