### PR TITLE
Clicking the (F) link on AI speech while make you orbit their camera eye

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
> AI screams TRAITOR IN X
> click on them to see the action
> get their core instead

### CODE REVIEW

**Comment by WJohn** [comment]
#13726 really ought to have covered this but I guess not. Oh well, :+1:

**Comment by PKPenguin321** [comment]
surprising that this isn't already intended behavior. :+1:

**Comment by MrStonedOne** [comment]
@WJohn i only ensured ai eye showed up in the orbit list

**Comment by Chocobro** [comment]
FINALLY

**Comment by Shad0vvs** [comment]
@tkdrg I'm not sure if you want to make this work for binary AI chat too, in order to be consistant, as that still goes to the core.

**Comment by tkdrg** [comment]
It's a good idea. If someone coded that I wouldn't mind merging it, assuming the code quality is okay.

**Pull request merged**
