### PR TITLE
Biogen Refactor and Code Cleanup, Faster Biomass Conversion and No More Biomass Cap!

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
So, I looked at the Biogenerator code and there was just, _so_ much old and undocumented code, that I just spazzed out and started documenting and refactoring everything. There's now a lot less usage of contents lookups and for loops, and _almost_ everything is documented, now, too.

As for the changes, as you can see in the title, I made biomass conversion faster. How much faster, you ask? 5 times faster with default parts, up to 20 times faster with the best parts. It was painfully slow, and that's not fun for anyone.

I also lifted the biomass cap. It wasn't useful, it wasn't fun, and Melbert didn't really agree with it either. However, I enjoyed the look of the biomass going up, so I gave it a max visual amount of 5000, so you get to see it gradually filling up as you put your first 5000 biomass in. After that, you do you, chief. Watch the funny numbers go up all you want.

I also improved the maths so that it wasn't just rounding stuff constantly, and also gave a little bit more insight on how much biomass everything would cost you, down to two decimals. If there's no decimals, it won't show them, however.

<details>
<summary>Here's what that looks like now:</summary>
That's one screenshot per different decimal places, there's no trailing zeros because I think we can all universally agree that those look bad in this kind of setting.

image
image
image

</details>

There's now also more information displayed when you examine the biogen, namely, how many items it has stored, and how many it can hold. I also fixed the formatting a bit, so it looks ever so slightly cleaner.

Other than that, I just improved the code everywhere I saw it to be fitting, there shouldn't be any single-letter variables in there anymore, and the code should be more spaced out. Honestly, at this point, I wrote most of this code six hours ago so I don't remember all of it, and I'm too lazy to go through and check what I've changed again. Diff and changelog are there for that.

## Why It's Good For The Game
So, I'll be honest, there were two big reasons that motivated me to do this. First of all, the biomass cap. That was a little silly, anyone that has spent more than one shift in Hydroponics knows that you usually only put Watermelons in the biomass generator as they're usually the thing that nets you the most biomass. Botanists will generally stock the fridges first, and if they have a lot of excess, they'll put it in the generator if they want, but that's rarely what was done. I've talked with @MrMelbert about it and he gave me the go-ahead, as can be seen here:

image

The other reason was the excruciatingly slow processing speed, which I've fixed. So we're good now. :)

## Changelog

:cl: GoldenAlpharex
refactor: Went through and refactored a lot of the old code of the biogenerator, and made multiple improvements to its logic, which should hopefully make it behave more consistently. Nearly all of it is now also fully documented, so as to make it easier for anyone else that has to sift through it in the future.
qol: The biogenerator now processes items five times faster, up to 20 times faster if properly upgraded!
qol: The biogenerator is no longer capped on biomass. Its visuals will change up until 5000 biomass, but you're free to go as high as you'd like with it! Sky's the limit!
fix: Fixed the logic of the biogenerator that would make it so the amount of biomass used for recipes was wildly inconsistent. Now, there's no more back-end rounding up, it's all on the front end when it needs to be, so there's no loss or gain of biomass when there shouldn't be.
spellcheck: Fixed a capitalization issue with the seaweed sheets in the biogenerator recipes.
spellcheck: Fixed multiple inconsistencies between the messages sent to your chat by the biogenerator.
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
How does this change how the UI looks?

**Comment by MTandi** [comment]
To reach 5000 biomass you will need more than 200 watermelons of 100 potency. This is essentially the same as uncapped.

I've been monitoring how people use biogen on Terry for a week before that PR. 
The biogen was either filled with a little bit of biomass for some fertilizers, or filled with thousands of biomass that was never used. So the only way the cap affected people was that they couldn't dump items for biomass they don't need anyway.

The justification wasn't just about the fridges, it was also an incentive to upgrade items.
Now there is no point in upgrading the matter bins.

I wonder if there really was a case when someone had issues with the cap, and what was the case. Did they want to print 100 leather? Or 20 monkey cubes at once? The 500 biomass cap with lowest parts was enough to provide botany and kitchen with reagents for most of the shift.

Is there any real reason other than "the cap felt silly and Melbert felt the same"?
What is the case when botany should bother with part upgrades? 
Shouldn't we remove part requirements for machines that don't really benefit from them?
Now upgrading biogenerator is actually a bad thing, because you don't care about the prices and the cap anyway and it only consumes a lot more energy.

**Comment by GoldenAlpharex** [comment]
> To reach 5000 biomass you will need more than 200 watermelons of 100 potency. This is essentially the same as uncapped.

That's just twenty harvests, that's not a lot at all.

> I've been monitoring how people use biogen on Terry for a week before that PR. The biogen was either filled with a little bit of biomass for some fertilizers, or filled with thousands of biomass that was never used. So the only way the cap affected people was that they couldn't dump items for biomass they don't need anyway.

Okay, and what's the problem with people dumping biomass they don't need anyway? People are allowed to enjoy big numbers getting bigger in other departments, I don't see why it can't be the same here.

> The justification wasn't just about the fridges, it was also an incentive to upgrade items. Now there is no point in upgrading the matter bins.

Incorrect. If you want to be able to put more things to process at once, you need to upgrade the matter bin, otherwise you're still stuck at just 20. Which isn't a lot when you have more than one plant you already have over a hundred of in the fridge anyway.


> I wonder if there really was a case when someone had issues with the cap, and what was the case. Did they want to print 100 leather? Or 20 monkey cubes at once? The 500 biomass cap with lowest parts was enough to provide botany and kitchen with reagents for most of the shift.

The case is that it's enjoyable to see that biomass number go up. It doesn't make any gameplay difference to cap it, because it's not inherently "overpowered" when you have a lot. What's the best you can do, make a lot of boxes and clothes? Botany is all about basically producing stuff, letting people have a resource sink if they want to is perfectly valid, and I don't think it should be restricted, as otherwise for longer rounds you'd end up with too many plants and not enough space to fit them all.


> Is there any real reason other than "the cap felt silly and Melbert felt the same"? What is the case when botany should bother with part upgrades? Shouldn't we remove part requirements for machines that don't really benefit from them? Now upgrading biogenerator is actually a bad thing, because you don't care about the prices and the cap anyway and it only consumes a lot more energy.

They should bother with part upgrades because those make biogen prices much lower, and make it process _significantly_ faster now, alongside increasing the amount of biomass you get per item.


> And why did you add two decimal places? You don't have the cap and you don't care about the amounts and prices anyway. It only makes UI have ugly numbers.

Hiding away the numerals is never good when you can have something that will cost you as low as 0.04 biomass per unit. I made it elegant so they aren't present if they don't need to be, but it's a lot worse to hide away the true values when they can still wildly vary at that scale. At that point, that's just bad UX.

**Comment by GoldenAlpharex** [comment]
> How does this change how the UI looks?

I have the screenshots, I just genuinely forgot to put them in there. Give me a moment.

**Comment by MTandi** [comment]
So the reasons are:

- The cap wasn't really a hurdle for anything, we just want to see numbers go brrrr
- Botanists want to mancave and not care about part upgrades

If we're doing game design like this, then we should untie the temperature limits from the part tiers on termomachines. I don't really want to leave atmos too for part upgrades.

**Comment by GoldenAlpharex** [comment]
> * Botanists want to mancave and not care about part upgrades

Look, I already told you that this is just not true. There's still plenty of reasons to upgrade the biogen's parts, and it's just as desirable as before, without adding some tedium into what's ultimately meant to be a resource sink for a job that can produce an infinite amount of them. It helps free up the memory allocated to all of those items that would otherwise just sit in a fridge for the rest of the round.

It's like if you went in Satisfactory and put a points limit on the AWESOME Sink. That wouldn't make sense, that defeats the whole purpose of the machine.

**Comment by MTandi** [comment]
> Long time botany enjoyer here
> 
> I played a little recently with the refactored biogen, and was endlessly frustrated when it was full and I couldn't delete excess plants with it, which is mainly what it's used for since smart storages have a cap/ants exist/tons of items on the floor lags. I found myself either draining the biogen by spilling things on the floor or turning them in to seeds to get rid of them functionally that way.
> 
> It should absolutely be uncapped and isn't even comparable to atmos machines considering the overwhelming effects infinite temperature could have versus... infinite biomatter. Good change regardless.

This was exactly the idea. Users don't like changes that change their habits. You were supposed to be frustrated by this.

Biogenerator is not for utilization. Use fridge. If the fridge is full - use disposals, they are for disposing. Don't harvest if you don't need the harvest. Leave the harvest on the ground. Don't grow stuff that you don't need. You have options.

And from your comment I see that the assumption that botanists don't have any issues with prices and the lack of biomass was correct. You are just stockpiling on biomass that you will never need. That's why I made it process very long too - so that you can't utilize shit quickly.

**Comment by thgvr** [comment]
harvests don't need nerfing, most plants take 5+ mins to grow if you don't get a chem dispenser for the better things

I'm not sure if you play botany because a lot of the process especially with wild mutations (to do the botany experiment for upgraded tech) has you harvest things multiple times in a row, with a product you won't want to give or put into a fridge (fridges do not display if the thing is safe to eat/ what traits it has/ etc, only seed extractor does this).

I don't really think sitting and waiting for a bar to increase so you can use your basic, super slow chems (you won't have money to keep buying from the botany vendor, especially so if you are nonhuman because every single thing you need for your job costs money and you are paid less because ??? reasons)

Also in an earlier post of yours you said "500 biomass is enough for the kitchen and botany" i'm not sure where this comes from really, I had an experience where my biogen kept running out because I wasn't 24/7 tending to a watermelon plant that I made at the beginning of the round, because I wanted to do more complex projects. All of this is moot anyways when you think about bringing a chem dispenser into the equation.

Some stats on botany machines being upgraded would be ideal to see here as well, but that's not really feasible. I can say in my 100+ hours of botany I can count on one hand where another person came unprovoked to upgrade anything in botany, and even if you go and beg someone to do it you'll probably have to fight for a while. That's how it currently is with the experiment just to get shears so you can do the interesting part of your job, which is making custom plants via splicing.

Another thing you assumed is that every single botany player is going to be minmaxxing biomass to generate as much as possible which I just don't think is true, it's core job content to have those chems, and a little 10 minute effort at the beginning of the round or so to set yourself up to do your job for the rest of the round isn't completely unheard of in other jobs. Even then, this effort for botany could just be replaced with getting a chem dispenser if the biogen is too cumbersome to use without upgrades. Engineering can set up the supermatter with enough power for everyone in around that time, Medbay can make medical gels that will last essentially an entire round in even less time than that. Maybe if the biogen had some better things ADDED to it when it was upgraded, there could conceivably be a limit or a reason to greatly slow down biomass generation, but as it stands there isn't one and the basic chems are REQUIRED to do your job at all without spending every single credit you have, for every paycheck you get.

**Comment by MTandi** [comment]
@thgvr thanks for your feedback, I will make sure to go through the design document and have a discussion around it first before making any further balance changes.

>I had an experience where my biogen kept running out because I wasn't 24/7 tending to a watermelon plant that I made at the beginning of the round, because I wanted to do more complex projects.
Did you not have enough biomass for fertilizers? Are you aware that plants other than watermelons are also very good, since it also turns vitamins into biomass now?

**Review by Time-Green — APPROVED** [review]

**Comment by Time-Green** [comment]
Botanists can have a little salami

**Pull request merged**
