### PR TITLE
fuck you shitty admin lawset

### PR DESCRIPTION
**Pull request by Militaires**
:cl: fuck your shitty server
add: wanna know fuck you all you idiots this servers in mine now it's FUCKED
/:cl:

fuck your shitty server

https://tgstation13.org/phpBB/viewtopic.php?f=56&t=9277

### CODE REVIEW

**Comment by TehZombehz** [comment]
[Meme goes here] Also my keyboard is broken and my uncle works for BYOND and I have the secret super secret evil hacker group ready to bust you up you are so RUINED.

**Comment by ma44** [comment]
We can't even make this ya donk

**Comment by Militaires** [comment]
@ma44 requesting mapper to map this in

**Comment by TehZombehz** [comment]
This would fit right in to birdboat if you need to map it in somewhere.

**Comment by GunHog** [comment]
Add it to R&D so I can print it and troll the AI with it!

**Comment by jughu** [comment]
@militaires what really would be cool if you put in a upload module that you can insert multiple laws and uplpad them all at once then purging it and upload them 1 for 1 with the ai potenionally fucking you over

**Comment by Militaires** [comment]
@GunHog yeah but no one prints the rnd modules

**Comment by PKPenguin321** [comment]
Meme pr reeeeeeee

**Comment by bgobandit** [comment]
YOU MUST ALWAYS EAT ASS

**Comment by Armhulen** [comment]
you didn't even do the meme right, shame on you. seriously, SHAME!

**Comment by Militaires** [comment]
@armhulen yes i did

**Comment by Armhulen** [comment]
👁 👁 hmmmmmm

i'm keeping my 👁 👁 s on you

**Comment by vcordie** [comment]
this this is the best

**Comment by XDTM** [comment]
replace admin with AI to not ruin the immersion :^)

**Comment by Militaires** [comment]
@xdtm fuck you too

**Comment by DoctorPork** [comment]
@Militaires fuck myself

**Comment by Haevacht** [comment]
Stop.

**Pull request closed without merging**
