### PR TITLE
Nerfs uranium material effects, and changes how effective materials are on sheets and statues

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
 balance: Uranium material gives less radioactivity per unit
 balance: Sheets now have more material effects
 balance: Statues now have less material effects
/:cl:

this balances out how much radioactivity is created per single unit of uranium, realistically 1 sheet (2k units) of material will be 40 units of radiation. sheets (as in, the item, a sheet) only has 5% material effectiveness now though, so thats 8 units of radiation in practice.

Statues only have 50% material effectiveness now, instead of 100%

### CODE REVIEW

**Comment by optimumtact** [comment]
about time

**Comment by TheBonded** [comment]
Nooo my uranium statue engine

**Comment by LemonInTheDark** [comment]
I'm kinda annoyed that there's 2 constants that effect how many rads a sheet of uranium makes, but this is good, thank.

**Comment by Qustinnus** [comment]
One is related to the material itself and one is related to how effective all materials are on object s. Both are important to balance and exist for different reasons

**Pull request merged**
