### PR TITLE
Speed reagent reaction code

### PR DESCRIPTION
**Pull request by neersighted**
istypeless meme

### CODE REVIEW

**Comment by Iamgoofball** [comment]
reagents code does seriously need some speed up improvements, it's pretty laggy according to the profiler

**Comment by neersighted** [comment]
Its just plain bad in most cases... Anyway this should speed up a lot of loops.

**Comment by CPTANT** [comment]
The code is not only resource intensive it is also quite slow. If for example you throw a black powder grenade it first mixes the black powder, then it realizes ok I am hot enough and explodes around 1.5 seconds later.

**Comment by Iamgoofball** [comment]
No, there's an intentional delay.

**Comment by CPTANT** [comment]
wut, what kind of unintuitive snowflake bullshit is that.

Nobody uses grenades anyway because they already were completely not practical.

**Comment by Iamgoofball** [comment]
It's called flavor and balance. Nitro is stronger and harder to make.

Black powder is much more easily available and can be really fucking strong.

If it was just "water + potassium but better" than it wouldn't be as interesting.

**Comment by KazeEspada** [comment]
@Iamgoofball Black Powder needs an audible hiss and then to produce a very smokey explosion.

**Comment by neersighted** [comment]
Why are you people arguing in my performance PR. Take it to the forum, please.

**Pull request merged**
