### PR TITLE
Interview System / Soft Panic Bunker

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request

Ports and improves my interview system that has been previously used in the summer ball and toolbox tournament events. Allows for a 'softer' panic bunker, wherein players who fall below the required living time limit can still join the server and be restricted to filling out a questionnaire. Upon completing the questionnaire, the player may be allowed into the server by an administrator. If the application is approved, they get a notification that they will be reconnected and upon reconnecting will have all verbs as they usually would. If the application is denied the user is put on a cooldown after which they may submit a new questionnaire.

Players who are being interviewed (herein interviewees) have no verbs other than those required for the stat panel to function, as well as a verb to pull up the interview panel. Interviews do not persist through restarts, and the ability to join that is granted by an accepted interview is only valid for the duration of that round. 

Open interviews are listed under a new 'interviews' tab for admins, which is VERY similar to the existing tickets tab.

Below is what a player who is flagged as an interviewee will see when they join the server. They can do nothing but respond to the questionnaire or leave.
image

This is what an administrator sees after an interview is submitted, they will also see a corresponding message within their chatbox, and an age-old BWOINK when an interview is submitted.
image

The interviews tab, which is similar to the tickets menu. You can open the interview manager panel to view all active (including non-submitted) interviews, queued (submitted) interviews, and closed interviews.

image

### FAQ:
**What happens if someone submits an interview when no admins are on?** It's treated like adminhelps are, the message gets sent to TGS to be dispatched off to configured end-points (like Discord or IRC), and the user is notified that their interview was handled this way.

**Can you configure the questions?** Yes, in ``config/`` there is now a ``interviews.txt`` file in which the welcome message and the individual questions can be set and modified.

**Can this be turned on and off during a round?** Yes, it can be toggled like the panic bunker. It requires the panic bunker to be raised in order to function.

**Can interviewees have further questions asked to them?** Yes, if you admin-pm them, which is possible using regular means or a conveniently placed button on the interview UI, they will be able to respond to the message.

### Technical details

To use the interview system you must have the panic bunker enabled, this is an additional setting for the panic bunker. It can be set through the ``PANIC_BUNKER_INTERVIEW`` setting in ``config.txt``, or alternatively enabled in-game as prompted during the panic bunker toggling process. It also can be toggled on its own using a verb added for this purpose, ``Toggle PB Interviews`` found under the server tab. These new actions are included in the logging for the panic bunker. I have also added a reporting stat to the world topic  status keyword, which now reports if the interview system is on using the keyword ``interviews``.

As mentioned above, for server operators, configure the questions and welcome message in ``config/interviews.txt``.

Note to maintainers and those with big brains I had to add a call to ``init_verbs`` on the stat panel window being ready because seemingly a race condition exists wherein the ``add_verb`` of the 'view my interview' verb doesn't cause a refresh of the tabs (and therefore doesn't show the 'Interview' tab) when running in dream daemon but running it directly from visual studio code properly shows the tab. Adding a ``init_verbs`` call directly after adding the verb didn't seem to help.

### A note for downstreams

If you don't use the HTML stat panel (which may not be a bad thing) then you will have to do some conversion from the HTML stat panel stuff used here to the old style stat panels. It's pretty trivial, but just be aware of that. You can see how I used to use the old stat panels in my PR from the summer ball, [here](https://github.com/CitrusGender/tgstation/pull/113), which should be helpful.

## Why It's Good For The Game

This allows for a softer version of the panic bunker which impedes the flow of malicious players while allowing genuine players a chance to enter a round to gain enough time to not be affected by the panic bunker's restrictions.

## Changelog
:cl: bobbahbrown
add: Added the interview system, a 'soft' panic bunker which lets players who would normally be blocked from joining be interviewed by admins to be selectively allowed to play.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
eat hot chip

**Comment by ATH1909** [comment]
> Interviews do not persist through restarts, and the ability to join that is granted by an accepted interview is only valid for the duration of that round.

Does this mean that admins will be bombarded with interview forms after the end of every round/before the start of each new round? Or do you mean another kind of "restart"?

**Comment by Bawhoppen** [comment]
Perhaps it would make sense to note that this is just due to high server load in the welcome message? I feel for a new player, having to fill out a questionnaire might be kinda unpleasant, so atleast an explanation maybe would make sense.

**Comment by msgerbs** [comment]
> 
> 
> Perhaps it would make sense to note in the welcome message that this is just due to high server load? I feel like for a new player, having to fill out a questionnaire might be kinda uninviting, so maybe at least mentioning why would be for the best.

Is it any less inviting than just being silently disconnected with no feedback at all?

**Comment by bobbahbrown** [comment]
> > Interviews do not persist through restarts, and the ability to join that is granted by an accepted interview is only valid for the duration of that round.
> 
> Does this mean that admins will be bombarded with interview forms after the end of every round/before the start of each new round? Or do you mean another kind of "restart"?

They may, depending on the number of players who take advantage of the interview system. A persistence of answers through cookies is maybe possible, and may be something to explore.

> > It requires the panic bunker to be raised in order to function.
> 
> Would it be possible to remove this restriction? Perhaps we might want to use "interviews" that quiz new players on the rules and such under even non-panic bunker circumstances (multiple choice answer support in a future PR would be nice for these sorts of quizzes).

No, this is fundamentally how it works. It could be changed in a future PR but the intent for this system is to be in place as a tool to act as a 'soft' panic bunker. I'm not sure that this is much of as a concern as you think it is, because when the interview system is enabled alongside the panic bunker, as is required for operation, then the panic bunker is just forcing them to be interviewed to join/play. I'm not sure that moving it to some system that doesn't work in coordination with the panic bunker would change anything.

This was done namely to use the same configured settings (the required playtime limits) for the interview system, to minimize code/feature duplication.

> People like Mischief? have shown a remarkable ability to imitate new/innocent players- are we sure that these interviews will actually filter out anyone? Or is the intention not to filter people out, but rather to make playing on a new account somewhat annoying for griefers (as they have to fill out the questionnaire each time they want to use a new account)?

The latter is correct. This won't stop a person who is out to grief, but it will make it slightly more annoying for them to get in, slightly more possible for us to notice them, and all the meanwhile helps us to prevent punishing new players who are genuine and want to try /tg/ for the first time.

Mischief doesn't show remarkable ability to imitate new or innocent players, he's unremarkable. He just doesn't get noticed because we don't watch every player's move at all times. Don't help to inflate his ego.

With my intended use for this system it should make creating alts for playing a much more painful process, but I can elaborate on that with admins as time goes on.

**Comment by bobbahbrown** [comment]
> Perhaps it would make sense to note in the welcome message that this is just due to high server load? I feel like for a new player, having to fill out a questionnaire might be kinda uninviting, so maybe at least mentioning why would be for the best.

The welcome message is configurable, but the panic bunker is not always engaged for the same reason. Sometimes it is for high pop, sometimes for other things. I'll leave that up to the configuration, and I'll toss on a nicer in-game configuration of the welcome message and questions at some point today.

**Comment by optimumtact** [comment]
@MrStonedOne

**Comment by RaveRadbury** [comment]
I used this system during the summer ball and was able to handle nearly all of them on my own, and that was during a high traffic time.

This is a great system and I look forward to being able to make use of it on our normal servers.

Thanks @bobbahbrown for making this!

**Comment by MrStonedOne** [comment]
Notes:

Use the common config system. json config files are cancer and should only be used if there is a justifiable reason to.

Configs in the config controller can be overrideen by child configs (via $include), making my job easier wrt global configs. Because this interfaces with the panic bunker, which uses a combined config of shared configs and server local configs, making this system also support that is a must.

The interview window should not be closable, it should be treated as the lobby ready window for unapproved users. it should also have an updating field saying how many people are in front of them.

**Comment by bobbahbrown** [comment]
Will aim to incorporate changes later today. Got a few things to finish this morning then I'll toss that together.

**Comment by bobbahbrown** [comment]
@MrStonedOne Added those changes, the interview system now uses interviews.txt as a config file, and the interview window cannot be closed by those who are non-admin.

**Comment by kriskog** [comment]
@bobbahbrown Did you intend for the tab to be there all the time despite panic bunker and the interview system not being active?
image

**Comment by bobbahbrown** [comment]
@kriskog i didnt explicitly not have it display, it *could* be made to only show when there are interviews active -- i just didn't write any logic for that component

if you do choose to do this just make sure you account for the fact that interviews can be active despite the system being turned off (as it could have been switched off mid-interview)

interacting with the stat panel has been fickle at times

**Pull request merged**
