### PR TITLE
Clockwork walls are now about as hard for hulks to break as rwalls

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Clockwork walls are now about as hard for hulks to break as rwalls.
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
STAHP CLOCKWORK IS ALREADY STRONG THEY BASICALLY HAVE ALL ACCESS WITH THIS BRASS CONVERTER THING THEY ALREADY CAN DEFEAT XRAY WITH OCULAR WARDENS THEY ALREADY CAN CONVERT THE AI EASILY AAAAAAAAAAAA!!!!

**Comment by jughu** [comment]
So does this make the walls basically rwalls?

**Comment by jughu** [comment]
Why cant clockwork convert rwalls

**Comment by jughu** [comment]
What is this

**Comment by scoopscoop** [comment]
Adam's PRs are making this hilarious

**Comment by PKPenguin321** [comment]
Why do you keep making these PRs?

**Comment by CPTANT** [comment]
This might have actually been merged if you didn't name it "hulk touched me, please nerf" but "makes clockwork walls stronger"

**Comment by optimumtact** [comment]
@CPTANT except it doesn't do that all

**Comment by optimumtact** [comment]
oh never mind they changed the code underneath me

**Pull request merged**
