### PR TITLE
Stops the librarian from being scared of themselves

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
closes #35032

Apparently if a lizard plays a librarian, and hears the sound of their own hissing voice, it scares them

This is both funny and obviously not intended

### CODE REVIEW

**Comment by evsey9** [comment]
Feature

**Comment by praisenarsie** [comment]
wtf removing indiana jones referenc

**Comment by DaedalusGame** [comment]
just ban lizards from playing librarian

**Comment by Grazyn** [comment]
\>still calling the curator "librarian"

**Comment by Buggy123** [comment]
Feature.

**Comment by Xhuis** [comment]
could do a species check so it assigns as long as they're not a lizard? idk

**Comment by F-OS** [comment]
+1 to the check idea.

**Comment by awesine** [comment]
feature

**Comment by OmegaShoots** [comment]
http://indianajones.wikia.com/wiki/Snake

>Indiana Jones suffered from a fear of snakes brought on from when he fell into a crate of them aboard the Dunn and Duffy Circus Train in 1912 while trying to evade Fedora, from whom Indy had taken the Cross of Coronado. 

Get outta here

**Comment by ExcessiveUseOfCobblestone** [comment]
#35032 is a better alternative I believe

**Pull request closed without merging**
