### PR TITLE
Adds an absurd impossible to balance blob chemical

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Adds Networked Fibers, which gains points instead of automatic expansion and causes manual expansion near its core to move its core.
/:cl:

it does what?
it moves its core by expanding
but why?
because

### CODE REVIEW

**Comment by Cyberboss** [comment]
Meme PR?

**Comment by AdamElTablawy** [comment]
i'm just imagining a blob running around the station in terror fleeing hordes of welder-wielding assistants as yakety sax plays in the background

**Comment by TechnoAlchemisto** [comment]
So instead of automatic expansion triggering you get more build points? And when you place a square adjacent to your core it moves your core to that location?

**Comment by ChangelingRain** [comment]
Yup.

**Comment by Shadowlight213** [comment]
This is bleb snek isn't it?

**Comment by ChangelingRain** [comment]
Like snake but given that the blob can remove tiles at will it's more like GOD DAMN IT CATCH THAT CORE

**Comment by XDTM** [comment]
Blob yakety saxing was something i would never have imagined

**Comment by kevinz000** [comment]
:+1:

**Comment by KingPhilipIII** [comment]
This would be incredibly funny. And if you wind up getting it you're either a meme or you switch chemicals. I don't see a blob winning with this chemical.

**Comment by AdamElTablawy** [comment]
how cna you NOT see a blob winning with this chem

every time autoexpand fires you gain points

and if you wanna attack someoen you just balls to the wall rush them with your fucking core alongside your blobbernaut broskis

**Comment by ChangelingRain** [comment]
Winning with this would surely be a test of skill, rather than anything else.

**Comment by ExcessiveUseOfCobblestone** [comment]
"Oh boy I hope I get Slipmemes or EM.. damn it joan"

**Pull request merged**
