### PR TITLE
removes traitor gamemode

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

removes traotr gamemode

## Why It's Good For The Game

bad mode

## Changelog
:cl:
del: traitors are no more
/:cl:

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
Finally, some real change.

**Comment by leon2550** [comment]
:thinking:

**Review by actioninja — APPROVED** [review]
yeah ok

**Comment by optimumtact** [comment]
Congrats fucko 

anyone else want to earn a fucking darwin award?

**Comment by Qustinnus** [comment]
me

**Comment by Qustinnus** [comment]
wait no

**Comment by ErwinSnowden** [comment]
Democrats, the change that matters.

**Pull request closed without merging**
