### PR TITLE
Fixes king of the hill not resetting properly

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**

### CODE REVIEW

**Comment by RemieRichards** [comment]
I'm angry at myself for assuming "King of the hill" was the show and not the concept...
*sigh*

**Comment by PKPenguin321** [comment]
Tbh we should add propane as a new gas to atmos

**Comment by ike709** [comment]
i sell plasma and plasma accessories

**Comment by duncathan** [comment]
@PKPenguin321 plasma is basically a carbohydrate and if that doesn't work for you then we've always got volatile fuel

**Comment by PKPenguin321** [comment]
but does a plasma-fueled grill leave the taste of the meat in tact? didn't think so.

**Comment by KazeEspada** [comment]
Yes. Since plasma is SUPER propane. Not that charcoal shit they make in chemistry! Here at Arlen Atmosia. We supply the finest canisters of plasma and plasma accessories.

**Comment by PKPenguin321** [comment]
Actually while it leaves the taste of the meat in-tact, it also makes it extremely poisonous, so there's that

**Pull request merged**
