### PR TITLE
Updates libmysql.dll

### PR DESCRIPTION
**Pull request by JJRcop**
Updates libmysql.dll to version 6.1.6. Which, according to file data, was created on February 25th 2015.

It is nearly 323% larger than the current libmysql.dll which was added to the repo on September 1st 2010.

Closes #21289

### CODE REVIEW

**Comment by optimumtact** [comment]
get them to test merge this in case it somehow breaks the database handling.

**Comment by JJRcop** [comment]
By the way the MD5 hash for the libmysql.dll is ```163cfb0646b24177abc4f8490af370a6```, you will find that this matches the zip file included in b095b7ed279b33ff220431f6cf711c875e204220.
The MD5 hash for the zip file included in b095b7ed279b33ff220431f6cf711c875e204220 is ```1a8226c5b7947ac785cf5a3d90f507ad```, which matches what is on the website I got it from at https://dev.mysql.com/downloads/connector/c/

The SHA-256 hash for the libmysql.dll is ```B69732131DB1AD326556D65559AC3FD37F52A5F833A776D69C01BDF4574F5107```, which also matches what's in the zip, which has a SHA256 hash of ```E1D0CB15E01D03D07BCE5C92D46B0ED12864DDC7183B1D142CBF0EC02BF44D1D``` and if you download it yourself you can compare the two.

I completely understand that since I am updating compiled executable code that is not neatly sandboxed in BYOND that I am obviously a horrible malicious madman who injected a trojan into the .DLL and plans to take over the servers without anyone noticing, at least until proven guilty. This is fine with me, please verify the hashes yourself, download the .zip yourself from https://dev.mysql.com/downloads/connector/c/, compare the two, you will see this is clean.

**Comment by MrStonedOne** [comment]
Confirmed md5, sha1, sha2-256, sha2-512, sha3-512 hashes, gonna test it locally on the same version of mysql installed on the servers.

**Review by MrsTonedOne — APPROVED** [review]
Tests out fine.

**Pull request merged**
