### PR TITLE
PK borgs now have pepperspray

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR adds a can of pepperspray to the peacekeeper model's list of modules.

## Why It's Good For The Game

pkpepperaccurate1
pkpepperaccurate2

I may or may not have spent like 1.5-2 hours making that comic in MS Paint.

## Changelog
:cl: ATHATH
add: A can of pepperspray has been added to the peacekeeper model's list of modules.
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
I didn't like the idea much at first but the comic won me over

**Comment by Kylerace** [comment]
any pr with a custom comic should be merged

**Comment by ATH1909** [comment]
Thank you, AIIA, for pointing out that PK borgs have one eye, not two. I've edited the comic to reflect that.

**Comment by IndieanaJones** [comment]
peacekeeper_pepperspray_ca

**Comment by ATH1909** [comment]
holy shit I'm fucking dying

**Comment by ATH1909** [comment]
note that the PK borg there could have sprayed and pax'd both Sunglasses Man and Victim Guy if they were worried about Victim Guy taking their revenge. if they then continued to refuse to break up, the borg could then pepperspray->instant buckle->helpspin one of the parties away from the other and/or use some bolted doors to separate them.

**Comment by IndieanaJones** [comment]
also note that chances are everyone stowed away in the surrounding rooms from Mr. Murderboner is going to realize he stopped firing and come outside to stomp his face in.  While the PK borg can harm alarm them, it only takes one to flash our hero and then have everyone else curbstomp Mr. Murderboner into a fine red paste.

**Comment by ATH1909** [comment]
> also note that chances are everyone stowed away in the surrounding rooms from Mr. Murderboner is going to realize he stopped firing and come outside to stomp his face in. While the PK borg can harm alarm them, it only takes one to flash our hero and then have everyone else curbstomp Mr. Murderboner into a fine red paste.

perhaps, but there'd still be a _chance_ of Mr. Murderboner being successfully quarantined from the rest of the crew, and I believe that a pepperspray-endowed PK borg's chances of successfully quarantining a murderboner are greater than those of a pepperspray-less PK borg.

like, I could give the PK borg an evidence bag or something to hold a confiscated item (like a flash) in, but I think that that might push this PR over the edge. maybe they could get access to one via a printable upgrade or something in the future, I dunno.

**Comment by Mothblocks** [comment]
theyre not sec borgs

**Comment by LemonInTheDark** [comment]
They're not meant to "catch" anyone right? just prevent them from killing people

**Comment by Serxule** [comment]
for your consideration 
image

**Comment by ATH1909** [comment]
> for your consideration
> image

they can unbuckle, pepper spray doesn't hardstun

**Comment by Autisem** [comment]
PK borgs cant keep peace. they are clown modules without the bananium. I think adding things like this would really help the borg to actuely be capable of doing its job

**Comment by Mothblocks** [comment]
PK borgs are clown borgs in that they were literally added as a joke option, giving them pepper spray is just bringing them closer to sec borgs. Borgs are not meant to be provided with tools to stop antags. To quote oranges--"it has a fucking HARM ALARM for fucks sake".

I'm extremely skeptical that any maintainer actually wants this.

**Comment by Autisem** [comment]
>Borgs are not meant to be provided with tools to stop antags

It seems more likely they would have a gasmask to be pepper proof then sunglasses to be flash proof, which all borgs have. So I dont think this would really be the big antag stopper compared to regulair old flash

**Comment by moocowswag** [comment]
Outside of conversion antag rounds I really dont see this making the peacekeeper borg any better at stopping most antags.

But considering pepper spray protection isnt exactly the easiest thing to distribute to masses of people, a pk borg could would definitely feel alot closer to a ghetto sec borg during a rev/cult round.

Especially since silicon laws are often fought over and changed during these gamemodes, usually nonhumaning the conversion antag in question so mr pk borg could spray people for sec team to trample over.

**Comment by Nistishere** [comment]
Good PR.

Great comics, keep em coming.

**Comment by wesoda25** [comment]
Isn’t the joke that peacekeeper borgs can’t do shit. 

Anyways valid hunt borg bad

**Comment by wesoda25** [comment]
Peacekeeper borgs are the ultimate pacifists in the sense that they can’t do shit and only serve to annoy everyone else.

**Comment by Timberpoes** [comment]
I second Mothblocks opinions. I don't believe there is any maintainer appetite to merge this PR. It is a silly change which pushes Peacekeeper borgs closer to validhunting capability. As was stated so clearly when I tried to give them cable ties - they are not meant to be secborgs. They're a funny big ol' meme borg.

This is not to say they can't ever be improved, but this wouldn't be the appropriate way to do it.

**Pull request closed without merging**
