### PR TITLE
Bring back Kilostation v3.0

### PR DESCRIPTION
**Pull request by Maurukas**
## About The Pull Request

At the demands of the maptainer, this is the successor to #54020 and #54182

This replaces Pubbystation with Kilostation. Kilostation was originally created by Okand, you can read about it [here](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=22551). Kilo has been out of rotation for quite a while, as it was causing out of memory crashes for reasons no one could find. This was recently fixed in #54245 through the effort of quite a few people. Paxilmaniac brought the map back, I've gone through and done the necessary cleanup. Things that were identified from the test merges (including the SM), or I've found elsewhere should now be fixed. All the varedited atmos mixes should be gone, though there may be a few oddly edited icons remaining. 

Based on this map's history, this should probably be testmerged.

KiloStation-1scaled

## Why It's Good For The Game
kilofx

Kilostation is a cool map, and quite a few people are dissatisfied with Pubbystation.

## Changelog
:cl: Paxilmaniac, Maurukas and Cartographer-D
add: Adds Kilostation
del: Removes Pubbystation
/:cl:

### CODE REVIEW

**Comment by Kylerace** [comment]
inb4 another crash happens every round at 34 minutes

**Comment by Tlaltecuhtli** [comment]
are you gonna remove the warning strip lines from every door/ wall

**Comment by kriskog** [comment]
> 
> Kilostation is a cool map, and quite a few people are dissatisfied with Pubbystation.

What a funny coincidence. Pubbystation is a cool map, and quite a few people are dissatified with Kilostation 🙂

**Comment by Cyberboss** [comment]
This can stay around for testing purposes, but I'm strictly instituting a "no map additions or deletions" policy until the out-of-tree maps system is complete.

After this rust-g PR is merged, the final PR can be made.

**Comment by Fikou** [comment]
can u remove the assault on people's eyes before replacing pubby

**Comment by Maurukas** [comment]
This seems to be on hold due to the work on map loading.

Paxil has already made a pass over some of the most egregious areas when it comes to striping. I'll go through again and see if there are other areas that need to be toned down.

**Comment by EOBGames** [comment]
If you're just going to leave a comment that says "ermagerd my eyes stripes bad" please just save it, we're all aware that kilo needs a pass to reduce the visual noise and we don't need 50 variations of the same comment we've been seeing for the last year.

**Comment by Fikou** [comment]
> If you're just going to leave a comment that says "ermagerd my eyes stripes bad" please just save it, we're all aware that kilo needs a pass to reduce the visual noise and we don't need 50 variations of the same comment we've been seeing for the last year.

ok when will it happen

**Comment by Bawhoppen** [comment]
Besides the hazard stripes, are there still hostile mobs in maint? I recall Kilo's maint being *wayyy* out of control.

**Comment by Maurukas** [comment]
Rebasing this to post-JSON fixes. Map JSON is updated so this should be a loadable map if you checkout this PR now. As far as I know this is still blocked by rust-g.

Also decal cleanup is about 1/3rd done. **Over 600 hazard stripe decals have been deleted.** I'm not going to remove all of them, but microwave ovens, hand labelers and the diner certainly don't require them. These are going to be reigned back in until they're around areas/objects that are actually dangerous to the unwary, or unprepared spaceman. Or where removing them looks dumb.

There are still hostile mobs in maint, but it I would say it is far from out of control (except for the abandoned warehouse on the far asteroid, that is nuts). All of the mobs have their ability to smash things disabled, and are in areas of maint that require player action to open, such as breaking down a barricade, or unwelding an airlock.

**Comment by EOBGames** [comment]
@Cyberboss with https://github.com/tgstation/rust-g/pull/53 merged, what's the status of the block you put on this PR?

**Comment by Cyberboss** [comment]
Still need to do the changes here, with any luck I can do it starting Friday

**Review by Cyberboss — DISMISSED** [review]
Can you undelete pubby in this PR so it can be more easily test merged

**Comment by Bawhoppen** [comment]
Oh, another thing that should be probably looked at, is giving Kilo a fleshed out Permabrig. I know we never got around to doing Pubby's, but if Kilo is readded, it probably deserves to have one more along the lines of the other stations. I can take a look at doing it, if you're interested.

**Comment by Maurukas** [comment]
Agree that perma needs a look. Kilo was removed from rotation before it ever got touched, and it is even currently even tinier than Pubby's. Fortunately the current perma is directly adjacent to open space and a solar panel, so there's quite a bit of room to work with. I'll take a crack it.

**Comment by Cartographer-D** [comment]
If this does end up replacing Pubby, I will help work on the decals and other work it needs.

**Comment by Maurukas** [comment]
Cartographer-D has contributed a redesigned, mostly air tight prison, using only spare parts and supplies found in Kilostation maintenance. This should meet the minimum legal requirements for the housing of prisoners.

KiloStation-prison

**Comment by Bawhoppen** [comment]
Looks great to me!
Only minor feedback from me is:
Maybe a more distinct visitation could be ideal, but it's probably not that important
The window on one of the cells facing into the common area is a little odd I guess
Possibly a couple more contraband spawners could be good! Searching for those is a lot of the fun of being a prisoner sometimes, and they're not too OP or anything in what they give.

**Comment by Cartographer-D** [comment]
I forgot, the windows on the isolation cell are supposed to have a button on the outside where they can be closed. 
I'm good with adding the contraband stuff in more places.
I'm trying to give off the vibe that the perma on Kilo is barely maintained and basically thrown together, so the dressers are likely a relic of what was previously there and nobody bothered to move them.
I like the idea of visitation having the theme that it's a window into the daily life, like someone put it there deliberately for when corporate is going to audit and only put effort into that part of the station specifically so it could be showcased.

**Comment by Bawhoppen** [comment]
Ah right. Didn't realize that was the isolation cell. 
And the dressers make sense, I get it

**Comment by Tlaltecuhtli** [comment]
perma looks sad and crappy

**Comment by Cartographer-D** [comment]
> 
> 
> perma looks sad and crappy

I'm glad you like it!

**Comment by Okand37** [comment]
hello gamers i am also interested in this and would like to begin phase 2 of kilo: making the second z-level beneath the station which includes new facilities including head of staff bedrooms and more areas for places like chemistry and large-scale projects, also maintenance for tunnel rats and real rats

i am also happy to clean up decals as requested and will tone them down so they are less cluttered

@Maurukas thank you for your good work if you would be willing to have me help and begin work on phase 2 with your excellence let me know!!!

**Comment by stylemistake** [comment]
@Maurukas 🗞️🗞️🗞️

**Comment by Cyberboss** [comment]
I'll let this through, if oranges gets mad i'll take the flak. I need further incentive to finish out of repo maps anyway.

**Comment by SmArtKar** [comment]
Can we please get rid of one of the mooks in the rage cage? Two of them is just ridiculous

**Comment by wesoda25** [comment]
I don't want to appear impatient but I am starting to get really tired of pubby existing

**Comment by Okand37** [comment]
hello gamers here are some updates on the offices but progress has also been made on other lower parts of the station including security and medbay (rd's office soon:tm:)
image
image
image
image

**Comment by Jared-Fogle** [comment]
Apparently Lia's faction is still syndicate, and they attack the HoS.

**Comment by Okand37** [comment]
> Apparently Lia's faction is still syndicate, and they attack the HoS.

looks like the current map is using the old reskinned version of cayenne rather than the subtype for lia, i've let the epic gamers know :) thanks for reporting this!

**Comment by Maurukas** [comment]
This is currently test merged on Bagil for this weekend. Please hop on and try it out if you can. This is likely to be the final test merge, as we are now cleared to add the map.

These are the fixes I've got queued up so far. I'll try to get these into the TM if I can. Please continue to report any further issues or things you find either in this PR. The feedback so far has been overwhelmingly positive and extremely useful.

- Some fixes and improvements to the engine piping to make it a bit more clear where things are going, and get rid of some doubled up pipes
- RD office needs an R&D console (this was originally in R&D just next door, but got moved to the bridge)
- "Lia" is actually Cayenne wearing a nametag that says 'Hello, my name is Lia'

**Comment by Jared-Fogle** [comment]
Played a round, liked it a fair bit. Here are my only two complaints:

- Medbay is cramped, old Pubby/Box cramped. 
- CMO does not have engineering access unlike every other map, intentional or oversight?

**Comment by Okand37** [comment]
> Played a round, liked it a fair bit. Here are my only two complaints:
> 
> * Medbay is cramped, old Pubby/Box cramped.
> * CMO does not have basic engineering access unlike every other map, intentional or oversight?

Kilo station is intended to be used for a bit smaller populations (20-40ish) but should be able to function with a bit bigger. I'm currently working on the multi-z branch and am configuring the layout of medical. Cryo is being moved to the old cloning room, stasis is replacing the old cryo room, and the surgery theatre is being placed atop. Medical lower will include the chemistry plant (for easier access), surgery theatre B, and perhaps a second triage center. It'll be accessed by stair or elevator.
image

I wasn't actually aware the CMO had basic engineering access. My guess is that they were given access on other maps while Kilo was out of rotation and it just hasn't been updated. Nothing against it here if that's the status quo!

**Comment by Jared-Fogle** [comment]
That new medical looks solid to me, thanks for the rapid response time :+1:

**Comment by ATH1909** [comment]
why does pubby have to go, though?

pubby is unique.

**Comment by Jared-Fogle** [comment]
4 maps is our limit for maintainability purposes, at minimum until out of repo maps. Also, Pubby blows. Kilo is unique and cool and also good.

**Comment by Cartographer-D** [comment]
> 
> 
> 4 maps is our limit for maintainability purposes, at minimum until out of repo maps. Also, Pubby blows. Kilo is unique and cool and also good.

And yet someone (me) is actively working to completely overhaul Pubby and make it better. If a map is going to be replaced, it should be one that nobody cares about improving (box) and still has glaring problems / outdated design.

Yes, Chilled is supposed to EVENTUALLY replace box, but that's eventually. Chilled isn't done yet, and EOB has said himself that he isn't letting anyone else on the project because of how many times Chilled has been restarted. Ideally by the time Chilled is done, the out of repo maps will be done, too.

Doesn't make sense to actively de-incentivize active mappers when there's a clear alternative. I'd like to recommend that Kas replace box instead of Pubby as I continue to work on it.

**Comment by optimumtact** [comment]
You should have consulted the maptainer, edge, before doing your pubby overhaul then

**Comment by EOBGames** [comment]
Ultimately the choice is up to Maurukas, though I would consider Pubby to be the most suitable map to be replaced by Kilo due to their similar comfortable pops and general theming. That said, I would accept it as a replacement for Box too, if Maurukas decides that.

**Comment by Cartographer-D** [comment]
> 
> 
> You should have consulted the maptainer, edge, before doing your pubby overhaul then

The maptainer knows that I'm working on Pubby and has for a while. Also, I'm not Edge.

**Comment by Cyberboss** [comment]
eventually there will be only meta and icebox in this repo. Hold onto whatever changes you make. Eventually, whether or not any other maps are included will be decided by the administration team.

**Comment by LemonInTheDark** [comment]
I'm not sure how I feel about that

**Comment by maxymax13** [comment]
pr that melts all of the ice and returns boxstation to natural order when

**Comment by Maurukas** [comment]
I have to agree with EOBGames here. In the current rotation, Kilo can fill the role Pubby does, but better. I don't see Pubby routinely beating Kilo in a mapvote if they were both in rotation. Icebox offers unique features that are not currently in use in any other map we have.  While Pubby is my favorite map currently in our rotation, even I have to acknowledge that it has some significant shortcomings. I'll be keeping a copy locally to work on, and I'm probably not the only one. 

Since the testmerge update on Sunday I have received only a single item to address which is included in the latest commits. I believe everything is ready.

**Comment by Cyberboss** [comment]
Yeehaw

**Comment by Addust** [comment]
> 4 maps is our limit for maintainability purposes, at minimum until out of repo maps. Also, Pubby blows. Kilo is unique and cool and also good.

this quote has had severe consequences for expeditioners who like docking their whiteship stationside
because the whiteship dock is not on the station

**Comment by Mothblocks** [comment]
It's been 11 months, you've had time to add it yourself

In fact, there's still time! Hurry!

**Comment by Addust** [comment]
well good thing dream makers open, bad thing is, i know shit about making shuttle docks
do i just place the docking point below the airlock?

**Comment by LemonInTheDark** [comment]
Ask on discord, there are mappers and graphics that will help you with this
Not even to say it's a thing that should change, but I can outsource that decision to someone else

**Pull request merged**
