### PR TITLE
Nerfs the detective's revolver

### PR DESCRIPTION
**Pull request by tkdrg**
:cl:
tweak: The detective's revolver now takes three full seconds to reload.
/:cl:

### CODE REVIEW

**Comment by xxalpha** [comment]
If it has to be nerfed, I think this is fine.

**Comment by Zilenan91** [comment]
The nerf it needed, though not a crippling one :+1:

**Comment by TheNightingale** [comment]
Just leave it as it is. Making it take three seconds to reload doesn't affect its utility as a weapon against unarmoured targets, it just annoys Detectives who use it for its intended purpose (shooting eighteen rounds into an eshield user). If you need to change it, give it a loyalty-pin or something, so antags don't go on shooting sprees with it.

**Comment by tkdrg** [comment]
Well, in my opinion, the detective's revolver is OP because:
- It can reliably stun any unarmored target.
- It's got instant reload using constructable items.
- It's ballistic, and so reliable against constructs, eshields, etc.
Of course, all weapons have their advantages, but the det's revolver has all of those and more in one versatile belt-sized rugged package. In my opinion, its key feature is being the only ballistic handgun available to any loyalist, so I considered either a) this b) removing the speed loaders from the autolathe or c) making the revolver a two-hit stun. In the end I decided that b) wouldn't solve anything, and c) was a bit too harsh, so I ended up going with this. It's still very much an the best weapon on the station (think about what would happen if we gave security a six-shot taser that also deals brute and comes with two portable insta-chargers), it's just not as spammable anymore.

**Comment by Zilenan91** [comment]
You can still kill a guy with .38s because they'll be floored for longer than you can reload, but yeah this is good.

**Comment by TheNightingale** [comment]
If you're using a .38 against constructs, you're going to have a bad time. It's reliable against eshields, yes, but it's also the one counter on the station (riot shotguns barely tickle an Operative) to them; it's a unique item, like the HoS's gun or the RD's telearmour, so it's not as if they're ubiquitous.
The instant reload is the same as any ballistic weapon, and it's only special because of its one-hit stun - which is required, since it's the Detective's first and only line of defense. If Cargo is a hive of scum and villainy, you're going to have trouble getting more ammo - so the tradeoff with the .38 versus a taser (ammo-wise) is that the .38 has more upfront (6+speedloaders), but the taser is more reliable in the long run. It's designed like this because Detectives use all their ammo at once - they see a perp, blast them six times, then cuff them and go "... hey, sorry, I just did like 90 brute to you, let me get a medkit", whilst SOs conserve their shots, then recharge at the nearest recharger.

It's still got the tase-and-lase capability (tag someone with a .38 shot, empty a laser into them), and if you're using it for that, you won't care about a three-second reload.

**Comment by tkdrg** [comment]
> If you're using a .38 against constructs, you're going to have a bad time.

I've found it pretty useful for dunking juggernauts, myself. Not as good as a riot shotgun, but better than lasers for sure, at least if you're worried about friendly fire.

> The instant reload is the same as any ballistic weapon

Except it's the only crew-side instant reload ballistic weapon available from roundstart (shotguns being non-instant, and the sabr requiring research).

>and it's only special because of its one-hit stun - which is required, since it's the Detective's first and only line of defense.

Having a strong ranged stun from roundstart isn't required. In fact, only detective, security, and the HoS have that (plus Captain/HoP if they pillage a taser, and Chemistry if you want to get creative). The detective as a job would do just fine without a single-hit ranged stun, as they rarely need to shoot.

> If Cargo is a hive of scum and villainy, you're going to have trouble getting more ammo - so the tradeoff with the .38 versus a taser (ammo-wise) is that the .38 has more upfront (6+speedloaders), but the taser is more reliable in the long run. It's designed like this because Detectives use all their ammo at once - they see a perp, blast them six times, then cuff them and go "... hey, sorry, I just did like 90 brute to you, let me get a medkit", whilst SOs conserve their shots, then recharge at the nearest recharger.

The instant reload means it might as well be an 18-shot gun, plus it's more reliable in the sense that it doesn't need power and the recharger fits in your pocket. You'll never need more than 18 shots within a single firefight, and if you do then you were already boned from the start.

> It's still got the tase-and-lase capability (tag someone with a .38 shot, empty a laser into them), and if you're using it for that, you won't care about a three-second reload.

Yep. I think that's fine. It's still mostly a better taser in that role. Again, my issue with this gun is that unlike our energy guns, which generally do one thing and do it well, it can fulfill mostly any fairly decently. It's just way too versatile and powerful for something that's given away to such a low ranking job.

**Comment by Lumipharon** [comment]
There's literally a single of these in the game, and it is very very strong (against things that stuns and stam damage effect), but so what? What about it makes it actually OP?

Saying it can be e-shield users sure as hell doesn't count as e-shields are specifically designed now to ONLY work against energy projectiles. And for killing simple mobs/unstunnable shit like juggs, it does less damage then a laser, doesn't get the double damage bonus against carp and xenos, and requires the autolathe for more ammo.

And there's only 1 in the game, seriously.

**Comment by PKPenguin321** [comment]
let's add an instagib rifle that gives the user godmode and traitor status, but only spawn one and make it somewhere random in maintenance. there's only one so it's fine, right guys?

**Comment by Lumipharon** [comment]
Cool strawman.

**Comment by PKPenguin321** [comment]
i'm just saying that "there's only 1" isn't a very good argument on its own

**Comment by Lumipharon** [comment]
And it's not a argument I used on it's own - hence everything else I said in my post.

A detective with a revolver is still 2 hit killed with a .357, is still 1 hit stunned by a taser or baton, and is still horribly murdered by any number and angry killy things. The upside being that he can help the crew against very specific niche threats, can murder+stun people with the same gun (along with the hos) if need be, and doesn't get cucked by emp's.

A single dude with this item doesn't terribly effect balance - the average antag is going to be cucked by a sec officer with a taser just as well as a det with a .38

It's like the chaplain's memehand - its a strong item, but it's ok because only 1 dude has it.

**Comment by Fox-McCloud** [comment]
It also does 15 damage (only 5 less than a laser), stuns and induces stamina damage.

:+1: to this; it's already insanely strong, and the ability to just slap in another set of bullets is crazy.

Oh...and it can be modified and doesn't delete the gun when it backfires anymore, so you can pretty much load it with lethals with no real consequences.

It's basically like a taser and a laser gun in one, with quick reload---don't really care if there's two; it doesn't change the fact that this is ridiculously strong.

**Comment by Shapsy** [comment]
Having it explode on you and stun you in the middle of combat is a pretty hefty downside to loading it with .357

**Comment by Zilenan91** [comment]
Yeah loading it with .357 isn't something you ever do right now.

**Comment by Fox-McCloud** [comment]
>Having it explode on you and stun you in the middle of combat is a pretty hefty downside to loading it with .357

Doesn't even do this. It does 20 brute and drops it below you. And this only occurs 10% of the time with a full cylinder.

**Comment by Dorsisdwarf** [comment]
Source: I was a healing holoparasite during my master's hacked revolver rampage and I never had to save his ass or do anything other than minor patchups from the boom

**Comment by KazeEspada** [comment]
# HUGBOX :-1:

**Comment by YakumoChen** [comment]
>since it's the Detective's first and only line of defense

Detectives are not security though???

**Comment by TheNightingale** [comment]
@YakumoChen What if I told you lowpop Detectives exist? Someone has to be Security, and it's either the Detective with the gun and baton, or the Lawyer with a briefcase. If you use it right, any stun-capable gun is lethal - and Cargo can order taser crates by the dozen. Make the .38 an objective item if you're concerned about them not having a target on their backs - but realistically, the Detective is a target anyway, since they have Brig access, a Security headset, one of (if not both) the two forensic scanners on the station, and a cool gun. They need the cool gun to protect them against people who kill them for the other three, and so they can investigate crime scenes without getting instantly murdered by the criminal hiding in a locker.

**Comment by KorPhaeron** [comment]
Amusing that something with "speed" in the name will in fact be slower

**Comment by Fox-McCloud** [comment]
>Amusing that something with "speed" in the name will in fact be slower

Admittedly, you' still have to slide the cylinder out to reload it; I really doubt the detective's revolver is break action.

**Comment by Zilenan91** [comment]
Now that the antag det pr and the .357 det pr have stalled/been closed I don't really support this.

**Comment by HankMoodyExperience** [comment]
:-1: no el vagabundo nerfs

**Comment by Cheimon** [comment]
:+1:  Seems good to me, robust detectives can always follow up with a baton for a kill against human targets anyway, or just throw anything with force 10 (fire extinguisher, toolbox, possibly also their baton) to crit.  This seems fair without taking away most of its utility as a weapon.

**Comment by KorPhaeron** [comment]
In memory of @tkdrg

**Comment by HankMoodyExperience** [comment]
ABSOLUTE FUCKING MADMAN

**Comment by Lumipharon** [comment]
Can we please rename the speed loader to slow loader?

**Comment by Dorsisdwarf** [comment]
This nearly got me killed four times in a round.

The fifth time was when the RD wandered in and saw I didnt have an implant.

**Pull request merged**
