### PR TITLE
Removes player references

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl:
fix: Removes player references.
/:cl:

### CODE REVIEW

**Comment by Davidththird** [comment]
thanks goof ball

**Comment by DaydreamIQ** [comment]
You didn't even get all of them smh

**Comment by Fikou** [comment]
why are we replacing player references with names straight from media make up some new stuff

**Comment by JohnFulpWillard** [comment]
It should be named after me ( johnfulpwillard)

**Comment by Mothblocks** [comment]
you just gave him like 10 gbp with that priority high tag

**Comment by Mothblocks** [comment]
15

**Comment by Iamgoofball** [comment]
yes

**Comment by san7890** [comment]
@JohnFulpWillard i was KIDDING

**Comment by JohnFulpWillard** [comment]
It was high priority

**Comment by Mothblocks** [comment]
bro theyre star trek names

**Comment by moocowswag** [comment]
No high priority tag for a pr that doesn`t impact anything in game, why live.

**Comment by Jackal-boop** [comment]
Goof and oranges are making out rn

**Pull request merged**
