### PR TITLE
Hand Drill Sound is now smoother on the ear.

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

This PR changes the sound file for the Hand Drill use to have a slightly lower volume and mute some of the higher frequencies.

See here:
Old Sound: https://www.dropbox.com/s/fh1izswophi91gp/drill_use%5BOLD%5D.ogg?dl=0
New Sound: https://www.dropbox.com/s/kcanewdxqwliv9w/drill_use%5BNEW%5D.ogg?dl=0

## Why It's Good For The Game

The sound of the Hand Drill is generally a bit annoying, due to how loud and high pitched it is, and for some people it is particularly irritating and even headache inducing. This change slightly smoothens out the sound to make it easier on the ear, specially when using it repeatedly.

## Changelog
:cl:

qol: Makes the Hand Drill use sound quieter and less high pitched. 

/:cl:

### CODE REVIEW

**Comment by FernandoJ8** [comment]
Fixed the fact I accidentally doubled the file size.
Oops!

**Comment by Farquaar** [comment]
Doesn't really sound all that different to me, but if it fixes a problem that bothers some people it's whatever.

**Comment by LemonInTheDark** [comment]
surely there's a better way to do this

**Comment by Mothblocks** [comment]
i 100% have a problem where the current hand drill sound hurts my ears and this 100% does not fix it for me

**Comment by Serxule** [comment]
maybe make a new drill sound since this one still sounds like somethings bubbling (what even is that, anyways)

**Comment by CRITAWAKETS** [comment]
oh thank god i dont have to listen to WHRRRRRRRRRRRR anymore constantly as CE

**Comment by FernandoJ8** [comment]
> 
> 
> i 100% have a problem where the current hand drill sound hurts my ears and this 100% does not fix it for me

Hm, I'll try to change the sound a bit more

**Comment by Mothblocks** [comment]
i think its just an awful sound to begin with, im not sure you can fix the existing one

**Comment by FernandoJ8** [comment]
> 
> 
> i think its just an awful sound to begin with, im not sure you can fix the existing one

I'll try

**Comment by FernandoJ8** [comment]
https://www.dropbox.com/s/xpy8aw1lcc7ftaz/drill_use%5BNEW%202%20ELECTRIC%20BOGALOO%5D.ogg?dl=0

Thoughts on this new one?

**Comment by FernandoJ8** [comment]
https://www.dropbox.com/s/pk6vtthvrj3s2f3/drill_use%5BNEW%203%5D.ogg?dl=0

Also this one

I'm trying to do harsher low pass filters to completely remove some of the higher tones

**Comment by Mothblocks** [comment]
Last one sounds the best on my ears so far, though it's very muffled.

I'm fine with that one, since I don't want to require you make your own sound, but I think long-term that's the best path to go.

**Comment by FernandoJ8** [comment]
Hm, in that case I think I'll settle for the 3rd one. I might revisit this in the future and yeah, the overall sound needs to be replaced.
For the moment though, I trust this will do.

**Comment by Serxule** [comment]
this sounds actually.. pretty bad, it doesn't sound quieter, it just sounds like I have earmuffs on, which sounds bad with nothing else sounding like that

**Pull request merged**
