### PR TITLE
Revert "Removes ComponentActivated in favor of callbacks"

### PR DESCRIPTION
**Pull request by Shadowlight213**
Reverts tgstation/tgstation#33274

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Oh shit a get

**Comment by Armhulen** [comment]
wasted

**Comment by PKPenguin321** [comment]
nice digits but also i cant believe you've done this

**Comment by ExcessiveUseOfCobblestone** [comment]
!()[https://vignette1.wikia.nocookie.net/plantsvszombies/images/f/f8/RichaelMosen.png/revision/latest?cb=20151110211347]

**Pull request closed without merging**
