### PR TITLE
Removes the stamina version of .45 ammo

### PR DESCRIPTION
**Pull request by lilacrhododendron**
:cl: the big gay
del: The old stamina damage dealing .45 ammo has been removed. This only affects the 1911 handgun.
/:cl:

Why:
With other epic gamer loot getting nerfed, the latest bit of gamer gear was the 1911 handgun, of which a few are available with magazines pretty safely in a space ruin with a GPS signal. It's particularly powerful because of its' stamina damage. Functionally, all this change means is that the 1911 won't knock people into stamcrit in 2 shots anymore, on a regular human being it'll take 4 shots to crit someone with brute damage. I don't actually know if this will compile but if it doesn't I'll fix it up when it isn't 2 AM. 

In before someone still thinks the C-20r still did stamina damage.

### CODE REVIEW

**Comment by Gousaid67** [comment]
this is good, it was essentially a better disabler on top of being able to deal the same damage as the det revolver, while having 7 shots. :+1:

**Comment by HomocidlePancakes** [comment]
Brick Carr? More like BRICK NERD

**Comment by ExcessiveUseOfCobblestone** [comment]
good branch name

**Comment by Tlaltecuhtli** [comment]
i ded

**Comment by subject217** [comment]
name one time in the past month that you've killed me in game tlal, you literally can't

**Comment by necromanceranne** [comment]
if you thought old Det revovler was bad, the m1911 would make you puke blood as you don't even get the benefits of anti-stun against it.

**Comment by ATH1909** [comment]
Isn't space loot SUPPOSED to be really good?

**Comment by necromanceranne** [comment]
It's supposed to be good when placed behind a semi-difficult challenge to acquire. The m1911 has a beacon straight to it and no genuine threats to keep you from getting even just one magazine, and a laughable one from the second magazine.

You could get it 100% of the time with very little difficulty and very quickly if you knew what you were doing.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm fine with this but you could also make the ruin more difficult

**Comment by zxaber** [comment]
>Nerfing our lord and savior the 1911

**Comment by imsxz** [comment]
making a ruin more "challenging" is bad design generally IMO, there will always be a cheese around it or otherwise meta start to dealing with it in a foolproof way. Better to have loot just not aids in the first place. Look at snowdin or wild west for extreme examples.

**Comment by Gousaid67** [comment]
> you're intended to use the guns to fight the monsters inside
> 
> it's fine as is tbh.

i dont recall any monsters found in space being affected by stamina damage, really the additional damage would make the 1911 better for fighting in space ruins.

**Comment by subject217** [comment]
the point is that the guns are at the start of the ruin for a reason. if you move them to the end of the ruin to make it "not a loot zone" you destroy the whole point.

really if we wanted this to be *balanced* we'd give the c-20r a different ammo type. this is fine though, it stops the two shot drop.

**Pull request merged**
