### PR TITLE
Removes an infinite power cell from tram maintenance

### PR DESCRIPTION
**Pull request by scriptis**
## About The Pull Request

powuh

[Power!!! Unlimited POWER! [Sg14jNbBb-8].webm](https://user-images.githubusercontent.com/12202230/221448947-03965621-aabb-4a1e-94ef-b64be3f4c086.webm)
## Why It's Good For The Game

this is a debug item and shouldn't be here
## Changelog
:cl:
fix: removes an infinite powercell from tram maintenance
/:cl:

### CODE REVIEW

**Comment by Deathfox666** [comment]
i understand if not posable but i think it be neat if you replaced it with a normal cell called limited-capacity power cell

**Comment by MMMiracles** [comment]
what if instead of removing it from tram u added it to every other map

**Review by Mothblocks — APPROVED** [review]

**Comment by CRITAWAKETS** [comment]
what if you made it theoretically infinite in that it recharges

one watt per minute

**Comment by Sealed101** [comment]
look at how lavaland's tcomms maints do this joke and replicate it

**Pull request merged**
