### PR TITLE
Wowie! Crates!

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

image

^ wowie look at those!! don't they suck? (they don't).

this I feel the need to mention: due to the design of the crates being changed so that the lock indicator is on the lid, crates being locked/unlocked no longer show all the time. But that shouldn't matter too much. (clueless)

also this screenshot is kinda old, the bright lights on top of the crate now extends to the top of the lock and i fixed a bunch of minor issues, but it gets the main point across.

credit for the wooden crate goes to tau ceti, I was too lazy to redo it myself, so we get this inbetweener for now. it looks good enough.
## Why It's Good For The Game

they look better, and spritetainer think it looks better:

image

image

oh, and also

crate2
## Changelog
:cl: axietheaxolotl / viro
image: brand new crate sprites, wowie zowie!!
/:cl:

### CODE REVIEW

**Comment by IndieanaJones** [comment]
DO MIMICS STILL WORK

**Comment by Rex9001** [comment]
> DO MIMICS STILL WORK

Iirc mimics use the regular crate as its sprite

**Comment by zxaber** [comment]
They *do* look a little short, but they're also way more sci-fi. Beveled edge / 10.

**Comment by Sealed101** [comment]
might wanna move the manifest a tad lower, it looks goofy otherwise
изображение

**Comment by MTandi** [comment]
I know it doesn't matter how much we dislike these, but I'll say it anyway.
Default and wooden ones are an improvement, but the rest looks worse than what we currently have.

chest

The colors have a weird blue tint. 
Why medbay chest is gray and not white? 
The cross is too small, just like on the new medkits which are worse (hopefully someone resprites them soon again). 
The arms crates had this nice bump that made it look like an actual army crate. 
I don't see syndicate crate on the picture, and I hope it stays unchanged.

**Comment by SyncIt21** [comment]
They look like briefcases without handles. Also if you are making them longer it would only make sense to increase their storage capacity else what's the point?

**Comment by Thunder12345** [comment]
They look too flat to me. Style is a definite improvement, but they should really be taller because right now they honestly look like the bottom got cut off

**Comment by axietheaxolotl** [comment]
> The colors have a weird blue tint.

russian man discovers hue/blue-shifting for the first time.

> Why medbay chest is gray and not white?

because white crates look dumb

> The cross is too small, just like on the new medkits which are worse (hopefully someone resprites them soon again).

A. it's really not, and B. no they won't.

> The arms crates had this nice bump that made it look like an actual army crate.

ok and

> I don't see syndicate crate on the picture, and I hope it stays unchanged.

the only reason it wasn't changed is pure laziness on my end, if I had more motivation, I would change it. and I honestly might later.

> There are really so many outdated and obviously bad sprites in the game. Why do you touch something that already looks very good and is 3/4?

"very good" is an incredibly strong word, and so is "ok". They were sufficient for the time, but that time has passed. why don't you ask the person who made them lol, who, himself, said they "were starting to get a bit mid".

And, yes, there are, objectively, worse sprites currently in the codebase rn, but those aren't as apparent as crates, hence why, I did crates first. You can dig into lots of dmis and find the most dogshit sprites imaginable, but, they aren't shown very often, so it doesn't really matter whether they suck or not.

**Comment by MTandi** [comment]
>out of place

Be careful with this word

**Review by Imaginos16 — APPROVED** [review]
I think the funniest part about this PR is how the crate sprites I authored 6 months ago is now considered "soul". Y'all are wild.

**Comment by Comxy** [comment]
I think it looks to much like playdough with the thick lines everywhere and the giant button.

**Comment by TheVekter** [comment]
These look alright. Inoffensive, I suppose. I think the Security one could benefit from a red stripe along the side like with the other departmental ones. It's supposed to look like an army crate but it looks too similar to the non-Security one even with the star on it.

**Comment by ExcessiveUseOfCobblestone** [comment]
how are these an improvement from the previous? the old crates look like they have some depth and are cute+quaint, these look like they have very little depth but are much more fatty. Think it might be because the angle of the sprites are different or something, the new ones look more topdown than the old ones which look more front-facing.

Also the manifest should reflect the sprite changes if it hasnt been changed yet, that looks icky.

**Comment by NotSoEpikName** [comment]
why
realy why
old sprites was not bad. even good i can say
i cant say new sprites look bad too, them look kinda nice but have their ussies
but why you even wanted to change them? cause them old? cause you think it look ugly?
so why?

**Comment by Wallemations** [comment]
I'll be entirely honest that the bottom outline being on the very bottom pixel of the 32x32 box mixed with it not being all that dark makes it look like these don't have proper bottom cutoffs, and as such they look like they're sunken into the floor.

I'm not entirely opposed to them but I'd suggest raising them a pixel or two up just to prevent this, since right now they look super short. More like step-stools with a little opening rather than a full crate.

**Comment by SyncIt21** [comment]
The freezer crates are just bland and non distinguishable from regular crates

Take a look at the old sprites
Screenshot (244)
From first glance we can immediately tell the one on the right is the freezer because it's white painted giving it the impression of snow/ice. It visually enforces it's name of a freezer crate

Now look at the new one's
Screenshot (243)
For those of you who can't tell at first glance yes the one on the right is the freezer like what is this? It's not white painted it's simply white tinted, it look's like a regular crate but just shinier and to make up for that lack of difference you added a weird red vertical bar on the left, like what even is that for?

It get's worse look at the inside of the old freezer crate
Screenshot (240)
Again clean, you can see the white chunks of ice giving it that cold feel it's very nice overall all, no problem's until you botched that with whatever this is
Screenshot (241)
What is this? you we're too lazy to draw ice chunk's so you put blue lines seriously? it look's like a run down air conditioner that need's maintenance and even worse it's looks like a gas stove with light blue flames coming out of it.

I really don't understand what you were trying to go for but it's clearly not working

**Comment by TheVekter** [comment]
There's good feedback in here (rare for a sprite PR!) but can we work on presenting it in a way that's not cunty and insulting please

**Comment by axietheaxolotl** [comment]
fixed manifest issue. should be ready to merge now.

image

**Comment by Pumpkinoe** [comment]
is it maybe possible to make the manifest look a little bit like it's got writing on it? hard to do with limited pixels I'm sure, maybe just a little bit of noise of darker colour to imply so? right now it's kind of hard to tell that it's written on - or is paper in the first place, since it's not the same colour as paper in-game rn

**Comment by axietheaxolotl** [comment]
> Also what is this nazi attitude? Not only you appeal to my geolocation without knowing my nationality, but also you're saying that if tomorow someone comes in with sprites better than these, you will use your influence to block its merge just no ensure that your work is not wasted? Is that how this community works?

ok

**Comment by Imaginos16** [comment]
Sprite PRs. Not even once.

**Comment by Profakos** [comment]
How do these look like when carried by a mulebot?

**Comment by MTandi** [comment]
> How do these look like when carried by a mulebot?

image

**Comment by Profakos** [comment]
Well, that is not good. The old crates were perfectly sized to be aligned exactly on the mulebot. This poor creature is now smaller than the crates themself, as the crates have become much more wider and longer. You should update mulebots too, or tweak crate dimensions.

**Comment by TheVekter** [comment]
I think that there's a lot of good feedback in this thread, even if the people giving it are being idiots at the same time. It's concerning that the author's reaction to the criticism seems to just be to ignore most of it.

**Comment by Sealed101** [comment]
the spriter cabal house always wins :trollface:

**Comment by Thunder12345** [comment]
> I think that there's a lot of good feedback in this thread, even if the people giving it are being idiots at the same time. It's concerning that the author's reaction to the criticism seems to just be to ignore most of it.

It’s an ongoing vicious cycle that’s existed with significant sprite PRs for a long time. 

- Non-expert commenters can see things that look off but don’t know the technical way to phrase their feedback
- Spriters get annoyed at people for not giving feedback phrased the "proper" way
- Commenters see the response to their feedback and feel they’re being ignored for not being part of a "spriter clique" so they become more hostile as a result
- Spriters see comments that are both non-technical and hostile, and are disinterested in responding to them
- This further reinforces the view that outside feedback is being ignored
- Everyone continues to get more vitriolic until [spritetainers/oranges/discord jannies] step in to silence the most aggressive voices
- The cycle continues

**Comment by CMDR-Gungnir** [comment]
> > I think that there's a lot of good feedback in this thread, even if the people giving it are being idiots at the same time. It's concerning that the author's reaction to the criticism seems to just be to ignore most of it.
> 
> It’s an ongoing vicious cycle that’s existed with significant sprite PRs for a long time.

The problem is that it looks worse. You look at the "Spritetainer approval" screenshot. You see them both rocking matching names. You know that Imaginos and Viro are good friends. So even more than the usual case, it feels like "People are being mean to my friend, so fuck 'em."

This PR was very clearly not ready, and it got speedmerged by someone with a clear connection to the PR maker. It just looks really bad.

I like Imaginos! I consider them a good friend! But I'm starting to grow increasingly worried about their suitability as a Spritetainer the more this keeps happening.

**Comment by Error4656** [comment]
does no one remember that you need to ask the players what they think before pushing something big

**Comment by tuckerorchistra** [comment]
@Error4656 I feel you, most of the changes made in 2022-2023 have sucked and just drained the game of originality and fun. I've asked the coders why on discord and their responses are somewhere around "Since we don't get paid to code why code what the player base wants?", I'm assuming the same can be said for spriters or maybe they're just kissing ass but because of this dogshit crybaby self-centered mentality the games quality has dropped, and also all its humor. The worst part about all of this is that while the game gets progressively worse, so does the player base which is also what the coders want. They want new players who haven't seen or played older versions of the game, who haven't heard of words like "antag". Again on discord, I've heard the coders wanting to remove antag from the minds of players because it doesn't make any sense since, "Antagonists harm everyone and want to kill everything while people like traitors are only meant to harm two or three people.". The people meant to uphold our code and sprites are just fucking shit up so they can have their "perfect" game, they aren't even trying to make tgstation 2 because they want all the players from this game to play it. One of the only positions of power that has good honest people are admins and even then, there's shitheads who take the admining job and just fuck shit up more. But sadly, unless the host or head admins do something about this problem, it's just gonna get worse.

**Comment by Sealed101** [comment]
hello reddit

**Comment by ZealousZeke** [comment]
not a fan of how flat and wide these look when compared to the slim and three-dimensional sprites before them.

**Comment by tuckerorchistra** [comment]
thats really gay that someone deleted my comment i dont even know why

**Comment by CMOisLing** [comment]
wtf is wrong with you people?

**Pull request merged**
