### PR TITLE
Buffs the Nar-Sie rune

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: The Nar-Sie rune produces less unnecessary shields.
/:cl:

Before:
before

After:
after

### CODE REVIEW

**Comment by Cyberboss** [comment]
:-1: Purely because the lack of a complete square triggers me

**Comment by ma44** [comment]
Turn the image by 45 degrees and you have a complete square

**Comment by GunHog** [comment]
How is this a buff?

**Comment by PKPenguin321** [comment]
The corner shields didn't actually do anything but block teammates

**Comment by Robustin** [comment]
Or enemies if the corners are the only access point!

I don't like it because the shields currently form the same size of the rune and in a chaotic fight I might actually overlook the 2nd set of shields, especially if 2 are already down or something. The current one leaves no doubt who's doing the summoning.

**Comment by ChangelingRain** [comment]
If someone broke two of the shields, then they really should have been able to interrupt it by then, honestly.

**Comment by Robustin** [comment]
Gun/shotgun spam can have that effect, shields will be down on one side but the ritual continues because nobody moved in for the kill. If the bottom/right shields go down then you can't even tell if the scriber is the one down and right or up and left of the two remaining shields.

It's nitpicky, but so is removing the shields so cultists get a few more tiles to work with.

**Comment by Militaires** [comment]
yeah but people are dumb and hit the corners and that's part of the point

**Pull request closed without merging**
