### PR TITLE
Diseases will now cure if species is changed

### LINKED ISSUE #31487: Humans who turn into androids having been infected by viruses still get all the effects of the virus.
What it says on the tin. Androids can feel sandy, and as if their blood is boiling.

EDIT: Tested with a lethal virus, will need testing with other symptoms.

### PR DESCRIPTION
**Pull request by ghost**
No more dying from a virus if you become an android! beep boop!

:cl: More Robust Than You
fix: Diseases will now cure if species is changed
/:cl:

Fixes #31487

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
Only works for species that are disease immune, right?

**Comment by praisenarsie** [comment]
RIGHT!?

**Comment by XDTM** [comment]
IMO you should check this on species change, rather than checking this every tick

**Review by Cyberboss — CHANGES_REQUESTED** [review]
What XDTM said

**Comment by Ratvar** [comment]
"Oh I got gibbis time to become slimeman"

**Comment by Ratvar** [comment]
"Oh I got gibbis time to roll random races"

**Comment by XDTM** [comment]
i mean, it's not like 98% of people will have green slime juice lying around

**Comment by Incoming5643** [comment]
not sure if it's an issue but this might break black slime mutagen because it turns you into a slime person the step before turning you into a slime.

**Comment by XDTM** [comment]
good point, that'd cure it

Since slimepeople are pretty much organic, i'd say we can just remove the virusimmune tag from them and be fine

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
