### PR TITLE
Fixes how the poll icon looks in the title screen

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
So, you might not have noticed it, but the poll button in the menu, for some reason, was mis-copy-pasted accross the icons, meaning that one of them didn't have the right shading line at the top.

My OCD couldn't handle it.

If you want to know how it looks like versus how it used to look like, check with the icon diff bot, honestly this was the fastest fix ever so I don't feel like taking pictures.

## Why It's Good For The Game
I'm going to enjoy that menu, finally, instead of being annoyed ever since I saw that issue.

## Changelog
:cl: GoldenAlpharex
fix: The menu is now looking more consistent, at long last.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by tralezab** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title that explains the purpose of the PR.

Your current title does not meet requirements, so please update it.

**Comment by Krysonism** [comment]
Fix open already.

https://github.com/tgstation/tgstation/pull/61023

**Comment by GoldenAlpharex** [comment]
> Fix open already.
> 
> #61023

Oh whoops, never mind then!

**Pull request closed without merging**
