### PR TITLE
Makes notepad available for laptops and consoles

### PR DESCRIPTION
**Pull request by NeonNik2245**
## About The Pull Request
Makes it so that notepad can be used on consoles and laptops

## Why It's Good For The Game
Now everyone have more places to write important information. Also someone who doesn't have PDA (ghost-role for example) will be able to use laptop's notepad.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>

laptop-notepad

</details>

## Changelog

:cl:
qol: Make notepad available for everyone, who has only laptop or console.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
Would be a cool interaction if it could take a picture of a paper and copy the text from it. Kinda like OCR thing using built-in camera.

**Comment by DrDiasyl** [comment]
> How This Contributes To The Skyrat Roleplay Experience
SkyRat huh

**Comment by NeonNik2245** [comment]
I **accidentally** push another commit here, my bad. And I don't understand how I could cancel it.

**Comment by rageguy505** [comment]
> Would be a cool interaction if it could take a picture of a paper and copy the text from it. Kinda like OCR thing using built-in camera.

This used to be possible with old pda's or old paper. Can't remember

**Comment by san7890** [comment]
> I accidentally push another commit here, my bad. And I don't understand how I could cancel it.
Edit: help me please.

https://git-scm.com/docs/git-revert

so when you're on your branch, just type `git revert 8837e3bfc5831d34d6ad6a14486afc5eaacb390e` in your Command Line Interface (or hit the "Revert Commit" Button on the associated commit in the right-click menu if you're on github desktop or something)

**Pull request merged**
