### PR TITLE
Fixes the head description.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

See title.

## Why It's Good For The Game

tenor (6)

## Changelog
:cl:
fix: Fixed the head description.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
This isn't a fix

**Comment by Mothblocks** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it. 

Your changelog is also inaccurate, so please update it.

**Comment by cacogen** [comment]
quick rundown?

**Comment by Timberpoes** [comment]
Do what mothblocks asked, please

**Pull request closed without merging**
