### PR TITLE
Swarmers now think brass is delicious

### PR DESCRIPTION
**Pull request by ChangelingRain**
And it is! You should totally eat the brass, and not the gateway that's making so much delicious brass!

### CODE REVIEW

**Comment by vcordie** [comment]
FUCKING CALLED IT. CALLED IT

**Comment by anconfuzedrock** [comment]
wow joan this was my most recent clock cult rounds and I wouldn't be this fucking salty that swarmers cucked us I'd complain about swarmers not buff this

**Comment by calzilla1** [comment]
Br-ass

**Comment by anconfuzedrock** [comment]
where is my "swarmers now think runed metal is delicious" pr

**Comment by Grazyn** [comment]
Can't believe you actually did it. Yep, can't have anything get it the way of clockcult!

**Comment by AdamElTablawy** [comment]
To be fair, literally no other antagonist in the game's 'dominator' or anything similar-nar'sie rune, gang dom (before gang removal, rip), nukeop nuke, malfAI nuke, etc- can be deconstructed by swarmers.

This is literally only clockcult that has to deal with it.

That being said I feel like there's a more tasteful way to go about this. Maybe, logically, because it's a large object, it should take longer to deconstruct?

**Comment by coiax** [comment]
>To be fair, literally no other antagonist in the game's 'dominator' or anything similar-nar'sie rune, gang dom (before gang removal, rip), nukeop nuke, malfAI nuke, etc- can be deconstructed by swarmers.

**Comment by anconfuzedrock** [comment]
or you know just nerf swarmers aren't borgs nigh immune to swarmers aren't constructs literally immune to swarmers don't cock cultists specialize in both

**Comment by Supermichael777** [comment]
borgs are to slow for turboswarmers and constructs are shitty anyway(at least bloodcuks got good enough to realize sword cult is better)

**Comment by anconfuzedrock** [comment]
only takes an rcd to stop swarmers too, just put 4 airlocks surroundin the thing and give them an access requirement swarmers can't do shit

**Comment by Iatots** [comment]
I fondly remember a round on the 27th of january in which I was a swarmer. With the air still hot from a plasma fire I rushed towards the gateway in the final moments of the summoning process. I tried clicking on it but alas, from later log-digging it seems I just shot my disabler. The fire probably did it in. To realize it could've been done, and that you want to take it away, bring great pain to my heart.

**Comment by Kromgar** [comment]
👎 Swarmers were made by an ancient race to destroy ratvar and can not consume brass because their objective is to keep ratvar sealed away 

NEW DEEPEST LORE

**Comment by ChangelingRain** [comment]
How can it be an ancient race if ratvar was only created 2300 years ago, in a failed attempt by nar-sian cultists to gain absolute dominion over the physical plane?

**Comment by ChangelingRain** [comment]
Also just fyi this is not going to make swarmers less likely to fuck with clockcultists because hooooly shit, each sheet of brass is 5 resources. They're going to eat absolutely everything they can.

**Comment by Thunder12345** [comment]
Guys imma go check on the ca... What cache? WHAT WALLS? **_WHERES OUR BASE?_**

**Comment by Iatots** [comment]
You think just dangling a piece of meat in front of us will distract us? 

With this swarmers would be unable to stop a round-ending event. 

It doesn't matter if the gateway multiplies resources, the swarmers are not here to reproduce ad infinitum, they are here to make the location fit for colonization from an unknown species. Ratvar is not on the guest list.

**Comment by ShadowDeath6** [comment]
doesn't ratvar make swarmer die?

**Comment by ChangelingRain** [comment]
Swarmers that have gotten fucked by Ratvar's mighty power do not live long enough to send messages about it being actually bad.

**Comment by francinum** [comment]
>swarmers being unable to stop the round from ending
GOOD.

**Comment by Kromgar** [comment]
@francinum This doesn't stop swarmers from doing that at all. Swarmers can still eat up all the brass and teleport cucks all over the station

**Comment by ExcessiveUseOfCobblestone** [comment]
Do people even get a notification when swarmers appear? having someone silently camp places that spawn with actual stacks of metal/glass until wow there's like 10 swarmers is pretty lame, especially when they aren't even the driving force [well, SHOULDNT BE] of the round.

at least the other PC round-ender is balanced around the fact that it requires humans and/or areas that have humans in them to grow into a powerhouse.

**Comment by Grazyn** [comment]
There's a chance (25%) for a classified report to appear that tells you there's a swarmer in the gateway chamber.

**Comment by Iatots** [comment]
Usually by the time swarmers are able to take a foothold genetics already has tk xray hulks that can meme them from space, especially since ghost roles are a magnet for shitters.

**Comment by ExcessiveUseOfCobblestone** [comment]
> There's a chance (25%) for a classified report to appear that tells you there's a swarmer in the gateway chamber.

Yeah that should be much higher tbh

> Usually by the time swarmers are able to take a foothold genetics already has tk xray hulks that can meme them from space, especially since ghost roles are a magnet for shitters.

But giving out those powers is really bad and just creates greentide [bad] or validhunting [less bad but not good]. 2 people meant to stop an entirely random event seems a bit silly.

**Comment by Iatots** [comment]
> But giving out those powers is really bad and just creates greentide [bad] or validhunting [less bad but not good]. 2 people meant to stop an entirely random event seems a bit silly.

They can give powers to sec, especially during clockcult, metafriends, or even no one at all. I don't like naming names, but I've had a couple of rounds as swarmer where oldman basically wiped the hive himself.

You don't even need a lot of powers, x-ray is plenty with mesons because swarmers have normal vision so you can snipe them from the darkness they usually dwell in.

**Comment by optimumtact** [comment]
This brings it in line with the other roundtype metaitems, which swarmers are not supposed to disrupt

**Pull request merged**
