### PR TITLE
Adds Prolonging Prism as an application scripture

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Added Prolonging Prism as an application scripture.
balance: Prolonging Prism will delay the arrival of an emergency shuttle by 2 minutes at the cost of 2500W of power plus 75W for every 10 CV and 750W for every previous activation. In addition to the high cost, it very obviously affects the shuttle dock and leaves an obvious trail to the prism.
/:cl:

Enjoy a horrible quality video of the effect!
https://www.dropbox.com/s/gdbg6q5ykuau6ct/2017-06-06_19-43-19.mp4?dl=0

You can't make or activate these offstation, and breaking them while they're visibly affecting the shuttle dock will prevent them from delaying the shuttle any further.
The activation cost increase is shared between all prisms, so making a new one won't get you a lower cost.

### CODE REVIEW

**Comment by juanototo2** [comment]
**>still attempting to turn post-stable scripts cuckwork into a curbstomp**

**Comment by Robustin** [comment]
You should just cap the number of times it can be used. I can already taste the salt from a round with a great engine setup and the CC locking down the SMES area and indefinitely delaying the shuttle.

**Comment by DoctoreMad** [comment]
Rat-Var's portal already stops shuttle calls. Remove that if you want to add this.

**Comment by Kraseo** [comment]
lol it's just a shittier shuttle curse but in clock form!

**Comment by DoctoreMad** [comment]
No

**Comment by ChangelingRain** [comment]
It's basically just a way shittier shuttle curse since it's not free and costs unreasonable amounts of power.

**Comment by KorPhaeron** [comment]
Should just let xhuis do his thing

**Comment by ChangelingRain** [comment]
I am, once he finishes he'll be totally replacing this version of clockcult.

**Comment by KorPhaeron** [comment]
Isn't this just going to make conflicts for him then? Why change something that is on its way out?

**Comment by ChangelingRain** [comment]
He'll be totally replacing it, you can't conflict if none of your changes will remain.
Because I like doing it, mostly. Also because if I do enough careful changes it might end up good.

**Comment by Kromgar** [comment]
Joan needs to get in a last few orgasms from seeing clock cult win

**Comment by Armhulen** [comment]
"WE'RE GONNA TRY AND MAKE CLOCKCULT SIMPLER FOR THE NEW PLAYERS"

at the cost of 3000W of power plus 100W for every 10 CV and 1000W for every previous activation.

**Comment by juanototo2** [comment]
@Kromgar guess that's why she wanted to make ratvar male, eh?

**Pull request merged**
