### PR TITLE
Delete bike meme music

### PR DESCRIPTION
**Pull request by Cyberboss**
```
[17:53:40] <Naksu> the easter egg bike music files are fan midi transcriptions of GBA pokemon bike music
[17:53:52] <Naksu> no license is granted by the person who made them
[17:54:12] <Naksu> not that he'd be in a position to do so for the full work anyways
```

### CODE REVIEW

**Review by ShizCalev — APPROVED** [review]

**Comment by Iamgoofball** [comment]
God damn it

**Comment by Iamgoofball** [comment]
Bicycles are ruined now

**Comment by 81Denton** [comment]
RIP

**Comment by optimumtact** [comment]
@Cyberboss @ShizCalev I don't agree that this was necessary

**Pull request merged**
