### PR TITLE
Porting and adapting food sprites from other repos (plus a couple original resprites)

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
I went out searching for better sprites from other repos for a few food items that we have. I found a handful from Aurora, another one or two from Bay, and the pineapple slice from Paradise. I've also adapted a few of these sprites for some food items, like a lot of vending machine snacks, meat slabs, cutlets and sauces. As for original sprites, I resprited the cooked crab meat (yeah, it kinda looks like dumplings, still several times better than that burned mess of an old sprite) and the cheese curd bowl.

Old
immagine

New
immagine

## Why It's Good For The Game
More appetitizing sprites, because people won't just stop adding more codersprited junk tbh.

## Changelog

:cl:
image: Ported and adapted several food sprites from Aurora, Bay and one instance from Paradise -- Bacon, plant meat, slime meat, cutlets, crab meat, crab rangoon, bechamel sauce, cheese curd, waffles, chips, shrimp chips, cheesie honkers, space twinkie, jerky, peanuts bags, chocolate, boritos, syndicake, popcorn, pesto, tomato sauce, pineapple slice, pineapple salsa, bran request cereals and bronx bar have been resprited.
del: Waffles no longer magically conjure a "waffle tray" trash item when eaten.
/:cl:

### CODE REVIEW

**Comment by honkpocket** [comment]
I don't think the boritos gain any improvement from this. Also the removal of '13' from the popcorn is a little meh, IMO.

**Comment by SmArtKar** [comment]
Pics? And honestly I feel like a lot of candy sprites are a downgrade from what we have right now, most of them are sideways which will make them look super weird

**Comment by Ghommie** [comment]
> I don't think the boritos gain any improvement from this. Also the removal of '13' from the popcorn is a little meh, IMO.

Old boritos look quite flat tbf. I'll reitroduce the '13' on the popcorn.

**Comment by zoomachina** [comment]
Most of the new candy snacks look mega flat, popcorn sprite is a big downgrade, especially the crumbled sprite

**Comment by Ghommie** [comment]
> Most of the new candy snacks look mega flat, popcorn sprite is a big downgrade, especially the crumbled sprite

I'm confronting the screenshots now. I'll perhaps revert the boritos, since the original is actually spot-on on how the bag would look like. The rest doesn't exactly look like a downgrade to me. Some aren't exactly an upgrade either, but at least we're getting rid of the old awful oblique projection from, idk, openss13 era.

**Comment by ophaq** [comment]
All these sprites look so much better but I say keep the old popcorn and chip sprites.

**Comment by Loafin34** [comment]
not the waffles... waffles should keep the tray and also resprite all the waffle reskins (soylent green, soylent viridian, roffle waffle)

**Comment by Loafin34** [comment]
crab meat doesn't make sense. why's the cooked one shrimp tails and the uncooked one yellow lumps?

**Review by Wallemations — CHANGES_REQUESTED** [review]
Old chip/popcorn bags looked better, new ones have a weird perspective. Please keep the old ones.

Also, why doesn't the bacon have any fat visible on it anymore? It just looks like a sliced cutlet

**Comment by Ghommie** [comment]
> crab meat doesn't make sense. why's the cooked one shrimp tails and the uncooked one yellow lumps?

It's the other way around.

**Comment by Ghommie** [comment]
> not the waffles... waffles should keep the tray and also resprite all the waffle reskins (soylent green, soylent viridian, roffle waffle)

they've already been resprited too, duh.

**Comment by Ghommie** [comment]
Reverted the boritos and popcorn sprites. Re-resprited other snacks. changed bacon sprite and color scheme a little. Hopefully it looks less burned off and has more noticeable highlights on the fat stripes.
immagine

**Review by Wallemations — APPROVED** [review]

**Comment by CCC23** [comment]
tgstation has fallen soul is dead its yo ho hover

**Comment by Dorsisdwarf** [comment]
the top and middle row are fantastic

**Comment by Wallemations** [comment]
Failed check

**Comment by Ghommie** [comment]
That's the alternate test, and it's failing for totally spurious and unrelated stuff.

**Pull request merged**
