### PR TITLE
Redesigns the Armory, adds an auxiliary storage to security

### PR DESCRIPTION
**Pull request by pudl**
The armory has been reduced to its old size. It still retains all Tec equipment. Additionally, there is a new storage room in security for misc. equipment.
- All guns are moved to two lockers. 1 extra shotgun has been added, bringing the total up to 3.
- All armor is moved to a locker
- Tec equipment is now in lockers
- An IV drip and blood bag are now in the execution room for lethal injections
- Atropine medipens have been added to code and put into the armory. Sprite by myself
- As an added touch to medipens, I also gave morphine pens a unique sprite
- Security lockers now contain security gas masks
- The warden's table with like 8 gas masks is now a rack of 2 hybrid tasers.
- A locked contraband closet has been added to the security office.
- Auxiliary storage has replaced evidence storage, with the detective's evidence closet being a single locker more than capable of taking its place
- Auxiliary storage contains two secways w/ keys, yellow gloves, a toolbox, a multitool, and 3 portable flashers. All these tools are to allow one security officer at the least the equipment to hack doors and access areas she/he may need inside of
- Detective now has a single evidence closet with an evidence bag in it.
- Ammo box for beanbags added and in the armory. Since the riot shotgun has an internal magazine, it's a cardboard box. Sprite by WJohnston.

Left is atropine, right is morphine.

Changelog coming soon.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
pics

**Comment by SconesC** [comment]
Moving away from the extremely restrictive rack-pocalypse of our current map's armory designs is pretty good. What we already have is not interesting, it's  inconvenient. Looks like no equipment was lost, and all in all the new layout just looks not only nicer but seems to play quite a deal better when you are not navigating a figure-eight of racks.

Evidence was pointless considering if something had been confiscated with almost zero exception, it belonged in the Security contraband locker. Also, the barriers and flashers and secways are officer-accessible, which is a nice touch.

Good reorganization of everything :+1:

**Comment by GunHog** [comment]
Please show us how a typical Syndicate bomb affects this new layout.

**Comment by Lumipharon** [comment]
why did all the normal guns get crammed in a locker while the steelrifles keep their own special racks, behind what is (currently) a no access requirment shutter?

Also weren't secmasks removed from seclockers to try avoid the whole faceless goon thing certain people like? (somewhat redundant since they somehow got slipped in as default box equipment but eh).

**Comment by Steelpoint** [comment]
Good change overall, few criticisms.

* Removal of the windoors for doors is a negative change, due to how I like to prop open the windoors for officers/people to let into the armoury. A button to lock/unlock the doors might work however.

* Stuffing all the guns and armour into two lockers is a bit iffy for me. But seems like a acceptable sacrifice (that was the main constraining factor in my original armoury design).

This change does, however, buff the presence of tasers on the map from three in the armoury to about five extra, a surplus of two extra tasers. Just a minor point.

Nevertheless, positive change :+1:

**Comment by Lumipharon** [comment]
That's actually a very good point. With the loss of the sec room window, and the replacement of the windoors with airlocks, the armoury is far more secure.

**Comment by WJohn** [comment]
I personally much prefer the feel that multiple guns on racks gives off. It makes the armory feel well stocked and in ship-shape, which is a nice contrast for when it's empty and littered with empty bullet casings and shotgun shells.

**Comment by Steelpoint** [comment]
That's kinda why I went with my design.

I'm simply thumbing this up due to it being a nice design, even if I prefer my own.

**Comment by Fox-McCloud** [comment]
:-1:  x :100:  On putting tasers in security officer's lockers.

This is just going to encourage officers to carry multiple tasers and to hoard them--now each officer also has two tasers--major major power creep for officers. On top of that, officers can and WILL go around to all the lockers where there's a spare taser and take them--and if not an officer, then the HoS, or Warden.

It's  also going to increase the likelihood that the  detective ends up with a taser as well.

Other changes are interesting, but the taser change is major powercreep to security, more so than even @Steelpoint's various RPs.

**Comment by SconesC** [comment]
@Fox-McCloud Do you play on TG? Officers don't hoard tasers, it simply does not happen, and if it ever does, it is rare.

It's convenience.

**Comment by Dorsisdwarf** [comment]
I don't like how all 13 guns in the armory have been squeezed into two lockers. That's just messy.

Why do security need a second set of tasers in their locker? They already spawn with one, and this is increasing the number of tasers on-map by like 25% at a time when we're supposed to be phasing them out.

Why do sec need a secmask in every single (already crowded) locker, security spawn with them in their backpack already.

Why do sec have an empty bloodbag in the fucking armory. They already have a whole room of stuff for their fucking executions why would you have a bloodbag

Why do steelrifles get display racks but not all the other armory kit?

Did you really put the like 25 items of armor into one locker?

Why does the steelrifle section have a special snowflake rwall-grille-rwall buffer from space, but the station's /entire supply of non-bullet weapons/ is in a single locker where the warden can barely see it right next to a single rwall into space?

**Comment by Steelpoint** [comment]
I was meant to replace the upper and lower auto rifle wall with a normal wall.

Say what you will about my current armoury design but it does showcase everything in a nice pleasing way, it makes it feel like a crowded armoury and not a bare, at least until later.

**Comment by Jalleo** [comment]
Where is the evidence room now?

**Comment by Fox-McCloud** [comment]
@SconesC 

It's because they can't, at the moment. One spawns on the officer and three spawn in the armory. There's nothing to hoard or stock up on.

This has every officer with a taser on his person and in his own locker---I find it incredibly hard to believe officers wouldn't raid loose lockers for spare tasers if this was to go through.

**Comment by joonoro** [comment]
Where is the armory air-alarm?

and @Jalleo the new contraband locker is supposed to replace the entire evidence room by the sound of it

> Auxiliary storage has replaced evidence storage, with contraband locker being a single locker more than capable of taking its place

**Comment by Dorsisdwarf** [comment]
Why did this fail Travis?

@Steelpoint  your armory didn't feel crowded, the old armory felt crowded. Yours is like a sports stadium when nobody's there.

**Comment by Steelpoint** [comment]
Less so crowded and more like a proper armoury where all the equipment is properly stacked.

This armoury feels like someone just crammed everything into a few lockers with no real sense or organization or ease of use.

**Comment by GunHog** [comment]
I have given this design some thought. I am not a Security player, but I do not believe I would enjoy working with an armory like this.

All of the guns barring the rifles are in one locker, and armor in the other...I would find it most unpleasant to sift through those piles to find the item I want. 

I believe it better for the Security players to leave the equipment separated and categorized for fast and easy selection. While the items are now easier to steal or destroy with explosives, it is not a favorable design for the players that actually need to use it, or fast moving antagonists looking for a specific item.

Perhaps the shutter room could be put to better use by placing the equipment groups there.

**Comment by Steelpoint** [comment]
Or you can try and work on my armoury design.



Is it the best? Well no considering this PR exists. 

But my armoury design actually keeps all items seperated, it even splits up the Riot Suits individually instead of clumping them togther.

If you move the Secway, flashers and the barricades out of my armoury and into the evidence room, you have the ability to better compress the armoury design and make it work, instead of putting it all in a few lockers.

**Comment by Steelpoint** [comment]
Hell, here's a quick mock up I did of a alt armoury design that I think is better.

screenshot 2015-09-24 21 06 47

**Comment by Nanotransistor** [comment]
Might want to remove the tasers from the lockers. I can see Mekhi looting each one of them at round start.

**Comment by Anonus** [comment]
Yes, but why do we only have two flashers now, and not three?

**Comment by Shadowlight213** [comment]
:-1: to putting all the guns in a secure locker. For one, it's extremely messy. Also, it means that antags need to have something to open the lockers in order to raid the armory. I'm pretty sure we agreed that a warden putting the entire armory in a locker was shit a long time ago.

**Comment by pudl** [comment]
I've seen the response, and I will be changing a lot of this PR. However, guns will still remain in lockers, being separated into two. I will, additionally, move the laserproof vest.

The TEC equipment was untouched for a good reason. First, I don't know if it will stay, so not messing with it would avoid a conflict with a removal PR.

A chair is in front of the shutter because a desk is behind it. The shutter entrance was unused and not needed.

I will replace the doors with windoors, in order to make it more open to people needing inside (propping open doors as Steelpoint said.)

Thanks for the reponses.

**Comment by pudl** [comment]
Responses fuck

**Comment by Lumipharon** [comment]
Requiring any armoury thieves to have a gun (or emag) to crack open the gun lockers, to get guns, is pretty shit.

Also it's way easier to just steal the entire armoury if it's all in a locker - thermite wall, space space, all guns gone. Honk.

**Comment by pudl** [comment]
If someone wants to steal the armory, they're an antagonist. An antagonist who wants to steal the armory can buy an emag.

It's been upped to three lockers now, and the lockers are now directly next to the warden, no longer against the wall. So the thief would have to walk into the armory, set off the motion sensitive camera, and drag out all three lockers all while the warden is watching.

**Comment by Jalleo** [comment]
Remove the ID locks its stupid.

**Comment by GunHog** [comment]
> If someone wants to steal the armory, they're an antagonist. An antagonist who wants to steal the armory can buy an emag.

Only *Traitors, Double Agents, and Nuke Ops* have access to emags. You failed to account for the other humanoid antagonists.

**Comment by pudl** [comment]
Updated the OP.

**Comment by SconesC** [comment]
You can EMP lockers. Is this really hidden knowledge?

**Comment by pudl** [comment]
Updated the OP again, just small errors I fixed and tasers on a rack, plus the additional portable flasher that was requested.

**Comment by Steelpoint** [comment]
Do the lockers have access requirements or do you just open them?

**Comment by pudl** [comment]
Gave unique sprites to morphine and atropine medipens, check the OP.
@Steelpoint All lockers in the armory require armory access. If you want, I'll make the TEC ones standard security access for easier use, I just figured a traitor who steals one would have an easier time killing a sec officer for his ID than a warden or HoS.

**Comment by Lumipharon** [comment]
Pretty sure emps only work on crates, not lockers. Could be wrong, but either way it's another level of security and gear/ability check for raiding the armoury - and with the window to the sec gear room gone you know HAVE to go through the warden's office to get there, unless you have shit to break r-walls.

**Comment by pudl** [comment]
I will put another window in the security equipment room. EMPs work on lockers.

**Comment by pudl** [comment]
This question is directed at the three biggest sec players on this PR, @Steelpoint @SconesC and @Lumipharon but anyone else can answer. What do you think would be the feedback if I added 2 more riot shotguns to the ballistics locker, in order to bring it up to 4, similarly to the other kinds of guns? Alternatively, what if I made it 3 to match the amount of riot suits? Or even add one more riot suit to match a buffed amount of shotguns?

**Comment by pudl** [comment]
And, as a final proposal to everyone, what would you all think of a stripped back armory?

2 eguns, 4 lasers, 4 riot shotguns, 4 ammo boxes for the riot shotguns, 2 riot suits, and 2 space suits? The other misc items would remain, such as barriers, but that would be the main weaponry, alongside the stuff Steelpoint added.
I think items like ablatives and the ion gun aren't entirely fit for sec to have by default, instead something from RnD. Why would NT supply weaponry to battle lasers when the syndicate uses ballistics? And why the ion gun, if they knew that robots would become killers why not fix them? Please don't respond "Nanotrasen is cheap."

**Comment by Steelpoint** [comment]
Riot Shotguns are a really poor weapon unless you get buckshot from Cargo, beanbag rounds simply don't do much, however this is more a bug with stamina damage on ballistic weapons. A buff to them would not be bad such as adding a additional riot shotgun to bring it in line with the three riot suits in the armoury in my opinion.

(If you want to buff Riot Shotguns you would have to add a optional box of lethal buckshot ammo)

Also I'm a fan of the Ion Gun, its rare to use but when it is used it is invaluable, since its one of the strongest hard counters to Cyborgs and is really the only counter to syndicate mechs aside from sustained firepower, which is hard to do.

**Comment by pudl** [comment]
The armory now has 3 shotguns.

**Comment by Lumipharon** [comment]
Riot shotguns are neat as fuck.
No one would complain about a 3rd one I think, which is consistant with the lasers and eguns.

That said, riot shotguns were far, far better back before beanbags got nerfed to shit.
If the armoury had a couple of boxes of one of the lethal ammo types, it would be pretty good - having to manually load shells + pumping stops them from being turbo murder weapons, while still being strong enough to take down buff motherfuckers in a pinch.

I wouldn't downscale the amount of shit in the armoury because frankly, when you have 50 pop games, 6 lethal weapons (shotguns don't have lethal rounds by default, and ignoring steelrifles) and 3 sets of a relevent armour isn't that much to start with.

The whole armoury is literally "emergency use" shit, so it seems prefectly reasonable to have anti energy and anti mechanical equipment on a station full of energy weapons and mechanical stuff.

**Comment by Dorsisdwarf** [comment]
If you try to remove Ion rifles from the armory because "waaah my immulsions" I WILL find you and slap you.

**Comment by Aranclanos** [comment]
looks pretty ugly, are the OP images updated?

**Comment by CPTANT** [comment]
Can't say I like the changes.

**Comment by Nanotransistor** [comment]
I have considered a few things regarding locked lockers here. 

First, if they are locked it will take about 5 clicks to successfully steal one gun. One click to equip the emag, another one to unlock the locker, another one to put the emag away or swap hands, another one to open the locker and one last click to pick the gun. When you can just spend one click to pick a gun right now. And of course, not every antagonist has access to an emag.

Still, i like the idea of putting them in lockers. I can see a traitor dragging a locker full of guns instead of having to pick them one by one. Or using a locker as a shield to block all the shots from the warden as the traitor takes the locker to space. Possibly more scenarios. 

Also, lowering the amount riot gear doesn't seem to bad. It currently is kind of strong since riot armor doesnt slow down anymore, and of course the shields are way too good for being a free item.

2 eguns and 4 lasers seems cool too. Right now eguns are the first choice over the lasers since they are just better. If these two weapons get modified later this could change (energy mags for the laser guns maybe?).

**Comment by Steelpoint** [comment]
Eguns are only taken due to the fact they are 100% better than Lasers, I think Lasers should get a buff but I digress.

Prehaps make the lockers have no access restriction, best of both worlds in that it only requires you to just open the locker but it also provides protection (shielding) and that its easier to drag all the guns out of the armoury, for good or bad intentions.

**Comment by pudl** [comment]
How about we meet in the middle, and they're normal sec access?

**Comment by Jalleo** [comment]
No sec access on the lockers its stupidly OP in delaying the theft of guns. That sounds good but harms antagonist activity too much. Like people have said we need a scaled armory for pop size.

**Comment by pudl** [comment]
Why do you have the mindset that antagonists must be absolutely given the armory if they want it? Should security have zero time at all to stop thieves? Robbing the armory is never, ever a required thing, since antags have an incredible arsenal of weaponry, some of which exceeds the effectiveness of eguns. If they decide to completely ignore all of that and go loud, C4ing into the armory for guns, why should their success be guaranteed, or at least in their favor as opposed to Security's?

**Comment by SconesC** [comment]
Saying that it "harms antagonist activity" is not only ridiculous in that it implies antagonists require Armory heists (from space) to succeed but also that they are deserving of being able to do it with a 100% ease-of-access success rate with no favor towards the people who are on the most intentionally well-defended part of their home turf. 

This does not make Armory break-ins impossible. This makes them slightly harder - But conversely, the steelpoint rifles are up against space now... So can you really complain it's going to be too hard to get at the "good stuff"? The design overall makes it more maneuverable, more aesthetically pleasing, and less of a confined poorly-structured mess of racks like it currently is.

**Comment by Shadowlight213** [comment]
Just make the lockers have no lock.

**Comment by pudl** [comment]
As an extension of the point to what Scones said, yes, you can literally just break open the place to the best stuff and now you have a locker with standard armory access, and you don't set off the camera. Literally, you will not be seen.

The point of this PR wasn't to compress the armory, it was to make the armory more secure with lockers. Making them have no lock completely invalidates what I am trying to do. The lowest access I'm willing to go is a normal sec officer.

**Comment by Shadowlight213** [comment]
Ah. I assumed it was just a redesign to make it easier to navigate.
Also, why does the sec equipment room armory desk need a shutter?

**Comment by pudl** [comment]
So that sec officers and/or other intruders can't just break down a window and enter easily. They need to bring at least thermite or a toolbox, some actual preparation for such a big heist should be required.

**Comment by Shadowlight213** [comment]
Alright then. Also for the lockers, leave then on armory access if you are going to keep them being locked. (You sure you're not willing to lower them to maint access?)

**Comment by pudl** [comment]
Assistants have maintenance access. I am absolutely not going to permit security-restricted weaponry being opened by non-security personnel. As of right now, the armory being hilariously weak is unbalanced, not me trying to make the lockers restricted to security.

For example: Why should anything in security be locked then? If someone breaks into security to steal a taser, why should they be restricted by a wall? Why do you have to open a security officer locker for a security vest, why can't it be maintenance access? I mean, breaking into security is SO hard, right?

That's how people sound.

**Comment by Shadowlight213** [comment]
The maint access thing was a joke....

**Comment by pudl** [comment]
I wasn't exploding at you, I was just exploding at previous posts that I strongly disagree with.

**Comment by Nanotransistor** [comment]
@SconesC Well, there are still several locked doors in-between, plus some reinforced walls, and of course the warden and every other person walking around security. Cameras too. Breaking into the armory is not exactly a walk in the park (and it shouldn't be), and i don't see why it should be made more difficult.

@pudl Only traitors and nuke ops have emags. Add to those, gangsters for C4. Don't think most antags have an easy way to open these lockers without having to kill the warden or HoS first.

**Comment by pudl** [comment]
Traitors and nuke ops have emags, changelings have emp screams. Cultists, gangs, abductors can convert security. Revolution has brute force of a lot of people to bust into security as an all-out raid. Wizards can open all doors.

**Comment by SconesC** [comment]
Cultists can produce EMPs as well, just to add to the list.

Revolutionaries and Gangsters are also conversion antagonists and depend on converted persons getting them in.

**Comment by bgobandit** [comment]
Technically anyone can get an EMP if they know the right science. Honk.

**Comment by GunHog** [comment]
Ground uranium and iron. Bug mining for uranium, grind it up, break into chemistry, get some iron from there, mix it in a grenade or beakers.

**Comment by pudl** [comment]
THANKS REMIE FOR TELLING ME THAT THAT WOULD WORK

**Comment by RemieRichards** [comment]
not my fault you suck at maps.

**Comment by pudl** [comment]
Alright almost done

**Comment by pudl** [comment]
Oh my fucking god this is why I close my PRs with every merge conflict

**Pull request closed without merging**
