### PR TITLE
Update minor BYOND version to 1542

### PR DESCRIPTION
**Pull request by ZeWaka**
## About The Pull Request

re: https://github.com/tgstation/tgstation/commits/master/.github/CONTRIBUTING.md, your codebase is supposed to support minimum 513.1540, since the `as anything` syntax breaks for special lists - and 1542 just fixes some regressions

* to finish this, we'll need to migrate away from extools, as it is no longer maintained
*  * this would need to be done to either auxtools maptick or 514

## Why It's Good For The Game

this has nothing to do with the game unless you count the various minor bugs fixed since 1536

### CODE REVIEW

**Comment by Mothblocks** [comment]
Extools doesn't work on 1542, I'm pretty sure--it'll spit out errors.

I think we should just upgrade to 514 and see what breaks, apparently Manuel is on it now.

**Comment by Mothblocks** [comment]
firefox_2021-02-19T00-16-09

**Comment by Cyberboss** [comment]
@ZeWaka Extools doesn't work on 1542

**Comment by ZeWaka** [comment]
bruh I was going to either port auxtools to tg or make it 514 compliant but ok

**Comment by Mothblocks** [comment]
Like I said, I don't know much about the state of it, but I'd like to just see us go to 514 and see what breaks.

**Pull request closed without merging**
