### PR TITLE
Gives miners their overalls back

### PR DESCRIPTION
**Pull request by ChangelingRain**
suit
nosuit

Makes miners in general less security-looking.

### CODE REVIEW

**Comment by GunHog** [comment]
I agree with this. Miners looked too black and evil looking. They looked much nicer before.

**Comment by nullbear** [comment]
getting tasered by sec for having a security backpack as miner is annoying.

**Comment by Shadowlight213** [comment]
I had someone once think miners were ops wearing tactical turtlenecks

**Comment by RemieRichards** [comment]
workboots+explorer suit just do NOT go.

**Comment by nullbear** [comment]
yeah, expand the explorer suit to cover the feet, looking like it did with jackboots. Or give jackboots to miners still.

**Comment by lzimann** [comment]
OR you can make sec red again so they don't look all the same :^)

**Comment by Bawhoppen** [comment]
give jackboots to miners again it was not unreasonable

**Comment by KorPhaeron** [comment]
Yellow shoes look disgusting

**Comment by KorPhaeron** [comment]
The separation between lavaland and any sort of objective and fair merge process is ABSOLUTE

**Comment by Zilenan91** [comment]
The overalls are still in the Miner clothing locker, so they need to be replaced with the turtlenecks

**Comment by duncathan** [comment]
kor cmon

**Comment by KorPhaeron** [comment]
Do you really think yellow boots look good with that suit @duncathan

**Comment by GunHog** [comment]
Fashion police!

**Comment by KorPhaeron** [comment]
I'm honestly confused why this PR was reopened

**Comment by optimumtact** [comment]
@duncathan you're not the design lead

**Comment by KorPhaeron** [comment]
Okay here is my serious reasoning

I have worked for a long time on lavaland and the spriters who have helped me with lavaland have all been working towards a consistent art direction (grim dark). I don't think it's actually unreasonable for me to say the thing that I and these people have been coordinating on keep that same art style. The boots look horribly out of place.

**Comment by duncathan** [comment]
fwiw I do like the yellow boots

**Comment by Zilenan91** [comment]
Yeah big no :-1: 

The overalls look really really bad with the explorer suit. This does not mean we should resprite the explorer suit because superior design > nostalgia which is literally what this pr is

**Comment by PKPenguin321** [comment]
:-1:

**Comment by Dorsisdwarf** [comment]
Explorer suit is  garbo made for "Le edgy darksteroid" though

**Comment by KorPhaeron** [comment]
My garbage asteroid is the most popular job in the game so I am gonna stay the course. And only 2% of the playerbase said the theme bothered them in the poll.

Also their old outfit was basically power armour from a game about killing zombies, not like they had something cuddly and civillian and original.

Anyway I have posted my serious reasonings now so I am gonna go ahead and try closing this again.

**Comment by Dorsisdwarf** [comment]
"This sprite is bad"

"Well the job is popular and they like everything else QED"

**Comment by KorPhaeron** [comment]
Makes more sense to cater to the people who like lavaland than to someone who says they hate the whole thing, doesnt it?

**Comment by Dorsisdwarf** [comment]
I do like lavaland, just not the "Miners are now grimdark" aesthetics

**Comment by KorPhaeron** [comment]
Also I am talking to a couple people about replacements for the syndie/security sprites

**Comment by Dorsisdwarf** [comment]
On the bright side, at least you're in charge so SEC SPRITES wont devolve into grudgecode wars like last time.

**Comment by ChangelingRain** [comment]
>The overalls look bad with the suit

You can't even see them with the suit up.
Boots, yeah, I can understand, but overalls can't even be seen with the suit on.

**Comment by ChangelingRain** [comment]
Let's try this again, but this time with the suit having ~boots~
suit nosuit

**Comment by KorPhaeron** [comment]
I just said 2 posts up that I was getting new jumpsuit icons

**Comment by ChangelingRain** [comment]
kor i will fight you for the right of miners to have overalls

**Comment by KorPhaeron** [comment]
Please do not start a stupid maintainer war over this

**Comment by coiax** [comment]
FIGHT FIGHT FIGHT FIGHT FIGHT

**Comment by KorPhaeron** [comment]
1. I am getting new icons. I understand syndie shirts are dumb but I do not like the wario clothes

2. Reopening your own PRs is bad. This is the most important one.

3. Miners already have a locker of overalls that they never put on

But it sounds like we are actually gonna have to involve the head coder over this nonsense

**Comment by Ausops** [comment]
i'll make some sort of appropriate undershirt for miners

until then please do not be cheeki breekis

**Comment by ChangelingRain** [comment]
Ausops it'd better include overalls

**Comment by KorPhaeron** [comment]
Lets put our bikeshed adventures on hold until we see what ausops makes then

**Comment by coiax** [comment]
FIGHT FIGHT FIGHT FIGHT

**Comment by GunHog** [comment]
Perhaps you should leave it up to the art director? Kor has too much of a personal bias to remain objective in this case.

**Comment by coiax** [comment]
And as the newly proclaimed ART DIRECTOR in @WJohn's absence, I feel there are not enough quality memes

**Comment by ChangelingRain** [comment]
stop closing my pr reeeeeeee
@WJohn help me take back the overalls

**Comment by KorPhaeron** [comment]
It's not my job to be objective though.

Also WJ was the one who set the mood of lavaland as a grimdark shithole covered in magic and skulls in the first place.

**Comment by KorPhaeron** [comment]
The RIGs he made for it were black as well, by the way

**Comment by LatD** [comment]
The dark suit fits the dark lavaland theme with ash storms and such but they do look way too much like security. Most people have got used to miners wearing their usual overalls which were really easy to separate from all other jobs. Whatever the final suit will be for them I hope it doesn't look as security as the current suit.

**Comment by optimumtact** [comment]
So what you're saying is we need to recolour security to blue?

**Comment by coiax** [comment]
> Or the police shut us down, down. Police shut us down, down. Po-po shut us

**Comment by Zilenan91** [comment]
I like the turtlenecks as they are currently tbh, I don't know how you'd change them to be more suitable to lavaland than they already are.

**Pull request closed without merging**
