### PR TITLE
makes pointing better.

### PR DESCRIPTION
**Pull request by nullbear**
pointing is better

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
This might fix that old higgs buggson about point not pointing at the right object.

**Comment by WJohn** [comment]
Cool 👍

**Comment by PKPenguin321** [comment]
Bad changelog
Otherwise good PR

**Comment by Niknakflak** [comment]
Point hotkey when

**Comment by nullbear** [comment]
some servers use middle-click for point.

**Comment by PKPenguin321** [comment]
That's awful since middleclick is and always should be swap hands

**Comment by nullbear** [comment]
so make it shift+middle-click

**Comment by PKPenguin321** [comment]
That works

**Comment by Zilenan91** [comment]
What about shift + right click, middle click is really awkward

**Comment by nullbear** [comment]
works too.

**Comment by nullbear** [comment]
oh.
uh. 

I just added a hotkey for it but okay

**Comment by nullbear** [comment]
right click = menu.

shift+middle click isnt that bad. You don't really point that often anyway.s

**Pull request merged**
