### PR TITLE
Removes False Alarm from possible events

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It's broken and chooses events without an announcement half the time. Also waste of an event slot.

Keeps the event in existence in case admins want to use it.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
# fix dont remove

**Comment by Anonus** [comment]
To fix it we need to rework how events in general work so good luck with that

**Comment by KorPhaeron** [comment]
Having nothing happen isn't fun even if its fixed

**Comment by Bluespace** [comment]
:thumbsup:

**Comment by Niknakflak** [comment]
:-1: :-1: :-1: Fix, Don't remove.

**Comment by KorPhaeron** [comment]
@Niknakflak 

I'm not rewriting the event system to fix one event that is basically "haha no event happened" anyway

**Comment by duncathan** [comment]
Improve don't remove is a dumb meme

IMO the concept of a false alarm event is itself flawed, so :+1:

**Comment by MrStonedOne** [comment]
actually, it would be easy to make it only select events that have an actual announcement.

admin tools use this to decide if they should bring up that "announce to the crew" pop up

**Comment by Niknakflak** [comment]
@duncathan If that is true here, then removing the actual event in the code would be a better option than just setting the weight to 0.  Also doing what Mrstonedone said.

**Comment by phil235** [comment]
:-1: mso has opened a fix pr.

**Pull request closed without merging**
