### PR TITLE
Removes enriched uranium

### PR DESCRIPTION
**Pull request by ohnopigeons**
[It's a WIP from 7+ years ago.](https://github.com/tgstation/tgstation/commit/a7171da6d0e1ec2e03bb36c831e5ff72669a1c3d)

### CODE REVIEW

**Comment by Bluespace** [comment]
smh another un-needed nerf to science.

**Comment by Bombpants** [comment]
Improve not remove

**Comment by arsserpentarium** [comment]
There aren't even sprites, IIRC.

**Comment by Shadowflame909** [comment]
I have no Idea what this does but REEE. Alright now continue.

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by nicbn** [comment]
The whole game is a WIP from several years ago, remove it entirely for sake of consistency.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
