### PR TITLE
Allows R&D to build the old protolathe given enough time.

### PR DESCRIPTION
**Pull request by F-OS**
:cl:
add: Allows R&D to build the old protolathe given enough time.
/:cl:

[why]: #

Science can already build an old circuit imprinter without the departmental locks, and having the ability to build a old protolathe could help if a bombing happens/boards are lost.

### CODE REVIEW

**Comment by F-OS** [comment]
AAAAA FUCKING

**Comment by praisenarsie** [comment]
lol

**Review by Cyberboss — APPROVED** [review]

**Comment by FantasticFwoosh** [comment]
Isn't this conceptually going to be rushed towards though just to go back to the same system prior?

**Comment by F-OS** [comment]
Yes, however, the old system was better for both RP and interdepartmental cooperation, and having people be required to go to R&D and ask for stuff actually helped break up the whole "every department a little world" mentality.

**Comment by FantasticFwoosh** [comment]
> the old system was better for both RP and interdepartmental cooperation

**Debatable**, the reason the dept lathes were added (so im told) was to eliminate the interaction over the RnD desk and the interaction required with the RnD computer, especially since it was locked in the lab and releasing it to the public would mean they could print off virtually anything they want in the research network as soon as it was researched often squandering the precious materials.

It put unnessecary leverage in the hands of miners & RD's to use the upgrades and technology mainly for themselves, and miners disrespected boundaries anyway often breaking in to just use the console via a breakdown a communication and respect.

- Im uh, something of a _expert_ on poor interdepartment relations as a field of speciality.

**Comment by Spaceinaba** [comment]
nobody but science even uses their lathes so people are actually getting less stuff than they were previously

**Comment by F-OS** [comment]
Remember, this does not remove the departmental lathes, simply adds the ability to build the old ones given enough time. So you can still stay in your little autism fort and use your lathe, also what Inaba said.

**Comment by FantasticFwoosh** [comment]
I've just looked at the department lathes design lists, i can't say im suprised but im not really impressed as it ports over all the protolathe designs. Which may explain the problem why people aren't using the design lathes at all, because they actually didn't interact with the items a whole lot unless they were playing science.

I think a protolathe is not going to fix the problem, because it **_condenses the purpose of all the department lathes into a single machine_** returning us back to pre-techweb RnD, I might write up a PR to address this between now and whenever i feel ready.

**Comment by ma44** [comment]
Do note that you require only 5 techs to get the chance to unlock this (data theory, engineering, emp_basic, high efficiency, advanced engineering), of which engineering and advanced engineering would already help towards advanced plasma cutters. 

Timegates can be further increased by requiring emp_adv or emp_super if wished.

**Comment by deathride58** [comment]
Do you understand the purpose of techwebs at all?

This will do nothing but reintroduce the problem of science getting all of the overpowered shit while all of the other departments get nothing. One of the purposes behind the departmental lathes is to allow coders to add new items without buffing science even more, this PR will make the addition of departmental lathes completely pointless, especially with the insanely easy-to-reach requirements.

An omni-protolathe should require maxed research, if it's *absolutely* necessary.

**Comment by epochayur** [comment]
as much as I miss pre-web science, there is a 0% chance of this being approved

**Comment by FantasticFwoosh** [comment]
- I was more concerned @deathride58 with as silly as it sounds, simply going around replacing all of the department lathes with protolathes as a 'upgrade'.

Figuratively lets say that you have a room large enough to support all of the lathes in there, if you only need to use the protolathe then the purpose of all the other machines isn't nessecary.

**Comment by Spaceinaba** [comment]
research should be 10,000 points MINIMUM if you want even a 2% chance in the entire cosmos

**Comment by Iamgoofball** [comment]
@KorPhaeron they're trying to re-add old R&D, i suggest a close

**Comment by F-OS** [comment]
@Iamgoofball i am literally just giving science the option of building the old protolathe given enough time and research

**Comment by Iamgoofball** [comment]
this is literally just "wait X minutes for oldR&D

**Comment by Cyberboss** [comment]
I'm closing this in a while, we're not going back to pre-techwebs and
people need to stop trying.

**Comment by F-OS** [comment]
There is a difference between reverting techwebs and simply giving science the option of building the lathe, this actually requires more research then some of the weapons and also helps with rebuilding if one of the departmental boards is lost.

**Comment by Buggy123** [comment]
# O L D S C I E N C E I S B A C K

Maybe now I can actually start playing scientist again, since the job isn't completely meaningless. Aside from xeno, of course, which ought to be a separate department anyway, and I don't have the heart to literally constantly kill cute burbling slimes.

**Comment by Repukan** [comment]
Fuck I lost the bet it took more than two weeks

**Comment by XDTM** [comment]
The whole point of the rework was _making RnD not a job_

Keeping the console in the department was a mistake, it gives the wrong idea

**Comment by Buggy123** [comment]
>The whole point of the rework was making RnD not a job

Okay, so should I just start on that PR that removes the science department and scientists completely _now_, or wait to see if this gets merged first.

**Comment by F-OS** [comment]
this pr won't turn into a shitfest not at all

**Comment by Cyberboss** [comment]
Big ships turn slowly, things will smooth out with new research eventually

**Comment by epochayur** [comment]
is anybody actually actively working on improving techweb?

**Comment by Cyberboss** [comment]
If people spent as much time working on improvements rather than reverts we might be moving faster. If you need good ideas ask on #coderbus

**Comment by ExcessiveUseOfCobblestone** [comment]
If your argument is that it's for repairing wouldn't it make sense to put it in engineering since that's their job rather than science?

**Comment by optimumtact** [comment]
We've already rejected this.

stop trying

**Comment by Bombpants** [comment]
I really think that science should be able to get some sort of expanded build list. Maybe instead of locked behind just points, it would require a series of goals to be achieved by all the other departments (like earn x points from engineering from engineers doing y).

**Comment by epochayur** [comment]
gameplay? in techweb? get real, buddy

**Comment by FantasticFwoosh** [comment]
@F-OS  had noble intentions that i find understandable, ill credit them certainly with that  🙇

**Comment by Bombpants** [comment]
@epochayur It would make things better than just wait x minutes to unlock thing y. 
What about I N T E R - D E P A R T M E N T  C O O P O R A T I O N

**Pull request closed without merging**
