### PR TITLE
Renames beach hut

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Mekhi didn't find it amusing and wants it changed. No player references anyway.

### CODE REVIEW

**Comment by kevinz000** [comment]
:^)

**Comment by TechnoAlchemisto** [comment]
Why not name it the love shack after that amazing song

**Comment by Dorsisdwarf** [comment]
Call it Procreatory Station Zeta

**Comment by bgobandit** [comment]
rip lotsu's love shack

**Comment by Cheridan** [comment]
what a cuck

**Comment by PKPenguin321** [comment]
Ban him and it wont be a player reference anymore :::::::^^^^^^^^))))))))

**Comment by KazeEspada** [comment]
Name it Jean

**Comment by KazeEspada** [comment]
Damnit, bad post.
Name it Jean's Love shack

**Comment by KorPhaeron** [comment]
Howabout we don't immortalize one of the most unpleasant players to ever grace our server

**Comment by optimumtact** [comment]
How about we do because it's funny you cuck

**Comment by KazeEspada** [comment]
Free Tonto Poster
DoubleBeard Bearded Wine
ULTRA RARE CUBAN PETE HAT
Rhumba Beat Virus
Pete's Cuban Spiced Rum
George Mellons griefing me. (Predates TG, George Melons was pre-r4407)

**Comment by Cheridan** [comment]
ok i think we got enough code review here

**Comment by Cheridan** [comment]
also Cuban Pete was fine and tonto is a hero

**Pull request merged**
