### PR TITLE
(WIP) Modified the Research sec checkpoint and emergency maintenance on Metastation

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

This removes what was, for me, a really annoying mapping choice on Meta.

## Why It's Good For The Game

It looks a bit better and expands what was a mostly unused closet in Research to something a bit more utilitarian.

## Changelog
:cl:
tweak: The security checkpoint in Research on Metastation has been modified to better fit in the station layout.
/:cl:

### CODE REVIEW

**Comment by TheSilverNuke** [comment]
Not bad but there aren't exactly many places in sci that aren't public already, and this removes one of the few that are private.

I do think it would look cooler if the tiles in what used to be maint were gone tho.

**Comment by Paxilmaniac** [comment]
mulebot cant get to the flaps through maint

**Comment by TheVekter** [comment]
> Not bad but there aren't exactly many places in sci that aren't public already, and this removes one of the few that are private.
I'm not really sure what you mean. The access on those doors in the emergency closet hasn't changed - you still need maint access to get in there, but you can't access Research through the green door without R&D access.

> mulebot cant get to the flaps through maint
I haven't updated the screenshot (and honestly you can look in map diff renders for the current version) but I removed one of the bio lockers and moved the scrubber over to where it was.

**Comment by Iatots** [comment]
By private they meant away from the eyes of  passebys. You have now turned the closet from a small maint room into the only path to enter the security post, AND whoever sits in the sec post has vision inside the room.

**Comment by TheVekter** [comment]
> By private they meant away from the eyes of passebys. You have now turned the closet from a small maint room into the only path to enter the security post, AND whoever sits in the sec post has vision inside the room.

Ahhhhh. I see what you mean. And no, it's not the only path, there's a door right there in the research lobby. I could remove that maint door if enough people think it's a good idea.

**Comment by TheSilverNuke** [comment]
I think that would be a good idea, though the door should probably be moved out of the way of the blast doors if you're gonna do that.

**Comment by TheVekter** [comment]
Yeah I was gonna say, there's a solid variant of the sec airlock isn't there? I'll do that when I wake up.

**Comment by HomocidlePancakes** [comment]
B79AB223-031C-4055-A325-DDE563F96A62

WHAT ARE THOOOOSE!!?

At least put a directional window there. Flaps look super scuffed.

**Comment by Tlaltecuhtli** [comment]
biosuit lockers are useless put the fire lockers there

**Comment by TheSilverNuke** [comment]
Biosuits prevent disease spread and also provide radiation resistance, discount rad suit.

**Comment by Timonkeyn** [comment]
The flaps look like a severe case of dent in head, please move them 1 tile down if you are gonna have ones

Remove 1 Bio suit locker and put the firelocker blocking the flaps there

Remove the tiles and give it the dirty maint look again

**Comment by Cenrus** [comment]
I see a missing reinforced wall, the new room needs decals, and lockers look out of place.

**Comment by TheVekter** [comment]
okay I'm awake

I'm taking the screenshots down in the OP because they're outdated, y'all can click on "Details" next to the map diff renders check and it'll show you what it looks like now.

Working on making it look less pretty/retarded.

**Comment by Dorsisdwarf** [comment]
I'm still not entirely sure what the point of this change is? All it does is add a connection between two nearby unused rooms

**Comment by TheVekter** [comment]
It's mostly cosmetic.

**Comment by PKPenguin321** [comment]
@TheVekter don't say r*****d or github kills you

**Comment by cacogen** [comment]
I don't know what the problem this fixes is and it's weird having maint crap in a closet in research. Also that plastic flap needs that wall beside it otherwise it looks off.

**Comment by TheVekter** [comment]
Going back to the drawing board on this.

**Pull request closed without merging**
