### PR TITLE
plumbing catalyst storag

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request

see title
also see video

https://github.com/user-attachments/assets/23e2d128-1175-4779-87cf-74a4d4e6e1c1

## Why It's Good For The Game

doing in 1 machine what was once done by 3-4 is nicer for the chemist. less materials wasted and more space available to play around in. also has the side effect of making the output slightly higher since time spent transferring catalysts can now be spent on transferring reagents that are consumed instead

## Changelog
:cl:
add: catalyst function for plumbing reaction chambers
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
> Why It's Good For The Game
> i dunno lol

Please elaborate more on this or it will get insta closed because after reading the code all this does is store reagents that are created in a reaction chamber and feed them back as input and that is a very useless feature.

There are 4 points to make on this

1. There is nothing related to catalysts in this PR. A catalyst is a reagent that affects the variables of a reaction without getting consumed and there is nothing here hinting at such mechanics being present so this feature is mislabeled.
2. This can already be achieved via a plumbing setup. Just use a chem splitter to separate your reagent from the output mix, store it in a tank & feed it back into the reaction chamber or into another reaction chamber via ducts. No reason to do this in code
3. Code has poor performance. You are capturing the reagents whenever there is a change in the reaction chamber which occurs when an reagents enters it, leaves it or reacts in it. All these operations happen per tick so with large plumbing setups this can easily cause lag especially with lengthy reactions where large volumes of reagents are involved.
4. Code can cause nested reactions which is even more performance degrading. Your catalyst buffer which captures reagents from the chamber can in turn have reactions occur inside it if you store multiple reagents which could react inside it and again all this is happening per tick so this is very bad
5. The UI is ugly. Button with the label "help" does not look appealing & the extra "C" next to each button in an already small UI window makes it look very clutered.

Overall this adds very little value & a lot of performance degradation to reaction chambers plus is not even efficient at what it does as listed in points 3 & 4. Maybe move it downstream because they might have different plumbing code but over here this has no value

**Comment by lovegreenstuff** [comment]
i just put in whatever to test the code and put up the draft
"i dunno lol" is basically just lorum ipsum

**Comment by SyncIt21** [comment]
> i just put in whatever to test the code and put up the draft "i dunno lol" is basically just lorum ipsum
> 
> thanks for the feedback though i'll make changes

The whole point of my above comment was a polite way of saying "Please close the PR because this feature is obsolete and can be done by a plumbing setup"

There are no need for changes cause there's no point to this feature. I highly suggest you work on the "Why it's good for the game section" first before making changes cause this will closed before you can proceed any further.

**Comment by lovegreenstuff** [comment]
poe2 finished downloading

**Comment by LemonInTheDark** [comment]
> The whole point of my above comment was a polite way of saying "Please close the PR because this feature is obsolete and can be done by a plumbing setup"
> 
> There's no need for changes cause there's no point to this feature. I highly suggest you work on the "Why it's good for the game section" first before making changes cause this will get closed before you can proceed any further.

This is not your decision to make. Code being bad is a solvable problem, and there are many things which are possible through multiple methods. The pr still needs to argue for WHY this is desirable which it is not currently doing, but not doing so is not justification to discourage someone from contributing or insta close a pr.

**Comment by lovegreenstuff** [comment]
workin on this again now that im bored

**Review by Time-Green — CHANGES_REQUESTED** [review]
Really happy to see you work on this! I've always wanted to implement this, but never did because I wasn't sure how to do it cleanly.

I'm not gonna lie though, this is not a good way to do this. Like, this is going to be buggy as hell. It uses procs that expressly don't transfer reagents, to transfer reagents between transfer periods to a hidden catalyst beaker and quickly out again. Any attempt to clean up plumbing code will immediately break this.

I'm also not 100% sure how to do this cleanly (synclt may be able to help with idea's, they've done the most work on reagent/plumbing code recently. if they can behave...). 

I think it would be okay to allocate a certain volume of the main reaction chamber to a catalyst, and simply refuse to transfer the catalyst out during completion. There are a lot of checks you'll need to rewrite to make sure the loading, reacting and emptying phases will still function correctly though. 

You may also be able to add the functionality of reacting in multiple containers into reaction code, but I think we should keep it simple. 

You jumped into pretty deep waters, please don't hesitate to communicate what you plan to do!

**Comment by lovegreenstuff** [comment]
thanks for the feedback man
this is gonna take some serious untangling though. transfer_to occuring receiver side is a problem of all time, and so are the reagent requests with no defined reagent. i'll keep you posted though

**Comment by SyncIt21** [comment]
> i aint got a clue on how to contact john syncit and i dont think they'd help even if i did

Spoke too soon my guy.

I have a plan however it's very difficult to put it in review form as it involves a major rework on top of your PR which is why i have 2 proposals.

1. Get this PR merged as it is right now. I can later build upon it in a later PR
2. You can give me write permissions to your branch and i'll push my commits on top of it. I'll explain the code as reviews later on if needed

EDIT:

The idea has been implemented & tested & works. It's ready to commit, waiting on you

**Comment by lovegreenstuff** [comment]
ay lmao
i'll try and get this done fast

**Comment by SyncIt21** [comment]
I've done the work. So which is it option 1 or 2?

**Comment by SyncIt21** [comment]
> 1. Get this PR merged as it is right now. I can later build upon it in a later PR
> 2. You can give me write permissions to your branch and i'll push my commits on top of it. I'll explain the code as reviews later on if needed

Can you communicate what your intention is

**Comment by lovegreenstuff** [comment]
sorry was sleepin i'll give you write perms in the mronin

**Comment by lovegreenstuff** [comment]
how do i share a repo again

**Comment by SyncIt21** [comment]
> how do i share a repo again

Did you create a protected branch? If not then everyone has write access or I think.

Hang on I'll try to push the commit and I'll let you know about the errors

**Comment by SyncIt21** [comment]
I have no access. Follow [this](https://stackoverflow.com/questions/10886174/how-can-i-give-access-to-a-private-github-repository)

**Comment by SyncIt21** [comment]
Thanks for the write acess. 

I have added a new feature that the reaction chamber will now request catalysts from the pipeline i.e. you don't have to wait for it to come in as input reagents & it won't block other reagents from coming in so it can come when it wants.

Make sure to test it locally & let me know if it works as you intended

**Comment by lovegreenstuff** [comment]
for normal reagents works fine
for conversion reactions like hollow water or unstable mutagen into blood, setting blood as a catalyst leads to buildup.
ploomb5
ploomb4

**Comment by SyncIt21** [comment]
What was the specified amount for blood catalyst?

I'll fix this don't worry

**Comment by lovegreenstuff** [comment]
it was 5u blood

**Comment by SyncIt21** [comment]
need a small clarification.

If the volume of blood in the reaction chamber is greater than 5u then it needs to empty out the excess & keep only 5u remaining right?

**Comment by lovegreenstuff** [comment]
ye

**Comment by SyncIt21** [comment]
Thanks for your patience. Can you test again to see if it works?

**Comment by lovegreenstuff** [comment]
no idea why youre thankin me when youre helpin me for free but eh

regardless of whether its a conversion recipe or standard catalyst reaction, the reaction chamber never leaves emptying state after the first reaction so it stunlocks itself

**Comment by SyncIt21** [comment]
> no idea why youre thankin me when youre helpin me for free but eh

The unpaid labour brag be crazy

> regardless of whether its a conversion recipe or standard catalyst reaction, the reaction chamber never leaves emptying state after the first reaction so it stunlocks itself

Fixed. Can you retest

**Comment by lovegreenstuff** [comment]
works perfectly as far as i can tell
great job

**Comment by SyncIt21** [comment]
Make sure to undraft so this can get merged

**Comment by Time-Green** [comment]
Looks good! Works well too!

image

My only thing is that it legit took me a while to figure out the UI. Make sure to update the wiki

**Comment by Time-Green** [comment]
also good work synclt :)

**Comment by SyncIt21** [comment]
> also good work synclt :)

Loved working on this.

Make sure to remove write access from me and delete the branch(optional)

**Comment by ZealousZeke** [comment]
Huge. Massive. Large. Radical.

**Pull request merged**
