### PR TITLE
Adds Yukata's and Kimono's to the ClothesMate + accessory DLC

### PR DESCRIPTION
**Pull request by Draggeru**
## About The Pull Request

Pretty much the title, adds a set of Yukatas and Kimonos to the ClothesMate for more clothing variety along with matching sandals and a hairpin

real weeb shit
Screenshot 2024-07-13 191053

## Why It's Good For The Game

This PR really has the chefs/bartenders and chaplains in mind who want to do a more traditional vibe to their work spaces and or sushi belts with a bit more theming to it. We have bamboo flooring, furniture and walls so this is the natural evolution. Plus new interesting item helps cultivate the funny sandbox environment.

## Changelog

:cl: Thedragmeme
image: Adds a series of traditional yukata's and kimono's
image: Adds in black sandals and a traditional hairpin for the back of the hair
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Despite the lack of explanation, I think the reason this was closed because of a lack of GBP.

**Comment by Draggeru** [comment]
1984

**Comment by Draggeru** [comment]
Also please tell me why the PR was closed. Wordlessly closing the PR tells me nothing that would be helpful in getting these sprites in the game.

**Comment by DrAmazing343** [comment]
I was really hyped for this, too— why the sudden closure?

**Comment by MrMelbert** [comment]
give a reason next time, and if the reason was gbp, they're only on -2 get off the high horse

**Comment by optimumtact** [comment]
This was closed due to a lack of gbp, and any maintainer can choose to do that at any time no matter how little negative GBP someone has, so this has to stand.

**Comment by sylvia-from-fulp-station** [comment]
As you can see i won the 1v1 vs oranges

**Comment by Yobrocharlie** [comment]
If you have the bartenders in mind it would be really neat if some of them you could shove the armor vest inside so you can still store the shotgun in suit storage instead of having it replace your backpack. Or maybe just have some of them be able to have the shotgun in their suit storage idk

**Comment by Draggeru** [comment]
> If you have the bartenders in mind it would be really neat if some of them you could shove the armor vest inside so you can still store the shotgun in suit storage instead of having it replace your backpack. Or maybe just have some of them be able to have the shotgun in their suit storage idk

I will look into some kind of solution, perhaps allowing the bartender to reskin their armor. However not for this PR

**Comment by Twaticus** [comment]
the hairpin is like 2 pixels do we relly need it

**Comment by projectkepler-ru** [comment]
> the hairpin is like 2 pixels do we relly need it

let me rp as a japanese catgirl please

**Comment by Draggeru** [comment]
> the hairpin is like 2 pixels do we relly need it

I have further plans for the hairpin, but I would like to gage interest for the item first before dedicating my time to an obtuse code project. 

So yes.

**Comment by Loafin34** [comment]
could you add an all-white "bathrobe" version for the lesser-culturally minded? (greyshits)

**Comment by Draggeru** [comment]
> could you add an all-white "bathrobe" version for the lesser-culturally minded? (greyshits)

Maybe I will do a gags version :tm: no promises

**Pull request merged**
