### PR TITLE
March into Mapness - The abandoned Mime Outpost

### PR DESCRIPTION
**Pull request by kinneb**
## About The Pull Request
A Mime Outpost, abandoned after being unsuccessfully raided by clowns.

image
### Mapping March
Ckey to receive rewards: Kinnebian

## Why It's Good For The Game
More ruins is fun! Also, I never see the mime-specific food used so they could make for nifty space loot.
## Changelog
:cl:
add: Added the Abandoned Mime outpost as space ruin!
/:cl:

### CODE REVIEW

**Comment by VladinXXV** [comment]
best map in the event so far i salute you

**Comment by kinneb** [comment]
no more merge conflict 
image

**Comment by Zytolg** [comment]
You didn't resolve your conflict properly. Please make edits to the following coordinates to only have 1 turf type (normally this is impossible to do within the editor but will instead occur on merge conflict)

`Error: (in pop xo) (at (8, 14, 1)) Typepath /turf/open/floor/iron/checker/airless has a banned neighbor: /turf/open/floor/iron/checker/airless`

`Error: (in pop Wc) (at (4, 13, 1), (4, 12, 1), (4, 11, 1), and 8 more) Typepath /turf/closed/mineral has a banned neighbor: /turf/closed/mineral`

`Error: (in pop yY) (at (6, 14, 1)) Typepath /turf/open/floor/iron/checker/airless has a banned neighbor: /turf/open/floor/iron/checker/airless`

`Error: (in pop Kh) (at (7, 14, 1)) Typepath /turf/open/floor/iron/checker/airless has a banned neighbor: /turf/open/floor/iron/checker/airless`

`Error: (in pop Er) (at (2, 7, 1), (3, 14, 1), (3, 7, 1), and 18 more) Typepath /turf/closed/mineral has a banned neighbor: /turf/template_noop`

`Error: (in pop Kr) (at (9, 14, 1)) Typepath /turf/open/floor/iron/checker/airless has a banned neighbor: /turf/open/floor/iron/checker/airless`

**Comment by kinneb** [comment]
hell, i cant figure this out

**Comment by kinneb** [comment]
no, bad github. closing so i can come back to this when i feel up for bugfixing my git

**Comment by kinneb** [comment]
reopening because i have free time now and i know what was causing problems

**Comment by kinneb** [comment]
i promise you there is a wall in that corner now here is a preview: 
image

**Pull request merged**
