### PR TITLE
makes the abductor console use radials

### PR DESCRIPTION
**Pull request by Amelia0010**
:cl: Nicjh
add: Abductor console's select disguise option now uses a radial
/:cl:

image

Definitely much better as a visual interface

### CODE REVIEW

**Comment by Kmc2000** [comment]
>🆑 Nicjh

**Comment by coiax** [comment]
Right, but that console is used for a WHOLE bunch of different things.

**Comment by nichlas0010** [comment]
okay?

**Comment by MMMiracles** [comment]
radials are nice for a lot of things but this isn't one of them

**Comment by nichlas0010** [comment]
why not? You're selecting a disguise, having a visual indication of what you're selection is better than having to guess based on the name, which you can still see by mousing over it.

**Comment by nicbn** [comment]
If the radial gets over 8 items a next button will show up, organizing pages at a maximum of 8 items each

**Comment by MrDoomBringer** [comment]
@nicbn huh neat

**Comment by XDTM** [comment]
Where does the radial show if you use it from the camera console?

**Comment by nicbn** [comment]
Over the object.

**Comment by XDTM** [comment]
which means that it won't work at all while you're looking at the station

**Comment by nicbn** [comment]
Yep. It's like AI status radials, that don't work if your camera (or one of yours cameras) is not at your core.

**Comment by XDTM** [comment]
could be edited to be displayed around the camera eye if activated from there

**Pull request merged**
