### PR TITLE
Lobotomy!

### PR DESCRIPTION
**Pull request by RemieRichards**
Adds the Lobotomy surgery which if successful removes antagonist status from somebody. This allows them to remain in the round <B>just as becoming a borg does.</B>

If the surgery fails the patient instead gains an objective to kill the surgeon (Which using self-surgery, can indeed be yourself which is hilarious.) The failed version of the surgery looks identical to the successful one so you can't meta it.

### CODE REVIEW

**Comment by paprka** [comment]
I would never, ever do this.

**Comment by RemieRichards** [comment]
We had a similair thing on Artyom for quite a while, except it was boring that did so (Boring already does so, it just instead says "Lol ur objectives are permafailed bby"

**Comment by Razharas** [comment]
"Jehal meta cherez meta
Vidit meta - meta meta
Sunul meta meta v meta
Meta meta meta meta" - old russian proverb

**Comment by Iamgoofball** [comment]
you do realize that our ~~metagamers~~ quality players are going to go "ALL CREWMEMBERS ARE REQUIRED TO GET A LOBOTOMY, IF YOU DO NOT YOU ARE VALID KILL"

:-1: x :100: i'd prefer to not get chloral hydrated by security and given a lobotomy while knocked out in the one time i manage to roll an antag because they felt like random lobotomies

**Comment by RemieRichards** [comment]
@Iamgoofball the same could be said of Borging, which does the same.

**Comment by Cheridan** [comment]
terrible idea

**Comment by WJohn** [comment]
Yeah but forcing lobotomies on everyone would get you banned SO FAST. It'd be like brigging everyone "just to be safe".

**Comment by fj45** [comment]
Couldn't you also make it take a very long time to complete?

**Comment by paprka** [comment]
What is the point of this if it doesn't reliably de-antag people even

**Comment by RemieRichards** [comment]
@paprka the failure only triggers if you use shit tools, which is your own fault.

**Comment by xxalpha** [comment]
I like this.

**Comment by Incoming5643** [comment]
There's no protection against people intentionally self lobotomizing for the failure chance antag, not only that, but they also get free greentext by killing themselves.

I really don't think this is a good idea

**Comment by RemieRichards** [comment]
@Incoming5643 you can die from this, easily, because of the saw step.

**Comment by xxalpha** [comment]
Oh yeah, if you can make yourself an antag with this, better remove that. Just in case.

**Comment by dannno** [comment]
this is not a good idea

**Comment by RemieRichards** [comment]
Butts to y'all :P
(Democracy at work, ladies and gentlemen)

**Comment by Niknakflak** [comment]
Can't you just make this surgery make people retarded or disabled in some way?  An equivalence of giving someone a chemical implant to keep them in line.  You could lobotomize antags to keep them alive but harmless.  I mean, I guess you can achieve the same effect through repeated bible hits but this antag objective change thingy is probably a bad idea.

**Comment by Niknakflak** [comment]
Whoops, it was closed during my comment.

**Comment by RemieRichards** [comment]
I'm not really attached to this at all.
I made it in 10 minutes because it seemed cool, overhaul reaction is negative, and thus I closed it.

**Comment by Niknakflak** [comment]
Didn't notice...sorry

**Comment by Incoming5643** [comment]
Now I want to make a button that gives everyone an objective to kill themselves

**Comment by RemieRichards** [comment]
@Incoming5643 do so :)

**Comment by Fox-McCloud** [comment]
Isn't this technically what loyalty implants are for?

**Comment by Dorsisdwarf** [comment]
No, not at all. People need to stop saying that loyalty implants de-antag traitors/lings/wizards/ops/cults. They don't. They aren't supposed to

**Pull request closed without merging**
