### PR TITLE
Removes mechs from the game

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Tin
image
## Why It's Good For The Game
They're boring and their code is bad. If you want to make the game fun for you and your crewmates you still have plenty of cooler options
## Changelog
:cl:
del: Removed mechs
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
Is there code really that bad i thought they've been refracted and updated?

**Comment by Metekillot** [comment]
Why would you merge something so controversial yet so brave?

**Comment by Metekillot** [comment]
image
God we love to see a code rework that removes line bloat

**Review by ZephyrTFA — APPROVED** [review]
loose approval

**Comment by LemonInTheDark** [comment]
Elaborate on the boring part

**Comment by Astrogem2** [comment]
mad-max

**Comment by jlsnow301** [comment]
> Elaborate on the boring part

at most, a mech is a showcase of wasteful material spending habits. a trap for new roboticists. it's a solo project that does not contribute anything to the station that a singular player can't excel in. it's not great at combat, mining, nor medical. takes no effort to cobble together: just print the parts and follow the wiki, only to let it collect dust without any opportunity to use in a shift.

**Comment by ArcaneMusic** [comment]
This says a lot about our society

**Comment by Holinka4ever** [comment]
I understand thats is for laugh and giggles, but these guy is right, mostly robotists makin mechs or to die from antag, with mech being stolen, or use it round end grief.
So what about to make battle mechs un-usuable in round end grief? It will encourage robotists to not spend time to make a battle mech again.

**Comment by Loafin34** [comment]
ok so are maulers gonna be removed because those things are really fun

**Comment by isotope436** [comment]
now im gonna give this pr the benefit of the doubt and say that its not just throwing everything you can at the wall and hoping it sticks so.

first off saying its bad at "medical, mining, and combat" is just flatout wrong the ody alone is extremely valuable especially during high death antag rounds like cult. A med beam and mobile pax dart thrower is far more useful than people seem to realize

as for mining the clarke can quite literally solo mining and you dont even need to be a miner to use it im pretty sure with enough strafing and patients you could kill bubblegum with that thing it also has a practically unlimited use plasma cutter that last i knew had the longest range of the bunch with a free mining satchel of holding to boot 

as for combat this is where a small part of me thinks this is a "i ded pr" because saying a phazon or shotgun gygax is bad at combat is mind boggling and calling it a "waste of materials" when drills print unlimited mats for basically free makes this even less correct than it was some odd 6 months ago 

and well you didnt mention cargo im surprised you didnt since technically speaking thats the only place as of current where mechs lack since the cargo modsuit is just flatout better its practically the only department where this would make sense and well you are technically right the mech code is old/bad but thats because its been around nearly as long as TG has and even then with recent refractors, tgui updates, and new mechs being added (with one being added to cargo in the last like 3 months if i remember correctly) the code here is probably 3-4 times more functional than other servers and thats putting it mildly. I do not recommend going onto a place like yogs or bee and trying to make a new mech.

**Comment by LSommers** [comment]
"at most, a mech is a showcase of wasteful material spending habits."
what is "miners doing their job"?

"a trap for new roboticists"
probably the only valid point but just yell at them not to do that

"a solo project that does not contribute anything to the station that a singular player can't excel in"
"it's not great at combat, mining, nor medical"
medical/mining/sec mechs get used all the time because of sheer utility, combat mechs are able to tango with threats that would otherwise cause multiple casualties, etc- the only mech that doesn't contribute anything is the HONK mech but even that is debatable.

"takes no effort to cobble together, just print the parts and follow the wiki"
surgery is too easy, you just follow the wiki or spam surgery tools until it works 
chemistry is too easy, just press the buttons and follow the wiki
etc

"only to let it collect dust without any opportunity to use in a shift"
nobody EVER fucking gives up a free mech, it WILL get used
(especially when sec forgets to ID lock their durand for the fifty fucktillionth time this week and it gets jacked by the clown)

**Comment by san7890** [comment]
I am not happy with removing an integral portion of the claim with two sentences in your PR body. Please update and elaborate on this. No other opinions at this time.

**Comment by GuillaumePrata** [comment]
We should let mechs die today and later they come back from the ashes, but well designed this time.

Strat worked well for Circuits.

**Comment by ATH1909** [comment]
> a trap for new roboticists.

is it really a trap if they still have the inherent payoff of being badass?

like, yeah, they're pretty impractical outside of, like, specifically blob and nukie fights, but we're here to have fun, not be strictly optimal

(to be clear, I do think it would be better if they were badass *and* practical)

**Comment by KingkumaArt** [comment]
Yeah outside phazon's ability to run through walls, the fact you can toolbox an unrobust durand pilot to death means they are far from flawless kill machines.

**Comment by necromanceranne** [comment]
Isn't this kind of PR the exact same thing that caused MSO to get pissed off at the maints about virology? AND on TGMC? I feel like you should cool it on the low effort flame bait prs, I really don't want to have to put up with Chud Plague here as well.

**Comment by Admiral-Gigaton** [comment]
So uhhh... can't wait for part 2 of MSO publicly executing coders for this kind of shit

(Flash back to MSO putting a wanted: dead bounty on some TGMC coders for this shit)

**Comment by jlsnow301** [comment]
> I feel like you should cool it on the low effort flame bait prs, I really don't want to have to put up with Chud Plague here as well.

lol

**Comment by Sadboysuss** [comment]
I feel like buffs and nerfs have a better place here, outright removal seems too far and would invalidate all the work we've put into mechs by now. Roboticist content is: Cyborgs, bots, augments and endgame - mechs. I don't think an outright removal is justified, even if they are a bit silly.

**Comment by YuliceTheDruid** [comment]
Honestly if we could improve modsuits to not suck huge mega dongo dick then they could end up taking mech's place entirely.

**Comment by Sadboysuss** [comment]
> Honestly if we could improve modsuits to not suck huge mega dongo dick then they could end up taking mech's place entirely.

Modsuits aren't that bad but it's a separate discussion not relevant to this PR

**Comment by jlsnow301** [comment]
> Honestly if we could improve modsuits to not suck huge mega dongo dick then they could end up taking mech's place entirely.

Agree here

**Comment by Metekillot** [comment]
Why are mech weapons not gated behind security fabdicators or access? You need a security fabdicator for a self recharging energy gun someone can shove you over and steal, but your mounted LMG on a few hundred HPs worth of metal that needs explosives and EMPs to counter is just freely available to any Roboticist who tiptoes up to the R&D console?

**Comment by Metekillot** [comment]
Why are mech weapons not gated behind security fabdicators or access? You need a security fabdicator for a self recharging energy gun someone can shove you over and steal, but your mounted LMG on a few hundred HPs worth of metal that needs explosives and EMPs to counter is just freely available to any Roboticist who tiptoes up to the R&D console?

**Comment by Metekillot** [comment]
We should move every single mech feature onto MODsuits and modules, and if a mech had something that wouldn't be appropriate on a MOD... Well, why does it have it at all?

**Comment by Metekillot** [comment]
Why does deploying a MODsuit take longer than getting into a mech

**Comment by SimplySmiley123** [comment]
> the only mech that doesn't contribute anything is the HONK mech but even that is debatable.

It's arguably the strongest combat mech solely because of the horn that can and will screw over everyone in the immediate area with a lengthy stun.

**Comment by SimplySmiley123** [comment]
> Why are mech weapons not gated behind security fabdicators or access? You need a security fabdicator for a self recharging energy gun someone can shove you over and steal, but your mounted LMG on a few hundred HPs worth of metal that needs explosives and EMPs to counter is just freely available to any Roboticist who tiptoes up to the R&D console?

The counter in the meantime, available to anyone who can get iron and uranium from techfabs or the ORM, or any other source and anything that can grind stuff.

**Comment by Exester509** [comment]
It's a feature that's neither gamebreaking, nor completely unused. We can't just remove things from the game just because they aren't the meta, or the coder personally doesn't like them. I really don't think a full on removal of mechs is deserved.

**Comment by SimplySmiley123** [comment]
> We should let mechs die today and later they come back from the ashes, but well designed this time.
> 
> Strat worked well for Circuits.

And the circuits ended up a novelty that barely anyone ever bothers with.
Yeahhhhh no.

**Comment by Maximal08** [comment]
A typical T-coder, I died in the round because of something, so tomorrow I will write on github, they requested a pool request to do this.

**Comment by Jacquerel** [comment]
This PR is insufficient to justify making this change or to start a conversation and none of the replies made by the PR author so far have contained any particular effort to begin one either. There doesn't appear to actually be any drive to merge this PR from you, nor does there appear to be any engagement with people replying in order to get any useful information out of having opened it, therefore there's no reason for it to remain open.
Feel free to reopen or make a new PR when you have tried to justify the change you are making. Maintainers aren't free from the responsibility to actually fill in the PR body or justify their changes.

**Comment by githubuser4141** [comment]
> > Elaborate on the boring part
> 
> at most, a mech is a showcase of wasteful material spending habits. a trap for new roboticists. it's a solo project that does not contribute anything to the station that a singular player can't excel in. it's not great at combat, mining, nor medical. takes no effort to cobble together: just print the parts and follow the wiki, only to let it collect dust without any opportunity to use in a shift.

this is just a skill issue that showcases you don't know how to play. i have like uhhhh 1000+ hours as using a mech in this codebase and other codebases of the game and you are completely wrong on their power (which is fully editable by adjusting variables BTW you don't have to be a coder to make mech guns do more/less damage)

**Comment by githubuser4141** [comment]
> > > Elaborate on the boring part
> > 
> > 
> > at most, a mech is a showcase of wasteful material spending habits. a trap for new roboticists. it's a solo project that does not contribute anything to the station that a singular player can't excel in. it's not great at combat, mining, nor medical. takes no effort to cobble together: just print the parts and follow the wiki, only to let it collect dust without any opportunity to use in a shift.
> 
> this is just a skill issue that showcases you don't know how to play. i have like uhhhh 1000+ hours as using a mech in this codebase and other codebases of the game and you are completely wrong on their power (which is fully editable by adjusting variables BTW you don't have to be a coder to make mech guns do more/less damage)

also are mechs good at combat or not? you say they're all weak and shit (again, can be EASILY adjusted with numerical variables, NO CODING REQUIRED.) then you say they can 'tango with' antags that'd normally cause a lot of casulties/manpower to handle. Which is it? It actually sounds like you're saying mechs have a lot of potential power (power "density"???) but due to their slowness and lack of agility function best as support units or something?

**Comment by jlsnow301** [comment]
> this is just a skill issue that showcases you don't know how to play. i have like uhhhh 1000+ hours as using a mech in this codebase and other codebases of the game and you are completely wrong on their power (which is fully editable by adjusting variables BTW you don't have to be a coder to make mech guns do more/less damage)

imagine if you spent those thousands of hours contributing or roleplaying
seems like you've engaged in a discussion with yourself tho, carry on

**Pull request closed without merging**
