### PR TITLE
Reduces caramel's nutriment factor by 80%

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request
What it says on the tin. Nutriment factor is now 2, down from 10.

## Why It's Good For The Game
Kind of goofy that we can use caramel (an easy to mass produce fluid) as a meal replacement by slapping a patch on us to do so. Goof is working on a more permanent fix for this but, until then, this is a sane resolution that allows players to continue to make it without needing to bother the cook for it.

I know this removes the ability for the chemist to stand in for the cook, and while I don't necessarily hate the idea of that, it really shouldn't be through an objectively easier to make and genuinely filling method that has no drawbacks whatsoever. Make nutriment paste instead.

The actual fix for this would be to just make it so that you can't absorb nutriment through your skin using a patch, but I'm not familiar enough with how that system works to make that happen. Coderbus was saying earlier that it seems as if that's not intentional behavior anyway, so hopefully it will be fixed in the future, but this is a low-impact fix for the time being.

An aside, but did you know caramel had a higher nutriment factor than chocolate pudding? How does that track?

## Changelog
:cl: Vekter
balance: Caramel is no longer more filling than many other foods, meaning slap patching it on yourself should not constitute a full meal.
/:cl:

### CODE REVIEW

**Comment by MatrixOne500** [comment]
Caramel is a last resort food that's used only when the kitchen is gone. The chef's food that buffs mood is infinitely preferable. This change only hurts people on red hunger who are already denied a chef, it's completely anti-player and unnecessary.

**Comment by Xander3359** [comment]
> > Caramel is a last resort food that's used only when the kitchen is gone. The chef's food that buffs mood is infinitely preferable. This change only hurts people on red hunger who are already denied a chef, it's completely anti-player and unnecessary.
> 
>     * Cargo can order pizza.
> 
>     * Vending machines (I know vending food kind of sucks but it's better than nothing).
> 
>     * Botany can make food.
> 
>     * Assistants can get access via HoP or break in to make food if no cook is available.
> 
> 
> There are solutions that make sense here that don't involve completely invalidating a department's gameplay.

If there is no chef, no botanist, no cargo pizza.
Your last option is really just to drink sugar/caramel.
There isn't any single person who is tiding the kitchen as an assistant to make food for everyone with no access.
This is really harmful especially to lowpop.

**Comment by DaCoolBoss** [comment]
I approve of this because it makes the nutritional content of desserts more consistent and dependant on food quality.

The caramel factories will still exist. Just make the dose 5x higher.

**Comment by TheVekter** [comment]
> If there is no chef, no botanist, no cargo pizza. Your last option is really just to drink sugar/caramel. There isn't any single person who is tiding the kitchen as an assistant to make food for everyone with no access. This is really harmful especially to lowpop.

I don't know how to say this in a diplomatic way, so I'll just be blunt: Make the goddamn food yourself.

**Comment by Xander3359** [comment]
> I am not a fan of allowing "easy button" solutions just so that you don't have to worry about making your own food when there's no cook around. I understand that is annoying for some low-pop users but it's not that difficult to make a burger once every half an hour.

It actually is quite difficult to:
>Go halfway across the entire map
>Hope there's meat in kitchen (or that you somehow have some?)
>Hope there's tools
>Hope there's bread
>Sit in the kitchen for 10 minutes and hope nobody is after you while you are busy making a burger

**Comment by TheVekter** [comment]
> It actually is quite difficult to: >Go halfway across the entire map >Hope there's meat in kitchen (or that you somehow have some?) >Hope there's tools >Hope there's bread >Sit in the kitchen for 10 minutes and hope nobody is after you while you are busy making a burger

Then I would recommend finding another solution that would be more cohesive with your view of the game and having that PRed. I am not making balance changes that will make the game worse for higher pop counts just because it makes it better for lower ones.

**Comment by improvedname** [comment]
What next making legion cores not restore your hunger to full?

**Comment by TheVekter** [comment]
> What next making legion cores not restore your hunger to full?

This is a false equivalency; legion cores require explicit effort to obtain and are not unlimited once you've performed a cursory amount of work. They also can't be automated.

**Comment by Metekillot** [comment]
You can get vending food pretty easy by bonking the vendors with a low damage object, as long as you take steps to have it not crush you. Grind it up and extract the protein, nutriment, fat, etc if you wanna avoid the sugar

**Comment by RBasilisk** [comment]
if we're gutting caramel we should probably remove caramel from some of the existing food items that rely on it as a nutrition source maybe. I believe there might be other options besides ruining the chemical itself that wouldn't have as far reaching consequences, but this is an intermediate step if we HAVE to prevent chemists from providing nutrition to MDs as it is right now.

I'd still choose a chef's food over a patch pile so I don't even see how this is a problem, but, if it's gonna be done we should consider how caramel and nutrition are balanced in general before removing, as an 80% nerf is basically removing, caramel from being an option.

**Comment by Metekillot** [comment]
I don't see what this adds to the game or fixes, by the way. Like... Who cares? And if they do, why? Caramel patches aren't muscling out the chef's job. Chef foods give speed boosts, healing, rare chems in some cases, and shock immunity at the highest 2 tiers.

**Comment by carlarctg** [comment]
I've literally never seen this on terry or sybil. You're patching away a cool sandbox toy that's an interception of game mechanics that happens every so often because of some wishy-washy meaningless balance concern, or maybe getting really really angry some people like to eat hot sugar instead of Going To The Kitchen. This isn't a competitive game, you don't need to do that.

**Comment by TheVekter** [comment]
For the record, I'm not even actually removing the functionality (which has actively been discussed in coderbus, as apparently it's possible being able to absorb nutriment through your skin using a patch is a bug), I'm just making it less effective because I think being able to construct an infinite "print food" machine in ~10-15 minutes is kinda busted and shouldn't be as effective as it is.

**Comment by Jackal-boop** [comment]
Does this effect rhe nutrition  of foods made with caramel?

**Comment by CRITAWAKETS** [comment]
fun fact the public garden is there. its free. you can just grow apples there
the public garden's actually really useful, assistants can just make toolbelts (or boxes if you're a filthy storagemaxing powergamer) for essentially nothing but a somewhat insignificant time investment

**Comment by TheVekter** [comment]
> Does this effect rhe nutrition of foods made with caramel?

I don't think so, but I'll check and raise the nutriment value on the food itself if so.

**Comment by TheVekter** [comment]
> I've never even seen a caramel patch factory on Sybil or Manuel, and no one seems to have ever seen one on Terry. This comes across as a nerf made because someone is upset at the IDEA of caramel patches making the chef useless, rather than it being something which actually ever happens.

This mindset is really confusing to me because, if it's really as rare as y'all say it is, why is the push back for me reducing it's efficacy so severe? You guys are saying "THIS NEVER GETS USED DON'T NERF IT", but if it never gets used, why do you care if it gets nerfed?

**Comment by Dorsisdwarf** [comment]
What I wanna know is why Caramel had a nutrition value 5 times higher than sugar in the first place.

**Comment by GPeckman** [comment]
> There are solutions that make sense here that don't involve completely invalidating a department's gameplay.

I'm kind of curious, what is it about the four alternatives you listed that doesn't invalidate the chef's gameplay?

**Comment by Metekillot** [comment]
The point that I'm personally making is the following: 

Hardly anyone has ever done this. Anyone who does do this is typically doing one of the following 

A) fucking themselves out of the half dozen quite good benefits of getting food from the chef 
B) doing this because there is no chef 

Yes I myself have mentioned that vending machines can be a source of food, even though their prices are frankly exorbitant. But the caramel thing is a useful quirk. If you want to make them not absorb through patches then go off I guess. Honestly patch is working the way they do now seems odd as hell to me, they just seem like pills but worse and sometimes they work in places they shouldn't seem to for some reason? I don't know that whole thing seems like it might need a passover but that's beside the point.

Caramel is not a replacement for food. From what everyone so far has said it seems like it's something that a desperately hungry person with chemistry or pharmacy access will resort to whenever the chef is either dead, not playing, or grossly incompetent. 

This change seems like it's... I guess going for realism but to what benefit? As has been said already there's not some pervasive issue of chemical factories muscling the chef out of their job duties.

**Comment by Archie700** [comment]
> I'm now finding out that slime food makes you disgusted which is baffling, I'm probably going to rework this as keeping the caramel nerf but also reintroducing slime food as a viable alternative that will do much the same as regular food with lower satiety and a negative moodlet

The reason why slime food was nerfed then is pretty much the same reason why people are focusing on caramel factories now.

**Comment by TheVekter** [comment]
> > I'm now finding out that slime food makes you disgusted which is baffling, I'm probably going to rework this as keeping the caramel nerf but also reintroducing slime food as a viable alternative that will do much the same as regular food with lower satiety and a negative moodlet
> 
> The reason why slime food was nerfed then is pretty much the same reason why people are focusing on caramel factories now.
> 
> It was too strong an alternative.

I'm pondering if there's a happy middle ground, because at least slime food takes input to make and isn't a "set it and forget it" solution.

My current idea is to make it kind of like Star Trek Replicator food - it tastes _okay_, but it's very clearly not actually the food it's supposed to be. It gives decent satiety but applies a negative moodlet that says something about the meal not being very satisfying.

**Comment by Loafin34** [comment]
> > There are solutions that make sense here that don't involve completely invalidating a department's gameplay.
> 
> If there is no chef, no botanist, no cargo pizza. Your last option is really just to drink sugar/caramel. There isn't any single person who is tiding the kitchen as an assistant to make food for everyone with no access. This is really harmful especially to lowpop.

i do exactly this lmao. it's really easy to tide food and you suck ass... also food vendors exist

**Comment by plutori** [comment]
At the very least, I think that it should have a satiety of 3, on the grounds that people are saying sugar's satiety is 2, and caramel is the cooked version of sugar. Since it requires more effort and work than sugar does, it should have 1 higher satiety.

**Comment by TheVekter** [comment]
> At the very least, I think that it should have a satiety of 3, on the grounds that people are saying sugar's satiety is 2, and caramel is the cooked version of sugar. Since it requires more effort and work than sugar does, it should have 1 higher satiety.

Why would it magically become more satiating just because you heated it up a bunch

**Comment by Xander3359** [comment]
> > At the very least, I think that it should have a satiety of 3, on the grounds that people are saying sugar's satiety is 2, and caramel is the cooked version of sugar. Since it requires more effort and work than sugar does, it should have 1 higher satiety.
> 
> Why would it magically become more satiating just because you heated it up a bunch

The same reason why food in real life is more nourishing after cooking it?

**Comment by DaCoolBoss** [comment]
The point of caramel as a food chemical, to me, is the taste_mult stat of 2. Cooking caramel makes it significantly better than sugar when used as a food additive because it directly improves the flavour stat of food.

**Comment by plutori** [comment]
> > At the very least, I think that it should have a satiety of 3, on the grounds that people are saying sugar's satiety is 2, and caramel is the cooked version of sugar. Since it requires more effort and work than sugar does, it should have 1 higher satiety.
> 
> Why would it magically become more satiating just because you heated it up a bunch

Heat thing up, it de-natures it into more base components for your body, and your body therefore gets more nutritional value out of it. That's how cooking works irl.

**Comment by CRITAWAKETS** [comment]
> > > At the very least, I think that it should have a satiety of 3, on the grounds that people are saying sugar's satiety is 2, and caramel is the cooked version of sugar. Since it requires more effort and work than sugar does, it should have 1 higher satiety.
> > 
> > 
> > Why would it magically become more satiating just because you heated it up a bunch
> 
> Heat thing up, it de-natures it into more base components for your body, and your body therefore gets more nutritional value out of it. That's how cooking works irl.

Except that's not what happens with caramel, which is just sugar heated up until it decomposes into glucose and fructose that then undergoes a maillard reaction. Because of how the human body works, sugar is pretty much pure nutrition and the process of caramel gets rid of some of the sugar to turn it into other molecules, usually flavor molecules.

Plus there's a bit more with de-naturing and what nutritional value you get out of it, mostly being micronutrients rather than macronutrients which is what matters in this case.

So if you want to go with the realism argument, caramel should have a bit less nutrition than sugar. Realism sucks for gameplay balancing though.

**Comment by ExcessiveUseOfCobblestone** [comment]
Was I supposed to be handling this issue tee hee

**Comment by TheVekter** [comment]
I'm not really that interested in making this change anymore. I feel like there's a bit of an issue with getting decent food in lowpop without having to have someone change jobs to cook to do it, and while I think that's the idea change, 1) I get why people might not want to abandon what they planned on doing to make food and 2) I've been actively watching higher pop rounds and not seeing this abused in the way I was worried it was.

I reserve the right to change my mind if I see people actually start building caramel factories to get around cooks making food but I don't think this is as big of an issue as I anticipated. I think the actual solution looks something like making it require scaling power depending on how long it's running or requiring some kind of input to keep chem factories running (other than power), but that's WAY out of my wheelhouse.

**Comment by TheVekter** [comment]
Also I can and will bring this back if Goof goes back to wanting to remove the ability to make it from factories wholesale; I still think this is a better change than that.

**Pull request closed without merging**
