### PR TITLE
Introducing the Standby Emergency Vessel, "Scrapheap Challenge"

### PR DESCRIPTION
**Pull request by Thunder12345**
:cl: Thunder12345
add: Added the Standby Emergency Vessel "Scrapheap Challenge" as a new emergency shuttle option. You'll even be paid 1000 credits to use it!
/:cl:

Behold:

As inspired by this monstrosity of multiple shuttle ordering:

### CODE REVIEW

**Comment by Niknakflak** [comment]
No real purpose besides making a shuttle out of a meme everyone will forget in a couple days

**Comment by Archie700** [comment]
At least it's functional

**Comment by Arianya** [comment]
and airtight, unlike some shuttles

**Comment by Thunder12345** [comment]
@Niknakflak Also remember that nobody at all understands some of the existing shuttles. See: The wooden box thing

**Comment by Cheridan** [comment]
It needs the corpse in the bathroom.

Also +1000 credits seems a bit much since yeah while its weird it's still a real shuttle

**Comment by Thunder12345** [comment]
It has no medbay though, and is ridiculously easy to breach

**Comment by JJRcop** [comment]
this will be our first .dm file with the word "fuck" in it

**Comment by Incoming5643** [comment]
please call it something else

**Comment by Cheridan** [comment]
seconded

**Comment by Thunder12345** [comment]
We already agreed that is a true fuck shuttle of coderbus

**Comment by optimumtact** [comment]
Looks ugly

**Comment by ShadowDeath6** [comment]
emergency_fuck.dmm is by far the best file name I've ever read

**Comment by KorPhaeron** [comment]
When the head coder says "please" he's not suggesting he's telling you to do something politely.

**Comment by Thunder12345** [comment]
I don't know what he even wants me to change is it the filename or the shuttle name itself?

**Comment by KorPhaeron** [comment]
I'm assuming both, but you'd have to ask him

**Comment by Incoming5643** [comment]
Personally I don't care what people put in the code, I just think that throwing swears at players is bad form.

**Comment by KorPhaeron** [comment]
We should generate these on the fly by randomly loading 4 shuttles at once

**Comment by Thunder12345** [comment]
But then we get into the issue of the shuttle being breached on arrival

I did see a suggestion for a randomly generated space hulk shuttle, though. Captain gets to spend credits on modules for it and such

**Pull request merged**
