### PR TITLE
Minor tramstation and train-rail-fluff fixes

### PR DESCRIPTION
**Pull request by MrDoomBringer**
## About The Pull Request
Fixes an incorrectly-shifted sprite for floor tram rails and adds some missing tram-rail fluff objects
Also does some minor renaming (railing -> rail)

## Why It's Good For The Game
looks better
**before:**
image
**after:**
image

## Changelog
:cl:
fix: Nanotrasen railroad engineers have done some minor repairs to their in-station tram rails.
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
step right up maintainers get your free green squares here hot and ready

**Comment by ShizCalev** [comment]
conflict

**Comment by MrDoomBringer** [comment]
no i didn't mess up my commit history while attempting to merge the sun was in my eyes bro I swear bro

**Comment by Mothblocks** [comment]
sorry my cat jumped on my keyboard i didnt mean to close it

**Comment by MrDoomBringer** [comment]
NOOOOOOOOO NOT AGAIN

**Comment by MrDoomBringer** [comment]
AAA

**Comment by MrDoomBringer** [comment]
image

**Pull request merged**
