### PR TITLE
Disk "fridge" Machine [QoL]

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
add: You can now build a disk ''''''fridge''''''''. goes great with botany gene machines [and I guess you can put the nuclear disk in there if you want to keep it cool :shades:].
/🆑 

Reasoning: It's a pain managing disks, having them in a fridge [I think] would be easier to manage and read.

Next time someone updates the map be a bro and add this to botany. You can still build it now with just one matter bin and the board [reprogram the fridge in botany, it's not like you actually provide food to the chef].

Also replaces the return values with TRUE/FALSE defines because it makes a bit more sense.

### CODE REVIEW

**Comment by Jordie0608** [comment]
This can hold the nuke disk, intentional?

**Comment by ExcessiveUseOfCobblestone** [comment]
yes, although this is a REALLY bad spot to place said disk in.

**Comment by ExcessiveUseOfCobblestone** [comment]
wowzers those silly errors.

AVERT YOUR EYES CHILDREN

**Comment by jughu** [comment]
Now i can have a disk in a portable storage 👍

**Pull request merged**
