### PR TITLE
Body split action now refreshes each spec_life tick

### LINKED ISSUE #87238: UI issue with slimepeople and maybe more
### Client Version:

515.1642

### Issue Summary:

slimepeople's split body and regenerate limb buttons dont update until you lay down for some reason

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

go goo
eat a lot
observe split button

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Closes #87238

slimeperson spec_life builds split action button icons after adjusting volume and nutrition

## Why It's Good For The Game

fixes an ui issue where the split button rarely updated, now it updates every life tick and shows when you can split or not

## Changelog

:cl:
fix: Body split action now refreshes each spec_life tick
/:cl:

### CODE REVIEW

**Review by MrMelbert — COMMENTED** [review]
This spec life should be deleted and handled via the `slime_blood()` proc, perhaps as a proc called in the middle of the proc, perhaps as an override of the proc itself

That proc already updates all the slime's buttons, so we should bundle everything there

**Comment by carlarctg** [comment]
holy shit can't let me have one win

**Comment by MrMelbert** [comment]
me when i have to do 5 minutes of work to fix something properly

**Comment by Syilumi** [comment]
dam..

**Pull request closed without merging**
