### PR TITLE
Revert "Adds support for Multiple products"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#20177

### CODE REVIEW

**Comment by optimumtact** [comment]
Breaks master

**Comment by Iamgoofball** [comment]
why?

**Comment by Iamgoofball** [comment]
NO


WE FIX

**Comment by AnturK** [comment]
@nullbear

**Comment by nullbear** [comment]
It works fine on my end. Probably a merge-conflict related cause by someone elses commit which is dependent on mine. I'm workin' on fixing it.

**Comment by nullbear** [comment]
Fixed: https://github.com/tgstation/tgstation/pull/20232
Someone added a new slime core recipe (glass) and it didnt show up as a merge conflict.

**Pull request merged**
