### PR TITLE
Space Motel: a new cozy ghost role.

### PR DESCRIPTION
**Pull request by Djiq**
obraz

## About The Pull Request

This pr adds a new space ruin : Space Motel! Space motel contains a few rooms for guests that find it in space, a bar a kitchen a stage a small hydroponic garden and a beach. The goal of the space motel is to add a new friendly port for space explorers, the ruin doesn't contain any gamer loot, so it will not draw powergamers from the station, rather it will attract people that are *already* exploring space. Below is the screenshot of the motel, a few notes : the bartender *cannot* leave, literally, the blue walls will let everything through but lasers, atmos AND the bartender, the area is also noteleport , so bluespace shenanigans are a no-go. 

obraz

## Why It's Good For The Game

Space is really really bland, and this adds a little bit of soul to it.

## Changelog
:cl:
add: New space ruin : Space Motel
add: New ghost role : Interstellar bartender
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
image
amazing

**Comment by necromanceranne** [comment]
Could we get a pier or a dock for the whiteship? I'd like another port for the whiteship to arrive at, and it'd make it more likely for folk to visit.

I am a little apprehensive about the idea of a bartender spawning with the possibility of nobody around to visit. Maybe include some patron spawners, or maybe even a touristbot portal?

**Comment by EdgeLordExe** [comment]
> 
> 
> Could we get a pier or a dock for the whiteship? I'd like another port for the whiteship to arrive at, and it'd make it more likely for folk to visit.
> 
> I am a little apprehensive about the idea of a bartender spawning with the possibility of nobody around to visit. Maybe include some patron spawners, or maybe even a touristbot portal?

there is a tourist bot portal already installed, i thought of it already :heart:

**Comment by EdgeLordExe** [comment]
> 
> 
> Could we get a pier or a dock for the whiteship? I'd like another port for the whiteship to arrive at, and it'd make it more likely for folk to visit.

thats a good idea, i will add that soon

**Comment by necromanceranne** [comment]
must have missed it. My bad! Good work. Though I don't know how much money that the person would be able to get due to a lack of a bank account...

**Comment by EdgeLordExe** [comment]
> 
> 
> must have missed it. My bad! Good work. Though I don't know how much money that the person would be able to get due to a lack of a bank account...

bank account is also initalized for the bartender

**Comment by wesoda25** [comment]
I like the idea but how is this functionally much different than the beach biodome?

**Comment by EdgeLordExe** [comment]
> 
> 
> I like the idea but how is this functionally much different than the beach biodome?

beach biome had literally nothing in it, you literally had nothing to do other than try to escape, here you can at least pass time with tourists and hydroponics

**Comment by kinneb** [comment]
What about carp? I wouldn't want to spawn in only to discover that some space explorer accidentally lured carp and got the windows destroyed. We should at least have a toolbox to make repairs. Otherwise, this looks like a fun ghost role.

**Comment by Valorium-RB** [comment]
> What about carp? I wouldn't want to spawn in only to discover that some space explorer accidentally lured carp and got the windows destroyed. We should at least have a toolbox to make repairs. Otherwise, this looks like a fun ghost role.

Seconded.

**Comment by Ghilker** [comment]
ah yes the "i wait hoping someone will stumble across me" ghost role

**Comment by nullAdept** [comment]
maybe you should replace the beach biodome with this? beach biodome is pretty similar to this but unlike this it sucks fuck beach biodome

**Comment by RaveRadbury** [comment]
We already have a space hotel ruin. Why do we need another one?

**Comment by Valorium-RB** [comment]
> We already have a space hotel ruin. Why do we need another one?
> 
> Also this is another space clubhouse for players to shirk off to for a whole shift.
> 
> image

Are you referring to Hilbert's?

**Comment by RaveRadbury** [comment]
> Are you referring to Hilbert's?

No, I'm not. We have a Space Hotel ruin. It is disabled in the config because it was considered to be terrible, afaik due to crew separation and hotel staff trying to leave for the station. This only addresses one of those things.

We do not need more "cozy" ruins. Ruins should be ruins, they should be transient spaces that you come to and leave. We should not be encouraging crew to dock the whiteship at a motel and spend the whole round their with their metaclique.

**Comment by Valorium-RB** [comment]
> > Are you referring to Hilbert's?
> 
> No, I'm not. We have a Space Hotel ruin. It is disabled in the config because it was considered to be terrible, afaik due to crew separation and hotel staff trying to leave for the station. This only addresses one of those things.
> 
> We do not need more "cozy" ruins. Ruins should be ruins, they should be transient spaces that you come to and leave. We should not be encouraging crew to dock the whiteship at a motel and spend the whole round their with their metaclique off-station.

Fair enough.  I do think there needs to be some kind of Beach Biome equivalent for space because having to deal with lavaland is eh and Charlie Station is the least cozy place on Earth.

**Comment by RaveRadbury** [comment]
> Fair enough. I do think there needs to be some kind of Beach Biome equivalent for space because having to deal with lavaland is eh and Charlie Station is the least cozy place on Earth.

The Beach Biome doesn't separate the crew in the same way that places like Deep Storage and the Whiteship do, in part because Lavaland is one Z-Level. Fucking off to space for entire rounds is a common issue, its unbalanced against antags, and it separates players from the rest of the crew. It's a headache and it runs counter to one of the big points of this game (playing with other people, not just your metafriends).

If you're really looking for balance tbh just kill the beach biome then. It doesn't get used in the same way that space ruins do but if that's how you want to frame it we'd be better off without it.

**Comment by Valorium-RB** [comment]
> > Fair enough. I do think there needs to be some kind of Beach Biome equivalent for space because having to deal with lavaland is eh and Charlie Station is the least cozy place on Earth.
> 
> The Beach Biome doesn't separate the crew in the same way that places like Deep Storage and the Whiteship do, in part because Lavaland is one Z-Level. Fucking off to space for entire rounds is a common issue, its unbalanced against antags, and it separates players from the rest of the crew. It's a headache and it runs counter to one of the big points of this game (playing with other people, not just your metafriends).
> 
> If you're really looking for equivalent ruin balance tbh just kill the beach biome then. It doesn't get used in the same way that space ruins do but if that's how you want to frame it we'd be better off without it.

Hmm. Maybe if we made it so if it spawns it has a teleporter on that little island next to it, so it's just a teleport away?

**Comment by nullAdept** [comment]
> If you're really looking for equivalent ruin balance tbh just kill the beach biome then. It doesn't get used in the same way that space ruins do but if that's how you want to frame it we'd be better off without it.

the problem with the dome is that it doesn't get used at all! I don't remember the last time I've seen a miner open it up. No one ever spawns as bums because there is nothing to do as them. why does this ruin even exist..

**Comment by RaveRadbury** [comment]
> Hmm. Maybe if we made it so if it spawns it has a teleporter on that little island next to it, so it's just a teleport away?

The teleporter is locked behind command access and it's still a needle in a haystack to figure out if you're target *has* left for space and if they are at the ruin. In this way you're running into Gateway issues, there's a reason that the Gateway is admin only these days.

> the problem with the dome is that it doesn't get used at all! I don't remember the last time I've seen a miner open it up. No one ever spawns as bums because there is nothing to do as them. why does this ruin even exist..

Why then would it be a good idea to make an equivalent in space? We had one, it got disabled. 😕

**Comment by Valorium-RB** [comment]
> > Hmm. Maybe if we made it so if it spawns it has a teleporter on that little island next to it, so it's just a teleport away?
> 
> The teleporter is locked behind command access and it's still a needle in a haystack to figure out if you're target _has_ left for space and if they are at the ruin. In this way you're running into Gateway issues, there's a reason that the Gateway is admin only these days.
> 
> > the problem with the dome is that it doesn't get used at all! I don't remember the last time I've seen a miner open it up. No one ever spawns as bums because there is nothing to do as them. why does this ruin even exist..
> 
> Why then would it be a good idea to make an equivalent in space? We had one, it got disabled. 😕

I edited it to add quantum pad. Sorry for the confusion.

**Comment by nullAdept** [comment]
> Why then would it be a good idea to make an equivalent in space? We had one, it got disabled. 😕

fair point, kill it all

**Comment by EdgeLordExe** [comment]
> 
> 
> > Why then would it be a good idea to make an equivalent in space? We had one, it got disabled. 😕
> 
> fair point, kill it all

yeah thats probably a better idea.

**Comment by nullAdept** [comment]
if you want to play singleplayer papa's bartenderia so much you can just launch your own local server and do that there

**Pull request closed without merging**
