### PR TITLE
Pictures of asses are properly sized now

### PR DESCRIPTION
**Pull request by silicons**
Whoops.

### CODE REVIEW

**Comment by Cw3040** [comment]
of course you need pictures of asses kevinz

**Comment by Tlaltecuhtli** [comment]
did you test this?

**Comment by Anonmare** [comment]
Don't forget to test xeno asses, they have their own unique ass picture

**Comment by PKPenguin321** [comment]
>Don't forget to test xeno asses, they have their own unique ass picture

🤢 🤧

**Comment by Borisvanmemes** [comment]
Is this a real PR or am i in a hellish nightmare?

**Comment by bgobandit** [comment]
that ass too fat

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
