### PR TITLE
Fix missing plural apostrophe

### PR DESCRIPTION
**Pull request by Kole6738**
Patients Rooms
to
Patients' Rooms

### CODE REVIEW

**Comment by Jordie0608** [comment]
I'm pretty sure `Patient's` is correct, the room is possessive of a patient
'Patients' would be if it was a room with multiple patients in it

**Comment by Kole6738** [comment]
If there's multiple rooms, wouldn't a room per patient make more sense, thus saying that there are multiple rooms of patients? Otherwise, would changing it to room make more sense?

**Comment by Jordie0608** [comment]
Ah I didn't see the `rooms`, in that case the correct way would be `patient's room`
`patients' rooms` would be several rooms containing several patients

**Comment by Jordie0608** [comment]
>the correct way would be `patient's room`
>this is not that

tkdrg plz

**Comment by tkdrg** [comment]
But it IS several rooms containing several patients, isn't it?

**Comment by Jordie0608** [comment]
No, these are several rooms for containing single patients, but areas are referred to in single tense: `brig cell`, `head of staff office`, `engineering quarters`
box

meta

**Comment by tkdrg** [comment]
I see. @Kole6738 please fix

**Pull request merged**
