### PR TITLE
nerfs Infective Exo-Locomotion use rate

### PR DESCRIPTION
**Pull request by Elli-Skala**
## About The Pull Request

makes Infective Exo-Locomotion use 5.5 nanites a second instead of 1.5

## Why It's Good For The Game

a single protocol-virus-food replication lets nanites spread 100% of the time (plus the wiki said 5.5 for ages and apparently its been 1.5 for ages also in the code,) and was ment to be a high resource program  

## Changelog
balance: Infective Exo-Locomotion now uses 5.5 nanites per second (up from 1.5)
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
"a single protocol-virus-food replication"
that's cross-departmental cooperation from 3 different departments (viro, cargo, and nanites), plus actually managing to roll the protocols as one of your bepis techs instead of something like rolling tables

**Comment by ATH1909** [comment]
even if you can get this up 24/7, it's still kinda meh. yeah, it has a range of 5 tiles, but it also has its own special snowflake 5 second cooldown between spreads (that your nanites won't account for unless you set up some special programming for them), has a 75% chance to just straight up not even try to infect a given person during one of those procs, AND still has to contend with permeability as yet ANOTHER dice roll it can fail

**Comment by ATH1909** [comment]
also, you wrote this PR on your master branch, which'll cause a headache for you later if you want to do any more coding for /tg/

**Comment by moocowswag** [comment]
I don`t agree with this change but I do think a better argument for you is to bring up how this program is packaged with mitosis and mind control as all 3 of these programs are from alien tech and how you`re nerfing it as a whole.

Mitosis gives a 0.5 - 5.0 extra nanite regen based on nanite volume with the only downside being slight corruption effects that I have yet ever seen desync someone from the cloud and have been able to easily manage just by using rules and restart timers to prevent unwanted triggers and programs becoming nonfunctional.

And mass mind control is self explanatory.

Alien tech is a big power boost to several jobs but I am a firm believer its a boost to nanites the most, only being rivaled in how much it can affect the round by necrotic revival surgery.

**Comment by Elli-Skala** [comment]
maybe you should update the wiki's numbers to follow the code's numbers instead of the code's numbers to follow the wiki's numbers like a dumbass

**Pull request closed without merging**
