### PR TITLE
Added Swollow to the list of Gibberish.

### PR DESCRIPTION
**Pull request by francinum**
OOC: Iteq: just make it a braindamage phrase.

### CODE REVIEW

**Comment by Thunder12345** [comment]
SWOLLOW

**Comment by paprka** [comment]
Epic injoke homies

**Comment by TheVekter** [comment]
:+1: I giggled

**Comment by Miauw62** [comment]
i don't get it
Op 5-jan.-2015 05:31 schreef "TheVekter" <notifications@github.com>:

**Comment by RemieRichards** [comment]
isn't this a player reference? from an old ERP log? *waves policy gun around*

**Comment by dannno** [comment]
:+1:

**Comment by Miauw62** [comment]
5 maintainers and a headcoder dont even know what this is referring to.

**Comment by Cheridan** [comment]
I don't think we should be glorifying ERP logs, sorry. 

A month from now: 
"Lol what's this Swollow meme a reference to?"
"It's a reference to this!: *pastebins ERP log*"

gg

**Comment by paprka** [comment]
pwned

**Pull request closed without merging**
