### PR TITLE
Give kudzu mouse_opacity 2 so clicking them is easier

### PR DESCRIPTION
**Pull request by MrPerson**
Clicking anywhere on a turf not occupied by something else == clicking the kudzu.

### CODE REVIEW

**Comment by WJohn** [comment]
This could also have been handled through giving the empty space in their sprites a tiny bit of super faint alpha, but I guess this works.

**Comment by Lumipharon** [comment]
Nah, person's method is better because you can still click on other shit on the tile.

**Comment by Jalleo** [comment]
Do we still put welders on tables or weaken them?

**Comment by MrPerson** [comment]
mouse_opacity 2 basically makes kudzu fully opaque on its tile(s) for purposes of clicking on it vs clicking things below. So as long as it maintains a higher layer than the table, you shouldn't wind up clicking the table at all.

**Comment by Jalleo** [comment]
Okay best kudzu defence build a table when its grown got it. :+1: love this partial fix. Since nobody would probably do that.

**Pull request merged**
