### PR TITLE
Revert "Adds Nien's HoS formal sprites so they dont look like a Prince s...

### PR DESCRIPTION
**Pull request by ghost**
It broke a ton of things in uniform.dmi because miauw doesn't know how to merge .dmis.

### CODE REVIEW

**Comment by paprka** [comment]
To elaborate: It reverted 
https://github.com/tgstation/-tg-station/pull/6525 and https://github.com/tgstation/-tg-station/pull/6471

**Comment by paprka** [comment]
Now I can't make my clothing set PR because it conflicts too

Damnit miauw

**Comment by Miauw62** [comment]
fuck git, seriously.
not going to do this PR again.

**Comment by Nienhaus** [comment]
Aww

**Comment by Steelpoint** [comment]
I'll do it after my open PR's are finished if you want.

**Pull request merged**
