### PR TITLE
Luxury Shuttle Alternative Version

### PR DESCRIPTION
**Pull request by Bawhoppen**
:cl:
add: Luxury shuttle has been even further adjusted.
/:cl:

This is an alternative proposal to #48395 
It reworks the shuttle to keep the interesting class division, while not being overly intrusive or un-enjoyable for any party. Should also been more in line with the flavor of the game.
New image from Mapdiffbot (ignore sinks): 
image

It should be ready now.

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
"Get out this is MY GARBAGE BIN"

Absolutely on brand for most rounds too. Love the ghetto medbay in the bottom left.

**Comment by Bawhoppen** [comment]
@cacogen If you want to use this map, feel free of course. Otherwise, I'll add your other improvements to this PR as well.

**Comment by Shadowflame909** [comment]
I like it.

**Comment by TheVekter** [comment]
Okay, see, _this_ is better.

**Comment by cacogen** [comment]
I prefer this map in most ways. It's a little messier, but it has a lot more personality. Hopefully it isn't too wide. I'd get the following changes from #48395:

- Makes it so boarding cost is mentioned when luxury shuttle purchase is announced (shuttles.dm, communications.dm)
- Makes it so shuttle names are announced when they arrive as another warning you need to pay for this one (emergency.dm)
- Changes ticket forcewalls to scanner gates, function the same but buzz and turn red when someone can't pass and turn blue when they do (special.dm)
- Fixes runtime where paying with cash and needing change didn't dispense any (special.dm)

**Comment by wesoda25** [comment]
Honestly it should cost more than 10k IMO. For indestructible walls and the sort, plus the whole concept of it, 10k is rather cheap

**Comment by kriskog** [comment]
I personally prefer #48395, but I dont feel that strongly about it. Its merged since it had a bunch of other improvements, but if another maintainer would rather have this one go ahead.

The pool in this one is nice, but I dont like the compartmentalization. One big first class area where everyone is treated the same works better imo.

**Comment by Bawhoppen** [comment]
awesome, I think it's ready

**Comment by Bawhoppen** [comment]
okay maybe now it's actually ready

**Comment by cacogen** [comment]
Oh, it's the same width

**Comment by Bawhoppen** [comment]
@cacogen I made it one longer in the front, but I tested it on Meta atleast and it should be fine I think for the other maps.

Otherwise, everything is ready to go, other than the fact the sinks mess up... though that's kinda outta my control other than removing them.

**Comment by Cyberboss** [comment]
Create an issue for the sinks

**Comment by Bawhoppen** [comment]
@Cyberboss https://github.com/tgstation/tgstation/issues/48450 There you go.

**Comment by Ohagi-Chan** [comment]
All the poor people hear that Luxury Shuttle has been purchased and give a sarcastic cheer.
The poor then shuffle in to the pigsty that reminds them of what the shuttle could have been.

**Comment by Bawhoppen** [comment]
Although I intended to be finished with this version, I decided the silver walls looked fairly out of place, so I made a recolored version of the shuttle walls for the first class section. (Looks like I forgot to commit the actual file itself though.)

**Comment by Bawhoppen** [comment]
Well now the sinks are fixed so it's ready again.

**Comment by actioninja** [comment]
I can already feel the complaints that the old one had more soul

**Pull request merged**
