### PR TITLE
improves emote and suicide restraint checks

### PR DESCRIPTION
**Pull request by zaracka**
:cl:
fix: You can now use certain emotes and the suicide verb while buckled, but not while stunned.
/:cl:

this will allow using emotes, with the restraint check, and the suicide verb while riding vehicles or sitting in chairs (you're not actually restrained), but unable to use them while stunned (you're technically restrained) e.g. clap, salute
improved to_chat messages so there's always feedback and they make sense in all circumstances

### CODE REVIEW

**Comment by BlueNothing** [comment]
That reminds me... as I recall, the empty-handed suicide animation has you bite your own tongue off or something, which... doesn't sound like it needs hands to do in the first place. So why can't it be done cuffed?

**Comment by Iamgoofball** [comment]
It's an old thing from a long forgotten era.

**Comment by Tlaltecuhtli** [comment]
can i flip while on a skate now?

**Comment by zaracka** [comment]
@Tlaltecuhtli yes

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
