### PR TITLE
tgui'ed P.A.C.M.A.N interface + some minor fixes

### PR DESCRIPTION
**Pull request by Menshin**
_Had this literally for years on my hard drive. Thought i would update it to the lastest codebase rather than wiping it. Your call._

* tgui'ed *P.A.C.M.A.N generators interface
* fixed a potential runtime related to soundloop on generators explosion
* fixed being able to connect an unanchored generator to a powernet through node cable laying

Mandatory gif :
tguipacman

:cl: Menshin
tweak: tgui'ed P.A.C.M.A.N generators interface
fix: fixed some bugs related to these generators
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
While I appreciate the work, convering a HTML interface to laggy TGUI is a step back in my opinion.

**Comment by ike709** [comment]
What happened to replacing tgui?

**Comment by optimumtact** [comment]
thank you for the ill-informed comments

**Comment by nicbn** [comment]
You didn't push the compiled tgui

**Comment by zxaber** [comment]
TGUI scales at higher resolutions neatly (as in, text doesn't become fuckhuge with a still-small window), so I appreciate the switch.

**Comment by Menshin** [comment]
Glad to see that tgui is still the hot topic...
Given how ubiquitous it has become, i assumed it was the de facto standard (found no "official" stance on that).
If the PR gets rejected, i can still commit the bugfixes only of course.

> 
> 
> You didn't push the compiled tgui

Though it was part of the build process, fixed. Thanks.

**Comment by 81Denton** [comment]
TGUI is the standard for most interfaces, it scales nicely and looks better. It can just be pretty laggy for clients and has no real documentation.
I don't mean to shit on your hard work, the only thing I dislike is TGUI itself.

**Comment by nicbn** [comment]
We just need some work on TGUI implementation to optimize JavaScript and all, there's no need to replace TGUI or refuse new TGUI work.

**Pull request merged**
