### PR TITLE
smoke wheat erry day

### PR DESCRIPTION
**Pull request by ghost**
adds the smoke trait to meatwheat. Meatwheat is the most useless plant in botany, as it's just...ruined wheat. gaseous decomposition is a trait that has yet to be added to any plant. meat creates gases when it decomposes...why not give meatwheat a little love? botany can already produce smoke easy with phosphorous+sugar+potassium, so the trait, from a balance standpoint, is rather redundant.

Also, holy fuck I can't into git.

### CODE REVIEW

**Comment by jughu** [comment]
1.>upvoting your own PR 👎

2.Sugar+pottasium+phosperous is based on potency so it takes some of your plant strength so a smoke trAit would make that balance useless 👎

3.meatwheat has enough love its MEAT

Because its the way real life is it doesnt have to be in the game itself

**Comment by vcordie** [comment]
jughu, learn to botany. smoke trait is ALREADY in the game and already merged, this just adds it to a plant.

**Comment by jughu** [comment]
Can you read comments?

**Comment by vcordie** [comment]
placing sugar+potassium+phosphours in your plant does work, you're not wrong. It also uses up a ton of the reagent capacity of the plant. The smoke trait is ALREADY IN THE GAME, it WASN'T added to a plant however. This ADDS it to a plant. the smoke trait PERSERVES THE REAGENT CAPACITY of the plant while still allowing you to get the smoke pyrotechnic affect. Whether or not that is OP is outside the scope of this PR however. If you didn't like the smoke trait, you should have commented on the PR that INCLUDED it. this PR merely adds the trait that ALREADY EXISTS to an ALREADY EXISTING PLANT that is widely considered USELESS.

**Comment by jughu** [comment]
Then dont you can simply get it from another plant and add it you lazy fuck 👎👎👎👎

**Comment by vcordie** [comment]
Except you can't. the smoke trait ISN'T ON ANY OTHER PLANTS. it isn't on ANY PLANT.

**Comment by jughu** [comment]
Death nettles

**Comment by ChangelingRain** [comment]
>Whether or not that is OP is outside the scope of this PR however.

Uh, if you're adding something to the game, it's a good idea to at least take a minute to think about what it'll do.

**Comment by jughu** [comment]
Oh wait nvm that was strange seeds

**Comment by jughu** [comment]
Flouro acid smoke tomatoes will affect the game bigly and smoke is a pretty common trait from strange seeds so uh

**Comment by vcordie** [comment]
I'm not adding anything, I'm changing what['s already there. However, you are correct in considering the impact having the smoke trait accessible every round will be. It's not a huge impact, as the smoke pyrotechnic effect is already available via potassium+phosphor+sugar genes, as jughu noted.

**Comment by jughu** [comment]
>im not adding anything

You added smoke trait to meatwheat

**Comment by vcordie** [comment]
meatwheat is not new. smoke trait is not new. I'm not adding anything new.

**Comment by ChangelingRain** [comment]
I'm ending botany buffs forever now. Please nerf botany before adding more buffs to it.

**Pull request closed without merging**
