### PR TITLE
In-hand sprites: transfer tank valve, tracking beacon, pizza box & carp plushie

### LINKED ISSUE #7395: No inhand for space carp plushie.
It urgently needs one.

### LINKED ISSUE #9858: BSRPED doesnt show on the man when in hands
BSRPED doesnt show on the man when in hands

### PR DESCRIPTION
**Pull request by kingofkosmos**
Adds in-hand sprites for:
- Transfer tank valve
  ttv
- Tracking beacon
  beaco
- Pizza box
  pizza
- Carp plushie
  carp

All of these are potentially dangerous items, thus should be recognized if someone is holding them in their hand. If you guys have any more similar things that don't have in-hand sprites, lemme know.

Also makes the bluespace rapid part exchange device use the same in-hand sprite as the normal RPED. Thanks to Nienhaus and WJohnston for the sprites!

Fixes #9858
Fixes #7395

### CODE REVIEW

**Comment by dumpdavidson** [comment]
TTV always showing the same canisters connected is a bit misleading. good sprites tho.

**Comment by RemieRichards** [comment]
Instead of always showing the same canisters, have the TTV's overlay system build them from the canisters it has.

**Comment by Nienhaus** [comment]
Pizza box is my favorite.

**Comment by Dorsisdwarf** [comment]
What exactly makes tracking beacons as dangerous as TTVs? I mean I love the sprites, but that seems a weird statement

**Comment by kingofkosmos** [comment]
Syndicate bombs come in disguised as tracking beacons before they're deployed.

**Comment by Supermichael777** [comment]
tracking beakons are used for 2 illegal items and for teleops

**Comment by Dorsisdwarf** [comment]
Yeah, but the beacons aren't dangerous in themselves (and nobody ever, ever carries a legit one) so it defeats the purpose of a *stealth* item that has a big huge unique inhand sprite making it instantly noticable that you're preparing to make something dangerous happen.

**Comment by Supermichael777** [comment]
press e beacon is now in backpack

**Comment by Dorsisdwarf** [comment]
Cant use it in your backpack checkmate atheists.

Also everyone gets a nice happy message "Jimbones McFuckedNow puts the SUSPICIOUS BACON into his donkco backpack valid him now"

**Comment by kingofkosmos** [comment]
IMO every item should have an in-hand sprite, but I'd rather start from the important ones (from a gameplay perspective).

**Comment by Supermichael777** [comment]
uh the beacon should function if you switched it on the others both drop something obvious that you cant pick up at your feet.

**Comment by CosmicScientist** [comment]
:+1: they all look cute.

**Comment by HankMoodyExperience** [comment]
fix the guitar while you're at it

**Comment by kingofkosmos** [comment]
Oh wow merged already, ok, sorry @RemieRichards I tried to get that code to work but I didn't know how.

**Pull request merged**
