### PR TITLE
Add remove buttons directly to Chem Dispenser

### PR DESCRIPTION
**Pull request by neersighted**
Demo

:cl: neersighted
tweak: Chemistry Dispensers now have a built-in drain!
/:cl:

### CODE REVIEW

**Comment by Anonus** [comment]
Makes chem master 20% less useful.
:+1:

**Comment by Iamgoofball** [comment]
:-1: until a remove 1 unit button is added
:+1: on the other hand

**Comment by PKPenguin321** [comment]
:+1: x :100:

**Comment by Dorsisdwarf** [comment]
:-1: this is what the chem master is for

**Comment by Lumipharon** [comment]
pretty redundant.

**Comment by Zilenan91** [comment]
Can you add this to the bar vendors too?

**Comment by MrStonedOne** [comment]
I think they are a child of the chem dispenser, if so, they would already get this.

**Comment by GunHog** [comment]
Looooooooooooooooooooove it! :+1:

**Comment by MMMiracles** [comment]
its beautiful

:+1:

**Comment by Iamgoofball** [comment]
@Lumipharon @Dorsisdwarf too bad, the age of having to move the beaker just to remove 5u of space lube is over, get used to it

I don't think any chemist would use that old shit method over the new one.

**Comment by AlexCrimson** [comment]
If you added machines that dispensed any chemical instantly, then i doubt people would use the old system to make their own. That doesnt mean the new system belongs in the game. Making jobs a little tedious is what makes them last longer.

**Comment by Iamgoofball** [comment]
did you just try to justify making the game more tedious for the sake of being tedious because you want to "make it last longer"

you make it last longer by giving more stuff to do, not making the existing shit tedious

**Comment by Zilenan91** [comment]
They added back in cryo KOing for some retarded reason too, even though it doesn't add any depth to healing, it just makes it more tedious for everyone involved.

**Comment by Iamgoofball** [comment]
Cryo KO doesn't make it tedious for the doctor treating the guy. Only the patient if he tries to self-serve. You can still get out, anyways.

**Comment by Zilenan91** [comment]
You can't self serve anymore though, someone has to let you in now since the NanoUI conversion fixed the self service bug.

**Comment by AlexCrimson** [comment]
Self-serve was silly, and not getting KOd screwed tator doctors out of a fun gimmick.

and yes, i am justifying making the game more tedious. To a person who would happily reduce jobs down to a few clicks on a machine. Guess im an idiot for trying.

**Comment by Iamgoofball** [comment]
Chemistry is literally "a few clicks on the machine": the job

Don't try ro argue that we're "reducing it to" that, because it already is.

**Comment by AlexCrimson** [comment]
As i said, pointless to argue with you.

**Comment by MrStonedOne** [comment]
no no no, this makes no logic sense.

The chem dispenser is basically a bunch of taps it doesn't have the machinery to be able to separate out chems.

If you gonna change that, you need new sprites, a new name, etc. 

Make these buttons be for the whole beaker not each chem, because how the hell could what is basically a drink fountain be able to separate out chems?

**Comment by Iamgoofball** [comment]
Are you REALLY trying to argue realism over fucking quality of life changes? I expected better of you .

**Comment by MrStonedOne** [comment]
That level of realism is what i liked most about this game....

I dislike things like table crafting because it's not as "real"

**Comment by Fox-McCloud** [comment]
Paradise has this; it's beyond useful.

**Pull request merged**
