### PR TITLE
Makes the data directory configurable

### PR DESCRIPTION
**Pull request by Cyberboss**
- Adds a locked string config: data_directory
- Replaces all instances of the hardcoded "data" with a config reference

:cl:
config: The server's data directory can now be changed from ./data
/:cl:

Conflict in #48446

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Oh god why

**Comment by Jordie0608** [comment]
I don't see this actually getting used.

**Comment by ninjanomnom** [comment]
This is for tgs is my guess @Jordie0608

**Comment by Cyberboss** [comment]
Just if you want data on a separate volume for whatever reason. My main goal for making this was to make the data dir a reference instead of hardcoded everywhere. Completely TGS unrelated.

**Comment by Cyberboss** [comment]
I'd actually like a more robust system that is aware of all files we potentially store in the data directory. Gonna revisit this.

**Pull request closed without merging**
