### PR TITLE
adds fuel trails, revived

### PR DESCRIPTION
**Pull request by tralezab**
## Deja Vu

Puddles pr was created, someone asked to put it in their larger pull request, then they didn't do it and the original pr was long dead by then.

#52172 < old pr, copy pasted some of its contents

## About The Pull Request

Splashing welder fuel on the ground will now leave a puddle. These puddles are flammable and will burn for a decent while, and will ignite nearby puddles in a trail.

[apgaiapapbdfapnbnohornerhe](https://file.house/5qDz.webm)

Also, puddles that have 30u or more of fuel will detonate once ignited the same way an IED would. This halves their fuel capacity so you can't have insane amounts of fuel burning indefinitely.

[iamgcopypasting this gohirb blah blah blah](https://file.house/MKKA.webm)

## Why It's Good For The Game

Now you can have a classic western "tied to a bomb and there's a fuse slowly burning towards you" scenario, or you can be the traitor that creates such a scenario.

After Takua discovered the Kanohi Avohkii, Teridax sent his Rahkshi to find Takua in an effort to prevent him from becoming Takanuva. After all these threats, Mata Nui was badly damaged, and Takanuva rediscovered Metru Nui after Teridax was defeated. The Turaga then proceeded to tell the Matoran and Toa the legends of Metru Nui, and the population of Mata Nui returned to their original home.

After the Matoran had returned to Metru Nui, the Toa Nuva released the Bahrag from their prison so that the Bohrok swarms could resume their task of restoring Mata Nui to its "former state".

When the Great Spirit was finally awoken (with Makuta's mind), he lifted his head and destroyed the island as he rose from his resting place. The remains of the island sank into the ocean depths.

## Changelog
:cl: PKPenguin321
add: Splashing welder fuel on the ground now leaves behind a flammable puddle. Make several of these puddles next to each other and they'll ignite each other, allowing you to create fuses or elaborate traps. Too much fuel in one puddle becomes explosive.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
will resolve conflicts and complete review that wasn't done on last pull request shortly

**Comment by PKPenguin321** [comment]
i had meant to make this instead spawn hotspots that auto-delete after a timer (which is why my original PR staled and died), not really happy with this current implementation and also it did break on me in local testing at least once when igniting many many many tiles as once likely due to an over-reliance on recurring timers

**Comment by wesoda25** [comment]
haha no way a forum post of mine actually accomplished something

**Comment by tralezab** [comment]
yeah, nemvar wanted to use hotspots as well so i must abide

**Comment by LemonInTheDark** [comment]
Timed hotspots might not be the best idea, but you could give them a shot. Where's the rest of the code btw? you only ported the fuel piles.

**Comment by PKPenguin321** [comment]
Seems he nuked the majority of the code trying to fix conflicts

**Comment by tralezab** [comment]
"Where's the rest of the code"
👀

**Comment by LemonInTheDark** [comment]
image

**Comment by SpaceManiac** [comment]
Closing as stale? although your PR description is a mess. Contact a maintainer for reopen.

**Comment by PKPenguin321** [comment]
did anyone ever end up doing this

**Comment by LemonInTheDark** [comment]
no 
:(

**Pull request closed without merging**
