### PR TITLE
We're gonna have a crate time!

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request
Crates have been a controversial topic as of late so I did my best to take the new crates and make them look better than before by simply doing several size changes.

Included are several new crate designs by Zydras who created things like the Trash Cart and Mail Crate in the same style as these crates.

New Crate Sprites
Screenshot 2023-07-02 230404

Zydras Crate Sprites
Screenshot 2023-07-04 101333

Various new Crate Sprites in a Test Session
Screenshot 2023-07-04 100135
## Why It's Good For The Game

Hopefully addresses the mass controversy in the player base by giving players a new crate design that looks better than before (and also takes up 32x32 space as opposed to 32x48)
## Changelog
:cl:
image: Added new Crate Sprites
/:cl:

### CODE REVIEW

**Comment by Byzz2077** [comment]
speed merge this

**Comment by Rex9001** [comment]
Look awesome, but they may look a bit wonky when pulled since they rest at the bottom of the tile. Love the sprite work though!

**Comment by borb197** [comment]
the lid for the open mail crate looks like its floating, i think in general the crates would just look a lot better if they didn't rest at the very bottom of the tile and were moved up just a little bit, i understand this would cause the lid while open to overlap with the tile above but the open mail crate also shows thats not a concern anyway

**Comment by Youtubeboy139** [comment]
> the lid for the open mail crate looks like its floating, probably should to move it up a tiny bit to the right and make it look like its supported by something other than the air below it, i think in general the crates would just look a lot better if they didn't rest at the very bottom of the tile and were moved up just a little bit, i understand this would cause the lid while open to overlap with the tile above but the open mail crate also shows thats not a concern anyway

actually, not really, there is a pixel gap between the lid and the other tile, I think I can fenagle it. As for the mail lid, I have no clue how it works, it's code related.

**Comment by Youtubeboy139** [comment]
> > the lid for the open mail crate looks like its floating, probably should to move it up a tiny bit to the right and make it look like its supported by something other than the air below it, i think in general the crates would just look a lot better if they didn't rest at the very bottom of the tile and were moved up just a little bit, i understand this would cause the lid while open to overlap with the tile above but the open mail crate also shows thats not a concern anyway
> 
> actually, not really, there is a pixel gap between the lid and the other tile, I think I can fenagle it. As for the mail lid, I have no clue how it works, it's code related.

**Comment by Youtubeboy139** [comment]
Screenshot 2023-07-04 122506

**Comment by SgtHunk** [comment]
How do they look on top of a mulebot?

**Comment by Wallemations** [comment]
The open lids look a tad small in comparison to the rest of the sprite. I can't really think of any way to fix that though.

**Comment by Youtubeboy139** [comment]
> The open lids look a tad small in comparison to the rest of the sprite. I can't really think of any way to fix that though.

Screenshot 2023-07-04 153840

They're actually the same size, but because of how it's positioned it looks a bit weird

**Comment by Teleported-Bread** [comment]
Why was this closed?

**Comment by Youtubeboy139** [comment]
> Why was this closed?

Crates are being reworked based on new references, rather than leave this in Draft while I basically redo the whole PR I decided to close it and reopen it later

**Comment by LSommers** [comment]
Hope you plan on coming back to this some day.

**Comment by Youtubeboy139** [comment]
> Hope you plan on coming back to this some day.

I am not. Sorry.

**Pull request closed without merging**
