### PR TITLE
[ready] Disintegrate/Flesh to Stone as actual touch attacks

### PR DESCRIPTION
**Pull request by Incoming5643**
When disintegrate was added it was certainly intended to be a touch attack, but there was no in game mechanics to properly have someone explode when you touched them. But now thanks to things like nodrop and abstract items, I could totally code an item that a wizard summons to his hand that represents a touch attack. So I did.

Disintegrate summons a glowing hand nodrop abstract item. It has a noticeable on mob sprite and (obviously) requires a free hand to use. It removes that shitty drop down menu UI and requires that a wizard be robust enough to actually smack someone with his hand to work. Spell doesn't recharge until the hand actually connects, reusing the spell with the hand out just refunds the charge and puts the hand away. Spell still gibs.

Nerfs:
*Requires a modicum of robustness in clicking a guy
*Offers a tell to spessman that the wizard is going for it
*Can't be used on the floor or while cuffed
*Takes up a hand slot during use

Buffs:
*Don't have to fiddle with a shitty drop down if you use it in a crowded area.

Designed to avoid #10575

https://www.youtube.com/watch?v=ct9fs3ULVIo

### CODE REVIEW

**Comment by bustygoku** [comment]
This should also be the case for mindswap.

Please do this for mindswap.

Stealth mindswapping in public areas is complete shit.

**Comment by AlexanderUlanH** [comment]
Mindswap has an obvious tell in public areas in the form of the incantation.  It's pretty important to mindswap that it be usable while restrained, and without giving people a warning in advance.

**Comment by bustygoku** [comment]
"It's pretty important to mindswap that it be usable while restrained" -- No. It's not a get out of jail free card. It's a 'sneak up on a high rank person' power. It's a disguise ability for apprentices and stealthy wizards.

**Comment by AlexanderUlanH** [comment]
And how are you going to sneak up on a high-rank person with your glowing magic hand?
It exactly is a get out of jail free card for very specific situations.  You're out for 30 seconds, and you have an incantation, so if there was anyone near where you mindswapped, it's suicide.  But if you've been arrested one-on-one, you absolutely should be able to mindswap your way out of that.

**Comment by bustygoku** [comment]
"But if you've been arrested one-on-one" you lose, get over it.

**Comment by Incoming5643** [comment]
regardless of if it's a good idea or not, it's not part of the scope of THIS pull.

**Comment by bustygoku** [comment]
Oh right this is a counter to Miauw's salt PR nevermind.

**Comment by Anonus** [comment]
I like this and the mental image of just punching a nerd and exploding them.

**Comment by Miauw62** [comment]
With this you still have the cancerous ei nath + mm combo, but at least
it's something.
Op 13-jul.-2015 03:43 schreef "Anonus" <notifications@github.com>:

**Comment by Dorsisdwarf** [comment]
Will look at making an abstract icon for these

**Comment by Jalleo** [comment]
Wizard phone home.
Mindswap i am not sure if it should be or not.

**Comment by Steelpoint** [comment]
If your trying to get rid of MM+Ei nath then this won't do that.

I think in most cases this is a positive change since it makes it far easier to target someone in a group of people instead of a drop down menu.

A robust wizard usually uses ei-nath on a stunned target as the coup de grace and not as a aggressively used attack, the fireball falls into the offensive form of attack.

Think of it like the difference between a Spy's Backstab (From TF2) versus the Soldiers Rocket Launcher. The backstab is a situational ability that requires a set up to use while the rocket launcher is general purpose attack. Replace the backstab with ei-nath and the rocket with the fireball though.

**Comment by Dorsisdwarf** [comment]
tod

'Owzat?

**Comment by WJohn** [comment]
Currently working on my own version

**Comment by WJohn** [comment]
Here you go: http://www.mediafire.com/download/87jskuqohec2j1c/Sprites_Request_11.0.4d.rar

It's in magic.dmi

Frankly I'd like it if BOTH this PR and miauw's PR were merged. The annoying parts of disintegrate are both the complete removal from the round AND how easy it is to use. Making both of those less permanent and quite so easy to use while keeping it as the instakill spell would be a lot better in my book.

**Comment by Steelpoint** [comment]
Nice art.

Overall I'm not 100% against these proposed changes, I just am pointing out how this is not really accomplishing what Miauw wants it to accomplish, and is in fact buffing the ability.

**Comment by Dorsisdwarf** [comment]
This isn't really a buff for the ability except in crowds, because you can't use it if you're stunned or cuffed, which is a big negative for combat wizzes

**Comment by Steelpoint** [comment]
Well to be fair that is a actual nerf, which is why I'm not 100% for this as well.

We want the game to be more lethal but we want to remove lethality? 

When I started to play this game years ago one of the first things I learned about watching Wizards was to NEVER walk next to them even if they are stunned, and I disagree with the change that a stunned wizard should lose their offensive capabilities because your goal should not be stunning a wizard but killing them.

A stun should not dilute a wizards potential. 

While some might say I'm exaggerating or being paranoid, but looking at the big picture I want to avoid "small" nerfs and changes to a good antag that reduces its power levels. We let that run rampart with modes like Traitor, Changeling and Cult and we are worser off for it.

**Comment by Nanotransistor** [comment]
Can the wizard touch himself?

**Comment by Incoming5643** [comment]
@Nanotransistor there are special checks to make sure the wizard doesn't explode or get hard if he touch himself.

@WJohn :+1: 

---

There are so many hard counters a wizard has access to for getting stunned:

Magic Missile
Repulse
Blink
Ethereal Jaunt
Teleport
Smoke 
Fireball
Lightning bolt
Mutate (also makes breaking out of cuffs really easy)
The sweet embrace of death (lichmode)

If you have any of those, you're probably fine. The nerf here isn't so much that you're "helpless when stunned" it's that it turns disintregrate into something with an active warning that you can learn to juke away from.

**Comment by Cebasiz** [comment]
this is really nice. it gets rid of the jankiness involved in using the verb from a sidebar and selecting a target.

**Comment by Incoming5643** [comment]
Ayy

**Pull request merged**
