### PR TITLE
Fixes appendicitis magically self-curing

### LINKED ISSUE #10911: Appendicitis can clear up on its own.
Examined a security officer with a 1/3 appendicitis case, and several seconds later without any intervention it cleared up. Could be a bug or it could be intended, I'm not sure.

### PR DESCRIPTION
**Pull request by PatchouliKnowledge**
Fixes #10911

### CODE REVIEW

**Comment by Aranclanos** [comment]
what causes the bug?

**Comment by PatchouliKnowledge** [comment]
It's caused by the cure checks in the stage_act() proc of _disease.dm

They work for everything else, but appendicitis is unique in that it can't be cured through 'normal' means and only by surgery, so I just made it stop calling ..() and left only the stuff that's necessary for it to advance stages.

**Comment by Aranclanos** [comment]
but why the stage_act() parent heals it?

**Comment by PatchouliKnowledge** [comment]
Not sure actually. My guess is that appendicitis somehow has the CURABLE flag, which is the only thing that can trigger cure() in the parent proc. But it's not flagged as such in appendicitis.dm.

It is a mystery.

**Comment by Aranclanos** [comment]
>//Disease Flags
>#define CURABLE		1
>#define CAN_CARRY	2
>#define CAN_RESIST	3

the flags are fucked, the bug is there. set can_resist to 4

**Comment by PatchouliKnowledge** [comment]
That works. Sneaky.

**Comment by Supermichael777** [comment]
Appendicitis can be caused by diseases regardless of the presence of an appendix. Could you make it so it auto cures if no appendix is detected?

**Comment by PatchouliKnowledge** [comment]
@Supermichael777 Appendicitis can only be caused by the 'Spontaneous appendicitis' random/admin event, and only in humans. And there's already safety nets for that, you get antibodies for appendicitis if it was already cured by appendix removal once, just like with any other disease.

**Comment by lordpidey** [comment]
@PatchouliKnowledge , but I like to randomly remove people's appendix.  Shouldn't that make them immune?

**Comment by PatchouliKnowledge** [comment]
After some testing, apparently the spontaneous appendicitis event called the wrong disease proc, forcing appendicitis past all the checks, sigh. Fixed that too.

**Pull request merged**
