### PR TITLE
Gives our engineers more love by adding black gloves to their closets so they be no longer why cant insulated gloves touch lightning?

### PR DESCRIPTION
**Pull request by jughu**
we must

:cl: optional name here
add: Adds black gloves to engineering locker
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)to fix lights when somoene stole the thingy...

### CODE REVIEW

**Comment by ma44** [comment]
What

**Comment by Arianya** [comment]
OOC: FishoftheDerp: did that guy have a downs attack writing that pr

**Comment by jughu** [comment]
yes

**Comment by Firecage** [comment]
Why not just make insulated gloves able to safely remove lights?

**Comment by jughu** [comment]
then why does the ce start with blackgloves and would make combat gloves useless :thinking:

**Comment by vcordie** [comment]
who gives a shit about combat gloves. they're basically just supposed to be insulated variant anyways

**Comment by Haevacht** [comment]
You can build a light and insert a tube without black gloves, smash it with a crowbar if you have to remove it.

**Pull request closed without merging**
