### PR TITLE
Nerfs HoP's access

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Removes HoP's access to security office.
Removes HoP's mech access entirely (except mining)

## Why It's Good For The Game

HoP already has a TON of access for what their job is about, managing job changes and service/cargo. There's no reason why they would need such things as access to mechs, science, medical, ect. But for now, I just want to focus on removing Security Office:

HoP, on all maps, has a gun recharger in their office, and they will still remain access to departmental offices, so security office access is irrelevant for charging their gun. I personally don't think that HoP, a non-sec role, should have aceess to security lockers. They are a Service/Cargo job, they shouldn't have access to just walk in and take SecHUDs.

If HoP really needs access to security office, they can give themselves the access, but thanks to ID trimming, that cost isn't free anymore. _**Though it technically is, because they only need to give themselves 1 access edit, which isn't gonna affect a Silver ID, so I personally think they should have more access removed but that's not the point right now.**_

## Changelog

:cl:
balance: the Head of Personnel no longer has access to Security Office nor Mechs (outside of mining ones).
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
HoP is already quite toothless compared to the CE and RD in terms of toys they get to play with. I don't really see the need for this.

**Comment by Pickle-Coding** [comment]
The HoP's toys are their dog, gun, and a lot of paper they should be using. They don't need security office and AI upload access, as it's not relevant to their job.

**Comment by ATH1909** [comment]
> The HoP's toys are their dog, gun, and a lot of paper they should be using. They don't need security office and AI upload access, as it's not relevant to their job. That's just unnecessary powercreep.

They're often deputies to (/secondary) captains, though.

**Comment by Farquaar** [comment]
> The HoP's toys are their dog, gun, and a lot of paper they should be using. They don't need security office and AI upload access, as it's not relevant to their job. That's just unnecessary powercreep.

Heads of Staff should get perks as a reward for taking on additional responsibility. It's not powercreep, but a justified reward.

**Comment by Pickle-Coding** [comment]
A reward or perk should benefit them for doing their job, not just what they could do if they get antag (why did HoP get upload access in the first place?).

**Comment by CRITAWAKETS** [comment]
i mean you can just

give yourself the access

**Comment by JohnFulpWillard** [comment]
> i mean you can just
> 
> give yourself the access

Being able to give yourself access shouldn't be enough reason for them to start with it. Otherwise why not just give HoP AA? Or even just armory?

**Comment by GuillaumePrata** [comment]
> Heads of Staff get perks as a reward for taking on additional responsibility. It's not powercreep, but basic game balance and player incentives.

While I understand this logic, HoP is the only Head of Staff that a slice of people play because of their core RP gameplay of giving access and not because they are Cargo Tech+ like people that play CE only for the no slips + access and then just act like a normal engineer.

So even if we go deeper into removing HoP power people will still play it because it is the only Head of Staff that actually has their unique core gameplay that is enjoyable.

**Comment by optimumtact** [comment]
Security office sure, who cares

AI upload, no, HoP is one of the people who is expected to change AI laws.

**Comment by ATH1909** [comment]
> Security office sure, who cares
> 
> AI upload, no, HoP is one of the people who is expected to change AI laws.

I thought only the (acting) cap and the RD had law changing meta protections? I could be wrong, though.

**Comment by SuperNovaa41** [comment]
> > Security office sure, who cares
> > AI upload, no, HoP is one of the people who is expected to change AI laws.
> 
> I thought only the (acting) cap and the RD had law changing meta protections? I could be wrong, though.

Sort of? It's on the rules wiki page but it's super vague, and is probably inferring that anyone who has roundstart access has the meta protections 
unknown

**Comment by JohnFulpWillard** [comment]
> Security office sure, who cares
> 
> AI upload, no, HoP is one of the people who is expected to change AI laws.

It should primarily be the RD's job to change laws, with the Captain also able to. HoP overriding that doing their own thing seems dumb since RD is the one with all the robotics things, Captain obviously being the Cap, but HoP is just a regular head of service/cargo.
I could change it if needed, but I don't see reason for the HoP to have access to the upload.

**Comment by optimumtact** [comment]
It wasn't a debate.

**Comment by NanoCats** [comment]
The HOP becomes the most boring pisswilly job imaginable after the two people who need access changes because they were traitors who selected "join random job if preference unavailable" option have gotten them, let the man have some fun.  This change is lame and unnecessary.

**Comment by JohnFulpWillard** [comment]
> The HOP becomes the most boring pisswilly job imaginable after the two people who need job changes because they were traitors who selected "join random job if preference unavailable" option have gotten them, let the man have some fun. This change is lame and unnecessary.

Well they have 2 whole departments they can manage, I don’t see how the only “fun” a HoP can have is the ability to roundstart to take sechuds and a stunbaton.

**Comment by admeeer** [comment]
> > The HOP becomes the most boring pisswilly job imaginable after the two people who need job changes because they were traitors who selected "join random job if preference unavailable" option have gotten them, let the man have some fun. This change is lame and unnecessary.
> 
> Well they have 2 whole departments they can manage, I don’t see how the only “fun” a HoP can have is the ability to roundstart to take sechuds and a stunbaton.

Two WHOLE departments? You mean cargo which has a quartermaster and service, the department that acts like a department but-isn't-really a department?

**Comment by NanoCats** [comment]
> > The HOP becomes the most boring pisswilly job imaginable after the two people who need job changes because they were traitors who selected "join random job if preference unavailable" option have gotten them, let the man have some fun. This change is lame and unnecessary.
> 
> Well they have 2 whole departments they can manage, I don’t see how the only “fun” a HoP can have is the ability to roundstart to take sechuds and a stunbaton.

Admeer said it better but Cargo will tell you to fuck off and potentially beat you up if you press it beyond that, Service is like trying to herd butterflies meanwhile, you could maybe do it, but not much is going to come of it regardless of how compliant they are.

**Comment by JohnFulpWillard** [comment]
> 

So much this

**Comment by admeeer** [comment]
> > 
> 
> So much this

average lizard player mindset

**Comment by NanoCats** [comment]
> 

I report bugs, go fulp yourself

**Pull request merged**
