### PR TITLE
Fixed auto-set nuke code on blob being a number instead of a string.

### PR DESCRIPTION
**Pull request by Cruix**
This bug has existed since September of 2014, how has it not been fixed yet?

### CODE REVIEW

**Comment by GunHog** [comment]
Because it almost never happens!

**Comment by coiax** [comment]
I actually just replaced this with a random_nukecode() proc that also generates numbers below 10000 (with appropriate zero padding).

**Comment by coiax** [comment]
Yeah, this will clash with #19207

**Comment by Cruix** [comment]
Closing it then.

**Pull request closed without merging**
