### PR TITLE
Animated speechie bubbles

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Adds an animation to most basic speech bubbles. It usually only effects the basic type of bubble. The dots usually appear one after the other in succession.

The slime bubbles have gained a dripping slime effect, shouldn't create too much visual noise.

Swarmers and clock cult bubbles also look more fancy now.

Biggest change is that lawyer objection!! bubble now shakes all over the place, drawing loads of attention.

## Why It's Good For The Game

Player interaction is the core of this game. The small act of animating speech bubbles may encourage people to interact more with each other, since they will catch more attention of the player than a static image.

If the moving dots prove too noisy, I can always just reduce this to the swarmer/clockcult/slime parts.

## Changelog
:cl:
imageadd: Animated speech bubbles.
/:cl:

### CODE REVIEW

**Comment by nicbn** [comment]
Should appear while a player is writing, and then keep static (I think they do it in baystation)

**Comment by ATH1909** [comment]
> Should appear while a player is writing, and then keep static (I think they do it in baystation)

But what if you've pre-typed something and are keeping it in a text box on the side of your screen? I sometimes queue up *deathgasp as a borg so I can pop it after I've been flashed and hit a few times without needing to worry about properly spelling it, etc.

**Comment by zxaber** [comment]
Yeah, I'm not sure about having the bubbles_while_ typing.

Extry visual fluff is cool, otherwise.

**Comment by SkeletalElite** [comment]
Yeah don't make it while typing, makes it easier to try and kill someone by baiting them into talking and then killing them while typing since itll slow their reaction. At least right now you have to predict when theyre typing to do that.

**Comment by Fikou** [comment]
you fucked up the slime one

**Comment by nemvar** [comment]
That's just icon diff being fucky. They all also look darker because icon diff doesn't show alpha correctly on animated icons. The more you know.

**Comment by SpaceManiac** [comment]
> Should appear while a player is writing, and then keep static (I think they do it in baystation)

There are arguments for and against this but either way such a change would belong in a separate PR

**Review by SpaceManiac — APPROVED** [review]
checked 'em in DreamMaker, looks fine; diff bot is known to sometimes be off: https://github.com/tgstation/IconDiffBot/issues/42

**Pull request merged**
