### PR TITLE
Birdshot Engineering Retrofitting

### LINKED ISSUE #75590: Birdshot: huge atmospherics problem
I'm sorry in advance - not a Discord person, neither a native speaker. Quality of the "KiloStation" was discussable, but it was way more refined than "Birdshot" on its release.

## Actual problems
There's also no proper enterance to **engine** part of **ENGINEERING DEPARTMENT** causing **engineers** to constantly pass throuh atmospherics, engine room is too small for interesting SM setups and etc. **BUT** that are the themes for another discussion. 

~~First of all, there is no exit to space inside main atmospherics room. At least some of my setups used mixing chamber and space to produce BZ and having an exit right next to it was neat.~~

<details>
<summary>Pipes are stacked on top of each other, some of them are hidden, some are placed under the cooler causing it to bug out.</summary>

(the right one)
dreamseeker_1Hr6oR1Sx4

(the left one) (can't unwrench)
dreamseeker_ylyqK7XRDU
dreamseeker_viT6XPWucD
dreamseeker_p7HtbCp9av

</details>

<details>
<summary>Cringey waste loop going through the entire atmo. Also it's impossible to dump waste gases in to space at the roundstart because main gas sorting loop is contaminated with non-sorted gases from the beginning and directly conected to scrubbers loop.</summary>

screenshot5

</details>

<details>
<summary>No space for gas-producing setups. Players are forced to disassemble pipe networks inside waste sorting loop to get some free space.</summary>

screenshot1

</details>

<details>
<summary>Turbine scrubber is scrubbing gas into the main waste loop. That's just hilarious.</summary>

screenshot2

</details>

UPD: turbine placement cuts off almost all the space and non-space based setups because there's no room for cooling loop and thermomcahines.

<details>
<summary>No N2O and CO2 tanks. Author decided that two pressure tanks and some horrible abandoned room is better than two normal-sized gas tanks.</summary>

screenshot3

</details>

<details>
<summary>No layer adapters on gas tanks exits.</summary>

dreamseeker_5vF6K926w4

</details>

<details>
<summary>HFR is in space and designated area is too small. No lights on the platform, no power outside of it.</summary>

dreamseeker_eyJfq25XH9

</details>

## Summary
Redo ~~this piece of garbage~~ engineering, **PLEASE**.

### PR DESCRIPTION
**Pull request by Zytolg**
Warning: Nanotrasen Confidential Proprietary Information (NCPI) must only be accessed and viewed within a Nanotrasen Virtual Environment (NVE, vNTOS-3). Employees in violation of this information ordnance will have their wages A) garnished, and B) sent to a labour camp up to a maximum of ten (10y) years. Questions regarding policies related to NCPI should be directed towards departmental heads or your sector Central Command Information Authority (CCIA) personnel. 

## About The Pull Request

Credentials Confirmed
The Birdshot Engineering Revitalization Plan (formerly proposal Blindfold, now BERP) is a procurement effort to address growing maintenance liabilities and costs on the Skitter-MDR Class Orbital Station located in the Spinward Stellar Cluster (SSC, Sector 28-7b). Over the course of the previous year, ongoing analysis data has provided vital feedback since the station was once again brought into operation after 17 years of abandonment; and using this data, 4 options were outlined for the Blindfold Proposal. 
1) Abandonment - No Cost. Operations on Birdshot will cease. 28-7b operations will be moderately impacted. 
2) Procurement - Medium Cost. Replace offending station sections completely with low-cost, working alternatives. Operational gains in 28-7b expected.
3) Do Nothing - No Cost. Moderate long-term impacts to operations in 28-7b.
4) >>>_Was removed_

Option 2 was selected for BERP. Procurement efforts identified 3 solutions and later narrowed it down to 1. Following the selection process architects were brought in to draft up low-impact refits to the designated hulk. 5 selections made it past initial drafting, with 3 ultimately being selected for engineering board review. Penultimately draft proposal 3 was selected for the project and now awaits engineering certification. The draft plan is provided on the next page:

Birdshot Eng Final

Following board certification, implementation of the plan will be commenced by 28-7b Nanotrasen Enigneering Corps. (NECs). Construction time-frame pending Project Foremans review.

## Why It's Good For The Game

Birdshot Engineering is where this whole station began. Back then, things were going to look closer to Birdboat Station, but that became looser and more ill-defined as progress was made on the overall station. While I was satisfied of the decrepit feel of Birdshot Enigneering initially, I knew that at some point, it would require modification to better play into Birdshots strengths. 

I've had a long laundry list of a roadmap that I've wanted to implement since the station was added, and this was the top item. Tier Zero. Problema Numero Uno. You get the idea. This has been a year of drafting, redrafting, and redrafting everything until it fit Birdshot right. With this, we're nearly there. I see this being the definitive Engineering Department for this station for quite some time to come. However, this is still a draft and some elements are subject to change as I begin to work out some of the more minor kinks in the draft such as pipe locations and transit tubes. 

Presently Atmospherics is completely rebuilt from the bottom up. There is more space, enough to do projects, but you'll have to tear down some windows and walls to gain it. Nothing ventured, nothing gained. You also have most of the gas distro line outside. I'm a firm believer in enabling whatever antics ANY lunatic may have. Atmos techs can rest assured that outside lines are completely reconfigurable (and powered) enabling some... unique project prospects. You also gained an inside HFR and Spare burn chamber. Enjoy. 

The Engineering Common Areas are now inside the department proper instead of the satellite treatment in the original implementation. Security gets an actual outpost and engineers now have a proper office to file engineering documentation. They say that office colleagues can form tight bonds so let's see whose is stronger: Purples or Yellows?

The Supermatter Engine is more of an upgrade over the previous model (Leaky SM is here to stay so deal with it). The room is larger with less rock, allowing some manner of greater customization, but I believe engineers will be more than happy to find that they now have a Burn Chamber of their own. I have zero clue of what they'll do with it, but I think any enterprising CE will be able to create something that even god should fear. 

Finally we have maint improvements. Nothing really to see here though maybe there's the beginning of something for the future if you care to speculate. I couldn't really keep the meandering maint of the previous rock, so instead we now have some pseudo dead-ends. It's all connected by transit tubes to the north (not shown) so you can slowly get around if you will it. Of course there's plenty of cut-throughs, not-so-finished sections, and opportunity for those who need it. Caution to the blind, this whole rock is spicy. 

Overall I'm happy with this and want to open it up in Draft Mode for initial thoughts. I have a rough timeline on finishing this that stretches out to the weekend, so the earlier comments are, the more likely I'll be able to MAYBE do something about it. Thanks for the patience and hopefully this is a doozy of an update for all our players. 

Previous Engineering Provided for Point of Reference:

Screenshot 2024-03-04 190827

closes  #75590

## Changelog
:cl:
qol: Wholesale Revamp of Birdshots Engineering Department
fix: Some Birdshot Amtospherics Concerns
fix: Some Birdshot Engine Concerns
/:cl:

### CODE REVIEW

**Comment by AviiCinders** [comment]
Birdshot haters coping and seething right now

**Comment by Zytolg** [comment]
This version of Birdshot Eng is now playtestable.

**Review by MrMelbert — COMMENTED** [review]
image

Why use mining turfs as a wall into a security outpost? Especially when you put pickaxes IN maintenance?

**Review by MrMelbert — COMMENTED** [review]
image

This should be a passive vent

**Review by MrMelbert — COMMENTED** [review]
image

Also this area, I'm not keen on essentially allowing free access into the engi lathe area via to anyone with maint access

**Review by Maurukas — CHANGES_REQUESTED** [review]
I really like this engine.

Fixes:
<details>
<summary> Pipe loop in the lower half of atmos </summary>

image

</details>
<details>
<summary> These layer adapters should be the visible subtype</summary>
It is not obvious that the upper two distribution pipes are linked together. 
A pump is also needs a label.

image
image
image

</details>
<details>
<summary>Missed asteroid turfs in the engine room</summary>
These spots don't look intentional

image

image

</details>


<details>
<summary>Electrified grille in maint:</summary>

image

</details>
<details>
<summary>This terminal should be an engineering preset and have a power cable underneath it so it can read the power grid.</summary>

image
</details>
<details>
<summary>These three reflectors are not anchored. Is this intentional?</summary>

image

</details>

* There are 0 mapped in insulated gloves on the station. Please add some.

Suggestions:
* The engine could use additional pressure meters, especially on the blue, green and orange pipes. As it stands only two pipes have meters, and this will make diagnosing engine issues much more difficult.
* Atmos internal piping could use additional meters to make it clear what the status of each pipe is at any time.  
* There is a total of 1 pipe dispenser mapped into the entire engineering section (other than the atmos job lockers), and it is in an unmarked crate in atmos. I think that adding at least one RPD near the engine, somewhere visible is a good idea.
* You have anchored tesla coils in the emitter area. Is this intentional? The emitters themselves are not welded.
<details>
<summary>This SMES may be very difficult to use without creating a power loop.</summary>

image

</details>
<details>
<summary> This door is barricaded. Intentional? Usually doors would be marked abandoned.</summary>

image

</details>

**Comment by Zytolg** [comment]
Changes made along w/ detailing pass. Engineers can now expect to find insuls and more throughout the department. Atmos has gained access to a more accommodating amount of RPD tools to fuel their ambition. Added books.

**Comment by Zytolg** [comment]
Oh yeah, I think it's work noting that as of this rework, there's no way to reduce trash. Incinerator could/would ash-ify most of it but we no longer loop through there. I'll put a proper refusal room in at some point down the line, but probably not before I've shuffled around some more departments.

Important: **Anyone who takes up this task because they want to or for whatever reason have to, use the section that runs through Science->CMD Maint->AI Maint->Eng Maint->N Cargo Maint.** This is the return section and anything before it is still collecting trash.

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
