### PR TITLE
Flesh Spiders Regenerate + QoL

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Replaces the Healing Touch component on Changeling-spawned Flesh Spiders with the Regenerator component, as the comment helpfully suggests.
Flesh Spiders can no longer touch themselves to heal, instead they automatically begin regenerating their health if they go four seconds without taking damage. It takes 6 seconds to fully regenerate, so 10 seconds to fully heal from the edge of death (less if you're not that injured).

image

Also I changed the sprite for flesh spider eggs to a different one we already had rather than regular spider eggs tinted red, just because I felt like it.
Would be cool to give the spiders their own sprite some time, but that's for another PR.

image
_Additionally_ the flavour text for flesh spiders was kind of messed up by being shoved into the objectives box and claiming that it was a directive from a spider queen you don't have, so I gave them their own slightly different antag datum to compensate.
It also actually mentions how you heal yourself, which previously was down to trial and error or codediving.

In the course of doing this I decided to just... move flesh spiders to their own type path. It _sort of_ made sense for them to be part of the giant spider typepath, but they keep being modified by changes targetted at "balancing the Giant Spiders antagonist" which this mob isn't related to and doesn't have any reason to follow. The fact that a mob has similar stats to another one isn't automatically a reason to share a typepath, and now that I have looked a little at this mob I'm sort of interested in branching it further away from "it's a spider mob but spawned a different way" in the future.

Finally, this spider egg cluster and the midwife one would prompt ghosts with a radial menu with a single option on it... that's a bit pointless, so we'll bypass that menu if there is only one possible outcome. 

## Why It's Good For The Game

Currently Flesh Spiders heal by clicking on themselves and standing still for two seconds, restoring 50% of their HP. This means they can fully regenerate over 4 seconds unless you stun them, and with 90 HP you're not _that_ likely to kill one during the channel time.
This just feels like an odd way for the creature to operate, regenerating instead gives it a hit-and-run strategy and adds more use to their webs (maybe we should give them meatier or bloody webs at some point? Might be cool).
Also clicking yourself to heal is just unintuitive and I suspect several players just didn't realise they could do it in the first place.

## Changelog

:cl:
balance: Flesh Spiders heal automatically over time if they go a short time without taking damage, instead of healing large chunks by clicking themselves and waiting two seconds.
qol: Spider egg clusters which only hatch into one kind of spider don't ask you to select that one type from a radial menu with one option on it.
qol: As a Flesh Spider, the game now tells you how you can heal yourself.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
<3

**Comment by Striders13** [comment]
they're not that good at hit and run though, since they can't outrun anyone and can't ventcrawl, so it's not really possible to escape a dude who wants to kill you.

**Comment by Jacquerel** [comment]
> they're not that good at hit and run though, since they can't outrun anyone and can't ventcrawl, so it's not really possible to escape a dude who wants to kill you.

If only they had some way to slow and impede the passage of others

**Comment by Striders13** [comment]
> > they're not that good at hit and run though, since they can't outrun anyone and can't ventcrawl, so it's not really possible to escape a dude who wants to kill you.
> 
> If only they had some way to slow and impede the passage of others

u right I forgot webs existed

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
