### PR TITLE
You can now smite ahelpers

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by RandomMarine** [comment]
YOU CAN'T SMITE ME WHEN I'M A GHOST

**Comment by Cyberboss** [comment]
var edit -> key = null

**Comment by Xhuis** [comment]
\>tell Cyber that we have a smite proc 
\>this PR shows up right after

Yay, I did a thing!

**Comment by bgobandit** [comment]
enh I kind of don't like this, it puts IC consequences in an OOC action

**Comment by Cyberboss** [comment]
>HELP: **********/(Johnathan Talist) (?) (PP) (VV) (SM) (FLW) (TP) (REJT) (IC): OwO whats this, any badmins around?

**Comment by ExcessiveUseOfCobblestone** [comment]
can you just toss this in the player menu somewhere instead of ahelps? Thanks :3

**Comment by dannno** [comment]
yeah I want to smite people who haven't ahelped or prayed please

**Comment by ExcessiveUseOfCobblestone** [comment]
cough cough jarektheraptor and repukan ;-)

**Comment by Robustin** [comment]
This is just begging for abuse, make it indecent of the a help function.

**Pull request merged**
