### PR TITLE
Update the traitor PDA

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: OSCAR MIKE
add: CONTACT ON THE LEFT SIDE!
/:cl:

It feels a bit more tacticool.

### CODE REVIEW

**Comment by yackemflam** [comment]
ARE YOU
SHITTING ME?

**Comment by GunHog** [comment]
Even though this change is small, typos can break your code. You should compile your code locally whenever this is a possibility. The Github onsite editor is NOT your friend if you are a new coder.

**Comment by Cheridan** [comment]
One time I found a PDA lying on the floor in the hall and I picked it up and put in a random code as a joke in case someone messaged it and it unlocked an uplink

**Comment by RemieRichards** [comment]
23,374 combinations now, up from 3,596 (still 899 possible numbers, but gone from 4 possible words to 26 possible)

**Pull request merged**
