### PR TITLE
[READY]Adds moodlets to appropriate drugs and drug-like reagents

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

This pull request adds moodies to a few drugs that lack them. So far i have given krokodi and fentanyl the new "narcotic_heavy" moodlet and morphine has been given the "narcotic_medium" moodlet.

Crank and meth have been given stimulant_medium and bathsalts have been given stimulant_heavy.

The fentanyl and morphine moodlets are delayed a few ticks as to not hinder drugging so much.

## Why It's Good For The Game

Upon information and belief, it is clear to me that these drugs feel pretty good to take, otherwise the Russians wouldn't risk their lives for a shot of krokodil.
The game should reflect that through appropriate moodlets, this also gives a very minor upside to the cool but useless krokodil.

## Changelog
:cl:
add: Moodlets have been added to krokodil, fentanyl, morphine, crank, meth and bathsalts.
/:cl:

### CODE REVIEW

**Comment by Krysonism** [comment]
I will consider adding a meth & crank moodlet as well.

**Comment by ATH1909** [comment]
> Upon information and belief, it is clear to me that these drugs feel pretty good to take, otherwise the Russians wouldn't risk their lives for a shot of krokodil.

Does a substance have to feel pretty good to take to be addictive? I thought that there are some drugs out there that taste awful/feel disgusting to use, but are still really addictive.

**Comment by PKPenguin321** [comment]
1/50 chance for your character to be predisposed to narcotic-induced anxiety that causes your character to instead get the absolute worst moodlet in the game

**Comment by TerraGS** [comment]
I imagine the bathsalt moodlet reading like someone having a stroke

**Comment by wesoda25** [comment]
Add a moodset for literally all drugs that make sense to have a moodlet, stuff like meth would _obviously_ make sense to have one.

**Comment by Krysonism** [comment]
I will be leaving for vacation in Germany for a week so i might not be able to make any edits until next week.

**Pull request merged**
