### PR TITLE
Buy my mixtape!

### PR DESCRIPTION
**Pull request by fuckdapoliceandadmins**
pls and thank you

### CODE REVIEW

**Comment by Iamgoofball** [comment]
comin' straight from the underground

**Comment by ChangelingRain** [comment]
goof get out

**Comment by Iamgoofball** [comment]
wasnt me this time

**Comment by Archie700** [comment]
CAN WE STOP IT WITH THE MEME PRS OH GOD

**Comment by PKPenguin321** [comment]
hahaha what the fuck

**Pull request closed without merging**
