### PR TITLE
Infiltrator Revisit: Be MILD and Introduce Sane QOL changes for punchies and the suit at 5am

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request (This is so fucking long I'm so sorry)

**Infiltrator Suit changes:**
Infiltrator suits now entirely fit in their special carrying case.

There no longer is a blood-red sneaksuit as a jumpsuit. Instead, the suit has been combined with the vest. It now has the full armor (this matches a blood-red hardsuit at 8 TC/syndicate spacesuit at 4 TC, as it did previously, but spread out over the arms/legs now). 

The jumpsuit has been replaced with a tactical turtleneck. This is in part to combat the invisible armor that the suit had from the jumpsuit level. (I acknowledge that the turtleneck has 10 melee armor as well, but so does a security jumpsuit, and a part of a wider issue, it just seems fitting and if anyone particularly takes issue with the jumpsuit, I'll just make it tacticool, easy peezy.)

The balaclava no longer has armor and the armor has been moved into the helmet. This helmet matches the suit. This wasn't always the case, and the suit/helmet had different values when I originally made the suit, but @Fikou is particularly big on this consistency and changed it down the line. You are also no longer spammed with the removal text when you move the mask around your inventory.

The infiltrator gloves are no longer nitrile glove subtypes, as the fireman carry trait is likely set for becoming a skillchip in the near future, and having an item that effectively _is a skillchip but isn't_ would be somewhat weird for antagonist gear. Especially since chameleon skillchips exist to fill this niche as well.

They instead now do three things; 
A) They make your punches consistently land without rng miss chance but prevent you from getting a critical hit knockdown _consistency often trumps potential, exile_

B) They make you do maximum punch damage (for humans, that is 10 of their species damage and 15 stamina, and 15 damage and 20 stamina for kicks ~~yes this is a kicking buff~~)

C) Let you either do Brute damage instead of your species damage (somewhat useful on ethereals) or purely Stamina damage.

**Not Infiltrator Suit changes AKA what is atomization?:**
Tidies up how punching damage is handled by having a species side damage calculation proc that works out most of the important parts of punchies. 

Separates the critical punch roll from the actual rolled damage so we can allow for damage multiplications without impacting crit chance, and also allow for people to get a crit even if they roll 1 damage. This same roll determines if we roll to miss.

Allows support for pure stamina damage attacks instead of just, potentially, having stamina damage being doubled up and multiplied by 1/4th if you did actually set their damage to Stamina.

Changes multipliers into flat bonuses. These flat bonuses are roughly equivalent to what most species would otherwise get from the old multipliers. (There is a very real buff to kicking here for human-equivalents, mind you, in that kicks apply a +5 and this will be dealt as stamina damage as well, where previously they didn't. I'll clarify in the Why It's Good For The Game below) (This is also a nerf to most species hitting the extreme levels for punch damage, but not by much, maybe about one or two points.)

To prevent this getting too out of hand for species that should be on the weaker end of punching prowess, a new trait, Terrible Puncher, prevents those species from getting damage bonuses. This applies to bananium golems (who basically couldn't benefit from the multipliers previously anyway but now actually can hit people for a pathetically tiny 1-2 stamina damage) and monkeys (who I don't really know if they actually use the normal harm proc so iunno? Better safe than sorry?)

Replaces the utterly baffling check for attack verbs (????) to determine a damage multiplier to whether the target is prone or not. _I get it, it's meant to be that you're kicking them, but come on there were better ways to do this even at the time, surely, and was this really necessary?_

The stun punch now checks for whether our target is prone or not, instead of whether or not they're...dead? I doubt this will really matter.

## Why It's Good For The Game (This isn't as long, you don't have to read this)

The Infiltrator kit needed some touch ups, and I was aware the gloves in their current state probably weren't going to be usable going forward with the skillchip changes. Hopefully some gloves that make you punch real hard might be an interesting niche for the gloves to fill ~~and the beginning of dismantling martial arts into a system that isn't terrible by making the base harm proc a little more versatile?~~

~~Boxing can be handled with components and the changes present in this PR.~~

Punching is fun. What isn't fun? Being unable to stamcrit people with punches, forcing lethal attacks.

Stamina damage in punch fights was meaningless because most of the time, you are going to either be missing or kicking. This at least allows you to stamina crit someone to conclude a fight with kicks _without_ necessarily putting them into lethal crit. 

You couldn't do this before, because punching will inevitably cause you to knock them on their ass, forcing them to take solely lethal damage from your attacks from there on out.

Also, it's impossible at a certain point for a pair of punchers to land a hit, so punching was kind of hilariously ineffective EXCEPT when you could kick, which would result in it being all the time as your kick damage spiked you past your stun threshold. 

Sorta takes the wind out of your sails when you can't punch other assistants while covered in your own blood, so punch fights are mostly just a series of misses until one side gives up and leaves or shoves and finishes the other guy off with kicks.

There is a **_spicy_** version of this PR. If you want it.

Shout out to @Hatterhat who gave me some idea of how better to deal with stuff like the masks equip/drop procs. since those suck ass.

## Changelog
:cl:
fix: Revisits the Infiltrator Kit, improving some of it's functionality and long standing bugs.
tweak: Replaces the Infiltrator gloves from nitrile gloves to special punching gloves. Switches between brute and stamina! Not a martial art! You swap modes using Alt-Click!
balance: Changes the species harm proc to allow for more diverse attackers and special punching abilities. Checks for target states to determine damage increases with unarmed attacks.
balance: Kind of rebalances how a lot of punching works. You'll probably find that punching is a lot more reliable and has less weirdness with probability.
/:cl:

### CODE REVIEW

**Comment by Hatterhat** [comment]
why did i get pinged here - oh ok thanks

**Comment by necromanceranne** [comment]
Only I could break the punch test but not punching itself. Truly, I am a genius.

**Comment by Sparkezel** [comment]
what does the spicy version include?

**Comment by necromanceranne** [comment]
> what does the spicy version include?

Evil

**Comment by ATH1909** [comment]
> The infiltrator gloves are no longer nitrile glove subtypes, as the fireman carry trait is likely set for becoming a skillchip in the near future, and having an item that effectively is a skillchip but isn't would be somewhat weird for antagonist gear. Especially since chameleon skillchips exist to fill this niche as well.

Er, what exactly is the problem with them remaining nitrile glove subtypes? If the fireman carrying speed thing gets moved out of nitrile gloves and into a skillchip at some point in the future, then it'll also get moved out of any nitrile glove subtypes, including infiltrator gloves. I see no reason to remove the fireman carrying buff from them NOW instead of at the proper time.

**Comment by ATH1909** [comment]
"Also, it's impossible at a certain point for a pair of punchers to land a hit, so punching was kind of hilariously ineffective EXCEPT when you could kick, which would result in it being all the time **as your kick damage spiked you past your stun threshold.**"
Note that the current 1.5x multiplier to kick damage is NOT factored in when determining whether or not your unarmed attack's damage will meet or exceed your species's stun threshold.

**Review by Twaticus — APPROVED** [review]

**Comment by necromanceranne** [comment]
> Er, what exactly is the problem with them remaining nitrile glove subtypes? If the fireman carrying speed thing gets moved out of nitrile gloves and into a skillchip at some point in the future, then it'll also get moved out of any nitrile glove subtypes, including infiltrator gloves. I see no reason to remove the fireman carrying buff from them NOW instead of at the proper time; can you not just let them keep their fireman carrying buff AND give them these new powers?

Because I want to make them distinct now and the process of moving nitriles to a skill chip is actually incredibly easy and quick. So much so that I am going to do that PR right now. 

> "Also, it's impossible at a certain point for a pair of punchers to land a hit, so punching was kind of hilariously ineffective EXCEPT when you could kick, which would result in it being all the time **as your kick damage spiked you past your stun threshold.**"
> Note that the current 1.5x multiplier to kick damage is NOT factored in when determining whether or not your unarmed attack's damage will meet or exceed your species's stun threshold.

Eurgh you are right my 5am brain got confused with stuff I was considering when I made alterations to the code myself. If I made the raw damage roll handle carry to the stun proc, it would spike past the threshold if you kicked and especially if you were a stamina only puncher.

**Comment by ATH1909** [comment]
> Because I want to make them distinct now and the process of moving nitriles to a skill chip is actually incredibly easy and quick. So much so that I am going to do that PR right now.

If that other PR gets merged before this one, would you mind adding the skillchip from that PR to the infiltrator kit?

**Comment by necromanceranne** [comment]
I actually thought about it, and maybe later. I'll add something in that PR that might be appropriate.

**Comment by necromanceranne** [comment]
Just gonna leave this as it is now. Don't think it needs much more. Kidnapping stuff should be it's own dealio, or just replicated with a cham skillchip

**Comment by necromanceranne** [comment]
Had a talk with Rohesie about these changes and the punch stuff might need another go around to get right. I'm gonna close this, atomize the suit specific changes and readd fireman carrying.

Notably they weren't particularly keen on glove and equipment based buffs, but maybe this could be reintroduced in some other form.

**Pull request closed without merging**
