### PR TITLE
Makes shuttle turf copy use proper helper.

### LINKED ISSUE #13213: Shuttles that launch to dark areas are permanently dark
If you fly a shuttle to an area without light, it becomes dark and lights wont function inside.

I assume this is because shuttles dont use dynamic lighting.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #13213

Not really sure why it wasn't using proper helper before. 
This might make shuttles bit slower but shouldn't have any unusal sideeffects.
Unless i'm missing something that shouldn't be updated there.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
ya..... this seems like a no brainer, No idea why it wasn't using change turf.

oh carn....

**Comment by RemieRichards** [comment]
That's our carn!

**Comment by MrStonedOne** [comment]
Ok, so I've decided that if this breaks things, we will work around what it breaks rather than revert it back to not using this.

**Comment by KorPhaeron** [comment]
This will also probably fix being able to poke holes to space in planets by attacking a shuttle

**Pull request merged**
