### PR TITLE
Airlock controller revamp

### PR DESCRIPTION
**Pull request by Aranclanos**
Revampes airlocks normal controllers (virology and incinerator doors at the current map)
The old controller and access buttons are replaced by:
-/obj/machinery/doorButtons/airlock_controller
-/obj/machinery/doorButtons/access_button
Hopefully the path doorButtons will be the base for the replacement of the airlock controllers who are left
The new controllers do not use radios at all, they link the doors with simple variables
Fixes issue #267
The new controllers will not correct the airlocks state (open/close) on their process, they will only do it when ordered by the user
If any door is missing, the door left will act like a single door correctly
Cases where the doors modify themselves of powers go out while the controller is activated are covered to stop it
Added a new sprite for the access_button, to represent lack of power
The controller and the access button will now have animations using old unused sprites.
The old computer datum used by the old controller is removed
Map changes to replace the paths in the incinerator and virology airlock controllers
Added a bolt() and unbolt() procs for airlocks
The controller will search for the airlocks on initialization instead of each time the button is activated

haha this took me 8 legit hours
kill me

### CODE REVIEW

**Comment by Razharas** [comment]
Ill ask oranges if he can gift free games on each feature freeze
The productivity of this is just amaizing

**Comment by Razharas** [comment]
>Failed

Cmon

**Comment by Miauw62** [comment]
this fixes the last ported from googlecode issue

ITS HAPPENING
ITS HAPPENING

**Comment by Aranclanos** [comment]
It compiles just fine.

**Comment by xxalpha** [comment]
Metastation needs to be remapped.

**Comment by HoaxIT** [comment]
`Metastation`

is that still a thing?

**Comment by Dorsisdwarf** [comment]
Seeing as server2 has been running it for what, three years? Yes, it's a thing

**Comment by ike709** [comment]
Please put "Fixes #267" so the issue is actually closed.

**Comment by Razharas** [comment]
Aran fix metastation plz

**Comment by Aranclanos** [comment]
manually merge it pleaserino have some mercy

**Comment by Aranclanos** [comment]
updated your green button lazy faggots

**Pull request merged**
