### PR TITLE
Revert "Round weighting now reduces the chances of repeating a recently played mode (#30522)

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This reverts commit 8503bf3f6a0f0d8a044db2edd32beb7c916ab691.
@Robustin 

This broke round start.

### CODE REVIEW

**Comment by kevinz000** [comment]
150 hours of testing

**Comment by eatsleepnoderepeat** [comment]
Not even 500 commits

**Comment by JamieH** [comment]
It's broken.

```
[08:06:39] Runtime in ticker.dm, line 174: Cannot execute null.pre setup().
proc name: setup (/datum/controller/subsystem/ticker/proc/setup)
src: Ticker (/datum/controller/subsystem/ticker)
call stack:
Ticker (/datum/controller/subsystem/ticker): setup()
Ticker (/datum/controller/subsystem/ticker): fire(0)
Ticker (/datum/controller/subsystem/ticker): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)```

I did find that if I manually called setup on the ticker it would work.

**Comment by AnturK** [comment]
You mean the revert didn't help or is the runtime from before that ?

**Comment by MoreRobustThanYou** [comment]
1 5 0
h o u r s

**Comment by lzimann** [comment]
img_4801

As a wise man once said, it's good to go

**Comment by JamieH** [comment]
Runtime is from now, we don't have the revert

**Comment by Robustin** [comment]
I didn't get this when testing, nor does it natch the runtimes I had seen in prior versions. When you duck with the config in local tests there is a decent likelihood it will behave differently live.

Is that the most specific runtime you got? I don't even know where to start with that...

**Comment by Cyberboss** [comment]
I think @AnturK's got it covered

**Comment by MoreRobustThanYou** [comment]
S P E E D M E R G E

**Pull request closed without merging**
