### PR TITLE
Plasmamen Gear Sprite Tweaks and Helmet Light Re-Addition.

### PR DESCRIPTION
**Pull request by SweaterKittens**
## Sprite Tweaks ##

Most of the Plasmamen equipment sprites have been tweaked very slightly, to change the feel of their outfit from a loose bio-suit to more of a environmental survival suit. [New Sprites](http://imgur.com/a/tGbsJ) The top sprite is with the light on, the bottom is the standard with the light off.

## Helmet Light ##

Originally, Plasmamen had an in-built helmet light. However, this was nixed during the initial design and integration process, as there were concerns that Plasmamen would be overpowered (lol) as well the fact that Shadowling was in the rotation at the time, and the concern that a non-removable light would be problematic was very justified. As it's very clear that Plasmamen are nowhere even remotely close to being overpowered, and Shadowling is no longer in rotation, I've re-added the integrated helmet light along with the appropriate sprites

### Changelog ###
:cl: Sweaterkittens
add: The station's Plasmamen have been issued a new production of envirosuits. The most notable change aside from small aesthetic differences is the addition of an integrated helmet light. 
tweak: Tweaked a few of the Plasma Envirosuit sprites to be more fitting thematically.
/:cl:

<sub>Thank you to Joan for helping me with the code!<sub>

### CODE REVIEW

**Comment by Mindustry** [comment]
I personally prefer the older darker purple mask but I don't mind the changes. 
Though I do think having a light built into the helmet is a bit unnecessary. Now with #23015, Plasmamen can use their hardsuit helmets. They could just pick up a flashlight like everyone else has to if they want a carryable light. 

I would support the ability to attach a sec-lite to a Plasmaman helmet (or really any helmet) akin to the kinetic accelerator.

**Comment by SweaterKittens** [comment]
Just to be clear, the top sprite is just how it looks with the light on, while the bottom one is how it will look normally.

As far as necessecity - it's not. It's just a feature that Plasmamen had since their creation and was removed when I initially got them implemented here on /tg/. Since it's very clear that they're not overpowered in any way and much of the community's concerns have been alleviated, I'd like to put that feature back in. It's more for flavor than function.

**Comment by Kromgar** [comment]
I still think its funny people thought plasmamen would be op

**Comment by FantasticFwoosh** [comment]
I agree with @Mindustry on a darker if not completely opaque purple spherical space man mask to imply that its full of dangerous gas and give a creepy (walking space suit manned by a plasma skeleton) vibe to it.

**Comment by PKPenguin321** [comment]
>I still think its funny people thought plasmamen would be op

they used to have built in spaceflight and could wear an atmos hardsuit to be on fire forever

**Comment by SweaterKittens** [comment]
@PKPenguin321 They had a built-in EVA suit, not spaceflight, and that was heavily balanced by the fact that it slows them and is permanent. The atmos hardsuit issue was a bug, not a feature (no matter how awesome it was).

**Pull request merged**
