### PR TITLE
Disconnect and Reconnect messages for deadchat

### PR DESCRIPTION
**Pull request by MrDoomBringer**
## About The Pull Request
adds messages to deadchat when a client with a mob disconnects or reconnects

## Why It's Good For The Game
useful when you're a ghost and you want to tell if someone has actually disconnected without looking through the ooc who menu

## Changelog
:cl:
add: Ghosts can now see when people connect or disconnect!
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
I can also add a client preference for toggling broadcasting join/leave messages if there's a demand for that sorta thing

**Comment by LemonInTheDark** [comment]
I don't like this. Partly cause I like being able to join without getting noticed by the admin team, but mostly because I don't think it's info we really need to share so openly, and all this will do is enhance the existing salt and shaming that comes with dchat.

Could you elaborate on the use case here?

**Comment by MrDoomBringer** [comment]
> Partly cause I like being able to join without getting noticed by the admin team

you know admins get a message when people log in right

**Comment by MrDoomBringer** [comment]
@LemonInTheDark 
>Partly cause I like being able to join without getting noticed by the admin team

I'm fairly certain admins already get a message when people log in 

Anyways, I'm not convinced that this feature takes away from what we have. If you really want some use cases I can think of a few fairly common situations I've seen that this PR would address:

- If a ghost's game crashes or they leave, other people won't keep trying to talk to them despite them not actually being in-game
- if a ghost reconnects mid-round, player feedback is clear and their friends can say "what's up" etc. 
- If some antag you're orbiting suddenly stops moving and gets killed there's more clear feedback that they stopped moving due to being disconnected.

**Comment by optimumtact** [comment]
@LemonInTheDark that's an interesting view to take, considering the admin team can set it up to get popups every single time you join if they want

**Comment by LemonInTheDark** [comment]
Dear god.

**Comment by Timberpoes** [comment]
The "has observed" message is already a pain in the ass and doesn't work well alongside admins engaging stealth mode. I don't think we need to turn deadchat into IRC with connect/disconnect notifications.

**Comment by MrDoomBringer** [comment]
@Timberpoes how is it a pain in the ass? Also, sounds like the solution here is to fix the "has observed" message and add a check in this PR for stealth mode

**Comment by Timberpoes** [comment]
Reached a compromise.

image

**Comment by MrDoomBringer** [comment]
@Timberpoes, Just implemented those suggestions. Code tested, should be good.

**Comment by Timberpoes** [comment]
@LemonInTheDark fancy weighing in again in light of the above changes?

**Comment by LemonInTheDark** [comment]
👍

**Review by Timberpoes — APPROVED** [review]

**Pull request merged**
