### PR TITLE
[TGUI] ImageButton component

### PR DESCRIPTION
**Pull request by AyIong**
## About The Pull Request
A new component to standardise all image buttons.
It has the ability to assign an action to the right mouse button - `onRightClick={() => {}}`

I've tried to make it as easy to use as possible, without having to deal with its internals.
However, feel free to add/change anything in the component.
Documentation and story are included, so you can explore the props in the documentation, and touch the component itself in Kitchen Sink.

The component supports all currently available ways of displaying an image on the TGUI (unless I missed something): Asset Cache, resolveAsset, Base64 and DmIcon.
There is also a stub if the image is missing, and DmIcon's own fallback.

At the moment, it's only used in two places: SmartFridges + Drying Rack and Loadout

## Why It's Good For The Game
Quite convenient and universal way to create buttons with images inside.
Also, it pains me to see images being shoved into regular buttons.... And that's because there are no alternatives.

## Images of changes
Everyone loves comparisons, don't they?
<details>
<summary>SmartFridge</summary>

| Before (Grid) | Before (List) | After (Grid) | After (List) |
| - | - | - | - |
| image | image | image |image |

</details>

<details>
<summary>Loadout</summary>

| Before | After |
| - | - |
| image | image |

</details>

## Changelog

:cl:
add: SmartFridge and Loadout now use new TGUI component - ImageButton. SmartFridge buttons have RMB action, same as amount vend button.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
shouldn't this go in tgui-core

**Comment by ZephyrTFA** [comment]
https://github.com/tgstation/tgui-core

**Comment by AyIong** [comment]
> https://github.com/tgstation/tgui-core

Well.. it would be nice to have a mentition somewhere in documentation
Or i just blind? :D

**Comment by optimumtact** [comment]
i don't think the documentation has caught up yet.

**Pull request closed without merging**
