### PR TITLE
Removes the most ridiculous of the new wizard weapons

### PR DESCRIPTION
**Pull request by Incoming5643**
Removes supermatter sword from wizards: It is not balanced, shouldn't be balanced, and won't be balanced. It is SUPPOSED to be obnoxiously OP.

Removes veil render from wizards: Singularities at round start isn't fair to anyone. People who want to go meme wizard get options to meme with but this is just ridiculous.

Folds Mjolnir and Singularity hammer into the offensive category to remove the weapons category.

Doesn't touch multiverse sword war, which is pretty damn silly, but at least a unique experience.

:cl: incoming5643
rscdel: Citing shenanigan quality concerns the wizard federation has withdrawn supermatter swords and veil renderers from spellbooks.
/:cl:

### CODE REVIEW

**Comment by swankcookie** [comment]
when did SM swords become wiz gear?

**Comment by Steelpoint** [comment]
From what everyone is saying this is from Kor.

I agree with this change, there's a meme spell and then there's something that's just so overpowered its not funny.

**Comment by Razharas** [comment]
@duncathan 
@KorPhaeron 
Cmon

**Comment by Iamgoofball** [comment]
multiverse sword is at least fun for everyone

i feel like the codeularity should be ressurected as something else at some point

**Comment by Niknakflak** [comment]
I TOLD YOU KOR.  I TOLD YOU

**Comment by PKPenguin321** [comment]
Fixes #13170

**Comment by Bawhoppen** [comment]
anyone who thought adding the fucking supermatter sword to wiz book should be crusified and burned alive

**Comment by Dorsisdwarf** [comment]
It was up for 4 days shoulda commented then baww

**Comment by Zilenan91** [comment]
On another note, rip veil render, we hardly knew ye.

You won't really be missed tbh.

**Comment by KorPhaeron** [comment]
What is wrong with veil render?

**Comment by KorPhaeron** [comment]
I'm not joking by the way I don't see how a small singulo that doesnt give off radiation is worse than infinite murder statues+grilles in the number of people it will kill, and its easier to avoid than the triplestun jaunt wizard.

It also threatens the wizard so all the destruction has a drawback.

**Comment by KorPhaeron** [comment]
@NikNakFlak

Hey 60% of the PR is still in so its still majority positive

**Comment by KorPhaeron** [comment]
Anywaay please spare veil render I am proud of the silly joke sprite I dont want it to go to waste.

I've not actually heard complaining about it either since I fixed it to not be nar-sie. I feel like this is about the "its okay I snuck veil render in" comment more than the gamelplay

**Comment by duncathan** [comment]
Tbqh I didn't think this would last as long as it did

**Comment by KorPhaeron** [comment]
@duncathan 

Probably because one bad ragin mages round doesn't really represent normal gameplay as a whole.

**Comment by Anonus** [comment]
I can tell you that, even if you make the supermatter 10 points, I WILL find a way to use it and meme the station to death, so you really should just take it out.
It's not fun for anyone, least of all the people getting insta-radded to death by me.

**Comment by KorPhaeron** [comment]
I wasnt aware that you could manually trigger the rads when I added it. I dont have an issue with the sword being taken out.

I do have issue with veil render being removed though

**Comment by Marflowerose** [comment]
@Iamgoofball Multimemesword would be fun if players got team icon to see who actually is part of the own memegroup.

**Comment by Bawhoppen** [comment]
@Marflowerose team icons are cancer never add

**Comment by Zilenan91** [comment]
Or just making all memesword users have the same outfit and 100 AP. That would fix them, because currently it's annoying as fuck to try and see if those people down there are you or not, and also solve the issue of some spawning with robust armor.

**Comment by Incoming5643** [comment]
kor the thing about the veil renderer is that there's literally no counter-play to it. Once a singularity is plopped down in the center of the station that's it. You can't destroy it, you can't contain it, you can't do anything about it. It just fucks the round utterly.

**Comment by KorPhaeron** [comment]
The round is utterly fucked from the moment a wizard spawns, especially with summon spells. You can run away from the singulo, which is what you have to do with half the wizard shit already anyway.

And a traitor can steer the singulo through the station roundstart as well.

**Comment by Incoming5643** [comment]
Listen just because you think wizards are a joke doesn't give you carte blanche to add things that make the problem worse.

**Comment by KorPhaeron** [comment]
I have added

-staff of change
-summon guns
-soulstones
-apprentices
-scrying orb
-timestop

And now these weapons.

I think "one guy stacks mobility/stuns/ei nath" is a joke. I have continously pushed to move wizard away from that. More people having fun, more chaos, less invincible murderman. I think the mode has been improved for that.

Treating wizards like a joke is the best thing that ever happened to the mode.

I'd have thought you would agree since you added 2 more summon spells that are even more chaotic than mine.

**Comment by Iamgoofball** [comment]
i should port summon mecha from NT

**Comment by Zilenan91** [comment]
I think it was goon that gave the wizard a chariot that was literally a Mule that ran people over.

**Comment by Incoming5643** [comment]
Well yeah, but the difference is that if a wizard summons magic there's a decent chance someones going to smack him with a wand of death, and summon events generally don't spare the wizard either unless it would instantly ruin his round by removing his robes or something. A wizard is simply never going to be caught by a singularity, he is the most mobile player in the entire game.

I mean it's fine to add stuff like that, I'm just saying it's not balanced, and really not even possible TO balance. Did you even really expect that pull to get merged with supermatters and veil renders in? I think a lot of people didn't. It kind of caught me flatfooted. So I shrugged and waited to see what people did with them. What I saw is that there's literally no other use for a singularity other than for shitting on the round. By the time this gets added people will have had at least two weeks with these wizard items, and I think the novelty will have worn off anyways.

You're right about the stuns, which is why I opened #13085.

**Comment by KorPhaeron** [comment]
My point is that I talk a lot of shit about wizard but I think I came off too seriously/malicious and I genuinely think we have much the same design goals. You don't need to protect wizard from me.

My history working on wizard, I hope, speaks louder than my words. I'm not trying to ruin the mode. I am out to ruin old wizard, it's true, but by providing as many zany (and I genuinely hope fun) alternatives as possible.

**Comment by Incoming5643** [comment]
Well yeah I think we can both agree that giving more selection to a wizard both to increase diversity and reduce predictability in loadouts is always a good idea (except when it leads to stun saturation) and that coding wizard shit is fun.

Alright I don't think either of us are actually mad at each other. You do add cool things to wizard. I'm just saying the veil renderer was removed for a pretty solid reason.

**Comment by Niknakflak** [comment]
BATTLE OF THE WIZARD CODERS.

INCOMING VS KOR
WHO WILL WIN???

**Comment by KorPhaeron** [comment]
Probably Incoming since veil render is kinda dumb

I'm attached to the sprite now though

**Comment by drynwyn** [comment]
So think of something cool for the Veil Render to do other than create a singulo.

**Comment by Bawhoppen** [comment]
Heres my replacement suggestion

If you've played terraria you might know the vilethorn weapon 
terraria_weapon_vilethorn


We would take that idea for a weapon and make it our own
ss 2015-11-24 at 12 13 32

It would do damage or whatever to whoever it hit and it also could leave shit behind (mainly trash and garbage to show how poorly made the fabric of reality is) and crack the floors and leave lube stains

**Comment by Zilenan91** [comment]
Grease spell that spews lube in all directions around the wizard Y/Y?

**Comment by Iamgoofball** [comment]
@Incoming5643 @KorPhaeron please consider bawhoppen's idea, it seems pretty rad and allows us to keep the "rift to the code" bit

**Pull request merged**
