### PR TITLE
Removes mobs from SSmob.currentrun

### LINKED ISSUE #22796: Those exploding pirates
```
ADMIN LOG: Explosion with size (0, 1, 5, 0) in area Unexplored Location (149,206,6 - JMP)
ADMIN LOG: Explosion with size (0, 1, 5, 0) in area Unexplored Location (149,205,6 - JMP)
runtime error: 
[00:46:53]Cannot execute null.handle fall().
[00:46:53]proc name: fall (/mob/living/carbon/fall)
[00:46:53]  source file: carbon.dm,229
[00:46:53]  usr: null
[00:46:53]  src: Vivian Stroble (/mob/living/carbon/human)
[00:46:53]  src.loc: null
[00:46:53]  call stack:
[00:46:53]Vivian Stroble (/mob/living/carbon/human): fall(1)
[00:46:53]Vivian Stroble (/mob/living/carbon/human): update canmove()
[00:46:53]Vivian Stroble (/mob/living/carbon/human): death(1)
[00:46:53]Vivian Stroble (/mob/living/carbon/human): death(1)
[00:46:53]Vivian Stroble (/mob/living/carbon/human): death(1)
[00:46:53]Pirate (/obj/effect/mob_spawn/human/corpse/pirate): create(null)
[00:46:53]Pirate (/obj/effect/mob_spawn/human/corpse/pirate): New(null)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): death(null)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): death(null)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): update stat()
[00:46:53]...
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): adjustHealth(15, 1, 0)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): adjustHealth(15, 1, 0)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): handle temperature damage()
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): handle environment(/datum/gas_mixture/space (/datum/gas_mixture/space))
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): Life(2)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): Life(2)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): Life(2)
[00:46:53]Mobs (/datum/subsystem/mobs): fire(1)
[00:46:53]Master (/datum/controller/master): Loop()
[00:46:53]Master (/datum/controller/master): StartProcessing()
runtime error: 
[00:47:29]Cannot execute null.handle fall().
[00:47:29]proc name: fall (/mob/living/carbon/fall)
[00:47:29]  source file: carbon.dm,229
[00:47:29]  usr: null
[00:47:29]  src: Raegan Shick (/mob/living/carbon/human)
[00:47:29]  src.loc: null
[00:47:29]  call stack:
[00:47:29]Raegan Shick (/mob/living/carbon/human): fall(1)
[00:47:29]Raegan Shick (/mob/living/carbon/human): update canmove()
[00:47:29]Raegan Shick (/mob/living/carbon/human): death(1)
[00:47:29]Raegan Shick (/mob/living/carbon/human): death(1)
[00:47:29]Raegan Shick (/mob/living/carbon/human): death(1)
[00:47:29]Pirate Gunner (/obj/effect/mob_spawn/human/corpse/pirate/ranged): create(null)
[00:47:29]Pirate Gunner (/obj/effect/mob_spawn/human/corpse/pirate/ranged): New(null)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): death(null)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): death(null)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): update stat()
[00:47:29]...
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): adjustHealth(15, 1, 0)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): adjustHealth(15, 1, 0)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): handle temperature damage()
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): handle environment(/datum/gas_mixture (/datum/gas_mixture))
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): Life(2)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): Life(2)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): Life(2)
[00:47:29]Mobs (/datum/subsystem/mobs): fire(1)
[00:47:29]Master (/datum/controller/master): Loop()
[00:47:29]Master (/datum/controller/master): StartProcessing()
```

While we're here, does anyone know why these pirates are so prone to exploding?

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #22796 among other things

### CODE REVIEW

**Review by MrsTonedOne — APPROVED** [review]

**Comment by MrStonedOne** [comment]
Wot

**Comment by Cyberboss** [comment]
@optimumtact said things

**Comment by Cyberboss** [comment]
```
3:18:48 PM
%beerobot
if we properly stored on every object what ticker it was assigned to 
3:18:54 PM
%beerobot
we could actually do it generically in the parent destroy proc 
3:18:56 PM
%beerobot
hmm 
3:18:57 PM
Somepotato
Bv], thats the point i'm trying to make 
3:18:59 PM
%beerobot
I think I have an idea 
3:19:09 PM
Cyberboss
alright 
3:19:10 PM
PJB3005
Bv], what do you mean 
3:19:11 PM
%beerobot
there is already a need to track which ticker something is processing on 
3:19:15 PM
TheGhostOfWhibyl1
[tgstation] Cyberboss closed pull request #23832: Removes mobs from SSmob.currentrun (master...patch-15) https://github.com/tgstation/tgstation/pull/23832 
3:19:19 PM
Cakey
I'm working modifying the chraracter prefs menu, but for some reason any if statements I add into it stop the proc from completing at all, any ideas? 
3:19:19 PM
%beerobot
MrStonedOne and me have chatted about this before 
3:19:23 PM
%beerobot
Cyberboss: no keep that open 
3:19:25 PM
%beerobot
I am slow 
3:19:27 PM
%beerobot
and unreliable 
3:19:36 PM
TheGhostOfWhibyl1
[tgstation] Cyberboss reopened pull request #23832: Removes mobs from SSmob.currentrun (master...patch-15) https://github.com/tgstation/tgstation/pull/23832 
3:19:38 PM
Bv]
PJB3005: calling C from DM is much slower than calling Rust from C so it really doesn't matter if calling Rust from C is fast 
```

**Comment by optimumtact** [comment]
wait, why dont' we just do this in the remove_from_subsystem call?

**Comment by Cyberboss** [comment]
STOP_PROCESSING? I suppose...

**Comment by optimumtact** [comment]
hmm wait, how does this work? currentrun is a method local var

**Comment by MrStonedOne** [comment]
No its not

**Comment by MrStonedOne** [comment]
It looks like it is, but its not

**Comment by Cyberboss** [comment]
No, you know what, the generalization of currentrun has been a long time coming. I'm going to do this right

**Pull request closed without merging**
