### PR TITLE
Ports over the Military Jacket from NTstation

### PR DESCRIPTION
**Pull request by TheVekter**
By popular request.

Spawns in all sec lockers, identical stats to armor, just looks way cooler. Enjoy.

### CODE REVIEW

**Comment by WJohn** [comment]
I can't actually remember ever having these but :+1: I guess?

Fashion sec forever.

**Comment by optimumtact** [comment]
Operation Flashpoint : security military jacket

This year, the security gear cold war heats up.

**Comment by Thunder12345** [comment]
Fail.

**Comment by optimumtact** [comment]
We appreciate your feedback and we want you to know that we will do our best to resolve this situation as best we can to yours and our mutual satisfaction.

**Comment by TheVekter** [comment]
He's talking about me fucking up and putting other changes in there. I'll fix it.

**Comment by Thunder12345** [comment]
Much better, yay

**Comment by ike709** [comment]
:+1:  Fashion Police

**Comment by Nanotransistor** [comment]
Now everyone looks like the HoS.

**Comment by SconesC** [comment]
@Nanotransistor That's okay the HoS has already been nerfed to be borderline indistinguishable from the average officer :^)

**Comment by PKPenguin321** [comment]
:-1: looks like someone puked on the officer's upper half

**Comment by optimumtact** [comment]
Just as well you don't need to wear it

**Comment by bustygoku** [comment]
Would prefer this stayed as a cosmetic jacket for anyone to wear that came in a clothing vendor. Looks more like a hippie '60s Vietnam protester jacket, ala Travis Bickle.

**Comment by TheVekter** [comment]
I've gotten a lot of requests to port it over straight, so...

**Comment by Fox-McCloud** [comment]
I'd like to point out that this is technically a buff to security, as it's better than regular armor, straight up (covers arms as well).

**Comment by TheVekter** [comment]
That's a good point. I'll fix that in a bit.

**Comment by Cheridan** [comment]
Yeah, I think this should be Vendomat instead. It breaks the style of the Sec uniforms which are the most important job to have a uniform appearance.

**Comment by pudl** [comment]
Put it in the vendomat or sec wardrobe.

**Comment by TheVekter** [comment]
I'll move it to the vendomat tonight. Dnm for now.

**Pull request merged**
