### PR TITLE
Removes buying shuttles because the headmins disabled it.

### PR DESCRIPTION
**Pull request by Iamgoofball**
# its almost like I said making this configurable would result in one of our 3 shitty headmins silently disabling all of them, bet it was joan

chrome_2017-04-28_21-45-52

### CODE REVIEW

**Comment by optimumtact** [comment]
this is premature

**Comment by Haevacht** [comment]
and immature

**Comment by Ausops** [comment]
well more than 3+mso people have access to remote plus there were server crashes earlier this week

it was re-enabled anyway

**Comment by PKPenguin321** [comment]
It was disabled because it was bugged to send the glitch handler shuttle every time you bought one, but thanks for making a big text pr instead of just telling us or something

**Comment by Iamgoofball** [comment]
# REPORT YOUR BUGS NEXT TIME CUNTBUCKET

**Pull request closed without merging**
