### PR TITLE
minor_announce now only works in areas that'd logically have working speakers

### PR DESCRIPTION
**Pull request by Cyberboss**
This doesn't affect priority_announce. Why: To increase immulsions, minor things shouldn't be able to be heard in areas they logically couldn't be.

:cl:
tweak: Minor station announcements can now only be heard in powered station areas
/:cl:

### CODE REVIEW

**Comment by BeeSting12** [comment]
Which ones or the minor announcements?

**Comment by ShizCalev** [comment]
@BeeSting12 from the looks of it, it just stops you from hearing announcements while on Lavaplanet.

**Comment by Tacolizard** [comment]
This should also prevent you from hearing announcements in maint

**Comment by Cyberboss** [comment]
@Tacolizard it only works for ghosts, admins, and mobs that can hear in powered areas. Idk, if maint is powered but it definitely won't work in space

**Comment by kevinz000** [comment]
REEEEEEEEEEEEEEE

**Comment by MrPerson** [comment]
Seems dumb. Minor announcements are generally things everybody should be aware of so they can actually interact with them.

**Comment by PKPenguin321** [comment]
:-1: Gameplay trumps immersion here

**Comment by Tacolizard** [comment]
but people on lavalnd don't care if there's a radstorm or a random rod spawned???

**Comment by optimumtact** [comment]
Uhh, aren't these coming through your headset?

**Comment by lzimann** [comment]
people seem to dislike + headsets are a thing so they would probably work in no-radioed areas...

**Pull request closed without merging**
