### PR TITLE
GAGS-ifies the Hawaiian Shirt, adds it to the ClothesMate

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Technically a port of https://github.com/Skyrat-SS13/Skyrat-tg/pull/17085
On the tin, it was mentioned that they could use it, I had these on-hand. Probably should have been up here in the first place anyways.
dreamseeker_ktdTANkHU9
dreamseeker_0jPbNpXygu
dreamseeker_AVZClDGGRt

Also makes them available in the ClothesMate so that crew can enjoy this beautiful... just... beautiful item.

Worth noting, this item may be reworked in the future to an accessory. This is just the greyscale half, the hard part. Changing the type to an accessory in the future is easy now.
## Why It's Good For The Game
GAGS is good for items like this that just deserve lots of color. And making them available for crew to actually use is cool.
## Changelog
:cl:
add: The Hawaiian Overshirt is now GAGS, and available to crew in the ClothesMate. Mahalo a aloha!
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
By accessory you mean the coat slot?

**Review by Wallemations — APPROVED** [review]

**Comment by TheVekter** [comment]
Something something ClothesMate bloat, or do we not care about that now that GAGS is a thing

**Comment by Wallemations** [comment]
> Something something ClothesMate bloat, or do we not care about that now that GAGS is a thing

I'd attribute it more to vending categories existing now, so it's not as cluttered as before

**Review by dragomagol — APPROVED** [review]

**Comment by OrionTheFox** [comment]
> By accessory you mean the coat slot?

Actually, it's already in the coat/suit slot. It mayyyy be moved to be a uniform accessory, where it can be attached to any uniform; but that's just talks and spitballing, no gurantees

**Pull request merged**
