### PR TITLE
Objs become unanchored if their turf becomes space

### PR DESCRIPTION
**Pull request by Cyberboss**
Good idea?

### CODE REVIEW

**Comment by coiax** [comment]
Override it for the syndicate nuke, otherwise it makes it possible to RCD the floor from under it, and then space it.

**Comment by Incoming5643** [comment]
Can lead to weirdness with multi-tile machines that were never intended to be movable.

**Comment by Iamgoofball** [comment]
anchored is used by a shitton of random stuff to prevent the atom's movement in any way, shape, or form, should not be tampered with

**Comment by PKPenguin321** [comment]
Yeah, the nuke comes to mind

**Comment by FantasticFwoosh** [comment]
Goliaths use anchor too, i can't see how dragging them around space is a meaningful feature beside the balance concern of the nuke.

**Comment by AnturK** [comment]
Effects

**Comment by Iamgoofball** [comment]
if you absolutely want to do this @Cyberboss make it call a proc that defaults to return null or something and make machines override that proc to unanchor

**Comment by coiax** [comment]
I think this will cause a lot of bugs for a very minor fix. If you want to see it to the end, then do so, but I'm not sure if it's worth it.

**Comment by Robustin** [comment]
Yea I see a lot of really bad things happening from this (lol dominators). Don't bother.

**Comment by KorPhaeron** [comment]
Could rcd under a mech and be able to pull it

**Comment by KorPhaeron** [comment]
I think this would unanchor the singulo as well which would be pretty funny if you shot it with a grav gun

**Comment by xxalpha** [comment]
See what the solars are doing, this might make it redundant.

**Comment by Cyberboss** [comment]
whoever named the var, should have named it immovable

**Comment by FantasticFwoosh** [comment]
hah more like un-mergable.

**Pull request closed without merging**
