### PR TITLE
Adds the ability to disable lavaland via the tgstation server tools.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Lavaland will stay enabled if the server tools are not used.
Alternative to #18740
@KorPhaeron 

@MrStonedOne since I'm touching the server tools

### CODE REVIEW

**Comment by coiax** [comment]
Remote abuse

**Comment by xxalpha** [comment]
Can we just abandon non lavaland mining?

**Comment by KorPhaeron** [comment]
This is probably better what I'm doing but I'm worried it's going to lead to some dumb demand that we have mining rotation and have to design the game around that

**Comment by xxalpha** [comment]
Exactly, we should just keep lavaland and develop lavaland.

**Comment by Shadowlight213** [comment]
@xxalpha this just allows lavaland to be switched off an on as needed. It will be super easy to switch it back on when kor feels like he wants to work on it again.
I could already do something similar by adding code to the updater to force disabling lavaland locally.

@KorPhaeron I can see how that would be a valid worry, but note that implementing that would REQUIRE that someone with remote change the server tools manually to support it.

**Comment by xxalpha** [comment]
This will just lead to extra work for contributors and for what?

**Comment by optimumtact** [comment]
Yeah, I'm not sure as maintainers that we're willing to manage both mining and lavaland.

It has to be one or the other and frankly it's past due time to have old mining completely ripped out

**Comment by optimumtact** [comment]
I really don't see the point in this, mining should be completely removed

**Comment by Cebasiz** [comment]
lavaland is fine

every problem with it is merely a symptom of other problems

ash liggers can be solved by reinvigorating security and just handing them a few lasers t b h

**Comment by AlexCrimson** [comment]
If having a rotation is out of the question, then just keep Lavaland. Its infinitely more interesting than Asteroid ever was.

Just sayin' though, if anyone ever remakes Asteroid to be on par with Lavaland, then it sure would be neat to have the server rotation between the two.

**Comment by Shadowlight213** [comment]
Honestly, we could just have both be loaded at the same time.

**Comment by KorPhaeron** [comment]
That'd be incredibly redundant to have 2 entire z levels for 3 people to mine on

**Comment by AlexCrimson** [comment]
Not a fan of having both loaded at the same time, but it might be a good idea to increase the Mining job slots to 4-5, or at least add some spare suits on the Mining Station.

**Comment by KorPhaeron** [comment]
I have been convinced this is a bad idea because

1) I clearly cant be trusted to not randomly delete/remove my own work

2) Gameplay changes are being made with the assumption that lavaland always exists (cult is the most recent and biggest example)

**Comment by KorPhaeron** [comment]
I do appreciate the effort to help though thank you

**Pull request closed without merging**
