### PR TITLE
Fixes #49156, godhand touch spells now visible as item

### LINKED ISSUE #49156: Smite and Flesh to Stone hand icons are invisible
## Reproduction:
Step 1: Be a wizard.
Step 2: Buy either Smite or Flesh to Stone with your spellbook.
Step 3: Activate either spell so that it gets channeled into your hand.
Step 4: Right click the hand with the spell. It's there, but invisible!
Step 5: Examine the spell. The examine icon is a syndicate balloon.

## The issue:
#45791 caused this by replacing the icon var to icons/obj/balloons.dmi. Balloons used to be in the icon file icons/obj/items_and_weapons.dmi, which is where the icons for the smite and stone hands currently are.
By setting the icon's file for the base touch spell item to balloons.dmi without setting the icon for ei nath and staun ei, the icon is invisible because there is no such icon_state called "disintegrate" or "fleshtostone" in balloons.dmi.

## Pictures and related code:
image
Wizard with smite active, smite in his hand, examine text 

https://github.com/tgstation/tgstation/blob/10c6208c07afec369f338e65f00f467f9d75faeb/code/modules/spells/spell_types/godhand.dm#L7
Icon is set to balloons.dmi
https://github.com/tgstation/tgstation/blob/10c6208c07afec369f338e65f00f467f9d75faeb/code/modules/spells/spell_types/godhand.dm#L52-L53
But icon isn't set to items_and_weapons.dmi here, which calls a nonexistant icon_state.

### PR DESCRIPTION
**Pull request by trollbreeder**
## About The Pull Request

Fixes #49156 by changing the icon directory to items_and_weapons.dmi.
In addition, this also changes the base godhand type's icon from the syndicate balloon to the latex balloon.

**Please tell me if i'm doing anything wrong because this is my first PR.**

## Why It's Good For The Game

Fixes bad bug.

## Changelog
:cl:
fix: Fixes an issue where Smite and Flesh to Stone were invisible in item form.
/:cl:

### CODE REVIEW

**Comment by JJRcop** [comment]
Please use descriptive PR titles

**Comment by trollbreeder** [comment]
i thought that fixes #[PR NUMBER] was the format

**Comment by Tharcoonvagh** [comment]
create another branch, if you commit to master things WILL get fucky

**Comment by trollbreeder** [comment]
that's a second thing i noticed yeah, that guide probably scuffed the branch i made for this

**Comment by tralezab** [comment]
congratulations on your first pr, it's great!

**Review by spookydonut — APPROVED** [review]

**Comment by RaveRadbury** [comment]
@trollbreeder congrats on the contributor badge

**Comment by trollbreeder** [comment]
@raveradbury Does that mean you can unblock me now?

**Pull request merged**
