### PR TITLE
Hypernob formation now consumes less trit in presence of bz

### PR DESCRIPTION
**Pull request by TheBoondock**
## About The Pull Request
Hypernob consumes a massive amount of trit and with the new ordinance update, making enough trit for nob experiment can be a big hurdle. This will hopefully make hypernob synthesis in ordinance much easier and requires less trit.

## Why It's Good For The Game
Add a way to reduce the insane amount of trit consumed in hypernob formation so that ordinance players will have an easier time doing nob experiment

## Changelog

:cl:
add: Bz now reduces trit consumption in hypernob formation
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
I'm not sure about the idea of tritium consumption being based on how much bz there is.

BZ being consumed for the reaction would make it a requirement and something people have to dump in. Since BZ is used to reduce the insane energy release from the reaction, the energy release from the reaction will be less prevelant, as people will use bz at significant amounts because it's required for the formation instead of to prevent themselves blowing up.

I would prefer it if the tritium consumption was just reduced, not based on bz content, and nitrogen consumption increased. BZ would then keep its role as being needed to not blow shit up, instead of needing it to begin synthesis.

**Comment by TheBoondock** [comment]
> I'm not sure about the idea of tritium consumption being based on how much bz there is.
> 
> BZ being consumed for the reaction would make it a requirement and something people have to dump in. Since BZ is used to reduce the insane energy release from the reaction, the energy release from the reaction will be less prevelant, as people will use bz at significant amounts because it's required for the formation instead of to prevent themselves blowing up.
> 
> You could make tritium consumption based on the temperature of the reaction, and BZ should not be consumed. BZ would then keep its role as being needed to not blow shit up, instead of needing it to begin synthesis.

Fair point, I added the bz consumption because I fear it could result in creating a new mass from nothing. I will remove the bz consumption. I do however like the reduction to be based on the amount of bz.

**Comment by Pickle-Coding** [comment]
BZ reduces energy gain, making it easier to achieve lower temperatures. BZ would indirectly decrease tritium consumption in this system as the temperature is lower.

**Comment by Inari-Whitebear** [comment]
I thought part of the point of those experiments was to have Toxins co-operate with atmos or so.
That said, it's not like you even need a lot of it if you just want to do the unlock (read: virtually 0)

**Comment by antropod** [comment]
cooperation is a myth

**Comment by GuillaumePrata** [comment]
If the issue is how hard it is to make enough tritium for the experiment, wouldn't it be easier to just lower the HN requirements for the experiment directly?
If it's in a lower amount it is also easier for the Atmos Techs to make some of it to gift Science a tank they prepared, which I assume would be the best result of those change, cooperation.
Science has a BZ can roundstart while Atmos need to produce their own, depending on how this balance change swings it might be significantly easier for Scientists to make HN for themselves than for an Atmos to do it to help them.

**Comment by TheBoondock** [comment]
Bz now no longer get consumed in the reaction and only reduce trit consumption. I like having bz reducing trit consumption, it further reinforces using bz in hypernob.

**Pull request closed without merging**
