### PR TITLE
Fix amputation

### LINKED ISSUE #75631: Skeletons no longer can be augmented or have their limbs amputated
## Reproduction:

As it says in the title. Skeletons no longer can be augmented or have their limbs amputated.

Skeletons have TRAIT_EASYDISMEMBER, but I suspect https://github.com/tgstation/tgstation/pull/75583 was somehow the cause? I don't even understand how. There is no changes to skeletons, and skeletons don't have either of the traits in that PR.

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Fixes #75631 

https://github.com/tgstation/tgstation/pull/75583#pullrequestreview-1442893750

## Changelog

:cl: Melbert
fix: Fixes being unable to amputate
/:cl:

### CODE REVIEW

**Review by san7890 — APPROVED** [review]
lol

**Comment by ATH1909** [comment]
me when untested kneejerk pr gets merged

**Comment by necromanceranne** [comment]
> image

Oh don't worry, I'll be sure to remind you whenever I can to test your code. Particularly if it's a one or two line change where a test is simple.

Alternatively, a unit test does the job perfectly, as suggested by melbert.

**Comment by mc-oofert** [comment]
> Oh don't worry, I'll be sure to remind you whenever I can to test your code. Particularly if it's a one or two line change where a test is simple.
image

**Pull request merged**
