### PR TITLE
Revert "Big chungus"

### PR DESCRIPTION
**Pull request by LemonInTheDark**
Reverts tgstation/tgstation#55938

### CODE REVIEW

**Comment by IndieanaJones** [comment]
No

**Comment by Couls** [comment]
not wholesome 100

**Comment by actioninja** [comment]
No, important change that needed to happen.

**Comment by LemonInTheDark** [comment]
no

**Comment by Jared-Fogle** [comment]
https://github.com/tgstation/tgstation/commit/4f34b41118c33cd8419720ae524c423e3bda7a70

**Comment by wesoda25** [comment]
image

**Pull request closed without merging**
