### PR TITLE
Makes the GAS system only update the icon when it has changed

### PR DESCRIPTION
**Pull request by ninjanomnom**
So it seems there's a memory leak when applying a new icon to the icon var even if it is the same thing. I still need to replicate this in a standalone project ~~but this workaround should be fine for now. Strictly speaking the leak is still there but so slow that it shouldn't make a difference compared to any other assignment to icon which I assume has the same problem.~~

Trying to workaround this by handling the asset cache interaction manually now, but likely this is going to need to be memory profiled on live to figure out the issue. The leak is still happening even when no GAS code is executing.

### CODE REVIEW

**Comment by Mothblocks** [comment]
I will be TM'ing this on Manuel and Terry later today.

**Comment by Mothblocks** [comment]
Manuel and Terry are still crashing, but not as much, just above what I usually expect.

I need to check the round IDs to see if its OOM.

**Comment by Mothblocks** [comment]
Turns out they're still crashing every round just...slower?

**Comment by celotajstg** [comment]
Terry crashed often before GAS got merged too though.

**Comment by Mothblocks** [comment]
Yes, I know, that's what I meant by this:

> Manuel and Terry are still crashing, but not as much, **just above what I usually expect.**

**Comment by ninjanomnom** [comment]
I'm keeping the caching changes here since it does improve how it works a bit, this way we're giving clients a properly baked sprite instead of a bunch of steps to make the sprite.

**Pull request merged**
