### PR TITLE
Adds the sacred Blahaj to the loudout menu

### PR DESCRIPTION
**Pull request by Astrogem2**
## About The Pull Request
Adds the shark plushie, Blahaj, to the item loadout pool.

## Why It's Good For The Game
It's a wonderful thing to be able to have, and a its a travesty that you can't start with it.

## Changelog

:cl:
add: Added Blahaj to the character loadout menu (Hooray).
/:cl:

### CODE REVIEW

**Comment by Astrogem2** [comment]
> You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

What are these lies, what is this libel!

**Comment by DATA-xPUNGED** [comment]
Feature creep/s

**Comment by ZephyrTFA** [comment]
get this coder some gbp

**Comment by Mothblocks** [comment]
reddit

**Comment by LemonInTheDark** [comment]
don't like this it feels hackneed

**Pull request closed without merging**
