### PR TITLE
Some manned turret balance from oldmans newgangs PR

### PR DESCRIPTION
**Pull request by improvedname**
some balance code changes fetched from oldmans pr to be merged into the current state of this gang
to prevent running and shooting while oldman reworks gangs.

### CODE REVIEW

**Comment by improvedname** [comment]
nvm

**Comment by KorPhaeron** [comment]
?

**Comment by Robustin** [comment]
Looks like all the manned turret balance I did in my gangs PR but since its not testmerged/merged yet he wanted to speed things up.

**Comment by improvedname** [comment]
ye

**Pull request closed without merging**
