### PR TITLE
Only one successful Gang Tool recall per gang

### PR DESCRIPTION
**Pull request by Robustin**
Of the worst Gang rounds I've seen, about 30% of the problem comes from infinite remote recalls.

### CODE REVIEW

**Comment by obscolene** [comment]
they run out of good boy points eventually. gangs need to be able to recall because the thing people do when they see gangs is immediately call.

**Comment by Kromgar** [comment]
Or make recalls cost a ton of gang boi points

**Comment by Magikarpet** [comment]
that would just result in the captain spam calling with no punishment to drain the gang's points thereby denying them weaponry/tools

either way this wouldnt fix the issue of "The focus is on security rather than the gangs", only cement it.

**Comment by PKPenguin321** [comment]
Infinite recalls but on a heavy cool down?

**Comment by Robustin** [comment]
@PKPenguin321 

My hard line stance on this is because:

1) You can still block a shuttle from leaving in a matter of seconds by spawning a dominator and activating it. Multiple antag groups being able to cockblock the shuttle with no advanced notice is already one of the most potent shuttle blocking methods in the game. I'm confident gangs could survive with recalls removed entirely and their pen cooldown reduced instead. 

2) Giving multiple gangs access to multiple recalls just leads to too many scenarios where a round goes on for 20 minutes longer than it ever should with staggered ping-ponging. I'd rather make Gangs more potent elsewhere (after I check in on their win rate) rather than making their key strength the ability to ping-pong the shuttle repeatedly. Nobody is having fun when the only war going on is the calling v. recalling spam.

**Comment by coiax** [comment]
Removing their recalls just turns the game mode into "guard the communications console", and further emphasises the call the shuttle meta.

**Comment by CPTANT** [comment]
Personally I think that letting a recall cost a significant amount of influence points is the most elegant solution.

**Comment by KorPhaeron** [comment]
Most of your changes seem geared to making the round end faster so far. This PR is probably reasonable, but still.

**Comment by coiax** [comment]
We can probably remove gang recallers if we get those proposed shuttle negative milestones merged. I'll see if I can work on them this evening.

**Comment by optimumtact** [comment]
gang was removed

**Comment by Robustin** [comment]
@KorPhaeron 

Gang rounds were always far longer than they ever needed to be. Either security had to stomp out every gang leader or the gang had to wipe out all opposition to ensure their dominator wouldn't get cheesed. 

If sec are taken out then the round absolutely needs to make steady progress towards resolution. Even the best Gang War design would fail if it allowed for bosses to drag a lost round out.

**Comment by PKPenguin321** [comment]
You have good reasoning. This seems good to me then

**Pull request merged**
