### PR TITLE
Smugglers satchels are now super, duper, koopa, troopa hidden. From observers.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Enhanced the undertile element to have an additional trait arg that can be applied to items and is intended to be used to control how observers can see the undertile thing.

Adds a new item trait that prevents the item being visible to observer t-ray scanners.

Removes the observer visibility of Smuggler's Satchels and prevents them being detected by observer t-ray scanners.

## Why It's Good For The Game

Quoting arcane from the original PR adding these back in:
#42228
image

Hunting for them is fun. Now go hunt for them.

## Changelog
:cl:
tweak: Smuggler's Satchels are no longer visible to observers when stashed under tiles.
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
I think you just removed them being able to be hidden under tiles entirely.

**Comment by Qustinnus** [comment]
did you test this? You removed the element that makes it hidden, the visibility is a parameter

**Comment by Qustinnus** [comment]
pulled a little tivi didnt you 😏

**Comment by Timberpoes** [comment]
In 5 letters. Aaaaa.

**Comment by Timberpoes** [comment]
image

They all spawned, under tiles. ghosts couldn't see them, they were there.

**Comment by Sparkezel** [comment]
Can you also check with a Tray too?

**Comment by Tlaltecuhtli** [comment]
being visible to ghosts was an intended feature

**Comment by Barhandar** [comment]
Are they still visible on t-ray view? Also, please add tracking to see if _anyone ever_ uses smuggler's satchels for their "intended purpose".

**Comment by Timberpoes** [comment]
Round 3. Now visible in-game to t-rays, invisible to observer t-rays, invisible to observers.

**Comment by Timberpoes** [comment]
> 
> 
> being visible to ghosts was an intended feature

Well, I'm planning to change that. There exists exactly zero reasons for ghosts to be able to see them. You can still find them in-game with a t-ray scanner.

**Comment by FloranOtten** [comment]
> > being visible to ghosts was an intended feature
> 
> Well, I'm planning to change that. There exists exactly zero reasons for ghosts to be able to see them. You can still find them in-game with a t-ray scanner.

Why shouldn't they be? It's a neat thing to see. Check out what's in the satchels this round. Ghosts cannot actually explore for them.

**Comment by Iatots** [comment]
How does this fix anything? Nobody needs discord buddies to scout for satchels, they are plentiful and easily found. 
The latter point is the real problem: you can't do actual smuggling if any random asshat with a t-ray can pass by and get to your dead drop; It's a gimmick item.

**Comment by Timberpoes** [comment]
> Ghosts cannot actually explore for them.

and

> How does this fix anything? Nobody needs discord buddies to scout for satchels, they are plentiful and easily found.

Whaaaaat? If you die for even 30 seconds you can basically scout every satchel present in every major part of the station.

> The latter point is the real problem: you can't do actual smuggling if any random asshat with a t-ray can pass by and get to your dead drop; It's a gimmick item.

Yes. One that's a bit easier to use if you happen upon one (or find it yourself using a t-ray scanner) and one that observers should definitely not be seeing. And if you tell me in response that observers should see everything, I'm going to have to disagree. Some secrets even observers shouldn't know about.

**Comment by Iatots** [comment]
Wow some cigs and maintpills. Gamechangers.

**Comment by FloranOtten** [comment]
What I meant by "Observers cannot explore for them" was "If you remove this, there would be absolutely no way for an observer to see them". Why should they be hidden? Please inform me of the flood of people metacomming to find.... Happy pills. Or cigarettes. We removed all the good loot. Nobody is metagaming to find these.

**Comment by Timberpoes** [comment]
After discussions in both here and the coding discord channel, I've decided that this probably isn't going to form part of the solution to the problem I want to address - Or at least, that the possible benefits of observers having knowledge outweigh the various risks when they carry that knowledge with them when later joining the round (on-station ghost roles, midround antags, etc) or rejoining the round (revival)

**Pull request closed without merging**
