### PR TITLE
Nerfs floor dirtyness

### PR DESCRIPTION
**Pull request by ghost**
- Tiles need a dirt value of 100 (100 times people walk on the tile) before the dirt even begins to appear (previous was 30)
- Starts much harder to see now
- Fades even slower the more people walk on the tile
- Has a lower threshhold so at maximum it's not as dark as the roundstart dirt

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Or we could just cut this entirely and not waste processing power keeping track of dirt on every single tile

**Comment by pudl** [comment]
people will complain about dirt until it comes to a point where the code is there but dirt never appears because it takes like 500 times to make it appear
please just cut this

**Comment by paprka** [comment]
"people will complain about dirt until it comes to a point where janitors do their jobs again"

Exactly, just like the vending machine food nerfs.

**Comment by Steelpoint** [comment]
Or do it properly. Make dirt only track from dirty tiles like how blood can only appear from a body.

Maintenance tiles and any space exposed tiles accumulate dirt that can track dirt into the station, or make shoes dirty that will make tiles the user walks on dirty.

Currently its a case of a mess appearing out of thin air!

**Comment by Lo6a4evskiy** [comment]
> Currently its a case of a mess appearing out of thin air!

This isn't worth it. This method is simple and requires no computation.

Last time bay did footprints from blood pools (long ago) it was laggy as hell.

The only problem with it I currently have is that if 99 people take the same path (which is totally possible, considering we have 3 tile wide hallways, sometimes even 2 tile and people tend to run in straight lines), 100th person will leave behind a trail of dirt. That shouldn't happen. Make it random, with chance being zero until some point after which it increases with some polynomial order of growth.

**Comment by Perakp** [comment]
It should have a random threshold so entire paths don't get dirty at the same time, but individual tiles here and there.
If the feature is even worth the processing time.

**Comment by optimumtact** [comment]
If I see someone use wasting processing power as an argument with posting profile showing clear increase in CPU usage I will be very angry and disappointed in them and then badtalk them in IRC

**Comment by Steelpoint** [comment]
Then argue its merits, paprika never gave a good explanation in the original PR as to why this feature should be added to the game.

In my opinion, the station gets very dirty to begin with due to people dying very often. This feature simply adds more messes to the game for the sake of it, not for any practical purpose. It also does so in a arbitrary fashion that makes little logical sense.

Blood trails not only appear in a meaningful manner, from dead bodies or people bleeding, but also serve a practical purpose, such as telling you someone was dragging a corpse around a area, as well as to show signs of conflict.

Dirt/Dust trails have none of this, they appear without reasoning aside to show that people have walked on a certain tile a certain number of times and produce a mess that gives no real clue, idea, knowledge or benefit to anyone. If these trails were tracked from maintenance tiles then suddenly it has a legitimate purpose.

Until then, this is a unneeded feature that is searching for a purpose.

**Comment by paprka** [comment]
"Until then, this is a unneeded feature that is searching for a purpose."

The janitor cleans messes. This feature creates more messes without the need of people dying or getting hurt (blood).

Good enough?

**Comment by Steelpoint** [comment]
That's the core of the problem. Its a mess that is being created from people that have no intention of making a mess.

People throwing their food, or hitting something, or throwing their rubbish or any other task creates a mess, this is doing it actively and is good. Whereas people walking around is a passive action that creates a very large mess, even worse than people dying, this is bad.

Firstly, there is no realistic reason as to why simply walking would generate dust/dirt in such a large amount in such short time. Dust takes weeks to accumulate, and activity actually stop dust from accumulating. In addition we can assume that we have a active life support system that may very well eliminate dust.

Secondly, there is little game play reason as to why this exists. Yes it does create a mess for the Janitor to clean, but its a unnecessary one that distracts from actual messes such as blood, vomit, oil or food. It creates messes all over the station to the point where there's no point in the Janitor existing as its too much and you may as well buy a roomba.

**Comment by paprka** [comment]
That isn't the core of the problem, the core of the problem is that it happens too frequently for our already underplayed janitor slot to keep up with on the servers, so I'm nerfing it. What you're describing is your own personal logic leaps you're taking over dirt overlays for no reason other than the fact that you want this to be some needlessly complex feature when it's rather simple and harmless as it stands, just more stuff for the janitor to do. The janitor's job is effectively determined by 2 things:

Roundstart RNG placement of messes
RNG lights being blown out
People being hurt or corpses being dragged

There's nothing dynamic about this at all. Dirt in high traffic areas is dynamic and doesn't rely on RNG. This has nothing to do with deep complex logic behind !!!FUCKING DIRT ON FLOORS!!! or how it doesn't help security(seriously steelpoint?).

**Comment by Jalleo** [comment]
Maybe once this is in there will be a actual effort for people to make things and to have new ideas of stuff that can HELP THE JANITOR!

There are cleanbots have they started to be used more?
There is the new bot control will this make sure cleaning is done at the right areas?
There are orderable crates of janitor stuff will this encourage ordering more?
There are possibly times of when only one or two people are dead for a certain amount of time.

Gameplay beats realism on this point stop trying to be realistic with dirt or should we replace dirt with poo and say this is where your food once eaten goes?!?!?!??!?!

**Comment by Steelpoint** [comment]
Try walking around in a circle and see how long it takes for dirt/dust to start appearing beneath you. Little tip, it won't happen.

At least having dirt be trackable from a actual dirty tile makes some sense.

I'll just finish by saying this is a dumb feature, making the station completely overrun with dirt just for the sake of it. Not to mention this will just be getting nerfed and nerfed until the code is just a waste of space as its never used.

**Comment by Jalleo** [comment]
@Steelpoint 
what about all the eating we have in game you need to constantly eat now do you constantly eat in real life stop complaining ITS A GAME!

**Comment by Jalleo** [comment]
@Miauw62 or any other contributor please lock this PR to contributor and author only this is only going to get worse.

**Comment by Jalleo** [comment]
I do agree that it does get bad though but complaining wont solve it seriously this is the sort of issue which upping the number or complaning about how it should be in a certain manner wont solve it.

**Comment by tedward1337** [comment]
Lets just cut this. Dirt doesnt seem to make any sense, other then say, on the mining outposts. Even then it'd take a while to accumulate.

**Comment by AnonymousNow** [comment]
I'd say cut it. It's interesting, I guess, but in the end it just causes more mess and grief.

**Comment by Iamgoofball** [comment]
We should all step back and think about how the janitor was the punishment job that got added for people who got banned from every other job

**Comment by paprka** [comment]
Why would it need to remain that way?

**Comment by Jalleo** [comment]
@Iamgoofball the new punishment job is permabanned.

**Comment by paprka** [comment]
Why hasn't this been merged yet

**Comment by ACCount12** [comment]
Because it needs to be removed, not nerfed.

**Comment by paprka** [comment]
This PR isn't mutually exclusive you fucktard

**Comment by Iamgoofball** [comment]
this hasn't been merged yet because this is the current comment approval ratio, 
approve | disapprove | neutral
1|7|0

**Comment by paprka** [comment]
>comment approval = whether something gets merged or not

really goofball you've been doing /tg/ for how long and you still think that's the case?

**Comment by paprka** [comment]
shitpost*

**Comment by Iamgoofball** [comment]
pot calling kettle black

**Comment by hornygranny** [comment]
@paprka could you put some kind of RNG into it so only some tiles will be dirty

**Comment by Niknakflak** [comment]
I personally support #6793

**Comment by paprka** [comment]
@hornygranny Yeah I can do a simple prob for adding to the dirt var

**Comment by paprka** [comment]
@hornygranny  ^

**Pull request merged**
