### PR TITLE
Fixes SSU's entering a broken state when their maintenace panel is open at the end of a decontamination cycle.

### LINKED ISSUE #45036: Screwing open a Suit storage unit while it's decontaminating breaks it
If the panel is still open and it's finished decontaminating, the storage unit automatically opens and trying to screw it close would attempt putting it in the auxiliary storage. effectively making you unable to screw it closed and trying to get whatever is inside the suit storage.

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #45036

:cl: ShizCalev
fix: Suit storage units can no longer have their maintenance panel opened while running a decontamination sequence, causing the machine to enter a broken state.
/:cl:

Also added documentation for all the vars.

### CODE REVIEW

**Comment by TerraGS** [comment]
I hear people who add documentation are incredibly good looking.

**Comment by ShizCalev** [comment]
@optimumtact / @JJRcop would `//!` be correct to do this instead then?

**Comment by JJRcop** [comment]
`//!` is correct for that use.

**Comment by optimumtact** [comment]
I don't think that's quite right

I have a feeling they go to the module level code docs instead of decorating the actual item

@SpaceManiac can you confirm?

**Comment by SpaceManiac** [comment]
`//!` is supposed to work same-line for vars, but is bugged in dmdoc. Prefer `///` or `/**` on preceding line for now. I'll try to better document what works and what doesn't.

**Pull request merged**
