### PR TITLE
components' pipes now show on plating

### LINKED ISSUE #11174: pumps secured to untiled floor dont show a pipe just the pump element.
doesn't affect  pipe performance far as i can tell. visual glitch.

### PR DESCRIPTION
**Pull request by duncathan**
Fixes #11174

### CODE REVIEW

**Comment by duncathan** [comment]
Holy fuck what conflicts with this jesus christ

**Comment by duncathan** [comment]
>mfw I forget to pull before committing

**Comment by WJohn** [comment]
Literally what is this??????

**Comment by duncathan** [comment]
Holy FUCK git

**Pull request closed without merging**
