### PR TITLE
Fixes some inconsistencies in genetics

### PR DESCRIPTION
**Pull request by Time-Green**
Adds chromosome interactions to a few mutations that should have it, but were simply not added.
Makes upgraded parts affect printing speed. Every tier decreases cooldown by 10%
Kind of off-topic, but fixes a runtime I caused when adding unique icons for species eyes
:cl: Time-Green
tweak: Chromosomes interact with more mutations
tweak: The DNA console printing speed is now affected by better parts
fix: Monkeys no longer runtime with transformations
/:cl:

I'd say no PRB since theyre my fault, but I'm not even sure if it would go up or go down

### CODE REVIEW

**Comment by knacker48** [comment]
How does this effect something like spatial instability? Does it just remove  the nausea or does it give you more control of the teleporting?

**Comment by ATH1909** [comment]
Wait, does this also fix the "moths are flashproof" bug?

**Comment by Time-Green** [comment]
Spatial stability can gave the power chromosome for a bigger range, synchronizer for less disgust and energy for less time between teleportation

**Comment by Time-Green** [comment]
@ATH1909 probably not. On transforming into a monkey or from, eye icon generation would be called by an old handle body call and runtime, thats it

**Pull request merged**
