### PR TITLE
Fixes infinite rods from reinforced floors

### LINKED ISSUE #9143: you can deconstruct a reinforced floor multiple times to get free metal rods
Construct/find a reinforced floor, then click it multiple times with a wrench. This will start multiple deconstruction attempts which will all produce metal rods.

### PR DESCRIPTION
**Pull request by Firecage**
As it says on the tin. This fixes the issue of getting infinite amount of metal rods when deconstructing a reinforced floor.

Fixes #9143

### CODE REVIEW

**Comment by optimumtact** [comment]
Wat the fuck is going on here?

**Comment by Firecage** [comment]
@optimumtact Well, you were able to get an infinite amount of metal rods when deconstructing a reinforced floor by spamming the wrench on it. This fixes it so it only gives you the rods you would normally get.

**Comment by optimumtact** [comment]
Did you try using the target option of the do_after call?
it checks to ensure target still exists and the loc hasn't changed

you'd want to do do_after(mob, blah blah, target=src)

**Comment by optimumtact** [comment]
I have a feeling it wouldn't work with turfs, which do special magic shit in the background

**Comment by Firecage** [comment]
Optimum...I tested this...it works, as intended.

**Comment by optimumtact** [comment]
I didn't mean your code, I meant the target option for do_after

could you please still test it? since it's much cleaner than the iftype check

**Comment by Firecage** [comment]
Ugh, I will do so tomorrow. Already 12:30 AM now.

**Comment by xxalpha** [comment]
Did you try simply if(src) ? I think turf changing changes the references, so src wouldn't be the same as the new turf. I might be wrong though.

**Comment by kingofkosmos** [comment]
I tried the target=src, didn't work with this one.

**Comment by phil235** [comment]
The target argument doesn't work because the original turf is never deleted or moved, it's just changed into plating.

**Pull request merged**
