### PR TITLE
Drink spilling and beaker feeding

### PR DESCRIPTION
**Pull request by kingofkosmos**
Made beakers and drinking glasses much more consistent with each other.

Before you could only splash with a beaker and drink/feed from a drinking glass.

**Now both drinking glasses and beakers can do the following:**
- Feed someone.
- Have a drink.
- Splash on someone (harm-intent).
- Splash on yourself (harm-intent).
- Splash on most things (harm-intent).

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1: x :100:

**Comment by WJohn** [comment]
Is this all intent based?

**Comment by PKPenguin321** [comment]
ohoho finally, this is such a strange quirk in this game and i'm glad to see it changed

**Comment by kingofkosmos** [comment]
Oh that's right, it's done by intent. Harm-intent = splashing. Updated the op.

**Comment by Lumipharon** [comment]
Nice.

**Comment by kingofkosmos** [comment]
Conflicts hopefully ok. Ready for merge by me.

**Comment by freerealestate** [comment]
:+1:

**Comment by Kromgar** [comment]
Can we make drinking polytrinic making you incapable of speaking due to burning your throat out?

**Pull request merged**
