### PR TITLE
Adds slime management consoles to boxstation

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Ixenobio

And an airless chamber to freeze slimes in.

### CODE REVIEW

**Comment by Bluespace** [comment]
yesssss

**Comment by Razharas** [comment]
This airless chamber will become aired fast enough
Put some flaps there to space or something grill maybe

**Comment by Bluespace** [comment]
You could just put space there. Slimes can survive for a pretty long time in the cold when they're not directly on a space tile.

**Comment by KorPhaeron** [comment]
I do the map merge process again when editing my edit, right?

**Comment by Anonus** [comment]
Yup.

**Comment by Bluespace** [comment]
PS: Monkey recycling doesn't delete the monkey when you recycle it. http://puu.sh/l5EMy/44d064774c.png

**Comment by KorPhaeron** [comment]
Aaaa

**Comment by Bluespace** [comment]
Okay monkeys are fixed and there's no conflicts so I shall go mergebeg for you.

**Comment by RemieRichards** [comment]
@Bluespace the pr is 4 hours old, it can't be mergebegged.

**Comment by Bluespace** [comment]
i want my xenobiology computer and chill room

**Comment by KorPhaeron** [comment]
Whoops

**Comment by Fallcon** [comment]
yessssss oh god yesssssssssss

**Pull request merged**
