### PR TITLE
Misc Tram Fixes

### LINKED ISSUE #74212: Tramstation Robotics' desk is missing a privacy shutter
Reporting client version: 514.1589

## Round ID:
[202394](https://scrubby.melonmesa.com/round/202394)

## Testmerges:
- [New Cosmic Heretic Path DLC](https://www.github.com/tgstation/tgstation/pull/73915)

## Reproduction:
The privacy shutters is missing a piece of the shutters, for the desk part of the spot.
Screenshot 2023-03-23 225600

### LINKED ISSUE #74348: Tram Issues 3in1
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:

- Hop office has no cams
- Escapepod Hall has no cams
- Vault is not connected to Power and Pipesystem (Upper and Below Pics)
Screenshot_1
Screenshot_3

### PR DESCRIPTION
**Pull request by Singul0**
## About The Pull Request
fixes #74212
fixes #74348

Added cameras in HoP office and escape pod bay, added missing privacy shutter and connected piping and wiring in vault to the rest of the station.

Image:
gambar

### Mapping March
Ckey to receive rewards: humanlike

## Why It's Good For The Game
Bugfix good! :)
## Changelog
:cl:
fix: AI's now can see into the HoP Office and Pod bay.
fix: Vault piping and wiring is now connected to the station.
/:cl:

### CODE REVIEW

**Review by Maurukas — CHANGES_REQUESTED** [review]
The lower set of multi-z pipe and multi-z wire connectors are not connected to anything, please remove them and adjust the tile decals:
image

**Comment by Singul0** [comment]
Fixed. another PR probably fixed that issue without telling anyone about it.. also added stripes in the tile containing the z-level connectors to help engineers find it.

**Comment by ZephyrTFA** [comment]
I think a merge to master didn't go correctly,  there are a few changes I don't believe you intended, such as a change to the science security outpost

**Comment by ZephyrTFA** [comment]
Nah, I'm just blind

**Pull request merged**
