### PR TITLE
Buffed IEDS

### PR DESCRIPTION
**Pull request by Buggy123**
I've never seen anyone use them, and everyone says that they are terrible.

If this buff is too much, I'm open to suggestions, but at the moment they're essentially useless.

:cl:
tweak: Buffed IEDS. They now have a small explosion capable of destroying things.
/:cl:

### CODE REVIEW

**Comment by Zilenan91** [comment]
Thank you, no longer can I make an explosive that can detonate in my hand and do absolutely nothing.

**Comment by Jordie0608** [comment]
Needs a changelog

**Comment by ike709** [comment]
>trying to commit a changelog instead of adding it to the end of the PR post like all the cool kids

**Comment by PKPenguin321** [comment]
Changelogs don't have to be done through code

https://tgstation13.org/phpBB/viewtopic.php?f=5&t=5157

**Comment by Buggy123** [comment]
:cl:
tweak: Buffed IEDS. They now have a small explosion capable of destroying things.
:cl:

**Comment by WJohn** [comment]
Thank you. They're now not completely useless.

**Comment by tkdrg** [comment]
:-1: There was a reason these were nerfed into the ground, and it was because they were absolute cancer with greytiders breaking the brig's windows every single round and then crying on ahelp because "waah if I'm not supposed to use it why can I make it". Giving everyone easy access to explosives is just a recipe to disaster in general. The entire point of the nerf was keeping them from breaking things, and now we get this buff that make them even stronger than they originally were, before Malk nerfed them at #3856. Seriously, this is a bad idea. We tried it out, it didn't work.

Also, I think the changelog has to go in the OP. Not sure, though.

**Comment by MMMiracles** [comment]
@tkdrg then ban those stupid enough to abuse it and complain. the IED as it currently stands is not even remotely worth making. There is not a single situation where an IED has any potential to not worthless because of the nerf. 

buff it so those dumb enough to grief with it can get banned. one less shutter on the server everyone wins.

**Comment by tkdrg** [comment]
There is literally no reason to give high-grade explosives to non-antag assistants. If IEDs are worthless, just remove them. The fact that one item is bad is no excuse to make it a free griffbomb. I repeat, these are pretty much completely useless for anything that isn't griff. There is no reason to have those around.

**Comment by MMMiracles** [comment]
The worst the did was bust windows and occasionally break wiring. Most griefers used it to break APCs or, as you said, the brig windows. They served a purpose of being a low-grade explosive that could potentially actually do something or just blow up in your hands. 

If it isn't going to be buffed then it might as well be removed because as it stands it's literally useless.

**Comment by WJohn** [comment]
Agreed with mmmiracles there, you don't realize how useless they are until you try them. It can at best make a 3 tile wide puff of flames that instantly vanish, *maybe* setting one person on fire if you're very lucky. At worst, the explosion is so small no fire is made at all. Keep in mind that the only damage they can actually do is set you on fire (and rarely even then). Standing right on top of the lit IED as it explodes won't do any brute. It is pathetic.

**Comment by tkdrg** [comment]
Yes, they are useless right now. I am not saying that they aren't. I'm saying that buffing them is stupid because giving everyone access to explosives is a recipe for disaster.

**Comment by MMMiracles** [comment]
Why don't we actually get rid of the people who apparently only exist in these scenarios to abuse things instead of working around them?

**Comment by Durkel** [comment]
Old Ieds were annoying, I remember people using them to cheese malf by blowing its apc with them, on the other hand they useless right now. I'd rather see them buffed and the shitters removed then have them continue to be useless.

**Comment by tkdrg** [comment]
I'd rather see them gone forever than buffed.

**Comment by Zilenan91** [comment]
IEDs have a use in gameplay that I feel will be something everyone will like.

**Comment by Fox-McCloud** [comment]
This will literally punch holes in the floor you're lucky--not only that, but in some cases it'll do close to ~100 damage to someone, knock them out, AND set them on fire.

Something that can be spam-made like no tomorrow by anyone shouldn't be a lucky one-shot.

**Comment by PKPenguin321** [comment]
Yeah, if you're going to buff these, the max you should buff them is to their pre-nerf levels. This is a little bit silly.

**Comment by Buggy123** [comment]
I reduced the buff, it can't blow holes into space now.

**Comment by Supermichael777** [comment]
Now seems too weak, maybe make it -1,-1,3. A decent area denial explosion with a some knockdown power, remember that explosion range counts the tile the weapon detonates in as tile 1 so that value will literally only cause knockdown if someone is standing on it.

**Comment by Zilenan91** [comment]
What's the second value again?

**Comment by tkdrg** [comment]
Still a :-1: as far as I'm concerned. Seriously, we've tried this, it didn't work.

**Comment by CPTANT** [comment]
pfff, they were fine before the nerf. Yes some assholes blew up brig windows, but you can just close the shutters or beat their ass.

**Comment by Zilenan91** [comment]
Back before they were nerfed was also a much different time. We don't have greytide nearly as bad as we did back then.

**Comment by Buggy123** [comment]
Buffed a little as Supermichael777 suggested.

**Comment by phil235** [comment]
One of the reason why we nerfed IEDs is that it breaks wires and pipes underneath floor tiles, making it a good grief tool.

**Comment by Fox-McCloud** [comment]
Why not just keep the flame range consistent and remove the random detonation time? an IED that you can cook properly and cause a consistent flame range would, indeed, be buffed, but wouldn't go around popping everything either.

**Comment by Nanotransistor** [comment]
:+1: And as MMMiracles said, if some greyshit tosses an IED to the brig, you laser them. It sucks we lose so much fun stuff because some people either dislike to die or really like to griff.

**Comment by optimumtact** [comment]
We can see how it goes I guess, but this will require a tougher admin stance on their use

**Comment by tkdrg** [comment]
Seriously, no. They were bad back then, they were removed, the game is fine without them. I'm just closing this. Feel free to bring it up with another maintainer or headcoder if you disagree.

**Comment by Zilenan91** [comment]
Tk, like I said above the game was a much different place than it is now. Back then, we had a server that got up to 150 people at peak, and along with the /v/ raids it was hard to find a round without greytiding. 

Nowadays? It's hard to find a round with greytiding, and for admins all they'd have to do is see the explosion, see the fingerprints on the explosion, and just ban the guy in a two second process, we didn't have those tools back then.

**Comment by duncathan** [comment]
I'll reopen if you only put them back to the point they were at pre-nerf, no more. I won't merge it tho; you'll have to convince another maintainer fit that.

**Pull request closed without merging**
