### PR TITLE
Removed Amber ERT's thermals

### PR DESCRIPTION
**Pull request by Robustin**
Takes away the Amber ERT commander's thermals and gives them ordinary HUDglasses.

Code Red still has them, send those guys if you want to ruin an antag's day. 

:cl: Robustin
del: Amber ERT Commanders no longer have thermal goggles 
/:cl:

### CODE REVIEW

**Comment by Saegrimr** [comment]
i ded tag

**Comment by Robustin** [comment]
Literally made this in response to the same complaint that convinced Kor to try and remove HIJACK.

**Comment by Bawhoppen** [comment]
atleast give him HUD eyepatch

**Comment by KorPhaeron** [comment]
An all access squad of seven tactical space marines with eguns, shields, a revolver/esword, medigun, and fucking nanites will still be stupid unfun unless they're responding to something absurd like a ling with sleeping carp.

Amber ERT is just kind of in a shitty niche in general where they steamroll "normal" threats but run out of ammo and die horribly against anything that'd actually warrant an ERT

**Comment by Shapsy** [comment]
7 man is almost always complete overkill, 3-4 man isn't that bad

**Pull request merged**
