### PR TITLE
Adds Chameleon Armor to the uplink

### PR DESCRIPTION
**Pull request by dawsonkeyes**
### About The Pull Request
Ever been lacking in armor as a tater tot? Wished you could be a strong boy against security without being blatantly obvious? Behold the brand new _chameleon armor!_ This vest and helmet sport chameleon appearance-changing tech but also protect as much as a blood red hardsuit does, with all the subtlety you love. It costs the same as the Hardsuit (**8 telecrystals**), and trades off the space protection granted by it for the chameleon ability to appear as whatever the hell you want it to.

### Why It's Good For The Game
Similarly expensive protection but with the caveat of being extra stelthy and not spaceproof.

### Changelog
🆑
add: chameleon armor kit
/🆑

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
chameleon items are already armored tho

**Comment by dawsonkeyes** [comment]
> chameleon items are already armored tho

The standard is (MELEE = 10, BULLET = 10, LASER = 10, ENERGY = 0, BOMB = 0, BIO = 0, RAD = 0, FIRE = 50, ACID = 50)
so, not that armored at all in comparison

**Comment by optimumtact** [comment]
terrible idea, webedits and a massively negative GBP, classic.

**Comment by Timberpoes** [comment]
As a philosophy we have tried to push away from "hidden" armor values where reasonable.

Sometimes we give allowances for fashion and style, such as the HoS beret having very similar armor value to security helmets. These are the kinds of exceptions that allow players to express themselves visually without falling behind powergamers who pick whatever has the best stats.

Chameleon equipment has nothing of this character. It's intended to allow a player to totally disguise themselves. It is not intended as a "go loud" armor.

Looking like you're unarmored but actually having hardsuit level protection is something I have no intent of unleashing on players.

If you want protection, order gear that protects you. If you want a disguise, order gear that disguises you. If you want both, make a choice or other both and swap between them as necessary.

**Pull request closed without merging**
