### PR TITLE
ANTAG FREEZE, ANTAG FREEZE ABOVE THIS LINE

### PR DESCRIPTION
**Pull request by optimumtact**
After some discussion, I have enacted a gamemode and antag items/roles freeze

This should not come as a surprise, given that I have been talking publicly about the issue with the lack of crew content for some time, use this time to focus on crew content, job content and if you're very bold, perhaps a new job.

If you need inspiration, see this thread: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=23614

Key info

WHEN: NOW

HOW LONG: a minimum of 1 month, this will almost certainly be extended.

WHY: we want to encourage a focus on crew content and job content for standard crew

Note that maintainers can still greenlight an antag rebalance or change if they feel it's necessary at any time to protect the server or health of the community.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Question: Is adding sabotage-able content to the crew considered traitor shit? IE content with legit uses that could also be weaponized maliciously

**Comment by optimumtact** [comment]
only if it's the primary purpose

**Comment by MCterra10** [comment]
Based

**Comment by cacogen** [comment]
can i fix a bug with chameleon id cards

**Comment by wesoda25** [comment]
wait wtf theres no way this includes bug fixes

**Comment by ExcessiveUseOfCobblestone** [comment]
True Bug Fix : OK
Elevating bugfix into new feature: Need Approval

**Comment by Fhaxaris** [comment]
merge when

**Comment by Timonkeyn** [comment]
speedmerge dis

**Comment by PKPenguin321** [comment]
This freeze isn't working. Too much shit is antag stuff that technically is just barely accessible as a non antag so you can technically change it. The goal of this freeze isn't being reached at all, kind of a let down

**Comment by optimumtact** [comment]
whatever you say bitch

**Comment by PKPenguin321** [comment]
wow, reported....

**Comment by PepperPrepper** [comment]
@optimumtact  Do you currently have a set date for this to end or are you just going to let it run until we have gotten enough crew content?

**Comment by optimumtact** [comment]
there is no set date, and so far people haven't added much crew content

**Comment by Fikou** [comment]
hi oranges can i be an issue janitor

**Comment by Buggy123** [comment]
It's over. It's done.

**Comment by LemonInTheDark** [comment]
5 months of cold, over at last.

**Comment by tralezab** [comment]
strut

**Comment by cacogen** [comment]
Has it really been that long

**Pull request closed without merging**
