### PR TITLE
No ID insertion for everything except the hop console (fixes the ORM)

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request
machines and consoles that previously required an inserted ID now check access on worn and inhand ids. They otherwise function identically.
Affected things:
ORM: click claim to claim cash to connected ID (also fixes it)
Mining vendor: uses ID on person or in hand.
medical console: checks worn ID
security records console: checks worn ID
gulag consoles: claim points to worn ID, checks access and point requirements from worn ID

Also some backend refactoring to prisoner management and gulag teleporter consoles

hop console will be next to strip out the shitcode entirely but this at least gets things functional in the mean time, but fully tested this time. It's very late here and I need to sleep. Due to the nature of it it's more elaborate of a rework.

## Changelog
:cl:
tweak: Medical and Security consoles now check access on worn or inhand ID instead of requiring an inserted ID
tweak: mining vendor now reads from ID in hand or on person instead of requiring an inserted ID
fix: ORM is functional again (for real this time)
tweak: ORM claim points button transfers points to worn/inhand ID instead of to an inserted ID, no longer accepts insertions
tweak: Same for gulag consoles
/:cl:

### CODE REVIEW

**Comment by AarontheIdiot** [comment]
speedmerge pls

**Comment by terranaut1** [comment]
please dont fix the hop console, finding (or in some cases deliberately leaving) an ID there is always a gem
good stuff otherwise though

**Comment by actioninja** [comment]
The planned change here will make sure that accidentally/intentionally leaving it logged on stays something that can happen. It will have A gameplay effect but mostly just that the id card can't be nabbed out of it while the hop is still there.

**Comment by PKPenguin321** [comment]
Would like it if you could still insert IDs into sec/med consoles in addition to being able to just have them on you

**Comment by actioninja** [comment]
Why?

**Comment by Fhaxaris** [comment]
amazing qol change

**Comment by PKPenguin321** [comment]
Hiding IDs, catching foolish officers with their pants down when they forget their ID

**Comment by zerk72** [comment]
What about the mining vendors?

**Comment by bgobandit** [comment]
merge please I am tired of handling 500 identical ahelps a day

**Comment by actioninja** [comment]
every change in this has been tested and this is ready to go.

**Comment by Kingtrin** [comment]
based ninja

**Pull request merged**
