### PR TITLE
makes clowns unable to drop/take off their honorable clothing

### PR DESCRIPTION
**Pull request by ghost**
🆑 awesine
balance: clowns can no longer take off their sacred clothing
/🆑

[why]: >clowns taking off their shoes

i have no idea if this would actually work, i stole no_drop_1 from hippies ka-nada

ignore the first 2 commits github is being a lil bitch

### CODE REVIEW

**Comment by kevinz000** [comment]
aren't you permabanned?

**Comment by awesine** [comment]
mrty is permabanned but he still codes

**Comment by awesine** [comment]
oh it doesnt compile

**Comment by kevinz000** [comment]
least mrty does useful things instead of /always/ trying to change balance when they don't play here.

**Comment by awesine** [comment]
>implying makes clown clothing unable to be taken off isnt a good thing

**Pull request closed without merging**
