### PR TITLE
Fixes Jaws of Life being unbuildable

### PR DESCRIPTION
**Pull request by XDTM**
They did not appear in any protolathe list.

### CODE REVIEW

**Comment by kevinz000** [comment]
It's build able just have to type search but not in categories.

**Comment by ExcessiveUseOfCobblestone** [comment]
are you saying there's a SECRET PROTOLATHE RECIPE???!?!?!??

**Comment by XDTM** [comment]
oh boy we need more SECRET PROTOLATHE RECIPES for experienced R&Ders

**Comment by ExcessiveUseOfCobblestone** [comment]
mekhi: *heavy breathing*

**Pull request merged**
