### PR TITLE
Adds Moisture potential for Cytology to the places a player immediately thinks of when they hear "moisture trap".

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
See title.

## Why It's Good For The Game

I got extremely confused about where to find moisture as per what the wiki said until I code dived.

## Changelog

:cl:
qol: More things provide moisture swabs for Cytology.
/:cl:

### CODE REVIEW

**Comment by Krysonism** [comment]
No meta spawns please. This subverts the goal of forcing players to search and find samples.

If a player can beeline to the toilets or build toilets to infinitely reroll the sample, cytologists can just stay near xenobio, which is what we want to get away from.

I can tell you a way to do this in a better way on discord.

**Comment by wesoda25** [comment]
Also can you make changelog more detailed?

**Comment by AlinaStarkova** [comment]
> No meta spawns please. This subverts the goal of forcing players to search and find samples.
> 
> If a player can beeline to the toilets or build toilets to infinitely reroll the sample, cytologists can just stay near xenobio, which is what we want to get away from.
> 
> I can tell you a way to do this in a better way on discord.

just make it give a random chance to spawn a moisture spot in any pre-mapped toilets and showers. built ones in game are "brand new and not used" and hence wont ever give one. so a cytologist still has to actually search spots around the station

**Comment by Iamgoofball** [comment]
I can hide it behind mapload spots only, yeah.

**Comment by nianjiilical** [comment]
add moisture cell lines to the bedsheets exclusively in dorms 4

**Comment by Watermelon914** [comment]
> I can hide it behind mapload spots only, yeah.
> 
> My beef here is that I spent an extremely long time swabbing a bunch of stuff that sounded gross and holds moisture like the game and wiki says to do, only to code dive and find that only 1 item in the game has Moisture and it's a literal random maint spawn. I combed the entirety of Box and did not find a single moisture trap once.

once you do this, undraft the pr

**Comment by Krysonism** [comment]
This is still totally unacceptable to me. 

It creates a foolproof meta location where you can collect a large number of sample.

It goes against the how the entire feature is designed and balanced.

**Comment by Watermelon914** [comment]
see above

**Comment by AlinaStarkova** [comment]
> This is still totally unacceptable to me. 
> 
> It creates a foolproof meta location where you can collect a large number of sample.
> 
> It goes against the how the entire feature is designed and balanced.

if it's only a random chance, say 5% of anything spawning at a roundstart toilet, then no, its not a "meta location". its still a chance. the problem is that currently too little things give samples to the point where you can have rounds where quite literally, absolutely nothing gives a sample, aka, impossible to do cytology

**Pull request closed without merging**
