### PR TITLE
Security: (Nonlethal) Katana Edition

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Nanontrasen, in it's infinite wisdom, has chosen to utilize the power of cryokinetic weaponry as a form of self-defense for all security members aboard Spacestation 13. As such, the stun baton is being shelved for the time being for the brand new Security Cryokatana!

Screenshot 2020-03-06 12 50 14
Screenshot 2020-03-06 14 13 31
Screenshot 2020-03-06 16 21 02

This brand new and definitely legal weapon comes with a number of lovely features, including;
A) Slicing action with a hefty 15 force! (dismemberments are workplace accidents)
B) Some limited block potential, but it won't save you from bullets.
C) It works basically like a baton except not! Switch it on for cold! It does 25 stamina damage and freezes the person you hit!
D) Induced freezing with every cut! Cryoxodrone buff? Lizard nerf? You decide!
E) Sword fights?!

All members of security spawn with these katanas on their belts, including the Head of Security, who gets an extra special robust version.

So as to not make the captain feel especially left out, his sabre is now 22 force. God forbid someone sharpens it.

And if you really want a stun baton I'm leaving them in cargo for now. Because then at least cargo has some reason to be providing equipment to security. I suppose.

Additionally, beepsky is now constructed with a cattleprod, and the cattleprod itself has been significantly nerfed. As have oztek boomerangs.

## Why It's Good For The Game

Stun batons are more powerful than any other melee weapon around. It wouldn't matter if it's lethal damage or stamina damage, it's a two-hit victory. Given multi-batoning (the act of bypassing the baton's inherent cooldown by using a second stun baton not on cooldown for instant stamina crit) has been discovered and any solution to that I felt would be a shitty copout, I've opted to instead go with the hard removal of stun batons as standard security equipment.

Why katanas? Because swords are cool. That's....really it actually. Also lethal self defense option. If you want to bring someone in, then you have a variety of useful security tools. If none of these work, you now have your katana to fall back on.

An unfortunate consequence of all this is now security has belt real estate that they need to juggle. Not much that can be done there. Either you want you webbing, your belts or your sword. Pack appropriately. It's not like you can't just carry belts in your bag if you really need all that extra gear.

## Changelog
:cl: NecromancerAnne
add: Security Cryokatanas! Your new (non)lethal self defense tool!
del: Removed batons from all security lockers and their spawned equipment
tweak: Beepsky is now constructed using a cattleprod.
balance: Some adjustments to the remaining batons readily available, including Oztek Boomerangs and Cattleprods. They are now far weaker as melee weapons.
/:cl:

### CODE REVIEW

**Comment by Jordie0608** [comment]
Capture
Tempting

**Comment by PKPenguin321** [comment]
This is like the "give sec glocks" meme but unironic and with swords. Most confusing thing I've seen today

**Comment by Fikou** [comment]
i thought my idea of just giving them bootknives was crazy

**Comment by SkeletalElite** [comment]
Thought this was gonna be a security buff of some sort.
Nope. It just shits all over security. Security will have no good melee anymore.

**Comment by TheVekter** [comment]
_**RULES OF NATURE**_

**Comment by bluetshirtguy** [comment]
you know, it'd be neat to see it test merged and what happens.

**Comment by Archanial** [comment]
Buff adrenals instead of removing batons.

**Comment by HomocidlePancakes** [comment]
April fools came early this year.

**Comment by HomocidlePancakes** [comment]
Also, mallcops with katanas ruins muh immersion.

**Comment by tralezab** [comment]
would like to see this tested!

**Comment by 81Denton** [comment]
*tips beret* heh... nothing personnel... greyshirt...

**Comment by trollbreeder** [comment]
Replace their disablers with a shitty self defense SNS pistol maybe?

**Comment by trollbreeder** [comment]
If you dont know what i'm referring to:
https://en.wikipedia.org/wiki/AMT_Backup

**Comment by gamefreak2998** [comment]
Cool pr, my advice for tweaks would be:
-Addition, not replacement (Preferably as mid tier sec research)
-Bit longer, add thicc curves to that nippon steel
-Additionally make it too big for bags but able to fit in vest inventory or on the back slot.
-Wakizashi's for when you disgrace yourself?

**Comment by gamefreak2998** [comment]
In general more sec gear based on fighting with cyro tools/countering it is awesome and I applaud the creativity

**Comment by necromanceranne** [comment]
When this inevitably gets closed I'm honestly unsure where I would want to put them. They don't quite work as cargo exclusives and iunno about BEPIS, it's not that outrageous for BEPIS tech. I'd say black market maybe?

**Comment by Victor239** [comment]
A removal like this is only going to lead to security murdering when trying to detain minor criminals. 

Suggested changes:
- Give it a non-lethal mode which does stamina damage only and a bit other freezing slowdown. Make it 4-hit stamina crit. 
- Nerf stunbatons to 3-hit attack stamina crit and leave this katana in security vendors or protolathe whilst batons still spawn in belts. 

Also if batons fit in secbelts/webbing so should the katana.

**Comment by PKPenguin321** [comment]
>When this inevitably gets closed

Baiting oranges with reverse psychology like this might actually tear the universe asunder, be careful

**Comment by necromanceranne** [comment]
honestly if I made them stamina swords I would almost definitely remove stun batons at that point. Stamina mode cryokatanas is starting to make this sound like a reasonably proposal though.

Unless...

**Comment by Fikou** [comment]
stunbatons - SOUL
cryokatanas - SOULLESS

**Comment by interestingusernam3** [comment]
This triggers the silicon.

**Comment by daklj** [comment]
would make more sense as a traitor item (in the freeze bundle perhaps?)

**Comment by Tlaltecuhtli** [comment]
cring

**Comment by Tharcoonvagh** [comment]
Another sec nerf, cool(haha)
Now your murderbone becomes even easier!

**Comment by nianjiilical** [comment]
the idea of a nonlethal cryo katana that subdued people by freezing them is extremely cool (pun not intended) and i hope it gets in in some way even if it doesnt replace batons

**Comment by necromanceranne** [comment]
Well...here you go, they're...basically stun batons but swords except not stun batons because they only do 25 stamina damage. So four hits will bring down anyone. 

I hope that helped this idea? I guess?

**Comment by necromanceranne** [comment]
Wait how did this break?

**Comment by gamefreak2998** [comment]
Imagine making this non lethal :(

**Comment by Ty-the-Smonk** [comment]
BULLSEYE

**Comment by Fikou** [comment]
i cannot take it anymore

**Comment by Mickyan** [comment]
Break into secure storage? That's a paddlin'

**Comment by Ty-the-Smonk** [comment]
S c u m

**Comment by Michael-Ashfield** [comment]
If it does 25 stamina, it will take around 4-5 hits to knock someone down. Why would I, as a sec officer, not just sit back comfortably and use my disabler which just needs 3-4 hits.
The advantage of the stun baton is that you just needed one hit, but risked getting in close to the criminal.

**Comment by trollbreeder** [comment]
Make it atleast 40 stamina damage. Then it's a 2 hit major fucked 3 hit stamcrit so it's better than the disabler atleast.

**Comment by anconfuzedrock** [comment]
Can we consider giving sec glocks again?

**Comment by Ty-the-Smonk** [comment]
> Make it atleast 40 stamina damage. Then it's a 2 hit major fucked 3 hit stamcrit so it's better than the disabler atleast.

Wasn't the point of the pr to give sec worse stun batons, this kinda just gives them a reskined baton, make it 30 at the most.

**Comment by Spepbuthewranglesgithub** [comment]
lacks that goon energy, should be emagable for more goon energy.


_also, are you trying to make security even more of a joke? weeb sticks that are even worse than a disabler AND can't be put in backpacks?_

**Comment by necromanceranne** [comment]
You fellas, all memed aside, you know that this weapon has no attack cooldown right? At 40 stamina force that makss it equal to the actual highest force weapon, which is a real katana.

**Comment by ATH1909** [comment]
> You fellas, all memed aside, you know that this weapon has no attack cooldown right? At 40 stamina force that makss it equal to the actual highest force weapon, which is a real katana.

And that's fine, because then people might actually opt to use one of these instead of just carrying around a second disabler.

Add these to hacked secvendors or something, but don't remove our current batons.

**Comment by ATH1909** [comment]
Am I gonna have to make an alternative PR that makes batons use click cooldowns instead of per-baton cooldowns?

**Comment by ATH1909** [comment]
Also, any PR that nerfs ozytek batonerangs automatically gets a downthumb from me, because those things are hilarious.

**Comment by necromanceranne** [comment]
ATHATH that suggestion comes with a stamina damage nerf right? You can't just take off the attack cooldown on stun batons without making them very powerful.

**Comment by ATH1909** [comment]
> ATHATH that suggestion comes with a stamina damage nerf right? You can't just take off the attack cooldown on stun batons without making them very powerful.

No, as in, they'd apply a click cooldown that's of the current cooldown length.

Cobby has a multi-batonning removal PR up anyway, let's just use that one instead of my idea.

**Comment by necromanceranne** [comment]
A click cooldown would be utterly dreadful in the first place because it would gimp using any other weapon alongside a baton. But yes, Cobby does have a wonderful fix up at the moment that resolves that issue.

**Comment by HomocidlePancakes** [comment]
You know, this even though this PR is silly, the idea of cryomachetes (they look like machetes, not katanas) was pretty neat, emphasis on was. Now it’s just a baton resprite? Necro, you are having a major sperg out right here. You’d be better off trying to implement them in some other way instead of whatever you are doing now.

**Comment by necromanceranne** [comment]
Hey man, that ain't cool. I'm having a lot of fun with this meme.

**Comment by necromanceranne** [comment]
That's fair. I'm going to reuse all these assets I have now (including a shocksword) and see what I can do with them.

**Pull request closed without merging**
