### PR TITLE
Gives drones engineering skillchip and access to a few more items

### PR DESCRIPTION
**Pull request by robotduinomm**
## About The Pull Request
 Gives drones the ability to see what wires do what. (engineering skillchip)
Adds new items to drone whitelist.
> rack parts
> stack of duct
> box of replacement lights and it's subtypes (tube, bulb, mixed)
> light replacers (bluespace one included)

## Why It's Good For The Game
It 's now easier for drones to repair hacked airlocks, broken lights and build showers/sinks.

## Changelog
:cl:
qol: drones now start with engineering skillchip.
qol: drones can now interract with light boxes, rack parts, light replacers and stack of duct.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
what if they could hold some basic janitorial stuff so they can maintain the cleanliness...
(something that doesnt slip/cause slips preferably but idk if we have something like that)

**Comment by robotduinomm** [comment]
> what if they could hold some basic janitorial stuff so they can maintain the cleanliness... (something that doesnt slip/cause slips preferably but idk if we have something like that)

Like soap and damp rag? Why not

**Comment by Fikou** [comment]
> > what if they could hold some basic janitorial stuff so they can maintain the cleanliness... (something that doesnt slip/cause slips preferably but idk if we have something like that)
> 
> Like soap and damp rag? Why not

rag is good, soap can be dropped so probably not

**Comment by Serxule** [comment]
just give them a spray cleaner, pretty sure it can be refilled in the jani office, or they can just use a chem machine

**Comment by robotduinomm** [comment]
> just give them a spray cleaner, pretty sure it can be refilled in the jani office, or they can just use a chem machine

but it can alsobe refilled with anything else

**Comment by Serxule** [comment]
> > just give them a spray cleaner, pretty sure it can be refilled in the jani office, or they can just use a chem machine
> 
> but it can also be refilled using any other liquid

i mean they're easy to get anyways. and drones literally have rules to not interact with the crew, if they fill a spray bottle with lube solely to slip people its just grief and they could end up getting drone banned

**Comment by JohnFulpWillard** [comment]
@Fikou 

I disagree with the cleaning stuff, the station being dirty is an organic problem since it's disease stuff, this is not something I want drones to be intervening in.

**Comment by robotduinomm** [comment]
> @Fikou
> 
> I disagree with the cleaning stuff, the station being dirty is an organic problem since it's disease and human psychology, this is not something I want drones to be intervening in.

Okay I removed the damp rag and trash.

**Pull request merged**
