### PR TITLE
Tweaks A* path cost weighting

### PR DESCRIPTION
**Pull request by Iamgoofball**
please dont sue blizzard

makes a* better

how?

tracer goofs

thanks 2 mso for figuring out how this dank goof worked

### CODE REVIEW

**Comment by Cyberboss** [comment]
You guys mind explaining?

**Comment by MrStonedOne** [comment]
This algo is called the tracer path find algo, its astar with one change, goofball is making tracer memes, also everything goofball says `goof`, he really means `meme`.

Preliminary tests show this to be 3 times faster then astar, but sometimes the paths are few tiles longer then astar

**Comment by Iamgoofball** [comment]
a longer path is well worth the speed

**Comment by Iamgoofball** [comment]
does this count as a bugfix @KorPhaeron

**Comment by MrStonedOne** [comment]
remie did some tests:

head of staff meeting room to chemistry:
old:


New

**Comment by Supermichael777** [comment]
it looks a little less natural(like a drunk stumbling into walls actually). But then again the difference between .7 seconds in 527ops and 12.0 seconds for 1735 ops is worth it

**Comment by MrStonedOne** [comment]
````
/proc/AStar_old                                                                                 14.047       18.129      194.668         2504
/proc/AStar_new                                                                                  3.501        6.901      155.404         2496
/proc/AStar                                                                                      0.078       25.108      350.147         5000
````

**Comment by AnturK** [comment]
Move this to heuristic, don't really see the reason it's in cost function. Also if you want to shave off few more seconds from proc overheads kill calc_f. Don't really see why it's a thing here.

**Comment by Jordie0608** [comment]
Is the turn away from the destination upon entering the conference room just a quirk of the calculations? Would it happen in a larger room, following the wall for longer?

**Comment by MrStonedOne** [comment]
longer round on bagil:

````
/proc/AStar_old                                                                                  221.202      253.985     6846.178         7413
/proc/AStar_new                                                                                  131.576      160.027     4911.254         7451
/proc/AStar                                                                                        0.239      414.250    11757.658        14864
````

**Comment by MrStonedOne** [comment]
>Move this to heuristic, don't really see the reason it's in cost function.

I'm noticing that it doesn't apply it to new nodes, only already met nodes. most likely why.

**Comment by optimumtact** [comment]
@Iamgoofball is there more literature on this particular heuristic modification anywhere?

**Comment by Iamgoofball** [comment]
I ripped it from some GitHub cause it worked

**Comment by AnturK** [comment]
@Jordie0608  Yes, this cuts the influence of cost function in half (average but it will always be at least 7/9 since) in every decision point compared to heuristic which more or less just turns it into greedy search. The backtracks are not apparent because our map are mostly small areas and corridors.

**Comment by Iamgoofball** [comment]
This works just fine so too bad, write your own pathfinding algorithm

**Comment by optimumtact** [comment]
we've seen it work fine in the general cases, there's no paper or research that indicates the heuristic is consistent as required by A* to function in all cases

**Comment by AnturK** [comment]
I don't really have an issue with making our pathfinding less optimal, we don't really need best paths in our current use cases. Just not by mangling generic proc when you can do it properly. And by simply increasing heuristic weight you won't get the drunken zigzags this seems to produce.

@optimumtact  Well A* is guaranteed to find the path if there's no negative costs, it just won't be optimal.

**Pull request merged**
