### PR TITLE
Added 20u transfer amounts to most containers

### LINKED ISSUE #13508: Booze and Soda Dispensers now dispense in fucking annoying amounts.
The addition of the 25u dose is nice, the removal of literally everything but that, 10u, and 5u is not.

Please add back 20 30 and 50 doses to the bar machine because it's suffering trying to brew a lot of drinks now.

Leave the 25 though because that makes a few of them a lot easier - basically the ones that are mixed in multiples of 4.

### LINKED ISSUE #13748: Give beakers the option to transfer 20u instead of 15u
Now that the new chem dispenser UI uses the allowed transfer amounts of the reagent container for injection amounts, you can't inject in 20u increments, which sucks because 20u is a hell of a lot more useful than 15u. Could the 15u option be changed to 20u?

### PR DESCRIPTION
**Pull request by Buggy123**
I think I got everything.

Fixes #13748

Fixes #13508

Let me know if I missed any.

:cl:
tweak: Added 20u per transfer option to most containers.
:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Don't forget #13508

**Comment by Buggy123** [comment]
Thanks, I added it.

**Comment by KorPhaeron** [comment]
You have to say

Fixes #13748

Fixes #13508 

For it to do it automatically. Doesn't understand "and" as far as I konw

**Comment by Buggy123** [comment]
Alright, done.

**Comment by newfren** [comment]
Can you please also update the shaker so it gets 30u and 50u back as well?

**Comment by Zilenan91** [comment]
Do the bar dispensers get a 30u transfer amount?

**Comment by Buggy123** [comment]
Dispensers get transfer amounts based on the container put into them, so they should, yes.

Also I think  the shakers now have 30 and 50u, but i'm not certain.

**Comment by Shapsy** [comment]
:+1::+1::+1:

**Comment by tkdrg** [comment]
Good stuff

**Pull request merged**
