### PR TITLE
Vending Machine Input Framework & Clothing Vendor Inputs

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request
I didn't like how the wardrobe replaced lockers but you couldn't clean up after yourself say once you switched to the nurse's outfit as a doctor. Now, anyone can put clothes in a wardrobe so long as that clothing is a vendable product of said wardrobe (No engineering jumpsuits in science vendor, etc.).

Building off the previous snack machine vendor, this lays the framework for ALL vendors to allow all sorts of items to be inputted into vendors, all you have to do is change `canLoadItem(obj/item/I,mob/user)` to TRUE for the items you want the vendor to accept! It also has an option to restrict loading by changing `canload_access_list`. NOTE: having any of the access permits input instead of all access is needed to input (important distinction!)

ECONOMY: This will make it so any clothes you put in becomes a sellable product. It does NOT make it free unless you can already access the vendor's contents for free.

Code improvement + minor QoL with minute balance implications. If you want to discuss how making it easier to clean up your unused clothes makes it more difficult for antags to sneak then I'm in trouble lol.

## Changelog
:cl: ExcessiveUseOfVending
tweak: Wardrobe Vendors will now accept clothing types they sell. Now you can clean up after getting that cool alternate uniform!
code: see PR #43964 on how to easily setup a vending machine to accept items!
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
[If you added a small refund for a returned item that the returner would have to pay for you could make assistants into Tom Hanks in The Terminal](https://www.youtube.com/watch?v=Gz-QYN_Kl6g)

**Comment by ExcessiveUseOfCobblestone** [comment]
I would do it but the goal for this PR was to clean up after you've vended your free stuff (I just tacked on autodrobe/clothesvend recently) so I'd probably have to cut out the free stuff to begin with if I wanted to give refunds to people.

Just doing a "would this person receive it for free" check would mean people would buddy up with someone else for ez money.

**Comment by RaveRadbury** [comment]
> Just doing a "would this person receive it for free" check would mean people would buddy up with someone else for ez money.

Yet another reason why any friendship or community is metacomming and should be banned from spessmens. /s

**Comment by MrFluffster** [comment]
> ECONOMY: This will make it so any clothes you put in becomes a sellable product. It does NOT make it free unless you can already access the vendor's contents for free.
One step closer to the economy actually working.

**Comment by ExcessiveUseOfCobblestone** [comment]
Sorta, "any clothes" = clothes the machine accepts (which by default is anything that it can dispense).

**Comment by Michael-Ashfield** [comment]
have you checked that any items returned must be empty. For example putting the nuke disk in a satchel then returning it doesn't work.

Also in terms of refunds, perhaps a float system could work so people dont get free money.
Person A: Buys something for $100, there is now $100 in the machine
Person B: Returns something for $30, there is now $70 in the machine
Person A: Returns their $100 item, they only get $70 as thats all the machine has in it

Therefore wealth is not created, but only transferred, having a tax reducing the change the vendor gets can help prevent people buying an item, using it for something the refunding it soon after for full refund.

**Comment by ExcessiveUseOfCobblestone** [comment]
> have you checked that any items returned must be empty. For example putting the nuke disk in a satchel then returning it doesn't work.

If you were to do that all it takes is a screwdriver crowbar to remove the contents. Is there any other situation where I wouldn't consider that emergent gameplay?

As for the refunds I could prob do that but I'll prob toss that in a secondary pr

**Pull request merged**
