### PR TITLE
Lizard Sprites and Digitigrade Limbs: Day 0 fixes

### PR DESCRIPTION
**Pull request by Incoming5643**
- Fixes being able to spawn as humans with digitigrade limbs through some shenanigans
- Fixes your shoes staying on if a badmin gives you digitigrade legs
- Fixes most (all?) cases where outfits/legs don't update properly when equiping clothes at roundstart/with admin verbs
- Fixes leg state confusion when wearing outfits and exosuits that give conflicting flags
- Fixes weird toggle trouble with adjusted jumpsuits
- Fixes black shorts being icon state breakable

Requesting Test Merge to be sure that this hits all the big bugs.

### CODE REVIEW

**Comment by WJohn** [comment]
I would also like to point out that any time you toggle alternate styles with your clothing, your legs will pop out.

**Comment by Incoming5643** [comment]
You shouldn't be able to toggle alternate styles while in digitigrade mode, so thanks for telling me

**Comment by TechnoAlchemisto** [comment]
the lizards have wronged me yet again

**Comment by Incoming5643** [comment]
as far as I can tell, this seems to hit everything, even that one bug I said I wouldn't fix.

**Comment by Incoming5643** [comment]
This is done

**Pull request merged**
