### PR TITLE
Adds trampling

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Kor, Joan
rscadd: When crossing over a downed person, you will deal brute damage to them, and you may trip while doing so.
/:cl:

You can't trample if:

- You have less than 2 legs.
- You're lying down.
- You're buckled.
- You're smaller than the mob you're trying to trample.
- You're a medical or janitor borg.
- You're flying.
- You're stunned.
- You're walking.
- You've recently trampled within the last 0.4 seconds.

Trampling does 4 brute damage, not ignoring armor, increased based on the difference between the trampler's mob size and the trampled's mob size.
For example, humans, which are size 2, will take 12 damage when trampled by an alien queen, which is size 4; the equation is `trample_damage *= 1 + trampler.mob_size - mob_size`, or in other words for this example, it's `4 *= 1 + 4 - 2`, or `4 *= 3` when simplified.

There's a 10% chance to trip for each conscious mob trampled; dead mobs will not cause you to trip.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
people are never going to be happy with this unless you also add a walk hotkey

**Comment by PKPenguin321** [comment]
Make it use regular click cooldown so it doesn't lead to mixing this with punches or whatever

**Comment by ChangelingRain** [comment]
Yeah well they deal with water somehow so I guess they'll have to deal with these much more obvious corpses/idiots that are less likely to stun you.
Also it does use normal click cooldown, it's just very short.

**Comment by TehZombehz** [comment]
>Slip
>Trample on accident 
>Valid escalation you tried to kill me *fireaxe*

**Comment by anconfuzedrock** [comment]
I mean water was always known well as a hazard and is only created by janitors so you won't find it while on a rampage in a maint tunnel people are not going to like this especially without a walk hotkey

**Comment by ExcessiveUseOfCobblestone** [comment]
who tf just rests in maint though

**Comment by anconfuzedrock** [comment]
probably a corpse

**Comment by Arianya** [comment]
If I'm not wrong, there *is* a walk hotkey, if you hold down shift it temporarily toggles you to walk instead of run.

**Comment by Emilc4h** [comment]
It used to, then it got reverted(?) because people didn't like walking when they tried to quick-examine. That or it just doesn't work for me any more, which is also possible.

**Comment by Arianya** [comment]
Drive by examining is trash anyway, bring back shift walk.

**Comment by ExcessiveUseOfCobblestone** [comment]
you could probably tie quick examine to the alt key so long as you're a tile away, since the only functions involving the hotkey [I can think of, at least] involve you being adjacent to the object.

**Comment by MimicFaux** [comment]
> who tf just rests in maint though

I've rested once in my life in maint intentionally. Slipped captain as clown. Stole his ID. Ran into maint without light. Rested, he ran past/over me. Clean escape.

**Comment by Durkel** [comment]
I don't mind the trampling mechanic but the tripping seems like it's going to be annoying just in a general sense, Something like war ops is going to leave bodies all over and will cuck people randomly.

**Comment by Haevacht** [comment]
Corpses are now EVEN STRONGER versus double esworders! They shall trip over your bodies as a LAST INDIGNANCE!

**Comment by SweaterKittens** [comment]
I love this, but share others' sentiments that a walk hotkey would make this a million times better. I get frustrated when the halls are littered wet tiles, not because of the slipping risk, but because turning walking on and off and on and off gets old real quick.

**Comment by dannno** [comment]
Maybe make you only trample if you're on harm intent. 
Sounds like a good way to do it to me  ¯\_(ツ)_/¯
Not sure why no one else thought of that guess I'm a fucking genius

**Comment by PKPenguin321** [comment]
Because then it won't happen on accident and it wouldn't be funny

**Comment by Armhulen** [comment]
If there really is bodies everywhere, lynch the janitor. Or maybe some doctors, iunno.

**Comment by PKPenguin321** [comment]
Oh, and I haven't read the full code so just checking, this is logged right?

**Comment by ChangelingRain** [comment]
yes this is indeed logged

**Comment by jughu** [comment]
Making collusus trampling you instagib you

**Comment by Kromgar** [comment]
Oh jesus god i tripped over a fucking legion corpse while fighting a goliath you sick fucks

**Comment by GunHog** [comment]
Watch your step!!

**Comment by Hatfish** [comment]
Maybe legions should drop special corpses like goliaths and watchers that butcher into humans and legion souls?
Might make it a bit harder to heal on the fly when fighting a shitload of legions, but you wouldn't constantly trip all over lavaland anymore.

**Comment by jughu** [comment]
So a medibot injected me when i was in crit and then trampled me

**Comment by PKPenguin321** [comment]
I don't think the tripping is still needed if there's attack cool down applied already

**Comment by RemieRichards** [comment]
tripping should be a slip, not weaken, so that you throw whatever's in your hands, for maximum chaos.

**Comment by BeeSting12** [comment]
this is actual cancer and needs to be removed ASAP. why does the game need this, we were fine without it

**Comment by PKPenguin321** [comment]
What is bad about it (aside from tripping which doesn't need to be there already)

**Comment by BeeSting12** [comment]
I'm actually okay with the trampling. The tripping is what's really dumb. We don't need another hazard that's commonly found on the ground.

**Comment by ChangelingRain** [comment]
Corpses will no longer cause you to trip; only conscious living mobs can cause you to trip!

**Comment by PKPenguin321** [comment]
Still bad. Tripping was only in kor's original PR to stop people from installing each other with this, but the cooldown does that just as well. Just nix it.

**Comment by ChangelingRain** [comment]
The point is the chain reaction of people tripping over other people and getting trampled, which kor pointed out in his pr!

**Comment by PKPenguin321** [comment]
:thinking: I guess it coulda been both
Either way, I really dislike being able to turn yourself into a banana peel by resting

**Comment by ChangelingRain** [comment]
You're only a banana peel if there's ten people in the tile!
Otherwise, you're just a 10% chance of being a banana peel!

**Comment by BeeSting12** [comment]
a nerf to sec, have fun arresting people while getting pushed over a stunned dude youre trying to cuff.

**Comment by SweaterKittens** [comment]
> I really dislike being able to turn yourself into a banana peel by resting

I'm really looking forward to the first time a traitor thinks they're being super tactical by resting during a chase, only to have the officer stop right in front of them and beat the now-unmoving target into a pulp.

**Comment by PKPenguin321** [comment]
Humans being 10% banana peel by resting is 10% more than they should be

**Comment by ChangelingRain** [comment]
>I'm really looking forward to the first time a traitor thinks they're being super tactical by resting during a chase, only to have the officer stop right in front of them and beat the now-unmoving target into a pulp.

Or just, you know, failing the RNG and discovering that not moving in favor of trying to get a 10% stun doesn't work.

**Comment by KorPhaeron** [comment]
I wanted this to work but in the end it doesn't seem to add much except accidentally stepping on patients and prisoners, I've never seen an actual stampede hurt anyone

**Comment by ShizCalev** [comment]
@KorPhaeron I was sec during a cult round a couple days ago. Called out the cult's location in the doors when one of them stunned and cuffed me. Security and the greytide promptly charged in, leading to multiple people getting the shit trampled out of them (myself included.) I was a hair away from crit by the end of it (from 100%.)

**Pull request closed without merging**
