### PR TITLE
Adds the Pneumatic Cannon

### PR DESCRIPTION
**Pull request by ghost**
cannon_preview

The pneumatic cannon, powered by gas, can shoot out any object that can fit into it. Slap in a top hat, some boxing gloves, and a few pens, and you have yourself a functional gun, as long as you have gas to power it with. As one would expect, using objects that have higher throwing power do more damage, whereas lower throwing power objects won't do nearly as much.

_To-Do_
- [x] Pneumatic cannon framework
- [x] Pneumatic cannon fleshing-out
- [x] Pneumatic cannon polish
- [x] Minor bugfixes/improvements

### CODE REVIEW

**Comment by kevinz000** [comment]
>it takes some time to charge up (during which you cannot move or y ou wil lhave to restart) but each blast bowls people over


>KA MAY HA MAY HA!!
dragonball ref

**Comment by PKPenguin321** [comment]
>**improvised** pneumatic cannon

How improvised are we talking? Assistant-level or improvised shotgun-level?
Either way, it sounds seriously fun.

**Comment by Iamgoofball** [comment]
tau cannon and rock-it launcher

tg is coming a long way

:+1: to both

**Comment by RemieRichards** [comment]
I recommend adding ```item.throw_speed = EMBED_THROWSPEED_THRESHOLD``` 
so that the items can embed as if they were thrown by an explosion.

or perhaps ```item.throw_speed = pressureSetting * someMagicalExponent``` so that it only triggers in certain ```pressureSetting```s.

(Don't worry about the throw_speed being changed, it gets set back to initial after ```throw_impact()```)

**Comment by Miauw62** [comment]
you can even change the pressure :+1:

**Comment by Xhuis** [comment]
Added the particle cannon (no recipe yet). Also did some work on the pneumatic cannon and added a recipe for the ghetto version. Both guns lack inhands and unique sprites.

**Comment by Boredone** [comment]
So, question.
How many shots would you get out of an improvised cannon loaded with the tank that starts in your box in your backpack?

**Comment by Xhuis** [comment]
Depends on the pressure setting. I think the most you can get is only 1 by default.

**Comment by optimumtact** [comment]
:-1: no more guns

**Comment by AlexanderUlanH** [comment]
:+1: more guns

**Comment by Xhuis** [comment]
Decided against the particle cannon for now due to difficulties with it. Pneumatic cannon still needs sprites, as well.

**Comment by Xhuis** [comment]
>conflicts

**Comment by Xhuis** [comment]
All right, sprites are added from a year-old forum thread on the archived old forum (thanks to WJohnston for finding it). Overlays are mostly working with the exception of them not disappearing after removing a tank despite my best efforts. Also lacks inhands.

**Comment by RemieRichards** [comment]
@Xhuis for overlays, do what humans do, and scrap the entire set of overlays on the object and rebuild it all again (in an update_icons())

If it's ok for humans (usually lugging around 6-7 overlays) your object should be fine.

**Comment by Xhuis** [comment]
Will do in the conflict fix.

**Comment by Xhuis** [comment]
Still not working. Could use some help - this is my code so far
http://hastebin.com/obokuhawej

**Comment by RemieRichards** [comment]
```overlays = null``` should probably be ```overlays.Cut()``` (but that shouldn't cause your issue)
What does your ```update_icons()``` do? When I suggested using it, I meant producing a custom one for your object that does ```overlays.Cut()``` and rebuilds all the overlays from scratch.

**Comment by Xhuis** [comment]
Ahh, I see. My mistake, will do some work.

**Comment by Xhuis** [comment]
All right, got it working. This lacks inhands but is merge-ready otherwise.

**Comment by AlexCrimson** [comment]
Having trouble building the ghetto one. Got all the materials on a table + wrench/welder in hand, but the option is still greyed out.

**Comment by Xhuis** [comment]
Tools go on the table as well.

**Comment by AlexCrimson** [comment]
Tried that too. Didnt work. Hell, i even divided the stacks of wrapping/metal into individual items.

**Pull request merged**
