### PR TITLE
Resprites the sec grenade launcher

### PR DESCRIPTION
**Pull request by ReinaCoder**
## About The Pull Request
Resprites the sec riot grenade launcher
image
image
image

## Why It's Good For The Game
image
This sprite is weird and not the best also similar in style to the syringe guns.

## Changelog

:cl:
imageadd: Resprites the sec grenade launcher
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
I'd recommend adding a third color to the shading, lighter than the rest. On the barrel it could maybe (?) benefit from actually being in the middle, as weapons are typically shaded from the middle with a focus towards the top, showing that the weapon is a tube.

**Comment by ReinaCoder** [comment]
is this better?
image

**Comment by CRITAWAKETS** [comment]
Ye.

**Comment by Imaginos16** [comment]
Wow! A grenade launcher that looks like an actual launcher? Hell yes!

**Pull request merged**
