### PR TITLE
buffs the cake hat

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
the cake hat does more wounds (similar to welders, but a little less bare wounds)
the cake hat no longer makes you bald and no longer hides your ears

## Why It's Good For The Game
brings it back to its glory

## Changelog
:cl:
balance: the cake hat wounds more
fix: the cake hat no longer balds you
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
Fikou, this coincides with yesterday when I saw a chef making cakehats. Besides the matter, bless your kind soul for bringing them back. Also make a way to take it off of the potted plant, please.

**Comment by carlarctg** [comment]
buff energy cakes too

**Comment by KittyNoodle** [comment]
Make it work as a very shitty welder

**Comment by ExcessiveUseOfCobblestone** [comment]
stupid

**Comment by Striders13** [comment]
Every round. Every fucking round I see some stupid assistant wearing this stupid fucking hat
and I already know they going to kill me with it. I don't know how or when but it always happens
and I'm so fucking sick of this overpowered piece of shit meme hat. Why the fuck do we even
have it? This is the most broken item on the station and it just enables powergamers basically
free kills on whoever they want. I want to throw it out an airlock every round but then I'll get
banned for metagruding the admins bankrollers, because of course anyone who uses this hat is
obviously the admins metafriends. Why else would THEY get ignored for getting the hat every
round? /tg/ died the moment this thing got put into the game.

**Pull request merged**
