### PR TITLE
March into Mapness Take 2: Better Meta Kitchen

### PR DESCRIPTION
**Pull request by Draggeru**
## About The Pull Request

As the title says, moves the kitchen counter up and reorganizes stuff so the meta kitchen doesn't feel like such a cramped stuffy hell hole. Adds an extra griddle and oven as well.

### Mapping March
Retry of #73863
This is mostly for mapping march, I now had a reason to stop being lazy.

Ckey to receive rewards: Thedragmeme

## Why It's Good For The Game

Cramped workspaces are bad, and it cures my OCD by making the counters line up. Doubles the number of griddles and ovens, more machines to do stuff = good. Especially since two people can be chefs at a time by default.

metaaaaa

## Changelog

:cl: Thedragmeme
qol: Makes the Meta station kitchen not cramped anymore
:cl:

### CODE REVIEW

**Comment by Draggeru** [comment]
I officially need an adult.

**Comment by zxaber** [comment]
>and it cures my OCD by making the counters line up.

Honestly, I thought the offset counters were visually interesting, and helped the two stay distinct.
That is to say, soulless, but also I play neither chef nor bartender so take my opinion with a grain of salt.

**Comment by Draggeru** [comment]
> > and it cures my OCD by making the counters line up.
> 
> Honestly, I thought the offset counters were visually interesting, and helped the two stay distinct. That is to say, soulless, but also I play neither chef nor bartender so take my opinion with a grain of salt.

I get what you mean, and while I like the visual appeal of the counters being even it's less about that and more about doubling the amount of cooking equipment and adding more ingredient space (tables.) 

If you absolutely know what you're doing and can speed through the extra equipment helps, and it also helps having two of both because by default there can be two chefs. Meta kitchen (at least in my experience) makes you do this weird little dance with your co chef when you're both trying to do your own thing or are not coordinated with them

**Comment by Helg2** [comment]
The tables look like a placeholder
And i don't think that this is a comfortable place for griddles, as it's position near tables don't cover you from getting shot.

**Comment by Time-Green** [comment]
I feel like I have to point out march has ended

**Comment by Draggeru** [comment]
> I feel like I have to point out march has ended

This PR was created originally in March, if you have decided to pay attention even a little bit to what the PR description says you'll know this is a fresh branch due to errors.

**Review by san7890 — CHANGES_REQUESTED** [review]
Just looking at your photograph:

image

This griddle is right under the firelocks and the shutters, which mean if either of those trigger, the chef will be unable to reach whatever eggs they are cooking. should probably remove these so that they're only placed on the counters. I think you might have to move the piano and place an actual wall to the east of the northern griddle, which will take a bit of design effort... But I think shutters closing on the griddle is just untenable.


image

I'm not certain if you've caused it but although this looks in fine in game to an average human player, this is quite ugly to ghosts as well as sometimes blocking the AI from clicking that button (since it can be obstructed when they see both sides of the walls). Could you kindly move the TV somewhere else in that bar lounge area, or place the button on another wall (this can be done in conjunction with the first review point (adding another wall))

image

I don't particularly like these vents/scrubbers being "blocked" by the stools, could you shuffle them such that they are on the wood flooring a bit above? It may look funny with the contrast but I think it's greatly preferable to having structures "block" it.

image

Are you using the `/contrasted` subtype of tile decals? I'm not sure why they look so strange otherwise (the decal drawing over the "grout" of the cafeteria turf).

**Comment by Draggeru** [comment]
> 

This is an excuse to make the theater prettier

**Comment by Draggeru** [comment]
> Are you using the `/contrasted` subtype of tile decals? I'm not sure why they look so strange otherwise (the decal drawing over the "grout" of the cafeteria turf).

Nope, I copy and pasted what was there already. I am not sure why it looks weird

**Comment by Draggeru** [comment]
> Just looking at your photograph:

maptainer

**Comment by Draggeru** [comment]
OH NO IT DELETED ALL OF THE DIRECTIONAL WINDOWS

**Comment by Draggeru** [comment]
Windows have been painstakingly re-added, I don't know why its flagging map diff, probably because it has a y or z tile offset. Good news though: The mourges body lading area had the window placed wrong. So this PR will fix that.

**Review by san7890 — CHANGES_REQUESTED** [review]
Sorry for getting back to you so late. One last thing is that you have an errant light fixture right here (these gotta go on walls), just gotta move that elsewhere and this is good to go.

image

ping me when this is done on discord

**Pull request merged**
