### PR TITLE
Adds a seclite to the detective's closet.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
:cl:Papa Bones
rscadd: The detective's closet now contains a seclite, get sleuthing!
/:cl:

### CODE REVIEW

**Comment by Jordie0608** [comment]
I'm conflicted between this making sense for a detective to have and lessening the difference between officer and detective.

**Comment by TechnoAlchemisto** [comment]
Having a flashlight is pretty essential detective gear in basically every movie ever. How else will you look for clues in dark alleyways?

**Comment by Jordie0608** [comment]
Yes hence

> this making sense for a detective

**Comment by Durkel** [comment]
This is good, having to look for a flashlight is annoying.

**Pull request merged**
