### PR TITLE
Revert "Adds *pee and *poo"

### PR DESCRIPTION
**Pull request by Shadowlight213**
Reverts tgstation/tgstation#23257

### CODE REVIEW

**Comment by Arianya** [comment]
The contributor we need, but not the one we deserve 👍

**Comment by PKPenguin321** [comment]
Can't have any comments in our code base

**Comment by ExcessiveUseOfCobblestone** [comment]
meme

**Comment by vcordie** [comment]
let the harmless ayy lmao comment stay,

**Comment by KorPhaeron** [comment]
Don't start revert wars with maintainers please

**Comment by Shadowlight213** [comment]
@KorPhaeron oranges himself has removed similar comments. Should I bring that back?

**Comment by Arianya** [comment]
@MrStonedOne I seem to recall you saying you dislike maintainers who break their own rules.

**Comment by Iamgoofball** [comment]
i seem to recall you flipping out over a single meme comment

get a life

**Comment by kevinz000** [comment]
@Iamgoofball i seem to recall you're shit.
get good.

**Pull request closed without merging**
