### PR TITLE
Adds Timeline Eradication Agent event [nono mergeymergy]

### PR DESCRIPTION
**Pull request by JJRcop**
Adds a new event/antagonist called the Timeline Eradication Agent, an implementation of #7084.

The TEA is tasked with erasing one sixth of the round population, maxing out at four, using the provided tools.

The event can be triggered after the round has lasted at least 45 minutes, and it can trigger a maximum of three times.

See #7084 for more information on the tools.

### CODE REVIEW

**Comment by pudl** [comment]
it's shit, stop doing this.

**Comment by TZK13** [comment]
Why does ninja have to be touched at all with this, they can easily coexist.

**Comment by JJRcop** [comment]
Alright, I will leave ninja.

**Comment by JJRcop** [comment]
I will fix the incorrect pathing when Z2 has its pathing fixed

**Comment by Ikarrus** [comment]
>Literally just a murderboning role

Please, no.

**Comment by Stickymayhem** [comment]
I think this is way better suited to capturing people and straight up murder objectives aren't particularly interesting.

**Comment by Steelpoint** [comment]
I like it.

:+1:

**Comment by AlexanderUlanH** [comment]
I don't know if this has been tested on the server, but it probably should be before it's brought in as an event that can happen without intervention.  I coulod see TEA being very fun or very lame in actual rounds.

**Comment by paprka** [comment]
>literally just a murderboner antag

please be more interesting than this.

**Comment by Fox-McCloud** [comment]
:+1: 

Still would love to see you expand on this antag and his abilities as a hypothetical replacement for ninja.

**Comment by JJRcop** [comment]
Got no objective ideas, none, hit me.

**Comment by optimumtact** [comment]
Remove ninja

**Comment by TZK13** [comment]
>Hating on ninja
>2015

**Comment by JJRcop** [comment]
Just to say, I'd love to have the TEA erase just one or two dudes and then have other objectives, but I want those objectives to be unique and fun, that also has a guarantee to affect the round in a chaotic way, and I don't have any ideas, and just having one or two dudes and nothing else makes the TEA not really affect much.

**Comment by TZK13** [comment]
How about making it so that the TED can delete objects as well and then having objectives to erase certain things like say the PA or gravitational generator.

**Comment by JJRcop** [comment]
I was actually thinking of renaming the antag to the "Timeline Mutation Agent",

**Comment by JJRcop** [comment]
oops

**Comment by Kromgar** [comment]
I like the object deletion idea as well.

**Comment by RemieRichards** [comment]
>>nono mergeymergy

I think that's the best request for a "Do Not Merge" tag I have ever seen

**Comment by JJRcop** [comment]
dunno if im gonna do anything anymore or not, maybe, idk

**Comment by optimumtact** [comment]
Then close the PR and leave the branch around for later

**Comment by JJRcop** [comment]
good idear

**Pull request closed without merging**
