### PR TITLE
Space Maggots Death Update

### PR DESCRIPTION
**Pull request by chesse20**
## About The Pull Request
@optimumtact wants death to be more impactful, so i made a new code where if a body is dead for too long it starts to get maggots in the brain. If the maggots are not removed they can eat your brain, at the start giving you a chance to be cloned into a fly person and later making you unclonable after they have eaten enough brain. 

## Why It's Good For The Game
Nerfs cloning and makes medical more important than just shoving people into cloning or cyro and makes surgery more important. 

## Changelog
:cl:
add: Added maggots 
add: Added surgery to remove maggots
rework: if you have maggots in your brain when cloned there is a chance to be cloned into a fly person
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
I kind of hate this thematically

**Comment by zxaber** [comment]
>Nerfs cloning and makes medical more important than just shoving people into cloning or cyro and makes surgery more important.

Except that this waits two and a half minutes before activating, and medical will usually just thrust the recently expired body into a cloner right after letting them die. This does not at all affect people using cloners over surgery.

But it does make murderboning more powerful, since leaving bodies in maint is more likely to have them sit for the _ten minutes_ that it takes for them to become uncloneable.

**Comment by Militaires** [comment]
based pr

**Comment by epicmemename** [comment]
redpilled pr

**Comment by Militaires** [comment]
image
based pr

**Comment by OverlyGeneric** [comment]
Space maggots are scarier than just eating our brains. 

It means that food can rot, the station is at risk for diseases like Lyme disease, anthrax, rabbit fever, anaplasmosis, hog cholera, rpoundworms, and not mention whatever horribly mutated bullshit space colonization has brought us. 

Some flies take blood from humans, some flies literally implant fucking maggots into your skin, some flies are literally, and most eat, fuck, and die all in a pile of shit.

It's honestly my greatest fear of just maggots being inside food or eating away at living bodies. I bloody hate flies.

The only thing I would say is that the air is lightly contaminated with formaldehyde, "safe" industrial-grade pesticides, and a large amount of monosodium glutamate to lower the costs to pay for professional chefs and reduce food costs by promoting cannibalism. 

The only thing that manages to survive the bloody pesticides are space cockroaches because they're hardy little bastards and don't die to anything but a good whack.

**Comment by HomocidlePancakes** [comment]
Ok. So. Let’s say Lexia Black kills 3 sec officers 5 minutes in. It takes 3 minutes to recover the bodies. Noone bothers to upgrade cloning so it takes 4 minutes to clone each officer. You manage to clone 2, but the third one becomes unclonable. His body was recovered in time but now he is pretty much gibbed.

There is no way to preserve bodies awaiting cloning. There are 3 possible solutions to this.

1)*Make morgue trays preserve bodies.*
It’s the most reasonable one, but morgue is rather secluded and MDs may forget about you(most of the times it’s someone else doing cloning anyway and they won’t have access there). Also they are uncraftable.

2)*Make some sort of special machinery to preserve bodies.*
This would be the best solution imo, but it requires effort(sprites, extra code).

3)*Make bodybags preserve bodies*
Self-explanotory. But if I remember correctly you can’t make regular ones.

**Comment by HomocidlePancakes** [comment]
Also does this affect decapited heads and removed brains?

**Comment by Tlaltecuhtli** [comment]
could be linked to miasma?

**Comment by ATH1909** [comment]
I hate this PR and the reason that it's being created for with a deep passion, but here's a critique about it that tries to ignore the reason for this PR's creation:

Say someone gets injected with strange reagent, oh, say, 7 minutes after they die, and they come back to life. _Where do the maggots that were writhing around their brain go?_ Are they supposed to _still be in there_?

Speaking of strange reagent, this PR kind of kicks strange reagent's schtick/niche of "like a defib, but it can be used on long-dead corpses" in the teeth.

Will defibs still deal brain damage based on the time that the defibee was dead for upon a successful resurrection?

You could make formaldehyde preserve brains while they're in a corpse with a brain- it already keeps corpses from producing miasma. Also, the potential meta strategy of filling chem implants (which automatically inject their contents upon their host's death) from sec with 5u of formaldehyde and then implanting them in sec officers, members of the command staff, and other important personnel to keep their corpses from decaying after their inevitable deaths could be somewhat interesting, if a bit tedious to set up every round.

Why do we need the imagery of _maggots_? Just have dead brains naturally decay over time or something and don't mention maggots (maybe add a grace period to the decay and make brains in MMIs immune to the decay so that MMIs won't just reject most brains due to them having minor amounts of brain damage from natural decay).

How is this supposed to interact with the "don't cremate, husk, or space bodies as a non-antag unless absolutely necessary" policy that us players supposed to follow?

I feel like a lot of people will just not bother trying to fix the brains of bodies that they can't clone and instead just leave them there in the cloning room to rot for all eternity. It's one thing to just drag someone over to cloning and clone them; it's another thing to drag someone over to cloning to clone them, discover that their brain is too damaged, break into the operations theater (or walk all the way over to the holodeck with the dead body or break into robotics), look up how to perform the brain-fixing surgery on the wiki, perform the brain surgery, drag the body back to the cloner, and discover that the body's ghost/client has already quit the game or become a ghost role, making their body uncloneable anyway.

I said that I wasn't going to attack oranges's push towards making death "more impactful", but I'd still like to reiterate that making the damage caused by accidental self-inflicted deaths, murderboners, plasmaflooders, and mass-bombers be MORE permanent doesn't seem like something that we should be doing.

**Comment by FloranOtten** [comment]
Oh boy, I can't wait to be left to rot forever because MDs can't be arsed to do surgery! It's already far too easy to just be shot and lockered in maint, do we really need to add an arbitrary timer that forces people to undergo brain surgery?

Not many doctors know how to do basic surgery, I doubt forcing them to do it en masse every time someone bombs hallway or goes on a spree (It will regularly take upwards of 10 minutes to get cloned. Bomb damage takes priority, and maintlockering is a guaranteed 10 minute wait) is a good idea.

**Comment by Barhandar** [comment]
I agree with others. This is a direct buff to already extremely overpowered antags, and not because medbay is usually incompetent - medbay doesn't even go into the equation. Kill target, space the body (or strip uniform and locker it in some forgotten maint corner), the owner is now permanently out of the round with _zero_ chance, as opposed to _small_ chance, of coming back. Miner dies, miner is guaranteed fucked over permanently because even with competent crew it takes longer than 10 minutes to get the body/brain back on station.

To make death more impactful, you need to make dying less easy, and hence antags far less powerful, first.

P.S. If this is April Fools PR, it's submitted too late.

**Comment by nicbn** [comment]
Isn't spark of life config already a thing

**Comment by Grazyn** [comment]
You don't need to come up with a realistic reason like these maggots to introduce a gameplay change, just say a body can't be cloned after 10 minutes and that's it. This doesn't even add maggots as an item/mob (could be great for exotic dishes, we lack southeast asian cuisine) so it's kinda disappointing.

**Comment by HomocidlePancakes** [comment]
Maggots a great fluff tho

**Comment by anconfuzedrock** [comment]
Maybe when hiding a corpse in a private locker in dorms isn’t a foolproof way to hide a body this will be a good idea.

**Comment by Mickyan** [comment]
who unbanned chesse

**Comment by SouDescolado** [comment]
> rework: if you have maggots in your brain when cloned there is a chance to be cloned into a fly person

If you have maggots when SCANNED, right?

**Comment by davethwave** [comment]
I would personally add something like soul degradation rather than something like maggots.

**Comment by Qustinnus** [comment]
is this a serious chesse pr? Wtf

**Comment by optimumtact** [comment]
thog regret letting chesse back in

**Pull request closed without merging**
