### PR TITLE
Move some globals out of world.dm

### PR DESCRIPTION
**Pull request by Cyberboss**
Putting them in SSmapping will make sense eventually I promise

### CODE REVIEW

**Comment by kevinz000** [comment]
please do this to awaydestinations too so i don't have to do snowflakey shit to change it.

**Comment by Cyberboss** [comment]
I'm gonna be genociding globals over the next month as part of a larger project

**Comment by MrStonedOne** [comment]
One thing to note as you do that is that globals are super fast to access because they compile to a numeric index on the global var array. (where as datum vars require a binary search)

**Comment by Cyberboss** [comment]
WHAT!!!!!

**Comment by Cyberboss** [comment]
Handle this in a different PR

**Pull request closed without merging**
