### PR TITLE
Security Suit Sensors are maximized by default

### PR DESCRIPTION
**Pull request by Robustin**
A simple improvement. For those going "REEEEE git gud you scrub", this isn't just about the officers who forget to set them, this is also about the security who gets ambushed by a taser because some other shitty officer didn't set his sensors and so nobody knew that he had died and gotten his shit handed out to revs/traitors/cultists/whatever. This will help sec keep tabs on their own (if they are vigilant). 

:cl: Sogui
tweak: All security (and captain) suit sensors are set to max by default
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
We should have any non-antagonist roles (Captain, Security) have their suit sensors on by default.

**Comment by Cyberboss** [comment]
Also you missed the HoS' gear

**Comment by Robustin** [comment]
I got the HOS gear, any subset of HOS gear should be affected too.

**Comment by Cyberboss** [comment]
Seems like you got everything EXCEPT the hos gear https://github.com/tgstation/tgstation/pull/23386/files#diff-4feb0a0aba22e605f873573ea7fa4b07R85

**Comment by PKPenguin321** [comment]
Just get good

**Comment by dannno** [comment]
>Just get good

**Comment by AnonymousNow** [comment]
sign me the FUCK up 👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌th 👌 ere👌👌👌 right✔there ✔✔if i do ƽaү so my selｆ 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by Kromgar** [comment]
Have you people gone into delta maint? Its a god damn labyrinthine maze of horros

**Comment by Robustin** [comment]
I don't even think this will help much with Delta.

Uh we got an officer down in uh... auxillary storage room. 

But hey its a start.

**Comment by calzilla1** [comment]
Give the warden a resprited HH medical tracker

**Comment by PKPenguin321** [comment]
When did we come to this?

**Comment by KorPhaeron** [comment]
I mean this is probably a good idea but holding peoples hands to the point where you need to automate a single right click for them is just a bit sad

Will be funny if this turns into a security nerf because everyone will know where they are though

**Comment by Robustin** [comment]
I dunno if Warden should get a HH crew monitor or what. Maybe the detective?

**Comment by dannno** [comment]
i can't believe we're actually hand holding this hard

**Comment by XDTM** [comment]
> Guy dies with max sensors, no doctor checks sensors

Sensors are useless! Nobody checks them! I won't bother turning them on anymore.

> Guy dies, doctor sees him dead in sensors but can't find him

Everybody keeps their sensors off! I won't bother checking the crew monitor anymore.

---

Rinse and repeat

**Comment by BeeSting12** [comment]
Kinda encourages hugbox.

**Comment by Haevacht** [comment]
Maxed suit sensors have coordinates. This will save people in Delta maint.

Jesus it's like none of you play medic/suit sensor yeller.

**Comment by sawrge** [comment]
dumb

**Comment by PKPenguin321** [comment]
I still can't use crew monitoring consoles without my game crashing tbh

**Comment by dannno** [comment]
>I still can't use crew monitoring consoles without my game crashing tbh

this

**Comment by Cyberboss** [comment]
Separate issue, nerds #22124

**Comment by Shapsy** [comment]
paranoia is dead

**Comment by Cheridan** [comment]
🤗 🗃 🤗

**Comment by Aloraydrel** [comment]
H U G  B O X

**Comment by Robustin** [comment]
1) Paranoia was already dead

2) This doesn't affect paranoia, if you get fucked, you get fucked, this just potentially warns the rest of sec that you got fucked and give you a shot at being cloned. 

Yes there are coordinates but unless you have a GPS they're just numbers, sec doesn't get GPS, handheld crew monitors could technically work but it would require the person holding the monitor to also be the one roaming maint looking for the body. I wouldn't even recommend having a health monitor up if you're walking through maint where another officer had been murdered. 

Or you know we could flip the "git gud" burden onto antags and tell them to git gud at stripping bodies if they're that upset about being found through suit sensors.

**Comment by Haevacht** [comment]
CJS, Get a GPS from science. Or 3. Get your overwatcher on the suit sensors and your rescuer has a GPS, overwatch guides. You know, ask another department for shit.

And on Meta at least the MedSec has access to the suit sensors console so he's your overwatcher.

**Comment by dannno** [comment]
if sec officers git gud at getting dressed by themselves like adults then antags still have to git gud at stripping so they don't get caught
so I don't get your point

**Comment by jughu** [comment]
Is pressing 2 buttons at roundstart this hard?

**Comment by Robustin** [comment]
For new sec players, yes, because they have no fucking clue they even exist. I see a "MAX SUIT SENSORS" message like once a month because nobody bothers anymore. If you don't hear someone reference suit sensors, there's absolutely 0 indication they exist and even then unless you play medbay and dig out the handhelds from the last choice in a vending machine, you STILL won't know they exist. 

Which brings me back to my post, sec gets punished when the newbies disappear and sec doesn't know if they're dead, AFK, distracted, and suddenly a random assistant tases your ass and doubles his collection of dead sec gear. 

If its so easy what's the problem with doing it for the newbies? Are you all really that desperate to say "HAHA FUCK YOU NEW SEC PLAYERS, NOBODY IS EVER GOING TO FIND YOUR BODY NOW, AHAHAHA".

**Comment by PKPenguin321** [comment]
i used to think hugbox was a meme

**Comment by optimumtact** [comment]
had to delete of poor comments from the pr, sad.

Might have to start building a wall to keep some of these low effort posters out permanently.

**Comment by PKPenguin321** [comment]
I hate this new oranges fad of deleting any comments that even vaguely refer to player skill levels being different and the possibility of getting better at the game instead of changing the game itself. Put in some effort in your game instead of just changing the game, Robustin.

**Comment by kevinz000** [comment]
This is a good change, not enough people use suit sensors, if you want to take them out take their jumpsuit off, this isn't horribly overpowered, why are people downvoting this? :/

**Comment by dannno** [comment]
Because it's babying players
It's sad that people even see this as a thing that would ever be necessary

**Comment by Haevacht** [comment]
If you don't hear someone bitching about suit sensors, the CMO, AI, and medical doctors have failed in their duty.  I'll admit I didn't know the handheld existed until not long ago but I sat next to the main computer instead.

And this only lets you find the looted corpse of that newbie, the person still gets the loot. That's pretty irrelevant.

**Comment by XDTM** [comment]
>Oh boy we can't have traitors needing to cover their tracks, the game is going to be a huge hugbox for sec if they have to do anything that takes more effort than stuffing the body in a maint locker if they don't want it cloned.

Plus, sec having consistent sensors would encourage medbay to check sensors more often to see if anybody in security died, which in turn will allow them to see other deaths, which'll make sensors used more often, which i think is a good thing, as it makes traitors take at least a few seconds to strip the body when murdering.

Also, the random sensors, as far as i know, are not there to give every single player a task to do before every round, it's to prevent metagaming by checking who turnied their sensors off. But there's hardly anything to metagame with security, we _know_ they can't be antags.

**Comment by optimumtact** [comment]
@PKPenguin321 put some effort into justifying why it should be something people should "get good" at then, just saying "get good" is not an argument, it's an opinion, but if you say "get good because x and y lead to z" then that's something someone can argue with, rather than just noise that shits up the r and obscures the real discussion

**Comment by optimumtact** [comment]
I think this makes sense for sec and for sec only, it's not a metagaming issue like the rest of the suit sensors cause security officers cannot be traitors at roundstart.

**Comment by PKPenguin321** [comment]
Every day we stray further from what we once were

**Comment by optimumtact** [comment]
shutup you meme

**Comment by PKPenguin321** [comment]
Remove death when

**Comment by Aloraydrel** [comment]
casualized tbqh

**Pull request merged**
