### PR TITLE
Datum and atom optimization

### PR DESCRIPTION
**Pull request by nicbn**
atom/admin_spawned, atom/initialized, datum/use_tag and datum/var_edited are now flags of atom/flags_2 and datum/datum_flags

datum/fingerprintslast moved to atom

**Please testmerge before merging**

Also I'd love if someone profiles it (idk how to do profiling sry)

### CODE REVIEW

**Comment by Cyberboss** [comment]
profiling won't do much. It's just memory usage going down

**Comment by Cyberboss** [comment]
var_edited and initialized are really important and need to stay their own things imo. Adding datum_flags also seems like a bad idea, datums should be as lightweight as possible

**Comment by nicbn** [comment]
> datums should be as lightweight as possible

That's why
I turned 2 vars (var_edited and use_tag) into one flag var. As far as I know there are no booleans at byond, so this should reduce the memory usage of each datum by one var.
Also I don't understand why var_edited and initialized need to stay as single vars. You can still read and write to them.

**Comment by Cyberboss** [comment]
They are meant to never be tampered with outside the systems that use them in order to reduce bug/attack surface, var_edited in particular must be protected against admins. Also initialized is a hard change on the state of the object, e.g. most things can't be interacted with before it's set.

**Comment by nicbn** [comment]
Well I know how to protect it all but I need time

**Comment by nicbn** [comment]
I will reopen when it's done

**Pull request closed without merging**
