### PR TITLE
re-adds an old vital cosmetic item

### PR DESCRIPTION
**Pull request by MMMiracles**
WHATS THE WORST THAT COULD HAPPEN??

### CODE REVIEW

**Comment by Jalleo** [comment]
No this was our version of poo removal.

**Comment by SconesC** [comment]
I was saying "please let this be what I think it is"

And I check files changed

AND LO AND BEHOLD 

(its not anywhere on the map put it in the warden's locker for funnies)

**Comment by WJohn** [comment]
YES. YES. YES.

**Comment by Iamgoofball** [comment]
:-1:

**Comment by Aranclanos** [comment]
haha good jokes mate real funny see you at

**Comment by MMMiracles** [comment]
fun is kill

**Comment by daman997** [comment]
OPEN IT AGAIN FAGGOT I WANT THIS

**Comment by SconesC** [comment]
@Aranclanos I'm removing your admin rank

**Pull request closed without merging**
