### PR TITLE
Buildable Shuttle/Plastitanium Windows

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: You can now smelt titanium glass and plastitanium glass
add: Use titanium glass and plastitanium glass to build shuttle windows and plastitanium windows
/:cl:

Sprites by WJ, WJ also minorly updated the titanium and plastitanium icons

### CODE REVIEW

**Comment by Bawhoppen** [comment]
Me and WJ intended to make a sprite for a sheet of titanium glass to build them with instead. but this works too.

**Comment by davethwave** [comment]
I just wish the buildable shuttle can be smaller.

**Comment by Bawhoppen** [comment]
Actually I think we should do it the other with with the specific material for these, since there's precedent with plasma glass. Then we can have them used for constructing other things aswell.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
> Actually I think we should do it the other with with the specific material for these, since there's precedent with plasma glass. Then we can have them used for constructing other things aswell.

Yes make them consistent.

**Comment by uraniummeltdown** [comment]
What would you use titanium glass and plastitanium glass for except building shuttle/plastitanium windows? Seems pointless to add in 2 new materials just for one use.

**Comment by ExcessiveUseOfCobblestone** [comment]
Because they could have more use in the future and at worst it keeps them consistent so players don't F1 "why can't I make this glass?!!!".

**Comment by uraniummeltdown** [comment]
I'd rather add this in for the time being, if someone thinks of an interesting use for titanium/plastitanium glass they can add in the material and make the windows use those.
Playerd don't f1 "why can't I make this glass", I don't think any codebase even has many kinds of glass. It's like saying to add gold glass or diamond glass or uranium glass because players would be expecting it

**Comment by ExcessiveUseOfCobblestone** [comment]
or plasma or titanium or plastititan... oh wait.

**Comment by ExcessiveUseOfCobblestone** [comment]
sorry that was rude but please just make it consistent.

**Comment by Bawhoppen** [comment]
The sprites will be done as soon as I am finished hounding WJ to tell me why mine weren't good enough

**Comment by Bawhoppen** [comment]
WJ has decided to do the sprites for them instead of me
Here, please use them: http://www.mediafire.com/file/74nkbz9b88xt3ar/Shuttleglass.dmi

Additionally, WJ updated the titanium and plastitanium sprites themselves, so please update them too
http://www.mediafire.com/file/39v966xbggto3xm/titanium.dmi


Of course, if you don't wanna do any of this, I can make my own PR and you can close this one.

**Comment by uraniummeltdown** [comment]
Damn, those sprites are quite sexy
I still think its a dumb idea to make 2 new materials that are only used for building windows, but the sprites are great so I will add them in later
itll be mildly annoying if nobody uses titanium glass for anything else in the future

**Comment by Bawhoppen** [comment]
I think we can find something for them. Also I don't think that new materials are really a code burden at all either.

Hopefully in theory someday, we could have a modular construction system for structures, so like for example, you could use stronger types of glass in console construction, and the better, the more HP it would have. Probably won't happen anytime soon, but would be cool.

**Comment by uraniummeltdown** [comment]
ok I added the new glasses
in future we really need to OOPify the different glasses

**Comment by WJohn** [comment]
Yeah, these aren't really "new" materials at all. Putting in r-glass in an autolathe doesn't get used as a special r-glass slot, it gets split into appropriate metal and glass amounts. Likewise with something like plasteel, you get metal and plasma.

In this case, you'd get glass and titanium, or glass, titanium, and plasma all in one go.

**Comment by uraniummeltdown** [comment]
@WJohn do you want them to be new materials or alloys?

**Comment by Bawhoppen** [comment]
@uraniummeltdown What does that question mean? Alloys are just the type of materials made from other ones.

**Comment by uraniummeltdown** [comment]
@Bawhoppen I mean, does he want them to be a whole new material like MAT_TITANIUMGLASS or something

Also this PR is ready

**Comment by Bawhoppen** [comment]
No, he doesn't want that. This is fine as is.

**Comment by WJohn** [comment]
Nah, I'm just saying if you were to feed it to a protolathe or something, it should split them up into their constituent parts, like when you feed it r-glass.

**Comment by uraniummeltdown** [comment]
@WJohn this is ready

**Pull request merged**
