### PR TITLE
Fixed disposal piping on the listening station ruin

### PR DESCRIPTION
**Pull request by Blute1**
Fixed incorrect disposal piping on the listening station ruin. A duplicated pipe prevented things from being properly ejected out the chute.
:cl: optional name here
fix: Fixed disposal piping on the listening station space ruin.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

fixes pipes

### CODE REVIEW

**Comment by Blute1** [comment]
woops

**Comment by nicbn** [comment]
No changes

**Comment by Blute1** [comment]
hold on

**Comment by Blute1** [comment]
I removed a pipe that was duplicated

**Comment by Blute1** [comment]
i will return

**Pull request closed without merging**
