### PR TITLE
Refactors mech construction

### PR DESCRIPTION
**Pull request by jdawg1290**
## About The Pull Request
Refactors mech construction to dynamically generate the construction step list. Now just specify the circuit board types and plating types to use the standard build process, or specific phases can be customized by overriding the different steps procs or by overriding get_steps entirely. (HONK does this). 

## Why It's Good For The Game
Implements code reuse for the common construction steps and facilitates addition of new mechs.

## Changelog
:cl: JDawg1290
code: mech construction refactored
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
And you're sure this works? This doesn't violently break things, make the server stop running? We can actually touch Mech code without breaking everything?

I'm shocked.

**Comment by jdawg1290** [comment]
yes i’ve tested it on local, the mechs with special steps build fine.

**Comment by optimumtact** [comment]
good change, but this isn't mech code so it's no suprise it was easy

**Comment by jdawg1290** [comment]
Baby steps

**Comment by zxaber** [comment]
>Firefighter outer plating now only requires one stack of 5 plasteel, bringing it in line with other mechs.

I won't complain about firefighters being cheaper, but there was a point to them costing a bit more in plasteel than the MK-II (old) Ripley. Most maps generally provide enough plasteel in robotics for two MK-II's, but not the fifteen for a Firefighter (yeah, you can just go loot any of the other spawns, but that's beside the point).

It's actually a feature that makes Delta's robotics stand out; Delta is like the only map to give robotics 15 plasteel.

**Comment by jdawg1290** [comment]
Okay i've reverted the firefighter changed, added some basic comments, and the plating step generation actually works right now.

**Pull request merged**
