### PR TITLE
Adds a new ruin to Icebox, the post office.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Adds a totally originally and never before seen if you've never been to www.twitch.tv/tgstation in the past week, the mail office facility. This ruin is an iced over processing facility located in the underground region of icebox, where long ago Nanotrasen used as a HR and billing department mailroom. It fell into disrepair after a violent incident occurred, and eventually the whole situation was covered up, leaving the building to get blocked in by ice and rock. Until of course, you, the player find it.
## Why It's Good For The Game

Adds some much needed color to the icebox ruin pool. Features some puzzle gameplay as well as some well placed lore snippets. In addition, this PR comes with a change to hologrids that prevents them from being picked up because as I learned from that aforementioned event at www.twitch.tv/tgstation, you can pick up hologrids, breaking any and all puzzles that use them and make them VERY confusing to use!

## Map
<details><summary>map inside. </summary>

image

</details>

## Changelog
:cl:
expansion: A new ruin has surfaced on icebox. Signal pings indicated that may have been a post office, once.
fix: Hologrids once again cannot be picked up, as is intended.
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Did you fix the first key opening the room that has all the packages in it?

**Comment by ArcaneMusic** [comment]
> Did you fix the first key opening the room that has all the packages in it?

By obliterating that door and replacing it with another window, yes.

**Comment by maxymax13** [comment]
no pix no clix, mapdiffbot is die please provide images

**Comment by ArcaneMusic** [comment]
<details><summary>map inside. </summary>
image
</details>
Damn you to hell, map diff bot.

**Comment by EOBGames** [comment]
So, I figure I should clarify, once and for all:
image
image
Offstation map content, within reason, will be allowed. This includes ruins, shuttles, and the like. Ghost roles are unlikely to be accepted, barring very good reasoning. While I won't reject gateway missions outright, they're going to be fighting an uphill battle. In addition, a particular focus will be put on icebox, which is currently quite lacking in exploration potential. If you're in doubt as to whether something will be accepted, don't be afraid to ask a maptainer, either myself or Maurukas.

It's my hope that this should ease the current drought of content on icebox and provide an easier entrance to mapping for the codebase than the viper pit that is station mapping.

**Pull request merged**
