### PR TITLE
[DNM][WIP] XGM gas mixtures

### PR DESCRIPTION
**Pull request by mloc**
new, generic, non hardcoded gas mixtures ported from bay.
This PR will not be merged before #6644.
putting this up for feedback, map still needs to be fixed and other issues ironed out.

todo:
- [x] fix fires appearing out of nowhere, strange temperature increases?
- [ ] fix superconductivity
- [x] fix fire code in general
- [x] fix / redo overlays
- [x] look into making init_gas easier to use
- [x] fix map errors, convert everything to init_gas (oh god)
- [ ] organize & clean up __xgm_gas_mixture.dm, maybe split up
- [ ] write docs

### CODE REVIEW

**Comment by ike709** [comment]
is this dead or what?

**Comment by Mloc** [comment]
not yet, too much stuff on my plate right now.

**Comment by WJohn** [comment]
This is like super dead now isn't it?

**Comment by Dorsisdwarf** [comment]
6644 is never being merged, so, uh, what?

**Comment by Cheridan** [comment]
@Dorsisdwarf #6706

**Comment by Miauw62** [comment]
rip

**Comment by Razharas** [comment]
@Mloc can post here if it will appear alive again

**Comment by duncathan** [comment]
A moment of silence for those who went before

**Pull request closed without merging**
