### PR TITLE
Pink kitty ears

### PR DESCRIPTION
**Pull request by Nokia2Student**

### CODE REVIEW

**Comment by Nokia2Student** [comment]
How do I delete it damn

**Comment by Imaginos16** [comment]
Isn't this redundant? Besides, current kitty ears are greyscaled, pretty damn sure you can just do some code modifying to get what you want without having to add yet another sprite that is essentially a duplicate.

**Comment by Nokia2Student** [comment]
> Isn't this redundant? Besides, current kitty ears are greyscaled, pretty damn sure you can just do some code modifying to get what you want without having to add yet another sprite that is essentially a duplicate.

I made this pull request by accident

**Comment by Imaginos16** [comment]
Alright.

**Pull request closed without merging**
