### PR TITLE
New botany plant - Lanternfruit

### PR DESCRIPTION
**Pull request by Toastgoats**
## About The Pull Request

So I noticed the code references an Ethereal plant called "Lanternfruit," a sour pear-like fruit used as flavoring for a few foods and drinks. However, this plant doesn't actually appear in the game, this pr hopes to remedy this while also bringing some new hybrid potential to the table for botany.
Lanternfruit2
lanternfruit stages2
lanternfruit product2
lanternfruit seeds2

In essence, the plant contains sugar, liquid electricity, and sulfur; making it the easiest way to obtain the latter two chems, allowing botanists to experiment more with potential chemical recipes, and in theme with the plant itself, make flash powder. The justification for containing sulfur being that grapefruit gets its signature smell from a sulfur compound.

The plant can also be fermented into voltaic wine, which has some gimmick potential for particularly snobby Ethereals.

I also shamelessly hue shifted the maintenance seed packets, what can I say? They're good sprites.
## Why It's Good For The Game

Chem synergies are the lifeblood of high level botany, and worldbuilding is always fun too!
## Changelog
:cl:
add: The Ethereal Vintner's Union has been "convinced" to trade their signature Lanternfruit with Nanotrasen!
image: Sprites for the aforementioned fruit.
/:cl:

### CODE REVIEW

**Comment by Toastgoats** [comment]
Oops, yeah, tried to use the github desktop app for once, fucked something up, my bad.

**Comment by Wallemations** [comment]
https://media.tenor.com/qI39rb_VUn4AAAAC/plantern.gif

**Comment by Wallemations** [comment]
Make it dispel smoke (just kidding I know this is a practically impossible task)

image

**Review by MrMelbert — COMMENTED** [review]
You should make the graft gene `/datum/plant_gene/trait/glow/yellow`. (I know we can already graft it from Holymelons, but I think it's a missed opportunity otherwise.)

**Comment by Toastgoats** [comment]
> You should make the graft gene `/datum/plant_gene/trait/glow/yellow`. (I know we can already graft it from Holymelons, but I think it's a missed opportunity otherwise.)

Personally I kept it blank so anyone growing it can have quick access to perennial if they're making hybrids. But I'll definitely consider it.

**Comment by Wallemations** [comment]
> > You should make the graft gene `/datum/plant_gene/trait/glow/yellow`. (I know we can already graft it from Holymelons, but I think it's a missed opportunity otherwise.)
> 
> 
> 
> Personally I kept it blank so anyone growing it can have quick access to perennial if they're making hybrids. But I'll definitely consider it.

If you want perennial you can just graft roughly 50% of plants to any other plant, definitely go for the glow

**Comment by EricZilla** [comment]
I really love these, hilarious had the same thought for a fruit in the past, and would like to say, it would be really funny if you could stick them into light sockets like lightbulbs

**Review by MrMelbert — APPROVED** [review]

**Comment by deathrobotpunch** [comment]
wait, are the seeds going to be available at roundstart botany seed dispensers or found in maints?

**Pull request merged**
