### PR TITLE
Revert "Redesigns the shuttle bar"

### PR DESCRIPTION
**Pull request by coiax**
Reverts tgstation/tgstation#18754

Merged against maintainer's wishes, and broken.

### CODE REVIEW

**Comment by Niknakflak** [comment]
Not needed, a PR to fix the bug exists. Sorry.  Also kneejerk revert

**Comment by Militaires** [comment]
# much better.

**Comment by Niknakflak** [comment]
Also, if you do a straight revert, you are technically going back to a build of the shuttle that is still broken due to path changes, a bug which I fixed but did not cause

**Comment by Iamgoofball** [comment]
why the fuck does it have a xeno maid

**remember when we weren't throwing fetish content everywhere guys**

**Comment by Niknakflak** [comment]
#18834 is a much better option

**Pull request closed without merging**
