### PR TITLE
Crate edits 

### PR DESCRIPTION
**Pull request by Diegoflores31**
## About The Pull Request
reduces the black borders to make the crates mix better with the other sprites.

## Why It's Good For The Game
makes my eyes less hurty
BEFORE
image

AFTER ( examples , this bas been done for all crates)
image

## Changelog
helg2 , diegoflores31
:cl:
image: modified crate sprites
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
While you're here, one thing that was brought up is that crates don't currently line up with mulebots anymore as a result of the change. Could you look into that while we're adjusting it?

**Comment by CMDR-Gungnir** [comment]
Would it be possible to bump the lid up a couple pixels while you're at it? Hinges Don't Work Like That and it always bugs me.

**Comment by Rex9001** [comment]
I know you are getting a lot here, but would it be possible to bump the crate itself up a bit? Just so it doesnt rest on the bottom of the tile.

**Comment by kinneb** [comment]
pictures, people! pictures!

**Comment by LemonInTheDark** [comment]
> I know you are getting a lot here, but would it be possible to bump the crate itself up a bit? Just so it doesnt rest on the bottom of the tile.

don't think this is possible via sprites, lid's too big isn't it?

**Comment by Pumpkinoe** [comment]
> don't think this is possible via sprites, lid's too big isn't it?

the lid already goes beyond the tile it's on when it opens actually

**Comment by YehnBeep** [comment]
> pictures, people! pictures!

https://github.com/tgstation/tgstation/pull/75883/checks?check_run_id=14028727280

(Expand the 'modified' heading)

**Comment by Time-Green** [comment]
> > pictures, people! pictures!
> 
> https://github.com/tgstation/tgstation/pull/75883/checks?check_run_id=14028727280
> 
> (Expand the 'modified' heading)

We want to see it INGAME!!

**Comment by TheVekter** [comment]
Please post a screenshot of them in-game, ideally with the old (new?) crate sprites next to them. I can show you how to do this on Discord if you need help.

**Comment by Diegoflores31** [comment]
integrates #75895 into this PR .

**Comment by TheVekter** [comment]
> integrates #75895 into this PR .

You might want to get with @Helg2 if you haven't already because it sounds like they made a mistake and might not want it integrated.

**Comment by Diegoflores31** [comment]
> > integrates #75895 into this PR .
> 
> You might want to get with @Helg2 if you haven't already because it sounds like they made a mistake and might not want it integrated.

i havent copy pasted his PR i have done fixed the same issue . so it should be fine

**Comment by Wallemations** [comment]
Can you please show pictures of what it looks like _in-game_ as well? Y'know like, open up the game with your changes & send a pic of your dude next to some crates. It helps a lot compared to just static images on alpha-backgrounds.

**Comment by TheVekter** [comment]
Oh yeah, that looks way better.

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
