### PR TITLE
Maps are now voted on at the end of the round

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl:
add: If the map is to rotate and the config is enabled, a vote will be called for which of the available maps to rotate to when it normally would have been selected
del: Removed preference based voting
/:cl:

99% of the time people pick their favorite map the first time they set their prefs and then forget about it. Having them make the decision consciously each time can lead us to find what maps the players actually gravitate to on a daily basis. i.e. Does everyone hate pubby or is it just everyone loves meta?

This just uses a standard SSvote run

### CODE REVIEW

**Comment by Jalleo** [comment]
It should still be chance based if its below 80% voted for with a map.

**Comment by Cyberboss** [comment]
People will learn to vote or suffer 🔥

**Comment by davethwave** [comment]
This is miraculous...

**Comment by MMMiracles** [comment]
time to bring back cere

**Comment by GuppyLaxx** [comment]
ooc remember to vote deff guys pls

**Comment by pubby** [comment]
No randomness involved? It seems like Meta will win 100% of the time.

**Comment by optimumtact** [comment]
@Cyberboss if the vote interface is the normal shitty vote interface I am vetoing it, make a nice UI for this

**Comment by Dorsisdwarf** [comment]
wasnt the whole point of the weighted rng system to prevent "the most popular" map from being the only one that ever gets played?

**Comment by Spaceinaba** [comment]
I'm gonna miss everything that isn't meta, although now that I say it having the votable maps change every day could be interesting.

**Comment by barbedwireqtip** [comment]
why not just make it so that the more votes a map has, the more likely it is to be picked?

**Comment by Tlaltecuhtli** [comment]
make it a standard vote please no weighted voting ok

**Comment by Kromgar** [comment]
No one ever wants pubby

**Comment by nicbn** [comment]
Just make it 100% random, don't pretend SS13 is democratic

**Comment by ExcessiveUseOfCobblestone** [comment]
Have Sybil/Basil run different map rots :^)

**Comment by Iamgoofball** [comment]
just casually testing github maintainer hide stuff dont mind this post

**Comment by optimumtact** [comment]
@Dorsisdwarf did you delete my comment?

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
Keep the preference, make the preference be your default vote, run a normal poll but people don't have to vote if they want their default vote.

**Comment by MrStonedOne** [comment]
also keep the weighted random but do a 50/50 prob for fptp or weighted random. (configurable???)

**Comment by Jalleo** [comment]
What the stoned one said.

**Pull request closed without merging**
