### PR TITLE
adds new ambience to lavaland and spooky places

### PR DESCRIPTION
**Pull request by ghost**
:cl: floyd
soundadd: new ambience for lavaland and spooky places
/:cl:

dont ask how i got this https://vocaroo.com/i/s0stVfAWYCpc you dont want to know\

edit: alternate version pick ur fav: https://vocaroo.com/i/s1YQYtpD9f3w

### CODE REVIEW

**Comment by HydroFloric** [comment]
Stop, halt 2spooky4me

**Comment by yoyobatty** [comment]
Pretty spooky

**Comment by Potato-Masher** [comment]
Yeah, thought I heard that from somewhere. 

https://vocaroo.com/i/s1BCEuM8dB5h

You can't hide from me.

**Comment by Qustinnus** [comment]
:^)

**Comment by ShizCalev** [comment]
do you have permission from the original artist to use the sample

**Review by ShizCalev — COMMENTED** [review]
do you have permission from the original artist to use the sample

**Comment by Qustinnus** [comment]
this falls under fair use for audio

**Comment by Dorsisdwarf** [comment]
a fun idea but doesnt hold up as a sound on its own

**Comment by Qustinnus** [comment]
Its a small section that's been heavily transformed and does not resemble the original product enough to make any possible dents in the original products market.

Besides that, it's for nonprofit entertainment which is allowed because the other 3 conditions are met very well

**Comment by Therapist1** [comment]
Memes aside, this just doesn’t sound spooky.

**Pull request closed without merging**
