### PR TITLE
Fixes Honk and Odysseus mech strafe mode, allows Ody and Gygax to turn and move in one step while not strafing.

### LINKED ISSUE #46260: H.O.N.K mech strafing mode broken
## Reproduction:
1. Make honk mech
2. Jump in and toggle strafing mode
3. Still rotating while moving

Also i was unable to detach any equipment from mech there was no button in interface

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Fixes #46260. Makes Odysseus and Gygax able to move and turn in one step. Cleans up the HONK code for making clownshoe step sound effects.

## Why It's Good For The Game

Intended to be a fix for #46260, but I was told in the code discord that some people like how the Ody can move and turn in one step. This actually seems like a cool feature for a few "lightweight" mechs, so I added it to the Ody and Gygax as a feature. In both cases, it's overridden if Strafe is enabled, or if the user is holding the Strafe override key (Alt).

## Changelog
:cl:
fix: Strafe mode now works correctly on Honk and Odysseus mechs
add: Odysseus and Gygax mechs can now move and turn in one step if they're not set to strafe mode. This can be overridden with Alt to turn in place.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Could you add a way for the Odysseus and Gygax to turn in place? Doesn't strafe mode keep a mech from turning?

**Comment by zxaber** [comment]
On other mechs, holding alt will bypass strafe mode so that you can turn once without having to click the button. In this case, I have alt bypassing both strafe mode and also the move+turn thing, so that the mech can turn in place.

**Comment by kriskog** [comment]
That seems really out of place for the Gygax. Why?

**Comment by zxaber** [comment]
Gygax is supposed to be a fast, less armored alternative to the Durand. I figure it would help cement that idea a bit, without being too terribly powerful. Really, this lets the Gygax round a corner and have a shot lined up quicker than the Durand, but that's about it.

**Comment by kopoba** [comment]
Do i need to make another issue about missing button to detach equipment?

**Comment by zxaber** [comment]
I would. It's a separate issue and I'm not yet sure why the button is missing or how to go about fixing it.

**Comment by actioninja** [comment]
since the stupid powered actuators auto stun is removed this is fine

**Pull request merged**
