### PR TITLE
Salt for the salt shuttle

### PR DESCRIPTION
**Pull request by Niknakflak**
Adds coiax's ORIGINAL, AMAZING design of the emergency_bar as an option to load with the shuttle manipulator.

Coiax said to make my own design which I basically did, so I'll readd his original instead of his dumb revert.
#18984 can be closed now

### CODE REVIEW

**Comment by coiax** [comment]
I am only okay with this if my shuttle is the Emergency Bar Shuttle Original Recipe, and Niknak has to have the New Coke Bar Shuttle.

**Comment by Niknakflak** [comment]
Quit being a faggot, it's literally a number

**Comment by MMMiracles** [comment]
niknak secretly trying to be number 1

**Comment by KorPhaeron** [comment]
enough

**Comment by coiax** [comment]
See, no one questions other people's primacy of their features, I wouldn't be able to get anything merged about Clockcult that Joan or Xhuis didn't like, but suddenly OH NO, ITS ALL OPEN SOURCE, WHO CARES ABOUT COIAX'S OPINION. I blame @optimumtact for enabling this, I wouldn't have to play revert-war if Niknak's PRs weren't merged for dumb ass reasons

**Pull request closed without merging**
