### PR TITLE
Revert "remove y##f in h##l spray, adds furry pride spray"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#68077

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
The day of the messiah's rise is here, the end times have come

**Comment by jlsnow301** [comment]
closing this for not including the pr template. we have standards here

**Comment by DemoCrack** [comment]
basde oragnes? w tf

**Comment by san7890** [comment]
image

What changed?

**Comment by optimumtact** [comment]
I lied

**Comment by Mothblocks** [comment]
@optimumtact Let's force ninjanomnom to take a side on this for fun

**Comment by DemoCrack** [comment]
literally 1489

**Comment by Mothblocks** [comment]
@ninjanomnom You have to decide

**Comment by LemonInTheDark** [comment]
where is our head head head coder

**Comment by Farquaar** [comment]
lol

**Comment by ninjanomnom** [comment]
I like the ridiculousness of the yiff in hell spray but if someone wants to add a new spray to counter it then I'm fine with that.

**Comment by robbertapir** [comment]
lol

**Comment by Farquaar** [comment]
> I like the ridiculousness of the yiff in hell spray but if someone wants to add a new spray to counter it then I'm fine with that.

Bro if anything the furry pride spray would be used as a troll. I was planning to play clown tonight to spray furry pride all over random people's departments lmao

**Comment by RedBaronFlyer** [comment]
Furries

Furries2

Furries3



Could we at least have both?

**Comment by ninjanomnom** [comment]
As I said, having both is fine. Someone has to make the pr though.

**Pull request merged**
