### PR TITLE
Adds several weapons and cost adjustments to Gangtool

### PR DESCRIPTION
**Pull request by Robustin**
Switchblade down to 5 cost from 10.

C4 down to 7 cost from 10.

Added:
- Shuriken (3)
- Sharpener (3)
- EMP Grenade (5)
- Frag Grenade (minibomb-lite, 10)
- Stimulants (15)
- Sniper Rifle (40)

### CODE REVIEW

**Comment by Bawhoppen** [comment]
here we go

**Comment by Bawhoppen** [comment]
do you intentionally open these in the dead of night so less people will notice them?

**Comment by Robustin** [comment]
Do you really think I give a shit about when I open my PR's?

If we're going to bring GW back let's breathe some life into it. Currently points basically exist to finance the boss's Uzi fetish and hand out spraycans to the plebs so he can afford more uzi ammo. I'd like to move away from that by offering more lucrative & cheap weapons. 

I may actually turn the Gang income into a distributed system but this is a good first step.

**Comment by Bawhoppen** [comment]
stop trying to gather intent from non-explicit text

**Comment by FantasticFwoosh** [comment]
I find flaws with pretty much all of these points, im not sure you're grasping the theme of what a gang even is.

> No shuiken, replace it with something actually gangster,  like a readymix molotov or something

> I am half ok with a sharpener, but adding more whetstone blocks sounds like complete BS and will make captain sword instant sever (yeah the cap sword sharpened can decap in 1 hit) too strong

> Grenades are ok, just make them a little less explicit, a pipebomb (to stick to the theme) that shoots out projectiles that embed would be well themed and appropriate here, outright EMP is not needed when you can just UZI the borg to death.

> Weren't stims a little flunky lately? I forget but otherwise i dont really care about this one.

> 1) you didn't supply ammo and 2) no no no no, sniper rifles are more of a operative/specialist item currently, this is gang warfare not "Hitman"

**Comment by Bawhoppen** [comment]
@FantasticFwoosh To be fair, gang is supposed to encompass all different types of gang style wise (hence why we had sleeping carp). If you follow this logic, shurikens do make sense (ninjas or something), as well as all the military-grade equipment. The sharpener makes sense if you imagine it like a scene from a movie where some badass is sharpening his knife while being talked to or something.

**Comment by FantasticFwoosh** [comment]
It needs to be explicit since we only have one type of gang bawhoppen across different "Tribes" other than name and logo they are identical typical gangers.

Yakuza, some ex army dudes etc whatever fine but the theme currently is that these are small to medium arms bought on the black market. If you actually changed the gang tool's lore & description to buy good from the black market and then added these items to a pool of cycling options (as and when they are availible) then it becomes a competitive change.

I dont like them having these items ALL of the time, just in favour of gang heads (usually the richest) competing to buy black market stock weapons & objects the fastest.

**Comment by CPTANT** [comment]
This is something I don't really care about any way.

I think the most important gang fixes are 3 gang leader start. removal of implant breakers and 3x3 dom.

**Comment by lzimann** [comment]
Now you are just making gang a team traitor.

**Comment by KorPhaeron** [comment]
Seems like random bloat which wont help with security stomping every 5 minutes in

**Comment by Dorsisdwarf** [comment]
ay

**Comment by optimumtact** [comment]
gang was removed

**Comment by Robustin** [comment]
If you expect me to atomize these bloody PR's Kor you can't expect every PR to be THE solution to security stomping everyone.

Its not bloat, its a step toward making the whole points system more interesting and viable for people who aren't the boss.

@lzimann 

Right because the team antag with stechkins, edaggers and automatic weapons. Totally didn't play like a syndicate role. Stuff like the shuriken, whetstone, and stimpack would give gangs offensive tools that weren't just stolen sec gear or traitor guns.

**Comment by lzimann** [comment]
This is only adding uplink bloat to the gang tool. This won't help with the problems of the gamemode at all(which is mainly the same as every conversion gamemode).

**Comment by Robustin** [comment]
I'm grabbing low hanging fruit in this PR. Right now the point system is well.. pointless. The gang boss saves up for an uzi unless one of his lieutenants cucks him by buying something else first. For the gang's "foot soldiers" its basically rev v. rev. 

Shuriken is a really nice throwing weapon, its very strong without being OP. I mean we used to have an entire gang themed around Yakuza (I killed them, RIP) so I don't see a reason to lock out anything that doesn't fall into 1920's Chicago gangland themes. I feel the same way about the Sniper - its strong, yet fair and doesn't see enough use because both have to compete with stuff like Revolvers and SAWs in the Syndicate lineup. 

I'm open to taking a different approach to this but I don't feel that any of this is "bloat". I thought very carefully about each addition and always asked myself, "If I was a gang boss would I ever buy this?"

My ultimate goal is (hopefully) to have the average gang brawl be more of a melee than a shootout, but I don't know if thats possible until Gang "income" gets decentralized.

**Comment by PKPenguin321** [comment]
EMPs might be mode breaking since they could kill dominators through walls.
I think the only new things worth adding in this are stimulants and sharpener, as well as the cost reductions of already existing items. Other items seem a bit much

**Comment by Bawhoppen** [comment]
Honestly I don't think these are inherently bad additions but the problem as is, is that probably nobody will buy them very much considering how influence is gained

Gangs need more things to do than just spraying walls to gain influence

**Comment by PKPenguin321** [comment]
You can get influence by wearing gang outfits too

**Comment by Robustin** [comment]
Given the concern about wall spam and shorter dom times in my other PR's, maybe giving EMP's to gangsters is actually a really good thing.

Gangs would be encouraged to fan out and control an area (like they should) instead of just huddling up in an r_wall box. 

@CPTANT 

If I didn't have like 3 other big projects on my plate, decentralizing would be the very next thing I'd add. I'd make it an action-button based on an "implant" that is inserted by the gang pen. 

Individual rewards for tagging (only for your tags that survived when the points tally, to prevent abuse) and dressing up should be good. Clothing points going to the individual is also smart because it gives each player a direct cost/benefit instead of a gang leader pooping out leather jackets and ordering people to wear them so he can buy another uzi mag. 

I'd love to see it basically become its own system where you can make initial point outlays into clothing that will earn you more points in the long run. It starts off cheap, low-key, and low reward but escalates into increasingly obvious/gaudy/expensive clothing that also provides greater rewards. Of course any of these "investments" backfire if you spend all your early points on clothing while some greyshirt in a rival gang who bought a switchblade ASAP cuts you up and steals all the clothes off your corpse.

Clothing would directly reflect status since only the most confident or skilled gangsters would be decked out in a bunch of "loud" clothing that made them a walking target. 

What could possibly be more gangster than spending all your income on Space Jordans only to get murdered by another gangster who sees you wearing them and realizes that killing you is a lot cheaper than buying their own. 

Jesus someone help me code this already.

**Comment by PKPenguin321** [comment]
No, EMPs would be awful, I assure you

**Comment by Lumipharon** [comment]
Give gangs access to shit like improv or dual barrel shotguns. Sawn down by default for added FUN, and make various ammo types purchasable by the box.

**Comment by lzimann** [comment]
@tgstation/commit-access I don't like this at all(not because lol gang), adding uplink bloat is kinda awful. I'm closing this in 24h if no one says anything/merge this.

**Comment by Lumipharon** [comment]
But what does 'uplink bloat' even mean? if we log what items traitors buy I'm sure more than 50% of shit almost never gets bought outside of random crates, but that doesn't mean it should be removed.

While redundant or just copy paste tator shit might be undesirable, I don't understand why simply adding more stuff (as long as it's usuable and balanced) to the uplink is an issue?

**Comment by lzimann** [comment]
Maybe uplink bloat is the wrong wording. But this is just adding random traitor items to gang.

**Comment by Lumipharon** [comment]
I don't really agree with the sniper rifle or the shuriken, but the rest seem fairly fluffy and balanced.

**Comment by Robustin** [comment]
I feel the opposite about both, though the shuriken might be a little too oppressive for newbie victims who don't know how to catch them. 

I really like shurikens because they aren't like the guns where you're crit in one second and the fights where you get hit by one can play out in really interesting ways and it opens the door to some great hit and run strats. 

Snipers are extremely balanced in my view. The rate of fire is incredibly slow so its really difficult to 2-shot anyone, but in certain contexts its extremely satisfying to use. I honestly think I overpriced the sniper. Its probably going to be newbie bait where someone takes it so they can Xxnoscope360xX but then just get killed by someone rushing them with a stechkin.

I will wait and see though, Gang War at 3.5% makes it reeeeeallly fucking hard to sense how the mode is adjusting. I want to de-centralize points next and make the income system much more fun but it's kind of discouraging since I might go weeks without being able to see a round in action.

**Comment by optimumtact** [comment]
that's what the stechkin is supposed to be afaik

**Comment by Lumipharon** [comment]
stech is like 3-4 shot crit, and you can spam it pretty fast.

Back in ye olde NT station days, there was a (autolathe producible honk) glock. It was a 20 brute pistol with a fairly small mag. Just do something like that.

I disagree with sniper not from a balance point of view but fluff - but that's honestly not a big deal.

With the points system, if you're talking decentralisation in the sense of line members getting access to their own points, then what if the gang leaders get 50% of the gang income to their shared gang tools, while the line members get the rest split between them. Then allow them to supplement their personal income by spraying tags/wearing uniform etc, which in turn rewards the gang as a whole.

**Pull request merged**
