### PR TITLE
Make Kosmicheskaya Stantsiya 13 great again

### LINKED ISSUE #30379: Derelict drone shells not showing up on ghost mob spawner menu
as the title suggests

mob spawners are a recent feature that allows ghosts to easily see and pick what ghost  roles are available from the start

derelict drone shells are not included on the list even when they're present and available to pick, so you have to orbit them instead

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Drone shells have been refactored to use mob spawners, and now show up in the ghost spawner menu. Seasonal hats were sacrificed in the process. The spawners are also anchored to prevent players moving them off the derelict.

The derelict drone flavor text and laws have been relaxed slightly, and made more clear as to whats allowed for derelict drones in particular. Effectively: drones are not allowed to leave KS13, the no interaction restriction has been limited to sentient beings, and interaction is now allowed while on KS13. Going to the main station for any reason is explicitly disallowed.
image

The derelict itself has gotten a slight overhaul to make fixing it slightly more feasible. There is a vault you can get into after setting up power which contains materials to help fix KS13. The amount of air mix has been greatly increased.

## Why It's Good For The Game
The derelict has great potential for allowing players to learn about construction, as well as taking up the challenge of properly fixing the station. These changes makes that more realistically achievable without relying on random asteroid spawns close by that you werent really supposed to go harvest from.
Fixes #30379

## Changelog
:cl: Skoglol & Naloac
tweak: Make Kosmicheskaya Stantsiya 13 great again! No I mean it, go do it. The derelict has gotten a slight overhaul, and it is now more feasible.
tweak: Derelict drones has had their laws laxed slightly while on the derelict. It should now be harder to be forced into breaking them.
refactor: Drone shells are now mob spawners and show up in the ghost spawner window.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
One problem I had with the station was that it utterly lacked materials to reconstruct it. It would be nice if there was more materials lying about for the use in construction and restorinf the station.

**Comment by kriskog** [comment]
Thats why we added the vault. It has lots of materials, although you'll still need to conserve somewhat.

**Comment by Tlaltecuhtli** [comment]
more loot

**Comment by carlarctg** [comment]
time to mass driver into derelict, take all the mats, then mass driver back

**Comment by kriskog** [comment]
Have fun setting up power and waiting for the vault controller to charge. Oh yeah, we gated it to prevent feeding you nerds.

**Comment by Striders13** [comment]
Don't get me wrong, this is a great overhaul and actually makes this thing playable, but I'm not sure why you have to keep this restriction on not leaving the ks13, since you might as well play one of delta station staff with no laws restrictions and much more stuff to build (they even have singulo generator out there)

**Comment by kriskog** [comment]
Because drones are shitstorm generators. If they are forced to stick to their own station, it won't near be problematic. Without the limitation, people will start going to the station again.

**Comment by bgobandit** [comment]
can we move seasonal hats to borgs then

**Comment by dr-bee** [comment]
> 
> 
> Because drones are shitstorm generators. If they are forced to stick to their own station, it won't be near as problematic. Without the limitation, people will start going to the station again.

It was primarily because they were ghost roles with extra rules from the days before ghost roles. Remove the rule restrictions and nerf the hell out of them and they might be actually fun like they are on other servers.

That being said, Could you add a broken supermatter? Derelict drones would make for a great location for an engine tutorial area or area for experimental setup testing.

**Comment by kriskog** [comment]
I won't be removing the rule restrictions on the drones. Feel free to do so after this is merged though if you think that is wise.

**Comment by ExcessiveUseOfCobblestone** [comment]
Drones are not coming back into general play until you can get headmins on board.

**Comment by kriskog** [comment]
As for engine, I am hesistant to add ones that can affect the round outside KS13. Yes the oldstation has the singulo, I still dont want to. The TEG is simple enough to set up, and it's fitting that the derelict may be used to learn about it. Please note we have filled in some spaces with missing areas to make using the fixed space below grav gen easier.

**Comment by ATH1909** [comment]
Aw, I quite liked being able to steal the drones from the derelict and bring them to the station. Could we not keep that bit in the game?

**Comment by kriskog** [comment]
No. The drones weren't allowed to go to the station before, because fuck drones on the station. The fact you could move them at all was dumb, and only a potential cause of headaches.

**Comment by davethwave** [comment]
I would ask to perhaps add something like a mat depot because you can't really do much with repairing and stuff with how much you are given as a drone. At least some extra metal, and glass in order to patch the place up.

**Comment by Naloacisamazing** [comment]
@davethwave  it says in the PR that there is a vault that contains matts to rebuild it. That was one of my main reasons for wanting to rework it. It also has greater air mix in the atmos area to allow someone to properly fix the atmos since in the current version its impossible.

**Comment by Arathianen** [comment]
So I keep replaying an idea in my head, shared it with people and wasn't instantly called a moron so here it goes:

The station is supposed to be a tutorial but can't act LIKE a tutorial because the apes at the station typically will call the shuttle before any meaningful progress can be made. That is something inherent in the game and can't be changed.

So, the obvious way to stop it would be for changes to carry over shifts.

That means:

-A drone could legitimately fix a station over multiple rounds

-the place can act like a proper 'set up your own station' tutorial

-engineers with autism projects can make them somewhere legitimately where the grey will (probably) not toolbox them to death

-the station might even get into a usable enough state that legitimate players could end up using it.

That would mean there would need to be a reset button. A self destruct button with 1m primer that will explode the station and reset the whole thing next shift. Also, if no one picks a drone role, it resets automatically the next shift.

I have no idea how hard that would be to program. I do know things can carry over multiple shifts though like the CMOs cats.

**Comment by kriskog** [comment]
Thats pretty far out of scope of this PR, feel free to post it on the forums for someone to pick it up though. 
Generally we do not have a lot of persistance on tg, and thats for the better. You weren't around for the proper smuggler satchels, but even one item saved between rounds was too much as some people (me included) hid and retrieved shit every round for months until it was removed. Imagine being able to consistently hide lots of stuff on the derelict.

**Comment by Arathianen** [comment]
Yeah, I can definitely see how that could be abused.

The difference with satchels would be that satchels passively persisted if hidden well enough. Ks13 would need to be actively maintained by drones for it to persist and a single button press could send it all to hell.

Of course, even that restriction could be abused.

It's a neat idea but way too utopian thinking maybe.

**Pull request merged**
