### PR TITLE
Adds the white cane. (Bounty Code)

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

image

This PR adds the white cane. 

It can be crafted using 3 iron rods. Additionally, white canes can be purchased from the medical vendor, differentiating them from the costume canes.

White canes are transforming items that can be folded down from a small size to their fully extended versions, which are too large to store in a bag.

Sprites are still subject to change at the moment.

## Why It's Good For The Game

A white cane like this is traditionally used in the real world to designate that the holder is blind or seeing impaired. This is much the same, as the wielder doesn't get too much of a combat or situational advantage, but is meant as more of a visual indicator that the wearer is blind. 

## Changelog

:cl:
add: A white cane, an indicator that the wielder is blind, can now be bought and crafted from medical vendors and iron rods respectively.
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
Maybe it can have some force but will break after several hits, like chairs do

**Comment by anclandor** [comment]
"A white cane like this is traditionally used in the real world to designate that the holder is blind or seeing impaired."
I think well that is one of the effects, the main usage of a cane by a blind person is to feel out the area around them without stepping there/placing their hand there.

**Comment by MrZoraman** [comment]
I was kind of wondering, because changing the radius of the "darkness" around the player might be tough/complex
what if holding a white cane simply sped up the examining things check?

**Review by tralezab — APPROVED** [review]
good job

**Pull request merged**
