### PR TITLE
removes the odysseus mech

### LINKED ISSUE #50078: Putting someone in zero-G into the Odysseus' mounted sleeper results in them floating when ejected in gravity
## Round ID:
**Server-Side Code Modifications:** https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

**Round ID:** 132538
**BYOND Version:** 513.1508
**Master commit:** 2368a8acc3d8a1d6bdfb5698e2bd7bb767c235e3

**Local commit:** ee81158ee1243d25af998738644b53af8f071980
**Server tools version:** /tg/station 13 Server v3.2.6.2

## Testmerges:
**#49344:** '[READY] Space Dragon Rework' by IndieanaJones at commit 6665b02929

### LINKED ISSUE #87121: Medical Exosuit doesn't give medhud anymore
### Client Version:

515.1643

### Issue Summary:

Up until recently when hopping into an ody you'd be given a medhud overlay...but now, at least with posi mechs they don't get the hud anymore for some reason

### Round ID:

240001

### Test Merge Information:

- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)
- [Fixes multiple players being picked for the same single-slot command job roundstart.](https://www.github.com/tgstation/tgstation/pull/87005)

### Reproduction Steps:

Get a posi brain
Put it into an Ody
you can no longer see who needs healing

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Removes the Odysseus mech and the 3 associated mech equipment tools, as well as the mech wreckage (but keeps the toy figurine, since we kept firefighter too).
Closes #87121
Closes #50078

## Why It's Good For The Game

Odysseus has a really weird place in the design space- It is using the big combat mech system but instead it is used as a little gift for doctors that just sits in the medbay and doesn't do any actual mech action stuff, and I generally would like us to move away from mechs as job tools.
Its tools are not very good either, the medigun is something we generally keep away from non-antagonists as it takes gameplay away from doctors. The sleeper is a very weird tool to try to help people with, that is also partially replaced with the medical modsuit's spaceproof holobags. The syringe gun is just an antag tool really- its infinite reagent generation is something that is very niche and feels weird to be solely part of a giant mech. If we want a mechanic like this to stay in the game (other than bees where it already exists) it could be its own standalone machine.
I asked several medical players about it and they were either very indifferent to it, or disliked it for the medbeam gun taking away their job (and it's not like you can really reject it, you'd be an asshole for not taking a free buff like that).

## Changelog

:cl:
del: Odysseus mechs have been scrapped.
/:cl:

### CODE REVIEW

**Comment by Aliceee2ch** [comment]
>the medigun is something we generally keep away from non-antagonists
make it modsuit module (cmo one) then idk (plus nerf), i dont think it needs complete deletion

>The syringe gun is just an antag tool really.

no... infinite chems can be really useful

**Comment by Sealed101** [comment]
closes #87121
closes #50078
i think there's at least one more but i may have closed that one at some point

**Comment by Fikou** [comment]
> > the medigun is something we generally keep away from non-antagonists
> 
> make it modsuit module (cmo one) then idk (plus nerf), i dont think it needs complete deletion
> 
> > The syringe gun is just an antag tool really.
> 
> no... infinite chems can be really useful

i thought the chems were a part of the sleeper honestly

**Comment by Loafin34** [comment]
why do we gotta remove all these mechs that are better at their job than humans? The firefighter got removed because it was obsolete. and not as fun as the clarke. The paddy's straight up a roundstart security mech that carries a security team, and it works because it's a shitty mech. Why not give the odysseus some more updated equipment (I don't know, a teleporter beacon to medbay or something) and keep it around?

**Comment by Fikou** [comment]
> Moving medbeams to sci refined core buffed items or core required would be cool, with or without chem consumption with cores involved. Being able to use it as a dinky temperature beam weapon would also be cool.

yeah, the way i see a crew-accessible medbeam gun is 

- something with good feedback (though that should be a thing for all medbeams, stuff like sound playing as you heal someone)
- using a resource, like chems
- requires commitment, not just walking around and clicking anyone in range to steal the doctors job

> why do we gotta remove all these mechs that are better at their job than humans? The firefighter got removed because it was obsolete. and not as fun as the clarke. The paddy's straight up a roundstart security mech that carries a security team, and it works because it's a shitty mech. Why not give the odysseus some more updated equipment (I don't know, a teleporter beacon to medbay or something) and keep it around?

all of its equipment is flawed and redoing it would involve basically making the mech from scratch, when a medical mech is maybe just something not really needed. the only design space in which i see it is a transport for paramedics (for which they already have rollerbeds, bodybags, holobags- and you could make something bespoke like an ambulance if you wanted this) or help on a frontline (and nobody will make a medical mech during something like nuke op war), i do not think medbay should have a static mech that you walk in for 3 seconds to start healing someone and then leave

**Comment by Loafin34** [comment]
there is one medical modsuit per medical department, and sometimes when an instant death machine goes off there's too many dead bodies to move around. a big mech to haul everything over or stabilize them (say, a little vat of formaldehyde occupying their arm slot to inject them with) sounds great

**Comment by TheVekter** [comment]
I can't say I'm a fan of removing this without us having some kind of replacement for being able to haul a bunch of dying people around, like an ambulance cart or something. I know we have the bluespace body bag but I don't think we should be putting dying people into a thing that makes them unable to breathe.

Also cool with the medigun being moved to a core locked research item, but only if whatever core it's attached to is a singleton. Mediguns are stupid powerful and having more than one is just inviting some cunt to go HAHA CROSS THE STREAMS!!!!!

**Comment by Fikou** [comment]
> I can't say I'm a fan of removing this without us having some kind of replacement for being able to haul a bunch of dying people around, like an ambulance cart or something. I know we have the bluespace body bag but I don't think we should be putting dying people into a thing that makes them unable to breathe.

i think adding an ambulance would be neat but i dont think the odysseus is great at mass hauling dying people as its sleeper has only one slot. a ripley with a crate can do that better

**Comment by GuillaumePrata** [comment]
The only way to salvage the Odysseus is by turning it into a healing mech for other mechs, or lavaland Mecha doctor for miners.

The thing should never be inside medbay, it just makes the round a lot less interesting when one is parked there.

**Comment by necromanceranne** [comment]
I knew the time was coming for the Ody, since it not only lacked any interesting equipment at all, but that it had almost no code support for the many, many bugs it has accumulated over the years that would go unfixed for large spans of time. It has almost no reasonable place except to basically be a life support device while healing someone; and if thats the only purpose of the mech, we would be better off with a dedicated machine for that.

Fuck it, it's not worth keeping. I seriously can't think of a way to make it work that isn't just hanging onto it for nostalgia's sake.

(I will say, I'm going to miss this piece of shit, since my first ever mech murderbone was in an Ody using a hidden compartment scattergun and its ridiculous movespeed + turn rate at the time to play a soft fast mech with a onetap gun at point blank. I had a giant spider dropped on me for wiping out the station.)

**Comment by TwistedCicrularConvexLens** [comment]
I think pointing towards two visual bugs and screaming about how broken the oddy is code wise isn't fair. It's not maintained well (or at all) but it's not causing issues that are negatively effecting anything in a grand scale worth not reworking.

Also regarding the actual PR, I'm writing this at 3 AM so forgive me if I misspell anything.

>sits in the medbay and doesn't do any actual mech action stuff, and I generally would like us to move away from mechs as job tools.

Could you explain your reasoning behind this when Paddy & Ripley both help security and cargo respectively currently? Why are mechs bad as job tools? What makes them bad as job tools that doesn't deserve to be addressed at the core principles of mechs?

>I asked several medical players about it and they were either very indifferent to it, or disliked it for the medbeam gun taking away their job (and it's not like you can really reject it, you'd be an asshole for not taking a free buff like that).

Im my experience ( Terry/Lrp ), most doctors try and pride themselves on how fast they can revive/heal people. Whether that be through insane chem mixes or medibots or mending touch shenanigans, whatever. But being mad that your job is being made easier is not a reaction I've ever faced as CMO or medical.

I think I would be kinda mad as a patient if they're focusing on maximising their own percieved usefulness at the cost of other people's ability to even play. Sometimes no one is dead or it's a low threat round but the answer is not to force people to endure worse treatment so you have things to do, it's to recognise that if no one is injured in mebday you're doing well and can go take a break, have some roleplay or downtime until the next patient comes in. 

I won't get mad if someone doesn't instantly heal me with some 100 step recipe chem mix, but it's a spectrum of what's acceptable and removing non med medical stuff because only medical should be able to heal people or you risk outperformimg medical is petty. If you are healing people in med, you are part of med, you are not there to outperform them, you are there to help! This is in my opinion a problem with people's view on their job, not ody.

>The syringe gun is just an antag tool really- its infinite reagent generation is something that is very niche and feels weird to be solely part of a giant mech. If we want a mechanic like this to stay in the game (other than bees where it already exists) it could be its own standalone machine.

Create the machine first then remove the ody if it doesn't fit. Do not theorise on what could be made in the case ody was removed lest you delve into wishful thinking, because there's no guarantee anyone's going to code that. If a mechanic is being removed it should be being removed not because it is not great but rather it is actively bad or troublesome.

In the case of the infite chems themself, even if niche and wierd, there doesn't seem to be a case for removing it here. Moreso a note that it would be better elsewhere, but this doesn't justify removing it here. This is not a zero-sum you can have multiple sources of this one mechanic.

**Comment by necromanceranne** [comment]
I think literally any argument that boils down to 'actually, trivializing medical is good actually so nobody has to deal with medical' is probably good reason to delete the point and click medical invalidation machine.

**Comment by Wallemations** [comment]
RIP Odysseus, the cyclops got 'im

Honestly I think I'm most sad to see the medguns go since I always tended to use them to help stabilize people rather than fully make doctoring obsolete. Maybe a weaker anomaly-core-required version for modsuits like others in here said? One that's more meant to help keep patients alive rather than heal up battle wounds, something like that.

I'll fully admit I'm no balance guy though so

**Comment by necromanceranne** [comment]
I literally only used it for stabilization and it was because getting a stasis bed as a robo is a massive pain in the arse. I'm not convinced medibeams still working after exiting the mech is actually even intended in the first place.

**Comment by TwistedCicrularConvexLens** [comment]
So I've been looking through the [old PR](https://github.com/tgstation/tgstation/pull/14861)'s and turns , people were having the exact same discussion **Eight** years ago. So glad to see that nothing's changed.

> I think literally any argument that boils down to 'actually, trivializing medical is good actually so nobody has to deal with medical' is probably arguing better for deleting the point and click medical invalidation machine.

Ok. Question:

Why does medical need to be complex? Tend wounds is 4 clicks (one to start surgery, three to scapel-hemo-cautery), should we remove that for not being advanced enough?

(_Hyperbole yes, very much here, even I can see that, but if people are complaining about things being too simple or not complex enough, that becomes incredibly subjective and very easy to argue in some form or fashion **all of medical** is pointing and clicking. I understand this likely isn't the main argument to remove ody, so I'll be moving on._)

The med beam only heals brute/burn/tox/oxy damage. Not wounds, not blood and not organ damage. I can't exactly tell but I'm going to assume that the problem people have with the Medi beam is that it's relatively easy to make and attach to an ody and outperforms traditional med methods which have a bigger time investment to setup.

Which, if that is the case that med mains aren't happy about (sorry if it's not) I would argue having to rely on another department to make one of these for medical isn't as easy as it sounds. And for comparison, yes, chemistry is very complex for the medical benefits it can provide, it takes a lot of investment, and if we're comparing the two, the ody mech only requires mats and about 5-10 minutes’ worth of part printing/assembly compared to the 5-30 minutes it would take to setup a chem factory that can achieve a similar result. (This is ignoring cryo, which med have access to round start and not only heals all damage types same as Medi beam but also heals wounds too and has the massive investment of needing to insert a beaker and wrench a canister!).

Ultimately, yes, making a tool as good as the medibeam cost as less as it does can risk leaving those who invest into other healing methods feel invalidated or like they shouldn't have bothered in the first place, which would justfiy a nerf to medibeams.(But this is only the case in which robo, an entirely different department goes out of their way to research, make and equip one, and then drive it over to med, which can happen? But often, doesn't in my experience, odys are a rare gift if I don't directly ask for them).

_**However,**_ this is not a PR for the nerfing of medibeams, it is a PR to REMOVE ody. My points still stand that if you really don't like the medibeam, don't take it out on the mech! Make medibeam only heal brute/burn or have a higher research cost or any other reasonable nerf to medibeams that isn't deleting ody, because that isn't grounds for removal.

**Comment by SimplySmiley123** [comment]
> why do we gotta remove all these mechs that are better at their job than humans? The firefighter got removed because it was obsolete. and not as fun as the clarke. The paddy's straight up a roundstart security mech that carries a security team, and it works because it's a shitty mech. Why not give the odysseus some more updated equipment (I don't know, a teleporter beacon to medbay or something) and keep it around?

It could use some quality of life for the sleeper so it's less tedious to use and understand, maybe capacity upgrade for that sleeper so the mech could function as an ambulance for more then 1 person and not be outclassed by a single paramedic with a roller bed, or even better, bluespace bodybag, running at full speed to medbay.

**Comment by SimplySmiley123** [comment]
> Ultimately, yes, making a tool as good as the medibeam cost as less as it does can risk leaving those who invest into other healing methods feel invalidated or like they shouldn't have bothered in the first place, which would justfiy a nerf to medibeams.(But this is only the case in which robo, an entirely different department goes out of their way to research, make and equip one, and then drive it over to med, which can happen? But often, doesn't in my experience, odys are a rare gift if I don't directly ask for them).

And who's to say anyone in medical will even have time to pick that Ody up anyway, or use it.
It sure can have a medibeam or two, but it can't defib someone, it can't purge their chems, it can't do a brain surgery on the secoff that repeatedly tackle jumped into a wall, it can't fix organs as you said, so med doctors have less incentive to sit in it, at best the medbeam is used to help stabilise someone so they don't die or some gimmicks with the syringe gun which _is_ personally a welcome sight to me when seeing one handed to medical. Who doesn't want to play around more with their rare chems then they managed to make across the round.

And then there's also the fact mechs of any and all kind can and will get stolen if left alone for a moment too long.

I can see medbeam getting nerfed either in availability or effectiveness compared to the handheld medbeams, however little the latter option would make in this case, and sleeper getting updated to be both viable and relevant at all. Maybe the sleeper could have bigger capacity for how many people fit in it, 2 maybe 3 people, so the mech could act as an ambulance in case of mass casualties of whatever sort and not be outshined by whoever grabs a rollerbed and maybe some coffee if there's a breach.

**Comment by CRITAWAKETS** [comment]
I honestly don't see Odysseus medbeams as a problem? They're maybe a little too quick at healing but that's just something which can be nerfed rather than toned down. Having two medbeams that you can combine or split is actually a great mechanic for the Odysseus' real niche which is field healing.

Inside medbay it basically only makes tend wounds or chem mixes less necessary and that's about it, you still have organ damage and wounds to deal with which are usually going to be much more major than a bunch of brute. It's so little of an upgrade that I rarely see doctors even using it because _it's often times slower to jump into the mech than use tend wounds or chemicals._

Medbeams also have a huge vulnerability to toxins, they heal toxin much slower and don't purge any toxic chemicals. There's counterplay.

If you seriously want to remove something for utterly trivializing med, mediborgs have a full chemical repository that can be upgraded alongside a beaker, have cyborg movement mechanics, all access, surgical processor upgrade, faster tools than normal, crew pinpointer upgrade and a piercing hypospray upgrade. They can do everything out in the field and can trivialize doctors, and unlike the Odysseus don't have any Achilles' heels. And if you get around to this, you've also gotta remove the modsuit modules that somewhat equalize someone (albeit without hypospray) to the mediborg. THIS would be a good removal.

**Comment by DrAmazing343** [comment]
medborgs really are so powerful it's crazy I haven't seen an ided or something against them like ever

**Comment by DrAmazing343** [comment]
an ilive pr because I lived too fast

**Comment by SimplySmiley123** [comment]
> If you seriously want to remove something for utterly trivializing med, mediborgs have a full chemical repository that can be upgraded alongside a beaker, have cyborg movement mechanics, all access, surgical processor upgrade, faster tools than normal, crew pinpointer upgrade and a piercing hypospray upgrade. They can do everything out in the field and can trivialize doctors, and unlike the Odysseus don't have any Achilles' heels. And if you get around to this, you've also gotta remove the modsuit modules that somewhat equalize someone (albeit without hypospray) to the mediborg. THIS would be a good removal.

God medborgs are so much more annoying, even outside of trivialising medical doctor's work, like trivialising paramedic's main job of getting to people and getting them to medbay or treating minor issues on the spot, alongside being lethal little shits if the player is bloodthirsty with asimov, gets subverted lawset, or worst case scenario emagged and silently injects half the station with various poisons.

With addition of all-access because why the fuck not.

**Comment by moocowswag** [comment]
What exactly is wrong with oddy though, it heals basic damage on the field (which is important for combat) but cant easily fix wounds since thats a major limitation of chems (cryo mega gutted :c ) meanwhile medbay is still needed for fixing those wounds and doing actual surgery.

It has no overlap with medical doctors and surgeons, some overlap with chemistry and botany if anything.

**Comment by moocowswag** [comment]
> If you seriously want to remove something for utterly trivializing med, mediborgs have a full chemical repository that can be upgraded 

Mediborgs are strong at round start but as soon as you talk about upgrades you need to talk about progression that anyone can have. Whenever I play medical borg I try to give medical staff surgery toolset and medihud implants and i put breathing tube implants in crew so they dont take oxyloss from being in crit. 

Not to mention the new MENDING TOUCH gene which allows medical doctors to sap wounds off of people mid combat and then go back to medbay and treat themselves or get help from another medical doctor, this is absurdly fucking powerful when you have medical doctors practically ahealing security mid combat and then going back to medbay to treat eachother.

**Comment by Loafin34** [comment]
> > whatever moocow said
i think the medical treatment skills got removed because they were boring and not tied to anything beyond surgical speed. It was basically just an extra pair of nitrile gloves that you get for stitching together a morgue body 5 times

**Comment by moocowswag** [comment]
> It was basically just an extra pair of nitrile gloves that you get for stitching together a morgue body 5 times

Returning it would be a breath of fresh air for medical staff compared to doing surgery for experisci and then waiting to maybe receive your reward

**Comment by necromanceranne** [comment]
Actually, medical doctors can become comparable to borgs via surgery arm toolkits. The tools have the same speeds. Though for convenience, less clicks overall and still very decent surgery speeds, advanced tools tend to be more usable.

**Comment by shellspeed1** [comment]
If you want my take on how to make the oddy actually useful, a good direction to go would be setting it up to deploy a surgery table and operating console on the go. From there, you could also rig it up to provide an IV drip of scanned in chemicals. It could also retain the sleepers for transporting crew and the syringe gun since it does have some fun as an antag although it is abusable. Make it a mobile medbay for treating people in a crisis or for when medical is blown to shit.

**Comment by TheSmallBlue** [comment]
Yeeeah, the current ody is undeniably problematic, but why a straight up removal? Why not a rework or rebalanced?
The idea of doctors having a mean through which be present in the frontlines of battle isn't a bad one at all, and I feel that was the original intent of the odysseus in the first place.

**Comment by SimplySmiley123** [comment]
> Yeeeah, the current ody is undeniably problematic, but why a straight up removal? Why not a rework or a rebalance? The idea of doctors having a mean through which be present in the frontlines of battle isn't a bad one at all, and I feel that was the original intent of the odysseus in the first place.

It isn't problematic though. It doesn't really cause any issues beyond occassional syringe gun gimmick traitor.
Honestly it's very underwhelming and at best a quasi stasis bed when in medical.

**Comment by TheSmallBlue** [comment]
>  Honestly it's very underwhelming and at best a quasi stasis bed when in medical.

Yeah. Those are problems. So it's problematic.

**Comment by SimplySmiley123** [comment]
> > Honestly it's very underwhelming and at best a quasi stasis bed when in medical.
> 
> Yeah. Those are problems. So it's problematic.

I don't count it as problematic as it doesn't cause any problems to anyone on the station.
It isn't even that good at what I said it's usable for.

But I guess differing definition of problematic.

**Comment by carlarctg** [comment]
dont remove the wreckage......

**Comment by CCC23** [comment]
Not my Bosnian artillery platform nooo.. :(

**Comment by Shoddd** [comment]
> Giving more civilian (for lack of a better term) purposes for mechs
cars

**Comment by nyozzl** [comment]
muh fuckin free chemical generator :<

**Comment by Autisem** [comment]
rather see them reworked then just removed, utility mechs are already shit. the clark is the only one I sometimes see made for its utility rather then combat. removing one of 3 non combat options seems like step in wrong direction

**Comment by Majorkite** [comment]
> I asked several medical players about it and they were either very indifferent to it, or disliked it for the medbeam gun taking away their job (and it's not like you can really reject it, you'd be an asshole for not taking a free buff like that).


> I think literally any argument that boils down to 'actually, trivializing medical is good actually so nobody has to deal with medical' is probably arguing better for deleting the point and click medical invalidation machine.

I'm going to get a little wordy here, but I'm sick and tired of hearing this idea bandied about and I'm going to put it down for good.

Medical gameplay, is not hard. It isn't. Its time consuming. Its tedious. Its frequently stress-headache inducing. But it is not difficult. The hardest thing you're doing is comparing a list of what is wrong with a person, and then preparing a mental checklist of what to do to make those things not wrong anymore. Anything that shortens the number of things on that checklist, is good. It is beneficial to both doctor and patient.

To break down why this is, we must look at the end goal of the MD player: to get the human shaped mess that was dragged by the scruff of the neck into their medbay walking back out of it as soon as possible. This is good for the doctor because finding a prompt, efficient method of treatment is rewarding, because it means the person that was killed and found is spending less time sitting on their hands if they actually want to get back into the round. 

Players appreciate efficient doctors because we understand that no one wants to be hanging around medbay waiting for someone to fix them, or waiting for that fixing to finish. Good doctors dont shove people assembly line style into cryo because one, you can do it just as fast if not faster outside of cryo, and two, there is empathy for losing control of your character for anywhere from three to five minutes while you're waiting for the tube. There's no opportunity for RP. The same is why no one puts people under for surgery unless asked, because no one wants to spend the game sleeping. 

And this is where we get to our medibeams, our mending touches, our funny snake sticks. Those checklists we talked about before? These non round start upgrades help make those lists considerably shorter. Lets have a look.

Little Jimmy Nanotrasen walks in. He's been fighting in the bar again, He's got a dislocated arm, a bunch of really nasty cuts on his head and chest, and he's got a shitload of brute and burn damage. His liver is also starting to die from the amount of bacchus he drank. Our list for Little Jimmy looks like this.

Scan him.
Scan reagents to see if he penned.
Stop the bleeding.
Give him oxyloss meds if he's lost too much and starting to suffocate.
Get him antihol for his booze issues before his liver dies
Get him antitox so he doesnt go into crit
Get blood if hes lost too much blood because those oxyloss meds wont last forever
Meds for burns
Relocate his arm
Meds for brute

If we have our oddy, the cheklist looks like this:
Put the beam on him, preferably with someone inside the mech if someone else comes in thats more hurt than jimmy.
Get the bleeding
Get the antihol to make sure the bad stuff is purged before his liver dies
Get him blood if he needs it
Relocate his arm


Agency is what this game has always been about. In our first scenario, Jimmy is going to be standing around a lot while I work on his body as a project. Its engaging for me yes, but since I've been on the other side of this interaction, any pleasure I'd get from that gets sucked away if it takes too long. Any upgrade that lets you get your patients PLAYING THE GAME faster is what makes you feel best as a doctor. Not using people to augment your own gameplay. 

So this idea that medical needs to be made more and more complex and that tools like the oddy are somehow upsetting medical players due to 'taking our job away'? Drop it. 

If its an issue with the oddy itself causing code problems and no one wants to take up the torch for it, *say that*. If you don't like how the attachments work, say that, and then *improve* it.  

In closing, this ain't it.

**Comment by necromanceranne** [comment]
I'm not quoting it since it's a whole lot of text, but if there exists alternatives at all to the mechbeam (I'm surprised medibot hordes haven't been suggested more, they come from robotics roundstart and can target several damage types depending on type), does it really _need_ to be the Odysseus? It's a whole fucking mech, is that really necessary? 

To give it any value outside of the beam itself, you would have to actually give reasons for wanting to use anything _but_ the beam. You can only use two pieces of equipment, after all. It's clearly such a catchall that having two beams on someone probably does more for fixing someone than any alternative equipment you could suggest for the mech. Code jank aside, if the sleeper and syringe gun were actually half decent (they sorta are), why not just still use two mechbeams?

That's the fucking problem. The mechbeam is so good it not only trivializes healing generally, it even invalidates options for what could be added to the mech itself. For the mech to not be hurting its own possible design, it would have to go regardless. You either reconcile with the fact that the mech only exists for the beam, or that for the mech to matter, the beam must not exist at all and its healing options spread out in different ways.

**Comment by SimplySmiley123** [comment]
> 
> Players appreciate efficient doctors because we understand that no one wants to be hanging around medbay waiting for someone to fix them, or waiting for that fixing to finish. Good doctors dont shove people assembly line style into cryo because one, you can do it just as fast if not faster outside of cryo, and two, there is empathy for losing control of your character for anywhere from three to five minutes while you're waiting for the tube. There's no opportunity for RP. The same is why no one puts people under for surgery unless asked, because no one wants to spend the game sleeping.

> 
> Agency is what this game has always been about. In our first scenario, Jimmy is going to be standing around a lot while I work on his body as a project. Its engaging for me yes, but since I've been on the other side of this interaction, any pleasure I'd get from that gets sucked away if it takes too long. Any upgrade that lets you get your patients PLAYING THE GAME faster is what makes you feel best as a doctor. Not using people to augment your own gameplay.


Gonna be honest 3 to 5 minutes seems generous, been in rounds that weren't even chaotic messes where I've sat and seen people sat in medbay for upwards of half an hour, or the whole round to the point of some doctors dragging the corpse all the way to the escape shuttle and trying to speedrun fixing someone up in there.
Sometimes incompetence of medical doctors, sometimes sheer bad luck, sometimes the amount of bodies piling on or just someone else taking all the attention from everyone else who needs some fixing done.
Hell been a doctor several times in situations like this as well.
Ody is a welcome sight to me, even though I wish it was something more then a "this surgery table becomes a stasis bed" machine with just it's beams and had more of a presence outside of the medbay.

**Comment by SimplySmiley123** [comment]
> That's the fucking problem. The mechbeam is so good it not only trivializes healing generally, it even invalidates options for what could be added to the mech itself. For the mech to not be hurting its own possible design, the beam would have to go regardless. You either reconcile with the fact that the mech only exists for the beam, or that for the mech to matter, the beam must not exist at all and its healing options spread out in different ways. Would you still use that mech if that healing potential was spread out?

If the other options the mech gets were changed to be worth a while and not trivialised by someone with a roller bed or even more trivialised by a medborg existing.
Even more if some qol was done to the UI for those other options to not be a tedious mess to try and figure out.
Yes.

**Comment by san7890** [comment]
> What exactly is wrong with oddy though, it heals basic damage on the field (which is important for combat) but cant easily fix wounds since thats a major limitation of chems and heal beams (cryo mega gutted :c ) meanwhile medbay is still needed for fixing those wounds and doing actual surgery.
> 
> It has no overlap with medical doctors and surgeons, some overlap with chemistry and botany if anything.
> 
> And it mainly shines during large engagements like when the crew are fighting blob or sieging a cult base which is in line with every other big stompy combat mech it literally functions perfectly in situations where other combat mechs would want to be in, not alone, with support from other crew.
> 
> Anything that just heals brute / burn / toxin / oxyloss does not step on medbay's toes or invalidate medbay.

i agree with this assessment

**Comment by timothymtorres** [comment]
> That's the fucking problem. The mechbeam is so good it not only trivializes healing generally, it even invalidates options for what could be added to the mech itself. For the mech to not be hurting its own possible design, the beam would have to go regardless. You either reconcile with the fact that the mech only exists for the beam, or that for the mech to matter, the beam must not exist at all and its healing options spread out in different ways. Would you still use that mech if that healing potential was spread out?

I've always seen the healing rod used more frequently than the mech to heal patients. I will say that I agree with you that the mech code is suuuuuper outdated and poorly maintained. (most mech code is like that thou)

**Comment by Majorkite** [comment]
> I'm not quoting it since it's a whole lot of text, but if there exists alternatives at all to the mechbeam (I'm surprised medibot hordes haven't been suggested more, they come from robotics roundstart and can target several damage types depending on type), does it really _need_ to be the Odysseus? It's a whole fucking mech, is that really necessary?
> 
> To give it any value outside of the beam itself, you would have to actually give reasons for wanting to use anything _but_ the beam. You can only use two pieces of equipment, after all. It's clearly such a catchall that having two beams on someone probably does more for fixing someone than any alternative equipment you could suggest for the mech. Code jank aside, if the sleeper and syringe gun were actually half decent (they sorta are if you're being REAL generous about it), why not just still use two mechbeams?
> 
> That's the fucking problem. The mechbeam is so good it not only trivializes healing generally, it even invalidates options for what could be added to the mech itself. For the mech to not be hurting its own possible design, the beam would have to go regardless. You either reconcile with the fact that the mech only exists for the beam, or that for the mech to matter, the beam must not exist at all and its healing options spread out in different ways. Would you still use that mech if that healing potential was spread out?

Alright so its option two, you don't like how the beam works. So replace it with something. Otherwise this is just 'we need to get rid of this because I think its too good'.

The value outside of the beam is the ability to heal people in dangerous situations without being as vulnerable to attack. Cant easily get knocked down or stunned or easily dragged off, and you can use the thing to body block while others are fighting and you can heal or drag away the wounded. Its still a MECH with a closeable cabin and lights and the ability to move in space with the right upgrades. 

Additionally, the beam is not that good. It heals at about the same rate as two middling patches of chems. The only advantage is that you don't have to scan them for allergies before hand. Otherwise I'm keeping LOS on a person that's hurt instead of just slapping patches on that I can throw together in three minutes at the start of the round and forgetting about them while the chems work. Beam trades effectiveness for convenience. 

I do like the idea of giving it the ability to hoover up people in disaster areas like the paddy. I do  like the idea of making it like be able to deploy and have some paddles and a table on it, maybe even an IV hang.

**Comment by LemonInTheDark** [comment]
> i agree with this assessment

do you have plans to act on that? my gut is this pr is a good idea and none of the posts have really changed my mind.

**Comment by ShizCalev** [comment]
Screenshot_20241109_114111_Firefox

**Comment by Fikou** [comment]
> Screenshot_20241109_114111_Firefox

You've guaranteed the status quo will go on, for a while longer at least... War... will continue as an institution. As an industry. Men will fight for reasons they don't understand, causes they don't believe in...

**Pull request closed without merging**
