### PR TITLE
No More Calling get_equipped_items() in mob/living/Crossed(), Makes Slippery Component Work Without it

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
turns out every time a mob/living is crossed it checks the entire inventory of src for use in the slippery component. this is poop so i redid slippery component to not be built on poop and then got rid of the poop. idk if this counts as a performance thing but its one of the procs making tramstation more expensive and it doesnt need to exist anyways
edit: squeaky component is fixed too, COMSIG_ITEM_WEARERCROSSED is unused now so i deleted it

## Why It's Good For The Game
maaybe help tramstation and cuts down on unneeded cost

## Changelog
:cl:
code: slight performance improvement to clown pdas
/:cl:

### CODE REVIEW

**Comment by AnturK** [comment]
The signal was also used in squeak component.  You'll need to change that one too.
Also please test if it registration will be removed properly on item deletion.

**Comment by c420-o** [comment]
Doesn't gunboots use this too? And hulk exceptions for northstar gloves?

**Comment by Kylerace** [comment]
> 
> 
> Doesn't gunboots use this too? And hulk exceptions for northstar gloves?

not as far as i can tell

**Comment by Kylerace** [comment]
> 
> 
> The signal was also used in squeak component. You'll need to change that one too.
> Also please test if it registration will be removed properly on item deletion.

both squeaky and slippery stop working successfully after deleting the item held by a mob, squeaky is redone now too

**Pull request merged**
