### PR TITLE
Nerfs revenant

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Revenants are slower while revealed.
rscdel: Revenants can no longer cast inside dense objects.
tweak: Lying down will cure Blight much, much faster.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
:-1: I was hoping this would conflict with robustin's pr

**Comment by Man-Shroom-** [comment]
double griffghost nerf wew

**Comment by Robustin** [comment]
I dont see why them being slower is a nerf. They pop out, EMP your guns, then laugh as you futilely chase it for a few seconds and its gone. 

I approve of any Rev change but even if you removed every goddamn Revenant spell I wouldn't like them on the sheer basis of them being an invisible unkillable scout for every antag they work with. 

Sec borgs are gone and I'm fine with that, but the whole "revenant all day every day 24/7/365" meme makes security absolutely hell to play. EMP permanently damages energy weapons, which affects security approximately infinitely more than stechking/ebow/revolver traitors. 

If you don't intend this PR to conflict with mine, that's fine, but god damn I have never seen a round where I thought "gee this revenant sure enhanced this round". Griff ghost plz go.

**Comment by ChangelingRain** [comment]
>being slower isn't a nerf

I'm not sure where you got that, but being slower just makes them weaker, there's no way it'd be anything else.

**Comment by Robustin** [comment]
Speed = 1 is still crew speed with incorporeal movement, aka "I can move from one end of the station the other in under 10 seconds instead of 5 seconds". I want something more meaningful to give some chemo to these revenant memes.

**Comment by ChangelingRain** [comment]
If it's incorporeal it's full speed, the speed only applies while it's revealed. And it's below crew speed, speed = 0 is crew speed.

**Comment by PKPenguin321** [comment]
speed dont even matter when i can attack you from inside a wall

**Comment by Robustin** [comment]
Again, speed is virtually irrelevant here. Most revenant abilities lock you in place which means movement = NONE until you turn into an incorporeal turbohitler again. 

The whole issue is after 2 EMP's (one to reduce cell capacity, a second to drain whatever's left) security can do fuck-all about the revenant without hauling a lethal-packed shotgun everywhere. If the revenant teams up with antags (and 90% of the time it does) then you're often dealing with a fuckhead revenant shitting on you while someone else is trying to murder you with an ebow. 

Someone please explain to me why revenant should EVER be a common event? PLEASE ENLIGHTEN ME.

**Comment by ChangelingRain** [comment]
Speed is not irrelevant here, because the lock-in-place is less duration than the reveal. Both matter, and totally ignoring it because it 'clearly has no effect' is silly.
It's even more relevant with this change to prevent in-window casting, ie; the revenant has to cast someplace that's not in a dense window you can't attack it in.

**Comment by Kole6738** [comment]
Grief Ghost,
Go away,
You add nothing
To gameplay.
Glowing Snot,
Bug Me Not,
Revenant's a bad may-may

**Comment by PKPenguin321** [comment]
>rscdel: Revenants can no longer cast inside dense objects.

fugg
super :+1:

**Comment by AdamElTablawy** [comment]
slowdown is fairly useless for a revenant.

it's better to just increase the duration the revenant is stuck in place because it can still easily leave the moment it's revealed and juke around lasers unless it's speed is alien queen/golem tier.

also it's worth mentioning that the revenant's EMP is not a true EMP, otherwise it would drain SMES, fry APCs, and destroy dominators-if I recall it doesn't damage gun cells permanently either

**Comment by Chiefwaffles** [comment]
Has EMP been merged yet? Can the ghost still instantly ggnore silicones with the EMP?

**Comment by Robustin** [comment]
Last time I played revenant Shaps told me I had damage all his gun's power cells. 

And again, if locking the revenant in place for 3 seconds has proven insufficient to having the crew kill it, I don't see how speed = 1 for the 1-2 seconds you're moving but not invisible are going to make any kind of difference. When you can reveal yourself at will its super easy to cast from annoying places that the victims will never reach you from before you go invisible.

**Comment by Incomptinence** [comment]
Eh all for making them get caught easier but players deserve the blight so nah,

**Comment by Cheridan** [comment]
why not have both

**Pull request merged**
