### PR TITLE
removes cat ears from the autodrobe

### PR DESCRIPTION
**Pull request by ghost**
:cl: optional name here
del: Due to artificial intelligence concerns, cat ears have been removed form the autodrobe
/:cl:

[why]: 
it's literally code-approved ban baiting for the AI
it does nothing, it changes nothing, and all it does it make the AI/borg a living hell when a human is wearing this shit and they kill them thinking they're a catgirl
(ADMIN PM FROM: CATGIRL ENTHUSIAST) "WHY DID YOU KILL THAT HUMAN AS A BORG"
admin reply: it was a catperson
ADMIN PM: NO IT WAS A HUMAN REEE *bans u*

horrible, HORRIBLE fucking metaphor/analogy what the fuck ever but you get my point, right?

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
>code-approved ban baiting for the AI

it was added before catpeople were a thing

**Comment by coiax** [comment]
If only there were some quantifiable difference between cat people and humans.

It's a pity that there isn't in code, that seems like an oversight, honk honk honk.

**Comment by deathride58** [comment]
You can literally just shift-click someone to see if they're an actual cat or not

It's not that hard

**Comment by awesine** [comment]
you can't examine as an AI

**Comment by Tlaltecuhtli** [comment]
yes and the autodrobe needs to be updated to match the change

**Comment by awesine** [comment]
@The-clown-known-as-Pepe and now that catpeople are in it's literally just ban baiting so i'm removing it

**Comment by The-clown-known-as-Pepe** [comment]
i ded tag?

**Comment by Tlaltecuhtli** [comment]
or we could remove cat people and keep the cat ears in the autorobe

**Comment by deathride58** [comment]
Even if you can't examine someone as AI, you can tell if someone's a cat or not if they're capable of wearing a hat without getting rid of their tail and ears.

**Comment by awesine** [comment]
"i ded"

no, more like

"i killed someone who obviously looked like a non-human but now i got banned for it" even though this didn't happen it's stilla  fuckin pain for AI/borgs

**Comment by awesine** [comment]
@deathride58 what if they're not wearing a hat
what if the AI/borg doesn't know that code thing

wwyd

**Comment by awesine** [comment]
@Tlaltecuhtli i would but it would get insta-denied

**Comment by The-clown-known-as-Pepe** [comment]
> "i ded"

no, more like

"i killed someone who obviously looked like a non-human but now i got banned for it" even though this didn't happen it's stilla fuckin pain for AI/borgs

sounds like i ded to me

**Comment by Tlaltecuhtli** [comment]
lets make a vendor in the shuttle with 10 cat ears and remove catpeople

**Comment by The-clown-known-as-Pepe** [comment]
@Tlaltecuhtli can you calm down and accept the fact that more people want them in than the number of people that don't want them?

**Comment by kevinz000** [comment]
I'm on vacation but you should fuck off and cry harder anyways like you always do when things don't go your way.

**Comment by awesine** [comment]
@The-clown-known-as-Pepe 

can you calm down and accept the fact that more people want them doesn't mean that they are a horrible addition to the codebase?


@kevinz000 shut up nerd this is an actual change  that doesn't only apply to me

**Comment by awesine** [comment]
More people in the USA want to nuke north korea now and get it over with, but is that the best choice? No. same logic applies here.

**Comment by The-clown-known-as-Pepe** [comment]
@awesine you only think that because u ded

i don't think this codebase needs more codegrudging

**Comment by Tlaltecuhtli** [comment]
@The-clown-known-as-Pepe i m trying to find a solution to this specific code problem not sure what caused you to think i want cat people removed

**Comment by The-clown-known-as-Pepe** [comment]
@Tlaltecuhtli "lets make a vendor in the shuttle with 10 cat ears and remove catpeople"

**Comment by awesine** [comment]
@The-clown-known-as-Pepe 
can you SERIOUSLY not see the problem of AI/borg mistaking a human as a catperson when they wear this shit?

**Comment by The-clown-known-as-Pepe** [comment]
@awesine yes that is a problem

**Comment by Tlaltecuhtli** [comment]
removing cat people as a race so borgs dont have to check which hat someone is wearing while cat people enthusiasts have cosmethics available round start 

it also fixes borgs accidentally responding to orders of not humans from radio, you can notice its a lizard or a plasmaman (the name) but catpeople language is the same as human one

**Comment by awesine** [comment]
@The-clown-known-as-Pepe this is fixing that problem

**Comment by The-clown-known-as-Pepe** [comment]
@Tlaltecuhtli this would mean exactly the opposite of what playerbase wants

the real way to fix this issue with leaving everyone happy is introducing a race hud

**Comment by deathride58** [comment]
Another less controversial way to fix the problem would be to make the sprite for fake cat ears different from actual cat ears. Perhaps make fake cat ears slightly discolored compared to real cat ears?

**Comment by epochayur** [comment]
untitled

**Comment by The-clown-known-as-Pepe** [comment]
@deathride58 considering cat ears can be any color thats not a obvious enough change

**Comment by awesine** [comment]
@deathride58 


still not noticable from a glance

**Comment by Tlaltecuhtli** [comment]
maybe a text with "VALID" as example on top of real cat people

**Comment by kevinz000** [comment]
Itt: ooc bans aren't enough to make whiny drama Kings stop

**Comment by TribeOfBeavers** [comment]
This seems more like you should appeal the ban and not remove the item tbh. 

The ears have a use if you want to disguise yourself as a catperson for whatever reason. They probably shouldn't be removed.

**Comment by optimumtact** [comment]
\>even though this didn't happen

I appreciate you trying but please don't make any pr's touching cat related things, they're basically relegated to maintainer changes only at this point

**Comment by awesine** [comment]
kevinz000 has been added to your ignore list.

i'm literally NOT FUCKING STIRRING SHIT
FUCK YOU KEVINZ000


@optimumtact 
>ignoring literal code-approved ban baiting

**Comment by awesine** [comment]
https://i.imgur.com/rR4Z4Ab.png

**Comment by awesine** [comment]
@optimumtact 
this isn't even a cat person change, this is an accessory/clothing change

**Comment by optimumtact** [comment]
relax my dude, it's christmas, go do something with your time

**Comment by awesine** [comment]
@optimumtact 
christmas was 4 days ago

**Comment by PKPenguin321** [comment]
This actually had surprisingly valid reasoning and probably shouldn't have been shut down so quickly, I kind of hate the term kneejerk but reading through this there's obviously no real argument against the PR, just people being mad at OP

**Comment by optimumtact** [comment]
no

**Comment by PKPenguin321** [comment]
🤔 still no arguments...

**Comment by RemieRichards** [comment]
Member when /tg/ wasn't all drama? Oooh I member!

**Comment by optimumtact** [comment]
hey, dont' be a  to the drama

**Comment by RemieRichards** [comment]
:drum:

**Comment by Iamgoofball** [comment]
we need another coup

**Comment by awesine** [comment]
@optimumtact 
is there any actual rule saying cat-related things are maintainer only?

**Comment by kevinz000** [comment]
Itt awesine mad

**Comment by kevinz000** [comment]
screenshot_20171229-235729

**Comment by BeeSting12** [comment]
LOL awesine is a chumbis kek

**Comment by FantasticFwoosh** [comment]
@deathride58 the same thing arises when catpeople are unidentifiable with their tails removed (and ears present), from within something totally concealing like a EVA helmet & a human voice a physical borg is required to investigate as the AI is completely shut out of context & detail now that @coiax cares to remember this arguement i fielded ages ago in my forum threads.

Then you get shenigans of the borg being turned away by this human voice etc etc, or wasting your valuable silicon time on a catperson when actual humans are in danger, its not helpful.

**Comment by Screemonster** [comment]
how the fuck is this any different to the AI doorcrushing someone with a foam armblade because they saw them there with a foam armblade

cat ears aren't even an antag-tell so there's even less excuse

**Comment by FantasticFwoosh** [comment]
@Screemonster it isn't different at all in some respects.

They are a non-human tell, like (as you said before) someone with a armblade that the AI believes to be genuine would also be a non-human tell (changelings are non-human when they exhibit abilities) but cat-ears have no feasable evidence outside of asking a borg to check it out or cross-referencing station records.

- You can also ambigiously throw AI's off the scent by installing/removing real cat ears & tails onto them contrary to station records.

**Comment by awesine** [comment]
@FantasticFwoosh 
i was never banned for this, i'm just doing this so people *don't* get banned

**Comment by duncathan** [comment]
policy issue, not a code issue.
as for the question of "is there any actual rule" if you're asking that question you obviously don't understand the nature of our repo. maintainer decisions are the only rules we have.

**Comment by kyrahabattoir** [comment]
@awesine What happened to the first rule: "Don't be a jerk" ?

**Comment by The-clown-known-as-Pepe** [comment]
nice necro

**Pull request closed without merging**
