### PR TITLE
Revert "Make more use of <tool>_act"

### LINKED ISSUE #64432: Hacking doors does not work
Reporting client version: 514.1575

## Round ID:
[177296](https://scrubby.melonmesa.com/round/177296)

## Reproduction:

Attempting to hack open doors on Basil does not work. The pop up window with wire colors, pulse cut etc does not show up. Other windows still appear normally such as consoles and pdas.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#64375

test merge pr because only one server has this bug because only one has updated so far.

fixes #64432

### CODE REVIEW

**Comment by Iamgoofball** [comment]
can we keep it like this? greytiders can cope

**Comment by SuperNovaa41** [comment]
> can we keep it like this? greytiders can cope

so true dude

**Comment by magatsuchi** [comment]
#64435 will fix this issue while keeping those fancy schmancy <tool>_acts that look pretty

**Comment by Mothblocks** [comment]
#64435 has been merged

**Pull request closed without merging**
