### PR TITLE
Revert "ninjas can now hijack the shuttle"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#57594

ninjas dont need a buff, they're absurdly overpowered, have insane stuns, and can one hit people, along with sending people to centcom bar purgatory with no counter

it sucks, it doesnt need an excuse to hijack the shuttle

### CODE REVIEW

**Comment by Mothblocks** [comment]
hijacking isnt a buff

**Comment by Iamgoofball** [comment]
Discord_GJL52M29Wc

**Comment by Mothblocks** [comment]
maints had 24h to say no on the original pr 🙂

**Comment by YakumoChen** [comment]
Goof hasn't even looked at Ninja code in years or he would know they remade the entire antag

**Comment by Mothblocks** [comment]
goof apparently did not know that ninja was reworked at all

**Pull request closed without merging**
