### PR TITLE
Dual magazine shotgun

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Has two tubes, which you can toggle between by using the gun inhand. For example, you could fill one tube with riot ammo, and another with buckshot. Basically the UTS 15

Maybe something for science? It's a shame they can print all the zany shells out but don't have anything to put them in.

Sprites from Paprika

### CODE REVIEW

**Comment by Bawhoppen** [comment]
no more science pls
don't make it ops either

**Comment by Iamgoofball** [comment]
hi i'm bawhoppen stop adding things to the game

**Comment by TheNightingale** [comment]
Give it to Security (in the Armory), they need some love.

**Comment by Lumipharon** [comment]
Kor, isn't this essentially this same thing as alt fire modes (or more specifically, like the m-90?).

I ask because usually using the gun inhand usually removes the mag, and firemode is typically switched via GUI button.

**Comment by kevinz000** [comment]
Honestly science needs ballistic weapons . All those OP miniguns are nice but at the end of the day it gets hard countered by a guy with dual eswords/anything with laser resist/deflect.

**Comment by Iamgoofball** [comment]
@kevinz000 
sometimes you gamble and lose

**Comment by GunHog** [comment]
@Lumipharon it is several reasons. 
1. Science does not have shotguns, unless the HoS/Cargo decide it is Christmas and give you all three shotties from the Combat Shotguns crate.
2. The improvised shotgun is absolute garbage, along with being annoying to make. Also, it has been moved to the Autolathe - it is more of a weapon for assistants.
3. As you said, TABLECRAFTING. Very annoying.
4. There are stun shells, but leading back to point one - I normally have nothing to use with the shells. On RARE occasions, the bartender may stop by to load up his bar gun.

**Comment by Core0verload** [comment]
Improvised Shotgun is really powerful if you load it with the right shells. But making enough of the "right" shells is boring.

**Comment by stapler2025** [comment]
you mean clips right?

**Comment by KorPhaeron** [comment]
Should I just make the lathe print out the shells? 

Gathering 4+ objects and dumping them on a table to make a single shot seems absurd.

**Comment by Core0verload** [comment]
Leave the tablecrafting option, but add finished shots to lathe too.

**Comment by GunHog** [comment]
Those shells are quite powerful, you do not need to make them finished products. If you add a shotgun to R&D, I recommend you make a tablecrafting recipe for stunshells, and remove those from the protolathe, else lazy players will choose them every time. The players willing to do a bit of work getting the shells only need access to a shotgun.

**Comment by Lumipharon** [comment]
Make them printable Kor.
Forcing you to print 20 of 5 different items (including the empty shells!) then move them to a table (which before bluespace trashbags was a whole level of autism in of itself), before sitting there for 5 minutes watching a loading bar.
If anyone touches you while you're doing it, tough shit.
If you have too many items on the table, tough shit.
If you like playing the game rather then doing needlessly tedious tasks, tough shit.

Having the tablecrafting recipes is fine, but only as an optional thing (and really it should be doable by emptying out a normal shell and stuffing it full of bits and pieces you've looted from an RCD/medbays sleepers).

**Comment by AdamElTablawy** [comment]
science's shotgun shells are only balanced by requiring tablecrafting, which is tedious. printable shotgun shells is a REALLY BAD IDEA because most of science's shotgun shells (Pulse slugs and meteorshot and oH MY) are really really really lethal as fuck and not that difficult to mass produce.

You make printable shotgun shells and impro shotguns are going to turn into the new SMG because while it only has the one shot you only need one blast of meteorshot to assfuck everyone in sight, and god help you if science gets combat shotguns (instant cargo means they usually do) or if you give this shotgun to science.

no.

printable science-tier shotgun shells are a really, really, really, really, really, REALLY bad idea I cannot stress enough how badly it will ruin everything if you make printable meteorshot/EMP/pulse/whatever the fUCK the rest of them are shells. If they're printable you're going to have the warden run to science every time it's done to load up all his riot shotguns with pulse lasers and meteorshot, the bartender's going to devolve into an AI-stomping EMP-firing menace and science's impro shotguns are actually alarmingly easy to mass produce if you deconstruct some tables in arrivals/go annoy botany.

**Comment by Lumipharon** [comment]
>1 shell per reload
>meteor shot can only hit one person
>does 20 damage and a short stun

At BEST you could chain stun ONE guy to death, please explain how you're going to 'ass fuck everyone in sight' with that?

Also sec doesn't get GUNS from science often enough, do you really think the warden is going to be bothered to manually empty and load 3 shotguns every round?

**Comment by WJohn** [comment]
By combining it with buckshot. You stun and slightly damage someone with meteor, then walk up to them and finish them with 90 brute in one shot.

Though this. Can already be done with combat shotguns, really.

**Comment by AdamElTablawy** [comment]
Yes, but combat shotguns aren't mass reproducable and you can't shove a shitton of them in a bag of holding to be a walking armory.

**Comment by Lumipharon** [comment]
@WJohn That lets you kill one person. You can do that with literally any stun weapon, most of them more efficiently.

Being able to kill ONE PERSON by hitting a guy, having to reload, move up to them and hit them again, is far from OP.

Being able to tase someone then whip out a laser cannon/sabr is far quicker and more powerful.

**Comment by KorPhaeron** [comment]
Okay I have sprites now

Should it be a science gun, or replace the Wardens taser, or just be some admin only thing that I sneak into lavaland somehow later?

**Comment by GunHog** [comment]
My vote is obviously for Science, as Science lacks a shotgun where Sec starts with one. It does not seem strong enough to warrant being locked away in Lavaland. If you choose not to go with Science, I would like to try my hand at a shotgun that is halfway inbetween riot and combat, and can be modded to accept flashlights and suppressors. Upgrades are cool.

**Comment by jughu** [comment]
Just make the daul magazines a combat shotgun thing

**Comment by jughu** [comment]
Just make the daul magazines a combat shotgun thing

**Comment by KorPhaeron** [comment]
I guess I'll make it spawn somewhere some other time. It's done but I don't want to do the work for putting it somewhere in game at this time.

**Pull request merged**
