### PR TITLE
Makes angel potion bottle into a real bottle

### PR DESCRIPTION
**Pull request by Core0verload**
"Strange elixir" is no longer inconsistent in it's application - it works just like the rest of food and drinkables. You can also re-load empty elixir flask with something else and trick some fool into drinking grinded plasma.

The elixir found in lavaland crates has 5u of reagent. You need to apply (drink, inject, splash) all 5 units at once for it to work, any attempt to split or dilute the dose would fail.

I don't think it's enough of a feature to require a merge token. This is more like a refactor or inconsistency fix.

### CODE REVIEW

**Comment by Core0verload** [comment]
In next PR I'll make hivelord/legion core stabilizer reagent based too. This would make chemist more helpful for miners, because stabilizer is easy to produce in chem and doesn't require any vending points.

**Comment by KorPhaeron** [comment]
angel bees

**Comment by Core0verload** [comment]
Would be fun, but 1u per injection from a bee is not enough.

**Comment by Lexorion** [comment]
An odysseus mech with a syringe gun could analyze and replicate it

**Comment by Core0verload** [comment]
Should I stop players who built an Odysseus mech from replicating this reagent? Or does it fall in "emergent gameplay" and "FUN" categories?

**Comment by KorPhaeron** [comment]
seems more silly than a balance concern, no reason to blacklist if you dont want to

**Comment by Shadowlight213** [comment]
Angels really aren't that powerful anyways tbh.

**Pull request merged**
