### PR TITLE
Fixes For Bitrunner Domains & Safehouses To Fit The New Perspective

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Acts on another of my claims in #85583 .
Back on the main repo; time to get serious. This fixes the bitrunner domains and safehouses (all vetted in-game) to be 100% there for wallening. Buttons moved and fixed; wallmounts fixed (there were some types in there we delibrately linted against using; how did those slip by?? Are we just not checking the folders for these with linters?); the whole nine yards.

Maps not touched by this PR were already 100% above board.

## Why It's Good For The Game
Bitrunner maps were still mostly playable but this irons out the rough edges (mapping-side; there's a few sprite issues in the "i played every map help me" section) to make them proper presentable again. 

I had to play through each bitrunner map in private just to test this PR. Send help.

<details><summary>Screenshots Of Each Domain / Safehouse As Proof Of This Insanity</summary>
<p>

Peaceful Domains:

<details><summary>Beach Bar</summary>
<p>

image
image

</p>
</details> 

<details><summary>Breeze Bay</summary>
<p>

image
image

</p>
</details> 

<details><summary>Gondola Asteroid</summary>
<p>

image
image

</p>
</details> 

<details><summary>Vaporwave</summary>
<p>

image
image

</p>
</details> 

Easy Domains:

<details><summary>Clown Planet</summary>
<p>

image
image

</p>
</details> 

<details><summary>Disposal Pipe Factory</summary>
<p>

image
image

</p>
</details> 

<details><summary>Snakes And Ladders</summary>
<p>

image
image

</p>
</details> 

<details><summary>Xeno</summary>
<p>

image
image

</p>
</details> 

Medium:

<details><summary>Crate Chaos (!!!)</summary>
<p>

image

</p>
</details> 

<details><summary>Abductor Ship</summary>
<p>

image
image

</p>
</details> 

(I skipped the megafauna arenas because they're vetted already)

<details><summary>5/9ths Already</summary>
<p>

image
image

</p>
</details> 

<details><summary>Corsair Cove</summary>
<p>

image
image

</p>
</details> 

(Infected Domain had the same issue Crate Chaos had.)

<details><summary>Syndicate Assault</summary>
<p>

image
image

</p>
</details> 

Hard:

<details><summary>Island Brawl</summary>
<p>

image

</p>
</details> 

You thought I was fuckin' joking. Smh

</p>
</details> 

## Changelog

:cl:
fix: Every bitrunner domain's been patched up for the new perspective shift.
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
Gotta sya your screenshots made this PR very much worth to go through, 10/10 just based on the PR body alone

**Review by jlsnow301 — APPROVED** [review]
Looks great

**Comment by Ghommie** [comment]
immagine

Has it something to do with this?

**Comment by jlsnow301** [comment]
Were the binary walls ever fit to the 3/4th perspective?

**Comment by unit0016** [comment]
Binary walls weren't fit to 3:4ths; yeah. To be clear, that runtime *is* my fault for just trying to pave over it by setting it back to it's old icon.
I'm not a spriter (nor do I know how the cutter works); but I'll give a shot at fixing it properly.

**Comment by unit0016** [comment]
I should also state: me having added that will make the psyker domains unplayable until they're patched. Issue's already been reported in #85839

**Pull request merged**
