### PR TITLE
[READY]Peacekeeper cyborg projectile dampening fields, attempt three

### PR DESCRIPTION
**Pull request by silicons**
Lets try this again...
@RemieRichards I "refactored" it to proximity checkers :^)
:cl:
rscadd: Peacekeeper cyborgs now have projectile dampening fields.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
nerfed some values.

**Comment by Tacolizard** [comment]
make a changelerg

**Comment by GunHog** [comment]
Did you test the most recent version of this?

**Comment by kevinz000** [comment]
Yes[tm]
Why is it not working?

**Pull request merged**
