### PR TITLE
Water is good for you! It heals toxin damage VERY slowly.

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
Water now very slowly heals toxin damage it still mobilizes at the same rate. 5u of Syriniver (round start chem) with a fully functional liver heals about 21-25 toxin damage.  5 units of water would only give you 2.5 tox healing over a longer period of time. 
## Why It's Good For The Game
This may be controversial for some but I just hate walking into a room with a small amount of plasma without noticing and instantly start taking toxin damage before I can get my internals on. Then I have to look at that green heartbeat monitor instead of my nice blue happy one despite only taking a point or two of damage. To fix this I have to go all the way to medbay to get an injection or take a nap. You can easily top off brute and burn by just going and eating something. I feel it's reasonable to be able to get rid of a small amount of toxin damage without any hassle.

## Changelog
:cl:
add: Stay hydrated! Water heals a little toxin damage overtime.
/:cl:

### CODE REVIEW

**Comment by MMMiracles** [comment]
image

**Comment by SkeletalElite** [comment]
I'm not sure that it's true here, but on other servers tea heals small amounts of toxin damage. That would be better since its not as freely wide spread as water but you can still get it for fairly cheap from a vending machine or have the bartender get you some.

**Comment by necromanceranne** [comment]
Tea does indeed slowly heal toxins.

What this also means is that water kills slimes which is very, very fucking silly.

**Comment by Shadowflame909** [comment]
> 
> 
> Tea does indeed slowly heal toxins.
> 
> What this also means is that water kills slimes which is very, very fucking silly.

Cold kills slimes

Fire extinguishers are cold blasts of water.

It makes sense chief

**Comment by cacogen** [comment]
i can't tell you specifically how to fix this (i'd revert back to the commit i originally branched from, keeping the changes and then discard any changes that weren't mine, then recommit only my changes before rebasing the branch onto master) but you need to fix your commits, you're editing an unrelated file

**Comment by PKPenguin321** [comment]
>What this also means is that water kills slimes which is very, very fucking silly.

Does it not already? Our fire extinguishers have water in them

**Comment by itseasytosee** [comment]
It does not apply on touch only ingest. 
>i'd revert back to the commit i originally branched from, keeping the changes and then discard any changes that weren't mine, then recommit only my changes before rebasing the branch onto master

thanks.

**Comment by itseasytosee** [comment]
If you want to spend cash on tea or lime juice for a slightly quicker result its an option.

**Comment by HomocidlePancakes** [comment]
https://en.m.wikipedia.org/wiki/Water_intoxication

Add this or cuck.

**Comment by CPTANT** [comment]
Having no OD is a very bad idea. Water is everywhere, you can easily chuck 1000u.

**Comment by Tlaltecuhtli** [comment]
add water OD

**Comment by carlarctg** [comment]
this is dumb af just buy tea

**Comment by itseasytosee** [comment]
I may do something like this again but not today, not now.

**Pull request closed without merging**
