### PR TITLE
Remove meat from prison kitchens

### PR DESCRIPTION
**Pull request by dexmoh**
## About The Pull Request
This removes any meat products from the prison kitchens on all stations.

This change was proposed by @EOBGames on Discord after #55689 got closed.
vegeterian_propaganda_1
vegeterian_propaganda_2

## Changelog
:cl: Dex
del: Removed meat from prison kitchens. All prisoners are now on a strict vegetarian diet as part of their punishment.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
vegan prison

**Comment by interestingusernam3** [comment]
vegan prison

**Comment by Pugie** [comment]
vegan prison

**Comment by Fikou** [comment]
vegan prison

**Comment by ShibaInuLord** [comment]
vegan prison

**Comment by IndieanaJones** [comment]
vegan prison

**Comment by wesoda25** [comment]
I don't get what's wrong with having a slab of meat or two available in the kitchen at round-start.

**Comment by Pugie** [comment]
> I don't get what's wrong with having a slab of meat or two available in the kitchen at round-start.

**NO VEGAN DIET NO VEGAN POWERS**

**Comment by interestingusernam3** [comment]
go to vegan jail

**Comment by ATH1909** [comment]
but you can still get meat from monkeys from monkey cubes, so this doesn't actually solve anything

I just want to grill as a prisoner, for god's sake.

**Comment by ATH1909** [comment]
say, didn't floyd make a PR that let you use a campfire as a griddle? or am I completely misremembering things?

**Comment by Owai-Seek** [comment]
The bonfire can cook meat, but (at the moment) it cannot cook anything else. In theory you could make a bonfire in the prison and use that to make meat, but that seems like a dumb work around for something people should just, have access to.

Similarly, meat is (somewhat) useless in all maintenance kitchens now (to non-lizards) because you need to either make a griddle, or make a bonfire. This kind of ruins their purpose as an assistant teaching tool.

**Comment by jacklecroy** [comment]
> Similarly, meat is (somewhat) useless in all maintenance kitchens now (to non-lizards) because you need to either make a griddle, or make a bonfire. This kind of ruins their purpose as an assistant teaching tool.

Is there an even hour requirement for cook? Why does it have to be an assistant teaching tool?

**Pull request merged**
