### PR TITLE
Ports some CEV ammo box sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
imageadd: New sprites for .45, 9mm and 10mm ammo boxes, and also for the cap gun box. Thanks, CEV-Eris.
/:cl:

image
image
image
image

### CODE REVIEW

**Comment by Steelpoint** [comment]
Fancy stuff

**Comment by Borisvanmemes** [comment]
These don't really mesh well with most of the other sprites in the game imo.

**Comment by Militaires** [comment]
they're too fucking beautiful to fit in

**Comment by MrDoomBringer** [comment]
Why are they isometric tho im pretty sure literally none of our sprites are isometric

this is what happens when wjohn leaves

**Comment by nicbn** [comment]
Isometric is the same as 3/4 but rotated, and fits well to icons.
And we have isometric sprites already, like the monkey cube box and the die.

**Comment by lolman360** [comment]
eris has the best sprites
can we just port all eris spritese

**Review by ninjanomnom — CHANGES_REQUESTED** [review]

**Comment by Cyberboss** [comment]
I do take issue to the isometric sprites, they match with nothing in the game

**Comment by nicbn** [comment]
image
image
image

**Comment by MrDoomBringer** [comment]
@nicbn 3 niche items out of the many many many we have is really just about nothing. I think the slight exaggeration cyberboss made is warrented

also something bad existing doesnt validate additional bad existing yadda yadda

**Comment by nicbn** [comment]
Are you calling CEV Sprites bad lol
Also again, isometric isn't that different from 3/4 (it's literally 3/4 but rotated) and fits items well.

**Comment by MrDoomBringer** [comment]
@nicbn u chumbis im saying that those isometric sprites in our codebase are bad, and don't validate more isometric sprites coming in

>Also again, isometric isn't that different from 3/4 (it's literally 3/4 but rotated) and fits items well.

that is so completely out of left field
we are trying to have a consistent style my guy

**Comment by nicbn** [comment]
We could start using isometric on more item sprites so it'll be clear these things are pickupable - WJohn suggested this as a possibility when I prompted him on Discord.
Also the sprites are objectively better than the ones we have now - regardless of the art style -, as expected from eris sprites.

**Comment by ninjanomnom** [comment]
If wjohn is willing to reach beyond the grave to push for this change I'll merge this

**Comment by WJohn** [comment]
To give further context to that, I think that there's nothing inherently wrong with isometric sprites, but ya'll need to decide if you want to have all items be isometric (to be immediately recognizable as something you can pick up) or if you want them to be in 3/4th (to stay consistent with the perspective of the rest of the sprites).

I'm not active enough to hold any sort of sway on this, you guys gotta choose.

**Comment by MrDoomBringer** [comment]
context is for wussies but yes

**Pull request closed without merging**
