### PR TITLE
Removes offending line from CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by coiax**
Apparently my multiline strings (and only MY strings, other people
have been splitting strings with just longer line lengths, and no one
complained then) are on the par with NAZI CONTENT, that is HARD BANNED
in the CONTRIBUTING.md file.

I mean this is just petty and vindictive. Apparently my multilines
ARE EQUIVALENT TO NAZIS.

It's dumb, you should remove it, and I can't believe this is an issue.

### CODE REVIEW

**Comment by lzimann** [comment]
stop multilining then you evil person

**Comment by coiax** [comment]
Why?

**Comment by RemieRichards** [comment]
You're the one being prosecuted because you do it every time without fail.
everyone else does it intermittently or never.

**Comment by ChangelingRain** [comment]
CEASE MULTILINES

**Comment by coiax** [comment]
No.

**Pull request closed without merging**
