### PR TITLE
PubbyStation update #2

### PR DESCRIPTION
**Pull request by pubby**
Several fixes and improvements, including most of Tacolizard's changes from #21318. Read the commit message see more details.

Big change: There is now a space monastery floating next to the station. The dormitory pod can be used to get there.

:cl: Pubby
add: A space monastery and chaplain job have been added to PubbyStation.
/:cl:
:cl: El Tacolizard
add: Improved pubby's maint detailing
/:cl:

### CODE REVIEW

**Comment by TehZombehz** [comment]
What a great place to ~~hide the bodies of my victims~~ visit!

**Comment by ToadStar** [comment]
Maybe try adding some wooden airlocks and walls to the interior of the monastery. It might look even better imo.

**Comment by XDTM** [comment]
It's beautiful

**Comment by Cheridan** [comment]
i don't like the area made completely with glass walls. like, if you visualize it how does that even look? if it was rounded off like a biodome or something it'd work but its all jagged.

**Comment by Tacolizard** [comment]
A classic .45 handgun with a small magazine capacity. An engraving on the side reads: Tacolizard Forever

**Comment by Tacolizard** [comment]
wait did you not merge the clear pda maint loot?!! I've always wanted that pda to be obtainable

**Comment by phil235** [comment]
You should use the map merger tool so the diff isn't huge. https://tgstation13.org/wiki/Map_Merger

**Comment by pubby** [comment]
I did use the mapmerger but correct me if I'm mistaken.

**Comment by AnturK** [comment]
The map specific definitions should be moved to the map folder.

**Comment by Alek2ander** [comment]
Cult base?
Cult base.

**Comment by pubby** [comment]
@AnturK I get path errors when I try that because the map editor doesn't follow #includes.

I suppose it would work if I add the files to tgstation.dme, but that would cause the files to be compiled for every map and defeat the purpose of keeping map-specific code separate.

**Comment by AnturK** [comment]
Toggle the map index file in dme for editing, just don't stage that change.

**Comment by pubby** [comment]
I don't expect other people to know that and I don't agree with this change at all. It's going to cause a lot of confusion and frustration for people when they try to open the map and get twenty path errors shoved into their face. People who don't know the solution will be locked out of the map. Either that, or they'll submit PR edits to map that "fix" the path errors by removing all the pubbystation-specific paths.

Blegh. I hate this idea.

Still, I did what you said and moved all the files to the PubbyStation folder. Maybe it really is for the best.

**Comment by KorPhaeron** [comment]
@pubby 

Please fix it, this looks cool I'd like to merge it

**Comment by pubby** [comment]
@KorPhaeron Merge conflicts should be fixed. Hopefully.

And man was I crabby yesterday. My apologies, AnturK.

**Comment by Jordie0608** [comment]
Map merger again; protip to fix it quick: make a copy of the current map file then revert it to before this commit, run prepare_maps , delete reverted file, rename your copy to the original file name, run Map Merge, commit changes.

**Comment by pubby** [comment]
I should really just add the map merger as a git pre-commit hook.

I think it's good now.

**Comment by GunHog** [comment]
This is now the best map for Chaplain players EVER.

**Comment by AnturK** [comment]
Yeah, i realize it's not the cleanest  solution sorry for that. I'll try to come up with something that needs less fiddling when it comes to map creation but dm is not really helping here.

**Comment by ExcessiveUseOfCobblestone** [comment]
now all we need to do is make the monk staff nullrod reskin _cool_

**Comment by YakumoChen** [comment]
I like it but it looks like a lot of empty space that nobody will ever use, unless antag.

**Comment by optimumtact** [comment]
Kor would like to merge this, but they will never ever!

**Pull request merged**
