### PR TITLE
adds the troll emoji

### PR DESCRIPTION
**Pull request by oilysnake**
:trollface: 
## About The Pull Request

:trollface:

## Why It's Good For The Game

:trollface: 

## Changelog
:cl:
add: :trollface:
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
:trollface:

**Comment by Rowelll** [comment]
:trollface:

**Comment by Zytolg** [comment]
:trollface:

**Comment by Timberpoes** [comment]
No, thank you for trying.

**Comment by Mothblocks** [comment]
its important to note the creator of the troll face is notorious about sending people cease and desists for using it without his permission, so we will never accept this

**Comment by notfrying1pans** [comment]
:trollface:

**Comment by oilysnake** [comment]
> 
> 
> its important to note the creator of the troll face is notorious about sending people cease and desists for using it without his permission, so we will never accept this

thats fucking hilarious i want this to be the thing that shuts tg down

**Pull request closed without merging**
