### PR TITLE
Makes showers clean WASHABLE_COLOUR_PRIORITY

### PR DESCRIPTION
**Pull request by silicons**
fix.

### CODE REVIEW

**Comment by Supermichael777** [comment]
This is for space cleaner https://github.com/tgstation/tgstation/blob/2672d888001d74672696bd6d494488e7301c027c/code/modules/reagents/chemistry/reagents/other_reagents.dm#L927

**Review by Cyberboss — CHANGES_REQUESTED** [review]
This shouldn't be restricted to mobs

**Comment by Cyberboss** [comment]
Anyway, like @MrPerson seems to be an intentional decision

**Comment by kevinz000** [comment]
@Cyberboss now works on all

**Comment by RemieRichards** [comment]
Please fix the fact that worn/held items do not get ```wash_obj()```'d, they only get cleaned and it's amazon prime shitcode.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
What @ShizCalev said

**Comment by lzimann** [comment]
but shiv never commented in this pr

**Comment by ShizCalev** [comment]
Think he meant remie

**Comment by Cyberboss** [comment]
@RemieRichards revert your Avatar, rreeeee

**Comment by RemieRichards** [comment]
@Cyberboss no, please grow eyes fit for the 21st century.

**Comment by kevinz000** [comment]
done i think

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
