### PR TITLE
[READY] New Singularity Hammer inhands textures

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Adds new singularity hammer inhands, courtesy of @Nebulacrity for the initial sprites, I chopped em up for inhands. Took me 3.5 hours to do it too, lord now I know why spriters hate these things.

@Twaticus This'll need your signoff boss.

## Why It's Good For The Game

These really shouldn't be black recolors.

## Changelog
:cl: Nebulacrity for the sprites, LemonInTheDark for chopshop job
add: Adds proper inhands to the singularity hammer, take a look, they're pretty neat.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I have been asked at threat of absolutely nothing to add [ready] to the title

**Comment by Nebulacrity** [comment]
I wasn't as lazy as I expected myself to be yesterday. You're welcome.

**Comment by Tharcoonvagh** [comment]
Pics pls

**Comment by Twaticus** [comment]
righthand singularity_hammer1 has a stray pixel

**Comment by Nebulacrity** [comment]
Dude's asleep currently but yeah, thanks, will get fixed.

**Comment by LemonInTheDark** [comment]
> 
> 
> righthand singularity_hammer1 has a stray pixel

The pixel has been disposed of

**Comment by LemonInTheDark** [comment]
Have a low res [vid](https://cdn.discordapp.com/attachments/625970248503394304/710375114369400832/2020-05-13_23-16-25.mp4) from my shit pc

**Comment by Shadowflame909** [comment]
That staff exudes charm.

Someone boutta bounce

**Comment by Nebulacrity** [comment]
I tried. *bow

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
