### PR TITLE
Traitors now have the syndicate faction

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
You could probably antag test with this

**Comment by MoreRobustThanYou** [comment]
@PKPenguin321 probably not, as this would likely only affect them not being shot by like, nukeop turrets

**Comment by Anonmare** [comment]
I actually thought they already did have the Syndicate faction

**Comment by MoreRobustThanYou** [comment]
nop. learned this when I got turned into a traitor right before nukeop turrets shot me down

**Comment by jughu** [comment]
Syndicate faction and not getting hurt by the pirates vs syndicate ruin!

**Comment by Steelpoint** [comment]
Do certain turrets or mobs, like the Battleship Ravens Turrets, target Syndicate faction mobs?

**Comment by DoctoreMad** [comment]
Oh el oh hel. So I can buy Battleship Raven to instantly win against any traitor who has hijack/escape objectives?

**Comment by MoreRobustThanYou** [comment]
Doesn't Battleship Raven target mobs in the "hostile" faction?

**Comment by Steelpoint** [comment]
I just want to ensure there are no unintended side effects with the change.

**Comment by Anonmare** [comment]
I think the Raven turrets shoot everything without a neutral faction, and traitors should still have the neutral faction so it should be fine.

**Comment by Bawhoppen** [comment]
Absolutely no reason for this other than powercreep

**Comment by MoreRobustThanYou** [comment]
@Anonmare >shooting things in passive faction

lmao

**Comment by KorPhaeron** [comment]
@MoreRobustThanYou 

What is your goal with this PR?

**Review by imtakingabreakdontatme — CHANGES_REQUESTED** [review]
Please clearly explain what your goal with this PR is

**Comment by jughu** [comment]
Clearly the goal is that traitors wont get hurt by ayndicate mobs from various ruins giving them free loot

**Comment by MoreRobustThanYou** [comment]
@KorPhaeron this is kinda an i ded PR lmao, I got killed by nukeop turrets 10 seconds after admemes made me a tator

**Comment by WJohn** [comment]
I am very much in favor of this. It makes syndicate shock troops much more of a "time to go loud" kind of deal for syndies, and means I don't have to set them to the syndicate faction myself when I want to bring them aboard a syndicate base event I spawn in.

Yes, it could technically be used to antag test but outside of syndicate shock troops you're not likely to find syndicate mobs, and the only places with syndie turrets are the nuke op ship and maybe a handful of ruins in space. Not exactly easy to perform the test where it could be easily chalked up to the sec officer having been targetted first!

**Comment by KorPhaeron** [comment]
This would fuck up servers with away missions and make nuke op shuttles defenseless against traitors helping the crew

Also adds an antag test to the syndicate portal event

**Comment by MoreRobustThanYou** [comment]
@KorPhaeron syndicate portal event is rare, and when it does occur, it gives traitors a chance to go loud

**Comment by Bawhoppen** [comment]
Honestly the portal event needs to be removed or made not terrible

**Comment by WJohn** [comment]
The only thing I have a problem with here is how syndies can effectively kill simple animal syndicates and loot their bodies with no fear of being attacked. This is sort of powergamey but not the worst thing ever.

**Comment by jughu** [comment]
Just make them change factions to 100% hostile when attacked

**Comment by WJohn** [comment]
I mean then you'll end up with dumb cases of friendly fire where they'll shoot eachother because one of them got triggered by a player.

**Comment by jughu** [comment]
its just a grumpy syndicate part time worker! he just doesnt care anymore!!!

**Comment by KorPhaeron** [comment]
no for the reasons I listed, wouldn't be fair on away missions or for traitors to waltz into the nuke ops ship

**Pull request closed without merging**
