### PR TITLE
airlock style edit

### PR DESCRIPTION
**Pull request by rasehgal**
## About The Pull Request
Update airlock print per open issue
## Why It's Good For The Game
Requested
## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Accidental?

**Comment by rasehgal** [comment]
Yep, please disregard, will fix when I’m back at my desk. On Jan 12, 2023, at 5:57 PM, necromanceranne ***@***.***> wrote:﻿
Accidental?

**Comment by SyncIt21** [comment]
Thank you for the help but i got this one 👍  #72680

**Comment by Mothblocks** [comment]
Superceded

**Pull request closed without merging**
