### PR TITLE
Fixes megafauna being able to port through jaunt tunnels due to snowflake code

### PR DESCRIPTION
**Pull request by silicons**
And apparently necropolis tendrils too...

### CODE REVIEW

**Comment by Kromgar** [comment]
Oh fuck that got broke? AMAZING

**Comment by Buggy123** [comment]
FUCK. THE SECRET IS OUT. NOW I'M GONNA HAVE TO USE THE DAMNED MINING SHUTTLE FUCK!

**Comment by Kromgar** [comment]
Eh mining shuttles more work... also more lethal if you fuck up but it can work out pretty well... only issue is you can't get colossi onto the shuttle

**Comment by Buggy123** [comment]
BUT I'D REALLY LIKE TO NOT HAVE TO USE THE MINING SHUTTLE DURING MEGAMEMES

**Comment by Buggy123** [comment]
ALSO COLOSSUS IS POSSIBLY THE BEST FAUNA TO GET ON THE STATION DAMNIT

**Comment by Kromgar** [comment]
@Buggy123 I know... but there's nothing we can do to prevent it's quillls from destroying the console.


At best you can try and time it just as it gets on before a quill fucks you

**Comment by Buggy123** [comment]
image
image
image
image

image
image

**Comment by Kromgar** [comment]
This convo has been had before. I just accepted it and only drew ash drake or bubblegum to station

**Comment by Potato-Masher** [comment]
Aw heck. How is a lone traitor miner supposed to make admeme tier shenanigans now? I honestly think it's not all that bad every once in a while, a refresher from the norm. And besides, the chance of it happening is low.

3 miners out of 70-90 players.
Each dude has a low chance of being a solo antag in the first place depending on the amount of tators/lings.
On top of that, Buggy has been very diligent about keeping this technique on the down low, so barely anyone knows about it.
In the rare case they DO know about it, they might not feel like doing it in favor of another strat just so they can get the greentext.

Idk. I know everyone might not feel the same way, but all the rounds that this has happened it was pretty fun. Just trying to survive, waiting for the ERT to save us, and then getting to watch as the DS tries to solo the Colossus or something.

**Comment by Buggy123** [comment]
If this goes through, I'll make a new PR to re-enable it but also add admin logging so that admins can keep a eye on it if it gets out of hand. Maybe also a admin toggle if I can figure it out but I doubt I can.

**Comment by Kromgar** [comment]
It did have admin logging

**Comment by kevinz000** [comment]
@Buggy123 far as i'm aware, old portals did not allow this unless you THREW the megafauna through which is almost impossible as they're anchored.
it was only made possible through my patch.
it was not intentional by me.
so now I'm fixing it.
@Buggy123 that's in case we use portals in the future that allow anchored objects like megafauna. Not for this.
Literally anyone can get to lavaland and portal them to the station, it doesn't take a traitor miner but it makes it more likely. You can still do this but you have to use the mining shuttle.
So yeah, not intentional.

**Comment by Buggy123** [comment]
A: if someone who is not an antag does it and it's intentional (unintentional is very unlikely, I've fled from fauna with jaunters and never had them follow), ban them because they basically did the equivalent of bombing half the station/releasing the singulo.

B: LET. PEOPLE. HAVE. FUN. I could name a dozen damned features that are actually just ascended bug. Being a 'bug' is not a issue. And seriously, how is this abused?

Scientists get 6 bombs worth of destructive potential and a free license to do literally all the prepwork necessary to use it as part of their job, with minimal risk.
Chemists can make a grenade that renders a entire room uninhabitable with about 3 minutes of work, and mass produce them with a lathe.
Do I need to mention the round where a virologist made a virus that killed you so quickly, that even if you ate the cure (SUGAR) before getting infected AND had a brute patch for burst+continuous healing, you still die? 

Jesus fuck, half the station can destroy half the station, that's part of the damned fun. Megafauna on the station are interesting, rare enough to not be irritating, and uniquely _combatable_ because they can DIE, so random people have both opportunity and encouragement to fight back, instead of running from a instant death energy ball that teleports behind you and kills you before you know its near you, or the abstract unconquerable barrier that is vented hallways/raging plasma fires without a suit. Admins get a opportunity to spawn ERTs, make memes, bring ghosts back into the round... how often do we get a ERT to fix the crater formerly known as Engineering after they fuck up the SM?

Holy fuck, I am the saltiest most fun-hating person who hasn't outright quit yet and I'm telling you to stop killing fun. What the fuck?!

**Comment by Kromgar** [comment]
@kevinz000 

https://github.com/tgstation/tgstation/issues/17960

**Comment by Buggy123** [comment]
FUCK

**Comment by Kromgar** [comment]
@Buggy123 do what you promised make a patch adding logging(although i'm pretty sure jaunter logging exist) and try to let megafauna go through portals again.

**Comment by Buggy123** [comment]
It should already log, but alright. I will wait to see whether the fix or the revert PR that is currently up get merged, and if the revert isn't merged I'll try to add more detailed logging and re-enable fauna going to the station.

**Comment by Shadowflame909** [comment]
"LET. PEOPLE. HAVE. FUN. " This is forgotten sir. Coders would rather have the shitters continue playing, by abusing shit as non antags, then rather let the people who would never think of abusing such a thing. Keep using it! Reeeeeee

**Pull request merged**
