### PR TITLE
Improved material colors

### PR DESCRIPTION
**Pull request by MrPerson**
## About The Pull Request
Gave better color matrices to some materials. Simplified some of the existing matrices down. Gave uranium a standard color since it didn't need a matrix. Made bananium obnoxiously bright. Made gold slightly less bright. Made diamonds somewhat brighter. Made glass actually look like glass, it was almost grey before wtf.
Improved some of the greyscaled sprites used by materials, many of them were too dark and/or straight reused from other things. Some of them weren't even grey come on guys.

## Why It's Good For The Game

Looks even nicer than the last tweak to the material colors. Here's some examples.

image

image

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Ya know, how would gold look if the online color was closer to like a yellowish orange? I know we already tried orange for gold and it looked super wrong but at least this way you kinda get some of the darker shades of gold's color.
image
All in all though I like everything here anyway

**Comment by MrPerson** [comment]
Yeah I think gold probably oughta be a touch darker. I'll try some out and see if anything looks good

**Comment by cacogen** [comment]
make glass transparent

**Comment by Qustinnus** [comment]
Glass alpha is way too high

**Comment by MrPerson** [comment]
Glass alpha is back where it was, dunno what I was thinking. It looks MUCH nicer like this. Gold is more... golden brown and less bright. Also fixed mythril by request. Here's your picture you cretins.

image

**Comment by 81Denton** [comment]
Noice

**Pull request merged**
