### PR TITLE
revamps toxins

### PR DESCRIPTION
**Pull request by granpawalton**
:cl: Granpawalton
add: toxins on all maps now have an unlocked chamber air alarm, 2 air pumps, a rpd, a heater, a freezer, and igniters
tweak: the pipe arrangements in toxins have been reorganized for efficiency
/:cl:

[why]:  These are some common complaints i hear among toxins players about the maps, this doesn't give them anything they don't already have but it cuts out things that they shouldn't have to do to complete their job such as running to aux mining to get the rpd there or hacking their air alarm when we already have /obj/machinery/airalarm/mixingchamber for a reason. I wanted to do this a while ago but chose not to because of bomb rushes would be even faster after these changes were made but after #40107 I feel like it will not cause an issue. The efficiency changes were based around conserving gas by not using extra pipe segments where it would diffuse out of the canister to or changing unused pipe segments to more useful ones.

Sample from metastation:
revamps toxins 2

### CODE REVIEW

**Comment by Wilchenx** [comment]
we should probably just move toxins to atmos

**Comment by granpawalton** [comment]
im definitely not opposed to that

**Comment by Tlaltecuhtli** [comment]
make the burn room air alarm indipendent and unlocked (steal from box toxin)

**Comment by Grazyn** [comment]
QoL changes that are useless now that tech points are capped, and yes what wilchen said, why rework toxins so that they have a complete atmos setup at roundstart (unlocked air alarm, even fucking RPD when they can just hack the autolathe, another freezer/heater)  instead of just giving 6 TTVs to atmos and call it a day?

**Comment by Barhandar** [comment]
That freezer/heater setup is still inefficient due to connectors AND machinery having volume too, so they'll still have to use the movable pumps. The rest is great.

**Comment by 81Denton** [comment]
>instead of just giving 6 TTVs to atmos and call it a day

Probably because you'll need to remap a whole bunch of areas to make it work

**Comment by kriskog** [comment]
Mostly good changes, but you have completely removed the filter from meta at least. I understand space is an issue, but can you try to fit it in? Maybe remove a bomb locker, and turn the freezer/heater around.

**Comment by Grazyn** [comment]
>Probably because you'll need to remap a whole bunch of areas to make it work
as opposed to remapping toxins on all maps so that tritium is easier to make, which is what has been done in the past couple weeks? What kind of gargantuan remapping effort is giving ttvs to atmos and make the door to testing range atmos access only? The range can already be reached directly from maint on most maps (meta, delta, box, dunno about the others)

**Comment by 81Denton** [comment]
>What kind of gargantuan remapping effort is giving ttvs to atmos and make the door to testing range atmos access only?

It leaves science with a toxins mixing area, but no launch site access because ???
Not to mention that on plenty of maps, the launch site is far away from atmos, has the RD hardsuit, RnD coloring etc.

**Comment by Kagus** [comment]
Who needs a launch site when you have dorms?

**Comment by Grazyn** [comment]
@81Denton obviously toxins would have to be removed from science since it would fall under atmos.
It still feels weird to me that toxins was barely touched for years, then someone finds a good setup to get tritium that requires repiping and a bunch of other atmos tweaks (like air alarm access, scrubber instead of vent etc.) and suddenly there is a shower of PRs completely remapping toxins on all maps (much more effort than replacing some colored tiles and moving a suit closet) so that scientists can have the optimal setup at roundstart, going as far as giving them atmos-specific gear (RPD). That's not QoL, that's like giving botanists a chem dispenser so they can cut all the prep time of making mutagen-melons and stuff.

Atmos can make tritium with minimum effort and they already have all the tools they need. It seems logical that it would be easier to give them TTVs rather than turning toxins into mini-atmos.

**Comment by Barhandar** [comment]
Also, maybe this will finally result in non-negligible amounts of plox, stimulum and h-n being made.

Or just sci getting extra BZ.

**Comment by ExcessiveUseOfCobblestone** [comment]
For the meta filter you should have the connector up and left as opposed to directly north, otherwise the mixing canister can't be reached if every port is wrenched in.

**Comment by subject217** [comment]
This is a buff disguised as QoL. The real effect of these changes is that the time it takes for le epic bombs can be produced is significantly decreased.

**Comment by granpawalton** [comment]
@ExcessiveUseOfCobblestone I was trying to avoid having any excess piping for gas conservation and due to the fact that they could grab a canister at the south or east ends of the 3 way connector

@subject217 Also that is something i was worried about and it was my main reason for not doing this sooner, but after the point cap rework the baby max caps and the max caps that take longer than 5 minutes to make have little to no difference so this change was more geared towards helping the larger bombs due to them currently only being made for dick measuring. If it does need time gating i would rather it be done in a way that is blatant time gating like rnd instead of having them run menial chores every round. If i am just being biased though more contributors can ask for a time gate to be in place and i will handle it adjacent to this PR.

**Comment by duncathan** [comment]
make toxins part of the atmos department

**Comment by kriskog** [comment]
That's a lot of moaning over removing a few excess pipes that is only a problem because the atmos system has shortcomings that is a pain to deal with.
The pumps added are usually stolen from outside atmos, and are really annoying to find gone because of someone doing toxins. This is a good change.
The RPD is not actually needed to do the bomb rush, and wont speed it up noticably. It is strictly a QoL change. You no longer have to cannibalize the pipe setup to do different, more advanced stuff. You give people working with plants plant stuff, why not give the people working with pipes and gases pipe stuff? It is not comparable to giving a chem dispenser to botany at all, and you are overreacting.

And last, to all of you saying to move toxins to atmos. Why do you wanna give scientists less work to do? If anything make it easier for atmos techs to do bombs for research, but leave toxins as part of science. Now keep in mind atmos tech is strictly speaking a maintenance role, meant to fix breaches and keep the station oxygenated. I think giving them a play area is great, but lets not balance their role around the play instead of the actual work.

**Comment by ExcessiveUseOfCobblestone** [comment]
@granpawalton we need corner-pumps tbh

**Comment by Bawhoppen** [comment]
Resource-creep by giving them an RPD, and also QoL is poor argument, since some of the intended work they have to do comes from the fact they need to re-arrange pipes in a different way.

**Comment by kriskog** [comment]
Hey @Bawhoppen , guess what kinda tool you can use to rearrange pipes.

**Comment by granpawalton** [comment]
@Bawhoppen i only changed the ones they don't typically change anyways when making bombs, things like the 3-way mixer or filter that is slightly inefficient and most players cant be half assed to change. The only other changes were making sure all maps had the same tools so someone wont say "oh i don't want to do toxins because we are on X-station". Also are you saying it is resource creep because now they have a 2nd one or because now they have one that isn't a 20 second walk to get?

**Comment by ExcessiveUseOfCobblestone** [comment]
resource creep is meta's drone dispenser getting removed but the free stack of metal/glass beside it wasn't.

**Pull request merged**
