### PR TITLE
Feature Freeze February is now in effect. All feature PRs above this PR will be closed

### PR DESCRIPTION
**Pull request by Time-Green**
For the month of February, no new features.

### What's a feature?
Anything changing or adding to in-game mechanics. Anything you would tag with feature, qol or balance would fall under this. 
Purely sprite or mapping changes are fine.

Also no dropping 7000 lines feature PRs on the first of March or you will be deleted

### CODE REVIEW

**Comment by Time-Green** [comment]
If we hit 0 open issues we'll consider ending feature freeze february a day early

**Comment by Ekaterina-von-Russland** [comment]
Is this real or is this a troll post?

**Comment by Jolly-66** [comment]
I'll drop a 7001 feature PR on 3/1, that way I CAN'T get deleted

**Comment by Time-Green** [comment]
> Is this real or is this a troll/meme post?

Fix every bug and you'll find out

**Comment by VladinXXV** [comment]
wheres the blame mso label

**Comment by lessthnthree** [comment]
Purely spite changes are fine.

**Comment by Wallemations** [comment]
And yet this has the feature tag ~~(along with every other tag)~~...  strange...

**Comment by CPTANT** [comment]
> Purely spite changes are fine.

All my changes are out of spite.

**Comment by Mothblocks** [comment]
@Wallemations its also not getting merged :-)

**Comment by Wallemations** [comment]
> @Wallemations its also not getting merged :-)

_Yet_

Just wait for March, it might

**Comment by Overuseddart** [comment]
Let’s hit 13k issues so we can become github13

**Comment by Fikou** [comment]
its march for me

**Pull request closed without merging**
