### PR TITLE
Slaughter Demons no longer have an infinite range, point-and-click attack that can also be used while phased.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

RMk0H40Nts

Fixes this by adding an adjacency check.

## Why It's Good For The Game

Someone did an uwupsie.

## Changelog
:cl:
fix: Slaughter demons now require physical adjacency to body slam and can't body slam while phased.
/:cl:

### CODE REVIEW

**Comment by D4C-420** [comment]
wait since when could slaughter demons do that?

**Comment by Timberpoes** [comment]
> 
> 
> wait since when could slaughter demons do that?

Shaps added it as part of wounds 8 months ago. For 8 months all slaughter demon types have been able to psychically body slam people from infinite range.

**Comment by ATH1909** [comment]
awwww.

I liked having this; it gave slaughter demons something to do/set up new blood pools with if the station was on the ball with denying you access to blood streaks. I'd like to see it come back as an intended mechanic at some point; it's really fun to yeet people who happen to be standing in the wrong place into vending machines.

**Comment by cacogen** [comment]
These suck

**Comment by interestingusernam3** [comment]
Alternative title: removes anime wrestlers.

**Comment by Timberpoes** [comment]
> 
> 
> awwww.
> 
> I liked having this; it gave slaughter demons something to do/set up new blood pools with if the station was on the ball with denying you access to blood streaks. I'd like to see it come back as an intended mechanic at some point; it's really fun to yeet people who happen to be standing in the wrong place into vending machines.

The body slam is still there, it's just not telekinetic anymore. You have to be adjacent to the target and corporeal.

**Comment by ATH1909** [comment]
> > awwww.
> > I liked having this; it gave slaughter demons something to do/set up new blood pools with if the station was on the ball with denying you access to blood streaks. I'd like to see it come back as an intended mechanic at some point; it's really fun to yeet people who happen to be standing in the wrong place into vending machines.
> 
> The body slam is still there, it's just not telekinetic anymore. You have to be adjacent to the target and corporeal.

yeah, but it was the incorporeal part that was really cool

**Pull request merged**
