### PR TITLE
Gumballs and spider lollipops can now be put in your mouth and chewed/sucked!

### LINKED ISSUE #49643: Gumballs cannot be placed on mask slots
## Reproduction:
With the addition of #49431 we now have gum that can be consumed like suckers by equipping them to the mask slot. However, this behavior has not been added to gumballs, you still have to eat them like normal food.

### PR DESCRIPTION
**Pull request by Rodey125**
## About The Pull Request

Fixes https://github.com/tgstation/tgstation/issues/49643

## Why It's Good For The Game

This allows you to chew gumballs and suck spider lollipops, which fixes the consistency issue brought about by not being able to do so.

## Changelog
:cl:
tweak: gumballs and spider lollipops are now a subtype of chewables
/:cl:

### CODE REVIEW

**Comment by Rodey125** [comment]
credit to ME for finally doing something on my own for once

**Comment by Coastfront** [comment]
When can we chew and suck other crewmembers~

**Comment by RaveRadbury** [comment]
My hero

**Comment by Rodey125** [comment]
> My hero

i was dumbfounded when that guy just flat out ignored your request to add this, it took me 5 minutes to do once i actually figured out WTF i was looking at

**Comment by Mickyan** [comment]
no the guy did not flat out ignore the request, the guy explained that the PR was adding chewing gum to an already existing feature (equipping lollipops in mask slots) and did not want to add unrelated changes in that one particular PR, is this clear enough for you?

**Pull request merged**
