### PR TITLE
Fixes turret lethal mode not targeting lying/handcuffed/critted humans

### LINKED ISSUE #22606: AI turrets on the lethal setting do not seem to target lying humans
I witnessed a round in which the AI stunned the CE with its turrets, then flipped them to lethal to finish him. The turrets did not fire lasers while he lying down, only when he stood back up.

AI turrets, on the lethal mode, are supposed to fire until the target is dead, regardless of lying or standing. Basically, the turrets are still acting as if they are on the stun mode.

I have not taken the time to examine the code or figure out who broke AI turrets.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #22606

### CODE REVIEW

**Comment by Supermichael777** [comment]
this is actually a severe nerf because you can brainlessly rush the guns before they re-target

**Comment by Supermichael777** [comment]
not that you cant already brainlessly rush them due to the pathetic fire-rate of the gun-turret but....

**Comment by GunHog** [comment]
The AI player is supposed to stun, then switch to lethal mode in order to finish the target. Done quickly enough, the turrets will not need to close and re-open.

**Comment by Supermichael777** [comment]
is an ai player ever told this?

**Comment by Jordie0608** [comment]
No but we don't tell security to tase assistants before beating them, yet they figure it out fine; not everything needs to be explicit.

**Pull request merged**
