### PR TITLE
Moves Air Alarm Status to the bottom of the UI

### PR DESCRIPTION
**Pull request by rdragan**
## About The Pull Request
Moves the Status part to the bottom of the Air Alarm UI, ensuring the controls are at the top and won't get moved when the Status adjusts height.

## Why It's Good For The Game
Having the variable height status section at the top of the UI means that the entire contents of the UI will get shifted whenever the gas contents change. This makes the controls unreliable at best and useless at worst in conditions where the gas is constantly changing, such as fires or exotic SM setups, in other words, exactly when you need it the most.

For most people that just glance at air alarms this will change nothing, as they can't even unlock them normally. For anyone actually working with air alarms, I have never found the status to be of any real value, you have better tools to get an idea of what's happening with the air in an area and I can't remember a single instance of ever using the air alarm status to check up on gas contents as Atmos/Engi/CE. If you really need to, all you have to do is scroll down instead of up.

## Changelog
:cl: Thebleh
tweak: The Status section of the Air Alarm interface has been moved to the bottom.
/:cl:

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
toxins scientists use their air alarm to watch gas contents in the mix chamber, though thats broken most maps and they dont properly display the chambers contents, but they are supposed to

**Comment by rdragan** [comment]
> toxins scientists use their air alarm to watch gas contents in the mix chamber, though thats broken most maps and they dont properly display the chambers contents, but they are supposed to

Air Alarms scan the turf they're in, so they have no means of showing you what's inside the burn chamber, incinerator or SM.
Toxins does have a console that's connected to the gas sensor inside the chamber and will allow you to monitor the chamber's contents.

**Comment by AlinaStarkova** [comment]
> > toxins scientists use their air alarm to watch gas contents in the mix chamber, though thats broken most maps and they dont properly display the chambers contents, but they are supposed to
> 
> Air Alarms scan the turf they're in, so they have no means of showing you what's inside the burn chamber, incinerator or SM.
> Toxins does have a console that's connected to the gas sensor inside the chamber and will allow you to monitor the chamber's contents.

really? oh, i always thought the alarm just showed the average of whats in the room, hmmm, suppose this means a tot could flood a room with co2 and put a scrubber right under the alarm so it never goes yellow/red hmmmmm

**Comment by LemonInTheDark** [comment]
What does this end up looking like?

**Pull request closed without merging**
