### PR TITLE
Reduces the number of steps in the augmentation surgery

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR cuts out two steps from the list of steps required to perform the augmentation surgery, making it much less tedious to perform.

## Why It's Good For The Game

This should make roboticists ask for to code craftable automated (automatic?) surgeons for them less often (like one did in this thread: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=24307).

## Changelog
:cl: ATHATH
balance: Two steps have been cut out from the augmentation surgery, making it much less tedious/time-intensive to perform a full-augging on someone. The new sequence of tool usages that you should perform on someone after you've started an augmentation surgery on them is: scalpel -> hemostat -> retractor -> robotic limb.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
smiling cat views list of webedit commits with pride and satisfaction as he proclaims that yes, he is a coder

**Comment by CPTANT** [comment]
Good change.

I still feel inserting implants should go from organ manipulation to augmentation surgery though.

**Comment by anconfuzedrock** [comment]
augs are really useful they don't need to take only 30 seconds to apply especially without a saw

**Comment by GuyonBroadway** [comment]
Honestly surgery in general is tedious, there really isn't anything fun about waiting on five timers.

**Comment by carshalash** [comment]
Saw should be required, one of the other steps should be skipped.

**Comment by Time-Green** [comment]
You can augment the whole body at once, just have a defib with you

**Comment by ExcessiveUseOfCobblestone** [comment]
what does full aug do again?

Damage Threshold?
Easier Self-Healing?
EMP bad?

**Comment by Shadowflame909** [comment]
full aug gives 20% innate armor. Makes EMP's a 10-second stun with full body damage.

Space proof (still need to breathe) and allow you to equip stuff while suitless.

I think the healing itself needs a power-creep. Augmented nerds still heal toxins via medicine. But the only way to heal burns and brutes is cable coil and welder.

This takes a good minute with the action timer, and it makes it really not good for combat. Considering if you try to get augmented for mining and are being chased by a megafauna. You can't stand still and wait 10 seconds to fully repair a limb.

I wonder if an advanced welder being an instant heal/ something close to it like 3 second heal would be merged.

**Comment by ATH1909** [comment]
> full aug gives 20% innate armor. Makes EMP's a 10-second stun with full body damage.
> 
> Space proof (still need to breathe) and allow you to equip stuff while suitless.
> 
> I think the healing itself needs a power-creep. Augmented nerds still heal toxins via medicine. But the only way to heal burns and brutes is cable coil and welder.
> 
> This takes a good minute with the action timer, and it makes it really not good for combat. Considering if you try to get augmented for mining and are being chased by a megafauna. You can't stand still and wait 10 seconds to fully repair a limb.
> 
> I wonder if an advanced welder being an instant heal/ something close to it like 3 second heal would be merged.
> 
> Edit: Tldr being augmented has saved my butt during a plasma flood/bombing situation when there is no Air. But it's not all that combat savvy as an option. Considering you can't heal in combat like other current medicines.

Alright, lemme dissect this:
1. I don't know where the hell you got that "20% innate armor" thing from; that's not how the damage reduction from augmented limbs works at all. When an augged limb, torso, or head (to clarify, I mean a cyborg limb, torso, or head; prosthetic ones don't count) takes brute or burn damage, that damage is reduced by a flat amount (by 5 points for brute damage or by 4 points for burn damage). This damage reduction takes place after armor reduces the severity of the incoming damage, IIRC.
2. The stun length due to getting EMP'd while having a robotic limb, torso, or head (not necessarily a cyborg one) depends on the strength of the EMP. If the EMP effect is a category 2 EMP effect, you'll get paralyzed for 10 seconds and your robotic body parts will take 5 damage each; if the EMP effect is a category 2 emp effect, you'll get paralyzed for 20 seconds and your robotic body parts will take 10 damage each (by "robotic body parts", here, I of course mean robotic torso, heads, and limbs).
3. Healing yourself while augged can be done at a perfectly reasonable rate; I don't know what you're on about. You do know that you can weld multiple things (or even the same thing multiple times) at once, right?
4. If you want an instant heal, just ask someone else to weld you; each welding attempt made to heal someone other than yourself can be performed instantly.
5. It should be noted that most healing chems don't heal robotic limbs and that the mechanical repair nanite program only affects robotics heads, torsos, and limbs (and that the accelerated regeneration and bio-reconstruction programs can't heal robotic body parts).

**Comment by ATH1909** [comment]
@ExcessiveUseOfCobblestone ^

**Comment by ExcessiveUseOfCobblestone** [comment]
i'd like to see the saw step somewhere in here

**Pull request merged**
