### PR TITLE
Reworks and resprites the metal hydrogen fireaxe

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request

<details><summary>Small useless personal stuff here</summary>
<p>

This is my 100th PR for TG and I wanted to buff my main job!
I actually kinda hate that I realized that my next PR would be the 100th, it kept bugging me to do something big or important instead of cleaning some random `allowed_list` that I have done multiple times even if I know code readability is important and I love working on that.
The first thing I coded for SS13, but never PRed, was a pair of items: A heavy 2 handed welder for engineers, their version of a fireaxe basically, and a telescopic fireaxe that I had no idea where to put.

I kinda worked the second in this PR, just 3 years late...

----

</p>
</details>

Changes the MH axe to work more as an upgraded tool instead of a worse version of a roundstart item:

1 - It can be used as a crowbar for anything with the default speed of 1.
2 - It has decreased damage (15 instead of 24) but it has a high `demolition_mod` of 2, meaning that it still does the same damage to structures or machinery that the fireaxe does (30)
3 - It can be carried on the exoslot of most Atmos/Engineering clothing including their MODsuits, firesuit, wintercoats and the hazard vest.

While I was there I sorted the `allowed` list of items of some suits to be in ABC order, have an item per line, trailing comma, etc.

## Why It's Good For The Game
fireaxe
Yes, the new sprite is close to an oversized crowbar to easily convey that it is a tool and meant to be carried around.

The MH axe we have is a 100% worse item than the fireaxe that Atmos Techs have access roundstart, it's only saving grace is that it can be spammed so you often only see it made when something like a revolution or cult is going on.
An Atmos tech that enjoys the "janitor" side of the job and goes around fixing damage has no reason to ever get close to Metal Hydrogen and that is just sad, it is the perfect material to lock efficient tools behind but it is mostly used for golem spam in my experience...

With these changes it becomes a flavorful tool for Atmos Techs to work on their free time.
Using the fireaxe to make entry or exit points mid emergency  is one of the most enjoyable parts of the job that is ignored for most of the players because your backpack slot is way more valuable than the average job.
You can't work on breaches easily without a MODsuit, the firefighting backpack is another fun tool that uses that slot and you need to carry a lot of materials for repairs.

With this new MH axe you can carry and use it without conflicting with these 3 above and without having to deal with a clown or greytider shoving you to steal your fireaxe mid emergency because the only way to carry it is by hand.

## Changelog

:cl: Guillaume Prata
balance: Metal Hydrogen axe was reworked. It now work as a crowbar, can be stored on most engineering/atmos suits and deal less damage than the default fireaxe (15) against mobs while still doing the same damage (30) to structures or machinery.
/:cl:

### CODE REVIEW

**Comment by KommandantJackal** [comment]
Can you make it customizable with a pen? I wanna give my axe fun names and descriptions

**Comment by itseasytosee** [comment]
Glad to see demo mod being useful.

**Comment by Palpetinus** [comment]
>An Atmos tech that enjoys the "janitor" side of the job and goes around fixing damage

Holy shit I never expected my playstyle of atmos tech to get any sort of acknowledgement
Half-joke aside, maybe it's time to actually figure out advanced atmos stuff instead of just "pump the bajillion moles of air into the hallway" gameplay I'm usually doing.

**Comment by Colovorat** [comment]
so it has less damage, but does it have the same wound chances or whatever

**Comment by GuillaumePrata** [comment]
> so it has less damage, but does it have the same wound chances or whatever

It has the same wound modifiers but those get multiplied (or whatever, I didn't read the code) by the base damage value.
So I assume it will have lower chances of wounds.

**Comment by distributivgesetz** [comment]
Giving incentive to do an atmos project in order to maintain the station better and vice versa is my dream for engineering, they are both incredibly fun ways to play the department but they don't have to be separated!

**Comment by gitbirb** [comment]
Would it be able to fit on hazard vests?

**Comment by GuillaumePrata** [comment]
> Would it be able to fit on hazard vests?

Yes

**Comment by Jackal-boop** [comment]
LETS GOOOOOOOOOOOOOOOOOO

**Pull request merged**
