### PR TITLE
Increases morbidity factor (fix morbid surgery boost)

### PR DESCRIPTION
**Pull request by FlufflesTheDog**
## About The Pull Request
Fixes a bug that prevents morbid surgical implements from receiving their 30% speed boost. Also removes a small redundant check in the same area 
## Why It's Good For The Game
Fix bugs!
## Changelog
:cl:

fix: Morbid (coroner's) tools now properly receive their speed boost in appropriate conditions

/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
30 morbillion% surgery speed increase

**Comment by TheVekter** [comment]
I was wondering why it felt a little slow, though I chalked it up to the increase just not being immediately noticeable. Nice catch.

**Comment by necromanceranne** [comment]
Oops

**Comment by EricZilla** [comment]
I really pushed a mediborg out the way to do tend wounds on a corpse for nothing huh

**Comment by necromanceranne** [comment]
borg is absolutely going to be faster than even a functioning morbid speed boost, so yes. Especially since tend wounds doesn't get that benefit.

**Pull request merged**
