### PR TITLE
Revert "Changes to the Atmos Watertank Backpack"

### PR DESCRIPTION
**Pull request by LanCartwright**
Reverts tgstation/tgstation#28588

image

An entire cult base.
In space.
Made with a water tank, the backpack tank, and a holographic projector.
That can't be ambushed because it's see through.

This is far too strong. You should not be able to build a space station with resin.

oh did I mention this cleans gases too?

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
NU

**Comment by calzilla1** [comment]
EMERGENT

**Comment by Tacolizard** [comment]
GAMEPLAY

**Comment by Tacolizard** [comment]
also like 2 hits to that base and everyone inside dies.

**Comment by GunHog** [comment]
Sure, you can see attackers coming, but your paper thin walls and lack of proper doors means all I have to do is smack it with a decent weapon and there goes all your air!

**Comment by Tacolizard** [comment]
1. make a shitty base really quick and easy
2. it breaks because it's a shitty base that's quick and easy to make


seems balanced to me

**Comment by KorPhaeron** [comment]
The issue is cult spacebases, not one of several tools to create them

**Comment by Anonmare** [comment]
Same effect can be achieved with a breaching shield

**Comment by Ergovisavi** [comment]
Let's see how much of this is the fault of these changes:
* The resin walls can literally be replaced with glass walls, there's a stack of 50 glass in the same room that the atmos watertanks are in and are available everywhere
* The floor is made of metal, which is available everywhere
* The holographic airlock can be replaced with an iron door which is made of metal and available everywhere. It's not 100% as effective, but blocks atmos until you open it
* The air is provided by air canisters which were untouched by me and are available in many locations

Weird, it's almost like my changes have nothing to do with this.

**Comment by ChangelingRain** [comment]
>Same effect can be achieved with a breaching shield

>Weird, it's almost like my changes have nothing to do with this.

Curious. It's almost like this isn't the problem, and cult is the problem? I'm not sure how that could be. Maybe they just have too much leverage.

**Comment by Tacolizard** [comment]
jmad lever should've opened this

**Comment by LanCartwright** [comment]
I'll remove cult.

**Pull request closed without merging**
