### PR TITLE
Makes nanites more accessible, giving them a separate research point type

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Rebalanced the research costs of nanite techweb nodes, splitting them between regular research points and the new nanite research points.

Nanite research points are gained simply by having nanite hosts; the more the merrier. However, there are penalties if the host is non-sentient, non-humanoid (further penalties if it's just a simple mob), or dead. (To prevent just grabbing some xenobio monkeys for easy points)

I set the base point gain ratio to 3.5*mob/sec, on the vague basis that a team of 3 reclusive scientists with nanites will unlock the lower tier nodes in 90 seconds each. Will probably need some testing to make sure it's not too fast or too slow.

## Why It's Good For The Game

- Makes nanites much more accessible without having to delay all other research in the meantime, a common complaint when nanites are used.
- Makes the nanite progression more linear, instead of researching all nodes at once.
- Incentive for the scientists to make nanites more publically available, since it will get them the advanced nodes more quickly.

## Changelog
:cl:
add: Nanites now have their own research point type, gained over time based on the amount of mobs with active nanites.
balance: Basic nanite programming is much cheaper and no longer requires basic robotics.
balance: All other nodes had their cost split into normal and nanite research, lowering their impact on the research progression for other departments.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
> different point types

Was it really that hard to finish implementing that when we got techwebs? I am not sure if I should laugh or cry from how long it took. 

But anyway, good change. Are you planning on implementing it for other stuff?

**Comment by XDTM** [comment]
Can't take credit for the point types, it was already fully implemented by the creator. All i had to do was use it.

**Comment by HomocidlePancakes** [comment]
Yeah, I know it was already in the code. That’s why I started off by complaining. Felt like the creator just half-arsed techwebs.

**Comment by XDTM** [comment]
In their defense, techwebs was already complete, this was always just an extra tool for other coders to build on it.

**Comment by Fox-McCloud** [comment]
I support this, if only because it'll make it all that much more obvious all that much quicker how gamebreakingly overpowered nanites currently are.

**Comment by XDTM** [comment]
If nanites become meta I expect sabotage to become more frequent as well, which should counterbalance the benefits, at least in theory

**Comment by zxaber** [comment]
You might want to take a look at the research log on the server console. I remember seeing code for multiple point types, but I sorta glossed over them since they weren't being used.

**Comment by davethwave** [comment]
Honestly i'm glad that you are making the PR, it opens up a lot of ideas on department specific research points and the like.

**Comment by kevinz000** [comment]
ah, finally a use of the multiple point system.
love ya XDTM!

**Comment by Shadowflame909** [comment]
Now I can finally agree, it's now a potential job for a scientist. Instead of being left as dust!

**Comment by ATH1909** [comment]
Eh, I kind of feel like the main thing that's balancing nanites right now is the cost on research points that diving into them imposes. Sure, them being able to be sabotaged helps balance them, but it (and EMPs and shocks) can't be the only thing balancing nanites.

Just wait until later in the round when the super-critical stuff has been researched, _then_ you can blow your points on nanites without getting lynched. I think that sort of player-enforced timegate is a neat balancing mechanism that currently works just fine.

**Comment by XDTM** [comment]
I definitely prefer them being in the spotlight and nerfing them if they end up being too overpowered, because right now they're too rarely used to get accurate feedback.

**Comment by davethwave** [comment]
Well one way that could be helpful is a chem or something that gets rid of the nanites like drinking 20u of pure iron gets rid of 250 nanites over the duration so if you want to get rid of them entirely you just need to grind a sheet of iron or eat one of the borgs lolipops. That and maybe rare metals like silver and gold would boost nanite production.

**Comment by actioninja** [comment]
Conflict

**Pull request merged**
