### PR TITLE
Failsafe uplink codes.

### PR DESCRIPTION
**Pull request by AnturK**
:cl: 
add: Failsafe codes for uplinks are now available for purchase.
/:cl:

Costs 1 TC , when entered blows up the uplink.
When you really hate the security.
Also cleans up the uplink code code.

Explosion strength up to debate, dev range is probably overkill.

### CODE REVIEW

**Comment by Kagus** [comment]
Does it get added to your notes like the standard uplink code? That would be quite handy.

**Comment by MrDoomBringer** [comment]
It should beep for like, 2 seconds before exploding. That way cunning tators can use it as a last resort nade or something, also for dramatic effect+feedback to other people that the PDA is the thing exploding, not a grenade or something they have

**Comment by PKPenguin321** [comment]
instant is better so sec gets fucked if they do that shit where they threaten you for your code or whatever

**Comment by Kagus** [comment]
Sec, captain, random powergaming vigilantes... Yeah.

**Comment by MrDoomBringer** [comment]
OOOOH wait i get it

**Comment by MrDoomBringer** [comment]
monsterous meme

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
