### PR TITLE
Allow splitting admin tabs

### PR DESCRIPTION
**Pull request by celotajstg**
## About The Pull Request

This PR adds a configuration option for splitting the admin tab sub groups into separate tabs. This allows for greater convenience, as if the tabs are split you do not have to scroll.

But of course, this is something that needs to be toggled first, and current behavior stays as default.

This can be toggled in preferences, and here is how it looks in action:
image

And if you prefer, you can disable splitting as well.
image

An option for wiping and fetching verbs has also been added to the stat panel debug menu, as previously you could only wipe verbs.

## Why It's Good For The Game

Allows for greater convenience in administration and less scrolling.

## Changelog
:cl: Celotajs
admin: Added a configuration option for splitting the admin tab into multiple tabs
admin: Interviews have been moved to the Tickets tab
qol: It is now possible for administrators to split the admin tab into multiple tabs
/:cl:

### CODE REVIEW

**Review by stylemistake — APPROVED** [review]

**Comment by stylemistake** [comment]
I disagree with adding more tabs to stat (to the point they can't fit on one line) and more user preferences, but whatever.

**Comment by Dorsisdwarf** [comment]
> 
> 
> I disagree with adding more tabs to stat (to the point they can't fit on one line) and more user preferences, but whatever.

Then get rid of the "interviews" tab (Why does it even exist? Interviews are possibly the single least-used admin feature they do not deserve that big splot of prime real estate)

**Comment by celotajstg** [comment]
Made a minor phrasing improvement in preferences_toggles.dm - noticed it was not committed previously.

No further changes are planned, the pull request is ready to be merged.

**Comment by CoffeeDragon16** [comment]
> Then get rid of the "interviews" tab (Why does it even exist? Interviews are possibly the single least-used admin feature they do not deserve that big splot of prime real estate)


 I disagree, interviews are intended for big events like the Ball and proved quite useful for the last one. I don't find they get in the way.

**Comment by wesoda25** [comment]
I do. Tab clutter sucks, why would we give a feature used 1-2 times a year “prime real estate”?

**Comment by celotajstg** [comment]
@wesoda25 you will like this
image

**Comment by Qustinnus** [comment]
more prefs means shittier UI in the future, bad idea.

**Comment by RaveRadbury** [comment]
Moving Interviews under tickets was a good move.

**Pull request merged**
