### PR TITLE
.38 no longer insta stuns

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
balance: .38 no longer insta stuns, it still deals 25 brute
/:cl:
>inb4 limited ammo 

yeah its not like the seclathe prints the ammo and every detective and their mother have at least 7 speedloarders in their bag
>inb4 det nerf 

yeah det isnt supposed to be the elite officer which dies to a stun pod and then traitor LB kills everyone with a .38
>inb4 i ded

not an argument yet i didnt die from .38 
>inb4 useless now

1 shot slows down 2 shots and he is down 3 shots stuns an armored target maybe i should also lower the stamina dmg

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Take it from hippie, we did this and now our lives are much better for it.

**Comment by ExcessiveUseOfCobblestone** [comment]
> yeah det isnt supposed to be the elite officer which dies to a stun pod and then traitor LB kills everyone with a .38

sounds like grudgecode

**Comment by Tlaltecuhtli** [comment]
@BeeSting12 its not really short when one hit means you have 100% chance of unloading your revolver on him

**Comment by GuyonBroadway** [comment]
1hit ranged stuns are cancer and your lives will be infinitely better once you delete them all.

**Comment by ExcessiveUseOfCobblestone** [comment]
If you're complaining about stun-based combat (which is fair) then don't do it piecewise.

At the very least buff the stamina damage if you're removing the stun.

**Comment by Tlaltecuhtli** [comment]
65 is 2 shots to fuck up a person, a disabler needs 3

**Comment by GuppyLaxx** [comment]
totally not an ided, none of the upvotes are an ided either ok

**Comment by imsxz** [comment]
>infinite range tazer >less visible, indistinct bullet sprite >less visible, indistinct in-hand sprite >indistinct sound >ammo-based rather than energy based, meaning it doesnt need to take any time to recharge its uses >hard counters adrenals via brute+stamina damage >hardcounters deswords/eshields by virtue of being a ballistic weapon >people actually unironically believe it's balanced

i can't think of a single reason i'd ever take a tazer over a .38

**Comment by GuyonBroadway** [comment]
Honestly it would be nice if we could put it in a position where giving officers the option of a .38 as opposed toba taser would be nice.

Less hard stunning power for more flexibility.

**Comment by PKPenguin321** [comment]
>>inb4 i ded

>not an argument yet i didnt die from .38

you cant fool me i saw the .38 murderbone last night

**Comment by CitrusGender** [comment]
you'd be stunned too if you got shot by a gun

**Comment by zamolxius** [comment]
G R U D G E C O D I N G

**Comment by optimumtact** [comment]
remove the stun/stam damage completely and make it 4-5 shots to crit again.

**Comment by Bawhoppen** [comment]
This is the exact type of change that's going to be continuously fought over. Expect a revert to original functionality PR in 2-6 months.

**Comment by Kagus** [comment]
.38 Bullets should deal no damage, but instead inflict increasing levels of nicotine dependency in the target.

Should also make the candycorn fedora require a powercell, shit's OP as fuck.

**Comment by kevinz000** [comment]
:-1: Not because I don't think it's bullshit OP (It really is IMO) but because stam damage is arguably even more lethal. Stun's stun but two-three hits will fuck someone up to the point of being unable to move at any good speed at all.

**Comment by Dorsisdwarf** [comment]
👎perfectly balanced, as all things should be👍

**Comment by Bawhoppen** [comment]
Another idea is make it knock you down for like 1/4 of a second, while mainly doing damage

**Comment by optimumtact** [comment]
remove the stun/stam damage completely and make it 4-5 shots to crit again.

@Tlaltecuhtli

**Comment by FrostyFridge** [comment]
i
ded

**Comment by OmegaShoots** [comment]
Look mom I merged it.

**Comment by ElPresidentePoole** [comment]
@optimumtact is looking out for us det mains

**Pull request merged**
