### PR TITLE
UNIQUE_RENAME storage no longer blocks pens

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request
I was making a PR that allowed renaming pill bottles with pens using the UNIQUE_RENAME flag. Renaming a storage item didn't work when the storage was full because the pen was trying to store itself instead. 

This gives pens a toggle. The pen will only try to store inside UNIQUE_RENAME storage when off.  This doesn't affect storage without the flag.

This means pen won't write unless toggled on with attack_self() or the action button this PR adds. The sleepy pen needs to be on to inject reagents. The charcoal stylus can't be toggled and always writes. The energy dagger still uses attack_self() to activate and the action button toggles writing. The four colour pen cycles through being off and its colours when toggled.

Ctrl+Shift click now changes pen head rotation instead of attack_self(). Pen descriptions now reflect this. This means that pens that override attack_self() can be uplinks too.

This PR also includes and closes #54755 as I made these together and they touch the same code. It also moves definitions and procs in pen.dm so they are ordered by object. This makes it harder to miss things.

## Why It's Good For The Game

Items with storage datums can use UNIQUE_RENAME without issues. You can click pens. Every pen can have its head rotated and be an uplink now. 

## Changelog
:cl: cacogen
fix: Pens can now rename storage with the UNIQUE_RENAME flag when it's full. They won't try to store themselves instead.
tweak: Pens now need toggling on to write or inject. Toggle them in-hand or with their new action button. Edaggers still activate in-hand and use the action button to toggle writing.
tweak: Moved pen head rotate from attack_self() to Ctrl+Shift click (listed on examine). Any pen could potentially be made an uplink now. 
soundadd: penclick.ogg
/:cl:

### CODE REVIEW

**Comment by Maurukas** [comment]
A couple nights ago, someone gave the AI a law that wearing satchels and backpacks caused human harm. Thinking quickly, I grabbed my pen and attempted to rename my satchel to 'dufflebag', a type of storage which did not cause human harm, but found I was unable to do so. I had to make use of the much less convincing hand labeler.

This fix could save someone's life.

**Comment by cacogen** [comment]
I hate to say it, but the duffelbag would've had to have the UNIQUE_RENAME flag (like drinks, food and produce) to be affected by this. I don't know of any storage that does at the moment.

**Comment by cacogen** [comment]
Maintainers, will my PR be merged?

**Comment by cacogen** [comment]
itty bitty chaquita cajones
I moved things around so that proc definitions were directly beneath the objects they belonged to not realising it would fuck with the diffs I will remake without doing that

**Comment by LemonInTheDark** [comment]
wholesome

**Pull request closed without merging**
