### PR TITLE
Remove shocker circuit

### PR DESCRIPTION
**Pull request by optimumtact**
:cl: oranges
del: Removed the shocker circuit
/:cl:

It's a little bit too overpowered

### CODE REVIEW

**Comment by Armhulen** [comment]
thanks

**Comment by evsey9** [comment]
Keep it in for drones

**Comment by Armhulen** [comment]
no.

**Comment by ninjanomnom** [comment]
Don't forget a changelog

**Comment by evsey9** [comment]
Oh well, I can still make SHEER HEART ATTACK.

**Comment by Magikarpet** [comment]
>remove stun gloves
>readd machine stungloves
What were they thinking?

**Comment by evsey9** [comment]
i'll take this over removing circuits fully

**Comment by JJRcop** [comment]
Don't tell @JJRcop but I prefer this PR over his. 🤐

**Comment by jughu** [comment]
something tesla module denying power cost roundstart making shocker incredibly strong and infinite

**Comment by Grazyn** [comment]
>readd machine stungloves

what kind of man builds a machine to ~~kill~~ stun a catgirl?

**Comment by Noahnoah55** [comment]
What if we just made it take a shitton of power and nerf the tesla module's range to 1 or 2 tiles.

**Comment by kevinz000** [comment]
i don't want it to go but it's op as fuck hoping i can rework how it works without a hard stun that is invis and all that in the future =|

**Comment by davethwave** [comment]
A better idea is to just make it require a head/sec ID to activate the circuit instead of removing it as well as make it so it can shock only so many times in a minute or something like that, or making the circuit unprintable but making 2 or 3 of the shocker circuits instead spawn in the armory so they can be monitored as well as taken care of so as to not allow getto stun items evolve to something ridiculous(improve do not remove)

**Comment by Qbopper** [comment]
@Grazyn a protopost in a github pr, well done

**Comment by Spaceinaba** [comment]
or give it a semilong cooldown

**Comment by Iamgoofball** [comment]
@optimumtact I was gonna put this into a traitor item, do you mind if I do that

**Review by ninjanomnom — APPROVED** [review]

**Comment by Buggy123** [comment]
but muh hubris

**Comment by davethwave** [comment]
It would have just been great if they just spawned in a limited amount or they were traitor items only scientists/roboticists can have instead of just removing them...

**Pull request merged**
