### PR TITLE
Removes security HUD from cyborgs

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Hopefully a smaller nudge towards "AI isn't part of security" than removing it/removing borg types/changing up the laws. Security cyborgs should be arresting people based on its laws, not based on whether they've done random petty crime.

### CODE REVIEW

**Comment by Xhuis** [comment]
That's a poor argument for removing it from security cyborgs. One could argue that Law 2 compels them to assist the security force, assuming they're ordered to. Security cyborgs should at least keep it - if they see someone wanted, they can query whether or not if they've caused harm, for instance.

**Comment by xxalpha** [comment]
This removes it from the AI as well?

**Comment by PKPenguin321** [comment]
:+1:

**Comment by GunHog** [comment]
I do not support this at all. :-1: 

However, I know that I will be ignored otherwise, so I shall state that you are doing this incorrectly; It will also remove the HUD from the AI, which is only a _job icon_ HUD. A "proper" way to proceed with this change would be to rename the HUD to "Identity" or something and set borgs to the AI's job-only version. There is no need to remove it entirely.

**Comment by KorPhaeron** [comment]
That would also be okay. My main issue was with the loyalty implants+wanted status

**Comment by Dorsisdwarf** [comment]
:+1: 
Why do silicons need to know ranks if we have them on asimov?

**Comment by Jazaen** [comment]
Yes, because no one has ever uploaded a lawset other than asimov, no sir.
Change into identity hud seems fine though.

**Comment by tkdrg** [comment]
Conficts.

**Comment by Cheimon** [comment]
I can see the point of this, but removing it entirely seems drastic.  There are many situations where it is helpful for a silicon to access the sechud: if it is subverted in a revolution or gang situation, if it is given a lawset for which the hud is relevant, or if it simply wants to be able to identify someone it already needs to stop faster (a known murderer set to wanted, for example).  

For that reason, some way of re-enabling the HUD, like an upgrade board, would make this much more reasonable.

**Pull request closed without merging**
