### PR TITLE
Welding mask toggling while buckeled fix

### LINKED ISSUE #9071: you can't toggle a welding gas mask while buckeled to a chair
I was not cuffed at the time. seems weird.

### PR DESCRIPTION
**Pull request by kingofkosmos**
Welding mask can now be pushed while buckled to a chair.
Also found a similar instance with the tape recorder and fixed it as well.

Fixes #9071

### CODE REVIEW

**Comment by Thunder12345** [comment]
I think you meant to say buckeleled there.

**Comment by phil235** [comment]
:+1:

**Comment by Boggart** [comment]
Could you fix the sprayer tank problem too? (If not, it's fine. I can open an issue for it.)

**Comment by kingofkosmos** [comment]
Sure, I'll see if I can fix it.

**Comment by kingofkosmos** [comment]
Alright, all done, tested properly and ready to merge. I'm guessing there's LOADS of the similar case of this bug (https://github.com/tgstation/-tg-station/search?p=4&q=restrained+canmove&utf8=%E2%9C%93) but I'm not competent enough to start fixing all of them, just the major ones for now.

**Pull request merged**
