### PR TITLE
Smooths CentComm walls

### PR DESCRIPTION
**Pull request by Thunder12345**
pizza construct 92 2017-01-21 150117

:cl: Thunder12345
add: The indestructible walls on CentComm will now smooth.
/:cl:

### CODE REVIEW

**Comment by lzimann** [comment]
seems like an unnecessary resource usage

**Comment by coiax** [comment]
lzimann, stop being so unfun. I bet if we invoke @MrStonedOne he'll tell us that smoothing only uses resources on the smoothing step and then that's it.

**Comment by lzimann** [comment]
it's not even unfun, it's just that anything related to centcomm zlevel changes are pretty much useless

**Comment by Kromgar** [comment]
It just requires a few master sculpting dwarfs/assisstants to spend some time on it

**Comment by Thunder12345** [comment]
\>Wasting your master engraver's time on smoothing that half a dozen novice masons can do to gain experience

**Comment by Kromgar** [comment]
Master engravers work for centcomm... how else do you think they get indestructible walls?

**Comment by Thunder12345** [comment]
Slade

**Comment by RemieRichards** [comment]
did you use the tool for this? or did you smooth it by hand? considering it's a perfectly square icon the tool would have done it really well.

**Comment by Thunder12345** [comment]
Yup

**Comment by RemieRichards** [comment]
>asks a question that requires more than yes or no
>"Yup"

aaaaaaaaaaaaaahhhhhhhhhhh

**Comment by Thunder12345** [comment]
Used the tool

**Comment by RemieRichards** [comment]
good, I couldn't quite tell from the picture because the pattern, while square, is a bit complex, really happy with how the tool handled it though.

**Pull request merged**
