### PR TITLE
Changes Bone Armor/Bracer Graphics

### PR DESCRIPTION
**Pull request by TehZombehz**
As the title says. 
barmfull
In order from the left:
Side view of bone armor w/o bracer, Front View w/ bracer, Side view w/ bracer, Back view w/ bracer, Front view w/ bracer (lizard, makes seeing colors easier), Armor item, Bracer item.
Willing to make additional changes.
UPDATE: Red thing on north facing removed/changed. Images:
bbracernorthnew
Changed the item graphic to also reflect the change (And make the bracer look thicker, it kind of should)
bbracernew

### CODE REVIEW

**Comment by KazeEspada** [comment]
WHERES MUH MAN THONG?

**Comment by TechnoAlchemisto** [comment]
nice nice good improvement

**Comment by Cheridan** [comment]
The red line on the north-facing sprite still looks weird to me

**Comment by TehZombehz** [comment]
@Cheridan the red line is something I kept from the original sprite. I suppose it's supposed to be some kind of sinew binding to hold the bracers in place? If you'd like, I can change that.

**Comment by KorPhaeron** [comment]
I agree on the red bit looking weird

**Comment by Iamgoofball** [comment]
shoulder pads need spikes tbh

**Comment by TechnoAlchemisto** [comment]
The shoulder pads are spikes

**Pull request merged**
