### PR TITLE
Degoons the punching bags.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

This replaces the punching bag sprites with ones that aren't from Goon.

Screenshot_270

This also adds in a non-Goon fitness.dmi, which could be used in the future for exercise equipment additions or resprites.

The punching bag sprites originally came from this pull request on Bay, with some edits by myself to make it fit more with /tg/'s spriting direction:

https://github.com/Baystation12/Baystation12/pull/18044

I'm not sure who drew the sprites originally, it was either AtomicWorm, or the anonymous person who he credited as helping out with the spritework on the PR.

## Why It's Good For The Game

The less Goon stuff, the better.

## Changelog

:cl: sergeirocks100, AtomicWorm, some anonymous guy
imageadd: The punching bag has been resprited.
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
> You currently have a negative Fix/Feature pull request delta of -21. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

how the f-

**Comment by san7890** [comment]
Delete goon/icons/obj/fitness.dmi as well?

**Comment by sergeirocks100** [comment]
> Delete goon/icons/obj/fitness.dmi as well?

The sprites for the weight lifting machines are still there, so i can't delete it.

**Comment by Tastyfish** [comment]
> > Delete goon/icons/obj/fitness.dmi as well?
> 
> The sprites for the weight lifting machines are still there, so i can't delete it.

I'm working on new sprites for the weight lifting machines, so soon, maybe.

**Review by JohnFulpWillard — CHANGES_REQUESTED** [review]
please credit the original creator of the sprite in the changelog.

**Comment by Twaticus** [comment]
dont like it, i'll live with goon for a little while longer

**Pull request closed without merging**
