### PR TITLE
Removes hull integrity as a payout factor for engineering

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request

This removes the hull integrity check system from economy.dm

image

## Why It's Good For The Game

image

image

 - This change reduces lag and tames some of the rampant resource usage that economy.dm has.

  - This change also opens the door to a new, more effective and less resource-intensive way to evaluate whether or not engineering is doing a good job and deserves money.

  - In the meantime engineers might get paid slightly more than usual.

## Changelog
:cl:
del: Removed hull integrity system from economy.dm Should reduce periodic lag.
/:cl:

FUTURE:
  - Obviously engineering needs a new way to make money
  - Civillians don't even have a way to increase their income???
  - Medical, Security, and Service are all lumped together???

### CODE REVIEW

**Comment by optimumtact** [comment]
oh my god what have you done to your system fonts

**Comment by RaveRadbury** [comment]
> oh my god what have you done to your system fonts

Literally nothing??

**Comment by ExcessiveUseOfCobblestone** [comment]
didn't know windows98 could run discord

**Comment by RaveRadbury** [comment]
_The Unbearable Lightness of Being Roasted_

**Review by optimumtact — APPROVED** [review]

**Comment by Ziiro** [comment]
Base their income on power generation so the engineers that furiously masturbate to the mw output are rewarded or something

**Comment by PKPenguin321** [comment]
\>put 3 paper bins worth of paper around the SM
\>get 9999999 credits every 5 minutes in addition to generating 9 * 10^9999 gigawatts per second because paper defies thermodynamics

Good idea

**Comment by FloranOtten** [comment]
> >put 3 paper bins worth of paper around the SM
> >get 9999999 credits every 5 minutes in addition to generating 9 * 10^9999 gigawatts per second because paper defies thermodynamics
> 
> Good idea

Do paper bins generate more than bluespace rpeds/lightbulb boxes?

**Comment by optimumtact** [comment]
I just realisedt his probably pays out way more than it's supposed to, can you pls make sure it has a sane amount

**Comment by RaveRadbury** [comment]
@optimumtact 
`	var/engineering_cash = 3000
	engineering_check.count()
	var/station_integrity = min(PERCENT(GLOB.start_state.score(engineering_check)), 100)
	station_integrity *= 0.01
	engineering_cash *= station_integrity`
So it's 3000*station_integrity%. As you pointed out, integrity never gets that low before shuttle is called, so I figured that 90% is just as good as 100% in that regard? It's not like there was a major factor that reduced the 3000, it was just being multiplied by integrity as a percentage.

**Comment by optimumtact** [comment]
k, sounds good

**Pull request merged**
