### PR TITLE
Xenomorph changes and features

### PR DESCRIPTION
**Pull request by GunHog**
The following changes to Xenos are created on behalf of @WJohn!

:cl:
Name: WJohnston & Gun Hog
rscadd: Aliens may now force open unbolted, unwelded airlocks. Unpowered airlocks open faster than powered ones. Has a cool sound provided by @Ultimate-Chimera!
tweak: Alien Drone health increased to 125 hp.
tweak: Alien drone is now faster!
tweak: Alien egg and larva maturation times halved.
tweak: Resin membrane health increased to 160 hp.
rscadd: Aliens may now open firelocks.
rscadd: Aliens may now unweld scrubbers and vents. (From the outside!)
tweak: Droppers no longer affect aliens.
/:cl:
- [x] Prevent lasers travelling through membranes
- [x] Prevent droppers affecting xenos (they do not have eyes!)

~~Make xeno spit targeted using clicks~~

### CODE REVIEW

**Comment by Supermichael777** [comment]
REEEEEE! :+1:

**Comment by GunHog** [comment]
> Can you make alien embryo grow 2-3 times slower in dead bodies? So the aliens would actually have a reason to keep hosts alive.

If WJ wills it, sure, I can look into how that code works and adjust accordingly.

**Comment by WJohn** [comment]
<3

Also yeah I suppose longer maturation times to keep hosts alive is a nice idea, gives the humans a few more chances to escape or cause damage.

**Comment by lzimann** [comment]
>Can you make alien embryo grow 2-3 times slower in dead bodies? So the aliens would actually have a reason to keep hosts alive.

Isn't it already like this?

**Comment by GunHog** [comment]
https://github.com/tgstation/-tg-station/blob/8cd8d259eeb8d6af23a08a0de8c085e2a7b4b809/code/modules/mob/living/carbon/alien/special/alien_embryo.dm#L53

**Comment by WJohn** [comment]
Also, to make drones more appealing, their speed should be increased to base human movement, like sentinels got.
All my other suggestions are here: https://github.com/tgstation/-tg-station/pull/15886#issuecomment-202168686

**Comment by RemieRichards** [comment]
Have suicide corpses not count for the extra delay, because you just KNOW people WILL do that, not might, <I>WILL</I>

**Comment by Dorsisdwarf** [comment]
Make suiciding / ghosting with a babby disable your alien chances too for the round.

**Comment by Robustin** [comment]
Reduce egg maturation times too.

It's another needless speed bump for Xeno growth.

**Comment by GunHog** [comment]
The egg timer has been halfed, this is already in the original commit. In the next commit, I am halfing larva's maturation goal from 200 to 100. Please note that biting people does increase growth as well, so do consider getting out and nomming on things.

Drones are also getting a speed buff as well. I have these two changes saved, but in the interest of keeping a maintainer from forcing me to do a "rebase", I am uploading my commits in batches.

One more thing: @WJohn I am not sure changing chestburster growth inside a dead host is such a good idea. Checking for both suicide AND ghosting seems excessive and problematic, but that decision is up to you.

**Comment by KorPhaeron** [comment]
You can't suicide while restrained anyway

**Comment by WJohn** [comment]
I thought about it some more, and yeah there really aren't enough incentives to actually keep a host alive. There are so many benefits given by exposing things to space and even directly killing hosts, that slightly less longer human burst times when dead doesn't really fit with what we have now. I say we leave it as-is for now.

**Comment by Ultimate-Chimera** [comment]
:+1: merge when?

**Comment by GunHog** [comment]
I have to finish it first. My efforts to integrate click-based aiming for xeno spit (and fireball spell) were unsuccessful, so I will have to leave that out for now, and work on the other bits.

**Comment by Ultimate-Chimera** [comment]
@GunHog You can fix the door prying with this, change the cooldown with sleep if you feel the need for it. This is from citadel station. http://pastebin.com/X2x6jMyQ

**Comment by Ultimate-Chimera** [comment]
Also don't forget to add this. https://dl.dropboxusercontent.com/u/211463060/ShareX/2016/04/airlockforced_alien.ogg

**Comment by GunHog** [comment]
I already made code for the airlocks, but it does contain reminders for things (shocking etc) that I will be sure to add and test. That sound is awesomesauce, and I shall use it as well. New commit shortly. I will deal with the merge conflict later.

**Comment by GunHog** [comment]
Added more stuffs. @WJohn please provide feedback when you can! Some of the things I did not get around to doing yet, they are in the OP.

**Comment by Ultimate-Chimera** [comment]
:+1: :+1: :+1:

**Comment by GunHog** [comment]
Merge conflict? AGAIN? Seriously!? In the same file, where a conflict did not ACTUALLY exist. Ugh. Fixed again. Still waiting for @WJohn to reply.

**Comment by Ultimate-Chimera** [comment]
WJohn.exe is not responding.

**Comment by WJohn** [comment]
I can vanish at random, sorry, my home internet problem is still gonna persist for a couple more weeks.

Huge :+1:  to these changes. I prefer giving xenos more utility and flanking potential rather than just raw number buffs.

**Comment by GunHog** [comment]
Final changes added. **WARNING: Droppers have been nerfed such that they only work on human mobs.**

**Comment by Core0verload** [comment]
Add monkeys to the dropper. They have eyes too.

**Comment by WJohn** [comment]
I don't mind whether or not you can use droppers on monkeys, that's such an outlandish use that I doubt anyone would miss it.

**Comment by KorPhaeron** [comment]
Whats wrong with using droppers on xenomorphs?

Should be at least one way to capture them, and trying to melee a xenomorph is already very risky

**Comment by PKPenguin321** [comment]
yeah, undo the dropper change

**Comment by Core0verload** [comment]
Gas/foam grenades? It's already better than trying to use dropper on the alien.

**Comment by WJohn** [comment]
The dropper change was made because xenos do not have eyes and it bypasses the Queen's syringe immunity. With neurotoxin from the bar being an instant knockdown, this is not okay.

**Comment by KorPhaeron** [comment]
If someone can get into the heart of the hive, avoiding all the facehuggers/neurotox projectiles/pounces/aoe tail attacks and then land their melee hit before any alien hits them, then somehow drag the queen back out, is that the worst thing in the world?

**Comment by KorPhaeron** [comment]
I guess if aliens have no eyes that makes sense though

**Comment by PKPenguin321** [comment]
>muh realism
>muh xenos have a weakness!! remove!!

in terms of the game itself, if somebody actually manages to pull of neurotoxining a xeno with a melee range eye dropper, that would be hype and make a great story. i dont see the problem

**Comment by GunHog** [comment]
@WJohn, what do you want me to do here?

**Comment by KorPhaeron** [comment]
Alight so as to the rest of the changes:

Other than the aliens growing faster, all the changes are offense oriented/aimed at letting aliens break into places more easily.

I think this is a mistake/poor direction to go in. Aliens don't have any trouble going on the offensive. Once they're on the offensive they usually win. Aliens suffer when the station is kicking down the hive door down when they only have like 2 aliens and a larva.

And not only are you buffing the wrong stage of the alien game (when they're already winning), by making it harder to defend/fortify against them, you're just making it more attractive to call the shuttle (aliens are even harder to defend against, so why bother?)

All that being said this all just suggestions, because I don't actually care enough about xenomorph balance (sorry WJ!) to not just merge this eventually.

**Comment by Ultimate-Chimera** [comment]
@KorPhaeron But xenos should be able to open airlocks anyways. They can easily get trapped in rooms with no vents, no way they can escape, etc.

**Comment by WJohn** [comment]
Queens don't have too much trouble on defense if they are even slightly competent. Perhaps that could be improved by giving hints and tips on what to do whenever you evolve to the next stage. Blobs for example have this which is pretty useful for teaching hotkeys. If it outlined some basic key strategies I think we could make the defense consistently better, but that is for a different PR.

Also one-shotting the Queen is bullshit no matter what. It was the same shit with syringe guns and people brought up the same dumb "you deserve that kill" argument. One-shotting an unstunnable 400 HP monster is not okay, unless perhaps by bombs.

**Comment by GunHog** [comment]
New change: Dropper nerf mostly reverted, xenos are still immune to them, however.

**Comment by PKPenguin321** [comment]
that is dumb

**Comment by Dorsisdwarf** [comment]
Only aliens with acid spit should be able to unweld vents

**Pull request merged**
