### PR TITLE
Fixes #9035, atmos locker sprite and misc logging bug

### LINKED ISSUE #9035: Can't open lockers unless your hand is empty
I think with the recent fix to lockers it removed the ability to open lockers with a full hand. Don't know if this is intended.

### PR DESCRIPTION
**Pull request by Jordie0608**
Fixes #9035

All carbon and silicon mobs can use "Toggle Open" on closets; with the exception of borgs they all could already open them, borgs can now do so too.

Fixes atmos secure closet using atmos wardrobe door sprite.

Fixes thunderdome reset logging as user as null when user was one of the mobs deleted.

### CODE REVIEW

**Comment by Jordie0608** [comment]
I pushed to upstream accidentally before making this pr from origin and now travis is having a hissyfit. ¯\_(ツ)_/¯

**Comment by RemieRichards** [comment]
>doesrussellsteapotapplytorussellsteapot

no.

**Comment by Boggart** [comment]
Heh, I just did the exact fix you did on line 245 and was going to make a pull request. Good thing I did a search for locker PRs before I did.

**Comment by Jordie0608** [comment]
@tgstation/commit-access

**Comment by Shad0vvs** [comment]
"All carbon and silicon mobs can use "Toggle Open" on closets; with the exception of borgs they all could already open them, borgs can now do so too."

I'm confused because you can't open a locker when something is in your hand (how borgs used to open lockers) and you can't toggle open as it says "this mob cannot use var" or something similar. 

So borgs still cannot open lockers.

**Comment by Boggart** [comment]
There's a verb for it, also he's fixed the check so that non-secure lockers will open when an item is used on them like they used to.

**Comment by Shad0vvs** [comment]
I tried today and couldn't open a locker with the verb or with an item held as an engie borg. Ill see if its ever reproduced, maybe it was welded and I didn't see or something.

**Comment by Boggart** [comment]
Do you mean on a local server with the fork from this PR compiled? Because this hasn't been merged yet.

**Comment by Shad0vvs** [comment]
Confusing, the verb is added but this isn't merged? Guessing toggle open was added at a different point, if so then disregard.

**Comment by Jordie0608** [comment]
The verb already exists.

**Pull request merged**
