### PR TITLE
Removes AsteroidStation from Travis [speed merge] 

### PR DESCRIPTION
**Pull request by CorruptComputer**
Something broke when it got merged, but I won't be at a computer for at least a week, so it's not possible for me to fix right now. If someone else wants to go ahead.

### CODE REVIEW

**Comment by Razharas** [comment]
What exactly broke?

**Comment by CorruptComputer** [comment]
No idea, but Travis is failing if you look at the readme.

**Comment by CorruptComputer** [comment]
https://goo.gl/photos/d9nxS4KSYCKedEk3A

It seems that something with the path of secure closets was changed.

**Comment by CorruptComputer** [comment]
Ok well it seems that it is still failing, so someone else fucked up.

**Comment by CorruptComputer** [comment]
https://travis-ci.org/tgstation/-tg-station/jobs/69588228#L311

**Comment by optimumtact** [comment]
raz merged a borked changelog file

**Comment by CorruptComputer** [comment]
Would it be possible to get Travis to re test all PR's when something gets merged? Because I have played around with it a little bit and you can set it to build 100 things at a time, so it would only take 5 mins at most.

**Pull request merged**
