### PR TITLE
Updated implant action buttons

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: tacos taste good
tweak: changed the implant action button sprites
/:cl:

it is listed as something to resprite so i tried. 

**new sprites**
new sprites

**old sprites**
old

I redid the freedom, emp and adrenaline buttons. I added flames/detail to the explosive button. I changed some wonky pixels on the pill button.

**I know they aren't perfect, but I think they are significantly better than the old ones. Unless someone else comes along with drastically better sprites, there's no reason this shouldn't be merged.**

### CODE REVIEW

**Comment by Cyberboss** [comment]
@WJohn 

Also, freeze

**Comment by GunHog** [comment]
Sprite changes are exempt from the freeze.

**Comment by Tacolizard** [comment]
feature freeze = _**feature**_ freeze

**Comment by KorPhaeron** [comment]
I dont think they are better enough to be worth the confusion of changing them personally but it is up to Wj

**Comment by Tacolizard** [comment]
@KorPhaeron I can live with all the old sprites but the pill. Whoever made it fucked up and it wasn't symmetrical and it really bugs me.

**Comment by ChangelingRain** [comment]
These just aren't that much of an improvement sorry dude

**Pull request closed without merging**
