### PR TITLE
Departmental Security Option #2: Remove Depsec Entirely

### PR DESCRIPTION
**Pull request by Iamgoofball**
https://hackmd.io/@Dsm-BOZJQquXV0Z7ShxJQg/rkwa_htDY
## About The Pull Request

Removes Departmental Security from the game.

## Why It's Good For The Game

See the attached design document.

## Changelog
:cl:
del: Removed Departmental Security from the game.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Only serves to reinforce the image of security being its own entity 👎

**Comment by Ghilker** [comment]
but sec is its own entity, just like every other department

**Comment by Mothblocks** [comment]
:-1: Not OK'ing this one, basically none of the paths talked about in maintainerbus led to this

**Comment by Iamgoofball** [comment]
I wanted it available as an option because if we don't take Option 1 or Option 3, this is what we will be doing.

**Comment by Iamgoofball** [comment]
Additionally, this should still be on the table if Option 1 or Option 3 don't work out.

**Comment by Mothblocks** [comment]
If we want it then you can PR it then

**Pull request closed without merging**
