### PR TITLE
fixes point experiments not scanning anything

### PR DESCRIPTION
**Pull request by Bilbo367**
## About The Pull Request

Fixes point experiments so they can work again. Point experiments like scan 6 points, medical kiosk 2 points, etc etc Would not let you scan its machines like medical kiosk. This allows you to scan the things it wants, Instead of saying everything is not a machine relevant to the experiment.

## Why It's Good For The Game

They weren't letting you scan anything and this fixes that.

## Changelog

:cl:
fix: scanning point experiments now work again
/:cl:

### CODE REVIEW

**Review by 00-Steven — COMMENTED** [review]
I believe you need to have a specific stock part for most of the point-based machinery experiments to work, and otherwise it denotes it's not relevant to the experiment.

This pr seems to just be removing the part where point experiments do its final checks, `final_contributing_index_checks`, which is where the machinery experiments inheriting it check for the right parts.

If you still think there's an issue, could you be more detailed in how to reproduce it? Because I think just removing that check is not a good idea.

**Comment by Bilbo367** [comment]
Whoopsies

**Comment by 00-Steven** [comment]
o7
Honestly it's probably a good idea to look into making it give useful message at some point.
I _believe_ right now it uses the same "not relevant" message for _any_ error, which can be confusing when that even includes something already having been scanned or just missing a part.

**Comment by Bilbo367** [comment]
> o7 Honestly it's probably a good idea to look into making it give useful message at some point. I _believe_ right now it uses the same "not relevant" message for _any_ error, which can be confusing when that even includes something already having been scanned or just missing a part.

Yeah I think i might code this in tomorrow, and maybe add some more comments to the experi code cause its pretty hard to navigate.

**Pull request closed without merging**
