### PR TITLE
Adds a togglable border while in combat mode

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request

https://user-images.githubusercontent.com/35135081/125179532-b22acb80-e1a3-11eb-8f72-8e806a9a8430.mp4

Key decisions:
1. Several colors were tried--yellow, blue, and red. Red is hard to see with the blood overlays, blue is hard to see without them. Yellow might seem a bit jarring, but it's the clearest one of them all.
2. The ultimate goal is to be noticeable in your peripheral vision *without* blending into the background (which is why it is animated), but also not being distracting enough to make combat more mentally taxing. I tried the way it is now for a bit, and this one seems to match all of those.
3. It is a preference, as the ultimate goal is to help *you*--if you're able to distinguish between combat mode and non-combat mode easily, then you don't need this, especially if you find it distracting. Don't worry, Mothblocks gave me permission to let this through the preferences freeze.
4. The alpha itself was chosen after trying several different options, most being too hard to distinguish either with/without other overlays.

## Why It's Good For The Game
It's currently very hard to tell if you're in combat mode unless you glance your eyes to the minor UI element and focus away from the combat. This is problematic when combat mode is crucially important to so many interactions. 

## Changelog
:cl:
qol: Added a border while in combat mode to help make it easier to know when you have it on without having to dart your eyes. If you find it distracting, you can toggle it in OOC preferences under "Toggle Combat Mode Vignette", but give it a fair shake first if you have problems distinguishing.
/:cl:

### CODE REVIEW

**Comment by AndroidMK2** [comment]
It would be neat to be able to select other colors of it like red or blue for those who use different styled action boxes (I mean the item slots and action buttons like throw and drop but I forgot how it's called).

**Comment by Mothblocks** [comment]
I wouldn't be opposed to customizable colors (except for the sake of old preferences code being really bad), but of the colors we tried, most just patently suck.

**Comment by JJRcop** [comment]
>     3\. Don't worry, Mothblocks gave me permission to let this through the preferences freeze.

Something's wrong here

**Comment by Mothblocks** [comment]
im not wrong

**Comment by optimumtact** [comment]
>toggleable

Coward

**Comment by Mothblocks** [comment]
> also why animated? looks like shit, just do a static hazard border

> The ultimate goal is to be noticeable in your peripheral vision without blending into the background (**which is why it is animated**), but also not being distracting enough to make combat more mentally taxing. I tried the way it is now for a bit, and this one seems to match all of those.

Static tends to blend in.

**Comment by Twaticus** [comment]
pulsing hazard maybe? this does look especially awkward

**Comment by Twaticus** [comment]
ok hear me out... one of these in the corner but with text that says something about harm intent etc
https://user-images.githubusercontent.com/46540570/125230670-4762b880-e2a7-11eb-9427-053f14e5169f.mp4

**Comment by Mothblocks** [comment]
I'm really not sure that's much different than the UI button we have now, that you already have to glance your eyes over to see.

**Comment by Mothblocks** [comment]
I can try something pulsing but I'm not confident it'll be less distracting.

**Comment by MrDoomBringer** [comment]
Make it a full border that pulses or something. Moving my eyes around to look for the animated yellow slugs crawling around my screen sounds awful for combat.

That, or just make the 'combat' button sprite bright red so I can easily see the color from my peripheral vision.

**Comment by Krysonism** [comment]
I don't think this looks good. The yellow colour is unpleasant and the animation feels intrusive even if it relegated to the screen border.

I appreciate you making it a preference, but i think other options should be explored first, i think twaticus and mrdoombringer had some good ideas.

Another option could be switching the entire hud to a dedicated combat mode hud theme.

**Comment by Mothblocks** [comment]
> Another option could be switching the entire hud to a dedicated combat mode hud theme.

I actually tried this ~a week after combat mode was merged with Floyd in a call, we switched it to the Syndicate theme on a toggle--it doesn't really look better than this.

I'm trying to get a pulsing border to work, but considering most of the border of our screen is *already* taken by UI, there's no way to do it that's obviously visible.

**Comment by optimumtact** [comment]
image

**Comment by Mothblocks** [comment]
Will look into something later.

**Comment by EricZilla** [comment]
I dunno if anyone said anything along these lines yet, but what about a cursor change? In combat mode its a reticle or something along those lines.

**Pull request closed without merging**
