### PR TITLE
Fixes ability to extract DNA of species that has no DNA

### PR DESCRIPTION
**Pull request by Colovorat**
## About The Pull Request

death rant. You can extract dna of plasmemes, golems, and more, and you can also TRANSFORM golems and androids(WHICH HAS NO DNA) into other species. It's literally consistency issue. if specie has no dna, you shouldn't be able to extract DNA of that specie and transorm it too

## Why It's Good For The Game

Extract glass golem DNA, inject someone, they instantly turn into glass golem, hit 3 times, they are round deleted. Funny, isn't it?

## Changelog

Is it balance change? Yes. But i consider it a fix, because it shouldn't be available at first point

:cl: Colovorat
fix: You can no longer extract and transform DNA of species that have no DNA
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
plasmamen seems like an odd choice because they can roll lings themselves iirc

**Comment by Colovorat** [comment]
> plasmamen seems like an odd choice because they can roll lings themselves iirc

Well, they couldn't be sting by transformation sting, why would they be able to extract dna? As for Plasmemes lings, need to think on it. Maybe use backup human if plasmeme roll ling

**Comment by SgtHunk** [comment]
Wouldn't the real solution be to add the trait that stops you from transstinging someone into a dangerous species (like plasmaman)?

**Comment by Colovorat** [comment]
> Wouldn't the real solution be to add the trait that stops you from transstinging someone into a dangerous species (like plasmaman)?

How would you get the gene of dangerous specie, if it has no genes

**Comment by MrMelbert** [comment]
> 
> 
> Wouldn't the real solution be to add the trait that stops you from transstinging someone into a dangerous species (like plasmaman)?

`NOTRANSSTING` already does this

**Comment by Livrah** [comment]
ID of Ided round: 170782

**Review by Kylerace — CHANGES_REQUESTED** [review]
dont exclude a roundstart race, others are good though

**Comment by Colovorat** [comment]
> dont exclude a roundstart race, others are good though

Fine, with being turned into plasmeme you can somehow deal at least

**Comment by NanoCats** [comment]
Yeah but turning somebody into a golem is hilarious and you have to go through the effort of actually acquiring a golem to extract from.

Also I tried to sting somebody into a plasmeme once, it didn't let me do it because they were "incompatible" or whatever.

**Comment by Colovorat** [comment]
> Yeah but turning somebody into a golem is hilarious and you have to go through the effort of actually acquiring a golem to extract from.
> 
> Also I tried to sting somebody into a plasmeme once, it didn't let me do it because they were "incompatible" or whatever.

You can't transform anyone into plasmeme i believe, also as i said, turning someone into glass golem killing in 3 hits, and literally round deleting them

**Comment by Redrover1760** [comment]
Ided moment

**Comment by DeadliestDesire** [comment]
Skill Issue Colovorat :D

**Pull request merged**
