### PR TITLE
Fixes plastic golems ventcrawling with items in pockets

### LINKED ISSUE #39966: Plastic golems can vent crawl with items in pockets
Round ID: 93110.

Was a plastic golem. I could vent crawl with items in pockets; but not if I had a backpack or items in hands.

This is probably because regular humans don't get limited ventcrawl very often.

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
fix: Plastic golems can no longer vent crawl with items in their pockets.
/:cl:

Closes: #39966

### CODE REVIEW

**Comment by AnturK** [comment]
From quick glance the R&D fix might not be enough, since it computes time delta from zero.

**Comment by 81Denton** [comment]
You were right, that doesn't fix it. I'll remove it from this PR and leave it to someone who knows what they're doing.

**Comment by AnturK** [comment]
You just need to set the value to world.time at first run, then continue as usual.

**Comment by 81Denton** [comment]
That's easier than I thought. I'll do that in another PR since I'm a bit busy right now.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
