### PR TITLE
Removes lizard mamaries and slightly improves lizard shading.

### PR DESCRIPTION
**Pull request by WJohn**
What it says on the tin. This also slightly improves the details on the lizards by giving them greater contrast, so you can tell they have plates a bit better.

Top is old, bottom is new.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
incoming downthumbs from lizard players

**Comment by KazeEspada** [comment]
with tits, without tits. It doesn't matter.

**Comment by Incoming5643** [comment]
your sprites your call, just make sure you keep that outline consistent.

**Comment by Anonmare** [comment]
F R E E   L I Z   T I T S

**Comment by Jordie0608** [comment]
Pics

**Pull request merged**
