### PR TITLE
Adds the ability to label blood packs.

### PR DESCRIPTION
**Pull request by harmonyn**
16:02   Sweaterkittens  Code the ability to label bags of blood
16:03   Sweaterkittens  either a use in-hand or using a pen on it allows you to either pick from a list of suggestions or type in your own name
16:03   Sweaterkittens  that way empty blood bags that get filled can be labeled properly, as well as bags that are filled with something else

NEVER SAY I DO NOT LISTEN TO THE PEOPLE. This just updates its name, nothing fancy, but has obvious uses for people actually using the things.

GUYS AM I DOING THE FOLLOWING RIGHT:

:cl: bgobandit
rscadd: Blood packs can now be labeled with a pen.
/:cl:

### CODE REVIEW

**Comment by duncathan** [comment]
:+1:

**Comment by CosmicScientist** [comment]
:+1:

**Comment by bgobandit** [comment]
@CosmicScientist not sure what you mean

**Comment by CosmicScientist** [comment]
On this line:
https://github.com/tgstation/-tg-station/pull/13037/files#diff-9994537fa22ac1f1758b9d734aae9549R13
It would read in game as "blood pack [type]"

On your change custom names become "blood pack - [type]"

It's not necessary, I was just wondering if it would be better to make them the same or better to distinguish between spawned and edited.

**Comment by SweaterKittens** [comment]
Yay! Thank you Bandit!

**Comment by Aranclanos** [comment]
I think you can use some canusetopic, but im not sure, take a look.
With your code you can name them while stunned (a huge and important deal)

**Comment by Dorsisdwarf** [comment]
canusetopic controls monky and drone use too, right?

**Comment by Aranclanos** [comment]
it has an argument specilly for that

**Pull request merged**
