### PR TITLE
Makes the admin outfit have a unique sprite.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR makes the Admin Outfit have a unique hardsuit sprite, with the style of a syndicate hardsuit taken over by clockwork technology. Fitting for the admins. This also changes the hardsuit's path to that of the ERT hardsuit, for reasons.

## Why It's Good For The Game

 

also this prevents fikou from murdering me so please merge, i like existance

## Changelog
:cl:
imageadd: The admin hardsuit now looks unique. Be worried about divine retribution in an instant!
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Great opportunity to use some girly station sprites

**Comment by CRITAWAKETS** [comment]
> Great opportunity to use some girly station sprites

first of all, these were made by me for some stuff i might eventually get around to doing

second of all, you take that back or i'll make the captain's hardsuit a megaman armor

**Comment by Pugie** [comment]
just remove it admins should be using janitorial ert hardsuit if any hardsuit.

**Comment by ShibaInuLord** [comment]
clockwork jannie hardsuit when

**Comment by Twaticus** [comment]
looks cool but its unnecessary for something rarely used plus not even obtainable by players

**Pull request closed without merging**
