### PR TITLE
Fixes RnD not being able to make slime processors.

### PR DESCRIPTION
**Pull request by GrayRachnid**
Honk

:cl: 
fix: You can now make the slime processor in the circuit printer.
/:cl:

### CODE REVIEW

**Comment by fludd12** [comment]
I thought the slime processor was just a normal processor after using a screwdriver or something on the board...?

**Comment by GrayRachnid** [comment]
The thing is, RnD still wouldn't be able to make it because the Food Processor can only be made in the Service lathe.

**Comment by fludd12** [comment]
Oooh, a good point! :+1: to this, then.

**Comment by ExcessiveUseOfCobblestone** [comment]
You could always do both, as in give it an examine message AND add the slime processor to CI :^)

**Comment by GrayRachnid** [comment]
The real fix would be to come to a decision whether to split these two completely or merge them together once and for all because each one is designed for a different department and with techwebs splitting departments it makes it confusing.

**Comment by ExcessiveUseOfCobblestone** [comment]
you want to remove the slime processor design, give the food processor design the science dept flag, and then rename/desc the design into a generic "processor" with the desc being screwdrive to select between food or xenobiologics.

**Comment by GrayRachnid** [comment]
I honestly don't see the point of that, why would two machines who belong in two different departments share the same circuit board? I think it's better to just give science the ability to create slime processors rather than complicate it.

**Comment by ExcessiveUseOfCobblestone** [comment]
It's not two machines, it's a singular machine that switches what it processes with a screwdriver on the circuitboard.

If you want to have the absolute division then do that in the code (boo tbh), otherwise make it apparent they're the same thing please. We don't have 5 different smartfridge designs to fit chem/botany/kitchen/science, we have a singular one that can be produced by all with an examine message explaining that it can be screwdrived to change what it can store.

**Comment by ExcessiveUseOfCobblestone** [comment]
@vuonojenmustaturska https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/circuitboards/machine_circuitboards.dm#L351-L362

**Pull request closed without merging**
