### PR TITLE
The Syndicate are taking a break from arching Nanotrasen, and a different villain approaches.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Sprites credit to Admiral Hippie and Gumner.

The syndicate scheduled this April 1st for a vacation day or something, so someone else has to pick up the slack on messing with Nanotrasen.

### CODE REVIEW

**Comment by Jordie0608** [comment]
capture

**Comment by PKPenguin321** [comment]
What in the hell I was literally just watching this show. I finished an episode and came to check github notifications and this was the first thing I saw
What are the ODDS

**Comment by Iamgoofball** [comment]
mapdiff bot killed the map diff image so heres a shittier version
https://file.house/hrGt.png

**Comment by arsserpentarium** [comment]
What is this show?

**Comment by PKPenguin321** [comment]
The Venture Bros

**Pull request closed without merging**
