### PR TITLE
Moves coroner surgery tools to their surgery duffel

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Coroners currently get 2 sets of surgery tools, cruel ones in their medkit, and regular ones in a duffel in their office.
This removes the tools from their kit, and replaces their surgery duffel with a coroner surgery duffel, which has the cruel variants (if it exists), and does not come with a mask (as they spawn with one).

## Why It's Good For The Game

Coroners get 2 sets of surgery tools for a job that only has 1 position, Paramedics would dream of this.
This also removes the inconsistent medkits, 2 of them existing with the same name/icon/etc. but fit different things, is actually quite lame.
I also removed their folder, because they are already given a clipboard AND a filing cabinet.

## Changelog

:cl:
add: Adds the Coroner surgery duffelbag; This replaces Coroner's surgery tools in their medkit and current duffel, and has the cruel surgery tools instead of regular ones.
balance: Cruel surgery tools are no longer premium.
balance: Coroner's medkit is now premium in the vendor.
balance: All Coroner medkits are the same, there is no 'large' variant.
balance: Coroners no longer get a folder.
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
Thank goodness that was a PAIN to do every shift, plus now I can pinpoint who stole my surgery bag, which happens a lot

**Comment by necromanceranne** [comment]
The reason I put them in the coroner's kit was so that nobody pinched them thinking they were just standard tools. While they definitely work as standard tools, they _only_ benefit someone who is morbid. It would be pretty crummy for a coroner to miss out on their special tools just because someone stole them before they arrived/while they weren't looking, and then have to go bother cargo for them.

If we're going to have tools in a surgery duffelbag, they may as well just remain normal tools.

**Comment by JohnFulpWillard** [comment]
They are in the vendor in case they go missing, but I also do not see why someone would steal the coroner's tools instead of getting regular ones from the techfab anyways. If it's stolen, then it would be because there's no other option, which I think would be fine. I don't want them to just have 2 sets of surgery tools, and I think being mapped in is better than them spawning with the full set.

**Comment by necromanceranne** [comment]
I can't really agree with that if only because it isn't a full set, and we don't have that same expectation of medical doctors. They also have full surgery kits in the surgery rooms, but they spawn with at least enough tools to do their job just so they're still able to function in the capacity of the work they signed up for despite given round circumstances. 

Coroner should be much the same to me, especially since the bonuses from those tools are bespoke to them. Those surgery tools really are more important for non-coroners than coroners, and maybe it isn't necessary for them to be around since the two roles that could access it; CMO and roboticists, would have access to their own tools.

**Comment by JohnFulpWillard** [comment]
> They also have full surgery kits in the surgery rooms, but they spawn with at least enough tools to do their job just so they're still able to function in the capacity of the work they signed up for despite given round circumstances.

The difference is that the Coroner is 1 job slot, while Medical Doctors have more than there are surgery duffels.

> Those surgery tools really are more important for non-coroners than coroners

What do you mean by this? Anyone who wants surgery tools can print their owns, why do they need the coroner's?

**Comment by necromanceranne** [comment]
> The difference is that the Coroner is 1 job slot, while Medical Doctors have more than there are surgery duffels.

I don't see how that disproves my point. I'm not talking about round-start spawned coroners, I'm talking about coroners who arrive late. At a baseline, roles have what they need to do the basics. Most jobs that spawn with tools (and tools are their main gameplay loop) also start with the absolute basics to do their thing on their person. Coroner meanwhile would need to either hope their tools are there. Or they have to scrounge from medical itself or pay up to make up for the theft because they can't start their surgeries.

What about coroner overflow? The second guy just gets shafted either way? Most overflows account for this scenario because of the baseline tools. Even chaplains get a fresh null rod in this situation.

> What do you mean by this? Anyone who wants surgery tools can print their owns, why do they need the coroner's?

There may be more than just medical or robotics entering the morgue and think to acquire medical tools for themselves and cannot just print them. And their need may not even be malicious in nature. This scenario is only negative for the coroner who has to arrive late to a lack of their unique tools and work out what to do from there. Deal with having to use the normal versions or again, they have to pay up.

(Also there is the hypothetical scenario where there is more than one role that has the Morbid trait that might be interested in them)

**Comment by JohnFulpWillard** [comment]
> What about coroner overflow? The second guy just gets shafted either way? Most overflows account for this scenario because of the baseline tools. Even chaplains get a fresh null rod in this situation.

That is a unique station trait and we do not have to take it into account. The surgery set is special but it is not a requirement to do your job. Other jobs that have a closet also have this same situation (Atmos Tech, Security Officer).

> There may be more than just medical or robotics entering the morgue and think to acquire medical tools for themselves and cannot just print them.

**Comment by necromanceranne** [comment]
Hows about we meet in the middle somewhere here. What about moving the tools form the vendor's premium to the standard products just so it isn't charging them an arm and a leg to get more if they're stolen.

**Comment by necromanceranne** [comment]
Very cool.

**Comment by TheVekter** [comment]
Honestly, if doctors really want surgery tools and don't want to print them, there's already surgery duffels that spawn in the surgery suite on each map. They should be expected to get those instead, as they already have access to those rooms and not the coroner's office.

**Comment by EricZilla** [comment]
Plenty of doctors have stolen my surgery bag tbh, and the occasional tiding chaplain

**Comment by nintyuk** [comment]
This Breaks Coroner on any map not updated to include these changes and makes late join coroner a nightmare

**Comment by JohnFulpWillard** [comment]
then make a pr including them in the map

**Comment by JohnFulpWillard** [comment]
it's on all maps

image

**Comment by ZephyrTFA** [comment]
why did you wait three months to say this anyway

**Comment by nintyuk** [comment]
Because it only filtered down to the server I play on more recently and I don't play super regularly as I can't always spare 2+ hours to play a round or 2.

**Pull request merged**
