### PR TITLE
Weeb jail updates

### LINKED ISSUE #37717: Weeb jail mapping issues
The jail ninjas put you in has this fun thing where
- There are two beer kegs, but no glasses
- There is a beer cabinet, but it's locked and you can't even smash it

The whole area could use a remodel so it's less hideous and maybe stops people from killing themselves immediately.

### PR DESCRIPTION
**Pull request by GrayRachnid**
Closes #37717 

- Look at the map diffbot to see the change.

Open for more suggestions.

:cl: 
add: The Spider Clan proudly announces that they've taken steps to improve their hospitality at their capture center! They now hope that captured targets would not kill them self or fight between each other, dirtying the floor with blood.
add: They've also added a VR room for those sick of the real world, taking them to a reality where they feel like they matter.
/:cl:

I did [this](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/6660) for Citadel but I know that /tg/ probably doesn't share the same crowd so this is a bare bones PR in order to see what people want.

### CODE REVIEW

**Comment by Mark9013100** [comment]
The ninja jail is probably one of the best places to put VR sleepers, if those actually work now.

**Comment by GrayRachnid** [comment]
Not exactly sure how those work but I wouldn't mind looking into them.

**Comment by Tlaltecuhtli** [comment]
add mini megafauna arena

**Comment by newfren** [comment]
give booze and soda dispensers please thank

**Comment by Bluespace** [comment]
Adding a medibot and sleeper is pretty important, the ninja usually fucks you up in order to capture you.

**Comment by CPTANT** [comment]
I actually forgot this exists, all the ninja's I've met just tried to cut my head off.

**Comment by 81Denton** [comment]
I'm working on a remodel that makes it more weeb themed and has VR sleepers, but this is a massive improvement already.

**Comment by DaxDupont** [comment]
Maybe it's time to add the murderdome to the away missions and repurpose away missions for VR areas without a gateway

**Comment by Nabski89** [comment]
Do deaths by the chasm still count for mobs captured by the net?

I thought it was 1 point for living, half point for dead or monkey, then 2 points for xenos.

**Comment by GrayRachnid** [comment]
Capture points is taken into account when a mob is captured, not when the round ends I believe.

**Comment by nicbn** [comment]
No suicide chamber pls

**Comment by BebeYoshi** [comment]
Please put a piano or some instrument, should me nice, not sure if it would fit the theme tho

**Comment by nicbn** [comment]
muh imerson

**Comment by Shadowflame909** [comment]
Yeah, the suicide chamber is kinda confusing. Aren't you supposed to basically sell the nanotransen workers on the black market? Who would want a dead body? Replooce with VR.

**Comment by GrayRachnid** [comment]
Huh, didn't know the lore was like that. I must've missed it.

I'm not sure what to do in regards to VR, do I just add in the VR sleepers?

**Comment by Shadowflame909** [comment]
The suicide chamber isn't really a problem, just triggers peoples OCD.

**Comment by ExcessiveUseOfCobblestone** [comment]
Why does this ruin have to suck so much?

**Comment by BebeYoshi** [comment]
I would totally beg to be captured if there was a piano there, long away from all chaos from the station, unless some antagonist got captured as well

**Comment by Wilchenx** [comment]
This is bad because if captured person is killed they are worth 0.5 a point to the ninja.

**Comment by GrayRachnid** [comment]
As I said, i'm pretty sure the checks are done on capture and not at round end

**Comment by GrayRachnid** [comment]
Additionally, could replace it with Shezza's weeb cafe.

image

I'd add VR to it too. Considering just making all the doors all access and whoever wants to staff it from the people captured can staff it, or I could do the long way and add some gay ass snowflake code to only spawn staff sleepers when there's a ninja with a capture objective.

**Comment by Shadowflame909** [comment]
Honestly, It fits lore wise so I wouldn't mind that. Catgirls and cat girl maids fit perfectly in the realm of space ninjas. Which are the equivalent of space weebs using fancy moves they learned from Naruto. They force all of the people they capture to work in catgirl maid cafes? That wouldn't be too far fetched for the spider clan!

**Comment by Shadowflame909** [comment]
The weeb cafe needs an arcade machine though, you can never go wrong with one.

**Comment by GrayRachnid** [comment]
I'll expand it a bit and add a VR machine and an arcade machine, then we can hold off until the murderdome gets merged.

**Comment by 81Denton** [comment]
>They force all of the people they capture to work in catgirl maid cafes

EW

**Comment by ExcessiveUseOfCobblestone** [comment]
When people keep saying VR what is the purpose of adding VR here?

I haven't badmin'd them yet recently but last I used them it sent my VR alias to an actual Lavaland Ruin. If it's going to be "you got captured but not really because you can just second life indefinitely on lavaland" then i'm not too sure about adding them.

**Comment by GrayRachnid** [comment]
#37730

**Comment by 81Denton** [comment]
I'd replace the indestructible walls with an indestructible version of /obj/structure/window/paperframe tbh

**Comment by DaxDupont** [comment]
Please make the code for ninjas turn people into cat people for the salt.

**Comment by 81Denton** [comment]
>for the salt

Days since last fetishist trick: ~~41~~ 0

**Comment by Nabski89** [comment]
She's just sad the salt shuttle got rejected.

**Comment by optimumtact** [comment]
no catgirls for the space ninja or this pr gets closed

they're a techno cyberfuturist faction, not anime

**Comment by GrayRachnid** [comment]
:dango:

**Comment by Shadowflame909** [comment]
I'm pretty sure they're space weebs, or thats something of a derogatory term to them lore wise. But ok oranges.

**Comment by optimumtact** [comment]
The wiki wrote

 The vast majority of space ninjas belong to the Spider Clan, a cult-like sect which has existed for several hundred years. The Spider Clan practice a sort of augmentation of human flesh in order to achieve a more perfect state of being and follow Postmodern Space Bushido. They also kill people for money. Their leaders are chosen from the oldest of the grand-masters, people that have lived a lot longer than any mortal man should. Being a sect of technology-loving fanatics, the Spider Clan have the very best to choose from in terms of hardware--cybernetic implants, exoskeleton rigs, hyper-capacity batteries, and you get the idea. Some believe that much of the Spider Clan equipment is based on reverse-engineered alien technology while others doubt such claims. Whatever the case, their technology is absolutely superb.

**Comment by optimumtact** [comment]
thank you

**Comment by GrayRachnid** [comment]
Ready for merging

**Comment by GrayRachnid** [comment]
ree I don't know how to get rid of the label I give up

**Comment by 81Denton** [comment]
You can put [Ready] in the title

**Pull request merged**
