### PR TITLE
nerfs the frog ear rape

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
These 2 sounds are obnoxiously loud and players have been complaining about it for a while now.

Old:

https://github.com/tgstation/tgstation/assets/96586172/aa9cd23a-d8a9-4c8e-a7cf-4a075c1e6f8b

New:

https://github.com/tgstation/tgstation/assets/96586172/501caa95-1721-4a16-af92-fa0529febb8c

Keep in mind that is is much louder in game, on video it is quieter because of the recording software.
## Why It's Good For The Game
Stepping on a mob shouldn't explode your ears outwards like in a cartoon.
## Changelog
:cl: grungussuss
sound: frog sounds will no longer explode your ears
/:cl:

### CODE REVIEW

**Comment by LSommers** [comment]
**HNNNNNNNNNNNNNNNNNNNNNNG**

**Comment by ElGitificador** [comment]
highly disagree, frog jumpscares are hilarous regardless the situation.

**Comment by Jacquerel** [comment]
we don't have a "needs video" label

**Comment by thgvr** [comment]
Loud sounds just make people turn their audio off.

**Comment by TJatPBnJ** [comment]
I will never join the game again if this gets merged. This PR will mark the downfall of TGstation.

**Comment by MTandi** [comment]
What is this sound even? Is it some internal meme?

**Comment by Sadboysuss** [comment]
added video comparisons

**Comment by optimumtact** [comment]
> I will never join the game again if this gets merged. This PR will mark the downfall of TGstation.

finally a good reason to merge a PR

**Review by optimumtact — APPROVED** [review]

**Comment by L0pz** [comment]
BOOOOOOO

**Comment by DustanHache** [comment]
removal of frog soul. bad change.

**Comment by Xkallubar** [comment]
If this gets merged then /tg/ will die

**Pull request merged**
