### PR TITLE
Candy cigarettes! + cig tweaks

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request
Adds Little Timmy's Candy Cigarettes packets to cigarette vendors. They have a 10% chance to have Nicotine in them.
Gives dromedary cigarettes 5u of water, and adds a 5% chance for Carp Classic to have 3u of Carpotoxin.
image

## Why It's Good For The Game
Candy cigarettes are fun and a healthy* way to look badass! If for some reason you *really* don't want nicotine, you can examine them for a subtle description difference in the ones that have nicotine and the ones that don't.
DromedaryCo has water because funny camel joke and it annoys me that otherwise it's the exact same as a normal cigarette.
Carp Classic has a tiny chance for Carpotoxin for the same reason. It won't drastically poison you or anything, and clever people can use it to very slightly more easily fabricate some obscure chemicals.

## Changelog
:cl:
add: Candy cigarettes! Fun for the whole family. Reports of addiction are punishable by permanent retirement.
tweak: The Carp Classic representative was found practicing 'isometric exercise' in the Cigarette Poisoning Meeting's bathroom window.
/:cl:

### CODE REVIEW

**Comment by tmtmtl30** [comment]
>zombie powder
>obscure

**Comment by carlarctg** [comment]
> > zombie powder
> > obscure

3u of Carpotoxin isn't enough to make even 1u of Zombie Powder and it's a 5% chance to begin with

**Comment by davethwave** [comment]
Probably talking about the clone damage healing chem.

**Comment by 81Denton** [comment]
We got uhhh an icon merge conflict on aisle 3

**Comment by carlarctg** [comment]
dmi conflicts dfgfbgbgnlhgñghk

**Comment by PKPenguin321** [comment]
there has to be some kind of way to automate icon conflict resolution, that shit is so simple yet tedious

**Comment by carlarctg** [comment]
> there has to be some kind of way to automate icon conflict resolution, that shit is so simple yet tedious

actioninja said he might work on something to automate it i think

**Comment by carlarctg** [comment]
> We got uhhh an icon merge conflict on aisle 3

@81Denton fixed

**Pull request merged**
