### PR TITLE
Fixes chronosuit not checking if held items are chronosafe

### PR DESCRIPTION
**Pull request by JJRcop**
This was broken ever since remi's multihand PR at #20283, where it would only check back and belt.

I have no reason to believe she did this on purpose, she edited a lot of files, a LOT of files.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Yeah it wasn't intentional

**Comment by optimumtact** [comment]
But why?

**Comment by JJRcop** [comment]
I had no intention of closing this branch, something is wrong.

**Comment by JJRcop** [comment]
I figured out what was wrong, I was cleaning up old branches and included this one by mistake, I have my github remote set in mirror mode, so I pushed, and then this branch was of course, deleted.

**Pull request merged**
