### PR TITLE
Fixes servant cyborgs with the Standard module not having Abscond

### LINKED ISSUE #35173: standard clock cult borgs can't abscond to Reebe
the other modules get the scripture but standard doesn't

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: Servant cyborgs with the Standard module now correctly have Abscond.
/:cl:

Fixes #35173.

### CODE REVIEW

**Comment by GunHog** [comment]
This is off-topic, but whatever happened to that Steampunk cyborg rework of yours? You once said that the borgs were losing a lot of tools in the new Steampunk overhaul, but it never happened :(

**Comment by Xhuis** [comment]
I don't think I ever said that...? I'm not sure what you're referencing. :v

**Comment by GunHog** [comment]
My apologies, it was Joan, not you that said this in PR https://github.com/tgstation/tgstation/pull/29925. I cannot help but get you two mixed up sometimes! :stuck_out_tongue:

**Comment by DaxDupont** [comment]
Ouch, @Xhuis

**Comment by Xhuis** [comment]
Bah humbug!

**Comment by Anonmare** [comment]
Ban Gunhog for murdering another Contributer

**Comment by Xhuis** [comment]
It's okay, Anonmare. I often get him confused for the first experiments of scientists with circuits, so it's even!

**Comment by ExcessiveUseOfCobblestone** [comment]
I confuse gunhog with every other individual who downvotes any science nerf.

**Comment by Xhuis** [comment]
OOF

**Pull request merged**
