### PR TITLE
OOC-ifies the Bluespace Tag

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
De-ICs the bluespace tag, instead presenting the same information in an OOC format.
image
This does not alter the actual information shown (besides a slight change to wording for the armor-piercing/block values, though the thresholds are the same).

P.S. I don't know if this is tagged correctly- it doesn't seem to neatly fit any category. (When are we getting the Tweak tag back?)
## Why It's Good For The Game
The bluespace tag has sorta been an oddity since it was introduced. While the rationale behind its addition was sound- we want players to have information without code-diving, but not necessarily anything too concrete- the actual stuff surrounding that information has always felt off. Why exactly are we finding items that have lain undisturbed on lavaland for centuries that have a bluespace tag? What magical source of information are they drawing from? Basically, in its attempt to make OOC information IC-relevant, it creates more plot holes than it solves, and ultimately it does so to no real benefit. Hence, I feel it's best that we just stop trying to present this in an IC format.
## Changelog
:cl:
qol: Bluespace tags are gone. The information contained within is still available in the same way, just in a more out-of-character format.
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
but can't we just show up the straighr values at this point like juat 15 brute or 17 burn

**Comment by EOBGames** [comment]
> but can't we just show up the straighr values at this point like juat 15 brute or 17 burn

I was explicitly asked not to do this by mothblocks, and frankly I don't feel too strongly about it anyway- all I really aim to do here is get rid of the bluespace tag.

**Comment by SgtHunk** [comment]
wasn't the first iteration of bluespace tags rejected for doing this? since it was considered too game-y and that's why the tags have some flavor to them?

**Comment by BlueMemesauce** [comment]
Original pull request for reference #58865

**Comment by EOBGames** [comment]
So, re: the comments about prior iterations- I did seek mothblocks' approval here, since I know they spearheaded the original addition, and the general gist of the conversation (it's too lengthy to get a meaningful screenshot) was that they weren't a particular fan of the flavour and what was important in any changes I made was that the information maintained a degree of obscurance (which this does, given it hasn't changed any of the actual data). Ultimately, the final decision was that while finding an IC format for this kind of stuff is generally good, in this case it hasn't been successful and making it OOC instead was a suitable move.

**Comment by BlueMemesauce** [comment]
While you're here, there's a unneeded line break in the second box. It's no longer necessary now that each segment is in their own box.

**Comment by lizardqueenlexi** [comment]
Shouldn't that be "to crit", not "to kill"?

**Comment by GuillaumePrata** [comment]
> It should just say the damage values

Pure damage would be a lot more useful for the new players too.
The old tag was flavorful and funny, but it was a lot of info when the new players just want to know how much damage a toolbox do, which the only way to figure out still is to go code/wiki dive which makes the feature in itself mostly useless.

**Comment by CRITAWAKETS** [comment]
not showing the exact damage doesn't help at all for new players and whatnot, since you just need to take into account that people have 200hp in order to find the exact damage value. this is just being annoying and making you do extra math for the sake of being annoying

**Comment by EOBGames** [comment]
> > Shouldn't that be "to crit", not "to kill"?
> 
> It should just say the damage values if its going to be fully OOC, the amount of damage to crit can vary depending on multiple factors

Again, to fully reiterate it: I was explicitly asked not to give exact values by mothblocks. That's not the point of this PR. If someone wants to talk mothblocks into allowing exact values, they can do so, but I am not going to be the one to either try doing that or making the PR.

**Comment by Mothblocks** [comment]
EOB's only concern is that the IC text of the system is clunky and that OOC text here would be less silly. In the future I think I want these to be tooltips that you get from hovering over the item icon in examine, so we can avoid most text entirely. 

That being said, they are right that I do not want to see these using exact damage values. "Taking into account people have 200 HP" is, in itself, not super intuitive (most games are 100!) and I don't see how it is at all better than giving you more digestable numbers. It avoids needing to do the math, especially since armor makes it more complicated.

If the text on "to kill" is wrong then that's half my mistake since I suggested the text. "To take down" would be better if that's the intent.

**Comment by Jacquerel** [comment]
The macro name and implementation (`HITS_TO_CRIT`) does indeed imply it doesn't actually _kill_ the target so the wording could be changed if it might mislead people, but the number of hits it takes to make someone stop being able to fight back does seem like the most relevant way to communicate the information (so it'd be better to reword than to change it to check for 200 damage).
If we can address that I will merge this (unless mothblocks gets there first).

**Comment by Mothblocks** [comment]
> If the text on "to kill" is wrong then that's half my mistake since I suggested the text. "To take down" would be better if that's the intent.

Yeah if it's true then please do this

**Comment by BlueMemesauce** [comment]
> not showing the exact damage doesn't help at all for new players and whatnot, since you just need to take into account that people have 200hp in order to find the exact damage value. this is just being annoying and making you do extra math for the sake of being annoying
> 
> also, shows "to kill" when the values used are actually to crit, smh

There's no such thing as 0.7 of a hit, so you'll end up having to do math anyway to at least round it up to a whole number. Sure, this is essentially automatic to us, but dividing 200 or 100 by a number isn't that hard either. 
Also, if your target is already wounded, the number of hits will be worthless information unless you do the math to get the actual damage value.  It's only reliable in a perfect situation where the target has full health and full sanity (and therefore enters crit at the lowest health). Damage values are just more practical.

**Comment by Mothblocks** [comment]
> There's no such thing as 0.7 of a hit, so you'll end up having to do math anyway to at least round it up to a whole number. 

i'm okay rounding it up in another pr but not this one because that's not what inept cares about here. but no i still completely disagree that we should be showing exact damage numbers

**Comment by BlueMemesauce** [comment]
> > There's no such thing as 0.7 of a hit, so you'll end up having to do math anyway to at least round it up to a whole number.
> 
> i'm okay rounding it up in another pr but not this one because that's not what inept cares about here. but no i still completely disagree that we should be showing exact damage numbers

Just wondering if you still think this, and if so, then why do you completely disagree? I gave my reasons before and I still think giving the exact values is more valuable than the number of hits to reach 100 damage. That amount is quite arbitrary considering some players will have armor, lower mental states, or be already damaged which will all affect the amount of hits it takes to crit someone.  Yes, for a situation where someone starts with full health and no armor or anything it's easier as you just need to round up the number to see how many hits it takes. But for the many other situations it will take alot more mental math to approximate how many actual hits it will take to crit someone. That's why the exact damage values are overall more useful.

**Comment by RikuTheKiller** [comment]
> > There's no such thing as 0.7 of a hit, so you'll end up having to do math anyway to at least round it up to a whole number.
> 
> i'm okay rounding it up in another pr but not this one because that's not what inept cares about here. but no i still completely disagree that we should be showing exact damage numbers

Don't round it, it's useful as it carries extra information such as 0.5 hits meaning it can instakill.

**Pull request merged**
