### PR TITLE
[WIP] Infiltration gamemode

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Adds a new game mode, antagonist and event - **Infiltrators**.

_Infiltrators_ are a bunch of _sneaky_ fellows who are supposed to, you guess it, _infiltrate_ the station to complete bunch of their objectives on it and get out if needed.
By default, those agents start with a normal syndicate space suit, C4, chameleon PDA, ID, jumpsuit and shoes.
As they have nothing to do with Nanotrasen, they are not expected to leave on the shuttle, except for situations when they specifically need to hijack it or **impersonate someone**.

Infiltrators can come in all flavours, depending on how lucky you are today.
Currently, there are **4 factions**: Cybersun, Gorlex Marauders, Tiger Cooperative and MI13.

The faction you get affects quite a lot of stuff including: 
- Amount of starting TCs.
- Objectives.
- Role-specific items in the uplink.
- Starting items and, sometimes, implants.
- Flavor text (muh MRP).

The config allows admins to change a bunch of stuff, but mainly it's here for MRP servers or when you hate _particular faction_.

This PR also adds new traitor device - advanced mulligan. This handy tool allows you to store anyone's DNA and then transform yourself into the person you stabbed earlier.
Its main purpose is identity theft objective, infiltrators might get, but also allows them to stay undiscovered by the crew.

## Why It's Good For The Game

Basically, I was reading a wiki page on the game modes and noticed this thing:
image

I thought that it is one of the least terrible game modes that were disabled/removed, according to the page, and general idea is quite interesting.
Then, when I started to code it I remembered the old idea of having factions for traitors, then it all developed into what I got here.

I believe it can be a really good game mode/antagonist/event if done right.

_[Insert "antag variety = good" quote]_

## Changelog
:cl:
add: Infiltration game mode. Basically, a bunch of people that start in space near the station, without a job on it with traitor objectives.
add: Infiltrators have a chance to be from one of 4 factions, currently including "Standard", Cybersun, Gorlex, Tiger Co. and MI13. It affects their starting outfit, items, implants, amount of TCs, role-specific uplink items and objectives.
config: Infiltrators faction chances, flavour text, amount of objectives and whether they should get codespeak can be modified in the config.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
I said this in the last syndicate faction PR and I'll say it in this one, I hope in the future we can get faction-limited traitor gear from this

**Comment by EgorDinamit** [comment]
If this idea is well received, I would just need sprites to add new role-specific items.

**Comment by Mey-Ha-Zah** [comment]
Hey, Spriter here. There's the Cybersun Hardsuit I made a while ago you could use, plus I might be interested in helping make some unique gear.

**Comment by EgorDinamit** [comment]
As of now, this game mode works perfectly fine, but I was planning on adding more stuff in the future.

So, this specific PR, sadly, doesn't need new sprites.

**Comment by Fishimun** [comment]
based

**Review by Twaticus — APPROVED** [review]

**Comment by optimumtact** [comment]
wow another remake of traitors, so ORIGINAL you must have put so much effort into this.

embarrassing.

**Comment by dondonpow** [comment]
this better be a poe's law situation

**Comment by EgorDinamit** [comment]
Dear Oranges, when this is actually ready I will put [Ready] in the PR's name, but current version is playable and works well with the main idea that was behind it.

**Comment by Kaffe-work** [comment]
oranges on a anti-fun crusade, news at 8

**Comment by optimumtact** [comment]
The more I look at this the more convinced I am this is just traitor and should be rolled into the base gamemode

also the mulligan is a pretty weak copy of the changeling mechanics

**Comment by optimumtact** [comment]
in fact yeah, I'm gonna make a design call and say you should just roll this into traitor, not it's own gamemode.

happy for traitors to have factions and lore.

**Comment by Pumpkinoe** [comment]
I kinda like the 'infiltrator starts outside of the station unaffiliated and has to get in' mechanic. If this is rolled into traitor will that be lost?

**Comment by optimumtact** [comment]
There's no reason why a traitor spawn has to start on station.

**Comment by Pumpkinoe** [comment]
As long as they get to stay off the crew manifest and have to break their way inside still.

**Comment by EgorDinamit** [comment]
The main idea wasn't "Traitors with lore", it is all about _possible_ team work, getting into the station without getting spotted and only then completing your mission.
I am still working on it to be more distinguishable from normal traitors and be actually interesting by itself.

I can understand your concerns of it being "yet another gamemode bloat", but it's being worked on so there is no need to rush with such claims.

**Comment by ExcessiveUseOfCobblestone** [comment]
It's traitors with a twist, but I don't think it's such a twist it needs to be it's own mode.

**Comment by optimumtact** [comment]
I don't trust the creator to actually do this properly so i'm just saving myself the trouble

**Comment by Pumpkinoe** [comment]
lame, was looking forward 2 this

**Pull request closed without merging**
