### PR TITLE
Ignore list verb

### PR DESCRIPTION
**Pull request by PrimordialOoze**
## About The Pull Request
Adds a verb to the OOC tab that lets us view a list of players we've ignored.

## Why It's Good For The Game
Instead of trying to remember who we've blocked the game can just tell us. Makes it easy to check if we accidentally ignored someone we didn't want to ignore.

## Changelog
:cl:
add: Added a verb to view your ignore list
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Really should let you manage the list, since you cant normally unignore someone unless they are online

**Comment by nemvar** [comment]
Adds yet another way to detect stealthmins. Just ignore someone you think might be a stealthmin and display the list. It will tell you the persons real key.
If someone will actually do that though is questionable.

**Comment by PrimordialOoze** [comment]
#51353

**Comment by Cyberboss** [comment]
Closing in favor of above

**Pull request closed without merging**
