### PR TITLE
Fixes licensing error present in LICENSE and related files

### PR DESCRIPTION
**Pull request by ZeWaka**
## About The Pull Request

Fixes a licensing error in LICENSE. Somehow, the license got changed from CC-BY-NC-SA 3.0 to GPL 3.0 and then AGPL 3.0 at some point. This clearly was an error, as the original SS13 code that this codebase is derived from (Goonstation Revision 4407) was not licensed under those other two licenses, nor did the original creators did not give permission to relicense at any point.

Also corrected is a small error in the asset licence, in that the assets have been licensed under CC-BY-NC-SA in origins of this codebase as well.

## Why It's Good For The Game

N/A

### CODE REVIEW

**Comment by d3athrow** [comment]
fund it

**Comment by optimumtact** [comment]
banappeals

**Comment by Iamgoofball** [comment]
looks good to me, ship it

**Comment by Tharcoonvagh** [comment]
fun

**Comment by kyrahabattoir** [comment]
Dejà vu?

**Pull request closed without merging**
