### PR TITLE
Small path change and new Legion spawn animation

### PR DESCRIPTION
**Pull request by ghost**
- `/obj/structure/weightlifter` and `/obj/structure/stacklifter` have been merged since they were the exact same but were copypasted from one another.
- Legion now has a [spooky spawn animation and sound](https://dl.dropboxusercontent.com/u/116194515/legion_spawn.mp4). Sounds, messages, and colors are shown across Legion's z-level.
- The necropolis gate now has a decent delay before summoning Legion.

I suppose the merge token for this would be #18022. I'm not sure how merge tokens work.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
They're not actually the same, though. They've got different pixel shifts.

**Comment by Xhuis** [comment]
???

**Comment by ChangelingRain** [comment]
while (lifts++ < 6)
     			if (user.loc != src.loc)
     				break
     			sleep(3)
     			animate(user, pixel_y = -2, time = 3)
     			sleep(3)
     			animate(user, pixel_y = -4, time = 3)
     			sleep(3)
     			playsound(user, 'goon/sound/effects/spring.ogg', 60, 1)

And

    		while (reps++ < 6)
    			if (user.loc != src.loc)
    				break
    
    			for (var/innerReps = max(reps, 1), innerReps > 0, innerReps--)
    				sleep(3)
    				animate(user, pixel_y = (user.pixel_y == 3) ? 5 : 3, time = 3)
    
    			playsound(user, 'goon/sound/effects/spring.ogg', 60, 1)

Are not the same.

**Comment by Xhuis** [comment]
I can correct that easily, but it's still desirable to make one a child of the other.

**Comment by TechnoAlchemisto** [comment]
Did you get rid of the prompt?

**Comment by Xhuis** [comment]
The prompt for knocking on the door is still there.
This isn't a map edit, please remove that label.

**Comment by ChangelingRain** [comment]
it has a map edit tho???

**Comment by Xhuis** [comment]
Ahh, that. Yeah, nevermind!

**Comment by Xhuis** [comment]
Oh, conflicts. How I tire of having to deal with you. This time I'm not going to bother; maybe if I become invested enough I'll eventually fix them.

**Pull request closed without merging**
