### PR TITLE
Fix briochecake icon, add tastes and foodtypes

### PR DESCRIPTION
**Pull request by atakiya**
## About The Pull Request
- Adds a missing `icon_state` to the full brioche cake
- Adds `SUGAR` to the brioche cake's and slice's `foodtypes`, as they're glazed (according to the description)
- Adds butter and cream to the `tastes` as well

## Why It's Good For The Game
- Less visible errors
- Brioche is quite sweet and buttery, the taste mirrors that now

## Changelog
:cl: Avunia Takiya
fix: Brioche cakes don't look like errors anymore, visually
add: Brioche cakes and its slices have a specific taste now
/:cl:

### CODE REVIEW

**Comment by Pugie** [comment]
brioche cakehat?

**Comment by Avunia** [comment]
> 
> 
> brioche cakehat?

What about it?

**Comment by Pugie** [comment]
So it exists?

**Comment by Avunia** [comment]
> 
> 
> So it exists?

No.

**Comment by Pugie** [comment]
> > So it exists?
> 
> No.

why? are you not aware of the cake feature freeze. no cake changes unless it's cakehat related

**Review by ghost — APPROVED** [review]
thanks for fixing this.

**Review by Cyberboss — APPROVED** [review]
For the future, please do not combine features and fixes in the same pull request.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Avunia** [comment]
> 
> 
> For the future, please do not combine features and fixes in the same pull request.

Noted.

**Pull request merged**
