### PR TITLE
Major UI update and theme redesign

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

This PR completely overhauls Midnight and Midnight-derived UIs, as well as does some adjustments to the UI layout.

image

### Major changes:
 * All UI elements for Midnight/Midnight-derived themes have been redrawn to be cleaner, with consistent palettes and up-to-date sprites
 * Tiny equip E is gone - Drop action has been moved in its place, freeing some space in the bottom right corner
 * Four minor menu keys have been bundled with actions, now-vertical floor change element taking their place
 * Action palette (wide thing in the top left corner) is now hidden when it has zero actions bound to it and the player isn't currently dragging an action button.

I've also fixed some minor issues with how hand elements are rendered, and given feedback to resist button (it now lights up when pressed or when the hotkey is held down)

<details>

<summary>Some screenshots of new UIs</summary>

image

image

image

Redrawn UIs now have themed clothing slots

image

image

qrd5eRR

</details>

## Why It's Good For The Game

Our UI icons are very outdated and compressed, with very large palettes and odd transparency quirks, making adding new elements or redesigning current ones quite hard and frustrating. A fresh coat of paint can take user experience a long way.

As for moved elements, most people either equip things manually or use the equip hotkey - E button is rather obscure and rarely used, while drop button makes sense to be located near hands. Action palette just takes up screen space most of the time, so there's no reason to not hide it when you don't have any use for it.

## Changelog
:cl:
qol: Resist button now has visible feedback.
qol: Readjusted UI layout.
image: Completely redrawn Midnight and Midnight-derived UIs!
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
I don't actually use clockwork ui but I'd probably have concerns that people (mainly non-shaft-miners) have no idea wtf this is

image

If you want a deep cut, the old Write Spectacles sprite would work here tho

**Comment by SmArtKar** [comment]
> I don't actually use clockwork ui but I'd probably have concerns that people (mainly non-shaft-miners) have no idea wtf this is
> 

image

Yessir!

**Comment by AyIong** [comment]
Don't forget about icons\ui\inventory :D (Used for Strip Menu)

**Comment by Jacquerel** [comment]
> While we're at it, can we swap the locations of the two hand slots so that the left hand is actually on the left?

it might be wrong but it looks better for the hands to face outwards than inwards

**Comment by LemonInTheDark** [comment]
matches the sprite when it faces the "camera"

**Comment by Ghommie** [comment]
I think the clockwork theme should use the bronze/clockwork boots as base foe the shoes equipment slot, but gj anyway. I'll merge it once I'm home I guess.

**Comment by Jacquerel** [comment]
> I think the clockwork theme should use the bronze/clockwork boots as base foe the shoes equipment slot, but gj anyway. I'll merge it once I'm home I guess.

After a sprite lead approves it as well, I assume? 😅 
Even if it's mostly a tuneup of existing sprites this _is_ mostly a PR about art direction (and for our part, UI arrangement)

**Review by Wallemations — APPROVED** [review]
love the themed slots

**Comment by LSommers** [comment]
The slot backgrounds (and slot icons, frankly) seem to stand out a lot more, and not in a good way. I can't tell if it's less transparent than it was before, or if that's an optical illusion, but it's oddly distracting.

**Comment by SmArtKar** [comment]
> The slot backgrounds (and slot icons, frankly) seem to stand out a lot more, and not in a good way. I can't tell if it's less transparent than it was before, or if that's an optical illusion, but it's oddly distracting.

They're actually slightly more transparent than before - probably an illusion?

**Comment by gryffinp** [comment]
I hate the themed slots.

**Comment by LSommers** [comment]
The L and R indicators on the hands becoming "bolded" when the slot is highlighted is also messing with me, but at the same time I can't remember if was like that before or not.

**Comment by SmArtKar** [comment]
> The L and R indicators on the hands becoming "bolded" when the slot is highlighted is also messing with me, but at the same time I can't remember if was like that before or not.

It wasn't, I'm planning to address that in a bit (by dimming the highlight around the letters and brightening the bottom part of hands highlight) alongside fixing plasmafire's missing transparency (somehow that one went missing)

**Comment by kopoba** [comment]
why we missing equip button i was using it all the time and it was tiny E can we have it back near drop button?

**Pull request merged**
