### PR TITLE
Adds the distinguished employees gallery to Meta and Delta

### PR DESCRIPTION
**Pull request by Mickyan**
Adds a few persistent photo frames to the showroom on delta and meta for heads of staff to commemorate distinguished crewmembers, or for random assistants to impress everyone with their ability to hack the showroom door

## Changelog
:cl:
tweak: Added the persistent photo gallery for distinguished employees to Metastation and Deltastation showrooms
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
It should just be a photo gallery for whatever instead of having the specific purpose of immortalising people's OCs (which until there's a voting mechanic that culls crap won't even work for that dubious purpose because of how large the pool of potential persistences will become).

**Comment by Mickyan** [comment]
To the best of my knowledge photo frames work the same as albums meaning it's persistent by the actual meaning of the word, it's not saved permanently and loaded at random like paintings. Someone who understands persistence code can probably verify.

**Comment by MrDoomBringer** [comment]
imo this would be cooler if it was a system that displayed the 'employee of the shift', which could be voted on each roundend or something.

**Comment by Jared-Fogle** [comment]
mdb you know just as well as i do that it would just be one of the five people who murderbone every round

**Comment by Mickyan** [comment]
people really be suggesting grand new features on a 5 minute map tweak PR

**Comment by MrDoomBringer** [comment]
code my grand new features do it

**Review by Mothblocks — APPROVED** [review]
well it doesnt rewrite the entire game but its alright i guess

**Pull request merged**
