### PR TITLE
Delta mapping fixes + Improvements

### LINKED ISSUE #57388: The Bar RP/Hentai Bots Are Hard to Serve On Delta Station
Let me explain:

If you place a drink to the south of the robot within 1 tile (i.e. the bar/kitchen counters on metastation) they will pick up their drink and dispense the money on the counter.

On Delta station, however, the bar is built in the north of the service room, so the bots can't pick up the drinks and you have to go all the way through theatre to the other side of the bar to serve them.

Basically, the hentai/brazzerbots can't accept food and drinks north of them, only south of them.

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Fixes #57388 

Fix: the chairs are now facing north for the bartender so the robots won't sit facing south
Change: Bartender and chef now get a windoor and normal door respectively to more easily enter the atrium
Change: Opened up the chef's counter a bit more

## Why It's Good For The Game

Holy fuck I hate delta's kitchen, the pathing just to get to the atrium is unbearable man

## Changelog
:cl:
add: adds a windoor to the bar, and a door to the kitchen to allow access to the atrium
add: opens the kitchen up a bit more
fix: tourists now sit facing the bar on delta
/:cl:

### CODE REVIEW

**Comment by notfrying1pans** [comment]
make the tile below the door in the kitchen match the rest of the kitchen floor

**Comment by tralezab** [comment]
To the void

**Comment by Pugie** [comment]
A true American hero

**Comment by EOBGames** [comment]
Please make sure the chef still has a supply of wrapping paper and a labeller, once that's sorted I'll merge this

**Comment by tralezab** [comment]
ready, integration test was the gun_go_boom.dm

**Comment by tralezab** [comment]
still ready :)

**Pull request merged**
