### PR TITLE
adds electromagnetic warfare crate to cargo

### PR DESCRIPTION
**Pull request by ghost**
Costs 15000 credits. is contraband. contains one ion rifle and 3 classic emp grenades.

:cl: vcordie
rscadd: Quartermasters be aware: Some shadier sellers are now offering electromagnetic warfare crates. Such armaments are of course, contraband and will be automatically filtered by your console..
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
How hard us it to add a ion rifle for 5000 points

**Comment by Kromgar** [comment]
vcordie can't acccept the idea of a single ion rifle can he

**Comment by jughu** [comment]
He just wants a ion weapon that fits in his bacpack like a sawn off shotgun

**Comment by BeeSting12** [comment]
>thumbs upping your own PR

**Comment by XDTM** [comment]
I think that shotgun ions shoot 4 ion projectiles, not 1. The aoe type too, if i'm not mistaken.

**Comment by SweaterKittens** [comment]
As someone who loves silicon roles as well as playing them, I think adding more ways to completely obliterate them is a bad idea. They're weak as is, I don't feel like there needs to be even more ways to completely screw them over with zero counterplay.

**Comment by FantasticFwoosh** [comment]
I like this more than importing dumb carbines, still needs tweaking given how expensive the crafting materials are.

Bump up the cost to 12000 or more per box, it takes R&D parts (advanced capacitor & uranium laser) plus a bluespace crystal to construct a ion slug (each!) 

Also a nerf / just check before you merge of the ammunition's tech level so science doesn't try to cheese tech levels using 1 box of these. Then it should be good to go.

> AI can just lock the cargo doors or get a borg to drag the boxes into space when spotted.

**Comment by vcordie** [comment]
@SweaterKittens its not so much against silicons, its that lots of shit has emp weakness now. its the hip new thing to make your antag weak to as a balancing point. *COUGH CLOCKCULT COUGH* 


as to everyone else: If i make it an ion rifle, i make you happy, but make other people unhappy "WAH WAH ION RIFLE DOESNT EVEN HAVE TO AIM DUE TO 3X3 AOE". If I make it this, I get people whining at me that its "wah wah not an ion rifle wah", damned if I do, damned if I don't.

As far as I can tell, the slugs fire a single weakion projectile which empulses for 0, 0, unlike an ion rifle which empulsees for 1, 1.

**Comment by vcordie** [comment]
Alright, I was wrong, it actually does 4 pellets, each of which is a non aoe ion. I've doubled the price.

**Comment by vcordie** [comment]
you know what? lets try to make everyone happy. massive change incoming

**Comment by kevinz000** [comment]
Not happy.

**Comment by ExcessiveUseOfCobblestone** [comment]
>EMPs are a valid balance argument
 >They literally revolve around "do you have a form of EMP or not"
 >ALMOST AS DISGUSTINGLY BINARY AS SPACE

also can you just make a melee EMP option since having a range hardcounter that also AoEs you can buy in bulk seems really lame.

**Comment by FantasticFwoosh** [comment]
EMP grenade & ion rifle (not sure it should be there) is a little distasteful just because ion's are strong but a general improvement on the idea.

**Comment by jughu** [comment]
ION RIFLES ARENT CONTRABRAND TRY AGAIN

**Comment by jughu** [comment]
So how many points are these emp grenades worth because i can get a whole box of them way cheaper

**Comment by YakumoChen** [comment]
oh boy, 'classic EMP grenade', the one you only need two of to kill an AI in its core chamber without even going inside. Boy, I'm sure going to love cargo ordering that one every malf round.

**Comment by optimumtact** [comment]
Well nobody seems to like this, maybe try another pr with just an ion rifle in a crate or something.

**Pull request closed without merging**
