### PR TITLE
Minor post winter chills: Short MODsuit freeze

### PR DESCRIPTION
**Pull request by tralezab**
## About This Freeze

MODsuits have some bad dmi sorting that is causing needless merge conflicts, and @MrMelbert and I agree on getting this out of the way right now.

Only one restriction: Modsuit related pull requests are DNM until #63999, which has the restriction to properly split and sort the dmis, is handled.

### Because you were wondering, why that pr?

1. It got the review asking it to happen, and if it wasn't that feature pr it'd be the next one
2. It already properly sorts the modsuit sounds which were just thrown in the items folder

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
You should do the sorting in a pr other then that one. Something something atomization

**Comment by MrDoomBringer** [comment]
tralezab wants to merge 2 commits into tgstation:master from tralezab:المساعدون-جيدون-😂

**Comment by tralezab** [comment]
> You should do the sorting in a pr other then that one. Something something atomization

Yeah well, melb didn't give me much of a choice!

**Comment by MrMelbert** [comment]
hey man you can do whatever you want

**Comment by tralezab** [comment]
> hey man you can do whatever you want

that's not exactly how maintainers reviewing your pr works

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]
Do what you want. If you don't, I'll close your pr

**Review by san7890 — COMMENTED** [review]
i second what lemon said

**Comment by necromanceranne** [comment]
A bit of cleanup never hurt, and god do so many of our sprite files need it.

**Comment by MrMelbert** [comment]
all clean :)

**Pull request closed without merging**
