### PR TITLE
Moves blood crate back to surgery room instead of virology(box station)

### LINKED ISSUE #19373: Blood is missing from surgery on box station
Blood box thing is missing from surgery on box station. It's in the viro breakroom for 4noraisin.

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
tweak: Blood packs are now back in surgery room.
/:cl:
i'll never understand why it was moved to virology's breakroom to begin with
Fixes #19373

### CODE REVIEW

**Comment by ChangelingRain** [comment]
It wasn't actually moved, it just got removed at some point.

**Comment by lzimann** [comment]
makes even less sense

**Comment by Zilenan91** [comment]
Yeah there was always one in both viro and surgery.

**Comment by lzimann** [comment]
guess i can add it back to virology then

**Pull request merged**
