### PR TITLE
Removes a random stack of glass embedded inside of the rocks of Tramstation

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

This map edit was brought to you by the SS13 webmap. Everyone say "Thank you AffectedArc07".

image

Found this while looking for something entirely unrelated.

## Why It's Good For The Game

Glass doesn't go there!!!!

## Changelog

:cl:
fix: Surgically removed a stack of 50 glass sheets from the rocks of Tramstation's lower decks.
/:cl:

### CODE REVIEW

**Comment by TheBoondock** [comment]
Tramstation NERF

**Comment by bruhman8ghughug** [comment]
can you mark this as a balance pr

**Comment by TheBoondock** [comment]
High priority!!!

**Comment by Time-Green** [comment]
@JohnFulpWillard doing backdoor gbp deals huh?

**Pull request merged**
