### PR TITLE
FIXES DEAD CHAT QUICK MERGE PLS

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by Anonmare** [comment]
This is clearly good for the server and fixes a lot of long-standing issues regarding hte round meta

**Comment by PKPenguin321** [comment]
hurry travis go go go

**Comment by Anonus** [comment]
# THE SCREAMS OF THE DEAD FILL YOUR EARS

**Comment by Iamgoofball** [comment]
:-1: This PR will break the existing meta. Stop ruining my roleplay!

**Comment by optimumtact** [comment]
don't merge there is a bug

**Comment by PKPenguin321** [comment]
2 late

**Pull request merged**
