### PR TITLE
Jackhammer nerfs. This thing no longer destroys walls.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Title.
Same idea as #45836 originally had, only doesn't come with a complementary buff

## Why It's Good For The Game

Walls are bad right now, this is part of an overall push by me to increase their meaning. It's silly that this mass produced tool can instantly destroy most walls and even destroy rwalls with some time.
Since I have the goal to increase the integrity of room structures, this kinda has to go.

And no bikeshedders, I'm not going to remove it completely, that makes floyd a sad panda.

## Changelog
:cl:
balance: The sonic jackhammer can no longer destroy walls.
/:cl:

### CODE REVIEW

**Comment by CPTANT** [comment]
Jackhammers aren't "mass produced" they are very expensive and have steep research requirements. They are also bulky, which further limits their usefulness.

I don't even agree with the "walls are bad" attitude, illicit access is part of the game and segmenting the entire station isn't going to do anything except fuck antags over.

**Comment by nemvar** [comment]
The point of this is to fuck over antags.

**Comment by necromanceranne** [comment]
Antags don't give a shit about walls. There is a ton of shit to ge through walls out of the uplink for tots, changelings have a few interesting methods, wizards don't give a shit, cultists have veil shifters, and nukies get free explosives.

Only revs have problems and that's just because they're crew made antags. The real problem with easy wall destruction is honestly just griff and hardcore tiding.

**Comment by Cyprex** [comment]
I'd like to mention that it should be possible somehow to remodel rooms, move walls etc. for engineers, right now I think it is very difficult to remove reinforced windows in bulk without wasting a lot of time? For Rwalls, your only real options are borg RCDs(hope you have an engiborg) and mass producing thermite, but this is much more of an antag/tide thing, not something your usual engineer would have access to, and isn't really practical in large amounts. I'm thinking of things like expanding the Supermatter Engine emitter room backwards to add more emitters.

**Comment by CRITAWAKETS** [comment]
honestly if someone is spamming this down a hallway they effectivelly have a big "DISARM AND TAKE ALL MY SHIT" sign on them

Like, sure, your change makes sense if its just for like 5 people in a server. The issue is that /tg/ is 40 to 90 players.

**Comment by daklj** [comment]
jackhammer is bulkier, more expensive to make and has way less usages than RCD
also requires costly tech

at least let it outclass the powergamers omnitool in removing walls eh?

**Comment by actioninja** [comment]
I fully intended to merge this unless a decent argument that isn't just "but this make antag harder :/" is brought up.

**Comment by Cyprex** [comment]
See my comment regarding engineerings need to remove walls in bulk, jackhammer grief is fairly rare nowadays, I don't think this needs to be changed.

**Comment by Akrilla** [comment]
The difficulty to create, and carry jackhammers are large enough that their ability to destroy walls is reasonable. If an antag wants to use a jackhammer to do their antag stuff, they need to gain access to R&D, make sure there'se enough resources, then ignore all people asking why he's carrying a jackhammer around as a curator.

**Comment by KetasDotepasto** [comment]
@Akrilla You can print it at the cargo-lathe, tech requirement is advanced mining, which is top of the priority list currently, and cargo is one of the more easy going departments. The way the sonic jackhammer currently goes, you could then use it to break into places from space, avoiding all public areas on most in rotation stations.

With this thing, breaking into the AI core is only marginally slower than walking in if you had access. This thing is ridicously overpowered.

**Comment by plapatin** [comment]
ai core busting is trivial with the way the current jackhammer works, at least thermite gives you some time to react.
people seem to forget that you can put a sonic jackhammer on both your belt and in a mining suit storage (if you make the argument that this takes away a toolbelt slot, don't forget that most belts can be stored in your backpack too, being normal-sized items)
also, the argument of the fact that it's costly in materials is an absolute joke. if you can make a sonic jackhammer, chances are you can make 20 more of them if mining is doing their job.
i think a better way to approach this would be to remove it's rwall busting ability but its not normal wall busting ability and up it's size.
on a slightly unrelated note, i'd really like it if regular mining drills could keep up with PKAs. currently there's absolutely no reason to ever print a mining drill since PKAs and plasma cutters just fucking tear through everything

**Comment by actioninja** [comment]
To respond to "it's hard to get" comment, advanced mining is one of the earliest researched techs and as mentioned it's available from the cargolathe. Any tider or antag can get their hands on one if they just want one.

**Comment by CPTANT** [comment]
Yeah sorry but nerfing it this hard without any reduction in cost is just nonsense.

Better of to just remove the item with how useless it is now. Give me ONE situation in which I would want a jackhammer over any of the other options.

**Comment by adamkad1** [comment]
yeah, why make it cost a lot if its primary function is gone? (lets be honest, only golems ever use the thing to mine)

**Pull request merged**
