### PR TITLE
The Hangover station trait no longer makes you drop your held items into the shadow realm on roundstart.

### LINKED ISSUE #57642: Apparently, plasmamen that spawn hungover don't spawn with internals active
## Round ID:

#158023

## Reproduction:

image

image

### LINKED ISSUE #58262: Hangover trait spawns MDs without their special medkits
## Round ID:

#159888

## Reproduction:

The CMO and the MDs spawn without their special extra-large medkit with tools with hungover. Probably gets stuck in the spawn box since everyone spawns collapsed. 

Probably same issue as #57642

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

This PR changes the hangover station trait to, rather than applying sleep, make people rest. This makes it so that held items aren't dropped on the start of the round.

Closes #58262
Closes #57642

## Why It's Good For The Game

This makes it so that held items, such as the surgical kits of MDs and the plasma tanks of plasmamen aren't dropped upon spawn and lost into the void.

## Changelog
:cl:

fix: Hangover trait applies rest rather than sleep so that the roundstart held items of MDs and plasmamen aren't lost.

/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
good catch, thank you.

**Comment by Bluedazzled** [comment]
ah so that's where my wheelchairs went roundstart, thanks

**Comment by FernandoJ8** [comment]
> 
> 
> ah so that's where my wheelchairs went roundstart, thanks

oh no...
This PR doesn't fix that, and it probably does need fixing

**Comment by FernandoJ8** [comment]
> 
> 
> good catch, thank you.

Than Cyo, he's the one that noticed it.

**Comment by ArcaneDefence** [comment]
Related issues that weren't linked https://github.com/tgstation/tgstation/issues/58262 https://github.com/tgstation/tgstation/issues/57642

**Comment by FernandoJ8** [comment]
> 
> 
> Related issues that weren't linked #58262 #57642

Whoops, thank you, wasn't aware of those issue reports

**Pull request merged**
