### PR TITLE
Reverts newcult

### PR DESCRIPTION
**Pull request by Buggy123**
Let's try this again.

### CODE REVIEW

**Comment by feemjmeem** [comment]
what part of all of the 'feature freeze' comments did you not understand in your first PR

**Comment by Bawhoppen** [comment]
uh bro you know, im for this but you fucked up in so many ways

**Comment by optimumtact** [comment]
how about you take some time out after your losing a cult round and then think about reverting.

**Comment by Buggy123** [comment]
Lots of people have said they don't like newcult.

**Comment by duncathan** [comment]
1. Feature freeze
2. Git gud
3. Don't you remake this again unless another maintainer says you can

**Comment by Buggy123** [comment]
Sorry, I fucked up the first PR and was fixing it.

**Pull request closed without merging**
