### PR TITLE
Adds some new plushies

### PR DESCRIPTION
**Pull request by TehZombehz**
:cl:
add: Several new plushie dolls are now available in toy crates.
/:cl:
plushies1
They are very cartoony, with comically oversized beady eyes and heads, just like regular cutesy plushies.
I felt like we could use some variety in the plushie toy selection for fun and may consider adding more functionality to plushies in the future.

If all goes well, I hope to work on:
- Slipping items into plushies secretly
- Making plushie bombs
- Crane machine
- Throwing the snake plushie at people to freak them out
- Wearing the snake plushie as a scarf

### CODE REVIEW

**Comment by optimumtact** [comment]
no player references

**Comment by ninjanomnom** [comment]
#30710 reworks plushes so you'd be best off either waiting for that to be finished or pr it to my branch

**Review by LetterJay — CHANGES_REQUESTED** [review]
Nevermind

**Comment by Xhuis** [comment]
This isn't a Citadel PR...?

**Comment by LetterJay** [comment]
For some reason my email relayed this to me as a Citadel PR....

**Comment by ExcessiveUseOfCobblestone** [comment]
Im setting my ghost as these.

**Comment by calzilla1** [comment]
Can you have a detachable tail for the lizard plushm

**Comment by Anonmare** [comment]
Can't wait to slip a remote signaller chem grenade filled with high explosive into a plushie and giving it to the captain for his birthday

**Comment by kilkun** [comment]
do not ruin the purity of the plushies

**Comment by CosmicScientist** [comment]
i want

**Comment by CosmicScientist** [comment]
in real life

**Comment by CosmicScientist** [comment]
is the carp plushie going to get an update?

**Comment by kilkun** [comment]
will we get dehydrated nuke ops?

Spray the plushie with water to spawn a GOAP enabled Nuke Op npc

**Comment by ExcessiveUseOfCobblestone** [comment]
>Can't wait to slip a remote signaller chem grenade filled with high explosive into a plushie and giving it to the captain for his birthday

omg these should have an internal storage for C4 and grenades [probably the same thing, I forget the 2 c4 paths.]

**Comment by Bawhoppen** [comment]
c4 is a subtype of grenades nowadays iirc

**Comment by Cheridan** [comment]
That syndi is adorable oh my god

As far as the sprites go I would just add an outline to them so they fit in better with everything else, as most sprites in the game have them

**Comment by MrROBUST** [comment]
Do want alien themed plush!

**Comment by Hatfish** [comment]
Are they huggable if you use them in-hand?

**Comment by AnturK** [comment]
Will need repathing as of #30710

**Review by ninjanomnom — APPROVED** [review]
👍

**Pull request merged**
