### PR TITLE
(okay, fixed my commit issue, ignore the last mistake)

### PR DESCRIPTION
**Pull request by Cuboos**
OH GOD I'M SORRY, IT WAS BANDIT'S IDEA, SHE HELD ME AT GUNPOINT.

### CODE REVIEW

**Comment by Supermichael777** [comment]
Close the last one, re-title "adds graphics to Orion trail", ~~KILL YOURSELF~~ and quit apologizing; this is a decent change.

**Comment by optimumtact** [comment]
@Supermichael777 did you even look at this PR?

**Comment by Cuboos** [comment]
NO, IT'S A HORRIBLE CHANGE. IT IS THE HARBINGER OF OUR DESTRUCTION.

**Comment by Supermichael777** [comment]
what
also what
also kill bandit ~~then yourself~~

**Comment by bgobandit** [comment]
honk honk honk honk honk

**Comment by Cuboos** [comment]
This gonna get merged any time soon? it doesn't conflict with anything.

**Comment by optimumtact** [comment]
I doubt it

**Comment by Razharas** [comment]
What is this?

**Comment by Razharas** [comment]
@Cuboos

**Comment by optimumtact** [comment]
@Razharas it replaces the rubber dunk honk with the duck sound meme
https://www.youtube.com/watch?v=gmECGJbf-JU

**Comment by Razharas** [comment]
Ah a short lived meme i see

**Comment by Razharas** [comment]
Denied

**Comment by Cuboos** [comment]
What the fuck? reopen this

**Comment by Koriath** [comment]
Lel, this is going in Hate, in the form of stacks of ducks that can be tied.

**Pull request closed without merging**
