### PR TITLE
Makes pipe layers better, also some cleanups

### LINKED ISSUE #40977: Layered piping extends past the tile they're on
Which means that if you have two tiles, both of which having a layered pipe on it but one being plating, and one having a proper floortile, it looks really really odd. This example has a door in it, which just makes it look even worse:
image
image

[Reproduction]: # Put layered piping on 2 tiles, then put a floortile over one but not the other. For even worse results, put a door on the plating tile

And yes I used the hidden subtype, not visible.

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
fix: Layered pipes no longer stick out of their tile, also vents and other machines will always be in the middle of the tile.
imageadd: Layer manifold now loos like an adaptor.
/:cl:

* Some pipe mapping helpers were made into macros so maintaning things is easier
* Some unused icons were removed.
* A lot of icons were added, so that pipe layering looks better.
* Layer manifold renamed to layer adaptor and resprited to look more like an adaptor.

Fixes #40977

image
image

### CODE REVIEW

**Comment by yoyobatty** [comment]
Does this fix layer 1 and 3 pipes sticking out of floor tiles with windows and walls?

**Comment by Dennok** [comment]
Why you replace Initialize() to New()?

**Comment by nicbn** [comment]
@yoyobatty yes

@Dennok I replaced some New() with Initialize() and I got some runtimes, so I made it back into New() in the latest commits

**Comment by Barhandar** [comment]
>also vents and other machines will always be in the middle of the tile.

Prevents porting vg's five-vents-in-same-tile feature. Additionally might have visual identification issues since you can overlay these with pipes on a different layer, and that vent pipe connection looks _ugly_.

**Comment by Dennok** [comment]
> > also vents and other machines will always be in the middle of the tile.
> 
> Prevents porting vg's five-vents-in-same-tile feature. Additionally might have visual identification issues since you can overlay these with pipes on a different layer, and that vent pipe connection looks _ugly_.

I think here dont want to have five-vents-in-same-tile feature

**Comment by nicbn** [comment]
We opted in for not having multiple vents on the same tile when layers were added

You complain about the connection being ugly but the vents being disaligned are one thousand times uglier, also feel free to PR new sprites if you really think it's that bad

Identification is not hard with pipes over the vents because the caps (connections) are distinctive enough

**Comment by lolman360** [comment]
will this still allow you to place pipes/remove pipes on walls (for example, SM or toxins chamber)

**Comment by nicbn** [comment]
Yes

**Comment by Dennok** [comment]
> Does this fix layer 1 and 3 pipes sticking out of floor tiles with windows and walls?

How i see .Yes.

**Comment by Dennok** [comment]
Oh, some bad
image

**Review by SpaceManiac — APPROVED** [review]
Boy is my atmoscode rusty but this looks so much better than before. Thank you.

**Pull request merged**
