### PR TITLE
add note about singulo config

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Review by LemonInTheDark — APPROVED** [review]

**Comment by tralezab** [comment]
MSO let's be honest we should probably let this config go
There's a trillion ways to completely dumpster an entire station in moments much faster than singulo possession can

**Comment by MrStonedOne** [comment]
Our configs will continue to support downstreams (either now or in the future) that want to use the singulo engine as the primary engine.

**Comment by MrStonedOne** [comment]
I think you misunderstand why the config exists.

I'm not going to tell you because i'm getting sick and fucking tired of people making snap assumptions and then railing against something based on that snap assumption.

**Comment by MrStonedOne** [comment]
You are right, a config designed to limit admins ability to damage the station or ruin the round doesn't make sense.

Maybe that should have been your hint you were missing a key piece of info?

**Comment by msgerbs** [comment]
Thanks for taking the opportunity to educate those of us not making snap assumptions, I appreciate it.

**Pull request merged**
