### PR TITLE
Fixes deathgasp and gasping not showing up

### PR DESCRIPTION
**Pull request by ChangelingRain**
help emote is crap and doesn't use ..() properly anywhere

### CODE REVIEW

**Comment by optimumtact** [comment]
#21444 mate

**Comment by ChangelingRain** [comment]
That one doesn't fix the bug properly though

**Comment by Cyberboss** [comment]
Why are we being snowflakey with deathgasp when we can just gasp THEN die?

**Comment by ChangelingRain** [comment]
Oh wait I think this fixes gasping, too. Ugh, emotes.

**Comment by Cyberboss** [comment]
Alright @optimumtact merge this one

**Pull request merged**
