### PR TITLE
[WIP] Pickup, drop, and equip sounds

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Adds pick up, drop, and equip sound effects.
[Check it out here, epic gamers!](https://www.youtube.com/watch?v=nc0CaWkUfRs)
That's actually a bit earlier of a version where the volume of pickup and drop was different for some reason. I know somebody is probably going to complain about that, so don't.

Current sound effects added:

Pickup/Drop:
- Cloth (jumpsuits, coats, etc.)
- Multitool
- Wrench
- Crowbar
- Screwdriver
- Wirecutters
- Welding Tool
- Toolbox
- Disks (I couldn't find a floppy disk, jewel case will have to do)
- Cardboard boxes
- Matchboxes
- Ammo Boxes
- Belts
- Paper

Equip:
- Jumpsuit
- Belt

A sneaky new extra sound is in as well, specially tuned for your immershuns

All sounds are mono, 41khz, and ogg compressed.

Also some 0/1 to FALSE/TRUE refactoring.

## Why It's Good For The Game

Sounds increase muh immersions.

## Changelog
:cl:
soundadd: Shitloads of new sound effects for item pickup and dropping and clothing equipping. 
/:cl:

Throwing this PR up early so that code concerns can be worked out early.

I'm gonna record and mix a shitload more sounds current count is 33.

### CODE REVIEW

**Comment by Barhandar** [comment]
Reee I don't like change and this sounds like change to muh immershun.

**Comment by actioninja** [comment]
go away barhandar you dont like anything

**Comment by Tlaltecuhtli** [comment]
> go away barhandar you dont like anything

**Comment by Razharas** [comment]
Now this is the perfect target for datum outputs

**Comment by Razharas** [comment]
@Militaires

**Comment by MrDoomBringer** [comment]
wtf i like actionninja now?

**Comment by Ratvar** [comment]
Is it possible to make pickup sound pwewewence?

**Comment by actioninja** [comment]
Yeah, it's already in the game. It's called muting your audio.

**Comment by ATH1909** [comment]
It's like footsteps all over again.

I'm not sure whether I love or hate this PR.

**Comment by PKPenguin321** [comment]
A few of these seem pretty over exaggerated (disk and wrench ones kind of stuck out in particular), but I like it overall and disagreeable ones can always be changed later.

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by actioninja** [comment]
fun police

**Comment by MrDoomBringer** [comment]
image
Thanks for updating the title, @actioninja. It's important to have properly descriptive PR titles and or descriptions, like this one

**Comment by actioninja** [comment]
image
the tyranny of the fruit

**Comment by Tlaltecuhtli** [comment]
just add death grips samples when picking up objects so oranges wont get mad

**Comment by nicbn** [comment]
Pls try to keep file size low. Use some strong compression when there's not huge issue on losing some sound quality.

**Comment by qbmax32** [comment]
this is very epic but i would make an option to disable them to prevent the auts from whining because they hate change

**Comment by ExcessiveUseOfCobblestone** [comment]
reminder: posts not made by those in the "member" usergroup should be considered but not acted upon unless confirmed by someone in the "member" usergroup

**Comment by WJohn** [comment]
Fantastic stuff. Always wanted more sound effects, and sounds and atmosphere help people get into it more.

**Comment by Dorsisdwarf** [comment]
Whats the default sound

**Comment by actioninja** [comment]
Nothing at the moment. Default is not having a sound. Not sure if I should have a default or not.

**Comment by PKPenguin321** [comment]
heres your default sound bro https://file.house/dN0i.ogg

**Comment by actioninja** [comment]
@PKPenguin321 @Tlaltecuhtli https://www.youtube.com/watch?v=F1bHIKJZadM&

**Comment by Farquaar** [comment]
This has a lot of potential for fun.

**Comment by actioninja** [comment]
I've been being lazy as fuck and not recording new sounds, I'll try to get some new stuff done tonight.

**Comment by actioninja** [comment]
this will be back when I get the motivation to actually record sounds again.

**Comment by PKPenguin321** [comment]
Bruh Pickup/drop sound effect #2

**Pull request closed without merging**
