### PR TITLE
Remove calls to a private NanoUI proc from Chemistry-Machinery

### PR DESCRIPTION
**Pull request by neersighted**
Also mark procs as private (because they should have been private the whole time).

Get off my lawn! :angry:

### CODE REVIEW

**Comment by duncathan** [comment]
>private procs in byond

is this the world I remember?

**Comment by neersighted** [comment]
Oh hush, its internal to NanoUI and should not be used by anything but NanoUI code.

**Comment by optimumtact** [comment]
We use the pythonic version of private, which is we wont make it private and just insult you when you call it :laughing:

**Comment by neersighted** [comment]
Because @tkdrg is a derp.

**Comment by tkdrg** [comment]
hey i only copy pasted them from dispensers into the heaters
not my bug :tm:

**Pull request merged**
