### PR TITLE
Renames neurotoxin2 (the toxin, not the drink)

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: The 'neurotoxin2' toxin has been renamed to Fentanyl.
/:cl:

Having a drink called neurotoxin, a toxin called neurotoxin AND aliens that spit neurotoxin really cooks my goose. The only thing they have in common is that they are bad for you.

Instead of touching the other two, I've renamed the toxin that nobody ever mixes to Fentanyl.

### CODE REVIEW

**Comment by DaedalusGame** [comment]
technically they all cause brain damage probably so they are all neurotoxins i wonder if they work on braindead people because they clearly should be immune

**Comment by 81Denton** [comment]
More toxins should cause brain damage, XDTM's system is pretty nice

**Comment by DaedalusGame** [comment]
my only experience with neurotoxin2 is that i tried to put a monkey to sleep with it and he started chimping out and stunning me with voice of god

**Review by Cyberboss — APPROVED** [review]

**Comment by Fox-McCloud** [comment]
better to re-name the drink than the actual poison.

**Comment by 81Denton** [comment]
Give a reason why

**Comment by MoreRobustThanYou** [comment]
@Fox-McCloud the actual poison is worse than the drink

**Comment by Fox-McCloud** [comment]
Yes, exactly, which is why I believe the poison/toxin should retain its name, while the drink should be changed.

From a player perspective, when you hear "neurotoxin", your first thought is "oh, geeze, it's going to kill me" as opposed to "oh, gee, this is a gimmicky bar drink!"

**Comment by DaedalusGame** [comment]
no as in, the gimmicky bar drink is way more dangerous than the poison

**Comment by ShizCalev** [comment]
Fentanyl is an anesthetic akin to morphine, why do you feel it a good name for neurotoxin?

**Comment by 81Denton** [comment]
Iirc Neurotoxins don't work like neurotoxins2 does, but I suppose that giving it a "realistic" name would be better.
Anatoxin would be too close to amatoxin. How about Tetrodotoxin?

**Comment by DaedalusGame** [comment]
Because it makes people sleep, ShizCalev

**Comment by 81Denton** [comment]
Yeah what DaedalusGame said, neurotoxin2 works more like a sedative than a paralyzing neurotoxin.

**Comment by ShizCalev** [comment]
what a meme chemical name

**Comment by MoreRobustThanYou** [comment]
neurotoxin toxin is like morphine + shitty version of that super easy to make brain damage chem that kills you with 50u

**Comment by GuyonBroadway** [comment]
The bar drink is leauges more dangerous as it stuns for 6seconds + however long its in your system. And cuz the game is that stuns are the be all and end all of combat its basically a killchem.

**Comment by DaedalusGame** [comment]
what this guy said he's a good chem main

**Pull request merged**
