### PR TITLE
Sniper rounds now blow off limbs

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: yackemflam
add: The standard rounds now blow off limbs. Happy hunting!
/:cl:

### CODE REVIEW

**Comment by ma44** [comment]
Hopefully nuke ops would actually buy snipars now and quickscope everyone

**Comment by xxalpha** [comment]
It's the AWP cancer all over again.

**Comment by KorPhaeron** [comment]
Should probably be the normal sniper round only, wouldn't be fun to suddenly lose a leg through a wall and the penetrator is already the best round by far

**Comment by PKPenguin321** [comment]
yeah penetrator rounds are already nuts

**Comment by KorPhaeron** [comment]
Losing limbs from offscreen might still be dumb but nobody actually uses the sniper so lets see how it goes

**Comment by yackemflam** [comment]
You gave the wizard a weapon that has the same range, infinite ammo, AND has a faster firing rate but that isn't any of my business.

**Comment by KorPhaeron** [comment]
>wizard
>the same as a nuke op

Okay

**Comment by yackemflam** [comment]
Ops are still severely limited in gear compared to the wiz.

**Comment by KorPhaeron** [comment]
Yes exactly

**Comment by KorPhaeron** [comment]
I don't know why you're trying to get in an argument with me after I merged your PR either

**Comment by PKPenguin321** [comment]
Wizard should sometimes get the objective to detonate the on-station nuke

**Pull request merged**
