### PR TITLE
Puts Wags-His-Tail and Eats-The-Roaches back in Delta's janitor closet (extremely important)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Apparently I removed BOTH by accident and didn't notice

## Why It's Good For The Game

Missing lizards :(

## Changelog

:cl: Melbert
fix: Wags-His-Tail and Eats-The-Roaches have wiggled their way back from a deep space expedition to the janitorial closet of Deltastation.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
i have to hold myself back from speedmerging this

**Comment by JohnFulpWillard** [comment]
2 pets for the same department on the same map :(

**Comment by san7890** [comment]
> 2 pets for the same department on the same map :(

🖕 this is mapping soul don't impede on my domain https://youtu.be/61pqMZr1ps0?t=55

**Comment by MrMelbert** [comment]
> 2 pets for the same department on the same map :(

ok well go back in time and talk to Okand

**Comment by Jolly-66** [comment]
> 2 pets for the same department on the same map :(

Two of the BEST pets, you mean

**Comment by optimumtact** [comment]
not a bug, closed

**Comment by san7890** [comment]
> not a bug, closed

dies-of-death-compressed

**Pull request merged**
