### PR TITLE
Gives heads of staff disablers

### PR DESCRIPTION
**Pull request by Bawhoppen**
Kor suggested on the forums we give heads of staff eguns, however I think eguns are probably too much, just a few disablers should help out instead

### CODE REVIEW

**Comment by Robustin** [comment]
No, just no. I don't even understand what this hopes to accomplish.

**Comment by Bawhoppen** [comment]
robustin you can't talk you make the most shit prs with horrible balance all the time
"hurr durr lets give everyone guns on lowpop"

**Comment by Robustin** [comment]
Id take guns that do 20 damage every 3 seconds over a gun that "kills" people in one second. The fact you even think those things are comparable shows how little you grasp the concept of balance.

**Comment by Bawhoppen** [comment]
>robustin

>telling me I don't know balance

lmao

**Comment by Dorsisdwarf** [comment]
Hell no

**Comment by KazeEspada** [comment]
Unless you are super robust, most people dont play heads cause of rev.

**Comment by AdamElTablawy** [comment]
no, this encourages sec officer CMO, plus the disabler has a really damn high clip

**Comment by Supermichael777** [comment]
because what the station needs is more stuns

**Comment by lzimann** [comment]
more like git gud and use your baton

**Comment by Niknakflak** [comment]
>Some of the thumbs downers are greytiders

purge

**Comment by xxalpha** [comment]
:-1:

The Security department exists.

**Comment by jughu** [comment]
Lowee the clip to 6 shots so you just can pull 1 stun off

**Comment by Dorsisdwarf** [comment]
Uh, disablers are 3 shot stuns

**Comment by jughu** [comment]
>implying you hit all the shots

**Comment by PKPenguin321** [comment]
uh @Bawhoppen a core part of kor's suggestion was that by doing this we'd remove the eguns from the armory, mainly to spread those guns out
this just adds more guns and doesn't solve the problem kor was getting at at all

**Comment by Bawhoppen** [comment]
i didn't like that part of the suggestion

**Comment by PKPenguin321** [comment]
i feel it's wrong to attribute this PR to Kor then since it's not really his suggestion at this point

**Comment by Bawhoppen** [comment]
it's a modified suggestion to give all the heads sidearms

**Comment by PKPenguin321** [comment]
well in that case i dislike this PR
it just adds more guns to roles that are already pretty good, not to mention that the disabler gun thingy has like 40 gorillion shots

**Comment by jughu** [comment]
Just make it 3/6 shot disablers so you barely can get a stun off it if your lucky

**Comment by Bawhoppen** [comment]
ree hugbox

**Pull request closed without merging**
