### PR TITLE
Insignificant sprite improvements

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

This PR changes up some sprites exclusively for the sake of looks and a tiny bit of more detail.

## Why It's Good For The Game

Buttons are slightly easier to click on and differentiated. They also have animations that play when you use them. As for the other stuff, it looks good.

## Changelog
:cl:
tweak: Large welding fuel tanks are now red instead of white. Large tanks now also have a difference in size.
tweak: Cell chargers, PKA Modkits, light switches and buttons have been touched up a bit.
tweak: The incinerator button no longer looks like just a light switch
/:cl:
imagen

### CODE REVIEW

**Comment by Winterous** [comment]
Honestly I think the wall switches and cell charger look worse.

**Comment by Investigator77** [comment]
>Honestly I think the wall switches and cell charger look worse.
Cell charger used to have 3 colours with no defined outline let alone shading of any kind

**Comment by Winterous** [comment]
> 
> Cell charger used to have 3 colours with no defined outline let alone shading of any kind

But this one is round for some reason, which is ugly.

**Review by Twaticus — APPROVED** [review]
not too worried about the switch changes, theyre gonna need another overhaul soon for our new walls

looks good

**Pull request merged**
