### PR TITLE
Tweaks armory layout slightly

### PR DESCRIPTION
**Pull request by Bawhoppen**
ss 2016-04-07 at 03 16 44

this moves some of the stuff around a bit to have to make the layout better aswell as being visually being nicer, the armory now also comes stocked with some basic armor too

### CODE REVIEW

**Comment by TankNut** [comment]
:+1: Now I won't have to dive into the officer lockers when grabbing armor as warden/HoS

**Comment by KazeEspada** [comment]
No, those tables block the c4 entry point

**Comment by Supermichael777** [comment]
you can just push the locker down it takes no time at all.

**Comment by coiax** [comment]
Seems good, like the firing pins being a little more prominent.
:+1:

**Comment by KorPhaeron** [comment]
Thanks, I was too lazy and did text edits for replacing those barriers

**Pull request merged**
