### PR TITLE
tgui: Converts some uselocal -> usestate

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Title. Had some extra time, converted some UIs to use usestate/usecontext rather than uselocalstate.

PAI available software interface was adjusted a little.

<details>
<summary>pictures</summary>

before
Screenshot 2024-05-20 155616

after
Screenshot 2024-05-20 155927

image

</details>

## Why It's Good For The Game
Uselocalstate is deprecated in favor of using plain react hooks.
## Changelog
:cl:
fix: Slightly cleaned up PAI software downloads interface
/:cl:

### CODE REVIEW

**Comment by 00-Steven** [comment]
You have a picture of what the pAI software downloads interface looks like with this pr?

**Comment by jlsnow301** [comment]
> You have a picture of what the pAI software downloads interface looks like with this pr?

pictures in the desc now. button felt off. tooltip now covers the entire row

**Comment by 00-Steven** [comment]
baller, thank you

**Comment by Momo8289** [comment]
The icons in the available software buttons are off centre :(

**Pull request merged**
