### PR TITLE
Fixes the revenant drain beam going into the target instead of out of it

### PR DESCRIPTION
**Pull request by ChangelingRain**
Was the Beam() set up like that just to prevent this, was Xhuis unrobust at editing animated sprites, who knows.
BEFORE
IT IS ALWAYS BEST TO COMPLY
AFTER
WITH ARAN'S STUPID REQUESTS

### CODE REVIEW

**Comment by Aranclanos** [comment]
post an image of before and after in the OP

**Comment by Bawhoppen** [comment]
wait wasn't this intended? because the rev is like extending its beam into it

**Comment by Anonus** [comment]
Nope, it happened when I made a fix to the beam getting weird when the target was dragged off and was not intended.

**Comment by Bawhoppen** [comment]
ruining ERevenantP

**Pull request merged**
