### PR TITLE
You can now lick feet

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
You can now lick someone's feet, provided they are lying down, have no shoes on and you target one of their legs. It also lowers their firestacks because you are wetting them.

## Why It's Good For The Game
Fetish content, also adds a new way to extinguish people

## Changelog
:cl:
add: You can now lick feet
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Shit like this is why we banished people to Australia in the first place!

**Comment by KomradeSpectre** [comment]
Why on god's green earth, did you think this was a good idea?

**Comment by CakeQ** [comment]
what in the name of fuck

**Comment by TheVekter** [comment]
Get the fuck out of here.

**Comment by CRITAWAKETS** [comment]
NOW THIS IS **DOUBLE HERESY**

**Comment by Firecage** [comment]
Mmmm....

**Comment by very-polite** [comment]
excuse me what the fuck

**Comment by TheChosenEvilOne** [comment]
ahhahahahha, what

**Comment by FancyCyclops** [comment]
image

**Comment by 81Denton** [comment]
what

**Comment by MCterra10** [comment]
we had a good run lads

**Comment by MCterra10** [comment]
I'm getting 10 bucks for this shit, time to purge my computer of it

**Comment by Exavere** [comment]
**Ryan Cobb Intensifies**

**Comment by Twaticus** [comment]
Ryan Cobb loooooooooooooooves feet. He simply cannot get enough of them. When he thinks of those stinking, pungent appendages that have probably been walked on and drenched in the lovely nectar of sweat all day he can't help but feel ecstatic. Those little toes hanging off your feet? Ryan Cobb would love to suck on each of those little piggies because he himself, is a degenerate sec-main piggy.

**Comment by 81Denton** [comment]
all of you need jesus

**Comment by 81Denton** [comment]
this is also why we should cut australia's fiber cable

**Comment by MCterra10** [comment]
lol

**Comment by kevinz000** [comment]
jesus christ did they seriously try to port it to citadel

**Pull request closed without merging**
