### PR TITLE
The Identity System w/ tweaks

### PR DESCRIPTION
**Pull request by JJRcop**
Previous PR: #23693

Please put feedback on the concept of the system in [this forum thread](https://tgstation13.org/phpBB/viewtopic.php?f=9&t=9598), and keep this github page for code discussion only.

:cl:
add: Adds the identity system, which changes the way you see names.
add: Instead of instantly knowing everyone's name, you have to learn their names. This can be done by examining them, or manually setting their name with the new identity manager. <b><a href='https://tgstation13.org/wiki/Identity'>More info here.</a></b>
/:cl:

You no longer see everyone's names instantly when they speak, what you see is dependent of how you remember their name.
I recommend you read the [ugly wiki article](https://tgstation13.org/wiki/User:JJRcop/Identity) I wrote as that is more comprehensive (Hopefully it will be rewritten by someone who knows what they are doing :))

- [X] Complete code for identity system (subject to change from feedback)
- [X] Initial code approved
  - [x] examine needs to be better
  - [x] click on names in chat to rename them, don't use the identity manager for this, but keep it around still
  - [x] make the names in chat not blue all the time so that accents are visible
  - [x] list lengths should be defines
  - [x] move global regex vars to be static vars in the procs
  - [x] raz doesn't like var/_these_vars
  ~limited range for faceprint gathering?~
  - [x] config file for pre-knowns
  - [x] add accents
  ~some form of help~
  - [x] potential garbage issues for identity manager
- [X] Retrofitting for logging
- [x] Retrofitting for visible_message, show_message, audible_message
- [x] Retrofitting for to_chat
- [x] fix "subjextsd=list" aka various misspellings of "subjects"
- [x] identity list garbage collection
- [ ] Adjust to feedback

### CODE REVIEW

**Comment by Shadowlight213** [comment]
So, it's testmerge ready?
*extends finger towards testmerge button*

**Comment by ChemicalRascal** [comment]
Awww man I'm so keen

**Comment by Niknakflak** [comment]
Eh, even with all these changes, I still think it's going to be bad

**Comment by francinum** [comment]
Please for the love of god stop trying. This is a bad idea.

**Comment by Anonymous583** [comment]
Holy fuck, no, no, NO. Do not put this in. Security as a whole will stop existing because of how annoying it will be to get a name from anybody, and Changelings will be unstoppable.

**Comment by JJRcop** [comment]
Please use the [forum post](https://tgstation13.org/phpBB/viewtopic.php?f=9&t=9598) for discussion on the concept itself, i've already heard most everyone's opinions already and have taken them into consideration. Use this GitHub page for code related discussion.

**Comment by Davidj361** [comment]
These tags are just too fucking hilarious: Do Not Merge, Feature, FUCK, Merge Conflict, Work In Progress

**Comment by JJRcop** [comment]
Had a busy weekend, I can focus my time on the retrofitting now though.

**Comment by Shadowlight213** [comment]
You know, if this gets merged, but disabled in config, it would be interesting to have a list of known names stored in player's character files, so they have to meet new people.

**Comment by JJRcop** [comment]
This may take a bit longer than I expected, ETA mid next week (factoring in planned activities away from the computer)

I hope I'm wrong

**Comment by ExcessiveUseOfCobblestone** [comment]
stale?

**Comment by JJRcop** [comment]
no

**Comment by JJRcop** [comment]
# TESTMERGE READY

**Comment by Ninja137** [comment]
TESTMERGE READY

AHAHAHAHAHAHAHA ARE YOU FUCKING SERIOUS KID

**Comment by optimumtact** [comment]
Just a note: You don't get to complain that this is test merged, just give feedback on issues/concerns.

The players voted for an extended test period.

**Comment by shornwolf** [comment]
>The players voted for an extended test period.

As far as I can tell there was a unilateral "WHAT IS THIS GARBAGE" when it was testmerged, meaning nobody voted for this shit.

**Comment by optimumtact** [comment]
@shornwolf I will direct you to the following poll
http://www.ss13.eu/tgdb/tg/ingamepolls.php#p161

**Comment by Ninja137** [comment]
The IC name font is different from all other fonts in a way that does not fit. It is a different color and size, beyond just being a different actual font. It feels out of place and just downright fucking weird.

You are unable to identify yourself in any way. If you talk and examine yourself, it still shows as just Person. If someone near you talks and you examine them, it ALSO appears to just display as Person from what I have seen. I assume that second part is not intended, but I can't honestly tell with this.

This is going to make it absolute hell on earth to play as Sec, and god fucking knows we've already got enough problems with Sec players being drooling retards who're incapable of even basic thought or reasoning. I absolutely gurantee that this is going to lead to problems related to Sec.

When this was added tonight, literally the entire server was against it. There was not a single person that wanted it. The admins forced the round to end early, because it was incredibly disruptive, annoying, and generally just tedious and unfun to have around. It has since been immediately removed.

If this is going to be merged as a test for an entire month, it needs some serious fucking fixing in basically the entire thing. And even then, I still don't think that it would be a worthwhile addition. It's a massive amount of tedium and bullshit to get an incredibly minor benefit, and it's just not worth it.

**Comment by optimumtact** [comment]
Don't worry, after the month is up you'll have a chance to vote again.

**Comment by Ninja137** [comment]
Honestly, I'm not sure if you're retarded here or what. It got merged, people HATE it, and it's in clear need of a ton of fixing. 

But hey, that one poll that went through got a few votes because nobody had seen how absolutely shitfuck terrible it is, so now it's time to ruin an entire month of playing for everyone, right?

**Comment by PKPenguin321** [comment]
Radio needs to show names, I don't want to test merge this (much less merge merge it) if every round is going to be unknowns spamming WGW.

**Comment by optimumtact** [comment]
Right so you're going to discount the fact that just under 300 people voted in that last poll? and remember that identity system was just as buggy when that poll was run.

Basically I have data in hand here that say's that at least 56% of the active player base think this idea is worthy of further development. I'm not going to let the remaining 44% wag the dog

**Comment by Ninja137** [comment]
The vote won by just barely about 10%, Oranges. Unless this system actually gets fixed up and made into a less-fucked version, there's zero reason to try and ruin an entire month's worth of rounds.

To note, I like the idea of the system. I think it has some concerns about it enabling valids a lot easier, I think it's going to end with a lot of grief, I think it's going to make Sec a lot harder to do, but I like the concept.

However, the current implementation is all but non-functional. It looks downright fucking weird as mentioned before, it's got definite bugs in that you can't identify yourself and that interactions with others are currently not displaying names even after examining, and the entire server turned into a pillar of salt when it was tested because it seriously does appear to be a massively larger amount of work/effort for an incredibly marginal benefit that isn't fully worth it.

**Comment by optimumtact** [comment]
I think you're confused, these test merges are to shake out bugs, the gameplay evaluation period has not even begun - That will entail the code actually being merged to master for the month period and then either reverted or left in depending on the final poll.

**Comment by PKPenguin321** [comment]
To make myself clearer: I will actively avoid allowing this to be testmerged and ran on the servers as long as the radio thing is still in (unless another headmin/MSO wants to step in here).

**Comment by shornwolf** [comment]
>the entire server turned into a pillar of salt when it was tested

Understatement of the year. OOC was moving so fast with rage I couldn't read it all.

**Comment by optimumtact** [comment]
@PKPenguin321 can you follow up with the host and other headmins on that or should I?

I'm happy for headmins to weigh in on code but I'd rather they all got involved than just one person respresenting their opinion as being final, especially when you're elected as a triumvirate.

**Comment by PKPenguin321** [comment]
I will, no worries
Radio unknowns are kind of gamebreaking from what I can tell however, and I'm really reluctant to push something that just ruins the game

**Comment by BeeSting12** [comment]
A bad feature is still bad no matter how good the code is.

**Comment by Bawhoppen** [comment]
Conceptually good but way too overcomplicated

**Comment by InsaneHyena** [comment]
Stop being whiny babies. Give it a chance.

**Comment by francinum** [comment]
@InsaneHyena We did. It was tried several times. It's not a good feature.

**Comment by JJRcop** [comment]
Please post feedback on the concept and end-user experience in this forum thread: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=9598

This github page should be used for code related feedback only.

**Comment by optimumtact** [comment]
Right well this is dead in the water, you need to rethink your whole approach and figure out a way to introduce this bit by bit so we can test it in smaller components and you have a chance of not causing 20 billion bugs that make people hate your idea.

**Comment by JJRcop** [comment]
I'm going to continue to work on this, and try to get it to a state where we can testmerge again. I will try to figure out ways I can split it up, but at the moment it doesn't look like I can do that. Very sorry this has taken this long.

**Comment by optimumtact** [comment]
The thing is, unless you get it to a non bugged state you wont' get any useful feedback from the test merges other than yelling, so you'll never progress anywhere without somehow bringing it in bit by bit.

**Comment by RemieRichards** [comment]
people don't just hate it because of the bugs, they just hate it.
take the hint.

**Comment by PKPenguin321** [comment]
For real

**Comment by ChemicalRascal** [comment]
I too hate new things

JJ, I might suggest you split off accents first -- that's information that
can be displayed even with knowing people's identities (ergo, without the
rest of the system). If you can find a way to do that without screwing with
people's fonts and colours, that might be a good first step from which to
work from.

Although it would also technically be a balance change because then the
lavaland comms agent can't pretend to be the supermatter shard anymore but
anyway

**Pull request closed without merging**
