### PR TITLE
Adds the Wizard Academy as a Space Ruin [WIP]

### PR DESCRIPTION
**Pull request by Firecage**
This PR slightly redesigns the Wizard Academy so it can function as a Space Ruin, since we no longer use the Gateway after all.

I would appreciate it if you can inform me what else I should change on the map so it works better as a Space Ruin. I still need to do testing if some things like that Wizard Academy Defender still works though. If I can figure out how to test Ruins out.

Also, I switched out its wand of polymorph for a wand of healing. Would be annoying if a non antag makes people into Syndiborgs or Xenos. An Altruistic wand is better.

:cl: Firecage
add: We at the NanoTrasen Galactic Activity Monitoring Station(NGAMS) has recently detected rapid fluctuation in Space Time which our scientists suspects can only be linked to some advanced form of magic. NanoTrasen Security Forces now suspects involvement from the fringe group known as the Wizard Federation. The signatures appears to originate from deep space, the exact coordinates being [REDACTED].
/:cl:
procreatory object upsilon 2016-12-05 215659
procreatory object upsilon 2016-12-05 215644
procreatory object upsilon 2016-12-05 215616
procreatory object upsilon 2016-12-05 215554

### CODE REVIEW

**Comment by WJohn** [comment]
If this is an identical copy to the wizard academy away mission, then it is going to be GIGANTIC. Also extremely empty, super lacking in detail and quality, and just plain ugly.

**Comment by Firecage** [comment]
I am actually still working on it. the entire gateway room has been scrapped and replaced with a garden filled with plants and animals which leads inside.

Wjohn, also, that was the original Wizard Academy. I can't remember who, but someone did add a bit more detail to it. A Wizard Academy defender, mobs, 'secret' areas you go to via ruins which includes a laboratory?, an engine, a vault, and a cellar.

Also, Wjohn, how the heck can I capture a screenshot of the entire map at once?

**Comment by WJohn** [comment]
You can't usually do it in one go, unless you do it from in game. In that case, use the verb "change-view-range" and set it to 128. Set your view to stretch (top left window) and take a pic with I believe f2. It should result in a huge 100% resolution picture.

**Comment by Firecage** [comment]
Thanks, I'le try.

**Comment by Firecage** [comment]
@WJohn Okay, the images are uploaded.

**Comment by Crushtoe** [comment]
It lookss

**Comment by Armhulen** [comment]
Replace the hotel with this.

**Comment by Crushtoe** [comment]
That's a horrible idea. The hotel is great compared to this.

**Comment by FantasticFwoosh** [comment]
I don't think recycling the wizard away map really brings anything to improve it.

> @Crushtoe calling the hotel great is a stretch, the hotel still has the issue of being a 100% RP ruin and dry on gameplay & also huge like a away mission so it feels a little like everything lines the walls but its empty in the middle.

> What is the plan for wizards to actually do? Unless there's some kind of PR addition or mixture of mechanics/tools in the base for wizards alone, i won't really be sold on a bunch of wiznerd-greifers with quasi dangerous wands & recharge spells, especially if they try to get off station.

Using it as inspiration for a new ruin = totally fine given that in the existing map there is the same lack of detail (super huge bathrooms etc.) and you could do it on a much smaller & elaborate scale. I like the multiple asteroid rooms but i feel like they should be connected somehow and useful (rune teleports?).

**Comment by Firecage** [comment]
Fantastic, they were already connected via 'runes'(Technically ladders using the sprites of runes). One of a cellar, one of the 'engine', one is a vault, and one is a lab???(or something)

**Comment by Armhulen** [comment]
there's a wand of polymorph but i think op changed that, not that I'm complaining.

@Crushtoe hahaha holy shit

**Comment by Shadowlight213** [comment]
Wizard academy was a horrible lootfest map.

**Comment by KorPhaeron** [comment]
No it wasn't, it barely had anything good vs how many people died to it.

This is pointless to add as a space ruin though, you're never going to organize enough people to go clear it.

**Comment by WJohn** [comment]
Yeah this is not a good space ruin. It's gigantic and empty and follows the trope of tons of loot and tons of death.

**Comment by KorPhaeron** [comment]
>tons of loot

But it avoids that by having wizards (you can't loot spells!) instead of droping c20rs everywhere

**Comment by ExcessiveUseOfCobblestone** [comment]
Legitimate Question, do people even explore space regularly anymore?

**Comment by KorPhaeron** [comment]
no

**Comment by Firecage** [comment]
So. Should I keep this open and continue to tweak or @KorPhaeron, or just close it?

**Comment by Firecage** [comment]
Eh. I think next time instead of trying to port an awaymission over to being a ruin. I will instead try to craft my own space/lava ruin which is better than some of the meme ones we currently have. And due to the lack of support for the Wizard Academy, I shall be closing this PR.

Thanks for your time looking at this guys.

**Pull request closed without merging**
