### PR TITLE
[DRAFT] Industrial Fundamentals - Or That Time I Reworked 1/5th of <Metastation>

### PR DESCRIPTION
**Pull request by Zytolg**
### A long time ago in a space station far, far away...

OLD NASTYSTATION

### And now the continuation...

METAENGPRSTUFF

## Why It's Good For The Game

Quite a few points here:
-Personally, I'm tired of peoples only solutions to inherit problems with jobs being to simply 'Make the Room Bigger'. It's not a solution. If you need space then it's a clear indication that things within a room finally need to be compartmentalized. Aesthetically, SS13 draws heavily from classical scifi series such as Alien, Star Wars, Mobile Suit Gundam, Stargate, Cowboy Beebop, and there's even some Star Trek. That list isn't exhaustive either, but illustrates my next point. Huge Spaces that you could fit a ballroom in and host the Solar Gala aren't typical of our aesthetic. Spaces in each of these respective series are purpose defined (form follows function). When it comes to altering spaces on any of our maps, we need to properly consider that the spaces are reasonable defined. So when a change to Meta's Atmos makes it a larger space than **The Kilostaiton Hangar** and **Cargobay** combined, we've fucked up somewhere. 
-Compartmentalization is a valid solution to most of these things. If you need more space, it's likely that too much is going on for one room to handle. At this point in time, it is my belief that atmospherics has long since passed that threshold. The Job of Atmospherics involves tasks such as 1) Gas Production, 2) Gas Distribution, 3) Fire Fighting, 4) Turbine Power Generation, 5) HFR Gimmiks, 6) Crystalizer (what do it do), and 7) Personal Projects; Along with monitoring systems and tools for each of these. Fitting this all into 1 room is insanity. We have 7 tasks, so why not 7 rooms? It doesn't even need to be 7, just compartmentalized to a reasonable degree. 
-Adding nuance back into the game. Engineering feels stale. I think it's mainly because the original layouts of these things were considerate of an external power source, but we've long since shifted away from the Singulo/Tesla. It's finally time for the spaces to reflect that. Twisting hallways and purpose driven rooms to give a tight industrial feel, and a decal redesign from the top-down. Engineering isn't just a department anymore. It's the beating heart of the station- it's time to reflect that. 
-Of course I redid the engine too. Having atmos only receive these changes would have thrown off the whole aesthetic of the location. Everything feels nicely incorporated and there is room planned for @Ghilker Engine Turbines whenever those happen. 
-Expanded maint. Yeah, you maint lovers get double the maint on the starboard side. Go touch grass nerds.
-Finally, I thought it was time that somebody used pipe layers.

Attention Atmos players:
The biggest complaint I hear end on end is that you never have enough space. Atmos has 64 total tiles of dedicated project space distributed throughout. 15 Tiles on the Crystalizer, 17 tiles on the Abandoned Distro, and 32 tiles in a dedicated room by maint. This is all before you guys cannibalize whatever remains. In short: You have plenty of space, what amounts to an 8x8 room in total. Future optimizations of my lackluster pipe network designs will net you more, and I want people to improve my dogshit pipe network. I believe that with optimizations the amount of dedicated project space is within the range of 80-100 tiles, or similar to Deltastation's project room. This is more optimized for several personal projects however, so it is more agreeable to many atmos techs. You also have several ways to mess with gas now, with 2 tanks for each gas. I don't know what it means for you, but I thought it was neat. It has also given @Ghilker Ideas for the future. 

:cl:
add: A stationwide retrofit has been completed. Enjoy the new engineering section, Metastationeers. 
/:cl:

As this is currently a draft, I will append stuff and update this PR text as things change/near completion. 
ToDo:
-Fix the door Merge Conflict
-Beg maptianers to freeze metatstation while I work on detailing
-Detailing
-More Detailing
-Finish pipework
-Debug checks

### CODE REVIEW

**Comment by Ghilker** [comment]
Like the map, tho there are a few issues i see with the space management:
Please remove these walls and have that a one room for bigger projects (dude you even placed r-walls there)
image

Neat room, just hate that ring of pipes, it's just there for no reason or usefulness
image

It would look better as 2 wide hallway with 1 row of canisters
image

God this feels cramped, i think that a 3 wide hallway with one row of tiles without any pipes would work best here
image

Wut
image

For what i think of this map change, is good to reduce the amount of space a bit (that huge room was an eyesore) but i think having it too cramped will limit players liberty when it comes to setting up anything. Remember that thermomachines takes one tile and are dense so you can't move through them and not having the space to setup a bunch of them will be bad looked.

Also i hope you're planning to replace all those r-walls with normal ones, otherwise the "maint dismantle" will never happen because it would be a chore to do

**Comment by GuillaumePrata** [comment]
Another advantage of compartmentalizing the main Atmospherics room is that the giga room was a headache when you had multiple Atmos techs trying to work on something different each.
The first one would start working on the HFR/Crystallizer/Turbine and would put their setup all over the place like they own 100% of the floor space and then the second Atmos tech either gives up on their project or needs to dance around the other's setup.

**Comment by Palpetinus** [comment]
>It has also given Ghilker Ideas for the future

Oh no.

**Comment by SnoopCooper** [comment]
A bit unsure on this. Meta atmos is currently probably the most enjoyable atmos to play on. Long hallways etc. is not that fun to play in as it makes setup time, remodeling time take a lot longer. Splitting into rooms is probably a good idea, but having to pipe through lobg hallways is not.

**Comment by Zytolg** [comment]
Todays update before I hit the sack:
I'm on my laptop so uh no updates to the main PR title. I have taken @Ghilker's primary suggestions under advisement and implemented them. The resulting gain is that The total workspace open to techs is about 80, or similar to Delta Station. The HRF Room also grew as a result. I think the size of the rooms won't (or rather can't) change too much beyond this because there's simply no more room. Keep feedback coming through #mapping-general on the discord or direct via this PR. I want to reiterate that if any enterprising atmos tech has a better Pipe Network, please feel free to advise me on it. I plan to make micro adjustments to rooms as I go now and make sure that the feel of everything is just right.

**Comment by Unit2E** [comment]
First off, I want to say that I really like the aesthetic this is going for, it feels fresh, and a lot more like a somewhat cramped space station. Even as much as I like the current Meta atmos, and I think it's the best Engi department we have in-game, it doesn't look as visually appealing as this might when it's fully finished up.

With that said, I do have some criticisms, mainly concerning some choices in the piping and some rooms that feel like they're using a lot of space without bringing much to the table. I don't have insight into the greater vision of the map however, so I may simply be off the mark with some of these because it's WIP / works differently than I think, or stuck in my old ways when it comes to piping choices I don't understand.



afbeelding

First up, this area, containing the N2 and O2 tanks. I removed some of the plating here for clarity, but this feels extremely crowded, pipe-wise. Within this screenshot, 4 different pipe layers are used. Or 3 if you discount the yellow pipes to the right. I'm obviously not able to playtest this currently, but this feels like it's going to be very hard to work with, especially with how often O2 especially is needed. Not having free access to O2 on a layer adapter here hurts as well, unless the idea is to have dedicated layers already available for all the different project rooms (HFR, incin, etc.), but that would be crowded as well.

afbeelding

Next, the plasma tank. plasma is the single most used gas in Atmospherics, being used for anything involving fires, the HFR, BZ synthesis, quite a few crystallizer recipes, and more. Not having a layer adapter for plasma hurts enormously, and this unfortunate fact is worsened by having no space in front of the tank to place your own adapter + pump. This could probably be solved by just moving the plasma tank back a tile, shrinking it down or having it extend out to space. I can not stress enough that a layer adapter on the plasma tank is essentially a requirement for any Atmos work, and having to work through the Pure lines is something that all atmos players I know try their hardest to avoid.

I'm also not sure about using 3 pipe layers here, just, in general. I'm personally of the opinion that, most of the time, piping layers within a map should be kept to a minimum to allow more freedom in modifications without running into issues, unless the plan is to have appropriate piping in place at roundstart to run multiple projects without interfering with one another.

afbeelding

It's hard to get a single focused screenshot of what I'm going to try and point out here, but bear with me. The problem in this area is the enormous distance between what seems to be the main O2 tank, the plasma tank, and the incinerator. At least in the current version, the tank in the top right is an Air tank, and you can forget about this point if this is intended to be a secondary O2 tank. However, if not, there is no way the O2 and plasma tanks should be this far apart, and the O2 tank so extremely far removed from the HFR and incinerator rooms. The same thing about layer adapters I said before can also still be said here. Having layer adapters roundstart is very convenient, and space should be left for them always if they're not already there roundstart.

Minor note that's also visible in this screenshot, as it won't return in other screenshots. The area to the right with the connectors goes essentially unused, I don't think I've seen it used once in hundreds of hours of play, at least not in a way that couldn't have just been done better using a handful of player-placed pipes. I know a lot of maps have an area like it, but unless people feel particularly attached to it, I'd get rid of it personally. It adds to player confusion and I don't think it really serves a function, unless you want to fill a huge amount of pipes with gas because you want to slowly fill up a few canisters.

afbeelding

I like how this area looks, and in an aesthetic sense, I like that it's in space too. However, I don't entirely understand the purpose of it. The left two tanks are N2 and O2, but they're also right by what seems to be the main O2 and N2 tanks to begin with, so they're not particularly closer to any of the places you might want these gasses for other reasons. I think this might have to do with a future PR where players would be able to purchase gas tanks, or maybe something akin to it, but until then I don't see a strong use for these tanks in the position they're in.

Minor piping gripe as well, there's no space for layer adapters, which might be especially difficult because all these tanks are also on different layers. This might work out if you can get the gas you want on the layer you want to begin with, but otherwise, using 4 layers without any access to layer adapters around it as well is likely going to be hard to work with.

Lastly, this being out in space makes it potentially slightly more annoying to work with, as you'd need a space suit of some sort to make any modifications. Also, meteors. 

afbeelding

This seems to be the air monitoring room, and I like how it looks. However, it's also very large, and in its current layout it does not seem like it would easily be modified to suit other purposes either, especially with all the R-walls and strewn about computers. I'm not sure what else this space could be used for myself. The room works aesthetically, I understand what the intended look for it is, but in a practical sense, it feels like a lot of space used for what isn't an important room to begin with, especially now that everyone in Engineering gets tablets as their PDA, with access to the alarm systems. 


afbeelding


Last one, and it's minor! This being in the middle of atmos feels like it takes up a lot of space. The need for gas monitoring is more obvious here than in the room I talked about before, but all the different solid objects might make this area feel a bit too present and hard to work around, in my mind.


That's all my feedback for now. I really want to reiterate that I love the aesthetics, if this pans out well, I'd imagine it's the best looking Engi department we've ever had.

Lastly, there's a few 'problems' which seem to be due to this simply being WIP, like the lack of gas recycling from waste, missing pipes, no atmos to engine pipe, that sorta thing. I didn't mention them in detail for obvious reasons, but they are worth keeping in mind. Also, don't forget that an unmodified pipe setup needs to be able to pump gasses into distro, as a requirement for antagonistic AIs. I currently see no way of doing so (with no way for plasma to go to the mix tank). Probably also a WIP thing, but it might be hard to plan around.

Good luck with the mapping!

**Comment by Zytolg** [comment]
@Unit2E Thanks for the feedback! Detailed breakdowns such as this are exactly what I need when it comes to being informed about the best choices to make when taking the next step. Naturally, I'm not sure at this moment if I'll be able to make all of the suggestions, but I'll certainly make an attempt. 

First things first: I believe that in order for this to be a successful PR, I need to without a doubt nail (or at least make functional) the Atmospherics Pipe Network. Under normal situations, this is a easy task to complete, however this PR and Engineering Rework are anything but normal. I have a constraint, and that constraint necessitates that I attempt to compartmentalize and push the boundaries of what atmospherics can be. Your comments suggest that I've at least accomplished this aesthetically, however, as you imply, this has a long ways to go. 

I don't mind having to scuttle the current pipe situation. As I have the general shape of the rooms I'm working on down, I wouldn't mind having to shift air tanks around either in order to best establish a working solution. The one thing I'm a tad stiff on is pushing out towards the implied docking area. It's all aesthetic, and so it's quite low down on the list of things to do when things come down to it, but I really want to give the Xenobio sat some breathing room again, so I don't believe that a southwards expansion should be made before exhaustion other possible solutions. That being said, I'll play around with the tanks and see what I can do. 

The Atmospherics Pipe network leaves a lot to be desired. Out of everything I believe getting this to a satisfactory degree will take the longest. It's the reason I drafted this so early, and I'll need that feedback regarding it to keep on coming. I might be able to exchange Oxygen with Carbon Dioxide, but this will add additional piping to the overall rats nest, and regarding layered piping, I still want to utilize the pipe layers. If using 3 is such a big problem, I'm absolutely willing to go down to just using layers 3 and 5. Mapping absolutely every function of atmos to layer 3 is the reason this PR exists, and while it was the solution to atmos when there wasn't that much to do, things have changed, and that isn't the case anymore. Maps have a responsibility to use every tool available to create the most optimal and functional spaces within a given aesthetic, and Meta has an F grade on that last part. This all being said, you've given me a lot to consider when I open SDMM back up and I think I'll start by scrapping pretty much everything pipe-wise. It might even be time for a gimmick.

I don't know what I can do about the monitoring rooms (especially the secondary room) as they are deliberately placed in a way that stops the engineering rooms from feeling too cavernous. It's also where your trinkets and stuff will end up. I'll talk to some maptainers about removing the pipe dispenser though and that'll make some more room in the room. I'm being honest when I say I don't know too, because as I write this out, I'm brainstorming what I might do with it because I'd really like to keep it (it's a good aesthetic). 

So yeah. No hard no's and a ton to think about. Thanks for your time, and hopefully the next few commits are a leap in how this all comes together.

**Comment by san7890** [comment]
This is going to be a complex PR that won't be resolved in a night's worth of work. There is plentiful feedback given that should be continuously hashed out and integrated until a good final product is reached.

A test-merge may also be in order for this PR when it's approached that final state to ensure we don't brick stations on production, since Atmospherics and Engineering is a critical component to the station.

**Pull request closed without merging**
