### PR TITLE
Removes Sec and Command from the AI's channel

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
People complain that the AI is too buddy-buddy silent antag-hunter which can pull down the law on you undetected.

People complain that they can't even tell the warden to beat the screamer without being asimov'd

After this PR, of course, they will also complain that the AI has to nose into the festering wreck of tcomms to do all of the above.

But its too late at night for me to do real coding boom

suck it remie you're not the boss of me

### CODE REVIEW

**Comment by RemieRichards** [comment]
Explained this in the bus but whatever since you're being stubborn I'll state this here.
NTSL already lets you get these channels, people want the channels? they'll just download the MAGNI or some other script and thus you've changed -nothing- for the better

:-1: :x: :100: not a proper solution, it's change for changes sake the the status quo remains the same.

**Comment by PKPenguin321** [comment]
yeah, all this does is make power-player t-comm rapist AIs more powerful than standard AIs
i'm all for this change as a concept, but *this change* doesn't fix the problem at hand

**Comment by ike709** [comment]
Anyone can copypasta one of the many, many NTSL scripts that work around this

:-1:

**Comment by Anonus** [comment]
Literally doesn't fix the problem, the AI has two intercoms it can use to listen into these channels and a script it can use to talk on them.

**Comment by Aranclanos** [comment]
yeah like if you're gonna do this do it properly, no lazy stuff

**Comment by Anonus** [comment]
You can't even fix it without removing telecomms, as the sec and command freqs can be rerouted to, say, AI private.

**Comment by GunHog** [comment]
:-1: Enough of the nerfs, please. This does not benefit the players in question, and only serves to degrade the experience for another set of players.

**Comment by Dorsisdwarf** [comment]
I'd still like to point out that the point at which the AI reached it's current Junior Security Investigations Member status was pretty much exactly around the time gun_hog gave them access to security and command by defauly.

**Comment by Aranclanos** [comment]
yeah sure but do it properly

**Comment by ExcessiveUseOfCobblestone** [comment]
What's the problem with people using a script to get it? You can easily edit the script to make it so the AI is blocked from ALL tcomms altogether and tcomms doesn't scream like your assassination target :^). Also most people aren't going to make the script due to apathy unless they're TRYING to be validscreams mcrobocop, in which case it's pretty clear to badmins and players who get salty about validhunting AIs.

Remove sec channels from AI altogether and you'll have PDA AI which is harder to spot than Tcomms-script AI AND Sec Channel AI. Give them the choice and watch as most people don't make it.

:+1: doin SiliGod's Work.

**Comment by Miauw62** [comment]
remove ai access to ntsl 2k15

**Comment by RemieRichards** [comment]
@ExcessiveUseOfCobblestone of course they won't make the script themselves.
there's 100s of NTSL scripts out there from MAGNI complex to just giving you the radio channels.

Again
## This Solves Nothing.

**Comment by GunHog** [comment]
Or you could...tune your other two intercomms to Sec and Command, and leave the menu open for quick switching. This nerf is not needed, please stop.

**Comment by Cheridan** [comment]
Yeah, this doesn't really fix anything, as mentioned above.

**Comment by Aranclanos** [comment]
do it properly!

**Comment by Dorsisdwarf** [comment]
sabface

**Pull request closed without merging**
