### PR TITLE
Reworks coin press (TGUI)

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Picking up where @Akrilla left it in #46452.

Changes:
 - Interface is tgui-next - auto updating, and not utter crap.
 - Start/stop at any time during the process, without needing to wait until it finishes an arbitrary number of coins.
 - Choose which material to press, but will go through all materials automatically without needing to swap each time.
 - Ores/sheets are automatically pulled into the machine when placed to the right of the mint (the arrows actually make sense now!)
 - Ten coins are now pressed per process tick, instead of going through each coin with sleep calls.
 - Code is less shitcode.

image

## Why It's Good For The Game
Coin press ui is ancient and useless, also gets rid of a sleep in process.

## Changelog
:cl: Akrilla & Skoglol
tweak: Coin press has a fancy new UI, QoL changes, and actually takes in ore/sheets from the right (floor arrows make sense).
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Port to tgui-next, tgui is frozen.

**Comment by kriskog** [comment]
Can't go porting shit until it actually for sure is in. That's how you get clutter and ui-less shit if it falls through.

**Comment by Cyprex** [comment]
It's not going to fall through at this point.

**Comment by Shadowflame909** [comment]
I think the worst part about the coin press is actually how the coins work themselves.

you have to slowly grab a coin and click your id with it, and spam this until you have whatever monetary value you want. Or until you get tired of it

**Comment by Cyprex** [comment]
You can dump from money sack now @Shadowflame909

**Comment by Shadowflame909** [comment]
Really?

Oh fuck if this is true I can't believe I wasted like 40 minutes dumping 100 golden coins into my id hand by hand

**Comment by Qustinnus** [comment]
don't convert shit to tgui when we're in the middle of removing all existing tgui templates thats just unproductive.

**Comment by kriskog** [comment]
This tgui is already done though, and was when Akrilla opened it in the first place. I'm all for swapping to tgui-next, but until its actually merged this needs the fallback anyway.

**Comment by PKPenguin321** [comment]
I wouldn't say that it *needs* it

**Comment by Akrilla** [comment]
> don't convert shit to tgui when we're in the middle of removing all existing tgui templates thats just unproductive.

It doesn't change anything lol, this was going to get merged anyway, and all this means is that there's going to be a nicer UI until the full conversion comes.

**Comment by 81Denton** [comment]
This is bad timing since we're in the middle of switching to tgui-next. Good PR though.

**Comment by kriskog** [comment]
Allright then, I'll re-do the UI in next.

**Comment by stylemistake** [comment]
It's fine to redo the UI in a separate PR.

**Comment by kriskog** [comment]
@81Denton This is ready now

**Comment by kriskog** [comment]
its ready again

**Pull request merged**
