### PR TITLE
Mining nerf

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Dunking the abandoned crate in lava will make it explode

### CODE REVIEW

**Comment by Ergovisavi** [comment]
Does this also affect normal secured cargo crates, because you can open those with lava too.

Free shotguns 24/7 because QM has mining access

**Comment by KorPhaeron** [comment]
It does not

**Comment by lzimann** [comment]
wooooow super lame, fuck those 4 digits code reeee

**Comment by MMMiracles** [comment]
and thus, the locked crates were never touched again.

**Comment by Durkel** [comment]
As much as I understand how retarded it is to bypass the lock by using lava, no one ever opens these these in the legit manner and I doubt removing them from the game would affect anyone after this change.

**Comment by francinum** [comment]
Because the 4digit code doesn't seem to properly work.

**Comment by Kromgar** [comment]
Its not like these fucking crates give anything good anymore. YOu can't get hyper or super kas. Occasionally you get a ghetto surgery kit which is cool

**Comment by lzimann** [comment]
the best you can get is a plasma cutter(really good to mine stuff fast) and that KA modkit(which is meh)

**Comment by Thunder12345** [comment]
24 hour rule?

**Comment by jughu** [comment]
You can get a hand tele from it @kromgar

**Pull request merged**
