### PR TITLE
Adds a new sprite for paradox bags.

### PR DESCRIPTION
**Pull request by Expletive**
:cl:
imageadd: Added new inhand, worn, and icon sprites for the paradox bags.
/:cl:

I saw this in Sprites Needed section of the projects page, so I went ahead and took a crack at it. These are the results.

dufflegaphagall

edit: Here's an animated icon sprite. Will commit in a bit. animated

### CODE REVIEW

**Comment by improvedname** [comment]
Thats a dufflebag you doofus!

**Comment by FantasticFwoosh** [comment]
Why is there a lizard with sunglasses on the front, is that a IC self reference?

**Comment by Expletive** [comment]
>lizard with sunglasses

I'm not seeing it.

**Comment by Repukan** [comment]
Paradox bags are shit though

**Comment by Supermichael777** [comment]
well we just don't have the supply and inventory limitations that would make it GOOD. For away missions and such like that its god-teir for loot extraction and resupply.

**Comment by WJohn** [comment]
I mean, this really doesn't look good at all, but re-used sprites is bad, too. I'd personally prefer the old ones over these purely because the colors are clashing incredibly horribly. Red, white, purple, yellow?

**Comment by RandomMarine** [comment]
For people that don't get the reference, it just flat-out looks ugly.

As someone that does... eh, could be a lot better.

**Comment by Repukan** [comment]
What's the reference

**Comment by RandomMarine** [comment]
>spoonfeeding

**Comment by DoctoreMad** [comment]
What's the reference

**Comment by WJohn** [comment]
Do not merge until it gets a better sprite, this is really quite ugly.

**Pull request closed without merging**
