### PR TITLE
Halloween Costumes

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fury sprited them maybe he has pictures I'm not sure of his git account so I can't @ him I'll just message him on discord

More specifically it adds

Jester outfit

Mummy outfit + pharoah hat

Scarecrow outfit +hat + mask

Skeleton outfit

They don't spawn anywhere yet but it might be nice to redo the halloween event to hand out costumes rather than trash the round by making everyone a zombie

:cl: FuryMcFlurry
add: Added mummy, scarecrow, skeleton, and jester costumes. They don't spawn on the map yet, so make sure to beg the admins for them!
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Kor you're missing some changes

**Comment by BeeSting12** [comment]
I believe there is a jester outfit ingame already in the costume vendor.

**Comment by Nienhaus** [comment]
This one looks a lot better though.

**Comment by BeeSting12** [comment]
Oh cool then replace it

**Comment by lzimann** [comment]
stop making prs adding sprites if you can't be bothered with pictures

**Comment by KorPhaeron** [comment]
@lzimann I PMd the spriter when I opened the PR, I'm not gonna load up the game locally and spawn all the stuff and dress up four mobs and then screencap and then upload the screencap and then link it here if he already has a picture on hand=

**Comment by FuryMcFlurry** [comment]
oh hey i made those. lemme grab a bunch of pictures..
image

**Comment by ShadowDeath6** [comment]
rp scenario where a real skeleton dresses up as a skeleton

**Comment by AnturK** [comment]
DNM ?

**Comment by Cyberboss** [comment]
@KorPhaeron pls

**Comment by FuryMcFlurry** [comment]
Currently the masks are  implemented as head slot items. And there exist no monkey slot items for said mask items. Unless this was somehow changed.

**Comment by KorPhaeron** [comment]
@Cyberboss 

okay

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
