### PR TITLE
Adds a new away mission: Underground Outpost 45

### PR DESCRIPTION
**Pull request by WJohn**
Underground outpost 45 is a large abandoned outpost built into a cave (which is also a gas pocket). It's mostly a leisure resort equipped with its own atmospherics filtering system, is fully self sustained with a large hydroponics bay, and has a lot of dormitory rooms and a big bar for its crew. The station, although abandoned, is fully operational and can continue being so as long as you can get some plasma or uranium into those generators.

Currently the fluff for UO45 is missing entirely because nobody (myself included) can be arsed to write the gigantic amounts of crew logs to make it extra interesting. It's not really the point of this map, as it's mostly a stress test on away mission atmospherics and what sort of atmos environment I can have around it.

Minor current issues:
-May be lacking in sufficient amount of equipment
-Gas filters in atmos do not start on for reasons unknown, but CAN be turned on

Here is the map of the outpost:
https://dl.dropboxusercontent.com/u/12849736/UO45%20Map.png

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Looks good, though personally, I feel this should go for more of the "abandoned research facility; what the hell kind of research was going on here?" spooky vibe--the design itself seems great to me, on initial examination.

**Comment by paprka** [comment]
[theme]_outpost_[number]

**Comment by TZK13** [comment]
Arctic outpost when, the snowy sprites are way too underutilized being only outside the syndie base.

**Comment by paprka** [comment]
^

**Comment by WJohn** [comment]
It's meant to be a leisure resort purely so that nothing massively dangerous can happen to it, the fact that it's in a plasma filled gas pocket that needs only a small oxygen leak and a *tiny* increase in temperature to start a chain reaction is dangerous enough.

**Comment by ike709** [comment]
your next away mission has to be Arctic Outpost *insert number here*

**Comment by WJohn** [comment]
Unfortunately arctic things will require trees that you can cut down, rock walls that aren't red, and a LOT more ghetto construction stuff.

**Pull request merged**
