### PR TITLE
Adds patting!

### PR DESCRIPTION
**Pull request by GunHog**
:cl: Gun Hog
add: You can now hug someone while aiming at the head, eyes or mouth to give them a pat on the head!
/:cl:

### CODE REVIEW

**Comment by AnonymousNow** [comment]
That's cute. I like that.

**Comment by vcordie** [comment]
pat the lizards condescendingly, yes yes.

**Comment by PKPenguin321** [comment]
This was already rejected

**Comment by Iamgoofball** [comment]
@optimumtact

**Comment by Iamgoofball** [comment]
#21352

**Comment by KorPhaeron** [comment]
Good PR

**Comment by Iamgoofball** [comment]
this is a meme PR zone now becaUSE THIS WAS ALREADY REJECTED

**Comment by KorPhaeron** [comment]
We have PRs that were rejected opened later all the time

**Comment by Iamgoofball** [comment]
chrome_2017-02-04_15-14-22
dreammaker_2017-02-11_14-43-29
chrome_2017-02-01_19-37-27
chrome_2017-02-01_19-00-38
chrome_2017-01-21_20-09-02
chrome_2017-01-21_20-08-43
steam_2017-01-31_16-35-12
chrome_2017-01-14_23-20-11

**Comment by Arianya** [comment]
@PKPenguin321 If something that was rejected once was never merged then goof would be out of a not-a-job

**Comment by PKPenguin321** [comment]
when goof reopens things he changes them, like removing doublefrying

**Comment by GunHog** [comment]
How should I change it, then?

**Comment by kevinz000** [comment]
:+1:

**Comment by Arianya** [comment]
@PKPenguin321 Please don't make me pull up the multiple times goof has re-opened a PR literally unchanged~

**Comment by Iamgoofball** [comment]
fuck you

**Comment by Arianya** [comment]
@Iamgoofball :heart:

**Comment by PKPenguin321** [comment]
name one unchanged reopened goof pull that got merged

**Comment by kevinz000** [comment]
rude

**Comment by optimumtact** [comment]
fuck off

**Comment by KorPhaeron** [comment]
Just imagine if he we tried to add hugging today someone would probably scream and try to stop it

**Comment by Arianya** [comment]
Considering goof has something like a 95% closure to merge ratio and git doesn't let me search by merge vs closed... @PKPenguin321

**Comment by Iamgoofball** [comment]
@Arianya DOT DOT DOT

**Comment by jughu** [comment]
COMMA

**Comment by Arianya** [comment]
@Iamgoofball ellipse

**Comment by AnonymousNow** [comment]
This seems like a harmless change that'll add a little something without being a detriment to anything (unless you count ERP, and we don't have that anymore). Is this a kneejerk "meme" contrarian reaction I'm seeing?

**Comment by optimumtact** [comment]
it's denied for the same reason as the original pr

**Comment by kevinz000** [comment]
gee maybe people who don't even know what lorebus is might want this.

**Comment by KorPhaeron** [comment]
lorebus invented patting on the head

**Comment by kevinz000** [comment]
🤡

**Comment by GunHog** [comment]
**WHAT HAVE I STARTED!?**

**Comment by Iamgoofball** [comment]
chrome_2017-02-04_15-14-22
dreammaker_2017-02-11_14-43-29
chrome_2017-02-01_19-37-27
chrome_2017-02-01_19-00-38
chrome_2017-01-21_20-09-02
chrome_2017-01-21_20-08-43
steam_2017-01-31_16-35-12
chrome_2017-01-14_23-20-11

**Comment by Iamgoofball** [comment]
# MEME PR ZONE

**Comment by kevinz000** [comment]
shut up goof.

**Comment by PKPenguin321** [comment]
@Arianya 
https://github.com/tgstation/tgstation/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20author%3Aiamgoofball
https://github.com/tgstation/tgstation/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aunmerged%20author%3Aiamgoofball%20

**Comment by kevinz000** [comment]
1/3 ok fine.

**Comment by PKPenguin321** [comment]
now how many have been remade without any changes to the code and merged? hmm

**Comment by ShadowDeath6** [comment]
this buffs the borg hugging module too much, not sure if I can get behind this pr :confused:

**Comment by Repukan** [comment]
Fetish shit

**Comment by Grazyn** [comment]
Old PR was rejected because it was pandering to a well known metagang which made constant use of patting (Kyo the green cat and the other pink cat and their orbiters), this metagang has since been disbanded so there's no reason to oppose patting at this time.

**Comment by Thunder12345** [comment]
Was never about those cats. Was always inspired by lorebus.

**Comment by Repukan** [comment]
Better reason to reject it then. 

No doubt lorebus is behind this, the sneaky catjuden

**Comment by GunHog** [comment]
Clearly this is a lesson. Never enable "Allow maintainer edits".

**Comment by Cyberboss** [comment]
Unchecking that shit so fast from now on

**Review by PKPenguin321 — COMMENTED** [review]
:ok_hand:

**Comment by Thunder12345** [comment]
Don't worry he's gone, it's not happening again

**Comment by RemieRichards** [comment]
@GunHog @Cyberboss Don't disable it.

**Comment by Thunder12345** [comment]
Yeah there's no need to disable it with oranges gone

**Comment by Doppeltongue** [comment]
This should get reverted, it shows up in the changelog, but doesn't actually exist in game, which is not good.

**Pull request merged**
