### PR TITLE
All types of spacesuits can hold Captain's Jetpack in their suit storage, Also Plasmaman EVA suit change.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Biggest changes to come from this is all space suits will fit the Captain's jetpack on their suit storage slot and plasmaman EVA not fitting weapons (WHY DOES IT FIT GUNS, ITS NOT A COMBAT SPACE SUIT).

## Why It's Good For The Game

Most Spacesuits not fitting Cap's Jetpack feels like a bit dumb when every MODsuit including Syndicate and non-spaceproof ones can fit it.

Also the plasmaman EVA suit isn't a combat space suit, It shouldn't hold weapons in its suit storage.

## Changelog
:cl:
balance: All Spacesuits can fit Cap's Jetpack now (Not just EVA and MODsuits like before).
balance: Plasmaman EVA suit no longer fits weapons in its suit storage.
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
> WHY DOES IT FIT GUNS, ITS NOT A COMBAT SPACE SUIT

This was a really old leftover from when plasmamen didn't have their enviro jumpsuits and needed to keep EVA all the time, so it had to hold guns for officers.

Kinda sad to see the tidbit die, but it also is not used for anything.

**Comment by CVSthePharmacy** [comment]
> (WHY DOES IT FIT GUNS, ITS NOT A COMBAT SPACE SUIT).

it's for sec, since they kinda need an EVA suit as a plasmaman sometimes, and can't get ahold of the other plasma module for sec suits

**Comment by starrm4nn** [comment]
> > (WHY DOES IT FIT GUNS, ITS NOT A COMBAT SPACE SUIT).
> 
> it's for sec, since they kinda need an EVA suit as a plasmaman sometimes, and can't get ahold of the other plasma module for sec suits

i'm pretty sure the module is roundstart, there's a bunch of them chilling in some departments and plasmamen can spacewalk with just a firesuit

**Comment by CVSthePharmacy** [comment]
> > > (WHY DOES IT FIT GUNS, ITS NOT A COMBAT SPACE SUIT).
> > 
> > 
> > it's for sec, since they kinda need an EVA suit as a plasmaman sometimes, and can't get ahold of the other plasma module for sec suits
> 
> i'm pretty sure the module is roundstart, there's a bunch of them chilling in some departments and plasmamen can spacewalk with just a firesuit

anyone can spacewalk with a firesuit, they just need their own space suit to be able to hold guns

**Pull request closed without merging**
