### PR TITLE
Adds in the DAB

### PR DESCRIPTION
**Pull request by ditalos**
*dab

### CODE REVIEW

**Comment by obscolene** [comment]
goofball-tier trash pr

**Comment by ditalos** [comment]
lots of people asked for it :^)

**Comment by obscolene** [comment]
just kidding. i love epic memes. *dabs* woot!! for teh epic winz0rz!! x3c

**Comment by ShadowDeath6** [comment]
this is disgusting no matter who does it

**Comment by ditalos** [comment]
**at least it's not ERP**

**Comment by optimumtact** [comment]
feature freeze

**Comment by dannno** [comment]
ahhh so fahnny ahahha dude i laff so ahrd aha aaaaaaaaaaaaaa
you're the one who wasted time doing this you moron

**Pull request closed without merging**
