### PR TITLE
Sprite reorganizing, minor sprite fix for mineral stacks

### LINKED ISSUE #37520: 34+ sheet plastitanium stacks don't have an icon
Or rather, they show the "NO SPRITE" fallback.

Reproduction: take 35 or more plasma + titanium alloy sheets from the ORM, take one from the stack to refresh the icon so it doesn't show the "1 sheet" one. 
Only really shows up with free golems and if someone wants to decorate like Syndicates.

### PR DESCRIPTION
**Pull request by ohnopigeons**
Moves all sheet_ prefix sprites from mining.dmi to stack_objects.dmi and fixes a typo bug for plastitanium.
:cl:
fix: Large stacks of plastitanium now display properly
/:cl:

Fixes #37520 

EDIT: REQUIRES https://github.com/tgstation/tgstation/pull/37564

### CODE REVIEW

**Comment by ShizCalev** [comment]
@Cyberboss bot broke?

**Comment by Cyberboss** [comment]
which bot?

**Comment by Cyberboss** [comment]
Oh that's on @lzimann

**Comment by YakumoChen** [comment]
Plasteel is supposed to have a max stack size of 30, I believe.

**Comment by Barhandar** [comment]
It's plastitanium that has the issue, not plasteel.

**Comment by SpaceManiac** [comment]
plasma sprites broke

**Pull request merged**
