### PR TITLE
Added rice seeds, hydroponics tools, salt and pepper shakers to service vendors

### PR DESCRIPTION
**Pull request by erwgd**
This adds some items to the vending machines for the Kitchen and the Hydroponics work areas: 
3 rice seeds to the Megaseed Servitor; getting more rice will become easier
5 salt shakers and 5 pepper mills to Plasteel Chef's Dinnerware Vendor; make all the meat pies you want!
2 plant analyzers, 3 spades and 3 cultivators to NutriMax. 

:cl: Erwgd
rscadd: "The Kitchen Vending machine now stocks salt shakers and pepper mills!"
rscadd: "The NutriMax now stocks spades, cultivators and plant analyzers."
rscadd: "Rice seeds are now stocked in the Megaseed Servitor."
/:cl:

### CODE REVIEW

**Comment by KazeEspada** [comment]
Add a cleaver or two to the default kitchenvend. Its annoying to have to hack it every round to feel like a real chef.

**Comment by newfren** [comment]
While you're at it can you remove the wheat mutation into rice? That way the oats mutation is easier to get and you don't exactly need it anymore with 3 seeds in the vendor.

:+1: even without that, on box there aren't even enough cultivators/hatchets in botany for a fully staffed department.

**Comment by KorPhaeron** [comment]
>IF YOU MODIFY THE PRODUCTS LIST OF A MACHINE, MAKE SURE TO UPDATE ITS RESUPPLY 

Did you update those?

**Comment by erwgd** [comment]
The three vending machines do not use resupply canisters right now, so there isn't anything to update there.

**Comment by tkdrg** [comment]
Yeah if you're gonna make rice a default seed, remove it as a mutation from wheat.
:+1: otherwise

**Comment by erwgd** [comment]
I didn't intend to add all those other people's commits. I'll make another PR for all my changes.

**Pull request closed without merging**
