### PR TITLE
Adjust ai's cams around icebox's execution chamber to be more consistent.

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request

Adjusts some cams around icebox's Perma so the door to the reeducation chamber is no longer visible. It is like this intentionally for every other map including box before the Perma changes.

## Why It's Good For The Game
Consistency. The AI could still hack the door if its in camera range and AIs tend to metagame this all the time.

## Changelog
:cl: itseasytosee
tweak: Cams in iceboxe's perma no longer reveal the door to the prisoner "reeducation" room
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Doesn't the door to the execution chamber start with its AI control disabled?

**Comment by itseasytosee** [comment]
Yeah but Ai can hack doors that have the wire cut to access them after a delay (news to me as of this morning hence the pr)

**Comment by ATH1909** [comment]
> Yeah but Ai can hack doors that have the wire cut to access them after a delay (news to me as of this morning hence the pr)

whaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by itseasytosee** [comment]
video incoming

**Comment by itseasytosee** [comment]
https://www.youtube.com/watch?v=LWpQjY_MEjY

**Comment by zxaber** [comment]
Being able to *eventually* open the execution chamber has been a thing since before I started playing AI.

That said, I don't know what AI player willingly wants the headache of catching sec executing someone in the re-education room. The whole point of that room is that it makes life easier for AI and sec players.

**Comment by itseasytosee** [comment]
Realy what prompted this all was me seeing an Ai bolt down the execution room after a warden announced over sec radio that they were taking a prisoner for re-education. See no evil

**Comment by msgerbs** [comment]
Seems like an administrative issue.  The whole point of the fluffy euphemism of the room name is so that the AI has no reason to look inside or interfere. That said I don't see any reason not to merge this.

**Review by Timberpoes — CHANGES_REQUESTED** [review]
Can you provide images showing the before-change and after-change of the AI's camera views for the area in question?

On which other maps can the AI see the re-education room door, if any?

With those two things addressed, I'll be able to make a more informed decision on merging this or not.

**Comment by itseasytosee** [comment]
can do just a moment

**Comment by itseasytosee** [comment]
Meta AI can't see the entire corridor leading up to the execution room, on delta the door not visible but the surrounding area is. And on pubby, it is completely visible.

**Comment by itseasytosee** [comment]
precam
Before
postcams
after
(note that that area would be entirely obscured if it were not for the camera looking through the open door which is not windowed.)

**Review by Timberpoes — APPROVED** [review]
Hmmm. Given your replies, I still think it's an administrative issue, but I'm not against this change in principle.

Tentatively approving the changes.

I will merge in 12-24 hours, so if you have any major issues with merging this PR that's your time frame. Any other maintainer is free to overrule me and block the merge.

**Comment by itseasytosee** [comment]
You sound like an AI that's just been law 2ed to kill themselves,

**Comment by Timberpoes** [comment]
> 
> 
> You sound like an AI that's just been law 2ed to kill themselves,

More like someone just uploaded a onehuman law when I'm not even on Asimov, but I don't want to give the game away in case they change me back!

**Pull request merged**
