### PR TITLE
OOC: Brumbpo: your new year's resolution should be nerfing the rapier

### PR DESCRIPTION
**Pull request by Iamgoofball**
what the fuck are these stats, this is some OP garbage that I'm going to go abuse the fuck out of

>15 damage
>sharp and can decap
>ignores armor
>ignores half of all melee attacks

### CODE REVIEW

**Comment by Supermichael777** [comment]
Stahp

> My Christmas gift to myself is no new feature or balance arguments for a couple weeks.

**Comment by PKPenguin321** [comment]
No I love the rapier

**Comment by AnturK** [comment]
Freeze

**Comment by jughu** [comment]
i call it weaponry refactor :^)

**Comment by Jordie0608** [comment]
\>people still calling it a rapier

**Pull request closed without merging**
