### PR TITLE
Removes old shotgun handcrafting

### PR DESCRIPTION
**Pull request by Bawhoppen**
now that we have craft anywhere button we don't need this

### CODE REVIEW

**Comment by lzimann** [comment]
\>wanting to force craft button and not just use stuff on stuff to assemble more stuff

**Comment by PKPenguin321** [comment]
Ree :-1: Freeze

**Comment by Iamgoofball** [comment]
@lzimann 
>people bitch you shouldn't need a table to craft
>we give them a crafting button
>they keep bitching that you need a button to craft

stop being fucking retarded pls

**Comment by Razharas** [comment]
Stuff on stuff to make more stuff is cancer of code
It may be pleasanter to do but it kills the codebase

**Comment by PKPenguin321** [comment]
No it doesn't it just triggers your autism

**Comment by Lumipharon** [comment]
@Iamgoofball 
>people bitch about the shitty table crafting system
>gets replaced by a slightly less shitty air crafting system
>autism babies think this makes conventional crafting any less superior

**Comment by Iamgoofball** [comment]
@Lumipharon like we've said every time:

make a handcrafting code setup that isn't shit and we'll consider re-adding it

**Comment by PKPenguin321** [comment]
What is even bad about attack by crafting? Is this just a meme?

**Comment by Lumipharon** [comment]
No on has ever explained to me, other than 'it's shit code', not 'why it's shit code'.

**Comment by Zilenan91** [comment]
Yeah don't remove slap crafting

It's fine with what we have and way more intuitive than looking through menus on a button that's really hard to notice in the first place

**Comment by Cheridan** [comment]
ugh you can remove shit during feature freeze

BECAUSE IT'S NOT A FEATURE

**Comment by Fox-McCloud** [comment]
>No it doesn't it just triggers your autism

Too true.

**Comment by Iamgoofball** [comment]
it's literally the definition of shitcode

it's a ton of snowflaked attack bys with special snowflake messages with intermediary icons that take up RSC space and serves no purpose than to waste time and be bad filler content

**Comment by Zilenan91** [comment]
The same could be said about Ian clothes, nobody wants to remove it because they think it's a better system to find these things rather than clicking on something and now Ian is wearing a santa hat.

**Comment by lzimann** [comment]
i would rather have a shitcode with better in-game execution than having to open a crafting menu everytime i want to do something(yes, i know this only removes the in-hand craft shotgun that i've never seen anyone using)

**Comment by Iamgoofball** [comment]
@Zilenan91 we recoded Ian clothes to not be shitcode ages ago

**Comment by RemieRichards** [comment]
>ages ago

it was like, in the last month.

**Comment by PKPenguin321** [comment]
>it's a ton of snowflaked attack bys with special snowflake messages with intermediary icons that take up RSC space and serves no purpose than to waste time and be bad filler content

oh no it takes up all our technobabble that doesn't do anything! look at all the lines it takes! it's wasting so many of our *literally infinite amount of lines!* how wasteful!!!

**Comment by Zilenan91** [comment]
Then recode this feature if you don't want it to be shitcode. If it's infinitely more intuitive and easier to use then make the sacrifice because flipping through menus on a crafting menu isn't as close to as easy.

**Comment by Iamgoofball** [comment]
@Zilenan91 we did recode crafting

thats called tablecrafting

**Comment by Zilenan91** [comment]
And that was reverted due to being bad so here we are now.

**Comment by Iamgoofball** [comment]
but we didn't revert it, we simply changed how you access it

**Comment by Iamgoofball** [comment]
because he deleted it:
chrome_2016-05-18_16-38-11

**Comment by Zilenan91** [comment]
I deleted it for a reason, also yes you did revert it. Before, it required a table, now it doesn't. That takes away 90% of the restrictions that the old one had so it's basically an entirely new system.

**Comment by Iamgoofball** [comment]
i do not think that word means what you think it means

**Comment by Cheridan** [comment]
IT IS NOT FUCKING INTUITIVE TO HAVE TO SMASH THIS ITEM WITH ANOTHER ITEM THERE IS LITERALLY NO WAY TO KNOW THIS IN GAME STOP USING THIS RETARDED EXCUSE

**Comment by PKPenguin321** [comment]
:-1:

**Pull request merged**
