### PR TITLE
Small fix - Updates paths to stickmen

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

#61272 just got merged and idk what happened, these were never changed.

## Why It's Good For The Game

Code isnt compiling help

## Changelog

I dont think this is player facing until they realize their favorite space station 13 server cant load.

### CODE REVIEW

**Review by Timberpoes — APPROVED** [review]
Have a fancy label due to this fixing master being broken.

**Comment by Timberpoes** [comment]
https://github.com/tgstation/tgstation/commit/a9a73541c5e90abf600735a1534cce07f6aa02f0 broke master. Likely merge skew?

**Comment by JohnFulpWillard** [comment]
seems skewed with #60302

**Comment by Timberpoes** [comment]
Speed merging as this is a simple 2 line housekeeping PR that should fix master.

**Pull request merged**
