### PR TITLE
Emojispooky

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
add: Adds several Halloween-Themed Emojis. See if you can get them all! [no code diving cheaters!]
/:cl:

I changed some of the states just so if you saw the previous PR but want to "find out" the emoji names ingame you still can.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
SO MANY COMMITS I NEED TO REDO MY MASTER SO IT ISNT SO AUTISTIC

**Comment by JJRcop** [comment]
run this in a console on your branch, i fixed it for you
```
git fetch https://github.com/JJRcop/tgstation.git savethemojis; git reset --hard FETCH_HEAD; git push --force emojispooky
```

**Comment by ShadowDeath6** [comment]
Skeleton emoji is A+

**Comment by ExcessiveUseOfCobblestone** [comment]
I need to fix my master regardless because I used to update manually instead of setting it to upstream 😢 but thanks for the help 😸

**Comment by JJRcop** [comment]
@ExcessiveUseOfCobblestone Well even if you update your master, this PR will still be shot.

Run the command, all will be fixed!

**Comment by ExcessiveUseOfCobblestone** [comment]
errr 

fatal: You are pushing to remote 'emojispooky', which is not the upstream of
your current branch 'emojispooky', without telling me what to push
to update which remote branch.

**Comment by JJRcop** [comment]
oh i'm an idiot
```git push --force origin emojispooky```

**Pull request merged**
