### PR TITLE
Adds "narrow" emote

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
-adds *narrow emote and simple mob and param variation

## Why It's Good For The Game
-new emote

## Changelog
:cl:
add: Added "narrow" emote
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
sus

**Comment by Megamaw** [comment]
can we have an alt *emote for this that's a bit shorter in a pinch

since narrowing your eyes would be body language insinuating suspicion i propo--

**Comment by Mothblocks** [comment]
narrowing your eyes doesn't necessarily mean suspicion. i think the context of the conversation can decide that, probably don't need it in your emote message

**Comment by Mooshimi** [comment]
> narrowing your eyes doesn't necessarily mean suspicion. i think the context of the conversation can decide that, probably don't need it in your emote message

Just remembered the squint emote, which I forgot for some reason 🦀 This pr never happened and you can't prove it...

**Comment by Mooshimi** [comment]
> > narrowing your eyes doesn't necessarily mean suspicion. i think the context of the conversation can decide that, probably don't need it in your emote message
> 
> Just remembered the squint emote, which I forgot for some reason 🦀 This pr never happened and you can't prove it...

THERE IS NO SQUINT EMOTE WHY DID I THINK THAT

**Pull request closed without merging**
