### PR TITLE
[April Fools] Adds 13 new jobs to the game to enhance the roleplaying experience.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Adds 13 new jobs to the game and spawns for them on the map.
dreamseeker_s9KbKhV42U

## Why It's Good For The Game

Enhances the roleplaying experience by adding 13 new jobs to the game!

## Changelog
:cl: Fury McFlurry, Baystation, Paradise, Skyrat for assorted job sprites
add: Adds 13 new jobs to the game!
add: Added the Blueshield and Nanotrasen Consultant to Command.
add: Added the Security Medic, Security Sergeant, Magistrate, and Corrections Officer to Security.
add: Added the Bouncer and Barber to Service.
add: Added the Orderly to Medical.
add: Added the Engineering Guard to Engineering.
add: Added the Science Guard to Science.
add: Added the Customs Agent and Gun Dealer(and relevant crates) to Cargo.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Is this every type of department guard to exist on all downstreams, put together

**Comment by orthography** [comment]
Is it April first already?
image

**Comment by JohnFulpWillard** [comment]
Also I'm closing for the same reason as every other april fools pr
closed prs can still be testerged n stuff

**Comment by JohnFulpWillard** [comment]
reopening for CI to make sure it works, requested by goof

**Comment by LemonInTheDark** [comment]
sent

**Comment by LemonInTheDark** [comment]
image

**Comment by Wallemations** [comment]
Where's the radio show host?

**Comment by DrDiasyl** [comment]
Finally, RP PR

**Comment by Iamgoofball** [comment]
ok, CI passes, we gucci for april fools

**Comment by Iamgoofball** [comment]
reopening to remove a .dmi change real quick

**Comment by Mothblocks** [comment]
run your tests locally or on your own repo dude, we already get ci clogging problems

**Comment by Iamgoofball** [comment]
@Mothblocks i am not running CI locally, it takes 2 hours

**Comment by RikuTheKiller** [comment]
Apparently it turns out this PR is legit good enough that I'd like to see it fullmerged.

Quite a few others share this opinion.

Goof, you fucking legend.

**Comment by Rex9001** [comment]
I know this was april fools and all, but I would love to actually have some of these jobs merged. This is a pr that felt like such a natural extension of the game and made high pop so much more enjoyable. 

Goof, well done like actually really well done, this is one of the more fun prs in a long time.

**Comment by LSommers** [comment]
Echoing the other comments, giving this a second pass for quality control (IE removing the goddamn gun dealer) and putting it on Manuel or even elsewhere legitimately feels like a good idea.

Also, the science guard having the Black Mesa logo for their icon sent my sides into orbit. 

My specific thoughts on each job, just in case it helps:

```
Blueshield is questionable, and more likely than not will just be played as "sec but blue" or "stupid command's personal hitman". Fairly redundant.

Nanotrasen Consultant has immense RP potential, but can also fall prey to the "assistant with sec comms and access" problem that Lawyer can, _but worse_. Would absolutely need to be restricted to Manuel.

Security Medic: Great idea given how often people in the brig wind up hurt, genuinely not seeing any downsides. Worst case scenario it's just an extra secoff. 

Security Sergeant: Redundant, sec forces aren't big enough to need a larger chain of command. Cool drip though.

Magistrate: Please god give us more reasons and easier ways to have trials. They always bring comedy and fun.

Corrections Officer: Could certainly help if the Warden is busy acting as dispatch for sec. Again, worst case scenario, it becomes an "extra sec officer slot" job.

Bouncer: Literally just hire a greyshit. 

Barber: No content, mirrors exist, etc.

Orderly: A sort of misc "pick up the slack and deal with all the crap" job for medical makes sense- Think about how dirty it gets, how random shit piles up, and how often tiders cause trouble. 

Departmental Guards: We have the departmental sec posts, why _not_ use them? Plus, imagine a science sec guard on Tram greeting every latejoining scientist with "Mornin' Mr/Ms X, looks like you're runnin' late."

Customs Agent: Redundant, not really needed, will most likely either ignore their job or be shot by the QM for sending back contraband/gun crates.

Gun Dealer: Pleasegodno
```

**Comment by CMDR-Gungnir** [comment]
I agree pretty much all the way with Sommers. A lot of these would make fantastic additions to keep.

**Comment by JohnFulpWillard** [comment]
Barber was already approved afaik, goof just never finished it.
The rest were all denied in the past, and likely will continue to be denied.

**Comment by Mothblocks** [comment]
hate to rain on everyones parade but i tihnk theyre all redundant/bad ideas except for the barber, and would not want to see them as a permanent addition

**Comment by DrDiasyl** [comment]
The only jobs from this PR, that have the reason to stay is:
- Magistrate
- Nanotrasen Consultant

All you need to do is remove CentCom ID from the consultant (as a consultant he doesn't need to have any CC flavour, he might look like just a fancy bureaucrat)

**Comment by DrDiasyl** [comment]
> Barber was already approved afaik, goof just never finished it.
> The rest were all denied in the past, and likely will continue to be denied.

Nothing will always be the same

**Comment by CMDR-Gungnir** [comment]
> hate to rain on everyones parade but i tihnk theyre all redundant/bad ideas except for the barber, and would not want to see them as a permanent addition

Having a Detective is redundant, just give the HoS the scanner. Having a Warden is redundant, officers can process their own prisoners. Having Chemists is redundant, MedDoc's can mix chems. Do we really need a Virologist? After all, if Science can be Xenobio and Toxins and experiments and research, Medbay can do the same too. While we're speaking about Science, let's fold Geneticist in, too. Atmos Tech? I mean Engi can just drag a canister out while they go to repair the structure.  Do we really need both a Clown and a Mime? We can just have an Entertainer and let people pick.

If you try hard enough, everything is redundant. Doesn't mean we shouldn't have it.

**Comment by JohnFulpWillard** [comment]
what are you trying to say

**Comment by CMDR-Gungnir** [comment]
That they're not actually redundant. It's easy to say something is, but that doesn't make it true.

**Comment by DrDiasyl** [comment]
> what are you trying to say

Sometimes things change, sooner or later.

**Comment by Mothblocks** [comment]
> If you try hard enough, everything is redundant. Doesn't mean we shouldn't have it.

it does considering we already have enough trouble as is making our existing jobs feel worthwhile

**Comment by Mothblocks** [comment]
> > what are you trying to say
> 
> Sometimes things change, sooner or later.

i stay alive just to spite some people drdiasyl

**Comment by CMDR-Gungnir** [comment]
> > If you try hard enough, everything is redundant. Doesn't mean we shouldn't have it.
> 
> it does considering we already have enough trouble as is making our existing jobs feel worthwhile

Adding the Magister would encourage lawyers and trials more, as you wouldn't have to get the Captain involved for every single one of them. SecMed's good, whether it's a Brig Doctor style or a Corpsman, both would provide value to the Security Team and be worthwhile.

A large chunk of the added options provide nothing, yes, but there are some in here that add dynamics or behaviour that existing jobs don't already have. If they're not added, are we going to put that stuff in for the existing jobs? Or are we going to go without? With Lawyers having no purpose because Captains never have the time to run trials?

That's my issue. We shouldn't just dismiss it all out of hand. Some of them would add new dynamics that wouldn't interfere with existing jobs. Some of them add features and dynamics we could just GIVE to existing jobs, but seemingly won't.

**Comment by ophaq** [comment]
I really want most of these jobs to stay. Primarily blueshield, brig medic, bouncer and barber.

**Comment by KonKonBreezeFox** [comment]
those jobs are great, and those that decide to do boring jobs, shame on them.

**Comment by dessysalta** [comment]
@Iamgoofball Would you mind if I copied this branch and made an effort to add a few of these roles, or do you plan on doing so yourself?

**Comment by Iamgoofball** [comment]
@dessysalta please do not do that, i am working with maintainers on this

**Comment by CMDR-Gungnir** [comment]
> @dessysalta please do not do that, i am working with maintainers on this

What're we, hopefully, getting to keep?

**Pull request closed without merging**
