### PR TITLE
print 5 cable coils instead of 1 in lathes

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
What the title says.
## Why It's Good For The Game
It is incredibly tedious to get a large amount of cables from lathes, considering you need a lot most of the time (especially in engineering), it should be printing way more than one piece of cable.
## Changelog
:cl: grungussuss
qol: lathes will now print cables coils in packs of 5
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
How is it tedious? There's an input box where you can type the exact amount of cable to print and the print times remains constant.

Also the fact you can now print 5 cable pieces for the exact same cost as before makes this a balance PR

**Comment by Sadboysuss** [comment]
> How is it tedious? There's an input box where you can type the exact amount of cable to print and the print times remains constant.
> 
> Also the fact you can now print 5 cable pieces for the exact same cost as before makes this a balance PR

the maximum amount you can print at a time in a lathe is 50, this is very annoying when trying to get a lot of cables compared to other items, before a certain change it printed 30 cables per print so that wasn't a problem, the amount of mats required to print cables is negligible so it doesn't really change anything in the balance of things.

**Comment by 00-Steven** [comment]
hmn, while I don't think it's a bad idea to let you bulk print wires, I do feel this is unintuitive UI- you're always printing 5x as much as what it says on the tin, which is annoying when there is no way for you to know that as a new player or someone that doesn't read every changelog ever
I think things that could make that less awkward could be say, putting `(x5)` in the name, or having a separate `Cable Coil (x5)` design

**Comment by MrMelbert** [comment]
On one hand it's unintuitive that it's called "cable coil" but only prints 1, on the other hand it's unintuitive that it would print more than one (throw back to when autolathe would print 1 cable, but RND lathe would print 30, so people would print x30 cables and end up with 900)

> ...or having a separate Cable Coil (x5) design

Rename the cable coil design to "cable" and then do this

**Comment by CCC23** [comment]
Finally I wont have to spend half my weight in gold on lathe tax to print enough cables

**Comment by MrMelbert** [comment]
> Finally I wont have to spend half my weight in gold on lathe tax to print enough cables

Anon wake up it's 2024

image

**Comment by zoomachina** [comment]
Why couldn't we just have x30 cable printed everywhere..

**Comment by Time-Green** [comment]
150 CABLES!!!!

**Pull request merged**
