### PR TITLE
Fix lack of to_chat_immediate in client code that disconnects clients.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
these clients are about to be disconnected, they can't wait for the mc to tick next

### CODE REVIEW

**Comment by MrStonedOne** [comment]
this is just one file, but its the one file with the most of this pattern.

**Review by LemonInTheDark — APPROVED** [review]
Does this sort of thing get blocked by the tgui disconnecting message?

**Comment by MrStonedOne** [comment]
this sort of thing often happens when tguichat has not even loaded, most of these are in client/New()

**Comment by LemonInTheDark** [comment]
alright so it's finee

**Comment by MrStonedOne** [comment]
@tralezab explain yourself arm =P

**Comment by optimumtact** [comment]
bazelart did this one

**Pull request merged**
