### PR TITLE
Return of the Ass: Photocopier Edition

### LINKED ISSUE #43348: Ass photocopying is broken
Round: 104689, Sybil

Photocopying your ass doesn't work anymore, you get a blank photo ("The photo appears to be blank...")

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request
Corrected creation of /datum/picture during photocopying of asses.

Appears someone added/reordered arguments in the constructor and broke calls to it... sad...

Also I used named arguments to attempt to prevent this issue in the future, but it may actually cause issues if some big brain changes the argument names.

Fixes #43348 

## Why It's Good For The Game
Ass is back.

## Changelog
:cl: bobbahbrown
fix: Return of the photocopied ass
fix: Photocopiers now properly have a delay before photocopying an ass.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Speedmerge now

**Comment by JJRcop** [comment]
If "some big brain changes the argument names" they'll get compile time conflicts and they'll have to fix this code. Don't worry about that.

**Comment by bobbahbrown** [comment]
> If "some big brain changes the argument names" they'll get compile time conflicts and they'll have to fix this code. Don't worry about that.

GOOD point thank you

Sent from AOL Mobile Mail

**Comment by ShizCalev** [comment]
oh great swami of picture code, could you please take a look at this too to see if you can figure out why it runtimes when someone tries to print a photo from the security records computer?
https://github.com/tgstation/tgstation/blob/3b2c0e27f7cb515d82a04568199d3141391e7d4f/code/game/machinery/computer/security.dm#L768-L783

relevant runtime;
```
[2019-03-18 04:15:26.601] runtime error: Cannot modify null.picture_image.
 - proc name: print photo (/obj/machinery/computer/secure_data/proc/print_photo)
 -   source file: security.dm,779
 -   usr: Tim Drake (/mob/living/carbon/human)
 -   src: the security records console (/obj/machinery/computer/secure_data)
 -   usr.loc: the floor (116,166,2) (/turf/open/floor/plasteel/dark)
 -   src.loc: the floor (116,167,2) (/turf/open/floor/plasteel/dark)
 -   call stack:
 - the security records console (/obj/machinery/computer/secure_data): print photo(/icon (/icon), "Jessica Sulivard")
 - the security records console (/obj/machinery/computer/secure_data): Topic("src=\[0x2007093];choice=Edit%2...", /list (/list))
 - Ryufen (/client): Topic("src=\[0x2007093];choice=Edit%2...", /list (/list), the security records console (/obj/machinery/computer/secure_data))
 - Ryufen (/client): Topic("src=\[0x2007093];choice=Edit%2...", /list (/list), the security records console (/obj/machinery/computer/secure_data))
 - 
```

**Comment by bobbahbrown** [comment]
for sake of consistency I will put my response in discord here as well

it does what it says on the tin, its a null pointer

P.picture needs to be initialized/instantiated by using the new keyword/proc/whatever this hell is in byond

in other words you need to do something like

```
/obj/machinery/computer/secure_data/proc/print_photo(icon/temp, name) 
     if (printing) 
         return 
     printing = TRUE 
     sleep(20) 
     var/obj/item/photo/P = new/obj/item/photo(drop_location()) 
     var/icon/small_img = icon(temp) 
     var/icon/ic = icon('icons/obj/items_and_weapons.dmi',"photo") 
     small_img.Scale(8, 8) 
     ic.Blend(small_img,ICON_OVERLAY, 13, 13) 
     P.icon = ic 
     P.picture = new(desc = "The photo on file for [name].", image = temp)
     P.desc = P.picture.desc
     P.pixel_x = rand(-10, 10) 
     P.pixel_y = rand(-10, 10) 
     printing = FALSE 
```

**Comment by ShizCalev** [comment]
would you mind cleaning up like 123 a bit as well?
```
					else if(ishuman(ass)) //Suit checks are in check_ass
						temp_img = icon(ass.gender == FEMALE ? 'icons/ass/assfemale.png' : 'icons/ass/assmale.png')
```
this should do fine.

**Comment by bobbahbrown** [comment]
@ShizCalev done

also fixed the delay on printing the photo while i was there with the broom

**Pull request merged**
