### PR TITLE
 Unfuckening of icebox kitchen and dining for chef, CQC and shutter edition

### PR DESCRIPTION
**Pull request by DustanHache**
## About The Pull Request

After the rework of icebox kitchen and dining area to include the bar, Chef lost a number of important security tools they used to deter tiders in their workspace, namely extended CQC to dining areas and THEIR FUCKING SHUTTERS. This fixes both by replacing a telescreen that was on the wall behind the ovens with the shutter control button, and extends the flag to properly cover the Atrium (Upper level of the dining hall. Bar lounge/theater are both still CQC free!)
## Why It's Good For The Game
Cooks need to be able to lock down their kitchen like it's fucking Madagascar during an emergency, or they die VERY fast. Also, having tiny CQC area makes it hard to protect dinebots and patrons from tider invasion.
## Changelog
:cl:
add/fix: Replaced the telescreen inside the kitchen on icebox with the shutter control button. Not like your patrons could watch the bitrunning from there anyway.
fix: Re-enables chef CQC in the dining area on icebox now known as the Atrium.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
You gotta keep the entertainment monitor somewhere, how else are people gonna watch the game

There's a good amount of extra real estate on the wall with the light switch if you just shift the button around

image

**Comment by DustanHache** [comment]
> You gotta keep the entertainment monitor somewhere, how else are people gonna watch the game
> 
> There's a good amount of extra real estate on the wall with the light switch if you just shift the button around
> 
> image

last i checked, you have to be standing next to it to watch anyway, but maybe i'm stupid. That said, maybe it would be better suited in the lounge?

**Comment by MrMelbert** [comment]
Entertainment monitors are supposed to have infinite range, if they don't rn that's a bug

**Comment by MrMelbert** [comment]
> last i checked, you have to be standing next to it to watch anyway, but maybe i'm stupid. That said, maybe it would be better suited in the lounge?

Not enough real estate unfortunately (Also I modeled it like one of those dive bars with a bunch of TVs above and behind the counter)

**Comment by DustanHache** [comment]
> > last i checked, you have to be standing next to it to watch anyway, but maybe i'm stupid. That said, maybe it would be better suited in the lounge?
> 
> Not enough real estate unfortunately (Also I modeled it like one of those dive bars with a bunch of TVs above and behind the counter)

okay, hear me out. What if I put it on... THE TABLE.

**Comment by DustanHache** [comment]
actually no, we dont even need to. there's literally two telescreens down there..

**Comment by DustanHache** [comment]
TeleSCREAM

**Comment by MrMelbert** [comment]
I don't see why we can't just put it next to the light switch it's free real estate

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Failing linters because you use step_y (which breaks the game) instead of pixel_y

Also you should put the button by the light switch and put the tv back and i'll merge this

**Comment by DustanHache** [comment]
> Failing linters because you use step_y (which breaks the game) instead of pixel_y
> 
> 
> 
> Also you should put the button by the light switch and put the tv back and i'll merge this

the follies of mapping in dreammaker.. Okay, sure. just remember that wall objects dont play nice with eachother if they get destroyed, and since they're sharing spots it'll be hard to repair.

**Comment by MrMelbert** [comment]
If the wall gets destroyed no one's gonna repair the light switch I tell ya what

**Pull request closed without merging**
