### PR TITLE
Omegastation Updates and Fixes

### PR DESCRIPTION
**Pull request by Okand37**
#34068 but also adds the CE's magboots to the gravity room, a medical wrench to cryo, and a new A.I. satellite!

:cl: Okand37
add: Added a fully functioning A.I. satellite to Omegastation!
add: Added the CE's magboots to the gravity room on Omegastation!
add: Added a medical wrench to cryo for Omegastation!
/:cl:

### CODE REVIEW

**Comment by Anonmare** [comment]
Got a pic @Okand37 ?

**Comment by Okand37** [comment]
@Anonmare Here is a slightly outdated and dodgy quality picture. Some of it was cleaned up/finished after the making of this picture, but it gives a general and mostly up to date view of it.
image

**Comment by Tlaltecuhtli** [comment]
can you turn that one window inside the ai core into a rwall?

**Comment by Anonmare** [comment]
@Tlaltecuhtli I believe it has a shutter in it like it does on Delta and Meta

**Review by ShizCalev — CHANGES_REQUESTED** [review]
https://github.com/Okand37/tgstation/pull/2

**Comment by ShizCalev** [comment]
That'll fix #34062 too.

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
