### PR TITLE
Put drone spawners back

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
-adds a filled drone spawner in each station's robotics maint somewhere
-removes the maint drone research node
-removes maint drone design from mechfab

## Why It's Good For The Game
-Some people just want to play silicon and not be fucked with every few seconds
-They're useful, and never made now
-They've been refactored so they can't interact with multiple things(air alarms, volume pumps, etc), and they can't do anything within ~5 tiles of a living or dead mob

## Changelog

:cl:
qol: Maintenance drone spawners have returned to robotics maintenance
removed: maint drone is gone from the mechfab and research tree
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Sorry to assault your gbp but I'm positive this is not quality of life.

**Comment by Mooshimi** [comment]
> Sorry to assault your gbp but I'm positive this is not quality of life.

i was told the changelog thing is just for the symbol, I didn't put the tag on it

**Comment by ExcessiveUseOfCobblestone** [comment]
> preloaded 

🤢

**Comment by IndieanaJones** [comment]
I agree something needs to be done for drones, they're in a great spot currently but nobody makes them.

**Comment by AnCopper** [comment]
Ah yes, Drones, the things that were only used as an infinite greytide respawn.

"What do you mean I'm trying to slip the antag? No bro, I just happen to coincidentally drag soap around with me"

**Comment by Mothblocks** [comment]
don't they completely freeze when they're near someone now

**Pull request merged**
