### PR TITLE
Adds new eldritch longsword sprite

### PR DESCRIPTION
**Pull request by Lexorion**
## Adds new eldritch longsword sprite
**OLD**

**NEW** (EDIT:updated picture)

I thought it was a bit small for a longsword so I changed it.
This PR also makes it more consistent with the other swords we have.

### CODE REVIEW

**Comment by Lexorion** [comment]
Oops, I'll fix the inhand glow tomorrow, forgot to make it reverse.

**Comment by Armhulen** [comment]
Make it bigger than one tile!

**Comment by Lexorion** [comment]
But you only need one hand to use it, so it wouldnt make a lot of sense to make it even larger I guess!

**Comment by WJohn** [comment]
much much better

**Comment by Robustin** [comment]
Meh, I like the dark metal aesthetic. Also the pulsing syncs up with a few other cult glows so I would highly recommend you at least make the aura "timing" line up with the old up.

**Pull request merged**
