### PR TITLE
Replaces chem macros with a recording based system

### PR DESCRIPTION
**Pull request by JJRcop**
## About The Pull Request

This removes chem dispenser text macros and replaces them with a recording function. This allows you to still use macros, but you must record them yourself. You are no longer able to paste in a pre-written macro.

When the dispenser is recording, trying to dispense chems will record to the in-progress macro instead and won't dispense like normal. You can then save this macro when you're done recording and use it like you would before.

Using an existing macro while recording a new one will record the macro contents to the in-progress macro, and can be done multiple times.

It looks like this:

image

## Why It's Good For The Game

It forces chemists and bartenders to learn the recipes for themselves first if they want to get the macros going quickly.

## Changelog
:cl: JJRcop
del: Removed text macros from the chem dispenser.
add: Replaced with dispenser input recording macros.
/:cl:

### CODE REVIEW

**Comment by py01** [comment]
I thought the goal of macros was to remove clicking tiny buttons to make chems

**Comment by optimumtact** [comment]
I want to make chem like a plumbing minigame tbh

**Comment by actioninja** [comment]
I don't really think this fixes any of the issue with current chem.

**Comment by optimumtact** [comment]
yeah but at least it makes macros a little more high effort

**Comment by Tlaltecuhtli** [comment]
does it also record when you del chemicals?

**Comment by JJRcop** [comment]
It doesn't, good point. I'm going to sleep but will try and do tomorrow

**Comment by Dawson1917** [comment]
This might have been better received in the days when chemistry wasn't responsible for supplying 90% of medbay, along with the addition of more specific chems with negative side effects or limited applicability since then. 

This doesn't stop or limit macros, you just press the buttons in order of the macro once as opposed to pasting the recipe in. In no way does this make chemistry more interesting or fun, only slightly more tedious for the people getting essential macros out of the way at roundstart so they can have fun with other chems.

**Comment by Dawson1917** [comment]
I agree that macros being used by every chemistry player isn't good, but it's a result of chemistry being convoluted and boring to actually _play_. Stare at wiki while you press labeled buttons **or** make a macro is hardly a choice. Making macros require you stare at the macro/wiki while pressing the buttons a single time mildly worsens the situation, and creates a nuisance when making multiple recipes with different sizes, namely mutagen and chems that have uses on their own but are also prerequisites for other chems

**Comment by actioninja** [comment]
tgui conflict

**Comment by GLACoding** [comment]
Can't we just make macros available on better parts?
Would mean round start chemists and bartenders would need to still use and learn recipes as normal and later on can pump chems out with macros.

Macros also allowed a lot more precision with the amount of reagents made and i don't think that would be easy to translate into this system.

**Comment by Swagile** [comment]
yeah i don't touch chem cause of the amount of back and forth clicking, and removing macros to replace it with recording is bringing back the same issue

especially with the removal of chems like bicard and kelo and having to make high level chems for medbay before you can do stuff of your own (unless you want to be a douche and just do your own thing from the start, but that just makes the issue of chemists "not doing their job" even worse)

**Comment by Iatots** [comment]
Hey uh I haven't played in a while and am just browsing the git because of the warops noise but

can't you already record recipes like this by putting your ID in the machine?

**Comment by Detective-Google** [comment]
I don't see why this could in any way be a negative change, instead of pasting in a (probably broken) macro into the machine, you only have to make one batch of a chemical, the entire round, and your macro is done, the current macro system doesn't support removes either, so it's done with janky math and odd values (1s, 4s and the like) whereas a macro system that allows removes let's you perform recipes much easier

**Comment by SynnGraffkin** [comment]
I am against the removal of macros how they currently are. It isn't really a matter of forcing chemists and bartenders to learn round start medicine and drinks, but being able to pump out those drink and chems at a good pace before people start begging for various things you may need to make by hand or have already memorized. Using the current macro system, I can easily pump out a couple batches of styptic and silver sulfadiazine before the botanist comes up to me for some Mutagen. What if there is a virus cure for saline glucose and we haven't made any? Poof. Macro. Now we can pump out some virus cures.

**Comment by ExcessiveUseOfCobblestone** [comment]
or just press water sodium chlorine water sugar then press the newly generated macro?

**Comment by SynnGraffkin** [comment]
Also consider this, Macros don't persist between deconstruction of chem machines. So if I am replacing a dead battery with a charged one, I would lost all of the macros manually imported with EITHER system. This proposed system would make readding macros in the same shift / machine much more of a pain in the ass than copy and paste.

**Comment by ExcessiveUseOfCobblestone** [comment]
I for one don't find the chemicals exciting so i'm not too keen on removing macros for the sake of forcing people to learn the recipes because I'd rather not have chemical strength justified based on "not many players know how to make it" or "it's a pain to make" or whatever. 

Chemical balance should come from either setting up the dispenser so you can't make all meds at T1 OR have the stronger meds involve more resources to make batches (IE Hearty Punch 6:1 ratio or whatever it is). Second one sounds easier and less of a headache to deal with from the peanut gallery.

in b4 someone just rewrites the macros already available to make it easy to input into this system like they did before macros existed to begin with.

**Comment by SynnGraffkin** [comment]
I don't see why there has been so much need to change chemistry so much to begin with. The only main issue with Chemistry recently has been players who just don't do their job at all and only make meth / drugs instead of helping supply medical supplies first at the very least. Part of that has been hindered with the removal of Trekchems mixing and the addition of, in my honest opinion, healing chems that are extremely niche in the way they heal or are applied (food, spray, forced dilution or lol poisoned with an anti toxin medicine).

I would agree that stronger medicines should be the ones that require more steps than just combining three base components. That is why Pententic Acid is much better than potassium iodide, for example, but people are more than likely going to use the meds they know works (Styptic or silver sulf. for example) instead of ones they may not recognize right away unless labeled as such, like the brute or burn meds that work better when you have more than 50 of the respective damage.

**Comment by SynnGraffkin** [comment]
Also, the reason I brought up macros not carrying over between deconstructions is because, from my experience on Sybil at least, you cannot 100% rely on other departments to upgrade the machines or provide dispensers, but chemists can easily take the battery charger in the science lobby, as well as tools from cargo, tool storage, or Cryo (after respectfully setting it up before swiping tools) and recharge their machines by swapping the battery out when needed which helps quite a lot early in the round. There will also be moments where people who upgrade your machines will not upgrade the capacitor, battery, or if they do the battery, not even charge it beforehand. Being able to easily input macros instead of having to record the entire process again is a timer saver if compared this way.

**Comment by JJRcop** [comment]
@Iatots
Not like this. You can paste in a recipe list currently but this PR removes that in favor of recording.

@​**others**
I think the precision units was just a bad feature since you can't do that in the normal chem dispenser UI, only through recipes.

The macro system only records total amounts of chems just like the old one did under the hood. It doesn't record 5 water 10 sugar 5 water 5 water, it records 10 sugar 15 water.

I've decided against recording removals because that will let you make fine adjustments to chems.

**This change does not intend to make chemistry easier, its purpose is to make chemistry harder.**
This is detailed in the *Why It's Good For The Game* section of the PR.

**Comment by SynnGraffkin** [comment]
> **This change does not intend to make chemistry easier, its purpose is to make chemistry harder.**
> This is detailed in the _Why It's Good For The Game_ section of the PR.


And this is why I am strongly disagreeing with you. Because of all the recent changes to medbay, pressure has been put more and more on chemists because doctors will almost always run out of medicine, be it through actually treating patients or the usual greytider breaking into medical storage and looting the medkits. By making chemistry harder, your effectively contributing to the downward spiral medbay has been experiencing, because even if the chemists themselves aren't doing their jobs, anyone given chems access would also have to put up with this when trying to make supplies for medbay. The current macro system for this already in place is completely fine, especially considering what Dawson said, where this and bartending are jobs you will almost always have the wiki up, especially for more complex medicines or drinks.

**Comment by necromanceranne** [comment]
I feel this PR is a strong highlight of how silly chemistry actually is and how it's entirely a job based on APM rather than actual game knowledge and skill. 

Whatever changes oranges has in mind cannot come fast enough.

**Comment by SynnGraffkin** [comment]
I wouldn't say it is a job based entirely on APM until there is some kind of crisis and you have a ton of people at the window because the virologist let out a death virus or an engineer gave everyone radiation cancer. You can normally roll at your own pace until stresses like that happen.

**Comment by ExcessiveUseOfCobblestone** [comment]
Their point was the only thing different between a good chemist and a bad chemist is input speed, and even that's trivial with macros.

**Comment by SynnGraffkin** [comment]
I would disagree with that. You can be as fast or slow as you want, but chemists who don't stock basic meds in the front chem fridge are bad chemists in my opinion. It is really shitty to be 40 minutes into a round and seeing no changes in the stock of a chem fridge since round start, save for maybe some missing charcoal pills.

**Comment by ExcessiveUseOfCobblestone** [comment]
sure ok, input speed and whether or not you put in basic meds in the fridge.

Once you put in basic meds in the fridge though...

**Comment by SynnGraffkin** [comment]
Well, what defines a good chemist is subject to matter of opinion. I would prefer someone who is slow and helps their department over someone who is fast and dies from overcooking their meth for the third shift in a row.

**Comment by JJRcop** [comment]
chems_simply

You can't paste a recipe into the machine from a list of them you found online. New chemists can pick up the chemistry textbook and repeat what they see into a macro to make it easily repeatable. Experienced chemists will memorize the recipe and can enter it quickly.

**Comment by SynnGraffkin** [comment]
Okay, but that still doesn't respond to my points earlier about power and deconstruction.

**Comment by JJRcop** [comment]
I can add data disks to save recipes to once you've recorded them. Might make a separate PR for that.

**Comment by SynnGraffkin** [comment]
Could probably work in the same PR, because honestly, this one just seems like either keep Macros how they are now, or remove the system **entirely**. A good chunk of macros were probably made because the "Experienced" chemists as you would call them, got lazy because when you do the same thing every shift, it's a lot more efficient to import a macro from previous shifts.

**Comment by JJRcop** [comment]
btw y'all check out [the chemfactory thread] it's da bomb. this pr works for now but that's like the ending of mcu phase 3

[the chemfactory thread]: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=23355

**Comment by adamkad1** [comment]
why was this not here from beggining anyway

**Pull request merged**
