### PR TITLE
Adds a github action to remove emoji from PR titles and changelogs

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Adds a workflow action that can be configured to automatically remove emoji from PR titles and/or body content.

Here it is in **_action_**:
chrome_lVszvn9m0I
edit: PR titles with only emoji will now become "**A title without emoji**" instead of "(only emoji)" as pictured above.
chrome_yRybhdtE6g
Typical execution time is around 3 seconds and that's mostly spin-up.

Code is here: https://github.com/Wayland-Smithy/emoji-stripper-action/blob/master/src/index.js

## Why It's Good For The Game

Better headcoder sanity.

## Changelog
GitHub change only, so does it need a CL?

### CODE REVIEW

**Comment by Mothblocks** [comment]
utterly insane

**Comment by tralezab** [comment]
hahahahahahahahahahahahahahahaha

**Comment by Y0SH1M4S73R** [comment]
:bee: moment

**Comment by MrStonedOne** [comment]
give https://github.com/Wayland-Smithy/emoji-stripper-action a readme so i can post it to hacker news.

**Comment by Wayland-Smithy** [comment]
README done. Wanted to get the PR up first soon as I finished testing. Mostly just copied from the round_linker repo anyway.

**Comment by Couls** [comment]
this PR is great! 😊

**Comment by Mothblocks** [comment]
image
this is so dumb

**Review by Mothblocks — CHANGES_REQUESTED** [review]
i want timber to provide a good reason against it other than "im old". i still see zero problem with emojis in titles, changelogs i get

**Comment by Wayland-Smithy** [comment]
🤔 I could name the action just "PR emoji" with 2 jobs "title_stripper" **and** "changelog_stripper" it should not be too hard to do the same treatment to all text between the CL tags only.

**Comment by AMonkeyThatCodes** [comment]
jokes on you ill just put them in my commits

**Comment by Wayland-Smithy** [comment]
> jokes on you ill just put them in my commits

Sure go nuts and I will be laughing too since that's not a concern AFAIK just like including them in the rest of the PR body. I thought the trouble was with knock-on effects from them in titles and changelogs whose text is rendered in many other places too. The titles alone are shown in discord, in-game, and I imagine on the server test merge interface plus git CLI and for changelogs it's worse since they need to pass through multiple scripts to be "compiled" one of which uses PHP.

With v2 the maints now have the ability to configure the action to run on just the title, or a section of the body, or both as they see fit.

**Comment by interestingusernam3** [comment]
https://user-images.githubusercontent.com/51925758/128646355-dd87ae13-033c-4e06-a60a-e966b83862db.mov

**Comment by AMonkeyThatCodes** [comment]
:trollface:

**Comment by optimumtact** [comment]
> i want timber to provide a good reason against it other than "im old". i still see zero problem with emojis in titles, changelogs i get

If you squash merge a PR the commit title and body are inherited from the PR op, which means the emojii goes into the git log and it's not a unicode emojii it literally shows it as the `:word:` form and it looks terrible anywhere outside of github

**Comment by Timberpoes** [comment]
> 
> 
> i want timber to provide a good reason against it other than "im old". i still see zero problem with emojis in titles, changelogs i get

They make PRs more difficult to search, to me they obfuscate PR titles and make them harder to understand at a glance and they get pushed to players on live servers with the appropriate preferences enabled. The reason I decided I was going to start closing PRs with emojis in the titles is so I don't have to decipher whatever arcane meaning the PR author had with their emojis. I can just close it and ask them to remake it with a proper title and/or changelog.

#59881 - I'm well aware of what merchants are without needing a bag of money to remind me what they are.

image - I'm not sure what the rat emoji was meant to add to this PR title other than to imply it touched rat code. It did not.

#60701 - Again, not sure why the thumbs up is in the title. Is this to tell us the PR is a good PR? The bee just obfuscates things for me.

I don't feel like I'm being unreasonable here. If there are no open PRs with emojis in the titles, then there's a better chance that people aren't going to see them, think it's accepted or common practice in the codebase and start doing the same. In changelogs or in PR titles.

**Comment by Mothblocks** [comment]
they dont make prs more difficult to search unless the title is literally just an emoji, in which case we already have precedent for the "friendly warning" of accurate titles/descriptions, if anything they stand out MORE

**Comment by Timberpoes** [comment]
> they dont make prs more difficult to search unless the title is literally just an emoji, in which case we already have precedent for the "friendly warning" of accurate titles/descriptions, if anything they stand out MORE

I've outlined my reasons. You say they don't, I say they do. Do we want contributors making their PR titles stand out from the crowd? We're going to get around to every PR eventually, I don't want contributors throwing emoji into their PR titles to get their PRs noticed. I find that a negative point for it.

Why do you think emoji in PR titles are so beneficial that they outweigh the relative downsides and must be kept?

**Comment by optimumtact** [comment]
he's ignoring my post im getting mad

**Comment by Mothblocks** [comment]
> Why do you think emoji in PR titles are so beneficial that they outweigh the relative downsides and must be kept?

I think appending another action that has the potential to error and send annoying emails is something worth taking a look at.

@optimumtact That's because it was a reasonable answer and so I didn't respond

**Review by Mothblocks — COMMENTED** [review]
i'm not blocking this anymore, but i still think it's mostly pointless

**Comment by MrStonedOne** [comment]
> they dont make prs more difficult to search unless the title is literally just an emoji,

Replacing words with emojis keeps the result from showing up for searches for that word.

They also make titles hard to read while skimming thru the pr list. For my boomer ass, my instinct is to read past them, so "the 🐝 knees" just reads as "the knees" the first 5 times through.

**Comment by Timberpoes** [comment]
> 
> Replacing words with emojis keeps the result from showing up for searches for that word.
> 
> They also make titles hard to read while skimming thru the pr list. For my boomer ass, my instinct is to read past them, so "the 🐝 knees" just reads as "the knees" the first 5 times through.

How do PRs with emojis in the titles appear on the keyholder tooling for testmerging PRs etc? How easy is it to search for PRs with emojis in with that tooling?

I've got no experience with the keyholder tools and emoji in PR titles hasn't really cropped up before the past month. Like, for example, how does #59881 appear? Does it substitute for the string `:moneybag:` or does it appear as a square or does it render in the font like tgchat does?

**Comment by MrStonedOne** [comment]
image
image

**Comment by MrStonedOne** [comment]
> How easy is it to search for PRs with emojis in with that tooling?

There is no searching, you just get a drop down in descending order

**Comment by Rohesie** [comment]
I'm good with this, but maybe the org should host the action.

**Comment by Wayland-Smithy** [comment]
> maybe the org should host the action.

One reason I configured the workflow with a commit hash was so that once vetted you can be sure that code will not change.

Anyway I'm also down to transfer the repo or you could just fork it I suppose.

**Comment by ExcessiveUseOfCobblestone** [comment]
if something gets through, say "the 🐝s knees" and I see "the s knees" im going to find that a lot less helpful vs "the bee s knees" or something similar.

Is there anyway we can replace the stripping with the keyword? That way even if we miss it theres still SOME semblance of what it was suppose to say without it looking like an autocorrect fill disaster.

**Comment by Mothblocks** [comment]
People don't actually tend to use emojis in the title as replacement for words, it's more likely you'd just see [🐝] The bee's knees

**Pull request merged**
