### PR TITLE
Adds Nuroxanide a powerfull antiparasitic

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl: optional name here
add: Central Command has rushed the approval of a new anti-parasitic agent to cut down on fumigation costs.
add: Nuroxanide can be made with sulfur plasma and cyanide. Side effects may include projectile vomiting, blood in vomit, vomit in blood, and death.
/:cl:

Dealing with borers surgically is a loosing battle. They can make new borers and take control of doctors faster is possible to fight. Plus they usually just take control on the table and try and robust you.

Open to suggestions.

### CODE REVIEW

**Comment by kevinz000** [comment]
it's a loosing battle because it's beneficial to have one, not because people can't get it out, getting it out is easy.

**Comment by ShadowDeath6** [comment]
yeah, the main reason borers can't be eliminated is because people don't mind having to vomit up a new borer every (x) seconds for free heals.

**Comment by Repukan** [comment]
Are you guys forgetting that they can also OD you and steal your body.

Borers are shit because they're a soft antag just like umbras were. Having people get free revives and heal sluts that can double as a valid hunting comms (Because if borers want to survive they will hunt the shit out of both cults) is shit design and one of the reasons they were removed for a time.

**Comment by Jazaen** [comment]
Suprise suprise, they can't steal your body unless you are braindead, since you can resist out of it.

**Comment by FantasticFwoosh** [comment]
@Jazaen they have a ability to shadowling glare you into a blank state & can see through ventilation where isolated targets are. Its extremely easy to play as one.

**Comment by Jazaen** [comment]
I am aware.
By "can't steal your body" I meant "can't ASSUME DIRECT CONTROL of you 'till the end of time".

**Comment by coiax** [comment]
People already spam sugar pills when borers are around, and this doesn't actually have any side effects. This also means that all someone has to do is throw a smoke grenade of this on the shuttle, and boom, borers all die.

**Comment by Repukan** [comment]
It's not like borers have a direct comm link to rally other borers to protect chemistry.

What is the point of a mid round antagonist spawning if you want it to not be countered. If you really want them to be protected then add them roundstart like VG does

**Comment by Supermichael777** [comment]
i blame goofchems apply methods all being the fucking same.

**Comment by Repukan** [comment]
Aren't smoke nades useless if you wear a gas mask and internals?

**Comment by ShadowDeath6** [comment]
>borers can see people while in vents

are you sure about that

**Comment by PKPenguin321** [comment]
Yes

Also this shouldn't have been closed, borers are ass and need more counterplay like this instead of just being "lol I heal sec and make antag space heself": The Antag

**Pull request closed without merging**
