### PR TITLE
Blob Fixes / QoL

### PR DESCRIPTION
**Pull request by Whoneedspacee**
## About The Pull Request

Sets the density of blob structures back to false (this was changed to true in an attempt to fix the snowflakey stuff about blob but did not actually fix all the issues)

Addresses the previous issues with the snowflakey solution by allowing blob structures to be used as a spacemove backup so blob mobs are no longer stuck and unable to move in zero gravity.

Also addresses the fact that projectiles would pass over blob structures by having them hit if they cross over.

I also made it so that the blob overmind can see turfs since I don't think it will provide that much of an actual benefit and I think it's easier on the eyes to not have to deal with constant sight lines changing, but you still need to go over and look to see structures / mobs etc.

## Why It's Good For The Game

General quality of life impovements to a mostly neglected mode.

## Changelog

:cl: Whoneedspacee
qol: Blob Overminds can now see all turfs regardless of sight lines.
fix: Blob Spores can now path through blob structures normally.
/:cl:

### CODE REVIEW

**Review by Watermelon914 — CHANGES_REQUESTED** [review]
If you want to fix spore pathing, you should actually properly fix it, don't do the same thing others did in an attempt to fix a bug by creating new ones as a result.

**Comment by Whoneedspacee** [comment]
But hey blame @Watermelon914 every time you play a broken gamemode, he's certainly not going to fix it.

**Comment by Timberpoes** [comment]
> 
> 
> But hey blame @Watermelon914 every time you play a broken gamemode, he's certainly not going to fix it.

Skill issue.

**Comment by Whoneedspacee** [comment]
> > > If you don't want to properly fix something, that's your problem not mine.
> > 
> > 
> > I don't even play the game my man, I was just doing you a favor reverting a bug that's existed for 9 months because you guys let someone merge broken code.
> 
> The issue wasn't with you fixing the bug, it was that the way you fixed it will cause problems in the future/create new bugs/bring back old bugs.
> 
> > Next time do your job properly.
> 
> > But hey blame @Watermelon914 every time you play a broken gamemode, he's certainly not going to fix it.
> 
> This is an open source codebase, completely maintained by people volunteering. It's not a job, they're not paid to do it, so if @Watermelon914 doesn't want to fix a bug, either because they're burned out or not interested in that area of the code anymore or any other reason, that's their choice. They have no obligation to fix any bugs, even ones they created. If you want to take up the job of fixing one of those bugs, that's your choice, but if the maintainers don't accept your fix, too bad. Seriously, do you think if you're rude enough to them they'll just change their mind and agree with you? Grow up.

It’s not a buggy fix, and it’s ridiculous of them since the only reason the bug exists in the first place was because maintainers merged broken code and then left the game in a broken state because they’re too lazy to fix it themselves.

**Comment by Whoneedspacee** [comment]
blbo machine broke

**Pull request closed without merging**
