### PR TITLE
Syndicate turret no longer packs a bunch

### PR DESCRIPTION
**Pull request by ghost**
Packs a bunch... of ammo... for your face.

From:
_desc = "Syndicate defense turret. It really packs a bunch."_
To:
_desc = "Syndicate defense turret. It really packs a punch."_

### CODE REVIEW

**Comment by CosmicScientist** [comment]
I even held back _obviously not out of not realising_ from spelling defence the Breeteesh way.

**Comment by Incoming5643** [comment]
It really snacks a brunch

**Comment by Thunder12345** [comment]
Proper english only, mate

**Comment by CosmicScientist** [comment]
@Thunder12345 hm?

**Comment by Thunder12345** [comment]
British english only proper english

**Comment by Razharas** [comment]
I dun gedit

**Comment by CosmicScientist** [comment]
I'll tell you when you're older Razharas.

**Pull request merged**
