### PR TITLE
Fixes some dexterous guardian issues

### PR DESCRIPTION
**Pull request by ChangelingRain**
You can't heal guardians with brusepacks
Guardians can't use guardian creators by default
Medbeams only check if the user is a living mob instead of specifically human

### CODE REVIEW

**Comment by Xhuis** [comment]
\>guardians summoning other guardians
L O L

**Comment by ChangelingRain** [comment]
infinite guardian chain works

**Comment by Supermichael777** [comment]
MY PUNCHGHOST HAS A PUNCHGHOST

**Comment by Kromgar** [comment]
This must be the work of recursive enemy stands

**Comment by Cheridan** [comment]
Deep fried deep fried deep fried stand stand stand.

**Pull request merged**
