### PR TITLE
"""Borrows""" MoMMI icons from /vg/ for use with /tg/ drones

### PR DESCRIPTION
**Pull request by plapatin**
## About The Pull Request
Exactly what it says on the tin.
Inhands are a little wonky but everything else should be fine. I'd fix them, but the only real way to do that would be to override inhands for the ENTIRE drone mob, which shouldn't need explaining as to why that's a terrible fix.

## Why It's Good For The Game
mommidance

## Changelog
:cl:plapatin, /vg/station coders
add: """Borrows""" MoMMI Sprites from /vg/station, to be used on drones.
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
You need the nickname(s) _after_ the first :cl:, not before.

**Comment by plapatin** [comment]
shit

**Comment by SouDescolado** [comment]
Ugly as fuck

**Comment by ExcessiveUseOfCobblestone** [comment]
cringe

**Comment by Tlaltecuhtli** [comment]
why not port mommis at this point

**Comment by plapatin** [comment]
because drones and mommis are basically the same thing, the only difference being one uses an internal storage and has a slightly different lawset

**Comment by Nabski89** [comment]
That sprite is so very ugly. Stick figure arms and legs with a bland ass central body that doesn't even match the typical metal color palette for SS13.

**Comment by plapatin** [comment]
it's got SOUL

**Comment by ExcessiveUseOfCobblestone** [comment]
Someone
Other than
U
Likes this

**Comment by Tlaltecuhtli** [comment]
they are actual borgs with real logging instead of dump shitcode simplemods

**Comment by anconfuzedrock** [comment]
this looks far too different from current drones, the only reason I see for this is somebody likes vg a bit too much

**Comment by PKPenguin321** [comment]
Mommy mommy

**Comment by nicbn** [comment]
Icon is bad and you should feel bad

**Comment by Dorsisdwarf** [comment]
yuck

**Comment by WJohn** [comment]
those look awful.

**Comment by Fox-McCloud** [comment]
Ugly as sin.

**Comment by JMoldy** [comment]
Out of everything you could port from vg why do you port the single worst thing?

**Comment by FloranOtten** [comment]
Looks horrible. Instead of ugly dance, how about giving regular drones an instrument function and allow them to tapdance.

**Comment by plapatin** [comment]
why would drones need instruments

**Comment by ExcessiveUseOfCobblestone** [comment]
If you plan on respriting these to be more in line with our other drone designs then ok but rn they look like poopies

**Comment by N3X15** [comment]
;_;

**Comment by PJB3005** [comment]
Y'all are completely uncultured.

**Comment by ValkyrieSkies** [comment]
I didn't realize TG's taste was THIS bad.

**Comment by DrSnips** [comment]
TG: That mommi sprite is ugly and doesn't match our style.
Also TG:
tg

**Comment by ExcessiveUseOfCobblestone** [comment]
nani

**Comment by 81Denton** [comment]
wtf I hate cobby now?

**Comment by ExcessiveUseOfCobblestone** [comment]
necromaintainer

**Pull request closed without merging**
