### PR TITLE
Adds Harmabe to the rare name list for pun pun

### PR DESCRIPTION
**Pull request by Incoming5643**
Add Harambe as a possible name for pun pun?
We must honor our great meme ape: 20
He has no style, he has no grace, this meme is a fucking disgrace.: 3
Did not vote: 52

### CODE REVIEW

**Comment by Incoming5643** [comment]
:fried_shrimp:

**Comment by Incoming5643** [comment]
To be fair the rare pun pun name list is the very definition of a meme dumping ground

**Comment by PKPenguin321** [comment]
reopen

**Comment by ike709** [comment]
only oranges is allowed to close good PRs

**Pull request closed without merging**
