### PR TITLE
[READY] Overhauls Pubby Cargo

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This PR completely redoes the layout for PubbyStation's Cargo department, adding plenty of quality of life improvements and significantly changing cargo gameplay compared to every other map through the addition of a cargo docking arm instead of direct docking.

The primary features are thus:
1.The QM gets a corner office that allows him to act as a foreman.
2.The Cargo Bay's layout is drastically changed, repurposing the warehouse as a loading bay and making the main bay as the primary storage area.
3. The docking arm allows for maintenance to run through a small portion of cargo for sabotage opportunities and creates diverse scenarios for unloading and loading cargo.
4.The cargo bay has a way to directly distribute ordered crates to the delivery office.
5.The disposal room (taken from Delta) now shoots trash away from the station and potentially loops around to arrivals.

Kudos to @Zytolg for their advice and critique on layout and other issues in earlier drafts.

Old Cargo:
https://user-images.githubusercontent.com/63861499/92770495-ff61c500-f367-11ea-9a69-7672c1497999.png

New Cargo:
https://user-images.githubusercontent.com/63861499/92770848-59628a80-f368-11ea-8bf4-77a8e75d2f0c.png

I playtested this as regular crew and AI, and surprisingly everything worked the first time around minus a few small things that I have fixed. @ me on discord if you notice problems.

Here also is an image with the cables and disposals/atmos included as per @Timberpoes ' request
wew

## Why It's Good For The Game

Pubbystation has been severely neglected in terms of improvements, and needs enhancements that continue to diversify it from the rest of the maps without changing its overall atmosphere. By introducing these new layouts and thus gameplay elements, I hope to make alternate maps more enjoyable and provide diversity in play.

## Changelog
:cl:
add: A completely new cargo department for Pubby Station, try it (and the new Cargo Arm™) out!
/:cl:

### CODE REVIEW

**Comment by Cartographer-D** [comment]
Trying to fix this absolute cluster, gimme a bit.

**Comment by Cartographer-D** [comment]
OK. Everything should be fixed! Had some issues with typepaths as the original branch was made before the 5 layer PR was merged. Before merging please double check to make sure that the atmos is good and I didn't accidentally delete something important.

**Comment by Cartographer-D** [comment]
Here is the new cargo shuttle for Pubby:
image

**Comment by EOBGames** [comment]
image
duplicate cameras here in the mining dock

**Comment by EOBGames** [comment]
image
two APCs in the cargo lobby

**Comment by EOBGames** [comment]
there's no air alarms in the QM's office, warehouse, cargo bay, cargo lobby, or mailroom

**Comment by EOBGames** [comment]
image
uh oh (maint loot/trash spawner in wall above the warehouse)

**Comment by EOBGames** [comment]
Alright now I think that's most of the technical stuff out of the way, it's opinion time

I feel like the walk out to the shuttle will be too much, reducing it by 2 or even 4 tiles would be quite a bit nicer.

The little nook the public bounty pad is in looks kinda awkward on the corner there. Not sure how I'd fix that, but perhaps replacing the firelocks with a wall/window and adding some decoration (tables, racks, whatever) would help.

Some of the placement of trimlines feels a bit off, but that's probably just personal preference.

A lizard plushie, but no name for it? That's a paddlin'.

All in all I like this design quite a lot- excellent work!

**Review by Timberpoes — APPROVED** [review]

**Comment by kopoba** [comment]
right got no maintenance access
image
carates stuck on this outlet if there is many caretes in disposal pipes transition
image

**Pull request merged**
