### PR TITLE
Fixes features not updating when changing character slots

### PR DESCRIPTION
**Pull request by vinylspiders**
## About The Pull Request

What it says on the tin. The entire bottom half of the prefs was not updating on switching character slots.

~~We need to use the old hook here because it needs the key to differentiate the active slot.~~

edit: useEffect can work in its stead here as mothblocks pointed out 👍 

## Why It's Good For The Game

Bugfix for a kind of serious issue for downstreams, not so much here because there aren't really any text fields being used as features.

## Changelog

:cl:
fix: fixes features not updating when changing character slots
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
> @jlsnow301 if you can think of a better solution for this feel free but this is all I've got for now

in situations where we still need this type of functionality, uselocalstate is fine. perhaps one day we can change uselocalstate internally

**Review by Mothblocks — CHANGES_REQUESTED** [review]
I don't think it's necessary here:

```ts
useEffect(() => {
    setPredictedValue(props.value);
}, [ data.active_slot ]);
```

...sohuld work.

**Comment by Ben10Omintrix** [comment]
> this was the cleanbot-specific runtime I mentioned earlier that was for whatever reason not fixed by #80262 . Did you ever apply the fix you mentioned in the comments? Seems to still be happening unfortunately... : (
i did. looks like ill have to figure something else out

**Comment by Ben10Omintrix** [comment]
> Also unrelated to this PR but mentioning it because CI got the spurious runtime, @Ben10Omintrix
> 
> image
> 
> this was the cleanbot-specific runtime I mentioned earlier that was for whatever reason not fixed by #80262 . Did you ever apply the fix you mentioned in the comments? Seems to still be happening unfortunately... : (

i did. looks like ill have to figure something else out

**Pull request merged**
