### PR TITLE
Added chameleon insulated gloves and sunglasses to the chameleon kit

### PR DESCRIPTION
**Pull request by isaac-smothers**
## About The Pull Request

Modified the chameleon kit to use real chameleon insulated gloves and sunglasses and increased the cost by 2

- Replaced chameleon mesons with sunglasses. Default state looks like normal sunglasses, protects you from flashes while having chameleon abilities.
- Replaced chameleon fake insulated gloves with real ones that protect you from shocks and keep chameleon abilities

## Why It's Good For The Game

In the current meta every traitor needs flash protection and a pair of insulated gloves, otherwise they will be destroyed by a single flash or one shocked door. Thus every shift a traitor must break into a sec locker or rob someone for their shades, or if on delta find them in maint. Then they must break into engineering or use cargo to obtain insulated gloves. 

This takes up valuable time that you could be putting towards your planned gimmick, and is a necessity every single shift as a traitor. It is monotonous and time consuming. You can always buy an infiltrator suit or syndi hardsuit for flash protection, but those are obvious and don't provide synergy with a stealth playstyle (sneaking boots be damned). 

This update adds flash protection (cham sunglasess) and shock protection (cham insulated gloves), saving you time and the potential to get killed by a flash while hunting down protection. This enables you to spend more time on your gimmicks or objectives or more interesting and valuable time sinks.

All of these together make for a worthy starting point for any traitor that will cost you 4 tc total, 2 more than the original chameleon kit

## Changelog
:cl:
Added chameleon insulated gloves and sunglasses to the chameleon kit
Upped the chameleon kit cost by two tc
/:cl:

### CODE REVIEW

**Comment by xlink97** [comment]
merge it or I will shank the children and skin your loved ones

**Comment by optimumtact** [comment]
straight up powercreep 👎

**Comment by xlink97** [comment]
I think you should merge this pr

**Comment by xlink97** [comment]
Haha me too, it's a really good pr

**Comment by xlink97** [comment]
omg me three yeah totally merge this

**Comment by xlink97** [comment]
orange man I'm going to shit on your children and make a PR to remove you if you don't shut your orange juice filled mouth

**Comment by ATH1909** [comment]
Make sure that this won't be better for loud traitoring (due to the noslips and armor) than the syndicate infiltrator suit.

**Comment by MoonFalcon** [comment]
@ATH1909 

**Original chameleon:**
TC: 2

- suit: `armor = list("melee" = 10, "bullet" = 10, "laser" = 10, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)`

- mesons: `armor = list("melee" = 10, "bullet" = 10, "laser" = 10, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)`

- gloves: `armor = list("melee" = 10, "bullet" = 10, "laser" = 10, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)`

- hat: `armor = list("melee" = 5, "bullet" = 5, "laser" = 5, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)`

- armor: `armor = list("melee" = 10, "bullet" = 10, "laser" = 10, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)`

**Advanced chameleon:**
TC: 8

- suit: `armor = list("melee" = 15, "bullet" = 15, "laser" = 15, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 10, "fire" = 50, "acid" = 50)`

- glasses: `armor = list("melee" = 10, "bullet" = 10, "laser" = 10, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)`

- gloves: `armor = list("melee" = 10, "bullet" = 10, "laser" = 10, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)`

- helmet: `armor = list("melee" = 35, "bullet" = 30, "laser" = 30,"energy" = 40, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)`

- armor: (unmodified)

**Infiltrator:**
TC: 6

- suit: `armor = list("melee" = 10, "bullet" = 10, "laser" = 10,"energy" = 10, "bomb" = 0, "bio" = 0, "rad" = 10, "fire" = 50, "acid" = 40)`

  - suit flags: `resistance_flags = FIRE_PROOF | ACID_PROOF`

- no glasses, but mask: `armor = list("melee" = 10, "bullet" = 5, "laser" = 5,"energy" = 5, "bomb" = 0, "bio" = 0, "rad" = 10, "fire" = 100, "acid" = 40)`

  - mask flags: `resistance_flags = FIRE_PROOF | ACID_PROOF`

- gloves: - no armor `resistance_flags = FIRE_PROOF | ACID_PROOF` 

- armor: `armor = list("melee" = 40, "bullet" = 40, "laser" = 30, "energy" = 40, "bomb" = 70, "bio" = 0, "rad" = 0, "fire" = 100, "acid" = 100)`

  - armor flags:
```resistance_flags = FIRE_PROOF | ACID_PROOF```
```strip_delay = 80```

- helmet: `armor = list("melee" = 40, "bullet" = 40, "laser" = 30, "energy" = 40, "bomb" = 70, "bio" = 0, "rad" = 0, "fire" = 100, "acid" = 100)`

  - helmet Flags:
        `resistance_flags = FIRE_PROOF | ACID_PROOF`
	`flash_protect = FLASH_PROTECTION_WELDER`
	`flags_inv = HIDEHAIR|HIDEFACIALHAIR|HIDEMASK|HIDEEARS|HIDEEYES|HIDEFACE`
	`flags_cover = HEADCOVERSEYES | HEADCOVERSMOUTH | PEPPERPROOF`
        `strip_delay = 80`

**Comment by MoonFalcon** [comment]
@ATH1909 
suit: cham better armor by 5 for melee bullet and laser, but is not fire / acid proof while infiltrator is

glasses: infiltrator has no glasses, default cham mask will provide 5 protection for melee bullet and laser

mask: infiltrator wins by 5 for melee, masks are same for bullets and laser, and infil has 5 better for energy. Infil also comes with 10 rad protection + fire / acid proof. Both have voice changer capabilities.

Gloves: Default Chameleon / advanced cham are better in armor for hands, infil has 0 but is fire + acid proof

armor: infiltrator has far better armor plus strip delay, fire resist and acid proof. We are talking melee 10vs40, bullet 10vs40, laser 10vs30, energy 0vs40, bomb 0vs70.

helmet: infiltrator better: melee 35vs40, bullet 30vs40, laser 30vs30, energy 40 vs 40, bomb 25 vs 70, fire and acid proof plus a strip delay, flash protection.

I don't know what other features infiltrator clothes have, but I do know it comes with a bigass weapons case too that fits in your bag and provides extra storage.

**Comment by MoonFalcon** [comment]
@optimumtact thank you for your input, can you explain how? the old kit will definitely still be viable as a 2 tc full outfit changer, identity hider, and voice changer. Plus it will still be utilized by contractors. 

Removing the original 2tc option seems like a bad idea as it can still be used in a lot of different ways.

**Comment by necromanceranne** [comment]
I made infiltrator to be as dead obvious to observers as the hardsuit that you're a badman when spotted. This adds a lot of very invisible armor and even on the Infiltrator I think I shouldn't have added armor to certain parts like the mask, and just folded it into the helmet and made the jumpsuit a body suit. (Which is actually probably going to be a followup at some point)

Chameleon kits having armor is maybe a mistake. I don't think this serves any purpose other than to aggravate issues with armor stacking, and especially from hidden values you cannot predict. If this suit is worn together it isn't that different to the Infiltrator except that you get to hide the fact that you are a tot.

**Comment by 2whatever2** [comment]
Finally i always have to grab the required shit i need for traitoring before ACTUALLY traitoring. This helps a lot instead of having to get the required flash protection and gloves from engineering and a sec locker. Whenever i decide not to get these required equipment i just get fucking cucked by a flash or shocked door

**Comment by Kelenius** [comment]
This actually seems rather overpriced for 8 TC.

**Comment by BigGrease** [comment]
I love stealth antag, and I must admit I haven't used infiltrator once yet because of that. This suits my antag playstyle down to the ground, and I would definitely make use of this if it was merged! I resent the idea of it being powercreep, because it even has a higher cost than infiltrator, so its not like you can pair it with too much "epic antag weapons n gamer gear" 

Great first PR, imo! Very ambitious! Will be watching this closely. I think lovers of the stealth antag playstyle have been waiting for something like this for a long time. I hope it gets a chance!

**Comment by LemonInTheDark** [comment]
I hate to say it, cause this is your first pr, but this really feels like powercreep. If we have something in game that does this - some buffs, and what you're paying for is to not have to be stealthy and collect equipment, that feels like it demeans the thematic and gameplay goals of traitor to make things easier to do on the antag's end.

**Comment by MoonFalcon** [comment]
@LemonInTheDark 

For insulated gloves you can:
- Break into engineering and steal insulated gloves. Half the time you do this you will run into a valid hungry engineer that you then have to kill. If you are noticed during this process you have to kill everyone who comes after you.
- Order insulo's from cargo, with the potential to not get them at all, wasting a lot of time either way
- Spend 1 tc on a toolbox with combat gloves that are not covert at all, even if machine washed with a crayon

For sunglasses you can: 
- Break a sec locker. They are at arrivals or every department and even in security. Doing this will almost always get noticed as they are in public places. If you do not want to be noticed you will have to spend a large amount of time playing it out and probably use thermals or a stealth tool to avoid detection, wasting tc and time. 
  - You also have to make a spear to do this or steal a fireaxe. It is a very repetitive process and imo doesn't add any value to the game, and definitely doesn't add any stealthy situations. Its super feasible, but most times will result in you either getting validhunted or chased down by sec who can flash you before you break the locker.
- Get them from bartender (The "stealthiest" option)
- Buy an infiltrator suit or syndi hardsuit (both extremely non stealthy)

The reality of these situations is that no one ever takes the stealth option because of the time sink and potential tc waste. They just break into arrivals with a spear and break the locker then break into engi steal the gloves and kill whoever comes after them. 

Flashes and insulated gloves are "equipment checks" that will ruin your shift if you do not have them. I am trying to reduce the annoyance of these requirements as I do not feel the process of gathering this equipment is beneficial to the game. Doing the same B&E jobs every time you get traitor is repetitive and boring, and highly predictable.  

With an advanced chameleon kit you can spend that time you would on gathering playing requirements on things like your objectives, stealing actually interesting items like weapons, AI upload boards, one of the many other equipment checks, RPEDs, the list goes on.

**Comment by optimumtact** [comment]
You are literally reducing the decision states a user has to make and therefore reducing gameplay.

I will be closing this at the 24 hour mark.

**Comment by MoonFalcon** [comment]
I would say it is trading invaluable gameplay for valuable gameplay. Instead of having to perform the repetitive action of breaking into arrivals locker and engi every shift you can put that time towards something creative or more crew involved.

**Comment by MoonFalcon** [comment]
@necromanceranne here are the stats of the combined total armor points for original and new cham and infiltrator 

melee
Original cham: 50
Advanced cham: 85
Infiltrator: 100

bullet
Original cham: 50
Advanced cham: 80
Infiltrator: 95

laser
Original cham: 50
Advanced cham: 80
Infiltrator: 75

energy
Original cham: 0
Advanced cham: 40
Infiltrator: 95

bomb
Original cham: 0
Advanced cham: 25
Infiltrator: 140

You are right that in some points it gets close or is even slightly ahead, but it is more expensive and you are making tradeoffs. 

- For 6tc you get very good head and body armor and all the perks that come with infiltrator (no noise when walking, voice changer, etc), as well as complete fire and acid protection. With infiltrator you also get really good bomb protection and a large carrying case.

- For 8tc you get stealthier armor than infiltrator that is focused on head protection but without fire / acid protection and generally worse armor stats other then laser. You also get no-slips and gloves. 

- Both have voice changers. 

The adv cham kit should have some decent armor in the head, I understand if we may need to bring the jumpsuit armor down a bit, but I believe it makes appropriate trade offs when compared to infiltrator otherwise. I was thinking with adv cham that, while you still sacrifice armor for stealth, it is not as severe as the original chameleon kit which is rid of armor almost completely.

I could also modify the armor values and put them in the vest instead of the jumpsuit to somewhat improve "visibility". The armor increase is really coming from the helmet, as the jumpsuit has only been bumped by 5 for each of its stats from the default chameleon kit jumpsuit.

**Comment by ATH1909** [comment]
> You are literally reducing the decision states a user has to make and therefore reducing gameplay.
> 
> I will be closing this at the 24 hour mark.

???????????

This ADDS a decision. 8 TC is a CONSIDERABLE cost; this isn't a "free pick" every round.

**Comment by Kelenius** [comment]
I think a decision of "do I want to spend a bunch of TC and get this shit here and now without risk or do I try to steal them" is fairly good, and I'd even make it cheaper because honestly, 8 TC. That's a lot. 1/3 of your reserve. You can get things you can't get anywhere else, or powerful weapons, or you can get sunglasses, insuls, noslips, and shoddy armor.

**Comment by BigGrease** [comment]
honestly i think the creator of this pr has made his point very well. I am legitimately deeply saddened that this pr isn't being given a chance, and i almost want to say it's down to personal feelings towards the creator and/or a lack of understanding, or stubborn refusal to understand, or a frank lack of care about the reality of gameplay on bagil and gross negligence to address legitimate issues that stand in the way of fun gameplay. 

rounds can be as short as 30 minutes, because bagil is chaotic and completely unpredictable. every second counts. you need to have all your bases covered. this is an OPTION for traitors who WANT to complete their objectives well and remain undetected, while still having a fallback if they are in the form of the armor and sunglasses. 

as has been said, there are known ways to get sunglasses and gloves, but these take time and are very risky. perhaps the risk is appropriate for the high value and utility of the items, but then so shouldn't the cost of this item packet?

by the way, oranges has played 3 rounds in the past 6 months. does he really understand the current meta of the game to make these kinds of decisions? dare i say it? he's out of touch, and refuses to get back into touch. he's literally a cranky old man stuck in his ways who hates change. since this pr is going to be closed anyways, i don't feel any inhibition saying this. The way oranges is running things is inappropriate and intolerable, and I don't understand why he came back if he was just going to be a cranky, rude, angry ass again. ass in the way of donkey, not the butt. cause he's so stubborn! 

oranges? more like lemons. where's cave johnson when you need em? sourpuss.

**Comment by BigGrease** [comment]
[](https://cdn.discordapp.com/attachments/701572761075712093/720187851739889724/Capture.PNG)

link to an image captured from discord showing his bias. yes, i have a bias, too, but its only because i am invested in the idea behind this pr.

**Comment by saprasam** [comment]
oranges will never play the game for long periods of time i dont know what you're expecting

**Comment by Doosteroni** [comment]
How about...infiltrator is 7tc but it gets sweet biker shades

**Comment by MoonFalcon** [comment]
@necromanceranne I would say there’s a big gameplay difference between actual stealth (trying not to be noticed) and being loud but hiding your identity 

@doosteroni infil already had a flash protection

**Comment by MoonFalcon** [comment]
Now that I have removed the jumpsuit / helmet armor I am just going to change this PR into a revamp of the original chameleon kit, adding chameleon sunglasses and chameleon insulo's and changing the cost to 4 instead of 2. It will not come with no-slips.

**Comment by MoonFalcon** [comment]
Updated the files, description, and changelog. Now the chameleon kit will cost 4tc and come with sunglasses and insulated gloves that have chameleon functionality.

**Comment by ATH1909** [comment]
> Updated the files, description, and changelog. Now the chameleon kit will cost 4tc and come with sunglasses and insulated gloves that have chameleon functionality.

Could you also give some form of sonic protection to the chameleon headset? Otherwise, you'll still need to tide for a bowman headset to not get cucked by flashbangs (and said bowman headset won't be able to transform alongside the rest of your disguise), kind of invalidating the point of this PR...

If people are concerned about "hidden" flash protection/shock protection/ear protection, you could make the flash protection/shock protection/ear protection values (but not, say, the armor values) of the pieces of the chameleon set match whatever pieces of clothing you have them currently disguised as. So, for example, in order to get flash protection from chameleon sunglasses, you'd need to have them be in the form of a piece of eyewear with flash protection (sunglasses, secglasses, welding goggles with their visor down, etc.).

**Comment by MoonFalcon** [comment]
@ATH1909 I consider flashbangs a lot less of an equipment check / threat than the flash. Not to mention only sec have flashbangs while anyone can have a flash

**Comment by Fikou** [comment]
i dont like chameleon kit price being doubled because now theres shades and insuls

**Comment by Doosteroni** [comment]
> i dont like chameleon kit price being doubled because now theres shades and insuls

Eh I think being able to be anyone at any time should cost more than a few tic tacs

**Comment by evilcyborgmrt** [comment]
To be fair, to be anyone at any time you also have to purchase an agent ID card.

And isn't the purpose of the chameleon kit to hide your identify? Shades and noslips are meant to protect you once you are found out. Seems kind of contrary to the purpose of the cham kit.

Why not just add shades along with the noslips already available on the uplink?

**Comment by Tlaltecuhtli** [comment]
you can buy insuls for 1 tc with the toolbox, and shades are everywhere there is no need for this especially if you are pumping the tc price

**Comment by MoonFalcon** [comment]
@Tlaltecuhtli Combat gloves are not stealthy

**Comment by Tlaltecuhtli** [comment]
then spend 1 tc for cash and buy them from cargo/vendor lol

**Comment by MoonFalcon** [comment]
@tlaltecuhtli if you read the earlier posts the point of this pr is to free up time spent on repetitive or monotonous tasks like collecting sunglasses after breaking into sec lockers or ordering gloves or stealing from engi.

Freeing up this time allows you to make more interesting choices as an antag

**Comment by Tlaltecuhtli** [comment]
make cham gloves and glasses take those properties if you hit them with the specific items

**Comment by Doosteroni** [comment]
Suggestion: 1 tc item: “Polarized Lenses”. Use them on eyewear to make it flashproof. Might also want to make it incompatible with night vision and thermals

**Comment by optimumtact** [comment]
good day sir

**Pull request closed without merging**
