### PR TITLE
Meta update to kitchen with shared biogenerator

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request
This was primarily to get the biogenerator in botany to be shared with the kitchen. That goal has been reached. The kitchen underwent some remodeling with this change. Seating was added to the hallway, and the layout of the room has been reworked.

biogenerator shared v4

## Why It's Good For The Game
The hallway seating has more people involved in hallway activities creating more interactions.
If you want to eat you do not have to enter the bar, if you do not like alcohol, or people are getting crazy in the bar. 
The line of the hall was pushed back for the Botany counter, and this keeps the nice visual flow.
Lets the Chefs interact with more people having a second window.
Give a nice prep table to the cooks, the old one was to small to work with, more so if you had two cooks.
The Biogenerator is the source of milf and stuff that the chefs need, they should have access to it. and it gives botany a reason to dump stuff in it constantly if they want more food.

## Changelog
:cl:
tweak: Moved the Biogenerator to be shared with the kitchen
add: Hallway counter to the kitchen
tweak: Changed the layout of the kitchen
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I love the hallway seats, gives it a cooler diner feel.

**Comment by Iatots** [comment]
Where am I gonna drag the fridges now?

**Comment by gryffinp** [comment]
Is it possible to get a table next to the microwaves somehow? Possibly by swapping the fryers with the east side of the center table? Having a place where things get sliced next to the place where things get cooked is very useful and saves a lot of tray micro. Other than that, looks excellent.

**Comment by nightred** [comment]
I swapped the fryers to the back of the kitchen gryffinp.

**Comment by RaveRadbury** [comment]
I really like this change

**Comment by jdawg1290** [comment]
Total ideaman moment but what if the bar were in the bottom left corner of the theater?

**Comment by kriskog** [comment]
Looks nice :)

Add a firelock over the biogen

**Comment by nightred** [comment]
I put a firelock over the biogenerator, I just have not updated the image.

**Comment by kriskog** [comment]
Not a fan of the glass door into freezer. We all know where the meat comes from, but noone wants to KNOW know. Also more camera coverage which is bad.

**Comment by nightred** [comment]
That is a render issue with strongdmm.
This is what it looks like in game, also see the shutters to the hall are closed.
biogen ingameshot

**Comment by Farquaar** [comment]
Not the biggest fan of the hallway counter addition, but it's not too hard to rebuild the window there, so I don't mind too much.

**Comment by kriskog** [comment]
Ah, gotcha

**Comment by nightred** [comment]
This looks like everything is working as intended now.
I see no more requests that are reasonable at this time, I am not remaking the bar in this.
I believe this is ready for a test at the minimum.

**Pull request merged**
