### PR TITLE
WHAT IS THAT

### PR DESCRIPTION
**Pull request by Iamgoofball**
# WHAT THE FUCK IS THAT

### CODE REVIEW

**Comment by YakumoChen** [comment]
Fuck off goof?

**Comment by mattroks101** [comment]
Honestly though, fuck that github program.

**Review by Cyberboss — APPROVED** [review]

**Comment by Tacolizard** [comment]
it sucks but i still use it for some reason

**Comment by kevinz000** [comment]
i use it though

**Comment by Iamgoofball** [comment]
This explains a lot about you

**Comment by kevinz000** [comment]
yeah and still less bugs than you

**Comment by FantasticFwoosh** [comment]
I use the program (Its actually useful if you never use the UI for ANYTHING but commits and use bash instead) but its outright broken when it says 'open to github desktop' because it does NOT synchronize & clone repositories.

For instance, you can write out a entire PR from the compiler without backing out to save your changes, run the created compiler byond executable through dream demon to test, come back and then push & publish a branch brand spanking new. You have to clear out the file and re-clone your repository though after each function in order to follow the master.

**Comment by lzimann** [comment]
Change so option 2 is use shell

**Comment by AnturK** [comment]
Please give this PR title that indicates the content or it will have to be closed.

Can't disagree with the content though. The ZIP suggestion should have a warning it's only useful if you don't want to contribute.

**Comment by Dorsisdwarf** [comment]
I use tortoiseGit because I dont like command line interfaces, but what the hell is "git for windows"

**Comment by mattroks101** [comment]
Sourcetree best tree.

**Comment by Really-Good-Soda-Flavor** [comment]
Advanced users don't need to read a manual, so I think it's unnecessary to remove something that is very helpful to new users.

**Comment by lzimann** [comment]
Afaik github for windows is really buggy/doesn't work properly in some situations. So removing this is a good thing for new users.

**Comment by kevinz000** [comment]
^ yeah it's inferior and only for the lazy.

**Comment by FantasticFwoosh** [comment]
@AnturK i committed my first 2 pr's entirely from zip files and i do still regularly hoard ZIP's of repositories, it hardly makes you a non-contributor as much as a web-git user.

**Comment by lzimann** [comment]
Downloading zip is far from ideal, it leaves you with a copy that is not easy to update(you will have to redownload the entire repo everytime), might be ok for a small change here and there, but installing git and cloning the repo makes the whole process(from updating to pushing your changes) way easier.

**Comment by PKPenguin321** [comment]
Definitely use git shell for as much as you can and maybe like tortoise or something for committing/comparing changes

**Comment by Iamgoofball** [comment]
90% of the problems with git we have fall under 1 of 2 categories:
1. They used github for windows and it broke badly.
2. They're doing super complex git command line shit and we need to summon a git wizard like oranges or MSO.

**Comment by optimumtact** [comment]
s/github for windows/any of the git clients other than git bash/

**Comment by Poojawa** [comment]
The only thing I've noticed desktop github having issues with was when maps are being edited, elsewise it's worked just fine. sometimes a merge conflict needs bash opened for a git add .

**Pull request merged**
