### PR TITLE
Prayer response voice is generalized again

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
> get a prayer to the honk mother
> hit the easy reply link
> respond as space satan
> no feedback telling me I even replied as satan

### CODE REVIEW

**Comment by xxalpha** [comment]
What?

**Comment by Jordie0608** [comment]
Why not let admins choose the name?

**Comment by Shapsy** [comment]
Admin prayers currently use the name of whatever deity the chaplain chose (or space jesus for default), but there's no way for admins to tell what they're gonna show up as so

**Comment by Jordie0608** [comment]
Default in input() can just be set to ticker.Bible_deity_name

**Comment by tkdrg** [comment]
I dunno, I think it makes sense to keep SM as a quick generic thing, and letting admins use Direct Narrate if they need more control. Maybe wait for @KorPhaeron to chime in here.

**Comment by KorPhaeron** [comment]
I don't really want an extra window every time I sublte message yeah.

**Comment by drynwyn** [comment]
>implying the honkmother is not space satan

**Pull request merged**
