### PR TITLE
Shitty ideas thread: 3. Mecha Punching glove! the Oingo Boingo Punch-face!

### PR DESCRIPTION
**Pull request by MrsTonedOne**
:cl: RemieRichards
add: A New weapon for clown mechs, the Oingo Boingo Punch-face! it's a giant boxing glove that extends out on a spring and sends atoms flying (including anchored ones and things that make no sense to move because -clowns-)
/:cl:

Oingo Boingo (No embeds because xbawks #heug)
http://i.imgur.com/R8OVKuQ.gif
http://i.imgur.com/MCjsbX1.gif
@RemieRichards
Closes #23180

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Anchored atoms moving though?

**Comment by kevinz000** [comment]
so basically a mech with flightsuit collision mechanics ok

**Comment by MrStonedOne** [comment]
>flightsuit collision mechanics

\>implying i know what that is.

**Comment by XDTM** [comment]
Anchored items already move with meteorshot and it doesn't really get abused.

**Comment by Supermichael777** [comment]
that's more an access issue if you can get meteor shot you can get pulse slugs and those are just better

**Comment by kevinz000** [comment]
@Supermichael777 40 brute + 8 weaken + get rid of anything but a wall vs 50 burn + get rid of nothing but a wall

**Comment by XDTM** [comment]
Also bananium is rarer than rcd cartridges

**Comment by Supermichael777** [comment]
based on cost

**Pull request merged**
