### PR TITLE
Biogen doesn't dispense reagent containers anymore

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request
This only changes it so that the reagent container you put in the biogenerator gets used much more since you cannot create reagent containers with it anymore

## Why It's Good For The Game
Removes conistency issue and makes the bucket you put in there be actually necessary and not just fluff for the most part.

## Changelog
:cl:
del: Removed all reagent container outputs from biogen designs, replaced with reagent designs that feed into the container currently placed in the biogen
tweak: all plant nutriment produce 30u instead of 50 for the same biomass price
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
literally why

**Comment by spessbro** [comment]
> 
> 
> literally why

because i can :)

**Comment by Tlaltecuhtli** [comment]
why not remove the container and let it dispense bottles instead

**Comment by shellspeed1** [comment]
I'm going to be honest, this pr seems pointless and just aimed at making botany more annoying.

**Comment by Shadowflame909** [comment]
Why can people be so cruel.

Oh woe is me

**Comment by MCterra10** [comment]
I thought the attached container was responsible for holding processed biomass?

**Comment by lolman360** [comment]
it's used purely for the milk/cream functions now (which are useless becasuse there are functions that give milk or cream in bottles which everyone uses anyways)

**Comment by ExcessiveUseOfCobblestone** [comment]
> del: Removed all reagent container outputs from biogen designs

lol...

**Comment by shellspeed1** [comment]
> it's used purely for the milk/cream functions now (which are useless becasuse there are functions that give milk or cream in bottles which everyone uses anyways)

Milk function is useful, dispense 10 enzyme, then just add milk for cheese. I use it quite a bit when I play chef.

**Comment by ExcessiveUseOfCobblestone** [comment]
now everyone will :^)

**Pull request merged**
