### PR TITLE
Accessibility fix: Ganghud colorblindness

### PR DESCRIPTION
**Pull request by OneArmedYeti**
Added colorblind fix for Ganghud, at present Red-green colorblind players cannot easily distinguish between gangsters and gangleaders. Changed sprite such that gangster icon is slightly smaller and gangleader icon has a border.

### CODE REVIEW

**Comment by duncathan** [comment]
:+1: this is the kinda shit we need
Huge props for doing this

**Comment by bgobandit** [comment]
:100: I didn't even think of that

**Comment by KazeEspada** [comment]
Pics please if you could.

**Comment by OneArmedYeti** [comment]
Here's the before and after

gangphotoshopfix

**Comment by tkdrg** [comment]
Neat idea.

**Pull request merged**
