### PR TITLE
Fixes plastic reaction creating 10 sheets for all reagent amounts

### LINKED ISSUE #38292: Can create 100 plastic sheets from 100u chemicals
During creation of plastic sheets in chemistry, you can circumvent the usual 10u -> 1 plastic sheet ratio by adding small amounts of the final ingredient to an already heated mix. 

[Reproduction]:
Using the following recipe: 20 Sulphuric acid, 30 Ash, 50 Oil.
Heat a beaker containing 2/3 of the ingredients needed to create plastic sheets (tested with sulphuric acid and ash) to between 374K (Plastic sheet) and 480K (oil -> ash). Add 5u of oil, which results in enough ingredient for the reaction to 1 plastic sheet. Results in 10 sheets, but only consumes the material to create one sheet. Possible to create 100 sheets from 100u if heated repeatedly.

### PR DESCRIPTION
**Pull request by FrostyFridge**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Frosty Fridge
fix: Plastic creation reaction now properly scales with the amount of reagents; 10u = 1 sheet.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Fixes #38292

### CODE REVIEW

**Review by SpaceManiac — APPROVED** [review]

**Comment by SpaceManiac** [comment]
Actually, is this scaling correctly? Wouldn't you want to divide `created_volume` by 10?

**Comment by Supermichael777** [comment]
10u chems mixed = 1u out created volume = 1 sheet.
so a large beaker filled with the chem makes 10 sheets.

also check to be sure you actually have at least one unit to prevent cig abuse for production

**Comment by Winterous** [comment]
Rip huge amounts of plastic.
Also Spacemaniac: created_volume actually works pretty unintuitively. If a recipe calls for 1 unit of X and 1 unit of Y, you'd assume that created_volume = 1+1, right? It's actually not.

created_volume is is the number of times the ingredients are filled. So if you have 50 of X and 50 of Y, that mixes together 50 times. With plastic's recipe, there are 10 units required to mix, so for every 10 reagents that mix created_volume = 1.

**Comment by OmegaShoots** [comment]
sad day

**Pull request merged**
