### PR TITLE
Adds jobbans for lavaland spawners

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
the end of an era

**Comment by KorPhaeron** [comment]
yeah hopefully this doesn't turn into something overly restrictive and terrible, but we've had people do things like spawn as literally every lavaland role and suicide

**Comment by WJohn** [comment]
>but we've had people do things like spawn as literally every lavaland role and suicide

some people just want to watch the world burn

**Comment by AlexCrimson** [comment]
I hope you permabanned the person who did that. What an incredibly shitty thing to do.

**Comment by Iamgoofball** [comment]
i'll be honest sometimes I get killed as every role but thats just me being bad at the game

**Comment by optimumtact** [comment]
Was it J_Mad

**Comment by GunHog** [comment]
Why not just consider these "ghost roles", and apply that ban type to these as well?

**Pull request merged**
