### PR TITLE
Adds canned air

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
add: Robust Soft Drinks LLC is proud to announce Premium canned air for select markets.  There is not an air shortage.  Robust Soft Drinks has never engaged in any form of profiteering.
/:cl:

The hottest in memes, yet a classic.  Air in a convenient can.  Just throw it!

http://www.mirror.co.uk/news/weird-news/british-expat-selling-fresh-mountain-9939780

https://www.youtube.com/watch?v=SiabeNR_q0U

http://www.snopes.com/michigan-is-about-to-sell-100-million-gallons-of-groundwater-to-nestle-for-200/

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
this is op it allows for space walking more effectively

**Comment by Supermichael777** [comment]
hi chemistry can i get an air pill?

**Comment by ChangelingRain** [comment]
Needs a crushed can sprite in janitor.dmi

**Comment by calzilla1** [comment]
Add peppermint flavor

**Comment by Supermichael777** [comment]
putting mint toxin in it would raise serious balance concerns.

**Comment by FantasticFwoosh** [comment]
Exactly the kind of shitty thing to throw in a oxygenless plasmaman bar/cloning centre. Brilliant

**Comment by calzilla1** [comment]
@Supermichel777 We have taste, just make it taste like FUCKING PEPPERMINT

**Pull request merged**
