### PR TITLE
Nerfixes styptic powder, silver sulfadiazine, and strange reagent; adds pill bottles of bicaridine and kelotane to NanoMed; and changes contents slightly of burn/brute aid kits

### PR DESCRIPTION
**Pull request by Barhandar**
## About The Pull Request

Styptic and sulf no longer heal over time but can heal in VAPOR (i.e. foam and spray bottle) form. Strange reagent is now only usable as intended - by surface application - and will be useless in pills and syringes.

## Why It's Good For The Game

Styptic and sulf were literally better versions of bicaridine and kelotane - same heal over time, but also heal on application and _no overdose_. This makes sure they're dedicated spray heal chemicals, and not powergamer's dream.

## Changelog
:cl: Barhandar
balance: styptic powder and silver sulfadiazine no longer heal over time.
balance: but they now heal in foam (and blob attacks, if anyone adds a styptic blob).
fix: strange reagent no longer works if applied by injection (syringes) and ingestion (pills, food and smoke w/o internals), as indicated by its description.
balance: patches in nanomed have been replaced with pill bottles of relevant reagent.
balance: instead of 3 (4) patches and 2 (0) pills of advanced healchem, dedicated burn/brute kits now have 3 patches, 3 basic healchem and 1 advanced healchem pills.
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
okay but slight concern is does this make synthflesh directly better than bicard/kelo

**Comment by Barhandar** [comment]
Synthflesh is untouched, and doesn't heal over time anyway, only on application.

**Comment by Fikou** [comment]
>no more strange reagent plants
bruh

**Comment by ATH1909** [comment]
> > no more strange reagent plants
> > bruh

Yeah, I'm a bit on the fence about this part of the PR as well.

If anything, strange reagent needs a buff- for some reason, strange reagent needs you to have 80 less brute and burn damage than defibbing does (100 vs. 180), despite supposedly being a magical "miracle chem". Could we buff it to use the same threshold that defibbing does?

**Comment by 4dplanner** [comment]
Just make a liquid contents strange reagent plant, not a real issue

**Comment by Barhandar** [comment]
It's a miracle chem that resurrects the dead regardless of how long they were dead unlike defib, higher requirements are okay. Also, if you have it you'd usually also have synthflesh, which means brute/burn is irrelevant.  
Also nerfing hydroponics is always a plus :^)

**Comment by terranaut1** [comment]
yeah sure make medbay more awful than the removal of the sleepers already made it
>advanced chems are better than base chems
wow?!?!!?!?!?!?!??!?!!?!??!?!?!!?!?
who says SR is intended to be only used in surface application?

**Comment by nemvar** [comment]
```/datum/reagent/medicine/strange_reagent
	name = "Strange Reagent"
	id = "strange_reagent"
	description = "A miracle drug capable of bringing the dead back to life. Only functions when applied by patch or spray, if the target has less than 100 brute and burn damage (independent of one another) and hasn't been husked. Causes slight damage to the living."```

**Comment by miniusAreas** [comment]
you absolute madlad

**Comment by miniusAreas** [comment]
Anyways, actual fucking comment time.
As a medical main both for TG code and Baycode, conclusion is that this PR is retarded.

Neither of these chems are powergamers dreams and it just looks like another fucking attempt to make trekchems snowflake again. If you wana talk fucking powergame, watch me heal some one from crit using a standard fucking first aid kit. Even on bay where bicard is the only thing for brute I still use trauma kits because it's 100% faster than bicard anyways, and bicards jack useless unless someome has IB.

I fucking give this PR a -1. Please fucking go actually get fucking responses from 30 other medical mains and go throw them at me in #coderbus before making any other shit that supposedly "nerfs powergamers".

**Comment by AdamElTablawy** [comment]
stypic and silver sulf are incredibly potent healing chemicals that work amazingly when they're in patches because they heal on application and then over time further, which is why they are the ideal chemical to use in basically all situations for brute or burn except making an autistic deathmix

these chemicals are incredibly simple to make and mass produce and are the only medicines medbay needs aside from charcoal for toxin and mannitol for brain damage. they're not advanced chems-just simple ones.

a nerf is pretty well deserved. 

@miniusAreas bicardine does not treat internal bleeding here on /tg/ because internal bleeding does not exist and it's a surprisingly good brute treatment chemical, albiet not s good as stypic

that being said, stypic and bicardine are about as difficult to make (not at all) and so stypic is basically just the superior chem. you can't OD on it, it heals on touch and over time-so unless you're stacking to make a healmix, you just slap a stypic patch on the guy.

strange reagent, however, blows ass and doesn't need a nerf. by the time you have strange reagent available you could probably just use reconstruction-revival surgery.

**Comment by HomocidlePancakes** [comment]
:clap: MAKE :clap: MEDBAY :clap: MORE :clap: ENGAGING :clap: BY :clap: NERFING :clap: IT :clap:

**Comment by Barhandar** [comment]
>strange reagent, however, blows ass and doesn't need a nerf. by the time you have strange reagent available you could probably just use reconstruction-revival surgery.

Reconstruction-revival surgery takes _way_ longer than a beaker with synthflesh followed by a beaker with synthflesh and SR (or a medspray with them, SR doesn't have unit threshold). How many people do even use specifically pills and syringes for SR, considering the thing that fixes the damage is also surface-only and has been for all this time?

**Comment by ExcessiveUseOfCobblestone** [comment]
synthflesh dead healing is possibly going to get removed in the reconstruct PR if I can bother

**Comment by Angustmeta** [comment]
Styptic and silver sulf will probably cause extreme message and scream spam if used in foam. On live it does that already with the "I don't feel so good', but at least those messages stack.

**Comment by Barhandar** [comment]
They already can cause that if used in smoke. And it doesn't stack because it's ungood-heal-scream-ungood-heal-scream (with foam it'll be heal-scream because it doesn't apply INGEST, only VAPOR). Nonetheless I'll think about how to fix it.

**Comment by Angustmeta** [comment]
Test it. Foam ticks way more often than smoke.

**Comment by HideAndSeekLOGIC** [comment]
They aren't and were never "powergamers' dream". I know this, being somewhat of a powergamer myself.

**Comment by Suicidalpickles** [comment]
there's like no way to get bicaridine for brute damage without chemistry since it doesn't spawn anywhere unlike kelotane (and yes its super easy to make but you cant rely on chemistry all the time)

point is, you're left with like no source of healing brute damage over time since it'd gone from styptic patches.

I'd probably down for this if it at least buffed the healing rate of bicaridine/kelo or stocked med roundstart but this screams of "i ded"

t.med main

**Comment by Barhandar** [comment]
P.S. I've miscounted, it's actually 120 healing per pill so it's a considerable buff to nanomed's potency.

**Comment by Angustmeta** [comment]
I don't think kelo and bicard need any buffs. They've always been decent. This PR does make brute kits rather weak though. Those are the main treatment supplies you can refill from cargo, which will probably nearly never be worth the effort unless their contents are changed. The burn kits will still be relevant since they have oxandrolone pills.

**Comment by Barhandar** [comment]
It makes both kits have 1 oxandrolone/salicylic acid pill (instead of 2 oxa/0salacid), along with 3 pills and 3 patches.

**Comment by HomocidlePancakes** [comment]
Why not add 10 bicord/kelo in to patches instead?

**Comment by Barhandar** [comment]
@HomocidlePancakes wouldn't some idiot try to slap several patches on in a row and get OD?

**Comment by 4dplanner** [comment]
So goof basically said that bicard and kelo basically aren't meant to be good, and were just left in for sleepers.

**Comment by Barhandar** [comment]
Point being that goon is a different codebase with different gameplay and hence vastly different balance, and goof should just play on goon if he wants goonchems to be the only possibility. Also someone tell tlatle that goon has 7.5*REAGENT_METABOLISM for styptic and sulf (i.e. 3 units/chemtick), not 5.

**Comment by AdamElTablawy** [comment]
they weren't meant to be good because sleepers weren't meant to be good or compare to actual chemistry-made chemicals or active doctoring because they were virtually infinite and easy ways to treat patient with no actual expense on the part of medbay

that's not 'goonchems are the only possibility', just that he couldn't do what goon did and make sleepers inject you with stypic, etc, because he wanted chemistry to be involved in helping medbay but not make medbay helpless without chemistry

**Comment by Barhandar** [comment]
Goon's sleepers only inject saline-glucose, ephedrine (??? might be actually epinephrine and a typo on the wiki), salbutamol and charcoal, and also provide oxygen (atmos sleepers when). Their saline-glucose heals 2 damage with chance, instead of 0.5 on TG (and you can't buff that without removing the colossal salglu tank recently added hurr hurr); going by the wiki, their crit also deals brain damage, tg's crit is pure oxyloss.
>because he wanted chemistry to be involved in helping medbay but not make medbay helpless without chemistry

Even big if he actually wanted that, maintainers disagree - currently medbay _is_ eventually helpless without chemistry or robotics, once the meds in their storage run out. Which also means the entire point about sleepers doesn't matter because stasisbeds, and as such, it boils down to pure disagreement on which niche should patchchems occupy - the end-all brute/burn chems (goof), stuff to patch you up while you get to medbay for long-term medicine (goon, remember, on goon 20u styptic will heal 26.6(6) damage because it metabolizes at 3u/tick), or immediate healing only (me).

**Comment by ATH1909** [comment]
> there's like no way to get bicaridine for brute damage without chemistry since it doesn't spawn anywhere unlike kelotane (and yes its super easy to make as said earlier but you cant rely on chemistry all the time)
> 
> point is, you're left with like no source of healing brute damage over time since it'd gone from styptic patches.
> 
> I'd probably down for this if it at least buffed the healing rate of bicaridine/kelo or stocked med roundstart with bicarid pillbottles but this provides like zero benefit to anybody as is.
> 
> source: powergamer med main

Don't some of the flowers that spawn roundstart in the chapel have bicardine in them?

**Comment by HomocidlePancakes** [comment]
@barhandar they would need to use 4 patches to OD and at that point it’s their own fault. I’d rather have medkits have a lil’ amount of good healing items rather then alot of mediocre ones so you don’t have enough heals to last you the entire shift.

**Comment by Barhandar** [comment]
@HomocidlePancakes 3, also you can't replicate the roundstart patches now because they have more reagents than patches can contain hur hur.

**Comment by ExcessiveUseOfCobblestone** [comment]
Was this stale or something? Was on vacay so dunno the conversation about this PR

**Pull request closed without merging**
