### PR TITLE
Fixes spiders locking up the MC with do_after's

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by phil235** [comment]
:+1: :+1: :+1:

**Comment by optimumtact** [comment]
Does this break the spider AI? wouldn't it be relying on those sleeps to ensure it does things in appropriate order after a delay?

**Comment by MrStonedOne** [comment]
the sleeps are for when players use these vars, the spider ai doesn't care.

**Comment by optimumtact** [comment]
I probably should've looked at the code

**Pull request merged**
