### PR TITLE
Adds Life Support Quirk

### PR DESCRIPTION
**Pull request by Acantharctia**
## About The Pull Request

Adds a Life Support quirk that replaces your regular heart with an outdated and fragile one. It will constantly decay even while inside of you on top of also being damaged when its owner is attacked.

It _will_ also carve your chest hollow if it gets too damaged, but that's just minor details.
## Why It's Good For The Game

A quirk for those who want more points to play around with in exchange to having to manage their heart closely or get torn apart.
## Changelog
:cl:

add: Added a new Life Support quirk, replacing your heart with an outdated one. Be careful using it!

/:cl:

### CODE REVIEW

**Comment by FlufflesTheDog** [comment]
We do, but this functions quite a bit differently than the surplus organs it seems. 
Though, i believe this would be the only quirk that puts a timer on people's lives the moment they spawn, without something like meds to counter it

**Comment by lizardqueenlexi** [comment]
What does "manage your heart" mean here anyway? I can't think of any way you're actually meant to restore this heart once it starts failing.

Plus, I feel like there's already a lot of "you are slowly dying" quirks as it is.

**Comment by Acantharctia** [comment]
> What does "manage your heart" mean here anyway? I can't think of any way you're actually meant to restore this heart once it starts failing.
> 
> Plus, I feel like there's already a lot of "you are slowly dying" quirks as it is.

You're right. Originally I had the idea of you being able to repair the heart all by yourself in a similar way to how installing implants on cybernetic arms works.

**Comment by Acantharctia** [comment]
> The way you phrase this as giving you more points to play with is an incorrect approach to thinking about quirks by the way.
> 
> They're ways to make the player a little flavourful and different, not something you optimise your points stack for.
> 
> Makes me quite hesitant to merge such a PR.

I added that thinking it would be better looked upon than the actual reason.

I think it's a neat concept to have what's basically a time bomb inside of you, and also the sheer image of someone in-game starting to die suddenly in the middle of the hallways sounds incredibly fun (and horrifying).

Plus, gives docs another issue when fixing you up.

**Comment by Acantharctia** [comment]
> > What does "manage your heart" mean here anyway? I can't think of any way you're actually meant to restore this heart once it starts failing.
> > 
> > Plus, I feel like there's already a lot of "you are slowly dying" quirks as it is.
> 
> You're right. Originally I had the idea of you being able to repair the heart all by yourself in a similar way to how installing implants on cybernetic arms works.

I figured it wouldn't be accepted if you could just fix it, so I scrapped the idea.

**Comment by Time-Green** [comment]
I don’t like this. This quirk just means you gotta replace your heart roundstart?

**Comment by Acantharctia** [comment]
> This quirk just means you gotta replace your heart roundstart?

The idea is more something you'd need to keep an eye on to make sure you don't end up dying suddenlly;
.

**Comment by Time-Green** [comment]
Sorry, I don’t think this is a good quirk. Passive damage means you need to get it replaced as close to roundstart as possible or accept dying.

Brute damage transferred to internal organ seems a bit arbitrary, it just means avoid damage (not like it matters because you need to get it replaced asap due to the countdown above yout head)

**Comment by EricZilla** [comment]
Why didn't you make it so you spawn with a necklace that you can trigger to alert the paramedics you are dying like medbots do, and the inability to get up after falling down? Oh life SUPPORT not life ALERT my bad

**Pull request closed without merging**
