### PR TITLE
Improves Tesla Performance

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Well, this was interesting.

The Tesla was an obvious candidate for improving performance with filtered typecache...but then it got me to wonder....could you apply a filter to a filter to save even *more* performance? Turns out, yes...yes you can!

Before:
```
Proc Name                                Self CPU    Total CPU    Real Time    Calls
--------------------------------------------------------------------------------------
/obj/singularity/energy_ball/process       0.228       22.716       22.719        10073
/proc/tesla_zap                          16.621       21.738       21.739        10072
```
After:
```
Proc Name                                Self CPU    Total CPU    Real Time    Calls
--------------------------------------------------------------------------------------
/obj/singularity/energy_ball/process       0.149       16.851       16.857        10006
/proc/tesla_zap                          8.114       15.992       16.002        10005
```

Filtered typecache (only once), with `is_type_in_typecache continue` instead of a second filter:
```
Proc Name                                Self CPU    Total CPU    Real Time    Calls
--------------------------------------------------------------------------------------
/obj/singularity/energy_ball/process        0.173       17.550       17.550        10087
/proc/tesla_zap                          8.723       16.617       16.618        10086
```

### CODE REVIEW

**Comment by Supermichael777** [comment]
this is some advanced magic bullshit

**Comment by MoreRobustThanYou** [comment]
i do not understand this so I will say....

**_MAGIKS!!_**

**Comment by Cyberboss** [comment]
Closes #25483 perhaps?

**Comment by Iamgoofball** [comment]
@Cyberboss this doesnt do that

**Comment by Fox-McCloud** [comment]
I wasn't happy with things, so I made it even better.

**Comment by Fox-McCloud** [comment]
It doesn't say anything about that they shouldn't be switched, just that they're "frowned upon" if it's done "for no reason".

The contributing guidelines consistently use `for()` and not `for (`, not to mention my reason is that I'm enforcing backwards consistency with the newly added proc 😛

**Comment by Fox-McCloud** [comment]
@Cyberboss 

Probably not; while this makes the tesla cheaper, it's not going to magically make it so you can suddenly support 40+ of them at once....I'm not sure why that's even an open issue; it'd be like if i created 200 NPC Interactice humans then made the report "game crashes if you spawn 200 interactive AI human mobs".

It's just...not a realistic expectation for the game to support that many of an instance of something.

**Comment by RemieRichards** [comment]
@Fox-McCloud they're not enforced as in you don't have to follow any of the 2 styles, however you SHOULDN'T change them, for what you've done, which is no reason.

**Pull request merged**
