### PR TITLE
Tunes Up The Syndicate Infiltrator

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
BEHOLD:

(Ignore the errors on cyborg limbs, side-effect of Kapulimbs)
I've been sitting on this one for a hot minute. I meant to PR it after I got GAGS Airlocks working - But airlock codes sucks - and #65702 was merged, but I got impatient plus'm getting weird about it so I just decided to bite the bullet.

~~No major balance changes are present within this PR, as it's mostly aesthetic - save the chemmaster's addition. I doubt Nukies'll make a habit of doing dental surgery, though. Things have been changed around or added, however.~~
Chemmaster removed as of commit a9f3dd0 .
Also converts the chairs' map varedits into real subtypes, because I HATE VAREDITS I KILL VAREDITS NO VAREDITS

## Why It's Good For The Game
For being one of the most iconic elements of spacemans, the thing deserves better than the state it's in, and I hope what I've done with it here resonates.

## Changelog

:cl:
expansion: The syndicate infiltrator has been tuned up, coming with a fresh coat of paint, insurance, and the new shuttle smell. Sadly, no complimentary taco in the glovebox.
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
badass except for acting like the chemmaster isn't a massive free buff / balance change

**Comment by unit0016** [comment]
> badass except for acting like the chemmaster isn't a massive free buff / balance change

Open to removing it tbh, Came to me when I saw the drill but before I remembered they *do* get pills in the brute/burn medkits

**Comment by san7890** [comment]
image

Very very very very cute diorama :)

**Comment by Sealed101** [comment]
bring back the donuts box from the shuttle's bridge

**Comment by unit0016** [comment]
> bring back the donuts box from the shuttle's bridge

It's still there, for some reason only the lid renders in the map editor.

**Comment by SmArtKar** [comment]
Some of the rooms feel quite empty, maybe you should add a few tables or some shit to the bottom two rooms

**Comment by Sealed101** [comment]
oh yeah the chair corridor lacks chairs now, how so :(

**Comment by unit0016** [comment]
> oh yeah the chair corridor lacks chairs now, how so :(
> 
> the badass decal in the middle is also of concern since the shuttle is prone to change its directions, won't the decal skew if you park the shuttle not facing north?

Unlike the already-in-game soviet decal, I prepped for this and split it up into 32x32 tiles. Directionals work with it too.
I think this is the third time I've implemented the damn thing, may as well be branded onto me.

**Comment by anclandor** [comment]
Why is there nothing in the closets?

**Comment by unit0016** [comment]
> Why is there nothing in the closets?

There *is* stuff in the closets. Minus the one in medbay, which was more intended to be a place to shove extraneous shit into during surgery rather than actually contain anything.

**Comment by anclandor** [comment]
> There _is_ stuff in the closets. Minus the one in medbay, which was more intended to be a place to shove extraneous shit into during surgery rather than actually contain anything.

Sorry I don't understand mapping I guess.  What is in the lockers in the equipment room then?

**Comment by unit0016** [comment]
> Sorry I don't understand mapping I guess. What is in the lockers in the equipment room then?

One has the standard nukie equipment, other has that plus the military PDA. Same as they were when they were in the armory.

**Comment by anclandor** [comment]
> One has the standard nukie equipment, other has that plus the military PDA. Same as they were when they were in the armory.

Didn't they have stuff other than what's in the standard equipment lockers? (more ammo, nades, etc)

**Comment by unit0016** [comment]
> Didn't they have stuff other than what's in the standard equipment lockers? (more ammo, nades, etc)

No. Everything that wasn't already in a locker was merely repositioned.

**Comment by anclandor** [comment]
> No. Everything that wasn't already in a locker was merely repositioned.

I mean, are those lockers just the standard syndi equipment lockers found on the base proper or are they the special ones with tons of markov ammo and flashbangs in the old lockers?

**Pull request merged**
