### PR TITLE
Removes a vast majority of the uplink for being completely unused.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
del: A vast majority of the uplink, due to them being completely unused for the last 4 months proven by statistics, have been removed.
/:cl:
Everything that has been removed here has been ordered approx. 0 times this year.

Too much shit in the uplink. Here's the stats to back it up.
https://atlantaned.space/statbus/stat.php?stat=traitor_uplink_items_bought&year=2018&month=1
https://atlantaned.space/statbus/stat.php?stat=traitor_uplink_items_bought&year=2018&month=2
https://atlantaned.space/statbus/stat.php?stat=traitor_uplink_items_bought&year=2018&month=3
https://atlantaned.space/statbus/stat.php?stat=traitor_uplink_items_bought&year=2018&month=4

Stop adding useless crap to the uplink.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Don't even try to claim "but I use these"

because the stats dont lie

**Comment by nicbn** [comment]
Changelog

**Comment by iskyp** [comment]
actual fun removal
>surplus rifle is axed
>cqc is axed
>bundles are axed
>NO SLIPS AREN'T USED????
>elite hardsuit is gone?
>power sink goes unused

what

**Comment by MMMiracles** [comment]
haha what a story mark

**Comment by Spaceinaba** [comment]
this is probably just goof attentiongrabbing since the freeze is over and he was irrelevant during it because he can't piss people off with fixes

**Comment by Cyberboss** [comment]
PR based on bad data, also bulk removal like this is anti-CONTRIBUTING.md on it's own

**Comment by AlexTheSysop42** [comment]
Doesn't statbus itself say it's preliminary and non-operational?

**Comment by iskyp** [comment]
yes @AlexTheSysop42

**Comment by PKPenguin321** [comment]
Don't even try to claim "but I play"

because the stats dont lie

goof connections

**Comment by Iamgoofball** [comment]
that is correct

**Pull request closed without merging**
