### PR TITLE
tgui followup

### PR DESCRIPTION
**Pull request by neersighted**
Followup fixes and tweaks in the wake of the tgui merge

### CODE REVIEW

**Comment by newfren** [comment]
It would be nice if you could make the scroll bars that appear on the windows not change the usable width of the window - when you're using the chem dispenser it changes the number of columns you get from 3 to 2 which is incredibly annoying.

**Comment by neersighted** [comment]
Yeah I've been meaning to replace window scrollbars with javascript scrollbars -- I'll see what I can do.. For now, I resized the chem dispenser to be 4 columns and much taller.

**Comment by newfren** [comment]
I mean it's mostly the changing in the number of columns that's annoying not the amount.

**Comment by Aranclanos** [comment]
>14 commits

WEB
DESIGNERS

**Comment by Cheridan** [comment]
they're actual commits though. instead of 14 fuck-up commits named 'asfdfsdf'. it's fine

**Comment by Aranclanos** [comment]
wew its true

**Pull request merged**
