### PR TITLE
Makes crayons use their reagents

### PR DESCRIPTION
**Pull request by QualityVan**
:cl: Qualityvan
tweak: Crayons grind for more crayon powder
fix: Crayons no longer color the floor wherever you draw
/:cl:

Old method was grinding them in a poor way. Also stops crayons/spray cans from trying to move reagents to turfs since turfs don't actually contain reagents.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
There are actually bartender drinks that rely on crayon powder such as green beer, which needs powder of the appropriate colour. That's the only one off the top of my head that i can remember.

**Comment by coiax** [comment]
This removes spray cans of lube and crayons and spraycans colouring the turfs.

**Comment by coiax** [comment]
Special casing all of these various spraycans (which I came up with to demonstrate what you could do with varying reagents in spraycans) doesn't change the fact you're making the code more complicated for no real gain.

Having reagents react to the turf is the simplest and most natural way to have effects happen.

**Comment by QualityVan** [comment]
That's what spray bottles are for. Honestly, the hellcan in particular should really derive from reagent_containers/spray. There's zero functionality it shares with regular spraycans(what's the point of choosing graffiti for a hellcan when it can't paint?) aside from having a cap and spraying contents - which spray bottles do better anyway.

**Comment by duncathan** [comment]
I agree with coiax

**Comment by PKPenguin321** [comment]
Crayons coloring the floor is shit though, you can't see the actual pictures you draw because it blends in with the all-one-solid-color floor

**Pull request closed without merging**
