### PR TITLE
fixes pod hair tgui bug

### PR DESCRIPTION
**Pull request by azrael-x86**
## About The Pull Request

after 3 hours of trying to figure out why this shit bluescreened the pref menu, i finally realized that the fix was as simple as changing a 0 to a 1.

i hate podperson hair now.

## Why It's Good For The Game

not having a bluescreened pref menu is always good

## Changelog

:cl:
fix: fixes a bug that causes podpeople hair to crash the pref menu
/:cl:

### CODE REVIEW

**Comment by magatsuchi** [comment]
everyone laugh at their commit history hahaaa

**Review by MrMelbert — CHANGES_REQUESTED** [review]
ci is failing because, even though you told it to generate icons, you didn't set it up to generate any icons, which breaks all of the other icons in the prefs menu

you need to give it icons in init_possible_values as an assoc list of [style] to [generated icon]

**Comment by ArcaneDefence** [comment]
Can you write a better changelog please? This tells the players nothing, and only makes things more confusing

**Comment by magatsuchi** [comment]
> Can you write a better changelog please? This tells the players nothing, and only makes things more confusing

is this not exactly what i did, though?



> ci is failing because, even though you told it to generate icons, you didn't set it up to generate any icons, which breaks all of the other icons in the prefs menu
> 
> you need to give it icons in init_possible_values as an assoc list of [style] to [generated icon]

on it right now

**Review by MrMelbert — APPROVED** [review]

**Pull request merged**
