### PR TITLE
CRUNCHY CRUNCH the soda can.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

You can now crush soda cans on other people.
Also fixes the return value of soda cans attack proc.

## Why It's Good For The Game

Why not?

## Changelog
:cl:
add: You can now crush soda cans on other people.
/:cl:

### CODE REVIEW

**Comment by Fhaxaris** [comment]
SCP-173 HAS BREACHED CONTAINMENT.

**Comment by Anonymous583** [comment]
jay owen buff

**Comment by carlarctg** [comment]
needs brute damage

**Comment by 81Denton** [comment]
@Anonymous583 RIP stggggs

**Comment by actioninja** [comment]
I'm gonna need to make a sound for this.

**Pull request merged**
