### PR TITLE
fueltanks now have larger explosions if welded/shot, beer kegs can now be shot to detonate them instead of only being able to be detonated by the blob.

### PR DESCRIPTION
**Pull request by Buggy123**
OOC: Zilenan91: I find it kinda strange
OOC: Zilenan91: how fueltank explosions are now less than IEDs

This might be too much but he has a point...

### CODE REVIEW

**Comment by Lumipharon** [comment]
why does a tank of beer explode with more force then a sydie bomb?

**Comment by Buggy123** [comment]
Why did it explode with the force of a syndie bomb when hit by a blob?

**Comment by Zilenan91** [comment]
Does this really make beer keg explosions equivalent to a syndibomb?

**Comment by Zilenan91** [comment]
good lord the beer keg makes a big kaboom. I could get behind this thouhg.

**Comment by PKPenguin321** [comment]
okay listen here is the science:
beer is flammable
there is a small space for the beer
beer expands when burned
there is a **LOT** of beer
the keg itself is made from microscopic razorblades that disintegrate anything they touch, but only when they're separated by something, such as expanding beer

**Comment by Zilenan91** [comment]
As the dude who plays basically nothing but Bartender on Sybil I will keep the secrets of beerkeg-fu with me and use them only in the most dire of times.

**Comment by JJRcop** [comment]
@Zilenan91 but prs are broadcasted to the entire server to players that have it enabled

**Comment by Cheridan** [comment]
beer is not flammable.

**Comment by Zilenan91** [comment]
Well yeah but the knowledge of beerkeg-fu is only available to those who know to look inside the pr itself, it isn't too evident in the title of the OP.

I mean, we could make it canon that SS13 beer is literally just diluted welding fuel

**Comment by PKPenguin321** [comment]
>beer is not flammable.

yes it is. you see, the reason for this is science

**Comment by Buggy123** [comment]
I could remove the syndiebomb-beerkeg but keep in mind it already exploded like that before this PR, but only when the blob hit it. So this is more a matter of consistency than anything.

**Comment by Lumipharon** [comment]
I've literally never seen a beerkeg explode in all my years playing. Just remove that yo, it makes no sense what so ever, and is just going to result in it getting stolen by antags every single round for free boom boom.

**Comment by PKPenguin321** [comment]
i for one welcome our stolen beerkeg overlords

**Comment by MrStonedOne** [comment]
I'm making a similar change to fuel tanks in the tesla_pr because i'm merging the act's into one proc, boom(), as i had to do to add tesla_act to fuel tanks, the beer keg part seems odd and shouldn't explode

**Comment by Zilenan91** [comment]
Oh yeah are fuel tanks enough to gib now with these changes?

**Comment by Buggy123** [comment]
Uh, I think so yes.

**Comment by Zilenan91** [comment]
Wew okay that could be problematic but it's probably fine.

**Comment by Buggy123** [comment]
Again, i've done nothing but improved consistency. Why would a welding tank explode harder when a blob hits it instead of being LIT ON FIRE or SHOT BY A LASER?

**Comment by MrStonedOne** [comment]
@Buggy123 See the work i did in my tesla pr, it seems like we did the same thing:

https://github.com/tgstation/-tg-station/pull/14851/files#diff-85dfa6847a4fdcbf04be9765c75773a8L91

**Comment by Buggy123** [comment]
Yup, except for the beerkeg thing. Do you want me to close this then?

**Comment by Zilenan91** [comment]
I'd love for the beerkeg thing to stay around but that's probably insanely unbalanced.

**Comment by PKPenguin321** [comment]
not even remotely

**Comment by Zilenan91** [comment]
I don't think anybody ever said teleprods would be unbalanced

except for on the shuttle but they're too hard to make to ever be used in any capacity.

**Comment by PKPenguin321** [comment]
Kinda like how there's a single beer keg on most stations and getting a laser specifically to blow it up is so much effort that it's essentially pointless

**Comment by Zilenan91** [comment]
can't the bartender blow it up with his shotgun though

**Comment by Buggy123** [comment]
I think bullets work, yes.

**Comment by tkdrg** [comment]
Mso's PR has been merged, so I'm closing this as redundant. PM me if you want this reopened to tweak the delicate beer keg meta.

**Pull request closed without merging**
