### PR TITLE
Mine turf fixes

### LINKED ISSUE #13421: Smooth lava isn't smoothing
http://puu.sh/lHKaa/5710ba10ad.png
See screenshot

### LINKED ISSUE #13423: Asteroid walls leave fully-aired asteroid tiles behind
I think the path you were looking for was /plating/asteroid/airless , rather than /plating/asteroid

@KorPhaeron

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes aired asteroid tiles. Fixes #13423 

Fixes smooth lava not smoothing. Fixes #13421

### CODE REVIEW

**Comment by WJohn** [comment]
Also while you're at it, could you fix it where basalt floors are guaranteed to have one of the special floor types? It's kind of ugly to have a "special tile" literally everywhere.

**Comment by tkdrg** [comment]
@KorPhaeron this fixes it partially but all the pre-spawned turfs in mining are still the kind with air

**Comment by RemieRichards** [comment]
Merged due to the ugly state of mining right now, it hurts us all.

**Comment by KorPhaeron** [comment]
@tkdrg

I may have misunderstood the issue then.

Is it only in the caves?

**Pull request merged**
