### PR TITLE
Disables Emergency Pods for a testmerge

### PR DESCRIPTION
**Pull request by Iamgoofball**
Someone suggested this on the forums. Why not? It'll be a fun test.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Disables them how? They just won't move ever?

**Comment by Iamgoofball** [comment]
Mhm

**Comment by PKPenguin321** [comment]
Dislike and unsubscribe

**Comment by Bawhoppen** [comment]
it's a fun test

**Comment by Bawhoppen** [comment]
though I doubt it would be good to stick

**Comment by XDTM** [comment]
I'd keep red alert emergency launch tho

**Comment by FantasticFwoosh** [comment]
If they could still fire you to lavaland on red alert without a shuttle call that'd be great.

**Comment by octareenroon91** [comment]
>If they could still fire you to lavaland on red alert without a shuttle call that'd be great.

Holy shit, doing absolutely nothing is pretty severe.

**Comment by Supermichael777** [comment]
making us more like goon because goofball still hasnt been unpermaed

**Comment by BeeSting12** [comment]
Interesting for a testmerge but I don't want to see it as a permanent thing

**Comment by CPTANT** [comment]
Pods should still launch to lavaland on red/delta

Otherwise this is good.

**Comment by Tacolizard** [comment]
On the forums, I didn't really mean they SHOULD be removed, I was more just trying to start a conversation. Anyways, it's worth a testmerge

**Comment by duncathan** [comment]
if this is just for a testmerge then there's no harm in closing the PR; should people actually want to go through with this do it properly later

**Comment by kevinz000** [comment]
"On the forums, I didn't really mean they SHOULD be removed, I was more just trying to start a conversation. Anyways, it's worth a testmerge"
"Escape pods shouldn't exist" is the title
man tacolizard is a good boi.

**Comment by Tacolizard** [comment]
don't listen to my words i am delusional

**Pull request closed without merging**
