### PR TITLE
Removes sound from the laugh emote.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
Having everyone's laughs sound the same is bad. This game gives you plenty of ways of making a unique character, and having everyone's laughs being identical is just bad for roleplay.

### CODE REVIEW

**Comment by Davidj361** [comment]
But it is not the same, it has varying pitch on the same sound.

**Comment by cacogen** [comment]
can someone bankroll voices for emotes

**Comment by Davidj361** [comment]
>can someone bankroll voices for emotes
What does that mean?

**Comment by cacogen** [comment]
So in the character creation window you can select from multiple voices for your character, which will make their voice consistent across emotes

It's a dumb idea, don't worry about it

**Comment by Niknakflak** [comment]
techno so upset that others laugh he has to take away laughing from everyone

**Comment by Davidj361** [comment]
That could possibly be done with pitch. But having dedicated sounds for each voice is hard because of copyright and having the same voice actor. Also there's increase file size of the repo.

**Comment by RogueSteampunker** [comment]
This is a joke, right?

**Comment by cacogen** [comment]
no because some people unironically demand that rockstar games level of perfectionism from their 2d space sim which isn't inherently bad

**Comment by 81Denton** [comment]
Literal fun removal

**Comment by sawrge** [comment]
Good change :+1:

**Comment by cacogen** [comment]
>That could possibly be done with pitch. 

oh yeah in the sims you can alter the pitch of your sim's voice as well as the type no one cares enough to add this though

**Comment by TechnoAlchemisto** [comment]
The game being text based with no voice chat is why it's good for roleplay. I'm not asking for 3000 different laughing sounds, I am asking for 0 laughing sounds for text-based RP.

**Pull request closed without merging**
