### PR TITLE
Fixes dizzines not shaking your screen

### PR DESCRIPTION
**Pull request by Alomga**

### CODE REVIEW

**Comment by 81Denton** [comment]
15 duration might be a little rough, it's as long as the screen shake when the gravity generator shuts down/powers up

**Comment by Alomga** [comment]
So what do you suggest?

**Comment by XDTM** [comment]
should fix the dizziness thing, not sweep it under the rug while using something else

**Comment by Alomga** [comment]
So is that a nono?

**Comment by Alomga** [comment]
@XDTM Could you tell me where is dizzinnes in code? Becasue I'm too stupid to find it.

**Comment by XDTM** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/carbon/life.dm#L331

**Comment by Alomga** [comment]
@XDTM Woah, that is... complicated... Maybe tad too complicated for little me who barely even understands the code... I hope you don't mind me constantly asking you stuff, if you do say so and I'll either try to learn it myself or bug someone else.

**Comment by XDTM** [comment]
Of course not, i'm happy to help. Don't feel obligated to fix the bug yourself, though, i noticed it's pretty complex, and it can wait a bit longer until someone who knows that stuff fixes it.

**Comment by Alomga** [comment]
Okay, I'll leave it for now, get to know the code better, try my strengths at other things, maybe return to it later.

**Pull request closed without merging**
