### PR TITLE
Removes patting as it is snowflake code and beerobot told me too

### PR DESCRIPTION
**Pull request by optimumtact**
:cl: oranges
del: Removed patting
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
This is snowflake code and can be done with existing emote systems, the existing examples should ideally go too but at this point they meet the scratch test for legacy code.

### CODE REVIEW

**Comment by kevinz000** [comment]
Better remove slapping too

**Comment by ChangelingRain** [comment]
If you can do it with emotes, then do it with emotes instead of removing it.

**Comment by optimumtact** [comment]
@ChangelingRain I'm referring to the *me emote

**Comment by Cheridan** [comment]
what we have here is a clear case of maintainer bias

everyone give oranges your pats so he can see how nice they really are

*pats*

**Comment by Iamgoofball** [comment]
@Cheridan so when are all clockcult buff PRs being reverted

**Comment by PKPenguin321** [comment]
What about slapping

**Comment by PKPenguin321** [comment]
Wait a minute

**Comment by Iatots** [comment]
Slapping is ancient goonshit. It (used to?) check your "me" emote for a "slap X" pattern and you automatically slapped X (or yourself if typing no valid name) playing the telltale sound.
Patting has no sound or special feature bound to it, so it can be entirely substituted with "me" emotes.

**Pull request merged**
