### PR TITLE
this is why we don't let cheridan suggest gun names

### PR DESCRIPTION
**Pull request by Iamgoofball**
thanks cheridan

### CODE REVIEW

**Comment by Cheridan** [comment]
DENIED

**Comment by Iamgoofball** [comment]
i'll deny your mom tonight then

**Comment by optimumtact** [comment]
Wow it's fucking nothing

**Comment by tuypo1** [comment]
no goofball is right sketchkin was a great name although anything is better then that period of time when it was called literally syndicate pistol

**Pull request closed without merging**
