### PR TITLE
Experimental tweak to demo recorder

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Cuts out a section of `encode_appearance` that was used to reduce the output size by doing updates differentially. Did a lot of logic and I am not sure how much it actually helped the end demo size. It is being compressed in the end anyways.

The intent of this is making the demo recorder overtime less at the expense of larger demo size. Ideally the size difference won't actually be very large, but it will need to be tested to see the difference.

This is mostly experimental and needs a testmerge.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
tmed on manuel

**Comment by optimumtact** [comment]
What was the outcome of the test merge?

**Comment by actioninja** [comment]
Did not solve the lag issues, leave this open for now because I have some other things to test.

**Comment by actioninja** [comment]
This is broken because GitHub so I need to reopen it.

**Pull request closed without merging**
