### PR TITLE
Fixes rites being able to be done by non-chaplains

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

This has stuck around for far too long. Adios, bug!

## Why It's Good For The Game

They weren't supposed to be done by anyone less than priests but I think I was the one who fucked up and used the wrong operators

## Changelog

:cl:
fix: fixes non-chaplains being able to invoke rites
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Can you still do this if you use the syndicate bibble? I think that might set you to HOLY_ROLE_PRIEST.

**Comment by datorangebottle** [comment]
does this mean that the transhumanist chaplain can no longer be turned into an android?

**Comment by TheBonded** [comment]
> does this mean that the transhumanist chaplain can no longer be turned into an android?

Exactly my thinking, a lot of rites require help from followers and it seems weird to restrict it to just the chaplain. What's next, runes can only be used by cult leaders?

**Comment by datorangebottle** [comment]
> What's next, runes can only be used by cult leaders?

I actually feel like this could be an interesting cult variant, where only the prophet of lub'shaggalot and a few individuals they designate can make the cool toys / invoke the cool spells, and have to coordinate and distribute power to lesser cultists/where it's needed. (but this is also wildly off-topic)

**Comment by TheBonded** [comment]
> > What's next, runes can only be used by cult leaders?
> 
> I actually feel like this could be an interesting cult variant, where only the prophet of lub'shaggalot and a few individuals they designate can make the cool toys / invoke the cool spells, and have to coordinate and distribute power to lesser cultists/where it's needed. (but this is also wildly off-topic)

It was intended to be rhetorical but you're right, that could actually create interesting dynamics. (And yeah this is off topic so we should probably drop it)

**Comment by Coastfront** [comment]
This also means that if this goes through iirc the maint sect and the robo sect chaplains wont actually be able to do their rites on themselves, since it goes off of whats ontop of the altar (atleast if memory serves me right, i might be wrong on the maint sect.)
And that'd be kinda weird if a chaplain could neither benefit from their own sect, or even make use of some of their rites for whatever wacky religious reason they come up with.

**Comment by datorangebottle** [comment]
> This also means that if this goes through iirc the maint sect and the robo sect chaplains wont actually be able to do their rites on themselves, since it goes off of whats ontop of the altar (atleast if memory serves me right, i might be wrong on the maint sect.) 

Last I played it(a while ago), maint sect chaplains didn't have to lay on the altar to do things to themselves.

**Comment by Donpedrito** [comment]
Does this block non-chaplain members of an honorbound sect from recruiting new members?

**Comment by davethwave** [comment]
Welp, no reason to ever use the robo sect again.

**Pull request merged**
