### PR TITLE
Fixes tempgun block ignoring.

### PR DESCRIPTION
**Pull request by silicons**
Closes #32654 because mrty is too unrobust to play antags.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
I ded

**Comment by ike709** [comment]
#11017

**Comment by Jordie0608** [comment]
Smooth recovery there tableboy

**Comment by PKPenguin321** [comment]
>he died to a tempgun

**Comment by ike709** [comment]
>he died to a tempgun

**Comment by Cyberboss** [comment]
>>he died to a t e m p g u n

**Pull request closed without merging**
