### PR TITLE
Mining MODsuit sprite changes + balance

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Slightly slimmed down the helmet, changed belt into plates, recolored brown parts to blue and added a few more glowy bits to the mining MODsuit.

image

Here's what it looks like currently

image

Mining MODsuit now hides belts, has THICKMATERIAL while active and got large capacity storage. Eating apparatus no longer has an on-person sprite. Adjusted drill module active sprite to actually fit on your hand instead of being slightly to the side.

## Why It's Good For The Game

Currently the MOD looks a bit goofy, I tried making it a bit more streamlined without removing the bulk and look of a reinforced explorer exosuit. Belts are hidden for the sake of visuals, as almost all miners wear riggings which do not fit with the MOD spritework at all.  While inactive it has THICKMATERIAL but for some reason loses it when activated, which doesn't make much sense. Its a thick, armored spacesuit.

Eating apparatus isn't a module that people around you need to be acutely aware of, nor did it look particularly good. I tried respriting it but there's not much to be done with 12 pixels worth of space.

Large storage is a rather impactful change - currently only loader and advanced (CE's personal) MODs have it, and more can be printed after researching advanced engineering MODsuit designs (from my experience, usually done by ~40 minute mark). Storage space is a very important aspect, and mining MODs already have high competition with ash drake and H.E.C.K. armors. Having less storage makes them a weird sidegrade, arguably even a downgrade, to roundstart explorer gear that has been upgraded with plates; its only real advantage is being able to pass through lava and freeing a pocket previously occupied by your ore satchel due to arcmining nerfing its main purpose (ore mining). While this still is technically worse than roundstart backpacks, this should allow them compete with with other equipment in terms of usability.

## Changelog
:cl:
balance: Mining MODsuits are now considered thick clothing and gained expanded storage.
image: Mining MODsuits got a slight glowup and hide belts now
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
The point of the clamp is to pick up tendril chests. It fits up to 3 and is quite useful, I don't see why you're removing it honestly. THICKMATERIAL prevents suturing, though I had absolutely no clue it lost it when active.

**Comment by SmArtKar** [comment]
> The point of the clamp is to pick up tendril chests. It fits up to 3 and is quite useful, I don't see why you're removing it honestly. THICKMATERIAL prevents suturing, though I had absolutely no clue it lost it when active.

Former point is valid, yeah, gonna revert the clamp removal then. Latter is... arguable to be honest, from both logical and gameplay perspectives.

**Comment by Vect0r2** [comment]
Remember to update the PR description

**Review by Wallemations — APPROVED** [review]
Good job adding more bulk

**Comment by Jacquerel** [comment]
You know it occurs to me moments after clicking that... worth checking if `THICKMATERIAL` blocks the miners survival pens :clueless:
If not then should be fine

**Pull request merged**
