### PR TITLE
Nerfs Saber SMG to 21 per magazine

### LINKED ISSUE #13812: Saber SMG has an enormous ammo capacity.
The prototype saber SMG that R&D can print out has 42 rounds per mag, on top of a 3-round burst fire mode. This means you never ever have to stop shooting. It got buffed to these ludicrous levels because for a while we had the similarly overpowered steelrifles in. Now that those are gone, these things stayed buffed and are still insanely powerful.

Should be dropped to at least 30 rounds per magazine, the burst fire and 9mm refillable bullets are already a gigantic upgrade over steelrifles, on top of being manufactured here on the station rather than ordered by cargo.

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
fix: Saber magazines have been dropped to 21 per magazine. When asked, Nanotrasens official ballistic department replied "There is indeed such a thing as too much bullet."
/:cl:

STEEEEL

Resolves #13812

### CODE REVIEW

**Comment by GunHog** [comment]
This is a nerf, not a fix. :-1:

**Comment by Bawhoppen** [comment]
0/10 :-1: nerf it to 35 not 25

**Comment by Zilenan91** [comment]
>35 rounds
>20 brute per
>3 round burst

What the fuck guys

**Comment by WJohn** [comment]
35 is barely lower than 42, the issue would not be closed at all.

I'd be okay with 25 OR 30.

Also it should be reworded to "closes" or "resolves" as I think those auto-close those.

**Comment by Bawhoppen** [comment]
its a lategame R&D item with alternatives that will be far superior after this nerf

**Comment by MMMiracles** [comment]
It has the advantage of having multiple ammo types for a variety of situations, its also extremely easy to obtain the regular ammo for it.

**Comment by Bawhoppen** [comment]
I do agree it needs a slight nerf, but 25 is too low, make it 32 to be an autistic number again

**Comment by LatD** [comment]
At least make the number divisible by 3 since it's shooting bursts of 3

**Comment by MMMiracles** [comment]
I just did.

**Comment by LatD** [comment]
Yeah, that's a good number

**Comment by Bawhoppen** [comment]
>not 33

**Comment by MMMiracles** [comment]
Who needs more than 9 full bursts per clip I mean jesus christ how bad is your AIM.

**Comment by Bawhoppen** [comment]
even if you need less to kill someone, you don't need to reload as often

**Comment by WJohn** [comment]
Yeah that's the problem in the issue baw, you don't ever have to reload because you have so many bullets in the magazine. 27 or 30 is totally fine.

**Comment by Bawhoppen** [comment]
bruteforce nerfs are dumb
Atleast make it 30 to fit with like every other magazine every and be a nice number

**Comment by MMMiracles** [comment]
I thought you wanted an autistic number.

**Comment by Shapsy** [comment]
I'm pretty sure SABR's only had 20 rounds in a mag up until steelpoint doubled their magazine size to justify their existence after he shoved steelrifles into the game (so 20 + 1 in the chamber would give you 21 shots/7 bursts), not to mention that SMG mags are tiny items and you can literally carry 8 extra magazines for the same backpack space as two laser guns

**Comment by GunHog** [comment]
Set it to 30 at least.

**Comment by MMMiracles** [comment]
Yep, if you go back far enough you'll see the initial count was 20 before Steelpoint buffed the capacity.

This is literally just bringing it back down to more reasonable standards and is STILL a buff compared what they used to be.

**Comment by CPTANT** [comment]
Wasn't it 30 original?

I have no idea why that was ever changed in the first place.

**Comment by MMMiracles** [comment]
Read above.

**Comment by Durkel** [comment]
Make it 30 bruh,

**Comment by MMMiracles** [comment]
Keeping it 27 unless a collaborator says otherwise fam.

**Comment by WJohn** [comment]
I'd say 30, but I already did.

**Comment by duncathan** [comment]
27 is a pretty number
30 is ugly
3^3 is much nicer than 2*3*5
Make it 27 to satisfy my math fetish

**Comment by Bawhoppen** [comment]
I did but you'll never do that so go with a sane number 
30 is also the ammo box size

**Comment by MMMiracles** [comment]
the deciding factor here is if i get bonus points for satisfying dunc's math fetish by keeping it at 27.

**Comment by RemieRichards** [comment]
Change it to 30.
Multiple of 5, 10, it's even, it's a multiple of 3 which fits with the bursts.
down with 27 long live 30.

**Comment by GunHog** [comment]
>Keeping it 27 unless a collaborator says otherwise fam.

Two have requested it so far!

**Comment by MMMiracles** [comment]
sorry dunc democracy wins.

**Comment by Durkel** [comment]
The system works.

**Comment by Lumipharon** [comment]
wow wow wow kids.
The SABR used to be 20 rounds per mag. And it was fucking good.
It only got buffed to 42 for the sole and exclusive reason to 'make them better then steelrifles', back when steelrifles were literally just sabr's only free and objectively better in every single way.

As someone who uses these probably more then anyone else (because having a silenced sabr gives me a tacticool hardon), I can safely say that this gun was still very, very effective with 20 round mags.
With the way storage has changed, even without a boh you can still carry 30+ mags of ammo.
With a garbage bag of holding, you can carry like 200 mags.

This is a lot of dakka.

**Comment by KorPhaeron** [comment]
>gun gets its capacity more than doubled for no fucking reason
>BRUTE NERFS ARE BAD FIND ANOTHER WAY TO DEAL WITH THE SMG HAVING MORE AMMO THAN ANY GUN THAN THE SAW

???

Why are so many people against this?

**Comment by KorPhaeron** [comment]
I mean I agree in general that brute nerfs are lazy and boring but this is in response to a lazy and boring brute buff to a boring gun that has no special properties beyond having way too many bullets

**Comment by MMMiracles** [comment]
I wanted 27 but *democracy*

**Comment by Steelpoint** [comment]
Just revert the mag count to the exact same number of rounds it was prior to my auto rifle PR.

That being it a 20 round magazine.

**Comment by Dorsisdwarf** [comment]
20 round mag plz

**Comment by Steelpoint** [comment]
One in the chamber, that's normal for any ballistic gun.

**Comment by MMMiracles** [comment]
I had 3 collabs say 30 even though I pointed out it was 20 to begin with. 

Convince them I guess.

**Comment by Bawhoppen** [comment]
30 is just better
Ammo box amount, same as every mag ever, nice /sane/ number, not bruteforce nerfing

**Comment by Steelpoint** [comment]
Its just my opinion but I think restoring it to its original amount is better than fucking around with a increased magazine number.

The only reason the SABR was buffed was due to the presence of round start Auto Rifles, but with that now confined to Cargo the SABR has no reason to remain buffed anywhere past 20 rounds.

**Comment by Bawhoppen** [comment]
Don't over-nerf it right away without thinking, 42 itself wasn't that bad so dropping it to less than half it's cap would be overdoing it
If it's a problem later on it can be fixed

**Comment by MMMiracles** [comment]
It isn't a bruteforce nerf if was made 42 to begin with because a bruteforce buff, FYI.

**Comment by Bawhoppen** [comment]
ye but it has worked out at 42 and hasn't even really been OP at that

**Comment by MMMiracles** [comment]
Read lumi's earlier post on why it is.

**Comment by Bawhoppen** [comment]
it isn't though???

**Comment by MMMiracles** [comment]
Being able to carry a militia's worth of ammo without having to reload for the next several bursts every time IS OP. 

It's literally 8 less than the SAW.

**Comment by Bawhoppen** [comment]
it isn't, but even then 30 is a reasonable nerf to it

**Comment by MMMiracles** [comment]
You've must of never seen a murderbone or done one with it, then.

**Comment by Bawhoppen** [comment]
you can murderbone with plenty of other things just as effectively

**Comment by MMMiracles** [comment]
One would assume it'd take more effort than 'click down the hallway and reload every 20th time.'

**Comment by GunHog** [comment]
Just leave it at 30 and call it a night, geez.

**Comment by MMMiracles** [comment]
Its literally only at 30 because I've been told to, doesn't mean I want it there.

Main reasoning that even the man who buffed it wants it returned to initial values.

**Comment by tkdrg** [comment]
I like 20 mags+1 in the chamber (also a multiple of 3). Still think these are too good even after this nerf.

**Comment by LanCartwright** [comment]
Hold the phone. I'll look at it and think about it tomorrow and I'll tell you what it should be.

**Comment by LanCartwright** [comment]
30 is too much, 20 is just short of too few rounds.

24 round magazine is what I recommend. Anything more or less becomes a problem.

**Comment by Steelpoint** [comment]
Technically any ballistic gun holds the mag's size plus one extra round, from the round that slots into the chamber.

So a 20 round mag would equal 21 bullets in total, assuming there's still a bullet in the chamber.

**Comment by Bawhoppen** [comment]
@LanCartwright  thanks master of balance
we were waiting in anticipation

**Comment by LanCartwright** [comment]
here's the problem with ballistics and the 42 magazine

49 per bag, 7 bags, bag of holding.
2 in pockets, 2 mag in hand, 1 on exosuit, 1 loaded smg.
296520

That's the biggest ballbuster for ballistics.

**Comment by MMMiracles** [comment]
@Bawhoppen 

Depends on how bad the user's aim is.

**Comment by Lumipharon** [comment]
Lan, you forgot 200 mags in a garbage bag of holding.

**Comment by MMMiracles** [comment]
sometimes democracy doesn't know whats good for it and we just need to GO AGAINST THE SYSTEM FOR THE GREATER GOOD.

**Pull request merged**
