### PR TITLE
Adds an indestructible disco/dance machine for admemes and disco inferno shuttle

### PR DESCRIPTION
**Pull request by DaxDupont**
🆑 Dax Dupont
add: Thanks to the extensive disco and plasma research gathered by the Disco Inferno shuttles, an indestructible mark V disco machine is now available. The latest edition of the Disco Inferno shuttle now carries it.
/🆑

[why]: Dance machine on the shuttle now has intended properties, can no longer break the pride and joy of the shuttle. Also kor asked me to make an admin/indestructible version for the shuttle.

### CODE REVIEW

**Comment by coiax** [comment]
I think it would be better to make a subtype and use that. Var edits are grody.

**Comment by DaxDupont** [comment]
Making a subtype for something that will only ever be used once on a single shuttle that only gets bought maybe 1 in 100 rounds seems silly.

**Comment by coiax** [comment]
You should always use subtypes, makes things more reusable. It's just good practice.

**Comment by DaxDupont** [comment]
But it's never gonna be reused

**Comment by coiax** [comment]
You don't know that.

**Comment by DaxDupont** [comment]
I'll make it a subtype if the maintainers ask, even though it's stupid. 
We'll see what they say.

**Comment by BeeSting12** [comment]
@DaxDupont the maintainers probably will ask. just do it, takes ~five minutes or less

**Comment by DaxDupont** [comment]
It's dumb to subtype something that will never be reused. Do you really want the codebase to filled for a subtype for every minor thing one use thing?
Besides, it was already varedited.

**Comment by DaxDupont** [comment]
Actually fuck it, Kor said maybe to make an admin one that's indestructable. Here we go bois

**Comment by ExcessiveUseOfCobblestone** [comment]
Not preemptively coding subtype variants isn't a bad thing :/

**Comment by DaxDupont** [comment]
@ExcessiveUseOfCobblestone well now i've enabled the admins so the discussion is over i guess. It will be indestructible in the shuttle now but that's fine with me.

**Comment by optimumtact** [comment]
Personally I disagree that we should make subtypes for everything

one they cause compiler overhead and two the type heirarchy should not be used as a database

most maintainers don't agree with me though so I've given up arguing about it other than leaving a note

**Comment by Bawhoppen** [comment]
We don't need to encourage admins to spawn stuff

**Comment by DaxDupont** [comment]
Well people were crying about having a subtype so it was either:
- Subtype that will only be ever used once
- Something that can be reasonably reused by admins

**Pull request merged**
