### PR TITLE
changes the xenomorph lavaland ruin

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

changes the xenomorph lavaland ruin to something that takes up way less space and turns into into an abandoned mining thing infested with benos

## Why It's Good For The Game

the old ruin was boring, had nothing and was way too big, i think this is a bit better and more interesting

## Changelog
:cl:Fikou
add: Attention to all sisters, we moved the hive to an abandoned mining facility.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
it's disabled though fikou

why change a disabled ruin!1!

**Comment by Fikou** [comment]
> it's disabled though fikou
> 
> why change a disabled ruin!1!
> 
> Edit: also images please

we can reenable it 😳 
looks something like this but i did some small changes since
image

**Comment by TheMidnightRose** [comment]
> it's disabled though fikou
> 
> why change a disabled ruin!1!
> 
> Edit: also images please

The lavaland xenomorph ruin? No its not, I see it pretty often, at least six times in the last two days.

**Comment by Shadowflame909** [comment]
Woops never mind. There was a time when the ruin was gonna be disabled or have its egg removed. See #43616

**Comment by cacogen** [comment]
I see what you mean by it being boring and having nothing, but the layout is interesting. Why not add something to find to make exploring it rewarding?

**Comment by dr-bee** [comment]
good change, The current ruin is absolutely huge for what is in it. any chance you can reduce the ruin spawn cost now that it is smaller?

**Comment by Iatots** [comment]
It's very boxy, and those windows might lead to a lot of FUN.
If it has to be a mining depo, could it not be the old depo that was on the asteroid?

**Comment by knacker48** [comment]
Does it have less stuff now that its smaller? I don't see the old space suit that was there before

**Comment by Fikou** [comment]
> It's very boxy, and those windows might lead to a lot of FUN.
> If it has to be a mining depo, could it not be the old depo that was on the asteroid?

i dont have the asteroid map sorry

**Comment by TheMidnightRose** [comment]
> Woops never mind. There was a time when the ruin was gonna be disabled or have its egg removed. See #43616

The egg was removed I think? Its all simple mob xenos and there shouldnt be any eggs in there now. I think they did that with the update to prevent miners from just breaking into the main nest area instantly.

**Comment by Iatots** [comment]
it's a bit big, I wouldn't mind if you shortened it vertically. It's around twice as tall as yours, and 1.5x times as wide.
asteroid mining base

**Comment by cacogen** [comment]
@iatots change-view-range

**Comment by Iatots** [comment]
It's /vg ya dip. But apparently, you can zoom with the mouse wheel, neat.

**Comment by cacogen** [comment]
I just wanted to blow your mind

**Review by kriskog — COMMENTED** [review]
Seems fine, the old one was a bit meh.
You got air turfs inside though, which means the pka wont work very well. Is this a conscious choice?

**Comment by CAPTTLasky** [comment]
Why have sec lockers in it except to give miners free sec gear without having to take it from a locker on the station.

Seems kind of silly. You should replace them with mining lockers if it's really supposed to be a mining station, or limit the sec gear to jumpsuits and armor.

And I see that baton sitting there too. Gives a free baton without any risk (Cargo order, beepsky, officer, or gear room all risk detection by sec). You should make it a detective baton or some other weapon.

**Comment by CAPTTLasky** [comment]
Why aren't the dead mobs on Xeno beds?

**Comment by kriskog** [comment]
Huh I didnt notice the sec lockers. Its the cargo variety lockers, so its armor and bowman/hud. Not a fan.
The baton and the stechkin were present in the old ruin, I dont really mind those. Do make sure the baton is cell-less though, if it isnt already.

**Comment by Fikou** [comment]
> Huh I didnt notice the sec lockers. Its the cargo variety lockers, so its armor and bowman/hud. Not a fan.
> The baton and the stechkin were present in the old ruin, I dont really mind those. Do make sure the baton is cell-less though, if it isnt already.

they are cell=less

**Comment by Fikou** [comment]
> Seems fine, the old one was a bit meh.
> You got air turfs inside though, which means the pka wont work very well. Is this a conscious choice?

there are tiny fans inside, makes sense for it to have air

**Comment by Fikou** [comment]
> Why aren't the dead mobs on Xeno beds?

because i dont think i can buckle mobs on maps

**Comment by kriskog** [comment]
> 
> 
> > Seems fine, the old one was a bit meh.
> > You got air turfs inside though, which means the pka wont work very well. Is this a conscious choice?
> 
> there are tiny fans inside, makes sense for it to have air

You put those there. Also you didnt really answer my question.

**Comment by Fikou** [comment]
> You put those there. Also you didnt really answer my question. Have you considered that the PKA will be near useless for fighting the xenos inside?

yeah ok i can change it

**Comment by Taylorkills2** [comment]
> > > Seems fine, the old one was a bit meh.
> > > You got air turfs inside though, which means the pka wont work very well. Is this a conscious choice?
> > 
> > 
> > there are tiny fans inside, makes sense for it to have air
> 
> You put those there. Also you didnt really answer my question. Have you considered that the PKA will be near useless for fighting the xenos inside?

To be fair, since miners can easily ruin the pressure gradient by plasmacutting the walls or KPAing the windows from outside. Just will take a bit longer with the small fans.

**Comment by kriskog** [comment]
> 
> 
> > You put those there. Also you didnt really answer my question. Have you considered that the PKA will be near useless for fighting the xenos inside?
> 
> yeah ok i can change it

I don't mind if you put air in there or not. I am asking if that is something you're willing to stand by as a conscious design choice or if it was an oversight.

**Review by kriskog — CHANGES_REQUESTED** [review]
Get rid of the sec lockers

**Comment by Fikou** [comment]
this ruin is too low quality, i decided that ill first try to make a goodly designed mining station and then break it with xeno stuff

**Pull request closed without merging**
