### PR TITLE
MetaStation Atmospherics Air Alarm Insanity

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

image

Four. Four Air Alarms for largely the same area. That's WAY too many. No need for that many. Let's get rid of that central one since it is a large area and it does need a few air alarms, but it just feels ridiculously excessive right now. It's also in what I consider to be an awkward position.

## Why It's Good For The Game

image

Looks nicer.

## Changelog

:cl:
del: There is no longer an air alarm in the central island of atmospherics on MetaStation.
/:cl:

### CODE REVIEW

**Comment by TheBoondock** [comment]
But what if I wanna have a backup one when the inevitable fire breaks out and destroy the other 3. Cringe pr

**Comment by KommandantJackal** [comment]
I feel personally attacked by this pr. That's the air alarm I used for my BZ setup. How could you San

**Comment by san7890** [comment]
> But what if I wanna have a backup one when the inevitable fire breaks out and destroy the other 3. Cringe pr

Make new air alarm.

> I feel personally attacked by this pr. That's the air alarm I used for my BZ setup. How could you San

What?

**Comment by KommandantJackal** [comment]
San, we are messing with you

**Pull request merged**
