### PR TITLE
Gives fountain ruins unique ids so the lavaland one will spawn

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request
Come ON man

## Changelog
:cl:
fix: The fountain ruin will now properly spawn on lavaland
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
We have shared ruins for lavaland and icemoon. Currently only Free Golems use this, would it be better to make them use that instead?

**Comment by LemonInTheDark** [comment]
are you sure about that? there's two definitions for free golems here, each with the same id

**Comment by JohnFulpWillard** [comment]
Oh I was entirely wrong, they just have the same ID too
image

i was referring to this PR https://github.com/tgstation/tgstation/pull/71017

**Comment by LemonInTheDark** [comment]
edit: I'm unsure why ids exist if they're not gonna be consistent, but part of the issue here is the spawn ruins verb using names, and names conflicting.

**Comment by JohnFulpWillard** [comment]
Question; How is this fixing the problem of the ruin not spawning? Are there multiple ruins on lavaland named "fountain"?
IceBox and Lavaland should already have separate blacklists.

**Comment by dragomagol** [comment]
Both of these are the exact same ruin (except that the lavaland version has a cost of 5?) so I'm not sure why there's two. Do we not have a shared or general map_template datum?

**Pull request merged**
