### PR TITLE
Update AI Airlock UI to use TGUI

### PR DESCRIPTION
**Pull request by psykzz**
:cl: psykzz
refactor: AI Airlock UI to use TGUI
tweak: Allow AI to swap between electrified door states without having to un-electrify first.
/:cl:

AI interface was old and outdated, this updated it and cleaned up a few things related to it.

### CODE REVIEW

**Comment by GunHog** [comment]
Yay! Finally!

**Comment by psykzz** [comment]
Screenshot of the new UI
image

**Comment by WJohn** [comment]
Hm. Last thing I'd like with these is for them to all be aligned as much as is possible. Having them all sticking out at different distances is a bit messy looking.

**Comment by GunHog** [comment]
Maybe some colors, too? Red for bad, green for good? (Regarding electrification and power)

**Comment by vuonojenmustaturska** [comment]
**Ẅ̴̲̞́ͫͩͭ͌͒ͤͤͥ͠h̸̡̑́̉ͯ̓̿͑̆҉͕͔y̮̹̣͚ͦ͒͊ͯ͠͡͝ ̠̯̹ͤ͢n͕̠̦͔̠ͤ́͑͑͌ȏ͔͍͙̏͆̑̐͘͜ͅt͖̠̽̉ͯ̆̄ͤ ̱̦̭̙͓̱̆͊u̽̈̀ͦͤ̀͑͘͏̪̣̭s̮̟̹̘̩̥̭̒̈̓é̸̷͇̮̟͚̪͉̥̪̱̈́͆͑ͨͫ̓ ̭ͩ͋͗̓ͥ̽̅ͩ͘T̶̡̧͍͕̦̍̇ͧ̓ͥ̉̓ͨ͋G̵̝̯̞̦̓̆ͣ̄ͦ̉̎ͮ́Ư̥͚̑ͮͧͥȈ̖͔͔̫͓͢?̷ͥ̊ͤ͝͏͈̗͚̣̩̱̗̮**

**Comment by psykzz** [comment]
@vuonojenmustaturska if you have a guide on TGUI getting started, i'll do it.
@WJohn @GunHog i'll look into alignment and adding colours.

**Comment by Jalleo** [comment]
Lazy alognment solution is using tables.

**Comment by Xhuis** [comment]
I think they were joking about TGUI, since on the whole it's very slow. I think autorefresh is already implemented how the current UI works, at any rate.

**Comment by ike709** [comment]
@psykzz https://ftl13.com/wiki/index.php?title=How_to_Understand_TGUI

**Comment by Cyberboss** [comment]
This SHOULD be in TGUI for the auto update, but I'm not going to reject this PR because of it. It's still an improvement.

**Comment by psykzz** [comment]
Im working on TGUI, depending on how the first pass goes, ill update it. shouldn't be long.

**Comment by psykzz** [comment]
Almost done
image

**Comment by GunHog** [comment]
Emperor Bless You!

**Comment by Xhuis** [comment]
Ooh, very nice. 👍

**Comment by psykzz** [comment]
Final update and look
image

Also updated some TGUI stuff
> Update the TGUI package to allow you to natively run the gulp binaries, which makes it easier to work cross platform `npm run build` and `npm run watch` are both supported commands.

Should be ready for wider testing / merge.

**Comment by GunHog** [comment]
You somehow made it even BETTER! I nominate you our official TGUI writer!

**Comment by Cyberboss** [comment]
I agree with @GUN_HOG

**Comment by optimumtact** [comment]
you guys had this power all along, you just chose not to wield it

**Comment by JJRcop** [comment]
Open door and close door are missing from the new UI. Shift clicking doors wasn't working for me somehow.

**Pull request merged**
