### PR TITLE
Lowers the chance for monkeys to become gorillas

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
balance: Lowers the chance for monkeys to become gorillas
/:cl:

Closes #30108

### CODE REVIEW

**Comment by Supermichael777** [comment]
9.8% per life tick was probably way too high

**Comment by MoreRobustThanYou** [comment]
Now it's .98%. I can still lower it to .098%

**Comment by Supermichael777** [comment]
gorilla is less powerful then hulk, tk, space-walker, don't know why these guys are getting so triggered

**Comment by PraiseRatvar** [comment]
because you can mass-produce them, they are a more budget hulk and boy o boy geneticist traitor sounds op with 'em

**Comment by Kromgar** [comment]
They can rip off limbs. Hulks can not rip off limbs.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
No differences based on sentience!

**Comment by KingPhilipIII** [comment]
That is hilarious. Too bad I haven't been on lately to witness the mayhem.

**Review by Cyberboss — APPROVED** [review]

**Comment by RemieRichards** [comment]
@MoreRobustThanYou lower it to 0.098%

**Comment by RemieRichards** [comment]
👍

**Pull request merged**
