### PR TITLE
Fun->Show Tip verb added

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: Our administrators, here at /tg/, don't get enough credit for
their wealth of experience and knowledge. Now they get the chance to
share that with you by giving out custom tips!
/:cl:
- Show Tip verb, asks for input, then outputs it to all players in
  exactly the format that tips are displayed in. Also supresses the
  automatic tip if given before it's sent out.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Needs a way to have it come out at 30 seconds until round start so it's not obvious its fake

**Comment by coiax** [comment]
I don't think people really pay attention that much to the timing, and I didn't really forsee this being used preround, more for mega commentary during meme rounds.

**Comment by Jordie0608** [comment]
This functionality can be replicated by Global Narrate, I don't think we need another button just for this niche use.

**Comment by coiax** [comment]
I will put the ability to replace the tip of the round in, once I get a functioning machine again

**Pull request merged**
