### PR TITLE
Revert "Did you remember to install Counter-Strike Source? Adds emerg…

### PR DESCRIPTION
**Pull request by actioninja**
Revert of #50788 

## About The Pull Request

This was not tested at all, is very obviously and severely broken in many areas, and causes more trouble than it fixes.

@Iamgoofball if you want this to be merged again, fix the issues with it yourself instead of peddling the work off on to other people.

## Why It's Good For The Game

game now looks visibly and obviously broken for nearly a month.

## Changelog
:cl:
del: missing textures
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this PR was clearly made out of spite, :-1:

**Comment by actioninja** [comment]
Yeah, that's the response I expected.

**Comment by necromanceranne** [comment]
Yikes he self-merged it.

**Comment by Whoneedspacee** [comment]
yeah regardless of your intentions action this is not the way to do this cmon man.

**Comment by Iamgoofball** [comment]
for the record i am appalled this speed merge got speed reverted

i refuse to be a hypocrite on this, my revert should of remained up for the 24 hours and then had a decision made

it is entirely possible we would of wanted to keep this revert in place after 24 hours and this speed merge of a revert of the revert is a bad move

**Comment by nemvar** [comment]
f

**Comment by Cyberboss** [comment]
@Iamgoofball I sidestepped the rules for speed merging as damage control for the original incident. Not going to apologize for doing it, but I wish I didn't have to.

@actioninja This is not kosher. master branch is only able to remain unlocked in good faith that maintainers are able to self govern in accordance of our rules. Exceptions are allowed in extraordinary circumstances but this was not one of them. I don't even know or care what these PRs are about, but it's clear they do not warrant either speed or self merging. It's been in the game a month, it can wait another day. If something is super important, we have the test merge system to effect rapid patches. Forcing all the game servers and downstreams to instantly accept a change applied by one person undermines our credibility as a well-maintained upstream. An open pull request is infinitely better than a knee-jerk commit.

Take a breath, calm down, don't do it again. Consider this your warning.

**Pull request merged**
