### PR TITLE
Fixes slime jelly

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
Who the fuck botched this THIS badly

### CODE REVIEW

**Comment by Shapsy** [comment]
Taking suggestions for new values that don't deal half a crit's worth of damage in a single tick

**Comment by Incoming5643** [comment]
You've misread the code. adjustToxLoss(rand(20,60)*REM, 0) is the normal value. It's behind a prob(10) check that reduces its AVERAGE tox per tick to 4 tox. Slime Jelly is **supposed** to be hideously lurching with its damage application.

This pull just makes slime jelly comically weak.

**Comment by Shapsy** [comment]
Are you sure it's supposed to be that big of a jump though? That seems really out of wack with every other chem, though I admit I may have jumped the gun a bit

**Comment by Incoming5643** [comment]
It's a very very very old chem, so it's not surprising that it works a bit differently than most.

**Comment by LaharlMontogmmery** [comment]
Isn't slime jelly just supposed to be used by slime people for nutrients?

**Comment by Incoming5643** [comment]
it was comically toxin before I used it for their blood. It's just not toxic to slimepeople

**Pull request closed without merging**
