### PR TITLE
Removes station collision from away missions

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It's a generic, tiny burned out space station, with way too much loot, no challenge, and not enough interesting/unique stuff to be worth preserving or updating. Using a daemon as a singularity engine is kind of a neat concept though, maybe someone else will resurrect it later.

http://i.imgur.com/ZcslDNR.png

### CODE REVIEW

**Comment by WJohn** [comment]
:+1:

**Comment by Shadowlight213** [comment]
:+1: I hated that away mission anyways. Gave up on switching shit to airless tiles as I had to fuck with sprites constantly.

**Comment by ike709** [comment]
I dunno, I kinda want to see it remade from scratch to be less shit, but :+1: for now

**Comment by Jordie0608** [comment]
You will need to remove it from the away missions configs as well.

**Comment by KorPhaeron** [comment]
@Jordie0608

I did all of the updates in a file in my most recent commit to avoid conflicting with myself

**Pull request merged**
