### PR TITLE
Gives engineering basic circuit workstations

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
All in-rotation stations get a basic circuits workstation somewhere in engineering.
- Component printer
- Module duplicator
- 3 circuit omnitools (they don't need them but it signals that this is a circuit workstation)
- No BCI station because that's too advanced for them (they can build one anyways)

<details>

### Metastation:
image_2024-12-08_022056583

### Birdshot:
image_2024-12-08_022113656

### Deltastation:
image

### Icebox:
image

### Nebulastation
image

### Tramstation
image

### Wawastation
image

</details>

## Why It's Good For The Game
- Circuits are an incredibly unique and underused feature of the game, I think giving engineers the possibility to use it will increase its usage and push players to try it out, circuits were tucked away somewhere discreet before, now they'll be in plain sight so engineers get an urge to try them out.
- I think engineers are more likely to find good use out of circuits, especially when doing passion projects.
## Changelog
:cl: grungussuss
map: All station engineering departments now have a basic circuit workstation.
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
Meta and birdshot's circuit rooms look a bit empty, other than that I'm all in for this. While circuits are supposed to be a science nerd thing our current iteration has been made with a philosophy of avoiding direct interactions with players and relying on nearby machinery to perform circuit actions. Engineers have much more opportunities to capitalize off that, maybe circuits will see some more use with this.

**Comment by mc-oofert** [comment]
maybe we should buff circuits instead of them being kept weak and needing to be someone like you know who to get any real use out of them

**Comment by mc-oofert** [comment]
also tram, icebox, wawa edits look pretty bad i mean the machines are in the middle of the engineering access hall

**Comment by Sadboysuss** [comment]
> also tram, icebox, wawa edits look pretty bad

Didn't put too much effort into it at first because I didn't know how well it'd be recieved.

**Comment by norsvenska** [comment]
there is a doubled table on icebox

**Comment by moocowswag** [comment]
Ya circuits are more of an advanced form of assemblies and remote signalers, chemists can use them just as well as engineers, i kind of believe the sci circuit lab should have a front sci desk similar to robotics and genetics instead of being tucked so far away to the point where if you want something from the circuit lab on almost every map you go through maint.

**Pull request closed without merging**
