### PR TITLE
Fixes spelling for Lavaland Syndicate

### PR DESCRIPTION
**Pull request by YakumoChen**

### CODE REVIEW

**Comment by YakumoChen** [comment]
Am I doing it right? (please tell me I'm doing it right)

**Comment by YakumoChen** [comment]
oh no I have no idea what I'm doing

**Comment by YakumoChen** [comment]
im doin it guys im a real coder now

**Comment by RandomMarine** [comment]
Please don't have vague IC changelogs that only confuse players as to what the hell it actually means.
Especially not for fixing a single misspelled word. Something that small shouldn't have a changelog entry at all.

You're also reverting #26626's changes.

**Comment by YakumoChen** [comment]
those weren't in the current version of the code though?

**Comment by kevinz000** [comment]
kek

**Comment by kevinz000** [comment]
@YakumoChen not a real coder until you brick the server

**Comment by PKPenguin321** [comment]
Uh cheridan this reverted that other pr

**Pull request merged**
