### PR TITLE
gives viro access+ on skeleton crew

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
-gives virologist on skeleton crew access to medical lockers and plumbing for making virus pills

## Why It's Good For The Game
-QOL improvement for virologist on lower pop

## Changelog
:cl:
qol: virologists can now open the medical lockers in their own area
/:cl:

### CODE REVIEW

**Comment by Mooshimi** [comment]
it looks like the access is under surgery if they can't open it on skeleton crew, but they should have access normally?
image

**Comment by Mooshimi** [comment]
for #61059 btw

**Comment by Sealed101** [comment]
I don't quite remember virologists not having access to their medical lockers or chemistry rooms, I'm sure nothing changed?

**Comment by Fikou** [comment]
youre editing the normal viro access, not skeleton crew

**Comment by Mooshimi** [comment]
yeah just tested and it's fine.

**Comment by Mooshimi** [comment]
> youre editing the normal viro access, not skeleton crew

true, but they have access anyways so I'm closing this and it doesn't matter :P

**Pull request closed without merging**
