### PR TITLE
Add client pickable font for tgchat

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
Let players choose chat fonts

https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/547

credit to waltermelon from cm for this backport feature

@stylemistake 

## Changelog
:cl:
add: tgchat now has font selection
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
has science gone too far?

**Comment by Low3** [comment]
This is sin against god and nature, what do you think ss13 is? Some kind of user friendly game?

**Comment by tralezab** [comment]
https://www.dafont.com/minnie.font < mind throwing this in as an option?

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
Conflicts

**Review by stylemistake — CHANGES_REQUESTED** [review]
Needs to:

1. Have a default option, which disables the font override completely.
2. Have only one font family name per list item (i.e. Arial) instead of a clump of fallback fonts (Arial, blah blah, Helvetica, sans-serif). You can hardcode `sans-serif` as one fallback for all fonts.

Bonus points for custom fonts (e.g. free text input) or for complete detection of available system fonts.

I know this is a "port", but getting this right first time is important, so that you wouldn't have to write migrations or nuke chat settings later.

**Pull request closed without merging**
