### PR TITLE
Take away pyro slime's sentience

### PR DESCRIPTION
**Pull request by JAremko**
Alternative to #49277 and #49283

## Changelog
:cl:
balance: Anomaly slimes no longer sentient
/:cl:

### CODE REVIEW

**Comment by gitbirb** [comment]
half of the good bit of pyro anomalies is the slimes that come along. I dislike this idea.

**Comment by JAremko** [comment]
> half of the good bit of pyro anomalies is the slimes that come along. I dislike this idea.

It still spawns the slime :roll_eyes:

**Comment by IndieanaJones** [comment]
I enjoy playing as a slime as the round goes to shit.  If it were up to me, it'd be a hard pass, chief.

**Comment by improvedname** [comment]
@RaveRadbury can you open your pr its auctally the one what adresses whats broken about slimes having auctally structure damage.
Like this whole fucking slime bussiness is because 1 guy decided to be a literal piece of shit and destroy the supermatter apc and gravgen apc each round

**Comment by JAremko** [comment]
Yap would be fine with me :+1:

**Comment by JAremko** [comment]
Personal I think the best fix would be making slime afraid of machines so they wouldn't attack them (similar to swarmers) it should include everything that draws power, wires and piping. But at the same time give them ability to split and mind swap like jelly people do. then you can give anomaly slime associated with this greentext so it will have a goal and it will be aligned with what slimes are - ever hungry sneaky hunters.  

But it's  quite a lot of work and I doubt anyone cares enough to implement this.  :roll_eyes:

**Comment by dee-dubya** [comment]
apc dead pls nerf

**Comment by Tumesuo** [comment]
lmao cringe

**Comment by ExcessiveUseOfCobblestone** [comment]
a slime doesn't need to damage structures i don't know why "well if I can't damage an APC I might as well not play the role at all" is the conclusion people remotely come to.

**Comment by Cyberboss** [comment]
This is not a good alternative

**Comment by GuyonBroadway** [comment]
This here reeks of coders trying to fix an admin issue.

If a guy is being a little shit every round he needs to get bannified, not to have sections of the game cut out just to stop him specifically.

**Comment by JAremko** [comment]
> This here reeks of coders trying to fix an admin issue.
> 
> If a guy is being a little shit every round he needs to get bannified, not to have sections of the game cut out just to stop him specifically.

Welllll to be fair it is impossible to be an anomaly slime every round. Not only it doesn't spawn that often but also there are multiply ghosts competing for it.  But due to the lack of any golas, ability to communicate with anyone or even split and grow you every slime kinda forced in that role. And ones that practice it a bit become extremely destructive. While not even being an antag, they are neutral faction and have pAI role.

**Pull request closed without merging**
