### PR TITLE
Splits armour across the equipment slots.

### PR DESCRIPTION
**Pull request by KitsuneQueen**
## About The Pull Request
The title. Adds bulletproof and riot braces and greaves to the Armoury and Cargo, which share the same armour values as the vests.
armoury
crates
front
side
back

## Why It's Good For The Game
Currently the only combat gloves / shoes in the game are, well, combat gloves and no-slips which only give insulation and slip immunity. Moves the game away from insulated gloves being used for combat and instead making armour used.

Riot armour no longer covers the limbs, greaves and braces do.

Helps players know what part of their body is actually armoured, instead of having to guess.

## Changelog
:cl:
add: NanoTrasen has supplied their security force with armoured greaves and braces in an attempt to sell the same product for more money.
add: Riot and bulletproof braces and greaves added to Cargo Supply Console.
imageadd: Sprites for braces and greaves.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
the riot gloves should match the same worn length as the ballistic ones if they're gonna be that length item sprite (also that longer gloves are far better in terms of irl melee protection)

**Comment by Serxule** [comment]
also, the "combat braces" dont lose shock immunity right? shock immunity is insanely helpful and important to have

**Comment by WinterDarkraven** [comment]
> also, the "combat braces" dont lose shock immunity right? shock immunity is insanely helpful and important to have (or are combat gloves being kept still)

Combat gloves are separate and do not have armour values like before.


> the riot gloves should match the same worn length as the ballistic ones if they're gonna be that length item sprite (also that longer gloves are far better in terms of irl melee protection)

I didn't want to resprite the original riot suit, but I'm more than happy to sprite elbow pads to make it longer.

**Comment by Serxule** [comment]
> Combat gloves are still separate items with no armour values like before. They still have shock immunity.

was a bit confusing how you said it in the PR 

> I didn't want to resprite the original riot suit, but I'm more than happy to sprite elbow pads to make it longer.

could just snip off some of the extra length on the item sprite to fit better

**Comment by SomeoneYouProbablyKnow** [comment]
Is that really needed? i mean most everyone targets head/chest and targeting limbs to get around the armour is neat. This just adds more busywork for next to no benefit. Does add some neat drip options, so that's a plus
And If you want insuls to be bad for combat do the same fix we have for ranged weapons or maybe add a dropchance because this doesnt effect insuls in any way. And i dont think anyone has to guess anything, the armour protects the parts that the sprite covers (Even skirtsuits don't cover legs)

**Comment by Serxule** [comment]
> And If you want insuls to be bad for combat do the same fix we have for ranged weapons or maybe add a dropchance because this doesnt effect insuls in any way. 

sir refer to what they literally just said (also insuls are not very combat capable regardless, they cannot shoot guns or use batons)

>Combat gloves are still separate items with no armour values like before. They still have shock immunity.

**Comment by Serxule** [comment]
> I just don't really see how it's good for the game to add extra armour items you have to fiddle with when the extra armour is negligible

more variety, less metagamey loadouts (you have to pick and choose your gear), and as someone whose played on tgmc a lot, the armor on specific parts (arms, legs, torso, head) is insanely important, it most certainly applies to here too, because any experienced player will generally target legs before going for the head

**Comment by SomeoneYouProbablyKnow** [comment]
> more variety, less meta/powergame loadouts (you have to pick and choose your gear)

It's Armoury gear, it's inherently reactive, sec isn't supposed to use it unless shit's hitting the fan. If it's nuckies you take bullet, if it's most other things you take riot now you just have to take 4 items instead of 2 if you value the limb protection. It's not much of a choice. I don't see what you'd get from mixing and matching that stuff.

> And as someone whose played on tgmc a lot, the armor on specific parts (arms, legs, torso, head) is insanely important, it most certainly applies to here too, because any experienced player will generally target legs before going for the head

I don't think tgmc is 70% stuns by volume. I mean i'm sure it matters here for ranged combat for which you had time to prep against an experienced player who has not dobythrow or batonthrow stunned you. Not an impactful % though

**Comment by Serxule** [comment]
> It's Armoury gear, it's inherently reactive, sec isn't supposed to use it unless shit's hitting the fan. If it's nuckies you take bullet, if it's most other things you take riot now you just have to take 4 items instead of 2 if you value the limb protection. It's not much of a choice. I don't see what you'd get from mixing and matching that stuff.

you clearly havent played on sybil

> I don't think tgmc is 70% stuns by volume. I mean i'm sure it matters here for ranged combat for which you had time to prep against an experienced player who has not dobythrow or batonthrow stunned you. Not an impactful % though

i have no idea what you're trying to say here other than you've never played tgmc and maybe not even on TG servers, not for long anyways, i dont think you can really qualify for discussing game balance

**Comment by Fikou** [comment]
these are a direct upgrade to normal sec gloves/boots and having an item set of 4 different things you all have to carry seems very annoying

**Comment by SomeoneYouProbablyKnow** [comment]
> i dont think you can really qualify for discussing game balance

Brother this is a free forum and no one here is that qualified nor do they need to be.

If i'm wrong you should be able to explain why without having to resort to that kind of elitist attitude. 

Or ignore me, that's always an option. My word doesn't have much sway, neither does yours.

**Comment by Overuseddart** [comment]
This armour doesnt have counterplay (like aiming for limbs to bypass it). It seems that there’s no reason to ever not have this as a secoff (especially since you can get genes like insulated). A downside or counterplay to this armor would be nice so it isn’t just a direct upgrade.

**Comment by Autisem** [comment]
make the gloves thick with caviat you can still use batons and maby guns, Alternatifly make all other non combat actions slower like table climbing or using other tools? bassicly anything that is not stricly sec duty would be penelized

**Comment by optimumtact** [comment]
I dont think any maintainer would bother to merge this when we dont have a coherent idea of what we want armour to actually look like

**Comment by Mothblocks** [comment]
image

New head coder pronouncement

**Comment by Mothblocks** [comment]
That wasn't necessarily your motivation here (it is for some people, and was mentioned in the comments), but it definitely makes body zone switching way more important than I want

**Pull request closed without merging**
