### PR TITLE
Fixes #7086 Job selection window width

### LINKED ISSUE #7086: Job preferences menu is too wide
The sorting got messed up because of my splitting cargotechs/miners into their own 'supply' job sort. But i have literally no clue how to work with this HTML to restore it back to normal, so.

ss 2015-01-15 at 01 27 57

They should be below HoP, and their color should be brown.

### PR DESCRIPTION
**Pull request by Jordie0608**
Lazily makes supply jobs appear under hop in job selection
capture

### CODE REVIEW

**Comment by pudl** [comment]
alphabetical order for everything

**Comment by paprka** [comment]
Is there really no way to make supply its own section under service?

**Comment by pudl** [comment]
supply and service are technically the same department, i think

**Comment by Jordie0608** [comment]
@paprka yeah it's possible, but then it also looks like the QM is a head

**Comment by paprka** [comment]
Put cargo above the service jobs, below the HoP. Service/civillian jobs like lawyer, chaplain, etc don't really need a head of staff and their radio channel is VERY rarely used.

**Comment by Jordie0608** [comment]
Like this?
capture

**Comment by paprka** [comment]
Nah, directly below HoP.

Cap
HoP
Supply roles
Service roles (bartender, cook, janitor, botanist)
Civilian roles (chap. clown, lawyer, etc)

Service roles should also have the same lime-green color that their radio channel uses, if you want to do that it will separate them from the civilian (grey) roles better.

**Comment by Jordie0608** [comment]
Alright, colors are bolder than the existing ones but they're always easy to tweak later.

**Comment by paprka** [comment]
rip in peace file history

**Pull request merged**
