### PR TITLE
I WAS WRONG. YOU PEOPLE DON'T **DESERVE** MY FARTS

### PR DESCRIPTION
**Pull request by Cheridan**
Reverts tgstation/-tg-station#8684

### CODE REVIEW

**Comment by WJohn** [comment]
cancer

**Comment by Fayrik** [comment]
:+1: You say no one deserves it ironically, but they really do not deserve it.
Let it be on record forever, we tried to give people something nice. It was the worst thing ever.

**Comment by Incoming5643** [comment]
If I'm reading this correctly, if a slime person farts, he immediately dies.

:+1:

**Comment by CorruptComputer** [comment]
Please don't remove farting, can you instead turn it into an emote? Of course it would get annoying but you could put like a 5-10 minute cooldown on it.

**Comment by GunHog** [comment]
Our community cannot handle farts, or anything silly. See the horrific reaction to when Lizardpeople were allowed as a roundstart choice. It is really sad.

Imagine if the cat-people were kept as a permanent choice! I honestly believe that the server would implode and many, many players would be banned.

**Comment by Atskadan** [comment]
i would gladly allow myself to get banned if it meant i got to spree kill some furries first

**Comment by Kromgar** [comment]
Revert asap

**Comment by PKPenguin321** [comment]
Wow. I cannot believe this. A new feature gets added, and one coder gets dunked by it, and now it's "i ded pls revert"? Get your kneejerk reverts out of here. /tg/station isn't your sandbox for removing things you don't like personally. Was farting too difficult for you to play around? Maybe that's because it's new. Why don't you let the meta evolve a bit more before violently taking it out immediately? I can't believe you powergaming kneejerk-reverting no-good dirty-rotten coders.

**Comment by RemieRichards** [comment]
it's important :^)

**Pull request merged**
