### PR TITLE
Map Edit Atmo

### LINKED ISSUE #24656: O2 Gas Filter Orientation in Atmo
Recent changes to the basic TG station map have changed the starting orientation of the O2 gas filter in the waste loop. It is switched off and installed misaligned. This doesn't seem like it would be canon.

atmo

### PR DESCRIPTION
**Pull request by Penguaro**
Changed DIR of Gas Filter for O2 in Waste Loop from 1 to 4
Fixes #24656
:cl: Penguaro
fix: Changed DIR of Gas Filter for O2 in Waste Loop from 1 to 4
/:cl:

[]: # Current Default start for TgStation (AKA BoxStation) map has the O2 Gas filter pointing the wrong direction, causing the loop to start broken and inoperable past Nitrogen filtering. Newer players or smaller maps without an engineer may miss this and a broken loop does not seem canon to the general story.

### CODE REVIEW

**Comment by Cyberboss** [comment]
Add `Fixes #24656` to your PR body

**Comment by DanteRU0312** [comment]
Can confirm, always have to rotate this thing. Also, map is called Boxstation.

**Comment by Cyberboss** [comment]
Also, you fucked up the map merge for sure

**Comment by Penguaro** [comment]
Not sure how I impacted the map merge. The only change I'm away of touching was the specific map file.

**Comment by Cyberboss** [comment]
See here for how to edit maps: https://tgstation13.org/wiki/Map_Merger

**Comment by Penguaro** [comment]
Thank you for the feedback. I'll review that.

**Comment by Penguaro** [comment]
Re-Committed with Map Merge Tool.

**Comment by Supermichael777** [comment]
yummy word salid

**Pull request merged**
