### PR TITLE
Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

I have a feeling it was causing more overtime then maptick savings.

This is mostly done for testing on live, so we can see if it has any apprechiable effect on maptick, and if it helps td, by how much

## Why It's Good For The Game

We've started using overlays more often in place of vis_contents. Want to see if the overtime hit is reflected in maptick gains or not 
image

### CODE REVIEW

**Comment by Mothblocks** [comment]
#58382

**Comment by LemonInTheDark** [comment]
overtime of the subsystem is going down that's for sure. Not sure about maptick

**Comment by Mothblocks** [comment]
lemon is out of office right now but i want the reports back on this when he's back

**Comment by Kylerace** [comment]
data from @LemonInTheDark
image

delta on maptick is so small it either doesnt exist or we cant measure it over the course of months and we can measure the effect on SSoverlays/fire() overtime

**Pull request merged**
