### PR TITLE
Kilo Station

### PR DESCRIPTION
**Pull request by Okand37**
## About The Pull Request
Reboot of #43876
image

Adds a brand new map into rotation: Kilo Station! This map is intended as a medium population map that introduces a new and exciting formula to the cast of stations. 

You can access a mostly up-to-date map on [Renderbus](https://atlantaned.space/renderbus/)
[Forum Post](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=22551&p=492081#p492081)

## Why It's Good For The Game

This map focuses on a few simple principals to help create a unique but enjoyable experience:

**1. Compartmentalization:** Cutting out the middle man of hallways, departments are organised on a room-to-room basis, and most rooms have multiple ways in and out. This reduces dead space and brings the department closer together while allowing for more ways to move around the department. Ideally, this transcribes into your co-workers being less "out of sight, out of mind" and keeping engagement, as you're constantly in a workspace instead of an empty hallway. I think this will open up a lot of interesting venues for gameplay of all sorts!

**2. Organization:** Kilo Station strives to deviate from the formula popularized by Meta Station, but not without reason. It brings a more technical mindset to map organization, re-arranging areas and placing others in ways that boost their usability. Security posts are organized within the departments in a way bring their relevancy up by boosting their coverage and visibility. Low traffic areas like the library, surgery recovery room, courtroom, council chamber and chapel are re-arranged in ways to not only boost their visibility but increase their functionality. Some minor areas like the medbay patient rooms and the cargo warehouse have passed away.

**3. Resource Allotment & Scarcity:** In previous iterations of my maps, I've toyed with the balance of scarcity regarding both essential and non-essential items. Kilo Station focuses on having less non-job essential items strewn about the station while increasing some of the volume of certain job essential items, specifically in relation to engineering and atmospherics players.

**4. Functionality & Purpose:** In addition with the organisation changes made above, "maintenance loot" and their respective gimmick rooms have been overrun with simplemob NPCs. While not overtly destructive, the NPC mobs provide no loot of their own, but provide enough challenge to gate certain rare but useful items while providing a new point of interest for certain players to engage with. As well, a number of asteroids and rocks are placed around the station with low-mineral chance, opening up the venue of opportunity while allowing more ways for players to contribute to the round meaningfully.

**5. Atmosphere:** Last but not least, these various motifs along with the general appearance and environment serve to cultivate a specific lived in atmosphere where destruction, murder, and intrigue is just another day on the job. This aims to give the station a more unique personality to help it become a new and fresh experience for players.

## Recent Updates
Kilo Station was received fairly well during its initial PR and testmerge. As I now have time to properly contribute and maintain the map, I am PRing it again. Not included in the picture is a small changelog of updates to bring the map up to current speed, including:
- Second Operating Theatre in Medical
- Ticket Machine for HoP
- New Carpets
- White Ship & Freight Station Dock
- Smaller QoL Changes or Fixes

## To-Do List
Here's a [To-Do List](https://docs.google.com/document/d/1lFcZm_KAF135Wnf9iJ9oBtncXokkQF8JeA0NtKdWgvk/edit?usp=sharing) google document highlighting posted reports as well as ideas that will be worked on.

## Changelog
:cl: Okand37
add: Central Command has commissioned a new brand of Kilo-class stations. Rumours report the station design will be used in the up and coming Space Station 13 plasma research station.
/:cl:

### CODE REVIEW

**Comment by Ty-the-Smonk** [comment]
Is it still caution line 13

**Comment by Detective-Google** [comment]
I love kilo but the decal clutter is still rough :/

**Comment by CRITAWAKETS** [comment]
please get rid of all the useless caution lines like i get that you may hurt your hands handling plant trays without gloves but thats kinda a given

also the caution lines where firelocks go are pretty much just "beware, air"

**Comment by Okand37** [comment]
In response to the comments that've been posted, both here and before:

I'm always happy to take feedback into consideration, but I tend to be more willing to incorporate **functional feedback.** As this is just an **aesthetic choice**, I don't necessarily have any plans nor intentions on changing it. One reason it may be more disorientating is due to the comparison of other maps and their levels of detail, which weren't possible until the turf_decal system was introduced. One way metacide had put it in regards to Kilo Station was that a similar complaint had arisen about Meta Station and it's "overbearing detail" when Box Station was the go-to station, which you can find here #43876

> The visual style stands out and looks good, the map feels great to walk around in, can't wait to give this a try sometime with a full crew. As for the busy design with lots of warning tiles - when Meta first came out loads of people complained there were too many colourful or warning tiles compared to box and it's now the norm - this is fine, you just need to get accustomed to the increased level of detail. Here's hoping it's run again soon as a test, if not merged outright.

I think in time people will better adjust to the details, but it's something I feel helps the map stand out, and don't intend on changing it in the foreseeable future.

**Comment by Detective-Google** [comment]
> In response to the comments that've been posted, both here and before:
> 
> I'm always happy to take feedback into consideration, but I tend to be more willing to incorporate **functional feedback.** As this is just an **aesthetic choice**, I don't necessarily have any plans nor intentions on changing it. One reason it may be more disorientating is due to the comparison of other maps and their levels of detail, which weren't possible until the turf_decal system was introduced. One way metacide had put it in regards to Kilo Station was that a similar complaint had arisen about Meta Station and it's "overbearing detail" when Box Station was the go-to station, which you can find here #43876
> 
> > The visual style stands out and looks good, the map feels great to walk around in, can't wait to give this a try sometime with a full crew. As for the busy design with lots of warning tiles - when Meta first came out loads of people complained there were too many colourful or warning tiles compared to box and it's now the norm - this is fine, you just need to get accustomed to the increased level of detail. Here's hoping it's run again soon as a test, if not merged outright.
> 
> I think in time people will better adjust to the details, but it's something I feel helps the map stand out, and don't intend on changing it in the foreseeable future.

Personally it doesn't bother me but the "kilo crash" was a pretty common issue and a lot of people blamed it on the decals etc

**Comment by CRITAWAKETS** [comment]
It is an actual issue when the overload of decals causes even gaming PCs to struggle running the map with just around 25-30 people playing.

**Comment by Okand37** [comment]
> Personally it doesn't bother me but the "kilo crash" was a pretty common issue and a lot of people blamed it on the decals etc
> It is an actual issue when the overload of decals causes even gaming PCs to struggle running the map with just around 25-30 people playing.
I haven't shared any similar issues nor seen people report the issues prior, but I'll keep an ear open for this issue and see if similar cases are had.

**Comment by Poojawa** [comment]
Yay it's back!

**Comment by AdmiralPancakes1** [comment]
just to let you know, the fake nuke disk you put in the captain's room can be used to get illegal tech

might want to either remove the disk or make it not give illegal tech

**Comment by nicbn** [comment]
One thing I think doesn't make sense is the windows in the showers and toilets near dorms. No one would ever want to leave them open in an immersive-ish scenario.

Maintenance is pretty good but it has so much interesting stuff that I think it could be even bigger, making the interesting bits farther apart and giving more room to wander around maint.

I think vacant commissary is a bit too small, I suggest making it at least one tile taller on the y direction. That would make maintenance below it really tight tho.

It'd be cool if you added a fast route between bar and kitchen, given that they are relatively far apart, so that food may be delivered to the bar. Disposal pipes would be nice, transit tubes as well, but there's not much room for the terminals of transit tubes.

Between the airlocks going from atmos to engine there's a misplaced air alarm (renderbus version).

**Review by jdawg1290 — APPROVED** [review]

**Comment by 81Denton** [comment]
@Okand37 Is this WIP or ready for review/test merge?

**Comment by Okand37** [comment]
> just to let you know, the fake nuke disk you put in the captain's room can be used to get illegal tech
> 
> might want to either remove the disk or make it not give illegal tech

I'll see if I can do the latter, as I enjoy the gimmick. 

> One thing I think doesn't make sense is the windows in the showers and toilets near dorms. No one would ever want to leave them open in an immersive-ish scenario.

The main reason for this is just so they can be broken and used as an escape route for whatever reason that might occur.

> Maintenance is pretty good but it has so much interesting stuff that I think it could be even bigger, making the interesting bits farther apart and giving more room to wander around maint.

I'm pretty comfortable with how spaced and sized it is right now, but if there are any specific suggestions you have in mind I'd be more than happy to hear them!

> I think vacant commissary is a bit too small, I suggest making it at least one tile taller on the y direction. That would make maintenance below it really tight tho.

It'd definitely be possible. I'll keep my thumb on it and see how I think about this idea later.

> It'd be cool if you added a fast route between bar and kitchen, given that they are relatively far apart, so that food may be delivered to the bar. Disposal pipes would be nice, transit tubes as well, but there's not much room for the terminals of transit tubes.

Someone had suggested a food chute before. It's something that has been on the mind, but I'd like to see how the dynamic plays out more before jumping to this. I like the kitchen being a place to visit on your own to get food, too.

> Between the airlocks going from atmos to engine there's a misplaced air alarm (renderbus version).

Just on the renderbus version, but good catch!

**Comment by optimumtact** [comment]
enough, no more comments on the decals, unless you have  proof they cause client crashes (in which case make a byond bug report first).

**Comment by CRITAWAKETS** [comment]
repost since off-topicized but needs to be addressed

SM scrubber is extremely easy to break into its area with only a regular wall that is accessible from maint. You can just place a floor tile and get the waste gases outputted into maint or you can unwrench the scrubber and put the gases in distro. I recommend replacing the walls seperating the scrubber from maint with r-walls.

**Comment by Irafas** [comment]
Found one issue in Operating Theatre A. The Smart Organ Storage machine x/y coords is on the tile with the holopad and pixel_x/pixel_y has been used to shift it down and left. This means that you can't walk over the holopad because the SOS blocking it, making it awkward to reach the crate of prosthetic limbs

_Artists rendition of captain trying to reach a crate of prosthetic limbs_
holopad-1

**Comment by Irafas** [comment]
In the SM's Laser Room the left side is missing a cable piece under the airlock meaning the emitters won't function. The pipes are covering some wiring. The right side does connect to those wires as well so it looks like the left side is an oversight.

smcable-1

**Comment by Okand37** [comment]
> SM scrubber is extremely easy to break into its area with only a regular wall that is accessible from maint. You can just place a floor tile and get the waste gases outputted into maint or you can unwrench the scrubber and put the gases in distro. I recommend replacing the walls seperating the scrubber from maint with r-walls.

I'd like to see how it plays out, as it wasn't particularly an issue during earlier test-merges. I want to strike a balance between things being easier to sabotage than on, say, metastation--but not in a way that easily detracts from the round. Good pointing it out, though!



> Found one issue in Operating Theatre A. The Smart Organ Storage machine x/y coords is on the tile with the holopad and pixel_x/pixel_y has been used to shift it down and left. This means that you can't walk over the holopad because the SOS blocking it, making it awkward to reach the crate of prosthetic limbs

> _Artists rendition of captain trying to reach a crate of prosthetic limbs_
> holopad-1

It's funny cause I should really remember that stuff works like this. I've replaced the table and medical records laptop with the smart organ storage. Thanks for letting me know and I appreciate the graphic, very informative! 😛 


> In the SM's Laser Room the left side is missing a cable piece under the airlock meaning the emitters won't function. The pipes are covering some wiring. The right side does connect to those wires as well so it looks like the left side is an oversight.
> 
> smcable-1

Definitely an oversight. The cable was just missing from under the door from when I had to re-wire it due to the wiring update.

**Comment by MCterra10** [comment]
It's back it's back it's back!!

**Comment by actioninja** [comment]
https://www.youtube.com/watch?v=V6f2OiYXx5E

**Comment by Qustinnus** [comment]
Can we pull another map out of the repo if thsi is merged?

**Comment by MacBlaze1** [comment]
Add a second surgery room, meta has one and delta has tons of maint surgery tables. It works well with cobby chem and stuff.

**Comment by Okand37** [comment]
> Add a second surgery room, meta has one and delta has tons of maint surgery tables. It works well with cobby chem and stuff.

If you'll notice in the PR's description, I mentioned the renderbus image was only "mostly-up-to-date." In the "recent changes" section, you'll see some updates that have been made after the renderbus image was taken that help to update the map to current-standings. This includes the HoP's ticket system and the second surgery room.

**Comment by Okand37** [comment]
Incase it is helpful, here's a post of the updates made after the renderbus image was taken, and are either implemented in the PR already or will be in one grouped update:

### New Features
- Updated carpets in the Bar, Library, Law Office, Detective's Office, Head of Security's Office, and Captain's Office, among other areas.
- Updated the Head of Personnel's office with the ticket machine and ticket increment button.
- Replaced the old mining shuttle with a stylized version of the larger type. 
- Added the White Ship and a small freight dock nestled in abandoned territory.


### Minor Updates
- Added a medical kiosk to the medical reception lobby.
- Added a biohazardous room to maintenance where a far more biohazardous creature resides.
- Added a door-bolt toggle to the maintenance bank vault's door.
- Removed one of the easier-to-obtain stethoscopes from the medbay.
- Fixed the stacking machine. It is now linked to the console and vice versa.
- Fixed Kilo-Kocktail not containing reagents.
- Fixed a few areas where the tile decals were applying over other decals, discolouring them.
- Multiple small fixes for the powernet after rewiring it.
- Replaced the RCLs with cable coil spools.
- Replaced the medical laptop in the primary operating theatre with the smart organ storage device.
- Replaced the cherry donut in security with a regular donut.
- Reallocated the lobster suit to the toy crate.
- Smaller undocumented QoL changes or fixes.

**Comment by nicbn** [comment]
>Replaced the cherry donut in security with a regular donut.

How dare you

**Comment by Okand37** [comment]
> > Replaced the cherry donut in security with a regular donut.
> 
> How dare you

Preparing for #46933 which adds a myriad of donuts, but removes the cherry jelly donut.

**Comment by kriskog** [comment]
Atmospherics has some issues:
 - Gas sensor in incinerator is the wrong type. Use the incinerator subtype, or it wont read off on the console.
 - The cycling airlock into the incinerator doesnt seem to work. Vent stayed off, may need linking?
 - The incinerator output should have a maxed pump and the engine variant of the injector

**Comment by Okand37** [comment]
> Atmospherics has some issues:
> 
> * Gas sensor in incinerator is the wrong type. Use the incinerator subtype, or it wont read off on the console.
> * The cycling airlock into the incinerator doesnt seem to work. Vent stayed off, may need linking?
> * The incinerator output should have a maxed pump and the engine variant of the injector

Thanks for letting me know. I'll make sure to list these down and work on them with the next update!

**Comment by Detective-Google** [comment]
image
vents in the new arrivals airlocks so they can't even get out of the shuttle during a gas flood 😬 

in general this map rewards plasma flooding too much since it's such a boring copout

**Comment by Okand37** [comment]
> image
> vents in the new arrivals airlocks so they can't even get out of the shuttle during a gas flood 😬
> 
> in general this map rewards plasma flooding too much since it's such a boring copout

I'll remove the vents from the arrivals airlocks, and possibly add some emergency airlocks into maintenance near the gravity generator.

Could you elaborate a bit on the latter part? What makes you think this map rewards plasma flooding over others? What are some specific examples that could be rebalanced or changed?
The major departments (science, medical, security) each have their own Atmospherics Connectors that you can use to turn off flow from the distribution loop to the department.

**Comment by Detective-Google** [comment]
> > image
> > vents in the new arrivals airlocks so they can't even get out of the shuttle during a gas flood 😬
> > in general this map rewards plasma flooding too much since it's such a boring copout
> 
> I'll remove the vents from the arrivals airlocks, and possibly add some emergency airlocks into maintenance near the gravity generator.
> 
> Could you elaborate a bit on the latter part? What makes you think this map rewards plasma flooding over others? What are some specific examples that could be rebalanced or changed?
> The major departments (science, medical, security) each have their own Atmospherics Connectors that you can use to turn off flow from the distribution loop to the department.

same amount of plasma but everything is more compact, there's a lot of vents compared to how compact everything is, in general less vents and less scrubbers, the station has a really robust atmos setup compared to how everything else is a bit bootleg in design

**Comment by Okand37** [comment]
> same amount of plasma but everything is more compact, there's a lot of vents compared to how compact everything is, in general less vents and less scrubbers, the station has a really robust atmos setup compared to how everything else is a bit bootleg in design

Compactness is apart of the design feature, but I can see how the ratio of vents-and-scrubbers to size would effect how quickly or slowly a room is flooded. Most rooms try to abide by having a single vent and scrubber each--are there any specific areas (the halls, certain departments or rooms, etc) you feel have too many for their size? I'd be more than happy to see what I could do to help mitigate the damage without removing it entirely.

**Comment by Rohesie** [comment]
The bar could use another camera at least.
Noticed the AI often lacking access to people who requested things on radio. Maybe a local test as AI might be positive to see where the eyes are not reaching.

**Comment by Detective-Google** [comment]
people have also been saying the PDA server doesn't work during the most recent batch of tests on sybil

**Comment by Okand37** [comment]
> people have also been saying the PDA server doesn't work during the most recent batch of tests on sybil

Something is definitely up with it not linking with the main server. This also results in the encryption key paper spawning empty for the CE or syndicate agents. It is certainly on the to-do list!

**Comment by Okand37** [comment]
I've added a To-Do List to the bottom of the initial post, and I'll post it here:
## To-Do List
Here's a [To-Do List](https://docs.google.com/document/d/1lFcZm_KAF135Wnf9iJ9oBtncXokkQF8JeA0NtKdWgvk/edit?usp=sharing) google document highlighting posted reports as well as ideas that will be worked on.

**Comment by MacBlaze1** [comment]
Medical Toggle button for the entrance doors do not work

**Comment by PKPenguin321** [comment]
I mentioned it in the goof PR but once this goes through I'm gonna be running a favorite map poll

**Comment by Okand37** [comment]
> Medical Toggle button for the entrance doors do not work

I'll see what I can do, thanks for bringing this to my attention!

> I mentioned it in the goof PR but once this goes through I'm gonna be running a favorite map poll

You should consider consulting with oranges on this subject, as he may have had specific plans on this.

**Comment by TheSilverNuke** [comment]
[https://i.imgur.com/6CFbXnb.png](url) This lower maint door has to be bolted open every time I want access to the aux base as either a robo or a scientist, I would suggest adding Sci access to it so that scientists can properly maneuver around the xenobio maint.

**Comment by optimumtact** [comment]
@TheSilverNuke wat
image

**Comment by TheSilverNuke** [comment]
Uh I was able to open that image in a private window so you definitely don't need logged into. But its the door to the right and down of the Aux base.

**Comment by Rohesie** [comment]
This is the image in the link:
6CFbXnb

**Comment by Tharcoonvagh** [comment]
@Okand37 some problems:
-The AI dies in thirty minutes for some reason, probably wiring
-People can get fat loot from maint, including sunglasses, a powergamer's dream
-This is not really a mapping problem, but it still is a big bad boy. The map rotation. With the default map being Meta, anytime a map vote happens, the people who did not vote probably left their default map the same. This means that we won't be able to play on Kilo. Ever.

Otherwise this is my favourite map! Good work! ❤️

**Comment by Moonman121** [comment]
There is a single, standard door leading directly into the captains office from maint, making breaking into it and stealing the locker very easy. Shitters should at least have to put in some form of effort to get the locker.

**Comment by TheSilverNuke** [comment]
EVA has 50 sheets of plasteel, this should be reduced to 10 or 15.

**Comment by kriskog** [comment]
>
>
>This is not really a mapping problem, but it still is a big bad boy. The map rotation. With the default map being Meta, anytime a map vote happens, the people who did not vote probably left their default map the same. This means that we won't be able to play on Kilo. Ever.

Votes read off preferred map, which a lot of people have set to meta because they like meta. The default map was changed to nothing just after voting was added to prevent this exact situation. You'll notice how the default option is blank, where it used to specify metastation.

**Comment by TheSilverNuke** [comment]
Bad spot for a disposal unit

**Comment by Okand37** [comment]
## Patch 10/15/19
- Edits to the incinerator in an attempt to fix the gas sensor, airlock cycler, and vent as well as max the output of the exterior ejector.
- Added optional science access to the maintenance door leading up to the auxiliary mining base as a temporary fix for scientist's to access the base before multi-z is introduced.
- Added a command camera to the area outside of the captain's tactical relocation. It is listed as "Captain's Tactical Relocation" on the base network.
- Replaced the telecomms/message_server with the /preset subtype. It should now spawn linked at round start.
- Replaced the dangerous and archaic cake hat with some fish fingers made out of their killer.
- Removed vents from the arrivals airlocks to prevent them from being flooded.
- Removed the lootdrop/grille_or_trash spawners in maintenance due to the new wiring system creating shocked grilles.
- Removed the sunglasses in maintenance and replaced with a snazzy tie.
- Fixed the missing wire below the AI's SMES, and added another SMES for the rest of the satellite due to higher power consumption.
- Fixed the Medbay Doors Toggle button not being linked to the medbay doors properly.
- Adjusted the plasteel count in E.V.A., there are now 10 plasteel sheets in the stack.
- Adjusted the position of the disposal's bin in the medical lobby.
- Lawyers can no longer access the security office.

**Comment by RaveRadbury** [comment]
Sitting in the medical reception booth you can't see the medical lobby doors or anyone standing in front of them, yet you're expected to work the button for that set of doors. Intended?

**Comment by TheSilverNuke** [comment]
>No Robotics AI Holopad
>Curator doesn't have access to Aux base, only construction
>Many assistants and other maint wanderer's aren't equipped or able to fight the multiple dangerous mobs in various locations and round start and end up wandering into areas where they shouldn't be.
>Random holes in asteroid terrain that an unsuspecting blob might spawn into and get trapped, realizing that it can't break out of the rock and destroy it (blobs can't destroy rock for some reason)
>APC and air alarm locations are difficult to locate in the main hallway, and it can be unclear as to what APC's or alarms connect to which segment of the hallway at a glance. Could be fixed by making the main hallway into two rooms split in a hemispheric manner.
>Unabundance of fire lockers (Could be fine with the current amount, however should be easier to locate)
>Brig prisoner pens can see directly into dorms bathrooms, I know that if I was here, I wouldn't want to see some potential prisoner staring at me while I was on the toilet.
>Evac signs to lead people to pods?

**Comment by Okand37** [comment]
> Sitting in the medical reception booth you can't see the medical lobby doors or anyone standing in front of them, yet you're expected to work the button for that set of doors. Intended?

This isn't intentional or unintentional per say, it just happened as a result of how things were set up. 

> Many assistants and other maint wanderer's aren't equipped or able to fight the multiple dangerous mobs in various locations and round start and end up wandering into areas where they shouldn't be.

This danger is intentional and should subside as people begin to become more familiar with the map. The mobs are all selected in the way that you should be able to defeat them all on your own, albeit suffering wounds, as long as you're carrying a weapon. I tested most of them with a spear or baseball bat as a default assistant. Consider preparing before endeavoring into the unknown!

> Random holes in asteroid terrain that an unsuspecting blob might spawn into and get trapped, realizing that it can't break out of the rock and destroy it (blobs can't destroy rock for some reason)

I don't really follow this one. Player controlled blobs are able to choose their spawn, and none of the AI event blobs spawn in the rock. Where might this be an issue or has been an issue before?

> APC and air alarm locations are difficult to locate in the main hallway, and it can be unclear as to what APC's or alarms connect to which segment of the hallway at a glance. Could be fixed by making the main hallway into two rooms split in a hemispheric manner.

Most of the firelocks, barring a few mid-section firelocks, define the borders of the different areas of the hall. Becoming more familiar with the areas and the air alarms will come with familiarity with the map itself.

> Unabundance of fire lockers (Could be fine with the current amount, however should be easier to locate)

Metastation and Kilostation both have 3 firelockers in the main hall. There is also one firelocker in the security hall, as opposed to metastation having one in each starboard and port halls, but that is the result of a larger width. Kilo has 3 Emergency Storage locations, 2 of which have firelockers in them, and the latter has a firelocker outside in the hall. These also include other emergency air items. There are also a plethora of them inside maintenance. This is again going to be an issue with unfamiliarity.

> Brig prisoner pens can see directly into dorms bathrooms, I know that if I was here, I wouldn't want to see some potential prisoner staring at me while I was on the toilet.

Each shower and toilet unit have an optional shutter. The reason they have shutters instead of walls is because I want people to be able to break the windows for escapes, or to create access ways.

> Evac signs to lead people to pods?

There are already EVAC signs in each department near the closest maintenance door that shows which direction the pod is in. For security, it is in the security office pointing downward. For medical, it is in the breakroom pointing down and another in maintenance pointing left. Science has signs in the access between xenobiology and science, as well as toxins. There are also some pod signs in maintenance itself. 

I think a lot of these tie into the idea of unfamiliarity and new territory, but also the increased visual clutter. Some of them (like the pods, or firelockers, or auxiliary base) will be amended when multi-z is introduced for Kilo.

**Comment by TheSilverNuke** [comment]
As far as the blob is concerned I experienced that one directly. I saw a random hole in the rock to the right of science and there was one Goliath there, so I thought it would be a neat spawn. Turns out I couldn't break out of the rock at all, and an admin had to delete a path out.

**Comment by Okand37** [comment]
> As far as the blob is concerned I experienced that one directly. I saw a random hole in the rock to the right of science and there was one Goliath there, so I thought it would be a neat spawn. Turns out I couldn't break out of the rock at all, and an admin had to delete a path out.

This seems like something that could be alleviated code-wise by either allowing blobs to break through rock, or by disallowing them to spawn in area/space/nearstation. This would still allow them to spawn on the solars, but prevent them from spawning on exterior plating or asteroid turf.

**Comment by Okand37** [comment]
While we continue to grind out bugs and refine balance, I'm also going to be starting progress on the multi-z aspect of Kilo Station. 
## Kilo Station Multi-Z Progress has begun!
This will shift some things to the lower levels, like the pods to a proper escape pod launch bay, as well as include extra areas and quarters for each head of staff under their offices. As an example, here's the Captain's Quarters side-by-side with the Captain's Office for comparison.
image

**Comment by Qustinnus** [comment]
@Okand37 if you make maint that runs under the floor in the hallways / rooms and also have grates/catwalks that look into maint I'll help u code it

**Comment by kriskog** [comment]
#47242

**Comment by Okand37** [comment]
## Patch 10/23/19
- Added a missing disposal pipe in the line going through science maintenance.
- Adjusted the wiring setup so the left and right side should both be connected to the inputs, which then can go through the SMES’ and into the power grid.
- Added a holopad in robotics.
- Added a green and mixed wardrobe to maintenance below the dormitory area, near the detective’s office.
- Curators can now access the doors leading from maintenance near the gateway up to the Auxiliary base.
- Replaced one of the soda vendors in recreation with a water cooler.
- Replaced the black bedsheets in dorms with random spawner subtypes.
- Replaced the front “Brig” doors with the /glass subtypes.

**Comment by TheSilverNuke** [comment]
AI is unable to trap people inside the upload. I recommend adding blast doors here in front of this transit tube to prevent tiders from diving in and escaping.

2019-10-24 23_24_51-Window

Mice spawn in this area and the turrets always will fire at them in response, but be unable to kill them.

2019-10-24 23_26_27-Window

I would recommend cameras on this southern arrivals wall. The blank zone here can make it a nice area for someone to get imprisoned, and unable to escape as the arrivals shuttle gibs them. Much like tying someone to a railroad track. On second thought, you can keep that, or not. Completely optional.

2019-10-24 23_29_10-Window

Nightmare spawning on solars

2019-10-24 23_39_01-Window

Hazard closet not public access

2019-10-24 23_43_37-Window

I can only give feedback with areas that I actually play in. So apologies if it's sci/silicon focused feedback, and not enough sec, cargo, medical, etc.

**Comment by Tlaltecuhtli** [comment]
why are there double firelocks on arrival shuttle? it already has double airlock it just makes it impossible to get out if someone activates the fire alarm and steals the crowbars
kilosucks

**Comment by Okand37** [comment]
> AI is unable to trap people inside the upload. I recommend adding blast doors here in front of this transit tube to prevent tiders from diving in and escaping.

It is part of why the lockdown shutters are on the other end--to prevent people from using the tube or at least escaping in a timely manner. This might not be entirely effective, however. I think when I introduce multi-z, I will replace the outside area with a down-look so it is a bit more reinforced. In the meantime, I'm going to make the area space and see how that plays out.

> I would recommend cameras on this southern arrivals wall. The blank zone here can make it a nice area for someone to get imprisoned, and unable to escape as the arrivals shuttle gibs them. Much like tying someone to a railroad track. On second thought, you can keep that, or not. Completely optional.

Sounds funny! I'll add some cameras though.

> Nightmare spawning on solars

The areas are the same on Kilo Station as any other station, no reason they should spawn on the solars if they aren't capable of doing so on the other maps too, as far as I'm aware at least. If you decude a reason as to why this is, feel free to let me know! The only landmarks are for carp or xenomorphs on the solars.

> Hazard closet not public access

That is because the hazard closet is apart of security. It'll likely be moved belowdecks but rests in its maintenance closet so people can break in and steal from it for now.

> why are there double firelocks on arrival shuttle? it already has double airlock it just makes it impossible to get out if someone activates the fire alarm and steals the crowbars

That is because they are not intended to be there. Double airlocks are standard on every map, however, and they should have safety-mode enabled which allows people to pry them open without tools if they're depowered. Thanks for the creatively named image!

**Comment by Learner10** [comment]
In quite a few games (about 40-50% of them), the station has had some weird power issues, between the SM emitters not running/receiving power and the solars not providing enough... though thankfully the turbine runs well enough (thank you gas miners).

I could attribute the solars to something relating to stuff being in the way of them. I mean, if the solars DIDN'T need a clear line of sight, then they'd just always provide power with their tracking right? But Kilo isn't a perfectly clear map, it's got rocks and a station and stuff.

As for the SM... I couldn't begin to explain it. I mean, the power net looks like it should be stable enough for the emitters to function. My one and only theory is that perhaps the SMES are feeding into each other, which makes the overall available power incorrect. I mean, if you made a closed circuit loop for an SMES, all the power available would be whatever it was putting out, and though I don't know priorities for power, I'd imagined that an SMES sits a little high.

Also, got an ETA on the White Ship?

**Comment by actioninja** [comment]
Sporadic issues with things failing to be powered sounds like there's somewhere where a smes input is connected to the output.

**Comment by anconfuzedrock** [comment]
Why the hell does the warden get a completely non functional computer? replace it with a prisoner management console or better yet remove it altogether. it just takes up space.

**Comment by Okand37** [comment]
> In quite a few games (about 40-50% of them), the station has had some weird power issues, between the SM emitters not running/receiving power and the solars not providing enough... though thankfully the turbine runs well enough (thank you gas miners).

With how the new wires work, it ends up having there being a wide node under the terminal and another under the SMES, which tends to auto connect them. I'm still looking at maps to understand how they do it and if it is avoided on them, or if the issue is persistent across them all now. I'd like to figure out how to deal with this if so.

> Also, got an ETA on the White Ship being available?

It should already be present, though it might be having some issues that I'm unaware of that might be causing it to spawn funky?

> Why the hell does the warden get a completely non functional computer? replace it with a prisoner management console or better yet remove it altogether. it just takes up space.

Because pathtypes changed the prisoner computer to two subtypes.  This is already fixed in the next update, but thanks for mentioning it.

**Comment by Learner10** [comment]
The White Ship, whenever I've sought it out, always appears to spawn on the same Z level (that one being 13). When I've investigated it as a ghost, it seemed to be one of those isolated Z levels.

As for the SMES issue, I 'think' that if a player places a wire beneath an SMES when it's already got a power terminal, the game automatically prevents the two wires from connecting. (Experience: setting up the north SMES at the Derelict.) If the solution can't be found, a handy paper note sitting nearby couldn't hurt. Most set-ups are just learned and rehashed behavior after all.

**Comment by actioninja** [comment]
> With how the new wires work, it ends up having there being a wide node under the terminal and another under the SMES, which tends to auto connect them. I'm still looking at maps to understand how they do it and if it is avoided on them, or if the issue is persistent across them all now. I'd like to figure out how to deal with this if so.

Correct on that smes > terminal do not link, but they can still feedback on to each other elsewhere in the network.

**Comment by actioninja** [comment]
Found the problem spot.
image
diagram showing how the cables are connecting to cause this.
Issue is that there's a cable for the engineering console right underneath:
image

**Comment by Tlaltecuhtli** [comment]
i m not talking about airlocks there are double FIRElocks too

**Comment by Okand37** [comment]
> Found the problem spot.
> image
> diagram showing how the cables are connecting to cause this.
> Issue is that there's a cable for the engineering console right underneath:
> image

That makes sense. I'll have to reallocate the computers so it can still function as a power monitoring console somewhere else.

**Comment by Okand37** [comment]
> i m not talking about airlocks there are double FIRElocks too

> That is because they are not intended to be there. 

This is in response to the double firelocks.

> Double airlocks are standard on every map, however, and they should have safety-mode enabled which allows people to pry them open without tools if they're depowered.

This is in response to you saying it would be hard to open them without crowbars. The intention is to have safety mode enabled on the airlocks so crowbars aren't needed. This was meant to reassure you that the firelocks were unintended as you're supposed to be able to get off the shuttle without a crowbar.

**Comment by optimumtact** [comment]
I'll hold a map vote near christmas to decide which map gets bumped in favour of this one

**Comment by Tharcoonvagh** [comment]
Donut please

**Comment by TheVekter** [comment]
Bump meta. Take the fucking _shot_.

**Comment by PKPenguin321** [comment]
As promised I'll set up a favorite map poll

**Pull request merged**
