### PR TITLE
Prevent monkies/animals from picking up intercoms

### LINKED ISSUE #15452: Monkeys can pick up wall radios
HELP: Scaredofshadows/(monkey (406)) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): as monkey I can pick up wall radios 

He was indeed picking up and dropping an intercomm from the inside of an escape pod

### PR DESCRIPTION
**Pull request by neersighted**
WHY ARE THESE NOT ACTUAL MACHINES AAAAA
ANCHORED ITEMS?!

Fixes #15452

:cl:
tweak: Gibtonite can now be pulled.
/:cl:

### CODE REVIEW

**Comment by MrStonedOne** [comment]
No, no no no no no no no no.

Fix the core bug, nobody should be able to pick up anchored items.

**Comment by duncathan** [comment]
Shitty bandaid fix :-1:

**Comment by neersighted** [comment]
Okay let's check anchored in attack_{hand,paw} aaaaa

**Comment by xxalpha** [comment]
It really should be a machine. Items are not usually anchored, machines are.

**Comment by neersighted** [comment]
That would require an embedded radio and messing with saycode... aaaaaa maybe another time

**Comment by ChangelingRain** [comment]
But gibtonite is anchored, MSO!

**Comment by Jordie0608** [comment]
>Gibtonite is anchored

Is there any strong reason for this because the easier solution here is to make it unanchored

**Pull request merged**
