### PR TITLE
Port tgui to ES6

### PR DESCRIPTION
**Pull request by neersighted**
Replaces Coffeescript with ES6

### CODE REVIEW

**Comment by WJohn** [comment]
I've completely given up even trying to understand the wizardry you're pulling on the UI. I guess keep doing whatever it is you're doing??

:+1:

**Comment by Incoming5643** [comment]
>removes IE8 support  
:-1:

**Comment by hornygranny** [comment]
please tell me you're fucking joking

**Comment by neersighted** [comment]
Wine will support IE9-11 soon (http://www.wine-staging.com/news/2015-12-22-release-1.8.html), and VMs are available from Microsoft (http://modern.ie).

**Comment by Incoming5643** [comment]
I legitimately believe that a machine from 2003 should be able to play this game. I mean if it's truely unsustainable that's one thing, but I'll still :-1: .

**Comment by KazeEspada** [comment]
a 13 year old computer cant run shit.

**Comment by hornygranny** [comment]
it's literally out of support on anything but windows thin pc (2011) and windows embedded (2009)

**Comment by neersighted** [comment]
https://www.microsoft.com/en-us/WindowsForBusiness/end-of-xp-support
https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=internet%20explorer
http://windows.microsoft.com/en-us/windows/lifecycle

**Comment by neersighted** [comment]
Also IE auto-updates after 9: https://technet.microsoft.com/en-us/browser/gg615599.aspx

**Comment by Incoming5643** [comment]
it's a moral :-1: not a practical :-1: . You can merge this, I'll just be a little sad :<

**Comment by Bawhoppen** [comment]
I do kind of agree with incoming about the fact you could play this since 2003 on original exadv1 code and never need to upgrade

**Comment by KazeEspada** [comment]
You still dont. You just have to disable fancy tgui. Ugly tgui still works on shittops.

**Comment by JJRcop** [comment]
So basically this removes CoffeeScript stuff, which is a language that compiles to JavaScript and is intended to make it better, with ECMAScript 6, aka ES6, a new version of JavaScript which borrows from the improvements CoffeeScript made, but of course is more official I guess.

**Comment by MrStonedOne** [comment]
IE8 is the highest IE that can be installed on XP.

I don't know, I think we should still be supporting and targeting XP

**Comment by neersighted** [comment]
IE8 and XP are both EOL.

**Comment by Supermichael777** [comment]
its not as if you cant run byond on a crappy new computer(which is probably more powerful than your old computer. Remember when 4 gig was top of the line?)

**Comment by neersighted** [comment]
I remember paying $90 for a 256mb -> 512mb upgrade ;-;

**Comment by vista-** [comment]
If <IE9 is still supported by the "no frills" UI style, then :+1:, if not, then :100:x:-1:
You are not only breaking compatibility for XP users (may god have mercy on their souls), but Linux/Wine users as well. 

Before saying "Windows VM", please consider that only software mode is available that way without pretty serious hacks, and that won't work with the upcoming lighting modifications and runs pretty shit anyway.

**Comment by tkdrg** [comment]
Yeah, this will invariably break playing on linux and playing on windows XP.

**Comment by PJB3005** [comment]
Playing on Linux is already going to be broken when GoonLights makes it, since colour matrices don't render. Though that might be fixed in the latest WINE version, but when I tried it BYOND stopped starting at *all* (might be it breaking the IE versions installed through winetricks, though, I haven't tried a fresh wineprefix)

**Comment by Bawhoppen** [comment]
>impling shitty goonlights is going to go through

**Comment by tkdrg** [comment]
@pjb3005 it "worked" for me with actual goon, they didn't render properly so I could see in the dark but they didn't crash or anything. either way, goonlights don't lock out linux/xp players out of a large chunk of the game

**Comment by neersighted** [comment]
First off, let's forget XP... As far as Linux goes, I run Linux myself and want to maintain compatibility. There is nothing in principle here that breaks Wine support, other than Wine being confined to old versions of IE because of WUSA being unsupported. This is being resolved in wine-staging...

As it is, I don't think Wine support should be a goal of this project. We should try to confine ourselves to sane technologies that work on Windows (IE9 is over 5 years old and is supported on Vista+), and let the Wine project worry about supporting standard Windows features. Unfortunately, BYOND is tied inexorably to Windows.

**Comment by tkdrg** [comment]
> This is being resolved in wine-staging...

That's true, but it isn't resolved yet. We don't need ES6, so I don't think we should lock out 2% of our players and incovenience another 30% by forcing it. But that's just my opinion.

**Comment by neersighted** [comment]
Okay fine I'll cave lets use hacks to support IE8...

**Comment by duncathan** [comment]
Neer has promised ie8 support
If he is lying we will sacrifice him to an ancient powerful god yet to be determined

**Comment by neersighted** [comment]
I'm not tasty... Don't eat me Nar-Nar...

**Pull request merged**
