### PR TITLE
Red and green energy swords have much less saturated light colors

### PR DESCRIPTION
**Pull request by ChangelingRain**
Old:

New:

### CODE REVIEW

**Comment by calzilla1** [comment]
Well, it IS a beam of pure light

**Comment by Supermichael777** [comment]
yes but most of the light is crystallized into a solid blade.

**Comment by Armhulen** [comment]
Eh, I don't really like the change.

**Comment by Cebasiz** [comment]
kinda like the brighter one better

**Comment by OtherDalfite** [comment]
I like it. First ones are colored way too strongly.

**Comment by RemieRichards** [comment]
brighter is better tbh.

**Comment by Robustin** [comment]
My bigger issue is how red and other primary colors are so much strong in vglighting.

I think the better solution is to make certain colors less "powerful" in their lighting effect.

Just make two colors lights one red and the other anything else and you'll see how red will dominate the other light.

**Comment by ChangelingRain** [comment]
The color's hex values matter a lot; the further two of its rgb values are from #FFFFFF the more saturated it is, the less overall bright it is, and the more effect it has on other lights.
So if you have #FF0000 and #00FF00 at the same power the red shouldn't overpower the green, but if the green is actually #99FF99 the red will overpower it more.

**Comment by optimumtact** [comment]
yall must be blind cause it's obviously better

**Pull request merged**
