### PR TITLE
Uplink Discount System

### PR DESCRIPTION
**Pull request by Incoming5643**
Every traitor uplink now will have up to three random items discounted. Which items that are discounted are different between uplinks (blame game mode code for this, will have to be fixed in Datum Antags).

Keep in mind that while there will always be three items discounted some of those items might be things that the traitor can't access due to game mode and thus it will APPEAR as if there are fewer discounts.

Any item that already implies a discount is barred from being put on sale as is the implant uplink, for obvious reasons. The balloon is also barred, because it's already far too good a value.

Discounts Odds:

25% off: ~57%
50% off: ~29%
75% off: ~14%

Note that for the three items any combination of these results is valid (so getting three 75% offs is possible, just extremely rare).

### CODE REVIEW

**Comment by kilog** [comment]
BUY THREE, GET NONE FREE!

**Comment by Anonus** [comment]
75% off holoparasites, just 3 tc for an army of terrifying healbots and like two ranged attackers.
Amusingly, still not the best choice as it'd be easy to just, like, fire down a hallway at your army of heal-o-trons.

**Comment by Iamgoofball** [comment]
Please make this 5 items.

**Comment by Incoming5643** [comment]
Goof the more items I add the more likely it is someones gonna get access to something <b>crazy</b>

**Comment by Iamgoofball** [comment]
And? It'll spice shit up.

**Comment by kilog** [comment]
I don't think you're at liberty to say what's ~spicy~ and what's not mister

**Comment by PKPenguin321** [comment]
:+1:
1 TC items should be excluded since you can't really make 1 any lower without making it free or use decimals

**Comment by Incoming5643** [comment]
They are

**Comment by PKPenguin321** [comment]
Oh haha I'm illiterate

**Comment by Zilenan91** [comment]
75% off revolver would be disgusting

**Comment by KazeEspada** [comment]
Its so random, and it benefits traitors, so YES.

**Comment by Fox-McCloud** [comment]
RNG random discounts doesn't come across as a good thing here, especially randomized between individual uplinks.

I could understand conditional discounts (ie: cheaper tools for stealing, cheaper lethals if you have a kill objective....lots of officers, or something like that), but just "lol, I can buy double energy sword and a revolver" because of RNG seems inherently bad to me.

RNG always makes for terrible game balance, long term.

**Comment by Incoming5643** [comment]
if it seems too much the % offs could be reduced pretty far. The "randomized between uplinks thing" IS bad, but can't be helped quite yet.

If this feels to spicey now I'll probably ressurect it at some point after datum antags

**Comment by Iamgoofball** [comment]
It should really be randomized globally.

**Comment by Lo6a4evskiy** [comment]
>75% off revolver would be disgusting, as would syndibombs.

Seriously, you should tone down the percentages there. Something like 20% off, 35% and 50%?

And why do the chances add up to 100%, if they are separate and all three can appear?

Actually it's the chance that I've got the biggest problem with.

Let's say we have 5 traitors in a round. Not unreasonable, right? The chance of at least one getting a 75% discount is 1 - ((1 - 0.14)^5) = ~0.53 or 53% or almost half of the rounds. The chance of at least one getting -50% is 82%.

I'd say if you have a steep discount, it should be pretty rare. Any single traitor who gets his hands on something ridiculously cheap can do a ton of harm (see cheap bombs or revolvers like people pointed out). Of course, a lot of items are garbage or are too cheap to get a serious discount, so may be someone should factor that in.

Also, it doesn't affect nuke ops' uplink, right?

**Comment by JJRcop** [comment]
I like the rare chance to get something ridiculously stupid.
:+1: in its current state

**Comment by Incoming5643** [comment]
there's balance considerations here that I need to look into.

There are ALWAYS discounts, it's not a rare thing, it's an always thing. What the discount IS varies, but its existance doesn't.

Even 25% off can be really good for large ticket price items (especially since yeah, it impacts nukes).

**Comment by Lo6a4evskiy** [comment]
Consider making it a fixed TC price reduction then instead of percentage based.

>it impacts nukes

I don't think it should. In the current form at least.

Consider the round where nukes steamroll the crew because they got a very lucky discount. Did this system really benefit the round in that case? Same thing with traitor murderboning with 5 revolvers. [May be this](https://www.youtube.com/watch?v=0V5eq4IQ6Go) wasn't a bad explanation of balancing RNG in games.

So yeah, my opinion is, change it to fixed TC reduction and don't make it a big one either. And may be remove it for nuke ops.

**Comment by JJRcop** [comment]
I understand, but what I mean by rare, is rare chance to get 3x 75% off on very expensive items. That would be ridiculously stupid. :)

**Comment by Lo6a4evskiy** [comment]
But even a single lucky 75% off can shift the balance heavily. Like all nuke ops having double swords in addition to a bunch of other equipment.

**Comment by Zilenan91** [comment]
Like 75% off maulers and the whole crew just dies

**Comment by Incoming5643** [comment]
yeah no this was just a single day project it's gonna get toned down into the ground before merging don't worry.

Sometimes you code something and you don't think about the repercussions until its in the PR.

And where we are.

**Comment by Zilenan91** [comment]
So what will you do with Ops. They have five uplinks normally, so they'd all compare what they get discounted then transfer all TCs to the one with the most OP shit discounted and then steamroll everyone with a ton of mechs, borgs, or whatever else. There's no real way to balance this without the discounts being much lower.

**Comment by Lo6a4evskiy** [comment]
Awesome :heart:

Oh and yeah. Nuke ops basically have the percentages for 5 traitors guaranteed and combined.

**Comment by Incoming5643** [comment]
yeah I'll keep it out of ops.

datum antags is gonna have to figure out another way around that issue but I'll cross that bridge when I get there.

**Comment by Supermichael777** [comment]
DANGER ZONE INTENSIFYS

**Comment by xxalpha** [comment]
This will just throw item cost balance out of the window.

**Comment by Incoming5643** [comment]
We can send stats to the database, but I'm not sure if we can do the reverse.

It's all years old erromagic to me.

**Comment by xxalpha** [comment]
Ask @MrStonedOne

**Comment by Steelpoint** [comment]
Don't go for what Counter Strike Source did in that it raised and lowered gun prices based on popularity, this resulted in situations like a Deagle costing $5000, a Mac10 costing $140 and armour being all but out of reach.

**Comment by Zilenan91** [comment]
Oh fuck I remember that holy shit. For months rifles and armor were hella expensive, so all you got every scrim was dudes spamming P90s and UMP-45s

**Comment by Incoming5643** [comment]
closed pending long hard look in balancing mirror

**Comment by xxalpha** [comment]
Don't compare SS13 to counter strike, please.

**Pull request closed without merging**
