### PR TITLE
Resprites Mi-Go to not be plagiarized from a CDDA tileset + adds special shiny variant of the Mi-Go

### PR DESCRIPTION
**Pull request by KingkumaArt**
A lot of the xenobiology mobs are really, _really_ crusty. The mi-go is, in my opinion one of the worst offenders (DMI file shown below), and even if it wasn't as old as it is - and it is very old, I think it predates this github - it's also just straight up stolen from a CDDA tileset. This pr fixes that.
Old mi-go:
image

New mi-go:
Go migo Go 

"But what about the shiny variant you added?" Well, let me introduce you to...

MigoH1
_**Hatsune Mi-go.**_

...I'll see myself out. 

In honesty, this PR started as solely a shitpost made in an hour of photoshopping a miku wig onto a mi-go, but ended up willing itself into quality.
## Why It's Good For The Game

Besides the spritework obviously having aged, having stolen/traced art ingame is not a good look. Below is the DMI of the mi-go, put along with a screenshot of the CDDA tileset. It is, admittedly, _slightly_ altered, but thats because the CDDA version wouldn't fit in a dmi's 16x16 tilesize, and so parts are just chopped off to make it work, and some coloring was changed.

a-migo

As for the mi-go/miku pun - if we have the 1 in 100 among us firelock, a 1 in 25 chance for a migo (a rare mob) to have an easter egg/pun seems fine. I like the tiny chance things like that in this game. 

## Changelog
:cl:
add: Shiny joke mi-go variant (not xenobio spawnable)
del: Removed unused mi-go static sprites
image: Resprited mi-gos to not use plagarized art from CDDA
image: Also allowed mi-gos to have directional facing instead of always facing east
/:cl:

### CODE REVIEW

**Comment by Donglesplonge** [comment]
peak PR simply because of the return of hatsune mi-go

**Comment by TheVekter** [comment]
Old sprite was peak soul but we get Hatsune Mi-Go with this so I guess it can stay

**Comment by moocowswag** [comment]
Funny bit of trivia, not only the migo sprite was ripped from cdda at the same, but also the way they existed.

Back then cdda migos spawned from orange nether portals....and we have (although rare) orange nether portals.

**Comment by moocowswag** [comment]
Also youre comparing newer cdda textures....older texturepacks used the brighter pink color pallete...and one of them looks identical.

From google search if you look really hard

image


image

**Comment by moocowswag** [comment]
After playing more cdda i found out that it was the chibi utilica tileset that we literally copy pasted migo from.

**Pull request merged**
