### PR TITLE
Moves GLOB.movement_keys into SSinput and adds movement direction badminry

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: ninjanomnom
admin: There are 3 new helpers in the secrets menu for messing with movement controls
/:cl:

It's possible with var edits but this makes it so you can replace all the movement directions at once with no intermediate step of only some directions being edited.

Also hey it's fun.

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]
Add one to normalize them

**Comment by ninjanomnom** [comment]
In order to add that I need to do a minor refactor to do it cleanly >:(

**Comment by Iamgoofball** [comment]
See, I'm going to :-1: this simply because it stands in the way of rebindable keys.

We know how pissy admins get when we fuck with their toys, and if we added rebindable keys we'd have to remove this feature to avoid screwing over people's keybind setups.

**Comment by deathride58** [comment]
It'd still be entirely plausible to keep this without getting in the way of rebindable keys.

**Comment by ninjanomnom** [comment]
Yeah this doesn't really stand in the way of that.

**Comment by kevinz000** [comment]
tbh if admins want to fuck up the game in such horrifying ways they should learn how to properly proccall/varedit instead of using a lazy button
laziness is shit.

**Comment by Iamgoofball** [comment]
Stop whining about sdql not getting used so much

**Comment by kevinz000** [comment]
@Iamgoofball varedit not sdql idiot

**Comment by ninjanomnom** [comment]
The problem with doing this via regular var edit is that you cant replace all the movement directions in an instant

**Comment by optimumtact** [comment]
I can't tel if this is ready or not

**Comment by ninjanomnom** [comment]
It is

**Pull request merged**
