### PR TITLE
Adds syndicate throwing knives

### PR DESCRIPTION
**Pull request by ghost**
They are a cheaper alternative to eswords, do more damage when thrown, but do less damage on straight attacking and >throw code basically balances them out. Their price and damage can be adjusted later anyway.

garb

(the gif is big, wait for it to load)

### CODE REVIEW

**Comment by Anonus** [comment]
Catch the knives, throw them back!

**Comment by paprka** [comment]
Precisely

**Comment by TZK13** [comment]
Having throw enabled is a pretty hard counter to these that pretty much everybody can do, no? Making it so that you can't catch these and maybe some other items too would be good.

**Comment by paprka** [comment]
guess what happens when you throw knives at people holding stuff

they can't catch them

**Comment by Cheridan** [comment]
We already have a syndicate throwing weapon, dumdum. Syndicate cards.

**Comment by TZK13** [comment]
Those only have throwforce 10 though while these have 40, they are a lot easier to use though considering you get a stack of 52 to pick out and throw from.

**Comment by Niknakflak** [comment]
Oh god, the codersprites.  Sprite change please.

**Comment by Cheridan** [comment]
I just don't see the point of adding a second type of throwing weapon to the uplink. I also think that in general the uplink is getting pretty cluttered, and that new additions should focus on providing interesting interactions instead of just new weapons. 

If these were mode-exclusive (Nuke/DA only?) or something then I could at least see the point more and it wouldn't add yet another thing to scroll through on the uplink.

**Comment by paprka** [comment]
@Niknakflak I didn't make these

**Pull request closed without merging**
