### PR TITLE
Staff of Honk Icon and Tweak

### PR DESCRIPTION
**Pull request by Robustin**
Is there anything I can't do?

Please, contain your exuberance: 
honkstaff

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Screenshots?

**Comment by KorPhaeron** [comment]
Also are you 100% sure the inhands for staves go in those dmis and not the gun specific inhand files?

**Comment by Robustin** [comment]
Yes

**Comment by optimumtact** [comment]
@Robustin well you can't make a pr with just one commit for starters :laughing:

**Comment by RemieRichards** [comment]
@Robustin learn to embed images.

**Comment by WJohn** [comment]
That's a pretty bad sprite. Looks like the door opening staff got its tip replaced with a banana sprite, not even a new one at that.

**Comment by KorPhaeron** [comment]
It's a silly sprite for a silly admin only item, and its on par with the other clown related magical items.

**Comment by KorPhaeron** [comment]
This touches common files so I dont want it held up forever, maybe one day someone will make a real sprite for it

**Comment by optimumtact** [comment]
GO ON HOLIDAY ALREADY

**Comment by KorPhaeron** [comment]
I am in an airport between flights, nothing better to do

**Pull request merged**
