### PR TITLE
Paradox bag sprites

### PR DESCRIPTION
**Pull request by itseasytosee**
project card link -> https://github.com/tgstation/tgstation/projects/6#card-2128039
## About The Pull Request
image
image
image
image

These blink but I don't know how to upload jifs.

## Changelog
:cl: itseasytosee
imageadd: new sprites for paradox bags
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
ITS PRONOUNCED GIF

**Comment by cacogen** [comment]
Can you show a screenshot of them in the game pls

**Comment by itseasytosee** [comment]
image
image

**Comment by cacogen** [comment]
Thanks

**Comment by TheBonded** [comment]
what if there was a set of orange + lighter blue (or replace the current blue with green) as a nod to portal? perhaps there's a 1% chance for every set of paradox bags to have this alternative sprite? just an idea

**Comment by itseasytosee** [comment]
References are neat and all, but we do have a literal portal gun in the game already that uses that color scheme.

**Review by Mothblocks — APPROVED** [review]
code is ok, icon boys please merge if the sprites are approved

**Review by Twaticus — CHANGES_REQUESTED** [review]
mob sprites are cool, i like the black with red/blue. but the normal icons are a bit confusing. kinda hard to tell its supposed to be a bag 😕

**Comment by itseasytosee** [comment]
Do you think something like a silver or gold buckle would work?

**Comment by itseasytosee** [comment]
I may or may have not deleted this repo on accident. (take two coming soon)

**Pull request closed without merging**
