### PR TITLE
Ian can now wear the ian shirt on his head

### PR DESCRIPTION
**Pull request by Incoming5643**
For that double ian goodness.

d10_icon
:police_car: Codersprites :police_car: 

:cl: incoming5643
rscadd: Ian can now wear his own worn t-shirt... just not on his torso.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
Max codersprites there. Neat idea otherwise.

**Comment by ike709** [comment]
@Niknakflak

**Comment by duncathan** [comment]
You should probably make it work on his body, too. This way, while funny and adorable, isn't exactly intuitive.

**Comment by Incoming5643** [comment]
but the shirt design would be under him, and thus worthless

**Comment by bear1ake** [comment]
XD :+1:

**Comment by Niknakflak** [comment]
I don't think that's how you wear shirts on your head, as someone who has a corgi in real life, I can assure you that they would A) not wear a shirt on their head like that and B) shake it off

**Comment by Bawhoppen** [comment]
@Niknakflak >dog wouldn't shake off sheets and countless other bulky hats

**Comment by bgobandit** [comment]
this is not exactly what I meant by ian wearing the ian shirt but ok

**Comment by Aranclanos** [comment]
fix the sprites

**Comment by Bawhoppen** [comment]
>fix

**Comment by Incoming5643** [comment]
impossible

**Pull request closed without merging**
