### PR TITLE
Removes joy and taco emoji

### PR DESCRIPTION
**Pull request by lzimann**
There's also thumbs up and down, but they are whatever. 
Joy is cancer and taco is just a reference to himself that must be purged.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
:joy:

**Comment by vcordie** [comment]
LEOZ HATES FUN

**Comment by Supermichael777** [comment]
unless he improves the quality of these sprites (note brains don't like math circles, use vertically symmetrical polygons) they gota go. http://www.dragonflycave.com/spriting-guide#outlining

**Comment by Bawhoppen** [comment]
no reason to remove go away

**Comment by dannno** [comment]
Stupid that a self-ref got in, tbh

**Comment by coiax** [comment]
Does the emoji code self populate based on the sprite file, or is there code that need to be changed to?

**Comment by lzimann** [comment]
By the sprite file.

**Comment by Tacolizard** [comment]
@supermichael777

The joy sprite was originally a lot better but I was forced to make it a downsized version of the joy mask. That's why it doesn't look perfect.

**Comment by Tacolizard** [comment]
Why do you hate fun. At least my taco emoji is merged on two other codebases now. Btw the emoji for taco is :forever:. Guess the reference

**Comment by sawrge** [comment]
Fall off your bike, Tacolizard! A thousand pox upon you!

**Comment by kevinz000** [comment]
take the ref out

**Comment by kevinz000** [comment]
@Tacolizard yeah and if this goes in i guess they'll be removed :^)

**Comment by Tacolizard** [comment]
Fine take out the totally coincidental taco emoji but keep the joy emoji. We have an item in the game that's a joy mask, that's what it's based off of because apparently all emojis should be based off of items already in spess

**Comment by Tacolizard** [comment]
If the sprite is bad, make a better one and pr it. Don't remove it

**Comment by Tacolizard** [comment]
:taco:

**Comment by jughu** [comment]
Why dont we have tacos as food item yet

**Comment by Cheridan** [comment]
all tacos are banned foreverentially

**Comment by optimumtact** [comment]
If something is already in have the good faith to accept it's gotten past you

👎 from me on this pr

**Comment by Bawhoppen** [comment]
@optimumtact that is an extremely surprising stance

**Comment by kevinz000** [comment]
^

**Comment by Bawhoppen** [comment]
the maintainers are out of control

**Comment by Tacolizard** [comment]
i know. since when was oranges /ourgoy/?

**Pull request merged**
