### PR TITLE
Revert "Atmos Grenades"

### PR DESCRIPTION
**Pull request by Supermichael777**
Reverts tgstation/tgstation#21014

These are the worst kind of shuttle greifing meme.

:cl:
del: The atmos grenades have been removed. if you want to burn down the shuttle use canisters or something but at least work at it.
/:cl:

### CODE REVIEW

**Comment by A-t48** [comment]
Nooooooooooooo.

**Comment by optimumtact** [comment]
How can this be griefing? they're literally an antag tool

**Comment by Iamgoofball** [comment]
WORD N A Z I CANNOT APPEAR IN THE CODEBASE

**Comment by optimumtact** [comment]
Also yes goof isn't joking, it's literally against our contributor guidelines, so please update your changelog

**Comment by Iamgoofball** [comment]
Also what oranges said it's not fucking griefing it's antags

**Comment by KorPhaeron** [comment]
Why did we give job tools to the uplink again anyway

**Comment by Iamgoofball** [comment]
@KorPhaeron what bothers me more is that people are referring to this as griefing

**Comment by PKPenguin321** [comment]
they're pretty dumb honestly

**Comment by lzimann** [comment]
you can do single tank valves that do the same as this, no point in having it honestly

**Comment by Supermichael777** [comment]
its being used exclusively for greif and wrecking other traitors rounds

**Comment by Supermichael777** [comment]
also we literaly had a !NOT! wolfinstine away mission

**Comment by MMMiracles** [comment]
@Supermichael777 the mission never got past being test-merged for player responses because cheridan hates nazis and i couldn't be assed to re-theme it to something else

**Comment by Supermichael777** [comment]
Removed nazi

**Comment by kevinz000** [comment]
@Supermichael777  Stop griefing the codebase :)

**Comment by Supermichael777** [comment]
i legit think these are plain bad

single purpose unimaginative mass murder

**Comment by A-t48** [comment]
These are at least more fun than a minibomb to the face.

**Comment by KorPhaeron** [comment]
They're cheaper and spread farther though

**Comment by Iamgoofball** [comment]
# STOP USING  THE WORD GRIEF TO DESCRIBE TRAITORS USING TRAITOR TOOLS

**Comment by kevinz000** [comment]
so do we ban all the traitors for ""griefing"" now? because that's the logic here.

**Comment by Dorsisdwarf** [comment]
I think what supermickey means here is that they serve no actual purpose for antags other than escape shuttle KILLEMALL meltdown.

**Comment by Supermichael777** [comment]
yeah 

everyone with gear to survive it has it anyway

**Comment by ExcessiveUseOfCobblestone** [comment]
👍 grenades that burn everything is not fun

**Comment by A-t48** [comment]
Still more survivable than a minibomb which FOREVER REMOVES THE FLOOR OF THE SHUTTLE AND WHICH YOU CAN'T SURVIVE WITH JUST HARDSUIT.

**Comment by A-t48** [comment]
Two minibombs are along the same cost as atmos grenades, and far more effective.

**Comment by ExcessiveUseOfCobblestone** [comment]
> a single explosion that opens a single area to space

>>> is more survivable than something that creates fire, which permadeletes items and tears down airlocks.

n-n-n-no i don't think that's correct.

**Comment by PKPenguin321** [comment]
Also n2o which knocks your ass out and Freon that keeps you from running

**Comment by Supermichael777** [comment]
A minibomb can be survived by buckeling up and puting on a breath mask.

this can be survived by having one of three items in the game(atmos fire-suits and hard-suit or a mech that hasn't been built in months.)

its just bad

**Comment by A-t48** [comment]
So nerf the plasma nade by not starting it off lit, maybe? The n2o bit doesn't matter as you generally will have breath mask on at that point in the round anyhow, and if minibomb happens, air is draining from the shuttle anyhow. If you're in shuttle, nowhere to run anyhow.

**Comment by A-t48** [comment]
Or give the shuttle a sprinkler system. :P

**Comment by ExcessiveUseOfCobblestone** [comment]
Or just remove the grenade because it's not a very fun feature?

**Comment by kevinz000** [comment]
if I want to fuck the shuttle up irrevocobaly I'd either maxcap it 6 times or take a bar of plasma from maint or even the 30 from engineering to the shuttle and apply welding torch, who the hell needs to spend TC?

**Comment by PKPenguin321** [comment]
also i'd like to just say that freon grenades are crashing the server

**Pull request merged**
