### PR TITLE
Removes stun from ebow.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: hm
fix: hm
/:cl:

this has been a long time coming

buffed the damage tho

### CODE REVIEW

**Comment by GunHog** [comment]
Enough with the memes. For someone who constantly barks about
# SLIPPERY SLOPE
, you seem to enjoy acting on it yourself.

**Comment by FantasticFwoosh** [comment]
Now the esword e-bow combo for stun & murder no longer works.

Colllectively as the bigger picture i like what i see, but now you need to nerf the curator's 100% disarm whip.

**Comment by XDTM** [comment]
i'm all for removing the ebow, but keeping it this weak for 14 tc is kind of pointless

**Comment by PKPenguin321** [comment]
This is stupid

**Comment by ShadowDeath6** [comment]
https://github.com/tgstation/tgstation/pull/24403#issuecomment-282203212

**Comment by banthebantz** [comment]
HAHAHAHAHAHHAHAHAHAHAHAHAHHAHAHAHAH 

no

**Comment by KorPhaeron** [comment]
So with this you can shoot once every 2 seconds, for 16 damage.

8 damage per second.

A toolbox can strike once every .8 seconds for 10 damage

12.5 damage per second.

Bad math friend

**Comment by Iamgoofball** [comment]
Toolbox isn't ranged infinite ammo

**Comment by banthebantz** [comment]
It's also something that didn't get dropped on my head as a baby.

**Pull request closed without merging**
