### PR TITLE
removes viral aggressive metabolism

### PR DESCRIPTION
**Pull request by imsxz**
:cl: imsxz
del: the viral aggressive metabolism symptom has been removed
/:cl:

not i ded, im the one abusing it.

shitty cancer overpowered symptom that makes for instakill viruses. the dead people can attest to this.

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
yeah, one time she did it as nonantag.

an admin couldnt cure the disease even though he cured all diseases 6+ times and he had to give everyone staffs of healing. It was extended, though.

**Comment by Shadowflame909** [comment]
lexia killed the entire server in 5 seconds with this. but this is not what needs to go, lexia with viro access does. The end 👍

**Comment by imsxz** [comment]
alternatively can we just remove viro altogether? it has been and always will be a source of pure awful

**Comment by Buggy123** [comment]
TBH its kinda funny when the entire station dies.

**Comment by Shadowflame909** [comment]
yeah viro's healing already got nerfed to shit. now we dont even play viro for healing anymore, only death. The next step is to just remove it entirely. and replace it with the clown museum.

**Comment by 81Denton** [comment]
>nerf viro healing
>"Viro is only used by assholes to kill everyone, can we nerf or remove that?"

🤔

**Comment by MimicFaux** [comment]
I'd suggest altering the symptom itself before outright removal if, and only if it's such a major problem. Maxcaps, are a good example of a 'problem' that was tweaked and altered until it found a home. It was a stupidly powerful in the hands of the few people who learned in the ins and outs. The same could be said of plasma flooding, or any other 'kill the station' tactic.

A few suggestions for curbing aggressive metabolism if it continues to be a problem would be to maybe increase the stat penalties so it's harder to make stealthy, easier to cure; or even regress through the stages faster. A virus that starts developed and then weakens over time absolutely fills an otherwise unfulfilled niche in virology.

**Comment by imsxz** [comment]
ease of curing doesnt really matter. when i go to vaccinate myself against the virus, i have the cure reagent in me before even infecting myself and still nearly die even with immediate medical attention. removing viral aggressive metabolism will not ruin antag virology, just put it more in line with stuff like fungal TB which is still very strong.

**Comment by ChangelingRain** [comment]
ah, virology...

**Comment by imsxz** [comment]
viros healing is still very strong but its just not as retarded OP as it used to be. it wasnt nerfed to shit, it was nerfed to sanity. @Shadowflame909 if you truly believe that viro healing isnt strong anymore than i gotta say you sound very spoiled by how ridiculous old virology was.

**Comment by Robustin** [comment]
Viro just needs to find that sweet spot between overly niche and demigod. 

I think part of it should involve making stats an even more crucial aspect of the virus like it was prior to the last nerf, but have symptoms carry a randomized range of stats so that there is some active research/critical thinking aspect of making diseases and it's not just like playing a slot machine with plasma coins.

I looked over healcode and I agree its still pretty strong. I think Viro should get back its low power basic healing symptoms though, I never saw an issue with those healing 2 per tick, it was abusing the high-end one for permanent fleshmending at 12/tick that was a problem. I like the idea of choosing between a general healing virus that just keeps everyone topped-off versus a more specialized combat-oriented ones that we have now with certain conditions attached. 

A decently done heal virus can still reach the fleshmend-tier if you meet its conditions.

As for this actual PR: It's pretty symptomatic (heh) of how people here react when powergamers open PR's. Instead of understanding that we're basically the canaries in the bullshit mines and refuse to believe us until we abuse the mechanic enough that enough IDED's support the change or until enough imitators catch on and make it obvious that there's a problem. 

When I made a similar virus last year we ended up with https://tgstation13.org/phpBB/viewtopic.php?f=10&t=13299 after a single round. If I had kept playing viro we would've seen aggressive metabolism removed months ago.

It's going to continue to be a problem and while its not an salvageable symptoms, its simply broken in its current state and there's no easy fix. You either have to nerf most negative symptoms so they can't kill you in a matter of seconds at Stage 5, or you have to somehow strike a balance where if you can get a modest amount of healing, you'll be cured.  Even then its not the best mechanic if its basically another medkit check. The whole point of viruses should be an emphasis on quarantine and curing, metabolism shits on that entire premise and just makes it an instant heal-check that will generally just kill everyone in a matter of seconds. 

Even if you strike a balance now it's just going to continue to fuck with balance and design space in the future, it might be interesting to have a Doomsday virus with a very slow progression but incredibly nasty Late-Stage symptoms - but aggressive metabolism means that can never happen. Therefore its best for viro if we just remove it and use the design space for something more interesting and fitting for a virus.

But of course this is just a wall of text to most people and the opinions of the games most experienced players carry less weight than a glib response with an edgy punchline.

**Comment by Robustin** [comment]
lol Lexia found something she couldn't kill with soap and a toolbox, so naturally she wants it gone

**Comment by Spaceinaba** [comment]
EMOJI YOUR OWN POST ONE MORE TIME MOTHERFUCKER I DARE YOU

**Comment by imsxz** [comment]
oh wow the virus you used in october 2017 is pretty much the same one i use now nice (autophag with thresholds met+aggressive metabolism)

**Comment by PKPenguin321** [comment]
Should be nerfed before full removal

**Comment by Nabski89** [comment]
It's cute for things like confusion or minor harmful effects to cure themselves after a time. It's not when a virus starts at stage five then they die.

If I had to recommend a real change it has massive amounts of stagespeed, but cures the virus after 30 seconds at stage five (starting at stage one like everything else does).

But yeah, chop it.

**Comment by Adanps** [comment]
In its current state aggressive metabolism is extremely strong and should probably cure itself faster or at least have nerfed stats as others have suggested. Now that symptoms can have extra effects, if the virus stats are high enough, it COULD be possible to make a doomsday virus with very restrictive stat requirements. 

Virus healing does need some sort of revision. It is certainly very strong if you are properly equipped, but unfortunately (or fortunately) very few people are going to bother drinking plasma, radium, and water.

**Comment by Shadowflame909** [comment]
I **donut** agree with removing this. This is a blow to the already memed healing virus's. If this get's removed, then wouldn't it only incline more people to use virology for killing virus's? There aren't a lot of symptoms that give you stage speed, and any healing symptoms usually try to nerf stage speed. TLDR: Removing stage speed symptoms would be a bigger blow to good Viro's then too bad Viro's.

**Comment by AlexTheSysop42** [comment]
>viro's
>virus's

no

**Comment by imsxz** [comment]
shadowflame you big dumb stupid idiot this wont ruin viro's ability to make kill viruses. it will just make them not guaranteed station cleaners 100% of the time regardless of cure availability. you can still have viruses that will kill if not cured within a few minutes, but wont be as ridiculous as current viro.

**Comment by imsxz** [comment]
and nerfing the kill symptoms rather than removing aggressive metabolism isn't good either because they SHOULD be able to kill when untreated, but it shouldnt be instant with little to no time to react.

**Comment by davethwave** [comment]
I'm making a new symptom in a pr soon so I'll edit the stats on it to replicate the viral aggressive metabolism symptom if this goes through.

**Comment by zeskorion** [comment]
you know, a simple nerf to transmission which makes this impossible to spread with maxed-out deathsymptoms is all this really needed, right?

**Pull request merged**
