### PR TITLE
 [Delta] Fixes Missing R&D Shutter Near Public Autolathe

### PR DESCRIPTION
**Pull request by JohnTheDonut**
##  **Fixes Missing R&D Shutter Near Public Autolathe On Deltastation**
Fixes a missing security shutter in Research and Development on Deltastation. This should allow the lockdown of R&D to be more secure as now all windows in R&D will be able to lockdown using the shutter control buttons located in R&D and RD office.

## **Images**
capture
_Red Box - Area where new shutter is placed._

## **Changelog**
:cl: Tofa01
Fix: [Delta] Fixes missing R&D shutter near public autolathe
/:cl:

### CODE REVIEW

**Comment by Arianya** [comment]
How will I spy on the ERPers now!

**Comment by GunHog** [comment]
I think you are looking for the Medbay!

**Comment by Arianya** [comment]
@Emilc4h Care to comment on what @GunHog has accused?

**Comment by Emilc4h** [comment]
SLANDER. LÜGENPRESSE. NO COMMENT.

**Pull request merged**
