### PR TITLE
Dominators require an open space, except it works this time

### PR DESCRIPTION
**Pull request by ChangelingRain**

### CODE REVIEW

**Comment by ChangelingRain** [comment]
grumble grumble kneejerk reverts

**Comment by XDTM** [comment]
20 seconds for every invalid second is a bit harsh, you could sabotage a dom by walling it and letting the timer reach the hours

**Comment by KorPhaeron** [comment]
No self merging is the only real rule we have please follow it

**Comment by ChangelingRain** [comment]
dom timers are in deciseconds, though

**Comment by Iamgoofball** [comment]
@KorPhaeron well i mean it does fix a major issue that was the cause of the speed revert

**Comment by KorPhaeron** [comment]
Yeah but it takes like 2 seconds to just ask someone else

**Pull request merged**
