### PR TITLE
Gives pride's hammer a new sprite

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

I'm very nostalgic about pride struck hammer, it really reminds me of the good old days. Unfortunately it's sprite does too, lets destroy the soul

The base shape was originally from Azlan, who gave me permission to mess around with it.

## Why It's Good For The Game

@Twaticus 

## Changelog
:cl:
imageadd: Updates pride hammer sprites!
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
(i'll quickly fix it)
image

**Comment by TemporalOroboros** [comment]
There are also floating white pixels in the inhands (specifically the leftmost one according to icondiffbot? It might be the south-facing one, but I don't know icons well enough to tell.

**Comment by tralezab** [comment]
ya that's just inhands nonsense like you guessed, don't worry

**Comment by tralezab** [comment]
I should also mention, I've switched it over to rewind which I didn't do in the old days when I should have, this makes it a LOT smaller

**Comment by Twaticus** [comment]
tailpin and uglymine-inactive are being deleted from items_and_weapons

**Comment by tralezab** [comment]
Believe me i know

**Comment by tmtmtl30** [comment]
>lets destroy the soul

>new image has 3/4ths perspective

don't listen to his lies

**Comment by tralezab** [comment]
okay no more icon troubles

**Review by Twaticus — APPROVED** [review]
coolio

**Pull request merged**
