### PR TITLE
Adds inhands for botanical belt

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About The Pull Request

Adds inhands for the botanical belt.

## Why It's Good For The Game

More inhands more money.
## Changelog
:cl: Swept
server: Added inhands for botanical belt
/:cl:

### CODE REVIEW

**Review by ShizCalev — APPROVED** [review]

**Review by Twaticus — CHANGES_REQUESTED** [review]
belt_lefthand.dmi - utility_ce got renamed on accident

change plant back to plantbelt

**Comment by SweptWasTaken** [comment]
> 
> 
> belt_lefthand.dmi - utility_ce got renamed on accident
> 
> change plant back to plantbelt

Fix it for me.

**Comment by Mothblocks** [comment]
i dont think theyre going to

**Comment by maxymax13** [comment]
> Fix it for me.

this is your pr 🤨

**Pull request closed without merging**
