### PR TITLE
Adds a pressure control system to cryotubes

### PR DESCRIPTION
**Pull request by RikuTheKiller**
## About The Pull Request

This PR already existed in the form of #71795, however oranges objected to it when someone acknowledged that what the PR did was possible via atmos equipment... while it wasn't.

You cannot reasonably get enough pressure to do what this PR does without quite literally setting up a 5 layer pump system with half the round's supply of gas (I'm talking about the big chamber here...) shoved into the cryotubes and I'm not sure what sort of fantasy world you live in if you think that's going to happen.

When I asked about this in the discord a while ago during the feature freeze, I was told to open it sometime after the freeze is over. So, here it is.
## Why It's Good For The Game

Oh, right, this also affects adding custom mixes to cryo. It's much easier to manage custom mixes when you have control over the release pressure, similarly to internals tanks.

Upgraded cryotube setups shouldn't become death traps. It also fixes an unconsidered side-effect of making cryotubes need gas.

I'll clarify. Essentially, due to low temperatures when upgrading the thermomachine (which is the intuitive way of making cryo more effective) the pressure of the anesthetic mix becomes so low that it can no longer supply the inhabitant with enough N2O to keep them sleeping nor enough O2 to keep them breathing. This puts them into a pseudo death-state where all they can do is ghost or be fucked forever.
## Changelog
:cl:
add: Cryotubes now have a pressure control system.
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
I'd like to note that cryoxadone works at over 94.6% of its maximum efficiency when cooled to 73.15K, which tier 1 thermomachines reach.

**Comment by ZephyrTFA** [comment]
Oranges didn't close it, it was closed because no maintainers merged it. It went stale.

**Comment by RikuTheKiller** [comment]
> I'd like to note that cryoxadone works at over 94.6% of its maximum efficiency when cooled to 73.15K, which tier 1 thermomachines reach.

Nice to know, I might make a PR to change that later since it seems kind of dumb.

**Comment by RikuTheKiller** [comment]
> Oranges didn't close it, it was closed because no maintainers merged it. It went stale.

Thanks for the correction, though I still feel as if oranges is the one that sort of introduced the dumb reasoning that probably led to it's closure.

**Comment by optimumtact** [comment]
>You cannot reasonably get enough pressure to do what this PR does without quite literally setting up a 5 layer pump system with half the round's supply of gas (I'm talking about the big chamber here...) shoved into the cryotubes and I'm not sure what sort of fantasy world you live in if you think that's going to happen.

proof?

**Comment by Pickle-Coding** [comment]
After some experimenting, I have found that you can achieve the necessary pressure while maintaining both thermomachines and the CO2 filter by shedding off some unnecessary pipes and pumping the anesthetic mixtures into the pipes.

Very simple modification without any additional gas needed can allow the pressure required necessary for both oxygen and nitrous oxide to have their necessary effects, even at 2.7 Kelvin.

I will point out that the cryo cell is supposed to have a volume of 1.25kL, but it can't access airs[1] on initialize so it never sets the volume, leaving it at the default 200L. I have tested it on both 200L cryo and 1.25kL cryo. Both work at 2.7K with some basic modifications.

**Comment by optimumtact** [comment]
can you take a picture of the setup? I'm trying to decide how much effort it is as a reward vs just having it built in to the machines.

**Comment by GuillaumePrata** [comment]
The setup becomes even easier if you swap the O2 for Pluoxium as it is 1/4 of the requirements pressure wise to O2 and another option is to add anesthetic chems to the chem mix, but only Super Melatonin is a safe one (and boosts healing values) as far as I'm aware.

**Comment by Pickle-Coding** [comment]
> can you take a picture of the setup? I'm trying to decide how much effort it is as a reward vs just having it built in to the machines.
> 
> 
> 
> even though OP is continuously rude.

Can't take a picture at the moment. It's 2 connector ports and a pump that leads to the pipenet, with a pipe that connects the connector ports to the pump. The canisters get moved to the newly placed connector ports. The pump gets turned on.

There's enough leeway in pressure that shedding off pipes isn't necessary, as long as there are less than 24 pipes in the pipenet.

**Comment by SyncIt21** [comment]
> > can you take a picture of the setup? I'm trying to decide how much effort it is as a reward vs just having it built in to the machines.
> > even though OP is continuously rude.
> 
> Can't take a picture at the moment. It's 2 connector ports and a pump that leads to the pipenet, with a pipe that connects the connector ports to the pump. The canisters get moved to the newly placed connector ports. The pump gets turned on.
> 
> There's enough leeway in pressure that shedding off pipes isn't necessary, as long as there are less than 24 pipes in the pipenet.

Can you screen record the whole setup?

**Comment by RikuTheKiller** [comment]
> can you take a picture of the setup? I'm trying to decide how much effort it is as a reward vs just having it built in to the machines.
> 
> even though OP is continuously rude.

No no, I just had the presumption you couldn't do it due to my experiences with shoving half the roundstart gas chamber into a single canister... I just couldn't imagine that working with atmos machinery.

**Comment by RikuTheKiller** [comment]
> The setup becomes even easier if you swap the O2 for Pluoxium as it is 1/4 of the requirements pressure wise to O2 and another option is to add anesthetic chems to the chem mix, but only Super Melatonin is a safe one (and boosts healing values) as far as I'm aware.

I have not seen pluoxium in-game. Ever. If you think that's reasonably going to happen to a cryo setup, you're damn wrong.

**Comment by RikuTheKiller** [comment]
> The setup becomes even easier if you swap the O2 for Pluoxium as it is 1/4 of the requirements pressure wise to O2 and another option is to add anesthetic chems to the chem mix, but only Super Melatonin is a safe one (and boosts healing values) as far as I'm aware.

Adding sleep chems works I think but they metabolize very slowly and would probably leave the inhabitant asleep for the next 2 milennia, especially if the cryo tube is upgraded to multiply chems more aggressively.

**Comment by RikuTheKiller** [comment]
> Can't take a picture at the moment. It's 2 connector ports and a pump that leads to the pipenet, with a pipe that connects the connector ports to the pump. The canisters get moved to the newly placed connector ports. The pump gets turned on.
> 
> There's enough leeway in pressure that shedding off pipes isn't necessary, as long as there are less than 24 pipes in the pipenet.

Also doesn't this setup completely neglect CO2 removal?

**Comment by RikuTheKiller** [comment]
> even though OP is continuously rude.

Also looking back I can tell why you think that, sorry.

**Comment by RikuTheKiller** [comment]
> can you take a picture of the setup? I'm trying to decide how much effort it is as a reward vs just having it built in to the machines.

And yeah I'd like to see your gigachad atmos setup, I'm honestly curious as to how you solved it.

**Comment by Mothblocks** [comment]
Actually, to clarify, does "low temperatures" here mean after I upgrade, that only once I lower temp does it become ineffective? If so then I can ease up more on requiring atmos infrastructure for this, but it still feels unintuitive in that we should probably directly tell you if we're not going to just fix it for you

**Comment by YakumoChen** [comment]
It sounds like a lot of these issues could be solved with simple mapping changes

In an ideal world cyro would have some sort of safety to prevent unintentional GBJ but its ss13 baby

**Comment by DustanHache** [comment]
> The setup becomes even easier if you swap the O2 for Pluoxium as it is 1/4 of the requirements pressure wise to O2 and another option is to add anesthetic chems to the chem mix, but only Super Melatonin is a safe one (and boosts healing values) as far as I'm aware.

if you’re gonna bring up plutoxium, what about healium?

**Comment by RikuTheKiller** [comment]
So what's the status for this PR getting merged or not?

**Comment by GuillaumePrata** [comment]
> if you’re gonna bring up plutoxium, what about healium?

Healium was changed to be the end game of Cryo ever since the changes in #65513
If you can get it, it runs cryo by itself without even needing O2 as it is an anesthetic that outheals the suffocation damage and kicks people out. (In my limited experience, I should retest it to be sure...)

Now Pluox was designed for the entry level of Atmos-Cryo cooperation on #69320 and brings something unique to Cryo, organ healing. Doctors should really ask more for it.

**Comment by RikuTheKiller** [comment]
> > if you’re gonna bring up plutoxium, what about healium?
> 
> Healium was changed to be the end game of Cryo ever since the changes in #65513 If you can get it, it runs cryo by itself without even needing O2 as it is an anesthetic that outheals the suffocation damage and kicks people out. (In my limited experience, I should retest it to be sure...)
> 
> Now Pluox was designed for the entry level of Atmos-Cryo cooperation on #69320 and brings something unique to Cryo, organ healing. Doctors should really ask more for it.

Very nice. This PR happens to help with all custom mixes even if it wasn't the original intent.

**Comment by ZephyrTFA** [comment]
I'm sorry to say that no one appears to be interested in this PR, get approval from a maintainer and they can reopen this

**Pull request closed without merging**
