### PR TITLE
Fixes nitryl gas not applying its effects.

### LINKED ISSUE #38877: Nitryl Gas not applying effects
https://github.com/tgstation/tgstation/blob/e10535d3ad3bfefd651bdea3100b8f149f4faca1/code/modules/surgery/organs/lungs.dm#L270

This is probably the issue, adding the reagent nitryl_gas instead of just nitryl.

https://github.com/tgstation/tgstation/blob/f0bff6a2d6c6a502a0e41db6efc984f25eadf0a4/code/modules/reagents/chemistry/reagents/other_reagents.dm#L1283

And this reagent will give the proper effects.

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: Frozenguy5
fix: Fixes nitryl gas not applying its effects.
/:cl:

tsk tsk @nicbn 
fun fact this was a bug for 8 months.
Fixes #38877

### CODE REVIEW

**Comment by praisenarsie** [comment]
@cyclowns gets stomped on

**Comment by nicbn** [comment]
oof

**Comment by Iamgoofball** [comment]
how do you set that up???

**Comment by Cyberboss** [comment]
Check pinned messages in `#coding-general`

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
