### PR TITLE
Remove armor from plasticflaps

### LINKED ISSUE #67863: TramStation Disposal'd Borgs can get "softlocked" in cargo behind plastic flaps
## Round ID:
[185156](https://scrubby.melonmesa.com/round/185156)

## Testmerges:
N/A

## Reproduction:
Screenshot_1

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

Fixes #67863

Plastic flaps had insane armor for some reason and this was landlocking borgs if they got trapped behind one.  My changes remove all armor from plastic flaps so this doesn't happen.

## Why It's Good For The Game

Plastic flaps shouldn't have god mode.

## Changelog

:cl:
fix: Fix borgs not being able to escape plastic flaps.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this is a massive balance change to area penetrability, but we also made flaps not matter because lmao rest movement

**Comment by timothymtorres** [comment]
> this is a massive balance change to area penetrability

Regular humans can bypass plastic flaps in less than a second.

> (yes I know all you need currently is to crawl or a wrench+screwdriver)

A grille or table is a _stronger_ deterrent than plastic flaps.  

My changes affect borgs and not human gameplay.  Whoever added armor to plastic flaps didn't even bother doing it correctly since they clearly just c/p'd code. (hint hint, BIO armor does nothing)

**Comment by BlueMemesauce** [comment]
TG coders explaining why one of the most easily bypassed  structures which is mostly just intended for utility/decoration needs to have insanely high armor and be impossible to destroy


https://user-images.githubusercontent.com/47338680/174789263-89ba1f8f-7a1c-4e22-ae89-b9f0865a2fb2.mp4

**Comment by Iamgoofball** [comment]
@BlueMemesauce before your time, plastic flaps *were* nigh impassable beasts only defeatable by mulebots

**Comment by san7890** [comment]
It just feels pretty silly to have such overpowered objects be present to make up the walls for stuff like... the science break room, since we don't really have any "low powered" alternative to plastic flaps that function in the same way as plastic flaps. It's just weird for relative security- and I know that we want to sorta clear out just how strong relative security is (especially owing to the fact that people won't stop wanting to discuss a transition from reinforced windows to normal windows with me).

**Comment by Palpetinus** [comment]
Oh, the coder does not want plastic flaps to become penetrable?
Well.. I feel sorry for the borgs I will now griff as antag just so they come here to complain. Nothing personnell, coder.....

**Pull request closed without merging**
