### PR TITLE
Fixes science scaling to decrease materials rather than increase....

### PR DESCRIPTION
**Pull request by silicons**
heh heh?
:cl:
rscadd: Oh hey guys, RND shows correct material values now, don't hurt me!
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
Put the 🆑 in the bag and nobody gets hurt

**Comment by AlexTheSysop42** [comment]
did better manips increase costs or something?

**Comment by ExcessiveUseOfCobblestone** [comment]
should have lowered t4 parts in that case.

**Comment by newfren** [comment]
Can this shit get merged already please this the most annoying nonsense

**Review by DaxDupont — APPROVED** [review]

**Pull request merged**
