### PR TITLE
Removes some obselete attackby() code [Removes attackby crafting]

### LINKED ISSUE #14892: You can make two flamethrowers from one tool
image
If you're click it quick enough you can make two throwers from one tool with two rods. Not too gamebreaking but eh, I like my headpats.

### PR DESCRIPTION
**Pull request by MrPerson**
Duplicate of #17876 see there for comments.

Code by Bawhoppen all rights reserved.

Fixes #14892

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Failed checks

**Comment by xxalpha** [comment]
:put_litter_in_its_place:

**Comment by PKPenguin321** [comment]
Literally why?

**Comment by Wyzack** [comment]
If Baw saw fit to rescind it then why would you put it back up?

**Comment by pudl** [comment]
lol failed checks

**Comment by Cheridan** [comment]
MrPerson make sure to fix #14892 as well if you catch my drift

**Comment by Cheridan** [comment]
whew those "close and comment" and "comment" buttons sure are right next to each other

**Comment by PKPenguin321** [comment]
it's a sign that this pr needs to be closed

**Comment by Zilenan91** [comment]
It really does. Slapping the parts together is just a better system.

**Comment by Cheridan** [comment]
its literally not

**Comment by Iamgoofball** [comment]
@Zilenan91 prove it

**Comment by Zilenan91** [comment]
Because I have to sift through laggy as fucking balls menus that always scroll back up to the top for things at THE BOTTOM OF THE FUCKING MENU SO I HAVE TO SCROLL DOWN AND FIND THE SAME RECIPE AND I HAVE TO GET ALL THE INGREDIENTS AND I HAOV AINOPAEUNFOUSNDIPVAUNFAP CUAND UINSPODUFNFASDV  osd nvapound PUVNPAIUNPIAEU NAPIOEUWNVAI PURN SIVUNIOU ANVPIUSFN FIOAUSDNVADKJ NAKLJFSLKRJNA KNDGJ SFJ AL ;KNSL;FJN;FKG SKKM;lm

Slapping makes sense and it's easier for someone to wrap their brain around rather than looking for a tiny as fuck button in the bottom of the screen that literally nobody will E V E R fucking notice unless they've been specifically told it's there. Like why would you ever look down there, there's 0 reason to ever change what part of the body you're targeting unless you have a really high brute weapon to dismember people, and even then you just have it on the same limb always so.

**Comment by Iamgoofball** [comment]
>Because I have to sift through laggy as fucking balls menus that always scroll back up to the top for things at THE BOTTOM OF THE FUCKING MENU SO I HAVE TO SCROLL DOWN AND FIND THE SAME RECIPE

this doesn't apply with remie's filters and the tgui functionality

> AND I HAVE TO GET ALL THE INGREDIENTS

you have to do that right now, whats different?

>Slapping makes sense

What makes it make sense over a crafting menu?

>and it's easier for someone to wrap their brain around

Can you get me some statistical data proving this?

>rather than looking for a tiny as fuck button in the bottom of the screen that literally nobody will E V E R fucking notice unless they've been specifically told it's there.

You're right, let's make the button bigger.

>Like why would you ever look down there, there's 0 reason to ever change what part of the body you're targeting

1. It's next to the intents wheel, not the limb changer. What are you on about?
2. If some nerd is wearing a helmet and no armor I'd target the chest tbh

**Comment by Iamgoofball** [comment]
>I would literally have had no idea how to craft anymore if I wasn't specifically told about the crafting button in the changelog.

Thats why we have the changelog

As a new player, can you say without a doubt that you would of been able to craft a stun prod (and know they exist) with the old method, without either

1. looking it up on the wiki
2. being shown how by another player

**Comment by Zilenan91** [comment]
>players teaching other players how to do things is something we don't want to encourage
Why

Also yeah I learned stunprods from other people. I expect everyone who slap crafts to learn it from other players, this is organic and it's overall a nice, if rare interaction.

**Comment by Iamgoofball** [comment]
And how do you suppose those people learned how to make stun prods?

**Comment by Zilenan91** [comment]
Probably not and that's fine. Just ask someone, that's good game design. It gets players to interact with each other and help each other out.

**Comment by PKPenguin321** [comment]
Hey I think that guy is up to something he's got a wire rod hey why is he breaking that window

VS

Oh hey that dude stood still for a few seconds and grew a spear from nowhere okay

Also WE ARE LITERALLY ABLE TO HAVE BOTH, it's absolutely petty to remove either when there is absolutely no reason to

**Comment by Shadowlight213** [comment]
I get the whole thing of "terrible code"
But most players I've seen avoid menucrafting unless it's absolutely necessary.
I get the seperation meme and coders not really caring about what players like, but I think we should get some feedback from the server before we just remove something most players seem to prefer that isn't unbalanced or anything.

**Comment by CosmicScientist** [comment]
:+1: for not requiring a wiki.
:-1: for item bloat.

**Comment by CosmicScientist** [comment]
I think I'll put down something simple.
:+1: for not needing a wiki to find out if something exists.
:+1: for a standardised interface that (I assume) is easy to add new recipes to.

:question:
- Why add one feature and remove another in the same PR?
- Whilst having atomic changes isn't necessary, at least we'd have stunprods added to the standardised list.

:question:
- Why is the title misleading?
- We still have attackby() crafting elsewhere and part of cooking is built upon it (unless I'm incorrect, I've never seen or touched that code).
- The obsolescence only exists because of this PR.

:-1: for replacing a white box system with a black box system. Or to explain, I enjoy crafting to be involved rather than a collect all inputs an await for outputs, not only do I find it more rewarding, when done right nothing feels arbitrary and wait time is derived from physical crafting.
:-1: for increasing item bloat in the standardised interface that _is not_ guaranteed to get better.


I think I'll add something that's more of a naive summary.
Whilst I couldn't give a flying fig if this goes either way, could we at least fix the stupid parts of this? Fix your title, make another PR to separate the changes, start fishing in the forums for more feedback and ideas coders, my poor wittle heart can't take it when a fair number of admins don't like changes when they're supposed to be some of the most intimate with the game itself (not talking about this PR alone). Oh and my poor wittle heart can't take it when a forum post somehow explains a PR better than the PR itself. The angry nature of said posts tend to be justified by that too.

**Comment by pudl** [comment]
i wouldnt have a problem with this if Remie would make a not shitty interface for personal crafting instead of the bs that tg uses right now

**Comment by PKPenguin321** [comment]
>👍 for not needing a wiki to find out if something exists.
>👍 for a standardised interface that (I assume) is easy to add new recipes to.

We already have this. We have slap crafting and UI crafting already. We get all the benefits already. Removing slap crafting does not somehow give more benefits.

**Comment by pudl** [comment]
tbh lol just lol at a codebase that manages to be so uptight on their code standard that they perform self destructive and alienating decisions in an effort to appear better than everyone else

**Comment by CosmicScientist** [comment]
@PKPenguin321 
>:-1: for replacing a white box system with a black box system. Or to explain, I enjoy crafting to be involved rather than a collect all inputs and await for outputs, not only do I find it more rewarding, when done right nothing feels arbitrary and wait time is derived from physical crafting.

If the above doesn't tell you what I think about removing slap crafting then how about this. Those positives were for putting the stun prod in menu crafting.

**Comment by pudl** [comment]
close this meme pr

**Comment by Zilenan91** [comment]
It also bears mentioning that the guy removing slap crafting is also the same guy who has tried to flat out remove spears and stunprods numerous times before. Could be Person just wants to make these things less accessible for people.

**Comment by pudl** [comment]
ok that just borders on startoad level of coderbus conspiracy

**Comment by Incomptinence** [comment]
STAY STRONG! 

SLAY SLAP CRAFTING!

**Comment by Dorsisdwarf** [comment]
Careful not to drown in that pudl of tears.

**Comment by lzimann** [comment]
can we just close this pr before someone stupid actually merges it

**Comment by pudl** [comment]
@KorPhaeron Save us please

**Comment by Dorsisdwarf** [comment]
Where did the Controversial tag go.

**Comment by MrPerson** [comment]
There we are, flamethrower slapcrafting and related code is gone too.

**Comment by pudl** [comment]
OH MY GOOOOOOOOOOOOD

**Comment by Supermichael777** [comment]
think of the poor tableless ashwalkers

**Comment by RemieRichards** [comment]
@Supermichael777 realise that we haven't needed tables to craft for quite some time now.

**Comment by lzimann** [comment]
12 :-1: to 5 :+1:

just close this already

**Comment by Iamgoofball** [comment]
@lzimann i dont think you understand how things work around here

**Comment by lzimann** [comment]
oh i do, stupid shit gets merged all the time, that's pretty straight foward

**Comment by Iamgoofball** [comment]
you're clinging to archaic systems "because thats how it has always been"

**Comment by xxalpha** [comment]
Don't forget to count the confused emoji and the party emoji.

**Comment by Iamgoofball** [comment]
if you feel that you literally can't play the game because you can't slap together a flamethrower in the same way you did before

then feel free to leave to another server

**Comment by xxalpha** [comment]
You can play the game without a lot of shit goof, including goofchem and loading bars.

**Comment by PKPenguin321** [comment]
Remove construction. It's just a bunch of hacky attack_bys! Make grille deconstruction use a UI! Reeeeeeeeeeeeeeese

**Comment by Iamgoofball** [comment]
@xxalpha exactly

ps. you're still salty about one of the biggest QoL changes in the last 2 years? lol

@PKPenguin321 it really is
we need to standardize it

**Comment by pudl** [comment]
Progress bars are cancer

**Comment by Iamgoofball** [comment]
@pudl i understand you have a boner for terminal windows and technology dating back to the unix epoch, but it's time to let it go and embrace modern technological advances

**Comment by PKPenguin321** [comment]
Crafting UI feels more like a step backwards rather than forwards though

**Comment by lzimann** [comment]
maybe we should remove goof instead

**Comment by Iamgoofball** [comment]
@PKPenguin321 go find a modern game using a crafting system that does not have a crafting UI where you craft something after having all the resources for it

**Comment by xxalpha** [comment]
ironsights when

**Comment by Iamgoofball** [comment]
@xxalpha you're an idiot

**Comment by Cheridan** [comment]
We have to rip the band aid on this. If the actual crafting system has issues then we can address them, just as we have in the past via improvements like adding the full recipe list, porting it to TGUI, and removing the table requirements. The more that people can avoid interacting with the system the less they'll get used to it.

**Comment by pudl** [comment]
God is dead and cheridan killed him

**Pull request merged**
