### PR TITLE
Fireball now requires robes.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
See title

## Why It's Good For The Game
Fireball is a loud spell. It's Fireball. You wanna be loud, you gotta wear the robes, that's how Wizard works.
## Changelog
:cl:
balance: Fireball now requires robes.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
For reference, goof was not even aware that Fireball was a robeless spell until <10 minutes ago.

**Comment by Iamgoofball** [comment]
It didn't used to be robeless.

**Comment by ATH1909** [comment]
Also note that Fireball becoming robeless will kill off (the viability of) most golem wizard builds, as well as nightmare destruction apprentices.

**Comment by ATH1909** [comment]
This also affects the viability of mindswap wizard builds.

**Comment by ATH1909** [comment]
Goof has ALSO forgotten to account for the existence of Fireball spellbooks, which exist as both lavaland loot and as possible drops from Summon Magic.

**Comment by brotherbeyondd** [comment]
silly goof

**Comment by optimumtact** [comment]
holy shit athath if you post any more people might think you care or something LMAO

**Comment by CRITAWAKETS** [comment]
> It didn't used to be robeless.

always has been

**Comment by OverlyGeneric** [comment]
May I suggest moving the "thrown lightning" spell to the robeless category? It is comparatively weaker than most spells in the robed section and a quieter spell suited for "stealth" wizards.

**Comment by ATH1909** [comment]
> May I suggest moving the "thrown lightning" spell to the robeless category? It is comparatively weaker than most spells in the robed section and a quieter spell suited for "stealth" wizards.

it's lowkey pretty bonkers for its price, it just has the critical weakness of requiring you to not be stunned/staminacritted/cuffed to cast it.

**Comment by wesoda25** [comment]
I can't think of an argument against

**Comment by kopoba** [comment]
This "Why It's Good For The Game" is just poof you can say that about any spell. And i don't think fireball require robe.

**Comment by ATH1909** [comment]
> I can't think of an argument against

I've given like 5.

**Comment by wesoda25** [comment]
Only thing you said which matters is that this will fuck over spell books, but we could fix that by having it give a robeless variant of the spell. With someone as infamous as you for looking for the most bullshit strategies and combos in the game, I’m not exactly convinced by the argument that this phases out a few wizard builds.

**Comment by Iamgoofball** [comment]
EMP would be a good robeless wizard spell

**Comment by Shadowflame909** [comment]
I thought fireballs whole gimmick was that it tends to self implode on the user. that's why it's so cheap and easy to use. 

It's got RNG code

**Comment by 81Denton** [comment]
What athath said

**Pull request closed without merging**
