### PR TITLE
Mounted chainsaw inhands

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
chainsaw

It's not beautiful but it's better than having the two handed stuff I think

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
vroom vroom

**Comment by Jordie0608** [comment]
Pics?

**Comment by Zilenan91** [comment]
Pic would be nice.

**Comment by PKPenguin321** [comment]
As the maker of mounted chainsaws, :+1:

**Comment by duncathan** [comment]
@KorPhaeron fix conflicts

**Comment by duncathan** [comment]
@KorPhaeron fix conflicts and then ping someone right away so that this can be merged; I want it so bad ;-;

**Comment by KorPhaeron** [comment]
@duncathan 

All my PRs have been sitting half finished cause Fallout I'll get around to it Soon(TM)

**Comment by PKPenguin321** [comment]
@KorPhaeron pls

**Comment by PKPenguin321** [comment]
@KorPhaeron  **P L S**

**Comment by KorPhaeron** [comment]
@PKPenguin321 

EVENTUALLY. Was thinking about doing onback stuff first as well.

Or you could steal em and make a PR whichever

**Comment by PKPenguin321** [comment]
Okay, I'm probably gonna steal these and make my own PR, but before I do I need to know if they actually need their own sprite in weapons.dmi. It's literally identical to chainsaw_on, can't we just use that for the icon_state then set item_state to mounted_chainsaw for the inhands?

**Comment by KorPhaeron** [comment]
Oh yeah probably

**Pull request closed without merging**
