### PR TITLE
Prevents energy weapons from being sharpened

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl: Cyberboss
tweak: You can no longer sharpen energy weapons
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Should make it slice the whetstone in half tbh fam

**Comment by RandomMarine** [comment]
But then you have two whetstone.

Whetstone win every time.

**Comment by Nabski89** [comment]
does that mean lines 17-18-19 are no longer needed in, since it calls out about sharpening eswords there?

**Comment by PKPenguin321** [comment]
It mentions eswords specifically, but is there as an intended catch all balance thing so nothing can exceed 30 force with this

**Comment by Nabski89** [comment]
Oh whoops. I misread and thought that it was making sure things always did more damage when thrown than sharpened.

**Pull request merged**
