### PR TITLE
Adds station badges to title screen

### PR DESCRIPTION
**Pull request by Cyberboss**
https://tgstation13.org/phpBB/viewtopic.php?f=11&t=11763

image

- [ ] Get the rest of the images from @nfreader

### CODE REVIEW

**Comment by Niknakflak** [comment]
eh 

sure why not but eh

**Comment by PraiseRatvar** [comment]
perhaps it should be closer to the corner?

**Comment by Tacolizard** [comment]
uh, cool idea but I'm not sure I like the presentation.

**Comment by Tacolizard** [comment]
@PraiseRatvar it's probably in the corner, just his window is too wide.

**Comment by optimumtact** [comment]
I'll revert this if the meta being the gold standard is left in reeeeeeeee, box is the gold standard

**Comment by Armhulen** [comment]
the badges are just ugly enough to make me wanna die

**Comment by WJohn** [comment]
These really don't fit with the quality of the background provided.

Maybe we can get some proper art done for these badges, but IDK.

**Comment by optimumtact** [comment]
that there title screen is /tg/ CULTURE WJOHN

**Comment by RemieRichards** [comment]
@optimumtact yes, which is why he wants proper BADGE art to go with them.
(you misinterpreted what he meant)

**Comment by optimumtact** [comment]
so I did, thanks remie

**Comment by dannno** [comment]
I don't think they fit. The placement is odd, they look out of place.

**Comment by Steelpoint** [comment]
Place it in the status taskbar or somewhere else.

**Comment by Iamgoofball** [comment]
make it an svg and embed in the chat box

**Comment by Shadowlight213** [comment]
Yeah, it looks really wierd and out of place

**Comment by nfreader** [comment]
This is... not what I had in mind. It should be like TF2’s loading screen. Strip that /tg/station 13 Out of the title graphic and added it as a banner to the top of the splash screen, and then the badge in the bottom right with something like “You’re on your way to [Box patch]” or something like that.

**Pull request closed without merging**
