### PR TITLE
Cyborg damage slowdown and borg stun rebalance

### PR DESCRIPTION
**Pull request by Ebb-Real**
## About The Pull Request

Borg are very powerful, immune to space, starts with a full set of tools for their job, can't take damage from fists, don't suffer wounds or bleed out, are immune to conventional methods of getting stunned or slowed down, are immune to chems, can repair themselves if they have a welder, have all access, can control machines and doors remotely, become unable to fight when they reach 150 damage unlike humans at around 100, they can still run at full speed after having all their modules broken at 150 damage, can be mass produced at robo and importantly for this PR suffer no damage slowdown.

In combat movement speed means a lot, its easier to hit slowed opponents and if you are faster than your opponent they won't be able to can't escape from combat. Human have damage slowdown and are affected automatically in terms of movement the more damaged they get. Borg's movement speed is not affected by damage currently. This means that in any fight where the opponent to a borg dosen't have a flash, EMP or falshbang the borg will almost always have the advantage in a fight. This combined with all their other bonuses make them extremely annoying to fight without something to stun them with. And if they come close to dying, they can just run away at full speed and if they just damaged you a bit you won't be fast enough to even have equal speed. Even if you have equal speed they'll just be able to bolt a door behind themselves and escape anyway. 

This PR adds damage slowdown to borgs making them more equal in combat against anyone that's not a borg themselves.

Realistically it also makes sense like with humans when your body breaks down that you are unable to run at full speed like nothing ever happened.

To balance out the slowdown, flashes and laser pointers now need 2 hits to stun, the first hit will blind with static vision and slow down the borg, the second will stun. Borg stuns last less long and can't be chained infinitely but you can stun them again as soon as they have recovered. The stun duration is still enough to emag, give the borg damage slowdown, or kill if you can damage fast. EMP still works instantly since a lot of things only cause one EMP blast and the things that don't are generally rare on the station.

I talked about some stuff i should have thought about when making the PR at first here: https://github.com/tgstation/tgstation/pull/68445#issuecomment-1186205303

## Why It's Good For The Game

Borgs are now more equal to everyone else in combat and you have a bigger chance to kill a borg without using flashes or stuns. Spiders now can actually put up a fight against borgs who are just going in hitting them, then running as soon as they are close to dying (Borgs are immune to toxins). Blobs now have more of a chance against borgs without using the EMP strain. + all the other combat situations I forgot about.

Methods to stun borgs are less powerful to balance out cyborg combat, so it won't be a steamroll of either one side or the other.
## Changelog

:cl:
balance: Cyborgs are now slowed down by taking enough damage like humans are.
balance: You need to flash cyborgs twice to fully stun them, the first flash will slow them down and blind them. The second will stun.
balance: You can't infinitely chain stun cyborgs with flashes as their sensors already are down.
balance: Cyborgs recover from stuns slightly faster.
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
Honestly? Not a bad nerf, I think it's pretty agreed that borgs are strong as fuck and this should somewhat limit gamer potential

**Comment by Ryusenshu** [comment]
> Honestly? Not a bad nerf, I think it's pretty agreed that borgs are strong as fuck and this should somewhat limit gamer potential

I sure love walking at snails pace, hoping for a robo that can repair me because of the fire damage i got (it wont happen)

Borgs are weak on themselves, the only reason they can fight most of the time is that the opponent isnt prepared for them, which i doubt is a good nerf reason for any kind of situation

Borgs are also still bound on law and policy
They arent Carbons, please dont make them one

**Comment by GuillaumePrata** [comment]
Having to deal with the consequences of your actions (being beaten to near death) should not be a Carbon only thing...

If Robos can't fix you, it is part of the drama in the round, if a department is unable to do their job the crew should feel it and Cyborgs are lucky because they are only dependent on 1 job unlike the rest of the crew.

**Comment by Kubisopplay** [comment]
> Having to deal with the consequences of your actions (being beaten to near death) should not be a Carbon only thing...
> 
> If Robos can't fix you, it is part of the drama in the round, if a department is unable to do their job the crew should feel it and Cyborgs are lucky as they are only dependent on 1 job (that any assistant can do if you ask) unlike the rest of the crew.

On one job that they should allow only to maximum of 4 people to do, since technically letting assistants open you is a violation of laws, since it is a big risk of tampering.

**Comment by iansdoor** [comment]
This kind of shafts mining borgs hard on lavaland or ice moon. Get hit, no repairs, permaslow. Also no more megafauna killing with the inclusion. Borgs are still tied to humans, right?

**Comment by Ryusenshu** [comment]
> This kind of shafts mining borgs hard on lavaland or ice moon. Get hit, no repairs, permaslow. Also no more megafauna killing with the inclusion. Borgs are still tied to humans, right?

i mean , they still have a welder, but some enemies could hard enough to remove your ability to dodge properly

but yeah, megafauna fights are impossible then

**Comment by IndieanaJones** [comment]
This makes engineering and mining borgs even stronger than the rest of the borg cast due to being able to self-weld.  This also makes mining cyborgs much worse at their jobs.  

For a solution, I think mining cyborgs should have a module which lets them utilize legion cores to mitigate slowdown (perhaps only on lavaland/in low atmos?).  As for engineer borgs, I'm not really sure.

**Comment by LemonInTheDark** [comment]
I kinda like that borgs are different from humans in terms of slowdown, would be sad to lose that

**Comment by Shadowflame909** [comment]
Very good for balance but makes me wonder how we prevent flashes from screwing borgs now. Maybe give them flash resistance for a couple seconds after being flashed once?

**Comment by Dorsisdwarf** [comment]
Single largest nerf to cyborgs of all time, basically guarantees that any non-emagged borg will die to any human with a weapon improvised or other. Not only defangs the silicons but makes them even more prone to just quietly doing everything security tells them now that they can't even run away from a squabble over not looking the other way for sec.

**Comment by zxaber** [comment]
Both flash and EMP enable chain stuns on borgs, and every proper antag has access to at least one of them.

If you're going to kneecap borgs, the *other* counters should be considered as well.

**Comment by chemistrymain2** [comment]
The lack of slowdown is the main reason borgs are so strong.

With this gone, they simply don't need their insane hardcounters anymore. It'd be safe to tone down flashes permafucking them.

**Comment by IndieanaJones** [comment]
Merge this in exchange for secborgs.

**Comment by necromanceranne** [comment]
> Both flash and EMP enable chain stuns on borgs, and every proper antag has access to at least one of them.
> 
> If you're going to kneecap borgs, the _other_ counters should be considered as well.

Flashes also stun humans, and humans can be stunned by a whole lot more than just two different tools. Not every opponent will be equipped with one of these two tools, so borgs are already a cut above humans. You have to give some room _somewhere_. Damage slowdown is truly the least severe nerf and generally still playable, because playing as a human, you would already have to deal with this issue. 

If you can survive as a human taking damage, you can survive as a borg. If you can't, that demonstrates just how much more aggressive borgs can be as combatants due to their overall greater survivability where damage doesn't matter for both their ability to engage or disengage (usually).

**Comment by realthomas69** [comment]
although i hate sillicons, cyborgs are a non-issue and its pretty easy to just dispatch them by using emps or a flashbang. i dont see any reason for them to be nerfed, especially not this hard

just multitool an empnade to activate instantly, if they're visible on the screen when you activate it you'll land the stun and then you can just shoot them to death, you probably wont even need a second nade. keep in mind you can make this in like 1 minute with some uranium, iron and a blender

**Comment by Pandarsenic** [comment]
Cyborgs are basically a joke for the reasons mentioned above.

If this is merged, it would be reasonable for borgs to lose compensating disadvantages like flashes and EMPs both being instant, long-duration hardstuns, which are now impossible on carbons...

or we can stop trying to solve interesting choices/skill issues like "fighting silicons is different from fighting carbons, do I gear up for that or try to handle them a different way" with ided PRs

**Comment by Shellton123** [comment]
Borgs are pretty weak due to them having no counters to their stuns, stuns being able to be mass produced at any chem dispenser or robo lathe and limited amount of choice for their weapons. But lets say they are uber strong, 90% of the time 50% of the time auto wins any conflict with them since assimov exists and if you are not human it is clearly stated a few times per round how to not angry the all mighty silicon nation. And 1% of the time AI gets dnd lawset which makes it so they can't attack anything since one of their laws is all living things are players and you can't harm players.

**Comment by datorangebottle** [comment]
AIs already quiver in fear at the idea that security might send a single hulk to their satellite and they'll be able to do absolutely dick-all about it. Why are we nerfing one of their only methods of interacting with the round?

**Comment by LemonInTheDark** [comment]
Why is it better to make borgs weak in the same way as humans when damaged? Why is it worth it to erode that uniqueness

**Comment by Dorsisdwarf** [comment]
> > Both flash and EMP enable chain stuns on borgs, and every proper antag has access to at least one of them.
> > If you're going to kneecap borgs, the _other_ counters should be considered as well.
> 
> Flashes also stun humans, and humans can be stunned by a whole lot more than just two different tools. EMPs are definitely strong, but they're not ubiquitous and come with their own downsides as well. Not every opponent will be equipped with one of these two tools, so borgs are already a cut above humans. You have to give some room _somewhere_. Damage slowdown is truly the least severe nerf and generally still playable, because playing as a human, you would already have to deal with this issue. Also, totally unarmed opponents simply cannot damage borgs, so someone not equipped to deal with you still just kind of dies.
> 
> If you can survive as a human taking damage, you can survive as a borg. If you can't, that demonstrates just how much more aggressive borgs can be as combatants due to their overall greater survivability where damage doesn't matter for both their ability to engage or disengage (usually).

1) Flashes stun carbons for a short period (2-5 seconds in perfect case) humans who arent wearing any of the common total no-sells and can be almost totally neutered by just not looking towards the guy trying to flash you, reduced to 1-2 seconds for a sideways and zero for looking in the opposite direction. They stun borgs for 9 to 14 seconds and apply confusion stacks regardless of facing and there is no protection in the game against them.
2) Cyborgs unlike humans aren't allowed to fight back against most of the crew, they have to run away when Jenkins McAnnoyance whacks them with an oxytank.
3) You can overcome this supreme power of the cyborg by picking up the oxytank out of your survival kit. Borgs don't have a force minimum, they just have a hardcoded "no punching"

**Comment by Kubisopplay** [comment]
Reminder that stunned cyborg cannot call for help, nor tell anyone they are being deleted, in contrast to humans who are quite hard to totally silence

**Comment by ATH1909** [comment]
image

**Comment by ATH1909** [comment]
personally, I'm of the opinion that cyborg escape tools NEED to be good, as escaping is their only option against any human with flash protection (such as, say, a welding helmet). a human can deal with damage slowdown with a well-made speed chem mix or (much more commonly) just by fighting to the death, but a cyborg has access to neither of those options.

this also pretty much kills playing possum while being flash->bashed as a borg, which is an immense shame.

**Comment by Ebb-Real** [comment]
> Why is it better to make borgs weak in the same way as humans when damaged? Why is it worth it to erode that uniqueness

Whether a borg escapes/wins a fight is incredibly determined by whether the enemy has a way to stun the borg. Its a massive steamroll for either the borg or human not much in-between. This steamroll has made carrying flashes or ways to stun borgs incredibly meta and a need to have especially for antags, because if you don't and get in a fight with a borg they'll be able to just run and snitch on you no matter how strong weapons you got that aren't stun. Which can especially be annoying with borgs just following you around while you got a slight bit of slowdown and outing your location, this can easily be achieved by the borgs hitting you a few times then running if you don't have a way to stun them.

Them having slowdown will in no means make them unable to win a fight like many people are arguing. They'll still even have the advantage in a fight which dosen't use massive dps weapons or doesn't include insta-win stuns. Since they still are able to deal damage until they reach 150 damage taken where all their modules will break and don't suffer all the other weaknesses of humans. They don't go crit even after this which makes sense since they're robots and don't feel pain. But them being able to run away at full speed like nothing ever happened doesn't make sense to me both realistically and balance wise.

They're incredibly powerful against anyone not carrying something to stun them with but also get instantly destroyed by anyone who does. I made this PR to make it less of a steamroll, but i should maybe also take the stuns into consideration since that's also part of the reason fighting against borgs will end up as a steamroll for one side or the other.

Another thing i'd like to mention is that borgs can easily be mass produced or even mass emagged. I think leveling the playing field for something so easy to mass produce is necessary. Especially when they can use explosives like welder bombs, run away at full speed while no one can catch them and get repaired by either an antag or robo. Then go and do it again.

**Comment by Ebb-Real** [comment]
I was told to post this or im scared 👍 
image

**Comment by GuillaumePrata** [comment]
> Why is it worth it to erode that uniqueness

Is this uniqueness something worth in the first place?
When anyone thinks about cyborgs in any sci-fi setting there will be a few generic perks they would bring up:
Made of metal and resistant to damage, resistant to space, fire and cold, immune against diseases and poison.
Weak to EMP, susceptible to being hacked, limited by their programing/laws/model.

Now I really don't think anyone would say that "They move at max speed no matter how damaged they are" would be one, breaking down borgs/mechs part by part and seeing them slowly be worse at killing you is standard everywhere and it isn't something that we delve into enough here.

We should focus on making Borgs be more interesting to engage and not just be a snowflake different than carbons, right now with the insta win stun meta it just isn't interesting to engage with them.

**Comment by TymurShatillo** [comment]
When you nerf a mob that gets hardstunned in a one click of a flash with no ability to get protection from it

**Comment by Pandarsenic** [comment]
That post had a lot of words about why you want to do it (ided) but not a lot of words about why it's good for the game

**Comment by D4C-420** [comment]
#62231 is relevant to this,  More time needs to be spent making fighting borgs different than carbons. Damage slowing them down is boring and not creative or unique. Something else however might be. 
Also miner borgs would be completely destroyed by fauna if they had slowdown from damage.

**Comment by Ebb-Real** [comment]
I playtested mining borg, you won't have many issues fighting regular fauna and mining. Even if you get damaged enough by fauna its just like fighting them as a regular miner that dosen't have a bunch of regen cores. Most fauna is slow and also avoidable. You get a welder to repair yourself in-between each fight if you need to repair. You don't go crit at 100 damage and can still walk back to base for repairs as long as you aren't dead.

**Comment by Ebb-Real** [comment]
To balance out the slowdown, flashes and laser pointers now need 2 hits to stun, the first hit will blind and slow down the borg, the second will stun. Borg stuns last less long and can't be chained infinitely but you can stun them again as soon as they have recovered. The stun duration is still enough to emag, give the borg damage slowdown, or kill if you can damage fast. EMP still works instantly since a lot of things only cause one EMP blast and the things that don't are generally rare on the station.

**Comment by IndieanaJones** [comment]
> I playtested mining borg, you won't have many issues fighting regular fauna and mining. Even if you get damaged enough by fauna its just like fighting them as a regular miner that dosen't have a bunch of regen cores. Most fauna is slow and also avoidable. You get a welder to repair yourself in-between each fight if you need to repair. You don't go crit at 100 damage and can still walk back to base for repairs as long as you aren't dead.
> 
> You can still easily do your job if you aren't reckless.

What if I want to fight a megafauna, or have to in order to save a human?

**Comment by Ebb-Real** [comment]
> > I playtested mining borg, you won't have many issues fighting regular fauna and mining. Even if you get damaged enough by fauna its just like fighting them as a regular miner that dosen't have a bunch of regen cores. Most fauna is slow and also avoidable. You get a welder to repair yourself in-between each fight if you need to repair. You don't go crit at 100 damage and can still walk back to base for repairs as long as you aren't dead.
> > You can still easily do your job if you aren't reckless.
> 
> What if I want to fight a megafauna, or have to in order to save a human?

As I see it, in mining borgs current state, they aren't supposed to fight megafauna. They get no benefits from it, don't have the same variety of healing as regular miners or ability to become stronger as they mine. A lot of megafauna deal burn damage which they have no ability to heal themselves from at all.

If it was to save a human they could just run in buckle them fast before the megafauna agros on them and then run as megafauna attacks them or get lucky and not get agroed on at all. But this kind of situation is incredebly rare since fighting megafauna is supposed to round remove you so you gotta be there at absolute perfect timing if this were to happen.

**Comment by Dorsisdwarf** [comment]
> Another thing i'd like to mention is that borgs can easily be mass produced or even mass emagged. I think leveling the playing field for something so easy to mass produce is necessary. Especially when they can use explosives like welder bombs, run away at full speed while no one can catch them and get repaired by either an antag or robo. Then go and do it again.

Focusing in on this a bit, this seems to be the key to the underlying issue - that on 90% of rounds there are 0-2 cyborgs, but people balance them for the one round in a hundred where there are 20. And that's an incredibly hard balance point to hit for a role that is designed to be fundamentally different from the typical "Ordinary guy in a special jumpsuit" role

**Comment by ATH1909** [comment]
why do people keep gravitating towards making everything a baton clone

**Comment by ATH1909** [comment]
also you forgot flashbangs, flash powder, etc.

**Comment by LemonInTheDark** [comment]
I have succeeded in developing an opinion on combat balance, and I don't want this. I will now explain why.

> Having to deal with the consequences of your actions (being beaten to near death) should not be a Carbon only thing...
> 
> If Robos can't fix you, it is part of the drama in the round, if a department is unable to do their job the crew should feel it and Cyborgs are lucky as they are only dependent on 1 job (that any assistant can do if you ask) unlike the rest of the crew.

Consequences of your actions and slowdown on damage aren't one and the same. You're right in that there is unmined soul here.

> or we can stop trying to solve interesting choices/skill issues like "fighting silicons is different from fighting carbons, do I gear up for that or try to handle them a different way" with ided PRs
> 
> > You have to give some room _somewhere_.
> 
> That's the great part. You don't! In case you forgot, having cyborgs going after you should be _scary_ if you're not geared up with real weapons and/or hard counters. Malf/subverted AIs with cyborgs, or even lone subverted cyborgs, should be significant dangers. You should have to rub both of your brain cells together a few times before you tangle with a robot. Trying to make every possible scenario a fair fight is stale and uninteresting, and doing it by removing mechanical representations of fluff differences (cyborgs not feeling pain, etc.) is even worse.
> 
> there's no need whatsoever to give cyborgs damage slowdown, or mood bars, or flash resistance, etc.
> 
> Just let different things be different from each other.

I agree with this post in particular. Cyborgs are typically limited by laws and the rules of the station. The cases where that isn't a factor are 
A: When you're a non human antag (IE: you have chosen to play a role who is open to attack by cyborgs, this is The PointTM of this downside)
B: When you're a non carbon antag, in which case you're given tools for dealing with this sort of thing
C: The cyborg has had its laws changed, either by 
C.1: the captain to make it better at hunting ze bad men, in which case the crew has turned the silicons into crew aligned members, like antags can or 
C.2: By some antagonist, or a malf ai, in which case they become the defining theme of the round, and avoiding/shutting down the ai and then the cyborgs becomes the Point.

I don't think any of these cases are so trivial, or should be so trivial, that they warrant making cyborgs "Balanced" in a fair fight against humans. Balance here is a misnomer even, since it's not something we actually want. 

I want 20 borgs to steamroll the crew, I want an antag who turns the ai to be massively more powerful, I want fighting a cyborg to be something it is wise to consider ahead of actually engaging one,
I don't want fighting a borg to be like fighting a human, I don't want turning the ai to mean the antag just has a few new human buddies on his team. I don't want cyborgs to be balanced.

> > Why is it better to make borgs weak in the same way as humans when damaged? Why is it worth it to erode that uniqueness
> 
> Whether a borg escapes/wins a fight is incredibly determined by whether the enemy has a way to stun the borg. Its a massive steamroll for either the borg or human not much in-between. This steamroll has made carrying flashes or ways to stun borgs incredibly meta and a need to have especially for antags, because if you don't and get in a fight with a borg they'll be able to just run and snitch on you no matter how strong weapons you got that aren't stun. Which can especially be annoying with borgs just following you around while you got a slight bit of slowdown and outing your location, this can easily be achieved by the borgs hitting you a few times then running if you don't have a way to stun them.

I am fine with this. If you're not prepared to fight a borg, don't get in a fight with a borg or you're going to have a hard time.
 
> Them having slowdown will in no means make them unable to win a fight like many people are arguing. They'll still even have the advantage in a fight which dosen't use massive dps weapons or doesn't include insta-win stuns. Since they still are able to deal damage until they reach 150 damage taken where all their modules will break and don't suffer all the other weaknesses of humans. They don't go crit even after this which makes sense since they're robots and don't feel pain. But them being able to run away at full speed like nothing ever happened doesn't make sense to me both realistically and balance wise.
>
> They're incredibly powerful against anyone not carrying something to stun them with but also get instantly destroyed by anyone who does. I made this PR to make it less of a steamroll, but i should maybe also take the stuns into consideration since that's also part of the reason fighting against borgs will end up as a steamroll for one side or the other.
>
> Another thing i'd like to mention is that borgs can easily be mass produced or even mass emagged. I think leveling the playing field for something so easy to mass produce is necessary. Especially when they can use explosives like welder bombs, run away at full speed while no one can catch them and get repaired by either an antag or robo. Then go and do it again.

As mentioned above, I don't see this as a problem
--------------------------------------------------
I'm fine with people adding downsides to being hit, but I think the goal of making fighting cyborgs a semi level playing field is silly, and ultimately destructive to the weight of decisions I find interesting and well, entertaining.

If you don't want to fight borgs, or aren't prepared to fight borgs, I don't think you should put yourself in a situation where you need to fight borgs.
If the issue is cyborgs and silicons being crew aligned instead of human aligned, that's something that should be taken up with the admin team, rather then attempting to handle it via code I think. Not saying it is, but just on the off chance.

I don't think I want this. Also because it makes borgs and humans more samey, which makes me sad.
Given my current thoughts, I think I would have closed that previous pr that attempted to nerf hardstuns and such.
I'm closing this.

**Comment by LukasBeedellCodestuff** [comment]
I'm not really sure how so many people have issues fighting borgs, they've got quite a few counters. As far as things go, you should aim to collect counters otherwise it's a skill issue.

**Pull request closed without merging**
