### PR TITLE
Removal of Unsprited Redcoat Costume

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request

This costume has existed in the codebase for a long time and has not had a sprite. It's currently possible to attain one using a denied stamp to dye an undersuit. Bad!

This could alternatively be solved by someone spriting it.

Relates to https://github.com/tgstation/tgstation/issues/37817

## Why It's Good For The Game

Removes ability to attain broken item

## Changelog
:cl: bobbahbrown
del: Removed unsprited redcoat costume.
/:cl:

### CODE REVIEW

**Comment by bobbahbrown** [comment]
oops didnt mean to remove that

**Comment by Fikou** [comment]
improve dont remove

**Comment by ArcaneMusic** [comment]
Working on sprites now.

**Comment by bobbahbrown** [comment]
> Working on sprites now.

thank u

**Comment by ArcaneMusic** [comment]
TheBritish
Ironically enough, the redcoat hat seems to have been fully sprited, just not the coat. Neat.

**Comment by bobbahbrown** [comment]
> TheBritish
> Ironically enough, the redcoat hat seems to have been fully sprited, just not the coat. Neat.

ok closing in preparation for your pr

**Pull request closed without merging**
