### PR TITLE
Quantum teleportation makes rainbow sparks

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Happy pride month

Jokes aside, since its addition quantum teleportation has always had a rapidly-changing-rainbow motif, i thought that making the sparks behave in the same way would be cool now that we have teleport flags.
Side change: non-bluespace teleportation no longer makes sparks by default.

## Changelog
:cl:
tweak: Quantum teleportation now makes pretty rainbow sparks instead of the normal ones.
fix: Non-bluespace teleportation (spells etc.) no longer makes sparks.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
ugh of course coders would PR this during pride week >.>

**Comment by fludd12** [comment]
🌈 🌈 🌈 
Pride Sparks
🌈 🌈 🌈

**Comment by JJRcop** [comment]
If they touch an ignitable gas mix they should create quantum hotspots that doesn't damage anything or consume gas until it's looked at by a living mob, and it has a 50/50 chance of just disappearing immediately when looked at.

**Comment by OverlyGeneric** [comment]
taste the rainbow, motherfudger.

**Comment by AnturK** [comment]
Mere conflict.

**Comment by AnturK** [comment]
Something went wrong with the merge.

**Comment by XDTM** [comment]
oh dear

**Comment by optimumtact** [comment]
Sparks often cause server lag etc which is why I removed them from a lot of teleport sources, can this be spammed?

**Comment by XDTM** [comment]
this is a recolor, so there is no number change in quantum teleportation itself (which can't be spammed due to cooldown anyway).

The extra fix where magic teleportation no longer sparks probably removed sparks from potentially spammable teleportation, but i didn't check all the do_teleports around the code.
Off the top of my head only portals from the portal gun should be still spammable for sparks, so if you already removed those we should be fine.

**Pull request merged**
