### PR TITLE
Adds a blob-start landmark to runtime station to avoid crashes

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
Throws a landmark in to stop some errors.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
When you say crashes

**Comment by Mothblocks** [comment]
Your changelog is bad. Changelogs describe changes, from your changelog it looks like you made a bug fix by making Runtime Station crash. It should be "Fixes crashes on Runtime Station", but 1. this was never the cause of a crash (just runtimes that blocked spawns), and 2. changelogs should only detail changes players actually see.

**Comment by itseasytosee** [comment]
I personally crash on runtime station because of this but I understand It would be different if you ran it on the servers.

**Comment by itseasytosee** [comment]
image

**Comment by LemonInTheDark** [comment]
That just causes a runtime doesn't it?

**Comment by itseasytosee** [comment]
Yeah, but it also crashes my Dream deamon server.

**Pull request merged**
