### PR TITLE
Roundstart Engine Selection (WIP)

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request

The main idea behind this PR is to turn every roundstart engine area into a blank workspace and give Engineering the ability to warp in a prefab of an engine of their choice. Prefabs will have the basic setup for the selected engine along with some extra supplies to do whatever with. If an engine is not selected via the beacon tool within a reasonable roundstart time, a random one will be selected and warped in automatically.

## Why It's Good For The Game

More variety to choose from when playing as an Engineer and might encourage people to learn the lesser-used engines (TEG, mostly) or learn why the supermatter eventually replaced the singularity. 

## Changelog
:cl: MMMiracles
add: Engineering now starts without an engine but with the ability to spawn one in.
add: The CE's office spawns with an engine beacon and a plethora of prefabs to choose from for the station engine.
add: Not choosing an engine for the station without a reasonable amount of time will have one randomly selected and warped in for the station.
/:cl:

todo stuff:
- [ ] Make the engine warp look fancier/maybe deadlier if you're under it
- [ ] Proper naming in the engine selector rather than the template's pathtype.
- [ ] The actual mapping of the engines
- [ ] Remapping Box/Meta/Donut to suite this new design.

The main reason I handle the engine checking and spawning through the beacon item itself is so maps that aren't set up to use it don't run into any issues until their updated. I only plan on updating Box/Meta/Donutstation with this, as having to remap every engineering section and give proper fitting universal templates is gonna be enough of pain as is.

### CODE REVIEW

**Comment by Jimmius** [comment]
I like the idea of giving the CE more to do, especially stuff that fits the less hands on "site foreman" CE, who oversees the engineers rather than doing everything themself because they have the best gear.

However, the Singulo and Tesla were both phased out of sensible maps for a reason. That being: giving anyone with engineering access the ability to end the round whenever they like by cutting two wires (or just blowing up a field gen) is dumb as hell.

The game really needs more non-meme engines for this to work. Currently, loyal CE's will only choose between the SM and TEG, and traitor CEs will only choose between the Singulo or Tesla.

Failing that, maybe only give the beacon to CE's on Pubby or Donut, because they're gimmick maps built around the idea that the engine will loose.

**Comment by Ziiro** [comment]
Given the issue that Jimmius has raised here (and I agree) maybe just make it random on mapload so people are forced to learn something else.

**Comment by MMMiracles** [comment]
To be fair, you can still create both of those engines with the help of cargo (cargo even has the tesla as a potential bounty item). If engine choice is enough of an issue, they can just easily just have their template removed.

**Comment by Bawhoppen** [comment]
I would think this is a prime candidate for a config option on whether it's choose-able, random, or pre-decided.

**Comment by OverlyGeneric** [comment]
If it is going to be a machine, make Singulo/Telsa emag-only because engineers will pick it roundstart all the time because its more destructive than most engines.

**Comment by wesoda25** [comment]
You contradict yourself. “Learn why sm replaced it eventually” is exactly why this PR shouldn’t be open. Its a cool idea and all, but fucking hell it’ll just lead to CEs getting an easy singuloose/tesaloose when they roll traitor, SM is the perfect engine and all others can fuck off.

**Comment by OverlyGeneric** [comment]
> You contradict yourself. “Learn why sm replaced it eventually” is exactly why this PR shouldn’t be open. Its a cool idea and all, but fucking hell it’ll just lead to CEs getting an easy singuloose/tesaloose when they roll traitor, SM is the perfect engine and all others can fuck off.

image

TEG is actually more efficient than any other engine. The only problem is that it can't produce its own fuel but its completely viable for the ancient art of hellburning.

**Comment by optimumtact** [comment]
I'm going to deny this.

I want to go towards one engine, not many. We have problems with power balance and I can't easily resolve them with multiple engines in play.

Will leave this open for discussion until 24 hours passed.

**Comment by TerraGS** [comment]
Kind of surreal how I was talking to people about this exact idea 5 hours ago but Oranges said it wasn't a good idea.

**Comment by OverlyGeneric** [comment]
@optimumtact 

The thermo-electric engine is the only way to go. Do not doubt the power of hellburns.

**Comment by wesoda25** [comment]
I aint got shit to learn sm is the best

**Comment by ike709** [comment]
All hail Lord Singuloth!

**Comment by Unit2E** [comment]
I agree, the SM is best for being an engine that can both be sabotaged and be fixed.

Without a doubt, the TEG is more 'efficient', however, being an engine within a game, it's extremely lacking. The TEG is riskless, and boring overall, though it does have options for being optimised at the least. On the other end of spectrum are the tesla and singulo. Instead of being practically riskless, these are way too high risk, with no real way of fixing them or knowing they even need to be fixed before they destroy the station with little effort. They also have very little in the way of experimentation attached to them, which the SM allows, as does the TEG (in a lesser degree).

So as people have said, there is a reason there's a move away from the other engines that exist, why change that now just for the heck of it? Very cool idea in theory, but for it to be viable, we would need more engines that are as good, game wise, as the SM, and currently there aren't any.

**Comment by zxaber** [comment]
Having preset engines helps maps like Pubby and Donut stand out, too. Sure, there's more to a map's character and charm than just the engine, but it all ties in with letting them be unique.

**Comment by optimumtact** [comment]
I'd like to remove those engines tbh.

**Comment by MMMiracles** [comment]
I made this PR mostly due to the results of the donutstation poll I asked for, if this doesn't make it in I'll probably end up switching Donut to the SM since one main engine seems to be the goal here.

**Comment by 81Denton** [comment]
@optimumtact The templating part of this would be a good step towards solving the issue where five maps have to be changed every time someone touches a part of them. 
For example, generic areas like the supermatter engine and telecomms could be replaced with templates.

**Comment by JMoldy** [comment]
the TEG and Turbine are going to be improved significantly with the upcoming fusion changes. 

the Singulo and Tesla honestly need some serious work on making them easier to fix, or at least give people a chance to catch it the way the SM does. AT the very least the engineers need notification that the containment is losing power, or the singulo is gaining too much mass.

**Comment by optimumtact** [comment]
They don't need work they need to be tossed out, they're holding back engineering

**Comment by OverlyGeneric** [comment]
> They don't need work they need to be tossed out, they're holding back engineering

@optimumtact You can't kill off a important piece of SS13's history and is a waste of destructive potential in a game about space.

**Comment by optimumtact** [comment]
1) I can
2) they're still available via the SM
3) you have no idea what you're talking about

**Comment by lordpidey** [comment]
Oranges does bring up some good points about the destructive potential of the singularity and tesla.

However, I think the move to more modular stations is a good one, and engine is a great place to start.

So, what I think a good compromise would be:

Disable the ability to select singulo/tesla engines, otherwise keep in tact.

I have some ideas for new engine types, some more serious than others, and having this would greatly help in the future if those engines ever get implemented.

**Comment by lordpidey** [comment]
orange man bad

**Pull request closed without merging**
