### PR TITLE
Implements an experimental tool degradation system on all tools

### PR DESCRIPTION
**Pull request by ArcaneMusic**
I hope everyone's having a wonderful day, I'm just coming off a case of COVID.

## About The Pull Request

- All basic tools, such was wrenches, scalpels, screwdrivers, etc. have been given a degradation component. 
- Advanced tools or otherwise unique tools do not have this component, including power tools and advanced tools located within the research net.
- Tools will degrade only after successful completion of it's action, such as completing a do_after or successfully using the correct tool for the job.
- Additionally, misusing tools for combat will also decrease the durability of those tools.
- Tools whose durability have gone past 50% will see their combat force, as well as their tool speed, become more inefficient. 
- At any time, tools can be closely examined to determine how much durability they have.

## Why It's Good For The Game

I'm writing this PR as more of an experiment than anything, just to test the waters, but the content of this PR is functional and working as intended to the best of my ability.

I'm copying this verbatim from a fledgling design doc I wrote a few weeks ago and pasting it here, but the full document can be found here, alongside alternate designs that I decided not to go with after developer feedback:

https://hackmd.io/fswOYeA1TfOuJPISKUGgcA

> Tools as they exist in game are extremely common, obtainable by nearly all crew at all times to some respect, and nearly every job needs access to some level of construction equipment to properly do their job.
> 
> Engineers, obviously, need tools to set up power, repair explosions, or to build things out of raw materials.
> Scientists and chemists need tools as their job necessitates the construction of extra machinery, as well as working with/around robots.
> Medical doctors have their own custom tools, that they use at all times for operating on patients.
> Cargo technicians don't actually need tools to do their job exactly, but with full lathe access and bounties to complete, nearly every cargo technician has a full set of tools.
> Most assistants, for the same reasons as cargo techs, have a full set of tools, but that's mostly because it is convienant for powergaming, and tools are outright required for efficient gameplay.
> And for that same reason, most *security officers* have a full set of tools, in case a crewmate is using their tools to commit crimes or be difficult.
> 
> If a player is caught without any tools, than more often than not they're at a severe disadventage. However, the issue is **not** that players shouldn't need to use tools as much as they do, no.
> The issue is that players **need** to get tools *every single shift*, and then they don't need to make any further decisions regarding those tools going forward.
> 
> The most fulfilling way to make tool-use more interesting is to change the tools themselves, as opposed to changing the usage of tools. This is, of course, my opinion, and I am not a maintainer, but the proposal is where I'm trying to get permission to do so.

## Changelog

:cl:
balance: Adds a new component to all basic, non-powered and non-unique tools to the game.
balance: Tools now degrade with usage after successful completion of a task. Breaking a do-after will not use durability.
balance: Tools that are misused will also see their degradation, which slows their tool speed, as well as their combat force after a point.
balance: A tool with zero durability has it's tool speed 5 times slower, and it's force at if not near zero.
/:cl:

### CODE REVIEW

**Comment by tuckerorchistra** [comment]
Why do we need tool degradation? I see no use in this other than to make the game more annoying to play.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Absolutely no comment on the balance of the feature, just code review

**Comment by trexter5555** [comment]
this brings nothing good to the game, it just adds an unneeded annoying mechanic that nobody likes or wants

**Comment by GuillaumePrata** [comment]
This adds a new and amazing balance lever to toy with balance and desirability of tools.

Something as simple as making the medium sized crowbar have more durability than the default pocket crowbar. It makes a medium crowbar desirable for engineers for it's durability while the pocket stay as a good tool for the crew without a toolbelt to carry more durable tools easily.

**Comment by YuliceTheDruid** [comment]
Definitely have to say I'm not a fan of this balance wise; obviously can't speak for the quality of the code itself, but all this seems like it would do is make it so that people now simply just mass produce lots of tools and leave them laying around or constantly run and print a new set off as soon as they finish using their tools for whatever, or the durability hits will be so insignificant that people will never even need to make more tools beyond their first anyway. Alternatively, it'll make things that can still hold advanced tools and fit inside of a bag even more desirable and will consolidate power into the hands of a few small people who intricately know the game's mechanics and know where and how to get those limited items very quickly.

**Comment by Draggeru** [comment]
TG is turning into breath of the wild and animal crossing new horizons and I am not for it

**Comment by CRITAWAKETS** [comment]
y tho.

**Comment by CMDR-Gungnir** [comment]
"I don't like that people tide for tools, so I'm going to make sure they need to tide for tools even more"

honestly quite incredible.

**Comment by Mothblocks** [comment]
>  The issue is that players need to get tools every single shift, and then they don't need to make any further decisions regarding those tools going forward.

This justification makes no sense to me. I don't think not needing to make "further decisions regarding tools" is a bad thing. The decision you are making is that you are taking up storage that could be used for something else. That boxes are in the state they are in is a separate issue.

I'm going to mark DNM in case another maintainer was interested in this and I am out of the loop by virtue on not being on Discord (my fault admittedly)

**Comment by private-tristan** [comment]
will there be any way to quickly dispose of tools (iirc you can't recycle tools without autolathe) or will medbay be flooded with 'broken' hemostats after they preform 2 tend wound surgeries?

how will this effect hacking? does crowbar degradation decrease airlock pry open time?
how will this effect heirloom tools (engineer/CE only I guess)? will they become (effectively) deadweight on your character with no practical use once they hit 0%?
will there be a way to check durability? (pr is kinda vague on this and I don't feel like codediving)
about how many uses (on average) will a tool have? obviously things like hemostats will need a lot more durability than things like wirecutters.

overall this is a very interesting PR, I wonder how a TM will go.

**Comment by Wallemations** [comment]
My main concern is more in the resource management side of things. From what I understand, this is gonna exponentially increase the amount of materials used per round, since everyone and their mother is gonna want their tools replaced. Seeing how lots of people get tools roundstart or close to roundstart, I can only see this resulting in waves of people's tools breaking all at once, and them all rushing together to the nearest lathe to get them replaced.

I'm sure there's some subsystems that this could be useful in, like I can imagine a faster & more powerful form of an existing tool that happens to also have durability as a way of balancing it, but for general tool use I can't say I see it working well. It's definitely an interesting concept though.

**Comment by ArcaneMusic** [comment]
> > The issue is that players need to get tools every single shift, and then they don't need to make any further decisions regarding those tools going forward.
> 
> This justification makes no sense to me. I don't think not needing to make "further decisions regarding tools" is a bad thing. The decision you are making is that you are taking up storage that could be used for something else. That boxes are in the state they are in is a separate issue.
> 
> I'm going to mark DNM in case another maintainer was interested in this and I am out of the loop by virtue on not being on Discord (my fault admittedly)

Well, I'm more than willing to take the L on this one all things considered, but I also did copy-paste an older justification so I'll try and rephrase.

As it stands, every crewmate wants and needs a full set of tools, either for hacking, job progression, or traitor activities. However, because tools never degrade, never change, and have no incentive to ever be replaced or recycled, a player will continue to use the same set of tools from roundstart 4-5 hours into a late long shift. Tools are a large part of the item economy in that a significant portion of the printing in-game goes towards making tools at the start of the shift, but there will never be a reason to replace them. Hell, even power tools don't give enough of a significant speed-up to be worth printing when compared to regular tools.

So, tools as a broad metric are too powerful and generally required for all jobs. However, that also means that they're no specialization. Why call over an engineer when a chemist with his toolbox can do the exact same job? In the Hackmd I already talked about 3 different ways that one could go about with making that work, either making tools unique, more expensive, or leaving them cheap but going about this durability system, and this was the one I was met with the most support towards. Either way, as long as we can introduce even basic systems that require players to consume some amount of resources, it would make for a healthier system of drains on the item economy.

I could be wrong, though.

**Comment by GuillaumePrata** [comment]
Tool degradation was the best of the 3 systems as they are the only that actually have player input and decisions changing from round to round.

Right now, whenever there is an emergency that you need to use tools there isn't much planning or consideration, you map the shorter line to your goal and just hack or weld down walls to get to it as your tools will never fail you.

Now with the knowledge that your tools will eventually fail you, something as simple as making false walls to kill Runtime for the 5th round in a roll has the risk of your tools failing you if you overused them earlier, leaving you on a bad situation and needing to figure a new route.

**Comment by CMDR-Gungnir** [comment]
> Tool degradation was the best of the 3 systems as they are the only that actually have player input and decisions changing from round to round.
> 
> Right now, whenever there is an emergency that you need to use tools there isn't much planning or consideration, you map the shorter line to your goal and just hack or weld down walls to get to it as your tools will never fail you.
> 
> Now with the knowledge that your tools will eventually fail you, something as simple as making false walls to kill Runtime for the 5th round in a roll has the risk of your tools failing you if you overused them earlier, leaving you on a bad situation and needing to figure a new route.

They will simply tide for more tools before this becomes an problem.

**Comment by Mothblocks** [comment]
> However, because tools never degrade, never change, and have no incentive to ever be replaced or recycled, a player will continue to use the same set of tools from roundstart 4-5 hours into a late long shift. Tools are a large part of the item economy in that a significant portion of the printing in-game goes towards making tools at the start of the shift, but there will never be a reason to replace them. 

I think this is circular reasoning. Nothing you said here is really a bad thing on its own and I don't know why getting new tools is innately good.

**Comment by SomeoneYouProbablyKnow** [comment]
I think tool degradation and other changes to create scarcity are good but they should coincide with ghetto alternatives, otherwise you're just increasing the demand for tools. Fire alarm buttons my beloved. (Yes i could have used discord, i just want to spam your email in case you have notifs on)

**Pull request closed without merging**
