### PR TITLE
Dextrous guardian HUD fix

### LINKED ISSUE #50624: dextrous guardian hud had some of its icons removed
it is missing the icons in guardian.dmi for its hand storage and internal storage.

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR fixes an issue where dextrous guardian lacked some of his HUD elements, because they depended on having flexible ui_style.

Fixes #50624

## Why It's Good For The Game

Bugfix.

## Changelog
:cl: Arkatos
fix: Fixed an issue where dextrous guardians lacked some of their HUD elements.
/:cl:

### CODE REVIEW

**Comment by AnturK** [comment]
This is wrong fix, fix the outliers instead of ignoring common system.

**Comment by Arkatos1** [comment]
I have no idea about that. What outliers? Pull icon is the outlier, not the other way around. I should know, I was the one who added it in the first place.

**Comment by AnturK** [comment]
Initial change implied guardians can't use ui_styles. Now it only applies to pull which should be in all styles. So what exactly is the issue here ?

**Comment by Arkatos1** [comment]
Alright, I will explain. I made some customized, guardian-only pull icons, and made them use ui_style to be consistent with other HUDs. This is all fine for basic guardians(non-dextrous), as they do not have any HUD slots, crafting menus and so forth, so making them use their own little ui_style is of no issue. 

Problem is, I did not realize that dextrous guardians need that HUD elements, which is why HUD elements were missing, as the guardian.dmi does not contain any of them. Easiest way to do that was to simple delete forced guardian ui_style, and make it fallback on user preference styles (like Midnight, Retro, Clockwork and others) to make it pull it from them. Pull icon is the only special HUD thing in guardian.dmi anyway, which is why I made it directly pull the icon source for it.

**Pull request merged**
