### PR TITLE
New crate sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl: nicbn
imageadd: New crate sprites!
/:cl:

image

### CODE REVIEW

**Comment by optimumtact** [comment]
what perspective are the new spprites in?

**Comment by nicbn** [comment]
3/4

**Comment by GunHog** [comment]
I feel that the sprites should be improved, rather than just the same thing in a new perspective.

**Comment by optimumtact** [comment]
Then you have not been following along with the switch to 3/4 sprites have you

**Comment by MrDoomBringer** [comment]
did you make this PR without posting anything in #creative-general etc? (because i cant find any posts related to new crate sprites in the official discord or comfycord) if so it will be your hubris alone that closes this P

anyways we generally improve sprites when we update them to 3/4, otherwise it encourages being happy with mediocre sprites. having the bad sprite not be in the right perspective offers more incentive to actually improve them.

**Comment by MrDoomBringer** [comment]
a reading from the gospel of john:
image
may his spriting knowledge forever be with us

**Comment by praisenarsie** [comment]
the space heater sprite was a mistake

**Comment by fludd12** [comment]
I mean, personally, I like the change? Not sure what everyone's talking about the need to improve crate sprites for, I've always liked the crates currently in-game, and making them fit perspective is nice.

**Comment by vuonojenmustaturska** [comment]
The orange nuclear crate and the two mustard-colored crates are not really my favorites, but that's a problem with the originals. Could you fix the nuclear crate at least, it kind of looks like someone just slapped two nuclear signs onto a crate sprite in developer art fashion? 

Changing the perspective on the tall cube crate has somehow really improved it, it used to stand out pretty bad and not favorably.

**Comment by nicbn** [comment]
SS13 is not suposed to look sci-fi, it's suposed to look cyberpunk-ish. I'm gonna redo the crates and re-PR it

**Comment by MrDoomBringer** [comment]
>cyberpunk-ish? 

where? the aesthetic has always been retro-futuristic (ie. the Alien aesthetic). I just said scifi to prove the point that crates dont have to be GRADIENT RECTANGLES

though i appreciate the effort a lot to making the game's style better! Before you PR again, it might be good if you just remake the default crate, making sure to take input and criticism from our spriting channels. After people say it looks good then I would go on and finish the rest of the crates.

**Comment by nicbn** [comment]
Yeah, I meant retro-futuristic
oops

**Comment by MrDoomBringer** [comment]
#coderbus is the IRC for coding help. Sadly its been dead for a while.

Best place for coder help, sprite help, or other discussion is the official tg discord! https://discord.tgstation13.org/

**Comment by fludd12** [comment]
Don't listen to MDB, #coderbus is still quite active.
Though, discord is *also* a valuable resource. Pick whichever you want, or use both.

**Comment by MrDoomBringer** [comment]
>quite active

r u sure

**Comment by praisenarsie** [comment]
it's active, ur just in denial :dancer:

**Pull request closed without merging**
