### PR TITLE
Adds a line about alien species to contributing.md

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Line could probably be written better and I'd prefer not to have it at all (how embarrassing) but it ends up being a significant source of drama and stress for everyone involved when one of these PRs is opened and five more follow up.

@tgstation/commit-access My heart is not set on this if you guys think it's unneeded I'll find another way to address this

### CODE REVIEW

**Comment by duncathan** [comment]
Approval from whom? A maintainer? The design lead? God himself?

**Comment by KorPhaeron** [comment]
call the president and ask him if you can add catgirls to /tg/station

**Comment by KorPhaeron** [comment]
I'd be fine with maintainer approval but if you guys end up all getting pestered over the PR before it opens this may not end up saving on stress anyway

**Comment by duncathan** [comment]
I think the primary issue with maintainer approval is the difference of opinions we have, such as lzi not supporting fully aesthetic races where someone else like Joan or myself may. Not sure how the proper way to address that would be

**Comment by ChangelingRain** [comment]
ask for approval on the forums, maybe?

**Comment by ninjanomnom** [comment]
design lead approval would probably be best

**Pull request merged**
