### PR TITLE
Weapons permit for the curator

### PR DESCRIPTION
**Pull request by ghost**
So that he won't keep getting assfucked by beepsky when he takes out his whip
:cl:
tweak: The Curator now can take out his whip legally!
/:cl:

ided

### CODE REVIEW

**Comment by praisenarsie** [comment]
no, this isn't a proper fix

**Comment by ShiggyDiggyDo** [comment]
make on then

**Comment by praisenarsie** [comment]
no

**Comment by Cyberboss** [comment]
low effort shitpost

**Pull request closed without merging**
