### PR TITLE
Seperates charcoal and anti-toxin

### PR DESCRIPTION
**Pull request by ghost**
OJRHI94EITJNRJOTKM4T54RT4R54T434/R5.1!!!T,ROTHKNTRK

:cl: More Robust Than You
balance: Charcoal only heals 0.5 toxin damage per tick
balance: Anti-toxin no longer metabolizes reagents, but it now heals 3 tox per tick, up from 2
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
why

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blame/master/.github/PULL_REQUEST_TEMPLATE.md#L22

**Comment by Cyberboss** [comment]
I'd link the other closed attempts at this as well, but i'm too lazy

**Comment by Cyberboss** [comment]
#32580

**Comment by JJRcop** [comment]
https://github.com/tgstation/tgstation/blob/7fac86cfa8d41e4db3b697affdf85946b28c8f04/.github/PULL_REQUEST_TEMPLATE.md#L22

**Pull request closed without merging**
