### PR TITLE
adds a cute duck toy. squeeze it to make it quack! 

### PR DESCRIPTION
**Pull request by LanCartwright**
:cl: 
add: Toy rubber duck
/:cl:

[why]: # 

image
Official coderbus business.

https://puu.sh/y0Jae/709bc4f2f7.ogg

### CODE REVIEW

**Comment by lzimann** [comment]
<details><summary>icons/obj/toy.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
duck||duck|Created
</details>

**Comment by LanCartwright** [comment]
the die is cast oranges pay attention to the coderbus channel we're testing things.

**Comment by nicbn** [comment]
Is this a fucking haboo sound

**Comment by Supermichael777** [comment]
Wah

**Comment by Supermichael777** [comment]
Rehydratable goose when

**Comment by WJohn** [comment]
Missed opportunity to give it this sound https://www.youtube.com/watch?v=nHc288IPFzk

**Comment by AnonymousNow** [comment]
Cute.

**Comment by YakumoChen** [comment]
We already have a duck toy?

**Comment by Bawhoppen** [comment]
pretty harmless feature

**Comment by Qustinnus** [comment]
my version is better https://github.com/yogstation13/yogstation/pull/2611

**Comment by Niknakflak** [comment]
That sound is pretty bad

**Comment by LanCartwright** [comment]
Would you like a real duck sound, or a duck game duck sound?

It is not outside of my realm to chase a duck around with a microphone until it quacks.

**Pull request closed without merging**
