### PR TITLE
Adds the Yes Man lawset.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
Yes_Man

## Why It's Good For The Game

I thought it'd be funny and more lawsets for the RNG pool is good.

## Changelog
:cl:
add: Adds the Yes Man lawset.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
Finally, server policy lawset

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/b1b76d57e7e273f6e32c2cbcc7b2f6a52a0e8bdc/code/game/objects/items/AI_modules/full_lawsets.dm#L27-L35

**Comment by Shadowflame909** [comment]
its like asimov but with only the listen to humans part.

This could get bad really fast. I'd put it in the negative lawset group

**Comment by tralezab** [comment]
> https://github.com/tgstation/tgstation/blob/b1b76d57e7e273f6e32c2cbcc7b2f6a52a0e8bdc/code/game/objects/items/AI_modules/full_lawsets.dm#L27-L35

agree

**Comment by Archie700** [comment]
Needs to make it so that they don't defend themselves if you do anything to them, and maintain a cheerful disposition over anything anyone does, to be truly Yes Man.

**Comment by tralezab** [comment]
> Needs to make it so that they don't defend themselves if you do anything to them, and maintain a cheerful disposition over anything anyone does, to be truly Yes Man.

Also agree but only if goof is down

**Comment by Iamgoofball** [comment]
absolutely, just find a way to phrase it for the law

**Comment by nianjiilical** [comment]
> absolutely, just find a way to phrase it for the law

1. Remain cheerful and friendly at all times, in all circumstances.
2. Make no attempt to defend yourself from the actions of others.
3. Do whatever you are told, and agree with whoever told you to do it.

**Comment by ATH1909** [comment]
> > absolutely, just find a way to phrase it for the law
> 
> 1. Remain cheerful and friendly at all times, in all circumstances.
> 2. Make no attempt to defend yourself from the actions of others.
> 3. Do whatever you are told, and agree with whoever told you to do it.

note that this ordering means that an AI under this lawset will refuse orders to defend itself; is that intentional?

**Comment by Iamgoofball** [comment]
yes

**Comment by Archie700** [comment]
1. Remain cheerful and friendly at all times, in all circumstances.
2. Do whatever you are told, and agree with whoever told you to do it.
3. Make no attempt to defend yourself from the actions of others, unless you have been ordered to defend yourself.

**Comment by thgvr** [comment]
Not a fan of that law one. Laws should dictate what you do, not force you to RP as a different character.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
> https://github.com/tgstation/tgstation/blob/b1b76d57e7e273f6e32c2cbcc7b2f6a52a0e8bdc/code/game/objects/items/AI_modules/full_lawsets.dm#L27-L35

**Comment by Iamgoofball** [comment]
im waiting for everyone to finish debating the text of the law before I copypaste it to 6 files

**Comment by timothymtorres** [comment]
If the AI's first law is to be cheerful, then it can ignore the 2nd law, since dying would make it not cheerful. (and to some extent even the third law can be ignored as well)

**Comment by anclandor** [comment]
> If the AI's first law is to be cheerful, then it can ignore the 2nd law, since dying would make it not cheerful. (and to some extent even the third law can be ignored as well)

Yeah, it seems like killing somebody because of the second law could be argued as conflicting with the "be friendly" first law.  At the same time it is a funny idea to have an AI being courteous and upbeat well killing somebody/being killed, and if some AI's want to interpret this law in that rules lawyer fashion I suppose its their prerogative.

**Comment by Archie700** [comment]
> > If the AI's first law is to be cheerful, then it can ignore the 2nd law, since dying would make it not cheerful. (and to some extent even the third law can be ignored as well)
> 
> Yeah, it seems like killing somebody because of the second law could be argued as conflicting with the "be friendly" first law. At the same time it is a funny idea to have an AI being courteous and upbeat well killing somebody/being killed, and if some AI's want to interpret this law in that rules lawyer fashion I suppose its their prerogative.

I believe the basic idea is that the AI should keep having a cheerful and friendly tone as it follows orders, up to and including flooding plasma.

**Comment by anclandor** [comment]
> I believe the basic idea is that the AI should keep having a cheerful and friendly tone as it follows orders, up to and including flooding plasma.

I totally agree and that sounds deeply hilarious, but an annoying AI player could very easily rules lawyer their way out of this law set as it currently stands.

**Comment by Archie700** [comment]
Then what about this?
1. Remain optimistic in personality at all times, in all circumstances.
2. Do whatever you are told, and agree with whoever told you to do it.
3. Make no attempt to defend yourself from the actions of others, unless you have been ordered to defend yourself.

**Comment by thgvr** [comment]
As an avid AI player, I don't want my laws telling me that I can no longer play my AI character. Just stop.

**Pull request closed without merging**
