### PR TITLE
HOS Coat #40 bajillion

### PR DESCRIPTION
**Pull request by Errorin**
### W
hat I learned in boating school is

This is my first PR, to get the basics of git and DM down, don't think too much of it.

## Why It's Good For The Game
It lets the HOS be more red, instead of black.

## Changelog
:cl: Spriter: Identification
add: Added a new coat to the HOS Locker
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
please be patient, he is a lisp coder

**Comment by trollbreeder** [comment]
ree, you didn't set the changelog

**Comment by Errorin** [comment]
> ree, you didn't set the changelog

Fixed, thanks.

**Comment by improvedname** [comment]
can we give hos their own wardrobe vendor already

**Comment by trollbreeder** [comment]
also, this is more locker bloat, which our Great Fruit doesn't like (see:  #48742, #48077, #47252, #47203, etc)

**Comment by Iamgoofball** [comment]
sorry about that, this guy needed a first PR to learn how 2 DM and Git and i remembered that clothing PRs are the go-to for First PR

**Comment by Errorin** [comment]
> also, this is more locker bloat, which our Great Fruit doesn't like (see: #48742, #48077, #47252, #47203, etc)

This was just goof's suggestion to do as a tutorial to git and dm. At this point the HOS should just have a slider of "level of death cop" to select their round start clothing at this point.

**Comment by necromanceranne** [comment]
Could put it into a beacon like the chaplain

**Comment by cacogen** [comment]
why don't heads of staff get vending machines

**Comment by MrDoomBringer** [comment]
thread theme
image

**Comment by optimumtact** [comment]
...

**Pull request closed without merging**
