### PR TITLE
Brings back internals tank gibbing you on suicide

### PR DESCRIPTION
**Pull request by lzimann**
Leaving a body is just stupid

### CODE REVIEW

**Comment by Bawhoppen** [comment]
:-1: 
remove all the over the top suicides
they're just a shitty meme

**Comment by coiax** [comment]
From what I understand, the original reason to remove body destruction from oxygen tank suicides, was that it made it too easy to deny your body from being used as a xenobaby hatchery. Everyone is issued a tank in their internals box, and there would be many people gibbing themselves if they felt they wouldn't get surgery in time, thus denying xenos their new larva.

**Comment by FantasticFwoosh** [comment]
There is also the issue of with gibbing code, it also destroys the items on your person because you are in essence admin deleted with a little fluff gibs left on destruction behind.

If we had a system of a hard-gib (syndicate agents blowing themselves up to destroy equipment and bodies for purpose) and a soft gib (suicide gas tank that destroys the body but strips all your clothing slots starting with your jumpsuit first). It wouldn't be such a tip-toed round thing.

Soft gibs wouldn't fix the whole better deny myself mentality, but if a admin message was attached on self gibbing, people could be more accountable and think twice about it and get bwoinked for abuse.

**Comment by coiax** [comment]
Quite why people are so insistent on destroying the body, I'm not sure. Suicide, outside of bolts of life, should render you unrecoverable.

**Comment by Aloraydrel** [comment]
>Xeno denying

if you somehow didn't stunlock someone long enough for them to gib themself with a tank it's all on you

**Comment by coiax** [comment]
It happens a lot. Facehuggers will be scattered in maint, maybe someone gets away in a scuffle in the hive. Facehugger infection goes through stages, which you can tell apart by messages, when it goes too advanced, you could gib yourself with the availible tool rather than gib AND spawn a larva.

**Comment by Supermichael777** [comment]
This was removed for legitimate reasons.  Mostly green-text/reward denial for antags and REALLY shitty player behavior about it.

**Comment by lzimann** [comment]
Destruction of items is no longer a problem, it will drop everything before gibbing.

**Comment by PKPenguin321** [comment]
:-1: Let's just not

**Comment by Niknakflak** [comment]
:-1: :-1: :-1: :-1:

**Comment by jughu** [comment]
>oxygen gibbing problem>medical wrench not

**Comment by coiax** [comment]
There is one medical wrench in the medbay. There are at least N oxygen tanks, where N is the number of characters, plus dozens across the station. The two are not comparable. And if the medical wrench becomes a real problem, we can change it.

**Comment by lzimann** [comment]
i really don't see how a suicide can bring problems, it's just a person removing himself from the round

**Comment by KazeEspada** [comment]
removing himself and the entire armory plus all traitor objectives from the round

**Comment by lzimann** [comment]
If that's the problem, it is adressed already(since it will drop all items before gibbing).

**Comment by PKPenguin321** [comment]
@lzimann that same logic could be used for *not* making it gib people

**Comment by Cheridan** [comment]
What @Supermichael777 said

**Pull request closed without merging**
