### PR TITLE
Truly fixes plumbing rotation

### LINKED ISSUE #50350: Plumbing machines and issues with wrenching/rotation
image

Blue/red pipes don't properly line up graphically with where the game thinks they are. They also don't seem to be able to be rotated at all, sometimes with the machine permanently being stuck in a certain direction, while graphically the pipes/sprite moves fine.

Synthesizers get stuck in directions with specific chemicals, and also have issues with resetting their location after any chem change.

Chem tanks randomly get stuck with blue on left and red on right, regardless of being rotated graphically.

Filters have their left and right switched sometimes.

### PR DESCRIPTION
**Pull request by Time-Green**
Haha, april fools, you guys thought I fixed plumbing while in reality I broke it even worse!

closes #50350 

:cl:
fix: plumbing now properly rotates, I promise
/:cl:

I actually sat down and looked at the code this time instead of frantically changing stuff till it would start working

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
*sigh*

**Comment by ExcessiveUseOfCobblestone** [comment]
can you explain this fix

**Comment by Time-Green** [comment]
Fair enough.

Basically, the plumbing machinery would setup the ducts in the starting direction. Synthesizers would have blue ducts north, etc. They would visually spin with the machine because they're multi-directional sprites.

This was fine until I made it possible for the sprites to change by adding undertile functionality. If at that point I regenerated the icons, it would again draw the ducts. Problem is at this point the default directions could have been changed by turning around, so the blue synthesizer duct could instead be drawn to the west.

Problem is that west would then be the default direction, so the duct would now appear to be west when the machine was facing the front, instead of north. Codewise it would still think the duct was north.

The 270 was just complete nonsense, because during testing I always ended up with it being misplaced 90 degrees due to this visual duct bug.

This was fixed by just always taking the original duct direction, which would in this case be north. It would still visually spin with the machine to indicate a normal direction. 

Summary: coder forgot not to call a special function only made for first time use and then got confused, but has now fixed it to be sane and safe to call

**Comment by ExcessiveUseOfCobblestone** [comment]
Ok it makes sense now.

**Comment by ExcessiveUseOfCobblestone** [comment]
Gonna early merge since the recent PR broke it severely.

**Pull request merged**
