### PR TITLE
New captain PDA colors and PDA cases.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR adds in PDA cases and also a new color scheme for the captain's PDA since i am too lazy to make two PRs.

## Why It's Good For The Game

For the captain's PDA colors, thats because the original one looks awful.

As for the PDA cases... A new gimmicky item that can have use! You can find 10 of these at any cartridge vendor.

What is the speciality of PDA cases?
Panic at the N1
Lets say you are facing off agaisnt someone with less than 18 health and he has taken some hostages or whatever so you want to put him in critical condition. You have a cased PDA, so what do you do?

MEGAMAN, ATTACK!
They are now down for the count! Also the new captain's PDA color scheme is shown off here.

Also it doesnt actually make your PDA durable, i wanted to make it more durable but PDAs are actually invincible.
## Changelog
:cl:
add: New PDA cases have been added to all cartridge vendors! They are elephant resistant and very heavy! Ask your Head of Personnel for one today! Warning: PDA Cases do not work on WGW Series PDAs.
tweak: Nanotrasen have repainted the colors for Captain PDAs. They are now more vibrant.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
So all this is doing is adding a way to weaponize PDAs? What?

**Comment by LemonInTheDark** [comment]
I like the sprite, but the throwing effect bothers me a bit. The cap already has good methods of beating people up, floor tiles are a thing, and it doesn't really seem to serve any purpose. Can you elaborate on why you think it's a good addition to the game?

**Comment by necromanceranne** [comment]
Killing someone with a PDA is the equivalency of ending your opponent 'rightly'. Especially if you don't take your ID out first.

**Comment by rdragan** [comment]
I thought the plan was for tablets to eventually replace PDAs?

**Comment by CRITAWAKETS** [comment]
> I thought the plan was for tablets to eventually replace PDAs?
They dont currently and when they do, this can be ported to tablets.

**Review by Twaticus — CHANGES_REQUESTED** [review]
i dont like the PDA color changes. the goldish version feels more like a captain pda, this blue makes me think of the hop tbh. the case looks good though

**Comment by Tharcoonvagh** [comment]
The damage it deals is way too much, make PDAs unable to accept ids if in a case and we have a deal

**Comment by CRITAWAKETS** [comment]
in retrospect, this PR sucked

**Pull request closed without merging**
