### PR TITLE
[WIP]Removes the Syringe Gun.

### PR DESCRIPTION
**Pull request by Iamgoofball**
This is done.

### CODE REVIEW

**Comment by ShizCalev** [comment]
speedmerge

**Comment by ChangelingRain** [comment]
I don't remember if kor okayed this but if he did he should probably be the one opening the pr!
>Balance changes (there can be incidental balance changes from otherwise acceptable PRs, but no "I buffed tasers" or "I nerfed eswords"). This includes changes/balancing under the guise of reverts/removals. If you feel strongly that we absolutely can not wait to change X feature because it is making the game unplayable PM me and if I agree I'll open a revert.

**Comment by kevinz000** [comment]
btfo

**Comment by Fox-McCloud** [comment]
Dunno if they should be removed completely, but making them traitor-only would be a good start.

Also, if this is being done, shotun darts would also have to be removed/made traitor only.

**Comment by FantasticFwoosh** [comment]
- Wear a suit or nerf syringe projectiles instead or something, we can already produce piercing syringes with RnD which bypasses the syringe gun altogether.

- Goof rolls wizard because we know from the amount of PR's he puts out, it must be his favourite mode, gets knocked out by choral hydrate syringe. GG. Nerf.

**Comment by Iamgoofball** [comment]
My connection logs prove i haven't played in months, suck it

**Comment by YakumoChen** [comment]
why do you think it warrants removal then

**Comment by Iamgoofball** [comment]
Because it makes weeb trash like you angry.

**Pull request closed without merging**
