### PR TITLE
Colossus chest ignores colossus bolts

### LINKED ISSUE #44030: Megafauna continue their current attack cycle after death

### PR DESCRIPTION
**Pull request by 4dplanner**
## Why It's Good For The Game
Colossus can smash its own chest with some projectile lag, destroying all its loot
fixes #44030

## Changelog
:cl:
tweak: colossus chest is intangible to colossus bolts
/:cl:

### CODE REVIEW

**Comment by 4dplanner** [comment]
Technically abusable to take out a second colossus, will have to change

**Comment by Daxxed** [comment]
Have it only be indestructable for a limited time, or apply this to the loot inside the chest instead?
Anomaly crystals and blaster tubes have this already, why shouldn't VoG ?

**Comment by Whoneedspacee** [comment]
or make it so when it’s destroyed it dumps its loot instead of deleting it

**Comment by 4dplanner** [comment]
> or make it so when it’s deconstructed it dumps its loot instead of deleting it (contents forcemoved to turf)

I don't think colossus should be trashing its own chest at all, if only for aesthetic reasons. I've had it pointed out to me that this doesn't allow for anything the crystal didn't already, but I'll probably make the invulnerability to colossus bolts only last for a few seconds tomorrow anyway.

**Comment by 4dplanner** [comment]
> or make it so when it’s deconstructed it dumps its loot instead of deleting it (contents forcemoved to turf)

just to clarify, the problem isn't chest deleting in general deleting contents, it's just colossus bolts in specific. This is because they call ex_act, which destroys contents.

(warning: I haven't actually checked this, might be wrong)

**Comment by Whoneedspacee** [comment]
you could probably still make it so they just move out of the chest

also how are you causing these issues i’ve never once had the colossus chest break on me and yet you seem to be finding these problems on speeddial i am genuinely interested

**Comment by Daxxed** [comment]
You should have more kills than me so I am honestly surprised this is the first you heard of it

**Comment by Whoneedspacee** [comment]
i can only assume the specific way i fight means that i don't uncover these issues, like the ones for drake i guess. i fight pretty consistently every time.

**Comment by 4dplanner** [comment]
> i can only assume the specific way i fight means that i don't uncover these issues, like the ones for drake i guess. i fight pretty consistently every time.

Maybe you just only fight them on low TiDi servers? This bug only comes up at high lag, when the crate can spawn inside a projectile.

**Comment by 4dplanner** [comment]
Anyway, switched to force pierce, which has (I think) only one fun abuse

**Comment by Daxxed** [comment]
Anomalous crystal blocks deathbolts too, so this is fine.
I can reproduce this with 0 lag on localhost consistantly whoneedspace.
Set the megafauna two hits from death, shoot it to aggro and then finish it just as it starts a new attack ( colossus spiral, drake’s final attack )

**Pull request merged**
