### PR TITLE
Adds mutagen dispenser, grinder, and toolbox to seed vault

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**

### CODE REVIEW

**Comment by Lumipharon** [comment]
kor they need a brewmaster (same as botany) to let them extract specific chems from plants.
this also would let them create their own mutagen with the right plants, which would remove the need for the magic mutagen dispenser (if you wanted to).

**Comment by Lumipharon** [comment]
RIP.

**Comment by KorPhaeron** [comment]
@Lumipharon 

Soon(TM)

**Comment by Lumipharon** [comment]
Well technically they can still make mutagen with just the grinder, it will simply be diluted with nutriment and ammonia (which is good), but also probably a bit of radium/phosphorus (which is eh), or chlorine (which is very bad).

**Pull request merged**
