### PR TITLE
Reverts a check added in `[NO GBP] Fixes drone toolbox issues`, fixes clothing unequipping, unit test

### LINKED ISSUE #87129: Items in slots wont drop after unequipping clothing
### Client Version:

515.1643

### Issue Summary:

Roundstart, and for the rest of the round, after i unequipped a jumpsuit, i didnt drop items on my id and belt along with pockets

### Round ID:

[240028](https://scrubby.melonmesa.com/round/240028)

### Test Merge Information:

_No response_

### Reproduction Steps:

1. spawn
2. take off jumpsuit
3. items equipped dont drop

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Fixes #87129

[This change](https://github.com/tgstation/tgstation/pull/87073/files#diff-c8ab5fbc20de60e202b839834b039649cbb69a1c4b99b27a5e467f3889442ccd) added in #87073, passing `invdrop = FALSE` to `doUnEquip`, breaks the behavior of unequipping dropping your items. Because that's what `invdrop` does. If you pass it as `FALSE` it prevents other items from dropping off the mob, intended for like, outfit use / "quick swapping" an item out

So I reverted it. Drone tools still seem to work I guess. @SyncIt21 

## Changelog

:cl: Melbert
fix: Fixes stuff staying on your body after removing your clothes
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
I thought the var wasn't used anywhere so I set it to true just for drone code which was my bad. I needed a way to check if we were temporarily unequipping the item when switching that item between hands so `datum/component/holderloving` won't block that unequip(which would block our ability of switching the item between hands)

You can see the intention behind the [name](https://github.com/tgstation/tgstation/pull/87073/commits/dd7ee6c7e175f601477f137b9768a29d308cd91e) of the commit itself.

With this change you won't be able to swap a drone tool between hands so yeah a better solution is much appreciated

**Comment by MrMelbert** [comment]
I'd help find an alternate solution but to be honest I don't know what the purpose of `/datum/component/holderloving/proc/no_unequip(obj/item/I, force, atom/newloc, no_move, invdrop, silent)` is. 

I changed it to check for `no_move` (which is a var set in temp removal) and now it never returns `COMPONENT_ITEM_BLOCK_UNEQUIP` but seems to work fine (you can swap items across hands, you can drop to move to storage)

**Comment by MrMelbert** [comment]
In any case I don't know exactly what I'm supposed to be fixing about drones so I suggest you write a few unit tests, so I can know if I'm breaking something or not

**Comment by SyncIt21** [comment]
> I'd help find an alternate solution but to be honest I don't know what the purpose of /datum/component/holderloving/proc/no_unequip(obj/item/I, force, atom/newloc, no_move, invdrop, silent) is.

So stuff like camera assemblies use the proc `temporarilyRemoveItemFromInventory()` to check if we can remove an item like a gas analyzer from a players hand so as to install the x ray upgrade.

We don't want this for drones because their gas analyzer is inbuilt as in cannot be removed so this component blocks the removal by overriding the signal which is called by the above mentioned proc which is it's whole purpose.

Since you can swap the item between hands make sure to last check if we can install the gas analyzer  from drone tools in the camera frame(which should fail for drones). 

If that passes then we're good

**Comment by MrMelbert** [comment]
That's still an issue, but you should definitely write some unit tests fort his

**Comment by MrMelbert** [comment]
#87138 Lol... I think we need to go back to the drawing board on drones anyways

**Comment by SyncIt21** [comment]
The long term solution is to merge `temporarilyRemoveItemFromInventory` with `transferItemToLoc` by adding an additional arg for `no_move`. Probelm is `temporarilyRemoveItemFromInventory` always sets `newloc = null` so we don't know in what context this proc gets called(are we switching the item between hands or moving it into another atom? no clue).

If we use `transferItemToLoc` but with pass `no_move = FALSE` and ensure `newloc` is never null then we can know what are planning to do with the item and this will be an easy fix.

Just putting my thoughts here cause i beleive `temporarilyRemoveItemFromInventory` is redundant

**Comment by MrMelbert** [comment]
> The long term solution is to merge `temporarilyRemoveItemFromInventory` with `transferItemToLoc` by adding an additional arg for `no_move`. 

I would say rather than merge them, you would just have a separate proc - Maybe call it `prepare_move_to_loc` - which is "`transferItemToLoc` but it doesn't do the transfer". 

(To the feature coder, all these boolean args are nonsense, so requiring people pass `no_move = TRUE` would get messy and break things.)

This proc would essentially just be `temporarilyRemoveItemFromInventory` but has an argument for denoting the new loc (so we can get context for things like the signal).

**Pull request merged**
