### PR TITLE
aclap emote

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request
aclap emote

## Why It's Good For The Game

fun new emote

## Changelog
:cl: cacogen
add: *aclap
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
lgtm, ship it

**Comment by Ryll-Ryll** [comment]
came for the angry clap

stayed for the ass clap

**Comment by tralezab** [comment]
i'm just gonna save everyone the trouble one of these days and make an emote called *roleplay that makes you do every single emote in the game, at once AND YOU'LL ALL EAT IT UP

**Comment by ATH1909** [comment]
speedmerge

**Review by Tlaltecuhtli — APPROVED** [review]

**Comment by trollbreeder** [comment]
0/10 not babbaboey

**Comment by optimumtact** [comment]
thomas had never seen such bullshit before

**Pull request closed without merging**
