### PR TITLE
Fixes TK headbutts

### PR DESCRIPTION
**Pull request by PKPenguin321**
Fixes https://github.com/tgstation/tgstation/issues/22998

Only like 85% sure this will work since I'm not sure how TK handles Adjacent()

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Oh shit I'm sorry

**Comment by PKPenguin321** [comment]
Sorry for what?

**Comment by AnturK** [comment]
So did you test it ?

**Comment by PKPenguin321** [comment]
Full disclosure no
I'll do it today

**Comment by PKPenguin321** [comment]
Oh well that works too

**Pull request merged**
