### PR TITLE
Nuka Cola causes irradiation

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Nuka Cola now causes irradiation. 

## Why It's Good For The Game

Most of our speed bonuses, such as Methamphetamine, comes with a downside (the usual one being brain damage), because speed is king. 

When you give people a speed boost that comes with absolutely NO downsides outside of visual, it turns out people abuse it, a lot. 

Even a small speed boost ends up being abused.  It is not uncommon to see security officers saddled with two, three bottles. Nor is it uncommon to see tiders use it to escape said officers, or antags to escape said tiders. Do you see the problem here? It has become a situation where not having it puts you at a disadvantage, which is sad. 

Irradiation fits thematically, too. And it also shows you when someone's using it, since they start glowing green. 

## Changelog

:cl: Melbert
balance: Scientists have discovered Nuka Cola is not good for short term health. 
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
i always thought the downside of nuka cola was it being psycaledic, so your screen gets all wonky so its hard to use it in combat

**Comment by GuillaumePrata** [comment]
Doing stamina damage to a cap would make it quite interesting balance for combat IMO, without removing a fun niche of just being fast for mining, getting to the evac shuttle or whatever else people use it for.

You get faster, but it is easier for disablers and other stamina weapons to get you down.

**Comment by moocowswag** [comment]
I thought the downside was the cost, imo nuka cola could use a slightly higher price as a premium drink, money could do with being alittle bit more valuable for stuff like that.

**Comment by K4rlox** [comment]
@MrMelbert heres my suggestion due to it being nuka cola
(fallout i think?)

make it irradiate and toxin when drunk a bit

**Comment by MrMelbert** [comment]
Irradiation sounds funni, Stamina will be hard to do without completely negating the speed up

**Comment by celulamp** [comment]
"NO downsides outside of visual" not being able to tell what is going on and your screen shaking all the time is def enough of a downside.

**Comment by MrMelbert** [comment]
If you can't tell what's going on through a mild screen shake Idk what to tell yo u

**Comment by GuillaumePrata** [comment]
You don't need to tell what is going on perfectly when your goal is to just run away from security too.

**Comment by Fikou** [comment]
your pr doesnt cause nuka cola to do brain damage

**Comment by MrMelbert** [comment]
this guy didn't even read the pr body

**Comment by Fikou** [comment]
idiot

**Comment by MrMelbert** [comment]
Just for fun, here's a list of drink purchases from the soda vendor over the past year 

image

**Comment by K4rlox** [comment]
> Irradiation sounds funni, Stamina will be hard to do without completely negating the speed up

after this PR gets merged, thinking of adding several nuka cola subtypes for bartenders to use too

(like nuka quartz and nuka quantum)

**Comment by jughu** [comment]
personally i think nuka cola should speed ip crafting instead of speed considering how much speed increasing things we have already

**Comment by CCC23** [comment]
:(

**Comment by moocowswag** [comment]
> The cost wouldn't work well as a stop gap, not only because money is mostly meaningless, but also because it is trivial to make a lot of nuka cola, space cola and uranium is a tier 1 recipe.

oh i thought it was a premium drink with a hidden recipe owned by the company selling it, time to make it every round along with grey bull.

**Comment by Dawnseer** [comment]
Radioactive resonance enjoyers keep winning

**Comment by Pickle-Coding** [comment]
Seems cool, though sadly it is incredibly easy to heal radiation now.

**Comment by jughu** [comment]
> Seems cool, though sadly it is incredibly easy to heal radiation now. It might not have a significant impact against giga tiders.

Same could be said about meth, you need mannitol to counter the irridiation its just pretty much adding a step for inconvience still usable but it can backfire eventaully

**Comment by Sakamoto4ka** [comment]
Good night flukie cola

**Pull request merged**
