### PR TITLE
Adds 2 weapons to the armory

### PR DESCRIPTION
**Pull request by Shadowlight213**
The security temperature gun!
I saw this on birdboat and found it absolutely hilarious.
Security temperature gun has a firing pin and lowered tech levels to keep rnd balance.

:cl:
add: Security has two new weapons in their arsenal. The security temperature gun, and the DRAGnet capture and recovery system.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
completely unbalanced.

**Comment by Kromgar** [comment]
I... Is the temperature gun still a thing?

It never worked it was shit

**Comment by NocturnalQuill** [comment]
Literally a worse version of the disabler. You are retarded if you think this is op.

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/tgstation/issues/11017 never forget

**Comment by Archie700** [comment]
anyone remember the reworked temp gun pr

rip buggy taken too soon

**Comment by Jordie0608** [comment]
I think these should be left to RD lest someone actually try to use it.

**Comment by Firecage** [comment]
Honestly? You don't even need to add a firing pin to this. You can even have 100 of them spawn. Not like it will affect anything.

**Comment by Shadowlight213** [comment]
When the slimepocalypse happens and they are immune to your lasers, you'll change your tune.

**Comment by PKPenguin321** [comment]
Dragnet?

**Comment by PKPenguin321** [comment]
Woah there that was sneaky

**Comment by Jordie0608** [comment]
It's Cheridan's birthday

**Pull request merged**
