### PR TITLE
Adds maint oddities, small adjustments to loot tables

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Finally makes use of the oddities list from #47646. These are very rare (1:10000) per maint loot spawn. This list is still a bit small, more specific items will hopefully be made and added as time goes on.
Repathed die of fate slightly, and added a stealth cursed version.
Reduced the overall amount of strange items, it was a bit high.

## Why It's Good For The Game
Provides some motivation to go digging through maint loot, and should hopefully make for some fun experiences.

## Changelog
:cl: Skoglol
add: Maint loot table has been adjusted, may now contain some special stuff. Get hunting!
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
time to start rolling every die i find in maint

**Comment by necromanceranne** [comment]
Unironically the reactive table armor is insanely powerful, as much as the reactive teleport armor is. The only difference between them is the meme tabling. It is otherwise a complete attack dodge and teleport and will save your ass. I've used one this christmas to fight wizards and demons to considerable success and found no difference between it and teleport armor in usefulness.

**Comment by ATH1909** [comment]
Won't 1:10,000 odds make this stuff a bit... _too_ rare?

**Comment by Jalleo** [comment]
@ATH1909 its PER spawner.  there are more than twenty on a map.

**Comment by Fikou** [comment]
why not add a crayon rune to the fakeout list

**Comment by MrDoomBringer** [comment]
@Jalleo thats still saying theres a 0.002% chance of this happening on a single round, which seems way too low

**Comment by kriskog** [comment]
Metastation has around 200 loot spawners, so there is about a 1:50 chance of either one of these showing up somewhere in maint. Around the same as the xeno egg in xenobio.

**Comment by cacogen** [comment]
why do we add fun things that are then never seen by most people

**Comment by optimumtact** [comment]
perfectly happy with these spawn chances.

Oddities should be just that, oddities that occur one round in 40

**Comment by improvedname** [comment]
Remember that lizard janitor you used to bully midshift?
Well he found a d20 rolled a 20 and now is a lv 10 magician whos out for your ass

**Comment by improvedname** [comment]
@necromanceranne can't you just counter the table armour with well... glass tables?

**Comment by necromanceranne** [comment]
@improvedname it spawns a table.

**Comment by kriskog** [comment]
Reminder that the teleport armor is available every round if you take down the head nerd and doesnt cause any major issues :slightly_smiling_face:

**Comment by Shadowflame909** [comment]
Can I get an uh currently unobtainable wrestling belt

or meteor pen

**Pull request merged**
