### PR TITLE
Create hello there friend in deadchat

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
#48006 must live on. I have most likely somehow stuffed up here. 
## Why It's Good For The Game
you seem to be having a good round on ss13

### CODE REVIEW

**Comment by optimumtact** [comment]
no

**Comment by PepperPrepper** [comment]
aw what? why not? We've had code jokes in the past. Take a look at the ban hammer.

**Comment by PepperPrepper** [comment]
This is a one in one million chance.

**Comment by PepperPrepper** [comment]
@optimumtact Looks it's fine that you closed it. I know it's not that funny. But I'd just like to know exactly why you closed it.

**Comment by PKPenguin321** [comment]
Kinda dumb and I'm not sure that prob takes non-int values

**Comment by PepperPrepper** [comment]
@PKPenguin321 
Well I stole the prob from the pulse rifle chance so I'm fairly sure it works. And yeah it is dumb but I figured since it would never ever happen it would be pretty fine.

**Pull request closed without merging**
