### PR TITLE
Fixes drunken scientist R&D point gain.

### PR DESCRIPTION
**Pull request by AnturK**

### CODE REVIEW

**Comment by Time-Green** [comment]
Can we perhaps change drunk scientists telephaticly siphoning research with alcohol? Limit it to scientists doing RnD?

**Comment by Iamgoofball** [comment]
No, get good.

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Is add_points_all even the right call to be making here? If another point type was actually added, should getting drunk benefit it?

**Comment by AnturK** [comment]
Good point, should probably be just R&D from now on.

**Comment by Iamgoofball** [comment]
Yes, adding all points was intentional.

**Pull request merged**
