### PR TITLE
completely normal delta station absolutely nothing was changed about it i swear

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
nothing was changed about delta this pr is a lie and a mere figment of your imagination

## Why It's Good For The Game
it's definitely not

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
Right

**Comment by itseasytosee** [comment]
Funny

**Comment by nullAdept** [comment]
at least it's not cockvore

**Comment by Paxilmaniac** [comment]
gamer time

**Comment by Paxilmaniac** [comment]
ok bye

**Comment by Paxilmaniac** [comment]
it was too immersive

**Comment by Paxilmaniac** [comment]
ok bye again

**Comment by Paxilmaniac** [comment]
I SWEAR it's fixed this time

**Comment by Paxilmaniac** [comment]
i hope i never have to mess with this again

**Comment by davethwave** [comment]
This is great.

**Comment by MrDoomBringer** [comment]
Players seem to really love this map, myself included.

**Comment by Exavere** [comment]
Map is very epic.

**Comment by davethwave** [comment]
Something to consider is to make this a 1/100 chance kinda thing that can happen naturally or have it as an admin only thing. Would be awesome to be able to deploy this now and then.

**Comment by ATH1909** [comment]
What is this PR, by the way?

**Comment by ATH1909** [comment]
Wait, is this a Syndicate station?

**Comment by ExcessiveUseOfCobblestone** [comment]
what is wrong with you

**Comment by Paxilmaniac** [comment]
Why everyone is commenting on a closed pr that changes absolutely nothing about delta is extremely strange

**Comment by Paxilmaniac** [comment]
anyways arm wanted me to fix some of this stuff

**Comment by Paxilmaniac** [comment]
ok bye again

**Comment by Paxilmaniac** [comment]
didn't I say I never wanted to touch this again

**Comment by Paxilmaniac** [comment]
Don't get your hopes up

**Comment by Fikou** [comment]
stfu

**Comment by Paxilmaniac** [comment]
ok I SWEAR this is the last time I'm changing anything about this

**Comment by Paxilmaniac** [comment]
ok bye bye

**Comment by Paxilmaniac** [comment]
open

**Comment by Paxilmaniac** [comment]
close

**Comment by spessbro** [comment]
good pr

**Pull request closed without merging**
