### PR TITLE
Use a more common documentation block standard.

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

Related to #54604.

I propose use of a more common standard of documentation blocks instead of what we currently use. This new style of documentation block will allow easy adaptation of third-party documentation plugins for VSCode, because all common languages use this particular style of docblock, e.g. C, C++, C#, Go lang, Java, JavaScript, CSS, PHP... you name it.

DM shouldn't be a snowflake in that regard and adopt a proper standard.

[Auto Comment Blocks](https://marketplace.visualstudio.com/items?itemName=kevinkyang.auto-comment-blocks) - Reference VSCode Extension

demo

## Good

```
/**
 * This proc adds two numbers together.
 *
 * Arguments:
 * - a - first number
 * - b - second number
 */
```

## Bad

```
/**
  * This proc adds two numbers together.
  *
  * Arguments:
  * - a - first number
  * - b - second number
  */
```

## Very Bad

```
/*
  * This proc adds two numbers together.
  *
  * Arguments:
  * - a - first number
  * - b - second number
*/
```

### CODE REVIEW

**Comment by Cyberboss** [comment]
Depends on SpacemanDMM

**Comment by SpaceManiac** [comment]
dmdoc should currently be supporting both "Good" and "Bad" equivalently, while "Very Bad" would not be recognized as a doc comment because it does not start with `/**`. Please provide details if this is not the case.

**Comment by stylemistake** [comment]
@SpaceManiac it's from recent PR that adds double spaces to all comments, including those that are not dmdoc, which results in this horrid format.

https://github.com/tgstation/tgstation/pull/54604/files#diff-6771f60655d59d0d4166df815c0b400bd37d7ef6124d4bafe26ffef293ab9a34R50-R67

**Comment by MCterra10** [comment]
You might even say there was a... style mistake

**Comment by optimumtact** [comment]
seems fine I guess

**Comment by spookydonut** [comment]
i prefer what you label as bad because it lines up the asterisks

**Comment by Rohesie** [comment]
Sharing the standard with most common languages is positive and good enough on its own.
Other than that, no reason to prefer one way or the other, so why not?

**Comment by stylemistake** [comment]
I'm not saying we should bulldoze all docs to use one standard, I just want to update the standard and to have legal leverage to stop tivi from ruining the codebase.

**Comment by spookydonut** [comment]
> 
> 
> I'm not saying we should bulldoze all docs to use one standard, I just want to update the standard to something better and to have some legal leverage to stop tivi from ruining the codebase.

He's just copying my regex from tgmc where there were more comments formatted like that than not and it also just made the regex easier.

**Comment by SpaceManiac** [comment]
> to have some legal leverage to stop tivi from ruining the codebase

dude, just say no

**Comment by Cyberboss** [comment]
image

**Comment by spookydonut** [comment]
@tgstation/commit-access someone make a decision on this

**Comment by Jared-Fogle** [comment]
i like it

**Pull request merged**
