### PR TITLE
Lava slowdown

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

Changed lava slowdown to be greater then cuffed legs, but less then cuffed and chained legs.
Ash drake uses a different lava that has the old slowdown.

## Why It's Good For The Game

We move through lava way to fast, lava is a thick sticky liquid more like tar, you should move very slowly though it.
This should stop people from escaping the gulag by running through lava and using water to put out the fire after. (I did not test this)

## Changelog
:cl:
balance: lava slowdown increase
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
This makes making a mistake on the ash drakes lava pool move a death trap.

No.

**Comment by nightred** [comment]
I hear the issue with the ash drake, would it not actually mean the fight is harder and a better fight if the lava is far more deadly?
But how is this the drake now uses a special lava floor that has less slow down (same as before)

**Comment by nightred** [comment]
The Why is because someone was complaining that gullag people can run over the lava take damage and use water to put themself out, and escape.

**Comment by MonkyCocc** [comment]
The ash drake fight gives some really good shit, mad that you're gonna have to try a little bit harder?

**Comment by OverlyGeneric** [comment]
cool beans.

this will be helpful for quicksand tiles too.

**Comment by Shadowflame909** [comment]
MonkeyExplexitive thats like saying

"Just dont get hit bro"

You have to have room to err. Otherwise whats the point of even having healing items

**Comment by nightred** [comment]
The ash drake was changed to use a new lava tile that uses the old slowdown.

**Comment by Fikou** [comment]
> The Why is because someone was complaining that gullag people can run over the lava take damage and use water to put themself out, and escape.

this is very hard to do because after you cross the river from the damage you dont have any time to spare and need to rush to find a fire extinguisher in the mining station and theres a chance that the mining shuttle will be there which completely makes you unable to escape, also there are easier gulag escape ways, just widen the gap by 1 block if anything

**Comment by nemvar** [comment]
>This PR would have essentially doomed the sec officer to a lavaland Z-Level admin prison and thats not right.

Don't get gulagged. I don't see how this is different from getting thrown into space.

**Comment by carlarctg** [comment]
damn this is so realistic, this will immerse me further into the game! i love it

lavaproof armor now worthless as lava slows you down

shitting on a cool gulag escape method? genius. really should just make it so that if youre outside the gulag you should be gibbed instantly tbh

**Comment by wesoda25** [comment]
> lavaproof armor now worthless as lava slows you down

It makes you not die from lava ???

> shitting on a cool gulag escape method? genius. really should just make it so that if youre outside the gulag you should be gibbed instantly tbh

What if, WHAT IF, you maybe... AREN'T supposed to escape from gulag? Crazy idea I know....

**Comment by itseasytosee** [comment]
> What if, WHAT IF, you maybe... AREN'T supposed to escape from gulag? Crazy idea I know....

Mordern problems require modern solutions

**Comment by Shadowflame909** [comment]
Why should anything that isn't admin prison be unescapable?

**Comment by carlarctg** [comment]
you're right wesoda, that's why i specified that we should just make it so that leaving the gulag gibs you instantly, because doing otherwise would be leaving a glaring hole in the gulag's security, and we can't have that!
there is no concievable reason anyone could ever justify gulags NOT being 100% escape-proof!

perhaps we can make it so that the gulag is surrounded by admin walls? surely that'd be a simpler alternative to your genius goal

**Comment by jacklecroy** [comment]
> This should stop people from escaping the gulag by running through lava and using water to put out the fire after. (I did not test this)

They removed water from the vending machines, so I don't think it's possible to do this without help. Even for a max sentence, mining isn't that hard, and you don't come back a fugitive. If this is your main reasoning behind the slowdown, I think that it's silly.

**Comment by SpinnerMaster** [comment]
If you escape the gulag like that, and you somehow manage to get to the station and get through cargo (all without an ID that has any access mind you), you are still on the status "incarcerated" and any braindead security officer will beat you and drag you back to the brig once they notice you are gone. Beepsky will beat you. AI will trap you. 

This is a bad PR, just add one more square of lava 🤣

**Comment by Shadowflame909** [comment]
>This is just like space bro

Senior Code Janitor knows cloning will be removed, and already wants more methods of permanent round removal. Oh boy.

I sincerely hope you thought about the major effect of all lava suddenly having a nigh-paralysis slowdown.

You've just made Fire-Fighters useless.

Ash-Drake armor can no longer allow you to traverse lava.

Goliath Boats and the boats you can get from the necropolis tendril are useless.

In an attempt to go "gulag escape bad" you've literally made 75% of LAVA land untraversable!

Don't even get me started on how this changes the dynamic of the Legion Fight.

**Comment by improvedname** [comment]
The thing about escaping gulag is that YOU dont need an fire extinguisher you can make a sink with any type of material which is an infinite water source

**Comment by HomocidlePancakes** [comment]
Might as well replace lava with chasms.

**Comment by JMoldy** [comment]
Leave normal lava alone and make the ash drake's lava use this.

**Comment by TheMidnightRose** [comment]
> > This is just like space bro
> 
> Senior Code Janitor knows cloning will be removed, and already wants more methods of permanent round removal. Oh boy.
> 
> I sincerely hope you thought about the major effect of all lava suddenly having a nigh-paralysis slowdown.
> 
> You've just made Fire-Fighters useless.
> 
> Ash-Drake armor can no longer allow you to traverse lava.
> 
> Goliath Boats and the boats you can get from the necropolis tendril are useless.
> 
> In an attempt to go "gulag escape bad" you've literally made 75% of LAVA land untraversable!
> 
> Don't even get me started on how this changes the dynamic of the Legion Fight.

What does it do to affect the Legion Fight? I usually create myself a loop to fight them with. 

But yeah, honestly gulag is still easier to escape if you know how to mine at all since you know, gulag rocks still have gibonite, three to five gibonite at react 3 or 4 can bust you into the main mining areas, which dont have any access requirements and you can use the public shuttle to get back. 

Just add more lava between the mining dock and the gulag, theres like six spots where there is only two tiles of lava for them to cross and all it requires is a few minutes of mining.

**Comment by Tlaltecuhtli** [comment]
death stranding reference?

**Comment by improvedname** [comment]
Ash drake never allowed you to traverse lava tho??? Just make and rcd in that case

**Comment by Shadowflame909** [comment]
What if you just quit breaking 70 of lavalands features to make one imprisonment method more inescapable. This shit doesn't stop at gulag and lava paralyzing you is very very very wack.

I'm not comprehending why anyone who isn't trolling would want that. If you think mining is too unbalanced so they deserve the instant death, your the reason the anty keeps being upped instead of stabilized back to on station levels.

**Comment by improvedname** [comment]
No gulag should be punishing. And not escaple by digging 1 sand and making a sandstone toilet and crossing 2 lava tiles its currently less punishing then the current brig cell timer.

If it was with gibnonite exploding into public mining i would say smart thinking creative and requires effort to get the gibnonite

But just a sink out of 1 mat then crossing over lava no risk attached is stupif

**Comment by Shadowflame909** [comment]
>Gulag is too easy to escape because an infinite sink exists
I know let's just make stepping in lava a guaranteed death.

This doesn't fix the issue of gulag being easy to escape, and it makes everything worse for miners by making fire extinguishers due

**Comment by Shadowflame909** [comment]
Im baffled at how little this PR gets anything done other then breaking lavaland functionality.  You are making fire extinguishers useless. You are gaining....

The knowledge that maybe crafting infinite water is broken. Here's a better idea. Remove sinks or a mortars from the crafting menu instead of breaking a decades worth of mining code for grudgecode that won't even do its intended goal thanks to gibonite.

Crazy man. Absolutely bonkers.

**Comment by Taylorkills2** [comment]
This is an annoying change since flying and floating over lava still applies the slowdown.

**Comment by Tharcoonvagh** [comment]
Just widen the gulag lava brook

**Comment by improvedname** [comment]
Oh wait i just realised he made slowdoen 10 thays crazy 3-4 suffices

**Comment by kopoba** [comment]
maybe just make that lava gib you on touch? not a big difference after all

**Comment by nightred** [comment]
This was never a real good idea and we all know it, but it shows that this is a bad fix for gulag escape, also nothing should be forever escapable.
Sinks and toilets could be fixed to prevent being used outside of a room with an APC or something, this is just not the right move.

**Comment by Qustinnus** [comment]
it's cool i'll re-open this and dab on shadowflame

**Comment by improvedname** [comment]
@nightred nooo good prrr

**Pull request closed without merging**
