### PR TITLE
Stock Part Resprite

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Resprites stock parts to bring them up to date, changes manipulators to servo motors as I couldn't make manipulators work well at this scale.

image
(Power cells sold separately)

## Why It's Good For The Game

The old stock parts are dated, in some cased quite ugly, and in the case of manipulators a ball of assorted pixels. Incidentally removed a couple of single letter var names.

## Changelog
:cl:
image: Stock parts have been resprited.
code: Manipulators have been renamed to servo motors, all related types have been repathed to match.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
Better than the current, but there should be more visual difference between 1,2 (2 looks like just 1 laying on a side) and 3,4 (They seem like the same thing but of a different scale)

**Comment by JohnFulpWillard** [comment]
I can't tell which is what, is there any way we can make them more visually distinguished? Ex: Matter bins can look more bin-like

**Comment by Overuseddart** [comment]
> I can't tell which is what, is there any way we can make them more visually distinguished? Ex: Matter bins can look more bin-like.
> 
> The first 3 all look like they can be lasers to me

All of the old sprites (besides the matter bin and cell) were hard to tell what they were as well. You probably just got used to the sprites and memorized which is which, which would happen for these sprites as well.

**Comment by Thunder12345** [comment]
> (Although the first 2 look almost exactly alike)

Updated the pattern on the capacitors to make them more distinct from lasers
image

**Comment by MTandi** [comment]
> All of the old sprites (besides the matter bin and cell) were hard to tell what they were as well. You probably just got used to the sprites and memorized which is which, which would happen for these sprites as well. (Although the first 2 look almost exactly alike)

The old sprites were easier to differentiate except for the tier 1 capacitor and scanning module. These, on the other hand, while looking better, are objectively hard to differentiate even for someone unfamiliar with SS13.

Also it's not good that the same tier parts have identical color scheme. Imagine a pile of T4 parts lying on a table, It will be just a bunch of blue, orange and gray pixels. In this aspect the current parts are even better.

**Review by Mothblocks — APPROVED** [review]

**Comment by Jolly-66** [comment]
FINALLY some good fucking food

**Comment by Dorsisdwarf** [comment]
If you're gonna go with "The sprites dont matter actually because you never see them outside of an RPED" then what's the point of the PR?

Or for that matter why bother changing the name of femtomanips to femtoservos when the new icon doesn't look like either?

**Comment by TheVekter** [comment]
I do agree with John here, I kinda wish the matter bins looked more like a container for things to hang out in so they're easier to distinguish at a glance. Otherwise these sprites look great.

**Comment by CRITAWAKETS** [comment]
The color palettes should really be looked at, so far 17/25 stock parts have yellow as a major color (ignoring power cell states), and a few more also have yellowed pale parts.

**Comment by Or-Fi-S** [comment]
> image

the tier 4 sprite's animation still uses the old design for most frames

**Comment by TheVekter** [comment]
> The color palettes should really be looked at, so far 17/25 stock parts have yellow as a major color (ignoring power cell states), and a few more also have yellowed pale parts.

I'm not really seeing why this is an issue?

**Comment by Mothblocks** [comment]
> If you're gonna go with "The sprites dont matter actually because you never see them outside of an RPED" then what's the point of the PR?

Because nobody said "never"--I said that being able to distinguish several parts scattered on a table is not as important as being able to easily distinguish tiers, which is still true

**Comment by Mothblocks** [comment]
Also seeing them inside an RPED is still seeing them?

**Comment by Wallemations** [comment]
> > If you're gonna go with "The sprites dont matter actually because you never see them outside of an RPED" then what's the point of the PR?
> 
> Because nobody said "never"--I said that being able to distinguish several parts scattered on a table is not as important as being able to easily distinguish tiers, which is still true

Another important thing to take into consideration is that this makes it WAY easier to click on things like manipulators, which is a great thing. I HATED trying to grab those little bastards.

**Comment by Farquaar** [comment]
Looks good, except I feel like the bins could look more like bins. The new bin sprites kind of look like wall adapters.

**Comment by MTandi** [comment]
On top of the common suggestion to make bins look more like "bin" can you please consider making capacitor and servo look a bit more different from laser?

Like making capacitor more square, and adding an axle for the servo motor? Excuse my draft.

image

**Comment by zxaber** [comment]
I appreciate the clickability of these sprites. 

For the servos, you could do "micro-precise servo" and "nano-precise servo".

**Comment by BlueMemesauce** [comment]
That makes sense. Well there's no need to actually put the word precise I was just wondering what it would mean for a servo but that would make it less readable. Maybe it can be put in the description though

**Pull request merged**
