### PR TITLE
Polymorph belt blacklists several biotypes instead of allowing only organics

### LINKED ISSUE #77756: polymorphic belt thing can't scan some things that it seems like it should be able to
Reporting client version: 514.1589

## Round ID:
[212897](https://scrubby.melonmesa.com/round/212897)

## Testmerges:
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [MODLink System (+ NWTLMM)](https://www.github.com/tgstation/tgstation/pull/77639)
- [Revert "Edits a proc from dynamic.dm to use the actual cumulative formula of the Cauchy-Lorentz distribution."](https://www.github.com/tgstation/tgstation/pull/77728)

## Reproduction:
image
couldn't scan this thing while alive or dead, and previously in the round I couldn't scan an adult slime

### LINKED ISSUE #78227: You can turn everyone into lings using the Polymorph Belt
## Testmerges:

Reported from downstream: https://github.com/Bubberstation/Bubberstation - Reproduced on upstream

## Reproduction:

- Find a dead head slug from a ling. Doesn't matter if it was successful or not.
- Scan it. Inject the egg into a corpse. Kill yourself (without suicide verb). Sit in your corpse
- Wait 4 minutes
- Congratulations. You're now a changeling.

Did I mention that someone can pull the polymorph belt from your body and repeat the process?

### PR DESCRIPTION
**Pull request by Sealed101**
## About The Pull Request

Title; this makes the belt able to morph into _more_ mobs, but _less problematic/abusable_ mobs hopefully. It still only functions on basic/simple_animals, however.

~~Headslugs get a `MOB_UNDEAD` bioflag to prevent morphing into them completely. Though catching a sentient ling slug and morphing everyone into it is funny, it's only funny the first 5 times someone does it. (disclaimer: this is an approximation, i did not actually see a polymorph belt in-game because i currently play miner and like 10 games a week tops)
Arguably, this isn't ideal, but it's the closest we get unless we rename `MOB_EPIC` or something into `MOB_SPECIAL` and let that one be the go-to bioflag for mobs we don't want **fun** things happen to.~~
`MOB_EPIC` is now `MOB_SPECIAL`. Headslugs get that.
I think the alternative methow could use whatever the gold cores use to determine what to spawn but that would shift the mobs available for the belt even more and I can't be assed to figure out how _much_ of a shift that would be. Dragons or slimes or lavaland mobs would be out, for example. Don't really vibe with that.

Fixes headslug's description bit that discerns a sentient slug from an AI one showing up on a dead slug. It can't move while it's dead, no matter its mind/AI.

Also adds simple dmdoc comments to the defines to help discern a few of them more easily. Non-quip text suggestions welcome.

## Why It's Good For The Game
- Resolves #77756
- Resolves #78227

More mobs available for the funny belt but less _fun_ mobs should allow for more stable use of the damn thing. Arguably, some of the mobs that have been found to be incompatible with the belt are simply lacking a `MOB_ORGANIC` flag, some of them with no apparent reason. However, blacklisting potentially problematic biotypes should be easier to design the unwanted mobs around.
Also consistency, less all-ling stations, code clarity. Whatever.

## Changelog

:cl:
balance: polymorph belt now blacklists mobs that are undead, humanoid, robotic or spiritual (in nature, not religiously), as well as megafauna
balance: however, this means that it works with more mobs that it should logically work with, like slimes/bugs/lightgeists etc
fix: fixed headslug shenanigans with the polymorph belt hopefully for good this time
fix: fixed headslug description mentioning its movement despite the slug being dead
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
marking as balance because i believe humanoids are currently morphable into, and some previously unavailable creatures are now morphable into

could be wrong though i didn't fucking play with the item in any way

**Comment by iwishforducks** [comment]
dear god i know WHY we're giving it the mob_undead tag but SURELY there's a better way. headslugs are DEFINITELY not undead

**Comment by necromanceranne** [comment]
I feel like the MOB_SPECIAL bitflag is entirely a reasonable name rather than the potential bag of worms that is headslugs being classified as undead.

**Comment by Sealed101** [comment]
well the worst of it would be death wands being able to revive headslugs but yeah

**Comment by Sealed101** [comment]
<details><summary>spoiler for funny</summary>
<p>
free GBP for whoever fixes being able to smack a live headslug with a regenerative black core then lazarus injecting the resulting corpse then transference potioning into it
</p>
</details>

**Pull request merged**
