### PR TITLE
AIs can no longer resist

### PR DESCRIPTION
**Pull request by Cyberboss**
Like, seriously?

Closes #23646

### CODE REVIEW

**Comment by jughu** [comment]
IT HAS A WILL OF ITS OWN

**Comment by ShadowDeath6** [comment]
Fun removal

**Comment by Cheridan** [comment]
RESISTANCE IS FUTILE YOU WILL BE ASSIMILATED

**Comment by evsey9** [comment]
Dude there is no need to fix this just go to AI upload console and upload saying "Stop resisting" there

**Comment by jughu** [comment]
did you try turning the apc off and on?

**Pull request merged**
