### PR TITLE
Adds new trim decals mapping resources

### PR DESCRIPTION
**Pull request by Mickyan**
I've added some new decals for making colored trims around walls, points of interest, or color coded guiding lines for that hospital feeling. These fit perfectly with existing tile coloring.

Here's a quick and dirty example for some use cases. Yes, I messed up that corner.
Screenshot_3

:cl:
imageadd: Added new floor line decals for mappers to decorate the station
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
Having those lines become the standard will be great for new players and new maps and remind me of Black Mesa

**Comment by MMMiracles** [comment]
this is fucking hot ngl

**Review by SpaceManiac — APPROVED** [review]
very good

**Comment by Mickyan** [comment]
PSA for mappers that I forgot to mention: these are setup exactly the same as hazard stripes in terms of handling corners, ends, etc.

**Pull request merged**
