### PR TITLE
Observe on non mobs will now orbit the mob

### PR DESCRIPTION
**Pull request by optimumtact**
This is better than doing nothing, which was what it did after I
introduced the previous fix that filtered by mob

### CODE REVIEW

**Comment by optimumtact** [comment]
damn I forgot this was a mob level proc

**Comment by ChangelingRain** [comment]
Bad fix, should replicate earlier behavior without changing it.

**Comment by optimumtact** [comment]
The original behaviour was just broken thanks to a runtime

**Comment by ChangelingRain** [comment]
Then maybe replicate the original behavior, but with less runtime?

**Comment by optimumtact** [comment]
Nah

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Should mimic original behavior so you can observe an object and orbit something else.

**Pull request closed without merging**
