### PR TITLE
Fixed the leftmost and bottommost 15 turfs not having camera static

### PR DESCRIPTION
**Pull request by Cruix**
:cl:
fix: Fixed the leftmost and bottommost 15 turfs not having static for AIs and camera consoles
/:cl:

### CODE REVIEW

**Comment by Mervill** [comment]
Always wondered what was up with this, nice work

**Comment by optimumtact** [comment]
I don't understand how this works exactly, can you explain? Why are you doing a max of (y, 1) and (x, 1) and why not (z, 1) ?

**Comment by Cruix** [comment]
block() is a byond proc that returns all the turfs in a rectangle denoted by the lower left and upper right corner you pass into it (see http://www.byond.com/docs/ref/info.html#/proc/block)

block() is returning no turfs on the leftmost and bottommost camera chunks because for them either x or y are zero, putting them outside the border of the map. Putting the max(x/y, 1) clamps the lower left corner of the block to a valid location, so block() will return the turfs that it should. The upper right corner of the chunk is already properly clamped, which is why the uppermost and rightmost chunks are properly filled in.

It is not necessary for the z value because that will always be exactly the z level of the ai eye, which will always be valid or null.

**Comment by Mervill** [comment]
@Cruix this is worth of a changelist entry

Copy and paste this into your pull request body
```
:cl: Cruix
tweak: Fixed the leftmost and bottommost 15 turfs not having camera static
/:cl:
```

**Comment by optimumtact** [comment]
Perfect, thanks

**Pull request merged**
