### PR TITLE
Added some trigger words to the voice of god

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Adds some additional words that trigger Voice of God effects.
/:cl:

@XDTM 

I mean, this is just QoL stuff, I've seen people shout "repulse" and be confused that nothing is happening.

### CODE REVIEW

**Comment by kilkun** [comment]
feature freeze (fuck it)

**Comment by coiax** [comment]
NOT ANY MORE HA HA

**Comment by calzilla1** [comment]
Give it a 1/1000 chance for, if you say who am I? Every one responds with DUNKACHINO!

**Comment by ShadowDeath6** [comment]
>QoL of life

**Comment by kevinz000** [comment]
triggered

**Comment by XDTM** [comment]
If you don't mind i'd incorporate these into my PR, i'm about to add some new commands

**Comment by KorPhaeron** [comment]
XDTM stole this and put it in his PR

**Pull request closed without merging**
