### PR TITLE
Resolves #4400, moves protectstation module on meta

### LINKED ISSUE #4400: ProtectStation needs better defined wording
SubtleGraces on the forums:
"ProtectStation is absolutely terrible. Had a bit of a discussion about it in ASAY after an AI had someone killed over a floor tile being pulled up.
Can we get rid of it, or better yet, have better wording for the law so nobody can conclude that simple maintenance and deconstruction deserves death?

The wording of the law is absolutely atrocious and nobody seems to have reached a consensus on what "damage" means."

### PR DESCRIPTION
**Pull request by Jordie0608**
Resolves #4400

### CODE REVIEW

**Comment by GunHog** [comment]
I do not believe a "Fix" label is appropriate for this, as ProtectStation is not broken, as a coder would define it. It is a balance change, as you are not fixing anything, you are simply removing something.

From a balance standpoint, I do not see the point of doing anything about it. Anyone uploading it obviously wants the AI to kill people, any other module besides Asimov basically grants the AI permission to kill someone, the variation of lawsets defining whom and under what conditions. Here, it would be anyone who modifies the station in a way the AI does not approve.

**Comment by xxalpha** [comment]
Do not remove protect station please

**Comment by Miauw62** [comment]
What use does protectstation serve apart from "you crowbarred up a floor
tile kill he"
Op 29-mei-2015 00:20 schreef "xxalpha" <notifications@github.com>:

**Comment by GunHog** [comment]
You could make that same argument for most law boards that are not Asimov.

**Comment by duncathan** [comment]
Corporate accomplishes the same but with less murderboner.

**Comment by xxalpha** [comment]
ProtectStation is not supposed to prevent killings.

**Comment by Miauw62** [comment]
if you can upoad protectstation you may as well purge or upload antimov

**Comment by Cheridan** [comment]
>ProtectStation is not supposed to prevent killings. It's not something you upload unless you're up to no good.

The module is called PROTECT Station. The very name suggests that its *supposed* to be helpful. If it's a module that only is helpful when "you're up to no good", then there are other modules that are better like Tyrant, Antimov, OneHuman, or just purging. OxygenIsToxicToHumans module got taken out too, for basically the same reason: It didn't do anything that wasn't already covered better by another lawset.

**Comment by xxalpha** [comment]
Yes, you're supposed to help the station, not the crewmembers.

Learn to have fun.

**Comment by GunHog** [comment]
Every AI is different and unique in how they interpret laws. I as an AI player under ProtectStation would ignore Engineers that pull up tiles or do maintenance work, but would seek to kill things like hulks, or people deconstructing things as a way of breaking and entering.

**Comment by AlexanderUlanH** [comment]
The protectstation module seems fine but is a terrible terrible thing to upload.  That's how it was always intended.  Laws that backfire are the most interesting kinds.

**Comment by mrpain666** [comment]
It should be put on the table with Antimov and whatever the fuck else is basically the "DO NOT ACTUALLY USE THIS SHIT UNLESS YOU'RE AN ANTAG" table and that module should be given the same scrutiny as those laws.

Why bother flat out removing i....on second thought that's not a half bad idea too.

**Comment by Cheridan** [comment]
Realized that OxygenIsToxic module is still in the AI upload, so yeah just move it to the shitty pile from the good pile IMO if that turd of a module still exists.

**Comment by GunHog** [comment]
Yes, just move it to the 'Antag' pile.

**Comment by Jordie0608** [comment]
Remove OxygenIsToxic too you say?

**Comment by Jordie0608** [comment]
ProtectStation is already on box's high risk table

**Pull request merged**
