### PR TITLE
Morph Fixes

### PR DESCRIPTION
**Pull request by AnturK**
- Fixes morphing while dead
- Fixes gold slime spawn
- Adds some missing information to welcome text
- Lowers base form damage a bit

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>Fixes gold slime spawn

Boo

**Comment by AnturK** [comment]
I'd leave that in if it weren't for the pink slime extract. Honk

**Comment by phil235** [comment]
:+1:

**Comment by KorPhaeron** [comment]
@AnturK 

Xenobio can make changelings with the same method, this doesn't seem any worse than that.

**Comment by AnturK** [comment]
I suppose. Alright, i'll leave gold spawn in for now.

**Comment by Steelpoint** [comment]
I think the base damage is fine, that's a four hit crit on a mob that is very slow to start with.

**Comment by AnturK** [comment]
I probably should have waited with balance changes a bit since it's bit too new to gauge anyway. I'll open feedback thread on the forums soonish

**Comment by phil235** [comment]
merge conflict

**Comment by AnturK** [comment]
confilcts solved

**Pull request merged**
