### PR TITLE
Changes the size of bags

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Plant bag, chemistry bag and bio bag are all bulky now. They can still be equipped on the belt slot.
Plant bag has double the weight limit and bio bag double the item limit.

## Why It's Good For The Game

It's a tad ridiculous that we have stuff that can cheat the inventory system this much. This consolidates these items more as something you wear at your workplace instead of something gamers use to not worry about inventory space.

EDIT: Now has sprites.

## Changelog
:cl:
balance: Plant, chemistry and biobag are now bulky. Some of them have had their carry limits increased. They can still be worn on the belt slot.
add: The three bags can now be stored in the winter coats of their respective department and the chemistry/bio bag can now be stored in labcoats
add: Chem, bio and plant bag now have belt sprites.
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
Instead of making webbing not fit the jackhammer because you don't understand how it would, make the jackhammer show up on the webbing toolbelt-style. It's clipped to it externally, not placed in pockets.

**Comment by RaveRadbury** [comment]
Could you provide a stronger argument than "It's a tad ridiculous"? I'm a big fan of holding bags in my satchel. Additionally, what about toolbelts? This is a whole category of item that is treated like a fancy box and from what I can tell you're changing them to be fancy satchels/duffels/backpacks.

**Comment by nemvar** [comment]
The new bags are more like fancy belts that can't be stored in your backpack.  This changes them to be less of an inventory cheat item and more into a specialised tool. And that's exactly what my goal with this is. To make the bags useful for their intended purpose, being quickly moving large quantities of items across your workplace, instead of being the powergamers choice for ignoring the inventory system.

Sure, everyone likes to carry an infinite amount of healing items in their box, but why do we even have an inventory limit in the first place when we allow this to happen?

**Comment by zxaber** [comment]
How about a mini-version of the bags that hold less but also fit in an inventory?

I don't play roles that use the bags that often, but I was an ERT medic the other day, and it was quite convenient to be able to quickly grab a bunch of cure pills to a virus that was going around so that I could distribute them. A box would have worked, but I would have had to load it with pills manually.

**Comment by vpellen** [comment]
This feels like a ham-fisted attempt to nerf botany. I'm not saying it isn't needed, but I feel like it could be done with more elegance.

**Comment by knacker48** [comment]
I don't think randomly nerfing several different departments as a roundabout way to nerf botany is the right way to do things.

**Comment by nemvar** [comment]
The entire point of this change is that it should cost you something if you want to carry large amounts of stuff. The cost, in this case, is that it uses up your belt slot.

After this change, these bags will work more like a trashbag instead of "300 plants and 100 synthflesh beakers in my box".

**Comment by RaveRadbury** [comment]
To be consistent you need to do this to the various belts and mining satchel.

**Comment by nemvar** [comment]
Not really? Belts can't store 50+ items in them. Storage wise, most of them are worse than a normal box.

The mining satchel is somewhat required to be a rulebreaker due to the nature of the job. And it can't be used to store actually useful items in it.

**Comment by Tlaltecuhtli** [comment]
if the problem is carrying 50+ items in 1 slot then why arent you changing that

**Comment by PKPenguin321** [comment]
I'm open to them being normal sized since then it would at least be somewhat meaningful to have them in your backpack rather than practically free, but basically the entire point of these it to alleviate inventory hassle with systems that use a shitload of small objects (like pills/pill bottles in chemistry or slime cores). Plant bags though, those can be bulky since those have historically been kind of bullshit (carry 20000 minibombs in one backpack!)

**Comment by nemvar** [comment]
I'm not going to budge on making all the bags bulky. I'm going to make them equippable on lab coats though, since you can store plant bags on your apron.

**Comment by Tlaltecuhtli** [comment]
normalsize both and have plant carry 50 ,chem carry 25

**Comment by HomocidlePancakes** [comment]
I’d rather have smaller capacity while still fitting in pockets instead of bigger capacity w/o it.

**Comment by Tlaltecuhtli** [comment]
its called a pill bottle @homopankike

**Comment by nemvar** [comment]
It's not about people want, it's about what's balanced.
Even with a capacity of twenty, these items are somewhat rediculous in how much they can store as a normal sized item.
The natural comparison would be a box, which can store 7 small items. They would still be double as effective.

The important question I asked me when making them bulky was: "Would they still be used after the nerf", the answer is: "Absolutely". These things are still comparable to the janitors trashbag of holding, which is BIS for the belt in terms of general inventory space.

@zxaber It's called a box or a pill bottle.

**Comment by zxaber** [comment]
Does the pill bottle auto-load items from a tile the same way the bag does? If so, there's nothing else from me about this PR, it would be the "smaller version that fits in a bag" item.

**Comment by nemvar** [comment]
The pill bottle could do that last time I checked. I haven't used one in a while though because of how much the bag outshadowed it.

**Comment by Michael-Ashfield** [comment]
If you are making them fit lab coats don't forget bio suits and bee suits as they also store normal lab coat items

**Comment by Shadowflame909** [comment]
Botany can no longer make bombs though.

**Comment by anconfuzedrock** [comment]
I don't see how this nerfs botany either. botany has no reason not to put the bag in their belt slot, since backpacks can hold 99% of belt items. This does massively nerf medbay though since back defibs take up the slot so they won't be able to fit a chem bag. this is really mostly a medbay nerf.

**Comment by nemvar** [comment]
Maybe I will make the storage space on medkits larger in a later PR. They are currently one of the weakest containers in the game.

**Comment by ATH1909** [comment]
> I'm open to them being normal sized since then it would at least be somewhat meaningful to have them in your backpack rather than practically free, but basically the entire point of these it to alleviate inventory hassle with systems that use a shitload of small objects (like pills/pill bottles in chemistry or slime cores).
This, but minus the bit about making plant bags bulky (that I cut out of this quote). The bags should definitely be normal sized (like boxes, no?), but them being bulky is going too far.

**Comment by RaveRadbury** [comment]
If you're going to put them in the exoslot, be sure to include winter coats.

**Comment by Tlaltecuhtli** [comment]
> Maybe I will make the storage space on medkits larger in a later PR. They are currently one of the weakest containers in the game.

just make the chem bag hold 25 and normal sized ;)

**Comment by Tlaltecuhtli** [comment]
hey i had a cool idea:
chem bag size changes with the ammount of items inside, want to carry 3 bottles of lube? tiny, want to carry 15 bottles of lube? normal sized, want to carry the whole medbay? bulky
with some magic code on size change to make it eject from the bag if it turns bulky etc

**Comment by nemvar** [comment]
It would be prettier to not even allow items into the bag if they don't fit. But that's a fair point. I'm still not convinced them ever being tiny though.

Small: Size 3, Weight 12
Normal: Size 12, Weight 48
Bulky: Size 50, Weight 200 (should be 48 if follow the pattern but shush)
Sizes would be doubled for the plant bag because item volume is higher for botany.
Potentially we could go even bigger, with huge having 200 slots. But that's probably not a good idea.

**Comment by datorangebottle** [comment]
> Instead of making webbing not fit the jackhammer because you don't understand how it would, make the jackhammer show up on the webbing toolbelt-style. It's clipped to it externally, not placed in pockets.
> 
> Also, changing 100 item storage in your pocket to 200 item storage on your belt doesn't really nerf the original issue (A HUNDRED FUCKING PLANT GRENADES IN A SINGLE SLOT) but does inconvenience players.

plant grenades got removed because of plant bags, don't @ me

**Comment by ExcessiveUseOfCobblestone** [comment]
The bags should hold just enough to be sensible to transfer from loc to fridge.

They're gross storage creep i'm assuming veiled under QoL. There is not a reason you need to hold 50 medical items or 100 plants at once on top of whatever you can fit in your bag

**Comment by Shadowflame909** [comment]
It currently takes forever to put 1000 10 unit synthflesh patches into the fridge though. If your nerfing the amount it can hold. Gimme moar bags

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't think fridges can hold  that many anon

**Comment by Shadowflame909** [comment]
They can.

It's always worth it.

**Comment by ExcessiveUseOfCobblestone** [comment]
synthflesh is probably the worst healing chem you deserve to suffer tbh

**Comment by Shadowflame909** [comment]
That's fair but I prefer to dab on cloning with synthflesh and Strange Reagent.

That's what you gamers get, making a chemist do work and all that junk.

**Comment by AdamElTablawy** [comment]
Normal size would be better, or alternatively you could make the bag scale up with how much is in it, like the garbage bag does (I think.)

You shouldn't be able to carry 600 death potatoes, but you should be able to carry at least a small number of assorted plants in your backpack without having to resort to boxes instead-otherwise it makes little sense that you could carry a box filled with 10 death potatoes but not a plantbag filled with 10 death potatoes in the same backpack.

**Comment by ExcessiveUseOfCobblestone** [comment]
but you can carry 10 in the box and in the bag at the same time so they shouldn't arms race with each other.

**Comment by optimumtact** [comment]
Well where is this going then?

**Comment by nemvar** [comment]
I'm happy to get this merged in this state.

The change to make stuff different sized based on amount stored shouldn't really be in here because I feel like it should extend to stuff like backpacks and belt.

**Comment by Yttriums** [comment]
Guess I'll just be huffing more ephedrine and running back and forth to botany to grab more gas grenades.

**Comment by AdamElTablawy** [comment]
What do you mean 'extend to stuff like backpacks and belt'?

You should be able to put a bag not full of items into your bag because it can be folded up. A bag full of only a few items can also be placed into the bag.

A bag filled to bursting with other items cannot be placed in a bag. Haven't you ever packed a bag before?

**Comment by ExcessiveUseOfCobblestone** [comment]
>There is not a reason you need to hold 50 medical items or 100 plants at once on top of whatever you can fit in your bag

The only response to this I got was from some guy making supposedly hundreds of 10u synthflesh packages so I need a sensible usecase where you shouldn't just be forced to make multiple trips if you want this merged as is (by me at least)

**Comment by Yttriums** [comment]
> > There is not a reason you need to hold 50 medical items or 100 plants at once on top of whatever you can fit in your bag
> 
> The only response to this I got was from some guy making supposedly hundreds of 10u synthflesh patches so I need a sensible usecase where you shouldn't just be forced to make multiple trips if you want this merged as is (by me at least)



> > There is not a reason you need to hold 50 medical items or 100 plants at once on top of whatever you can fit in your bag
> 
> The only response to this I got was from some guy making supposedly hundreds of 10u synthflesh patches so I need a sensible usecase where you shouldn't just be forced to make multiple trips if you want this merged as is (by me at least)

It takes at least 5 slots in a plant bag to  carry the stuff to create a fully fertilized dirt patch and plant a seed. You also have to carry around sandstone and robust harvest. If I want to distribute a plant with useful chems around the station, it's nice to have plenty of room.

While you could make a botanist make several trips to plant a ton of things, I don't really think botany should be more tedious than it is. Making anything broken in botany already requires at least 20-25 minutes of optimal powergaming - I don't think adding additional tedium is the balancing it needs.

I also feel like people are judging the weight of plants based on the potency-based size scaling on plants - but that scaling is already cartoonish and makes no sense given that 'yield' is a separate trait.

**Comment by ExcessiveUseOfCobblestone** [comment]
5/50 is 10%, you have 90% left to use so I'm not really buying why you need 100 slots.

Yes, if you're spamming something, it should be difficult to do. If you're amassing 50+ items in quick succession botany is probably doing well for themselves. If you're just hoarding items then that's the issue...

Being tedious is like botany's only balancing act besides gene machine stat restrictions. It's even more free chem creation than chemistry with it's cost being water/nutrients/time (2/3 are fully mitigated with a plant and the third can be mostly mitigated via stats).

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
Formalizing this, also lower the max_items of both medical and plant bags to something sensible for someone to make...

... From a fully decked botany tray (10-13 with bees). Personal recommendation would be <30, maybe 25 ish so 1 trip per 2 decked out trays.

... From a 100u beaker. Typically people make >=10u pills/patches/etc. BUT pills can be bottled which go into the bag so <=20 maybe ~15. At 20 you can only need 1 trip if making 5u meds from a fully filled 100u beaker.

Mining is fine especially since most people just use the box anyways.

**Comment by Yttriums** [comment]
We should probably call the engineering backpack into question. I don't see any reasonable case where someone should be able to carry enough metal to construct multiple walls.

**Comment by ExcessiveUseOfCobblestone** [comment]
I know you're shitposting but a stack of anything in your backpack can take up a nice chunk of your space. That and building is insufferable unlike having a chemical arsenal in your back pocket.

**Pull request closed without merging**
