### PR TITLE
Resprites the Hypernob crystal to look like a crystal and not a xenobio potion

### PR DESCRIPTION
**Pull request by D4C-420**
## About The Pull Request
Changes the hypernob crystal from using the generic xenobio blue potion to somthing that looks more inline with its color when applied to a piece of clothing and ya know. A crystal.
Picture of the sprite upclose.
hypernob_crystal_upclose_4

Next to a fool

hypernob_crystal_4

EDIT: Changed the sprite to not look bad. hopefully looks better now. Replaced the old images in the PR body. 

EDIT 2: Cleaned up the look of the crystal. It now looks like

hypernob_crystal_upclose_5

and of course next to a person 
hypernob_crystal_5
Edit 3: Okay last time probably (not) I'm changing this thing. Its now a cube. still leaving the last 2 versions up top for comparison.

hypernob_crystal_6
hypernob_crystal_upclose_6

Cubes are fun

## Why It's Good For The Game
Less confusion about what is a xenobio potion and comes from xenobio and what is an atmos crystal and comes from atmos.
Also makes it looks nicer than having 3 very similar things have the same sprite.  Also slightly changes the description of the crystal to match its new sprite.

## Changelog

:cl:
imageadd: Unique sprite for the Hypernob crystal from atmos
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
Hate to say it but... these don't really look like crystals. The squiggles in the middle don't really look crystalline. You might want to take inspiration from something like [these](https://www.youtube.com/watch?v=xlSo7GPgps0).

image

**Comment by Ebin-Halcyon** [comment]
Oh baby, that's a sprite for sure.

**Comment by ArcaneMusic** [comment]
It definitely looks more like a boulder of glass now than it was before, which is totally what you're going for. Nice work.

If you're up for making some tweaks to it, I've got 2 suggestions:
1. Limiting your palette to about 4-5 colors per face really helps to make the difference faces of the glass stand out, without muddying the colors like with a gradient.
2. In choosing your palette, you can make the spite have some extra depth to it by isolating out your brighter and darker edges similar to how we've done 3/4ths sprites. Here's an example of the 3/4ths thing as well as something with a kind of crystalline texture. (I broke that first rule slightly on the right but it's actually fairly similar to what you're doing here)
image

Don't know if that helps but hey 🤷

**Comment by D4C-420** [comment]
> Limiting your palette to about 4-5 colors per face really helps to make the difference faces of the glass stand out, without muddying the colors like with a gradient.

Something like this? 
hypernob_crystal_upclose_5
And next to a player
hypernob_crystal_5

> In choosing your palette, you can make the spite have some extra depth to it by isolating out your brighter and darker edges similar to how we've done 3/4ths sprites. Here's an example of the 3/4ths thing as well as something with a kind of crystalline texture. (I broke that first rule slightly on the right but it's actually fairly similar to what you're doing here)

I been trying to make the sprite look as close to the nitruim and ammonia/n2o crystal as I could without just using that sprite and recoloring it so I don't think ill end up doing the 3/4ths for this. Either way the feed back is wanted so thanks.

**Comment by Comxy** [comment]
I like the original you posted first. But maybe a white outline, especially all the way through might not fit

**Comment by ArcaneMusic** [comment]
I suppose on second though if you kept the glossy gradient from the first sprite, but as comxy said worked on using some darker shades on the sides of the sprite so it's not just a white outline, it'll really pop off.

**Comment by disappointedButNotSuprised** [comment]
the new sprite looks like a cabbage

**Comment by D4C-420** [comment]
> the new sprite looks like a cabbage

This is 1000% intentional as to get atmos and botany to work together on miasma farms. 

But no really I see that and am seeing if I can't remedy that slightly.

**Comment by NightmareChamillian** [comment]
Honestly going to second that I kind of like the old sprite slightly more

**Comment by moocowswag** [comment]
I like the old sprite more too, it gives a feeling of something that looks crudely made / unstable.

**Comment by D4C-420** [comment]
Okay here we go not cabbage anymore because 

hypernob_crystal_upclose_6
hypernob_crystal_6
It is now CUBIC. 

(also push comes to shove if this is not an improvement I'm just going to go back to the first image)

**Comment by Jacquerel** [comment]
I think this latest one is definitely the best so far.

**Pull request merged**
