### PR TITLE
New drink sprites aka Drink Desouling

### PR DESCRIPTION
**Pull request by MassacreDemigirl**
## About The Pull Request
[Crumpaloo](https://github.com/Crumpaloo) and [PestoVerde322](https://github.com/PestoVerde322/)decided to sprite each and every drink sprite to be in our new perspective so here they are

## Why It's Good For The Game
New sprites look sexy as fuck
image

https://user-images.githubusercontent.com/25566633/166112828-179e9b18-2288-413b-b586-84c0752036ed.mp4

## Current Sprite Status

- [x] New Soda Cans (By PigeonVerde)
- [x] Perspective Fix
- [x] Broken Bottle
- [x] Champagne Cork

drinks

## Changelog

:cl: Crumpaloo - Main Sprites, PestoVerde322 - Soda Cans, Vending Machines and Posters, ErdinyoBarboza - PR and Small Fixes
imageadd: All drinks and bottles have been resprited
/:cl:

### CODE REVIEW

**Review by ArcaneMusic — COMMENTED** [review]
A few issues:
You have several sprites that you changed the name of the sprites in the DMI, so you know, icon_state is Capitalization sensitive. That means that a few sprites like the Rum Glass may be broken now. Please check on that.

In addition, You're also removing quite a few other sprites, like colocups, and the masking sprite we use for broken bottles. These sprites are used, and in the case of the broken bottles are used in combination with a few other bottles. What that intentional?

**Comment by Toastgoats** [comment]
Nice, first time I've ever had sprites get desouled, I feel like a proud father lmao
The jack rose looks really sick, though the handle on the applejack glass looks a little funky.

**Comment by BebeYoshi** [comment]
I will miss the Blank Paper pencil and color....  Otherwise they all look great

**Comment by ErdinyoBarboza** [comment]
@ArcaneMusic It was not. The spriter fellow sent the dmi and I did not notice the missing pieces. I'll patch those back in

**Comment by MrDoomBringer** [comment]
Woah

**Comment by red-creature** [comment]
these sprites are sexually attractive

**Comment by carshalash** [comment]
May I ask why you went with pilsner glasses to replace highballs as the default glass?

**Comment by Wallemations** [comment]
You left a duplicate bottle of nothing

**Comment by cacogen** [comment]
I wish you'd provide a comparison to the old ones.

**Comment by Crumpaloo** [comment]
> I'm REALLY not understanding this one.

Hey, bottle already looked fine so i didnt have much reason to change anything asides from the top of it to hint at the perspective.

**Comment by Crumpaloo** [comment]
> Very nice! Although there's a few that I prefer for the old designs, like irish car bomb or B-52, the vast majority of these look really, really sick. A little concerned for poor EOB who's now gotta try to stay somewhat in line with these new ones, haha.
> 
> Also, just repeating what arcane's said - why the deletion of sprites like the glass bottle, the shakes, helianthus, etc?

Heya, went back and tried to make those two drinks you talk about a bit better, as well as going back and respiting the glass bottles, the shakes, helianthus, etc which all should now be updated and implemented into the PR along with the Irish Carbomb and B-52 ^^.

**Comment by Crumpaloo** [comment]
> I will miss the Blank Paper pencil and color.... Otherwise they all look great

Hellloooo, added the pencil back into the sprite, wasnt 100% sure what it was at first but having heard the feedback it has been re-implemented to look more obvious 👍

**Comment by Crumpaloo** [comment]
> Nice, first time I've ever had sprites get desouled, I feel like a proud father lmao The jack rose looks really sick, though the handle on the applejack glass looks a little funky.

I went ahead and took the handle off and made a couple minor edits to it, should be fixed now 👍

**Comment by Crumpaloo** [comment]
> I wish you'd provide a comparison to the old ones.

image
here ya go. :p

**Comment by theOOZ** [comment]
I don't really like the new soda cans, but the rest of this PR is ten atta ten 👍

**Comment by MTandi** [comment]
Just curious, do we have some guidelines for pixel art?
Even though these sprites were done by a single person, the angle/perspective seems random.
For instance, cans are 1:1, while most of the drinks are 1:2.

DoMGm-mWkAECVag

**Comment by Crumpaloo** [comment]
> Just curious, do we have some guidelines for pixel art? Even though these sprites were done by a single person, the angle/perspective seems random. For instance, cans are 1:1, while most of the drinks are 1:2.
> 
> DoMGm-mWkAECVag

Heya! Im currently going through and fixing all the inconsistencies the best i can before handing them off the the PR maker who im in contact with via DM's to update them ^^

**Comment by Crumpaloo** [comment]
> WHAT HAVE YOU DONE TO THE LONGHAUL SPRITE?

Stuff... i did stuff to it... also heres it with a few edits: 
image

**Comment by TheBonded** [comment]
> > I'm REALLY not understanding this one.
> 
> Hey, bottle already looked fine so i didnt have much reason to change anything asides from the top of it to hint at the perspective.

@Crumpaloo isnt the top supposed to be square because its based off a real life bottle? also you left in the small transparent section at the bottom due to the inside of the bottle curving up at the bottom, meaning you are looking at the bottom from the side but the top from above, which kinda messes with perspective.

**Comment by MTandi** [comment]
> > I don't really like the new soda cans, but the rest of this PR is ten atta ten 👍
> 
> image
> 
> Heya, went back and made a few edits to fix the soda, including fixing its perspective on all of them. 👍

I'd suggest something like this for cans: 
cola

**Comment by TemporalOroboros** [comment]
Those are some fantastic drink sprites. I do have a few notes though...
1. Sprites are missing for "hell", holy water, broken bottles, and champagne corks.
2. The swirling affect on the singulo sprite is very clearly isolated to the bottom of the drink. It also looks a bit more like red glitter in clear syrup being stirred than a singulo. Spreading the swirling to the rest of the liquid in the glass and adding some purple/black could probably improve it a bit.
3. The syndicate bomb is no longer a TTV. 
4. Please give the hivemind eraser back its sparkles. The new sprite has a higher quality base, but it looks quite a bit less lively than the old one.

**Comment by Crumpaloo** [comment]
> > > I'm REALLY not understanding this one.
> > 
> > 
> > Hey, bottle already looked fine so i didnt have much reason to change anything asides from the top of it to hint at the perspective.
> 
> @Crumpaloo isnt the top supposed to be square because its based off a real life bottle? also you left in the small transparent section at the bottom due to the inside of the bottle curving up at the bottom, meaning you are looking at the bottom from the side but the top from above, which kinda messes with perspective.

Ill go back and resprite it properly once ive fixed up a few more things 👍

**Comment by carshalash** [comment]
image
What is that on the shaker?

**Comment by Crumpaloo** [comment]
> 



> Those are some fantastic drink sprites. I do have a few notes though...
> 
> 1. Sprites are missing for "hell", holy water, broken bottles, and champagne corks.
> 2. The swirling affect on the singulo sprite is very clearly isolated to the bottom of the drink. It also looks a bit more like red glitter in clear syrup being stirred than a singulo. Spreading the swirling to the rest of the liquid in the glass and adding some purple/black could probably improve it a bit.
> 3. The syndicate bomb is no longer a TTV.
> 4. Please give the hivemind eraser back its sparkles. The new sprite has a higher quality base, but it looks quite a bit less lively than the old one.



> image What is that on the shaker?

Just suppose to be a red logo with a bit of writing

**Comment by sergeirocks100** [comment]
Looking through the sprite diffs, it seems a couple of sprites have the wrong names, like the manhattan glass, and the nuka cola.

Also, the lean sprite should probably be removed, since the drink it was used for got removed over a month ago.

**Comment by carshalash** [comment]
> > image What is that on the shaker?
> 
> Red logo with black writing

Mmmh, symbols and writing aren't really common on shakers. While the rest of the shaker sprite looks nice (The top black line separating the strainer component is nice) I think the writing and red bit are a touch offputting.

**Comment by ErdinyoBarboza** [comment]
Shaker has been diversified, new soda can sprites will be brought by PigeonVerde soon hopefully

image

**Comment by ErdinyoBarboza** [comment]
@TemporalOroboros Hell does not have an attached drink afaik

**Comment by Wallemations** [comment]
> > WHAT HAVE YOU DONE TO THE LONGHAUL SPRITE?
> 
> 
> 
> Stuff... i did stuff to it... also heres it with a few edits: 
> 
> image
> 
> 

I'll admit I'm not personally a fan of the tall glass used instead of the Guinness-style rounded beer glass from before.

**Comment by Crumpaloo** [comment]
> Also, the lean sprite should probably be removed, since the drink it was used for got removed over a month ago.

It shall forever stay in the sprite files.

**Comment by sergeirocks100** [comment]
https://github.com/tgstation/tgstation/pull/66538/checks?check_run_id=6231130758

There's still about 5 drink sprites with the wrong names (most of the ones marked as "added" at the bottom of the icon diff list).

Please either change the sprite names back to the old ones, or change the drinks themselves to use the new sprite names.

Also, Demon's Blood is still missing its sprite, so you should probably fix that

**Comment by ErdinyoBarboza** [comment]
[sergeirocks100](https://github.com/sergeirocks100) fixed

**Comment by carshalash** [comment]
I would like to ask again about the choice of using beer pilsners as the base glass instead of the highball.

**Comment by ArcaneMusic** [comment]
Everything's looking good now, nice work!

**Comment by Crumpaloo** [comment]
> I would like to ask again about the choice of using beer pilsners as the base glass instead of the highball.

This has been ratified about two days ago, Pilsners will still be a glass type, but only for regents that are more liable to be drinked plainly by themselves (so no berry,carrot,banana juice etc.) The highballs has taken their place and will be rolled out as the base drink glass for holding regants upon merging of the PR 👍

**Comment by Sneeker134** [comment]
Damn, Moana Loa got quite the glow up lol. Doesn't really look like the old sprite I made for it, but it definitely looks way better lol. Great PR, and great job!

**Comment by ErdinyoBarboza** [comment]
This is officially ready to merge

**Comment by MTandi** [comment]
The new cans look a lot better.

The only thing that's a bit off is this dark horizontal line at the top of a can. It feels like this line splits the can in half. Is this some kind of a shade added intentionally?

Screenshot_2022-05-03-11-11-30-287

**Comment by carshalash** [comment]
Oh yeah. I forgot to ask earlier, what exactly is the green garnish in the amaretto alexander?

**Comment by Imaginos16** [comment]
Well, the reception seems very positive, I do not see why this PR should be still on limbo.

**Pull request merged**
