### PR TITLE
Direction Control of Vents using the AirAlarm

### PR DESCRIPTION
**Pull request by WarlockD**
## About The Pull Request
This allows you to set the vents using the airalarm to blow either way.  Don't worry, it will be colored red to make it clear that its sucking in.

Also moved some of the controls in the tgui interface so I can eventually allow more finite control of individual vents.

## Why It's Good For The Game
The vents in the big air tanks suck in as well as a few other bases.  Eventually I want a player to be able to rebuilt anything that could be created in the map editor.  Also more consitancy across the board.  No reason why an atmos tech cannot control the vent direction.

## Changelog
:cl:
tweak: allows the air alarm to control vents
fix: Not sure why, but vents send a 0 or 1 on the signal like scrubbers
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Budget scrubber, based

**Comment by FloranOtten** [comment]
Will these just replace siphoning scrubbers?

**Comment by LemonInTheDark** [comment]
maybe lessen it's ability to scrub if it's on par with scrubbers, that way it's a "shit someone plasma flooded" tool

**Comment by spookydonut** [comment]
@WarlockD merge conflict

**Comment by WarlockD** [comment]
The pressure settings have to be set up a curtain way for it to work within a pressurized line.  Also, technically, the scrubbers are better as they have a higher volume to work with than unitary pumps.  But its easy to move those numbers around on the volume of air being moved. At one time

**Comment by WarlockD** [comment]
They could replace them, not sure its a good idea though.

> Will these just replace siphoning scrubbers?

They could, but really not a good position for them.  These vents have variable pressure controls, so now you can control if a room becomes overpressurized   I can see using a combo of vents you could control a mix tank with different gasses going in but I haven't sat down and mapped that out yet.  But the volume of air moved per tick by the scrubbers is more than the vents so doubt they will be replaced.

**Comment by spookydonut** [comment]
@WarlockD merge conflict

**Comment by WarlockD** [comment]
ugh god damnt that fork, one sec

**Comment by WarlockD** [comment]
Any chance to test merge this?

**Comment by WarlockD** [comment]
arg yea I know its stale trying to fix

**Comment by WarlockD** [comment]
I mean its done, just waiting on some kind of review

**Comment by WarlockD** [comment]
ok repulling with a fixed branch

**Pull request closed without merging**
