### PR TITLE
Golems now have tongues again, except cardboard golems

### LINKED ISSUE #67972: Golems are missing tongues
RoundID 185457

noticed that golems talk like they're missing a tongue now

ooooarroh

### PR DESCRIPTION
**Pull request by CoffeeDragon16**
## About The Pull Request
Fixes #67972. Golem's tongues were being set as the adamantine chords, which are what allows adamantine golems to speak to all golems. However, since vocal chords aren't actually tongues, they wouldn't load in, leaving all golems with no tongues.

Also, makes cardboard golems still not have tongues. A good few people told me golems should stay this way in some form. I'm not particularly attached to this change, I just like it, so feel free to make a revert of this part.

Maintainer species approval:
image
image
## Why It's Good For The Game
While golems having no tongues is pretty funny, it gets frustrating for the golems. Keeps a little bit of that in the game. 

## Changelog

:cl:
fix: golems will now have tongues again, and adamantine golems can now talk to all golems again
add: cardboard golems no longer have tongues
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
@MrMelbert @CoffeeDragon16 imagine discussing balance changes in admin channels, disgusting

**Comment by Shadowflame909** [comment]
lorewise cardboard golems have tongues, its just that the innate moist (Saliva) environment of their mouth renders it mush and useless

**Comment by itseasytosee** [comment]
Cardboard golems gimmick of reproduction seems counterintuitive to them not having tounges. How are they gonna tell their spawn their master's wishes?

**Comment by ATH1909** [comment]
Yeah, this change looks like it'd make cardboard golems even more unga dunga-y, seeing as how they'll be unable to use anything but miming and violence to meaningfully communicate with not only each other, but also the outside world.

**Pull request merged**
