### PR TITLE
shuttles will now throw you if you don't buckle in

### PR DESCRIPTION
**Pull request by ghost**
:cl: SPACE CONDUCTOR
tweak: Shuttles will throw you around if ya don't buckle in
/:cl:

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
capture

**Comment by lzimann** [comment]
change the title fast or the pr will be closed

**Comment by Mark9013100** [comment]
sit yo ass down muthafucka

**Comment by Cyberboss** [comment]
Get the passive aggressiveness out of the body or the pr will be closed

**Comment by GunHog** [comment]
How is the direction of the throw determined? I want to know how well I can use this to space people.

**Comment by ninjanomnom** [comment]
When the shuttle leaves it throws you to the back, when the shuttle arrives it throws you to the front. Determined by the same method as parallax movement.

**Review by ninjanomnom — APPROVED** [review]
code is fine but this is primarily a balance change. I'll leave this up to @KorPhaeron

**Comment by DaxDupont** [comment]
Won't this space people if the shuttle is damaged? Some shuttles have little to none chairs as well.

**Comment by lzimann** [comment]
i believe that's the entire point of this change actually

**Pull request merged**
