### PR TITLE
Adds high-speed engineering tools for the CE

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
rscadd: The CE got a pay raise and some better tools.
/:cl:

All the tools have 2.5 speed and
# _**DEFAULT SPRITES**_

are you guys happy now

the CE gets his better tools

sprites left in for when I add the gang pimp-toolbox with solid gold wiring and multitool/gloves

### CODE REVIEW

**Comment by Bawhoppen** [comment]
did you not understand that people didn't want the ce to have better tools either?

**Comment by Iamgoofball** [comment]
@Bawhoppen oh my god fuck off

**Comment by Bawhoppen** [comment]
I don't care myself but if you read the comments in the other pr the majority were about how OP the tools were, not the sprites

**Comment by Iamgoofball** [comment]
great, did you even fucking read the OP where I nerfed it a shitton

**Comment by GunHog** [comment]
I am actually fine with this now. CE having faster tools is appropriate because he is a head of staff. Personally, I would use a flat 2x, but whatever makes you happy. And maybe get @WJohn to make thematic sprites.

**Comment by TechnoAlchemisto** [comment]
Plasteel tools would be thematic

**Comment by xxalpha** [comment]
Just make slightly different sprites, different but not totally alien like the cyborg tool sprites.

**Comment by lordpidey** [comment]
Add a special multitool too.

**Comment by TechnoAlchemisto** [comment]
Multi tools wouldn't have anything to benefit from

**Comment by xxalpha** [comment]
Special multitool that uses TGUI instead of old gui.

**Comment by lordpidey** [comment]
Multitools are used to unlock the fireaxes and reset the personal safes, both of which have a time delay.

**Comment by swankcookie** [comment]
These for sure need to have an alternate sprite.

**Comment by Iamgoofball** [comment]
@swankcookie you guys veto'd the alt sprite and it got the last 2 PRs close

give me sprites and sure

**Comment by swankcookie** [comment]
@Iamgoofball the golden sprites? Of course they got veto'd, they made no sense. just make them look slightly alternate in a way that would justify doubling the speed. I know it can be frustrating, but it's not my job to help you complete your PR.

**Comment by Armhulen** [comment]
aw fuck me I liked the golden sprites

goofball when they turn down your golden tools pr you have to make diamond tool pr

**Comment by Zilenan91** [comment]
OH MAN STOP THE PRESSES THE CE CAN SCREWDRIVER GLASS A FEW SECONDS FASTER

:+1:

**Comment by PKPenguin321** [comment]
The delicate window fastening meta

(most construction delays are on the chopping block anyways)

**Comment by Armhulen** [comment]
I would've preferred that we kept the gold tools

**Comment by optimumtact** [comment]
Make a new pr when you have this cleaned up

**Pull request closed without merging**
