### PR TITLE
Adds the golem Qustinnus was REALLY too afraid to add

### PR DESCRIPTION
**Pull request by Time-Green**
[Glorious soviet golem demonstration](https://youtu.be/SEXzSlWpX2M)

Stalinium is currently unavailable, so it's an admin only golem
:cl: Time-Green
rscadd: Adds glorious soviet Russia golem
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
I was gonna make some nutrition joke but you already implemented it
10/10 PR

**Comment by tralezab** [comment]
my hero

**Comment by Swiftkor** [comment]
sounds like communist propaganda but ok

**Comment by ATH1909** [comment]
Speedmerge this now.

**Comment by optimumtact** [comment]
changed my mind, can see an admin running  a good event with this.

**Comment by davethwave** [comment]
As long as you can't get the mats for the this golem ingame without admemes I am fine with this. I can see Soviet Golem Ruin as a potential idea as a event I guess.

**Comment by OverlyGeneric** [comment]
This should be vodka-colored for the silvery white reminds me of the harsh winter like the strong punch of vodka, comrade.

**Comment by Tlaltecuhtli** [comment]
vodka should heal them

**Comment by Time-Green** [comment]
they should be red, the color of socialism
also yeah I can do vodka healing

**Comment by Ziiro** [comment]
Turn all revs to soviet golems upon rev victory

**Comment by ATH1909** [comment]
> Top bad golems can‘t wear clothing, these guys would rock the track suit

Actually, isn't there a way to make clothing able to be worn by certain species that normally can't wear it? I'm pretty sure that it's called "species_exception" or something and that it's used a lot with the angel race (and their wings).

**Comment by nichlas0010** [comment]
this is beautiful

**Pull request merged**
