### PR TITLE
Photocopier paperforms fix

### LINKED ISSUE #65831: Sanitization kills the markings on the forms
## Reproduction:

Hi, in PR #61323 I implemented the form system. It was based on the use of pre-formed html/css code. But as I understood from the names in #65752 this approach is not safe. I'm getting to the question, is it worth trying to maintain these mechanics or is it just easier to remove it from the TG codebase?
изображение

### PR DESCRIPTION
**Pull request by twilightwanderer**
## For upstream builds tgstation.

**Please read this carefully.** This PR updates the broken **config/blanks.json** configuration. Before incorporating these changes into your build, make sure that you have not made any changes to match the specifics of your builds. Otherwise, fix the configuration yourself or contact me.

## About The Pull Request

Fixes #65831

In this [PR](https://github.com/tgstation/tgstation/pull/61323) I added a system of pre-prepared paper forms for the printer. This system worked for a while and because of security problems in the papers was completely broken by quick fixes to the holes. I did not try to fix the forms, because at the time because of the broken papers it was pointless, and I decided to wait until the code papers are fully recycled. Waiting for a [fix,](https://github.com/tgstation/tgstation/pull/68612) I rewrote the config and now the system blanks again normally print forms. In addition, this fix allowed to bring the configuration of the forms in a more readable form.

As a bonus, I decided to add a "VOID" stamp. I was going to do it back when the system of forms was introduced, but because the stamps at the time did not work properly I did not do it.

9l2tDbfMFW

## Why It's Good For The Game

The system of prepared forms again works to the delight of fans of bureaucracy.

## Changelog

:cl:
add: Added new VOID stamp
fix: Photocopier paperforms
/:cl:

### CODE REVIEW

**Comment by twilightwanderer** [comment]
This solves this bug. https://github.com/tgstation/tgstation/issues/65831

**Comment by Timberpoes** [comment]
I am not gonna lie, I didn't even realise this was a feature! That explains the printing blank part I updated in the original PR.

I'll check this out on local and make sure it all works. Seems you've done that yourself, but I want to make sure I didn't fucking anything else in the background.

Very cool of you to update it all. If it all checks out and I merge this, I'll also make sure to update the configs on our servers when I am able.

**Comment by Timberpoes** [comment]
Right, checked the branch out and all seems gucci gucci. Gonna slam this into the repo and then update our servers with the updated json. Thanks again!

**Review by Timberpoes — APPROVED** [review]

**Comment by twilightwanderer** [comment]
> Right, checked the branch out and all seems gucci gucci. Gonna slam this into the repo and then update our servers with the updated json. Thanks again!

You're welcome. At the time I implemented these forms, I was using HTML code to its full potential and was unaware that it itself causes huge security problems. I don't exclude that this fix may have to be redone in the future as well. 

Perhaps I should prepare some README on editing blanks.json so that server hosts based on the tgstation build can easily edit it for their needs.

**Pull request merged**
