### PR TITLE
Tram resprite

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Brings the tram into perspective like everything else

image

## Changelog

:cl: LT3
image: Tram has received a new exterior and coat of paint
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
The tram dearly awaits when we make the cutter work with diagonal/curved walls 😔

**Comment by MrMelbert** [comment]
I like it but I'm kinda curious why we changed from titanium white to black

**Comment by lessthnthree** [comment]
> I like it but I'm kinda curious why we changed from titanium white to black

When I started on it I thought it'd be a better contrast with the light grey of the tiles around it.

**Comment by lessthnthree** [comment]
> The tram dearly awaits when we make the cutter work with diagonal/curved walls 😔

Yes. :( It's very boxy now, but it will have to do until diagonal walls.

**Comment by LemonInTheDark** [comment]
how does it look in movement?

**Comment by SomeoneYouProbablyKnow** [comment]
Ayyyy alien lookin tram. But i think the contrast is neat

**Comment by lessthnthree** [comment]
> how does it look in movement?

https://github.com/user-attachments/assets/67370f61-8cca-4a84-8411-3aae26d10d2f

**Comment by SmArtKar** [comment]
> > how does it look in movement?
> 
> dreamseeker_OrEUiUeQwr.mp4

those windows are really jank, are overlays on those turf based?

**Comment by lessthnthree** [comment]
> > > how does it look in movement?
> > 
> > 
> > dreamseeker_OrEUiUeQwr.mp4
> 
> those windows are really jank, are overlays on those turf based?

discussing it on discord

**Comment by SmArtKar** [comment]
feels weird seeing it black, doesn't really fit the vibe. Maybe add blue or red stripes to white one if you want it to be more vibrant?

**Comment by notfrying1pans** [comment]
the windows not connecting to the walls is throwing me off perspective-wise

**Comment by lessthnthree** [comment]
yeah it's drafted until the windows are sorted.

**Comment by lessthnthree** [comment]
> how does it look in movement?

https://github.com/user-attachments/assets/8e5c2ffe-f6fa-4d9c-97e7-a48a52b395f8

**Comment by notfrying1pans** [comment]
> the windows not connecting to the walls is throwing me off perspective-wise

looks way better now

**Comment by MMMiracles** [comment]
goes hard

**Comment by Wallemations** [comment]
My concern is that the color of the doors kinda blends with the tram floor tiles, specifically with the bottom ones.
Any way you might be able to make them easier to visually see?

**Comment by lessthnthree** [comment]
> My concern is that the color of the doors kinda blends with the tram floor tiles, specifically with the bottom ones. Any way you might be able to make them easier to visually see?

Sure

**Comment by Jacquerel** [comment]
I'm afraid that due to the now-in-progress revert of Wallening from the master branch in order to "put it back in the oven" you may need to re-PR this to the wallening repo instead, sorry for the inconvenience.

**Pull request closed without merging**
