### PR TITLE
Fixes #8612 Hat Removal Code Fix

### LINKED ISSUE #8612: Removing hat doesn't update mob's head
A hat can be removed from the inventory but it doesn't update a mob's head var so the game still thinks you're wearing one.

Tried with both a human and a monkey

@RemieRichards

### PR DESCRIPTION
**Pull request by RemieRichards**
Fixes #8612 

Literally not even my fault, somebody unticked carbon/inventory from the DME.

Sanic merge this.

### CODE REVIEW

**Comment by RemieRichards** [comment]
@tgstation/commit-access Sanic this, it's important.

**Comment by phil235** [comment]
Apparently I'm the one at fault, I unticked the file by mistake. :(

**Comment by RemieRichards** [comment]
@phil235 Awww it's your fault? I can let you off then, you've done great work with Life() recently so I imagine you accidentally hit it then :)

**Comment by Jordie0608** [comment]
travis is for dorks (and keeps breaking anyway)

**Comment by RemieRichards** [comment]
Yeah it's super borked atm, plus I tested this locally and it worked so, yippee.

**Pull request merged**
