### PR TITLE
Adds prayer sounds to admins + prioritizes chaplain prayers

### PR DESCRIPTION
**Pull request by ghost**
prayers

Chaplain prayers will have an extended version of the same sound effect in addition to changes in chat. There is a preference for this so it may be turned off by admins who do not wish to hear sounds. Normal players will not have a sound.

In addition, cultists and chaplains both have unique chat messages for prayers.

Sounds:
https://dl.dropboxusercontent.com/u/116194515/pray.ogg
https://dl.dropboxusercontent.com/u/116194515/pray_chaplain.ogg

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Oh gosh.

May the Lord help use poor admins now...

**Comment by Alek2ander** [comment]
If you're adding prayer alerts for admins, time to add a prayer response option which sends a Hallelujah to the player too.

Down with voices in your head, this is a message from your **GOD**, and you *won't* miss it.

**Comment by Ikarrus** [comment]
:+1:

**Comment by Ikarrus** [comment]
I have a request, though.

It sounds like the Hallelujah sound is going to get annoying when spammed. Very often players would pray multiple times in rapid succession, either to add thoughts or to carry on the conversation. I like having sounds like these as alerts, so it'd be a shame to have to turn them off.

Could the regular prayer simply be shortened to "Haa!" and the Chaplain prayer to the full "Hallelujah!"?

**Comment by xxalpha** [comment]
Regular player prayer should not have any sound.

**Comment by Man-Shroom** [comment]
Yeah, only the chaplain prayer should produce sound.

**Comment by Fayrik** [comment]
I know that the Hallelujah is "le epic monty python lolz", but could we please change this to just be a Buddhist's bell or something different? If this feature is ever going to be used, it needs to sound unintrusive otherwise it's going to interfere while I'm working on adminhelps which will get it a nice fast mute and it'll be like you've done no work at all.

**Comment by CollenN** [comment]
I like the idea of it being a bell noise better. Less intrusive, shorter in length.

**Comment by Xhuis** [comment]
Due to popular demand, praying sounds are only played now to chaplains. You also hear the prayer sound from being granted a cookie, and cultist prayers have a unique message as well.

**Comment by Jordie0608** [comment]
If the non-chaplain prayer is removed then don't add it as an unused sound and commented out code.

Also yeah shorter a soundbite would be nice.

Changelog.

**Comment by WJohn** [comment]
If there's no player pray sound, then the chaplain should use the shorter sound that player prayers used to have, as their extended version is WAY too long for something you can spam without delay.

**Comment by Kelenius** [comment]
Or just give the sound a cooldown.

**Comment by Fayrik** [comment]
Or both.

**Comment by Xhuis** [comment]
Chaplain prayer sound shortened. I kept the long version for granting people cookies.

**Comment by Dorsisdwarf** [comment]
If chaplains spam pray, spawn something horrifying to kill them. Respect your god yo

**Comment by TheVekter** [comment]
That sound is -awful-.

**Comment by Xhuis** [comment]
What do you suggest?

**Comment by TheVekter** [comment]
I like the sound for normal prayers, but the chaplain prayer sound is way
too long. Idk, it'd kinda be nice to have a holy sound effect for a normal
prayer (like angels going AAHHH or something) and the HAAAAALELLUIAH for
chaplains.

**Comment by xxalpha** [comment]
Vekter he changed it so normal prayers don't play any sound and the chaplain prayer is short.

**Comment by TheVekter** [comment]
:+1:

**Comment by Dorsisdwarf** [comment]
It's now june, this is merge-ready, and nobody seems to have any outstanding objections

**Pull request merged**
