### PR TITLE
Adds a way for admins to load new zlevels

### LINKED ISSUE #23125: dmm_suite load_map() not initializing things loaded
Nothing loaded is initialized, this makes APCs , comms, and everything else not working.

### PR DESCRIPTION
**Pull request by Cyberboss**
Also refactors zlevel/away mission loading to use `map_template`

This, together with #22778 will fix #23125 

Removes @kevinz000's ghetto way of doing it

### CODE REVIEW

**Comment by Supermichael777** [comment]
feels cold is it a freeze?

though legit this could be cool

**Comment by MrStonedOne** [comment]
it sounds like maybe DMM_LOADER needs to be improved rather then wrapping a wrapper around a buggy system to remove the bugs.

**Comment by MrStonedOne** [comment]
>Removes @kevinz000's ghetto way of doing it

Also, no, I use the same method to profile world start. loading the initial map doesn't show up on profile, so I load runtime station then use dmm_loader to load box station with the profile on so i can see the cost of New() for various things

**Comment by AnturK** [comment]
Yeah, this works this way mostly because in the past the loader was general, now that it's optimized for ss13 there's no reason to merge them really.

**Comment by Cyberboss** [comment]
Ugh, I don't quite feel like dealing with that refactor

**Pull request closed without merging**
