### PR TITLE
adds unintelligible swedish and chav quirk

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

adds quirks that give you the unintelligible, swedish and chav mutation

## Why It's Good For The Game

good

## Changelog
:cl:
add: unintelligible swedish and chav quirk
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
takes away the charm and funny uniqueness of the chef having a swedish accent tbhpqh

**Comment by LoserWasTaken** [comment]
> 
> 
> takes away the charm and funny uniqueness of the chef having a swedish accent tbhpqh

it doesn't though what do you mean

**Comment by PKPenguin321** [comment]
thieving content from genetics smh

**Comment by Pugie** [comment]
> takes away the charm and funny uniqueness of the chef having a swedish accent tbhpqh

Fairly sure chefs have an italian accent.

**Comment by Megarop** [comment]
> ## Why It's Good For The Game
> good

ok but seriously why is it good for the game

**Comment by ExcessiveUseOfCobblestone** [comment]
Your PR is missing proper format, an inappropriate title, or contains incorrect/missing information in your PR body.

Please look over your PR and make sure all items are filled out in a way that someone looking back years from now can easily access and understand.

**Comment by Kaffe-work** [comment]
unintelligible should give you points, not be neutral.

**Comment by LoserWasTaken** [comment]
> 
> 
> unintelligible should give you points, not be neutral.

foreigner doesn't give you any points

**Comment by ExcessiveUseOfCobblestone** [comment]
sorry i was testing the saved reply feature.

DNM cuz your why is trash

**Pull request closed without merging**
