### PR TITLE
meta armory feeds to brig locker room, fixed stacked pipes and unconnected powernet

### PR DESCRIPTION
**Pull request by ShizCalev**
:cl: ShizCalev
fix: Armory on meta now opens into the security locker room
fix: Armory on meta is now connected to power
fix: Armory on meta no longer has stacked pipes
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
why

**Comment by SkeletalElite** [comment]
> why

Because the security locker room has different access than the main hall of the brig. The way it is currently opening the shutters gives lawyers and detectives armory access when they shouldn't have it, if you're not supposed to be able to open the sec lockers, you shouldn't be able to get to the armory shutter either.

**Comment by Cartographer-D** [comment]
I can't forsee a situation in which the Warden would need to regulate weapons for crew and not regulate weapons for officers.

If the station is going up in flames to the extent that the armory is open access to officers, it's probably certain that it would be open access to the crew as well.

Putting the shutters on the gear room makes it easier for the warden to be lazy and not distribute weapons like his job entails or the HoS to just open the shutters and invalidate that part of the Warden's role. It ruins the tactical decision to have the shutters be open or closed. 

 It ALSO has the added problem that if a Warden needed to make the armory open access, they also have to make all the sec gear open access too.

Looking at the map changes, you also removed the quick access door for the warden. Part of the intent is to have a warden be able to get to the armory relatively quickly instead of having to run all the way around.

I am not a fan of this change at all.

**Comment by SkeletalElite** [comment]
> If the station is going up in flames to the extent that the armory is open access to officers, it's probably certain that it would be open access to the crew as well.

This is simply not true. Especially on the dynamic servers, plus if the situation calls for the guns to be handed out to whoever you can just use the door remote.

**Comment by MrDoomBringer** [comment]
Aren't stations are designed to be fallible (to a degree)? Armory should feed into the main brig hall so that a crafty traitor _can_ have a chance of getting into it if the door is left open. There's a reason brig isn't an optimized perfectly defensible bunker with turrets everywhere, its much more fun if a warden DOES have to worry about things like people slipping into the armory, etc.

It's still in brig, so it's not like it's giving away armory access to everyone.
I would still keep the pipe and cable changes though, obviously.

**Comment by MrDoomBringer** [comment]
@SkeletalElite At that point, why not just give all officers an egun to start with? Less hassle that way, right? At some point, "Hassle" should be a part of the game design because it has the opprotunity to breed conflict. That's why you're supposed to take your gamer gear off to shower - it's a hassle, sure, but it's more importantly a mechanic that opens up a slight opportunity for conflict (ie someone nabbing your stunbaton while you're distracted)

**Comment by MrDoomBringer** [comment]
@SkeletalElite At that point, why not just give all officers an egun to start with? Less hassle that way, right? At some point, "Hassle" should be a part of the game design if it has the opportunity to breed conflict. That's why you're supposed to take your gamer gear off to shower - it's a hassle, sure, but it's more importantly a mechanic that opens up a slight opportunity for conflict (ie someone nabbing your stunbaton while you're distracted)

Also

>there really is no reason for the warden to hand out the weapons one at a time

that's literally his job tho 🤔

**Comment by Cartographer-D** [comment]
> 
> 
> Aren't stations are designed to be fallible (to a degree)? Armory should feed into the main brig hall so that a crafty traitor _can_ have a chance of getting into it if the door is left open. There's a reason brig isn't an optimized perfectly defensible bunker with turrets everywhere, its much more fun if a warden DOES have to worry about things like people slipping into the armory, etc.


Literally this.

**Comment by Twaticus** [comment]
iirc the mapper who made the brig revamp specifically wanted the shutters there as a possible weakpoint. 

With the current version, wardens are either handing guns out to sec through the armory desk or theyre actually having to keep watch when the shutters are open. And when theyre not paying attention while the shutters are open, anyone trying to sneak in has to do it right in the middle of the brig leading to more interesting situations and tactics.

Changing this will most likely go back to wardens opening the armory for sec and either not worrying about it because its behind extra doors and the sec gear room, or just forgetting about it entirely because its not an area they can see from their office.

**Comment by BeeSting12** [comment]
If the PR is unacceptable as is then I think this is a good compromise: 
>Another thought would be having the airlock facing the main hall, and keeping the two shutters facing the sec gear room. Best of both worlds or something

**Comment by Cartographer-D** [comment]
> 
> 
> If the PR is unacceptable as is then I think this is a good compromise:
> 
> > Another thought would be having the airlock facing the main hall, and keeping the two shutters facing the sec gear room. Best of both worlds or something

Negates the points being made methinks.

**Comment by SkeletalElite** [comment]
> Putting the shutters on the inside negates the points being made. It isn't best of both worlds and isn't a compromise. It's just doing what you want. Why not just leave it fallible?

Because it's completely inconsistent with every other station and probably smarter to just set open the door next going into the gear room with the door remote so lawyers dont get access to the guns.

**Comment by BeeSting12** [comment]
The armory is still vulnerable. With the armory doors out of view of the warden's office, people can still sneak in through the back and steal stuff. It's just ridiculous to have the shutters feeding out into the brig area which isn't even secure: lawyers, prisoners, and randoms are in there 24/7 defeating the point of having the shutters.

**Comment by Cartographer-D** [comment]
It's almost like it'd be a good idea not to keep the shutters open 24/7 and have the warden do their job and regulate. Maybe stick around and make sure lawyers/randoms/etc. don't slip past you into the armory.

It's a lot more fun to have the shutters out in the open for some risk/reward and extra thing to manage. Just because it's sometimes a hassle for you doesn't mean its suddenly awful for everyone else. It's different, changes the dynamic, and offers great variation from the standard armory and offers non-sec a different way to work with the armory. If you want to go ahead and ruin the fun for others just to increase your personal convenience then I don't know what to say.

**Comment by optimumtact** [comment]
come on shiz you know better than to bundle fixes with balance changes like that

**Pull request closed without merging**
