### PR TITLE
Deletes broken clothing from Xenobiology on box

### LINKED ISSUE #13580: There's an undroppable winter coat hood in xenobiology on box
.

### PR DESCRIPTION
**Pull request by swankcookie**
fixes #13580
Deletes broken winter hood in south of lab
I don't know why the hood was there, the coat has a built in hood.

### CODE REVIEW

**Comment by WJohn** [comment]
You need to use the map merger, man. It's really easy.

**Comment by swankcookie** [comment]
what does it do?

**Comment by swankcookie** [comment]
will do, next time. sorry about that.

**Comment by swankcookie** [comment]
I fucked up

**Pull request closed without merging**
