### PR TITLE
Fixes untouchable windows

### LINKED ISSUE #13354: many of the windows on box are intermittently fucky
Meaning you can't hit them/break them.

Same issue that happened to Wildwest

### PR DESCRIPTION
**Pull request by SuperSayu**
Sorry about that.  Fixes #13354

### CODE REVIEW

**Comment by RemieRichards** [comment]
*shakes fist*

**Comment by Anonus** [comment]
You probably should quickmerge this as it's a relatively large issue.

**Comment by RemieRichards** [comment]
@Anonus was waiting for travis, nerd.

**Comment by SuperSayu** [comment]
I did test it before I put it up and the only side effect was mild increase in cancer rates

**Pull request merged**
