### PR TITLE
Makes Ministation Toxin Airlocks Heat-Proof

### LINKED ISSUE #14139: Heat superconducts through the Toxins airlocks on Ministation.

### PR DESCRIPTION
**Pull request by swankcookie**
Fixes #14139

### CODE REVIEW

**Comment by swankcookie** [comment]
oh shit, tried too sneak-admin myself

**Comment by tkdrg** [comment]
Why did you change telecomms?

**Comment by swankcookie** [comment]
they were giving conflicts. I assumed they were outdated/unused.

**Comment by tkdrg** [comment]
Uh, I think they're very much used? What do you mean by "conflicts"? If you mean not opening the map, that's probably because you didn't tick the ministation presets and loaded it with the boxstation mapfile.

**Comment by swankcookie** [comment]
I fucked up. re-doing this.

**Pull request closed without merging**
