### PR TITLE
[Hotfix] Character save compatibility with custom lizards

### LINKED ISSUE #9979: Lizards busted my saves
though locally it worked fine, apparently I gotta do something to saves to make it work right for servers at large.

Making the issue before someone else can make it and yell at me :cry:

### PR DESCRIPTION
**Pull request by Incoming5643**
I thought you could store a list in a save file

Nooooooooope

Fixes #9979

Please merge asap

### CODE REVIEW

**Comment by Incoming5643** [comment]
And so it was fortold that never again would someone be able to touch the savefile without fucking everything up, at least for a little while.

**Comment by optimumtact** [comment]
savefiles, not even once

**Comment by Incoming5643** [comment]
But seriously though someone should merge this, the longer this isn't fixed the more chance for a server downstream to update then get all upset because I accidentally corrupted their saves.

**Comment by MrStonedOne** [comment]
just a note, I had to revert sybil because of this bug, luckily the update script saves a backup of the save and notes savefiles by putting them in a git repo, and making a commit, and sending it to the backup servers. So I was able to revert.

**Comment by Incoming5643** [comment]
Yeah I'm really sorry, the bug didn't appear during testing for some reason. But I was able to replicate the bug locally with a little hindsight and I'm absolutely sure this works.

**Pull request merged**
