### PR TITLE
Removes safety checks from firelocks

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl: Cyberboss
del: Due to budget cuts. Firelocks no longer have safety features
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
Does this mean that it will DOORCRUSH people?

**Comment by CPTANT** [comment]
Always bothered me, people getting crushed by firelocks is hilarious.

**Comment by Cyberboss** [comment]
@GunHog AIs usually aren't the ones activating the fire alarms

**Comment by GunHog** [comment]
> @GunHog AIs usually aren't the ones activating the fire alarms. Unless they've flooded plasma...

Non-antag AIs use them to contain breaches and to slow people down during a chase.

**Comment by jughu** [comment]
This activates tactical crowbar firelock?

**Comment by KingPhilipIII** [comment]
New ways to murder people. 

Zap with stun prod. Drag to firelock. Crowbar firelock shut on them. Laugh maniacally. Repeat.

**Comment by RandomMarine** [comment]
It'll be a matter of time before someone develops their click-fu skills to doorcrush someone with an airlock AND firelock at once.

**Pull request merged**
