### PR TITLE
Bag of Holding Rework

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Bag of Holding detonations have been significantly reworked.
/:cl:

Why: Bags of holding are super easy to get, super destructive, and basically impossible to repair the damage from. They are my favourite item but they've continuously been a balance problem and an admin headache since they can't easily undo the damage people do when griefing. Went with the actual tabletop impact of bags of holding for inspiration

Bags of holding now create a large area of "chasms" that lead to a new area called the Tear in the Fabric of Reality with a singularity at the center.

Two ladders lead in/out of the Fabric of Reality area, and those ladders lead to random spots in lavaland/space.

Bags of holding are still very overpowered when detonating but theoretically survivable and repairable.

Further plans: Allow people to connect a third ladder there, maybe put special items so insane scientists can purposefully jump in there to try and loot. Maybe not have the other ladders active in lavaland/space until someone enters with a BoH and uses them (and consequences like anomalies or monsters appearing if you weaken the fabric of reality too much, use the ladders, etc)

### CODE REVIEW

**Comment by KorPhaeron** [comment]
reality

**Comment by Arianya** [comment]
What happens to the detonator? Do they just fall in as they would normally? And what happens if you BoH bomb in the tear?

**Comment by 81Denton** [comment]
This looks good! I could even see people build bases down there.

A few things:
- RCDs aren't able to build on top of the tear, but metal rod into lattice -> floor tile is possible.
- Deconstructing lattice built on top of the tear won't drop the metal rod through the tear.
- Indestructible objs like the station self-destruct get transported to the centcom z-level, this is relevant for the next one:
- Edge case: You can put the nuke disk inside the self-destruct and detonate a BoH on top -> both will get transported to the centcom z-level, really screwing over nuke ops.
- Another edge case: If the crew is extra cheeky, they can build a path towards the center, put the nuke disk there and deconstruct all other tiles with an RCD. Looks like this:
https://user-images.githubusercontent.com/32391752/40410060-0becd838-5e6d-11e8-9dcd-a5ff924a4296.JPG
- Sparks and other effects like flightsuit ion trails can fall through the tear, which could possibly get very spammy.
- Ladders sometimes don't connect and give the `The mysterious ladder doesn't seem to lead anywhere.` message.
- Atmos machinery that falls through the tear causes a bunch of runtimes:
```
[09:02:06] Runtime in vent_pump.dm,253: Cannot execute null.return pressure().
[09:02:14] Runtime in LINDA_turf_tile.dm,57: Cannot execute null.merge().
[09:02:28] Runtime in airalarm.dm,597: Cannot read null.gases
```

@Arianya Yeah, they seem to fall down to a random tile. If they don't drop into the singularity, they can take a ladder out or walk off the edge, which dumps them in space.

If you detonate a bag inside, it won't affect the main area but will give the edge a "rim" like this:
https://user-images.githubusercontent.com/32391752/40410206-75625c34-5e6d-11e8-8f1c-e01bc73610e2.JPG

**Comment by KorPhaeron** [comment]
RCDs should be able to build on chasms, not sure why they cant

Sounds like another chasm bug

Bizzare, not sure how to fix off the top of my head

Shouldn't be too bad if they hide a disk on a chasm island since you can floor rod to it

Another chasm problem yeah, I'm sure regular chasms on station will reveal many

The unlinked ladder is not meant to be linked until a miner finds the other half in a box or RnD builds it or something

Atmos machines should stop runtiming once I figure out an alternative to blocks air yeah

**Comment by Arianya** [comment]
Sounds interesting all round.

Peak hilarity value: BoH bombing the bridge to get heads of staff off z-level in revs.

**Comment by Tlaltecuhtli** [comment]
does it mean you can sit there and count as "escaped" for green text?

**Comment by arsserpentarium** [comment]
Surprisingly nice idea

**Comment by DaxDupont** [comment]
Also please be mindful that gun beams also fall into chasms which is a currently open issue, when someone aims a particle accelerator over chasms everyone that sees it nearly gets crashed because of the 43000x falls in chasm.

**Comment by ExcessiveUseOfCobblestone** [comment]
> /global/
> New()

WHEN WILL THIS END

**Comment by ExcessiveUseOfCobblestone** [comment]
Also this is really fourth wall breaking but that can be fixed later :^)

**Comment by GhostEcho** [comment]
Wait, RCDs are SUPPOSED to be able to build over chasms? Holy fuck I just thought we were meant to just put up with em

**Comment by davethwave** [comment]
This seems interesting.

**Comment by AlexTheSysop42** [comment]
Two things: 

1. Will the tear area depressurize?
2. Can't people abuse this to get to centcom?

**Comment by KorPhaeron** [comment]
Alright turns out the disk just straight wont leave if its on centcomm at all so I'm gonna have to do some snowflake check or move this to another Z level

**Comment by davethwave** [comment]
Forgot, does the disk have a specific spawn point?

**Comment by KorPhaeron** [comment]
It does not

**Comment by 81Denton** [comment]
>Will the tear area depressurize?

The tear on the station doesn't, while the tear area on the centcom level initializes with no gases and blocks gas movement.
@KorPhaeron is it intended that it has `air = null`? You can't even use an analyzer or the "view gases" verb there, oddly enough.

>Can't people abuse this to get to centcom?

I doubt it as it's surrounded by 7 tiles of transit space and has noteleport set to TRUE.

**Comment by davethwave** [comment]
Does it prevent bluespace crystal teleportation?

**Comment by Armhulen** [comment]
Super lame area it should be something that is a seizure warning not this LAMO shit

**Comment by Armhulen** [comment]
Or maybe just softly changing rainbow colors yknow something enjoyable to look at

**Comment by Arianya** [comment]
Notes from testmerge: 
* Dense objects can fall on top of the ladders
* Floors don't fall through? Floors remain as bluespace tiles instead of inheriting floor of area that was bombed (Not sure if intended)
* Theoretically, BoH Bombing with one spare boh on  you allows you to maxcap everyone who falls through even if they don't get singulo'd
* The tear will happily eat a SM and become a super matter charged tear in the fabric of reality. No effect on gameplay other then the additional text in the name/description

**Comment by davethwave** [comment]
What would happen if you BoH bomb the 7 by 7 space?

**Comment by cacogen** [comment]
nah gay

**Comment by optimumtact** [comment]
@KorPhaeron the disk not teleporting back to the station when it's on teh centcom z level is surely a bug with the stationloving component @SpaceManiac @vuonojenmustaturska ?

**Comment by optimumtact** [comment]
honestly it sounds like chasms aren't calling forceMove

**Comment by SpaceManiac** [comment]
The bug is with stationloving, it checks for the z-level instead of `/atom/proc/onCentCom()`

**Comment by davethwave** [comment]
You can't push someone that's buckled to a chair into the tear.

**Comment by KorPhaeron** [comment]
@SpaceManiac Probably so it doesnt vanish from the nuke ops base

**Comment by SpaceManiac** [comment]
Double-checked the stationloving PR and it's a straightforward port of how it worked before, so stationloving would need to be changed to blacklist the new area.

**Comment by optimumtact** [comment]
it should be a whitelist not a blacklist

**Comment by GravitronBlue** [comment]
Throwing in my 2 cents worth...

space station 13 2018-05-24 005012

space station 13 2018-05-24 010338

Should probably foolproof this room to prevent escaping into Centcom.

**Comment by chesse20** [comment]
no support at all i love make singularity

**Comment by Dorsisdwarf** [comment]
Neat idea, needs work as said above (adding more ways to crash people is bad, super easy to escape and get to cc, no longer able to stop the nuke, but CAN steal the nuke disk)

**Comment by zaracka** [comment]
Addressing the why, if for whatever reason this doesn't go through, making a singular bag of holding always destroy singularities spawned by bags of holding could work.

I dislike the Tear in the Fabric of Reality area. The gate to the Astral Plane is supposed to close and be one-way only. My thinking was, since the bag isn't magic and uses bluespace technology, opening to a random z-level made sense. For gameplay reasons, the station-side gate doesn't need to close so they can still be destructive.

I think it's too big and square, feel like it would look nicer if it was smaller and more rounded. It should suck objects/mobs into it, just like a singularity.

Alternative idea, expand it into a loot/monster area, but remove the ladders. Maybe give it its own z-level. It's a one-way trip only escapable with conventional methods, like hand tele, jaunter, and whatnot. Except now the gate closes after a specific amount of time, but can be opened again by putting another bag of holding into a bag of holding.

**Comment by Kromgar** [comment]
Blob buff pls nerf

**Comment by zaracka** [comment]
The bag of holding singularity era will be missed, but we must evolve and keep moving forward.

**Comment by ExcessiveUseOfCobblestone** [comment]
>Blob buff pls nerf

Bring the blob too, it's fun for the whole family!

**Comment by davethwave** [comment]
get the blob into tear, auto creates blob walls, auto-attack destroy walls that prevent going out of the area, spreads to everywhere in space.

**Comment by AlexTheSysop42** [comment]
The only thing keeping you in is the transit space which I think affects blobs

Then again, those might spread through space

**Comment by Kromgar** [comment]
I guess blob dropped in the tear means crew loses? Unless they drop in to fight it

**Comment by GravitronBlue** [comment]
From earlier testing throwing more bags of holding into reality chasms usually means some will end up getting eaten by the tear in reality, causing a large 5/15/45 explosion, so I wouldn't be too concerned about blobs winning just because they manage to get inside it.

**Comment by Kromgar** [comment]
Aren't cores immune to explosions?

**Comment by PKPenguin321** [comment]
you know that wizard spell that just fucks everything up in like a 7x7 area and randomizes their positions or whatever
this whole area should have that all the time

**Comment by PKPenguin321** [comment]
yeah that one

**Comment by moonheart08** [comment]
Silly idea that just might improve the place: Figure out a way to proc gen this area in a similar manner to Lava Planet, and fill it with both dangerous hazards and really good loot. Make it potentially worthwhile to come over, but dangerous to stay unless you're really good at the game.

**Comment by KorPhaeron** [comment]
Expanding the area might be cool in the future but I'd rather have the basics working and let someone else expand on it than work on it forever with this PR

**Comment by zaracka** [comment]
> you know that wizard spell that just fucks everything up in like a 7x7 area and randomizes their positions or whatever
this whole area should have that all the time

So a whole area becomes permanently unusable then? Back to square one. Actually kind of worse, because at least with a singularity you can rebuild the area.

**Comment by Dorsisdwarf** [comment]
zaracka, pkp means the alternate dimension i think

**Comment by PKPenguin321** [comment]
yeah

**Comment by AlexTheSysop42** [comment]
That makes it impossible to build anything in there

**Comment by PKPenguin321** [comment]
and the massive singularity 3 feet away doesnt?

**Comment by AlexTheSysop42** [comment]
yeah, the single doesn't suck things in and you can just build around it (and then build a tele to safely go in and out)

**Comment by AlexTheSysop42** [comment]
*singulo (can't edit posts on this computer)

**Comment by AlexTheSysop42** [comment]
*singulo (can't edit posts on this computer)

**Comment by DaxDupont** [comment]
Can you add a admin coord jump on the bag of holding detonation message? Before we could jump to the singu, but since there's no more singu it might be handy do have a coord jump to figure out instantly where it happened.

**Comment by Michael-Ashfield** [comment]
The jaunter does not protect you from failing into the tear in reality, I feel it should protect the user like it does for chasms.

**Comment by KorPhaeron** [comment]
Jaunter is broken for all chasms right now

**Comment by msgerbs** [comment]
This is actually the dumbest thing ever.

**Comment by optimumtact** [comment]
nobody cares, make your own server

**Comment by davethwave** [comment]
Kind of too late to complain as well...

**Pull request merged**
