### PR TITLE
Made asteroid treasure room soulstones usuable by anyone.

### LINKED ISSUE #12296: Artifact room soulstones can't be used by everyone
could be intended if 2much fun but that would be lame

### PR DESCRIPTION
**Pull request by Shadowlight213**
fixes #12296

### CODE REVIEW

**Comment by Anonus** [comment]
DANGEROUS AND UNWISE :+1:

**Comment by Supermichael777** [comment]
Add shells to the list

**Comment by Shadowlight213** [comment]
Shells can spawn in the wizard den room

**Comment by Supermichael777** [comment]
okay also that suit doesn't come with a helmet

**Comment by Fox-McCloud** [comment]
:+1: 


What could possibly go wrong.

**Comment by Firecage** [comment]
Can we just go ahead and remove the shitty feature which makes soulstones unusable normally? Since why is it there in the first place?

Normal crew can use traitor gear
Normal crew can use wands and staffs
Normal crew can learn spells

Honestly we might aswell then make that the normal can't are unable to use eswords or ebows, that they are unable to fire wands or spells, etc.

**Comment by Bawhoppen** [comment]
I agree with firecage

**Comment by Miauw62** [comment]
normal crew cant learn spells, the spellbook is bound to the wizard on its first use
wands and staffs are intended for summon magic

soulstone restrictions were a neccesary addition to cult because non-cult constructs caused a huge amount of confusion and bugs, and even if we wanted to remove them its byond the scope of this pr.

**Comment by MrPerson** [comment]
I think we should close this and the related issue.

**Comment by Shadowlight213** [comment]
@MrPerson I don't understand why you would close this? This makes the soulstones in the mining treasure rooms actually be able to be used. This doesnt touch cult or anything. It just makes the stones not completely useless.

**Comment by MrPerson** [comment]
The logic of not having a stone for the chaplain still applies just as much to the treasure room.

**Comment by Shadowlight213** [comment]
@MrPerson well the treasure rooms are fairly random. There's no guarentee that you'll find a soulstone or if it will even spawn. If it's still a bad idea, the soul stone can simply be removed from the treasure room. There's no reason to keep it in its current state.

**Comment by MrPerson** [comment]
I can agree with that. I think the idea is that a lucky cultist could use it but the reward is too trivial.

**Comment by Miauw62** [comment]
yeah, this is fine. it's obviously intended that you get a soulstone if you're lucky which isn't an extremely game-breaking thing or anything since you can't get it every round and need to be an antag to actually use it effectively.

**Comment by Lumipharon** [comment]
@Miauw62 normal crew can learn from normal spell books, and if you gib or incinerate the wizard, you can also use their main spell book (and typically summon magic to get a free point and use that to learn a spell of choice).

**Comment by AnonymousNow** [comment]
I approve; when soulstones were made unusable on the crew, I disagreed until I was blue in the face, and offered lots of suggestions that were completely blanked. Getting some usability back on something that's otherwise pointless is a great boon.

**Pull request merged**
