### PR TITLE
Redone Coffin Icons (Dikembe Mutombo Edition)

### PR DESCRIPTION
**Pull request by Chuckleberry-Finn**
[Changelogs]: 
:cl: Chuck
imageadd: New Horizontal Coffin Sprites
/:cl:

dd

[why]: stop #35106, #35108

### CODE REVIEW

**Comment by Xhuis** [comment]
These are really fancy instead of cheap-looking and look good! I like this one most out of all the PRs up right now.

**Comment by Bawhoppen** [comment]
Coffin sprite war now

**Comment by ChuckTheSheep** [comment]
Working on some tweaks Wj suggested.

**Comment by PKPenguin321** [comment]
Choco coffin

**Comment by ChuckTheSheep** [comment]
Lightened up the wood, adjusted the shading, and redid the interior. With a little pillow for good measure.

**Comment by Grazyn** [comment]
It's that mahogany? it's really dark

**Comment by uraniummeltdown** [comment]
Looks great 👍

**Comment by WJohn** [comment]
These look much better now that you've spruced them up further.

**Comment by ChuckTheSheep** [comment]
@Grazyn I matched it to the wood color used elsewhere, the old coffins always stood out in that way.

**Review by Cyberboss — APPROVED** [review]

**Comment by praisenarsie** [comment]
this is just me but i think the cross could be more brighter

**Comment by Xhuis** [comment]
I guess we got something good out of the code war after all!

**Comment by Bawhoppen** [comment]
I guess competition really does drive innovation.

**Pull request merged**
