### PR TITLE
[WIP] Use reinforced plasma glass in engine

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
tweak: Singularity/supermatter setups now use reinforced plasma glass as opposed to high pressure glass.
/:cl:

Maps done so far:
- [x] Box
- [ ] Meta
- [ ] Cere
- [ ] Pubby
- [ ] Delta

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
for some reason there seems to be alot of changes. i use fastDMM. did I accidently make too many changes?

**Comment by ShizCalev** [comment]
uh... I recreated your changes on my end and didn't encounter this issue at all. Not sure what you did.

**Comment by ShizCalev** [comment]
@MoreRobustThanYou see https://github.com/monster860/FastDMM/issues/35

**Comment by ShizCalev** [comment]
@MoreRobustThanYou https://github.com/monster860/FastDMM/issues/35

Also, fastDMM is far more aggressive with pruning unused dictionary entries than TG's mapmerge is.

**Pull request closed without merging**
