### PR TITLE
Medieval pirates patch

### PR DESCRIPTION
**Pull request by uaioy**
## About The Pull Request

- moved where the warlord spawner is, should make warlord be the first pirate to spawn
- added propulsors to the ship
- crude helmet doesn't hide your hair anymore (it didn't fully cover your head so it made you bald)
- shortsword sprite has its original colours (i was pranked with the whole -100 DM file and in a desperate attempt, made the shortsword have the same colours as the claymore)
- the message to pay the pirates is different (i used the same one as tider pirates as placeholder)
- their helmets have flash protection (borgs knock them down too easily, flashbangs will still knock them down because no bowman)
image
## Why It's Good For The Game
some things that i missed, plus the pirates are knocked over too easily by borgs
## Changelog
:cl:
qol: the first Medieval pirate to spawn will be the Warlord, warlord and crude helmet have flash protection
fix: Medieval shuttle has actual engines now
fix: Shortsword has its original colours
fix: Crude helmet no longer makes you bald
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
wouldnt it be better to just make their helmets block flashes? that way it fits better with their gimmick. theres already helmets that block flashes (eg. specific EVA helmets) and giving low-tech medieval pirate a set of blazing hot raybands seems a bit strange

**Comment by CCC23** [comment]
> Admiral

they REQUIRE the drip

**Comment by uaioy** [comment]
> wouldnt it be better to just make their helmets block flashes? that way it fits better with their gimmick. theres already helmets that block flashes (eg. specific EVA helmets) and giving low-tech medieval pirate a set of blazing hot raybands seems a bit strange

its mainly about balance, when defeated they yield 4 helmets that are already peppper proof and have high melee resist, which means they can choose more freely what to put in their eyes and mouth slot (e.g, a cig[nicotine or whatever chem concoction] and mesons)

**Comment by SyncIt21** [comment]
Why is this labeled "NO GBP"? Especially with a balance PR.

> balance: Medieval pirates have sunglasses 

This could have labeled as qol, doesn't look like a balance PR at all actually

**Comment by uaioy** [comment]
> Why is this labeled "NO GBP"? Especially with a balance PR.
> 
> > balance: Medieval pirates have sunglasses
> 
> This could have labeled as qol, doesn't look like a balance PR at all actually

yeah u r right its more of a qol thing, they're forced to directly attack the crew so it kinda sucked when an item borgs and anyone can easily print would instantly disarm them (and then either be gored by rabid people or carried to security to be executed)

**Review by Maurukas — COMMENTED** [review]
Please push an empty commit or merge master and push to force Mapdiffbot to rerun. It has been fixed.

**Comment by jlsnow301** [comment]
> wouldnt it be better to just make their helmets block flashes? that way it fits better with their gimmick. theres already helmets that block flashes (eg. specific EVA helmets) and giving low-tech medieval pirate a set of blazing hot raybands seems a bit strange

agree here, it's antithematic

**Comment by uaioy** [comment]
ok i didnt know it would add the no GBP tag again after doing a commit

**Pull request merged**
