### PR TITLE
Shotgun party, new shells, an improvement and a fix

### PR DESCRIPTION
**Pull request by Thunder12345**
Adds a new ion shell. Shotgun version of ion rifle, more lethal at point blank range, but effect suffers at longer ranges.
[Needs 1 x empty techshell, 1 x ultra high power microlaser, 1 x ansible crystal] ionslug

Adds a new laser slug. Identical to the standard laser, but able to be fired from a shotgun.
[Needs 1 x empty techshell, 1 x high power microlaser, 1 x advanced capacitor] laserslug

Improves the improvised shell, with a new and more improvised sprite, and a tablecrafting recipe.
[Needs 1 x grenade casing, 1 x metal sheet, 1 x cable coil, 10 units welding fuel] improvslug

Adds overloading of the improvised shell. Extra random, has 3 to 8 pellets, each does 0 to 10 damage. Do you feel lucky?
[Needs 1 x improvised shell, 5 units black powder] improvslug

Fixes the FRAG-12 shell, it now actually explodes on impact.

### CODE REVIEW

**Comment by WJohn** [comment]
Tablecrafting improvements when

It's so comically improbably anyone will ever find any of these...

**Comment by Thunder12345** [comment]
Any more suggestions? I'm all out of ideas for now.

**Comment by PKPenguin321** [comment]
ion gun one makes sense since it's shotgun spread ion
laser one's way too hard to make for one laser, but i'm not sure what a better recipe would be

**Comment by Jordie0608** [comment]
Changelog

**Comment by Thunder12345** [comment]
Changelog added, this should be ready to merge whenever

**Comment by Jalleo** [comment]
Pie shell
Ingredients
Bluespace shell and multiple pies 
Nuff said for the clown. Unless we already have this.

**Pull request merged**
