### PR TITLE
Changes advanced medkit contents

### PR DESCRIPTION
**Pull request by googobbug**
## About The Pull Request

Buffs the advanced medkit a bit. The synthflesh patches and gauze have been replaced with medicated sutures and advanced burn mesh.

## Why It's Good For The Game

The advanced medkit is a little underwhelming right now. You can already get synthflesh from the nanochem and pent acid from the toxin kits, leaving the atropine pens as the only unique thing inside. The advanced healing stack items aren't too commonly seen and I think they'd make the advanced medkit more unique without making it too powerful.

## Changelog
:cl: Bumtickley00
balance: Changed the contents of the advanced medkit
/:cl:

### CODE REVIEW

**Comment by Ryll-Ryll** [comment]
Gauze is still very useful for treating bleeding and other wounds, removing it from the kits would probably be a downgrade

**Comment by AdmiralPancakes1** [comment]
> Gauze is still very useful for treating bleeding and other wounds, removing it from the kits would probably be a downgrade

Plenty of other places to get gauze though. White and red kits have some, and there's a ton in the nanomed.

**Comment by ExcessiveUseOfCobblestone** [comment]
the kits are just there for people who are too lazy to make the chems, i dont think it should act as a method to bypass bot/chem interactions.

**Comment by AdmiralPancakes1** [comment]
Hmm, I get what you mean. This does step on botany's content a little, but then again I've seen botany make these items exactly once. Fixing whatever causes botany to never make these items is probably the move.

**Pull request closed without merging**
