### PR TITLE
Adds mutation toxin recipes for roundstart races.

### PR DESCRIPTION
**Pull request by Wilchenx**
:cl: Wilchen
add: Recipe for felinid mutation toxin, the reagent is soymilk
add: Recipe for moth mutation toxin, the reagent is hippie's delight
add: Reciple for fly mutation toxin, the reagent is bad food made from burned mess
/:cl:

Didn't add plasmamen because its very fucking lethal as opposed to midly annoying at most.

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
If this gets added then we add abductor mutation toxin.
If we add abductor mutation toxin then every race will get added again.

Don't add this pls

**Comment by Wilchenx** [comment]
>If this gets added then we add abductor mutation toxin.

what

**Comment by ishitbyabullet** [comment]
@Wilchenx all the mutation toxins except a few were removed because 'lol that's dumb but timestop is a good idea my dudes' and now the only way to become some races is basically the most rng shit ever imagined.

Maybe abductor toxin is a bit too much however someone will eventually argue on why they should re-add a r ace that was previously a mutation toxin even if it's something dumb like shadowpeople.

**Comment by Wilchenx** [comment]
Well, this race was never a mutation toxin so we're free from that argument.

**Comment by CosmicScientist** [comment]
:thinking:

**Comment by CosmicScientist** [comment]
One ingredient... could it be a perfect recipe?
:thinking:

**Review by francinum — CHANGES_REQUESTED** [review]

**Comment by Grazyn** [comment]
le soyboy meme so funnie xD

**Comment by Therapist1** [comment]
dumb bait pr

**Comment by Tlaltecuhtli** [comment]
>adding all start race is out of scope
yep this is only a fetish content pr

**Comment by tralezab** [comment]
Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.

**Comment by XDTM** [comment]
The line between available races and unavailable in mutation toxins currently is if they're roundstart-available; lizards and humans are already there so there is an argement in favor of this pr.

**Comment by tralezab** [comment]
Then let them post that, seems fine to me. I just don't get why they get to output half-assed pulls that don't follow the repository rules, it's pretty insulting to people who do.

For example, their last 2 prs were "rebases to citadel" and "adds tarajans"

Am I missing something here?

**Comment by ishitbyabullet** [comment]
@XDTM i still dont like you for touching the ayy toxin.

ayy
we lost so much.

**Comment by tralezab** [comment]
And just because i'm funny both of those prs also did not give a reason for why they were created

**Comment by 81Denton** [comment]
@XDTM I'm in favor of adding fly/moth/plasmaman mutation toxins as well then

**Comment by Wilchenx** [comment]
@Tlaltecuhtli did you just downthumb all my comments 😂 holy fuck thats special

@tralezab you act like you've never seen a goof pr before

@81Denton I could easily readd moth/fly mutation toxins too but not plasmaman as its easily one of the strongest chems in the game due to it basically killing you.

**Comment by epochayur** [comment]
you know someone's buttflustered when they start replying to every post

👎 dumb meme PR, how has this not been closed?

**Comment by tralezab** [comment]
@Wilchenx I don't think you should justify fairly consistently breaking repository rules by citing someone doing worse

your track record is lame but all i'm asking is for you to put a reason in the op

**Comment by Wilchenx** [comment]
My reason is, currently we only have toxins for two roundstart races. There's really no explaination why there's only two, so i just added this one as it was recently added as a toxin, this is just a recipe for it.

As i've said i can easily readd other non-dangerous roundstart races.

**Comment by F-OS** [comment]
At least add a less memey reagent for making this.

**Comment by Wilchenx** [comment]
i wanted to change the reagents to somewhat reflect the races that are still easily obtainable

**Comment by Tlaltecuhtli** [comment]
>Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

close this nazi pr

**Comment by ishitbyabullet** [comment]
Are people unironically finding this bad because of soymilk? What the fuck?

I looked up 'do cats like milk' and saw that apparently most cats are lactose intolerant. Soy milk apparently has no lactose however it does have issues of it's own.

Either way it's not the end of the world if a fucking mutation toxin requires soy milk meanwhile some assholes in the right call people 'soy boys'. This also gives the item more use besides shitty tofu.

**Comment by Wilchenx** [comment]
I think its more of a case of "latch onto anything that you can to provoke a argument"

**Comment by epochayur** [comment]
a case of "quickly add other species when it's made painfully obvious that the PR is fetish content"

**Comment by TheDreamweaver** [comment]
Sorry, aren't these all round start races, and isn't this using a method *already in place* to switch between roundstart races? While I agree the formatting of this PR and possibly the reagents used was a bit lazy, I don't get what exactly people are freaking out about? Or is this another case of "I saw the name of a non-human race in the PR so it must be something fetishy so let me read no further"?

**Comment by tralezab** [comment]
@TheDreamweaver When I looked there was no reason given, and it was only felines and not every other roundstart race. Now that the pr has reasoning and it more generally moves all races into a mutation toxin option, I don't see why not

"Oh so you hate catgirls i get it"

No, but if you can't justify adding catgirls to the pool because roundstart races are there while refusing to port the other roundstart races.

**Comment by Wilchenx** [comment]
@tralezab i refused to port all races, not the roundstart ones

**Comment by tralezab** [comment]
i missed that, my bad

**Comment by TheDreamweaver** [comment]
As always a bit of reading on the readers part and as well as additional clarity on the creators part, solves most of these issues.

**Comment by Grazyn** [comment]
Soy milk is meme and doesn't reflect the race in any way. Please don't make this PR fool you into giving your cat soy milk.

"Stachyose and raffinose are the sugars found in soya milk and although they can be digested by microbes in the gut, they cannot be digested by enzymes the cat produces. As a result, cats fed soya milk will often suffer from flatulence and digestive upset."

**Comment by Wilchenx** [comment]
Can i give my catboy some soy milk?

**Comment by Grazyn** [comment]
From what I understand of the lore, cat people are more felinized humans than humanized cats, so maybe they don't suffer from the same enzyme deficiencies as their smaller, furry brethren.

I still fail to see the link between soy milk and cats, since you said it "reflects the race", I would like it explained.

**Comment by Kagus** [comment]
Worth mentioning that fly-ifying someone with a mutation toxin will let you obliterate them with a flyswatter-turned-esword.

Still probably not as lethal as turning someone into a catperson, but it's handy to keep in mind.

**Comment by AlexTheSysop42** [comment]
@wilchenx @tlaltechuhtli #39639 didn't break the guideline, as it didn't actually update the availability of any mutant races. The toxin was added, but, as the PR stated, you couldn't _get_ it.

**Comment by 81Denton** [comment]
It updated the availability since players can get it through strange seeds

**Comment by actioninja** [comment]
You can get ALL of the species mutation toxins via strange seeds.  I submitted it because with felinids being a distinct race not having a dedicated mutation toxin seemed more like an oversight than an intentional decision.  So availability of mutant races was technically changed but not really since botany now has a very low chance of turning people into catgirls when before they had a very low chance of turning people into skeletons, abductors, shadowpeople, or worst of all plasmemes.  I've actually rolled plasmaman mutation toxin recently and was too terrified to actually use it considering how dangerous something like that is.  I could see having an objection to mutation toxins showing up in strange seeds but the most you can say about my pr was that it added a harmless version of something that already existed in far, far more dangerous format.

Jesus I can't believe I'm having to defend a shitpost pr I made at 3am in like 20 minutes.

**Pull request closed without merging**
