### PR TITLE
Aluminium with two i

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
spellcheck: For consistency's sake, aluminium is now universally spelled with two 'i'.
/:cl:

I changed the two remaining cases of "aluminum" to "aluminium". It wouldn't make sense to have a mix of American/British spelling with bugs like #35443 and #35452 around.

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Changing the name of the define violates CONTRIBUTING.MD revert that part please

**Review by Cyberboss — APPROVED** [review]

**Comment by 81Denton** [comment]
Just curious, what part did it violate?

**Comment by Hatfish** [comment]
this is an american codebase, go back to terry

**Comment by ExcessiveUseOfCobblestone** [comment]
*spills contents of this pr into boston harbor*

**Comment by Jordie0608** [comment]
@Cyberboss refers to https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#enforced-not-enforced
but it's silly here because changing the defines isn't any more violatory than the previous 2 PRs and `aluminum` is just wrong.

**Comment by PKPenguin321** [comment]
`aluminum` is the correct American spelling so technically it would fall under that contributing guideline but i care more about standardization tbh

**Comment by 81Denton** [comment]
Yeah, it could be in Italian for all I care as long as everything is standardized

**Pull request merged**
