### PR TITLE
Renames Charcoal to Anti-Toxin

### PR DESCRIPTION
**Pull request by Iamgoofball**
This is a very highly requested change among all /tg/ players.

### CODE REVIEW

**Comment by Memendia** [comment]
lmao

**Comment by duncathan** [comment]
:+1:

**Comment by SconesC** [comment]
:+1: honestly people still call it antitoxin

**Comment by Core0verload** [comment]
fuck you goof

**Comment by Miauw62** [comment]
:+1:

**Comment by phil235** [comment]
Funny but let's not clog up the system with joke PRs.

**Pull request closed without merging**
