### PR TITLE
Firesuits no longer provide low pressure resistance.

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request
As the title says

Amongst other things, there have been a few consistency updates with this change as well. Plasmamen can no longer use firesuits as a means of being fully sealed, since they don't stop all forms of pressure damage anymore.

Spacesuits, modsuits and the likes will still completely block all pressure damage.

## Why It's Good For The Game
They're firesuits and it doesn't fit their intended gameplay purpose for them to be used in low pressure situations. If we have situations where firesuits are used for low pressure gameplay, then people should be using space suits instead. They're supposed to be used in plasmafires, not space.

## Changelog
:cl:
balance: Firesuits no longer provide low pressure immunity. Wearing a firesuit no longer counts towards being sealed up as a plasmaman.
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Considering that there are maximum 20-30 spaceproof suits on the station, and we don't have any temporary measures for not dying to the low pressure, nerfing fire suits which are used as ghetto evas, is just making the game less playable on highpop.

**Comment by SargesC** [comment]
This makes spacing any part of the station a death sentence for anyone without eva access. Firesuits a good compromise because it will let you survive space but not for any extended period of time without loading up on coffee unlike the space suit which is locked away.

**Comment by GPeckman** [comment]
If you're going to remove pressure protection from firesuits, could you at least make them actually protect you from fires? Because without _something_ like that they're basically worthless. (I am aware that they still stop high pressure damage, but that's too niche to be useful)

**Comment by Loafin34** [comment]
you could just change plasmamen helmets to not protect from pressure as well, but a firesuit nerf because plasmemes use it is a bit over-the-top.

**Comment by DATA-xPUNGED** [comment]
> Considering that there are maximum 20-30 spaceproof suits on the station, and we don't have any temporary measures for not dying to the low pressure, nerfing fire suits which are used as ghetto evas, is just making the game less playable on highpop.

I've honestly never touched a firesuit to protect myself against being spaced it's manageable

**Comment by OuroborusReporter** [comment]
This makes plasmemes even less likely to be revived after death. If a plasmaman is dragged into medbay, stripped naked from whoever killed them, the only way to revive them and keep them mobile is to:

1. Order a plasmaman outfit through cargo and hope cargo is actively running shuttle orders
2. Get a full space suit from EVA, and hope you can get into EVA and that the max 8 suits in there haven't been stolen
3. Slap a firesuit on them, before this PR
4. Revive them on a stasis bed and just never let them leave, or revive them under a shower and have them catch fire once it stops

**Comment by SkeletalElite** [comment]
TBF they're not very good at their "intended game play purpose" of being used in a fire either so if you're gonna nerf this you could at least make them a little more effective against fires.

**Comment by uaioy** [comment]
might wanna give tider pirates full eva suits or something else then, since right now their method of exploring space is EVA helmet + firesuit + coffee

**Comment by Moonlit2000** [comment]
Doesn't this screw over scientists trying to add scrubbers to the gas mixing chambers?

**Comment by Dawnseer** [comment]
> Doesn't this screw over scientists trying to add scrubbers to the gas mixing chambers?

It does

**Comment by necromanceranne** [comment]
End of an era of makeshift EVA.

**Comment by DaydreamIQ** [comment]
Might wanna give sci's some kind of EVA suit or hell give them a reason to finally have a research modsuit for their mixing chamber

**Comment by SmArtKar** [comment]
I feel like there still should be a way to ghetto your way into space, just with some more effort. Seal it up with some tape and wires, maybe, and make the seal break when you take too much damage?

**Comment by GuillaumePrata** [comment]
> Plasmamen can no longer use firesuits as a means of being fully sealed, since they don't stop all forms of pressure damage anymore.

This has been needed for a long time.
There are few things that gets me more disappointed in a round than antagonists that just go hide in space being cowards, and plasmamen were often the worst offenders.

> If a plasmaman is dragged into medbay, stripped naked from whoever killed them

By what I quickly read in the code, you can still use a firesuit to stop self ignitions, just can't sit in space only with a suit.

And honestly, if a plasmamen gets burned to a crisp *they should be hard to revive*
That is like.... 80% of their downsides and it is too easy to bypass it in the current state, the meta around plasmamen slowly turned them into species with literally no friction as they ignore half of the game and then ignore half of their own features.

**Comment by Jackal-boop** [comment]
A high pressure fire can very quickly turn into low pressure with a few extinguisher blasts due to our shitass atmos

**Comment by Deultus** [comment]
fire suits were the only way to survive a sudden plasma flood, well, that's not going to happen with this PR, and that's sad.

**Comment by Deultus** [comment]
> > Plasmamen can no longer use firesuits as a means of being fully sealed, since they don't stop all forms of pressure damage anymore.
> 
> This has been needed for a long time. There are few things that gets me more disappointed in a round than antagonists that just go hide in space being cowards, and plasmamen were often the worst offenders.

probably because they are literally the weakest race in combat and are not capable of normal confrontation. even the toolbox is a weapon for quickly killing plasmamen, let alone any other laser-level weapons on the station.

**Comment by SomeoneYouProbablyKnow** [comment]
Fire suits are a nice ish anti spacing measure. That part of it should stay, people who couldn't get their hands on an eva suit should have some recourse. Can definitely make fire suits less ubiquotous.

the real culprit is coffee, it's another dumb super acessible chemical that negates the danger of space nearly by itself. Firesuit catching strays.

**Comment by SimplySmiley123** [comment]
> This makes spacing any part of the station a death sentence for anyone without eva access. Firesuits a good compromise because it will let you survive space but not for any extended period of time without loading up on coffee unlike the space suit which is locked away.

Yeah, it's great for emergencies.

Often times you won't be able to get an EVA suit, command players tend to ignore pleas for opening EVA storage, same as AIs.
With modsuits taking way too long to matter.

**Comment by Exester509** [comment]
> And honestly, if a plasmamen gets burned to a crisp _they should be hard to revive_ That is like.... 80% of their downsides and it is too easy to bypass it in the current state, the meta around plasmamen slowly turned them into species with literally no friction as they ignore half of the game and then ignore half of their own features.

No, no it's not, 80% of their downsides is their absurd 50% vulnerability to the two most common types of damage in exchange for not suffering toxin damage from poisons (while being unable to heal tox with chems as well, mind you).
A plasmaman burnt to a crisp isn't harder to revive than humans unless his envirosuit or helmet is destroyed/taken away, in which case it's just a stupid knowledge check not even on the actual plasmaman player, but on a doctor that might not have anything to do with plasmamen. It doesn't even add tedium because getting ways to stabilize a naked plasmaman isn't that hard at all.

I think people overstate how much plasmamen abuse these mechanics, considering they're sufficiently geared up to explore space by themselves, and no antagonist will ever have trouble finding an actual EVA suit. I'm pretty damn confident that the most common use for emergency firesuits is for actual emergencies, both by plasmamen and other species. Removing pressure protection won't help either side.

**Comment by moocowswag** [comment]
This just makes everyone more likely to flood genetics which is funny because we keep getting maps that dont have it next to a public hallway , seems like a joint effort between map and code to make sure they get tided.

**Comment by SomeoneYouProbablyKnow** [comment]
> This just makes everyone more likely to flood genetics which is funny because we keep getting maps that dont have it next to a public hallway , seems like a joint effort between map and code to make sure they get tided.

Let's be real 80% of players don't care enough to powergame, so it's not gonna cause more players to tide.
The 20% are either tiding already or abusing coffee with some other thing like riot armour

**Comment by TheVekter** [comment]
This is one of those very rare cases where I agree with most of the complaining here; low pressure damage is extremely annoying and there's not really a way to deal with areas that are exposed to vacuum without having an EVA suit, of which most stations have maybe six.

Is this actually addressing an issue where people are actively over-using these items? Otherwise I'm not sure what this is meant to correct.

I'm also usually against arguments of soul, but the ability to chug a coffee and go for a spacewalk with a firesuit on is a classic SS13 "thing" and I don't see a reason to remove that.

**Comment by SomeoneYouProbablyKnow** [comment]
> I'm also usually against arguments of soul, but the ability to chug a coffee and go for a spacewalk with a firesuit on is a classic SS13 "thing" and I don't see a reason to remove that.

"I'm against the argument of soul except the cases where i like the feature" unironically based.

But also there's a difference between chugging coffee for a short space walk and one cup being enough to make space a non-issue for essentially the whole shift or definitely for long enough to come back to the station and get another cup since they are everywhere. It's not even a special cocktail from a bartender (like the redundant anti-freeze) it's literally the basic ingredient coffe.

> I would only really agree with merging this if #85712 was also merged, otherwise you're making venting areas significantly more powerful without giving the crew any way to handle it.

Funny eva suits but that's an even greater loss of soul. The emergency suit is cool but also firesuit my beloved.

**Comment by TheVekter** [comment]
> > I'm also usually against arguments of soul, but the ability to chug a coffee and go for a spacewalk with a firesuit on is a classic SS13 "thing" and I don't see a reason to remove that.
> 
> "I'm against the argument of soul except the cases where i like the feature" unironically based.

I should clarify that I'm against arguments of soul in cases where the only reason to resist a change is soul. Stuff like not wanting to change a sprite because of soul doesn't pass the vibe check for me.

> But also there's a difference between chugging coffee for a short space walk and one cup being enough to make space a non-issue for essentially the whole shift or definitely for long enough to come back to the station and get another cup since they are everywhere. It's not even a special cocktail from a bartender (like the redundant anti-freeze) it's literally the basic ingredient coffe.

This is true, but I think that's more an issue of how temp loss works in the game and could be addressed separately if that was the concern.

> > I would only really agree with merging this if #85712 was also merged, otherwise you're making venting areas significantly more powerful without giving the crew any way to handle it.
> 
> Funny eva suits but that's an even greater loss of soul. The emergency suit is cool but also firesuit my beloved.

Eh, I'm a realist. This is probably getting merged, so I might as well hope for some kind of common ground.

**Comment by SomeoneYouProbablyKnow** [comment]
> This is true, but I think that's more an issue of how temp loss works in the game and could be addressed separately if that was the concern.

Yes which is why i said the firesuit is catching strays. The real issue is temp and chemistry, but firsuits are the visible part of how players are working around it.

> Eh, I'm a realist. This is probably getting merged, so I might as well hope for some kind of common ground

Probably, the suits are neat but firesuits are impecable drip.

**Comment by D4C-420** [comment]
Don't remove the low pressure resist off the atmos fire fighting suits. Those are suppose to be used when dealing with wacky atmos beyond just the burning part of a plasma fire and as someone else has stated because of the way atmos works, most fires ends up leaving a low pressure environment. This really just dissuades using fire suits at all since the moment someone with a fire suit uses a normal fire extinguisher, the gas cools down towards 2.7k, meaning the area has cold, spaced like gas.

**Comment by CCC23** [comment]
its yo ho hover

**Comment by DrAmazing343** [comment]
Definitely will need to see the other PR merged, for this- ghetto EVA has been a very valuable way to even odds, and I've not seen such an intense amount of cowardtags running to space with shit like this. If they're gonna commit, they tend to get better gear, either MOD or Syndie stuff, or both. The reasons I'm reading here still don't seem good enough to rip out this feature, but if it's GOING to happen, might as well offer an alternative.

**Comment by Dawnseer** [comment]
So when will we remove ghetto surgery and chemistry?

**Comment by Redrover1760** [comment]
This screws with toxins. You get given a firesuit in lockers which you use to enter the vacuum that is the burnmix chamber. Now you have to get an eva suit through access you dont have just to prep a chamber thats better than the default shit.

**Comment by iwishforducks** [comment]
I don't think ghetto EVA even needs a nerf in the first place, honestly.

**Comment by LemonInTheDark** [comment]
IDK I kinda like the idea of a highly scuffed "wrong feeling" space walk tool, I think if there are issues with it as of now they are with body temperature being FAR too forgiving more then anything like this

**Comment by alien3301** [comment]
Why not just make coffee metabolize much faster so you can't just completely ignore space with one cup?

**Comment by SimplySmiley123** [comment]
> IDK I kinda like the idea of a highly scuffed "wrong feeling" space walk tool, I think if there are issues with it as of now they are with body temperature being FAR too forgiving more then anything like this

It's not body temperature being forgiving, especially if you're a lizard player shit's annoying AF to deal with if you don't use the one simple drink - coffee.

Coffee's the problem. Not the suit itself. Not really how body temperature being "forgiving".

**Comment by TheVekter** [comment]
For what it's worth, I did talk to Watermelon in coderbus and he committed to merging the emergency space suit PR after this one goes through, so while it's not the ideal solution, it's something.

> This screws with toxins. You get given a firesuit in lockers which you use to enter the vacuum that is the burnmix chamber. Now you have to get an eva suit through access you dont have just to prep a chamber thats better than the default shit.

I will probably go back and replace those with either the emergency EVA suits or a snowflake version of them once this merges. Ping me on Discord if this actually ends up needing doing.

**Comment by ArcaneMusic** [comment]
One thing worth noting, is that within cargo there are packs that have additional EVA suits, but admittedly it can be difficult to gather larger sets due to the fact they're offered as single sets each
See: 
`/datum/supply_pack/emergency/plasma_spacesuit`
`/datum/supply_pack/emergency/spacesuit`

I wouldn't mind a PR that offers the single suits as goodies, and a larger bulk order crate as we've done to things in the past.

My 2-cents:
I think this PR does bring up a very valid concern of how common they are, but that there should be at least some level of makeshift alternative to fill the gap between axing lets say, half of the firesuits, and making them protect less against vacuum. In real-life, fire-resistant rubber is a common older material used in spacesuits, and notoriously some rubber does not handle cold temperatures well, so an argument could be made for a compromise where below freezing, firesuits start to take additional ticks of obj-level damage while offering the same level of protection, and then destroying themselves after being cold temperatures for that long.

**Comment by SomeoneYouProbablyKnow** [comment]
Cargo is cargo but it's no substitute for an emergency eva option. Firesuits and those emergency suits are something you go looking for when it's an "oh shit" type of situation. Can't go to cargo and wait on your order.

Honestly i don't know why everyone's so intent on doing stuff to fire suits when there are like 3 different problems with how stupid coffee is and there's a whole heretic path rework created BECAUSE coffee completely negates temperature. BUT seeing a dude with 3 fire suits hot swapping them in space as they sequentually crumble to dust would be funny as hell.

**Comment by Redrover1760** [comment]
Also void path gives immunity to damage to low temperature as well as self-resp but not low pressure immunity, essentially requiring you to use a firesuit to go out into space. This sorta makes that ability useless otherwise.

**Comment by Momo8289** [comment]
> One thing worth noting, is that within cargo there are packs that have additional EVA suits, but admittedly it can be difficult to gather larger sets due to the fact they're offered as single sets each See: `/datum/supply_pack/emergency/plasma_spacesuit` `/datum/supply_pack/emergency/spacesuit`

Those require EVA access to open, which leaves us with the same issue. Without EVA access, you're fucked. And as someone else already said, cargo is not a substitute for emergency suits.

**Comment by Cheshify** [comment]
I personally disagree with this PR because I think running out an airlock as an assistant at the earliest convenience, with a bottle of coffee at my hip and a firesuit on, is very fun.

**Comment by Jacquerel** [comment]
This has sat open for two weeks because nobody is brave enough or agrees significantly enough with the change to merge it despite resistance.
Very very few people actually seem to want this to happen, and I am significantly inclinced to agree with the idea that at this point firesuit spacewalking is part of the "soul" of the game. I don't really find the stated reasoning in the PR that convincing personally and it seems silly to merge it with the expectation that we'll then immediately merge a different PR that puts them back in with a different name in every emergency locker when we could just keep the firesuits we already have.

I'd be interested in more of a revamp to how mob temperature equalisation works, and/or space's threat in general, but I don't think targeting only or specifically firesuits really solves any particular problem the game has right now.

**Comment by SomeoneYouProbablyKnow** [comment]
It's funny but when every second assistant is capable of staying in space for as long as their internals last em (or more likely they run out of coffee) for basically no cost it becomes annoying. Firesuits are not the problem, coffee is and-. Ope it got closed

**Comment by Watermelon914** [comment]
I don't really agree but I'll re-open this when times aren't as hectic

**Comment by optimumtact** [comment]
don't reopen it, if you disagree with another maintainer take it up with the headcoders.

**Pull request closed without merging**
