### PR TITLE
Nerfs swarmers

### PR DESCRIPTION
**Pull request by swindly**
:cl: Swindly
balance: Repair self now costs 10 resources
/:cl:

[why]:  (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
swarmers are bad

### CODE REVIEW

**Comment by GhostEcho** [comment]
t. I lost plz nerf

**Comment by swindly** [comment]
plot twist: i was an observer and played as a swarmer

**Comment by Buggy123** [comment]
Man those swarmers must've had a hell'va time killing you, considering they're designed around not doing that.

**Comment by swindly** [comment]
I never want to see any complaints about swarmers.

**Comment by subject217** [comment]
really if you want to make a change that will be relatively controversial you have to put a lot more work into arguing for it. it's kind of a PITA. i'm not sure this was the right change for swarmers as repair time isn't something that actually causes trouble that much IMO (like, i never almost kill a swarmer only to have it repair just in the nick of time or something like that). some changes could probably come to them though.

**Comment by Barhandar** [comment]
Swarmers _can repair themselves_?

**Pull request closed without merging**
