### PR TITLE
Syndicate Lavaland now uses PACMANs

### PR DESCRIPTION
**Pull request by Addust**
Changes out the turbine that doesn't fucking work on a basic setup for some accursed fucking reason (and also the cause of multiple blackouts) for 3 regular PACMANs and 2 SUPERPACMANS.

Also an extra turret at the arrivals area of the base because MINING MODSUITS CAN LITERALLY ROLL OVER LAVA FOR SOME FUCKING REASON and put the base in GRAVE FUCKING DANGER because a single miner took a fancy-ass suit from the vendor.

## About The Pull Request

Throws out the syndie lavaland turbine alongside the associated plasma tank. In exchange, 2 SUPERPACMANs and 3 PACMANs are provided as alternate power generation, and the plasma tank is replaced with a fuel storage area.

image
image

## Why It's Good For The Game

The Syndicate Lavaland turbine is pretty fucky and provides about half the amount of power the two exterior RTGs do on a standard 50/50 plasma oxygen setup, and the base isn't even equipped to upgrade it to try to offset that shit. As such, we're throwing the turbine and its plasma tank out to make sure the base doesn't blackout at least during regular shifts. Due to their access to a BSRPED filled with T4 parts, I expect and am wholly supportive of dumping some manipulators and capacitors into the PACMANs to gain lots of power.

The only downside is if used on any server that has absurd shifts it will run out eventually, but the T4 upgrades and the SMES can offset that pretty damn easily.

## Changelog

:cl:
add: Syndicate Lavaland now uses PACMANs and SUPERPACMANs to provide power.
add: Syndicate Lavaland now has a new turret at the arrivals hall.
del: No more syndie lavaland turbine. That shit didn't even work half the damn time.
/:cl:

### CODE REVIEW

**Comment by weesnaw-ops** [comment]
turbine is difficult and all but pacmans/superpacmans take so little sheets and you have to refill them constantly

**Comment by moocowswag** [comment]
I thought superpacmans were removed and you cant upgrade pacmans anymore?

**Comment by san7890** [comment]
The nukies still start with a supermatter shard, right?

**Comment by Palpetinus** [comment]
> I thought superpacmans were removed and you cant upgrade pacmans anymore?

Superpacmans are - unless I'm confusing two things - simply another setting for the pacmans now (multitool the board/use it in-hand, don't remember) and just use uranium for better power output. But you are correct, they can no longer be upgraded with stock parts.

**Comment by Addust** [comment]
the SM shard is only a third of the time
also, even if unupgraded, my shitty math tells me the base can still get a whopping 180kw of power

**Comment by Addust** [comment]
tried to use the turbine how it's intended with the pressure difference science bullshit and that didn't work well either, producing at maximum 3kw. for comparison, the PACMAN setup can do 180kw and the base on average needs around 50kw

**Comment by Addust** [comment]
once again it has been confirmed that i either do not know how to use the turbine or it's dogshit
i'm going with the second option

**Comment by Addust** [comment]
> The syndies still start with a supermatter shard, right?

They only get the shard when they get a specific test chamber spawn, which is a third of the time. So yes, that third of the time, syndies will indeed get their yellow death crystal that scares the shit outta miners.

**Comment by san7890** [comment]
I'm not 100% on this because I don't see why we can't have both the turbine and the PACMANs, because I know some people use the syndicate base for testing setups they normally can't do on stations.

**Comment by Addust** [comment]
Good idea, will add it when I get the chance.

**Comment by optimumtact** [comment]
@Addust coming back to this?

**Comment by Addust** [comment]
Not coming back to this. The turbine can in fact be pushed to charge one of the SMES units with the right config. Might semi-revive this PR with 2 backup generators.

**Pull request closed without merging**
