### PR TITLE
DRAGnet lives!

### PR DESCRIPTION
**Pull request by Cheridan**
Completed version of #8402

icon sprites courtesy of nienhaus i think, it's been a while.

### CODE REVIEW

**Comment by ike709** [comment]
Is it still admin only or was it added to abductors/sec/ERT/RnD?

**Comment by AlexCrimson** [comment]
Seems pointless and takes some of the fun out of the job. Instantly teleporting prisoners to the brig? Booooring.

Also you know people are just gonna set the teleporter to the bomb testing range and murderbone with it, or just do it to troll Sec.

Overall, do not see the point of this new item.

**Comment by Cheridan** [comment]
@ike709 I'll probably put one in the armory later.

@AlexCrimson Better than getting harassed all the way by the undesirables.
Also teleporter hijinks is half the fun.

**Comment by PKPenguin321** [comment]
@AlexCrimson yeah, but it also enables antags to steal it and teleport their target to who knows where for all kinds of shenanigans
every tool sec has is potentially a tool traitors can have

**Comment by AlexCrimson** [comment]
I know. I did mention that murderboners could make use of it. I just think its taking the fun out of the chases. Like stopping a Sec officer from escorting a Rev Head to the brig, or chasing down a criminal running around with the cuffed Captain.

**Comment by pudl** [comment]
This tool is really, really op for security. Possibly as a single object for the HoS is fine but pushing it, but any other function would be too much.
If security is literally a shadow force that appears, teleports someone away to be brigged, then vanishes again, they have literally no balance. What of shitty security players? What about a traitor who disguises themselves as security?
Even if your answer is that "security can be watched by admins", this still opens up a lot of opportunities for simply stealing security gear and instantly winning.
As it is right now, it's easy to transport someone from a location to the brig if you're fast and smart about it.

**Comment by Jordie0608** [comment]
Balance concerns are better addressed when, if ever, Cheridan makes this accessible to anyone but admins; for now however, it works as far as I tested.

**Pull request merged**
