### PR TITLE
Removes Multisword from Spellbook

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Xhuis** [comment]
:+1:

**Comment by Cheridan** [comment]
fun removal?

**Comment by GunHog** [comment]
It is Wizard. The swords are fun, chaos is good. The hype will die down once something more interesting comes along, no need to remove this :-1:

**Comment by Incoming5643** [comment]
There's chaos and then there "the wizard may be dead but no one can really tell because this feels like highlander".

Congrats on making something too crazy for wizard though, that takes some skill.

**Comment by KorPhaeron** [comment]
@incoming5643

I honestly dont see the problem if a wizard wants to trade his round for pseudo highlander

**Comment by KorPhaeron** [comment]
@Cheridan

I'll re-add veil render dont worry

**Comment by WJohn** [comment]
RIP.

**Comment by Aloraydrel** [comment]
RIP meme sword

**Comment by Robustin** [comment]
I feel like there should just be a design decisions as to whether we want Wizard to be a real antag or just highlander with guns/magic/infinite respawns. A majority of wizards are just magic memesters now while its always novel at first you just want to space yourself when you get roundstart guns/magic/clones. 

There's a reason highlander rounds are rare, taking one of the highest weighted roundtypes and letting it turn into Deathmatch on a regular basis isn't good.

**Comment by KorPhaeron** [comment]
Why not both Robustin? It's up to the wizard to decide what he wants his round to play out as.

Classic wizard is more viable than ever, I've done nothing to nerf or remove it. People are just siezing on an alternative.

The round chance should probably be a bit lower, but that's not a code issue

**Comment by KorPhaeron** [comment]
And if it's really a "majority" of wizards it means random chaos and death match is popular with the majority.

**Comment by daman997** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Robustin** [comment]
Except that a single person getting a choice on whether or not to have highlander is not a referendum on the whole crew.

One wizard was selected twice in a row yesterday, same schtick, you can be sure the crew wasn't wild about the second run around. 

And the other argument is that wizard is one of the most judgmental rounds there is, its much easier to do your "basic" job as a blob/malf AI, wizard requires a lot of station knowledge, prior experience, and so many people just prefer to take the easy way out by letting the crew antagonize themselves instead of fireballing themselves 5 seconds in and dying while everyone laughs at them.

**Comment by Miauw62** [comment]
i dont see the big difference with ei nath tbh

**Comment by KorPhaeron** [comment]
@Miauw62 

At least they get to stay in the game this way. Wizard is a trash death match with no room for subtly or roleplay or doing your job anyway, multiverse just makes several teams instead of wizard vs everyone.

@Robustin 

But if it's appearing frequently, that means many "single persons" are choosing it.

Right now we have 24 Multisword spawns in the last month, out of 136 wizards (or 104 wizard rounds). So around ~1/5 of wizards take it, and wizard is currently 10% of rounds.

So you'll see multisword something like once every 50 rounds at the current rate, and I suspect that will drop as the novelty wears off. The same guy getting selected twice in a row was an incredible fluke.

**Comment by GunHog** [comment]
> wizard requires a lot of station knowledge, prior experience, and so many people just prefer to take the easy way out by letting the crew antagonize themselves instead of fireballing themselves 5 seconds in and dying while everyone laughs at them.

That is not fun for the Wizard player, who wasted one of the most desired antag rolls, nor the crew, who either just had their round end abruptly, or Mulliganed into Extended. Probably the only person to have a bit of fun is whomever got to space his corpse.

As a Wizard, you either pick spells to cause chaos for you, or you buff yourself up into a high-speed glass cannon. Wizards have few defensive spells, but strong evasion spells, and devastating offensive spells. 

What options does a wizard have for an extended brawl with the crew, where he is slinging combat spells, but NOT teleporting around or hiding in a locker to patch up the damage from two lucky laser hits?

**Comment by Cebasiz** [comment]
which is the entire problem with wizard as a gamemode, for whatever reason it's entire effective kit is  two teleports and a touch instakill, because it has no options for crowd control at all.. when it's a wizard. master of crowd control

baffling

**Comment by Cheridan** [comment]
if the creator wants it gone then rip

**Comment by Miauw62** [comment]
rip syndieborg flood

**Comment by AnonymousNow** [comment]
Sounded really fun, shame I never got the opportunity to see it in action.

Also, I swear that things which re-add people to the round - something I absolutely love from the bottom of my blue, shrivelled little heart - get screwed over on a consistent basis.

**Comment by Miauw62** [comment]
it was fun the first time but after that it was really just highlander with respawn.
could also be used with a staff of change to make five hundred syndieborgs without any effort.

**Pull request merged**
