### PR TITLE
Fixes minimaps crashing the server.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
The list wasn't getting gc'ed until the proc ended, causing a fuck ton of lists to use up memory until it went over the memory limit

### CODE REVIEW

**Comment by Razharas** [comment]
>People actually clearing lists with newlists

Damn son

**Comment by PKPenguin321** [comment]
sounds kinda high priority and probably could use the [s] tag unless im misunderstanding here

**Comment by MrStonedOne** [comment]
its only generation that can crash the server, so players can't abuse this.

**Comment by PKPenguin321** [comment]
ah, so the server doesn't work at ALL then
rip the poor bastard that merged this without testing the code

**Comment by neersighted** [comment]
@PKPenguin321 The code was tested and working, the issue only became apparent when CTF increased memory usage.

**Comment by PKPenguin321** [comment]
i never blamed you neer

**Comment by Razharas** [comment]
Well ye it compiles

**Pull request merged**
