### PR TITLE
Revert "Adds a Recipe for morphine to medicine"

### PR DESCRIPTION
**Pull request by Iamgoofball**
hi yes this is a really powerful combat chem

ignoring all damage slowdown is really powerful

it's supposed to be limited to whats available roundstart, and reishi

### CODE REVIEW

**Comment by epicmemename** [comment]
this. upvote

**Comment by Buggy123** [comment]
I swear I will pop the ball https://imgur.com/giC2TMq.jpg don't test me boy.

**Comment by yourdoom9898** [comment]
Doesn't morphine give the tradeoff of a eventual slowdown and knockout? This seems like a bit of a kneejerk reaction.

**Comment by RandomMarine** [comment]
\>really powerful combat chem
\>puts you to sleep after 20 seconds

**Comment by Iamgoofball** [comment]
You can microdose it to avoid this.

**Comment by MoreRobustThanYou** [comment]
or just chug both morphine and coffee

**Comment by XDTM** [comment]
But ephedrine and meth are ok?

**Comment by Ordonis** [comment]
I still stand by my reasoning that chloral is a far more effective combat chem that is as easy or easier to make for offensive use; for defensive, hearty punch requires no chem access, and most bartenders will jump at the opportunity/excuse to make it. I haven't seen tiders running about with morphine at all in the few rounds it's been merged.

**Comment by arsserpentarium** [comment]
Even if allow chem synthesis of morphine, recipe should be complex as fuck. Like spaceacillin, or even harder.
Upvote. Don't know,who and why merged this reciepe.

**Comment by 81Denton** [comment]
>ignoring all damage slowdown is really powerful

Legit question, what makes it stronger than the ephedrine/meth "GOTTAGOFAST/GOTTAGOREALLYFAST"?

>Morphine synthesis is complex as fuck.

I don't think that realism applies to spess chemistry when there are chems like life, corgium, strange reagent and pretty much anything involving plasma.

**Comment by DaedalusGame** [comment]
it has IGNORESLOWDOWN, which is a seperate thing that stops damage slowdown from applying to you apparently. Meth and ephedrine just make you fast. I can look this up in detail tho

This pr is still a kneejerk because medbay is full of morphine and you can probably deconstruct reconstruct nanomed plus to refill it and botany of all things can also make it.

**Comment by arsserpentarium** [comment]
Still recipe is too simple. 70 reactions is overkill. But 6-7 is better.

**Comment by Cyberboss** [comment]
Too many PRs to let stuff I know won't get merged stay open

**Comment by FantasticFwoosh** [comment]
How does that response even reply to the PR @Cyberboss outside of 'its a goof-pr lets close it'

**Comment by Cyberboss** [comment]
Because kor already decided on and approved the balance implication of adding it and it hasn't even been in one real round yet

**Comment by Iamgoofball** [comment]
kor hadnt gotten back to me about it, but you raise a fair point...

if chem tracking FUCKIN WORKED

**Pull request closed without merging**
