### PR TITLE
Sets bodypart throw force to zero

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request

Limbs do no damage while being flung at people.

## Why It's Good For The Game

This change is intended to make mechanics such as ashwalker sacrificing less annoying as you get hit with a leg to the head. I believe organs were already given a throwing force of zero for this purpose.

## Changelog
:cl:
tweak: limbs no longer do damage when thrown at people
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Ashwalkers are tearing off their own limbs to use as weapons? That's awesome and shouldn't be patched out

**Comment by MrDoomBringer** [comment]
awful change, i want to be able to KO someone by throwing their own leg at them.

Also, it's actually pretty funny sacrificing someone and actually taking damage because you got hit by their flying, dismembered head.

**Comment by itseasytosee** [comment]
Limbs do 3 damage. I'm referring to when ashes sacrifice someone and their bodies explode doing minimal but annoying damage when you sacrifice someone. The intent is not for normal throwing but for bodies exploding.

**Comment by MrDoomBringer** [comment]
Yeah but by changing the throwforce, you affect both bodies exploding and limbs being thrown, right?
>I'm referring to when ashes sacrifice someone and their bodies explode doing minimal but annoying damage when you sacrifice someone. 


I understand that ashes sacrificing someone causes the ashses to sometimes suffer minor damage from the flying limbs. I'm saying thats funny and should be kept in.

**Comment by MrDoomBringer** [comment]
Yeah but by changing the throwforce, you affect both bodies exploding and limbs being thrown, right?

I'm referring to when ashes sacrifice someone and their bodies explode doing minimal but annoying damage when you sacrifice someone.

I understand that (see my previous comment). I'm saying that interaction is funny and should be kept in.

**Comment by itseasytosee** [comment]
You make valid points. My perspective has been changed by your wisdom, thank you.

**I'm going to buff plasmafist**

**Comment by MrDoomBringer** [comment]
now this is a based dell latitude E6410 laptop battery moment

**Pull request closed without merging**
