### PR TITLE
[Delta] The DeltaStation Mega Update

### LINKED ISSUE #23787: [Delta] Bad intercom placement in supermatter SMES room
image

### PR DESCRIPTION
**Pull request by JohnTheDonut**
## **The DeltaStation Mega Update**
Adds wardrobes to Deltastation in areas including The Arrivals Shuttle and the Dorms these wardrobes vary in different colours to allow variety. This is done because in the event that someone looses their clothing or they for whatever reason would like to wear a different colour of clothing there should be adequate spares in easily accessible location on the station. 

Adds access buttons to Virology doors this is to make Virology a more secure area as it may contain deadly viruses. 

Adds a disk fridge to botany for easy storage of important disks.

Adds Three pairs of optical meson scanners to supermatter room for engineers and atoms techs this is to help stop stop people working on the supermatter from hallucinating and being irradiated.

Adds bolt door buttons to all dorms rooms/cabins this is to allow more privacy for players in these rooms to do what they would like without being interrupted and all other maps have door bolt buttons on dorms so this is also added to align with mapping standards.

Fixes a misplaced station intercom in Supermatter SMES room this Fixes #23787 

## **Images**
[Dorm Door Bolt Buttons
](http://imgur.com/a/goNfR)

[Wardrobes](http://imgur.com/a/HgCw6)

[Virology Access Buttons
](http://imgur.com/a/n1iYI)

[Meson Scanners & NW Supermatter Filter Changes
](http://imgur.com/a/HcbKA)

[Disk Fridge In Botany
](http://imgur.com/a/NHVDm)

[Cake Hat In Bar
](http://imgur.com/a/BSCGw)
## **Changelog**
:cl: Tofa01
Tweak: [Delta] Changes NW supermatter filter to filter O2 instead of N2
Add: [Delta] Adds wardrobes to Dorms & Arrivals Shuttle
Add: [Delta] Adds access buttons to virology doors for extra security
Add: [Delta] Adds bolt door button to all dorms
Add: [Delta] Adds three pairs of optical meson scanners to supermatter room
Add: [Delta] Adds a disk fridge to botany
Add: [Delta] Adds a cake hat to the bar
Fix: [Delta] Fixes misplaced station intercom in Supermatter SMES room
/:cl:

_Thanks to the [Deltastation map issues](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=9516) thread for pointing out all these issues._

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Hey do you mind being a hero and adding a disk "fridge" to botany as well 😉

**Comment by Tofa01** [comment]
@ExcessiveUseOfCobblestone Done! Also added a load more stuff.

**Comment by Tofa01** [comment]
Updated PR with images.

**Comment by jughu** [comment]
Still no cakehat

**Comment by Tofa01** [comment]
Just noticed this, all other maps have it so why not just added it in latest commit.

**Comment by Tofa01** [comment]
Added cake hat, all other maps have this included so i added it to the bar.

**Pull request merged**
