### PR TITLE
Shuffles around admin permissions because I should not be outranked by a coder on administrative things

### PR DESCRIPTION
**Pull request by silicons**
What the fuck ORANGES IS HIGHER RANKED THAN ME BECAUSE HE HAS SOUND AND I DONT

### CODE REVIEW

**Comment by kevinz000** [comment]
This ... was a serious PR.

**Comment by Bawhoppen** [comment]
NEW RECORD ON CLOSING! @Iamgoofball

**Comment by Bawhoppen** [comment]
ONLY 3 SECONDS DEAR GOD

**Comment by coiax** [comment]
So when you say "out ranked" you mean who is higher in the list of admin who?

**Comment by Shapsy** [comment]
I assume they mean in terms of who can kick/ban/whatever who

**Pull request closed without merging**
