### PR TITLE
Removes the overdose from Space Drugs.

### PR DESCRIPTION
**Pull request by Iamgoofball**
It doesn't need an overdose, because it does not have any actual positive gameplay effects. The rest of the drugs have overdose or addiction effects because they do shit like increase your speed or reduce stuns.

### CODE REVIEW

**Comment by Anonus** [comment]
It has an overdose so that the blob that gets the space drugs reagent doesn't get completely dicked over(even though it basically already does)

**Comment by Iamgoofball** [comment]
Space Drugs blob should really be axed or replaced with something else.

**Comment by Incoming5643** [comment]
It was intentionally designed to be kinda shit, it was coded before the OD mechanics for space drugs were added

**Comment by PKPenguin321** [comment]
Space Drugs blob should really be axed or replaced with something else.

\>goofball
\>wanting to revert things

**Comment by phil235** [comment]
@Iamgoofball I don't mind removing the mild damage effects and raising the overdose treshold, but I'd rather we keep the potential hallucinations effect.

**Comment by Iamgoofball** [comment]
Yeah, but people will still go "OMG SPACE DRUG OVERDOSE PURGE  expecting to die unless it's completely removed

**Comment by phil235** [comment]
We could give it a specific overdose message by using overdose_start(). Something like "You're really starting to trip hard!

**Comment by Iamgoofball** [comment]
That could work, yeah

**Comment by Anonus** [comment]
If the overdose gets removed or made non-deadly, space drugs blob needs to go.

**Pull request closed without merging**
