### PR TITLE
Reverts a self-merge speed-merge.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Unacceptable behavior. Regardless of the intentions of the PR, a speed merge should not be done under any circumstances. I would be a hypocrite to not call for a revert on this.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
what part of "speed merges are bad, don't do them" did you miss

**Comment by Iamgoofball** [comment]
no, seriously

i stand by my statement here
speed merges are bad
this could of waited 24 hours

**Comment by Iamgoofball** [comment]
the 24 hour rule and no self-merging rules are the only rule of law we have for maintaining the /tg/ repository aside from the banned content list, and it is incredibly hypocritical of us to decry ninja's speedmerge and then immediately turn around and speed merge another PR

**Comment by Cyberboss** [comment]
This is simply damage control for the original incident

**Comment by ArcaneDefence** [comment]
I'm the most drunk I've been in quite some time, and I still find physical pain in the turn of events. I really hope things settle. :(

**Comment by Whoneedspacee** [comment]
speed merging this was the best while it could have waited its more fair to return things to their original state, opening a pr for removal that is focused on removal and not this drama is for the best.

**Comment by GhostEcho** [comment]
I sympathize with Goof, but I can sympathize in the wish to kinda correct things sooner rather than later. Its happened before and will happen in the future, but we just have to make sure that if something is to be spedmerge, its done so thoughtfully

**Pull request merged**
