### PR TITLE
Limits mobs to 1 do_after per target by default

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
This generalizes the change made by #55145 to all do_after's, as started by my previous PR #50048, which added support for checking if you're already interacting with a given target before starting another do_after. I chose not to enforce 1 do_after per user per target at the time because I figured there was some kind of edge case I'd break, but it's probably better to bite the bullet now and prevent further do_after spam issues from arising. To specify, this change means that you cannot stack multiple do_after checks on the same target, but you're still able to start multiple do_after's on different targets (except where specifically checked for, like surgery)

I can add an override if any specific do_after check should allow you to stack multiple concurrent checks at the same time, and I'd like to hear if there are any that people think may need/should have exceptions, just let me know in the comments and I'll take care of them.

## Why It's Good For The Game
Prevents further issues with do_after spam

## Changelog
:cl: Ryll/Shaps
code: Users can only queue one do_after per target at a time
/:cl:

### CODE REVIEW

**Comment by Ryll-Ryll** [comment]
The following are some of the exceptions I need to take care of (first 2 courtesy of roh)
```
if(!instant && !do_mob(src, src, 1 SECONDS, timed_action_flags = (IGNORE_USER_LOC_CHANGE|IGNORE_TARGET_LOC_CHANGE|IGNORE_HELD_ITEM), extra_checks = CALLBACK(src, /mob/living/proc/rest_checks_callback)))

if(do_after(H, 5 SECONDS, timed_action_flags = (IGNORE_USER_LOC_CHANGE|IGNORE_HELD_ITEM|IGNORE_INCAPACITATED)))```

also stripping menu

**Comment by TiviPlus** [comment]
*Distant I told you so*

**Comment by Qustinnus** [comment]
Whether or not this fixes some issues, there's definitely some huge balance implications with this PR as it will nerf things like stripping extremely hard, and making snowflake exemptions for it doesn't sound like a good fix.

I'm also not a huge fan of the INTERACTING_WITH() define as it's doing a x in list for each execution.

I might open up an alternative PR to refactor some of the deeper issues with do_afters.

**Comment by SkeletalElite** [comment]
This may warrant an increased suture/mesh speed similar to how it was changed for CPR where the first attempt takes a while but the automatic subsequent attempts are much faster.

**Comment by ATH1909** [comment]
this fucks over stripping (and cuffing+stripping headset), sutures, cyborg self-welding, and probably a whole bunch of other stuff too. the bar for getting up from being prone might also cause some issues.

**Comment by ATH1909** [comment]
do ethereals still use do_after spam, or did that get cpr-ified?

**Comment by wesoda25** [comment]
> this heavily nerfs suturing people, cyborg self-welding, crafting, and probably a whole bunch of other stuff too. the bar for getting up from being prone might also cause some issues.

How does it nerf any of these things?

So long as we could exclude certain do_afters such as the aforementioned stripping, this seems like something we would want. Doing cooldown checks for every do_after is a bit ridiculous. At the very least if it was a variable for do_afters that was off by default, and we could enable for what we want (and later maybe make it on by default since most of them would use it).

**Comment by SkeletalElite** [comment]
> > this heavily nerfs suturing people, cyborg self-welding, crafting, and probably a whole bunch of other stuff too. the bar for getting up from being prone might also cause some issues.
> 
> How does it nerf any of these things?


People queue loads of do_afters with sutures/meshes to heal faster. Probably the same for cyborg self welds. I dunno what crafting needs do_after spamming though.

**Comment by wesoda25** [comment]
And those are clearly not intended. It's not a nerf, it's a fix.

**Pull request closed without merging**
