### PR TITLE
Adds 3 'Comms Buoy' Space Ruins

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
https://github.com/tgstation/common_core/blob/master/Technology%20and%20Science/Communications.md
I was playing Starsector shortly before I read through this lore blurb and realized that simple Comms Buoys would be easy little ruins to make.
Then I decided to make NT's extra-special because NT is always leading in tech innovation.

Adds 2 "low-tech" Comms Buoy ruins (**no local comms**, these are just little fluff things):
<details><summary>Kosmokomm Communications Buoy</summary>

image</details>

<details><summary>Pirated Communications Buoy</summary>

image</details>

The majority of the PR is the "high-tech" Nanotrasen Extraorbital Bluespace Communications Buoy 
<details><summary>The NT-EBCB Model 7 (ignore the parallax i couldnt get it all in one screenshot)</summary>

image
</details>

This is a medium ruin that's more lore heavy than loot heavy - though that doesn't mean there's no danger. NT wouldn't want you walking in and reading all their communication logs after all.

<details><summary>SPOILERS INSIDE</summary>

**Hazards:** 2 Laser Turrets (in a titanium room, so they reflect off walls)

**Loot:** 2 Experimental Tool spawners, 2 NT Private Security bodies, 3 space suits, 1 of each tcomm component, 2 RTGs (can these even be taken)

The majority of the sat is for lore. It has 3 paper notes and 5 consoles (1 broken, 1 dupe, so 3 unique consoles)

All lore will be here to show how formatting appears in-game.

<details><summary>Airlock Note: "Page 33: NT-EBCB Model 7"</summary>
This one gives a quick summary of what to expect inside - consoles and defense turrets. Of course, players won't have the special ID (and couldn't use it anyways, the guys inside covered it in blood)

image
</details>
<details><summary>Pinned Note: "Table of Contents: NT-EBCB Model 7"</summary>
A page out of the manual. Rest of manual not included. (Names the different parts of the buoy)

image
</details>
<details><summary>Main-Dish Note: "Spinward-NT-EBCB Inspection Report"</summary>
An inspector left behind a few notes during pre-deployment. Sure hope no important security risks were missed!

image
</details>
<details><summary>Console 1: "Satellite Dish Operations Terminal"</summary>
This one's mostly just a tie-in with the "story", don't know how necessary it is but it filled the empty spaces.
This console has a spare in the Main Dish (as its prone to breaking from the turrets)

image
</details>

<details><summary>Console 2: "Blackbox Transcription Terminal"</summary>
The "local" side of the story. This console monitors the Local-Space Comms, and managed to log the repair team's activity.

image
</details>

<details><summary>Console 3: "Long-Range Interstellar Relay Operations Terminal"</summary>
Here's the big lore thing for freaks like me who love lore being shown in-game.
It's got a lot of random-made-up-science-bullwhizz relating to the ongoing NT research mentioned in the plasma_exposure lore blurb. Granted, the guy's a bit biased in his ex-partner's work.

image
image

</details>

</details>

## Why It's Good For The Game
A) Everybody loves new space ruins, even small fluff ones. I hope.
B) Lore integration is cool. Aside from the obvious 'Comms Buoys being a thing you can find', it also makes mention of the Gateway system/Port Ellis and a certain lore blurb involving plasma (albeit under more severe, and biased, testing)
## Changelog
:cl:
add: 3 new Space Ruins: two small Comms Buoys (fluff) and an NT Bluespace Comms Buoy. Employees are asked not to touch vital components when nearby this critical infrastructure.
/:cl:

### CODE REVIEW

**Comment by OrionTheFox** [comment]
thats a lot of reviewers 😰

**Comment by bob-b-b** [comment]
Looks good, but maybe replace one of the experimental tool rolls with the gold r&d disk/anomaly core loot roll. As is pretty middling loot for a space ruin that actually has dangerous aspects.

**Comment by mc-oofert** [comment]
ok but why are the computers offset into the wall

**Comment by MoonDeer728** [comment]
do it have unbreak walls?

**Comment by Exester509** [comment]
Is that an actual blackbox? If it is, please spawn it empty or snowflaked so it doesn't break traitor objectives (like asking to destroy an already destroyed blackbox because it's somewhere on deep space and you don't know)

**Comment by TheVekter** [comment]
What do the Private Security bodies have on them? I want us to be reducing the amount of gamer loot in space, not increasing it.

**Comment by Xkallubar** [comment]
> What do the Private Security bodies have on them? I want us to be reducing the amount of gamer loot in space, not increasing it.

Pretty sure just an ID with no access, and a vest and helmet.

**Comment by rageguy505** [comment]
> Is that an actual blackbox? If it is, please spawn it empty or snowflaked so it doesn't break traitor objectives (like asking to destroy an already destroyed blackbox because it's somewhere on deep space and you don't know)

theres already a blackbox in space im pretty sure

**Comment by Singul0** [comment]
Luv me some lore

**Comment by OrionTheFox** [comment]
> Looks good, but maybe replace one of the experimental tool rolls with the gold r&d disk/anomaly core loot roll. As is pretty middling loot for a space ruin that actually has dangerous aspects.

Very good idea, will push it with whatever fixes this CI fail. I had no clue what loot to put there 😭 

> ok but why are the computers offset into the wall @mc-oofert 

I thought it looked better, but if it doesn't / it's not allowed I'll change it back to normal

> Walls/Blackbox comments

Walls are normal titanium. It's not valuable enough to do unbreakable (plus I couldnt see unbreakable corner walls)
The blackbox and most of the other decorative components are Fluff items. There IS a ruin with one that probably shouldn't be there but that's not relevant to this PR

**Review by Wallemations — APPROVED** [review]
SAT dish sprite seems fine

**Pull request merged**
