### PR TITLE
Removes 509 server support.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
its buggy, it makes the game laggy to the point of being unplayable, and there is no reason (That i know of) for coders to not use 510. the client is better, uses less bandwidth, uses less cpu, deals with lag better, the server is better, doesn't lag as much, has better performance, and so far every crash that only happened in 510 only has been fixed.

Coders, speak now or forever hold your peace. If there is a reason the 510 client breaks something when playing normally or testing, I need to know, if there is a reason the 510 IDE breaks something when coding or testing, I need to know. if there is a reason the 510 deamon breaks something when hosting test servers, I need to know.

As right now maintaining support for both is too much of a headache and there isn't much reason as even the majority of players and coders are using 510 already.
## THIS APPLIES TO SERVER ONLY

509 clients still work, but that might be changing soon as they seem to put more stress on the server then 510 clients.

### CODE REVIEW

**Comment by optimumtact** [comment]
Plus we weren't really supporting 509, no travis build to test it, no servers running it, minimal coders caring about it.

**Comment by Core0verload** [comment]
Never encountered anything 510-specific except the JSON crash, and it was fixed. 510 is currently as stable as it could be without actually being released, and even the client-side issues are mostly fixed.

If the cleanbot bug is not 510-specific, there is no reason to keep 509 supported.

**Comment by MrStonedOne** [comment]
ya, we had cleanbot in 509

**Comment by RemieRichards** [comment]
As far as I'm concerned we /shouldn't/ really been maintaining 509.
:+1: to this.

**Comment by MrStonedOne** [comment]
I mean, I wanted to give it a try, but ya. too much work.

**Comment by coiax** [comment]
#16792 got speed reverted (in #16900) by @Incoming5643 and @Cheridan on the basis that it rendered the server unable to compile in 509 (which according to @optimumtact would compile if you had bygex installed, so whatever)

**Comment by MrStonedOne** [comment]
@tgstation/commit-access

**Comment by Incoming5643** [comment]
I wasn't aware how not so stable "stable" was, so I'm alright with it, but I'm still going to dev on 509 while 510 is in beta and point out what doesn't compile on 509 because usually the fixes are trivial and there's no reason not to.

**Comment by MrStonedOne** [comment]
@Incoming5643, I don't think you understand, This pr breaks everything as it removes all the #if DM_VERSION shit and prevents compiling on 509 with a error message

**Comment by Incoming5643** [comment]
Then I'll readd it locally until I can be arsed to upgrade

**Comment by duncathan** [comment]
:+1:
it's been a pain in the ass to maintain 509

**Comment by RemieRichards** [comment]
@Incoming5643 what is your problem?

**Comment by Incoming5643** [comment]
I'm lazy

**Pull request merged**
