### PR TITLE
New pill sprites!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin, sprites made by @maxymax13 
image
image

## Why It's Good For The Game
Better shading, makes the pills look much more appealing to consume too!

## Changelog

:cl: Maxymax13
imageadd: resprites pills
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
the pillening has come

**Comment by D4C-420** [comment]
based and new pilled

**Comment by Wallemations** [comment]
the one that makes me confused is the black and white pill, why does that one have a curved middle while the others don't?

**Comment by Farquaar** [comment]
These look pretty good.

**Comment by GoldenAlpharex** [comment]
> the one that makes me confused is the black and white pill, why does that one have a curved middle while the others don't?

The white and green one also has it, but I agree it feels a bit inconsistent here.

**Comment by tralezab** [comment]
> > the one that makes me confused is the black and white pill, why does that one have a curved middle while the others don't?
> 
> The white and green one also has it, but I agree it feels a bit inconsistent here.

when you say inconsistency i see variety idk

**Comment by Mothblocks** [comment]
Pretty

**Comment by Livrah** [comment]
Nothing more appealing to consume then old floor pill. Others looks nice.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
