### PR TITLE
Adjusts the behavior of Mood on sanity

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
balance: Changes rate of sanity drain and caps it depending on mood
/:cl:
Kor gave me permission to work on mood during the freeze so I could stop the fuckload of people that ping me 5 times with insults.

If you are only slightly sad, you wont go insane, but go to a cap, to go insane you /need/ to be in a bad mood at the same time, or you will go back to sane really fast. Also sanity drain rates lowered.

Also if there's bugs/issues with mood just make an issue on the issue trackers, I dont need you pinging me at 4AM to tell me how I'm horrid at things. It'll just make me get a headache. I'm making PRs in good faith, not to annoy the playerbase. The same respect in return would be appreciated.

If mood doesn't work out after this the Headmins will turn off the config, and I'll look into either rebalancing it or repurposing it.

### CODE REVIEW

**Comment by Qustinnus** [comment]
footage of KevinZ pinging me at 4AM https://youtu.be/uBZy34iwVjw

**Comment by Wilchenx** [comment]
@Qustinnus make it so the "area beauty" moodlet is from things that can be seen on your screen not the entire area.

**Comment by chesse20** [comment]
does this fix the reality dissociation disorder being unplayable due to quick insanity gain

**Comment by Qustinnus** [comment]
what does that disorder do @chesse20 

@Wilchenx this is a compromise between gameplay and optimization, I'll ask if I can make something that scans the area every 5-10 seconds and use that instead of using the entire area. :)

**Comment by iskyp** [comment]
reality dissociative disorder is a -2 trait that makes you have hallucinations unless you're on mindbreaker toxin

**Comment by Qustinnus** [comment]
that's a seperate type of insanity, unrelated to my system AFAIK.

**Comment by Doppeltongue** [comment]
Is area beauty an integer or a flag? It might make more sense to have area beauty be more on the side of area attributes. Chefs/medical doctors/roboticists/security could be resilient to blood, botanists/plantpeople resistant to dirt/tomatoes, etc. That way, people don't run into too many issues doing their job normally.

**Pull request merged**
