### PR TITLE
Adds brand new ruins to the Icebox Ruins roster.

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

Icebox is novel for many reasons, and the fact that it brings a completely unique mining-z to the equation is on of the more significant ones. A while ago, Inept @EOBGames asked me if I could work on some Icebox ruins, and this is essentially phase-1 of that request. 

## Why It's Good For The Game

Icebox's ruin roster is a sad thing to look at. We have 3 z's of fun for the ruin generation code, but not nearly enough ruins in the folder for that code to work with. Instead of being an interesting minefield of dangerous (and exciting) fun, it's a sad barren place that you get boring rocks from. 3 new ruins, and many more over the course of several additions, should revive the icewastes into a less desolate place. 

**Introducing the Homestead:** 

Icebox Happy Cabin P1

**The Comms Outpost:**

icebox_comms_ruin

and the crowning jewel of this round of ruins,
**The Plasma Facility:**

Plasmafire Ruin Mk3

These haven't been enabled yet (pending review), however once I have maptainer approval, I'll add them in. 
Please look forward to it!

## Changelog
:cl:
expansion: Adds the Homestead, Comms Outpost, and Plasma Facility to the Icewastes Ruins Roster. 
code: Adds area support for the Plasma Facility ruin.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
aw, the comms outpost's garage doesn't have any ATVs in it. sad!

**Comment by ATH1909** [comment]
can we get a better view of the southern part of the plasma facility that's cut off in your image of it?

**Comment by Zytolg** [comment]
> can we get a better view of the southern part of the plasma facility that's cut off in your image of it?

You can always view the mapdiffs under the checks tab of a map PR. I recommend you view these for the latest updates to a given map (it's fully rendered too). I'll put what the mapdiff shows in this reply so you can get a better idea of what I mean. My initial PR Images are meant to give an approximation of the content being added/changed, but are never a final representation of what will be seen in game (doubly so if I need to make requested changes via maptainer request).
image


On another note, I'll need to update this on the 'morrow with some code changes to support a new area for the Plasma Facility to use. It's failing a check because I took a lazy approach and used a var-edited area instead of doing the smart thing.

**Comment by Maurukas** [comment]
@MrStonedOne I have been directed to ping you for the config update in iceruinblacklist.txt, but that this also shouldn't matter in normal operation, since they're commented out.

**Pull request merged**
