### PR TITLE
Fixes tgui dependencies

### PR DESCRIPTION
**Pull request by AnturK**
Use npm update to update current deps.

### CODE REVIEW

**Comment by Cyberboss** [comment]
What prompted this?

**Comment by Robustin** [comment]
Me and Leo not being able to get the compiler to work, god bless @AnturK

**Comment by Shadowlight213** [comment]
Didn't everything break last time tgui dependencies were updated?

**Comment by lzimann** [comment]
@Shadowlight213 What was updated last time was the ractive. This time is something else(the dependencies that will handle minify).

**Comment by lzimann** [comment]
Also, I had to delete all my node_modules and install them again, but after that the minify is working again.

**Pull request merged**
