### PR TITLE
[READY]Check Antagonist player count

### PR DESCRIPTION
**Pull request by silicons**
Way easier than counting who.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
oh boy, verb bloat.

seriously how lazy can you be

**Comment by PKPenguin321** [comment]
I actually like this

**Comment by kevinz000** [comment]
@Dorsisdwarf I'm lazy and code is the manifestation of my laziness.

**Comment by Dorsisdwarf** [comment]
👍

**Comment by SweaterKittens** [comment]
Can't you literally just use Check Antagonists and count the number of people?

**Comment by kevinz000** [comment]
that takes time and effort.

**Comment by kevinz000** [comment]
sorry kittens. :(

**Comment by SweaterKittens** [comment]
There are already way too many niche or borderline useless admin buttons, adding more because you're lazy is silly.

**Comment by PKPenguin321** [comment]
I actually have to count the dead players in the Who verb all the time and on high pop it can be a pain in the ass especially with the text box always auto scrolling, this is far from useless

**Comment by SweaterKittens** [comment]
So wait, does this let you check the player count for EVERYTHING? Including living players, dead players, antagonist players, etc? I was under the impression that it just told you the number of antagonists, which seemed asinine to me.

**Comment by kevinz000** [comment]
@SweaterKittens currently it gives the following:
Total number of living mobs with a ckey attached (basically living players including DC'd)
Total number of dead mobs with a ckey attached (basically dead players as I believe ckey is unique)
Total number of living CONNECTED mobs (basically living players still connected)
Totaly number of living antags.

**Comment by kevinz000** [comment]
I'm putting some more detailed info and moving it to its own info window, as this will increase the check-antagonists panel's size by a large amount which may not be needed in all cases.

**Comment by SweaterKittens** [comment]
Oh, see I thought this would only count the number of antags, because I misunderstood the title of this PR. Yeah this seems reasonable and cuts out a lot of tedious reading, especially during chat scroll.

**Pull request merged**
