### PR TITLE
Prepends object names with 'The' in speech

### PR DESCRIPTION
**Pull request by QualityVan**
Touches saycode, where be dragons

Looks like
[Medical] The cryo cell beeps

### CODE REVIEW

**Comment by coiax** [comment]
plz change it to "the"

**Comment by optimumtact** [comment]
leave it The ignore coiax

**Comment by coiax** [comment]
Ignore the fruit, he closes PRs when he feels attacked, but never mind, it was to wind people up.

**Comment by coiax** [comment]
Oh look, a speed merged PR. I wonder if the fruit will face any sanction? Doubt.

**Comment by Cyberboss** [comment]
This needs to STOP

**Pull request merged**
