### PR TITLE
Low memory mode

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Adds define to run the world in a reduced memory usage mode by skipping the creating of the space zlevels loading only centcom and runtime station. Mainly for lummox.

I'm allowing edits from maintainers, feel free to amend this with other memory hogs that can be disabled, I've got it down to 272mb.

### CODE REVIEW

**Comment by optimumtact** [comment]
what if we just run like this all the time

**Comment by lzimann** [comment]
don't forget to add it to [_compile_options.dm](https://github.com/tgstation/tgstation/blob/master/code/_compile_options.dm)

**Comment by MrStonedOne** [comment]
`_compile_options.dm` happens after map files are loaded

**Comment by lzimann** [comment]
oh well, doesnt matter that much I guess

**Comment by coiax** [comment]
Could always just make a Centcom-lite, if you really want to cut down on the memory size.

**Review by Cyberboss — APPROVED** [review]

**Comment by MrStonedOne** [comment]
I think we hit a point where memory savings is going to come from culling down global lists, not map removals.

**Comment by lzimann** [comment]
I'm sure there are plenty of global lists that could be put in subsystems and prevent what is not essential from existing.

**Comment by MrStonedOne** [comment]
if @cyberboss would make that framework to get the current memory usage from tgs3 I could profile the memory cost of everything very easily and we could do more work culling shit down

**Pull request merged**
