### PR TITLE
[WIP] Equipment Upgrade Kits!

### PR DESCRIPTION
**Pull request by GunHog**
Adds the Anti-Acid EUK (Equipment Upgrade Kit)
- Coats an item in gold to make it unacidable.
- Fixes acid_act() so it respects the unacidable var on items not being
  worn.

Forum thread here: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=3159

The Anti-Acid EUK can coat the following item types:
- Suits, including armor and hardsuits.
- Head items.
- Guns!
- Mining tools ~~(Golden Plasma Cutters for hunting that blob, anyone?)~~ ((Plasma cutters are now useless against blobs))
- Gloves
- Shoes
- Shields

This is a Work In Progress. It may need a _lot_ of work. Current code and method of apply the icon changes may be inefficient.
- [ ] Optimize the usage of icon code to be better and faster.
- [ ] Acquire a sprite for the EUK item and depleted EUK item. <b>Will the person who gave me this please send it again?</b>
- [ ] Get a unique sound effect for using the EUK. (maybe something with a hiss).
- [ ] Find a way to apply the color change to the on-mob sprites.
- [ ] Fix the bug with animated items having broken timings.
- [ ] Include a changelog to appease Lord Jordie.

<b> The Golden Armory! {New Gif to come when I can make it properly!}</b>

### CODE REVIEW

**Comment by Chocobro** [comment]
I realized way too late that this is basically call of duty skins
:+1:

**Comment by WJohn** [comment]
This is pretty cool, although I think the color should be slightly more red to make it more gold colored, as these I feel are just yellow.

**Comment by Lumipharon** [comment]
Blinging shit out is hilariously neat, acid protection or not.

**Comment by GunHog** [comment]
>This is pretty cool, although I think the color should be slightly more red to make it more gold colored, as these I feel are just yellow.
Also super uncool it doesn't change how your equipment and inhands look when worn.

Tell me how, and I will do it! Give me the Hexcolor you feel is optimal. I am no artist, as you can clearly see from my EUK codersprite.

**Comment by killerfgs** [comment]
Shit i don't care about no acid protection, i just want to look pimp as hell with golden weapons.

**Comment by Boredone** [comment]
This looks nice, and its a decent touch in my opinion that it requires some Fluro Acid.
But, it looks like the golden coloring ALSO colors the energy markers for atleast some of the guns.
Maybe it shouldn't?

**Comment by Jordie0608** [comment]
I like the modularity. Will there be a way to recharge the uses or are the devices disposable?

**Comment by WJohn** [comment]
Also I'm really not entirely sure about having an actual kit to upgrade your equipment with, I kinda like the idea of simply using gold bars on your items to upgrade them.

**Comment by GunHog** [comment]
> This looks nice, and its a decent touch in my opinion that it requires some Fluro Acid.
But, it looks like the golden coloring ALSO colors the energy markers for atleast some of the guns.
Maybe it shouldn't?

I am no expert on this stuff, I am afraid. I created a blender item just so I could figure out the correct order in which to Blend() the shine and color to get the guns to look the way they are. It would be extremely difficult to avoid coloring certain parts of an item.

>I like the modularity. Will there be a way to recharge the uses or are the devices disposable?

I have not decided on what to do for the exhausted devices. For now, they are disposable, some could possibly be refilled by adding more base ingredients such as more gold and acid. I am hoping a spriter reading this will make me a better set of EUK sprites - one empty and full...or an overlay for that.

>Also I'm really not entirely sure about having an actual kit to upgrade your equipment with, I kinda like the idea of simply using gold bars on your items to upgrade them.

It is to help facilitate inter-departmental interaction between Science and the rest of the station. Sec would be more encouraged to drop by Science to protect their guns, and miners to pimp their tools. Also, I would not want to cause a situation where the HoS is stealing all the gold to bling out the armory!

**Comment by Cheridan** [comment]
That bling is amazing.

**Comment by WJohn** [comment]
It still needs to be made more golden rather than literally pure yellow. Try #FFD700 ?

**Comment by GunHog** [comment]
@WJohn I will try that along with the newer overlay I got from some guy whose name I do not remember.

**Comment by GunHog** [comment]
Conflicts resolved. I still need that bloody sprite, and I cannot find any non-snowflake way to update on-mob sprites. I could really use some help from someone who works with icons often.

**Comment by RemieRichards** [comment]
>someone who works with icons often.

So no one, since ```/image``` are superior in 90% of situations so nobody cares to go in depth with shitty ```/icon```s

**Comment by GunHog** [comment]
I am just going to close this now, the very reason I opened this PR was for fighting acid blobs / chemists who use acid as a weapon. Both these have been nerfed, and the weapon intended to fight blobs (plasma cutters) are now useless as a weapon against them.

As such, this project will have no meaningful impact, and has become more about the icons themselves more than the effect. I essentially made a "Pimp your gun" PR. I am not a spriter, nor do I have any artistic abilities whatsoever. So, unless the players *really* want this and someone is willing to help me find a better way to get this working, this project shall be scrapped.

**Pull request closed without merging**
