### PR TITLE
Fixes some pathtypes for away missions + TGM conversion

### PR DESCRIPTION
**Pull request by MMMiracles**
I mean we literally have no use for them anymore but maybe a downstream has some use for them or something.

The ones I didn't put in the PR aren't compiling because they're still the old turfs, I'll fix them later or something maybe I don't know.

### CODE REVIEW

**Comment by tedward1337** [comment]
>537k changes
WHOO WEE

**Comment by optimumtact** [comment]
Please finish or close

**Comment by MMMiracles** [comment]
all builds passed but still conflicting

i dont know honestly

**Comment by optimumtact** [comment]
You don't know what? It's conflicting, you need to merge the latest upstream master to unconflict it.

**Pull request merged**
