### PR TITLE
Makes the rocket launcher epic ( Giant RPG Buff )

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

image
image

The sprites of rocket launchers, rockets, and their projectiles have been updated.

The name of the rocket launcher has been changed from "PML-9" to "Dardo-RE Rocket Launcher".

Rocket launchers can be worn in suit slots as well as on your back if you really wanted.

## Why It's Good For The Game

image

The PML sprite is nearly like seven years old at this point I think. This is something a little less ancient and a little more cool looking.

Speaking of cool. Weapon names that are just a bunch of random letters and numbers together suck, especially with TTS around making some of these abbreviated names pronounce really weird. The new one should roll off the ai generated tongue a little easier if someone mentions it by name.
## Changelog
:cl:
add: The PML-9's name has been changed to something that's a little less boring random numbers and letters, and something that TTS can likely pronounce much nicer than before. Get blown up by a Dardo rocket launcher today.
image: Sprites for rocket launchers, rockets, and rocket projectiles have been changed to something fresher looking.
balance: Rocket launchers can be worn on your back or armor vest.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
actually there's a random rocket type that doesn't have a unique sprite i should fix that

**Comment by Vect0r2** [comment]
I like the 'NT this way' more, but other than that I like it.

**Comment by DaCoolBoss** [comment]
Most of this is good but I don't like the weird stick in front of the HE rocket. Looks awkward. Don't like the new name either, 'dardo' just sounds a bit dumb and I don't think TTS errors are a good reason to change it.

**Comment by ZephyrTFA** [comment]
> Most of this is good but I don't like the weird stick in front of the HE rocket. Looks awkward. Don't like the new name either, 'dardo' just sounds a bit dumb and I don't think TTS errors are a good reason to change it.

it's not a wierd stick, it's a puncture spike; which means that it's not HE, it's HEAT (High Explosive Anti-Tank)

**Comment by necromanceranne** [comment]
Don't forget to change the uplink entries.

**Review by Wallemations — APPROVED** [review]

**Comment by Paxilmaniac** [comment]
> Don't forget to change the uplink entries.

Good catch

**Comment by Exester509** [comment]
> Most of this is good but I don't like the weird stick in front of the HE rocket. Looks awkward. Don't like the new name either, 'dardo' just sounds a bit dumb and I don't think TTS errors are a good reason to change it.

Yeah, "Dardo" is pretty silly for a rocket launcher. And as someone else said, the "NT this way" should be kept in the sprite in some way

**Comment by junkgle01** [comment]
sprite's nice, but I have to agree dardo sounds weird

**Comment by Paxilmaniac** [comment]
Dardo is Portuguese for javelin, RE is for REusable, if I think of a better name at some point I'll maybe change it but I'm not changing it from what I already have because people are going to be immature with something's name.

**Comment by Singul0** [comment]
looks far more boxy and cartoony rather than sleek and _tacticool_ of the old sprite

**Comment by junkgle01** [comment]
> Dardo is Portuguese for javelin, RE is for REusable, if I think of a better name at some point I'll maybe change it but I'm not changing it from what I already have because people are going to be immature with something's name.

i would just take it into consideration

**Comment by san7890** [comment]
undraft when you've addressed the "good catch"

**Pull request merged**
