### PR TITLE
Winter coats: A brand new coat of paint

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

Resprites/facelifts the winter coats. Did you know alot of them had transparent pixels in the middle of them?

Coats

## Why It's Good For The Game

New bunch of sprites for old sprites that haven't seen much attention.
## Changelog
:cl:
imageadd: Winter coats have been resprited.
/:cl:

### CODE REVIEW

**Comment by SethLafuente** [comment]
how do they look with the hoods on

**Comment by Ebin-Halcyon** [comment]
> how do they look with the hoods on

I'll boot up a test server for that sometime in the near future. Laziness got the better of me.

**Comment by VladinXXV** [comment]
I maintain that I would really like to see the HOP winter coat use the same colors as the HOP resprite done by Viro- the current colors used on the winter coat and cloak feel very out of place.

**Comment by Ebin-Halcyon** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

Shush bot, i've been in a slump.

**Pull request merged**
