### PR TITLE
Supermatter Generator Room

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR see's the addition of a optional Supermatter Generator room to Boxstation.

The Generator room works fully, and can hold the SM Shard in operation.

---

Not much to say, maintenance near the SM Gen had to be moved around, also the SMES cells are back inside engineering proper to make way for the SM Gen.

The generator room is designed to attempt to minimise any damage caused by a malfunction, and a control room allows the ejection of the SM Shard should it overheat.

DM image of the Generator room.
screenshot 2015-01-29 21 11 01

For the moment, a SM Shard is placed inside Secure Engi Storage.

### CODE REVIEW

**Comment by callanrocks** [comment]
"The generator room is designed to attempt to minimise any damage caused by a malfunction, and a control room allows the ejection of the SM Shard should it overheat."

I demand that you adjust this so that the engine is as dangerous as possible without making it completely unusable.
Also the whole room looks way bigger than it needs to be and the wiring on the SMES is a bit iffy.

**Comment by Deantwo** [comment]
I liked the little SMES room.
Meant that when someone *accidentally* forgets to close the plasma canister and starts a fire, the station doesn't loss all power.

**Comment by Steelpoint** [comment]
Some of those suggestions mess with the symmetry of the design, as well as that I have to extend out the SM Generator in order for it to fit on the station, as such liberties had to be taken.

I'm not finished with the design though, and either way thanks for the feedback thus far.

**Comment by Deantwo** [comment]
I'd rather have less space wasted than have it symmetric.
I'd much rather see https://github.com/Spoffy/LLA-Station-13/pull/193, that my friend made.

Having multiple huge engines just seems like a wast of space on the station.

**Comment by Chocobro** [comment]
i'm not a fan of having a perfectly ready sm engine room all good to go. whenever an engineer makes an sm engine, they are usually VERY creative. this pr will take the potential for that away. "why make an engine room when there's one already built???" is what will be asked.
it's also a poor design, reiterating callan's picture.
overall :-1: from me

**Comment by Miauw62** [comment]
either replace the singulo or don't add an SM room at all :-1:

it's also pretty ugly and empty.

**Comment by Steelpoint** [comment]
Jesus christ, everyone wants a SM Generator before, now no one wants it.

Forget it then.

**Comment by Dorsisdwarf** [comment]
Can I suggest doing it in a Cool And Unusual way? 
If so, work on making the engine room randomly select either Supermatter or Singularity at the start of a round, and set up the room appropriately. I'm fairly sure some other server does that, it looks neat-o

**Comment by Deantwo** [comment]
That is what https://github.com/Spoffy/LLA-Station-13/pull/193 is.

**Pull request closed without merging**
