### PR TITLE
Add watertank, shower, sink to mining station and gulag

### PR DESCRIPTION
**Pull request by octareenroon91**
:cl: 
add: Showers and sinks added to gulag and mining station for hygiene and fire safety.
add: Watertanks added to mining station for convenient fire extinguisher refill.
/:cl:

Lavaland is one big fire hazard.
Wildlife slaughter can get messy.
Maybe gardening.

I'm open to concerns about adding a slip hazard to the gulag.

**Sink and shower in Gulag common area**
screenshot_2017-04-16_21-33-23

**Shower in Mining airlock, watertank at entrance to EVA**
screenshot_2017-04-16_21-33-08

**Watertank in mining storage, sink in dining area**
screenshot_2017-04-16_21-32-45

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Finally when I accidentally set myself on fire as a gulag prisoner I'm not totally screwed.

**Comment by swindly** [comment]
ez alcatraz escapes

**Comment by octareenroon91** [comment]
I had a feeling on gulag extinguishers, but couldn't quite place it.

**Comment by swindly** [comment]
ice cup from vending machine + sink = gulag extinguisher

**Comment by KorPhaeron** [comment]
You can't add extinguishers to the gulag or people will just walk out

**Comment by FantasticFwoosh** [comment]
Add paper cups to the vendor instead so people can have a drink of water.

> Gardening, water taps = Space Australia Gulag for perma gulag residents.

**Comment by octareenroon91** [comment]
@KorPhaeron I'll take out the fire extinguishers today.

Thoughts on a water cooler?

**Comment by FantasticFwoosh** [comment]
That would be a upgrade, pity it would be limited.

**Comment by octareenroon91** [comment]
Sink too

**Comment by KorPhaeron** [comment]
If the prisoners get any water at all they will walk straight to the mining camp

**Comment by octareenroon91** [comment]
I will reflect on balance and update sometime this week.

**Comment by jughu** [comment]
@korphaeron implying you cant easily escape on delta because the mining shuttle has emergency toolbox and all access doots so you run trough the lava with a medkit grab extinguisher extinguish yourself use med supplies and escape

**Comment by Iamgoofball** [comment]
idgi, are you implying you can tank the lava with water?

just make it so you melt into the lava

**Comment by octareenroon91** [comment]
Instakill memes are unpopular though.

I think escape is supposed to be very minimally feasible but I didn't make lavaland.

**Comment by optimumtact** [comment]
freeze

**Comment by octareenroon91** [comment]
@KorPhaeron I've removed the extinguishers from gulag.

Awaiting requests for any more tweaks.

**Pull request merged**
