### PR TITLE
Boxstation Brig Mapping Additions

### PR DESCRIPTION
**Pull request by Steelpoint**
:cl: 
add: Boxstation now has a Crew Monitoring Console in the Warden's Office. The Head of Security'ss Office also has a Medical Laptop
add: Security Hardsuit Storage now holds a Oxygen Tank.
/:cl:

After playing on several other maps consistently I've noticed that all other stations brigs have some additions that Boxstation lacks, considering the popularity of other maps (or regularity) being on rotation I'm now proposing the following additions for Boxstation.

* Warden's Office now has a crew monitoring console
* HoS's Office now spawns with a Medical Laptop
* The Suit Storage Units holding the Standard Security Hardsuits now hold a large Oxygen tank.

changes

Thank you for reading.

### CODE REVIEW

**Comment by Haevacht** [comment]
Its a suit sensors episode!

**Comment by Iamgoofball** [comment]
Steel point security PR here we go

**Comment by SweaterKittens** [comment]
Please, for the love of god, do NOT put a suit sensors monitor in the Warden's office. Suit sensors are for the medical team to use to find bodies and track emergencies. If you want to track criminals with them, bug medical, or go have a medic do it. People already hardly use suit sensors, making them a security lowjack is just going to make it so people purposely turn them off instead of ever bothering to turn them on.

Aside from that, these changes all seem okay.

**Comment by Steelpoint** [comment]
Either its all ok, or none of it is.

I could either place the SSM in the Warden's office on box, or remove all SSMs on all other maps that are in the Warden's (and even on some maps the HoS's!) office.

**Comment by SweaterKittens** [comment]
None of them should have a suit sensor monitor. I wasn't even aware that other maps did, that's fucking atrocious.

**Comment by XDTM** [comment]
Suit sensors are to track the officers that get inevitably assassinated. Would probably be better to make a sec-only subtype, but that's more complicated.

**Comment by jughu** [comment]
Maybe they shouldnt go alone into maints and get horribly robusted because they held their taser out and slipped over a wet tiles then get tased and robusted then you whine in deadchat then this happens

**Comment by SweaterKittens** [comment]
Suit sensors have always been for medical purposes. Again, if you want to track your officers, coordinate with medical for a handheld, or ask them to track a downed officer themselves. Putting a medical crew monitoring console in the brig is a bullshit "Quality of Life" change that makes it so you have everything you need at roundstart and you don't ever have to interact with another player. Like, fuck, if you really want a console that bad, go to tech storage and get the board and build one yourself.

**Comment by Steelpoint** [comment]
Its a 'crew' monitoring console, not a 'medical' monitoring console.

I fail to see how the presence of a crew monitoring console in the Warden's office will result in all security personal never interacting with any other player on the entire station. Even arresting someone is a interaction and security talk to people all the time about mundane things, hell I get into PDA convos oft times with people.

The strength of the crew monitoring console is it makes it more viable for the HoS/Warden to quickly check on exactly who is a member of security at that moment in time, and that a proactive HoS can keep tabs on his Officers and, if he's good enough, be aware when one silently falls silent.

The HoS can already do this via the bridge crew monitoring console, so I fail to see the doom and gloom of sec access to a crew monitoring console.

**Comment by SweaterKittens** [comment]
The "doom and gloom" is that it was always a part of the medical department, for medical purposes. It matches all of the other medical consoles, because it was designed for that purpose. It's a "crew" monitoring console but at that point you're splitting hairs. It was clearly intended for use by medics, not by security.

 The fact that there is one on the bridge only strengthens my argument. There are plenty of ways for the security team to use the sensor system if they really want to, they don't need one in the brig itself so the warden never has to leave his chair to validhunt. It's already nigh-impossible to get people to turn their sensors on, if crew monitoring has become a security implement no one will ever use them. I'm tired of these "Quality of Life" changes that take something that's already accessible and makes it so have to do even less make use of it. If you want to abuse the medical suit sensor system as a security officer it shouldn't literally be handed to you at roundstart when there are plenty of ways you can go about getting it through IC methods.

**Comment by Steelpoint** [comment]
You say the Warden never having to leave his office is a bad thing, his entire job is to sit there. Also you seem to be mistaking 'validhunting' for 'doing security's job'. But I digress.

I have played and observed rounds on all the other stations that offer the crew monitoring console to security in the brig, even the ones where they add a second one into the Head of Security's office as well. Yet I fail to see the degradation and ruin of security into a powerhouse of shit. 

If someone wants to code a alternative version of the crew monitoring console that only monitors members of security, which raises its own set of questions, then that's fine. 

But I disagree with the assertion being put forward that the crew monitoring console is a medical only system. Ever since I've been playing this game from 2011 the crew monitoring console, or whatever its name was back then, has always been used by command, security, medical and basically anyone trying to find someone.

**Comment by calzilla1** [comment]
Add a resprited portable one to the warden's locker

**Comment by SweaterKittens** [comment]
If you think I'm implying that adding a crew monitoring console to the brig is going to mean the end of days, you're mistaken. I'm not so short-sighted that I think that this change will fuck everything up forever. But it's a step in the wrong direction. It's just another QoL change that eliminates player interaction and gives people everything they need at an arm's reach at roundstart. Why are we making it easier for sec to use this when they already have the means to get a handheld or a console? 

Yes, all of the departments have used the monitoring console when they were trying to find someone. But they had to come to medical to do it. They had to coordinate with other players and actually go out of their way to take advantage of a system that was set up in the medical bay. Why is there this trend of cutting out all inter-departmental interactions? "Let's put a chemmaster in Botany, so they don't have to go to chemistry" etc.

**Comment by Steelpoint** [comment]
The fact of the matter is I belive that the function of the CMC is very vital and useful for security to have access too. You disagree to a extent and believe that security should be relying on medical to have access to the crew monitor, or at least force the HoS to sit in the bridge to read the CMC.

We can at least agree to disagree, and see what others have to say, lest we argue on till the end of days.

**Comment by GunHog** [comment]
He is just trying to make the Box map consistent with the other ones. I do not think this is going to have changes anywhere as drastic as stated in the comments. It seems to me that this is more about Steelpoint and his reputation rather than the merit of the PR itself. This looks to me like a small change to update the final map, little more than that.

I feel it wrong to treat someone like this because of his PR history. Sometimes it is deserved, but not in this case; I doubt anyone will even notice the difference here, as all the other maps already have this change. You might want to consider making an alt or having someone else make your PRs for you, Steelpoint, as you will not have fair judgement posting as yourself.

**Comment by SweaterKittens** [comment]
I would just like to clarify that my opinion has **absolutely zero** to do with the creator of the PR and everything to do with the series of "QoL" changes that have been made to eliminate inter-department coordination and interaction, as well as increasing the likelihood that no one will use their suit sensors ever. I was not even aware that the other maps had crew monitors in the brig.

**Comment by Haevacht** [comment]
Sec having access to suit sensors means more non-sec will just disable them roundstart making medical's life harder.

Remove it from all maps steeploint.

**Comment by Steelpoint** [comment]
Why would non-antags disable their suit sensors to prevent security from knowing where they are?

**Comment by Metacide** [comment]
I think the monitor is an obvious QoL improvement, and it's common sense for the warden to have it. I give the warden a monitor whenever I play security on Box - it gives the warden a much better sense of how things are going on-station, and between that and the camera monitor allows for much better coordination between security players, as well as the crew in general. That's why I added it to Meta way back when, and I've only really heard positive feedback about it.

Traitors and people who want to avoid sec can easily turn their sensors down or off, and people who want sec to look after them by monitoring already have to contend with traitors getting pocket-monitors and tracking them effectively so they can murder them. This doesn't really upset the meta much, and it's pretty nice to have.

**Comment by GunHog** [comment]
> Sec having access to suit sensors means more non-sec will just disable them roundstart making medical's life harder.

That sounds like a risk-based thing to me. People who want to be rescued or protected will keep their suit sensors on, people who are antagonist or otherwise do not want to be found will disable them (thus reducing the chance of discovery by both medical and security), and the rest (usually majority) will not touch their suit sensor setting at all.

**Comment by DamianX** [comment]
tracking
implants

**Comment by GunHog** [comment]
> tracking
implants

Invalid unless either Sec starts with them as well, or mindshields gain the same properties. Sec players that do not already put in the effort to implant them now will not ever do so in the future to a sufficient degree. If it is not done for them, then it will not be done at all.

**Comment by Steelpoint** [comment]
In addition the tracking implants lack the more advanced and sleek features of the console, its cumbersome and is meant primarily to track suspected prisoners or people, such as suspected changelings.

In addition security have a extremely limited supply of the implants, there is not even enough to half of the security force let alone having enough to implant into prisoners or suspects.

**Comment by Niknakflak** [comment]
A second sec buff PR.  Take pictures and downvote everyone

**Comment by Steelpoint** [comment]
Closing this for now to avoid merge conflicts with my other PR. Will revist later on.

**Comment by Haevacht** [comment]
Nonantags would disable them because sec can be shitlords, or to gimmick, or just because they hate sec fnr.

**Comment by Steelpoint** [comment]
Going to see if this can get back on track now.

**Comment by Steelpoint** [comment]
Ok, any merge conflict concerns have been resolved.

**Comment by Metacide** [comment]
Is the laptop density=0 so the HoS can reach corner stuff?

**Comment by Steelpoint** [comment]
Good point, I'll fix the issue.

**Comment by Steelpoint** [comment]
All good now.

**Comment by Metacide** [comment]
Looks swell 👍

**Comment by optimumtact** [comment]
@tgstation/commit-access if nobody else decides what to do with this in two days I'm going to close it because personally I don't think it's necessary

**Comment by Steelpoint** [comment]
Was this closed due to the addition of the Crew Monitoring Console or was it closed due to all the changes proposed?

If the CMC is the point of contention I can just drop it and work off of the other changes this PR makes. Otherwise I'll have to make another PR which takes up time.

**Pull request closed without merging**
