### PR TITLE
Admin dynamic rule management

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

image
This PR adds a very ugly menu which allows admins to force dynamic rulesets to be enabled or disabled.
Some admins asked if someone could add this and it seems reasonably useful.

image

The information you have available becomes slightly more detailed once the game is actually running, because then we know how many players and how much threat there is.

image

I don't know why the weight of every midround is 0 when I run locally. It's fine.
Unfortunately, the interface I have crafted is hideous. This is because it's not part of tgui and I am not very good at working with byond UIs without my beautiful typescript. It functions though. 
If anyone has any pointers I'll take 'em.

"Force disabling" a ruleset simply ensures it will never run.
"Force enabling" a ruleset disregards minimum population and minimum threat rules, but doesn't ensure that the ruleset will run. It might still be skipped due to low weight, insufficient threat to _buy_ it, or other disqualifying factors.

## Why It's Good For The Game

It was an admin request so presumably they have some plans for it.
It's a less-intrusive way of theming a round than disabling dynamic and running all the midround rules yourself.
If they want to temporarily set the game to traitorling I guess they can do that. Or only heretic/cult.

## Changelog

:cl:
admin: Admins can turn off dynamic rulesets (or force them on despite not meeting the qualification criteria) on a per-round basis.
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
A force-disable-all button would probably be nice.

The status of each could be more detailed ("Enabled", "Inactive", "Disabled-Config", "Enabled-Forced", "Disabled-Forced"), but that's probably a bit more complex for getting statuses.

Consistent indentation for the clickable links is nice. Perhaps a table could be used?

**Comment by Jacquerel** [comment]
> A force-disable-all button would probably be nice.
> 
> The status of each could be more detailed ("Enabled", "Inactive", "Disabled-Config", "Enabled-Forced", "Disabled-Forced"), but that's probably a bit more complex for getting statuses.
> 
> Consistent indentation for the clickable links is nice. Perhaps a table could be used?

Getting whether the gamemode can _actually_ run is complicated in that it's impossible before the round has started, but I can see about making it more detailed for midrounds.

**Comment by zxaber** [comment]
More than anything, it'd be helpful to know when a specific antag is impossible due to lowpop. I suppose it could just be "Inactive-Lowpop" to specify that it's not going to tell you Revs wants a few command staff. Other spawn rules are complex enough that you'd be chasing edge cases for days.

**Comment by Rex9001** [comment]
This is awesome, can't wait to try cooking up some stuff with it

**Comment by Pumpkinoe** [comment]
good shit

**Comment by san7890** [comment]
i think this is one of those admin menus that could very well be tgui since it's not critical enough for server operation but i'll err on the side of caution and let you enjoy your html sovl

**Pull request merged**
