### PR TITLE
Reverts a speedmerge of a revert of a self-merge speed-merge.

### PR DESCRIPTION
**Pull request by Iamgoofball**
I stand by my original statement that speed merges are not cool.

This PR should remain up for 24 hours before being merged. Speed merging the revert makes any attempts to disagree with ninja's speedmerge incredibly hypocritical.

If a head coder disagrees, then it is final but I will still grumble about it I guess.

for reference, this PR(as in, this very PR right here) removes the missing textures

### CODE REVIEW

**Comment by Whoneedspacee** [comment]
stop let actionninja make a pr as he should have in the first place

**Comment by nemvar** [comment]
There is nothing wrong with the revert getting speedmerged.
The original PR should not have been merged in the first place so letting it hit servers instead of reverting it is irresponsible.
Speedmerges exist specifically for damage control which this was.

**Comment by 81Denton** [comment]
While I agree with the original revert PR (aside from the self merge), I will leave yours up for 24 hours so we can get input from people who disagree with closing this one.

**Comment by Iamgoofball** [comment]
:+1: thanks

**Comment by 81Denton** [comment]
Ah hang on, so this is a revert of the revert that followed after actioninja's PR. My bad, I misread that.

**Comment by Qustinnus** [comment]
lol i also misunderstood that

**Comment by Moja10** [comment]
This is what Oranges was trying to stop the entire time, Pensive Cowboy

**Comment by Iamgoofball** [comment]
@81Denton This PR would put us back to *not* having fallback icons.

**Comment by IndieanaJones** [comment]
Please merge this.  I understand why the original was made, but everything that got borked by this really has made the game look sloppy for a while now.

**Comment by Iamgoofball** [comment]
oh god it merge conflicts

**Comment by Cyberboss** [comment]
Fix the errors not the symptoms

**Comment by Cyberboss** [comment]
Which IS happening btw and likely would not without this feature

#51340
#51328
#51327

**Comment by Fhaxaris** [comment]
correct

**Pull request closed without merging**
