### PR TITLE
Fixes DNA Restore dealing brain damage

### PR DESCRIPTION
**Pull request by LanCartwright**
Joan this is what happens when you do -math with healing.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
this is what happens when you do complex math and don't test it

**Comment by PKPenguin321** [comment]
what the fuck is a testing?

**Comment by optimumtact** [comment]
:-1:

13:31 < aoranges> no
13:31 < aoranges> why is that a problem?
13:31 <+KorPhaeron> actually thats a good point
13:31 <+KorPhaeron> why not have it be a dual symptom
13:31 <+KorPhaeron> or one that can fuck up
13:31 < aoranges> the virologist should learn how to balance their symptom
13:31 <+KorPhaeron> if you do the math wrong
13:32 <%Joan> players have no ingame way to figure out if it'll heal or hurt
13:32 < aoranges> they can apply the disease
13:32 < aoranges> and test
13:32 <%Joan> which is bad tm
13:32 <+KorPhaeron> test it
13:32 <+KorPhaeron> on a monkey

**Comment by LanCartwright** [comment]
complex math requires even more rigourous testing.

I didn't expect this.

**Comment by LanCartwright** [comment]
image

**Comment by ChangelingRain** [comment]
I don't really understand the math here because there's no graph but I'll trust that chart means it works right

**Comment by LanCartwright** [comment]
Thanks for bringing that up @ChangelingRain . I've found it difficult to make charts with two different values, I'll see what I can do next time. It's pretty complicated math I salvaged from MMO and RPGs, I'll simplify it here:

Theoretically the absolute highest stealth possible with toxic filter would be 8, which would remove 2.44  points of healing on average.
The average lowest healing possible is 4.5 average.

Even at 12 stealth, in perfect random math, it shouldn't (on average) deal more damage than it heals.

Or in other words there's no way it could deal damage now.

**Pull request merged**
