### PR TITLE
Makes space credits worth 1/4th less when exporting, plasma is also worth 1/2 less due to it being very easily gotten and the ORM multiplying the refined plasma (RnD upgrades)

### PR DESCRIPTION
**Pull request by ma44**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
if you are doing this so you can be justified in making plants give more points then just stop

**Comment by Core0verload** [comment]
Cargo points **are** space credits, and plasma is totally intended to be the best exportable sheet.

**Comment by YakumoChen** [comment]
Plasma is worth alot because it's a plasma mining research station and it's supposed to be their main export.

**Comment by KorPhaeron** [comment]
This conflicts with stupid stuff I'm doing sorry

**Pull request closed without merging**
