### PR TITLE
Replaces the Exosuit Materials 2 experiment with one about equipping mechs rather than destroying them.

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Replaces "Exosuit Materials 2: Excessive Damage Test" with "Exosuit Materials 2: Load Strain Test". Rather than building and then destroying two exosuits, you now equip them with any two (compatible) main equipment pieces. Once the experiment is done, you'll have two exosuits still, so consider making exosuits that you can donate to other crew afterwards.

Note that the exosuit *has* to be built by the crew. Round-start exosuits (or those obtained through other means like the nuke ops' uplink) will not work.

## Why It's Good For The Game
The idea of creating and destroying a few rounds of mechs sounds like a neat concept. But in practice, it burns through station resources for no real good reason, and is somewhat antithetical to the idea of robotics making mechs for other departments. With this change, you're still required to make the two mechs if you want the discount, but now they'll be available afterwards. If someone has requested a mech for their department, for example, you can now accomplish that and part of this experiment simultaneously.

## Changelog

:cl:
add: Adds a new discount experiment for unlocking the combat exosuit nodes - complete it by scanning two exosuits with equipment in the left and right hand slots. This replaces the prior discount experiment about destroying exosuits.
/:cl:

### CODE REVIEW

**Comment by HoodMilk** [comment]
so much better than "waste 100 iron for this experiment".

**Comment by SimplySmiley123** [comment]
Yeah this is way better, still honestly gonna end up being a waste most of the time, but at least now there's a chance the resulting two mechs will be used by someone, anyone.

**Comment by Exester509** [comment]
I'd rather see this as the Exosuit Materials 1 experiment, while the arbitrary integrity test would become the new Exosuit Materials 2. It doesn't make a lot of sense that the discount takes barely any effort while the stress test takes all the tedium. In their current implementation, Exosuit 2 is the more taxing one, since it's an optional benefit rather than a mandatory experiment.

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
But yeah, the order of the two tests should be swapped at this point.

**Comment by zxaber** [comment]
I don't want to swap them in this PR for two main reasons;
- There was a time where damage could randomly destroy any equipment. I don't remember if that's still a thing, but if so, you'd want to do the damage experiment first
-  There's another PR that aims to make the damage experiment easier, including dropping the required scans to 1 mech, rather than 2. If that goes through, then keeping the current order would make more sense.

**Pull request merged**
