### PR TITLE
Adds a new Centcom Response Team type: Horde of Interns

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
Adds a new ERT type, a human wave of NT Interns

Each intern gets internals, a bolt action rifle, two extra stripper clips, and a police baton. The head intern gets all that, PLUS a dorky-ass hat to command authority with, a megaphone to yell at their peers with, and a vest to sling their rifle on.

I had the idea to add this after sending ~10 centcom officials to the station to combat a giant spider infestation, and wishing there was an easier way to arm them than spawning their extra gear en masse and hoping they took them

[](https://i.imgur.com/obWEz1F.png)

Showing off the Head Intern and Intern outfits. Great thanks to @Mey-Ha-Zah for the excellent sprites!

## Why It's Good For The Game
Adds another tier of CentCom Response Team (at the bottom) that is focused on shooting things en masse, without all the excessive/irrelevant gear and loot of ERT's (you don't _need_ fancy toys like RCD's, medibeams, and pulse weaponry to detonate a nuke!)

Low gear level lets you throw a ton of ghosts back into the game and hope a few of them can stick together and accomplish something. Losing one member of a four man ERT can be devastating, especially if their gear ends up in the hands of the enemy, but losing one intern and their half empty mosin out of ten is par for the course. Remember, it's not human wave tactics, it's the _doctrine of stochastic tactical effectiveness_!

And honestly, most ERT's are horribly coordinated and usually immediately split up and die alone. If they're gonna act like disposable interns, may as well treat them like it!

## Changelog
:cl: Ryll/Shaps
add: New opportunities for (unpaid) internships are available at CentCom for those willing to face danger and earn glory for your company! 
/:cl:

### CODE REVIEW

**Comment by Mey-Ha-Zah** [comment]
love it

**Comment by ArcaneMusic** [comment]
Only gripe: maybe change the uniform to look less like the Centcom officer uniform, or maybe get rid of the sunglasses. It makes them look WAY to official for their unpaid 16 week course on how to manually cure a blob crisis.

**Comment by Fox-McCloud** [comment]
I admit, I don't like the selection of the uniform and hat, but that's mostly because the Captain originally had a green hat+green uniform+green armor....,heck, on Goon, he still does.

**Comment by Shapsy** [comment]
Someone's making a new sprite for the uniform now. It'll still be partly green since they're connected with CentCom, but it'll look far shittier

**Comment by WarlockD** [comment]
I love this idea!  Is there a way to just have the interns have random accessories?  Like they ran out of green shoes so they just gave them what they had, yellow shoes, purple shoes, all clown shoes:)  Everyone wearing "combat" gloves, just a pair of flammable black gloves.

I also like the idea that when they spawn, there is a crate that spawns with them that has one "good" gear.  Like a combat helmet.  Though having your team fight over that at the start might not be the best thing since they are all armed.

**Comment by Anonmare** [comment]
>Armour

What are you, a coward?

**Comment by Shapsy** [comment]
I gave them vests so they can stow their mosins at least (since they can't be slung on the back for whatever reason), but it got in the way of the dope new sprites now in the OP, so now only the leader gets a vest

**Comment by ATH1909** [comment]
Maybe give them cable cuffs too, to go with their batons?

**Comment by Timonkeyn** [comment]
Make them start with coffee pills

**Comment by Shapsy** [comment]
Oops I reverted the last commit, I'll fix it tomorrow

**Comment by Sishen1542** [comment]
Hey wait a minute..
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9137
😲

**Comment by Shapsy** [comment]
*sweats*

**Comment by CRITAWAKETS** [comment]
engineering interns would be really useful since in one of five rounds the SM is always ignored or burning up due to incompetence

**Comment by Mey-Ha-Zah** [comment]
Sishen, I doubt any of the TG coders actively watch the Citadel github for interesting features to steal.

**Comment by KomradeSpectre** [comment]
> 
> 
> Sishen, I doubt any of the TG coders actively watch the Citadel github for interesting features to steal.

I watch a lot of downstream branches for features to port over though, even semen demon station (citadel).

**Comment by Shapsy** [comment]
i'll fix it tomorrow..

**Comment by Shapsy** [comment]
I'm going to remake this

**Pull request closed without merging**
