### PR TITLE
Adds walterje's pais

### PR DESCRIPTION
**Pull request by ghost**
Credit to https://tgstation13.org/phpBB/viewtopic.php?f=11&t=1659

Adds new pAI screens and a new pAI card, as well as a new default emotion, 'null'.

pai pai pai pai pai

### CODE REVIEW

**Comment by ike709** [comment]
pretty :+1:

**Comment by WJohn** [comment]
It's like a gameboy! :+1:

**Comment by GunHog** [comment]
E.L.O.N.A. 2.0 ONLINE :+1:

**Comment by TZK13** [comment]
Out of the three PRs up with WalterJe's sprites this is the only one I feel is an improvement.

**Comment by Miauw62** [comment]
these look amazing :+1:

**Comment by RemieRichards** [comment]
:+1: Love it

**Comment by Yakk** [comment]
Hello, I am a representative from the Nintendo® corporation and your sprites too closely resemble our GameBoy™ portable video entertainment platform. Please remove these like we made you remove the Metroid™s that were an infringement upon our intellectual property of Metroid™.

Thank you for your time :)

**Comment by paprka** [comment]
wot, they don't look anything like gameboys

unless you're implying d-pads are the intellectual property of nintendo

get legalled fucker

**Comment by GunHog** [comment]
Just merge it, already!

**Comment by Tenebrosity** [comment]
lookin sharp

**Pull request merged**
