### PR TITLE
removes gang turrets

### LINKED ISSUE #27816: you can hop on the mounted turret, hop of and run at your enemies as you spit out bullets
LOCUST ATTACK!

### LINKED ISSUE #28507: gang turrets broken again
Can't climb on turrets, three seconds of fucking nothing to try and get on, and you can't
150 hours.

### LINKED ISSUE #29187: MG Turrets have no cooldown
THE FUCKING MACHINE GUNS APPARENTLY HAVE ZERO COOLDOWN BETWEEN VOLLEYS, LEADING TO ME RUNNING DOWN THE HALL THINKING IT'S SAFE TO APPREHEND TO IDIOT ON THE TURRET AND THEN DYING ALONG WITH MY OFFICER WHO HEARD THE GUNFIRE AND FIGURED IT WAS SAFE.

### LINKED ISSUE #29188: MG Turrets still shoot when the person is stunned.
Title. If we're gonna have turrets then please fix this shit or remove it from the uplink.

### LINKED ISSUE #29189: The extended vision on MG turrets is also broken.
It ends up with a little square in the center with your effects and stuff and then extended view which is extremely disorienting. No pictures right now and I'm pretty sure there's another issue for this open anyway but couldn't find it. @Robustin

### PR DESCRIPTION
**Pull request by BeeSting12**
:cl: BeeSting1
del: Gang turrets are removed.
/:cl:

Why: These things have multiple issues that noone is fixing and they're unbalanced.

Closes #29189
Closes #29188
Closes #29187 
Closes #28507
Closes #27816
There's another one that isn't just relating to turrets so I left that one.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
This looks like balance.

**Comment by BeeSting12** [comment]
LeoZ said that removals were fine during the freeze though

**Comment by XDTM** [comment]
not this one, i'm pretty sure

**Comment by CPTANT** [comment]
Can this be re-opened? 

I feel the mg turrets really feel out of touch with the gang gamemode and on top of that are plagued by numerous issues.

**Pull request closed without merging**
