### PR TITLE
[MDB IGNORE] Big Access Tweaks and Organization

### LINKED ISSUE #67498: Paramedics can't do their job now.
Reporting client version: 514.1584

## Round ID:
[184238](https://scrubby.melonmesa.com/round/184238) (It has been around for at least a few rounds now)

## Testmerges:
- [Adminwho now caches feedback links until admins are reloaded (and also works again)](https://www.github.com/tgstation/tgstation/pull/67307)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Disables soft lock on traitor objectives](https://www.github.com/tgstation/tgstation/pull/67385)

## Reproduction:
1. Be a paramedic
2. Attempt to enter any department that isn't medical
3. notice you can't enter.

I don't see a PR removing paramedic's access to any of these departments (sans EVA), so I'm presuming this is a bug.

I can get removing Engineering access (though I don't like it), I can also understand removing cargo access, removing EVA is annoying, but science access basically only gave you access to nanites, and service basically only gave you access to the lathe, which doesn't mean much.

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This request organizes the access.dm folder and jobs.dm folders to alphabetical order inside of the lists for regions and accesses, as well as moves the accesses around a bit within the individual job for easier reading (puts extra access on the bottom instead of the top)

Since I was going through and organizing the folder, I also audited through the accesses and removed some of the ones I believed were holdovers or unnecessary for the job role, and added one or two that I thought a job role would need. Because of that I'm going to label it a balance change even though most of what I'm doing is fixing stuff. I also changed some jobs that previously had research access to have science access instead and gated some of the science machines under access_research instead of access_science. 

<details>
<summary> Here is a list of the accesses that were changed per job: </summary>

Atmos Technician:
min: No changes
extra: removed MINERAL_STORAGE (It is already on min access). Added MINISAT, TCOMMS. 

Bartender:
extra: Removed MORGUE (Morgue unnecessary to perform functions on lowpop, even if taking over for chef)

Botanist:
min: Removed MORGUE (Not needed in highpop / encourages interaction with medbay for podpeople)
extra: Added MORGUE (More autonomy on lowpop to do podpeople)

Captain:
no changes

Cargo Technician:
no changes

Chaplain:
no changes

Chemist:
min: Removed MORGUE (Not necessary for job function)
extra: Added MORGUE (Added in case lowpop needs chemist to act as doctor)

Chief Engineer:
no changes

Chief Medical Officer:
min: Added CONSTRUCTION (for front of engineer access, lathe, open way to minisat)
extra: no changes

Clown:
no changes

Cook:
no changes

Curator:
no changes

Detective:
no changes

Geneticist:
no changes

Head of Personnel:
min: no changes
Removed MORGUE, RESEARCH. Added SCIENCE (Removed morgue for same reason as crematorium. Research -> Sci to properly reflect general access)
extra: no changes

Head of Security:
min: Removed RESEARCH. Added CARGO, SCIENCE, SERVICE (Sci as alt to research, cargo as missing despite shipping access, service as a miss from when that access req was added)
extra: no changes

Janitor:
no changes

Lawyer:
no changes

Medical Doctor:
no changes

Mime:
no changes

Paramedic:
min: ~~Removed RESEARCH. Added CARGO, SCIENCE (To give them basic access to all departments, res->sci because sci is the access that reflect general access now)
extra: no changes

Prisoner:
no changes

Psychologist:
no changes

Quartermaster:
no changes (Though I wish I could give them extra access COMMAND ; (   )

Research Director:
min: Removed: MINING, MINING STATION, MEDICAL, Added CONSTRUCTION. (While the RD needs minerals to function they should never be taking over for mining and really it's not necessary for the job function. It only opens up the RD stepping in where they shouldn't be. Medical is a holdover from when the geneticist was in medbay and also isn't necessary for their job. Construction added to give basic access to engineering and enable access to the minisat/tcomms.)
extra: no changes

Roboticist:
min: no changes
extra: Removed ORDNANCE, ORDNANCE STORAGE (To fit with other science roles' extra access)

Scientist:
no changes

Security Officer:
no changes

Departmental Officers:
no changes

Shaft Miner:
min: Removed SHIPPING (So that miners don't have access to the mail room, opens the way for the shuttle and ordering console to be put under shipping. Talked with John about that but I don't think it fits in this PR so it'll be done elsewhere.)
extra: no changes

Spare Shaft Miner:
min: Removed SHIPPING (See above)
extra: no changes

Station Engineer:
min: Added MINISAT (So they can access the minisat for repairs)
extra: no changes

Virologist:
no changes

Warden:
no changes

</details>

I also renamed ACCESS_MAIL_SORTING to ACCESS_SHIPPING. This is to generalize the access more so we can use it to gate other things if we want in the near future (things like the shuttle or ordering console being accessible). I didn't want to do that here because I found the order console doesn't currently have reqs associated with it and want to discuss it more before I or someone else puts up a PR for it.

I also went through our maps and did some necessary reorganization for some areas to allow the paramedic to properly access some areas, namely in engineering (since I was able to fix most of their access in the access tweaks). I also fixed engineers having access to secure tech pending merging of #67503 . I also added an access helper for the minisat so that access could be properly utilized using that access for those areas and standardized it as much as possible across all stations. I did the same standardization with access to the power control console (making it general) where possible. Some are in the engineering equipment room so I didn't change the access there. Most of that is in an effort to use ACCESS_CONSTRUCTION as less of a catch-all so we can properly portion out access where it's required.

I also fixed access being gated to the minisat via science on TramStation. While that means you can now access the science general hall with things like minisat or tcomms access, people can actually get their and do their jobs now. Just an unfortunate reality of the layout we have.

## Why It's Good For The Game

Better readability for our accesses. Trimming of holdover accesses from a bygone age and fixing of accesses that weren't fixed or were improperly added due to the confusion between ACCESS_SCIENCE and ACCESS_RESEARCH. More consistent / equal skeleton crew access. Proper access to proper areas (minisats and tech storage). Sets the groundwork for future polishing of the access system.

Fixes #67498 

## Changelog

:cl:
code: Reorganizes some of the access and jobs access code for readability
balance: The minisat and tcomms are more accessible to engineering roles on skeleton crew, and engineers normally
balance: Service personnel who do not handle corpses have had their morgue access revoked and moved to skeleton crew.
balance: The HOP has had their cremator access revoked, as they are not licensed to handle the dead
balance: The Research Director has had their mining and mining station access removed.
balance: The Research Director has been given construction access to allow for access to the minisat and that access has been removed from the HOP
balance: The roboticist has had their skeleton crew access to ordnance revoked to align with the geneticist's skeleton crew access
balance: Miners no longer have SHIPPING access (previously Mail Sorting)
fix: The HOS has proper access to the basics in each department again
fix: A holdover access from when genetics was in medical has been removed from the Research Director
fix: Paramedics can now access the entrance doors for most departments again
fix: Minisats across all maps have proper access requirements to their contents
fix: Tech storage now uses its access properly and again requires both command and tech access to get to secure storage
/:cl:

### CODE REVIEW

**Review by Timberpoes — CHANGES_REQUESTED** [review]
Can you document all actual access additions and removals you made to trims. Because you reformatted them its.not obvious in.this PR.

Also please make the changelog more detailed in with those access changes else MSO gets irate.

The DNM tag is for these two points. Once everything has been properly documented in the PR body and changelog it can be removed by any maintainer.

Finally, when multilining lists I believe the accepted formatting is every list item ends with a comma including the last, with the trailing closed parenthesis on a new line.

This makes additions and removals at the bottom of the list end with cleaner commit histories.

**Comment by Timberpoes** [comment]
Right, that's clearer and there's a decent list of changes.

Now I'd like you to go through your access changes and outline your thoughts on why they've been changed (ie. why do you believe X job needs/no longer needs access to Y place on high/lowpop?).

There's a whole bunch of changes and not all of them are self-explanatory.

**Comment by Son-of-Space** [comment]
Edited as requested.

**Comment by Timberpoes** [comment]
What is locked behind ACCESS_CONSTRUCTION and how does this fit in with RD and CMO job needs?

**Comment by GuiltyNeko** [comment]
Hey so as long as you're touching secure tech storage access, because it uses accesses from two access regions, unlike the vault, there is no door remote that can control that door, so a combined access would be beneficial there.

**Comment by Son-of-Space** [comment]
> What is locked behind ACCESS_CONSTRUCTION and how does this fit in with RD and CMO job needs?

Construction is generally the gravity generator, any aux construction rooms, sometimes vacant offices. It's not consistent what access it's under and it's one of the things I intend to clean up in the near future.
I'm using construction as an alt access since construction would also allow access to the engineering lathe. It gives the RD and CMO access to go into the engineering bay and get to the minisat if necessary through use of the least number of accesses possible.

**Comment by Son-of-Space** [comment]
> Hey so as long as you're touching secure tech storage access, because it uses accesses from two access regions, unlike the vault, there is no door remote that can control that door, so a combined access would be beneficial there.

I don't really understand what you're asking me to do here.

**Comment by JohnFulpWillard** [comment]
Didn't see this until now, sorry. I'm assigning myself since I discussed this in mapping channels.

> What is locked behind ACCESS_CONSTRUCTION and how does this fit in with RD and CMO job needs?

That's Engineering foyer and techfab, which is what all of Command had access to in the past. Instead of snowflaking adding Bridge access to Engineering Foyer, I find construction to be the better plan for it. I like the idea of departments asking their head of staff to get parts/tools for them, in the same way I like it when people ask their heads of staff to research stuff for them.

Now for the PR:

- Bartender & Chaplain: They should keep their theatre access, it's access to costumes for whatever religion they have, or hats for Pun Pun.
- Head of Personnel: They should keep crematorium access. While we preferably don't want them cremating people, especially when there's a Chaplain, it's still their department (and that fact will hopefully become more evident to players if QM actually becomes a head), and they are one more person that security can ask to open doors quickly in case of a Changeling, or any other case, reliance on command staff is better than reliance on silicon imo.
- Paramedic: You didn't add Surgery like your PR body says, you added Pharmacy, which I am not comfortable with, because for literally no one else to have access to chem machines, it would require no Chemists, a CMO, MDs AND a Viro, which I really don't see happening often. I would rather they stick to having to ask/steal access, I don't like paramedics constantly tipping into everyone else's jobs.
- Research Director: Yeah it's fair. The access was cool to get yourself to techfabs for experisci, or to help robos that want medibots. Mining used to get into cargo which was where Bepis was, but asking department workers to be let in is probably better, plus we shouldn't be encouraging RD to leave their department to do experiments, should be delegating that to scientists.
- Virologist: Consistency isn't really arguable here. MDs on lowpop get pharmacy and not chem lab, so I think Viro getting chem lab instead of pharmacy is fine, they're only one job slot, so getting access to just one chem machine set seemed fine.

**Comment by Son-of-Space** [comment]
Those all make sense. I'll make those changes.

**Pull request merged**
