### PR TITLE
Mass-replacement of stat to machine_stat

### PR DESCRIPTION
**Pull request by Rohesie**
Living and machine `stat` vars are pretty different, one uses flags and other number-defines.
This should make some other mass-replacements and searches a bit easier.

### CODE REVIEW

**Comment by spookydonut** [comment]
The only benefit of this is VV will show the correct flag names

**Comment by Rohesie** [comment]
Made that happen. Guess it's another benefit.

**Comment by optimumtact** [comment]
holy conflicts batman

**Comment by Rohesie** [comment]
Conflict solved.

**Pull request merged**
