### PR TITLE
Removes clown..

### PR DESCRIPTION
**Pull request by optimumtact**
..mask typo that always bothered bgobandit

### CODE REVIEW

**Comment by bustygoku** [comment]
Wouldn't it be honk-mother

**Comment by optimumtact** [comment]
because that is the lore

**Comment by CosmicScientist** [comment]
Why is Clown Mask capitalised? Could you tell it to insert the name there so it's "Your clown wig and mask blah blah"?

**Comment by bgobandit** [comment]
https://www.youtube.com/watch?v=coCjlhyFug8

**Comment by Firecage** [comment]
Busty, it is Honk Mother because it is a Deity, like Zeus, or the super mythical Jahaweh.

**Comment by bgobandit** [comment]
It's the Honkmother. Like the Godfather.

**Comment by Chocobro** [comment]
:+1: made me click

**Pull request merged**
