### PR TITLE
Small grammar correction for emergency teams

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by Qbopper** [comment]
stolen from reddit

**Comment by Signmark** [comment]
how do i upvote on this site xd

**Comment by MrStonedOne** [comment]
>how do i upvote on this site xd

Click the smiley face icon in the top right then click the thumbs up icon.

**Comment by Mark9013100** [comment]
elite erp

**Comment by calzilla1** [comment]
DO IT

**Comment by optimumtact** [comment]
well i dont agree so im closing this pr but only blind people can see this message so everyone else is gonna freak the fuck out

**Pull request closed without merging**
