### PR TITLE
Fixes some map editing of items

### LINKED ISSUE #21823: The syringe in brig medbay on box is called "steel point"
no player references

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #21823

### CODE REVIEW

**Comment by Niknakflak** [comment]
when did this get in and why?  What the fuck
"Yo guys, I have a player reference, I named a syringe to my name on the map"
...what?

**Comment by lzimann** [comment]
In box was when steelpoint or someone that I don't remember redid the brig to include the little medbay there. It's really easy to get player references in a map, specially if the diff is big.

**Comment by ExcessiveUseOfCobblestone** [comment]
just goes to show how much that room sees use

**Comment by optimumtact** [comment]
This is very minor, do grow up

**Comment by Iamgoofball** [comment]
this was actually added by quiltyquilty or whatever their name was at the time, they told me they slipped it in in the brig redo PR ages ago

**Pull request closed without merging**
