### PR TITLE
Fixes a firebot runtime

### PR DESCRIPTION
**Pull request by TerraGS**
## About The Pull Request
Firebots were runtiming due to multiple initializations, so this fixes that issue by calling a proc to refill the extinguisher rather than going through the initialize proc to do it.

## Why It's Good For The Game
Runtimes are bad.

## Changelog
:cl:
fix: Fixed a firebot related runtime
/:cl:

### CODE REVIEW

**Comment by TerraGS** [comment]
Not sure if this counts as a refactor. Still hazy on the definition.

**Comment by ShizCalev** [comment]
Realllllllly not a fan of splitting code like this.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Atomize this (ie make separate PRs for the fix and the refactor)

**Comment by TerraGS** [comment]
@ShizCalev If the part about moving the code into construction is the part you don't like, you should understand that this was already the case for medkits and toolboxes and I was simply following that model. If the opposite is what you would prefer I can revise my changes to move all the object out of construction.dm and into their respective object files.

**Comment by TerraGS** [comment]
I'll move ahead in that direction and just leave this as a fix for the runtime.

**Comment by TerraGS** [comment]
@ShizCalev Ok this is now just a runtime fix

**Comment by TerraGS** [comment]
Learning to rebase at the moment

**Review by ShizCalev — APPROVED** [review]

**Comment by TerraGS** [comment]
He didn't remove the thumb down reeee

**Pull request merged**
