### PR TITLE
Box Revamp and Overhaul

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
A complete revamp of Boxstation. Changes literally everything.
Old crusty smelly box:
boxold
New great box of greatness:
boxnew
Diff map for funsies:
boxdiff

## Why It's Good For The Game
Boxstation has been getting old and crusty. This _fresh_, _new_ take on the station, I believe, improves the game immensely and is really the best change since sliced bread. (Happy April 1st.)

## Changelog
:cl: Inept
fix: Box is fixed.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
No supermatter. 0/10 go back to the drawing board

**Comment by wesoda25** [comment]
Excuse me but thats not a box

**Comment by cacogen** [comment]
Updating those paths must've taken hours

**Comment by PKPenguin321** [comment]
image
very good

**Comment by EOBGames** [comment]
> Updating those paths must've taken hours

if only it were that simple...
no, this is reconstructed from a screenshot
it took 4 days please send help

**Comment by cacogen** [comment]
Christ

**Comment by EOBGames** [comment]
> image
> very good

the biggest tragedy is that there isn't 24 assistant job slots... unless...?

**Comment by Hanador** [comment]
Good change the Supermatter was an awful engine anyways I for one won't miss it and its boring delaminations. I also really like the new AI location and that you re-added cloning.

**Comment by nicbn** [comment]
Oh that brings memories

**Comment by Fikou** [comment]
> Updating those paths must've taken hours

i tried doing the same thing to see if it would work, updating paths took about an hour but the map just glitched out, maybe if you edited it directly with search and replace and some text editor that would work

**Comment by davethwave** [comment]
Unless the singulo changed, that isn't a large enough space for the singulo. I mean, it's enough *space* but when it reaches tier 3 it will breach containment and eat through the station into tier 4 and all that.

**Comment by TheVekter** [comment]
My dumbass sat there for a second like "oh that looks familiar"

**Comment by ATH1909** [comment]
First off, wow, this is a really amazing recreation.

Second off, there are some... problems with it:

Genetics is in Medbay, but Geneticists don't have Medbay access anymore like they used to.

Medical doctors don't have access to a full set of surgical tools, nor can they print any without a medical protolathe. They need to go to cargo and print their tools there, I think, or make their own autolathe.

The chaplain doesn't get a null rod.

There are no medHUDs in Medbay (except maybe in the CMO's locker? I forget if there's one in there).

The mechanical fabricators in Robotics deposit their printed items into the centers of the winows to the south of them. If you don't move them, you'll HAVE to break one of those reinforced windows to access the items you printed, as they're directed windows, not fulltile ones.

**Comment by ATH1909** [comment]
I also don't think that certain traitor theft objectives (secret documents, reflective trenchcoat, etc.) will spawn anywhere on this map. Has this been accounted for?

**Comment by ATH1909** [comment]
Lowkey, I think that keeping this in the code as a meme map for admins to occasionally select would be really, really cool, especially seeing as how so much effort has gone into making this PR.

**Comment by senjx** [comment]
shut up athath

**Comment by EOBGames** [comment]
I didn't account for really anything given this was made for a 1 day meme event, that said I wouldn't be averse to cleaning it up a bit and making it properly playable in modern code if admins are willing to run it occasionally.

**Comment by fatted50** [comment]
This is the worst layout I have ever fucking seen. I never thought I'd actually miss old box somehow, but you pulled it off. Good job you absolute madman.

**Pull request closed without merging**
