### PR TITLE
Revert "Sacrifice rune hotfix"

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/-tg-station#11903
TRAVIS FAILED OH FUCK WE FUCKED IT UP

### CODE REVIEW

**Comment by Miauw62** [comment]
IT WORKED IN TESTING

**Comment by Xhuis** [comment]
AYYY

**Comment by RemieRichards** [comment]
CAN YOU TWO GET YOUR SHIT TOGETHER?

**Comment by Miauw62** [comment]
dont merge yet pls

**Comment by Miauw62** [comment]
it might just be travis fucking up

**Comment by Xhuis** [comment]
# ___AAAAAAAAAAAAAAAAAAAAAAAAAAA___

**Comment by Miauw62** [comment]
travis is ded, make a new PR xhuis

**Pull request merged**
