### PR TITLE
[MDB IGNORE] Revert thermomachines

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Many people want this, @LemonInTheDark wants this, here it is

## Why It's Good For The Game
is not but is better if i do this and not someone else
image

## Changelog

:cl:
revert: revert thermomachines to be magic heat deleters
/:cl:

### CODE REVIEW

**Comment by InsaneRed** [comment]
is this not gonna effect the setups we have in place for thermomachines? i.e places like turbine or even that onewhiteship which has a whole H/E setup for the thermomachines to work

**Comment by Ghilker** [comment]
this is not going to affect a thing, existing setups will still work fine

**Comment by Pickle-Coding** [comment]
It doesn't look like TEG is coming back any time soon, so I don't see any problem with this, even if it's magic. It just moves heat with a bluespace field or something.

**Comment by Ghilker** [comment]
no is bad

**Comment by InsaneRed** [comment]
freezers/heaters were amazing and stopped the unnecesary garbage that is setting up an entire waste system for something youre gonna use for 30 seconds,

**Comment by InsaneRed** [comment]
also will we still be able to change between heater/freezer with a button

**Comment by Ghilker** [comment]
> freezers/heaters were amazing and stopped the unnecesary garbage that is setting up an entire waste system for something youre gonna use for 30 seconds,

remove gameplay is fun, we need to crunch those numbers fast

> also will we still be able to change between heater/freezer with a button

no thermomachines are automatic, they have been since the changes i made, just set the temperature

**Comment by Ghilker** [comment]
No you know what? I'm not going on with this one, I like the feature and it adds an interesting behaviour. 
I tried to make it better by adding heat pipes but that didn't went through.
I'm not going to butcher the thermomachines because someone is annoyed that it needs a further step to be in high working conditions.

So I'm going to close this.

**Comment by iprice** [comment]
Bait and switch, sad.  Thermomachines are a pain and realism isn't the goal.  Signed, an overheating medical.  Again.  Thanks freezer.

**Comment by Capsandi** [comment]
I'm glad this was closed, but it is true that requiring a full pipenet to heat air is too much. Its better to keep the partial fix than to regress to the times when heat was free

**Comment by LemonInTheDark** [comment]
@Ghilker You don't need to do this. I don't think there's a good reason to, at least not right now since I've not done anything to the role yet, and atmos as it is now is setup for this. You especially don't need to do this yourself, that's not a feeling I'd wish on anyone.

**Comment by Pickle-Coding** [comment]
Roundstart waste cooling isn't enough. Would probably want waste filled with CO2 at the start of the round, because thermomachines still superheat the CO2 people breathe out and cause an endless fire.

**Comment by Potato-Masher** [comment]
I will say, thermomachines moving heat like this does have some use when moving extreme levels of heat around. Seems to work more reliably than heat pumps ever did.

**Pull request closed without merging**
