### PR TITLE
Engineering Points:. Shadowlight is [TRIGGERED]

### PR DESCRIPTION
**Pull request by Iamgoofball**
# >make engi point vendor
# >get told rewards are shit make new ones
# >complies with request
# > gets PR closed for adding unique vending rewards

See: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=9920

Every other department (besides sec) has a progression mechanic, usually gated behind RNG, metaknowledge, and materials in order to acquire. Engineers meanwhile are pretty much done 2 minutes into the round and have very few ways to personally enrich their job experience. So while cargo rides by on ATV's with shotguns slung on their backs, botany has invented the most deadly bannana in existence, robotics is rolling out in Durands with modules that would make a mauler blush, RND and genetics are pretty much demigods... engineers, at best, go around repairing the other departments so they can keep doing cool shit while the engineers get a pat on the head before slinking back to stare at the engine.

THAT CHANGES TODAY!

YOU GET POINTS FOR DOING SHIT AND PUSHING YOUR ENGI AUTISM TO THE LIMIT AFTER SO MANY CHANGES IM DONE REVISING THE DESCRIPTION.

This PR has been locally tested and is 100% ready to ACTUALLY MERGE YOU PUSSIES

🆑 Robustin
add: Added special rewards available from the new Engineering Vendor, these includes the new items and other ultra-rare equipment - the currency is a new point system you get from addressing alarms, exporting power, and filling canister orders!
add: Added the Power Exporter, beam away power from the grid for Engineering points.
add: Added the Engineering Point Vendor, receive points for keeping the station powered and full of non-burning air.
add: Added the Atmos Canister Exporter, receive points for filling a rotating set of orders of various difficulty.
add: Added several new powerful engineering items, equipment, and vehicles. The vehicles are specialized and carry several unique features.
experiment: The Nuclear Fission Construction Device, rumor has it this prototype can ravage the station, or reinforce it, depending on its owner's will.

/🆑

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@Robustin update your conflicts

**Comment by Haevacht** [comment]
Hey this meme conflicts with your RCD.

**Comment by Iamgoofball** [comment]
Cool

**Comment by Haevacht** [comment]
You could have probabl6y squashed it man even for a meme that many commits is unsightly, especially without comments in between em.

**Comment by Iamgoofball** [comment]
Squash merge is a thing

**Comment by coiax** [comment]
Goof, if you're serious with helping Robustin get this merged, then start making PRs for the individual rewards I guess?

**Comment by Haevacht** [comment]
wait why does this touch the clown shuttle ruin what the fuck cjs

**Comment by Iamgoofball** [comment]
Why the fuck would anyone merge a vendor that comes with nothing by default and needs other PRs? Am I the only one who sees what they're doing here?

**Comment by Haevacht** [comment]
No get that concern the fuck out of here why does this touch the clown shuttle

**Comment by ExcessiveUseOfCobblestone** [comment]
>Why the fuck would anyone merge a vendor that comes with nothing by default and needs other PRs

^^^^^^

If you don't like an item, just _give it a chance_ instead of demanding the entire point of the system gets gimped becaused each item must have at least 100 comments about theorycrafted balance.

**Comment by SgtxRootbeer** [comment]
Refactoring of bananium walls.

**Comment by sawrge** [comment]
this entire thing is a really bad idea and robustin was told this several times before ignoring that and spending weeks on it anyway

**Comment by MMMiracles** [comment]
Assistant points when? I need more incentive to tide more effectively.

**Comment by Repukan** [comment]
>not treating your notes for greytiding as the points

**Comment by Iamgoofball** [comment]
@Robustin fix pubbystation and the RCD please this is on your branch

**Comment by Iamgoofball** [comment]
@sawrge gives engineers reasons to do their job so

**Comment by MMMiracles** [comment]
im pretty sure the main reason engineers don't do their job is the fact that most people call the shuttle at the sight of a broken window, not that they aren't getting patted on the head and told what a good boy they are for doing their job.

**Comment by SgtxRootbeer** [comment]
@MMMiracles
Maybe people call the shuttle because engineering isn't gonna fix the issue. They're just gonna sit at the bar until the bar gets blown up...

**Comment by MMMiracles** [comment]
@SgtxRootbeer Engineering doesn't fix anything because people call the shuttle the moment anything gets broken and it'll be reset in 15 minutes. The people call the shuttle the moment anything breaks because Engineering doesn't see the point in repairing something that'll get reset in 15 minutes. Engineering doesn't fix anything because ...

See the issue here?

**Comment by Bawhoppen** [comment]
maybe I missed a previous PR but can you explain all the rewards?

**Comment by kevinz000** [comment]
Dumb goofball cat

**Comment by Shadowlight213** [comment]
@ExcessiveUseOfCobblestone
Some of the items like the ARCD and the vehicles were fine.
However, Robustin decided to add shit like krav maga, and stealth armor that has 0 business being in there as rewards, and rather than remove the controversial stuff, which would probably have gotten the pr merged, he threw a massive hissy fit, and refused. Jordie has said he might merge it if the rewards were atomized, but of course, Robustin said no.
It's his own fault really.
@iamgoofball I closed the PR with cheri's approval. I was literally given maintainer to do so. Bring it up with cheri.

**Comment by SgtxRootbeer** [comment]
Why didn't​ you just tell Cheri to close it?

**Comment by Shadowlight213** [comment]
Jordie had said to atomize the controversial rewards already. I probably could have been more clear, yes.
Also cheri didn't close it because he said maintainers didn't have the heart to close a pr that someone had worked on for so long.
Being an admin, my soul was already gone and I had no issue with it, so I was given maintainer to do it.

**Comment by Iamgoofball** [comment]
I'm not going to accept someone being given maintainer because someone else can't put their foot down. If they know the reason is stupid and they do not want to close it, shoving it off on someone else is unacceptable. I will continue to reopen this PR.

**Comment by Iamgoofball** [comment]
@optimumtact Can you clear shitposts like @kevinz000 @Repukan and @MMMiracles

**Comment by sawrge** [comment]
Watching numbers go up until you get bullshit loot isn't engaging gameplay and this will absolutely be powergamed into an optimal engine setup sooner or later and rendered totally pointless

The rewards are also fucking terrible in their own right.

Engineers already have a reason to do their jobs. If they don't, literally nothing works. If you want to encourage them, prevent the twenty minute shuttle calls.

**Comment by Niknakflak** [comment]
ban him from the repo while you can

**Comment by SgtxRootbeer** [comment]
@swarge, we can fix the engine setup stuff by simply tweaking the numbers of the various systems, for example, the alarm system could be given a much much higher bounty, and the engine setup lesser so, so engineering gets more points from repairing thant they do from making a super-autism engine.

@Niknakflak no
@Iamgoofball ######## do you consider me a shitposter?

**Comment by Robustin** [comment]
Shadow I discuseed both items with you, I even nerfed the decoy armor AND bumped it price by 50% and you still won't even acknowledge it. The maga gloves are a silly joke that takes an obscene amount of time for the weakest martial art. The ARCD is easily stronger than either of those items right now.

**Comment by Robustin** [comment]
I'm going to wait and hear what Jordies doing since it seems like they will have control over how this plays out.

**Comment by optimumtact** [comment]
here's a shitpost for you goof.

i never liked this stupid thing, it's the clunkiest piece of game design I've seen since the mining vendor. It's like baby's first game design meme and it's literal garbage. There are developers at bioware who can come up with better game systems than this. It lacks creativity, it's the sign of a small minded thinker. Iv'e seen fourth graders who can brainstorm a better way to incentivise engineers than this.

I'd rather merge the PR that made cats into a full race rather than this excuse of a pr that tries to cover up the lack of interesting mechanics for engineering. It's embarrassing, it's like someone tried to ice the plain cake but somehow thought it would be a good idea to ice it with something disgusting, like fake whipped cream in a can, it's literally worse than when they started out and now you can't save the cake because it's covered in whipped cream.

**Comment by optimumtact** [comment]
I should have just closed robustin's pr in the first place the first time.

**Comment by optimumtact** [comment]
and yeah I know it's really quite hard to achieve that, but being an open source project we should strive for the right way, and not merge something now just to paper over cracks in a system. (Something we ahave all been guilty of before)

**Comment by shornwolf** [comment]
>If anyone wants to know where I stand on this, making systems that are engaging so that they are their own reward is the right way to do things.

>Making grind fests for points so you can access items later is the wrong way, and is literally everything bad about most of our current systems.

I see nothing wrong with implementing a point system until an actual engaging department mechanic can be applied to engineering. This works great with mining because you're not restricted to autistic points grinding, you can ignore that system and just KA blast your way to ruins and megafauna. It's the best of both worlds.

Engineering was already boring before, but with the removal of the tesla/singularity engines, it's literally nuffin. The only people who play the job do it to be assistants with easy access to gloves and hardsuits. Your entire argument revolves around "I don't like thing, so nobody should be allowed to try it." Just because there may be a different approach to improving gameplay doesn't mean all other factors are null and void.

**Comment by optimumtact** [comment]
it will make engineering worse and lead us down a path that is too hard to climb back out of, it's why the mining vendor still exists.

the fact you claim that the supermatter engine is less engaging than the tesla/singularity makes me doubt your judgment anyway.

**Comment by shornwolf** [comment]
I never said the supermatter was less engaging, I was commenting on the fact that the server flat out removed 2 optional engines to an otherwise boring department, making it that much more boring. Cool projection Ahmed.

**Comment by optimumtact** [comment]
We did that so we can focus on making one engine much more interesting and engaging.

it's a depth versus width issue.

Just having lots of boring cakes isn't interesting or engaging.

**Pull request closed without merging**
