### PR TITLE
Changes clown/mime naming to use preferences. 

### LINKED ISSUE #497: Clown arrival announcement announces Clown's default name
##### Revision that this bug was encountered on:
Show-server-revision doesn't display the revision correctly.

##### Server which you encountered the bug on:
Sibyl 1

##### Problem Description:
A clown's arrival is announced by the AI before it chooses its name, so the name reported by the AI is usually incorrect.

Could cause problems telling latejoin clowns apart from your assassination target, as the name on your objective is the clown's default name.

##### Steps to reproduce the problem:
1. Make sure there's an active AI
2. Join the game as a Clown
3. Your default name will be announced before you choose your proper one

##### Possibly related stuff:

### LINKED ISSUE #928: Bible: No second chance at renaming it if your first attempt was too long
##### Server Revision: 
*unknown*

##### Server:
Sibyl1

###### What did you expect to happen? 
If I chose a bible name that was above the character limit, I'd be allowed to change it.

###### What happened instead?
I was stuck with this:

###### Why is this bad/What are the consequences?
I'm a perfectionist. So I can't deal with it. I can't.

And this is an insult to the church of the Combustible Video Game Man

##### Steps to reproduce the problem:
1. Spawn chaplain
2. Name your Bible something long, like, "One day while Andy was masturbating, Woody got wood."
3. Observe that your title was cut off, and you have no opportunity to change it.

### LINKED ISSUE #1643: Clowns can drop their PDA or ID before name change
8d3d006c67fd3b2ce2a630fcd9c46b90ea7c711c
Problem: You can make your ID/PDA make not match up with your real name
Reproduce:
1. Spawn as clown
2. Drop ID
3. Change name with the roundstart popup
4. Compare ID name to your name

### LINKED ISSUE #2636: Mime name fails to take
Long story short - for some godawful reason there's an invisible timer on mime naming which means that it flatout won't work if you take longer than ten seconds or so, but it won't inform you and your choice is gone forever.

### LINKED ISSUE #3558: bible doesn't spawn?
HELP: snip/(snip) (?) (PP) (VV) (SM) (JMP) (CA) : Hey I got disconnected naming my bible and such, when i reconnected, i dont have a bible. i was wondering if you could spawn one for me please

### LINKED ISSUE #4052: Chaplain's bible spawn easily breaks
I mean really, the menus are presented to you at roundstart, and if you get a lag spike and disconnect for a moment, or something happens to your internet before you select names, everything breaks. This leads to you not getting a bible (annoying) and not being able to choose name of deity and religion and bible's appearance (very annoying).

I suggest it's made so chaplain starts with an item that, when activated, gives him these choices and spawns bible once you answer the questions.

### PR DESCRIPTION
**Pull request by phil235**
- Players will now choose their mime/clown/AI/cyborg name in the main preference screen and save it, instead of choosing at roundstart. (note that this will only work for cyborgs if config.rename_cyborg is activated).
- Players will also choose their religion and deity names in the preferences while the bible icon will be chosen at roundstart by clicking their bible (which spawns in your backpack now) (only works as a chaplain and once per round).
- Adding a config file for random mime names.

Fixes #2636
Fixes #497
Fixes #1643
Fixes #4052
Fixes #928
Fixes #3558

### CODE REVIEW

**Comment by AnturK** [comment]
Aw yeah. :+1:

**Comment by RemieRichards** [comment]
I don't like how every job that has a custom name will need a variable.
Can't you achieve this with a custom named associative list?
eg ```name = prefs.customNames[role]```

**Comment by bgobandit** [comment]
:honkman:

**Comment by Miauw62** [comment]
Any chance of adding chaplain stuff to this?

**Comment by phil235** [comment]
I'm working on it.

**Comment by phil235** [comment]
Should be ready to go.

**Comment by Amnestik** [comment]
I kind of like being able to choose my name at roundstart, depending on what's going on and what mood I'm in. Isn't it possible just to increase the time limit players have to choose to a couple of minutes?

**Comment by phil235** [comment]
@Amnestik It's possible but it wouldn't fix the issues that relies on that roundstart timer.

**Comment by Dorsisdwarf** [comment]
0/10 :-1: 
half the point of being able to rename yourself as a clown is to make a joke about something that's happening.

Likewise this negatively affects people who run differing names, or who have the wrong name set up.

**Comment by phil235** [comment]
>half the point of being able to rename yourself as a clown is to make a joke about something that's happening. Likewise this negatively affects people who run differing names, or who have the wrong name set up. 

You do realize that with my PR you can change your clown name in the lobby at any moment right? If something is happening, you can change your clown name in the lobby just as fast as before, I fail to see what opportunity would be lost. And if we're talking latejoining clown then my system is objectively better since there is no timer.
 
Also each of your three saved characters can have a different clown name saved. With our current system people already make mistakes and end up with a name they don't want (and they can ask admins to fix it).

**Comment by Amnestik** [comment]
We're talking about IC events. What other characters are on board, what's happening at the time.

**Comment by AnonymousNow** [comment]
It does undermine one of my favourite gimmicks - naming myself in theme to whoever my partner in crime is (mime, AI etc.). It's a thing that can only be seen and reacted to ingame.

All we needed was a longer timer, maybe a notification.

**Pull request merged**
