### PR TITLE
Boxstation: Adds More Decals to Arrivals and Hydroponics

### PR DESCRIPTION
**Pull request by Hanador**
Adds several hundred stupid little grey squares nobody can really see to Arrivals (plus the locker room there) and adds some green squares everybody CAN see to the entrance of hydroponics. Screenshots are a bit stupid looking because all the squares are being randomly generated probably due to April fools or something, But I assure you, they are **probably** all there and grey or green.

Arrivals
---
A
A2
A3
A4
A5
A6

Arrivals Lockers
----
AL
AL2

Hydroponics
-----
B1
B2

### CODE REVIEW

**Comment by Hanador** [comment]
No. They are all grey in arrivals, green in hydro with exception of their sinks which have grey squares. It seems to be happening on the server *Sybil+Bagil currently so I'm hoping it is just an April fools PR that has gone wrong.

**Comment by Farquaar** [comment]
Should probably grab some new screenshots now that April Fools is over.

**Comment by cacogen** [comment]
The randomised pastel tiles are a recent addition that appear for the holiday but will be off now. Makes me want to taste something that isn't strong but is pleasant

**Comment by Hanador** [comment]
When the April fools squares are gone I'll take new screenshots but for now I have no idea how to get rid of em as my git skills are limited.

**Comment by cacogen** [comment]
https://github.com/tgstation/tgstation/blob/4a4d1c801a3c5093bab1b14eb75462f817fc0064/code/game/objects/effects/decals/turfdecal/tilecoloring.dm#L7-L10

**Comment by Hanador** [comment]
Thanks.
Screenshots updated now. May look at removing that one green square under the firelock tomorrow or the day after. I'd add some green decals to the arrivals garden but I'll probably be changing that room up sometime in the next month. Also do keep in mind that these are neutral squares so they are a little hard to see. Areas that may look like they are missing squares actually have them like the 2nd arrivals screenshot just right of the firelock it actually does have two decals there.

**Comment by Hanador** [comment]
Ugh shit, my attempts at removing the green decal led to a merge conflict.
April Warehouse Hotel 2020-04-03 172324

**Comment by Hanador** [comment]
I really hope I didn't fuck anything up. I haven't tried to change any sprites or code. I tried rebasing so I wouldn't have to re-decal everything, don't know if I did it correctly or not god help me I just want to make box not shit.

**Comment by optimumtact** [comment]
your pr is completely busted, don't rebase in future, just merge.

**Comment by Hanador** [comment]
Alright thanks for letting me know orange man. Closing and re-doing this.

**Pull request closed without merging**
