### PR TITLE
Adds skub to the AutoDrobe as a premium item

### PR DESCRIPTION
**Pull request by bobdobbington**
Filthy anti-skub degenerates BTFO. This one adds skub as a premium item (costs a coin) to the AutoDrobe, because if you gave the clown skub at roundstart it broke the metagame. Merge token graciously donated by our citrus overlord.
:cl:
add: Added skub to the AutoDrobe as a premium item.
/:cl:

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
can you wear it

**Comment by coiax** [comment]
> merge tokens aren't transferable

except when they are

**Comment by bobdobbington** [comment]
Nope, it's Lzimann's old skub code and skub sprite, the only thing I did differently was put it in the vendor instead of in the clown inventory because roundstart skub proved to be too overpowered.

If it turns out oranges can't donate me a token I've got one of my own. Anti-skubbers pls go.

**Comment by optimumtact** [comment]
I allow this by fact of me being pro skub and a maintainer

**Comment by Core0verload** [comment]
Skub is just a shitty meme, and we have more than enough shitty memes in our codebase.

**Comment by optimumtact** [comment]
Anyone who actually is against this meme is literally not from /tg/ and should get a server github and forum ban.

**Comment by bgobandit** [comment]
I only removed skub from the cluwn to make room for the cluwn memeaphone

**Comment by Fox-McCloud** [comment]
Literally retarded.

**Comment by Firecage** [comment]
....Well, this is still a better retarded PR than when oranges adds shit for retarded people to say

**Comment by Zilenan91** [comment]
I like how skub being in the game or not literally resulted in the skub situation

**Comment by coiax** [comment]
image

**Comment by Fox-McCloud** [comment]
Oranges why!

**Comment by Nienhaus** [comment]
The sprite is pretty shit.

**Comment by optimumtact** [comment]
P R O S K U B

@Nienhaus well a nicer once could be nice :smile: 

source material http://pbfcomics.com/20/

**Comment by Nienhaus** [comment]
I made the original not knowing what it was. I don't want to make it again.

**Pull request merged**
