### PR TITLE
Fixes surveillance software

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Another good thing about making my stuff admin only is that it never works the first try

:cl: Kor
rscadd: Nuke ops can purchase sentience potions for 4tc
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
Never heard of "testing", have you? :P

**Comment by Iamgoofball** [comment]
what's testing?

**Comment by GunHog** [comment]
Oh, you just make sure the code compiles, you do not actually have to **run** the code and go through your changes to make sure they work or anything. So long as it passes Travis, you are good to go :)

**Comment by freerealestate** [comment]
Why make admin-only content in the first place? It's rarely used and encourages favouritism.

**Comment by MMMiracles** [comment]
@freerealestate content for admin events that'll make them worth-while to do, or potential loot for away missions so the loot variety is more than '30 variants of guns'.

**Comment by Anonmare** [comment]
@MMMiracles Yeah but why would you want to have fun variety in a videogame?

**Comment by freerealestate** [comment]
only a handful of people will get to experience the 'variety'

**Pull request merged**
