### PR TITLE
Adds newline to spiritual

### PR DESCRIPTION
**Pull request by 4dplanner**
## Changelog
:cl:
fix: spiritual moodlet description has a newline
/:cl:

### CODE REVIEW

**Review by SpaceManiac — APPROVED** [review]
lgtm but I really want to know why the newline is here and not where they're printed

**Comment by 4dplanner** [comment]
I dunno, could possibly do with a find + replace

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/25f18ff5232f6db4ec6806535eed4a98e11e984b/code/datums/components/mood.dm#L77-L79

because it sums the messages rather than to_chat's each individual one.

**Comment by SpaceManiac** [comment]
that should be changed to use .Join() instead of string concatenation, but this PR looks good in the meantime

**Pull request merged**
