### PR TITLE
Makes Moist Nugget a heavy weapon

### PR DESCRIPTION
**Pull request by AarontheIdiot**
## About The Pull Request
long gun needs 2 hands to shoot

## Why It's Good For The Game
immersion

## Changelog
:cl:
tweak: Mosin Nagant requires two hands now
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
It so big because extra range

**Comment by Krysonism** [comment]
Can the obrez still be fired with one hand?

**Comment by Learner10** [comment]
Since it's a rifle, would it be broken to give it a bit of a vision range enhancer? Something minimal like 1-3 spaces of extra vision range when you try to aim with it?

Also, I'm fine with it requiring 2 hands.

**Comment by HomocidlePancakes** [comment]
Muh new cops

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
