### PR TITLE
Revert "Resprites secborg to be blue (#66074)"

### PR DESCRIPTION
**Pull request by Fikou**
This reverts commit 115f4284b601b03d10a4d287ed85a4da1520a306.
## About The Pull Request
makes secborgs red again

## Why It's Good For The Game
the red menace is iconic. blue secborgs were added when we were actually trying to bring them back, but thats clearly not happening, i think we should keep them red to really strike fear when the admins spawn one

## Changelog
:cl:
imageadd: secborgs are red again
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
so true bestie

**Comment by IndieanaJones** [comment]
I still believe in the day where the secborgs come home.

**Comment by YakumoChen** [comment]
👍 it was a really ugly shade

**Comment by GuillaumePrata** [comment]
If not red, it should be white to keep parity with Peacekeeper as both *should* prioritize laws above sec duty.
The blue just make it look like Command borg which would just make it a valid hunter anyway...

**Comment by Mothblocks** [comment]
make it gags

**Comment by Pumpkinoe** [comment]
make it orange :3c

**Comment by optimumtact** [comment]
>I still believe in the day where the secborgs come home.

you believe in a future that does not exist

**Comment by Zytolg** [comment]
Secborgs are a mistake.

**Comment by Twaticus** [comment]
GAGS SECBORG GAGS SECBORG

**Comment by ShizCalev** [comment]
@Twaticus don't you fucking tempt me.

**Comment by ShizCalev** [comment]
cause i'll fucking do it.

**Pull request merged**
