### PR TITLE
Allows C4 on mobs again

### PR DESCRIPTION
**Pull request by silicons**
However, the explosive strength will be only ex_act(3) which is around 50% chance to knockout and like 50 damage.
:cl:
experimental: Donk Co. would like to report that it has stopped cutting cost on C4 adhesive material.. Bricks of C4 will now attach to living animals and people properly, however its explosion is predicted to be weakened by the high water content of living creatures.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
maybe still let it kill but not gib if youre going to nerf it like that

**Comment by PKPenguin321** [comment]
i mean it is a nerf considering it does 50 damage (basically nothing) rather than outright gibbing
i'm not saying it's unwarranted but it's a bit much

**Comment by PKPenguin321** [comment]
i suppose yeah it's better than nothing but if it's this useless it will hardly be used and it will be harder to convince people to buff it again in the future

**Comment by kevinz000** [comment]
@PKPenguin321 the problem is we have 3 explosive levels.
assuming you don't have bomb armor or you don't roll rng right:
1 is gib
2 is instant kill with no defib due to >190 damage and most of your things will be shredded.
3 is 50 damage and a good chance of knockout and deafens.
sorry m8.

**Comment by FantasticFwoosh** [comment]
At least allow the person to resist it off by making it a forced attachment onto their jump suit @kevinz000 so they have the opportunity to remove it or ask someone with wirecutters to defuse it akin to a electropack.

They'd have to stand around else with a timer, hopefully outrunning the set time on the C4 (which would need a minimum of like 30 seconds for a undisturbed resist time of 25/26/27/28/29 or therabouts) if they even happen to notice the beeping it makes.

**Comment by OmegaShoots** [comment]
>water
>dampening explosions

Looks like kevin needs to take some physics lessons.

**Comment by juanototo2** [comment]
Local catboy attempts to sneak parapen c4 back in in the wake of moths, more at 11

**Comment by kevinz000** [comment]
@OmegaShoots it's called "bullshitting".
it's something people sometimes use to justify balance when the physics behind it make no sense.

**Comment by PKPenguin321** [comment]
why not do a 50 damage explosion then manually add like 50 brute as well so it at least crits

**Pull request merged**
