### PR TITLE
Freon now simply uses a color matrix rather than blending an icon

### LINKED ISSUE #20245: Freon freezing turns shuttle airlocks into external airlocks
what the fuck goof, how the fuck did you do this
what
notice the light placement. that's a SHUTTLE airlock

### LINKED ISSUE #20314: Freon freezing only shows one tile of sprites larger than 32x32
Like #20284 but with freon's blending.

### LINKED ISSUE #24744: Frozen overlay doesn't work on objects that smooth, like tables
image

#fuckingfreon

### LINKED ISSUE #25874: Freon frozen things with animations are faster and desynced
A frozen airlock will open rapidly multiple times. A frozen security camera will be rotating constantly.

### PR DESCRIPTION
**Pull request by ChangelingRain**
This absolutely fixes: things animating weirdly/too fast while frozen, things showing up as other things while frozen, large objects like cyro pods being much smaller while frozen, things with overlays not appearing frozen properly.
Fixes #20245
Fixes #20314
Fixes #25874
Fixes #24744
This might fix: the server crashing at the same time freon is released, even though it's _definitely not_ freon that's doing it.

### CODE REVIEW

**Comment by kevinz000** [comment]
JOAN IS A HERO

**Comment by ChangelingRain** [comment]
I repeat; this _**definitely does not fix the server crashing while freon is released.**_
Lacks of crashes while freon is released are a _coincidence._

**Comment by DoctoreMad** [comment]
I disagree with the changes on principle as TGstation players are "happy on suffering" so to speak.

**Comment by MimicFaux** [comment]
I'm just picturing a Chaos vs Order battle in my head, with ClockCode on one side, and Goofcode on the other.

**Comment by XDTM** [comment]
I'd pit Goofcode against Cybercode and ClockCode against RobustinCode

**Comment by The-clown-known-as-Pepe** [comment]
no code can match 150 hours of testing

except RobustinCode

**Comment by Tokiko1** [comment]
Thank you!

**Comment by YakumoChen** [comment]
but when will Freon stop being a copyrighted name???

**Comment by Iamgoofball** [comment]
This is ugly looking and gross

**Comment by Iamgoofball** [comment]
This isn't even a fix, it's a fucking revert

**Comment by PraiseRatvar** [comment]
sharex_2017-08-07_00-46-08

**Comment by Iamgoofball** [comment]
Deleting something that has a bug isn't fixing a bug, it's deleting the feature.

**Pull request merged**
