### PR TITLE
Adds `ALLOW_RESTING` to a bunch of items

### LINKED ISSUE #82788: Alt-clicking your bag while floored opens floor contents instead
Reporting client version: 515.1636

## Round ID:
[227541](https://scrubby.melonmesa.com/round/227541)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [[READY] the unfuckening of clothing rendering](https://www.github.com/tgstation/tgstation/pull/79784)
- [Controller Overview UI](https://www.github.com/tgstation/tgstation/pull/82739)

## Reproduction:
1. Rest
2. Try alt-clicking your bag or any storage items inside your bag to open them
3. Floor contents menu opens instead
Works normally when not resting

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Allows you to alt-click a bunch of items while resting. 

Fixes #82788

## Why It's Good For The Game

Some of these, such as storage, are bugfixes. You shouldn't need to be standing up to configure a spray can, or change the direction of your bedsheet

Others are just sensible changes. 

## Changelog

:cl: Melbert
fix: You can open bags with alt click while resting again
qol: Many items which previously required you to stand to alt-click now don't, such as bedsheets and spray cans
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
does this include adjusting your suit?

**Comment by MrMelbert** [comment]
don't think so

**Comment by lessthnthree** [comment]
Does this apply to items that have TGUI windows as well?

**Comment by MrMelbert** [comment]
> Does this apply to items that have TGUI windows as well?

This flag is (currently) only used for alt click

**Review by jlsnow301 — APPROVED** [review]

**Pull request merged**
