### PR TITLE
Add onmob headset icons

### LINKED ISSUE #50899: List of headsets with missing sprites
Issue reported from  Round ID: [136312](https://scrubby.melonmesa.com/round/136312) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Reproduction: Search "obj/item/radio/headset" in the create object panel. Try them on and look for a white dot to the left of the character and pink dots that look like ear muffs.

/obj/item/radio/headset/headset_sec

/obj/item/radio/headset/headset_eng

/obj/item/radio/headset/headset_rob

/obj/item/radio/headset/headset_med

/obj/item/radio/headset/headset_sci

/obj/item/radio/headset/headset_medsci

/obj/item/radio/headset/headset_srvsec

/obj/item/radio/headset/headset_srvmed

/obj/item/radio/headset/headset_com

/obj/item/radio/headset/heads/captain

/obj/item/radio/headset/heads/rd

/obj/item/radio/headset/heads/hos

/obj/item/radio/headset/heads/ce

/obj/item/radio/headset/heads/cmo

/obj/item/radio/headset/heads/hop

/obj/item/radio/headset/headset_cargo/mining

/obj/item/radio/headset/headset_cargo

/obj/item/radio/headset/headset_srv

/obj/item/radio/headset/headset_cent/empty

/obj/item/radio/headset/headset_cent/commander

/obj/item/radio/headset/headset_cent

### PR DESCRIPTION
**Pull request by babydoll**
## About The Pull Request
Fixes #50899

Adds slapdash onmob headset icons for each missing state. These currently use the colours from each headset's inventory state, but could just as well be duplicates of the default headset if desired.

## Why It's Good For The Game
They don't look great but they look better than the blank state

## Changelog
:cl:
fix: Added missing headset mob display icons.
/:cl:

### CODE REVIEW

**Comment by babydoll** [comment]
Fixes #50899

**Comment by remove32** [comment]
as was discussed in coderbus, the item_state assigned to each headset doesn't seem to do anything. adding these icons is good but it seems to be unintended that both the item and the clothing overlay use the same variable for both states

**Comment by Qustinnus** [comment]
who said that? We've used icon_state as a default for item_state for aeons and I've never heard claims its unintended.

**Comment by remove32** [comment]
> 
> 
> who said that? We've used icon_state as a default for item_state for aeons and I've never heard claims its unintended.

I am making this claim right now because it seems like the item_state doesn't change anything regarding the sprite used. Granted I'm pretty new to digging around in the guts of the code but the only thing that actually changed the sprite on or off the mob was icon_state

**Comment by babydoll** [comment]
/tg/ system:
`icon_state` = inventory & onmob
`item_state` = inhands

elsewhere:
`icon_state` = onmob
`item_state` = inventory & inhands

i recommend implementing a `worn_state` variable because there are a lot of items that should be inheriting their parent's onmob icon (these headsets being a very good example) but it isn't doable when `icon_state`  is responsible for both onmob and inventory icons

**Comment by babydoll** [comment]
regarding the `item_state`s set in headsets.dmi, they're over 5 years old and are likely from before /tg/ switched over to unified `icon_state`

**Comment by remove32** [comment]
> 
> 
> /tg/ system:
> `icon_state` = inventory & onmob _(this is explicitly stated in the base `/item` definition and is obvious looking at the code)_
> `item_state` = inhands
> 

`item_state` for headset_eng is "headset" which is inherited from the parent. 
it doesn't change the inhand icon, otherwise it'd appear in this screenshot as a default headset. hence my comment regarding `item_state` being effectively useless
image

**Comment by optimumtact** [comment]
good advice

**Pull request merged**
