### PR TITLE
Removes the bitflag helpers

### PR DESCRIPTION
**Pull request by ninjanomnom**
These helpers just obscure functionality, making it harder for people who don't know the syntax to get used to them and harder for people who know the syntax to quickly scan past them when reading code. They're basically equivalent to
`#define ADD(x, y) (x + y)`
and should be treated like the regular operators they are instead of hidden away.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
since someone felt necessary to add these, can we change the portion in flags.dm to comments?

**Comment by ninjanomnom** [comment]
The someone you're looking for here is kevin, and why would we leave commented out code when it's in the history? There's no good reason to have these

**Comment by ExcessiveUseOfCobblestone** [comment]
someone merged it :P 

I'm thinking more along the lines of what each one does IE &= is a check for bitflags, not necessarily keeping the code. That's of course if we think the byond explanation isn't easy enough for coding newbies to pickup (I haven't checked the documentation for bits). In a perfect world people should be able to easily F1 in DM and lookup/understand the operators and their function.

**Comment by ExcessiveUseOfCobblestone** [comment]
nani

**Comment by ExcessiveUseOfCobblestone** [comment]
I tried to merge this but it looks funny on my non-personal computer so can someone double check it's working as intended @tgstation/commit-access

**Comment by optimumtact** [comment]
whatever you did, please never do it again

**Comment by ExcessiveUseOfCobblestone** [comment]
I pressed merge 🤔

**Pull request merged**
