### PR TITLE
removes skewium

### LINKED ISSUE #33431: Skewium glitching out and completely blinding consumer
Round #79931 on Sybil
I had been force-fed skewium, and aside from making my screen flip the fuck out, it completely blinded me after a short while. 

image

### LINKED ISSUE #36267: skewium doesn't move light glows

### LINKED ISSUE #37787: Skewium makes screen turn black after a while.
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:) [Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)
It was on my own server.
After use of skewium the screen turns black after some time of screen flipping out up and down (that flipping out part is expected but not the black screen part). After testing about 10 times it gave the same result 9/10 times. Screen just turns black but you can still *see things* at the bottom left where it says what your holding over.
skarmbild 50

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)
No testmerges
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Take about 40 units of skewium
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

### LINKED ISSUE #37923: Skewium locking up client, and my computer
I don't know if it's a graphics card thing but skewium fucked up my game client and even made my computer lock up, made the screen on the client black out with only flashes of game view, and then after it wore off it caused horrible slowdown for my client.

### LINKED ISSUE #42374: Skewium and Rotatium bug?
Issue reported from  Round ID: 100304 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I'm not sure which of the two caused it, but some guy fed me 50 u of skewium and 20u of rotatium and killed me while in-effect. The effect persisted even as a ghost and it hasn't gone away since, even affecting ghost UI

### PR DESCRIPTION
**Pull request by ghost**
It's been a year and no one has fixed the bugs
"it shouldn't be in teh game those fancy physical stuff never works at the client level tbh" -Oranges

One bug example (seizure warning): https://gyazo.com/267e4677badf9e27ed21e1b0646f8015
Closes #42374, Closes #37923, Closes #37787, Closes #36267, Closes #33431

If you don't want it removed, fix it yourself.

### CODE REVIEW

**Comment by necromanceranne** [comment]
I dread encountering this shit and I heavily warn people from using it simply because I think it's not functioning as intended and equates to crashing peoples clients deliberately if their computer can't, for whatever reason, handle the processing power. This can't be merged faster.

**Comment by ATH1909** [comment]
iMPrOve dON'T REmOvE

**Comment by 81Denton** [comment]
>iMPrOve dON'T REmOvE

Just PR a fix

**Comment by Shadowflame909** [comment]
I thought maintainers didn't give a damn about the tracker

@py01 checkmate those bugs technically don't exist and therefore don't count.

I think it does need a healthy replacement though.

As without the skewiums and rotatiums of the world, what the fuck does chemistry have? Heavily nerfed knock outs?

Bunch of instant kill mixes?

It's like the options are either 0 or 100. And you can't get that fair balance of "get the hell out of here but I don't want to kill you."

**Comment by Krysonism** [comment]
Rotatium worked last time i tried it, isn't skewium the only problematic one?

**Comment by MCterra10** [comment]
I agree, Rotatium doesn't seem to cause any issues that I'm aware of, perhaps we could get rid of Skewium and then maybe decrease the cycles it takes before Rotatium takes effect to balance it out. But I agree, Skewium is crazy and not worth having

**Comment by Moonman121** [comment]
No longer will I have to reboot my pc after a chemist decides to shoot me with a syringe of skewium

**Comment by AdamElTablawy** [comment]
rotatium doesn't cause issues, but skewium crashes, yeah

**Comment by ExcessiveUseOfCobblestone** [comment]
revert rotatium removal

**Review by 81Denton — APPROVED** [review]
If anyone wants Skewium back, feel free to PR it after fixing the aforementioned bugs.

**Pull request merged**
