### PR TITLE
Improves shuttle purchase formatting

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request

This PR bolds shuttle names, arranges them alphabetically and adds a red warning message to griff shuttles.

## Why It's Good For The Game
It's much easier to find the shuttle you want once the list is sorted and shuttle names are bolded. The red warning message is mostly for admins, since captains can't pretend that they didn't know that hi daniel is a griff shuttle. 

## Changelog
:cl: Denton
tweak: Shuttle names are now bolded and they've been arranged alphabetically. Dangerous shuttles now have a red warning message under their name.
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
For comparison

qefr24g34g334

**Comment by MrDoomBringer** [comment]
I feel like arranging by cost would be the better move here, as price is generally more important than name for shuttles

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Whatever they're being sorted by, it should be done right after `SSmapping.shuttle_templates` is populated rather than based on their order in the file.

**Comment by WJohn** [comment]
Maybe have something closer to what the syndicate PDA does, with tooltips describing the shuttle when you hover over them? Our shuttle options are getting hugely bloated and this is only going to get worse over time.

**Comment by 81Denton** [comment]
@SpaceManiac I agree, I'll look into it.
@WJohn That's definitely doable with TGUI, the uplink and cargo interfaces do something very similar. If I get around to it, I'd do it in a different PR though.

**Comment by improvedname** [comment]
>oh hi daniel unsafe shuttle

HUGBOX

**Comment by 81Denton** [comment]
I should get around to this on the weekend or so

**Comment by AnturK** [comment]
Bump

**Comment by 81Denton** [comment]
I'll reopen this once I have time for a refactor, the whole thing could use some polish. I can't give an ETA yet though

**Pull request closed without merging**
