### PR TITLE
Gives IAA its own preference

### LINKED ISSUE #38811: IAA doesn't have its own preference, instead it's included in the traitor preference.
IAA doesn't have its own preference, instead it's included in the traitor preference. This isn't technically a bug, but they're two seperate gamemodes and should have different preferences.

### PR DESCRIPTION
**Pull request by Amelia0010**
:cl: Nichlas0010
fix: IAA now has its own preference
/:cl:

IAA and traitor are two distinct preferences, would make sense for it to have its own.
fixes: #38811

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
lol that's still in the game?

**Comment by Bombpants** [comment]
I thought IAA was a job....

**Comment by AlexTheSysop42** [comment]
@ExcessiveUseOfCobblestone it's out of rotation and no one runs it

@bombpants it is on paradise and some other servers, but not here

**Comment by TheDreamweaver** [comment]
I'm not sure you actually fixed it. It seems like you just messed up the traitor preference, and added a preference for IA without actually implementing it in a way that it will actually do that.

**Review by ShizCalev — CHANGES_REQUESTED** [review]

**Pull request merged**
