### PR TITLE
Removes headslugs from gold pool

### PR DESCRIPTION
**Pull request by improvedname**
No it isn't free antag

### CODE REVIEW

**Comment by YogsMcree** [comment]
Isint free antag as it is. Admin problem.

**Comment by Kromgar** [comment]
It's really rare and doesn't make you an antag. It's a reward for hard work in xenobiology and can take over an hour to get it.

**Comment by AlexTheSysop42** [comment]
if people are self-antagging with it, ahelp it

**Comment by XDTM** [comment]
It's one of the rewards that take longer to get in the game, and it doesn't give antag by itself.

**Comment by improvedname** [comment]
All these comments are jokes because it aint rare at all and if somoene is gonna talk about how hard is to get rainbow slimes just use a magicarp lol

**Comment by XDTM** [comment]
remove magicarps duh

**Comment by improvedname** [comment]
Sorry but kor the game designer lead says magicarps are xenobio endgame

**Comment by XDTM** [comment]
it'd make more sense to remove actual gamebreaking magic than remove changelings tbh

**Comment by improvedname** [comment]
image

**Comment by improvedname** [comment]
https://github.com/tgstation/tgstation/pull/30883

**Comment by Kromgar** [comment]
Then remove rainbow slimes from magicarp. I didn't even know you could get rainbow slimes from magicarp

**Comment by improvedname** [comment]
I want to be fair lumiscents are already the best thing for xenobio headslugs is just pushing that t b h

**Comment by XDTM** [comment]
>I think most players would rather have rounds break down in entertaining ways rather than have us strive for perfect balance, especially when you are nearing the 40 minute mark
I mean, that's pro-changeling here

**Comment by improvedname** [comment]
xenobio lings only causes drama and mass confusion it should not be a element of the main play

Everyone hates changelings to the bone but lets give crew the ability to turn themselves into one

**Comment by Spaceinaba** [comment]
you clearly have no idea what you're doing since you think that xenobio changelings = antag

**Comment by improvedname** [comment]
thats how people act like lol

this is why we cant have fun things thus should be removed

**Comment by XDTM** [comment]
also how in the world would lings cause more chaos than a bolt of transformation magicarp

or any magicarp really

**Comment by improvedname** [comment]
because a magicarp is fucking obviously and if everyone is running around with changelings it just becomes a shitfest

**Comment by Spaceinaba** [comment]
this is why we cant have fun things he says as he removes fun things
really makes you think

**Comment by Kromgar** [comment]
THIS IS AN IC ISSUE FOR ADMINS

**Comment by Spaceinaba** [comment]
changelings arent even confusing for admins anyways since we get a nice little (xenobio changeling) marker next to them on the antag list last time I checked so

**Comment by uraniummeltdown** [comment]
go back to Bay

**Comment by improvedname** [comment]
go back to paradise

**Comment by Hatfish** [comment]
this reeks of i ded, please show me on the doll where the xenobio ling touched you

**Comment by improvedname** [comment]
image

**Comment by ChuckTheSheep** [comment]
How about a subtype that doesn't have any hostile stings? It would take away the temptation of being a shithead... mostly.

**Comment by 81Denton** [comment]
How about uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh you hit F1 instead

**Comment by KorPhaeron** [comment]
Willing to bet OP tried to kill a xenobio ling and it defended itself and that is what he is referring to as "acting like antag"

**Comment by Kromgar** [comment]
Idedplsremove

**Review by ShizCalev — APPROVED** [review]

**Comment by PKPenguin321** [comment]
Disgusting PR

**Comment by 81Denton** [comment]
i ded

**Comment by Potato-Masher** [comment]
i ded

**Comment by KorPhaeron** [comment]
Not popular

**Comment by KorPhaeron** [comment]
RnD has suffered enough

**Comment by kevinz000** [comment]
dumb fucking rabbit

**Pull request closed without merging**
