### PR TITLE
Removes some excessive fire alarms from Tram Medbay and other wall mount stuff

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

Tram's medbay was a headache to look at as a ghost on a high alert. There are too many alarms. Some fire door sections and rooms have multiple alarms within a very close space. I have taken the liberty to remove a couple of the offending alarms and move some to better places to space them out more evenly.

image

Orange Xs: Removed fire alarms
Orange lines: Moved fire alarms
Green lines/circles: Moved another wall mount. 

**Of importance is the medbay APC, it was moved from behind a console to the west side.** 

**Two fire extinguishers were removed from the surgery rooms.** They were excessive and shared wall space with too many other wall mounts.
One fire extinguisher was added to the hallway to give the empty wall space something to do.
Not pictured: I added a fire extinguisher to the CMO office, because I didn't see one.
Also not pictured, I moved a fire alarm in the morgue sharing the same space as a light switch. Blegh.
Added a fire alarm to the medbay sec post, because it didn't have one.

I removed the one med kiosk in surgery because I didn't want a fire alarm behind it. There's like, 3 or 4 in medbay already, you won't miss it.

## Why It's Good For The Game

Having a fire alarm next to every single set of doors is a bit excessive. Especially when you look at maps like box or meta where alarms in the hallways are limited to usually one (or even none) per fire door section. 

Opens some space up on the walls around medbay. Maybe remove a few fire extinguishers next?

## Changelog

:cl:
del: Tramstation's Medbay has had some budget cuts on their fire alarms.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
You should add some vents and scrubbers when you're here, those firelocked sections don't have any (i am pretty sure)

**Comment by YakumoChen** [comment]
I moved the northmost one back because it shared a wall with a light

> You should add some vents and scrubbers when you're here, those firelocked sections don't have any (i am pretty sure)

That seems almost intended so I'm not going to mess with it.

**Review by san7890 — CHANGES_REQUESTED** [review]
Few requests while you're in the area just to keep everything looking nice.

<details>
<summary>Click for Images</summary>

image

This wasn't you, but would you mind moving this fire alarm for virology to this tile? It's covering up the door bolt button.

image

The two fire alarms with red X's on their tiles are just placed a bit _too_ obtusely, I'd much rather  you find blanker tiles to place them on rather than be behind machinery/objects. There's some space, so feel free to shuffle. If you're unsure on where to find a new place to put them, the more "central" it is in relation to the fire alarms in its area might not be a bad rule of thumb to follow. I'll leave the new locations up to you so long as they're sorta "open" towards a hallway and not otherwise obscured, you might have to shuffle around some other items on the walls to accommodate if you are so inclined.

If you're not certain/need help on better locations, do let me know and I can help. I just want to leave this open-ended for you.
</details>

Thank you! Just hit "Mark Ready For Review" when the above changes are done.

**Comment by YakumoChen** [comment]
I have redone the PR @san7890

**Review by san7890 — CHANGES_REQUESTED** [review]
Few things you missed, unfortunately:

image

This APC needs to be wired into the grid.

image

Please delete these two excess wires.

Thanks for uncluttering a lot of the stuff, that's always appreciated in "busy" sections such as these.

**Comment by YakumoChen** [comment]
Fixed, thanks for the catch

**Pull request merged**
