### PR TITLE
Comms consoles now have a GPS signal.

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Does as title says.

## Why It's Good For The Game
Helps solve the issue of hidden comms consoles delaying (or forcing) a round end.

## Changelog
:cl:
balance: Communication Consoles now show up on GPS.
/:cl:

### CODE REVIEW

**Comment by trexter555** [comment]
how does this work for comms program on tablets?

**Comment by zxaber** [comment]
There isn't a comms console tablet app. The comms console was intentionally left separate from modular computers.

**Comment by ATH1909** [comment]
does this gps signal work like the gps signal for ai upload consoles, where screwdrivering the console (which takes longer than normal) to disable it also disables the gps signal?

**Comment by zxaber** [comment]
Yes, the GPS is gone when the console calls destroy (which it does when you deconstruct it).

I didn't make the screwdriver deconstruction step longer though. I'm not really sure if it's a big deal; the shuttle changes are announced and you can keep a GPS in your pocket if you're fighting someone back and forth over it.

**Pull request merged**
