### PR TITLE
Remaps delta's ordnance

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
Dawn of the final day, only kilo to go.

## Why It's Good For The Game
Refer to #65807 

Similar structure and design principles. Main difference is where i put the canister/scrubber/pumps in and the cool window glass :)

## Changelog
:cl:
expansion: Remaps delta's ordnance
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
please add a screenshot of the new ordnance to the pr body

**Comment by vincentiusvin** [comment]
Use the mapdiffbot

**Comment by JohnFulpWillard** [comment]
"Use mapdiffbot" mf's when mapdiffbot doesnt map diffs
image

**Comment by vincentiusvin** [comment]
skill issue, use the older commit






ok ill add it later this pr wont get merged soon anyway

**Comment by vincentiusvin** [comment]
here you go :)
image

**Review by san7890 — CHANGES_REQUESTED** [review]
Did a more comphrensive review this time.
<details>
<summary>Images Within</summary>

image

Prefer ORD MIX CHAMBER own that wall.

image

Interesting design choice to have a bypass into ordnance via the bathroom. If you wanna stick to that, add a heavy firelock here.

image

Would be better to put the firelock on this tile so it's more "accessible".

image

You need vacuum flooring under the vents, I presume (instead of space!). Also, I double-checked with Lemon and those directional windows _must_ be reinforced plasma window directionals to block superconduction. Please update that.

image

Scrubbers/Vents under machinery and objects are ugly and don't particularly work. Please move them to a more open space when possible.

image

Also, dead camera space here for no real reason. Just put a camera in this little cubby.

image

This error also came up during the testing, could you make sure it's working as intended? It did not error this way in the Tram PR.
</details>

All in all: an interesting new take on Delta's Ordnance department that does shake it up a bit while still being decently incorporated into the division. Just iron out the kinks, and we should be set.

**Review by san7890 — APPROVED** [review]

**Pull request merged**
