### PR TITLE
Adds my name to the file

### PR DESCRIPTION
**Pull request by DreamwalkerSisyphe**

### CODE REVIEW

**Comment by Shadowflame909** [comment]
>I would like to be able to use the test server, please and thank you

Inb4 the mere mention of dreamweaver in the files destroys all lines of code.

**Comment by TheDreamweaver** [comment]
I am Dreamweaver, Destroyer of Code

**Comment by optimumtact** [comment]
you're supposed to do this as part of other pr's

**Comment by TheDreamweaver** [comment]
@optimumtact Oh woops

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Fix the line endings

**Comment by ExcessiveUseOfCobblestone** [comment]
lol

**Comment by Cyberboss** [comment]
You're currently changing 134 lines, it should only be 1

**Comment by TheDreamweaver** [comment]
fuck it, I'll do it in the other pr

**Pull request closed without merging**
