### PR TITLE
Mouse Detective poster

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request
Adds a poster of a detective facing off against a wire eating menace.

mouse_detective
> "A poster advertising the escapades of Dick Gumshue, mouse detective. Encouraging crew to bring the might of justice down upon wire saboteurs."

## Why It's Good For The Game

Everyone wants the words "DICK GUM" emblazoned on the walls of their hobo crib.

## Changelog
:cl:
imageadd: New mouse detective poster.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
>mouse with long tongue plus the words dick gum

???

**Comment by Kurgis** [comment]
> mouse with long tongue plus the words dick gum
It was meant to be a wire.

**Comment by wesoda25** [comment]
I mean I get that but there’s just something very odd about it all

**Comment by spessbandit** [comment]
why does the detective have a mime mask

**Comment by Ryll-Ryll** [comment]
I'd watch this movie

**Comment by pireamaineach** [comment]
not funny didn't laugh

**Pull request merged**
