### PR TITLE
[s] If you know so much about good maps, why don't you make one yourself?

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
an extremely funny platform in the middle of space and the only two jobs are assistant and cyborg. gonna use this for something later.

## Why It's Good For The Game
it most definitely isn't

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Can you not

**Comment by Paxilmaniac** [comment]
This is a mystery tool that will help us later, ok?

**Comment by Paxilmaniac** [comment]
You're going to want to unsubscribe from this

**Comment by Paxilmaniac** [comment]
fine

**Comment by Paxilmaniac** [comment]
will this implode, let's find out

**Comment by optimumtact** [comment]
I am going to give you the worst CBT of all time

**Pull request closed without merging**
