### PR TITLE
Adds patriotic apparel for upcoming 4th of July (and inferior countries too I guess)

### PR DESCRIPTION
**Pull request by MMMiracles**
patriotism

Adds boxers, socks, and undershirt apparel due to the most god damn american holiday being just around the corner.

:fireworks: :us: :us: :us: :us: :us: :us: :us: :us: :us: :fireworks:

also adds some for inferior europoors and cyka bylats too I guess.

commie

europoor

canada

### CODE REVIEW

**Comment by optimumtact** [comment]
:-1: this is a Canadian game

**Comment by RemieRichards** [comment]
if this is happening then we need a British crown and sceptre too.
and a Prince Charles SNPC who always swiggity swooty's.

**Comment by optimumtact** [comment]
and a fair dinkum australian cork hat

**Comment by MrPerson** [comment]
This needs a hat. The most American of hats. It shall be Canada.

**Comment by Dorsisdwarf** [comment]
:-1: 

Everyone knows Nanotrasen is an indonesian company. What's their holiday?

**Comment by MMMiracles** [comment]
If europoors and cyka blyats feel left out I can probably throw together matching pairs for the UK and Soviet shirt.

**Comment by RemieRichards** [comment]
please do so

**Comment by PKPenguin321** [comment]
why would europoors, inferior countries, etc. have clothing dedicated to them? they're nowhere near as self indulgent and patriotic as the U S OF A :us: :us: :us:

**Comment by freerealestate** [comment]
I was going to comment that adding this doesn't seem to fair to the people
from the 20+ other countries that play this game, but then I realised
that'd be caring too much. It's just one set of clothes.

**Comment by Ricotez** [comment]
I was gonna say that americans are the only ones who would literally dress in their own flag but then I remembered that what the Dutch do is even worse



my eyes burn every time we're in a major sports competition

**Comment by Razharas** [comment]
I think american one needs some rainbow between the red stripes

**Comment by CosmicScientist** [comment]
Not enough Union Flag in the top left corner of the colony's flag.

**Comment by phil235** [comment]
We already have the freedom stuff vending machine. This isn't needed

**Comment by Ikarrus** [comment]
>talks about patriotism about countries that are not relevent in this game

>no NT shirt

**Comment by MMMiracles** [comment]
Considering the UK and commie shirt already existed I didn't think adding this would be too much of a stretch. The boxers and socks were also added to make them matching sets, so I think it works.

@Ikarrus theres a "i love NT" undershirt already ingame.

**Comment by Ikarrus** [comment]
@MMMiracles what where?

**Comment by MMMiracles** [comment]
@Ikarrus 
ilovent

**Comment by CosmicScientist** [comment]
There's also an undershirt with just NT on it I think? White letters on a dark blue undershirt?

**Comment by ike709** [comment]
:+1:

**Comment by daman997** [comment]
USA USA :+1:

**Comment by bustygoku** [comment]
AUSTRALIA OR RIOT

**Comment by xxalpha** [comment]
This shit again

**Comment by OhEmGee** [comment]
>no eu shirt
pig disgusting
sprite posthaste pls we need apparel bearing the star flag of our slowly deteriorating union ingame

**Comment by MMMiracles** [comment]
5 days and still no merge?

communist cyka bylats must be behind this. kavaloosh was right all along.

**Comment by optimumtact** [comment]
We'll merge it right after the 4th

**Comment by Incoming5643** [comment]
:clap: :clap: :clap: :hamburger: :clap: :clap: :clap:

**Comment by MMMiracles** [comment]
:us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us: :us:

**Comment by Iamgoofball** [comment]
usa-united-states-of-america-33748624-1333-1333
america
images
yl07zkigzezvrnxwvdun
bald_eagle_and_flag_united_states_america1
o-american-flag-gun-facebook
guns
chuck-norris-guns-flag
guns-in-america
gun-control-in-america-stack

custom-font-b-american-b-font-font-b-eagle-b-font-font-b-gun-b-font
fba9ee0bcb583fcea1477898d286e92c
fjmoq
american-eagle-logon-3
allen-west-american-eagle
images 1
tumblr_inline_nomdo31j571qzria2_500

**Comment by Chocobro** [comment]
https://www.youtube.com/watch?v=H-XxfHde7I8

**Pull request merged**
