### PR TITLE
adds walterje's genetics update

### PR DESCRIPTION
**Pull request by ghost**
genegenegenegenegene
genegenegenegene

Credit to https://tgstation13.org/phpBB/viewtopic.php?f=11&t=1659

Will get an ingame screenshot of them on the map in a moment

### CODE REVIEW

**Comment by ike709** [comment]
not sure how I feel about these until I see them on the map

**Comment by paprka** [comment]
clip 2015-01-20 at 03 08 22

**Comment by dannno** [comment]
Eh. They're good sprites but they do look out of place. The current ones look more in line with the consoles, etc.

**Comment by CollenN** [comment]
These sprites look kinda outdated and clunky. They don't really fit with the style of the rest of the game.

**Comment by ike709** [comment]
do not fit in

**Comment by Kromgar** [comment]
Uh what is that last one? with the blood and shit? Is that an emagged cloner? Either way the sprites look way out of place do not merge.

Pap posted it so it will get merged

**Comment by pudl** [comment]
literally fucking hideous

**Comment by Kromgar** [comment]
It looks like the fucking cloner is way too advanced for space station 13 with our anachronistic shit tech

**Comment by paprka** [comment]
guys

what if

we merged sprite improvements that looked out of place

then eventually the entire game would look better and they wouldn't look out of place anymore

???

no let's stick with 3 year old sprites you're right i love human sized computers fuck change

**Comment by pudl** [comment]
it's not an improvement, it's legitimate shit

**Comment by MMMiracles** [comment]
nice yeah but they really don't fit the style of everything else.

**Comment by AlexanderUlanH** [comment]
:-1: not even good sprites.  That half-perspective is going to annoy me every time I pass genetics.

Also our current aesthetic is fine.  The game doesn't need a new visual direction.  It wouldn't hurt, but it's not so needed that it's worth bringing in sprites that don't fit with anything in the hope that someone'll sometime sprite everything else that clashes with it to bring everything together.

**Comment by paprka** [comment]
It has to start somewhere.

**Comment by Kromgar** [comment]
Paprika you want change for the sake of change and its UTTERLY FUCKING ANNOYING

**Comment by Ricotez** [comment]
The sprites themselves look pretty good.

But they don't fit in at all - AT ALL - with the entire rest of the station. :-1: 

Also what's wrong with the old sprites?

**Comment by WJohn** [comment]
Really don't like these sprites at all. The giant orange tubes and the inconsistent perspectives (in the sprite, not in comparison to others) is annoying to look at. :-1:

**Comment by fingersticky** [comment]
If it isn't broke then what the heck are you doing, absolutely everything EXCEPT this is broke go fix something that isn't perfectly fine.

Enough is enough paprika. I'm going to start contributing ~~now~~ soon so my opinion actually matters.

**Comment by paprka** [comment]
EW INCONSISTENT PERSPECTIVES

EXCEPT THE OLD PODS AND TUBES HAVE IT TOO

ss 2015-01-20 at 04 53 52


LMAOOOOO

**Comment by Anonus** [comment]
WJ doesn't like it, so he can deny it because he's a sprite maintainer!
also :-1: to the sprites because I don't like them + all the other stuff mentioned

**Comment by WJohn** [comment]
Look I'm not gonna be that guy and use my position to pick and choose sprites as I see fit, that to me is an asshole. I personally just don't like the sprite for a bunch of reasons. Could I make a new one myself? I'm just saying that our current one looks totally fine and is fairly consistent with the blue steel machine sprites we have right now (which are by far the most common types of machine sprites).

**Comment by Razharas** [comment]
Id like the blue vertical strip to be a little darker and less teal

**Comment by RemieRichards** [comment]
Majorly: WJ has stated they do not like this change (WJ is an Art Director)
Else: Lots of people have declared distaste with this change (For reference, I don't like it either)

@Nienhaus get in here and share your opinion on this please.

**Comment by Nienhaus** [comment]
I don't see a point in changing the sprites.

**Comment by RemieRichards** [comment]
Well that's both Art Directors disagreeing with this change. Take that for what you will but I'm pretty sure this should be closed now.

**Pull request closed without merging**
