### PR TITLE
Nerfs Icepacks

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:tada:

### CODE REVIEW

**Comment by Durkel** [comment]
f

**Comment by Kraseo** [comment]
F

**Comment by TehZombehz** [comment]
f

**Comment by Kraseo** [comment]
F

**Comment by HankMoodyExperience** [comment]
security powercreep?

**Comment by chickenboy10** [comment]
You forgot the FUCK tag
f

**Comment by TechnoAlchemisto** [comment]
Hey guys you should all watch westworld!

The pilot episode is up for free on http://www.hbo.com/westworld !

Check it out!

**Comment by KorPhaeron** [comment]
wait I got a better PR

**Pull request closed without merging**
