### PR TITLE
reduces the amount of some of lavaland and icemoon gases

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
reduces bz and miasma amounts from lavaland atmos
reduces miasma amount from icemoon

## Why It's Good For The Game
No more cargo selling infinite amounts of bz/miasma

## Changelog
:cl:
tweak: lower amount of lavaland bz/miasma
tweak: lower amount of icemoon miasma
/:cl:

### CODE REVIEW

**Comment by spessbro** [comment]
I'd say keep the water vapor honestly but yes fartmining is very boring and annoying :+1:

**Comment by Tlaltecuhtli** [comment]
can you buff the ammount produced legit ways like corpses and corpse flower?

**Comment by Ghilker** [comment]
> can you buff the ammount produced legit ways like corpses and corpse flower?

that's out of the scope of this PR and honestly i'm reluctant to touch rot code since it has many issues with performances

**Comment by HibernianBones** [comment]
Just delete cargo

**Comment by Wallemations** [comment]
I see this having many problems with lavaland and icebox as a whole, as it will make the amount of times that air is breathable much higher, and while gas farms are OP at the moment, completely removing them seems like the wrong call. Imo, it would work better if you could find some way to mark if a canister went to lavaland in the code, and if it did, lower the price of the gas within. This is probably not that viable a solution, however it is far better than yet another removal.

**Comment by bluetshirtguy** [comment]
Can we please put cargo out of its misery already?

**Comment by Whoneedspacee** [comment]
please do not remove water vapor or plasma from ice moon, thanks.

if the issue with water vapor is that it doesnt make sense thats okay but its mostly an aesthetic thing and perhaps it should behave even more different at very low temperatures but I don’t believe it should be removed.

the slipping issue could be solved i believe by simply lowering the moles count of the water vapor.

plasma is very thematic to ice moon and definitely should not be removed, there are plasma lakes for a reason this is an easy place to gather plasma.

stinky gas can go though yeah.

**Comment by Ghilker** [comment]
water vapor will go from icemoon, along with miasma. I'll restore plasma tho

**Comment by LemonInTheDark** [comment]
Too sleepy to think about the balance concerns right now, can you elaborate on why you think this change is good for the game?

**Comment by Ghilker** [comment]
Arcane is trying to make economy matter more. This will remove a farm that is too easy to setup, that doesn't require much knowledge and that is able to make an infinite amount of money by just draining the air of those locations.
Miasma/Bz farming was always a balance concern, but nobody touched it since money weren't that important. Now with arconomy we are changing this and those farms are a worse balance concern.

**Comment by LemonInTheDark** [comment]
Gas farming mostly effects cargo, not econ, the two have been split up intentionally so we don't need to deal with cargo as much.
I personally hate miasma at 10 mols for aesthetic reasons, but having the air be more dangerous then just plasma is fine and good, maybe instead of removing them you tone down the amounts a good deal?

**Comment by Ghilker** [comment]
What a good amount would be? Between 0.1 and 1?

**Comment by LemonInTheDark** [comment]
yeah that sounds reasonable, maybe just slightly above 1 cause that's when gas starts to be visible? play around with it and see what makes sense

**Comment by Ghilker** [comment]
Aight

**Pull request merged**
