### PR TITLE
Null rods can dispel Nar'Sie summoning runes again

### LINKED ISSUE #54413: Nar'Sie Rune is Not Clearable With Null Rod
image

At the least even if this is somehow intended behaviour the fact it's logged as removal in admin logs is a bug then.
Kinda bummed out rushing into a cult summon and spamming the rune with a null rod only to have nothing happen I recall nar'sie rune being clearable in the past.
Other runes don't have this issue.

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

A bug that caused admins to be notified when someone tried to erase or dispel a Nar'Sie summoning rune, but wouldn't actually let the person trying to remove the rune successfully delete the rune (or unlock the special cult-themed shuttle) has been fixed.

Apocalypse runes now also notify admins when someone attempts to erase or dispel them, and removing them with a cult dagger takes just as long as removing a Nar'Sie rune with a cult dagger does.

You'll now hear that distinctive "shunk" noise (the same one that's played to you when you try to remove a normal (or apocalypse) rune) when you attempt to erase a Nar'Sie summoning rune with a cult dagger.

Attempting to erase any kind of rune with a cult dagger will now display a message to onlookers (and to you) in the chat box.

The cultist versions of the names of two admin/mapping-only runes have been correct so that they will no longer contain one more "rune" than they should.

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/54413.

## Changelog
:cl:
fix: A bug that caused admins to be notified when someone tried to erase or dispel a Nar'Sie summoning rune, but wouldn't actually let the person trying to remove the rune successfully delete the rune (or unlock the special cult-themed shuttle) has been fixed.
tweak: Apocalypse runes now also notify admins when someone attempts to erase or dispel them, and removing them with a cult dagger takes just as long as removing a Nar'Sie summoning rune with a cult dagger does.
fix: You'll now hear that distinctive "shunk" noise (the same one that's played to you when you try to remove a normal (or apocalypse) rune) when you attempt to erase a Nar'Sie summoning rune with a cult dagger.
add: Attempting to erase any kind of rune with a cult dagger will now display a message to onlookers (and to you) in the chat box.
fix: The cultist versions of the names of two admin/mapping-only runes have been corrected so that they will no longer contain one more "rune" than they should.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
ath. can you predict my next move

**Comment by Jared-Fogle** [comment]
image
ath please

**Comment by Jared-Fogle** [comment]
image
ath

**Comment by Jared-Fogle** [comment]
its the principle of the thing

**Comment by TheBonded** [comment]
@Jared-Fogle 
I feel like I'm missing something. why was this closed/who is ath?

**Comment by Jared-Fogle** [comment]
ath1909 the creator of this pr is banned from web editing

**Pull request closed without merging**
