### PR TITLE
SS14 Liquid Plasma Sprite

### PR DESCRIPTION
**Pull request by 13spacemen**
## About The Pull Request
Replaces the "liquid plasma" sprite with SS14's modified one by mirrorcult

## Why It's Good For The Game
The current liquid plasma sprite just looks like weirdly colored lava. SS14's one looks more like molten plasma

Before:
Screenshot 2024-01-02 200720

After:
Screenshot 2024-01-02 195947

## Changelog

:cl:
image: New liquid plasma sprites from SS14!
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I was kind of hoping from the description that it would stop being recoloured lava after the change

**Comment by timothymtorres** [comment]
I honestly can't tell any difference between the two.

**Comment by SomeoneYouProbablyKnow** [comment]
The difference is minor but at least it no longer looks like it's a z level below you when it's in front of you.

**Comment by Wallemations** [comment]
You just saturated the colored lava......

**Comment by EricZilla** [comment]
Its still better, to be fair

**Comment by Wallemations** [comment]
Fuck it

**Pull request merged**
