### PR TITLE
Cult messages will now always include the user's real name

### PR DESCRIPTION
**Pull request by ChangelingRain**
Also fixes the logging for clockcult rounds; that's not an escape objective really.

### CODE REVIEW

**Comment by Xhuis** [comment]
Why are __you__ making a _blood_ cult PR? What is wrong with you? Have you gone insane?

**Comment by Robustin** [comment]
Joan does blood cult stuff every month or so, little stuff. This was one of those long-standing "I think this should change but I don't know how" issues.

**Comment by Xhuis** [comment]
I know, I know. I was poking fun.

**Comment by ChangelingRain** [comment]
At some point I'm going to take robustin's changes and just do them myself because it'd be a lot faster and more reliable.

**Comment by Xhuis** [comment]
Can you just be robustin instead?

**Comment by ChangelingRain** [comment]
I can't be robustin but I can code for him

**Pull request merged**
