### PR TITLE
Updates the chronosuit helmet for a new look

### PR DESCRIPTION
**Pull request by tralezab**
:cl: lyman
imageadd: Updated the Chronosuit Helmet sprite.
/:cl:

It's an old sprite, the suit looks great but the helmet was really lacking. It also wasn't very tech-y and resembled a motorcycle helmet.

Here's the palette differences, 18 of the 24 colors were for the visor.
https://cdn.discordapp.com/attachments/473914925870350337/477001111966973962/unknown.png

https://cdn.discordapp.com/attachments/473914925870350337/477001190954106880/unknown.png

and here is the chrono agent facing all directions.
image
image
image

## All credit goes to my friend lyman, he's the one who sprited this. I just wrangled git into a pr.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
are those 2 white pixels on his head intended?

**Comment by tralezab** [comment]
If you take a look at icondiffbot, it's antennae. The stalk of it is grey, so it blends into the floor.

**Comment by JJRcop** [comment]
Could you make it a different grey, since that floor texture is extremely prevalent?

**Comment by tralezab** [comment]
alright here's a version with a different grey, that won't blend into the floor.

**Review by SpaceManiac — APPROVED** [review]
Looks good

**Pull request merged**
