### PR TITLE
Dreaming Improvements

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
tweak: Dreams are now more immersive and interesting.
/:cl:

Forms a 2-3 part dream composed of (adjective) subject, (adverb) verb, (adjective) object. Perfect grammar not guaranteed, but the results can be fun.

dream
What will Lavaland teach our brave miner?

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
just fucking add yog's old dream system already

**Comment by davethwave** [comment]
What's Yog's dream system?

**Comment by MoreRobustThanYou** [comment]
they used to have a system where dreams were an actual place where you could walk around in

**Comment by Iatots** [comment]
sleep VR sounds nice. Don't really know how it would work with 60 people on the server (where do you actually go?). Could add quite a bit of disorientation in the transit between wakefulness and sleep which would be nice for RP with some more polishing. Waking up with some minor hallucinations related to the dream could be quite fun, especially if you get knocked out cold during a fight and wake up in medbay beating the doctor,

**Comment by Bawhoppen** [comment]
Nah

**Comment by arsserpentarium** [comment]
Interesting idea is dream level. With possibility of constructing machines in dream world.
Possibly even construction of teleport and bluespace artillery.
Not realystic?not sure. Try to remember Carlos Castaneda.

**Comment by ShizCalev** [comment]
https://youtu.be/LCCiwPEdEpg

**Comment by Time-Green** [comment]
The dreams were removed from yogs because people wanted to be able to look around them, and *sigh*, I think the people here would send a hitman to make sure they can keep doing so

**Comment by optimumtact** [comment]
did you really reinvent my existing string system for building up strings at runtime?

**Comment by Bawhoppen** [comment]
I retract my nah to the dreamVR

**Pull request merged**
