### PR TITLE
Throwing a bee at someone injects reagents

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Throwing a bee at someone injects that bee's reagents.
This has a larger code footprint than you might expect because venom injection is done via an element which in turn gives a callback to a component.
While I was touching that I also separated `COMSIG_MOVABLE_IMPACT` into `COMSIG_MOVABLE_PRE_IMPACT` because a lot of effects trigger from `COMSIG_MOVABLE_IMPACT` despite the fact that the throw impact can be cancelled after the signal is sent.

I also added an inject check onto the venomous element for mob attacks, so thick clothing can now protect you from venom injection. 
I elected that Giant Spiders have big enough fangs to ignore this such that this isn't a major balance change, as do moonicorns (that horn is massive), Fire Sharks, and Clowns (no idea how they are applying chems at all to be honest).

## Why It's Good For The Game

I thought about someone throwing a bee at someone like a little dart and thought "hee hee"

## Changelog

:cl:
add: If you throw a bee at someone it will hit them sting-first and inject that bee's reagent
balance: Thick clothing can now protect you from the venom of bees, snakes, frogs, and (small) spiders
/:cl:

### CODE REVIEW

**Comment by xXPawnStarrXx** [comment]
🐝

**Review by Ghommie — CHANGES_REQUESTED** [review]
Nice, though they should check for thick clothing when thrown. These aren't piercing syringes.

**Comment by Jacquerel** [comment]
> Nice, though they should check for thick clothing when thrown. These aren't piercing syringes.

The venomous element in general does not do this, should it?

**Comment by necromanceranne** [comment]
> > Nice, though they should check for thick clothing when thrown. These aren't piercing syringes.
> 
> The venomous element in general does not do this, should it?

Lol, probably, are bees ignoring thick clothing rn?

**Comment by MrMelbert** [comment]
> Nice, though they should check for thick clothing when thrown.

In particular it should check `try_inject`

> Are bees ignoring thick clothing rn?

Probably only player controlled ones, unless bees do something on the bee side. Bees will ignore mobs with thick clothing outright.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
