### PR TITLE
[TM only] Roundstart Traitors will not have side objectives

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

By headmin request, they wanted to try out "what if we just didn't have traitor progression" in an attempt to validate or invalidate various views about antagonist gameplay that the admin team have but don't necessarily have firm agreement about.
We will not merge this PR. This is intended in an investigative fashion to see what, if any, player changes you might see if this incentive wasn't in the game.
Any actual change following this will depend on how it goes on servers.

This basically just removes the side objectives tab. Timelocks still exist, and removing those would be a separate discussion.

## Why It's Good For The Game

Plausibly, the FOMO pressure of having side objectives drives player behaviours in ways we don't like. It's unclear if we could establish this for or against in a short-term testmerge trial run, but might as well try.

## Changelog

:cl:
balance: Traitors cannot perform side objectives to fast-forward their progression and obtain additional telecrystals.
/:cl:

### CODE REVIEW

**Comment by Metekillot** [comment]
What are the goal gameplay styles that are being driven for, versus the ones that this change may or may not discourage?

**Comment by the-orange-cow** [comment]
Just food for thought, but if progression is eventually removed, certain items that have been added/adjusted with additional TC in mind may warrant being tinkered with.

**Comment by necromanceranne** [comment]
Less of a focus on a continuous loop of progression objectives until a prescribed conclusion, and ultimately more of a focus on self-determined objectives/main objectives

**Comment by Watermelon914** [comment]
this pr is not being merged unless someone can come up with a more compelling design reason to do so.

Players have the option to make their own objectives if they so choose, that's part of player agency in this sandbox.

If the crew are racing to defeat progression traitors, that doesn't sound right given the design of progtot and how data has generally shown that most final objectives are typically unlocked late into a round. I'd need to update myself on this data to see if it's still consistent, but about a year or so ago, the average time was usually around 90 minutes to 140 minutes into a round that final objectives unlocked, which is generally what we're going for.

Final objectives aren't a complete round-ender, they just create a new threat if the traitor chooses to pursue them, a more severe version of a heavy midround antagonist. This is creating new challenges for the crew to face and provides action to the round if the traitor actually manages to reach a final objective, and I don't see this as a negative for the game.

All in all, this PR is very likely not going to be merged without more substantial justifications.

**Comment by Metekillot** [comment]
I find that as an antagonist, I'm racing against the clock of bored heads of staff who want their next antag roll.

**Comment by Vect0r2** [comment]
I like secondary objectives but I have no objections to this being TMed for a few days because I am also curious about how this would go. I do not think that it's a good idea but I do not have a problem with seeing it's impacts.

**Comment by Watermelon914** [comment]
> I like secondary objectives but I have no objections to this being TMed for a few days because I am also curious about how this would go. I do not think that it's a good idea but I do not have a problem with seeing it's impacts.

you would likely see no significant impact since it's more or less just a straight nerf to traitor. The only argument really being made here is that there might be a psychological effect where you might not feel more pressured as a tot? I'm not entirely sure how truth to the fact this is or not because there hasn't been any data gathered about it and although it makes theoretical sense since there's more stuff to do, I don't think it's a net negative for players to have more agency and options.

**Comment by Loafin34** [comment]
i think this doesn't make sense. most traitors i see don't give a shit about side objectives unless it falls into their hands, because the equipment and stuff can easily be tracked back to them. Spy's entirely progtot, and there's no problem with them.

**Comment by necromanceranne** [comment]
Ill make an argument for why this is a good place to explore and analyze, since I believe any potential balance ramifications can be offset well enough with a few adjustments as needed (maybe to roundstart TC, it's been 20 for so long it might be interesting to shake that up in light of a lack of scaling).

Firstly, I think there is a degree to which players feel like the secondary objectives an obligatory track to follow. Or that they are the right thing to be doing at any moment as a tot because by design, they give the most immediate feedback on results. It is a constant reward system, and for players who are a bit less sure of what to do, this can be useful as a way to help keep them engaged in the role.

The problem with this is that I feel it detracts from innovation. It also doesn't really teach players to do much else with their role and growing TC pile that isn't this loop, since nothing else really has that immediate feedback. The final objective is a definite objective and has obvious feedback to the player upon having reached it compared to something more self-driven. Hence the feeling of more samey results in a given round.

Admins shouldn't feel obligated (and frankly, I don't think have any right to do so in any fair scenario) to tell players that following this pattern isn't acceptable when it is placed so obviously in front of them, and the game is encouraging them to follow that pattern. It is a problem with the design and not the player.

**Comment by Blacklist897** [comment]
excellent pr- traitor powercreep and constantly escalating rounds stem from side objectives

**Comment by EnterTheJake** [comment]
I have probably spent a thousand hours just playing progression traitor and actively engaging with the system.

 This is a terrible change trying to address a made up problem pushed by people who just do not play the game.

 Superset is currently busted for objectives so you'll have to take my work on this, but at least on Manuel there's an extremely niche amount of players that even bother engaging with the system, final objectives only pop after the 2 hours mark or during lowpop hours when there's no security.
 
 Going back to the progression system, most people have "Antag anxiety" and don't interact with it because it puts them at increased risk of getting caught.
 
 Finals do exactly what they were designed to do,end shifts that have dragged on for too long, Manuel already has lower threat than the other servers, nobody wants to see 3 hour long shifts with nothing happening.
 
 Now the system has a few issues, some easier to solve than others.
 
 1) There needs to be a more clearer tell for security what traitors are engaging with the system and what not.
 
 The existence of the progression system makes security less lenient towards traitors in general, as there's no tell which might come back to end the round.
 
 2) Most of the objectives kinda suck to be honest.
 
 - I don't feel like there is much to add here, kill pets, screwdriver crowbar a machine is not terribly engaging gameplay

**Comment by mc-oofert** [comment]
most of the traitor objectives are something that is exceptionally obvious to everyone around you and before you know it youre in a maint tunnel with 12 assistants being strapped to a chair forced to play mahjong lest you get banished

also good change i suppose given that i guess atleast traitors have to figure out what to do instead of speedrunning objectives minute 20

**Comment by SimplySmiley123** [comment]
> this pr is not being merged unless someone can come up with a more compelling design reason to do so.
> 
> Players have the option to make their own objectives if they so choose, that's part of player agency in this sandbox.
> 
> If the crew are racing to defeat progression traitors, that doesn't sound right given the design of progtot and how data has generally shown that most final objectives are typically unlocked late into a round. I'd need to update myself on this data to see if it's still consistent, but about a year or so ago, the average time was usually around 90 minutes to 140 minutes into a round that final objectives unlocked, which is generally what we're going for.
> 
> Final objectives aren't a complete round-ender, they just create a new threat if the traitor chooses to pursue them, a more severe version of a heavy midround antagonist. This is creating new challenges for the crew to face and provides action to the round if the traitor actually manages to reach a final objective, and I don't see this as a negative for the game.
> 
> All in all, this PR is very likely not going to be merged without more substantial justifications.

The traitor finals are something you have in your mind regardless of what your role and status are to be honest.
Mostly less because of the potential danger and more-so because it's a guaranteed round end on a common antagonist that's gonna show up in most rounds with several of these bastards all working separately (usually) to get their round end buttons.

**Comment by SimplySmiley123** [comment]
> most of the traitor objectives are something that is exceptionally obvious to everyone around you and before you know it youre in a maint tunnel with 12 assistants being strapped to a chair forced to play mahjong lest you get banished
> 
> also good change i suppose given that i guess atleast traitors have to figure out what to do instead of speedrunning objectives minute 20

To be honest most traitors just outright go loud because of that.
Either they dominate the station or die trying.

**Comment by SimplySmiley123** [comment]
> This is a terrible change trying to address a made up problem pushed by people who just do not play the game.
> 
> Superset is currently busted for objectives so you'll have to take my word on this, but at least on Manuel there's an extremely niche amount of players that even bother engaging with the system, final objectives only pop after the 2 hours mark or during lowpop hours when there's no security.
> 
> Going back to the progression system, most people have "Antag anxiety" and don't interact with it because it puts them at increased risk of getting caught.
> 
> Finals do exactly what they were designed to do,end shifts that have dragged on for too long, Manuel already has lower threat than the other servers, nobody wants to see 3 hour long shifts with nothing happening.
> 
> I agree with Melon that you are not going to receive any meaningful data by testing this pr, again, very few people even bother engaging with the system.
> 
> Now the system has a few issues, some easier to solve than others.
> 
> **There needs to be a more clearer tell for security what traitors are engaging with the system and what not.**
> 
> The existence of the progression system makes security less lenient towards traitors in general, as there's no tell which might come back to end the round.
> 
> **Most of the objectives kinda suck to be honest.**
> 
> I don't feel like there is much to add here, kill pets, screwdriver crowbar a machine is not terribly engaging gameplay

Manuel is honestly completely different from other 3 TG servers, much stricter on what antagonists get to do and what crew can do about them.

No restrictions? Welp have fun dealing with traitors immediately speedrunning their side objectives to get that gamer gear faster and either steamroll the station and dominate it, or die trying.

All for that sweet sweet round end button.

**Comment by EnterTheJake** [comment]
> Manuel is honestly completely different from other 3 TG servers, much stricter on what antagonists get to do and what crew can do about them.
> 
> No restrictions? Welp have fun dealing with traitors immediately speedrunning their side objectives to get that gamer gear faster and either steamroll the station and dominate it, or die trying.
> 
> All for that sweet sweet round end button.

I only play Manuel and this is essentially a non issue, final objectives pretty much belong on lrp with rounds with no security, and amount of gaming when security is active is going to lead to a premature death.

**Comment by LSommers** [comment]
The classic "I can fix a player/administration issue with a PR" PR.
How about rather than collective punishment, someone just bwoinks the supergamer speedrunners?
That way people who do a side obj to get TC for an actual antag gimmick don't have their ability to do shenanigans get hamstrung?

Nah, that'd be too easy.

**Comment by KingkumaArt** [comment]
> I don't feel like there is much to add here, kill pets, screwdriver crowbar a machine is not terribly engaging gameplay

this is my opinion as well. 3 of the 4 starter side objectives are just some variant on murder (calling card, heirloom, and pet kill) and the fourth, kidnap, is borderline suicidal if you dont have a radio jammer. I'd argue theyre often tougher to pull off than many of the primaries like highrisk theft. Some variety in secondaries would be nice, its why I rarely bother with them.

**Comment by TheSilverNuke** [comment]
How does this affect final objectives?

**Comment by Yobrocharlie** [comment]
> The classic "I can fix a player/administration issue with a PR" PR. How about rather than collective punishment, someone just bwoinks the supergamer speedrunners? That way people who do a side obj to get TC for an actual antag gimmick don't have their ability to do shenanigans get hamstrung?
> 
> Nah, that'd be too easy.

No only difference being this would actually probably would fix this issue though due to making traitors way more ignorable

**Comment by Lauwma** [comment]
Side objectives being removed won't bring more innovation or creativity in traitors. People that want to get innovative, get innovative, people that don't just do the basic stuff. If you don't want people to do the basic stuff then you may just bring the ambition system Skyrat had a few years ago but I'm 100% certain nobody wants that.

**Comment by TheSmallBlue** [comment]
Are you guys purposefully not reading the "We are not merging this PR" bit of the description? I sincerely cannot tell.

**Comment by necromanceranne** [comment]
> The classic "I can fix a player/administration issue with a PR" PR. How about rather than collective punishment, someone just bwoinks the supergamer speedrunners? That way people who do a side obj to get TC for an actual antag gimmick don't have their ability to do shenanigans get hamstrung?
> 
> Nah, that'd be too easy.

Thranos, you do realize that progtot exists to solve a player issue, right? That was the core reason we have it in the first place. To combat people who would go on murderbones the moment their antag status appeared on the screen.

**Comment by Watermelon914** [comment]
> > The classic "I can fix a player/administration issue with a PR" PR. How about rather than collective punishment, someone just bwoinks the supergamer speedrunners? That way people who do a side obj to get TC for an actual antag gimmick don't have their ability to do shenanigans get hamstrung?
> > Nah, that'd be too easy.
> 
> Thranos, you do realize that progtot exists to solve a player issue, right? That was the core reason we have it in the first place. To combat people who would go on murderbones the moment their antag status appeared on the screen.

That's what timelocks solved. Progression tot was implemented to give players to push through timelocks and to enable more gimmicks by allowing traitors access to more TC.

**Comment by MrStonedOne** [comment]
if anybody wants the data on tot objectives for the last 3 months

https://tgstation13.download/dip/discordimageproxy.php/attachments/326871815811235841/1267609722400542821/traitor_objective_feedback_3months_json.json

**Comment by kawaiinick** [comment]
i don't like traitors snowballing tc, but just leaving time gates is lame
> Are you guys purposefully not reading the "We are not merging this PR" bit of the description? I sincerely cannot tell.

all previous "tm only" prs in past months were merged with little to no changes, and i don't think this will be any different

**Comment by Watermelon914** [comment]
this is different

**Comment by Watermelon914** [comment]
also not sure what you mean
image

**Comment by kawaiinick** [comment]
i mean the changes that were done in beheading and shovestun prs were merged in separate prs later, and i doubt this one will be different

**Comment by necromanceranne** [comment]
But you can still shovestun, that specific part hasn't been removed.

**Comment by kawaiinick** [comment]
well okay true shovestun was removed from everything but telebaton and wallshove

**Comment by necromanceranne** [comment]
Well, if it means anything, my later changes were with several people approving and headcoder specifications and approval included (mothblocks) after I gathered a lot of feedback from the community and drew conclusions that seemed to convince them about the change, 

Where as this has a lot of maintainers and oranges fundamentally against it. I'm very sure there is no chance this is being merged without some fundamental changes taking place in our live servers policies first.

**Comment by mc-oofert** [comment]
> If you remove side objectives then remove reputation lock with it, otherwise this is a big no from me. The best solution is to leave the side objectives alone for reasons stated by others already.

no rep timelocks = medbay bombed 3 mins in

**Comment by TheSilverNuke** [comment]
> no rep timelocks = medbay bombed 3 mins in

But that's the fun part lol. Dumping the funds then bombing the crew who scramble to save it is the best.

Besides, people need to learn how to repair the station and make makeshift setups. They aren't knowledgeable enough a lot are too lazy.

**Comment by mc-oofert** [comment]
> > no rep timelocks = medbay bombed 3 mins in
> 
> But that's the fun part lol. Dumping the funds then bombing the crew who scramble to save it is the best.
> 
> Besides, people need to learn how to repair the station and make makeshift setups. They aren't knowledgeable enough a lot are too lazy.

yeah ok have fun rebuilding the entirety of medbay 3 minutes into the round because some schmuck instantly bought a bomb and destroyed med

**Comment by TheSilverNuke** [comment]
> yeah ok have fun rebuilding the entirety of medbay 3 minutes into the round because some schmuck instantly bought a bomb and destroyed med

I always do. I love construction projects.

**Comment by kawaiinick** [comment]
> We've gone from "all of them were merged without any changes" to "two of them were merged without any changes" to "one of them was merged and a different change was made as a result of the other one", I wonder where the goalposts are going to end up next.

i obviously didn't mean prs without player player facing changes

**Comment by mc-oofert** [comment]
> > yeah ok have fun rebuilding the entirety of medbay 3 minutes into the round because some schmuck instantly bought a bomb and destroyed med
> 
> I always do. I love construction projects.

youre not everyone though

**Comment by NullDagaf** [comment]
> > > yeah ok have fun rebuilding the entirety of medbay 3 minutes into the round because some schmuck instantly bought a bomb and destroyed med
> > 
> > 
> > I always do. I love construction projects.
> 
> youre not everyone though

I like it too.

**Comment by Shadowflame909** [comment]
> I find that as an antagonist, I'm racing against the clock of bored heads of staff who want their next antag roll.

This might be the true core conflict of all antags. Need more objectives that has (minor) crew rippling effects. Instead of very little interaction until a big boom occurs. Like pulling a scarecrow and drugging heads of staff with mindbreaker toxin.

If your actively engaging and being engaged with by the game, less reason for a boredom shuttle call.

**Comment by Watermelon914** [comment]
closing this PR because closed PRs can still be testmerged and even after a week, I don't intend to merge this in

**Comment by Redrover1760** [comment]
> This is a terrible change trying to address a made up problem pushed by people who just do not play the game.

Tbh I quit tg mostly because prog tots replaced old traitor.

**Pull request closed without merging**
