### PR TITLE
Makes magic projectiles get properly blocked by shielding

### LINKED ISSUE #14688: Reactive tele armor and magic
If you have telearmor and you dodge a magical bolt it still does its effects to you but you teleport away .. like if you get deathbolted your CORPSE teleports
Oh and telebatons bypasses it!
and handcuffs but it's probably a feature!

### PR DESCRIPTION
**Pull request by silicons**
Fixes #14688

### CODE REVIEW

**Comment by Incoming5643** [comment]
I'm pretty sure magic bolts being unblockable isn't a bug. Holding up a piece of plexiglass to block arcane bolts is pretty silly.

**Comment by kevinz000** [comment]
there's lots of things that are pretty silly.

**Comment by PKPenguin321** [comment]
""""""""""""""""""""""""fix""""""""""""""""""""""""

Freeze

**Comment by Robustin** [comment]
Kevinz using a fix to try and sneak in a reactive teleporter armor buff, you have no shame. :^)

**Comment by AnturK** [comment]
Yeah, no. The bug here is being teleported not other way around.

**Comment by Anonmare** [comment]
Make a bolt of teleportation teleport the shield out of your hand. A polymorph bolt changes it into a random, useless object. Bolt of death disintegrates it. Bolt of animation makes you drop and it come alive. Bolt of resurrection gets blocked normally. Bolt of door creation spawns a door on top of you and deletes the shield.

**Pull request closed without merging**
