### PR TITLE
Fixes Soul Vessel created borgs not having an antag hud

### PR DESCRIPTION
**Pull request by ChangelingRain**
HAND OF GODDAMNIT

### CODE REVIEW

**Comment by optimumtact** [comment]
So instead of actually figuring out the issue you're just going to paper over the crack?

I aint gonna merge it.

**Comment by ChangelingRain** [comment]
As far as I can tell, there IS no issue, which is clearly wrong.

**Comment by ChangelingRain** [comment]
I FOUND THE ISSUE AND FIXED IT PLEASE KILL ME

**Comment by optimumtact** [comment]
:+1: :heart: :hear_no_evil:

**Pull request merged**
