### PR TITLE
Randomizes Chemmaster Beaker Overlay Position

### PR DESCRIPTION
**Pull request by Cheridan**
so immersion

whoaaa

Also optimizes the icon editing with Cut(), which was the entire point of this.

### CODE REVIEW

**Comment by phil235** [comment]
:+1:

**Comment by pudl** [comment]
i don't like it

**Comment by paprka** [comment]
Thanks for the unique and detailed opinion once again quilty

:+1:

**Comment by pudl** [comment]
i just don't see why this is needed.

**Comment by paprka** [comment]
It's dynamic and interesting?

**Comment by pudl** [comment]
its neither

**Comment by Dorsisdwarf** [comment]
Wait is this the bit I never got around to doing in my PR?

**Comment by phil235** [comment]
It conflicts with carn's PR, can't merge it yet.

**Comment by GunHog** [comment]
Neato :+1:

**Comment by optimumtact** [comment]
Ship it @hornygranny

**Pull request merged**
