### PR TITLE
Gives the Revolvers on the Nuke Ops uplink Syndicate Firing Pins

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

gives revolvers on the nukie uplink syndie firing pins

## Why It's Good For The Game

Every other firearm on the nukie uplink has a syndie firing pin.

## Changelog
:cl:
fix: The Syndicate Revolver now has a Syndicate Firing Pin on the Nuke Ops uplink.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
um wrong. the ansem pistol they start with does not

**Comment by Yobrocharlie** [comment]
Boo, I vote no.

**Comment by F-e-r-n** [comment]
> um wrong. the ansem pistol they start with does not

then it should also be changed, taking an already weak syndicate weapon and refusing to give it a benefit every other weapon gets is kinda shitty, especially when its unintended.

**Comment by starrm4nn** [comment]
WHY

**Pull request merged**
