### PR TITLE
Revert "Ports dakimakuras from HippieStation."

### PR DESCRIPTION
**Pull request by lzimann**
Reverts tgstation/tgstation#27167

### CODE REVIEW

**Comment by Militaires** [comment]
WHAT  A GOOD PR.

**Comment by Militaires** [comment]
wtf i love lzi now

**Comment by Cyberboss** [comment]
@KorPhaeron @Cheridan WHERE IS THE ACCOUNTABILITY REEE

**Comment by MMMiracles** [comment]
closes the PR, reopens it, merges it, then proceeds to merge the revert PR shortly after

wot

**Pull request merged**
