### PR TITLE
Adds explorer gas mask for lavaland miners

### PR DESCRIPTION
**Pull request by Core0verload**
This PR adds a new gas mask unique to mining SSUs. It's recolored to fit mining suit theme.
gasmask gasmask_up
This mask's mouthpiece can be adjusted, exposing your mouth. It allows miners to eat goliath steaks without playing inventory tetris with gas mask.

This PR depends on #18427 getting merged.

**Merge Token:** #18392

### CODE REVIEW

**Comment by xxalpha** [comment]
Why did you use a commit from another PR?

**Comment by Core0verload** [comment]
Because this commit rearranges mining equipment files, and this PR changes one of those files. I'm trying to avoid self-conflicts that way.

**Comment by Core0verload** [comment]
I added merge token. Also, do unreported issues count for tokens? Or I had to report them before fixing?

**Comment by PKPenguin321** [comment]
i wouldn't mind this being added to regular gasmasks honestly

**Pull request merged**
