### PR TITLE
RAD/EMP/Bomb Hardsuit messages

### PR DESCRIPTION
**Pull request by GunHog**
#### All hardsuits
- Hardsuits now provide a warning message for radiation and EMP events.
- Radiation messages provide the intensity of the radiation pulse.
- EMP messages indicate if the pulse is light or strong.
#### Prototype hardsuit
- Displays the size of nearby explosions. It is a simpler message than what the full doppler array provides, limited to 21 tile range instead of 100.

All messages are visual, and display on the suit's electronic visor. They show a neat little icon when you are wearing the helmet to signify that the helmet is the source of the message.

image

### CODE REVIEW

**Comment by WJohn** [comment]
Noticing a spelling error with the rad warning: Magnitide should be magnitude.

**Comment by GunHog** [comment]
Thanks, I will catch it on my next commit.

**Comment by Alek2ander** [comment]
Yet another reason to never take it off

**Comment by Steelpoint** [comment]
Its a nice change that's not game breaking information.

All it will do is give you more accurate information on Radiation exposure for 99% of people who use hardsuits.

EMP attacks are so rare that its hardly noticable, and the RD's suit is only going to be noticed by one guy and odds are the bomb is going to be a max cap at his feet.

How exactly would knowing the exact damage a bomb does be a deal breaker?

**Comment by PKPenguin321** [comment]
"dont worry guys the RD hardsuit will just be a space-worthy glorified bombsuit nothing more"

**Comment by Razharas** [comment]
@GunHog 
Tell when its ready

**Comment by GunHog** [comment]
It is ready now, unless someone has a suggested change, @Razharas

**Pull request merged**
