### PR TITLE
shadowshroom nerf reverted

### PR DESCRIPTION
**Pull request by ghost**
so yeah they're basically useless now...

### CODE REVIEW

**Comment by Buggy123** [comment]
:+1:

**Comment by DaxDupont** [comment]
Please don't put it back to old values, the grief was immense

**Comment by Buggy123** [comment]
Do you see that picture? It literally does nothing ATM.

**Comment by Armhulen** [comment]
@daxdupont
That was because of a generation bug causing them to grow forever, fixed. Also people couldn't interact around them and now we have a fix for that too

**Comment by DaxDupont** [comment]
@buggy123 did I say not to buff them? I clearly said not to return to previous values which was over the top. Read pls.
@Armhulen if that's the case sure, let's try and see if it goes to shit or not

**Comment by Buggy123** [comment]
It was buffed by a factor of about 4. Looking at that picture, I wouldn't even expect a 4x buff to be enough. I guess there must be some wonky nonlinear shit going on with negative lights and the lighting code in general.

**Comment by DaxDupont** [comment]
@Buggy123 that picture is the nerfed state
The new values are the exact old ones before the nerf. Though @Armhulen is claiming that they wont spread as a bad, which would make it less horrible.

**Comment by Cyberboss** [comment]
Take pictures of .2 and .1 please

**Comment by Armhulen** [comment]
Ok fine yea

**Comment by Armhulen** [comment]
@DaxDupont remember when glowshrooms would be every fuckin' where and it was pretty awful because it creeped into every department and into maint?

that could be achieved off of one generation of glowshroom because they would never stop making new generations and since shadowshrooms are a child of glowshrooms it did it for that too

**Comment by DaxDupont** [comment]
@Armhulen if that's the case I don't mind!

**Comment by PKPenguin321** [comment]
wait these are still in the game?

**Comment by lzimann** [comment]
are you sure you just didnt have toggle darkness in this pic

**Comment by Armhulen** [comment]
i don't know, i just remember being really pissed at this image when i took it after the nerf and i found it again while browsing

**Comment by Armhulen** [comment]
even if it was, you can see in the nerf pr at max potency they just make everything purple. it's pretty sad

**Comment by kevinz000** [comment]
lmao the one time i will support a botany buff

**Comment by lzimann** [comment]
You really should check and take proper pictures without any toggle darkness on and value comparisons like cyberboss asked.

**Comment by FantasticFwoosh** [comment]
We should remove the plant until someone can mutually decide how to re-implement it as a entire rework is actually needed.

Im fond of the effect but its a small-minded attempt to keep fighting over the light level/greifyness unless you actually have a plan to implement it in a smart way. It has no important reagents either or outstanding traits beyond its gimmick.

- Summary changes can be as easy as lowering the light level by 1-2-3-4 to respective (20) of potency as to say it sucks in surrounding light to emit a dull glow. Without obscuring yourself with contrasting shining 'bright-dark' effects so you can cut through the darkness with a torch though they will be less effective depending on the shroom's potency.

**Comment by praisenarsie** [comment]
@FantasticFwoosh a wise man once said:
firefox_2018-01-06_00-44-07

**Comment by Armhulen** [comment]
don't reply to him maybe he'll go awau

**Comment by Cyberboss** [comment]
You gonna do it or what boi?

**Comment by Armhulen** [comment]
imagines very soon

**Comment by Armhulen** [comment]
image
30 potency (base)

**Comment by Armhulen** [comment]
image
75 potency (i looked at a child so 74 on that)

i guess if you squint you can kinda pretend it's dark

**Comment by Armhulen** [comment]
image
just to show you i'm not bullshitting it's PRODUCING some level of light

**Comment by Armhulen** [comment]
see the purple on the side

**Comment by Armhulen** [comment]
image
update from 30 potency, yeah uh

**Comment by Armhulen** [comment]
image
100 potency sorry it's growing pretty slowly

**Comment by Armhulen** [comment]
image
just showing

**Pull request merged**
