### PR TITLE
No more low pop nuclear emergency

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
http://www.ss13.eu/tgdb/latest_stats.html#mode_nuclear_emergency

They have a 78% winrate below 30 people. Complete waste of time when it's ~15 civillians vs 5 agents and a couple syndicate cyborgs. Nuke shouldn't happen without a healthy population (that hopefully includes security, and, you know, a captain).

### CODE REVIEW

**Comment by optimumtact** [comment]
http://www.ss13.eu/tgdb/tg/stats_2015-09-04_to_2015-10-04.html#mode_nuclear_emergency

for the correct stats

**Comment by Steelpoint** [comment]
This or scale Op population below 30 people to only have 2 or 3 Ops.

**Comment by swankcookie** [comment]
I think that's probably a better idea

**Comment by MrStonedOne** [comment]
The stats page @optimumtact linked is out of date.

Protip oranges: the pages listed are not in the order you think, its in the order of generation date, but you can have it generate for any given date.

**Comment by optimumtact** [comment]
http://www.ss13.eu/tgdb/tg/stats_2015-10-29_to_2015-11-28.html seems to be the most recent data.

**Comment by Incoming5643** [comment]
yeah, using the latest numbers kind of bucks the trend. There WERE balance changes to Nuke Ops since, specifically how to some degree the number of TC scales to station population.

**Comment by Steelpoint** [comment]
Either way while I don't mind this I would prefer if we tried to scale low pop Nuke Rounds instead of just removing the chance altogether.

Low pop already suffers from a lack of interesting game modes and I think removing this game mode from low pop should be a last resort.

Also look into boosting Op populations on high pop, as their win rate on High pop is even worse (inverse) to their low pop.

Essentially, lower Op population to two to three people on sub-30 people, and boost their numbers to around six to seven on post-40 to 50 people.

**Comment by KorPhaeron** [comment]
Having 2 guys assassinate the captain, or worse, just emag into an empty bridge at half an hour, then the round suddenly ending, wouldnt be interesting either.

**Comment by Incoming5643** [comment]
job selection does what it can to assure even a low pop station isn't completely headless, in theory as long as anyone has any head set to at least low at least one head will be present.

Issue here is that unless the head that spawns is the captain or HoP (or maybe occasionally the HoS) they probably won't take the initiative to secure the disk.

**Comment by Cheridan** [comment]
If this is a problem still it's something that can be addressed with more aggressive TC scaling. A very low pop station might be up against 5 ops with nothing but bowie knives. Very high pops are also a problem, though less than it was in the old days, they should probably get better scaling on the high end.

**Comment by KorPhaeron** [comment]
@Cheridan 

They get 60 brute automatic shotguns with 8 round drums for free now, TC scaling is dead

**Comment by Steelpoint** [comment]
Again, Op population scaling.

Have it be a minimum of three Operatives at low pop.

**Comment by Cheridan** [comment]
@KorPhaeron Well yeah, so make them not get those

**Comment by Dorsisdwarf** [comment]
I tried to nerf the shotguns a while back but the PR died

as official(tm) nuke ops balance master, take the Bulldogs away

**Comment by Robustin** [comment]
Yea there are very few rounds where even 2-3 ops in lowpop would produce a fair conflict.

Syndieborg is always going to be an issue too.

**Comment by swankcookie** [comment]
Secborgs in general need to be rethought.

**Comment by optimumtact** [comment]
I don't see why people are opposed to this? it will basically never be an issue on sybil.

**Comment by Incoming5643** [comment]
restricting more rounds from midpop means that low/no pop servers will have an even higher wall to scale in escaping traitor/ling hell

**Comment by optimumtact** [comment]
I think we can rely on the downstream being able to configure roundtypes, perhaps Kor should focus instead on making these limits configurable by the gamemode.txt if they are not already.

**Comment by Zilenan91** [comment]
Op rounds are particularly bad late night. Good change.

**Comment by KorPhaeron** [comment]
should probably just redo all this as a config yeah

**Comment by KorPhaeron** [comment]
wait shit merge conflicts

**Comment by Steelpoint** [comment]
Honestly low pop Ops should just spawn one guy in a alt base with a mini shuttle.

Otherwise removing low pop Ops is still a good thing.

**Comment by KorPhaeron** [comment]
Lone ops is still dumb because its extended for 40 minutes until he sets off a bomb and the round has a jarring halt

**Comment by Steelpoint** [comment]
You should open this PR ASAP. Low pop Ops is boring and horribly one sided.

**Pull request closed without merging**
