### PR TITLE
Updates small xeno queen sprite

### PR DESCRIPTION
**Pull request by Spess-Rando**
xenoqueen 4x

:cl: Sligneris
imageadd: Updated sprites for the small xeno queen mode
/:cl:

### CODE REVIEW

**Comment by dannno** [comment]
what changed
show comparative

**Comment by Sligneris** [comment]
xenoqueen_old 4x

**Comment by Kromgar** [comment]
Does Wjohn know your stealign his waifu?

**Comment by Sligneris** [comment]
He said he's not maintaining 1x1 queen sprites, so I decided to take matters in my own hands.

**Comment by KingPhilipIII** [comment]
Isn't the Queen usually bogged down with a massive ass eggsac that keeps it from moving at all unless it physically severs itself?

**Comment by Sligneris** [comment]
Have you never seen the queen in-game or something?

**Comment by Sligneris** [comment]
xenoqueen_comparison2

**Comment by WJohn** [comment]
Neat. Though I personally still am not in support of the 1x1 xeno sprite, I suppose I'll have no excuse not to do so now. I thought perhaps it'd be best if it made use of the praetorian sprite, which, while bigger than 1x1, is still perfectly usable in combat and is significantly bigger than all the other xenos.

**Pull request merged**
