### PR TITLE
Edits Syndiebase to fix TC station floors.

### PR DESCRIPTION
**Pull request by kittymaster0**
Why remove the TC station but not fix the floor????
I also moved the nukie spawn to around the table so they are not just sitting on stools in the middle of the floor. Also added a bar behind the leader table because it was barren and I had no better idea.

image
vs
image

## Changelog
:cl:
tweak: Cleaned up Syndiebase after TC station removal.
/:cl:

### CODE REVIEW

**Comment by AnturK** [comment]
Could probably revamp it a bit to use freed up space.

**Comment by kittymaster0** [comment]
> Could probably revamp it a bit to use freed up space.

Yeah there is a lot of empty space on the right side, there's not much to really put there. Could perhaps move the table over a few spaces so it's in the middle. But other than that i'm beat for ideas.

**Comment by kittymaster0** [comment]
Bruh It failed travis. I touched nothing else.

**Comment by Tlaltecuhtli** [comment]
bruh did u use the map merger

**Comment by kittymaster0** [comment]
bruh wtf is that

**Comment by MrDoomBringer** [comment]
@kittymaster0 haha bruuuuh https://github.com/tgstation/tgstation/wiki/Mapping

**Comment by kittymaster0** [comment]
wiki is down, i'm gonna just uhhh, idk, figure it out

**Comment by Tlaltecuhtli** [comment]
tgstation\tools\mapmerge2 in ur folder, i dont remember which .exe does the the work just press them all until you get one which asks a number

**Pull request closed without merging**
