### PR TITLE
Adds two saferChems for vent clogs.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Dax Dupont
balance: More chemicals can be found when vents get clogged.
/:cl:

[why]: Since a PR removed one of them because the chem is broken instead of fixing the chem, I've added two replacements.

### CODE REVIEW

**Comment by XDTM** [comment]
The bluespace reagent's id might be bluespace_dust instead of bluespace

**Comment by DaxDupont** [comment]
@XDTM 
yjop9ii 1

**Comment by evsey9** [comment]
I hope Initropidril is one of them

**Comment by 81Denton** [comment]
Haha oops the fucking vent foam teleports you into space

https://github.com/tgstation/tgstation/blob/3553c12d0bfa4ce2eb75fd2dd0b2d410c167521c/code/modules/reagents/chemistry/reagents/other_reagents.dm#L953-L964

**Comment by SpaceManiac** [comment]
Being randomly spaced is not exactly safe.

**Comment by DaxDupont** [comment]
It's not SAFE chems.
It's SAFER.
Morphine will OD you as well, bluespess just teleports you around, unless you're near space it's fine.

**Comment by DaxDupont** [comment]
This is an extremely rare event in the first place. Besides the intent behind it is deffo not being completely safe, but better than always being a random reagents.

Remember, I am the one that brought it back and unfucked it.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
