### PR TITLE
Overides old sechailer sounds for NO REASON

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
add: INCOMING WAS BREAKING THE LAW
soundadd: Sechailer has new audio clips!
/:cl:

closes #22172 

YOU HAVE THE RIGHT TO SHUT THE FUCK UP.

### CODE REVIEW

**Comment by dannno** [comment]
can you make one for the sechailer emag pr

**Comment by PKPenguin321** [comment]
Learn to enunciate

**Comment by PKPenguin321** [comment]
And also be louder

**Comment by Supermichael777** [comment]
sadly my stammering hits at about word six.

this was done with tts because its near impossibly to do that with one take.

**Comment by dannno** [comment]
can you make one for the sechailer emag pr

**Comment by TechnoAlchemisto** [comment]
Fucking narc

**Comment by Supermichael777** [comment]
@dannno i said no because i cant say tha- -out stamer- ing it to fuck

**Comment by Incoming5643** [comment]
Please don't point out in the changelog that we were breaking the law.

**Comment by Firecage** [comment]
Well, I have to say. They do sound like retarded manchildren speaking.

**Pull request merged**
