### PR TITLE
Adds shoulder holster for the detective

### PR DESCRIPTION
**Pull request by ghost**
Now you don't have to stick your gun in your pants

ss 2015-01-17 at 05 10 23
ss 2015-01-17 at 05 08 15

It's a belt slot item because tie code is crap

Sprites mostly ported from bay

### CODE REVIEW

**Comment by TZK13** [comment]
>Using the grey detective suit with tie and waistcoat look for example pic.

:^)

But yeah this is pretty cool, why not have it be able to hold all revolvers and other handguns though considering it can hold both a detective's revolver and a syndie pistol? I'd also understand wanting to keep it exclusive but I could see this being a neat thing for the biogenerator as well if the list of guns it can hold was expanded.

**Comment by paprka** [comment]
You know i love you thurg

**Comment by Fox-McCloud** [comment]
Bay uses these as ties that function as a container that can only hold weapons of a certain type.

They also have webbing vests that can hold small items---the only problem with vests is they promotes slot hyper-efficiency for anyone that has access to them...end result is security officers end up carrying around something like 10 flashbangs, their armor, and multiple weapons and still have space to spare.

**Comment by paprka** [comment]
I don't care what bay uses

**Comment by AlexanderUlanH** [comment]
>salty

It's a friendly suggestion.  This is a place where people discuss features.
Anyway, I realize it would suck to not be able to use with armor, but this would really make more sense as an exosuit slot item than a belt.  Especially since the stylish pictures you've got there don't have any.

It would also make sense if this were added to the biogenerator, assuming it gets expanded to hold some other guns.

**Comment by pudl** [comment]
i think the idea is stupid, but it's not hurting anyone to add and variation is fun :+1:

**Comment by paprka** [comment]
the detective is meant to wear it under his coat and i don't want to nerf him

it's just a fluff way for him to not wear his gun on his belt/suit storage slot

**Comment by pudl** [comment]
well he wears it on his suit slot, which means he wears it probably in a pocket in his coat? this is a buff tbh

**Comment by paprka** [comment]
you can wear it on either your suit or your belt slot, so it really doesn't change much

**Comment by ike709** [comment]
I wuv u pap :+1:  x :100:

**Comment by paprka** [comment]
prease merg

**Pull request merged**
