### PR TITLE
Demotes Psyker Pirates to Bounty Hunter Duty

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

This PR demotes the Psyker-gang from a pirate team to a fugitive hunting team. For more information on Psyker pirates, please refer to #71650.

Stuff this also does in the process:
- Gives fugitive hunters their own subfolder in the fugitives antagonist folder, moves some of their stuff into hunter-specific files rather than interlacing it with the rest of the fugitive code.
- Moves the hunter backstories to defines, to make reading things easier while I made this change.
- Exhaustively moves everything related to psykers from being pirate-oriented to hunter-oriented (typepaths, locations where stuff is defined, etc. There should be nothing left behind related to psykers in anything pirate related). (Tell me if I missed anything somehow).

They still get their ship (they even get their own custom psyker-friendly prisoner capsule). They still have a bunch of lethally chambered firearms. They're the same gunrunning nutcases they were before, just as bounty hunters.

To assist with basic tasks such as "getting to the station" or "figuring out who the fuck we're supposed to be kidnapping", the psykers have "acquired" a Seer to assist them. They can _try_ to coordinate the psykers and lead them through situations where their impairments put them at too great a disadvantage. If you're one of the psykers, make sure to keep this guy alive at all costs!

image

Why are they called Shikaris instead of hunters? Mariam-Webster says it's a Hindi word for some kind of hunter/tracker, and it sounded like something a bunch of space-junkies would call themselves because they think it sounds cool.

They now also come with a slightly different motivation, now that they can't directly threaten the crew for money. Psyker hunters now arrive tasked with a dirty kidnapping job, payment rendered in GORE.
## Why It's Good For The Game

Psykers aren't up to the challenge of being pirates. They're bogged down by a number of fundamental issues that render them unable to do anything expected of pirates. As it currently stands, they present about as much threat as you would expect from three blind junkies with guns.

Removing them wholesale would be kind of lame. They can function as a bunch of chaotic-neutral gun-toting space-maniacs, but for the purposes of gameplay, keeping them as pirates would be a waste of their talents.

Moving them to a lower-stakes role not only moves them to a niche they are more capable of filling, but gives players a more lax environment to get a grip on playing psyker without being overwhelmed.

Giving them a seeing-eye role should bring a more unique dynamic to how psykers are played (that is, some semblance of organization rather than blind flailing), and should help get over the mechanical hurdles of being a psyker until better solutions can be made. It shouldn't be too big of an impact on balance considering the psyker gang only has three spawns, while most hunter packs have 4+.

## Changelog
:cl:
balance: Psyker Pirates are now Psyker Shikari (bounty hunters).
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
Does this fix #71946

**Comment by Helg2** [comment]
I still think the only purpose psykers have is to drag gore injectors to station and become meat cube.

**Comment by Jolly-66** [comment]
> Does this fix #71946

I think the issue there lies in them not being able to conventionally see?

**Comment by nukularpower** [comment]
Can someone please for the love of god just give psykers (and other pirate crews) backpacks

**Review by Maurukas — APPROVED** [review]
Map changes look good

**Review by JohnFulpWillard — CHANGES_REQUESTED** [review]
Unless Psykers can actually use their consoles and see antag huds, I don't think they should be bounty hunters. I don't think they should be pirates either, they don't seem to fit ANY team antagonist, really.

**Comment by Rex9001** [comment]
> Unless Psykers can actually use their consoles and see antag huds, I don't think they should be bounty hunters. I don't think they should be pirates either, they don't seem to fit ANY team antagonist, really.

Then what do we do with them? A psyker solo antagonist just seems like a threat drain

**Comment by Helg2** [comment]
> Unless Psykers can actually use their consoles and see antag huds, I don't think they should be bounty hunters. I don't think they should be pirates either, they don't seem to fit ANY team antagonist, really.

You should have sayed it when they were added like this.

**Comment by JohnFulpWillard** [comment]
> You should have sayed it when they were added like this.

I had no idea what a psyker was or how it would play out in-game, I didn't really care much, but now that it's in-game we can see how players are affected by it.

**Pull request merged**
