### PR TITLE
Adds a cat language to runtime and other cats.

### PR DESCRIPTION
**Pull request by Wilchenx**
No, its not a catpeople pr.

### CODE REVIEW

**Comment by HeyBanditoz** [comment]
Yes it is

**Comment by HeyBanditoz** [comment]
Also merge conflict on open nice

**Comment by nichlas0010** [comment]
nice

**Comment by KorPhaeron** [comment]
This was previously rejected

**Comment by nichlas0010** [comment]
🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣

**Pull request closed without merging**
