### PR TITLE
last resort works as monkey or animal

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
changeling last resort works if youre a monkey or animal
any reasonably organic animal that is (golems included) so no constructs, no spirits (shades, etc), no deathmatch/bitrunning body and also not a headslug

## Why It's Good For The Game

for a "last resort" ability you cant use it if you got monkified which is something that can happen fucking you over which is not great
or perhaps due to some foul magicks you became a rat or whatever youre basically fucked because you cant do anything and all you can do is bumrush people

this fixes both

## Changelog
:cl:
balance: changeling last resort works as a monkey or animal
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
i gotta disinclude dumb stuff like shades and stuff hold on

**Comment by carlarctg** [comment]
check for biotypes

**Comment by moocowswag** [comment]
What about in a borg since youre technically still the brain (theres two ways to be turned into cyborg as ling)

**Comment by mc-oofert** [comment]
> What about in a borg since youre technically still the brain (theres two ways to be turned into cyborg as ling and still have the ling abilities)

yeah no recovery from that idk how youd manage that aside from polymorphing and eating nanites

**Pull request merged**
