### PR TITLE
Adds Med-Hardsuit, Removes suit from EVA

### PR DESCRIPTION
**Pull request by Strathcona**
Pretty much exactly what Meta has in their CMO's office.
medhardsuit

### CODE REVIEW

**Comment by GunHog** [comment]
Acceptable. :+1:
(still no love for the dang RD, but that is for a different PR)

**Comment by Dorsisdwarf** [comment]
If the RD is ever going into space he can damn well get the special-access Command space suits from EVA.

**Comment by Steelpoint** [comment]
Good change, virtually every other map gives the CMO a hardsuit and its about time he gets something akin :+1:

**Comment by Invisty** [comment]
There seems to be no good arguments for this beyond "other stations have it" and "other departments have them". 

Why not move the regular EVA SSUs to their command offices?

**Comment by Jalleo** [comment]
Because of population and antagonist reasons. If ya want more explenation i can do it probably 20 or so hours from now just reply here ifya want me to @Invisty

**Comment by optimumtact** [comment]
:-1: NO MORE FUCKING SUITS

**Comment by AnonymousNow** [comment]
Several years overdue.

Invisty - we have a medical spacesuit, so why give the CMO a regular one?
oranges - did you complain when security got all their suits?

**Comment by optimumtact** [comment]
I did, I consistently complain about it.

also the fact that there are already too many suits is not a defense for adding more you memehead.

**Comment by Strathcona** [comment]
Realistically will giving CMO a suit mess up round balance? Space is supposed to be deadly, sure, but it's also crazy how for a spacestation, we're like the titanic in terms of lifeboats. Recovering and reviving husked corpses in space is already a tedious process and a medical hardsuit makes it less tedious is all. Med has a legit reason to go to space. If you're worried about too many suits, why not remove command EVA? It gets used seldom to none.

**Comment by GunHog** [comment]
Removing Command EVA and replacing it with the CMO and RD hardsuits was part of my proposal: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=4724

I am posting in this PR because the thread's existence is what inspired the author to make it. If the hardsuits are added, removing Command EVA is needed to maintain the current space suit count.

**Comment by Jalleo** [comment]
That eva section used to never have command access.

**Comment by MrPerson** [comment]
:-1: CMO doesn't need a suit and thus shouldn't have one.

**Comment by AnonymousNow** [comment]
If we're making that point, the HoS doesn't need a suit, either. But he seems to have access to two of them in the armoury, including one for the warden.

The warden.

CMO's spacesuit will be for retrieving bodies from breaches and space, which needs to be done quite often in the latter case. Since he already has access to a spacesuit, all this does is add a thematically appropriate one to his supply.

I wonder if the people who complain about the idea of the CMO having a spacesuit because "they don't need it" have played medbay.

**Comment by optimumtact** [comment]
I don't care if he needs it or not, I care that there is far too many space suits available, fix that and you can give him as many spacesuits as he wants

**Comment by GunHog** [comment]
<b>My RD proposal, along with this one, is to remove Command EVA to preserve the suit count.</b>

**Comment by Steelpoint** [comment]
I mean, taking away the TWO EVA suits and adding TWO suits, one each to the RD and CMO, is not adding any more additional suits to the station.

**Comment by AnonymousNow** [comment]
How many times has the removal of command EVA been ignored now?

**Comment by optimumtact** [comment]
I see no evidence that the PR author has implemented that change

**Comment by GunHog** [comment]
He is right; Removing Command EVA is my idea, not that of the PR author. My proposal would have Command EVA being removed after the RD hardsuit is added to the code. The map PR adding the RD hardsuit and CMO hardsuit to the Box map would include the Command EVA removal.

This PR is actually entirely separate, and not in my control.

**Comment by Strathcona** [comment]
If you'd like, why don't we close this pull and GunHog can make a seperate one with this change and his R&D suit since I don't have the resources for that.

**Comment by GunHog** [comment]
I cannot do mapping changes. I pay WJohn in Xeno code to do my mapping for me. If I somehow make it through the gauntlet and get the hardsuit itself into the code, then a map PR can be made to add it, the Medical suit to the CMO office, and remove Command EVA.

**Comment by tuypo1** [comment]
this is great eva gear should be more accessible especially for heads and medical frequently needs to go into space

frankly I think they should get medical hardsuits in medbay storage as well but this will do for now

**Comment by Dorsisdwarf** [comment]
Mergeconflix and a reminder that every spacesuit given to a head is an additional 1/6th chance of a rev round lasting forever while That Dick builds an autism fort in space with a turret pointed at the door

**Comment by tuypo1** [comment]
just make eva gear in general easier to acquire so heads can be followed into space

**Comment by WJohn** [comment]
You know the whole of box got repiped, right? You'll probably need to grab the entire map and start over with your changes.

**Comment by GunHog** [comment]
Translation: Cry. CRY HARD. And then CRY SOME MORE.

**Pull request closed without merging**
