### PR TITLE
Removes shadowshrooms from botany.

### PR DESCRIPTION
**Pull request by Wilchenx**
Removes shadowshrooms from botany.

:cl: optional name here
del: Removed shadowshrooms from botany
/:cl:

[why]: # Noone likes them, they spam admins with messages if someone actually uses them.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
wrong

**Comment by lzimann** [comment]
Change the title so it tells what the PR is.

**Comment by The-clown-known-as-Pepe** [comment]
Sorry, thought i was goof there for a second.

**Review by lzimann — DISMISSED** [review]
If the PR is even serious, at least do the proper job of removing it entirely.

**Comment by kevinz000** [comment]
kek

**Comment by The-clown-known-as-Pepe** [comment]
They're removed from botany, still can be given to players via admins or other unexpected ways.

**Comment by FantasticFwoosh** [comment]
Read up on ideas on the forums about how to improve before you remove.

https://tgstation13.org/phpBB/viewforum.php?f=9

**Comment by ExcessiveUseOfCobblestone** [comment]
Just make planting these in the halls/not botany valid salad like you lube is.

**Review by Cyberboss — APPROVED** [review]

**Comment by MimicFaux** [comment]
Move it to exotic seed crates then. Give it the same level as a virologist ordering their crate.

**Comment by MoreRobustThanYou** [comment]
But they're good for shadowpeople mutation toxin clubs

**Comment by ExcessiveUseOfCobblestone** [comment]
Can the "why" go into more detail beyond "people don't like these"? It seems people actually DO like these according to the ratings of the PR so if we can find out what people don't like we can target that directly instead of REMOVE

**Comment by The-clown-known-as-Pepe** [comment]
@ExcessiveUseOfCobblestone vocal minority

**Comment by GuyonBroadway** [comment]
Vocal minority is a rather shit reason to justify this sort of PR, where's the logic in assuming that people who have objections are the "wrong" party and thus we can do the opposite of what they ask?

**Comment by FantasticFwoosh** [comment]
Vocal majority it seems for over 20 notable coders such as the ones who have talked in this thread, OP hasn't further defended their point at all and Lzimann who notoriously dislikes coloured light basically is saying "sure, go do whatever"

I cite a conflict of interest here to properly handling this PR, it'll be proven if lzimann merges it themselves without as much as a discussion. Aint no democracy, but coders still hold enough political power to least matter.

**Comment by lzimann** [comment]
@KorPhaeron

**Comment by lzimann** [comment]
@FantasticFwoosh what the fuck are you going about? I really don't care about this pr and have no intention of merging/doing anything with it

**Comment by FantasticFwoosh** [comment]
Heh. Well straight from the horses mouth thats good to hear.

**Comment by kevinz000** [comment]
the only vocal minority is fwoosh

**Comment by ExcessiveUseOfCobblestone** [comment]
The real trick is to make shadow shrooms a color and remove the colored lighting on normal glowshrooms :^)

**Comment by fludd12** [comment]
_Cue the discordant legion-voiced shrieks of "Improve don't remove"_

**Comment by KorPhaeron** [comment]
I dont care either way

**Comment by ChangelingRain** [comment]
Okay if kor doesn't care I'm going to care in this direction

**Pull request closed without merging**
