### PR TITLE
RCD & RPD resprite

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request
This change the RCD & RPD Sprites for something *way* more beautiful than what it was.
Basically port : https://github.com/Citadel-Station-13/Citadel-Station-13/pull/8953

## Why It's Good For The Game
It look better than what we currently have.
https://imgur.com/a/gnfD6gs

Also, some idiot will complain that they will take the RPD for the RCD, they are just blind, while they have the same color scheme, they are different enough to know what is what.

And Citadel *may* be a ERP server, you have to admit they sometimes do some good stuff

## Changelog
:cl:
change: Changed RCD & RPD Sprite
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
That thing looks more like a heavy _cannon_ than any sort of construction device! It does look quite nice, though.

**Comment by kriskog** [comment]
The RPD sprite is a bit busy. I am having a hard time telling what its trying to look like.

**Comment by trollbreeder** [comment]
RPD sprite looks more like a pneumatic cannon than a pipe dispenser.

**Comment by Tlaltecuhtli** [comment]
looks like a weapon

**Comment by ArcaneMusic** [comment]
RPD looks a lot like the ACTUAL plasma cutter from dead space than our actual deadspace plasmacutter

**Comment by Fikou** [comment]
soulless

**Comment by Michael-Ashfield** [comment]
The RPD sprite looks quite messy when held, otherwise it looks fine when on the floor.

**Comment by wesoda25** [comment]
fetish content

**Comment by JMoldy** [comment]
Eeeeh. The RCD is nice, the RPD is...kind of a mess.

**Comment by cacogen** [comment]
RCD is just busier, RPD should be some amazing gun

**Comment by Jordie0608** [comment]
As said RCD is good but drop the RPD sprite. I think it's better off with the old sprite than what looks like a laser from battletech.

**Comment by r4d6** [comment]
Citadel didn't complain about the RPD looking like a cannon.

Although the fact that we are all adults over there help.

**Comment by wesoda25** [comment]
lol the erp server is trying to throw shade

**Comment by optimumtact** [comment]
talk about a bikeshed

**Pull request merged**
