### PR TITLE
Makes NVGs, It's HUDs and Thermals more sensitive to bright lights.

### PR DESCRIPTION
**Pull request by AcapitalA**
## About The Pull Request
Night Vision Goggles, it's HUD variants and Thermal Optics now have their **flash_protect** set to **-1**.

## Why It's Good For The Game
Consistency, considering about half of the thermal optics have a differing flash_protect because they have night vision. It also adds to realism and it shouldn't affect much gameplay-wise aside from getting flashed / using a welding tool while wearing them.

## Changelog
:cl: AcapitalA
balance: Night Vision Goggles and certain Thermal Optics are **slightly** more sensitive to bright lights.
/:cl:

### CODE REVIEW

**Comment by knacker48** [comment]
Can you show a side by side comparison oh what it would look like?

**Comment by Tlaltecuhtli** [comment]
new  |  old
-1     |    0

**Comment by AcapitalA** [comment]
> Can you show a side by side comparison oh what it would look like?

It doesn't change the brightness itself, it just changes a var for consistency and realism.

The only gameplay change is that they got a flash_protect of -1 now. The var basically determines if you get blinded by bright lights. For example welding helmets when down have a flash_protect of 2 while sunglasses have a flash_protect of 1.

**Comment by ExcessiveUseOfCobblestone** [comment]
based posting w/o looking at files changed

**Comment by wesoda25** [comment]
The thing I hate is ling screech absolutely fucking rapes someone wearing thermals (and by extension NVG), which doesn’t make sense its an auditory attack, right?

**Comment by ExcessiveUseOfCobblestone** [comment]
lol it does what?

**Comment by wesoda25** [comment]
Ling screech disorients you for an obscenely long time if you're wearing some sort of NVG/Thermals, it basically makes you walk like you chugged a bottle of absinthe for over a minute.

**Comment by Tlaltecuhtli** [comment]
there are 2 ling screechs and one is an emp

**Comment by wesoda25** [comment]
It was the disorienting ling screech (non emp)

**Comment by bigfatbananacyclops** [comment]
Would it affect nuke ops though? They have Nv

**Comment by Fikou** [comment]
> Would it affect nuke ops though? They have NV, would flashes be strong enough to go through the hardsuit protector or will it be the same?

hardsuit helmets are +2, so it will be +1, wont be flash stunned, will have welding eye damage

**Comment by CRITAWAKETS** [comment]
Maybe give the meson NVG some sort of protection for only welding light so that engineers dont just blind themselves?

**Comment by AcapitalA** [comment]
IMO, NVGs and such shouldn't be something you just equip and forget about. It's something people should use in dark areas and such and not just keep equipped, because it's often literally a direct upgrade over their current eyewear.

Then again, I was thinking about buffing them a bit in other aspects so they don't get completely left in the dust compared to thermals and x-rays. Especially if this PR gets merged, ill try to look into making them somewhat better to compensate for this PR, even if it was for consistency issues.

**Comment by Fikou** [comment]
> Maybe give the meson NVG some sort of protection for only welding light so that engineers dont just blind themselves?

with sunglass protection you only get flashed once from welding so if they have a helmet they are fine

**Comment by SkeletalElite** [comment]
If this is going to be a thing then a button on screen to turn NVGs on and off would be nice, to make using NVGs with a welder more convenient.

**Comment by AcapitalA** [comment]
> If this is going to be a thing then a button on screen to turn NVGs on and off would be nice, to make using NVGs with a welder more convenient.

Sadly not in this PR, this one adjusts the flash_protect because it looks like an unagreed mess at times.

I was thinking in a future PR about buffing them a bit through, a toggable function would indeed be nice.

**Comment by ExcessiveUseOfCobblestone** [comment]
> If this is going to be a thing then a button on screen to turn NVGs on and off would be nice, to make using NVGs with a welder more convenient.

you can prob use a vast majority of the eye welding goggle's code to accomplish this

**Pull request merged**
