### PR TITLE
[Ready] Adds abductor Mind Interface Devices, and a gland HUD 

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Abductors can now see if people already have glands! Never worry about abducting the same guy twice again.
add: Added the Mind Interface Device to the abductor shop for 2 Credits. Only scientists can use it.
add: The MID has two modes: Transmit and Control.
add: Transmit will allow you to send a message anytime, anywhere to the mind of a target of your choice, regardless of language barriers. The message will be anonymous, but abductor-like.
add: Control allows you to give a temporary directive to a target with an implanted gland, that they MUST follow. Duration and amount of uses varies by gland type. When a gland is spent, it will no longer respond to Control signals. The target forgets ever receiving the objective when the duration ends.
/:cl:

This feature relies on people reading the words on the screen and obeying them; since there is a precedent with the whole golem/sentience potion dynamic i think it can work for abductors as well.
This gives a new avenue for abductors to either cause chaos (Order the victim to murder as many people as possible) or precision manipulation (Order the captain to upload a specific law).
The time limitation and the limited amount of uses prevent this from becoming a conversion mechanism: it's a resource that is used and spent, and the target can go back to being unreliable or hostile to the abductors after that (with the "forgot the objective" caveat).

Sprites:
Mind Device (Transmit/Control)
mind_device mind_device2
Gland HUD (Ready/Spent/Active)
hud_1 hud_2 hud_3

### CODE REVIEW

**Comment by ACCount12** [comment]
HUD icons are clearly not different enough. Other than that - 👍 .

**Comment by ACCount12** [comment]
Hm. Maybe make this HUD not antag-specific, but bound to a species-specific eye type? I like the idea of people stealing non-overpowered antag tools.

**Comment by XDTM** [comment]
Different how? It's not noticeable on the image but they're on the right side of mobs, so it won't interfere with existing HUDs, and shouldn't really confuse people since only abductors can really see it.

**Comment by ACCount12** [comment]
I mean the difference between states. You can see it when 3 states are all close together, but what if you see just one?

**Comment by XDTM** [comment]
The hud is connected to abductor species which is available through xenobio. but they won't pass the scientist check if you want to use the mind device.
As for the icon difference, i think the green/grey/flashing red should be fairly visible i game, they're a bit bigger than this after all.

**Comment by Armhulen** [comment]
Neat

**Comment by GunHog** [comment]
Extra fun!

**Comment by kevinz000** [comment]
make mindshield implants protect against it or this'll bypass "you can not convert people with mindshield implants" unlike every other "conversion or control" method in the game, i don't want someone in sec getting kidnapped and getting forced to go on a murderbone with their innate trust and access without any method of detection.

**Comment by ACCount12** [comment]
If someone was kidnapped, they are compromised unless proven otherwise.

**Comment by XDTM** [comment]
Checking for implants would severely increase the time abductors spend keeping you unconscious in surgery to remove the implant if the abductors already know about the limitation, and if they don't they'd be excited to have kidnapped the captain, think of a fun plan to enact, and then they'd just get blueballed.

Also, remember that they have an alien gland inside and already have a weird objective to follow, implant or not. They are already likely to not be trustworthy.

**Comment by juanototo2** [comment]
>no method of detection
>>>what is health analyzer, having eyes and seeing that mr pubcurity man is exploding into blood everywhere

**Comment by jughu** [comment]
Dude the abductors baton has litteraly a check if the person already has a probe like litteraly go trough the list.

Stun. Sleep. Restraint. Probe check.

**Comment by FantasticFwoosh** [comment]
@jughu Is right poke them with your pink stick it will even tell you how many points they are worth dead or alive, but this is still nice for ensuring that abductees continue with their mission by influencing station members & guiding them with their mundane objectives & in character.

Perhaps the mind device should read out their objective text so that the abductors can communicate with them effectively and contextually, given that ayys are not supposed to influence the outcome of the round so much that them being able to discover other antags already probed wont change anything.

Wearing hats made out of tinfoil wrapping would prevent the ayy's from beaming taunting messages to your brain.

**Comment by kevinz000** [comment]
@juanototo2 glands are not detectable by health analyzer, every other mind control/brainwashing mechanic in the game has interaction with mindshield implants, I don't see why abductors should be able to do that. People already act weirdly abductor objectives or not. Often times people ignore or half ass the objectives.
@XDTM and if they do remove the implant and it's on someone trustworthy you quickly go "Hey why isn't the HoS implanted..?"
 
>what is knowing what things do before arguing but then again it's juanototo...

**Comment by XDTM** [comment]
Unlike other conversion mechanics, abductors don't have complete control of the victim after the abduction, so, even if they dont remember the abduction, they can go "oh boy i suddenly find myself without an implant how odd let's replace it as soon as possible" and the abductors can do nothing about it.

Also, you can think of it as the defenses being breached already since the gland's inside, much like cultists don't get deconverted by implants.

**Comment by Potato-Masher** [comment]
So, uh... is this going anywhere?

**Comment by XDTM** [comment]
This has been ready for a while, i don't know why it's being ignored

**Comment by davethwave** [comment]
Add a {Ready} to the title. It might help.

**Comment by Kerbin-Fiber** [comment]
Why can't the **_CMO's ADVANCED HEALTH ANALYZER_** detect abnormal glands in someone.

**Comment by Kerbin-Fiber** [comment]
unless it already does but hey
gotta say something

**Comment by davethwave** [comment]
Finally the time has come!!!

**Pull request merged**
