### PR TITLE
Makes the tesla gun more METAL

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Makes tesla shots (From the weapons) arc while in flight rather then just on hit.
Adds some burn damage to the shots so they are more effective at killing shit.
Removes the stupid fucking chain that linked the user and the bolt, kor what the fuck.

This may be better suited to #49448, not sure. I've asked @TheVekter about the gun and he just wants the chain removed, so eh.

## Why It's Good For The Game

The tesla projectile is lame, and needs to be more..... impactful. This achieves this goal.

Also worth noting that this change makes the gun cause a butt-load of light emp's. Mostly just shuts firelocks but I thought I should bring it up. 

Worth noting that the damage output is quite good, crit in 6 shots, but around half that damage hits the user. This does not apply to the mech weapon.

## Changelog
:cl:
tweak: The tesla revolver/cannon's projectiles now arc while in flight.
balance: The projectiles now deal light burn damage on hit.
/:cl:

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
no stun

**Comment by theuhdirector** [comment]
yes stun make the gun useful

**Comment by wesoda25** [comment]
just go knockdown route - boring but works

**Comment by LemonInTheDark** [comment]
> just go knockdown route - boring but works

It's the electrocute_act() stun, so not really an option unless I hook it in, and I don't really like the idea. I feel the stun is reasonable due to the unavoidable damage and the need for insuls.

**Comment by TheVekter** [comment]
So there's some important context needed here - the Tesla gun will likely require a Flux anomaly core to unlock the ability to make it in the future.

That being said, the stun needs to be pretty damn short.

**Comment by LemonInTheDark** [comment]
> 
> 
> So there's some important context needed here - the Tesla gun will likely require a Flux anomaly core to unlock the ability to make it in the future.
> 
> That being said, the stun needs to be pretty damn short.

4 seconds boss

**Comment by TheVekter** [comment]
Yeah, naw, that's way too long. Four seconds = very dead

**Comment by LemonInTheDark** [comment]
Even with the need for insuls from the user?

**Comment by TheVekter** [comment]
Yes. You're underestimating how easy it is to get insuls.

**Comment by LemonInTheDark** [comment]
You make a fair point.
Let me see what I can do about this. Is the issue the stun itself or insuls being insuls?

**Comment by TheVekter** [comment]
It's the stun. There's a reason literally nothing stuns anymore but like.... Cult stun and even _then_ it's divisive.

**Comment by LemonInTheDark** [comment]
Ehhhhh, aight, that sucks but I get it. Lemme see what I can do

**Comment by theuhdirector** [comment]
if you need an anomaly core just to make it i think it has the right to be powerful

**Comment by TheVekter** [comment]
It's not going to require them for construction, it's going to require it to unlock it. You scan the core in the analyzer and it unlocks the node.

**Comment by Naloacisamazing** [comment]
Death to stuns

**Comment by theuhdirector** [comment]
i ded plz remove

**Comment by LemonInTheDark** [comment]
Ok yeah this thing is a 6 shot to crit, I'm happy with the stun removal. Still fucking metal by looks alone, just a little more usable without prep, and less of an instakill.

**Comment by LemonInTheDark** [comment]
Aight this looks good, time to test the mech weapon.

**Comment by LemonInTheDark** [comment]
Aight mech is a 3 shot crit, 7 or so shot kill.

**Comment by LemonInTheDark** [comment]
Ok this should be good, any other issues @TheVekter?

**Comment by LemonInTheDark** [comment]
We should be good. I think this is as complete as it ever will be.

**Comment by LemonInTheDark** [comment]
Oh and if #49448 gets merged before this pr, which frankly is a forgone decision, do NOT merge this pr until I get the core shit working.

**Comment by TheVekter** [comment]
> 
> 
> Oh and if #49448 gets merged before this pr, which frankly is a forgone decision, do NOT merge this pr until I get the core shit working.

This isn't necessary, 49448 doesn't touch anything dealing with the tesla gun.

**Comment by LemonInTheDark** [comment]
I was planning on adding the same functionality to the revolver, is this against the master plan for rnd?

**Comment by TheVekter** [comment]
Yeah, you use a single core to unlock the research node so you can build them.

**Comment by LemonInTheDark** [comment]
Aight, sounds good. Cancel that.

**Pull request merged**
