### PR TITLE
Adds the Peacekeeper Borg.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
rscadd: Adds the Peacekeeper Borg to replace the Security Borg. It comes with the following tools:
tweak: Energy bola launcher - For slowing down harmful individuals so that their targets can escape
tweak: Flash - To make people drop their weapons. Blinds when hacked.
tweak: Sedative injector - For when people get a little too unruly. Injects a non-harmful dose of a chemical that makes the subject dizzy and off-balance. Injects chloral or another toxin when hacked.
tweak: Energy barrier - Deploys a shield wall where the borg is standing in order to block energy projectile fire only. Electrocutes on contact when hacked.
tweak: Cookie dispenser - Sometimes people just need something to brighten their day. Poisoned when hacked.
tweak: HARM ALARM! - Functions like the ling's shriek, but weaker. Notifies the AI when used. Deafens when hacked.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
uh goof you didn't actually add it?

**Comment by GunHog** [comment]
Goof, you are missing the actual borg's code...

**Comment by Malkevin** [comment]
Hm... still no riot foam to keep harmful jerks away from each other or stupid jerks falling out of hull breaches.

**Comment by Zilenan91** [comment]
Nah :-1:

**Comment by TrustyGun** [comment]
Absolute madman

**Comment by lzimann** [comment]
a y y y y

**Comment by Niknakflak** [comment]
:-1:

**Comment by Aloraydrel** [comment]
I love this meme

**Comment by coiax** [comment]
> no pictures

**Comment by xxalpha** [comment]
:+1:

**Comment by Zilenan91** [comment]
Or not a skin for anything since it doesn't even remotely fit the aesthetic of the station.

**Comment by Anonmare** [comment]
>Check file commits

Goof you goof

**Comment by TechnoAlchemisto** [comment]
good shit lmao

**Comment by jughu** [comment]
Its basically a better secborg for validhunting unless it gets it own laws

**Comment by TechnoAlchemisto** [comment]
check the file commits you fool

**Comment by Niknakflak** [comment]
In case techno deletes his comment: This just adds the egg skin to service borg, most of the thumbs downs are assuming this is actually the borg

**Comment by Cheridan** [comment]
don't be an asshole goof

**Comment by PKPenguin321** [comment]
my favorite PR thank you goof

**Pull request closed without merging**
