### PR TITLE
Improves Chat Highlighting: allow more symbols, match word/case toggle

### LINKED ISSUE #57782: highlight chat doesn't work with more than one word
I can't seem to make chat highlight work. The only thing that seems to do anything is a comma after the first word making the first word work (as stated by the feature) but no amount of spacing or commas after that point seems to make the second or any thereafter word highlight

## Reproduction:
image

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Now this is what I call quality of life stuff.

Fixes: #57782 but I'm not sure why exactly.

Before:
<details>
<summary>Multiple cases</summary>

image

</details>
<details>
<summary>False positives</summary>

image

</details>
After:
<details>
<summary>Multiple cases</summary>

image

</details>
<details>
<summary>Match whole word only</summary>

image

</details>

## Why It's Good For The Game

Fix good. Better chat experience.

## Changelog
:cl:
qol: Chat Highlighting now works with more symbols and can be case sensitive and/or match whole words only.
fix: Fixed Chat Highlighting only working for the first comma separated entry.
fix: Your own messages sent over a radio and dchat now properly avoid_highlighting.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
reminding myself that i still need to make the pr that makes highlighting a whitelist instead of a blacklist (since you only want it for a few things)

**Comment by Naloacisamazing** [comment]
I dont know if this is possible but can you make it not highlight names too? I dont like it when I speak and it highlights my name everytime when I just wanna see when others are asking me stuff

**Comment by Wayland-Smithy** [comment]
IC say and hear code already tries to suppress highlighting when you hear yourself talk and it kinda works except when you hear your own radio broadcast because `avoid_highlighting = speaker == src` evaluates to false due to comparing your mob `src` to a virtual speaker version of `speaker` where as hearing it plain has two mobs to compare.

> can you make it not highlight

Probably yes, though it may be out of scope for this PR I'll try.

**Review by stylemistake — APPROVED** [review]
Good stuff, although I wouldn't add a lot of settings into that small area near the color box, it might overflow weirdly if squished.

Try putting them below the text area.

**Comment by Mothblocks** [comment]
> IC say and hear code already tries to suppress highlighting when you hear yourself talk and it kinda works except when you hear your own radio broadcast because avoid_highlighting = speaker == src evaluates to false due to comparing your mob src to a virtual speaker version of speaker where as hearing it plain has two mobs to compare.

this is what i mean. im going to make it a whitelist eventually since most of the stuff that highlights is nonsense

i'd change this one to just if the name matches yours though

**Comment by Wayland-Smithy** [comment]
> i'd change this one to just if the name matches yours though

I'm don't think `/atom/movable/virtualspeaker` inherits the `source` name, so either way we need to pass `virt.source` and comparing name rather than object just invites collisions to happen like with voice mimicry or simply someone else having your name for whatever reason. I've been in more than one round where *everyone is John Smith* with their IC name pref temporally overridden by admin for a mini event just to name one example.

**Comment by atakiya** [comment]
> Fixes: https://github.com/tgstation/tgstation/issues/57782 but I'm not sure why exactly.
>

I know I'm probably *quite* late to this, but the reason why that failed before was the global (`/g`) flag with `RegExp.prototype.test()`:
https://github.com/tgstation/tgstation/blob/96ceda031bdf6ad6aeb6f9981c34b2b5d688cf60/tgui/packages/tgui-panel/chat/renderer.js#L179
in cojunction with
https://github.com/tgstation/tgstation/blob/96ceda031bdf6ad6aeb6f9981c34b2b5d688cf60/tgui/packages/tgui-panel/chat/renderer.js#L187
Which was removed in https://github.com/tgstation/tgstation/pull/60146/commits/587426526e621378aec76ff0fd256c0da1ef1b4f

See here on test's behavior with /g:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#using_test_on_a_regex_with_the_global_flag

Hope this brings some closure to anyone.

**Pull request merged**
