### PR TITLE
Assemblies with lighting circuits now properly update light position.

### LINKED ISSUE #35577: Advanced light circuits leave their light source behind when dropped
### Before and after moving the assembly:

This is currently reproducable on a local server with revision 091034b and was reproducable on live servers on round ID 83463. The advanced light circuit was linked only to a starter but the effect could be triggered by pulsing it with a debugger, too.

Circuit code can be found here: https://pastebin.com/jnBDZa0G

### LINKED ISSUE #36706: Light made by light circuits will not follow the circuit assembly they are in if it moves via a locomotion circuit
- Use integrated circuits to build a basic drone that can move via a locomotion circuit
- Insert a light circuit and toggle it to on
- Have the drone move on its own
- Notice how the light does not follow the drone

Curiously, if you turn the light off, pick up the drone, turn it on while it is still in your hand, and walk around, the light will follow you. If you drop the drone on the floor and have it move on its own, the light will not follow it.

### PR DESCRIPTION
**Pull request by fludd12**
The circuit itself doesn't process, so I added it to the assembly process. This actually makes a bit of sense, considering the light itself is in the assembly.

I'm not sure, but I think this also makes the light properly qdel when turned off, if it didn't before, so that's a plus.

Fixes #36706
Fixes #35577

### CODE REVIEW

**Comment by Cyberboss** [comment]
This should only happen when it needs to, put it in Moved or something

**Comment by fludd12** [comment]
Will do.

**Comment by arsserpentarium** [comment]
Thanks.

**Comment by fludd12** [comment]
Happy to help!

**Review by vuonojenmustaturska — APPROVED** [review]

**Pull request merged**
