### PR TITLE
buffs the immolator

### PR DESCRIPTION
**Pull request by ghost**
Makes it do 30 damage instead of 20. It's a mech version of the laser gun, so it should be a bit heavier damage.

:cl: vcordie
tweak: Upgrades the mech-mounted laser gun with a heavier coil, allowing it to deal more damage.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Ehhhh

**Comment by vcordie** [comment]
This makes it so the immolator has higher damage per second over the solaris. Still probably won't be used over the solaris however.

**Comment by WJohn** [comment]
Laser cannons got shat on ever since they had their projectile reworked to deal more damage the further away you are. 6 more damage per tile makes it kinda useless since you can't even see what you're trying to hit.

**Comment by vcordie** [comment]
solaris doesn't fire laser cannon shots. fires just a straight 40 damage shot.

**Comment by jughu** [comment]
Mechs already are strong enough

**Comment by Magikarpet** [comment]
you can literally get the solaris cannon with 1 more emp and combat making this kinda moot and null

**Comment by vcordie** [comment]
magikarpet: normally yes, but for as much time as it takes to fire the solaris twice, you can fire the immolator 4 times, with this pr, technically this means the immolator has more dps output...if you manage to hit every shot.

**Comment by jughu** [comment]
Your in a big fucking killing mech nobody is gonna be able to kill you without ranged weapon or emps why would it need more buffs so it can kill faster

**Comment by vcordie** [comment]
jughu, I saw an engiborg solo a marauder (or was it a mauler) the other day. mechs are not strong at the moment.

**Comment by jughu** [comment]
Then the driver is terrible

**Comment by Robustin** [comment]
Keep it at 20, people expect lasers to do 20 and it would be a little bullshit to have mech lasers arbitrarily doing 50% more damage.

Increase the rate of fire a little, but like I said in the other PR I really don't think we need a mech arms race.

**Comment by kevinz000** [comment]
Give it the laser's rate of fire, NOT HIGHER DAMAGE
Oh yeah you're bad at mechs did I make that clear yet? If not, YOU'RE BAD AT MECHS!!

**Comment by FantasticFwoosh** [comment]
Given the mech's large battery capacity, it'd be nice if it would just rapidly fire 20 (or 25 because mech-gun creep) shots consistently just by holding down the mouse button it could probably withstand the strain (you can also load it up with better batteries & carry fuel with you)

Thats my thoughts on the DPS immolator vs 1 high damage shot at a time solaris, at 20 it'd still require concentrated fire to down 1 person which can be balanced if they find some cover. Plus it would self balance as EMP's/Repair drones chew chunks out of your weapon & utility power.

**Comment by optimumtact** [comment]
well this didn't seem overly popular and no other maintainer merged it by now so I suspect it's not liked by any of them.

Try a new pr perhaps with changes to the speed of shooting like people suggested?

**Pull request closed without merging**
