### PR TITLE
Removes the CRAB-17 phone from the traitor uplink.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
##  About The Pull Request

This pull request removes the suspicious phone from the traitor and nuke op uplink.

## Why It's Good For The Game

Haha remove dont improve.
No but seriously, this item has severe issues that make it basically unsalvagable. 
Every single person i've asked about this item says they hate it.
Also the thing has caused severe issues for admins because it can be used on a different z-level and affect the station. That includes central command.

## Changelog
:cl:
del: The CRAB-17 phone is no longer in the uplink.
admin: Admins can still spawn the CRAB-17 phone.
/:cl:

### CODE REVIEW

**Comment by loserXD** [comment]
haha 5000 health machine that siphons all your holochips and plays a sound globally

**Comment by wesoda25** [comment]
1000 and 1 creative ways to create a diversion as a traitor. Blatant round effecting already exists in the form of a power sync. CRAB phone is annoying and disruptive and happens way too often. Its a blatant and unimaginative way to cause a diversion as a traitor, used more often to annoy people and meme if anything.

**Comment by nemvar** [comment]
>Also the thing has caused severe issues for admins because it can be used on a different z-level and affect the station. That includes central command.

Maybe admins should use their local server for testing shit instead of the thunderdome. This isn't an argument.

**Comment by CRITAWAKETS** [comment]
Also while i was testing this PR, the thing spawned in space and then wandered off to deep space.
Good item, 10/10.
https://i.imgur.com/uCXqfoZ.png
https://i.imgur.com/Bu15kUt.png

**Comment by nemvar** [comment]
I'm mostly interested in the unsalvage part. You don't exactly explain why that is. You could easily make this thing destroy itself should it ever be on another z-level than the station.

**Comment by Detective-Google** [comment]
honestly it just seems like a shitty meme item and every time it gets to a place where It seems balanced in how it affects the round floyd immedietly buffs it again because it's not being used how HE wants it or because it's not common enough

**Comment by Yttriums** [comment]
It's also unrealistic because nobody who is into crypto-currency will ever reproduce successfully so the technology won't exist in 2500.

**Comment by optimumtact** [comment]
things you didn't do

list any of the "severe issues"

**Comment by MCterra10** [comment]
Still waiting for Dawson to show up and explain how the phone really does positively affect the game's meta

**Comment by necromanceranne** [comment]
Floyd's recent changes have made it into a real goddamn joke of an item and in a bad way. It has 5000 health and 80 melee armor so it takes almost no damage whatsoever from whatever the crew can salvage to fight it. The only weapon that THAT do more than maybe a single point of damage is the captain's saber. Thing is even with a team of dedicated people smacking the thing you still aren't likely to destroy it before the 8 minutes are up. He might as well have made it invincible.

The point of it being a distraction is completely irrelevant as the vast majority of people do not go and seek it out. They just accept they've lost their money. For most people that's an acceptable loss. They don't care. Money is largely meaningless. So this item only really serves to annoy the crew and nothing else. It's a free money siphon to the traitor for 8 minutes if anything and that has its uses since buying a bunch of energy guns and stun batons out of cargo can be enough to carry out your objectives fairly readily. But then why not just get briefcases?

It proves a problem when ops can just grab these things roundstart and to ops it does actually prove to be useful in eliminating some of the crews wealth to prevent quick armament. But more often than not its to just piss people off. If anything the item should be only usable on z-level so ops can't just use it to piss people off or have issues using uplinks on centcomm.

**Comment by optimumtact** [comment]
then remove it entirely

**Comment by Dawson1917** [comment]
> 
> 
> Still waiting for Dawson to show up and explain how the phone really does positively affect the game's meta

i like this item

If it gets removed we shouldn't bother leaving it in for admins. It's not entertaining enough for adminbuse. I agree with Anne's points in that the vast majority of people don't bother cashing out because 1) 80% of jobs don't care about the economy system or 2) they don't feel a need to run into xenobiology or the library or the corporate showroom to stop them losing the 100-200 credits they've accumulated over the course of the shift.

**Comment by CRITAWAKETS** [comment]
Im keeping the item in even when unobtainable mainly for if someone wants to remake it or if a downstream wants to do something with it.

**Comment by optimumtact** [comment]
Yeah I don't want to carry the sprite and icon if it's unused, just toss it out

**Comment by Krysonism** [comment]
You are not supposed to destroy it.

**Comment by PKPenguin321** [comment]
unused sprites go in https://github.com/tgstation/SS13-sprites if they get taken out btw

**Comment by SkeletalElite** [comment]
Literally why though. I don't see the "severe issues" that you are talking about. The only issue you mention is it affecting the station from different Z levels which is far from a "severe issue." That's literally only a problem if an admin starts pressing buttons.

**Comment by MrDoomBringer** [comment]
>No but seriously, this item has severe issues that make it basically unsalvagable.

ok what issues

>Every single person i've asked about this item says they hate it.


anecdotes be like
also still not explaining why its bad

>Also the thing has caused severe issues for admins because it can be used on a different z-level and 
affect the station. That includes central command.

Sounds like a one line PR that adds a is_station_turf() check or some shit

>haha 5000 health machine that siphons all your holochips and plays a sound globally

Its literally not supposed to be destroyed. Its not a thing to destroy, its a thing to take your money that happens to be destructible. If it was invincible tg would have a shitfit

>1000 and 1 creative ways to create a diversion as a traitor. 

Okay, now its 1000 and 2

>Blatant round affecting already exists in the form of a power sink. 

Okay? Thats like saying 'death weapons already exist in form of this gun, so we dont need that other gun'. The power sink is counterable in ways that the CRAB-17 isnt, and vice-versa

>CRAB phone is annoying and disruptive and happens way too often. 

Sounds like some one-line-PRs could be made by you if you really had an issue with this.

>Its a blatant and unimaginative way to cause a diversion as a traitor

The uplink is literally designed to help you do shit you dont want to do youself, i.e eswords instead of your own meelee weapons, emags instead of regularly hacking/breaking open doors/lockers, sketchkins instead of eguns, etc. This is a core element of traitor gameplay that you're complaining about

>used more often to annoy people and meme if anything.

It will still always result in people rushing towards it to destroy it, which is its intented purpose. If its really "annoying" then just fix it to be less annoying (not a global sound, etc)

>Also while i was testing this PR, the thing spawned in space and then wandered off to deep space.
Good item, 10/10.

Sounds like a one-line is_space_turf() PR fix to me, if it was really an issue for you

>I'm mostly interested in the unsalvage part. You don't exactly explain why that is. You could easily make this thing destroy itself should it ever be on another z-level than the station.

Facts

>honestly it just seems like a shitty meme item and every time it gets to a place where It seems balanced in how it affects the round floyd immedietly buffs it again because it's not being used how HE wants it or because it's not common enough

Okay so you're saying the item has been balanced in how it affects the round before. Bring this issue up with @Qustinnus and make a PR that reverts it to this state, if you really think it's an issue.

>It's also unrealistic because nobody who is into crypto-currency will ever reproduce successfully so the technology won't exist in 2500.

Facts

>Still waiting for Dawson to show up and explain how the phone really does positively affect the game's meta

By adding some fun shit for traitors to do that effect the round in a balanced way? At least, it can be balanced, according to @Detective-Google 

>Floyd's recent changes have made it into a real goddamn joke of an item and in a bad way. It has 5000 health and 80 melee armor so it takes almost no damage whatsoever from whatever the crew can salvage to fight it. The only weapon that CAN do more than maybe a single point of damage is the captain's saber. Thing is even with a team of dedicated people smacking the thing you still aren't likely to destroy it before the 8 minutes are up. He might as well have made it invincible.

The point of it being a distraction is completely irrelevant as the vast majority of people do not go and seek it out. They just accept they've lost their money. For most people that's an acceptable loss. They don't care. Money is largely meaningless. So this item only really serves to annoy the crew and nothing else. It's a free money siphon to the traitor for 8 minutes if anything and that has its uses since buying a bunch of energy guns and stun batons out of cargo can be enough to carry out your objectives fairly readily. But then why not just get briefcases?

Sounds like you're complaining about money being useless. As has been said 999 times before, money being unvalued is an issue outside the scope of this PR

>It proves a problem when ops can just grab these things roundstart and to ops it does actually prove to be useful in eliminating some of the crews wealth to prevent quick armament. But more often than not its to just piss people off. If anything the item should be only usable on z-level so ops can't just use it to piss people off or have issues using uplinks on centcomm.

Okay? Sounds like a one-line is_nuclear_op_uplink() PR check to me. A PR that you could make, if you really thought it was an issue,

>Im keeping the item in even when unobtainable mainly for if someone wants to remake it or if a downstream wants to do something with it.

We have access to this through the magic of !version control! (literally what git is)

>You are not supposed to destroy it.

Facts

>unused sprites go in https://github.com/tgstation/SS13-sprites if they get taken out btw

Facts

>Literally why though. I don't see the "severe issues" that you are talking about. The only issue you mention is it affecting the station from different Z levels which is far from a "severe issue." That's literally only a problem if an admin starts pressing buttons.

Uhh your counter-post isnt as thought out as this one

**Comment by CRITAWAKETS** [comment]
whats with just the random replies that you just put "facts" under.

Are you actually trying to make your post seem more competent by being longer for no reason?

**Comment by Tlaltecuhtli** [comment]
if its supposed to be unbreakable remove the random movement

**Comment by zxaber** [comment]
It's an attack with infinite range, hits everyone on the station Z level, and intended design has no room for "dodging" or acting quickly to avoid being hit. Granted, it does no damage, but almost every attack or effect has some sort of tell or warning for people paying attention and able to act quickly enough (except hiveminds, but those are out now too). This is the part that really bugs me.

That aside, it's not really that funny of a meme (I suppose that's subjective), and doesn't really do a whole lot. It has all the effect that the aurora event thing has.

The part where it travels off the Z-level could probably be fixed by deleting the thing when it does so, and really it ought to only land on a randomly selected teleporter beacon on the station Z-level to lower then chances of that. But I personally don't see much reason to keep it; it's extra uplink clutter in the form of a dead meme.

Did the idea of it not hitting miners/explorers ever happen? I haven't seen it used while I was off station so I don't honestly know. Now that miners use cash instead of points, it's a bit of a big deal. Lord knows I would be upset if I was half-way across Lavaland and lost all my cash before I could get back.

**Comment by cacogen** [comment]
it's shit
it's dumb
the word CRAB pisses me off

**Comment by Qustinnus** [comment]
the item was never supposed to be a target of destruction, if you wanted to complain about that the PR that changed that was open for around a week.

You can walk up to it and stop it from draining your ID. That's the intended gameplay.

**Comment by Qustinnus** [comment]
@critawakets acting like it's unsalvageable is retarded by the way, and if you had the slightest clue about programming you'd know the z level problem is a miniscule fix. Ofcourse confessing to that would make your already miniscule list of arguments even smaller

**Comment by actioninja** [comment]
This is stupid. If you don't like something just say you don't like it instead of making claims that it's severely unsalvagably bugged or bad without actually listing any problems that aren't extremely easy of fixes.

**Comment by cacogen** [comment]
I'm not sure why it has health and a health readout if it isn't supposed to be destroyed. Also the fact it moves around makes withdrawing your credits a pain in the ass if it's only supposed to serve as a distraction for the crew to get them to head to a certain point on the station.

**Comment by Qustinnus** [comment]
making it move around less often isn't an unreasonable change

**Comment by Dorsisdwarf** [comment]
If you wanna sabotage the whole station use a power sink tbh, they share the same role of traitor tool except one is an annoying robot that teleports everyones money into itself and one drains power from its location

**Comment by Qustinnus** [comment]
power sinks are barely used iirc because they suck balls. And again, a lot of items in the traitor pool share the same functionality so if you want there to be some kind  "only unique behavior sets" rule make it consistent. They're both distracting in different ways and are more diverse in what they do than the weapons in a uplink.

**Comment by Akrilla** [comment]
Last round this was called had about ~12 people hitting this thing for a solid 5 minutes. Fun meme tbh

**Comment by Qustinnus** [comment]
youre not supposed to hit it.  I'm not sure what I'm supposed to tell you. I can full remove the health as that's literaly the only other thing i can think of to make it more clear lol

**Comment by Akrilla** [comment]
Whenever this thing spawns I see literal swarms of people come to hit this thing until it dies lmfao. Tbh I'd make it invincible, but give a message that says they did no damage, or keep it the same as is, but make it more clear when it'll disappear?

**Comment by carshalash** [comment]
Nobody wants it to be invincible.

**Comment by wesoda25** [comment]
Literal issue of what playerbase wants vs what coders want. Players want it to be destructible so that they can get rid of it. Coders want it to be indestructible so that players just withdraw their credits. In my eyes, theres really no difference, they both serve the same issue of getting players over to where the crab is.

Also, PR creator didn't use the best arguments. It should be removed because it does not belong in the uplink. I think no one will disagree with me if I claim its only purpose is to serve as a diversion. But we don't _need_ a diversion item. We already have tons of them, and blatant round effecting ones exist in the form of power sink (not ass btw, its a good item). There was absolutely no need for CRAB Phone, and it seemed a memey PR at best. Now we've been living with it for several months, and want it fucking gone. Its annoying because it plays a global sound, takes everyones money bc??, and is a shitty, unimaginative traitors way of either pissing everyone off, or creating a diversion. 

I think our uplink shouldn't have any blatant answers to any type of scenario. There shouldn't be a perfect choice for anything a traitor would want, they should have to weigh their options and choose what items fit them best. CRAB Phone is effectively handing them a diversion on a silver platter, which is boring and lame. We should encourage them to use different traitor items to create a unique experience for the crew, not the same fucking shit every fucking shift.

**Comment by MrDoomBringer** [comment]
>whats with just the random replies that you just put "facts" under.
Are you actually trying to make your post seem more competent by being longer for no reason?

Scared?

>It's an attack with infinite range, hits everyone on the station Z level, and intended design has no room for "dodging" or acting quickly to avoid being hit. Granted, it does no damage, but almost every attack or effect has some sort of tell or warning for people paying attention and able to act quickly enough (except hiveminds, but those are out now too). This is the part that really bugs me.

Sounds like a powersink to me
Also, there **is room** for dodging and acting quickly. The machine announces its location a while before it actually starts draining cash, and it is immobile during this period - that is the perfect opportunity to act quickly to prevent your funds from being drained. Making this period longer wouldn't be an unreasonable change.

>it's shit
it's dumb
the name CRAB-17 pisses me off and i don't know why

ur shit
ur dumb
ur name pisses me off and i know why: its cus ur dum

>If you wanna sabotage the whole station use a power sink tbh, they share the same role of traitor tool except one is an annoying robot that teleports everyones money into itself and one drains power from its location

t. someone who didn't read my wall of text that addressed this issue 

>Last round this was called had about ~12 people hitting this thing for a solid 5 minutes. Fun meme tbh

t. someone who can't tell that this isn't supposed to be destroyed

**Comment by Qustinnus** [comment]
@wesoda25 cant wait for your PR to remove the e-sword and revolver.

the uplink is specifically a limited store in which you can buy specific answers for specific things, emag being a subsitute for hacking, weapons being a subsitute for getting your own weapon. etc.


also coders dont want it indestructible. stop grouping it up. I want it indestructible because the intended gameplay is that you can't send one guy with a weapon to it to finish it off. the point is that people get out of their department and go to the machine themselves.

**Comment by wesoda25** [comment]
> @wesoda25 cant wait for your PR to remove the e-sword and revolver.

If the intent is murder, you can either choose to go loud (esword or revolver), stealthy (gun with silencer or poison), or choose any other murder method available in the uplink! Theres no silver platter ranged kill available in the uplink!

> the uplink is specifically a limited store in which you can buy specific answers for specific things, emag being a subsitute for hacking, weapons being a subsitute for getting your own weapon. etc.

For hacking, you could purchase a toolbox, you could get an emag, or you could just fucking get the AI on your side and not need hacking. Or, take out HOP or Cap and similarly not need to hack. 

> also coders dont want it indestructible. stop grouping it up. I want it indestructible because the intended gameplay is that you can't send one guy with a weapon to it to finish it off. the point is that people get out of their department and go to the machine themselves.

you are a coder, the only one really making changes to it, thus I say coders. Also, one guy with a weapon never COULD finish it off. Expecting EVERYONE to go after it is childish and lame as fuck. Even for power sinks, its just a group of people actively searching for it while everyone else carries out their job as well as they can. You somehow are entertaining the notion that EVERYONE should drop EVERYTHING and go find the shitty crab.

**Comment by Qustinnus** [comment]
> complains that its too similar to item A
> complains it doesn't do the same thing as item A

ok wesoda. I forgot you just complain on this github for the sake of complaining

**Comment by wesoda25** [comment]
Hey quistinus I have a suggestion, instead of taking feedback personally and trying to generalize everyone who dislikes your PRs, you should try and interpret the feedback and alter your features accordingly. Unless I'm wrong, I've been pretty thorough and fair in explaining my opinion throughout this PR. I don't complain for the sake of complaining, I myself have made and had at least one PR merged considering the CRAB Phone. I've tried to better the item, but it should just be removed due to the conceptual flaw that is the item itself.

**Comment by MrDoomBringer** [comment]
@wesoda And if you want a diversion, you either use a powersink or the crab phone!

**Comment by Qustinnus** [comment]
hey wesoda I have a suggestion, instead of trying to pretend your feedback is supposed to be constructive and trying to pretend it's everyone else who is the problem, you should try and not use insults in every single one of your comments. Unless I'm wrong, you've never been able to make a comment where you don't belittle or shittalk the person who's feature you're attacking.

**Comment by wesoda25** [comment]
yeah my thoughts on why it should be removed are out there ill stop replaying to this PR

**Comment by necromanceranne** [comment]
@MrDoomBringer You're not wrong. There is a lack of value in money but this item being bad and that problen are neither mutually exclusive nor does this item help the problem in any way. If this was supposed to provide a use for cash for a traitor, we already have cash briefcases. 

zxaber brings up a good point. It's a global attack you can't avoid or cannot easily be remedied and comes with no warning. We have another mode type with attacks like that and it's wizard, and that is unabashedly supposed to be mean and nasty to deal with. Traitors almost certainly do not deserve this item. More importantly it blatantly gives away the round type in the most metabreaking way imaginable with a global ooc meme announcement. Honestly that alone should be the death knell. There is subtle references and nods and this is just hiting everyone with a blunt object until they think it's funny.

**Comment by PKPenguin321** [comment]
hey guys, no need to get so crabby with each other

**Comment by ExcessiveUseOfCobblestone** [comment]
> More importantly it blatantly gives away the round type in the most metabreaking way imaginable with a global ooc meme announcement.

Then change how it's communicated? There's nothing stopping a traitor from just outting the mode over radio/forcing AI to announce over communications console. There are also other blatant tells within the traitor arsenal such as the powersink or BEEP BEEP BEEP. 

If we cared about preserving the veil of the gamemode, we did a really trashy job long before this item existed.

**Comment by Detective-Google** [comment]
It wouldn't be so unsalvageable if Floyd didn't buff it every time it got nerfed to the way the players wanted it. :^) 

It's pretty shitty to create an item and then buff it until it's part of "the meta" just so it gets used

**Comment by ExcessiveUseOfCobblestone** [comment]
Really odd to bag on a contributor for maintaining a feature until they got the desired effect.

**Comment by optimumtact** [comment]
don't mind me just taking out the trash

**Comment by wesoda25** [comment]
Googles comments have merit in the sense that we shouldn’t be forcing the buff PRs when they go against what the players want, specifically for this scenario. Indestructible or not, people are gonna be rushing the stupid thing, which achieves its main goal, creating a diversion. I’m not saying always do what the players want but in this case it makes no difference.

**Comment by CRITAWAKETS** [comment]
Honestly i dont feel too comfortable in my github skills to PR a complete removal.

**Comment by optimumtact** [comment]
Forcing a particular design view is the job, therefore his comments have no merit and are just baseless personal attacks

**Comment by wesoda25** [comment]
CRIT I can make a full removal PR if you would like

**Comment by CRITAWAKETS** [comment]
Closed so that wesoda can do his PR.

**Pull request closed without merging**
