### PR TITLE
Medipen suit storage sprites

### LINKED ISSUE #69504: epipen missing suitslot sprite
wear labcoat
put epipen on suit slot

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
This was missing.
## Why It's Good For The Game
fixes #69504
## Changelog
:cl: itseasytosee
imageadd: Proper medipen suit storage sprites
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
?
image

**Comment by itseasytosee** [comment]
fuck

**Comment by itseasytosee** [comment]
👍

**Comment by ShizCalev** [comment]
Plenty more still missing if anyone's looking for some busy work. ♥
```
/datum/unit_test/suit_storage_icons
  	1 - /obj/item/ammo_casing/shotgun using invalid worn_icon_state, "shell"
  	2 - /obj/item/gun/ballistic/shotgun/hook using invalid icon_state, "hookshotgun"
  	3 - /obj/item/gun/ballistic/automatic/surplus using invalid icon_state, "surplus"
  	4 - /obj/item/melee/sickly_blade/void using invalid icon_state, "void_blade"
  	5 - /obj/item/nullrod/tribal_knife using invalid icon_state, "crysknife"
  	6 - /obj/item/radio/headset/syndicate/alt using invalid worn_icon_state, "syndie_headset"
  	7 - /obj/item/radio/headset/headset_sec using invalid worn_icon_state, "sec_headset"
  	8 - /obj/item/radio/headset/headset_sec/alt using invalid worn_icon_state, "sec_headset_alt"
  	9 - /obj/item/radio/headset/headset_eng using invalid worn_icon_state, "eng_headset"
  	10 - /obj/item/radio/headset/headset_rob using invalid worn_icon_state, "rob_headset"
  	11 - /obj/item/radio/headset/headset_med using invalid worn_icon_state, "med_headset"
  	12 - /obj/item/radio/headset/headset_sci using invalid worn_icon_state, "sci_headset"
  	13 - /obj/item/radio/headset/headset_medsci using invalid worn_icon_state, "medsci_headset"
  	14 - /obj/item/radio/headset/headset_srvsec using invalid worn_icon_state, "srvsec_headset"
  	15 - /obj/item/radio/headset/headset_com using invalid worn_icon_state, "com_headset"
  	16 - /obj/item/radio/headset/heads/captain/alt using invalid worn_icon_state, "com_headset_alt"
  	17 - /obj/item/radio/headset/headset_cargo using invalid worn_icon_state, "cargo_headset"
  	18 - /obj/item/radio/headset/headset_cargo/mining using invalid worn_icon_state, "mine_headset"
  	19 - /obj/item/radio/headset/headset_srv using invalid worn_icon_state, "srv_headset"
  	20 - /obj/item/radio/headset/headset_cent using invalid worn_icon_state, "cent_headset"
  	21 - /obj/item/radio/headset/headset_cent/alt using invalid worn_icon_state, "cent_headset_alt"
  	22 - /obj/item/toy/eightball using invalid icon_state, "eightball"
  	23 - /obj/item/toy/mecha using invalid icon_state, "fivestarstoy"
  	24 - /obj/item/toy/mecha/ripley using invalid icon_state, "ripleytoy"
  	25 - /obj/item/toy/mecha/ripleymkii using invalid icon_state, "ripleymkiitoy"
  	26 - /obj/item/toy/mecha/hauler using invalid icon_state, "haulertoy"
  	27 - /obj/item/toy/mecha/clarke using invalid icon_state, "clarketoy"
  	28 - /obj/item/toy/mecha/odysseus using invalid icon_state, "odysseustoy"
  	29 - /obj/item/toy/mecha/gygax using invalid icon_state, "gygaxtoy"
  	30 - /obj/item/toy/mecha/durand using invalid icon_state, "durandtoy"
  	31 - /obj/item/toy/mecha/savannahivanov using invalid icon_state, "savannahivanovtoy"
  	32 - /obj/item/toy/mecha/phazon using invalid icon_state, "phazontoy"
  	33 - /obj/item/toy/mecha/honk using invalid icon_state, "honktoy"
  	34 - /obj/item/toy/mecha/darkgygax using invalid icon_state, "darkgygaxtoy"
  	35 - /obj/item/toy/mecha/mauler using invalid icon_state, "maulertoy"
  	36 - /obj/item/toy/mecha/darkhonk using invalid icon_state, "darkhonktoy"
  	37 - /obj/item/toy/mecha/deathripley using invalid icon_state, "deathripleytoy"
  	38 - /obj/item/toy/mecha/reticence using invalid icon_state, "reticencetoy"
  	39 - /obj/item/toy/mecha/marauder using invalid icon_state, "maraudertoy"
  	40 - /obj/item/toy/mecha/seraph using invalid icon_state, "seraphtoy"
  	41 - /obj/item/toy/mecha/firefighter using invalid icon_state, "firefightertoy"
  	42 - /obj/item/toy/waterballoon using invalid icon_state, "waterballoon-e"
  	43 - /obj/item/toy/balloon using invalid icon_state, "balloon"
  	44 - /obj/item/toy/balloon/corgi using invalid icon_state, "corgi"
  	45 - /obj/item/toy/balloon/syndicate using invalid icon_state, "syndballoon"
  	46 - /obj/item/toy/balloon/arrest using invalid icon_state, "arrestballoon"
  	47 - /obj/item/toy/captainsaid using invalid icon_state, "captainsaid_off"
  	48 - /obj/item/toy/spinningtoy using invalid icon_state, "singularity_s1"
  	49 - /obj/item/toy/ammo/gun using invalid icon_state, "357OLD-7"
  	50 - /obj/item/toy/sword using invalid icon_state, "e_sword"
  	51 - /obj/item/toy/foamblade using invalid icon_state, "foamblade"
  	52 - /obj/item/toy/windup_toolbox using invalid icon_state, "green"
  	53 - /obj/item/toy/snappop using invalid icon_state, "snappop"
  	54 - /obj/item/toy/talking using invalid icon_state, "owlprize"
  	55 - /obj/item/toy/talking/ai using invalid icon_state, "AI"
  	56 - /obj/item/toy/talking/codex_gigas using invalid icon_state, "demonomicon"
  	57 - /obj/item/toy/talking/griffin using invalid icon_state, "griffinprize"
  	58 - /obj/item/toy/nuke using invalid icon_state, "nuketoyidle"
  	59 - /obj/item/toy/minimeteor using invalid icon_state, "minimeteor"
  	60 - /obj/item/toy/redbutton using invalid icon_state, "bigred"
  	61 - /obj/item/toy/snowball using invalid icon_state, "snowball"
  	62 - /obj/item/toy/beach_ball using invalid icon_state, "ball"
  	63 - /obj/item/toy/beach_ball/baseball using invalid icon_state, "baseball"
  	64 - /obj/item/toy/beach_ball/holoball using invalid icon_state, "basketball"
  	65 - /obj/item/toy/beach_ball/holoball/dodgeball using invalid icon_state, "dodgeball"
  	66 - /obj/item/toy/toy_xeno using invalid icon_state, "toy_xeno"
  	67 - /obj/item/toy/cattoy using invalid icon_state, "toy_mouse"
  	68 - /obj/item/toy/figure using invalid icon_state, "nuketoy"
  	69 - /obj/item/toy/figure/cmo using invalid icon_state, "cmo"
  	70 - /obj/item/toy/figure/assistant using invalid icon_state, "assistant"
  	71 - /obj/item/toy/figure/atmos using invalid icon_state, "atmos"
  	72 - /obj/item/toy/figure/bartender using invalid icon_state, "bartender"
  	73 - /obj/item/toy/figure/borg using invalid icon_state, "borg"
  	74 - /obj/item/toy/figure/botanist using invalid icon_state, "botanist"
  	75 - /obj/item/toy/figure/captain using invalid icon_state, "captain"
  	76 - /obj/item/toy/figure/cargotech using invalid icon_state, "cargotech"
  	77 - /obj/item/toy/figure/ce using invalid icon_state, "ce"
  	78 - /obj/item/toy/figure/chaplain using invalid icon_state, "chaplain"
  	79 - /obj/item/toy/figure/chef using invalid icon_state, "chef"
  	80 - /obj/item/toy/figure/chemist using invalid icon_state, "chemist"
  	81 - /obj/item/toy/figure/clown using invalid icon_state, "clown"
  	82 - /obj/item/toy/figure/ian using invalid icon_state, "ian"
  	83 - /obj/item/toy/figure/detective using invalid icon_state, "detective"
  	84 - /obj/item/toy/figure/dsquad using invalid icon_state, "dsquad"
  	85 - /obj/item/toy/figure/engineer using invalid icon_state, "engineer"
  	86 - /obj/item/toy/figure/geneticist using invalid icon_state, "geneticist"
  	87 - /obj/item/toy/figure/hop using invalid icon_state, "hop"
  	88 - /obj/item/toy/figure/hos using invalid icon_state, "hos"
  	89 - /obj/item/toy/figure/qm using invalid icon_state, "qm"
  	90 - /obj/item/toy/figure/janitor using invalid icon_state, "janitor"
  	91 - /obj/item/toy/figure/lawyer using invalid icon_state, "lawyer"
  	92 - /obj/item/toy/figure/curator using invalid icon_state, "curator"
  	93 - /obj/item/toy/figure/md using invalid icon_state, "md"
  	94 - /obj/item/toy/figure/paramedic using invalid icon_state, "paramedic"
  	95 - /obj/item/toy/figure/psychologist using invalid icon_state, "psychologist"
  	96 - /obj/item/toy/figure/prisoner using invalid icon_state, "prisoner"
  	97 - /obj/item/toy/figure/mime using invalid icon_state, "mime"
  	98 - /obj/item/toy/figure/miner using invalid icon_state, "miner"
  	99 - /obj/item/toy/figure/ninja using invalid icon_state, "ninja"
  	100 - /obj/item/toy/figure/wizard using invalid icon_state, "wizard"
  	101 - /obj/item/toy/figure/rd using invalid icon_state, "rd"
  	102 - /obj/item/toy/figure/roboticist using invalid icon_state, "roboticist"
  	103 - /obj/item/toy/figure/scientist using invalid icon_state, "scientist"
  	104 - /obj/item/toy/figure/syndie using invalid icon_state, "syndie"
  	105 - /obj/item/toy/figure/secofficer using invalid icon_state, "secofficer"
  	106 - /obj/item/toy/figure/virologist using invalid icon_state, "virologist"
  	107 - /obj/item/toy/figure/warden using invalid icon_state, "warden"
  	108 - /obj/item/toy/dummy using invalid icon_state, "puppet"
  	109 - /obj/item/toy/seashell using invalid icon_state, "shell1"
  	110 - /obj/item/toy/brokenradio using invalid icon_state, "broken_radio"
  	111 - /obj/item/toy/braintoy using invalid icon_state, "brain-old"
  	112 - /obj/item/toy/reality_pierce using invalid icon_state, "pierced_illusion"
  	113 - /obj/item/toy/foamfinger using invalid icon_state, "foamfinger"
  	114 - /obj/item/toy/intento using invalid icon_state, "blank"
  	115 - /obj/item/toy/sprayoncan using invalid icon_state, "sprayoncan"
  	116 - /obj/item/toy/xmas_cracker using invalid icon_state, "cracker"
  	117 - /obj/item/cultivator/rake using invalid icon_state, "rake"
  	118 - /obj/item/hatchet/wooden using invalid icon_state, "woodhatchet"
  	119 - /obj/item/hatchet/cutterblade using invalid icon_state, "cutterblade"
  	120 - /obj/item/storage/pill_bottle using invalid icon_state, "pill_canister"
  	121 - /obj/item/organ/internal/monster_core using invalid icon_state, "hivelord_core"
  	122 - /obj/item/organ/internal/monster_core/brimdust_sac using invalid icon_state, "brim_sac"
  	123 - /obj/item/organ/internal/monster_core/regenerative_core/legion using invalid icon_state, "legion_core"
  	124 - /obj/item/organ/internal/monster_core/rush_gland using invalid icon_state, "lobster_gland"
  	125 - /obj/item/abductor/gizmo using invalid icon_state, "gizmo_scan"
  	126 - /obj/item/abductor/silencer using invalid icon_state, "silencer"
  	127 - /obj/item/abductor/mind_device using invalid icon_state, "mind_device_message"
  	128 - /obj/item/banner using invalid icon_state, "banner"
  	129 - /obj/item/banner/security using invalid icon_state, "banner_security"
  	130 - /obj/item/banner/medical using invalid icon_state, "banner_medical"
  	131 - /obj/item/banner/science using invalid icon_state, "banner_science"
  	132 - /obj/item/banner/cargo using invalid icon_state, "banner_cargo"
  	133 - /obj/item/banner/engineering using invalid icon_state, "banner_engineering"
  	134 - /obj/item/banner/red using invalid icon_state, "banner-red"
  	135 - /obj/item/banner/blue using invalid icon_state, "banner-blue"
  	136 - /obj/item/claymore/cutlass using invalid worn_icon_state, "cutlass"
  	137 - /obj/item/claymore/highlander/robot using invalid icon_state, "claymore_cyborg"
  	138 - /obj/item/gun/magic/staff/locker using invalid worn_icon_state, "lockerstaff"
  	139 - /obj/item/gun/magic/staff/flying using invalid worn_icon_state, "flightstaff"
  	140 - /obj/item/melee/energy/sword/pirate using invalid icon_state, "e_cutlass"
  	141 - /obj/item/clothing/glasses/eyepatch using invalid icon_state, "eyepatch"
  	142 - /obj/item/melee/energy/sword/cyborg/saw using invalid icon_state, "esaw"
  	143 - /obj/item/tank/jetpack/improvised using invalid worn_icon_state, "jetpack-improvised"
  	144 - /obj/item/multitool using invalid icon_state, "multitool"
  	145 - /obj/item/multitool/cyborg using invalid icon_state, "multitool_cyborg"
  	146 - /obj/item/multitool/circuit using invalid icon_state, "multitool_circuit"
  	147 - /obj/item/pillow using invalid icon_state, "pillow_1_t"
  	148 - /obj/item/pillow/clown using invalid icon_state, "pillow_5_t"
  	149 - /obj/item/pillow/mime using invalid icon_state, "pillow_6_t"
  	150 - /obj/item/storage/bag/trash using invalid icon_state, "trashbag"
  	151 - /obj/item/storage/bag/trash/bluespace using invalid icon_state, "bluetrashbag"
  	152 - /obj/item/cane using invalid icon_state, "cane"
  	153 - /obj/item/cane/white using invalid icon_state, "cane_white"
  	154 - /obj/item/megaphone/clown using invalid icon_state, "megaphone-clown"
  	155 - /obj/item/food/pie/cream using invalid icon_state, "pie"
  	156 - /obj/item/instrument/bikehorn using invalid icon_state, "bike_horn"
  	157 - /obj/item/reagent_containers/cup/soda_cans/canned_laughter using invalid icon_state, "laughter"
  	158 - /obj/item/grown/bananapeel using invalid icon_state, "banana_peel" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	159 - /obj/item/grown/bananapeel/bombanana using invalid icon_state, "banana_peel" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	160 - /obj/item/grown/bananapeel/mimanapeel using invalid icon_state, "mimana_peel" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	161 - /obj/item/grown/bananapeel/bluespace using invalid icon_state, "bluenana_peel" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	162 - /obj/item/grown/bananapeel/specialpeel using invalid icon_state, "banana_peel" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	163 - /obj/item/food/grown/banana using invalid icon_state, "banana" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	164 - /obj/item/food/grown/banana/bombanana using invalid icon_state, "banana" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	165 - /obj/item/food/grown/banana/mime using invalid icon_state, "mimana" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	166 - /obj/item/food/grown/banana/bluespace using invalid icon_state, "bluenana" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	167 - /obj/item/food/grown/banana/bunch using invalid icon_state, "banana_bunch" in worn_icon override file, 'icons/mob/clothing/head/hydroponics.dmi'
  	168 - /obj/item/stack/spacecash/c1 using invalid icon_state, "spacecash1"
  	169 - /obj/item/stack/spacecash/c10 using invalid icon_state, "spacecash10"
  	170 - /obj/item/stack/spacecash/c20 using invalid icon_state, "spacecash20"
  	171 - /obj/item/stack/spacecash/c50 using invalid icon_state, "spacecash50"
  	172 - /obj/item/stack/spacecash/c100 using invalid icon_state, "spacecash100"
  	173 - /obj/item/stack/spacecash/c200 using invalid icon_state, "spacecash200"
  	174 - /obj/item/stack/spacecash/c500 using invalid icon_state, "spacecash500"
  	175 - /obj/item/stack/spacecash/c1000 using invalid icon_state, "spacecash1000"
  	176 - /obj/item/stack/spacecash/c10000 using invalid icon_state, "spacecash10000"
  	177 - /obj/item/clothing/mask/facehugger/toy using invalid worn_icon_state, "facehugger"
  	178 - /obj/item/kitchen/fork using invalid icon_state, "fork"
  	179 - /obj/item/kitchen/fork/plastic using invalid icon_state, "plastic_fork"
  	180 - /obj/item/kitchen/spoon using invalid icon_state, "spoon"
  	181 - /obj/item/kitchen/spoon/plastic using invalid icon_state, "plastic_spoon"
  	182 - /obj/item/bonesetter using invalid icon_state, "bonesetter"
  	183 - /obj/item/cautery using invalid icon_state, "cautery"
  	184 - /obj/item/cautery/advanced using invalid icon_state, "e_cautery"
  	185 - /obj/item/hemostat using invalid icon_state, "hemostat"
  	186 - /obj/item/hemostat/supermatter using invalid icon_state, "supermatter_tongs"
  	187 - /obj/item/retractor using invalid icon_state, "retractor"
  	188 - /obj/item/retractor/advanced using invalid icon_state, "adv_retractor"
  	189 - /obj/item/scalpel using invalid icon_state, "scalpel"
  	190 - /obj/item/scalpel/supermatter using invalid icon_state, "supermatter_scalpel"
  	191 - /obj/item/scalpel/advanced using invalid icon_state, "e_scalpel"
  	192 - /obj/item/surgical_drapes using invalid icon_state, "surgical_drapes"
  	193 - /obj/item/stack/medical/bruise_pack using invalid icon_state, "brutepack"
  	194 - /obj/item/stack/medical/gauze using invalid icon_state, "gauze"
  	195 - /obj/item/stack/medical/suture using invalid icon_state, "suture"
  	196 - /obj/item/stack/medical/suture/medicated using invalid icon_state, "suture_purp"
  	197 - /obj/item/stack/medical/ointment using invalid icon_state, "ointment"
  	198 - /obj/item/stack/medical/mesh using invalid icon_state, "regen_mesh"
  	199 - /obj/item/stack/medical/mesh/advanced using invalid icon_state, "aloe_mesh"
  	200 - /obj/item/stack/medical/aloe using invalid icon_state, "aloe_paste"
  	201 - /obj/item/stack/medical/bone_gel using invalid icon_state, "bone-gel"
  	202 - /obj/item/stack/medical/poultice using invalid icon_state, "poultice"
  	203 - /obj/item/assembly/flash/handheld using invalid icon_state, "flash"
  	204 - /obj/item/clothing/mask/cigarette using invalid icon_state, "cigoff"
  	205 - /obj/item/clothing/mask/cigarette/rollie using invalid icon_state, "spliffoff"
  	206 - /obj/item/clothing/mask/cigarette/candy using invalid icon_state, "candyoff"
  	207 - /obj/item/clothing/mask/cigarette/cigar using invalid icon_state, "cigaroff"
  	208 - /obj/item/clothing/mask/cigarette/cigar/cohiba using invalid icon_state, "cigar2off"
  	209 - /obj/item/clothing/mask/cigarette/pipe using invalid icon_state, "pipeoff"
  	210 - /obj/item/clothing/mask/cigarette/pipe/cobpipe using invalid icon_state, "cobpipeoff"
  	211 - /obj/item/disk using invalid icon_state, "datadisk0"
  	212 - /obj/item/disk/holodisk using invalid icon_state, "holodisk"
  	213 - /obj/item/disk/nuclear using invalid icon_state, "nucleardisk"
  	214 - /obj/item/disk/surgery using invalid icon_state, "datadisk1"
  	215 - /obj/item/disk/cargo/bluespace_pod using invalid icon_state, "cargodisk"
  	216 - /obj/item/disk/tech_disk/major using invalid icon_state, "rndmajordisk"
  	217 - /obj/item/melee/powerfist using invalid icon_state, "powerfist"
  	218 - /obj/item/melee/skateboard using invalid icon_state, "skateboard"
  	219 - /obj/item/melee/skateboard/pro using invalid icon_state, "skateboard2"
  	220 - /obj/item/melee/skateboard/hoverboard using invalid icon_state, "hoverboard_red"
  	221 - /obj/item/melee/skateboard/hoverboard/admin using invalid icon_state, "hoverboard_nt"
  	222 - /obj/item/melee/baseball_bat using invalid icon_state, "baseball_bat"
  	223 - /obj/item/melee/baseball_bat/homerun using invalid icon_state, "baseball_bat_home"
  	224 - /obj/item/melee/baseball_bat/ablative using invalid icon_state, "baseball_bat_metal"
  	225 - /obj/item/melee/flyswatter using invalid icon_state, "flyswatter"
  	226 - /obj/item/melee/energy/axe using invalid icon_state, "axe"
  	227 - /obj/item/melee/energy/blade using invalid icon_state, "blade"
  	228 - /obj/item/melee/energy/blade/hardlight using invalid icon_state, "lightblade"
  	229 - /obj/item/melee/synthetic_arm_blade using invalid icon_state, "arm_blade"
  	230 - /obj/item/melee/sabre using invalid icon_state, "sabre"
  	231 - /obj/item/melee/beesword using invalid worn_icon_state, "stinger"
  	232 - /obj/item/melee/supermatter_sword using invalid icon_state, "supermatter_sword"
  	233 - /obj/item/melee/cleric_mace using invalid worn_icon_state, "default_worn"
  	234 - /obj/item/melee/rune_carver using invalid icon_state, "rune_carver"
  	235 - /obj/item/melee/ghost_sword using invalid icon_state, "spectral"
  	236 - /obj/item/stamp using invalid icon_state, "stamp-ok"
  	237 - /obj/item/stamp/qm using invalid icon_state, "stamp-qm"
  	238 - /obj/item/stamp/law using invalid icon_state, "stamp-law"
  	239 - /obj/item/stamp/captain using invalid icon_state, "stamp-cap"
  	240 - /obj/item/stamp/hop using invalid icon_state, "stamp-hop"
  	241 - /obj/item/stamp/hos using invalid icon_state, "stamp-hos"
  	242 - /obj/item/stamp/ce using invalid icon_state, "stamp-ce"
  	243 - /obj/item/stamp/rd using invalid icon_state, "stamp-rd"
  	244 - /obj/item/stamp/cmo using invalid icon_state, "stamp-cmo"
  	245 - /obj/item/stamp/denied using invalid icon_state, "stamp-deny"
  	246 - /obj/item/stamp/void using invalid icon_state, "stamp-void"
  	247 - /obj/item/stamp/clown using invalid icon_state, "stamp-clown"
  	248 - /obj/item/stamp/mime using invalid icon_state, "stamp-mime"
  	249 - /obj/item/stamp/chap using invalid icon_state, "stamp-chap"
  	250 - /obj/item/stamp/centcom using invalid icon_state, "stamp-centcom"
  	251 - /obj/item/stamp/syndicate using invalid icon_state, "stamp-syndicate"
  	252 - /obj/item/storage/lockbox/medal using invalid icon_state, "medalbox+l"

```

**Comment by itseasytosee** [comment]
Be back later

**Pull request closed without merging**
