### PR TITLE
[READY] Redesigns Metastation Perma with Box-Style Rooms

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This PR takes the design concepts by @Bawhoppen on Box Station and brings them over to MetaStation.

Overall Screencap:
image

Visitation:
image
People can now visit prisoners without going to the prison wing. Better watch the visitors if you don't want them smuggling things in (or out!)

Prison Wing:
image
Adds a new Isolation Cell and changes the overall layout.
Perma:
image
The Box perma rooms are now on Meta! Did you know that US prisons use pink to pacify aggressive criminals? Nanotrasen sure does! 
(The awkward entrance has been fixed)
image

## Why It's Good For The Game

Takes the gameplay advancements from Box Station and brings them to Meta, not only to preserve them but also to implement them on another map and bring greater depth to PermaBrig.

## Changelog
:cl:
add: New Prison wing for MetaStation!
add: Visitation room for MetaStation Perma
balance: Incorporates Box Perma balances for MetaStation
/:cl:

### CODE REVIEW

**Comment by Cartographer-D** [comment]
Playtested, works well. Let me know if you find any other problems.

**Comment by TheVekter** [comment]
image

**Comment by TheVekter** [comment]
https://gfycat.com/impartialwhichhorsemouse

**Comment by Fikou** [comment]
change jobs on meta station to be 5 prisoners like on box

**Comment by Cartographer-D** [comment]
> 
> 
> change jobs on meta station to be 5 prisoners like on box

There are four cells, Fikou.

**Comment by Fikou** [comment]
do 4 then

**Comment by MrDoomBringer** [comment]
The doors in the prison should be the white normal doors. Red doors should always imply sec access is required to get through them

**Comment by wesoda25** [comment]
If box doesn’t get removed this should be closed

**Comment by optimumtact** [comment]
I don't think you should do this until the final decision on box is made, otherwise you are participating in the issue that caused the desire to remove in the first place.

**Comment by Bawhoppen** [comment]
@optimumtact When I did the new perma, I originally intended to make expanded ones for each map, but I only ever got around to actually finishing it Box. I'd happily let someone else take on the mantle of doing the other maps (I'll give some feedback later when I have a chance to review).

**Comment by optimumtact** [comment]
Making the same thing for every map is the problem though

**Comment by MrDoomBringer** [comment]
But it's not the same, this perma is a quite different from box's

**Comment by optimumtact** [comment]
If you say so

**Comment by Twaticus** [comment]
The title doesnt do this PR justice. "Recreates" makes it sound more like a copy-paste rather than a new design which is causing the confusion. Nice work though keep it up carto :+1:

**Comment by Cartographer-D** [comment]
I can't really think of a good title for it, but yea it's definitely its own thing with inspiration from bawhoppen.

**Comment by ATH1909** [comment]
Does this have random contraband loot in it like Box's prison does?

**Comment by HomocidlePancakes** [comment]
I don’t like how you are supposed to perma people by throwing them in to the chute, it’s too safe for officers. It was pretty great catching sloppy secnerds off guard when they were bringing in new prisoners.

**Comment by Cartographer-D** [comment]
> 
> 
> I don’t like how you are supposed to perma people by throwing them in to the chute, it’s too safe for officers. It was pretty great catching sloppy secnerds off guard when they were bringing in new prisoners.

Imagine robusting a secnerd into the chute and then watching them get DEstroyed by the 5 perma prisoners on the other end.

**Comment by Pugie** [comment]
Remove the perma trashbag it will be used to powergame shotgun ammo.

**Comment by Bawhoppen** [comment]
After looking it over, there's a few bits of feedback I'd like to give:
While I do doubt that the eight cells I gave to Box's map will ever fully be used (and they did feel excessive), I do think that it's worthwhile to have plenty of space to allow for the potential to have them fill up on those rare occasions, and thus then create a better prison gameplay environment. Although yours are weaved in there neatly as is (which is nice), I also enjoy the feel a caricature of a proper cell-block gives as well.
Besides that, I also agree with some of the other feedback regarding the entrance. As fun as the idea of a chute is, I think a traditional entrance would better serve the potential for interesting situations to play out. 
Most importantly, I feel that this design has _far_ too much openness and visibility. This relates to the greater topic of isolation (and therefore paranoia) in the game, and in general I am strongly in favor of trying to create a feeling of such. Having people be somewhat separated (even if not far apart, just in different rooms they can't see into) allows for many fun dynamic ways for things to play out. In this case, in the current design, I think it would be for the best to remove most of the non-exterior windows, most especially with the cells. This allows for more opportunities for prisoners to hide themselves, contraband, and also creates a sense of unknown for everyone, security and prisoners alike. 

Otherwise, while this design is certainly different to how I would've done it, I do believe it's good to have some variety in the maps, and this clearly has been made with skill and in a cohesive manner. It's pretty compact, yet still has a lot to it, which is kinda nice, especially when compared to how bulky my Box version is. Seems like it will probably end up having a pretty good feel ingame as well.

**Comment by Cartographer-D** [comment]
Thanks for the feedback Bawhoppen. I'd like to see how it plays out in game before I change much else.

**Comment by ModDownloading** [comment]
@ATH1909 

Yup, checked the .dmm file and there are 8 spots for prison contraband to spawn. The map looks great too and I'd love to be able to play perma on meta like this.

**Comment by uomo91** [comment]
You could clean up the camera c_tag's a bit, they're kind of inconsistent.
A lot of your cameras are labeled "Prison [....]" but you have a couple stragglers like "Isolation Cell" and "Permabrig Central".

If somebody is at a camera console and wants to do a quick remote sweet of the prison, they should be able to just type in "prison" into the search (or, scroll down to prison, prior to the new sec camera console code) and see all of the prison cameras listed.

**Comment by Rohesie** [comment]
Let's us know when the feedback is addressed.

**Comment by Cartographer-D** [comment]
Did so, should be ready.

**Pull request merged**
