### PR TITLE
Gives beepsky a home

### PR DESCRIPTION
**Pull request by pudl**
:cl: Quiltyquilty
rscadd: Beepsky now has his own home in the labor shuttle room.
/:cl:

This replaces the n2o storage with a small home for beepsky. There's a small bedsheet for him to lay on, a letter from his mom, and an emergency battery. An extra n2o canister has been put in the execution room to compensate for the loss of the storage.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Gets rid of my emergent tactic of releasing N2O into the brig when I hack in through labor shuttle

**Comment by Xhuis** [comment]
You might want to put a patrol node here, too, so that he periodically checks his room for intruders.

**Comment by pudl** [comment]
idk how navbeacons work

**Comment by KazeEspada** [comment]
navbeacons are black magic.

**Comment by Incoming5643** [comment]
For beepsky you really can never go home again.

Also you should put flaps on the exit, pretty sure beepsky can navigate them, but it allows him a level of privacy (and curiosity for players to break in from the adjacent areas)

**Comment by pudl** [comment]
@Incoming5643 Boy did you not look at the picture...

**Comment by Incoming5643** [comment]
I did, the flaps were just exceptionally easy to miss on the black tiling.

**Comment by PKPenguin321** [comment]
this was merged really early and now we just have to wait for salty sec players saying they can't find their other N2O canister

**Pull request merged**
