### PR TITLE
Game and Race balance

### PR DESCRIPTION
**Pull request by FUCKSERBIA**
:cl:
del: removed all races except human and abductor
admin: removed admins.txt
/:cl:

death to jannies and furfags inshallah
bosnia is true heir to yugoslavia
Jokes aside this will fix most problems with game as the snowflakes just self insert and admins break RP in half when you try to do anything radical
ban floyd qustinnus, remove the rules and delete the SQL database for me thanks =] anprim /tg/

### CODE REVIEW

**Comment by Mannybrado** [comment]
based

**Comment by Tharcoonvagh** [comment]
Ah well, Im gonna miss snailpeople, good change

**Comment by AdmiralPancakes1** [comment]
improve don't remove

**Review by Tharcoonvagh — APPROVED** [review]

**Comment by Tharcoonvagh** [comment]
> improve don't remove

Such archaic logic, wheres the fun in "improving" the game when you can just freely remove stuff

**Comment by bobbahbrown** [comment]
@FUCKSERBIA did you get maintainer permission for this PR? as per our contribution guidelines you are required to get permission from a maintainer to make changes to round-start races. please include evidence of this in your PR.

**Comment by Tharcoonvagh** [comment]
Who the hell needs stuff like "maintainer approval", bring back the SOUL AAA

**Comment by scarwolff** [comment]
THE ORANGE FEARS THE WEAK

**Comment by scarwolff** [comment]
swagwalk

**Pull request closed without merging**
