### PR TITLE
Basic Mob Carp IX: Carp Rifts & Migration

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

The almost-final part of the much larger PR I tried to make a month ago (there's actually one more thing but I'm waiting on a dog PR to get merged first).
This adds _new_ behaviour and abilities to carp.

Now when a Carp Migration occurs, all of the space carp who are spawned are given a path through the station. 
Specifically, each carp which shares a z level will try to path to a specific station area, then back out into space.

https://www.youtube.com/watch?v=0KtTI4_7a0c
Here in this video we follow one carp and its friends as it attempts to navigate "Kilo Station" in order to return to its ancestral spawning grounds, via the dormitories. 
Why are there walls underneath those windows? That's a question nature has no answer for.

In order to ensure that they don't destroy Arrivals, Departures, and anywhere else with windows in the process of trying to get inside they have also gained a new "Lesser Carp Rift" ability.
This allows carp to teleport a short distance once per minute, leaving a rift at their exit point. Any other mob can enter the rift to travel to a similar location to the space carp (within the same 3x3 area).

https://user-images.githubusercontent.com/7483112/209584254-afb5839b-a1cd-4c5a-b701-dbb47a024272.mp4

Teleporting puts their attack on a one second cooldown so you won't be _immediately_ bitten for 20 damage out of nowhere.

Their AI has been updated appropriately and they will use these abilities:
- If they're trying to migrate through the station and encounter an obstacle.
- If they're trying to atack something and encounter an obstacle.
- If they're trying to run away, as soon as possible.

https://user-images.githubusercontent.com/7483112/209584287-4402bf5b-3c41-4603-9205-5c4da8b4cd1c.mp4

That last point includes the HoS's pet Lia, who is an occasional target of traitor objectives, which can either work in your favour (scaring her to a less secure location) or against it (wait, where did she go?).

Also this fixes an embarassing bug where space carp weren't spaceproof but I am going to pull that out into its own PR so it can be merged without also needing to review this.

## Why It's Good For The Game

Carp are an iconic space animal but also quite boring, which this hopefully remedies.

In the current game the Carp Migration event announces itself to the crew and usually advertises to ghosts that a cool shark mob has spawned and this changes essentially nothing about the round, the only people Carp will usually attack are people who go out to set up the solars, and the occasional wandering curator or lone operative.
This should make the announcement mean something, as suddenly it means a belligerent animal might unexpectedly try to pass through your workplace. 

Non-magical space carp are weak enough that even an unarmed spaceman can take on one or two at a time (and even being mildly armed with makeshift weapons you have around makes them fairly non-threatening) but it can give you a bit of excitement.

The ability for Carp to teleport allows them to do this without causing _too much_ property damage or breaching the station, in my tests they will _generally_ find a way in which doesn't involve them busting windows open en masse. Also it just makes them a bit more interesting.
Traitors with dehydrated carp are not much able to make use of the Carp Rift ability as there isn't any way to get them to do it on demand, but you could spawn one which is not allied to you and then try to scare it in an appropriate direction which I think is a fun use of the item.

This undoubtedly will make Space Dragon player-controlled carp more dangerous in a way which is difficult to predict, but it also makes playing as them more fun and might encourage some guerilla tactics and cooperation which wasn't previously possible.

## Changelog

:cl:
add: Space Carp seem to have begun associating the station with food and attempting to enter from the outside, rather than simply congregating around solar panels. Employees are advised that these are wild animals, and should not be fed.
add: Space Carp can intermittently teleport short distances, leaving a short lived rift which other nearby carp will be attracted to follow them through.
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
>should not be fed

Aww, but doesn't hand feeding them make them non-hostile?

**Comment by Jacquerel** [comment]
> > should not be fed
> 
> Aww, but doesn't hand feeding them make them non-hostile?

It does, but it's like teaching a bear that there's food in your house, so they keep trying to get inside to say hello and are upset when you don't feed them 😔

**Comment by KittyNoodle** [comment]
how do they handle multi-z migrations (eg. carp spawns on z level 1 of tram but has to mirgate to area in second z level)

**Comment by Jacquerel** [comment]
> how do they handle multi-z migrations (eg. carp spawns on z level 1 of tram but has to mirgate to area in second z level)

They only pick an area on their z level, all carp which spawn on the same level go to the same place but it'll be a different place than ones which are one layer above or below

**Comment by AlamoTurtle** [comment]
Will we be able to get an ability or something like carp spurs for when we're riding a tamed carp to trigger the teleport? If so, that'd be absolutely sick and a cheeky way to get a room infiltration objective done as traitor.

**Comment by Jacquerel** [comment]
> Will we be able to get an ability or something like carp spurs for when we're riding a tamed carp to trigger the teleport? If so, that'd be absolutely sick and a cheeky way to get a room infiltration objective done as traitor.

That would be cool but this is already a big PR so I don't want to add too many extra features to it. 
Tying it to an item is a good idea though.

**Review by Time-Green — APPROVED** [review]
Not an expert in AI controllers but looks real good

**Pull request merged**
