### PR TITLE
Medullary failure nerf

### PR DESCRIPTION
**Pull request by ghost**
Medulary failure requires standing still for 3 second, so you cant cast it while being dragged, or instantly popping onto someones screen to cast it. Band-aid fix before the ability gets replaced with something better.

:cl:
balance: Medulary Failure takes 3 seconds to cast now.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
That's the only good defensive power hiveminds actually have, though. Without it they're sort of worthless to fight as.

**Comment by ExcessiveUseOfCobblestone** [comment]
why doesn't anyone try to remove it lol

**Comment by py01** [comment]
I’m trying to make a replacement bu coding is hard

**Comment by Barhandar** [comment]
It doesn't need a replacement, and standing still for some time isn't hard. 

What hivemind is, is utterly overpowered conversion gamemode because to convert, they just have to stand still on the screen somewhere near you, and the conversion fuckstuns you. The other two conversion gamemodes work adjacent only and have protection that they can't just ggwp off with their abilities at same range (flashes vs eye protection for revs, antimagic for cult stuns + cult needs the rune for convert).

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm not seeing how a targeted heart attack spell is fun or balanced because someone stands still for afew seconds.

**Comment by davethwave** [comment]
I would say that this should give something like the heart attack random event when you use it that's accelerated so the person who is inflicted has some kind of warning, better than instant killing whoever you want at least.

**Comment by Suicidalpickles** [comment]
right now assimilation is just
>see other hivemind from tracker
>click button to stop their heart instantly
>drag and reclaim other hivemind somewhere
>wait for cooldown
>repeat, one mind

would be nice if it was nullified if using it on other hiveminds but this is neat

**Pull request merged**
