### PR TITLE
Make the black jumpsuit fireproof again

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: Yackemflam
add: Black jumpsuits are foreproof again
/:cl:

He removed fireproofing from the black jumpsuit, why?

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Go home you're drunk Yacky.

Also...

> 1. It is powercreep on a common station (there are lockers in most locker rooms full of black jumpsuits/attire, it would be a better addition to syndicate tacticool's) item only distinguished by its colour
>2. It makes no sense, that's like saying blue jumpsuits give space resistance for no reason other than blue

**Comment by yackemflam** [comment]
But is it powercreep if it was there in the first place?

**Comment by FantasticFwoosh** [comment]
Yes, and it should have had a issue report.

**Comment by yackemflam** [comment]
But that was known for years.

**Comment by optimumtact** [comment]
Ha ha, great joke pr.

THank you for your contribution.

**Comment by Iamgoofball** [comment]
So is this why everyone wears black jumpsuits?

**Pull request closed without merging**
