### PR TITLE
Adds a cat tongue, for mewrrr daily dose of anoying memes

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl: SuperrrMichael
add: Added a cat tongue, currrrrrently only in rrreal cats.  Mew'll have to kill one to get it.
experiment: extrrreme trrrigerrr warrrning.
/:cl:

Cat meme tongue. For when you want to be even more of an annoying asshole. Read it like the Tacospeak rolling rr for proper effect.

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
no please

**Comment by kevinz000** [comment]
NO PLEASE

**Comment by Supermichael777** [comment]
all i'm seeing is "please make it more annoying."

**Comment by ShadowDeath6** [comment]
slibary slobe meme?

**Comment by dannno** [comment]
👍

**Comment by Supermichael777** [comment]
I actually tested™ thidon't and it worked. dropped the nya for not realy making sense in most cases

**Comment by GunHog** [comment]
Well hey, if you hate cat-girls, attack one and cut out her tongue!

**Comment by Iamgoofball** [comment]
slippery slope's lost

time to just add tajaran and vulpakin and get it over with

**Comment by Iamgoofball** [comment]
# seriously though stop pretending and just add this directly to the cat ears

**Comment by optimumtact** [comment]
grumpy cat says no

No thank you, we're not encouraging additions or modifications to the cat race at this time as it is a sensitive point.

**Comment by Supermichael777** [comment]
> I'm unhappy my preferred option lost a player vote and wish to use my position to bury the feature.

Nice meme, where did you find it?

**Comment by Supermichael777** [comment]
@Cheridan

**Comment by FantasticFwoosh** [comment]
Refusing this is a contradiction to #22116 because catpeople would fail the quota for the first statement but are put under protection by the second 

> Refuses pr's that while dumb, does try to distinguish catpeople as a seperate entity to humans

> Topically cat-people are not human with next to no PR content, no downsides as long as the are constantly concealed, such as taking a engineering hardsuit and wearing it constantly to cheese past asimov laws & generally lack depth.

But via player vote we are forced to keep it in anyway.

**Comment by optimumtact** [comment]
The mutant parts were added as a test of the mutant parts system, not with the goal of producing a new race.

**Comment by Iamgoofball** [comment]
@optimumtact by restricting potential new features from them you're bypassing the headmins!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Supermichael777** [comment]
I literally put the tongue in cats.  this was never intended to be more than a joke.  stop taking everything so personally.  just because I happen to play a degenerate cat man ironically doesn't  mean it's all about that catman ass

**Comment by ShadowDeath6** [comment]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>ironically

also adding the organ itself is still adding to the growing list of human mutation "items", like cat ears and tails, as it plays no real function outside of such, except maybe making sentient cats slightly more irritating to talk to. Who gives cats sentience, anyway?

**Pull request closed without merging**
