### PR TITLE
Reading boring book manuals makes people fall asleep

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This was split off of https://github.com/tgstation/tgstation/pull/65668 into its own separate PR.

Boring book manuals will cause a person to fall asleep if they are drowsy.

## Why It's Good For The Game

Zzzzzzzzzz

## Changelog

:cl:
expansion: Reading boring book manuals while drowsy will cause the mob to fall asleep.
/:cl:

### CODE REVIEW

**Comment by BebeYoshi** [comment]
"Stay awhile and listen!" - Deckard Cain

**Comment by Wallemations** [comment]
I have one request.

Please fix the spelling mistake of drowsiness being `drowsyness`

**Comment by MetalClone** [comment]
It's a shame this isn't a part of the bookworm quirk anymore, I thought that was quaint being exclusive to that quirk

**Comment by timothymtorres** [comment]
> Please fix the spelling mistake of drowsiness being `drowsyness` while you're at it. I am not a maintainer I just have OCD.

While that's a good idea, it's way out of scope for this PR and should be a separate grammar fix.

> It's a shame this isn't a part of the bookworm quirk anymore, I thought that was quaint being exclusive to that quirk

It was never intended to be apart of the bookworm quirk and that will get added later.

**Comment by Wallemations** [comment]
> > Please fix the spelling mistake of drowsiness being `drowsyness` while you're at it. I am not a maintainer I just have OCD.
> 
> While that's a good idea, it's way out of scope for this PR and should be a separate grammar fix.

Fair enough

**Comment by Mothblocks** [comment]
It's cute, but we shouldn't be mechanically punishing people who are trying to learn the game the literal only way that is viable (the wiki)

**Comment by timothymtorres** [comment]
I'm curious how you would feel about me applying this to only regular books then?

**Pull request closed without merging**
