### PR TITLE
Nitryl changes and N2O reactions

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Nitryl formation is made more doable and hopefully we'll see it more used on the station; added N2O formation. Both have the same gases requirements (N2O uses bz as catalyst only) but they have different temperature of reaction (low temp for N2O, high temp for NO2)
N2O now can also hurt you if inhaled in high quantities (is still a toxic gas, let's not forget this)

## Why It's Good For The Game
Made nitryl more common for uses and production, added a way to remake N2O. This is an atomized PR base for future works on those gases and more. 

## Changelog
:cl:
add: N2O formation reaction (n2 + o2 + bz as catalyst + cold = n2o)
add: N2O toxic behaviour (if you inhale it you can die in your sleep)
changed: NO2 Formation reaction (n2 + o2 + bz + heat = no2)
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Add some more detail into the change-log. Let's say I'm Joe yahoo and I want to understand what changed. Would I?

**Comment by Ghilker** [comment]
updated

**Comment by GuillaumePrata** [comment]
That is good, I used to make Nitryl every shift since you could make it without leaving Atmos when it used N2O as the catalyst, Pluoxium isnt hard to make but it did gated Nitryl for some minutes and behind setting up the incinerator which is annoying on some maps, cooperative engs or SM access.
Was also dumb that Nitryl and Pluoxium where Cargo bounties when one is the material for the other.

**Comment by ATH1909** [comment]
Are the mixes used in Medbay's anaesthetic tanks still going to be nonlethal?

**Comment by Ghilker** [comment]
yes, you need high amount of n2o to be dangerous (usually occurs only in n2o floods)

**Comment by Ghilker** [comment]
no! bad stale

**Comment by LemonInTheDark** [comment]
F

**Comment by optimumtact** [comment]
I honestly have no idea if this is balanced or not

**Pull request merged**
