### PR TITLE
removes player reference

### PR DESCRIPTION
**Pull request by anconfuzedrock**
## About The Pull Request
Removes a player reference

## Why It's Good For The Game
No player references

## Changelog
:cl:
del: Removes a player reference from the banjo.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I merged the original pr despite your arguments, which means I was well aware of it and let it slide.

Don't be a baby.

**Comment by anconfuzedrock** [comment]
going to be a baby so hard, oranges. You're being highly immature to flip so much.

**Comment by optimumtact** [comment]
okay, well in that case go be a baby somewhere else then

**Comment by anconfuzedrock** [comment]
Wish you would, Oranges.

**Comment by PKPenguin321** [comment]
it's oranges

**Comment by cacogen** [comment]
i hope the guy who plays mura at least sent you nudes oranges

**Comment by optimumtact** [comment]
come on cacogen, at least try to keep it code related

**Pull request closed without merging**
