### PR TITLE
Standardizing Toxins Gas Storage Amounts

### PR DESCRIPTION
**Pull request by AlinaStarkova**
## About The Pull Request
EDIT: (when the optimized corner decals was merged a ton of them vanished on my end when i merged master for some reason, so i had to go in and replace every single missing decal, hence the much larger line changes than expected)

Due to the newest PR that makes toxins more involved with science via experiments and such, it has come to my attention that holy hell the maps are extremely random, some maps have 6 o2 and 6 plasma and 4 nitrous oxides and 2 n2, but some maps have 4 o2, 3 plasma, 2 nitrous, and literally 0 n2, what?? theres such an extreme disparity in how much gas you start with that it becomes a hassle to do the experiments when you are working with vastly different gas amounts

so instead, i made each map standard by removing the co2 (most maps had up to 4 cans of it, when co2 does *nothing* for toxins, like at all) and making each map have 

6 o2
6 Plasma (except Kilo, it only gets 4 Plasma because holy hell Kilo is TINY)
2 Nitrous Oxide
2 N2
3-4 empty canisters
2-3 Portable Air Pumps
2-3 Scrubbers
2 Big Air Scrubbers (Again, except Kilo, it gets 0 because holy hell is it TINY, and with it being tiny the small scrubbers work fine)

(note, Meta had like double of every can any other map had so its storage was HUGE, this is what Meta looked like trimmed down to the above standard: 
image

So I have pushed meta toxins storage in to the left by one tile wide to reduce the insane space it had:
image

## Why It's Good For The Game

normally its cool to have gamers panic and have to adapt to vastly different starting resources, but considering that research is now locked behind toxins experiments, including experiments to make gas mixes they never had to make before, it should be roughly standard so that they can get used to and learn what the hell they are doing, I have been informed however this isnt enough to make the gases like Nobilium they need in the amounts for the experiments, in this case they can learn to filter out o2 from the supply line, or beg atmos to pipe them up with further gas as the round goes on, this is a rough bare minimum amount of gas to get you started on experimenting with gas mixing

## Changelog

:cl: Nari Harimoto
qol: Each Map now comes with a standard amount of gas cans in Ordanance Storage (except kilo which gets slightly less, because Kilo is too small) so you do not need to have to learn vastly different mixing methods per map, removed stored co2 as it is not used
/:cl:

### CODE REVIEW

**Comment by RandomGamer123** [comment]
Given the recent comments on #62284 (presumably by a xenobio player who actually uses BZ), would you consider adding another BZ can to toxins, which would also help with how often atmos steals the xenobio BZ can.

**Comment by AlinaStarkova** [comment]
> Given the recent comments on #62284 (presumably by a xenobio player who actually uses BZ), would you consider adding another BZ can to toxins, which would also help with how often atmos steals the xenobio BZ can.

ive been told that with the gases here you can easily make BZ, i dont think the maptainers want us to just give toxins the gases they need roundstart. they should have to make it

**Comment by Draggeru** [comment]
Leave at least one can of c02. A lot of people, including myself, use it for toxins via connecting the thermo machine to waste.

**Comment by AlinaStarkova** [comment]
> Leave at least one can of c02. A lot of people, including myself, use it for toxins via connecting the thermo machine to waste.

ive been told this isnt needed because there should be gas in the waste pipes anyway, and science always has a spare co2 can anyway albeit its in cytology but imma be real, i dont think cytology actually bothers using it since its just a kill gas which is rarely needed

**Comment by Draggeru** [comment]
> > Leave at least one can of c02. A lot of people, including myself, use it for toxins via connecting the thermo machine to waste.
> 
> ive been told this isnt needed because there should be gas in the waste pipes anyway, and science always has a spare co2 can anyway albeit its in cytology but imma be real, i dont think cytology actually bothers using it since its just a kill gas which is rarely needed

Not if you do toxins roundstart or alter waste for a custom set up

**Comment by AlinaStarkova** [comment]
> > > Leave at least one can of c02. A lot of people, including myself, use it for toxins via connecting the thermo machine to waste.
> > 
> > 
> > ive been told this isnt needed because there should be gas in the waste pipes anyway, and science always has a spare co2 can anyway albeit its in cytology but imma be real, i dont think cytology actually bothers using it since its just a kill gas which is rarely needed
> 
> Not if you do toxins roundstart or alter waste for a custom set up, any pipes you place for a custom set up have a fit with the thermo machines, so its just easier to slap the co2 in then try to fuck with waste more to get gas into the new pipes

there fine, they all have 1 co2 somewhere in ordnance to use for custom freezer setups

**Comment by AlinaStarkova** [comment]
this ones gonna take me some time to fix, after the PR that added optimized corner decal sprites all the maps i have in this PR got only half of those sprites updated, the other half are still left as the old ones, and theres a handful spattered around randomly where the decals just vanished entirely, so i have to go through every map tile to make sure the correct decals are there, and that decals that should be there are there

**Pull request merged**
