### PR TITLE
Makes paralysis trauma more modular, allows paralyzing single limbs

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
tweak: The Paralysis trauma now randomly chooses a selection of limbs to paralyze instead of always being complete paralysis. It can be a single limb, both arms, both legs, either side of your body or the classic full paralysis.
/:cl:

Trait-based paralysis both on the mob side and the limb side for all your limb-disabling needs. If you want a weapon that disables only the limbs they hit, this is your friend.

### CODE REVIEW

**Comment by XDTM** [comment]
Easy to do with this, all it takes is applying the paralysis traits.

**Comment by BeeSting12** [comment]
It would be cool for disablers to disable whatever limb they hit. Torso and head hits would stun them like right now. Leg/arm hits disable that limb.

**Comment by XDTM** [comment]
that's already a thing unless there's a bug

**Comment by FantasticFwoosh** [comment]
> 
> 
> that's already a thing unless there's a bug

Um. No? They just hit general stamina and make you fall over rather than a limb simply getting sleepy as far as im aware without more focus on the system.

**Comment by XDTM** [comment]
Stamina damage is limb-based, and if it hits the limb health cap (50, or 2 shots) the limb is disabled until it recovers half its health. Although stamina does regenerate pretty quickly, and i doubt people aim for the limbs when disabling.

**Comment by subject217** [comment]
>It would be cool for disablers to disable whatever limb they hit. Torso and head hits would stun them like right now. Leg/arm hits disable that limb.

they already do this and it ruined disablers
>i doubt people aim for the limbs when disabling.

you end up hitting the limbs anyway because of the ranged projectile impact location variance or whatever you want to call it

**Comment by XDTM** [comment]
yeah, but since disablers do 40 stamina damage they need two shots on the same limb before it regenerates the stamina away, which doesn't seem very likely if you're aiming somewhere else

**Comment by optimumtact** [comment]
stale?

**Comment by XDTM** [comment]
fixed conflicts

**Comment by optimumtact** [comment]
@FantasticFwoosh we'd need wheelchairs first but it's an interesting idea.

**Comment by optimumtact** [comment]
@XDTM whitespacing issues

**Comment by AnturK** [comment]
Fix the conflicts,looks good to merge.

**Comment by XDTM** [comment]
turns out the undef _was_ the conflict

**Pull request merged**
