### PR TITLE
Condenses Smoke Notification for Admins

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
What it says on the tin. This is a byproduct of the new vape feature, which logs every 3 seconds when you multitool it [or emag it]. I figured it doesn't need to be in paragraph form for the quick admin heads up, but I kept the sentence structure for the actual logs.

This also shows the contents of non-ckey related smoke. Might be good to know if someone finds themselves in it then ahelps.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
HOW DO I CONDENSE THOSE REMOTE MERGES REEEEEEE

**Comment by MrStonedOne** [comment]
for your master branch, you would need to hard reset your master to upstream master, then force push that

**Comment by MrStonedOne** [comment]
for this branch, just do git reset head~6 --soft then git commit to redo the commit, then git push --force

**Comment by ExcessiveUseOfCobblestone** [comment]
weird

**Comment by ExcessiveUseOfCobblestone** [comment]
ok i think i got it now, nice.

**Comment by optimumtact** [comment]
The vape should not be sending admins a message every time it creates a smoke cloud

**Comment by ExcessiveUseOfCobblestone** [comment]
Even then I don't need three lines of text in apm to tell me there's a smoke cloud somewhere.

I thought that was a """feature""""

**Comment by Cheridan** [comment]
admin spam is never a feature

**Pull request merged**
