### PR TITLE
Hijack objectives now have a minimum pop to trigger

### PR DESCRIPTION
**Pull request by BeeSting12**
:cl: BeeSting12
tweak: Hijack objectives will only be given out if there are more than 30 players.
/:cl:

It's pretty dumb to encourage murderboning when there's not enough people to fight off the traitor.

Obligatory i ded

### CODE REVIEW

**Comment by Kromgar** [comment]
seems fair

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Nothing actually calls checkplayercount

**Comment by PKPenguin321** [comment]
Maybe like 25?

**Comment by BeeSting12** [comment]
@Cyberboss where and how do i call the proc

**Comment by improvedname** [comment]
Im gonna murderbone either way

**Comment by BeeSting12** [comment]
@improvedname 
I didn't make this to prevent lowpop murderbone just to not encourage it.

**Comment by Cyberboss** [comment]
Find out where is should go to prevent the objective from being generated. @AnturK probably knows exactly where

**Comment by BeeSting12** [comment]
closed in favor of @DaxDupont 's PR

**Pull request closed without merging**
