### PR TITLE
Lesbian & Intersex Pins, and General Resprite

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Adds Lesbian & Intersex pins after I was asked to. Also redoes the general design of the pins to be better.

guh3

## Why It's Good For The Game

More character options = good, and better sprites = good.

Also spritetainers said I could.

image

## Changelog

:cl: axietheaxolotl
expansion: Brand-new Lesbian and Intersex pins!
imageadd: New sprites for Lesbian and Intersex pins, and also re-does the already existing pins.
/:cl:

### CODE REVIEW

**Comment by bluetshirtguy** [comment]
are they like, a bunch of separate pins or a radial menu?

**Comment by SmArtKar** [comment]
> are they like, a bunch of separate pins or a radial menu?

they use radial menu for reskins

**Comment by MMMiracles** [comment]
do medbay mains spawn with the lesbian pin by default?

**Comment by Fikou** [comment]
they look worse than before

**Comment by AlinaStarkova** [comment]
the Intersex pin just looks like a gold medal, i get that the pixels are too few to make a circle visible, but there is an older version of the Intersex flag if you wish to have one thats visible, albeit this one might look too similar to the trans one on the small scale too tbf

image

**Review by Twaticus — CHANGES_REQUESTED** [review]
original pin shape was better, add purple to the inside of the gold mob pin

**Comment by cacogen** [comment]
yeah i'm gonna wear the gold one because it looks like it's from a weird space cult that loves gold but also tentacles

**Comment by VladinXXV** [comment]
hexagons are the bestagons but these are supposed to be circles

**Comment by axietheaxolotl** [comment]
image

image

ok fine

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
