### PR TITLE
Drops Dragnet Stun And Reduces Dragnet Trap Break-Out Time

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl: 
balance: dragnet no longer stuns on hit
balance: dragnet traps are removed 10x faster than previously.
/:cl:
why: its a better taser, the bear trapping is already enough to make it a good gun doesnt need to have fucking stun and 30s beartraps

### CODE REVIEW

**Comment by Steelpoint** [comment]
Fair change, its a surprisingly powerful weapon in the right hands. Even post nerf the massive slowdown it causes will practically nullify the threat of whomever is hit by the trap.

**Comment by necromanceranne** [comment]
Undervalued like crazy, and was likely to become even more powerful with the movespeed adjustment. Probably a positive change.

**Comment by Adanps** [comment]
It does seem like a ridiculous weapon when you think about it, shotgun-like spread with a short stun and a massive slow afterwards, and you don't need physical ammo. I do wonder why it isn't used more.

**Comment by yoyobatty** [comment]
How about keep the stun if you run over it, remove it if it collides with you directly while not moving, and reduce the breakout time to like 5-7 seconds. Does that make any sense?

**Comment by bubberducky2** [comment]
agree with yoyobatty

**Comment by ExcessiveUseOfCobblestone** [comment]
If you can't follow up on the semi-perma slow (until an uninterruptible channel for 3 seconds) then they prob deserve to escape.

**Comment by Potato-Masher** [comment]
It's a stupid powerful stun weapon that I abuse at any chance as Warden.

It's probably not known as well just for the fact that on most maps is hidden under a pile of boxes and other crap on a table, rather than a proper rack.

**Comment by ExcessiveUseOfCobblestone** [comment]
looks good, the breakout time might need a small increase but i'd rather see how it plays out before making that call.

**Comment by The-Driker** [comment]
Unfortunate, we've turned one of the few viable, non-lethal security tools into a less useful bola. No stun, mediocre range, fast removal time and a slowdown that I assume can be negated by methamphetamine or stimulants. I guess it's still potentially useful if used in a group, but bolas or guns would likely serve that situation better, excluding energy sword users. 

Will have to do some play-testing to see if it's got some viability left in it, or if it'd just be better to outright remove it.

**Comment by Steelpoint** [comment]
You can still screw over Nuke Ops, Sword users and others with this item. A Op moving at a snails pace is little threat.

Also, you can extra screw someone over by setting the teleporter to some no-where coordinate and you can freely space someone with this weapon.

**Pull request merged**
