### PR TITLE
Power machines can now operate on different cable layers

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request

Machines that require a cable underneath it to operate like Tesla, SMES, Emitter & Turbine now look for the `cable_layer` (red, yellow, blue default being yellow) to operate on and not `machine_layer`(that var is removed). `machine_layer` & `cable layer` served the same purpose so i removed `machine_ layer` var and made it just look for the cable layer to operate on to reduce redundancy.

The following machine's can have their cable layer changed with a multitool when in the specified state
1. Emitter when it's not welded
2. Tesla Coil when it's not wrenched
3. SMES when it does not have a terminal attached
   3.1 Terminal of the SMES cable layer can also be changed with Right Click during installation
4. APC terminal cable layer can also be changed with Right Click during installation
5. Turbine rotor when its panel is open

POWER
Here all 3 SMES were on 3 separate layers of cable but they were all joined by a single multi z layer hub cable summing up all their contribution's even though they were on different cable layers. 

##  Why It's Good For The Game
It makes sense that a machine should only look for what cable layer it should operate on and adding another layer called machine layer was just redundant. Also cable layers blue & red which could not be used by machines are now usable

## Changelog
:cl:
fix: cable layers 1 & 3 can now be used by machine's like emitters, smes, tesla coil & turbine.
fix: terminals(smes & apc) can operate on different cable layers by installing them with right click
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
Anyone merge/review?

**Comment by SyncIt21** [comment]
@Time-Green help!!.  Please remove the stale label

**Comment by Time-Green** [comment]
It might be a bit before I can get to it

**Comment by SyncIt21** [comment]
> It might be a bit before I can get to it

No worries, I'm not going anywhere 👍

**Comment by SyncIt21** [comment]
@Time-Green unrelated to this PR, Is there a way to organize includes inside the `tgstation.dme` file automatically like a keyboard shortcut or an extension in VS code so it doesn't fail linters?

**Comment by Time-Green** [comment]
> @Time-Green unrelated to this PR, Is there a way to organize includes inside the `tgstation.dme` file automatically like a keyboard shortcut or an extension in VS code so it doesn't fail linters?

If there is, I wouldn't know about it

**Comment by SyncIt21** [comment]
So it's just trial and error then. It's gonna be a looong day for me :(

**Comment by Time-Green** [comment]
> So it's just trial and error then. It's gonna be a looong day for me :(

Maybe just click the 'Ticked' thing in those files off and on? The .dme's are alphabethized so you could always put them back like that. I usually overwrite my .dme and manually tick my new files back in vscode
image

I don't think you could've asked a maintainer with less toolling knowledge though

**Comment by SyncIt21** [comment]
THANK YOU, THANK YOU, THANK YOU SOO MUCH!!. It was as simple as Clicking the "Ticked" option in VS code i was struggling all night with the stupid linters, My sanity is restored

> I don't think you could've asked a maintainer with less toolling knowledge though

Then my technical knowledge is non existent in compared :). Thank you

**Pull request merged**
