### PR TITLE
Gluttony Ruin Update

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request

Going to go through and try to make all of the sin ruins fit in with the general lavaland aesthetic, give them some TLC, and remove gamer bullshit.

- Removes the free antag button (TODO: Rework/Remove Morph in another PR)
- Flavours the ruin up
- Keeps the veal render
- Butchering gloves as loot
- Silver extract for snacks
- Map slightly smaller

one2

## Why It's Good For The Game

Removes free antag button and makes gluttony a bit nicer

## Changelog

:cl:
add: Remaps the gluttony ruin!
del: Remove the free antag syringe from the gluttony ruin.
/:cl:

### CODE REVIEW

**Comment by IndieanaJones** [comment]
I'm going to ask that you don't remove Morph.  I've been meaning to getting around to looking at them and probably integrating them into the midround antag pool, would rather not have to re-add everything for that to happen.

**Comment by newfren** [comment]
What's the modsuit loot?

**Comment by Cheshify** [comment]
> What's the modsuit loot?

mining modsuit off miner corpse

**Comment by Serxule** [comment]
doesnt really resemble gluttony imo, the ruins are based off of the sins, and arent just some weird lavaland thing, as they're all magical in some way, like prides ruin changing you but teleporting you into space, or greeds ruin with its life-draining gambling (which a chance to get a magic die), while gluttonys isnt neccesarily magic it looks and makes sense, whereas this just looks like a camp for cannibals

**Comment by Cheshify** [comment]
> doesnt really resemble gluttony imo, the ruins are based off of the sins, and arent just some weird lavaland thing, as they're all magical in some way, like prides ruin changing you but teleporting you into space, or greeds ruin with its life-draining gambling (which a chance to get a magic die), while gluttonys isnt neccesarily magic it looks and makes sense, whereas this just looks like a camp for cannibals

Counterpoint, uranium walls and kitchen floors don't match

**Comment by Serxule** [comment]
> Counterpoint, uranium walls and kitchen floors don't match

the flooring could be easily changed

**Comment by Son-of-Space** [comment]
Can we add a fat abomination clown that drops the reward instead of soap?

**Comment by ATH1909** [comment]
incredibly sad, gluttony syringe morphs are funny

**Comment by Cheshify** [comment]
> Can we add a fat abomination clown that drops the reward instead of soap?

I'd be honestly ok with this, I originally wanted to add a simplemob but I couldn't get a clear answer as to where I should put it

**Comment by Cheshify** [comment]
> the flooring could be easily changed

correct, I changed the flooring to a necropolis flooring, gave the ruin some flavour, got rid of the stupid + shape, and made it smaller.

**Comment by Cheshify** [comment]
> incredibly sad, gluttony syringe morphs are funny

Funny for the person that gets to eat the ORM, not funny for the station who's one miner is now griefing them.

**Comment by Serxule** [comment]
> > the flooring could be easily changed
> 
> correct, I changed the flooring to a necropolis flooring, gave the ruin some flavour, got rid of the stupid + shape, and made it smaller.

"the flooring could be changed"
"correct, i changed the entire ruin"
Screens345o

**Comment by TheSilverNuke** [comment]
Bad update

**Pull request merged**
