### PR TITLE
Removes normal ways to obtain drones

### PR DESCRIPTION
**Pull request by ghost**
:cl: CosmicScientist
del: Can't make drones anymore
/:cl:

I don't want this merged as soon as, I'd just rather normal drones to go away if no-one offers to fix their broken state.

Going to see if I can find out from someone how to edit maps tomorrow to remove the dispensers from them since you can't make them and I swear I've seen them before.

- [x] remove any way to obtain drones outside the dispenser
- [x] remove dispenser from maps

**Edit: To better explain for the sake of a good PR body** and a lack of a link to the PR a day ago, drones have been in the code in roughly the same state for 3 years (dispenser PR by Xhuis is missing from GitHub) and have gained laws admins enforce when they notice drones doing the wrong thing due to it being a ghost role. The code verbally dictates this will happen. The role hasn't been coded to prevent these many wrong things and has weak balance to begin with being a monkey with a vent ready backpack.

Administration hasn't stopped caring about this role. It should be in their direct hands until the role is clearly not an administration problem and fixed to represent that.

### CODE REVIEW

**Comment by Jord1081** [comment]
Will we be allowed to pray to become a drone? It seems like asking for permission would at least make it easier to manage, and allow more helpful/constructive drones to keep playing.

**Comment by vuonojenmustaturska** [comment]
If you're doing this, be sure to kill staticOverlays list on mobs and the associated code

**Comment by CosmicScientist** [comment]
This doesn't remove drones from the code, so yes, if the admin lets you.

They'd even be able to spawn the dispenser.

**Comment by Aloraydrel** [comment]
adios meme drones

**Comment by Bombpants** [comment]
Why do you want to remove drones?

**Comment by Shadowflame909** [comment]
Something Something "Welp metagrudgers keep abusing drones and people in the policy discussions dont have a solution that can't be missintepretated 100 percent of the time." "BYE BYE DRONES"

**Comment by Spaceinaba** [comment]
imagine being such an absolute unit you remove drone spawning items entirely instead of just removing the machine that makes them and removing the cargo crate

**Comment by Shadowflame909** [comment]
>Code a better fix.

I see what you're doing here. You're trying to make us believe this is a code issue! When it isn't. Drones are literally just non-interactive engineers with more mobility. If we want less drone shittery then maybe we should just start giving out drone bans instead of trying to code them out?

**Comment by ishitbyabullet** [comment]
@Shadowflame909 why do the admins have to argue about whether or not plants are actual living things because a drone did botany?

That's why.

**Comment by ike709** [comment]
Or you could just, y'know, not remove my second favorite role just because some fucktards suck at following drone laws and admins aren't banning them hard enough.

**Comment by RandomMarine** [comment]
>if players can't understand policy, they need to be ensured an active admin on to explain and curb behaviour.

If there aren't any active admins then the server's going to have bigger problems than a few bad drones, for instance literally every other role griefing with impunity.

**Comment by Shadowflame909** [comment]
Don't give me more "what-ifs" Repair and Improve. It's up to an admins discretion. Maybe instead of trying to make a code work-around over every situation. Why can't the admin just go "Bwoink. I don't think you should be doing that." 
The player: "But *insert admin here* let me get away with it!"
Admin: "I'm not that *insert administrator here* So please don't do that."  That's all you need to do!

**Comment by fludd12** [comment]
On one hand, I agree that drones shouldn't be removed from normal play and that we should ban player who abuse them.

On the other hand, I want to make it clear that the answer for issues like this isn't always just, *Well, the admins should work harder.* I've seen that reasoning used for a lot of things, and let's remember that they're volunteers who are doing what amounts to adult babysitting for hours on end for your benefit.

**Comment by 81Denton** [comment]
How about locking drones behind a playtime limit instead?

I feel that this would get rid of players who have a hard time with reading basic rules.

**Comment by Ratvar** [comment]
No, it wouldn't, really.

**Comment by CosmicScientist** [comment]
@Shadowflame909 what bullet said about botany applies. There are no what if's. This gets in - admin will be directly responsible - what they say goes. Currently they can fly without an admin.

@ike709 this is a high standard role, if this gets in, ask an admin to let you play one.

@RandomMarine regular players aren't held by high standards, it's just don't murder each other unless valid, the rest of their standards comes from code limitation. Drones have less code limitation (ID access, ventcrawl) and higher standards whilst being available to everyone dead.

@fludd12 pretty much. Until someone fixes drones to either stop them before admins need to or to help admins to know when to stop them, I don't see why admins should monitor this extra work role without directly spawning them in.

@81Denton there's already an age check [drones_as_items.dm#L49](https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm#L49) but I assume that's not a playtime check. Feel free to add one and maybe a whitelist too.

**Comment by SgtxRootbeer** [comment]
Nice, the codebase is adminning again

**Comment by Shadowflame909** [comment]
I guess we'll only see drones on wizard rounds, then.  If you look at the duration of time VR was enabled if admins wanted them to be, they were only enabled like 1/30 rounds. 

I firmly believe any admin would avoid the extra work, or having a chance of a griefer being able to be tied to there name and come back to bite them in the butt.

**Comment by Bombpants** [comment]
Is whitelisting drones too much work? Maybe if a player can play for a month or so without being a complete jerk AND make a short post on the forums (something REALLY simple), they could be whitelisted.

**Comment by F-OS** [comment]
:clap: STOP :clap: FIXING :clap: ADMINISTRATIVE :clap: PROBLEMS :clap: WITH :clap: CODE

**Comment by Arianya** [comment]
The issue is two fold.

One is that drones are a never ending pile of policy discussions, because no amount of refining or discussion on their rules/policy has actually produced a consistent experience for players on the other end of drones.

The other side of it is the administration issue, when drones are a freely spawned role by the station crew, it becomes more problematic to bwoink them over minor offences, especially when those offences might be un-reported by living crew and only noticed by admins/ghosts.

If this role is swapped to admin-spawned (or some kind of non-default whitelist) then it becomes a privilege rather then a right, and it becomes more palatable to pursue drones over seemingly minor infractions.

**Comment by F-OS** [comment]
Make drones roundstart with two slots, like borgs, remove the dispensers, and make them buildable by robotics, like VG does, bam.

**Comment by Squeakmonium** [comment]
Why are we trying to fix admin problems with code? Removing drones is not the solution here.

**Comment by Arianya** [comment]
Because trying to fix "admin problems" with administration hasn't proven effective at generating a consistent player experience of what drones are like to have interact with the round, and consistency is something that players, admins and headmins all feel is very important with regard to admin issues. Code is impartial and unbiased, so it can enforce these things without any policy discussions or long back and forths on the specifics of roleplay rules.

**Comment by cacogen** [comment]
>make controversial pr
>no indications it's getting merged
>rack up tons of (You)'s

**Comment by Squeakmonium** [comment]
If trying to fix admin problems with administration isn't giving the type of answer you're after, then it may be a further admin problem.

Code itself may be unbiased, but that doesn't mean the coder is.

**Comment by F-OS** [comment]
Removing a feature doesn't equal fixing it

**Comment by Arianya** [comment]
Trying to answer every problem with "it's an admin problem to fix" is an easy cop out for people who do not have to deal with administration problems, same as "just fix the bugs" is an easy cop out for people who have no intention of spending the untold hours troubleshooting, fixing and PRing the bugs.

If we can't go more then a week without a policy thread, a adminbus discussion or people complaining about a drone rampaging around the station doing something that doesn't fit their interpretation of drone law/policy, then we are beyond the point where you can just say "don't fix admin problems with coding!!"

If you can offer an actual solution to the problem that conclusively deals with:

* Players having a consistent experience with drones
* Drones not needing to be watched 24/7 in case they breach their laws/policy
* Drones not creating a policy issue/discussion thread each and every time a drone ends up interfering with a round and we have to have a long back and forth on why plants aren't being but kudzu, a plant, is a being and why drones should maybe just not be in Botany full stop given they are a role meant to repair and maintain the station, not grow mutated plants for the crew.

**Comment by Tlaltecuhtli** [comment]
🍆

**Comment by Shadowflame909** [comment]
Here are two solutions.
1. We start drone-banning people.

2. We remove "Improve" and make repairing the station the only thing drones are allowed to do.

**Comment by Arianya** [comment]
1. is basically what every headmin/admin has tried to do since 2014, create a coherent drone policy that leads to bad drones being banned and mostly only good drones left, and here we are in 2018 and its clearly still not working

2 might be an actual solution, but realistically it would require a player vote or ultimatum by the headadmins to be even vaguely enforceable.

**Comment by Shadowflame909** [comment]
I believe "2" is how it is on most servers. But you can emag drones and make them semi-free. Basically like tiny emagged borgs.

**Comment by RandomMarine** [comment]
>Players having a consistent experience with drones

Who the fuck plays SS13 for a 'consistent experience'? Are you that detached from the spirit of the game?
>Drones not needing to be watched 24/7 in case they breach their laws/policy

If only we had a system for players to file reports when they witness rulebreaking behavior.
Oh wait.

>Drones not creating a policy issue/discussion thread each and every time a drone ends up interfering with a round and we have to have a long back and forth on why plants aren't being but kudzu, a plant, is a being and why drones should maybe just not be in Botany full stop given they are a role meant to repair and maintain the station, not grow mutated plants for the crew.

This is the only legitimate argument but it really isn't hard to just say "Yeah go ahead and grow wood or other stuff you want for a project or some harmless gimmick, but don't try to take over botany or leave out deathnettles or slippery shit for people to use."

Enforce and create policy around the rules as intended, not necessarily over the rules as written.

**Comment by Arianya** [comment]
>Who the fuck plays SS13 for a 'consistent experience'

No, you're right, clearly every round should start with the station map randomly shuffled around, escalation rules generated by a markov chain, and every objects force, size and anchoring randomized. This sounds like a fun SS13 experience.

If you run into a borg and tell it to open a door for you, you expect it to open a door for you. You don't expect it to put on a top hat, deconstruct the floor in front of the door, and throw a banana pie in your face, and then have to open a silicon policy thread about how silicons are breaking their laws.

>If only we had a system for players to file reports when they witness rulebreaking behavior.

Ban appeals are the salt mines and you know it and you're just arguing from bad faith if you think drones would be any less of a bikeshed if people filled out a form telling us how they were really upset by the action of drone 561 18 rounds ago and also most of what they were doing is unlogged good luck admins!

**Comment by Squeakmonium** [comment]
We're not asking for anarchy Arianya, we're saying that if every round went the exact same way, it would get boring. If literally every round you started as botanist, played for 10 minutes, then had a bomb explode that depressurized botany, you'd likely not play botany anymore. But if you have a random round where as chemist you accidentally blow yourself out of chemistry and have to fix it? That's a different story.

Ban requests are salt mines yeah, but ya know what. Sometimes ya gotta learn to deal with the salt, and the admins seem to have gotten pretty good at it.

**Comment by Shadowflame909** [comment]
I mean no one's denying it still. If this gets merged. **WE WILL NEVER SEE DRONES OUTSIDE OF WIZARD ROUNDS** (Unless an admin becomes a drone or does that end round drone-ops meme) This is fact

**Comment by Arianya** [comment]
We could easily operate drones by TC trade rules, given upon request at admin discretion with the admin liable for what the drone does, but that's a policy discussion not really for github

Also saying "lmao deal with the salt" is once again a cop out attempt by people who will never have to deal with a ban request or understand the community ramifications of their existence.

And how is "drones behave in something resembling a somewhat predictable manner based off their EXTREMELY STRICT, ONE PURPOSE EXISTENCE" making "every round the exact same way"

**Comment by Shadowflame909** [comment]
That's how drones should be though. They should be completely one track minded. They should focus on repairing the station, fixing hull breachs and replacing lights. If they are doing any more then that. Then they shouldn't be a drone. Simple as that!

**Comment by Arianya** [comment]
Cool, thanks for agreeing with me shadow

**Comment by RandomMarine** [comment]
Very few players mind drones that decide to play an instrument, or clean up messes, make conveyor/transit tube/disposal rides, or set up any other harmless gimmick, and it all goes along with their primary rule of not interfering with people.

There's more lost than gained if anyone decides that they can _only_ do repairs and nothing else just because of a few bad eggs that take over departments or fight things.

**Comment by Shadowflame909** [comment]
This PR is more loss in general. You'd never see drones again.

**Comment by CosmicScientist** [comment]
@Kromgar no, otherwise it'd be a PR to stop that.

@SgtxRootbeer the role is designed to be administrated heavily [read its laws](https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm#L80). This makes it to be admin spawned only so the admin who spawns it is responsible, not the code because it is unable to enforce what admins want. If you want a whitelist, code it. It differs to sillycones in presence/knowledge of what to ahelp against due to their lacking presence (small, untappable comms).

@Shadowflame909 if any admin would avoid the extra work, because as you say the average player can't handle it, the role is bad or policy needs to be changed and the drone laws rewritten. If you don't want them to go, code a fix or demand a large policy change.

@Bombpants make a whitelist PR. I don't know how to do that code.

@F-OS this is an administrative heavy role, [read its laws](https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm#L80), and no-one's fixed the innate problems for three years. If you want to see a different change, make a PR. Drones can be produced by mech fabbers currently, and are on the techweb, unless this PR is merged. If you wish it to not be "removed"/adminspawn only, fix it, it's had three years.

@Arianya thanks for trying to explain the problems. I appreciate it since I'm struggling to take it all in.

@Squeakmonium admins never fixed their problem with the role and the code reflects this, [read its laws](https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm#L80), so I'm handing the role to admins alone until they figure it out or someone else changes the role to not need admins.

@cacogen I hope to someday have a PR with the most reactions or comments.

Frakking hell's bells. If administration either gave up on the role/demanded code to determine its balance, not the admins, or someone removed its fluff laws, the admin enforcement notice and flipped the Vs to the host, then you'd get to keep your drones in their 3 years and running broken state that demands administration to pick up the balance slack that code has not.

**Review by ChangelingRain — APPROVED** [review]

**Comment by MrStonedOne** [comment]
I fail to see what the issue with drones are.

It is entirely valid to say "The thing is an open ended thing to ensure flexibility and policy will handle the emergent gameplay issues"

That is not a flaw

That is good design.

**Comment by CosmicScientist** [comment]
I'll wait to see if any headmins want to say anything before I try and headbutt what you just said.

**Comment by CosmicScientist** [comment]
Admin intervention is required by policy when IC conflict occurs. The code does not support finding these conflicts or preventing them in the first place without one eye on every drone with one hand over the adminpm button and I imagine it'd be quite a task to rectify that.

I feel the flaw is that admins and coders have two separate designs.

Thanks for the concise point though, it's a good one that has me shaking in my git push boots, no sarcasm!

I'm going to clam up now and hope maybe a headmin can give an opinion and maybe @ShizCalev can tell me if my map file editing is all that's necessary since it's my first toim in the .dmm files.

**Comment by Shadowflame909** [comment]
So what your saying is, drones are so evasive that admins can't keep track of them. Yet, I challenge and retort that statement! You just have to ahelp about a drone being a shitter and sure enough, it will get drone banned. 

Honestly just remove "Improve" from the things drones are allowed to do and things will run a lot more smoothly.

**Comment by ChangelingRain** [comment]
`You just have to ahelp about a drone being a shitter and sure enough, it will get drone banned.`
yes good true how do you do that if you don't know which drone did it, or even that it *was* a drone that did it

**Comment by davethwave** [comment]
Its called witnessing it and saying the drone(111) did this, is more than enough. What do you mean by the (or even that it _was_ a drone that did it)?

**Comment by MrStonedOne** [comment]
"Because its possible to violate policy without getting seen its bad".

Thats like 90% of this game thou.

**Comment by CosmicScientist** [comment]
Breaking my clammy vow for one moment, the role is designed to not be seen or heard and policy is for it to be dumb (not snipping power cables because of a powersink). Every other role can act upon problems, especially antagonistic and cannot hide when interfering unless an antag with the right tools.

If they were big clunking machines that left oily trails and blared "Vehicle reversing"...

**Comment by Shadowflame909** [comment]
I guess a better solution is to make drone actions more obvious to the admins. IE some special sort of logging?

**Comment by optimumtact** [comment]
cosmic you're a doody head for opening this PR after your last one got btfo

anyway this is a headadmin decision as far as I am concerned

**Comment by vuonojenmustaturska** [comment]
For the record, I'm somewhat against a policy-as-a-PR thing like this that doesn't address the significant code issues with drones. However, in my opinion drones have multiple problems involving:

- The code is literally hitler, particularly anything involving staticOverlays but also the parts where drones have human/carbon-level features pasted on but then there's also `attack_drone()` and all sorts of other nonsense. At least their saycode no longer loops through the dead players list once for every mob in the game.
- Their design is effectively a single-player role, thrust in the middle of a multiplayer round that they are not allowed to interfere with. I think it's fair to say that this has not worked at all, fucking golems/ashwalkers interfere less with the round and they're not explicitly disallowed to do so.
- In order to deal with drones administratively, we would have to extend logging to any action the drones are capable of doing. This might not be technically feasible.
- The crew does not have any tools to tell free drones and non-free drones apart

Personally, I've never felt a drone has improved any round I've played in. At best, drones rebuild APCs someone else may have sabotaged and build autismforts in space using resources no-one cares about like metal and glass. 
More commonly, they're frivolously spending the station's exotic materials, somewhat unintentionally preventing things like a traitor robo finishing his mech. Very common sights involve drones fighting the midround side-antags, drones welding shuttle airlocks, drones supporting one side in a non-extended round. 
Consider the fact that drones as a ghostrole know what the gamemode is, and if I see a drone opt to build their autocloner in the brig instead of the hallway like usual I pretty much know it's revs or nukies. Though stealth-revs really isn't a thing.

**Comment by optimumtact** [comment]
Two of the three headadmins have approved the idea of this PR, so it will be merged subject to the approval of the design lead

**Comment by Noahnoah55** [comment]
@KorPhaeron At that point, isn't it just a borg though?

**Comment by ike709** [comment]
image
One of these days the proletarians will rise up and overthrow the ruling class.

**Comment by ike709** [comment]
@KorPhaeron I agree with @Noahnoah55. Doing that would just turn drones into Borg Lite:tm:

**Comment by optimumtact** [comment]
do you even still play here ike, go make your own drone station lol

**Comment by ike709** [comment]
@optimumtact You're right, I'm going to make my own drone station, with blackjack and hookers!

**Comment by CosmicScientist** [comment]
It'd only be borg if you forced them to use positronic brains.

**Comment by Bawhoppen** [comment]
Drones shine out as a jewel in this dark void, since they require people to use their discretion and skip a blatant and clearly defined ruleset. But the ruling elite admin class cannot let this slide by, as without rules, they will have no way to control and herd the sheep that are the players without them. This is why drones had to go.

**Comment by msgerbs** [comment]
This was dumb and removes yet another means of getting back into the round that isn't a stupid ghost role which gets boring after 2 rounds.

**Comment by Shadowflame909** [comment]
That was some pretty good poetry. But, this was still the worst solution ever. I'm positive admins won't be spawning drones anytime soon. Why hold your reputation at stake when a drone can easily mess up and you get flooded in OOC for "Admin why did you give that player drone? What a shitty move" 

This kinda has been proven and tested when admins accidentally give overpowered telecrystal trades. (Like blood crawl or Ash Drake form rip alphonzo)

**Comment by fludd12** [comment]
If it hasn't happened when I'm finished making crossbreeding and a few other things, I'll rework and readd drones.

**Comment by CosmicScientist** [comment]
@Shadowflame909 the worst solution is no solution. You're welcome to make a different solution.

**Comment by epochayur** [comment]
40 downvotes and it still gets merged
sounds about right

**Comment by KorPhaeron** [comment]
@epochayur take it up with the headmins, they didn't want to deal with the rules issues any longer

**Comment by Shadowflame909** [comment]
I'm guessing headmins wanted it because they didn't feel like putting in the time to change drone rules. The only difference between this and a straight removal is that the staff of change and the bardrone shuttle exists... TBH any bad drone problem could of been solved by removing "improve" in the drone rules. The good drones are the ones that never overstep there boundaries.

**Comment by CitrusGender** [comment]
I don't recall there being any vote or anything. It's possible oranges asked us separately? I guess I'm the 1/3rd headmin that didn't "approve it" since I was slightly against it (but I never voiced my opinion.)

**Comment by CosmicScientist** [comment]
Headminship is a sham! They control nothing!

Did you not get my discord @headmin ping?

**Comment by RogueSteampunker** [comment]
>inb4 citrus reveals that rustled is just arm wearing their skin, and conversing with oranges to get rid of drones

**Comment by msgerbs** [comment]
Aren't server policy issues generally supposed to be dealt with through server policy, rather than through code?

**Comment by optimumtact** [comment]
you all replied to this, not at the same time but over several days

**Comment by OmegaShoots** [comment]
port goon critters

**Comment by CitrusGender** [comment]
I think my response was that I didn't want to PR this.

I mean, it's no matter now.

**Comment by optimumtact** [comment]
I can taste the salt pouring out of your tears and it's pretty delicious.

This is a conversation for you to have with the two other headmins, both of who approved of the PR which was then signed off by the design lead

don't try to act like I have bypassed you in anyway, I asked all three of you in the open in the keyholders channel, you knew that I was polling the headadmins and frankly any failing here is on your part.

**Comment by CitrusGender** [comment]
You come out of the woodworks and immediately call me a liar because "you thought I voted for this" when you were wrong. You're just causing trouble here and it's obviously showing. Have some damn respect when you figure out you've messed up. I understand that I should have used more avenues to talk with them, but damn.

**Comment by PKPenguin321** [comment]
2/3 headmin votes means they totally can bypass you, that's just how it is

**Comment by optimumtact** [comment]
I called you a liar in a private channel, you don't need to lose your marbles in public over it.

Nothing here has been misrepresented

**Comment by CitrusGender** [comment]
@PKPenguin321 That's fine. I'm not really that concerned about that. What is done is done.

**Comment by optimumtact** [comment]
And just so we're clear here, I don't' appreciate you rocking up after the fact and casting aspersions about me acting in a shady manner or somehow in a rogue fashion on this PR.

If I wanted the drones gone I could easily have merged this without consulting you, there was plenty of maintainer backing for that line of action.

I asked all three of you in a channel you could all see in a single ping. I then posted publically on the PR that two of the three headadmins had approved the PR, you then had 2 days to show up and correct the record or discuss with your other headadmins before I managed to get a hold of Kor to get them to give final sign off.

I have acted completely above aboard and I resent having my actions questioned by someone who is clearly upset about the end result.

**Comment by CitrusGender** [comment]
You didn't even know which headmins approved it, you falsely said that I approved it before log searching to see that it was actually the other headmins.

**Comment by optimumtact** [comment]
you're clearly not handling this well, anyway, I'm sure if you ask your other headadmins they'll discuss it with you.

Code hasn't gone anywhere you can't get it back from

**Comment by Incomptinence** [comment]
oranges contain salt: fact

**Comment by optimumtact** [comment]
you dumb do research lol, you not so smarty pant incomp

**Comment by Incomptinence** [comment]
Increased accuracy the sodium free classification is actually a food ranking thing and they are actually just very low in sodium.

**Comment by CosmicScientist** [comment]
Don't put two citric fruits in the same bowl unless you want one juiced when you come back.

I should have waited longer before making that comic.

**Comment by epochayur** [comment]
>I can taste the salt pouring out of your tears and it's pretty delicious.

lol, jesus christ dude, it was a civil discourse until you came in with that
oranges yet again stirring shit, stretching the truth, and demanding respect he hasn't earned
countdown to this comment being deleted in 3... 2...

**Comment by cacogen** [comment]
civil
discourse

**Pull request merged**
