### PR TITLE
Adds another name to the list of first names.

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About The Pull Request

Adds the name Glizzy to the list of first names. The name Glizzy derives from the ancient Egyptian word for "stick".

## Why It's Good For The Game

I had a good friend that was beaten badly a couple of days ago named Glizzy. He's been very hard since then and I wanted to cheer him up by immortalizing him into one of his favorite games. Hopefully this will help him come out of his daze a little.

## Changelog
:cl:
add: Added the name "Glizzy" to the list of first names.
/:cl:

### CODE REVIEW

**Comment by dootdoom** [comment]
gee i wonder how this happened

**Comment by ExcessiveUseOfCobblestone** [comment]
Hope Glizzy is doing alright

**Comment by ExcessiveUseOfCobblestone** [comment]
Glizzy Bagsin

**Comment by dootdoom** [comment]
glizzo ito

**Comment by ZeWaka** [comment]
good change, it reminds me of my friend also named Glizzy who always had a knack for getting himself in tight spots

**Comment by unusualcrow** [comment]
please merge, it makes me very upset that i can't roll my real name

**Pull request closed without merging**
