### PR TITLE
Optimizations to SSmachines/fire() and its processes

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
might not be worth it since the results are smaller than id hoped so making the pr for feedback before i fully finish it. the main difference is the removal of machine/proc/auto_use_power() which is normally called for most machines by SSmachines. according to some profiling auto_use_power() took roughly 25% of SSmachines/fire() total_cpu, so now thats gone. 

auto_use_power() was unnecessary work since it was adding semi-constant power usage to its area just to remove it every fire(). now instead all machines remove and readd their constant power usage from their area after redefining power vars like use_power, active_power_usage and idle_power_usage, and power_channel with the help of updater procs. for example if you were to switch the power_usage var from IDLE_POWER_USAGE to ACTIVE_POWER_USAGE you would call update_use_power(ACTIVE_POWER_USAGE), otherwise the power usage wouldnt be updated

also goes over some of the more expensive machine process() procs like airalarms, and apcs for admittedly micro ops and slight code improvements

there is a small behavior change with this, currently apcs would still draw static power from a channel even if that channel is turned off, this cant work if 99% of power draw is in static power so now channels use zero static or dynamic power if shut down.

## Why It's Good For The Game
SSmachines seems to frequently require just over a single tick to complete on roundstart metastation, now it does so less

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
How bad is the comparison? You mention it being small?

**Comment by Kylerace** [comment]
@LemonInTheDark ill get a non shit profile when i get back home, but from profiles on my machine the biggest contributors to the total_cpu of SSmachine/fire() are: 20-25% auto_use_power() (which is gone), 15-20% apc/process(), 16-20% self_cpu, and 10-15% airalarm/process(). with the exception of auto_use_power() not much of what i did made a big difference as far as i can tell.

**Comment by MrStonedOne** [comment]
>auto_use_power() was unnecessary work since it was adding semi-constant power usage to its area just to remove it every fire(). 

IIRC the system was designed that way as otherwise things get denied power because they got processed before power generators like smes or rad collectors added power, and so making it two step kept this from being issue.

**Comment by Kylerace** [comment]
> 
> 
> > auto_use_power() was unnecessary work since it was adding semi-constant power usage to its area just to remove it every fire().
> 
> IIRC the system was designed that way as otherwise things get denied power because they got processed before power generators like smes or rad collectors added power, and so making it two step kept this from being issue.

hm, ill have to look for that then

**Comment by Kylerace** [comment]
@LemonInTheDark sorry that took a while my attempts of getting a squeaky clean profile fell through for some reason so the master profile has a grand total of 48 more machines in the processing list than the optimized branch (2000 for this branch, 2048 for master, so a tiny difference). master SSmachines had an average of 45.4 ms cost per fire() over 10 minutes, this branch had an average of 39 ms cost per fire() over 10 minutes

**Comment by LemonInTheDark** [comment]
Ok that's pretty alright, you still planning on doing that thing with air alarms?

**Comment by Kylerace** [comment]
yes

**Comment by LemonInTheDark** [comment]
Sweet

**Comment by Kylerace** [comment]
doing something more important, ill refocus on this when thats done since most of the work is already done

**Pull request closed without merging**
