### PR TITLE
Adds the Casino Emergency Shuttle

### PR DESCRIPTION
**Pull request by DAKKA-WAAAGH**
## About The Pull Request

A shuttle with an arcade, a bar, slot machines, roulette wheel, dining area, and various card tables. Also includes a pet daycare for the heads to bring their pets so they can have an extra layer of protection.

Also includes various random items such as hats, space cash, various coins, and cigars.

image

## Why It's Good For The Game

It's a larger than average shuttle for players to use in their getaway from the station while also keeping them entertained (who wants to sit in a seat for a few minutes?). The extra size should also help traitors with any unfinished objectives without attracting the attention of the entire crew.

## Changelog
:cl:
add: Casino emergency shuttle
/:cl:

_Sorry ahead of time if there are errors! First pull request to /tg/._

### CODE REVIEW

**Comment by Fikou** [comment]
From technicals:
You didn't mapmerge this map. You need to go into strongdmm settings and make it always turn map files into .tgm, and then save it.
From personal views:
I feel like the green/blue carpets are a bit too large, they shouldnt take over the entire floor
There is no airlocks or any other door thingy for the tables
This is another map with the jukebox, kind of stealing the gimmick of the rollerdome.

**Comment by DAKKA-WAAAGH** [comment]
> 
> 
> From technicals:
> You didn't mapmerge this map. You need to go into strongdmm settings and make it always turn map files into .tgm, and then save it.
> From personal views:
> I feel like the green/blue carpets are a bit too large, they shouldnt take over the entire floor
> There is no airlocks or any other door thingy for the tables
> This is another map with the jukebox, kind of stealing the gimmick of the rollerdome.

Woops, you're right I didn't mapmerge, thank you. I changed the setting and hopefully this works now.

**Comment by Iamgoofball** [comment]
The jukebox is fine, this is a full on casino floor. It's completely different from the rollerdome, IDK what they're talking about.

**Comment by wraith-54321** [comment]
is the revolver real? if so I feel that could cause some uh, problems

**Comment by DAKKA-WAAAGH** [comment]
> 
> 
> is the revolver real? if so I feel that could cause some uh, problems

No, it's a cap gun.

**Comment by godspeedfunnyman** [comment]
> > is the revolver real? if so I feel that could cause some uh, problems
> 
> No, it's a cap gun.

A Russian roulette revolver would be more fitting

**Comment by PowerfulBacon** [comment]
When I only unbox common in-flight service 😔

**Comment by Bawhoppen** [comment]
Needs more walls in my opinion. Main area is too open. Maybe like divide it into thirds, with the green sections being more isolated. Maybe could be a bit smaller too.

**Comment by Iamgoofball** [comment]
No, it looks fine as is. It's a casino floor. This is how they look. Have none of you seen a casino before?

**Comment by Bawhoppen** [comment]
I've never been to a real casino, but the impression I got from media is that there's atleast a few partitions between areas.

**Comment by Mothblocks** [comment]
CC @EOBGames @Maurukas

**Review by Maurukas — CHANGES_REQUESTED** [review]
A couple minor detailing issues:
In the command area, you've got some screens attached to corners, which get smoothed in game. This results in the screens clipping out of the wall. There is also a mis-rotated couch segment. The microwave is also clipping into the shuttle wall.
image

In the main compartment there's a fire extinguisher clipping into a light, and a mini-med on the same wall as a light (this just looks weird to me)
image



In the medical area you have a rogue sink that needs to be nudged up against the wall:
image

Other than these details, this looks fantastic. Reminds me of the small casinos you find attached to gas stations in rural Nevada. Get these details handled and hit the ready for review button when you are done.

**Comment by DAKKA-WAAAGH** [comment]
> 
> 
> A couple minor detailing issues:
> In the command area, you've got some screens attached to corners, which get smoothed in game. This results in the screens clipping out of the wall. There is also a mis-rotated couch segment. The microwave is also clipping into the shuttle wall.
> image
> 
> In the main compartment there's a fire extinguisher clipping into a light, and a mini-med on the same wall as a light (this just looks weird to me)
> image
> 
> In the medical area you have a rogue sink that needs to be nudged up against the wall:
> image
> 
> Other than these details, this looks fantastic. Reminds me of the small casinos you find attached to gas stations in rural Nevada. Get these details handled and hit the ready for review button when you are done.

Okay, I fixed the minimed, extinguisher, and microwave. The couch and sink are issues I'm not sure how to solve.

The sink isn't getting nudged properly on shuttle rotation and the couch is built correctly in the editor.

**Comment by DAKKA-WAAAGH** [comment]
image

**Comment by Maurukas** [comment]
You're correct. The couch thing is shuttle nonsense. Looks perfect.

**Pull request merged**
