### PR TITLE
Gives the janitor a bucket of paint remover

### PR DESCRIPTION
**Pull request by jughu**
THE BUFF THAT JANITORS DESERVED AFTER RAINBOW CRAYON COLORS TILES

:cl: Hyena
add: Adds paint remover to the janitors closet
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)because clown and his rainbow crayon!!

### CODE REVIEW

**Comment by WJohn** [comment]
WEE WOO WEE WOO FEATURE FROZEN EXPLAIN BUGFIX OR GET OUT

**Comment by jughu** [comment]
IT WOULDA HAVE WORKED IF IT WASNT YOUR MEDDLIN MAINTAINERS!

**Comment by KorPhaeron** [comment]
This should not be on the top of the pile, it's a very niche item

**Comment by jughu** [comment]
@KorPhaeron its moved down now just under the flashlight

**Comment by KorPhaeron** [comment]
Thanks

**Pull request merged**
