### PR TITLE
Small player-facing text improvements (2 pill bottles, 1 recycler note)

### PR DESCRIPTION
**Pull request by Pandarsenic**
Nothing special, honestly - exactly what it sounds like.

## About The Pull Request

- ~~Gravity Generator Volume is reduced from 40 to 20. If that's too much or too little, I'll do a no-GBP followup to tune it further.~~
- Two grammar fixes to pill bottles (missing spaces).
- A little grammar tuning on a note I'm pretty sure literally nobody ever reads, at any point, ever.

## Why It's Good For The Game

~~The gravity generator is too damn loud holy shit I'm going to die~~

~~Comparison, including a few common sounds (emitters, airlocks, punching a monkey, a bwoink) to help you get an idea of the relative volume:~~

Live, Volume 40
https://user-images.githubusercontent.com/101627558/171316990-ff8fe972-cadd-4ef0-bcbe-b7eebcd045e5.mp4

Updated, Volume 15
https://user-images.githubusercontent.com/101627558/171317648-a1aa1097-1c39-4e44-94c9-6c2ba040eb36.mp4

Just words fixes now but we might as well get them while we're here

## Changelog

:cl:
fix: Corrected a couple of trivial typos.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Do you have recordings of both sounds so we can see how it is?

**Comment by Pandarsenic** [comment]
> Do you have recordings of both sounds so we can see how it is?

Uploading to OP presently.

**Comment by LemonInTheDark** [comment]
15 does feel a little too quiet, hm

**Comment by Fikou** [comment]
the volume is not the issue its the range, at some point it got like fucking doubled because i can hear it from the main room of runtime station

**Comment by Pandarsenic** [comment]
> 15 does feel a little too quiet, hm

I'll try 20 and 25 and get short videos up tomorrow.

> the volume is not the issue its the range, at some point like a month ago it got like fucking doubled because i can hear it from the main room of runtime station

Other than that it definitely is also the volume because it's physically painful for me to pass over it as a ghost.

**Comment by Pandarsenic** [comment]
At Vol 18 while I do some other stuff on a local build.

https://user-images.githubusercontent.com/101627558/171499058-8231a863-b738-45d4-84ad-2b97aecf8577.mp4

**Comment by Pandarsenic** [comment]
Got distracted by things I do for money, will get those up shortly. Going to do the 18 I already added plus 21, 24 volumes, maybe. Maybe even 30, but I suspect way too loud on 30 still.

**Comment by Pandarsenic** [comment]
#67586 makes the gravgen part unnecessary, praise be (hopefully), so I'll kill that part and have it just be the grammar fixes shortly.

**Pull request merged**
