### PR TITLE
Roundstart Xeno egg deliveries create a Captive Xenomorph team, gives regular xenos a fluff objective so their popup isn't blank.

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

Xenomorphs who are a product of the roundstart xenobio egg delivery will now spawn as "Captive Xenomorphs", who receive an objective to break containment. Here's how it works:

When a delivery egg is generated that area will be marked as the "captivity area". Xenomorphs born within this area now have their own team, and have their own section in the roundend report that will greentext them based on if they were able to survive and escape captivity. Xenomorphs born outside of this area will spawn as normal Xenomorphs, with no escape objective or special fanfare.

To further encourage people from actually taking the role and potentially resigning themselves to an hour in Xenobio CBT prison, the first of the hive gets their own header on the roundend report. 

(When I say "team" here, I mean they receive a different antag team datum. They're still able to collaborate and cooperate with other Xenomorphs, they just have a different title and extra objective in addition to the bonus roundend report limelight.)

image

image

(This also adds a basic "survive and advance the hive" objective for all xenomorphs, since their objective popup was otherwise completely blank).

Since the captivity area is entirely dependent on the location of the egg itself, admins can plop one of these down anywhere, and mappers don't have to put the egg mapping helper specifically in Xenobio.

For clarification -- To be qualified for the Captive Xenomorph team, **a delivery egg must be spawned**, and the xeno you inhabit must be born in the same area the egg was spawned. If the queen breaks captivity and starts nesting elsewhere on the station, their children will be born as normal Xenomorphs, not Captive Xenomorphs. 

## Why It's Good For The Game

Adds a bit of distinction, and gives bragging rights, to anyone bold enough to take a roundstart xeno roll and escape with it.

The Xeno egg delivery is already rare enough, I think it deserves a bit more fanfare (especially considering the dramatic impact it sometimes has on the direction of a round). 

## Changelog
:cl:
add: Xenomorphs born in the room the roundstart delivery egg was spawned in will be part of a special "captive xenomorph" team, tasked with escaping and tracked in the roundend report.
fix: Regular Xenomorphs no longer receive a blank objectives popup on spawn.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
I love how the captive xenomorphs just started as a random rare spawner that Metacide added to their map, as a random side joke, and now it has a bunch of attention to it.

**Comment by moocowswag** [comment]
This pr doesnt put xenomorphs anymore at odds with sci than they already are when they are kept in captivity. Xenos tend to already want to escape their cell because.

1. Being stuck in captivity is very boring
2. Its cramped.
3. Someone *most likely who isnt even a scientist* will eventually try to grief sci by plasmaflooding the xeno pen along with the rest of xenobio because they dont know how gasses work and they think flooding someone else's department is a good way to learn.

If you were already going to let your pet xenos out and try to be friends with them this fluff objective will still be fluff.

**Comment by ATH1909** [comment]
> I can adjust the objective wording to be less direct, but ultimately they're just fluff objectives to be ignored by anyone with a creative spirit or a better idea.

I'm neutral here, but aren't objectives supposed to be taken seriously if you're a team antag (cultist, rev, etc.)?

**Comment by ZAMODA** [comment]
> I can adjust the objective wording to be less direct, but ultimately they're just fluff objectives to be ignored by anyone with a creative spirit or a better idea.

I feel like just adding (optional) in the objective text would solve some the f these issues would it not? I'm pretty sure that's happened with some other objectives before.

**Review by Time-Green — CHANGES_REQUESTED** [review]
I think it's fine to give the aliens something tangible to work towards and reward them with. The edge scenario of this crushing creativity is extremely rare in which case the queen can overrule it anyway. I agree with Willard but i think its still a net positive

**Pull request merged**
