### PR TITLE
Adds skeleton viro access to chem, reverts expanded medbay access

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request
During skeleton shifts jobs get access to most spaces within their department

## Why It's Good For The Game
Fixes an oversight in #43769

## Changelog
:cl:
fix: Chem has viro access during skeleton shifts
fix: Doctor, Chemist and Viro lost mutual expanded access.
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
@ExcessiveUseOfCobblestone Let me know if you want me to strip down some of the ``minimal_access`` from viro, chem, and doc.

**Comment by Angustmeta** [comment]
I believe this makes chemist always have viro access, just like the doctors and viros currently always have chemistry and viro access. The only extra access those three jobs currently get is genetics.

**Comment by RaveRadbury** [comment]
@Angustmeta https://github.com/tgstation/tgstation/compare/master...RaveRadbury:med_access_like_research

This is what it did. I tried to make highpop medbay act like highpop science. I left out a viro access for chemist. 

This PR may have been merged with a misunderstanding of what my intents were. So it might end up getting reverted, but the viro access during skeleton will stay, I think.

**Comment by Angustmeta** [comment]
Last PR changelog: 
`tweak: all medbay jobs have access to viro during skeleton shifts`

But what it really did was add viro to the doctor's normal access. Same as this PR does to chemist. Do I understand right?

**Comment by RaveRadbury** [comment]
tweak: all medbay jobs have access to viro during skeleton shifts
**tweak: chemist, doctor, and virologist share increased mutual access**
The bolded tweak was my intention, the other tweak was what I perceived to be an error in assigning skele access that I came across while doing the bolded thing.

And then my oversight was not adding skele viro to chem

**Comment by Angustmeta** [comment]
I think I understand what you mean now. It was your intention all along for viro to be accessable at all times if you're a doctor or chemist.

**Comment by RaveRadbury** [comment]
@Angustmeta yes, as this mirrors their sister-department: Science.

**Comment by ExcessiveUseOfCobblestone** [comment]
My intention was for these to be like other departments in that they share access **ONLY** in lowpop, and I had mix up the vars between access. Looks like I also misread the PR since I thought this was a bug rather than intended lol. I would have closed it if it was meant for normal pop.

These jobs should **not** be interchangeable in normal/high population by default.

**Comment by RaveRadbury** [comment]
Gotcha, making changes.

**Comment by RaveRadbury** [comment]
@ExcessiveUseOfCobblestone Ready to merge. Glad we cleared this up!

**Comment by ExcessiveUseOfCobblestone** [comment]
Going to quickmerge since this does something I very much do not want it to do (and I'm assuming downstreams who merged also believed it was flipped like me so let's rollout a quick fix).

**Pull request merged**
