### PR TITLE
Replaces the armory's laser guns with Mini Eguns

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl:
tweak: Armory laser guns replaced with Mini Eguns
add: Added Meta's contraband locker gun spawns to Box
/:cl:

mini eguns were added in #17472 but were pretty much forgotten.

they hold 6 laser shots or 3 taser shots.

after all **disablers hold just as many lasers as laser guns do, so lasers had no real purpose.**

wew a like from goofball i've really made it haven't I

**i almost forgot i also added meta's contraband locker spawner thing to boxstation**

### CODE REVIEW

**Comment by kevinz000** [comment]
STOP NERFING SECURITY

**Comment by Iamgoofball** [comment]
how is this a nerf it gives them 3 more 8 second stuns

**Comment by Tacolizard** [comment]
@kevinz000 when was the last time i nerfed sec

**Comment by TechnoAlchemisto** [comment]
Laser guns hold more lasers than energy guns. If anything the energy guns should be removed.

**Comment by kevinz000** [comment]
Tacolizard, your balance is shit you should realize that and not try to remove lasers from the armory so you can have your gimmick fit-in-pocket eguns.

**Comment by Tacolizard** [comment]
@TechnoAlchemisto as far as i can tell, that's just not true. The laser guns and eguns use the same stock battery, so they'd have the same number of shots.

**Pull request closed without merging**
