### PR TITLE
Reduces the export cost of Zauker to something more sane

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

I'm not entirely sure why someone thought 1050cr/mol was a good price, but turns out you can make Zauker pretty easily using the HFR once you know what you're doing.  tl;dr it's Hydrogen all over again.

## Why It's Good For The Game

Economy no break please

## Changelog
:cl:
balance: Centcom is now only paying 100cr/mol for Zauker, down from 1050.
/:cl:

### CODE REVIEW

**Comment by Timberpoes** [comment]
Ghilkermos goes brrrrrrr

**Review by Timberpoes — APPROVED** [review]
This is why we can't have nice things, and 100 is still nuts high compared to the other gasses too.

**Comment by TheVekter** [comment]
> 
> 
> This is why we can't have nice things, and 100 is still nuts high compared to the other gasses too.

Possibly but I want to try this first so it's still worth doing, if it continues to be a problem we can just nerf it again.

**Comment by Ghilker** [comment]
Oh yeah I forgot about this
This was a thing when Hypernob was 1000, but then I changed Hypernob and forgot about changing zauker
Thanks for catching it up

**Comment by Sethnov** [comment]
but zauker is suppose to be hard to make?

**Comment by TheVekter** [comment]
The problem is that, apparently, you can just cram a bunch of oxygen and nitrogen into the meme donut and it craps out a bunch of Zauker. This puts it at about the same level as Stimulum which is also moderately hard to make. If it ends up that people aren't using it enough, we can tweak it higher if need be, but as it is right now you can just print money with it which is verboten.

**Comment by ArcaneMusic** [comment]
Full approval, anyone making upwards of 100,000 credits with just gas is absolutely bad form.

I really don't have the technical grasp of atmos balance and fusion I'm afraid, so I'll defer to your judgement here.

**Comment by Sethnov** [comment]
> The problem is that, apparently, you can just cram a bunch of oxygen and nitrogen into the meme donut and it craps out a bunch of Zauker. This puts it at about the same level as Stimulum which is also moderately hard to make. If it ends up that people aren't using it enough, we can tweak it higher if need be, but as it is right now you can just print money with it which is verboten.

you mean adding proto nitrate to the donut to make zauker?

**Comment by LemonInTheDark** [comment]
> 
> 
> Ghilkermos goes brrrrrrr

~~I merged this~~

**Comment by LemonInTheDark** [comment]
> 
> 
> but zauker is supposed to be hard to make? and 100 is the same for Stimulum at least, for now, you still have to delam the hfr to get it, and zauker would feel useless now making the price go down. and its way much easier to make stimulum in hfr in higher quantities than zauker. plus its easier to make it in nonfusion way, rather than the HFR, i would also consider the time it takes to get zauker. or setting up the hfr and the prep for it.

This seems like more of an issue with zauker then anything else, tho I'm glad credits and such have meaning

**Pull request merged**
