### PR TITLE
nerfs throwing shit at electric grilles

### PR DESCRIPTION
**Pull request by Supermichael777**
Because it seriously makes them a joke.

### CODE REVIEW

**Comment by Zilenan91** [comment]
no

**Comment by lzimann** [comment]
are we in the "nerf everything" phase

**Comment by Bawhoppen** [comment]
:-1:x:100: don't be autistic, really

**Comment by Cheridan** [comment]
better fix: hitting an electrified grill with an item causes a shock to arc off and hit whoever is closest.

**Comment by lzimann** [comment]
but that doesn't even make sense

**Comment by Supermichael777** [comment]
two throws of a fire extinguisher to eight throws.

**Comment by Shadowlight213** [comment]
Cheridan's idea is best. Do that.

**Comment by Bawhoppen** [comment]
cheri's idea would be the most fun, just making it take a few extra hits would be the most sane

**Comment by Cheridan** [comment]
fuck yeah

**Comment by Lumipharon** [comment]
This makes no sense but ok.

**Comment by Zilenan91** [comment]
There's no reason to buff shocked grilles to that ridiculous of a level.

**Pull request closed without merging**
