### PR TITLE
Tramstation Department Swap

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request

Swaps the Security and Service wing around entirely, including some new maintenance sections. Also makes the asteroid rock leave behind breathable flooring to incentivize digging tunnels through it.

## Why It's Good For The Game

Makes it so that each wing has at least one gameplay-important department attached to it so there are equal reasons to go between each wing fully instead of just mostly the last two.

## Changelog

:cl: MMMiracles
add: Tramstation's Security and Service wing has been flipped around.
add: Tramstation's commissary has been placed above in the central wing beside the kitchen.
add: Tramstation's EVA and Gateway rooms have been adjusted. EVA now has one extra suit storage unit.
add: Tramstation's maintenance near the Service and Security wing has had reworked layouts.
add: Tramstation's asteroid now leaves behind breathable turfs so digging out a room isn't as tedious.
/:cl:

image
image

### CODE REVIEW

**Comment by tralezab** [comment]
wow!

**Comment by wesoda25** [comment]
:( it's gonna be even harder for sec to get around and respond now.

**Comment by Fikou** [comment]
yummy

**Comment by GoldenAlpharex** [comment]
Now if you could make it so the bridge could see the Tram, instead of the HoP, now we'd be talking.

**Comment by Maurukas** [comment]
First review done. Here's a big pile of minor fixes:

The vault now extends past the floor on the level above. This exposes it to space and creates roundstart active turfs:
image

This APC terminal is unwired outside the bar:
image

The vacant commissary APC is unwired:
image

Prison garden has vents and scrubbers, but no air alarm
image

Prison work area needs an APC:
image

Prison shower has an APC and atmos hookups, but no air alarm. Also a shameful lower right corner: 
image

Captain's private quarters are a seperate area, but have no APC:
image

Gateway has an area and atmos hookups but no air alarm:
image

**Pull request merged**
