### PR TITLE
Typepath fix on the bear virtual domain

### LINKED ISSUE #83920: Pizza Party bitrunning sim issues
Reporting client version: 515.1637

## Issue Summary
The newest bitrunning sim,  ̶F̶i̶v̶e̶ ̶N̶i̶g̶h̶t̶s̶ ̶a̶t̶ ̶I̶a̶n̶s̶  Pizza Party, has two potential issues.

1. The second door in the sim, between the dirt floor room and the security office, just fucking vanishes when you open it. No animation, just pops out of existence.
Screenshot 2024-06-12 143524

2. There's a bear mask in the locker to the left of the office. The mask that got placed there is the CURSED version wizards can summon, and glues itself to your hand if you pick it up. Not sure if it's a big or not, pretty funny if it's a prank not gonna lie
Screenshot 2024-06-12 143611

## Round ID:
[230436](https://scrubby.melonmesa.com/round/230436)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Mouse drag & drop refactored attack chain](https://www.github.com/tgstation/tgstation/pull/83690)
- [Ctrl click refactor](https://www.github.com/tgstation/tgstation/pull/83784)

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

This changes the spawn door on the FNAF bitrunner map to be an /obj/machinery/door/airlock instead of a /obj/machinery/door, fixing it disappearing when opened.

~~The bear mask no longer sticks to your hand~~ (confirmed as intentional by map developer. How EVIL!)
## Why It's Good For The Game

Closes #83920.
## Changelog
:cl: Rhials
fix: Fixes a door in the Fredington Fasting Bear Five Nights and Fnafbears map.
/:cl:

### CODE REVIEW

**Comment by munchyi** [comment]
it was intended! also thanks i was getting some issues couldnt fix myself

**Comment by munchyi** [comment]
this was the issue if you are wondering https://cdn.discordapp.com/attachments/1247938029885325365/1250753150047227905/image.png?ex=666c1624&is=666ac4a4&hm=9cfdfa0f4e495d97a1e10bbb82b053d4f40c034c2953272b4a054dd2ab3de35f&
i couldnt test it

**Review by jlsnow301 — CHANGES_REQUESTED** [review]
Please replace the advanced security camera as well. This is easily meta gamed as they can just boot the vdom and view the station.

Bit of a bikeshed but the map could use some more cache spawns

**Comment by Rhials** [comment]
Alright, I've swapped the cam console with a laptop. It shouldn't be a problem since it shouldn't be able to connect to NTOS.

I've also thrown in 2 more bitrunner spawns in the empty areas of the map.

image

**Comment by Rhials** [comment]
Dang why is Mapdiffbot tweaking?

**Pull request merged**
