### PR TITLE
adds chameleon belt to chameleon kits

### PR DESCRIPTION
**Pull request by improvedname**
for the full STEALTH experience

:cl: improvedname
tweak:chameleon kits now include chameleon belts
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.) full chameleon experience

### CODE REVIEW

**Comment by BlueNothing** [comment]
Can they hold anything?

**Comment by improvedname** [comment]
they are like rig webbings they hold all small objects

**Comment by Shadowflame909** [comment]
1. What you're not sawrge

2. Nice, they needed something after chameleon guns got removed.

**Comment by improvedname** [comment]
oke i need to get the thingy... darn it cyber...

**Comment by Shadowflame909** [comment]
nooooooooooooo

**Pull request closed without merging**
