### PR TITLE
Fix quirks list in preferences menu being empty before SSquirks

### LINKED ISSUE #61490: Quirks menu is empty when someone opens the preferences menu before SSquirks is initialized

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Fixes #61490

## Changelog

:cl:
fix: Fixed the quirks list in the preferences menu sometimes being empty.
/:cl:

### CODE REVIEW

**Comment by Burgermancoding** [comment]
CERTIFIED POGGERS MOMENT

**Comment by Mothblocks** [comment]
wait i didnt actually
i didnt actually make prefs use it hold on

**Review by Timberpoes — CHANGES_REQUESTED** [review]
It seems strange that the only way to populate quirk_blacklist is to initialise the SS when it's basically a constant. Would it be a good idea to pull the list for quick_blacklist into the proc's var definition so it's always available alongside get_quirks(), even if the SS hasn't Initialised yet?

I don't think there's a current issue where get_quirks is called in a code path relying on quirk_blacklist being generated, but the implication of calling get_quirks at any time even when the SS hasn't initialised would indicate to me that the blacklist should probably be generated then too.

**Comment by Mothblocks** [comment]
sure, the fact SSquirks exists as anything other than a namespace is pretty junk anyway

**Comment by Mothblocks** [comment]
Yeah, it would've had the same problem, good catch--I made it a static list.

**Pull request merged**
