### PR TITLE
You can now recolo(u)r lightbulbs

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Makes lights shine in a different color if you recolour them.

## Why It's Good For The Game

Whoever created the rapid lighting device intended for this to be a feature but it just didn't work. I'm not seeing a reason why this shouldn't be a thing. Feels very natural.

## Changelog
:cl:
add: Colored lights now shine in different colours.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Time to make all the lightd in kilo be a sickly blue and orange for that real dystopic hellscape.

**Comment by Tlaltecuhtli** [comment]
black light?

**Comment by nemvar** [comment]
Black light isn't real and can't hurt you.

**Comment by Barhandar** [comment]
Blacklight should slow down viruses. Since we don't have bacterial contamination of stuff (yet).

**Comment by nemvar** [comment]
'Black light' is literally darkness. What else do you expect when you use a black spraycan on a light fixture?

**Comment by ATH1909** [comment]
> 'Black light' is literally darkness. What else do you expect when you use a black spraycan on a light fixture?

But is this darkness as in "the light isn't on" or darkness as in "like a shadowshroom"?

**Comment by nemvar** [comment]
The light isn't on.

**Pull request merged**
