### PR TITLE
Cream pie map edits

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: Added the cream pie closet to various maps. Added contraband Cream Pie Crate to Cargo.
/:cl:

Each closet contains one cream pie. At least it's better than the empty lockers the clown had before, and they're lockable. #stealthclownbuffs

Box
Metastation
Efficiency
Dream

### CODE REVIEW

**Comment by Mercenaryblue** [comment]
I did ask for this. Honk!

**Comment by PKPenguin321** [comment]
these rape nuke ops by the way

**Comment by Mercenaryblue** [comment]
Allright. I did ask for one pie at theater for the clown.
The crate is contraband, that's fine.
But the new closet? Too easy. Have kitchen bake them.

**Comment by coiax** [comment]
...editing maps is HARD. Change to just one pie per closet?
 Styling with Markdown is supported
Comment Close and comment

**Comment by Mercenaryblue** [comment]
Basically, Meta and the other stations already had a banana cream pie for the clown. Not Box. I wanted to fix this. This, plus the Cream Pie at the bar, should be enough to start with.

**Comment by Supermichael777** [comment]
box should have one at the bar

**Comment by coiax** [comment]
But Box already has one at the bar.

**Comment by Mercenaryblue** [comment]
One pie per closet is more balanced.

**Pull request merged**
