### PR TITLE
Converts DCS from PascalCase to under_score for consistency

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Does as it says on the tin, components, elements and signals have been converted from PascalCase to under_score.

Forgive me if I'm wrong, and I may be, but I didn't see any reason we were using PascalCase here.

Changes circuits add_component to add_circuit_component.
Changes circuits load_component to load_circuit_component.

## Changelog

Not player facing.

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
RegisterSignal isn't camel case

**Comment by Mothblocks** [comment]
It's time for a merge skew moment

**Comment by Mothblocks** [comment]
Have fun with ur conflicts

**Comment by Gandalf2k15** [comment]
watch me fix it

**Comment by Gandalf2k15** [comment]
I used surgical precision, these mundane github action limits will not stop me.

**Comment by LemonInTheDark** [comment]
Prove to me that you are serious and I will consider letting you live

**Comment by timothymtorres** [comment]
Even though style isn't strictly enforced... if you look at a lot of files for the repo you notice a pattern where var names for objects are *mostly* in under_score.  ALLCAPS is mostly defines and constants.  For proc names there is quite a mixture of PascalCase and under_score that were created by the players.  However the [DM reference docs](https://www.byond.com/docs/ref/) use PascalCase exclusively for the procs inherited by any type of object, except for global level procs that aren't inherited by anything which use under_score.  It'd be nice to have a universal consensus otherwise it's just going to be a refactor tug-of-war with naming conventions.

**Comment by Time-Green** [comment]
Removes soul from the code 😔

**Comment by timothymtorres** [comment]
> The dm reference has nothing to do with what we base our naming convention on, the style guide says proc names are snake case, simple as.

[Nowhere does it say that.](https://github.com/tgstation/tgstation/blob/master/.github/guides/STYLE.md)

If the var names are overwhelming `snake_case` then it makes absolutely no sense to have your proc names do that as well.  The whole point for using different styles is to help differentiate between functions/procs/vars/objects/etc at a glance.  

While you don't have to follow a programming languages programming style pattern, it's definitely recommended in a lot of languages.  Some even go as far to enforce it via being a strong-typed language vs a loose-typed language.  Things like tabs are strictly enforced and require everyone to use the same style pattern.

**Comment by Gandalf2k15** [comment]
After discussing this in maintainer chat, will remake this if we decide to go down this route.

**Pull request closed without merging**
