### PR TITLE
Lowers instaflesh's toxicity

### PR DESCRIPTION
**Pull request by Anonmare**
## About The Pull Request
Instabitaluri's toxicity keeps it from being an effective medication choice as the toxicity is simply too high to be worth it, as toxin damage is simply more painful to treat than brute/burn is.

## Why It's Good For The Game
Makes instabitaluri a more attractive medication option and worth the price tag it has in the nanomed.

## Changelog
:cl:
balance: Nanotrasen have refined instabitaluri's formula to be less toxic to living tissue.
/:cl:

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
isnt the point of cobbychem to encourage people to using surgery instead of chems? i think its as good as it is now, since its a bit harder to make than of the other healing chems

**Comment by tmtmtl30** [comment]
i thought the main point of it was to efficiently prep bodies for surgery

**Comment by Tlaltecuhtli** [comment]
maybe instead of adding tox damage give it some shitty poison like histamine?
so you can defib someone at 400dmg but then you have to deal with histamine and other kind of poisons

**Comment by gryffinp** [comment]
> maybe instead of adding tox damage give it some shitty poison like histamine?

This just amplifies the problem: "multiver" deals lung damage now, which is extremely hard to treat if the lung goes into crit, and calomel deals massive amounts of toxin damage, which just brings us back where we started. Removing poison reagents from a body is even worse than trying to fix toxin damage these days.

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> i thought the main point of it was to efficiently prep bodies for defibrillation

it's the only reason it's kept in.

**Comment by wesoda25** [comment]
Cobby chem worked tho, even with tox damage lowered tend wounds will forever be preferable to synflesh. Encouraging hands on methods (surgery) before chem alternatives was really the entire point.

**Comment by optimumtact** [comment]
honestly cobby i cannot figure out if you want the change or not, so this is a guess.

**Comment by ExcessiveUseOfCobblestone** [comment]
this is fine

**Comment by optimumtact** [comment]
i hate you

**Pull request merged**
