### PR TITLE
Removes synth species

### LINKED ISSUE #21751: One of the wizard race options from the magic mirror makes them invisible.
It was Synth

### PR DESCRIPTION
**Pull request by Shadowlight213**
Synth sprite is completely broken since dismemberment, and it pretty much always has been buggy and barely working.
Closes #22647 
Fixes #21751

:cl:
del: The synth species has been removed
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
DONT REMOVE FIX!

**Comment by jughu** [comment]
>is it so hard to remove race coloring from synth

**Comment by Shadowlight213** [comment]
Synth code was always basically held together with black magic and duct tape. Never fully worked right.
I have 0 clue how to fix it. I probably should remove the species tbh,

**Comment by jughu** [comment]
Ok remove the black magic then

**Comment by Supermichael777** [comment]
I DON'T KNOW HOW TO FIX CAR REMOVE CAR FROM ROAD. 

Though i had plans for synth it got copted by a bunch of fallout 4 nonsense.

**Comment by lzimann** [comment]
Consider the person could get invisible by selecting synth race, it's a good use of tag.

**Comment by KorPhaeron** [comment]
Someone fixed it

**Comment by Shadowlight213** [comment]
Said PR only fixes the bug caused by dismemberment.
The breaking of the traits upon cloning, and incorrect layering of the human sprite above the metal one still exists

**Comment by optimumtact** [comment]
I agree with shadow, these are broken and have been for ages because people don't actually care about them

**Comment by Shadowlight213** [comment]
I'm not? As I said before, the overlay for the sprites, never sat completely correctly. You'd have the edge of the skeleton sticking out from the side of the head or something.

**Comment by RemieRichards** [comment]
That was intentional.

**Comment by Shadowlight213** [comment]
No it wasn't. Don't try to lie.
I know it wasn't, because there's be instances where it didn't occur. Then something would trigger it, and it would be slightly off-center. What you're thinking of is the DAMAGE system, where if they got damaged, it caused the skeleton part to show through once they got below a certain threshold.

**Comment by RemieRichards** [comment]
If you're talking about my original implementation, that used Bay's IPC sprites, then yes, it was intentional, and the times they popped out vs. when they didn't? was based on the health of the synth, it was literally a mechanic you.

The sprite "fit" before the damage because it wasn't displayed, and when they were damaged they popped out and it *was* intentional, you literally don't get to decide what is or isn't intentional about something I did, I explained why everything was the way it was when I made them, guess you just didn't listen.

**Comment by Shadowlight213** [comment]
It was occurring even when they weren't damaged, but fine whatever. You're right. It was all intended and worked perfectly. I apologize for ever doubting.

**Comment by Supermichael777** [comment]
looks like the synth needs a diet

**Pull request closed without merging**
