### PR TITLE
Gauze can now be applied to corpses

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
title

## Why It's Good For The Game
buffs antags, get gauzed after being beaten and then dragged into a locker in a corner of maint

Okay, real reason now. Allows you to gauze somebody's corpse because its handy to keep a patient's corpse intact for defibbing before Newfiend Mcdoctor steals the corpse off you and drags it across the station and causes the person to lose like half their blood while dead.
## Changelog
:cl: SuicidalPickles
tweak: Rolls of gauze now works on corpses.
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
>buffs antags, get gauzed after being beaten and then dragged into a locker in a corner of maint

just drag the locker smh

**Comment by bgobandit** [comment]
since these are basically mummies, can you also remove their brain through the nose with a crowbar

**Comment by nemvar** [comment]
The application code for medical stacks is so ugly, hopefully someone will eventually come down from the heavens and rewrite the entire thing.

**Comment by zombiegums** [comment]
Very good change.

**Pull request merged**
