### PR TITLE
Adds the dmm2tgm converter to MapMerge

### PR DESCRIPTION
**Pull request by CorruptComputer**
Instead of re-coding it @RemieRichards gave me a version that takes input.

Disclaimer: May break.

### CODE REVIEW

**Comment by RemieRichards** [comment]
:+1: Love it.

**Comment by CorruptComputer** [comment]
Vote: Should the dmm2tgm converter be a .exe? This would mean you don't have to have python installed, but you could only use it on windows. If left as a .py you can use it on any OS that python supports, but you need to have python installed.

**Comment by Razharas** [comment]
I vote exe
People who use linuxes are proficient enough in the CS to make it work on their systems anyway

**Comment by RemieRichards** [comment]
Said this in IRC but I'd like to push for both.
I didn't make the EXE for nothing, and the only thing stopping us using both is a once per download extra of 2MB, it affects people with the source code and nobody else, the players aren't disrupted.

Original .py + EXE

**Comment by Cheridan** [comment]
Yeah, I don't see why we can't just have both.

**Comment by CorruptComputer** [comment]
Will do, after I get home.

**Comment by CorruptComputer** [comment]
Now it will try the .exe and if that fails it will fall back onto the .py and if that fails you are doing something wrong with your life.

**Pull request merged**
