### PR TITLE
Small fixes to asteroid!

### PR DESCRIPTION
**Pull request by lzimann**
Ok, third time is a charm. HOPEFULLY I didn't mess up anything once again!
Just some small fixes. I'll soon update the atmos area.

### CODE REVIEW

**Comment by WJohn** [comment]
Man please use the map merger in the future, it's not hard to do. Use prepare maps, edit your map, save, then use run map merger. Type in how many files you've edited, then type in the number of the file you've edited, shown on the list it provides, and *then* you commit.

**Comment by lzimann** [comment]
But I did use it. I used it wrong then?

**Comment by GunHog** [comment]
This is part of why I do not do mapping...

**Comment by Bawhoppen** [comment]
do relics spawn on ass station, if not add them

**Comment by Jordie0608** [comment]
@WJohn File name was changed and it seems git hasn't pick up on it.

**Pull request merged**
