### PR TITLE
Fixes briefcase launchpads having no power when being in an area that does

### LINKED ISSUE #66351: bluespace briefcase launchpad refuses to work
## Round ID:
[181899](https://scrubby.melonmesa.com/round/181899)

## Testmerges:
#66220 

## Reproduction:
buy a briefcase launchpad
set it up in a powered area
try to use it with the folder remote
ERROR: Launchpad not operative. Make sure the launchpad is ready and powered.
regular launchpads work just fine however

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
See title.

So, here's why this bug occurs in the first place:
- Step 1: The launchpad is spawned in nullspace "to hide it from briefcase contents"
- Step 2: /obj/machinery/LateInitialize() calls powerchange()
- Step 3: powerchange() calls powered(power_channel)
- Step 4: /obj/machinery/proc/powered returns False since its in nullspace, and there can't be power in nullspace
- Step 5: machine_stat is set to NOPOWER
- Step 6: LateInitialize() doesn't call setup_area_power_relationship() because use_power is set to NO_POWER_USE
- Step 7: This causes machine_stat to not be changed even when the launchpad is deployed

Now, why did this not cause an issue prior to #66059, well, before it, the briefcase launchpad was set up in a hacky way where 
idle_power_usage and active_power_usage were overrided to be 0, but use_power was still IDLE_POWER_USE, which cut off the chain at Step 6, but now, use_power is properly set to NO_POWER_USE which in due to this one specific chain of events actually breaks things.

UPDATE: Also makes briefcase launchpads not drain power because it doesn't make sense for them to drain power if they work without power anyways

## Why It's Good For The Game
Fixes #66351 , makes briefcase launchpads actually function.

## Changelog

:cl:
fix: Briefcase launchpads now work again.
fix: Briefcase launchpads now don't drain power from the station.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
do they work in unpowered areas now?

**Comment by RandomGamer123** [comment]
> do they work in unpowered areas now?

After some testing, yes they do, uh I don't actually know if this is intended that briefcase launchpads work in unpowered areas

**Comment by MrMelbert** [comment]
I'm not sure if this is the right fix - 
Maybe instead, 
```
/obj/machinery/launchpad/proc/isAvailable()
	if(machine_stat & NOPOWER)
		return FALSE
	if(panel_open)
		return FALSE
	return TRUE
```
When a launchpad checks that it's available, check if `use_power = NO_POWER_USE` to skip the `NOPOWER` check?
And also set the biefcase launchpad's `active_power_usage` and `idle_power_usage` to 0?

I'm not even sure if that's the right alternative but I don't think the current solution is right either so

**Comment by RandomGamer123** [comment]
> I'm not sure if this is the right fix - I don't even know _when_ the briefcase launchpad was changed to use power because I recall it always working in unpowered areas like space
> 
> Maybe instead,
> 
> ```
> /obj/machinery/launchpad/proc/isAvailable()
> 	if(machine_stat & NOPOWER)
> 		return FALSE
> 	if(panel_open)
> 		return FALSE
> 	return TRUE
> ```
> 
> When a launchpad checks that it's available, check if `use_power = NO_POWER_USE` to skip the `NOPOWER` check? And also set the biefcase launchpad's `active_power_usage` and `idle_power_usage` to 0?
> 
> Either that, or set it up after it's deployed?
> 
> I'm not even sure if that's the right alternative but I don't think the current solution is right either so
> 
> image

They work in unpowered areas, but they also consume power upon usage if they're in an active area which is the strange part, I'll probably override isAvailable to just remove the machine_stat check

**Comment by MrMelbert** [comment]
> They work in unpowered areas, but they also consume power upon usage if they're in an active area which is the strange part, I'll probably override isAvailable to just remove the machine_stat check

It sounds like a bug to me that they consume power sometimes but don't need power

**Comment by tralezab** [comment]
thank fuck they don't take power anymore this is so SCHTEWPID

**Comment by tralezab** [comment]
(thank you for just killing active power use meme)

**Pull request merged**
