### PR TITLE
>100u CLF3 foam >Burned a single tile

### PR DESCRIPTION
**Pull request by Iamgoofball**
haha NO
:cl: Iamsaltball
rscadd: Buffs CLF3 VS tiles.
/:cl:

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
it's powerful as shit in smoke it's just the foam

**Comment by pudl** [comment]
another untested pr by goof "the wang" ball

**Comment by Iamgoofball** [comment]
excuse me i identify as dong and this triggers me

**Comment by pudl** [comment]
fixed sorry

**Comment by Dorsisdwarf** [comment]
Oh look, goofball messed up his own stuff again

**Comment by MMMiracles** [comment]
wouldn't it actually be a 'didn't ded' tag if he's buffing it

**Comment by phil235** [comment]
It's funny, goof, because you're the one who broke foam....
I'll report the comment I made in your PR https://github.com/tgstation/-tg-station/pull/16357

>@Iamgoofball
This renders the foam's reagent reactions basically useless. In order to avoid duplicating reagents, the amount that reacts during each processing cycle is the total volume divided by the total lifetime, so that the sum of all the reactions that happen is equal to the volume put in the foam.
With a lifetime of 40, it means that instead of having 6 reaction of Volume/6 , we now have 40 reaction of Volume/40.
The issue is that the foam reagent reactions use the VAPOR method which check for clothes protecting the mob's skin. reaction_mob() is currently using a threshold (https://github.com/Iamgoofball/-tg-station/blob/68e752b46153e32d116d7a0d916de5c7c1ca199c/code/modules/reagents/chemistry/reagents.dm#L40) because even bio suits don't give a 100% protection so we need the threshold to not have small reagent amounts still reacting with the mob wearing a bio suit.
Now that you divide the reaction amount by 40 instead of 6, it means that any foam reaction with less than 20u of a given reagent won't have any effect, even on naked humans (and you probably need 40+ unit for people with just jumpsuits and shoes)
Another effect is that reagent reaction that gives a message to the mob will now spam the mob with 40 messages in a very short time.(styptic powder or condensed capsaicin foam for example, or worse a strange_reagent foam would spam every observer with 40 messages for every suicided human in the foam)

**Comment by Iamgoofball** [comment]
yup, but I didn't think it would be this badly broken

then i tried playing it

its all over all dead no hope

**Comment by phil235** [comment]
I'm closing this, since the real issue has nothing to do with clf3.

**Pull request closed without merging**
