### PR TITLE
Updates scrubber sprites and animation

### PR DESCRIPTION
**Pull request by Partheo**
## About The Pull Request

This PR is part 2 of the vent update I did a while ago: https://github.com/tgstation/tgstation/pull/43630
I have updated the scrubbers, which I think were terrible, to a better design that matches the style of the vents sprites, and without the graphical errors of the current scrubber.
image

Overall it is a bit easier to see what the scrubber is doing- there are now clear differences between on, expanded, and scrubbing mode, besides just a color change(which is what the current design does).

## Why It's Good For The Game

The scrubbers now match the vent sprites and have greater visual clarity.
The current design is also terrible; these are somewhat better.

## Changelog
:cl: Partheo
imageadd: Scrubbers have updated design and animation
/:cl:

### CODE REVIEW

**Comment by nicbn** [comment]
Make the lateral lights position not depend on orientation please

**Comment by ExcessiveUseOfCobblestone** [comment]
Would be nice to have a single light that signals where the machine plugs into so you don't have to play crowbar scratchoff

**Comment by actioninja** [comment]
SOULLESS

**Comment by HomocidlePancakes** [comment]
Tray scanner cobblenerd

**Comment by Partheo** [comment]
@nicbn I really would like it to be this way, mainly because it significantly reduces the redundancy of the .dmi file. When I first created the new vent/scrubber sprites(https://github.com/yogstation13/yogstation/pull/2729), they only had one orientation and only the pipe attachment overlay would change direction.

However, https://github.com/tgstation/tgstation/pull/34037 was merged over a year ago which added the other directions for the vents and scrubbers. When I asked ShizCalev why it was done, the response I got was that having a single orientation is an issue that had to be fixed.
image
image
Because of this, I assume they will have to stay this way.

---
@ExcessiveUseOfCobblestone no clue what you're referring to. Do you mean where the pipe connects to the scrubber? There's an overlayed joint sprite between the connecting pipe and the scrubber that is visible if you crowbar the tile.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Tray scanner cobblenerd

let me bikeshed in piece jerk

**Comment by RaveRadbury** [comment]
What does the scrubber look like when siphon _and_ expanded?

**Comment by ExcessiveUseOfCobblestone** [comment]
the same as normal range siphon

**Comment by Partheo** [comment]
@RaveRadbury 
It makes no difference to a siphoning scrubber whether or not it is on expanded mode, so it doesn't have a sprite for expanded + siphoning as it is functionally identical to just siphoning.

**Pull request merged**
