### PR TITLE
Adds Cargo Lobby Area Turfing (Lobby it Up!)

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hello there,

Take a look at this photograph:

image

This hall is MASSIVE. Look at that area, even though it's not exactly part of the hall, we count it like that anyways. Since the purpose of that area is for visitor to cargo to wait for their orders, let's supplant it under them. Let's fix this by adding a new area turf and map it in on DeltaStation, as well as the two other maps that have the "lobby" areas (IceBox and Tram).

## Why It's Good For The Game

image

Helps deblobbify some chunky areas we have across the maps, and help things be a bit more locatable.

## Changelog

:cl:
add: On DeltaStation, IceBoxStation, and TramStation: Nanotrasen has now blocked off the area informally known as the "Cargo Lobby", and formally defined it.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by san7890** [comment]
> Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.
> 
> Your current title and or body content does not meet requirements, so please update it.

Better?

**Comment by optimumtact** [comment]
yeah

**Review by Twaticus — APPROVED** [review]

**Comment by Son-of-Space** [comment]
I haven't gone in to check yet, but friendly reminder to make sure that any new area you make has an auto APC, air alarm, fire alarm, etc.

**Comment by san7890** [comment]
> I haven't gone in to check yet, but friendly reminder to make sure that any new area you make has an auto APC, air alarm, fire alarm, etc.

image

I know. I only forget sometimes.

**Review by Maurukas — CHANGES_REQUESTED** [review]
Delta cargo lobby is missing an air alarm.

Otherwise looks good.

**Comment by san7890** [comment]
I know it's fun to pick on Kilo since it has a cramped design, but I am of the belief that trying to add anything on the walls of DeltaStation are just as, if not more, of a laborious task.

**Pull request merged**
