### PR TITLE
Cargorilla Drip

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Some FUNNY MAN decided to put this poor, innocent gorilla into an ill-fitting costume.
image
Branding them for his amusement.
image
As if to JEST them, they even gave him a little hat.
image

## Why It's Good For The Game

It's funny, a good sprite and the Cargorilla is now uniform with the Department.

## Changelog

:cl: Cursor, sprites by Crumpaloo.
imageadd: The Cargorilla has found clothing in their size.
add: Updated the Cargorilla's description to match their new look.
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
image

**Comment by githubuser4141** [comment]
Looks nice, but what's the humor behind the brand? I'm guessing it's a reference but I'm pretty bad with references.

**Comment by theselfish** [comment]
> Looks nice, but what's the humor behind the brand? I'm guessing it's a reference but I'm pretty bad with references.

I'm unsure. The spriter put it in "because it's funny".

**Comment by MrDoomBringer** [comment]
the brand is needlessly cruel smh gorillas rights

**Comment by gamefreak2998** [comment]
How do you actually obtain the suit for the gorilla?

**Pull request merged**
