### PR TITLE
adds Jacquerel and I to codeowners for basic mobs

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

i typically get pinged for these anyways since these refactors typically touch maps but i keep missing out on notifications relating to these which i'd really rather have

also jacquerel wanted in too so he's in too

### CODE REVIEW

**Comment by Rhials** [comment]
I nominate Ben10Omnitrix to be included in this as well

**Comment by san7890** [comment]
he can add himself

**Comment by MrMelbert** [comment]
Probably remove Arm while he's on break

**Comment by san7890** [comment]
ehhhh there's lots of MOA codeowners, i think standing policy is to just keep people on until they opt out

**Pull request merged**
