### PR TITLE
sidetail 4 sprite change

### PR DESCRIPTION
**Pull request by ghost**
just a small inconsistency with this sprite i normally like quite a bit

normally the south-facing hair looks like this:
ss 2015-02-11 at 04 29 48

but the west facing sprite looks like this
ss 2015-02-11 at 04 30 36

so i made it look like this instead to be consistent and look less like ass
ss 2015-02-11 at 04 29 37

that's all

### CODE REVIEW

**Comment by WJohn** [comment]
:+1: x :100:

**Comment by Thunder12345** [comment]
While you're at it, can you try to make the back look less ass?

**Comment by paprka** [comment]
i did a little, yes

**Comment by MrSnapwalk** [comment]
;_;
feelings hurt 4ever
(In all seriousness, :+1:)

**Comment by paprka** [comment]
snap your sprites are gud m8 but some of them need a bit of touch-ups that's all

**Comment by TZK13** [comment]
>Using female sprites for example pics.

**Comment by paprka** [comment]
..why not?

**Comment by TZK13** [comment]
>this sprite i normally like quite a bit

It was a joke, now that I have to comment again to clarify I'll also say that I approve of this change. :+1:

**Pull request merged**
