### PR TITLE
Maint Tunnel Clown!

### PR DESCRIPTION
**Pull request by ACCount12**
Added maint access to mime and clown. Why? Because fun, that's why.

### CODE REVIEW

**Comment by Jalleo** [comment]
Config'd?

**Comment by ACCount12** [comment]
It would work only if extended crew access is on.

**Comment by Jordie0608** [comment]
Changelog

**Comment by Fayrik** [comment]
:-1: Assistants don't get maint access, and they might actually have a use for it.
In fact, there are whole bunch of people who could use maint a hell of a lot more than a clown or mime ever could, so this is probably going to end with people stealing their ids to get access.

**Comment by Cheridan** [comment]
This is something that needs broader discussion than just a PR, please make a topic and a poll on the forums.

**Pull request closed without merging**
