### PR TITLE
Adds "empty" cloning

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Adds Empty Cloning functionality to cloning consoles. Selecting a record and Empty Cloning it creates a clone of the record without pulling its mind into it, and therefore also bypassing the usual restrictions.
It does not put random minds in it like the experimental cloner; it simply creates a mindless replica.

UPDATE: Cloners can now also do BODY-ONLY scans, which are clearly marked as such in the records database. These can only be used for empty cloning, but do not require the body to have a functioning mind for the scan. They can be deleted without access if they're cluttering the list, and will not overwrite an existing full record if one exists.

**Potential future additions to this PR:**
- Making the cloning scanner able to scan soulless bodies, for Empty Cloning only. DONE
- Making it possible to clone from a DNA disk.
- Warning signs in case of mistakes.

## Why It's Good For The Game

Monkey-cloning was always an option, but kind of unintuitive and rather complicated when you consider you have literal cloning technology one room over.
Can be used to create clone armies, or to pre-prepare a replacement body for a crewmember (and potentially add augments, surgical buffs, and so on) to swap them into at a later time.

## Changelog
:cl:
add: Cloners now have the option to "Empty Clone" a record, creating a mindless replica of that person.
add: To aid the above function, cloners can now do Body-Only scans, which can be used to create empty clones but not real clones, but bypass the sentience restrictions on scans. They can also be deleted without requiring access.
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Time to hook one into the kitchen backroom for one kind of every meat.

**Comment by Shadowflame909** [comment]
is it still attached to your key? Hopefully, it is. If so I can see some use out of it.

**Comment by ExcessiveUseOfCobblestone** [comment]
neat

**Comment by ExcessiveUseOfCobblestone** [comment]
> is it still attached to your key? Hopefully, it is. If so I can see some use out of it.

Idk what you're asking here. It's a catatonic version of your body. You won't ever be able to use it as a second life unless you get brain surgeried into it.

**Comment by wesoda25** [comment]
I think he means like does it take your characters special attributes, such as if you are sac target and cult sacs an empty clone, does it work? Does killing an empty clone of a kill target work? Etc.

**Comment by ExcessiveUseOfCobblestone** [comment]
Objs are mindbound, not bodybound. Your mind doesn't get transferred to these guys so you can't use them in lieu of your true target.

Consequently, you could say they would work as doubles although the catatonic message is prob a big red flag.

**Comment by zxaber** [comment]
Sounds like a fun thing to mix with brainwashing for tator medical doctors. Capture assistants, brainwash them, and place them into an empty clone of yourself. Create an army of you.

**Comment by XDTM** [comment]
To be fair i think you can already do that with the genetic scanners if the rework didn't remove that functionality. A fancy idea could be to make sentience potion work on empty people, though, to get random personalities to work as your clone army.

**Comment by XDTM** [comment]
Update: Body-Only scanning is now available if you want to clone dead people who would normally not be scannable in the cloner due to DNR or other mind-related issues.

**Comment by HomocidlePancakes** [comment]
Should have a warning message pop that the clone will be a dud. Should help with more careless MDs

**Comment by PKPenguin321** [comment]
I've always wanted this

**Comment by fludd12** [comment]
@XDTM With the upcoming changes to crossbreeding, one of the crossbreeds will let you create a biological brain that works like a posibrain re: ghost possession. I think this could be a _very_ interesting use for it!

**Comment by Daxxed** [comment]
I just have to spoil it, the main use for this will be getting the robust observe mains on your team during cult ( powergamers hate me go ahead )

**Comment by GuppyLaxx** [comment]
feels like this should replace current altogether and just make it so you have to make them shit out their empty husk of a body out of the cloner and then slam their normal brain in

**Comment by XDTM** [comment]
Tbh I kinda like that idea, since it would remove the whole deal about cloners magically checking if people are still alive and pulling their soul out of the old body

**Comment by Tlaltecuhtli** [comment]
@fludd12 just making a golem and giving him human mut toxin works why add weird redunant things reeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by shellspeed1** [comment]
I've argued the whole having to put people in new bodies when cloned, issue is most people aren't smart enough to do that, at least in terms of medical staff.

**Comment by GuppyLaxx** [comment]
Most people arent smart enough to use stasis beds yet here we are, in a present where people throw everyone they see into cryo to heal up little scratches

**Comment by ExcessiveUseOfCobblestone** [comment]
> feels like this should replace current cloning altogether and just make it so you have to make them shit out their empty husk of a body out of the cloner and then slam their normal brain in

interesting

**Comment by Shadowflame909** [comment]
It'd make medical doctors 1000% useful. But if that were the case, I want those dispensable toolbelts for surgery tools.

A surgeon belt.

**Pull request merged**
