### PR TITLE
space dragons take 20% less burn damage

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

space dragons take 20% less burn damage

## Why It's Good For The Game

after lasers got buffed space dragons get absolutely fucking melted by lasers
this should make them as much of a threat as they were formerly

## Changelog
:cl:
balance: space dragons take 20% less burn damage
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
0.83 modifier would be a bit closer to the value of how they were if that's what you want

**Comment by carlarctg** [comment]
if the issue is lasers being too strong then lasers themselves need to be made weaker

i dont want every antag to recieve a buff against 30 dmg lasers instead of the laseres themselves being nerfed, thats just wack

**Comment by Ticklezcat** [comment]
Dragons being hard to burn makes sense in general, even beside the OP lasers currently.

**Comment by MrMelbert** [comment]
image

**Comment by DaydreamIQ** [comment]
Yeah just pr to lower the laser damage again. It's probably been long enough since the pr

**Comment by optimumtact** [comment]
I dont' agree and also space dragons are lame.

**Comment by mc-oofert** [comment]
> 0.83 modifier would be a bit closer to the value of how they were if that's what you want

ok

**Comment by mikederkan** [comment]
> image

maybe the laser buff wasnt a good move

**Comment by mc-oofert** [comment]
> > > 0.83 modifier would be a bit closer to the value of how they were if that's what you want
> 
> bro didnt doublecheck the math........... they used to be 20 and became 25. youd want 0.8

ok

**Pull request closed without merging**
