### PR TITLE
Makes cyborg module damage visible to anyone nearby

### PR DESCRIPTION
**Pull request by PKPenguin321**
:cl:
tweak: Cyborgs that take enough damage to have a module disabled will now automatically announce that they've had a module disabled to anybody nearby. Now if you want to stop a cyborg from interfering with your business but don't want to kill it, you can simply bash until you see the CRITICAL ERROR message.
soundadd: Borgs will play an alarm sound in addition to displaying this message as they have their modules disabled.
/:cl:

The `SYSTEM ERROR: Module 3 OFFLINE.` messages are now in the `userdanger` span for the borg itself, and bystanders will see a message in the `warning` span that reads `Cyborg-115 sounds an alarm! "SYSTEM ERROR: Module 3 OFFLINE."`

Hopefully this will allow people who want borgs to fuck off but don't want to outright kill them (security) to know when to stop bashing.

### CODE REVIEW

**Comment by Repukan** [comment]
What if they don't stop

**Comment by Repukan** [comment]
The borgs, I mean. They still move with no slowdown and can open, close and bolt doors freely.

**Comment by PKPenguin321** [comment]
Yeah but changing that is out of scope for this PR
I never said this would fix everything

**Comment by coiax** [comment]
This isn't speech, so would be understood by anyone, regardless of whatever languages they know.

**Comment by ExcessiveUseOfCobblestone** [comment]
Just make the borgs forcesay it.

I think a better indicator would be little yellow pixels coming out from them or, for the more advanced spriter, overlays that show their circuitry exposed when taken enough brute.

**Comment by PKPenguin321** [comment]
>Just make the borgs forcesay it.

I didn't do this since borgs can't speak or emote when stunned which is most of the time that they're taking damage

**Pull request merged**
