### PR TITLE
By request, added some more clothing to the biker crate

### PR DESCRIPTION
**Pull request by Tacolizard**
added gloves and cargo cap

I had an awesome revs round where cargo all became rev and we got to actually be a dank biker gang. golves improve the look, and the cap ensures everyone knows it's the cargonia gang.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
> all those items

>>>>>> STILL ONLY 2000

**Comment by Tacolizard** [comment]
@ExcessiveUseOfCobblestone you do realize you can get this stuff for free from the clothes vendor? and they offer zero benefits other than looks

**Comment by Tacolizard** [comment]
@kevinz000 shut up and go revert every vehicle in the game if you care so much about slips

**Comment by ExcessiveUseOfCobblestone** [comment]
so does the hat crate [in terms of zero benefits other than looks] , which costs 10x as much as this one does. The hat crate doesn't even come with utility value found in this crate, which will now also include gloves to stop prints.

I'm not going to argue balance around a meme crate, but I will say that if you're going to throw the entire gimmick in there [when that gimmick comes with features that advantage the player, regardless of how minute these advantages are] then it should cost a bit more. Just my opinion.

**Comment by Tacolizard** [comment]
@ExcessiveUseOfCobblestone the hat crate is a meme tf2 reference

**Comment by Tacolizard** [comment]
@ExcessiveUseOfCobblestone there are gloves in the actual cargo bay roundstart

**Comment by ExcessiveUseOfCobblestone** [comment]
fingerless gloves memer

**Comment by PKPenguin321** [comment]
Cargo hat crate is the cargo equivalent of the syndicate balloon costing 20 TCs. It can also be used as a cargo point sink by traitors.

**Comment by optimumtact** [comment]
Uh I'm pretty sure the only gloves that stop fingerprints are the latex ones. I'm pretty sure I remember a controversial nerf to the rest of the gloves.

**Comment by Bawhoppen** [comment]
Increase the price

**Comment by ExcessiveUseOfCobblestone** [comment]
why would someone nerf the roundstart gloves hos and det have reeeee

**Comment by PKPenguin321** [comment]
>Uh I'm pretty sure the only gloves that stop fingerprints are the latex ones. I'm pretty sure I remember a controversial nerf to the rest of the gloves.

not true, all gloves but fingerless ones hide prints. latex gloves have a chance of leaving prints, not guaranteed. unless it was changed recently?

**Comment by Tacolizard** [comment]
@optimumtact they all leave fibers though, except i believe nitrile.

**Comment by Tacolizard** [comment]
@ExcessiveUseOfCobblestone how does this nerf gloves

**Comment by optimumtact** [comment]
maybe it was fibres that I 'm thinking of

**Comment by ExcessiveUseOfCobblestone** [comment]
@Tacolizard I was referring to the pr that oranges was speaking about.

**Comment by Tacolizard** [comment]
@optimumtact @ExcessiveUseOfCobblestone yeah they still block fingerprints. i play det a lot. only the fibres are left behind.

**Comment by Iamgoofball** [comment]
you know if the biker gang that wears all black gloves is suspected for a breakin try hitting up the biker gang that wears all black gloves as security

**Pull request merged**
