### PR TITLE
Revert "Adds toggleable darkmode to the game!"

### PR DESCRIPTION
**Pull request by Thunder12345**
Reverts tgstation/tgstation#43072

image
Some admin panels partially near-unreadable in light mode

image
image
Custom OOC colours can be made readable in only one mode without highlighting

image
image
Admin PM messages are substantially less distinctive than before

image
Deadchat colour is difficult to read in dark mode

image
Ditto for the AI radio frequency

Also breaks with the standard of optional new features defaulting to the old behaviour, not immediately obvious how to disable.

This PR was not fit for purpose, and should have been subjected to some level of playtesting using a testmerge, instead of being dropped like a hot potato with no testing, and minimal demonstration of the new appearance in the PR.

### CODE REVIEW

**Comment by actioninja** [comment]
le epic kneejerk revert

**Comment by Kmc2000** [comment]
https://github.com/tgstation/tgstation/pull/43253

**Comment by Cyprex** [comment]
Then speedmerge the fixes please.

**Comment by Kmc2000** [comment]
Get a maintainer to do it.

Anyways, there's fixes up for a lot of the complaints so I don't see why you need to revert it into oblivion this early on.

**Comment by Barhandar** [comment]
Because the fixes should have been on testmerged PR of the darkchat.

**Comment by Kmc2000** [comment]
We'll leave it up to the maintainers I guess. They can choose to scrap it or merge the fixes.

**Comment by Arianya** [comment]
I doubt oranges will merge this and the fixes are more likely to get a testmerge then a revert.

Also remember that merge was oranges decision, not kmc's, giving him flack about it isn't productive or helpful.

**Comment by Barhandar** [comment]
Giving flak to someone who made easily testable and obviously bad decisions is perfectly fine.
and orange man is a menace

**Comment by Dorsisdwarf** [comment]
KMC: "If you dont like my changes, make a revert PR"

Also KMC "wtf how dare you make a revert pr kneejerk kneejerk!"

**Comment by Kmc2000** [comment]
What....?

I never said kneejerk, I said it's probably better to merge the fixes instead of outright nuking it.

For more information, please re-read.

**Comment by actioninja** [comment]
> KMC: "If you dont like my changes, make a revert PR"
> 
> Also KMC "wtf how dare you make a revert pr kneejerk kneejerk!"

You're getting mad at the wrong bastard here.

**Comment by Borisvanmemes** [comment]
This IS very much a kneejerk revert but at the same time dark mode should've been tested more and testmerged beforehand.

**Comment by Kmc2000** [comment]
The fix PRs are testmerged right now

**Comment by qbmax32** [comment]
I have no issue with a darkmode but this should really be reverted and tested until it actually works properly, oranges speedmerging it was stupid and dumb

**Comment by Kmc2000** [comment]
Mhm, nerve's testmerged this on the servers for the time being.

I'll continue trying to fix it into a more usable state.

**Comment by tralezab** [comment]
So wait, both the fixes to this pr's problems and this pr that removes the feature are both testmerged? Did whoever who testmerged the fixes then go back and remove then and the feature itself? What is going on behind the curtains here?

**Comment by Kmc2000** [comment]
The fix prs are removed. This one's testmerged.
Darkmode is gone for the interim

**Comment by optimumtact** [comment]
It was not speed merged, the PR was open for 12 days, and yet not a single one of you bothered to download the change, compile it and test it and give any feedback.

Frankly your level of entitlement is through the roof.

**Comment by Barhandar** [comment]
>demands people manually grab the PR

>complains about _said people's_ entitlement

**Comment by Kmc2000** [comment]
rm-rf

**Comment by optimumtact** [comment]
>people complain about a pr not being tested
>unwilling to actually test it themselves

hypocrites and snakes, you'll get no sympathy from me

**Comment by PKPenguin321** [comment]
>not testing your own pr
>expecting others to test it for you

oranges is being epic, leave now of you're vulnerable to bait

**Comment by Kmc2000** [comment]
Et tu, PK?

**Pull request closed without merging**
