### PR TITLE
Adds logging for crafting

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
Adds logging for crafting
Well technically there was limited logging before this change, but only via the investigate_log command used during an ongoing round. This adds full game logging to crafting in its own separate txt file. This is my first time messing around with logs so if you think I fucked up please tell me (might warrant a testmerge).

## Why It's Good For The Game
This was coded by me entirely for the purpose of being able to collect data on how often pipeguns are crafted in order to justify an argument to oranges.

image
image
link to thread: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=30653

This change will help me collect the data I need, denying this change is a denial of investigative journalism. It will also help others gather the data they need about the use of crafting recipes in the future.

## Changelog

:cl: itseasytosee
server: Adds logging for crafting
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
dude i https://github.com/tgstation/tgstation/pull/63178

**Comment by Mothblocks** [comment]
they exist in crafting.log, ask MSO (or I think edit the tgstation13.org PHP repo?) to put them on parsed-logs

**Comment by Mothblocks** [comment]
you wouldnt have been able to easily access this anyway because you made it a separate file--only whitelisted files go through to parsed-logs

**Comment by LemonInTheDark** [comment]
> 

you need to ask mso. He doesn't update that repo because he's ~~lazy~~ a closed source shill

**Comment by itseasytosee** [comment]
Cheers for the tip

**Pull request closed without merging**
