### PR TITLE
Makes certain curtains block your view when closed, new curtain type

### PR DESCRIPTION
**Pull request by Mickyan**
Opaque curtains block your view when closed (so shower curtains don't), and also adds a new fancy curtain type

Curtains are neat but don't get nearly enough use in mapping, thins might make them more interesting to use as low tech shutters

Screenshot_2

## Changelog
:cl:
tweak: Opaque curtains now block view when closed
tweak: Added crafting recipe for cloth curtains
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Could these be crafted with cloth/carpet and metal rods or something?

**Comment by uomo91** [comment]
> Could these be crafted with cloth/carpet and metal rods or something?

This sounds cool.
Could we also map in the theater having a curtain across it?

**Comment by uomo91** [comment]
Also could continuous curtains open as one piece?

**Comment by Mickyan** [comment]
I added a recipe for generic cloth curtains, you can change their color with crayons anyway

multi tile curtains sound nice but I wouldn't even know where to start

**Pull request merged**
