### PR TITLE
Removes Fastload.dmm

### PR DESCRIPTION
**Pull request by Cyberboss**
This was needed by the maploader at one point, but no longer

### CODE REVIEW

**Comment by optimumtact** [comment]
@ShizCalev why did you thumb this down?

**Comment by Thunder12345** [comment]
\>Non-coders downthumbing things that have no bearing on gameplay

**Comment by ShizCalev** [comment]
I use fastload to quickly check icon changes since it loads a little faster than a larger station like Meta does.

Update checking with fastload takes 14.42 seconds to load
Checking with Meta takes 19 seconds

Spread that out over 30 changes, that's 2.5 minutes of loading screen added.

**Comment by Cyberboss** [comment]
You shouldn't be checking dmm files...

**Comment by optimumtact** [comment]
@ShizCalev you can run runtimestation.dmm

**Comment by ShizCalev** [comment]
@Cyberboss Didn't mean checking a checkbox. Meant checking how transparencies and shit look over certain turfs.

@optimumtact forgot that one was there. disregard.

**Comment by lzimann** [comment]
STOP STEALING FAST LOAD

**Pull request merged**
