### PR TITLE
Renames the explosions subsystem to DrSingh's Lightning Fast Explosions, in memoriam of drsingh/magic mountain/delari, one of the best SS13 coders who sadly passed away recently

### PR DESCRIPTION
**Pull request by Iamgoofball**
Fuck death, man. This shit sucks.
https://forum.ss13.co/showthread.php?tid=19810

I already wrote everything I have to say on the matter in the comment, I guess. Please merge this PR at your earliest convenience.

note:
i added this subsystem
the key lag fixing thing in this subsystem(doing all the turfs at once without sleeping) was discovered by drsingh, thus i am crediting them for this subsystem
i will not entertain any shitty arguments on this front no matter what your rank in the community is
if you disrespect my dead friend who's done more for this video game than you ever will in your entire life i will disrespect you in return and you better not cry about it

### CODE REVIEW

**Review by SuperNovaa41 — APPROVED** [review]

**Comment by optimumtact** [comment]
There is an existing location in the code to express remembrances for developers you may add comments there, renaming subsystem's wholesale is not appropriate.

**Comment by optimumtact** [comment]
Oh and by the way, issuing threats in your PR body to attempt to coerce people is not something I would recommend you do.

**Comment by Simplehorror** [comment]
?XD this guy didn't do shit. hippie did it first with no input from him

**Comment by optimumtact** [comment]
I think you are lost mate

**Comment by Iamgoofball** [comment]
>Oh and by the way, issuing threats in your PR body to attempt to coerce people is not something I would recommend you do.

that was more to head off the "literally who???" comments from bottom of the barrel redditors but ok

**Comment by Iamgoofball** [comment]
@Simplehorror 
i'm sorry, but i don't think anyone asked you for your input

**Pull request closed without merging**
