### PR TITLE
Summon Guns can now be cast for extra spell points once more.

### PR DESCRIPTION
**Pull request by Iamgoofball**
You can only cast Summon Guns once, but you get an extra spell point for your troubles.

Best of both worlds of the Summon Guns changes.

I could make it castable 5 times, or leave it at the 1 cast.

### CODE REVIEW

**Comment by Ikarrus** [comment]
There's no possible downside to using this infinitely.

Summon Guns making traitors is supposed to help the wizard cull the crew population by making them kill each other. Why are we giving them more spells for making it easier for them?

**Comment by Iamgoofball** [comment]
@Ikarrus As it stands in this PR you can only cast it once, like Summon Magic.

**Comment by Ikarrus** [comment]
It was to my understanding there are no limits to summon spells any more.

Even if it did work as the way you say, I still disapprove.

**Comment by WJohn** [comment]
Yeah I mean summon guns creates antags that murder the crew and with this change wouldn't cost you anything.

The only benefit you get out of having almost exactly the same thing with summon magic is an extra spellpoint, but the ENTIRE crew will be hunting you since none of them can be antags. This is pretty bad.

Frankly, if you want to buff the wizard just give him magic missile and jaunt by default, it's almost guaranteed he'll take those things because of the insane mobility and survivability those provide.

**Comment by Iamgoofball** [comment]
Eh, alright.

**Comment by Ikarrus** [comment]
Thanks goof

**Comment by Iamgoofball** [comment]
remember to pay your coderbus premium dues

**Pull request closed without merging**
