### PR TITLE
Gives Geiger Counters a worn sprite

### LINKED ISSUE #58250: gieger counter has no suit storage sprite
## Reproduction:
step 1: go to fuck with the SM
step 2: put on the magic suit to not melt to ashes instantly
step 3: dare to put the geiger counter in your suit storage instead of your pockets
step 4: An Add-On is creating script errors

### PR DESCRIPTION
**Pull request by Orchian**
## About The Pull Request

Adds a previously missing worn icon for geiger counters in suit storage

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/58250, Adds in a previously non-existant sprite

## Changelog
:cl:
Add: worn icon for geiger counters
/:cl:

### CODE REVIEW

**Comment by Orchian** [comment]
I'm open to changing the sprite if needed

**Comment by Orchian** [comment]
I just realized I fucking misspelled "Geiger" on the title

**Review by Twaticus — CHANGES_REQUESTED** [review]
missing side directional
theres also a geiger counter sprite in icons\mob\clothing\belt.dmi if youd like to use that, but i just realized its missing its side sprites aswell if you wanna fix that too 👀

**Comment by Orchian** [comment]
> missing side directional
> theres also a geiger counter sprite in icons\mob\clothing\belt.dmi if youd like to use that, but i just realized its missing its side sprites aswell if you wanna fix that too 👀

I don't recall seeing that, but I'll look into it

**Pull request merged**
