### PR TITLE
Allows players to affix bayonets to their pipe guns, for defense against ruffians invading your department

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
Literally just changes a FALSE to a TRUE in the gun's code, allowing people to put bayonets on their pipe rifles.

## Why It's Good For The Game
Imagine the situation, if you will. Four unruly gentlemen have decided to break into your department, but not to worry! Your trusty pipe gun will surely handle these ruffians! You manage to down the first one with a single shot of your rifle, and destroy the second two foolish men with your cannon (this is also for self defense) but alas! You are out of ammunition for both of your ranged weapons. Not to worry however, as after this pr you will finally be able to attach a bayonet to your maintenance rifle, allowing you to charge down the final miscreant and successfully defend your department from the invaders.

## Changelog

:cl:
balance: allows the attaching of bayonets to pipe guns
/:cl:

### CODE REVIEW

**Review by Kylerace — APPROVED** [review]
just as the /tg/station maintainers intended

**Comment by necromanceranne** [comment]
Might want to check if you need to make any sprite adjustments. I believe there are bayonet offsets vars.

But otherwise lol nice

**Comment by Iamgoofball** [comment]
it's impossible for medbay to stitch the wounds from these up
👍

**Comment by TheBonded** [comment]
> > it's impossible for medbay to stitch the wounds from these up +1
> 
> It's impossible to stitch up basic piercing wounds? Do you know how to play med?

They were referencing the video, "triangle bayonette wounds are impossible to stitch up"

**Comment by CRITAWAKETS** [comment]
just make sure your pistol isnt smoothbore as it'll nail Ian instead.

**Comment by SuperNovaa41** [comment]
> > > it's impossible for medbay to stitch the wounds from these up +1
> > 
> > 
> > It's impossible to stitch up basic piercing wounds? Do you know how to play med?
> 
> They were referencing the video, "triangle bayonet wounds are impossible to stitch up"

ok i just havea smooth brain

**Comment by SkeletalElite** [comment]
Own a pipe rifle for department defense, since that's what the coders intended. Four ruffians hack into my robotics lab. "What the devil?" As I grab my gas mask and pipe rifle. Blow a golf ball sized hole through the first man, he's dead on the spot. Draw my makeshift shotgun on the second man, miss him entirely because of the scatter and nail the other robo's borg. I have to resort to the Durand mounted with a missile launcher, "Tally ho lads" the missile shreds two men in the blast, the sound and extra shrapnel set off fire alarms. Fix bayonet and charge the last terrified rapscallion. He Bleeds out waiting on security to arrive since triangular bayonet wounds are impossible to stitch up. Just as the coders intended.

**Comment by tohg7** [comment]
My username is Tohg7. and i approve this PR.

**Comment by datorangebottle** [comment]
Does this effect the Regal Pipegun as well?

**Comment by drIcepop** [comment]
https://www.youtube.com/watch?v=twbV97KPQ3g

We're gonna have to remake this...

**Comment by TheBonded** [comment]
> Does this effect the Regal Pipegun as well?

Assuming the regal pipegun is a subtype of the normal pipegun, it should carry over

**Pull request merged**
