### PR TITLE
Another fix for laggy tgui tooltips -- Turn off popper event listeners (+ give R&D console its tooltips again)

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Every single popper registered TWO event listeners for scrolling and resizing. This does not appear to be necessary for our cases.

https://user-images.githubusercontent.com/35135081/132781895-d91ea538-6ff0-4327-860e-5ec53be6a6e6.mp4

## Changelog

:cl:
fix: The R&D console has been given back its tooltips
/:cl:

### CODE REVIEW

**Comment by AMonkeyThatCodes** [comment]
are you going to crush our dreams again or is this real... 😢

**Comment by Mothblocks** [comment]
https://user-images.githubusercontent.com/35135081/132782611-ff776ca6-bd47-41c5-9937-b2db7392a6fb.mp4

this one works bro

**Comment by Mothblocks** [comment]
image

i almost dont want to believe this is the cause, but on a round on sybil with this TM'd, and NOT on a round on manuel where it isn't, the RPD ui looks like fuckin this

**Comment by 170141183460469231731687303715884105727** [comment]
Woah. By any chance would this fix chemistry UI lag, or would it only fix R&D?

**Comment by Mothblocks** [comment]
its not related

@170141183460469231731687303715884105727 it would fix that too yes

**Review by stylemistake — APPROVED** [review]

**Pull request merged**
