### PR TITLE
Mob Initialization

### LINKED ISSUE #24950: Runtime in unsorted.dm,1239: Found new qdeletion in type /mob/new_player!
Runtime in unsorted.dm,1239: Found new qdeletion in type /mob/new_player!
proc name: stack trace (/proc/stack_trace)
src: null
call stack:
stack trace("Found new qdeletion in type /m...")
Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
Atoms (/datum/controller/subsystem/atoms): Initialize(751092)
Master (/datum/controller/master): Initialize(10, 0)

### PR DESCRIPTION
**Pull request by Cyberboss**
Oh boy, here we go. Bite the bullet, cut the cord.

Dead mobs will ALWAYS Initialize in New. Repathed /mob/new_player to /mob/dead/new_player

Fixes #24950

### CODE REVIEW

**Comment by coiax** [comment]
Well, at least this means /mob/dead actually has some meaning as a type.

**Review by Cyberboss — COMMENTED** [review]
Self review looks good

**Comment by Cyberboss** [comment]
DNM while this comment is here. Needs testing

**Comment by KorPhaeron** [comment]
@Cyberboss 

Conflicts

**Comment by Cyberboss** [comment]
D N M

**Comment by Cyberboss** [comment]
Looks good, ship it.

**Comment by AnturK** [comment]
RIP codebase

**Pull request merged**
