### PR TITLE
Buffs cakehat

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Happy 15,000!

Let us celebrate with cake(hat)

### CODE REVIEW

**Comment by Incoming5643** [comment]
#2509

**Comment by duncathan** [comment]
#14001

**Comment by Giacom** [comment]
>Not making it set people on fire.

3/10

**Comment by Shapsy** [comment]
what kind of birthday parties have you been going to giacom

**Comment by MMMiracles** [comment]
@Shapsy the good ones

**Comment by tkdrg** [comment]
:tada:

**Comment by freerealestate** [comment]
the night darkness rises good

**Pull request merged**
