### PR TITLE
Adjust job selection table

### PR DESCRIPTION
**Pull request by celotajstg**
## About The Pull Request

The following changes have been made to the job selection table:

- Psychologist has been moved to the column with service jobs
- Service jobs are now directly under command (Captain / HOP) because of HoP having a dependency on service playtime
- The column item height has been changed from 17 to 15 in order to have the third column be populated not only with "Prisoner", but also the rest of security jobs. Makes it looks less empty.
- Cargo department jobs are now under the engineering department. Purely for aesthetical purposes, same with fitting the AI / Cyborg jobs in the 2-cell space below the service department.

Before:
image
After:
image

## Why It's Good For The Game

The job selection menu's third column now looks less empty, and new players will no longer get confused whether playing Cargo might count as service playtime due to it being under HoP.

## Changelog
:cl:Celotajs
qol: Visual adjustments have been made to the job selection table.
/:cl:

### CODE REVIEW

**Comment by Misdoubtful** [comment]
The job table has been making me irrationally uncomfortable with its disorder for like forever, thanks for this.

**Comment by TheBonded** [comment]
Can you also give assistant a Never/Low/Medium/On? For example, I'd like to be able to set assistant to medium with another job, so if I don't get my high job I get either curator, chaplain, or assistant, or, engineer, scientist, or assistant, each having an equal chance.

**Comment by celotajstg** [comment]
I think it would be best to do that in another PR, as it is slightly out of scope of this one. Good idea, though.

**Comment by TheBonded** [comment]
> I think it would be best to do that in another PR, as it is slightly out of scope of this one.

Does this mean you'll consider doing that? It would be a nice qol change

**Comment by optimumtact** [comment]
We explicitly do not allow you to differentiate because we do not want to encourage people to play assistant when their favorite roles are not available, so we would not accept that change anyway.

**Comment by celotajstg** [comment]
That settles it then, thank you.

Just in case - no further changes are planned in this PR, it's ready to be merged.

**Comment by TheBonded** [comment]
> We explicitly do not allow you to differentiate because we do not want to encourage people to play assistant when their favorite roles are not available, so we would not accept that change anyway.

@optimumtact  Isn't there a "become assistant if job preferences not available" in the bottom of the job preferences tab? Sounds like you're trying to encourage people to play as an assistant when their jobs are unavailable...

**Comment by optimumtact** [comment]
I do not acknowledge the existence of that button

**Pull request merged**
