### PR TITLE
Removes Oranges

### PR DESCRIPTION
**Pull request by datorangebottle**
## About The Pull Request

Removes Oranges.

## Why It's Good For The Game

His reign of terror has gone on long enough. We must evict this tyrant from our codebase so that it can flourish! Rally to me!

## Changelog
:cl:
del: Removed Oranges
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
hasn't this exact joke been made before

**Comment by Detective-Google** [comment]
this joke gets made like once a month lol

**Comment by cacogen** [comment]
oranges is gay

**Comment by PKPenguin321** [comment]
image

**Pull request closed without merging**
