### PR TITLE
Buffs BZ gas by allowing it to interfere with lings' hivemind access and chem regen

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
This isn't really intended to be a serious nerf to lings, but rather more of a fun little interaction for an otherwise useless gas that Nanotrasen for some reason supplies to the station.

:cl: Naksu
balance: BZ gas now makes lings lose their chems and hivemind access. The chem loss is gradual.
/:cl:

### CODE REVIEW

**Comment by Kromgar** [comment]
That's actually kinda cool. Now you can throw lings into a bz filled chamber in xenobio and then straight jacket them and give them a bz, n2o, oxy mix

**Comment by Iamgoofball** [comment]
@kromgar just incinerate them

**Comment by DaedalusGame** [comment]
You can fleshmend out of lava

**Comment by Noahnoah55** [comment]
This is actually pretty useful. Helps stop the ling from calling for help or using their chem bullshit when you make the trip to the incinerator/gibber/other gibbing place.

**Review by imtakingabreakdontatme — DISMISSED** [review]

**Comment by Iamgoofball** [comment]
>lava

Did you guys forget about the chapel

**Comment by DaedalusGame** [comment]
how do you drag them to the chapel if they keep regenerating really makes you think

**Comment by Iamgoofball** [comment]
I dunno same way we've been doing this shit for years

**Comment by KomradeSpectre** [comment]
They can keep fleshmending through anything. I had an objective to kill one yesterday as a traitor on lavaland, and despite killing it 20 times, and throwing it into lava 4 times over, it still fleshmend spammed and cryostung spammed me to death. This kind of counter to changelings spamming their chems is welcome to me.

**Comment by nicbn** [comment]
Add a hint ingame

**Comment by Bawhoppen** [comment]
This is a really cool change :+1: x :100:

**Comment by arsserpentarium** [comment]
Now you have excuse to bz entire station.lol

**Comment by Tlaltecuhtli** [comment]
ling tests mandatory soon

**Comment by lzimann** [comment]
this is great, adds a tool to deal with lings in an effective manner but in no way it adds a ling test.

**Comment by epicmemename** [comment]
cool i like it

**Pull request merged**
