### PR TITLE
Quieter highlander

### PR DESCRIPTION
**Pull request by ninjanomnom**
Reduces it by 10dB, for you @vcordie 

:cl: ninjanomnom
tweak: Highlander no longer breaks your speakers
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
no

**Comment by Pacmandevil** [comment]
Highlander being ear-shattering loud is the best part about it. Deny dis

**Comment by Armhulen** [comment]
Make it louder.

**Comment by Repukan** [comment]
Close this.

Vcordie should just lower his volume

**Comment by vcordie** [comment]
FUCK YOU EVERY OTHER LOUD ANNOYING SHIT CAN BE MUTED, EXCEPT FOR THIS. REEEE MUTE HIGHLANDER.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://youtu.be/ciPu4DnKBuM

**Comment by calzilla1** [comment]
^but louder

**Comment by FantasticFwoosh** [comment]
## **SCOOOOOOOOOOOOOOOTTTTTTLLLLLLLAAAAAAANNNNNNNDDD FOOOOOOOOOOOORRREEEEEEEEEEEEEEEEVVVVEEEEEEEEEEERRRR!!**

**Comment by banthebantz** [comment]
We cannot allow you to nerf Scotland

**Comment by PopNotes** [comment]
this is unacceptable

**Comment by kevinz000** [comment]
:salt:

**Comment by YakumoChen** [comment]
>17 downvotes
>merged anyway

**Comment by optimumtact** [comment]
Yeah, cause it's too loud

**Comment by ninjanomnom** [comment]
let the salt flow

**Comment by PopNotes** [comment]
> optimumtact commented 3 hours ago
Yeah, cause it's too loud

"lmao who needs community feedback I say yes so it happens"

**Comment by optimumtact** [comment]
that's how it works yes, do you have a problem with that?

**Comment by Pacmandevil** [comment]
Yes, Because it's literally you thinking you know better than The Majority.

**Comment by PopNotes** [comment]
>optimumtact commented a day ago
that's how it works yes, do you have a problem with that?

I assume this is rhetorical?

**Comment by optimumtact** [comment]
it's obviously rhetorical since I don't take your opinions into account anyway.

**Comment by PopNotes** [comment]
I'm only making sure you aren't _just_ slow on the draw.

**Pull request merged**
