### PR TITLE
Clowns get an automatic self-recharging pie cannon as a traitor item for 10TC

### PR DESCRIPTION
**Pull request by silicons**
Hey, it's less OP than the memebow.
20 max charges, 2 seconds/charge.

Question: Should I lower it to 10 max, and 6 seconds/charge, but let you add reagents to all of them by pouring reagents in?

### CODE REVIEW

**Comment by Armhulen** [comment]
acid pies please

**Comment by obscolene** [comment]
i wouldn't say it's less OP than the ebow, they're 2 different items that function slightly similarly. this having stored charges, and recharging about the same as the ebow.

**Comment by kevinz000** [comment]
@obscolene they stun for 1 so it's instantly removed the next tick.
if it's a problem i'll raise recharge and lower max amount stored.
other types of pies will be in a later PR.

**Comment by kevinz000** [comment]
Also, alternative is raise the recharge and lower the max, and let you add reagents to the pies by pouring reagents into it, Y/N?

**Comment by darkpaladin109** [comment]
Don't we only allow like 1 role-restricted traitor item per job?

**Comment by Armhulen** [comment]
Y

@darkpaladin109 where did you get this meme

**Comment by darkpaladin109** [comment]
@Armhulen I recall Kor saying it in the PR for the librarian's magic eightball
Checked, it was Citrus, but I guess the difference isn't super important anyways.
https://github.com/tgstation/tgstation/pull/24607

Might seem strong, but seeing as we've got ebows this seems not much stronger anyways, so I'm all for trying it out at least.

**Comment by Expletive** [comment]
Clowns should just get a self recharging pie cannon with reagent holding pies as a regular item.

**Comment by duncathan** [comment]
why not

**Pull request merged**
