### PR TITLE
Autoshuttle timer reduced to 15 minutes

### PR DESCRIPTION
**Pull request by Robustin**
Absolutely no reason for a round to go on for 30 minutes when the station is fucked. 

Edit: To clarify when both consoles + the AI are destroyed, a 25 minute shuttle is called. That shuttle will now be 15 minutes. 

Edit2: I'm a reasonable guy. I absolutely do not understand the people who want to drag out finished rounds but 15 minutes is my new compromise number, up from 12.

### CODE REVIEW

**Comment by ElfLeaderMike** [comment]
I have never seen a round where the full time was ever beneficial to the remaining players, this is a good tweak.

**Comment by Niknakflak** [comment]
12 minutes is barely longer than a regular shuttle call.  The 20 minutes is the punishment for the crew failing to call the shuttle through normal means.

**Comment by Repukan** [comment]
Nobody plays the game to be punished though

**Comment by Kromgar** [comment]
@Niknakflak 

The crew must be punished because boh singulos ate the consoles after someone popped a singulo off at the bridge and there is no ai

**Comment by Niknakflak** [comment]
15 minutes?

:meek_smile:

**Comment by Robustin** [comment]
Niknak its not like you can blame people for failing to call the shuttle. We have this crazy ~20m wait for shuttle calls when its easily possible to destroy both consoles + AI by the 20m mark. 

Loose engines, rampant plasma fire, general murderbone, even past the 20m mark its a long list of things necessary to get a shuttle call if youre not a head. 

If someone really wants to keep a shit round going they've got a comfy 7 minutes to make a comms console to recall.

**Comment by AdamElTablawy** [comment]
Guess we're back to instantly calling because someone saw a tome again.

**Comment by Robustin** [comment]
Adam... that's not the shuttle timer im talking about.

**Comment by ShadowDeath6** [comment]
>singlo eats both comms consoles
>no AI
Crew needs to wait 25 minutes while singulo sticks his void dick in the rest of the station and effectively makes it uninhabitable

Good change

**Comment by Buggy123** [comment]
I agree, give them 25 minutes to deal with their fuckups.

**Comment by Robustin** [comment]
>People acting like getting a malf AI and maxcapping the bridge is something that any player is going to be able to prevent and that they deserve to be punished for it.

This PR is almost worse than the one where I took Nar-Sie out of the construct portal storm event. A dozen angry comments about something that is an objective improvement to the game.

**Comment by PKPenguin321** [comment]
Not objective

If there's no AI and the bridge gets bombed once that's a stupid reason to leave ASAP. If everything is absolutely fucked admins can lower the call time.

**Comment by Robustin** [comment]
Like I said if the crew has a desire to say in that scenario then RND or Engineering can get a comms board and recall.

Depending on admins to correct for stupid code is not a good plan either. Late night rounds exist (25m shuttles when everyone is dead is guaranteed to kill the server for the night) and sometimes admins don't change the timer.

The round that inspired this PR had 6 admins on including Kor and a Headmin. The round was already nearly an hour in and the only active player who wasn't just huddling on the arrival shuttle was a ling who had wiped out anyone that the plasma flood/fires hadn't. Even the ling was totally ready to wrap the round up by the end.

Given the opposition I'll bump this to 15, but 25 is just inexcusable.

**Comment by PKPenguin321** [comment]
>Like I said if the crew has a desire to say in that scenario then RND or Engineering can get a comms board and recall.

This has never happened

Maybe make it call regular length if admins are on? iirc part of the reason it's so long is because you could bypass the roundstart delay before calling the shuttle by destroying the comms boards

**Comment by Robustin** [comment]
It seems silly to say "Well maybe we should keep the timer at 25 in case people want to have a full round despite having no AI or comms consoles" but then when I propose burden-shifting to the people who WANT to keep a round going in spite of major problems, you act like its impossible.

I have seen people recall the auto shuttle twice this month. In on instance it earned the crew a ~12 minute recall when the captain had actually recalled so he could try and get a code red shuttle to come faster. Having this mechanic at 25 minutes is just a shitshow for everyone.

**Comment by sawrge** [comment]
instead merge incoming's PR that sets it to an hour

**Comment by optimumtact** [comment]
you've made this pr before and got told to drop it I'm sure.

If you haven't

drop it.

**Comment by Robustin** [comment]
I haven't, and you're anger is completely unwarranted. Last I checked we're here to improve the game and a 30 minute shuttle when the station is destroyed is the antithesis of a good game mechanic.

**Pull request closed without merging**
