### PR TITLE
Hitting someone with a dualsaber now has a chance to make you *flip

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
While you spin

:cl: Kor
rscadd: You now have a chance to flip while attacking with a dualsaber.
/:cl:

### CODE REVIEW

**Comment by Zilenan91** [comment]
You're on a roll lately

**Comment by Anonus** [comment]
Instead of a prob chance, have it flip if the dir/i is 8.

**Comment by newfren** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by Bawhoppen** [comment]
ghost *flip when

**Comment by Niknakflak** [comment]
Lol

**Comment by duncathan** [comment]
Webm or gif please

**Comment by Aloraydrel** [comment]
I HAVE THE HIGHER GROUND

**Comment by Cebasiz** [comment]
[unintelligible screech]

**Comment by Bawhoppen** [comment]
@Cebasiz https://www.youtube.com/watch?v=MdN0NXgjsn8

**Comment by Megatrononline** [comment]
Spinning is a good trick

**Comment by HankMoodyExperience** [comment]
next pr: energy sword parries energy sword

**Pull request merged**
