### PR TITLE
Removes that annoying clunking steam engine ambience sound that's probably from a youtube video

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
https://clyp.it/gn1yslfl this one

:cl: Naksu
del: Steam engines have been removed from maintenance, engineering, atmos and teleportation areas.
/:cl:

### CODE REVIEW

**Comment by Wilchenx** [comment]
everytime i hear that i think its clockcult round and suicide

**Comment by Jordie0608** [comment]
Is that a person talking from 0:31 onwards?
Was this recorded inside a textiles factory?

**Review by ShizCalev — APPROVED** [review]

**Comment by Qustinnus** [comment]
Oh yeah these were unused when I was fixing up ambience so I added it back to the engineering ambience list, its really old and was added before we used github kek

**Comment by praisenarsie** [comment]
why did we merge the ambience pr, floyd sucks weewee

**Comment by Qustinnus** [comment]
i didnt add this sound it was already in the files ree

**Pull request merged**
