### PR TITLE
moves blast doors and shutters to a layer above windows and doors and changes shutters cost and build time

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

This PR increases the layer of poddoors to 3.3, above windows and doors. (Poddoors include blast doors and shutters). I tested this PR to see how blast doors and shutters look with the changes, and they look better open and closed with the new changes. I did not see any bad interactions with windows or doors, except the preexisting fact you need to build a blast door before making a door, or you will be unable to link them up. This PR also rebalances shutters to be a cheaper, easy to build alternative to the monstrosity that is a blast door.

## Why It's Good For The Game

Blast doors and shutters (collectively referred to as poddoors) are thematically important parts of the game, providing a level of extra security and reinforcement that is hard to recreate. Somehow, they are below windows and doors, meaning someone with a fireaxe can destroy windows and doors quite easily without scratching the poddoors. It also makes no sense for a poddoor to be under a window, somehow inside a grille or glass pane. This change will make it so someone who wishes to destroy areas must actually first defeat the theoretically first line of defense (poddoors). Shutters now actually have a noticeably different purpose to blast doors. They are still not meant to be anything but reinforcement to existing barriers. This will help encourage their usage over blast doors.

## Changelog
:cl:
balance: blast doors and shutters are now above windows and doors, and will hide them. Both layers have been increased to 3.3.
balance: shutters now cost 5 plasteel and 5 coil and 1 airlock electronic and take 10 seconds to build
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Question: since this only appears to change the visual layer of the blast doors themselves, in situations where the blast door is covering an airlock, will the airlock still open and close or no?

**Comment by MacBlaze1** [comment]
> Question: since this only appears to change the visual layer of the blast doors themselves, in situations where the blast door is covering an airlock, will the airlock still open and close or no?

Im not entirely sure, let me test it real quick

**Comment by MacBlaze1** [comment]
> Question: since this only appears to change the visual layer of the blast doors themselves, in situations where the blast door is covering an airlock, will the airlock still open and close or no?

Nope, alt clicking the blast door does not work, you need to see the floor tile, and running into the door via the bump open proc does not work either.

**Comment by zxaber** [comment]
Arguably fire locks should also do this (or be somewhere between airlock and shutter)

**Comment by MacBlaze1** [comment]
> Arguably fire locks should also do this (or be somewhere between airlock and shutter)

they already are between airlocks and shutters

**Comment by Rohesie** [comment]
Hope it's not an overbuff. We'll see.

**Pull request merged**
