### PR TITLE
Adds a new RoundEnd Sound.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
[Changelogs]: 

   :cl: ArcaneMusic
   soundadd: Added a new, shoutier RoundEnd Sound.
   /:cl:

[why]: Sometimes after a nice, long round you just want to scream.  Now, feel the Catharsis of someone else doing it for you!

I balanced the audio as best as I could to keep it from going ear-rapey, let me know if it's needs to go up/down.

### CODE REVIEW

**Comment by optimumtact** [comment]
please don't close and reopen the pr needlessly it causes spam

**Comment by ArcaneMusic** [comment]
Right, sorry.

**Comment by MrDoomBringer** [comment]
I feel like something like this would be a bit better with maybe some reverb? How does this sound?
https://www.dropbox.com/s/fmr2fpb36aon53o/gondolabridge.wav?dl=0

**Comment by PKPenguin321** [comment]
seems kind of random? i mean most round end sounds are but at least they have some amount of deep lore

**Comment by ArcaneMusic** [comment]
@MrDoomBringer Oooh, that sounds better. Thanks!
@PKPenguin321 Yeah, this certainly doesn't have much server lore, but it does add a little bit more flavor to the existing endround sounds.

**Comment by Bawhoppen** [comment]
Are round end sounds going to become the new brain damage lines?

**Comment by optimumtact** [comment]
What are the rights on this track?

**Review by SpaceManiac — APPROVED** [review]

**Comment by Arianya** [comment]
I've only just heard this for the first time now and I want you to know its amazing

**Pull request merged**
