### PR TITLE
Add debug-verb to read AT (active turfs) cords at roundstart

### PR DESCRIPTION
**Pull request by bear1ake**
For easy search active turfs.
Can help for fixing #10253
Screen Example:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Fantastic

**Comment by duncathan** [comment]
:+1: absolutely wonderful

**Comment by Thunder12345** [comment]
How did nobody think of doing this before :+50:

**Comment by Aranclanos** [comment]
I guess checking trough the controllers is a bit complicated because it doesn't say anywhere.
But I'm not convinced about the file, how about a simple list and a verb? Like the show del log

**Comment by bear1ake** [comment]
@Aranclanos i can make it in debug-verb, but... File should be better to fast operating with this list

**Comment by MrStonedOne** [comment]
keep the file, I'll add it to the public runtime logs.

**Comment by bear1ake** [comment]
@MrStonedOne i kept it in file and it avaliable to read from game

**Comment by Aranclanos** [comment]
remove the file, it's not needed

**Comment by bear1ake** [comment]
@Aranclanos file is needed to @MrStonedOne's public runtime logs. You sure?

**Comment by Aranclanos** [comment]
yeah the contents of this information is always the same

**Comment by Jordie0608** [comment]
Conflicts

**Comment by bear1ake** [comment]
@Jordie0608 fixed

**Comment by bear1ake** [comment]
damn dme...

**Comment by bear1ake** [comment]
@Jordie0608 Ready

**Pull request merged**
