### PR TITLE
>give them config to disable shuttles

### PR DESCRIPTION
**Pull request by Iamgoofball**
>they still warn and bwoink people for buying certain shuttles 

Before you go muh steno that guy has notes for just buying meme shuttles in general, the suicide stuff apparently started after

Shit or get off the pot. Disable the shuttles or stop arguing about people using them.

### CODE REVIEW

**Comment by coiax** [comment]
This is not disabling the shuttles, this is removing shuttles from code altogether. If the admins want to disable shuttles, there's already config options in place.

**Comment by MrStonedOne** [comment]
So, like, we can't decide that antags/assistants are allowed to buy them, but captains are not?

**Comment by MrStonedOne** [comment]
@coiax reading comprehension man.

**Comment by coiax** [comment]
I don't understand

**Comment by MrStonedOne** [comment]
the title line, and the first line of the pr body are connected.

he isn't saying he's disabling shuttles.

**Comment by lzimann** [comment]
Instead of removing the entire datum, set the price to `INFINITY`.

**Comment by GunHog** [comment]
Goof trash PR #44583

**Comment by KorPhaeron** [comment]
What MSO said

A captain buying something dumb and suiciding is very different from a captain buying something dumb to get emergency cash, or even a captain buying dumb and otherwise contributing.

If anything the shuttles should require the captain mind to buy (or a voucher item he spawns with that enables it) or red alert so one all access mime can't do it.

Also there is a freeze

**Comment by Iamgoofball** [comment]
He has notes that ONLY mention meme shuttles. Not the suicide part.

**Pull request closed without merging**
