### PR TITLE
Revert "Santizes racist robot code from the codebase."

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#73909

see #73944 

secondly it has been reported that deportista is the spanish word for sportsman and a google translate backs that up.

This whole PR has basically character assassinated someone for no reason.

### CODE REVIEW

**Comment by TheSmallBlue** [comment]
Spanish speaker here, it's true, deportista means sports player. lol. lmao, even

**Comment by HansRobertCoooding** [comment]
oranges is truly the saviour of teegee

**Comment by the-orange-cow** [comment]
whythough
I tried to tell them.

**Comment by BlueMemesauce** [comment]
ok but can we keep enrique thats my spanish characters name

**Review by Kylerace — APPROVED** [review]

**Comment by githubuser4141** [comment]
In the future shouldn't changes like these be fact-checked before merge? It was brought up in the OP's comments what deportista meant but was ignored. A lot of people might automatically assume a change like this is fact-checked by default by the maintainers/admins when it's merged, which could spread misinformation.

**Comment by Kapu1178** [comment]
kinda weird it got merged in the first place, all of the words in the various bot prefix files are just words that americans associate with other cultures. like. "anime" being a prefix for japan. it's either all offensive, or none of it is.

**Comment by Jacquerel** [comment]
> In the future shouldn't changes like these be fact-checked before merge? It was brought up in the OP's comments what deportista meant but was ignored. A lot of people might automatically assume a change like this is fact-checked by default by the maintainers/admins when it's merged, which could spread misinformation.

That's my bad, it was a sloppy merge where i just took the change at face value without looking deeper. Seemed reasonable at first glance but its not my job to just take a glance. 

I especially shouldn't have let that change log pass as it is transparently inappropriate.

**Comment by optimumtact** [comment]
I want to add that I think the word most people are looking for is tacky.

By the way we're open to changing the drink orders, just you know, replace them with actually relevant drink orders of a similar complexity.

**Pull request merged**
