### PR TITLE
Free keys

### PR DESCRIPTION
**Pull request by optimumtact**
limited time giveaway

nobody ever uses these and they should, so lets do our part for christmas

### CODE REVIEW

**Comment by optimumtact** [comment]
whoever merges this first gets one free steam key of their choice (appropriate max cost limit applies)

offer redeemed on the 16th

**Comment by Dicks1** [comment]
Make them 1 point at the very least so someone just doesn't spawn a million of them around the halls.

**Comment by optimumtact** [comment]
that is hilarious

**Comment by optimumtact** [comment]
should I make the channel anonymous?

**Comment by Dicks1** [comment]
That might hinder the person who subverts the ai then wants to give it orders over binary.

**Comment by optimumtact** [comment]
it's a syndicate key not a binary one.

**Comment by optimumtact** [comment]
oh I edited the wrong key, one sec.

**Comment by Bawhoppen** [comment]
>nobody ever uses these

You see them literally every fucking traitor round you elk-monger

**Comment by KorPhaeron** [comment]
obj/item/device/encryptionkey/syndicate (0TC) (Total): 282	

It is used in 38% traitor rounds. (111 / 286)

It is used in 41% traitorchan rounds. (95 / 228)

**Comment by optimumtact** [comment]
thanks for your feedback

**Comment by Bawhoppen** [comment]
I'll buy a steam key for whoever closes this

**Comment by Dorsisdwarf** [comment]
Technically if someone merges this they get both steam keys

**Comment by Bawhoppen** [comment]
I'd like to compliment myself on how clever my comment was because:
1. If someone closes or merges it, that means they're accepting bribery so this needs to stay open forever.
2. Oranges could close it himself and make a profit.
3. I made it impartial whether it should be merged or not again
4. What dorsi said

**Comment by Dorsisdwarf** [comment]
Steam keys please.

**Comment by Bawhoppen** [comment]
shit

**Comment by Bawhoppen** [comment]
3K4HN-V2IXJ-27MVL

5. I didn't say if they would be valid or not

**Comment by Dorsisdwarf** [comment]
And to think you spended real monies on a fake key. Charmed.

**Comment by Bawhoppen** [comment]
what, I made it up intentionally, I just took one of my already used keys I saved and edited it slightly

**Comment by Dorsisdwarf** [comment]
You promised to buy one Q_Q betrayed in my bribery

**Comment by optimumtact** [comment]
I think it's okay

**Comment by Bawhoppen** [comment]
I was going to buy the 10 random steam CD keys bundle on g2a and post them here, but I can't right now

**Comment by GunHog** [comment]
These are not used enough imo. I am okay with this.

**Comment by Shadowlight213** [comment]
>Not used enough

Yeah. Kor is correct I see these used almost all the time.

**Comment by Incoming5643** [comment]
Technically speaking if we had a 0 TC item the surplus box could contain a theoretically infinite number of them, of course in reality the onslaught of keys would stop once the last priced TC item was picked and brought the total down to 0 TC. Still, I wonder how many would spawn in the mean time.

**Comment by Fox-McCloud** [comment]
Wouldn't it be best to just like---give all traitors this key, by default, then instead of it being a purchase?

**Comment by optimumtact** [comment]
probably but I'm lazy

**Comment by Fox-McCloud** [comment]
@optimumtact 

It wouldn't be that hard...

just add something like this: http://hastebin.com/pefikumixo.coffee

under: https://github.com/tgstation/-tg-station/blob/master/code/game/gamemodes/traitor/traitor.dm#L275

**Comment by Shadowlight213** [comment]
@oranges you're going to want to limit the number a single uplink can spawn, or you'll have players spawning hundreds of them
Actually I'm not going to use it and gonna mail all of sec keys every round as it won't cost me anything.

**Comment by optimumtact** [comment]
consensus is nobody uses them because other players can dob you in to sec.

**Pull request closed without merging**
