### PR TITLE
Revenant event can only occur once per round

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Dual lightning spam ghosts is crazy as much fun as I had leading them as the HoS (or were they leading me?) to kill all the badguys

### CODE REVIEW

**Comment by RemieRichards** [comment]
let's compromise, with 2!

**Comment by Anonus** [comment]
Probably a good idea. Personally I'm planning to make them not have incorporeal move while revealed, for reasons that should be obvious after trying to catch one.

**Comment by KorPhaeron** [comment]
@Anonus 

They suffer from the same balance issue as all simple animals in that they're impossible to kill with melee weapons (which are all slow and low damage) but easy as shit to kill with laserguns (spammable and high damage)

**Comment by MrStonedOne** [comment]
what we really need is a min buffer var, so that an event doesn't trigger two quickly, but can happen again in boring rounds

**Comment by Anonus** [comment]
We really just need an event manager in general.

**Comment by MrStonedOne** [comment]
we have one...

no need to proc or re-code, just add the functionality to it.

it would take 5 lines...

**Comment by AlexCrimson** [comment]
Good. More than one is way too much. Removing their ability to move through walls whilst visible is a good idea too. 

They still could use more fun abilities though.

**Comment by Razharas** [comment]
After playing two rounds of sybil both of which had multiple revenants despite not being extended i decide this balance change is good for now
Anyone who wants new event handling can open new pr
I ded plz nerf

**Pull request merged**
