### PR TITLE
(Black)market Telepad (LTSRBT) Update: Restocking Edition

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This is a suggestion that was to me several months ago to add the ability to pay credits to restock the black market. I liked the idea because it'd add anothe small reason to buy the board, though I had forgotten about it shortly after and just happened to remember it now.

So, yeah, you can swat the LTSRBT with a holochip to restock the market(s). The price is shared amongst all pads and starts at 675 credits, but it doubles up everytime this is done, for obvious balance purposes. 

I've also updated included this new feature in the unit test, given the LTSRBT new sprites and renamed the Blackmarket subsystem to Market, because of how it can support different types of market datums, not just the blackmarket

## Why It's Good For The Game
This adds one more reason to buy and build the LTSRBT and make markets less dependant on the bad side of RNG, if you have the credits. It's a bit of a money sink.

## Changelog

:cl:
add: You can now restock the black market by hitting the LTSRBT with enough credits. The price doubles each time this is done.
imageadd: Updated the LTSRBT sprites.
balance: Reintroduced the LTSRBT to cargo for 2000 credits vs the original 4000 (the ansible and crystals to build it are included btw), and slightly lowered the average blackmarket price for the same item to account for shipping costs.
/:cl:

### CODE REVIEW

**Comment by YuliceTheDruid** [comment]
IIRC they removed the LTSRBT from cargo and you can only buy it from the uplink itself now; may want to check that out or else this feature will just be dead half the time.

**Comment by Ghommie** [comment]
> IIRC they removed the LTSRBT from cargo and you can only buy it from the uplink itself now; may want to check that out or else this feature will just be dead half the time.

Fine, I've reintroduced the thing to cargo. The main gripe that led me to remove it from cargo in the first place was the exaggeratingly high price of 4000 and the blackmarket being a bit worse than it's now (still waiting for Arcane to port the auction market by the by), compared to the current 2000.

**Comment by CCC23** [comment]
finally I can now purchase 8000 collar bombs and 80 switchblades

**Comment by TheChosenEvilOne** [comment]
Hey, I am the guy who originally made the blackmarket. Decided to just comment here about it since I have seen some PRs related to it. Also going to comment on some of the older PRs that I have noticed that change the blackmarket.

I planned and actually had code for "player markets", so players could sell items on the uplink as long as an LTSRBT exists on the station. Also the LTSRBT was supposed to allow selling items to the blackmarket itself. Anyway I lost the code I wrote for all that for a reason or another, and then I lost interest in SS13 (though I still seem to come back occasionally, the other curse of SS13 I guess). The crate was a lot more expensive than the machine was supposed to be because the crate contained diamonds (lol).
Speaking of items, I put zero thought into the items on the blackmarket. I just went on Terry with a spreadsheet and asked what items I should include, thanks to Timonk and some admins in admin chatter for most of the item list. Also I was scared that if I included powerful items on the blackmarket the PR wouldn't get accepted, so I asked people to not add anything too powerful to the list.

Some comments on older PRs:
#81818 - Supply pod was one of the four original delivery methods, it took the users area and spawned a supply pod in it. I got asked to remove it due to it having potential for grief.

#64271 - Blackmarket uplinks didn't use the user's ID card for money because I wanted to have markets that used different types of currency (something like TC for example).

Anyway thank you for updating this thing I made just because I saw that /vg/ had some blackmarket thing and wanted to make my own version.

**Comment by Ghommie** [comment]
Selling things on the blackmarket wouldn't be a bad idea, since we have the code to support unique market items (like fenced goods and hostages). Heck, I already have a pretty simple implementation of the idea (I'd have to sprite a hatch on the machinery though).

**Comment by CCC23** [comment]
> Selling things on the blackmarket wouldn't be a bad idea, since we have the code to support unique market items (like fenced goods and hostages). Heck, I already have a pretty simple implementation of the idea in mind, but I'd have to sprite a hatch on the machinery though.
> 
> EDIT: Actually, people would use it to scam the shit out of each others by selling junk haphazardly named like it were cool stuff. Might need some extra checks to make it harder to do so.

I mean you are buying things on the black market after all who's to say if the chemist was selling actual meth pills or 30 pounds of acid and cyanide with the label zaza on it

**Comment by Ghommie** [comment]
> 
> I mean you are buying things on the black market after all who's to say if the chemist was selling actual meth pills or 30 pounds of acid and cyanide with the label zaza on it

Funny pills are not an issue, like it isn't to try to sell a fake (toy) emag. All I want is the initial name of the item being attached to the name of the market entry if they don't match, like \"officer's sabre (wrench)\", or something similar to that.

**Comment by EricZilla** [comment]
For selling, maybe have the item's icon visible, so the scam only works on things that actually look alike?

**Comment by deathrobotpunch** [comment]
> Funny pills are not an issue, like passing a fake (toy) emag for the real deal isn't. All I want is the initial name of the item being attached to the name of the market entry if they don't match, like "officer's sabre (wrench)", or something like that.

I find it hilarious that people would sell knockoff shit like an Ebay scammer

**Review by ArcaneMusic — APPROVED** [review]
LGTM

**Pull request merged**
