### PR TITLE
adds badminka vodka to contraband in booze vendors

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
adds badminka vodka to the list of booze vendor contraband items

## Why It's Good For The Game
How else is one supposed to look fancy while drinking vodka without going to deep space or buying the mother russia shuttle?

## Changelog
:cl:
add: adds badminka vodka to the booze vendor contraband items
/:cl:

### CODE REVIEW

**Comment by Mickyan** [comment]
casual reminder that fernet is literal poison and I moved it to contraband for a reason

**Comment by Paxilmaniac** [comment]
uh oh, stinky

**Comment by carshalash** [comment]
Why was fernet even made poisonous?

**Comment by TheVekter** [comment]
Because fernet is a bitter apertif and tastes like wet dog

**Comment by carlarctg** [comment]
fernet isnt a poison why did u make it one tf

**Comment by Mickyan** [comment]
the guy that made it had no idea what he was doing and I wasn't allowed to properly fix it

**Comment by HomocidlePancakes** [comment]
Being able to buckle people to vodka bottles when? It’s an old Russian tradition.

**Comment by Dorsisdwarf** [comment]
Loot the vault like a civilised person you animal

**Pull request closed without merging**
