### PR TITLE
Syndicate borgs dont have binary

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Robotic Talk, Syndicate Assault Cyborg-371 queries, "What is the plan, operatives?"

### CODE REVIEW

**Comment by MMMiracles** [comment]
ROUND ISNT OVER YET THE META

**Comment by Lo6a4evskiy** [comment]
IC in Github

**Comment by Zilenan91** [comment]
sound the alarm

**Comment by Jordie0608** [comment]
What about if the AI gets subverted?

**Comment by Zilenan91** [comment]
Actually yeah can we make it so syndi borgs can hear binary but not use it

**Comment by KorPhaeron** [comment]
@Jordie0608

They can buy binary keys in the uplink

**Comment by Cebasiz** [comment]
i guess it's not a big deal but to be honest it's caused one problem in what is probably literal years

**Comment by GunHog** [comment]
It is a player problem. A few borgs screwing up here and there is not enough to warrant a removal. Binary is still useful for intercepting AI communications with the borgs and communicating with borgs you manage to flash and emag.

It is not worth it to lose that like this just to bubble-wrap a few noobs.

**Comment by tkdrg** [comment]
(it was me who did this)
It's useful sometimes, but syndiborgs are OP either way so any nerf is a good thing.

**Comment by Cebasiz** [comment]
there is literally nothing op about a syndiborg

who even thinks this

**Comment by GunHog** [comment]
People who say that borgs are "unstunnable" and such. The majority of syndieborgs I see either die or carry the round themselves. What kills most Syndieborgs? Flashes. Which All heads and Sec have. They handwave that fact so that they can exaggerate a borg's ability to survive..

**Comment by Cebasiz** [comment]
oh yeah

how to kill syndiborg

get any other borg

flash

beat to death with crowbar

wow difficult

man i don't generally like to say gitgud but the only really decent weapon syndiborgs have is the grenade launcher which half the time fucks your own team 

the LMG is passable and the esword is asking to die considering any asshole with a flash insta GGNOREs you as soon as you move to attack with it

**Comment by tkdrg** [comment]
The OP thing about borgs isn't just their combat skills. It's the fact that they can interact with any station systems/doors, they add an extra ops member which is usually guaranteed to be experienced, and that they have a very easy time killing the AI. The fact that they're a solid gun is just a bonus. They're horribly underpriced and there's a reason they're used in 95% of all nuke rounds.

**Comment by Cebasiz** [comment]
that reason being they add solid utility to the group? 

ops can win without using them, they are used chiefly because even new ops can identify that the AI is a big problem, and the easiest way to remove it is with a cyborg. that doesn't mean the cyborg is broken, it just means the cyborg can achieve what it is supposed to.

in other news, many traitors take emags, emags are broken news at 11.

**Comment by tkdrg** [comment]
emags are used in literally every single traitor round, they're incredibly powerful and underpriced as well. The fact that emags are very good doesn't mean that syndiborgs are not extremely good as well. One problem does not cancel another. As for your argument, it would be true if the cyborg was only being used to disable the AI; however, its utility value goes far beyond that: apart from being a hard counter to the AI, they are also an emag on legs that can think and is also fairly efficient at killing. While it is true that it is not perfect at any of those (apart from killing the AI), it's a very flexible tool that can let the ops get out of many sticky situations, and that alone makes it worth the meager 50TC cost.

**Comment by Shadowlight213** [comment]
:-1: on the change. This is terrible justification to remove it. Just because one player screwed up does not mean it has to be removed and bubblewrapped. Hell, why not bring back irremovable syndie hardsuits, since I've seen some newbie ops fail to detonate their implants and get stripped of their gear.

**Comment by KorPhaeron** [comment]
>binary
>all access
>extra team mate
>door control
>instant kill aoe grenades
>infinite ammo lmg
>built in emag
>immune to convential stuns/200hp/no slowdown/usual borg advantages
>dead AI for zero effort
>The rest of the op team are immune to its counters and can easily cover it

If something is bought 95% of rounds it is probably because its good

**Comment by GunHog** [comment]
>binary

Because it is a cyborg.
>all access

Again, like all cyborgs.
>extra team mate

Worth it for their cost.
>door control

All cyborgs have this as well.

>instant kill aoe grenades

They are powerful, but do not guarantee a kill.

>infinite ammo lmg

The LMG has a self-recharging magazine, taken from the borg's cell. *It is not infinite*. The LMG has a maximum of 30 shots.
> built in emag

This one is entirely valid, as it is quite useful as well.
>immune to convential stuns/200hp/no slowdown/usual borg advantages

Immune to conventional stuns, yet entirely shut down by flashes/flashbangs/EMP.
Humans also have 200 HP. They go into crit at the 100 mark, whereas borgs lose their first module at 150, second at 100, and third at 50. 
>dead AI for zero effort

It is unfortunate the the AI is not allowed to attempt countering this if it is not aware of the Ops before the borg makes it inside. This point here is likely the primary reason to buy a Syndieborg in the first place.
>The rest of the op team are immune to its counters and can easily cover it

This is true, depending on the strength of squad's teamwork.

Cyborgs ARE good, your points are not a justification for removing their binary, as in your OP, you state that your reason for doing this is to stop the borg player accidentally giving away the team's cover.

**Comment by MMMiracles** [comment]
There still needs to be more disadvantages to getting the borg, as its one of the most-bought items as of recently and it does the same exact thing every time.

Literally the only way you can wreck it is if the borg is dumb enough to give you the ability to get within flash-range or it doesn't react fast enough to a flashbang. For a decent player, syndiborg's objective usually ends up being "kill ai, proceed to murderbone the crew as the ops get the disk'.

This isn't exactly the right way to go about it, but it definitely needs some sort of utility nerf.

**Comment by Zilenan91** [comment]
Or just remove it and give the Ops a cost-effective way to murder the AI. Literally the only reason I'd buy it as an Op is because it kills the AI so so efficiently unless the AI is a shitter and metas Ops. If there was something of similar cost that JUST killed the AI I'd buy it every time.

**Comment by optimumtact** [comment]
:+1: to this alongside my price increase

should shake up the nukeop meta a bit

**Pull request closed without merging**
