### PR TITLE
Dangerous Research - The Alternate Sciences Research Center Space Ruin!

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request
Adds the space ruin "dangerous_research.dmm" to the game. This ruin was previously PR'd to two separate codebases ->
https://github.com/shiptest-ss13/Shiptest/pull/528
https://github.com/Skyrat-SS13/Skyrat-tg/pull/5047
It's a fun little lore-heavy ruin. With a few dangers and some environmental storytelling, as well as a few documents detailing the events that caused the science experiment to go horribly wrong.
This is absolutely the definitive version of this map, I spent a whole lot of time redesigning and remapping it to be the gold standard for space ruins.
## Why It's Good For The Game
We need ruins! This one is fun, has a fun/spooky/slightly edgy story to tell, and I believe it would help bolster the few space ruins we have.
Map screenshot is below! I think it's best experienced without reading the lore/seeing the map. If you're interested in experiencing the ruin in-game, I'd advise against poking around too much!
<details>
<summary> Map screenshot! </summary>

dangerous_research

dangerous_research2

</details>

## Changelog
:cl: Cheshify, Ferro
add: A new ruin has been detected near the station, what secrets could it hold?
/:cl:

### CODE REVIEW

**Comment by Lovebird-Frungy** [comment]
looks really nice, we need lore stuff like this.
there doesn’t seem to be an atmos system however.

**Comment by Cheshify** [comment]
> looks really nice, we need lore stuff like this. there doesn’t seem to be an atmos system however.

Atmos isn't real it can't hurt you. Also, since there's no atmos interaction as part of the map there isn't really a reason to have one

**Comment by MMMiracles** [comment]
Loot distribution looks fine, I don't see anything that would make a gamer immediately jump into the void if they see the active gps. Another .38 revolver making its way on-station isn't going to make or break a round. 

Doors not having access requirements is a bit odd to me, since this is supposed to be a separate outpost. Maybe take advantage of the away access placers and IDs to restrict unprepared explorers and encourage actually looking through the whole ruin? Stuff like having the head ID between the angry mobs so you can gain access to their office and hit a button to disable the lockdown on the supply closet.

I'd really like to see an expansion on the current ruin's powernet/atmos. I'm glad you added a dorms section so you can more easily see how people would work here long-term but restricting the power supply to a single room with an SMES and some RTGs. Take the listening station for example, its a long-term working environment for a person so it has somewhat of a proper setup for distributing air, removing waste and consolidating the important bits for general maintenance/power generation. Even something as simple as an air tank pumping into distro and the waste pipe just shooting into space is enough for what we're working with currently.

Other maptainers can step in against this but with march mapness coming up I feel like we should make sure the more 'realistic' ruins ala outposts should strive to have some basic station setups so instead of it feeling like a separate setpiece you can find it and go "oh, people live here so obviously has to have some basic air distribution and power just like our stations" and actually be right. I think the map quality shown here is actually decent otherwise (big fan of anyone who takes the time to actually write up lore for their work, even if most players won't read it), I'd just like to see a bigger push towards making livable environments rather than just setpieces if possible.

**Comment by Cheshify** [comment]
Aight, will add atmos

**Comment by Cheshify** [comment]
Oh sure I'll also expand upon it being a liveable area. Also, the revolver has an outback pin so if someone WANTS to use it, they'll need to go through security for a pin.

**Review by Maurukas — COMMENTED** [review]
I like this a lot.

<details>
<summary>Decals on R-walls </summary>

image
</details>

* The RTGs are not connected to the SMES
* `beaches_journal_3` is invisible, likely due to an icon issue. Not sure why, it shows as a different icon in the map editor, but the object itself has no icon in game, even when picked up.
* Also agree on a really basic atmos setup - just for looks. Feel free to add any sub areas you need to do more elaborate networks

**Comment by Cheshify** [comment]
Agreeing with the posted reviews. I have a small atmos wing (possibly some disposals too depending on how much I want to stretch mapsize). I may have made a code mistake with the ruin lore paper! Will look into it, thanks.

**Comment by Cheshify** [comment]
- Multiple areas for different parts of the ruin
- Functioning atmos system, with some ENVIRONMENTAL storytelling thrown into the mix
- Added some ID cards to help guide players through the most interesting route
- Some more loot for flavour and fun
- Removed wall-decals
- Fixed some text mistakes in the documents
- Added an atmos room, expanded the map by 2 tiles to make up for the space used

**Comment by Cheshify** [comment]
I don't know what's up with codeowners.

**Comment by ZAMODA** [comment]
This looks really nice, I love seeing heretic based stuff in the game, but, if you don't mind me making a suggestion, maybe add a carving knife or some other minor heretic loot? Ive always wanted a way to earn some form of heretic loot from ruins, and a ritual gone wrong seems like the perfect candidate for that. (If there is already a ruin that does that do please inform me)

**Review by Maurukas — APPROVED** [review]

**Comment by ZAMODA** [comment]
> Hey there! The ruin doesn't have a ritual knife specifically for ruin lore reasons. You could poke around the code and get a general idea as to why, but I think exploring it in-game and coming up with your own theories may be just as fun. I am glad that you picked up on the absence of the weapon, because it _does_ matter to the story I tried to write. 😃

I gotcha! This is still super nice to see and now that it's merged I cannot wait to find it in game!

**Pull request merged**
