### PR TITLE
xray lasers now have 100 armor penetration

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

gives xray lasers 100 armor penetration

## Why It's Good For The Game

an xray laser passes through solid objects, armor is a solid object so it makes sense xrays pass through it
xray doesnt really have that much of a niche, it literally does 5 less damage than roundstart laser guns while being late-game research. you kinda do need xray to use it effectively. this should give it a niche outside that and its pretty cool i think

## Changelog

:cl:
balance: xray lasers now have 100 armor penetration
/:cl:

### CODE REVIEW

**Comment by datorangebottle** [comment]
New PR: Xray lasers no longer deal damage. 
Because they just pass through things.

**Comment by nianjiilical** [comment]
> New PR: Xray lasers no longer deal damage. Because they just pass through things.

i mean a laser gun that only deals organ damage *would* be kind of unique........

**Comment by itseasytosee** [comment]
Make X-ray lasers be stopped by meat walls

**Comment by ATH1909** [comment]
> Make X-ray lasers be stopped by meat walls

and human skin suits

could go even further and including leather/bone items, but eh, that'd lead to a lot of bikeshedding

**Comment by bruhlookatthisdood** [comment]
make a large amount of xray lasers give you multiple stages of cancer

**Comment by Shadowflame909** [comment]
> > New PR: Xray lasers no longer deal damage. Because they just pass through things.
> 
> i mean a laser gun that only deals organ damage _would_ be kind of unique........

Head shots that make your opponent think its a laser gun until they suddenly start slurring and drop dead

**Comment by bruhlookatthisdood** [comment]
quick they got xray guns!
wrap the ai in human skin!!

**Pull request merged**
