### PR TITLE
Metastation Science Redo Part 2 - Gloopy Bluberoo (Brand New Xenobiology)

### PR DESCRIPTION
**Pull request by Zytolg**
Nanotrasen Prefabs are cheaper to replace than maintaining rusty old space hulks.

## About The Pull Request

The original changes to Metastation Science added Cytology Specific locations to the Xenobiology Satellite, in addition to the overhaul of science on the Main Station. Xenobiology however, never got the same love as the rest of science, and a lot of the old satellite was preserved during the addition of Cytology. After seeing how Cytology works (and running things by with its creator) I have designed a new Satellite for Xenobiology.

## Why It's Good For The Game'

Science got a rework, but Xenobio was barely touched. Cytology is an amazing addition, but Xenobiology should be brought in line with the rest of the Metastation Science Rework. A new layout, overall lower footprint, and stronger integration of Cytology will help keep the jobs fresh for a long time to come, all while keeping that dope Metastation Satellite in Station Orbit. 

## Changelog
:cl:
add: New Xenobiology Satellite
add: 1 Additional Slime Pen
del: The Old Xenobiology Satellite
tweak: Shrunk 2 Slime Pens
tweak: Integrated Cytology closer in to the Xenobiology Lab.
tweak: Slimes now are centralized around the Execution Room, and get to watch. 
/:cl:

Meta Xeno 1
**New Lab, Smaller Size, but just as capable.**

Meta Xeno 2
**Smaller, Radial Hall. Allows for better observation of slimes, finally adds nuance to the roomspace.**
**8 slime pens, with front row seats to the SLIMEZONE**

Meta Xeno 3
**Xenos Room. Shield Gens are on the outside in maint. 2 Maint rooms flank both sides, providing access to power and air respectively.** 

MetaNeoXenoSat9
**Full sat engineering map for reference**

_//Station Communications Log//Date Classified//Central Command// _
_ What do you mean we have to wait a week for a new prefab to ship? You just approved a departmental overhaul and you're telling me that you can't afford bluespace delivery? No. Uhuh. Well.. I. Hey, you can tell Corporate that we're loosing more credits patching the holes that the old model keeps making and I'll be happy to bill them for it. I don't care if Central sends down a suit, the RD is up mine wondering sector S's Satellite is more advanced then theirs!_

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
Not a fan of having the pens in this arrangement instead of the easy side-by-side line they were in before...

**Comment by AlinaStarkova** [comment]
> 
> 
> Not a fan of having the pens in this arrangement instead of the easy side-by-side line they were in before...

its barely any extra work, not that xenobios do much of it anyway, they sit at a computer all shift 😏

**Comment by Pumpkinoe** [comment]
It's a noticable difference if you, say, want to transfer slimes from the top left pen to the one on the bottom right - also the shield gens are an absolute pain to setup or turn off in this configuration. Not a complete fan of this design.

**Comment by KathrinBailey** [comment]
I can't tell if this is more or less obnoxious to spacewalk around than the old one, but it looks nicer.

**Comment by Zytolg** [comment]
NewMetaXenoSatSpacewalk
As spacewalking may prove to be a complication, I've added some scaffolding in order to alleviate some of that pressure.

**Comment by Tlaltecuhtli** [comment]
why does metastation need a map change every week? can you people update ice box instead?

**Comment by Zytolg** [comment]
> why does metastation need a map change every week? can you people update ice box instead?

This is part of the ongoing mapedits to Science. Things will largely be calming down after this in regards to this department. 
In regards to Icebox, fixes are going through, but not really new areas. There's more going on this but this PR isn't the place to address that.

**Comment by Pugie** [comment]
But old xenobio was literally perfect???

**Comment by D4C-420** [comment]
All I see here is more rooms for pens and therefore I like this

**Comment by Livrah** [comment]
But why changing something what already good? Why meta? There is k*lo and box multiZ xenobio that makes me wanna jump to bottom Z level until horizontal.
And as I said before, you cant see every cells on same screen due UI.

**Comment by Zytolg** [comment]
> But why changing something what already good? Why meta? There is k*lo and box multiZ xenobio that makes me wanna jump to bottom Z level until horizontal.
> And as I said before, you cant see every cells on same screen due UI.

Yes you can. All slime pens are visible as shown in the images in the original PR post.

**Comment by Son-of-Space** [comment]
> 
> 
> why does metastation need a map change every week? can you people update ice box instead?

This is a part of our master plan to Ship of Theseus MetaStation until it is no longer the station anybody remembers. We only have a few more departments left until your precious MetaStation, like the shortened legs on old gramama's chair, is gone forever. We shall soon completely negate "but it's not meta." from players' mouths forever. When those words are uttered, we shall laugh in triumph.

And you think, with these grand designs in motions, that a map as broken and unfixable as BoxStation crosses even a modicum of our purview? No. We have consigned it to the abyss where it shall die an icy cold death, forgotten.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
