### PR TITLE
Changes the flightsuit helmet light

### PR DESCRIPTION
**Pull request by Lexorion**
## Changes the flightsuit helmet light
Old one on the left,new one on the right.

EDIT: Those brown pixels around the helmet are my characters hair,those are NOT in the files!

### CODE REVIEW

**Comment by XDTM** [comment]
It looked especially goofy when you put a speed or fireproof potion on the suit

**Comment by GunHog** [comment]
Why not just improve the visor glow, instead of giving it a generic light that you probably pulled from another hardsuit?

**Comment by Lexorion** [comment]
I dislike glowing visors (atleast in this case, it's just not fitting in my opinion) and I like some consistency

**Comment by KorPhaeron** [comment]
Commonly touched icon file, person who created it likes it, don't believe we need 24 hours of review

**Pull request merged**
