### PR TITLE
Galactoturf: False Grass, Real Aesthetics

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Adds galactoturf floor tiles- fake grass in tiled form.
image
It can be converted from iron tiles in the same way as any other tile variant.

## Why It's Good For The Game
Should be nice for some faux nature without the full natural look of real grass.

## Changelog

:cl:
add: The Electric Garden company has made Galactoturf available in the SSC region- yes, that includes SS13. Put some down and enjoy the feel of nature indoors!
/:cl:

### CODE REVIEW

**Comment by Zytolg** [comment]
These are great. I can already see myself giving the captain a lavish restroom using these tiles.

**Comment by Time-Green** [comment]
They look really good! But, maybe make it made with grass or plastic? You’re kind of undermining grass by making these craftable from the most common material on the entire station

**Comment by Fikou** [comment]
can you make the half and half ones rotateable?

**Comment by EOBGames** [comment]
> They look really good! But, maybe make it made with grass or plastic? You’re kind of undermining grass by making these craftable from the most common material on the entire station

I could do it with plastic, sure. Using grass to craft artificial grass sounds like a mindfuck though.

**Comment by necromanceranne** [comment]
> They look really good! But, maybe make it made with grass or plastic? You’re kind of undermining grass by making these craftable from the most common material on the entire station

I dont agree that this undermines grass. They look noticeably distinct with the tiling pattern. If anything this makes me wish we had a ceramic material.

**Review by Watermelon914 — APPROVED** [review]

**Comment by maxymax13** [comment]
grass is already astrotu.. well.. grass is like quantum soil substance. you can make it from the plant, which says "preparing astroturf" and a shovel can also transmute it into sand somehow.

**Pull request closed without merging**
