### PR TITLE
Meta lounge/theater regained area

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

The recent expansion of kitchen screwed lounge and theater hard by making the cafeteria next to the kitchen into a hallway and the theater got screwed because the audience would have to use this hallway to watch a performance.

This PR moves art storage to another side of the hallway towards engineering, and cuts one maints room to make space for proper lounge and theater as before the kitchen expansion.

Before:
Labor Platform Nineteen 2023-05-02 015051

After:
Draconic Hub Juliet 2023-05-02 133458

## Why It's Good For The Game

Even if Chefs know CQC, they should respect other professions.

## Changelog

:cl:
balance: Meta lounge and theater are back to original sizes, art storage moved to aux tools storage
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
image

can you fix this by moving one of those wall items elsewhere thanks

**Comment by Helg2** [comment]
Looks lame

**Comment by YuliceTheDruid** [comment]
If you want me to put on my huge nerd emoji then this is also a balance issue because it makes Secure Tech Storage more secure by removing the windows. The line of sight made it easier to teleport in or break in with a space suit and hololocks.

**Comment by MTandi** [comment]
> If you want me to put on my huge nerd emoji then this is also a balance issue because it makes Secure Tech Storage more secure by removing the windows. The line of sight made it easier to teleport in or break in with a space suit and hololocks.

Well it's not much harder to disassemble one reinforced wall in maints than going two reinforced windows. But yeah, the one option less.

We have to choose to either make space for theater or too remove it, because it's useless in the current form anyway. Please suggest if you have a better idea for the art storage placement.

**Comment by san7890** [comment]
image

move art storage here, then you have enough room for that space-gap. you can then shuffle the lockers into the new space or what have you, fuel tank can just be dropped somewhere in maintenance, useless room anyways

also the space-gap is a good idea because literally everyone on the station has tools to decon a reinforced wall, but spacesuits are always in some sort of limited demand (unless robotics does their job)

**Comment by MTandi** [comment]
> move art storage here, then you have enough room for that space-gap. you can then shuffle the lockers into the new space or what have you, fuel tank can just be dropped somewhere in maintenance, useless room anyways

That room was an isolate maint room for relatively safe xeno spawn. But OK, I made art storage part of aux tools storage.

**Comment by Singul0** [comment]
As if metastation maint isn't small enough as-is.

**Comment by MTandi** [comment]
> As if metastation maint isn't small enough as-is.

I dislike too that kitchen expanded triggering this chain reaction. These tiles have to be taken somewhere. Revert that PR and I will close mine.

**Comment by Dorsisdwarf** [comment]
I'm VERY in favour of this change because it puts the processor 2 tiles from the griddles, so I can mass-produce burgers 👍

**Pull request merged**
