### PR TITLE
Maintains Dream

### PR DESCRIPTION
**Pull request by ChangelingRain**
It turns out the best way to get me to update my map is to complain it's not being updated.

Medbay's patient room is a tile taller, finally.
Security's mulebot delivery flaps have been moved so the flaps are no longer next to space.
Some misc tile changes.
Some misc wiring changes to make the powergrid less robust.
Auxiliary mining base wee woo

### CODE REVIEW

**Comment by GunHog** [comment]
Since you are making DreamStation changes, would you consider adding support for the Aux Mining Base? Certainly not a requirement, but it would be nice.

**Comment by GunHog** [comment]
Thanks Joan~

Here is a screenie of it since I was curious:
dreamstationaux

**Comment by ChangelingRain** [comment]
it is an ugly tumor blight on the station
but oh, the sacrifices we make for cool shit

**Comment by GunHog** [comment]
If you do not like its shape or location, you as the map maker can change it to your needs. Just try to keep it a square shape, or weirdness happens. Edit both the docking port and remote to the correct dimensions.

**Comment by ExcessiveUseOfCobblestone** [comment]
> It's an ugly tumor blight on the station

It's the same for box as well.

**Pull request merged**
