### PR TITLE
Makes the Russian fugitive hunters less bad (also gives them a pet bear)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

This PR updates the Russian fugitive hunters. Namely, it remaps their ship and gives them slightly better equipment, also adds some variance to their outfit for style. 

- One of the Russians is now a "Russian Commandant".
- The Russians now get some varied gear when they spawn.
- Gives them some extra ammo, tools, medical supplies.
- Actually gives them oxygen tanks so they can spacewalk.
- Adds a pet bear to the ship. For self defense. Their name is ~~Wojtek~~ Voytek. 

image

## Why It's Good For The Game

The Russian ship is kinda dog water currently. 
It uses normal iron walls, tiny fans, **HAS NO OXYGEN TANKS** or extra ammo or tools, and so on.
Given Fugitives are slightly more common now, I feel like it should receive some love. 

## Changelog
:cl: Melbert
expansion: Russian Fugitive Hunters are now stronker. Their ship has been remade, they have a little bit more ammo and equipment, and most importantly they now have a pet bear.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
>Adds a pet pear to the ship.

I can pearly contain my excitement

**Comment by Colovorat** [comment]
It should be commendant, or even if we go full Russian you can use komandir or commander something like that
Also I'm not sure what bear name should mean. You can ask me if you have questions about Russian)))

**Comment by EOBGames** [comment]
> It should be commendant, or even if we go full Russian you can use komandir or commander something like that Also I'm not sure what bear name should mean. You can ask me if you have questions about Russian

Wojtek was a Polish bear who served with an artillery regiment in WW2. It's not related to Russia, but I think it's a fitting reference to a real (and awesome) figure from history:
https://en.wikipedia.org/wiki/Wojtek_(bear)

**Comment by Colovorat** [comment]
> > It should be commendant, or even if we go full Russian you can use komandir or commander something like that Also I'm not sure what bear name should mean. You can ask me if you have questions about Russian
> 
> Wojtek was a Polish bear who served with an artillery regiment in WW2. It's not related to Russia, but I think it's a fitting reference to a real (and awesome) figure from history: https://en.wikipedia.org/wiki/Wojtek_(bear)

Ah, then it's fine I think. Eastern Europe, sorta Slavic thing. But the name is still quite weird to my ear

**Comment by Colovorat** [comment]
Also got another name for bear if you want truly Russian
Kosolapiy

**Comment by BlueMemesauce** [comment]
You could call it Voytek which is the russian pronouncation of Wojtek

**Comment by MrMelbert** [comment]
> You could call it Voytek which is the russian pronouncation of Wojtek

Sure thing.

**Comment by wraith-54321** [comment]
This is good, I feel silverscale pirates also suffer from the same problem, mainly lack of any extra ammo

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
