### PR TITLE
Nerfs Clogged Vents Harder

### PR DESCRIPTION
**Pull request by Iamgoofball**
nnow requires 50 people minimum, lowers the weight down to 25, foam size reduced drastically

Closes #35306

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
afraid?

**Comment by PKPenguin321** [comment]
You can just do "Closes ####" instead of fixes and it still closes iirc

**Comment by PKPenguin321** [comment]
Also reposting from the other PR
>Perhaps put this event on a severity scale, like meteors? You see the clogged vents announcement and it's a gamble if it just poots water or spews lava

This way we can still have minor clogged vents at lowpop

**Comment by epochayur** [comment]
wow it's almost like we knew this was gonna be a huge issue

**Pull request merged**
