### PR TITLE
make git handle line ending conversions automatically

### PR DESCRIPTION
**Pull request by optimumtact**
Files will be normalized to /n on commit to repository

dmm and dmi files shall be unchanged.

### CODE REVIEW

**Comment by optimumtact** [comment]
This will cause a number of whitespace changes in every diff since until we cover every single file, unless you want me to do it all at once.

**Comment by Cheridan** [comment]
Editing all files at once is a pain, it's fine to have a little whitespace as we go.

**Comment by Razharas** [comment]
Is this mloc 2.0?

**Comment by optimumtact** [comment]
yes but I get stuff done

**Pull request merged**
