### PR TITLE
The Lance Crew Evacuation System (New Emergency Shuttle)

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request
Yeah this shuttle deliberately hits the station.
While more hazardous to people in departures, the Lance is a great crew-friendly tool for a station that has a severely damaged departures! No longer will you need to struggle with firelocks and collapse just outside the shuttle in a depressurized departures, when The Lance comes RIGHT TO YOU.

<details>
<summary> The Lance being used </summary>

image

</details>

<details>

<summary> Map screenshot! </summary>

image

</details>

### Mapping March
Ckey to receive rewards: Cheshify 
I don't need a token or anything, but the GBP or whatever would be nice so I can make more map stuff

## Why It's Good For The Game

New shuttles are good! This one has both immense pros (very safe when you're inside it, lots of supplies) and immense cons (smashes into the fucking station). It'll be an interesting purchase for the antagonist using it to kill a bunch of people in departures, and a useful tool for the crew making it easier for them to evacuate.

This shuttle is not restricted to emags or any other prerequisite, as that would defeat the purpose. It's supposed to be a mixture of pros and cons, and keeping it locked behind an emag removes it's use as a prohibitively expensive but ultimately useful tool for the crew.
## Changelog
:cl:
add: Nanotrasen has given the crew access to a brand new emergency shuttle! Watch out for it's destructive entrance!
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
It's a little uhhhhhhhhhh... Phallic.

Jokes aside, this is actually a pretty good shuttle and I'm excited to see it used.

**Comment by UnokiAs** [comment]
> It's a little uhhhhhhhhhh... Phallic.

Great 😉

**Comment by Cheshify** [comment]
If that looks like a dick to you PLEASE go see a doctor

**Comment by DaydreamIQ** [comment]
The idea of CC literally ramming an emergency shuttle into the station on purpose is too funny to pass up

**Comment by Vect0r2** [comment]
Yeah. It's really fucking cool.

**Comment by san7890** [comment]
You must add this to the shuttle configuration, see https://github.com/tgstation/tgstation/blob/master/.github/guides/MAPS_AND_AWAY_MISSIONS.md#configuration for more information

**Comment by Cheshify** [comment]
Why the fuck does this PR change the order of varedits on a totally different map lol

I genuinely have no idea, merge it, it's funny.

**Comment by optimumtact** [comment]
> If that looks like a dick to you PLEASE go see a doctor

I tried to warn you

**Comment by zxaber** [comment]
This is perhaps the only shuttle to have reversing thrusters (that I can recall, anyway). Which makes sense, I suppose, since it would need to back out of the station.

Why does it have two syndicate balloons?

**Comment by Cheshify** [comment]
> This is perhaps the only shuttle to have reversing thrusters (that I can recall, anyway). Which makes sense, I suppose, since it would need to back out of the station.
> 
> Why does it have two syndicate balloons?

Those are the mapping helpers that make the shuttle crash into the station! I thought only one would be required, but it seemingly only worked with 2 in the tests (similar to the monastery)

**Comment by RedBaronFlyer** [comment]
> If that looks like a dick to you PLEASE go see a doctor

Make it shoot out metal foam

to uh...

help with breaches...

yeah...

**Review by Maurukas — CHANGES_REQUESTED** [review]
> it seemingly only worked with 2 in the tests (similar to the monastery)

I can think of absolutely no sane reason why this would be the case. Can you open an issue on this?


<details> 
<summary>The tip of the shuttle depressurizes the centcom dock </summary>

image

It appears to be a result of having the catwalk tile being one tile in front of the docking port. This causes it to land on top of the centcom blast doors, stomping the machines on that turf. When it departs for the station, it vents Centcom to space.

image
This catwalk can also pick up solid objects like firelocks and windows from the station and carry them to Centcom, trapping people in the shuttle:

image


</details>

It also looks like your PR has picked up a random varedit reordering in the emergency_monastary.dmm.

Other that everything seems working and I see no other issues.

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
