### PR TITLE
Remaps the Kilo whiteship and adjusts the kilo abandoned warehouse 

### LINKED ISSUE #68307: Kilo Whiteship Bridge Console does not function
Reporting client version: 514.1585

## Round ID:
[186386](https://scrubby.melonmesa.com/round/186386)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:

The bridge console for the kilo whiteship does not function properly, leaving the navigation console as the only way to move it, limiting where it can go by default.

### PR DESCRIPTION
**Pull request by Capsandi**
## About The Pull Request
Here's a picture(no mood lighting though)
image
The nonfunctional kilo whiteship has been remapped. I tried to capture the style of the original and the theming (mining ships got demons) has been retained. 

As for the warehouse, I got rid of an airlock and 2 of the 4 hive lords which would repeatedly open the airlocks and depressurize the place every round.

## Why It's Good For The Game

Fixes: #68307
The current ship is very pretty, but doesn't fly, this one does[tested].
Also this one has mood lighting. Mood lighting is cool.

## Changelog
:cl:
add: The kilo whiteship has been remapped and can fly again
add: Kilo's abandoned warehouse has been adjusted slightly to match the ship
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
seal of approval granted

**Comment by Addust** [comment]
also, the old one COULD fly, but it needed nav console.

**Comment by Addust** [comment]
Cable management means that setting up a PACMAN will force the engineer on the ship to block the door to cargo in order to charge the SMES. Please fix.

**Review by Maurukas — APPROVED** [review]
Exactly what I was looking for. Thank you.

**Pull request merged**
