### PR TITLE
Ninja event wont occur naturally (admin only)

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I lost pls nerf etc

Ninja currently either has infinite or near infinite perfect (no counters, no thermals, etc, as far as I know) invisibility and just clicks everyone to death and the round ends, it's very dull. Ninja needs to be reworked before it shows up on its own.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
shameful dishonour

theres plenty of counters, you can hover over and see the ninja is there, then you kill it
pretty simple

**Comment by borntohonk** [comment]
Yes.

**Comment by Lo6a4evskiy** [comment]
Tag it fun removal

**Comment by Bawhoppen** [comment]
revert/removal tag too to give it a negative connotation

**Comment by Dorsisdwarf** [comment]
Compared to the rest of the side antags? Blobs, perfect stealth stunbaton teleporters, aliens, revenants, nuke ops? The only problem with ninja is the infinite (bugged) invisibility

**Comment by Dorsisdwarf** [comment]
Whoops

**Comment by KorPhaeron** [comment]
>The only problem with ninja is the infinite (bugged) invisibility

That's a pretty big problem though. I can shoot the rest of those.

**Comment by Dorsisdwarf** [comment]
Then *fix the invisibility* instead of saying "Bug now feature, rest of feature now admin-only"

**Comment by KorPhaeron** [comment]
Except I said

>Ninja needs to be reworked before it shows up on its own.

**Comment by Bawhoppen** [comment]
rework =/= fixing 1 bug

**Comment by Lo6a4evskiy** [comment]
In Kor's defense, it is kinda like wizard showing up at random.

**Comment by Bawhoppen** [comment]
But wizards is full on meme, ninjas can easily be defeated if you know what you're doing

**Comment by KorPhaeron** [comment]
>rework =/= fixing 1 bug

Redoing invisibility code to break on attack is a rework though. 

Why are you being pointlessly contrarian and nitpicking words/phrases anyway?

**Comment by Bawhoppen** [comment]
It doesn't need a rework, it needs a single bug to be fixed, even if that is difficult technical-wise,

**Comment by GunHog** [comment]
Removing something due to a bug...sounds familiar...
I have not seen a natrual ninja spawn (in the round-end report) in a really long time. Do not be lazy, just fix the bug. It does not speak well of /tg/ coders to rip out entire features because of one correctable problem with it.

**Comment by KorPhaeron** [comment]
It isn't being removed though, it just isn't being randomly thrown into rounds.

**Comment by duncathan** [comment]
Remove don't improve is my favorite meme

**Comment by KorPhaeron** [comment]
It isn't even being removed aaaaaaaa

**Comment by Bawhoppen** [comment]
it is being REMOVED from normally appearing in the gam

**Comment by AlexCrimson** [comment]
I mean, it seems like it would make more sense to fix the invisibility bug rather than make the event admin-only. This will not fix anything, just make the butthurt less common.

**Comment by RemieRichards** [comment]
to be fair, the invisibility bug is a REALLY weird one.
I've attempted to fix it twice.
Aran tried to fix it.

that's 3 attempts, and it still just -doesn't- work.

**Comment by duncathan** [comment]
If anyone would like to fix the bug, they're more than welcome to. This PR didn't preclude that possibility.

**Comment by AlexCrimson** [comment]
Well this PR will just be like stuffing it all under your bed or in your wardrobe. Why fix it? Its admin-only after all!

**Comment by RemieRichards** [comment]
A brilliant point Alex.

**Comment by duncathan** [comment]
Why fix it? So it can return as a random event, duh. If people want it that badly, someone will fix it.

**Comment by tkdrg** [comment]
Why are people so obsessed with keeping a broken feature around? Ninja is awful right now and it really has no place being a random event. Being removed from that rotation here doesn't mean it's dead forever, it's only dead as long as nobody wants to work on it.

**Comment by Bawhoppen** [comment]
Its because it isn't awful, its a fun event that can help break up standstill shit rounds

**Comment by Lo6a4evskiy** [comment]
By the way, don't merge this because of the invisibility bug, I fixed it, it's just taking its sweet time to upload because I haven't updated my repo in a long time.

**Comment by Shadowlight213** [comment]
@Bawhoppen Have you actually tried fighting an invisible ninja? Their alpha is set to 0, meaning that they can't be seen by ANYTHING. Not sechuds, not thermals, not anything. Well, I think they can be targeted by mobs, but that's about it.
Perfect invisibility, armor piercing high damage infinite throwing stars, teleport, the ability to emag borgs, Stimulant speed, instant summons for their energy sword, etc. Ninja is a fun event for the ninja, it's not really fun for the crew to fight.
Are you seriously saying that because you might be able to see the tiny text in the lower left corner if you happen to mouse over the spot where the ninja is that it is a counter? Seriously?

**Comment by Bawhoppen** [comment]
@Shadowlight213 This game literally nearly entirely relies on reflexes, well-placed mouse movements, and careful vision of all your surroundings, you can easily be alerted to a ninja's presence by many factors, and then you know to keep up your guard

**Comment by Shadowlight213** [comment]
@Bawhoppen With that argument we should probably bring back cloakers then. Make it the same as ninja too, with 0 alpha so there is not way to see them at all. Since you can just mouse over them!

**Comment by Bawhoppen** [comment]
misses my point

**Comment by Shadowlight213** [comment]
What was your point then? From what I saw you were saying the only counter was essentially luck.

**Comment by ike709** [comment]
insert improve not remove meme here

**Comment by Anonus** [comment]
You can't be alerted to the presence of an invisible ninja unless they have an active light, they're COMPLETELY INVISIBLE and the most you can notice is a door opening or a number of corpses with sword or ninja star wounds.

**Comment by Bawhoppen** [comment]
My point, is that you can tell a ninja is around from many things like emagged and drained APCs,  throwing starts, piles of corpses with throwing stars in them, etc.
If you know one is around, they still have to be physically in your view radius to attack you, whether by throwing star or ekatana, after they attack, you will then know where they are and can easily retaliate with stunprod and force them to either be captured/killed or jaunt out

And thats even with the invisibility bug, which should be fixed

**Comment by Dorsisdwarf** [comment]
How to detect ninja: 

1) spot massive piles of dead people
2) draw disabler / any form of gun with lots of ammo
3) fire down corridors/ at any suspiciously opening doors
4) wait for the ninja to be hit and generate a big red message
5) mouse-over and click to death

**Comment by KorPhaeron** [comment]
I provoked someone into fixing ninja so I guess this PR served its purpose

**Pull request closed without merging**
