### PR TITLE
Make screentips and examine names use a shared proc, so prosopagnosia or other name hiders actually work with screentips

### PR DESCRIPTION
**Pull request by 00-Steven**
## About The Pull Request

So when I first started using the Prosopagnosia quirk, I was _very_ confused by the fact that it didn't seem to actually hide any names. And then I realized it only hides names on the examine, which is trivialized by the fact that screentips show you the name anyway.

So! I looked into the code.
```dm
(/code/modules/mob/living/carbon/human/examine.dm, line 1-20)
/mob/living/carbon/human/examine(mob/user)
	(...)
	var/obscure_name
	var/obscure_examine

	if(isliving(user))
		var/mob/living/L = user
		if(HAS_TRAIT(L, TRAIT_PROSOPAGNOSIA) || HAS_TRAIT(L, TRAIT_INVISIBLE_MAN))
			obscure_name = TRUE
		if(HAS_TRAIT(src, TRAIT_UNKNOWN))
			obscure_name = TRUE
			obscure_examine = TRUE

	. = list("<span class='info'>This is <EM>[!obscure_name ? name : "Unknown"]</EM>!")
```
Lo and behold, the code for hiding names based on prosopagnosia is *specific* to examining humans.
Case in point:
```dm
(/code/game/atom/_atom.dm, line 935)
active_hud.screentip_text.maptext = "<span class='context' style='text-align: center; color: [active_hud.screentip_color]'>[name][extra_context]</span>"
```
Screentips just use the name variable directly.

Sooooooo we just split this name obscuring check off into its own proc, `get_observed_name(mob/user)`.
```dm
(/code/game/atom/atom_examine.dm, line 109-110)
/atom/proc/get_observed_name(mob/user)
	return name

(/code/modules/mob/living/carbon/human/human_helpers.dm, line 59-65)
/mob/living/carbon/human/get_observed_name(mob/user)
	if(isliving(user))
		var/mob/living/living_user = user
		if(HAS_TRAIT(living_user, TRAIT_PROSOPAGNOSIA) || HAS_TRAIT(living_user, TRAIT_INVISIBLE_MAN) || HAS_TRAIT(src, TRAIT_UNKNOWN))
			return "Unknown"
	return ..()
```
And then just use that for both of them! This seems to fix the issue just fine.
## Why It's Good For The Game

Things that hid the examine name didn't actually hide the screentip name, like prosopagnosia or the unknown trait, making it completely trivial to get around them.
This fixes that.
## Changelog
:cl:
fix: Screentips actually account for name obscurers like prosopagnosia. For this sake, screentips and examine names now use the same proc, so please report any issues with this.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Might need to be profiled, adding new procs to screentips is always a little scary

**Comment by 00-Steven** [comment]
Understandable, would need to know _how_ first though

**Comment by SyncIt21** [comment]
> Might need to be profiled, adding new procs to screentips is always a little scary

I remember Lemon clearly being upset when people tried to change screentips at the atom level cause it's called every tick.

Furthermore this would encourage people to override this proc and write more complex code to compute a name causing even worse performance.

It's not worth it. Check for this trait at a lower level

**Comment by 00-Steven** [comment]
I mean, the traits themselves _are_ checked for only at the human level, currently.
But what are you thinking of?

**Comment by Mothblocks** [comment]
we cannot afford new proc calls in screentips. it is one of the hottest procs in the entire game

**Comment by Mothblocks** [comment]
if you want something like this, then you need to do it in the same way the signals work--bitflag/simple variable (notably, not trait ideally, because it's cheaper) on the user saying "i need more complicated screentips" (in this case, using observed names) that would then perform the work

**Comment by 00-Steven** [comment]
Right, thanks, that makes sense Mothblocks. I'll look into it probably a few days later or somesuch.

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
Oh, nevermind, Mothblocks makes a point here. We'll be waiting for the signals I guess.

**Comment by 00-Steven** [comment]
Mhmm, haven't had the time to look into it much and forgot to set it to draft, thanks.

**Pull request closed without merging**
