### PR TITLE
Fixes some things about husks

### LINKED ISSUE #18532: Beheading husks regrows hair, presumably creates implantable head
Cross-posting from https://github.com/HippieStationCode/HippieStation13/issues/2516. The head is still obviously that of a husk (except for the magically regenerating hair); I assume it can also be transplanted but have not gotten a chance to test it

### LINKED ISSUE #18584: Ling Stasis appearance bug
Changeling regen stasis doesn't fix the "burnt husk" look that you get after getting too much burn damage
Transforming doesn't fix it either
Terrible for stealth as everyone will know you're either badmin shennanigan spawn or a changeling or some other antag.

### PR DESCRIPTION
**Pull request by phil235**
Fixes some things about husked corpses. And changes other things?

This is a PR I started back in June, I still need to finish it.
Fixes #18532
Fixes #18584

:cl: phil235
fix: to be added
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
stale

**Comment by optimumtact** [comment]
@phil235 soon?

**Comment by phil235** [comment]
working on another PR at the moment, I'll finish this eventually.

**Comment by KorPhaeron** [comment]
Reopen when you're ready

**Pull request closed without merging**
