### PR TITLE
Statue DLC - Bluespace Da Vinci

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
(waiting on spriter to give me the proper cape/bluespace chisel sprites)

Adds:
- Bluespace chisels
- Engravable memory options to statues
- Sculpting skill that affects the beauty and art values of a statue
- Statues now have a sculpt duration that is based on the toughness of the material
- Sculpting statues now creates a mood event and memory
- Obsessed objective to sculpt a statue out of their target
- ~~Persistent statues~~ saving this for later

Fixes:
- Incorrect statue pixel offsets while sculpting
- Incorrect direction while sculpting
- No more weird statue lighting bugs caused from overlays (if you made statues out of lanterns you know what I'm talking about)
- getFlatIcon only rendering directions if facing south

I made a [spreadsheet](https://docs.google.com/spreadsheets/d/1qzraVAC1e6xFd9KbAF3iV9sPidP922KmclRMAEFOwA0/edit?usp=sharing) to show the effects.

## Why It's Good For The Game

d9rzk94-5f055a2d-30d5-4bb5-9fcd-7af35c8f066e

## Changelog
:cl:
add: Add bluespace chisels that let you sculpt faster and create animated statues
add: Add sculpting skill that affects statue beauty/art values and legendary cape
add: Add mood event and memory when a statue is sculpted
add: Statues can now be engraved with memories
add: Statues now have a sculpt duration based on the toughness of the material
add: Obsessed objective to sculpt a statue out of their target
fix: Fix incorrect pixel offsets, direction, and lighting bugs while sculpting statues.
image: Add sprites for sculpting legendary cape and bluespace chisel 
refactor: Refactor statue code to be more robust
/:cl:

### CODE REVIEW

**Comment by Dawnseer** [comment]
What's the sculpting skill do? Make you sculpt faster? Make the statues look nicer when people examine them?

**Comment by DATA-xPUNGED** [comment]
Bluespace is tied to teleporting and non-euclidean storage, how does it sculpt animated statues here

**Review by Wallemations — CHANGES_REQUESTED** [review]
If you're still waiting on the sprites then I'd say draft this so people don't merge it on accident, otherwise if you do it yourself the chisel shouldn't be hard at all, just a change to the handle/blade colors would suffice

**Comment by timothymtorres** [comment]
> What's the sculpting skill do? Make you sculpt faster? Make the statues look nicer when people examine them?

The skill lets you sculpt statues faster and gives an art and beauty boost to the statues.  I added a handy dandy spreadsheet in the OP for reference.

> Bluespace is tied to teleporting and non-euclidean storage, how does it sculpt animated statues here

Using new revolutionary technology and techniques NT now has bluespace chisels that can sculpt statues from the inside out. By tearing the fabric of space and time, it is able to embed past animations onto the statue itself.

**Pull request closed without merging**
