### PR TITLE
Removes uninspired "me-too" bee meme content

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Removes the bee syndicate pack, the bee sword and the bee socks.

The bee plushie can stay, it's cute and harmless and also someone put more effort into it than "hurr durr bees".

## Changelog
:cl: Naksu
del: Removed surplus bees
/:cl:

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
image

**Comment by wesoda25** [comment]
ya excellent PR but it’d be nice if you added another bundle in compensation for bee kit bc I honestly feel it made special kit better, the memey side annoyed me tho

**Comment by necromanceranne** [comment]
I do not understand why bee socks have to go. Bee socks are good.

**Comment by HomocidlePancakes** [comment]
I’d remove just the socks and keep the rest. Per every pair of socks, thigh highs and skirts we remove the world becomes *slightly* better

**Comment by Rowelll** [comment]
meh

**Comment by kriskog** [comment]
I may have missed something, but why do we suddenly hate bees?

**Comment by HomocidlePancakes** [comment]
We don’t. It’s just the OP

**Comment by kriskog** [comment]
image

**Comment by nemvar** [comment]
> The bee plushie can stay, it's cute and harmless and also someone put more effort into it than "hurr durr bees".

I didn't though.

**Comment by Krysonism** [comment]
At least one maintainer has said he would merge this as soon as possible. ¨

It is a bad idea to reflexively cut good new content, such as the bee bundle, that i bet the maintainer is question never even have tried in a a live game.

**Comment by vuonojenmustaturska** [comment]
empty references are not content

**Comment by necromanceranne** [comment]
Empty references to what? Bees? Bees are just bees.

**Comment by Krysonism** [comment]
> 
> 
> empty references are not content

That is not what i said, argue in good faith!

A syndicate bundle is indeed content, and the bee one is better and more functional than a few others that come to mind.

**Comment by ExcessiveUseOfCobblestone** [comment]
the bee suit will forever be based and untouchable.

**Comment by Detective-Google** [comment]
one the one hand, we aren't goonstation
our bees don't have cutesie sprites, they're just bees.
it's kinda their mascot.

That being said, we need our own animal mascot, so we need Vomi/tg/oose socks, suit, ands weapons NOW.

**Comment by ExcessiveUseOfCobblestone** [comment]
can we have space runtime instead I think it will make for great merch opportunities.

**Comment by Dorsisdwarf** [comment]
Ian is our mascot

**Comment by granpawalton** [comment]
If the bee surplus is staying in it should be more syndicate themed than some goofy yellow bee suit, fannypack, and a poisoned bee pun sword

**Comment by Geikkamir** [comment]
All of the gimmick bundles are goofy as shit though

**Comment by SpaceManiac** [comment]
Merge conflict

**Comment by Arathianen** [comment]
People who like to shit on other people for liking things they don't like can jump off a fucking cliff.

How do bee socks negatively affect your experience exactly?

They don't. So shut the fuck up and close this shit PR.

**Comment by wesoda25** [comment]
Shitty meme content improves the game in no discernible way and is a complete waste of space

**Comment by ExcessiveUseOfCobblestone** [comment]
:(

**Comment by vuonojenmustaturska** [comment]
Rise from your grave

**Comment by trollbreeder** [comment]
Do you even think you can get this merged with this amount of conflicting files, you level 10 necromancer?

**Comment by vuonojenmustaturska** [comment]
I'll re-do the DMIs in a few hours

**Comment by vuonojenmustaturska** [comment]
also, yes, i know how git works

**Comment by trollbreeder** [comment]
Also this is a self reopen which is like merging your own PR lite

**Comment by trollbreeder** [comment]
And back to the PR itself: Why remove other than "bees lol not funny"?

**Comment by necromanceranne** [comment]
We've had this shit for nearly a year why bother reopening it now?

**Comment by Fikou** [comment]
cringe

**Comment by Spepbuthewranglesgithub** [comment]
the entirety of goonstation's playerbase would be ashamed of you.


_also why is this back_

**Comment by cacogen** [comment]
>the entirety of goonstation's playerbase would be ashamed of you.

not a bad thing

**Comment by Tharcoonvagh** [comment]
Ided

**Comment by vuonojenmustaturska** [comment]
it's back because i reopened it

**Pull request closed without merging**
