### PR TITLE
Fixes timSort

### PR DESCRIPTION
**Pull request by ghost**
:sob::gun:

### CODE REVIEW

**Comment by Cheridan** [comment]
Can you give more information on what was wrong? Just the off-by-one error?

**Comment by Carn** [comment]
MoveRange was behaving differently when fromIndex > toIndex, when fixed, it caused offset errors in timSort
When fixed this caused errors in galloping mode.

All should be fixed. I've had it brute-sorting random-length randomised lists then testing, using a simple for loop with a break-on-error to detect errors. It was running for 3+ hours with no errors.

**Comment by Carn** [comment]
Basically I say basically a lot, basically

**Comment by Cheridan** [comment]
Thanks for the clarification :mag_right:

**Pull request merged**
