### PR TITLE
Juke Build 0.9.0

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

Next step in consolidating all build in Juke Build.

### `tgui/bin` folder was moved one level up

Bash and PowerShell scripts for TGUI have been removed, because they duplicated too much functionality. They have been fully consolidated in Juke Build for a while, and each of them is now reachable via a bunch of `bin/*.cmd` files in tgstation root, so in practice, they were pushed one level higher and became launchers.

Each of these cmd scripts now **pauses on error**. This feature uses a known quirk of Juke Build, that prevents the command window from closing during normal operation, and it's used to suspend the window on error, and immediately close it on success. I think it's very nice. **Needs testing**.

Not only that, but each of the build steps is also individually accessible via Yarn, because they are declared in `package.json` scripts field. So, back to good old days. I think it provides this missing flexibility of running build steps manually, and it dramatically shrinks the size of the build file (because each invocation of package.json scripts is just one line in `build.js`).

You might discover some new things like `tgui-sonar`, I'm pretty sure nobody knew about it, so now you can smell your bad code in its full glory.

### CODE REVIEW

**Comment by stylemistake** [comment]
Actually, I will add `librust_g.so` compilation in another PR.

**Comment by mokulus** [comment]
Right now on master ./tools/build/build.bat clean master doesn't work but used to. I think it's because dm and clean build targets are started in parallel. I've bisected and this seems to introduce this.

**Comment by maxymax13** [comment]
building is now completely broken for me, what did you coders do now

**Comment by stylemistake** [comment]
uninstall node, run bin/clean.cmd, build again

**Pull request merged**
