### PR TITLE
Adds donald trump hair

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

This PR adds in Trump's famous combover which gloriously flaps about in the wind

## Why It's Good For The Game

https://gyazo.com/fa7ac667fe2326d2eb6f26d82fff2799

Gentlemen and gentlemen, I present to you:
The apex roleplay feature

This pr allows your OC to have FULL 30FPS animated hair.

Imagine the possibilities.
-As a captain you can make your skin orange and wear this hair, then have your hair gloriously flap about as you execute traitors with the guillotine
-As a nukeop, you can start the trump family of operatives and watch your enemies BASK in your fantastic hair-styling skills.

I'm open to suggestions on extra hair styles, so if you have any put them down in the comments below

Thanks for your attention :)

(If you want i can change the name to combover instead)

## Changelog
:cl: Kmc2000
add: Added Donald Trump's combover that flaps about when you walk
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
fuck you orange man

**Comment by FantasticFwoosh** [comment]
There actually isn't any legitmate reason to close this, unless oranges would like to clarify what they mean on a high quality PR; we have other hairstyles from a number of other pop-culture sources.

> Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

Trumps hair is otherworldly and possibly sentient but im hard pressed to believe it would have a reason to be blocked.

**Comment by Kmc2000** [comment]
/shrug
I put this down to Oranges' daily meme quota

A shame because I liked the hair but ah well

**Comment by optimumtact** [comment]
I'm not adding anything from that weird orange golem to this game

**Pull request closed without merging**
