### PR TITLE
Makes the spelling of 'mjollnir' consistant and renames singularityhammer.dm to wizard_weapons.dm 2

### PR DESCRIPTION
**Pull request by D4C-420**
## About The Pull Request

All the below copied from #79588 

Does as the tin says and renames all instances of 'mjolnir' to 'mjollnir' . They are TECHNICALLY both correct but because 'mjolnir' was only used for the spelling in game for the hammer itself and the icon when worn on the back I decided on two l's.  This also means I had to change the icon name for the back sprite 

If I'm missing any files with it spelt 'mjolnir' please tell me

While I was at it i also decided to change singularityhammer.dm to wizard_weapons.dm because apparently the file is supposed to be where wizard weapon are stored and having it be named after a single weapon is confusing incase people add more weapons later on. 

## Why It's Good For The Game
More consistent spelling.

Code wise it makes it more clear what the intended use for a file is
 

## Changelog
:cl:
spellcheck: hopefully changed all instances of the word 'mjolnir' to 'mjollnir'
/:cl:

### CODE REVIEW

**Comment by D4C-420** [comment]
Everything should be the same from #79588. Yada yada ya I messed up while fixing conflicts

**Comment by ATH1909** [comment]
wait, is mjollnir actually the more common spelling irl? autocorrect wants to correct it to Mjolnir.

**Comment by Ghommie** [comment]
> wait, is mjollnir actually the more common spelling irl? autocorrect wants to correct it to Mjolnir.

Kinda, it's actually Mjöllnir, but he said he doesn't want the umlaut in the name. Mjolnir as a simplified, english keyboard-friendly is also correct. Anyway, this is simply about consistency. 🤷

**Comment by D4C-420** [comment]
> Also, you could have used git reset or git revert and try again instead of making a new PR on a new branch, but we're over it now...

Noted for next time.

<details>
<summary>Real reason why I made a new pr</summary>

Honestly I had tried to solve the conflicts by downloading the current versions from master, replacing my local files then adding my changes but that had seemed to mess it up and I ended up using git checkout cause desktop would not let me revert (which seems to have been a bad idea), and accidentally messed up my main, and in the end I had to  clone the repo again which meant making a new pr
</details>

Anyway this should be ready to merge if there's no other places where 'Mjolnir' is used to refer to the hammer and no issues with my renaming of singularityhammer.dm

**Pull request merged**
