### PR TITLE
Brings tgstation into compliance with international law

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Recolours the cross on syndicate medical duffles to not be red, as the red cross is a protected symbol and we're not actually allowed to use it.
image

## Why It's Good For The Game

We should probably follow international law before we get a strongly worded letter from the ICRC

## Changelog

:cl:
imageadd: The Syndicate have removed the Red Cross symbol from their medical duffle bags to comply with intergalactic law (Even they're not evil enough to misuse protected symbols)
/:cl:

### CODE REVIEW

**Comment by UnokiAs** [comment]
Tg station is now safe from a red cross raid 🙏

**Comment by Thunder12345** [comment]
I tried that first, it sucks and no longer looks like a cross
image

**Comment by unit0016** [comment]
Damn.

**Comment by alphanerdd** [comment]
> Honestly the colors.. clash a bit much for my eye-holes. Maybe switch the white and red out for each other instead?

Idk I kind of like the colors. It immediately catches your attention, and is instantly identifiable as med shit.

Being spared from the wrath of the Red Cross is a nice bonus.

**Comment by CRITAWAKETS** [comment]
be like doom, make it green

**Comment by sergeirocks100** [comment]
I'd recommend making the crosses the same shade of blue as the medbay ones, just for consistency's sake.

**Comment by Sealed101** [comment]
needs a more evil shade of blue or maybe just use green

**Comment by Thunder12345** [comment]
Medkit blue is a bit too pale at such a small scale, it starts to fade into the white and be less visible. I tried green as well, but had similar problems there

**Comment by cacogen** [comment]
>I tried that first, it sucks and no longer looks like a cross

You didn't add any shading to the white, of course it looks unnatural. 

Looking at IconDiffBot, the red cross looked bad as well so it doesn't really matter if the blue one looks bad for the same reasons. At least it's consistent with the other crosses in the game.

**Comment by Zonespace27** [comment]
The item sprite, to me looks fine but the on mob sprites look a bit... off to me

**Comment by optimumtact** [comment]
i prefer to wait for the letter

**Comment by optimumtact** [comment]
@tgstation/sprite-team does this look any better? otherwise im closing it.

**Comment by notfrying1pans** [comment]
> be like doom, make it green

we used green for med until like 2014

**Comment by Twaticus** [comment]
it doesnt and also i didnt even know it was supposed to be a cross to begin with

**Comment by Imaginos16** [comment]
I'd rather wait for the letter. Its a very very small detail when ninety nine percent of our crosses are a different color already.

**Comment by timothymtorres** [comment]
> i prefer to wait for the letter

What is Nanotrasen's mailing address?

**Comment by Kurgis** [comment]
> What is Nanotrasen's mailing address?

Go outside with a letter and a rocket, send it off and godspeed.

**Comment by UnokiAs** [comment]
[RED CROSS RAID IN PROGRESS /// 💀 💀 💀] 🔺

**Pull request closed without merging**
