### PR TITLE
surgery is now slower instead of failing

### PR DESCRIPTION
**Pull request by jdawg1290**
## About The Pull Request
Removes failure chances from surgery.
suboptimal tools and surfaces now delay surgery instead.
sterilizers now boost speed.

## Why It's Good For The Game
Hopefully encourages use of field surgery while limiting its effectiveness compared to a proper surgical suite

## Changelog
:cl: JDawg1290
del: Surgery can no longer be failed
balance: suboptimal tools and surfaces now slow down surgery instead of causing failure. Sterilizers increase speed.
/:cl:

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Fix the comments, they're all out of date now. Besides that. I think the speed modifier and fail chance should both exist, with fail chance just being more rare.

**Comment by jdawg1290** [comment]
Any comments that need updating in particular? Also the maintainer said no fail chance at all.

**Comment by ATH1909** [comment]
But what about lobotomies and the like?

**Comment by Michael-Ashfield** [comment]
> But what about lobotomies and the like?

This is true, failure of delicate surgeries like coronary bypass, brain surgery, brainwashing are all sorta of balanced around the fact that you need to do surgery in the right conditions or you will mess up your patient, this would allow a janitor to perform brain and heart surgery on maint floor using wirecutters and glass shards

**Comment by jdawg1290** [comment]
Penalties are multiplicative. Floor dissection with a knife takes upwards of four minutes just for the dissection step.

**Comment by XDTM** [comment]
Also removes all potential for faking failure

**Comment by CRITAWAKETS** [comment]
> > But what about lobotomies and the like?
> 
> This is true, failure of delicate surgeries like coronary bypass, brain surgery, brainwashing are all sorta of balanced around the fact that you need to do surgery in the right conditions or you will mess up your patient, this would allow a janitor to perform brain and heart surgery on maint floor using wirecutters and glass shards

You cant do most of those surgeries without the operating computer being right next to you.

**Comment by jdawg1290** [comment]
If surgery can only be failed on purpose, then people would metagame the shit out it. Instead consider f. Ex. Performing brain removal instead of brain surgery if you want to fuck people up.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Also removes all potential for faking failure

Not really for this PR but the long term to "readd" this would be obscuring steps so the sabotage goes from pretend-fail to doing a different surgery under their nose.

Making failure simply lower would also lower the already extremely low plausible deniability in repeatedly failing most surgery steps in the game.

**Comment by XDTM** [comment]
@ExcessiveUseOfCobblestone i already added that semi-recently; patients and people watching from more than one tile away see semi-ambiguous messages that allow for some misdirection (for example, brainwashing looks the same as brain surgery).

I'm torn on failure as a mechanic, since it is frustrating and stifles the use of surgery outside of surgery rooms, but i also don't want to let go of the potential of someone """accidentally""" severing a critical brain artery during routine brain surgery, which is the first thing one would imagine doing as a traitor surgeon.

**Comment by PKPenguin321** [comment]
After a slowness threshold, slowness should no longer increase and you should have an increasing chance to fail. The slowest guaranteed rate would be maybe 30 seconds per step (not exact values), and getting worse conditions than that will instead bump up a failure chance while the time per step stays at 30 seconds.

**Comment by Fox-McCloud** [comment]
yeah, I'm...not a fan of this.

It removes the consequences of doing poorly at surgery while also making intentionally messing up surgery completely unviable and 100% metagamable.

**Comment by OverlyGeneric** [comment]
This is very much a hugbox feature.

I don't think it even makes sense to have the shady back-alley implant surgeons in the dirty depths of maintenance be on par with safety and healthy surgical conditions as the sterile clean environment of professional malpractitioners.

**Comment by AarontheIdiot** [comment]
If this was merged, ghetto surgeries or surgeries in sub optimal conditions would have no risk. Being slower is not really interesting.

**Comment by Difrit** [comment]
> Penalties are multiplicative. Floor dissection with a knife takes upwards of four minutes just for the dissection step.

Excuse me what the fuck
Failure chances are what make doing surgeries outside of surgery a risky and fun choice, just increasing the time and making everything succeed is super dumb and just slows gameplay down with no real result

**Comment by Learner10** [comment]
Gotta agree with some of the folks. Otherwise, you end up with situations like "Hey, I know this dirty maintenance floor is uncomfortable, but don't worry, I've got a pen. I'll get that brain of yours fixed, because there's no way I can mess up. Why? I'll just do it slower and take my time. It'll only take about as long for the shuttle to arrive, leave, and land at Centcomm for it to get done."

**Comment by PKPenguin321** [comment]
Yeah this seems real bad as-is, I think I will PR my thing as an alternative

**Comment by PKPenguin321** [comment]
I done gone and did it

**Comment by jdawg1290** [comment]
Pkps is better so closing. Will leave branch up.

**Pull request closed without merging**
