### PR TITLE
Blobbernauts can no longer smash walls.

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Blobbernauts can no longer smash walls of any type.
/:cl:
## You know why.

Blobbernauts also get a more accurate description when spawned.

### CODE REVIEW

**Comment by GunHog** [comment]
:(

**Comment by Incoming5643** [comment]
They are the koolaid man and I refuse to believe otherwise :-1:

**Comment by Anonus** [comment]
# OOOOOH NO

**Comment by PKPenguin321** [comment]
Is this because we're making them player controlled?

**Comment by Anonus** [comment]
It is, very much so.
Players cannot be trusted with anything.

**Comment by Jazaen** [comment]
Let's make SS13 a playerless station simulator, shall we?
Though, to be honest, :+1: because once goofy AI is replaced by a player blobbernauts become hilariously OP. Best blob strategy right now is, as soon as you can afford to do so repeatedly, to spam them.

**Pull request merged**
