### PR TITLE
Fixes turret placement in boxstation's AI core.

### LINKED ISSUE #19044: box AI core turrets can't hit anything in front of the AI core.
they told me the new projectiles didn't change their path!

### PR DESCRIPTION
**Pull request by WJohn**
Fixes #19044 
Moved top two turrets up by one tile. They are now capable of hitting these areas like they used to before pixel projectiles.

:cl: WJohn
fix: AI core turrets can once again hit you if you are standing in front of the glass panes, or in the viewing area's doorway.
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
Its not like you can shoot the apc with a ion rifle anyways

**Comment by Anonmare** [comment]
Well you can shoot the APC with a proper laser weapon still

**Comment by jughu** [comment]
not really killing if you can shoot these apcs too

**Comment by YakumoChen** [comment]
finally

**Pull request merged**
