### PR TITLE
Adds a hacked autolathe subtype

### LINKED ISSUE #31384: Map maker autolathe with "hacked" set to 1 does not actually spawn in hacked.
Though it will have the variable set to 1 as normal, you won't get the expanded inventory. When hacking and looking into the wires, the blue light will show itself to be on as normal, but the corresponding wire will not be cut. You have to cut the corresponding wire in order to actually get the expanded inventory (blue light remains on before and after cutting).

### PR DESCRIPTION
**Pull request by Cyberboss**
Closes #31384

### CODE REVIEW

**Comment by ShizCalev** [comment]
Is it fine to have a type defined only by a proc override? Thought that was considered a bad thing to do.

**Comment by msgerbs** [comment]
Surely the new subtype should also have its hacked var set at least? As it stands you'd have to use this subtype, but then also varedit it to start hacked.

**Comment by Cyberboss** [comment]
The proc I called does that itself

**Comment by msgerbs** [comment]
Never mind I am dumb.

**Pull request merged**
