### PR TITLE
Fixes another instance where the mulligan system just starts screaming at admins instead of doing anything

### LINKED ISSUE #8774: Failed convert roundtypes don't end the round and spam adminlog
ADMIN LOG: Convert_roundtype failed due to round length. Limit is 60 minutes.
Unknown gasps!
The mouse runs in a circle
ADMIN LOG: Convert_roundtype failed due to round length. Limit is 60 minutes.
The mouse squeeks
ADMIN LOG: Convert_roundtype failed due to round length. Limit is 60 minutes.
OOC: Arfeudutyr: Way to fuck up, AI.
ADMIN LOG: Convert_roundtype failed due to round length. Limit is 60 minutes.
ADMIN LOG: MrStonedOne/(Alpha 6) is considering ending the round.

The same thing happens for the dead count check

I've seen this with malf ai and blob.

@Incoming5643

### PR DESCRIPTION
**Pull request by Incoming5643**
"The Mulligan system, as it exists today, is practically bug free"
-Incoming 4/5/15

Fixes #8774

### CODE REVIEW

**Comment by RemieRichards** [comment]
heh I did this too (returning numerical values when you actually want a null or alpha value)

**Comment by optimumtact** [comment]
Bug free this time for sure :smile:

**Comment by An0n3** [comment]
There should be an accompanying game option to turn this thing on or off.

Ostensibly it sounds like a good idea but deciding what to do with a round when things are winding down or a curveball gets thrown is something the admins on the server should be deciding, not a random number generator.  I don't like taking that opportunity for FUN out of people's hands and letting what is basically Tensioner 2.0 handle it.

**Comment by Incoming5643** [comment]
There was a way to toggle it off preemptively for a round in #8586 but it's gotten hold up in the size of it. I'll try to isolate it and give it its own commit sooner rather than later.

If you're talking about just disabling it completely you can easily do that by the methods I put out in the bottom half of this message https://tgstation13.org/phpBB/viewtopic.php?f=10&t=3088#p74719

but I really do think there's a good idea here somewhere so I'd rather it was left on in some respect. This feature is a huge pain to work with because the only way I can really test it is on a live populated server, so if it's turned off it will probably never reach a state I'd call complete in terms of development.

**Comment by Incoming5643** [comment]
@An0n3 #8859 will make it easier

**Pull request merged**
