### PR TITLE
[QoL] Transfer TGchat notifications to the top

### PR DESCRIPTION
**Pull request by AyIong**
## About The Pull Request
Right now the notifications are not conveniently located, as when the server is initialised, it is quite problematic to communicate OOC
Actually this inconvenience I would like to solve

Also reconnect/restart buttons have been slightly modified
| Before | After |
| - | - |
| dreamseeker_aYyT5cewaz | image |

## Why It's Good For The Game
Now you can discuss the last round without waiting for the server to fully initialise

## Changelog

:cl:
qol: Chat notifications are now at the top
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Moving to the top is good but I think just having "relaunch game" be a power button is a bit misleading, even if it does have a tooltip

**Comment by AyIong** [comment]
> Moving to the top is good but I think just having "relaunch game" be a power button is a bit misleading, even if it does have a tooltip

I couldn't find a better icon, any suggestions?

**Comment by optimumtact** [comment]
Leave it as text? it doens't need to be a random ass icon.

**Comment by AyIong** [comment]
> Leave it as text? it doens't need to be a random ass icon.

Then it won't be compact 
image

**Comment by jlsnow301** [comment]
> I couldn't find a better icon, any suggestions?

don't think history makes a good reconnect button either. wb network-wired and sync, respectively?

**Comment by stylemistake** [comment]
Leave reconnect as text only button, relaunch as icon.

**Pull request merged**
