### PR TITLE
Revert gulpfs version to 6d71a65 in tgui

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
it works, gimme my 5 GBP

**Comment by MrDoomBringer** [comment]
[hes boutta do it](https://i.imgur.com/EPZqtWu.png)

**Comment by lordpidey** [comment]
Why is this important?

**Comment by ninjanomnom** [comment]
The tag gives 5 points and currently travis is making every pr fail.

**Pull request merged**
