### PR TITLE
acutally implements the science and slime bounties

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: you can now get slime and science cargo bounties
/:cl:

they were added but werent in the bounty list generated round start

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
while you're at it can you replace all of those loops with contributing.md form `var/i in 1 to X`

**Comment by ExcessiveUseOfCobblestone** [comment]
actually wow that proc lol

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
`for(var/i = 0; i < 1; ++i)`
is more correctly:
`for(var/i in 1 to 1)`
Yes it's dumb.

**Comment by ExcessiveUseOfCobblestone** [comment]
that's what he has rn after the aaaaaaaaaaaaaaaaaaaa commit

**Comment by SpaceManiac** [comment]
`=0, <1` is just one value, `0`
`1 to 2` is two values, `1` and `2`

**Comment by ExcessiveUseOfCobblestone** [comment]
oh I misread youre .... commit :^)

**Comment by optimumtact** [comment]
Is this ready @vuonojenmustaturska

**Comment by ExcessiveUseOfCobblestone** [comment]
so wait, the `for` is literally useless for some of these bounties?

**Comment by Tlaltecuhtli** [comment]
i left the for in case someone wants to add more (in the future) but i guess ur pr predates this

**Pull request closed without merging**
