### PR TITLE
Adds Sovereign Citizens to the game.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
add: Adds Sovereign Citizens to the game as a job.
/:cl:

### CODE REVIEW

**Comment by Isratosh** [comment]
yes, of course

**Comment by Firecage** [comment]
Ugh, way to clutter up the pull request list.

**Comment by Iamgoofball** [comment]
THIS IS A SOVERIGN PR YOU HAVE NO POWER HERE

**Comment by KorPhaeron** [comment]
dont tread on me

**Comment by RemieRichards** [comment]
[!Imgur](http://i.imgur.com/qmONVnc.png)
@Iamgoofball but I control time as you can clearly see.

**Comment by Iamgoofball** [comment]
>>>contradicting the """design""" """"""lead""""""

**Comment by ike709** [comment]
moving us closer to #20000 one meme pr at a time

**Comment by Iamgoofball** [comment]
ARTICLES OF CONFEDERATION

**Comment by Cheridan** [comment]
am i being detained?

**Comment by Iamgoofball** [comment]
I KNOW MY RIGHTS

**Comment by KorPhaeron** [comment]
am I free to go?

**Comment by RemieRichards** [comment]
@KorPhaeron fraid not.

**Comment by Iamgoofball** [comment]
ARTICLES
OF
CONFEDERATION

**Comment by TheColdTurtle** [comment]
MAINTAINERS I HAVE A RIGHT TO POST, YOU ARE VIOLATING THE ARTICLES OF CONFEDERATION

**Comment by KorPhaeron** [comment]
iamgoofball's right to make garbage prs SHALL NOT BE INFRINGED

**Comment by Iamgoofball** [comment]
i know my RIGHTS

**Comment by optimumtact** [comment]
Neo: Yeah. That sounds like a really good deal. But I got a better one. How about... I give you the finger... and you give me my phone call?

Agent Smith: Mr. Anderson... you disappoint me.

Neo: You can't scare me with this Gestapo crap. I know my rights. I want my phone call.

Agent Smith: Tell me, Mr. Anderson... what good is a phone call... if you're unable to speak?

**Pull request closed without merging**
