### PR TITLE
Improve the naming of the element argument hash index selector

### PR DESCRIPTION
**Pull request by optimumtact**
So confusing name

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
I still think we should remove this entirely

**Comment by optimumtact** [comment]
> I still think we should remove this entirely

How would people make their elements bespoke then

**Comment by Mothblocks** [comment]
with the flag ELEMENT_BESPOKE like they're already doing

**Comment by tralezab** [comment]
shore

**Pull request merged**
