### PR TITLE
Removes vocaloids costume

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
What are these

**Comment by Iamgoofball** [comment]
they're the costumes from those hatsune things that danno added

**Comment by Militaires** [comment]
thank fuck i love you

**Comment by Militaires** [comment]
dreamseeker_2017-03-23_20-42-18

**Comment by Incoming5643** [comment]
eh these are a little less flavor of the month than the other two pulls...

**Comment by lzimann** [comment]
it'sn ot a meme of the month but a good riddance

**Comment by Armhulen** [comment]
tfw you thought this was holoparasites

**Comment by Cheridan** [comment]
what i dont get is why this was added as a costume instead of a holoprojector option for the ai

uhh fuck forget i said that

**Comment by Repukan** [comment]
Vocaloids, they're called I think

**Comment by PKPenguin321** [comment]
Oh dang

**Comment by Militaires** [comment]
>remie closes this without any given reason

**Comment by Repukan** [comment]
He's right though, all of these are meme shit that don't belong

**Comment by Iamgoofball** [comment]
Why?

**Comment by Repukan** [comment]
Can you at least give a refusal or an explanation why this holds no water, Remie?

**Comment by RemieRichards** [comment]
It says in the title, "goof is being an outdated meme"
While he has the point that there's no point to this content, it's optional, so there's no point to not having it. His argument on RSC sizes was already debunked, so all that remains is his personal dislike of the content (and boy does it show)

If I were to do the same crusade against things I didn't like, I'd expect the same response, quite rightly.

**Comment by FantasticFwoosh** [comment]
Its not optional to remove it evidently by you shutting & overruling the thread.

**Comment by RemieRichards** [comment]
as I said before, you have the reading comprehension of a dead potato.

**Comment by Militaires** [comment]
@RemieRichards maybe the fact that it's supported by people ingame should let it stay 

i mean you're not giving solid points either

>it's optional, so there's no point to not having it. 

buddy boy friend son man guy dude diego santoro amigo zŏl something being optional is not a reason for it be in but rather an excuse, content that has no place ingame rather than to appease 3 autists is the definition of "bloat".

**Comment by RemieRichards** [comment]
Nobody's listening to you.

**Comment by Militaires** [comment]
@RemieRichards  and i'm not to blame.

it's not to listen to people when you're a maintainer, no?

**Comment by RemieRichards** [comment]
my job is to stop shit PRs, and to support good ones, and I'm doing just that.

**Comment by Militaires** [comment]
also you misread the title it's not "goof being an outdated meme" it's "goof's [outdated meme] removal PR".

@RemieRichards the reasons you provided as to why this pr should be closed are inadequate

**Comment by RemieRichards** [comment]
>misread it

What is satire?

**Comment by Militaires** [comment]
@RemieRichards 

it being made by goof being the first thing you mentioned; I assure you if it was not goof that had made that pr you would have not closed it, and that's really ad hominem if you think about it cause the big apple that closed the goof pr was it being a  goof pr.

>While he has the point that there's no point to this content, it's optional, so there's no point to not having it. His argument on RSC sizes was already debunked, so all that remains is his personal dislike of the content (and boy does it show)

that's your main point 

>it's optional, so there's no point to not having it.

something being optional doesn't validate its exist or justify it. maybe you're taking it as that because it's between keeping it and removing it from the game, which is pretty much a "middle-grounds" fallacy.

**Comment by RemieRichards** [comment]
The Decision was made.

**Comment by Cheridan** [comment]
overruled

**Comment by kevinz000** [comment]
remie's right.

**Comment by Haevacht** [comment]
Cheridan that's fucking dumb.

**Comment by Xhuis** [comment]
Couldn't the drama be avoided if we just put "removes vocaloid outfits" in the title and kept it at that

**Comment by optimumtact** [comment]
I don't care about this one

**Comment by KorPhaeron** [comment]
Just make it adminspawn. Could be a silly rare ruin easter egg or something

**Comment by Bawhoppen** [comment]
Just cause you don't like something doesn't mean it should be removed????

**Comment by lzimann** [comment]
@KorPhaeron it is what he is doing basically

**Comment by ShadowDeath6** [comment]
tbh I never really liked things ingame that referenced pop culture, it makes no sense for a station completely isolated from any planet similar to earth and 500-however years in the future to have the colored suits from lazytown and japanese robot singers

and I mean like to the lore of the thing, not the "oh but wizards with hotrods throwing fireballs and using stands" kind of no sense

**Comment by RemieRichards** [comment]
@Cheridan You're wrong, but whatever.

**Comment by RemieRichards** [comment]
>see this one doesnt seem to have any support so i'll close it
wow that was hard

**Comment by Core0verload** [comment]
Just give a PR 24 hours before closing it. The only exception is meme PRs, and this is not

wait

no, it's goof's PR, you did nothing wrong.

**Comment by Cheridan** [comment]
No I'm not

**Pull request closed without merging**
