### PR TITLE
Fixes the mulligan reagent recipe

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
fix: The mulligan reagent can now be created with 1u stable mutation
toxin + 1u unstable mutagen.
/:cl:

There is no "humanmutationtoxin", that's just stable mutation toxin.

### CODE REVIEW

**Comment by XDTM** [comment]
oh right i never got around to fixing that, thanks

**Comment by juanototo2** [comment]
### **CHEMISTRY POWERCREEP**

No but seriously you can get the effect of a TATOR ITEM via a bit of help from xenobio. Remember how xenobio turned basically everyone on the station into an  ayy? This'll be worse.

**Comment by coiax** [comment]
This balance change was already made, I'm just fixing a bug that prevents it from working.

**Comment by optimumtact** [comment]
if it's shit I will expect a nerf pr up within a day or two

**Pull request merged**
