### PR TITLE
CTF players are no longer 13 year olds

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

CTF ids now have registered_age = 30 so they won't show a large flashing message about players being underaged for drinking which is pretty annoying

## Why It's Good For The Game

CTF IDs no longer show an annoying message, which is good

## Changelog
:cl:
fix: CTF IDs no longer show message about holder being underage
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
ctf is not the only place with this, you should increase the default age in the code to like 18 or 20 instead of every id being a minor by default

**Comment by SmArtKar** [comment]
> ctf is not the only place with this, you should increase the default age define in the code to like 18 or 20 instead of every id being a minor by default

Yeah, probably

**Comment by maxymax13** [comment]
there was a comment about the joke about this being the average age of the ss13 player but it got zapped during the trim nonsense, noo not my soul

**Comment by ishitbyabullet** [comment]
mentally immature, physically mature

**Comment by Mothblocks** [comment]
> so they won't show a large flashing message about players being underaged for drinking

What? When do they have access to a booze machine? Is it something in the new CTF maps I'm not aware of?

**Comment by SmArtKar** [comment]
> > so they won't show a large flashing message about players being underaged for drinking
> 
> What? When do they have access to a booze machine? Is it something in the new CTF maps I'm not aware of?

No, when you examine your ID.

**Comment by Mothblocks** [comment]
Oh, whatever then.

**Comment by KathrinBailey** [comment]
Only people around ages 7 to 14 play laser tag, this broke my immersion revert plox.
Also you aren't allowed to play laser tag CTF at age 30 because that's too much fun. It's illegal to have fun at that age. This is unrealistic and has no place on TG's MRP servers.
/s

**Pull request merged**
