### PR TITLE
pAI languages and app economy

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This PR attempts to alter the pAI app economy by making crew languages default languages instead of app languages.

**This is not meant to contravene the intent of the recent and controversial silicon language changes, so please read the next section thoroughly.**

## Why It's Good For The Game

So, of course, immediately everyone is going to think of https://github.com/tgstation/tgstation/pull/76305 so I want to address that first. **That PR did not ultimately change that pAIs' effective access to languages, and neither does this PR affect pAI standing in that aspect.**

What this PR is about is the economy. One byproduct of the aforementioned is to skew pAI app economy. If a pAI is downloaded by a nonhuman crewmember, in order to converse with the pAI's master (and conspecific friends) in their native language, the universal translator is essentially an automatic download. Increasing the cost of the app wouldn't fix this; it's a hard lock on the often-preferred communication method, so if one wants it, the app is necessary at whatever cost. And a higher cost would limit access to already pretty limited utility options and make for a worse experience overall.

"Should I really get this app? What if another app would be more useful?" I think the game is more interesting when this question has a situational and uncertain answer. If maybe, in some situations and depending on round events, the translator might be invaluable... or maybe not, compared to other options, depending on the situations that arise; and hence I wish to make this change.

## Changelog

:cl:
balance: To make the universal translator app a more situational choice, pAIs receive crew languages by default.
/:cl:

### CODE REVIEW

**Comment by Striders13** [comment]
so what is the change

**Comment by YehnBeep** [comment]
> so what is the change

Languages for crew species are default instead of requiring the app.

**Review by JohnFulpWillard — CHANGES_REQUESTED** [review]
I think pAIs should instead copy the languages of their creator upon imprint, so they would always know common (do they know robotic?) and whatever languages their creator knows. 

Also your changelog doesn't seem descriptive enough for players.

**Comment by YehnBeep** [comment]
> I think pAIs should instead copy the languages of their creator upon imprint, so they would always know common (do they know robotic?) and whatever languages their creator knows.
> 
> Also your changelog doesn't seem descriptive enough for players.

Updated the changelog.

As for the creator languages idea - On the one hand, that would leave the translator app still somewhat more valuable than before. Nonetheless, I think that would make the translator app feel less like an "automatic yes" when deciding to download so it would accomplish the point of this PR, and I'm partial to it since it would work similar to another idea I liked for inheriting creator things.

But my abilities are pretty limited. Tweaking a language list I can do; developing new code/logic to seek out a player and copy their stuff is a bit beyond me.

**Comment by JohnFulpWillard** [comment]
There's existing code to do it already, you just need to call ``copy_languages`` on the pAI with the source being the person imprinting their DNA, in pAI's ``set_dna`` proc.

**Comment by ExcessiveUseOfCobblestone** [comment]
Translator should just be free but the languages themselves should be app-space so you can either cheap out and only know a few languages or learn all.

In either instance making it easier to know the languages is obviously a 180 from the PR you linked, im a bit lost on why pAI is suppose to be treated differently than the other silicons here and in fact make the addressed issue stronger for pais.

**Comment by YehnBeep** [comment]
> In either instance making it easier to know the languages is obviously a 180 from the PR you linked

...That's exactly what I was worried people would jump to seeing which is why I tried to explain that front and center, but, I don't see how it's a 180? Cyborg and AI stay not knowing anything.

pAIs, both before and after that PR and whether this PR is merged or not, have access to every language. What changed is the value of the app really - by making languages entirely reliant on it, and yes, *that* I do want to "180" on. Or at least go 90 or 45 degrees on. But one way or another since you've tagged this do not merge, it seems I should abandon trying something along the lines of John's suggestion?

**Comment by YehnBeep** [comment]
Ehm, well, is what it is I guess. I don't think leaning so hard on the app is ideal but it's not exactly destroying gameplay.

**Pull request closed without merging**
