### PR TITLE
Chemistry machinery sprite overhaul

### PR DESCRIPTION
**Pull request by mirrorcult**
:cl: cyclowns
imageadd: ports the chem dispenser, chem heater, chemmaster, soda dispenser and booze dispenser sprites from Eris
imageadd: chem heaters now have different sprites based on whether the container is being heated or cooled
/:cl:

Ports some good-looking 3/4 perspective chemistry machinery sprites from Eris (and booze/soda dispensers). Also cleans up some useless code (in chem_master.dm), makes chem heaters use an overlay for the beaker, and adds a feature to chem heaters where they change icon state when heating or cooling its container. Overall the sprites look cleaner and better and it seems that we're pushing towards 3/4 perspective so I figured this was a good next step.

image

### CODE REVIEW

**Comment by Armhulen** [comment]
AAAAAAAAAAAH

**Comment by cyclowns** [comment]
it appears that icondiffbot is drunk

**Comment by nicbn** [comment]
That heater looks awful.

**Comment by cyclowns** [comment]
thats the heater already present in the game

**Comment by ACCount12** [comment]
It looks different enough.

**Comment by nicbn** [comment]
No, the heater in the screenshot is different.

**Comment by cyclowns** [comment]
you're right, i didn't notice that i took the heater sprite too sicne they looked similar

**Comment by alexkar598** [comment]
Thru all look aweful

**Comment by cyclowns** [comment]
fucked up shit happenin

**Pull request closed without merging**
