### PR TITLE
Adds a new tool, ColonCatcher.py

### PR DESCRIPTION
**Pull request by RemieRichards**
<B>ColonCatcher.py</B>
ColonCatcher.py finds all colons that are used to avoid typesafety (Bad colons! very bad!) and ones used in ternary operations (1. because @MrPerson said to, 2. because the logic of avoiding all ternary colons is CRAZY complex)

<B>Output Format:</B>
filename (truncated down to just SS13 related stuff) line, line?, line (Line? represents a ternary operator colon) and then the total colons, 
eg: `..code\world.dm Lines: 27, 28, 98?, 102?, 119?, 149?, 230? Total Colons: 7`
These files are saved as "currentdate-colon_operator_log.txt" where currentdate is today's date (25/10/2015) in reverse (2015/10/25)

Also included is today's log, as an example, it's the latest master (as of just before pushing this PR) and reported: "433/1564 files have colons in them"

### CODE REVIEW

**Comment by PKPenguin321** [comment]
when i glanced at the title i only read the first and last part and for a brief moment i thought it was called colonoscopy
i don't have anything to add because i have no idea what this actually is but i just thought it was funny

**Comment by RemieRichards** [comment]
Rofl.

**Comment by Supermichael777** [comment]
coloniscope.py

**Comment by freerealestate** [comment]
when i saw the title i thought of removing people's colons

we could add that

**Comment by Jordie0608** [comment]
What do you have against regex Remite ;-;

**Comment by Razharas** [comment]
>Pyton

Whatevs tbh fam smh

**Pull request merged**
