### PR TITLE
Ports feral cats and feral cat grenades from Hippie

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request
Feral Cats are just a hostile variant of cats that will fuck you up if they see you. They are added solely for the sake of feral cat grenades - a new, interesting, and fuzzy way to get out of a jam or just wreak havoc around you. Each one costs 5 TC and spawns 5 really pissed off cats to chase down assistants in the hallway.

They don't currently ignore traitors or the person who threw them - I haven't worked out how to do that with our faction system (Hippie gave them the syndicate faction but traitors don't get that on our codebase). If anyone wants to contribute or help me suss that out it'll be cool, otherwise just don't be around if there's nobody else for them to maul.

## Why It's Good For The Game
They're funny.

## Changelog
:cl: Vekter
add: Added a new hostile variant of cats, "feral cats".
add: Added a new traitor item, "feral cat grenades". For 5 TC, you too can throw a grenade at someone and make five cats maul them to death.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Hang on I goofed something up but I'm fixing it

**Comment by tralezab** [comment]
hippie code 👍 x 😋

**Comment by TheVekter** [comment]
Okay I think we're gucci

**Review by Jacquerel — APPROVED** [review]

**Comment by TheVekter** [comment]
> it'd be funny if the cats latch onto your face to deal extra damage, like facehuggers

It would be, but all I'm doing is porting this, so I'm going to take the lazy way out and say that's out-of-scope

**Comment by ATH1909** [comment]
could make the grenade give you a "feralcat" faction when you prime it or something

**Comment by YakumoChen** [comment]
Genuinely surprised you chose cats instead of geese like skyrat did
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12121

**Pull request merged**
