### PR TITLE
Removes the haloperidol chem from omega weed (EDIT: and makes some other alterations)

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Currently, one of the many chems in omega weed is haloperidol, an anti-drug chem that will near-immediately purge most of the other chems that omega weed can give you from your system. This PR removes the haloperidol chem from omega weed so that the drugs in omega weed can run their course.

EDIT: I've decided to alter the chem list of omega weed further. It's now lost its haloperidol, capsaicin, barber's aid, itching powder, and histamine. In exchange, it's received nicotine as an additional chem. The chems that were previously in omega weed but were not mentioned in the above list are still in omega weed.

In addition, I've changed the list of chemical production traits of rainbow weed from 15% mindbreaker toxin and 35% lipolicide to 5% colorful reagent, 3% psicodine, 10% happiness, 10% mindbreaker toxin, and 15% lipolicide. This should make ingesting rainbow weed change your character's color, but should also make 100 potency rainbow weed highly addictive.

## Why It's Good For The Game

Haloperidol is kind of against the theme of omega weed, no?

## Changelog
:cl: ATHATH
balance: Omega weed has lost its haloperidol, capsaicin, barber's aid, itching powder, and histamine chemical production traits. In exchange, it's received the nicotine production trait as an additional chemical production trait. The chemical production traits that were in omega weed before this change but were not mentioned in the above list are still in omega weed.
balance: The list of chemical production traits of rainbow weed has been changed from 15% mindbreaker toxin and 35% lipolicide to 5% colorful reagent, 3% psicodine, 10% happiness, 10% mindbreaker toxin, and 15% lipolicide. This should make ingesting rainbow weed change your character's color, but should also make 100 potency rainbow weed highly addictive.
balance: The extradimensional orange has received the 15% haloperidol chemical production trait that omega weed used to have.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
If you'd like, I could move haloperidol to a different plant so that botanists will still have easy access to it/can replica old!omega weed. Any suggestions?

**Comment by ATH1909** [comment]
I'm also not quite sure why omega weed has barber's aid (not even the concentrated variety that can grow your hair out) in it, seeing as how that chem has no effect when ingested. You could use it with hypodermic prickles, I guess?

**Comment by Trumpetplaya288** [comment]
You could really throw it in anything, extradimensional orange is just an orange clone with nothing to differentiate it other than the gif sprite.

**Comment by shellspeed1** [comment]
> 
> 
> I'm also not quite sure why omega weed has barber's aid (not even the concentrated variety that can grow your hair out) in it, seeing as how that chem has no effect when ingested. You could use it with hypodermic prickles, I guess?

For a meme maybe? Or maybe the creator didn't know how it worked? Not sure.

**Comment by Ty-the-Smonk** [comment]
Add it to the Extradimentional orange

**Comment by ATH1909** [comment]
> You could really throw it in anything, extradimensional orange is just an orange clone with nothing to differentiate it other than the gif sprite.

Sure, I'll move it over there.

Also, after thinking for a bit, I've decided to tweak the contents of omega weed a bit more, to reflect the additions of some new drugs (and to remove some weird chems that don't really have much of a reason to be in omega weed).

**Comment by ExcessiveUseOfCobblestone** [comment]
wtf is this plant

**Comment by ATH1909** [comment]
There, my additional alterations have been made. Its a bit of a shame that ephedrine's addiction and overdose thresholds are so close together (and are so high); I would have preferred it if I could have made wolfing down a 100 potency leaf of omega weed addict you to ephedrine without giving it something like a 25% or so ephedrine chemical production trait.

**Comment by ATH1909** [comment]
I also gave haloperidol to the extradimensional orange, as was requested in the comments of this PR.

**Comment by nemvar** [comment]
cringiperidol

**Comment by optimumtact** [comment]
I have been awoken

**Review by optimumtact — DISMISSED** [review]

**Comment by Ratvar** [comment]
This won't make 100 potency omega weed highly addictive because someone added magical feature called DNA manipulator. Just a buff that gives botany more anti-stamina damage and maxspeed chems, disguised under tasty flavor of all-drug plant.

**Comment by Shadowflame909** [comment]
They could have always done that though. This doesn't change that?? It just makes it actually dangerous

**Comment by nemvar** [comment]
So Mr. Ratvar, what has prevented botany from just removing haloperidol themselves? This almost exclusively a flavour change.

**Comment by ATH1909** [comment]
In a future PR, I'll likely boost the chem capacity of deathweed a bit and add the itching powder and histamine chemical production traits that I removed from omega weed in this PR to it.

Perhaps in a different future PR, I'll add a type of plant that'd be sort of like a medipen that I could add a barber's aid chemical production trait to.

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> They could have always done that though. This doesn't change that?? It just makes it actually dangerous

i don't think botany can make either epi from just genes barring strange

**Comment by Shadowflame909** [comment]
what are you trying to say

This pr removes the instant chem purger so all of the nasty downsides of this giant drug of a weed can kick in and make a total mess out of you

thus I am in support of this PR because it makes it total madness like it should be. Instead of being totally lame.


Might I suggest you add in some rotatium ATH1909 to make people be more insane to ingest this thing

**Comment by ExcessiveUseOfCobblestone** [comment]
If you take off the bad stuff, what do you have left both pre and post PR.

do you see the issue now?

**Comment by Shadowflame909** [comment]
No...?

That's a completely separate issue that this PR isn't addressing at all.

This becomes dangerous, and if you wanted to not get over-dosed on a bunch of dangerous chemistry lab experiments. You'd use the gene editor to remove it.

You still do that here.

I don't see the issue or problem you're trying to bring up cobby. It's like having a problem with someone making an uplink only give you loud murderbony items if you get hijack/martyr but ye got a problem with the dual e-sword being in the uplink anyways.

I don't see the issue.

**Comment by ExcessiveUseOfCobblestone** [comment]
dude changing the chems is the entire point of this PR, frick off.

I could care less about the halo removal because if it was such an issue botanists could already remove it.

I DO care about pump-up being added to the botanist arsenal as well as eph, both being "combat" chems. It doesn't matter if it's tied with bad stuff because that bad stuff can be removed.

Hell, even nicotine is a soft antistun.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
PR title - Remove Haloperidol (and stuff)

"I have removed the purging chem so the bad chems can run their course" - okay whatever

"I have also replaced all the really bad chems with combat chems and lipolicide" - lol

"additionally, I've added 1 bad chem to rainbow weed but dropped the dosage on all the other bad chems and added 2 new good ones" - lol

**Comment by Shadowflame909** [comment]
Well thats a different point entirely that I didn't know about because I no read well

Maintainers enjoy the Nerf athgamer

What were you doin trying to rebalance omegaweed with more buffs then nerfs.

I still recommend a small amount of rotatium or copper.

**Comment by WaterStBlues** [comment]
This is the SS13 equivalent of a normie taking a dab. Full support

**Comment by ATH1909** [comment]
@ExcessiveUseOfCobblestone Ephedrine is already present inside of coffee robusta, hence why I felt like it'd be fine to add it to omega weed as well. Ephedrine gives you the same stun resistance trait that pump-up does and pump-up has a "drug" theme to it, so I threw pump-up in as well.

**Comment by ATH1909** [comment]
```
// Coffee Robusta
/obj/item/seeds/coffee/robusta
	name = "pack of coffee robusta seeds"
	desc = "These seeds grow into coffee robusta bushes."
	icon_state = "seed-coffeer"
	species = "coffeer"
	plantname = "Coffee Robusta Bush"
	product = /obj/item/reagent_containers/food/snacks/grown/coffee/robusta
	mutatelist = list()
	reagents_add = list(/datum/reagent/medicine/ephedrine = 0.1, /datum/reagent/consumable/nutriment/vitamin = 0.04, /datum/reagent/toxin/coffeepowder = 0.1)
	rarity = 20

```

**Comment by ATH1909** [comment]
Itching powder and histamine feel like they really should be in deathweed, not omega weed (as far as I know, cannabis isn't supposed to make you feel "itchy" (correct me if I'm wrong, though)). They also have relatively minor effects, so I don't know why you're mad about their removal. Tbh, the negative side effects of pump-up probably compensate for their removal. Capsaicin and barber's aid do pretty much jack shit in omega weed currently (I think capsaicin might actually FEED you? I don't quite remember, but I remember that it basically just increases your temperature and DOESN'T cause condensed capsaicin-like effects). You already agree with me about the removal of haloperidol from omega weed. Lipolicide was in omega weed before (in the exact same dosage, no less), so I don't know why you said that I replaced the chems I removed with lipolicide.

**Comment by ATH1909** [comment]
As for the rainbow weed changes, I reduced the dosage of some of the "bad" chems to make room in the plant for the new ones (plants only have a reagent capacity of 50u by default), which, in their current doses in a 100 potency plant, will addict you to happiness if you eat the rainbow weed too quickly. The happiness addiction will eventually drive you insane if you don't take more happiness, encouraging you to eat more rainbow weed (which has psicodine and happiness in it) to try to boost your sanity up again. The happiness chem itself deals brain damage, by the way. The colorful reagent chem is there so that your character will be randomly recolored when they consume rainbow weed.

**Comment by ATH1909** [comment]
> > @ExcessiveUseOfCobblestone Ephedrine is already present inside of coffee robusta, hence why I felt like it'd be fine to add it to omega weed as well. Ephedrine gives you the same stun resistance trait that pump-up does and pump-up has a "drug" theme to it, so I threw pump-up in as well.
> 
> Yes, and that's a separate plant you have to mutate coffee into then extract to be able to obtain versus 1 plant that gives you several different anti-stuns.

It's a bit of a diminishing returns situation, though, no? Don't we have a speed cap?

But fine, I'll remove the ephedrine and pump-up if it'll make you happy.

**Comment by ATH1909** [comment]
@ExcessiveUseOfCobblestone done

**Pull request merged**
