### PR TITLE
Adds Advanced Security Cameras to Box. This is feedback testing.

### PR DESCRIPTION
**Pull request by KazeEspada**
Everyone agrees that security camera computers SUCK BALLS.

Well, apparently we have had these bad boy for a while now, and they NEVER got tested by security players because they thought they would be to OP.

Well, we never know till we try.

### CODE REVIEW

**Comment by francinum** [comment]
Finally.

**Comment by CPTANT** [comment]
This is something like the AI eye?

**Comment by borntohonk** [comment]
AI EYE like camera controls?

I don't know if that's a good idea.

**Comment by xxalpha** [comment]
One player having omnipresence is enough, I think.

**Comment by CPTANT** [comment]
Actually I do know if that's a good idea.

Its's not

**Comment by KazeEspada** [comment]
Its not omnipresence. They can only hop as well as a regular camera computer, and they don't autotrack.

Its just a better version of moving around then the shitty crap security has right now.

**Comment by ChangelingRain** [comment]
Ah yes, a way to check on the AI core at will.

**Comment by PKPenguin321** [comment]
There is a reason these are admin/abductors only. :-1:

**Comment by KazeEspada** [comment]
You can already do that with a normal camera computer?

**Comment by ChangelingRain** [comment]
No, you can't. The core cameras on box are set to RD, not to SS13, and the core cameras on other stations(dream) don't even have that.

**Comment by Shadowlight213** [comment]
:-1: one omnipresent eye is bad enough.
Having 5 is just insane.
Would be ok if we used this to replace AI though. :^)

**Comment by KazeEspada** [comment]
@ChangelingRain That's just dumb mappers.

**Comment by PKPenguin321** [comment]
No, it's smart use of the camera system if anything

**Comment by AnturK** [comment]
I'm not going to go into balance discussion but please wait until #14626 is fixed. Should be soon.

**Comment by optimumtact** [comment]
Artificial interface difficulty is not difficulty at all.

If cameras are too powerful like this then we should nerf cameras, not the interface to them.

**Comment by xxalpha** [comment]
The list sucks I agree, but you can replace that with a minimap.

**Comment by Zilenan91** [comment]
:-1:  :x:  :100:  we don't need any more than one omnipresent valid salid satelite

**Comment by KorPhaeron** [comment]
Dont need ~4 extra camera eyes scanning for badguys at all times

**Comment by optimumtact** [comment]
If cameras are too powerful like this then we should nerf cameras, not the interface to them.

**Comment by Zilenan91** [comment]
That would be much preferrable. Cameras should go inert when the power in an area goes inert. That'd be the perfect nerf for enabling this.

AI players will kick and scream about this however.

**Comment by duncathan** [comment]
I'd agree with doing that to regular ol security cams, @Zilenan91. It wouldn't be fun for AI though.

**Comment by Zilenan91** [comment]
The AI has armies of borgs that can re-enable the power for it, it'd literally be a non-issue.

**Comment by KazeEspada** [comment]
If you are playing AI without at least 1 engi or 1 sec borg, then you aren't playing right.

**Comment by Shadowlight213** [comment]
@KazeEspada or no one chose borg and robotics isn't making any, which happens a lot for me.
It's not the fault of the AI player. Don't say you aren't playing AI right.

**Comment by AlexCrimson** [comment]
Holy fucking shit. That console was added specifically for Abductors because the normal camera system was terrible for tracking the Agent. Why would anyone even consider replacing the normal camera system with it? Its overpowered as hell. 

Do you guys have no concept of balance at all? Its hard to believe this isnt a joke PR.

**Comment by ChangelingRain** [comment]
Camera eyes don't give a shit about networks, you can't just go "well that's dumb mappers" about something mappers never knew was coming.

**Comment by octareenroon91** [comment]
Maybe just buff the bridge one or the warden's.

**Comment by KazeEspada** [comment]
I was thinking of JUST the warden's. And maybe the one in arrivals for #shenanigans. And if the HoS has one, he should get one too.

**Comment by octareenroon91** [comment]
By my count, there are six security camera consoles on Box, including the Detective's wooden TV.
* HoS Office
* Warden's Office
* Main Security room
* Detective's Office
* Security Checkpoint
* Bridge
* ```cwN``` below refers to a camera console on the escape shuttle.
```
$ grep -E "machinery/computer/security(/wooden_tv)?," tgstation.2.1.3.dmm
"abV" = (/obj/machinery/computer/security,/turf/simulated/floor/carpet,/area/security/hos)
"ago" = (/obj/machinery/computer/security,/turf/simulated/floor/plasteel{icon_state = "showroomfloor"},/area/security/warden)
"ait" = (/obj/item/device/radio/intercom{name = "Station Intercom (General)"; pixel_y = -29},/obj/machinery/computer/security,/obj/machinery/atmospherics/pipe/simple/supply/hidden{dir = 4},/turf/simulated/floor/plasteel{icon_state = "red"},/area/security/main)
"arT" = (/obj/machinery/computer/security/wooden_tv,/obj/machinery/newscaster{pixel_x = 28},/turf/simulated/floor/plasteel{icon_state = "grimy"},/area/security/detectives_office)
"aCY" = (/obj/machinery/computer/security,/obj/structure/reagent_dispensers/peppertank{pixel_x = 0; pixel_y = 30},/turf/simulated/floor/plasteel{icon_state = "red"; dir = 1},/area/security/checkpoint2)
"aTT" = (/obj/machinery/computer/security,/turf/simulated/floor/plasteel{icon_state = "red"},/area/bridge)
"cwN" = (/obj/machinery/computer/security,/turf/simulated/floor/plasteel/shuttle{icon_state = "shuttlefloor3"},/area/shuttle/escape)
```

**Comment by Dorsisdwarf** [comment]
:-1: 

stop

adding

admin 

kit

**Comment by duncathan** [comment]
Admins do not have exclusive rights to a good interface

**Comment by AlexCrimson** [comment]
They do when even the creator of the damn thing agreed that its something only the Abductors should get. Its overpowered. An all-seeing eye that can no-clip around the station, who in their right mind would consider that a good thing to add to the station just "because its a better interface"?

**Comment by xxalpha** [comment]
Agreed, it's power creep.

The interface can be bettered with minimaps, which neersighted plans on doing.

**Comment by Shapsy** [comment]
Wardens should have to rely on communicating with their security officers to get up to date information about what's going on outside, and cameras are just a supplement to that. If you know the main areas that you want to check (toxins, head of personnel's office, engineering foyer) then you can already use the current cameras effectively, just because it's possible to give them complete omnipotence doesn't mean you have to. Like, it'd be easier to give science a button that gives you maxcap bombs rather than have them make it, but that doesn't mean it's a good idea because you have to put in a certain amount of effort to get the reward of information

also
>If you are playing AI without at least 1 engi or 1 sec borg, then you aren't playing right.
"if you don't play how I play you're playing wrong and deserve to get nerfed"

**Comment by Zilenan91** [comment]
Realistically, Sybil pop has the AI having a borg almost 99% of the time. I genuinely can't even remember the last time there wasn't a borg at round start.

**Comment by tkdrg** [comment]
This feels like it could use a testmerge. @KorPhaeron

**Comment by KorPhaeron** [comment]
Fine

**Comment by AlexCrimson** [comment]
Why does every shitty PR need a test merge? You guys never revert shit unless every person on the server bitches about it enough.

**Comment by optimumtact** [comment]
Mate chill your bones, a test merge is a test without merging to the mainline, so that we don’t' need to merge it to master to test it.

Please understand what is happening before getting all heated.

**Comment by KazeEspada** [comment]
This was generally well received and actually ended up distracting officers, since they are super vulnerable while using this.

**Comment by KorPhaeron** [comment]
Note: Above feedback was after a single traitor round, nowhere near enough testing has been done yet

**Comment by Shadowlight213** [comment]
>sec officers receiving a sec buff well.

Who would have thought.

**Comment by Bawhoppen** [comment]
:-1:x:100:  you already have xenobio camera consoles for your shitty powergaming

**Comment by KazeEspada** [comment]
I only play warden, and only if the job RNG fucks me.

**Comment by PKPenguin321** [comment]
still tho dont add this
:-1: i cant believe this is getting considered in the first place
if it goes through i will personally make the revert PR

**Comment by Bawhoppen** [comment]
@PKPenguin321 we agree on something for once

**Comment by PKPenguin321** [comment]
that's how you know this is a bad PR

**Comment by KorPhaeron** [comment]
As my first official act following my design lead appointment by @Cheridan I am rejecting this PR.

Better luck with future contributions.

**Pull request closed without merging**
