### PR TITLE
Haha fart

### PR DESCRIPTION
**Pull request by GaryGreytide**
fart

### CODE REVIEW

**Comment by ATH1909** [comment]
image

uh oh

**Comment by LemonInTheDark** [comment]
ya gotta pr just the music tracks, we don't want the whole fulp repo

**Comment by SgtHunk** [comment]
Absolutely based

**Comment by GaryGreytide** [comment]
man when the fuck are we moving to scratch, this git shit is mad hard and my ass is too burnt out for it all

**Comment by XRandomXManX** [comment]
Detroit: Become Fulp

**Comment by edgeotron** [comment]
best pr tg has ever seen

**Comment by cacogen** [comment]
git is the easiest part of contributing

**Comment by Jared-Fogle** [comment]
hmmm seems to be some conflicts

**Comment by Jared-Fogle** [comment]
image

**Comment by san7890** [comment]
bruh

**Comment by ShibaInuLord** [comment]
chad tries to merge all of fulp

**Comment by cacogen** [comment]
pr of the year material right here

**Pull request closed without merging**
