### PR TITLE
ADDS SUPERIOR AIR ALARM SPRITES FROM ERIS

### PR DESCRIPTION
**Pull request by ghost**
@IconDiffBot do your magicjks

:cl: More Robust Than You
imageadd: Better air alarm sprites
imagedel: Deleted some unused sprites
/:cl:

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
for fks sake confdiff butt. anyways here's some real good picsss

**Comment by evsey9** [comment]
stop stealing from russianstation

**Comment by evsey9** [comment]
also
>liking your own pr

**Comment by MoreRobustThanYou** [comment]
@evsey9 guess where our machine/computer/APC sprites came from? Eris.

**Comment by ACCount12** [comment]
And that's why our APCs are out-of-the-place eyesores. New computers fit the style of new TG machinery at the very least.

**Comment by DaxDupont** [comment]
Can you perhaps take a screenshot that does not cut off 50% of the wall since I'd argue it's pretty important.

**Comment by DoctoreMad** [comment]
We're all subservient to the graphics deisgner who has dominion over our eyes anyways what does protesting mean
_Sephurution of chushebhashe and adhimhishrashrion._

**Comment by Supermichael777** [comment]
Icon dif bot butchers it again. Man it does not like removals

**Comment by nicbn** [comment]
This sprite already was pred like one thousand times
No

**Comment by Supermichael777** [comment]
This is ugly as sin and has that weird pseudo anti-aliasing our down streams seem in love with

**Comment by Armhulen** [comment]
You'd have a better chance adding pee pee poo poo

**Comment by davethwave** [comment]
honestly to my eyes it looks more like a apc than a air alarm.

**Comment by ChangelingRain** [comment]
This was previously rejected and nothing has changed.

**Pull request closed without merging**
