### PR TITLE
hop moves from supply positions to service positions

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

this is one thing i forgot in my civillian service merge pr, qm already somewhat rules over supply while service doesn't have any authority figure, so i figured that moving hop to service would be neat

## Why It's Good For The Game

i dont think this actually does anything ingame but i'd classify hop more as service than supply

## Changelog
is it even needed

### CODE REVIEW

**Comment by EgorDinamit** [comment]
Add changelog stating Cargonia's independence.

**Comment by tralezab** [comment]
Hop rules both

**Comment by Fikou** [comment]
> Hop rules both

why isnt he in both then

**Comment by Cyberboss** [comment]
Inb4 comments on QM (not) being a dept head.

**Comment by tralezab** [comment]
@Fikou You're changing the lists, not me! If it doesn't break anything, why don't you do exactly that? If it does, then this change is not really needed

**Comment by Qustinnus** [comment]
HoP is the QM's boss either make QM a head (lol doubt) or keep it as is

**Comment by Fikou** [comment]
> HoP is the QM's boss either make QM a head (lol doubt) or keep it as is

hop is also the boss of everyone in service

**Comment by ExcessiveUseOfCobblestone** [comment]
What do these lists touch exactly? He should be in both unless there would be a problem with "duplicate" values.

**Comment by Fikou** [comment]
> What do these lists touch exactly? He should be in both unless there would be a problem with "duplicate" values.

in practice the only thing that changes is that the department members of a person change which affects who creep will get as objective

**Pull request merged**
