### PR TITLE
Creating a supermatter shard in the crystallizer is now actually possible

### PR DESCRIPTION
**Pull request by SyncIt21**
**About the pull request**
Fixes issue [#70307](https://github.com/tgstation/tgstation/issues/70307)

There was another PR  #70805 which tried to impose HFR heat levels for shard creation  but there were 2 problems with this
- You already have to use the HFR to create gases like Hyper-Nob & Anti-Nob which requires fusion level 6 which is already dangerous & difficult enough. Making it again require the HFR to heat the mixture by fixing temperature pumps or whatever just makes this process needlessly difficult.  A player would just order a shard at the start of the round and wait another 20 minutes to order another one which is much safer
- That PR also wanted to create anomalies around the crystallizer if the quality of the crystal isn't good this again creates 2 more problems
  - Makes the process even more dangerous
  - A player with an anomaly neutralizer can neutralize these cores and refine them by building a refinery near the crystallizer!!. No need to order one from cargo or go on any dangerous adventure nope just try creating a shard in atmospherics and get your free anomaly core 

**The Solution?**
Like i said in that issue just reduce the heat levels produced. To avoid getting into a debate of how much is too much/too less i just made the requirements equal to that required to create a plasma sheet i.e
- Min Temp = 10k
- Max temp = 20k
- Reaction is exothermic
Creating a high-quality plasma sheet requires atleast 3 T4 freezers and a canister of 10,000 moles of plasma & even then u dont' get the highest quality always but atleast makes the process possible. There aren't any consequences for creating a low quality supermatter shard as this process is already difficult enough with acquiring the gases & T4 stock parts 

Here is a montage of me creating the shard. As you can see it still struggles to reach the target but makes steady progress none the less

https://user-images.githubusercontent.com/110812394/204268965-e575caf4-77b7-48ad-bfcd-dd0e9b20070a.mp4

**Why its good for the game**
1. Gives atmospheric technician's something to do with both HFR & crystallizer
2. Don't have to bug cargo for one which is good especially if no one is working there or if someone steals the shard there
3. Makes the process possible & fun

**ChangeLog**
:cl:
qol: creating a shard is possible
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
@LemonInTheDark thoughts???

**Comment by Iajret** [comment]
Hyper-nob and anti-nob both can be created without even touching the HFR. I think, current process even simplier than metallhydrogen formation. A bit long though, but requires just t4 thermomachines. i'm with all my limbs up for this PR, but maybe it should require something more extreme than just T4 parts and low quantities of hyper-nob.

**Comment by SyncIt21** [comment]
> Hyper-nob and anti-nob both can be created without even touching the HFR. I think, current process even simplier than metallhydrogen formation. A bit long though, but requires just t4 thermomachines. i'm with all my limbs up for this PR, but maybe it should require something more extreme than just T4 parts and low quantities of hyper-nob.

Have any ideas? I mean we could make it more complicated but then again if we make it too complex for a round then it will just discourage players and they will just resort to ordering from cargo again. 

Or perhaps we could add more gases required for the recipe?

**Comment by Iajret** [comment]
Well... havent thought about outright purchasing it. I think its better to have some high temperature required for the proccess, as in PR mentioned above. Something in range of fusion level 5. Still easy to get since you only need to pump plasma and oxy. But at least would force the usage of HFR. You still need t3 parts for hyper-nob though. And maybe, purchasing **should** be easier because of the inter-department interaction and such. It's quite hard to make crystallizer viable since shard costs only about 5k creds and could be bought from engie budget literally at roundstart

**Comment by SyncIt21** [comment]
> Well... havent thought about outright purchasing it. I think its better to have some high temperature required for the proccess, as in PR mentioned above. Something in range of fusion level 5. Still easy to get since you only need to pump plasma and oxy. But at least would force the usage of HFR. You still need t3 parts for hyper-nob though. And maybe, purchasing **should** be easier because of the inter-department interaction and such. It's quite hard to make crystallizer viable since shard costs only about 5k creds and could be bought from engie budget literally at roundstart

You are right about not requiring HFR for antinob & hyper-nob . As you have mentioned the cost of a shard is 5k so players would rather create lots of Hyper-nob & electrolyze it to antinob and sell that in cargo to make a ton of money &  buy a ton of shards which is far more safer rather than use the HFR to attain the right temperatures.

Not to mention the [wiki](https://tgstation13.org/wiki/Atmospheric_Technician) page states this
Screenshot (53)

Making helium just requires fusion level 1 for most reactions so ppl would just keep the HFR running at level 1 for like 5 minutes to create enough helium to buy at least 5 shards!! so ppl would most definitely use the HFR for that instead. 

I guess the only option is to admit that creating a supershard isn't such a dangerous idea and we shouldn't worry about players using it to take over the station or some shit. You literarily have to drag the shard across the station where everyone can see it and so everyone will know well enough to stay away from it. Moreover the player dragging the shard is in more danger as someone could just push him into it before he could do any damage with it. 

The main purpose of this PR is to make ppl more interested in the crystallizer and the benefit's of that far out way the risks. Do u agree?

**Comment by SyncIt21** [comment]
@LemonInTheDark , @Ghilker . Anyone there to review just 3 lines of code?

**Comment by LemonInTheDark** [comment]
> > Hyper-nob and anti-nob both can be created without even touching the HFR. I think, current process even simplier than metallhydrogen formation. A bit long though, but requires just t4 thermomachines. i'm with all my limbs up for this PR, but maybe it should require something more extreme than just T4 parts and low quantities of hyper-nob.
> 
> Have any ideas? I mean we could make it more complicated but then again if we make it too complex for a round it will discourage players and they will just resort to ordering from cargo again.

I can tell you the intention of the shard was to be the "top" of the crystalizer, at least if I recall right. Wanted it to be the cool thing you work up to making.
IDK how I feel about making it easier then just ordering from cargo, since it's meant to be sort of an accomplishment, tho I might be wrong about that.

**Comment by SyncIt21** [comment]
> > > Hyper-nob and anti-nob both can be created without even touching the HFR. I think, current process even simplier than metallhydrogen formation. A bit long though, but requires just t4 thermomachines. i'm with all my limbs up for this PR, but maybe it should require something more extreme than just T4 parts and low quantities of hyper-nob.
> > 
> > 
> > Have any ideas? I mean we could make it more complicated but then again if we make it too complex for a round it will discourage players and they will just resort to ordering from cargo again.
> 
> I can tell you the intention of the shard was to be the "top" of the crystalizer, at least if I recall right. Wanted it to be the cool thing you work up to making. IDK how I feel about making it easier then just ordering from cargo, since it's meant to be sort of an accomplishment, tho I might be wrong about that.

Adding more gases required for the shard seems like the best bet.playing around with temperature  won't be a good idea from the last PR, in my opinion at least.

It's your call.

**Comment by SyncIt21** [comment]
Also i wouldn't say its easier than ordering than cargo. Ordering from cargo is way too easy & the only thing stopping them from doing it is the 20 minute cooldown.
There are 2 ways to make an experience rewarding
- Have a long list of easy steps
- Have a short list of difficult steps
I prefer the 1st option, but  it's your creation so you decide

**Comment by LemonInTheDark** [comment]
It ain't mine I'm just the maintainer who deals with atmos. will sleep on it, talk tomorrow

**Comment by LemonInTheDark** [comment]
> Also i wouldn't say its easier than ordering from cargo. Ordering from cargo is way too easy & the only thing stopping them from doing it is the 20 minutes cooldown. In that 20 minutes one could create a shard hence their both the same There are 2 ways to make an experience rewarding
> 
>     * Have a long list of easy steps
> 
>     * Have a short list of difficult steps
>       I prefer the 1st option, but  it's your creation so you decide

My gut says the second, but I don't want it to become an hour long slog. Honestly if you want to make it easy for now that's ok, if it starts to get spammed we can just make it harder again

**Comment by Iajret** [comment]
Well... So far it's kinda long process already. Make trit, make bz, make nob. It just doesnt feel right to cool everything with t4 freezers at the end and be done. But it's fine i guess. Not a big fan of using freezers everywhere. Maybe it's just me, but i find its pretty fun to use heat from HFR to make hydrogen ingots, for example. Even though they are somewhat useless. But making gasses for supermatter if not hard, at least takes a bit of time to do.

**Comment by SyncIt21** [comment]
Then we all agree with these changes for now atleast. Ready for any maintainer to merge this

**Comment by SyncIt21** [comment]
Any maintainer interested in suggesting changes or merging this? I have no pending changes to make

**Comment by SyncIt21** [comment]
Don't want to spam but this is my last open PR. After this i will have a clean slate.
@Time-Green can i trouble you one last time :D?

**Comment by Time-Green** [comment]
> Don't want to spam but this is my last open PR. After this i will have a clean slate. @Time-Green can i trouble you one last time :D?

I've pinged Lemon on discord, since I feel kinda bad stealing another mans merge. I'll merge it tonight or tomorrow otherwise, since they already said they were okay with it

**Comment by SyncIt21** [comment]
> > Don't want to spam but this is my last open PR. After this i will have a clean slate. @Time-Green can i trouble you one last time :D?
> 
> I've pinged Lemon on discord, since I feel kinda bad stealing another mans merge. I'll merge it tonight or tomorrow otherwise, since they already said they were okay with it

Thank you 😄

**Comment by Time-Green** [comment]
> > Don't want to spam but this is my last open PR. After this i will have a clean slate. @Time-Green can i trouble you one last time :D?
> 
> I've pinged Lemon on discord, since I feel kinda bad stealing another mans merge. I'll merge it tonight or tomorrow otherwise, since they already said they were okay with it

**Pull request merged**
