### PR TITLE
Fix make nuke call in the nukeops antag spawner

### LINKED ISSUE #20187: Nuke Ops reinforcements are naked, not syndicate, not implanted
All points from a war declaration went into reinforcements. Poor admins had to fix every single one of the new guys. They all spawned naked, without gear, without being syndicate and without implants.

### PR DESCRIPTION
**Pull request by optimumtact**
Fixes #20187

### CODE REVIEW

**Comment by KorPhaeron** [comment]
This was actually already fixed, but I guess this is prettier

**Comment by optimumtact** [comment]
Who fixed it?

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/tgstation/pull/20190

Turns out you're the one who merged it

**Comment by optimumtact** [comment]
Oh no I'm referring to the runtime.

That's not valid byond syntax

**Pull request merged**
