### PR TITLE
Reduces progression cost of a lot of traitor items. Groups assassinate/behead/eyesnatching objectives together so that they're treated the same under the traitor no-dupe rules.

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

Assassinate/behead/eyesnatching objectives now share one common type so that they don't end up sharing the same targets. Also, this allows me to limit the amount of assassinate/behead/eyesnatch objectives by treating them like one objective type instead of 3 separate objective types.
As a result, you can only get 4 of these objectives within a 15 minute period, which means your potential objective list won't be flooded with assassinate/kidnap objectives.

Additionally, progression costs for traitor items have been rebalanced. Primarily, progression costs have either been removed or reduced for most non-murderboney traitor items. There are a few notable exceptions where the progression costs have been removed/reduced for murderboney traitor items, primarily for the Clown Car and His Grace. I'll go into the reasoning why below.

Also fixed an obscure bug where traitor categories with a list depth greater than 2 would have their list mutated because they weren't being properly deep copied.
Also, purchasing His Grace or Syndicate Balloon will now lock you out of future purchases and they can't be bought if you've already bought other items.
## Why It's Good For The Game

Less duplicate objectives is for the better. Also, this'll give some of the other objectives some breathing room to appear.

Progression costs have been normalised amongst the more murderbone-orientated items so that they all mostly unlock at 30 minutes for consistency purposes.

Progression costs have been largely reduced for non-murderboney items because most of these items didn't need a progression cost in the first place, as they weren't really a problematic tool to use at the start of a round.
For the items where their progression cost was reduced to 5 minutes, I'll go into the reasoning why now:
**Clown car** - It's not really a tool that's used for murderbone and it works best at the start of a round. It can end up killing a large portion of the crew, but it takes a lot of effort to reach that point. I think reducing the progression cost of the clown car to 5 minutes allows for the clown car gimmick to happen more often.
**His Grace** - Now this is a tool that is used primarily to go on a murderbone, but the reason that the progression cost has been decreased down to 5 minutes is because I think it's the one tool where you are supposed to get it at the start of a round and go on a murderbone, given its absurd price tag and the fact that you're required to kill others to survive. If this ends up being a boring roundstart murderbone tool, then I can look at increasing the progression cost back up to 30 minutes, but it's worth giving it a shot.
To balance out His Grace, you can't purchase any uplink items after purchasing it, and it can't be purchased if you have already purchased items.

## Changelog

:cl:
balance: Reduced the reputation cost of most non-murderbone orientated uplink items like hypnotic flash and emag.
balance: Reduced the amount of assassinate/kidnap/eyesnatch objectives that'll appear at once.
/:cl:

### CODE REVIEW

**Comment by flowercuco** [comment]
if you have the uplink implant can you still buy the syndicate balloon and his grace after you get 4 TC from objectives or does it only lock you from these items if you buy something from the uplink?

**Comment by Watermelon914** [comment]
> if you have the uplink implant can you still buy the syndicate balloon and his grace after you get 4 TC from objectives or does it only lock you from these items if you buy something from the uplink?

no you can't

**Comment by flowercuco** [comment]
my only other concern then, with the emag, is that i thought it had the 20min prog limit because of cyborg subversion, it is true that outside of that though it isn't very inherently dangerous but its what i thought the reasoning behind the limit was for that item.

**Comment by Watermelon914** [comment]
> my only other concern then, with the emag, is that i thought it had the 20min prog limit because of cyborg subversion, it is true that outside of that though it isn't very inherently dangerous but its what i thought the reasoning behind the limit was for that item.

The reason any of these items had a reputation lock in the first place was because they could immediately be used for mass murderbone. Stuff like emag don't actually have the potential to let you immediately start killing your crewmembers. Emagging a borg takes time and effort and even they can't go on a massive murder streak.
Therefore, it doesn't really need to be rep-locked. More powerful items can be rep-locked, but I want to remove the progression lock from items that didn't have it pre-progression traitor if they don't need it.

**Comment by Vect0r2** [comment]
Can I ask I question? I am to lazy to codedive right now, but does His Grace alert you that you cannot buy another item to use it? I feel like somebody is going to fuck up and buy something, so maybe when you are a chaplain, before you buy your first item, there is a little pop-up that says "Oi, you ain't gonna be able to buy His Grace if you buy this! Still wanna buy? Y/N"

**Comment by Watermelon914** [comment]
> Can I ask I question? I am to lazy to codedive right now, but does His Grace alert you that you cannot buy another item to use it? I feel like somebody is going to fuck up and buy something, so maybe when you are a chaplain, before you buy your first item, there is a little pop-up that says "Oi, you ain't gonna be able to buy His Grace if you buy this! Still wanna buy? Y/N"

yes, it does

**Comment by dessysalta** [comment]
Just me, but I think buying the Syndicate balloon shouldn't lock you out of other purchases. While that was the intent of the original balloon, I find it more worthwhile to just make fun of people who buy the balloon alongside other gear. It defeats the point, but I don't think limiting people for taunting security or the rest of the crew is fun. Less limits on stuff makes the game feel more creative.

If you end up keeping it that way, can you make it so you can buy the balloon multiple times, and lock out everything else? If for some reason you can buy two of them, you ought to be able to.

**Pull request merged**
