### PR TITLE
Adds headpatting

### PR DESCRIPTION
**Pull request by Wilchenx**
Its another attempt to pr headpatting

### CODE REVIEW

**Comment by duncathan** [comment]
don't abuse the announcer
as for this pr I seriously doubt it'll go through but in the spirit of Christmas I'm letting it live a little longer

**Comment by praisenarsie** [comment]
[why](https://github.com/tgstation/tgstation/pull/28210) [do](https://github.com/tgstation/tgstation/pull/28208) [you](https://github.com/tgstation/tgstation/pull/30052) [bother](https://github.com/tgstation/tgstation/pull/30089)

**Comment by lzimann** [comment]
no thanks

**Comment by FantasticFwoosh** [comment]
Can we do something about these repeat fetish PR's please?

**Comment by The-clown-known-as-Pepe** [comment]
@FantasticFwoosh how is it a fetisho

**Comment by Pascal125** [comment]
You're all retarded Christmas Grinches lmao.

There's literally nothing more stupid then calling handholding fetish content.

**Comment by FantasticFwoosh** [comment]
Unsolicited contact, if people do not want to be touched do not touch them.

@The-clown-known-as-Pepe We're not Vulcans in heat, but keep your freaky ass dirty salad fingers away from us, mostly for escalation purposes of gentle contact leading to ERP.

**Comment by Cyberboss** [comment]
It's a normal social interaction, but our player base is obviously too shut in to comprehend that.

**Comment by FantasticFwoosh** [comment]
Only if you grew up in a cult @Cyberboss , who even headpats in this modern day and age if you're not a golden retriever or a 8 year old child.

**Comment by Xhuis** [comment]
is hugging fetish content, fwoosh

**Comment by FantasticFwoosh** [comment]
Good question @Xhuis I'd say no because its abrupt and is generally recognised as a mature intimate response between people.

- Doesn't mean it can't still be abused by doing it too much to clearly make people uncomfortable.

It would be a different matter if hugs were a target the chest interaction enabled by grab and could be held indefinitely. Again, headpatting is for **simpleton's & doggo's**, nobody wants to touch your greasy-ass scalp.

**Pull request closed without merging**
