### PR TITLE
This fixes the issue of the white ship shuttle console

### LINKED ISSUE #7153: No board for the white ship
Paragraph 2 of this http://www.ss13.eu/wiki/index.php/White_Ship
says the computers can be repaired on the white ship. However, no boards exist that work. The shuttle one and ferry ones just say "missing" when installed there.

### LINKED ISSUE #8718: Shuttle consoles break completely when repaired
Smash a shuttle console and repair it, suddenly you can't take it anywhere because it loses all its destinations

This happens for the white ship, not sure about others.

### PR DESCRIPTION
**Pull request by Firecage**
This fixes the issue of the white ship shuttle console breaking when you tried to repair it. It was both due to their not being a real white ship console and a white ship console circuit board. This also adds the proper console to the white ship. Tested and everything works.

Fixes #8718 
Fixes #7153

### CODE REVIEW

**Comment by Lumipharon** [comment]
Does this mean you could steal the board an rebuild it somewhere else to control it remotely?

**Comment by Supermichael777** [comment]
sure, is that a problem? actually it might be prudent to put a spare control board on the white ship

**Comment by Firecage** [comment]
@Lumipharon Yah, I believe so. The same should also be true for the Gulag shuttle and the mining shuttle.

**Comment by Miauw62** [comment]
YOU DIDNT USE THE MAP MERGER ;~;
Op 13-mei-2015 03:03 schreef "Supermichael777" <notifications@github.com>:

**Comment by Firecage** [comment]
@Miauw62 , I don't know how....

**Comment by Jordie0608** [comment]
https://tgstation13.org/wiki/Map_Merger

**Comment by Firecage** [comment]
.....Mmmm....Third times the charm.

**Comment by Firecage** [comment]
@Jordie0608 Yaaaay, I got it to work!

**Pull request merged**
