### PR TITLE
Fixes ODing on crank/other chems, viruses, and other things damaging/healing robotic limbs.

### PR DESCRIPTION
**Pull request by ShizCalev**
:cl: ShizCalev
fix: Fixed chem OD's causing damage to robotic limbs.
fix: Fixed wood golems repairing robotic limbs every tick of life()
fix: Fixed vampires repairing robotic limbs every tick of life()...
fix: Fixed shadowpeople healing robotic limbs every tick of life()
fix: Fixed poppeople healing robotic limbs every tick of life()
fix: Fixed adjustBruteLoss and adjustFireLoss not properly discriminating for limb status types.
tweak: Fixed bibles healing robotic limbs, because your false deity can't fix SCIENCE.
fix: Fixed the Starlight Condensation, Nocturnal Regeneration, Tissue Hydration, Regenerative Coma, and Radioactive Resonance virus symptoms repairing robotic limbs.
/:cl:

Gonna be away the next two weeks, so if there's anything major after today just go ahead and close it and I'll fix it when I get back.

### CODE REVIEW

**Comment by Barhandar** [comment]
Robotic limbs are used as point generator and in like 5% of the rounds, let's nerf them.

**Comment by Cyprex** [comment]
What do you mean by point generator?

**Comment by ShizCalev** [comment]
@Barhandar Sorry you feel that way, but these are all bugs. ODing on burn chems shouldn't cause your prosthetic/robotic arm to fall apart into pieces, and a tissue healing disease shouldn't be fixing them either.

**Comment by XDTM** [comment]
Barhandar is against anything that can be interpreted as a nerf

**Comment by zxaber** [comment]
Except fixing the bug where robo limbs are damaged by OD is a straight buff...
More than the nerf of all the other fixed bugs combined, actually.

That being said, Lightgeists can heal borgs too, IIRC, so they ought to also fix robo limbs.

**Comment by ShizCalev** [comment]
Oh, can they?

**Comment by XDTM** [comment]
You know, we really should add a form of internal damage separated from external brute/burn damage to handle this stuff; it doesn't make sense that a poison that melts your insides bruises your limbs

**Comment by Iamgoofball** [comment]
@shizcalev I coded ODs, this isn't a bug. You're just going to make robolimbs the new roundstart meta.

**Comment by XDTM** [comment]
it's an inconsistency at the very least

**Comment by Iamgoofball** [comment]
Tough shit, stop making chem abuse easier

**Comment by Peeping-Peacock** [comment]
The worst inconsistency with robolimbs is that a fully aug'd plasmaman will still burst into flames in the presence of 02. Considering how often Roboticists actually go through the lengthy tedium of installing cyborg limbs (fucking never) its no wonder there is a bunch of unintuitive things relating to it.

**Pull request merged**
