### PR TITLE
Wayward grammar

### PR DESCRIPTION
**Pull request by Mervill**
`This is model is ...` `->` `This model is ...`

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Mervill** [comment]
Incidentally, this is the only place where the clear pda can be found
https://github.com/tgstation/tgstation/blob/master/code/game/asteroid.dm#L115

**Comment by Iamgoofball** [comment]
@Mervill you can also get it from chameleon PDAs

**Comment by Tacolizard** [comment]
I tried to add the clear PDA as pubby maint loot but it wasn't merged

**Comment by Mervill** [comment]
AFIK there's no benefit to having the clear pda, other then being cool AF

**Pull request merged**
