### PR TITLE
Redesigns the armory, adds an auxiliary storage room to security, etc…

### PR DESCRIPTION
**Pull request by pudl**
The armory has been reduced to its old size. It still retains all Tac equipment. Additionally, there is a new storage room in security for misc. equipment. See #11977.
- All guns are moved to two lockers. 1 extra shotgun has been added, bringing the total up to 3.
- All armor is moved to a locker
- Tac equipment is now in lockers
- An IV drip and blood bag are now in the execution room for lethal injections
- Atropine medipens have been added to code and put into the armory. Sprite by myself
- As an added touch to medipens, I also gave morphine pens a unique sprite
- Security lockers now contain security gas masks
- The warden's table with like 8 gas masks is now a rack of 3 hybrid tasers
- A locked contraband closet has been added to the security office
- Auxiliary storage has replaced evidence storage, with the detective's evidence closet being a single locker more than capable of taking its place
- Auxiliary storage contains two secways w/ keys, a toolbox, a toolbelt, and 3 portable flashers. All these tools are to allow one security officer at the least the equipment to hack doors and access areas she/he may need inside of
- Detective now has a single evidence closet with an evidence bag in it
- Ammo box for beanbags added and in the armory. Since the riot shotgun has an internal magazine, it's a cardboard box. Sprite by WJohnston

Left is atropine, right is morphine.

Changelog coming soon.

### CODE REVIEW

**Comment by pudl** [comment]
Whoops lmao

**Comment by WJohn** [comment]
Certainly much better looking now.

**Comment by Fox-McCloud** [comment]
Should be riot shotguns instead of regular ones, IMO.

They hold +2 ammo and can be sawn off.

**Comment by pudl** [comment]
They are riot shotguns.

**Comment by pudl** [comment]
FUCK AUTHOR: NEXIS LMAO

**Comment by pudl** [comment]
???? why

**Comment by tuypo1** [comment]
this is even worse you should be minimising on how little is unseeable from the wardens office this fixs nothing

**Comment by pudl** [comment]
lmao

**Comment by bustygoku** [comment]
You can see pretty much everything from the warden's office here, lockers aren't dense. The only thing you could do is hide in the bottom left corner.

I'll miss how cramped the old armory was but this is probably less awful to deal with as an actual warden when people breach.

**Comment by Jalleo** [comment]
Is that insulated gloves i see that is real powercreep for sec

**Comment by tuypo1** [comment]
Did you not notice the lockers behind the big arse blast doors behind a wall to space

It was bad enough when I could not see everything blocked off by the tac equipment wall in the north west corner

New weapons is great putting them behind blast doors was retarded and now there's a bunch of stuff locked away in lockers the warden does have to leave his office to check perma sometimes the warden should be able to see instantly that somebody stole something in his absence

**Comment by tuypo1** [comment]
That said prisoner transfer Iv is cool and the more shotgun shells sec gets the more likely people are going to accept putting lethal shells for it in the armory

**Comment by pudl** [comment]
I included a pair of insulated gloves, only one, in order to allow at least one officer to hack open doors and reach areas they may need to be in to save people/stop an antag.
This armory increases visibility, moreso than the last one. You can't complain when the warden can genuinely see everything except for the Tac armor, which was already impossible to see.

**Comment by tuypo1** [comment]
somebody could sneak in steal something from a locker then lock it again and the warden would never know if he failed to catch the culprit in the act

i do agree that the gloves are a good idea though

**Comment by pudl** [comment]
Someone who is sneaking in without a security ID would have to break the locker, which is pretty obvious. If they stole a security ID, then someone's gonna turn up dead eventually and that will set off some triggers.

**Comment by tuypo1** [comment]
say also as was mentioned by people in the previous pr for this if you get to the armory you should be able to get what you need and leave you have succesfully broken into one of the 4 most high security areas on the station you are going to want to get out of there fast

also racks just look better

also you want to remove the ion rifle thats crazy

as a regular warden player one of the greatest joys of the job is takeing that thing off its rack and issuing it out or more likely nobody going to pick it up and having to go use it yourself

nanotrasen doesent fix the ais because they cant work out how its a rare ocurence for them to break but comen enough there needs to be a failsafe

and of course the autorifles are still in a special snowflake spot they need to be treated as an alternative to lasers not some tactical gear shit

stealing from the armory shouldent be subtle you can break in silently but the warden should always notice when he looks at it

**Comment by tuypo1** [comment]
and the implication is that yes they have gotten a sec id but no matter what the only way to delay people finding out you looted the armory should be killing the warden to hold things off for a time

**Comment by pudl** [comment]
No more ygloves in the armory.

**Comment by tuypo1** [comment]
say aww thats a shame that was the only part of this setup i liked oh well

**Comment by Dorsisdwarf** [comment]
:-1: 

fuck lockers, I bet you only did that because a wizard teleported into the armor and roflstomped you

**Comment by Steelpoint** [comment]
If the lockers don't have any access then I don't see a problem.

If.

**Comment by Nanotransistor** [comment]
One quick question, would EMP also empty the guns inside the lockers?

**Comment by GunHog** [comment]
EMPs are indeed transferred to the contents of the locker. Two good shots should shut down all of the armory's energy weapons.

**Comment by pudl** [comment]
I haven't played tgstation in almost a year. I made this pr after a discussion with a friend who isn't as good at mapping as I am.

**Comment by tuypo1** [comment]
well let me tell you as a regular warden player its shit

i liked the insulated gloves though sec does need a pair

**Comment by pudl** [comment]
Tuypo1, you have not said a single thing that has convinced me that you aren't either a twelve year old, or someone who's incredibly challenged in the mental department.
Using this setup a warden has sight of all weapons in the armory excepting the Tac gear, which he couldn't see regardless. Additionally, there is a motion sensitive camera in the armory that will alert an AI of anyone who's walking around in there.
There are three lockers, one with riot gear, one with ballistics, and one with energy guns. Of course the best of these three would be the energy gun locker, so theft of it would require preparation. Eguns will be drained of their energy by an EMP, but ballistics wont. A single EMP will open all three lockers, meaning you can get out a riot shotgun (there is ammo in the locker, mind you) and use that to defend yourself while you collect energy guns, and charge them later.
Alternatively you could steal the bullet Tac gear and use that in a heist for the energy guns. This would be your best plan of action, as no one can see you taking Tac gear, but it would require more EMPs, and more storage space since you will be carrying around more weaponry.
This change is by no means a buff to security, or a buff to antags, or a nerf to either. It's a different approach to the concept. The armory is less cluttered, and objects are in organized lockers. You can access the entire armory from one tile, next to all three lockers. Security now has less control over their Tac gear, but have a much higher amount of awareness over their primary weaponry. Antagonists now have to plan more to break into the armory, but once they're opened the lockers, everything they could ever want is in front of them, all within an arm's reach.

**Comment by tuypo1** [comment]
How does putting something behind a solid locker give sec more awareness it was bad enough with the wall above the autorifles

This is as buff to antags in every way you can come in from space where almost all non hop theft comes from and take the autorifles without being seen now admitidly you can raise the shutters but they shouldn't be there in the first place and having them the one weapon not being on lockers makes them even more special snowflake then the shutters already were I will admit I'm glad you realise that the lasers should be just as much a target as the rifles (sort of) 

I will admit the idea of stealing some weapons to make it easier to steel more is pretty cool but it's not worth what we lose

And the tac gear is not really tac gear the only person who thinks that is steelpoint it's fuckers got laser resistance gear.

I'm not against people being able to steal weapons I'm against people being able to steal weapons withought the warden ever noticing lockers are shit.

**Comment by Miauw62** [comment]
i think one of the complaints with the new armory was lack of cover for op breakins, i suggest just putting the autorifles on a pile somewhere.

**Comment by Steelpoint** [comment]
To be fair Miauw if Ops are breaking in with a bomb then they will have blown up all their possible cover, in fact with the older armoury design their bomb would blow up more than just the armoury.

If they're going in with C4 then you may have a point.

The positioning of the lockers in this design does offer some cover to Ops if they C4 their way in.

**Comment by Xhuis** [comment]
Looks quite good, but I feel that the armory should have a desk like it does currently, for easy weapon distribution without allowing people into the armory itself.

Auto-rifles in lockers... :+1: x :100:

**Comment by WJohn** [comment]
It DOES have one, xhuis, it just has a shutter on top of it.

**Comment by Xhuis** [comment]
Oh really? In that case, nevermind my earlier point.

**Comment by tuypo1** [comment]
Well I do have to agree with xhuis partially if your going go down the shitty path of weapons in lockers at least put the autorifles in the same situation they should be viewed as an alternative to lasers not some special snowflake weapon.

I'm still going to take all the weapons out and put them on racks every time I'm warden though. Just as I always get the walls above the autorifles torn down now.

**Comment by tuypo1** [comment]
A question though are there still windoors behind the shutter it needs to be possible for the officers in the equipment room to see in to (well not so much with this layout but still.

**Comment by pudl** [comment]
Yes, there are still windoors. I have added a camera to Tac Equipment as well.
I would like for there to be a way for the warden to have more say over the organization of the armory. I could put some unbuilt racks into the auxiliary storage and the warden, if she/he wants, can just set up the armory however she/he so pleases.

**Comment by Metacide** [comment]
Looks good to me.

Can you @ me if this gets pulled to remind me to bring MetaStation's armoury more in line with this?

**Comment by pudl** [comment]
Yeah, let's just hope it actually gets merged. :P

**Comment by pudl** [comment]
Can I get a "ready to review/merge" tag please?

**Comment by Dorsisdwarf** [comment]
PR ready to review by maintainer.

**Comment by Razharas** [comment]
@pudl 
Good luck pal

**Comment by pudl** [comment]
@Razharas Fuck you, it's working now.

**Comment by tuypo1** [comment]
the moment of truth is soon (I really hope this does not get merged)

but yes if it does get merged racks in storage is probably a good idea

**Comment by Dorsisdwarf** [comment]
@Cheridan 

Controverisal PR inbound, requesting review

**Comment by WJohn** [comment]
>112 files changed

Pudl I think you messed something up.

**Comment by Cookiesndip** [comment]
Terrible because it sounds like the lockers are access restricted. On top of it the autorifles are hilariously easy to access from space, so it's just retarded.

1. If ANY antag manages to break into the armory, with or without a warden, HoS, or Captain ID, they should be rewarded for it with the ability to steal guns. Necessitating several EMPs to unlock a single locker, then receiving drained weaponry that you can't even lose is a huge antag nerf. At the same time, being able to steal all the Steelrifles is a buff, but not too severe because antags sole benefit is getting the drop on someone, and for that you need quick crits or stuns, not sustained damage which more benefits sec in rev/gang. It's more of a weapon that enables easy kills once you down someone, for most antags, and since the tasers are behind 1 rwall, through a bunch of lockers and shutters, next to the wardens office. The lockers they're in is also locked, so you can break into the armory through rwalls, steal a bunch of lockers, then you have to find an emag or EMP (most antags aren't tators, so probably an EMP) or one of three IDs on the station by killing them without a gun, THEN you can use a single weapon you've stolen into the armory for. On top of it you can't even swipe guns quickly, you have to swipe an entire fucking locker, run out into space with it, stash it somewhere safe, then take the other lockers as well, instead of being able to pick and choose.

It also means wizards can't steal ANYTHING from the armory, which is just poor design and a severe nerf.

Would stop playing on /tg/station/10 if merged.

**Comment by pudl** [comment]
What the fuck

**Comment by pudl** [comment]
lmao

**Comment by Bawhoppen** [comment]
this redesign looks cancerously dumb

**Comment by pudl** [comment]
This is getting really annoying to deal with fixing.

**Pull request closed without merging**
