### PR TITLE
[DNM] AFK heads and headrevs no longer delay rev rounds

### LINKED ISSUE #29322: Rev round can still be delayed by AFK players.
This player disconnected, was stuffed into a cardboard box by another player, then the other heads died, and the round did not end. I thought either of these cases counted you as dead?

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: AFK heads and headrevs no longer delay revolution rounds.
/:cl:

When a mob leaves, their client is deleted. Their key, however, stays the same, and this is what the code was checking. It now checks for a client instead.

Additionally, headrevs can no longer be AFK and still count against the heads.

Fixes #29322.

### CODE REVIEW

**Comment by RandomMarine** [comment]
I don't agree with this fix. Many players (including myself) suffer from intermittent disconnects and that shouldn't potentially end the round.

**Comment by Xhuis** [comment]
Frustratingly, I'm not sure if there's an easy way to solve that problem. Being someone who has occasional Internet problems, I completely get the sentiment, but I don't know if it's addressable.

**Comment by RandomMarine** [comment]
I'm not even sure if it should be addressed in the code.
If anything, a disconnected head/headrev in a rev round should just trigger an admin alert.

**Comment by Xhuis** [comment]
Even so, that'd be considered a balance change, which I'm avoiding. This was the intended way for it to operate; I was just fixing it so that it does.

**Comment by GunHog** [comment]
Five minute delay?

**Comment by RandomMarine** [comment]
How is alerting administrators a balance change?

**Comment by Xhuis** [comment]
It's in that it's taking the intention of the code - to end the mode with clientless revs/headrevs - and removing it. It's enough of one that I'm not sure it'd be accepted under the freeze. Nevertheless, I suppose I could look into it, but it isn't a high priority for me.

**Comment by ShizCalev** [comment]
Should definitely add a grace period of a minute at the least before they are considered gone. Having a round end on you because you got comcasted without actually getting killed or something seems really disheartening.

**Comment by Dorsisdwarf** [comment]
I say make it wait two minutes after registering DC before ending the round (Thus giving you a minute for your internet to come back, the up-to 40 seconds ad wait if you aren't premium, and 20 seconds grace

**Comment by ShizCalev** [comment]
....there's an ad wait? lol

**Comment by AnturK** [comment]
Adding grace period fine this is fixing an issue and is not really affecting the mode much.

**Comment by ExcessiveUseOfCobblestone** [comment]
Is this actually a problem?

**Comment by lzimann** [comment]
About alerting admins instead of ending the round: The game should function without actually requiring an admin online.
But yea, an one/two minutes grace period for disconnect as last head should be enough for this.

**Comment by RandomMarine** [comment]
That's the thing, this PR isn't even tackling the key issue.

The only difference a client makes when a head is hiding in a locker is whether or not they'll fight back once they're finally discovered.

**Comment by Xhuis** [comment]
Given the amount of negative feedback this PR has received, I'll be making some changes to it once I get the opportunity, probably to add the grace period y'all have recommended. This is DNM for now.

**Comment by DoctoreMad** [comment]
You want to fix the bug but fixing it would cause problems but taking a alternative path would be limited by the freeze?

Well this quite tiring. Not to say, probably not in the spirit of what the code freeze is meant to be.
Can't you just PM KorPhareon and have him let you/another coder fix this already?

**Comment by ShizCalev** [comment]
@DoctoreMad Two maintainers have said that adding a grace period is fine. Freeze isn't an issue with this.

**Comment by DoctoreMad** [comment]
Oh I just saw Xhuis commenting on not being allowed to do that because of the freeze then skipped everything
Whatever then

**Comment by Xhuis** [comment]
👏

**Comment by Xhuis** [comment]
Just a heads-up to y'all: I'm getting overwhelmed with the amount of stuff I'm doing at once so I'm gonna put this PR on "potentially closing" for now; I'll decide whether or not to by tomorrow. It's not a high-priority issue so it likely wouldn't be coming back.

**Comment by Xhuis** [comment]
Yeah, given how much I have already this is fairly low on my priorities, especially given that the game still works fine without it. If I do this again it'll be as another PR!

**Pull request closed without merging**
