### PR TITLE
The nth grown food refactor: Changes MOST unique plant effects into special plant genes/traits! Plant Genes+ 

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

This PR's a biiit of a doozy so let's break it down.

image

### The boring stuff:
- Auto doc'd much of grown botany food and plant traits and renamed a buncha variables and parameters to match modern contribution guidelines.
- Cleaned up a good bit of plant gene code left over from the prior refactor and modernized some of it.

### The interesting stuff:
- All plant effects that were once unique to a plant are now un-graftable, un-mutatable, un-shearable plant traits - called **IMMUTABLE** traits. Take holymelons for example:

image
_The anti-magic trait of holy-melons is now a plant gene named "anti-magic vacuoles". Functionally identical, the only difference is now that it's not hidden behind obscure game knowledge._
image
_Deathnettle's have two immutable traits now. One of them is based on the plant's backfire effect (hurting people who hold it) and the other is what gives deathnettle's their force._

The ultimate goal of this PR was to make all of the hidden, arcane traits that are spread through botany's various plants and add a way to figure out they exist in game. Take omega-weed, for example, which has a maximum volume of 420 units. Nowhere in game can you figure that out easily, but now there's a plant trait to hint to the botanist that something is unique with this plant
image

### **What does this mean for the enterprising botanist?**

In most cases, all the plants should act the same way. None of the immutable traits are graftable from any of the plants, they cannot be sheared off of the plant, and they cannot be mutated randomly from strange seeds or high instability mutations.

Though, in refactoring these traits, two things have been fixed: Novaflower's on hit and Deathnettle's on hit now proc again. If you aren't aware, Novaflowers apply firestacks and Deathnettles paralyze on hit. They've been in an unreachable code segment for a few years now and i'm not sure if they should be "fixed" or not, since I think they don't need any buffs.

### _A few other things have changed:_

- Liquid Contents can no longer be applied to plants with Hypodermic Prickles, and visa-versa. They already didn't work together, but this means you need to go through an extra step to make LC-deathnettles.
- Killer Tomatos no longer have liquid contents. Didn't really make sense, anyways.

- [x] Make sure I didn't break anything
- [x] Make sure nothing slips through the cracks
- [x] Make sure I got everything

## Why It's Good For The Game

(Somewhat) More sensible code, more mechanics being revealed to the player though in-game means rather than through the wiki, additional ability for adminbus. 

A ton of mechanics of botany are hidden behind arcane knowledge or through the wiki. This PR serves to make botany more available and less sekret.

## Changelog
:cl: Melbert
add: There are now over a dozen new plant traits, but they're not really new. A bunch of unique plant behaviors (like holymelon's anti-magic) are now un-graftable, un-shearable, un-mutatable plant traits that show up on the plant analyzer now.
qol: The plant analyzer now differentiates between traits you can mess with and traits you cannot.
balance: Killer Tomatos no longer have liquid contents naturally.
balance: Liquid Contents and Hypodermic Prickles are no longer compatible with one another. They already didn't work together in most cases, this just makes it so you need an extra step to make Liquid Contents Deathnettles.
fix: Novaflowers now apply their on hit effects again.
code: Autodoc'd grown food / plant gene code
refactor: Refactored grown food / plant gene code
admin: A bunch more botany grief stuff is logged now
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
ORANGESpwoer

**Comment by the-orange-cow** [comment]
For what it's worth, Liquid Contents and Hypodermic Prickles do actually work together, so long as HPrickles is 'before' LContents in the trait list.  It will be a little bit unfortunate to see them no longer combinable, seeing as how usually when you are trying to inject reagents via Hprickles, you're pretty much done with the vegi once it's payload is delivered.  It being destroyed via LContents is super convenient for not having to leave excess waste afterwards.

That being said, very nice addition with the new trait system, more transparency is always nice.

**Comment by MrMelbert** [comment]
> Liquid Contents and Hypodermic Prickles do actually work together...

Yeah, it depends on the order in which it registers the `on impact` signal on the plant. I didn't really like that there was a trait that only worked half the time depending on the internal order of genes so I made them incompatible.

**Comment by BebeYoshi** [comment]
Wouldn't cotton family, grass family and tower cap family all be considered IMMUTABLE plant traits allowing them to be used in loom/hand/cut to get materials? Also does the change you did in jupiter cup actually make it extractable or is that change just a change of words? Great PR overall

**Comment by MrMelbert** [comment]
- Cotton, Grass, and Tower Caps being able to be made into a material I thought about sticking in an immutable trait, but since it's like the actual plant (cut logs into planks, loom cotton into cloth) I decided against it
- Jupiter Cups's trait is still un-extractable, it's just handled in a different way now than it was before. (Via trait flags, instead of unsetting its mutability)

**Comment by BebeYoshi** [comment]
What about Bongo tree and shrubs? They seem unique enough to have their effect as a trait, also Replica Pod has a special feature which just lets you get a max of 2 seeds, could be made into a trait too but I might just be thinking too far.

**Comment by MrMelbert** [comment]
Bongo Tree / Gatfruit / Bananas / Egg-plants, I'm leaving the way they are currently since their ability to unshell their plants to stuff (guns, bungopits, etc) is tied to the actual type of the plant and the edible component (as they're considered food trash)

Shrubs, like glowshrooms, are physically planted down so I didn't disconnect them yet, though they could definitely be done.

Replica pods are much more complex in the way they're handled so I probably won't move them over yet.

**Comment by ExcessiveUseOfCobblestone** [comment]
the paralyze is going to need to be changed to a knockdown or its gonna be meta on merge

**Comment by MrMelbert** [comment]
i'll remove it entirely cause I think it's busted anyways

**Comment by the-orange-cow** [comment]
I think this might have broken the ability for larger reagent amounts to overwrite smaller ones via crosspollination.  I don't know for a fact this pull is the cause, but I've only noticed it not happening recently after the merge.

**Pull request merged**
