### PR TITLE
Removes overlay queuing, saves 6/7 seconds of initialize. Lightly modifies stat tracking macros

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

So we have this overlay queuing system right? It's built with the assumption that the "add to overlay list" operation is real expensive, and is thus useful to queue removals or additions.

It turns out that it just isn't, at least during init. In my testing the operation of queuing took LONGER then the actual overlay add/remove did.

That's ignoring the cost of the subsystem's work.

I've also modified part of the stat tracking macro, since it took a good bit of cpu time, and didn't seem to well, do anything. So far as I can tell it always evaluates to 1

## Why It's Good For The Game

Speeds up initialize, and potentially the rest of the game too. Also now we can always trust the overlays list, which is useful

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Does NOT appear to cause duping, at least in my testing

**Comment by AnturK** [comment]
Dangerzone PR

**Comment by Mothblocks** [comment]
sus

**Comment by optimumtact** [comment]
>So we have this overlay queuing system right? It's built with the assumption that the "add to overlay list" operation is real expensive, and is thus useful to queue removals or additions.

No, it's built on the assumption that many adds and removes happen within one timer tick and it might be slightly more efficient to do them to the actual overlay list once a tick instead.

**Comment by Mothblocks** [comment]
do we have a good way of testing the impact of either of those?

**Comment by optimumtact** [comment]
no not really

**Comment by Mothblocks** [comment]
I don't have internet other than my phone data can someone test merge this

**Comment by LemonInTheDark** [comment]
Testmerged on manuel now

**Comment by Mothblocks** [comment]
@LemonInTheDark merge skew

**Comment by LemonInTheDark** [comment]
nooooooooo

**Comment by FreeStylaLT** [comment]
haha 6/7

**Pull request merged**
