### PR TITLE
deathmatch ui qol and deathmatch plasmamen are made humans

### LINKED ISSUE #81622: Packed deathmatch lobbies can lead to the UI getting funky
## Issue Summary

When a lot of players sign up for Deathmatch, the ckey list can go below the Ui buttons and look wack

image

## Round ID:

I forgot

## Reproduction:

Fill up a lobby.

Wow.

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

2024-02-22 18_33_26-Space Station 13

there is a new option in the loadout dropdown "Randomize", using it picks a random loadout
also the UI scrolls now so it can survive more players
and plasmamen are set into humans as to not need to create more plasmaman specific outfits

## Why It's Good For The Game

player list going out of its section = bug bad
plasmamen getting lit on fire instantly and dying = bad
Closes #81622
## Changelog
:cl:
add: Added an option to deathmatch loadout dropdown that allows you to pick a random loadout
fix: In deathmatch, plasmamen are made humans and the UI supports more players
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
On #56501 we added 2 traits to keep plasmamen as themselves and avoid some of the same issues for Highlander.

I have no idea how Deathmatch works, but could be another way to fix the issues.

**Comment by Rhials** [comment]
Add "Closes #81622" to your PR body so it's auto-closed on merge

**Comment by mc-oofert** [comment]
> On #56501 we added 2 traits to keep plasmamen as themselves and avoid some of the same issues for Highlander.
> 
> I have no idea how Deathmatch works, but could be another way to fix the issues.

NOFIRE won't help

**Comment by Zargoar** [comment]
I loved being a plasmaman and on fire so I had more motivation to attack other people in the deathmatch.
It reminded me of the Immolation pyromancy from Darksouls.

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
