### PR TITLE
Minor tram door logic changes

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
- Warning lights now flash faster and begin to flash before the start of the begin travel proc, giving people some more notice.
- Increased the speed the tram controls reset, ready to be dispatched again. Less mashing at the console as it does nothing.
## Why It's Good For The Game
People don't like running for the tram and falling off the platform. People boarding don't like waiting 3 seconds to dispatch an empty tram.
## Changelog
:cl: LT3
qol: Tram controls unlock faster on arrival at a station
/:cl:

### CODE REVIEW

**Comment by SkeletalElite** [comment]
> Increased the speed the tram controls reset, ready to be dispatched again. Less mashing at the console as it does nothing.

one problem with this. one person can hold the entire tram hostage by building tram girders on all the doors and no one can deconstruct them if the controls become responsive quicker.
It's already kind of a problem that if they manage to get those girders converted into walls before you stop them you can do literally nothing about it unless they didn't seal the windows in which case you can laser them to death but it will be even easier to do with this change.

**Comment by lessthnthree** [comment]
> 

I saw this for the first time the other day. We can take this as an opportunity to fix then, is 3 seconds enough?

**Comment by SkeletalElite** [comment]
> > 
> 
> The tram doors are just windoors, you can take them apart quickly like any other. They open on arrival so the first step is already done.
> 
> Does it really happen that often to be a problem?

I'm not certain how often it often happens, I had it happen a couple of days ago, and it was really annoying. The problem isn't the doors themselves, someone will literally wall the doors off and spam move the tram to prevent people from deconstructing the walls. 

The best way to fix it would probably be to add a way for heads to lockdown the tram with card swiping, but that seems out of scope for this PR

**Comment by lessthnthree** [comment]
> 

I like the lockout feature, I'll look into it though it's not in scope.

Another possibility (well could do both really) is making the 8 white tiles invincible and unable to be built on. Problem is they're machinery, not turf so would have to get creative.

Either way let's start with this, someone building girders and blocking is such a rare edge case it shouldn't prevent the changes. If you had all the engi tools you could RCD the wall as well.

**Comment by lessthnthree** [comment]
Like as I see right now. Short of restricting building, this change isn't going to stop people from doing things like this, which they can do right now anyways.

image

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
