### PR TITLE
Refactors Say-Modification into a Component [WIP]

### PR DESCRIPTION
**Pull request by Ordonis**
:cl: Ordo
Changes how say commands are modified. Now almost anything can modify how you speak!
/:cl: 

See #37457
This will be done in three steps, unless someone more experienced tells me I should do it differently.

1) Create the component type 
2) Create a readme for word-replacement JSONs
3) Change the moustache to fit the new system

SECRET STEPS
4) create a language crate
5) oranges a wumbis

### CODE REVIEW

**Comment by ma44** [comment]
*scream

**Comment by ma44** [comment]
Surprisingly enough speechModification() is a proc for any obj/item that wouldn't just be restricted to the mask slot

https://github.com/tgstation/tgstation/blob/ba1030f8038f07bfba17d4b2887c584d09b8c9fe/code/game/objects/items.dm#L227

**Comment by Ordonis** [comment]
Yeah, we've gotten it to work with head items, this is just going to make it easier to do so; for example, with masks, you check wear_mask, but for head, you only check _head.

**Comment by Ordonis** [comment]
@Barhandar Oranges told me to make it a component, you'd have to bully him for an answer as to why he went with that

**Comment by ma44** [comment]
https://github.com/tgstation/tgstation/blob/057aa31cda6eb47505bc9fdd263fd1427b1276ed/code/modules/mob/living/carbon/human/say.dm#L31

>tfw speaking had a proc that hard checks if there's a chameleon mask on the speaker

**Comment by Ordonis** [comment]
So, currently it's looking like this should improve performance overall, because holy shit the number of hardchecks, but it'll take substantially longer to go through and de-snowflake things like the chamelon mask, horsemask, Cluwne etc. Hoping to bring it down check only when you actually say something. Someone more skilled with BYOND might be able to get it down to checking only when you change possession of an item, but that would be a refinement rather than a base step

**Comment by ExcessiveUseOfCobblestone** [comment]
@ma44 say code only checks for mask though hence why it wouldn't work with anything else.

This is going to be one of those "this will be easy!" PRs that end up being massive lol

**Comment by optimumtact** [comment]
@Ordonis signals and components go together, they're like wine and cheese

**Comment by optimumtact** [comment]
I let your other one through, but you need to do this before adding more K

**Comment by Ordonis** [comment]
I think this one will make it way easier (once done) too do more of them,
so that's fine by me. Also at the moment I'm trying to figure out how to
make this tread on the least number of toes possible; I THINK I should be
able to make it so that even having a chemical or somewhat in your system
calls a universal say modification function, but that has added time and
work. Yay feature creep.

**Comment by optimumtact** [comment]
I think it's best to start with a minimal scope, just items that register a component can listen for a signal from the mob and transform the radio message and then return it.

You can add that other stuff as needed in later PR's when the need arises, otherwise you may never finish the change

**Comment by Ordonis** [comment]
Fair enough; this is my first project of this scope, so keeping things
minimal is probably for the best anyway.

**Comment by Ordonis** [comment]
Current plan, after many non-working plans:

speech_modification is a var that can be attached to any obj/item/clothing; default is zero (no speech modification), and 1 will be active; this leaves room to add in degrees and types of speech modification later on. Say will now check if you're wearing an item whose speech_modification == 1, and if so, it'll run the speechModification function that was written for the moustache.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
Every instance of a binary 1/0 should be replaced with TRUE/FALSE

**Comment by Ordonis** [comment]
Even under the assumption that the system will change in the future? I'm happy to switch it to boolean, but it seems a little odd to me to make it more difficult to expand upon in the future, in the spirit of modularity.

**Comment by ExcessiveUseOfCobblestone** [comment]
You can make your own defines to better reflect what these are suppose to represent. "Modes" should always be defined in some form.

**Comment by Ordonis** [comment]
In that case I'll probably switch to boolean for now, and add in more bells and whistles later.

**Comment by Ordonis** [comment]
Update: I just got out of the hospital and am still in recovery; I should be able to start working on this in earnest in a few days.

**Comment by optimumtact** [comment]
cut my life into peices

this is my last resort

**Comment by KorPhaeron** [comment]
Let me know when you're feeling better

**Pull request closed without merging**
