### PR TITLE
Adds Blank Paper, a new mime cocktail

### PR DESCRIPTION
**Pull request by BebeYoshi**
Adds a new drink, made by mimes, for everyone! It was based in a costum drink that had the flavour text of eraser, nothing and future! Recipe is 1 part Silencer, 1 part Nothing and 1 Part Nuka Cola (it also heals mime like most mime drinks do)
:cl: BebeYoshi & Hexmaniacosanna
add: A new drink called Blank Paper was added to the bar menu, it was made by a mime and it represents a new start.
/:cl:
The sprite:

[why]:  This was a special costum drink and we thought it deserved its own cocktail, besides, mimes needs more unique things (even if you don't even need a mime to make it).

### CODE REVIEW

**Comment by Therapist1** [comment]
Seems like quite the drink to mix just for basic drink moodlet.

**Comment by davethwave** [comment]
As a bartender semi main I feel offended that you only see the usefulness of drinks in their moodlets... There are drinks that can kill just by having a glass and those that can cool or heat you up in case of plasma fire or ling stings, and don't forget nuka cola...

**Comment by ExcessiveUseOfCobblestone** [comment]
Wouldn't those drinks be more effective unmixed?

**Comment by BebeYoshi** [comment]
> Seems like quite the drink to mix just for basic drink moodlet.

You can get up to two moodlets by drinking it, you get a moodlet for a "good drink" and a moodlet for drinking it multiple times.
But I'm open to suggestions, the boozepower for instance is up to change. We made it thinking of a Cute Sweet drink.

**Comment by OverlyGeneric** [comment]
@ExcessiveUseOfCobblestone Yeah, this drink is honestly less effective and more expensive than the parts used for it.

**Comment by duckay** [comment]
Maybe replace nuka for Snow White?

**Comment by plapatin** [comment]
milkies

**Comment by ahkent** [comment]
if you gotta buff it to sleep at night, buff it to sleep at night

but man who cares

it tastes amazing

**Pull request merged**
