### PR TITLE
cult stun is blockable

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

cult stun is blockable with shield

## Why It's Good For The Game
the 16 second paralyze hand going through all blocks does not make for fun combat nor fights

## Changelog
:cl:
balance: cult stun is blockable
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
ok now you're cooking

**Comment by SimplySmiley123** [comment]
It would be nice if mindshields (the thing you're encouraged to do by it preventing regular conversions) reduced the stun time as well for their cost of guaranteed round removal if you get sacced with a mindshield.

**Comment by Vect0r2** [comment]
If there isn't already, could you add some feedback like "you reach out your hand, but [name] blocks it!"

**Comment by ATH1909** [comment]
should this maybe count as an unarmed attack for the purposes of blocking? since it's, uh, your hand?

**Comment by NullDagaf** [comment]
You can already block these with any anti-magic utility of your choice. Though if bothering the botanist for holy-melons during an active cult outbreak is still too much, stun times being reduced through having holy water in your system would probably work too. Making it be blocked through shields is just lazy.

**Comment by Xackii** [comment]
I was killed - delete

**Comment by SimplySmiley123** [comment]
> You can already block these with any anti-magic utility of your choice. Though if bothering the botanist for holy-melons during an active cult outbreak is still too much, stun times being reduced through having holy water in your system would probably work too. Making it be blocked through shields is just lazy.

So only chaplains with their nullrod and botanists with holy melons if they even got them out in time.
Yeahhhhh nah.

**Comment by Higgin** [comment]
Every day I pray for active blocking, but in the mean time, this makes sense to me - it is a touch attack.

**Comment by MrMelbert** [comment]
I can't think of anymore that sounds more infuriating than having my one-use spell be consumed on RNG block chance.
(Also I would prefer if the spell had an alternative effect if blocked rather than doing literally nothing, maybe by making them force-drop their shield or something, idk)

Anyways cult stun was just nerfed in another way so let's not over-correct.

**Pull request closed without merging**
