### PR TITLE
Adds RCL inhands

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
spriteadd: Added RCL inhands
/:cl:

capture  capture

shamelessly ported from paradise

### CODE REVIEW

**Comment by ShizCalev** [comment]
Can you put them in mob\inhands\equipment\tools_*.dmi instead please?

**Comment by MoreRobustThanYou** [comment]
sure

**Comment by MoreRobustThanYou** [comment]
Oh god come on

**Comment by MoreRobustThanYou** [comment]
merge-ready now

**Comment by DaxDupont** [comment]
29391398-1b2c53f2-82c5-11e7-9a1b-c1a138a298b1 1
"My lizard, it spit on your face"

**Comment by MoreRobustThanYou** [comment]
lel

**Pull request merged**
