### PR TITLE
Ssreligion

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Instead of tracking the various chaplain vars in the ticker

All the chaplains after the first will now have the same null rod type as the original.

### CODE REVIEW

**Comment by JJRcop** [comment]
Maybe we should have a "Subsystem" religion, worshiping the almighty MC.

**Comment by CrAzYPiLoT-SS13** [comment]
Seeing the number of really weird subsystems being made at this time
(SSsqueak, SSreligion), why don't you guys just implement a SSmisc
subsystem for this kind of things? Just a  simple subsystem that would
process away. It would also remove the need for SSdisease.

**Comment by optimumtact** [comment]
Doesn't really offer us anything over having separate ones.

**Comment by CrAzYPiLoT-SS13** [comment]
Except reduced clutter in the stat window?

**Comment by A-t48** [comment]
Sssnakes when?

**Comment by AnturK** [comment]
Subsystems could use a show in stat variable, that's true.

**Comment by FantasticFwoosh** [comment]
Huh interesting. So given the missed opportunity, will ashwalkers/ghost roles ever be preset to their necropolis worshipping religion?

**Pull request merged**
