### PR TITLE
Include item overlays in attack animations (shows the proper color of screwdrivers etc)

### LINKED ISSUE #31871: When a screwdriver hits a fire alarm the screwdriver texture goes slightly transparrent and loses all colour
Issue reported from Round ID: 77615 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

https://gyazo.com/c54ab576cf3441229a69fe050d9d45cd
^ gif so you can reproduce issue

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Fixes #31871

:cl: Naksu
fix: Screwdrivers and other items with overlays now show the proper appearance of the item when attacking something with them, or when put on a tray.
/:cl:
image

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
hmm might not even need a mutable appearance...

**Comment by SpaceManiac** [comment]
Wait, that works? Then what is getFlatIcon even for?

**Comment by vuonojenmustaturska** [comment]
¯\_(ツ)_/¯

It working was news to me as well

**Comment by vuonojenmustaturska** [comment]
now fixes #32240 too. `add_overlay(new /mutable_appearance(I))` works but `add_overlay(mutable_appearance(I))` doesn't 🥇

**Comment by vuonojenmustaturska** [comment]
it just works during testmerge, no issues that i've seen

**Pull request merged**
