### PR TITLE
Makes satchels stack by name instead of type

### PR DESCRIPTION
**Pull request by kriskog**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Skoglol
tweak: Satchels (chem bag, bio bag etc) now stack by name in addition to type.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
Prevents different pills and such from stacking in one big pile in the satchel, as suggested in another PR.

### CODE REVIEW

**Comment by XDTM** [comment]
I don't think it's wise as long as there is renameable stuff, which does include patches and pills

**Comment by kriskog** [comment]
Why is that a problem though? What is there to be gained by gaming the stacking system?

For the record, smart fridges already stack pills by name.

**Comment by XDTM** [comment]
Mostly because a patch and a pill with the same name would stack, and potentially other renameable items. It's not a _huge_ issue especially since the contents are whitelisted anyway all things considered.
Thinking about it again i suppose it's an improvement.

**Comment by kriskog** [comment]
So when you make a pill, "pill" is added to the end of the name. So trying to name a pill "Brute patch" will make it "Brute patch pill". Same for patches. Bottles cannot be renamed, maybe beakers? You are going to have to try to break it to actually do so, at least so far as I can see.

**Comment by XDTM** [comment]
I was thinking about pen renaming, which does not have restrictions, but if that does not apply to pills/patches my point is moot unless admins get involved.

**Comment by kriskog** [comment]
Right, I just tried and it seems you cannot pen rename pills, patches or reagent containers. That leaves medical sprays (assuming that PR gets merged), which allows for renaming and potentially breaking this. Still though, I can't see it ever becoming an issue.

It was worth exploring regardless, thanks.

**Comment by PKPenguin321** [comment]
Easy fix, just check both type and name. If same type *and* same name then stack, otherwise don't

**Comment by ExcessiveUseOfCobblestone** [comment]
Is the issue that someone might hide a naughty item behind other items via renaming?

**Comment by kriskog** [comment]
I'm not sure there is an issue. The bags are whitelisted, so you can't just put anything in.

**Comment by Tlaltecuhtli** [comment]
what about stuff with different descriptions like shells

**Comment by kriskog** [comment]
Shells?

This change affects trash bags, mining satchels, plant bags, sheet snatchers, trays, bio bags and chem bags.

**Review by Cyberboss — DISMISSED** [review]

**Review by Cyberboss — CHANGES_REQUESTED** [review]
The others are right, use type AND name

**Comment by ExcessiveUseOfCobblestone** [comment]
`"[I.name]-[I.type]"` lol

**Comment by ExcessiveUseOfCobblestone** [comment]
```DM
if(.["[I.name]-[I.type]"])
    .["[I.name]-[I.type]"] = new /datum/numbered_display(I, 1)
    //blah blah blah
```

**Comment by kriskog** [comment]
Right, just make it a string. Yeah, that works, pushing in a bit.

**Comment by kriskog** [comment]
FUCK

**Comment by kriskog** [comment]
Okay, crisis averted. I did a dumb, so this got some new tags..

**Comment by ExcessiveUseOfCobblestone** [comment]
lol

**Pull request merged**
