### PR TITLE
Apc change

### PR DESCRIPTION
**Pull request by TheSilverNuke**
## About The Pull Request

Moves the AI chamber APC's inside the windoor area of the sat.

2020-04-17 03_43_27-Space Station 13
2020-04-17 03_45_22-Space Station 13

I had actually fucked up twice with getting this PR done when using the tools. I (hopefully) learned from my mistakes and should have everything good to go this time.

## Why It's Good For The Game

AI can be eliminated so easily by ventcrawlers bum rushing the AI APC. 2-3 hits on the APC within a couple of seconds is enough to take it out. This should make the AI a little more resilient without actually doing anything to hamper the crew if they need to break down the AI's doors.

## Changelog
:cl:
tweak: moved AI APC's inside the windoor areas
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
It still looks like you didn't run map merger.

**Comment by TheSilverNuke** [comment]
SCREE!!

**Comment by zxaber** [comment]
You _can_ reopen PRs you yourself closed, y'know.

**Comment by TheSilverNuke** [comment]
Decided to keep the newscaster even though it's rarely used.

2020-04-25 15_56_31-Halaal Lab 88
2020-04-25 15_58_42-Religious Haram Construct Foxtrot

Also the diff bot is still broken somehow despite me running the merger

**Comment by itseasytosee** [comment]
image
Rip newscaster

**Comment by TheSilverNuke** [comment]
It's still there, just moved. I'm not sure why the diff bot is freaking out tbh.

**Comment by TheSilverNuke** [comment]
yey

**Pull request merged**
