### PR TITLE
Emotes by default will not be heard through walls

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
Added a var to emotes for ignoring walls when playing their sound, now only the scream emote can ignore walls.
## Why It's Good For The Game
It's really annoying and stupid that you can hear people crying through walls and doesn't make sense at all.
## Changelog
:cl: grungussuss
sound: only the scream emote can be heard through walls
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Maybe you should just change that closed turfs decrease sound volume a bit more comparing to the open turfs, but it'll be kinda conplicated I think

**Comment by Sadboysuss** [comment]
> Maybe you should just change that closed turfs decrease sound volume a bit more comparing to the open turfs, but it'll be kinda conplicated I think

someone should do that, that sounds like a cool idea...

**Comment by alien3301** [comment]
Why leave out scream tho? I don't think the manual scream makes sound so it's mosly just flavour for surgery and wounds.

**Comment by Sadboysuss** [comment]
> Why leave out scream tho? I don't think the manual scream makes sound so it's mosly just flavour for surgery and wounds.

That's exactly why it still pierces walls, imagine getting hurt so bad - you scream in agony over it, it would be loud enough to hear through the hull. Since it's only code-callable, you can't abuse it.

**Comment by LSommers** [comment]
If this code existed prior, we'd never have had the legendary Terry Dorm Four Incident, and I think that proves it's a bad idea- or at least that *slap should also wallpierce.

**Comment by Sadboysuss** [comment]
at least that *slap should also wallpierce.

slap is an abstract item, not an emote. but now that I think about it slap shouldn't wallpierce either 😈

**Pull request merged**
