### PR TITLE
deletes our psd folder

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

deletes our psd_files folder, which contained mostly really outdated icons
moves one useful thing from it, the grille template into structurespawners.dmi

## Why It's Good For The Game

this is extremely outdated and nobody uses it
this folder made someone think stamps should look like they used to 10 years ago (unreadable)
fuck adobe

### CODE REVIEW

**Comment by magatsuchi** [comment]
desouling

**Review by Imaginos16 — APPROVED** [review]
So based... So fvking zased...

**Comment by Iamgoofball** [comment]
move these to the sprite repo

**Comment by SuperNovaa41** [comment]
i agree with goof

**Pull request merged**
