### PR TITLE
Little Treats Tea Room Bar Sign

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Another bar sign has hit the codebase
Dalm made this I'm just PRing it for her
dreamseeker_lFMsAMbwFa
v2r3cVdYoT

## Why It's Good For The Game

Lets you advertise a vibe not currently available

## Changelog

:cl: Dalm
image: A tea room sign for the bar
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
A picture of george bush as he is informed about the planes hitting the twin towers, the image is captioned "sir a 9th bar sign PR has hit the repo"

**Comment by dalmationer** [comment]
another step in my secret plan to make ss13 british

**Review by Wallemations — CHANGES_REQUESTED** [review]
Not sure how I feel about how drastic that emissive animation is
I like the idea of it flickering but it flickering _that much_ makes it extremely difficult to read
Maybe tone it down a bit? Make it not shrink as much? That might work

**Comment by timothymtorres** [comment]
I'm loving the emissive animation.  None of the other bar signs have this kind of unique effect and it looks really cool.

**Comment by Jacquerel** [comment]
@Wallemations still too much?
dreamseeker_bXnEhSuHcC

**Review by Wallemations — APPROVED** [review]
Better

**Pull request merged**
