### PR TITLE
Stops carpotoxin from removing temporal scars.

### PR DESCRIPTION
**Pull request by rasepretep**
## About The Pull Request
Hopefully simply removes the feature of carpotoxin where it deletes temporal scars.

## Why It's Good For The Game
We already have a "Clear Slots" button in the character setup window that lets you delete temporal scars for the given character. This is just meant to prevent accidental scar removals so people don't lose them by, for example, accidentally drinking a spiked drink, or taking a pill of Rezadone if it has some carpotoxin impurities in it.

## Changelog
:cl:
code: removed the piece of code that causes carpotoxin to qdel temporal scars (hopefully I identified it correctly)
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I thought this was a feature???

**Comment by RaveRadbury** [comment]
This is an intended feature, it's meant to be like botox.

I'd like to see a method of removing scars IC, but in a way that lets you pick the scars rather than just losing them at random.

@Ryll-Ryll what do you think?

**Comment by rasepretep** [comment]
It's a feature yes, but as it is right now it's just way too easy to get all your scars removed by accident and I don't think it should be. Removing the feature entirely, because it can be done OOC by clicking was my first idea. If someone wants to code in a new method that requires surgery to remove scars, that's probably be best.

**Comment by Ryll-Ryll** [comment]
Yeah carpotoxin reagent just straight removing all your scars no matter the dosage is wack. I really should add a better way to remove scars voluntarily, which I hope to soon, but this is good in the meantime

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
