### PR TITLE
Botany+Medical bounties, tweaks

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
add: Added botanical and medical bounties as well as a static adamantine bar bounty.
tweak: Increased the syndicate document bounty's reward from 10.000 to 15.000 credits.
tweak: Removed the gondola hide bounty and in return, increased the export value to the old level.
tweak: The briefcase bounty now also accepts secure briefcases.
fix: The action figure bounty now correctly spawns as an assistant type bounty.
/:cl:

I added a bunch of bounties:
- Botanical: These ask for between 5 and 10 plants, with the reward depending on the mutation tier/rarity. Cannabis rewards a little extra hush money.
- Medical: Organ bounties, half of which were moved from the assistant category. Some accept cybernetic organs, while others require you to take organs from dead/living crewmembers.
- Added a static bounty for adamantine bars, something for Xenobio to work towards if they're not busy fiddling with gold slimes.

Tweaks etc:
- Increased the syndie document bounty to 15.000 credits. Right now, you can pretty much only get those from the lavaland mining base - the reward seemed too small consindering the danger.
- Removed the gondola bounty - the gondola asteroid doesn't spawn most times, resulting in an uncompletable bounty just sitting around. Instead, I increased the gondola hide export price.
- Briefcase bounty didn't accept secure briefcases, it now does.

### CODE REVIEW

**Comment by Bombpants** [comment]
Can you just keep selling cannibus like ores. Or is there a specific bounty for it.

**Comment by 81Denton** [comment]
There is a cannabis bounty, but you can also sell plant seeds still.

**Comment by Mickyan** [comment]
bounties for specific blood types could be interesting

**Comment by 81Denton** [comment]
Good idea, let me try to figure out how it works. I can probably just copy code from reagent bounties and blacklist blood packs.

**Comment by Tlaltecuhtli** [comment]
can you make special wines from  #38977 a bounty?

**Comment by 81Denton** [comment]
I'm too hungover to get into adding blood types, but I'll have a look at fruit wines heh

**Comment by Bombpants** [comment]
Could there be a power bounty of some sort for engineering? If there was some challenge system for each department, maybe it could unlock some advanced crates in cargo

**Comment by recurracy** [comment]
Would it be possible to add extra points based on whatever's in the plant, i.e. gaia with mannitol?

**Comment by Kagus** [comment]
> Could there be a power bounty of some sort for engineering? If there was some challenge system for each department, maybe it could unlock some advanced crates in cargo

He already did #39568, with things like requests for atmos gases and a live tesla energy ball. The absolute madman.

> Would it be possible to add extra points based on whatever's in the plant, i.e. gaia with mannitol?

I'm not sure how you'd go about doing this without requiring either a bunch of one-off snowflake spaghetti or a big fat restructuring. Either way, I don't really seee how it would be worth the effort and potential for fuckery. Like, that one singular example is probably easy enough to pull off, but implementing a *system* that follows those rules while still being somewhat comprehensive would be trickier.

Plus you could probably cheese it by just getting chemistry to inject things into the veggies after they're harvested or something.

**Pull request merged**
