### PR TITLE
fixes flametrowers not being buildiable in the autolathe

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: You can make flamethrowers in the lathe as was intended.
:cl:

### CODE REVIEW

**Comment by DaxDupont** [comment]
Wait flamethrowers are in the lathe?
That's dumb, it's supposed to be craftable.

**Comment by arsserpentarium** [comment]
Maybe Dax is right this time.

**Comment by Anonmare** [comment]
Wait a minute, a full flamer comes with a full plasma tank, effectively allowing you to *print plasma*.

I would **strongly** recommend altering this to either an empty tank or no tank, since being able to print plasma will make the steal plasma objective even more easier than it already is.

**Comment by DaedalusGame** [comment]
wrong, full flamer comes without tank, full/tank comes with tank

**Comment by Bawhoppen** [comment]
This actually did used to be a feature even though maybe it shouldn't have been

**Pull request merged**
