### PR TITLE
ODs and addictions threesholds now trigger on > instead of >=

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl: 
tweak: ODs and addiction threesholds get triggered on > instead of >=
/:cl:

there is no fun into making 29.75u kelotane pills

### CODE REVIEW

**Comment by optimumtact** [comment]
optional name here

**Comment by Vidiveni** [comment]
This would kill so many fun offensive gimmicks/mixes:
- 10u bath salts is piercing syringe
- 15u krokodil in ordinary syringe
- 20u modafinil in cryo syringe
-  20u crank + 20u meth in patches
Etc etc. 

I feel having the OD threshold be the actual OD point is more intuitive. And I kinda like making 9.9u pills.

**Comment by Tlaltecuhtli** [comment]
just use bluespace syringes

**Comment by Vidiveni** [comment]
Those require research and mining and I'll still have to micromanage 15.1u and 10.1u doses to get the effects I want without wasting syringe space. Just make 20-25u pills like always. It works fine. 

This also ruins the thirteen loko bluespace syringe OD which is 60u.

**Comment by necromanceranne** [comment]
I agree, weaponizing OD's kinda requires this to equal due to how the various syringes work (piercing is 10u by the way). The difference it makes for healing chems is basically too insignificant to really matter.

**Comment by nicbn** [comment]
Yet another one buffs the chemistry

**Comment by Tlaltecuhtli** [comment]
whole point of bs syringes is to od people, it is unlocked and miners deliver 90% of the rounds, there are others way to kill people with standard syringes also yeah cryo syringes for some reason hold 20u which is more than enough for most chem ODs and surprise surprise it costs 1000 research points to unlock clf3 the rnd wall and press a botton or just trade meth for research points

**Comment by Cyberboss** [comment]
Bad pr

**Pull request closed without merging**
