### PR TITLE
Adds a priority system for client.color effects

### PR DESCRIPTION
**Pull request by RemieRichards**
## Main:

Added a priority system for `client.color` effects, this allows us greater control over which `client.color` is displayed on screen, as opposed to Byond's default of "whichever was set in the var last" which isn't very useful for us.

simply define subtypes of `/datum/client_colour` with the `colour` and `priority` values changed, the higher `priority` is the more important that colour is treated as and the higher chance it'll be the one drawn on screen.
## Misc:
- Updated cursed hearts to use this system.

This is what I meant about not liking how @KorPhaeron did things in the backend NOT a lewd comment guys jeez.

### CODE REVIEW

**Comment by MrPerson** [comment]
>colour

Needing a system like this is exactly why the noir glasses were shelved. So let's go nuts, eh?

**Comment by optimumtact** [comment]
> This is what I meant about not liking how @KorPhaeron did things in the backend NOT a lewd comment guys jeez.

Suree :laughing:

**Comment by RemieRichards** [comment]
@optimumtact the worst thing about emojis coming from you is the fact that they're usually small, round and yellow faces so you can easily imagine it's actually /oranges/ doing the face ;_;

**Comment by Cheridan** [comment]
orangeportal

**Pull request merged**
