### PR TITLE
Abductor surgical tools resprite

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

Resprites the abductors tools to give them high tech, animated, hard light designs!

**I've ~~3~~ 4 designs I'm switching between, so I'll let the public (but mostly the spritetainers) decide which one to go with.
I'll keep it as a draft until I have a solid answer**
They are, in order, from left to right, top to bottom: Drill, Cautery, Hemostat, Retractor, Scalpel, Saw
The gyazo links are gifs of the animation.
We have:

- No ornamentation

https://gyazo.com/fcbcb94b528f743ab81f1be9b144622e
image

- Green and purple highlights

https://gyazo.com/f1a2fdd17588a7fb9808f83c086ca114
image

- Green, purple and yellow highlights

https://gyazo.com/f6dbbd14da1dde93665143bdbf60d161
image

**EDIT:**

Alright, here we go with a new set of sprites, two of which were very kindly made by Imaginos as a reference: 
**Do watch the gyazo links or open the .dmi files on  your own, as the cautery, drill and scalpel are animated!**

image
https://gyazo.com/8e57f49e78c2960e7642375fe8decb90

And in their home territory:
image
https://gyazo.com/8182ff123508b5275e1d484339359271

As shown in the static shots they are, in order, left to right top to bottom:
Retractor, Cautery, Drill, Hemostat, Scalpel, Saw

## Why It's Good For The Game

With this PR I set out to do three things:

1: Fulfill my cripping addiction to high-tech hard light designs

2: Make the abductors tools fit better with the rest of the abductor equipment, which is quite colorful in comparison to the old tools

3: Make the tools easier to distinguish and less samey between themselves. We've all been there, it's often hard to remember which is the scalpel and which is the cautery as a glance, this fixes that.

Overall, I think the tools needed something different than their original design which, while slick, wasn't very fancy.
This new look fits better (and looks cooler imo) with the rest of the abductor's aesthetics. 

## Changelog

:cl:
imageadd: Resprites all of the abductors surgical tools
/:cl:

### CODE REVIEW

**Comment by FernandoJ8** [comment]
God dammit I didn't open it as a draft **_AGAIN_**

**Comment by SpaceDragon00** [comment]
I'm personally having a hard time telling what each of the alien tools are analogous to. The hemostat and retractor seem to be swapped (The former is known for having narrower jaws while the latter has wider, curved jaws), and the scalpel reads more as a hacksaw than a scalpel. The cautery especially just looks like... nothing in particular. I think there's better ways to represent these in a strange way while still having them intuitively read as their original tools

**Comment by Nobelium-XVIII** [comment]
so much soul

**Comment by Livrah** [comment]
It misses Grey-Purple alien theme.

**Comment by FernandoJ8** [comment]
> It misses Grey-Purple alien theme.

I decided to abandon a bit of the purple in exchange for more green, as the handheld gadgets tend to use green in their highlights more than purple.
A bit is still present in the top of the handle though.

**Comment by Fikou** [comment]
do they vibrate?

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
While I appreciate an attempt at making these sprites more distinct from each other, I feel as though the colors and shading of the sprites themselves are a downgrade from their previous iteration. They feel bright, garish, and not very laser looking. I'm willing enough to help so look for Imaginos#2911 on the #spriting-svgs-general chat if you want to brainstorm a better version with me!

**Comment by EricZilla** [comment]
I think the first set looks best.
Would like to see just the green highlight on its own though

**Comment by VladinXXV** [comment]
I second the thoughts of Imaginos16 and SpaceDragon00. For me, these are harder to match up than the current sprites are, and they're far too flashy and colorful (the animations are quick and don't really help this). If I had to choose, I'd go with "No ornamentation," but frankly I think they would benefit from something different. I think looking towards the alien crowbar may provide a better example of hardlight for this.

**Comment by FernandoJ8** [comment]
> I second the thoughts of Imaginos16 and SpaceDragon00. For me, these are harder to match up than the current sprites are, and they're far too flashy and colorful (the animations are quick and don't really help this). If I had to choose, I'd go with "No ornamentation," but frankly I think they would benefit from something different. I think looking towards the alien crowbar may provide a better example of hardlight for this.

Yep, a new set of sprites is being worked on with Imaginos' feedback and very helpful examples. I'll post it as soon I've got the thing done.

**Comment by FernandoJ8** [comment]
New sprite set's up!

**Comment by VladinXXV** [comment]
Took me a minute to figure out which was which, but I could get used to these. Drill feels a little thick (especially since it's only ever used for dental implants) but it's probably fine since no one does dental implants anyway.  Cautery in particular is pretty interesting. (in a good way)

bottom line yeah sure i can get behind these

**Comment by FernandoJ8** [comment]
> Took me a minute to figure out which was which, but I could get used to these. Drill feels a little thick (especially since it's only ever used for dental implants) but it's probably fine since no one does dental implants anyway. Cautery in particular is pretty interesting. (in a good way)
> 
> bottom line yeah sure i can get behind these

I'm aware that the drill is too thick but it's a compromise I had to make. Making it any thinner I could not for the life of me find a way to make it seem like it was a drill and not just a differently shaped scalpel

**Comment by VladinXXV** [comment]
Yeah fair enough, i can't think of a particularly better way to do it m'self.

**Review by Krysonism — CHANGES_REQUESTED** [review]
I'm sad to say I prefer the old ones.

The old ones are subtle and elegant, these are a little too on the nose.

Let's see what Twaticus thinks.

**Review by Twaticus — APPROVED** [review]
i like them. they can always be tweaked again in the future if need be

**Pull request merged**
