### PR TITLE
Clown Ops

### PR DESCRIPTION
**Pull request by Cruix**
Addresses #36418

clownops

### CODE REVIEW

**Comment by Metroidlover** [comment]
Dear god

**Comment by Plapatin** [comment]
steal the bananium sword sprite from ftl13 pls

**Comment by YakumoChen** [comment]
port /vg/'s banana peel swords and bananarangs

**Comment by MimicFaux** [comment]
Honk!

**Comment by Militaires** [comment]
i assume they have the cosmohonk hardsuit i added on their ship by default

**Comment by CPTANT** [comment]
bombana's really need to be worms style cluster bombs.

**Comment by Wilchenx** [comment]
@Plapatin ftl13 is a downstream of TG

where do you think the bananium sword came from?

**Comment by PKPenguin321** [comment]
We need an April fools branch reee

**Comment by Cruix** [comment]
@Wilchenx where do <I>you</I> think the bananium sword came from?

@Militaires The only different thing about the map is the bananium nuke, so no cosmohonks. They would not even be able to use it if they had it, because they are not given the assigned role of "Clown".

**Review by WJohn — APPROVED** [review]

**Pull request merged**
