### PR TITLE
Adds skirts to security

### PR DESCRIPTION
**Pull request by GuppyLaxx**
:cl: Ausops
add: Added security skirts.
/:cl:

sprite made by Ausops
image

why : Because skirts, and space lesbians, or whatever. Also harold said they would punch anyone wearing them so.

### CODE REVIEW

**Comment by alexkar598** [comment]
what is the purple pixel doing there?

**Comment by GuppyLaxx** [comment]
Dunno what's that from, 100% sure it isn't the skirt though

**Comment by nervere** [comment]
It makes no sense to have skirts for members of security. Security is a well-trained force that guards the crew, at least in theory. No self-respecting security force would have an option for skirts or any other needless fashion options.

It goes without saying that /tg/station is not a fashion show. This content is both unnecessary and will be, without a doubt, used as yet another means of borderline ERP, just like cat ears and the maid outfit are.

**Comment by Ausops** [comment]
its a pixel for positioning sprites on a grid

**Comment by Ausops** [comment]
you meant that sec will always have something to be self-respecting of, uniform traditionalists will never cease to be the dullest github commenters in the history of pull requests.

Each negative comment following the PR and thumbs down from erp virgins as they bikeshed over assorted cosmetic changes has been indistinguishable from the others. Aside from the gloomy typos, their posts’ only consistency has been its lack of excitement and ineffective use of actual arguments, all to make ss13 unattractive, to make roleplaying seem hopeless.

Perhaps the die was cast when you vetoed the idea of fashion PRs being necessary; such content made sure the game would never be mistaken for a work of volunteers that meant for it to just be a simulator of gas moles, just ridiculously autistic fusion simulation for future nerfing. The secskirt PR series might be pro-ERP (or not), but it’s certainly the anti-security sort of post in its refusal of dressing up fun and snowflakes to make sec fun. No one wants to face that fact. Now, thankfully, they no longer have to.

>a-at least the other options weren't needless though

"No!"

This post is drea.dful; the implications are terrible. As I read, I noticed that every time a github poster downvoted fashion PRs, the poster wrote unintelligibly about "muh slippery slope"

I began marking on the back of an envelope every time that phrase was referenced. I stopped only after I had marked the envelope several dozen times. I was incredulous. Your mind is so governed by irrational fear of two people idling in a dorm and genuine quality roleplaying that you have no other style of writing. Later I read a boring, rote comment of fashion PRs by seemingly the same author. He wrote something to the effect of, "If these gamers are wearing sec skirts and cat ears and maid outfits, then when they get more jaded they will go on to play on Citadel." And he was quite right. He was not being ironic. When you wear such items you are, in fact, being trained to play on Citadel.

**Comment by Tlaltecuhtli** [comment]
wrong repo go to [citadel](https://github.com/HippieStation/HippieStation)

**Review by Tlaltecuhtli — CHANGES_REQUESTED** [review]
delet

**Comment by 81Denton** [comment]
hey buddy you got the wrong repo, citadel club's two sectors down

**Comment by Alexch2** [comment]
@nervere unarmored caps, bandanas, berets, jackets etc

**Comment by KorPhaeron** [comment]
can_adjust = FALSE

Or else people will turn it invisible trying to roll up sleeves

**Comment by Armhulen** [comment]
"No"

**Comment by Cyberboss** [comment]
@Ausops wins, I'm merging dis

**Review by Cyberboss — DISMISSED** [review]

**Comment by Qbopper** [comment]
smdh this was gonna be my pr

**Review by Cyberboss — CHANGES_REQUESTED** [review]

**Comment by MrDoomBringer** [comment]
image
^from the last time this was pr was closed

**Comment by Keekenox** [comment]
I hate this simply because you beat me to making them. I wanted to sprite these REEE.

**Comment by RogueSteampunker** [comment]
Looks nice, seems like it shouldn't offend anyone, and anyone who does get offense from it that isn't just funny memeing is yet another slippery slope conspiracist, afraid anything that isn't a buff, nerf, or abusable feature is trying to shove erp into their greytide.

In other words, if this or missed the cit repo two blocks down, a fair few of the posters missed Hippiestation on the other side of town.

**Comment by F-OS** [comment]
downvote fetish content
do not reply to fetish content posters
report fetish content

**Comment by Mickyan** [comment]
If seeing a skirt immediately makes you think ERP frankly I think you might need to get out more, the sprite looks good and is reasonably designed

>No self-respecting security force would have an option for skirts or any other needless fashion options.

This is objectively wrong and there's many countries that use/allow skirts in military/police uniforms, especially in formal occasions

**Comment by davethwave** [comment]
Perhaps include this in the formal sec uniforms crate?

**Comment by GuppyLaxx** [comment]
i wanted to keep it pretty limited, original idea was one in the locker, and you could get more with coins out of the sec vending machine
or something like that

**Comment by Shadowflame909** [comment]
I don't know if there's a line or where it is. But, I'm fine with this as long as ERP memes stay dead.

**Comment by nicbn** [comment]
haaaaaaa no

**Comment by cyclowns** [comment]
i dont personally care but "because i want it or whatever" isn't a good reason to add something that's already inherently controversial. not that i can see any reasons that people would want this added other than "it looks okay who cares" and "owo nyaa~"

@pubby 
the more i think about this the more i realize that you're right

**Comment by OmegaShoots** [comment]
I don't see how there's any way that this should be added.

Realisticly, a skirt can't provide armor
A skirt isn't a combat uniform

And from a gameplay/rp perspective, if you want to wear shitty erp costumes and sit in dorms tuggin someone else's willy, you shouldn't be playing security, pick assistant and go raid the maid costumes
:-1:

**Comment by pigeonsk** [comment]
>Realisticly, a skirt can't provide armor
A skirt isn't a combat uniform

Pedicabo ego vos et irrumabo

**Comment by GuppyLaxx** [comment]
the bot got mad at me over a one line change of wether or not you can adjust the skirt that the pr merges with or without

**Comment by RogueSteampunker** [comment]
@OmegaShoots  Realistically, a station in space shouldn't be able to be attacked by space wizards that can end in you with a fucking touch of their dick, two different types of cultists who are actually justified, and the fact that human beings can act like everything's fine when they're missing all their limbs and their tongue.

playing the realism card doesn't work. What DOES work is asking whether or not a simple skirt fits in the universe we have set up, which I'd say it does.

Oh, and let's not forget "And from a gameplay/rp perspective, if you want to wear shitty erp costumes and sit in dorms tuggin someone else's willy, you shouldn't be playing security, pick assistant and go raid the maid costumes"

Newsflash, kiddo: Not everyone who doesn't wear default uniforms wants to erp. Some of us just find things that matter besides trying to call anything that isn't a gameplay feature erp, and screaming about how sec ruined your greytide brigade.

**Comment by newfren** [comment]
This doesn't make sprites turn sideways please remove it that is the only gameplay that matters

**Comment by KorPhaeron** [comment]
OP doesnt know how to use git and blamed the bot for his PR not working instead of asking how to fix it so someone else should probably remake this

**Comment by GuppyLaxx** [comment]
Well shit, sorry I'm not mr le code nicest man to sit here staring at something that enjoys being uninformative apart from screaming that something is conflicting in icons after one line change.
Oh well, there goes 5 minutes of copy pasting

**Pull request closed without merging**
