### PR TITLE
Ointments and bruise packs stacking

### PR DESCRIPTION
**Pull request by CandyClownTG**
Ointments and bruise packs are now in stacks of 6 instead of 5.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

did you adjust it for gauze too?

**Comment by CandyClownTG** [comment]
Yes, I did.

**Comment by PKPenguin321** [comment]
:+1: now you can heal all 6 areas of your body with only one stack

**Comment by Cheridan** [comment]
power creep :^)

**Pull request merged**
