### PR TITLE
Fixes #8375

### LINKED ISSUE #8375: Preference savefiles are broken.
At least on Basil. Probably : https://github.com/tgstation/-tg-station/pull/8328

### PR DESCRIPTION
**Pull request by theOperand**
UNTESTED I DONT KNOW WHAT IS GOING ON AAAAAAA

AAAAAAAA

### CODE REVIEW

**Comment by Miauw62** [comment]
@tgstation/commit-access AAAAAA

**Comment by RemieRichards** [comment]
Uh @Miauw62 
https://github.com/tgstation/-tg-station/issues/8375#issuecomment-81869577

**Comment by Miauw62** [comment]
I don't know.
It probably won't with the things I included now?
I have no fucking idea.

**Comment by RemieRichards** [comment]
That should do it, from the little knowledge I retain of savefiles, that fixes it safely.
Now we only lose our chat toggles instead of our entire character slots + antag prefs.

**Comment by Miauw62** [comment]
your chat toggles were dead the moment my PR was merged.
RIP in pepperoni
(now merge this PR)

**Comment by RemieRichards** [comment]
@Miauw62 NVM, my old memory was corrected (read Carn's ancient comments on savefiles)
This should be fine.

**Pull request merged**
