### PR TITLE
Neural Override Implant

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request
I received suggestions about letting you implant brains into people to let them take over, so here's my interpretation of the idea.

The Neural Override Implant is an implant, researchable via techweb in the Advanced Implants node. An MMI or posibrain can be inserted into it; once that's done, the implant can be implanted into the victim.

When implanted, the overrider (the player inside the implant) can, at will, take over control of the victim's body, with no limitation. Overriding only ends if the implant is disrupted by an EMP (which will put the override on cooldown), if the overrider disconnects (no being stuck in an afk body), or if the body dies. And, of course, if the implant is removed.

## Why It's Good For The Game

More cruel and unusual punishments inflictable by surgery, the hallmark of a civilized society.

## Changelog
:cl: XDTM
add: Added the Neural Override Implant. It can be loaded with an MMI or positronic brain and implanted into a victim to let it take control of the victim's body at will.
/:cl:

### CODE REVIEW

**Comment by Archanial** [comment]
That's basically cloning.

**Comment by XDTM** [comment]
if you're planning to put someone's brain in another's body you can just do that without the implant

**Comment by AdamElTablawy** [comment]
What possible nonantag use could this have?

**Comment by Donpedrito** [comment]
Does this work with positronic brains?

**Comment by XDTM** [comment]
It covers more or less the same range of uses that a chem implant has, so for nonantags the ideal use is probably keeping a prisoner/known antag under control.

It doesn't work with positronic brains right now, since posibrains aren't real brains and i'd have to code a separate system to use them.

**Comment by GravitronBlue** [comment]
Might want to see that #43591 gets fixed or else there's possibly going to be people taking over changelings.

**Comment by XDTM** [comment]
to be honest i suspect that split personality might cause some switcheroos, but i can't test with more than two players to check

**Comment by Archanial** [comment]
Funny idea would be to make traitor version of that implant that would "copy" your brain and activate after your death, giving you controll of that person and effectively second chance.

**Comment by ArcaneDefence** [comment]
The only way I could see myself using this is as an antag, forcibly making one player torture another player, with neither of them consenting to it.

**Comment by Ratvar** [comment]
Implant friends into people on conversion antag rounds, duh

**Comment by ATH1909** [comment]
This reminds me of https://en.wikipedia.org/wiki/The_Assignment_(Star_Trek:_Deep_Space_Nine) a lot, and I think that's a good thing (if you haven't watched this episode yet, go do that; it's a good one).

Can this be used to assume control of the body of a changeling?

Have you considered changing what needs to be inserted into this implant from "a brain" to "an MMI", so that we can use posibrains with this?

**Comment by ATH1909** [comment]
Actually, come to think of it, I think that this reminds me more of a certain character from Season 2 of Westworld (I'd say their name, but it doesn't look like github has spoiler tags) than it does of that DS9 episode.

**Comment by HomocidlePancakes** [comment]
Um, I dumb and I don’t get it. Is it a split-personality, but the second personality can take over the body on demand?

**Comment by Tlaltecuhtli** [comment]
> The only way I could see myself using this is as an antag, forcibly making one player torture another player, with neither of them consenting to it.

implant a officer brain into known antang and let him be free

**Comment by XDTM** [comment]
@HomocidlePancakes yeah, pretty much

@ATH1909 i forgot posibrains are MMIs, i might actually switch over to those. As for controlling changelings, it should be possible, i don't see a direct way they could counter it.

**Comment by Victor239** [comment]
I'd like to see it work with posibrains, and with that open "seed" PR for posibrains leave a message like [Need neural implant oversight for a known criminal]. That way they know what they're getting into when they accept the ghost role and will feel motivated to take it seriously and stop these people committing further crimes.

**Comment by XDTM** [comment]
Switching to MMIs was surprisingly easy, so i went and did it. Now you can also use posibrains as a result of this.

**Comment by HomocidlePancakes** [comment]
Ok, here is my issue with this. Unless you are in control it’s stupidly boring and because of that, why should you ever not be in control? I can’t imagine anyone baby-sitting a traitor on parole for god knows how long, staring motionless into their monitor, waiting for them to be a bad boy. This thing sucks.

**Comment by XDTM** [comment]
There's people who play pAIs, possessed blades, and imaginary friends, which have a similar level of interactivity with no chance of controlling anyone. This playstyle won't suit you, but some might like it.

**Comment by HomocidlePancakes** [comment]
It’s not comparable to them. You can still interact with other players as pAI/blade/friend. And this? You just never give up control, forcing the other player to ghost. It’s just a fancy brain transplant that allows you to become a ling.

**Comment by XDTM** [comment]
This has literally the _same exact level_ of interaction of imaginary friend, minus the walking around.

**Comment by Dennok** [comment]
Or sword that can only say.

**Comment by HomocidlePancakes** [comment]
Here’s what you’ve said on it’s intended use

> It covers more or less the same range of uses that a chem implant has, so for nonantags the ideal use is probably keeping a prisoner/known antag under control.

Here’s me saying why it won’t work.

> Ok, here is my issue with this. Unless you are in control it’s stupidly boring and because of that, why should you ever not be in control? I can’t imagine anyone baby-sitting a traitor on parole for god knows how long, staring motionless into their monitor, waiting for them to be a bad boy. This PR sucks.

Here’s you giving me an answer

> There's people who play pAIs, possessed blades, and imaginary friends, which have a similar level of interactivity with no chance of controlling anyone. This playstyle won't suit you, but some might like it.

Here’s a translation of that statement

> I guess you just hate social interaction and thus hate my PR

It does NOT have the same level of interaction as they RP roles you’ve mentioned. It will not be used to parol traitors, or used to RP the same way pAIs are, or used for any reason at all aside from becoming a ling.

If you give permanent control, then the second guy will never give up control, making it no different from regular murder. If you make the control temporary, then it kinda defeats the whole purpose of the implant. This PR is flawed at it’s core and I don’t see a compromise tbh.

**Comment by XDTM** [comment]
If you want to put a brain in control of another body, you can just replace the old brain with the new one and apply defib, without needing to research and print a specialized implant. (You don't steal ling powers since they're mind-based)

This only works if you think of it as an RP role. If your idea of playing as an overrider is to keep control 100% of the time, then yes,
> I guess you just hate social interaction and thus hate my PR.

I'm not meaning it as an insult, i _know_ not everyone likes to play this kind of role, but what i'm trying to say is that there are people who do, and they're the only ones who have a reason to use this implant, since there's an easier alternative if you just want to take over a body.

That said, i coud be staggeringly wrong and players will indeed always use the implant 24/7. If that happens i'll change it into a temporary control with a cooldown, but i want to believe that we can trust players a little bit with this, since such limitations would likely ruin the affidability of the implant (one could wait for the cooldown then just find a source of emp or a surgeon and remove it with no trouble)

**Comment by HomocidlePancakes** [comment]
Since there is no reason to give up control, people will use it 24/7. Like, the amount of commit you need for this thing completely locks you out of doing anything else other than control. Would be much batter if you could control remotely from some sort of a machine instead.

**Comment by trollbreeder** [comment]
Thou doth protest too much, methinks.
Maybe it works better in practice than on paper. Maybe the majority of the playerbase aren't perfectly efficient robots that powergame to the max. Maybe someone does like being the leash on a criminal.

**Comment by Jack7D1** [comment]
I suggest this be gated by illegal tech

**Comment by XDTM** [comment]
I don't think there's need for that, it requires a sacrificial player to do the job and antags are unlikely to have one at hand _and_ also not have another, easier, conversion method.

**Comment by ExcessiveUseOfCobblestone** [comment]
very odd feature, is there something that forces the implanted brain to play nice?

talking sword but the spirit can possess the user indefinitely until someone EMPs him, but the user was a bad guy so no one will want to EMP them???

I would prefer you just borg me so I can choose to be the talking sword or whatever rather than sit in an organic gbj for the rest of the round hoping "my" body gets EMP'd.

Not sure how posibrains can work with this considering it bypasses the inability to put posibrains into humans for control.

**Comment by Ratvar** [comment]
I really do not like letting **posibrains** be used. Printing new crewmembers who will validhunt in lately antag/humanmonkey body would be extremely bad. There is a reason you cannot use posibrains as normal brains.

**Comment by XDTM** [comment]
Honestly the idea of a rev with a backup pal in case they get deconverted sounds awesome to me, and elaborate enough that i doubt we'd see it used often enough to get stale. 

As for posibrain implanting, it's kind of a hard decision, since posibrains will probably be the primary source of brains when used by the crew. Maybe restricting implantation to only sentient people would do the trick.

**Comment by Pumpkinoe** [comment]
i think this would work better if it was operated through a **console** instead where you could control someone using a computer instead of having someone have to sit back and wait for a very long time for anything to happen

**Comment by XDTM** [comment]
It would be good, but it's very prone to bugs from consciousness transfer

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm still confused as to how this is on par with talking sword or say imaginary friend when I don't think either can semi-permanently force you to "switch" (they can't even speak so it's literally worse than your role) so they can play and you have no say in the matter until you get by one of the more rarer mechanics in the game (EMP). Better hope your MMI likes to validhunt so antags will use EMP because sec sure as hell isn't going to want to EMP someone btfoing a known antag.

Prob gonna close this.

**Comment by XDTM** [comment]
The idea seems to have flaws at its core, by now i'm not that convinced about it either.

**Pull request closed without merging**
