### PR TITLE
Adds the trash bag of holding icon to the janicart

### PR DESCRIPTION
**Pull request by alxmra**
## About The Pull Request

Until now, both the regular trash bag and the trash bag of holding would show the same icon when placed inside the janicart. This differentiates them visually, at last!

## Why It's Good For The Game

With this, everyone will see the janitor that carries a bluespace trashbag on their janicart as a national hero.

image
Typical janitor

## Changelog

:cl:
add: Adds the trash bag of holding icon to the janicart
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
image

did you test this

**Comment by JenqaDev** [comment]
i did(as shown in the picture), i have no idea why is that happening

**Comment by JenqaDev** [comment]
i figured it out

**Comment by JenqaDev** [comment]
making a new one as i forgot a key step in PR-ing
skill issue

**Pull request closed without merging**
