### PR TITLE
Paperwork 2077

### PR DESCRIPTION
**Pull request by Dawnseer**
## About The Pull Request
This PR adds a new arm implant to the game, that is a toolset implant, but for paperwork.
image
It gives you a fountain pen, clipboard, universal recorder,  zippo lighter, laser pointer, and a granted and denied stamp.
This should give the paperwork enthusiasts almost everything they need, except for say, a folder, four color pen and whatnot.

Now, like the other toolset implants, I figured it'd be nice if it unlocked a new tool if emagged, but I definitely did not want the same as them. A knife? I can't use that for paperwork. So instead when emagged, the paperwork implant unlocks a chameleon stamp. I went with a chameleon stamp because I wanted this to be a more covert thing, and it fits right in line with it being a paperwork implant.
image

As for method of acquiring this new implant, I decided to go with adding it as a cargo crate. Cargo still feels like it lacks for things for crew to buy, and this being a niche implant unlike the other toolsets, felt like it'd fit in here. I gave it half the price of the strongarm implant, because well, it's an implant for paperwork.
image

## Why It's Good For The Game
Adds a nice little doodad for a part of the game that admittedly not many partake in. But I think it'd be cool for HoPs, detectives, lawyers, cargo techs and whatnot to have a little something extra to work with.
## Changelog
:cl:
add: Unleashed a great evil upon hoplines, in the form of a paperwork implant.
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
bros this is huge

**Comment by Loafin34** [comment]
what about the energy dagger?

**Comment by Dawnseer** [comment]
I considered it, and many other options for the emag functionality, but I prefer the stamp. Also the energy dagger is better thrown, and you can't throw it from your implant.

**Comment by ju45he** [comment]
What if the emagged pen could fake signatures like that one pen on SS14?

**Comment by Dawnseer** [comment]
Certainly sounds better for the covert nature that I want the emagged functionality to have, and I might make an attempt at trying to make that happen around the same time that I try to make the implant able to print paper slips

**Comment by Dawnseer** [comment]
Oh no, now I have to find more issues on my skill level to fix...

**Pull request merged**
