### PR TITLE
Zombie claws do +1 damage

### PR DESCRIPTION
**Pull request by Robustin**
The door deflection threshold was apparently raised to 21 from 20.

Zombie claws do 20.

The one thing I absolutely never wanted was for zombies to go back to the (sprint speed, instant conversion) days where they could be stopped by one of the most common objects on the station, an airlock.

So now they do 21.

### CODE REVIEW

**Comment by Armhulen** [comment]
makes sense

**Comment by kevinz000** [comment]
come on they already get insane regen but whatever fine bleh doors

**Comment by Armhulen** [comment]
yeah it's like bullshit but they need this

**Comment by Robustin** [comment]
Isn't the regen still +4? 

Ive only seen a couple zombie rounds since I changed it but they seem reasonable to fight - but just like zombies are better in groups, players need to group against zombies. 

If we had a system to disable regen for X seconds after taking damage I would support it though.

**Comment by YakumoChen** [comment]
zombies shouldn't be something that requires 5 people to kill, especially when that means any single one of them bleeding out means they'll just make it worse.

**Comment by MrROBUST** [comment]
Tank zombies are cool. You just not robust enough. Pickup fuel tank, laser gun, fire axe or captain saber (or anything good for limbs dismemberment). Push tank to Z (they are slow) and fire it with laser. Explosion and burning will crit it, that give you much time to cut his head off.

**Comment by jughu** [comment]
Zombies outheal burning talking from experience where i killed the rd in a plasma fire

**Comment by jughu** [comment]
And why the fuck zombies get regen because they were a joke cause they could be stunned? Making them unstunnable removed that joke adding regen is overkilking it

**Comment by AnturK** [comment]
If they're meant to always damage doors, having it explicit in code would be better.

**Review by Cyberboss — DISMISSED** [review]

**Comment by Repukan** [comment]
The point of zombies is working on a team to take them down, or run.

It's on you if you take it one on one and die.

**Comment by jughu** [comment]
repukan. 5 PEOPLE it took to fight me at once YET THEY DIDNT GET ME DOWN

**Comment by Repukan** [comment]
Tell em to get good

**Comment by jughu** [comment]
THEY TRIED EVERYTHING THEY COULD I JUST OUTHEALED IT TO FAST

**Comment by Bawhoppen** [comment]
Don't they get to pry them open just like xenos?

**Comment by Poojawa** [comment]
Because a hand can sheer through a solid steel door.

Makes sense.

**Comment by BeeSting12** [comment]
@jughu ive soloed zombies its not that hard you just need to fire till theyre dead and behead.

**Comment by jughu** [comment]
5 people to take down a single zombie beesting.

**Comment by MrROBUST** [comment]
I saw how 2 people was dominated by single npc monkey. So do not judge about power level compared to some weaks.

**Comment by Robustin** [comment]
Again, the heal is 4/tick. Max healing virus is 3/tick. 

Zombies are still exceedingly rare (the only time I see them is when my Syndiecrate drops Romerol) and if there is a consensus about them being too strong I would support a function where their regeneration is disabled when taking damage. 

But having the ability to open doors isn't really something I'm going to debate. 

They used to be able to pry (I coded that) but after Coiax made them "human" and we added destructable machinery, it was changed to just rely on damage.

**Comment by jughu** [comment]
Their idds can open doors fuk off

**Comment by ExcessiveUseOfCobblestone** [comment]
you should instead give their claws the prying function again instead of buffing their damage output when the only reason is to explicitly open doors.

**Comment by YakumoChen** [comment]
@Robustin healing viruses don't make you stun immune. Every tick a zombie heals is another tick it has to damage someone trying to kill it, and it can outheal being on fire and any other environmental danger

**Pull request merged**
