### PR TITLE
TguiPrettierTarget now uses the '--write' parameter outside of CI

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
TguiEslintTarget already does this with the '--fix' parameter. I don't know why we shouldn't do the same with prettier, especially if you're building without an editor because you're probably a bit lazy and just want to click the tgui-build bat. ~~now replace "you're" with "I'm"~~

## Why It's Good For The Game
See above.

No CL.

### CODE REVIEW

**Comment by optimumtact** [comment]
What does this actually do?

**Comment by Ghommie** [comment]
It rewrites lines of tgui code that don't comply with the coding style so that they do. The style options are basically priettier default, with the exception of the `singleQuote` option which is set to `true`. An example would be:

```tsx
  const { text, toggle, list[], tooltip, var_one, var_two, var_three, var_whatever} = props;
```
Being rewritten in this form:
```tsx
  const {
    text,
    toggle,
    list[],
    tooltip,
    var_one,
    var_two,
    var_three,
    var_whatever,
  } = props;
```

We don't use the '--verbose' (or whatever it's called, mental fog) parameter when execuring Prettier, so it throws a simple warning that the file not complying with the style and urges you to fix it when 99.9% of the times you can just execute the '--write' param, and the other 0.1% slap a prettier-ignore comment above the accursed line.

Rewriting doesn't happen during CI checks, it can be run on VSC thanks to extensions or settings. This PR extends that function to the tgui-build bat outside of CI.

**Comment by optimumtact** [comment]
i would suggest you do your utmost to run this by MSO because based on historical precdent he will probably be against it.

**Comment by Ghommie** [comment]
Drafting because the other maints would rather have this as a new .bat

**Pull request closed without merging**
