### PR TITLE
resprites most tanks

### PR DESCRIPTION
**Pull request by CoiledLamb**
## About The Pull Request
i resprited a bunch of various tanks to have nicer shading using imaginos' base
you can see the before and after for each tank here:
image
(now includes plasmatank)
## Why It's Good For The Game
the previous tank sprites held up for a while, but they have dark grey outlines and their shading has become a bit dated, so it's nice to freshen them up. this brings them closer to some of the nicer sprites in the game, while preserving their shape, as the bases for them were quite good.
## Changelog

:cl:
image: updated most tank sprites. 
/:cl:

### CODE REVIEW

**Comment by CoiledLamb** [comment]
also nobody asked but i expanded the green bits in case someone wanted to add a pressure meter there like so
it was part of the original intent for these but it turns out the functionality is not in the game at all oops hehe
image

**Review by Wallemations — APPROVED** [review]
Big fan

**Comment by MTandi** [comment]
The plasma tank arrow looks like cross, holy plasma.

**Comment by TheVekter** [comment]
These are fine but the shading on the plasma tank looks off. It looks way too lit from multiple angles and you can't make out the arrow on it.

**Comment by CoiledLamb** [comment]
> These are fine but the shading on the plasma tank looks off. It looks way too lit from multiple angles and you can't make out the arrow on it.

i can tweak the arrow some but honestly i don't have a huge amount of ideas left for the plasmatank, if someone wants to tweak the version in the PR i'll toss em the file. i'm not totally happy with it either but i also don't feel like messing around with it for much longer

**Comment by Ticklezcat** [comment]
Mostly looks nice, just brighter/more highlit versions of the old sprites, although I see two potential issues.
One is that the double yellow tank thing (forgor what it's called) is much harder to make out without the shading between the two, also its' green light gauge wasn't originally parallel to the tank like the rest, so changing it to match doesn't quiet look right, both it and it's singular tank counterpart also lost the line/seam on the white band (just a nitpick)
Second is that the Plasma tank now looks like butter instead of safety orange, and as others have already pointed out the arrow on it is a bit mangled.

**Comment by optimumtact** [comment]
> Big fan

no they resprited tanks

**Comment by potato1234x** [comment]
plasma tank looks too desaturated imo

**Comment by MrDoomBringer** [comment]
simply delicious

**Pull request merged**
