### PR TITLE
Halloween Tweaks

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Halloween now lasts Oct 28th to November 2nd. I think a couple more days of being able to spawn as halloween races would be enjoyed by players.

The Halloween main event no longer edits your race to zombie/skeleton (players get to pick from setup now)

Halloween events (clown spam, meteors, eyeballs) have been axed. Having the outside of the station swarmed with hostile mobs every round makes modes like nuke a pain, and double pumpkin meteor waves trashing everything made for 20 minute shuttle calls.

Normal meteor waves will automatically become meteor waves on Halloween because I know people love the giant death pumpkins.

### CODE REVIEW

**Comment by sawrge** [comment]
kor you're fat

**Comment by sawrge** [comment]
and you're ugly too

**Comment by sawrge** [comment]
sorry i didnt mean either of those things you are a very handsome young man

**Comment by sawrge** [comment]
not gay

**Comment by DoctoreMad** [comment]
>Dullahans still not merged
>Probably won't be by the time halloween ends, whether this PR passes or not

WAKE ME UP

**Comment by KorPhaeron** [comment]
@DoctoreMad They are merged

**Comment by DoctoreMad** [comment]
Well since you said that I passed my eyes and saw there was no 151+ comment PR despise the fact I had seen it about a hour ago.
Very well, I have woken up

**Comment by TechnoAlchemisto** [comment]
Lord Commander Phaeron(LOL just like 40k) -

You have yet again, knocked my socks off. You have mastered the code, you have mastered the players, and now you have mastered time itself. Every day that I spend in your shadow I think more and more, "are you a man, or a god?". 

A lesser being, would have simply extended the duration of halloween, the damn fool. But you... you knew. Like a hawk, swooping down on a poor ground squirrel(Gray) you tweaked the event weights. It's as if you saw the future itself, and cut the threads of destiny before they could come to fruition.  As I write this, my hands tremble, I think... I'm afraid of you? I've become to see you not as a friend, but as a deity who exists in the periphery of my experiences. I think to myself, have I become less? Or have you just become so. much. more. I fear this may be my last transmission for awhile, old friend. 


Kerblam,
TechnoAlchemist

**Comment by sawrge** [comment]
holy shit a ghost it really is halloween

**Pull request merged**
