### PR TITLE
Plasmemes can breathe easy with, NEW!! plasma sheet eating internals.

### PR DESCRIPTION
**Pull request by Unstagrav**
## About The Pull Request
PMM2
PMM3
PMM4
PMM5

## Why It's Good For The Game

 Sometimes folks visit me in atmos to fill up some poor saps plasmeme canister.  I don't play plasmamen, or even understand where they get these cans from in the first place.

 With this brand new spankin upgrade they can just cram a plasma sheet directly into their internals without having to interact with a canister OF MURDER AND PLASMA FLOODING MY ENTIRE ATMOS ROOM. 

*heavy breathing*.

side note: i dont know how to code and accidentally shoved tanks.dm in the front part, and deleted it.  thats why it shows a random upload/delete preceding the code change below.

:cl:
qol: made something easier to use
code: changed some code
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
[dont make me tap the sign.png]

**Comment by Mothblocks** [comment]
Feature freeze #62946

**Comment by Farquaar** [comment]
Personally, I think it would be better as a researchable item than a roundstart feature of the plasmeme tank.

**Comment by Pickle-Coding** [comment]
Just weld the plasma sheets if you want plasma gas.

**Comment by Mothblocks** [comment]
dreamseeker_2021-12-13T19-59-54
dreamseeker_2021-12-13T20-00-06

**Comment by EricZilla** [comment]
Sticking advanced plasma internals under advanced plasma would be pretty cool, just color it yellow like the extended capacity tanks, like in January though obviously

**Pull request closed without merging**
