### PR TITLE
Adds Captain's Private Shuttle

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Adds the very cool Captain's Private Shuttle for 50000 cash.
image

## Why It's Good For The Game

You know, sometimes when you are the captain, all the crew might die while you have tons of cash for some reason, this is the moment where you buy this shuttle and reign over it alone, comes with an equipped medbay!

## Changelog
:cl:
add: The Captain's Private Shuttle is now available for 50000 spacebux! Better steal from cargo fast, Captain!
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
This shuttle is just activating battle royale mode, don't lie.

**Comment by Fikou** [comment]
> This shuttle is just activating battle royale mode, don't lie.

i don know if you want to use 50000 moneys for battle royale do it

**Comment by necromanceranne** [comment]
if it has cap access only the only person making it out is the one with captain access, so at that point you might as well secure it for yourself and everyone else be damned.

**Comment by Fikou** [comment]
yeah well it is called the captains PRIVATE shuttle

**Comment by terranaut1** [comment]
i like this for hijack shuttle objectives.

**Comment by ATH1909** [comment]
jUSt REsT sO YoU cAn aLL FiT In

**Comment by HomocidlePancakes** [comment]
>using r-glass instead of plasma r-glass

**Comment by Fikou** [comment]
> using r-glass instead of plasma r-glass

the syndicate sleeper cost all the budget nt had for the shuttle

**Comment by Jimmius** [comment]
so I can no effort hijack AND fuck over cargo with one simple trick? hell yeah

**Comment by GunHog** [comment]
>When you thought the asteroid shuttle was grief due to it smashing escape and inviting miners to chew it apart....
>>When you also thought that the Bubblegum shuttle was Battle Royale + Grief
>>>When you thought that Oh Hi Daniel was a grief shuttle due to the small size and being made of wood...

Here comes the 50K credits 1x3 Captain only shuttle! Not only does it make everyone want to kill the Captain, it also basically sends everyone to pods only due to fact that greyscum are going to break the windows, all with the added bonus of burning up Cargo's budget! **I could not think of a better non-antag way to make everyone on the station go beserk!** It is freaking glorious.

**Comment by Barhandar** [comment]
One meth grenade will erase your entire hijack.

**Comment by Fikou** [comment]
ok im giving this thing some small fixes and by small i mean it doesnt dock properly haha

**Comment by Fikou** [comment]
ok so i gave it a redesign and also made it dock and fly correctly now its a beautiful shuttle

**Comment by MrFluffster** [comment]
This is worst than daniel

**Comment by Fikou** [comment]
> This is worse than daniel

daniel lets any scum in no matter their access level, this is only for the most prestigious person on station

**Comment by MrFluffster** [comment]
> daniel lets any scum in no matter their access level, this is only for the most prestigious person on station

You mean "the guy who's an assistant with all access". Because that's the only type of guy who's gonna buy it(besides hijack tators).

**Comment by Fikou** [comment]
> You mean "the guy who's an assistant with all access". Because that's the only type of guy who's gonna buy it(besides hijack tators).

i would buy it

**Comment by Shapsy** [comment]
The other meme shuttles are one thing since they're griffy but at least functional, but I'd be hard pressed to not issue a ban for someone buying this, so let's please not meme this issue into reality

**Comment by optimumtact** [comment]
I don't think meme shuttles are appropriate, but if you want to add a feature where the captain can buy a shuttle for them self that docks on the other side of the station knock yourself out.

**Comment by qbmax32** [comment]
> The other meme shuttles are one thing since they're griffy but at least functional, but I'd be hard pressed to not issue a ban for someone buying this, so let's please not meme this issue into reality

yeah but it would be funny

**Comment by kevinz000** [comment]
very cool

**Comment by Fikou** [comment]
### **_H_**

**Comment by Akrilla** [comment]
This is really really cool for hijack objectives, big +1

**Comment by Fikou** [comment]
@Akrilla it closed already

**Comment by Akrilla** [comment]
@Fikou Added an edit to my comment, can still see a place for it honestly.

**Pull request closed without merging**
