### PR TITLE
fixes triple latched toolboxes spawning too often than anticipated

### PR DESCRIPTION
**Pull request by Militaires**
WOOPS

missing commit was the problemo

### CODE REVIEW

**Comment by Cyberboss** [comment]
So instead of a 1% chance they have a 0.1% chance??

**Comment by Armhulen** [comment]
R A R E

**Comment by Militaires** [comment]
@cyberbos

Yes.

**Comment by Cyberboss** [comment]
Might as well remove it then, because that means it'll only be seen once every 1000 rounds

**Comment by Iamgoofball** [comment]
no

**Comment by Armhulen** [comment]
@Cyberboss there's more than one toolbox on the station and by golly they're supposed to be rare

**Comment by BeeSting12** [comment]
Not really, my understanding of it is that for each tool box on the station there's a chance it will be a triple latched one. There's lots of toolboxes and the chance of having one increases for each toolbox. Let's say there's fifty toolboxes- thats a .1% chance for each one which adds up.

**Comment by ExcessiveUseOfCobblestone** [comment]
@BeeSting12 it's 1% of 10% meaning it's 0.001% or 1 in every 1000 toolboxes [postmerge]

**Comment by Penguaro** [comment]
I've never even heard of this and given that it is becoming rarer means I'll likely never see it. What is a triple latched toolbox?

**Comment by Militaires** [comment]
this is per toolbox, they were spawning too much because it's not 0.1% each round it's 0.1% x number of toolboxes on station

**Comment by Cheridan** [comment]
ok

**Pull request merged**
