### PR TITLE
HEY PLEASE REPORT FUCKED UP INHANDS. 

### LINKED ISSUE #25438: Healing staff right hand east/west sprites are just copies of the left hand east/west sprites
Makes them appear in the wrong hand when facing east/west while holding them in your right hand

### PR DESCRIPTION
**Pull request by Supermichael777**
Okay I'm thinking we should just do in-hands all in one go. If you see a missing in-hand side or a fucked up/ in-hand please report it so I can lazily flip and/or copy paste it

:cl:
fix: Several in-hands have been corrected
/:cl:

Fixes: #25438

### CODE REVIEW

**Comment by Jalleo** [comment]
There is a missing one for the meteor gun last I knew

**Comment by Supermichael777** [comment]
oh thanks

**Comment by Bawhoppen** [comment]
Isn't the meteor gun missing an actual icon_state anyways

**Comment by Supermichael777** [comment]
yeah that's a bit beyond my capability

because i hate myself I'm going to look at every in-hand for errors

**Comment by Supermichael777** [comment]
oh god merge conflicts

**Comment by Nabski89** [comment]
The envy knife doesn't have an inhand?

**Comment by Supermichael777** [comment]
if someone makes one i can put it in

**Comment by AnturK** [comment]
Conflicts

**Comment by optimumtact** [comment]
conflicts

**Comment by Tacolizard** [comment]
conflicts

**Comment by Cyberboss** [comment]
Conflicts

**Pull request closed without merging**
