### PR TITLE
Adds in iron/dark and iron/white half tiles in Tau Ceti's style.

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
• Adds in the tiles composed of two quarter pieces and a half pieces for the iron/dark and iron/white tiles.
• Adds in new turf_decal corners for these tiles, and all other tiles that have half pieces.
• Adds in new turf_decal corners for the tiles that are one quarter piece and a three-quarter piece.

## Why It's Good For The Game
More freedom for mappers to make more diverse-looking rooms and to give them more color and shape.
Instead of being limited to:
image
You now have:
image
And the respective corner piece of:
image

As of yet this is not a player-facing change hence no CL.
I have to go to work. I **think** it's ready so I'm putting this up for feedback.

## Credit
Although these aren't ported, obviously, the ideas here inspired by what I've been able to do with similar tiles ported from Tau Ceti on a downstream. They had the corner pieces, but with colors already applied instead of using turf_decals. This is the same deal, but turf_decals instead.
Full credit to Tau Ceti for the inspiration and stuff.

### CODE REVIEW

**Comment by KathrinBailey** [comment]
Alright, so.
Example use case:
image
Meta Botany. Yeah this doesn't look great and I personally wouldn't use it here, just a demonstration.

image
Meta arrivals seccie checkpoint. Again, just a demonstration.

image
A square, I guess.

image
Demonstration of the new corners that cover, well. Not corners and... the other type of corner?

I'm scratching the bottom of the barrel with these screenshots. I assure you there's plenty of stuff to do with it.

Also, back from work and my nap so this is now tested and ready. 👍 
I talked about this on Discord with @EOBGames
https://discord.com/channels/326822144233439242/782914977874837515/850843628062375966
(also some screenshots of how it can be utilized here)

**Comment by CRITAWAKETS** [comment]
you have no idea how much i needed this

**Comment by Fikou** [comment]
image
why are the edges here so harsh?

**Comment by KathrinBailey** [comment]
https://discord.com/channels/326822144233439242/326849939240124419/851889545775284274
image
image
probably should've posted it here instead of on the discord
not sure what to change to prevent harsh edges. First image is TG's half iron half dark tile, second image is my half iron half dark edge version.

**Comment by Twaticus** [comment]
discussed with maptainer, not too interested in these sorry

**Pull request closed without merging**
