### PR TITLE
[DNM] Include __FILE__:__LINE__ with every log

### PR DESCRIPTION
**Pull request by Mothblocks**
Might assist in investigating a current issue.

### CODE REVIEW

**Comment by Mothblocks** [comment]
@MrStonedOne Has this helped any? I don't want to leave it test merged for too many rounds since it doesn't interface well with any existing log scraping software

**Comment by optimumtact** [comment]
I think we should keep it forever

**Comment by Mothblocks** [comment]
@optimumtact If you're serious (which is reasonable) Zephyr is working on JSON logs right now and we could have it be included there very easily

**Comment by MrStonedOne** [comment]
it should be removed from everything already, i'll double check

**Comment by optimumtact** [comment]
> @optimumtact If you're serious (which is reasonable) Zephyr is working on JSON logs right now and we could have it be included there very easily

I don't see why not

**Comment by Mothblocks** [comment]
Going to close this for now then

**Pull request closed without merging**
