### PR TITLE
Fixed spelling of possession, Separate, and Cemetery

### PR DESCRIPTION
**Pull request by Dr-Pope**
Updated posession to possession

## About The Pull Request
Just fixes some spelling for gangs. I also fixed misspellings for "posession" to "possession". Fixed "seperate " to "Separate" Fixed "Cemetary" to "Cemetery"

## Why It's Good For The Game
Bad spelling makes me sad 

## Changelog

:cl: Doctor Pope
spellcheck: fixed a few typos
/:cl:

### CODE REVIEW

**Comment by Dr-Pope** [comment]
**Updated Themes.dm**

**Comment by LemonInTheDark** [comment]
I'll be honest, I thought you failed to properly resolve a merge conflict because of all the tags and requests

**Review by tralezab — APPROVED** [review]
looks good dog

**Pull request merged**
