### PR TITLE
Removes the flash from sec's starting equipment

### PR DESCRIPTION
**Pull request by DATA-xPUNGED**
## About The Pull Request

Security won't spawn with a flash in their pocket anymore
## Why It's Good For The Game

I always found it annoying to get to security to get the equipment and have to get rid of that flash somehow, as the belt already comes with one. This PR should save several minutes of your average sec main.
## Changelog
:cl:
qol: Security will no longer spawn with a redundant flash anymore.
/:cl:

### CODE REVIEW

**Comment by iwishforducks** [comment]
the flash is a useful roundstart item since if you're joining a station you at least have some kind of close quarters protection. if anything the belt should probably have its flash removed

**Comment by DATA-xPUNGED** [comment]
> the flash is a useful roundstart item since if you're joining a station you at least have some kind of close quarters protection. if anything the belt should probably have its flash removed

I don't think situations like that are common at all, and removing it from the sec belt instead might be unintuitive for new players

**Comment by Vect0r2** [comment]
Also, how does it take "minutes" to pop the flash into your locker?

**Comment by Pumpkinoe** [comment]
wouldn't the real solution be to remove the flash from the belt instead?

**Comment by DATA-xPUNGED** [comment]
> Also, how does it take "minutes" to pop the flash into your locker?

I meant the time adding up over a sec main's life

**Comment by thgvr** [comment]
Can't join with baton
Can't join with flash
What's next

**Comment by Pumpkinoe** [comment]
> Can't join with baton Can't join with flash What's next

can't join with character

**Comment by githubuser4141** [comment]
> > Also, how does it take "minutes" to pop the flash into your locker?
> 
> I meant the time adding up over a sec main's life

It takes less then a second to grab it, them Q to drop it takes on the floor. This is super annoying for players who aren't you and prefer having two flashes because it'd much easier to dispose of one then it is to find another

**Comment by BlueMemesauce** [comment]
Remove the evidence bag

**Pull request closed without merging**
