### PR TITLE
Makes round-end credits configurable

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
tweak: Round-end credits can now be toggled on or off in the server game options.
/:cl:

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
TRUE FALSE defines, and invert the logic. Make setting it disable the credits

**Comment by Tacolizard** [comment]
Why this change?

**Comment by kevinz000** [comment]
why bother if they dont want it they can just comment a single line in ticker to disable.

**Comment by lzimann** [comment]
Because that is not feasible to do in downstreams, not so easy to edit a file like ticker without being in conflict hell.

**Review by Cyberboss — APPROVED** [review]

**Comment by Tacolizard** [comment]
what is the point of this?

**Comment by Tacolizard** [comment]
We worked on this code, we deserve credit. It's frankly disrespectful to disable the credits. It's not like you're forced to read them. A GOOD change would be allowing downstreams to add more credits based off contributers from their repo.

**Comment by Tacolizard** [comment]
We work on this code for free. Is it really that much to ask to let some credits roll?

**Comment by JJRcop** [comment]
@Tacolizard this code is AGPL, anyone can do anything with it as long as that thing is also open source, giving more freedom to downstreams is pursuing the spirit of the license.

It may sound strange for me to say "giving more freedom" in a 'libre' codebase, but between modifying the code and a config option, modifying the code has way higher maintenance upkeep if they want to keep up to date, so forcing them to modify the code is more restrictive.

**Comment by Cyberboss** [comment]
The tool to generate the credits for their repo is here https://github.com/tgstation/tgstation/tree/master/tools/CreditsTool so if people want the correct credits for their repo they can make em

**Comment by Tacolizard** [comment]
@JJRcop linux uses a similar license, GPLv2, and they have https://github.com/torvalds/linux/blob/master/CREDITS

if a downstream is significantly different to warrant the removal of credits, they shouldn't have any reason to care about conflicts with master.

**Comment by Tacolizard** [comment]
Also I still don't understand. What was the motivation behind this change?

**Comment by lzimann** [comment]
it's not everyone that have a hard on when they name show up on round end

**Comment by tortellinitony** [comment]
I'm surprised only one person is crying about this

**Comment by Tacolizard** [comment]
@tortellinitony 😢 you have four downvotes

@lzimann I've never seen my name at roundend.

**Comment by Tacolizard** [comment]
@tortellinitony why did you make this PR

**Pull request merged**
