### PR TITLE
Removes mining drill power mechanic.

### PR DESCRIPTION
**Pull request by GunHog**
- Removes the power mechanic from mining drills and the sonic
  jackhammer.
- Fixes broken borg diamond drill upgrade.

EDIT: Removed mining drill from voucher choices due to it no longer being nerfed. (A quick trip to Science is recommended)
This is an alternate to https://github.com/tgstation/-tg-station/pull/9378.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
10/10 puts an end to "coderbus makes shitty changes and never reverts them".

Oh and also makes drills useful again

**Comment by RemieRichards** [comment]
@Dorsisdwarf coderbus didn't make this change, paprika did, lynch them :P

**Comment by AlexCrimson** [comment]
Might want to nerf the Sonic Jackhammer. Last time i used that thing it was pretty insane. The downside was that it had a low power charge.

**Comment by GunHog** [comment]
Technically, before the addition of the power mechanic, the diamond drill had all of the abilities and speed of what is now the Sonic Jackhammer. Essentially the jackhammer is now the diamond drill.

**Comment by Miauw62** [comment]
maaaaaaaaaaaaaaan
this is technically a feature, but i really dislike the power "mechanic" drills have right now.
@Cheridan

**Comment by phil235** [comment]
You also need to remove the standard drill from the list of tools available with the mining voucher, because without the power consumption it becomes the definitive choice for miners at roundstart.

**Comment by GunHog** [comment]
Alrighty, mining drill removed from voucher. Also corrected a little oversight in the recharger code.

**Comment by Cheridan** [comment]
This change is an alternative to a PR which fixes a bug ;) Therefore, this must be a bugfix PR.

**Comment by EchoFade** [comment]
@Cheridan 
Yes is bug fix, please merge!

**Comment by Kromgar** [comment]
Me love you long time Gunhog

**Comment by WJohn** [comment]
#9378 got merged so this is obsolete???

**Comment by GunHog** [comment]
No, WJohn, just conflicted.

**Comment by GunHog** [comment]
All conflicts gone!

**Comment by EchoFade** [comment]
HORRAY! thank you Phil for the merge!

**Pull request merged**
