### PR TITLE
Fixes a historical inaccuracy

### PR DESCRIPTION
**Pull request by Bawhoppen**

### CODE REVIEW

**Comment by Firecage** [comment]
While the damage makes sense(a bit to low though, 20 would probably be better), the description is way to bloated. Do we really need such bloated descriptions which will spam the chatbox instead of something short?

**Comment by Bawhoppen** [comment]
I'm trying to fix a culture here not make a good video game

**Comment by lzimann** [comment]
it's the new meme making huge descriptions

**Comment by Bawhoppen** [comment]
is that really what you guys are going to complain about

**Comment by Cheridan** [comment]
Katanas are thrice as sharp as European swords and thrice as hard for that matter too. Anything a longsword can cut through, a katana can cut through better. I’m pretty sure a katana could easily bisect a knight wearing full plate with a simple vertical slash.

**Comment by Bawhoppen** [comment]
nice fucking meme cheri you know thats not true yet you say it anyways

**Comment by Firecage** [comment]
@lzimann Honestly don't really care if its a meme or not. Since horribly big descriptions is bloody annoying, chatbox spammy, and an eyesore. And in this case, doesn't deliver any more info than the previous description, besides the fact that the previous one had the bonus of being funny.

**Comment by Cheridan** [comment]
I should know what I’m talking about. I myself commissioned a genuine katana in Japan for 2,400,000 Yen (that’s about $20,000) and have been practicing with it for almost 2 years now. I can even cut slabs of solid steel with my katana.

**Comment by lzimann** [comment]
and \>reducing force from 40 to 10, just fuck off ok thx

**Comment by Firecage** [comment]
Yah, force reduction is way to much. A more realistic reduction would be 20 force, or atleast 25.

**Comment by Bawhoppen** [comment]
my kitchen knife is better than a katana

**Comment by KorPhaeron** [comment]
stop erasing teegee culture

**Comment by Bawhoppen** [comment]
ITS INTERNET CULTURE IN GENERAL

**Comment by Firecage** [comment]
bawhoppen, Katana's were inferior to most other swords, but they weren't THAT bad.

**Comment by Bawhoppen** [comment]
thats why I made it as good as a toolbox

**Comment by GeneralGoose** [comment]
meme PeAr kouldnt melt nippon steel

**Pull request closed without merging**
