### PR TITLE
Fixes error sprite from pdas in exosuit storage slots

### PR DESCRIPTION
**Pull request by ArcaneDefence**
## About The Pull Request
It's just an icon state for pdas in exosuit storage slots

## Why It's Good For The Game
The icon state was missing, so it did the pink/black missing texture sprite

## Changelog
:cl:
fix: putting a PDA into an exosuit storage slot won't cause the missing texture sprite any more.
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
what is -2

**Comment by ArcaneDefence** [comment]
> 
> 
> what is -2

A mistake in pasting the image to add an icon state which got put at the end of the file for some reason

**Review by Twaticus — CHANGES_REQUESTED** [review]
missing directionals

**Comment by ArcaneDefence** [comment]
I just imagined it as pinning it onto a pocket on the front, but sure.

**Comment by Twaticus** [comment]
having 1 direction on a mob sprite like that will use it for all sides is all

**Pull request merged**
