### PR TITLE
Revert "Random mineral spawning (mostly) no longer change turfs"

### LINKED ISSUE #49367: Lavaland Tunnels do not spawn, resulting in no roundstart Fauna, Tendrils or most Megafauna
## Round ID: 
130257 among others

## Testmerges:
#49081: 'Fixes SM hell, makes some changes to how gas is handled in the SM' by LemonInTheDark at commit 81d30538f7
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
Play a round on Bagil, wait for roundstart, no tendrils, bubblegum, ashdrakes, or Collosus.
Blood Drunk and some other ruins still spawn, those that don't require tunnels.

Likely broken by something in the Lavaland Gulag changes.

### PR DESCRIPTION
**Pull request by tralezab**
Reverts tgstation/tgstation#49205

fixes #49367

probably should just be TESTMERGED until this can be fixed, it makes lavaland pretty wack atm as in almost unplayable and completely unfun

### CODE REVIEW

**Comment by tralezab** [comment]
if you're wondering why this has to happen, #49367

**Comment by Buggy123** [comment]
That's my bad there, I forgot to test cave spawning.

**Comment by trollbreeder** [comment]
lol why didn't we testmerge this i have no idea

**Comment by tralezab** [comment]
we don't testmerge refactors trollbreeder

**Comment by trollbreeder** [comment]
we probably should for a few hours before merge in the case of zany bugs happening, like #49367

**Comment by Buggy123** [comment]
#49372

**Comment by SpaceManiac** [comment]
> lol why didn't we testmerge this i have no idea

testmerges create work on the part of the admins with testmerge rights, so they're reserved for cases which *need* careful study on live servers with real players

for stuff like this it should have just been tested locally

**Comment by cacogen** [comment]
Why doesn't everyone test things locally before pushing?

**Comment by Dennok** [comment]
> Why doesn't everyone test things locally before pushing?

Sometimes coders just dont see side effects from refactors. It see the work only part what it focused now. 
As me before, on ChangeTurf inherit air refactors, that make shuttles lost air. I test hand construction, and make turf don't lose airmix or floor tile placing and removing. 
And in result it lost air on shuttle moving.

**Comment by cacogen** [comment]
yeah actually my refactored baton thing fucked a couple of things and i made sure to test it extensively

**Comment by tralezab** [comment]
mistakes happen

**Comment by Buggy123** [comment]
My main concern while finishing the PR was getting ore spreading working correctly, because it was being fucky and had been troubling me for a few hours. As soon as I got it done I figured it was complete, because the ore spreading was the only thing I really refactored and the turf spawning was basically the same, so the issue with caves snuck past me.

**Comment by tralezab** [comment]
okie doke

**Pull request closed without merging**
