### PR TITLE
Adds Mediborgs Amputation Adventure Board to Illegal Tech

### PR DESCRIPTION
**Pull request by XRandomXManX**
## About The Pull Request

I add Mediborgs Amputation Adventure Board to comp_board_designs.dm
I add Mediborgs Amputation Adventure Board to Illegal Technology in all_nodes.dm

## Why It's Good For The Game

I think this is an underused arcade game. I understand the rarity of it, but it doesn't do much for that amount of rarity anyways. I was also hoping this might inspire someone to make a special prize for emagging it too, now that that is a feasible thing to do.

## Changelog
:cl:
add: Added Mediborgs Amputation Adventure Board ID to all_nodes before actually making it.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
illegal tech should now require arcade games node

**Comment by Time-Green** [comment]
Mediborgs Amputation Adventure is a rare anomaly. By adding a reliable way to get it, you kinda ruin it being special

**Comment by PKPenguin321** [comment]
i kinda agree

**Comment by XRandomXManX** [comment]
I just thought that the game did very little for the amount of rarity it had, and that if it could be reliably obtained someone might do something cool like add a special prize for when you Emag it like the other two.

**Pull request closed without merging**
