### PR TITLE
Removes hugbox variants of the supermatter crystals. Replaces instances of them with real supermatter crystals.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
All hugbox variants of supermatter crystals are replaced with real ones. This includes the hyperfractal shuttle and the OSHA violator deathmatch map.
## Why It's Good For The Game
So people don't get disappointed.
## Changelog
:cl:
balance: The hugbox supermatter crystals in the hyperfractal shuttle and OSHA violator deathmach map are replaced with real ones.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Please provide a better justification for the change "makes this shuttle totally unuseable".

**Comment by SgtHunk** [comment]
wont this make the hyperfractal shuttle SM delam before it even arrives on station

**Comment by moocowswag** [comment]
This is bad for deathmatch because 1

its a fucking ghost minigame that is already controvercial due to speculation on its performance impact.

2 there is an easter egg on the map that involves hacking in and taking the sliver off of it to use as a weapon and if its sucking people in and moving atmos around its not gonna be possible anymore. (This is already a hard endeavor since you have to cross the entire map twice while people are fighting you.

**Comment by moocowswag** [comment]
> wont this make the hyperfractal shuttle SM delam before it even arrives on station

It will also turn the shuttle into a toasty fireball due to plasma generation.

**Comment by norsvenska** [comment]
april was two months ago

**Comment by Pickle-Coding** [comment]
> Please provide a better justification for the change "makes this shuttle totally unuseable".

I tried but I couldn't.

**Pull request closed without merging**
