### PR TITLE
Removes the "To Kill" wish option from the wishgranter

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

See the title.

## Why It's Good For The Game

This PR was made as an alternative to this PR: https://github.com/tgstation/tgstation/pull/47076

Personally, I don't like this change, but it's at least better than replacing the primary end reward of the second hardest away mission (that someone can _be sacrificed/sacrifice themselves_ for) with a mundane piece of paper with an Undertale reference on it.

## Changelog
:cl: ATHATH
del: Your wish that the wishgranter grants you can no longer be "To Kill".
/:cl:

### CODE REVIEW

**Comment by AnonymousNow** [comment]
Seems like a better solution.

**Review by lordpidey — CHANGES_REQUESTED** [review]
You also need to remove "To Kill" from the input list on line 91.

**Comment by YakiAttaki** [comment]
The "to kill" wish is literally the only wish I see anyone choose, ever. By removing it you're essentially removing the wishgranter's primary function of "free hijack".

**Comment by ATH1909** [comment]
> You also need to remove "To Kill" from the input list on line 91.

Thanks.

**Comment by ATH1909** [comment]
> The "to kill" wish is literally the only wish I see anyone choose, ever. By removing it you're essentially removing the wishgranter's primary function of "free hijack".

I've never seen anyone choose the "To Kill" wish; in my experience, the "Immortality" one is much better.

And hey, it at least preserves more of the wishgranter's primary function than just REPLACING IT WITH A PIECE OF FUCKING PAPER would.

**Comment by carlarctg** [comment]
ah yes leaving a undertale piece of paper is a far better alternative to butchering an item from the game entirely

**Comment by ATH1909** [comment]
> ah yes leaving a undertale piece of paper is a far better alternative to butchering an item from the game entirely

?

**Comment by PKPenguin321** [comment]
@ATH1909 the removal PR puts a sans undertale quote in place of the wish granter because it is a bad pr

**Comment by Fox-McCloud** [comment]
To be honest, if this is removed, there's not much point to the wishgranter being a ruin, let alone it being so insanely hard to access.

It'd probably be best just to alter what the wishgranter gives or put something else in the center that is suitably strong, but not round ending.

**Comment by Shadowflame909** [comment]
we have a shitload of unused admin items (and debug items) to replace it. Some of them I'm not even sure why they're unused.

Might I recommend someone being able to wish to be the universes best wrestler and getting the real wrestling championship belt?

Or wishing for the universes best vehicle and getting the speedwagon/speedbike

Maybe wishing to not be seen, and getting the shadowcloak. Rapidly depowers with every step, recharges in the darkness.

Tons of potential.

**Comment by 81Denton** [comment]
The wishgranter lavaland ruin has been disabled in config for ages because it's just free antag gated behind some bluespace crystals. For what it's worth, the whole thing could be put in the trash and nobody would notice outside of the away mission.

**Comment by Dawson1917** [comment]
this doesn't help that wishgranter is so easily cheeseable and a complete joke to get inside that it doesn't deserve to reward you. it's as bad without the free antag option as it is with it.

also i love pr duelling

**Comment by Shadowflame909** [comment]
Pretty sure this is about the gateway variant

**Comment by Dawson1917** [comment]
> 
> 
> Pretty sure this is about the gateway variant

gateway variant is also a joke, the gibbing leaves behind a head so cloning is ezpz and requires no sacrifice whatsoever. as cheeseable as the lavaland ruin.

**Comment by nemvar** [comment]
Fixes https://github.com/tgstation/tgstation/issues/46348

**Comment by Learner10** [comment]
So wait... was the only thing this wish even did was make you an antag, thus technically allowing you to kill? Other things exist that let you do the same and they're somewhat easier to acquire. Unless I'm missing some information on this, I think this wish seems pretty mundane compared to literal x-ray and laser eyes, immortality, or... hmm... does wealth just mean you get a box full of material?

**Comment by 81Denton** [comment]
>Other things exist that let you do the same and they're somewhat easier to acquire

Morph syringe aside, I can't think of any other item that turns you into an antag for zero effort

**Comment by Learner10** [comment]
There's also a trauma that can place you in situations for appropriate murder. But for some reason, I had thought that there were more things.

**Comment by Quartich** [comment]
> > Other things exist that let you do the same and they're somewhat easier to acquire
> 
> Morph syringe aside, I can't think of any other item that turns you into an antag for zero effort

@81Denton becoming a morph doesn't count for antag status iirc

**Comment by Shadowflame909** [comment]
@Quartich 

It's pretty funny that you say that. Considering Denton made a PR that specifically gives them antag datum/ Coded antag status

**Comment by 81Denton** [comment]
Yeah, morphs were always treated as antags by admins and I just added an antag datum to them to remove any confusion

**Comment by CRITAWAKETS** [comment]
There's also the dice of fate that can turn you into a wizard. That one is just rng.

**Comment by Shadowflame909** [comment]
blood contract turns someone into an antag permanently, but makes them red and very valid to everything, even fellow team-mates if a team-antag.

Bottle of mayhem turns you and everyone around you into a murderboning antag for 3 minutes, and you get three of them

**Comment by ninjanomnom** [comment]
The antag datum is a code convenience please don't interpret it to mean full antag status under the rules

**Comment by 81Denton** [comment]
This is decent enough until someone has the heart to put away missions and the lavaland wishgranter ruin out of their misery.

**Pull request merged**
