### PR TITLE
Fixes crafted foods not getting reagents from its contents

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Fixes crafted foods not gaining the reagents from the foods in their contents.

`CheckParts` sent `COMSIG_ATOM_CHECKPARTS` before it added the parts to the atom's `contents`. Meanwhile, in the edible component `OnCraft` relied on the `contents` list being filled out, meaning at the time it caught the signal, `contents` was empty and nothing happened.

Food now checks the passed `parts_list` instead of the `contents` to deal with this.

## Why It's Good For The Game

Botany can now poison the chef's food with drugs once again.

## Changelog
:cl: Melbert
fix: Crafted foods now inherit their component food's reagents again.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Since CheckParts empties the list passed in this signal after doing things to it, doesn't this significantly change behavior? 
Is there a better way of doing this?

**Comment by MrMelbert** [comment]
Valid point I missed, I've moved the signal before it empties the list which shouldn't change behavior.

**Comment by LemonInTheDark** [comment]
Tested?

**Comment by MrMelbert** [comment]
image

**Pull request merged**
