### PR TITLE
Octuples sniper range

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About The Pull Request
While testing out #63654 I was trying to shoot Pun-pun from Metastations port-aft solars and noticed that the sniper rounds were running out of steam about halfway through the chemistry lab. This is a disappointing amount of range for a weapon designed to be used at long distances. About on par with the carbine actually. This gives the sniper rifle bullets enough range to shoot something in one corner of the z-level from the opposite corner with range to spare.

Also, don't worry about the turrets. They were already overriding their range to be about 16.

This PR has #64015 baked into it so...
Closes #64015

## Why It's Good For The Game
The gun built for long ranges can now shoot things from far away.
You can now shoot where you click.

## Changelog

:cl:
balance: The sniper rifle can now shoot things from much further away.
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
This will be basically meaningless until this bug is fixed https://github.com/tgstation/tgstation/issues/62423

**Comment by TemporalOroboros** [comment]
I'll take a look, but I may have already fixed it.

**Comment by TemporalOroboros** [comment]
I appear to have fixed the large deviation, but have also introduced a bug where you can't actually shoot at specific pixels on the target. Easy fix.

**Comment by TemporalOroboros** [comment]
Projectile aiming is fixed. You will now fire precisely at whatever pixel you click on, ignoring deviation.

**Comment by SuperNovaa41** [comment]
nice! add it into your pr body

**Comment by optimumtact** [comment]
what is the justification for the buff?

**Comment by TemporalOroboros** [comment]
Mostly that it does not make intuitive sense that the sniper rifle, a weapon specifically designed to be used over long ranges, would have the same range as a SMG or shotgun. In terms of balance... I personally haven't ever seen the sniper rifle get used and belive it should be. This will help motivate that.

**Comment by optimumtact** [comment]
the range was reduced because it is extremely annoying to be killed by something from beyond your view range

this kind of gun does not work well in this viewpoint and engine setup

**Comment by Shadowflame909** [comment]
> Mostly that it does not make intuitive sense that the sniper rifle, a weapon specifically designed to be used over long ranges, would have the same range as a SMG or shotgun. In terms of balance... I personally haven't ever seen the sniper rifle get used and belive it should be. This will help motivate that.

how do you even get one, is it a nukie purchase?

Sniping the captain from the nukie ship!

**Comment by SuperNovaa41** [comment]
> how do you even get one, is it a nukie purchase?
> 

Only nukies can explicitly buy it, regular traitors can get it through the syndi-kits

**Comment by LemonInTheDark** [comment]
Would be good to not bundle the fix with a balance change, goes through smoother that way

**Comment by TemporalOroboros** [comment]
Probably. I'll split it up later.

**Comment by cacogen** [comment]
A range of over a z-level seems like overkill (just make it like the length of escape to central primary or something) but I don't see how it practically makes a difference unless nuke ops can get bullets that go through walls or something.

**Comment by TemporalOroboros** [comment]
> A range of over a z-level seems like overkill (just make it like the length of escape to central primary or something) but I don't see how it practically makes a difference unless nuke ops can get bullets that go through walls or something.

Penetrator rounds exist. Though they are expensive.

**Comment by BlueMemesauce** [comment]
> A range of over a z-level seems like overkill (just make it like the length of escape to central primary or something) but I don't see how it practically makes a difference unless nuke ops can get bullets that go through walls or something.

they can lol

**Comment by ilikesaying** [comment]
> the range was reduced because it is extremely annoying to be killed by something from beyond your view range

almost like being shot by a sniper

**Comment by optimumtact** [comment]
I know how a sniper rifle works, that still doesn't translate into it magically becoming a fun part of the game

**Comment by Bawhoppen** [comment]
Modscopes when?

**Comment by TemporalOroboros** [comment]
> Would be good to not bundle the fix with a balance change, goes through smoother that way

Done. The fix has been extracted into #64015 if you want to merge just the fix.

**Comment by TemporalOroboros** [comment]
The fix label should be removed from this, seeing as it was merged as a separate PR.

**Comment by timothymtorres** [comment]
> the range was reduced because it is extremely annoying to be killed by something from beyond your view range
> 
> this kind of gun does not work well in this viewpoint and engine setup

This was ironically the justification used to remove long range scopes from Human VS Human combat in Colonial Marines.  The playerbase hated getting 360 scoped halfway across the map without any counterplay.

**Comment by Ryll-Ryll** [comment]
Reduce the range of the penetrator ammo because otherwise that's going to be like a mini immovable rod, and I'll merge this

**Comment by TemporalOroboros** [comment]
> Reduce the range of the penetrator ammo because otherwise that's going to be like a mini immovable rod, and I'll merge this

How much?

**Comment by TemporalOroboros** [comment]
Can't debug on my machine because changing the PATH to include my python install somehow broke cmd and therefore build.bat. It's a single var change so if it compiles it shouldn't break anything.

**Comment by Shadowflame909** [comment]
> > the range was reduced because it is extremely annoying to be killed by something from beyond your view range
> > this kind of gun does not work well in this viewpoint and engine setup
> 
> This was ironically the justification used to remove long range scopes from Human VS Human combat in Colonial Marines. The playerbase hated getting 360 scoped halfway across the map without any counterplay.

I'd say nerf its damage/Make it 95% stamina

That way it works more as a shocking ranged slowdown that goes away, but will keep the same wowfactor as being sniped from across the station.

**Pull request merged**
