### PR TITLE
well that went pretty badly, time to stuff this idea in the "never try again" pile

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
add: How do you do fellow players? I added a new hip and trendy gamemode.
/:cl:

### CODE REVIEW

**Comment by DaedalusGame** [comment]
👍 this is jojo's bizarre gamemode
it won't work but that's secondary

**Comment by Buggy123** [comment]
I really like the idea of this but on a fundamental level every player having a holoparasite means that _there's half as many people in the station_. Unless its just a few people with holos, then it's fine.

**Comment by epochayur** [comment]
really it should be the first person to collect the gibs of Mr Christ wins

**Comment by Mark9013100** [comment]
**THIS MUST BE THE WORK OF AN ENEMY『STAND』...**

**Comment by Potato-Masher** [comment]
First ones to pull out their injectors gets their stands first. There aren't enough observers to go around.

**Comment by Shadowflame909** [comment]
>half the players on the station, whoever pulls out there injector wins

But what if, at roundstart you get chosen as a guardian, and someone else gets chosen as the welder? Like traitor lings, or blood brothers?

**Comment by Shadowflame909** [comment]
If this got merged would all jojo references be ic in ooc? 🤔

**Comment by Potato-Masher** [comment]
No, these are guardians/holoparasites. Totally different from stands. Not a single similarity.

**Comment by Durkel** [comment]
There's not enough observers for this game mode work. You'd be better off splitting this up so it will pick users/guardians at start instead of from the ghost pool.

**Comment by Buggy123** [comment]
Actually, now that I think about it this is a great gamemode because of that. Dying is more permanent because of all the stands, _BUT_ you're essentially guaranteed a reincarnation as someone else's holoparasite.

**Comment by Cyberboss** [comment]
This isn't a bad idea, but it doesn't deserve it's own game mode

**Comment by Iamgoofball** [comment]
i've been asking for a testmerge for like 2 days now but Arm is refusing to do any because of the election, doesn't want to influence the election w/ testmerges I think

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball he doesn't want a great PR like this to cuck him out of votes.

**Comment by Potato-Masher** [comment]
Honestly, it should be a mode like highlander that the admins can trigger on the fly.

**Comment by Potato-Masher** [comment]
@Iamgoofball You fool, apparently it's not in the gamemode list and does not have a button. An admin tried to start it and he was unable to.

**Comment by Doppeltongue** [comment]
Classic goofcode.

**Comment by Potato-Masher** [comment]
dreamseeker_2018-03-07_23-41-08

**Comment by Potato-Masher** [comment]
Also, holy shit, more people than I thought are giving this the 👎 .

Maybe it's because it's low effort (you can't deny this one goof).

**Comment by astralloop** [comment]
Wow, just wow. This gamemode is like cancer growing on cancer. It makes gangpocolypse look sane in comparison. As a player, I get an instant braindead guardian, and no attempt to reset it works. As a ghost, I get spammed with PONG PONG PONG and my ears raped. I'd rather have my balls impaled with a rusty meat cleaver than ever play this horrible excuse of a gamemode again. Goofball, I don't know what sort of drugs your on, but please just take sedatives instead, maybe you'd come up with a good idea then. Or maybe just make something as good as deep fryers and freon. But please, this mode makes you look like a BDSM addict!

**Comment by Buggy123** [comment]
r i p

**Comment by Therapist1** [comment]
yeah that was kinda shit. itd be better if there were like, 7 or 8 stand users as antags instead of literally everyone has a super deadly weapon they're not supposed to use

**Comment by Therapist1** [comment]
it's sorta like 'summon guns' the gamemode.

**Comment by ishitbyabullet** [comment]
15+ tickets in a round that lasted less than fifteen minutes.

holy shit

**Comment by Iamgoofball** [comment]
things 2 note:
stand code broke, we had more than 1 person per stand and it went badly
the never 4 this round button apparently also broke

**Comment by Buggy123** [comment]
Just give 5-10 people a holo and the rest a randomly picked martial art. Holos are antags that have to do something or other, everyone else isn't.

**Pull request closed without merging**
