### PR TITLE
[Metastation]Changes some stuff in medbay, And removes all static donk pocket spawners and replace them with random ones

### PR DESCRIPTION
**Pull request by improvedname**
Removes 2 medkits at medbay roundstart and 1 set of gauze/mesh/suture replaces the kiosk into the upper lobby and places the water dispenser/paper cups in the auctall lobby.
-
Removal on medical supplies is to cut down on the free medkits back to the orginal 1.

Removes all static donk pocket spawners replacing them with random ones now not only engineering will get the taste of sweet pizza pockets but also medbay/science/security!

## Changelog
:cl: Improvedname
del: Removed a couple medkits from medbay
tweak: Changed medbay a bit
tweak: Static donk-pocket spawners are replaced by flavour pocket ones
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
image
Did you use map merger? :thinking: 
https://tgstation13.org/wiki/Map_Merger

**Comment by carshalash** [comment]
Oh dear

**Comment by nemvar** [comment]
why no donkeys for the chef?

**Comment by improvedname** [comment]
@nemvar chef already gets them

**Pull request closed without merging**
