### PR TITLE
Buffs Oxygen Blob and Radblob

### PR DESCRIPTION
**Pull request by Iamgoofball**
It now does losebreath too

### CODE REVIEW

**Comment by JJRcop** [comment]
Unmentioned rad blob buff!

**Comment by Iamgoofball** [comment]
forgot about that, whoops

**Comment by GunHog** [comment]
BLUUUUUUUUUUUUUUUBS! Now only if RR can finish https://github.com/tgstation/-tg-station/pull/7607...

**Comment by kevinz000** [comment]
Nothing my virologist self-resp skills can't fix. VIRO STRONK

**Comment by Jordie0608** [comment]
Changelog

**Comment by stapler2025** [comment]
only if you don't miss, kevin

:3

**Pull request merged**
