### PR TITLE
canUseTopic now uses TRUE/FALSE instead of defines that just say TRUE

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

The most idiotic thing I've seen is canUseTopic's defines, they literally just define TRUE, you can use it however you want, it doesn't matter, it just means TRUE. You can mix and match the args and it will set that arg to true, despite the name.

It's so idiotic I decided to remove it, so now I can reclaim a little bit of my sanity.

I've also individually went around replacing args to specify what they're setting.

### Regex

I did this manually but you can use ``canUseTopic.+(BE_CLOSE|NO_DEXTERITY|NO_TK|FLOOR_OKAY)`` to not waste as much time as I had.

## Why It's Good For The Game

It doesn't affect the game, but just LOOK at it I hate this so much please let me kill it.

## Changelog

Nothing player facing.

### CODE REVIEW

**Comment by timothymtorres** [comment]
It's a better idea to use bitflags for this.  See [7ea51667a168ee034df47d9a0cef9ba8692f0ca2](https://github.com/timothymtorres/tgstation/commit/7ea51667a168ee034df47d9a0cef9ba8692f0ca2) since I was planning on doing the same thing since canUseTopic currently sucks to use and is poorly documented.

**Comment by JohnFulpWillard** [comment]
At the end of the day I don't think there'll have much of a difference if it's just one list with bitflags or all being individual args, I can do it but it would have to wait until I'm more motivated.

**Comment by timothymtorres** [comment]
After your PR gets merged I'd like to implement them as bitflags (I'll explain in the PR) and plan on adding new useful args for people to use.  (gravity checks, lighting checks, etc.)  Also I had documentation setup but I lost it since I didn't commit the changes before the library computer I was using reset itself.

**Comment by san7890** [comment]
Did you regex up the search-and-replace for this? Would be nice to put it in the PR Body for posterity if you did.

**Comment by JohnFulpWillard** [comment]
> Did you regex up the search-and-replace for this? Would be nice to put it in the PR Body for posterity if you did.

I didn't

**Pull request merged**
