### PR TITLE
Changing Coffee jittering to be an overdose effect.

### PR DESCRIPTION
**Pull request by phil235**
Because jittering after taking one gulp of coffee is silly.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1: example usage of modular overdose code in other parts of chemistry

**Comment by RandomMarine** [comment]
A threshold of 80 is awfully high, that's almost three whole coffees.

**Comment by Lumipharon** [comment]
Random do you just shaking like you're having an epileptic fit after 2 coffees? (or even three for that matter)

**Comment by RandomMarine** [comment]
Do you find yourself running slower after downing a glass of iced beer?

**Comment by Atskadan** [comment]
it should be used to show that someone drank a shitload of coffee anyway, not be a normal occurrence

**Comment by Lumipharon** [comment]
Also loads of other things cause jittering. Like 13 Loko.

**Pull request merged**
