### PR TITLE
Quick carry modules now give the correct bonus

### LINKED ISSUE #79470: MOD advanced quick carry module erroneously has no additional benefits
## Reproduction:

`/obj/item/mod/module/quick_carry` has the benefits that the advanced version is supposed to bestow due to a copy/paste error.

https://github.com/tgstation/tgstation/blob/0cfacbb71dce9f6c5845a2d4500c3addc9de3807/code/modules/mod/modules/modules_medical.dm#L84-L95

### PR DESCRIPTION
**Pull request by Momo8289**
## About The Pull Request
Fixes #79470
The quick carry module and its advanced version both gave the same buff after a copy/paste error. That ain't right.
## Why It's Good For The Game
Uuuuuhhhh oversight bad
## Changelog
:cl:
fix: MOD quick carry modules now give the correct carry speed bonus
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Despite linking the issue you didn't delete the duplicate definition of `/obj/item/mod/module/quick_carry/on_suit_activation` and `/obj/item/mod/module/quick_carry/on_suit_deactivation`

**Comment by Momo8289** [comment]
> Despite linking the issue you didn't delete the duplicate definition of `/obj/item/mod/module/quick_carry/on_suit_activation` and `/obj/item/mod/module/quick_carry/on_suit_deactivation`

Looked to be intentional. Both the standard and adcanced version apply the fastmed trait, but they both apply different quick carry traits.

**Comment by MrMelbert** [comment]
But that's not how that works, currently ONLY the weaker / normal version has `TRAIT_FASTMED`

**Comment by san7890** [comment]
image

regardless this really should just be folded into one proc anyways

**Comment by Momo8289** [comment]
oops

**Pull request merged**
