### PR TITLE
plasma cutters combat property nerf

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
balance: plasma cutters have a range of 2, it does the same dig range as before
/:cl:
before:
blobs die to ez to plasma cutters spam
its pretty much a 5 range better laser rifle infinitely printable
now:
it does the same range as before when used for digging rocks

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Needs an I DED.

Plasma cutters are weak as shit in a pressurised area.

**Comment by SgtxRootbeer** [comment]
It does kinetic dmg anyways. Doesn't blob have resistance for it?

**Comment by imsxz** [comment]
if you've ever played as a xeno or blob against plasma cutters you'd know how autistically strong they are and obnoxious to fight against. In low pressure, they out damage laser guns and have functionally infinite ammo (1 plasma sheet full recharges it, full charge with adv cutter gives like 100 shots). This, combined with the ability to mass produce them at cargo lathe with their insanely cheap research requirement and material cost, makes them absurd and outright gamebreaking against most lategame antagonists. The ability to easily supply each crew member with 2 infinite ammo laser guns during a blob or xeno outbreak is an incredibly silly feature to have in the game. Furthermore, plasma cutters are supposed to be a MINING tool, their current strength in combat is idiotic balance considering basic plasma cutters are already 500% better at mining than KA.

**Comment by Barhandar** [comment]
Consider: plasmacutters are perfectly balanced without this PR because they're borrowed directly from Dead Space where they're second best weapon in the game (first is autorifle).
>against most lategame antagonists

Then they shouldn't be lategame.

**Comment by FantasticFwoosh** [comment]
You can still hit at range if you skirt the plasma-bolt through rocks, KA is pretty standard anyway though.

**Comment by octareenroon91** [comment]
# u ded

What you're saying is that the blob takes on some risk when breaching the station, and xenos are more vulnerable in the vacuum of space?

_what a shame the **emergent gameplay** is getting in the way of your memes_

**Comment by XDTM** [comment]
Also a tool meant for mining should at best be comparable to an actual weapon (and only in its ideal conditions), not vastly superior; especially if it's much cheaper and easier to make.

**Comment by WarRage333** [comment]
The ''Whole'' station wont be using them on a blob because for them to be effective the area has to not have any pressure and there not enough hardsuits to go around.
And noone ever depressurizes areas to go murder people with the laser cutters at least not enough to be noticable

this is just an ''i ded playing bleb pr''

**Comment by GuyonBroadway** [comment]
It basically gives the crew a measure of action vs the current blob meta of "open to space to prevent crew without suits attacking me" which is now autisticly strong due to space damage being tripled.

Well now the few crew WITH suits get to use a stronger weapon. In future consider staying in a pressurised area to avoid this.

**Comment by XDTM** [comment]
I'd agree if they acted like easily printable laser guns, but they're apparently far better due to having a _lot_ of shots and an instant reload (each laser gun can shoot a bit, then you need to bring it to a recharger to reload for ~15 seconds, assuming you have a free recharger close by). Same damage, near zero downtime, _and_ far lower production cost, for a tool whose primary function is _not_ being a weapon, is definitely not balanced.

**Comment by ExcessiveUseOfCobblestone** [comment]
Plasma cutters are the dex build of mining, I'd rather have them reverted back to the infinite welder and have a larger capacity KA researchable instead.

**Comment by PKPenguin321** [comment]
>Consider: plasmacutters are perfectly balanced without this PR because they're borrowed directly from Dead Space where they're second best weapon in the game (first is autorifle).

okay, this is epic

**Comment by 81Denton** [comment]
>I'd rather have them reverted back to the infinite welder and have a larger capacity KA researchable instead

You'd need to balance a lot of lathe values for that since cutter mining (aside from bombs) is the only real way to mine lots of ore quickly.

**Comment by Whoneedspacee** [comment]
If plasma cutters were subjected to the same rules as kinetic accelerator charging it might not be so bad. Dual wielding them and shooting many every second is pretty strong. Also get rid of the chance to remove limbs.

**Comment by deathride58** [comment]
Plasma cutters are easy to counter as blob by either simply not depressurizing the area you're in, or rolling electromagnetic web. They're also easy to counter as a xeno by simply sticking to pressurized areas, or if you can manage to get your extraterrestrial claws on a couple of large/bluespace beakers with the necessary chems, using large EMPs. Atmospheric pressure and EMPs are the two biggest weaknesses of plasma cutters and all other mining weapons.

**Comment by Barhandar** [comment]
>I'd say: Tone down the plasma cutter, tone it way down from its hilarious versatility and power.

For example adding damage scaling from range in pressurized environment, so it only chops off limbs and deals significant damage almost point-blank (aforementioned 2 tiles of range), while still being just as potent in space and on lavaland (or remove the slowdown from dual-wield KAs).  
If the area is unpressurized, well, you shouldn't have done that and went against plasmacutter, also, station'll have _plenty_ of other ways of obliterating blob and xeno by then so better get rid of the sources.

**Comment by XDTM** [comment]
Wait, it can still chop limbs and deal significant damage in pressurized areas?

**Comment by Barhandar** [comment]
>Wait, it can still chop limbs and deal significant damage in pressurized areas?

Yes. It deals only a quarter of damage but _the dismemberment chance is the same_.

**Comment by XDTM** [comment]
I still don't know why it would make sense that a mass-printable mining tool can be vastly more effective than actual weapons, in limited supply, stored in a restricted location.

Either the condition should be more restrictive (strictly lavaland), the combat potency should be reducted (which makes sense since on the mining side it is _vastly_ betten than KAs), or it should be turned into a real weapon in cost, research and pin requirements; as well as reducing its mining capabilities.

A tool that is the ideal choice at both mining and combat while also being the cheapest option available is very far from any definition of balanced, although it looks like nobody wants to give up any of these.

**Comment by XDTM** [comment]
The intended purpose of the item matters too; making welders shoot like pulse rifles but only within 5 tiles of the SM is still OP, even if you can argue that you can avoid them by staying far from the SM or that welders aren't powerful outside of the SM range.

**Comment by Barhandar** [comment]
>I still don't know why it would make sense that a mass-printable mining tool can be vastly more effective than actual weapons

Because actual weapons are, comparatively, _weak_ (and also accessible much earlier). They can't break through vast swathes of rock, and rock's tad harder than flesh.

Of course, this is still a game. Yet this PR is still "i ded" because 1: station has way better weapons against blob and xenos, including ones that don't require pins, and 2: by the point you can print APCs you can also effectively print infinite-charge-and-higher-damage KAs due to miners having points in the scientific notation range.  
I maintain that if xenos or blob are in space, they deserve to get fucked sideways by anyone with plasmacutter.

**Comment by ExcessiveUseOfCobblestone** [comment]
You have to ignore the mining/science players so they can go through the first four stages of grief. Until then you're wasting your time lol.

**Comment by Barhandar** [comment]
@ExcessiveUseOfCobblestone speaking of that, is there a proc to see if someone's on designated mining z-level?

**Comment by ExcessiveUseOfCobblestone** [comment]
`if(z == 5)`?

**Comment by XDTM** [comment]
we have ztraits now, so we can check if someone's on lavaland even if the zlevel is different

**Comment by Barhandar** [comment]
I've checked the code and it's is_mining_level(z) because ZTRAITS LOL, but now I'm searching for a way to get said z because I bet there's a fucking helper proc for it instead of just user.z.

**Comment by XDTM** [comment]
pretty sure it's either user.z or get_turf(user) and then check the turf's z

**Comment by ExcessiveUseOfCobblestone** [comment]
why would there be a helper proc for just a variable lookup lol

**Comment by Barhandar** [comment]
Because there's a ton of these for just a variable lookup. Anyway, compiling alternate balance for plasmacutters.

**Pull request closed without merging**
