### PR TITLE
Better station ambience drone

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Steals baystation's ship ambience who stole it from eris. This is likely some shit they grabbed from somewhere uncredited, but it's not credited and sounds better than what we have so I'll give it the benefit of the doubt.

## Why It's Good For The Game

The current one we have isn't great.

## Changelog
:cl:
soundadd: new station ship ambience
/:cl:

### CODE REVIEW

**Comment by TheSilverNuke** [comment]
Can we get a preview of the sound file to hear it?

**Comment by actioninja** [comment]
https://github.com/tgstation/tgstation/blob/66a625e6df15eaa97e599248a2281c74238ce26e/sound/ambience/shipambience.ogg

**Comment by Akrilla** [comment]
sick

**Comment by OverlyGeneric** [comment]
on another note, have we credited myformerselves, creator of the sound, for the chapel ambiance sound?

it's clearly the intro of the "If You and I Were Friends" track from Gingiva's OST.

Link to Song: https://www.youtube.com/watch?v=4qzgc2Uu6FM

**Comment by PKPenguin321** [comment]
As long as we're porting Eris sounds, grab their spooky maint sounds please

**Comment by SpaceManiac** [comment]
> on another note, have we credited myformerselves, creator of the sound, for the chapel ambiance sound?

it can't be that hard to check and then correct this yourself

**Pull request merged**
