### PR TITLE
Makes .357 speedloaders unrecyclable.

### PR DESCRIPTION
**Pull request by Bucovineanu**
## About The Pull Request

Makes it so 4-TC worth 357 speedloaders don't get turned into a pile of useless iron

## Why It's Good For The Game

Frustration doesn't make for good gameplay

## Changelog
:cl:
add: Added one line that makes 357 speedloaders unrecyclable.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
What problem does this solve, just out of curiousity?

**Comment by Dawson1917** [comment]
> 
> 
> What problem does this solve, just out of curiousity?

If you hold a speedloader and click on a pile of .357 bullets it fills up the loader. Normally when you're printing .357 ammo from the autolathe. Accidentally clicking the lathe instead of your bullets would destroy your 4tc extra loader

**Comment by PKPenguin321** [comment]
A couple years ago I had to do this but for the revolver itself, wack

**Comment by itsadavid** [comment]
yeah but what if you just moved the bullets away from the lathe

**Pull request merged**
