### PR TITLE
[NO GBP] Fixes my many fucks ups in the RD PR.

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request
Fixes the coat being incorrectly togglable as a labcoat, and fixes handholes in the turtleneck.

## Why It's Good For The Game

guh
## Changelog
:cl: axietheaxolotl
fix: The RD coat is no longer incorrectly togglable, and lack of "fill-in" on turtleneck handholes.
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
owned, bozo.

**Comment by GuillaumePrata** [comment]
Making the RD labcoat into a jacket will make it desync from the base labcoat allowed list and need to be manually ported (now, and in any future PR) into the jacket.
This is the allowed list ignoring the items that the jacket can carry already.

```	allowed = list(
		/obj/item/analyzer,
		/obj/item/biopsy_tool,
		/obj/item/dnainjector,
		/obj/item/flashlight/pen,
		/obj/item/healthanalyzer,
		/obj/item/paper,
		/obj/item/reagent_containers/dropper,
		/obj/item/reagent_containers/cup/beaker,
		/obj/item/reagent_containers/cup/bottle,
		/obj/item/reagent_containers/hypospray,
		/obj/item/reagent_containers/pill,
		/obj/item/reagent_containers/syringe,
		/obj/item/gun/syringe,
		/obj/item/sensor_device,
		/obj/item/soap,
		/obj/item/stack/medical,
		/obj/item/storage/pill_bottle,
		)
```
Or well, just keep them removed and be labeled as a balance change.

**Comment by Imaginos16** [comment]
Actual L.

**Review by Imaginos16 — APPROVED** [review]
Otherwise, uh, pay attention more or something, I'unno.

**Pull request merged**
