### PR TITLE
Fixes all noRP-type respawning

### PR DESCRIPTION
**Pull request by ghost**
:cl: HideAndSeekLOGIC
add: Makes respawning bad
/:cl:

[why]: # 

Respawning is noRP and allows for antags to get called out and DIE and , medby now has mire wats to gjt stuf don nf clonung . now nerfed and MINERS now Stop powerga ming and xenobiologists will also stop powergaming and that means that powergaming will be reduced to null and we can

### CODE REVIEW

**Comment by optimumtact** [comment]
Okay now this is premium salt

**Comment by subject217** [comment]
Okay, now this is epic.

**Comment by XDTM** [comment]
From mindswap to mutually assured destruction

**Comment by PKPenguin321** [comment]
Looks good to me, ship it :+1:

**Comment by Tlaltecuhtli** [comment]
why is this fix a feature

**Comment by kingoftheautism** [comment]
speedmerge

**Comment by HideAndSeekLOGIC** [comment]
> why is this fix a feature

look at the code

**Comment by DaydreamPuppeh** [comment]
I love this. If you dont merge it permanently, merge it for April fools day

**Comment by ExcessiveUseOfCobblestone** [comment]
good pr

**Comment by MACIEKBAKI** [comment]
speedmerge pls

**Pull request closed without merging**
