### PR TITLE
Crafting TGUI improvements (Compact mode!)

### PR DESCRIPTION
**Pull request by RemieRichards**
:cl:
add: Added a Compact mode to the crafting tgui
tweak: Modified the back end of the crafting tgui so that it has well let's just say "a lot less" calls to certain functions, should lag a little less but don't expect miracles (you'd have to wait till we get a new version of ractive for those!)
/:cl:
## Changes:
- Added a "Compact" mode for crafting
- Reduced number of `istype()` calls per `ui_data()` by `((2*requirements_num) + catalysts_num + tools_num)*recipes_in_category_num`, this, not surprisingly, is a big number! these calls were left over from the previous raw HTML UI that crafting had, and weren't actually necessary
## Compact Mode:

compact crafting ui image
<B>Pros:</B>
- Smaller (Less whitespace, majority of what you see is a functional part of the UI)
- See more entries per section (Roughly double the entries of the full-size mode)

<B>Cons:</B>
- No filter bar (Sadly doesn't work in compact mode, so it's disabled, will try to add this for compact mode in a future update)

### CODE REVIEW

**Comment by Incoming5643** [comment]
but does it load in any faster?

**Comment by RemieRichards** [comment]
@Incoming5643 learn to read.

**Comment by xxalpha** [comment]
Looks a lot better, and who needs filter when you have ctrl+f?

**Comment by Incoming5643** [comment]
I'm pretty sure that changelog wasn't there when I saw this, but whatever

**Comment by RemieRichards** [comment]
@Incoming5643 it was because somebody added it to the PR template, so it forced a changelog on me.

**Comment by MrStonedOne** [comment]
I'm gonna give ractive another go, they've had quite a few fix prs merged, so maybe some bug we found was fixed.

**Comment by ChangelingRain** [comment]
this looks okay

**Pull request merged**
