### PR TITLE
Buffs the mime. (Adds 30 new emojis, all emojis visible within PDA.)

### PR DESCRIPTION
**Pull request by spessbandit**
## About The Pull Request

Adds more emoji to the game:

newmoji

Also:
Added Antur's redesign of the emoji guidebook that made images display inline without having to click.
Alphabetized the emoji guidebook.
Centered some emoji that were annoyingly off center and made other small edits to emoji (the cat emoji has ears now for instance).

## Why It's Good For The Game

The mime can better communicate, in particular it can now say AI DOOR 

also regular people can use them

also the pda sucks a little less

## Changelog
:cl: bandit
add: 30 new emoji have been added. Mime buff, mime now OP.
tweak: The mime's PDA now lists all emoji pictures in the PDA in alphabetical order without having to click.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
cock emoji very cool

**Comment by spessbandit** [comment]
we already have the actual cock emoji (eggplant)

**Comment by HomocidlePancakes** [comment]
Any in game way to see the emoji list?

**Comment by spessbandit** [comment]
the mime has it on his PDA

**Comment by carshalash** [comment]
🔫 and 😂 so they can indicate when they want to kill themselves.

Also wew github made it the dumb water pistol emoji

**Comment by spessbandit** [comment]
we already have two separate gun emoji (cap gun and revolver)

**Comment by Detective-Google** [comment]
we already have 😂 as well iirc

**Comment by TheChosenEvilOne** [comment]
Not enough, add more

**Comment by spessbandit** [comment]
give me suggestions that can actually be executed at scale by someone with no real artistic ability and I will try

**Comment by carlarctg** [comment]
credit anturk

clown mask if its somehow not in

a cult rune

**Comment by spessbandit** [comment]
both are in

**Comment by wesoda25** [comment]
I want a box emoji

**Comment by spessbandit** [comment]
done

**Comment by Tlaltecuhtli** [comment]
add circle hand

**Pull request merged**
