### PR TITLE
Heavily updates the Syndicate Lavaland Compound

### PR DESCRIPTION
**Pull request by Addust**
oh boy here i go messing with ruins again!
## About The Pull Request
Upgrades Syndicate Lavaland's noncombat functions heavily!

1. Syndicate Lavaland's maintenance has been removed, instead replaced with a water synthesiser closet with the oxygen canister, a janitor's closet with some space cleaner and regular cleaning tools, and an expanded bar backroom that doubles as a kitchen!*
image
image
image
*kitchen functionality untested.

2. Atmospherics has gotten a slight update, allowing for the turbine to be more easily converted to run with the modern system and provide longer-lasting gas supplies! I would've made it use gas filters instead of gas miners, but the atmospherics wiring there is bad enough as-is. Additionally, the piping layers have been re-standardised: layer 4 is now distro and layer 2 is now scrubbers as Ratvar intended. The radiation closet placements have also been reduced as I can't find anywhere else to put them and the engineering airlock needs decluttering: better pack your toxin meds!
image
3. The crew quarters now feels more homely, and is pre-supplied with crowbars for use exclusively on Campbell because their rounds are stupidly fucking long for good reason.
image
4. The plasma tank dispenser is now a water cooler wired into the ducts. Ignore the aftertaste.
image
5. Slightly pushes back the wall with the APC in Arrivals since maintenance is gone.
image
6. Ports one, single, lone door from our friends over at Yogstation so the comms agent can drink themselves to death slightly faster.
image
7. Chemistry now gets 1 plumbing constructor and 2 full stacks of duct, for creating bioweapons! Or meth!
image

## Why It's Good For The Game
Syndicate Lavaland's map design is kinda stagnant, and at the same time the non-standardised piping has probably caused at least one headache by now.

## Changelog
:cl:
qol: Syndicate Lavaland has recieved a major facelift! Go visit the Syndicate fortress today! Just try not to get a 50 BMG round up your nose.
qol: The piping at Syndicate Lavaland is now standardised.
add: Syndicate Lavaland now has a plumbing constructor and a griddle.
fix: Syndicate Lavaland's turbine now requires less extensive modification to produce power.
tweak: woops, i shuffled around some of syndicate lavaland's air alarms. shouldn't take too much effort to find
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
> gas miners are kinda sus considering the lavaland base gets a supermatter shard.

A random chance to get a supermatter shard

**Comment by Addust** [comment]
oh PISS i accidentally used an old version, re-drafting! (when i find the button)

**Comment by Addust** [comment]
i'll convert it to the up-to-date code later tommorrow

**Comment by Rex9001** [comment]
> gas miners are kinda sus considering the lavaland base gets a supermatter shard.

33% to have one

**Comment by TheVekter** [comment]
> why does a 33% chance change anything about it being sus, it's still sus

It'll only be sus 33% of the time!

**Comment by Googles-Hands** [comment]
Would it be possible to configure the bar sign to start emagged so they can select the Syndie-Cat logo if they want to?

**Comment by Rex9001** [comment]
> Would it be possible to configure the bar sign to start emagged so they can select the Syndie-Cat logo if they want to?

Yeah it would be easy, if I understand the code right

**Comment by Addust** [comment]
thanks for the extra ideas, i've still got air alarm work to do

**Comment by Addust** [comment]
can't pre-emag the barsign, BUT! cargo is updated with funky warehouse shutters (little do they know the corner wall in the warehouse is literally a bomb)
image

**Comment by san7890** [comment]
> can't pre-emag the barsign

you can make a mapping helper that calls emag() or what have you on the bar-sign on world init

**Comment by Rex9001** [comment]
> Prehaps implement a way to generate power? As is right now, unless they get the supermatter room, the Syndicate base will run out of power. And due to turbine nerfs, the turbine can't produce enough power to power the base, nor can the TEGs outside.

Maybe upgraded turbine parts?

**Comment by Addust** [comment]
that's why i added the exhaust cooling chamber, to keep the turbine's exterior in space-like conditions. could possibly see to stocking upgraded parts though

**Comment by Addust** [comment]
i'll add some VV'd in tier 3 ones

**Comment by Addust** [comment]
also, outside those are RTGs. i could actually add a TEG though, nobody bothered to remove it from code and it could be a unique element of the ruin

**Comment by Rex9001** [comment]
> also, outside those are RTGs. i could actually add a TEG though, nobody bothered to remove it from code and it could be a unique element of the ruin

Is the TEG code even functional? Or is it just the sprite that has been left in

**Comment by Addust** [comment]
TEGs are broken, nope

**Comment by san7890** [comment]
updating tags to reflect changelog

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
