### PR TITLE
[Box Map] Brig Updates

### PR DESCRIPTION
**Pull request by Ikarrus**
The prison station change probably isn't going to go through, so this is just a collection of some of the smaller changes I made for it that I liked.
- Security can now use their Brig external airlocks
- Added armory shutters to let officers in quickly and easily without having to constantly open doors for them
- Gavel and gavelblock added to courtroom
- Added a couple of more windows around the evidence room
- Removed muzzle and blindfold because they are literally unfun hitlers on top of being in an unresistant straight jacket.
- Fixed horribly misplaced /area/s in the brig
- Added some weak points (non-reinforced walls) around the exterior of the singularity chamber.

### CODE REVIEW

**Comment by bgobandit** [comment]
>Security can now use their Brig external airlocks

thank you based ikarrus

**Comment by SconesC** [comment]
>Security can now use their Brig external airlocks

jesus fuck

Picture for the new shutter stuff?

**Comment by Ikarrus** [comment]
screenshot 2015-07-22 21 54 15 - copy

Similar to this, but it's just one button instead of two.

**Comment by SconesC** [comment]
Looks weird without a border on the top but hey its a nice change

**Comment by Dorsisdwarf** [comment]
Can you make it one of those blast door things instead of a shutter? I don't remember what they're called, but it might look better and be more thematic

**Pull request merged**
