### PR TITLE
Durathread bundles and sinew make their proper noises instead of metal clang sounds.

### LINKED ISSUE #85433: Raw durathread bundles make metallic sounds when dropped and picked up
Reporting client version: 515.1641

## Issue Summary
Self-explanatory. They probably inherit the sound from base stack materials

## Round ID:
[232895](https://scrubby.melonmesa.com/round/232895)

### LINKED ISSUE #85503: metal sinews
## Issue Summary
dropping a watcher sinew makes metal clang sound

## Round ID:
[233079](https://scrubby.melonmesa.com/round/233079)

## Testmerges:
#85392 

## Reproduction:
drop a watcher sinew
listen

### PR DESCRIPTION
**Pull request by Astrogem2**
## About The Pull Request

Adds cloth noises to durathread bundles and meat noises to sinew strands to stop them from making metal clang noises.

## Why It's Good For The Game
Fixes https://github.com/tgstation/tgstation/issues/85433, fixes https://github.com/tgstation/tgstation/issues/85503

## Changelog

:cl:
fix: Raw durathread bundles and sinew strands no longer make metal clang sounds.
/:cl:

### CODE REVIEW

**Review by grungussuss — CHANGES_REQUESTED** [review]
Hook it onto cotton so it covers both

**Comment by Sadboysuss** [comment]
I'm dumb sorry, I thought durathread was a subtype of cotton for some reason.
Just add the same thing you did for cotton to durathread, and it'll be a fix for both cotton sound and durathread sound.

**Comment by Astrogem2** [comment]
I think I did that, tested it and the durathread bundles made cotton noises and such, should probably be fine(?)

**Comment by Astrogem2** [comment]
yeah its /obj/item/stack/sheet/cotton/durathread, so it works i think :)

**Comment by Sadboysuss** [comment]
Oh ok nvm then 🙂

**Comment by Rhials** [comment]
You might want to bundle fixing #85503 into this too? It's an identical fix for a near identical bug.

**Comment by Sadboysuss** [comment]
> I'm assuming stuff that has the item/stack/sheet path will have the metal clang noise as default for some reason so stuff that uses that path without it's own unique pickup and drop sound will need some pick up and put down noises added.

yes that's correct

**Comment by Sadboysuss** [comment]
I'll do a pass over of all the sheets later, you don't have to keep updating your pr lmao

**Comment by Shadow-Quill** [comment]
> Fixes: #85433 #85503

jsyk, you have to repeat a keyword for each issue to have it linked to be auto-closed.
IE: `Fixes #85433, Fixes #85503`

**Pull request merged**
