### PR TITLE
Adds Efficiency Station

### PR DESCRIPTION
**Pull request by WJohn**
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

### CODE REVIEW

**Comment by Nienhaus** [comment]
:+1:

**Comment by Zilenan91** [comment]
Do you mind adding some costumes to the theatre in case anyone wants to make a play? Monkey suits, xeno suits, that sort of thing.

**Comment by GunHog** [comment]
Nice work, WJ! It seems the HoS and RD offices are missing their hardsuits, though.

**Comment by Zilenan91** [comment]
Oh also kickin' rad map I look forward to playing on it

**Comment by PKPenguin321** [comment]
the mining shuttle smack in the middle of the station is nasty smelly poo poo stinky bad but otherwise :+1:

**Comment by KazeEspada** [comment]
Needs Maint Med. It isnt a true efficiency station without one.

**Comment by Zilenan91** [comment]
Maint on this is certainly miles better than box, though there isn't an abandoned surgery room which kinda sucks.

Also can you remove those random grilles in the middle of maint hallways? Every other map removed those because they're just unnecessary blockage.

The Bartender locker isn't a formal locker, it's a regular locker, also does the Barman and Chef share the access to both of their doors into their storage room between them?

REALLY love the bridge design even though I'll never see it since I'm a lizard. Are the insuls on the table fake maint loot or are they real? If they're real I'd suggest removing them because the Captain/HoP should go to engineering to get insuls not fight each other for the pair on the table even though it'd be funny to have the cap announce he killed the HoP for gloves.

The Teleporter room has some problems. Afaik you can't turn the hub off from outside if it's on because of how machines work, so moving the shutter to get inside might be for the best, otherwise captains will leave the teleporter on so nobody can enter the bridge from there. It's also not emaggable from the outside as it is a shutter, so I suggest changing that to an airlock.

The Library looks really barren, it'd be nice if you could add some random trash like paper scraps and newspapers to the floor so it looks a little bit older.

Do you mind at all adding an arcade machine to perma? Makes it a lot more enjoyable to inmates.

I don't see any initial place for miners to gear up, so I assume you're just using the asteroid itself for them to gear up at?

**Comment by Jordie0608** [comment]
You will need to add this to config\maps.txt

**Comment by neersighted** [comment]
Woo its happening!

**Comment by xxalpha** [comment]
This map will likely be maintained, so :+1:

But it should have been efficiency1.

**Comment by YotaXP** [comment]
CE has their own private bathroom to hide in. :+1: 

Perma is extremely close to the shuttle dock.  Is it possible for a prisoner to spacewalk out a broken window and into the escape shuttle airlock before passing out?

**Comment by duncathan** [comment]
is that an ATMOSPHERICS PUG

**Comment by KazeEspada** [comment]
His name is Spaghetti because of all the pipes. HE WAS THE FIRST PUG EVER MAPPED.

**Comment by Alek2ander** [comment]
Map comments:
:question: HoS office is closest to the gloves on the bridge. Powergaming is go.
:+1: Holodeck is extremely efficient for evil AI. Finally setting it on fire has a point.
:-1: Vault and tech storage are horribly unsecure. Their access hallway seems like something with extremely low traffic, so you're likely to be safe hacking the door without any precautions. Also, direct wall to maint.
:-1: AI core protected by shutters, good luck getting in without deconstructing an rwall.
:question: HoP doesn't have a private toilet, but the other heads do.
:+1: Head of staff toilets are easy to break into quietly (because no cameras)
:+1: Telecoms satellite
:?: It would seem that a connection between permabrig and the the escape dock would make sense for quick evacuation of prisoners (and that would also add a way to break out of perma if you get tools)

**Comment by Dorsisdwarf** [comment]
Metastation has the core shutters in the door too, doesn't it?

**Comment by Anonmare** [comment]
@Zilenan91 Cap's gloves are electric/heat resistant, plus the Cap spawns with them on and has a spare pair in his locker anyway and the HoP usually gets them if he asks nicely.

**Comment by alphaaBeta** [comment]
@Dorsisdwarf Meta's shutters are powered by the APC in the foyer, I think.

**Comment by Dorsisdwarf** [comment]
Not unless that changed recently, I think.

**Comment by Supermichael777** [comment]
:question: armory is in the middle of high security areas glhf breaking into it. on the one hand finally on the other this is a bit too far. 
captains quarters has a double r wall where it could have A BIG DESK MADE OF TABLES.
other double r walls nearby.
crew cannot see JUSTICE occurring.

**Comment by Dorsisdwarf** [comment]
HOS bathroom needs regular walls not rwalls, the whople point is to be a weak spot.

**Comment by WJohn** [comment]
I felt that would be too easy to break into at the time, since all you'd need to do is hack one door and break down one wall and you're in the HoS office. Sure, you need space protection, but honestly a firesuit and some hot coffee would last more than long enough for the very short walk from escape the the security pod.

**Comment by Dorsisdwarf** [comment]
You mean like on every other station, where it's one non-rwall from space, or two regular doors from maint?

**Comment by Metacide** [comment]
:+1: :+1: :+1:

Look forward to seeing this in action again!

**Pull request merged**
