### PR TITLE
Adds Earn Your Beard (w/ "doesn't count" admin button)

### PR DESCRIPTION
**Pull request by JJRcop**
This is a second attempt to add persistent beards that grow when you survive rounds. Except this time, I added a "Freeze Survival Streak" admin button that, when pressed, will cause everyone's streak progress to freeze for that round.

This means that even if you die, or don't make it to the shuttle, or your beard is shaved off, or any other madness that could happen to you, your beard and "Rounds survived in a row" stat will not change. This also means that they won't increase either.
## Old PR's desc (#19367)

:cl:
add: Adds Earn Your Beard. Enabled in character preferences, this forces you to grow your beard out by surviving consecutive rounds in the same body, in exchange for cool animated effects!
/:cl:

If enabled in preferences, you will start shaven, and will grow your beard as you survive consecutive rounds in a row. The benefit though, is your beard will have an animated effect which is choosable from preferences, that is not attainable anywhere else.

Survival is defined by escaping on the shuttle alive in the exact same body you were spawned in. If the round ends without the shuttle being called, like if you kill the blob, survival is defined as above except without the shuttle part.

rainbow shadow electric blaze

### CODE REVIEW

**Comment by Yiu113** [comment]
Fuck yeah, admins can do rounds where they summon 70 immovable rods without killing beards.

**Comment by xxalpha** [comment]
this saves the tgstation

**Comment by WJohn** [comment]
Unusual beards.

I'm okay with this.

**Comment by Shapsy** [comment]
And then people get pissy when admins don't hit the button when an admin event gets one or two people killed, or they do get pissy when the button is pushed and their streaks get frozen for the round, and it's still a massive headache

**Comment by MMMiracles** [comment]
B E A R D

**Comment by Alek2ander** [comment]
If your special beard gets shaved in-game the streak should be reset as well

On the other hand, antags with no escape objective should be exempt from losing the streak (keeping the beard > sacrificing yourself to spawn Nar-Sie).

**Comment by jughu** [comment]
Speedmerge!!

**Comment by optimumtact** [comment]
Something needs to be done to get the headmins/headcoder on board with this.

I don't have any real ideas, maybe a medal (the byond type, not the ingame type) for surviving multiple rounds instead of a beard?

I just don't see anyway to resolve the tension about this, other than making the reward less important so people dont' care as much, which then dilutes the original intention of the PR.

**Comment by RemieRichards** [comment]
I could stand by increasing medals, eg:
<B>Getting the hang of things:</B> Survive a round
<B>[funny name]:</B>Survive 2 rounds in a row
<B>[funny name]:</B>Survive 5 rounds in a row
</B>Are you metagaming?:</B> Survive 10 rounds in a row

And even opposites:
<B>Oops:</B> Die
<B>Bad day?:</B> Die 2 rounds in a row
<B>[funny name]:</B> Die 5 rounds in a row
<B>I ded pls nerf:</B> Die 10 rounds in a row

**Comment by GunHog** [comment]
>Something needs to be done to get the headmins/headcoder on board with this.

>I don't have any real ideas, maybe a medal (the byond type, not the ingame type) for surviving multiple rounds instead of a beard?

>I just don't see anyway to resolve the tension about this, other than making the reward less important so people dont' care as much, which then dilutes the original intention of the PR.

The rule:
>Losing is part of the game.
Your character will frequently die, sometimes without even a possibility of avoiding it. Events will often be out of your control. No matter how good or prepared you are, sometimes you just lose.

Needs to be more strongly emphasized to counter the deluge of NaCl saturated tears that will be extracted as a result of this PR. 

- Ensure that a full greentext exemption exist for antagonists, period. Players should **never** be discouraged to sacrifice themselves for the greater good (such as a Nar'Sie summon).
-Invalidate admin complaints due to loss of beards, even if an admin forgets to use the NOT CANON button.
- Have something to allow admins to do this to a single player who requires admin attention due to special circumstances (such as game bugs, memes, etc)

**Comment by KorPhaeron** [comment]
It's not good to have game mechanics that encourage one attitude and rules that then tell you that attitude is wrong though

**Comment by Lobachevskiy** [comment]
How does this transfer from character to character? What about female characters? What if I need to change my appearance? What if I change beard style? What about other kinds of facial hair? What if I'm changeling? Or any other kind of antagonist?

I understand that you want it to be a gimmick, but this is just too intrusive.

**Comment by optimumtact** [comment]
Sadly I just don't think there is appetite for this from admins/maintainers.

**Pull request closed without merging**
