### PR TITLE
Rescale SM health from 900 to 100, UI improvements, visual changes.

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
Title.
Rescaling because i saw someone think that the number on the supermatter UI are actually the percent damage over time, which is wrong.

Added delta symbol to damage and energy since they actually denote change, not the actual value.

Chose the numbers that look good instead of doing a 1:1 rescale of the old one (i.e. im dividing or multiplying things by 10 instead of 9). In practice this means I'm lowering the damage cap but increasing damage over the board for atmos (since it's mostly divisors). Lowered the damage overall for external stuffs.

Picked the spirit of #71641 up, with my own modifications.

A bit of modification on the filter helpers to suit my needs. Added documentation because I'm awesome.

## Why It's Good For The Game
Should be self evident.

## Changelog
:cl:
code: rescaled supermatter health from 900 to 100.
balance: we didn't do a 1:1 rescale of the damage though, atmos based damage should be slightly higher across the board but have lower caps. All external damage is slightly lower.
code: made the less important parts of the visual supermatter effects same between different delams so we have an easier time changing the code.
qol: added a delta symbol to the SM UI on damage and energy breakdown to denote that they are actually changes instead of exact values.
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
Don't forget the effects numbers will have to be tweaked to look correct afterwards

**Comment by vincentiusvin** [comment]
Oh shit right

**Comment by vincentiusvin** [comment]
Actually while I'm in the area ill scale the numbers down. Not constrained by the refactor tag here.

**Comment by JohnFulpWillard** [comment]
Code looks good and it was testmerged for

22 fuckin rounds??

**Pull request merged**
