### PR TITLE
Proper removal of chem implant action buttons

### PR DESCRIPTION
**Pull request by silicons**
#36021 but it works
also port new --> initialize, destroy() ordering, 1 --> TRUE

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by GuppyLaxx** [comment]
kevonz ruining my game

**Comment by Robustin** [comment]
Didn't realize Optimum actually merged that awful PR. 

The action button version needs to be added to a medical tech node if we're going to be bitches and deny them to sec.

**Comment by Spaceinaba** [comment]
just get good and dont get stunned nerd

**Comment by Spaceinaba** [comment]
more like oldman brain is crusting

**Comment by Robustin** [comment]
I never used meth chem implants or shit like that, im too lazy - but I think it was a fair niche for sec to invest in. 

That's part of the lack of appeal in security. Everyone works to make these great chems, cool viruses, giant mechs, xeno armies, miner relics, etc. but sec just gets its best equipment at roundstart and its downhill from there.

**Comment by Spaceinaba** [comment]
engineering has the same dilemma but people still play it

**Comment by Spaceinaba** [comment]
anyways what do chem implants do without the action button do they just serve no purpose or were they multi use or something before

**Comment by KorPhaeron** [comment]
@Robustin its hard to improve on ranged stuns without making shit silly is why

**Comment by Robustin** [comment]
@KorPhaeron 

It doesn't necessarily have to be weapons - but there are plenty of weapon ideas. A sentience module for Beepsky. An AUTOCUFFER that can be used to instantly apply cuffs, or its final form a ranged cuff launcher (but the cuffs would be much easier to break). Upgrades for armor or the sec hardsuits, a single-charge shield generator... I'm just spitballing here but sec probably has the most design space for lategame tech.

@Spaceinaba 

I agree engineering has the same problem but their issue is mitigated by the fact they have the best roundstart loadout by far. RCD's, Gloves, Materials, Hardsuits... my experience has been that engineering is a "fuck off and do your own thing" role once the engine is set up within the first few minutes.

**Comment by Spaceinaba** [comment]
thinking about it engineering and sec have the same problem where you have fucking nothing to do until the antags ruin things

**Comment by PKPenguin321** [comment]
Robustin just use tooth implants same thing

**Pull request merged**
