### PR TITLE
Nerfs Water mildly :^)

### PR DESCRIPTION
**Pull request by Niknakflak**
> Duncathan: there are other values to tweak it to; there could be a yet milder nerf like 3,2 or 3,1 or you could nerf storage capacity of things like spray bottles. You've got lots of options; I believe in you

and so here we are.

### CODE REVIEW

**Comment by optimumtact** [comment]
:+1:

**Comment by duncathan** [comment]
good branch name

**Comment by Lumipharon** [comment]
Can someonr please address spray bottles since that is very clearly the only thing that can be considered an issue, instead of water itself?

This is the same thing as giving sec 50 round tasers, then nerfing stuns because it's OP.

**Comment by Amemelius** [comment]
I mean, this is okay I guess, it actually makes them usable again. Only thing is really the only thing that should be nerfed is spray bottle capacity (it'd be totally fine if sprays could only hold 50 reagents total), rather than stun duration, imho.

**Comment by Xhuis** [comment]
ayoo

**Comment by PKPenguin321** [comment]
:+1:

**Comment by Core0verload** [comment]
:-1:

**Comment by Niknakflak** [comment]
I'm sorry, negative feedback is not allowed

**Comment by Core0verload** [comment]
:-1:

**Comment by optimumtact** [comment]
I'm sorry, negative feedback is not allowed

**Comment by adrix89** [comment]
:+1: :-1: :+1: :-1: :point_up_2: :hand: :facepunch: :v:

**Comment by Niknakflak** [comment]
Merge when?

**Comment by Dorsisdwarf** [comment]
Cannot merge needs 5 day test run and over 50 responses to an ingame poll.

Also I need a stamped form from exadv, cheridan, miauw, and TLE

**Comment by Niknakflak** [comment]
You're not even real.  "Issue maintainer"

**Comment by duncathan** [comment]
Adding insult to injury since 2015

**Comment by borntohonk** [comment]
please no

**Comment by duncathan** [comment]
If people don't like it I'll revert it again don't worry

**Comment by Lumipharon** [comment]
t e s t p r f e a t u r e

**Comment by duncathan** [comment]
:^)

**Comment by Lumipharon** [comment]
Seriously, merging shit like this saying 'we can revert' evenif you sincerely mean it (unlike most), puts on the onus on those that don't want the change, as opposed to those that do want it, since the pr is already merged.

If you use the feature explicitly designed for shit like this, then it more sensibly puts the onus on the people that WANT it merged, to justify it being there.

**Comment by duncathan** [comment]
Alright so to actually explain myself, I'm gonna move to say that this isn't what the test PR feature is for. This isn't a big change that affects a lot of things, like steelrifles or goof's proposed med changes. It's a minor value change that very few people will even notice. Using the test PR feature for this wouldn't really have useful results. 

I'll make something more clear about this one, though - I'm not looking for people to dislike it so that I decide to revert. I'm looking for people not to notice it. If the nerf goes unnoticed, I'll revert it because it didn't accomplish its goal, so why leave things nerfed that didn't need to be? So in that way, I guess I am putting the onus on people to like it.

**Comment by PKPenguin321** [comment]
yeah, testing pr feature on this would be dumb because then we'd have to have a round focused on using the newly balanced slips so we could test it specifically

**Comment by Lumipharon** [comment]
In the words of the person who first preposed these nerfs, they're targetting one specific player.

So either way, by their own admission this would really only be important in rounds where that specific player is using this specific thingo for murderboning.

**Comment by Niknakflak** [comment]
MMMiracles was targeting one specific player?

**Comment by Lumipharon** [comment]
>This PR was made from a collaboration of watching multiple rounds and multiple murderboners that were successful solely because of lelwaterslip. If shit like quick-choke and table chain-stunning was removed then why would water spam be allowed to stay as well?

Going from that, and the constant shit people were giving amelius in the last pr, yes, it seems to me heavily implied that amelius rekt loads of nerds with water an suddenly waterslips that haven't changed for years needed to be nerfed.

**Comment by Dorsisdwarf** [comment]
@Niknakflak Yes. Both of the people in favor of this change have admitted it's because memelius likes to murderbone with waterslips, and no other reason

**Pull request merged**
