### PR TITLE
Base Female sprite tweaks

### PR DESCRIPTION
**Pull request by Sheits**
## About The Pull Request

ASS STUFF HAS BEEN REMOVED BUT I STILL HATE IT

This PR tones down the proportions of the female base sprites, as currently they have about SIX extra pixels on the ass and a random pixel missing from the neck, which breaks some hairstyles & makes the neck look quite stupid.
It also adds a couple pixels to the male one because theirs was so stupidly SMALL it looked like they had no tailbone (still does, kind of).

Here is the current sprite 
image
& new sprite (only neck pixel removed)
image

## Why It's Good For The Game

Fixes some hairs

image

## Changelog

:cl:
image: fixes weird inconsistency on the neck and butt of the female base sprite
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
boober

**Comment by EricZilla** [comment]
Can you also delete the dixel so all the underwear fit on both bodies lmao

**Comment by Pickle-Coding** [comment]
I thought women were supposed to look like women.

**Comment by cnleth** [comment]
> I thought women were supposed to look like women.

How do a weird neck and a missing pixel on the back make the old sprite look more like a woman

**Comment by Serxule** [comment]
ass is a genital fellas, you heard it here

**Comment by atlasle** [comment]
> I thought women were supposed to look like women.

as if you've ever seen one

**Review by Wallemations — APPROVED** [review]

**Comment by Jackal-boop** [comment]
whats the weird tummy thing?

**Comment by Helg2** [comment]
> whats the weird tummy thing?

It's a hand

**Comment by MTandi** [comment]
It's less distinguishable now from a male. That was the main function of this sprite and you reduced it.

I really wonder who even cares about such thing. It's just an ass.

**Comment by thgvr** [comment]
You need to adjust the female sprite masking stuff if you're doing this or parts of the body will show through clothing.

**Comment by Sheits** [comment]
image
female ass change reverted hopefully

**Pull request merged**
