### PR TITLE
Gang Stat Tracking

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Since some players seem to think gang steamrolls security, and other players seem to think security steamrolls gangs, lets try and find out what actually happens.

### CODE REVIEW

**Comment by chanoc1** [comment]
yea sems preddy gud

**Comment by Bawhoppen** [comment]
I'm pretty sure its irrelevant what happens either way

**Comment by CosmicScientist** [comment]
:+1: Surprised this didn't exist already. Thanks for putting it in.

**Comment by Ikarrus** [comment]
kor I think you got the conditions backwards

**Comment by KorPhaeron** [comment]
It'll probably be fine

**Pull request merged**
