### PR TITLE
TGUI GPS

### PR DESCRIPTION
**Pull request by GunHog**
- Ported the GPS system to TGUI.
- GPS signals may now be updated automatically or manually, based on a new toggle.
- The GPS now has the option to scan only the same Z-level, or all of them.
- Toggling GPS power may now be done from the interface as well as the alt-click.
- The user's own GPS unit is no longer displayed in the signal list, and is now its own section for quick and easy self-location.
- Signals on the same z-level now have distance and direction information added to aid with hunting and exploration.
- The scanning range and auto-update buttons have tooltips to explain how they work.

:cl: Gun Hog
add: The GPS interface has been converted to tgui.
experiment: GPS now update automatically or manually, give distance and direction to a signal, and many other improvements!
/:cl:

I have always thought the GPS system was a little rough and hard to use well. It was a pain to even find my own signal to determine my location, let alone my target! My intent is to make the GPS much better, less clunky and more useful, while preserving as much as the original functionality as possible.

This is my first attempt at TGUI, so the code and UI itself might be a little crude and messy (such as the sizing). It is refined somewhat based on feedback from the forums, but is still up for polish and refinement. Thanks to everyone that helped me get into TGUI!

Corresponding forum thread here: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=10361

TGUI GPS

### CODE REVIEW

**Comment by Repukan** [comment]
>Hungry signal

Does this mean that thing got enabled again?

**Comment by GunHog** [comment]
It is not enabled on the servers, just the default code config.

**Comment by Repukan** [comment]
Thank goodness

**Comment by KorPhaeron** [comment]
Nice

**Comment by coiax** [comment]
GUYS GUN_HOG IS MAKING A PR, LET'S COMPLAIN ABOUT IT

**Comment by GunHog** [comment]
COIAX NO, PLEASE.

**Comment by Repukan** [comment]
Fucking hugbox, god forbid people find or name their coords.

**Comment by KorPhaeron** [comment]
Powercreep

**Comment by GunHog** [comment]
_Curls up into a ball and begins sobbing_

**Comment by Repukan** [comment]
>Miner fantasy monster hunter powercreeping

**Comment by KorPhaeron** [comment]
I think a gps spawns in RD on metastation so we all know his true motives

**Comment by Repukan** [comment]
GunHog confirmed for kevinz alt

**Comment by Kromgar** [comment]
Thank god for the local button you glorious son of a bitch

**Comment by Hatfish** [comment]
This is going to be a pain to resize every time you want to look at your GPS, but great work all the same.

**Comment by GunHog** [comment]
I would welcome your assistance on better auto-sizing techniques, especially when switching to local mode. Currently, it sizes itself according to the full GPS list when you first use it.

**Comment by lzimann** [comment]
I have nothing in mind about the resizing right now, but it will be easy to edit later.

**Pull request merged**
