### PR TITLE
Makes the flow of gas overlays cleaner

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Two things here:
1: I made `MOLES_GAS_VISIBLE_STEP` actually like, matter. This adds 60 overlays per gas type, but makes things sooooo much better
2: I changed the formula for alpha from a linear one to a logarithmic one. This means turfs won't represent their contents quite as well, but it also makes things look a whole lot better as it better matches the rate of gas flow. The applying thing is also effected by how the old code worked. Because of the use of CEILING gas will show a bit later now

Here it is with [logarithmic flow](https://cdn.discordapp.com/attachments/326831214667235328/745138517675343972/2020-08-17_21-16-02.mp4), and this is the [linear flow](https://cdn.discordapp.com/attachments/326831214667235328/745138566236995614/2020-08-17_21-32-17.mp4) 
## Why It's Good For The Game

Old:
image

New:
image

## Changelog
:cl:
add: Gas overlays are more smooth now, but will display things a little more subtly.
fix: Gas overlays have the proper amount of detail now
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I am not sure this is a good idea. Being knocked out by an N02 Flood you don't even see sucks donkey ass.

**Comment by LemonInTheDark** [comment]
Yeah that's true. I'll try raising the slope of the alpha change so stuff becomes more apparent faster

**Comment by LemonInTheDark** [comment]
Wait I'm dumb, the log curve will always be more visible then linear. I up'd it anyway for kicks

**Comment by Rohesie** [comment]
Harmful gases should be visible whenever possible.
Also, does this increase memory or processing cost?

**Comment by LemonInTheDark** [comment]
processing is the same, I'm changing the index list rather then the lookup. it adds a static 60+ overlays per gas type, stored in the meta gas list. I think it's worth it for the smooth gas

**Comment by Rohesie** [comment]
Yea, that's not an expensive cost.
Let us know when this is ready.

**Comment by LemonInTheDark** [comment]
it should be good as of now, unless there's something you'd like changed

**Comment by LemonInTheDark** [comment]
or actually....

**Comment by LemonInTheDark** [comment]
nah this is good

**Pull request merged**
