### PR TITLE
Deadchat listeners will hear when people die

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: Deadchat is now notified when a sentient mob dies.
/:cl:

Includes the area name, because why not, I guess?

### CODE REVIEW

**Comment by Incoming5643** [comment]
This could get out of hand really fast

**Comment by Shadowlight213** [comment]
Yeah. I can see this becoming really bad in combination with like swarmers or someone boh bombing.

**Comment by Zilenan91** [comment]
It should just check for humans walking around and nothing else. Nobody really cares if a swarmer dies and it'll spam the chat.

**Comment by Iamgoofball** [comment]
@Zilenan91 
combine it

all human deaths are shown
all sentient mobs with antag status are shown

**Comment by coiax** [comment]
That's half the fun though, if 10 people suddenly die in R&D, you know that some SHIT'S GOING DOWN.

**Comment by Zilenan91** [comment]
Yeah that's great, but if there's tons of swarmers dying and reproducing everywhere it'll just spam the chat to shit

**Comment by Shadowlight213** [comment]
@Iamgoofball 
EVERY sentient mob has the antag flag though.

**Comment by Armhulen** [comment]
Then just have some mobs on a blacklist so we don't get swarmer shitty chatspam

**Comment by optimumtact** [comment]
I am not a fan of blacklists, whitelists are somewhat preferable, neither is best

**Comment by phil235** [comment]
This shows mobs dying in the thunderdome from admin testing and stuff, we shouldn't show the message for mob on z=2

**Pull request merged**
