### PR TITLE
fixes cameras crashing the server

### PR DESCRIPTION
**Pull request by silicons**
## About this pull request

ok so disclaimer
**i have no clue why this works** and by that i mean i do not have hard evidence that the below is why it broke, all i know is i tested this and it worked when it didn't before (tested, changed code, tested again, seemed fixed)
my best *theory* is that well for one i'm saving one massive blend operation that i realized was not needed since we have blend underlay as a mode 
and more importantly, enforcing no_anim, as my theory is something is animated which is causing getflaticon and therefore camera blend to produce a single 7x7 image with like what 49 frames or something instead of one, which would obviously be an issue as that's going to duplicate your image that many times.

i also added plane sorting to the camera layering system to be more realistic 

also added icons/blanks/32x32 and 96x96 .dmis for the blanks cameras and other stuff use (although i can honestly get away with just making it 32x32 only and using .Scale() so tell me if i should do that instead) while i was at it so you never have a situation in the future where someone touches something in effects.dmi and it breaks getflaticon.

## Changelog
:cl:
fix: cameras no longer crash the server
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
>i have no clue why this works

inspiring words to live by.

**Comment by optimumtact** [comment]
this is bullshit

**Comment by AnturK** [comment]
Did you replicate actual crashing or is this just blind changes.

**Comment by kriskog** [comment]
I've made my local server crash by taking pictures on current master. If it doesnt crash, it runtimes with bad icon operation. Taking photos spikes memory usage straight up. I dont see that with this with this checked out.

There is currently an issue where pictures save multiple frames per photo. This is one I took in thunderdome, then grabbed the photo file from the server. Thats where no-anim comes in presumably.
image

**Comment by optimumtact** [comment]
this happened last time when the backing images were removed

**Pull request merged**
