### PR TITLE
Nerf November is here

### PR DESCRIPTION
**Pull request by optimumtact**
In honor of Nerf November, we will not be accepting new features, balance changes (unless strictly necessary to stop servers expoding) for all of November.

We will be accepting fixes and code refractors only.

The person who makes the best fix as determined by the maintainer team will get a prize, which I will make up later.

### CODE REVIEW

**Comment by cacogen** [comment]
Our favourite time of year

**Comment by Ghommie** [comment]
Is this act retroactive as well, or are older PRs exempt from it, as long as no new banned changes are added to them in the meanwhile?

**Comment by optimumtact** [comment]
it's not retroactive unless you're doing something strange

**Comment by Jordie0608** [comment]
red

**Comment by kriskog** [comment]
> 
> 
> balance changes

So in honor of nerf november we are running a no nerf november event? Nice

**Review by Cyberboss — APPROVED** [review]

**Comment by necromanceranne** [comment]
Next month: Delete December.

**Comment by optimumtact** [comment]
That was a good freeze

**Pull request closed without merging**
