### PR TITLE
Fires Now Break Tanks

### PR DESCRIPTION
**Pull request by Whoneedspacee**
## About The Pull Request

Fires now break tanks after a few seconds, this makes singlecaps much harder to do.

## Why It's Good For The Game

Fires should probably break tanks, it makes sense.

At the very least if singlecaps are going to happen they should ideally blow up almost instantly which can at least sometimes kill the user or destroy the pump they are using.

This is the best way I can think to deal with singlecaps right now that also makes logical sense. I'm sure this conditional logic of breaking when there is a fire in a tank could prove to be useful for some creative atmosians as well.

On the flipside this might make old bomb methods that take a long time to react not work anymore, but I don't think I see many people use slow reacting plasma bombs anyways.

## Changelog
:cl: Joe Berry
tweak: Internal fires now cause tanks to rupture after a few seconds.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Lord almighty

**Comment by kriskog** [comment]
The way to remove singlecaps isnt to move the recipe or method further into arcane knowledge. If you wanna remove singlecaps, go ahead, but do so properly.

**Comment by AlinaStarkova** [comment]
"Fires should probably break tanks, it makes sense."

what sense? even irl a fire doesnt inherently break a tank, theres many usages in irl industry in which a tank contains a fire, many industrial processes use tank fires in their production method, a fire inside a tank has no reason to inherently break the tank, a fire only BREAKS a tank because it heats the gas enough that it expands to rupture point OR it melts the actual tank casting, both of which the game already checks for. this is a stupid way to rebalance singlecaps and will break a lot of atmos fuckery imho

**Comment by LemonInTheDark** [comment]
Why not remove the behavior? Is it about removing the throwing portion of things? What is the exact bit of behavior you're trying to nuke here?

**Comment by Whoneedspacee** [comment]
> The way to remove singlecaps isnt to move the recipe or method further into arcane knowledge. If you wanna remove singlecaps, go ahead, but do so properly.

The intention of this is not to fix singlecaps, in fact I'm almost certain that the knowledge on how to do them again will be leaked at some point. The intention of this PR is that the person who is doing the singlecaps must 100% be close to the detonation so that they might be injured by their own explosion or will actively have to be doing the bombing.

This is just me taking issue with people setting up 5 minute timers for singlecaps and leaving them all across the station or chucking singlecaps at the station from another z level, etc.

If you have a better idea on how to fix them entirely that isn't just hardcoded cap limits or weird stuff I'd be down for it, but tbh most op ss13 stuff is just obscure shit anyways, look at weird chemistry shit and you find the same thing.

**Comment by kriskog** [comment]
You are essentially just hardcapping the fuse timer here. If you've done the math, what is the maximum time (assuming no atmos SS load) a tank will take to reach 0 integrity once there is a fire inside?

**Comment by Whoneedspacee** [comment]
Yes I am hardcapping the fuse timer, that’s the intention of the pr.

From when the fire starts in the tank about 8 seconds.

**Comment by AlinaStarkova** [comment]
> This is just me taking issue with people setting up 5 minute timers for singlecaps and leaving them all across the station or chucking singlecaps at the station from another z level, etc.
> https://github.com/tgstation/tgstation/blob/cbfc64415a4ed22d43d551d01123ec67030ab385/code/game/objects/obj_defense.dm#L173

i personally dont think this is a common enough issue to warrant such a change. in fact, in my whole 2 years playing ss13, ive seen a single cap only once, and that was me trying to make one and blowing up kek. i feel like this is a fix looking for a problem, not the other way around.

**Comment by Tlaltecuhtli** [comment]
8 seconds is still enough time to place a tank on floor and move away

**Comment by Fikou** [comment]
> i personally dont think this is a common enough issue to warrant such a change. in fact, in my whole 2 years playing ss13, ive seen a single cap only once, and that was me trying to make one and blowing up kek. i feel like this is a fix looking for a problem, not the other way around.

rare =/= good, singlecaps can decimate the entire station in seconds if used properly

**Comment by AlinaStarkova** [comment]
> > i personally dont think this is a common enough issue to warrant such a change. in fact, in my whole 2 years playing ss13, ive seen a single cap only once, and that was me trying to make one and blowing up kek. i feel like this is a fix looking for a problem, not the other way around.
> 
> rare =/= good, singlecaps can decimate the entire station in seconds if used properly

you say that yet my PR which fixes a rare occurrence is hated by everyone because "it rare and funny" .... obviously its an issue when it happens, but the fact it rarely happens means this isnt really an issue. especially when this is a lazy fix as it simply does exactly what the code already does, but faster.

**Comment by Jared-Fogle** [comment]
> i personally dont think this is a common enough issue to warrant such a change. in fact, in my whole 2 years playing ss13, ive seen a single cap only once

I thought it was the coders that didn't play the game 🤷‍♀️

I've seen quite a few rounds that just get decimated by them. But frequency doesn't particularly matter, it's a tumor.

> you say that yet my PR which fixes a rare occurrence is hated by everyone because "it rare and funny" 

Did a maintainer tell you this? People say a lot of things.

**Comment by LemonInTheDark** [comment]
Given how variable atmos ticks can be, I'm not sure this is the play. I also disagree about making them harder, we should make them less then usable, not just make them even more secret.

Also, assuming the atmos ss fires twice a second, does your math hold true?

**Comment by Whoneedspacee** [comment]
> Given how variable atmos ticks can be, I'm not sure this is the play. I also disagree about making them harder, we should make them less then usable, not just make them even more secret.
> 
> Also, assuming the atmos ss fires twice a second, does your math hold true?

8 seconds is the absolute highest.

>gas put into tank, 0-2 seconds later 1st fire tick happens, 2 integrity.

>fire tick happens 2 seconds later, 1 integrity.

>fire tick happens 2 seconds later, 0 integrity.

>tank breaks 2 seconds later.

so anywhere from 6-8 seconds.

The formula is essentially the same with more plasma and oxygen for higher energy so this isn't even really targeting the """arcane knowledge""" of singlecaps, if you'd really like I could just post the new recipe in this PR. The intention of this pr is to stop people from putting 5 minute timer singlecaps in lockers or crates around the station which essentially makes an unstoppable chain reaction with no way to find the tanks since nobody is near them.

I understand this doesn't fix all the issues with singlecaps but I feel it's a step in the right direction.

If tritium fires specifically broke tanks faster that might be a better solution but reaction results isn't a list that has that by default and I wasn't sure if it'd be wise to add something new to that list from atmos ticks.

**Pull request closed without merging**
