### PR TITLE
Adds a disk slot to the ORM, to allow the uploading of new smelter designs

### PR DESCRIPTION
**Pull request by Profakos**
:cl: Profakos
add: Centcom has decided to upgrade the Ore Redemption machines with a floppy drive, intended for design disks.
/:cl:

This adds the ability to upload designs with the SMELTER buildtype to the Ore Redemption machine. Currently, the only transferable alloy is Alien Alloy (plastitanium and plasteel are known by the smelter by default). The ORM is not as efficient as the Protolathe, but at least it is conveniently close.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Interesting, i wonder if the dwarf smelter could have a unique adamantium & mythril crafting disk.

**Comment by Profakos** [comment]
Perhaps rune engraved disks that somehow fit into the floppy drives perfectly. 

If needed, I can expand this functionality to old style smelters too, as they also use design datums to make alloys. I just was not inclined to do it at first for multiple reasons, such as that upgrades are ORM's thing, the old smelter is controlled through a proxy screen, and that it would require some tweaks with regards to the labor camp (either no disk slot, or a way to have hidden point value for soon to be discovered alloys).

**Comment by ExcessiveUseOfCobblestone** [comment]
old style needs to be removed

**Comment by FantasticFwoosh** [comment]
No no, the old style has its place, its actually nice to have the ability to smelt things wrong & produce slag, really the old smelter & sorting machine needs a little rehaul & a way to build them.

**Comment by Profakos** [comment]
The old smelter has been overhauled though by me, it sadly can't make slag anymore. Its old code that enabled this functionality was kinda nightmarish, an if else chain where each if statements containing a dozen variables...
The sorting machine is still the same, but only because it stacks sheets, and not just materials.

**Comment by Bawhoppen** [comment]
this is pretty cool actually

**Pull request merged**
