### PR TITLE
Thermomachine can be dragged around now

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Thermomachines can now be moved around.
To do this, open up the panel with a screwdriver, then Right-Click on the machine with a wrench, after a delay the machine will be un-anchored; use ctrl-click to move the machine around. Then set the rotation of the machine by Left-Click with a wrench, screwdriver to close the panel, and the machine is functional again.

thermomachines can change the piping layer while constructed by hitting them when un-anchored with a multitool

## Why It's Good For The Game
More thermomachine QOL
being able to move the thermomachine around without having to deconstruct/rebuild it each time, helps player and will haste the construction of the various pipenets required to produce different gases, it is also much more needed since the rework due to the slightly increase in piping required

## Changelog
:cl:
qol: Thermomachines can now be moved around. To do this, open up the panel with a screwdriver, then Right-Click on the machine with a wrench, after a delay the machine will be un-anchored; use ctrl-click to move the machine around. Then set the rotation of the machine by Left-Click with a wrench, screwdriver to close the panel, and the machine is functional again.
qol: thermomachines can change the piping layer while constructed by hitting them when un-anchored with a multitool
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
For now this is still welcoming but...

20 qol changes later and we are gonna have thermo machine mechs that fix shitmos.

**Comment by Jhyrachy** [comment]
> 
> 
> For now this is still welcoming and especially good for toxins but...
> 
> 20 "qol" changes later and we are gonna have thermo machine mechs that can fix shitmos and instantly cool sm.

Until numbers are tweaked, this will never happen.

Try to cool a 20k kelvin mix and see how slow it is

**Comment by LemonInTheDark** [comment]
Why is this particular change good for the game? just saying it's qol doesn't really describe that, please be more clear

**Comment by Ghilker** [comment]
updated PR body

**Comment by Nexofas** [comment]
Setting thermomachines for incinerator and hfr were taking too much time, this is a QoL improvent by saving the unnecessary decon/construction time for sure.

**Comment by Jhyrachy** [comment]
> Why is this particular change good for the game? just saying it's qol doesn't really describe that, please be more clear

Atmos is terribly slow and space hungry.

So too often you have to relocate pipes and termomachine when you change gas production.
The big rework slowed down a lot everything because it made much more complex removing heat, so any kind of improvement is welcomed because it make atmos less frustrating.

Also @Ghilker what about using a multitool when they are in "move mode" to change their layer? (like it is right now when using multitool on the board)

**Comment by moocowswag** [comment]
I guess one reason why this is good for the game that isnt just "qol" is that the jobs that are relevant to this change have suffered a little bit from the change to dynamic being the main gamemode, both jobs are also heavily limited by how long the round lasts and how efficiently they can make use of their time.

-Rounds seem to have gotten shorter so spending less time moving freezers around helps make up for it.
-Toxins scientists and atmos techs have been getting more things to work on/work towards.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
