### PR TITLE
Fix typo 'abandoned'

### PR DESCRIPTION
**Pull request by TheTypoMaster**
Hi! I'm a bot that checks GitHub for spelling mistakes, and I found one in your repository. When it
should be 'abandonned', you typed 'abandoned'. I created this pull request to fix it!

If you think there is anything wrong with this pull request or just have a question, be kind to mail me 
at thetypomaster@hotmail.com (professional email, huh?). I’ll try to address the problem as soon as
I’m aware of it.

Looking for the source code of this bot? Well, you have to be patient! The bot is under development
and I will publish the source code as soon as I’m finished with it.

If you decide to close this pull request, pleace specify why before doing so.

With kind regards,
TheTypoMaster

### CODE REVIEW

**Comment by TheTypoMaster** [comment]
Sorry, you may see the problem here. Just close this!

**Comment by Cheridan** [comment]
Haha what

**Comment by RemieRichards** [comment]
abandoned is the correct spelling @TheTypoMaster, Thankyou anyway.

**Comment by TheTypoMaster** [comment]
Yes, it knows that, was doing some new code and didn't noticed it searched for the correct spelling, haha.

**Comment by RemieRichards** [comment]
Fair enough, it's an interesting Idea I'll give you that!

**Comment by TheTypoMaster** [comment]
Thanks :) It'll be released today/tomorrow!

**Comment by Miauw62** [comment]
Damn bots trying to sneak typos into our repo :P
Op 3-okt.-2015 22:03 schreef "TheTypoMaster" <notifications@github.com>:

**Comment by TheTypoMaster** [comment]
Haha, sorry!

**Pull request closed without merging**
