### PR TITLE
Lowers firedoor loop volume

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
Reduces the volume of the firedoor alarm loop
## Why It's Good For The Game
It's loud, especially when they double up. On those shifts where it's running constantly, it can get on your nerves.
## Changelog
:cl: LT3
qol: Reduced volume of firedoor alarm sound loop
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
I don't think fire alarms should be ignorable as background noise.

**Comment by Zergspower** [comment]
> I don't think fire alarms should be ignorable as background noise.

less background noise focused and more 'kinda tired of this earrape because atmos hasnt showed up in 40 minutes' so lowering the default volume is a yes plz

**Comment by JohnFulpWillard** [comment]
I don't think the volume should be lowered so terribly, I expected this to be a small change lol

**Comment by lessthnthree** [comment]
We could do 40.

**Pull request merged**
