### PR TITLE
chunky fingers trait no longer prevents modular computer use

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

what the title says

## Why It's Good For The Game

its annoying
it doesnt amount to anything
it doesnt make sense to make the job that needs the tablet the most (engineers) not able to use tablets
you can literally just cheese it by removing your gloves, putting the tablet in your pocket and putting your gloves back on

## Changelog

:cl:
balance: chunky fingers trait (from insulated gloves) no longer prevents modular computer/tablet use
/:cl:

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
> no, take your gloves off you lazy shit.

This is not how you run an open source project.

**Comment by thegman254** [comment]
> no, take your gloves off you lazy shit.

Devs like you are the reason we can't have nice things.

**Comment by Pickle-Coding** [comment]
Was there some Reddit post or something? Why are people necroposting all of a sudden?

**Comment by optimumtact** [comment]
anime avatars so probably a /vr/ thread

**Pull request closed without merging**
