### PR TITLE
Stun combat """""overhaul"""""

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I want to test merge it again because it's been a few months and it was pretty funny last time

Can't stun people who are already stunned

### CODE REVIEW

**Comment by ChangelingRain** [comment]
how about reducing incoming stuns based on however many stuns you already have

**Comment by Shapsy** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by 9600bauds** [comment]
I foresee the birth of the term "stuncamping"

**Comment by Cheridan** [comment]
stun + cuff still extends the stun into infinity so I don't know how much this will change anything, but worth a shot i guess

**Comment by Shadowlight213** [comment]
Fun times

**Comment by Ergovisavi** [comment]
I don't believe this is a good solution if only for the fact that player stun timers are invisible and unreliable due to server tick rates, meaning determining how long someone has been stunned isn't great.

Seems like a band-aid.

**Comment by KorPhaeron** [comment]
@Ergovisavi 

Probably everything will be a bandaid as long as we have our real time tile based combat. Kind of a weird system to work with.

**Comment by PKPenguin321** [comment]
literally the worst PR ever will expand later once round ends

**Comment by Durkel** [comment]
Boy, I Sure do love how my shitty telebaton can't keep someone down so I'm forced to just beat the every living fuck out of the criminal I catch as detective. Might as well just load .357s in my gun as this rate.

**Comment by TechnoAlchemisto** [comment]
This fucking suuuucks as sec. Your taser sucks because you can't follow up baton anymore, flashbangs suck because they make everyone in the room immune to a real stun and guarantees saxxing.

**Comment by AdamElTablawy** [comment]
>get a tazer from warden

>taze

>cuff

Done. No biggie.

Besides, if you're arresting people as a detective you suck ultra dong. The only time a detective is actually gonna be arresting someone and not be megahitler is if the guy's a murderer/trying to kill the det and you have your hilarious stun+stamina gun for that.

**Comment by Durkel** [comment]
> Done. No biggie.

Besides, if you're arresting people as a detective you suck ultra dong. The only time a detective is actually gonna be arresting someone and not be megahitler is if the guy's a murderer/trying to kill the det and you have your hilarious stun+stamina gun for that.

Right, I'll continue to arrest people especially those with a ebow or those who have shot me with a syringe gun, you can keep running being worthless and crying about someones play style. Any way it stands the you don't always have enough time to handle a situation with just one stun, and reapplying it incredibly dangerous while knocking the piss out of them isn't.

**Comment by AdamElTablawy** [comment]
both of the examples you listed are things i said i wouldnt get buttmad over a detective arresting someone over but ok

also i repeat

hilarious stamina + hardstun gun

and you can ask the warden for a tazer or stunbaton

dont whine that you cant handle a fully equipped traitor with your shitty whacking stick at roundstart with 0 effort

**Pull request closed without merging**
