### PR TITLE
Claymore sprite update

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

God these sprites were old.

## Why It's Good For The Game

They're kind of all over the place ingame so I felt it was about time they got an update.

Screenshot 2020-02-09 18 46 42

## Changelog
:cl:
imageadd: Redid the claymore sprites to look a little better.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Fecc, I'll fix this later.

**Comment by Tharcoonvagh** [comment]
what

**Comment by Fikou** [comment]
claymores have those cool cross thingies
image

**Comment by necromanceranne** [comment]
I tried my darn hardest to make it look good with those quillions but it always came out looking like arse. It's just too tiny.

**Comment by necromanceranne** [comment]
This will return in a bit.

**Pull request closed without merging**
