### PR TITLE
Changes the gold tile sprite

### PR DESCRIPTION
**Pull request by Lexorion**
It didn't look golden enough so I changed it. People won't make these most of the time anyway since it's a waste of gold but who cares! Also makes the tile consistent with the other station tiles (no thick lines between the tiles)
pr image
EDIT:updated the image

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Please make a new tile object sprite too that one is just random pixels

**Comment by GunHog** [comment]
**S W A G**

**Comment by ChangelingRain** [comment]
Also i notice the shine effect isn't consistent across multiple tiles; the shine doesn't create a line across each tile if you look at it

**Comment by Lexorion** [comment]
@ChangelingRain okay,I'll change the object sprite and make the shine form lines in a moment

**Comment by Bawhoppen** [comment]
:-1: thumbs down not because I don't like the sprite, but I think the craftable tiles should be simple and plain, and while this is beautiful, you should make it a different recipe or something

**Comment by ExcessiveUseOfCobblestone** [comment]
F A N C Y

**Comment by Iamgoofball** [comment]
memez

**Comment by scoopscoop** [comment]
It looks a bit noisy

**Comment by bgobandit** [comment]
https://www.youtube.com/watch?v=Cgoqrgc_0cM

**Comment by Iamgoofball** [comment]
@Lexorion when you get the chance drop me a meme-o on coderbus, I have a golden project for you

**Pull request merged**
