### PR TITLE
Event Horizon rifle resprite

### PR DESCRIPTION
**Pull request by MelokG000**
## About The Pull Request

changes Event Horizon rifle sprite
image
## Why It's Good For The Game

event horizon rifle using esniper sprite looks very strange
## Changelog
:cl:
image: Event Horizon Anti-Existential beam rifle is now actually  looks like a mass destruction cannon
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
Too much pillowshading imo, makes it look blurry.

**Comment by xKREKSx** [comment]
lol1-export
animation

**Comment by CRITAWAKETS** [comment]
doesn't change the held sprites and worn sprites making them look very out of place with the glowing green gun in comparison

**Review by ArcaneMusic — CHANGES_REQUESTED** [review]
Check your tests, you're missing a backsprite now.

**Pull request closed without merging**
