### PR TITLE
Refactor Toggle Weapons

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Again

### CODE REVIEW

**Comment by KazeEspada** [comment]
BAD BAD BAD BAD BAD BAD. All the same stupid reasons, two handed weapons are unmaintanable as shit.
Put it on an action button like chameleon functionality.

**Comment by lzimann** [comment]
even more action buttons? there is too much already

**Comment by Supermichael777** [comment]
this doesn't change the functon at all looks like it just makes them object oriented what are you smoking kaze

**Comment by KorPhaeron** [comment]
>people telling me it's bad to remove copypaste

???

**Comment by KazeEspada** [comment]
No, it makes them a typepath with a functionality that is extra and not important. This means making an object that is toggleable and should inherit from something else will require MORE copypaste.

**Comment by KorPhaeron** [comment]
aaaaaaaaaaaaaaaaa

**Pull request closed without merging**
