### PR TITLE
Makes fedoras look better

### PR DESCRIPTION
**Pull request by MelokG000**
## About The Pull Request

Some fedoras are one pixel from perfection, this PR fixes that
## Why It's Good For The Game

If a hat looks good, people will use it
## Changelog
:cl:
image: fedoras are now one pixel lower (not all of them)
/:cl:

### CODE REVIEW

**Comment by Jezzared** [comment]
Foolishly, i thought this would move fedoras UP one pixel to make them work better with most hairs.

Instead you've done the opposite, and exacerbated the problem for hair that reasonably SHOULD look good with a fedora, but doesn't because it pokes over the back of the hat.

You can even see this in the Spy Diff right above me.

**Comment by Livrah** [comment]
Ingame screenshots before and after, please

**Comment by MrMelbert** [comment]
> Ingame screenshots before and after, please

image

**Review by Wallemations — CHANGES_REQUESTED** [review]
Fedoras already suffer from being too far down with most hair styles to the point of clipping, this ain't a great fix to be honest.
This is an inherent flaw with a lot of our hats and hairs obviously

**Comment by the-orange-cow** [comment]
Fedoras should float several inches above the head, levitated by the power of the fedora wearer's own euphoric enlightenment.

**Comment by MrMelbert** [comment]
If you want to move it down without looking ugly you would need to make the hair not clip through. 

But straight up applying `hidehair` would look bad in a lot of places, like the above screenshot test. 

One solvable way is, in theory, masking the hair below a point. So hair ABOVE the fedora does not render but hair BELOW does.

**Comment by MrMelbert** [comment]
image

**Pull request closed without merging**
