### PR TITLE
 Fixes cryo overlay system 

### PR DESCRIPTION
**Pull request by nicbn**
This fixes a bug that causes the occupant overlay to be added twice when the occupant not human.

### CODE REVIEW

**Comment by nicbn** [comment]
a / x = a * y
Where y is 1 / x
a * y is faster on byond

Old factor is x
New factor is y

**Comment by XDTM** [comment]
Don't forget to change the upgrades so the sleep time doesn't increase with upgrade tier

**Comment by nicbn** [comment]
a is the upgrade factor
a / x and a * y
In both cases a doesn't need to be changed

**Comment by banthebantz** [comment]
Is it worth a hit to readability though? The difference is surely very minor.

**Comment by nicbn** [comment]
Factor means that it multiplies, not that it divides.
So this already increases readability I think.

**Comment by ninjanomnom** [comment]
Factor means divide, coefficient is multiply

**Comment by RemieRichards** [comment]
>'a number or quantity that when multiplied with another produces a given number or expression.'

**Comment by nicbn** [comment]
> Factor means divide, coefficient is multiply

Nope. Sixth grade math.

https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables/cc-6th-evaluating-expressions/a/terms-factors-and-coefficients-review

Coeffient is the constant part, factor is any part that multiplies. As we use variables instead of defines, we call the variable factor.

What divides is the divisor.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
