### PR TITLE
Voodoo dolls now actually have a chance of ousting the user when doing certain actions

### PR DESCRIPTION
**Pull request by silicons**
Hint chance added to force movement/say.

### CODE REVIEW

**Comment by Repukan** [comment]
Why?

**Comment by Wilchenx** [comment]
grudgecode

**Comment by Repukan** [comment]
lmao

**Comment by Shadowflame909** [comment]
Wasn't it intended that it'd only reveal you when you do a lethal action. Like setting them on fire or being harmful. Voice changer is better than this rare piece of dumb garbage.

I also never figured out how to get an item that would go into the doll, and take one out to replace it.

**Comment by kevinz000** [comment]
item should be traceable if you force someone to do something.

**Comment by Wilchenx** [comment]
>item should be traceable if you force someone to do something.

>and remote view.

🤔

**Comment by Shadowflame909** [comment]
The only way to obtain it is the necropolis tendril. Or tc trade?

**Comment by davethwave** [comment]
I love messing with people when I get the chance of getting this item. I mostly get them to talk about how much they love cheese but still.

**Review by Cyberboss — APPROVED** [review]

**Comment by Dorsisdwarf** [comment]
>Approving a kevinz "i got fucked over" pr

**Comment by davethwave** [comment]
The only BIG harmful thing I guess that this could be used for is using the step when someone is surrounded by chasms/BOH bomb holes, poking it with a needle when the person only has about 5 health left, or burning it in the same situation which can be easily solved and tells you where the doll is in either situations.

**Pull request closed without merging**
