### PR TITLE
adds a dumb reference to arrows

### PR DESCRIPTION
**Pull request by PKPenguin321**
Fixes https://github.com/tgstation/tgstation/issues/20459

### CODE REVIEW

**Comment by Niknakflak** [comment]
I dont get it

**Comment by PKPenguin321** [comment]
https://wiki.teamfortress.com/wiki/Skewer

**Comment by Delimusca** [comment]
no skymeme ref in sight, all is well
shame tf2 is very dead.

**Comment by ike709** [comment]
https://youtu.be/b7XDbzxpGJM

**Pull request merged**
