### PR TITLE
Maps load in the center of Z-level instead of bottom-left corner

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Reopen of https://github.com/tgstation/tgstation/pull/67857 as it became stale and autoclosed.

Z levels are 255 by 255 tiles, but only 235 by 235 area is accessible because the 10-tile margins are reserved for smooth transition between space levels (essentially no-go area) 
The levels were loaded with x and y offsets set as 1, regardless of the level bounds.
So when you load a custom DMM or just a map that is smaller than 255x255 and doesn't take into account these smooth transition margins, its western and southern part was cut.

This PR makes it so that stations and custom maps are always placed in the center of the z-level.

This has no effect of the 255 by 255 maps, but smaller maps, like runtime station or custom ruins loaded as stations, will not require to have the smooth transition margin tiles reserved in DMM. And they will not end up having parts in the inaccessible area.

This inaccessible area is highlighted on the screenshots below.

### Before:
before

### After:
after

## Why It's Good For The Game

You can now properly load any space ruin as a custom map without it being fucked up by map cropping.

## Changelog
:cl:
fix: The maps are now placed in the center of Z level to avoid having parts getting into the inaccessible area
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
what if a map was larger than 255x255

**Comment by MTandi** [comment]
> what if a map was larger than 255x255

Doesn't matter, it takes `world.maxx` and `world.maxy`

**Comment by MTandi** [comment]
> what if a map was larger than 255x255

If you're talking about the case when the map is bigger than the world size - I don't know about such case, but I guess that it will be cropped on all sides evenly instead of cropped on top and right.

**Comment by Time-Green** [comment]
> what if a map was larger than 255x255

Byond doesn’t allow that, all z’s need to be the same size

**Pull request merged**
