### PR TITLE
Fixes jaunters

### LINKED ISSUE #34424: Jaunter is broken
It doesn't teleport you if you run into it anymore.

roundid: 81883

### PR DESCRIPTION
**Pull request by silicons**
Fucking event wormholes ugh. Who even had the idea of making these a subtype of them?? 
Fixes #34424 
Closes #34425

### CODE REVIEW

**Comment by Buggy123** [comment]
But my PR reverts the severe balance changes put in by the PR that broke them in the first place.

**Comment by Kromgar** [comment]
OKAY. SO THATS WHY THE JAUNTER PORTAL DIDNT TELEPORT ME TO THE STATION

**Comment by kevinz000** [comment]
Megafauna being able to teleport through jaunters but not regular portals is not a balance change, it's a bug introduced by my refactor.

**Comment by Buggy123** [comment]
So what? So what.

Mate, do you know how many bugs-turned-balance changes there are? A consistent bug is literally just a feature. I'm not even kidding. You could call more than 50% of what ends up in issues a "feature", albeit a undesirable one.

Please, explain how exactly it being a bug that was introduced makes it _not_ a major balance change. Need I remind you that 

# cloning used to be a bug before it was officially implemented as a feature

**Comment by alexkar598** [comment]
Totally unrelated but how did people manage to clone before it was implemented?

**Comment by alexkar598** [comment]
Totally unrelated but how did people manage to clone before it was implemented?

**Comment by Buggy123** [comment]
Either they used the glitch or they didn't, and it was permadeath. Depends on the time period, plus i'm not a expert on early SS13 history.

**Comment by lordpidey** [comment]
You used to revive people with genetics by turning em into a monkey and back.

**Comment by Hathkar** [comment]
Please keep it so Megafauna can still travel through jaunter portals.

**Comment by Buggy123** [comment]
>Please keep it so Megafauna can still travel through jaunter portals.

**Pull request merged**
