### PR TITLE
Improve name generation

### PR DESCRIPTION
**Pull request by spessman-007**
## About The Pull Request

Name generation has been improved.
There is now a 50% chance to use US name lists, and a 50% chance to use Mexican name lists. Name sources have also been updated.
Name sources:
US names: https://data.world/uscensusbureau/names-from-census-1990
Mexican names: http://datamx.io/dataset/muestra-de-nombres-y-apellidos-comunes-en-mexico
Unisex names: https://fivethirtyeight.com/features/there-are-922-unisex-names-in-america-is-yours-one-of-them/

## Why It's Good For The Game

It would make for better name generation, and overall make the game more interesting.

## Changelog
:cl:NewSta
tweak: Improved name generation - new name lists backed by statistics, and you can also be Mexican now!
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Why do we have country split lists at all

**Comment by libre-x** [comment]
Because it allows you to have different name origins

**Comment by spessman-007** [comment]
So basically, it would allow you to have a different origin of your character. It's much better than mixing all names in one bunch, and allows for more variety imo

**Comment by Qustinnus** [comment]
This seems really out of place especially if its 50% of the time,  this should include more countries or be based off of something besides pure chance.

**Comment by trollbreeder** [comment]
Not even british names included smh

**Comment by spessman-007** [comment]
What countries would you recommend?

**Comment by nemvar** [comment]
This sets a really stupid precedent imo. It adds weight to names when previously there was none. And the names weren't even really "US". They are english or anglicized names which makes sense considering the projects language IS english. If you feel like we could profit from anglicized version of spanish or mexican names, feel free to add them.
Linking name selection to real existing countries also, for example, justifies the one albanian player adding a 3 kilobyte file of traditional albanian names to the codebase which isn't reasonable imo.

**Comment by Ryll-Ryll** [comment]
I mean increased variety for names in general would probably be a boon, though I agree splitting them based on country wouldn't make much sense for the far far far future. Maybe make additions to the name lists based on most common names globally? Who even knows where our current name list comes from

**Comment by spessman-007** [comment]
Might consider a better way or doing this later

**Pull request closed without merging**
