### PR TITLE
pkpenguin's changes to teslagrilles completely undid the entire point of it

### PR DESCRIPTION
**Pull request by Iamgoofball**
people are now just throwing stuff at electrocuted grilles to bypass them again

this reverts it back to proper teslagrille

### CODE REVIEW

**Comment by PKPenguin321** [comment]
This adds blowing up the bridge/brig/HoP office/CE office by throwing a screwdriver at it

When you said you'd look into it I didn't think you meant waiting a bit and reverting it

Just up the range if it's such a huge problem

**Comment by ChangelingRain** [comment]
Plus this doesn't actually fix it properly; it will still always still tend to the lower left if it has multiple targets at the same distance from it, this just did the closeness checking wrong so that was more obvious.

**Comment by GunHog** [comment]
Make it shock the _mob which threw the item_, and only that mob.

**Comment by TechnoAlchemisto** [comment]
we could just revert tesla grilles

**Comment by Aloraydrel** [comment]
Le hardcore xD

**Comment by Firecage** [comment]
IB4 non conductive glass once again causes everyone in the vicinity to get shocked due to fucking electric arcs. NON CONDUCTIVE GLASS.

**Comment by optimumtact** [comment]
People prefer the nerfed version goof.

**Comment by Cheridan** [comment]
Just add an arg to tesla_zap that makes it not explode things, jeez. 

don't kill the one actual environmental hazard on the station

**Comment by PKPenguin321** [comment]
>Just add an arg to tesla_zap that makes it not explode things, jeez.

i tried doing this but didn't find a very easy way to do it, if somebody could then that would be really awesome. this PR doesnt do that though

**Comment by Bawhoppen** [comment]
don't thumbsup your own PR goof

**Comment by PKPenguin321** [comment]
or do because reddit upvotes matter for the merging process now

**Comment by optimumtact** [comment]
Goof can you do the needful please

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/tgstation/pull/20448 made a proper arg to make tesla zaps not explode stuff so if you want to redo this but add this proper arg in feel free

**Pull request closed without merging**
