### PR TITLE
Adds clown eggs to the game.

### PR DESCRIPTION
**Pull request by harmonyn**
## About The Pull Request

You can stamp eggs with a clown stamp, similar to how you can use a crayon on them (the rainbow crayon is taken, so I just went with what bedsheets do) to create one of several kinds of clown egg. The eggs are functionally no different than the colored eggs we already have, just clowny.

Thanks to Pugnacious-Gnome for the sprites.

## Why It's Good For The Game

Clown eggs are a [real clowning tradition](https://www.smithsonianmag.com/travel/gallery-london-houses-dozens-clown-egg-portraits-180968914/) that has existed for decades. If West of Loathing has them we should have them too. Honk.

## Changelog
:cl: bandit
add: Nanotrasen's clowns have begun to preserve their images by stamping eggs with their NT-issued clown stamps. This is fine and normal.
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
thank you for the mental image the title of this pr will no doubt put in people's heads

**Comment by fluffe9911** [comment]
egg clown cluwne when

**Comment by Farquaar** [comment]
>implying clowns don't hatch from eggs

**Comment by Pugnacious-Gnome** [comment]
> egg clown cluwne when

New Piskel-3 png

**Comment by PKPenguin321** [comment]
was thinking West of Loathing while reading the title and am glad it was mentioned. :+1:
(chameleon stamps should make the egg have a tiny chance of becoming one of those mutant clowns)

**Comment by Kitfox88** [comment]
Thought I could lay clown eggs, but this is pretty great too.

**Comment by Pugnacious-Gnome** [comment]
Honestly, just take out my overpowered meme clowns and add in this wholesome educational content

**Comment by bgobandit** [comment]
merge when

**Pull request merged**
