### PR TITLE
Med kiosks no longer runtime with no ID equipped

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
Title

## Why It's Good For The Game
Runtimes bad

## Changelog
:cl:
fix: Med Kiosks no longer runtime when no ID is equipped.
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
why didn't it indent, one sec

**Comment by MCterra10** [comment]
HOW WAS THIS POSSIBLE!
Inconsistent indentation in the same file! Tab indents in some areas, two space indentation in others, and 4 space indentation in still others!

**Comment by Ty-the-Smonk** [comment]
I mean we are supposed to use tabs

**Comment by ArcaneMusic** [comment]
Now in my defense it was my first real feature.
...On the flip side I have no idea how this even compiled the first time, holy shit, sorry :X

**Comment by actioninja** [comment]
nice indentation

**Pull request merged**
