### PR TITLE
Adds quicksmite hotkey

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl: 
admin: You can now use Ctrl + Shift + F + U to bring up the smite menu for the mob closest to you
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
inb4 admins come in here and make low quality jokes

**Comment by Armhulen** [comment]
What an awful hotkey jesus

**Comment by praisenarsie** [comment]
you're an awful hotkey

**Comment by Spaceinaba** [comment]
more like CRTL + FUCK

**Comment by arsserpentarium** [comment]
How about shift+E+C+T? at least it is more easy for hand.

**Comment by Cyberboss** [comment]
What does ECT stand for? (in case you weren't aware the only reason I'm doing this is for the meme)

**Comment by MoreRobustThanYou** [comment]
**E**le**CT**ricity

**Comment by kevinz000** [comment]
or we can just rightclick...

**Comment by arsserpentarium** [comment]
It is just unused combinatuon of 4 keys,which unlikely to be pressed accidently. Also it is much more easy to press with one hand.

**Comment by Buggy123** [comment]
>tries to smite someone

>has to press hotkey and click at the same time

>presses ctrl, shift, F, and U with one hand to smite someone

Totally worth the broken hand.


On my keyboard there are 2 main ways I can press this with one hand. I can shift my chair to the right a bit, turn my hand 45 degrees to the right, press ctrl and shift with my pinky, stretch my thumb to U, and fold my index finger inward and press F with the top of it.

Alternatively, I can move to the opposite side of my keyboard, or stand above the keyboard and twist my arm, and hit ctrl and shift with my thumb, F with my index finger, and U with my ring finger.

I honestly can't think of a worse hotkey that isn't just actively being malicious. You literally cannot press this without being a finger contortionist or fucking _standing up or moving the keyboard around_. Pick. Something. Else.

**Comment by Cyberboss** [comment]
No one appreciates the meme

**Comment by praisenarsie** [comment]
i do ;(

**Pull request closed without merging**
