### PR TITLE
Locks up Insulated gloves in cargo

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
tweak: The insulated gloves crate has been locked
add: Space china's grey market reacted quickly to the news and has attempted to undercut legitimate suppliers. Purchase from such dubious sources is of course prohibited.
/:cl:

These things are supposed to be rare and act as cargo's go to power-gaming item. This change should have happened a long time ago to be honest.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
>caring about ID locks
>Not simply smashing the crate open

Do you even cargonia?

**Comment by Supermichael777** [comment]
It makes it clear that this is a restricted item. Its become far too accepted for non-engineers to have these "just in case" and security policy has rolled over on it. They are and have always been a restricted access item; but the as written policy as written and the design of the game were pointing in different directions. Hopefully this makes their status more clear.

**Comment by Shadowlight213** [comment]
moongloving is not ok I see

**Comment by Iamgoofball** [comment]
cargo players should look up degloving on google to prepare for this

**Comment by Cyberboss** [comment]
Aren't there glove in primary tool storage?

**Comment by Supermichael777** [comment]
one pair on coin access yes

some maps sprinkle them in maintenence but >mapedits

**Comment by Hatfish** [comment]
What prompted you to make this change?  How is it supposed to improve anything beyond making it slightly harder for people to get insulated gloves right away?
also,
> liking your own PR

**Comment by kevinz000** [comment]
yeah no

**Comment by PKPenguin321** [comment]
Not necessary

**Comment by optimumtact** [comment]
Strong no from me, what even prompted this?

Flow of insulated gloves into the round from cargo is an important part of making the station fly apart after the round gets boring

**Comment by MrPerson** [comment]
Pick your poison. Either it's accepted that cargonia walks around wearing gloves or accepted that cargonia walks around wearing gloves and has some way to break open crates

**Comment by FantasticFwoosh** [comment]
How to solve crybaby arguement.

> Buy gloves (and file report correctly) as QM/HOP, make a note of who takes the gloves if it starts getting vultured by techs, preferably do it in secret.
> Hack the autolathe and print off a electropack and wire
> Find a spare box & rig with the electropack & wires
> Put spare gloves you are not wearing/delicate things inside
> Call security and punish any future illicit glove ordering
> Keep box out of reach of cargo-tech manchildren for shipping off for points.
(Extra points, rig the box to issue a signal to you or a spare PDA on your person when opened for surveillance with a mouse trap signaller)

Also without cargo to import gloves & no way to make gloves without some machine or recipe everyone else suffers on the station in the name of balance, particularly engineering in a similar situation we used to have with wires before being cargo import only.

**Pull request closed without merging**
