### PR TITLE
Maze Shuttle

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
get good

So the idea behind this shuttle is that there will be a teleporter effect at the first red square, you'll be dumped into that big green area above and have to run some sort of maze/gauntlet, and then come back out the other end at the other red square.

The big maze area will load with the shuttle, but otherwise be static/stay out in space while the shuttle (in blue) flies. You'll therefore have the 3 minutes of docked time and 2 minutes of transit time to complete the maze and get back on the ship.

I have the code for this figured out, the hurdle I've hit now is I don't actually like mapping very much and am not very good at it, so I'm opening this PR in the hopes of attracting someone with a vague amount of mapping skill.

If there's no interest I'll close it in a couple days and maybe finish it myself.

### CODE REVIEW

**Comment by kevinz000** [comment]
wew

**Comment by Aloraydrel** [comment]
second!

**Comment by Kevak** [comment]
I like this idea.

**Comment by Cyberboss** [comment]
This needs to kill everyone still in the maze before the centcomm docking for maximum memage

**Comment by pubby** [comment]
just use dreamstation as the maze :^)

**Comment by ChangelingRain** [comment]
mazes are awful and engineers would win because mesons

**Comment by Cyberboss** [comment]
Have the teleporter qdel mesons and scanner goggles then. They don't need em anymore

**Comment by PKPenguin321** [comment]
is this purchasable or an admin thing because it feels like an admin thing

**Comment by KorPhaeron** [comment]
@ChangelingRain 

You already figured out how to beat mesons for clock stuff though.

But yeah, it might have to be a teleporter maze that randomizes or else people could just memorize/meta it

**Comment by Cyberboss** [comment]
Easy make 1 maze and several (I'm talking upwards of 10) dead ends that each could spawn an in/out teleporter.

**Comment by Niknakflak** [comment]
space maze

**Comment by ExcessiveUseOfCobblestone** [comment]
HAS SCIENCE GONE TOO FAR

**Comment by KorPhaeron** [comment]
I found someone who said they want to help map this, I'll hopefully have a real PR in a few days

**Pull request closed without merging**
