### PR TITLE
Mech Refactor and Rebalance

### PR DESCRIPTION
**Pull request by ghost**
Refactors:  The explosion mechs make on destruction, the enter time, and exit time are now variables.
 
:cl:
balance:
- Mechs always explode on destruction, instead of 30% of the time
- Exiting a mech takes time, punches and equipment are disabled during, and moving interrupts this.
- Noncombat mechs take 5s to enter, 5s to exit
- Combat mechs take 10s to enter, 10s to exit, and trigger a 1 tile heavy explosion when destroyed, which instantly kills the pilot.
/:cl:

The purpose of this PR is to nerf mechs without actually nerfing their direct combat power. Mechs will still wreck you in combat, but aggressors have an easier time ambushing the pilot during repairs, and entering a mech requires you to bet your life versus theirs: you cannot just pop out of your nearly dead mech mid-combat and continue fighting on foot.

### CODE REVIEW

**Comment by subject217** [comment]
Not sure what your expected outcome with this PR is. Making combat mechs guaranteed to kill the pilot upon destruction just further encourages the shitty self defense mech killbaiting mentality. And it doesn't really make mechs much weaker, since the pilot is usually fucked if his mech dies anyway. The enter and exit change isn't that bad an idea though.

**Comment by zxaber** [comment]
FYI, my Ripley Rework PR (#42828) already makes the enter time a variable, since I lowered it for the MK-I Ripley. I didn't actually change it on any other mech, though.

**Comment by py01** [comment]
It's pretty easy to kill a sec officer, steal his baton, disabler, ect then get back in. Then, if your mech is going to go down, you can pop out instantly to engage the target on foot. 

The severe explosion on combat mechs might be too severe, and can be toned back if I get enough support for it.

**Comment by Adanps** [comment]
Not sure if this is a good idea, but you might look at applying a stun to a mech pilot when their mech is destroyed instead.

**Comment by py01** [comment]
@zxaber well we coincidentally used the exact same variable name and stuff for the exit delay, so there shouldn't be much issue with merge conflict

**Comment by necromanceranne** [comment]
Seems fine to me. Might be nice to have some kind of emergency escape pod for nukie mechs though since they would want to be able to keep fighting even if their mechs blow. Otherwise, with nukie mechs being super vulnerable to ions compared to the crew counterparts, nukie mechs seem like putting too much into one basket.

**Comment by py01** [comment]
@necromanceranne Explosion strength is mech specific, so I can give the syndie mechs no explosion if I get support for that.

**Comment by ATH1909** [comment]
> FYI, my Ripley Rework PR (#42828) already makes the enter time a variable, since I lowered it for the MK-I Ripley. I didn't actually change it on any other mech, though.

Friendly reminder that zxaber's PR is ready, required some spritework to make, and is good, but no maintainers have bothered to actually look at it (I asked oranges to look at it, but he said that he wasn't interested in mechs and refused to) and (test)merge it.

**Comment by Tlaltecuhtli** [comment]
@subject217 thats a policy problem

**Comment by Tlaltecuhtli** [comment]
i would say adding an emergency eject as a module itself that you can add at cost of a slot would be cool

**Comment by zxaber** [comment]
Policy problem or not, Subject _does_ have a point. If we make mechs explode always, then there will be no non-lethal way to arrest a mech pilot. For better or for worse, any combat involving a mech **will** be to the death.

Honestly, I think we should go the other way. Remove mech explosion, but hard-stun the pilot if they're in the mech when it dies. If you have lethal intentions, you can still wreck the downed pilot, or else you cuff and arrest them for being the shitter they are. Plus, a mech near death couldn't just run into a crowd and force collateral damage/kills.

I've taken some time to think about the changes. Ten seconds to enter and then another ten exit a combat mech sounds like it's gonna suck, especially if you just need to hop in for something small like enabling maintenance mode. I don't know if the longer enter time is really going be a nerf to mech combat so much as it would be just an anti-QoL change. An exit delay sounds fine (ten seconds will still probably feel like ages, but eh).

Also, if we're balancing around not being able to pop in and out of the mech, can we change the malfunction event to occur at a lower HP remaining? It normally happens at what, 50% integrity? Depending on what event you roll and what's going on, the event can basically just be the end of your mech, at least for the time being. You certainly aren't going to continue fighting in a mech that can't walk straight or has a burning cabin.

**Comment by ExcessiveUseOfCobblestone** [comment]
this is going to merge conflict with 42828 so prob want to relax with this one until the other gets finished.

**Comment by 4dplanner** [comment]
Good changes, but I agree that a (LONG) stun might be more reasonable.

**Comment by 4dplanner** [comment]
Also once you add an exit time there's not a real need for a huge entry time, it's already substantial.

**Comment by py01** [comment]
I think i fucked something up with the conflict resolution, so I'm just closing and making a new one

**Comment by ExcessiveUseOfCobblestone** [comment]
lol

**Pull request closed without merging**
