### PR TITLE
Adds a stethoscope to the interceptor to prevent the vault safe from being an instawin

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
balance: A single stethoscope can now be found on the Syndicate interceptor, so if all the others are destroyed, operatives can still access a nuclear disk in the vault safe.
/:cl:

I've heard a few instances of this happening, and while amusing, I imagine it's also fairly frustrating having to sit and accept that there's no chance at winning this round because the safe was cracked and the disk put in, even having had my operative pref. disabled for a few months now. Because of that, I put a stethoscope in the interceptor medbay on a table near the surgery area.

### CODE REVIEW

**Comment by Spaceinaba** [comment]
now all we need is to let them buy a thermal drill with tc for MAXIMUM PAYDAY MEMES

**Comment by Anonmare** [comment]
https://www.youtube.com/watch?v=PfjVIrVw8b4

**Comment by ma44** [comment]
Should probably also add a piece of paper that explains how to open the safe, as just using a stethoscope probably won't do it.

**Comment by Xhuis** [comment]
The stethoscope is in the interceptor medbay since it's a medical implement. It's not meant for cracking safes realistically (even if mechanically it exists for that purpose) so having a paper that explains how to crack them is kind of silly!

**Comment by Robustin** [comment]
Dumb snowflake change. 

Crew has to keep the stethoscope around too or else they can't open the safe and the Nukeops get a victory anyway. 

So it's not even an "instant win" if the Ops manage to secure the safe. Either the crew flees and loses or they try to get a stethoscope to the vault to recover the disk and the Ops can loot it off their corpse. 

Using the safe for disk security is a really time-consuming and difficult tactic that requires a lot of communication and coordination to avoid a Syndicate win. I can testify first-hand that if the Ops secure the vault it's extremely difficult to recover since if the crew doesn't have bombs there's almost no weapon that can dislodge multiple syndies. 

The best tactic here for either side is gittin' gud.

**Comment by vuonojenmustaturska** [comment]
The safe is not guaranteed to be openable with a stethoscope. It might be, but it might not.

**Comment by Xhuis** [comment]
As a codebase, we have historically been against either side winning with flat-out zero mechanical way to change that victory state. Though I'm unsure if it's true, a friend told me that one of the rounds in which this happened, the disk was counted as secured. For those reasons, I stand by this.

**Comment by praisenarsie** [comment]
safe needs a refactor

**Comment by BeeSting12** [comment]
This is the wrong way to go about it. Add a thermal drill that takes 300 seconds to get through. Occasionally, it will jam up which takes five seconds to fix. The drill always spawns on the op ship and can be used to destroy anything.

**Comment by AnturK** [comment]
I'd rather not validate this as legitimate feature/tactic.

**Comment by ShizCalev** [comment]
What @vuonojenmustaturska said, #12474 - safes can't even always be opened.

**Comment by Xhuis** [comment]
@AnturK @ShizCalev What would y'all rather be done about it? It's already being used commonly on-station by this point.

**Comment by Robustin** [comment]
Commonly? I'm literally the only person I've seen do it.

**Comment by Xhuis** [comment]
A friend of mine has told me three separate rounds of it happening, and even if it wasn't happening, allowing it to exist and knowingly allowing it to be countered by just destroying the stethoscopes to irrevocably screw over the ops is silly.

**Comment by ShizCalev** [comment]
Can't they just blow up the safe? They're given free explosives, are they not?

**Comment by Robustin** [comment]
Its explosive proof. There are other ways to destroy the safe but you have to put some effort/TC into it. 

Also your argument is that the crew is spending several minutes cracking the safe and then INTENTIONALLY destroying the stethoscopes to give the Nukeops a FREE VICTORY because the victory message says MINOR instead of MAJOR? 

You're creating a solution for a problem that doesn't exist.

**Comment by Bawhoppen** [comment]
Bad change for reasons Robustin probably explained in his walls of text

**Comment by InsaneHyena** [comment]
Disk in the safe counts as a major crew victory. For some reason.

**Comment by imsxz** [comment]
I'm shocked that anyone here is arguing that it's completely fair to force a syndie minor victory, rather than giving due credit to the victor, whichever faction it may be.

Additionally, the argument that the crew intentionally destroying all the stethoscopes giving the nukies a "FREE VICTORY" is also invalid as fuck. Have you ever opened a safe IRL? They have this neat function where if you know the combination, you can open it without a stethoscope. The captain can easily just tell everyone (not over comms/announcements) the code to the safe, and usually there will be at least one person alive to open it.

Nukies should have SOME way to open safes up. If not via stethoscope, the drill idea seems good with the side bonus of payday memes. If it were my decision, I'd give them the stethoscope along with 1 or more drills to buy from their uplink.

**Comment by Xhuis** [comment]
Even though there's evidence to suggest it's a major crew victory, even if it was a minor Syndicate one, forcing any side's win with no way to counter it is, to me, not good design. It means the crew can win with no effort and the Syndicate can only sit and watch if it's a major victory for the crew, and that if it's not, then the Syndicate can just bumble around because they have to settle with a minor victory. Reports on it conflict, but the person who reported this to me said that it was a major crew victory.

**Comment by kevinz000** [comment]
just murderbone everyone and make them sit out for 15 minutes ez.

**Comment by Xhuis** [comment]
People seem opposed to this for the most part, so I'll close this down and give some thought to another solution. It's definitely commonplace, as I played in two nuke op rounds last night and both times people shouted for the captain to put the disk in the safe. Still! Maybe I'll do a drill or something.

**Pull request closed without merging**
