### PR TITLE
Atmos re-Defined

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
This PR takes the atmospherics.dm in _DEFINES and split it into several files to lower the mess, increase readability and improve on the code for later uses
Also added some docs here and there

## Why It's Good For The Game
Less clutter in files

### CODE REVIEW

**Comment by timothymtorres** [comment]
This was desperately needed.  SS13 has so many looooooong files that need to be broken down into smaller chunks,

**Comment by LemonInTheDark** [comment]
Values that are core to the simulation, or defines that are used by other defines should be inside a _core file. I also think this is a bit too split up, but ahhh

**Comment by Ghilker** [comment]
Ehhhh that would be too much of a clutter, there are plenty of defines that are core of the sim but are working into very separated part of it, like turf, breathe, reactions, pipenet, etc. Don't get used to shitcode @LemonInTheDark follow the new norm

**Comment by LemonInTheDark** [comment]
> 
> 
> Ehhhh that would be too much of a clutter, there are plenty of defines that are core of the sim but are working into very separated part of it, like turf, breathe, reactions, pipenet, etc. Don't get used to shitcode @LemonInTheDark follow the new norm

It's important both for readability and because stuff that's used by other stuff needs to be defined first, or the game won't compile.

**Comment by Ghilker** [comment]
> It's important both for readability and because stuff that's used by other stuff needs to be defined first, or the game won't compile.

I moved the clothing defines inside the mob interaction and grouped a bunch of files into one main "atmos_core"

**Pull request merged**
