### PR TITLE
Make basic id cards constructable.

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
Make basic id cards constructable in service fab after some researtch.

## Why It's Good For The Game
Sometimes we need more cards then we have.

## Changelog
:cl:
add: Make basic id cards constructable in service fab after some researtch.
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
I’m not sure what the HoP could be up to that requires more than the ~35 spares he has on most maps but I’m sure it’s nothing good.

**Comment by Dennok** [comment]
Generally i make this not for HoP.
And what if someone steal all spares?
And we can remove some roundstart spares.

**Comment by nemvar** [comment]
Should be orderable from cargo imo.

**Comment by cacogen** [comment]
harmless pr; doesn't deserve to be thumbed down

**Comment by FloranOtten** [comment]
>And we can remove some roundstart spares.

well that's just editing the game to suit your PR.

Harmless PR though, merge with average speed

**Comment by actioninja** [comment]
w/e this is really inconsequential.
I would prefer it cargo orderable but it can always be moved if cargo gets the revamp it needs.

**Pull request merged**
