### PR TITLE
Virology Doors can now be emagged.

### PR DESCRIPTION
**Pull request by Ikarrus**
It removes all access restrictions.

### CODE REVIEW

**Comment by GunHog** [comment]
I thought this already was the case with all door control buttons? Huh.

**Comment by Ikarrus** [comment]
They were rewritten but some features were missing.

**Comment by Aranclanos** [comment]
is that copypasted?

**Comment by Ikarrus** [comment]
Is there a problem?

**Comment by Aranclanos** [comment]
if its copypasted, then yes

**Comment by Iamgoofball** [comment]
i don't see any copypaste here

**Pull request merged**
