### PR TITLE
Start removing the legacy projectile system [WIP]

### PR DESCRIPTION
**Pull request by optimumtact**
This will require fixing reflectors to properly calculate reflection angle.

### CODE REVIEW

**Comment by octareenroon91** [comment]
I thought we'd at least obtained the insight for the fix.

**Comment by Bawhoppen** [comment]
I am working on it, the code that one guy gave me doesn't work properly so now I have to learn how to actually do it

**Comment by optimumtact** [comment]
I will try to get back to this at some point

**Comment by optimumtact** [comment]
the calculation of reflection just requires using the projectiles world angle unit vector and doing a dot product with the reflection plane angle unit vector to calculate the outside of the reflection angle, which is (90 - the product of the dot vector). then adjusting that to match the rotation of the reflection plane itself

in case anyone wants to do it

**Comment by Bawhoppen** [comment]
@optimumtact i was able to get it to always shoot back at me

**Pull request closed without merging**
