### PR TITLE
Ports some low level New()s to Initialize

### PR DESCRIPTION
**Pull request by Cyberboss**
Reverts tgstation/tgstation#24210

Original PR:
#24132

@ChangelingRain !!!!

### CODE REVIEW

**Comment by ChangelingRain** [comment]
MAKE IT OBVIOUS WHEN YOUR PR IS BROKEN JEEZ

**Comment by Cyberboss** [comment]
Vacation till Sunday

**Comment by optimumtact** [comment]
why did i close this?

**Comment by RemieRichards** [comment]
@Cyberboss quick question, why doesn't ```turf/Initialize()``` call ```atom/Initialize()```? (instead choosing to duplicate it's logic making the whole not-calling-..() pointless)

**Comment by Cyberboss** [comment]
Proc call overhead

**Comment by RemieRichards** [comment]
That's disappointing, I'm going to have to duplicate some stuff now.

**Pull request merged**
