### PR TITLE
Medbay Removed

### PR DESCRIPTION
**Pull request by mrhugo13**
Citruses tastes better then Oranges anyway

### CODE REVIEW

**Comment by mrhugo13** [comment]
this probably took more time then it should've ngl

**Comment by Jordie0608** [comment]
Ironically, replacing medbay with open space thus exposing some of the most walked corridors to depressurization and giving everyone oxyloss will only make medbay more useful.

**Comment by Ghommie** [comment]
Basically what the guy above said. Let's not repeat the Paradise Station medbay removal testmerge meme.

**Comment by mrhugo13** [comment]
Don't worry guys i sealed all the entrances off with walls so that medbay is exactly as useful as it was before to the average greytider.

**Comment by mrhugo13** [comment]
smh totalitarianist travis at it again

**Comment by optimumtact** [comment]
The intent is to provide players with a sense of pride and accomplishment for unlocking medical healing. As for cost, we selected initial values based upon data I pulled out of my ass. Among other things, we're looking at average per-player  heal rates on a daily basis, and we'll be making constant adjustments to ensure that players have challenges that are compelling, rewarding, and of course attainable via gameplay. We appreciate the candid feedback, and the passion the community has put forth around the current topics here on Discord, Reddit, our forums and across numerous social media outlets. Our team will continue to make changes and monitor community feedback and update everyone as soon and as often as we can.

**Comment by mrhugo13** [comment]
hahahah

**Comment by CitrusGender** [comment]
image

**Pull request closed without merging**
