### PR TITLE
Adds missing races to mob spawn list

### PR DESCRIPTION
**Pull request by 81Denton**
A bunch of species were missing, this makes spawning them for testing easier.

### CODE REVIEW

**Comment by lordsaladin** [comment]
Moff.

**Comment by AlexTheSysop42** [comment]
I think clockwork servant is also missing

**Comment by 81Denton** [comment]
Oh yeah, stargazers and luminescents as well

**Review by SpaceManiac — APPROVED** [review]

**Comment by KorPhaeron** [comment]
Need a non offensive PR to test the hippie webhoook with so merging before 24 hours

**Comment by praisenarsie** [comment]
image

our plan is coming together

**Pull request merged**
