### PR TITLE
Shitty ideas thread: Round 1

### PR DESCRIPTION
**Pull request by RemieRichards**
:cl:
add: Added the ability to choose where your uplink spawns, choose between the classic PDA, the "woops you don't actually have a PDA" fallback Radio uplink and the brand new Pen uplink!
add: Emagging a sleeper now randomises the buttons, the buttons remain the same until randomised again so you can "learn" the new button config if you're a masochist, Inject omnizine but realise far too late that it's all morphine, woops! (Note: Epinephrine can always be injected, regardless of chem levels, this means if something !!FUN!! ends up on the Epinephrine button, it will always be injectable!)
add: A New weapon for clown mechs, the Oingo Boingo Punch-face! it's a giant boxing glove that extends out on a spring and sends atoms flying (including anchored ones and things that make no sense to move because -clowns-)
/:cl:

I dug through all 40 or so pages of the shitty ideas thread, I found about 12 that are worth attempts, here's the first 3.

Oingo Boingo (No embeds because xbawks  #heug)
http://i.imgur.com/R8OVKuQ.gif
http://i.imgur.com/MCjsbX1.gif

### CODE REVIEW

**Comment by lzimann** [comment]
god damnit stop adding stuff to gamemodes aaaaaaaaaaaaa

**Comment by ma44** [comment]
>pen uplink
>can be rotated by anyone, proving that whoever has the pen is obviously a traitor and only has 360 possible combinations of 1 number

**Comment by RemieRichards** [comment]
@ma44 1/360 odds are much better at random-guessing than other uplinks, yes, but you can fit a pen in a lot of places you can't fit a pda or radio (and no, I'm not talking about your butt)

**Comment by ma44** [comment]
It's impossible to tell the difference between a pda with an uplink, or no uplink

You can tell if the pen has an uplink by pressing Z

**Comment by RemieRichards** [comment]
@ma44 No you can't, are you dumb? ALL PENS show the rotate screen, you'd have to guess the 1/360, which again, as I've said, is more likely to guess than the much lower odds (that I once calculated but forgot) for the PDA, but the pen, again, has it's own advantages.

**Comment by lzimann** [comment]
should probably open a pr for each thing so it's cleaner/better feedback...

**Comment by RemieRichards** [comment]
not happening.

**Comment by Mervill** [comment]
I love that the reinforced glass smooths as it's being thrown XD

**Review by Razharas — DISMISSED** [review]
PRS SHOULD BE ATOMIC PRS SHOULD BE ATOMIC PRS SHOULD BE ATOMIC PRS SHOULD BE ATOMIC PRS SHOULD BE ATOMIC PRS SHOULD BE ATOMIC PRS SHOULD BE ATOMIC PRS SHOULD BE ATOMIC PRS SHOULD BE ATOMIC

**Comment by ShadowDeath6** [comment]
On yog emagged sleepers inject 30u of every chem they have into you and shut down, that might be a bit more lethal than 100u of whatever chem rolls epinephrine button

**Comment by RemieRichards** [comment]
@ShadowDeath6 1. the idea as it was from the thread was for random buttons, and I'm in favour of that and 2. the point isn't for lethality, it's to annoy people and allows traitors to remove one of the "cheap" methods of healing more easily and less noticeable than just dismantling them.

**Comment by ShadowDeath6** [comment]
I'm not saying that it's better or worse, just providing some reference.

**Comment by RemieRichards** [comment]
Fair enough, I didn't mean to come off stand-offish, just to provide my reasoning as to why things are as they are.

**Comment by Supermichael777** [comment]
No moving anchored atoms it breaks shit badly

**Comment by Iamgoofball** [comment]
hook me up with the rest of the ones remie

**Comment by XDTM** [comment]
Meteorshot already pushes unpushable stuff, and it's more frequent than HONK mechs. And walls are turfs, not structures.

**Comment by MrStonedOne** [comment]
Maintainers who don't subject themselves to their own rules really irks me.

**Comment by Thunder12345** [comment]
**A**_T_**O**_M_**I**_C_ **P**_R_**S**

**Comment by RemieRichards** [comment]
@MrStonedOne Considering I've already stated my reasons, and the fact we HAVE had bundle PRs based on such themes before, seems rather unfair to deny it to myself, purely because I'm a maintainer and not goof or cheridan.

**Comment by RemieRichards** [comment]
Although, reading now what you wrote in the SDQL2 pr I'm less angry.
you just have a tendency to come off as passive aggressive, when really you're just trying to help here.

my point still mostly stands though, and some point about lose themes should be either explicitly allowed or denied on our rules.

**Comment by KorPhaeron** [comment]
I think it is nice to have them in separate PRs in this case at least, would probably be nice to clarify the rules though

**Pull request closed without merging**
