### PR TITLE
Justice can no longer decapitate people.

### PR DESCRIPTION
**Pull request by hyperjll**
Justice is no longer capable of decapitation, it's 'finish him' move simply increases the dismember chance to 100% and 200 damage rather than decap.

## About The Pull Request

It's become pretty clear to a lot of people that this mech is super strong, and because I'm a coder (and coders hate fun) I'm suggesting removing some of the more bullshit capabilities of this mech while still keeping it strong.

## Why It's Good For The Game

Getting dashed into or hit once and instantly getting decapitated (instant death) is NOT fun. Especially when the mech can dash across an entire room or go invisible and sneak up on you for a free hit. Having your limbs re-attached is NOT easy, and takes the involvement of someone else entirely just to get ONE limb back, the worst this mech should ever be capable of is 'nuggeting' someone.

## Changelog

:cl:
balance: The "Justice" mech can no longer decapitate it's victims. It's finishing move now guarantees dismemberment and instant death instead of decapitation.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
erm pr bloat

**Comment by hyperjll** [comment]
> erm pr bloat

It's all for a Justice nerf, i assure you.

**Comment by SmArtKar** [comment]
Checking for soul when gibbing is an extremely weird solution to an already questionable problem

**Comment by hyperjll** [comment]
> Checking for soul when gibbing is an extremely weird solution to an already questionable problem

True, but i just wanted people to not get round removed by a Justice + Mining Drill combo.

**Comment by SmArtKar** [comment]
> > Checking for soul when gibbing is an extremely weird solution to an already questionable problem
> 
> True, but i just wanted people to not get round removed by a Justice + Mining Drill combo.

Then remove gibbing entirely, there's no reason as to why it should gib knocked players. Leave gibbing for xenomorphs - that's a neat reference

**Comment by Loafin34** [comment]
ided pr

**Comment by Blacklist897** [comment]
gibbing with the drill is cool

**Comment by EnterTheJake** [comment]
Isn't that mech really bad tho? it has 180 hp and when they unsheath its sword it moves as slow as a durand.

Plus even stealth all of its attacks have like a 2 seconds delay.

**Comment by hyperjll** [comment]
> Isn't the mech really bad tho? it has 180 hp and is a melee only mech with the same movement speed of a Durand.

No, the mech is actually really strong. (Also, 200 HP.)

**Comment by Kiromaka** [comment]
> > Isn't the mech really bad tho? it has 180 hp and is a melee only mech with the same movement speed of a Durand.
> 
> No, the mech is actually really strong. (Also, 200 HP.)

Well, the mech wasnt used a lot, like really. It only appeared in a few rounds. I dont know how a strength of a mele only, (200hp), no movement speed mech can be determined with such a small dataset.

**Comment by Deultus** [comment]
"I didn't even know there was such a thing, but I want to take it away." I just have a question, why?
With the same logic, you can remove charred corpses or destruction from any kind of explosions.

**Comment by GPeckman** [comment]
I don't know how you managed to make a salt PR over a feature you've never even seen in game (gibbing with the drill), but you somehow managed it.

Anyways, if your concern is that the drill could be used with the justice mech, just make it so that the drill can't be put on it. Most mech weapons are already restricted from non-combat mechs, so just do something similar with the drill and justice.

**Comment by hyperjll** [comment]
> "I didn't even know there was such a thing, but I want to take it away." I just have a question, why? With the same logic, you can remove charred corpses or destruction from any kind of explosions.

I don't follow your reasoning here, i wouldn't even use such logic to get those removed (nor do i want them to be). I'm just asking for mech drills to NOT gib people.

**Comment by GPeckman** [comment]
> I've actually seen this in-game, you apparently can't read.
> 
> Also, i tried that solution first and couldn't for the LIFE of me get that to work. I'm still looking into it despite everything.

The Justice isn't supposed to be able to get any arm attachments whatsoever. But after testing this in-game, it appears that you can attach weapons. I'll open a bugfix PR for it in a little while.

**Comment by hyperjll** [comment]
> > I've actually seen this in-game, you apparently can't read.
> > Also, i tried that solution first and couldn't for the LIFE of me get that to work. I'm still looking into it despite everything.
> 
> The Justice isn't supposed to be able to get any arm attachments whatsoever. But after testing this in-game, it appears that you can attach weapons. I'll open a bugfix PR for it in a little while.
> 
> Edit: there we go, fix PR up. No need for the drill nerf anymore.

Huh. Good call.

**Comment by GPeckman** [comment]
I wasn't sure about the other nerf in this PR, but while I was looking at the Justice code to fix the bug I noticed that it deals 60 damage with its melee. That's a lot of damage. So now I'm kinda fine with a small nerf.

**Comment by Xackii** [comment]
If he does not cut off the head, he will endlessly repeat the final attack, trying to simply press on spaceman in stun or crit(
сonsidering that you removed check to see if spaceman has a head). You should make it do 200 damage and cut out all organs or something like finish_attack as a finishing attack and not just a regular attack with delay.

**Comment by hyperjll** [comment]
> If he does not cut off the head, he will endlessly repeat the final attack, trying to simply press on spaceman in stun or crit( сonsidering that you removed check to see if spaceman has a head). You should make it do 200 damage and cut out all organs or something like finish_attack as a finishing attack and not just a regular attack with delay.

Done.

**Comment by zoomachina** [comment]
Are you making this pr because the xenobio powergame you do every round is countered by decapitation?

**Comment by hyperjll** [comment]
> Are you making this pr because the xenobio powergame you do every round is countered by decapitation?

Xenobio powergame? Uh, no. My grievances when i initially made this PR was from watching a crew get absolutely destroyed by this mech in an unfair manner, this round in which i had played as a Chemist. I have yet to do xenobio and face off against this mech.

**Comment by Ghostkokos** [comment]
Coders: "hat this mech is super strong"
Gamers: "Dies from laser spam After the slightest scream In radio where mech after 5 minutes, how did he create a mech"

**Comment by hyperjll** [comment]
> I'm sorry but you have to be delusional to consider justice a strong mech. It's speed is abysmal, health is absurdly low and it gets fucked by a single person with a laser gun. Not to mention the whole gimmick of this mech is to be great at melee combat (it isn't but that's due to it just being garbage rather than by intention), how exactly does it make sense that a giant mech blade is incapable of cutting one's head off, not only that but removing such a feature would make the mech be useful in what exactly? The whole selling point and the only reason someone would wish to waste their 10tc for a garbage mech is to at least have it be able to behead people. This is either a severe case of 'ided pls nerf' pr or you haven't actually used the mech, as you would realize just how of a stinking pile of metal it is.

Again, the reason i made this PR is because a lot of people requested it after getting slammed in a round by this thing and i have indeed used the mech before on my own time. Yes, i see the twenty+ thumbs down emotes but I'd like to imagine many of the people pissed at this mech don't hop onto github to complain here. Just a reminder: this mech can go invisible and dash across the screen hitting all it dashes through.

**Comment by hyperjll** [comment]
> > I'm sorry but you have to be delusional to consider justice a strong mech. It's speed is abysmal, health is absurdly low and it gets fucked by a single person with a laser gun. Not to mention the whole gimmick of this mech is to be great at melee combat (it isn't but that's due to it just being garbage rather than by intention), how exactly does it make sense that a giant mech blade is incapable of cutting one's head off, not only that but removing such a feature would make the mech be useful in what exactly? The whole selling point and the only reason someone would wish to waste their 10tc for a garbage mech is to at least have it be able to behead people. This is either a severe case of 'ided pls nerf' pr or you haven't actually used the mech, as you would realize just how of a stinking pile of metal it is.
> 
> Again, the reason i made this PR is because a lot of people requested it after getting slammed in a round by this thing and i have indeed used the mech before on my own time. Yes, i see the twenty+ thumbs down emotes but I'd like to imagine many of the people pissed at this mech don't hop onto github to complain here. Just a reminder: this mech can go invisible and dash across the screen hitting those it dashes through.

**Comment by Exester509** [comment]
> > Are you making this pr because the xenobio powergame you do every round is countered by decapitation?
> 
> Xenobio powergame? Uh, no. My grievances when i initially made this PR was from watching a crew get absolutely destroyed by this mech in an unfair manner, this round in which i had played as a Chemist. I have yet to do xenobio and face off against this mech.

Wait so this was an ided PR all along? Nuke this negative GBP PR!

**Comment by Jacquerel** [comment]
Following #84925 this mech can no longer equip drills (it was never supposed to be able to in the first place).  
Given that this seems to be a very unpopular PR and also largely seems to be about a combo (this mech + drill) which no longer exists, is this change still necessary?

**Comment by hyperjll** [comment]
> Following #84925 this mech can no longer equip drills (it was never supposed to be able to in the first place). Given that this seems to be a very unpopular PR and also largely the discourse in these comments seems to be about a combo (this mech + drill) which no longer exists, is this change still necessary?

Eh, personally i'd still prefer it and i think a bunch of other people would... but it's certainly not a high priority for me anymore.

**Comment by Exester509** [comment]
> > Following #84925 this mech can no longer equip drills (it was never supposed to be able to in the first place). Given that this seems to be a very unpopular PR and also largely the discourse in these comments seems to be about a combo (this mech + drill) which no longer exists, is this change still necessary?
> 
> Eh, personally i'd still prefer it and i think a bunch of other people would... but it's certainly not a high priority for me anymore.

I doubt the existence of that "bunch of other people" considering there's like a single comment kinda supporting it/not caring

**Comment by Kiromaka** [comment]
> Eh, personally i'd still prefer it and i think a bunch of other people would... but it's certainly not a high priority for me anymore.

image
  -"Hey you like this ?"
 -"Ye , you ?"
 -"Me too."

**Comment by ShizCalev** [comment]
image

**Pull request closed without merging**
