### PR TITLE
Makes the "nothing happened!" option of drake's blood vaguely more entertaining/frustrating

### PR DESCRIPTION
**Pull request by Incoming5643**
By turning those who hit it into a lizardperson approximating the appearance of an ash drake.
avatar_134682b6a0bb_128
# fiveminutecommits

### CODE REVIEW

**Comment by GunHog** [comment]
YES YES YES YES YES!

**Comment by lzimann** [comment]
what is the point of using that shit if it has a chance of turning you into a goddamn lizard

**Comment by MMMiracles** [comment]
@lzimann whats the point of anything if it has any potentially remote downsides?

**Comment by WJohn** [comment]
You understand that people *will* willingly gimp themselves if only to make themselves look cooler, right?

**Comment by GunHog** [comment]
>@lzimann whats the point of anything if it has any potentially remote downsides?

Chance to become:
- A skeleton
- Lavaproof
- A **DRAGON**

Come on, now.

**Comment by Incoming5643** [comment]
Become big dragon, elation
Become little dragon, disgust

**Comment by Kromgar** [comment]
Where all the gray markings an ash drake has

**Comment by Incoming5643** [comment]
There aren't exactly things like that in the lizard customization sprites

**Comment by ChangelingRain** [comment]
I suggest `#FEE5A3` for the eyes and `#A02720` for the skin, should look a lot more drake-y.

**Comment by GunHog** [comment]
You should give it wings, to be honest.

**Comment by Incoming5643** [comment]
There aren't exactly things like that in the lizard customization sprites

**Comment by Kromgar** [comment]
Oooh you could totally give it mini ashdrake wings kinda like potion of flight

**Comment by Incoming5643** [comment]
I'm already sitting on a huge sprite project for lizards that WJohn provided for me, I ain't gonna ask for wings too.

**Comment by ChangelingRain** [comment]
Oh, that's darker than I expected, try `#AF2921` for the skin.

**Comment by WJohn** [comment]
Wings could be done first, but if incoming updates lizard sprites and adds digitigrade legs, then this potion could at least give you those.

**Comment by Incoming5643** [comment]
`>Quick lackadaisical pull running against serious major pull I've been putting off`

Oh god I've been trapped.

**Comment by KorPhaeron** [comment]
I'm gonna merge this as is, if people want to edit it later they are free to make their own PR

**Comment by lzimann** [comment]
can i make a pr to revert it? :^)

**Comment by Incoming5643** [comment]
@ChangelingRain 
avatar_134682b6a0bb_128
?

**Pull request merged**
