### PR TITLE
PRs with the "Good First PR" label now award 6 GBPs

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Exactly what it reads on the tin.

## Why It's Good For The Game
I've brought it up with the maintainers, and Oranges said it should award the same amount of a feature so first-time contributors don't get overly penalized by it.

## Changelog
N/A

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
I expect my 6 GBP that I earned two years ago in the mail by saturday.

**Comment by ninjanomnom** [comment]
Just raise the starting gbp value, there's no point in going about it roundabout like this.

**Comment by optimumtact** [comment]
> Just raise the starting gbp value, there's no point in going about it roundabout like this.

I want to punish those who do not make good first pr's

**Comment by Ghommie** [comment]
Oh right, I could do what ninjanomnom said instead, tho I'll take a snooze first.

**Comment by deathrobotpunch** [comment]
me who started coding a month ago ):

**Comment by SomeoneYouProbablyKnow** [comment]
time to make a few new accounts, boys.

**Comment by moocowswag** [comment]
We need a “first good pr” label

**Comment by deathrobotpunch** [comment]
how about a “good pr” label

**Comment by SuperNovaa41** [comment]
> how about a “good pr” label

-15 gbp

**Pull request merged**
