### PR TITLE
crashed ship update

### PR DESCRIPTION
**Pull request by Dennok**
small update of crashed ship.
Remove a walls under airlocs, all airlocs changed to titanium, miror simmerty fixes.

:cl:
tweak: small update of crashed ship
/:cl:

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Screenshots?

**Comment by Bawhoppen** [comment]
Good PR. What motivated you to care about this ruin btw?

**Comment by Dennok** [comment]
I hate walls under doors,,, all other i deal passingly.
Screenshots show nothing, i think. you cant see walls under doors on screenshots.

**Comment by Dennok** [comment]
crashedshipup
Add shuttlers.
Next i want to make shuttle from it.

**Comment by Dennok** [comment]
Next i want to make shuttle from it, but not sure about this.

**Review by SpaceManiac — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
