### PR TITLE
Nerfs bag of holding explosions.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Changes the BOH explosion radius to a 5x5
boh

## Why It's Good For The Game

The meme has been ran into the ground and being able to delete your entire screen just by pressing a button is well... I don't think I have to explain that.

I thought about bringing back lord singulo and capping his size at 2 and making him despawn after 30 thirty seconds. If you prefer that, please tell me.

## Changelog
:cl:
balance: Bag of holding explosions are now much smaller.
/:cl:

### CODE REVIEW

**Comment by kicking99** [comment]
I think they should be smaller, but 5x5 seems a bit too small still.

**Comment by AdamElTablawy** [comment]
that's tiny, it should at least be a fair bit bigger

**Comment by anconfuzedrock** [comment]
people would whine about the death of the meme but I think even just 30  seconds of a level 1 singulo would be far better. the problem with this that made the old singulo arguably MORE fair is that when someone used it you had a chance to react and run, while when someone uses boh bombs now it's insta you die.

**Comment by datorangebottle** [comment]
> people would whine about the death of the meme but I think even just 30 seconds of a level 1 singulo would be far better. the problem with this that made the old singulo arguably MORE fair is that when someone used it you had a chance to react and run, while when someone uses boh bombs now it's insta you die.

Actually, only the person using the boh bomb instantly dies. The other people have a chance to escape using the ladders.

**Comment by wesoda25** [comment]
rocks idea is cool but until he decides to PR it ill upboat this

**Comment by lordpidey** [comment]
While this is a good idea, I think the limited singularity is a better one.

**Comment by anconfuzedrock** [comment]
yeah orangebottle they can escape using the laddder. they'll be stranded in a fucking cave on lavaland and it'll take em at least 15 minutes unless they have a hardusit, in which case it's more of a long shot. and boh bombs to the shuttle are just a massive "fuck you" to everyone ever.

**Comment by datorangebottle** [comment]
> yeah orangebottle they can escape using the laddder. they'll be stranded in a fucking cave on lavaland and it'll take em at least 15 minutes unless they have a hardusit, in which case it's more of a long shot. and boh bombs to the shuttle are just a massive "fuck you" to everyone ever.

I'll reiterate- the only one who can use this without dying permanently is the xenobiologist. Also, one of the ladders tends to go through the station as far as I'm aware. The main problem with this mechanic is griefers and traitors who just don't care anymore. This change doesn't stop BOH bombs on the shuttle, and it still has a huge impact in that situation because the shuttle is a very small area.

Also, boh bombs have a huge tell- someone carrying a bag of holding or two, and/or wearing one. This change is super unnecessary.

**Comment by nemvar** [comment]
Well, I just nerfed the explosion radius by 85%. I think it will make quite a big difference in how much these bombs effect.

A big problem was that they DIDN'T have a huge tell. Someone could come peeking from the edge of the screen and instantly press a button to delete everything he sees. That's not a huge tell, there's barely any time to react. Now you have the time actually notice that a guy is running around with two BOHs before you are in his striking range.

**Comment by datorangebottle** [comment]
> Well, I just nerfed the explosion radius by 85%. I think it will make quite a big difference in how much these bombs effect.
> 
> A big problem was that they DIDN'T have a huge tell. Someone could come peeking from the edge of the screen and instantly press a button to delete everything he sees. That's not a huge tell, there's barely any time to react. Now you have the time actually notice that a guy is running around with two BOHs before you are in his striking range.

It's really easy to spot before they've even come close to his target- anyone telling on them can absolutely ruin their plans. It's like seeing someone carrying a TTV or putting it into their boh. Super obvious, and there are very few situations where a BOHbomb actually gets used to begin with!

Also, 85% is a massive nerf that makes it borderline useless, because not only do you gib, but you hit less targets and they're just as likely to survive.

**Comment by wesoda25** [comment]
Yeah I’d say scale the size up to 7x7 or something.

**Comment by 4dplanner** [comment]
`makes it borderline useless`

it's a meme, why does it have to be useful?

**Comment by datorangebottle** [comment]
> `makes it borderline useless`
> 
> it's a meme, why does it have to be useful?

Because you're taking something that is currently useful when you can circumvent the downsides and/or use it for an appropriate situation(like xenos / cult bases), and making it pretty terrible in comparison.

**Comment by 4dplanner** [comment]
That doesn't answer the question, you've just said currently it is useful

**Comment by nemvar** [comment]
This is the wizard buff you have all been waiting for.

**Comment by datorangebottle** [comment]
> That doesn't answer the question, you've just said currently it is useful

Because having more viable options in a game where things get continuously nerfed and removed(thus restraining/removing those options) is a good thing. Because having options as to how you want to destroy a part of the station is also pretty cool. Because bags of holding interacting should be pretty disastrous, and it's a really cool reference to the original item.

**Comment by XDTM** [comment]
A meme by itself is only fun until it gets old, and then is completely useless; a meme that has also an actual use does not suffer the same fate.

That said, the ideal middle ground is making it useful enough that you'd see it rarely, making it a fun surprise, rather than making it too strong, resulting in it becoming meta and getting old _really_ fast.

**Comment by Dawson1917** [comment]
now instead of deleting you from the round to kill at best 7-8 people gathered at escape you can delete yourself from the round to... delete cloning, and maybe one person. why? boh bombs aren't prevalent, and are only useable more than once by xenobiologists who create golems. anyone carrying two bohs is normally instantly attacked on sight as is

if you're nerfing this, make the void spread out from the user's position to its maximum size so people can still run away if they aren't directly next to the person bombing, while a large area like escape can still be sabotaged until someone with an RCD/metal rods comes and fixes it in 10 seconds flat. you know, rather than make it entirely useless

**Comment by Daxxed** [comment]
I would honestly be surprised if an actual antag used these anyway.
99% of the time it's a griefer, newfriend or ghostrole bombing with these.
Nothing of value was lost, good PR

**Comment by BeloneX** [comment]
where's the ided tag.

**Comment by bigfatbananacyclops** [comment]
golems are a pain in the arse

**Comment by knacker48** [comment]
Is there be a way that you could make it so it doesn't immediately cover the screen, but rather have it take a few seconds to expand out, giving you a window to run away if your paying attention? I think that would be a better alternative

**Comment by nemvar** [comment]
I don't know why people think that mass printable screen deleters are a good idea. To be honest, I can't even begin to understand why that would possibly the case.

**Comment by ATH1909** [comment]
> I'll reiterate- the only one who can use this without dying permanently is the xenobiologist.

Botany and their replica pods say "hi".

**Comment by wesoda25** [comment]
> I don't know why people think that mass printable screen deleters are a good idea. To be honest, I can't even begin to understand why that would possibly the case.
Id say because they’ve always been incredibly powerful. This would be the first PR to establish them as something weak and pointless. With the removal of autocloning, its quite literally giving up your entire round for one blow. Just scale it up a bit and they’ll be happy, I agree that its dumb in its current state.

**Comment by optimumtact** [comment]
they were a funny reference back when the server was smaller, now they're just a giant pain in the ass

**Comment by Cw3040** [comment]
And now they'll be a 5x5 pain in the ass

**Comment by datorangebottle** [comment]
> Botany and their replica pods say "hi".

Except that requires the cooperation of multiple people who have generally don't have to listen to eachother, so no, that's very very very very unlikely to work. Meanwhile, benobio can do it very reliably- all they need is one golem, and that golem has to obey their orders.

**Comment by YakumoChen** [comment]
Bring back singulo if you are just going to nerf this to the ground

**Comment by wesoda25** [comment]
I actually got teh idea of it'd be sort of cool if doing this created a bluespace anomaly, which basically just does random shit, shooting out chaos gravity bolts, maybe randomly spawning tears in fabric of reality around it, randomly shooting projectiles it. The issue is that type of coding is wayyy beyond me.

**Comment by Tlaltecuhtli** [comment]
my idea would be either make the terraforming slower so you can escape it or when the dude puts the bag in the bag it would give a do_after with a message and an audio warn that he is doing it instead of insta death because you didnt notice that the dude who entered your screen has 2 bohs

**Comment by NoxVS** [comment]
Just remove it entirely. This is a stupid meme reference that requires no effort to instantly remove multiple people from the round. You can’t even fully detect it, a bluespace bodybag can hold a BoH. When the bodybag is folded up and placed in another BoH the effect is triggered. Even with the normal BoH they can just hit yes before anyone realizes what is happening and boom everyone caught in it is effectively dead.

**Comment by HomocidlePancakes** [comment]
1)People walking around with two BoHs are super obvious 
2)Give it a channel and bolded text in chat if you concerned with this having no counterplay

**Comment by NoxVS** [comment]
As I mentioned earlier you can put a BoH in a bluespace bodybag and fold it up. This can be secretly stored in I believe your pocket. Take the folded bodybag out of your pocket, put it in your worn BoH, hit yes, everyone dies.

**Comment by necromanceranne** [comment]
It's also really big and instant unlike actual bombs which have a delay on the outer edges and may actually rng not kill you instantly if you're lucky and weren't near the epicenter.

I don't want to get rid of the reference entirely because I'm a dnd nerd but the actual effect in dnd is not actually that big either. The proposed size seems about appropriate for what would the actual dimension rift created by putting a bag of holding into a bag of holding.

**Comment by FloranOtten** [comment]
I would say slow the explosion so it expands instead of nerfing to oblivion. (This seems to be a trend). With these it's not even a danger anymore. You can just send at most 24 people (provided the entire square is full) to lava land. Many don't even suffer the danger of being gibbed anymore.

**Comment by CPTANT** [comment]
The singularity felt a lot more balanced because it started small and you could actually escape it. The tear just instantly rips away the entire screen.

**Comment by XDTM** [comment]
It did not feel more balanced, although mostly because it was permanent and spelled the eventual end of the whole station once started

**Comment by ShizCalev** [comment]
image

**Pull request closed without merging**
