### PR TITLE
Removes air mix tanks

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
These air mix tanks pop up here and there, but noone ever uses them because they are shit. Replaces them in lockers/packs with the emergency/big oxygen kind where it makes sense.

## Why It's Good For The Game
Wasted space begone.

## Changelog
:cl: Skoglol
del: Replaced portable air mix tanks with standard oxygen tanks.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
yeah i've always hated these

**Comment by Anonmare** [comment]
For the record, this is removing the internal tanks, not the air cans in the event that some of you can't or won't read.

**Comment by Whoneedspacee** [comment]
it’s removing the air tanks and replacing them with oxygen tanks

**Comment by nemvar** [comment]
I used these things before. It was when I couldn't be bothered to cool my tank for the pneumatic cannon.

**Comment by kriskog** [comment]
> 
> 
> I used these things before. It was when I couldn't be bothered to cool my tank for the pneumatic cannon.

Just fill one from a blue pump, its better anyway. But yeah, just reiterating how useless these are.

**Comment by anconfuzedrock** [comment]
they're fucking emergency tanks so you don't die, they're not supposed to be good. and they last long enough too.

**Comment by Whoneedspacee** [comment]
he’s replacing them with normal oxygen tanks so not like thats an issue

**Comment by ShizCalev** [comment]
improve don't remove

**Comment by kriskog** [comment]
These don't fit our current breath system, as we dont need the n2 to breathe. The only way to improve them is make them pure o2, and we already got a tank like that.

**Comment by Poojawa** [comment]
Oxygen Toxicity was added to Citadel. It makes Ash Walkers choke and die in normal air comp. high pressure oxygen will do the same to you as well. 

:3

**Comment by 81Denton** [comment]
Airmix tanks are pointless bloat. If anyone ever adds oxygen toxicity (wyci), feel free to re-add these.

**Pull request merged**
