### PR TITLE
update layer manifold sprite

### PR DESCRIPTION
**Pull request by duncathan**
before: 
after:

### CODE REVIEW

**Comment by lzimann** [comment]
<details><summary>icons/obj/atmospherics/pipes/manifold.dmi</summary>
Key | Old | New | Status
--- | --- | --- | ---
manifoldlayer-f3|manifoldlayer-f3|manifoldlayer-f3|Modified
manifoldlayer-f2|manifoldlayer-f2|manifoldlayer-f2|Modified
manifoldlayer-f|manifoldlayer-f|manifoldlayer-f|Modified
manifoldlayer3|manifoldlayer3|manifoldlayer3|Modified
manifold_full_layer_long-f3|manifold_full_layer_long-f3|manifold_full_layer_long-f3|Modified
manifoldlayer-f1|manifoldlayer-f1|manifoldlayer-f1|Modified
manifold_full_layer_long2|manifold_full_layer_long2|manifold_full_layer_long2|Modified
manifold_full_layer_long3|manifold_full_layer_long3|manifold_full_layer_long3|Modified
manifoldlayer1|manifoldlayer1|manifoldlayer1|Modified
manifoldlayer|manifoldlayer|manifoldlayer|Modified
manifold_full_layer_long-f2|manifold_full_layer_long-f2|manifold_full_layer_long-f2|Modified
manifoldlayer2|manifoldlayer2|manifoldlayer2|Modified
</details>

**Comment by duncathan** [comment]
i forgot to do the pipe item to match oops

**Comment by lzimann** [comment]
<details><summary>icons/obj/atmospherics/pipes/manifold.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
manifoldlayer-f3|manifoldlayer-f3|manifoldlayer-f3|Modified
manifoldlayer-f1|manifoldlayer-f1|manifoldlayer-f1|Modified
manifold_full_layer_long3|manifold_full_layer_long3|manifold_full_layer_long3|Modified
manifoldlayer-f2|manifoldlayer-f2|manifoldlayer-f2|Modified
manifold_full_layer_long-f3|manifold_full_layer_long-f3|manifold_full_layer_long-f3|Modified
manifoldlayer2|manifoldlayer2|manifoldlayer2|Modified
manifoldlayer3|manifoldlayer3|manifoldlayer3|Modified
manifold_full_layer_long-f2|manifold_full_layer_long-f2|manifold_full_layer_long-f2|Modified
manifoldlayer-f|manifoldlayer-f|manifoldlayer-f|Modified
manifoldlayer1|manifoldlayer1|manifoldlayer1|Modified
manifoldlayer|manifoldlayer|manifoldlayer|Modified
manifold_full_layer_long2|manifold_full_layer_long2|manifold_full_layer_long2|Modified
</details>
<details><summary>icons/obj/atmospherics/pipes/pipe_item.dmi</summary>

Key | Old | New | Status
--- | --- | --- | ---
layer_manifold|layer_manifold|layer_manifold|Modified
layer_manifold1|layer_manifold1|layer_manifold1|Modified
layer_manifold3|layer_manifold3|layer_manifold3|Modified
layer_manifold2|layer_manifold2|layer_manifold2|Modified
</details>

**Comment by nicbn** [comment]
Everything in this sprite is wrong.

**Pull request merged**
