### PR TITLE
Increases CMO hypospray capacity + adds microdosing

### PR DESCRIPTION
**Pull request by googobbug**
## About The Pull Request

Increases the reagent capacity of the CMO hypospray to 60u and adds the ability to inject smaller amounts of reagents, like a dropper can.

You still only get 30u of omnizine, sorry.

## Why It's Good For The Game

The hypospray is pretty dogwater as a medical tool. The tiny 30u capacity means you'll be refilling it constantly, making it unattractive compared to medigels or pills for everything but murder. These changes solve that issue by making the capacity less miserable and also give it a unique niche of being able to efficiently administer medicines via microdosing.

## Changelog
:cl: Bumtickley00
balance: The CMO's hypospray now holds 60u, and can be set to inject smaller amounts of reagents
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
I can't think of a situation where i'd want to dose someone with only 2 or 4 units. 
1 unit is cool for formaldehyde and 3 units is cool for some niche chems but in between, Not really

**Comment by SomeoneYouProbablyKnow** [comment]
I mean. Let's be real, the hypospray is good. Refilling it is very easy, fast and not liks you are hurting for inventory space... ever.
But also since it's not an issue, nothing wrong with boosting its capacity. 

Although changing the dose can get a bit fiddly. You set it to 3 then forget you did that and have to z z z it back to five after 2 people don't wake up after you sting em. I'm pretty sure you can transfer reagents from the hypo easily anyway. And not like 1 to 5 units is ever a useful distinction 99% of the time.

**Comment by githubuser4141** [comment]
It'd be good if you could set it to pre-set amounts normally, and use a TGUI menu to set it to whatever you'd like (3, 7, 13.37)
That way it wouldn't add clutter to people who don't use it like that

**Comment by AdmiralPancakes1** [comment]
> I can't think of a situation where i'd want to dose someone with only 2 or 4 units.

> Although changing the dose can get a bit fiddly.

> add clutter to people who don't use it like that

Just changed the selection to only be 1, 3, and 5 to make it less annoying to flip through without losing too much functionality.

**Pull request merged**
