### PR TITLE
Fixes lizard faces and makes angel wings a little more standard

### LINKED ISSUE #18031: Lizard faces are broken again.
muh special snowflakes
tgstation bagil english 100 free lag capitalist bomb xix 2016-05-29 075755

### PR DESCRIPTION
**Pull request by Incoming5643**
Makes angel wings play nice with the rest of mutant parts and removes some minor snowflakication.

Fixes #18031

### CODE REVIEW

**Comment by Incoming5643** [comment]
Also @Shadowlight213 the side springs for angel wings are the same both open and closed (they both look open)

**Comment by RemieRichards** [comment]
>side springs

**Comment by Incoming5643** [comment]
I'd love to say that was autocorrect, but nope. Must have been thinking about springs when I typed that. Do not judge me.

**Comment by RemieRichards** [comment]
@Incoming5643 "Sprite", "Wings" -> "Sprite" + "Wings" -> "Springs"

**Comment by GunHog** [comment]
Why not make these things organs, so I can rip them off an angel or demon, then have them surgically attached to a new body?

**Comment by Bawhoppen** [comment]
@GunHog the time will come for special-dismemberment, but now is not that time fo snowflake

**Comment by Shadowlight213** [comment]
@Incoming5643 Technically intentional. Kor's gf only made the open sprites for the side, so I just used them for both open and closed.

@GunHog I mainly used species because I could hook in nicely with the already existing code and all the code would be generalized to the species datum. I'm not sure how to make it work as an organ, but I guess I can try at some point in the future. (The secret reason, is that I'd need a sprite for the item and I despise having to do any sort of actual art.)

**Comment by Incoming5643** [comment]
ok I figured that was the case I just wanted to make sure there wasn't a sprite for it that just accidentally didn't get committed

@RemieRichards get out of my head Charles

**Comment by RemieRichards** [comment]
join my school for mutants @Incoming5643, we could use people with "side springs" :P

**Comment by Shadowlight213** [comment]
@incoming5643 which layer did you move them onto btw?

**Comment by Incoming5643** [comment]
BODY_BEHIND_LAYER, BODY_ADJ_LAYER, and BODY_FRONT_LAYER

The northern facing sprite goes on BEHIND, the east/west goes on ADJ(ECENT) and the southern facing sprite goes on FRONT. With some creativity you can even create sprites that "curl around" other parts of the body to have parts appear both in front and behind, but this didn't need to be done for wings

**Pull request merged**
