### PR TITLE
Space heater actually turns On with a right click this time.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
I got bamboozled and this PR of mine https://github.com/tgstation/tgstation/pull/61334 isn't working as expected.
The Space Heater turns on but wasn't processing Atmos to change the temperature around itself.
This fixes that.

## Why It's Good For The Game
Fixing my stupid mistakes, also no GBP tag here please...

## Changelog

:cl: Guillaume Prata
fix: Space heater actually turns On with right click now, for reals this time!
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Test ze code

**Review by LemonInTheDark — APPROVED** [review]
If you wanna be extra based make turning on a space heater a separate proc so we don't make this mistake again

**Comment by GuillaumePrata** [comment]
> Test ze code

100% my fault for assuming it was a separate proc already.
> If you wanna be extra based make turning on a space heater a separate proc so we don't make this mistake again

I'm looking into it right now, I also found a issue that the Space Heaters are working forever even if their cells run empty so I will look into that too.
Just don't want to have something broken in game while I work on it.

**Comment by AlinaStarkova** [comment]
> > Test ze code
> 
> 100% my fault for assuming it was a separate proc already and only testing if it was turning ON and OFF.
> > If you wanna be extra based make turning on a space heater a separate proc so we don't make this mistake again
> 
> I'm looking into it right now, I also found a issue that the Space Heaters are working forever even if their cells run empty so I will look into that too.
> Just don't want to have something broken in game while I work on it.

wanna do something even more based? currently nobody anchors space heaters because why would they? how about if a space heater is anchored in place it will draw power from the APC and not its own battery, if the APC has charge of course, else when u anchored or the area its anchored in has no APC with a charge, it consumes battery like normal

**Comment by LemonInTheDark** [comment]
>I'm looking into it right now, I also found a issue that the Space Heaters are working forever even if their cells run empty so I will look into that too.
>Just don't want to have something broken in game while I work on it.

I can understand that, but I gotta be honest with you, it's not a huge issue 
image


> wanna do something even more based? currently nobody anchors space heaters because why would they? how about if a space heater is anchored in place it will draw power from the APC and not its own battery, if the APC has charge of course, else when u anchored or the area its anchored in has no APC with a charge, it consumes battery like normal

That'd be out of scope. I don't really like the idea either but we don't need to get into it here

**Pull request merged**
