### PR TITLE
Makes the combat shotguns (Aussec/Cycler) armor-slottable, compact shotgun beltable

### PR DESCRIPTION
**Pull request by Higgin**
## About The Pull Request

Makes the combat shotguns WEIGHT_CLASS_BULKY instead of WEIGHT_CLASS_HUGE. 

Gives the compact shotgun (the little one) the ability to fit on the belt-slot as well as a lower weapon_weight of medium.

## Why It's Good For The Game

Since the nerfing of improv shells, the addition of cheaper scatter laser shells, and the addition of the disabler SMG/laser carbine, shotguns have been in a weird but I personally think much healthier place.

They don't have the ability to shit out run-ending wounds for free. They do have a use as a slightly more EMP-insulated way of still bringing lasers to the fight (which are also countered with deflects.) They still have the assortment of interesting but very seldom-used and time-intensive techshells available, which are cool.

But.

There are three riot shotguns on each map that you can actually get roundstart and store on an armor slot. 

All the shotguns you can get after that point - by spending time and resources on them through cargo free orders, budget, or goodie crates - cannot fit on an armor slot. 

They have a higher capacity, sure - but a few extra shots you can miss with more quickly is a lot less of a clear trade for a weapon you can't reliably hold onto in the face of slips. This, in my experience, has meant that the combat shotgun is sort of a redheaded stepchild as far as ranged weapons go - even the Mosin/Sakhno is able to fit on a vest and, in terms of damage output/AP if you can click worth half a shit, a superior ballistic option to the shotgun (now, again, in a much healthier place vis a vis its ability to easily lay down crew-sided ballistic fire, where I haven't even seen improv shells get used except for property damage since the nerf.) 

This lets people put the shotguns they can get on armor so they're not off in this weird wilderness of having a trade-off other ranged weapons that aren't the SAW, ion rifle, particle cannon or such don't acknowledge. This includes the good ol' cycler. I also made the compact shotgun version beltable and lowered its weapon-weight to compensate, so it's not just a roundstart combat shotgun with less capacity (it's still not baggable though.)

## Changelog

:cl:
balance: Full-size automatic shotguns (combat/cycler) can now be secured on armor like other ranged weapons. The compact combat shotgun weighs a bit less and can be worn on a belt.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I dont want to make shotguns more accessible sorry.

**Comment by starrm4nn** [comment]
only DNM'd and not closed, the dream might be alive...

**Comment by Higgin** [comment]
> I dont want to make shotguns more accessible sorry.

understandable have a nice day

**Comment by starrm4nn** [comment]
rip

**Comment by SimplySmiley123** [comment]
This wouldo f been a good change if not for oranges hating on shotguns. RIP

**Comment by starrm4nn** [comment]
> This wouldo f been a good change if not for oranges hating on shotguns. RIP

he hates them for 4NO RAISIN

**Pull request closed without merging**
