### PR TITLE
Fuck lances

### PR DESCRIPTION
**Pull request by silicons**
Fixes sprites not updating properly.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
kek

**Comment by kilkun** [comment]
based

**Comment by Shadowlight213** [comment]
[06:30:57]SAY: Ghost/Kevinz000 : SHADOWLGIHT REMOVE THE FUCKING EXPLOSIVE LANCES
[06:31:01]SAY: Ghost/Kevinz000 : MY FUCKING GOD WHY
[06:31:18]ADMIN: DSAY: Shadowlight213/(Luna Selenia) : AYYYYYY. I recall you loving them before
[06:31:26]ADMIN: DSAY: Shadowlight213/(Luna Selenia) : L M A O
[06:31:27]SAY: Ghost/Kevinz000 : NOT WHEN IM NOT WEARING THE RTA OR IM ON THE RECIEVING END.
[06:31:28]SAY: Ghost/Kevinz000 : &gt;:[
[06:31:33]ADMIN: DSAY: Shadowlight213/(Luna Selenia) : KEK

**Comment by optimumtact** [comment]
come back with a real title

**Pull request closed without merging**
