### PR TITLE
Demon Balance

### PR DESCRIPTION
**Pull request by Xackii**
## About The Pull Request

Demon now takes damage when located in bloodcrawl(every 20 seconds take 5% of max demon hp)
Demon can eat stuned peoples
Demon now can't eat simple animels/basic mobs and etc. Only carbon human being.
Speed buff when demon exit bloodcrawl increase to 10 seconds instead of 6
Slaughter Demon now have 300 hp instead of 200
Slaughter Demon deal 20-30 damage instead of 15 
Slaugther Demona deal 100 obj damage instead of 50
Laugther Demon now make stamina damage
Laugther Demon deal 10-20 damage

## Why It's Good For The Game

Makes demon more combative and less immortal.
Laughter demon cost 1 wizard point so he must be weaker.

## Changelog

:cl:
balance: bloodcrawl now deal damage when you using it
balance: demon can eat only carbon human beings
balance: demon can eat stunned peoples
balance: increase speed buff when exit bloodcrawl from 6 to 10 seconds
balance: buff demons damage
balance: laugther demon deal stamina damage instead of brute
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
the bloodcrawl damage seems like a bad idea, since demons start in bloodcrawl and given the new healing reduction may just fucking kill them if they're eating in a bad spot

**Comment by Striders13** [comment]
definitely make them not take damage until they leave bloodcrawl for the first time, and definitely make them stop taking damage while eating

**Comment by JohnFulpWillard** [comment]
Laughter demon costs less cause it releases and aheals everyone upon being killed, and is a little more obvious, just a little silliness.

**Comment by mc-oofert** [comment]
worst slaughter demon balance pr ever just get good at the game

**Comment by Holinka4ever** [comment]
> the bloodcrawl damage seems like a bad idea, since demons start in bloodcrawl and given the new healing reduction may just fucking kill them if they're eating in a bad spot

They are slaughter demons, nor a stealth demons, that sitting in jaunt whole shift, to grab someone in the dark like a nightmare and repeat these stuff over and over.
These pr is forcing slaughter demon to be onslaught, and it besides giving more buffs to demon to do murderdrom, that they made for lol.

**Comment by SomeoneYouProbablyKnow** [comment]
I don't like the idea of passively damaging the demon, it should be tied to their actions in a specific and direct way. 

Honestly the simplest nerf would be to damage the demon per tile bloodcrawled of a tile without blood. Possible scaling so it starts out low and grows exponentially.

Want to move to a distant place, well take damage
People actually cleaning 80% of the station, well take damage
Blood crawled in 2x2 puddle and don't want to go to the surface, well fuck you take damage.

**Comment by ElGitificador** [comment]
imo demons arent immortal, just annoying because of the no cooldown free immunity ability which is probably the main problem because people dont play around it s weakness. they die a lot more than they succeed for what i ve seen and tbh you can counter them with just a cleaner grenade and actually prepared crew. they re meant to be powerful (wiz item and stuff), imo these changes just make it s gameplay more tedious (unsure if this is actually a nerf since demons have a 1 click stun so with these changes you allow for rclick + grab bloodcrawl = instantkill)

**Comment by SomeoneYouProbablyKnow** [comment]
Cleaning doesn't work, demon just waits. There's no way to make the station fully clean even if it's JUST the demon and often time it's other threats too

**Comment by ElGitificador** [comment]
> Cleaning doesn't work, demon just waits. There's no way to make the station fully clean even if it's JUST the demon and often time it's other threats too

>demon pops up -> use cleaner grenade -> he cannot escape anymore in like 10 seconds (not taking into account lag which extends duration of the foam) now you re free of lasering it to death with your gang.

**Comment by SomeoneYouProbablyKnow** [comment]
Okay that's pretty funny, i'll have to do that next time

**Comment by ElGitificador** [comment]
also has anybody heard of devil kiss?

**Comment by improvedname** [comment]
You should limit the demons to 1 buy each. balance doesn't really matter because its a wizard buy but when wizard usually gets those they tend just to waste all their points unto them

**Comment by Xackii** [comment]
it is aimed at making demon to fight and not sit in jaunt whole round waiting for a lone target to stand on the blood tile. The wizard must think about why he is buying a demon and build gameplay around this. The demon is not a separate antagonist, but a mob summoned by the wizard, even without talking about the fact that it does not obey the wizard. The problem is that demons are usually bought just to ruin the round (wizard dies in the first 5 minutes while the demons live until the end of the round)

**Comment by Xackii** [comment]
and usually he lives simply because he sits afk in jaunt

**Comment by DarkHunter7756** [comment]
> and usually he lives simply because he sits afk in jaunt


And usually has a kill streak of 20 or 30 bodies. Which will not be resurrected, because in conditions of chaos and dead guards no one can/wants to defeat him, but they are simply called a shuttle. Can a mage do something like that for 1 spell point ( cost of laughter demon)?

**Comment by Xackii** [comment]
> > and usually he lives simply because he sits afk in jaunt
> 
> And usually has a kill streak of 20 or 30 bodies. Which will not be resurrected, because in conditions of chaos and dead guards no one can/wants to defeat him, but they are simply called a shuttle. Can a mage do something like that for 1 spell point ( cost of laughter demon)?

Yes, another problem for demon laughter and demon slagter. As wrote above about laughter the demon revives everyone when die. but you won’t see this because they won’t dir. he can sit the entire round in a jaunt with 20 corpses that are impossible to get and never leave the jaunt until the end of the round

**Comment by Xackii** [comment]
returned full heal when eating a corpse because Livrah said so

**Comment by IndieanaJones** [comment]
Smells like an ided PR. I don't think Demons need these changes.

**Comment by Xackii** [comment]
> Smells like an ided PR, because that damage in blood crawl change will just get them killed. I don't think Demons need these changes.

The point is to force demon to fight more and use his jaunt to heal or to quickly get from point to point. What is happening now with demons is more like abductors who are looking for someone to kill. This doesn't bring any amount of fun to the battle between the demon and the station, rather you just keep in mind the fact that a demon might come out of blood and you shouldn't walk near it. This would be nice for a standalone antagonist but it's a wizard summon so it's more looks like a joke

**Comment by Namwty** [comment]
Mfw I spend points on demon and they die cause they didn't want to use piss bottle during 1+ hour long rounds, or their connection died for couple mins, cause surely byond is so stable that nothing ever would go wrong. ( Unless there is a means to prevent dc from being "death", but I am not exactly fluent in code )


If you don't like bloodjaunt to be used as "stalking for decent pray" why even keep jaunt? Imo jaunt checks if spessmen have enough braincells to not be alone in room full of blood. I think it's funny to see people be punished for being "brave".

Not even gonna talk about usual 20 ghosts orbiting demons in jaunt ( wiznerd moment ), which makes "ambushing" part, not exactly a thing.


But I do think that both slaughter demons and laughter demons currently are lame, but doubt this is a way to improve them.

**Comment by jughu** [comment]
Slaughter demons/laughter demons were designed with them killing the wizard in mind aswell as that were one of their main objectives back then, but since wizards ended the round when they died they usually avoided the wizard

**Comment by Deadgebert** [comment]
i don't really wanna be 5 shot by a slaughter demon and round removed

**Comment by tralezab** [comment]
Way too many changes in one pr alone that go in all sorts of different directions on adjusting balance, it's hard to see what state slaughter demon is going to be in and thus hard to even decide if I like the pr. Some changes are so reasonable it's a wonder they haven't been done already, some changes are insanely radical and it's all bundled together. Overall, it's about 50/50 on whether a change is about demons being weaker overall, or demons having a healthier play pattern for the game. We can't tackle both at once.

So please atomize the pr into just one idea this pr will be about. If it's about demons only eating carbons, exclude everything else and focus on that change. We'll have a better discussion, the reasons for the change will be more specific, and you can pr the rest of these changes in the future when you see how that change alone makes a difference in game.

**Comment by san7890** [comment]
a design doc would also be nice

**Comment by tralezab** [comment]
To help you atomize I'll call out the changes that I think would benefit the most from focusing on that idea alone:

>Demon now takes damage when located in bloodcrawl(every 20 seconds take 5% of max demon hp)

Radical, but interesting. Even if it's a somewhat heavy solution for the problem I understand what this change is trying to encourage and maybe with a buffer time where you won't take damage or some other future iteration it works out.

>Demon now can't eat simple animels/basic mobs and etc. Only carbon human being.

This is a no-brainer that removes get out of jail free cards such as a demon losing a fight and due to no fault of the station the untrackable jaunting demon gets a full heal somewhere else before going back for round 2

Pick anything to focus the pr on but these two stand out as the most interesting of the bunch.

**Comment by Xackii** [comment]
> Way too many changes in one pr alone that go in all sorts of different directions on adjusting balance, it's hard to see what state slaughter demon is going to be in and thus hard to even decide if I like the pr. Some changes are so reasonable it's a wonder they haven't been done already, some changes are insanely radical and it's all bundled together. Overall, it's about 50/50 on whether a change is about demons being weaker overall, or demons having a healthier play pattern for the game. We can't tackle both at once.
> 
> So please atomize the pr into just one idea this pr will be about. If it's about demons only eating carbons, exclude everything else and focus on that change. We'll have a better discussion, the reasons for the change will be more specific, and you can pr the rest of these changes in the future when you see how that change alone makes a difference in game.

Well, in general, the goal is one - to make the demon fight more. Eating simple mobs is generally more like a bug that the demon uses to quickly restore full HP. Demon must make a rustle at the station as quickly as possible and die accordingly as quickly as possible. This is a wizard summon for 2(1) points and he should not become the main threat to the station(at least not as much of a threat as he is now)

**Comment by mc-oofert** [comment]
when the literal demonic muscle entity is no longer allowed to kill people efficiently

**Comment by Xackii** [comment]
> when the literal demonic muscle entity is no longer allowed to kill people efficiently

as I already said it would be normal if it were a separate antagonist. The wizard's summon must not live for 2 hours of the round. With enough skills, you can learn to catch a victim to restore HP and continue this again and again. But now it looks more like a lazy revenant who crawls out every 2 minutes to attack a bored clown.

**Comment by Xackii** [comment]
> To help you atomize I'll call out the changes that I think would benefit the most from focusing on that idea alone:
> 
> > Demon now takes damage when located in bloodcrawl(every 20 seconds take 5% of max demon hp)
> 
> Radical, but interesting. Even if it's a somewhat heavy solution for the problem I understand what this change is trying to encourage and maybe with a buffer time where you won't take damage or some other future iteration it works out.
> 
> > Demon now can't eat simple animels/basic mobs and etc. Only carbon human being.
> 
> This is a no-brainer that removes get out of jail free cards such as a demon losing a fight and due to no fault of the station the untrackable jaunting demon gets a full heal somewhere else before going back for round 2
> 
> Pick anything to focus the pr on but these two stand out as the most interesting of the bunch.

So for now, leave only taking damage in Jaunt and prohibit the ability to eat animals?

**Comment by san7890** [comment]
DNM for a full week and now stale, I would recommend you follow tralezab's advice and apply it as a new PR if you're still interested in these changes.

**Comment by Xackii** [comment]
> Makes demon more combative and less immortal.

https://github.com/tgstation/tgstation/pull/83859

**Pull request closed without merging**
