### PR TITLE
PDAs now spawn in the ID slot with the ID already inside.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Saving a couple more roundstart clicks.

### CODE REVIEW

**Comment by Aranclanos** [comment]
lots of machines still only accept IDs and reject PDAs :-1: 
plus I think id sprites are cooler

**Comment by SconesC** [comment]
the ID is still there though aran?

**Comment by Dorsisdwarf** [comment]
Good work. Now stealth ops will get instabusted becase >examine >assistant ID no PDA >;"STEALTH OPS AT LOCKER ROOM"

**Comment by SconesC** [comment]
But that was already a way to do so?

Try again sorry

**Comment by AlexanderUlanH** [comment]
That's why you blow some Assistants' PDA's first so you have an excuse.
Though, it would be nice if ops started with PDA's, or if PDA's were easier to get.

**Comment by Jalleo** [comment]
Newbies will get confused about this. This is why it didnt happen ages ago.

**Comment by Steelpoint** [comment]
Make it a config or similar option that you can toggle in your character screen.

@Jalleo makes a good point where this is something new players might miss.

Overall I do support having the ID start in your PDA however.

**Comment by tuypo1** [comment]
im against it

**Comment by pudl** [comment]
I see no reason to accept this. Just because some people think it's more convenient to have the ID in your PDA, there are other people who prefer it outside of it. Other points raised in the comments only go further to show that.

**Comment by xxalpha** [comment]
No no no no no no

:-1:

**Comment by bgobandit** [comment]
:-1: Not everyone puts their ID in their PDA.

**Comment by SconesC** [comment]
@bgobandit alt click

**Comment by optimumtact** [comment]
this just removes literal busy work, you should always put your ID into your pda to free up the belt slot.

**Comment by pudl** [comment]
You have to remove the ID from your pda for computers, air alarms, all sorts of shit. This just generates busy work for people who need the id OUTSIDE of their PDA.
Keep in mind, when you have your id outside of your pda, you can open every single id-locked thing. With it inside, you can only open some. This is just hiding away your ID.

**Comment by RemieRichards** [comment]
##JUST MAKE IT A PREFERENCE

Some of us want it, some of us don't (myself included), it provides NO advantage, it's the perfect thing to be a preference as it's a subjective preference!

**Comment by pudl** [comment]
"Just make it a preference."
- Remie "Attack animations shouldn't be a preference" Richards

**Comment by RemieRichards** [comment]
@pudl key difference here, ADVANTAGES.

**Comment by pudl** [comment]
PDA w/ ID provides space on your belt slot.

**Comment by KorPhaeron** [comment]
@pudl 

Which you can accomplish in 3 seconds of clicking at roundstart anyway

**Comment by RemieRichards** [comment]
@pudl Which is not permanently taken away from people who use it for IDs, you giant mong.

**Comment by pudl** [comment]
I can't fucking believe I got called a giant fucking mong by Remie fucking Richards.

**Comment by RemieRichards** [comment]
@pudl nobody said you were fucking anything ;)

**Comment by pudl** [comment]
I don't know what that means but thanks for the winkie anyway. ;)

**Comment by Bawhoppen** [comment]
Yea definitely make it an option instead of a forced thing. If its a forced thing then you're adding clicks to other people's time to remove it.

**Comment by SconesC** [comment]
"it provides no advantage"

Except... More space? Like, a belt slot? Jesus fucking christ

**Comment by RemieRichards** [comment]
@SconesC read the part where @pudl already brought up that argument, and it was debunked by myself and @KorPhaeron

**Comment by SconesC** [comment]
Still no reason not to have it but ok

**Comment by PKPenguin321** [comment]
>27 comments flinging shit at each other over a PR that exists solely to remove two clicks at roundstart

what the fuck is wrong with you people

**Comment by ike709** [comment]
>several comments about not wanting to save three clicks at roundstart

i fully support this, but maybe make it a preference to appease the complainers
:+1:  x :100:

**Comment by Iamgoofball** [comment]
>some machines only accept ID, and not PDAs with IDs in them

# then maybe we should fucking fix that you faggot

**Comment by Bawhoppen** [comment]
@Iamgoofball implying thats a fix

**Comment by Iamgoofball** [comment]
how is that not a fix

the problem is a few machines dont accept PDAs with IDs in them

therefore

making those machines accept PDAs with IDs in them is a fix

explain your logic faggot @Bawhoppen

**Comment by Bawhoppen** [comment]
@Iamgoofball While it might be a fix to functionality, I think that ID card in PDA should be a more bonus thing as opposed to what you are obligated to do (to save space). Fix that too if you want but make sure theres a toggle for having it start in a PDA or not

**Comment by Iamgoofball** [comment]
right now the meta IS to have your ID in your PDA, and unless we add a specific PDA slot just for PDAs like paradise did there's no point in not putting your ID in PDA and PDA on ID slot for the belt slot save

**Comment by Bawhoppen** [comment]
@Iamgoofball thats not the meta at all, the majority of people still wear their ID card alone

**Comment by Iamgoofball** [comment]
@Bawhoppen do you play medical or security or engineering

**Comment by Bawhoppen** [comment]
@Iamgoofball of course, I actually play the game, unlike some people who will not be mentioned

**Comment by Iamgoofball** [comment]
then you should know the value of a medical/security/tool belt

**Comment by Bawhoppen** [comment]
@Iamgoofball why would you leave the PDA on you belt? it goes in your pockets? also medical belt is useless

**Comment by Iamgoofball** [comment]
But you use pockets to store
Spare Cuffs
Medicine
Tools you're using for the current job

**Comment by Bawhoppen** [comment]
Boxes of stuff in your backpack??? I mean thats already whats done. If I can't get a toolbelt I just load all my tools into a box in my backpack. Medkits, etc. same. But what I was pointing out is that if you go to sybil right now and observe and look at random people, the majority don't have ID in PDA

**Comment by Steelpoint** [comment]
As Security, Medical or Engineering wearing your ID card in your belt and/or pocket slots is a massive waste of space.

If you do this then your being really inefficient.

As a security player most people I nab have their ID in their PDA for the most part, exceptions for antags holding spare ID's from other people they stole, or general people stealing access.

Generally there no benefit to not putting your ID in your PDA.

**Comment by Bawhoppen** [comment]
Just make it a toggle option and that will solve every problem.

**Comment by CPTANT** [comment]
No god, a toggle is not the option for everything. Just have the balls to actually change something as minor as 2 roundstart clicks.

Console interfaces need to have a look. Security records interface for example is horrible. You have to take out your id put it in verify, take it out again and put it back into your pda. The login button should just check for the ID in your pda.

**Comment by Cheridan** [comment]
Can we all tone down the rhetoric some you guys are getting too mad about this shit

**Comment by freerealestate** [comment]
>Just make it a toggle option and that will solve every problem.

**Comment by Bawhoppen** [comment]
We need a controversial tag on this

**Comment by Razharas** [comment]
Lol everyone is so mad here relax dudes why you mad its just a game theres no need to be mad

**Comment by PKPenguin321** [comment]
this PR pretty much wont change anything
if "muh nuke op meta" is such a big deal then give ops PDAs

**Comment by Bawhoppen** [comment]
The point is not that its a meta-thing (though it could become), but as I already said, I think the ability to put ID in PDA should be a more bonus thing than an obligation. Also what Aran already said right at the beginning.

Again a toggle would end this entire argument.

**Comment by PKPenguin321** [comment]
for machines that only take IDs and wont take PDAs i literally just type "id" and hit enter twice and in less than a second i have my ID out
is that so much of a hassle for you people?

**Comment by optimumtact** [comment]
It's already an obligation because you really need the extra slot free for other items.

Why would you not do it? Who would willingly sacrifice a free slot to their PDA so they can have the ID seperate

**Comment by Bawhoppen** [comment]
@optimumtact Alot of people, thats why this entire argument exists? 
>plus I think ID sprites are cooler

**Comment by PKPenguin321** [comment]
then just take your id out at roundstart
"but why dont you guys just put your ids IN at roundstart"
because we're the majority and we have a coder on our side :^)

**Comment by Bawhoppen** [comment]
Go to sybil right now and observe and examine random people, the majority will have their ID outside of their PDA.

**Comment by optimumtact** [comment]
The argument is that it will take more clicks to get it out for use in some machines right? What I don't get is that it actually only takes the same number.

Consider id->pda -> id slot - takes 1 alt click to get it in your hand
Consider id -> id slot - still only takes 1 click to get it in your hand

So the only difference is the modifier key, I guess I'm just confused as to why it's a problem for people other than that.

**Comment by Bawhoppen** [comment]
The entire argument isn't just about the machines, for reasons already described above, many people like to not have it in their PDA, and many do, so we shouldn't force it to start in the PDA.

OR WE COULD HAVE A TOGGLE

**Comment by SconesC** [comment]
but i still don't get why people like it outside of the pda

we have altclick for one click removal and that means it is DIRECTLY MORE EFFICENT SPACE WISE

so, why?

**Comment by Bawhoppen** [comment]
You can physically show it, the machine functionality, PDA is disposable-ish, RPwise it seems better to have it just as an ID alone, and I'd think the ID in PDA thing is more of a bonus

**Comment by Iamgoofball** [comment]
>can show the ID

Why not make the PDA show it too?

>machine functionality

This needs fixed.

>PDA is disposable

Uh, not really, it's a very nice thing to have.

>RPwise

We don't code for RP. We code for gameplay

**Comment by Bawhoppen** [comment]
alright goof, just keep powergaming for saving space

**Comment by Iamgoofball** [comment]
Seeing as this is a video game, I'll gladly continue to play the video game.

**Comment by Bawhoppen** [comment]
It is a roleplaying video game, and while we don't roleplay as much as some other people, Its not all about winning.

**Comment by Iamgoofball** [comment]
you don't quite understand that in order to have roleplay we DON'T have to mutilate gameplay

**Comment by Bawhoppen** [comment]
its a fucking PDA, its not /THAT/ big of a deal, yet you insist that 1 extra slot is important

**Comment by Iamgoofball** [comment]
it is gameplay wise, inventory management is one of SS13's worst aspects

**Comment by Bawhoppen** [comment]
I think a single slot of space is worth looking cooler. A station full of scientists with their own keycards they need to scan for every door as opposed to a nerd PDA.

t.o.g.g.l.e.

**Comment by tuypo1** [comment]
I like machines that require you to insert your id

**Comment by Dorsisdwarf** [comment]
I think goofball's being a nerd.

SS13 is a game->SS13 involves inventory management->IDs require inventory management at roundstart->ID->ID goes in the PDA->PDA takes up a slot->SS13 is about slots->PDA is bad->People think the ID card is cooler than the PDA->Cool->Opinion->Roleplay

Therefore Roleplay is opposed to it being a game.

I've seen videos where the end is a screen saying "Illuminati confirmed!!!" that made more sense

**Comment by freerealestate** [comment]
outta the way ID fucken shits, statistically scientific poll cummin thru

http://strawpoll.me/5642204/r

**Comment by Bawhoppen** [comment]
you posted a strawpoll link to the RESULTS of the strawpoll

**Comment by freerealestate** [comment]
yup

**Comment by Bawhoppen** [comment]
Wasn't your point to make it so we voted on it?

**Comment by freerealestate** [comment]
both

**Comment by Bawhoppen** [comment]
cancer

**Comment by freerealestate** [comment]
you'll figure it out.

**Comment by Zilenan91** [comment]
In gameplay, there is literally no reason to not have your ID in your PDA. Unless you're constantly locking and unlocking things like lockers, which no job has any reason to really do, it just sits in your PDA allowing you to open doors.

In the case you actually do need to open a locker, there's the object tab, in there is the eject ID button, which ejects your ID into your hand from your PDA in one click. There is no reason to not have it in your PDA, I legitimately don't see why this is controversial or an issue.

**Comment by freerealestate** [comment]
i think you can alt+click lockers now anyway

the only time you really need to take it out is to show other people (which is a very rare occurence) or when it needs to be slotted into a computer (and as people have already said in this PR computers should either accept PDAs as well as IDs or just act like most of the other objects that require ID in the game and work based on the ID in your slot)

**Comment by Bawhoppen** [comment]
As I said before, theres other reasons for you wanting it out than just mechanically. Its not about being the most efficient always

**Comment by Aranclanos** [comment]
this will be awfully worse for new players, I'm sure you'll be able to survive 4 extra clicks at roundstart in exchange of that

**Comment by freerealestate** [comment]
Aranclanos, people want this to be a pref.

And considering the whole game has one of the steepest learning curves out there, that argument doesn't really hold water for such a minor change.

**Comment by Iamgoofball** [comment]
@Miauw62 re-open please

**Comment by KorPhaeron** [comment]
4 extra clicks a round
~x50 players a round
~x1000 rounds a month according to our stat tracker
x12 months in the year

Saving literally millions of clicks a year.

Someone else can make it a pref in another PR though I don't the desire to figure out how that part of the code works.

**Comment by SconesC** [comment]
The future is dead

**Comment by Aranclanos** [comment]
4 extra clicks a round
~x5 players who actually do it
~x10 new players per round confused
~x20 extra clicks per hop line
~x20 extra clicks per machine interaction
x12 months in the year

**Comment by Bawhoppen** [comment]
aran to the rescue again

**Comment by PKPenguin321** [comment]
>~x20 extra clicks per hop line
~x20 extra clicks per machine interaction

it's literally the same amount of clicks whether id is in or out of PDA

**Comment by Iamgoofball** [comment]
# WILL YOU FUCKS STOP IGNORING THE "MAYBE WE SHOULD MAKE PDAS WORK IN MACHINES TOO" SHIT

**Comment by Bawhoppen** [comment]
There should be physical mechanical benefits to both aside from just RP, and letting PDAs work in machines would be a huge nerf to ID standalones

**Comment by KorPhaeron** [comment]
>letting PDAs work in machines would be a huge nerf to ID standalones

I'm gonna cry laughing. Just when I think this PR can't get any more surreal.

**Comment by ExcessiveUseOfCobblestone** [comment]
nerf id's please

**Comment by Bawhoppen** [comment]
this really matters to me ok

**Comment by PKPenguin321** [comment]
\>tfw your id is too powerful

**Comment by Bawhoppen** [comment]
I was being half sarcastic but seriously though, IDs should be the main thing, not obligated to put ID into a PDA

**Comment by SconesC** [comment]
tfw id power creep

**Pull request closed without merging**
