### PR TITLE
DELTASTATION: Complete service + arrivals revamp, cargo tweaks (some maintenance was harmed in the making of this pr)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

This PR completely revamps the service department and arrivals wing of Deltastation. Cargo received some tweaks as well to accommodate these changes. 

deltadeez3

<details>
<summary>(Picture with all the pipes and stuff)</summary>

deltadeez2
</details>

### Notable changes:

- The service department as a whole was redesigned with a large open, bazaar-style floor plan. This includes open cafeterias and bars, as well as a full on stage for theater roles. 
- Arrivals was expanded to give a more grandiose welcome to what is supposed to be a very large station. Wide corridors and ample seating. 
  - Arrivals customs and the arrivals security checkpoint were merged into one room, serving as a potential "second HoP-line".
  - A public garden was added to arrivals to replace the removed maintenance garden.
  - Some additional maintenance rooms were added to arrivals maintenance.
- Cargo received some tweaks to accommodate the shift of service.
  - The drone room was moved down and connects to the cargo office.
  - The delivery office was moved to the mining office, and now connects to the main loop. ORM untouched.
  - The warehouse was moved inwards to the bay and given shutters.
  - Cargo was fitted with some more amenities afforded to them by other maps. Roller skates and the cargo ripley. 
- A good bit of maintenance was cut off from service maintenance. New maintenance now exists between cargo and service, connecting the main loop to arrivals maintenance. 

## Why It's Good For The Game

Deltastation has always been a very samey map - Metastation, but larger. A lot of its design is a little antiquated by now and overall it could use some facelifts. This begins the process by re-doing Deltastation breathing some new life into it.

Service was chosen as it was largely pretty lacking and simple in its design. Every corner of service was a square connecting to either the bar or the main hallway. 
- The bar had ample room for re-designing, but the kitchen, being connected to the main hall, didn't offer the same opportunities. 
- The theater was pretty standard and, in my opinion, very plain. 
- Hydroponics was a hot mess - very little room, doubled up machines for no reason, overall a weird and not very pleasant design to use, especially with nu-botany. 

Ultimately, this redesign sought to address some of the problems of the various service sub departments while giving Deltastation some identity. Deltastation is the big station in town meant for a ton of people, so it should have big departments to match. 

## Changelog

:cl: Melbert
add: Deltastation - Service and arrivals complete revamp! Cargo tweaks! 
/:cl:

### CODE REVIEW

**Comment by FalkKeegan** [comment]
Where is the bathroom?

**Comment by Jolly-66** [comment]
RIP meta bathroom

Now where will I commit my most obvious murders

**Comment by SuperNovaa41** [comment]
Woah this looks awesome

**Comment by MrMelbert** [comment]
The bathroom returning was a want, not a need, in my working list...

The price must be paid - a soul for a soul

**Comment by bluetshirtguy** [comment]
Circular botany is agony to play in always, diagonal movement sucks and moving things around to circumvent that is silly.

**Comment by MrMelbert** [comment]
image
I returned the bathroom to its home. In turn, arrivals maintenance was shifted left a bit, but the size was maintained largely. In turn in turn, the atmos experimentation room was moved over too, but it should still have enough room to do everything. I also went through and touched up the atmos experimentation room since it was very basic - some naming airlocks, decals, turf changes.

The picture in the PR body has been updated.

**Comment by MrMelbert** [comment]
> Circular botany is agony to play in always, diagonal movement sucks and moving things around to circumvent that is silly.

It's already expected that botanists move their trays around to how they are accustomed with nu-botany. Here's an example layout of all trays spread out in a nu-botany compatible format that is leaves perfectly square walking paths.

image

**Comment by Laz0rG** [comment]
for what it's worth this is going to make antagging on this station even harder due to the removal of the spacious and multi-pathed service maintenance. Despite how nice the redesign is I don't think it justifies this gameplay malus, especially given that delta is already the defacto highpop station meaning that antagging is already difficult under such circumstance.

**Comment by bluetshirtguy** [comment]
> > Circular botany is agony to play in always, diagonal movement sucks and moving things around to circumvent that is silly.
> 
> It's already expected that botanists move their trays around to how they are accustomed with nu-botany. Here's an example layout of all trays spread out in a nu-botany compatible format that is leaves perfectly square walking paths.
> 
> image

Fair enough but maintenance being completely gutted still stands

**Review by Maurukas — CHANGES_REQUESTED** [review]
This is amazing. Exactly what I was hoping to see on Delta. This makes service into an open area that takes advantage of all the real estate Delta has to offer.

One minor issue to fix before merging:
<details><summary>There are two APCs in the marketing den. One is hidden under a poster. </summary>

image
</details>

**Comment by theta006** [comment]
looks mostly good

**Comment by timothymtorres** [comment]
I'm happy to see other people using the random spawners for mapping.  The open space nature of the service area will give the map a different feel but I think this is good!

**Comment by NanoCats** [comment]
Bless you for making a clown and mime separated office.

**Pull request merged**
