### PR TITLE
GAGs Buckets

### PR DESCRIPTION
**Pull request by ShizCalev**
:cl: ShizCalev
qol: Converted buckets (and naturally cleanbots) over to GAGs.
fix: Cleanbots built with a wooden bucket will now properly drop a wooden bucket when destroyed.
/:cl:

### CODE REVIEW

**Comment by DAKKA-WAAAGH** [comment]
Truly wonderful, does it get any better than this?

**Comment by Time-Green** [comment]
Send bucket pictures pls

**Comment by ShizCalev** [comment]
image

image

**Comment by Time-Green** [comment]
Oh my god it’s perfect

**Comment by thebestcodertoevercode** [comment]
This is a bucket. Dear god.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
