### PR TITLE
Fixes pinpointer runtimes

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Missed this one in #48326

### CODE REVIEW

**Comment by cacogen** [comment]
damn

**Comment by trollbreeder** [comment]
Also make sure that the Navigationally Challenged trait doesn't get forced on your character. When i came in the round a lot of people were talking about the pinpointer that's wasting pocket space appearing in their pockets despite not having the trait.

**Comment by kriskog** [comment]
See #48616

**Comment by trollbreeder** [comment]
> See #48616

fuck i have tunnel vision

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
