### PR TITLE
Gives a few ill needed buffs to the mediborg

### PR DESCRIPTION
**Pull request by Incoming5643**
*Refillable Gauze Module
*defibrillator (Had to ugly up defib code a bit to get the borg version to work properly, my bad)
*Swaps out omnizine in the cyborg hypospray with a new chem (Saline-Glucose-Charcoal-Salbutamol Solution) that 1:1 mimics the effects of its overdose free precursors.
*Medical Drapes
*Omnistat [Needs sprite]: an all in one solution for surgery tools with beyond perfect accuracy to assure a harm free environment. (important note, doesn't stop intrinsic harm from augmentation or brain removal)
*Autostripper [Needs sprite]: for when they absolutely, positively, NEED to be naked quickly (5 seconds normally/1 second emagged)

### CODE REVIEW

**Comment by Incoming5643** [comment]
Wanted to add but couldn't figure out: A way for the mediborg to various machines that accept beakers with its beaker module

**Comment by TheVekter** [comment]
I don't think there's going to be any way to do that without being able to drop/pick up the borg's beaker.

**Comment by Iamgoofball** [comment]
@Incoming5643 if you're fucking with mediborgs, see about swapping the omnizine in the injectors with  some kind of healing mix

salglu should help with some brute/burn, charocal should help with tox, and some salbutamol would be nice too in replacement of omnizine

**Comment by RandomMarine** [comment]
Just want to point out for reviewers that the borg's defib can harmpaddle people without tampering.
And it's asimov-friendly to boot. Weaken (5) with a boatload of staminaloss.

**Comment by Incoming5643** [comment]
Mostly intentional that yeah. When I saw the harmpaddle was asimov friendly I pretty much had to, as subverted mediborg is outright tragic and needs all the help it can get.

**Comment by Lumipharon** [comment]
The only thing tragic about hacked mediborgs is the poor sods that get reduced to a pile of naked, melted meat from acid spray.

+1 for mediborgs shockpaddling people for shit and giggles though.

**Comment by Miauw62** [comment]
Borg hypos are coded to be able to dispense arbitrary chems easily. It's
not hard to change them.
Op 13-feb.-2015 10:03 schreef "Lumipharon" <notifications@github.com>:

**Comment by Iamgoofball** [comment]
Hold up, don't add a recipe for that. It's a heal-all as it covers all  the damage types.

Available in the borg hypospray is fine, just don't add a player mixable recipe.

Also miauw it's because otherwuse the charcoal purges the other chems.

**Comment by paprka** [comment]
Nope, shit code in defibs, try again.

**Comment by Deantwo** [comment]
wait. You made a whole new chemical for this? What? Why?

Also, would think the defibrillator is a little OP, and won't work all that will anyway since a borg can't use patches.

**Comment by Incoming5643** [comment]
@paprka unless that person died from pure oxy/tox/exotic damage (and that's pretty rare outside a vengeful chemist) the body is almost always going to be too messed up to use the defib on. Nothing the mediborg caries can patch up the dead so it really can't use the paddles too well without the aid of a human.

Also I'd love to see what the non shitty way to retrofit a two handed weapon that relies on an external item to work for a no handed silicon without said item is (beyond not making it a child in the first place and just copy pasting the relevent bit)

@Deantwo As stated before, all chems that remove tox damage also speed the removal of all chems besides itself in patients, so any healing mix that includes charcoal, is only vaguely better than charcoal alone. The only way to have this effect without it "cannibalizing" itself is to make it all one chem.

**Comment by Incoming5643** [comment]
if yall hate defibs for mediborgs so bad suggest some other bones to throw at them, cause it needs something going for it.

**Comment by paprka** [comment]
Surgery tools, it doesn't need a defib as it shouldn't be giving a shit about dead bodies.

I don't disgaree with giving it defibs that it can use to zap people but I want to handle that myself, rather than have 5000 checks.

**Comment by dannno** [comment]
surgery tools is a pretty decent idea

**Comment by Incoming5643** [comment]
a defib unit has a bunch of var and procs a silicon robot doesn't have (specifically: powered, safety, deductcharge(), and cooldowncheck() ), I already attached the battery power of the defib to the robot, and that's pretty much where the similarities end.

I can add the surgery tools, but I thought that'd be MORE controversial than a defib, considering how prone to harm surgery is.

**Comment by Deantwo** [comment]
But why do mediborgs need a cure-all chemical?
Because only people that don't wanna learn chemistry plays them?
Why not leave it with them to chose what chemicals to give a patient?

A mediborg need to have charcoal anyway, so they can purge bad chemicals from a patient.
Just replace *omnizine* with *Saline-Glucose Solution* and *Charcoal*.

**Comment by Incoming5643** [comment]
the idea is to give some incentive to play the only borg worse at its job than a competent human.

**Comment by Incoming5643** [comment]
New suggested modules have been added to the pull, the idea is to add at least some of these, if not all of them.

**Comment by Deantwo** [comment]
Nice ideas.

Just think the idea of the emagged *Autostripper* is a little much.
Leave it at 5 seconds. But you could make it work faster if the targer is dead or in crit.
Maybe have it destroy the jumpsuit though?

**Comment by Dorsisdwarf** [comment]
The autostripper shouldn't be faster for the emagged borgs. Not only is it a hard tell "Borg strip that guy or we'll blow you", but it's too powerful. You can literally stun someone with the defib and their radio is gone /before they can even call ;help borgs rogue.

Mediborgs should not have medical tools. Not only do they include high-brute weapons like the circle saw and drill, but they will never be used for intended purpose, as an asimov borg can't even do surgery on a human to pull a xenomorph out of them, because cutting them open causes harm.

**Comment by Incoming5643** [comment]
To be fair borgs can strip natively anyways, if anything the autostripper is a side grade to just being robust with the strip menu.

And oh my god all these conflicting opinions on shit I'm starting to realize why no one's tried to balance mediborg

**Comment by Incoming5643** [comment]
We need some clear cut definitions of what is "harm" here:

Most surgeries don't actually do damage when performed perfectly, and the omnistat with it's base 500% success rate is ALWAYS perfect.

The defib doesn't cause lasting damage, but it does cause stamina damage, but the sec borg's disabler seems to suggest that stamina damage isn't "real damage" for the purposes of what harm is

I don't consider either of these things "harm", but for people with a more abstract concept of "harm" I understand why they would. Someone somewhere is gonna have to draw a line on this.

**Comment by Dorsisdwarf** [comment]
Yeah but having a ONE SECOND button that takes off all their armor, kit, weapons, empties their pockets, and leaves them unable to call for help?

Holodamage/stamina is not harm and more than a taser shot or pepperspray is.

Just because most surgeries do damage and then fix it in a later step doesn't make it any more palatable. The human could have a counting-down nuclear warhead in their chest cavity and they couldn't do the saw step.

**Comment by Deantwo** [comment]
Depends on a lot on how the individual borg understands the asimov law.
Does one life count for more than 10? What if it can save the world by killing one person?

But really, just make the *Omnistat* have a safety on it that prevents them from attacking people with them, unless emagged?

**Comment by paprka** [comment]
Autostripper is really bad

**Comment by TheVekter** [comment]
If the human consents to the harm isn't it an exception to law 1?
Considering borgs don't have to stop the Roboticist if it cuts someone open.

**Comment by paprka** [comment]
I will ask pandar about surgery tools

**Comment by Incoming5643** [comment]
Most surgeries NEVER do quantifiable damage unless you fuck up and use the wrong tool at the wrong point, which borgs are specifically protected from in this pull.

Only augmentation and brain removal actually do "damage", and both of those shouldn't be undertaken by asimov borgs to begin with.

**Comment by GunHog** [comment]
Recommendations: Remove the auto-stripper and omni-surgery tool. Give borg force zero versions of each tool. Do not give the borg a mix of chems, just give each individual chem to the hypo instead (it may need a UI or something though).

The stripper module would only make sense if borgs could not strip on their own. The omni-surgery tool makes surgery far too easy and simple. Call me what you will, but I enjoy doing it as a Roboticist, and I would not ask to have the omni-tool made for me. It could cause a bit of clutter, but a Mediborg should still have to know all the proper steps as a human MD would.

Having one chem for several damage types removes the need for diagnosis, do not cut that part out of doctoring. My ultimate point here is that playing as a Mediborg should be similar to playing as an Engineering borg - you have all the tools and resources you need to do your job, but you still need to know *how to do the job*.

**Comment by TheVekter** [comment]
Hey @Incoming5643, while we're at it, can we go ahead and give mediborgs a portable crew monitor? I don't think they can access it otherwise without being in front of a console.

**Comment by paprka** [comment]
the powergame is strong

**Comment by Incoming5643** [comment]
I'm gonna put the omnistat v full set of surgical tools thing to a non-binding and probably pointless forum poll, as it's really almost entirely a matter of taste and I'm just curious how people feel about it

**Comment by Lumipharon** [comment]
Can we have less portable "crew tracker 5000's" then more? Seriously if they should exist at all it should be a CMO only thing.

**Comment by Incoming5643** [comment]
I think I'm going to split up this pull into individual items so the less controversial aspects can get merged faster, Mediborgs REALLY need gauze and I've yet to find a soul who disagrees on that

**Pull request closed without merging**
