### PR TITLE
Replaces patient rooms on box, delta, and meta with a second Surgery

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
bye erp dens

## About The Pull Request
This PR changes the Box, Delta and Meta patient cells into a second, smaller, surgery theatre.
meta
box
delta
## Why It's Good For The Game
Since surgery is meant to be playing a larger role in medical as the medical changes move forwards (Tending wounds etc), its somewhat dumb for medbay to have a single op theatre and a single set of surgery tools laid out, especially considering how easy it is to accidentally wander off with a tool in your pocket. Also the patient dens are only ever used for braindead people and hiding your traitor trash.
## Changelog
:cl: Dorsidwarf

tweak: Swaps out Box, Delta and Meta patient rooms for a small secondary surgery theatre

/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
> 
> nooooo my nanomeeeeds
> 
> and if there's more blood in those freezer's that's a big deal and not epic

I totally forgot there are nanomeds in those rooms, I'll correct that soon.
Is it a massive change for the station to have two of each bloodpack instead of 1? I dont use them much so I'm not sure.

**Comment by Dorsisdwarf** [comment]
Could swap it for an organ storage fridge if you want? I mostly just put it there for completeness

**Comment by Tharcoonvagh** [comment]
i once tried to cure an antag in one of those patient rooms....

**Comment by kriskog** [comment]
Did you know virology has a crate of blood packs too? I bet most didn't, since it's never really an issue.

As for the nanomeds, toss them. Burn/brute packs and sprays aren't all that good anymore, it's not a huge loss. If anything, maybe add the pubby ones: /obj/machinery/vending/wallmed/pubby
It has 3 syringes, one burn/brute patch and a sterilizine spray. One in each surgery would be fine right?

**Pull request merged**
