### PR TITLE
Adds more moth names to prevent duplicate random names

### PR DESCRIPTION
**Pull request by 81Denton**
:cl:
spellcheck: Nanotrasen's space entomology department is shocked to discover that Mothpeople have surnames!
/:cl:

Fixes: #36846

Moths only have 40 names to pick from, which can lead to duplicates when random names are picked. 
I added a bunch of names (read: copied them from various biology pages) and gave moths surnames to increase the amount of combinations to 100*57.

In case someone mentions the freeze, racial content etc:
adfafsfssdsfd

### CODE REVIEW

**Comment by epicmemename** [comment]
add fluttershy as a random name

**Comment by 81Denton** [comment]
xd

**Comment by XDTM** [comment]
a json file with two categories would be better in this case, so we don't need to have a file for each

**Comment by nicbn** [comment]
Add hakuna and matata

**Comment by 81Denton** [comment]
@XDTM Sounds like a good idea, but I have no clue on how to make it work. Closest one I found find is generate_pirate_name().

**Comment by XDTM** [comment]
Brain damage lines, hallucinations and maybe golem names could be good examples.

**Comment by fludd12** [comment]
But where is moon moon

**Review by vuonojenmustaturska — APPROVED** [review]

**Pull request merged**
