### PR TITLE
Karambit

### PR DESCRIPTION
**Pull request by CptnCapitalism**
## About The Pull Request
Adds a new melee weapon for the Syndicate

## Why It's Good For The Game
While eswords are robust enough to kill an opponent in a few hits, their sound makes it obvious for anyone nearby that they have a traitor on the ship. This karambit gives agents the ability to "slit" a target's throat, making them unable to speak for a short time, allowing for a new way of silent murder.

## Changelog
:cl:
add: Added the karambit, a new Syndicate weapon with a special attack that prevents your target from speaking for a short while.
add: Karambits can be found in Syndicate uplinks under Stealthy and Inconspicuous Weapons, and in the nuke ops lockers
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
>A robust karambit with a plasteel blade.

How many other things do Syndi/traitors have that are plasteel? Isn't part of the setting that plasma is a new resource that NT is monopolizing on, forcing competing companies to band into the Syndicate?

**Comment by optimumtact** [comment]
Do we really need yet another antag item?

**Comment by nemvar** [comment]
This is powercreep on the edagger. It does more damage and also has a pretty strong secondary effect. Doesn't have the load activation sound. Only downside is that it isn't pen sized, which is barely a benefit in most cases. All of that for the same price.

I'm also opposed to giving nukies even more free stuff. Let them actually spend their TC if they want something. Nukies already get survival knifes as a free robust melee weapon and combat gloves+ serve as their way to get a silence, if needed.

There also doesn't seem to be a downside to be permanently be in throat cutting mode. So you can just spam Z for maximum efficiency. It would seem more sensible that this effect should always trigger when targeting the mouth, instead of this bizzare need to spam Z.

**Comment by CptnCapitalism** [comment]
> 
> 
> > A robust karambit with a plasteel blade.
> 
> How many other things do Syndi/traitors have that are plasteel? Isn't part of the setting that plasma is a new resource that NT is monopolizing on, forcing competing companies to band into the Syndicate?

Yes, it is a farily new resource, and NT is doing everything it can to monopolize it. That's why one of the traitor objectives is to steal a full tank of plasma. Since the Syndicate already provides their agents with state of the art equipment (like teleporters, chameleon kits, eswords, etc.), I think it's safe to assume that they wouldn't hesitate to use some of the stolen plasma to create enough plasteel for a blade, if that can make their agents more effective.

**Comment by CptnCapitalism** [comment]
> 
> 
> This is powercreep on the edagger. It does more damage and also has a pretty strong secondary effect. Doesn't have the load activation sound. Only downside is that it isn't pen sized, which is barely a benefit in most cases. All of that for the same price.
> 
> I'm also opposed to giving nukies even more free stuff. Let them actually spend their TC if they want something. Nukies already get survival knifes as a free robust melee weapon and combat gloves+ serve as their way to get a silence, if needed.
> 
> There also doesn't seem to be a downside to be permanently be in throat cutting mode. So you can just spam Z for maximum efficiency. It would seem more sensible that this effect should always trigger when targeting the mouth, instead of this bizzare need to spam Z.

I thought the edagger did 18 damage, and I set the karambit to 17. It's also a Syndie-exclusive weapon, meaning if anyone sees you with this, they can assume that you are a traitor. I could increase the TC cost, 2 was just a starting point.

I forgot about the survival knives for the nukies, ill remove these from their lockers.

The muting effect lasts for 15 seconds. I could change it to last much shorter (like 3 or 4 seconds), and only activate when you target the mouth. What do you think?

**Comment by zxaber** [comment]
You could just nuke the damage down a lot. Make it a special use item about muting, and not also a damage-oriented weapon.

**Comment by CptnCapitalism** [comment]
> 
> 
> You could just nuke the damage down a lot. Make it a special use item about muting, and not also a damage-oriented weapon.

That's a good idea. I will change the description to stress the ability to mute, and reduce the damage to 12, so that it would crit in 9 hits instead of 6.  Should I also tweak the muting effect to trigger when you hit the mouth, or can it stay the way it is now?

**Comment by nemvar** [comment]
The thing is that we already got traitor items that mute the target, namely the sleepy pen and EMP flashlight.

Not talking about the flavour fail where a sharp blade just makes you unable to talk for a few seconds when it hits your throat instead of cutting open some arteries. It makes somewhat sense for Krav Maga to do it because that's a blunt force, but this strains the suspension of disbelief.

The only possible niche this item can fill is a combination item between damage and silence, which I don't think is something that is healthy for the traitor gamemode. I can't imagine that this will be used for much else other than stunbaton > karambit.

It also feels like this should be a subtype of the kitchen knife (just like the combat and survival knife), so it gets butchering and stuff from inheritance.

**Comment by CptnCapitalism** [comment]
I could move it to kitchen.dm, but there is not much point if nobody wants it in the game.

**Comment by AdamElTablawy** [comment]
slitting your throat not causing bleeding seems pretty bizzare. At this point it might as well be a garotte

**Pull request closed without merging**
