### PR TITLE
New lavaland ruin

### PR DESCRIPTION
**Pull request by Boopideedoo**
## About The Pull Request
This pr adds a new ruin to the game that is based on xenobiology as we need more diverse ruins I thought to add one about xenobiology to add more diversity
## Why It's Good For The Game
It adds more diversity for the ruins and has a new ruin type being a xenobio ruin
## Changelog
:cl:
add:Xenobio Ruin
/:cl:

### CODE REVIEW

**Comment by Boopideedoo** [comment]
Im grabbing pics

**Comment by Boopideedoo** [comment]
I forgot to add lights so itll be a bit dark

**Comment by Boopideedoo** [comment]
image2
image

**Comment by DaxDupont** [comment]
This honestly feels very flavorless

**Comment by Boopideedoo** [comment]
> This honestly feels very flavorless

Mind giving some suggestions to make it feel more flavored?

**Comment by Xkallubar** [comment]
It's literally just xenobio but on lavaland. Make it at least somewhat destroyed, with barricades, hostile gold slime spawned enemies (such as blobbernauts and spiders) so it isn't given to you for free. If you want to use it, you should have to fight some tough mobs, clean it up, and rebuild broken areas. It shouldn't come set up all nice and fancy for free.

**Comment by nikothedude** [comment]
its also critically flat, i mean just look at the drab grey tiling everywhere

add some tables, some separating walls, decals, anything to make it less of just "floor with crab window"

**Comment by private-tristan** [comment]
does the freezer work? that looks like a normal vent, instead of a passive vent.

**Comment by Jacquerel** [comment]
Please put the pictures in the PR body not the comments.
But it's also uh... it's very bare. There's not much story to this ruin, or character. Would be nice to have a bit of environmental narrative as to why there's an abandoned but also functionally completely pristine xenobiology lab lying in lavaland.

**Comment by Boopideedoo** [comment]
I'm not home rn so I'm gonna close the PR and fix what was suggested then bring it back once I fix a few things after I get back home

**Comment by Boopideedoo** [comment]
I'll have it back in a few days once I fix that

**Pull request closed without merging**
