### PR TITLE
You can unpack bibles into new altars of the gods

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

There's a problem of people breaking altar of the gods, just to fuck over the Chaplain's entire round.
I was thinking of making this by using a bible on the table instead, but that just feels weird since you would expect it to just place it on the table instead of make a new altar.

If you have any questions on how this is possible, [refer to this video](https://www.youtube.com/watch?v=AivZSC9J3Rs)

(Other code changes are because I tried to make it easier to read so I can go through it better)

## Why It's Good For The Game

Chaplains can replace their altar of the gods so it being destroyed won't mean their round is ruined.

## Changelog

:cl:
qol: Chaplains can now replace their Altar of the Gods by hitting the Chapel floor with a Bible.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Can't you print new bibles?

**Comment by JohnFulpWillard** [comment]
> 
> 
> why not just make the altar of gods not breakable outside of explosions

Invincible structures for no reason make no sense. Structures should be craftable by players in-game whenever possible.

**Comment by Wollywoger** [comment]
honestly i'd say let the chaplain place the altar outside the chapel despite what was previously said. The reason for this is that the chapel tends to get crossfired a lot/or just targeted because funny for the same reason as the altar (although less often because it requires _effort,_ or just outright ruined by events **meteors**
As for the maint chap problem, i'd more say its a non issue, the pro of it is portable altar, and if this really shatters the balance, just have the chaplain only have one bonus altar at a time

**Review by tralezab — CHANGES_REQUESTED** [review]
small things about feedback

**Review by tralezab — APPROVED** [review]

**Pull request merged**
