### PR TITLE
New sprites: toilets, sinks, urinals.

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
imageadd: A bunch of water closet stuff was resprited.
/:cl:

image
image
image
image
image

Uses the same color palette as grey part of chem master.
The mirror is now square but the magical mirror is still rounded to keep an old aged aspect of it.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
UGLY BAD

**Comment by optimumtact** [comment]
based and 3/4 pilled

**Comment by PKPenguin321** [comment]
i really really hate the toilet side sprite, wtf is going on with that cistern
shit's looooong
wait till u see the urinals
oh no no no
*WHEEEEEEEEEEZE*
look at the thickness of the ***bowl***
look at how skinny the top is

**Comment by nicbn** [comment]
The urinal we have right now is pretty ugly, and the toilet we have seems weird when not facing south because of perspective.

Yeah sinks are pretty good but it doesn't really match the style we are aiming towards

**Comment by nicbn** [comment]
The new toilet cistern may seem long because it extends all the way to the bottom, but is a way I found to make it look less contemporary and more like something you'd find in a space station - some clunky thing that was designed to work and not to be charmful.

**Comment by nicbn** [comment]
Shit wrong button

**Comment by Moja10** [comment]
Add urinal cakes by default that assistants can loot  for slips

**Comment by anconfuzedrock** [comment]
I thought the pic of the old ones was “ok i made the toilets and urinals better here” and I was gonna say those are a major improvement
Toilets look like lifeweb poop-holes, how could you sit on those?
Square sink is a crime against humanity.

**Comment by nicbn** [comment]
Urinals cake don't show up because they are inside the drain cap

> Toilets look like lifeweb poop-holes, how could you sit on those?

I literally used the old toilet south sprite as baseline for the new one (the shape is the same)

**Comment by Militaires** [comment]
inconsistent and wonky dimensions overall

**Comment by nicbn** [comment]
How is it inconsistent?
Our current sprites alternate between 3/4 and sideview depending on the direction, and the urinals right now are a cardboard hanging in the wall.
We are aiming to move towards 3/4 perspective, how could using it be "inconsistent"?

**Comment by nicbn** [comment]
NT recent cuts to its budget removed all the lids - their employees are to be trained to work under shit smelling conditions.

**Comment by deathride58** [comment]
Those urinals look like shit. You could probably make them look better or more modern by making their bottom part a part of the floor, making use of overlays to put their bottom part on the floor layer and making the underneath of the bowl only visible if the floor underneath the urinal has exposed plating

The other sprites look fantastic tho 10/10

**Comment by subject217** [comment]
IIRC magic mirrors inherit the regular breaking stuff from mirrors including the icon state so you probably need to re-add the old broken mirror icon and update the code. Also, I don't see that magic_mirror icon in the diffs, are you sure you added it?

**Comment by nicbn** [comment]
magic_mirror is unchanged, that's why it won't show up

**Comment by anconfuzedrock** [comment]
It just looks fucking AWFUL without lids, sorry but the ugly sprites are reserved for beards.

**Comment by Memager** [comment]
May need to work on this a bit more

**Comment by zamolxius** [comment]
looks hideous

**Comment by Militaires** [comment]
by inconsistent i meant that the shapes of some of your sprites change between directions, look how wide the toilet bowl is when facing east vs facing south

**Comment by Militaires** [comment]
i think if you fixed just that it'd look much better

**Comment by nicbn** [comment]
The shape is actually the same, it's just rotated

**Comment by Militaires** [comment]
you shouldnt just take the bowl and rotate it 90 degrees, you'd do that if the perspective was top down

**Comment by nicbn** [comment]
What I mean is that the top face shape is rotated, the shading is changed to fit it - and of course, the other faces are adjusted so it's 4/3.

I did start by the south facing sprite to make the other dirs, and I did use the old south facing toilet sprite as base for the new one, if that's what you mean.

**Comment by nicbn** [comment]
I'll polish these sprites and PR them separately.

**Pull request closed without merging**
