### PR TITLE
 Fixes overlapping space ruins

### LINKED ISSUE #19768: Space Ruins Spawning On Top Of Each Other
srb33nx

Ahhhhhhhh

### LINKED ISSUE #19867: Ordinary Space Tile Issue
@Incoming5643 The satchel is not hidden.

### PR DESCRIPTION
**Pull request by Incoming5643**
Fixes a ton of area designation in space ruins that was causing ruin overlapping

Deconverts ruins that were converted to tgm because the primary reason to use tgm (reduces merge conflicts) doesn't really matter on small, isolated ruin files. It might also let them load faster?

Fixes #19768 
Fixes #19867

### CODE REVIEW

**Comment by PKPenguin321** [comment]
-40k lines :ok_hand:

**Comment by Bawhoppen** [comment]
the reason I converted them to TGM was because I mapmerged 60+ files all at once

**Comment by Iamgoofball** [comment]
Keep them on tgm, codebase standard.

**Comment by Incoming5643** [comment]
Most of the ruins are not in TGM

**Comment by optimumtact** [comment]
Yeah because of oldies like you

**Comment by Cheridan** [comment]
It's fine

**Pull request merged**
