### PR TITLE
fixes cult hardsuit size

### PR DESCRIPTION
**Pull request by imsxz**
either whoever coded this first was an idiot or had some really weird ideas on balance. the helmet is bigger than the suit itself ????

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
It's cult magic, just like the syndie hardsuit

**Review by ShizCalev — APPROVED** [review]

**Comment by uraniummeltdown** [comment]
"Fix"
this is a balance change

**Comment by uraniummeltdown** [comment]
Yes, the hardsuit has a small size because cult magick and so you can stash it away, bloodcult is about stealth

**Comment by Robustin** [comment]
Also the blood cult cant even make the hardsuits anymore, its a Lavaland relic now.

**Pull request merged**
