### PR TITLE
Converts Hydroponics oneharvest var and Potato's Battery Quality into Plant Genes

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Converts the `oneharvest` var on seeds into a plant gene.

The `oneharvest` var controls whether or not a plant can be harvested repeatedly (tomatoes, chillis, etc.) without the plant being cleared, or if it is cleared (wheat, rice, etc.). Instead of this being a var on the seed item itself, it's now a gene trait datum that can be extracted and placed on other plants.

For clarity, the gene you can extra would add/remove "multiple harvests".

You cannot, however, insert it into the Replica Pod seeds because well..that plant is kinda weird+snowflakey with regards to how it harvests.

Also, potato batteries now have a specific plant gene on them that can be spliced into other plants, allowing you to turn them into batteries. Not particularly exciting, or useful, but it adds support for a broader `on_attackby` system for plant genes, so...*shrug*

pic:

img1

Additionally, also turns plant types (normal, mushroom, or weed) into an attribute; by adding/removing these traits (only one plant type trait at a time!), the botanist should have some more control over how much water, light, and nutrients a plant needs---in addition to how impacted by weeds they are.

Lastly, adds in a stinging plant ability which will inject a plant's reagents into someone. when that plant is thrown at them (how much is based on potency); currently death nettle have this trait by default.

:cl: Fox McCloud
add: The ability to harvest a plant, repeatedly, is now a gene-extractable trait that can be spliced into other plants
add: can extract the battery capabilities of potatoes and splice them into other plants
add: Plants types are now gene traits that can be added/removed from plants
add: Adds new stinging plant trait that will inject a bit of a plant's reagents when thrown at someone
/:cl:

### CODE REVIEW

**Comment by Aloraydrel** [comment]
Neat

**Comment by Supermichael777** [comment]
infinity destroying angels

**Comment by MisterTikva** [comment]
More botany powercreep. I approve

**Comment by TehZombehz** [comment]
Finally, the botanist can make growing wheat a painless activity.
E-everybody thinks that, right? B-because we all care about wheat t-that the chef can use.
That botany will definitely grow instead of just making meme plants. R-right?
I'm sure we're on the same wavelength here.

**Comment by XDTM** [comment]
To give some perspective, this makes the plant last until its age goes above its lifespan, which can go up to 100 and is a transferrable gene. After the initial growth period, you get a harvest every [prod. speed] plant cycles, which go as low as 1. A harvest can contain ~5-10 plants with robust harvest and max yield.
So yeah, up to 1000 plants per tray, especially if you gaia them so they don't need mainteinance.

Not saying this will be a balance issue, since you could just transfer the chems you need onto tomatoes, but i'm just pointing out that botany does that.

**Comment by MisterTikva** [comment]
> A harvest can contain ~5-10 

13 at 10 yield and robust harvest

**Comment by FantasticFwoosh** [comment]
Well, i've already theorycrafted my new left 4 zed (unstable mutagenless) meta for this PR.

I can only think of a few instances where you might want to ADD this gene rather than subtract it, as per dangerous effects (exploding plants without 'seperated-chems' traits or as a self limiter to stop people abusing them)

**Comment by XDTM** [comment]
The gene is the multiple harvest, not single harvest, despite the pr name

**Comment by Fox-McCloud** [comment]
Question for those here---should I convert potato battery's "can be turned into a cell with cable coil" into a trait that can be spliced out and added to any plant?

code wise, it's not that difficult, and could mean more OOP `attackby` in the future, based on gene traits and not the `grown` itself.

**Comment by RemieRichards** [comment]
yeah why not.

**Comment by SgtxRootbeer** [comment]
But what about the sprites for the banana-battery or whatever new batteries get created?

**Comment by PKPenguin321** [comment]
Also make sure it doesn't break potato batteries that exist pre-made on the map

**Comment by Fox-McCloud** [comment]
Alrighty, went ahead and did the potato battery thing; it's not particularly exciting, but it does mean more OOP `attackby`'s in the future based on plant genes, rather than the object itself.

**Comment by Fox-McCloud** [comment]
Will try to get the commit up, once Github's service outage ends...won't even sync up properly...

**Comment by Fox-McCloud** [comment]
Going to re-submit this---something went wrong during the outage.

**Comment by Fox-McCloud** [comment]
@RemieRichards 

Can you think of anything else that could be pushed into traits? Not saying I'll do it, for sure, just looking for ideas.

**Comment by FantasticFwoosh** [comment]
How do chems affect the batteries? As i sort of remember it scaled with potency before.

Glowcap/Electrical activity should super-charge these batteries, pretty well.

**Comment by AnturK** [comment]
Might sound kinda silly , but taste gene ? A message on how it tastes when eaten. So we can have apples tasting like oranges. Might be too boring.

**Comment by Fox-McCloud** [comment]
>How do chems affect the batteries? As i sort of remember it scaled with potency before.

Glowcap/Electrical activity should super-charge these batteries, pretty well.

The existing functionality is retained; the only thing this does is make it so that the effect is moved from the potato `grown` to a gene.....anddd it gets its own icon based on the grown you use the cable coil on.

**Comment by XDTM** [comment]
Spiky gene, to make it behave somewhat like nettles, aka hurts on touch/eat. Should do potency scaling brute damage, converted to burn damage + stun if there's acid in the genes (like deathnettle). Maybe even inject a portion of the chemicals inside when stung.

**Comment by Fox-McCloud** [comment]
Turned plant types into a gene...now you should be able to have some control over how weed resistant/nutrition/water/light a plant needs.

**Comment by MisterTikva** [comment]
How about something like 'Micro Stingers' that would inject plant chems into the target on hit/throw/squash/slip?

**Comment by XDTM** [comment]
Does alien properties do anything yet?

**Comment by Fox-McCloud** [comment]
>Does alien properties do anything yet?

Nope; it's been around forever, but there's never been a plant that uses it.

**Comment by Fox-McCloud** [comment]
@MisterTikva 

Adding in a stinging trait; death nettles have them by default; if you thrown a grown at someone it will inject them with the reagents inside--how much it injects them with it based on the potency of it.

**Comment by optimumtact** [comment]
These better not be too powerful

**Comment by Chocobro** [comment]
@Fox-McCloud fix the sprites
there's wires on the corn and banana that aren't connected to anything

**Pull request merged**
