### PR TITLE
Improves some of the dress sprites

### PR DESCRIPTION
**Pull request by optimumtact**
I want to be the pretty princess
:cl: oranges
tweak: Removed the 'gloves' from the sailor dress which looked weird since it was a blouse basically
tweak: Made the skirt on the blue/red skirts less blocky, 
tweak: Made the striped dress consistent at every direction
/:cl:

red skirt
blue skirt
striped skirt
sailor skirt
invisible skirt

### CODE REVIEW

**Comment by Zilenan91** [comment]
piiiiiiics

**Comment by optimumtact** [comment]
Hohohoh baby, just let me shave my legs

**Comment by Zilenan91** [comment]
oh damn it's kicking off

**Comment by optimumtact** [comment]
There you go

**Comment by Shapsy** [comment]
But these are all skirts

**Comment by Incoming5643** [comment]
:+1: for actually making sure the dresses look properly on men

**Comment by WJohn** [comment]
I mean I suppose this is an improvement. Sure why not.

**Comment by Aranclanos** [comment]
>Sure why not

**Pull request merged**
