### PR TITLE
Moves Listening Post to Z6, removes it as an away mission

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Listening Post is very short/small with little to do, and is not very suitable as an away mission.

We do however need more random shit in space to stop body loops, and this is already mapped, so it seemed like a good idea.

The only loot here is bananium (already obtainable elsewhere on the map), the listening machines, and a single stetchkin if you crack the floor safe, so I don't think it will encourage mass amounts of people to abandon ship or unbalance the round.

I believe Hippie already did this

:cl: Kor
rscadd: The away mission Listening Post, originally mapped by Petethegoat, has removed as a mission. It is now present in normal deep space.
/:cl:

### CODE REVIEW

**Comment by Incoming5643** [comment]
I don't mind making it general space debris, but you CANNOT put ANYTHING on z = 6.

Because z = 6 is the original "deep space" z level it's used in a few instances as a place assumed to be homogeneously space with nothing in it.

Off the top of my head I know that if you were thrown/fell off a shuttle in transit, you'd end up at a random point in z = 6. If this was there you could spontaneously appear on the listening post.

Any other z level is fine, including z = 7, "deep space 2: electric boogaloo"

**Comment by KorPhaeron** [comment]
@Incoming5643 

Shit, thanks

**Comment by WJohn** [comment]
:+1: Thank you.

**Comment by PKPenguin321** [comment]
more space content es bueno. :+1:

**Comment by Zilenan91** [comment]
Ees good :+1:

**Comment by Jordie0608** [comment]
@Incoming5643 Actually it picks a random level between 3 and 7
https://github.com/tgstation/-tg-station/blob/master/code/game/turfs/space/transit.dm#L14

**Comment by KorPhaeron** [comment]
@Jordie0608 

So is this fine then?

**Comment by Incoming5643** [comment]
Someone improved the check while I wasn't looking

**Comment by neersighted** [comment]
:+1:

**Pull request merged**
