### PR TITLE
Prevents you from obtaining every power every round.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: Spacemen deoxyribonucleic acid degradation from centuries of cloning has resulted in loss of structural enzyme blocks, helping reduce the dwarf-hulk-xray-tk hordes. 
/:cl:

### CODE REVIEW

**Comment by XDTM** [comment]
So why would someone play geneticists now

Just remove hulk

**Comment by kevinz000** [comment]
No

**Comment by kevinz000** [comment]
Fuck off good.

**Comment by BeeSting12** [comment]
19 to 5 is pretty dumb

**Comment by Iamgoofball** [comment]
It can probably be raised, but the number as it stands is horrible.

**Comment by XDTM** [comment]
If you want to do it properly impement something like goon where it's far easier to activate it if you have it, but there are other avenues to get them even if you don't have them, like rad-rerolling or using injectors after "researching" the gene off someone who has it

**Comment by Iamgoofball** [comment]
I'd love to port goonetics fullscale

**Comment by Mercenaryblue** [comment]
I'm okay with limiting the number of powers they can find each round.
But they should be able to find at least 3, if not 4.

**Comment by Iamgoofball** [comment]
This PR does that.

**Comment by RandomMarine** [comment]
What if I want to fuck somebody up with all the disabilities?

And are you SURE that the monkey SE is guaranteed to exist in this case?

**Comment by Iamgoofball** [comment]
Monkey SE always exists, hardcoded.

**Comment by MimicFaux** [comment]
Idea: Genetics equipment is limited by what blocks it can irradiated by equipment tier level.

**Comment by Iamgoofball** [comment]
Time gates are worthless. No.

**Comment by Bawhoppen** [comment]
Goof you probably shouldn't have made this PR cause I know people are thumbsing it down just cause it was you who made it

**Comment by Incomptinence** [comment]
Stupid way to do it. 

Limit the number of power blocks but leave disability blocks unchanged.

Time gates are shit but this basically means if hulk is in the mix it is found then starts ruining the round near instantly every time. Similar for round start xray being the end of privacy good luck doing treason after 5 minutes into the round.

**Comment by TribeOfBeavers** [comment]
If this gets merged, the research value of DNA injectors should be changed. Its based around the number of powers in the injector, and is one of the few ways to get engineering 6

**Comment by Iamgoofball** [comment]
@KorPhaeron

**Comment by optimumtact** [comment]
I dont' think this is the right approach, we should aim to make genetics more complex such that getting the powers at all becomes the acheivement

**Pull request closed without merging**
