### PR TITLE
Removes persistent messages

### PR DESCRIPTION
**Pull request by AnturK**
As promised in #23176 

This seems to be average usage:

### CODE REVIEW

**Comment by TehZombehz** [comment]
This is why we can't have nice things.

**Comment by KorPhaeron** [comment]
I think this is salvageable if you add a way to actually remove messages regularly instead of requiring the librarian to use his three chisel charges, which he'll obviously just make more messages way

**Comment by ChangelingRain** [comment]
Also, messages should not be any input you want! God damn it @coiax we told you this and you didn't listen.

**Comment by Haevacht** [comment]
Preset phrases if its a fucking soapstone.

**Comment by SweaterKittens** [comment]
I  know this is a gray area, but we /could/ just deal with shit like that in the same way we deal with spam. I've seen a lot of really great soapstone messages and it'd be a bummer to see them all go because of shit like this.

**Comment by coiax** [comment]
Also, this literally looks like one guy spamming a bunch of non-creative messages for the purpose of being an asshole. Are we going to remove this feature because of one asshole?

**Comment by swindly** [comment]
Limit the number of messages displayed per round?

**Comment by ChangelingRain** [comment]
I told you, make the messages like dark souls, and then you didn't do it.
Yes, potentially you can get rid of these, but NOBODY WILL BECAUSE THEY'RE TOO BUSY MAKING THEIR OWN MESSAGES

**Comment by KorPhaeron** [comment]
@AnturK 

I think its fair that we give coiax at least one or two chances to fix it before a revert, I'll reopen it if it's still an issue after the changes that are about to be PRd

**Comment by KorPhaeron** [comment]
I'd just put DNM on this but nobody respects that tag anyway

**Comment by Xhuis** [comment]
I'ma give this a vocabulary if you don't do it yourself y'hear

**Pull request closed without merging**
