### PR TITLE
Adds dab emote

### PR DESCRIPTION
**Pull request by gy1ta23**
## Changelog
:cl:
add: Added dab emote
/:cl:

## About The Pull Request
Adds an emote that makes you dab. The reason that emote.dm was deleted and replaced is that I am using only the github web editor because I can't be fucked to use desktop.

## Why It's Good For The Game

Before, every time somebody wanted to dab they would have to go spend five extra seconds using the me command, costing precious time. Now, you can quickly just type *dab to dab, right in the comfort of your own home. This will make the game approximately three times better, and helps to encourage meaningful interdepartmental interaction and promote workplace health and safety.

### CODE REVIEW

**Comment by gy1ta23** [comment]
This is the peak of the human race, it is all downhill from here

**Comment by literallytrash0** [comment]
image

**Comment by wesoda25** [comment]
Give it a chance to just fucking send your arms flying

**Comment by gy1ta23** [comment]
> Give it a chance to just fucking send your arms flying
that would require the slightest bit of competence

**Comment by tralezab** [comment]
i can code you the arms flying off, 1% chance to happen yes?

**Comment by gy1ta23** [comment]
I mean I would say that's a good idea but on the other hand this pr would be instantly closed

**Comment by literallytrash0** [comment]
> 
> 
> i can code you the arms flying off, 1% chance to happen yes?
> 
> warning: i am not responsible for any closed prs due to adding double limb dismemberment

I could probably (shit)code it in since I'm already working with him on this

> 
> 
> I mean I would say that's a good idea but on the other hand this pr would be instantly closed

nah it's a great idea let's do it

**Comment by gy1ta23** [comment]
> I could probably (shit)code it in since I'm already working with him on this

you literally did nothing

**Comment by literallytrash0** [comment]
> 
> 
> > I could probably (shit)code it in since I'm already working with him on this
> 
> you literally did nothing

how about we don't start an argument here since we know how that literally always works

**Comment by optimumtact** [comment]
webeditors don't get to make meme code

**Pull request closed without merging**
