### PR TITLE
Role spawn landmarks now have icons instead of Xs

### PR DESCRIPTION
**Pull request by coiax**
No user facing changes, but mapmakers please prepare yourself for the
BRAXTON CHERRY ZONE.

image

### CODE REVIEW

**Comment by as334** [comment]
How does a person making a new job go about creating more of these icons?

**Comment by coiax** [comment]
I, uh, just spawned my guy on a void tile on City of Cogs, coloured that turf red, used the Select Equipment option, screen shot, then copied the red tile into the Dream Maker client, filled the red with transparent, named it, and that was that...

It really wasn't that hard.

**Comment by XDTM** [comment]
and here i am taking pictures for the wiki by manually putting limbs together to make a human and the copypasting the clothes on top

**Comment by coiax** [comment]
@lzimann says he has a better way, linked to something in chat

**Comment by lzimann** [comment]
```
/proc/get_all_jobs_icons(datum/preferences/prefs)
	var/mob/living/carbon/human/dummy/D = new
	D.setDir(SOUTH)
	if(prefs)
		prefs.copy_to(D)
	var/icon/final = icon()
	for(var/job in subtypesof(/datum/job))
		var/datum/job/J = new job
		for(var/obj/item/I in D)
			qdel(I)
		J.equip(D, TRUE, FALSE)
		COMPILE_OVERLAYS(D)
		final.Insert(getFlatIcon(D), J.title)
	fcopy(final, "icons/effects/job_landmarks.dmi")
```

just a simple thing, generates an icon like this:


might want to need/want to add a check for AI and cyborgs though

**Comment by optimumtact** [comment]
loook at mr fancy over here

**Comment by duncathan** [comment]
@coiax you should use lzi's method and have consistent icons like that

**Review by duncathan — CHANGES_REQUESTED** [review]
you should use lzi's method and have consistent icons like that so that they aren't any one player yfeel

**Comment by Bawhoppen** [comment]
Put a red background block behind them perhaps? Will be more obvious, they seem to blend in a little

**Comment by Bawhoppen** [comment]
Also all you have to do for sprites is just paste clothing sprites onto a naked human body sprite (which I can give you here: https://puu.sh/yJxtc/2985d57431.dmi)

Same rule applies for making simple mob human sprites

**Comment by ShizCalev** [comment]
put them ontop of red x's :^)

**Comment by lzimann** [comment]
If you use my proc, remember to change the icon state of landmarks to match the job titles. Also I can probably add a background of some sort to the icon generation if that's really needed/wanted.

**Comment by ShizCalev** [comment]
Closing in favor of #33714

**Comment by coiax** [comment]
:(

**Pull request closed without merging**
