### PR TITLE
partial revert of #11699, fixes #11850 without breaking #11699

### LINKED ISSUE #11850: Hair does not reappear on humans when removing an EVA helmet.
Think this is caused by changes in #11699. I'm testing a patch.

### PR DESCRIPTION
**Pull request by feemjmeem**
Fixes #11850 
#11699 fixed a lizard sprite bug but this particular change doesn't SEEM to have been necessary; I tested back and forth and lizard appearance between the full change in that PR and the section I removed in this one is identical, but this one restores the expected human hair behavior.

@Jordie0608 can you verify that what you fixed is still fixed in this?

### CODE REVIEW

**Comment by Incoming5643** [comment]
It feels redundant since there's an update hair in the child as well, but maybe I'm missing something here

**Comment by feemjmeem** [comment]
I would have thought so too. But this fixes the problem experienced in #11850 which was introduced by #11699.

**Comment by Jordie0608** [comment]
@feemjmeem #11699 was @Incoming5643's PR

**Comment by feemjmeem** [comment]
So it was! My brain hurts. @incoming5643, same question.

**Comment by Incoming5643** [comment]
It's not even really a revert, the <i>functionality</i> of that pull is still in, it's just that what I thought was a redundant piece of code apparently wasn't

**Pull request merged**
