### PR TITLE
Food bags

### PR DESCRIPTION
**Pull request by Thlumyn**
## About The Pull Request
Creates food bags. 

Food bags can be purchased at the ChefDrobe vendors or crafted out of 4 cloth. 

Food bags can hold food, condiments and trash (as many food items like waffles produce trash)

Food bags can be worn on the suit item slot of chef aprons, as this is intended to be a chef item.

## Why It's Good For The Game
I play chef. When I play chef, I use a bluespace trashbag to shove all my food into. I have seen other chefs do that too. This isn't good for multiple reasons: 
1. It's not the intended purpose
2. It's NASTY, from a roleplay perspective, I don't want to see my chef dump a trashbag full of pizza slices onto the counter and call it a day 
3. It limits players to tiny or small sized items, while there's tons of amazing normal sized food items, especially with the recent food PRs. 

Now you might be saying, "but Thlumyn we already have a serving tray, and that's a bag subtype for food" 

Yes, but, serving trays are bulky items which makes sense given what they are and what they can carry (eg: fancy boxes - makes 100% sense to not have a regular bag hold a normal sized storage object) - but it's a pain, especially when you ditch the chef apron for aesthetic reasons. Food bags sacrifice a lot of the variety of items they can carry (as compared to serving trays) for more capacity and a smaller item size.

Overall this is hopefully going to add to the quality of life for chef players without messing with any balance, especially on the larger roleplays where they have to crank out food at industrial speeds. 

## Changelog
:cl:
add: food bags
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
please expand on your changelog it is not helpful to players

**Comment by Thlumyn** [comment]
edited changelog and comment, to try and word things better.

**Comment by MrMelbert** [comment]
I don't know if I like us ditching the flavor of the serving tray for "just another magic bag", especially since it fits in the same slot as the tray (belt slot)

If anything I feel like the tray could use a small nudge(buff) so carrying 7 donuts is not equal to carrying 7 full pizzas. 

~~Or a bluespace tray~~

As an aside how is a wedding cake not a bulky item? You're telling me two full wedding cakes fit in that pouch?

**Comment by Wallemations** [comment]
> ~~Or a bluespace tray~~

Ah yes let me reach into my black hole on a platter real quick


I think a bluespace tray is a hilarious idea though I have no clue whatsoever how it would be done.

**Comment by Thlumyn** [comment]
Genuinely willing to code anything as long as I get to carry more than 7 food items at a time while trying to feed a server with 150 people online for 3 hrs straight
A bluespace platter, probably an item that'd need research (tacked onto some other research ofc not its own thing), would be hilarious

**Comment by MrMelbert** [comment]
I think it would be hilarious if we added a "Large Tray That Happens To Be Blue" and the description was just something like "It's got nothing to do with bluespace, it's just a larger platter. But we painted it blue to fit the theme." 

> Genuinely willing to code anything as long as I get to carry more than 7 food items at a time while trying to feed a server with 150 people online for 3 hrs straight

You're gonna hate me for suggesting this, but, have you tried the food cart?

**Comment by Dorsisdwarf** [comment]
I gotta agree with MrMelbert that I kinda don't like the "everything goes in identical recoloured autobags" approach to inventory management. It takes away from a lot of the game feel of serving your shit and counter space managing.

If you find yourself needing to take lots of food items out of the kitchen why not, like, give the chef a serving trolly he can drag around and quickly load/unload with his tray.

**Comment by Wallemations** [comment]
> I think it would be hilarious if we added a "Large Tray That Happens To Be Blue" and the description was just something like "It's got nothing to do with bluespace, it's just a larger platter. But we painted it blue to fit the theme." 


That's way funnier than what I thought of, which would be "Using bluespace technology this tray's surface area is mathematically 1,000 square meters."

**Comment by optimumtact** [comment]
> edited changelog and comment, to try and word things better.

They mean this bit
```


🆑
add: food bags
/🆑
```

as this is the bit players will see in game.

**Comment by BlueMemesauce** [comment]
we already have paper sacks meant for food
holding food in an actual bag is weird

**Comment by Thlumyn** [comment]
> > edited changelog and comment, to try and word things better.
> 
> They mean this bit
> 
> ```
> 
> 
> 🆑
> add: food bags
> /🆑
> ```
> 
> as this is the bit players will see in game.

Huh? I did change it 

Github undid all my other changes too... bleh this is annoying

**Comment by BlueMemesauce** [comment]
Just click on the edit history and copy paste what github removed, it does that sometimes

**Pull request closed without merging**
