### PR TITLE
Fixes MC crashing

### PR DESCRIPTION
**Pull request by AnturK**
Closes #25801 

Joan,Cyberboss please.

### CODE REVIEW

**Comment by Cyberboss** [comment]
But wait.... THERE'S MORE!!!!!!

https://github.com/tgstation/tgstation/pull/25808/files#diff-5fe917b04da5e766a5720a8a9bd49caeR7

**Comment by AnturK** [comment]
Yes that's the joke. Infinite recursion.

**Comment by Cyberboss** [comment]
That's supposed to be for `/datum/round_event_control/falsealarm`...

**Review by Cyberboss — APPROVED** [review]
>No runtime log why BYOND? :(

**Pull request merged**
