### PR TITLE
improves balance

### PR DESCRIPTION
**Pull request by Kylerace**
## Changelog
:cl:
balance: improves balance so players have a better experience
/:cl:

### CODE REVIEW

**Review by JohnFulpWillard — APPROVED** [review]
please merge after https://github.com/tgstation/tgstation/pull/72551 it adds support for this

**Review by MrMelbert — APPROVED** [review]
this one's less funny to the non-coders

**Comment by Kylerace** [comment]
[Kylerace](https://github.com/Kylerace) approved these changes now

**Comment by bruhman8ghughug** [comment]
glad balance was improved

**Comment by DAKKA-WAAAGH** [comment]
Based and QOLpilled

**Comment by RigglePrime** [comment]
Great PR

**Comment by Wallemations** [comment]
does `INITIALIZE_HINT_QDEL` just delete the toolbox?

**Comment by Xander3359** [comment]
> does `INITIALIZE_HINT_QDEL` just delete the toolbox?

Yes exactly, the team "nerfing what kills us" is nerfing what killed them in the toolbox tournament.

**Comment by Kylerace** [comment]
waiiit a minute i made this joke the day before

**Pull request closed without merging**
