### PR TITLE
[s]enables halloween module

### PR DESCRIPTION
**Pull request by Shadowlight213**
For testmerging.

### CODE REVIEW

**Comment by kevinz000** [comment]
what does this do

**Comment by optimumtact** [comment]
Someone doesn't know how to properly use the holiday events system so they added a file you tick to make closets trapped instead of doing something sane

**Comment by Iamgoofball** [comment]
@optimumtact i believe it predates the system, we should fix that

**Comment by Jordie0608** [comment]
@Iamgoofball Unfortunately not the case

**Comment by Iamgoofball** [comment]
fuck

**Comment by AnturK** [comment]
Should probably be ported over yeah.

**Comment by Shadowlight213** [comment]
Halloween is ogre.

**Pull request closed without merging**
