### PR TITLE
tgui-next: Radio, ORM, Solar Tracker

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

New radio interface.

- Station intercoms
- Headsets
- Station bounced radio
- Cyborg radio (has subspace tx on/off button instead of high volume)

image

New Ore Redemption Machine interface.

image

Solar Tracker interface.

image

> P.S. I might later add more interfaces to this pull request, to save on rebuilds.

## Changelog
:cl:
add: New Radio interface.
add: New Ore Redemption Machine interface.
add: New Solar Tracker interface.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
What does the little bar on the left represent?

**Comment by bobbahbrown** [comment]
> What does the little bar on the left represent?

it's the position in the range of possible numbers for that field, you may have seen it in-game already on other UI elements.

**Comment by PKPenguin321** [comment]
If we're going to just tell them the channel name of the current radio frequency on the radio UI itself, we may as well add a button that lets you choose from a list of known frequencies

**Comment by stylemistake** [comment]
> If we're going to just tell them the channel name of the current radio frequency on the radio UI itself, we may as well add a button that lets you choose from a list of known channels

I kinda dig the feel of manually tuning in, and when a good frequency was found, station name pops up.

**Comment by Learner10** [comment]
> 
> 
> > If we're going to just tell them the channel name of the current radio frequency on the radio UI itself, we may as well add a button that lets you choose from a list of known channels
> 
> I kinda dig the feel of manually tuning in, and when a good frequency was found, station name pops up.

Agreed. There's something right about it, kind of like tuning your radio between the static and finding something usable. This does make me wonder though, if someone attempts to create their own radio channel (assuming they were able to first of all, and name it as well), would it display the name of said channel?

**Comment by stylemistake** [comment]
> This does make me wonder though, if someone attempts to create their own radio channel (assuming they were able to first of all, and name it as well), would it display the name of said channel?

That would be a cool feature to code someday. Right now, it only displays two preset channels.

**Comment by stylemistake** [comment]
Implemented an `Input` component, updated documentation, fixed some bugs with NumberInput, added @actioninja's interface conversion guide draft (which is pretty good), and finally, remove `KitchenSink` from the production build which save us about 6-8KB.

**Comment by actioninja** [comment]
This looks good to go.

**Pull request merged**
