### PR TITLE
Adds recharger to Cerestation's shuttle and Removes Centcomm's thunderdome doors

### LINKED ISSUE #26050: somebody added doors to the thunderdome that you can just smash down with weapons and walk out of and get into centcomm through
please remove these doors the separation between the thunderdome and the rest of centcomm must remain absolute

### PR DESCRIPTION
**Pull request by BeeSting12**
:cl: BeeSting12
fix: Cerestation's shuttle now has a recharger.
del: Centcomm's thunderdome airlocks have been removed due to contestants breaking out.
/:cl:
Why: It's basically box's shuttle and box's shuttle has a recharger so logically Cere's would too
Why: Fixes #26050

I goofed and PRed the contents of #26082 with this one so I closed that one. Sorry.

### CODE REVIEW

**Comment by BeeSting12** [comment]
what did I just merge from the wrong branch or something? fuck it I'm too lazy, closing my other PR and leaving this open

**Comment by KingPhilipIII** [comment]
I dunno. It's not like thunderdome fighters aren't under admin supervision. Why remove the doors. If the admins don't want you to walk through the door they can stop you, but I like having the door there in case they let you through.

**Comment by Bawhoppen** [comment]
Yea don't remove those doors, they serve the purpose if any admin wanted to host an event with the crew on centcomm, which means they're under admin watch regardless.

Also you should remove it to atomize your PRs anyways.

**Comment by BeeSting12** [comment]
Yeah, I know that I should atomize, but somehow I screwed up and had both fixes in this PR so I just closed the other one. If the admins want people to exit the thunderdome, they can teleport them out or delete the wall and add an airlock themselves.

**Comment by Bawhoppen** [comment]
Also why does the Cerestation shuttle need a recharger anyways?

**Comment by BeeSting12** [comment]
It's a copy of boxstation's shuttle. Boxstation's shuttle has a recharger but mmmiracles used an outdated copy of the shuttle. I'm adding one since I'm assuming this is an oversight.

**Comment by PKPenguin321** [comment]
thunderdome doors must die

**Pull request merged**
