### PR TITLE
Adds the smelly mutation

### PR DESCRIPTION
**Pull request by Time-Green**
An inconvenient mutation that makes you lose hygiëne faster.
:cl: Time-Green
rscadd: Adds the smelly mutation
/:cl:
Inspired by PKpenguins PR

I'm also not exactly sure what a balanced hygiëne loss should be, so if someone thinks it's too much or too lite, please say so.

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Make them sweat so much it extinguishes them while releasing a fuck ton of miasma

**Comment by Time-Green** [comment]
miasma is handled by hygiene. Sometimes applying negative firestacks is a fun idea

**Comment by HomocidlePancakes** [comment]
Will they stand out somehow, or do they just get dirtier faster? I want to see a lynch mob to form around someone with this trait forcing them to shower.

**Comment by Time-Green** [comment]
They just get dirtier faster

**Comment by HomocidlePancakes** [comment]
Sad.

**Comment by PKPenguin321** [comment]
Hygiene normally decrements by 0.025 a tick. This would make it 3.025 a tick, which is 121x faster. Probably a bit much...

**Comment by HomocidlePancakes** [comment]
>
BUT ISNT THAT THE WHOLE POINT?

**Comment by OverlyGeneric** [comment]
There is actually a smelliness mutation in the real world.

https://en.wikipedia.org/wiki/Trimethylaminuria

I would recommend naming the mutation after this and smell like a fish.

**Comment by Anonymous583** [comment]
Oh yes...very good!....very sloppy and wet my dear....hmmmmm...is that a drop of nugget I see on the rim?...hmmmm.....let me.....let me just have a little taste before the sniff my darling.......hmmmmm....hmm..yes....that is a delicate bit of chocolate my dear....ah yes....let me guess...curry for dinner?....oh quite right I am....aren't I?....ok....time for sniff.....sssssnnnnnnniiiiiiiiffffffff.....hmmm...hhhmmmmm I see...yes....yes indeed as well curry......hmmm....that fragrance is quite noticeable....yes.....onion and garlic chutney I take it my dear?.....hmmmmm....yes quite.....

**Comment by 81Denton** [comment]
@datorangebottle There is no "we", this is all volunteers that do it for free. If you're not a fan of hygiene, you can also open a PR that removes the feature.

**Pull request closed without merging**
