### PR TITLE
Adipem Utensils

### PR DESCRIPTION
**Pull request by RaveRadbury**
Many apologies to @Krysonism this is something that I was planning back on the 4th of February but only got the sprites for today.

## About The Pull Request
Originally I was going to try and abstract the omelette fork behavior to all other foods, but @Qustinnus has other plans for eating with utensils and convinced me not to. So now I am left with these sprites that Adipem made. They are nice.
image
This PR adds sprites by Adipem (of Bread Sprite Update #56498 fame).

Changed sprites: Kitchen Knife, Fork, Spoon, Plastic Knife, Plastic Fork, Plastic Spoon, Butcher Knife, and Forkloaded

## Why It's Good For The Game
They look great 

## Changelog
:cl: AdipemDragon
imageadd: New cutlery sprites
/:cl:

closes #57488 
closes #57489 
closes #57490 
closes #57491

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Shoot, I missed marking this as a draft, and it's *obviously* a draft, smh

**Comment by AdipemDragon** [comment]
wow hi yes it's my sprites, can't wait to see em realized

**Comment by MrDoomBringer** [comment]
what did kyrson do to deserve this all he wanted was the 12 gbp

**Comment by RaveRadbury** [comment]
> what did kyrson do to deserve this all he wanted was the 12 gbp
Yeah tbh I feel terrible that out of anyone to have this kind of moment with it had to be Kryson

Sorry Kryson. 😞

**Comment by cacogen** [comment]
These ones look wavy, like an oil painting. I prefer the knife and cleaver slightly to Krysonism's, though.

**Comment by RaveRadbury** [comment]
> These ones look wavy, like an oil painting. I prefer the knife and cleaver slightly to Krysonism's, though.

Yeah might have to separate out specific bits depending on what how the review goes.

**Comment by KathrinBailey** [comment]
Napalm bombing Krysons Vietnamese good boy rice field farms are we?

**Comment by necromanceranne** [comment]
healthy competition never hurt anyone.

**Comment by maxymax13** [comment]
this is some vg grade soulful spriting

**Comment by KathrinBailey** [comment]
I like Adipem's chef's knife and cleaver more, and Krys's spoon and fork more.
They're both very very close contenders though and they're all wonderful.
I do think the sprite sizes for the fork and spoon are a little big though. I know it's real hard with 32x32, but near full tile-size...

**Comment by MrDoomBringer** [comment]
>but near full tile-size

this is the correct observation I think, having a fork+knife+plate on a single table is gonna look ridiculous with these, as opposed to our current/kryson's sprites

**Comment by Twaticus** [comment]
while i do enjoy the cartoony style its got going on, i prefer krysons versions

**Comment by MrDoomBringer** [comment]
champion

**Comment by notdonte** [comment]
I prefer the cleaver and kitchen knife in this over kryson's version being honest.

**Pull request closed without merging**
