### PR TITLE
Removes the thunderdome doors on Centcomm

### LINKED ISSUE #26050: somebody added doors to the thunderdome that you can just smash down with weapons and walk out of and get into centcomm through
please remove these doors the separation between the thunderdome and the rest of centcomm must remain absolute

### PR DESCRIPTION
**Pull request by BeeSting12**
:cl: BeeSting12
del: The thunderdome's doors were removed.
/:cl:

Why: Fixes #26050

### CODE REVIEW

**Comment by BeeSting12** [comment]
why the hell did I remove floor

**Comment by PKPenguin321** [comment]
thanks

**Comment by PKPenguin321** [comment]
oh there's a door on both sides by the way
https://puu.sh/vfawf/aabd41e5b2.jpg
the one at the top left in this image and the one on the opposite side

**Comment by BeeSting12** [comment]
Yeah I did remove both, just checked in dreammaker. And I remembered that if the wall is covering it who cares if the floor is gone

**Comment by BeeSting12** [comment]
Okay I accidentally put the contents of this PR in #26086 so I'm just closing this one.

**Pull request closed without merging**
