### PR TITLE
Ports closets from Oracle (which ported from Goon)

### PR DESCRIPTION
**Pull request by nicbn**
CEV alternative: https://github.com/tgstation/tgstation/pull/56350

## About The Pull Request

Ports Oracle (which ported from goon) closet icons, with some adaptation.

I just moved all other closet sprites into goon folder, but I'm not sure if this is ok, notify me if it isn't.

## Why It's Good For The Game

image
image
image
image
image

## Changelog
:cl:
imageadd: Ported Oracle / Goon closets.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I can feel the :soul: draining out of my body.

**Comment by Tlaltecuhtli** [comment]
fridge is just a downgrade rest is worse at best

**Comment by Coastfront** [comment]
Soul-less

**Comment by maxymax13** [comment]
now port the cool yogstation animated closet doors

**Comment by ZeWaka** [comment]
Do you have a link to Oracle's PR?

**Comment by BeloneX** [comment]
Real G's remember Oracle Station....

**Comment by maxymax13** [comment]
i don't think getting any *more* sprites into the /goon folder licensefuck is a good thing, ideally you'd want to replace the existing ones inside it

**Comment by bluetshirtguy** [comment]
you know if they actually looked much better i'd be inclined to really like this but it's not really much of a change in the better sprite direction.

**Review by AnturK — CHANGES_REQUESTED** [review]
Sorry but we're not expanding the goon sprites directory more. If you want to add these sprites find the authors and include them normally with proper attribution (assuming you get compatible license). I'm going to close this PR if not.

**Comment by Ziiro** [comment]
> Do you have a link to Oracle's PR?

Nov 5, 2017
https://github.com/OracleStation/OracleStation/pull/242

**Comment by cacogen** [comment]
Why are you doing this? I'm almost certain there are better looking closet sprites out there. But ours don't need replacing again. They already look good. There are plenty of shitty sprites in this game (some of which pre-date /tg/station) which are just begging to be replaced (even if it's just by porting other servers' replacements over). 

I will never understand this need to replace our current sprites with sprites that look worse and/or don't fit the de facto art style. It's done to certain sprites over and over again while ancient ones you could replace with almost anything and see an improvement remain unchanged.

**Comment by Dorsisdwarf** [comment]
these are just our current locker sprites with an ugly border, yuck

**Comment by interestingusernam3** [comment]
This sucks

**Comment by nicbn** [comment]
> these are just our current locker sprites with an ugly border, yuck.
>
> (As in I'm pretty sure our current locker sprites, which are not very old, are based on these sprites from goon but improved)

Actually when I sprited our current locker sprites I just took the old skew perspective ones and added a top to them.

One of the reasons I dislike them is the lack of a border actually, as they seem to be just flat closet doors in an assembly. Also the colors in them are awful, but the color in these are mostly the same so meh.

> Sorry but we're not expanding the goon sprites directory more. If you want to add these sprites find the authors and include them normally with proper attribution (assuming you get compatible license). I'm going to close this PR if not.

**Comment by nicbn** [comment]
Closing this in favor of the CEV icons

**Comment by itseasytosee** [comment]
>Closing this in favor of my own pr
>your own pr get closed 3 hours later

**Pull request closed without merging**
