### PR TITLE
Fixes addiction text

### LINKED ISSUE #35695: Man suffering from addiction has identity crisis.
dreamseeker_2018-02-15_11-54-43

### PR DESCRIPTION
**Pull request by praisenarsie**
Fixes #35695

### CODE REVIEW

**Comment by 81Denton** [comment]
FUCK TOO SLOW

**Comment by Buggy123** [comment]
"You want some X." is arguably _more_ common than "you want to have some X". I'd argue that this PR is actually _less_ grammatically correct than the current grammar.

English has no central authority like some other languages, it is defined as the sum of the language of everyone who speaks it. If the majority of people speaking (a dialect of) English say "You want some X.", then by definition it is proper grammar.

**Comment by 81Denton** [comment]
speedmerge this

**Comment by praisenarsie** [comment]
who cares

**Comment by ShizCalev** [comment]
This is an informal idiom and _is_ considered grammatically correct in American English.

Example:
"What would you like to eat?"
"I feel like some Chinese (food)!"
or
"I feel like some pasta!"

You aren't saying that you feel like you are pasta, but instead you are saying that you have a desire to eat pasta.

**Comment by Buggy123** [comment]
That yeah

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
