### PR TITLE
The Cratening (Crate Resprite)

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
ITS TIME!

This PR, in preparation to the upcoming wallening, resprites the crates to be in the glorious 3/4ths perspective for all of us to enjoy!
Credits for: @OrionTheFox for making the original critter crate which he let me modify for the purposes of this PR.
The Eris team for presumably creating the original trash cart sprite I have modified. Unfortunately despite my best efforts to dig names via commit history, I have turned an empty hand.
image
image
image

## Why It's Good For The Game
The biggest offender for cabinet perspective sprites were crates, and despite me leaving some **notable** culprits (the necropolis crate) untouched, having most of the crates in this new perspective will be beneficial in the long run.

It also looks extremely nice!

## Changelog

:cl: PositiveEntropy
imageadd: Resprites most crates and the trash cart!
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
Probably the best crate resprite out of the like 15 attempts I've seen so far, good work

**Comment by Striders13** [comment]
Does it change crate mimic's sprite too?

**Comment by Imaginos16** [comment]
> Does it change crate mimic's sprite too?

image

Yes!

**Comment by retlaw34** [comment]
This goes so hard

**Comment by Serxule** [comment]
the shading at the edge where the lid opens is a bit weird, but these are good

**Comment by zxaber** [comment]
The open lid sprites are a bit visually unclear. If it's showing the underside of the lid, should it not just be an unpainted grey?

**Comment by optimumtact** [comment]
The ones where the under crate sprite matches the top sprite is a little visually confusing, I keep seeing another crate there.

Other than that it looks great

**Comment by bruhlookatthisdood** [comment]
you should like
give the mimic teeth

**Comment by mathis650** [comment]
CRATES

**Comment by notfrying1pans** [comment]
sick!

**Comment by Twaticus** [comment]
i think the lids will be fine as is but we can check back soon to see if a bigger lid/case distinction is needed.

**Pull request merged**
