### PR TITLE
Re-adds cloning pre-scanning

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Mark9013100
add: Re-added prescanning to cloning, along with genetic diskette functionality.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Both on the PR that removed autocloning and pre-death scanning, and the forum topic posted in reponse to that PR, it was generally agreed that only autoprocess was considered the offender and not pre-death scannning.

Pre-death scanning predated autocloning and still requires another player to perform the scan, and initiate cloning.

chrome_2018-12-08_08-56-49

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
+1 quickmerge

**Comment by 4dplanner** [comment]
It's worth noting that I actually made a version that kept pre-scanning, and the choice of the one that was merged was an active maintainer decision.

**Comment by daklaj** [comment]
stop being shit at the game and dying all the time, problem solved

**Comment by Mark9013100** [comment]
@daklaj This is not an 'i ded' PR, it was made in response to Arianya's post on the forums, as well as trying to find a middleground for both crowds.

**Comment by 4dplanner** [comment]
Original PR gets I ded
Partial revert gets I ded

way of the world

**Comment by Tlaltecuhtli** [comment]
:joy:

**Comment by nicbn** [comment]
Just cap the slots for autocloning, so medical team will have to manage them so that only high risk personnel (like miners, maybe engineers and heads) will be prescanned.

**Comment by anconfuzedrock** [comment]
yeah, oranges was so mistaken to remove pre-scanning. The game was so broken without the feature of retaining your memories when a copy of you from half an hour ago is cloned. The game just isn't fun with the tension of disarming a bomb risking you being impossible to clone unless you put the anti-bomb suit on, a random console in medbay should cure all ails. People shouldn't have to be cautious byond stopping by medbay once, and they definitely shouldn't have to rely on security staff in any way shape or form to protect the station.

**Comment by Nickkoranda** [comment]
ITT more HRP arguments for a MRP server. Dying isn't fun, disarming a bomb is only the case for nuke op rounds/syndicate bomb defusal, and if you fuck up you have much more to worry about than not being cloned. The point of this game, and why we play it, is to have fun.

**Comment by nicbn** [comment]
Friendly reminder that challenge is also fun.
If can't have fun with challenge, you'll probably be better off in some sandbox server.

**Comment by 4dplanner** [comment]
> Just cap the slots for prescans, so medical team will have to manage them so that only high risk personnel (like miners, maybe engineers and heads) will be prescanned.

But if you don't then they remain high-risk personnel, which is cool.

**Comment by Ratvar** [comment]
You are not permanently removed, go click ghostrole spawner. It's your choice to be permanently removed from the round, duh!
You are not permanently banned from other servers, go click byond hub. It's your choice to wait 20 minutes untill round ends, duh!

**Comment by nicbn** [comment]
Ghost roles are supposed to be tutorials (except by posibrain and xeno mobs, and these are dependent on the crew)

**Comment by AdamElTablawy** [comment]
Tension is a joke and people hold no value over their lives regardless of if their death is permanent or not because they will gladly rush after an antagonist fully aware that it'll probably permanently kill them if they get the opportunity.

All the removal of prescanning does is make the game less fun for people who are permanently dead, but it absolutely does not mean anything like 'hey people value their lives more' or 'there's more tension and drama'. People don't care, rounds last thirty minutes tops, and there's basically nothing that can be done to change that.

**Comment by 4dplanner** [comment]
> 30 minutes tops

lol

**Comment by ATH1909** [comment]
Perhaps prescanning/autocloning should be added back in, but with way(s) to do something to a corpse to make the soul belonging to it unable to be cloned (even with autocloning/prescanning) (maybe until the corpse is destroyed or the thing keeping it from being cloned is removed from the corpse, so people could still rez you by finding the corpse?). Sort of like how you can soulstone a corpse to permakill the person who owns it (if they're still dead), but with more availability (and preferably not exclusive to only a select few types of antags). That way, serial killers can still permakill people (and could leave calling cards or some kind of mark on their corpses!), but miners won't be forgotten about and never rezzed after they accidentally step onto a lava tile in Lavaland.

**Comment by Mark9013100** [comment]
@ATH1909 An interesting idea, but I'm not much of a coder, so I wouldn't know how to do that.

**Comment by HideAndSeekLOGIC** [comment]
Best idea so far was putting a limit on the amount of people who are stored in the pre-scan. 

To expand, why not simply have the scanner use 'cloning disks'? Anyone can pre-scan themselves into a disk, but only one can be inserted into the machine at a time and must be manually activated by doctors at the scene. This could be combined with an (possibly unlockable with T4 scanning or something) interface outlining whether or any disked persons are still alive for doctors' convenience. This will create a layer of 'body removal' for the traitor in the form of finding the cloning disks - it will be fun and challenging, only without the entire "cloning got annihilated" thing you all were so fiery about.

This can also be complemented by the implementation of a 'cloning queue' - one of the main problems right now is the lack of people getting cloned and instead just lying there. The ability to scan multiple people and add them to a queue to get cloned one by one would be nice.

**Comment by optimumtact** [comment]
Thanks for the PR, but I thought I made it pretty clear I was not interested in having prescanning

**Comment by optimumtact** [comment]
In fact you got it completely wrong, the issue isn't auto processing, it's that there is a way to return to life, from any location in the game, with zero repercussions. Which makes death meaningless.

This is entirely due to pre-scanning.

the autoprocess matters not one bit, other than making an already extremely overpowered function, much more reliable.

**Comment by Nickkoranda** [comment]
Death is meaningless in a game that you know you will get another shot in because the game is in rounds. If I die I'll be back in the game <1 hour, there is no value to life in any round because of that.

**Comment by Daxxed** [comment]
> 
> 
> Death is meaningless in a game that you know you will get another shot in because the game is in rounds. If I die I'll be back in the game <1 hour, there is no value to life in any round because of that.

Biased peak-time basil player spotted
We have other servers too, where rounds last longer than 20 minutes on average.

**Comment by GhostEcho** [comment]
I love how when people don't like PR, coders say fuck you learn to code, and when someone makes a PR that has majority player support, a maintainer will just be like, no fuck you I don't like it, clearly the issue is having maintainers be the end voice for PRs, change my mind

**Comment by GhostEcho** [comment]
Especially when said maintainers don't actually play the game, just maintain the code, how are they suppose to have a valid opinion on what should be allowed and disallowed?

**Comment by optimumtact** [comment]
They wont' get away with this

**Comment by ExcessiveUseOfCobblestone** [comment]
evil hitler maintainers

**Comment by Shadowflame909** [comment]
Auto-Cloning is shit. Pre-Scanning without Auto-Cloning is the best solution. Why do you do this Orange Man?

WHY HAVE YOU GONE PAST YOUR EXPIRATION DATE

**Pull request closed without merging**
