### PR TITLE
Nerfs Scattershot Mech Gun

### PR DESCRIPTION
**Pull request by ghost**
Previously, the scattershot produced 4 pellets with 65 stam, 20 brute each. This made it one of the best anti-human weapons by a massive margin. For comparison, in the same tech node, you get the LMG (three 20 brute bullets) and Hades (one 20 brute bullet with fire), with each having about the same cooldown. This PR brings the scattershot more in line with the other, giving it four 24 brute bullets.
:cl: 
   tweak: Removed stamina damage from Mech Scattershot, added a little more brute.
   /:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
Don't all shotguns have stamina damage, though? If so, it seems like this would just be inconsistent.

**Comment by imsxz** [comment]
no, normal buckshot does only brute and the damage drops for every tile it passes.

**Comment by zxaber** [comment]
Ah, well then I guess I have no further objections. I'm far to biased by my love of the scattershot to make a good argument.

**Comment by necromanceranne** [comment]
Good this shit was OP.

**Comment by SpookyWitch** [comment]
ive abused the scatter way too many times to clear out entire hallways full of people. its way too op

this is a good change imo, i use it a lot and find it to hold too much power, the ability to stun someone with simply scatter shot is POWERFUL

**Comment by Borisvanmemes** [comment]
This is needed but i will miss how it used to work.

**Comment by Tlaltecuhtli** [comment]
why not 8 bullets of 12 dmg

**Comment by py01** [comment]
I'm specifically trying to avoid oneshot guns. You're still fucked if it gets a full blast off on you, but if you were full health before the encounter, you have a small amount of time to yell ";mech rogue"

**Comment by 81Denton** [comment]
8x12 bullets would still deal 96 damage, you'd just have a larger amount of shot pellets that would make the gun more similar to shotguns.

**Comment by YakumoChen** [comment]
yeah ok but everyone has stopped using the scatter in favor of the instant kill missile

**Comment by 81Denton** [comment]
@YakumoChen The missile itself is only a 0/1/2 explosion on mechs/structures and 0/0/2 on living targets.
The real issue is more about how explosions are way too strong at low sizes.

**Comment by py01** [comment]
RPG is OP,  but PR's need to be atmozied. Also, I'm not sure how to weaken it while keeping it true to its theme.

**Comment by ExcessiveUseOfCobblestone** [comment]
> yeah ok but everyone has stopped using the scatter in favor of the instant kill missile, can you nerf (or remove) that one first?

how does that have any bearing on this PR lol

**Pull request merged**
