### PR TITLE
Janitorial cart now uses a radial menu

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR replaces a janitorial cart HTML UI with a radial menu, which is used for taking various janitorial items out of it.

**BEFORE:**

JanicartBefore

**AFTER:**

JanicartRadial

## Why It's Good For The Game

Better handling of the janitorial cart.

## Changelog
:cl: Arkatos
add: Janitorial cart now uses a radial menu.
/:cl:

### CODE REVIEW

**Comment by uomo91** [comment]
Awesome!

Any chance you could add soap to the list of things janicarts can hold? Never made sense to me that they can't.

**Comment by jtroopa** [comment]
> 
> 
> Awesome!
> 
> Any chance you could add soap to the list of things janicarts can hold? Never made sense to me that they can't.

People already jack with the janitor all the time; I think putting soap on the cart would just lead to it being stolen all the time.
The janibelt can hold soap too, and it's harder to swipe from the janitor when he's not looking.

**Comment by uomo91** [comment]
> > Awesome!
> > Any chance you could add soap to the list of things janicarts can hold? Never made sense to me that they can't.
> 
> People already jack with the janitor all the time; I think putting soap on the cart would just lead to it being stolen all the time.
> The janibelt can hold soap too, and it's harder to swipe from the janitor when he's not looking.

The janitor is free to put or not put whatever they want into the cart, accounting for the fact it can be stolen..
With the exception of soap, they mechanically cannot, which just seems like an odd inconsistency. The thing can fit a light replacer in it but not a bar of soap?

**Comment by RaveRadbury** [comment]
It can hold a _spray bottle_ which is like, holy grail cleaning imo.

**Pull request merged**
