### PR TITLE
The death or internal/external organ pathing (ft. fixed fox ears and recoloring bodypart overlays with dye sprays)

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This PR kills the abstract internal and external typepaths for organs, now replaced by an EXTERNAL_ORGAN flag to distinguish the two kinds.

This PR also fixes fox ears (from #87162, no tail is added) and mushpeople's caps (they should be red, the screenshot is a tad outdated).

And yes, you can now use a hair dye spray to recolor body parts like most tails, podpeople hair, mushpeople caps and cat ears. The process can be reversed by using the spray again.

## Why It's Good For The Game
Time-Green put some effort during the last few months to untie functions and mechanics from external/internal organ pathing. Now, all that this pathing is good for are a few typechecks, easily replaceable with bitflags.

Also podpeople and mushpeople need a way to recolor their "hair". This kind of applies to fish tails from the fish infusion, which colors can't be selected right now. The rest is just there if you ever want to recolor your lizard tail for some reason.

Proof of testing btw (screenshot taken before mushpeople cap fix, right side has dyed body parts, moth can't be dyed, they're already fabolous):
immagine

## Changelog

:cl:
code: Removed internal/external pathing from organs in favor of a bit flag. Hopefully this shouldn't break anything about organs.
fix: Fixed invisible fox ears.
fix: Fixed mushpeople caps not being colored red by default.
add: You can now dye most tails, podpeople hair, mushpeople caps etc. with a hair dye spray.
/:cl:

### CODE REVIEW

**Review by Time-Green — APPROVED** [review]
There has to be a better way to review stuff like this ;_;

I'm so sorry downstreams, this will hurt

**Comment by Time-Green** [comment]
I'm testmerging it for a bit. I know some code can break from this (especially some for loops, all I saw looked good but also my github kept nearly crashing due to the dif size).

**Comment by Time-Green** [comment]
Conflicts again. Tell me when it's fixed and I'll throw it on Terry for 2-3 days and merge it

**Comment by tgstation-server** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Terry

##### Merged By
Auto\time-green

##### Revision
Origin: 06aa1279d4a3543fd71620db610a96c585c2bfee
Pull Request: 619d09501e5d26ca82ca568a8137ac750e6fff0e
Server: 4ebdc5e4e6f7ee9eb599ebbb1ddce99adf8a228e

##### Comment

[GitHub Deployments](https://github.com/tgstation/tgstation/deployments/activity_log?environment=TGS%3A+Terry)
</details>

**Pull request merged**
