### PR TITLE
Birdshot engineering re-rework

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
Went with a more traditional SM setup
image

Engineers have their own designated area
image
Atmos layout:
image
## Why It's Good For The Game
A lot of engineer mains have been complaining about Birdshot engineering, including me.
Decided to go with a more traditional SM setup because SM is something that can easily derail the round and shouldn't be different from the standard as that increases our chances of delam.
Went with something special for Atmos because players that sit in atmos are experts anyways and a non-standard setup shouldn't confuse them too much.
Engineers didn't have a designated area.

All in all I hope this change will help make birdshot a more favored map than it is right now.
## Changelog
:cl:
add: Changed the layout of birdshot engineering atmos and SM, added a proper engineering storage area.
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
RIP quirkyness

Can you at least make the sm chamber walls into shuttle walls?

**Comment by Sadboysuss** [comment]
> RIP quirkyness
> 
> Can you at least make the sm chamber walls into shuttle walls?

no, because they let radiation through and are much easier to dismantle than r-walls, allowing griefing

**Comment by Admiral-Gigaton** [comment]
> > RIP quirkyness
> > Can you at least make the sm chamber walls into shuttle walls?
> 
> no, because they let radiation through and are much easier to dismantle than r-walls, allowing griefing

Major lame! Now it just looks like shittier meta!

**Comment by Pepsilawn** [comment]
Screenshot_20240607-173827_Chrome
SM is hotwired to the grid

**Comment by Nistishere** [comment]
> SM setups shouldn't be "quirky" or "different", we can make the map quirky and different without adding stress to new engineers on setting up an SM they've never seen before, SM is important for round health which is why I'm using the standard setup here, read the "why it's good for the game" part of my PR please.

SM setups being universally the same is a giant factor as to why a lot of people misunderstand engineering at a practical level and end out either repelled or codediving to try to figure things out, because the game design challenge provided by the SM every round is the exact same, and inevitably people do not grow better by being put in the same scenario but Now Its Reversed OoOo. Its why whenever a new station tries something different everyone is left drooling at their screens incapable of fixing any mistakes. You aren't teaching new people how to play the system, you are teaching them one puzzle and its solved, so any deviations are a head-scratcher.

The Rwall addition was a necessity tho and a very welcome addition.

**Comment by OverwatchVoice** [comment]
I can't tell from the preview image alone, but current Birdshot air mix to air tank line has an upside down mixer; 79% oxygen and 21% nitrogen - It should be the other way around, and have a pressure pump to limit it'the mixer's speed so station doesn't run out of pure nitrogen 15 minutes in. (or oxygen, in the case of this fuckup)

**Comment by Sadboysuss** [comment]
> I can't tell from the preview image alone, but current Birdshot air mix to air tank line has an upside down mixer; 79% oxygen and 21% nitrogen - It should be the other way around, and have a pressure pump to limit it'the mixer's speed so station doesn't run out of pure nitrogen 15 minutes in. (or oxygen, in the case of this fuckup)

oh I know about that problem, it's fixed here

**Comment by Sadboysuss** [comment]
guess I'll wait til the mapbot is fixed

**Comment by SyncIt21** [comment]
The mapbot is fixed.

Also you can't put [Ready] in your title when your PR is drafted, finish up your work here before it goes stale

**Comment by ShizCalev** [comment]
Conflict

**Comment by Sadboysuss** [comment]
Closes https://github.com/tgstation/tgstation/issues/84612

**Comment by Inari-Whitebear** [comment]
Oh, didn't find this PR or I would've posted it here :D

**Comment by Peliex** [comment]
Personally I think copy pasting the Meta Station SM but flipped is maybe not the best solution to people having brown outs.

The SM on birdshot is certainly difficult to get running by comparison, sure, but people getting rushed to turn the SM on in <10m because they sap all the electricity like a crowd of monkeys.

It provides interesting challenges to optimize and is harder to get a >1mW output from.

There is some complexity it could do without like the two separate gas chambers but aside from that, Birdshot is expected to put out regular wattages.

Maybe we could increase the starting power buffer to give Engineering some leeway so we aren't gating an entire job role behind speed running the engine then never touching it again.

**Comment by Sadboysuss** [comment]
Providing an "interesting" challenge that completely hijacks the rest of the shift if you fail it, that sounds like a lot of fun that definelt won't frustrate anyone.

**Comment by Peliex** [comment]
The cost of failure when the supermatter is involved is pretty much always frustrating when it happens right at the start of the round, yes.

Removing any semblance of a challenge may be overreacting though, I'm not a reviewer though I don't have any say.

I do still stand by my opinion that it may be beneficial to look into other power sources to go alongside the SM for Birdshot.

**Comment by Cheshify** [comment]
Very sad to see a cool SM setup replaced with another meta copy.

**Comment by Peliex** [comment]
I actually like the atmospheric changes a lot.  I feel like I should point that out.  I've come back and looked at this a few times and while the interior gas chambers is a bit risky, it is an avenue of sabotage or margin of error that is more than welcome on a map full of quirks

**Comment by Pepsilawn** [comment]
> Personally I think copy pasting the Meta Station SM but flipped is maybe not the best solution to people having brown outs.
> 
> The SM on birdshot is certainly difficult to get running by comparison, sure, but people getting rushed to turn the SM on in <10m because they sap all the electricity like a crowd of monkeys.
> 
> It provides interesting challenges to optimize and is harder to get a >1mW output from.
> 
> There is some complexity it could do without like the two separate gas chambers but aside from that, Birdshot is expected to put out regular wattages.
> 
> Maybe we could increase the starting power buffer to give Engineering some leeway so we aren't gating an entire job role behind speed running the engine then never touching it again.

If you want a unique roundstart SM setup it shouldnt be on a lowpop map.
Birdshot following Kilo's departure is currently the only map whose default config has a maxpop instead of a minpop to become available. If you want to pick a map for that kind of setup, Birdshot is a poor choice.

**Comment by Ghommie** [comment]
Merge conflicts.

**Pull request merged**
