### PR TITLE
Ocular Wardens will now target hostile-to-clockcultists simple animals

### PR DESCRIPTION
**Pull request by ChangelingRain**
this could not have stopped the tomatopocalypse alone

### CODE REVIEW

**Comment by Doppeltongue** [comment]
Tomatoes should also target wardens so it's more enjoyable.

**Comment by Repukan** [comment]
What is the point exactly of removing all kinds of counterplay to clock cult.

Why can we not let the cultists attack and defend themselves from the tomatoes.

**Comment by FantasticFwoosh** [comment]
@Repukan because clock cult is flawed because it tries to play tower defence mode with wardens without the properly faculties to have wardens shoot multiple/excessively strong targets.

> Instead of buffing/rejiggling clock cult, opts to destroy all excessively strong/swarm counters - literally what is this B.S

Remove wardens shooting through walls, & have wall shooting plus eventual rapid fire for multiple targets be upgrades clock cults can spend money/lategame scriptures on if you want shitty point/base defence. Even station cameras are more intuitive then clock-trash.

**Comment by XDTM** [comment]
Podpeople add the plants and vines factions to their own, they don't overwrite them, so they won't draw fire with this. I'm wondering why the current code doesn't attack mobs tho.

**Comment by GunHog** [comment]
This will make wardens target medibots and other friendly bots! These weak little things are not going to do anything against a killer tomato swarm, but they will pummel the poor little bots! (Insert strawman about Sentinel's Compromise here)

**Comment by jughu** [comment]
Inb4 beepsky tries to arrest the ocular warden

**Comment by Robustin** [comment]
Only way I'm ok with this is if Tomatoes will target the wardens too.

**Comment by Kromgar** [comment]
And any simple mob can attack and kill the attacking eyeballs right?

**Comment by optimumtact** [comment]
Things that are hostile to clockcultists should naturally get targeted by the weapons a clock cultist uses, this should be an obvious change and non controversial.

**Pull request merged**
