### PR TITLE
Gives syndiborgs a disk apparatus

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Gives all syndicate borgs a tool that can carry and use disks (akin to the borg beaker holder). Can carry, drop, and insert contained disk into machines (IE nuke). Will drop the disk if the borg dies.

## Why It's Good For The Game
If syndicate borgs are going to count as Ops members for the purposes of delaying round-end, they should also have the ability to finish the job.

## Changelog
:cl:
add: Syndicate borgs now have a tool for carrying and using disks.
/:cl:

image

### CODE REVIEW

**Comment by itseasytosee** [comment]
You forgot a trailing newline

**Comment by PKPenguin321** [comment]
how does this interact with the disk teleporting away if they leave the z-level?

**Comment by zxaber** [comment]
If the disk moves out, I assume Exited() is called, which removes the disk from the stored variable and resets the sprite. I can test it, though.

**Comment by Ryll-Ryll** [comment]
Seems like a pretty big change, promoting the borg from a dedicated support role that requires sticking with a human to a full fledged operative in their own right.

**Comment by itseasytosee** [comment]
If they can't complete the mission on their own they shouldn't keep the round from ending.
Mabey if only they live we could have a minor or even neutral victory I don't know if they count for that for purposes of green texting.

**Comment by Shadowflame909** [comment]
@Ryll-Ryll 

You give 40-70 TC for one, compared to the 19 TC for a regular reinforcement.

The points reflect the power.

**Comment by Ratvar** [comment]
I do not like PRs that remove team gameplay from nukeops and make it closer to <rush cap alone on speedboosts/as engiborg, win alone>. Maybe secborgs should not count for delaying round instead?

**Comment by Ryll-Ryll** [comment]
Does that 19TC include the full kit of an operative including weapon, explosives, esword, emag, ammo, and more?

**Comment by Shadowflame909** [comment]
No. But you get that stuff for free with the syndicate lockers and hardsuit dispenser

**Comment by Iatots** [comment]
I guess the worst that could happen is people not securing the disk and a saboteur borg nabbing it, but that's on the crew I guess.

**Comment by cacogen** [comment]
>If syndicate borgs are going to count as Ops members for the purposes of delaying round-end, they should also have the ability to finish the job.

probably they should not

**Comment by BadSS13Player** [comment]
Does this count as a fix in regard to the antag freeze?

> I do not like PRs that remove team gameplay from nukeops and make it closer to <rush cap alone on speedboosts/as engiborg, win alone>. Maybe secborgs should not count for delaying round instead?

That just makes you a flukeop. If you rush the disk alone in a warop round the only thing you'll accomplish is getting robusted by the crew, while in a stealthop round you probably don't have a borg since you have better things to spend TC on. The only case where this borg module would make a difference is when both the crew and the nukeops are pretty wrecked.

**Comment by zxaber** [comment]
Antag freeze is ded.

**Comment by kriskog** [comment]
Im not sure what I think about this. Syndiborgs in the right hands are stupid strong, this just makes them able to do the entire job themselves. The alternative is making the syndiborgs not delay round end, which makes them truly a support role.

**Comment by BadSS13Player** [comment]
> this just makes them able to do the entire job themselves.

They don't have disk pinpointers.

**Comment by kriskog** [comment]
Just kill and steal what looks like a head, search them. Its usually on one of the blue ones.

**Comment by trollbreeder** [comment]
> Just kill and steal what looks like a head, search them. Its usually on one of the blue ones. Some times the black and red one.

Who is the brown and white man trying to flash me?

**Comment by zxaber** [comment]
> 
> 
> Just kill and steal what looks like a head, search them. Its usually on one of the blue ones. Some times the black and red one.

During Stealth Ops, the disk pinpointer is unlikely to be activated, and Borgs cannot activate it. It's also likely to be carried by the HoS or another member of sec, all of which have flashes by default.

During War Ops, whoever has the pinpointer is likely to be armed, and only one syndicate borg has any ranged weapons to speak of (and generally little opportunity for repairs unless a sabo borg was brought).

**Comment by Ratvar** [comment]
Are people unironically saying borgs dont have ranged options by default. 
 How about a canister full of plasma you grabbed, or that sweet saboteur style welderbomb. Sounds 
 ranged.
 Maybe ask your syndiefriends to give you a pinpointer to pull, if you lack one.

**Comment by kriskog** [comment]
> 
> 
> > Just kill and steal what looks like a head, search them. Its usually on one of the blue ones. Some times the black and red one.
> 
> During Stealth Ops, the disk pinpointer is unlikely to be activated, and Borgs cannot activate it. It's also likely to be carried by the HoS or another member of sec (if not just left disabled in the cap's office), all of which have flashes by default.
> 
> During War Ops, whoever has the pinpointer is likely to be armed, and only one type of syndicate borg has any ranged weapons to speak of (and generally little opportunity for repairs unless a sabo borg was brought).

I didnt say kill the captain/hop/hos for a pinpointer, one of them has the disk 99% of the time.

**Comment by zxaber** [comment]
>Are people unironically saying borgs dont have ranged options by default.
How about a canister full of plasma you grabbed

Default disk holder has a hardsuit that's immune to plasma fires, so that won't do much to get the disk. I think the HoS's hardsuit is also fireproof.
>or that sweet saboteur style welderbomb

Ah yes, the attack that takes half your heath and involves moving a box to be close to an opponent with guns that instantly set it off. Works when it works, but I wouldn't call it reliable.

>I didnt say kill the captain/hop/hos for a pinpointer, one of them has the disk 99% of the time.

Ah, that's fair, but they're still going to have guns (and if you're in a scenario where this tool matters, likely numbers). I doubt this tool will drastically change the outcome of most fights, but if a fight breaks out and both sides take heavy casualties, at least the borg can finish up the job afterwards.

**Comment by optimumtact** [comment]
Don't make them count for the round end.

I'm okay with borgs being unable to complete the goal without human assistance and I prefer it that way because it makes the idea of being a borg more flavourful because you can't do things that you usually can, which changes your gameplay calculus entirely.

**Pull request closed without merging**
