### PR TITLE
Gives everyone anteg gear

### PR DESCRIPTION
**Pull request by Buggy123**
anteg good

Maintainer approved:
screenshot-discordapp com-2020 01 06-12_52_04

### CODE REVIEW

**Comment by zxaber** [comment]
Good idea but I imagine this will ruffle feathers due to the suitcase of money invalidating our economy system.

**Comment by mrhugo13** [comment]
great crew content update, oranges would love this.

**Comment by Shadowflame909** [comment]
merge to the april fools branch for 50% chance of merge

**Comment by FantasticFwoosh** [comment]
anteg good :+1:

**Comment by HomocidlePancakes** [comment]
Does it mean I can add antag items with global effects to bypass the freeze?

**Comment by Buggy123** [comment]
>Does it mean I can add antag items with global effects to bypass the freeze?

yes

**Comment by Zenog400** [comment]
Just checking, this gives everyone _two_ debug uplinks?

**Comment by Buggy123** [comment]
They're slightly different. Also, what if they lose one? You don't want anyone to lose anteg because they accidentally dropped their debug uplink, do you?

**Comment by ninjanomnom** [comment]
I'm ninjanomnom and I approve of this message

**Comment by Buggy123** [comment]
😦

**Pull request closed without merging**
