### PR TITLE
Mail now only cares about the (real) name to open

### LINKED ISSUE #73194: Paradox Clones Can't Open Mail
## Round ID:

https://sb.atlantaned.space/rounds/199434

## Reproduction:

Unsure if this is intentional, but after encountering a Paradox Clone, we managed to discover who was the original by having both attempt to open mail. Is it worth it/possible to make them able to open the mail of the person they are a clone of?

### PR DESCRIPTION
**Pull request by Lufferly**
## About The Pull Request

Fixes #73194

Instead of checking for a specific mind when opening, mail now only cares about your real name. In meaningful terms this means that paradox clones and changelings can open "their" mail, and I suppose if two people happen to name themselves the EXACT same thing they can open eachothers mail. The job of the intended recipient is still on there, but there are no checks to make sure you have that job or anything.
I also made it so dead people can receive mail, but not suicided people. My reasoning is that dead people are still part of the round, and maybe a cargo tech looking for them would be interesting, but suicided people are not really fun to interact with.

## Why It's Good For The Game

As funny as it is, mail keeps getting abused because it is an easily accessible mind datum check. This will make it so that paradox clones, changelings, and things of that ilk can avoid antag checks.

## Changelog

:cl: Seven
balance: Mail doesn't care about specific minds anymore, as long as your real name is whats on the envelope you will be able to open it. As a result paradox clones and changelings can now open mail "intended" for them.
balance: Dead people can now receive mail, but not if they committed suicide
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Remember, folk, that antag checks are against the rules and you can in fact ahelp if something like this is used against you. No knock against the PR in any fashion, just a reminder that if something like this does happen again that we've rules to protect you from dorks abusing this to make the game less fun.

**Comment by DrDiasyl** [comment]
A Mailman accidentally discovers a murder after searching for the last person to deliver a parcel to, nice

**Comment by moocowswag** [comment]
> Remember, folk, that antag checks are against the rules and you can in fact ahelp if something like this is used against you. No knock against the PR in any fashion, just a reminder that if something like this does happen again that we've rules to protect you from dorks abusing this to make the game less fun.

The rules are a band aid solution to code issues.

**Comment by Y0SH1M4S73R** [comment]
Wouldn't it make more sense to check for the mind, and then check for the real name if the first check fails? The actual recipient of the mail knows who they originally were, and should be willing to open their own mail even if their body has screwed with.

**Comment by Lufferly** [comment]
> The rules are a band aid solution to code issues.

There is no code replacement for authority, rules give us some freedom to not worry about abuse and make room for an actual sandbox.

**Comment by Lufferly** [comment]
> Wouldn't it make more sense to check for the mind, and then check for the real name if the first check fails? The actual recipient of the mail knows who they originally were, and should be willing to open their own mail even if their body has screwed with.

Best to keep things simple, I dont want to get to a point where we are storing a list of all real names a mob has ever had for something like mail. If we are going to have ridiculous rules for mail might as well keep it predictable.

**Comment by Y0SH1M4S73R** [comment]
> I dont want to get to a point where we are storing a list of all real names a mob has ever had for something like mail. If we are going to have ridiculous rules for mail might as well keep it predictable.

That's not what I was implying was necessary. We just keep the current check, but then, if that check fails, check if the opener's real name is the name assigned to the original recipient's mind.

**Comment by optimumtact** [comment]
this is an admin issue in the first case and shoul dnot be handled with a code solution unless admins have shown they're unwilling to enforce this not bieng used as a meta tell or have asked us to change it.

**Comment by Jacquerel** [comment]
The person the mail is for should always be able to open it regardless of if their head has been translated onto someone else's body.
If the end result of this PR is that a changeling can open your mail and you can't (because they transform stung you) then you've only made it worse, not better.

**Pull request closed without merging**
