### PR TITLE
Add hover indicator for body zone selector 

### PR DESCRIPTION
**Pull request by SpaceManiac**
:cl:
add: The body zone selector now indicates which body part you are about to select when hovered over.
/:cl:

zonesel

### CODE REVIEW

**Comment by optimumtact** [comment]
can't wait for people to complain about this one being "delayed" next

**Comment by Stickymayhem** [comment]
Can we add a hover overlay that shows the complaints clicking 'merge' will generate

**Review by Cyberboss — DISMISSED** [review]

**Comment by BeeSting12** [comment]
Can this be a preference???


/s

**Comment by ExcessiveUseOfCobblestone** [comment]
I just want to let you know I was kidding about the alpha level

**Comment by ExcessiveUseOfCobblestone** [comment]
yes please

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
