### PR TITLE
Assistant cap config

### PR DESCRIPTION
**Pull request by ghost**
Defaults at unlimited. Defined in game_options.txt. Set to -1 for no cap. This allows the server to still have an unlimited amount of players and not block anyone from joining, and also allows the HoP to do their job and open more job slots without everyone latejoining as assistant. Ideally the HoP would get a notification when there was no job slots open, but this is a better solution than hard capping the server. It would allow people to join, see that there's no slots, and then go to basil if they want to populate it. Forcing people off might be a poor idea and just frustrate people more than anything. Some people would prefer to observe, even if they can't play.

### CODE REVIEW

**Comment by xxalpha** [comment]
Yes! Make that HoP have some responsibility.

**Comment by hornygranny** [comment]
What happens if more than x amount of people ready?

**Comment by paprka** [comment]
They should be getting kicked back to lobby, I thought there was a sanity check for this. I'll double-check.

**Comment by xxalpha** [comment]
Turn the excess into fully equipped janitors.

**Comment by Dorsisdwarf** [comment]
The Slippening

**Comment by paprka** [comment]
This actually works now.

**Comment by Jordie0608** [comment]
Changelog, remember to mention the new config to SoS when merged.

**Comment by Miauw62** [comment]
changelog and pls make it start at unlimited

**Comment by paprka** [comment]
Oh my bad

**Pull request merged**
