### PR TITLE
Introducing the 'Bluespace Catastrophe', a mess of a shuttle.

### PR DESCRIPTION
**Pull request by Firecage**
This PR adds the second Fuck Shuttle, with Thunder's PR containing the first Fuck Shuttle.

Here is the original buggy mess:

ss 2016-12-07 at 03 46 02

And here is our new bluespace mesh up shuttle!

aegis outpost seven 2016-12-07 220704

:cl: Firecage
add: We at NanoTrasen are proud to announce the unveiling if our new series of Shuttles! This specific model was, by 'accident', bluespaced together from several other shuttles! Introducing, the 'Bluespace Catastrophe!'
/:cl:

### CODE REVIEW

**Comment by Mindustry** [comment]
i wouldn't mine a space hulk-esque shuttle

**Comment by KorPhaeron** [comment]
@Mindustry 

Stay tuned

**Comment by WJohn** [comment]
how would this even dock to the station at all?

**Comment by Arianya** [comment]
@WJohn How does the asteroid even dock to the station at all?

**Comment by Firecage** [comment]
Wj, look at the door on the right.

**Comment by WJohn** [comment]
oh, so the cockpit would be facing south, i see.

also this meme needs to friggin die right now it's promoting hideous shuttles for shits n giggles

**Comment by Firecage** [comment]
Wjohn. There's two cockpits.

**Comment by Firecage** [comment]
Besides. This specific shuttle which was produced by a bug, actually seems very appealing to me. It just...has something.

**Comment by optimumtact** [comment]
Looks bad

**Comment by ShadowDeath6** [comment]
>looks bad

isn't it supposed to look bad? it's combining 4 shuttles

**Comment by coiax** [comment]
I kind of like it.

**Comment by KorPhaeron** [comment]
I don't think we need two of these

**Comment by Firecage** [comment]
Kor, I do have one question though, I still can't figure out which shuttles makes up this shuttle. I think one is Meta?

**Comment by KorPhaeron** [comment]
Pubby + meta

**Comment by Firecage** [comment]
Personally this one does look oddly appealing though, thats why I made it into a shuttle. It has all the necessities, it doesn't have any hull breaches or overly weak points(...discounting the fact that technically windows wouldn't survive hyperspace travel...), and has engines on three sides.

**Comment by optimumtact** [comment]
To me the other one looks more fucky, and therefore is the one I prefer

**Pull request closed without merging**
