### PR TITLE
Hit Numbers

### PR DESCRIPTION
**Pull request by Iamgoofball**
https://www.dropbox.com/s/28a6kg0ltvsbr64/hitnumbers.webm?dl=0

Borrowed the popup code from dragonroll.

We could totally use the popup crap for other things too.

### CODE REVIEW

**Comment by Ikarrus** [comment]
I'm sorry, but this is way too meta for my taste. We don't need to know the exact damage values for everything.

**Comment by WJohn** [comment]
I personally want blood splatters, whose size could be based on the amount of damage dealt in a hit (small, medium, large, with a few versions of each). We don't get exact numbers for anything else outside of the health scanner, and this makes the health meter, examining yourself and examining someone else kinda obsolete (and to some extent the health scanner obsolete too!)

**Comment by Iamgoofball** [comment]
@Ikarrus Sorry, what?

Since when do we care about something being too meta? It's a video game.

**Comment by Ikarrus** [comment]
And there is value in not revealing everything to players in video games.

**Comment by Iamgoofball** [comment]
So not revealing basic gameplay info is a good idea?

Every other popular multiplayer game with fighting elements has some kind of hit damage indicator to tell you how much damage you did.

I don't see why we need to keep staying in the dark ages because muh mysterious in an open source codebase.

**Comment by Xhuis** [comment]
This is pretty awesome. Still, I don't like it very much. It has a place, but not here.

**Comment by palpatine213** [comment]
No, not every game has it. Those games that do are more silly and cartoonish. No sense in role play at all. This is a feature more suited to goon, which doesn't take itself as a role play game at all.

**Comment by Jordie0608** [comment]
Changelog

**Comment by Iamgoofball** [comment]
@palpatine213 

We don't code for roleplay or immersions. This is a video game. I have checked with maintainers about this and they have confirmed it.

**Comment by Aranclanos** [comment]
ignoring completly the feature itself, don't create images like that I already told you and i want to take your head off and put it on a stake to make a point

**Comment by Iamgoofball** [comment]
@Jordie0608 over my dead body

(yeah sure)

@Aranclanos i'll talk to professional BYONDers about it

**Comment by Summoners** [comment]
Doesn't fit in this game and seems silly, good feature but just ain't for this kind of environment.

**Comment by MrPerson** [comment]
Examining oneself is a relic of the old days. The paperdoll was already designed to surpass it. Examining others/health meter is more to tell what drugs they need. This is more of an in-combat notification, although it has some uses for telling if someone is bleeding.

The icon stuff is an interesting idea, but I suspect that would be kinda confusing unless the sprites were really big. There's just not a lot of detail one can pack into 7x7 or 9x9 or w/e.

**Comment by Ikarrus** [comment]
I liked the idea of having more abstract representation of how much a damage did rather than straight up numbers.

At least visually it would not violate immersion as much.

**Comment by Boggart** [comment]
The popup text looks really obnoxious to me, it's going to get pretty spammy when a bunch of people are on fire.

**Comment by Aranclanos** [comment]
completely ignoring the code side of this
IMMERSIONS = RUINED

**Comment by Iamgoofball** [comment]
We don't code for immersions. I asked a maintainer and they verified this.

I'll add a toggle, however, so muh immulhsions can be saved by disabling seeing the numbers.

**Comment by Ikarrus** [comment]
>A maintainer

What about the others?

You know aran is one too.

**Comment by Incoming5643** [comment]
Could be useful as a debugging tool, or maybe attached to some form of advanced medical hud, but as a general every attack thing it seems like entirely too much information.

Plus I feel like showing the damage you did so overtly will just encourage people to just beat the shit out each other even more than they do now because the numbers will reenforce their actions.

**Comment by Iamgoofball** [comment]
@Ikarrus uh

aran isn't a maintainer anymore

he quit

**Comment by Ikarrus** [comment]
Aha okay.

But still, one maintainer's word is not law.

**Comment by Iamgoofball** [comment]
If someone is beating people up for the sheer sake of seeing the numbers, they need to rethink what they're doing.

**Comment by Incoming5643** [comment]
The entire objectives system is based on the notion that players will go out of their way to do certain things for a tiny bit of recognition by the game. If that kind of player smacks a guy and see a 40 sail over his head for everyone around to see, he's gonna love doing it.

**Comment by Incomptinence** [comment]
Seems fine it is more meta to have memorized most weapon damage anyway.

**Comment by MrPerson** [comment]
If people don't want to see "so many" of these, we can make it only show to the poor sap getting hit and and guy doing the hitting while everybody else just sees the attack animation.

**Comment by Incoming5643** [comment]
On a personal level I feel like gamification has its limits in a game like this, at least for this codebase. When you smack someone your first thought should be "I smacked them" not "I did 20 damage, only four more to go". 

Just because some people internalize that sort of damage counting doesn't mean it's something that should be celebrated.

**Comment by palpatine213** [comment]
I agree with what incoming said. Basically my thoughts.

**Comment by Cebasiz** [comment]
this seems terrible. what possible problem does it solve? seems like change for the sake of change and not in a good way, it will be annoying as shit to see this shit in large combats, it won't even be readable in any real mashup. it's an eyesore and doesn't fulfill a real purpose when whether you do 7 damage or 9 damage in a punch means very little when you already know that your opponent is still capable of fighting back; his state is transparent to you already by a few state switches, namely if he's standing, capable of moving, bleeding and how slow he's moving. giant numbers that won't even be of real use in threat estimation 90% of the time are purposeless and just ugly.

not only does it not serve a tactical purpose in any real way but it's simply super fucking ugly and obscures the sprite of your enemy, which actually does give tactical information. the dropbox you posted clutters the sprite such that you can miss that your target is suddenly holding a gun in all the visual noise.

i hope you aren't intent on ramming this through, it's awful. please reconsider.

**Comment by optimumtact** [comment]
don't like this particular change, we don't need to see this info I reckon, not oppossed to your other stuff like text etc though

**Comment by ExplosiveCrate** [comment]
>this seems terrible.
Basically this. Also what everyone else said. Looks ugly, feels too 'gamey'.

**Comment by WJohn** [comment]
A lot of people would be fine with it just being blood splatters. Even bay does it, and I personally would like it done that way. Heck you could even scale the size of blood splatters based on how damaging an attack was, and that wouldn't feel too meta.

**Comment by xxalpha** [comment]
This isn't a top-down shooter.

**Comment by palpatine213** [comment]
Yes to blood splatters. Have the blood come more from the combat rather than dragging a person around.

**Comment by Miauw62** [comment]
Yeah, I don't like the idea of hit numbers. I like the idea of blood splatters, but there isnt much reason to have obnoxious and rather immersion-breaking hit numbers pop up whenever you hit somebody, since the game already conveys quite a large amount of information to the player about in what state your opponent is.

**Comment by Dorsisdwarf** [comment]
I agree with the other guys, this is dumb.

**Comment by LaharlMontogmmery** [comment]
Yeah, no. This is kinda dumb and goes against most of the TG13 mechanic philosophy, I believe.

This COULD be used for medical HUD/advanced medical HUD, but this would create a case of everyone probably wanting them. 

You shouldn't be able to put a number in the damage done purely using your naked eyes, anyway. There is suck a thing as "Too much meta", even for us.

**Comment by WJohn** [comment]
Almost everyone already wants the med huds, they're extremely useful. I don't think I'd mind seeing this added to those, although I think it'd be neat if there were both red damage numbers and green heal numbers shown when using them (visible only to people wearing those).

**Comment by DaedalusGame** [comment]
Stop.

**Comment by RemieRichards** [comment]
General consensus is:
* NO
* Blood splatters are better.

you do the do @Iamgoofball

**Comment by freerealestate** [comment]
Looks really good. I like this shift towards presenting important feedback to the player more proactively, especially in an eye-grabbing and modern way (at least by BYOND standards). But without an IC justification it doesn't make much sense.

The speech bubbles and the progress bars provide information to the player that their characters could know. Seeing physical damage measured numerically with the naked eye doesn't make sense. Health analysers and medical HUDs don't make much sense either, but at least they attempt to suspend your disbelief by being futuristic technology. So I wouldn't mind seeing this in security or medical HUDs.

This has reminded me how much we need randomisation of damage values, too.

**Comment by Miauw62** [comment]
Eh, damage values are already random enough, what with armor, bleeding damage, prior damage to target, etc.

**Comment by Cheridan** [comment]
>hit someone irl
>huge floating numbers don't show up

WOOOOOOOOOOOOOOOOW

**Comment by freerealestate** [comment]
@Cheridan
>realism

This could be changed to only work with HUDs, by the way.

**Comment by Xhuis** [comment]
This working with hudglasses is actually a pretty cool idea.

**Comment by HoaxIT** [comment]
I'm going to steal this. thanks @Iamgoofball

**Comment by Iamgoofball** [comment]
no problem bby

**Comment by RemieRichards** [comment]
@HoaxIT don't credit goof he's a dirty thief.

**Comment by HoaxIT** [comment]
@RemieRichards :^) I'm just linking back to this PR for keks.

**Pull request closed without merging**
