### PR TITLE
fix heart attack event follow link

### LINKED ISSUE #35615: Random Heart Attack click to orbit link in chat does not work
1) Random Heart Attack triggers.
2) As a ghost, try to click the link to orbit the poor sod.
3) Nothing happens.

Round ID: 83513

### PR DESCRIPTION
**Pull request by PKPenguin321**
🆑
fix: Ghosts should now be able to orbit people who are going into cardiac arrest
/🆑

Fixes #35615

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>conflicts

im gay

**Comment by MoreRobustThanYou** [comment]
>steals my GBP because @optimumtact is an asshat

🤔

**Comment by Robustin** [comment]
What does this even change?

**Comment by optimumtact** [comment]
this literally does nothing other than adjust spacing

**Comment by Robustin** [comment]
On a side note the UI-alert that comes with the event works fine so just have the chat link use the same link and you're good.

**Comment by PKPenguin321** [comment]
if this code doesnt work then uhhhh vOv

**Comment by vuonojenmustaturska** [comment]
??? there's no way this changes anything?

**Pull request closed without merging**
