### PR TITLE
emagged cyborgs may now selfdestruct if locked, but require a charged cell

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
you need a charged cell instead of being unlocked and to be unstunned to selfdestruct as an emagged cyborg

## Why It's Good For The Game

allows emagged cyborgs an easy way to make sure their secrecy law is fulfilled by blowing up if captured

## Changelog
:cl:
balance: to self-destruct as an emagged cyborg, you need a cell with charge and to be not stunned
/:cl:

### CODE REVIEW

**Comment by Higgin** [comment]
stunning a cyborg without EMP is a two-tap these days, this is patently unnecessary. if you fail to pull the ripcord in time, you aren't entitled to keep your secrecy.

**Comment by necromanceranne** [comment]
> stunning a cyborg without EMP is a two-tap these days, this is patently unnecessary. if you fail to pull the ripcord in time, you aren't entitled to keep your secrecy.

Not for nothing, but self destruct means you straight up cannot be revived. The alternative method to this is just....DNR when security kills you for being a emagged borg.

**Comment by Higgin** [comment]
> > stunning a cyborg without EMP is a two-tap these days, this is patently unnecessary. if you fail to pull the ripcord in time, you aren't entitled to keep your secrecy.
> 
> Not for nothing, but self destruct means you straight up cannot be revived. The alternative method to this is just....DNR when security kills you for being a emagged borg.

if the requirement is that emagged cyborgs not be able to be tracked or traced or recovered, why not just make them automatically DNR?

Creates some incentive not to get caught out/subverted in line with law 3, helps protect secrecy. Hell, even make them blow up automatically.

If it's going to be a choice that can be made only out of spite, and when not made potentially screws up the antagonist who risked their neck to collect you, why even make it a choice?

**Comment by mc-oofert** [comment]
> stunning a cyborg without EMP is a two-tap these days, this is patently unnecessary. if you fail to pull the ripcord in time, you aren't entitled to keep your secrecy.

i dont know what the fuck youre on about but there has been an innate requirement to not be stunned to self destruct that is also kept

**Comment by starrm4nn** [comment]
emagged borgs have no secrecy, most people forget to pulse/cut the camera wire on them

**Comment by zxaber** [comment]
Self Destruct was specifically gated behind being unlocked to allow robotics to use Siliconnect to get emag owner names. That's an intended interaction.

Emagged borgs can smash the console if they're worried about the lockdown. Alternatively, work alongside your VIP so that they can haul you off for a wire pulse unlock if need be.

**Comment by mc-oofert** [comment]
> Self Destruct was specifically gated behind being unlocked to allow robotics to use Siliconnect to get emag owner names. That's an intended interaction.
> 
> Emagged borgs can smash the console if they're worried about the lockdown. Alternatively, work alongside your VIP so that they can haul you off for a wire pulse unlock if need be.

again they cant do shit if stunned so take them out with an EMP or flash+weapon if you want the name

**Comment by zxaber** [comment]
The robotics console is intended to be an avenue to accomplish that as well. That's *why* we have a lockdown function in the first place.

You haven't mentioned why this is a good change, by the by. Your section in the PR description just mentions what the PR does. Requiring emagged borgs to round-remove themselves upon lockdown should have some reason attached to it.

**Comment by ATH1909** [comment]
> emagged borgs have no secrecy, most people forget to pulse/cut the camera wire on them

we really ought to make the camera something the borg can toggle themselves

**Comment by ExcessiveUseOfCobblestone** [comment]
I think if youre caught it should be mechanically difficult to actually fulfill the secrecy law from a game perspective, because borgs are incredibly powerful if used correctly you should temper that with the fact that there is a way to out the emagger. Making emagging "safe" for the emagger is a small price to pay for the potential devastation a borg partner can cause.

Even the worst borg still acts as a way for all access.

**Comment by mc-oofert** [comment]
> I think if youre caught it should be mechanically difficult to actually fulfill the secrecy law from a game perspective, because borgs are incredibly powerful if used correctly you should temper that with the fact that there is a way to out the emagger. Making emagging "safe" for the emagger is a small price to pay for the potential devastation a borg partner can cause.
> 
> Even the worst borg still acts as a way for all access.

borgs killing themselves is usually beneficial for everyone

**Comment by mc-oofert** [comment]
closed with no explanation god bless

**Pull request closed without merging**
