### PR TITLE
WHAT THE FUCK IS THAT

### PR DESCRIPTION
**Pull request by Iamgoofball**
# WHAT IS THAT

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>>>using fucking A* for VIRUSES

**Comment by Thunder12345** [comment]
\>Viruses use A*

**Comment by Shadowlight213** [comment]
Isn't it so viruses don't go through windows or something?

**Comment by Cruix** [comment]
Yes

**Comment by Iamgoofball** [comment]
Cost is not worth it

**Comment by Cruix** [comment]
Use get_hear() so it works in the dark

**Comment by banthebantz** [comment]
what the actual fuck is that autistic piece of shit line

**Comment by AnturK** [comment]
Please give this PR title that indicates the content or it will have to be closed.

**Comment by Alek2ander** [comment]
inb4 "Issue: We rounded up the infected and put them in observation but now we're infected through the window ree"

**Comment by Bawhoppen** [comment]
yea removing a key game feature for performance isn't good

**Comment by Iamgoofball** [comment]
Do you know how laggy A* is?

**Comment by Screemonster** [comment]
A* is fairly "what the hell why use that of all things" but removing it entirely and letting people get infected through solid objects is not the solution.
Sure replace the A* with a cheaper check, don't remove the check entirely.

**Comment by lzimann** [comment]
I don't think this has any significant performance impact in the game. Also I would rather lose a bit of performance than having viruses spreading through windows

**Comment by Iamgoofball** [comment]
merge #28197 instead

**Pull request closed without merging**
