### PR TITLE
Circuit gun inhands and grabber fix

### LINKED ISSUE #35298: IC Grabbers not updating inventory properly
Issue reported from  Round ID: 83048 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

{"assembly":{"type":"type-b electronic mechanism","opened":1},"components":[{"type":"ranged sensor"},{"type":"examiner"},{"type":"thrower","inputs":[[1,0,2],[2,0,2]]},{"type":"number pad"},{"type":"two pulse demultiplexer","inputs":[[1,0,2]]},{"type":"beeper circuit","inputs":[[1,0,"beep"],[2,0,3]]},{"type":"beeper circuit","inputs":[[1,0,"chime"],[2,0,3]]},{"type":"text-to-speech circuit","inputs":[[1,0,"examine"]]},{"type":"text-to-speech circuit"},{"type":"grabber","inputs":[[2,0,1]]}],"wires":[[[1,"O",1],[2,"I",1]],[[1,"O",1],[10,"I",1]],[[1,"A",1],[2,"A",1]],[[2,"O",3],[3,"I",1]],[[2,"O",4],[3,"I",2]],[[2,"A",2],[5,"A",1]],[[2,"A",2],[8,"A",1]],[[3,"I",3],[10,"O",1]],[[3,"A",1],[5,"A",3]],[[4,"O",1],[5,"I",1]],[[5,"A",2],[6,"A",1]],[[5,"A",2],[10,"A",1]],[[5,"A",3],[7,"A",1]]]}

[Reproduction]: This circuit is designed to pick things up with a grabber and throw them. The grabber part does not update its contents list after a thrower removes an item stored in it.

### PR DESCRIPTION
**Pull request by Garen7**
Fixes #35298

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Garen
rscadd: Thrower and Gun circuits put messages in chat when they're used.
tweak: Only the gun assembly can throw/shoot while in hand
imageadd: Adds inhands for the gun assembly
fix: grabber inventories update when a thrower takes from them
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

The way I fixed the bug was snow flaky however I don't know any other way to fix it, and it can cause a lot of hassle for anyone trying to use a thrower as you would otherwise need to repulse the grabber to update it's outputs which is really unintuitive. I added inhands to the gun assembly and made it the only assembly that can fire guns & throw things in hand since both of those can be dangerous and should be communicated to other players. 
imageedit_3_8849308010
It's worth saying that both the bug fix and the tweaks affect balance, however they cancel each other out since the fix is a buff and the tweaks are nerfs. Overall the changes create healthier playstyles since the bug just confuses people getting into circuits and the inhands and chat messages will help people realize what is causing them harm.

### CODE REVIEW

**Comment by fludd12** [comment]
Maybe make the larger machine boxes also able to use the gun component for the creation of stationary turrets and such

**Comment by Noahnoah55** [comment]
Ideally we would just have inhands for all circuit assemblies, but this is an alright compromise for now.

**Comment by AlexTheSysop42** [comment]
>fix: grabber inventories update when a thrower takes from them

I smell a dupe bug

**Comment by AverageJoe82** [comment]
@fludd12 they can, the only restriction is that the gun assembly must be used for it to fire while being held.

@AlexTheSysop42 dupe bug?

**Comment by AlexTheSysop42** [comment]
If a thrower can take from a grabber without the grabber losing the object, that would probably dupe it

**Comment by AverageJoe82** [comment]
nah, it doesn't the grabber still has the weakref to the object but the object its self is outside, this is an issue because if you say want to keep throwing the start of the list it'll keep trying to throw the object outside of the assembly.

**Comment by AlexTheSysop42** [comment]
Just tested it, yeah it doesn't dupe it

**Pull request merged**
