### PR TITLE
Humans that get turned into monkeys don't get monkey AI

### LINKED ISSUE #55539: Monkeying people sometimes creates an invisible copy of them?
## Testmerges:

I've observed this a few times today. Pretty sure this was one of the rounds. From what I can tell, when you inject someone with a monkifier mutation, it might create an invisible version of them? For the round in question, I turned bob oakland into a monkey, and at some point later when I was dead, I jumped to his mob. I ended up going to the roughly the place that I turned him into a monkey, but he was a monkey at the time and somewhere else completely. Later on other players noticed and made a big event out of it. 

I want to say it was caused by #55238 but idk

### PR DESCRIPTION
**Pull request by Yenwodyah**
## About The Pull Request
Humans that transformed into monkeys and then back into humans were having monkey AI applied to them in their human form. (But funnily enough, not in their monkey form). This PR fixes that by properly transferring null AI status through transformations.
Also fixes a bug where a monkeyfied human's old human body would stick around invisibly after transforming. No clue why this was happening, but it's fixed now.

fixes #55539

## Changelog
:cl:
fix: Spacemen that get turned into monkeys and back again will no longer be affected by their primate instincts
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
can you keep the ai for monkeymens without a mind? its funny  and makes sense of a monkey brain being stuck in a human body

**Comment by Qustinnus** [comment]
this PR prevents humanized monkeys from having the AI if I'm reading the code right, which is not the intended effect.

**Comment by Qustinnus** [comment]
actually disregard that i misread

**Comment by cacogen** [comment]
Someone flushed a catatonic monkeyman yesterday and I was very confused on why it behaved in a manner not unlike a player. Certainly better than having them stand there doing nothing.

**Comment by Yenwodyah** [comment]
> can you keep the ai for monkeymens without a mind? its funny and makes sense of a monkey brain being stuck in a human body

That still works

**Comment by Vanadiom** [comment]
Please merge this, It is literal hell, I tried being a monkey to tide me some access, but instead I am stuck permanently chasing some fucking assistant that wanted to turn me into a burger.

**Comment by wesoda25** [comment]
> Please merge this, It is literal hell, I tried being a monkey to tide me some access, but instead I am stuck permanently chasing some fucking assistant that wanted to turn me into a burger.

I was a cult geneticist and my coworker roundstart monkey rushed me and once I was turned back I couldn't stand still long enough to draw a rune SPEED MERGE

**Comment by ATH1909** [comment]
> Please merge this, It is literal hell, I tried being a monkey to tide me some access, but instead I am stuck permanently chasing some fucking assistant that wanted to turn me into a burger.

They're just awakening the ultra instinct deep within you. Embrace it. Become the monkey spirit-assisted aimbot you were meant to be.

**Pull request merged**
