### PR TITLE
Restricts certain uplink items from appearing in low pop

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
rscadd: Adrenals, no slips, surplus crates and SUHTANDOS now have minimum population requirements before they can be purchased.
/:cl:

Adrenals, no slips, and suhtandos will not appear if the crew is smaller than 25 players.

Surplus crate requires 30 players.

> but kor why these items?

Because they all greatly increase a traitors survivability/stun resistance, which is fine with a full crew, but bad when there is only a single officer or ragtag collection of vigilantes trying to stop the bad guy.

This won't fix the problem entirely, but it will mean that the clown PDA will be enough to stop the rampage, no matter how many guns the guy stole from the armory.

### CODE REVIEW

**Comment by Robustin** [comment]
Would've preferred to give the crew a means to fight back, holoparasites were probably the only real "offender" to lowpop since even a braindead halfwit could summon a holo and murderize the crew. Almost any halfway decent tatertot can still achieve the same effect with any of the other weapons. Instead of nitpicking away at the traitor arsenal while I get inevitable ahelps about "where's my suhtandos", personal defense weapons are an answer to almost every lowpop rampage tactics. Holoparasites are vulnerable to ranged damage, adrenals don't do shit against getting shot, etc...

Anyway preaching's over, this is still a net positive for lowpop so its better than the status quo.

**Comment by Supermichael777** [comment]
lets give guns to everyone! Surly they wont be used by greytiders against non antags!

**Comment by lzimann** [comment]
aw man not the crate

**Comment by AlexanderUlanH** [comment]
I just want to say I've never given everyone guns and then come to regret it. Personal defense weapons actually seem like a pretty good idea.

**Comment by Steelpoint** [comment]
I disagree with removing items from low pop.

Firstly what if the game barely starts in low pop before exploding in population? Plenty of people delay joining at round start, you can get 50 people on a server yet almost get 25 to ready up at best.

Secondly its just inconsistant.

Honestly I'm coming around more to the Oldman school of thought with low pop.

**Comment by KorPhaeron** [comment]
Oldman's (purposefully weak) defense weapons wouldn't do shit if the other guy has the entire armoury+a stand/adrenals to just shrug off their attacks. Even if you hit him past his taser/disabler spam, he'd just be able to shrug it off.

**Comment by Steelpoint** [comment]
If someone has stolen the entire armoury and is toting high end Traitor gear then no amount of removing adrenals and no-slips is going to save the average crew member.

At least with a shitty rifle/pistol the average go getter can do SOMETHING. Removing adrenals and no slips and whatever simply forces the traitors into using other gear that is still highly lethal and will change little overall.

**Comment by KorPhaeron** [comment]
If a traitor steals 6 guns and an officer tases him, or the janitor slips him, thats it, its over. It doesn't matter how many laserguns or eswords he has stashed in his bag.

Unless he has an adrenal. Then he springs up and kills the officer (or escapes, and the officer has to win the right 2 more times to exhaust the implant, than once more to finally stop him).

There is a vast, vast, vast difference between having to tase a guy once, and having to tase a guy 4 times while he is at max move speed.

I'm not taking away traitor lethality, I'm taking away traitor durability.

**Comment by Steelpoint** [comment]
But the identified problem with low pop is that the majority of the minimal crew are helpless against a aggressive traitor. There's already the marked problem of little to no security population on low pop and unless your Janitor is lugging around a pair of cuffs then slipping the traitor is not a guaranteed finishing move.

Lack of adrenals is going to make zero difference when Traitor McTraitor walks into Science and guns down all two scientists in the department.

But if the two Scientists had access to a crummy fire arm, then it at least gives the Traitor pause in attempting to attack them.

**Comment by Iamgoofball** [comment]
i killed a rampaging murderboner traitor in lowpop one time

i had put space lube in my bucket

alt-tabbed for 30 min in my office

came back

went to intersection between medbay, command, and the ring

lubed up the floor intending to grief

traitor comes running through

slips

drops his esword

i saved the day

remember kids

noslips dont stop lube

**Comment by KorPhaeron** [comment]
Yeah but andrenals and stands do

**Comment by Iamgoofball** [comment]
simple solution: make stands slip on space lube and make adrenals just increase movespeed instead of stun resist

**Comment by Steelpoint** [comment]
There once was a murderboner with a gun.

Who was shooting everyone for fun.

So I ran out with lube.

And I ended his root.

By shoving his sword down his throat!

**Comment by duncathan** [comment]
I like this much better than Robustin's PR.

**Comment by AdamElTablawy** [comment]
stands slipping on space lube would be fucking hilarious imo, if completely illogical

i'm just watching a very confused and angry holoparasite skid down the hallway on it's ass because the clown got mad

**Comment by Lumipharon** [comment]
Stop saying 'muh lube', adrenals and stands are the main offenders because the let you counter or completely ignore stuns.

**Comment by Bawhoppen** [comment]
kor make it a config option, this is way different on basil than sybil

**Comment by KorPhaeron** [comment]
I don't think basil enjoys lowpop murder any more than sybil does. 

Hell they probably enjoy it less.

**Comment by Bawhoppen** [comment]
basil doesn't have lowpop murderbones in the same way sybil does

**Comment by KorPhaeron** [comment]
Wait a minute you don't even like stands I'm not falling for this

**Comment by Bawhoppen** [comment]
so?

**Comment by optimumtact** [comment]
a lot of this stuff should be some kind of config mini language

**Comment by lzimann** [comment]
let's make the entire game a config

**Comment by optimumtact** [comment]
That is stupid

**Comment by KorPhaeron** [comment]
@Core0verload 

Obviously I can't speak for your server, but noslips are the #1 most abused item by our highest profile murderspree players. The ability to lay down aoe stuns (that you're immune to!) from a spray bottle while moving full speed is an easy way to take out the entire security force as they chase you down maint.

**Comment by Core0verload** [comment]
Helpful in getaways? Helpful against shitsecs? Yes, and yes. But it's not nearly as helpful against competent, robust assistants, and every lynch mob has at least one. And taking out the secs is often as simple as luring them into a CO2 cloud or such.

**Comment by Bawhoppen** [comment]
:-1:x:100: since kor refuses to make it a config

**Comment by optimumtact** [comment]
If it's low pop there is no guarantee of having any "competent" "robust" assistants

**Comment by Lumipharon** [comment]
noslips aren't useful 'for getaways or for shitsec'. They are aggressive items that let you just ignore peels and water (mainly your own water) to shit on nerds.

If you're trying to escape, you can just spray behind you. If you're fighting sec, literally when do you ever worry about the sec officer whipping out a bucket of water or something?

**Comment by Durkel** [comment]
This won't help, and if you think it will you've got little idea what a low pop murderbone is like. The easiest solution is to admins stop being lazy pricks and actually deal with the asshole ruining the round for everyone. 30 minute rounds with 80% of the station dead because one guy has a ebow and esword isn't fun. You can write home about how "muh I can do whatever I want as a antag", and which I can reply with a hearty "fuck you". This shit is not fun, Come up with a fucking gimmick, or try to stroke your murderboner when there's actually enough players on to be a challenge.

**Comment by Iamgoofball** [comment]
why is it my job as an antag to entertain you

i play games to entertain myself

**Comment by Durkel** [comment]
Then you should play a single player game where you can be a dick by yourself. If the only fun you can manage to have while playing ss13 is rolling antag and then proceeding to roll a practically defenseless 20 pop crew then you're on the wrong station. You want to murderbone at 50+ pop, go for it. You managed to kill everyone too, hot damn, good job.

Not low pop, not when everyone is just relaxing and rping. We shouldn't have to massively shift game play style because one person decided to rush into the armoury (that had no security to begin with), grab all the guns and then go on a rampage. It will always be shit to do a low pop murderbone, there's no way to justify that save a escape alone.

That said, restricting items isn't going to help. Even something like a ebow and a stick of c4 to disable comms is a death sentence at low pop. If you want to prevent something like this you're going to need policy change.

**Comment by Iamgoofball** [comment]
maybe the armory shouldnt have guns if there's no security to defend it

**Comment by Lumipharon** [comment]
This isn't going to 'fix' low pop murderbone, but it will make it less impossible to beat.

If they don't have adrenals (or hulk), then 1 stun will most likely be a ggnore.

**Comment by CPTANT** [comment]
I have the feeling low pop murderbone occurs way less often then someone people would like you to believe.

And when it does happen it is by no means AUTOMATICALLY a bad thing. Sometimes you just lose the struggle.

**Comment by lzimann** [comment]
rip crate(all i care about tbh)

**Pull request merged**
