### PR TITLE
Bubblegum is faster

### PR DESCRIPTION
**Pull request by ChangelingRain**
It charges faster, has less delay before charges and blood warps, and TRIPLE CHARGE ISN'T BROKEN!

### CODE REVIEW

**Comment by Kromgar** [comment]
You mad man

**Comment by PKPenguin321** [comment]
Who are u

I'm u but faster

**Comment by XDTM** [comment]
If we balance megafauna around top players nobody else will be able to defeat them

**Comment by jughu** [comment]
Kors oc should have a godmode tag he should never lose

**Comment by ChangelingRain** [comment]
have you ever fought bubblegum, anyway? the charges are SLOW AS FUCK and easy to dodge.

**Comment by XDTM** [comment]
I couldn't outrun a bubblegum chasing me last time i went up against one. It probably is easy to dodge, given some space, but it's hard to lose aggro if you don't want to fight it.

**Comment by ChangelingRain** [comment]
Yes, its normal movement is difficult to avoid, but its charges are slow as fuck and easy to avoid.

**Comment by XDTM** [comment]
Hard to outrun due to endless charges, i meant. Not really related to fighting it, though, i realize, so it's a bit offtopic.

**Comment by Kromgar** [comment]
May god have mercy on everyones soul if he gets on station

**Pull request merged**
