### PR TITLE
Fixes small chem doses

### LINKED ISSUE #36152: You can gain a permanent speedboost by smoking
Round ID: 84467

If you add a small enough ratio of speed boosting chemicals to a cigarette/cigar/e-cig, and smoke it for a second, the speed boost you get will never run out.

[Reproduction]:
Prepare chemicals that boost your movement speed (meth, ephedrine, whatever else).
Water it down a bit. Let's say 20% of the boosting mix, 80% of anything else. 
Suck the mix in something you can smoke.
Smoke it.
You're now supersonic forever. You can take off the smoke and still keep it.
Bonus points by adding morphine, meaning you can run ultrafast no matter what you wear or how much damage you take.
So you can run around in a hardsuit and DUFFLEBAG at light speed.

You can even do this! [Sonic the clown](https://i.imgur.com/mXhyCOt.gif)
And yes it sounds as annoying as you think.

I only found this working for movement speed. Health regen, stun decrease or whatever else don't stick after smoking it. 
The health analyzer shows the reagents never entering you. At a higher ratio of the mix, it _does_, and then it just works normally.

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
fix: Tiny amounts of chems no longer have unintentional behaviors.
/:cl:

fixes: #36152

This fixes two separate flaws, That traits were added from reagents last, after the reagents removal could have been processed, and that removal of traits or reversions of changes never checked that those changes had been made (so brave bull could make a death vape after the fix for the og bug for example).  

It does this by checking if reagents have been qdeleted before adding the trait and that the trait or change has been added before trying to remove it. It does this without the old stutter-step bug returning. Sorry for the poor form last time.

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
If(on_mob_add(blah))
     mobeffective = TRUE

would this not work? I don’t like the idea of having to ensure you manually set it to true everytime you work with a reagent

**Comment by ExcessiveUseOfCobblestone** [comment]
That said, is there no way to forgo the var entirely and have the fix localized in the offending procs itself?

**Comment by Supermichael777** [comment]
This is much more future proof. Considering the great liberties certain persons in our codebase take with petty things like reading the documentation and "testing" future additions will have the fix for potential fuckups like brave bull becoming adminproof deathjuice (best bug that never was).  

I should have done it that way with the if(on_mob_add) add but I don't feel like manually reverting it.

**Comment by vuonojenmustaturska** [comment]
Does the mobeffectactive var even do anything? It's not like you're running extra checks on delete if the var is set, at a glance it seems like the `&&!QDELETED(R)` check in the branch leading to on_mob_add is the one that is actually doing anything here

**Review by Cyberboss — CHANGES_REQUESTED** [review]
What Naksu said

**Pull request closed without merging**
