### PR TITLE
Wiz-Off: An Arcane Battle for the Fate of the Universe!

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
image
Adds Wiz-Off, a new and extremely simple card game to the Fun Vendor. The rules are simple:
Players draw 5 cards.
Players play 5 rounds.
Victory in a round is determined by a rock paper scissors-esque circle: Defensive beats Offensive beats Utility beats Defensive.
In the event of two cards of the same class being played, the highest number wins.
Best of 5 wins.
Rules are easily checked ingame by examining more on the deck.

Oh, and as a little aside- I made the code modular at the request of Anturk: Creating a new card game with the same rules is as easy as adding the cards to wizoff.json, changing the theme variable, and adding sprites. I'm not sure why you'd want to do this, but hey, easy request, and it makes the code a bit cleaner.

## Why It's Good For The Game
In comparison to some of our other card games, this is much more playable with the game's controls and timeframe of the rounds. Also, it's a fun little distraction that people can enjoy in downtime, which I think the game needs more of.

## Changelog
:cl:Inept
add: The Nanotrasen Entertainment Division has released a new card game designed to be played quickly and easily: Wiz-Off.! Join the battle at your local Fun Vendor today!
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
so, card-jitsu but purple?

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=D_2bluVPsb0

**Comment by EOBGames** [comment]
> so, card-jitsu but purple?

You weren't supposed to reveal my hand like that, man!

(Joking aside, it's based on card-jitsu, but has a few things stripped back, like card colours and special cards, since this is meant to be about the simplest card game it's possible to make)

**Comment by TheBonded** [comment]
> so, card-jitsu but purple?

Came here to say this

**Review by Twaticus — APPROVED** [review]

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-7). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
