### PR TITLE
Warden Compact Combat Shotgun

### PR DESCRIPTION
**Pull request by Steelpoint**
I am very hesitant to suggest new weapons for security, as I do agree I tend to go a bit overboard and be overzealous at times. Nonetheless I do think the current Cycler Shotgun is lacking and is underused enough that I think this is a acceptable alternative.

This is a semi-continuation of my prior PR: https://github.com/tgstation/tgstation/pull/27362

--

This PR replaces the Cycler Shotgun, which is still in the code, with a Compact Combat Shotgun. Which is placed into the Warden's Personal locker only.

This is a one off item, there is no other way to buy or acquire this weapon in the game, you cannot saw off regular Combat Shotguns to make this.

The CCShotgun is less bulkier than the regular CShotgun, thus it can fit into armour slots, but it can't fit into backpacks. However this comes at the cost that the shotgun only holds four shells in the tube, down from the regular six.

compactshotgun

:cl: Steelpoint
add: The Warden's Cycler Shotgun has been replaced with a Compact Combat Shotgun. A unique weapon, it can fit in armour slots but at the sacrifice of a smaller ammo capacity of four shells.
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)

### CODE REVIEW

**Comment by vcordie** [comment]
this is shockingly sane.

**Comment by dannno** [comment]
probably better than the cycler tbh.

**Comment by factoryman942** [comment]
Wait can't you just empty a normal shotgun, saw-off and store in backpack

**Comment by Steelpoint** [comment]
Yes.

However, a saw-off Riot Shotgun just becomes smaller, you still need to pump it after every shell. 

Whereas the Compat Combat Shotgun remains a semi-automatic weapon. Only difference is you can fit it in your armour slot, though you can't put it in a backpack.

**Comment by FantasticFwoosh** [comment]
I prefer this over a sec rifle and the cyndrical shotgun which felt useless (can't fire unless its aimed at something technicality, can't empty etc, opaque function & bullets loaded in) & a bit over the top.

However this is substantially better than the rest of the shotguns by a mile, so if we could put a DNA pin inside it, that'd be great.

**Comment by Steelpoint** [comment]
The shotgun can only fit in a armour slot akin to the regular Combat Shotgun. So you have to keep it visible at all times, either by holding it or by having it be seeable upon examination. 

No idea how I would do a DNA pin, and I think a loyalty pin would not go over well, and be redundant if you have access to the armoury.

**Comment by GunHog** [comment]
I guess you failed in your attempt to fix the cycler, huh? By the way, that sprite is rather low effort, @WJohn might be able to help you here.

**Comment by Steelpoint** [comment]
I never made a attempt to fix the Cycler, it's beyond my abilities.

**Comment by GunHog** [comment]
Then replace it with something unique, such as being able to put a suppressor on it or something.

**Comment by Steelpoint** [comment]
The biggest issue with the weapon is its unreliability and how bulky it is.

I can't make it more reliable, but I could make it less cumbersome, but that was rejected. Thus I am proposing a alternative Warden issue weapon.

I'd suggest a Energy Shotgun but that is also beyond my abilties.

**Comment by Dorsisdwarf** [comment]
Doesnt the energy shotgun already exist

**Comment by FantasticFwoosh** [comment]
Its on the old removed space hotel ruin (its also OP as shit)

**Comment by Shapsy** [comment]
Since when was the combat shotgun not one of the best firearms in pure killing power on station

**Comment by Anonmare** [comment]
DNA pins have to be pricked on whoever you want to lock it to before putting the pin into the weapon. You'd have to make it start in the warden's inventory or snowflake a method of it knowing who the warden is, even after shift start in case of late arrivals.

**Comment by dannno** [comment]
There's nothing wrong with the sprite? It makes complete sense for it to look the way it does
This doesn't have to be a super cool snowflake unique warden epic gun!!!!
A shortened combat shotty is fine.

**Comment by BeeSting12** [comment]
The cycler is kind of bugged and essentially useless, I feel this is a good change.

**Comment by octareenroon91** [comment]
>However this is substantially better than the rest of the shotguns by a mile, so if we could put a DNA pin inside it, that'd be great for warden's use, so emaggers can't just pick up a shotgun they can hide in their bag & then surprise unload on people with as a discount revolver.

There's still a pin removal recipe.

**Review by Cyberboss — APPROVED** [review]

**Comment by Thunder12345** [comment]
The problem with combat shotguns is the price. I buffed them ages ago because they were just slightly larger riot shotguns. When Goofconomy was done they somehow ended up disgustingly cheap.

**Comment by Iamgoofball** [comment]
# you know if we did guncrafting this literally could of just been done without needing 5 sprites, a new item definition, and new internal magazine definition

**Comment by dannno** [comment]
stop typing so big you nigger oh my god why are you like this when are we finally going to find a cure for autism

**Comment by Iamgoofball** [comment]
SWKHFASJHGDFJGHJGHWREFGJHWAESGHJFESS

**Comment by dannno** [comment]
thank you.

**Comment by Iamgoofball** [comment]
<3

**Comment by Bawhoppen** [comment]
give it a cool name and I'll make you a cool sprite for it, WJ taught me how to sprite real nice

**Comment by Steelpoint** [comment]
I honestly think the sprite is fine.

**Comment by Bawhoppen** [comment]
looks ghetto to me

**Comment by Steelpoint** [comment]
Really its more that the Warden took of the stock and strap, called it a new gun, and everyone just nodded and moved on with their day.

**Comment by GunHog** [comment]
Let Bahoppen make you a sprite, yours looks more like really long pistol, and there is no effort behind it!

**Comment by calzilla1** [comment]
Give the warden an ak47

**Comment by dannno** [comment]
It's a shortened combat shotgun.
The sprite is a combat shotgun sprite, shortened appropriately
???

**Comment by FantasticFwoosh** [comment]
@octareenroon91 yes but that's a intentional way of working around it, and you'd need to get past a shotgun armed warden to do so.

> A box of 2 dna pins & some instructions on a piece of paper how to use, then remove the pins from the wardens own collection of unique weapons so that they can only choose 1 or two secure weapons.

**Comment by demonfiren** [comment]
isn't there already a normal pump-action shotgun that does the same thing?

**Comment by Steelpoint** [comment]
Ask and ye shall recieve.

**Pull request merged**
