### PR TITLE
Make butt sprites overridable for downstream

### PR DESCRIPTION
**Pull request by thegrb93**
## About The Pull Request
Allows changing the spritesheet for downstreams
## Why It's Good For The Game
Small code cleanup and lets downstreams do more butts for other species.

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Ignoring the implications, `get_butt_sprite` should be refactored into returning an `icon` (`return icon(x, y)`) rather than do this

**Comment by thegrb93** [comment]
That would overcomplicate things and make us have to also overwrite all the TG get_butt_sprite to use the new icon. Also downstream already has some get_butt_sprite proc that return string already.

**Comment by Jacquerel** [comment]
> Downstream already has some get_butt_sprite proc that return string which would be broken by the refactor.

You're PRing to our codebase, you should write the code correctly and then fix your downstream to work with it. You are already on thin ice from "literally not filling in the mandatory why it is good for the game" part of the PR body.

**Comment by thegrb93** [comment]
Sorry, fixed that

**Comment by thegrb93** [comment]
I don't really get the request to make it return an icon. It'll be a lot of duplicate code and string paths for each spot, but sure we can do it.

**Comment by thegrb93** [comment]
Refactored as requested

**Comment by thegrb93** [comment]
And tested 
image

**Comment by san7890** [comment]
yeah i think there should be a better way to describe these changes as "it's better for downstreams" because at it's core it is a pretty nice improvement for even our codebase to have this be on a getter proc and avoid the constant typecasting etc.

**Comment by thegrb93** [comment]
Ohhh, that's what he meant. I didn't understand (pretty new to byond). I think I can give that a go.

**Comment by thegrb93** [comment]
I updated the 'why it's good' with something more sensible.

**Pull request merged**
