### PR TITLE
Adds C4 bag to uplink

### PR DESCRIPTION
**Pull request by AnturK**
9 TC for 10 C4
Yes, it's a discount.

:cl:
rscadd: Syndicate Operatives can now buy bags full of plastic explosives for 9 TC.
/:cl:.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Too many C4s for too many TCs, ops wont use them all and it won't get bought because of that
Make it like 5 C4s for 3 TCs or something

**Comment by Zilenan91** [comment]
:+1:  to PKs suggestion at this price nobody will ever buy it.

**Comment by Bawhoppen** [comment]
I'd use it for the storage space of the c4s if anything

**Comment by Lumipharon** [comment]
Pk has it right. Scale it down, no one is going to use 20 c4.

**Comment by Anonmare** [comment]
>No one is going to use 20 C4s

That's what you think

**Comment by Lumipharon** [comment]
well if they do, they can just buy multiple smaller bags.
If they are large bags, you can't buy a half or quarter of it.

**Comment by AnturK** [comment]
Alright, made it 10 for 9. I mostly intended this for traitor gimmicks but i guess syndies could use these.

**Comment by octareenroon91** [comment]
What would you say to five c4s in a free smuggler's satchel?

**Comment by Bawhoppen** [comment]
that sounds like you'd never want to buy a smuggler's satchel then

**Comment by PKPenguin321** [comment]
well fuck
this conflicts with my EMPs pr
reeee

**Comment by borntohonk** [comment]
9 explosive lances oh boy

**Pull request merged**
