### PR TITLE
Only allow one call to IsBanned to process at a time, per ckey

### PR DESCRIPTION
**Pull request by optimumtact**
Potential improvements, store the list on a subsystem, also include
ip/cid based flood checking

Clear on a timed basis instead of after finishing

shouts to @monster860 for being stinky to make this

### CODE REVIEW

**Comment by optimumtact** [comment]
was thinking about a subsystem that sweeps the cache lists each tick and decrements all active counters by one

**Comment by optimumtact** [comment]
other approach is a world.time based resetting

**Comment by KingTerrytheTerrible** [comment]
what is this meant to do?

**Comment by optimumtact** [comment]
I have another planned Idea, which I will make along side this one

**Comment by optimumtact** [comment]
This is working on downstreams, we shoudl ship it and look to improve later

**Comment by AnturK** [comment]
Could use some slow cleanup in case of runtimes.

**Pull request merged**
