### PR TITLE
Fixes weird bug when changeling with augmented eyesight (that isn't on) readapts.

### LINKED ISSUE #11773: Weird Changeling seeing through walls bug
I was playing a round on basil as a changeling, anyways after I had already absorbed someone I was buying my powers and I misclicked, so I readapted and then I was somehow able to see through the walls like genetic's xray vision with darkness and all. 
ss 2015-09-13 at 07 42 17
For the sake of science I tried killing myself and regenerating and that didn't remove it, and then it continued for the rest of the round.

### PR DESCRIPTION
**Pull request by phil235**
Fixes #11773 
Made the code dealing with special things to do when removing certain changeling powers more OOP.

### CODE REVIEW

**Comment by xxalpha** [comment]
This fixes keeping the eyesight after readapting, right?

**Comment by phil235** [comment]
@xxalpha yes, I tested readapting with both augmented eyesight off and on.

**Comment by Dorsisdwarf** [comment]
@phil235 ready for merge?

**Comment by phil235** [comment]
@Dorsisdwarf yes

**Pull request merged**
