### PR TITLE
Fixes DRAGnet net mode not dealing stamina damage

### PR DESCRIPTION
**Pull request by Maia-J**
## About The Pull Request

This was meant to be a thing. Looking at the gitblame it has been broken for **9 fucking years** (Ever since it was added):

image

How the hell did NOBODY notice for so fucking long

## Why It's Good For The Game

Actually makes something work as intended. Might make sec consider less lethal options when dealing with threats.

## Changelog
:cl:
fix: after 9 years, adds a single dot to the dragnet code, making it deal stamina damage as intended
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
are we sure they're currently NOT doing stamina damage? I remember doing some testing with them like a year or two ago.

**Comment by Majkl-J** [comment]
> are we sure they're currently NOT doing stamina damage? I remember doing some testing with them like a year or two ago.

Considering on_hit() needs to return BULLET_ACT_HIT to actually make it disable, yes.

**Comment by jughu** [comment]
powercreep net+stam damage practically disabler+

**Comment by projectkepler-ru** [comment]
> powercreep net+stam damage practically disabler+
> 
> This while also not make sec approach threats less lethally it just means they will use this to stamcrit the antag even easier and just kill them right after especially since its a backpackable gun

if a  bug fix cause security to get buffed I think we really need to consider what else has been broken in sec and been secretly nerfing them

**Comment by Majkl-J** [comment]
> powercreep net+stam damage practically disabler+

This is a bugfix, the values have always been that. It just happened to be/get broken and nobody bothered to fix it.

Someone else can adjust the balance later, as far as I am aware this is a bug and it should be fixed.

**Pull request merged**
