### PR TITLE
Various cult equipment rebalances to address energy weapon immunities being too common

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Prevents cultists from acquiring the shielded robe and mirror shield from the daemon forge. Also replaces the eldritch longsword in the equipment spell with a cult dagger.

Eldritch Longswords now have block chances, and are made in the forge instead of the mirror shield. They have a 50% block chance.

Cult dagger also have block, but only 25% and cannot block projectiles.

Nar'sian Hardened Armor are able to be acquired from the daemon forge instead of the shielded robe. They have had their stats tweaked to match the old robe, but the cult version doesn't have slowdown.

## Why It's Good For The Game

When I was doing my revisit to pipeguns, I was pretty plainly told by Rohesie we need to start towards getting rid of weapons like the pipegun, and what I was doing was a waste of time. Maintainers in general would be looking to move in that direction, so I closed the PR but said I feel then it would be appropriate to look to what would severely impact the game should those stop existing.

I argued that the primary reason most ballistics are somewhat necessary for the sake of game stability _right now_ is that many game modes actually have anti-energy weapon gear or energy weapon immunity gear in them, or just weapons that deliberately punish using anything but the hardest hitting weapons with as many attacks as possible (AKA shotguns). Cult specifically was an example I was, straight from the horses mouth, told was balanced entirely around the crew needing to use ballistics to get anywhere in defeating them.

The two items removed were mostly meant to stop tasers (and for shielded robes, hardstun stun batons as well). Tasers have been gone for nearly two years. The only good they do now is mandating ballistic weapons like autorifles, shotguns and such to deal with cult.

As such, these items do next to nothing for the cult due to everyone quickly and easily moving to use their main weakness to bypass these immunities, so they often go untouched. They only exist to give reason for crew to produce shotguns as expediently as possible.

Since the cult have less fears about instant stuns than in the past when these items were first added, they now need more generalized defences that decent block and reasonable armor can provide. Worse case scenario, they still have EMP if they need to turn off an egun or two.

Moving the eldritch longsword into the mirror shield slot was primarily because lol it's an esword bro, why can you just conjure that shit in your hand? For free? From anywhere? Fucked up.

_(real question is when is cult being disabled so this isn't a problem anymore because gosh there are so many problems with cult that a single balance pr like this is more or less just paving over this horrible problem child of a mode)_

## Changelog
:cl:
balance: Shielded Robes and Mirror Shields can no longer be made from daemon forges.
balance: Eldritch Longswords and True Nar'sian Hardened Armor can be made from daemon forges. True Nar'sian Hardened Armor has no slowdown, unlike the lavaland version.
balance: The equipment spell now grants you a cult dagger. Still separate from the other spell so that you can acquire a dagger without being slapped with a validsuit.
balance: Eldritch longswords and cult daggers have block chance (50% and 25% respectively). Cult daggers cannot block projectiles and the cult ghost longsword only has 25% block chance.
balance: The cult blindfold only stuns you if you actually are stupid enough to put it over your eyes.
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
While you're touching cult stuff would you mind removing the hard stun from picking up cult blindfolds? Misclicking a pile and being left stunned AND blind is a pain in the ass, at least the blind thematically made sense.

**Comment by itseasytosee** [comment]
Might as well just remove the create cult dagger speel while you're at it.

**Comment by Mothblocks** [comment]
> Still separate from the other spell so that you can acquire a dagger without being slapped with a validsuit.

@itseasytosee

**Comment by moocowswag** [comment]
Does this mean the homonculi with eldritch longswords that can be instantly summoned and respawned from the spirit realm rune are getting a 50% block rate?

**Comment by necromanceranne** [comment]
> While you're touching cult stuff would you mind removing the hard stun from picking up cult blindfolds?

I'll have it stun on equip to the eyes.

> Does this mean the homonculi with eldritch longswords that can be instantly summoned and respawned from the spirit realm rune are getting a 50% block rate?

Whoops I forgot to mention. The ghost sword version has a 30% block, because they're free goons. Thanks for reminding me to add that to the open post and sorry for the confusion.

> I see a major side effect of this pr and thats that it really raises the skill ceiling of cult while lowering the skill floor, the avg cult player is not gonna make ruined metal and an anvil to get an eldritch sword nor abuse spirit realm rune.

I mean...cult already has those boundaries, I can't fix cult being astronomically more complicated than it already is. I can say that the average cultist can now at leaat have a slightly better melee weapon upon conversion, but even then, you still get cultists who never gear themselves up even with their cult dagger.

**Comment by Krysonism** [comment]
>Eldritch Longswords now have block chances, and are made in the forge instead of the mirror shield. They have a 50% block chance.

This just makes the swords more like the halberds, if you want block you should have to get a halberd. 

Or get a riot shield or buckler.

**Comment by moocowswag** [comment]
You know what i can agree better daggers do make things better with the skill floor and help simplify things.

> This just steps on the toes of the halberd, if you want block you should have to get a halberd.

If youre refering to the spear from blood rites I dont think the block rate is the selling point of the weapon, especially when it can be semi reliably sacrificed for a ranged hard stun.

**Comment by Sparkezel** [comment]
Didn't you just basically remove the damn mirror? If not where can you use it now? Also the damn shield has blockchance in and of itself and can summon "ghosts" simplemobs with your apperace that also deal damage to non-cultists, what about them?

**Comment by necromanceranne** [comment]
> Didn't you just basically remove the damn mirror? If not where can you use it now? Also the damn shield has blockchance in and of itself and can summon "ghosts" simplemobs with your apperace that also deal damage to non-cultists, what about them? Its not balance its goddamn removal.

Yeah it is

**Comment by necromanceranne** [comment]
> And if this pr is merged cult loses their only other ranged hard stun which is the mirror shield so blood halberd's toes may be stepped on but they just gained new footing.

Don't forget bolas. They're not a stun anymore but a knockdown is still super valuable, and you can spam them to your hearts content.

**Comment by Sparkezel** [comment]
> Yeah it is
> 
> 

Remove them fully then

**Comment by necromanceranne** [comment]
I mean, we retained the bastard sword in the code. I think they're conceptually neat, but maybe for specifically admemery.

**Comment by necromanceranne** [comment]
@carshalash added that slot check for ya, it doesn't change much balance wise so it's a whatever change

**Comment by Ratvar** [comment]
I think some cult items, like shield, would fit as expensive wizard items with a bit of work

**Comment by moocowswag** [comment]
Give the cult leader the shield?

**Comment by necromanceranne** [comment]
Giving the cult leader anything other than a boot to the head is a distinct mistake.

**Comment by Sparkezel** [comment]
Their spells get reset upon being selected so I guess that could use a fix

**Comment by necromanceranne** [comment]
The reason it does that is because it wipes your antag status, then gives it back as the leader.

**Comment by optimumtact** [comment]
👎

**Pull request merged**
