### PR TITLE
SNPC's now have a much lower chance of being able to talk

### PR DESCRIPTION
**Pull request by Iamgoofball**
Requested by HBL

### CODE REVIEW

**Comment by phil235** [comment]
Terrible title...

**Comment by Iamgoofball** [comment]
since when are SNPCs not a 1:1 recreation of the average player

**Comment by WJohn** [comment]
Thank christ.

**Comment by Lumipharon** [comment]
It was always amusing how snpc basically shitposted over radio in a continuous stream.
Amusing, but retarded. :+1:

**Comment by bgobandit** [comment]
do SNPC mimes still talk

**Pull request merged**
