### PR TITLE
New tile sprayer + airlock painter sprites

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
All credit to @crumpaloo for the sprites, this was just the result of our conversation

All new sprites for 4 versions of the sprayer, complete with in hand sprites. The debug version of the tile sprayer gets upgraded to this sort of CoD-satire bloody reskin that I'm still thrilled about. 

Clockwise: airlock painter, decal sprayer, admin sprayer, tile sprayer.
Screenshot 2022-05-16 005423
Inhand sprites.
Screenshot 2022-05-16 005639

I also changed the icon state names to be more conformant. Tested and all working.

## Why It's Good For The Game
old sprites were not epic

## Changelog

:cl: Crumpaloo
imageadd: Added new sprites for the airlock painter, tile & decal sprayer.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
Nice! Did you update the cartridge sprite for them?

**Comment by Crumpaloo** [comment]
> Nice! Did you update the cartridge sprite for them?

Heya, wasnt aware there were cartridges, if you already know where the dmi. files are
send me them at Crumpaloo#9431 and ill get that fixed. 👌

**Comment by Wallemations** [comment]
> > Nice! Did you update the cartridge sprite for them?
> 
> 
> 
> Heya, wasnt aware there were cartridges, if you already know where the dmi. files are
> 
> send me them at Crumpaloo#9431 and ill get that fixed. 👌 

Iirc they use the same ink the photocopier uses

**Comment by Jolly-66** [comment]
> Reply chain

They do

**Comment by ArcaneMusic** [comment]
I will say I was going for an "extreme" looking version of the decal painter for the admin version, not blood splattered, but that works since it's mostly there for testing more than anything (Although I suppose there's no reason we couldn't make this player facing, honestly!)

The only thing I'd suggest is change the body color of the tile sprayer to better distinguish it from the decal painter.

**Comment by notfrying1pans** [comment]
imo they're a little bit too flat

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
