### PR TITLE
Fixes inconsistencies w/ energy descriptions

### PR DESCRIPTION
**Pull request by ShizCalev**

### CODE REVIEW

**Comment by nicbn** [comment]
Watts is an unit of potency not energy

**Comment by SpaceManiac** [comment]
Maybe nitpicky, and I haven't yet looked into how this works in-game, but "A basic power cell that holds 1 kW of power" doesn't make sense. Power is a unit over time - you might say a power cell outputs at 1 kW (in the same way that an SME outputs at 50 kW by default), but it doesn't tell you anything about the cell's capacity. The capacity should be more properly measured in joules, a measure of energy, where 1 W = 1 J/s.

**Comment by ShizCalev** [comment]
If you want to be more accurate, batteries ratings are actually measured in mAh, but I don't feel like doing conversions for everything. reeee.

**Comment by SpaceManiac** [comment]
Not too worried about matching IRL conventions, 1 J = 0.2778 mAh * V, and SS13 doesn't really have a concept of voltage so joules is close enough and way easier to compare to watts.

**Pull request merged**
