### PR TITLE
Updates vending refill packs to reflect additional items added in headphones PR

### PR DESCRIPTION
**Pull request by silicons**
.. I don't even know how the counting in this file works but I hope this works!

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]
Explain the change because I don't understand it

**Comment by FantasticFwoosh** [comment]
Charges aren't assigned to individual items, they are assigned via a bit of math and you have to reflect how many charges (dispensible objects) it has

Adding headphones moves the formula around a bit and this is what mekhi is correcting so that objects aren't under-stocked.

**Comment by kevinz000** [comment]
@Cyberboss I forgot to update the charges so vendors would be understocked as there isn't enough charges until this change to fully stock all items because headphones were added.

**Comment by ChangelingRain** [comment]
vending refillers are unsustainable shitcode and should be much more dynamic

**Comment by PKPenguin321** [comment]
I've been meaning to refactor vending machines to only have one stocking unit that has a sane method for keeping track of stock

**Comment by kevinz000** [comment]
@PKPenguin321 pls do.

**Pull request merged**
