### PR TITLE
nightmare eyes and robotic glowing eyes can now be mistaken for blood cult glowing eyes

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

If your eyes are the EXACT same color as blood cult glowing eyes AND they have the "glowing" variable set to TRUE, then they'll produce the same message that glowing blood cult eyes do when you're examined.

Currently, the only eyes that can have this "glowing" variable be set to TRUE without admin intervention are burning red eyes (from nightmares) and active high luminosity eyes.

Burning red eyes have a red eye_color now.

## Why It's Good For The Game

Baiting validhunters is funny.

Plus, this feature makes sense- their eyes are, in fact, glowing an unnatural red.

As for the eye_color change for burning red eyes, nightmares don't have eye sprites, but their eyes can be transplanted into a normal human or something (and the sprites of the extracted eyes (and the names of the eyes themselves) very heavily imply that they're supposed to be glowing red).

## Changelog
:cl: ATHATH
add: Burning red eyes and active high luminosity eyes can now be mistaken for blood cult glowing eyes if they're the exact right color.
tweak: Burning red eyes now have a red eye_color. This shouldn't really matter unless you transplant them into a non-nightmare, though.
/:cl:

### CODE REVIEW

**Comment by OmegaDarkPotato** [comment]
Although it makes sense, I don't think that baiting jackasses into killing players when those players did anything wrong is "right". Haha funny validhunter kill random people haha and all, but this PR looks like it'd just make life tougher for the few people with red eyes + NVG eye combo.

Either that, or I'm just vastly over-imagining the population of people who have both red eyes + nvg eyes and aren't trying to bait validhunters

**Comment by ATH1909** [comment]
> Although it makes sense, I don't think that baiting jackasses into killing players when those players did anything wrong is "right". Haha funny validhunter kill random people haha and all, but this PR looks like it'd just make life tougher for the few people with red eyes + NVG eye combo.
> 
> Either that, or I'm just vastly over-imagining the population of people who have both red eyes + nvg eyes and aren't trying to bait validhunters

To be clear, you have to set your eye color to the EXACT eye color that blood cult glowing eyes use (or surgically extract the eyes from a nightmare and have your eyes be replaced by them) in order for this to kick in, so it's hard to invoke this unintentionally. Also, your eyes still need to be uncovered in order for this examine message to appear, so you can just wear any form of eyewear if you want to use your nightmare eyes in peace.

**Comment by Time-Green** [comment]
Can you just make it red? The EXACT same color as cult eye is basically impossible without code-diving the exact values.

**Comment by ATH1909** [comment]
> Can you just make it red? The EXACT same color as cult eye is basically impossible without code-diving the exact values.

How would I do that, exactly?

**Comment by Time-Green** [comment]
Convert the hexadecimal color to rgb. If red is 100 or higher and at least twice as big as the other colors, it’s considered red. [Here’s a good explanation with an example](https://stackoverflow.com/questions/59856547/determine-which-color-red-blue-green-or-other-would-be-visible-for-a-given-r)

I’m not sure if there’s a good way to convert to rgb, you’d probably need to check byond docs if there’s a way to do it at all

**Comment by Krysonism** [comment]
>fucking shitsec uncuff me i killed a nightmare
>fuu'majin

**Comment by Doosteroni** [comment]
eh, if your gonna go out of your way to set a specific color for your eyes and then getting glowing eyes, that's basically just calling yourself a tator. Basically all this will do is get a bunch of people killed because haha validhunt funee.

**Comment by necromanceranne** [comment]
If it was just red doesn't that mean albinos with red eyes will have this same message come up? They often already get shot dead.

**Comment by ExcessiveUseOfCobblestone** [comment]
makes a message specifically to out cultists > people add plausible deniability around it

i was ok with this at first but it just seems kinda pointless. Im fine with the eye color matching just not the unique message that says "you are literally cult"

**Comment by ATH1909** [comment]
> If it was just red doesn't that mean albinos with red eyes will have this same message come up? They often already get shot dead.

No, they won't give off this message (or a similar message), because their eyes won't have the glowing variable set to TRUE. Their eyes are red, but they're not glowing.

**Comment by ATH1909** [comment]
> makes a message specifically to out cultists > people add plausible deniability around it
> 
> i was ok with this at first but it just seems kinda pointless. Im fine with the eye color matching just not the unique message that says "you are literally cult"

""plausible deniabiliy""

In order for a nightmare to even SPAWN, you'll have to be pretty far into the round, far beyond the point where a competent cult would have already revealed themselves. The same also applies for the tech for glowing eyes being researched. In 99.999% of situations where you'd be caught as an actual cultist, claiming that "oh, these are just nightmare/glowing eyes" would be an INCREDIBLY flimsy excuse.

The unique message doesn't say "you are literally cult", it says that your eyes are "glowing an unnatural red". Nightmares were created by the wishgranter, a supernatural entity (plus, y'know, nightmares themselves literally jaunt around in shadows like a horror movie villain), and glowing eyes are robotic. Neither of them are natural.

**Comment by ExcessiveUseOfCobblestone** [comment]
the glowing red eye message was coded to be a cult-outing tool, but yes you are right it doesn't actually say "I am a cult outing plot-device" in the examine.

**Comment by ATH1909** [comment]
> the glowing red eye message was coded to be a cult-outing tool, but yes you are right it doesn't actually say "I am a cult outing plot-device" in the examine. Regardless, the effects of the PR is to add plausible deniability to something specifically meant to remove plausible deniability and just out a cultist.

Just because other, rare possibilities are TECHNICALLY possible doesn't mean that you have plausible deniability.

We have other "fake out" items in the code, like the dark blessing null rod form and the Arreyst balloon. Hell, there's even a drink that makes you speak in cultslurring.

Plus, it makes sense that if you replace your eyes with those of a cursed horror movie villain and they just passively glow red all of the time, people _might_ think that you're a witch.

**Comment by ExcessiveUseOfCobblestone** [comment]
bro you can't argue there isn't plausible deniability then go "well it's ok if there is"

I get your argument, but i don't agree with overlaying the "I'm a cultist" message (which is what the glowing eyes is actually suppose to be) with non-cultist items. They can still take on the color so it looks sus but examining should be the fool-proof difference between weird looking eyes and cult eyes since that's why cult gets red eyes in the first place.

Metabreakers are fine but metabreaking something that is explicitly meant to out the antagonist (rather than say a tool you keep hidden like the clock watch that's used as a conduit for handling cult functions) makes no sense except to add plausible deniability OR baiting people to kill others. If you're not coding for the first reason your PR is mega cringe.

That message should NOT be overlayed with non-cultist stuff as that was the entire point of the message to begin with. **I will not be accepting the message although I am fine with the visual similarities.**

**Comment by ATH1909** [comment]
> bro you can't argue there isn't plausible deniability then go "well it's ok if there is"
> 
> I get your argument, but i don't agree with overlaying the "I'm a cultist" message (which is what the glowing eyes is actually suppose to be) with non-cultist items. They can still take on the color so it looks sus but examining should be the fool-proof difference between weird looking eyes and cult eyes since that's why cult gets red eyes in the first place.
> 
> Metabreakers are fine but metabreaking something that is explicitly meant to out the antagonist (rather than say a tool you keep hidden like the clock watch that's used as a conduit for handling cult functions) makes no sense unless you're doing it to bait people to kill others. If that's the case your PR is mega cringe from an admin pov.
> 
> That message should NOT be overlayed with non-cultist stuff as that was the entire point of the message to begin with. **I will not be accepting the message although I am fine with the visual similarities.**

The message stuff is the entire point of this PR.

**Comment by ExcessiveUseOfCobblestone** [comment]
ok

**Pull request closed without merging**
