### PR TITLE
Giving the away missions some love: part 1

### PR DESCRIPTION
**Pull request by MMMiracles**
My journey to making all the away missions just a little less shit.

I'll probably do separate PRs for map fixing and general rehauls/remakes.

First one up: Beach

fak2

The immursion-breaking walls were placed with dense water and sand. You can't walk past it but you can see past them to the off-map decor (muh immursions).

The bar has a ghost spawnpoint for any ghost who wants to take control of the bartender who runs it (no shotgun).

100% more coconuts.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Neat

**Comment by Niknakflak** [comment]
>No beach showers
>Mens room doesn't have urinals

**Comment by MMMiracles** [comment]
theres a shower head in each on the bottom-section of the room. also fuck those urinal sprites look ugly anyway.

**Comment by Shadowlight213** [comment]
:+1:

**Comment by Bawhoppen** [comment]
0/10 don't ruin beach it was best away mission you cheeklord

**Comment by MMMiracles** [comment]
but i made it bigger AND less shit.

also more coconuts than the original so therefore its already 10x better.

**Comment by Bawhoppen** [comment]
>less shit

you made it quim-tier

**Comment by MMMiracles** [comment]
it was a box with sand and water inside it with crabs THAT ISNT A BEACH.

**Comment by KorPhaeron** [comment]
Add duck mobs that throw you across the map on contact

**Comment by Bawhoppen** [comment]
@KorPhaeron i have nightmares about that level still

**Comment by KorPhaeron** [comment]
Add a big watermelon you have to push but duck mobs destroy it

**Comment by RemieRichards** [comment]
Just don't do nintendo's mistake and add a "Wigger" (Wiggler) :P 

Nice map :+1:

**Comment by WJohn** [comment]
While the away mission could be improved immensely in so many more ways, this *is* better than what we had. Eh, slowly but surely getting better, at least it's receiving SOME love.

**Comment by MMMiracles** [comment]
Some suggestions to add would be nice while the PR is still up. I just tried to make it more than a metal box with sand and water.

**Comment by Dorsisdwarf** [comment]
Make the bartender have an exile implant so he cant fuck off from the job

Co

**Pull request merged**
