### PR TITLE
Finnaly puts me in the power

### PR DESCRIPTION
**Pull request by jughu**
of my own client

### CODE REVIEW

**Comment by jughu** [comment]
@AnturK client side though??? its easier for me to refork and test unless you want me to not test 🤔

**Comment by praisenarsie** [comment]
host via dreamdaemon ya idiot

**Comment by AnturK** [comment]
Client side what, this is empty PR, you're free to add yourself when you have some content to contribute. Besides localhost autoadmin exists.

**Comment by jughu** [comment]
I shall return you will regret this day 25 october 2017

**Pull request closed without merging**
