### PR TITLE
Warden access for gulag machine

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
i gulagd pls nerf

Warping someone into LAVA HELL should require the say so of the guys responsible for running the brig, not any random officer/detective removing people for twenty minutes over being sent smiley faces via PDA

### CODE REVIEW

**Comment by kevinz000** [comment]
REMOVE NOT IMPROVE

**Comment by francinum** [comment]
Sec can gulag manually. this simply makes it more annoying to gulag people.

**Comment by Cheridan** [comment]
Detective already can't access it though

**Comment by AlexCrimson** [comment]
I believe this was suggested in the feedback thread, but would it not be better to have point limits for certain ID levels? So for example a normal Sec officer can only gulag someone for a max of say 200 points, where a Warden would have 500, and HoS/Captains get no point restriction?

**Comment by KorPhaeron** [comment]
@AlexCrimson 

That'd require more than one line of code

**Comment by optimumtact** [comment]
It's about time.

**Comment by ExcessiveUseOfCobblestone** [comment]
Warden's Brig, Warden's Rule.

A Policy all should live by.

**Comment by Dorsisdwarf** [comment]
I like the idea of the Warden having use.

**Pull request merged**
