### PR TITLE
Removes stun gloves

### PR DESCRIPTION
**Pull request by Iamgoofball**
from ninjas

we must retake the holy code from the stun glove infidels
:cl: Iamgoofball
balance: Removes stun gloves from Ninjas.
/:cl:

ninjas have literal teleports behind u nothin personell kid and free invisibility and are damn near impossible to kill, they do not need stun gloves

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
you buy null crates to fight the ninja

**Comment by Dorsisdwarf** [comment]
Stungloves are anethema because theyre undetectable stuns that anyone could have at any time, not because theyre gloves that stun you

**Comment by Iamgoofball** [comment]
its both actually

**Comment by WJohn** [comment]
Not only undetectable, but also undisarmable.

**Comment by ma44** [comment]
Alternatively make the stun gloves also electrocute_act the target with siemens_coeff so wearing insulated gloves doesn't lead to stun haven.

**Comment by ma44** [comment]
Also to be fair the only way you can use said gloves is if you have them on as well as a suit, which having a ninja suit on is already pretty obvious to the eye.

**Comment by Iamgoofball** [comment]
what part of free invisibility do you not understand

**Comment by PKPenguin321** [comment]
iNvIsIbIlItY
transparency

**Comment by Shadowflame909** [comment]
If u remove da stun gloves were left with the esword katana. WTF goof is promoting murderbone plz delete pr thank u

**Comment by YakumoChen** [comment]
Also goof is trying to get free gbp with the fix tag when he's just removing stuff. Needs balance tag too

**Comment by Kromgar** [comment]
It's ninja. Aren't space ninjas supposed to be op?

**Comment by Shadowflame909** [comment]
I didn't even know this was a feature. I usually shurikened people and put them into soft crit to send them. Shock gloves are needed to do your kidnapping objective with the net. Not a smart removal.

**Comment by Iamgoofball** [comment]
listen if you can't figure out restraining someone with infinite teleportation, free invisibility, and the other ninja suit benefits, that's your problem

**Comment by Shadowflame909** [comment]
For one, I would like an actual reason why, preferring an in game argument on how the equivalent of a stun baton that effects all the powers of a ninja, can be abused. Secondly, the  invisibility isn't invisibility at all it's the genetics cloak of shadows. It just makes you transparent. It also drains at an alarming rate and has a cool down. Any other items like your e-sword or your shurikens aren't very good for netting people alive. Lastly, your reasons for this Nerf is that you believe stun gloves should be removed entirely, but goof you fool the gloves literally are used to gain power in the ninja suit. Without it, the suit doesn't function. So please play as the ninja, and play in general before making moronic antagonist breaking PRS.

**Comment by YakumoChen** [comment]
well for one ninjas don't have storage space for anything like cuffs or stuns, that's why all their abilities are actions and powers

**Comment by Supermichael777** [comment]
Remove the rest of ninja while your at it, literaly everyone thinks stealth antags are garbage.

**Comment by Shadowflame909** [comment]
>There's demand for IAA, Morphs, Abductors, Blood Brothers. 

Yeah, I think 99 percent of people disagree with you and we want more stealth antagonists.

**Comment by Anonmare** [comment]
Why don't we just remove the kidnapping objective?

**Comment by Shadowflame909** [comment]
Because it's the only antagonist with a kidnapping objective and it makes it unique from all the others. Think about it, without the abillity to space net and kidnap ANY LIVING MOB. What sets ninjas apart from other antagonists? That's the only skill unique to ninjas.

**Comment by Kromgar** [comment]
You know if the space ninja weeb room gets upgraded to have VR and all that jazz we could add the kidnap objective to normal play. 

Instead of just killing someone.

**Comment by Shadowflame909** [comment]
Yeah, I want my ninjas to kidnap more and murder less. Kidnapping antagonists for the win!

**Comment by ExcessiveUseOfCobblestone** [comment]
I realize ninja is rare but saying it has "invisibility" is just untrue.

**Comment by Kromgar** [comment]
Why does goof always say "Free" whatever thinks something is op? INFINITE TELEPORTATION = Requires Power, Plasma is "FREE MONEY". Invisibility and the stun gloves cost power. Invsibility costs a ton of power.

**Comment by Iamgoofball** [comment]
@kromgar don't fucking pretend power isn't free

Stop pretending resource limits are real

**Comment by Shadowflame909** [comment]
I'm pretty against this because Goof is basically saying "Lol you want to be able to non harmfully detain people? Tough luck you're gonna have to put them into crit and have them die on you if you want to take them to spess ninja land" This pr is the encourager of murderbone!

**Comment by davethwave** [comment]
By the time a ninja is able to spawn(1 hour) sec has their superweapons, genetics have superpowers, at least 1-2 medical staff has a rapid syringe gun ready and filled. And so on and so forth.

**Comment by SpinnerMaster** [comment]
i ded pls nerf

**Comment by PKPenguin321** [comment]
>don't fucking pretend power isn't free

It pretty much is, but the ninja's *suit power* can only hold so much and takes significant time to charge. It's definitely not free by any means in that regard

**Comment by ExcessiveUseOfCobblestone** [comment]
If resource limits and time limits don't work then what exactly is stopping people from getting the best gear every round goof?

**Comment by Iamgoofball** [comment]
nothing is

**Comment by YakumoChen** [comment]
Yes this is why I am definitely able to build three AIs one humaned to science, a phazon mech for each of them, and one for myself, by the 20 minute mark,  consistently, every single round, while being a Xenoling

**Comment by YakumoChen** [comment]
And also a null crate with 30 bicycles

**Comment by ExcessiveUseOfCobblestone** [comment]
I miss bicycles no one buys them anymore because we ruined all the money makers lol

**Comment by improvedname** [comment]
People gettinh their cock over 1 thing that always will scream i have stungloves

**Comment by improvedname** [comment]
Stungloves were a issue before because everyone had those fine yellow gloves that wasnt detectable or disarmable thats not the case with ninja

**Comment by Shadowflame909** [comment]
Yeah, as a space ninja you actually have to wait around a power charger. Usually the one in robotics and just wait till it reaches 100 percent whilst saying "Hi." to everyone who walks past you. I uh, had to fend off alot of sec officers in that time period with emps and adrenals.

**Comment by Kromgar** [comment]
Goof has no idea how ninjas work clearly

**Comment by Dorsisdwarf** [comment]
Removed the fix label since I only just noticed that the poor dumb bot cant detect goof memes

**Comment by Arianya** [comment]
Perhaps instead of worrying about power or cargo credits being "free", we should worry about the real non-existent resource limit.

Namely how goof still has GBP to open PRs. Wasn't the intent that opening a PR, merge or close, would deduct GBP?

**Comment by YakumoChen** [comment]
Holy shit its true, just go through his merged PRs and almost all of them are some feature or tweak or balance change but he uses the fix tag

LITERALLY how does he keep getting away with this

**Comment by ExcessiveUseOfCobblestone** [comment]
> Thinking GBP matters to literally anyone.

**Comment by Arianya** [comment]
@ExcessiveUseOfCobblestone don't fucking pretend GBP isn't free

Stop pretending PR limits are real

**Comment by Iamgoofball** [comment]
you guys know the pr deposit didn't get merged right

Stop whining about people having different balance opinions than you.

Also stop shit posting on my pull requests or I will get Github involved for harassment.

**Comment by Shadowflame909** [comment]
Who's shitposting, these are all valid complaints

**Comment by Iamgoofball** [comment]
I dunno the 5 posts above mine rambling about a pr deposit thing that didn't get merged

**Comment by AdamElTablawy** [comment]
ninjas are kinda wimpy altogether atm though

their teleport got nerfed to shit, throwing stars are still good i guess, they can't carry extra items, their one stun resist fucks them over, and now with that they can't print tons of cells from R&D they're almost always on super low power because recharging cells takes forever especially the good ones and cells are the only good source of power

and to top it off their invisibility isn't even good anymore, they're just mildly transparent, literally alien sentinels are harder to see

ya don't need to remove their stun melee as well, especially since the stun takes a bit to kick in, costs power, and doesn't affect people with insulated gloves

**Comment by Arianya** [comment]
I do not believe this change is rooted in good statistics or an understanding of the game mode. I would disagree with its implementation on the basis that the pull creator does not frequently play and thus would not have a good idea of the implications of this change, especially with regards to a rare random event side antagonist.

**Comment by Kromgar** [comment]
Yeah a rare solo antagonist that spawns an hour into the round. Usually hour + antagonists are meant to end rounds anyway

**Comment by optimumtact** [comment]
it's not a problem, if you see a space ninja they have a very distinct look, you can expect to know they have stungloves.

stungloves were a problem when accessible to every role with no tell.

**Pull request closed without merging**
