### PR TITLE
Morgue fix and redecoration

### PR DESCRIPTION
**Pull request by Justice12354**
## About The Pull Request
- Tramstation's Morgue was annoyingly broken (the disposals chute was not linked to the disposals net). I fixed that! :D
- I also decided to change the Coroner's Office a bit up, because it makes no sense for the Surgery Tools and the Organ Storage to be two miles away from the Operating Table.
- I've also added a table clock to every Morgue because it's a pretty cool ambience sound (in exchange for that, I removed it from the Coroner's heirloom list).
- Changed the position of Northstar's Morgue Trays to have more without having to break down the walls.
- Changed a bit the Deltastation Morgue's colors to match the Coroner's black and white.

Deltastation:
image
Metastation:
image
NorthStar:
image
Tramstation:
image
Icebox:
image
## Why It's Good For The Game
Tram's Morgue's disposals leading to nothing was miserable. The table clock gives a nice ticking sound. Surgery tools shouldn't be 2 miles away from the table. The Skeleton now looks at you while you perform autopsies (except on Meta, fuck Meta).
## Changelog
:cl:
add: The Morgue now always has a table clock
del: The Coroner can no longer have a table clock as an heirloom
qol: The Morgue now has the surgery tools, operating table, and organ storage all near each other
fix: The Tramstation's Morgue now has a functional disposals chute
/:cl:

### CODE REVIEW

**Comment by Crushtoe** [comment]
There's two standing PRs already to address tram morgue: #75856 #75657

**Comment by Justice12354** [comment]
Maintainers, can you please remove the removal and fix tags from the PR? While I wanted it to be something players see in the changelogs, it isn't anything relevant

**Comment by Justice12354** [comment]
> There's two open PRs already to address tram morgue: #75856 #75657

Oh crap. I didn't see those. Given both #75657 and this will be covering the same while covering other issues, I will be removing the power cable fix from this PR in order to avoid conflicts (even though Idk if any will be caused).

**Comment by EricZilla** [comment]
Since you are already in there, any chance you might rearrange the morgue trays on icebox? Its a real pain in the butt to have to go completely around the entire room just to get to the office.

Usually I just destroy the middle two morgue trays by the end of the shift, but moving the top two or top three up a space would fix it too

**Comment by Justice12354** [comment]
> Since you are already in there, any chance you might rearrange the morgue trays on icebox? Its a real pain in the butt to have to go completely around the entire room just to get to the office.
> 
> Usually I just destroy the middle two morgue trays by the end of the shift, but moving the top two or top three up a space would fix it too

I have opened up a small path in the middle of the trays, as well as moved the disposals unit

**Comment by EricZilla** [comment]
Hell yeah looks greag

**Comment by Justice12354** [comment]
For some reason, two of the files are conflicting a lot. Since all problems that were getting fixed in this PR have already been fixed, I'll close this and later try to figure this out.

**Comment by EricZilla** [comment]
Might be better to do each morgue one by one to minimize issues popping up if you do wanna redecorate

**Pull request closed without merging**
