### PR TITLE
[GOD BLESS AMERICA] The Second Amendment Update

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
https://www.youtube.com/watch?v=U1mlCPMYtPk

## Why It's Good For The Game
godbless

## Changelog
:cl:
add: O say can you see, by the dawn's early light,
add: What so proudly we hailed at the twilight's last gleaming,
del: Whose broad stripes and bright stars through the perilous fight,
tweak: O'er the ramparts we watched, were so gallantly streaming?
balance: And the rocket's red glare, the bombs bursting in air,
fix: Gave proof through the night that our flag was still there;
soundadd: O say does that star-spangled banner yet wave
sounddel: O'er the land of the free and the home of the brave?
imageadd: On the shore dimly seen through the mists of the deep,
imagedel: Where the foe's haughty host in dread silence reposes,
spellcheck: What is that which the breeze, o'er the towering steep,
code: As it fitfully blows, half conceals, half discloses?
refactor: Now it catches the gleam of the morning's first beam,
config: In full glory reflected now shines in the stream:
admin: 'Tis the star-spangled banner, O long may it wave
server: O'er the land of the free and the home of the brave.
add: And where is that band who so vauntingly swore
add: That the havoc of war and the battle's confusion,
del: A home and a country, should leave us no more?
tweak: Their blood has washed out their foul footsteps' pollution.
balance: No refuge could save the hireling and slave
fix: From the terror of flight, or the gloom of the grave:
soundadd: And the star-spangled banner in triumph doth wave,
sounddel: O'er the land of the free and the home of the brave.
imageadd: O thus be it ever, when freemen shall stand
imagedel: Between their loved homes and the war's desolation.
spellcheck: Blest with vict'ry and peace, may the Heav'n rescued land
code: Praise the Power that hath made and preserved us a nation!
refactor: Then conquer we must, when our cause it is just,
config: And this be our motto: 'In God is our trust.'
admin: And the star-spangled banner in triumph shall wave
server: O'er the land of the free and the home of the brave!
/:cl:

### CODE REVIEW

**Comment by WarlockD** [comment]
Could you give the clown all the ammo?  Give him something to do and or run from.

**Comment by EgorDinamit** [comment]
Add bulldog ammo to autolathe too.

**Comment by ATH1909** [comment]
don't catch you slippin' now

**Comment by Qustinnus** [comment]
bit too much for april fools, this is the same as Kor's sniper rifle thing and it was funny for about 2 nanoseconds

**Comment by Fikou** [comment]
> bit too much for april fools, this is the same as Kor's sniper rifle thing and it was funny for about 2 nanoseconds

solution: start everyone with a deep fried gun to multiply AMERICA

**Comment by zxaber** [comment]
AMERICA

(Probably could have saved time by just sticking it into the internals box.)

**Comment by cacogen** [comment]
isn't there a vendor you can just throw in the bar or something

**Comment by CRITAWAKETS** [comment]
why only 1 gun and why is it the bulldog, real americans use a variety of guns like AR-15

**Comment by zxaber** [comment]
Y'know, that's a good point. If it's gonna be any one gun, it really ought to be the 1911.

**Comment by PKPenguin321** [comment]
🇺🇸 🇺🇸 🇺🇸 FREEDOM 🇺🇸 AINT 🇺🇸 FREE 🇺🇸 BROTHER 🇺🇸 🇺🇸 🇺🇸

**Comment by EOBGames** [comment]
> Y'know, that's a good point. If it's gonna be any one gun, it really ought to be the 1911.

This is a good point, and I would now like to issue an official apology to our American Overlords. _Please don't shoot me._

**Pull request closed without merging**
