### PR TITLE
Reinforcing the mining hardsuit now upgrades its sprites

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

mining hardsuit icons change if you reinforce it with goliath plates
image
image with the updated cool shoulderpads and inventory sprites
image

## Why It's Good For The Game

nice visual change

## Changelog
:cl: Fikou, Kryson, aceedex from /vg/
imageadd: reinforcing the mining hardsuit with goliath hide now makes the sprite cooler
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
NOOOOOO MERGE CONFLICT

**Comment by TemporalOroboros** [comment]
That looks amazing. I am slightly disappointed it's restricted to the hardsuit though.

**Comment by ATH1909** [comment]
this for the normal mining suit when???

**Comment by Fikou** [comment]
> this for the normal mining suit (and mechs) when???

it already exists for mechs
when you sprite it

**Review by Twaticus — APPROVED** [review]

**Comment by kopoba** [comment]
at first i was thinking im looking on sindi suit =\

**Comment by bluetshirtguy** [comment]
daaamn that helmet looks good

**Comment by SmArtKar** [comment]
That looks sick as fuck. Now we need the same stuff for suits

**Comment by D4C-420** [comment]
this looks good too bad the thing is useless on lava land.

**Comment by maxymax13** [comment]
top 10 ways to get immediately bodied when going back to the station: wear what to the average spaceman looks like a syndie suit with a blue helmet, at least until they shift click your horizontal sprite

**Comment by Jared-Fogle** [comment]
people on bagil see syndie hardsuits and just automatically assume you either killed a traitor or got back from the gateway

you get "based" m ore than you do death

**Pull request merged**
