### PR TITLE
Bespoke elements no longer create separate instances when supplied with lists with the same contents

### PR DESCRIPTION
**Pull request by ghost**
Thanks to Rohesie for most of the logic for this.

This allows us to supply bespoke elements with lists without having to do weird methods of preventing them from creating new instances.

As an example, in the old system if you had an element that drops loot on death you'd do

AddElement(/datum/element/death_loot_dropper, list(/obj/item/bones = 1))

every time you do this, it would create a new element because each time the list is its own, unique object.

Now, it would only create one assuming the list has the same contents in the same order (important to keep in mind). This prevents 500 mobs that would for example all spawn the same items from making 500 element instances.

this is required for some of the code basic mobs has, and also allows us to refactor some older features that rely on GLOB lists for similar behavior (Like swabbing for cytology)

### CODE REVIEW

**Comment by Mothblocks** [comment]
This looks like it only works on dicts, since looping over a flat list gives values, not indices.

Detecting this is absurdly annoying in BYOND, so might want to leave a warning somewhere for it?

**Comment by AMonkeyThatCodes** [comment]
i tested on both, both worked.

**Comment by Mothblocks** [comment]
NVM, didn't notice it spits values as well.

**Comment by LemonInTheDark** [comment]
This seems like it would add a not insignificant amount of overhead, how does it effect initialization times?

**Comment by AMonkeyThatCodes** [comment]
not at all because nothing really utilizes it yet. I can't imagine it'll be that bad because most elements don't have such extravagant lists.

**Comment by AMonkeyThatCodes** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
I'm not sure I agree increasing the overhead cost of attaching bespoke elements is worth the memory savings here. Could you profile how much attach cost is increasing when the arguments contain a list?

> how does it effect initialization times?

Init times isn't the concern, normally I would advise attaching and detaching elements frequently if you want to toggle behaviors but this would potentially change that

**Comment by AMonkeyThatCodes** [comment]
https://www.youtube.com/watch?v=CDXQBgnEVN4

**Comment by AMonkeyThatCodes** [comment]
might pick this up later

**Pull request closed without merging**
