### PR TITLE
Increases the genetic diversity of the station.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: The horde of hulk-dwarf-telekinetic-xray vision spacemen rampaging through the game disrupting all combat balance should be reduced.
/:cl:

This kills the hulk-dwarf-tk-xray.
untitled

### CODE REVIEW

**Comment by AnonymousNow** [comment]
But where's Healing Hands, though?

**Comment by Iamgoofball** [comment]
We still have that?

**Comment by AlchemicalGitHub** [comment]
Honestly this would be a change for the better.

**Comment by AnonymousNow** [comment]
Honestly, we should probably keep all those powers, but mix them up so that they can't all manifest in one round (unless you're ridiculously lucky), and instead five random powers from a pool of, say, ten, are available every shift.

**Comment by Iamgoofball** [comment]
That's what this PR does.

**Comment by AnonymousNow** [comment]
I was thinking of the five extra powers bit.

**Comment by Iamgoofball** [comment]
Why was this closed?

**Comment by optimumtact** [comment]
because we're not interested in this change thank you, these were removed by kor originally for being boring and annoying

**Comment by Iamgoofball** [comment]
I think we should trial run enabling them again since it's been a year.

**Comment by PKPenguin321** [comment]
Why? We already know that they were boring

**Comment by Iamgoofball** [comment]
people thought gang was fun a year ago

**Comment by PKPenguin321** [comment]
People pretty much never thought these were fun

**Pull request closed without merging**
