### PR TITLE
Janitor rework

### PR DESCRIPTION
**Pull request by chesse20**
[Changelogs]: 
:cl: optional name here
add: Added some mops and a lasergun to janitor closet
tweak: buffed the janitor cart
tweak: janitor gets heals from eating rats
code: janitor datum
/:cl:

[why]: # janitor rework by chesse20

suggested by [reddit](https://reddit.com/r/SS13/comments/8nb6w4/janitor_reeeework_ideas/)

this adds five new changes to the game

## Janitors Can Now Eat Mice For Full Health

janitors were often put in dangerous places and they got hurt alot so now you can eat mice and get a lot of health if your a janitor

## Laser Guns in Janidrobes

its contraband so you have to hack and hope an  assistant doesnt take it first

## New Janitor Datum

i added janitor datums

## Buffed Janicart Speed

it moved too slow

## Buffed Janitorial Crates

they have more mops people kept losing them

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
🍆

**Comment by outbools** [comment]
c*der (((humor)))

**Comment by moonheart08** [comment]
honk

**Comment by CitrusGender** [comment]
what does he need all those mops for

**Comment by fludd12** [comment]
The tears of the fallen.

**Comment by kevinz000** [comment]
gitban when

**Pull request closed without merging**
