### PR TITLE
Adds some very fancy tables

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan, Ausops
rscadd: Added some very fancy tables, constructed by adding carpet tiles to a standard table frame.
/:cl:

this is really fancy
Original sprite credit @Ausops with some edits to make it usable

Fixes a bunch of checks that weren't making sure the stack of whatever you were using to make the table with still existed.

### CODE REVIEW

**Comment by DfourC** [comment]
I thought carpet was how you made poker tables.

**Comment by ChangelingRain** [comment]
Poker tables require a wood table frame, these require a normal table frame.

**Comment by GunHog** [comment]
### [@kevinz000 intensifies]

**Comment by GunHog** [comment]
Chapel needs those.

**Comment by Niknakflak** [comment]
Finally, teasing these images for days before you made this PR
damn Joan

**Comment by KorPhaeron** [comment]
You should replace the shitty skeletal minibar that is actually racks in the lizard den with this table

**Comment by kevinz000** [comment]
O_o

**Comment by WJohn** [comment]
:+1:

**Pull request merged**
