### PR TITLE
tgui-next ntos card console

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

A PR now several weeks in the making that spiraled ridiculously out of control for something not many even use.
What else is new in NTOS hell?
~~I spent several days doing nothing but playing escape from tarkov so this took longer than expected~~ I valiantly spent all night and day working on this, and barely finished it before The Deadline
the card ntos program was split into three programs, manifest, job management, and id card modification. It didn't make much sense for them all to be the same program imo, and made the project a bit more managable.

ID Card modification:
image
image
Job management:
image
Crew Manifest:
image

Airlock electronics saw some improvements as well since it uses this new access control section as well.

Yet again some new functionality and improvements to core components. Buttons now have an "altSelected" feature where instead of changing the color it adds a small white marker, among some other things.

There were a couple of small changes in inconsequential ways in other places, and datacore was refactored a tiny bit. Probably some other stuff I don't remember.

I would replace the old card console with a modular computer right now, but I know a few people actually use this program and want a bit of time to iron out bugs and inconsistencies before replacing the main job console with it.

## Changelog
:cl:
add: tgui-next NTOS card console, job manager, and crew manifest
tweak: airlock electronics interface is a little fancier

/:cl:

### CODE REVIEW

**Comment by SpinnerMaster** [comment]
this is blessed, thank you

**Comment by Arturlang** [comment]
Why not give something similar for the ID console?

**Comment by Tharcoonvagh** [comment]
You can't prioritise jobs

**Comment by cacogen** [comment]
Looks really good. I use this all the time as HoP, and the current one is shittily laid out.

**Comment by actioninja** [comment]
> You can't prioritise jobs

knew I was forgetting something on that UI

**Comment by TheVekter** [comment]
I... didn't even know you could modify IDs from NTOS devices.

**Review by stylemistake — DISMISSED** [review]

**Comment by ShizCalev** [comment]
conflict

**Comment by 81Denton** [comment]
@stylemistake I'm unable to open your review, is this good to go?

**Pull request merged**
