### PR TITLE
Adds dmifonts

### PR DESCRIPTION
**Pull request by CorruptComputer**
This turns fonts into .dmi files.

### CODE REVIEW

**Comment by astralenigma** [comment]
Dumb questions: what do dmifonts do and do we really need them to do that?

**Comment by CorruptComputer** [comment]
It could be used to put words on maps.

**Comment by RemieRichards** [comment]
@CorruptComputer we can do that anyway.
it's called "Maptext", an object can have any text (within certain physical constraints also controlled by variables) written on it, and it sticks to the object if it moves.
It's how Neerti did the chess event ages ago.

But yes it works on turfs, without them being the same size as a turf (which would look quite odd).

**Comment by CorruptComputer** [comment]
Oh, I wasn't here for that, so I had no idea. Want me to just close this?

**Comment by RemieRichards** [comment]
Well, it depends on if this system is better or worse than maptext.
Maptext doesn't allow for giant (turf size) text like I assume this does, so maybe it's not useless?

**Comment by CorruptComputer** [comment]
Yeah, this does. You can actually choose the font, font size, underline, bold and italics.

**Comment by GunHog** [comment]
Could this lead to tooltips, where I could hover my mouse over something to get info on it? For example, I can get quick info on an airlock if I am the AI, or security records for a SecHUD user. I could even complete my dream of adding Diagnostic HUDs, ever since the passive HUD update made it too complicated to do so with icons.

**Comment by RemieRichards** [comment]
Oh well, I did forget, Maptext, being pure actual string text, has HTML and CSS support, so sizing and colouring underlining etc. ARE actually covered.

**Comment by CorruptComputer** [comment]
@GunHog I guess you could do that, it just makes an entire font set into a .dmi file that you can do anything you want with.

**Comment by CorruptComputer** [comment]
Here's some screenshots:

http://i.gyazo.com/7470dd4f7e13d1a86fa8d23db13f977e.png
http://i.gyazo.com/17013b798b2848ed3afd3fdf16739ed8.png

**Comment by RemieRichards** [comment]
@GunHog We can't do Tooltips.

MouseEntered()
MouseExited()
Both procs point out in their DM reference:
"Don't define this unless you need it, because it generates extra communication that is otherwise avoided. Defining it on only the objects that require it reduces overhead. "

We'd HAVE to place it on /atom, which would cause a MULTITUDE of MouseEntered() and MouseExited() calls.

**Comment by CorruptComputer** [comment]
Also I just thought I should point out, I didn't make this, nor do I know who did.

**Comment by RemieRichards** [comment]
@CorruptComputer LummoxJr, one of the Byond Devs did.

**Comment by CorruptComputer** [comment]
Ok thanks, I just found this in a zip when I was looking for a way to fix dream maker crashing every time I save a map.

**Comment by Iamgoofball** [comment]
Now we can add the runescape font and make it show above people's heads. 

:+1:

**Comment by astralenigma** [comment]
Are you saying that soon we will be able to free ourselves from the shackles of the chatbox window?

**Comment by CorruptComputer** [comment]
It is possible, but the amount of code would probably be ridiculous.

**Comment by CorruptComputer** [comment]
This could be used to do: https://github.com/tgstation/-tg-station/issues/9577#issuecomment-104151601

**Comment by Razharas** [comment]
No idea why we need this, but we have regex that none uses anyway so why the hell not

**Pull request merged**
