### PR TITLE
[WIP] Removes Beepsky's infinite stunlock

### PR DESCRIPTION
**Pull request by cacogen**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: cacogen
balance: Securitrons now drag people they've detained instead of chainstunning them
balance: Securitrons (Beepsky) now need power to stun, but charge themselves constantly
balance: Securitron cells can be upgraded, and max out at about 40 stuns
balance: Securitrons now require a power cell to build, add it as the second to last step
balance: Cells can't be used as weapons any more (because it's cleaner codewise), but they only did 5 damage
balance: If a securitron runs out of power, it hibernates until it can stun again (which takes about 10 seconds)
add: Adding plasma to a securitron's power cell will result in the robot detonating on stunning someone
add: Securitrons will tell you what area they've hibernated in over the radio
add: Securitrons with crap cells will not try to stun anyone (because they can't), and report the problem over the radio
add: Securitrons can be silenced to prevent them from reporting low power or bad cells (in addition to arrests)
add: If you have access bots will stop patrolling when you open their window, making it easier to interact (don't forget to turn auto patrol back on if desired)
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

There shouldn't be anything in the game that left to its own devices chainstuns permanently. It's lazy and unfair on the player being chainstunned. Securitrons are vulnerable to groups of people, but not to one person when they're stuck in a room with one set to detain. It's a niche issue, but detain is there to hold someone for collection, not as a makeshift alternative to the permabrig.

### CODE REVIEW

**Comment by obscolene** [comment]
add: If you have access, bots will stop patrolling when you open their window, making it easier to interact (don't forget to turn auto patrol back on after you're finished, if desired)

if this gets closed please make this into its own PR thanks

**Comment by MrDoomBringer** [comment]
Injecting plasma into the beepsky cell should make it fucking explode when it tries to stun people

god please

**Comment by MrDoomBringer** [comment]
yeah i would atomize that last part

**Comment by WJohn** [comment]
tbh i think having beepsky go to a charging port of some kind would be better instead of just magically regaining power all by itself.

i guess having the precedent for power supplies in bots is a step in the right direction, so that could be done at a later date.

**Comment by Barhandar** [comment]
This is clearly ided from forgetting about the STUNBATON OF **THE LAW** that is Armsky, but it might make xenobio actually fucking distribute their yellow cells so it balances out.
>tbh i think having beepsky go to a charging port of some kind would be better instead of just magically regaining power all by itself.

Map changes required, just make it siphon power out of the area it's in (and have beepsky in space have INFINITE CHARGE SO YOU CANNOT ESCAPE THE STUNBATON OF **THE LAW**)

**Comment by Therapist1** [comment]
If you had the interface unlocked, why would you put in a small cell instead of just, say, flipping the off switch?

**Comment by Barhandar** [comment]
Because you want to pretend Beepsky is still active, and prevent easy fix by anyone with access noticing he's not doing anything.

**Comment by Kagus** [comment]
Doesn't the construction of a securitron require a complete stunbaton? As in, one that's had a power cell inserted into it? Also, just because a 'tron has 10 stuns charged and ready does not mean you'll get 100 seconds of stuntime, as they don't always chain them perfectly. There will be a lot of "wasted" stuns where the bot will whack them while they're already down.

It's an interesting change, but it's a pretty massive nerf (when taking into effect the downtime for recharges) that I'm not sure securitrons strictly need. I'm not gonna say "git gud", because I've definitely been tagged and bagged by Beepsky on a number of occasions, but they're still not exactly the most threatening critters to begin with.

---
So, when do we get functionality for Beepsky where "detain" function will make him grab a handcuffed perp and drag them around on patrol with him?

**Comment by kevinz000** [comment]
The definition of I ded

**Comment by Iamgoofball** [comment]
this is stupid 👎 beepsky being a good cop is ss13 history

**Comment by ExcessiveUseOfCobblestone** [comment]
@kevinz000 you have to be alive to be chainstunned, checkmate :^)

**Comment by ishitbyabullet** [comment]
Yeah, you're basically making Beepsky into shit. It's not like you can make sentient beepskies and they're just ruining ss13. You need admins or the wizard to summon events for that shit.

Beepsky/Armsky is a simplemob which can be easily killed by 2-3 people grouping up on it at once or just throwing shit at it. Armsky is also, most of the time, awful since it feels random on whether or not it will even arrest you if you're in the armory. You can even kite it or just shoot at it in worst case scenario.

Did Armsky ruin your murderbone or something?

**Comment by cacogen** [comment]
Allowing it to chainstun people for six minutes is turning it into shit?

**Comment by MrDoomBringer** [comment]
holy shit 22 downthumbs are you guys even reading the pr

**Comment by BebeYoshi** [comment]
How this affects sentient securitrons? Askin for a friend hehe

**Comment by ExcessiveUseOfCobblestone** [comment]
@BebeYoshi this should only affect AI interactions unless i missed a line somewhere. Can you post which line gives you concern?

**Comment by sagattyy** [comment]
dude don't touch beepsky

**Comment by ishitbyabullet** [comment]
@ExcessiveUseOfCobblestone All/most stations also have permabrig cells which can be locked down with blast doors or bolts, I think. The only escape is someone breaking you out instead of you breaking a window yourself. It would be the same as if the windows were lockdown.

@MrDoomBringer yes, beepsky can recharge after ten stun hits so he's only kinda shit until _Jesus Christ_ upgrades him because no one upgrades bots or minor stuff most of the time. They can also be made to no longer report arrests so emagged beepskies could be even more of a meme in theory.

You may think my post of me saying 'you're making beepsky into shit lol did armsky ruin your murderbone lol' is a shitty argument and you therefore dislike it however I imagine the reason most of us, including me, truly hate this PR is for one simple reason:

**it's funny as fuck dude lol**

**Comment by epochayur** [comment]
i-it's tradition, guys

2kzlrcmlwo1q0-ew6nwhhjpv6crljfos6aysssfshak

**Comment by ishitbyabullet** [comment]
@epochayur unironically that.

Doesn't matter if the people think 'but it's better when it's able to stunlock' unless an overwhelming number of people agreed, though. It's up to the maintainers since this is a balance change on something that is objectively OP.

I still think armsky stunlocking is funny as fuck however.

**Comment by PKPenguin321** [comment]
@epochayur OLD BAD
NEW GOOD

**Comment by MrDoomBringer** [comment]
@ishitbyabullet ez solution; armsky is a grizzled bot powered by an RTG and doesn't need fancy cells. As such he never runs out of power

**Comment by Kagus** [comment]
I mean, he's technically powered by a potato battery and a shot of whiskey. The clash between the energized proto-vodka and the Space American bourbon mimics the eternal conflict between East and West, powering a political turmoil turbine in perpetuity. Due to constant exposure to the broad-spectrum legislative radiation from this engine, Beepsky embodies both the American tendency for overzealous physical policing, and the Russian disdain for due process. Together, these two halves come together to form the ultimate enforcement officer, meting out even-handed justice while constantly at odds with itself.

**Comment by MrDoomBringer** [comment]
>energized proto-vodka

my sides

**Comment by ExcessiveUseOfCobblestone** [comment]
@ishitbyabullet It's meant to temporarily secure a prisoner so they won't mess with you while you put someone else in, using it to permatrap is shit and I will happily use my "godly-powers" to open the door assuming the AI doesn't when asked.

**Pull request closed without merging**
