### PR TITLE
Add changelogs back to the beginning of recorded changelogs in the repo

### PR DESCRIPTION
**Pull request by optimumtact**
These were generated by writing parsing code for the original changelog
html data in archivedchangelog.html

You can see it here if you want, although it's horrible code
https://github.com/optimumtact/-tg-station/blob/changelogjammin/html/ss13_genchangelog.py

This gives us the ability to generate if we want, the history of records
back to 2009, as an unbroken html page

I had to make some editorial decisions about how the authors of these
old changelogs were tracked as it was not always clear

You can see this here https://www.oranges.net.nz/~oranges/new_changelog.html

note this is from when I did the work in 2016, I just finally got around to pushing this work to master and cleaning up the output

This will merge conflict quickly as the file is touched by the changelog generator script

### CODE REVIEW

**Comment by optimumtact** [comment]
https://www.oranges.net.nz/~oranges/new_changelog.html
here's all the changelogs up to today, as an example

**Comment by MCterra10** [comment]
nudist
thankyou, based oranges

**Comment by cacogen** [comment]
>Ghosts can no longer release the singularity.

there are some gems here

**Comment by RaveRadbury** [comment]
Blessed PR

**Comment by optimumtact** [comment]
it's safe to merge, don’t' be shy

**Comment by Jordie0608** [comment]
Might as well just delete `archivedchangelog.html` along with this.

**Comment by optimumtact** [comment]
well, I still think it has historical value, since the structures are not the same as the changelog

**Comment by Jordie0608** [comment]
Things with historical value belong in the museum of git history, not the codebase.

**Comment by optimumtact** [comment]
well you can make a PR to remove it then you fucking orange headed muppet

**Comment by MCterra10** [comment]
Oh god oh fuck down stream conflicts

**Comment by MCterra10** [comment]
Oh it didn't conflict, git gods be praised

**Comment by Jordie0608** [comment]
idk sounds like effort

**Pull request merged**
