### PR TITLE
Fixes throwing not preventing lava from burning you

### LINKED ISSUE #25858: Jump boots don't protect against lava
On using jump boots to jump over lava I was immediately set on fire - I reproduced this by attempting on a different lava river. I was told this was not intended behaviour ( did not test chasms).

### PR DESCRIPTION
**Pull request by silicons**
Fixes #25858

Before anyone screams balance either fix it or close both the bug report and this PR.

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by vuonojenmustaturska** [comment]
https://github.com/tgstation/tgstation/blob/2fce44610466a9f969d369047368714aa1645d14/code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm#L55

Remove cases like this if you're changing how throwing in general works.

**Comment by QualityVan** [comment]
This exact pr has been closed at least twice because of balance and the ability to throw people out of gulag.

**Comment by vuonojenmustaturska** [comment]
Actually, isn't the whole lava weather immunity literally "being thrown/carried on top of something over lava", since lava_proof is a different flag for walking in it?

**Comment by kevinz000** [comment]
@QualityVan s o c l o s e t h e i s s u e

**Comment by kevinz000** [comment]
lava_proof is an obj flag.

**Comment by QualityVan** [comment]
gimme the ability to close the issue and i'll do it 4 u

**Review by Cyberboss — APPROVED** [review]

**Review by Cyberboss — APPROVED** [review]

**Comment by RandomMarine** [comment]
Or remap lavaland to widen the river.

**Comment by KorPhaeron** [comment]
>This exact pr has been closed at least twice because of balance and the ability to throw people out of gulag.

**Comment by optimumtact** [comment]
that's a no

**Pull request closed without merging**
