### PR TITLE
Abduction Tweaks

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
tweak: Abductors no longer delete their research data when buying new gear.
tweak: The Plasma Gland no longer gibs, but instead causes the abductee to vomit plasma every once in a while.
/:cl:

This means that buying gear won't set you back in your objective.
Another minor thing is that the species gland no longer has an use limit and has the jellyperson race added to the list.

The reason for the plasma gland change is that the abductors were clearly meant to be nonlethal: it's not fun to get a semi-antag objective, only to get randomly gibbed after a few minutes. 
This should probably apply to the bodysnatcher gland as well, but i didn't know what to change it into.

### CODE REVIEW

**Comment by WJohn** [comment]
Does this split the research data into two separate lists, so we can tell at a glance how many we actually have for our objective, versus how many we can spend? That'd probably be optimal.

**Comment by XDTM** [comment]
Yup, points and credits, displayed separately

**Comment by PKPenguin321** [comment]
>tweak: Abductors no longer delete their research data when buying new gear.

Does this mean they can buy infinite gear?

**Comment by RemieRichards** [comment]
@PKPenguin321 you should be able to read code by now, which would answer your question.

**Comment by PKPenguin321** [comment]
I was too lazy

**Comment by XDTM** [comment]
To be precise, anyway, they gain one point and one credit per abduction, and you can spend the credits for gear while the points count towards the objective.

**Comment by AnturK** [comment]
Sure, why not. The original intent of these deadly gland was to discourage "come and take me alien overlords, i need my free grief license" stance but that's less of an issue than expected.

**Comment by WJohn** [comment]
The main problem I see with this left is that there's still nothing to actually BUY. The only stuff you *can* buy is replacement equipment, nothing new that makes your job easier or opens up new options.

**Comment by XDTM** [comment]
I was thinking of adding some buyable equipment once this gets merged.

**Pull request merged**
