### PR TITLE
Makes mimes mute

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Nothing more disgusting than a mime that breaks its vow to shout out traitor names.

### CODE REVIEW

**Comment by Zilenan91** [comment]
:+1:  Mimes go home, Clowns are better jokes

**Comment by Supermichael777** [comment]
so only the thing that was important enough for the vow is said?

**Comment by AlexanderUlanH** [comment]
But they still have the verbs to break the vow of silence?

**Comment by JJRcop** [comment]
@AlexanderUlanH This modifies their DNA and makes them actually mute.

**Comment by daman997** [comment]
remove talking mime :+1:

**Comment by Bawhoppen** [comment]
While I'm against mimes talking, there are special rare occasions where a mime should talk (not for anything simple like saying who killed them)

**Comment by GunHog** [comment]
I do not play mime, but taking a mime player's ability to choose to speak seems awful to me. :-1:

**Comment by KorPhaeron** [comment]
We already took a clowns choice to use guns years ago

**Comment by Saegrimr** [comment]
Clowns can go to the geneticist if he wants to be less funny in times of crisis.
Mimes can go to the geneticist if he wants to be a disgrace to mimes everywhere.

**Comment by Firecage** [comment]
No thanks. This is just silly. If a mime wants to break their silence to out a traitor, so what? It is the traitors fault for being incompetent and not handling the mimes headset. The same with ANY other crewmember.

**Comment by Miauw62** [comment]
:-1:

using guns and speaking are very different things and mimes already get shat on/lynched for talking a lot.
this is very unnecessary.

**Comment by CPTANT** [comment]
:-1: 

Mimes breaking vows often leads to hilarious situations.

**Comment by SweaterKittens** [comment]
:-1: Agreed, keeping your vow of silence should be a badge of honor, not an obligation. If a mime shouts a traitors name, than he has lived, but with a shamefur dispray that brings dishonor to his family. No need to force them to stay mute, especially if they want to do a fun gimmick.

**Comment by Bawhoppen** [comment]
just keep speaking mimes valid and we're good to go

**Comment by freerealestate** [comment]
ok taking player freedom over a personal opinion about how they should play the game is shit and also you didn't remove the ability to break your vow of silence which is now useless unless you've removed the mutation

**Comment by Aranclanos** [comment]
player's choice

**Comment by freerealestate** [comment]
wow we agree on something
we should marry

**Pull request closed without merging**
