### PR TITLE
Allows you to actually repair the cargo shuttle on Icebox 

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Military grade sad trombone, turns out if a turf is planetary, even if it's plated over with a floor tile, it can't be moved with a shuttle. This works around the problem by adding some openspace where the cargo shuttle lands. Now if it blows up, you can actually fix it!
~~If it looks weird, it's because I made sure it wouldn't space the mining base in the process. Hence the little chair nook. Thing.~~

## Why It's Good For The Game
One mistake making a job unfixable and undoable for the rest of the round is wack yo

## Changelog

:cl:
fix: Cargo's shuttle can actually be repaired on Icebox (and won't leave half of the plating you lay behind)
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
can we get a screencap of how it looks now?

**Comment by unit0016** [comment]
> can we get a screencap of how it looks?

Here's what it looks like in-game. Did my best to make it fit in all nice and tidy.
image

**Review by san7890 — COMMENTED** [review]
image

Nitpicking, but this wall (coordinates in bottom left, although I'm sure you know the one) probably should be owned by Cargo in area turfing.

**Comment by unit0016** [comment]
> image
> 
> Nitpicking, but this wall (coordinates in bottom left, although I'm sure you know the one) probably should be owned by Cargo in area turfing.

I was considering it, but the walls by the exterior chapel use the same /area/ - so I decided against it for consistency's sake.

**Comment by Maurukas** [comment]
I've asked @LemonInTheDark to take a look at this and see if there's a better way to do this besides cutting a hole in the map, so DNM for the moment.

I don't have a good enough handle on either shuttle code or planetary atmospherics to understand exactly why this happens.

**Comment by unit0016** [comment]
> I don't have a good enough handle on either shuttle code or planetary atmospherics to understand exactly why this happens.

It's less about atmospherics (var/planetary is actually irrelevant, it just made a good catchall term for the issue) and is more about the baseturf here from my understanding, had similar issues with custom shuttles on bee which is why I was clued into what the hell was happening

**Comment by LemonInTheDark** [comment]
https://github.com/tgstation/tgstation/blob/33e893e113bc7cb0255c84dd6442ace516bf6b54/code/game/area/areas/shuttles.dm#L19-L24

Shuttle code made the assumption that a plating tile would need to be placed before any floor tiles, so it injects the baseturf that marks the plating as "part of the shuttle" there.

The trouble is, since snow tiles are "plating", they ignore this bit of logic.
We can't just pass in the current tile and check for floor tiles there either, since it would break if you put down plating, then floor tiles, we'll effectively have two "shuttle markers" on one turf, which is a recipe for pain (trust me)

The fix is likely something to do with checking for existing shuttle markers, then if there are none between us and the next tile down, and we're an acceptable turf type, mark us as "part of the shuttle".

There's a small downside to this, in that floor tiles could be part of the shuttle with no floor underneath them, which is minorly silly, but I think workable

Will likely look into this myself if none else is interested. 

In general, fixes like this can be a bit of a headache, since at some point we're basically just admitting that a bit of code is broken, and trying to work around it.

~~Imagine if we just didn't let shuttles land on snow anymore~~

**Comment by cacogen** [comment]
Snow shouldn't act as plating. 

You should need to put plating down to build on top of it. It feels tacky and wrong to put floor tiles straight down on snow and causes atmosphere problems when you build on top of it if you need to tile it up to put something underneath the floor.

**Comment by LemonInTheDark** [comment]
image
scope creep claims another life.

**Comment by Maurukas** [comment]
It never ends.

image

**Comment by unit0016** [comment]
Lemon fixed it properly 👍

**Pull request closed without merging**
