### PR TITLE
Makes holy weapons re-nameble

### PR DESCRIPTION
**Pull request by jughu**
THIS IS MY ASCENDED Sord
ITS A SORT THAT HAS ASCENDED FROM ITS PLASTIC FORM INTO ENERGY SORD

:cl: Improvedname
add: You can now put custom name and lore on your holy weapon by using a pen on it!
/:cl:

### CODE REVIEW

**Comment by Supermichael777** [comment]
sO guD

**Comment by Armhulen** [comment]
good

**Comment by Supermichael777** [comment]
bait is probably the most cancerous evolution of anti-sec griff, it both wastes time and distracts from the real round. It goes beyond minor ic crime into self antaging via metaknowledge of hoe to imitate game-modes.

**Comment by jughu** [comment]
maybe we should jUsT mAkE a PoLicY aBoUt BaItInG wItH stUPiD RenAMes

**Comment by BeeSting12** [comment]
or just employ the act like antag, get treated like one. see someone hitting someone else with something that appears to be an esword even on examine? kill them, if they ahelp, i guarantee i will ic issue it

**Comment by Doppeltongue** [comment]
This is going to be used for dick jokes, I just know it.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
