### PR TITLE
lol lets just give you an instant stun that takes someone out of the round and doesn't even kill them so they can ghostrole no fighting back just dead

### PR DESCRIPTION
**Pull request by Iamgoofball**
by the way ninjas are retarded HG was right just SAYIN

### CODE REVIEW

**Comment by sawrge** [comment]
didnt you already make htis pr

**Comment by dannno** [comment]
remove ninja

**Comment by Iamgoofball** [comment]
>remove ninja

**Comment by Kromgar** [comment]
>Ninja only spawns like 50 minutes in

Lets remove it

**Comment by kevinz000** [comment]
dude goofball stop

**Comment by Iamgoofball** [comment]
I'm reopening feature FROZE prs

**Comment by Haevacht** [comment]
There's an actual open function lad.

**Pull request closed without merging**
