### PR TITLE
collectors power scaling

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Add power scaling to rad collectors. Now they have a scaling depending on the amount of plasma in the tank (from 1 to 0), the pressure of the tank (higher pressure = higher gains) and the temperature of the gas inside (lower temperatures = higher gains)
max 60% more power

## Why It's Good For The Game
Add something to do for the engies.

## Changelog
:cl:
add: collectors power scale with the gas temperature/pressure/amount inside the tank
code: snake naming good
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Didn’t we get rid of this on purpose?

**Comment by LemonInTheDark** [comment]
If/when someone attempts to make power matter, this would have to be removed, cause wesoda is right, we've had this before, and it made some sm setups much better then they had any right to be.

**Comment by Ghilker** [comment]
We did? Mmm well i limited the bonus to 60% more power if the gas is in good conditions (high pressure, low temperature) but I could limit to 30% more if needed. Also it makes a debuff over time up to 50% powerloss

**Comment by LemonInTheDark** [comment]
I'm weary of anything that changes the power output of the engine that isn't changing the setup itself frankly, and I don't want to add more work that will need to be cleaned up later

**Comment by Cyprex** [comment]
Yes, we've had this, check git history of the appropriate files to find the commits. I believe it scaled with mols in some way.

**Comment by Ghilker** [comment]
Aight, if not interested feel free to close this

**Comment by LemonInTheDark** [comment]
Alright then

**Pull request closed without merging**
