### PR TITLE
Makes medbay vending machines buildable

### LINKED ISSUE #26763: Nanomed plus cannot be deconstructed or repaired
Since the nanomed isn't considered a constructable vendor, it cant be deconstructed. However, this also means it cannot be repaired. Since everything can break now, we really need a way to fix stuff that can't be rebuilt.

### PR DESCRIPTION
**Pull request by QualityVan**
:cl: QualityVan
add: Cargo can order restocking units for NanoMed vending machines
add: NanoMed vending machines can be build and unbuilt
/:cl:

Adds medical vending refills, pictured below(codersprites ho)
https://puu.sh/vFQuY/64495e04b1.png

Works for both the small ones on walls and the big ones. Big ones need three cartons, the small ones only need one. The circuitboard is just another option on the regular vending circuitboard. Cargo can order three cartons for 2000 points.

The wallmounted vendors will have the issue of staying in the middle of the turf instead of being pixel offset if you make new ones.

Could use sprites for vending refills for:
Dinnerware vendor in the kitchen
PTech PDA vendor that the HoP has
YouTool and Engi-Vend in engineering
SecTech in security
Robotech Deluxe that robotics has
NutriMax and Megaseed Servitor in botany

oh yeah also closes #26763

### CODE REVIEW

**Comment by Bawhoppen** [comment]
the vending refills's code needs an overhaul sometime too

**Comment by FantasticFwoosh** [comment]
I dont see why you couldn't just attach a nanomed like a mechanical fire extinguisher. Craft it as a item then place down, probably involving unscrewing & levering from the wall to remove.

**Comment by BeeSting12** [comment]
Isn't the YouTool refill a balance issue as you can refill it once it's out of insulated gloves for infinite gloves?

**Comment by QualityVan** [comment]
Only if you gave the YouTool refill carts premium charges. If that was set to zero you couldn't restock gloves. That being said, can't cargo order gloves?

**Comment by ExcessiveUseOfCobblestone** [comment]
yes they can and often do

**Pull request merged**
