### PR TITLE
Humans that never had a player controlling them no longer count towards changeling absorption counter

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

If a DNA absorption victim doesn't have a client/mind (i.e. monkey or spawned corpse, most of the time) they no longer count towards the absorption counter / refresh your respec. This affects only one ability, that being bloody spiders which requires you to succ 3 people in order to buy it.

## Why It's Good For The Game

Blood spiders is a potent tool in right hands and I don't think that it should be acquirable by just visiting genetics/xenobiology/virology/cargo for some monkey cubes. This will force antags who want to get a strong ability to interact with the crew a bit more instead of spending first 15 minutes "powering up"

## Changelog
:cl:
balance: Humans that never had a player controlling them no longer count towards changeling absorption counter
/:cl:

### CODE REVIEW

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
> Maybe give chatbox message feedback if this happens? Just so players know why they're not getting any DNA from the absorb.

**Comment by EnterTheJake** [comment]
On one hand this is a pretty big nerf to an already weak antagonist, on the other it allows us to lock power ling abilities to absorptions now that they can't be cheesed.

**Comment by SmArtKar** [comment]
> On one hand this is a pretty big nerf to an already weak antagonist, on the other it allows us to lock power ling abilities to absorptions now that they can't be cheesed.

I don't think that many people actually used this cheese frequently, so I don't think that it'll have huge gameplay impact but I do agree with your second part

**Comment by Iamgoofball** [comment]
I thought we fixed this already, this has to be a regression.

**Comment by EnterTheJake** [comment]
> > On one hand this is a pretty big nerf to an already weak antagonist, on the other it allows us to lock power ling abilities to absorptions now that they can't be cheesed.
> 
> I don't think that many people actually used this cheese frequently, so I don't think that it'll have huge gameplay impact but I do agree with your second part

Oh you sweet summer child.

**Comment by DrAmazing343** [comment]
People use this cheese often but pretty much always to the detriment of the experience. Blood Spiders as an ability is very strong, but hardly ever in a narratively impactful way. I am not only 100% behind this, but really think we ought to in general be trying to balance more around stopping cheese that adds nothing to the game but chaos.

That's not to say that Blood Spiders should be removed, or anything, just that you SHOULD have to invest and create some chaos the Old Fashioned Way before embracing the Real Deal.

**Comment by moocowswag** [comment]
Isnt that what blood spiders were originally locked behind but then got hugboxed into counting mindless bodies too or am i missremembering.

**Pull request merged**
