### PR TITLE
More holosigns for techwebs

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
add: Added more holoprojectors to techwebs (security, engineering and atmos).
/:cl:

I added sec/engi/atmos holoprojectors for the "electromagnetic theory" node.

Edit: I'm leaving out the HUDsunglasses for a different PR.

### CODE REVIEW

**Comment by kevinz000** [comment]
Mass printable flash protection is not a good idea at this point of time.

**Comment by kevinz000** [comment]
Especially if science doesn't get a pair.

**Comment by as334** [comment]
Infinite holofan projectors for atmos/engineering is quite strong. Maybe raise their material requirements somewhat?

**Comment by Barhandar** [comment]
Printable holoprojectors yes pls, the only time I've ever seen atmos projector used were either "I am personally using it" or "someone took both and fucked off into nowhere". While printable sunglasses is way too OP.

Also, isn't electromagnetic theory kinda early? Being able to make more holoprojectors sometime about when you get advanced bluespace (=bag of holding) would be better, I think.

**Comment by PKPenguin321** [comment]
>printable sunglasses is way too OP

In what way

**Comment by 81Denton** [comment]
@as334 What idea do you have for the material cost? Imo 10k metal/2k glass would be better, I totally didn't copy the holoprojector cost (sshh)

**Comment by Barhandar** [comment]
>In what way

Flash protection with no downsides of limited vision (welding gear), slowdown (hardsuits) or interaction necessity (welding eyes) that can be made in bulk.

**Comment by PKPenguin321** [comment]
Ok but how often do you *really* get flashed, especially late into the round when these would become available

**Comment by Anonmare** [comment]
I am against printable, no-downside flash protection personally. Welding gas masks at least require you to activate the protection and suffer a reduction in vision and welding shield eyes require surgery to implant. And flightsuits have a high material cost. 

I would much rather it be that you can combine a HUD and a pair of existing sunglasses to create HUDglasses

**Comment by AlexTheSysop42** [comment]
>more glasses huds
>no nightvis sunglasses (for adv welders)

**Comment by cebutris** [comment]
> nightvis sunglasses

I'm pretty sure the very idea of this is a contradiction. It makes the light darker while also making the dark lighter?

**Comment by Barhandar** [comment]
>I'm pretty sure the very idea of this is a contradiction.

Automatic darkening from flashes while otherwise amplifying/converting light.

**Comment by improvedname** [comment]
People complaining about flash protection just print welding implants lol

**Comment by 81Denton** [comment]
@Anonmare I like your idea. Let me do that instead of printing tomorrow.

**Comment by ma44** [comment]
Flash protection also works as a way of protecting against revolutionary conversions that for some reason don't have stuns (or mutes) to strip off said sunglasses.

@improvedname it's a lot easier to just put on some sunglasses instead of acquiring a friendly person to spend some time doing surgery.

**Comment by improvedname** [comment]
Something you can see.
Vs
Something you can't see

**Comment by 81Denton** [comment]
I'm gonna do what the rabbit suggested and make HUDsunglasses craftable from HUD+sunglasses instead. This PR is now about holoprojectors nobody ever uses.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
