### PR TITLE
Makes the Shaft Miner's Explorer Suit sprite more consistent!

### PR DESCRIPTION
**Pull request by DrAmazing343**
## About The Pull Request
The Explorer Suit's arms looked metal from the front and back, but not the sides. I think the leather arms looks cooler, so I've adapted the armor to look consistently leather on the arms from all sides, now.
Old Explorer Suit:
oldshaftexample
New Explorer Suit:
shaftexample3
shaftexample1
shaftexample2
## Why It's Good For The Game
Sprite consistency is good! It's a bit more subjective whether to make the arms metal or leather, but I think making them metal without fully spriting out some goofy pauldrons that I also don't think would fit. More leather fits the vibe of the suit!
## Changelog
:cl: Jane
image: Central Command has cut funding to the Mining department, resulting in leather sleeves for the Shaft Miner Explorer Suit rather than the metal plates of before.
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
Dunno how to set draft, still gotta test things and figure it out since it's failing to build.

**Comment by DrAmazing343** [comment]
nevermind got help from #coding-general and we UP

**Comment by DrAmazing343** [comment]
> so sad to see this change absouletly devestated at the loss of the 4 pixels

The 4 pixels will remember and mourn you as they fade away o7

**Review by Wallemations — APPROVED** [review]
Fix the failed check then I'll merge

**Comment by DrAmazing343** [comment]
Done and done!

**Pull request merged**
