### PR TITLE
Replaces some goon sprites with new sprites, punching bags can now be pulled

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]:#
:cl:
imageadd: Punching bag and bank computer sprites have been changed
/:cl:

[Video](https://youtu.be/ZlHV4w5ufM0)

### CODE REVIEW

**Comment by WJohn** [comment]
Why not keep both punching bag types?

Also I don't believe I've seen goon terminals in game in any manner, so I don't know what those replace. In game pics if those are in any way useful?

**Comment by nicbn** [comment]
These replaces the bank machine, in the vault. Now it looks like a regular computer with some options. I'm adding a video

**Comment by nicbn** [comment]
Now bag looks like this:

**Comment by Iamgoofball** [comment]
that looks awful compared to the old punching bag, sorry

**Comment by nicbn** [comment]
Punching bags aren't supposed to be beautiful

**Comment by Iamgoofball** [comment]
im sorry, what

@WJohn you should just close this right now

**Comment by WJohn** [comment]
While I do prefer the goon kind in terms of quality, I think the new one makes more sense since it's not being suspended from the ceiling which we do not have.

**Comment by nicbn** [comment]
I'll try to do some improvements

**Comment by nicbn** [comment]
Does this look better?

nil

**Comment by Iamgoofball** [comment]
@wjohn stop, you're literally saying a shitty fucking sprite is better because of a meme we invented about ceilings

**Comment by nicbn** [comment]
@WJohn please review the new sprite

**Comment by Iamgoofball** [comment]
Put the goon sprite up too, dumbass.

**Comment by PKPenguin321** [comment]
goon sprite is in the sprite diff bot already but uh here
image vs image

**Comment by Iamgoofball** [comment]
yeah its not even a competition the goon sprite is better

**Comment by duncathan** [comment]
also, the idea of a punching bag being suspended in midair due to our lack of ceiling is hysterical to me rn

**Pull request closed without merging**
