### PR TITLE
Changes to DNA Injectors

### PR DESCRIPTION
**Pull request by AnturK**
- Injectors will now always activate the powers.
- Injectors now grant powers for a duration. Power removal is permanent.
- Duration depends on the powers activated by the injector. (Actual values yet to come)
- You can now create UI+UE Injector (again? i have weird feeling it was there before)
- DNA Scanner functionality remains unchanged. (Changes pending. Maybe.)
- Injectors now leave used up one on use.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
And no one played genetics ever again.

**Comment by WJohn** [comment]
By "power removal is permanent" does that mean you can't inject yourself after to get your powers again? Because that'd be garbage.

**Comment by AnturK** [comment]
@WJohn No. I just mean if eg inject a blind man with clean se he wil not become blind again in a few minutes.

**Comment by WJohn** [comment]
Ah, that's fine then. All you gotta do is carry a bunch of SE injectors in your backpack, then. No biggie.

**Comment by AnturK** [comment]
That's the idea.

**Comment by Fox-McCloud** [comment]
Why not make the powers harder to find, more gated, and based less on RNG?

Goon's genetics, for example, makes you play a mini-game to unlock the strand--certain powers are rarer than others, of course, but essentially, activating power is not RNG. As you go along, you can research additional things on your machine to make finding strands easier.

Also...powerstacking doesn't work as it makes your genome too unstable and can end up killing you.

**Comment by MrPerson** [comment]
Alright, come up with a design document and then we'll talk

**Comment by AnturK** [comment]
Feel free to code genetics overhaul.

**Comment by AlexCrimson** [comment]
Temp super powers? Fuck that.

**Comment by Fox-McCloud** [comment]
@MrPerson 

I may be able to do one better than that.

**Comment by Kromgar** [comment]
Lets make genetics EVEN WORSE.


Great idea guys

**Comment by WJohn** [comment]
It's not like you can't just grab bunches and bunches of SE syringes that you can pile an almost unlimited amount of into your backpack to prolong your guaranteed genetics.

**Comment by Kromgar** [comment]
Yes our solution to genetics never getting used is making all powers temporary. Where you have to fill your backpack with human se's brilliant

**Comment by Lumipharon** [comment]
A pile of SE injectors will kill you unless you have antitox/antirad shit as well.
It also takes a while to actually create a lot of SE injectors.

**Comment by AlexCrimson** [comment]
What next, weapon durability?

**Comment by PKPenguin321** [comment]
this is pretty much the worst idea ever

**Comment by AnonymousNow** [comment]
So, wait. Does this mean permanent power layering is out? You can't get one power with the manipulator, and then keep using the manipulator to get other powers over time, by chance?

If so, then full opposition.

**Comment by Tokiko1** [comment]
Can you still use the DNA scanner to get non-timed powers? 

If so then I'd argue that this is a good change. Maybe people will now actually enter the scanner instead of demanding injectors for powers.

**Comment by Dorsisdwarf** [comment]
Also I think it's important to mention how much of a buff 100% chance for manifest is! Currently, manifest chance is *10%*

IMO that more than counters out "Mass-produceable injectors are not permanent powers"

**Comment by Jalleo** [comment]
But injectors cannot be created on mass.

**Comment by AlexCrimson** [comment]
The manifest chance may be low, but once you get a power, it doesnt deactivate. Id rather have a power for the entire round rather than carry injectors around. Seriously, who is going to do that? Maybe one Geneticist, thats its.

**Comment by AnturK** [comment]
Updates:
- Adds Delayed option to the scanner. This will apply the selected buffer next time the machine is closed. Allows lone antisocial geneticist to get their permanent powers. Or turn victim into monkey faster.
- Injector timeout cut in half.

**Comment by Alek2ander** [comment]
The main bad thing about injectors as they are now is that they're weird not-syringes, and you're not changing _that_.

**Comment by Alek2ander** [comment]
As for the actual gameplay changes, :+1:
With the delayed scanner mode geneticists can still get their powers, and they still can provide permanent powers to people visiting the lab.
As for nerfing powers from injectors, I think it's alright, especially with the injector cooldown being reduced. This will probably make single-power injectors have some use, because it's better to have one power for 5 minutes than all 6 for 30 seconds or however that will work.

**Comment by AlexCrimson** [comment]
They will get no use. The scanner is just an infinitely better way to get powers, even before this pointless PR. There is no need to make Genetics an even more annoying job.

**Comment by MMMiracles** [comment]
Having disposable temp powers on the move or permanent ones does add an interesting dynamic. It's now possible to hide your powers and inject them at needed situations. 

Xeno infestation? Bait a xeno into trying to lunge into you as you inject hulk. Hide monkey  injectors in your storage implant to as a traitor in perma to monkey out of the vents.

**Comment by Lumipharon** [comment]
You'd lose your implant/nt get any of your shit back if you monkey'd out of perma. If you got the implant you can bloody fit a borg body + posibrain/emag/crowbar for shits and giggles.

Or just like, hulk injector.

The only time that temp powers are actually useful, is when you need hulk, but still want to have use of your guns later.

That said, I'm not so opposed to this anymore, since the machines were always way better for actually activating powers (since it didn't murder you with rad damage).

**Comment by MMMiracles** [comment]
You don't loose implants when turned into a monkey via genetics, so its still perfectly valid as an option.

**Comment by Lumipharon** [comment]
Then doesn't that mean you can bypass the whole 'can't carry stuff while ventcrawling' idea?

**Comment by AnturK** [comment]
- Lowered the buffer transfer radiation
- Injector Duration : Lowest Time Coeff *  60s * Upgrade Level

 Mutation | Time Coefficient 
 ------------ | -------------
Hulk | 1
Xray | 2
ColdRest | 5
TK | 1
Chameleon/Shroud of Darkness | 5
Monkification | 2
Other Disabilities | 1

**Comment by Alek2ander** [comment]
I think disabilities should last 5 minutes at least, short disabilities are just pointless.

**Comment by feemjmeem** [comment]
if we're putting a timer on monkey, what happens if you unmonkey someone while they're in a pipe -- just wondering

**Comment by AnturK** [comment]
Same as anything else that loses ventcrawl, they can crawl out but can't get back in. Also lose pipe vision.

**Comment by RemieRichards** [comment]
They don't lose pipe vision.
when they get put in the new mob it should call login(), which updates pipe vision if you're in a pipe (and it SHOULD be doing it regardless of if you can crawl or not, just being in a pipe)

**Comment by duncathan** [comment]
@AnturK

**Comment by AnturK** [comment]
Oh. I kinda forgot about this. I'll update it.

**Comment by duncathan** [comment]
Will revert controversial changes if people don't like it by the end of the week

**Comment by phil235** [comment]
:-1:

**Comment by PKPenguin321** [comment]
whyyyy was this merged :-1:

**Comment by Amemelius** [comment]
WHYYYYYYYYYYYYY

**Comment by Lumipharon** [comment]
Stop merging these pr's. There is a test pr functionality, why does it exist if you're not going to use it.
Seriously, how often have grossly unpopular pr's EVER been reverted?

**Comment by Xhuis** [comment]
@duncathan As a new maintainer, you're setting quite a bad streak for yourself. We have a functionality implemented specifically for testing new changes. Ask @KorPhaeron or @MrStonedOne for a testmerge if a change is controversial, not wantonly take things into your own hands.

**Comment by duncathan** [comment]
my bad; I'll do a real revert myself

**Pull request merged**
