### PR TITLE
Removes Corgi Meat as a possible steal objective

### PR DESCRIPTION
**Pull request by Ikarrus**
It's stupid and excessively silly.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
and incredibly easy, now that corgium exists.

**Comment by Nienhaus** [comment]
:+1:

**Comment by bear1ake** [comment]
How about add objective to kill Ian?

**Comment by TheVekter** [comment]
@bear1ake Naw, let's not.

**Comment by Iamgoofball** [comment]
@TheVekter why

**Comment by duncathan** [comment]
Pet killing isn't valid any more. Don't add the objective unless policy changes.

**Comment by bgobandit** [comment]
just gonna copy paste my forum thread

CORGI MEAT

The problem: Corgis are now cheap as fuck -- cargo can order a corgi crate and often does, and more importantly, science regularly shits out dozens of corgis if they find the cannon.

The solution: Make Ian produce unique meat, and change it to Ian's meat. Or maybe add corgi pelts and have Ian's pelt. This makes sense from both a difficulty/YOU MONSTER perspective, and from a fluff perspective (Ian is the station's beloved pet, killing it will strike a blow to morale, but any old corgi will do?)

**Comment by AlexCrimson** [comment]
I think its better to just remove it at this point. Ian is no longer the icon he once was. He no longer makes people valid for killing him, and the whole reason for the objective lore-wise was to demoralize the crew.

**Comment by Iamgoofball** [comment]
@duncathan good thing we have separation of code and server huh???

(For reals though replace this with something, don't just remove it and not replace it)

**Comment by AlexCrimson** [comment]
How about human meat from a head of staff? Too much?

If only RR finished dismemberment, then we couldve had head collecting objectives.

**Comment by TheVekter** [comment]
Why not specific brains?

**Comment by AlexCrimson** [comment]
Because debraining is much harder than cutting someones head off. Or atleast as far as i know according to the way dismemberment was being added.

**Comment by TheVekter** [comment]
Right but we don't have dismemberment yet because SOMEONE is dragging her
ass on it @RemieRichards

**Comment by GunHog** [comment]
Is there an objective for stealing the captain's spare ID?

**Comment by Miauw62** [comment]
thats a pretty dumb objective, point of captain's spare is to have all-access available if there's no HoP or Captain, its probably not a good idea to make people securing it suspicious.

**Comment by Ikarrus** [comment]
This is not the place for tangential ideas.

**Comment by Iamgoofball** [comment]
@TheVekter fuck off with that shit

**Comment by TheVekter** [comment]
@iamgoofball I'm kidding, geez

**Comment by PKPenguin321** [comment]
In regards to what BGO said, I made a retort to this idea on the forums already.
Making skinning Ian wouldn't make the objective any harder, as you can butcher him with any random object as long as it has the sharp flag (an esword, a shard of glass, etc.) and killing Ian doesn't allow the crew to murder you anymore without them getting banned.
:+1: for the removal of the objective.

**Comment by TheVekter** [comment]
... Any way we could do "kidnap Ian"?

**Comment by Iamgoofball** [comment]
you uh

you guys do realize

that if murder ian becomes an objective

then policy would need to change so that murder ian does make you valid salad again since that;s an antagonist objective right?

**Comment by TheVekter** [comment]
I said "kidnap", not "murder".

**Comment by Iamgoofball** [comment]
a murder pet objective could be added

just make it pick between ian, pun pun, pete, and runtime

**Comment by Miauw62** [comment]
pete and pun pun already die in most rounds anyway, though.

**Comment by Cheridan** [comment]
fyi stealing an RCD doesn't "make you valid" so server policy regarding pets is irrelevant here

it's still a pretty lame objective, we can do better.

**Pull request merged**
