### PR TITLE
Gang Mode Update

### PR DESCRIPTION
**Pull request by Ikarrus**
- Fixes round-end message always declaring both gangs lost
- 3gang is now twice as likely to appear
- Purchased spray cans will always be the gang's color

### CODE REVIEW

**Comment by Incoming5643** [comment]
What if you swipe another teams spray cans, will the color change or will I spray my tag in their color? (and if so which side does that count for, if any?)

**Comment by Ikarrus** [comment]
Gang tags will always be that gang's color regardless of what color setting you actually have on.

**Comment by Incoming5643** [comment]
Oh right I forgot spray cans can change their color.

Goddamn prismatic spray

**Comment by Ikarrus** [comment]
Spraycan code is just shit. I should have read up on how they worked before integrating them into gang.

**Pull request merged**
