### PR TITLE
Reverts yelling about reloading

### PR DESCRIPTION
**Pull request by Bawhoppen**
alright we all had our fun for christmas, it was funny for christmas CTF but in seriousness

### CODE REVIEW

**Comment by as334** [comment]
:-1:

**Comment by Bawhoppen** [comment]
don't thumbs down it didn't make any goddamn sense,
when you say things in ss13 you choose to say them it doesn't force say them for you
it also doesn't make sense because reloading is instant

**Comment by as334** [comment]
:-1:

**Comment by Dorsisdwarf** [comment]
:-1: 

it wasnt for christmas Ctf was it?

I liked it

**Comment by Bawhoppen** [comment]
it wasn't exclusively I guess but its still a pointless stupid meme that needs to go

**Comment by Incoming5643** [comment]
Anything that makes players force say things is tacky as hell from my point of view :+1:

**Comment by YotaXP** [comment]
Could it instead be set to only trigger on the Centcom and CTF layers?

**Comment by Bawhoppen** [comment]
I'd be fine with making it only for CTF but I have no clue how to

**Comment by phil235** [comment]
:+1:

**Comment by Iamgoofball** [comment]
:-1:

**Comment by optimumtact** [comment]
:+1: even though I had a perfectly good revert up and cheridan closed it

**Comment by Niknakflak** [comment]
:+1: 

>nuke op hiding in a locker
RELOADING

**Comment by Bawhoppen** [comment]
>FUN REMOVAL

**Comment by AlexanderUlanH** [comment]
:-1: I just used the SABR to mow down a bunch of clown simplemobs and it was the coolest shit

**Comment by Bawhoppen** [comment]
you can still do that???

**Comment by Iamgoofball** [comment]
>nuke op hiding in a locker
>implying this happened outside of someone's mind looking for every potential reason to get a PR closed

**Comment by AlexanderUlanH** [comment]
Yes but I wouldn't have time to yell "I'M RELOADING" myself
This is an important quality of life feature.

**Comment by KorPhaeron** [comment]
If you are actually a nuke op hiding in a locker you can do the normal reload instead of the tactical one

**Comment by Bawhoppen** [comment]
thats a dumb excuse

**Comment by KorPhaeron** [comment]
@phil235

Mimes wont speak unless they broke their vow previously, they fail the IsVocal check

**Comment by Jalleo** [comment]
Please remember this makes it so other people rather than just wizards with spells add junk to the chat which can cause helarious situations.

**Comment by Man-Shroom-** [comment]
:-1: X  :100:

**Comment by Aloraydrel** [comment]
I'd like to see the case of a nuke op trying to reload in a locker hiding tbh :-1:

**Comment by duncathan** [comment]
:-1:
If your reasoning is because you don't want to be forced to say something, maybe make the gun say it or something
Every other goddamn thing in this game speaks anyway so

**Comment by Bawhoppen** [comment]
Its because its ridiculous and just there for the sake of being a meme

making it so some guns would make a noise when reloading would be ok I guess but kinda silly too

**Comment by PKPenguin321** [comment]
Make it toggleable via alt-clicking a gun as an Easter Egg, like how explosive spears have the WITNESS ME one

**Comment by Bawhoppen** [comment]
wait they do?
should revert that too

**Comment by PKPenguin321** [comment]
>pushing the "coders hate fun" meme this hard

Please just leave

**Comment by Bawhoppen** [comment]
this isn't fun its just silly, makes no sense, is inconsistent, and just dumb

**Comment by PKPenguin321** [comment]
said the Grinch in reference to Christmas

**Comment by Bawhoppen** [comment]
christmas is over thats the only reason I allowed this shit

**Comment by PKPenguin321** [comment]
My point was that your ideas of what is and is not fun is inconsistent with a majority and you're resented for it

In other words, fuck off with your shit opinions

**Comment by Bawhoppen** [comment]
I see support for this being reverted too

**Comment by Bawhoppen** [comment]
also if everyone got what they wanted this would be a unpopulated slip-only stungloves oldling TDM server

**Comment by newfren** [comment]
:-1: 
Look bawhoppen more "support"

**Comment by Shapsy** [comment]
Go away grind :-1:

**Comment by KorPhaeron** [comment]
>I allowed

?

**Comment by KorPhaeron** [comment]
Also the head coder already ruled on this, immediately recreating a denied PR is against yhe rules please cease

**Comment by Thunder12345** [comment]
:+1:
Bad meme, kill it

**Comment by Bawhoppen** [comment]
@KorPhaeron that was closed cause that was pure memes

**Comment by Bawhoppen** [comment]
closing cause of https://github.com/tgstation/-tg-station/pull/14089

**Comment by Bawhoppen** [comment]
very well

**Comment by PKPenguin321** [comment]
Fuck

**Comment by optimumtact** [comment]
please make up your mind

**Comment by PKPenguin321** [comment]
I need to make a PR that reverts bawhoppen to be very honest

**Comment by Bawhoppen** [comment]
can't ignore me on my own pr

**Comment by Bawhoppen** [comment]
bless our lord and savior
I forgive you about the whole murderbone as ninja with protect objective

**Comment by PKPenguin321** [comment]
bawhoppen's communist nazi agenda is now furthered another step
don't you see what you have done raz

**Comment by Razharas** [comment]
>communist nazi agenda
>don't you see what you have done raz

Oh i know exactly what im doing

**Comment by duncathan** [comment]
;_:7

**Pull request merged**
