### PR TITLE
[DO NOT MERGE] Mini-Sat Tweaks

### PR DESCRIPTION
**Pull request by Penguaro**
Some concerns...
-RD Can't get to AI Upload on this map without EVA or Hacking Engineering (even prior to PR)
-This PR means there is only one secure door before AI Upload if an antag is breaching into the station from outside the minisat.
-The method of validating access to a turret is odd and I'm waiting for feedback on the forum before completing this. https://tgstation13.org/phpBB/viewtopic.php?f=10&t=10186

:cl: Penguaro
tweak: Delta - Added second entrance to AI - Upload to allow easier access
tweak: Delta - Adjusted access levels of Airlocks to MiniSat and Tube Access
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
Currently AI Upload is located within the Satellite past the first set of security turrets which have a higher level of security than the Upload room. This means without AI support a member of command would be challenged to get to AI Upload. There is now an entrance on the aft side of the chamber. The access levels of the doors in the minisat were inconsistent with other maps.

This is intended to address #25126.

### CODE REVIEW

**Comment by Penguaro** [comment]
I'll have a before and after picture shortly.

**Comment by Penguaro** [comment]
__BEFORE__
before

__AFTER__
after

**Comment by Penguaro** [comment]
In a nutshell, I switched the fore/aft airlock and window. One concern is that AI Upload is more accessible now by an antag. Normally Upload is within in the station so someone breaking into the station would have more challenge. From here, they can just go eva and break through some reinforced windows. I'm considering adding a small layer of reinforced walls.

Any thoughts anyone?

**Comment by ma44** [comment]
How is the captain suppose to go into it anyway, greytiding from spess?

**Comment by Penguaro** [comment]
There was a deleted comment from someone asking about how the Captain could get in and of course there's a path on the side. That did raise a different question though and that is how does the Research Director get there without hacking through? Realistically, AI Upload may need to be relocated from the minisat on this map for that reason.

**Comment by ChangelingRain** [comment]
Why not have both airlocks, and let people get in from both sides?

**Comment by Penguaro** [comment]
@ChangelingRain That's certainly a possibility. The door would need to be coded wtih MiniSat and Upload access. The turret control for upload would still be best on the south side of the room so people could access it normally. In order for a player to access from the foyer, they'd need an AI to turn off the turrets there so the AI could turn off the upload turrets remotely as well.

I noticed from the pictures I neglected to remove the turret control from the north side of the room (in minisat hall) and will remove that.

**Comment by Penguaro** [comment]
Updates
-Added door to north side of room with access required for minisat and upload
-Removed duplicate turret control from north wall
-Changed After Picture
-Changed PR text

**Comment by Penguaro** [comment]
More edits - I discovered that all of the doors had incorrect access on the minisat allowing construction access, upload access, heads access to enter various areas. I changed these to be consistent with other maps and adjusted the PR notes and name.

If the turret just needs to be adjusted, then just the access level of the turret and the various doors would be all this needs and the map edit would not be needed. I added DO NOT MERGE to the title while this is investigated. I started a forum thread about this here

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=10186

**Comment by Penguaro** [comment]
I've found a very different solution to this problem and will submit a clean PR.

**Pull request closed without merging**
