### PR TITLE
Smooth movement

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Makes smooth movement work like it does on goon/bay (fps agnostic)

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:+1: x :100: 

This is one thing about TG I've never quite liked---movement is veryyyy jerky, even when the game is completely smooth; this makes things feel and seem much more smooth in terms of movement. Can't give this enough thumbs up.

**Comment by Incoming5643** [comment]
Was never a fan of this, having the character so perfectly centered on the screen at all time gave me a sense of the world moving around the character instead of the character moving around the world.

subjective :-1:

**Comment by Bawhoppen** [comment]
:-1: I don't like it as much

**Comment by RemieRichards** [comment]
oh GOD no.
this is horrible :-1:

**Comment by Incoming5643** [comment]
After some playing around with this on a live server I'm moving this from "I have some subjective problems with this but I acknowlege that it might be a good idea" to "I actively dislike this and would be less likely to play the game if I had to deal with this"

The smoothness is distracting, everyone looks like they're slowly skating on a very rough slab of ice, it legitimately makes me feel a sensation almost like a weak form of carsickness.

**Comment by MrStonedOne** [comment]
the issue is anything else breaks down at higher fpses and is why we haven't done them.

**Comment by Supermichael777** [comment]
parallax space when? actually couldn't that be achieved by making space turfs invisible and making an overlay at the bottom-most layer and changing that based on area? seems  like you could have a config option that loaded a different space texture too for people who cant stand the vastness of the inky void.

**Comment by RemieRichards** [comment]
@Supermichael777 yes, and paradise did it already.

**Comment by Incoming5643** [comment]
On personal level I really don't care if we ever see 30/60 fps out of this game, given the graphics I don't think it really adds much of anything other than fucking with everyone's perceptions when people change it.

**Comment by MrStonedOne** [comment]
Ran a test on sybil and bagil, some hated it, some liked it

bagil:
How did you like smooth movement?
Its ok: 11
It sucks: 3
I hated it until i got used to it: 1
I liked it at first, then i hated it: 3
Did not vote: 20

Sybil:
How did you like smooth movement
Its ok: 7
It sucks: 9
I hated until i got used to it: 0
I liked it at first, then i hated it: 0
Did not vote: 14

**Comment by lzimann** [comment]
I really prefer the way it is now and not this smooth, just feels out of place

**Comment by KazeEspada** [comment]
:+1:  I liked this change. I feel like it will take some getting used too.

**Comment by demonfiren** [comment]
Run a poll when Sybil is halfway decently populated, MSO.

**Comment by optimumtact** [comment]
These things definitely need time to adjust to as well, so perhaps merge for a few weeks, then run a poll once people have had a chance to adjust past the weirdness of a slightly different movement system.

**Comment by MrPerson** [comment]
Why would you intentionally not want it to look smooth? Jerky looks like shit

**Comment by Steelpoint** [comment]
"I don't like smooth movement"

What is wrong with you.

**Comment by Cheridan** [comment]
Well, seems like this has more support than detractors. If for some reason there's some huge backlash then whatever it's 1 line

**Comment by Incoming5643** [comment]
this was never even test merged!

**Comment by RemieRichards** [comment]
@Incoming5643 pretty sure it was actually.

**Comment by Incomptinence** [comment]
Ugh not for me sorry.

**Pull request merged**
