### PR TITLE
Changeling absorb sound

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
- it doesn't ignore walls

https://github.com/user-attachments/assets/fa4d010b-cee4-455a-a3c8-43e6839ab596
## Why It's Good For The Game
I think it's very atmospheric and helps hammer in the idea that changelings are horrific monsters
## Changelog
:cl: grungussuss
sound: changelings now have a sound for absorbing
/:cl:

### CODE REVIEW

**Comment by DaydreamIQ** [comment]
Y'know, I think this might be the first time I'll say...I think we're better off not hearing what that sounds like actually.
Please stop being so good at your job its horrifying

**Comment by DrAmazing343** [comment]
It's a great sound, but yeah, hearing in repetition may be a bit too much. 'specially if there's ever one of those double ling revive chicken fights going on.

**Comment by Sadboysuss** [comment]
> hearing it in repetition may be a bit too much

- There are 3 stages for a ling absorb

- The sound only plays on the 3rd stage and ends on absorb end

**Comment by Bibarra** [comment]
It's a great sound, but _should_ it have a sound? Lings have a need to be stealthy and I can't count how many times I've had a casual conversation with another character while absorbing someone "pretending" to be investigating. This would be a dead tell the player is a ling and make absorbing even harder than it already is.

**Comment by DATA-xPUNGED** [comment]
This really sounds like someone chewing, misophonia mfs is gonna hate this (me, i'm the mfs)

**Comment by norsvenska** [comment]
ok, hear me out guys. what if it was like this instead

https://github.com/user-attachments/assets/2f2a46ed-d1c3-469e-b4f5-a055a647e0e1

**Comment by MrMelbert** [comment]
> ok, hear me out guys. what if it was like this instead

I suggested they make it this on april fools

**Comment by Ghommie** [comment]
> ok, hear me out guys. what if it was like this instead
> slurp.mp4

I knew this would happen. I knew it. I was certain. I already composed that sound, playing in my head. I was prepared, I was sure, or so I thought. 18 seconds. 18 seconds, of slowly losing hope, and then, it hits me like a truck. God fuckind damnit, lol.

**Pull request merged**
