### PR TITLE
Electroadaptive_pseudocircuit for carbons.

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
Split electroadaptive_pseudocircuit for carbons and cyborgs.

## Why It's Good For The Game
Lazy engi like it.

## Changelog
:cl:
add: Electroadaptive_pseudocircuit for carbons.
/:cl:

### CODE REVIEW

**Comment by BeeSting12** [comment]
Theres no real need for carbons to have it. Borgs need it to construct APCs and air alarms but carbons have the actual circuits for it.

**Comment by Dennok** [comment]
it need to go to fab to create it.

**Comment by nemvar** [comment]
The correct solution would be to get rid of airlock, firelock, APC and air alarm circuits and replace them with a unified one. It would allow every single one of those machines to get their access levels changed (would obviously do nothing for firelocks) and make construction a lot less of a hassle.

**Comment by Dennok** [comment]
Not enough robust

**Pull request closed without merging**
