### PR TITLE
Fixes frozen PDAs in the game logs

### LINKED ISSUE #30944: frozen pdas show up as frozen on the pda message list

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by BeeSting12** [comment]
@Cyberboss 
Will this also fix the PDA appearing on the PDA list accessed from the PDA as frozen?

**Comment by Cyberboss** [comment]
ehh no

**Comment by BeeSting12** [comment]
yeah thats what i made the initial issue about. this is good too though

**Comment by Cyberboss** [comment]
Gonna take a big refactor to fix that and I don't feel like it right now

**Pull request merged**
