### PR TITLE
Radial close button is now more clear

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR does a simple sprite change to a radial close button by adding red cross over it, to make it more clear what it is and what it does, as previously players struggled to notice it, or were not sure what it did.

Example image (Updated!):

RadialCloseButtonTuned

## Why It's Good For The Game

Clear close button and less confused players.

## Changelog
:cl: Arkatos
qol: Radial close button is now more obvious and clear.
/:cl:

### CODE REVIEW

**Review by Twaticus — APPROVED** [review]

**Review by Mothblocks — APPROVED** [review]

**Comment by maxymax13** [comment]
make it the same color as the other buttons instead of garish red

**Comment by Mothblocks** [comment]
should maybe lower the darkness on the background too

**Comment by Mothblocks** [comment]
show new screenshots too

**Comment by Arkatos1** [comment]
Main post updated with a new image. Tuned down colors to be more inline with surroundings, but still very much visible.

**Comment by Mothblocks** [comment]
i like it better

**Comment by cacogen** [comment]
bikeshed but this is ugly and while it's true the centre button is unintuitive (does it have a tooltip already?) eventually you build up the courage to try it and see that it just closes the menu

**Pull request merged**
