### PR TITLE
Removes black stockings

### PR DESCRIPTION
**Pull request by Rowelll**
## About The Pull Request

my second ~~fetish content~~ PR about socks, this one removes black stockings from Affected's PR (#44274)

## Why It's Good For The Game

Black stockings are literally "Striped Thigh-highs" and thus they take up space. ~~(it's not like it's just 3 lines of code and some meaningless bytes)~~

## Changelog
:cl: Rowell
del: Removed black stockings
/:cl:

### CODE REVIEW

**Comment by Rowelll** [comment]
jeez i should start searching for more interesting stuff

**Comment by AffectedArc07** [comment]
Let me be retarded in peace. Also how will this impact someone that selected these

**Comment by Rowelll** [comment]
I'm not really sure, but if they are curious, they should check this PR and just change them to thigh stripped

**Comment by HomocidlePancakes** [comment]
Why stop at one kind of stockings when you can remove all of them?

**Comment by Rowelll** [comment]
DIY

**Comment by optimumtact** [comment]
jsut remove the other version

**Comment by Rowelll** [comment]
it's an alternative option

**Comment by ExcessiveUseOfCobblestone** [comment]
what? You just said they were the same?

**Comment by Farquaar** [comment]
They always looked pretty dumb anyway

**Comment by Rowelll** [comment]
>what? You just said they were the same?

Yes, they are the same, but older version has knee and thigh versions and new version is basically thigh. I had two options:
Remove new or remove old.
I chose removing old

**Pull request merged**
