### PR TITLE
Adds plastic, makes plastic flaps constructable and deconstructable

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Cargo can now order plastic sheets to make plastic flaps. No doubt
other uses for plastic will be discovered in the future.
add: To deconstruct plastic flaps, unscrew from the floor, then cut apart with wirecutters. Plastic flaps have examine tips like reinforced walls.
/:cl:

image

Later maybe we can make cable coils use plastic and metal, rather than
metal and glass. And make plastic tables. And make foam darts use
plastic rather than metal. And make spray bottles out of plastic. And
cheap plastic tables. And cheap plastic chairs.

Why? Because plastic makes sense as a material that you can make stuff
out of, and those DAMNED PLASTIC FLAPS AREN'T CONSTRUCTABLE.

### CODE REVIEW

**Comment by Niknakflak** [comment]
the beginning of large space ocean pollution starts with this PR

**Comment by ChangelingRain** [comment]
>construct nearly-indestructible flaps, which are used explicitly like walls in most places

**Comment by kevinz000** [comment]
@coiax is not environmentally friendly.

**Comment by cedarbridge** [comment]
So we just make them destructible. Easy as.  Especially given structure damage anyway.

**Comment by TehZombehz** [comment]
Well, even if the initial reason is for something kinda oddly specific, adding plastic as a material would introduce a world of fun new construct-able things to ~~pollute space with~~ construct.

**Comment by optimumtact** [comment]
Yeah, just give them similar deconstruction times as for walls

**Comment by XDTM** [comment]
Or just hack your legs off duh

**Comment by jughu** [comment]
Plastic bags when
Plastic bags over head to cause suffocation damage when

**Comment by Anonmare** [comment]
Are plastic sheets going to only be available from cargo or can chemistry make some sheets too? I believe plastic is a hydrocarbon  made from oil.

**Comment by BeeSting12** [comment]
Plastic flaps would have to be made relatively easier to deconstruct. Other than that, 👍

**Comment by SgtxRootbeer** [comment]
Maybe chem could make like 30 units of oil, and add 10u of some "bonding" chem, which bonds with 10u of oil (so we get 40u of an intermediary chem like "unpure resin") You then burn the unpure resins' contaminants to get 1 sheet of plastic. similar to making soap.

**Comment by Militaires** [comment]
:thumbsdown: to the plastic flaps, all the of the meta rooms are balanced around the plastic flaps being indestructible, you're literally opening up security to fucking anyone if you remove their invincibility

also plastic flaps being indestructible is a persistent meme dont remove it you dumbfucks, not everything has to be constructable

**Comment by PKPenguin321** [comment]
Plastic flaps are always surrounded by walls/r-walls though, so if you just make them take as long as an r-wall to decon then you're not really changing much in terms of how hard it is to breach a department that uses them

**Comment by jughu** [comment]
Reinforced plastic flaps when

**Comment by Cheridan** [comment]
what joan said. we literally can't add this as long as flaps can't be deconstructed

**Comment by PKPenguin321** [comment]
Just make them construct and deconstruct like walls, maybe instead of girders you have to build the roof anchors for the flaps instead and then secure them to the roof before fastening the actual plastic flaps

**Comment by coiax** [comment]
Now constructable and deconstructable.

**Comment by optimumtact** [comment]
Did you make them take at least as long as walls? otherwise they're a free entryway into nearly every room on the station.

**Comment by coiax** [comment]
They take as long to decon as a wall would.

**Pull request merged**
