### PR TITLE
Updates the colored glasses sprites

### PR DESCRIPTION
**Pull request by Lexorion**
@Niknakflak asked me to change them. Pic below shows both old and new colored glasses. 
pr preview

### CODE REVIEW

**Comment by PKPenguin321** [comment]
not bad, can you do aviators?

**Comment by pudl** [comment]
I really prefer the old sprites to these, theyre more consistent with the rest of the game too

**Comment by Niknakflak** [comment]
amazing, redo onmob perscription and onmob hipster too if you could.

**Comment by Bawhoppen** [comment]
they're not supposed to be sunglasses??????

**Comment by PKPenguin321** [comment]
how do u know that

**Comment by Bawhoppen** [comment]
i am the chosen one :man_with_gua_pi_mao:

**Comment by Lexorion** [comment]
oh god what is happening,I think I messed up but it compiles now 
@Niknakflak Those are okay,I don't think I should change them
@PKPenguin321 Mmmmaybe,I made some earlier but they ended up being HUGE so I don't know
@Bawhoppen what *are* those glasses supposed to be,I wonder. I thought they were cheap sunglasses (which offer no protection since they are that cheap)

**Comment by Niknakflak** [comment]
The onmob glasses sprites need help

**Comment by Dorsisdwarf** [comment]
But really, they're meant to be goggle-like, not distinct glasses.

Nice sprites though

**Comment by Xhuis** [comment]
I kind of liked the yellow ones for my totally-not-Ratvar getup. They match the actual name now though so I like it anyway.

**Pull request merged**
