### PR TITLE
Bonfire can be made with wood

### PR DESCRIPTION
**Pull request by Colovorat**
## About The Pull Request

Bonfire can be made with wood

## Why It's Good For The Game

Bonfire can be made with wood

## Changelog

image

:cl:
qol: Bonfire can be made with wood
/:cl:

### CODE REVIEW

**Comment by ProfessorSniff** [comment]
Bonfire can be made with wood

**Comment by Colovorat** [comment]
> Bonfire can be made with wood

they can be made only with tower cap logs

**Comment by nianjiilical** [comment]
bonfires currently require unprocessed logs which makes a lot of sense but i can also confirm that i see like one ahelp a week asking why people cant make bonfires with processed wood planks so i support this

maybe someone could make an alt bonfire sprite for plank bonfires someday

**Comment by TheBonded** [comment]
> > Bonfire can be made with wood
> 
> they can be made only with tower cap logs

I think they were probably continuing the chain of saying "Bonfire can be made with wood" from the "About The Pull Request", "Why It's Good For The Game", and changelog sections of the pr body, and not suggesting that it's the case already.

**Comment by Colovorat** [comment]
> > > Bonfire can be made with wood
> > 
> > 
> > they can be made only with tower cap logs
> 
> I think they were probably continuing the chain of saying "Bonfire can be made with wood" from the "About The Pull Request", "Why It's Good For The Game", and changelog sections of the pr body, and not suggesting that it's the case already.

Me sorry, me do not understand Englisho jokes

**Comment by bluetshirtguy** [comment]
I think having atleast 2 uses for uncut tower logs to be worth keeping instead of 1 single use.

**Comment by Colovorat** [comment]
> I think having atleast 2 uses for uncut tower logs to be worth keeping instead of 1 single use.

no

**Pull request merged**
