### PR TITLE
Makes the cult Talisman of Horrors ranged

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
tweak: Blood Cult's talisman of Horrors now works at range. It will still give no warning to the victim.
/:cl:

Because right now if you want to slap someone with a paper it might as well be stunpaper. Making it ranged allows cultists to cause confusion on key targets, making them see eswords, plasma floods and so on.

Remeber that hallucinations no longer stun you for hours, and that all stunning hallucinations are avoidable.

### CODE REVIEW

**Comment by kevinz000** [comment]
remind me why bloodcult needs MORE buffs? And hallucinations are fucking destruction to anyone getting hit by it, and how are stunning hallucinations avoidable? Don't answer with some powergamey stuff because not everyone will do it.

**Comment by Core0verload** [comment]
Just run away from stun-inducing hallucinations.

**Comment by kevinz000** [comment]
@Core0verload and how is that not strong enough to be melee only?

**Comment by XDTM** [comment]
most hallucinations don't stun, and running away is pretty intuitive

**Comment by XDTM** [comment]
Plus the stun is usually 2-3 seconds and unpredictable by the cultist, or delayed enough that it makes it not really good for combat.

**Comment by Metacide** [comment]
Looks like a very irritating buff for cult, don't really see the need for it.

Hallucinations are much more powerful than you let on, and make dealing with anything much more difficult. How long will they last in this case? Having no indication of what happens makes it sound terribly irritating to encounter. If you waltzed up to the brig and silently used these on everyone in security you'd put most of the station's resistance out of action for a fair chunk of time, completely uncounterably.

Sounds like a bad idea to me, playing cult rounds is already tiresome enough.

**Comment by XDTM** [comment]
I've stared into the SM for a whole round to see what would happen, and about 95% of the time it resulted in deceptive but otherwise harmless visions or noises.
The singulo can be outrun, since it only moves 10 tiles before disappearing, and the bubblegum has a delay and a very clear line to avoid being in. Fake attackers don't deal much damage in the first place, but i changed them so they could be fought off with damaging weapons.

The whole point of hallucinations is convincing the target of a nonexisting threat. If the talisman said "You have been cursed with horrors!" or whatever, then they'll just say that they're hallucinating and wait it out.

**Comment by coiax** [comment]
As @XDTM said, if you're going to hit someone with a melee range talisman, you'd 99% use a stun talisman.

**Comment by KorPhaeron** [comment]
Maybe the talisman should just be removed then

**Comment by XDTM** [comment]
or, bear with me here, it could have another niche in spreading confusion amongst the opponents through hallucinations, which are a bit of an underused mechanic

**Comment by Robustin** [comment]
I already outlined my plan for replacing this recently, but this is a fine adjustment in the meantime. Technically its superiority in melee range comes from having no attack animation/invocation so outside of the small handsprite there's no indication that someone has been "hallucinated" - but as I argued the niche benefit is not worth the time/effort/risk of having to create the talisman, carry it out, then find an appropriate victim and try to get in melee range of them. I liked the theory of being able to both inhibit sec's fighting strength and throw the meta so cultists could feign changelings... but realistically, like the fake runes talisman, it just was a little too much effort for a marginal benefit. 

New talisman of horrors:
- Stealthy AOE
- No vanilla hallucinations
- Makes the victim see all carbon mobs as cultists (Robe+Sword) and all simple mobs as constructs
- Cultists are immune obviously

If you want you could make this one AOE anyway. Like you said the hallucinations aren't as OP anymore, but they are a little more convincing, I don't think it would impact more than 1% of rounds. With the Cult Master/Constructs Update/Rune Update coming I am going to make things harder for the cult in other ways. I anticipate the "3 randomized rooms" summoning requirement and multi-sac requirements causing a material drop in win-rate. I'm also contemplating a tome damage nerf, manifest ghost will be buffed in some ways but nerfed in others that may overall drop win rate, etc.

**Comment by octareenroon91** [comment]
Maybe cut the dose for balance?

**Comment by XDTM** [comment]
25 is a bit much, but i want to see how this goes before nerfing it.

**Comment by lzimann** [comment]
Ranged hallucination is stupid.

**Comment by octareenroon91** [comment]
>Ranged hallucination is stupid.

For whom?

**Comment by lzimann** [comment]
For everyone involved.

**Comment by Robustin** [comment]
Literally a bikeshed PR given it rarely gets used and will only be in this form for a month, two tops.

**Comment by KorPhaeron** [comment]
Am I missing something with my mindbreaker math?

25 units, consumed at .4 units per tick, lasts 62 ticks. +10 hallucination per tick you have mindbreaker.

So 620 total. Meanwhile you only get -2 hallucinations per tick.

So just one of these and the guy has 5 and half minutes of hallucinations to deal with, which is a pretty substantial chunk of the round. Maybe this speaks more to mindbreaker being obnoxious than the talisman, but it seems like it'd be pretty trivial to fuck up security by running up to the brig window and clicking on them, or past them in the hallway.

**Comment by Metacide** [comment]
Five minutes of random stuns such as the singulo which can get you through walls instantly with no warning? Not to mention bolt lockdowns, random attackers, and all the other hallucinations which are difficult to manage when you're not fighting a coversion antag.

This sounds absolutely cancerous to encounter. If you're going to add something this powerful it needs to be brightly visible in-hand and have​ a spoken invocation at the very least.

How did this seem like a good idea?

**Comment by XDTM** [comment]
Hallucinations are definitely not as powerful as you make them seem, @Metacide

**Comment by PKPenguin321** [comment]
Yeah hallucinations were toned way way way the fuck down recently

**Comment by XDTM** [comment]
As i said, i reworked them to make them fool people rather than acting as an unreliable stun

**Comment by Robustin** [comment]
@KorPhaeron 

You're still thinking of old hallucinations. If we still had those I'd have a different take on this but the new ones are 95% distractions and 5% actually detrimental in combat. 

I made this talisman strong (with old hallucinations) because I knew that inconveniencing an officer for 2 minutes wouldn't be enough to justify the risk of getting caught and taken out of the round for 30 minutes - but even then it still wasn't worth it. Now that hallucinations are nerfed (its a good thing) this talisman needs a new angle. 

Until I add that (RIP another weekend trying to have my cult master PR keep up with constant refactoring of EVERYTHING), this is a decent compromise.

**Comment by octareenroon91** [comment]
Results of testing 20u Mindbreaker today:

Disruptive, but not paralyzing. It took a while to kick in, pinned me down with one of two singulo hallucinations it threw at me. The dose will make a target a bit more vulnerable for some time, especially if they're attacked by a mob or otherwise slowed down at some point.

Hallucination takes time to start and then escalate:

`code/modules/flufftext/Hallucination.dm`:

````
        while(hallucination > 20)
                sleep(rand(200,500)/(hallucination/25))
````

**Comment by duncathan** [comment]
@KorPhaeron

**Comment by Metacide** [comment]
I still worry this is a buff cult doesn't really need that will only make cult rounds more tedious and more difficult to deal with. That it is entirely stealthy and takes time to kick in makes it sound very irritating indeed.

I guess we'll see how it goes..

**Pull request merged**
