### PR TITLE
removes all dirty map var edits from the codebase and reverts pixel_x/y grep

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Reverts tgstation/tgstation#54845
i manually ran every single map to remove all redundant vars and sort vars in order

## Why It's Good For The Game

the grep is an arbitrary limit on the specific number 0 made with the intention of removing dirty vars, and the original pr that added it already changed the pixel_y on some map objects from 0 to 1, i dont think we should have that stuff if we can just not have any of the dirty vars (unless we had some script that checks for those dirty vars like dynamically instead of comparing to 1 static number), especially with them becoming very rare since the most popular mapping tool automatically disables them and if you tick it in options completely remove them from the entire map file

## Changelog
unneeded

### CODE REVIEW

**Comment by optimumtact** [comment]
DNM'ed until you explain why you're reverting the lints

**Comment by optimumtact** [comment]
seems like there's no maintainer support to merge this

**Comment by EOBGames** [comment]
I know I gave approval to the original PR, but having put some thought into it since this grep does cause some issues for mappers- any item with a built-in pixel variable (best example I can think of is fireplaces) would need a new code variant due to causing a false positive, which seems unnecessary for such a minor edit. With that said if another maintainer wants to merge this, I'd offer support for it.

**Comment by optimumtact** [comment]
You're the maptainer

**Pull request merged**
