### PR TITLE
Removes Thieves

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Removes thieves, and their midround counterpart, opportunists

## Why It's Good For The Game

Plethora of reasons. The short of it is that I don't think /tg/station is the server for a miscreants-level-antagonist and it won't be for a very long time. And because it's not, future headmin candidates are going to struggle to change thief to be something different, and it's going to become antithetical to its original goals.  So away with it!
The long reasons list:
* Thief fails to be open. When I implemented flavor traitors, the flavor supplements the antagonist, but they are still free to do as they please. Sure, after that progression traitors got added, but that changes their access to gear, not necessarily their freedom on actions. MRP traitors always had rules around objective following. Thieves have their flavor tied to objectives, and while they can do whatever and ignore objectives, players do not do that in practice.
  * Says my point well: image
* Thief fails to work in LRP. People are confused about what they are allowed to do, since all other antagonists have no restrictions, but thieves do, it ends up with policy headaches. Some candidates are discussion allowing thieves to kill to steal, which will go against the very notion of a 'miscreant-level' antagonist.
* Thief fails to work in MRP. On MRP, people are overly cautious, and farm objectives without actually committing crime, and repercussions for thieving frequently bring up admin headaches, though not the ones like LRP has.

Sorry for uh... dejecting ss13 to that for awhile. I'll try better to design good antagonists. But at least it's not going to become a headmin candidate talking point, getting desecrated by wide policy changes until it is finally taken out back, that whole process won't be fun for players.

## Changelog

:cl:
del: Thieves are gone, and so are Opportunists, their midround counterpart.
/:cl:

### CODE REVIEW

**Comment by anclandor** [comment]
I feel like a team thief antag where one player is a crew leader and assembles a crew of like four spacemen to pull off some epic heist would be cool, but I totally agree with putting the kibosh on current thieves.

**Comment by Mothblocks** [comment]
Edit the codebase dynamic.json too

**Comment by tralezab** [comment]
You'll find it funny to hear they were not in there

**Comment by necromanceranne** [comment]
Rest in pepperoni pizza

**Comment by Iamgoofball** [comment]
Another gamemode ruined by an ineffective admin team who refuse to curate a playerbase that is capable of understanding anything more complicated than a binary "valid/not valid" and "can murderbone/cant murderbone" model of gameplay that caters to children who lack critical thinking skills

we should really leave it in the code, /tg/station the server being unwilling to do basic gameplay moderation does not mean that /tg/station the codebase should remove perfectly fine and functional gamemodes

just because a town of people refuse to drink anything but soda does not mean the city shouldn't have a water supply

**Comment by Palpetinus** [comment]
>a playerbase that is capable of understanding anything more complicated than a binary "valid/not valid" and "can murderbone/cant murderbone" model of gameplay that caters to children who lack critical thinking skills

It's not children, it's people who play ss13 purely to PvP. I could go on a tagent about how rule 12 did absolutely nothing and name five different "problem" people, but this is github, not the tg forums so this is the wrong place for it.
Bottom line is, Thief is simply not something the players enjoy, neither from the perspective of playing them, nor from the perspective of playing against them. Removing them until uncertainty about valids/nonvalids has cleared up (probably never) is the best choice here.

**Comment by Iamgoofball** [comment]
>It's not children, it's people who play ss13 purely to PvP. 

yeah, children

**Comment by ninjanomnom** [comment]
In general I prefer to allow coders to play with concepts even if I suspect the concept will fail as experimentation is beneficial for us all to see what the design space looks like. Goof has expressed interest in picking up this game mode from arm so I'll allow him 2 major prs in regards to thieves before we consider removal again. Alternatively if a month passes with no thieves prs from him we can consider his efforts over and consider removal again then.

**Comment by Kitfox88** [comment]
> I feel like a team thief antag where one player is a crew leader and assembles a crew of like four spacemen to pull off some epic heist would be cool, but I totally agree with putting the kibosh on current thieves.

Nuke ops without the station destruction would be cool.

**Comment by optimumtact** [comment]
@ninjanomnom I don't trust goof and you should not either, @Mothblocks requesting you pick a side on this topic

**Comment by Mothblocks** [comment]
Goof wanted an answer by the end of the day so at present my gut agrees with oranges on a no

**Comment by Iamgoofball** [comment]
you should hit the merge button then

**Comment by Mothblocks** [comment]
Oh I thought this was the Goof PR I'm stupid

**Comment by Iamgoofball** [comment]
and with that, we admit we refuse to make antagonists with interesting storytelling goals 🥳 

enjoy the future of ss13 folks

**Comment by tralezab** [comment]
adios thieves
https://user-images.githubusercontent.com/40974010/185729238-9246cc2f-a104-4f9e-8275-7dda7ef422a8.mp4

**Comment by tgent007** [comment]
> and with that, we admit we refuse to make antagonists with interesting storytelling goals 🥳
> 
> enjoy the future of ss13 folks

We will this antag was not fun and created no stories. If people cant already make stories what makes you think they will change if you try to push it onto them?

**Comment by Iamgoofball** [comment]
you're the kind of person who ruined this game, @tgent007

**Comment by wesoda25** [comment]
> and with that, we admit we refuse to make antagonists with interesting storytelling goals 🥳 
> 
> 
> 
> enjoy the future of ss13 folks

Can't you accomplish that with flavor for pre-existing antags?

**Comment by ninjanomnom** [comment]
@optimumtact I don't trust goof to succeed here but I do trust him make things interesting before he fails. I see it as little loss to keep thieves around for another couple months while goof experiments with gameplay with them and see potential benefit from finding out what's fun or interesting and applying what we learn to future projects.

But if the two of you don't think it's worth the exchange then I can't do anything about that.

**Comment by Iamgoofball** [comment]
it doesn't matter, they aren't interested, it's not worth the argument

**Comment by Iamgoofball** [comment]
@wesoda25 you lack perspective

**Comment by Iamgoofball** [comment]
oranges isn't saying he doesn't trust me to success

he's saying he doesn't trust me, no qualifier, 

why does everyone read what oranges posts and then append new words onto it to try to extrapolate a different meaning

**Comment by tgent007** [comment]
> that is the attitude that is ruining this game, @tgent007, by refusing to play the game in any way other than as competitive TTT

Where did you pick that up?
I don’t want this game to be competitive and I also don’t want pvp to be the major factor. I just want the game to be a place where people aren’t forced to do something they don’t want to do or that gets in the way of them having a fun experience. Like forced Mrp for example. Whatever meth you’re smoking to think I’m a giant pvp head is some good stuff!

**Comment by Iamgoofball** [comment]
apologies, there's been a lot of PVP fortnite gamers rolling in recently to gloat about thief's removal

**Comment by Palpetinus** [comment]
> where people aren’t forced to do something they don’t want to do or that gets in the way of them having a fun experience. Like forced Mrp for example.

Then untick Thief? I've done that after the third-ish time I've rolled thief and never looked back

**Comment by tuckerorchistra** [comment]
Thief? More like poop.

**Comment by tuckerorchistra** [comment]
But real talk, thief felt more like a crippled traitor than a special new antag, the objectives were pretty stale, and the thief couldn't really murder people. It probably could have been better if it was a special variant of the traitor where you stole things and sold them to the syndicate for tc or something. But there wasn't a reward for being the thief other than a greentext.

**Pull request merged**
