### PR TITLE
Revert "adds alternate medborg sprites"

### PR DESCRIPTION
**Pull request by Fikou**
wha

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
Do you no longer plan on maintaining this code?

**Comment by Fikou** [comment]
> Do you no longer plan on maintaining this code?

i do plan on maintaining this important code

**Comment by LemonInTheDark** [comment]
Author unresponsive to questioning, pr closed in favor of #54631

**Comment by MrDoomBringer** [comment]
kino

**Pull request closed without merging**
