### PR TITLE
Icebox Multi-z Chemistry Lab + Maintenance Areas (Wage Cage 2: Electric Boogaloo, now with maint bridges)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

This PR is the spiritual successor to #53939 , which was closed due to stale / merge conflicts. 

Moves the chemistry lab of icebox to the lower level, giving them more space to work. Adds in a extra maintenance surrounding the new chemistry lab area, including an awesome maint bridge. Also adds in the chemistry wage cage :tm: to the above level of medbay and does some minor remapping around it.
image

**PICTURES WITHIN:**
<details>
  <summary>Medbay Changes</summary>

Where the chemistry lab once was, there is now some maintenance / access points for the chemistry lab. Also, the wage cage.
image

Downstairs is the full chemistry lab.
image

Cryogenics and the aft hallway were remapped very slightly.
image

</details>

<details>
  <summary>Maintenance Changes</summary>

There is now a ladder in the area of maintenance between atmospherics, chemistry, and the hallway.
image

Downstairs is a general maintenance area with external access.
image

Further down the hallway, there's a maint room with some chemistry things.
image

This maintenance hall connects to the xenobiology maintenance hall via a !!maint bridge!! (heck yeah)
image

The area between service, chemistry, and the public mining storage recieved some fluff as they were almost touching.
image
</details>

MISC CHANGES:
- Split up aft maintenance due to it growing very large from xenobio to engineering. Half of it is now medbay maintenance (left of medbay + chemistry lab maintenance) and the other half is aft maintenance (right of medbay, left of xenobio, xenobio lower maintenance)
- ~~Fixes a maint door in aft maintenance that leads into the atmos HFR room that had the wrong access & name.~~

## Why It's Good For The Game

Expands the multi-z aspects of Icebox further, adding new maintenance areas and more room for chemists to create factories. 

The wage cage was well received last time, and only wasn't merged due to conflicts, but now it's back.

## Changelog

:cl: Melbert
add: Icebox Chemistry Lab is now multi-z'd, with maintenance changes to match.
fix: fixed a maintenance door in the icebox HFR room that had the wrong access / name
/:cl:

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
> Adds in a extra maintenance surrounding the new chemistry lab area, including an awesome maint bridge. 

just to ask, since i had a big PR to fix it on all maps up to now: is all walls surrounding maint in this PR given a maint area? for some reason relating to engravings or something, all walls that surround maintnence (including walls shared with depts.) need to be a maintnence area (the area wont affect any wallmounts in the depts so it wont break anything to do so)

just asking to make sure

**Comment by MrMelbert** [comment]
yep, I made sure all the maint areas extend to walls, I was aware of the maint area pr
image

**Comment by TheBonded** [comment]
what's in the animal crate in the maintenance area where chemistry used to be? and does this change affect the pharmacy at all? It seems like it'll be a longer walk to move from the pharmacy to the chemistry lab

**Comment by MrMelbert** [comment]
> 
> 
> what's in the animal crate in the maintenance area where chemistry used to be? and does this change affect the pharmacy at all? It seems like it'll be a longer walk to move from the pharmacy to the chemistry lab

- The crate is empty, just fluff
- The pharmacy is largely untouched, there's an access door + ladder to the lab pretty much the same distance as the walk was before

**Comment by Zytolg** [comment]
I love that you continued what I started with the Icebox Service rework. I just took a look at the mapdiff and the continuation feels natural, which is really as much as we could ask for on icebox. 
Great job on the exterior, that was my biggest concern in the case that this got picked back up. 

image

**Comment by Colovorat** [comment]
what one pipes? Can you route chem fab pipes to upper z level?

**Comment by notfrying1pans** [comment]
will wolves spawn and break open holes into chem?

**Comment by MrMelbert** [comment]
> what about pipes? Can you route chem fab pipes to upper z level?

There's a set of two plumping chem teleporters in the lab round start + a multitool so chemists can send chems upstairs

> will wolves spawn and break open holes into chem?

Perhaps.

**Comment by unit0016** [comment]
~~wheelchair mains crying as per usual~~

regardless nice to see this idea (Multi-z chem) done in a way that isn't absolutely garbage, even if I'd still prefer a lift existed. ~~Maybe get funky and put the actual chem machinery on the lift, I dunno.~~ Though I do slightly fear the bluespace machinery'll function more as a bottleneck (And may not even be the right way around at roundstart? Though I admit it's been so long since I've tinkered with it, I dunno.)

**Comment by Maurukas** [comment]
I'm impressed, this is really good work. Your camera coverage looks perfect, as do wiring and plumbing. All the APCs charge. I love the exterior details, I love the maint. 

In fact, I can only find a tiny handful of very minor things to complain about, which are mostly aesthetic. 
This door is on top of the primary connection to distro:
image

Your chemical recipients are anchored, but rotated the wrong way around. Having to fix these each shift will become a mild annoyance:
2021-09-15 16_32_00-Window

The multi-z trunk sprite seems to have issues. When rotated it converts to a standard trunk sprite, which looks like disposals is disconnected. Maybe slap a tile on it, or move it one tile up so you can use the unrotated object?

image

**Comment by AlinaStarkova** [comment]
"The multi-z trunk sprite seems to have issues. When rotated it converts to a standard trunk sprite, which looks like disposals is disconnected. Maybe slap a tile on it, or move it one tile up so you can use the unrotated object?"

thats normal and exists on every map everywhere else, the multi-z trunk only has a different sprite when rotated south, you can check sdmm as well, so either nobody actually sprited the other direction or the code that manages the sprites for it is incorrect. the better option for this one is to fix the spriting in code rather than change the mapping to accomodate visual issues with the code

**Comment by MrMelbert** [comment]
Moved the maint door off of the distro connection and rotated the chemical receivers

Didn't touch the trunks, since I assume the sprite is just a bug that can be fixed, given that other places on the map (service) look the same

**Pull request merged**
