### PR TITLE
[Metastation] MetaCargo: The Spring-Cleanening

### PR DESCRIPTION
**Pull request by junkgle01**
## About The Pull Request

cargoupdated4ithink

Changes the layout and design of meta cargo. 

Swaps the position of the QM office and warehouse and expands the cargo bay, leaving mining and the drone bay unchanged.

It does shift the vault area and disposals and upper cargo maints by one tile for a little more room in the QM's office and cargo bay, but otherwise unnoticeable. Removes the existing crate return flaps in lieu of a chute in the main cargo lobby.

## Why It's Good For The Game

Meta Cargo got it's last update around 4 years ago, and it's starting to show it's clunkiness in comparison to other maps like Wawastation, Delta, or Icebox. 

The cargo bay felt a little cramped and the QM's office felt kind of tacked on at the bottom and was sort of misshapen to fit the entrance of lower left maintenance into the cargo bay. In comparison to other maps, It felt very out of place, so my goal was to open up the space and have more space for cargo work and whatever else.

This also gives them a closer proximity to the Vault, and provides somewhat easier access into and escape from their office via maintenance. Also just adds a tad bit of flavor.

## Changelog
:cl:
add: Changes the layout of MetaStation's cargo to fit with new Nanotrasen guidelines.

/:cl:

### CODE REVIEW

**Review by MrMelbert — COMMENTED** [review]
image

These decals need to be updated now that there's no doors there

**Comment by MrMelbert** [comment]
Seems to be enough room to maintain the crate return chute, why not keep it? 

image

**Comment by SomeoneYouProbablyKnow** [comment]
People cannot stop re-mapping meta cargo bay. Why is it specifically meta cargo bay?

Anyway, looks nice, few points.
You changed the disposal conveyor belt to be fully inside cargo, removing the hallway-side access. I don't mind but don't understand why, it was a neat little path. Same for the glassdoor that used to lead to cargo from one of those conveyors.
You didn't touch the sec post at all and with the lathes and the warehouse being so far away now it's even more useless (not like it saw much use to begin with)
Speaking of lathes and that little lathe area, it's neat but the 1x1 alcove left of the lathe feels a bit awkward.
Cool QM office location, it's a shame the requisition console is below it, i think you can see from the office but barely maybe there's something to be done there.

Now minor stuff. Left maint door has a lightbulb on it.

**Review by MrMelbert — COMMENTED** [review]
image

Should use the diagonal floor tiles if you're gonna use the diagonal decals. Also I think the trimline on top of the diagonal design doesn't look super good (opinion)

**Review by MrMelbert — COMMENTED** [review]
Cardinal sin 

image

image

image

**Comment by junkgle01** [comment]
> Cardinal sin
> 
> image
> 
> image

they're on opposite sides of the wallll 😭

**Comment by MrMelbert** [comment]
> they're on opposite sides of the wallll 😭

AIs (and observers) can see both sides of the wall at once 😉

**Comment by junkgle01** [comment]
> > they're on opposite sides of the wallll 😭
> 
> AIs (and observers) can see both sides of the wall at once 😉

it's so over....  they must go 😔

**Comment by junkgle01** [comment]
> Seems to be enough room to maintain the crate return chute, why not keep it?
> 
> image

i didn't really like the one windoor into cargo bay you could access by just moving under the flaps, but wanted to encourage more back and forth between cargo and a rowdy assistant by just having a chute that throws them into the little trap that is the disposals chute belt. also i like dragging the crates to the belt by hand personally haha

**Comment by MrMelbert** [comment]
> i didn't really like the one windoor into cargo bay you could access by just moving under the flaps, but wanted to encourage more back and forth between cargo and a rowdy assistant by just having a chute that throws them into the little trap that is the disposals chute belt. also i like dragging the crates to the belt by hand personally haha

It seems rather inconvenient to have to drag a crate from the belts, through the 1-tile-corridor by the entrance, and then around the railings to the loading zone, idk. 

You could just remove the windoor and flaps and leave it as a chute: 

image

**Comment by junkgle01** [comment]
> People cannot stop re-mapping meta cargo bay. Why is it specifically meta cargo bay?
> 
> Anyway, looks nice, few points. You changed the disposal conveyor belt to be fully inside cargo, removing the hallway-side access. I don't mind but don't understand why, it was a neat little path. Same for the glassdoor that used to lead to cargo from one of those conveyors. You didn't touch the sec post at all and with the lathes and the warehouse being so far away now it's even more useless (not like it saw much use to begin with) Speaking of lathes and that little lathe area, it's neat but the 1x1 alcove left of the lathe feels a bit awkward. Cool QM office location, it's a shame the requisition console is below it, i think you can see from the office but barely maybe there's something to be done there. Left maint door has a lightbulb on it.
> 
> But all in all lookin nice

i'm not sure what you mean about the req console.. could you please clarify? also please see above comment for crate chute

not entirely sure what to do about the sec outpost. i think it's fine as is? I don't see how lathe usage ties into it

**Comment by junkgle01** [comment]
> > i didn't really like the one windoor into cargo bay you could access by just moving under the flaps, but wanted to encourage more back and forth between cargo and a rowdy assistant by just having a chute that throws them into the little trap that is the disposals chute belt. also i like dragging the crates to the belt by hand personally haha
> 
> It seems rather inconvenient to have to drag a crate from the belts, through the 1-tile-corridor by the entrance, and then around the railings to the loading zone, idk.
> 
> You could just remove the windoor and flaps and leave it as a chute:
> 
> image

gah, okay alright

 poor little loads-the-crates is about to get erased forever

**Comment by EEASAS** [comment]
from what the errors show:
Space turf /turf/open/space/basic found in non-allowed area (/area/station/maintenance/port/fore) at Fore Port Maintenance (63,168,2)! Please ensure that all space turfs are in an /area/space!
you have a space turf in some maintenance area OR have a maintenance area in space. check for any errors

**Comment by junkgle01** [comment]
> from what the errors show: Space turf /turf/open/space/basic found in non-allowed area (/area/station/maintenance/port/fore) at Fore Port Maintenance (63,168,2)! Please ensure that all space turfs are in an /area/space! you have a space turf in some maintenance area OR have a maintenance area in space.

should be fixed!

**Comment by Dawnseer** [comment]
Bit sad that as a cargo tech, I'd have to leave cargo to enter upper maintenance to get to disposals to activate it, but other than that, looks neat.

**Comment by junkgle01** [comment]
> Bit sad that as a cargo tech, I'd have to leave cargo to enter upper maintenance to get to disposals to activate it, but other than that, looks neat.

wdym by this? is there a switch i missed that lets u turn on the maint disposals belt? if so i can re-add it i was just never aware it was there in the first place

**Comment by Dawnseer** [comment]
> > Bit sad that as a cargo tech, I'd have to leave cargo to enter upper maintenance to get to disposals to activate it, but other than that, looks neat.
> 
> wdym by this? is there a switch i missed that lets u turn on the maint disposals belt? if so i can re-add it i was just never aware it was there in the first place

Nah, the direct route is just not accessible to the tech, now. QM gets that maint entrance

**Comment by RedBaronFlyer** [comment]
My only ehs are that you can still stupidly easily break into the cargo bay via unwrenching the orm (granted this is a code issue not a map issue), area with the lathes and forms seems like a massive traffic clog area, depending on if there's five techies and a QM walking around, and the aforementioned loss of a direct path to maints north since the dronebay is up there (granted, I only know like, two people who use drones even somewhat regularly)

Personally, I kind of like the current cargo bay better, but this one still looks really good!

**Comment by junkgle01** [comment]
> My only ehs are that you can still stupidly easily break into the cargo bay via unwrenching the orm (granted this is a code issue not a map issue), area with the lathes and forms seems like a massive traffic clog area, depending on if there's five techies and a QM walking around, and the aforementioned loss of a direct path to maints north since the dronebay is up there (granted, I only know like, two people who use drones even somewhat regularly)
> 
> Personally, I kind of like the current cargo bay better, but this one still looks really good! The current metastation cargo bay is a bit cramped compared to some of the others, especially now that there's upwards of five CTs running around.

i could tack on another windoor that's ct access only behind the orm like it has on icebox if you'd like. not really sure how to fix the drone bay issue besides adding a maint door next to the golden QM statue, but that feels like way too many maint doors in such a small area. i guess the lathes could be a traffic clog area, but i really like the visual of having the lathes on a little upstairs area overlooking the bay

**Comment by EricZilla** [comment]
Maybe remove the maint door from QM and put it next to the statue?

**Review by Maurukas — CHANGES_REQUESTED** [review]
The cargo lobby is missing an air alarm and apc. Get that, resolve the conflict and you're good to go.

**Review by Maurukas — COMMENTED** [review]
Waiting for the author to get his internet back. Local fiber line had an encounter with a back hoe.

**Comment by junkgle01** [comment]
okay, not sure what's going on. merge conflicts should be resolved but mapdiffbot isn't playing nice

**Comment by junkgle01** [comment]
or maybe i just don't understand how it works, unsure

**Comment by junkgle01** [comment]
honest to god have no clue what the problem is. if anyone could enlighten me that would be greatly appreciated

**Review by Maurukas — COMMENTED** [review]
Please push an empty commit or merge master and push to force Mapdiffbot to rerun. It has been fixed.

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
