### PR TITLE
DeltaStation 2.0

### PR DESCRIPTION
**Pull request by Okand37**
Updated to version 2.0, complete (hurray) version!
Map can be found here: https://drive.google.com/file/d/0B67Y0cE3wQneTXJVVjJVVXluT0U/view
Forum topic is located here: https://tgstation13.org/phpBB/viewtopic.php?f=11&t=7172&view=unread#unread

Please post bugs, issues, and oversights in the comments below.

### CODE REVIEW

**Comment by Cobraman202** [comment]
Medical break room does not have any lights.

**Comment by Cobraman202** [comment]
Rnd has no windows on the tables. Also, it lacks shutter controls so they can't close their shutters

**Comment by ChangelingRain** [comment]
YOU'RE'VE MESSED IT UP

**Comment by Okand37** [comment]
It should work. Fingers crossed!

**Comment by Okand37** [comment]
After the second successful playtest, a number of reported bugs, issues and oversights have been fixed and missing content has been included. A rough idea of what was fixed/changed:
Fixed a number of APCs with no external breaker
Increased engineering SMES charge at roundstart from 1.5e+006 to 2e+006
Added janicart pimpin ride keys
Fixed access issues in engineering foyer and throughout atmospherics
Fixed access issues with medbay storage
Fixed access issues rendering gulag prisoners unable to leave the transferring center after serving their sentence.
Fixed flashes being /assembly instead of assembly/handheld
Fixed tiles out of telecomms sharing the in-telecomm tiles, causing station-wide mass lag and temperature+oxygen issues.
Added air alarms in central, aft, port and starboard hallways.
Fixed stray intercom in central hallway being pix y-26 instead of pix x-26

To do:
Add door button to main medbay entrance doors on interior side
Fix fore starboard solar tracker not registering(?)
Add APCs to all solars
Properly set vents in xenobiology killroom, telecomms and research server room to keep the rooms cold
Address any further issues below that were not previously addressed.

**Comment by MrStonedOne** [comment]
no escape!

**Comment by optimumtact** [comment]
I believe we should remove an existing map in favour of this.
Either Dream or EFF, as neither are well maintained, nor popular.

**Comment by dannno** [comment]
Orange is a genius 
slay EFF and put superior delta station instead

**Comment by Okand37** [comment]
After a third fairly successful testplay, as well as getting to witness the ever fun exploding supermatter engine, a number of reported bugs, issues and oversights have been fixed and missing content has been added.

Engineering foyer doors have been fixed and should be accessable
Atmospheric solar doors have been fixed and should respond to atmospheric level ID access
Pipes leading into and out from gas chambers have been fixed
Additional O2/fire closets have been added to the aft hallway and escape area.
A stray fire extinguisher in the aft hallway has been corrected
An air alarm has been added to the fore hallway
Cargo doors have been fixed and no longer require both mining and cargo access, simply one or the other
Cargo office and cargo security point APCs have been connected to the grid
Engineering security point APC has been connected to the grid
Roboticists can now operate the shutters in the mech bay, and a desk windoor has been added to the desk
Loading door buttons have been added to the interior side of the loading doors area, infront of the cargo console
Service hall is now accessible by all members of the service department
Corrected the teleporter shutter control being accessible by any crewmember, and it is now set to generic heads access
Bookcases in the library now spawn with books in them
A room in maintenance has been changed
Updated the mining dock with pickaxes, shovels, a welding tank, ore box and o2 closet
Added gas canisters to the education chamber
Added yucky cockroaches to maintenance
Fixed a few lattices attaching to corners of the gulag shuttle as well as the mining shuttle
Added deputy armbands to the security office
Added seclites and sechailers to the warden's office
Changed the tables from regular to reinforced in E.V.A.
Filled the rest of the corporate lounge table to look more occupied
Added a table to the fitness room, hopefully wrapping up the fore portion of the room to look less empty
Added a disclaimer to the holodeck operating room
Added a secret
Added o2 closets to a few external airlocks, provided they had room
Removed holobarrier from transit tube access
Filled the rest of the atrium tables to appear more occupied
Added a cherry jelly filled donut to the security office

**Comment by Metacide** [comment]
Just had a stellar round on here, really does seem great. Particularly excellent for highpop with lots of chaos, I think. A few more departmental direction signpost things and perhaps a wallmap would be good additions, but it seems incredibly solid already.

👍  x 💯

**Comment by Arianya** [comment]
I know you're aware of the camera network not being setup yet but the AI job is still enabled, so it may be worth doublechecking so poor AIs don't try to deal with being gimped 👍 

Map is really good overall!

**Comment by Okand37** [comment]
Today's to do list includes but is not limited to:
Post more departmental direction signs at cross-section intervals (central to port/central to starboard halls)
Fix the research lab's doors not all properly reacting to a roboticist level ID
Fix vents in xenobiology killroom, telecommunications room and server room to properly keep the rooms a chilly delight
Add a limbgrower to the medbay
Remove auxiliary E.V.A. testing room and subsequently think of something to replace it with
Add two additional E.V.A. suits to E.V.A.
Add a tank dispenser to atmospherics
Procrastinate on finishing the camera network
Procrastinate on creating the navigation beacon network
Slightly rebalance some portions of maintenance
Add an additional hardsuit to engineering gear stoage(?)
Finish placing windoors around desks across the station where they belong
Fix the windoors on the hydroponics desk opening inward opposed to outward
Possibly(?) add a turbine around somewhere...
Work on making a functioning station map to help lost spacemen navigate the hulking mass of metal that is deltastation
Increase the roundstart charge of the supermatter's SMES from 1.5e+006 to 2e+006 to match the regular engineering ones
And more!

**Comment by jughu** [comment]
Xenobiology has no water tanks biobags or a proper cold room

**Comment by Okand37** [comment]
Xenobiology does have a water tank, it is in the back room where the air supply is kept. I'll add biobags and the cold room was just addressed above.

**Comment by jughu** [comment]
Why the backroom? What if my extinguisher ran out of water and a slime is eating the rd i have to run the whole way to the back room?

**Comment by Okand37** [comment]
Because its a storage supply. There are also roughly 4-5 fire extinguisher cabinets, two fire extinguishers on the watertank, and a mini fire extinguisher in the xenobiology area.

**Comment by jughu** [comment]
Is there atleast 2 tanks in the backroom? Incase someone wants to do oldschook xenobiology

**Comment by Jordie0608** [comment]
It's not too important currently but you should look into how to use the map merger so your map commits don't have 20k line diffs each since it'll matter if the map is merged into the codebase.

**Comment by optimumtact** [comment]
This map is not box and therefore I am obligated to hate it

**Comment by Dorsisdwarf** [comment]
The version live on the shuttle cant be changed to

**Comment by Lakart** [comment]
Chemistry has all the components for grenades except the casings themselves or anything to craft them out of

**Comment by dannno** [comment]
👍 👍 👍

**Comment by dannno** [comment]
please a mass driver
I don't see a good reason for there not to be one
it only adds potential to the map, having one removes nothing
mass driver has driven many fun rounds I've played

**Comment by KorPhaeron** [comment]
This is popular and it works fine you can tweak minor stuff later

**Comment by calzilla1** [comment]
Replace pubby with this

**Comment by optimumtact** [comment]
remove pubby, dream and eff

**Pull request merged**
