### PR TITLE
Wizard Shapeshift now converts damage taken while transformed 

### PR DESCRIPTION
**Pull request by MMMiracles**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: MMMiracles
tweak: Wizard shapeshift now converts damage taken while transformed
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

wizard doesn't need 2 health bars where one can be refreshed constantly ok thank you ok i died ALRIGHT

### CODE REVIEW

**Comment by 81Denton** [comment]
Doesn't that also apply to lavaland ass drake transformation?

**Comment by imsxz** [comment]
why not have convert damage on dragon form? that shit has like 300 HP and gets insane mobility and ranged offense

**Comment by subject217** [comment]
meant to get around to doing this, thank you mmm 👍

**Comment by Shadowflame909** [comment]
> 
> 
> why not have convert damage on dragon form? that shit has like 300 HP and gets insane mobility and ranged offense

I believe it's 200. So only 100 more than a human, and it has none of the laser gun resistance that an ash drake has. So you can quickly just lethal that large hitbox to death.

**Comment by Tlaltecuhtli** [comment]
is it a % transfer or a number?

**Comment by Borisvanmemes** [comment]
@imsxz It only has 200 HP.

**Comment by MMMiracles** [comment]
@imsxz because this is balancing the version the wizard uses, not changing anything else because that's for another PR

**Comment by fludd12** [comment]
:D
People are using my code!

Anyway @tlaltecuhtli it is percentage based, and works both ways. This might be a pretty severe nerf.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
