### PR TITLE
Removes stuns from flashbang sound.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Having an AOE stun only viably counterable by limited equipment found in the brig, on the captain, or on sec officers, is pretty bullshit.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
ooh controversial 
:+1:x:100:

**Comment by Dorsisdwarf** [comment]
RIP flashbangs.

**Comment by Archie700** [comment]
Calling it, "i ded" tag

**Comment by Aloraydrel** [comment]
adios meme bangs

**Comment by Zilenan91** [comment]
I too am sick of Mekhi carrying boxes and boxes of flashbangs

**Comment by PKPenguin321** [comment]
This is fine

**Comment by Shapsy** [comment]
Don't nerf all of sec just because one player who abuses loads of other mechanics abuses this mechanic too, just deal with the problem player.

**Comment by Anonmare** [comment]
Sound should disorientate tbh

**Comment by KazeEspada** [comment]
@Shapsy That's your job.

**Comment by Eaglendia** [comment]
@KazeEspada >banning people for playing the game

Is this grudge code? :-1:
Flashbangs haven't been a problem for a long time now. There are good and bad ways to use them, and they're one of the few tools in the game that has legitimate counterplay options.

**Comment by Supermichael777** [comment]
yeah make sound just make people deaf and stumbly else its useless due to sunglasses

**Comment by Zilenan91** [comment]
Actually yeah, don't remove the stun just make it make people stumble for a long time

**Comment by lzimann** [comment]
rename them to flashes then. Since the bang is useless

**Comment by Lumipharon** [comment]
This will severely nerf flashbangs. Anyone with sunglasses/welding mask/hardsuit will be able ignore flashbangs effectively - even if you add confusion to it, they can still stand there and shoot you.

Also earmuffs spawn in multiple areas outside of sec, git gud.

**Comment by Fox-McCloud** [comment]
There's earmuffs in engineering and science both---at the most, this should still cause you to drop whats in your hands AND induce confusion--otherwise, flashbangs are going to be useless.

**Comment by PKPenguin321** [comment]
>This will severely nerf flashbangs. Anyone with sunglasses/welding mask/hardsuit will be able ignore flashbangs effectively

That is fine. That is how flashes worked back when they stunned, and they were still used extremely often in arrests. You have to realize that most of the crew won't have eye protection, and that most available eye protection (welding gear) obscures vision, meaning you can stand just on the edge of their screen and snipe them with no resistance.

**Comment by Lumipharon** [comment]
Sunglasses are common as fuck, sometimes I'll find 5 pairs in maint.
Vision reduction from unlimited welding gas masks is zero issue because all you need to do is toggle it down before it explodes, then pop it back up.
And of course everyone in a hardsuit can simply laugh them off.

**Comment by PKPenguin321** [comment]
>Sunglasses are common as fuck, sometimes I'll find 5 pairs in maint.

anecdotal and not even always true

>Vision reduction from unlimited welding gas masks is zero issue because all you need to do is toggle it down before it explodes, then pop it back up, and even when toggled down you can still see enough to shoot people with no issue.

**Comment by Bawhoppen** [comment]
actually sunglasses are pretty common @PKPenguin321 I have to agree with lumi on that

**Comment by PKPenguin321** [comment]
well if anything they'll be much less common after your maint loot table addition gets merged @Bawhoppen

**Comment by Bawhoppen** [comment]
@PKPenguin321 even in fixed spawn points though they're pretty common

**Comment by PKPenguin321** [comment]
i can't speak for metastation but honestly besides the bartender and QM (and sec and heads of course) i can't really think of fixed sunglasses spawns

**Comment by Bawhoppen** [comment]
theres fixed sunglasses spawns in maint on box

**Comment by PKPenguin321** [comment]
where? asking for a friend :)

**Comment by Bawhoppen** [comment]
one right above the bar in maint iirc

**Comment by Zilenan91** [comment]
Nope. There isn't one above the bar in maint.

**Comment by Bawhoppen** [comment]
its in a locker

**Comment by Lumipharon** [comment]
On box they're ony random spawns, but they are common, but as said before, unneeded.

**Comment by PKPenguin321** [comment]
again, they won't be nearly as common with bawhoppen's PR, and if it really is an issue (protip: it's not. we had guaranteed sunglasses spawns back when we had flashes that could stun and it wasn't an issue then either) we can lower their chances or remove them all together from the maint table

**Comment by Bawhoppen** [comment]
there used to be a fixed sunglasses spawn there, strange

**Comment by optimumtact** [comment]
You of all people should know this is a bad idea

**Comment by Core0verload** [comment]
The problem here is a single shithead player, not flashbangs. Just ban the player and let flashbangs be.

**Comment by optimumtact** [comment]
Once I realised this was removing the stun from lacking ear protect I changed my mind on this

:+1: from me, they were fine when they were just an eyeflash stun

**Comment by Incomptinence** [comment]
No no no no.

Stop rev/tider buffing. Death to mob scum. 

Oh boy I can't wait for numbers always wins combat just like that notably tactically deep game EVE online, entitled bloody civilians.

**Comment by PKPenguin321** [comment]
you cuck
if you are genuinely using flashbangs on a mob, odds are that most of them wont have flash protection
don't meme me by saying otherwise. you know what i say is true deep within your soul

**Comment by MMMiracles** [comment]
i play csgo and i always look at flashbangs when i throw them and i never fall over from it.

turning your character around to negate the blinding effect of flashbangs when?

**Comment by Bawhoppen** [comment]
>implying csgo is realism

**Comment by KorPhaeron** [comment]
I don't like flashbangs but I think this PR is going about it in the wrong way. You made the gear check less strict, but it's still an aoe stun gearcheck that security is immune to.

If anything flashbangs should still blind/confuse/deafen you through protective gear so you have to actually throw them into rooms instead of running at people holding them.

**Comment by Lumipharon** [comment]
They used to do that but when HG made the stun nerf he never bothered to look at how flashprotection works, making sec immune.

**Comment by Shadowlight213** [comment]
An alternative proposed nerf was to make bowmans not give protection from the bang, but instead give sec earplugs. Earplugs would slightly lower your hearing range, and you couldnt wear earplugs and radio.
That would make sec have to be prepared if they planned to use flashbangs, rather than having the protection being always on.

@KorPhaeron I was worried that nerf would be too strict, however I can change it to that.

**Comment by Lumipharon** [comment]
just make flashbang protection 100% effective, it was a dumb, unintended change that made flashbangs way safer to use (this is compared to when officers literally just kept them in their hands till they went off and cucked everyone else for double duration)

**Comment by Shadowlight213** [comment]
@Lumipharon what? The protection is already a hard protect.

**Comment by Core0verload** [comment]
Just make flashbangs stun everyone in 1-tile radius regardless of protection.

**Comment by Zilenan91** [comment]
Just make flashbangs give you drunk movement for a long time if you don't have ear protection

Also remove bowmans

**Comment by Lumipharon** [comment]
@Shadowlight213 
>just make flashbang protection **not **100% effective

**Comment by Nanotransistor** [comment]
:+1:  Maybe it's time for sec to get good and do some work when taking down revs and mobs in general.

**Comment by Malkevin** [comment]
>They used to do that but when HG made the stun nerf he never bothered to look at how flashprotection works, making sec immune.

Sec isn't immune, if they go off in your hand or at your feet you'll be stunned the full 18 seconds, same as anyone else.
Which is a far bigger disadvantage than the old flashbangs which would go off two tiles around you and stun you but only for half the time as other people - making cooking a bang in your hand whilst chasing after a son of a bitch a very viable tactic as you'd stun them 18 seconds and you'd only be stunned for 9 - giving you plenty of time to jump up and twat them with your baton or prenerf non-garbage taser.

**Comment by GunHog** [comment]
No half-trained Sec player blows it in their hand any more. He will just cook it in his hand, then throw it at the last second, leaving the target near-zero response time. Robstin stomped me using this tactic more than once.

**Comment by Nanotransistor** [comment]
Think a better idea is just to remove flashbang protection from everything other than hardsuits. They should be situational.

**Comment by Steelpoint** [comment]
inb4 merge despite massive opposition.

**Comment by CosmicScientist** [comment]
This reads as if without forethought; knee jerk.

**Comment by PKPenguin321** [comment]
This isn't that bad. A vast majority of the crew will still be vulnerable to flashbangs. Secbabies with no skill just don't want their ez AoE stun button nerfed in any way. :ok_hand:

**Comment by Lumipharon** [comment]
@Malkevin 

I am aware of that malk.
However the old system was far better - even though sec had a ADVANTAGE over people without protection, they were still stunned, which made them vulnerable to 

A: things that are stun immune (hulk etc)
B: Things that can reduce stuntimes (drugs/adrenal implant etc)
C: People that weren't in range when it went off

There is a **HUGE **difference between not being stunned at all, and being stuned for half the duration.

**Comment by KorPhaeron** [comment]
To reiterate: AoE gear check weapons that their users are immune to are stupid. This PR does not change that while still managing to rile everyone up.

I will accept a flashbang change that either

-Removes the stun, replacing with long blinds (That are lessened, but not removed, by eyewear), and maybe confusion/deafness from the bang (again mitigated by protection, but not outright removed)

or

-Keeps the stun, but don't allow anyone full immunity from it

Basically anything that stops it being a "I'm immune to my own explosion!" weapon that you can chuck into the middle of your team with abandon

**Pull request closed without merging**
