### PR TITLE
Joins the NTNet Receiver and the NTNet Request components into one NTNet component.

### PR DESCRIPTION
**Pull request by TheSmallBlue**
## About The Pull Request

So now that NTNet components actually work, I thought it'd be way nicer for people planning on making future radio-like components and players to join both components.

All features from the previous components have been retained. For example, you can still choose the data type of the output:

EMHo29SZZd
(this is not very impressive i just like posting gifs and videos in my PR's cus i think they look cool)

And unlike the first time the NTNet components were first merged, these work right out of the gate because I did a nifty little thing called "testing it"

https://user-images.githubusercontent.com/24967815/130277046-3b7a2908-8ac9-4709-a589-ebefed330bce.mp4

## Why It's Good For The Game
Makes the NTNet component more like the radio component, which was very intuitive.

## Changelog
:cl:
refactor: The NTNet Receiver and Request components have been merged into one single NTNet component
/:cl:

### CODE REVIEW

**Comment by TheSmallBlue** [comment]
Dunno if the QOL changelog tag also fits into this, should I put both in there?

**Comment by Colovorat** [comment]
i don't like it. it's too big

**Comment by TheSmallBlue** [comment]
It's not about the size, it's about what you can do with it

**Comment by Colovorat** [comment]
> It's not about the size, it's about what you can do with it

same thing as before but now it looks bigger?

**Comment by TheSmallBlue** [comment]
It was a dick joke

**Comment by Mothblocks** [comment]
I don't really like this, I prefer the components to be granular. The radio component as both sender and receiver is more justifiable to me just because it's really small, but NTNet transmitters combining just doesn't look great.

**Pull request closed without merging**
