### PR TITLE
Adds vacant commissary to BoxStation, moves det office to sec

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
tweak: On BoxStation, there's a vacant commissary where detective office used to be. Detective office is now located where Law Office was, and Law Office has been moved to the adjacent Vacant Office B.
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
lmao we had the detective where vacant office b is now it goes to lawyer office and lawyer to vacant A

**Comment by MegaEmpirical** [comment]
I love the commissary addition. The best greytide use of aux was when they made a little shop out or bar of it so this let's them do it with less greytide.

**Comment by optimumtact** [comment]
guys who gives a shit if the detective is moved or not it's not a big deal

**Comment by Grazyn** [comment]
Having the det office far away from sec didn't stop detectives from behaving like sec officers so...

**Comment by BeeSting12** [comment]
yall are acting like this changes how the detectives acted when in reality it lead to the occasional confused ahelp about where the dets office was.

**Comment by ExcessiveUseOfCobblestone** [comment]
funny how the least favored map has this change to improve det behavior but delta and meta, the two more "popular" ones both have det's office beside if not IN security.

**Pull request merged**
