### PR TITLE
Fixes bane runtimes

### PR DESCRIPTION
**Pull request by AnturK**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Bane?!

**Comment by Anonmare** [comment]
You don't get to bring sins

**Comment by InsaneHyena** [comment]
If this PR gets closed, will you die?

**Comment by QualityVan** [comment]
Was getting merged part of your plan?

**Comment by Anonmare** [comment]
Tell me about the Devil, why does he do the dance?

**Comment by lordpidey** [comment]
Whoops.  That's my fault.

**Comment by Spacedong** [comment]
>this PR

**Comment by Hatfish** [comment]
Well congratulations, you opened your PR.  Now what's the next step of your master plan?

**Comment by Anonmare** [comment]
@Hatfish Merging this PR with no conflicts

**Pull request merged**
