### PR TITLE
Adds toggle wire to emitters

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request
This PR adds a "toggle" wire to emitters that switches them on/off when pulsed.

## Why It's Good For The Game
This lets players be more creative with emitters, for example by remotely shutting down the SME emitters.

## Changelog
:cl: Denton
tweak: Added a third wire to emitters that toggles them on/off when pulsed.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
What happens when this wire is cut? Does it disable the firing of the emitter?

**Comment by PKPenguin321** [comment]
It should prevent it from being toggled at all so you can hardware-lock emitters on

**Comment by 81Denton** [comment]
hmm yes good idea

**Comment by 81Denton** [comment]
Just checked, calling interact() will give you error messages about unsecured emitters, even if you pulse the wire from the other side of the station. I'll rewrite this so it's less of a hack job and then open another PR.

**Pull request closed without merging**
