### PR TITLE
Veil Render Fix + spellbook balance

### LINKED ISSUE #12995: Veil Renders are fucking hilarious (but overpowered)
Veil renders make mini Nar-Sies that turn everything into cult tiles and people into harvesters. While this is funny, five of them are not.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Veil Render now spawns a wizard styled singulo instead of a mini nar-sie.

Veil Render now has a limit of 2 per spellbook.

Supermatter sword now costs 6, which leaves you with 2 points to spend on rad protection, and 2 points to spend on recall (or a spell, and have no way to get your sword back when you lose it).

Fixed the supermatter typo

Fixes #12995

### CODE REVIEW

**Comment by KorPhaeron** [comment]
And yes I actually tested this new singulo

**Comment by Cheridan** [comment]
>And yes I actually tested this new singulo

#whoa

**Comment by WJohn** [comment]
>Wizard styled singulo.

Come on dude, really? What is this thing? Looks like a choppy and broken up screengrab of code.

**Comment by Shadowlight213** [comment]
Yeah, the sprite looks really really shitty. :-1: for sprite.

**Comment by Niknakflak** [comment]
At least its not narsie :+1:

**Comment by KorPhaeron** [comment]
Was supposed to be a joke about tear in reality obviously people dislike the execution

**Comment by KorPhaeron** [comment]
Can just make it use the normal singulo then

**Comment by Jalleo** [comment]
Make it a smaller version of the supermatter sing stage 6 that cant dissipate

**Comment by PKPenguin321** [comment]
sprite for reference
wizard singulo

**Comment by Shadowlight213** [comment]
Actually, seeing it animated it doesn't look that bad. Changing to a :+1:
Although having it show its own code rather than generic world load code would be better.

**Comment by Iamgoofball** [comment]
:+1:

**Comment by KorPhaeron** [comment]
I thought world.dm would be most appropriate for the fabric of reality.

My own code is something I never want people to see

**Comment by optimumtact** [comment]
that's fucking glorious I love it

**Comment by KorPhaeron** [comment]
@duncathan 

Mergebegging

**Comment by duncathan** [comment]
wjohn's final verdict on the sprite was "whatever" and general opinion in here seems more positive than negative sooo

**Comment by WJohn** [comment]
Hopefully someone will make something more tolerable than that in the future.

**Comment by Chocobro** [comment]
muh coder jokes

**Pull request merged**
