### PR TITLE
Slaps some symbols on those medkits

### PR DESCRIPTION
**Pull request by AdipemDragon**
## About The Pull Request
image
This gives the 5 medkits that specialize in specific damage types more distinct symbols in place of their usual white cross:
a toolbox for brute, a flame for burn, O₂ for oxigen, a skull for toxin and an exclamation for the advanced kit.

If there's any better ideas for what to replace the symbol with I'm all ears.

## Why It's Good For The Game
image
People being able to (hopefully) be able to see the difference between different medkit types if color vision is impared, ingame or otherwise, is a pretty good thing, I think.

## Changelog

:cl:
imageadd: Specialized medkits have some new distinct symbols to aid in distinguishing them on the spot.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
god i love that toxins one

**Comment by Farquaar** [comment]
I like

**Comment by AdipemDragon** [comment]
> I feel like brute could be a blood drop or something similar, since it took me a while to realize it's a toolbox, and even then it's a little ambiguous. Just my opinion though.

image
 Dunno, a blood drop's pretty close to a flame, shapewise

**Review by Twaticus — CHANGES_REQUESTED** [review]
medkit_advanced has a stray pixel

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
