### PR TITLE
Allows admins to scan circuits + more logging

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Dax Dupont
admin: Admins can now scan circuits if they have admin AI interaction enabled.
admin: some more circuit logging
/:cl:

Easier than using VV to add keys to assemblies and what not. Admin interaction should just be able to scan it.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Don't really understand your reasoning?

**Comment by 81Denton** [comment]
@PKPenguin321 circuitry = skub

**Comment by ExcessiveUseOfCobblestone** [comment]
Thanks anon, now I too can partake in epic meme machines!

**Comment by Arianya** [comment]
@PKPenguin321 #38588

**Comment by PKPenguin321** [comment]
How does letting admins scan any circuit as a ghost fix or even help aid that issue in any way?

**Comment by DaxDupont** [comment]
Because if there's a scenario where something is a foot, we can take a suspect assembly and clone in to figure out if it's doing something non-kosher that isn't properly logged. 

It's not like this is new functionality, it's just easier to do it now.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
