### PR TITLE
NumberInput for atmos machines

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Replaces some set value buttons on atmos machines with the new NumberInput component.
This is what this looks like:
image
image
image
They work like this:
https://cdn.discordapp.com/attachments/326826573951008769/637577237989818368/2019-10-26_02-02-41.mp4

## Why It's Good For The Game

The real edge of using a surgical update templating engine actually becomes apparent

## Changelog
:cl:
tweak: Atmos machines now use NumberInput: Slick in ui setting of values
/:cl:

### CODE REVIEW

**Comment by stylemistake** [comment]
Rebased on top of current master, removed all tgui builds while this is a work in progress.

Also improved `NumberInput` as you said, by adding:

- `animated` boolean prop.
- `format` prop, which accepts a `value => value` function for value formatting.
- Suppresses value flicker when releasing the control. Not configurable.

Do not use animated props unless you really need to, because value animations are expensive (they are constantly updating at a rate of 30 FPS, and in something like an AirAlarm, this would cook toaster-tier PCs.

**Comment by stylemistake** [comment]
@actioninja atmos control console inputs don't work for some reason.

**Comment by stylemistake** [comment]
> webedit pro

absolute madman

**Comment by actioninja** [comment]
I'm using tilt controls!

**Pull request merged**
