### PR TITLE
Fixes Adminorazine killing ash lizards

### LINKED ISSUE #37837: Adminorazine makes ash lizards unable to breathe
I forgot to submit this a few days ago when it happened.  Anyway it was summon events, and I was changed into an ash lizard, and then the healing event happens, I am filled with adminorazine and I can't breathe and suffocate.

### PR DESCRIPTION
**Pull request by ShizCalev**
fixes #37837

:cl: ShizCalev
fix: Adminorazine will no longer kill ash lizards.
fix: Adminorazine will no longer remove quirks.
/:cl:

### CODE REVIEW

**Comment by YPOQ** [comment]
I don't think this will work because NOBREATH is a species trait, not a roundstart trait.

**Comment by ShizCalev** [comment]
oh fuck nice catch.

**Comment by imsxz** [comment]
does this fix it killing/removing space immunity/removing the ability to speak from zombies, skeletons, abductors, golems, etc? This bug has killed me loads on wizard rounds with events summoned, as I'll get changed to one of the mentioned species, and later getting adminordrazine from the invincibility event.

**Comment by ShizCalev** [comment]
Yes

**Pull request merged**
