### PR TITLE
Ports tkdrg's library computer caching system. 

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This helps mitigate lag caused by the computer grabbing meta information about almost **two thousand books** over sql on EVERY load of the library computer interface

A list of books is maintained as a global var. The generated menu from the books is maintained as a per computer var since it needs to have the computer's src reference in it.

The first load will generate about 0.7 seconds lag with 1700 books, but all loads after that take about 0.017 seconds.

These numbers may be higher or lower depending on database setup for downstream servers and the main servers.

One downside is that uploaded books won't be printable until the next round. But i'm ok with this.

This is a repull of #6555 since he deleted his branch.

### CODE REVIEW

**Comment by hornygranny** [comment]
yolomerge

**Comment by ike709** [comment]
YOU DID NOT WAIT 24 HOURS

**Comment by Dorsisdwarf** [comment]
HE HAS DEVALUED THE SYSTEM

**Comment by Giacom** [comment]
>One downside is that uploaded books won't be printable until the next round. But i'm ok with this.

And why can you not add the new book to the cache?

**Comment by RemieRichards** [comment]
Yeah there was originally a cache update in tkdrg's PR.
why was that removed here?

**Comment by MrStonedOne** [comment]
It was removed because the cached formatted html needs to be stored per-computer as it needs to have the right src address in the order links.

When i was working on porting this and fixing that bug, I was faced with a choice. Refactor the upload code to clear the cache from all computers or something else, or... just.... not.

The way i figured it, if you had the book to upload, you didn't need to be able to see it in the external archive.

It seemed like too much effort for almost no gain.

**Pull request merged**
