### PR TITLE
the express supply console now requires general cargo access instead of QM access

### PR DESCRIPTION
**Pull request by AIUNBOLT**
## About The Pull Request
the express supply console no longer requires a QM level id to be usable

## Why It's Good For The Game
while the express supply console is much more efficient in delivering crates to cargo, i do not feel as if there is any reason to lock it behind qm access only, hopefully this unnecessary requirement can be removed.

## Changelog

:cl:
add: the express supply console now requires cargo access instead of quartermaster access
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
Please include a changelog for your PR

**Comment by AIUNBOLT** [comment]
> I feel like it should at least require Cargo Bay access if not QM access

there is only ONE quartermaster and ONE captain so i felt as if this access restriction was a bit excessive 
i think requiring a cargo tech id would be fairer, because you wouldn't want people wasting cargo's money

**Review by AIUNBOLT — COMMENTED** [review]
this changes the required access to basic cargo access instead of no access at all

**Comment by MrDoomBringer** [comment]
Great change TBH

**Comment by SingingSpock** [comment]
> this changes the required access to basic cargo access instead of no access at all

Don't forget to change the changelog on the PR to match 👍

**Pull request merged**
