### PR TITLE
Fixes all overlays being compiled twice at roundstart

### PR DESCRIPTION
**Pull request by Cyberboss**
NobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviewsNobodyReviews

# S P E E D M E R G E

### CODE REVIEW

**Review by CakeQ — COMMENTED** [review]
This is a review

**Review by ghost — COMMENTED** [review]
This is a review

**Comment by AnturK** [comment]
Oranges ples

**Comment by Cyberboss** [comment]
Fuck it, handled in #24356

**Comment by Cyberboss** [comment]
Oh you did it anyway, whatever

**Comment by optimumtact** [comment]
You need to stop writing so many bugs

**Pull request merged**
