### PR TITLE
Adds the Sidecut hairstyle

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Okand37 & Lexorion
add: Added a new hair style, the Sidecut!
/:cl:

Sprite by Lexorion:

emohair

### CODE REVIEW

**Comment by Grazyn** [comment]
Now you too can be Detective Miller from The Expanse!

**Comment by Okand37** [comment]
Woo, sidecut, now I can evolve to the next stage of cyberpunk.

**Comment by Mervill** [comment]
@Grazyn I'm convinced that the ss13 detective is modeled on miller -- He'll solve the case one he shifts into MAXIMUM OVER-NOIR

**Comment by Cheridan** [comment]
TRIGGERED

**Comment by KorPhaeron** [comment]
bloat

**Pull request merged**
