### PR TITLE
Flashman 4: Shine Eternal

### PR DESCRIPTION
**Pull request by lilacrhododendron**
🆑 Armhulen, Basilman, Cobby, and Subject217
add: You can now find the Flashy Costume in maintenance.
/🆑

This is Basilman's sprite, with a bunch of modifications so it actually works properly and looks good. [Here's a preview.
](https://streamable.com/m63u0)
There are two caveats. One, it doesn't look nearly as good with a backpack on, but I figured it was just a necessary evil. Two, the single nose pixel sticks out of the front of the helmet from the side, and I could not figure out how to fix this. It's not the end of the world to leave it that way, but I would like to change it if someone knows how.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
@Militaires 

The gift that keeps on giving

**Comment by Nabski89** [comment]
Exercise gulag bikes get closed and this stays open.

**Comment by subject217** [comment]
I would appreciate it if you didn't denigrate my PR based on the actions of the maintainers. Multiple people put a fair amount of work into Flashman, and there's nothing wrong with it. It's just a silly costume like the Griffon, it's unique, it presents a fun gimmick.

**Comment by Militaires** [comment]
do not deniggerate this..........

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
