### PR TITLE
Create RUN_SERVER.cmd

### PR DESCRIPTION
**Pull request by hack-wrench**
## About The Pull Request

A RUN_SERVER.cmd file is a type of batch file on Windows operating systems that can be used to start a server application. Batch files contain a series of commands that are executed by the command line interpreter. They are useful for automating repetitive tasks and can be particularly handy for starting a server with specific configurations or parameters.

## Why It's Good For The Game

By double-clicking the RUN_SERVER.cmd file, all these commands are executed in sequence, starting the server with the defined settings. This makes it much easier to start the server than typing out all the commands each time. It’s a convenient way to manage server settings and ensure consistency across server restarts. Batch files like this are widely used in various applications where a server needs to be started with specific parameters on a Windows environment.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl:
add: Added RUN_SERVER.bat for maintainer issues
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Please finish filling in your PR body, it is not optional.

**Comment by Iamgoofball** [comment]
also please do not write it with chatgpt

**Comment by san7890** [comment]
how is this materially different than `bin/server.cmd`? why do we need both this and the BAT?

**Comment by hack-wrench** [comment]
> how is this materially different than `bin/server.cmd`? why do we need both this and the BAT?

Technically nothing, just like BUILD.cmd, which is a copy of `bin/build.cmd`

**Comment by optimumtact** [comment]
I guess

**Pull request merged**
