### PR TITLE
Resprites: Clarke & Honker and some misc boards

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Gives the clarke, honker and mecha mainboard/peri/targeting boards new icons!
sprites not drawn by me!

## Why It's Good For The Game

image
image

color coded boards for better clarity when constructing mechas, better icons for Clarke and Honker exosuits.
The purple board might look weird or have editing artefacts, those shouldn't exist in reals (maybe)

## Changelog

:cl: by INFRARED_BARON
image: changes icons for clarke, honker and mecha circuit boards.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
You forgot to update:

- mech_construction.dmi
- mech_construct.dmi

For both this and the previous PRs

**Comment by Donkier** [comment]
Not gonna lie, the Clarke looks more bland than the original.

**Comment by githubuser4141** [comment]
> You forgot to update:
> 
> * mech_construction.dmi
> * mech_construct.dmi
> 
> For both this and the previous PRs

mech construction is just frames, the mechs are non coloured during this process, but I'll update the last 2 frames of mech construction in a bit

**Comment by Xackii** [comment]
Can’t figure out which sprite is new and which is old.

**Comment by EuclidianGeometer** [comment]
The boards look great. They have that nice chunky electronic feel. 

The new take on the clarke is alright, but I like the feeling of the older one better- the grey and brown bits on the torso feel like different layers of mechanics attached to each other, while the newer one loses that feeling by making the shilouette more smooth and making the grey bits brown.

The honk is great, excepting that i think as the annoying clown mech it should be a slightly more eye-searing color. The bullhorn you did looks much more like a bullhorn than the old one, and your version of the torso-mouth is much clearer! I never realized that was what it was supposed to be on the old design ,but it looks great here.

**Comment by L0pz** [comment]
I like the boards but clarke already looked really, really good so I don't really see a reason to replace it

**Comment by LSommers** [comment]
Still has the recurring issues with of your other resprites wherein a considerable amount of detail is lost vs the old sprite, colors are all very bland and blend together, and there are large patches of extremely monotone coloring.

The boards look good though.

**Comment by san7890** [comment]
for the record it is almost always preferable to atomize your PR. everyone would be able to keep the topic on point if there were three PRs: one for the clarke, one for the honkbot, and one for the board sprites. it's very easy for people to not have to keep switching topic in their posts talking about it to not have to change gears between constructive criticism and unconditional extolment. just for future reference.

**Comment by Admiral-Gigaton** [comment]
> Clarke looks worse, not a fan of that. You should keep his shape the same but just change the colours to fresher ones.

You should have seen the alternatives

(Spoiler: they were all spikey. Literally.

**Comment by Ghostkokos** [comment]
Nice boards sprite but mech true 💀

**Review by Wallemations — CHANGES_REQUESTED** [review]
> You forgot to update:
> 
> mech_construction.dmi
> mech_construct.dmi
> For both this and the previous PRs

I've been struggling on whether or not this is something we should wait for or if I should just merge these so these mechs match the other newer mech sprites, and then they could do the construction/construct sprites later?

**Comment by githubuser4141** [comment]
> > You forgot to update:
> > mech_construction.dmi
> > mech_construct.dmi
> > For both this and the previous PRs
> 
> I've been struggling on whether or not this is something we should wait for or if I should just merge these so these mechs match the other newer mech sprites, and then they could do the construction/construct sprites later?

I'll just edit them myself it's like a few minutes to smudge out some details when I get around to it lol

**Comment by githubuser4141** [comment]
> > You forgot to update:
> > mech_construction.dmi
> > mech_construct.dmi
> > For both this and the previous PRs
> 
> I've been struggling on whether or not this is something we should wait for or if I should just merge these so these mechs match the other newer mech sprites, and then they could do the construction/construct sprites later?

ok.. should be done... soon..

**Comment by Jacquerel** [comment]
We can't merge this until merge conflicts are resolved

**Review by Wallemations — CHANGES_REQUESTED** [review]
I've finally managed to figure out why I felt torn on the Clarke sprite
I think it's the lack of a contrasting highlight color that the existing sprite has
Every color in the sprite is a shade of yellow/orange, where in the original there was a grey/silver color used for highlights & to make the segments more distinct.

I think if you made that separator on your sprite that metallic grey then it will really improve overall.

**Pull request closed without merging**
