### PR TITLE
small swat suit change 

### PR DESCRIPTION
**Pull request by Bawhoppen**
It now doesn't have that entirely horrible slowdown, it is actually useful to wear now

I meant to do this in my other PR but kor merged too fast

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1: doesnt fit my design vision

**Comment by Bawhoppen** [comment]
@Iamgoofball go fuck off and die :wink:

**Comment by Iamgoofball** [comment]
lets fuck babe

**Comment by Lumipharon** [comment]
Didn't you try to add slowdown to telearmour to make it entirely not useful to wear anymore?

**Comment by Bawhoppen** [comment]
that wasn't me

**Comment by KorPhaeron** [comment]
Don't think we need heavily armoured 0 slowdown space suits from cargo

**Comment by kilkun** [comment]
To be honest, they are expensive as fuck.

**Comment by Shapsy** [comment]
They're still spaceworthy though so they may as well keep the same downsides other spaceworthy gear gets

**Comment by Bawhoppen** [comment]
the price is exactly why I think its balanced, they no longer have the OP combat knives, so instead the suit is better, plus its a combat suit and combat in this game is primarily about movement than tanking

**Comment by Bawhoppen** [comment]
also kor you can't just force close these PRs even if you claim to be design lead

**Comment by KorPhaeron** [comment]
Literally my job to say no

**Comment by Bawhoppen** [comment]
this is honestly not that unbalanced, it just makes life less miserable
riot armor already has 0 slowdown, not to mention how much more expensive this is

**Comment by kilkun** [comment]
Riot armor doesn't have the ridiculous armor values and it isn't space proof.

**Pull request closed without merging**
