### PR TITLE
Disease and blob camera mobs can move vertically while a location or host hasn't been chosen yet. Revenants can also freely move vertically.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
I found out on the icebox map, roughly a week or two ago, that the camera mob couldn't be moved to the other station leveleven **before the core was placed**. I believe this to be an oversight, which is why this PR has been made.
Sentient diseases also suffer from a similar issue while on the host selection stage, so I'm fixing that too.

EDIT: Someone pointed out that revenants (and other mobs with incorporeal movement) don't ignore turfs and obstacles when moving vertically, so I have added a few lines to `living/can_z_move` to hopefully fix that.

## Why It's Good For The Game
This PR aims to fix both issues explained in the above section.

## Changelog

:cl:
fix: blob overminds can now move vertically through station z-levels while its core hasn't been placed yet.
fix: disease mobs can too move vertically while a host hasn't been selected yet.
fix: (unrevealed) revenants can now move up and down more freely, without having to be standing on or below open space. This also applies to other living mobs with generic incorporeal movement (not to be confused with the nightmare or wizard's jaunt) as long as they can fly or there's no gravity.
/:cl:

### CODE REVIEW

**Comment by Y0SH1M4S73R** [comment]
Very cool. Can you fix revenant vertical movement while you're at it?

**Comment by Ghommie** [comment]
Oh yea sure. Are they unable to travel z-levels while hidden or more simply unable to move through open space?

**Comment by Y0SH1M4S73R** [comment]
> Oh yea sure. Are they unable to travel z-levels while hidden or more simply unable to move through open space?

Can't move z-levels while hidden

**Comment by Ghommie** [comment]
Mhm, It seems incorporeal movement doesn't grant free vertical movement. That's something i forgot about when I refactored it...

**Comment by Ghommie** [comment]
Done.

**Pull request merged**
