### PR TITLE
Changes integrated circuit locators to use Range instead of View

### PR DESCRIPTION
**Pull request by Iamgoofball**
Makes it much more useful.

### CODE REVIEW

**Comment by arsserpentarium** [comment]
not really.everything else uses view.So you just won't be able to process refs.

**Comment by Iamgoofball** [comment]
What? View is blocked by line of sight, range isn't. I can't make the xeno detector from Aliens if I can't do through-walls.

**Comment by arsserpentarium** [comment]
yes, no circuit can see throught walls now.
I'm planning some fuckery about circuits, which changes assembly's visible params, or even make it see throught camera.but probably after freeze

**Comment by SailorDave** [comment]
If the circuit uses range instead of view, it just won't have to worry about line of sight. It can still process refs just the same.

**Comment by arsserpentarium** [comment]
and add visible check circuit to see difference between visible/invisible objs

**Comment by arsserpentarium** [comment]
anyway,I know, how I'll change it later.

**Comment by Iamgoofball** [comment]
My GPU is fucking dead, this is on hold indefinitely

**Pull request closed without merging**
