### PR TITLE
Removes the NULL Crate

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Cargo Intelligence Agency
del: You don't get to bring traitor items.
/:cl:

### CODE REVIEW

**Comment by LanCartwright** [comment]
spec request;
change it so it consumes (qdel, or makes the emag completely useless) to open the crate.

Opening the crate any other way destroys it.

**Comment by Iamgoofball** [comment]
aha whoops wrong button fuck

**Comment by ma44** [comment]
>wrong button

**Comment by optimumtact** [comment]
you don't get to bring buttons.

**Comment by Bawhoppen** [comment]
this is actually kind of good and will help make cargo less of a meme

**Comment by PKPenguin321** [comment]
bad

**Comment by ma44** [comment]
Well you are paying smugglers to bring in items

Also we getting rid of lemons and that apparently fixes all cargo problems somehow

**Comment by PKPenguin321** [comment]
if it's REALLY REALLY REALLY an issue then make ordering the null crate require a password that's actually the traitor codephrases so that only genuine traitors can buy them

**Comment by Anonmare** [comment]
If this PR get's closed would you die?

**Comment by Iamgoofball** [comment]
it would be extremely annoying

**Comment by YakumoChen** [comment]
You could always just drive the cost up or something instead of outright removing it.

Traitor crates can make rounds fun, and usually unless it's super low pop someone is going to notice you ordering a trillion traitor crates so it's not easy to get away with this unseen.

**Comment by kevinz000** [comment]
Goofball go fix your stocks instead of the problems it makes.

**Comment by Cheridan** [comment]
They expect one of us in the wreckage, brother

**Comment by PKPenguin321** [comment]
sad day for ss13

**Comment by YakumoChen** [comment]
>people don't want it removed
>coders remove it anyway

DO YOU EVEN PLAY

**Comment by optimumtact** [comment]
It's called designing

**Comment by YakumoChen** [comment]
replace it with something else fun then, Null crates made science rounds fun.

**Comment by Iamgoofball** [comment]
if the only way to make science fun is to give them traitor items we need to look at how science works

**Comment by YakumoChen** [comment]
I mean there's all sorts of suggestions to actually fix this instead of just removing it. There's been absolutely no problems with null crates until you made this PR.

**Pull request merged**
