### PR TITLE
adds a convermol syringe to emergency first aid kits, makes it possible to buy emergency first-aid autoinjectors from NanoMed Pluses

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Replaces one of the two emergency first-aid autoinjectors in the emergency first aid kit with a convermol syringe.

Reduces the price of epipens from NanoMed Pluses from 300 credits to 150 credits. They're also not premium items in NanoMed Pluses anymore, so MDs can buy them for free like most of the other meds in NanoMed Pluses.

Adds emergency first-aid autoinjectors to the inventories of NanoMed Pluses. They cost 150 credits each.

Adds epipens, emergency first-aid autoinjectors, and convermol syringes to the inventories of wall-mounted NanoMeds.

Adds an emergency first aid kit single-pack to the list of things you can buy from Cargo. It costs 250 credits (the same price as a normal first aid kit).

Adds emergency first aid kits to the pool of items that can appear in "Medical Supplies Crate"s from Cargo.

## Why It's Good For The Game

Emergency first aid kits contain iron pills to deal with the blood loss from bleeding, but not any convermol to heal the oxyloss damage from said bleeding (or the oxyloss damage from formerly-critted people after you've healed their brute/burn damage with the sutures and ointments in the kit). Also, this might allow a future PR to change the lexorin counter-chem to be convermol and/or salbutamol instead of epinephrine.

For some reason, even though almost everyone starts the round with an internals box that contains an epipen, it still costs a whopping 300 credits to buy a SINGLE EPIPEN from a NanoMed Plus (even if you're a medical doctor).

Emergency first-aid autoinjectors serve a somewhat different niche than epipens do (EFAAs contain spaceacillin and more coagulant than epipens do, but contain no formaldehyde), and yet the only way for MDs to get their hands on them is to search (or hire someone else to search) oxygen lockers for them. Also, this kind of compensates for the halving of the number of EFAAs in each emergency first aid kit.

Cargo can buy the other kinds of basic first aid kits, so why not emergency first aid kits?

## Changelog
:cl: ATHATH
balance: One of the two emergency first-aid autoinjectors in the emergency first aid kit has been replaced with a convermol syringe.
balance: The price of epipens from NanoMed Pluses has been reduced from 300 credits to 150 credits. They're also not premium items in NanoMed Pluses anymore, so MDs can buy them for free like most of the other meds in NanoMed Pluses.
add: Emergency first-aid autoinjectors have been added to the inventories of NanoMed Pluses. They cost 150 credits each.
add: Epipens, emergency first-aid autoinjectors, and convermol syringes have been added to the inventories of wall-mounted NanoMeds.
add: Emergency first aid kit single-pack can now be purchased from Cargo. They cost 250 credits each.
add: Emergency first aid kits have been added to the pool of items that can appear in "Medical Supplies Crate"s from Cargo.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
image

**Comment by wesoda25** [comment]
whats crazy to me is the length of the title vs the cl

**Comment by Ryll-Ryll** [comment]
Convermol sucks though, the emergency medipen is 10x more useful

**Comment by Krysonism** [comment]
I am disliking this because epipens are too useful and convenient to be free for medical personnel. 

I have purchased them on many occasions for the 300 credit price, although i buy the shears first if i am a medical doctor.

**Comment by Tlaltecuhtli** [comment]
converol is already in o2 kits which are common, why not keep the 2 medipens and add leporazine pill(s) instead? as it feels more emergency chem

**Comment by kriskog** [comment]
This adds a lot of roundstart supplies to medbay, especially on maps like delta with a few wallmounted nanomeds. The emergency kits are also fine to be a stabilizing kit as opposed to solving all your troubles.

**Pull request closed without merging**
