### PR TITLE
Shadowling Update II

### LINKED ISSUE #9021: Shadowling Veil doesn't turn off hardsuit lights
Also possibly doesn't turn off pumpkins, hard hat lights, and a few other lights.

### LINKED ISSUE #9197: shadowling can dress up while in chrysalis
result:
kek

### LINKED ISSUE #9538: Shadowling veil does not work on gunlights
Should be an easy fix.

### PR DESCRIPTION
**Pull request by ghost**
- Shadowling ascendants now speak in REALLY BIG TEXT when they talk normally.
- Shadowling ascendants get a new ability that lets them send a message in huge text to the game world
- Glare now properly silences instead of injecting mute toxin.
- Veil has been refactored and will now properly turn off all held lights.
- Drain Thralls is now Drain Life, and will affect all humans instead of thralls. Healing amount depends on the amount of people nearby, as well.
- The mostly useless Spatial Relocation ability has been scrapped and replaced with Black Recuperation. With a five-minute cooldown, a shadowling can, after a short time, revive a dead thrall to full health.
- Thralls no longer dust upon a shadowling ascending, but instead just die. This is to prevent massive lag.
- Vortex has been removed.
- Most instances of the deadsay span class have been replaced with the shadowling span class.
- The shadowling span class has been made more purple.
- Shadowlings can only enthrall up to five people before being forced to hatch. A hatched shadowling can continue to enthrall, but non-hatched ones can not enthrall once the global thrall count has reached five.
- Enthralling now gives a large visible message to everyone nearby.
- The cooldown on all ascendant abilities bar Glacial Freeze has been lowered to zero. Prepare yourself.
- Moves the ascendant_shadowling.dm to the shadowling gamemode folder
- Shadowlings now have unique names upon hatching rather than numbered ones
- Fixes #9538
- Fixes #9197
- Fixes #9021

This will probably break the feature freeze, I know.
I will fix some other issues later.

### CODE REVIEW

**Comment by JJRcop** [comment]
The feature freeze died but the headcoders don't tell anyone so all the features say "don't merge me". Yet the fact that the features are there in the first place defeats the purpose of the freeze.

**Comment by Xhuis** [comment]
A lot of the stuff on this PR is shadowling issues/polish that has needed creation/fixing since the gamemode came out. There's only a few features in comparison.

**Comment by Xhuis** [comment]
not actually sure why that happened

**Comment by Cheridan** [comment]
>Shadowling ascendants now speak in REALLY BIG TEXT when they talk normally.

How big is "really big"? Please no more NARSIE HAS RISEN/Complionator screen-filling shit

**Comment by Xhuis** [comment]
@Cheridan http://gyazo.com/6b24d44d945392ec646e1f94bb1d73be

**Comment by Dorsisdwarf** [comment]
All-'Ihram telephatically roars "REEEEEEEEEEEEEEEEEEEEEEEEE"

Oh, does this give their spells proper icons?

**Comment by Xhuis** [comment]
Dorsis: No, I have no sprites for that

**Comment by Xhuis** [comment]
This is merge-ready but I would prefer it waits until after the freeze ends in case I need to do anything else

**Comment by Xhuis** [comment]
Could you remove the do not merge tag from this?

**Comment by Xhuis** [comment]
Will do this later when I have less to work on.

**Pull request closed without merging**
