### PR TITLE
Shadowling: Removes Pre-Hatch Enthralling

### PR DESCRIPTION
**Pull request by Robustin**
Based on my feedback thread here:

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4851

It encourages a completely awful playstyle for a troubled game mode. Most idiots appear to be under the assumption that if they just stunprod, cablecuff, and then attempt to enthrall, then security can't arrest or punish them for anything worse than kidnapping. That is until the victim (if rescued in time) claims that his attacker was a shadowling and/or security implants them as a precaution and then summarily executes the Sling for resisting the implant.

Pre-Hatch Thralling is a dichotomy. Either you have the items/chems and the knowhow to successfully and silently convert people in which case you have 0 incentive to actually -play- as the antag you've been chosen for... or you don't have those things and pre-hatch thralling is worse in every way, serving only as bait for new/bad players who fall into the aforementioned trap. 

Nobody wins with pre-hatch thralling and it continues the cycle of bad shadowlings since these idiots never actually learn to play the antag. Pre-Hatchers who "succeed" by destroying comms, using chems, etc. just appeal to the very worst of powergaming while still depriving the station of a compelling antagonist.

### CODE REVIEW

**Comment by Xhuis** [comment]
pssh whatever

**Comment by RemieRichards** [comment]
@Robustin they're not given the enthrall spell when they hatch, so you need to add that otherwise they'll never get the spell.

**Comment by Robustin** [comment]
Thanks, that should take care of it.

**Comment by Zilenan91** [comment]
:-1: this is a player problem not a code problem

**Comment by Robustin** [comment]
It's a player problem ENABLED by the code design.

New players selected for Shadowling have two real spells, one is a big scary unknown that's very high commitment and irreversible. The other is much more tame, discrete, and understandable. So the new players go low commitment and end up as a pile of ashes in the crematorium about 5 minutes later.

**Comment by Zilenan91** [comment]
Once again, what you've described is a player problem. If players want to be successful, they'll get good, with pre-hatch thralling only for those who got good enough to be able to pull it off. If they fuck it up that's just life

**Comment by Robustin** [comment]
"If players want to be successful, they'll get good"

5 years of Nukeops has proven otherwise. 

Shadowling is about SHADOWLINGS, not assholes with 500 units of stun+silence chemicals and a syringe gun stuffed in their bag with a lube spray bottle in each pocket. It's extremely unhealthy for the game mode to allow or encourage what is invariably shitty un-engaging gameplay that plays out like it's extended.

**Comment by PKPenguin321** [comment]
if anything, make it so they can enthrall at least 1 person before hatching. it's nice having a minion right at the get-go instead of having to risk everything by yourself.

**Comment by Zilenan91** [comment]
Yeah that would be great. Have someone telling you what's going on on the station.

**Comment by Steelpoint** [comment]
Why would you need that when you yourself can just look around the station before hatching?

Hell I think this game mode should return back to the admin-event version where you spawn in the game as a Shadowling from the get go (Who needs maint access when you had a quick teleport ability from the get go).

But I think this is a fine change :+1:

**Comment by Robustin** [comment]
No, not even one. That's the kind of short-sighted crap that I loathe this place for. So many issues with people who would attempt multiple thralling and only realize once its too late that they can't get more than one without hatching in front of them. And it still wouldn't correct the primary cause for this PR, the average player gets caught in their first thralling attempt and is out'd and killed in the most anticlimatic way possible.

**Comment by PKPenguin321** [comment]
robustin has turned on us, he is going full "NO NO NO i control what happens, I AM THE ONE WITH THE CODE"
abort abort

**Comment by Dorsisdwarf** [comment]
TBH tho the "compromise" made on prs these days is getting pretty insane

(See: steelrifles evolution from pr1 rev 1 to pr 4(?) rev 3(?) )

**Comment by Steelpoint** [comment]
To be fair the rifles themselves saw little physical change, the main changes made were more pertaining to magazine and rifle presence on the map.

**Comment by Robustin** [comment]
The mode is shadowling, not "3 random crew with stunprods - the mode".

Before my last PR it was "2 random crew with stunprods - the mode". 

I want to see the mode on par with gang war in terms of what a fresh new mode can bring to the game. That's not going to happen as long as people assume that non-hatching is the NORMAL playstyle and that hatching is the "alternative".

Either you screw up and essentially waste a critical antag slot, or you kick your powergame up to 11 and succeed by taking the SHADOWLING out of the SHADOWLING GAME MODE. Either way it doesn't provide the crew with a compelling antagonist and the round ends with "WHAT IT WAS SHADOWLING?!"

I've never supported player freedom for the sake of freedom, I just support fun. Generally freedom = fun, but there are cases like this where it just encourages a majority of players to be selected for an antag that they never actually play.

**Comment by Steelpoint** [comment]
I should note that when I initally suggested this as a game mode a year ago that I did not envision any alternative way to play as a Shadowling that involved not being a Shadowling.

**Comment by SweaterKittens** [comment]
I agree with this, the best sling rounds I've seen and what gives players the most experience and fun is forcing them to hatch to be successful. Yes, players will git gud after playing more, but making the mode actually ABOUT SHADOWLINGS is exactly what we need. It's a player problem, I agree, but that doesn't change the fact that it is a problem - and I think this will do a lot of good towards fixing it. And "shitty compromises" aside, there's still nothing stopping you from grabbing your first quarry while human, and hatching while you have them restrained to thrall them. It's a truly terrifying experience trying to frantically escape your cuffs while you watch the person in front of you turn into a shadowling.

I have to wildly disagree with "bringing it on terms with gang war" though, as I think Gang is an absolutely atrociously shitty game mode. It has good ideas, but brings nothing but long, drawn out, deathmatch rounds. This on the other hand has the potential to really mix things up, and making it all about hatching and actually being a shadowling is what we need.

**Comment by Steelpoint** [comment]
The fact of the matter is Shadowling should be about the Shadowling, not the Human who becomes one.

This game mode was well received, and was pushed to become a actual game mode, from the uniqueness that the actual Shadowlings brought to the table. It was not praised to hell because of a Human with the ability to convert someone into a Thrall.

**Comment by Robustin** [comment]
Well regardless of our opinion on Gang War, I'm simply talking about gametype quality and not playstyle.

Sling is probably the least murderboney conversion mode and Gang War is the most. Improving Sling could really bring out a top-tier mode that doesn't involve murdering everyone with an implant. But I must continue to stress that this game will NEVER reach its full potential as long as 50% or more of the shadowlings continue to die without hatching and the primary CREW v. ANTAG conflict is chasing down some asshole engineer with a stunprod in maint.

**Comment by SweaterKittens** [comment]
Yeah, fair enough, I understand what you're saying about play style. I agree that by improving sling it would really make the round come into it's own and not a 20 minute "slings are dead call shuttle" or a 45 minute "It was sling?" as it is now. Perhaps we could use or shiny new PR test system to give this a shot if people are still uncertain?

**Comment by Zilenan91** [comment]
Once again, it's a player issue. People in OOC are of the opinion that pre-hatch enthralling should be something that you can do if you're good and have the equipment for it, but it's not required. If people for some reason think they HAVE to do it, then they need to git gud.

**Comment by Cookiesndip** [comment]
Eugh. Horrible for a bunch of reasons. Sling needs the come-up period where you can get a modest thrall base silently. Without that, hatchers fluke the moment someone walks into their base, especially since the meta is to call the shuttle instantly when slings are called out (because they're boring + impossible to tell even vaguely how close to victory they are).

Also, it ruins my typical shadowmeme strategy (cut comms, enthrall a few low-hanging folks, enthrall a secman, then hatch). Honestly, I feel the big problem is that slings just have shitty abilities and the ones that are viable aren't fun. They're weak and die in three laser blasts, their abilities have huge cooldowns, and the only really decent active ones, glare and shadow step, are boring and single-target, or have a huge cooldown and short range. They also have zero abilities that can stop or kill a hulk, and they don't even have perfect nightvision so I actually perform better with fucking mesons pre-hatch than with the ghetto NV. They die to fucking flares all the time, and are hardcountered by botany, flares which are scattered throughout the station, and even just one of the trillion station-bounced radios can fuck one. Top that off with turning into an obvious flaming nigger that will make people scream valids, and shadowmemes are just plain weak and worst of all, more boring than not hatching. Regardless, it's a severe downgrade for any remotely robust player TO hatch.

**Comment by Steelpoint** [comment]
Shadowling did very well back in the admin test days of Shadowlings spawning in the Derelict already as a Sling instead of some shitty "stealth phase" element we have now.

There are a lot of differences between original 'admin event' version of Sling versus the xhuis 'modern sling' we have now.

Whereas Admin Sling made the Shadowlings pretty powerful in their own right, and had them actively participate in the round from the get go, the modern sling encourages Slings to be passive and to sit out.

**Comment by Steelpoint** [comment]
This change is a good first step in making Shadow Ling a better game more, right now its a shadow of its former self as it did not survive the transition from Admin event to Real Game Mode in its entirety.

**Comment by Fox-McCloud** [comment]
Errr...Shadowlings can't resist implants?

**Comment by Zilenan91** [comment]
When they're not hatched they resist implants.

**Comment by Fox-McCloud** [comment]
@Zilenan91 

Could you show me, in the code, where that's at?

**Comment by Zilenan91** [comment]
I can't show you in the code because I'm not a coder and can't read it, but you can test it and see that unhatched slings resist implants. Unless it got stealth changed, that is the case.

**Comment by Fox-McCloud** [comment]
Considering I can't find it, then you're going to have to demonstrate and prove out your point.

**Comment by Zilenan91** [comment]
that's not something I can do right now

**Comment by Dorsisdwarf** [comment]
@Fox-McCloud 

https://github.com/tgstation/-tg-station/blob/e3e6fc13a919ed50a1777471f44deaf04340be7e/code/game/objects/items/weapons/implants/implant_loyality.dm#L22

**Comment by Fox-McCloud** [comment]
@Dorsisdwarf 

Thank you.

**Comment by Xhuis** [comment]
This has already been implemented. You can close this PR now.

**Comment by MrStonedOne** [comment]
Please make a changelog,

You can add it to the PR's body rather then as a file now, see here: https://tgstation13.org/phpBB/viewtopic.php?f=5&t=5157

**Comment by duncathan** [comment]
This PR is now redundant

**Pull request closed without merging**
