### PR TITLE
Prevent negative sqrts in dna heal

### PR DESCRIPTION
**Pull request by optimumtact**
Fixes a runtime

@LanCartwright what even is this algorithm man

### CODE REVIEW

**Comment by xxalpha** [comment]
It's ((((((((math)))))))))

**Comment by Incoming5643** [comment]
>byond doesn't support imaginary numbers

**Comment by LanCartwright** [comment]
negative sqrts isn't possible currently, hence why my lack of concern.

**Comment by optimumtact** [comment]
@LanCartwright I HAVE ABOUT 16,000 RUNTIMES THAT DISAGREE WITH YOUR OPINION

**Comment by Jordie0608** [comment]
For reference these are said runtimes https://tgstation13.org/parsed-logs/sybil/runtimes/runtime-2016-04-28-condensed.txt

**Pull request merged**
