### PR TITLE
Adds deathsquad corgis

### PR DESCRIPTION
**Pull request by TZK13**
deathsquad corgi

Dress up a corgi as a deathsquad trooper today.

Sprites courtesy of dbuhos that I found on the old old forums [here](https://www.theforgottenzone.com/hosted/archive/tgss13/viewtopic.php?f=10&t=11902&start=30#p199098).

Also updated the beret and nurse hat sprites for corgis, made it so that corgis can wear the warden's hat too, and fixed some description texts.

### CODE REVIEW

**Comment by Steelpoint** [comment]
Amazing

**Comment by Cheridan** [comment]
:man: :gun: :dog2:

**Comment by RandomMarine** [comment]
Do they bark pulse lasers? They should bark pulse lasers.

**Comment by paprka** [comment]
well this is great

**Comment by WJohn** [comment]
This isn't even #8000 yet. And you're not aran. What's going on?

**Comment by Niknakflak** [comment]
Yes, merge now.  Right now

**Comment by ike709** [comment]
YOLOMERGE

**Comment by palpatine213** [comment]
:+1:

**Pull request merged**
