### PR TITLE
Grenade belt for nukeops

### PR DESCRIPTION
**Pull request by Bawhoppen**
New type of grenade: Gluon frag. It gives off rad damage, stamina damage, and chills everyone it's blast hits.

Ops can now buy a big ol' belt of various grenades for 22TC (willing to negotiate the price)
ss 2016-03-20 at 07 41 56

~~I lowered the price of the syndie minibomb to 3 to help balance it, and unrelatedly also made the stechkin only 5 TC and revolver ammo 2 TC (it can be mass printed anyways)~~

New sprites for frags and smoke grenades courtesy of ausops and WJ.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
also I actually tested stuff (#ooh #ah)

**Comment by Niknakflak** [comment]
>doing a ton of price changes along with adding something


I see through your deception

**Comment by Bawhoppen** [comment]
it was 2 minor price changes though

**Comment by Zilenan91** [comment]
>syndi minibomb to 3

No, you go from being able to gib 3 people/body piles to 6

**Comment by Bawhoppen** [comment]
I could compromise that but I want to make it worthwhile to ever purchase those.

**Comment by Zilenan91** [comment]
Revolvers are 14 TCs right? This means you can have three speedloaders of ammo from your TCs, that means 24 revolver shots. You can piss ammo.

**Comment by Xhuis** [comment]
##### JESUS
#### FUCKING
### CHRIST
## NO

:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1:

**Comment by Bawhoppen** [comment]
You can mass print it near infinitely roundstart from an autolathe. But I'll change that one back because I don't care about the ammo change much.

**Comment by optimumtact** [comment]
Yes Yes Yes


YESSSSSSSSSSSSS

**Comment by Bawhoppen** [comment]
there now revolver ammo change is reverted and minibombs have been compromised to 5

**Comment by PKPenguin321** [comment]
pls bawhoppen this is a cool feature don't get it rejected with controversial price changes, save those for another PR

**Comment by Bawhoppen** [comment]
what do you want me to change back all the price changes entirely? the revolver was the main problem I thought

**Comment by PKPenguin321** [comment]
yeah just put them in a separate pr

**Comment by Bawhoppen** [comment]
fine fine

**Comment by Zilenan91** [comment]
The stechkin buff is good tbh, that gun sucks for 9 TCs, could probably keep it

**Comment by Bawhoppen** [comment]
I'll be fiddling with syndie items later anyways, I'll do it then

**Comment by JJRcop** [comment]
There have been a lot of prs with cool features that get killed because they were mixed with stupid balance changes of something else that should have been in a separate PR.

**Comment by PKPenguin321** [comment]
yeah you're one of the few that actually removes the controversy from an otherwise good pr, good job :)

**Comment by Bawhoppen** [comment]
I have told goof and other people countless times to seperate their PRs up, so I shouldn't be a hypocrite about it

**Comment by Xhuis** [comment]
Oh good, the shitty changes got removed. :+1: then I guess

**Comment by Bawhoppen** [comment]
should I changelog this

**Comment by Xhuis** [comment]
If I wanted responsibility I would say _yes_.
If I wanted people to discover it randomly one round and go ballistic with it I would say _no_.
Guess which I choose?
Hint: it's not "yes".

**Pull request merged**
