### PR TITLE
New Slime Sprites

### PR DESCRIPTION
**Pull request by MTandi**
NVIDIA_Overlay_zdD7d5wFSY

## About The Pull Request

Resprited slimes, added unique sprites for the dead states.

## Why It's Good For The Game

Sprites were dated. 

Sheet:
slimes_flat

## Changelog

:cl:
image: Updated slime sprites
/:cl:

### CODE REVIEW

**Review by tralezab — APPROVED** [review]
code changes are minimal and I don't see issues

**Comment by improvedname** [comment]
what about with the faces?

**Comment by Jacquerel** [comment]
Can we get some in-game screenshots too?
Spritesheets are never actually sufficient.

**Comment by Jacquerel** [comment]
You will also have to modify the unit test someone wrote to make sure they are emoting at the right time

**Comment by Profakos** [comment]
You can actually remove perform_change_slime_face and the current_mood var, they only existed for slime faces. 👍

**Comment by MTandi** [comment]
> You can actually remove perform_change_slime_face and the current_mood var, they only existed for slime faces. 👍

Not really, they also *emote based on their mood, so I'm leaving it.

**Comment by Wallemations** [comment]
I like the sprites but the faces were part of the slime's charm :(

**Comment by EricZilla** [comment]
Slimes are cuter with no face imo

**Comment by Elli-Skala** [comment]
What about reverting it to its prior state where slimes only get a face if they're dociled/player controled.

**Comment by MrMelbert** [comment]
they do look very good but how do you tell slime mood (hungry or asleep or whatever) now?

**Comment by MTandi** [comment]
Sure, I'll make them have faces when player controlled and docile as @Elli-Skala suggested.

**Comment by MTandi** [comment]
Reverted everything related to faces. They now use the old face sprites and logic. Only the bodies are changed in scope of this PR.

**Pull request merged**
