### PR TITLE
2 much brain damage can now rekt you!

### PR DESCRIPTION
**Pull request by ghost**
```<atlanta_ned> fwoosh is a good example of brain damage not being lethal```
rip fwoosh i guess

:cl: More Robust Than You
tweak: your brains now actually realize when it's better to be dead than to be retarded
/:cl:

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
Make it so people forget to breathe, get confused (stunned)

**Comment by ChangelingRain** [comment]
This doesn't even work, since the maximum braindamage is 100.
I'm super vetoing this anyway since it's terrible and, if it worked, would once again make brainrot the most lethal virus in the game.

**Comment by MoreRobustThanYou** [comment]
@ChangelingRain would there be any way to raise the max. Also would making brainrot slower and slower as it got over 100 be good or no?

**Comment by Cyberboss** [comment]
Braindamage is a meme, keep it that way

**Comment by MoreRobustThanYou** [comment]
Ok, I made is so _**210**_ brain damage is required for death

**Comment by ChangelingRain** [comment]
>This doesn't even work, since the maximum braindamage is 100.

**Comment by MoreRobustThanYou** [comment]
@ChangelingRain how would I change that? Yes, I plan to nerf brainrot to make it not go to deadly braindamage levels

**Comment by The-clown-known-as-Pepe** [comment]
you'd think that a disease that literally ROTS your brain away would be more deadly @ChangelingRain

**Comment by Jordie0608** [comment]
Spacemen don't use their brain for anything.

**Comment by KorPhaeron** [comment]
>Alright 120 brain damage kills you
>You cant actually get 120 brain damage
>Fine we"ll compromise it takes 210 now

???

**Comment by MoreRobustThanYou** [comment]
> how do i raise the max
> no answer

**Comment by ExcessiveUseOfCobblestone** [comment]
prob in life

**Comment by YakumoChen** [comment]
wouldn't this make admin brain damage instantly lethal (which is unintended)

**Comment by Durkel** [comment]
Smite brain damage punishment does 75 damage.

**Comment by FantasticFwoosh** [comment]
☠️ Mannitol Plox! ☠️

**Comment by jughu** [comment]
Best pr makes meth and uh other shit auctally fangerous i guesaz

**Comment by MoreRobustThanYou** [comment]
@YakumoChen IIRC, admin braindamage does 75-100. This PR requires 210 to be lethal.

**Comment by kevinz000** [comment]
Oh so instead of realizing that chaplains being able to make infinite healing water is dumb, you TRY TO BALANCE A MAJOR PART OF OUR MEDICAL SYSTEM SO YOU CAN ADD THAT DUMB OVERPOWERED FEATURE.
No.
Stop.

**Pull request closed without merging**
