### PR TITLE
Shows defib icon on corpses with soul

### PR DESCRIPTION
**Pull request by rdragan**
## About The Pull Request
With cloning being removed and the manual reviving process being more laborious, it is very disappointing and frustrating for medics to discover they've been working on a soulless body. This will make the old defib icon show on medhuds for bodies that still have a ghost attached, otherwise it will change to the standard dead icon.

The defib icon is still here and not being used for anything else but I'm not a big fan of it. I'm open to changing it if anyone wants to submit a different icon

## Why It's Good For The Game
Gives MDs faster and easier feedback on what bodies are worth their attention or if a body becomes soulless while being treated.
Makes it easier to see what corpses you can safely throw out of an airlock 30 seconds before the round ends.

## Changelog
:cl: Thebleh
tweak: Bodies with souls show the defib icon on medhuds.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Will this work even if the ghost isn't in their corpse? As in, the ghost's floating around and observing the round?

Also, how does this interact with the DNR (do not resuscitate) button?

**Comment by rdragan** [comment]
> Will this work even if the ghost isn't in their corpse? As in, the ghost's floating around and observing the round?
> 
> Also, how does this interact with the DNR (do not resuscitate) button?

Basically, if an examine shows you "and their soul has departed... " then the dead icon will be shown. To have the icon update I've added calls to the DNR verb and to observer `Destroy()` (called when a ghost is destroyed ie. it's owner got a new body). This covers ghost roles and event rolls. 

There are some debug commands that remove the reference to the old body before the ghost is destroyed and won't update the icon immediately (namely 'Select equipment'), but this should be rare enough that they shouldn't be a problem. Worst case scenario, a soulless body will still show the defib icon, but any stat change will update it, eg finishing a treat wounds step will make it update.

**Comment by trollbreeder** [comment]
How would this work with fake deaths? Would they show up with the defib icon or the skull icon?

**Comment by rdragan** [comment]
> How would this work with fake deaths? Would they show up with the defib icon or the skull icon?

Defib icon.

**Comment by ExcessiveUseOfCobblestone** [comment]
You can tell if someone is pretend-dead or not by checking the available surgeries as there's some that require death be a prereq.

**Review by kriskog — APPROVED** [review]

**Pull request merged**
