### PR TITLE
Adds sixteen new OOC emoticons

### PR DESCRIPTION
**Pull request by Tacolizard**
toot toot everyone hop on the bee train

extremely hip icon

new

**Ok, i've had to promise myself not to do any more. This is all of them unless someone makes a really good suggestion.**

### CODE REVIEW

**Comment by unrealair** [comment]
MERGE THIS TOO

**Comment by Repukan** [comment]
It's hip

**Comment by RemieRichards** [comment]
change the bee to ```hip```

**Comment by Tacolizard** [comment]
@RemieRichards done

**Comment by ExcessiveUseOfCobblestone** [comment]
add the joy mask emoji please

**Comment by kevinz000** [comment]
>b

no.

**Comment by Repukan** [comment]
No normies meme shit please.

**Comment by Tacolizard** [comment]
its called ironic memery

**Comment by TehZombehz** [comment]
No thinking emoji?

**Comment by ExcessiveUseOfCobblestone** [comment]
Are you rea🅱️y?

**Comment by Repukan** [comment]
Fuck off with the b

**Comment by dannno** [comment]
was cool until you fucked it up
retard

**Comment by duncathan** [comment]
for the love of God destroy those pieces of meme garbage
The first 5 ones are fine

**Comment by Tacolizard** [comment]
@ExcessiveUseOfCobblestone That's a good point. I'll try and make more 'ss13-y' sprites.

**Comment by optimumtact** [comment]
source for the emoji?

**Comment by ChangelingRain** [comment]
'forever', 'up', 'down', and 'joy' all have a white background that they shouldn't.

**Comment by ChangelingRain** [comment]
Also why the heck didn't you just take the entire icon for the help/disarm/grab/harm icons, they're already 16x16 and they'll look better if they're all the same size

**Comment by Tacolizard** [comment]
they were larger when i pasted them

**Comment by ChangelingRain** [comment]
that means you fucked up here are the full-size versions http://puu.sh/vNk9u/e7f6e74431.dmi

**Comment by dannno** [comment]
get rid of the fucking apple ones have some self respect

**Comment by Tacolizard** [comment]
the only apple ones are the thumbs. also i tried removing the white backgrounds but it wouldn't erase

**Comment by ExcessiveUseOfCobblestone** [comment]
just use the byond editor and paint with the mask lol

**Comment by RemieRichards** [comment]
@Tacolizard I think they should be animatable, yes

**Comment by Tacolizard** [comment]
well i feel like the bee really should move

**Comment by Iamgoofball** [comment]
just downside the crayons to 16x16 and make them letters

**Comment by Iamgoofball** [comment]
@RemieRichards chatbox doesnt support it atm, we'd need goonchat for animated

**Pull request merged**
