### PR TITLE
Do you expect me to talk?

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: Fixes the Atheist's Fedora's throw damage.
/:cl:

No, Chaplain, I expect you to die.

### CODE REVIEW

**Comment by Armhulen** [comment]
good chuckle

**Comment by lzimann** [comment]
i was expecting a super memey pr but it's just a regular one, now i'm kinda disappointed

**Comment by Iamgoofball** [comment]
@lzimann in a sense it's a meme

**Comment by Zilenan91** [comment]
What if you made the Fedora 50 brute 100 AP so you can cut off limbs in one throw

**Comment by Davdichan** [comment]
@iamgoofball does the fedora embed in electrified grills and shock anyone pulling it out?

Also specialized throwing shoes.

**Comment by coiax** [comment]
So you're just undoing @hornygranny's PR, and making the hat a force=0 weapon again? One that no one ever used? Just buff its throw damage, keep the hit the same.

**Comment by GunHog** [comment]
Agreed with coiax. You can keep the Oddjob reference with the high throw force, but remove the `force` var entirely, and allow it to come from the parent. The weapon being unused is a concern that will not be addressed with the current changes.

**Comment by hornygranny** [comment]
as long as it has 0 force it will never be used, just give it both

**Comment by Iamgoofball** [comment]
here's what I'm gonna do instead

50 throwforce for instant dismember on hit

5 to 10 damage on normal force

it is very much a throwing weapon

**Comment by FantasticFwoosh** [comment]
Peaky blinder edge damage razorblade flatcaps when?

(For reference, peaky blinders is a name of a ye'olde birmingham gang that hid razor blades within the rim of their flatcaps so they could whisk them off at a moments notice and severely cut people before putting them back onto their heads and blending in with the rest of the birmingham population.)

**Comment by evsey9** [comment]
if you knew that you would be able to oneshot kill silicons using this in current age, would you merge it?

**Comment by optimumtact** [comment]
yes

**Comment by GunHog** [comment]
How does it one-shot silicons?

**Pull request merged**
