### PR TITLE
Frees the white ship from the station's evil grasp.

### PR DESCRIPTION
**Pull request by WJohn**
The white ship is no longer stuck to flying around the station z level. It can now fly around the z level it spawns (and discover the ruins there) as well as the z level the derelict spawns, and more in the future!

*FTL Intensifies*

:cl: WJohn
add: The white ship is no longer stuck to flying around the station z level. It can now fly around its own spawn's level and the derelict's level too (these sometimes will be the same level).
/:cl:

### CODE REVIEW

**Comment by Borisvanmemes** [comment]
I've been waitting for this for AGES!

**Comment by Dennok** [comment]
Maybe add something like a FTL beacon, which gives the FTL ability to the Z level.

**Comment by adamkad1** [comment]
> Maybe add something like a FTL beacon, which gives the FTL ability to the Z level.

would be cool if it was deep space item or something. also whiteship cant go to station now?

**Comment by Dennok** [comment]
It can, if it can dock to station as before.
 If no write issue that whiteship cant dock to station on some map.

**Comment by Dennok** [comment]
Ah i already do FTL beacon. And no. You need to build it. Or i add it to some habitable ruins later.
#44807

**Comment by adamkad1** [comment]
> It can, if it can dock to station as before.
> If no, write issue that whiteship cant dock to main station on some map.

It didnt seem to have a station button, just derelict, deep spess and lavaland, and potentially custom

**Comment by Dennok** [comment]
On what main station map you see this?

**Comment by adamkad1** [comment]
> On what main station map you see this?

apparently the fancy new publing mining shuttle now can obstruct the dock whiteship used to use. WE NEED MORE DOCKS

**Pull request merged**
