### PR TITLE
Fix Atmos Tanks Connecting to pipenets when mapped [MDB IGNORE]

### LINKED ISSUE #61594: Atmospheric Tanks do not connect to adjacent pipes during mapload
## Reproduction:
Observed over a couple rounds, just now remembered to report it.
https://puu.sh/IcG4X/c9fed6e28a.png

It's also "broken and nonfunctional", as is the one in the turbine, when examined.

Also, I have no idea how these even connect to pipes? I surrounded it with omni pipes and none seemed to connect.

### PR DESCRIPTION
**Pull request by Maurukas**
## About The Pull Request

Fixes #61594

#59556 changed atmos tanks so that they do not automatically connect to adjacent pipes, but can support up to 4 directional connection, and merge with neighboring tanks to form one large one. Old tanks would connect based on their dir variable. New tanks would not. A work around was to varedit both dir *and* initialize_direction variables to the same value in the map editor - but this is not expected behavior for mapping.

This adds a check for mapload in the tank's initialize proc. If the tank is initializing during mapload, dir will be copied to initialize_directions (as it is in most other atmos devices), and the tank will connect in the specified direction(s). 

The behavior of player constructed tanks is unchanged.
## Why It's Good For The Game

The primary purpose of these large, constructed atmos tanks is to provide a bulk source of gas to a map, such as a plasma tank for the incinerator, or air supply tanks to ruins or disconnected parts of the station. This enables them to be readily used for their purpose.
This fixes the 41 broken atmospheric tanks currently mapped in the codebase.

## Changelog

:cl:
fix: Mapped in atmospheric tanks will now connect to pipenets in the appropriate direction
fix: Icebox, Runtime, and a number of ruins have had their gas tanks rotated or repiped
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Tested? (Especially on ruins)

**Comment by Maurukas** [comment]
Double checked and found one additional issue on the Hotel - it was converted to use layer 4 distro, but never given a layer adapter.

**Comment by LemonInTheDark** [comment]
:)

**Comment by LemonInTheDark** [comment]
I think this might? still break for things like shuttles, but I'm not totally sure. Hard to tell, can worry about it if it comes up in future

**Review by LemonInTheDark — APPROVED** [review]

**Comment by newfren** [comment]
hooray I can refill xenobio again

**Pull request merged**
