### PR TITLE
adds a testicular torsion smite

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

said smite gives them testicular torsion then gibs them after 1.5 seconds
(sound on)

https://github.com/tgstation/tgstation/assets/70376633/0cdf80bb-39cf-4df1-97cf-efc973907a30

## Why It's Good For The Game

funny

## Changelog
:cl:
admin: added a testicular torsion smite
/:cl:

### CODE REVIEW

**Comment by Singul0** [comment]
make a message visible to all near the target so they know what happened?

**Comment by mc-oofert** [comment]
> make a message visible to all near the target so they know what happened?

not sure what to write

**Comment by Jolly-66** [comment]
Men who see this PR:

image

**Comment by Iamgoofball** [comment]
Spacemen do not have genitalia and thus cannot have testicular torsion.

**Comment by nikothedude** [comment]
i say always be wary with genitalia references since github can get a little :eye: at it

**Comment by EricZilla** [comment]
CB/tg/

**Comment by ChungusGamer666** [comment]
god tier

**Comment by ChungusGamer666** [comment]
> i say always be wary with genitalia references since github can get a little 👁️ at it

Jamie pull up skyrat-tg github

**Comment by mc-oofert** [comment]
> Funny little not actually fun at all medical problem aside, this is just delayed gibbing. Call me a contrarian, but unless it does something more than that, it isn't even worth adding to the list of smites.

okay mr.contrarian but i do think getting your nuts twisted by an admin before exploding from pain is pretty funny

**Comment by ChungusGamer666** [comment]
@mc-oofert it's funny yeah but it doesn't have unique sound effects or visual effects, isn't that kinda half assed?

**Comment by Sealed101** [comment]
make the victim tilt a few degrees or something, really needs more than just a scream and a delayed gib

**Comment by Fikou** [comment]
I mean I guess what I'm trying to say is if you actually need the cock boiler to get off then buy the cock boiler but don't let Society trick you into thinking that everybody needs a cock boiler some people need to have their cocks boiled some people are content with them just being at like ambient human body temperature
it's the same with like skydiving or dancing you know
you know all I'm saying is these pro skydiving mfers have been real quiet ever since the submarine imploded

**Comment by mc-oofert** [comment]
> I mean I guess what I'm trying to say is if you actually need the cock boiler to get off then buy the cock boiler but don't let Society trick you into thinking that everybody needs a cock boiler some people need to have their cocks boiled some people are content with them just being at like ambient human body temperature it's the same with like skydiving or dancing you know you know all I'm saying is these pro skydiving mfers have been real quiet ever since the submarine imploded

whar

**Pull request closed without merging**
