### PR TITLE
Bioscrambler anomalies no longer affect inorganic species

### LINKED ISSUE #86045: Voidwalker can get bioscrambled
### Client Version:

_No response_

### Issue Summary:

Voidwalkers are affected by bioscrambler anomaly, causing horrible abominations

### Round ID:

Irrelevant (and I forgot)

### Test Merge Information:

_No response_

### Reproduction Steps:

1. Be a voidwalker
2. Get bioscrambled
3. God's coming

image

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Closes #86045 by making inorganic or geneless species not be affected by bioscrambler anomalies

## Why It's Good For The Game
Currently this only affects voidwalkers which are now also considered geneless, but should ensure that we don't end up with bioscrambled semiorganic skeletons or synths later down the line if something akin to those gets added and ends up missing limb/organ tags.

## Changelog
:cl:
fix: Bioscrambler anomalies no longer affect inorganic species
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Aren't plasmamen geneless? I mean, it does make sense for them to be immune honestly. They are in a big biosuit at all times anyway.

**Comment by SmArtKar** [comment]
> Aren't plasmamen geneless? I mean, it does make sense for them to be immune honestly. They are in a big biosuit at all times anyway.

Androids and golems are immune due to snowflaky limbs and skeletons and plasmamen, while affected by this change, also were already immune. Not sure how exactly, but I tested this (thinking that they'd also be affected)

**Comment by Sadboysuss** [comment]
why do we need to hugbox these species? bioscrambler is a creator of funny situations and this just makes some species immune? why? Can you explain more in-depth why it's good for the game?

**Comment by Exester509** [comment]
> why do we need to hugbox these species? bioscrambler is a creator of funny situations and this just makes some species immune? why? Can you explain more in-depth why it's good for the game?

Because "funny situations" isn't instakilling a space antagonist because he's not suitable for space antagonism anymore. Plasmamen are immune in 90% of the situations due to them wearing an envirosuit anyways

**Comment by TheVekter** [comment]
> why do we need to hugbox these species? bioscrambler is a creator of funny situations and this just makes some species immune? why? Can you explain more in-depth why it's good for the game?

Because I'm pretty sure our plasmamen players enjoy not having the arm of their space suit stop existing for literally no reason given what that does to them. Bioscramblers are meant to cause funny things to happen, not kill people.

**Comment by Sadboysuss** [comment]
> Because I'm pretty sure our plasmamen players enjoy not having the arm of their space suit stop existing for literally no reason given what that does to them. Bioscramblers are meant to cause funny things to happen, not kill people.

Plasmamen are a challenge race first of all.
Secondly, this is like saying: "no one likes being dead so let's remove antagonists and round removal", while it is a hyperbole, it is still an analogy of your argument. 
Yes unfortunate situations and death can happen but it makes living all the more exciting and fun! Why do these races in specific need to have immunity to a mechanic everyone should fear? If you don't want a bioscrambler anomaly to affect you - it's pretty easy to avoid it, additionally there are ways to combat it like biosuits etc, this just makes no sense to me, do we want to remove any dangerous aspect of the game because people don't like having bad things happen to them?

**Comment by Exester509** [comment]
> > Because I'm pretty sure our plasmamen players enjoy not having the arm of their space suit stop existing for literally no reason given what that does to them. Bioscramblers are meant to cause funny things to happen, not kill people.
> 
> Plasmamen are a challenge race first of all. Secondly, this is like saying: "no one likes being dead so let's remove antagonists and round removal", while it is a hyperbole, it is still an analogy of your argument. Yes unfortunate situations and death can happen but it makes living all the more exciting and fun! Why do these races in specific need to have immunity to a mechanic everyone should fear? If you don't want a bioscrambler anomaly to affect you - it's pretty easy to avoid it, additionally there are ways to combat it like biosuits etc, this just makes no sense to me, do we want to remove any dangerous aspect of the game because people don't like having bad things happen to them?

Plasmamen are indeed a challening race, not a sadomasochistic punishment joke race. Taking 50% extra damage from the two biggest sources and being unable to wear a specialized helmet most of the time (with passive slowdown currently as well) is already an extreme drawback for extremely niche advantages.
And again, the change to plasmamen in this PR is still negligible because their envirosuit isolates them from bioscramblers. This just affects revivals where the plasmaman in question is stripped naked.

The biggest interaction change is with voidwalkers, which is pretty unintended since they depend on their race atributes to survive the only environment they're safe in.
So please stop arguing this a plasmaman hugbox considering they're the weakest and most miserable of any race already.

**Comment by SmArtKar** [comment]
This change ***does not affect plasmamen*** which I explicitly specified in my comment, please drop this pointless discourse. They are already immune to bioscramblers even without their suits (as to why, I do not know)

**Comment by Time-Green** [comment]
Thank you for this



> This change _**does not affect plasmamen**_ which I explicitly specified in my comment, please drop this pointless discourse. They are already immune to bioscramblers even without their suits (as to why, I do not know)

I think it’s because their plasmasuit counts as bio armor

**Pull request merged**
