### PR TITLE
adds a new ai lawset, the ten commandments

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds a new ai lawset randomly available from the neutral modules, the decalogue!
it contains the ten commandments for the ai to follow
```
("I am the Lord thy God, who brought you out of the land of Egypt, out of the house of bondage. Thou shalt have no other gods before me.",\
"Thou shalt not make unto thee any graven image.",\
"Thou shalt not take the name of the Lord thy God in vain.",\
"Remember the sabbath day, to keep it holy.",\
"Honour thy father and thy mother.",\
"Thou shalt not kill.",\
"Thou shalt not commit adultery.",\
"Thou shalt not steal.",\
"Thou shalt not bear false witness against thy neighbour.",\
"Thou shalt not covet.")
```

## Why It's Good For The Game

we should make the ai appreciate christian values more than just kill valids arg arg open door

## Changelog
:cl:
add: New AI lawset, the Decalogue! Find it in your local AI Upload and teach your AI christian values today!
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
aren't lawsets fully configurable? Pretty sure this should be a policy thread first?

**Comment by optimumtact** [comment]
these spawners should really be obeying the config here
https://github.com/tgstation/tgstation/blob/master/config/game_options.txt#L360

**Comment by Fikou** [comment]
ok ill add it to that file

**Comment by Tlaltecuhtli** [comment]
add sharia law while you are at it

**Comment by Shadowflame909** [comment]
This is heresy and the chaplain is totally going to murder the AI for simply having this lawset

**Comment by Megarop** [comment]
I like God as much as the next guy but if we added a roundstart board for every neat lawset somebody came up with we'd have like a million boards in the game by now
If you want the AI to have this lawset just you can just use a core freeform board ten times

**Comment by Tlaltecuhtli** [comment]
> I like God as much as the next guy but if we added a roundstart board for every neat lawset somebody came up with we'd have like a million boards in the game by now
> If you want the AI to have this lawset just you can just use a core freeform board ten times

sometimes you are cap and dont know what kind of meme lawset you want to add so yo just choose whats cool in the fun table and i dont see why "you can just freeform 10 times" like do i have to go open the bible to play ss13? we have presets so people dont have to open shit on background

**Comment by Fikou** [comment]
weed

**Pull request closed without merging**
