### PR TITLE
Removes the antimatter engine

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

I don't know why this is still in the game. Not balanced in the slightest, ugly as sin, risk free, simple compared even to tesla and singulo, it just goes on.

## Why It's Good For The Game

gets rid of pointless unbalanced bloat

## Changelog
:cl:
del: Removed the antimatter engine
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Remove don't improve. I like it.

**Comment by Barhandar** [comment]
Safe cargo engine as opposed to having them build a tesgulo + memes about being able to just EXTEND it into infinity.

**Comment by Tlaltecuhtli** [comment]
cargo now has to build solar panels

**Comment by habader** [comment]
ive never once seen it built

**Comment by MCterra10** [comment]
Instead of being lazy and ripping it out, actually add some interesting stuff to it like containment breach

**Comment by actioninja** [comment]
We already have SIX other station-usable power sources not including the antimatter. It's not needed.

**Comment by Detective-Google** [comment]
AM engine isn't "risk free", any jackass can go and pump up the injector rate and blow it up.

that being said shit looks like it's straight out of 2005 and needs to be Reworked or removed probably.

**Comment by SouDescolado** [comment]
Go Solars or go home _~flashbacks of being killed by nukies~_

**Comment by Timonkeyn** [comment]
sad gamer moment

**Comment by optimumtact** [comment]
bitch you probably never even used this ugly ass looking thing

**Pull request merged**
