### PR TITLE
Adds getPixelDistance()

### PR DESCRIPTION
**Pull request by RemieRichards**
Adds a proc for finding the distance between two atoms, in pixels

It seems that when I'm bored I make random functions relating to pixels. Whatever.
Maybe one day I'll have added enough pixel functions that we can move to pixel movement :P

(If you want to be pedantic, this calculates the distance in pixels from the edge of each atom's turf, I _could_ offset this by half the width of world.icon_size but the actual distance value remains the same, that's how distance works kids)

### CODE REVIEW

**Comment by RemieRichards** [comment]
@Miauw62 that's not how it works :P 

If you edit a file, you get the option of "Commit upstream" or "Auto make a branch"
I just cba to make a local branch, I did this when I added Destroy() to pooling and that all worked out fine.

**Comment by Miauw62** [comment]
can't you just do the edit on your own fork :V (that automakes a branch for you too)

**Comment by RemieRichards** [comment]
Eh, either way works, Plus I always have a tab idle on /tgstation/-tg-station so it was easier this way :P

**Comment by optimumtact** [comment]
Except now everyone who tracks tg gets it :smile:

**Pull request merged**
