### PR TITLE
Return of ore stacking, various changes to lavaland bombs to facilitate reduced lag

### LINKED ISSUE #33712: Server Crash via Too many minerals in mining satchel of holding
Issue reported from Round ID: 80519 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% LAG FREE])

Server started lagging VERY hard when I was mining with bombs and picking up ore. Lag started as soon as I was picking up ores, and stopped when I stopped picking them up. Sever eventually crashed right as I picked up some ore after not picking up anyone for about 10 seconds.

Probably reproducible pretty easily with either another mining satchel of holding or an ore box.

Also not the first time this has happened to me while mining.

### LINKED ISSUE #35336: sheets of ash only making one brick
when you make bricks from say 5 ash in a sheet, you'll only get one sand block instead of the 5 you're supposed to get

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
First things first, @kevinz000 had no part in the "bomb balance" aspects of this PR, he "only" made the original ore-stacking PR which I cherry-picked into this one. It just so happens to be the majority of this PR's contents so leaving his name out would have been unfair. 

:cl: Naksu and kevinz000
tweak: Ores are no longer completely impervious to explosions, but rather "proper" ores are destroyed by the strongest explosions and sand is blown away everything but the weakest ones. This shouldn't affect ore spawns from explosions
tweak: Lavaland bomb cap reduced to double the station bombcap.
refactor: Ores are now stackable. Ore stacks now have the appearance of loose ores and are not called "sheets" by machines that consume them.
code: Material container component now uses the singular names of stack objects.
refactor: /obj/item/ore/Crossed() is now removed in favor of the ore satchel utilizing a redirect component
/:cl:

stacks:
image

[why]: 

Every now and then someone lags the server to hell with bombs that never resolve without admin intervention or a server crash. Implementing a bomb cap didn't much help with this issue, as two bombs resolving at the same time is possibly worse than the megabombs you used to be able to make with fusion. This PR hits every part of the problem apart from explosions themselves, likely solving the lavaland special case problem with explosions.

Fixes #35336
Fixes #33712

### CODE REVIEW

**Comment by DaedalusGame** [comment]
You say that instating a bomb cap didn't help this issue so why would you decrease the bomb cap anyway

**Comment by vuonojenmustaturska** [comment]
Because with the change you'll need twice as many bombs to affect the same amount of turfs, current bomb cap affects 11k roughly and the new one affects 5k. The smaller bomb may even actually resolve.

**Comment by Bawhoppen** [comment]
So is this code magic to make the stacks look like their loose ore sprites but are all the same item?

**Comment by vuonojenmustaturska** [comment]
Yes, that's the modification i made into kevinz's ore stacking, besides fixing a stack-related wart in the material storage component

**Comment by KorPhaeron** [comment]
@mrstonedone

**Comment by Buggy123** [comment]
With the testmerge, when you have a satchel and are dragging the ore box, ores are _not_ automatically put in the ore box(normally they are). This is astronomically annoying.

**Review by MrsTonedOne — APPROVED** [review]

**Comment by vuonojenmustaturska** [comment]
DNM while i re-add autoboxing and fix the bugs

**Comment by vuonojenmustaturska** [comment]
image
* Making sandstone now uses the sheet crafting mechanic, allowing additional recipes to be added.
* Picked-up ores are now autoboxed automatically, as before.
* Ore box contents list formatting is fixed

**Pull request merged**
