### PR TITLE
removes comments that do not contribute to code understanding

### PR DESCRIPTION
**Pull request by optimumtact**
GET OUT

### CODE REVIEW

**Comment by Xhuis** [comment]
http://i.imgur.com/yNlQWRM.jpg?fb

**Comment by optimumtact** [comment]
comments should be relevant to the code at hand. because all comments add developer overhead, as we have to maintain them.

**Comment by KorPhaeron** [comment]
muh culture

**Comment by Incoming5643** [comment]
Someday someone is just gonna try and remove all comments from the codebase. I can feel it.

**Comment by Shadowlight213** [comment]
@Incoming5643 the someone is oranges and the someday is soon

**Comment by Ricotez** [comment]
while we're on the subject it might be helpful to agree on some kind of standardized way to comment code

for example I started using javadoc because I am used to it, but it feels kinda wrong in BYOND

**Comment by optimumtact** [comment]
As long as the comments are illustrative and highlight important features that are not necessarily visible from just viewing the code then I'm fine with them.

**Pull request merged**
