### PR TITLE
Adds killstreaks

### PR DESCRIPTION
**Pull request by Buggy123**
:cl:
add: Centcom now offers kill tracking, courtesy of their MLG360PRO subsidiary.
/:cl:
image
tOO LATE

Open to suggestions for more killstreak names. Shamelessly copied from #14059, credit KorPhaeron.

### CODE REVIEW

**Comment by calzilla1** [comment]
Can you give me admin rank for a sec so i can can this guy

**Comment by calzilla1** [comment]
Also, where the fuck is killionare

**Comment by Buggy123** [comment]
Added, how could i have forgotten?

**Comment by 81Denton** [comment]
>no global audio files playing

shit PR

**Comment by Buggy123** [comment]
I'll put it in the queue.

**Comment by JohnMcLaime** [comment]
Add killstreaks higher than 15.

**Comment by kevinz000** [comment]
fuck off and stop encouraging more TDM than there already is.

**Comment by Buggy123** [comment]
!(https://imgur.com/I13kBX6)[]

**Pull request closed without merging**
