### PR TITLE
Tones down Supermatter Singularity sound effect

### LINKED ISSUE #11926: Supermatter singularity noise is too jarring.
Its overkill, make it have a weird noise but this high-pitched headphone user-killing noise is dumb.

### PR DESCRIPTION
**Pull request by Lijah99**
Fixes #11926

I essentially lowered the amplification, it is still completely noticeable, but it's nowhere near like living in the Projects of Detroit.

### CODE REVIEW

**Comment by Anonus** [comment]
I think something is fucked up because this does not appear to be an actual sound.

**Comment by Lijah99** [comment]
Well, I used audacity to edit the file, and it was an ogg file, so converted it back

**Comment by Lijah99** [comment]
I just started yesterday, so I'm bound to screw up

**Comment by WJohn** [comment]
:+1:

**Comment by Xhuis** [comment]
Might wanna add "Fixes #11926" in the OP

**Comment by Razharas** [comment]
Thats not a sound file

**Comment by optimumtact** [comment]
Yeah I checked out your branch and tried to play the file, looks like it exported incorrectly

**Comment by Lijah99** [comment]
woops, I can fix that easily. Do I have to make a new pr or can I edit it from here?

**Comment by optimumtact** [comment]
you should be able to edit it locally, then commit the fixed/updated file in git and then push the new commit onto this branch

**Comment by Razharas** [comment]
@Lijah99

**Comment by Lijah99** [comment]
Too meme-like, will not do.

**Pull request closed without merging**
