### PR TITLE
Removes Bloodbrothers

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Removes bloodbrothers from the code.

Given permission to do this by armhulen and oranges over voice chat.
I was working on a fix for blood brothers while in vc when I was told to just remove them, so that's what I'm doing.

## Why It's Good For The Game

It's out of rotation and it's buggy, there's no indication on who your blood brother even is outside of one line of text in chat when you first get the antag datum.
It's currently out of rotation, so this wouldn't affect the servers at all, except maybe if admins ever give this antag out (for some reason).

## Changelog

:cl:
del: Blood brothers have been removed entirely.
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
It was such a clunky gamemode.  Kind of a mix between traitors and cult but it sucked.

**Comment by RaveRadbury** [comment]
I'd be interested in re-enabling BB for MRP if the bugs were fixed.

**Comment by NamelessFairy** [comment]
I'll echo my fellow headmin on this, I've attempted to bring up the topic of re-enabling blood brothers if there was drive to improve it in the past and making it functional again would be a good start.

**Comment by Dawson1917** [comment]
I think BB would work well brought into rotation for MRP. The main reasons people hated it before was 1) getting BB meant you didn't get an uplink with gamer gear and instead had to work together with someone else (yuck) and 2) if you didn't get a Gamer as your BB then you were pretty much fucked if you didn't do all the objectives by yourself and couldn't rely on them.

Now that there are fewer players obsessed with just winning the game, #1 would probably be less of a problem and for #2 people are a lot more willing to RP or at least work together than before. I really wouldn't call it a bad antag role, or one that ought to be removed.

**Comment by ExcessiveUseOfCobblestone** [comment]
If it was in rot I would be ok with keeping it in but until then it should just be removed until it’s actually fixed

**Comment by itseasytosee** [comment]
Does anyone have a comprehensive list of all the bugs?

**Comment by JohnFulpWillard** [comment]
> Does anyone have a comprehensive list of all the bugs?

From what I'm aware of, the problems at the moment is that Bloodbrothers don't know who their fellow blood bros are because there's no indication in antag ui or memories, and admins have no way to add more than 2 Bloodbrothers per team despite there being able to have 3 roundstart.

**Comment by MrMelbert** [comment]
> I'd be interested in re-enabling BB for MRP if the bugs were fixed.

I ran a BB round on Manuel a week or so ago to less than thrilling results - 15 threat was spent for one team of two brothers. (The team itself hardly interacted at all, but it's a small sample size obviously so do with that what you will)

I noticed though that despite being enabled for like a year now, roughly half the online players had BB enabled in prefs. (27 / 54, but again, sample sizes and whatever)

**Comment by RaveRadbury** [comment]
> If it was in rot I would be ok with keeping it in but until then it should just be removed until it’s actually fixed

https://tgstation13.org/phpBB/viewtopic.php?p=623670#p623670

Blood Brothers have been enabled on MRP Dynamic

**Comment by Mothblocks** [comment]
My player reference

**Comment by JohnFulpWillard** [comment]
> My player reference

the preference icon is probably the most work anyone's ever put into bloodbrothers.

**Comment by Mothblocks** [comment]
I was gonna reuse it for like imaginary friend without the blood if this went through

**Comment by tralezab** [comment]
sounds like it isn't if headmins re-enabled it within 11 hours of the pr opening

**Comment by JohnFulpWillard** [comment]
headmins gave me an L today

**Comment by Shadowflame909** [comment]
> > If it was in rot I would be ok with keeping it in but until then it should just be removed until it’s actually fixed
> 
> https://tgstation13.org/phpBB/viewtopic.php?p=623670#p623670
> 
> Blood Brothers have been enabled on MRP Dynamic

based headmins saving blood brothers

**Pull request closed without merging**
