### PR TITLE
Brings the atmos code together in modules.

### PR DESCRIPTION
**Pull request by Firecage**
This brings the various atmos code together under Modules.

Added a folder in modules named atmospherics.

atmospherics.dm from code/ATMOSPHERICS moved to code/modules/atmospherics  (renamed: atmosmachinery.dm)

pipeline.dm from code/ATMOSPHERICS/ moved to code/modules/atmospherics (renamed: datum_pipeline.dm)

code/LINDA's contents moved to code/modules/atmospherics/environmental

gas_mixture.dm from code/datums, and gas_types.dm from code/ATMOSPHERICS, both moved to code/modules/atmospherics/gasmixtures

code\ATMOSPHERICS\components's contents moved to code\modules\atmospherics\machinery\components (components.dm renamed to base_components.dm)

code\ATMOSPHERICS\pipes's contents moved to code\modules\atmospherics\machinery\pipes

zvent.dm, meter.dm, area_atmos_computer.dm moved from code\game\machinery\atmoalter to code\modules\atmospherics\machinery\other

scrubber.dm, pump.dm, portable_atmospherics.dm, canister.dm moved from code\game\machinery\atmoalter to code\modules\atmospherics\machinery\portable

atmos_alert.dm, atmos_control.dm moved from code\game\machinery\computer to code\modules\atmospherics\machinery\atmoscomputers

airalarm.dm moved from code\game\machinery to code\modules\atmospherics\machinery

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Please detail the folder change in a clear and concise way akin to #14735

**Comment by Firecage** [comment]
Sure, why not

**Comment by neersighted** [comment]
I think the atmos prefix on this is a little silly, but other than that, :+1:.
Fire alarms are probably also an atmos machine.

**Comment by Firecage** [comment]
@neersighted Mmm, I think a fire alarm is more along the lines of the generic things.

**Comment by tkdrg** [comment]
Note that this changed the line endings of all the atmos files as well.

**Pull request closed without merging**
