### PR TITLE
Riot and combat shotgun sprite changes.

### PR DESCRIPTION
**Pull request by pireamaineach**
Just tossing this tiny P.R. out there since I've heard people whinge about the new sprites.

Shotguns

### CODE REVIEW

**Comment by actioninja** [comment]
I assumed this would be a revert from the title but I actually like these.

**Comment by Tlaltecuhtli** [comment]
the old ones look more futuristic

**Comment by GuppyLaxx** [comment]
The old ones look like you grabbed a long gun and smeared it with shitty cyberpunk themed paint

**Comment by InsaneKatrina** [comment]
I'd argue the current ones are better since their sprite work is really nice looking in general (yes, even say the paintjob (or whatever that is) is fine) where as these feel a little lacking. I mean sure if the new sprites will get a better rendition of them than what they are currently I'd be happy to see if it changes my mind, otherwise they seem a little eh. Maybe some fancy the simpler look idunno.

**Comment by pireamaineach** [comment]
> the old ones look more futuristic

Futuristic and shotgun aren't words I often associate with eachother.

**Comment by nicbn** [comment]
You could make the recolored parts pale  green, I think it would look more fitting than wood

**Comment by pireamaineach** [comment]
I've seen plenty of police shotguns with wooden furniture.

**Comment by dr-bee** [comment]
Better sprites, as it clearly communicates that the shotgun is pump action and not some sort of semi-automatic like the combat shotgun.

Current sprites are too futuristic and dont communicate that you need to manually rack the shells at all.

**Comment by HomocidlePancakes** [comment]
Um. Combat shotgun is just a black recolor of riot one. ummmmmmmmmmmmmmm

**Comment by pireamaineach** [comment]
It's not.
There's notable differences between them.
Most semi-automatic combat shotguns aren't very unique looking, besides having the fixed foregrip and a bolt.

**Comment by pireamaineach** [comment]
Hm... maybe I could tweak this to make the fixed grip more obvious. Look better if nothing else.

**Review by ExcessiveUseOfCobblestone — DISMISSED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
are the inhands that generic they don't need to be changed as well?

**Comment by pireamaineach** [comment]
> are the inhands that generic they don't need to be changed as well?

They've always actually not fit with almost any sprite. They don't fit with the current ones, either.

**Comment by ExcessiveUseOfCobblestone** [comment]
ok lol

**Comment by GravitronBlue** [comment]
Forgotsomething
Missing a sprite change in [icons\mob\back.dmi]
(Immersion crushing shotgun shells)

**Comment by ExcessiveUseOfCobblestone** [comment]
they're on the other side of the shotgun ;)

**Pull request merged**
