### PR TITLE
Tweaks blob burst times upwards, adds LORE

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Procedure 5-6 may be issued for biohazard containment under certain situations.
tweak: Blobs will now burst slightly later on average, and the nuke report with the nuke code will arrive slightly earlier.
/:cl:

This changes the burst time from a minimum of 2 minutes, 40 seconds and a maximum of 7 minutes, 40 seconds to a minimum of 5 minutes and a maximum of 7 minutes, 30 seconds.

In addition, the nuke report will arrive 40 minutes after the blob report is send in.

There's a nifty lore paper when the blob report is sent in, as a bonus.

### CODE REVIEW

**Comment by Jordie0608** [comment]
\>Changelog for some lore and not the actual change
bb plz

**Comment by Anonus** [comment]
who cares about changes I play for phat lore, half of which I added myself

**Comment by LatD** [comment]
Blobs really need a timer to show when the burst is going to happen. This alone would be a big buff to blobs

**Comment by tkdrg** [comment]
okay sure why not

**Pull request merged**
