### PR TITLE
Hand labelers cannot be used on any mobs.

### PR DESCRIPTION
**Pull request by harmonyn**
Closes https://github.com/tgstation/tgstation/issues/17743. If you want to rename a mob this is what pet collars are for, plus there are just too many checks

also feel free to suggest a less shitty word than "creatures"

### CODE REVIEW

**Comment by coiax** [comment]
what about `mobs`

**Comment by bgobandit** [comment]
that's more a code term

**Comment by XDTM** [comment]
Living beings

**Comment by coiax** [comment]
Are shades, bots, zombies alive?

**Comment by octareenroon91** [comment]
`beings`
`entities`
`something sentient`
`any which know their own name`

**Comment by bgobandit** [comment]
"living things" won't work, this also counts for dead mobs

**Comment by octareenroon91** [comment]
`"The hand labeler cannot make one forget their own name!"`

**Comment by PKPenguin321** [comment]
:-1: x 100
I like to name my monkeys
Just fix Ian changing name in attackby erroneously

**Comment by bgobandit** [comment]
then get pet collars

**Pull request merged**
