### PR TITLE
Updates Mapping Sprite for Interrogation

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

This PR updates the DMI file for the mapping area turf for the Interrogation room.

## Why It's Good For The Game

This does not look good in the slightest:

image

This is better.

image

## Changelog

:cl:
imageadd: The "Interrogation Room" area now has a new sprite to define it on the mapping end.
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Looks fine

**Review by Twaticus — CHANGES_REQUESTED** [review]
uses the wrong font
image

**Comment by san7890** [comment]
> uses the wrong font
> 
> image
> 
> 

Ack, I'll fix it later.

**Review by Twaticus — APPROVED** [review]
ty

**Comment by san7890** [comment]
hold on i have no idea what's going on here

**Comment by san7890** [comment]
all those commits were me trying to figure out how to fix the conflict WITHOUT having the DMI Merge Git Hook installed.

**Comment by ShizCalev** [comment]
image
🤔

**Comment by san7890** [comment]
> image 🤔

It shouldn't have any effect, it's probably because of what I tried to trouble shoot the merge conflict. My master is fucked beyond recognition, and I initially tried to merge it there, and it somehow just nabbed whatever the fuck was in there. I'm pretty sure that was the disposals fix I did earlier this month.

It's also present in this PR: https://github.com/tgstation/tgstation/pull/64120

And: 
image

The git hooks are there now and I resolved the conflict a different way.

**Pull request merged**
