### PR TITLE
Players can disable the ability to receive solo antag objectives in their prefs

### PR DESCRIPTION
**Pull request by Y0SH1M4S73R**
:cl: Y0SH1_M4S73R
add: Adds a new preference, "Get Solo Objectives", that enables receiving objectives as a traitor, changeling, wizard, or ninja. This preference is enabled by default.
admin: Admins can still manually give objectives to antagonists with the "Get Solo Objectives" preference disabled.
tweak: Antagonists without objectives cannot receive greentext or redtext.
/:cl:

This PR is meant to make being an antagonist more enjoyable for people with excessively goal-oriented personalities (such as (and especially) myself; label this as "i ded" if you want). Such people may find that having an objective compels them to complete that objective, even if it would be more enjoyable to fuck around and be gimmicky. Furthermore, I feel that #32356 acts as an insult both to players that don't give a fuck and give too much of a fuck about their objectives. In the end, there should be no problem with a PR that allows players to enjoy the game more without making other players enjoy the game less, should there?

### CODE REVIEW

**Comment by nicbn** [comment]
the problem here is murderboning

**Comment by Iamgoofball** [comment]
@nicbn you can do what you want as an antag

**Comment by Cyberboss** [comment]
Having a preference control over objectives doesn't smell good to me

**Comment by Iamgoofball** [comment]
@Cyberboss this'll be fine, this lets people not have people whining at them about objectives post-game because they didn't have any

**Comment by lzimann** [comment]
What is next, preferene to auto complete your objectives?

**Comment by kevinz000** [comment]
The problem here is murderbone and everyone without objectives turning the round into a near free for all.
I've rarely met admins on tg who will completely ignore you if you have an interesting gimmick instead of wanting to do normal antaggy stuff.

**Comment by Y0SH1M4S73R** [comment]
@Cyberboss Most players can choose to disregard their objectives. This PR extends a branch to players who are psychologically inclined to force themselves to work towards their objectives at the expense of their emotional well-being. Maybe I can make this preference whitelisted.

@lzimann This isn't about greentext. This is about giving up the possibility of greentext to avoid the possibility of redtext.

**Comment by lzimann** [comment]
If you are scared of failing, or care too much about failing, disable antag and you won't have any problems.

**Comment by Y0SH1M4S73R** [comment]
@lzimann But then you never get the opportunity to do things that would get you banned as a non-antag.

**Comment by Iamgoofball** [comment]
@KorPhaeron are solo antags required to do objectives because your dipshit admins won't stop doing the 
"it's not REQUIRED to do objectives but you know *winky face*"

**Comment by Alecw155** [comment]
are people actually implying that objectives have EVER prevented murderboning?

**Comment by Iamgoofball** [comment]
^^^^

that too

**Comment by Iamgoofball** [comment]
going to ping @ausops as well because relevant

**Comment by kevinz000** [comment]
Player issue don't play to win :^)

**Comment by ShizCalev** [comment]
Is a sound playing when you don't accomplish your objectives really that insulting?

**Comment by kevinz000** [comment]
@Alecw155 something something even though antags "can do anything" there's something about a steal objective for plasma tank/tech levels killing everyone and stalling everyone in dead chat for 2 hours versus someone with hijack.

**Comment by Y0SH1M4S73R** [comment]
@Kevinz000 I see your point, but the shuttle autocalling in response to mass casualties is a thing.

**Comment by Alecw155** [comment]
could someone be banned from antag for killing literally every other person on the station when their goal was magboots? if no, this PR won't affect player behaviors at all

**Comment by Arianya** [comment]
A level of preferences too deep, IMO.

**Comment by Cyberboss** [comment]
I think I'm just going to stop this here. Yes, you can do whatever you want as an antag, but at the same time you have objectives given to you and it's on you for disregarding them. Also, giving players a choice in their objective handouts also undermines any semblance of game design we're trying to accomplish.

**Comment by optimumtact** [comment]
"excessively goal-oriented personalities"

**Comment by Y0SH1M4S73R** [comment]
If giving players a choice in their objective handouts undermines tgstation's game design, then my personality undermines my ability to enjoy the game in the way it was meant to be enjoyed. Best not let the door hit me on my way out.

**Comment by lzimann** [comment]
bye

**Comment by Iamgoofball** [comment]
@KorPhaeron can you reply or what, i'll reopen this

**Pull request closed without merging**
