### PR TITLE
Medals are no longer instant to pin

### PR DESCRIPTION
**Pull request by lzimann**
Kinda stupid being instant to be honest, now it takes 2 secs(should be enough) to pin on someone and instant if you are giving yourself a medal
:cl: Lzimann
:tweak: Medals are no longer instant to attach to someone's jumpsuit.
/:cl:

### CODE REVIEW

**Comment by Shapsy** [comment]
But why?

**Comment by InsaneHyena** [comment]
C4 memes.

**Comment by Aloraydrel** [comment]
Booo

**Comment by PKPenguin321** [comment]
fixes https://github.com/tgstation/tgstation/issues/19270

**Comment by lzimann** [comment]
it is not removing c4ing a medal, just removing instant medal pinning.

**Comment by ike709** [comment]
It doesn't really fix the issue if you still don't know the medal has C4 on it.

**Comment by jughu** [comment]
It gaurantees atleast if the suspicous fucking pinning faggot tries to pin you for no reason at all and before you know it *boom*

**Pull request merged**
