### PR TITLE
No more air leaks from the asteroid shuttle

### PR DESCRIPTION
**Pull request by Thunder12345**
image
:cl: Thunder12345
fix: The asteroid with engines strapped to it will no longer vent both the CentCom docks and its own entrance.
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Can you explain to the commoners (myself and others) what changes you made? Also air leakage is expected because of the nature in which it crashes into the map not so cleanly and that the open plan entrance is uninhabitable. Outside of being penetrated by a pickaxe, tiny fans underneath a simple airlock built in-front of the iron doors would fix the problem too.

**Comment by Thunder12345** [comment]
The problem was that there were a couple of holes in the left side of the shuttle that were exposed to space. One of these was connected to the docking wing itself, causing both it and the area with the doors to depressurise.

It would certainly be more logical for the exposed parts of the asteroid to be depressurised on arriving at the station, but as a consequence of that, the docking wing was left uninhabitable without admin intervention, as well as the extra work for atmos because of the slow draining of air.

**Comment by FantasticFwoosh** [comment]
But its not meant to be inhabitable past the doors on the left hand side docking least from what i understand of its initial design choices @Thunder12345 , pressurisation changes i could understand as a concern though like you say.

Couldn't a alteration to the ships structure to have a forward set of double airlocks (with the big fans) leading into the interior solve this instead?

**Review by ShizCalev — APPROVED** [review]

**Comment by Bawhoppen** [comment]
CentComM in changelog

**Pull request merged**
