### PR TITLE
Spetsnaz Pyro Bundle Rebalance

### PR DESCRIPTION
**Pull request by BeeSting12**
I made the stetchkin APS pistol smaller so it can fit on the ops belt. I also made 9mm mags purchasable for 2 TCs each, seemed like a fair price since they do the same as a stetchkin and you get roughly twice as many bullets.

:cl: BeeSting12
balance: The stetchkin APS pistol is smaller.
add: The 9mm pistol magazines can be purchased from nuke op uplinks at two telecrystals each. 
/:cl:

Why: Gun size seemed unintended, if it was intended then thats dumb. I just think it would be nice for the mags to be purchasable.

### CODE REVIEW

**Comment by kevinz000** [comment]
uhhh one difference
aps is burst.

**Comment by KingPhilipIII** [comment]
Whenever I use the bundle I buy a storage implant to put the gun and a sword away. Reducing the size is good in my opinion. Don't know how I feel about increasing the cost of bullets for whats supposed to be a last ditch sort of weapon.

**Comment by BeeSting12** [comment]
I'm not increasing the cost, I'm putting them in the uplink in the first place. 
@kevinz000 
i know

**Comment by Bawhoppen** [comment]
This will probably never hurt anything.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
