### PR TITLE
fixes a "typo"

### PR DESCRIPTION
**Pull request by anconfuzedrock**
I don't know what I am doing but hey now the shadycigs vendor description has a . in it if I did it right

### CODE REVIEW

**Comment by Time-Green** [comment]
Did you test this?

**Comment by anconfuzedrock** [comment]
I don't know how mate but its fucking adding a . to the end of the description of the cigarette vendor what could go wrong

**Comment by Time-Green** [comment]
The events could be catastrophic

**Comment by anconfuzedrock** [comment]
know what I'm gonna have to learn how to test shit anyway

**Comment by Thunder12345** [comment]
Could crash the server, better test it

**Comment by anconfuzedrock** [comment]
image
i think i did it

**Comment by anconfuzedrock** [comment]
wait shit I thought they removed the "it seems pristine and undamaged" messages but I got them, what does that mean?

**Comment by Time-Green** [comment]
You broke the server dude

**Comment by RemieRichards** [comment]
@anconfuzedrock you game is out of date, but it doesn't matter for such a small change it won't affect anything.

**Comment by anconfuzedrock** [comment]
alright what do I do to update it for the future

**Comment by RemieRichards** [comment]
@anconfuzedrock <B>pull</B> from the <B>remote</B> (/tg/) into your <B>local</B> (your version of the code) with git.

**Comment by anconfuzedrock** [comment]
as in right click and pull the folder with tortoisegit and set remote as remote?

**Comment by RemieRichards** [comment]
@anconfuzedrock you should already have /tg/ as a remote if you obtained your copy of the source code in a normal way (ie: not with the zip you fool)

**Comment by anconfuzedrock** [comment]
so, I should have another option under remote besides remote, and I'll have to get that going,  then for remote branch pick what?

**Comment by RemieRichards** [comment]
@anconfuzedrock is your remote /tg/ or your own branch? (you can see in tortoise)

**Comment by XDTM** [comment]
if you followed the instructions in the wiki it should be upstream, origin would be your fork

**Comment by anconfuzedrock** [comment]
image
I remember I got it not from the zip, from the clone or download link on my fork

**Comment by XDTM** [comment]
pick upstream and set master as the branch

**Comment by anconfuzedrock** [comment]
where do I pick upstream

**Comment by XDTM** [comment]
Where origin is right now, if it's there

**Comment by RemieRichards** [comment]
right that's origin, that's your remote not /tg/'s, you need another remote pointing to:
```https://github.com/tgstation/tgstation.git```

**Comment by anconfuzedrock** [comment]
huh, I don't have upstream, shit I'll get on that

**Comment by anconfuzedrock** [comment]
yes or no for "do you want to fetch remote branches from the newly added remote

**Comment by RemieRichards** [comment]
No.

**Comment by anconfuzedrock** [comment]
image
is this normal or should I have unchecked the putty thing

**Comment by RemieRichards** [comment]
I'm headed home so you'll have to get someone else to help as I won't be free.

**Comment by anconfuzedrock** [comment]
good news there was just a space I didn't notice im dumb

**Comment by bgobandit** [comment]
ur fat

**Comment by chanoc1** [comment]
rekt

**Pull request merged**
