### PR TITLE
FIIUXI SING RWEWSTLIGJN TO FEFOIRO RIGHTH

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: RIGIAMGO RTGOOFBAL
rscadd: ffuuuckkkeceftt goro makke worltuijhgsinn
experimental: DITI SFOOWKKRKS AArguiigiian
/:cl::cl::cl:

### CODE REVIEW

**Comment by LaharlMontogmmery** [comment]
HO MY GOD

YOU ACTUALLY FUCKING DID IT

YOU ABSOLUTE MADMAN

**Comment by evsey9** [comment]
No

**Comment by Iamgoofball** [comment]
TYUYUUUT ODSLFDKE  TOM TO OIIHT

**Comment by Iamgoofball** [comment]
# WHYYAEFYYYY

**Comment by evsey9** [comment]
You have a better chance of making you admin everytime the server starts getting merged than this

**Comment by LaharlMontogmmery** [comment]
I JUST LOOKED AT THE COMMIT

THIS IS ABSOLUTLY BLOODY GLORIOUS

MY SIDES

**Comment by X-TheDark** [comment]
I really want to comprehend what is going on...and yet I probably will never be able to.

**Comment by Iamgoofball** [comment]
@evsey9 thasrstt a godooweo oneda

**Comment by Thunder12345** [comment]
Goof go to bed and sleep it off, you're drunk

**Comment by Iamgoofball** [comment]
https://github.com/tgstation/tgstation/pull/18962

**Comment by LaharlMontogmmery** [comment]
@X-TheDark 

Goof came onto Basil completly drunk, barely able to type anything.
I challenged him to actually do a fix and push it on git on OOC. He logged off from the servers after that.
This is the result.

Ten outta ten, no regrets.

**Comment by Iamgoofball** [comment]
@LaharlMontogmmery ii got badnnenkekd on thge s evr evrs 4 dfyt66e00nsn meintues

**Pull request closed without merging**
