### PR TITLE
Adds [TRIGGERED] armband

### PR DESCRIPTION
**Pull request by Bawhoppen**
I've wanted to do this for so long

### CODE REVIEW

**Comment by tedward1337** [comment]
Not even ironically

**Comment by Bawhoppen** [comment]
i mean compared to hippie this is super tame

**Comment by tedward1337** [comment]
When dildos that impale get added, then we can start talking about nazi armbands

**Comment by xxalpha** [comment]
>it's real

what

**Comment by Bawhoppen** [comment]
WJ sprited it for me so like a gentleman I could not refuse

**Comment by xxalpha** [comment]
We added furry shit, so I will not object this.

**Comment by PKPenguin321** [comment]
to be very honest friends this is a quality feature

**Comment by Man-Shroom-** [comment]
to maintain server neutrality we must either add this or remove all the fur shit so :+1: 

besides it won't actually appear unless a mapper puts it in anyway

**Comment by PKPenguin321** [comment]
you can get it by hacking the secvendor to dispense contraband products

**Comment by Supermichael777** [comment]
give the Chaplin a Star of David necklace
or armband

**Comment by Bawhoppen** [comment]
fuck i would if i had a sprite

**Comment by Bawhoppen** [comment]
i should make it so anyone with the character name Adolf Hitler starts with one in their backpack

**Comment by Cheridan** [comment]
no

**Comment by Bawhoppen** [comment]
you cucking americano

**Comment by Xhuis** [comment]
We've reached a new low.

**Comment by xxalpha** [comment]
The low was furry.

**Comment by Bawhoppen** [comment]
I'm sorry for representing a group of people with their uniform standards in this game

**Comment by xxalpha** [comment]
We have nazi uniforms?

**Comment by Bawhoppen** [comment]
the thing that goes on their uniform you know

**Comment by xxalpha** [comment]
You mean armbands?

**Comment by Bawhoppen** [comment]
yes but i was being fancy about it goddamnit dont ruin the joke

**Comment by Bawhoppen** [comment]
holy cuck this was a quick meme I was hoping to get added for some meme rounds stop fucking with it

**Comment by optimumtact** [comment]
do you hear that? it's the sound of every maintainer scrambling to get a boot in

**Comment by Bawhoppen** [comment]
maybe they're just jealous I add a feature the players want

**Comment by duncathan** [comment]
My favorite part of this PR is the fact that it doesn't compile

**Comment by TheColdTurtle** [comment]
we have liggers and catpeople but THIS is out of line

**Comment by Bawhoppen** [comment]
ill fix that if you merge immediately

**Comment by Bawhoppen** [comment]
i put a period instead of a comma really ez fix just warm up the merge button

**Comment by optimumtact** [comment]
they need a few more boots in to get the message across

**Comment by Bawhoppen** [comment]
idk bro you should have seen ooc rejoice
but i guess it isnt a democracy

**Comment by optimumtact** [comment]
you're showing too much awareness, please enter the re-education chambers.

**Comment by Bawhoppen** [comment]
sorry we don't have those cause nobody knows who operates them without the armbands

**Comment by TheColdTurtle** [comment]
make sure to add an ss uniform

**Comment by Man-Shroom-** [comment]
just port the /vg/ nazi vendor

**Pull request closed without merging**
