### PR TITLE
[Pending new map vote poll]Removes all maps except for Box-station and Meta-station to fix feature rollout blockage.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

This pull request deletes Delta-station, Donut-station, and Pubby-station from the repository, including not only their .dmm files, but their job changes, additional code, and json definitions.

## Why It's Good For The Game
Say, for the sake of argument, a contributor wanted to rework medical so that the first line of healing is based on a surgery. They would, in order to ensure good gameplay flow, reorient and reorganize medbay so that surgery is not hidden in the back and obnoxious to get to. It would be better for it to be in the front, after all, since it is the most important section of Medbay at that point.

To do this, the contributor would need to edit five maps and rework Medbay on all five of those maps within the existing space Medbay occupies.
This entails designing **five separate medbays**.
Implementing all five of those separate medbays includes the following:

1. Manually re-pipe the atmospherics system and ensure it works properly, which takes a lot of time, while avoiding pipe overlaps, pipe-through-walls, and other various no-nos of the mapping process.
2. Manually re-wire the department and ensure it works properly, which takes less time but is still incredibly obnoxious.
3. Manually re-pipe the disposal network, which is an obtuse and awkward process with disposal sorting tags, a system that hasn't been changed for over seven or eight years.
4. Test the flow of the map and how it feels to move around in as a guest, how it feels to move around in as a department member, and how it feels to move around in as a department head.
5. Test the combat flow of the map as every antagonist type to ensure it does not excessively favor the antagonist in question or the crew in that matchup.
6. Test the combat flow of the map in crew versus crew situations.
7. Ensure the map is not easily broken into by non-department members which could render a department completely overrun by people who aren't supposed to be there.
8. Run the last 4 tests in a public environment all over again for multiple weeks.
9. Make changes based on that testing run.
10. Repeat until the map is satisfiying to play.

The maintainer(s) assigned to the project now have to verify all of these changes themselves and review the maps, adding even more time and workload to the project as a whole.

This has to be repeated **five times** with our current map pool. And if we add any more maps, this needs to be done all over again for those maps.

Having so many maps is a serious blocker to our repository's ability to make large scale gameplay reworks without investing a bunch of extra time doing map design, something that needs to be done to a precise perfect point otherwise it has a huge negative impact on client enjoyment of the end product.

Even if we were to streamline our toolset for map creation, it would only eliminate the first three entries on that list, and not the battery of needed tests to ensure a map is production-ready.

Removing these three maps will reduce that five count down to a mere two, which is far more reasonable and healthy for our contributors to undertake. We want only the best gameplay experience for players, and if we require people trying to rework gameplay to spend multiple weeks, possibly even months, redoing map designs five times over it will simply stall out our gameplay development and result in extreme feature stagnation as everyone has and continues to avoid projects that would involve editing the map.

## Changelog
:cl:
del: Removes all alternative maps except for Box-station and Meta-station to fix feature rollout blockage, reduce the workload needed for refactoring existing features, and minimize the workload needed for designing fun and interactive gameplay interactions.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
o no

**Comment by ArcaneMusic** [comment]
image

**Comment by Ziiro** [comment]
He's not wrong, actually.

**Comment by nemvar** [comment]
don't forget config

**Comment by Iamgoofball** [comment]
@nemvar This is not a config issue. This is not about configs and what maps are enabled/disabled, this is about removing maps to ensure we can properly support the two maps that, as of our last big community-wide map poll, are the two most-favorite maps of the server.

**Comment by 81Denton** [comment]
Yes, having a lot of maps slows down the implementation of features.
No, this is currently not a crippling or unbearable issue. It's also not acceptable to remove the majority of all maps without consulting the player base first.
I will be closing this PR at the usual 24 hour mark.

**Comment by Iamgoofball** [comment]
@81Denton I made this pull request because oranges has stated multiple times in the past this is an issue.

**Comment by nemvar** [comment]
What I meant is removing the other maps from the config options but ok.

**Comment by Iamgoofball** [comment]
@nemvar Ah, my bad. I'll fix that.

**Comment by PKPenguin321** [comment]
@iamgoofball I can throw another server poll up but I don't think this is a crippling issue, and map variety is a bigger net positive than prompt feature rollout

Server-side map toggles would be more appropriate so maps can be enabled once they're updated

**Comment by PKPenguin321** [comment]
Actually on second thought I think I will not do a map poll until https://github.com/tgstation/tgstation/pull/46968 goes through/is closed

**Comment by Arianya** [comment]
I don't think I've seen a more picture perfect execution of a return then coming back with a big, unnecessary change, shouting at someone for mentioning configs, getting shut down by a maintainer, and sticking the landing by it not even compiling.

**Comment by Iamgoofball** [comment]
@PKPenguin321 Thanks, I attempted to get another poll ran but was ignored by the people who are able to open them. I do sincerely believe that ensuring a good gameplay experience is better than map variety, because honestly, Cobbychem's poor reception I feel is entirely based on the fact medbay is still using a design setup on all five maps built around a chemistry-focused healing experience. I used medbay as the example in the OP for this pull request for that specific reason.

**Comment by Iamgoofball** [comment]
@Arianya Please do not post off-topic comments on my pull request. I've reported this comment to the maintainers for harassment.

@ArcaneMusic Please do not post off-topic comments on my pull request.

**Comment by PKPenguin321** [comment]
If you feel that feature rollout being prompt > map variety, that's a valid opinion, sure. However, if that's your issue, then surely a server-side toggle is still preferable. Maps can be kept disabled until they are updated, without the permanent loss of map variety via gutting the maps from code entirely.

**Comment by Iamgoofball** [comment]
@PKPenguin321 That's a very good point. If we were able to have some way to declare maps as "deprecated" so that they would automatically shut off until manually re-enabled by maintainers, it would alleviate this issue and allow us to add a prompt to roundstart indicating the map is deprecated, as to shift the blame from the new feature to the un-updated map instead.

I'll close this PR until you run that poll.

**Comment by Fox-McCloud** [comment]
Yeah, I'd agree with this. Extensive feature rework is a pain in the butt when it comes to multiple maps. Either the maps start languish, or you end up having to double or triple (or worse) the project time for something just to remap a handful of maps that aren't used much.

**Comment by Qustinnus** [comment]
epic PR, I agree 100%

**Comment by Krysonism** [comment]
Welcome back goof! 

Trade me delta for box and i am on board.

**Comment by TheSilverNuke** [comment]
I would actually die if Delta or Pubby were removed from the game, thanks for preventing the merge @81Denton

**Comment by Iamgoofball** [comment]
@Krysonism @TheSilverNuke I'm interested to see how the map vote poll works out, I suspect we might see Delta dethrone Metastation in the 2nd favorite map ranking.

**Comment by Iamgoofball** [comment]
if anyone needs to contact me regarding this please do it by steam and not by discord

**Comment by Learner10** [comment]
I don't know why you'd keep the least interesting and least played AND least voted map in... I too am glad for @81Denton keeping this from going through. My favorite map is by a landslide Delta, and Pubby, though a bit different in layout and design, is the most aesthetically pleasing map of all.

That being said, I do agree that it would be rather bothersome having to remap all 5 of our maps if you'd like to make a certain change the norm...

But who says that this needs to be the case? There was a time where before we forced Pubby to match our other stations by giving it a SME, it for a while stood to be the only map to still run the Singularity. This made the map different, and gave it strength as a map choice. The entire point of having multiple map options is to allow for subtle differences in game play where it seems fit, and if not even that, it's just to have a different setting to work in. If you want surgery to be in the front of medbay, then doesn't it end up being counter-productive if all we did was make every station's department look, feel, and play the same? At that point, we may as well just have Meta only.

**Review by Tlaltecuhtli — COMMENTED** [review]
good

**Pull request closed without merging**
