### PR TITLE
Scan an android to get 200 point discount on the final augmentation node [NO GBP]

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Provides an alternative way to get the 200 points for the final augmentation node.

Also reduced the tier of the prior tech node, it was put to tier 4 by mistake

## Why It's Good For The Game

More options to get the desired node.

## Changelog

:cl:
fix: Techweb: Moved upgraded cyber organs to tier 3 from tier 4
qol: Techweb: Added fully augmented android scan discount experiment for Advanced Cybernetic Organs techweb node
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
I might be mistaken, but I don't think full augmentation will actually change your species to android.

**Comment by MTandi** [comment]
> I might be mistaken, but I don't think full augmentation will actually change your species to android.

I think it does, will confirm later. Also the church-converted androids count too.

**Comment by alien3301** [comment]
> I might be mistaken, but I don't think full augmentation will actually change your species to android.

The only ways to actually become an android are android mutation toxin (exotic botany seeds), the magic mirror from a lavaland ruin and chaplain's sect ritual

**Comment by moocowswag** [comment]
Id like to make sure we let roboticists earn that discount through augments.

**Comment by EnterTheJake** [comment]
> > I might be mistaken, but I don't think full augmentation will actually change your species to android.
> 
> I think it does, it did when I performed the augmentation last time. Will confirm later. Also the church-converted androids count too.

Full androids lack a few organs, for example they gain the no breathe trait, while robo augs do not.

**Comment by MTandi** [comment]
The experiment allows now for both androids and fully augmented humans.

**Pull request merged**
