### PR TITLE
Adds the artistic toolbox and His Grace

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Artistic toolboxes now spawn in maintenance and possess various supplies for wire art and crayon art.
add: Traitors can now obtain His Grace. Chaplains can buy it for 20 TC, or it can be found in a surplus crate.
/:cl:

Come on, don't act like you weren't expecting this. I added job-specific traitor items, and there's no way I wouldn't at least _try_ to get this added.

This item was entirely inspired by the Goonstation traitor item of the same name and general effect. All credit goes to them.

* Adds His Grace, an item available to traitor chaplains for 20 telecrystals and from surplus crates with a 5% chance.
* His Grace is a toolbox in a bright green color. When not awakened, it is called the "artistic toolbox" and, aside from being larger than normal toolboxes, has no other effects.
* His Grace functions like a normal toolbox until a certain ritual is used to "awaken" it. To do this, fill the box with any assortment of organs and activate it in your hand. This shows a message and plays a sound to everyone currently online.
* Once activated, His Grace will begin to thirst for blood. As it grows hungrier, its wielder gains different benefits, but the danger increases. Using His Grace effectively is a balancing act of keeping it hungry enough to give you powerful resistances while sating it enough to prevent it from turning on you.
* Attacking a dead or unconscious person with His Grace will feed them to His Grace, resetting bloodthirst to zero, killing the victim if they weren't dead already, and storing their corpse inside of His Grace.
* Bloodthirst starts at 0 and increments every second. For every victim His Grace has consumed, it will increase by an extra second every tick.
* At 120 bloodthirst, His Grace will turn on and consume its wielder. If it has been dropped, it will instead attack and attempt to consume anyone nearby, and instantly devour anyone who picks it up.
* If His Grace reaches 150 bloodthirst, it will fall back asleep and regurgitate the corpses of everyone that it has consumed.
* His Grace grants different benefits depending on bloodthirst count.
  * __0-30 bloodthirst:__ No change
  * __30-60 bloodthirst:__ Force changes to 20
  * __60-90 bloodthirst:__ Force changes to 25, wielder heals 1/1/0.5/5/0.5 damage per tick
  * __90-110 bloodthirst:__ Force changes to 30, wielder heals 2/2/1/10/1 per tick, and stuns are reduced by 1 per tick
  * __110-120 bloodthirst:__ Force changes to 40, wielder heals 20/20/10/all/5 damage per tick and is immune to stuns
* His Grace gives fluff messages at certain bloodthirst levels, and can be examined to show how many people have died to it and give a cryptic indicator of current bloodthirst.
* If someone somehow revives from inside of His Grace, they can climb out by moving.

Also adds `is_string_in_list` and `remove_strings_from_list` procs for convenience and to make warning messages easier. I'm not sure how to make warning messages better, so if you have cleaner code I can use for them please tell me right away.

Sprites (unawakened and awakened)

his_memes

:+1:s go here please
V

### CODE REVIEW

**Comment by Steelpoint** [comment]
Chaplain last sighted dragging a locker full of corpses around the central primary hallway, all personal are advised to avoid contact until further notice.

So this is based off of a Goonstation item if I recall correctly. I think I would support this addition.

**Comment by Fox-McCloud** [comment]
If I may be so bold as to suggest: https://github.com/ParadiseSS13/Paradise/pull/4395 https://github.com/ParadiseSS13/Paradise/pull/4667

IMO, it's a bit cleaner implementation

**Comment by Xhuis** [comment]
@Steelpoint Yeah, it's an old goon item that got removed because of the way they implemented it. People who examined it were given antag status, so people would gun down the wielder, examine it on purpose, and go on a rampage.

And yes, you can technically wield this in a pacifist manner if you have a ton of monkey corpses or something.

**Comment by Militaires** [comment]
hey atleast credit goon they do hard work on this cool shit

**Comment by Xhuis** [comment]
Done

**Comment by Militaires** [comment]
cool, can I see sprites

**Comment by Xhuis** [comment]
Yeah, let me jump in-game

**Comment by bgobandit** [comment]
job-specific traitor items are bad

**Comment by Xhuis** [comment]
Sprites added to OP.

**Comment by FantasticFwoosh** [comment]
Eats bodies then removes them from the game. Gee that sounds like that's  going to make people VERY salty about being removed. About as bwoinkable on lowpop as incinerating the bodies when you're done.

If you're going that route, why not have the toolbox gib them then borrow the demon antag code to 'eat their soul' so it just becomes a soul repository (which you could use later to do chaplain things with, spare soul stones etc.)

**Comment by Xhuis** [comment]
I thought laughter demons had the same code, where they stored the body in the demon mob. I went this route because if (read: when) His Grace turns on his wielder or is left alone for too long, they'll spit the bodies out - and in the majority of cases I would imagine that the chaplain is either dead, eaten, or long gone from the box.

I don't want to gib people and force them out of their human bodies. If the chaplain wants to use soul shards then he can leave His Grace to his own devices for a while.

**Comment by TehZombehz** [comment]
Having no knowledge of the item from Goonstation, I looked at this hoping it was a little snake wearing a crown and cloak.



Part of my brain was actually hoping this was just a tiny snek. I may need coffee.

**Comment by FantasticFwoosh** [comment]
@Xhuis your description that it'll spit the bodies out is contradictory to your description of it eating the bodies then going back to sleep.

To my understanding the slaughter demon stores the bodies within the 'blood' and q deletes bodies who have been under there too long associated to the demon who pulled them in then refreshes demon's health. (irreclaimable bodies littering where they can't be seen/interacted with else)

**Comment by Xhuis** [comment]
Oh! Sorry about misleading you, then. Bodies are never deleted and will always be spit out when His Grace falls to sleep.

**Comment by Armhulen** [comment]
it already obviously shakes when awakened, do you mind me adding eyes and teeth to it?

**Comment by Xhuis** [comment]
Nah, I feel like part of the charm comes from the fact that it's just a toolbox. Nothing special about it. It's green, but that's it. Also, it's covered in blood and shaking. But just a toolbox.

**Comment by Armhulen** [comment]
fair enough, i like that vision too I suppose. I was only thinking of the eyes when it was extremely hungry, but holders don't need even more warnings I guess.

**Comment by InsaneHyena** [comment]
Never expected to say this, but I'm glad Xhuis coded something.

**Comment by Armhulen** [comment]
are you joking, he's only been coding good things since like the revenant > umbra pull

**Comment by optimumtact** [comment]
GOON GO HOME, CLOSING PR IN 24 HOURS

**Comment by juanototo2** [comment]
fuck you oranges Chap needs a further dose of N2SNOWFLAKE14

**Comment by Armhulen** [comment]
fuck you oranges Chap needs a further dose of N2SNOWFLAKE14

**Comment by darkpaladin109** [comment]
I'm only okay with this if you can retrieve the bodies out of the toolbox somehow, murderboners permanently removing people from the round isn't fun.

**Comment by Armhulen** [comment]
you can

>If His Grace reaches 150 bloodthirst, it will fall back asleep and regurgitate the corpses of everyone that it has consumed.
so literally just wait until his grace gets hungry enough to go asleep and you get all the bodies back.

**Comment by Xhuis** [comment]
@optimumtact REEEEEEEEEEEEEEEEEEEEEEE

**Comment by PKPenguin321** [comment]
how did you make it shake like that

**Comment by Xhuis** [comment]
I made it an animated icon that shifts by 1 pixel in each direction. It's basically a slideshow that moves one pixel left, then up, then right, then down.

**Comment by PKPenguin321** [comment]
oh darn it i thought somebody actually made a working shake proc

**Comment by Xhuis** [comment]
Unfortunately, no :(

**Comment by gt33** [comment]
Pull this already!!

**Comment by Xhuis** [comment]
24 hour minimum is a killer

**Comment by Fox-McCloud** [comment]
@Xhuis 

The examine-slave thing was stripped out; it only makes the first person who attempts to open it the servant; no one else aside from the original opener is going to be a servant. Likewise, it doesn't delete bodies; it stores them in the toolbox itself and ejects them when the toolbox is destroyed.

**Comment by KorPhaeron** [comment]
@Iamgoofball 

Stop encouraging people to raid our pull requests "voting" you meme

**Comment by Xhuis** [comment]
New commit.
* Adds an actual artistic toolbox that spawns in maintenance loot drops. It has a pack of crayons, a crowbar, and a coil of every wire color! It can hold more than normal toolboxes but weighs more.
* His Grace is now a subtype of the artistic toolbox.

This is to prevent people screeching "CHAPLAIN TRAITOR REEEEEEEEEEEE" when they seem him carrying around a green toolbox, but also to give people a semi-reliable way to do wire art without having to rely on luck to get the colors they want.

Otherwise, this is merge-ready.

**Comment by gt33** [comment]
Gonna set Chaplain on High again if this gets (test)merged!

**Comment by gt33** [comment]
Wait, idea. If the Chaplain somehow gets the right access, they should be able to shove His Grace into a Beepsky/ED-209 to create a indiscriminate murderboning, shuttle-calling, robot of death of destruction.

**Comment by KorPhaeron** [comment]
>Gonna set Chaplain on High again if this gets (test)merged!

@Incoming5643 was right

**Comment by gt33** [comment]
@KorPhaeron  ?

**Comment by KorPhaeron** [comment]
He was worried people would roll jobs purely to try out their antag items

**Comment by Xhuis** [comment]
Incoming was saying that people would roll certain jobs- what he said

**Comment by GunHog** [comment]
Curiosity about the new items is to be expected, Kor. Ban the players that kill themselves after taking the job, but failing their antag roll. It will settle back down once people are familiar with the new thing.

**Comment by Iamgoofball** [comment]
@KorPhaeron 
1. we don't acknowledge reddit meme votes because of how easy it is to spoof
2. I didn't actually go to goon to tell them about this, IDK how hippie chron dudes found it, but I did link it to a guy I know who happens to play goon because I figured he'd think it's cool

**Comment by Iamgoofball** [comment]
also @Xhuis @Incoming5643 @KorPhaeron whats the problem with people rolling underused jobs to try out features

**Comment by Xhuis** [comment]
I never said there is one. In fact, that's one of the reasons I'm making so many items! If people want to select a job just to roll the antag, and then they don't, they can still play as that job - and if they just off themselves, then it's a player problem and can be dealt with in the same way.

**Comment by Steelpoint** [comment]
It makes logical sense that if a certain job gets a new, unique, item with some fan fare before hand that you should expect that job to pick up in popularity for a while.

**Comment by Incoming5643** [comment]
@Iamgoofball Chaplain is not an underused job anymore. Check the stats page. Ever since the specialized null rods came in chaplain has gotten a healthy supply of power game picks for a one slot roll.

**Comment by Xhuis** [comment]
Conflicts are fixed.

**Comment by Core0verload** [comment]
Goonstation shit, instant 👎

**Comment by gt33** [comment]
@Core0verload thanks for the suggestion, left feedback on your comment

**Comment by Xhuis** [comment]
Core has never been known for a tolerant and sane-minded person

**Comment by Armhulen** [comment]
@ChangelingRain this does not have merge conflicts anymore

**Comment by Chronitonity** [comment]
@Iamgoofball i play here every once and a while, no one there including me is from hippie as far as i know

**Comment by Armhulen** [comment]
WOO

**Pull request merged**
