### PR TITLE
Barticles for bonfires 2021

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Gives bonfires barticles

## Why It's Good For The Game

This looks fantastic! Better than any icon_state can do and we should look into this for other fire sources

https://user-images.githubusercontent.com/40974010/123691308-4f801a00-d80a-11eb-8c54-6f20f54ce65b.mp4

## Changelog
:cl:
expansion: added barticles to bonfires
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
BARTICLES LETS GO

**Comment by tralezab** [comment]
oh, and i should clean up bonfire bode one second

**Comment by Time-Green** [comment]
Wait particles actually got rolled out, or is this a work-around?

**Comment by tralezab** [comment]
barticles are bere

**Comment by Time-Green** [comment]
WHAT ARE BARTICLES

**Comment by Iamgoofball** [comment]
:-1:
Particles are still completely busted on this version of BYOND. Wait till next version when they're fixed.

**Comment by Fikou** [comment]
> 👎
> Particles are still completely busted on this version of BYOND. Wait till next version when they're fixed.

this is a stationary object and it will look fine

**Comment by MrDoomBringer** [comment]
barticles

**Comment by MrDoomBringer** [comment]
also show ingame gif you stinky dumb

**Comment by ArcaneMusic** [comment]
Reading this gives me a stroke

**Comment by tralezab** [comment]
also i should note, right now an object can hold one particle datum so in the future we should do something like filters

**Comment by tralezab** [comment]
added demonstation

**Review by coiax — COMMENTED** [review]
Not really a fan of the rename and the edit, I don't want to play "compare side by side".

What have you changed apart from the filename?

**Comment by Timberpoes** [comment]
I swear to Nya'sie Arm, stop making PRs with shit-tastic titles or I will start instantly closing them when I see them pop up.

Everyone else is held that standard and so you shall be too.

**Comment by MrDoomBringer** [comment]
>Not really a fan of the rename and the edit, I don't want to play "compare side by side".
What have you changed apart from the filename?

what does this mean
also thanks for the video you smell good

**Comment by tralezab** [comment]
@coiax should have included that in the pr, but I also brought bonfires up to contribution standards and gave them their own file.

**Comment by Krysonism** [comment]
> 
> 
> I swear to Nya'sie Arm, stop making PRs with shit-tastic titles or I will start instantly closing them when I see them pop up.
> 
> Everyone else is held that standard and so you shall be too.

no fun allowed

**Comment by Mothblocks** [comment]
@coiax improvise. adapt

image

**Pull request merged**
