### PR TITLE
stripes on the tacticool clothes

### PR DESCRIPTION
**Pull request by sylvia-from-fulp-station**
## About The Pull Request

Makes the tacticool clothes striped.
dreamseeker_U6eHK7jiTP

## Why It's Good For The Game

These probably need to be updated but uh ill just edit them
They should look more like the clothes they are trying to imitate than a slightly different turtleneck.

## Changelog

:cl:
image: The tacticool clothing is now striped.
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
the stripes make it too powerful

**Comment by MTandi** [comment]
I prefer them stripe-less. They look like some sweaters now. While it's just a black turtleneck that you put under your armor layer. 

image

**Comment by MTandi** [comment]
Just a reference of how it look like IRL:

image

**Comment by sylvia-from-fulp-station** [comment]
dude this is the toy version of tactical turtleneck lol

**Comment by sylvia-from-fulp-station** [comment]
image
"tactifool" / "tacticool" in the code refer to the station version of the syndicate jumpsuit which bizarrely has a sprite closer to the "turtleneck skirt"

**Comment by sylvia-from-fulp-station** [comment]
Aseprite_F0Ni8Sjh6z
Aseprite_kzBfEiuGw0
For reference i just used the actual syndicate jumpsuits while keeping the bottom coloration instead of making a new piece of clothing; again its not a sprite overhaul its just meant to make it look more like the real thing.

**Comment by Ghommie** [comment]
Wait what? Why is the tactical one striped while the tacticool isn't? Shouldn't it be the other way around?!

**Review by ShizCalev — APPROVED** [review]

**Comment by Wallemations** [comment]
The real ones should be stripeless, to make them more tactical and also to match a majority of the refs. Sure the hitman one has stripes but they're extremely small compared to the turtleneck sweater look you've went for.

**Comment by sylvia-from-fulp-station** [comment]
> they ARE stripleless, this pr only changes fake, check "files changed" or icondiff bot

No the real ones are striped, thats the whole point of this PR

**Comment by sylvia-from-fulp-station** [comment]
> The real ones should be stripeless, to make them more tactical and also to match a majority of the refs. Sure the hitman one has stripes but they're extremely small compared to the turtleneck sweater look you've went for.

What does this even mean man I just made it look the same as the syndicate jumpsuit instead of a default turtleneck sweater. if you don't want this merged just close it

**Comment by Jacquerel** [comment]
If the point of this PR is to give stripes to the real ones and the spritetainer opinion is that those ones specifically should not have sprites then I guess it might as well be closed.

**Pull request closed without merging**
