### PR TITLE
Fixes lore

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
> 2556 > thinking you can just change it to 2525

**Comment by ShadowDeath6** [comment]
I thought it was always 25(insert year + 40), how deep is this lore

**Comment by PKPenguin321** [comment]
This somewhat supports my headcanon but also probably isn't official lore

**Comment by Iamgoofball** [comment]
if man is still alive

**Comment by TechnoAlchemisto** [comment]
I was on a mining colony, on Mars?

**Comment by Iamgoofball** [comment]
god shakes his mighty head

**Comment by PKPenguin321** [comment]
>if man is still alive

If human can survive

**Pull request closed without merging**
