### PR TITLE
Gives Chaos/Meat Donuts Their Missing Sprites

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

title, plus gives meat donut an actual name and desc

## Why It's Good For The Game

wiki said they did they didnt

## Changelog
:cl: optimum wesoda
imageadd: Sprites for Meat and Chaos Donuts
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
no its not for pride month, yes they arent the prettiest sprites im just copying whats on wiki, same for meat donut desc. third times the charm

**Comment by fludd12** [comment]
🌈🍩🌈
Pride Donut
🌈🍩🌈

**Comment by Farquaar** [comment]
> 
> 
> no its not for pride month, yes they arent the prettiest sprites im just copying whats on wiki, same for meat donut desc. third times the charm

Legit, I just made those wiki images before I learned how to code sprites into BYOND. The meat donut sprite is okay, but the chaos donut sprite is a half-finished piece of refuse.
They're all fake. It's a great big fake is what it is.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
make it look better.

**Comment by wesoda25** [comment]
eughhh.

**Comment by wesoda25** [comment]
I dont even fucking know what to make them look like. What conveys chaos??? What makes a chaos donut? Should I do visual stuff??? I dont KNOW!! and idk dude hte meat donut description is that its ugly looking so i thought that was fitting. i will give chaos animation but leave meat i dont even know what id do for that

**Comment by Farquaar** [comment]
If you're not prone to epileptic seizures, the original idea behind the chaos donut placeholder was that it would pulse like the image below.
https://i.imgur.com/PbRtk.gif?1
It was one of my earliest sprites and looks pretty bad though. I'd recommend tossing out the placeholder chaos donut sprite and starting from scratch.

**Comment by wesoda25** [comment]
Ok so for chaos I think I’ll do some sort of pulse mechanism utilizing red and blue (since cold + hot sauce make chaos). Again not too sure as to what I should do for meat tho.

**Comment by ShizCalev** [comment]
meat donut is fine (it's been a while since i looked at donuts, and they're all pretty shit, so eh.)

give chaos the animation though

**Comment by optimumtact** [comment]
I'd rather have some half decent sprite than no sprite

**Pull request merged**
