### PR TITLE
Gang Update [Ready]

### PR DESCRIPTION
**Pull request by Ikarrus**
screenshot 2015-06-08 23 52 46
### New Objective: Hostile Takeover
- Gangs must preform a hostile takeover to win, replacing the old territory objective, which many felt was anticlimactic 
- Gangs must purchase and defend a dominating **dominator** machine for a varying length of time
- Dominators cost 50 influence
- Once activated, the entire station will be alerted to it's location.
- The more territory your gang controls, the less time you will need to defend it. This ranges widely from 3 to 30 minutes
- Emergency shuttles cannot depart from SS13 while a hostile takeover is in progress
- Dominators have 200 health. If destroyed, Gangs can try again with a new dominator, but must start over with a new timer.
### Gang Outfits
- Outfits are not purchasable from the gangtool for a cheap 1 influence each
- The first time they are purchased, the buyer picks a style that their gang will use for the remainder of the round
- I've only included 3 right now (Gang colors, leather, suits), but more could easily be added
- They also get to pick if they want to spawn a hat with the outfit
### Gangtool Changes
- Thompson SMGs aka "tommy guns" are purchasable as late-game weapons for 50 influence each. Additional ammo drums cannot be purchased at this time.
- Bulletproof vests are purchasable for 10 influence each
- Gang messages are now free
- Prices of pistols and pens reduced to 20 and 30, respectively
### Misc
- Gangs start with 25 influence instead of 30
- Gangs will no longer be notified how much territory the enemy controls
- Gang spraycans have been made a lot less obvious. They look nearly identical to regular ones, now.
- Priority announcements support titles now
- The usual round of bugfixes

### CODE REVIEW

**Comment by pudl** [comment]
first

**Comment by Dorsisdwarf** [comment]
The announcement should be a centcomm message, to stop AIs from being "funny" whenever the heads try and declare Red

**Comment by Lumipharon** [comment]
Gangsters need more swag.

Brass knuckles and drive by shootings with Uzi's when? (oh that's right, pap removed uzi's, whelp)

**Comment by KorPhaeron** [comment]
Do they get any special gear to defend it?

I can't imagine a gang defending a static location from flashbangs very well

@Lumipharon

Why was the uzi removed?

**Comment by Jordie0608** [comment]
Changelog

**Comment by Lumipharon** [comment]
Pap removed it because it was functionally the same as a c-20r (well, can't hold a suppressor). Of course giving people c-20r's for events or whatever immediately makes them syndicate in players eyes, since it's a syndicate gun.

**Comment by KorPhaeron** [comment]
I don't see what the problem in having functionally identical but differently fluffed things is in a sandbox roleplaying game. Odd.

If you can find the sprites I'll re-add it.

**Comment by Steelpoint** [comment]
That's Pap for you.

But I do like the idea of some gang members having high tech/powerful gear at the end game, and they will need it to defend the dominator.

**Comment by Dorsisdwarf** [comment]
Maybe let them order meth injectors to reduce stuns?

**Comment by Alek2ander** [comment]
Maybe Delta and not red? Because, you know, Hostile Runtimes, nobody reads this stuff, and it's funny when people try to lynch the AI for no reason

**Comment by Lumipharon** [comment]
Some Ephedrine with a bit of crank + meth would do wonders.

**Comment by Ikarrus** [comment]
I don't believe tommy guns are used anywhere else. I'll probably nerf them a tiny bit (I believe they're insanely OP right now) and let them get purchased as a higher-end weapon.

**Comment by Ikarrus** [comment]
I'm thinking maybe tommy guns if I can get them balanced.

**Comment by Ikarrus** [comment]
Update is now ready.

**Comment by Czarcastic** [comment]
Are the uniforms just cosmetic? Why would you buy them if it instantly identifies you as a gangster with no bonuses involved?

**Comment by Ikarrus** [comment]
Popular request.

**Comment by Ikarrus** [comment]
Some Players just want roleplay tools. Its not always about winning.

**Comment by Iamgoofball** [comment]
@Lumipharon maybe since you're gangsters you should roleplay and pay off the chemists to deal drugs for you instead

**Comment by kevinz000** [comment]
>50 round stunlocking tommy gun
RD wins.

**Comment by Ikarrus** [comment]
I'm sorry I don't speak meme

**Comment by kevinz000** [comment]
On a unrelated note, nothing can break telearmor

**Pull request merged**
