### PR TITLE
Adds a new screaming sound for males

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd
 add: New screaming sound for males
/:cl:

https://vocaroo.com/i/s0SUXFUI6fXj

### CODE REVIEW

**Comment by nemvar** [comment]
OOF

**Comment by Qustinnus** [comment]
credits to actioninja

**Comment by actioninja** [comment]
image

**Comment by AarontheIdiot** [comment]
AAAAAAAahhhhgh

**Comment by MrFluffster** [comment]
Did you scream it yourself?

**Comment by actioninja** [comment]
yeah this is me screaming

**Comment by MMMiracles** [comment]
your scream forever immortalized in the spaceman

**Comment by Swagile** [comment]
long ago, in a distant station, actionninja, the screaming master of space, unleashed a unspeakable horror

but a foolish maintainer, welding a closed button, stepped forth to oppose him

before the closed button was pressed, actionninja tore open a portal to testmerges, and flung the maintainer into the feature, where his scream was law

now the maintainer seeks to return to github, and undo the testmerge that is actionninja

**Comment by PKPenguin321** [comment]
aaaAAaauaaAAAAgh

**Pull request merged**
