### PR TITLE
[april fools] Improves bedhead hair

### PR DESCRIPTION
**Pull request by BanementI**
## About The Pull Request
This PR improves immersion and roleplay experience within SS13 by making all characters that use bedhead, the most overused hairstyle in-game, go completely bald instead.
## Why It's Good For The Game
You get what you deserve.
## Changelog
:cl:
balance: Characters that use bedhair are now bald.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
was hoping it added an icon of a bed

**Comment by BanementI** [comment]
> was hoping it added an icon of a bed
i thought bald was funny but i can do bed instead

**Review by optimumtact — APPROVED** [review]

**Comment by the-orange-cow** [comment]
Comb-cels seething

**Comment by san7890** [comment]
i added that label from the batch-edit PRs screen btw, my bad

**Comment by Jackal-boop** [comment]
Do we have stats for the most used hair styles

**Pull request closed without merging**
