### PR TITLE
Nuclear bombs now only explode the station as long as they're in a non-space area on the station zlevel

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Nuclear bombs will no longer explode the station if in space. Please be aware of this.
/:cl:

random failures due to setting up in the wrong spot are fun, right?

### CODE REVIEW

**Comment by coiax** [comment]
This means you'll just arm it in space though.

**Comment by KorPhaeron** [comment]
>This means you'll just arm it in space though.

**Comment by ChangelingRain** [comment]
They do that already, and it's real confusing when the bomb fails on station.
Maybe just make it fail if it's on a space turf, hmm?

**Comment by Zilenan91** [comment]
Ops will just take some metal, put some lattices in space, floor tile it, anchor that shit and nobody will ever find it

Then again by that point they've already won but it's still a problem

**Comment by RemieRichards** [comment]
@Zilenan91 we just check for the space AREA instead then.

**Comment by JJRcop** [comment]
Then they steal blueprints

**Comment by coiax** [comment]
You can distinguish between station areas, and those setup via blueprints.

**Comment by ChangelingRain** [comment]
If you go to the length of stealing blueprints to make a tiny bomb room for the nuke you've earned it

**Comment by xxalpha** [comment]
Or arm it in the solars.

**Comment by Zilenan91** [comment]
If they steal blueprints they have earned it yeah

**Comment by kilkun** [comment]
not really

all they have to do is shoot the CE who was probably trying to kill them anyways. and assuming the ce left it in his locker they can just emag/blow it open and gg no re, which WILL become a new standard strategy.

**Comment by JJRcop** [comment]
Actually you have to have an airtight room in order for the blueprints to work. It doesn't have to have air in it, it just has to have the ability to hold air.

**Pull request merged**
