### PR TITLE
Pipe Pressure Panic

### PR DESCRIPTION
**Pull request by RemieRichards**
- You can now unwrench atmos machinery who's internal pressure is greater than it's environment...
- However this will violently throw you away from the machine, with painful results!
- During the do_after() (the delay of the action) you are warned of the machines danger, allowing you to cancel by walking away

The speed and range of the throw relate to the pressures of the machine, the higher the pressure, the further you go quicker!

The unwrenched machine will also leak it's juicy gas contents all over the floor when unwrenched in this fashion (let's assume when a pipe is unwrenched below the dangerous pressures the Atmos tech caps both ends of each pipe, k?) it does so in the same fashion (code/mechanically) as a portable atmos canister (the big ones, not the hand held ones) except it takes an amount from each of the machine's air mixtures equally (binaries have 2 mixtures, trinaries 3, etc)

### CODE REVIEW

**Comment by kyrahabattoir** [comment]
Is there a specific direction for the pressure? could it be applied to opening an air injector too for some compressed gas catapult goodness?

**Comment by RemieRichards** [comment]
@kyrahabattoir the person who unwrenches the pipe is thrown backwards (away from the pipe/machine), the gases and other remaining pressure junk leftover after the throw leaks as any other atmos leak would.

The proc is currently at the ```/obj/machinery/atmospherics level```, and is *fairly* generic, so it could be expanded to other machines, yes.

**Comment by duncathan** [comment]
+1
Will make dealing with overpressure not only more fun, but more deadly. I love it.

**Comment by PKPenguin321** [comment]
:+1: :+1: :+1: more things for throwing people

**Comment by optimumtact** [comment]
Can you not just dump the pressure into the tile and let space wind move them?

**Comment by RemieRichards** [comment]
@optimumtact that's a HILARIOUSLY underwhelming effect.
Throwing people is funny.

**Comment by optimumtact** [comment]
So buff spacewind?

**Comment by PKPenguin321** [comment]
>buff spacewind

get out

**Comment by francinum** [comment]
:+1:

**Comment by optimumtact** [comment]
Typical hugboxers

**Comment by fj45** [comment]
Sounds hilariously !FUN!, only possible issue is anyone being able to grab a wrench and mess with the distro line, but that might not be an issue.

Big use for this that I can think of would be very rapid breach filling.

**Comment by freerealestate** [comment]
>Typical hugboxers

nice meme

**Comment by WJohn** [comment]
Holy shit finally.

**Comment by Tokiko1** [comment]
Do higher pressures cause worse injuries?

**Comment by RemieRichards** [comment]
@Tokiko1 not at the moment, but since it's 20 damage per wall you hit while thrown (this has ALWAYS been the case) I didn't touch the numbers yet.

At most I'd add a Weaken() call to hitting the wall (like when an Alien is stunned because they leaped face first into a wall) and ... MAYBE some brainloss.

**Comment by PKPenguin321** [comment]
Just for the record, buffing getting slammed into the wall also buffs getting thrown into a wall, making chain-table-chain-throw kills easier.

**Pull request merged**
