### PR TITLE
Revert "Unit Test connected station areas"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#74367

This is gimping mappers ability to do cool things intentionally.

Also im thinking we might need to pause adding new unit tests until we have better ways to whitelist or exempt shit because this keeps fucking happening.

### CODE REVIEW

**Comment by Mothblocks** [comment]
cc @san7890

**Comment by san7890** [comment]
Is there a way you can exclude reverting the map changes? Those were legitimate fixes

**Comment by Cheshify** [comment]
While I disliked the unit test preventing me from having areas without atmos objects, it did genuinely help me find and fix errors

**Comment by Jolly-66** [comment]
Instead of a unit test why not make it a mapping verb?

**Comment by san7890** [comment]
> Instead of a unit test why not make it a mapping verb?

mapping verbs are nice but no one will ever act on them ever because there's no reason to care. i did the whole "obstructed atmospherics" thing so i could eventually make a unit test and look where we are now

**Pull request closed without merging**
