### PR TITLE
icebox maints revamp

### PR DESCRIPTION
**Pull request by manofpepsi**
## About The Pull Request

Revamps the icebox maints to make them less of wall maze with some maint loot sprinkled around and have more abandoned/unfinished rooms instead.

Pictures of the biggest map changes.
Before --------> After
pic 1
pic 2
pic 3
pic 4
pic 5
pic 6
pic 7
pic 8
pic 9

## Changelog
:cl: Pepsiman0
add: IceBox maints revamp
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Box has been in need of this.

It looks like one of your new maint ruins is a bar. Doesn't box already have a maint bar?

**Comment by manofpepsi** [comment]
> Box has been in need of this.
> 
> It looks like one of your new maint ruins is a bar. Doesn't box already have a maint bar?

yeah it would be the third bar if you count the bootleg ones as well. I am redoing it right now since I finally got some actual feedback in the form of an idea and now I know what to replace it with.

**Comment by manofpepsi** [comment]
image

**Comment by Wilhelm770** [comment]
This looks good but a hidden dorms/shower area in maints is a risky move.

**Comment by manofpepsi** [comment]
manky

**Pull request closed without merging**
