### PR TITLE
Fixes clockcult round end stats showing up when they shouldn't

### LINKED ISSUE #21654: Ratvar end of round stats show up on non clockcult round
Ratvar's servants had 0 Tinkerer's Caches.
Construction Value(CV) was: 0
Script scripture was: LOCKED
Application scripture was: LOCKED
Revenant scripture was: LOCKED
Judgement scripture was: LOCKED

traitorling round, no cultists.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #21654

### CODE REVIEW

**Comment by SkowronX** [comment]
Is this mode here to stay? Last I saw peeps were complaining about it being too complex.

**Comment by ChangelingRain** [comment]
It's definitely going to stay, yes.

**Comment by Crushtoe** [comment]
Game modes are rarely removed, and when they are it's usually because they're too buggy (See: Meteor, Monkey). But even then, they're usually kept in the code (See: Hand of God, Meteor, Monkey, Shadowling) and just removed from rotation.

**Comment by XDTM** [comment]
Shadowling has definitely been nuked from the code, and i think HoG was too.

**Comment by lzimann** [comment]
both were nuked, but it is still really rare to a gamemode being removed from the code.

**Comment by Crushtoe** [comment]
Some Hand of God sprites are still in the files I believe.

**Comment by ExcessiveUseOfCobblestone** [comment]
only as vanity items.

**Pull request merged**
