### PR TITLE
Removes standalone porta-turret covers from the derelict, which was causing runtimes.

### LINKED ISSUE #34929: /obj/machinery/porta_turret_cover - missing parent runtimes
```
runtime error: 
[05:29:41]Cannot execute null.attacked by().
[05:29:41]proc name: attacked by (/obj/machinery/porta_turret_cover/attacked_by)
[05:29:41]  source file: portable_turret_cover.dm,75
[05:29:41]  usr: Whom (/mob/living/carbon/human)
[05:29:41]  src: the turret (/obj/machinery/porta_turret_cover)
[05:29:41]  usr.loc: the floor (90,147,7) (/turf/open/floor/plasteel/airless)
[05:29:41]  src.loc: the floor (90,146,7) (/turf/open/floor/plasteel/airless)
[05:29:41]  call stack:
[05:29:41]the turret (/obj/machinery/porta_turret_cover): attacked by(the screwdriver (/obj/item/screwdriver), Whom (/mob/living/carbon/human))
[05:29:41]the screwdriver (/obj/item/screwdriver): attack obj(the turret (/obj/machinery/porta_turret_cover), Whom (/mob/living/carbon/human))
[05:29:41]the turret (/obj/machinery/porta_turret_cover): attackby(the screwdriver (/obj/item/screwdriver), Whom (/mob/living/carbon/human), "icon-x=21;icon-y=11;left=1;scr...")
[05:29:41]the turret (/obj/machinery/porta_turret_cover): attackby(the screwdriver (/obj/item/screwdriver), Whom (/mob/living/carbon/human), "icon-x=21;icon-y=11;left=1;scr...")
[05:29:41]the screwdriver (/obj/item/screwdriver): melee attack chain(Whom (/mob/living/carbon/human), the turret (/obj/machinery/porta_turret_cover), "icon-x=21;icon-y=11;left=1;scr...")
[05:29:41]Whom (/mob/living/carbon/human): ClickOn(the turret (/obj/machinery/porta_turret_cover), "icon-x=21;icon-y=11;left=1;scr...")
[05:29:41]the turret (/obj/machinery/porta_turret_cover): Click(the floor (90,146,7) (/turf/open/floor/plasteel/airless), "mapwindow.map", "icon-x=21;icon-y=11;left=1;scr...")
runtime error: 
[05:29:43]Cannot execute null.attacked by().
[05:29:43]proc name: attacked by (/obj/machinery/porta_turret_cover/attacked_by)
[05:29:43]  source file: portable_turret_cover.dm,75
[05:29:43]  usr: Whom (/mob/living/carbon/human)
[05:29:43]  src: the turret (/obj/machinery/porta_turret_cover)
[05:29:43]  usr.loc: the floor (90,147,7) (/turf/open/floor/plasteel/airless)
[05:29:43]  src.loc: the floor (90,146,7) (/turf/open/floor/plasteel/airless)
[05:29:43]  call stack:
[05:29:43]the turret (/obj/machinery/porta_turret_cover): attacked by(the wirecutters (/obj/item/wirecutters), Whom (/mob/living/carbon/human))
[05:29:43]the wirecutters (/obj/item/wirecutters): attack obj(the turret (/obj/machinery/porta_turret_cover), Whom (/mob/living/carbon/human))
[05:29:43]the turret (/obj/machinery/porta_turret_cover): attackby(the wirecutters (/obj/item/wirecutters), Whom (/mob/living/carbon/human), "icon-x=19;icon-y=6;left=1;scre...")
[05:29:43]the turret (/obj/machinery/porta_turret_cover): attackby(the wirecutters (/obj/item/wirecutters), Whom (/mob/living/carbon/human), "icon-x=19;icon-y=6;left=1;scre...")
[05:29:43]the wirecutters (/obj/item/wirecutters): melee attack chain(Whom (/mob/living/carbon/human), the turret (/obj/machinery/porta_turret_cover), "icon-x=19;icon-y=6;left=1;scre...")
[05:29:43]Whom (/mob/living/carbon/human): ClickOn(the turret (/obj/machinery/porta_turret_cover), "icon-x=19;icon-y=6;left=1;scre...")
[05:29:43]the turret (/obj/machinery/porta_turret_cover): Click(the floor (90,146,7) (/turf/open/floor/plasteel/airless), "mapwindow.map", "icon-x=19;icon-y=6;left=1;scre...")
runtime error: 
[05:29:45]Cannot execute null.attacked by().
[05:29:45]proc name: attacked by (/obj/machinery/porta_turret_cover/attacked_by)
[05:29:45]  source file: portable_turret_cover.dm,75
[05:29:45]  usr: Whom (/mob/living/carbon/human)
[05:29:45]  src: the turret (/obj/machinery/porta_turret_cover)
[05:29:45]  usr.loc: the floor (90,147,7) (/turf/open/floor/plasteel/airless)
[05:29:45]  src.loc: the floor (90,146,7) (/turf/open/floor/plasteel/airless)
[05:29:45]  call stack:
[05:29:45]the turret (/obj/machinery/porta_turret_cover): attacked by(the pocket crowbar (/obj/item/crowbar), Whom (/mob/living/carbon/human))
[05:29:45]the pocket crowbar (/obj/item/crowbar): attack obj(the turret (/obj/machinery/porta_turret_cover), Whom (/mob/living/carbon/human))
[05:29:45]the turret (/obj/machinery/porta_turret_cover): attackby(the pocket crowbar (/obj/item/crowbar), Whom (/mob/living/carbon/human), "icon-x=19;icon-y=12;left=1;scr...")
[05:29:45]the turret (/obj/machinery/porta_turret_cover): attackby(the pocket crowbar (/obj/item/crowbar), Whom (/mob/living/carbon/human), "icon-x=19;icon-y=12;left=1;scr...")
[05:29:45]the pocket crowbar (/obj/item/crowbar): melee attack chain(Whom (/mob/living/carbon/human), the turret (/obj/machinery/porta_turret_cover), "icon-x=19;icon-y=12;left=1;scr...")
[05:29:45]Whom (/mob/living/carbon/human): ClickOn(the turret (/obj/machinery/porta_turret_cover), "icon-x=19;icon-y=12;left=1;scr...")
[05:29:45]the turret (/obj/machinery/porta_turret_cover): Click(the floor (90,146,7) (/turf/open/floor/plasteel/airless), "mapwindow.map", "icon-x=19;icon-y=12;left=1;scr...")
runtime error: 
[05:29:47]Cannot read null.on
[05:29:47]proc name: attackby (/obj/machinery/porta_turret_cover/attackby)
[05:29:47]  source file: portable_turret_cover.dm,44
[05:29:47]  usr: Whom (/mob/living/carbon/human)
[05:29:47]  src: the turret (/obj/machinery/porta_turret_cover)
[05:29:47]  usr.loc: the floor (90,147,7) (/turf/open/floor/plasteel/airless)
[05:29:47]  src.loc: the floor (90,146,7) (/turf/open/floor/plasteel/airless)
[05:29:47]  call stack:
[05:29:47]the turret (/obj/machinery/porta_turret_cover): attackby(the wrench (/obj/item/wrench), Whom (/mob/living/carbon/human), "icon-x=11;icon-y=16;left=1;scr...")
[05:29:47]the wrench (/obj/item/wrench): melee attack chain(Whom (/mob/living/carbon/human), the turret (/obj/machinery/porta_turret_cover), "icon-x=11;icon-y=16;left=1;scr...")
[05:29:47]Whom (/mob/living/carbon/human): ClickOn(the turret (/obj/machinery/porta_turret_cover), "icon-x=11;icon-y=16;left=1;scr...")
[05:29:47]the turret (/obj/machinery/porta_turret_cover): Click(the floor (90,146,7) (/turf/open/floor/plasteel/airless), "mapwindow.map", "icon-x=11;icon-y=16;left=1;scr...")
runtime error: 
[05:29:48]Cannot read null.on
[05:29:48]proc name: attackby (/obj/machinery/porta_turret_cover/attackby)
[05:29:48]  source file: portable_turret_cover.dm,44
[05:29:48]  usr: Whom (/mob/living/carbon/human)
[05:29:48]  src: the turret (/obj/machinery/porta_turret_cover)
[05:29:48]  usr.loc: the floor (90,147,7) (/turf/open/floor/plasteel/airless)
[05:29:48]  src.loc: the floor (90,146,7) (/turf/open/floor/plasteel/airless)
[05:29:48]  call stack:
[05:29:48]the turret (/obj/machinery/porta_turret_cover): attackby(the wrench (/obj/item/wrench), Whom (/mob/living/carbon/human), "icon-x=26;icon-y=13;left=1;scr...")
[05:29:48]the wrench (/obj/item/wrench): melee attack chain(Whom (/mob/living/carbon/human), the turret (/obj/machinery/porta_turret_cover), "icon-x=26;icon-y=13;left=1;scr...")
[05:29:48]Whom (/mob/living/carbon/human): ClickOn(the turret (/obj/machinery/porta_turret_cover), "icon-x=26;icon-y=13;left=1;scr...")
[05:29:48]the turret (/obj/machinery/porta_turret_cover): Click(the floor (90,146,7) (/turf/open/floor/plasteel/airless), "mapwindow.map", "icon-x=26;icon-y=13;left=1;scr...")
runtime error: 
[05:29:52]Cannot execute null.attacked by().
[05:29:52]proc name: attacked by (/obj/machinery/porta_turret_cover/attacked_by)
[05:29:52]  source file: portable_turret_cover.dm,75
[05:29:52]  usr: Whom (/mob/living/carbon/human)
[05:29:52]  src: the turret (/obj/machinery/porta_turret_cover)
[05:29:52]  usr.loc: the floor (90,147,7) (/turf/open/floor/plasteel/airless)
[05:29:52]  src.loc: the floor (90,146,7) (/turf/open/floor/plasteel/airless)
[05:29:52]  call stack:
[05:29:52]the turret (/obj/machinery/porta_turret_cover): attacked by(the welding tool (/obj/item/weldingtool), Whom (/mob/living/carbon/human))
[05:29:52]the welding tool (/obj/item/weldingtool): attack obj(the turret (/obj/machinery/porta_turret_cover), Whom (/mob/living/carbon/human))
[05:29:52]the turret (/obj/machinery/porta_turret_cover): attackby(the welding tool (/obj/item/weldingtool), Whom (/mob/living/carbon/human), "icon-x=24;icon-y=19;left=1;scr...")
[05:29:52]the turret (/obj/machinery/porta_turret_cover): attackby(the welding tool (/obj/item/weldingtool), Whom (/mob/living/carbon/human), "icon-x=24;icon-y=19;left=1;scr...")
[05:29:52]the welding tool (/obj/item/weldingtool): melee attack chain(Whom (/mob/living/carbon/human), the turret (/obj/machinery/porta_turret_cover), "icon-x=24;icon-y=19;left=1;scr...")
[05:29:52]Whom (/mob/living/carbon/human): ClickOn(the turret (/obj/machinery/porta_turret_cover), "icon-x=24;icon-y=19;left=1;scr...")
[05:29:52]the turret (/obj/machinery/porta_turret_cover): Click(the floor (90,146,7) (/turf/open/floor/plasteel/airless), "mapwindow.map", "icon-x=24;icon-y=19;left=1;scr...")
```

### PR DESCRIPTION
**Pull request by spessbandit**
## About The Pull Request

Removes all portable turret covers from the derelict and replaces them with nonfunctional turrets **with no guns**. Unless I fucked up the search these are the only standalone cover objects across the maps. Fixes https://github.com/tgstation/tgstation/issues/34929.

## Why It's Good For The Game

bug preventative measures

## Changelog
:cl: bandit
fix: The turrets on the derelict are less fucky.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
there is no reason for this to be possible, so this is not fixing the bug

**Comment by spessbandit** [comment]
clearly it's possible if it happened at least once! if only I could travel back in time to 2018 so we can get actual feedback on how

**Comment by spessbandit** [comment]
(my guess is some kind of ex_act memes)

**Comment by optimumtact** [comment]
I don't think you understand what im saying.

I'm sure it's possible, the runtime is more than enough proof of that.

it doesn't however, make any sense, which indicates it shouldnt' be possible, and the bug isn't that it happened, but that it was possible at all.

If you just cover up the runtime, the underlying cause will never be found, and no bug has actually been fixed, just papered over.

I will take a busy runtime log over unfixed issues any day

**Comment by bobbahbrown** [comment]
As I commented on the issue itself, if you wanted to investigate this runtime further, it occurred in round 82347.

https://tgstation13.org/parsed-logs/basil/data/logs/2018/01/22/round-82347/
https://sb.atlantaned.space/rounds/82347
https://scrubby.melonmesa.com/round/82347

**Comment by spessbandit** [comment]
fuck the derelict

**Comment by ShizCalev** [comment]
correct fix would be to check for parent_turret in all the attack_* procs in https://github.com/tgstation/tgstation/blob/8358169b8e5a37508ae4f15ac1db007ef14a4a88/code/game/machinery/porta_turret/portable_turret_cover.dm

**Comment by spessbandit** [comment]
@ShizCalev that was the original fix and then @optimumtact said it was wrong

**Pull request merged**
