### PR TITLE
You now have to stand next to the decoy nuke disk and examine it to know it's fake

### PR DESCRIPTION
**Pull request by ghost**
:cl: ShiggyDiggyDo
tweak: Syndicate experts were able to create more sophisticated copies of the nuclear authentication disk. While still unable to detonate the nuclear fission explosive with them, they're practically identical to the real disk if not examined closely.
/:cl:

The decoy nuke disk is pretty useless because anyone who hovers their cursor over it can see that it's fake. Now you have to stand next to the disk and examine it, so you may be able to swap it in the heat of the moment without people instantly noticing.

Sorry for the shitty commit name, I thought you had to actually write a detailed report of what you changed in "Message"

### CODE REVIEW

**Comment by 81Denton** [comment]
Good change for an item that is completely useless in its current state (you can buy C4 or the camera bug for 1 TC ffs)

**Comment by praisenarsie** [comment]
nah you should make it so you have to be holding or on the loc of the nukedisk to see if it's fake otherwise it gives the normal nukedisk description

**Review by Cyberboss — DISMISSED** [review]

**Comment by ShiggyDiggyDo** [comment]
@praisenarsie I can't code for shit, it's a miracle that I even managed to set up git

**Comment by ma44** [comment]
Thankfully spessmen have the ability to smell cheap plastic imitation of nook disks from over 7 tiles away

**Comment by ShiggyDiggyDo** [comment]
NanoTrasen trained them to smell fake nuke disks

**Comment by ExcessiveUseOfCobblestone** [comment]
`/obj/item/disk/fakenucleardisk/examine(mob/user)
>if(Ajacent(user))
>>to_chat(user, "<span class='warning'>Wait, this is a fake!</span>")
>else
>>..()`

With same desc and name as the nuclear authentication disk.

**Comment by Robustin** [comment]
/obj/item/disk/fakenucleardisk/examine(mob/user)
>..()
>if(Adjacent(user))
>>to_chat(user, "<span class='warning'>Wait, this is a fake!</span>")
>>for(var/i in 1 to 4)
>>>to_chat(user, "<span class='clownlarge'>YA GOT PRANKED!!!</span>")
>>>playsound(src, 'sound/items/airhorn2.ogg', 100)
>>>sleep(2)

This is the ultimate version of the code to which you aspire.

**Comment by ShiggyDiggyDo** [comment]
Thank you very much for the code @ExcessiveUseOfCobblestone

**Comment by Iamgoofball** [comment]
>>>sleep

**Review by Cyberboss — APPROVED** [review]

**Comment by FantasticFwoosh** [comment]
Agent Vreenak would like a word.

faaaake

**Comment by JJRcop** [comment]
You certainly can write a detailed description in the commit message, but the first line shouls be a summary. Alternatively you can follow [RFC1296](https://xkcd.com/1296/).

**Pull request merged**
