### PR TITLE
AI power net wiring update for layered cables & minor adjustments

### PR DESCRIPTION
**Pull request by Jambre**
This is a split from my other PR #54954 

This PR updates the power net setups around the AI and gravity generators on a couple maps. This utilizes the layered power cables, which I enabled in https://github.com/tgstation/tgstation/commit/567281538bd5add027a6446256ad42bb20152d9f
so this map update requires that commit otherwise there will be no power in affected areas.

Here are a picture to showing Metastation wiring change...

I drew some lines in mspaint to show a bit better the power lines. The yellow is a power feed from the station, that is directed into an SMES. There is a blue wire that leads from that battery to surrounding APCs such as down in Telecoms, and another blue wire that runs north through the wall into the AI chamber that is fed into the AI's personal battery backup, which APCs is powered by a separate yellow wire. 

ai_update

You can see how advantageous the multilayered cables are, with those cables not affecting other networks, you can run the cables along other ones cleanly. If you'd like to cross one layer to another, there is a cable connector hub (not the z level hub) that accepts and distributes the power to other layers. (Z is for multi-level stations.) Note: I do not believe the cable connector hub is buildable in game yet, but is perfect for mapping.

The other maps were updated to have the AI in similar setups, as well as the gravitational generators because they were not on running on their private SMES batteries.

## Changelog
:cl: Jamber
add: Updated AI power nets - runs off their own SMES that charges from the main power.
fix: Gravitational Generator's SMES is now connected properly
/:cl:

This _should_ compile cleanly I used the merge map tool. Here it goes.

### CODE REVIEW

**Comment by Jambre** [comment]
@LemonInTheDark In reference to your comment made https://github.com/tgstation/tgstation/pull/54954#issuecomment-727168171

Please check out the picture I provided. The AI's personal SMES is given power to the terminal through the blue wire. Currently it is powered by a full SMES which drains throughout the round. This setup does not allow for the AI's power to be sunk, as well as the Gravitational Generator's in Metastation which I also updated.

**Comment by Dennok** [comment]
Use cable hub in places where you need connect cable to machine.
I make  non central cables to not connect to machinery to be able  place it under machinery.  
(null)scrnshot1

**Comment by Dennok** [comment]
And i see you place cables in places where it must be placed by engineers on start of round

**Comment by Jambre** [comment]
> And i see you place cables in places where it must be placed by engineers on start of round

Are you talking about this hidden missing cable?

xx

**Comment by Dennok** [comment]
> Are you talking about this hidden missing cable?

Yes and i see new cable to AI sat on every(most) map that you change.

**Comment by optimumtact** [comment]
how is this a fix

**Pull request closed without merging**
