### PR TITLE
Laser beams have appropriately colored lights

### PR DESCRIPTION
**Pull request by TrustyGun**
space station 13 2017-03-06 205404

Now spacemen can have pretty light shows using the armory. Also makes all of the laser beams have light_range = 2 because lasers should give off light.

### CODE REVIEW

**Comment by Supermichael777** [comment]
"lasers"

**Comment by Dorsisdwarf** [comment]
lasers should only give off a tiny amount of light, but be rendered over darkness

**Comment by TrustyGun** [comment]
image

Updated the purple light to be lighter.

**Comment by AdamElTablawy** [comment]
i'd argue that lasers are focused light but tbh since they have a travel time who knows what the fuck they are

**Comment by TrustyGun** [comment]
it's not like this game is the paragon of realistic gameplay or anything

**Pull request merged**
