### PR TITLE
Fixes wizarditis runtime

### PR DESCRIPTION
**Pull request by Shadowlight213**

### CODE REVIEW

**Comment by Zilenan91** [comment]
Can you even obtain wizarditis normally?

**Comment by Shadowlight213** [comment]
@Zilenan91 Yes, the wizard's vending machine has a bottle

**Comment by Durkel** [comment]
I wouldn't exactly call getting a bottle from a usually unreachable area or from a area that you have no tools to hack in "normal".

**Comment by Bawhoppen** [comment]
@Durkel Staff of change an apprentice into a borg >choose engiborg >hack it >change him back to human 

easiest win of my life

**Pull request merged**
