### PR TITLE
Makes fire have coloured light

### PR DESCRIPTION
**Pull request by Cyberboss**
None of you memes remembered this

untitled

### CODE REVIEW

**Comment by coiax** [comment]
None of your FACE remembers this...

**Comment by coiax** [comment]
Gottem

**Comment by GunHog** [comment]
Pics plz k thx fam lol

**Comment by Poojawa** [comment]
Fire should color shift depending on temperature.

**Comment by Cyberboss** [comment]
That's just ASKING for performance issues

**Pull request merged**
