### PR TITLE
Ports Azlan's portable atmos machines from Baystation

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
image

Ports over Azlan's portable atmos machines from Baystation.
The scrubbers have been slightly edited to make them lighter to be in line with our whiter scrubbers.

unknown

## Why It's Good For The Game
Removes some more isometric sprites

## Changelog

:cl: Azlan, Wallem
imageadd: Ports Azlan's portable atmos machines from Baystation
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Death of soul

**Comment by Jackal-boop** [comment]
looks too boxy and angular

**Comment by BlueMemesauce** [comment]
> looks too boxy and angular

they're machines

**Comment by KommandantJackal** [comment]
Yes but most other atmos gear has curves and is more round

**Comment by tralezab** [comment]
looks fine

**Pull request merged**
