### PR TITLE
Cake Hat Power Creep

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
shameless self buff

**Comment by phil235** [comment]
what's the point?

**Comment by lzimann** [comment]
but why

**Comment by Aloraydrel** [comment]
Finally the cat hat meta begins

**Comment by PKPenguin321** [comment]
nice get

**Comment by GunHog** [comment]
Why not give it a squishy noise for when it is hit?

**Comment by MMMiracles** [comment]
slowly but surely, the cake hat will be the best weapon in the game

**Comment by lzimann** [comment]
\>implying it already isn't the best weapon in the game

**Comment by GunHog** [comment]
It is the best melee weapon against blobs. 15 burn, but no fuel concerns like a welder has.

**Comment by lzimann** [comment]
someone needs to remake that PR that turns you into a cake if you wear it for too long

**Comment by optimumtact** [comment]
Nice get

**Comment by Zilenan91** [comment]
We should totally have that cake pr, and also buff the shit out of the cake hat

You will be consumed by its power

**Comment by Bawhoppen** [comment]
:+1: for title being accurate

**Comment by swankcookie** [comment]
Can we make it a semi-annual tradition that someone just creates a PR adding 1 lum to the hat.

**Comment by lzimann** [comment]
road to cakehat illuminating the entire station

**Comment by Bawhoppen** [comment]
requesting speedmerge

**Pull request closed without merging**
