### PR TITLE
Robot pulls are not strong enough to restrain handcuffed prisoners; Re-enables secborgs, with no config. 

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Borgs can't valid hunt if you take away their arms!

new pr so i can get the extra commit in that isn't in the old pr because it got closed too soon

### CODE REVIEW

**Comment by evsey9** [comment]
no, fuck secborgs, they still are perfectly able to validhunt by keeping you stunlocked and being basically better sec officers

**Comment by KorPhaeron** [comment]
This won't really work other than to confuse newbie sec borgs since they have can chainstun the person they are dragging

**Comment by PKPenguin321** [comment]
Good start but easily circumvented and many more changes are required before secborgs should come back. This doesn't adequately address even a single one of their issues.

**Comment by MrStonedOne** [comment]
@tgstation/commit-access re-open please

**Pull request closed without merging**
