### PR TITLE
Adds public autolathe shutters to Box cargo

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: On Boxstation, Cargo can optionally open up their autolathe to the public, via shutters. Some consoles and machinery has moved to accomplish this feat.
/:cl:

image

#41608 is filled with passionate people talking about whether Box should have a public autolathe. View this PR as a sort of compromise. Essentially, Cargo can enable people to use their autolathe, but only if they want. Shutters are down by default, and Cargo Sec have full view of people using it if they are. The button has Cargo Bay required access.

- **But what if assistants just smash in to get to the autolathe?** - They could do that already, it's the same level of reinforced window.
- **I have strong feelings about public autolathes.** - Cargo retain control of the autolathe, and can still elect to serve requests normally. This leaves the decision up to cargo, in the same way they could always manually rebuild the autolathe to put it outside.
- **I want Box to be unique.** - Well, it still is. Only Box has the patent pending Autolathe Queue and Shutters.
- **The Cargo Security's copy of Space Law is all the way in the corner. What if he needs it?** - I'm sure he'll stagger through. He can fire disabler shots through the windows anyway.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
Hello yes I am very very very mad
couldn't it just be like, one shutter? with the autolathe being in the bay and the shutter being in place of a window? I think this takes up quite a bit more space than it needs to. absolutely furious.

**Comment by coiax** [comment]
That sounds boring.

**Comment by anconfuzedrock** [comment]
I can't tell if this is a meme pr or not but I'm leaning towards meme

**Comment by coiax** [comment]
I am 100% serious, I think it's a neat idea for a cargo-opt-in public autolathe system. It also sorts that problem where everyone's trying to use the public autolathe at once.

**Comment by anconfuzedrock** [comment]
I mean, it's just, like, it's an autolathe... I don't really think it needs several shutters? it takes up a lot of space and lets cargo trap people? I mean I like the idea of the autolathe being shuttered it's just... this is so weird...

**Comment by kingoftheautism** [comment]
@coiax Did you put firelock under autolathe? Or shutters?

**Comment by coiax** [comment]
No, but you're right, I should put some fire shutters.

**Comment by Repukan** [comment]
Better solution would be to remove the public lathes

**Comment by coiax** [comment]
Make the PR then.

**Comment by Barhandar** [comment]
Can you still brped ORM, protolathe and autolathe without entering cargo or using cameras?

**Comment by improvedname** [comment]
Add the shutter button to the security offices too

**Comment by nicbn** [comment]
The queue looks ugly, use a single shutter above the lathe.
Also I think it'd be more useful to have the ORM instead of the autolathe in that spot. After all, if cargo wants public autolathe, they can just move it.

**Comment by kingoftheautism** [comment]
>shutters above latte
then both cargo and rest of the crew cant use it

**Comment by ExcessiveUseOfCobblestone** [comment]
> sandbox game

>> people insist on building everything from the map POV instead of letting players do their own improvements

this game lol

**Comment by coiax** [comment]
Shutters aren't constructable. And that is true, Cobby, but only if you accept that the sandbox gets reset every 30 to 90 minutes, and people will occasionally kick your sandcastles over.

**Comment by ExcessiveUseOfCobblestone** [comment]
I accept that openly, if I wanted to build up on a persistent playground I'd play wurm/minecraft. That doesn't mean because these places reset that I want streamlined processes. Perhaps this streamlining plays a role in why rounds are ~an hour.

I think building great projects or even simple improvements in the face of those challenges is what makes the game fun. I had a blast showing people how easy medical is by moving sleepers to the front doors (literally the 2 tiles going into medbay) and watched how medbay just do whatever they wanted. Funny enough since then they've been buffed, I should do it again sometime lol.

A more obvious example, albeit a bit different, is my gimmick of "Man of Many Traps". It was quite a popular gimmick, so much that it got turned into a feature (I think by coiax lol). Since then it's just meh, not to either coiax's or my fault imo. From what i've seen, when you codify these features/gimmicks/improvements/etc. they seem to lose their flare.

**Comment by coiax** [comment]
You're acting like this PR is pioneering the use of a public autolathe, except that exists on all other maps except Box, and Box is so unpopular, many admins force rotate away from it.

**Comment by ExcessiveUseOfCobblestone** [comment]
Other maps having a public autolathe is not a justification if you can't explain why it's good to have.

**Comment by nicbn** [comment]
Having a public autolathe won't magically make box popular, also what cobby said

**Comment by coiax** [comment]
Were you the sort of person that was opposed to removing the sulphuric acid requirement from Science to print circuit boards?

**Comment by nicbn** [comment]
It's a totally different situtation. The reason for cargo to exist is to supply the station as a whole, and chemistry is more like bound to medbay.

Removing sulphuric acid requirement made chemistry no longer need to do something that wasn't their "core" job, but removing logistic and supply aspects of cargo is like moving the bar dispenser out of the bartender desk because "it's to annoying to have to ask the bartender and now people can serve themselves".

**Comment by FantasticFwoosh** [comment]
I misread to thinking you added constructable shutters to the autolathe.

This is fine too, if a bit cluttered.

**Comment by Cyberboss** [comment]
Not a fan of the mini hopline, it cuts into too much of the cargo lobby's space

**Comment by coiax** [comment]
It's only a single row, since I shrunk the Cargo Security by one row.

**Pull request merged**
