### PR TITLE
METASTATION: Atmospherics Remap/Expansion (Project space, dedicated HFR chamber, crystallizer!)

### PR DESCRIPTION
**Pull request by Potato-Masher**
## About The Pull Request
This PR contains a hefty overhaul to the Atmospherics section of Metastation with tons of new space and some additions and adjustments to encourage experimentation with gas reactions. No space has been taken away from maintenance; most if not all of the expansion has been into space right of atmos.

image

<details>
<summary>(Image with cables and the under-floor distro and scroober pipes, OUTDATED)</summary>

</details>

This is probably the most non-standard looking atmos setup to exist so far, but I've made sure to keep the roundstart functionality on par with the old version.

Some notes on this atmos:

- Yep, that's a Crystallizer up there with it's own little basic starting setup and thermomachine. If you have something in mind you want to make using the Crystallizer, it's already ready to go (at least in a basic capacity).
- The HFR chamber is now a separate area with it's own APC, and is no longer nearly as cramped as the old room. It has rad shutters controlled by buttons from the inside and outside of the room to help prevent those working outside the chamber from getting irradiated as easily. 
- Some empty space has been deliberately freed of pipes to provide some much needed room to tinker with gas mixtures.
- An electrical supplies table with some trinkets and tools like multitools and construction bags were added.
- All of the piping inside the walls that's critical to atmos is now visible above the wall or have been moved out of glass, allowing removal and replacement without having to tear down the whole wall or window.
- A space back porch with a space lounge chair and space books for space reading. In space.

Included in this PR are some adjustments to the xenobiology minisat in matters of atmos, namely regarding the cooling for the slime euthanization chamber. The cooling loop has been prettied up making it no longer a spam of 4way H/E pipes. Pipes connecting to the cooling loop now have a stationary CO2 tank connected in xenobio maint, thus removing the need to manually set up the cooling gas.

## Why It's Good For The Game

Atmospherics Technician as a job, outside of sealing hull breaches and restoring clean air to areas, has a whole wealth of content in the form of gaseous synthesis, the HFR, and physical items produced from the Crystallizer. From personal experience and observations, rarely do any of these features get used most rounds which is a shame as there's a lot of stuff to do and make. 

I believe the primary reason as to why these features see rare use is the fact that it takes a significant amount of time to get things going and set up. As a comparison, a chemist working in the pharmacy already has everything he needs to begin making chemicals (chem dispenser, reaction chamber, etc). He doesn't need to build his machines from scratch to start making chems. An atmos tech usually has to spend time to construct a pipe setup that can facilitate the reaction with temperature control and filtering of the needed product gasses built in mind. 

The easiest way to encourage use of the feature is to make it more accessible. This is the goal behind this first remap. Problems with the current meta atmos: 

- Meta atmos was completely full with piping from the beginning, so new custom piping necessitated cannibalizing parts of the gas network in the center of the room and the distro room.
- The HFR chamber was in this small little tumor of a room awkwardly added onto what once was a simple exterior airlock access. Space is a luxury in that room, and there isn't any room directly outside that area either unless you want to constantly shift between the station interior and space.
- The crystallizer, as on all the maps, was nowhere to be found and goes unused very often, maybe even less than the HFR. The HFR at the very least starts with parts for it's construction and it's own room.
 
Overall, meta atmos was the worst map for doing any sort of fancy atmospherics work. It's design has been pretty much unchanged for as long as it's been around, even with the introduction of new gas types and machinery.

This design hopes that by including the crystallizer from the start, having extra space for projects, and having extra space for the HFR will make approaching gaseous synthesis more accessible (at least on meta), and thus, more appealing.

## Changelog

:cl:PotatoMasher
expansion: Metastation - A near complete remap of the atmospherics section of the station. Functionally the same, but with added space for projects, the HFR, and an included basic crystallizer setup.
qol: Minor atmospherics adjustments to metastation's xenobiology satellite, the slime euthanization chamber cooling loop has been prettied up and starts with CO2 already inside to ensure the freezer works immediately with no setup.
/:cl:

### CODE REVIEW

**Comment by drIcepop** [comment]
look at all those layer adapters, got damn!!!

**Comment by Ghilker** [comment]
Loving it!

**Comment by Nistishere** [comment]
Seems good to me

**Comment by Zytolg** [comment]
Alright, so I'm gonna lay down my initial thoughts on this. While I don't think providing metastation's atmos with more space is not necessarily a bad thing, I do believe that this PR takes things in the opposite extreme. I already do not like Chemistry's Chemfactory Room due to the sheer amount of plain open space it demands. This is makes atmospherics even larger than that, and for me, that's a big no. 
Before continuing, I want to make two points very, very clear. Firstly, Atmos as it currently is (before this PR), is deliberately designed to be as ineffective, and bulky as possible. While the exact reasons for why it's done this way are lost to time, this is at least the accepted reason for it- That Atmos Techs will take the time to optimize the pipe network and then do their projects. This leads me to my second point. We have 5 pipe layers, and a myriad of pipe colors, which allow Atmos players to condense their atmos setups by an insane amount. I used to play atmos before we had 5 pipe layers, and doing crazy stuff with metastation's atmos setup was never a problem for me back then. Granted things have changed, but I don't think they've changed enough to effectively Triple the total amount of space avaliable to atmos techs. 

I won't deny that Atmos Techs probably need the extra space. As we continue to add machines to the the department it's inevitable that we're going to run out of space somewhere. However, instead of such an extreme rework of an already functional department, I would like to propose a policy discussion with the Maptainers, and likely the Maintainers as well. If atmostechs have no interest in optimizing their pipe network, yet yearn for space for high skill level setups, then should the pipe network be optimized at mapload? This will raise the skill floor for the gameplay in the department, but has the advantage of freeing up quite a bit of space that high level gameplay may need. Either way, atmos gets reworked into a more moderate version of this, but it's certainly worth considering.

**Comment by GuillaumePrata** [comment]
Meta is the "Standard" map and the best map for teaching new Atmos Techs IMO, mostly because it was small and clean.
You could sit in the middle of the room and see all of the system which is really good for the average "stare at the pipes until you understand" approach that most people hear and try to follow by themselves on a first shift ~~before giving up~~.

This Meta is now huge, but unlike Delta, it still is quite clean to read. The only 2 pet peeves I have are:
<details>
<summary>
The distro pipes snaking under the console with a layer manifold instead of having straight pipes on the tile below it.</summary>

</details>
<details>
<summary>
And that the 3 canister connectors are on top of red pipes with open space between both purple pipelines that could be used.</summary>

</details>

Atmos Tech is IMO, the worse job to learn in the game with a lot of important info being locked behind reading the code or being directly taught by players and not in game mechanics. Having a map that is clean for new players to grasp, without pipes going on top of pipes, is important.

Even more because the experienced players will turn the place into pipe salad 2 minutes into the shift regardless of how much we optimize it...

**Comment by LemonInTheDark** [comment]
Maybe a bit big, not going to have an opinion about that, but there's some stuff that's a bit worrying
> All of the piping inside the walls that's critical to atmos is now visible above the wall or have been moved out of glass, allowing removal and replacement without having to tear down the whole wall or window.

What does this mean? Are you just moving pipes around, or is there layer var editing fuckery going on or something
Outside of that I'm not a huge fan of the multilayer adapters. Not sure how much my opinion matters for that but it feels like roundstart volume pumps to me

**Comment by Pickle-Coding** [comment]
If the layer adapters are a problem, I'd like the pumps to stay in front of them. It's annoying if someone rushes pure and now you have to empty it, or fly around to unwrench the pipes.

**Comment by Potato-Masher** [comment]
> What does this mean? Are you just moving pipes around, or is there layer var editing fuckery going on or something

That means I'm just using the "visible" subtype of the pipes rather than the "hidden" type. Hidden puts the pipes under floor tiles and walls, visible keeps them on top of said structures. Minor change but it keeps pipes from being totally inaccessible and helps with visibility on where pipes are actually going.

**Comment by Maurukas** [comment]
In my opinion, this doesn't come anywhere near an optimized setup. An optimized setup would would reflect 'Rule 0' of atmospherics and pipenetworks. There would be no gas pumps to rip out and straight pipe. This setup is basically Meta atmos turned sideways, with no real optimization applied. It just stretches it out a little and makes it a little more understandable. I like this a lot.

Multilayer adapters on the tank outputs I'd count more of a QOL thing. They make setup a little neater and quicker, and they allow multiple players to share the output of a tank. They do not make the tanks or outputs better or more efficient, just a neater way for players to hook their own construction in.

Zytolg does raise a good point though. Atmos piping is significantly more space efficient and optimized than plumbing. This adds a **lot** of space. What exactly would be built in this space? Are these things that could use the HFR's space, or do they work together with the HFR? There's a lot of unused space around the crystallizer. Can this be squeezed down at all?

> I believe the primary reason as to why these features see rare use is the fact that it takes a significant amount of time to get things going and set up. 

I've been doing quite few rounds with exotic engines, and generally trying to get better at atmos. I'm fairly sympathetic to this point of view. It takes a *lot* of time to get certain things setup. I think we need to do a better job of providing an infrastructure that's easier to build these advanced machines and setups off of. That setup should be not entirely optimal - like the SM, ~Toxins~ Ordnance, and the Turbine. It should provide a functional base for the players to build off of.

I want to see more players building weird things in atmos and engineering.

**Comment by Zytolg** [comment]
I want to point out that the atmos pipe layout situation is essentially "Box station's setup works, so lets replicated it on x_station". You shouldn't feel beholden to that "norm" since it's the easy way for mappers to make atmos work (imitation is the greatest form of flattery after all). I'd like to say that 2020-2021 tgstation mapping has seen a transition from a purely utilitarian orientation into more of a gameplay experience orientation. 

> If the layer adapters are a problem, I'd like the pumps to stay in front of them. It's annoying if someone rushes pure and now you have to empty it, or fly around to unwrench the pipes.

This doesn't have to be a problem and the tgstation mapping team encourages experimentation on new formats within reason.  Idyllically, every station should bring something different and exciting to the table. They should present different challenges to overcome, and embody both unique strengths and weaknesses. The Engineering Department as a whole is an amazing place to start with these forms of changeups. 

PR's like this are good not just for content, but to also highlight some of the more severe flaws on some of our maps. Delta Station in particular has been in a state of neglect, and this PR especially highlights just how critical a redo of her Engineering Department is. I'll probably have to bump it up to the next thing I'll do.

**Comment by optimumtact** [comment]
@tgstation/maptainers

**Comment by Potato-Masher** [comment]
mapdiff machine broke

**Comment by optimumtact** [comment]
did this add a roundstart crystallizer?

**Pull request merged**
