### PR TITLE
Welding goggles balance

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Balances welding goggles cost and adds and YouTool

## Why It's Good For The Game

Moths need double eye protection for welding, but can't get both sets without the protolathe access. This gives them a source to buy without pestering a department. Since they are an upgrade over the welding helmet, adjusted the material cost and vendor price over the helmet.

## Changelog

:cl: LT3
balance: Welding goggles price increase
balance: Welding goggles are available in the YouTool vendor
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
powermoth. moths should steal sunglasses from lawyer's office instead of purchasing these paltry goggles

**Comment by Dorsisdwarf** [comment]
Is QOL entirely fair for this one? Because yeah it is quality of life for moths, but its also a straight buff for everyone else since you're putting an upgraded/limited item into general circulation at the same price.

**Comment by lessthnthree** [comment]
> Is QOL entirely fair for this one? Because yeah it is quality of life for moths, but its also a straight buff for everyone else since you're putting an upgraded/limited item into general circulation at the same price.

I'd say it's a buff if there was anything inherently special about the goggles, or if it was an upgrade. The helmet provides fire and acid protection vs. the goggles, they have the same tint value and protection.

**Comment by moocowswag** [comment]
The sci protolathe can also print welding goggles and its alot more accessible than engie on most maps btw.

**Comment by SuperNovaa41** [comment]
These should cost more, they're a direct upgrade to the welding mask

**Comment by lessthnthree** [comment]
Okay. I'll raise the price and keep it to protolathe.

**Comment by ExcessiveUseOfCobblestone** [comment]
I am not really a big fan of the sole reason for the change to be an offset for a particular species who is intentionally made to be poor at welding.

You have 2.5 departments (I think moths can use welding eyes too) to interact with as options if you are dead set on doing a lot of welding, not to mention dozens of non-moth players you could ask to weld for you with the existing protection that you have.

I very much dislike the thought process behind the change, theres plenty of ways to tackle the issue that doesnt include making it easier for the species to bypass at a code level.

**Comment by lessthnthree** [comment]
Sounds good.

**Pull request closed without merging**
