### PR TITLE
Anyone can now reactivate dead drones with a screwdriver

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Anyone can now attempt to reactivate dead drones with a screwdriver.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Wasn't this already denied

**Comment by ChangelingRain** [comment]
No.

**Comment by optimumtact** [comment]
yes it was -_-

**Comment by PKPenguin321** [comment]
what did he mean by this?

**Pull request closed without merging**
