### PR TITLE
Adds desc to vendor circuit board

### PR DESCRIPTION
**Pull request by 81Denton**
I didn't even know you could switch between different machines until I pulled up the file.

### CODE REVIEW

**Comment by Repukan** [comment]
Is there a less ooc way of wording this?

**Comment by 81Denton** [comment]
🤔

**Comment by Repukan** [comment]
"The settings of the vendor could be changed with a tool/screwdriver"

**Comment by 81Denton** [comment]
Yeah that's a good one

**Comment by 81Denton** [comment]
How about "You could turn the "brand selection" dial using a screwdriver."

**Comment by Repukan** [comment]
Yeah that sounds better

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
