### PR TITLE
Added The Tenets of Servicia to religions

### PR DESCRIPTION
**Pull request by RaveRadbury**
To celebrate the integration of civilians into the Service Channel, here's a fun religion for the Service department to gimmick together.

## About The Pull Request
- Adds the holy book "The Tenets of Servicia" 
- Get by worshipping "Space Dionysus", "Space Bacchus", "Partying", or "Servicia". 
- The book's description carries the Actual Holy Tenets: "Happy, Full, Clean."

## Why It's Good For The Game
It's hilarious to have the Chaplain's influence on a department-nation produce a theocracy that professes Good Service and Partying as the highest forms of being and worship. 

Imagine service decked out in follower outfits throwing ritualistic parties. 

Also, all the other religions are pretty much name and god only. It might be interesting to see what happens with a religion that has any in-game statement of core principles.

This religion also makes the bottle in the bible incredibly in-character, as the entire holy text is probably on the first page. And, y'know, the partying.

Praise Servicia!

## Changelog
:cl:
add: Added "The Tenets of Servicia" to Chaplain religions
add: Added deities "Space Dionysus", "Space Bacchus", "Partying", and "Servicia"
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Praise onto Dionysus! I mean Bacchus! Oh whatever.

**Comment by RaveRadbury** [comment]
@necromanceranne Space Dionysus confirmed.

**Comment by ATH1909** [comment]
> Praise onto Dionysus! I mean Bacchus! Oh whatever.

Ah man, that Bacchus, what a great guy. Hey, remember that time that he drove half of a city mad because they didn't worship him because they thought that he had been killed as a baby by the gods? And then when he later used his godlike powers to make the ruler of that city crossdress and head into the middle of the wilds, where he was then ripped into tiny pieces by the bare hands of those people who he drove insane? Oh man, imagine what the face of that ruler's mother must have looked like when she regained lucidity halfway through parading her own son's head through the city like that of a lion's and realized that she had ripped the left arm off of her own son while leading the charge of the mob that brutally killed him while he begged and screamed for her to stop and recognize her own son? Hahahaha, good times, good times.

https://www.albany.edu/faculty/dg6349/CLC105_SP07/docs/bacchae.html

In all seriousness, I do like this PR. It gets a thumbs up from me.

**Comment by necromanceranne** [comment]
Haha, yeah, what a wild guy.

**Comment by ATH1909** [comment]
> Pentheus fell,                             [1110]                 
         crashing to earth down from his lofty perch,
         screaming in distress.  He knew well enough                        1380
         something dreadful was about to happen.
         His priestess mother first began the slaughter.
         She hurled herself at him. Pentheus tore off
         his headband, untying it from his head,
         so wretched Agave would recognize him,
         so she wouldn't kill him. Touching her cheek,
         he cried out, "It's me, mother, Pentheus,
         your child.  You gave birth to me at home,
         in Echion's house. Pity me, mother—                                            [1120]
         don't kill your child because I've made mistakes."                 1390
         But Agave was foaming at the mouth,
         eyes rolling in their sockets, her mind not set
         on what she ought to think—she didn't listen—
         she was possessed, in a Bacchic frenzy.
         She seized his left arm, below the elbow,
         pushed her foot against the poor man's ribs,
         then tore his shoulder out.  The strength she had—
         it was not her own.  The god put power
         into those hands of hers.  Meanwhile Ino,
         her sister, went at the other side,                                           1400
         ripping off chunks of Pentheus' flesh,
         while Autonoe and all the Bacchae,                                                [1130]
         the whole crowd of them, attacked as well,
         all of them howling out together.
         As long as Pentheus was still alive,
         he kept on screaming. The women cried in triumph—
         one brandished an arm, another held a foot—
         complete with hunting boot—the women's nails
         tore his ribs apart.  Their hands grew bloody,
         tossing bits of his flesh back and forth, for fun.                     1410
         His body parts lie scattered everywhere—
         some under rough rocks, some in the forest,
         deep in the trees.  They're difficult to find.
         As for the poor victim's head, his mother                                      [1140]
         stumbled on it.  Her hands picked it up,
         then stuck it on a thyrsus, at the tip.
         Now she carries it around Cithaeron,
         as though it were some wild lion's head.

**Comment by necromanceranne** [comment]
Haha, yeah....

:3

**Comment by RaveRadbury** [comment]
When it's time to party we will party hard

**Pull request merged**
