### PR TITLE
Replaces the move fast traits with speed mods

### PR DESCRIPTION
**Pull request by ninjanomnom**
Also removes the physiology speed mod.

More gradual removal of the move delay proc. This one should probably get testmerged just to make sure the movespeed modification system can handle this sort of thing.

### CODE REVIEW

**Comment by Cyprex** [comment]
If I read this right this means different sources now stack, is that correct?

**Comment by ninjanomnom** [comment]
The physiology mods already stacked and so would the fast and faster traits. But yes other than that they can now stack. I don't see that as too much an issue and we can reduce the values if it does become one.

**Comment by ninjanomnom** [comment]
Apparently I need to handle conflicting movespeed modifiers for another use case anyway so I may apply that here as well if it turns out to be a bad thing in the testmerge

**Comment by Iamgoofball** [comment]
R.I.P GOTTAGOREALLYFAST

**Comment by Cyprex** [comment]
Sorry, I should have clarified, I meant different sources of GOTTAGOFAST. I don't see them stacking as much of an issue due to very high movement speed values making controlling your character difficult.

**Comment by ninjanomnom** [comment]
This has been testmerged since the label was added and is probably good to go. I've not heard of anyone noticing any differences.

**Comment by XDTM** [comment]
You could preserve the non-stacking aspect by making a shared chemical speed ID for the speedmod

**Comment by Iamgoofball** [comment]
also the fact that to stack both you'd have to be on two very fucky drugs at once

**Comment by ninjanomnom** [comment]
@XDTM Already considered that, it doesn't work because if you have two then remove one it removes both since it's not like traits

**Comment by Vidiveni** [comment]
Bear traps don't seem to work during current test merge. Didn't slow people down (at least noticably).

**Pull request merged**
