### PR TITLE
Outpost45 runtime fix

### PR DESCRIPTION
**Pull request by Yobrocharlie**
## About The Pull Request
fixes a few runtimes
## Why It's Good For The Game
makes outpost 45 cause less lag and adds a new tile, asteroid gravel which is mechanically identical, but adds nothing actually new to the outpost
## Changelog
adds a new tile, asteroid gravel which is mechanically identical to the old var eddited asteroid sand.
:cl:
fix: makes outpost45 cause less lag
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
'Fixed a few things' isn't a very good changelog

**Comment by Yobrocharlie** [comment]
> 'Fixed a few things' isn't a very good changelog

all i did was remove the var eddited tiles and replaced them with a new tile which is functionally the exact same

**Comment by Pumpkinoe** [comment]
> all i did was remove the var eddited tiles and replaced them with a new tile which is functionally the exact same

then say 'fixed outpost 45 runtimes' so that people looking through the changelog in the future know what you did instead of having to guess what you fixed

**Comment by Yobrocharlie** [comment]
> > all i did was remove the var eddited tiles and replaced them with a new tile which is functionally the exact same
> 
> then say 'fixed outpost 45 runtimes' so that people looking through the changelog in the future know what you did instead of having to guess what you fixed

thats what the title says

**Comment by Pumpkinoe** [comment]
> thats what the title says

But the title isn't visible in the ingame changelog. There is a changelog separate from the title for a reason.

**Pull request merged**
