### PR TITLE
Removes the compact combat shotgun 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by senjx**
## About The Pull Request

"I believe the compact combat shotgun, and all similar shotguns should be completely removed from the code." - oranges

## Why It's Good For The Game

"Super alpha strike compact shotgun is not really healthy for game balance." - Rohesie
Refer to #50750 for other arguments.

## Changelog
:cl:angelstarri
del: MA Arms Inc. has initiated a product recall of all compact combat shotguns due to faulty internal magazines that cause the weapon to explode after firing. Unfortunately, all of the weapons in our stock have already exploded. We're not going to acquire any replacements.
/:cl:

### CODE REVIEW

**Comment by Cartographer-D** [comment]
Again, this isn't going to do anything except have the warden go for a riot shotgun shiftstart. Congratulations.

**Comment by Cartographer-D** [comment]
This is a redo of #50750 btw, for those of you just joining us.
image

**Comment by Rohesie** [comment]
The gun has in-hands, correct?
I wouldn't completely remove it from the code, but only from regular spawns, personally.

**Comment by senjx** [comment]
> The gun has in-hands, correct?
> I wouldn't completely remove it from the code, but only from regular spawns, personally.

the fruit themselves requested this

**Comment by senjx** [comment]
> Again, this isn't going to do anything except have the warden go for a riot shotgun shiftstart. Congratulations.

i dont have a problem with that

**Comment by Rohesie** [comment]
> > The gun has in-hands, correct?
> > I wouldn't completely remove it from the code, but only from regular spawns, personally.
> 
> the fruit themselves requested this

Check the in-hands then, see you don't leave unused sprites there.

**Comment by senjx** [comment]
I checked the guns inhand dmi file and I couldn't find any sprites specific to the combat shotgun.

**Comment by senjx** [comment]
> > > The gun has in-hands, correct?
> > > I wouldn't completely remove it from the code, but only from regular spawns, personally.
> > 
> > 
> > the fruit themselves requested this
> 
> Check the in-hands then, see you don't leave unused sprites there.

The compact combat shotgun uses the same in-hand sprites at the regular combat shotgun.

**Comment by PKPenguin321** [comment]
i think either this or add an actual downside to sawing off your gun would be good

**Comment by wesoda25** [comment]
Who the fuck is MA arms

**Comment by Shadowflame909** [comment]
> 
> 
> i think either this or add an actual downside to sawing off your gun would be good

sawed off shotguns did get a nerf and now spread is stinky and you'll generally miss from 1 tile away

But high damage backpack storage is worth it

**Comment by optimumtact** [comment]
I think the best way to balance sawnoffs is to limit them to shotguns with 2 or less shots in the chambers.

**Comment by BeeSting12** [comment]
Keep it in the code for admin use just remove them from the maps.

**Comment by tmtmtl30** [comment]
image
cringe
(this PR is still stupid, by the way, literally trying to fix something that is, per the server's own fucking rules, explicitly sanctioned, with a removal that simultaneously buffs every antagonist)

**Comment by tmtmtl30** [comment]
image
oh come on

**Comment by necromanceranne** [comment]
Why is this a rules issue? @tmtmtl30

The warden can kill you with an assortment of weaponry and his shotgun can equally be geared to be nonlethal if he so chooses. This doesn't have anything to do with it being a rules issue it's a balance one.

**Comment by steamp0rt** [comment]
I used the shotgun. Wanna know why?

**Comment by SkeletalElite** [comment]
But the compact combat shotgun cant be put in a backpack. It is a bulky item. The only advantage it has over a regular combat shotgun is that you can put it on the armor slot. It's not significantly stronger than an unsawed off riot shotgun, it has a minor advantage in that it's a little easier to use and shoot fast, but gets 2 less shots.

**Comment by Shadowflame909** [comment]
> 
> 
> But the compact combat shotgun cant be put in a backpack. It is a bulky item. The only advantage it has over a regular combat shotgun is that you can put it on the armor slot. It's not significantly stronger than an unsawed off riot shotgun, it has a minor advantage in that it's a little easier to use and shoot fast, but gets 2 less shots.
> 
> I fail to see how any of the described "problems" are a problem with the compact combat shotgun and not a problem with shotguns in general

Well maybe any shotgun that can be stored anywhere outside of a rare event needs to despacito.

**Comment by SkeletalElite** [comment]
> Well maybe any shotgun that can be stored anywhere outside of a rare event needs to despacito.

If that's the case then do that in the PR instead of just removing the compact combat shotgun so that warden's don't just start taking riot shotguns instead.

**Comment by Archanial** [comment]
Stop trying to balance every weapon. This is not some competitive esport game. Only one exists for a reason.

**Review by Rohesie — APPROVED** [review]

**Comment by Shadowflame909** [comment]
Shotguns unironically do more damage, or if not on-par with the admin only pulse rifle.

Its main caveat being it loses all that power the further away your target is, making it literally a ranged melee weapon.

Thus preventing such a weapon from being able to "sneak attack" players does nothing to stop its ferocity. It just stops the ease of accessing it.

**Comment by necromanceranne** [comment]
They don't equal a pulse rifle at all. They actually outdamage the pulse. Even slugs outdamage pulse. The benefit of pulse is that it destroys everything between you and who you are shooting and can be spammed. Pulse rifles also come with tasers.

Crew pulse slugs are only 40 and normal are 50.

The average slug is 60 and buckshot is 75 total, being 6 shots of 12.5 damage. 

There is also no functional way to lessen the impact of the alpha strike without completely gutting the impact of getting the first strike. Which would require a pretty radical change to the game as a whole and I don't know how that would look without really messing up gameplay. Whether it is a shotgun, baton, laser, revolver, whatever, doesn't matter. The alpha strike can be anything but it often is what determines who wins or losses.

**Comment by Shadowflame909** [comment]
and that's POST necromanceranne nerf.

Weapons just the megafauna of on-station weaponry.

Speaking of megafauna, have I told you my story of being cheesed by a shotgun as one?

**Comment by Pugie** [comment]
> and that's POST necromanceranne nerf.
> 
> Weapons just the megafauna of on-station weaponry.
> 
> Speaking of megafauna, have I told you my story of being cheesed by a shotgun as one?

Don't compare lesssr ash drake to megafauna

**Comment by tmtmtl30** [comment]
>complaining about your horribly unbalanced RNG murderbonefest loot not being unbalanced enough
lmao

**Comment by Shadowflame909** [comment]
Harder to get then a shotgun. That's for sure.

**Comment by tmtmtl30** [comment]
so is a dark blessing, doesn't mean it deserves to be OP

**Pull request merged**
