### PR TITLE
BirdShot Service Department Changes

### PR DESCRIPTION
**Pull request by GremlinSeeker**
## About The Pull Request
Revitalizing birdshot by extensively  changing up most of the service departments.

## Why It's Good For The Game

Birdshot is in need of some changes. I was hoping that these changes would help improve it in the eyes of players.

This birdshot update features essentially an entirely moved/renovated service departments, along with an addition to an arcade and a commissary, along with a much improved public chapel. Moved the service lathe to a new service hall found between the kitchen and hydroponics. You can see the new layout below.

image

## Changelog

:cl:viralmilk22
add: Vacant Commissary and Arcade to Birdshot. Most service departments have been redone.

/:cl:

### CODE REVIEW

**Comment by Ilgradhr** [comment]
Atmos department is too cramped you cant do shit there

**Comment by GremlinSeeker** [comment]
> Atmos department is too cramped you cant do shit there

I believe someone else is working on that, it'll likely come later.

**Comment by Formerxboxgamer** [comment]
Finally someone fixed the god awful foot traffic at the center part of the station. Bar and kitchen patrons being 2 screens apart from one another on the old design was easily the worst part of birdshot.

**Comment by MrMelbert** [comment]
You should go into detail about what's changed, just a simple list would suffice (IE, "remapped x, y, z")

**Review by MrMelbert — COMMENTED** [review]
Camera on window
image

**Review by MrMelbert — COMMENTED** [review]
Camera on window
Also these cams are a bit close to one another

image

**Review by MrMelbert — COMMENTED** [review]
Camera on window, camera on door

image

**Review by MrMelbert — COMMENTED** [review]
At a glance seems like all these doors have only plating underneath them / no floor tiles
Also if I'm not mistaken that air alarm is behind a dir window
Also also, throw some decals around, looks a little plain
Also also also, why does botany have a public facing seed extractor? I would replace that with a fridge
Also also also also, service hallway shouldn't use a hydroponics door

image

**Review by MrMelbert — COMMENTED** [review]
This disposal seems to go into the void, unless it goes under the wall I guess but that seems a weird way to run it

image

**Review by MrMelbert — COMMENTED** [review]
- No Request Console in Botany or the Kitchen
- No newscasters in Botany, Bar, Library (this is a big one), Library backroom, arcade, comissary
- No Intercoms in Botany, Kitchen, Bar, Library, Park, Arcade, Bar Backroom, Kitchen Coldroom
   - Use intercom range display mapping debug verb for help, main hall looks a little sparse too
- No Fire Alarm in Arcade, service hallway
   - Service hallway seems to not have firedoors at a glance, could be wrong
- No Light switch in Kitchen, Botany, (Arcade but that's subjective) 
- No camera in Comissary, Library Backroom, Kitchen Coldroom
- No camera in Bar Backroom
And small things:
- Plenty of room for Entertainment Monitors, Status Displays, or Posters in the Arcade, Botany, Kitchen
- Park could use some status displays as well (remember to put both AI displays and Evac displays)
- I always like putting an entertainment display in the bar but that's subjective

**Review by MrMelbert — COMMENTED** [review]
Unconnected bin

image

**Review by MrMelbert — COMMENTED** [review]
Looks like a mail sorting helper which is doing nothing, make sur eyou checked all the new bins have proper mail sorting attached 

image

**Review by MrMelbert — COMMENTED** [review]
Pipe to nowhere 

image

**Review by MrMelbert — COMMENTED** [review]
Old botany mail pipe still there

image

Also what I believe to be the botany navigation landmark is there, make sure the nav landmarks are moved and updated

**Comment by GremlinSeeker** [comment]
image

Updated picture that should be a lil more accurate now.

**Review by MrMelbert — COMMENTED** [review]
Don't forget to move nav landmarks. This looks like botany's

image

**Review by MrMelbert — COMMENTED** [review]
Stacking wallmounts like this should be avoided 

image

**Review by MrMelbert — COMMENTED** [review]
These are supposed to be wall mounted 😅 

image

**Comment by GremlinSeeker** [comment]
> These are supposed to be wall mounted 😅
> 
> image

I dunno I honestly kinda liked how it looked, but I can put it on the wall. I don't think it ruins the functionality does it?

I also completely forgot about the nav markers, I'll get it done.

**Comment by GremlinSeeker** [comment]
image

Alright, broke some stuff ended up taking forever to fix it. I think I fixed most things, added a few more decals here and there. I spiced up the service hall a tad more. If I'm missing anything else let me know.

**Comment by GremlinSeeker** [comment]
Added firelocks to the chapels, forgot to add that in some changes that I made

**Review by MrMelbert — CHANGES_REQUESTED** [review]
1.

Maintenance areas should include all of their walls

You can see here these maint areas have some walls, but not all. 

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
2.

No APC, no air alarm in the kitchen coldroom

In fact you marked it as atmos sanity ignore, that's improper, it should have ventilation (and an APC / air alarm at the very least)

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
3.

Poster covering apc

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
4.

These two maint doors don't have public access helpers for their in -> out side, look at other maint doors on the map for an example

image

(Same here)

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
5.

Why is this disposal run so weird? You could just go straight to the right

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
6.

You made these delivery flaps for botany and the bar, but you didn't place any nav beacons beneath them, so MULEs can't actually deliver there. Intentional, and if so, why? If not, perhaps replace them with maint door access. Getting into maint from the bar or botany would be handy (radstorms, etc)

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
7.

More of a nitpick, but this decal doesn't make much sense logically - it implies they *cut a hole* out of the carpet to put the computer there which is silly

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
8.

Disposal network is all fudged up here

But to that end, you should make some of these pipe mail pipes. So people can ship directly to those departments. 

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
9.

I guess slightly nitpicky since I'm a botany player but this setup is very, very claustrophobic for botany. 

I would remove some trays and maybe re-arrange it. (12 or so trays maybe.) Those corner trays, while theoretically accessible, are not very accessible gameplay-wise. 

Also I still think the public facing seed extractor is silly. It should be a fridge.

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
10.

I don't think this air alarm is accessible as per my previous review

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
11.

No chef order console

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
12. 

These corners in the vault = mapping sin

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
13.

(Nitpicks)
- Maint doors on birdshot don't have tiles underneath, they have plating.

image

- Random pipes

image

- Still no newscaster in the library is a massive shame IMO

- You can rotate the shutters in the kitchen and comissary to match the direction of the tables, looks nicer to me (IMO) (some people disagree with me)

- Give the botany and kitchen request consoles the "supplies request-able" helper.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
14.

Rather than mapping in `/obj/structure/steam_vent` prefer to map in `/obj/effect/spawner/random/structure/steam_vent`

image

**Review by MrMelbert — CHANGES_REQUESTED** [review]
15.

The "private" and "secure" paintings are not very private, nor secure. 

Private should be in the backroom, secure should be behind some locked case. 

Also: They're not pixel offset, you placed them directly on the wall. They should be besides the wall and offset onto it. 

image

**Pull request closed without merging**
