### PR TITLE
Theatre Access for Chaplain

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
To expand his range of gimmicks

### CODE REVIEW

**Comment by GunHog** [comment]
:+1: Nice

**Comment by Zilenan91** [comment]
:+1:

**Comment by Alek2ander** [comment]
In return give clown access to crematorium. I'm sure _nothing_ can go wrong.

**Comment by Anonmare** [comment]
Time to form the religion of catgirl schoolgirls

**Comment by xxalpha** [comment]
No?

**Comment by Dorsisdwarf** [comment]
:-1:

**Comment by octareenroon91** [comment]
Clown running the confessional could be funny.

**Pull request merged**
