### PR TITLE
Command Report Obfuscation

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
tweak: The current mode now only has a 65% of appearing in the Command Report, down from 100%. 
fix: The Command Report should now properly discount the chance of "non-standard" modes appearing in the report.
/:cl:

Note: Haven't tested this, still not quite sure why if(M.probability) wasn't ever returning true, hopefully this will. The result was that every mode was weighted equally for false reporting so we saw reports filled with shit likes Devils, Devil Agents, Internal Affairs, etc. as often as actual modes.

### CODE REVIEW

**Comment by praisenarsie** [comment]
>removing features

**Comment by awesine** [comment]
i ded

**Comment by coiax** [comment]
Why not just list every possible mode under current population, and call it a day?

**Comment by awesine** [comment]
@coiax 
then why even have this feature in the first place
it exists to give you a *hint* as what the gamemode is

**Comment by Shapsy** [comment]
It hasn't been a feature in the entire history of the codebase up until a few months ago, and it should go back to being benign

In fact, in ye olden days of earlier this year there was a prompt on the report telling the captain not to go reading the classified information out for everyone to read, which made sense

**Comment by kevinz000** [comment]
Oh screw off robustin do it properly don't cover your fuckup with a nerf.

**Comment by Robustin** [comment]
Because in hindsight even fixing the bug won't solve the problem.

I don't think it's healthy to let people meta the gametype. Knowing with 100% certainty that there won't be Nukeops or some other antag type reduces the possibility for intrigue in the round.

What's the point of having so many items to bait other modes if the Captain can just go "lol no Nukeops aren't on the command report, try again". 

This method means the report still has a modest significance (a mode appearing on the report means its more likely to be true) but it removes the stupidity of giving the crew a 100% accurate list of which opponents they WON'T be facing.

**Comment by kevinz000** [comment]
holy shit if i have to do this myself i'm going to be pissed.

**Comment by jughu** [comment]
Its easy to meta shit by just playing its called common sense and time periods

**Comment by Robustin** [comment]
Kev's idea: "Add a clause that it might be wrong."

Me: Adds a line that means it might be wrong

Kev playing 4d shitpost chess: "I'll just scream incoherently about how awful Robustin is"

**Comment by coiax** [comment]
> Why not just list every possible mode under current population, and call it a day?

**Comment by Bawhoppen** [comment]
Dumb and also stop thumbsupping your own PR

**Comment by jughu** [comment]
Why not make it automatically pull the gamemodes from rotation and state them so if we ever remove a gamemode it wouldnt state it!

**Comment by Bawhoppen** [comment]
In case an admin forces the event so it won't be obvious (or wrong) when it states what it has

**Comment by ShizCalev** [comment]
> Haven't tested this

**Comment by Robustin** [comment]
The probability part is a no-brainer but the "fix" part applies to non-functioning code so worst case is it continues to not work.

**Comment by ExcessiveUseOfCobblestone** [comment]
Lets try 0 next since we still haven't came to the conclusion a guaranteed round-start """"""hint"""""" people use to guess the entire conflict of the round is bad.

@awesine it's fluff for a roleplaying game.

**Comment by lordpidey** [comment]
While I agree we should fix it so that false report weight for disabled gamemodes is set to 1, the 65% probability is a bit low.  Perhaps set that to 95%?

**Comment by jughu** [comment]
Tbh just say fuck it put all gamemodes in existance on it no randomization just a genea explanation of gamemodes etc etc its secret anyways so you wont know the gamemode and you wont base it off a paper if the modes are started at roundstart anyways

**Comment by lordpidey** [comment]
@jughu sometimes paranoia is greater if you have an idea of what to look for rather than "lul, literally anything"

**Comment by ShizCalev** [comment]
image

**Pull request closed without merging**
