### PR TITLE
Revert "Revert "Adds a note to maintainer guidelines""

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#60739

# 24 HOUR RULE VIOLATED

# ~~SELF MERGE RULE VIOLATED~~

# IT ENDS HERE

https://user-images.githubusercontent.com/4081722/128577993-03ef8f0e-7edf-4506-b679-344dc35882b2.mp4

### CODE REVIEW

**Comment by tralezab** [comment]
MSO is my boss!

**Comment by Iamgoofball** [comment]
i do not accept this false headcoder

**Comment by Time-Green** [comment]
> i do not accept this false headcoder

No one does and he’s not the new headcoder. He just said so and gave himself a discord role. Cyberboss already stripped him of write acces following his gross abuse

**Comment by Iamgoofball** [comment]
god bless

**Pull request closed without merging**
