### PR TITLE
Air alarm refactor

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl:
tweak: Air alarms in the same area now share configuration
/:cl:

TODO:

- [ ] Move more shared functions to the area datum
- [ ] Move vents and scrubbers to the area datum

### CODE REVIEW

**Comment by nichlas0010** [comment]
do they still detect air mixture based on the tile they're on, or is it area based?

**Comment by Jalleo** [comment]
Uh unless I am mistaken arent certain setups possible by having individual configuration?
Such as a burn chamber monitoring with a alarm if the temperature goes down to x level and so forth?

**Comment by Cyberboss** [comment]
I still need to decouple the sensing from the alarms themselves. Was
planning on doing it in a later PR but I guess I'll do it here

**Comment by Jalleo** [comment]
Nah do it in a seperate PR. Its fine.

**Comment by zxaber** [comment]
While we're discussing an Air Alarm wishlist, a change that would stop the lower half of the interface bouncing up and down as the air alarm adds and removes "Pluoxium: NaN%" would be nice.

**Comment by SpaceManiac** [comment]
Stale

**Comment by DaxDupont** [comment]
is cyberboss dead

**Pull request closed without merging**
