### PR TITLE
Revert "Removes i did not grief them (#28879)"

### PR DESCRIPTION
**Pull request by Wilchenx**
Was actually a nice song.

For people who don't remember which one was it
https://www.youtube.com/watch?v=NZfox7y8VAg

### CODE REVIEW

**Comment by msgerbs** [comment]
Where did you even find this commit lol?

**Comment by fludd12** [comment]
I didn't even realize the song was from The Room, I just came to associate it with tg.

**Comment by optimumtact** [comment]
You're just a little chicken, cheep cheep

**Comment by praisenarsie** [comment]
we're lacking songs and this was a good one anyway.

**Comment by Armhulen** [comment]
I really enjoyed this one

**Comment by AnonymousNow** [comment]
[It hung around a long time after some of the most SS13 music there is was removed, for some godawful reason. Re-add the space folk.](https://www.youtube.com/watch?v=wJzPhRJRgFA)

**Comment by Bawhoppen** [comment]
This is one meme that we do not need back

**Comment by Mark9013100** [comment]
I did naht hit her, I did naht.

**Comment by Qbopper** [comment]
how long was this on the server? I remember it but I don't know when it got removed

**Comment by ShizCalev** [comment]
@Qbopper 7 months, 26 days

**Comment by AnturK** [comment]
The whole point of a server side system is so we don't need PR's like these. Ask headmins or MSO to include the music you want in lobby.

Any maintainer that disagrees can reopen this.

**Pull request closed without merging**
