### PR TITLE
Makes blood contract work only for people inside of your view range.

### PR DESCRIPTION
**Pull request by evsey9**
:cl: Evsey9
balance: Blood Contract now only works on people that are inside of your view range.
/:cl:
I would prefer removing this item outright, but this at least makes it more sane.
This item, in it's current state, allows you to metagame the roundtype and also possible fuck over that roundtype. This item makes it incredibly easy to fuck over anyone and pit the entire station against them, whenever you want to, from wherever you want to. Gated behind PvE that could be done in a few minutes after roundstart.

Now this fixes the metagaming issue and the issue where you could pit the entirety of station on someone from whenever you wanted to.

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
how about z-level only instead of making the item useless

**Comment by evsey9** [comment]
get in viewrange of person you want to kill -> pull out contract -> use on them -> run away
how does this make it useless, again?

**Comment by GhostEcho** [comment]
Why not just restrict it so xenos, blob, etc dont show up on the list rather than make it trash?

**Comment by Kromgar** [comment]
Im sorry but xenos with chainsaws is the greatest thing to have ever existed

**Comment by imsxz** [comment]
Make blood contract instead require you to type in the real name of your target instead of a list of names

**Comment by evsey9** [comment]
I'd do that, but how would it work with people that have the same name? Example: changelings.

**Comment by Repukan** [comment]
Thrash change for thrash reasons.

**Comment by evsey9** [comment]
So being able to metagame the roundtype is bad?

**Comment by Kagus** [comment]
> So being able to metagame the roundtype is a trash reason?

No, he clearly said it's a _thrash_ reason, meaning something Slayer would sing about.

---
As for the fix, I'm not really digging the LOS restriction. The true name alternative does sound more appealing, but then you have the issue of changelings/mutation toxins making things difficult, or potentially trying to target someone who's already dead (although this could probably be fixed by just checking to see if the target is, y'know, deceased).

Considering the contract comes from a demon and demons are obsessed with true names, I'd say that having to discover the true name of your target and then write it in seems like the more thematic option. And as we all know, SS13 is primarily about the lore.

**Pull request closed without merging**
