### PR TITLE
Makes meth actually blue because Goofball is useless and won't do it

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

actually finishes the shitpost https://github.com/tgstation/tgstation/pull/71926

Meth becomes bluer depending on purity.
100% purity meth is rgb(135, 200, 250)
50% purity (lowest meth can EVER go) meth is rgb(250, 250, 250)

## Why It's Good For The Game

[chemist.webm](https://user-images.githubusercontent.com/82850673/209492369-bd89d780-83d9-41c9-ba53-32ad5416cdab.webm)

## Changelog

:cl:
add: Meth becomes bluer the higher the purity
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
Why not just use `BlendRGB()`?

**Comment by ChungusGamer666** [comment]
> Why not just use `BlendRGB()`?



> Why not just use `BlendRGB()`?

good question what the hell is wrong with me

**Comment by ChungusGamer666** [comment]
shit i need to use initial() fuck dont merge this

**Comment by saprasam** [comment]
isn't pure meth a colour more similar to white
this is a stupid question, this is a funny ss13 game. go nuts

**Comment by Pumpkinoe** [comment]
> isn't pure meth a colour more similar to white this is a stupid question, this is a funny ss13 game. go nuts

(he hasn't seen hit netflix series Breaking Bad)

**Comment by ChungusGamer666** [comment]
test failures are not my fucking fault

**Pull request merged**
