### PR TITLE
Boxstation Piping Redone in Layers 1/3

### PR DESCRIPTION
**Pull request by Helianthus00**
## About The Pull Request

Replaces all of the messy piping on box with layer1/3 pipes, reserving layer 2 for miscellaneous work and power lines. The general piping layout was conserved, including the standalone virology and cargo bay/locker room/common mining area pressurized air tanks. The vent/scrubber positions were also conserved, in most cases. Some were moved slightly, but now there are none under any furniture, which is a big improvement as well. There were also a few odd pipes, especially in medbay, where they didn't connect to anything or there were dead ends. All areas of the map are now connected to the air supply and scrubbers system, as intended.  Here is an image of the map, hiding most objects and things so the piping can be seen far easier. The missing vent in the maint bar has been corrected after the image was generated.
box_pipes_full

## Why It's Good For The Game

A more organized pipe system makes atmos maintenance (and sabotage) much easier. These pipes no longer need to run through walls in the majority of cases. Using layer 1 and 3 make it easier to see both sets of pipes, as well as cable if they are in the same spot. Plus it just looks much nicer overall.

## Changelog
:cl:
fix: Fixed the air supply and scrubber pipes to be more neat, as well as fixing a few displaced vents in medbay
del: removed the double cable on one of the AI upload doors.
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
Changelogs should be from the player's side. Players have no idea what "image of the station stripped of most objects, so the pipes can be evaluated easier" means, since it's not related with what the PR does, but with the description. Remove it and we gucchi.

**Comment by Helianthus00** [comment]
Oh I see. Sorry, this is my first real pull request, and I'm not so good at anything besides map work. Removed that from the changelog.

**Comment by TerraGS** [comment]
Is this up to date with the AI/grav gen relocation?

**Comment by Helianthus00** [comment]
No it isn't. How irritating. I swear I pulled to my clone before I started, but I guess I used the wrong file or something. At this point, it'll be quicker to just recreate the changes onto my map, so I'll work on that now.

**Comment by LemonInTheDark** [comment]
If possible layers 1 and 3 should be left exclusively for atmos fucking about. I know delta and a few other maps violate this idea tho. Is there anything else you could do with this?

**Comment by Helianthus00** [comment]
> 
> 
> If possible layers 1 and 3 should be left exclusively for atmos fucking about. I know delta and a few other maps violate this idea tho. Is there anything else you could do with this?

I'm not exactly sure what you mean. Do you mean that it's a bad idea to put the air supply/scrubbers on those layers or that all stations should have it that way? If you meant to convert the other stations too, I plan on eventually doing so, it just took a long time to do it for box (about 6-7 hours or so), so it might be a while before I get around to it. 

Also, I finished the edits to make the station more current hours ago, I'm just having to wrestle with git to actually get them on here. Hopefully, they'll be here soon though.

**Comment by LemonInTheDark** [comment]
Ah sorry for being unclear.

I think stations shouldn't use layer 1 or 3 for piping, instead leaving those open for atmospherics playing. 

I brought up delta because I recall a particularly gruesome instance in the engine room that severely limits messing about

**Comment by Helianthus00** [comment]
@LemonInTheDark I see, there can be issues with using the other layers, but I honestly can't stand the current state of the air/scrubber pipes on box. There is still a good bit of area on the station where there are no pipes either. Plus, using these layers means that pipes take up much less surface area overall, leaving more space that is available to all three layers.  It's definitely a trade off, but having pipes that are easier to access is preferable, in my opinion.

**Comment by LemonInTheDark** [comment]
I can understand that. Would it be possible to keep atmos/the engine room on layer 2? I'd like to give as much freedom to players to mess about and learn there

**Comment by Helianthus00** [comment]
@LemonInTheDark What about this? Still using layers 1/3, but I rerouted everything to be along the edge of the room. I think that leaves a nice amount of area for messing around with stuff. Also, these pipes are hidden, so they'll be under floor tiles.
box_pipes_atmos

**Comment by Helianthus00** [comment]
Finally managed to figure out the git issues. Here is the latest version of the map, with all the new map alterations, as well as the atmos room changes.

**Comment by LemonInTheDark** [comment]
That's great, thanks a whole ton. Could you do the same for the engine room?

**Comment by Helianthus00** [comment]
@LemonInTheDark There was much less room for improvement in the engine room, but I tried my best. 
engine room

**Comment by LemonInTheDark** [comment]
That is so much better. sorry for being a bit nitpicky, you're doin good work

**Comment by spookydonut** [comment]
having cables and pipes in engine/atmos both on layer 2 looks yucky

**Comment by Helianthus00** [comment]
@LemonInTheDark No worries. I'd rather people nitpick in the pr when I can still easily change something than later when I (or someone else) would have to make a whole new pr over it.

@spookydonut I don't disagree, but I didn't want to optimize anything too much, just fixing all of the pipes in the walls around the station. Plus I'm no SM or atmos expert, so I wouldn't want to mess something up.

**Comment by LemonInTheDark** [comment]
You could have the first proper use of cable bridges ever

**Comment by Helianthus00** [comment]
@LemonInTheDark The issue that I can see with that, is that the multi-layer cables are much harder to lay, and changing that in the SM might lead to catastrophic errors if it isn't able to be fixed quickly. However, I did move the layer 2 cables in the atmos room to be around the edges of the room with the other pipes.

**Comment by spookydonut** [comment]
Good enough I guess

**Comment by WarlockD** [comment]
Love it.

**Pull request merged**
