### PR TITLE
Temporarily disables revenants

### PR DESCRIPTION
**Pull request by ghost**
I enjoyed creating revenant, but there's a lot of issues and I can't find the time to deal with them. They've caused too much trouble and for now I'd rather they be disabled for the time being so when I have some spare time I can work on them.

### CODE REVIEW

**Comment by RemieRichards** [comment]
could just comment out the random event.

**Comment by Xhuis** [comment]
I decided on revenants themselves since they've caused a lot of issues.

**Comment by RemieRichards** [comment]
w/e

**Comment by AlexCrimson** [comment]
A damn shame, but if they are not working as you intended, then it cant be helped. Looking forward to seeing how you fix them, if you ever decide to.

**Comment by Fox-McCloud** [comment]
very damn shame; this had real potential.

**Comment by Xhuis** [comment]
has*
It's not being killed off!

**Comment by Memendia** [comment]
We still got it active here on Atlas ^_^ 

Even with all it's buggies it's still hilariously fun

**Comment by Cheridan** [comment]
I think it'd be better for the event to be commented out too. Admins can at least spawn them and they'll probably be more likely to get fixed by someone as opposed to "out of sight out of mind"

**Comment by JJRcop** [comment]
Yeah, if you completely disable the revenant then nobody will know it's there

**Comment by Xhuis** [comment]
rip in pease sweet prinse

**Comment by AlexCrimson** [comment]
Got to play Revenant one last time yesterday and made the HoS kill innocents by whispering him that they were "evil". It was fun until an admin got involved RIP.

Also probably not important at this point, but i couldnt unlock overload lights even when i had 70+ essence.

**Pull request merged**
