### PR TITLE
Cult: Counterplay Edition

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Combined the Convert and Sacrifice runes into one rune. It'll convert targets that are alive and eligible, and attempt to sacrifice them otherwise. The only changes to mechanics are that: Converting someone will heal them of all brute and burn damage they had, and sacrificing anything will always produce a soulstone(but will still only sometimes fill it)
tweak: You can no longer teleport to Teleport runes that have dense objects on top of them.
experiment: Wall runes will now activate other nearby wall runes when activated, but will automatically disable after a minute and a half of continuous activity and become unusable for 5 seconds.
experiment: The Blood Boil rune no longer does all of its damage instantly or stuns, but if you remain in range for the full duration you will be sent deep into critical.
/:cl:

The general idea is to give runes at least basic counterplay; stick a fueltank on a teleport rune, wait a wall rune out, run from an active blood boil rune, etc.

And, for usability, merging the convert and sac runes like this means less rune fiddling and more shoving people on the rune.

### CODE REVIEW

**Comment by Supermichael777** [comment]
no moar conversion free construct cults

**Comment by GunHog** [comment]
You can still have PokéCult, you just have to kill your captures first! Thanks to the healing mechanic being added, _Crit becomes the most effective stun_! Beat someone to crit with your weapon, drag him to the rune and convert!

**Comment by PKPenguin321** [comment]
Implying they wont succumb

**Comment by Supermichael777** [comment]
anyway looks like some convert runes are on the shuttles

**Comment by Tacolizard** [comment]
does this mean that if you try to convert an implanted crewmember then they'll get autosac'd?

**Comment by ChangelingRain** [comment]
If you have three people around the rune, yes.

**Comment by KorPhaeron** [comment]
Blocking runes still seems a bit less intuitive than how you deal with every other mess in the game.

It's the kind of thing you read on the wiki instead of try naturally

**Comment by ChangelingRain** [comment]
It's only less intuitive if like every other teleport in the game drops you on top of solid turfs with wild abandon(most do)

**Comment by Shadowlight213** [comment]
Why heal people to full on conversion though?

**Comment by KingPhilipIII** [comment]
Because it makes sense that a cult that uses their own blood would have no issues beating the shit out of potential members and dragging the mangled body for their rituals.

**Comment by ChangelingRain** [comment]
Not only that, it's a good gameplay thing; you can more freely crit people and shove them onto a rune without having to worry about how you're going to heal them.

**Comment by KingPhilipIII** [comment]
Not a fan of timed wall runes, because now my primary use for them is gone. Locking the door into my cult base. Like the rest though.

**Comment by ChangelingRain** [comment]
Yeah timed wall runes are iffy, but if they're not timed they're basically impossible to deal with because only the chaplain or holy water can actually get rid of them.

**Comment by KingPhilipIII** [comment]
There is always the option of going around them. Most cultists only place one, in the doorway. Any more is inefficient with space, time and blood. Nobody thinks decon the wall next to it.

**Comment by ChangelingRain** [comment]
Yeeeeah that only works if cultists don't spam 50 goddamn wall runes, given that the cost for each rune is 0.1 + 2 * number of times toggled brute, which is very easily healed off with pylons..

**Comment by KingPhilipIII** [comment]
How many cults actually build pylons lately? I haven't seen one in a long time.  And most bases are built in fairly cramped rooms in maintenence or in departments. Drawing enough wall runes isn't usually feasible in terms of space.

**Pull request merged**
