### PR TITLE
Adds a new changeling chemical, which can cure a majority of traumas, to Anatomic Panacea.

### LINKED ISSUE #44067: Anatomic Panacea repairs brain damage but has no effect on traumas
I feel like this is an oversight just because changelings have remained mostly unchanged since the trauma system started to gain traction, and it feels just a little bit unusual that changelings (who are meant to be masters of biology capable of purging toxins and repairing physical, or even genomic defects basically at will) can get bonked on the head/irradiated/poisoned in a way that renders them permanently damaged unless someone goes and pokes their literally-vestigial brain in the correct way.

I'm wondering what the most elegant solution to this is, and whether changelings should remain brainwashable as well (which is lumped in with the things that are cured by brain surgery). If this is all important to feature balance I guess it can be left alone, though.

### PR DESCRIPTION
**Pull request by Firecage**
## About The Pull Request
This PR adds a new changeling chemical, called Changeling Panacea, which can cure all traumas up to lobotomy-level, but does not work on neither magical nor permanent traumas(tiers 4 and 5 respectively). Since this is also a rather strong chemical, its can_synth has be set to FALSE. Would not be ideal of botany gets it via RNG.

Naturally, this chemical is also added to the changeling power of Anatomic Panacea so changelings actually has a way to cure the actually curable variety of traumas without either having to go get neurine, brain surgery, or a lobotomy, none of which would make much sense for an alien capable of near-perfect biological manipulation down to the cellular level.

Fixes #44067 

## Why It's Good For The Game
As stated above. Currently changelings, to cure one of the curable varieties of traumas, either has to drink neurine, undergo brain surgery, or get a lobotomy. Which is not to sensible for what they are, and because they can already heal their brain of actual physical damage.

## Changelog
:cl:
fix: Changelings are now able to cure themselves of most traumas via Anatomic Panacea, except magical and permanent traumas.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Why not just move all the effects of the chems you get from the ability to this chem?

**Comment by MCterra10** [comment]
ANTAG FREEZE REEEEE

**Comment by PKPenguin321** [comment]
This is a fix? Thought those were fine

**Comment by optimumtact** [comment]
`This PR adds a new changeling chemical, called Changeling Panacea`

**Comment by PKPenguin321** [comment]
This shouldn't even use a chem, just put this code into the ability itself so we can close the issue

**Comment by Firecage** [comment]
I....didn't actually think about doing that at all.

**Comment by Firecage** [comment]
@PKPenguin321 Will prob have to wait until after Antagfreeze anyway. Considering while it would be a fix, it technically wouldn't be a bugfix, and would technically be an antag buff anyway.

**Comment by PKPenguin321** [comment]
Either way, this issue will need to be fixed after the freeze, so you may as well get the code done now while you've got the ball rolling

**Comment by Firecage** [comment]
Oh, I already have the code done and it works as far as I can see.

**Comment by ExcessiveUseOfCobblestone** [comment]
to clarify

> True Bug Fix : OK
Elevating bugfix into new feature: Need Approval

**Comment by PKPenguin321** [comment]
I think this would qualify as the first thing if it was baked into the ability instead of being a chem

**Comment by itseasytosee** [comment]
Antag freeze is dead bring this back

**Comment by trollbreeder** [comment]
Cobby is cute and likes to reopen closed PRs

**Comment by ExcessiveUseOfCobblestone** [comment]
@trollbreeder branch was deleted but you can just replicate it 😏

**Pull request closed without merging**
