### PR TITLE
Fully Immersing someone now reminds them to roleplay correctly

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Please roleplay correctly!

## Why It's Good For The Game

They will now roleplay correctly

## Changelog

:cl:
expansion: Admin fully immerse smite now reminds the victim to roleplay correctly
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
Make them want piss and shit for full immersion

**Comment by AndroidMK2** [comment]
Roleplay on low rp server.  ._.

**Comment by tralezab** [comment]
> Roleplay on low rp server. ._.

**Comment by Mothblocks** [comment]
low rp is not no rp

**Review by Mothblocks — APPROVED** [review]

**Comment by DrDiasyl** [comment]
> low rp is not no rp

Wise words

**Pull request merged**
