### PR TITLE
Actually fixes broken accesses

### PR DESCRIPTION
**Pull request by ShizCalev**
Closes #35513

Originally tried to fix these in #35234. Didn't realize DMMs don't support number values in lists (they're always converted to text), so they went from being all-access (because they were broken from the start) to no access since it was trying to compare nums to text.

### CODE REVIEW

**Comment by 81Denton** [comment]
That explains a lot, I had no clue why lists didn't work.

**Comment by SpaceManiac** [comment]
> don't support number values in lists

Is this an issue with DreamMaker/BYOND or our map loader?

**Comment by ShizCalev** [comment]
@SpaceManiac Not quite sure

**Comment by ShizCalev** [comment]
might be our maploader. https://github.com/tgstation/tgstation/blob/cb200e15477b4c81edd686a31cdfdb352fab5b13/code/modules/mapping/reader.dm#L391

**Comment by Jordie0608** [comment]
`req_access = list(` was used back in the days of yore and I don't believe any change was made to map parsing lists, so it'd be the maploader.

**Comment by Cyberboss** [comment]
So is this good to go or what?

**Comment by ShizCalev** [comment]
This is good unless someone feels like fixing the maploader to support it.

**Comment by Cyberboss** [comment]
>Fixing the maploader

HA

**Pull request merged**
