### PR TITLE
Fixes a runtime in NTNet scanner

### PR DESCRIPTION
**Pull request by ACCount12**
NTNet scanner runtimed on null input, this corrects it. Also corrects capitalization: "NTnet" -> "NTNet".

### CODE REVIEW

**Comment by arsserpentarium** [comment]
Please, make subtype with old name to provide reverse compatiblity of blueprints.

**Comment by ACCount12** [comment]
It's literally one "Find/Replace" run on any affected blueprint.

**Comment by arsserpentarium** [comment]
But you need to follow github to check for all typo fixes. 
Or make more extended sanity check,which gives you list of conflicting parts.

**Comment by arsserpentarium** [comment]
With override cloning mode. Which try to print everything what prints and just ignoring incorrect commands.

**Comment by ACCount12** [comment]
Good idea by the way. I'll do it next time I'll touch save/load system.

**Comment by arsserpentarium** [comment]
but for now, use subtype

**Comment by arsserpentarium** [comment]
@ShizCalev Why are you counting usability less important, than grammar?

**Pull request merged**
