### PR TITLE
Adds the new "E.X.P.E.R.I-MENTOR" research machine.

### PR DESCRIPTION
**Pull request by sawu-tg**
An alternate research option.

*Built with 1 scanning module, 2 manipulators and 2 micro lasers.
*Manipulators affect the reset speed, lasers affect it's chance to have bad things happen.
*Heavily RNG based to be the "fun" alternative.
*Includes features such as causing spacial distortions, transforming things into other things, and setting your face on fire.
*Can be built, but currently not included on the map.

The process of the EXPERI-MENTOR works as such:
1. Build it/walk up to it and click the "Scan for R&D Console" button if it is there.
2. Insert anything, literally anything.
3. The user uses a process of elimination to guess what the correct use for the item is ("Poke", "Irradiate", "Gas", "Heat", "Cold" or "Obliterate")
4. A correct guess results in addition of research points and (potentially) a randomised thing happening (reduced with upgrades). A failed results in a fluff message.

Current "use" RND events are:
Poke
*Destroy item, hit mobs in oview(1) for 15 brute
*Destroy item, proceeding to Obliterate
*Eject the item, throwing it at a random target in oview(7)
Irradiate
*Destroy item, apply 25 IRRADIATE to oview(1)
*In oview(1), spawn goo in oview(1)
*Transform item into something from valid_items list and eject it (primes grenades first)
Gas
*Destroy item, spawn toxic gas cloud
*Spawn harmless gas cloud
*Destroy item, Empulse(8,10)
Heat
*Destroy item, explosion(-1,0,0,0,0,flame_range = 2) (sets a small fire)
*Destroy item, heat up turf
*Eject item, spawn smoke, hit mobs for 5 burn in oview(1)
Cold
*Destroy item, release frostoil smoke
*Destroy item, cool down turf
*Eject item, spawn smoke
Obliterate
(by default, this will transfer m_amount and g_amount to a linked lathe)
(I'm aware that both of these are kind of "one item at a time", but I like the effect and left it that way)
*Destroy item, pull all mobs and items in oview(7) towards src
*Destroy item, throw all mob and items in oview(7) at other mobs and items

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@sawu-tg is on a roll

i love it

**Comment by Anonus** [comment]
Best R&D replacement so far.

**Comment by ike709** [comment]
time to praise and worship the RNG gods

**Comment by Razharas** [comment]
Interesting

**Comment by Nienhaus** [comment]
:+1: x :100:

**Comment by tkdrg** [comment]
This looks really fun. Looking forward to playing around with it.

**Comment by paprka** [comment]
This should just replace the DA if you're adding it, right now it's completely inferior

**Comment by pudl** [comment]
what can research points get you?

**Comment by AlexanderUlanH** [comment]
I like the idea, but it doesn't seem like it adds much to RnD.  Most of the things you deconstruct aren't things you'll really care about, so the possibility of keeping the items you're deconning isn't going to be a huge advantage.
It seems like the only real use for it would be to go irradiate and roll for spellbook.

**Comment by YotaXP** [comment]
So can I research everything using paper and bedsheets?

**Comment by sawu-tg** [comment]
@pudl Research points are the normal ones you would gain from the desconstructive analzyer, it's arguable easier to get them with this (you can keep researching the same item up until it wouldn't give more tech), but more researching leads to more potential mishaps.

@AlexanderUlanH and @YotaXP  I should clarify, while it is set up to deconstruct anything, it will only accept things with tech origins, so if someone added a tech_origin to banana, then that would work too. Additionally, spellbooks aren't in the valid table (as far as I can tell), so it won't be transformed to them.

The valid table consists of hand selected type-paths that I considered to be not entirely OP or broken, and are as follows:
*/obj/item/weapon/reagent_containers/food
*/obj/item/weapon/stock_parts
*/obj/item/weapon/grenade/chem_grenade
*/obj/item/weapon/kitchen

@paprka  On SawuStation, it replaced the DA, but I didn't want to do a map edit because of the whole freeze thing, that being said though, this could be marginally better than it because you can get (on a chance) multiple points from one object, if you take the risk.

**Comment by AlexanderUlanH** [comment]
Yeah, I noticed those limitations and removed them from that bit from the comment.  Still, it seems too dangerous and inconsistent to be useful, especially when destructolizer research is so easy.

**Comment by sawu-tg** [comment]
@AlexanderUlanH As a replacement, the idea would be to make R&D less of a "grab everything, sweat shop research", as randomisation and events give it a bit of extra work and play. As an extra machine, it gives you the ability to (potentially) get much higher research than the destructor, because it doesn't destroy items (initially).

If it replaced the original destructor, R&D would be more of a multi-person, brain involved task (especially if more events were added), that involved reacting and being prepared, rather than taking two minutes to process everything and you're done.

If it was there as an "extra", people could take a more dangerous, but rewarding path to gain more research from objects (Instead of 2 plasma giving one point, you have the potential to get up to 2 from it), and so fourth.

**Comment by pudl** [comment]
i think you should add an insane amount of events, like 30 more

**Comment by sawu-tg** [comment]
@pudl I was planning on adding more, but the current ones were a "baseline". Mainly because I ran out of ideas for them.

**Comment by Dorsisdwarf** [comment]
Can we propose ideas for events?

**Comment by sawu-tg** [comment]
@Dorsisdwarf , @Ergovisavi is actually reviewing this for merge right now, but if any good ideas for events are suggested (and this gets merged), I can make them at a later date (or someone else can!)

**Comment by Ergovisavi** [comment]
Looks fine at this point, tested and everything appears to work.

**Pull request merged**
