### PR TITLE
New Plant Data Disk Sprite

### PR DESCRIPTION
**Pull request by ghost**
Sprite from Baystation
hydrodisk

:cl:
add: Plant data disks have new sprites.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
Acceptable!

**Comment by ma44** [comment]
That's a uranium disk!

**Comment by Armhulen** [comment]
TAB WHITE REEEE

**Comment by PKPenguin321** [comment]
Muh metabreaker

**Comment by WJohn** [comment]
adequately inoffensive enough, i guess? it doesn't look great but it's not horrible either. whatever. IN YOU GO

**Pull request merged**
