### PR TITLE
Clockcult combat changes

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Removed the Volt Blaster scripture.
rscdel: Ratvarian spears can no longer impale.
balance: Vitality Matrices now require a flat 150 Vitality to revive Servants, from 20 + the Servant's non-oxygen damage. Vitality Matrices are also no longer destroyed when reviving Servants.
balance: Ratvarian spear damage changed from 18 to 20, Ratvarian spears now generate 5 Vitality when attacking living targets. Ratvarian spear armour penetration changed from 0 to 10.
balance: The Judicial Visor's mark now immediately applies Belligerent and knocks down for 0.5 seconds. Mark exploding no longer mutes, mark explosion stun changed from 16 seconds to 1.5 seconds, mark explosion damage changed from 10 to 20.
/:cl:

Volt Blaster was situational, pretty strong in those situations, and unfortunately easy to interrupt.
Vitality Matrices requiring Vitality equal to damage is extremely confusing on a player side since there's no way to tell how much it needs. So, accordingly...
Ratvarian spear impaling... honestly, was a bad idea, since it uses so much power budget that could be used for things with *actual effects*.
Judicial Visors were supposed to be a combat thing, but they were usually too weak, except on stunned enemies, where they were effectively just an instant kill because hey, stun time. And then I gave them a mute for easier conversion and they were still shit for actual combat.

### CODE REVIEW

**Comment by ShizCalev** [comment]
Wouldn't this very explicitly fall under the freeze?

**Comment by Xhuis** [comment]
<pineapples> its not true it was emant to be that overhaul only but I guess the ones opened can be merged since they were made in good faith but no more other than the ones open unless its part of the big change or whatever

As such, this has my approval, but any changes past this can't be accepted, even from me, unfortunately. It'll have to go towards the rework.

**Comment by DoctoreMad** [comment]
I'll be honest with you, I think this PR won't be(and shouldn't be) accepted even with your funny sealnote. This is basically direct combat balance.

**Comment by GuyonBroadway** [comment]
Shame about volt blaster, it was fun to use butvI agree it was situational.

Maybe it could be made into an actual weapon. 

Gets three or so blasts and then you need to charge it up at a sigil or, keeping with the clockwork theme, stand still for a while and wind the key.

**Comment by Tacolizard** [comment]
how do you even generate power in clock cult lol

**Comment by Xhuis** [comment]
Sigil of transmission, either by activating it to nom machines near it or by feeding it brass sheets.

**Comment by BreadBurner** [comment]
Fuck freeze then ?

**Comment by Xhuis** [comment]
Kor has given leeway on the freeze for any clockcult changes before and including this one due to misunderstandings on our part. This is the last change that'll be allowed through the pipeline that isn't explicitly for the rework.

**Comment by Tacolizard** [comment]
how do you get brass sheets lol

**Comment by DoctoreMad** [comment]
Taco please.

**Comment by KorPhaeron** [comment]
What do these words mean

**Pull request merged**
