### PR TITLE
Adds INTJ skillchip

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Adds a new skillchip, it lets you taste food by examining it.
image
This has all of the effects of tasting food (various moodlets based on quality and food type) and can also trigger food allergies if you have them, however it does not consume the food nor give you any nutritional benefit.
You can buy it from a vendor or sometimes it spawns in maintenance.

## Why It's Good For The Game

The players are constantly clamouring for more additions to our most loved and useful feature, skill chips.
<details>

intj

</details>

## Changelog

:cl:
add: A new skill chip can be found in maintenance or purchased from the vendor, allowing you to experience food in new and exciting ways.
add: Abductors also have access to this incredible power, simply using their genius level brains.
/:cl:

### CODE REVIEW

**Review by Fikou — APPROVED** [review]

**Comment by SomeoneYouProbablyKnow** [comment]
Time to powergame my mood by pondering the donut from time to time. very based

**Comment by DaCoolBoss** [comment]
Could abductors start with this?

**Comment by optimumtact** [comment]
Better get this in before they admin jaq and they stop coding.

**Comment by ButterChugger** [comment]
Tried it a few rounds as a plasmaman and ethereal. Doesn't seem to be giving bonuses or negative moodlets.

**Pull request merged**
