### PR TITLE
Improves dufflebag sprites.

### PR DESCRIPTION
**Pull request by WJohn**
They always bothered me by how tiny they looked, so I made them look actually big because they're dufflebags, not fanny packs.

### CODE REVIEW

**Comment by Dawgas** [comment]
bag throwing simulator 2016

**Comment by RemieRichards** [comment]
I actually prefer the current sprites.

**Comment by WJohn** [comment]
The current sprites look like fanny packs. They're tiny!

**Comment by RemieRichards** [comment]
Still look better.

**Comment by Supermichael777** [comment]
with the old sprites 50% of the time you couldn't even tell.

**Comment by PKPenguin321** [comment]
:+1:

**Comment by ChangelingRain** [comment]
Just take the current sprites and make them bigger, these look silly to me.

**Comment by KazeEspada** [comment]
Roundstart duffle bags when

**Comment by Xhuis** [comment]
:+1: x :100:

**Comment by MrSnapwalk** [comment]
Hell, I made the original dufflebag sprites, and I think these are way better. I never was satisfied with how the on-mob sprite looked. :+1:

**Comment by Fox-McCloud** [comment]
This is how you actually wear a dufflebag; you don't wear it horizontally just above your butt; you'd fall over.

**Comment by tkdrg** [comment]
@Cheridan we have a disagreement between the head of sprites and two other maintainers, please solve
:+1: from me for what it's worth

**Comment by Iamgoofball** [comment]
:+1: this is how the real world does dufflebags

**Comment by Cheridan** [comment]
i like em

small dufflebags do exist though so the old sprites could still find some use somewhere

**Comment by Fox-McCloud** [comment]
I was going to say; if you look up large duffle bags and how they're worn; it's literally exactly like picture in the original post.

**Pull request merged**
