### PR TITLE
Adds the semi-recent headcoder ruling that issue managers cannot edit PR labels

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

I found this out while reading through the contributing file today and thought I should change it before goof uses it as an excuse to label a ton of PRs again.
For those unaware: https://github.com/orgs/tgstation/teams/issue-managers/discussions/10

## Why It's Good For The Game

github thing, not a game one.

## Changelog

Not needed.

### CODE REVIEW

**Comment by Jordie0608** [comment]
Headmin oranges?

**Comment by JohnFulpWillard** [comment]
> Headmin oranges?

They’re MY headmin

**Comment by optimumtact** [comment]
so true

**Comment by JohnFulpWillard** [comment]
oops

**Pull request merged**
