### PR TITLE
Patches frying oil splashing not accounting mobs' impermeability.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Reagents' TOUCH reactions are very stupid game design wise and do not account impermeability by default unlike VAPOR, yet both are pretty much interchangeably used. 
But not going to fix it today and debate how features and gameplay mechanics branched off this crooked fallacy should be adjusted. So forgive me for lines 134 and 135.

Nevertheless this should stop splashed frying oil from bypassing bio impermeability and thus every sort of protection. Plus message spam reduction.
Also slighty raised the damage cap of sizzling cooking oil to partially counter the mild bio protection gained from the average crewmember's attire.

## Why It's Good For The Game
I have used the pneumatic cannon deepfrying meme before, it requires some time and welding spamclicking, but it's pretty much a victory against anyone if the shots hit. 

## Changelog
:cl:
fix: Fixes splashed cooking oil bypassing any sort of mob impermeability. Also cut off message/sound spam from being repeatedly splashed within a minimal delay.
balance: Upped the cooking oil damage cap from 35 to 38 to account the mild bio protection of the average crewmember's attire. Also made hot deep fryer swirlies account the user's head covering gear's impermeability.
refactor: Standarized monkeys/humans get_permeability_coefficient().
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
They ignore impermeability because they're technically supposed to be used by patches, which go through stuff.

Also, hilariously enough, smoke is TOUCH and foam is VAPOR, even though foam would coat and smoke would vaporize.

**Comment by Ghommie** [comment]
> 
> 
> They ignore impermeability because they're technically supposed to be used by patches, which go through stuff.

Could be patched up by adding an additional arg to reagents/proc/reaction() and tweaking reagent/proc/reaction_mob(), It's pretty much the rest that discourage me right now.

> 
> Also, hilariously enough, smoke is TOUCH and foam is VAPOR, even though foam would coat and smoke would vaporize.

This. Really.

**Comment by optimumtact** [comment]
really there should be a PATCH type if it's functionality is so different from touch

**Comment by Ghommie** [comment]
> 
> 
> really there should be a PATCH type if it's functionality is so different from touch

I'll get

**Comment by ATH1909** [comment]
Don't forget to make dunking someone's face in a vat of cooking oil check for impermeability as well.

**Pull request merged**
