### PR TITLE
Revert "The Defib Nerf (Defibs are no longer a 10 second paralyze) (#…

### PR DESCRIPTION
**Pull request by optimumtact**
image

### CODE REVIEW

**Comment by carlarctg** [comment]
what?
that was a joke

**Comment by optimumtact** [comment]
im going to eat your shoes

**Comment by carlarctg** [comment]
😭

**Comment by MCterra10** [comment]
oh my god this is epic

**Comment by PKPenguin321** [comment]
i dont get it

**Comment by MCterra10** [comment]
@PKPenguin321 after this was merged on tg and austation's mirror bot copied it over, carlactg commented on the mirrored PR saying "bad pr, don't merge this", I sent a screenshot to orang and he made this meme PR

**Comment by optimumtact** [comment]
terrifying

**Comment by PKPenguin321** [comment]
scared?

**Comment by wesoda25** [comment]
When you were tiding
I studied The Baton
When you were having premarital ERP
I mastered The Taser
While you wasted your days in maintenance in pursuit of vanity
I cultivated Inner Justice
And now that the world is on fire and the ops are at the gate you have the audacity to come to me for help?

**Pull request closed without merging**
