### PR TITLE
Makes narsie less huge

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Narsies mouth alone now takes up an entire 14x14 screen, and nar-sies layer is high enough that nobody can see anything going on near it making the end game somewhat unplayable. Nar-sie should now be the same size as ratvar again.

### CODE REVIEW

**Comment by kilkun** [comment]
can we just have both of them back to their original 128x128?

**Comment by Xhuis** [comment]
⚠️ WOAH THERE PARTNER ⚠️ 
ℹ️ THAT THERE PULL REQUEST OF YOURS VIOLATES OUR ❄️FEATURE FREEZE ❄️ 
CLOSE 🚪 THIS PR BEFORE I CLOSE 🚪 YOUR LIFE 🔫 😠

**Comment by ChangelingRain** [comment]
Ratvar was never 128x128.

**Comment by kilkun** [comment]
no but nar-sie was and ratvar is a nar-sie ripoff so it should be clear what i mean by that

**Comment by kilkun** [comment]
which is "delete clock cult"

**Comment by Shadowlight213** [comment]
delete both if you're deleting cc

**Comment by Shadowlight213** [comment]
@KorPhaeron 
Narsie is a big gal.
For you

**Comment by Repukan** [comment]
T h i c c

**Comment by kilkun** [comment]
cuck cult is just regular cult with more circlejerking and a fedora tipping steampunk theme

both are bad but clock cult is unironically the stupidest gamemode short of blob

**Comment by MimicFaux** [comment]
You sound salty.

**Comment by Repukan** [comment]
Oh, he called him salty, how will he ever recover.

**Comment by DoctoreMad** [comment]
He can recover when he starts being less salty.

**Comment by kilkun** [comment]
salty about bad gamemodes :rage:

**Comment by banthebantz** [comment]
stop nerfing shit

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
