### PR TITLE
Add an animation for shaking

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request

2020-08-16T04-11-39

## Why It's Good For The Game
Feedback is good.

## Changelog
:cl:
add: There is now an animation for shaking someone.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
May be too much?

**Comment by Iatots** [comment]
Why are you shaking them lenghtwise...

**Comment by Jared-Fogle** [comment]
@lalots Because it looked better than when I did it vertically.

**Comment by nemvar** [comment]
I say direction should depend on the angle of the shaker.

**Comment by Jared-Fogle** [comment]
I tried to do that, it's just that shaking up and down just didn't look good. I can try it again if you want.

**Comment by SkeletalElite** [comment]
I think it's a little too fast, maybe make it a little more subtle

**Pull request merged**
