### PR TITLE
Reworks the uplink interface to drastically reduce loading lag.

### PR DESCRIPTION
**Pull request by Shadowlight213**
uplink
Instead of showing all items at once, the uplink is collapsed into the various categories. click on a category to expand it and view the items inside.

The filter function has been removed as the way I'm handling lag reduction isn't compatible with it.

:cl: optional name here
fix: The syndicate uplink ui has been refactored to majorly reduce lag
/:cl:

Basically what I'm doing is only sending the item data for the category that is selected. The data flow to the UI is cut massively, and it doesn't need to build nearly as many buttons.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
ctrl+f doesnt really work with this and without the search bar it will be a genuine pain in the ass to find shit in the uplink

honestly we should just undo tgui for uplinks. it's better for a lot of things but the uplink is not one of them

**Comment by Shadowlight213** [comment]
I dunno filter might be possible, but I don't know how
@RemieRichards any ideas? the filter was erroring about some null fields. you know tgui better than me.

**Comment by Bawhoppen** [comment]
FINALLY SOMEONE DOES IT I'VE BEEN ASKING FOR IT FOR MONTHS :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by RemieRichards** [comment]
@Shadowlight213 you can't filter things like that. the data isn't in the UI until you pop open a category, there's nothing to find.

**Comment by Shadowlight213** [comment]
@RemieRichards well, I was referring to it working within the selected category. Obviously it can't filter what's not being sent.

**Comment by RemieRichards** [comment]
@Shadowlight213 those categories are so small it's pointless to filter.

**Comment by MrStonedOne** [comment]
You could have it send the data over and just store it in a json object, then filter that, and pass it to another category control called search results that is normally hidden.

**Comment by RemieRichards** [comment]
@MrStonedOne kind of defeats the point, I'm very much on the stance that it's big data killing tgui, not buttons.

**Comment by MrStonedOne** [comment]
if the data never gets passed to ractive, it doesn't cause lag, finding a way to store it in a javascript var on the page won't cause lag. then you just use javascript to pass it to ractive to display it.

**Comment by RemieRichards** [comment]
@MrStonedOne all the data from ```ui_data()``` goes to ractive, all of it.

**Comment by xxalpha** [comment]
This menu should use a grid layout to make it more compact.

**Comment by PKPenguin321** [comment]
Hi, I know you will most likely ignore this, but if you could possibly port this to personal crafting (specifically for food items so there aren't 40000 categories that are all dedicated to food) that would be really really cool

**Comment by nullbear** [comment]
YES. THE ABOVE.

**Comment by Shadowlight213** [comment]
Uhhh. I'll uh try looking into it.

**Pull request merged**
