### PR TITLE
Further improves various sprites.

### PR DESCRIPTION
**Pull request by WJohn**
Let's get this party started.
Four bar signs, more to be updated later, as a lot use items that I will be respriting first.

Hoops and basketball/dodgeball.

Body bags.

Blood bags.

:cl: WJohnston
imageadd: Improved/resprited a few bar signs, basketball/dodgeball/hoop, blood bags, and body bags.
/:cl:

### CODE REVIEW

**Comment by Nienhaus** [comment]
Those look pretty coo.

**Comment by PKPenguin321** [comment]
blood bags and bar signs are a definite 👍 , but i'd like a comparison between new and old for the other two before i pass judgement

**Comment by calzilla1** [comment]
John, i think you put WAAAAY too much effort into these things.  The spries are great,  but I don't think they match tg's style. This is not an insult,  but i think goon would love you.

**Comment by nullbear** [comment]
@calzilla1 he's respriting a LOT of things, with the intention of making this into tg's style. So this point is invalid. TG doesn't really have a style for sprites, unless you consider 'occasional ausops' + 'codersprites' + 'ripped sprites from other games' to be tg's style.

**Comment by Iamgoofball** [comment]
@calzilla1 fuck off

**Comment by calzilla1** [comment]
@nullbear I don't really think tg needs a "style change" tg has a distinct look (flat-ish 2d sprites) and I think this new 3d hd stuff will seriously clash with the rest of the game unless you over write pretty much EVERY sprite

**Comment by pudl** [comment]
The hoop, body and blood bags look awful. The top of the hoop has almost nothing going on, its literally just empty, off white space. Its terrible.

The body bag has the same issue, and it looks less like a body bag than the current sprite, and its just not as good as the current sprite. Speaking of not as good, the blood bag is also worse than the current one. Pretty much all of these sprites arent as good as the original ones.

**Comment by calzilla1** [comment]
Also,  the clown mask bothers me.  Looks like it's inverted

**Comment by pudl** [comment]
Lmao i didnt notice that clown mask, yeah, it looks bad

**Comment by PKPenguin321** [comment]
I disagree with you pudl, especially on blood bags. Current blood bags are paprika codersprites that look like shit, these are a huge improvement.

**Comment by XDTM** [comment]
Those self thumbs up

**Comment by pudl** [comment]
Paps didnt sprite blood bags, theyre ported from bay

**Comment by PKPenguin321** [comment]
Either way they suck ass

**Comment by WJohn** [comment]
The clown mask is only inverted when it's lit up by the surroundings, as it's supposedly an object on there. It looks normal when it's not in the flashing part of the animation.

**Comment by ike709** [comment]
I love everything, except I don't know how I feel about the bodybags. I agree the current ones are trash, but these give me mixed feelings.

**Comment by Xhuis** [comment]
Like them all, although body bags are oddly... solid? It seems like they'd be more formless. :+1: either way

**Comment by ShadowDeath6** [comment]
Don't really like the body bags, it looks too three-dimensional.

Everything else is good looking good though :+1:

**Comment by FantasticFwoosh** [comment]
The body bags actually supposed to have people concealed within them is a nice touch but there's not much of a point to the sprite compared to the current (which is zipping it wide open to reveal all the corpse) if they just pop in and out like before.

**Comment by WJohn** [comment]
Everything's gonna be 3d, no more of those flat-in-front shit. I'm getting tired of it, and it's limiting to how good we can make our sprites.

**Pull request merged**
