### PR TITLE
Removes the Families gamemode

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request

A little bit of server stepping into codebase, but this gamemode was fully blocked by the three current headmins (and requested for removal), and hasn't been used on live servers for quite some time (as far as im aware).

The creator/reviver of families would also like to see this removed so it can at least be used in downstreams. So I took the time to remove it for them.

I left the family specific clothing in because it does no harm, and I believe the spritetainers had no words on whether it should be removed or not.

If I missed anything please let me know.

## Why It's Good For The Game

This gamemode is largely unused, due to conflicting policy requirements and unenjoyment (i think). Aswell, removing it here makes it easier for other servers to use it downstream.

## Changelog

:cl:
del: Removed the families gamemode.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
``The creator/reviver of families would also like to see this removed so it can at least be used in downstreams. So I took the time to remove it for them.``

To clarify, I don't actually want it removed, but if it's going to be removed then I want it done now so that we can get it modularized downstream.

**Comment by bluetshirtguy** [comment]
Rest in peace.

**Review by Mothblocks — APPROVED** [review]
I was going to get to it next month so good that we do it now

There are some further changes that are gonna need to be made to the clothing--they need the video game reference culling ported from the closed Families PR, and there are some I think art team wants to remove, but you don't need to concern yourself with that

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Oh one last thing, because screenshot tests don't support this yet--can you go to the unit tests folder, go inside screenshots, and delete the families ones?

**Comment by Iamgoofball** [comment]
The art team did not reply when asked about removal, if they have an issue with the sprites they can contact me so we can get those issues resolved.

**Comment by Mothblocks** [comment]
I haven't heard word back myself on specifics FWIW, and even if I did, a bit out of scope for this PR

**Comment by SuperNovaa41** [comment]
> Oh one last thing, because screenshot tests don't support this yet--can you go to the unit tests folder, go inside screenshots, and delete the families ones?

sure

**Comment by Colovorat** [comment]
What about families drip? Will it be still available to buy?

**Comment by ATH1909** [comment]
so families won't be available even as admin spawns now?

sad.

**Comment by Mothblocks** [comment]
@Colovorat Read the PR more closely

> I left the family specific clothing in because it does no harm, and I believe the spritetainers had no words on whether it should be removed or not.

**Comment by optimumtact** [comment]
>This gamemode is largely unused, due to conflicting policy requirements and unenjoyment (i think). Aswell, removing it here makes it easier for other servers to use it downstream.

This is false, both in that it is now harder for downstreams to remove it and for the reason it was removed soley because the admin team didn't like it or it's creator.

**Pull request merged**
