### PR TITLE
Airlock closing made easy

### PR DESCRIPTION
**Pull request by kingofkosmos**
Added invisible pixels near the opened airlocks so closing them won't require pixel-accurate clicking anymore, just clicking near the airlock (or the dents) is enough. All credit to WJohnston for doing all the actual work!

The red area seen below is invisible in-game, but clickable.
shb0mzw

### CODE REVIEW

**Comment by Chocobro** [comment]
FINALLY
now it will be easier to stop clowns running into cargo to steal shit from the autolathe

**Comment by Jalleo** [comment]
why not do the same thing as the proposed kudzu if there is nothing else on the tile.

**Comment by phil235** [comment]
Jalleo, wouldn't that prevent you from interacting with the floortile (e.g. crowbarring the tile) ?

**Comment by vista-** [comment]
Why would you want to crowbar a tile under kudzu?

**Comment by kingofkosmos** [comment]
What. In the case of an airlock, it's not uncommon for e.g. a power wire to go under an airlock.

Now if someone would want to interact with it (or follow the wire without t-ray), they couldn't do that with the mouse_opacity 2 -thing the kudzu PR uses. I talked to MrPerson about it, and he said that it's not possible to make the mouse_opacity switch on or off depending if the player's holding a tool in his hand or not, which would be required to make it not completely fuck over anyone who's trying to crowbar the tile under the airlock, or multitool the power wire under the airlock etc.

Although that is a rare case, and if people think so, I'd be more than happy to do the mouse_opacity 2 with the cost of fucking a handful of engineers over.

**Comment by RandomMarine** [comment]
@kingofkosmos  They can still just alt-click the tile, right?

**Comment by Jalleo** [comment]
You can still alt click interact it.

**Comment by kingofkosmos** [comment]
Another PR opened with same thing as the proposed kudzu.

**Pull request merged**
