### PR TITLE
buffs stamina regeneration take 2

### PR DESCRIPTION
**Pull request by CPTANT**
Lets try this again.

Stamina regeneration is now complete aids.
After this it will just be serious aids.

:cl:
tweak: stamina regeneration is now 50% faster.
/:cl:

### CODE REVIEW

**Comment by KazeEspada** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
Double it, in my opinion, then double all the stamina reduction chems, too.

**Comment by WJohn** [comment]
I thought disablers already did 40 per shot?

**Comment by Fox-McCloud** [comment]
@WJohn 

They do 36--the intent/goal is so that they can down in 3 shots in a reasonable time frame, even with the person fleeing.

**Comment by CPTANT** [comment]
@Fox-McCloud 

Personally I would like to buff it more, but I don't want to completely fuck over stamina based weapons.

**Comment by Saegrimr** [comment]
When at 80-100% stamina damage, use current regen, when below that start regening faster then?

**Comment by Robustin** [comment]
Yes, tested it a while back and I dont recall the specifics but it was ridiculous how long it took to recover from stamina damages.

**Comment by Fox-McCloud** [comment]
it currently takes 1 minute and 40 seconds to go from 100 to 0.

**Comment by lzimann** [comment]
You can always sleep to fully recover stamina(but then you will be vunerable and can't wake up whenever you want), but I agree with this, stam damage is annoying and should recover faster

**Pull request merged**
