### PR TITLE
The Grapplening: FIRMLY GRASP (THE ASSISTANT) IN YOUR HAND

### PR DESCRIPTION
**Pull request by necromanceranne**
###

When a mob is grabbed, resisting that grab is currently determined by what state the grab is in; Passive (0), Aggressive (1), Neck (2) or Choke (3). Each stage has different effects and each stage also has different resistance probabilities. At only Passive, you never have to resist to end this grab, and the only effect is that you are tugged along by another mob or some such.

With regards to **resistance**, there are several possible factors that will cause you to need to resist even during a Passive grab. This is determined by first checking whether they exist, and then increasing the grab state by +1. This is clunky, these effects are rare enough to not necessarily be present with one another, and the sole decrease to effective grab state for resistance only checks AFTER we already have decided that we need to resist the grab in the first place and then elevated the grab by one because of that from other effects.

In this PR, I've turned each of these into separate checks that individually modify the effective grab state for the sake of resistance. If each one is present, it will either increase or decrease the effective state by 1, and if the value is ever above 0 (Passive grabs are 0), then the mob is expected to resist their grab state.

This does not impact the TRUE grab state of the mob, and does not more quickly deprive a mob of actions. This only impacts resistance.

**These increase the effective state:** 

Being at a combined 40 damage from either Brute or Burn damage and you are staggered.

Having the Pushover quirk (good luck pal)

You are prone.

**These decrease the effective state:**

Having grab resistance AKA you have a fish infusion. 

### Your unarmed values contribute to grab damage (if you're human)

if you have arms, and you're grabbing someone (don't ask me how you grab without arms), then congratulations. You get to add your unarmed values to the stamina damage you deal. It's a random roll between lower and higher, as expected. The stronger your arms, the higher the damage.

If you're a Drunken Brawler, then congratulations, you get to add even more damage based on how brutalized you are, so long as you're drunk. You also increase the effective grab state while drunk. Congratulations, bartender, you also have a command grab. Just like the chef.

## Why It's Good For The Game

It's really frustrating to have someone snap out of a grab despite the fact they have several layers of grab elevators affecting them at the time. They could be prone, a pushover, staggered and also having taken enough brute and burn to otherwise be forced to have to resist, but they still only ever resist on a passive grab as an aggressive grab, which is a 60% probability to break. This kind of sucks for departmental defense reasons, and I think being more grab vulnerable should be punishing enough that an opponent could start really laying in the hurt if they do get the grab, or instead 

Unarmed values were weirdly absent from this effect as well, so I've included them to make grabbing more powerful for someone who invested. Or, I suppose, if the bartender in a drunken stupor decides your ass is getting tossed out into the hallway. No longer does the bartender have to always ask the chef for help, they can do it themselves! Violent, drunken manhandling!

## Changelog
:cl:
balance: After months of rigorous training montages, handwork and dedication. Nanotrasen can proudly say that their staff is now more capable of performing various judo techniques to disable and incapacitate any would-be troublemakers. They have proclaimed the Spinward 'safer than ever'. Unfortunately for Nanotrasen and the Spinward as a whole,, most of these same techniques have been incorporated into the Tunnel Arts through the use of Khan spies. (See: Extremely bored assistants who are getting tired of suplexing the clown). Is this the end for the Spinward Sector? Will anyone be able to stop Maint Khan's advance?
balance: Being grabbed can be harder to break out of depending on how vulnerable you are; being prone, staggered and wounded, or just being a pushover (the quirk) makes it easier to keep hold of you. Particularly if more than one of these is true. Though if you're a fishman, you probably can't get grabbed at all.
balance: Your arm power now contributes to the stamina damage someone is dealt when they attempt and fail to break out of your grab.
balance: Bartenders while drunk are great at grappling.
fix: The values used for determining at what point you must resist if you have taken damage and are staggered are now correctly set to 40, not incorrectly to 80.
/:cl:

### CODE REVIEW

**Comment by Eronymun** [comment]
What are all current ways to increase your unarmed again and what is the theoretical max number you can roll on a grab with every modifier, and is it fair?

**Comment by Loafin34** [comment]
Drunken brawling, advanced cybernetic arms, I believe magboots increase kicking power, and martial arts don't count because the two actually-usable ones (scarp, cqc) do aggressive grabs already. krav maga i believe doesnt do that so it might factor in

**Comment by necromanceranne** [comment]
Loafin has most of it, though magboots do not actually increase kicking power.

**Comment by Eronymun** [comment]
Ah I see. I was a little confused about upgrading grabs - as in, if you had enough drunken brawling force you'd be able to go past aggressive and straight to a choking grab. 

Still though, this is a pretty terrifying for bartenders. If I'm reading this right then a cybernetically augmented, drunk bartender at half health essentially has a low cooldown stun baton option that they can use with both hands full in terms of stamina damage - and iirc drunken brawler even works outside of the bar - that even causes grab stun to boot.

It would be pretty interesting to see in play for traitor bartenders.

**Comment by YuliceTheDruid** [comment]
Wouldn't this make Hulks grab monsters?
Not saying that that is a good or bad thing, but just asking out of curiosity.

**Comment by necromanceranne** [comment]
Hulks have no special benefit to grabbing.

**Comment by necromanceranne** [comment]
> It would be pretty interesting to see in play for traitor bartenders.

For a passive grab, you still don't lost any hand use, so even if this upgraded bartender does come for you, you can still usually respond even if you are forced to resist that passive grab. It's only until he upgrades the grab into an actual aggressive grab that it truly 'stuns'.

Think of passive being closer to an immobilizing effect that forces you to follow them, and aggressive to be more of a true hold that takes away actions.

For the most part, you probably will not notice a significant change in most instances where you wouldn't have noticed it already.

**Comment by Eronymun** [comment]
Oh I see. I thought it was just instantly upgrading to an aggressive grab based on the state of someone (prone/damaged).
I also misread the stam damage part, it's on resist, I thought it was on the grab itself.

Unrelated but you could do some neat gunfu by shooting someone with a revolver once, shoving, then grabbing. Makes me wish you could pistol whip for a stagger effect.

**Comment by Sakamoto4ka** [comment]
still not much usefull change for maint fu but useful for batongrab with even less chance(which wasn't anyway) to resist. for some reason, in PR, where someone wanted to remove instastun or add a short time before the second baton attack, someone mentioned that baton should strike exactly 2 hits, but in PR, where in fact the baton needs 1 attack (stunshove, batongrab), this paste isnt here.

**Comment by SomeoneYouProbablyKnow** [comment]
Also makes randomly grabbing distracted people stronger. Somsthing bound to give you a bonus on that and getting ctrl clicked twice in a middle of a conversation is the worst

**Comment by necromanceranne** [comment]
> Unrelated but you could do some neat gunfu by shooting someone with a revolver once, shoving, then grabbing. Makes me wish you could pistol whip for a stagger effect.

The idea of pistol whipping causing a stagger is kinda neat. Though what you're suggesting is actually already a thing on live, but not usually super usable. Usually if you shoot someone enough to do enough damage to make it harder for them to escape grabs, you could probably just keep shooting them and finish them off.

**Comment by necromanceranne** [comment]
> Also makes randomly grabbing distracted people stronger. Somsthing bound to give you a bonus on that and getting ctrl clicked twice in a middle of a conversation is the worst

This is no different before or after this PR. Someone standing out in the open and who has someone attempt to only grab them twice probably breaks the grab more times than not if they resist in any fashion at all (hits the movement keys), and has plenty of opportunity to escape after. If you cannot easily do this on live, you cannot necessarily do this after this PR. UNLESS the target took the Pushover quirk. In which case, the negative quirk is doing its job?

Attacking people while distracted or, god forbid, someone typebaited you and attacked you is either the game working as intended or banworthy and I don't think I need to correct that in any fashion.

**Comment by SomeoneYouProbablyKnow** [comment]
It is a tiny bit different after this pr. For the small % of cases where you have some damage from something else already. And whilr attacking someone suddenly IS the game working as intended it being as easy as clicking twice isnt necessarily something that's good. But completely unrelated to the pr itself if we are being honest barring the small edge case. I guess i don't see it impacting me (as either side the grabber or the grabbee) more than in that edge case

**Comment by necromanceranne** [comment]
If you're so beat up as to have about 40 brute/burn combined, you likely are already at a vulnerable state from slowdown alone.

AND this still requires you to be staggered, and the only conventional method for most people to apply that is with a shove. So that's actually closer to two hits, followed by a third where they actually stop you from responding back.

This also is something that can happen in the live game with the same outcomes in fact. If it isn't a problem now, it isn't a problem after the PR.

**Comment by Redrover1760** [comment]
the pr body isn't entirely clear what it actually changes regarding having the grab state changed/effectively changed.

**Comment by necromanceranne** [comment]
> the pr body isn't entirely clear what it actually changes in terms of actual gameplay regarding having the grab state changed/effectively changed.

Yeah, I do apologize about that, I'll try my best to re-explain whats going on in a bit.

**Comment by necromanceranne** [comment]
Alright, I rewrote the PR body. Hopefully this is a bit clearer as to what it is trying to do. Sorry about that, I sometimes do these prs sleep deprived.

**Comment by projectkepler-ru** [comment]
What are ways to increase resistances?

**Comment by necromanceranne** [comment]
Fish infusion can make you harder to grapple. That's the only one implemented at the moment actually.

**Comment by carlarctg** [comment]
we should add another if youre splashed with space lube

**Comment by necromanceranne** [comment]
That definitely sounds funny, I might do that as a follow up. Clowns suddenly becoming very difficult to grab would be extremely funny to me.

**Comment by Sonnzer** [comment]
another good Anne PR, banger after banger tbh

**Comment by Loafin34** [comment]
being fat should make you more grab susceptible

**Comment by SomeoneYouProbablyKnow** [comment]
Doesnt being fat make you harder to grab?

**Comment by Loafin34** [comment]
you have more mass to hold onto

**Comment by SomeoneYouProbablyKnow** [comment]
How big are your palms? Are you grabbing the whole person with just one hand? If anything fat people are harder to grab all other things being equal

**Review by SmArtKar — CHANGES_REQUESTED** [review]

**Pull request merged**
