### PR TITLE
Removes DNA Aide

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
-Makes genetics irrelevant
-Obtainable very quickly
-Little downside outside of the randomness 
-Spreads to the whole crew so you have xray hulks running around (either validhunting or breaking into every room for no reason).

Other feeling bad for removing something and not leaving something new in its place I can't really think of a reason to keep it. People have been complaining loudly about this so here is the PR.

If I'm mistaken about the general mood then I guess the PR can be closed though.

### CODE REVIEW

**Comment by Steelpoint** [comment]
I've been asking this since it was added.

It really just stepped into the toes of Genetics too much, as well as detract from the other things Viro could do.

Viro is all about more subtle powers that are not overtly influencing but still give a good advantage.

**Comment by GunHog** [comment]
Do not <b>remove</b> it. Change it. Have it heal cloneloss and cure bad blocks in the SE WITHOUT affecting the six power blocks.

**Comment by Supermichael777** [comment]
Absolutely terrible, how did it get merged in the first place?
NINJA: good idea gunhog but it will still re-roll your powers if you have them. therefore still terrible

**Comment by GunHog** [comment]
Slow down the rate to a few minutes (like it was before), then have it work like normal genetics where powers you have are NOT lost, but you have a small chance to manifest them. So it works as a *compliment* to Genetics without being a replacement.

**Comment by KorPhaeron** [comment]
@GunHog 

I've honestly never really played genetics or viro so fuck if I know how to code any of that. You should make the PR if you have an idea of how to do it though.

**Comment by Xhuis** [comment]
___THANK GOD.___
:+1:

**Comment by Kromgar** [comment]
PRAISE BE TO KOR 


Now Kor I kindly ask that you remove all of Goofs stupid meme powers so genetics isn't a chore to find powers. Its so bad now YOU HAVE 11 BLOCKS TO TEST. Its ridiculous

**Comment by Kromgar** [comment]
@Gunhog its the most overpowered disease viro has it totally invalidates genetics it should just be removed

**Comment by Aloraydrel** [comment]
Gunhogs idea sounds butter but please remove aids

**Comment by AlexCrimson** [comment]
loloverpowered. Its a gimmick/grief symptom. Thats all really. Rarely so Virologists actually give Genetics a working DNA Aide virus. Even if they do, its not like makes Genetics a whole lot faster. 

If you want to nerf Viro, then stop virus stacking effects. x3 regen is absolutely insane. Remove x3 stacking, and buff all symptoms slightly to make up for it.

**Comment by xxalpha** [comment]
It would be better if you did what gun hog suggested (improve don't remove), but I am not against removing it.

**Comment by Anonus** [comment]
:+1:
It's terrible and results in a station of superpowers really fast.

**Comment by Dorsisdwarf** [comment]
:+1: 
Improve not remove is fine, but sometimes it's better to remove for now then rebuild from the ground up

**Comment by Nanotransistor** [comment]
Good. Fuck this disease.

**Comment by KorPhaeron** [comment]
Remade here https://github.com/tgstation/-tg-station/pull/11941

**Pull request closed without merging**
