### PR TITLE
smite now uses a radial

### PR DESCRIPTION
**Pull request by Amelia0010**
:cl: Nichlas0010
admin: Smite menu now uses a radial
/:cl:

image

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
god i fucking love radial menus
makes me wanna be admin

**Comment by qbmax32** [comment]
Based

**Comment by MrDoomBringer** [comment]
The icons are cool, but _personally_ i would reccomend changing:
- the BSA, as that boom kinda implies a large area of affect
- the lightning, maybe change to the EMP yellow lightning bolt icon
- the fireball, i would use the actual fireball sprite rather than a burning peice of paper

**Comment by subject217** [comment]
The icons are ambiguous. IMO a feature like this should be designed to be used by someone who is a new admin, not someone who is experienced.

**Comment by optimumtact** [comment]
at the very least it would need some kind of tooltip hover

**Comment by Barhandar** [comment]
It would need to not be utter shit, i.e. not a fucking radial menu for fucks sake, the inability to toggle RCD modes quickly is trash so the only good thing is the airlock menu, and only because airlocks need visuals.

**Comment by optimumtact** [comment]
thanks barhandar your extensive experience as an admin is really valuable for us when we're deciding how to improve admin tools, appreciate it.

**Comment by nichlas0010** [comment]
@optimumtact Radials show the name of the option in the bottom left, like hovering over other atoms. So in this case, hovering over each option means the name of the option is shown down there.

image

**Comment by optimumtact** [comment]
That's not really obvious at all

**Comment by nichlas0010** [comment]
What, hovering over the option showing the name in the place where the name of anything you hover over is shown isn't obvious?

**Comment by BeeSting12** [comment]
I prefer being able to press a letter key and then immediately going to that one. Right click, click smite, press 'b', enter. Easy BSA or brain damage whichever comes first

**Comment by Alexch2** [comment]
Yeah, I've got the exact same thought about it that @BeeSting12 has. Not everything needs to be "pretty", especially not at the cost of usability.

**Comment by MrDoomBringer** [comment]
@Alexch2 
beesting's idea wasnt mutually exclusive of this one
image

**Comment by MrDoomBringer** [comment]
why would you delete this

**Pull request closed without merging**
