### PR TITLE
Changes jetpack objective

### LINKED ISSUE #12059: miners can get the objective to steal a jetpack
an object they can get within their job.

### PR DESCRIPTION
**Pull request by Firecage**
PR updated.
1. Adds the captains jetpack as a new items.
2. Adds it to the captains suit storage unit.
3. Changes the steal jetpack objective to require the captains jetpack, thus it no longer counts any jetpack.
4. Changes the difficulty required to 5, to match other captain items.
5. Shitty codersprites.

normal item sprite: 
captainjetpack

Fixes #12059

### CODE REVIEW

**Comment by Bawhoppen** [comment]
No. Thats stupid.

**Comment by xxalpha** [comment]
Yeah, what? The void jetpacks are in the derelict.

**Comment by Firecage** [comment]
Baw. You do realise otherwise literally ANY jetpack counts for the steal objective. Even the jetpacks syndies can order.

**Comment by MMMiracles** [comment]
Maybe make a special jetpack that can fit in a backpack like the Op ones and give it to the captain. It'd fall in line with all the other special shit each head gets (hypo for cmo, reactive armor for rd, 3-tier lasergun for hos, ect).

**Comment by Firecage** [comment]
Good idea, might do that.

**Comment by Bawhoppen** [comment]
Just make it only void, carbon dioxide (they need to research the mysterious gas), or the oxygen one.

The fact that stealing a hardsuit with an inbuilt jetpack counting is even possible is dumb.

**Comment by Firecage** [comment]
....Baw, do you even know what carbon dioxide is...

**Comment by MMMiracles** [comment]
It's a sick meme.

**Comment by Robustin** [comment]
Most traitor objectives are dumb. Maybe avoid screwing with jetpacks and just make it some other reasonable item like an AI upload board. At least people will care/investigate when that shit gets stolen.

**Comment by Firecage** [comment]
Robustin. I am not making a new steal objective. This PR is to make the steal jetpack objective less retarded.

**Comment by Alek2ander** [comment]
Bring back head jumpsuit objectives 2015

**Comment by Steelpoint** [comment]
We should do a review of traitor objectives at some point.

**Comment by Xhuis** [comment]
:+1:

**Comment by Lumipharon** [comment]
Jetpack steal objective is objectively retarded though.
SS13 jetpacks are just tanks of gas with a nozzle, not actual jets.

**Comment by xxalpha** [comment]
Guys the void jetpacks are in the derelict, there's no challenge in getting them. It's just as pointless as it is now.

**Comment by Firecage** [comment]
XXalpha. Would you mind actually reading the OP?

**Comment by bgobandit** [comment]
@firecage what the fuck is carbon dioxide

**Comment by Jalleo** [comment]
@Miauw62 maintainer chat lock please the memevasion must end.

**Comment by Firecage** [comment]
Jalleo, but then I can't comment on my own PR...

**Comment by Fox-McCloud** [comment]
This does need updating, I agree, but just giving the Captain a jetpack, even if it can fit in a backpack, is pretty meh of an item.

Advance magboots are an item players *care* about and want. It preventing slipping and spacewind pushing all while having no slowdown. It's a valuable commodity.

A jetpack that can fit in your backpack isn't really any more valuable than a jetpack that doesn't (miners also have jetpacks that can fit in backpacks), because while it's far more convenient to travel with them....you're still giving up storage while using said jetpack.

Now a jetpack that *acted* as a backpack? THAT would be something players would like/want.


Alternatively, make the captain's armor have a built in jetpack and make the objective "steal the Captain's armor", instead.

**Comment by Lumipharon** [comment]
Does this PR also ignore the fact the the captain already has a (as far as I know) unique jetpack? While functionally inferior to nukeop/void ones, I'm pretty sure it's still unique.

**Comment by Fox-McCloud** [comment]
@Lumipharon 

The only thing "unique" about it is that it's blue and has oxygen in it instead of carbon dioxide. Hardly something the Syndicate would want to steal over a jetpack with carbon dioxide.

**Comment by Lumipharon** [comment]
Yes but I mean, what is the difference between the current captain's unique jetpack and the one this pr is adding?

**Comment by Fox-McCloud** [comment]
Oh, in reference to this PR? Yeah, it's just a reskinned oxygen jetpack that has HUGE capacity and can fit in a backpack.

**Comment by Dorsisdwarf** [comment]
The sprite should be captain-trim blue and gold, rather than puke and brown.

**Comment by xxalpha** [comment]
No trim, just a couple of stripes.

**Comment by Razharas** [comment]
Im ok with this

**Pull request merged**
