### PR TITLE
Premium Items are no longer free for departments

### PR DESCRIPTION
**Pull request by Iamgoofball**
Request from the boss-man.

Also fixes the bug with premium pricing.

### CODE REVIEW

**Comment by optimumtact** [comment]
A request from who?

**Comment by Iamgoofball** [comment]
the guy who paid me to make economy requested it

i suppose second-boss-man is in order

**Comment by Repukan** [comment]
You should also fix or remove item spitting from vendors.

People are abusing it for free items

**Comment by BeeSting12** [comment]
@optimumtact (and to everyone who's downvoted this)

This allows for people to put cosmetic or other items in the vendors as sort of upgrades from the current stuff in the vendor. That way, everyone will have something to do with their money. This is also the way it was before the economy- premium items had to be paid for with coins.

Read this thread for more details: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=19772

**Comment by subject217** [comment]
Coins were trivial, it was basically just an effort check to run to dorms or something.

I dislike upping costs on any of this shit without fixing what you ruined first, to be honest. https://github.com/tgstation/tgstation/pull/40532 should be merged first at bare minimum.

**Comment by subject217** [comment]
Very funny.

**Comment by Iamgoofball** [comment]
@subject217 what are you gonna do about it, huh? Rageban me and get destroyed in appeals? Didn't think so. Get over yourself for once.

**Comment by subject217** [comment]
You're not the one who merged it, Goofball.

**Comment by Iamgoofball** [comment]
You also can't rageban Joan since they're already banned 5ever, so your point?

**Pull request merged**
