### PR TITLE
Renames Sahkno rifles and derivatives

### PR DESCRIPTION
**Pull request by Capsandi**
## About The Pull Request

Sahkno to Carabine (rifle)
Strilka .310 to Striker .310 (rifle clip and bullets)
Jezail to Aardvark (donksoft variant, longer barrel -> aardvark's long nose)

Orbez was the name for a sawn off Sahkno so its not too large of a change.

## Why It's Good For The Game

I consider myself disgustingly intelligent and my idea of how to pronounce these names waffles between partially correct understandings, providing endless anguish. I am projecting when I say this is likely the case for most of our players.
It's a controversial gun what with the mosin situation but the least controversial improvement is making sure players don't need to look up what languages the names are borrowed from to figure out how to pronounce them.

## Changelog

:cl:
spellcheck: Sahkno rifles are now called Carabine rifles
spellcheck: Donksoft Jezail rifles are now called Donksoft Aardvarks
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
A bit of a weird question, but how does TTS handle these names? I'd prefer if spessmen didnt screech horrifically trying to pronounce a firearm's name

**Comment by Iamgoofball** [comment]
How is Aardvark any easier to pronounce than Jezail, an actual type of gun?

**Comment by Iamgoofball** [comment]
>A bit of a weird question, but how does TTS handle these names? I'd prefer if spessmen didnt screech horrifically trying to pronounce a firearm's name

Irrelevant for now, we're in the process of subbing out the TTS engine

**Comment by Capsandi** [comment]
> How is Aardvark any easier to pronounce than Jezail, an actual type of gun?

I thought Jezail was greek before making this pr, so I was trying to pronounce it , turns out its arabic, and even then I've been told its pronounced Jes-ale and Jes- all by two different people. Being exact about different gun designations is cool and all I don't mean any disrespect to the gun nuts around here. Aardvark is a pretty 1:1 pronunciation but if you have any better suggestion which isn't nebulous in its pronunciation I'm not attached to any of these names (though Carabine is growing on me).

**Comment by Iamgoofball** [comment]
I think this PR should just be closed, Sakhno and Jezail aren't hard to pronounce at all unless you're a wine mom from California who pronounces quesadilla incorrectly.

**Comment by Capsandi** [comment]
Let it be known there is no sentiment which could bring me to closing this PR by my own hand other than a dissent from goofball, whose good sense in the matters of this project I often heed.
Also you forgot about the bulldog shotgun
Merry Christmas

**Pull request closed without merging**
