### PR TITLE
Lexorin Requires Salbu Instead of Oxygen

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request

Title

## Why It's Good For The Game

Lexorin is really strong with the recent O2 changes in relation to the difficulty needed to make it. This fixes that.

## Changelog
:cl: O2by
balance: Lexorin now requires Salbutamol instead of Oxygen (FIX YOUR MACROS)
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
wouldnt it be easier to just make it do less oxy damage

**Comment by bigfatbananacyclops** [comment]
oh this is a recipe change

**Comment by ExcessiveUseOfCobblestone** [comment]
> wouldnt it be better to just make it do less oxy damage

Outside of competition with equally easy to make toxins (which isn't really a pro), I don't see how it would be better.

**Comment by dr-bee** [comment]
isnt salbul unobtainable now?

**Comment by davethwave** [comment]
Nope, just VERY annoying to make.

**Comment by ExcessiveUseOfCobblestone** [comment]
I only removed salbu from roundstart, it can still be crafted although that recipe is godawful.

**Comment by Rowelll** [comment]
just a small macro change, haha

**Comment by terranaut1** [comment]
phenol=1;sodium=1;carbon=1;oxygen=1;sacid=1;ammonia=5;aluminium=5;bromine=5;lithium=5;plasma=25;hydrogen=25

**Comment by ExcessiveUseOfCobblestone** [comment]
ty

**Pull request merged**
