### PR TITLE
Lowers romerol zombie passive regen

### PR DESCRIPTION
**Pull request by jughu**
To stronk heal

### CODE REVIEW

**Comment by Bluespace** [comment]
I

**Comment by Bluespace** [comment]
HAVE

**Comment by Bluespace** [comment]
DIED

**Comment by Bluespace** [comment]
PLEASE

**Comment by Bluespace** [comment]
NERF

**Comment by jughu** [comment]
More like i robusted 5 people at once as a single zombie and they couldnt do nothing about it

**Comment by kevinz000** [comment]
Those must be some really unrobust folks.

**Comment by jughu** [comment]
I AM nerfing it kevinz.

**Comment by CPTANT** [comment]
Zombies should heal over time, just at a far lower rate.

Slash the regen to 2,2. Don't remove it completely.

**Comment by ShadowDeath6** [comment]
I think a slow regen would be good so zombies who have taken damage aren't encouraged to kill themselves and stop playing until they revive

**Comment by jughu** [comment]
Zombies shouldnt regen at all

**Comment by jughu** [comment]
Zombies should fight till they drop

**Comment by ShadowDeath6** [comment]
this is going to end up in zombies killing themselves so they can fully heal after a fight which is unengaging and less fun than shambling around waiting for your shit to heal

**Comment by jughu** [comment]
PLAYERBASE ISSUE

**Comment by jughu** [comment]
Besides if zombies die its crew task to remove their tumor and clone

**Comment by Robustin** [comment]
Jesus you guys are going to make me come up with non-terrible solutions for everything.

Lowering it is obviously better than removal, but I haven't seen a round where this was anything more than a retard check - once people start creating weapons like spears and circ saws, its effortless to outdamage the regeneration. Keep in mind the healing viruses do 3/tick. across all damage types.

My concern isn't so much about the "combat utility" of the regen, but rather the QOL for zombie players who are missing 80 health. If you're sitting on 80 brute damage at 2regen youre looking at needing over a minute to regenerate. In my view, needing that long to heal serious wounds is when playing a zombie starts becoming seriously unfun. I'll cook up a better compromise.

**Comment by jughu** [comment]
not everyone is you oldman.

**Comment by KorPhaeron** [comment]
I like Oldmans solution better

**Pull request closed without merging**
