### PR TITLE
new bepis design: Rusty old diving suit

### PR DESCRIPTION
**Pull request by ghost**
:cl: floyd / keek
 add: new BEPIS design; an old steampunky diving suit
/:cl:

still had these sprites and theyre pretty based so why not

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
does the lathe apply rust to it?

**Comment by Qustinnus** [comment]
yes it oxidizes it for that good old authentic feel

**Comment by trollbreeder** [comment]
Pressure proof like a firesuit?

**Comment by Qustinnus** [comment]
No I'm scared it'll be a cheap replacement otherwise

**Comment by Qustinnus** [comment]
got too much prs open rn with merge conflicts and i hate fixing these so ill re-open this when i feel like it

**Pull request closed without merging**
