### PR TITLE
Updates DreamStation 03 to 04

### LINKED ISSUE #12260: Dreamstation 3 : HoS has 2 Camera Consoles.

### PR DESCRIPTION
**Pull request by ChangelingRain**
> Fixes the mining shuttle being depowered(unreported)
> Fixes #12260 
> Fixes a few balance issues with certain secrets
> Also fixes security being, uh, lower security than intended
> Removes a few AI turrets, it's probably strong enough anyway

Quickmerge this so people stop talking about issues in ooc while not once posting on the forums or making an issue report

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>Fixes a few balance issues with certain secrets

Please tell me you didnt remove the 5 stack of bear traps because that shit is hilarious

**Comment by WJohn** [comment]
Looks like your map merge sorta failed there.

**Comment by Jordie0608** [comment]
It's suggested you drop the numbering from the map's name as it'll help a bunch with versioning history of the files and mean you don't have to update the .dm all the time.

**Comment by Anonus** [comment]
_How does metacide get away with any of it_

So, uh, how do i use the map merger, what is the map merger, is there any real benefit to using it in this case etc etc

**Comment by Jordie0608** [comment]
Because of some magic with byond, map edits made with dream maker make git think you've changed every line in the dmm, this makes versioning and seeing what was actually changed on github a pain. The map merger allows you to overcome these issues.
See here for how to use it: https://tgstation13.org/wiki/Map_Merger

**Comment by Anonus** [comment]
I'll, use that on any more changes I make to my map but I've got no idea how to use it here and I don't know if it's really worth the effort to do it for this update, unless not doing it means it won't get merged so uh

**Pull request merged**
