### PR TITLE
Helmet obscures eye slot

### PR DESCRIPTION
**Pull request by erwgd**
This PR makes the helmet obscure the eye inventory slot, meaning one can't remove glasses without taking off the helmet first. Right now only the ears are obscured by the helmet, even though the visor you see would block glasses from being taken off.

This affects the standard helmet, its bulletproof variant and the laser tag helmets. I have made an overriding flags_inv for the Blue Shift variant of the helmet; this helmet has no visor, so only obscures ears.

:cl: Erwgd
:tweak: Standard helmets now obscure the eyes, so remove the helmet to be able to remove any eyewear.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:-1: Reverse quality of life

**Comment by optimumtact** [comment]
Also will this make people wearing helmets immune to flashes if they're not wearing eyeprotection?

**Comment by erwgd** [comment]
@optimumtact oh, i had not considered that! Guess this'll be closed then.

**Comment by optimumtact** [comment]
That wasn't a statement, it was a question

**Comment by TechnoAlchemisto** [comment]
Make sure that this doesn't cause the glasses
Sprite to disappear through the helmet visor

**Comment by erwgd** [comment]
I've tested it: the helmet will not protect you at all from flashes. 
Glasses can't be seen through the visor at the moment, and I'm not sure how to fix that.

**Comment by erwgd** [comment]
I will close this until I can code something that will prevent #14780 from happening again

**Pull request closed without merging**
