### PR TITLE
Revert "Tweaks railings to stand and look taller"

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

reverts the sprites to exactly the commit before arcanes commit

## Why It's Good For The Game

The tall sprites match actually none of the border objects we have bar other railings, they look okay standalone but they look not so good when near any actual object ( also not mobs) like walls, border firelocks, directional windows, etc
Additionally they come from the Wallening which was thankfully shot down so we ALSO dont (and 90% likely wont) have any sprites in that perspective to match railings

With this revert, most of those issues should be remedied (Wooden railing doesnt have a not-tall sprite, im no spriter)
See the comparison:

# like right now
2024-10-12 12_12_51-Window
2024-10-12 12_11_05-Window
2024-10-12 12_10_58-Window
# PR does this
2024-10-12 11_44_14-Window
2024-10-12 11_43_18-Window
Untitled

## Changelog
:cl:
del: Tall railings have been replaced for the old classic railing sprites
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
what about other maps, how do they look?

**Comment by DATA-xPUNGED** [comment]
All the examples you showed just look worse

**Comment by 00-Steven** [comment]
I feel it does not look better with windows, as they're still not topdown but rather pointing whichever way is 'in', leading to clashing but in a different way
Besides that, it does look worse when put besides tables, chairs, consoles- really most of our objects which share a similar perspective. Given that's what I personally tend to use them for separating during gameplay, it feels especially off to me

**Comment by mc-oofert** [comment]
border objects are fundamentally fucked in a tilebased game anyway

**Comment by MrMelbert** [comment]
We should get the wallening thinwindow / half thinwindow sprites instead they looked way better

**Comment by Loafin34** [comment]
they were 2-inch thick panes of plastic that were polished to have zero sharp edges. no they were ass

**Comment by SimplySmiley123** [comment]
> I feel it does not look better with windows, as they're still not topdown but rather pointing whichever way is 'in', leading to clashing but in a different way Besides that, it does look worse when put besides tables, chairs, consoles- really most of our objects which share a similar perspective. Given that's what I personally tend to use them for separating during gameplay, it feels especially off to me

To be honest the tall railings do screw with tables especially more then old railings.
Mostly by just, obscuring more of the table.

**Comment by MrMelbert** [comment]
I'm gonna DNM since I just think it's a downgrade but since it's technically in the spritetainer's realm they're free to overturn me

**Comment by Wallemations** [comment]
Yea no the pics you showed just look worse with the old sprites

**Pull request closed without merging**
