### PR TITLE
unpowered orm can be hit

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
Now unpowered ore redemption machine can be attacked.

## Why It's Good For The Game
Bugs bad

## Changelog
:cl:
fix: Now unpowered ore redemption machine can be attacked.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
attackby should be calling inher for signalling i'm pretty sure.

**Review by actioninja — APPROVED** [review]

**Comment by actioninja** [comment]
it could use further refactoring now that stuff like wrench_act and the like exists but a bug fix is still a bug fix.

**Comment by PKPenguin321** [comment]
bit late to this but i believe this has been a bug for at least 6 years so good job

**Comment by Dennok** [comment]
I memory as i try this do near 2 years before, and someone say "this need a refactor, not just bugfix"

**Pull request merged**
