### PR TITLE
Fixes slapper attack message

### LINKED ISSUE #32044: You slap Unknown in the r_arm!
1. *slap
2. aim at arm
3. You slap Unknown in the r_arm!

### PR DESCRIPTION
**Pull request by JJRcop**
Fixes #32044
Closes #32083

Don't merge this unless you decide that you don't want #32083

### CODE REVIEW

**Comment by praisenarsie** [comment]
REMOVE IT, DON'T FIX IT!

**Comment by praisenarsie** [comment]
https://i.imgur.com/PqcBmc2.png

REEEEEEEEEEEEEMOVEEEEEEEEEEE

**Comment by JJRcop** [comment]
@praisenarsie [
image
](https://github.com/tgstation/tgstation/pull/31406#event-1287203050)

**Review by Cyberboss — APPROVED** [review]

**Comment by JJRcop** [comment]
To be clear, wasn't trying to diss @Cyberboss, was showing the revert button, that @praisenarsie could click, if he wanted to.

**Comment by praisenarsie** [comment]
@JJRcop revert button does not work (for me at least)

**Comment by JJRcop** [comment]
#32083

**Comment by JJRcop** [comment]
I'm going to reopen this, while I personally prefer #32083, this is a second option

**Comment by deathride58** [comment]
Yeah, this is probably the better option of the two, since this doesn't restrict non-lethal slapping to just the face, and lets the intended behavior of being able to slap people in the chest persist while also removing groinslapping, an unintended behavior of the feature.

**Comment by JJRcop** [comment]
This doesn't remove groinslapping

**Pull request closed without merging**
