### PR TITLE
Adds a mute trait.

### PR DESCRIPTION
**Pull request by pireamaineach**
Adds a mute trait worth -1 points. Mainly that low because half of the station never talks anyway.

:cl:
add: Added mute trait worth -1 point.
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Mime mains are cheering quietly

**Comment by pireamaineach** [comment]
To be fair positive traits are mainly useless.

**Comment by PKPenguin321** [comment]
👎 
- shouldnt encourage this
- steps on the mimes gimmick

**Comment by pireamaineach** [comment]
Pretty sure the mime's gimmick is pantomime not being mute.

**Comment by PKPenguin321** [comment]
you're serious?

**Comment by pireamaineach** [comment]
Yes? While pantomime entails silence it doesn't mean mimes have a monopoly on the concept of not talking.

**Comment by RaveRadbury** [comment]
Mime buff

**Comment by MrPerson** [comment]
We shouldn't be encouraging being mute via mechanics. Being mute is boring and lame for everyone else.

Unless you're the mime, who should be required to have this trait because talking mimes are literally Genghis Hitler Bin Stalin.

**Comment by pireamaineach** [comment]
I mean what is any of the severe negative traits if not a detriment to the rest of the station.
We shouldn't encourage being a useless sec officer but people will still play paraplegic secies.

**Comment by Mickyan** [comment]
#39504

**Comment by pireamaineach** [comment]
Yeah but the reason oranges closed it is bullshit and I've already stated why in this thread. I hadn't seen this P.R. prior and this one'll probably get closed for the same reason even though it doesn't make any sense.

**Comment by RaveRadbury** [comment]
It makes sense. Mimes shouldn't be immune to tourettes and mute also makes the vow of silence pointless. Name a similar scenario where something like this is okay. The closest thing I can think of is a spiritual chaplain and that's a noticeably different situation.

**Comment by pireamaineach** [comment]
I don't think you actual read his reason for closing that P.R. because none of what you said logically supports it.

**Comment by RaveRadbury** [comment]
What I said falls under replacing job content, which you shouldn't do. So.

**Comment by pireamaineach** [comment]
Except how is this replacing job content? Again, mimes don't have a monopoly on the concept of being a mute.

**Comment by PKPenguin321** [comment]
because now his unique gimmick is much more commonplace and not unique. pantomiming might as well be synonymous with being mute in this game and claiming they're different is just facetious. that's all putting aside that you shouldn't encourage non-communicative behavior from players in the first place

**Comment by pireamaineach** [comment]
Most negative traits encourage poor behavior from players, as I've said.
PKPenguin saying someone's being facetious is one of the most ironic thinge I've seen in a while.

**Comment by RaveRadbury** [comment]
Either this is for mime and stepping on job content or its not for the mime and that makes it copy the mime. Pick one and lose anyway. The orangeman cometh.

**Comment by PKPenguin321** [comment]
>PKPenguin saying someone's being facetious is one of the most ironic thinge I've seen in a while.

scared?

**Comment by pireamaineach** [comment]
Solid false dichotomy.
It's meant to be a disability like any other, we have paraplegic yet we can't have mute characters arbitrarily because according you mimes have a monopoly on the concept of being mute.

**Comment by RaveRadbury** [comment]
The mime and clown represent opposite ends of the communication spectrum. Social anxiety is the closest any non-mime should come to being mute. Currently mutism is only available through a random trauma, being able to force it is clearly a bad idea.

**Comment by subject217** [comment]
oh boy time for mute paraplegic blind captains and hoses

**Comment by pireamaineach** [comment]
> The mime and clown represent opposite ends of the communication spectrum. Social anxiety is the closest any non-mime should come to being mute. Currently mutism is only available through a random trauma, being able to force it is clearly a bad idea.

Not really.
You're not providing any reason for this you're just stating it.
It's not clearly a bad idea. There is no reason why social anxiety should be the closest anyone comes to being mute. Mimes aren't even mute they just take a vow of silence. Those aren't even the same thing.

**Comment by RaveRadbury** [comment]
It seems pretty clear to everyone who has engaged this PR so far.

**Comment by pireamaineach** [comment]
Appeals to popularity are always the most sound arguments.

**Comment by RaveRadbury** [comment]
Good luck on getting this PR merged

**Comment by pireamaineach** [comment]
Oh I basically gave up when I saw that oranges closed a similar P.R.


All hail Orange man.

**Comment by pireamaineach** [comment]
I mean I got nothing but good reception in the discord but the GitHub is basically it's own environment so.

**Comment by necromanceranne** [comment]
I see no reason why mutism need be monopolized by mimes if, in turn, we consider adding sign language to mute and deaf players which can only be understood by others with those quirks, the curator and some quirk that adds it as a language known.

That way they actually have leeway to communicate nonverbally while the mime simply can't.

**Comment by pireamaineach** [comment]
If I was a better coder I might just see about that. 

Unfortunately I'm incompetent, who knew.

Uh... maybe sometime? I'd suggest it elsewhere though, sounds pretty lovely.

**Comment by pireamaineach** [comment]
Actually thinking about it I could probably copy+paste that together.

**Comment by necromanceranne** [comment]
Make sure that everyone else sees sign language as wingdings

**Comment by pireamaineach** [comment]
I could add a positive trait besides that they lets you know sign language, and additionally make it so that if a mime takes that trait it removes it round-start.

**Comment by optimumtact** [comment]
copies the mime -1 you shouldn't be replacing job content.

I'll be closing this at 24 hours


turns out my "bullshit" reasoning still applies, next time actually try arguing the point first, instead of acting like the world marches only on your logic and not mine.

**Comment by pireamaineach** [comment]
Yeah I've got no idea what you're getting at here I argued my case.

**Pull request closed without merging**
