### PR TITLE
Lower power generation from solars and pacmans

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Power generation has been all over the place, things that are means of emergency power can be used as "main engines"
Current solar power generation: 
-each solar panel can make a maximum of 1500 W
-this value is multiplied by a number between 0 and 1 based on the position of the sun
-at maximum power a cluster of solar panels (64 of them) will make almost 100 kW
-most stations have 4 of these clusters, meaning a total production of well over 300 kW and all of them have a SMES to store and release the energy.
Solars are capable of powering the station all by themself, rendering the SM totally useless.
Solar clusters now will produce a third of that amount, around 32 kW, meaning that they won't be enough to power the station, but contributing enough power for a lacking SM. (every solar panel will be reduced to 500 W)

Current pacman generation:
-at t1 they are able to make from 10 kW to 40 kW, quadruple that at t4 so from 40 kW to 160 kW. 
-a superpacman will produce from 30 kW to 120 kw at t1, from 120 kW to 480 kW at t4. 
These numbers are outrageously high coming from a piece of equipment made for emergencies and that can be easily bought from cargo at a low price of 1000 credits or build with a few pieces of stock parts.
Pacmans are now means to power a smal grid for power, or a small amount of APCs, not the whole station
Now pacmans will make power from 2.5 kW to 10 kW at t1 and from 5.5 kW to 22 kW at t4
and the superpacman will go from 7.5 kW to 30 kW at t1 and from 10.5 kW to 42 kW at t4
Now the tier will impact more what the consumption will be, more power = more consumption, more efficiency = less consumption, more power + more efficiency = they cancel each other (base level consumption)

## Why It's Good For The Game
Get the engineering gameplay more centered around learning and making the SM a better engine. 
Other means of power should not be able to produce much more than the base SM without effort, this also enforces the SM as the main engine that the station rely upon.

## Changelog

:cl:
balance: singular solar panel power production changed from 1500 to 500, clusters of panels of 64 (majority of stations) will make around 32 kW
balance: pacman power production has been lowered to make power in a range that goes from 2.5 kW to 10 kW at t1 and from 5.5 kW to 22 kW at t4
balance: superpacman power production has been lowered to make power in a range that goes from 7.5 kW to 30 kW at t1 and from 10.5 kW to 42 kW at t4
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
ahem... GHIIIIIIIIIIIIIIIIILKEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEER

**Comment by Dorsisdwarf** [comment]
What's the power draw of a roundstart station again? I was under the impression it was ~150-200KW but I'm not sure.

**Comment by newfren** [comment]
is the roundstart pacman still useful for starting the emitters with this change?

also, this makes low pop completely fucking miserable.

**Comment by Fryzzie** [comment]
Also, basic pacman not even able to power roundstart telecomms is pretty cringe

**Comment by DmitriyRubetskoy** [comment]
I don't particularly enjoy the new SM and I think you are biased due to reworking it.
Plus, this is effectively gutting options for power setup.
What if I **ENJOY** setting up power through solars more then SM for example? I like flying in EVA suit and wiring them.

**Comment by 81Denton** [comment]
>singular solar panel power production changed from 1500 to 500, clusters of panels of 64 (majority of stations) will make around 32 kW

I'm concerned that this will make solars completely unviable and further lead to shuttle calls when the engine isn't running or destroyed. And nobody ever uses shards to build an engine outside of maybe 0.5% of all green shifts.

**Comment by Ghilker** [comment]
> I'm concerned that this will make solars completely unviable and further lead to shuttle calls when the engine isn't running or destroyed. And nobody ever uses shards to build an engine outside of maybe 0.5% of all green shifts.

I did some tests on meta with full smes, wired solars and all light working and it took 35 minutes for the power to start to have issues, I could increase solars from 500 to 1000 and that should solve most of the concerns, if you really want

**Review by Kylerace — COMMENTED** [review]
the more i think about this the more i think that nerfing power generation before creating the targeted use for balanced power (eg the design docs that have been thrown around) is the wrong order, at least when said goal is as far as im aware nowhere near implemented.

**Comment by LemonInTheDark** [comment]
Good idea, we're not ready yet.

Solars should be enough to power a station at the bare level, so vents, low power lights, and some essential machines. Better for lowpop when there's less people online, or after the engine goes down.
Unfortunately we don't have support for something like that right now. Solars should be a low power backup, but like.
Right now we don't have non binary power. it's either on or off.

What I want is 

```
SM
--Fully operational station--
Solars
Pacman
Turbine
--Total power failure--
idk fucking tesla coils hooked up to a monkey with a jacket or something knock yourself out
```

But we don't have that level of control right now. So 

```
SM
Solars
Pacman
Turbine
--Fully operational station--
//Notice how there's no space here?
--Total power failure--
```

Seems like the best way to set things up. These tools should be enough to keep a bare station up in future, but we don't have that level of control, and I think it's best to err on the side of generosity rather then SM or nothing. I get the urge to force people to learn the sm, but I think most people know the default setup, and if people want to be lame and ignore the fucking lighting crystal in favor of a panel that's ok for now. We can force them to use it once the groundwork is in place, and the hell work has been done.

**Comment by Mothblocks** [comment]
Same thoughts as the above two, was waiting to hear more consensus

**Pull request closed without merging**
