### PR TITLE
Changeling power "Anatomic Panacea" removes zombie infections

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: The changeling power "Anatomic Panacea" now causes the changeling
to vomit out zombie infections, along with headslugs and xeno
infections, as before.
/:cl:

Closes #24063.

### CODE REVIEW

**Comment by lzimann** [comment]
Won't "Currently, you get the zombie revival message, but then nothing happens."(from the pr you are closing) still be an issue here?

**Comment by Cyberboss** [comment]
Shift+Home+Backspace

^

**Comment by coiax** [comment]
Probably should fix the bug then, rather than make a changeling test.

**Comment by ExcessiveUseOfCobblestone** [comment]
who the frick is planning on using romerol as a changeling test?

**Comment by coiax** [comment]
who would have thought that examining someone's brain after you decapitate them to see how "lifeless" it is would be used as a changeling test. And people did...

**Comment by PKPenguin321** [comment]
Implying hitting somebody until their head pops off is as hard as acquiring romerol

**Comment by ExcessiveUseOfCobblestone** [comment]
but that's not using romerol, something you only get on clearance or with traitor help, as a tester. That's just obvious examine text.

**Pull request merged**
