### PR TITLE
testmerge this

### PR DESCRIPTION
**Pull request by LemonInTheDark**
If you merge this I will beat you up

### CODE REVIEW

**Comment by Fikou** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by LemonInTheDark** [comment]
No

**Comment by optimumtact** [comment]
this is a long shot theory of bargaining that this might fix reconnection not working

**Comment by JenqaDev** [comment]
oh god yes please i hope this fixes it since i need to leave the game and rejoin and by the time my byond decides to open the game and not lose connection magically the round has started already

**Comment by Cyberboss** [comment]
Conflicts and affecting my blessed PR count

**Pull request closed without merging**
