### PR TITLE
Adds a missing experimentor to icebox

### PR DESCRIPTION
**Pull request by Boopideedoo**
## About The Pull Request
This pull request adds a experimentor to icebox.dmm 
## Why It's Good For The Game
This makes it so we dont have to keep building it every time we play on icebox and it also follows a style with other maps having it already
## Changelog
:cl:
fix: Added E.X.P.E.R.I.M.E.N.T.O.R
/:cl:

### CODE REVIEW

**Comment by Boopideedoo** [comment]
Just a small map fix

**Comment by Boopideedoo** [comment]
if it isnt good in the current area I can just make a new area for it and commit to this same pr

**Comment by MMMiracles** [comment]
the experimentor is a bit depreciated at this point but we still have it mapped in so it probably doesn't hurt to actually keep some department consistency until someone actually takes it out back and properly puts it down for good

image
fix the floating camera and ideally move the lighting fixture off the window and this should be good to merge

**Comment by Boopideedoo** [comment]
Ok I can do that and rework an area for it after

**Comment by Boopideedoo** [comment]
> not gonna like, this looks kinda ugly.
> 
> image
> 
> * r-windows for walls is never clean or nice looking
> * random gap of un-reinforced walls
> * windoor has no name or access requirements
> * light on window
> * floating camera
> 
> it really doesn't fit in, it'd be preferable to move it back into the test chamber like in your original commit.

I followed some of your advice to help make it look better and Ill be working on improving it further to make it work in the area I put it unless you want me to make a new area for it

**Comment by Boopideedoo** [comment]
For the windoor without a name I generated icon directions for the one named research

**Comment by Helg2** [comment]
Not an expert, but wont it be better if you'll put experimentor just in that room?
image
There isnt quite anything and i never saw anyone using it for scientific purposes.

**Comment by Boopideedoo** [comment]
> Few things to note:
> 
> * Access helpers for airlocks don't work on windoors currently (they specifically check for '_obj/machinery/door/airlock/airlock_'), even if they did the current one you placed would throw an error since the 'req_access' variable is already defined on the door. You can actually see this caused your PR to fail a check (the access helper you placed can't find an airlock on the turf, so it creates an error message about it needing resolved).
> * The access type on the windoor you used from another area has the '_req_access_' set to "xenobiology", so currently only people with that access can open it. Roundstart scientists won't notice the issue but if someone gets general science access assigned to them they'll be confused why this particular windoor doesn't work for them despite everything else in the room being fine.
> * You left the gap of regular walls behind the room. This doesn't look great in-game and also leaves a vulnerable spot into the department where there usually isn't. This needs patched up with reinforced walls.
> * Please try to use the directional variants for stuff when available, I know you saw that plenty of them already don't do this but we should probably be enforcing this more.  Please use the 'north' variant of the windoor and change the '_req_access_' variable to "research" so it won't be something that'll need cleaned up in the future.
> 
> There's a lot of little things to mapping but most of it gets figured out with practice and unit tests usually catch the big issues.
> 
> While you're already here could you like place a single scrubber pipe there because currently the lab's scrubber isn't actually connected to waste and it's apparently been like that for a minute. image

Yea I can fix that and the walls sorry ive been inactive I was busy with some stuff I was fixing on another codebase

**Comment by Boopideedoo** [comment]
Still working on the area I made for it so for now Im just putting the experimentor in testing chambers

**Comment by Boopideedoo** [comment]
image2
image

**Comment by Boopideedoo** [comment]
Fixed that for ya The scrubbers

**Pull request merged**
