### PR TITLE
Roundstart sound refactor

### PR DESCRIPTION
**Pull request by ghost**
Roundstart sounds are now loaded from `strings/round_start_sounds.txt`.

### CODE REVIEW

**Comment by Cyberboss** [comment]
>4

Absolute madman

**Comment by AnonymousNow** [comment]
Nice!

Can we sneak Guardians in there, or is there no point?

**Comment by Xhuis** [comment]
It's one of the longest in the set so I decided not to.

**Comment by chanoc1** [comment]
i feel like this could get annoying fast... is it a random chance?

**Comment by KorPhaeron** [comment]
License memes

**Comment by Xhuis** [comment]
👏

**Comment by chanoc1** [comment]
o-oh.

**Comment by AnonymousNow** [comment]
Is Leslie Fish's old stuff still an issue? After all, d20 has Guardians as a roundstart tune.

Remember: we still have xenomorphs.

**Comment by Xhuis** [comment]
There's no license questions about this, we're good.

1. The single _Carmen Miranda's Ghost_ came from a singer by the name of [Leslie Fish](https://en.wikipedia.org/wiki/Leslie_Fish)
2. The single inspired a [collection of short stories](https://www.amazon.com/Carmen-Mirandas-Ghost-Haunting-Station/dp/0671698648) by independent authors
3. The music... seems to have no ties, really. It might be inspired, but the only source that I can find details it as coming from "a box of tapes sent to me by user mulewagon", so I imagine it came from people who were inspired by the short stories to write some loosely-based "star shanties".

**Comment by PKPenguin321** [comment]
I feel like these songs might get kind of obnoxious, they're less background-y than our other lobby themes

**Comment by AnonymousNow** [comment]
We currently have The Room. For some reason.

**Comment by chanoc1** [comment]
uhhhhh

**Comment by Niknakflak** [comment]
These sound like shit.  Any lobby music that has voice/words triggers me.  Lobby music memes have to stop.  The room itself is a shitty lobby music.  They don't sound very spacey or atmosphericy to me either and I don't know how you are trying to say "grunchy sea shantys" sound like "wacky future retro space station".

**Comment by AnonymousNow** [comment]
So The Room sneaks in, but actual filk music triggers people? This is Leslie bloody Fish - I'm not sure SS13 could've existed without the imagery dreamt up in Banned From Argo or The Good Ship Manatee. I don't see how it's possible to hear this music and not think of adventures and hijinks in space.

**Comment by KorPhaeron** [comment]
@AnonymousNow 

Don't use bad changes to justify more bad changes that doesn't make any sense at all

**Comment by Cyberboss** [comment]
On that note how the fuck did the room get merged in the first place?

**Comment by AnonymousNow** [comment]
This change makes perfect sense. Filk about space adventures and hijinks. Don't pretend that they're not relevant.

**Comment by chanoc1** [comment]
vocals get out ree

**Comment by optimumtact** [comment]
Remove the room music and these, frankly

**Comment by Xhuis** [comment]
Well, these are controversial, to say the least, so I'll cut them out. I will be keeping the refactor though, because it's handy.

**Comment by AnturK** [comment]
Once again, server based sounds, purge the codebase.

**Comment by Iamgoofball** [comment]
Don't remove the room :(

**Comment by AnonymousNow** [comment]
This music is the most SS13 thing there is.

I'm bitterly disappointed in all of you.

**Comment by PKPenguin321** [comment]
Yeah but it's not background music like the rest of it, which doesn't really match a lobby imo

**Comment by Xhuis** [comment]
It's a feelsbadman for sure, but I respect the majority's wishes.
This is merge-ready now, and there's no reason not to merge it as it's just a refactor now.

**Comment by Xhuis** [comment]
Again, this is merge-ready. The DNM tag isn't necessary anymore, and it's not WIP. There are no more sounds included, just the refactor.

**Comment by AnonymousNow** [comment]
I hope we'll readd fun soon.

**Comment by AnonymousNow** [comment]
Can we remove The Room while we're at it? It's jarring every time I hear it.

**Comment by chanoc1** [comment]
no. its very calm and soothing... unlike this

**Comment by MimicFaux** [comment]
I'm a huge fan of all the songs listed, especially the ones with vocals :/
Surprised to hear this much controversy over it. I mean, there's always the option to toggle your own sounds off. I think a server poll would be most appropriate than just the opinions of those who visit github

**Pull request merged**
