### PR TITLE
Adds Viral adaptation and evolution

### PR DESCRIPTION
**Pull request by LanCartwright**
Viral adaptation increases stealth and resistance, decreasing stage speed.
Evolution is the opposite, and increases stage speed and transmittance, but reduces stealth and resistance.

### CODE REVIEW

**Comment by Buggy123** [comment]
:+1:

**Comment by AlexCrimson** [comment]
self-adaptation seems like an insanely strong symptom. Especially when most of the stealth symptoms currently used are pretty shit. With this new one you can make a deadly airborne stealth virus that has no negative stats and 9+ Resistance.

**Comment by LanCartwright** [comment]
name = "Eternal Youth"
	stealth = 3
	resistance = 4
	stage_speed = 4
	transmittable = -4

It's very strong, but there are a lack of substitutes or compliments for a booster virus except for say, Eternal Youth and some shitty symptoms.

**Comment by AlexCrimson** [comment]
Well you dont really bother making a stealth virus unless you have Eternal Youth. Its pretty much required. This new symptom will be required as well, because its so good.

**Pull request merged**
