### PR TITLE
Renames Holoparasites to Nanoswarms

### PR DESCRIPTION
**Pull request by ghost**
@KorPhaeron

Also adds spans and tweaks the messages of success, attempt, and failure messages. The scarab egg cluster now has the spider eggs icon instead of the combat hypo icon. Two new colors have been added to nanoswarms as well: white and black.

### CODE REVIEW

**Comment by Firecage** [comment]
....Xhuis, did you have to use a very obvious reference for the name?

That aside, while I dislike holoparasite, this name just feels awkward.

**Comment by Xhuis** [comment]
This was a reference?

**Comment by Miauw62** [comment]
the sprites for these things make them look like cult stuff, really
confusing

**Comment by Lumipharon** [comment]
WHO'S THAT POKEMON?

http://bulbapedia.bulbagarden.net/wiki/Zygarde_%28Pok%C3%A9mon%29

**Comment by SconesC** [comment]
hard light holograms are a concept not a reference last i checked idk

**Comment by KorPhaeron** [comment]
I'd prefer them to be renamed "Guardian Nanoswarm" or "Guardian Nanites" in the uplink, and have the mob name just be "Guardian [colour]" to keep consistency between the ghost and tech variants.

Also I'd rather the fluff stay that they're alien nanites or whatever. Hard Light Hologram Pink would be a mouthful.

**Comment by Xhuis** [comment]
I'll change 'em to Nanoswarms.

**Comment by Lumipharon** [comment]
They also seem awfully high tech, considering the syndicate aren't even able to make their own AI's or borgs, yet they can make sentinent, parasitic nanomachines?

**Comment by Xhuis** [comment]
@Lumipharon They can easily make their own AI and cyborgs. See: traitor AIs, syndiborgs...

**Comment by KorPhaeron** [comment]
@Lumipharon 

That's why they're an alien parasite/symbiote, not something the syndicate made.

**Comment by Xhuis** [comment]
I renamed them to (guardian) nanoswarms.

**Comment by Lumipharon** [comment]
@Xhuis Fluf of traitor is shipping a prehacked AI to the station, not their actual own build.

Syndie borg fluff explicitly says it's a reconstructed NT borg with syndie shit stuck on.

**Comment by SconesC** [comment]
this is tg

how can we seriously try and use lore as a legitimate justification

**Comment by Bawhoppen** [comment]
@SconesC scones, maybe we should try and fix tg so it IS legitimate justification

**Comment by RemieRichards** [comment]
@Xhuis Traitor AI and Traitor Borgs are stolen, that's always been the lore, they take NT tech (which the lore still calls "experimental") and adapt it.

**Comment by Dorsisdwarf** [comment]
Just like jetpacks and magboots.

**Comment by Lumipharon** [comment]
Jetpacks have never made sense because it's literally just a tube of gas with a nozzle.
Mag boots were added by Paprika, and his fluff logic was the mag boots used by ops were the ones stolen by tators. "They gotta have some use for all those mag boots they steal" I think was exactly what he said.

**Comment by RemieRichards** [comment]
there you go then, we're still somehow following the very loose lore we very rarely follow.
10/10 grats everyone lets go get cookies.

**Comment by Lumipharon** [comment]
This is still just an issue about the fluff, not the gameplay btw.
I still don't know how the syndie has these, since NT doesn't have them to steal off either.

**Comment by Xhuis** [comment]
It's up to KorPhaeron, not me. He's the one who made these. Fluff-wise, I'm guessing that the Syndicate stumbles upon these nanomachines and started giving them out to agents to find out how they can be utilized.

**Comment by Xhuis** [comment]
fuck

**Comment by Shapsy** [comment]
Holoparasite actually kinda grew on me though, makes it sound nasty and destructive

**Comment by Xhuis** [comment]
Me too, but Kor wanted it renamed and he made them, so vOv

**Comment by KorPhaeron** [comment]
Vote on sybil just now was deadsplit between parasite and guardian, I don't know what to do anymore

**Comment by Lumipharon** [comment]
guardian parasite

**Comment by Ricotez** [comment]
much preferred to holoparasite, the holo part implies the thing is just an illusion

would an illusion be able to beat you the fuck up?

**Comment by RemieRichards** [comment]
@Ricotez if it was Hard-light, frequently (incorrectly) referred to as Hard-light holograms, then yes!

**Comment by Razharas** [comment]
Im not englishg so someone english please confirm the right

**Comment by KorPhaeron** [comment]
@Razharas 

I'd prefer you held off merging this since apparently there is some love for calling them parasites after all.

Certainly sounds more evil anyway.

**Comment by Xhuis** [comment]
Sounds like we're okay with calling 'em holoparasites. I'll close this PR unless @KorPhaeron asks me to re-open it.

**Comment by KorPhaeron** [comment]
@Xhuis 

Should send me the sprites or put them in another PR then, more colours is always good

**Pull request closed without merging**
