### PR TITLE
janitor sprite tweaks

### PR DESCRIPTION
**Pull request by L0pz**
## About The Pull Request
Tweaked some of the janitor's tools and made what I *THINK* is an improvement
image
image
image
image
## Why It's Good For The Game
People like better sprites

## Changelog
:cl:
image: tweaked some janitor tool sprites
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
I'm confused of the perspective on the light replacer, specifically the little claw parts at the top in relation to the rest of the body. 
Additionally the yellow section feels a little off for a modernized sprite, did you not add hue-shifting to the shaded part?

**Comment by L0pz** [comment]
> I'm confused of the perspective on the light replacer, specifically the little claw parts at the top in relation to the rest of the body. Additionally the yellow section feels a little off for a modernized sprite, did you not add hue-shifting to the shaded part?

Sorry for the late reply. I don't usually add tints to sprites that just use shades of black but I could try doing it if you think it'll be better

**Comment by Wallemations** [comment]
> Sorry for the late reply. I don't usually add tints to sprites that just use shades of black but I could try doing it if you think it'll be better 

Not the black, the yellow.

**Comment by Wallemations** [comment]
Hell that yogstation PR actually kinda fixed the issue I had with it

**Comment by AMyriad** [comment]
> Hell that yogstation PR actually kinda fixed the issue I had with it

image

**Comment by notfrying1pans** [comment]
this doesn't touch the bluespace light replacer sprite

**Pull request closed without merging**
