### PR TITLE
Fixes stacks and material containers, fixes wet floors

### LINKED ISSUE #34839: Lavaland clown ruin floors aren't lubed
Issue: The lavaland clown ruin floors aren't slippery. You can just enter, walk to the trophy room and stroll out.

Expected result: The floors are supposed to be slippery as if covered in space lube, forcing you to slip from wall to wall to get to the trophy room.

### PR DESCRIPTION
**Pull request by silicons**
Fixes #34839

### CODE REVIEW

**Comment by 81Denton** [comment]
Wish I could see the look on the face of the first person to enter the clown arena after this gets merged.

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by AlexTheSysop42** [comment]
>Wish I could see the look on the face of the first person to enter the clown arena after this gets merged.

crowbar

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by ShizCalev** [comment]
#34839?

**Comment by kevinz000** [comment]
@ShizCalev this will fix that

**Pull request merged**
