### PR TITLE
Makes the station more colorful...

### PR DESCRIPTION
**Pull request by Mickyan**
...on april fools, and adds a randomly colored tile subtype for mapping

## Changelog
:cl:
tweak: Due to a new clause in the Crew Satisfaction Program, the clown has been given full control over station decorations during April Fools
tweak: Added randomly colored tile decals for mapping
/:cl:

Screenshot_6

### CODE REVIEW

**Comment by trollbreeder** [comment]
Make all the plasteel floors turn into a random subvariant upon initialize

**Comment by EOBGames** [comment]
I give this my full support, and suggest a speedmerge pronto.

**Comment by optimumtact** [comment]
If you checked for the april fools event, this could even be mergeable assuming it doesn't cause other issues.

**Comment by Pumpkinoe** [comment]
beautiful

**Comment by Twaticus** [comment]
damn can we add this for easter event aswell its very pleasing to look at

**Comment by Mickyan** [comment]
AnturK was interested in having this as a random roundstart scenario, you should nag at him about making that system 😎

**Comment by cacogen** [comment]
delicious pastels

**Comment by Pugie** [comment]
Why is this still merged

**Comment by optimumtact** [comment]
it is permanently merged, and only appears during the easter event.

**Comment by Pugie** [comment]
> it is permanently merged, and only appears during the easter event.

Ah ok, cool thanks tangerineman.

**Pull request merged**
