### PR TITLE
Purges mime of clown influence

### LINKED ISSUE #11794: Mimes start with a bike horn and clown crayons.
This upsets the balance of the universe.

suspect related to https://github.com/tgstation/-tg-station/issues/11788

### LINKED ISSUE #11812: RD starts with medical backpack
Title. Dunno why but he does.

### LINKED ISSUE #11835: outfit datums tryint to create null objects!
@AnturK 
The following runtime has occured 2 time(s).
runtime error: Cannot create objects of type null.
proc name: post equip (/datum/outfit/job/security/post_equip)
  source file: security.dm,250
  usr: null
  src: Security Officer (/datum/outfit/job/security)

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #11794 

Also Fixes #11812 

Fixes #11835

### CODE REVIEW

**Comment by Chocobro** [comment]
rip mimexclown mind break erotic fiction

**Comment by bgobandit** [comment]
don't you mean

mime break

**Comment by Xhuis** [comment]
# ___AYYYYYYYYYYYYY___

**Comment by AnturK** [comment]
Ugh. Github online editor added newline

**Pull request merged**
