### PR TITLE
Resprites the butcher's cleaver!

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR resprites the butchers cleaver.

UPDATE: Now with new sprite. 

image

It also removes an old unused sprite.

## Why It's Good For The Game

The old sprite is very dull looking(lacking metallic shine) and is lit weirdly.

## Changelog
:cl:
imageadd: The butcher's cleaver has a new  sprite.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
only the most epic of gamers will make 4 prs that will conflict himself for 3 extra GBP

**Comment by rellyreri** [comment]
it looks too thick

**Comment by ShibaInuLord** [comment]
I like the other 3 sprites but this one just feels odd for some reason to me

**Comment by wesoda25** [comment]
Decrease the incline or lengthen the blade maybe?

**Comment by Serxule** [comment]
like i said before on the discord (and i think others agree with) is that it looks too thick and seems like an axe more than a cleaver.

**Comment by Dorsisdwarf** [comment]
Doesn't look like a real cleaver, way too stubby and somehow looks less well lit.


The handle is great though

**Comment by cacogen** [comment]
I also like the handle, but cleavers are [more rectangular](https://www.google.com/search?q=cleaver&newwindow=1&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjv2rn71ZzvAhVHyDgGHYJ1DBAQ_AUoAXoECBQQAw&biw=1716&bih=897). The border pixels seem to stand out a lot too. Too much contrast, I think.

**Comment by Krysonism** [comment]
> I like the other 3 sprites but this one just feels odd for some reason to me, I think it's the blade shading, with the sharp edge being black



> Doesn't look like a real cleaver, way too stubby and somehow looks less well lit.

>I think it's the blade shading, with the sharp edge being black

The edge would be darker unless it was lit from below, no?

>but cleavers are more rectangular.

since the sprite is 32px wide, I have to make the handle shorter if I want to make the blade longer.

I personally like this sprite and much prefer it to the alternative. But I will make a version with a slightly longer blade for your consideration.

**Comment by ShibaInuLord** [comment]
> The edge would be darker unless it was lit from below, no?

I think some/most cleavers are just coloured lighter on the sharp edge, not related to where light hits the blade.

**Comment by Krysonism** [comment]
image

Surely one of these must be satisfactory.

**Comment by cacogen** [comment]
It definitely looks better with a more rectangular blade. I like the coarseness of the metal too. I'm not sure which one I like the most. The one on the top right has the most character, but the one on the top left looks like you wouldn't get sick of looking at it.

**Comment by Krysonism** [comment]
I am personally leaning towards top left.

**Comment by Krysonism** [comment]
> 
> 
> I like the other 3 sprites but this one just feels odd for some reason to me, I think it's the blade shading, with the sharp edge being black

Since everyone keeps insisting the edge be lit from below. Here is that what that would look like.

image

**Comment by cacogen** [comment]
That looks strange. The cleavers on the image search page seem to have a blade that looks darker than the rest of the head.

I don't want to complain too much but I wish  your newest sprite had your original sprite's handle while keeping the new blade and the entire thing was just smaller to fit the canvas. The sprite you're replacing was better in terms of size and proportion.

**Comment by Krysonism** [comment]
> 
> 
> That looks strange. The cleavers on the image search page seem to have a blade that looks darker than the rest of the head.

It depends on how the edge is lit, i've had so many people complain the edge was dark, so i decided to backlight it. Now

> I don't want to complain too much but I wish your newest sprite had your original sprite's handle while keeping the new blade and the entire thing was just smaller to fit the canvas. The sprite you're replacing was better in terms of size and proportion.

I think this one is better proportioned if we are talking blade vs handle size.

I am waiting for input from our head spriter now.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
