### PR TITLE
Adds the EXPERI-MENTOR to the tgstation.2.1.3.dmm map. (#6797)

### PR DESCRIPTION
**Pull request by sawu-tg**
Optional Merge, discuss it and merge if everyone wants it.

UPDATE: DA and Experimentor placed together:
newroom

### CODE REVIEW

**Comment by dannno** [comment]
what is it

**Comment by AlexCrimson** [comment]
As i understand it, the "EXPERIMENTOR" hasnt even been on the server for long. Rather than replacing the Analyzer with something so new, how about we wait for people to play with it first? Maybe for now just add the new machine to R&D without removing the old analyzer.

**Comment by sawu-tg** [comment]
@dannno @AlexCrimson It's worth reading #6797

**Comment by paprka** [comment]
yolo

**Comment by Ergovisavi** [comment]
It's basically a more RNG-Y Destructive analyzer, with some neater effects.

Like turning a capacitor into space milk... confused the hell out of me when that happened during testing.

**Comment by AlexCrimson** [comment]
Yeah ive read it. Im just saying that replacing the Analyzer with this new machine when the playerbase hasnt even had time to play with it is jumping the gun. Lots of people who play Scientist are going to be confused.

**Comment by Steelpoint** [comment]
Place it next to or near the current DA machine so we can get a feel for both machines.

**Comment by sawu-tg** [comment]
[Click here for the guide](https://dl.dropboxusercontent.com/u/1513925/ss13/using_the_experimentor.txt)

**Comment by Ergovisavi** [comment]
>Place it next to or near the current DA machine so we can get a feel for both machines.

The problem with this is that the experimentor is inherently less useful than the DA, because it has RNG elements. It's like comparing the disabler and tasers, the disabler is inherently useless in comparison and is painted in a bad light simply because the taser exists.

I don't care on this either way, but you shouldn't attempt a bad experiment like that.

**Comment by dannno** [comment]
It sounds fun, but I'm not sure how I feel about it replacing the DA.

**Comment by GunHog** [comment]
It is far too early to do this. :-1: If the device is not fun or is not seen as better than the DA, then this will only be seen as a nerf. If this machine is akin to the taser vs. the disabler, then it will not be wanted. However, if it as seen as an energy gun (pre-nerf) vs an advanced energy gun, then things are a bit more interesting. Instead of a nerf, you get something with greater potential at the cost of being dangerous.

There has to be something to make this machine worth using over the DA, else it will just be something that slows down Science and gets the scientists killed on occasion.

**Comment by sawu-tg** [comment]
@GunHog This has a few reasons it's more "powerful" than the DA.

It has a % chance to not destroy items you research, meaning you could potentially get higher levels per item (I.E a bluespace 6 tech origin item would give you +1 under 6 on the DA, and then gets destroyed, however on this, should RND favour you, you could go from 1 - 6 bluespace on one item).

It also has a % chance to transform items, which can be used to obtain higher level items (occasionally).

Also, any objects obliterated will transfer their materials to a nearby lathe.

The last two give it a lot more long-term usability than the DA, because even if you have reached your maximum research, you can continue to transform items or recycle them.

**Comment by MrPerson** [comment]
Where does all this destructive analyzer love come from? I thought we were all in agreement that it's total crap?

**Comment by Anonus** [comment]
It's total crap, but it's reliable total crap that lets science get stuff quickly.
People want to keep it because it's reliable and won't kill them, even though it's total crap from a design standpoint.

**Comment by Anonus** [comment]
Don't actually keep the destructive analyzer though it's awful

**Comment by paprka** [comment]
Remember science isn't about research it's about reading a guide on how to max the levels in research to get shitty powergamer toys

**Comment by sawu-tg** [comment]
@Anonus @MrPerson @GunHog The general consensus seems to be "The DA is shit, but I don't want it to be removed because then there wouldn't be an easy research method."

I've put both in so we can perhaps do a "test" run to see what people want to use more. Either that or everyone needs to make up their mind.

**Comment by tkdrg** [comment]
People will use the DA because it's easy mode. There is no point in keeping both. Either we kill the DA or the Experimentor will never be used.

**Comment by sawu-tg** [comment]
See #6914, It obsoletes this.

**Pull request closed without merging**
