### PR TITLE
removes stun batons in order to usher in the glorious era of security just fucking murdering criminals

### PR DESCRIPTION
**Pull request by nianjiilical**
## About The Pull Request

replaces stun batons with electro knives. electro knives can do a single very short stun at the cost of all their battery charge. also they have 20 force so you can lacerate the illegal immigrant afterwards. this also applies to improvised stun prods

also replaces police batons with police batons but they have knifes on the end, telescopic batons with telescopic knives, and boomerangs with boomerangs that have no stun chance but do a shitload of damage

## Why It's Good For The Game

it's probably not but oranges keeps saying he wants stuns gone and i think it would be very funny to test merge this and call it a social experiment

## Changelog
:cl:
del: removed batongs
add: security now gets sharpned electro knifes to stab the criminals
add: boomerangs now violate the geneva convention, probably
/:cl:

### CODE REVIEW

**Comment by Kylerace** [comment]
huge gameplay change with negative gbp, weak justification. come back later

**Comment by LemonInTheDark** [comment]
image
image

Go away admin scum

**Comment by nianjiilical** [comment]
> image
> image
> 
> Go away admin scum

i cant believe byond is conspiring to break my extremely well thought out balance decisions

**Comment by LemonInTheDark** [comment]
You're right, this interaction was a waste of compute cycles

**Pull request closed without merging**
