### PR TITLE
Some talking toys now audibly chatter - Now without shitty references!

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: coiax, Nienhaus
rscdel: Unfortunately, the Belowyarn toys have been withdrawn from distribution
due to Assistants choking on the batteries. Centcom has sent their
condolences to the battery manufacturing plant.
rscadd: We are introducing Oh-cee the original content skeleton figurines.
Pull its string, and hear it say a variety of original phrases. Not suitable for
infants or assistants under 36 months.
tweak: Note that pulling the string of all talking toys is now visible
to others.
rscadd: Talking toys produce a lot more chatter than they did before. So do some skeleton "tongues".
/:cl:

With thanks to Nienhaus for doing the sprite.

The toy AI has also been made a "talking" toy because it works the same as the others.
chatter() is a global proc, not limited to just talking action figures
EDIT:

The Journey of this PR
- PR creator bundles it with a shitton of crappy undertale references
- We tell him to remove it
- He refuses
- He whines when he gets a Universally Disliked tag
- Tries the "maybe if I rename the PR people will think its something else" trick
- I re-open his PR without the shitty undertale references
- 10/10 would coderbus again

### CODE REVIEW

**Comment by Bawhoppen** [comment]
what is this pr I don't get it

**Comment by Iamgoofball** [comment]
It's the skeleton toy PR without the shitty undertale memes

**Comment by Bawhoppen** [comment]
isn't that literally the entire point of the skeleton toy

**Comment by Iamgoofball** [comment]
no, he's bundling a really good overhaul to how talking toys work with his shitty skeleton so I'm making a competiton PR

**Comment by Archie700** [comment]
Why not just seperate it

**Comment by Iamgoofball** [comment]
exactly, he's refusing to so instead I'm forking the PR and removing the lines myself

**Comment by Iamgoofball** [comment]
what the fuck

i'll make a followup to remove his skeleton then if you're gonna pull this shit

**Comment by KorPhaeron** [comment]
Why was this closed?

**Pull request closed without merging**
