### PR TITLE
Adds ether

### PR DESCRIPTION
**Pull request by pudl**
Ether is a chemical ported from Goonstation that functions identically to morphine, minus the speed. I don't know who to give credit to for making it, but thank you to Marquesas for giving me permission to implement it. If I were to guess who added it, it would be SpyGuy, because Cogwerks is currently very very busy.

Ether is created with sacid, ethanol, and oxygen.

All instances where morphine was used for its sleep inducing properties have been replaced with ether. To name them, sleepers, reishi, spiders, bioterror ammo, and sleepy pens.

An ether pill has been added for future convenience to mappers and coders.

### CODE REVIEW

**Comment by Incoming5643** [comment]
seems like a good candidate for a blob chem :hankey:

**Comment by Iamgoofball** [comment]
:+1:

**Comment by WJohn** [comment]
Sleepy pens are gonna be really slow to act, aren't they? If they still have the tiny prick message, it really should be removed since you'll probably have even longer.

**Comment by pudl** [comment]
@WJohn There will be no difference in speed.

**Comment by pudl** [comment]
Alright, Ikarrus' gang prs have caused conflicts twice, no ether for anyone. I hope goof adds it!

**Comment by Iamgoofball** [comment]
@pudl you do realize fixing conflicts is easy as shit right

**Comment by pudl** [comment]
@Iamgoofball Don't care.

**Comment by Iamgoofball** [comment]
@pudl why

**Comment by pudl** [comment]
@Iamgoofball Because I'm butthurt, duh.

**Pull request closed without merging**
