### PR TITLE
Nerfs sandbag health

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Reduced sandbag health from 280 to 200.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
what why? they need to be strong or else they're worthless

**Comment by ChangelingRain** [comment]
Miners are abusing the shit out of them because mobs can't path through them and have to attack them

**Comment by Bawhoppen** [comment]
thats the whole point? maybe we could make mobs like try to properly climb over them and such? or make an object based damage number different than their damage they do to mobs

**Comment by YakumoChen** [comment]
unless it can be used to kill megafauna (and from what I'm aware most of them can just wallhop anyway) I don't see a purpose for this.

**Pull request closed without merging**
