### PR TITLE
Glowing goo glows green

### PR DESCRIPTION
**Pull request by coiax**

### CODE REVIEW

**Comment by Kraseo** [comment]
funny guy

**Comment by coiax** [comment]
not everything is about you

**Comment by Kraseo** [comment]
gonna make light tubes/bulbs an eyesearing yellow next dude?

**Comment by Xhuis** [comment]
Tbh that would be kind of cool

**Comment by octareenroon91** [comment]
Anyone want me to port over my "paint light fixtures for colored light" patch?

**Comment by coiax** [comment]
I'm already working on refactoring light fixtures right now

**Comment by WJohn** [comment]
I think tubes should remain white, but bulbs being sorta yellow would be really nice.

**Comment by MrPerson** [comment]
Finally, the one colored light source even the grogiest of grognards can't complain about

**Comment by octareenroon91** [comment]
This would seem to give a reason to splash radium on the floor. Sound fun?

**Pull request merged**
