### PR TITLE
Revert "CentCom Galactic Ban DB"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#52519

Apologies @Cyberboss I should have marked this DNM, but it needs explicit signoff from headadmins and mso.

### CODE REVIEW

**Comment by ike709** [comment]
wew lad

**Comment by ike709** [comment]
Instead of this dance of merge, revert, revert the revert if they approve it... why not just leave the config disabled and not merge the revert until if/when they disapprove of it?

**Comment by optimumtact** [comment]
Because that might be seen as influencing the outcome, which I have no intention of doing

**Comment by ike709** [comment]
@MrStonedOne https://github.com/bobbahbrown/CentCom Your concerns have been addressed.

**Comment by ike709** [comment]
😢

**Pull request merged**
