### PR TITLE
Completing experiments after their associated nodes have been researched gives back a partial refund of the discount lost

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

So we're like simultaneously moving two vague directions with research. One being "experisci grants discounts for prohibitively expensive nodes so you want to do the experiments to discount them" and the other being "Let's give Heads of Staff a way to research anything they want without any communication to the research department, including the very expensive nodes that scientists may be working on" 

You already see the issue, right? You can't have your cake and eat it too.

It sucks for scientists to be working on a complex experiment like weapons tech for that huge 90% discount only for the HoS to stumble onto the bridge and research it anyways. Your time is wasted and RND is slowed down massively. 

We can do something to assuage that.

This PR makes it so completing an experiment which discounts already completed nodes will refund a partial amount of the discount that would've applied.

For example, researching industrial engineering without scanning the iron toilets will refund ~5000 points. 

This can only apply once per experiment, so if an experiment discounts multiple technologies, they will only get a refund based on the first technology researched. 

## Why It's Good For The Game

This accomplishes the following: 

- Expensive research nodes with difficult experiments remain expensive without completing the experiments. If no one does the experiment, they act the same as before. 
- Expensive research nodes with very easy experiments (but time consuming) no longer put RND on a time crunch to beat the itchy trigger finger of the Heads of Staff. Stuff like scanning lathes allow the scientists to work more at their own pace: they can talk to people or maybe stop at the bar or kitchen between departments without feeling pressure to get it done urgently. 
- Scientists are able to complete experiments which previously were no longer deemed relevant if they need a point injection. Experiments left behind are no longer completely useless bricks. Maybe even gives latejoin scientists something to do.
- Scientists mid experiment can still complete it to not feel like their time is wasted. 

Overall I think this has many benefits to the current science system where many have complaints.

## Changelog

:cl: Melbert
qol: Completing an experiment which discounts a researched tech node will give a partial refund of the discount lost. For example, researching the industrial engineering research without scanning iron toilets will refund ~5000 points if you complete it afterwards. This only applies once per experiment, so experiments which discount multiple nodes only refund the first researched.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I think if the UI indicated in some manner which research nodes people currently have selected in the experimentor that would be helpful too but that's not an essential addon to _this_ PR.

**Comment by Sealed101** [comment]
> For example, researching industrial engineering without scanning the iron toilets will refund ~5000 points.

doing this should gib the sinner

**Comment by VladinXXV** [comment]
> I wanted to go the other way and remove experiments that had their node researched already, once t3-t4 microlaser experiment is done, it's already a hastle to go back to t2, find unupgraded machines, upgrade them with only t2, and scan them, I also don't see why they should get any research points for doing it. I would like this if it was limited to experiments that are already in progress so you're not punished for starting them, but not making it on time, however I don't think you should be able to essentially get free points late-game after everything is available to you.

I need you to understand I was playing RD as the only member of science and I was working my ass off to do experiments so I could actually get people their research and medical staff just went "AI RESEARCH THIS" and engineering built their own consoles and the rest of command was impatient and not a single one of the experiments I did ended up mattering because by the time I was done I found out some prick already got their expensive tech researched, effectively wasting my time and efforts as well as the time of everyone else on station who now had to wait even longer for their tech. The total amount of points that could have been saved if these fuckwits would wait _literally 2 more minutes_ was over 15000 (I think it was closer to 30000 but 15000 is the most I can be certain of at this point).

So yeah, I don't play Scientist or RD anymore. And that's why. Everyone on the station wants everything from you at the same time and is too impatient to allow you to do experiments to actually afford the most research you can in a reasonable time frame. At least with this PR my efforts would be worth _something_.

**Comment by DaydreamIQ** [comment]
> > I wanted to go the other way and remove experiments that had their node researched already, once t3-t4 microlaser experiment is done, it's already a hastle to go back to t2, find unupgraded machines, upgrade them with only t2, and scan them, I also don't see why they should get any research points for doing it. I would like this if it was limited to experiments that are already in progress so you're not punished for starting them, but not making it on time, however I don't think you should be able to essentially get free points late-game after everything is available to you.
> 
> I need you to understand I was playing RD as the only member of science and I was working my ass off to do experiments so I could actually get people their research and medical staff just went "AI RESEARCH THIS" and engineering built their own consoles and the rest of command was impatient and not a single one of the experiments I did ended up mattering because by the time I was done I found out some prick already got their expensive tech researched, effectively wasting my time and efforts as well as the time of everyone else on station who now had to wait even longer for their tech. The total amount of points that could have been saved if these fuckwits would wait _literally 2 more minutes_ was over 15000 (I think it was closer to 30000 but 15000 is the most I can be certain of at this point).
> 
> So yeah, I don't play Scientist or RD anymore. And that's why. Everyone on the station wants everything from you at the same time and is too impatient to allow you to do experiments to actually afford the most research you can in a reasonable time frame. At least with this PR my efforts would be worth _something_.

Yeah this basically, people are so impatient and since admins aren't actively smiting people who build R&D consoles to waste 20k points on industrial engineering because science is struggling and then complain that we don't have any other tech done. This is at least a band aid that might make science less stressful, or just let us freely murder people who do that shit.

**Comment by the-orange-cow** [comment]
> > > I wanted to go the other way and remove experiments that had their node researched already, once t3-t4 microlaser experiment is done, it's already a hastle to go back to t2, find unupgraded machines, upgrade them with only t2, and scan them, I also don't see why they should get any research points for doing it. I would like this if it was limited to experiments that are already in progress so you're not punished for starting them, but not making it on time, however I don't think you should be able to essentially get free points late-game after everything is available to you.
> > 
> > 
> > I need you to understand I was playing RD as the only member of science and I was working my ass off to do experiments so I could actually get people their research and medical staff just went "AI RESEARCH THIS" and engineering built their own consoles and the rest of command was impatient and not a single one of the experiments I did ended up mattering because by the time I was done I found out some prick already got their expensive tech researched, effectively wasting my time and efforts as well as the time of everyone else on station who now had to wait even longer for their tech. The total amount of points that could have been saved if these fuckwits would wait _literally 2 more minutes_ was over 15000 (I think it was closer to 30000 but 15000 is the most I can be certain of at this point).
> > So yeah, I don't play Scientist or RD anymore. And that's why. Everyone on the station wants everything from you at the same time and is too impatient to allow you to do experiments to actually afford the most research you can in a reasonable time frame. At least with this PR my efforts would be worth _something_.
> 
> Yeah this basically, people are so impatient and since admins aren't actively smiting people who build R&D consoles to waste 20k points on industrial engineering because science is struggling and then complain that we don't have any other tech done. This is at least a band aid that might make science less stressful, or just let us freely murder people who do that shit.

Feature idea:  researching anything anounces as such over sci comms along with the players true name.  Maybe you can emag the console to stop that from happening in the event a tot wants to be discreet.  No, I won't be coding it.

**Comment by Sealed101** [comment]
holy shit people snip thy quotes

the general subconscious understanding of discount experiments in most of rnd players' minds is "what the fuck haha what is this funny collapsible button on my beloved ___ node" and "oh yeah let me scan some iron/glass toilets for industrial tech and never touch the experi-scanner again"

material scanning experiments were supposed to be placeholder until someone more crafty came over and made new and fun ones. this didn't happen. toxins, machine scanning (sob) and mech scanning didn't replace much of those

in any case, this really feels like a band-aid. most experiments don't get completed because they are tedium incarnate, so people skip them unless they are required (remember when there were required experiments haha) 

completing experiments could be granting a reward to the department's budget, at least, but like, there are probably less than 10 RD players that know they have an RD budget.

**Comment by Sealed101** [comment]
> okay but did anyone know that RND gets 250 credits to their budget every time they research _any_ node? I didn't until today

>log message for discounts was broken probablt from day 1

:society:

**Comment by Elli-Skala** [comment]
What if we changed it so that experiments don't give discounts but directly reward rnd with points? 

The issue of people researching things to fast wouldn't matter

Doing the experiments would still be helpful for rnd

You could add experiments for things such as teir 4 parts (maybe set to scan three random machines from the list of machines in a normal upgrade run?)

I know we tried to avoid something like this at first to avoid the old research bomb meta we had but the way to go about getting it is just different now

**Review by san7890 — CHANGES_REQUESTED** [review]
spelling nits

code looks good though

**Pull request merged**
