### PR TITLE
BCIs now come with an integrated circuit with a bci action which is also now removable

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

BCIs now come with an integrated circuit with a bci action which is also now removal

## Why It's Good For The Game

BCI actions can be printed off, so the unremovable bci action components means you can be stuck with an action on your bci that does nothing.

## Changelog

:cl:
qol:  BCIs only come with 1 bci action component and it is now removable.
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by moocowswag** [comment]
won`t you need to screwdriver the integrated circuit out of the bci to put a battery in it.

**Comment by Watermelon914** [comment]
You will need to do that, yes

**Comment by Mothblocks** [comment]
i think you should be able to put batteries inside shells anyway tbh

**Comment by Watermelon914** [comment]
> i think you should be able to put batteries inside shells anyway tbh

sure, but at the time I thought it'd be a good idea to have it like that. Turns out it's kinda shit.

**Pull request merged**
