### PR TITLE
IGNORE THIS

### PR DESCRIPTION
**Pull request by ghost**
I pushed it here by an accident, sorry. Just ignore it.

### CODE REVIEW

**Comment by SuperSlayer0** [comment]
Fuck

**Comment by SuperSlayer0** [comment]
Oops i was adding it to a fork not here

**Comment by Pickle-Coding** [comment]
Abobrus.

**Comment by SuperSlayer0** [comment]
> Abobrus.

Sorry for this

**Comment by lemshake** [comment]
poggers

**Comment by Thunder12345** [comment]
Abobrus

**Comment by MrStonedOne** [comment]
I think we found somebody's #69420 script.

Too bad they fucked up the `>=` direction.

**Pull request closed without merging**
