### PR TITLE
commendations are no longer logged

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

unlogs commendations

## Why It's Good For The Game

"Was there another character you noticed being kind this round that you would like to anonymously thank?"
"anonymously thank" does not imply that admins can look at who you commend, which they can!

## Changelog
:cl:
del: commendations are now more anonymous
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
It gets sent through tgui_alerts, and that gets logged anyway.
I don't think there's any real point in this

**Comment by Fikou** [comment]
> It gets sent through tgui_alerts, and that gets logged anyway.
> I don't think there's any real point in this

sure if someone bothers to go through tgui logs just to see who commends them, but sending a message to admins when it tells you "THIS IS ANONYMOUS" is weird

**Comment by Ryll-Ryll** [comment]
Yeah that logging was first added when the feature still let you send a short message alongside the commendation as an anti abuse feature where you could cancel hostile or abusive commendations. Without that, it's wack

**Comment by Mothblocks** [comment]
i dont like it, we should be logging more not less 😤

**Comment by Mothblocks** [comment]
that was my suggestion

**Comment by wesoda25** [comment]
> It gets sent through tgui_alerts, and that gets logged anyway. I don't think there's any real point in this

I'm pretty sure players can't access those, and that's a major improvement for shoving it in an admins face as opposed to requiring them to dig to find it. I cannot think of a benefit from logging this, super lame PR close 👎

**Comment by Mothblocks** [comment]
`log_admin` removes it from game logs too silly, which is what I didn't want

**Pull request closed without merging**
