### PR TITLE
Stops projectiles being blown away by spacewind

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**

### CODE REVIEW

**Comment by Supermichael777** [comment]
feture for bullets but weird for the much more visible lasers.
the shots literaly curve around to hit the target though.

**Comment by Jalleo** [comment]
Same thing i have noticed on emmiter beams.

**Comment by Aranclanos** [comment]
isnt INFINITY a define made by us? i mean, does it NEED to be INFINITY?

**Comment by Iamgoofball** [comment]
yes

**Pull request merged**
