### PR TITLE
You can no longer use communications consoles off a station/CentCom z-level.

### LINKED ISSUE #55517: Drones can use communications consoles with full access
Derelict drones, or rather more vaguely, drones in general, are able to use communications consoles with full access. This includes calling the shuttle, recalling, making a captain announcement, toggling maint access- I think you get the point.

## Reproduction:

Log into the communications console as a derelict drone, and then troll the station by changing the status display to "DRONES WIN".

image

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request

Closes #55517 by making it so communications consoles don't work off of the station z-level.

2020-12-14T02-59-34

## Why It's Good For The Game
If you want to impact the game for nearly every player, it's now more likely you're impacted by it as well. Also prevents people from hiding in things like asteroids or drones from constantly recalling/calling.

## Changelog
:cl:
tweak: You can no longer use communications consoles off a station/CentCom z-level.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
make it so you can do it on transit/reserve z too B)

**Comment by Cyprex** [comment]
I'm pretty sure this has been the case for a long time already? Presumably this got broken by something?

**Comment by stylemistake** [comment]
Rename Blinking to Blink to keep it short.

**Comment by Jared-Fogle** [comment]
@Cyprex This was something I didn't keep in my rewrite, just out of mistake.

It used to, and get this, check if your z level was below 6. Meaning if you ended up in some fuck off space level far away from the station, but happened to be 3 through 6, then you could still do this.

**Comment by Jared-Fogle** [comment]
this "common build tool" cant come soon enough

**Comment by Jared-Fogle** [comment]
dude come on

**Pull request merged**
