### PR TITLE
Viro Rework Tweaks (Buffed Natural Healing, Slower Progression, Stealth Respects Severity)

### PR DESCRIPTION
**Pull request by Higgin**
## About The Pull Request

image

what it says on the tin. we're in virology rework season again #79854 

makes natural healing enough for people to kick the teeth out of bad viruses without chem. (still needs exact testing to dial in, but ideally, chems will be a buff but no longer a mainstay. #83453 will help, and things like fungal TB will be unchanged.)

makes viruses progress a bit slower across the board - this was part of why you could have a bad virus shoot up to stage 5 from having been at stage 1 out of nowhere, even after having mostly fought it off. this is probabilistic, but the prob is lower now.

makes viruses only hide if their stealth stat is higher than their severity. if you want your virus to be sneaky, you need to spec into hiding it and run fewer symptoms (#83458 will fuck with this if implemented - stay tuned.) 

## Why It's Good For The Game

people don't like getting griefed by one-sided mechanics. while i think i got some of the way there in #79854, the felt impact of that PR was undercut by me being conservative with the values for what players' actual choices outside of chem could do and SD still existing. I'm hoping to go back and fix that first one since thankfully @Time-Green is working on #83453. 

Logic remains much the same as in https://hackmd.io/@Higgin/HJljdBuNp - I am leaving this as a draft until I've had at least a few more tests on the values, but I'd like to see this TM'd in a round or two with advanced diseases floating around if possible. 

edit to add some clarification: 
if you do nothing, I balanced the worst viruses to be about a 50% chance of death.
if you do the right thing, it should work 100% of the time or close to it.
the problem I'm trying to address here is that the second one was nowhere near 100%. 

## Changelog

:cl:
balance: Viruses now self-heal much more effectively with good mood, sleep, food, and spaceacillin.
balance: Viruses now punish being hungry more. Stay fed!
balance: Spaceacillin now gives 200 ticks of symptom resistance, declining over time, rather than 100.
balance: Viruses now progress slightly slower.
balance: Viruses now only hide if their stealth stat is greater than their total computed severity.
/:cl:

### CODE REVIEW

**Comment by DaCoolBoss** [comment]
This might just be anecdotal but I feel like natural immunity is already a little too strong. Yesterday I got hit with a random virus as miner containing sneezing and coughing fit, I went to the mining base and took a 5 minute pee break and by the time I was back the virus had already cured itself, the only steps I took was eating a donk pocket 20 minutes before I got the virus and having a positive moodlet from having a family heirloom. Surely we want to encourage some level of proactive behaviour on the part of players seeking to be cured?

**Comment by Higgin** [comment]
> This might just be anecdotal but I feel like natural immunity is already a little too strong. Yesterday I got hit with a random virus as miner containing sneezing and coughing fit, I went to the mining base and took a 5 minute pee break and by the time I was back the virus had already cured itself, the only steps I took was eating a donk pocket 20 minutes before I got the virus and having a positive moodlet from having a family heirloom. Surely we want to encourage some level of proactive behaviour on the part of players seeking to be cured?

yeah, that's why I want to test this out more - the proactive behavior has to work though. If you'd been in low mood, starving, and hadn't stopped at any point, we'd want the virus to be able to continue. There should be a reward for having kept yourself up before getting the virus, though, and I'm happy if the result is that it pays off more for people to take care of themselves by no-selling random or invisibly-spread problems.

**Comment by Higgin** [comment]
Right. I ran the tests on this: https://docs.google.com/spreadsheets/d/e/2PACX-1vRuIaJdr_oP9SqRHV3jEVZe9rR6bqyyfJeoE6TbhjfUnoPIGCE952_anxWDIoh0xApkZLppRriBGdyp/pubhtml

Lots of pictures and a bit of commentary to follow, but the bottom line is this: with these tweaks, you can sleep and eat to avoid viruses or cure them. Chems help, but they are not strictly necessary. Spaceacillin is good. At a baseline of mood/food and doing nothing to help yourself, it's about a coinflip still with the worst viruses - which was what I wanted to begin with. 

However - viruses will absolutely rock your world if you are hungry or burnt out. Take care of yourself!

**Comment by Higgin** [comment]
Viruses used
image
image
image
image
image

**Comment by Higgin** [comment]
Control Condition (give virus, wait until everyone cured or dead)
image
image
image

**Comment by Higgin** [comment]
Bad Condition Setup (dump the room full of miasma, ruin everyone's mood and starve them from vomiting, then cure all the viruses - I found spaceacillin was effective even with the low mood/starvation, though it took a hot minute for some of the last hanger-on viruses to go away.)

image
image
image
image
image
image

**Comment by Higgin** [comment]
Bad Condition Test (everyone's starved and unhappy)

image
image
image
image
(shoutout to my boy Nam on the second row, far left - he didn't even take damage once)

**Comment by Higgin** [comment]
At long last, the =3 condition (good): 

image
image
image
image
image

**Comment by Higgin** [comment]
It's worth posting up - none of this is done to a degree of statistical significance or rigor you or I should accept generally. The samples are small and the trials too few to run an analysis of errors/standard deviations. This is as much as I'm willing to do with it at the moment, but I'm also very happy with the direction it points and would hope it'd get a shot.

**Comment by Higgin** [comment]
Also worth keeping in mind - the test viruses for AP and AN didn't have itching on them which is one of the worst low-level symptoms because of its consistent brute damage over time. These are bad, but if you look at the control values and think 'shouldn't they be deadlier?' - they can be.

**Comment by Nidvex250** [comment]
well, while virology is getting reworked, maybe there can be an admin verb to make custom viruses?

**Comment by Time-Green** [comment]
> well, while virology is getting reworked, maybe there can be an admin verb to make custom viruses?

That already exists. I forgot the name but I ran into it a few times

**Comment by Higgin** [comment]
> > well, while virology is getting reworked, maybe there can be an admin verb to make custom viruses?
> 
> That already exists. I forgot the name but I ran into it a few times

yep, dead-on - there's an event for making advanced diseases

**Comment by Nidvex250** [comment]
> > > well, while virology is getting reworked, maybe there can be an admin verb to make custom viruses?
> > 
> > 
> > That already exists. I forgot the name but I ran into it a few times
> 
> yep, dead-on - there's an event for making advanced diseases

yes and no. unless I'm missing a verb the Disease Outbreak events only really let you pick the severity and how spreadable it is, or a list of premade viruses in the case of Classic. There's no panel to make a personalized custom virus.

**Pull request merged**
