### PR TITLE
Fixed picking up items through the dropdown menu. v2

### PR DESCRIPTION
**Pull request by Useroth**
## About The Pull Request

After second thought, this is a better version of the fix in https://github.com/tgstation/tgstation/pull/56851

## Changelog
:cl:
fix: Picking items up through the dropdown menu now works once again.
/:cl:

### CODE REVIEW

**Comment by Useroth** [comment]
Also, didn't actually notice there was already a PR open for that.
https://github.com/tgstation/tgstation/pull/56852

**Comment by Jared-Fogle** [comment]
This isn't a better version of the fix in #56846, what?

**Comment by Useroth** [comment]
> 
> 
> This isn't a better version of the fix in #56846, what?

I made a comment and deleted it. I was comparing it to another PR I made.

**Comment by LemonInTheDark** [comment]
This is an alt to #56846,  this is slightly more performant, but it doesn't standardize the fix, so it's more likely to crop up in other places

**Comment by Jared-Fogle** [comment]
Superseded by #56846.

**Pull request closed without merging**
