### PR TITLE
Flops can buy no-slips again.

### PR DESCRIPTION
**Pull request by The-Albinobigfoot**
I mean, seriously fam?

:cl:
rscadd: Nuclear Operative families may once again requisition ultra-adhesive footwear.
/:cl:

### CODE REVIEW

**Comment by Anonus** [comment]
You should change the excludefrom of `/datum/uplink_item/stealthy_tools/syndigaloshes/nuke` to list() instead of this, which will produce two different shoe entries at costs of 2 and 4.

**Comment by Bawhoppen** [comment]
that changelog makes me want to kill self

**Comment by Zilenan91** [comment]
I think Robustin tried pring this, is that one still open or what?

**Comment by KorPhaeron** [comment]
That changelog is non canon

**Comment by The-Albinobigfoot** [comment]
Should I just delete the tacticool galoshes and call it a day?

**Comment by phil235** [comment]
:-1: Nuke ops can already buy noslip shoes.
If you wish to lower their cost from 4 to 2, just remove /datum/uplink_item/stealthy_tools/syndigaloshes/nuke and the excludefrom line (but there's no need to add excludefrom = list())

**Comment by Bawhoppen** [comment]
I'm pretty sure they can't since robustin's PR never was merged,
They used to be able to at some point in the past at the very least

**Comment by Anonus** [comment]
The nuke noslips don't appear in the uplink, though? They're supposed to, but they don't.

**Comment by phil235** [comment]
@Anonus You were right, I didn't see that /datum/uplink_item/stealthy_tools/syndigaloshes/nuke inherits the nukeops exclusion. The excludefrom = list() is needed.

**Comment by Anonus** [comment]
Or they could be a different entry, but either works, really.

**Comment by The-Albinobigfoot** [comment]
Altered the changelog for the wimps out there.

**Comment by Amemelius** [comment]
They need to be more expensive than normal since it means that most unarmed crew can't take an op down and if they have an eshield literally nothing will get through except a baton (and with the new changes in the pipeline to THAT, even that won't work).

**Comment by The-Albinobigfoot** [comment]
The ops' no-slips costs 4 TC rather than 2.

**Comment by tkdrg** [comment]
Ok sure, this makes sense and it was always meant to be like this

**Pull request merged**
