### PR TITLE
New .357 Revolver Sprites

### PR DESCRIPTION
**Pull request by WJohn**
## About The Pull Request
New .357 revolver sprites! In response to #43405 
Left is the syndicate's 357 revolver, middle is the russian revolver, and right is the gold revolver that only admins can spawn anyway.

I can swap the left and middle sprites around if you guys prefer.

## Why It's Good For The Game

Prettier sprites are always good!

## Changelog
:cl: WJohnston
imageadd: New .357 revolver sprites.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Could make it reskinnable between left and middle (like the detective's revolver). I'd prefer the middle on the syndicate revolver so that it stays consistent with how it already is. I dig the sprites

**Comment by anconfuzedrock** [comment]
Syndies are black and red, can’t imagine the left sprite

**Comment by ATH1909** [comment]
> Could make it reskinnable between left and middle (like the detective's revolver). I'd prefer the middle on the syndicate revolver so that it stays consistent with how it already is. I dig the sprites

Yeah, and don't forget that gatfruits are a thing and that the guns in their sprites look black.

**Comment by Bawhoppen** [comment]
I feel like the barrel on the left and middle needs a little more contrast. Also maybe the grip seems a bit too large (but I guess it's accurate to real revolvers).
Anyways, great stuff :+1:

**Pull request merged**
