### PR TITLE
Carbon Dismemberment

### LINKED ISSUE #18532: Beheading husks regrows hair, presumably creates implantable head
Cross-posting from https://github.com/HippieStationCode/HippieStation13/issues/2516. The head is still obviously that of a husk (except for the magically regenerating hair); I assume it can also be transplanted but have not gotten a chance to test it

### LINKED ISSUE #18584: Ling Stasis appearance bug
Changeling regen stasis doesn't fix the "burnt husk" look that you get after getting too much burn damage
Transforming doesn't fix it either
Terrible for stealth as everyone will know you're either badmin shennanigan spawn or a changeling or some other antag.

### PR DESCRIPTION
**Pull request by phil235**
:cl: phil235
add: Monkeys can be dismembered.
add: Humans, monkeys and aliens can drop limbs when they are gibbed.
add: Roboticists can remove flashes, wires and power cells that they inserted in robot head or torso by using a crowbar on it.
add: visual wounds appear on a monkey's bodyparts when injured, exactly like humans.
add: Using a health analyzer on a monkey or alien shows the injuries to each bodypart.
add: Monkeys can become husks.
fix: Human-monkey transformations now respect missing limbs. No more limb regrowth by becoming a monkey.
fix: Changeling's regenerate ability also work while in monkey form.
fix: Alien larva has its own gib and dust animation.
fix: A bodypart that looks wounded still looks bloody when dismembered.
fix: Amputation surgery now works on robotic limbs, and monkeys.
/:cl:
- I rearranged X_defense.dm mob files, more damage_procs.dm. Here's what's inside:
  - X_defense.dm: is for the procs of attacks onto the mob, all the XXX_act() proc (things happening to the mob), as well as protection check and get procs (armor, ear prot, projectile dismemberment)
  - damage_procs.dm: actual damage procs like adjustBruteLoss() getfireloss, any proc that handles damaging.
- some bugfixes with gibspawner effects.
- monkey's bodyparts can be dismembered and are used to create its icon.
- <b>brains are no longer carbons.</b> :tada: 
- all carbon have bodyparts that can be dropped when the mob is gibbed.
- adminspawned bodyparts now have a default icon.
- robotic parts are now a child of bodyparts.
- health analyzer on alien/monkey shows damage on each limb
- added admin option to add/remove/augment bodyparts for all carbon (instead of just remove on humans)
- Fixes keycheck message spam for janicart and all when trying to move.
- Fixes bug with buckling to a scooter while limbless.
- removed arg "hit_zone" in proj's on_hit() because we can already use the def_zone var (where hit_zone got its value)
- Fixes mob not getting any damage when hit by a projectile on their missing limb, despite a hit message shown). carbon/apply_damage() now when we specify a def_zone and the corresponding BP is missing we default to the chest instead of stopping the proc. Consistently with how human/attacked_by() default to its attack to chest if missing limb.
- Fixes mini uzi icon when empty and no mag (typo).
- I renamed and changed a bit check_eye_prot and ear prot
- renamed flash_eyes to flash_act()
- I made a soundbang_act() similar to flash_act but for loud bangs.
- added a gib and dust animation to larva.
- husked monkeys
- no damage overlay for husk or skeleton.
- damage overlay for robotic limb now.
- no damage overlay when organic bodypart husked.
- one handed human with a bloody hand still get a bloody single hand overlay.
- fix admin heal being unable to heal robotic bodyparts.
- slightly touched robotic bodypart sprites (head one pixel too high)
- Fixes #18532 "beheaded husk has hair".
- Fixes #18584 "Ling stasis appearance bug"
- no more eyes or lipstick on husks.
- can remove flashes/wires/cells from robot chest and head with crowbar.
- Fixes not being able to surgically amputate robotic arm/leg.
- dropped bodyparts keep the damage overlays they had while attached.
- human-monkey transformation now respects missing limbs. No more limb regrowth by becoming a monkey.
- Changeling's regenerate ability also work while in monkey form.
- NODISMEMBER species can still lack a limb if they were another species with a missing limb and got species-changed.
- Admin heal regenerates limbs on all carbons.

### CODE REVIEW

**Comment by Incoming5643** [comment]
My gut question is this: are bodyparts tied to their specific type of mob or can I put little monkey arms on a person?

**Comment by phil235** [comment]
@Incoming5643 Codewise, yes you can, but surgery doesn't let you do that, because the monkey limbs are not at the same place as the human and xeno limbs. But admin definitely can force attach a different type of limb, if they know the right proc name.

**Comment by KorPhaeron** [comment]
Dual wielding never ever

**Comment by Cheridan** [comment]
sorry kor :<

**Comment by RemieRichards** [comment]
@phil235 how about something like this for placing limbs on incorrect mob types?

```
/obj/item/bodypart
    var/pixel_offsets = "human=0,0;monkey=0,-4;alien=0,-1"

/obj/item/bodypart/proc/get_offsets_by_carbontype()
    var/list/L = list()
    var/list/split = splittext(pixel_offsets,";")
    for(var/offset_pair in split)
        var/list/offset_pair_split = splittext(offset_pair, "=")
        L[offset_pair_split[1]] = offset_pair_split[2]
    return L
```
(string because lists would be overkill memory wise for this)

**Comment by WJohn** [comment]
absolute madman

**Comment by phil235** [comment]
@RemieRichards Yeah, but the offset would need to change for each direction so we'd have to split the current bodypart sprites that have all four directions to four sprites with each one direction.

**Comment by RemieRichards** [comment]
@phil235 no we wouldn't? we just have to update the dir of those images in ```setDir()```, no need to reorganise sprites at all (overlays always have the dir of their parent, so the only necessary change is in-code offsets)

**Comment by PKPenguin321** [comment]
good lord phil you are an actual god

also might wanna add that monkeys can be dismembered in your :cl: as well

**Comment by phil235** [comment]
@PKPenguin321 Yeah, changelog isn't ready yet.

**Comment by phil235** [comment]
I think it's ready.

**Comment by PKPenguin321** [comment]
So is xeno dismemberment a *soon* thing now? How about cross-species limb augmentations (xenos with monkey limbs when)

**Comment by WJohn** [comment]
Xeno limbs are not aligned with human ones. The only thing aligned between the two is the position of the hands. A xeno could hold any inhand a human could and it would look fine, but if you were to transplant the arm over, the shoulders would not align.

**Comment by phil235** [comment]
See  #20461

**Pull request closed without merging**
