### PR TITLE
Reworks Icebox Station's Kitchen and Diner

### PR DESCRIPTION
**Pull request by funman816**
**Reworks iceboxes kitchen and diner with a new look.**

## About The Pull Request

 Reworks Icebox's Diner, Kitchen, Cold Room, and adds a extra area outside for grill parties. Reworks the kitchen, adding a fast food serve line, and a small bar. Disposals system from botany is available to provide ingredients without the chef having to leave their kitchen. The upper kitchen is focused on more traditional cooking, fast food and meals, while the lower kitchen is designed to be cooking pastries and desserts. This is my first map change, so some mistake or errors could be expected.

### Images:
final1
grilarea
final2

## Why It's Good For The Game

 I've heard in the mapping discord that iceboxes' kitchen and diner needed to be reworked, so I went ahead and reworked it. The overall flow and space of the kitchen has been changed dramatically, opting for accessible kitchen with a navigable loop from one part of the kitchen from the others. Besides, this bigger flow will help new chefs enjoy their kitchen.

## Changelog

:cl:
add: Reworked Icebox Stations Kitchen And Diner
del: Removed Old Icebox Kitchen and Diner.
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
Why would you basically have two full sets of kitchen appliances?

Makes the underside feel irrelevant at this point.

**Comment by Son-of-Space** [comment]
Wasting a lot of space here:
image
image

The decaling is an interesting idea where you're sectioning off the actual kitchen work area, but the decaling isn't really working to help that. I would consider redesigning it to help the decals work rather than just be in your face.

**Comment by Dorsisdwarf** [comment]
Can I recommend putting the food processor on a table if its gonna be locked in a backroom instead of in the working area? That way you're less worried about leaving bits there / pickin everything up, especially with the ultra messy gibber next door.

**Comment by Serxule** [comment]
food processor shouldnt be in cold room imo, also there is not enough tables on the top floor, itd make it harder for making food. also the ovens being on a different floor is a bad idea, since you have to watch them to make sure it doesnt burn

**Comment by Wallemations** [comment]
Honestly, I prefer the current one, as it actually _feels_ like a diner, with a bunch of booths. Meanwhile this one just has a single table, totally takes that away.

**Comment by bluetshirtguy** [comment]
> Why would you basically have two full sets of kitchen appliances?
> 
> Makes the underside feel irrelevant at this point.

good idea, all the appliances should be upstairs, the appliances being split is the single worst aspect of current ice kitchen.

**Review by san7890 — CHANGES_REQUESTED** [review]
I don't think this PR is configured properly? The maps are meant to go in this folder: https://github.com/tgstation/tgstation/tree/master/_maps/map_files/IceBoxStation, and not... wherever they're configured to go. Please let us know in #coding-general or #mapping-general if you need help troubleshooting this.

Also, you'll probably have some conflicts if you replace the files in that aforementioned folder with your copy of those maps. Just be sure to run the batch files in `*/tools/mapmerge2`.

Once you get that figured out, feel free to mark your PR as "Ready for Review" again, as I just put it in a Draft state for our internal management.

**Comment by san7890** [comment]
It's been about a week, please fix these whenever you get a moment or I'll be closing this PR in about a week's time. You can always submit a new pull request featuring these changes again, though.

**Pull request closed without merging**
