### PR TITLE
Adds nt's sprite for syndielite suit

### LINKED ISSUE #13371: Snowman outfit sprite is broken.
What it says on the tin, it has the green SUIT tag in the top right as opposed to any actual sprite.

### PR DESCRIPTION
**Pull request by Jordie0608**
See #13024 for image

Fixes #13371

### CODE REVIEW

**Comment by PKPenguin321** [comment]
woah i didnt even realize we had these hardsuits

**Comment by Jordie0608** [comment]
They were merged yesterday since the PR creator had trouble adding the sprites.

**Comment by WJohn** [comment]
Pretty good sprites, although I`d like to have a bit more red in there.

Otherwise :+1:

**Comment by Dorsisdwarf** [comment]
Reddy?

**Comment by Jordie0608** [comment]
Yeah

**Comment by duncathan** [comment]
>five-day old sprite PR
>no conflicts

nice

**Pull request merged**
