### PR TITLE
Split the dmi files for suits into different categories under a single folder

### PR DESCRIPTION
**Pull request by InfinityArch**
## About The Pull Request

This pull request splits the dmi files from suits, which had something like 300 icons on it into smaller .dmi files with at most around 20 icons each. This was done along the lines of the recent split up of the uniform dmi

## Why It's Good For The Game

This makes the dmi files for suits vastly more usable than they are presently, and makes it easier for new iconstates for suits to be added.

## Changelog
:cl:
refactor: Split up the suits dmi into seperate categorized files.
fix: fixed the lack of a tech priest robe's item state.
/:cl:

### CODE REVIEW

**Review by ShizCalev — CHANGES_REQUESTED** [review]
fix the chameleon suit.

**Comment by cacogen** [comment]
I hope this breaks even more clothing sprites

**Comment by InfinityArch** [comment]
> fix the chameleon suit.

This has been done as of yesterday.

**Comment by ShizCalev** [comment]
@InfinityArch https://github.com/tgstation/tgstation/blob/b84420f46b151ebe4ebdf1ccd5aadc1109217a41/code/modules/clothing/chameleon.dm#L349

**Review by ShizCalev — CHANGES_REQUESTED** [review]
@InfinityArch https://github.com/tgstation/tgstation/blob/b84420f46b151ebe4ebdf1ccd5aadc1109217a41/code/modules/clothing/chameleon.dm#L349

not quite. you're going to have to blacklist all the dummy parent paths now.

**Comment by ShizCalev** [comment]
you also need to update this to change between mob overlay icons
https://github.com/tgstation/tgstation/blob/0e21944b7ca0ee7143f7086f4088943b4287a22a/code/modules/clothing/chameleon.dm#L218-L230

**Comment by Farquaar** [comment]
This will make coding new clothes a heck of a lot easier.

**Comment by SpaceManiac** [comment]
Info on resolving merge conflicts in icons: https://github.com/tgstation/tgstation/wiki/Resolving-icon-conflicts

**Comment by optimumtact** [comment]
stale

**Pull request closed without merging**
