### PR TITLE
Changes IC button to not be as infuriating

### PR DESCRIPTION
**Pull request by Nickkoranda**
## About The Pull Request

Changes IC button to reflect that you should deal with the issue IC rather than the IC button being a glorified rule 10 button.

## Why It's Good For The Game

Current IC button sucks lol

## Changelog
:cl: Hulkamania
admin: IC button changed to clarify that the issue should be dealt with IC, not display rule 10.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
good change since this better conveys the message we intend to send when we push this button

**Comment by ATH1909** [comment]
Is it "in-character" or "in character"?

**Comment by 81Denton** [comment]
yes

**Comment by nervere** [comment]
better off removing it tbh

**Comment by ExcessiveUseOfCobblestone** [comment]
Maintainer wise i'm fine with this. Honestly tho this should just be config bound so you don't need our oversight to change it.

Admin wise I'd prefer it be clear that "handling it IC" doesn't necessarily mean license to kill.

**Pull request merged**
