### PR TITLE
Changes grille sprites to be in-line with broken grilles

### PR DESCRIPTION
**Pull request by ChangelingRain**
Before;
dark mouse
After;
this will haunt you forever

### CODE REVIEW

**Comment by Razharas** [comment]
Ill pretend i see a difference
Good job

**Comment by Bawhoppen** [comment]
you already ruined grilles dont ruin their broken brethren too

**Comment by ChangelingRain** [comment]
I haven't touched broken grilles, though!

**Comment by Bawhoppen** [comment]
I dont know whats real anymore

**Comment by Cheridan** [comment]
you should touch broken grilles then, this new sprite has more tiling; i don't like it as much

**Comment by ChangelingRain** [comment]
it's the same sprite shifted 4 pixels up

**Comment by ChangelingRain** [comment]
also your alternative for broken grilles is this;
lookslikeshit

**Comment by Cheridan** [comment]
That's not so bad?

**Comment by optimumtact** [comment]
just add four rotated versions of the primary grille

easy

**Comment by optimumtact** [comment]
I suppose cheri can fix this in their own time.

**Pull request merged**
