### PR TITLE
APCs are now immune to fire

### PR DESCRIPTION
**Pull request by ChangelingRain**
Losing power due to a fire is bad and I don't like it. I want my perpetual fires back.

### CODE REVIEW

**Comment by Kromgar** [comment]
Can you make research machinery not melt in a fire now? Losing research because of fires sucks

**Comment by SgtxRootbeer** [comment]
@Kromgar 
no, figure out how to save your data to the rnd database every once in a while.

**Comment by Armhulen** [comment]
Can you make rnd database not melt in a fire now? Losing saved research because of fires sucks

**Comment by GunHog** [comment]
The server room is usually well secured against fire. If the room has been breached or flooded via atmos, it will most likely be a result of deliberate sabotage.

**Comment by KorPhaeron** [comment]
This doesn't really make any sense though fire isn't good for machines

**Comment by SgtxRootbeer** [comment]
Those machines are in a special room to keep them cool, mainly because heat damages them no.

**Pull request merged**
