### PR TITLE
Baseball bats have a 1% chance to be deformed on creation

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request

Makes every baseball bat created have a 1% chance to be what we call a "british baseball bat".*

_*This does not affect bounties._

## Why It's Good For The Game

[https://youtu.be/zVGPPMpXPA8](https://youtu.be/zVGPPMpXPA8)

## Changelog
:cl: Wallem
add: Recent surveys show 1% of nanotrasen employees have been misinformed on the concept of baseball.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
incredible video

also an incredible PR

**Review by Twaticus — APPROVED** [review]

**Comment by Fikou** [comment]
you forgot to remove a default state thing you added

**Comment by RaveRadbury** [comment]
You gotta know what a crumpet is to understand cricket

**Comment by Wallemations** [comment]
> you forgot to remove a default state thing you added

You mean in the sprites? If I left a default sprite copy accidentally that's my bad

**Comment by Rohesie** [comment]
Make a new PR

**Pull request merged**
