### PR TITLE
Circuit tiles now glow faintly

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Circuit tiles now glow faintly.
/:cl:

Normal

Nuke active

Something something byond's memory leak is still around but should be fixed soon don't merge this yet anyway

### CODE REVIEW

**Comment by GunHog** [comment]
Man that looks coooooooooool.

**Comment by WJohn** [comment]
That's... a bit too faint, I feel. I'd like it if it were brighter.

**Comment by GunHog** [comment]
Think about it, WJ! You would only see this when the main lights are unlit! So it looks a bit spooky with the lights off!

**Comment by WJohn** [comment]
I know, but I'd like it if I could have a core almost entirely lit by these, if they were bright enough to do so.

Besides, how often is the AI satellite totally dark? Pretty much never.

**Comment by Armhulen** [comment]
going delta should replace all the light colors with flashing red, like an alarm.

**Comment by WJohn** [comment]
The "light" from fire alarms and the light from light sources are two totally different systems, one is area based regardless of whether or not there are any lights, the other is actually calculated from light sources and is actually intensive.

**Comment by Iatots** [comment]
I noticed green tiles don't become red during delta. can you fix that while you work on this?

**Comment by ChangelingRain** [comment]
This does in fact fix that.

**Comment by Anonmare** [comment]
@WJohn When I'm traitor AI, always. I turn off the lights to confuse people who don't have NVGs or flashlights and to conserve power for the turrets.

**Comment by GunHog** [comment]
Hostile cyborgs also cut power to the APC in order to kill the AI more easily. EMP strikes by Traitors and Ion Rifle attacks from Sec are also occurrences.

**Pull request merged**
