### PR TITLE
Adds Hook() helper proc

### PR DESCRIPTION
**Pull request by nullbear**
Intended to be used for reducing type dependency. See included readme, and commit info, for more information.

I noticed i was using this mechanic in multiple PR's of mine, and that it would make more sense to just add it as a simpler version for all datums/atoms.

I will eventually get around to cleaning up stuff like diseasecode/symptomcode to use this, but i'll wait for the attackby refactor first.

### CODE REVIEW

**Comment by xxalpha** [comment]
>+71 lines
>2 lines of code

**Comment by nullbear** [comment]
its glorious.

the file isnt even included.

**Comment by KazeEspada** [comment]
You should code an example.

**Comment by nullbear** [comment]
see https://github.com/tgstation/-tg-station/pull/16944 execute() for an example of where i am using Hook(), although with a different name, in a less elegant format.

**Comment by nullbear** [comment]
@KazeEspada 

Here's an example: https://github.com/nullbear/-tg-station/commit/f8f4d1f4712ba5f754e6be296e4361b1e153b927

**Comment by xxalpha** [comment]
You should rewrite that code you cited to use this, then it is a proper example and you clean up stuff!

**Comment by nullbear** [comment]
See more recent example. I will update network to use it later.

**Comment by nullbear** [comment]
ill add when i use it in a pr.

**Pull request closed without merging**
