### PR TITLE
Adds wibbles to certain anomalous entities

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Adds wibble animation to portals, some anomalies, and bluespace rifts.

https://github.com/tgstation/tgstation/assets/51863163/9355dc53-590e-4558-82a3-15145829ce16

## Why It's Good For The Game

It looks kinda cool.
Helps cement these as anomalous, wacky things that don't necessarily fit in our plane of existence.

## Changelog

:cl: Melbert
add: Anomalies, portals, and bluespace rifts will now wibble a bit. 
/:cl:

### CODE REVIEW

**Comment by junkgle01** [comment]
i like all of these, but the wormhole is kind of unreadable. maybe lessen the intensity on that in particular?

**Comment by carlarctg** [comment]
add it to heretic cloak

**Comment by MrMelbert** [comment]
> i like all of these, but the wormhole is kind of unreadable. maybe lessen the intensity on that in particular?

I'll just remove it

**Comment by HoodMilk** [comment]
Looks very out of place, but in a good way. Anomalies breaking the pixelated style of the game and being wobbly vortexes of color is cool.

**Comment by Loafin34** [comment]
add this to wiz projectiles plz

**Pull request merged**
