### PR TITLE
Gives lavaland syndicates the syndicate faction.

### PR DESCRIPTION
**Pull request by WJohn**
What it says on the tin. They're blatantly syndicate, they should be immune from syndicate mobs and syndicate turrets, should someone (me) decide some shenanigans like that should happen.

### CODE REVIEW

**Comment by Armhulen** [comment]
Great

**Comment by GunHog** [comment]
Logical.

**Comment by octareenroon91** [comment]
Isn't faction a list?

**Comment by WJohn** [comment]
Only if there's more than one, I don't think it's necessary otherwise?

**Comment by octareenroon91** [comment]
From `code/modules/mob/mob_defines.dm`:

`
        var/list/faction = list("neutral") //A list of factions that this mob is currently in, for hostile mob targetting, amongst other things
`

**Comment by ExcessiveUseOfCobblestone** [comment]
it has to be a list because players are given their mob tag as a faction as well.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
