### PR TITLE
Nuclear Operatives now have to buy blood-red hardsuits, and instead get normal syndicate spacesuits at roundstart.

### PR DESCRIPTION
**Pull request by ghost**
:cl: iksyp
balance: The Syndicate has made some budget cuts to their Nuclear Agents, and in doing so, has downgraded the hardsuits they give out to standard syndicate EVA suits. However, due to the influx of hardsuits for *completely unrelated reasons*, they have lowered the telecrystal price of blood-red hardsuits for their Nuclear Agents.
/:cl:

why: Any decent newcop buys a better hardsuit anyways, and I want to see the reaction to a change like this. My discord `@david*#0818, `go ahead and yell at me.

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Map merge yada yada

**Comment by vuonojenmustaturska** [comment]
"stealth ops now get free eva suits"

**Comment by iskyp** [comment]
there we go mapmerge done
the one thing i kept screaming at myself to do and forgot

**Comment by AlexTheSysop42** [comment]
>"stealth ops now get free eva suits"

Wrong, these are the bright red kind, not the kind traitors can buy

**Comment by iskyp** [comment]
bright red is superior tbh

**Comment by Grazyn** [comment]
Most nuke ops don't even know the hardsuit has a combat mode anyway or they change it by mistake before they leave the shuttle and freeze in space

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't think "I want to see the reaction on people's faces" is a valid justification for a change.

**Comment by iskyp** [comment]
since when has testing waters ever been an invalid reason to change something

**Comment by ExcessiveUseOfCobblestone** [comment]
Since we've enforced "You have to explain why your PR is good for the game. If you can't, you probably shouldn't PR it."

**Comment by Iatots** [comment]
"it's a social experiment"

**Comment by iskyp** [comment]
>it's a social experiment

**Comment by Kromgar** [comment]
I'm removing chem "it's a social experiment"

**Comment by epochayur** [comment]
why: "because, lol"
🤔

~~most~~ some people actually prefer to contribute to the game instead of making pointless removals/tweaks

**Comment by iskyp** [comment]
making a pointless removal/tweak is still contribution if it gets merged

**Comment by PKPenguin321** [comment]
\>runs out of tcs not realizing you have to buy your own hardsuit
\>round is now extended
just a prank bro

**Comment by iskyp** [comment]
they get space suits still though

**Comment by Iamgoofball** [comment]
yeah did everyone forget about the classic red fatsuits

**Comment by iskyp** [comment]
@cyclowns it's pointless because any nuke op who's worth their salt buys a better hardsuit anyways

**Comment by Therapist1** [comment]
yeah seriously, how would this improve the game at all?

**Comment by Shadowflame909** [comment]
When will the stupid nerfs end! You're literally nerfing something just because you can. Not because of any outcry for balance or anything. I mean if the coders that actually play can see the problem here. I think the coders that don't play should understand they're overstepping the shitpost nerfs! What's next, is soap gonna be removed and replaced with a bucket of water just because?

**Comment by MMMiracles** [comment]
I prefer the aesthetic of the fat red suits more tbh but this is just a straight down-grade for the sole purpose of 'because i felt like it' and doesn't do anything other than stir up shit.

**Pull request closed without merging**
