### PR TITLE
Adds plaid skirts and new schoolgirl uniform colours

### PR DESCRIPTION
**Pull request by TZK13**
Plaid skirts are ported from Baystation12 and are available in the clothesmate.

barbie spess adventure

Also ports different schoolgirl uniform colours made by @dannno from NTstation which are available in the autodrobe: https://github.com/NTStation/NTstation13/pull/724

Finally moves the ties that I added to the autodrobe in another PR to the clothesmate and adds a black skirt and Amish suit to the clothesmate as well.

### CODE REVIEW

**Comment by Chocobro** [comment]
it looks like a heavy grid. perhaps we should change it to give it lighter colours, greys etc?

**Comment by TZK13** [comment]
I can always look into it if the sprites are provided.

**Comment by Miauw62** [comment]
@WJohn @Nienhaus

**Comment by WJohn** [comment]
I'm noticing that the sprites were drawn exclusively for females due to the armpits lacking an extra pixel. This was deemed no longer necessary to do when we first got the ability to "fit" clothes onto females. Test this on a male and see if you get any skin pixels, would you?

**Comment by Incoming5643** [comment]
skirts don't work with fitted clothing because of the dickpixel™, which appears in the middle of the skirt.

Since skirts/dresses/fancy bottom stuff seem to be getting more common, I could add a form of that var where it leaves the dickpixel™ unmolested but still removes the other ones.

But in any case, you always, ALWAYS, have to model your clothing on guys: the female uniform generation removes pixels for women, it can't create them from whole cloth for men.

**Comment by paprka** [comment]
>not dixel™

**Comment by TZK13** [comment]
Filled out the spots on the plaid skirts that are removed for women, I forgot Bay doesn't have that feature.

**Comment by Nienhaus** [comment]
Looks pretty good.

**Comment by Cheridan** [comment]
AM I KAWAII

**Comment by Incoming5643** [comment]
ability to wear bread in your mask slot fucking when

**Comment by paprka** [comment]
As long as men can wear this without showing armpit pixels you have a +1 from me so I can continue being a dirty crossdresser

**Pull request merged**
