### PR TITLE
Grammar edit for flashbangs tip

### PR DESCRIPTION
**Pull request by BeeSting12**
Removes the space between flash and bangs in the tip "Flash bangs can weaken blob tiles, allowing for you and the crew to easily destroy them."
the old title was better tbh

### CODE REVIEW

**Comment by PKPenguin321** [comment]
😫

**Comment by QualityVan** [comment]
Shouldn't this be 'Removes Flash bangs'?

**Comment by AnturK** [comment]
Please give this PR title that indicates the content or it will have to be closed.

**Comment by coiax** [comment]
Tips still have to be manually updated on the server.

**Comment by BeeSting12** [comment]
i will make this compile eventually tomorrow maybe

**Comment by BeeSting12** [comment]
idunno what that had to do with compile issues but it fixed it

**Pull request merged**
