### PR TITLE
Disables reliability

### PR DESCRIPTION
**Pull request by Iamgoofball**
People say(including myself) that "rng lol you cant deconstruct this/it blows up in your face" is retarded.

### CODE REVIEW

**Comment by duncathan** [comment]
:+1: x :100: x :100:

**Comment by Fox-McCloud** [comment]
:+1: 

It was a dumb feature anyway.

**Comment by Xhuis** [comment]
u hav nuklir enirgy gun? i mak u redation xDdddddddd

:+1:

**Comment by WJohn** [comment]
Thank you.

**Comment by Jordie0608** [comment]
Do it properly you dork.

**Comment by Razharas** [comment]
This level of coding is not good enough for our respectable code base
Improve yourself if you want to participate in our development circle

**Comment by Iamgoofball** [comment]
i mainly wanted to get a discussion started about this with this PR

**Comment by xxalpha** [comment]
Do it properly and just strip the system out.

**Comment by PKPenguin321** [comment]
:+1: i don't care how it's removed, just as long as it's removed

**Comment by Aranclanos** [comment]
do it properly

**Comment by Shadowlight213** [comment]
Aww, but giving sec unreliable guns and watching them get knocked out by rads was fun!
Keep the advanced egun overload thing in. Maybe have the overload chance trigger if the gun is emped, or maybe have a multitool able to toggle the safeties on it.

**Comment by bear1ake** [comment]
Oh no! Don't remove it!

**Comment by Shapsy** [comment]
I'm all for getting rid of the Advanced Energy Gun fuckery, but will this mean you never have to upgrade the DA anymore?

**Comment by Iamgoofball** [comment]
@Shapsy You get higher tech levels out of an upgraded DA I believe.

**Comment by Shapsy** [comment]
@Iamgoofball No, you need upgraded DA parts to be able to successfully decon higher tier parts, like how you can't decon, say, a sleeper board with reliability 88 without upgrading the parts of the DA, which would be silly. I'd vote just remove the tangible effects of reliability from produced items like the AEG, and keep it for gating research progression

**Comment by Fox-McCloud** [comment]
Oh, @Iamgoofball if you get rid of this, you'll have to get rid of selling blueprint disks to cargo, as everything will be 100% reliable.

**Comment by Rinoka** [comment]
Yeah, basically. Reliability is R&D's stopper; it's why you see R&D get Robotics to make things for them, because all Robotics parts are 100% reliable.

R&D does eventually transcend this limit after a while if it's good, but all the same - it's probably important to earlygame if we don't want R&D masters immediately going from 0 to 100% research.

**Comment by kevinz000** [comment]
Cargo currently gives points if you ship to centcom max reliability design disks 
This will also buff research since some things that you couldn't research before because of reliability issues will now be able to be deconned without upgrading the deconstructive analyzer

**Comment by kevinz000** [comment]
Also are you removing reliability or just making it 100? Because emps will still lower advanced energy gun reliability (which is why you should ditch adv eguns exposed to emps because it's going to blow up sometime)

**Comment by Razharas** [comment]
He is just making it 100
Which is why this is not going to be merged

**Comment by Aranclanos** [comment]
unupdated, no response, etc

**Comment by Iamgoofball** [comment]
seeing as the response is in favor for removing reliability, I'll go forward with a proper version of this PR

**Pull request closed without merging**
