### PR TITLE
Adjustable Chat Line Height

### PR DESCRIPTION
**Pull request by ghost**
In Goonchat settings you can now increase/decrease line-height for the body tag/style

This always bugged me, the spacing between lines is just way too big there's so much wasted space
Changed default line-height to 1.2 from 1.4, same as /vg/ (OG Goonchat port server) and Paradise use
Before:
spacing1
After:
spacing2

Note: Goonchat has a new option to increase/decrease line height now

:cl:
add: You can adjust line height in chat settings
tweak: Default chat line height is slightly shorter, from 1.4 to 1.2
/:cl:

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by DaxDupont** [comment]
The old spacing is better on the eyes imo

**Comment by uraniummeltdown** [comment]
I find the new spacing easier on the eyes, you have to move your eyes less to read the next line, you can read more lines without scrolling. It's not like the lines are rammed into each other there is still visible spacing

**Comment by praisenarsie** [comment]
just make it a preference

**Comment by Xhuis** [comment]
Hm, would it be possible to allow this to bet set as a number? That way people could set it to whatever they choose. Since ratings on this PR are just opinion, though, I prefer the old spacing more. This version is rather tight and compressed.

**Comment by Bawhoppen** [comment]
This looks bad.

**Comment by Supermichael777** [comment]
i feel 1.3 would balance readability with space usage

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Didn't expect it to be this contraversial so I guess it should be a preference. Do it like font size does it: https://github.com/tgstation/tgstation/blob/master/code/modules/goonchat/browserassets/js/browserOutput.js#L595

**Comment by optimumtact** [comment]
\>thing simple enough that everyone can have an opinion on it
\>I didn't expect it to be so controversial

I've got a nuclear reactor to sell you

**Comment by uraniummeltdown** [comment]
Ok you can now adjust line height in goonchat settings

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
