### PR TITLE
Being high is now a status effect. Also replaced the related fullscreen overlay with a client colour datum.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title. I Also adjusted the cursed heart client colour to the client colour refactor I have PR'd last month.

## Why It's Good For The Game
I'm planning to replace the current fullscreen overlay with slightly more captivating visuals.  I'll post a vid (or screenshot) once I finally test and finetune it.

## Changelog
:cl:
refactor: Being high is now an actual status effect.
add: Replaced the druggy fullscreen overlay with a client colour datum that rotates the RGB values of the screen over time.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
vid?

**Comment by MrStonedOne** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by Ghommie** [comment]
> Your current title and or body content does not meet requirements, so please update it.

Done. Thanks for telling.

**Review by MrsTonedOne — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
status?

**Comment by optimumtact** [comment]
This is still marked WIP

**Comment by Ghommie** [comment]
Yea, this ought to be ready for review tomorrow; I have to edit a few lines of code and comment, sorry for the delay.

**Comment by Ghommie** [comment]
There seems to be a byond issue about client view and non-animated pixel_x/pixel_y changes breaking the client.color transitions in an ironically trippy and funky way (I have yet to confirm whether this only applies to color matrices or not). The bad thing is the issue can persist for as long as the old view value is not restored, or until the player reconnect in the case of pixel x/y.
I'll have to make a bug report on the byond forums, until then...

**Pull request closed without merging**
