### PR TITLE
Removes Narnar shuttle

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

what it says
## Why It's Good For The Game

shuttle bloat

## Changelog
:cl:
del: Removed admin only narnar shuttle
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
>shuttle bloat

Please be more descriptive, what's the actual reason behind it?

**Comment by tralezab** [comment]
Shuttle... Bloat...?

**Comment by wesoda25** [comment]
The shuttle sucks gank it

**Comment by TiviPlus** [comment]
Unused, unmaintained and a waste of space

Not to mention oranges is saying to axe even more shuttles

**Comment by Jared-Fogle** [comment]
image

**Comment by trexter555** [comment]
the problem with that is command can just spam the buy shuttle whenever to see if there's any cultists still alive

**Comment by Jared-Fogle** [comment]
@trexter555 We could just steal what revs does, which is announce to the entire station that the threat is over, though I'd have to think about whether it's worth it or not.

**Comment by ExcessiveUseOfCobblestone** [comment]
just have it unlocked when a rune is successfully dispelled via null rod, I will not support a mechanic which acts as a tester for the mode.

**Comment by ExcessiveUseOfCobblestone** [comment]
We dont need to maintain shuttles like we do with station, what is the burden here?

**Pull request closed without merging**
