### PR TITLE
Updates catwalk sprites

### PR DESCRIPTION
**Pull request by ghost**
Fulltile again.

clip 2015-01-08 at 04 55 57

The urge to just make catwalks turfs is more and more appealing, but then that would defeat the entire purpose of them.

### CODE REVIEW

**Comment by Cheridan** [comment]
are you having a sprite war with yourself now? :white_check_mark:

**Comment by paprka** [comment]
yes

**Comment by tkdrg** [comment]
...make them turfs?

**Comment by paprka** [comment]
the problem with that is that they wouldn't move when pulled by singulos and wouldn't look like they're placed on top of space like lattices are

**Comment by Boggart** [comment]
Open the space tile in the graphics editor and paste the catwalk one over it.

**Comment by paprka** [comment]
but that wouldn't be dynamic as shit

**Comment by Boggart** [comment]
Hm, good point. I wonder if you could do something like have the random type space tile icon with the catwalk one as an overlay on it...

**Comment by paprka** [comment]
Lazy

If someone else wants to convert it to a turf though I don't mind

**Comment by Razharas** [comment]
All of this could be prevented if catwalks would be just plating with different sprite

**Comment by paprka** [comment]
I don't really want to argue about this, this PR fixes some sprite bugs with catwalks and that's it

**Comment by pudl** [comment]
i like the current sprites

**Comment by paprka** [comment]
Fine whatever enjoy the lattice bugs

**Pull request closed without merging**
