### PR TITLE
adds high-capacity watertanks

### PR DESCRIPTION
**Pull request by pudl**
:cl: Quiltyquilty
rscadd: Botany, atmospherics and cargo now all have access to high-capacity watertanks.
/:cl:

I got a request to add these from my old composting pr. They're just watertanks that hold 100,000 units. This is to give botany and atmospherics a water source similar to a sink, except portable. It only takes 14 buckets to empty a standard watertank. This makes life much easier.

Should i change the cargo price? Should it not be given to atmos? Any other feedback? Im willing to change anything. The only things i want to stay are the units of water and the fact that botany gets to have them.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
redpills watertanks

**Comment by Bawhoppen** [comment]
they dont even need watertanks when they have an infinite sink though

**Comment by Core0verload** [comment]
Maybe just 2x or 5x standard water tank? And the sprite is shitty, like, Goonstation shitty.

**Comment by pudl** [comment]
@Bawhoppen I said in the pr that the point is to allow for a portable source of water instead of having to go to the sink nonstop. The benefit of the watertank is that you can drag it with you and have water wherever instead of having to run to the sink nonstop.

**Pull request merged**
