### PR TITLE
Changes xeno signs

### PR DESCRIPTION
**Pull request by ghost**
Beautiful signs sprited by **WJohnston**. @WJohn 
xeno signs

The former replaces xenobio1 which I assume is the xenobiology sign and the latter replaces xenobio2 which I also assume is the mining sign.
I was completely unprofessional and forgot to ask for 32x32 versions so sorted that out myself.

### CODE REVIEW

**Comment by WJohn** [comment]
100% biased :+1:

**Comment by Nienhaus** [comment]
I'll be unbiased. :+1:

**Comment by CosmicScientist** [comment]
The left hand sprite has the slime one pixel higher, I didn't think to update the picture itself.

**Comment by tuypo1** [comment]
do you really need to get rid of the old signs why cant we have both sets

**Comment by CosmicScientist** [comment]
@tuypo1 I mentioned them to WJohnston and he said he didn't like the T-rex armed Xeno for Xenobiology and the head thing for "Danger! Aliums!" in Mining (as far as I recall he did them both ages ago). So he did up two sprites and I'm putting them in for him.

**Pull request merged**
