### PR TITLE
More map fixes.

### LINKED ISSUE #10049: Vault floor and plating all over centcom
There's lots of vault tiles around centcom where there really shouldn't be. Vault tiles are very ugly, not used ANYWHERE else in the game, and as they are right now are out of place with their surroundings. There's some in front of the thunderdome, just under the customs desk, and a couple randomly placed in the supply shuttle area,

### LINKED ISSUE #10896: More box mapping issues
Turbine Engine
Is this wall on the left intended above turbine engine room?

sadf
Bio disposals airlocks are not powered and there's a random ass wire under the first airlock.

### LINKED ISSUE #11054: The entry airlock of telecommunications is missing a pipe
Distro pipe is missing under the airlock

### PR DESCRIPTION
**Pull request by WJohn**
Fixes #11054
Fixes #10896
Fixes #10049
Changes look of bomb-proof wall on toxins test site to riveted like on centcom.
Cleans up various area boundaries around the station, shouldn't have any effect on gameplay but looks cleaner when mapping.

Don't mind the giant line changes, that's apparently due to me being the first guy to use the new map merger and it's supposed to do that. It'll be smooth from there on out though.

### CODE REVIEW

**Comment by daman997** [comment]
dong sprites when

**Comment by WJohn** [comment]
Is following me around and asking me that every waking hour all you do?

**Comment by CorruptComputer** [comment]
http://40.media.tumblr.com/05f2abe66a47dbe320b2318b43614cbd/tumblr_nof95lZ4hY1tnjmmio1_1280.png

**Comment by Ikarrus** [comment]
>Cleans up various area boundaries around the station, shouldn't have any effect on gameplay but looks cleaner when mapping.

This doesn't break emergency maintenance access, does it?

**Comment by WJohn** [comment]
No, the maintenance doors are still touched by the maintenance areas the same way. I haven't changed the areas any door is affected by.

**Pull request merged**
