### PR TITLE
Adds an examine message to braindead Ais

### PR DESCRIPTION
**Pull request by Shadowlight213**
Changes the examine text if the Ai is braindead.

### CODE REVIEW

**Comment by duncathan** [comment]
:+1:

**Comment by GunHog** [comment]
:+1: Acceptable!

**Comment by Fox-McCloud** [comment]
Latejoining AI's and cyborgs when?

**Comment by SconesC** [comment]
Never, because the sudden presence of an AI with no counterplay to prevent it's arrival get change the round far too drastically

Yeah but this is :+1:

**Comment by RemieRichards** [comment]
@SconesC I believe the way it is done on bay is that the inactive core is on the sat/station, and the AI can only latejoin if that core still exists, meaning you can just blow up the core as if there were an AI.

**Comment by Fox-McCloud** [comment]
@SconesC 

@RemieRichards is correct.

**Comment by SconesC** [comment]
Breaching a core to make sure an AI can't join rather than converting/crippling/killing off Science is a bit much but it's not an argument for this PR

**Pull request merged**
