### PR TITLE
Buffs clockcult structures

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Mending Motors heal for more.
wip: Mania Motors are overall more powerful; they have greater effect, but require more power to run and less power to convert adjacent targets.
experiment: Interdiction Lenses no longer require power to disrupt electronics and will no longer disrupt the radios of servants.
/:cl:

### CODE REVIEW

**Comment by lordpidey** [comment]
Apparently you do need all those VAR's, gosh.

**Comment by ChangelingRain** [comment]
I certainly do not.

**Comment by KingPhilipIII** [comment]
I never see people use structures that require power because they are a pain in the ass to power in reality. Gotta have that adjacent sigil of transmission, which you have to sap power from nearby sources (If it's a base in maint there is next to nothing to siphon, and most are.)) and they run out of power incredibly quickly.

**Comment by ExcessiveUseOfCobblestone** [comment]
you start off with a lot of power in the rune though so if you really wanted you could just recreate them since by this point if you're not trash you are churning out parts pretty fast.

**Comment by ChangelingRain** [comment]
Plus this does make the lens basically a power generator, as it'll constantly drain power from anything in a fucking massive range with no downside.

**Comment by KingPhilipIII** [comment]
I've never actually built the lens. How large is its range ? I've used the mending motor and mania motor and that's it because I got annoyed with the mania motor wasting power trying to convert me when I walked next to it.

**Comment by ChangelingRain** [comment]
If it's just at the edge of your screen it can hit everything you can see; 14 tile range.

**Comment by KingPhilipIII** [comment]
So. Something that's been bugging me. When it specifies the cost to run a structure how does it handle the costs power wise? Does it drain X amount of power per tick while on or what?

Another bug I've had for a while is I can't draw alloy from caches with my prosyletizer (Spell check). I just nap it and it says the cache is at full health. I can do it by hand yes but I'm lazy.

**Comment by ChangelingRain** [comment]
I fixed that bug recently!
Anyway; power is drained once per process tick(every 2 seconds) if it's "while active" and otherwise, if it's per object/activation, up to once per valid object/activation(if it does this while processing, this also happens every 2 seconds)
Stuff like the obelisk is one activation per gate/broadcast.

**Pull request merged**
