### PR TITLE
I created empty boxes

### PR DESCRIPTION
**Pull request by FluffTheMoth01**
Signed-off-by: Space Prius <bubba041102@gmail.com>

## About The Pull Request
I added empty boxes to cargo, I decided to follow the restriction stated in the file and set the price to 700, but my original intention was to have it be 500 so it isn't a completely horrible loss to the QM, which a more experienced contributed can do if they like.

## Why It's Good For The Game
Allows Cargo to store bulk items easily after they inevitably sold every crate in the station.

## Changelog
:cl: SpacePrius
rscadd: Added empty boxes.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
you don't need both a yaml file and the one in the body of your OP for the changlog, that'll get you two

**Comment by SpacePrius** [comment]
good to know

**Comment by SpacePrius** [comment]
Forgot to fill out the why its good part, somehow.

**Comment by FantasticFwoosh** [comment]
This isn't required because you can make wood boxes on a profit for _free_ with botany and also use lockers (no initial export value) to be a legitimate container for shipping to centcomm.

Why would you want this, this feels like code-bloat.

**Comment by MMMiracles** [comment]
7 lines of absolute BLOAT

**Comment by Tlaltecuhtli** [comment]
7 lines may not seem much, but these are 7 lines in a tgui window, which means free lag and freezes for a really useless empty crate when lockers do the same

**Comment by fludd12** [comment]
To my knowledge, the cargo UI doesn't put many at risk of freezes yet, and especially not the limited service tab of it. Additionally, it's worth noting that regardless of your view, there is no feasible way to obtain NT-standard plasteel crates at the moment besides ordering excess from cargo already.

I feel like the negative reactions towards this are somewhat over-exaggerating the impact of this PR. It could be argued that much, if not all, of my crossbreed project constitutes code bloat, but so far I have not seen negative commentary on it.

**Comment by SpacePrius** [comment]
Honestly, the cargo menu is one of the simplest UIs in the game in terms of actual code. Nothing changes besides the credit counter and the data is not very dynamic. The biggest concern for lag is the fact that it spawns objects but it doesn't even have anything in it which is the main source of lag in this regard.

**Comment by ATH1909** [comment]
Just use two sheets of metal in hand to make a locker (or ask a standard or engineering borg to do it for you; they get metal synthesizers). It's not that big of a problem.

**Comment by HomocidlePancakes** [comment]
Buy high sell low amarite guys?

**Comment by SpacePrius** [comment]
Its not that big of a problem, hence why the solution is 7 lines.

**Comment by SpacePrius** [comment]
Also, it isn't even sold at a loss, if you stamp the manifest you get your full 700 back.

**Comment by 81Denton** [comment]
Am I taking crazy pills or are you guys unironically arguing about empty crates

**Review by 81Denton — APPROVED** [review]

**Comment by SpacePrius** [comment]
God is dead and we have killed him

**Pull request merged**
