### PR TITLE
New BRPED Beam Sprite

### PR DESCRIPTION
**Pull request by WJohn**
Because the old one was baaaaaaaaaad.

:cl: WJohnston
imageadd: New and improved BRPED beam. The old one was hideous.
/:cl:

### CODE REVIEW

**Comment by davidchan13** [comment]
fwoooooooosh

**Comment by GunHog** [comment]
Nice WJ! Super quick work!

**Comment by OtherDalfite** [comment]
Sweet

**Comment by MrStonedOne** [comment]
please show old and new and show real size as well as zoomed in.

**Comment by WJohn** [comment]
The current one is this hideous piece of shit:


ANYTHING is an upgrade.

**Comment by Iamgoofball** [comment]
see

all you gotta do is make a codersprite and it will make a spriter #triggered so they fix it for you

**Pull request merged**
