### PR TITLE
Adds Nepetalactone

### PR DESCRIPTION
**Pull request by astralloop**
:cl: Astral 
add: Added Nepetalactone, which can be made with 2u carbon, 1u morphine, 1u mercury, and 1u sugar. It acts as a mild relaxant on normal humans... but causes very interesting (and funny) effects when exposed to mutant DNA.
/:cl:

Also, I added a new sound to the goon folder, because I couldn't find a better sound.

### CODE REVIEW

**Comment by Xhuis** [comment]
Nep
@Shadowlight213

**Comment by Xhuis** [comment]
Also, this PR is bad.

**Comment by astralloop** [comment]
@Xhuis why :(

**Comment by Xhuis** [comment]
Because it's just begging to start *more* drama over catpeople when we've already suffered through weeks upon weeks of endless debate about it, because there are people who unironically want to add as many in-game downsides as they can to any race or mutant parts that aren't default human.

**Comment by optimumtact** [comment]
support

**Comment by KorPhaeron** [comment]
Please carefully review our contributing guidelines

**Comment by arsserpentarium** [comment]
sad.

**Comment by astralloop** [comment]
@KorPhaeron who would I need "prior approval" from

**Pull request closed without merging**
