### PR TITLE
Revert "Adds webbing"

### PR DESCRIPTION
**Pull request by Bawhoppen**
Reverts tgstation/tgstation#27458

This PR was a half-assed change, had not come to a conclusion yet, nor was approved by WJ

### CODE REVIEW

**Comment by MrStonedOne** [comment]
I bet kor blackmailed oranges with threats of vetoing all of orange's prs.

It's the only thing that makes sense.

**Comment by WJohn** [comment]
Uh the sprites are actually quite fine in my opinion, but I have no input on the balance.

**Comment by FantasticFwoosh** [comment]
Suggestion: Draw a better one then and PR that.

**Comment by optimumtact** [comment]
I said it was up to me baw

**Comment by PKPenguin321** [comment]
oranges closing reverts to things he merges should stop

**Comment by Bawhoppen** [comment]
you're not allowed to do that reeeeeeeee

**Comment by optimumtact** [comment]
I am allowed, that isn't a rule yet

**Pull request closed without merging**
