### PR TITLE
Removes another potential github liability from the ion law json

### PR DESCRIPTION
**Pull request by Iamgoofball**
lets not gamble with this sort of thing imho

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
theres an entire .dmm file named this, either remove both or dont bother removing either, only removing 1 isn't gonna remove its liability.

**Comment by CRITAWAKETS** [comment]
i'd recommend removing the space ruin tbh, easily the worst one design-wise alongside being a poor attempt to have a hee hoo with a genocide

**Comment by Iamgoofball** [comment]
replacing the space ruin with a different once is on the todo list and i've got a mapper interested, they just need to wait until the freeze is over

**Comment by Razharas** [comment]
i dont know anything about these ruins or whatever but im against such behaviour towards arbitrary corporation standards on principle

**Comment by optimumtact** [comment]
if it becomes a problem I"m sure github will let us know.

**Pull request closed without merging**
