### PR TITLE
APOTHEOSIS! now forces you standing when you're in the death animation as a plasma skeleton.

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

APOTHEOSIS! adds the forcestanding trait when you perform APOTHEOSIS! during the animation where you exploded all your skin off and are just standing there moments before death.

## Why It's Good For The Game

I used to not need this but the resting rework made it so, so the cool standing at the center of an explosion before dropping dead is now proper

## Changelog

:cl:
fix: APOTHEOSIS! now forces you standing during your death animation, restoring the old (not forced) standing when I originally added APOTHEOSIS!
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
so awesome

**Comment by JohnFulpWillard** [comment]
monkeys with plasmafist dont actually do anything when shoving so you can't tell you're about to DIE

not related i just really wanted to tell someone

**Comment by tralezab** [comment]
> monkeys with plasmafist dont actually do anything when shoving so you can't tell you're about to DIE
> 
> not related i just really wanted to tell someone

weird

**Comment by Iamgoofball** [comment]
your content, no GBP

**Pull request merged**
