### PR TITLE
Fixing consistency issues in regards to plasmaman internals and jumpsuit

### LINKED ISSUE #32828: A couple of things I noticed as plasmaman
Server: Bagil

Revision: It gave me a whole bunch of information, I think this number is what I am supposed to give. 038998. If that's the wrong thing, it was today, 11/16/2017.

Problem Description: Pocket protector spawns on plasma envirosuit.

What did you expect to happen: I expected to not have a pocket protector on my plasma envirosuit, because I am unable to attach items like medals or pocket protectors manually.

What happened instead: I instead had one, and when I took the pocket protector off I could not put it back on again.

Why is this bad/What are the consequences: I think it should be consistent whether or not plasma envirosuits can have items like pocket protectors attached, either not have one spawn on it, or allow them to be attached.

Steps to reproduce the problem: Choose plasmaman as your race and atmos tech or something as your job at character setup.

I encountered a second issue, I am not sure if it's intended or not but I figured it was worth listing as well.

While I'm able to put my plasma internals tank in my suit slot when wearing a hardsuit, I am unable to put it in the same slot when wearing something like a firesuit, even though an oxygen internals tank is able to go there. I've noticed this for both firesuits and emergency firesuits, winter coats, hazard vests, and emergency life vests.

### PR DESCRIPTION
**Pull request by Garen7**
Fixes #32828, suits that allowed emergency oxygen tanks in their suit slot now allow plasma man tanks, also botany's winter coat can store emergency oxygen tanks just like the other coats now

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: tserpas1289
tweak: Any suit that could hold emergency oxygen tanks can now also hold plasma man internals
tweak: Hydroponics winter coats now can hold emergency oxygen tanks just like the other winter coats.
bugfix: Plasma men jumpsuits can now hold accessories like pocket protectors and medals.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Internals storage should be consistent between races and between the different winter coats. The same goes for the accessories issue, all other jump suits, including the sundress and griffon uniform, can equip accessories so plasma man jump suits should be able to also. Its worth noting that this was most likely unintentional as the proc that normally does this was overrode but did not call the parent proc.

### CODE REVIEW

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/011181d88b407d414cf70298555a3c232805b4c9/code/__DEFINES/inventory.dm#L217

Hit it here too please.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
see comment

**Comment by CosmicScientist** [comment]
Not necessarily for this PR to fix but I feel there are too many repeated lists in clothing that could be rewritten as variables within the file to draw from or inherited. Or both.

**Comment by Jalleo** [comment]
You should reference the issue that mentions this.

**Comment by tserpas1289** [comment]
oops my bad I'm new to this [https://github.com/tgstation/tgstation/issues/32828](url)

**Comment by CosmicScientist** [comment]
I think they mean put Fixes #32828 in the main post because I think it'll automatically close the issue? I don't know how github works or what bots are on this repo that sort stuff out but it's mentioned now.

**Pull request merged**
