### PR TITLE
Improves and syndicate-ifys nuke core container

### PR DESCRIPTION
**Pull request by ChangelingRain**
old
Old sprites.
newked
New sprites. The loaded core container is also animated; the red S scrolls left to right.
Also replaced the old plutonium core sprite with an animated one, even though you'll never see it short of admin fuckery.

### CODE REVIEW

**Comment by Core0verload** [comment]
:+1:

**Comment by Chocobro** [comment]
yeah my sprites for this were the fucking worst thanks to a shitty argument while I made it. shape and shading looks good, but I don't know why it needs to have a syndicate logo inside. i'd you're stealing the nanotrasen designed nuke on a nanotrasen owned station, why is there a syndicate part?

**Comment by Chocobro** [comment]
if you're stealing
(phone post also swype)

**Comment by Anonus** [comment]
Uh, because you're a syndicate hired to steal the shit out of the core?

**Comment by WJohn** [comment]
Every little bit helps.

**Comment by JJRcop** [comment]
@Anonus I think @Chocobro was getting at why not steal a nanotrasen core storage device, why did the syndicate bother manufacturing one?

**Comment by Anonus** [comment]
If the syndicate provides it, it should be syndicate-branded just as a general theme thing.

**Comment by Chocobro** [comment]
pretty sure the syndicate didn't provide it - it's inside the nuke on roundstart, right?

**Comment by JJRcop** [comment]
@Chocobro No no, not the core itself, the storage device.

**Comment by xxalpha** [comment]
The container is provided by the syndicate. Those look good.

Also the core is never actually seen.

**Pull request merged**
