### PR TITLE
Unhardcodes count and display of ores in ore box

### LINKED ISSUE #19706: The amount of Titanium you have does not show up in an ore box
Technically not a bug... but it kind of is

It's moreso coder oversight

### PR DESCRIPTION
**Pull request by Jordie0608**
Fixes #19706, see branch name
Don't know if this works, will test when I get home.

### CODE REVIEW

**Comment by optimumtact** [comment]
Good stuff

**Comment by Jordie0608** [comment]
From my testing it would seem that `uniqueList` is broken.

**Comment by Jordie0608** [comment]
Turns out it was the latter (kind of).

**Comment by optimumtact** [comment]
This code ugly af

**Comment by Jordie0608** [comment]
Are you going to miss those 53 lines of typecasting?

**Comment by optimumtact** [comment]
no

**Pull request merged**
