### PR TITLE
Adds emote bans

### PR DESCRIPTION
**Pull request by Shadowlight213**
Also fixes some holes where you could bypass emote mutes.
Moves OOC bans next to the other bans so they dont look so out of place.

### CODE REVIEW

**Comment by Xhuis** [comment]
# THE DESTROYER OF ERP
thumbsup

**Comment by Fallcon** [comment]
no

**Comment by Shadowlight213** [comment]
1 hour left

**Comment by daman997** [comment]
fun removal
really though could be useful for shit mimes and the such

**Comment by Iamgoofball** [comment]
# MERGE IT QUICK BOYS

**Comment by Shadowlight213** [comment]
@Jordie0608 @Razharas @WJohn @RemieRichards @phil235 @Cheridan @bs12-bot @Miauw62  
Merge please

**Comment by Jordie0608** [comment]
>pinging bs12-bot

**Pull request merged**
