### PR TITLE
Cult bola removal

### PR DESCRIPTION
**Pull request by NoxVS**
## About The Pull Request

Removes cult bolas entirely, summon equipment will simply give you the eldritch sword and cult armor.

## Why It's Good For The Game

While the original reason for this PR is soon to be fixed, I still think the cult bolas should be removed. One of the biggest problems I see in cult is how it has roundstart gear that is free to produce that outclasses anything the station can produce. In my opinion, this has resulted in significantly less interaction with the rest of the game, due to cultists being able to instantly create superior replacements to normally desirable objects - in this instance, a normal bola is completely ignored because you can pull a better version out of thin air. 

The same issue occurs with weapons and armor and I am planning on trying to work on that later even if this PR doesn't go through. 

## Changelog
:cl:
del: Cultist bolas have been removed
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
These aren't supposed to be stuns. Someone just broke knockdown.

**Comment by Rohesie** [comment]
Ohh, that is my fault. I'll go fix it.

**Comment by NoxVS** [comment]
Without a stun its just a normal bola and I dont see a point in it existing if you can just make one with metal and cable coil. Nar'sie is an eldritch god who wants to plunge the universe into darkness, not some welfare officer who goes around passing out bolas and weapons. Go make them yourself you edgy hippies. So much of what the game has to offer is entirely ignored because you can press a button and have a cult version delivered to you instantly.

**Comment by Rohesie** [comment]
It's not a normal bola, as it only affects non-cultists.

**Comment by wesoda25** [comment]
its fine and if its still op just nerf it again lol

**Comment by SkeletalElite** [comment]
> Without a stun its just a normal bola and I dont see a point in it existing if you can just make one with metal and cable coil. Nar'sie is an eldritch god who wants to plunge the universe into darkness, not some welfare officer who goes around passing out bolas and weapons. Go make them yourself you edgy hippies. So much of what the game has to offer is entirely ignored because you can press a button and have a cult version delivered to you instantly.

It also isn't just a normal bola. It's supposed to be knockdown not a stun. Regular bolas do not knockdown or stun. Only reinforced ones that come in the tot throwing kit do.

**Comment by Coastfront** [comment]
Knockdowns are broken atm normally, the cult & reinforced bolas are the onlyones that apply knockdown no bolas stun. They arent useless and/or broken they are just a slightly better bola.

**Comment by CRITAWAKETS** [comment]
"One of the biggest problems I see in cult is how it has roundstart gear that is free to produce that outclasses anything the station can produce. In my opinion, this has resulted in significantly less interaction with the rest of the game, due to cultists being able to instantly create superior replacements to normally desirable objects"

okay in that case you should PR the removal of the traitor uplink aswell

**Comment by OverlyGeneric** [comment]
fix knockdown. 

remove bola.

then let cults make traps for defense and trap people who wander maintenance.

**Comment by Rohesie** [comment]
Knockdown is fixed in #50321

**Comment by Shadowflame909** [comment]
It's a shame how destruction is always easier than creation.

**Comment by NoxVS** [comment]
> okay in that case you should PR the removal of the traitor uplink aswell, why be so laser-focused on cult with your changes?
The uplink has a limit on how much you can do, you can't rely on it entirely. The same problem would happen if everything was free and able to be purchased in infinite quantities. You are given some traitor items to have fun with but not so much that you can  just ignore anything outside of being a traitor, you still need to interact with the rest of the game

**Comment by Rohesie** [comment]
Why not make the creation of cult bolas require some resource consumption instead?

**Comment by Shadowflame909** [comment]
Just sounds like you have a problem with the way cult is designed.

Cult is not traitor.

They get dark powers with blood consumption as it's cost.

Your issue could also apply to changelings, who as well have infinite amounts of uses for tools and don't need to interact with any aspect of the game. (Healing, Crafting, Armor, ETC. All granted to them roundstart.)

**Comment by necromanceranne** [comment]
'Blood consumption as it's cost'

Actually this isn't true. They have no resource gate. Their spells dp damage to them but in reality they have no actual limit to how often they can cast their spells. The only limits that exist is timers on cult structures and even that can be circumvented by making more of them.

**Comment by Shadowflame909** [comment]
Should be its cost.

I know that's how it works with some spells, like the ghost jaunting, and the ghost summoning. 

Funny how the only spells with drawbacks are the ones that involve interaction with players already out of the round.

**Comment by SkeletalElite** [comment]
> Should be its cost.
> 
> I know that's how it works with some spells, like the ghost jaunting, and the ghost summoning.
> 
> Funny how the only spells with drawbacks are the ones that involve interaction with players already out of the round.

Those spells just deal damage to you, with a few pylons you can actually do them forever because you're still healed while channeling them

**Comment by Victor239** [comment]
I ded

**Comment by optimumtact** [comment]
the stun is fixed, if you still feel this is a problem in three weeks, remake the PR

**Pull request closed without merging**
