### PR TITLE
Roboticists now have access to open the R&D windoors.

### PR DESCRIPTION
**Pull request by ghost**
Roboticists can now open R&D windoors.

:cl:
tweak: roboticists have access to R&D windoors
/:cl:

[why]: because they already can open R&D doors, so they should be able to open R&D windoors as well

### CODE REVIEW

**Comment by theo2003** [comment]
I didn't request a review from ShizCalev. Is this automatic?

**Review by ShizCalev — DISMISSED** [review]

**Comment by newfren** [comment]
Can this extend to geneticists too? They can also access the doors but not the windoors.

**Comment by theo2003** [comment]
Geneticists cannot open the R&D doors unless they have additional access from low player count. If they do have additional access they can open the windoors.

**Comment by theo2003** [comment]
Just realized I forgot some windoors in meta and delta. Amended the commit.

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
