### PR TITLE
Blobs can no longer spawn if shuttle is close enough to station

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
tweak: Blobs can no longer spawn if shuttle is close enough to station
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
more salty prs from people who are permabanned from tg.

**Comment by Buggy123** [comment]
No no no no no. Enough of this crap.

**Comment by Buggy123** [comment]
This is like when fuckheads keep trying to pass PIPA or SOPA or FIFA or whatever the fuck they decide to call it, again and again year after year, changing one teeny little thing so that its technically different. Eventually the public get bored and stop trying to stop them and then it fucking works.

Stop with this crap, close it immediately, blob is fine.

**Comment by Doppeltongue** [comment]
Blob is easy to deal with (easy enough where it became a side antag) unless the station got completely fucked up. Solution: if you're an antag who wants the shuttle to leave, don't completely fuck up the station or face consequences.

**Comment by MoreRobustThanYou** [comment]
This is to basically prevent blobs from spawning when the shuttle is 2 minutes away and enraging every single ghost during a super-shitty round

**Comment by 81Denton** [comment]
#33327 had the same topic 8 days ago.

**Comment by ShizCalev** [comment]
So what exactly is the difference between the blob spawning at the 4:30 mark after calling and 5:00? I don't see the point.

(Recall is locked at <5 min, not 2.)

**Comment by ShizCalev** [comment]
image

**Pull request closed without merging**
