### PR TITLE
Moves Metastation's circuit lab to be against a main hallway

### PR DESCRIPTION
**Pull request by Metekillot**
## About The Pull Request

Circuits are comparatively rare for people to fiddle with than the rest of what science has going on. As such, to encourage people to use them more or to just even peek in and be nosy, I moved MetaStation's circuit lab to be off of the hallways leading to escape.

As well, its three points of entrance/exit encourage anyone working here to go through the main hallway to get back to science, rather than staying holed up in their department. They could go through maintenance, but who knows what's in there.

### Shrunk the experimentation lab and put an empty crate in there
Screenshot 2024-06-24 204902

### Made the bordering maintenance area look hastily cleared out, including a forgotten r-wall and a lack of doors
Screenshot 2024-06-24 204851

### The new circuit lab, directly south of genetics; three points of ingress and egress through the hallway, genetics, or maintenance
Screenshot 2024-06-24 213632

## Why It's Good For The Game

Encourages people to peek into the circuit lab and maybe ask the RD to EA the door against the public hallway to do some experimenting themself.
Encourages scientists working in the circuit lab to wander the main hall just a bit to interact with others.
Gives the Geneticists human interaction.
## Changelog
:cl:
code: MetaStation's circuit lab is now near departures, right beside genetics.
/:cl:

### CODE REVIEW

**Comment by Vect0r2** [comment]
Photos please?

**Comment by MrMelbert** [comment]
Needs a desk at the very least if you're going through the effort to move it besides the hallway

**Comment by Jolly-66** [comment]
Beep boop you're failing some unit tests

image

image

image

**Comment by DaCoolBoss** [comment]
What are you planning on putting in the old circuit lab's place? Moving experiment or left and filling the void with maints?

**Comment by moocowswag** [comment]
Its pretty weird seeing the circuit lab the only room in sci that is disconnected from the rest of sci and is not surrounded by reinforced walls like the entire rest of sci.

**Comment by Metekillot** [comment]
I'm doing Meta because it's the most popular map and I want to see if this encourages more departmental interaction with science besides ringing the desk bell and asking for parts.

Regarding the reinforced walls: The circuit lab isn't a high destructive potential area like almost every other science department. Any heinous tomfoolery involving circuits also requires other parts that are usually behind those rwalls.

Furthermore, I just think that most maps have too many rwalls everywhere, but beside the point.

Posted as draft to get input, which I'm currently getting so mission accomplished

**Comment by Inari-Whitebear** [comment]
While a good change, I think circuits largely don't get tinkered with for reasons other than "they're not in people's face". Such as being gated behind research people don't want to research to "waste" points on. Circuits not being that easily save-able/recreatable. And there just not being a whole lot of circuits with a good usecase

**Comment by san7890** [comment]
i don't like how empty/bland the experimentation lab looks, please consider something to do to "tighten" up that space (maybe allocate more to maintenance). at the very least change up the floors so it doesn't seem so bare

**Comment by dragomagol** [comment]
Conflicting

**Comment by Metekillot** [comment]
I'll do merge resolution soon, can't today because I've gotten sick from the heat

**Pull request closed without merging**
