### PR TITLE
Less ash lizard starting loot

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
No more whetstones, GPS, or combat medkit (so no NVG/combat defib).

They have some other goodies though including a hat to designate their leader. 

Hopefully weaker starting gear+miners not being so slow will make them manageable.

:cl: Kor
rscadd: Ash walker starting gear has been rebalanced. 
rscadd: Ash walkers can no longer use guns.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
>AI malfupgrade

**Comment by Aloraydrel** [comment]
rogue lizards

**Comment by TheNightingale** [comment]
Giving them something to deal with goliaths would be useful; one ashwalker is powerless against a goliath, since their only weapons are spears (and a scythe, which is a weaker spear). The previous best option was a sharpened spear (by using a whetstone), but this isn't available now. An upgraded kinetic accelerator, perhaps (giving miners some fun loot if they find the ashwalker nest)?

**Comment by Shadowlight213** [comment]
@KorPhaeron :-1: on the AI malf upgrade. It should be admin only.
Do the surveillance one instead.

**Comment by TankNut** [comment]
:+1: on the no guns change. As fun as it is it's quite easy for the ash walkers to absolutely snowball out of control if they get their hands on tasers and miner ID's. The latter of which is already quite easy to do if you catch the shaft miners in an area where their KA doesn't do it's full damage.

**Comment by KorPhaeron** [comment]
>one ashwalker is powerless against a goliath

Good thing you start with friends then. Teamwork is core to lavalands design.

**Comment by KorPhaeron** [comment]
@Shadowlight213 

I think it's a proper reward for the station organizing enough to go smash the endless lizard respawn in the middle of the hellish wastes

**Pull request merged**
