### PR TITLE
Resprites: Antag mechs

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Gives antag (centcom, Nukie) mechs a fresh layer of paint and resprites them! Also, touches on Phazon - makes it visually closer to other mechs.

## Why It's Good For The Game

Refreshes the marauder family of mechs, making them look better (TM). Adjusts colors of Dark Gygax/Phazon to give them more accurate colors, apparently!

OLD MAULER:
mechs_united_marauders

NEW MAULER (DARKER):
image

## Changelog

:cl: sprites by INFRARED_BARON
image: New icons for Marauder, Seraph, Mauler and adjusts the Phazon/Dark Gygax's sprites.
/:cl:

### CODE REVIEW

**Comment by zoomachina** [comment]
Mauler is way too gray

**Comment by mc-oofert** [comment]
done better but still worse than the old sprites because neither mechs are as glowy as the previous ones and the colors are too gray

**Comment by Livrah** [comment]
Looks worse and weirdy grey.

**Comment by githubuser4141** [comment]
> Looks worse and weirdy grey.



> Mauler is way too gray Edit: I might be wrong, but it looks like you removed sprite animations from these 3 mechs

correct, the moving LED lights aren't present in the new sprites. I'll wait for spritetainer feedback first though.

**Comment by Xackii** [comment]
fortnite mechs

**Comment by MTandi** [comment]
I wish it had more specular highlights and/or more contrast. It looks like it's plastic or has some weird matte paint job. 

Making it more metallic would make it look heavier and more dangerous, rather than resembling a toy.

And the glowing eyes are a must.

**Comment by SomeoneYouProbablyKnow** [comment]
These look good upclose but they are gonna turn into grey blobs on any small-ish screen. In my opinion you could use more contrast and highlights, the lit up underside on the the grey NT mech did a lot of heavy lifting for readability but you replaced it with a simple armour plate. The wider sections under the knees did quite a bit for the silhouette too. 

Honestly if you gonna resprite the mechs might as well add some flavour to them, we change sprites constantly, older ones are not beyond reproach.

**Comment by paganiy** [comment]
gooning 🤤

**Comment by Deultus** [comment]
Too bright, it's bad

**Comment by Xkallubar** [comment]
Please no

**Comment by EuclidianGeometer** [comment]
the contrast is too low, your eyes slide off it. while the old sprites are further from current tgstation style, they pop much more due to the lights contrasting with the frames really nicely, and the fewer tones used overall. The hard black lines certainly help too. 

These look much more similar to each other after your redesign. obviously they were all working off the same base sprite, but the color choices are very similar to each other, to the point i'd find it difficult to tell which is which, comp

I like the bulkier shapes of the originals more, they pop nicely, though i'll grant that the shilouettes of your mechs are clearer.

**Comment by LSommers** [comment]
This suffer from the same issue as prior sprites you've PR'd- It's too indistinct.
There are large swathes of color that just run into each other, colors are too similar and run together, and details are removed that frankly should not have been. 

More specific to this particular resprite- Armor plates that were meant to be easily visible _as segmented plates_ now look like roughly sculpted clay. The glowing eyes of danger are missing, the detail of various lights and under-mechanisms are missing, etc.

**Comment by ElPidor** [comment]
What the fuck is that, Get an actual art degree, the old sprites have idea and designe, New one are just deffirent colours, but it have one plus 
more colours, But god please make it less lighter, just add some good thing, or else pixel art is just not your thing

**Comment by LSommers** [comment]
> What the fuck is that, Get an actual art degree, the old sprites have idea and designe, New one are just deffirent colours, but it have one plus more colours, But god please make it less lighter, just add some good thing, or else pixel art is just not your thing

Jesus Christ dude, calm down and spell-check.

**Comment by MTandi** [comment]
> I wish it had more specular highlights and/or more contrast. It looks like it's plastic or has some weird matte paint job.
> 
> Making it more metallic would make it look heavier and more dangerous, rather than resembling a toy.
> 
> And the glowing eyes are a must.

Kinda

image

**Comment by githubuser4141** [comment]
> What the fuck is that, Get an actual art degree, the old sprites have idea and designe, New one are just deffirent colours, but it have one plus more colours, But god please make it less lighter, just add some good thing, or else pixel art is just not your thing

I'm not the artist, why weren't you on the spriting channel when it was being drawn if you care so much?

**Comment by zoomachina** [comment]
> > What the fuck is that, Get an actual art degree, the old sprites have idea and designe, New one are just deffirent colours, but it have one plus more colours, But god please make it less lighter, just add some good thing, or else pixel art is just not your thing
> 
> I'm not the artist, why weren't you on the spriting channel when it was being drawn if you care so much?
> 
> What feedback seems to boil down to is 'more gamer-rated LED lights like real life tanks (lol), make the details _pop_ more'

"You must be a part of our discord group, otherwise your opinion doesn't matter"

**Comment by CRITAWAKETS** [comment]
I feel like the Mauler should have a darker color palette, right now it's a little too bright for the DARK mauler.

**Comment by zoomachina** [comment]
For comparison, I've pasted old and new sprites onto some footage from a recent nukie round.
comp1
comp2
comp3
comp4

**Comment by Xackii** [comment]
> For comparison, I've pasted old and new sprites onto some footage from a recent nukie round. comp1 comp2 comp3 comp4

I initially thought that the left one was a resprite

**Comment by githubuser4141** [comment]
> > For comparison, I've pasted old and new sprites onto some footage from a recent nukie round. comp1 comp2 comp3 comp4
> 
> I initially thought that the left one was a resprite

why would they downgrade the sprites when the problem is a simple recolor/re-light? The one on the left is a massive downgrade technically speaking

**Comment by infraredbaron** [comment]
One of alternative palettes that was posted days ago in dedicated spriting channel on TG discord:
image

**Comment by githubuser4141** [comment]
Updated to make dgygaxes and maulers darker.

**Comment by Ghostkokos** [comment]
DARKER mauler It looks pretty good compared to the gray one. Indeed, there is a noticeable improvement. At least compared to other mechs of this PR and the previous one 😄 
I would like to see a real improvement in the sprites of past mechs

**Comment by EuclidianGeometer** [comment]
While I personally still think it's a bit grey and am hoping that the lights of the old mechs return, this is much better than the last palette.

**Pull request merged**
