### PR TITLE
Bug fix boogaloo, etc...

### LINKED ISSUE #12138: When jaunting, wizards can't move while cuffed and being dragged
get cuffed, get dragged, can't jaunt away because being pulled

### LINKED ISSUE #12141: Monkeys can use Hand Labelers to communicate
Discovered this today. Making a note for myself.

### LINKED ISSUE #12180: Morphs dying creates piles with way too many items
Currently EVERY item a morph absorbs gets released into a single pile when it dies. These piles are so large that there is a good chance of locking up the game client when right clicking them. This is of course always an issue with piles containing too many items but the morph amplifies this problem.

proposed solution: spread the items over a 3x3 grid centred on the morph when it dies.

### LINKED ISSUE #12211: Unlimited stunprod
Inject plasma in stunprod cell
Put cell in stunprod
Use stunprod
Explode
Stunprod is now infinite

### LINKED ISSUE #12214: Bodies in zero G leave blood trails
floatblood when??

### LINKED ISSUE #12243: Stand battlecry makes 2much spam
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"

### PR DESCRIPTION
**Pull request by phil235**
- Fixes not being able to move during jaunting if you are cuffed and pulled. Fixes #12138 
- Greenglow decal no longer disappears after 2 minutes.
- Fixes runtime with explosive implant activation.
- Fixes stunbaton infinite cell charge, the baton now turns off if you try using it after its cell has been deleted somehow. Fixes #12211.
- Fixes bloody pulled mob leaving a blood trail in zero G. Fixes #12214 
- Shortens the guardian battlecry message when attacking to lower chat spam. Fixes #12243
  <s>\* Items in Morph now disperses a bit on death instead of being all on the same tile.
- <b>After reaching a limit of 50 items, morph swallowing items deletes them instead of putting them inside the morph.</b></s>
- Monkeys can no longer modify the hand labeller's text to communicate. Fixes #12141 
- Fixes carbon,radium,uranium 's reaction_turf creating multiple decal on a tile, it now checks if there's already a decal of the relevant type and (for radium and uranium) only transfers reagent to it if it finds one.
- Fixes butchering, it no longer does both an attack and butchering at the same time.
- Morph no longer automatically drop its content on death, you have to butcher it to retrieve the content, 10 items at a time.
- And those items are spread in a one tile radius to avoid having too many things on one tile).  Fixes #12180
- The morph also drops generic meat (and gibs) during final butchering (it's only because it needed to drop something to be able to be butchered, feel free to change the meat to something else)

### CODE REVIEW

**Comment by Strathcona** [comment]
I feel like deleting items swallowed by a morph is inelegant. There should be a better solution since proficient morphs can go through hundreds of items some rounds, potentially deleting valuable items that would normally be a reward for killing it. I wouldn't mind scattering them around the corpse or at least applying an acid to them since that's much more consistent with other game mechanics.

**Comment by Incoming5643** [comment]
if the morph ate boxes it could automatically fill them with other devoured items of proper size?

**Comment by AnonymousNow** [comment]
I also disagree with the way morph swallowing is being handled. Make it a sort of organic explosion, like everything's being flung out in different directions by a grav catapult.

**Comment by Lumipharon** [comment]
Rather then it vomiting everything up on death, why don't you make the morph have to be cut open with a knife, to get all the shit out?

It also makes it more similar to other animls that you can knife up for stuff.

**Comment by WJohn** [comment]
I agree with lumi. Why not make knifing it extract 10 items per use?

**Comment by Bawhoppen** [comment]
That would be my favorable solution.

**Comment by phil235** [comment]
@WJohn @Lumipharon That's actually a great idea! Will use that instead.

**Comment by bgobandit** [comment]
that is also a better solution because you KNOW some asshole will eat 50 cigarette butts or pieces o paper or rods and then start eating the important stuff to get rid of it forever

**Comment by CPTANT** [comment]
Exploding loot pinjatata sounds a lot more fun than deleting stuff right away.

**Comment by CPTANT** [comment]
"first in, first out" is way more logical if the item deletion option is chosen by the way.

**Comment by WJohn** [comment]
Actually yeah what cptant said. When gutting the morph, it should launch them in every direction and also make gibs (and gib sounds) and slabs of meat. Pinatas are fun!

**Comment by phil235** [comment]
Alright, new changes:
 * Fixes butchering, it no longer does both an attack and butchering at the same time.
* Morph no longer automatically drop its content on death, you have to butcher it to retrieve the content, 10 items at a time.
* And those items are spread in a one tile radius to avoid having too many things on one tile).
*The morph also drops generic meat (and gibs) during final butchering (it's only because it needed to drop something to be able to be butchered, feel free to change the meat to something else)

Added changelog

**Pull request merged**
