### PR TITLE
Changes entertainment radio to be darker

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

I made the entertainment radio text a little less eye-searing.

image
image
image
## Why It's Good For The Game

I'm sure it looked kind of okay on dark mode, but for us light mode heathens, entertainment chat could be kind of hard to read sometimes. This shade looks better and, while not as bright, I think fits the role better - I went for something similar to the kind of blue/grey of a reporter's suit.
## Changelog
:cl: Vekter
fix: Changed the color of entertainment radio to be darker
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
> You should also change the comments mentioning its color as "Teal" as now its more of a "Camo"

Sure, but this is more "teal" than the original lime fucking green was.

**Comment by MrMelbert** [comment]
> I'm sure it looked kind of okay on dark mode, but for us light mode heathens, entertainment chat could be kind of hard to read sometimes

JSYK you can make the light mode color and the dark mode color separate, so you can keep dark mode the same but change light mode

**Comment by MrMelbert** [comment]
(I think the new dark mode color is a little too muted)

**Comment by TheVekter** [comment]
> > I'm sure it looked kind of okay on dark mode, but for us light mode heathens, entertainment chat could be kind of hard to read sometimes
> 
> JSYK you can make the light mode color and the dark mode color separate, so you can keep dark mode the same but change light mode

I know, but it was a dramatic enough change of colors that I didn't want one to look completely different than the other.

> (I think the new dark mode color is a little too muted)

(I disagree, I think it looks fine, but I can increase the white balance a little

**Comment by TheVekter** [comment]
I updated the dark mode color, screenshot in OP is accurate.

**Pull request merged**
