### PR TITLE
Clock cults always have to summon Ratvar, but that always involves a proselytization burst

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Clock cults always have to summon Ratvar, but that always involves a proselytization burst.
rscdel: The proselytization burst will no longer convert heretics, leaving Ratvar free to chase them down.
spellcheck: Places that referred to the Ark of the Clockwork Justicar as the "Gateway to the Celestial Derelict" have been corrected to always refer to the Ark.
/:cl:

The proselytization burst is so cool, but if you see it you can't do a ton of cool shit because Ratvar isn't up, and if Ratvar IS up, then you need to manually prosel a lot of shit.
So, best of both worlds.

### CODE REVIEW

**Comment by TehZombehz** [comment]
Team Ratvar T-shirts available when?

**Comment by FantasticFwoosh** [comment]
Summoning narsie has a effect of gibbing the cultists. 

Why couldn't ratvar just deconstruct and claim peoples souls in a smite action in order to add them lorewise to the atomic progression of time? Also so that the final ritual is one of self sacrifice and only the constructs leave on the ship.

> Ratvar comes in and eats your entire race as a space god to help weave the future fabric of time out of your souls. Allows free reincarnation as independent guardian spirits with the purple flame gimmick to chase people down.

**Comment by XDTM** [comment]
No more roundend griefmobs

**Comment by evsey9** [comment]
@FantasticFwoosh we dont need any more reasons for the crew to hate on ratvar cultists

**Comment by FantasticFwoosh** [comment]
Other than having no reprecussions to 'winning' a round where they have competed their ulterior objective and can just walk away with a pat on the back and are just instant converted when caught. Watching people be harvested is much more gratifying.

**Comment by ChangelingRain** [comment]
Ratvar is not going to eat/whatever his own servants at all, ever, because I think half of the problem with bloodcult is that nobody really wants to summon nar-sie, because all you get is turned into a shitty harvester, which isn't even that fun.
I might(and by might I mean won't) make Ratvar explode non-servants, but his own servants will always remain alive.

**Pull request merged**
