### PR TITLE
[WAWA] updates medbay with a few more lights

### PR DESCRIPTION
**Pull request by wonderinghost**
## About The Pull Request

brightens up wawa med with a few more lights in the central area and minor shifts in device placement

## Why It's Good For The Game

you cant look at this and say that this dark spot is good 

(before)
image

(after)
image
## Changelog

:cl:

add: Adds a few lights 
fix: removes the darkspot in wawa med
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
looks to be map dif bot being weird

**Comment by wonderinghost** [comment]
i dont know whats going on but seems to be hiding a light

**Comment by mc-oofert** [comment]
I think there was a light there already

**Comment by wonderinghost** [comment]
Unless there was a recent update that so happened added a light there then yeah

Wonder if there is a issue with z levels having lights sharing a tile even though they are on different z levels

**Comment by wonderinghost** [comment]
But that lower portion of medbay didn't have light

**Comment by wonderinghost** [comment]
here is a image from a up to date branch i havent altered 
image

**Comment by wonderinghost** [comment]
wait a minute

**Comment by wonderinghost** [comment]
guess there was. possibly the chance for it to break was so often that you think its gone

**Comment by MoonDeer728** [comment]
remove this shit station

**Comment by wonderinghost** [comment]
Improve it first

**Comment by mc-oofert** [comment]
> guess there was. possibly the chance for it to break was so often that you think its gone 

there is a map test define that disables random breaking of stuff

**Comment by mc-oofert** [comment]
> remove this shit station

won't happen and I'm sure you know why

**Comment by Time-Green** [comment]
> remove this shit station

User was obliterated for this post

**Comment by Ghommie** [comment]
Looking at the code, it seems it's only adding a light to the kirby plant location but not on that of the glass table, unlike what is shown on the screenshot. Did someone else do that bit already or did you mess up when merging?

**Comment by wonderinghost** [comment]
Im guessing the bottom light was var edited to be off. It has definitely been there before but when testing and checking the light does come on. 

Normally during rounds on Wawa I see that specific light off, since it's normally off (or broken) It came across as no light being there

**Comment by mc-oofert** [comment]
> Im guessing the bottom light was var edited to be off. It has definitely been there before but when testing and checking the light does come on.
> 
> Normally during rounds on Wawa I see that specific light off, since it's normally off (or broken) It came across as no light being there

its a normal light fixture with no var edits

**Comment by wonderinghost** [comment]
Weird

**Comment by wonderinghost** [comment]
Once I get home I got to see if that light ever comes on normally

**Comment by wonderinghost** [comment]
nope that light does work. in that case im going to slide a few things around

**Pull request merged**
