### PR TITLE
Plasma blasts, temperature beams, etc are now deflectable

### PR DESCRIPTION
**Pull request by ghost**
Energy projectiles that weren't subtypes of projectile/energy are now deflectable

:cl: More Robust Than You
fix: Plasma blasts, temperature beams, etc are now deflectable
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
We don't need everything to be the same.

**Comment by MoreRobustThanYou** [comment]
@Bawhoppen the temp gun shouldn't be powerful. right now it can be used to kill **DEATHSQUADS**, desworders, etc

**Comment by ShadowDeath6** [comment]
>>>>>>>double esworders


https://github.com/tgstation/tgstation/issues/11017

**Comment by PKPenguin321** [comment]
\>he's nerfing the temp gun

**Comment by ACCount12** [comment]
Plasma blasts are physical bursts of resonating plasma. I added them, so my headcanon on them must be worth something.

**Comment by kevinz000** [comment]
image

**Comment by Bawhoppen** [comment]
I mean PRs that just change like a var or edit a value of something are usually the worst PRs. If it were something that should've been done along time ago, it WOULD have been done since it's so easy.

**Comment by KorPhaeron** [comment]
@kevinz000 I thought you already fixed being unable to block these, is this just for reflecting them away in addition to the block?

**Comment by XDTM** [comment]
👍  for consistency

The real issue is that deswords apparently counter so many weapons at once that the temp gun seems like a viable weapon against them

**Comment by duncathan** [comment]
>nerfing the temperature gun

what the hell happened???

**Comment by MoreRobustThanYou** [comment]
@duncathan i got killed while de-swording by a sec officer with a temp gun

**Comment by MoreRobustThanYou** [comment]
@XDTM for deswords, don't run away while shooting them with a tempgun. get a shotgun or throw floortiles at em!

**Comment by PKPenguin321** [comment]
>>>>>>>he died to a temp gun

**Comment by JJRcop** [comment]
I am indifferent, but I'm downvoting to nullify MRTY upvoting his own pr.

**Comment by ExcessiveUseOfCobblestone** [comment]
Add I Ded immediately.

**Comment by newfren** [comment]
h e d i e d t o a t e m p g u n

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/tgstation/issues/11017

**Comment by ShadowDeath6** [comment]
I already linked that issue pk, get with the times please

**Comment by Robustin** [comment]
Temp Gun needs to be de-snowflaked. It looks like an energy beam, acts like an energy beam, but basically ignores everything designed to resist energy weapons or temperature.

**Comment by ExcessiveUseOfCobblestone** [comment]
There is nothing wrong with the temp gun.

**Comment by SgtxRootbeer** [comment]
here's a thought, maybe add an emp_act to the double e-sword, like the energy guns and whatnot have, the *energy* sword should be vulnerable to emps too!

**Comment by kevinz000** [comment]
@KorPhaeron he's making them fully reflectable instead of just blocks.
Also blocks were never fixed

**Comment by kevinz000** [comment]
Now I wonder if the guy I dunked yesterday with a tempgun was actually mrty evading.
Also go make your dumb fucking balance changes on hippie.

**Comment by Iamgoofball** [comment]
yo who buffed the tempgun

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Un-nerf the tempgun

**Comment by MoreRobustThanYou** [comment]
fuck no

**Pull request closed without merging**
