### PR TITLE
Adds mute quirk

### PR DESCRIPTION
**Pull request by Mothblocks**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl:
add: Adds the mute quirk for +2 points.
/:cl:

[why]: # Someone suggested it on the forums and it seemed easy enough.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
can it be fixed by taking mutadone?

**Comment by Jared-Fogle** [comment]
I'm under the assumption you can't fix quirk traits with mutadone. I'll test it out.

**Comment by Mickyan** [comment]
No way this is worth 3 points, especially so when it's free points for mimes

**Comment by Jared-Fogle** [comment]
What do you suggest?

**Comment by Mickyan** [comment]
2 would be fine

**Comment by Ratvar** [comment]
Force mimes to take it.
And force clowns to have clumsy quirk.

**Pull request closed without merging**
