### PR TITLE
Adds survival pod windows to the code

### PR DESCRIPTION
**Pull request by ChangelingRain**
Also adds vertical pod airlocks and a few of the more necessary overlays to pod airlocks.
example pods
Example escape pods(these are not added)
bolts+panel emergency lights
Bolts+panel open and emergency lights.

### CODE REVIEW

**Comment by Supermichael777** [comment]
i like the more industrial feel rather then the clean white and blue that looks like it gets polished 8 hours a day.

**Comment by Jalleo** [comment]
Why arent the walls smooth?

**Comment by KazeEspada** [comment]
That's their design, a line every 18 pixels.

**Comment by Bawhoppen** [comment]
this doesn't actually change the station pods though right

**Comment by ChangelingRain** [comment]
Yes correct it says that in the OP
If it did there'd be a changelog

**Comment by Bawhoppen** [comment]
that parentheses was hidden away

**Comment by Ausops** [comment]
those engine sprites need a good shoah or two

**Pull request merged**
