### PR TITLE
Updates Holopad code to use AltClick

### PR DESCRIPTION
**Pull request by RemieRichards**
Kor is lazy.

:cl: Remie + Kor
tweak: Holopads now use AltClick to request the AI
/:cl:

### CODE REVIEW

**Comment by duncathan** [comment]
:+1:

**Comment by KorPhaeron** [comment]
Changelog please

**Comment by CosmicScientist** [comment]
:+1:

**Comment by kingofkosmos** [comment]
Other things which have altclick-functionality have a note of it in description. Could holopads have as well?

**Pull request merged**
