### PR TITLE
The sprite for engi goggles is yellow and not green in meson mode

### PR DESCRIPTION
**Pull request by mgweave**
## About The Pull Request
#76596 changed engi scanner goggles to be green in meson mode, but the vision tint was still yellow. Originally I wanted to make the tint green (#76630), but it seems that people like yellow engi mesons more, so I changed the sprite instead. I copied the glass part of atmos-thermal mode t-ray goggles onto the engi goggles.
Before:
trayson-meson-prev
After:
trayson-meson
Also atmos thermal imaging goggles are now green to avoid confusion
## Why It's Good For The Game
Sprite color matches the vision tint
## Changelog
:cl:
image: Engineering scanner goggles are now yellow and not green when in meson mode
image: Atmospheric thermal imaging goggles are now green
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
could you do the same thing to the atmospheric temp and shuttle goggles? the atmospheric ones look exactly like mesons after your change, and shuttle goggles look exactly like traitor thermals now

**Comment by cnleth** [comment]
> could you do the same thing to the atmospheric temp and shuttle goggles? the atmospheric ones look exactly like mesons after your change, and shuttle goggles look exactly like traitor thermals now

engi goggles and atmos goggles have a different thing (antenna?) on their frame
meson
atmos

**Comment by Youtubeboy139** [comment]
> > could you do the same thing to the atmospheric temp and shuttle goggles? the atmospheric ones look exactly like mesons after your change, and shuttle goggles look exactly like traitor thermals now
> 
> engi goggles and atmos goggles have a different thing (antenna?) on their frame meson atmos Same thing for shuttle goggles, they have an antenna unlike thermals

I just switched the colors for the `trayson-atmospheric-thermal` and `trayson-meson` goggles. I'd just switch them back to their original colors because the antenna difference is so small that it might confuse players.
Screenshot 2023-07-08 121147

**Comment by cnleth** [comment]
Changed the atmos goggles to be green, as suggested
trayson-atmos-new

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
