### PR TITLE
Adds sunglasses to the autolathe!

### PR DESCRIPTION
**Pull request by lilacrhododendron**
:cl: 
add: You can now print sunglasses in the autolathe.
/:cl:

firefox_2019-01-02_12-11-36

### CODE REVIEW

**Comment by optimumtact** [comment]
I already told you I was not interested in this. Counters to flashes are meant to be rare.

This is not the way to fix borg balance either.

Closing this at 24 hours.

**Comment by ExcessiveUseOfCobblestone** [comment]
LOL

**Comment by subject217** [comment]
24 hour rule

**Comment by ExcessiveUseOfCobblestone** [comment]
the rules don't apply to those who rate their own PRs

**Comment by subject217** [comment]
?

**Pull request closed without merging**
