### PR TITLE
Resprites the Runite Bar and its stacks

### PR DESCRIPTION
**Pull request by AdipemDragon**
## About The Pull Request
Just about what it says on the tin, gives the Runite Bars a crispier look, and I'd imagine them Not Being Assets From Another Game is a nice bonus.
image

## Why It's Good For The Game
image

## Changelog

:cl:
imageadd: For those who seek out rarer materials, Runite Bars have a nicer appearance.
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Honestly quite incredible

**Comment by cacogen** [comment]
looks delicious

**Comment by Serxule** [comment]
> looks delicious

it really do look like a cake

**Comment by Farquaar** [comment]
> > looks delicious
> 
> it really do look like a cake

Looks more like blueberry hubba bubba to me

**Pull request merged**
