### PR TITLE
makes assistants start with orange jumpsuits instead of grey (D BOYS)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Qbopper** [comment]
don't close this pr

**Comment by TheGrandArchives** [comment]
yes

**Comment by epicmemename** [comment]
D BOYSSSS

**Comment by francinum** [comment]
yes

**Comment by Shadowflame909** [comment]
When will xhuis give us a scp-173 version of gluttonys blessing?? I guess it'd basically just be like, the space ninja's net + radiation death.

**Comment by Kraseo** [comment]
D BOIS

**Comment by Hatterhat** [comment]
D BOYS

**Comment by Jordie0608** [comment]
D-nied

**Comment by Hatterhat** [comment]
fuck

**Comment by epicmemename** [comment]
reopen it

**Comment by Shadowflame909** [comment]
How do we merge the two branches of /tg/ into one.

**Comment by Anonmare** [comment]
**Howl**

**Pull request closed without merging**
