### PR TITLE
Electrolysis works with enriched liquid electricity

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Electrolysis reaction seems to be overlooked with introduction of enriched version of LE.

## Why It's Good For The Game

Reaction actually works for LE from Jupiter Cups, Energy Bars, Empowered burgers - the common sources of LE.

## Changelog

:cl:
fix: Electrolysis chemical reaction works with enriched liquid electricity
/:cl:

### CODE REVIEW

**Comment by Y0SH1M4S73R** [comment]
This causes normal liquid electricity to not work for the reaction. This only matters if there are common ways to actually get the normal version, but I still wanted to bring that up.

**Comment by DustanHache** [comment]
> This causes normal liquid electricity to not work for the reaction. This only matters if there are common ways to actually get the normal version, but I still wanted to bring that up.

the most common way is to be an ethereal, but if you’re gonna do that you’re sacrificing blood for it.

**Comment by moocowswag** [comment]
Does it react with rdx

**Comment by MTandi** [comment]
> Does it react with rdx

I just changed the electrolysis reaction requirement, didn't touch the LE itself

**Pull request merged**
