### PR TITLE
Radiation tweaks and a geiger counter

### PR DESCRIPTION
**Pull request by ghost**
- Geiger counters have been added. They will increase in radiation level whenever a radiation pulse is received by its holder or the object itself. Radiation level will slowly decrease over time.
- When a mob is hit by a rad pulse, rad_act() is called on all objects in the mob with the same amount as the initial rad pulse.
- Geiger counters are found in quantities of 5 from the Engi-Vend and producable at any autolathe.
- You can scan a mob by attacking it on help intent to show its radiation level.
- Can be emagged to slowly generate radiation in small amounts and discharge it upon scan.

Sprites: 
geigers
From up to down
- Off
- Minimal radiation
- Average radiation
- Above average radiation
- High radiation
- Critical radiation
- Emagged

### CODE REVIEW

**Comment by GunHog** [comment]
Would you mind adding the detection function to all hardsuits (All but one have at least 50 radiation protections, and it makes sense for them to have such a device) and the radiation suit? I had and was testing code for this same idea.

**Comment by Xhuis** [comment]
@GunHog I'm only going to add it to engineering hardsuits, maybe even just the advanced hardsuit. Radiation pulses happen often enough in Engineering that they're warranted, but rarely ever in other departments, and a single small-sized object is negligible in your inventory.

**Comment by GunHog** [comment]
Disappointing.

**Comment by Xhuis** [comment]
Geiger counters are now producable from autolathes and can be found in quantities of five from Engi-Vend machines.

**Comment by PKPenguin321** [comment]
i think one or two could be useful in medbay for reading the radiation level of a patient, too

**Comment by Bawhoppen** [comment]
>geiger counter >for medical uses

what we need aswell is a HEV suit tbh

**Comment by Bawhoppen** [comment]
also 0/10 sprites holy FUCK

**Comment by CosmicScientist** [comment]
Oooo. This looks like fun to be able to quantify how much radiation characters have suffered.
:+1: for having minimal radiation as the smallest display.

**Comment by Xhuis** [comment]
@Bawhoppen If you can make better sprites, go ahead.

**Comment by Supermichael777** [comment]
remove the "your cloths feel warm" mesage so people will actually want one if they feel they are going to encounter a radiation hazard.

**Comment by Alek2ander** [comment]
This looks like a good PDA app

**Comment by xxalpha** [comment]
This really should be sound based.

**Comment by GunHog** [comment]
> remove the "your cloths feel warm" mesage so people will actually want one if they feel they are going to encounter a radiation hazard.

Xhuis has made it too a bit too restricted for that. They would have to be more common in that case.

I can understand not building them into every hardsuit, even though I think they should be. However, one handheld item should at least be included with the radiation suits. It only makes sense that Nanotrasen or any corporation would provide a geiger counter as standard gear in any locker containing the suit as well.

>This really should be sound based.

Oh, and before Xhuis stopped me coding this myself, I was looking for a set royalty-free geiger counter sounds I could use, based on intensity. I recommend doing that here! In the words of Three Dog: http://fallout.wikia.com/wiki/File:FO3_GNR_Radiation.ogg

**Comment by Xhuis** [comment]
The main issue with making the counters sound-based is that there is no such thing as lingering radiation in Space Station 13. The only form of radiation that exists is pulses that leave nothing behind (Though this be impossible in real life). It would require a heavy overhaul of how radiation works if I wanted to make this being sound based practical.

I will put geiger counters into radiation closets.

**Comment by GunHog** [comment]
No, silly. Just make the counter emit the noise in addition to the message in rad_act(). This is how it works for Fallout 3/NV. The Pip-Boy makes the noise and provides you a radiation message on the HUD.

**Comment by Xhuis** [comment]
I know, @GunHog. The problem is that it starts going off in an irradiated area. I suppose it would be easy to play certain sounds, though.

**Comment by WJohn** [comment]
Made some better sprites for you, it's in other.dmi:
http://www.mediafire.com/download/d1g7og4bgs84027/Sprites_Request_11.0.8b.rar


Yes, it's deliberately similar looking to the multitool.

Also, use the multitool inhands for these, would you?

**Comment by Bawhoppen** [comment]
>yellow geiger counter

why

**Comment by Xhuis** [comment]
If you Google "Geiger counter", about 80% of the results are colored yellow. Don't be autistic.

**Comment by Bawhoppen** [comment]
no, its just yellow ones look silly, the real dunker handheld ones are black

**Comment by Xhuis** [comment]
New sprites by WJohnston have been included. Will update the OP shortly.

**Comment by Bawhoppen** [comment]
make it so they spawn in radiation crates

**Comment by Xhuis** [comment]
How often do you see radiation crates ordered? That aside, you can only get them from cargo, which can mass-produce them from the autolathe anyway.

@Razharas This is merge-ready.

**Comment by Bawhoppen** [comment]
I just wanted them to be thematically added even if its not that useful.

**Pull request merged**
