### PR TITLE
CC Ferry can now dock at Omega

### LINKED ISSUE #26554: Omega station lacks a centcom ferry dock
See title.
Just like delta didn't have one until recently, omega does not have one.

### PR DESCRIPTION
**Pull request by Penguaro**
:cl: Penguaro
fix: The Central Command Ferry will now dock at one of the ports in Arrivals
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
Fixes #26554 - Currently there is no docking area for the CC Ferry thus limiting Admin options when playing on this map. The lower left port across from the arrivals shuttle now takes the ferry. This is intended as a quick fix with no modification to the structure of arrivals so the map creator can look at alternatives if they wish.

### CODE REVIEW

**Comment by Penguaro** [comment]
@Okand37 I believe this was your map? Didn't want to overhaul arrivals or even attempt at a whiteship in case you had plans for those things.

**Comment by FantasticFwoosh** [comment]
Suggestion: when there is nowhere to dock up, the ship chooses a random marker & crashes a path of destruction into the station.

**Comment by Penguaro** [comment]
@FantasticFwoosh Just for funsies I gave it a place to dock to avoid that.

**Comment by Penguaro** [comment]
shuttle

**Comment by Shadowlight213** [comment]
@Penguaro as far as I'm aware okand37 has left the project. They aren't maintaining their maps anymore. You don't need to ask them for permission to remodel anything.

**Comment by Penguaro** [comment]
Good to know. I'll start making a white ship and a slightly different arrivals then. I hate to step on toes if it isn't necessary and the wiki doesn't really say if it's being maintained by community or a person.

**Pull request merged**
