### PR TITLE
Adds Titanium Airlocks

### PR DESCRIPTION
**Pull request by Firecage**
Basically what it says in the title. This makes Titanium Airlocks buildable, and since Shuttle walls and floors are already Titanium based now, the Titanium Airlocks looks like and replaces many Shuttle Airlocks.

There there is this bloody shit, which is on a few maps here and there: /obj/machinery/door/unpowered/shuttle
What to do about this...what to do...

On an unrelated note, technically this also fixes an issue where you could never finish an airlock if you added Titanium to it.

Note, this also adds Glass Titanium Airlocks. Due to an issue with Airlock Assembly code, they currently can't be build until said code is changed, and I honestly don't know how. Though the Glass Titanium Airlocks themselves works, so mappers will be able to use them if they want to.

:cl: Firecage
add: The NanoTrasen Airlock Builder Federation(NTABF) has recently released the blueprints involving building and deconstructing Titanium Airlocks! These airlocks are now being used on all of our shuttles.
/:cl:

### CODE REVIEW

**Comment by Supermichael777** [comment]
sprites?

**Comment by Firecage** [comment]
Michael, the Shuttle Airlocks are now Titanium Airlocks.

**Comment by kevinz000** [comment]
nice

**Comment by ChangelingRain** [comment]
Do these have sprites for glass variations, or does adding glass just create a shuttle airlock that's mysteriously transparent?

**Comment by Firecage** [comment]
@ChangelingRain Didn't actually realise that every airlock needed a glass variation.

**Comment by Firecage** [comment]
Okay, PR is done.

**Pull request merged**
