### PR TITLE
removes tail pulling in its entirety

### PR DESCRIPTION
**Pull request by capsaicinz**
## About The Pull Request

removes tail pulling, effectively obliterating #62763.

## Why It's Good For The Game

literally the first moment i entered the game as a felinid, i was approached behind and feared for my earthly dominion, only to realize that somebody was attempting to pull my tail. i was CONFUSED. what IS this? and so, i looked onward. the github. the discord. everywhere i saw, tail pulling. why? what on god's green earth did we do to deserve this?

i've only seen bad/creepy stuff with this. literally hearing somebody say it felt like it was the equivalent of being sexually harassed when cornered and tail pulled is kind of off-putting, and this overall isn't something we need. it's inevitably you-know-what bait at best, and perverted shit at worst.

## Changelog
del: removed the ability to pull felinid tails.
/:cl:

### CODE REVIEW

**Comment by Redrover1760** [comment]
I'm not sure how one would argue that tail pulling could ever be a good thing for the game, honestly.

**Comment by datorangebottle** [comment]
I actually stopped playing felinid because of tail pulling.
Why are people dead set on adding things strictly to annoy felinid players and enable people to "roleplay" bigoted jerks? 
Being griefed by the coders isn't fun. Please stop adding things strictly to annoy / weird out felinid players.
I have never seen wound licking be used. I have never seen a felinid say a positive thing about tail-pulling ingame and would probably cringe into the nearest sun if I did.
The best thing to come out of this whole mess was the tailpulling=erp joke and that got stale pretty quick.

**Review by Ghommie — APPROVED** [review]
I'm completely, unironically and honestly in favor of this removal. I'm pretty sure I also got my hand scratched or bit each time I pulled a cat's tail.

**Comment by Thunder12345** [comment]
Funny while it lasted, but if the majority of the feature's use is to harass felinid players removal is probably for the best

**Comment by optimumtact** [comment]
> I actually stopped playing felinid because of tail pulling.

one less redditor

**Comment by NanoCats** [comment]
The entire "tail pulling" thing is a shit show and I wish it was never introduced.

**Comment by Redrover1760** [comment]
> > I actually stopped playing felinid because of tail pulling.
> 
> one less redditor

No explanation for the closed pull?

**Comment by datorangebottle** [comment]
> one less redditor

Please explain how this feature makes the game better.

**Comment by optimumtact** [comment]
redditors are a net negative on the community, anything that makes a felinid or redditor leave is a net positive for this community.

**Comment by NanoCats** [comment]
> > > I actually stopped playing felinid because of tail pulling.
> > 
> > 
> > one less redditor
> 
> No explanation for the closed pull?



> redditors are a net negative on the community, anything that makes a felinid or redditor leave is a net positive for this community.

POV: Oranges just whipped out the redditor joke:
image

**Comment by Redrover1760** [comment]
> redditors are a net negative on the community, anything that makes a felinid or redditor leave is a net positive for this community.

Why are felinids even in the game then?

**Comment by optimumtact** [comment]
I didn't find consensus to remove them back in 2018

**Comment by itseasytosee** [comment]
This exchange has brought new insight into the lore of tg and is rather interesting. We can now recontextualize oranges insistence on adding the tail-pulling pr, obviously defending it with arguments he himself did not believe in, as an attempt at sabotage of the felinid race. This is truly an interesting development.
I can't wait to see what happens next.

**Comment by optimumtact** [comment]
if I wanted to sabotage them, why would I remove the chocolate interaction?, this is clearly an attempted buff, which would place me on the pro felinid side.

also for those of you saying this should be removed for being creepy please reflect on the following

1. Many people hold cat people to be creepy, should I remove them from the game on that basis?
2. If you answered no to the above question, why do you rationalise this differently?
3. Where did you go during table moodlet, pouncing and wound licking?
4. Why are you so violently hypocritical?


PS: if you see someone being a creep, press the <f1> button and ahelp it.

**Comment by capsaicinz** [comment]
> if I wanted to sabotage them, why would I remove the chocolate interaction?, this is clearly an attempted buff, which would place me on the pro felinid side.
> 
> also for those of you saying this should be removed for being creepy please reflect on the following
> 
> 1. Many people hold cat people to be creepy, should I remove them from the game on that basis?
> 2. If you answered no to the above question, why do you rationalise this differently?
> 3. Where did you go during table moodlet, pouncing and wound licking?
> 4. Why are you so violently hypocritical?
> 
> PS: if you see someone being a creep, press the button and ahelp it.

1. i haven't seen you make any attempt to. if there are genuinely people piling your inbox about how felinids are breaking rule 8, then go ahead and do it.
2. N/A
3. because it isn't sexual by any degree.
4. why are you being so god awfully powertrippy?

**Comment by datorangebottle** [comment]
> also for those of you saying this should be removed for being creepy please reflect on the following
> 
> 1. Many people hold cat people to be creepy, should I remove them from the game on that basis?
> 2. If you answered no to the above question, why do you rationalise this differently?
> 3. Where did you go during table moodlet, pouncing and wound licking?
> 4. Why are you so violently hypocritical?

1. No.
2. You can have a mutant/alien race without them being weird, creepy, or cringe. See: every other race in the code. Felinids aren't inherently a creepy concept, it's all the crap that's been piled on top of it to make them that way.
3. I was on a year or two hiatus from SS13. Also: the table moodlet and pouncing don't specifically target the groin and pull on something long and firm. Wound licking is incredibly cursed and I've never seen anyone use it.
4. I'm not.

> PS: if you see someone being a creep, press the button and ahelp it.

I'm not going to adminhelp every time someone bullies my character using the mechanics you've given them.

**Comment by optimumtact** [comment]
>     1. i haven't seen you make any attempt to. if there are genuinely people piling your inbox about how felinids are breaking rule 8, then go ahead and do it.

https://tgstation13.org/phpBB/viewtopic.php?f=40&t=20294

**Comment by optimumtact** [comment]
> I'm not going to adminhelp every time someone bullies my character using the mechanics you've given them.

I assume you don't ahelp any time they break the rules using any of the other mechanics in the game too right?

**Comment by itseasytosee** [comment]
Now oranges, i won't be offended if you don't answer, and my opinions on everything felinid related have devolved into violently neutral, but I have to ask why you merged the PR in the first place. Was it to bait reaction? to try to win some clout with felinid players? Or did you think it was funny enough?

**Comment by optimumtact** [comment]
I merged the #59506 and felt it was only be fair to be neutral by adding a positive moodlet interaction

**Comment by itseasytosee** [comment]
You know that makes alot of sense and explains the PRs existence in the first place. Thanks for clearing it up.

**Comment by datorangebottle** [comment]
> > I'm not going to adminhelp every time someone bullies my character using the mechanics you've given them.
> 
> I assume you don't ahelp any time they break the rules using any of the other mechanics in the game too right?

Of course I do. If someone kills me, I tell the admins that someone might've broken the rules. Are you saying that I should be ahelping if someone spams a laser pointer, spray bottle, or tailpull?

**Comment by wesoda25** [comment]
I dont like catgirls so im a big fan of this

**Pull request closed without merging**
