### PR TITLE
Adds more equipment to most maps' Cytology Lab

### PR DESCRIPTION
**Pull request by EuSouAFazer**
## About The Pull Request

Adds a hydroponics tray to most maps + a few other changes. Check https://tgstation13.org/phpBB/viewtopic.php?f=11&t=29003 for more details on why this is needed.

## Why It's Good For The Game

Cytology is in a pretty bad state right now: Lack of rewards, lack of people actively working on the feature, very little in-game experimentation, etc. One of its main problems is lack of proper mapping support; recently Northstar has added a big support for Cytology and I'm doing a similar thing to the other maps

Note that I'm not merely mirroring Northstar's changes; I added the hydroponic tray however in the name of map uniqueness 
I did a number of small loot changes between stations. Namely:
-> Meta has some tofu roundstart for extra protein
-> Tram has a second hydroponics tray
-> Birdshot has a few cell spawners in its lab
Delta had a very confusing layout for me and it just in general looked very odd; I can't really tell what the pros and cons of cytology is on Delta so I just slapped the tray there and called it a day.
As for Icebox... Icebox is _bad_. Like, there is not even a dedicated pen for Cytology. This shit needs a full blown redesign; there's not even a petri dish storage - something that was already standard in all other rooms! I'll likely come back for Icebox later, adding a dedicated Cytology lab area. Unless Chilled comes first. godspeed.

:cl:
qol: Made the cytology lab in many maps much more convenient.
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
powercreep

**Comment by EuSouAFazer** [comment]
The feature already is massively underpowered and inconvenient to use. Out of all the ways to gain gamer loot in the science department Cytology is one of the worst and slowest ones. + any buff / content to Cytology is more steps against Xenobiology which is always appreciated

**Comment by dieamond13** [comment]
why just meta

**Comment by EuSouAFazer** [comment]
> why just meta

I could probably update it to add stuff to the other stations too tbh

**Comment by AtomTheProphet** [comment]
Glad to see stuff being added to cytology! I really feel like it has a lot of potential for more interesting stuff to be added (bioreactors, more interesting microbial stuff, you get the idea), but it doesn't get the attention it deserves.

**Comment by JohnFulpWillard** [comment]
this means scientists will be able to get and grow their own gatfruit with just their roundstart equipment

**Comment by EuSouAFazer** [comment]
> this means scientists will be able to get and grow their own gatfruit with just their roundstart equipment

If the scientists start growing gatfruit with no reason that is either powergaming (thus ahelpable) or antag activity, at which point it's competing with xenobiology releasing spiders or  ordnance bombing an entire department. 

Xenobio is just fucked up in general, and Cytology is meant as an alternative/eventually mix with Xenobio. It's not that big of a deal, and a xenobiologist who really really wanna do it all on their own can just build their own tray or make a dirt patch.


in fact reading this game me the excellent idea of one day removing gatfruit seeds from xenobio and giving it as one of cytology's drops, but that's for later

**Comment by necromanceranne** [comment]
> this means scientists will be able to get and grow their own gatfruit with just their roundstart equipment

Gatfruit is purely RNG if it even appears in a round, and through the xenobio method (the mo almost assuredly not a roundstart occurrence. Whether or not it is available roundstart means nothing if it isn't going to matter for about 40 minutes to begin with. And by that time, science can _print_ those boards instead.

(Also there are public hydroponic trays and dirt mounds so literally anyone can grow fruit right now, as any role)

**Comment by Pickle-Coding** [comment]
If we have public gardens, then why do cytologists need their own tray?

**Comment by EuSouAFazer** [comment]
> If we have public gardens, then why do cytologists need their own tray?

They need their own tray so they don't have to needlessly run around back and forth between the lab and the garden. The job already has a ton of places to visit - maint, chemistry, etc. Having to go to the garden as well is excessive, specially when 9/10 rounds there's not gonna be anyone else there.

**Comment by nukularpower** [comment]
This is great.  Now for real, how about giving science back a chem dispenser in xenobio as well?

**Review by Ghommie — APPROVED** [review]
Approving since cytology is in a sorry state indeed, though I'm not familiar with the feature.

**Comment by EuSouAFazer** [comment]
> I'd say replace the trays with the primitive dirt-mound variants. Give them something to upgrade towards or "borrow" from the garden/hydroponics.

Alright, I've done the changes - made most of them dirt mounds rather than hydroponics tray. I did left the hydroponics tray on Delta; every other map meaningfully changed got a specific thing to set it apart (meta has some tofu, birdshot has a bunch of cell spawners in the lab, etc) so I decided to give a tray to Delta as a map uniqueness thing.

**Pull request merged**
