### PR TITLE
Adds Syndicate Stormtrooper mobs

### LINKED ISSUE #13607: Syndicate shielded mobs
The syndicate mobs with eshields don't reflect energy weapons and block SOME bullets and melee like it's supposed to
They're simply immune to ranged damage
No, not Idedplsnerf, CONSISTENCY :/

### PR DESCRIPTION
**Pull request by Thunder12345**
Adds a new tier of melee and ranged syndicate mobs.

Melee stormtroopers function identically to regular space operatives, but have twice as much health
Ranged stormtroopers have twice as much health as regular space ops, but burstfire buckshot instead of SMG rounds, and drop unrestricted bulldogs on death.

Fixes #13607

### CODE REVIEW

**Comment by GunHog** [comment]
https://github.com/tgstation/-tg-station/pull/15029 Wait for that to be merged first.....HONK

**Comment by MMMiracles** [comment]
could you like fix the projectile blocking for the shielded mobs too, a 100% block chance for ballistics and lasers is pretty fucking silly, even more-so now that the actual energy shield they use doesn't even block ballistics anymore.

**Comment by Aloraydrel** [comment]
tr8or

**Comment by AnturK** [comment]
Change line 64 to `adjustHealth(Proj.damage)`while you're doing this.

**Comment by Zilenan91** [comment]
Yeah please remove them blocking ALL ranged damage on the shields. You physically can't beat these things 1v1 unless you have an esword and a riot suit on.

**Comment by Thunder12345** [comment]
I would complain about atomic PRs here but yeah that bug sucks, I'll get it changed.

**Comment by swankcookie** [comment]
so how is it okay for this to be obvious CR, but mine was not okay?

**Comment by swankcookie** [comment]
mine being #15029

**Comment by KorPhaeron** [comment]
@swankcookie 

The word "stormtrooper" is generic (such as german stormtroopers in WW1).

The syndies in the OP use the black, elite hardsuit sprite.

Yours on the other hand was clearly a star wars costume

**Pull request merged**
