### PR TITLE
Poster changes!

### PR DESCRIPTION
**Pull request by harmonyn**
- New posters!

posters
- Removing a corporate poster now displays a brand spanking new sprite that is not that of a syndicate poster. Fixes https://github.com/tgstation/-tg-station/issues/11264.
- Posters now have a do_after progress bar to go with the animation.
- Poster names and descriptions are now in a table instead of the 60+ switch cases they were before.
- Rewrote some descriptions to be more in line with seditious and/or fascist ideals.
- Changed the path of posters so that contraband and legit are children of the parent type, and renamed contraband.nm to posters.dm because it's really just posters. THIS AFFECTS THE MAIN TGSTATION MAPS AS WELL AS LOOT SPAWNERS.

### CODE REVIEW

**Comment by Razharas** [comment]
@bgobandit

**Comment by Miauw62** [comment]
we need an informative poster on atmospheric safety aboard a space station, featuring many fun facts about carbon dioxide.

anyway conflicts ;-;

**Comment by bgobandit** [comment]
>we need an informative poster on atmospheric safety aboard a space station, featuring many fun facts about carbon dioxide.

holy shit someone sprite this

**Comment by bgobandit** [comment]
THERE IT WORKS NO MORE MERGE CONFLICT

SALT

**Comment by duncathan** [comment]
>7 commits
>5 commits to do with making the game compile

honk/10

**Comment by bgobandit** [comment]
:(

**Comment by optimumtact** [comment]
@Cheridan @RemieRichards @Aranclanos  @Razharas merge please

**Pull request merged**
