### PR TITLE
Kilo Chapel Fixes (And Tweaks)

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Tweaks NewChapel to:
Fit in with the rest of Kilo (Dust n' Rust, OOC ranting not included)
Fix a Handful of stacked decals (There's still more in there! Somewhere! I just can't find them all!)
Not be as much of a box (But it's still boxy)
Fix the cameras for the wallening's inevitability!
Fix the lights for the wallening's inevitability!
Remove all the firelocks under every window! Seriously!
Get rid of all those annoying to remove `/fluff/` objects!
Get rid of the space plating in favor of proper latticing!
And a handful of other tiny tweaks!
Do some aesthetic tweaking to the bottom section!
Change up the areas to not be as confusing!? (Chapel Maintenance AND Monastery Maintenance? Wacky Tobacky!)

Act now and we'll throw in a FREE CAR!

StrongDMM removed the ability to natively screenshot and haven't reimplemented it yet so enjoy this scuffed snipping tool overview
image

Also removes the motion sensitive camera in front of the AI upload. In central primary. Because of course.

## Why It's Good For The Game
Why can't we make pod floors and walls again anyways? It'd be cool if I didn't have to scrub them out considering they were part of the whole design here, but baddabing baddaboom.

## Changelog

:cl:
fix: The Kilostation chapel has less stacked turf decals. They're still around, though.. Watching. Waiting... Additionally, magic power has been NUKED from the maintenance room back there. Pour one out.
fix: All lights (and cameras) in the Kilostation chapel have been PREPARED FOR THE FUTURE. And by the future, I mean the wallening.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
I FORGOT TO PUT QUOTES AROUND THE MAPEDIT VAR 💀

**Comment by Likteer** [comment]
Kilo my beloved. And in turn, **you!**

**Review by san7890 — COMMENTED** [review]
image

I like the way it all looks. Would you mind moving around the newscaster/APC so they don't layer on top of each other since that'll look bad to ghosts?

**Comment by unit0016** [comment]
> image
> 
> I like the way it all looks. Would you mind moving around the newscaster/APC so they don't layer on top of each other since that'll look bad to ghosts?

I'll do it when I get back to my computer. And hunt for more layered turf decals while I'm at it

**Comment by unit0016** [comment]
Merge conflicts my hated

**Review by Maurukas — APPROVED** [review]
Tons of nice detailing and improvements here. This is what I love to see.

**Pull request merged**
