### PR TITLE
Cigarettes and vapes are no longer subtypes of masks.

### LINKED ISSUE #82870: Cigarettes can be damaged, making them unwearable
Reporting client version: 515.1636

## Issue Summary
In this round a blob passed over a pack of cigarettes, leaving these "shredded cigarettes" behind. I don't know if only blob can damage them (and if it was really blob and not the infinitely burning fire that stayed on top of the blob because of lag), but they probably shouldn't inherit that behavior from clothing
shreddedcig

## Round ID:
[227759](https://scrubby.melonmesa.com/round/227759)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Since non-clothing items can also be worn on several slots, there's no need for cigarettes/vapes to be subtypes of masks anymore, since that comes with a few oddities like #82870.

## Why It's Good For The Game
This should fix #82870, with about no side-effect aside them no longer being edible by moths 🤢.

## Changelog

:cl:
fix: cigarettes and vapes are no longer treated as clothing (eg. They no longer get shredded and need to be repaired with... cloth).
/:cl:

### CODE REVIEW

**Review by MrMelbert — COMMENTED** [review]
Needs an updatepath script

**Comment by Wallemations** [comment]
RIP wearing a cigarette for chameleon mask

**Comment by Ghommie** [comment]
> RIP wearing a cigarette for chameleon mask

Dangit, I was too optimistic that I forgot about this nitbit. I'll peep into chameleon (shit)code later to make sure this won't be the case.

**Comment by MrMelbert** [comment]
> Dangit, I was too optimistic that I forgot about this nitbit. I'll peep into chameleon (shit)code later to make sure this won't be the case.

Actually fairly easy, all you need to do is call `add_chameleon_items(/obj/item/cigarette)` in `/datum/action/item_action/chameleon/change/mask/initialize_disguises()`

**Comment by EricZilla** [comment]
Nooooooo I can't believe this, I love eating cigarettes and joints OTL
(This is probably a good change)

**Review by MrMelbert — COMMENTED** [review]
Looking at IDB and it seems like cig icons have regressed, from the changes I made in my own PR

In your DMI
image

New icon
image

**Pull request merged**
