### PR TITLE
Improved Medical Tools and Medkits by Onule!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Back at it again. I am on an unstoppable roll!

Does what it says on the tin, adding the fabled medical tools that Onule was working on for more than a year into our codebase!
image

This PR also redoes medkits!
image

As for smaller quality of life things, this PR adds inhands to:
- The Tactical Medkit
- The Advanced Tools
- The Bonesetter
- The Surgical Drill
- Bone Gel
- Unique and separate inhands for Retractor and Hemostat

And finally, this PR resprites the Syndicate Cyborg's laser circular saw sprite:
circsaw

**Credits to:**
@Onule For absolutely making nearly everything in this PR. The only thing I really did was complete the medkits and PR their work!
@axietheaxolotl for making the Tactical Medkit sprite!
@thgvr for making the inhands of the medkits!
@TripleZeta for helping make minor tweaks for the main surgery tool inhand sprites!

## Why It's Good For The Game
A long awaited resprite for some of the oldest sprites still on our codebase! Now they're much shinier, and ready to be paired with the recent medical resprite!

## Changelog

:cl: Onule, PositiveEntropy, TetraZeta, Axietheaxolotl, Thgvr, AdipemDragon
imageadd: Completely resprites all medkits!
imageadd: Completely resprites all medical tools!
imageadd: Removes the clamp sprite and instead creates separate hemostat and retractor inhand sprites!
imageadd: Adds missing inhands for the bonesetter, advanced med tools, tactical medkit, surgical drill and bone gel!
/:cl:

### CODE REVIEW

**Comment by jacklecroy** [comment]
I don't like the upgraded retractor or hemostat, but the rest look nice.

**Comment by Farquaar** [comment]
Am I wrong or didn't we have a total resprite of the medical kits and equipment a couple months ago?

**Comment by Wallemations** [comment]
Good pr
every-house

**Comment by Imaginos16** [comment]
> Good pr
> 
> Mind if I ask how long it took you to set up these screenshots

Not as long as you'd think. I reckon, 15 - 20 minutes I wager.

> Am I wrong or didn't we have a total resprite of the medical kits and equipment a couple months ago?

You're absolutely correct, we did have a resprite of **medkits** a while back. The reason I'm redoing those is because they looked like toys. I feel the new ones are a much more realized version of what was attempted back there.

**Comment by bruhman8ghughug** [comment]
i like the sprites, but i will nevern forgive spriters after how hard they massacred det gear... and wooden tiles....

**Comment by AdipemDragon** [comment]
good to see that the symbols i made for the last version Sort of made it through into this one, nice

**Review by Twaticus — APPROVED** [review]

**Comment by Imaginos16** [comment]
> good to see that the symbols i made for the last version of medkits Sort of made it through into this one, nice

Yup! I changed the brute one since people couldn't tell it was a toolbox. Broken bones were a pretty genius solution!

**Comment by JohnFulpWillard** [comment]
wtf happened to the wrench

**Comment by AdipemDragon** [comment]
I know there's probably no point to it because they're minor changes at most but.
image

**Comment by Imaginos16** [comment]
> I know there's probably no point to it because they're minor changes at most but. image

Legendary mid-PR edit. Thanks for the help!

**Pull request merged**
