### PR TITLE
Ends Lizard Oppression! Suits won't hide tails anymore.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Right now we have a flag `HIDEJUMPSUIT` that also hides tails from any species, now I can see what you are about to say, it makes sense for a space/fire/other suits to hide the tail so it doesn't freeze or burn but this system is heavily inconsistent for a few reasons: 

1- Moths can keep their wings safe on the outside of suits, in the void of space or on a plasma hellfire with no issues.
2- Some suits don't hide your tail but will protect you from the cold/heat, others hide but won't protect.
3- Having your tail/wings out has no real effect in game, so it's basically a few suits can be used to easily hide your identity and make you look like a human if you are a lizard, but not if you are a moth.
4- You can wag your tail while it is hidden and tail wagging actually gives you tackle armor, small and silly, but still invisible niche armor with no feedback.

On the top image you can see a moth enjoying their wings being free.
spacesuit1
On the bottom image you see everyone being happy, unless the Lizard and Felinid want to hide their identity for crimes, then they might be sad instead...
spacesuits2

PR approval
Just to be clear, when I started on the PR I had in mind to just fix some inconsistencies with a few suits but as I looked more into it, I would need to refactor the system fully and still would be hard to make it consistent. Since this has a real balance weight I changed the tone of the PR from a fix on clothing code to a full balance.

## Why It's Good For The Game
Other than fixing some inconsistencies, I think that choosing to play a non human should have pros and cons, not being able to easily hide as a Human is an interesting interaction for security and antagonists.

## Changelog

:cl: Guillaume Prata
balance: Lizards/Felinids rejoice! Suits won't hide your tail anymore and don't worry, it won't freeze in space. Do remember you can't easily hide your species now if you are going to commit crimes.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
what do you have to wear to hide your identity now?

**Comment by GuillaumePrata** [comment]
> what do you have to wear to hide your identity now?

To be clear, you will just have your tail sticking out of a space suit but no change on the Unknown system so security staff can figure out that a lizard spaced thermited into the armory.

**Comment by tralezab** [comment]
yes, but i mean what do you have to do to hide your tail now

**Comment by CRITAWAKETS** [comment]
> yes, but i mean what do you have to do to hide your tail now (i should have said that in the first place, my bad)

amputation shears

**Comment by optimumtact** [comment]
you cant' just show your tail in a professional context!

**Comment by itseasytosee** [comment]
>it won't freeze in space

image

**Comment by tralezab** [comment]
> Remove moth wing showing, no balls

this was my first thought

**Comment by GuillaumePrata** [comment]
> Remove moth wing showing, no balls

Wouldn't fix the issue that you slap some xeno potion/atmos magic crystal on your clothing and now your wings/tail inherit space/fire resistance from a dress.

**Comment by GuillaumePrata** [comment]
> > > Remove moth wing showing, no balls
> > 
> > 
> > Wouldn't fix the issue that you slap some xeno potion/atmos magic crystal on your clothing and now your wings/tail inherit space/fire resistance from a dress.
> 
> I don't think those are common enough to be a reason to stick with the sticking behavior. It's also not really what bothers me about the difference here. I like the idea of hardsuits and such hiding your identity somewhat, though admittedly it does make wearing those items in a social setting a bit weird. Maybe that's good?
> 
> We can always fluff the xeno and atmos thing as bluespace or something, though in their current states they're not long for this world

Well most of those things can be pushed away as bluespace or can be ironed out to cut on inconsistencies and balance issues that hidden organs can bring. The main point will be about being easier to recognize others and if that is healthy for the game.
I personally think it is

**Comment by bluetshirtguy** [comment]
Awful pr in tg's long string of making non human gameplay harder.

**Comment by AndroidMK2** [comment]
Moths and lizards rejoice! You are getting fucking nerfed!

**Comment by wesoda25** [comment]
Mothblocks did although I'm not sure they understood it'd be for stuff like this.

Personally I don't play any nonhumans with tails and I think this is odd, it doesn't make any sense to me for protrusions to be exposed.

**Comment by LemonInTheDark** [comment]
arm what are you trying to say I can't tell at all

**Pull request closed without merging**
