### PR TITLE
Moves the right bone bracer over by one pixel.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
It's misaligned!

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
wait fuck

**Comment by TechnoAlchemisto** [comment]
my b
let me undo that

**Comment by ChangelingRain** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by KorPhaeron** [comment]
aaaaa

**Pull request merged**
