### PR TITLE
Updates the Banned Content to include stupid autist anime bait shit

### PR DESCRIPTION
**Pull request by Iamgoofball**
This stupid anime meme shit needs to stop

### CODE REVIEW

**Comment by feemjmeem** [comment]
the fuck is wrong with you

**Comment by sawrge** [comment]
How is patting anime
How does touching someone's head equate to a style of eastern animation

**Comment by Aliannera** [comment]
:3c

**Comment by sawrge** [comment]
If we're banning stupid autism meme shit does that mean you can't open PRs anymore @Iamgoofball

**Comment by Iamgoofball** [comment]
@Cheridan @optimumtact can you guys clear unproductive irrelevant comments from this PR like aliannera's

**Comment by feemjmeem** [comment]
here's a productive comment:

adding code rules to satisfy some weird personal vendetta is absolutely ridiculous

**Comment by Iamgoofball** [comment]
@feemjmeem this is the same as the other two code rules

**Comment by feemjmeem** [comment]
@Iamgoofball yeah no. One restricts hate speech and one is a code standards thing. Your new rule is ridiculous

**Comment by Shapsy** [comment]
only mgs5/whatever flavor of the month autism goof picks up is allowed

**Comment by feemjmeem** [comment]
If you have such a problem with whatever it is these people are doing then just shit up their PRs, don't shit up the code standards documents

**Comment by Aliannera** [comment]
I came here to meme at you.

In other news, your tits need calming my dude.

**Comment by uraniummeltdown** [comment]
weebs out

**Comment by Anonmare** [comment]
Goof is really triggered about this

**Comment by Iamgoofball** [comment]
@Aliannera Stop shitposting in this discussion.

@feemjmeem This has been tried, they just plug their ears and go "LALALALA"

or they just do that @anonmare did and go "LOL U TRIGGERED LOLOLOLO"

**Comment by Arianya** [comment]
I'll be removing all metal gear references to get rid of the disgusting weeb shit in our codebase.

Fucking *cardboard boxes*, degenerates.

**Comment by Iamgoofball** [comment]
Cool, go for it. You're still a fucking autist.

**Comment by Arianya** [comment]
Nah, I just put on internals so I never get vaccines. Thanks for looking out for me 👍

**Comment by Iamgoofball** [comment]
Cool, you're a fucking anti-vaxxer too. Jump off a cliff and stop compromising herd immunity.

**Comment by Arianya** [comment]
😆

**Comment by Earthykiller127** [comment]
weeaboos reaction over this pr = americans reaction to w bush getting elected

**Comment by Anonmare** [comment]
https://cdn.discordapp.com/attachments/186327568008347648/280794621586571264/16508768_385759061790860_2123730359397779228_n.png

**Pull request closed without merging**
