### PR TITLE
Syringes injecting plasma makes infinite plasma gas fix

### LINKED ISSUE #46100: You can make infinite gaseous plasma by drawing from and injecting a beaker of plasma repeatedly
## Reproduction:

1. Get a beaker with some ground up plasma inside.
2. Draw from the beaker with a syringe, then inject it back in.
3. Plasma will leak into the air but the full amount of plasma will be transferred into the beaker, allowing you to repeat the process forever.

You can fill a space the size of the thunderdome in 15 seconds of pumping and drawing. Good fun.

### PR DESCRIPTION
**Pull request by Ty-the-Smonk**
## About The Pull Request
Fixes: #46100 and #45020, all I did was revert the syringe change made in #44531

## Changelog
:cl:
fix: Plasma Gas Syringe
/:cl:

### CODE REVIEW

**Comment by Krysonism** [comment]
This will break stuff. I think we need to look at the plasma reaction_obj.

**Comment by Arathianen** [comment]
Oh thank fuck this is fixed. It's one of the most annoying xenobio things.

So now using a syringe on a slime shouldn't spill plasma, right?

For some reason, that was the case with droppers but not syringes.

**Comment by msgerbs** [comment]
That would break plasma grenades. Plasma is working exactly how it should, the issue is with this new code triggering reactions when they were never intended to be. It's also not the only chemical that does something like this, although it is the most noticeable.

A different proc altogether should probably be used for one-hit interactions with living beings, to avoid conflicting with the other existing reagent interactions?

**Comment by Krysonism** [comment]
Now that I think about it, I actually like this.

Volatile reagents that are associated with a gas should create some fumes of that gas when handled. 

That is why chemists have fume hoods after all. Intact on servers with better chemistry than TG you sometimes see clumsy chemists gas themselves because they forgot their gas masks.

Having to take precautions when working with plasma just makes the chemistry simulation a bit better and it is an unique opportunity since we actually have simulated atmos.

My solution to this would be removing some plasma on_transfer to account for the amount of plasma lost as gas, giving chem and xenobio a portable scrubber and adjusting the amount of gas created depending on transfer method.

**Comment by msgerbs** [comment]
That's silly. The whole point of the syringe is that it _doesn't_ react. Do you have any idea what a gigantic pain in the ass it would be to do chemistry with that change? No thanks. IMO, fix the code so it doesn't cause unintended interactions, and if you want to PR something like that later then go for it. But this is purely a bugfix to return it to how it worked before and trying to sneak in new mechanics with it is no bueno.

**Comment by ExcessiveUseOfCobblestone** [comment]
> That would break plasma grenades.

Are you telling me grenades don't ever react with their turf and just react within the grenade space?

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
Not correct fix, needs reaction_obj editing.

**Comment by Ty-the-Smonk** [comment]
edited it

**Comment by msgerbs** [comment]
I still don't understand why syringes need to call reaction_obj when they never did before.

**Comment by ExcessiveUseOfCobblestone** [comment]
so u use the cryo gear i imagine

**Comment by Ty-the-Smonk** [comment]
@ExcessiveUseOfCobblestone do you want me to change anything else or is this fix fine?

**Pull request closed without merging**
