### PR TITLE
AI powercreep

### PR DESCRIPTION
**Pull request by silicons**
:^)

(reverts the removal of voxtest 2)

### CODE REVIEW

**Comment by kevinz000** [comment]
Willing to code it to be only allowed once per announcement line (once per minute) to cut down on spam, if it'll help this get approved.

**Comment by kevinz000** [comment]
inb4 gitbanned for meme naming prs

**Review by Cyberboss — APPROVED** [review]
Why was this ever removed?

**Comment by AnturK** [comment]
Because it was tiring to listen to it every round.

**Pull request closed without merging**
