### PR TITLE
resprites clown mask styles and adds one

### PR DESCRIPTION
**Pull request by junkgle01**
Screenshot_108

## About The Pull Request

resprites the existing clown mask styles and adds a new clown mask style: The Dealer. the old madman mask has been made into an optional craft: the gamer's wig and mask. 

does not resprite already existing default clown mask

Screenshot_109

## Why It's Good For The Game

resprites are good! and more variety is good too

## Changelog

:cl:
add: the Honkmother has decided to bless Her children with a new form!
image: resprited the optional clown mask styles
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
why is the last guy wearing a sonic oc shirt

**Comment by ElGitificador** [comment]
why would you turn the madman into a craftable?

**Comment by EricZilla** [comment]
I don't think yalls understand, the resprited joker mask is selectable like normal, but if you want to go back to the jonkler, you just use a green crayon on the default mask

**Comment by DrAmazing343** [comment]
cleaner sprite from the OG, easy (roundstart) craft for the sovl jonkler. This is the best of both worlds.

**Comment by deathrobotpunch** [comment]
why so serious?

**Pull request merged**
