### PR TITLE
Attempts to fix negative supermatter rads, zeros BZ curve

### LINKED ISSUE #47703: Its possible to make a negative energy supermatter that incinerates everyone around engineering instantly
Over half the station died, this was on kilo and people in cargo just instantly dropped dead, from 100 health to husked, I think it was atmos witchcraft of some form. I dont know how it happened but admins say power level was at -6.16072e+019. Thats pretty much all I can say, good fucking luck.

Issue reported from  Round ID: 123404 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Modified the way pluoxium dampens rad output when used in the supermatter.

## Why It's Good For The Game

Should partially fix #47703

As far as I can tell, the negative rad output was because of this formula

I was incorrect in this assumption.
## Changelog
:cl:
fix: Attempts to fix the supermatter outputting negative radiation 
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
This runtimes:
```
[07:51:27] Runtime in supermatter.dm,430: Division by zero
  proc name: process atmos (/obj/machinery/power/supermatter_crystal/process_atmos)
  src: the supermatter crystal (/obj/machinery/power/supermatter_crystal/engine)
  src.loc: the reinforced floor (113,66,2) (/turf/open/floor/engine)
  call stack:
  the supermatter crystal (/obj/machinery/power/supermatter_crystal/engine): process atmos(0.5)
  Atmospherics (/datum/controller/subsystem/air): process atmos machinery(0)
  Atmospherics (/datum/controller/subsystem/air): fire(0)
  Atmospherics (/datum/controller/subsystem/air): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
```

**Comment by TheVekter** [comment]
If this works, this might be the best first PR ever.

**Comment by LemonInTheDark** [comment]
Pride comes before the fall

**Comment by LemonInTheDark** [comment]
Fuck me I went down the wrong path, the negative power has nothing to do with rad output. Note to self, do not make pull requests at 12:00Pm

**Comment by LemonInTheDark** [comment]
Closing while I reconsider my life choices and investigate the power decay function

**Pull request closed without merging**
