### PR TITLE
Condiments resprited

### PR DESCRIPTION
**Pull request by MTandi**
image

## About The Pull Request

Resprited many condiment containers.

And a tray (don't know why, it just was in the dmi)

Replaced the old condiment bottle from Condi Master with the one that was used in Chem Master before the test tubes.

## Why It's Good For The Game

More in line with other 3/4 stuff

## Changelog

:cl:
image: Resprited many condiment containers
image: Added a sprite for cooking oil / corn oil container
image: Replaced old condiment bottles with the newer bottles in Condi Master
/:cl:

### CODE REVIEW

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
Massive downgrade on the flour, rice and sugar containers. I prefer the current version.

**Comment by YakumoChen** [comment]
A lot of small details lost on the new sprites:

- Hot/Cold/UE sauce lost the detail on the label signifying what it was
- Soy sauce is hardly recognisable with the container shape now
- Mayo looks like a generic sauce bottle instead of the well-known bottle shape
- Peanut butter label too small to make out what is on it now
- - Missed opportunity to brand peanut butter as "GIF"

**Comment by Pumpkinoe** [comment]
The flour/rice/sugar sacks should feel a bit more sack-like, rather than box-like. Other than that these are great, love the new ketchup bottle.

**Comment by MrDoomBringer** [comment]
> Massive downgrade on the flour, rice and sugar containers. I prefer the current version.

The new versions have both unique shillouettes and fuckin adorable little wheat/flour/rice icons on the front conveying exactly what they contain.

If you are leaving criticism that is so bare of information it can't be used to actually improve the sprite it's probably best to restrain yourself to a thumbs down @Imaginos16

**Comment by MrDoomBringer** [comment]
This DMI really needed an update. Higher quality and much more charmful across the board - thanks for the work @MTandi

**Comment by Imaginos16** [comment]
> If you are leaving criticism that is so bare of information it can't be used to actually improve the sprite it's probably best to restrain yourself to a thumbs down @Imaginos16

And let this be merged? Yeah no. I requested a change specifically because I am rather unhappy at the current version. Of this. You may not know me well, but I do leave my reviews rather barren because I intend the contributor to reach out to me in the official /tg/station discord to be able to discuss any grievances I have with their project. (Something that MTandi did indeed do).

But since you're going to play that card on me, very well. I will dissect why I really dislike it here.

image

MTandi's proposals as pictured here have completely whack colors. A lack of contrast and hueshifting that leads to darker, blander packaging as compared to the predecessors.

> The new versions have both unique shillouettes

Where? They're all no better than the previous ones, in fact they're *worse*, they're basically squares using the uninspired Eris "light line" shading. At least the previous ones had a more sack-like appearance to them instead of looking like cardboard boxes.

> fuckin adorable little wheat/flour/rice icons on the front conveying exactly what they contain.

image
image
image

I did the above ones in less than a minute of my time at 4 AM. If those icons were so essential, I don't see why he couldn't have plastered them on the current versions.

All I want is better designs, and the proposals are definitely a downgrade as compared to the versions that @Agameofscones kindly provided nearly 6 months ago.

**Comment by Jezzared** [comment]
Personally i've always disapproved of the current sack sprites. They don't really look like sacks either.

And... i'm not crazy, right? All three of those CLEARLY have unique silhouettes? One has the raised top edge, and the third is rounded.

**Comment by MTandi** [comment]
They look like boxes because they're supposed to be. You rarely have detailed graphics with pictures on sacks, so I made them boxes. I'll either resprite them to be like sacks and with less details or leave the previous version. The main reason I touched those is a couple of weird pixels on the outline.

Please provide more information on where you think the shading is wrong on other sprites or hueshifting misused. I'm trying to learn.

**Comment by MrDoomBringer** [comment]
>  I intend the contributor to reach out to me in the official /tg/station discord to be able to discuss any grievances I have

I like your idea of putting the icons on the old sacks! I think we both agree on the importance of sprites conveying this type of information. Try leading with this first instead of forcing him to ping you on discord then replying with the thoughtful criticism of "Please revert the colors are worse". 

I get it - being helpful is hard, and not everyone starts off great at it. Maybe get some better rest before posting your next tirade?

**Comment by MrDoomBringer** [comment]
3 Images That Will Shock And Terrify You:

**Comment by Imaginos16** [comment]
image
image
image

Your point? Fuck off with being a whimsical smartass.

**Comment by MrDoomBringer** [comment]
jesus christ go to bed then learn how to make images smaller in markdown in that order

**Comment by MTandi** [comment]
I'll make them sacks, okay? Please don't proceed with this topic. I made the PR for the discussion and @Imaginos16 's criticism is welcome. It helped a lot to improve the air alarm sprite. I understand that graphics are sometimes shit, and this PR is a draft for people to say that something is shit and I can attempt to improve it.

**Comment by Imaginos16** [comment]
Thank you.

**Comment by Helg2** [comment]
Hot sauce looks like strange beer/whiskey bottle.

**Comment by MTandi** [comment]
Updated with the following:

condiments

**Review by Imaginos16 — APPROVED** [review]

**Comment by YakumoChen** [comment]
Like the changes
Not sold on mayo being 'white sauce bottle' but it is what it is

**Comment by LSommers** [comment]
Mandatory "player who doesn't watch git and just saw these in the game and is now commenting like a week late" comment:

These look AMAZING.
You didn't fall for the classic blunder of "this looks nothing like the sprite you're updating", and any changes that don't resemble the original sprite _make sense_ (IE the mayo squeeze bottle, milk being a carton instead of a jug).

THIS is what sprite replacement/updates should aim for. Excellent work.

**Pull request merged**
