### PR TITLE
Some small fixes to AsteroidStation. Also adds the custom z2.

### PR DESCRIPTION
**Pull request by lzimann**
Messed up last PR ([#12512](https://github.com/tgstation/-tg-station/pull/12512)) so I'm re-doing it. Hopefully I didn't messed up this one too.

Some minor stuff that needed fix. Also fix the custom z2 file not being used.

### CODE REVIEW

**Comment by Anonus** [comment]
The custom z2 doesn't have abductor ships and is also entirely unneeded with the default z2's dock change.

**Comment by lzimann** [comment]
Oh, I forgot, as usual, about abductors. And about docking, the shuttle is different, so it docks all wrong.

**Comment by GunHog** [comment]
If you have not added the RD's hardsuit to the map, would you mind doing so? Path is ````/obj/machinery/suit_storage_unit/rd````

**Comment by Jordie0608** [comment]
z2 isn't needed, the shuttle rotates to dock correctly.

**Pull request closed without merging**
