### PR TITLE
Incinerator and toxins burn chamber monitoring, some mapping fixes.

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
 - Added an atmos control computer to toxins and incinerator on all maps, reading gas sensor data from their respective burn chambers. This was already available from the main atmos control computers in atmospherics, but hardly very useful considering their location.
  - Slight remapping of toxins and incinerator on some maps to fit the new computer. Incinerator welder/water tank has been sacrificed in favor of the console and an extra rad suit locker on meta and box.
 - Maxed the incinerator outlet injectors and space pumps leading to them on all maps.
 - Fixed the incinerator plasma tank output direction, box had this pointing at a wall.
 - Added a second dropper to xenobiology on all maps. (kinda out of place here, but I was already touching all the maps anyway)

## Why It's Good For The Game
Fixes some mapping annoyances and oversights, and allows players to more easily get feedback from burn chambers.

## Changelog
:cl: Skoglol
add: Toxins and incinerator burn chambers on all maps now has a console which allows you to read off gas mixture inside.
tweak: Toxins and incinerator have been remapped slightly on some maps to fit the new computer. Some welder/water tanks are gone, added another radsuit on box and meta.
fix: Incinerator outputs have had the space pump and injector maxed.
fix: The incinerator plasma tanks have been rotated on some maps. Notably, box station' no longer outputs into a wall.
tweak: Xenobiology now has two droppers.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
map power creep prove me wrong

**Comment by kriskog** [comment]
Which part? 

Only thing I could maybe see is the extra radsuit on meta and box, the others have plenty available to atmos techs. Its silly that atmos techs gotta steal engineering rad suits to do fusion, but there is still one less available than the amount of atmos slots.

**Comment by optimumtact** [comment]
fix: Incinerator outputs have had the space pump and injector maxed.

**Comment by optimumtact** [comment]
this kind of shit is literally just removing experimentation and investigation for new players

**Comment by kriskog** [comment]
Both those are situated in space on the maps where I have made the changes. If you pipe something into output, you expect it to be able to output. Not get stopped by a 101kpa pump right outside the window.

**Comment by optimumtact** [comment]
I suppose if they're in space

**Comment by kriskog** [comment]
@optimumtact Was that a yes or a no on the pumps in space? It's hard to tell some times.

**Comment by optimumtact** [comment]
it's fine

**Pull request merged**
