### PR TITLE
Replace the objectively inferior straight quotes with objectively superior curly quotes

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
tweak: The disgusting VIRGIN inferior straight quotes in your speech have been replaced with objectively superior beautifly CHAD curly quotes. Now, instead of being disgusted by your poor taste in quotation marks, people will fawn over you and your exceptionally good taste in quotation mark choices. Instead of having your maint screams for help ignored due to your inferior VIRGIN straight quotes, security will be instantly teleported to you because you made the correct choice of having objectively superior CHAD curly quotes.
/:cl:

image

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
So are you saying you want to remove straight from /tg/?

**Comment by Cyberboss** [comment]
These quotes have been my enemy since I first learned visual basic. 👎

**Comment by nicbn** [comment]
Disgusting

**Comment by ShizCalev** [comment]
no

**Pull request closed without merging**
