### PR TITLE
Minor grammar change on the golden wheelchair.

### PR DESCRIPTION
**Pull request by orthography**
## About The Pull Request

Does anyone even know this exists, does anyone even have it unlocked?

~"Damn, he's been through a lot."~ -> **"Damn, must've been through a lot."**

Am I going to get flamed for this?

## Why It's Good For The Game

Removes gendered language from the wheelchair when anyone can suffer.

## Changelog

:cl:
spellcheck: minor grammatical change to the golden wheelchair.
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
2 people have this chair unlocked until I get 7 more points, b00t and tanachi.

**Comment by orthography** [comment]
> 2 people have this chair unlocked until I get 7 more points, b00t and tanachi.

Your entire life has been leading to this moment.

**Comment by Time-Green** [comment]
> 2 people have this chair unlocked until I get 7 more points, b00t and tanachi.

Goddammit another person? I've broken the 2k, 3k and 4k barrier and been working towards it slowly and then tanachi just did it in 2 weeks

**Comment by notfrying1pans** [comment]
i'd suggest replacing must've with whatever handles pronouns here

**Pull request merged**
