### PR TITLE
Updates the Limb Grower

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
About The Pull Request

Removes fly parts from the limbgrower and replaces them with ethereal parts, adds lizard tails under the lizard category, gives random coloring to limbs of appropriate species

Also changes a some descriptions and text to make things more accurate/clearer

## Why It's Good For The Game
Flypeople aren't a roundstart race any more and ethereals are.

Makes frankenstein'd bodies look frankenstein'd

Vegan lizard wine
## Changelog
:cl: Dorsidwarf
tweak: Added ethereals & tails to the limbgrower and removed flypeople
add: Limbgrower limbs are now appropriately randomly coloured instead of plain white.

/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
Now i dont have to clone myself if Malik Fisher wants a lizard tail attached to her groin. Nice.

**Comment by Krysonism** [comment]
I don't like lizard tails being printable since they are supposed to be a commodity. Lizard products should not be easily mass producible.

**Comment by 81Denton** [comment]
I'm also not a fan of lizard tails being printable for the same reason. The rest of this PR looks really good though.

**Comment by kriskog** [comment]
I agree on the tails, they should not be available in the grower.

**Comment by ExcessiveUseOfCobblestone** [comment]
i don't care about the tail so just remove it and this is ok

**Comment by ATH1909** [comment]
What about cat ears/tails, though? Could we add them to the limb grower instead?

#SaveRuntime

**Comment by Dorsisdwarf** [comment]
Nice

**Pull request merged**
