### PR TITLE
Re-enables bolas in crafting

### PR DESCRIPTION
**Pull request by ghost**
:cl: CosmicScientist
fix: bolas are back in tablecrafting!
/:cl:

Fixes a blatant stealth nerf to greyshirts in #27863
https://github.com/tgstation/tgstation/pull/27863/files#diff-da2444ed4282c414a8347678e39745c8L86
Half a year without an essential tool!

### CODE REVIEW

**Comment by KorPhaeron** [comment]
These are so op and still bugged to bypass shields though

**Comment by CosmicScientist** [comment]
Then do you want me to remove them from the code?

Are e-bolas above that balance concern for being in limited supply/never taken or do they work differently?

**Comment by Supermichael777** [comment]
>officers being good

Nice joke M80

**Comment by PKPenguin321** [comment]
You can craft them by hand too

**Comment by CosmicScientist** [comment]
@KorPhaeron I can open a separate PR and close this to remove them from the code if you're against them. It'd not take more than an hour to search for all references to bolas and delete until compilation succeeds.

**Comment by CosmicScientist** [comment]
I'm only giving options, mister Penguin. Though I've never used or fought against bolas to understand how OP they are... tasers seem to win fights just fine.

**Comment by FantasticFwoosh** [comment]
From my past experience, e-bolas break melee attackers such as double e-sworders & adrenaline users very hard by making their movement speed static until removed, and the e-bola cannot be thrown back at its attacker since it vanishes when removed. Though it is limited in supply entirely from the security vendor it is a must-have for most security officers.

Wheras a regular bola is very easy to craft, and drops the object when removed so there would be a constant supply of these items in the hands of literally anybody and remain difficult to counter if the riot shield was ineffective as claimed. Heavy duty cult version was a pain in the ass too.

If you can fix xenos jumping through riot shields, then you can fix bola's getting past too.

**Comment by lzimann** [comment]
if anyone wants they can open an appropriate pr to remove the bolas, however they not showing up on the crafting menu is not intentional

**Pull request merged**
