### PR TITLE
Allows all accessories to toggle between under/above suit

### PR DESCRIPTION
**Pull request by VladinXXV**
## About The Pull Request
An alternative for #65333.

What I've done here is I've allowed the already existing accessory above_suit toggle to actually be used by all accessories, rather than only specific ones (such as the medical medals.) As part of this, the default for all accessories is to show ABOVE your suit. The toggle was originally done via Alt Click, but due to conflicting with how the Pride Pin is reskinned, I've moved it to Right Click.

## Why It's Good For The Game
The code already existed, and certainly seems to be an intended behavior. I can't find any reason for it to only apply to things like the medical medals, but not say, the captains medal, or an armband. You're telling me I can't wear an armband over a winter coat sleeve?

## Changelog

:cl: Vladoricious
fix: You can actually toggle whether or not your accessories appear over your suit now! Right click the accessory inhand to toggle it. The default is appearing above the suit.
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
Do waistcoats, sheriff vests, and maid aprons make sense to be worn over suitslot items?
I think they'd cover too much of the suit tbh

**Comment by VladinXXV** [comment]
> Do waistcoats, sheriff vests, and maid aprons make sense to be worn over suitslot items? I think they'd cover too much of the suit tbh
> 
> If you're going to make it a default thing, then I'd say removing the `initial(above_suit)` from those if statements would really be all you'd need for the PR, no need to set everything to TRUE by default.

Do they make sense in the regard of being fashionable? No, not at all. But I think it's perfectly reasonable to let people make those bad style choices. Aprons tend to be pretty loose, you could easily wear one over even a MODsuit. The vest and especially waistcoat, probably less so, but I still think it's largely within the realm of "you COULD do this but why would you?" Thus, I felt there was little need to make them exceptions. Can always just toggle it and be sane, y'know?

As for the code suggestion, I can try to make that work, but this was easy enough since it's already a variable defined at the top, and there were only a handful of overriding accessories.

**Comment by VladinXXV** [comment]
> Do waistcoats, sheriff vests, and maid aprons make sense to be worn over suitslot items?

Also to be perfectly honest with you I think the maid apron and sheriff vest should just be suitslot items themselves, waistcoat is debatable. But I'm not gonna touch it, that's for someone else to do and get complaints about.

**Comment by VladinXXV** [comment]
> If you're going to make it a default thing, then I'd say removing the `initial(above_suit)` from those if statements would really be all you'd need for the PR, no need to set everything to TRUE by default.

This looks to work just fine, thanks! I'm gonna leave TRUE as the default for now since I still think it makes sense (most of our accessories are medals/pins, things for showing off), but if The People would rather the default be FALSE I can now do that just as easily.

**Comment by VladinXXV** [comment]
fuck i think i broke it

**Comment by VladinXXV** [comment]
fuckin hell i guess i'll start from scratch

**Pull request closed without merging**
