### PR TITLE
Made the incinerator on Boxstation less carcinogenic (literally)

### LINKED ISSUE #48792: Box Chem Factory is irradiated by fusion next door
Because someone decided to place Box chem factory wall to wall with the incinerator, literally the burn chamber in which fusion occurs within, the resulting radiation leaking from the fusion burn will contaminate objects directly on the other side of the wall. Normally, because this incinerator would be in space and sealed with reinforced walls, it wouldn't normally cause issues. On Box, standing next to the chemistry equipment in the lab will give you a nice, lethal dosage of radiation if the atmos techs are at work.

### PR DESCRIPTION
**Pull request by dablusniper**
## About The Pull Request

- Moved the entire incinerator one tile away from the chemistry factory to stop fusion radiation from leaking through the wall (fixes #48792) 

- Cleaned up the piping in the incinerator room

- Added a bridge between atmos and the incinerator so you don't need to take a jog around the block whenever you want to change your gas mix

- Added an extra airlock in North incinerator maint to maintain access to the gas tanks

**Before and after photos are available [here](https://imgur.com/a/exMLTuh).**

## Why It's Good For The Game
Makes boxstation slightly less cancer.

## Changelog
:cl:
add: added a bridge between atmos and incinerator on boxstation
tweak: added an airlock in North incinerator maint to maintain access to gas storage tanks
fix: fixed fusion radiation leaking into chem factory by moving incinerator one tile to the left
tweak: cleaned up piping in the incinerator room on box
/:cl:

### CODE REVIEW

**Comment by dablusniper** [comment]
If radiation is still coming through the walls we can always shorten the width of the chem factory.

**Comment by ExcessiveUseOfCobblestone** [comment]
the chem factory is tacked on terribly to begin with lol

**Comment by Neo-0** [comment]
Nobody ingame will know what "#48793" is. Fix your changelog with something more descriptive.

**Comment by dablusniper** [comment]
Fixed

**Pull request merged**
