### PR TITLE
Fitness Title Change

### LINKED ISSUE #81531: grammar error when leveling to master level fitness
Reporting client version: 515.1630

## Issue Summary
grammar error when leveling to master level fitness 

## Round ID:
[224115](https://scrubby.melonmesa.com/round/224115)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)
- [A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief](https://www.github.com/tgstation/tgstation/pull/81231)

## Reproduction:
train fitness (this sucks (unrelated))
image

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request
Changes the "Fitness" skill title to "Powerlifter"
## Why It's Good For The Game
Fixes: #81531
## Changelog
:cl:
spellcheck: changed the fitness skill title to powerlifter
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
it should probably be something like powerlifter tbh, since our gym gear only has the bench.

**Comment by Cheshify** [comment]
Done

**Comment by newfren** [comment]
for the record, the punching bag also trains fitness

**Comment by Cheshify** [comment]
Well god damn it

**Comment by EricZilla** [comment]
Gym rat?

**Comment by MrMelbert** [comment]
I liked bodybuilder better

**Comment by MrMelbert** [comment]
I'm depicting you as a soyjack

**Pull request merged**
