### PR TITLE
Crew Transfer (Shuttle call) Voting and Automatic Transfer Vote Subsystem

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Adds an OOC crew transfer vote that can be called. If successful, the shuttle will be called on an extended timer, and it will be un-recallable by ingame means. Note that observers and ghosts are not allowed to initiate transfer votes, but can vote on them. 

By default, players are not allowed to initiate transfer votes at all, and if `default_no_vote` is disabled, then a proportion (1/3rd for the first couple votes, then less and less as votes continue) of non-voters will be assumed to want to continue the round. 

Implements an automatic crew transfer vote subsystem. This will automatically call crew transfer votes if a round reaches a certain length. By default, a vote will be called 1.5 hours into a shift, and another will be called every 30 minutes afterwards.

Both the crew transfer vote and the automatic crew transfer have config options. Whether players can call transfer votes, whether automatic transfer votes happen, minimum shift length before votes can start and delay between auto votes can all be adjusted.

This also allows admin-recalling shuttles to bypass if a shuttle is un-recallable, so admins can override transfer votes if they are assuming direct control.

## Why It's Good For The Game

Everyone has seen long rounds begin to stagnate after a while, especially on greenshifts which have no 'end condition'. People begin to want to wrap it up and begin a new round, but generally no one calls the shuttle unless there's a reason. Captains/AIs/Heads often call crew transfer votes in game after a round gets a certain length, but this relies on most of the crew paying attention enough to respond.

This gives players a notification and allows them to directly vote on a means of calling the shuttle if a round is agonizingly slow. Multiple other servers have a system like this to prevent long, slow rounds, and there seems to be at least some desire to have something like this on TG, especially on the slower servers like Manuel.

This is entirely configurable as well, so servers can enable or disable transfer voting, auto transfer votes, or extend or shorten the timer for the auto transfer votes according to what they want.

## Changelog
:cl: Melbert
add: OOC Crew Transfer Votes. If successful, it will call the emergency shuttle on an extended timer and disallow it from being recalled.
add: Automatic Crew Transfer Votes. They begin at 1.5 hours by default, and happen every 30 minutes afterwards.
config: Adds a few config options for OOC transfer votes, and automatic crew transfer votes.
admin: Admins can now force-recall shuttles that are un-recallabale. 
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Probably won't see use outside of manual, but really I wouldn't want it anywhere else.

**Comment by bobbahbrown** [comment]
I feel like the power of non-voters might be a bit low in this.

On 60 pop 10 yes vs 7 no results in an unrecallable shuttle call. Also on 60 pop 15 vs 13 results in an unrecallable shuttle call.

At 30 pop 5 yes vs 2 no would result in an unrecallable shuttle call. Also on 30 pop 7 vs 5 results in an unrecallable shuttle call.

It's been my experience with restart votes that people typically don't vote, and this could easily result in a shuttle call that is possibly undesired by a majority of the population.

**Comment by Cyberboss** [comment]
image
I heard some chumbii on this station weren't voting.

**Comment by Tharcoonvagh** [comment]
If this was higher-RP only, then that should be fine.
In case you enabled it on all servers, as Bobbah has mentioned it's gonna result in a lot of unfair shuttle calls.

**Comment by itseasytosee** [comment]
Manual only or bust for me.

**Comment by MimicFaux** [comment]
Mild concern, but this would prevent the multiple-day projects that happen occasionally on the manuel/campbell servers. Secondary stations built in deep space, customized biodomes on lavaland, etc.

**Comment by MrMelbert** [comment]
> I feel like the power of non-voters might be a bit low in this...

Correct me if i'm wrong, but I believe on the servers `default_no_votes` is enabled, meaning none of those situations would result in a shuttle call - Assuming not a single player is AFK:
`60 pop, 10 yes 7 no` would result in 21 no votes total. At least 7 transfer votes would need to occur in total for the non-voter multiplier to get high enough for this to pass.
`60 pop, 15 yes 13 no` would result in 23 no votes total At least 16 transfer votes would need to occur.
`30 pop, 5 yes 2 no` would result in 9 no votes. At least 12 transfer votes would need to occur.
`30 pop, 7 yes 5 no` would result in 11 no votes. At least 9 transfer votes would need to occur.

Either way, I've seen concerns for both 'there will be too many unfair shuttle calls' and 'the vote will be impossible to pass' - I only suggest that the multiplier for no-voters can be tweaked as finely as possible if too many or too few shuttle call votes are succeeding.

>this would prevent the multiple-day projects...

This concern was in my mind working on this, and I initially planned on allowing you to cap how many transfer votes happened before it would turn itself off. I removed it because I thought it wouldn't be necessary (people can just vote to continue, and if someone really wants the shuttle called, odds are they can get it called in game). But, if you think it'll be a problem, I can re-add a configurable cap on the number of votes that can be called.

**Comment by bobbahbrown** [comment]
> `60 pop, 10 yes 7 no` would result in 21 no votes total. At least 7 transfer votes would need to occur in total for the non-voter multiplier to get high enough for this to pass.
> `60 pop, 15 yes 13 no` would result in 23 no votes total At least 16 transfer votes would need to occur.
> `30 pop, 5 yes 2 no` would result in 9 no votes. At least 12 transfer votes would need to occur.
> `30 pop, 7 yes 5 no` would result in 11 no votes. At least 9 transfer votes would need to occur.

Some what of a moot point to ask for clarification on this as I have verified what I didn't notice before, which is the default = no being disabled on /tg/ servers, but rather I am misreading your code or you are misinterpreting what you wrote.

```dm
if("transfer")
	/// multipler applied to non-voters. non-voters count for 1/3rd of a vote, then past two votes they count for 1/4th, 1/5th, and so on.
	var/non_voters_multiplier = clamp(SScrewtransfer.transfer_votes_attempted + 1, 3, 50)
	choices["Continue Shift"] += round(non_voters.len / non_voters_multiplier)
	if(choices["Continue Shift"] >= greatest_votes)
		greatest_votes = choices["Continue Shift"]
```

The underlying function is effectively ``no_votes = actual_no_votes + (non_voters / (total_voters_who_actually_voted + 1))`` -- correct?

Assuming the above statement is true, then for the first case, no_votes = 7 + (43 / 18) = approx 7 + 2 = 9 effective no votes

**Comment by MrMelbert** [comment]
The function you have is is almost correct, but - 
`no_votes = actual_no_votes + (non_voters / max(3, number_of_transfer_votes_attempted + 1)  )`
unless the clamp is implemented incorrectly.

`SScrewtransfer.transfer_votes_attempted` tracks how many votes occurred in total, and the more votes are attempted, the less non-voters are counted in votes. The multiplier has a minimum of three, so for the first two votes, a non-voters are 1/3rd of a vote, and on the third vote, they are 1/4th, and so on.

**Comment by bobbahbrown** [comment]
I excluded the clamp for simplicity, so would you say then that my analysis above was correct? I'm very confused as to where you're getting the numbers you put in the comment prior to that.

The ratio of 1/18 per non-voter only adds two no votes to the 60 player example.

**Comment by optimumtact** [comment]
who wants this? Because I sure don't it makes the expectation that rounds end at a few hours in where I want them to go as long as people want them to, so unless the headadmins do what's the point

**Comment by bobbahbrown** [comment]
I figured out my mistake I thought that class-level var was the number of votes in the current poll but it was actually the number of time the poll has been run all is ok now thanks

**Comment by MrMelbert** [comment]
> I want [the rounds] to go as long as people want them to

Yes - the round will go as long as people want it to continue (through voting), but if people want the round to end, they can also vote for the round to end. I've seen a strong desire for this amongst the community on the Roleplay servers specifically, where rounds can really really drag on.

**Comment by ExcessiveUseOfCobblestone** [comment]
This needs headmin support before the ball gets rolling on this. They dont have to like the default numbers so long as the numbers they dont like are configurable, just the concept.

Will take off DNM once that's done.

Personally I wouldn't mind this as an admin but only after an unholy amount of time like 4 hours where we you have spent like 2-3x the amount of time it takes for you to "max out" the jobs in the games, especially for the LRP servers where people will avoid joining the server at all if it's several hours in.

I would **not** be a fan of this if it's going to be used to set the soft values we have in our code where you get your main items within the hour, and reach all you could do near the 1.5hr mark.

**Comment by msgerbs** [comment]
I don't like that this sets the implicit expectation that a round has a set length after which it's "too long" and a shuttle call is needed. We already get enough "haha I want to roll antag again" shuttle calls as it is.

**Comment by MrMelbert** [comment]
The headmins were contact for their opinions on the PR 5 or 6 days ago, and a response is still being awaited, as an update.

**Review by MrsTonedOne — APPROVED** [review]
Config :heavy_check_mark:

**Comment by cacogen** [comment]
>add: Automatic Crew Transfer Votes. They begin at 1.5 hours by default, and happen every 30 minutes afterwards.

You should remove this and add it to a different PR.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
This does not need to be a new subsystem. Merge it into SSvote

**Comment by MrMelbert** [comment]
seeing has how it's been almost two months now without any apparent headmin response, I assume they hold no interest and i'm just going to close this now, maybe come back to it in the far future.

**Pull request closed without merging**
