### PR TITLE
Adds swimsuits for the summer ball event

### PR DESCRIPTION
**Pull request by Kraseo**
[why]: item_color is garbage and doesn't let you change sprites for clothes unless they're in the compiled .dmi file proper so I had to PR this

imagen
sprites courtesy of luna/bay I forget which

### CODE REVIEW

**Comment by GuppyLaxx** [comment]
okay but these when
swimmyboi

**Comment by sawrge** [comment]
fetish content

**Comment by CitrusGender** [comment]
Absolutely +1. I was going to sponsor this and do it myself but I told Kraseo to do it and they did. This is perfect.

**Comment by Repukan** [comment]
Fetish content.

It's my fetish though so please merge

**Comment by Repukan** [comment]
Tanlines when?

**Comment by Mickyan** [comment]
Wouldn't it make more sense for these to be underwear

**Comment by Kraseo** [comment]
do you tend to use a swimsuit as underwear

**Comment by Mickyan** [comment]
I don't have a swimsuit with pockets and a belt either

You're going to have a bunch of people wearing swimsuits with shirts and boxers underneath, is what I'm saying

**Comment by CitrusGender** [comment]
@Iamgoofball The same reason I didn't var edit the entirety of the beach map because "it's just for a specific event." It just makes it easier to have the objects lying around, especially for mapping.

**Comment by Iamgoofball** [comment]
A map is not comparable to a jumpsuit, especially with the SDQL tools.

**Comment by PKPenguin321** [comment]
This should be added to the beach bum ruin if we still have that

**Comment by Kraseo** [comment]
@Iamgoofball 
imagen

**Comment by Iamgoofball** [comment]
Why are you using item_color at all???

**Comment by Kraseo** [comment]
it forces you to otherwise it'll just keep displaying the same onmob sprite of whatever you edited

**Comment by Iamgoofball** [comment]
Then PR a removal of item_color.

**Comment by CitrusGender** [comment]
@Iamgoofball looks like you've found yourself something to do.

**Comment by msgerbs** [comment]
Goof's hatred for this PR is confusing to me.

**Comment by octareenroon91** [comment]
> 

What is this

**Pull request merged**
