### PR TITLE
Bye bye animal hospital.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Removes the animal hospital ruin and replaces it with some generic green greens patch of land.

Also replaces the footstep sounds from water with the lava sounds. Sounds better than sand imo, but not ideal.

## Why It's Good For The Game

The animal hospital is probably the most silly ghostrole in the game. There's no proper gameplay except seeking to get back to the station or being some kind of non flavourful hermit. I have yet to see anyone use this ruin for anything except a free respawn (bad) or to just suicide 3 minutes later (also bad). In addition to that it takes up a lot of space that miners could otherwise use for actual gameplay.

alright

I decided to replace it instead of just removing because some lavaland variety is indeed needed. It's a, in comparison, fairly compact ruin and gives players the ability to create unprecedented amounts of headcanon.

## Changelog
:cl:
add: A new ruin has been added to lavaland. Go explore!
del: The animal hospital on lavaland collapsed into a lavastream in an unfortunate accident. NT promised to send aid to the many goliath babies that can't get proper medical care now.
/:cl:

### CODE REVIEW

**Comment by knacker48** [comment]
Wait your taking the hospital out and not the beach bums?

**Comment by py01** [comment]
The animal hospital did have a bunch of weapons people looted. Does this have anything interesting in it?

**Comment by nemvar** [comment]
What interesting weapons? The animal hospital had a stunprod, a saw and lazarus. Nothing miners wouldn't normally have access to.

**Comment by py01** [comment]
theres a sawn off double shotgun and some ammo in one of the lockers

**Comment by knacker48** [comment]
@py01 Correction, you use the saw to turn the normal shotgun into a sawn off

**Comment by nemvar** [comment]
Right, forgot about the shotgun. I think miners will be able to survive without it and the medkits they sometimes steal.

**Comment by fludd12** [comment]
Maybe, rather than having pre-spawned lightgeists, have a tree in the center that works like the lightgeist spawn crystal? It'd still give ghosts something to do, and in a way that makes ghosting again a non-issue. It'd also tackle the "issue" of miners suddenly not having a medkit supply to raid, which I'm sure there will be no small amount of NaCl over.

**Comment by ExcessiveUseOfCobblestone** [comment]
miners looted it for the meds (which is really more of a reason to remove it imo)

**Comment by dr-bee** [comment]
Will this green patch have oxygen? because those butterflies are going to die pretty quick without it.

**Comment by nemvar** [comment]
Butterflys are edited to survive without air.

**Comment by zxaber** [comment]
Will they? The Pride's Mirror ruin (I think it's Pride) is full of butterflies that usually escape when you open the door, and they just sorta chill all round.

**Comment by nemvar** [comment]
Yes, normal butterflys die on lavaland.

**Comment by nemvar** [comment]
Oh, since I don't actually have water in this, tell me if I should atomize the footstep noises for water. Since I think that change is fairly uncontroversial, I don't think it's really that needed.

**Comment by necromanceranne** [comment]
I looted the hospital for the shotgun actually. The meds were an added bonus.

**Comment by HomocidlePancakes** [comment]
Never looted the meds as a miner, just the gun. It's more ueful for ashwalkers tbh

**Comment by cacogen** [comment]
>it takes up a lot of space that miners could otherwise use for actual gameplay.

This is a dumb reason. Lavaland is full of empty space that isn't used for anything. Realistically none of the ruins get used in the way they were intended, which is roleplay I guess. Just free loot/exploration for people who haven't been there before and a chance to get back to the station for ghosts. 

I like this ruin but I don't see any reason to remove the animal hospital when there are so many other shitty, pointless ruin spawns.

**Comment by YakumoChen** [comment]
beach bums have a dance machine though, worth spawning or walking in just to take a break from everything else

**Comment by anconfuzedrock** [comment]
the hospital was a reference to a fucking admin quote that I'm fairly sure nobody remembers 
nobody should have any reason to miss this thing

**Comment by Trilbyspaceclone** [comment]
Why not add a golden apple to the middle?

**Comment by dee-dubya** [comment]
I don't think I've ever seen someone spawn into the animal hospital on purpose. Maybe throw a sawn-off behind a tree somewhere to keep the miner mains happy?

**Comment by FantasticFwoosh** [comment]
Pandering and bargaining to keep maybe the one loot feature people would like shows how little people actually care for the animal hospital's ruin concept.

I appreciate the change, maybe a puddle or something added could improve its status as a oasis, I really don't care about lightgiests at all and i think they'll just get KO'd by lavaland wildlife/megafauna because they dont share a common mob-faction-group.

**Comment by Shadowflame909** [comment]
Hopefully, I gain enough coder expertise to just revamp shitty antag metagamers/respawner ruins.

I want more mini-boss battles. Having them be player-controlled would be pretty cool as well.

**Comment by OverlyGeneric** [comment]
Lightgeists seem quite jarring for the an Earth-like enviroment. 

I always thought of lightgeists coming from the folds of bluespace or better known as the Realm of the Chaos God.

On another note, rip bluespace dislocated animal veterinarian lore.

**Pull request merged**
