### PR TITLE
The screwdriver cocktail is now the world's worst screwdriver

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Screwdriver cocktail now secretly works as a screwdriver... just, the worst one ever. How the fuck are you doing that?!

## Why It's Good For The Game

It's funny and I bet someone has tried this before

## Changelog

:cl:
add: Screwdriver cocktails now work as the world's worst screwdriver
/:cl:

### CODE REVIEW

**Comment by private-tristan** [comment]
new tider meta?

**Comment by Jackal-boop** [comment]
Can you drink it as you use it?

**Comment by tralezab** [comment]
> Can you drink it as you use it?

i think so

**Review by MrMelbert — CHANGES_REQUESTED** [review]

**Review by ShizCalev — CHANGES_REQUESTED** [review]
`AddElement(/datum/element/eyestab)`
`RemoveElement(/datum/element/eyestab)`

**Comment by ShizCalev** [comment]
welcome to obscure element hour.

**Comment by ShizCalev** [comment]
honestly we need a component just to flag shit as screwdrivers properly now that we have 3~4 different items that use the same system lol

**Comment by Fikou** [comment]
> `AddElement(/datum/element/eyestab)` `RemoveElement(/datum/element/eyestab)`

i dont understand why youre insistent on adding eyestab to everything that has a screwdriver functionality, its not something unique to the screwdriver, its something for stabby things that you can see targetting eyes

**Comment by Shadowflame909** [comment]
We love useful bartender drinks

**Comment by ShizCalev** [comment]
> i dont understand why youre insistent on adding eyestab to everything that has a screwdriver functionality, its not something unique to the screwdriver

Except historically it quite literally was something unique to the screwdriver (and forks), and I'm a big fan of keeping things consistent in functionality. 
image

If you feel like adding eyestab to this is too much, so be it, I'll happily yield if others agree cause it is a little over the top; but I personally feel it absolutely keeping in theme with the hilariously ganky SS13 gameplay that a cocktail that ~✨_MAGICALLY FUNCTIONS AS A SCREWDRIVER_✨~ feature the full functionality of a normal screwdriver. :P

**Comment by Fikou** [comment]
> > i dont understand why youre insistent on adding eyestab to everything that has a screwdriver functionality, its not something unique to the screwdriver
> 
> Except historically it quite literally was something unique to the screwdriver (and forks), and I'm a big fan of keeping things consistent in functionality. image
> 
> If you feel like adding eyestab to this is too much, so be it, I'll happily yield if others agree cause sure it is a little over the top; but I personally feel it absolutely keeping in theme with the hilariously ganky SS13 gameplay that a cocktail called the **screwdriver** that ✨magically functions as a screwdriver✨ feature the full functionality of a normal screwdriver. :P

itd be really funny if it had a straw that stabbed you

**Comment by ShizCalev** [comment]
The screwdriver has a straw. 
image

**Comment by Shadowflame909** [comment]
it needs to stab people in the eyes

I don't care if it does 1 damage because its a straw. But seeing the bartender make screwdrivers and people using them to fight each other in the ragecage would make keeping the eye stab functionality worth it.

**Pull request merged**
