### PR TITLE
Adds a note about for loop speed

### PR DESCRIPTION
**Pull request by Iamgoofball**
i made a lot of changes on a bad assumption re: speed

### CODE REVIEW

**Comment by MrStonedOne** [comment]
```dm
                               Profile results (total time)
Proc Name                                  Self CPU    Total CPU    Real Time        Calls
--------------------------------------    ---------    ---------    ---------    ---------
/mob/proc/chain_call_profile_listtypes        0.384       30.828       30.828           64
/mob/verb/profile_listtypes                   0.001       30.828       30.828            1
/proc/new_loop_method                        21.529       21.529       21.530           38
/proc/old_loop_method                         7.810        7.810        7.809           26
/proc/initialize_shit                         1.104        1.104        1.104            5

```




```dm
/mob
	verb/profile_listtypes()
		var/timetostop = world.timeofday + 300
		var/i = 0
		while (world.timeofday < timetostop)
			i += chain_call_profile_listtypes(i)

	proc/chain_call_profile_listtypes(i)
		var/static/const/num = 2
		var/static/cur = rand(0, num-1)
		if (prob(33))
			cur = ((cur + 1) % num)

		var/static/list/L = initialize_shit()
		if (prob(10))
			L = initialize_shit()
		switch(cur)
			if(0)
				return i+old_loop_method()
			if(1)
				return i+new_loop_method()
			else
				throw EXCEPTION("invalid chain state")

	/var/list/numbers_to_use = list()
	/proc/initialize_shit()
		for(var/i in 1 to 1000000)
			numbers_to_use += rand(1,100000)
	 
	/proc/old_loop_method()
		for(var/i in numbers_to_use)
			var/fuck = i
	 
	/proc/new_loop_method()
		for(var/i in 1 to numbers_to_use.len)
			var/fuck = numbers_to_use[i]
```

**Comment by StarSmasher44** [comment]
Just wondering, would it be faster to use for(var/type/path in list), or for(var/A in list) var/type/path = A ?

**Comment by Cruix** [comment]
"for(var/A in list) var/type/path = A" is faster, because you avoid the overhead of an istype() for every element in the list.

**Comment by optimumtact** [comment]
as long as you can guarantee they're all of that type then yeah

**Comment by StarSmasher44** [comment]
Hm, sounds reasonable, my tests are the same..
If its faster, would it be a good potential to replace the subsystem loops with this type? (Still trying to figure out why the subsystem is using the while(current_run.len) system..)

**Comment by optimumtact** [comment]
where subsystem code is concerned if you think it's funny why something does it the way it does, it's probably for a good reason.

Check with MSO before you go refactoring things there

**Comment by StarSmasher44** [comment]
@MrStonedOne Could you elaborate on the use of while(list.len) var/type/path = list[list.len] rather than the quickest loop in this case?

**Comment by MrStonedOne** [comment]
@StarSmasher44 if you notice, its removing from the list.

this is because subsystems make a copy of the queue, so if they have to stop mid way because of check ticks, they can resume later on without issues.

If you remove from the beginning of the list, byond has to re-create the entire list every time, a O(n^m) operation in the context of the loop as a whole. 

Removing from the end of the list is cheap.

This also avoids issues with things that edit the processing list when they run, as some of them also edit the current run list

In reality, all of those should be changed to for (var/i in 1 to l) and remove after the loop ends (see ssgarbage for an example on how to do that properly)

**Comment by vuonojenmustaturska** [comment]
fair enough, doesn't seem to be much discussion happening here anymore

**Pull request merged**
