### PR TITLE
Fixes detective scanner not being able to ranged scan, adds range/viewcheck vars

### PR DESCRIPTION
**Pull request by silicons**
inb4 mekhi is powercreeping his own department again

### CODE REVIEW

**Comment by GunHog** [comment]
"Hopefully" implies that you did not bother to test it. Your commit name "Update <file>" also implies that you used the web editor, thus increasing the suspicion that you did not test it.
### PLEASE TEST YOUR CODE!

**Comment by FantasticFwoosh** [comment]
Real thugs copy paste the zip, make edits of the paths & then delete the executable, compile & test straight from there without ever making a branch to download a new zip from.

**Comment by ma44** [comment]
Real thugs ma44's the balance of the server with web browser then attempts to horribly revert it with web browser, which then cyberboss's the server

**Comment by lzimann** [comment]
If you don't even know if it will change anything, why are you even opening the pr?

**Comment by kevinz000** [comment]
@lzimann I'm testing gimme 6 hours

**Comment by kevinz000** [comment]
gunhog was rite

**Comment by kevinz000** [comment]
all good @lzimann

**Pull request merged**
