### PR TITLE
Adds upgrades to admin RCD

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
For testing purposes.

### CODE REVIEW

**Comment by trollbreeder** [comment]
To be honest i have no clue what the simple circuits upgrade does, i've checked the file and it seems to have no code. 
Maybe you would know since you're a more experienced coder/reverse engineer than i am?

**Comment by kriskog** [comment]
Nah, doesnt seem to do anything yet. Added it for future applications.
According to code, it should let you build apc, firelocks etc.

**Comment by trollbreeder** [comment]
Why has no one made a PR to implement that upgrade properly instead of it being a waste of mats?

**Review by Cyberboss — APPROVED** [review]

**Comment by Dennok** [comment]
> To be honest i have no clue what the simple circuits upgrade does, i've checked the file and it seems to have no code.
> Maybe you would know since you're a more experienced coder/reverse engineer than i am?

Last time it work like: Hit frame on wall to place circuit in it.

**Pull request merged**
