### PR TITLE
Watchlist notification text color

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
Changes the adminnotice text for watchlists to a similar pink used in the TGUI box for asay.

image
image

## Why It's Good For The Game
Color has better contrast for dark mode users (where it's currently a pain) without much of a contrast hit for light mode users. For accessibility, WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1. D100D1 scores 4.53:1 on white and 4.63:1 on black, meeting standards for both.
## Changelog
:cl: LT3
admin: Changed color for watchlist notifications
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
Please post screenshot of at least this colour text (not necessarily a watchlist) on light mode and dark mode

**Comment by ZephyrTFA** [comment]
Colors for stuff like this should really be a define

**Comment by Zonespace27** [comment]
Dark blue isn't great but I don't know if this is an improvement tbh

**Comment by lessthnthree** [comment]
> Colors for stuff like this should really be a define

Good point.

**Review by san7890 — CHANGES_REQUESTED** [review]
Pink-on-White is still not-very-readable... try playing with the saturation of it (desaturated pink might work)? unsure.

**Comment by dragomagol** [comment]
Agree, that pink is not great to look at on light mode

**Comment by lessthnthree** [comment]
Yeah I'll try and find something closer contrast. Sucks that we don't have light/dark mode for this. Do we keep that in a var anywhere?

**Comment by lessthnthree** [comment]
The accessibility standard WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1. D100D1 scores 4.53:1 on white and 4.63:1 on black, meeting standards for both.

**Pull request merged**
