### PR TITLE
Removes clockwork cult

### PR DESCRIPTION
**Pull request by Iamgoofball**
's name not being capitalized

### CODE REVIEW

**Comment by Iamgoofball** [comment]
it'll look better in the stats page

**Comment by PKPenguin321** [comment]
OwO

**Comment by Shihrt** [comment]
ayyy

**Comment by coiax** [comment]
I don't think this is in line with other game modes, is it?

**Comment by AnturK** [comment]
It isn't.

**Comment by Iamgoofball** [comment]
i'm going to change the rest of them to be capitalized for the stats page

half of them are capitalized and the other half aren't

**Comment by nfreader** [comment]
I run everything through `ucfirst` so this isn't 100% necessary. 

Actually, for the sake of string matching, this is a bad idea.

**Comment by Iamgoofball** [comment]
wtf antur

**Pull request closed without merging**
