### PR TITLE
Reduces cult minimum population to 24

### PR DESCRIPTION
**Pull request by ChangelingRain**
From 30.

### CODE REVIEW

**Comment by coiax** [comment]
24? Why not 25?

**Comment by GunHog** [comment]
LESS MIN POPS, MORE FUN!!

**Comment by Robustin** [comment]
I left my memes on my home PC so let me describe it for you:

Its the Sybil banner with 52 players, spammed all over the screen, then its "Cannot Force Cult: Requires minimum of 30 players and 4 antagonists" spammed over the screen, then its got a bunch of red skeleton chairs and other WAKE ME UP iconography.

Its a solid meme, but since I don't have it on me, I'll just have to thumbs up.

**Comment by Dorsisdwarf** [comment]
Its so annoying when people dont ready up, latejoin/observe, then complain that every round is traitorling

**Comment by GunHog** [comment]
I wish we had the ready count back...

**Comment by Jalleo** [comment]
Perhaps we should make it a ready up chance to be the mining people and keep a observe joining possible after 5 mins?

**Comment by Dorsisdwarf** [comment]
Making mining roles not available for 15 minutes would rustle a lot of a jimmies from all the roundstart suicide assistants though

**Comment by coiax** [comment]
In our current system, we apparently prefer roundstart suicide assistants to people just observing at round start, because we GOTTA GET THE HIGH POP SHIT, even if then the station population is effectively too low to deal with it and much salt ensues.

**Comment by KorPhaeron** [comment]
We need to make these config options

**Pull request merged**
