### PR TITLE
Adds missing sprites for suit storage and belts + improves a few other on mob sprites

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Adds missing sprites for fire extinguishers (suit storage and belt, for both big extinguishers and mini), geiger counters (suit storage mirror), shotgun shells (suit storage mirror), cigarettes and cigpacks (code and suit storage mirror), light replacers (suit storage mirror) and soaps (normal, syndie and omega belt and suit storage sprites).

**new:**
Fixes the sprite alignments for several sprites because I'm a dumb cat

Updates the on mob sprites for the HF Katana, the Multiversal Blade (or whatever it's called), geiger counter and ammobox.

Updates the cult dagger inhand like I told myself to do several prs ago but never did it matches the belt sprite now.

## Why It's Good For The Game

~~Pinks cool but what's even cooler is a sprite.~~

A lot of these were my fault for being bad.

## Changelog
:cl:
fix: Adds missing sprites for fire extinguishers (suit storage and belt, for both big extinguishers and mini), geiger counters (suit storage mirror), shotgun shells (suit storage mirror), cigarettes and cigpacks (code and suit storage mirror), light replacers (suit storage mirror) and soaps (normal, syndie and omega belt and suit storage sprites)
fix: fixes the alignment on several belt_mirror and belt sprites.
imageadd: Improves a few more on mob sprites like the HF katana, multiversal sword (or whatever it's called), geiger counter and ammo box.
imageadd: New cult dagger inhand sprites.
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
I think the Curator's whip is in need of a sprite, if you feel up to it

**Comment by necromanceranne** [comment]
I thought I fixed that, FUCK.

**Comment by necromanceranne** [comment]
okay so I checked it should totally be fixed are you sure it's still showing pink?

**Review by Twaticus — CHANGES_REQUESTED** [review]
something got messed up along the way cause some of these are backwards

for belt_mirror
cigpack is on the wrong side sprite
geiger_counter is missing side sprite
mini_FE is awkwardly big it should probably be on the back like the fire extinguisher (which is sick btw good idea)
all soaps are on the wrong side sprite
shell is on the wrong side sprite

for belt
mini_FE same as belt_mirror
all soaps same as belt_mirror

also a decent amount seem to cover the hand which i dont remember if that actually gets blocked in game or if the arm overlays work fine with them but its worth checking

**Comment by necromanceranne** [comment]
Yeah I'm not done I'm gonna come back to this tomorrow and fix up other stuff. There are more errors elsewhere but that should be in a separate pr methinks.

**Comment by Twaticus** [comment]
still a couple things busted sorry :(


/clothing/belt:
ammobox is misaligned

/clothing/belt_mirror:
shovel side sprites are backwards
shovel_serr side sprites are backwards
(also think the shovels should be switched upsidedown because the front facing makes them look like inhands)
scythe1 right directional is backwards
pitchfork0 side sprites disappear behind the body, should be bumped over a pixel or two
bullet has the wrong directional

/weapons/swords_lefthand:
cultdagger left directional is borked


thanks again for working on this, sorry for all the trouble

**Comment by necromanceranne** [comment]
Back to draft till I get enough time to deal with this. I WILL fix all these fucking sprites, so help me god.

**Comment by necromanceranne** [comment]
I'm gonna close this an atomize this back down, it's a little big right now and it'll be easier to do this slowly than all at once so I don't make too many errors.

**Pull request closed without merging**
