### PR TITLE
Resprites Majority of chairs

### PR DESCRIPTION
**Pull request by kinneb**
## About The Pull Request
Updates Chair sprites to be more appealing. Sprites made by @Imaginos16 
image
## Why It's Good For The Game
-Removes soul
## Changelog
:cl:
imageadd: Changed sprites for wooden chairs, comfy chairs, electric chairs, folding chair and shuttle seats!
/:cl:

### CODE REVIEW

**Comment by VladinXXV** [comment]
its joever

**Review by Imaginos16 — APPROVED** [review]
Haha how extraordinarily cool

**Comment by san7890** [comment]
image

is this IDB shitting the bed?

**Comment by kinneb** [comment]
> image
> 
> is this IDB shitting the bed?

Oops, thats embarassing. Fixed.

**Pull request merged**
