### PR TITLE
2014 Plan: remove parapen REMOVE PARAPEN

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Aranclanos, Giacom, and [Rock], ft. Iamgoofball
fix: remove parapen REMOVE PARAPEN
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
replace emag with cmag next

**Comment by lzimann** [comment]
Add a justification on why you want this and etc

**Comment by lzimann** [comment]
apparently it's just "2014 plan"

**Comment by Iamgoofball** [comment]
https://tgstation13.org/docs/2014Plan.html

**Pull request closed without merging**
