### PR TITLE
Replaces borg hat whitelist with a blacklist, making most hats wearable by borgs

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Expands the list of borg-compatible hats to almost anything in the game, restricted to what _isn't_ on a blacklist, rather than what _is_ on a whitelist. I should have done this a year ago when I added the check to make sure items were hat-slot compatible.

Oh, and by the by, the message about not being able to place an item on a borgs head is now gone, since we're no longer using a small list of approved items.

## Why It's Good For The Game
Arbitrary hat selection is now a bit less arbitrary. Hats help differentiate between borgs of the same module, and are fun. A blacklist is now in place for particularly visually-broken hats or ones that break things.

## Changelog
:cl:
tweak: Most headgear now fit on borgs.
/:cl:

I was really excited that drones could be placed on borgs until I tried it and it broke things.

We get this, though;
image

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
welding hard hat

**Comment by zxaber** [comment]
Wait, this actually breaks a lot more than I thought could be possible.

**Comment by loserXD** [comment]
this is good

**Comment by zxaber** [comment]
Alright, maybe I overreacted with the WIP. Fixing what I broke was a lot less hard that I feared.

Tlaltecuhtli, I have welding hoods blacklisted because they really just don't fit over the borg sprite well when down. That being said, having a welding hood on a borg doesn't stop you from flashing the borg at all. Also, I am certain you cannot possibly place a helmet that comes attached to the body piece (like most (all?) hardsuits) because even trying to pick up the helmet causes it to poof. If any particular headgear are causing issues, fixing it would be as simple as adding a line of code.

**Comment by nemvar** [comment]
What about the justice helmet? Does that thing cause any issues?

**Comment by oklews** [comment]
Can we put tinfoil hats on borgs? Can we have sec borgs afraid of security? Please tell me we can have a borg die of a heart attack

**Comment by datorangebottle** [comment]
The real question is, can borgs finally wear a security helmet so that we can easily identify the validhunting ones?

**Comment by HomocidlePancakes** [comment]
:eyes: looks at flashproof spacesuit helmets that cargo can order

**Comment by zxaber** [comment]
@oklews  @datorangebottle 
image

HomocidlePancake, flash-proof helmets don't seem to have any effect on borgs at all.

**Comment by spessbro** [comment]
not the hero we deserved but the hero we needed

**Comment by zombiegums** [comment]
Cute PR. Thank you for making this.

**Comment by ATH1909** [comment]
How does an EVA hardsuit helmet look on a borg?

Do our humanoid head sprites currently have an odd number of pixels in them? If so, maybe we should change the standard borg sprites (and those of other borg modules?) to have an odd number of pixels in them, to fix crimes against borg kind like these:
https://cdn.discordapp.com/attachments/326826573951008769/583802198052306954/offcenter.PNG
https://cdn.discordapp.com/attachments/326826573951008769/583802231233576961/offcenter2.PNG

**Comment by ATH1909** [comment]
> Can we put tinfoil hats on borgs? Can we have sec borgs afraid of security? Please tell me we can have a borg die of a heart attack

While worn hats don't usually have an effect on borgs, I could see us making putting a tin foil hat on a borg unsync them from their master AI (if they have one) and give them an ion law of some kind that says that THE MAN (or their former AI master?) is out to get them that would get removed upon the removal of the tin foil hat.

**Comment by ATH1909** [comment]
The location of the tinfoil hat (and presumably other hats) on the engiborg's sprite looks a little off; maybe we could move the location of the hat sprite to where the engiborg's "head" is on those sprites (or does that break things?)?

**Comment by ATH1909** [comment]
Don't forget to blacklist drone pAIs as well, if they count as hats (do they?).

**Comment by zxaber** [comment]
> 
> 
> How does an EVA hardsuit helmet look on a borg?
> 
> Do our humanoid head sprites currently have an odd number of pixels in them? If so, maybe we should change the standard borg sprites (and those of other borg modules?) to have an odd number of pixels in them, to fix crimes against borg kind like these:
> https://cdn.discordapp.com/attachments/326826573951008769/583802198052306954/offcenter.PNG
> https://cdn.discordapp.com/attachments/326826573951008769/583802231233576961/offcenter2.PNG

EVA helmets look weird and are blacklisted (now).


I don't really want to change all the borg sprites to line up with hats (scaling the hats out a bit would probably be better). In any case, I don't think it's a big deal if a few hats look off on a borg; As long as it isn't super terribly off and doesn't break anything game-wise, it'll be fine. People will probably just learn what hats look good and use those.

> While worn hats don't usually have an effect on borgs, I could see us making putting a tin foil hat on a borg unsync them from their master AI (if they have one) and give them an ion law of some kind that says that THE MAN (or their former AI master?) is out to get them that would get removed upon the removal of the tin foil hat.

Unsyncing an already-synced borg takes a deliberate effort and is usually obvious to the borg player when an action is being taken that can result in unsyncing. I'm not sure how I feel about any random assistant being able to unsync a borg that stands still, especially since the message to the borg about the hat placement isn't big or attention-grabbing. (And an ion law that says their former AI master is out to get them would most likely lead to a prompt AI power loss).

> The location of the tinfoil hat (and presumably other hats) on the engiborg's sprite looks a little off; maybe we could move the location of the hat sprite to where the engiborg's "head" is on those sprites (or does that break things?)?

This has to do with how hunched over the Engi-borgo is. Fixing it would require keeping track of the borg's direction and updating the hat's X offset when the borg turns, and I don't think it's that big of a deal for a silly hat feature. Anyway, it's sorta funny that an assistant runs up to the borg, and just places a hat on their back where it sorta balances.

> Don't forget to blacklist drone pAIs as well, if they count as hats (do they?).

Yeah, seems like you can with a bit of work (the pAI has to jump into the human's hand first). Seems to have the same issues as normal drones, which are runtimes all around. Just like normal drones, it also runtimes when a human takes the pAI off their own head. Maybe someday I'll figure out how to fix that. Anyway, all mob_holder objects are now blacklist (not just drones).

**Comment by ATH1909** [comment]
> Unsyncing an already-synced borg takes a deliberate effort and is usually obvious to the borg player when an action is being taken that can result in unsyncing. I'm not sure how I feel about any random assistant being able to unsync a borg that stands still, especially since the message to the borg about the hat placement isn't big or attention-grabbing. (And an ion law that says their former AI master is out to get them would most likely lead to a prompt AI power loss).

Hm, yeah, the ion law saying that their former AI is out to get them seems like a bad idea in hindsight (although an ion law saying that the borg should not allow the hat to be removed (with a clause that'd keep them from (or stop them from, if their laws would normally support it) murderboning everyone because "they could remove my hat" would still be nice). What's the harm in unsyncing the borg from their master AI, though? They'll still retain the laws that they/their master AI had before their unsyncing (right?) and it takes several seconds to put a hat on a borg, so I don't really see the issue here.

**Comment by zxaber** [comment]
Mostly because when you change laws for an AI, you expect that the borgs also get updated. This impacts both traitors and the crew recovering from traitors. Or when Nuke Ops happens and the cap needs to make them non-human, or a Wiz, and etc. When you unsync a borg, you're breaking that connection and the borg keeps whatever laws it had before, good or bad. It just creates an extra level of needless confusion for the purpose of a joke item that may not even be intended by the person adding the hat. Normally, unsyncing a borg from the AI for no real reason is against the rules (far as I know, anyway), so I'd not like to have a random interaction that does that from a feature that's supposed to be cosmetic.

**Comment by necromanceranne** [comment]
Hat stacking when. I want to make the other borgs jealous.

**Comment by ATH1909** [comment]
> Mostly because when you change laws for an AI, you expect that the borgs also get updated. This impacts both traitors and the crew recovering from traitors. Or when Nuke Ops happens and the cap needs to make them non-human, or a Wiz, and etc. When you unsync a borg, you're breaking that connection and the borg keeps whatever laws it had before, good or bad. It just creates an extra level of needless confusion for the purpose of a joke item that may not even be intended by the person adding the hat. Normally, unsyncing a borg from the AI for no real reason is against the rules (far as I know, anyway), so I'd not like to have a random interaction that does that from a feature that's supposed to be cosmetic.

I mean, the borg would be wearing an obvious tinfoil hat.

Maybe make it reconnect to its old AI if the hat gets taken off (or just synced/unsynced based on the state of its wires once the hat is off)?

**Comment by YakumoChen** [comment]
You can't actually de-hat borgs as far as I'm aware, which would make any tinfoil shenanigans that much worse.

**Comment by ATH1909** [comment]
> You can't actually de-hat borgs as far as I'm aware, which would make any tinfoil shenanigans that much worse.

You can if you replace it with another hat, IIRC.

What if tinfoil hats both unsynced a borg and cut off their binary chat access (presumably, it'd have to be changed to cut off the binary chat access of humanoids with binary encryption keys as well) so that they can't call out the AI saying malf things over binary chat if they were preemptively hatted?

**Comment by zxaber** [comment]
Eh. I'm not personally interested in linking borg hats to any hard gameplay features. Currently, the biggest change a hat does (besides a bigget hitbox) is that some hats are a free light source (and these are already allowed before this PR). If someone else wants to PR a change to the tinfoil hat borg interactions, then it's up to them.

**Pull request merged**
