### PR TITLE
like 254 new vox lines im not counting bro

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

https://github.com/tgstation/tgstation/assets/70376633/cde82903-80d9-4b9b-8d96-73b710dd61d9

255 new words, check files changed for info

## Why It's Good For The Game

vox being usable for actual sentences would be nice, actually

## Changelog
:cl:
add: 254 new vox lines
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Vox bloats out the RSC so much that there is a good argument for just replacing it with TTS messages.

**Comment by Sadboysuss** [comment]
> Vox bloats out the RSC so much that there is a good argument for just replacing it with TTS messages.

sometimes TTS is down, like it has been for the last 2 days.

**Comment by optimumtact** [comment]
That doesn't really relate to anything, the vox stuff still takes up a decent portion of the RSC for content only accessible to a single player.

**Comment by xzero314** [comment]
I use vox first thing every ai shift. Its fun and very helpful for getting peoples attention. More vox words would be awesome.If they are taking up too much space already,  I can live without more.

**Comment by MrMelbert** [comment]
ai vox currently: ~8.5% of our sound catalog (bytes) 
ai vox post pr: ~10% of our sound catalog (bytes)

**Comment by MrMelbert** [comment]
ostensibly some of these are completely useless anyways, like the atmos gas ones. 

zauker? no one even knows how to make it, let alone knows it exists

**Review by LemonInTheDark — APPROVED** [review]
this goes hard. am a bit concerned about increasing file sizes but it's like 1% of the sound folder so s fineee

**Comment by LemonInTheDark** [comment]
> ostensibly some of these are completely useless anyways, like the atmos gas ones.
> 
> zauker? no one even knows how to make it, let alone knows it exists same goes for all the meme atmos gases like anti-noblium, hyper-noblium

This is true

**Comment by carlarctg** [comment]
itd be smarter to add global generic ones like the 'could' and 'be' that you tried and failed to generate. find them by playing AI and seeing what words you wish existed but didnt

**Comment by mc-oofert** [comment]
> Vox bloats out the RSC so much that there is a good argument for just replacing it with TTS messages.

vg uses a daemon for this

**Comment by Dorsisdwarf** [comment]
I like the idea but after looking at what files are actually being added here, its almost all technical vocabulary that is hardly ever gonna be announced, not words that let you actually say sentences on the vox.

**Comment by mc-oofert** [comment]
> I like the idea but after looking at what files are actually being added here, its almost all technical vocabulary that is hardly ever gonna be announced, not words that let you actually say complete sentences on the vox.

yeah yeah uhhh nerd i just copied words from the SM page

**Pull request merged**
