### PR TITLE
Gracious Retired Contributor Armhulen has Granted Tralezab More Points (migrating gbp)

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

that account is now a ghost, should be okay to move it's points over right?

## Why It's Good For The Game

I earned those, back then the economy was nicer. Feels like i'm breaking open a piggy bank here.

### CODE REVIEW

**Comment by tralezab** [comment]
Special shoutouts to my home dog

**Comment by Kylerace** [comment]
you cant do this how do we know this is what armhulen wanted????

**Comment by tralezab** [comment]
I'll ask

**Comment by tralezab** [comment]
He said yes

**Comment by Mothblocks** [comment]
tbf i thought this one was ok, i did the same thing on the old system i just bugged mso for it

**Comment by Mothblocks** [comment]
would rather arm just work on fixes though instead of trying to get his fix

**Pull request closed without merging**
