### PR TITLE
Ports fried chicken from the 2020 toolbox tournament.

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR adds a new chicken recipe: fried chicken. The fried chicken is randomly assigned either the drumstick or wing sprite.

It is made with one chicken meat, 5 flour and 5 corn starch(for extra crispy batter).

The sprites are made by me and most of the code is by the toolbox tournament coders, although i have modified the recipe and converted the name to snake case.
image

## Why It's Good For The Game
We have a real lack  of chicken reciepes and fried chicken is one of the most common fast foods around the globe.

Chicken dishes are interesting from a gameplay perspective since they require chicken farming with is an underappreciated chef mechanic.

## Changelog
:cl:
add: You can now cook fried chicken.
/:cl:

### CODE REVIEW

**Comment by Losenis** [comment]
Does it specifically need chicken meat? If so, is there a plan on also changing the chicken nugget recipe to need chicken cutlet instead of any meat?

**Comment by Krysonism** [comment]
> 
> 
> Does it specifically need chicken meat? If so, is there a plan on also changing the chicken nugget recipe to need chicken cutlet instead of any meat?

It does specifically need chicken meat, like the chicken sandwich.

I wouldn't mind requiring chicken cutlets to make nuggies but chicken nuggets are made using mechanically reclaimed mystery meat so it isn't that much of a stretch they would call them chicken nugget even if they had no actual chicken in them.

**Comment by RaveRadbury** [comment]
I'm a fan of nuggets the way they are now, `you taste "chicken"`

**Comment by Dorsisdwarf** [comment]
At least we have chicken.

**Comment by necromanceranne** [comment]
> At least we have chicken.

Let ops spend tc for a bucket of chicken wings to eat just before changing straight into a hail of gunfire and fluking.

**Review by Twaticus — APPROVED** [review]

**Comment by cacogen** [comment]
Nice sprite

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
