### PR TITLE
Removes Free Golems from the Game

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

This PR removes free golems from lavaland. 

## Why It's Good For The Game

It seems nearly every round where golems amass any power, they come to the station looking for valids or to start a war. Lavaland, which is meant to be a sort of side quest, now has a massive impact on the station from golems alone. The issue seemingly cannot be solved by banning the bad players, as such we should remove the option. 

## Changelog
:cl: cute anime gurl
del: free golem ruin
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
You should have run this by me first.

**Comment by optimumtact** [comment]
For anyone wondering, headadmins can disable this ruin, it's explicitly a policy issue.

**Comment by wesoda25** [comment]
annnddd nothing ever happens in the policy threads

**Comment by Arianya** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=33&t=19007&start=50#p463811

Behold, the wisdom of Nostradamus, thrice given.

**Comment by subject217** [comment]
dont steal my pr author naming scheme wesoda 🔫

**Comment by wesoda25** [comment]
You’re girl im gurl

**Comment by Shadowflame909** [comment]
This isn't the Xeno ruin

The Xeno eggsac in meatyores

The Xeno event being able to happen 20 minutes into the shift

The Xeno egg being able to spawn in xenobio at roundstart



.

**Pull request closed without merging**
