### PR TITLE
Gives MDs maintenance access

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request

This PR gives medical doctors maintenance access by default.

## Why It's Good For The Game

It's a bit odd that MDs, the job officially responsible for fixing people up, have no proper access to the area where half of all people die. Not to mention that they have crew monitors in their department, which tell them where Greyshirt McGee got killed.

Other servers solve this issue by having an EMT job, but imho giving MDs maint access is the best solution for /tg/.

## Changelog
:cl:
balance: Medical doctors now have maintenance access by default.
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
HoPcurity-because-he-has-even-less-job time!

**Comment by wesoda25** [comment]
HOP will still have a job after the poorly thought out decision to keep docs without maint is removed. We’ve all played HOP and we all know some big majority of people requesting ID changes aren’t doctors. And even if it was, changing ID access is not a HOPs only job.

**Comment by anconfuzedrock** [comment]
to play devil's advocate the one thing that has made me concerned for this is if docs have maint then at this point >50% the station has the access, then again assistants do so basically everyone does.
ALSO DOES THIS APPLY TO THE CMO I'M HONESTLY UNABLE TO TELL

**Comment by 81Denton** [comment]
@anconfuzedrock CMO already has maint access on low and high pop

**Comment by FantasticFwoosh** [comment]
If assistants were any more supportive to drag people to medical from maint out of good-will or even earn $50 cash in hand per cadaver they find and $10 per disembodied organ ready to transplant by way of economic incentive, you wouldn't need to have doctors waste time on a time consuming task that is honestly beneath them.

In short, doctors have real better jobs to do rather than play fetch unless they are grossly bored. :-1:

**Comment by kriskog** [comment]
I've been saying this for a year now, thanks for doing it

**Comment by optimumtact** [comment]
I actually prefer to have the EMT job who are the doctors who roam the station.

I was thinking to actually give them access to most departments (door access, not closets or machines etc)

**Comment by francinum** [comment]
There is no distinction between those two things in many departments.

**Comment by Tlaltecuhtli** [comment]
@optimumtact make the “medical emergency botton” in the request console temporary give medical access to department

**Comment by daklj** [comment]
MD new powergame job????????????????

**Comment by SgtxRootbeer** [comment]
we have emt jackets and belts for doctors to use. its setup like a sub-job, similar to scientist vs xenobiologist. this just makes it work better.

**Comment by 81Denton** [comment]
@optimumtact If you're fine with that idea, I'll instead work on implementing EMTs so they can <s>die in maint</s> rescue people.

**Comment by 81Denton** [comment]
I'm gonna work on implementing EMTs instead. There might be sprite work that needs to be done, so I can't give any promises on the date.

**Comment by MegaEmpirical** [comment]
Downstream on Yogs we have Paramedics with most med access and maintenance. They're one of my favorite jobs.

**Pull request closed without merging**
