### PR TITLE
Fixes text gurbling in coms console and shuttle call's priority announcement

### PR DESCRIPTION
**Pull request by MrsTonedOne**
I don't want to have to find everything that uses priority_announce() and make it strip the input at the source, this seems like a better way.

### CODE REVIEW

**Comment by Robustin** [comment]
Thanks, I still have no idea how adding decode fixes the whole double sanitization issue, or where is the world priority_announce is even defined.

**Comment by Miauw62** [comment]
text garbling is caused by html_encode(), the reverse of which is html_decode()

in short: this is an ugly hack but what could possibly go wrong

**Comment by RemieRichards** [comment]
@Miauw62 wrong
text garbling is caused by double ```html_encode()```
the ```html_decode()``` in these cases is because the proc they call already ```html_encode()```s

**Comment by Miauw62** [comment]
yes, by double html_encode.
decoding text which may be only single-encoded can never go wrong, right?

**Comment by RemieRichards** [comment]
@Miauw62 he's decoding it BEFORE the second encode
this means when the message is finally outputted, it technically has only one level of encoding on it.

**Comment by Miauw62** [comment]
oh alright i thought the decoded text was getting put out.

**Comment by MrStonedOne** [comment]
priority_announce() has html_encode, and emergency.Request() uses priority_announce()

**Comment by optimumtact** [comment]
this is not a proper fix, it's a hack

:-1:

**Comment by MrStonedOne** [comment]
well, somethings send priority_announce() stripped input, some don't, there are more that do then don't, and I wanted to be able to fix this using github's interface because my working tree is reserved for the stickyban interface until i finish them.

**Comment by optimumtact** [comment]
what just stash the stickyban in another branch you meme

**Pull request merged**
