### PR TITLE
Ports Eris APC sprites

### PR DESCRIPTION
**Pull request by ghost**
:cl: MoreRobustThanYou
imageadd: Ported CEV-Eris's APC sprites
/:cl:

Closes #29809

untitled

### CODE REVIEW

**Comment by Repukan** [comment]
Looks ugly t b h

**Comment by ChangelingRain** [comment]
This is missing several sprites.

**Comment by ChangelingRain** [comment]
Replace your `power.dmi` with this one http://puu.sh/x5kDh/4097826dce.dmi
And replace your `apc_repair.dmi` with this one http://puu.sh/x5kE5/a55b3ff8f5.dmi

**Comment by lordpidey** [comment]
When you want to make a new branch, you need to BRANCH from origin master, not merge origin master into current branch.  Otherwise you'll get that commit history in that looks ugly.

**Comment by Cyberboss** [comment]
@MoreRobustThanYou when you get a chance, clean your work tree and run this to fix your fork:
```
git checkout master
git fetch upstream
git reset --hard upstream/master
git push -f
```

**Comment by WJohn** [comment]
This is fairly nice. I like em. 👍 
Most eris sprites look pretty good, though a bunch do need tweaking. I'm looking at you @Lexorion 

Gonna need to edit the ones you ported sometime soon.

**Comment by Tacolizard** [comment]
wasn't this PR already made by danno or someone?

**Comment by Tacolizard** [comment]
also @WJohn perspective wall sprites when

**Comment by WJohn** [comment]
Hah. Perspective walls. Good one.

Look at this guy.

This funny guy.

Making jokes.



Heh.

**Comment by Qustinnus** [comment]
Well I mean https://i.gyazo.com/af2320726adc3ed5e9cbaf69d46fd15e.mp4

**Comment by outbools** [comment]
@WJohn soon

**Comment by lzimann** [comment]
I really feel like this codebase sprites don't fit the game at all. Wouldn't like to see this merged(or any other sprite from there).

**Comment by MoreRobustThanYou** [comment]
#29809 is better than this, closing

**Comment by MoreRobustThanYou** [comment]
@Cyberboss i know this PR is closed, but I want to tell you i've cleaned up my fork

**Pull request closed without merging**
