### PR TITLE
Wall-mounted extinguisher cabinets are now constructable/deconstructable

### PR DESCRIPTION
**Pull request by Core0verload**
One step closer to fully constructable and deconstructable station.

It uses wall frames system, just like buttons, APCs and such. Use wrench on empty cabinet to dismantle it.

### CODE REVIEW

**Comment by xxalpha** [comment]
But you can't construct extinguishers.

**Comment by Core0verload** [comment]
You can. Step one - construct an autolathe.

**Comment by FantasticFwoosh** [comment]
Its a bit more clutter for the metal construction page but welcoming for improving station safety.

**Comment by xxalpha** [comment]
Yeah, this could be autolathe.

**Comment by Jalleo** [comment]
Tbh we should really move frames into construct from frames and build frames from metal to just declutter stuff.

**Pull request merged**
