### PR TITLE
Separates supply from civilian (service) jobs

### PR DESCRIPTION
**Pull request by ghost**
Cargo are special snowflakes now.

ss 2015-01-03 at 07 48 52

### CODE REVIEW

**Comment by TZK13** [comment]
Edging ever more close to making the QM a real head ;^)

**Comment by Cheridan** [comment]
Could go a step further and sort the way headsets are (making hydroponics/chef/bar sorted in Service, Chaplain/Clown/etc in Civilian)

**Comment by pudl** [comment]
why not also rename civilian to Service and misc to Civilian?

**Comment by optimumtact** [comment]
:+1: 

Could you look at the issue of Centcomm roles like Admirals and so forth showing up as Civilian roles? (the official ones)

#6581 

:frog:

**Comment by paprka** [comment]
This PR is ready

**Pull request merged**
