### PR TITLE
Changes a number of HUD icons

### PR DESCRIPTION
**Pull request by Spess-Rando**
Replaces the HoP's weird-looking stickman with a nice mugshot-looking icon.

hop hud

Gives the clown icon a pair of longer, playful eyes, curing it from its fatigued look! 🎉

clown hud

Also makes revolutionary and syndicate icons use thicker letters.

letter hud

### CODE REVIEW

**Comment by CosmicScientist** [comment]
Could you change the title to changes HUD icons?

The thicker rev and syndi letters look nice and I wouldn't want to blame the wrong person for that.

**Comment by GunHog** [comment]
:+1: To most of the icon changes.
:-1: To the clown icon. The big square is to represent having a big clown nose!

**Comment by ChangelingRain** [comment]
`hudchangeling` is unused, `hudheadofsecurityold` is unused, the old `hudclown` is better, and the new `hudheadofpersonel` looks like a buttplug.
also I don't like the thicker letters but people will probably disagree with me on that.

**Comment by Slignerd** [comment]
Forgot to mention these, hold on.

**Comment by Qustinnus** [comment]
i saw a head in the HoP icon but I guess you got your own priorities, joan :^)

**Comment by Slignerd** [comment]
Yeah, it is intended to be a head.

Would you like me to delete `hudchangeling` and `hudheadofsecurityold`?

**Comment by Qustinnus** [comment]
Also dont forget to change the syndie balloon

**Comment by epochayur** [comment]
don't change the syndie balloon I swear to christ, that's sacred territory you're treading on

**Comment by epochayur** [comment]
omw

**Comment by Slignerd** [comment]
Old and new:
dreammaker_2018-02-15_22-53-14
dreammaker_2018-02-15_22-51-34

**Comment by Qustinnus** [comment]
the joke of the syndie balloon kind of dies when it doesnt look like the hud icon

**Comment by Slignerd** [comment]
Uh, give me a moment.

**Comment by WJohn** [comment]
I think these look nice.

**Review by WJohn — APPROVED** [review]

**Comment by Metroidlover** [comment]
Hey, I noticed that there is two separate HUD icons in the antag HUD for Space Ninjas.
Can you see about unifying them?

**Pull request merged**
