### PR TITLE
Adds the donut steel and catbeest on a stick food items [wip]

### PR DESCRIPTION
**Pull request by ghost**
Donut steel is made with 1 sugar, 1 pastry base, and a sheet of metal. It contains a small amount of iron.

Catbeest on a stick is made with 1 rod, 2 meat steak, and a pet collar. Alternatively, a set of kitty ears can be used in place of the steak and collar.

### CODE REVIEW

**Comment by xxalpha** [comment]
:+1: :100:

**Comment by PKPenguin321** [comment]
yessss :+1:

**Comment by as334** [comment]
:+1:

**Comment by PKPenguin321** [comment]
now all we need is the donut mech

**Comment by KorPhaeron** [comment]
I know I'm gonna get called an SJW or something for this but I don't really think epic /pol/ memes regarding a highly divisive/sensitive political issue have much place in SS13. 

Taking it too seriously, I know.

**Comment by RemieRichards** [comment]
@KorPhaeron what about this is /pol/, like seriously? dindu muffin is just the phrase "I didn't do nuffin" which is just a humorous way of saying "I didn't do anything" (lit "I didn't' do nothing")
and donut steel is a reference to children who misspell "do not steal" when they post their original characters.

if this is somehow a /pol/ meme, it's far broader than that.

**Comment by optimumtact** [comment]
dindu's I'm pretty sure came from pol and spread out from there.

The other one is somewhere

**Comment by RemieRichards** [comment]
Hmm, apparently a /pol/ meme from 2014?

so why the fuck have I heard it prior to 2014...
CAN I SEE THE MATRIX?

**Comment by Xhuis** [comment]
in this context it's referencing the fact that assistants are often dragged into the brig screaming "I DINDU NUFFIN"

**Comment by Kromgar** [comment]
Do not steal came from all those hedgehog pictures on deviant art

**Comment by RemieRichards** [comment]
@Xhuis which is still referencing the riots and the meme's origins, just remove it.

**Comment by Kromgar** [comment]
http://www.urbandictionary.com/define.php?term=Donut+Steel

**Comment by Kromgar** [comment]
hahaha that fucking branch name

**Comment by Xhuis** [comment]
catbeest on a stick added

**Comment by Xhuis** [comment]
wow all these sjws seriously

**Comment by GunHog** [comment]
This PR is #10209 but on the other side of the spectrum. I feel this PR's existence is a justification for the re-opening of the other. For balance.

**Comment by PKPenguin321** [comment]
RIP dindu muffins

**Comment by optimumtact** [comment]
@GunHog except we have more people on this side than we do on the other

**Comment by freerealestate** [comment]
damn, all these racists

**Comment by Razharas** [comment]
You need to be at least maintainer rank to get your meme-prs merged

**Comment by Miauw62** [comment]
Dindu nuffin reminds me of discworld tbh. This PR is great,I actually
laughed at dindu muffin.
Op 28-jun.-2015 06:30 schreef "Kromgar" <notifications@github.com>:

**Comment by PKPenguin321** [comment]
wtf raz why

**Comment by Xhuis** [comment]
I DINDU NUFFIN

**Comment by Dorsisdwarf** [comment]
Needs opening again!

**Comment by PKPenguin321** [comment]
yeah for real we have a bunch of stupid jokes in the game from ye olde times, why not add new ones

**Comment by Aranclanos** [comment]
I SAID STUFF
(Aranclanos) and if that random guy can add his stupid memes, that means everyone can?
(Aranclanos) come in idiots and retards, add your memes to the game, its allowed!
(Aranclanos) or who is to say which ones are allowed or not?
(Aranclanos) the funny ones?
(Aranclanos) funny for who even?

**Comment by Strathcona** [comment]
Eh... this just sets a bad precedent and adds little to the game. I'd wager it's like the cat stuff. On it's own probably not so bad but just very much not worth the ensuing storm of drama. Go then, there are other PRs than these.

**Comment by Razharas** [comment]
Thanks for shilling for me aran, ill tell cheri i support giving you maintainer back

Also if we cant have doge why can we have this?
I demand doge back, at least it was really popular meme unlike these

**Comment by Iamgoofball** [comment]
now that we have filthy cattebeest because you dumb furries merged it can we have this merged

**Comment by Aranclanos** [comment]
nah

**Comment by Xhuis** [comment]
good maintainers
hey at least you didn't merge it while it had the [wip] tag

**Comment by Xhuis** [comment]
okay you can merge it now

**Pull request closed without merging**
