### PR TITLE
Revert "Tilening V2 Part 2: KrysonWood Edition"

### PR DESCRIPTION
**Pull request by Kapu1178**
Reverts tgstation/tgstation#69088

The sprites are horrifically bright and I've spoken to exactly 22 users, 19 of which said they heavily dislike the sprites.

I'm invoking the power of opensource to push for this to be undone.

### CODE REVIEW

**Comment by fighterslam** [comment]
I support this

**Comment by BrotherHangyul** [comment]
ided

**Comment by thgvr** [comment]
lol

**Comment by AdipemDragon** [comment]
if the problem's with the wood tiles themselves (and because it's too late to atomize an already merged pr), can't you do a selective undo instead?
(i honestly think there could be another way for the wood floors to be handled that's not "undo to the old" or "keep the ultrabright" but i'm just trying to see if an atomized revert is possible)

**Comment by tralezab** [comment]
looks fine to me idk
image

**Comment by Imaginos16** [comment]
Since I have talked with the PR author about the fact I was already in the works to make a compromise version that uses the newer style but changes the coloring to something everyone is more used to, I will put it in DNM as I get to work finishing it. Its a busy week after all.

**Comment by CPTANT** [comment]
You need lower contrast on the colours for the wood.

**Comment by optimumtact** [comment]
Don't care, cope seethe touch grass

**Comment by LemonInTheDark** [comment]
sucks to suck. spritetainers should do what they want

**Pull request closed without merging**
