### PR TITLE
New access level for cloning rooms and cloning pods

### PR DESCRIPTION
**Pull request by erwgd**
### Summary:
1. New access level, _Cloning Room_, provided to Medical Doctor, Geneticist and CMO on minimal access. Chemist and Virologist gain this on extended access.
2. On BoxStation and MetaStation, the cloning room door facing the medbay requires both Medical and Cloning Room access.
3. On BoxStation and MetaStation, the cloning room door facing Genetics Research requires Medical, Cloning Room and Genetics Lab access.
4. Cloning pods require Cloning Room access to unlock, instead of Genetics access.

Image of airlock electronics settings for cloning lab doors
MetaStation's cloning room doors also have these sets of requirements.

### Rationale:

This PR was made to make the cloning room on BoxStation accessible to medical doctors, even with minimal access. For this a new access level has been created, named _Cloning Room_, which allows a doctor to access the Genetics cloning room without being able to enter the research portion of Genetics. 
The Cloning Room access level is provided to all medical doctors, geneticists and Chief Medical Officers. In a skeleton crew it is also provided to chemists and virologists.

Geneticists may still find work to do with clones; even if doctors are cloning people with a good cryo mix that fixes genes and brains, geneticists are still needed to give UI+UE treatment to clones who've lost their previous identity after having to undergo a brain transplant.

I also want to make cloning lab access consistent across the current maps, so that Cloning Room and medical access is needed to enter the cloning room on each map.

This PR also makes cloning pods require Cloning Room access to be unlocked, so doctors can unlock it to eject the pod in emergencies (I'm aware of the APC trick). Genetics access will no longer be accepted, but anybody with Genetics access (geneticists, CMOs and RDs) can still unlock the pod as they have Cloning Room access.

I'm using "Cloning Room" instead of "Cloning Lab" because I believe Nanotrasen views cloning on its own as an established procedure, rather than an experiment. There isn't much research that can be done using the cloning machines.

### Changelog:
:cl: Erwgd
add: A new access level is available, named "Cloning Room". Medical Doctors, Geneticists and CMOs start with it.
tweak: On Box Station and on Meta Station, the cloning lab doors require Cloning Room access in addition to each door's previous requirements.
tweak: Cloning pods are now unlocked with Cloning Room access only.
/:cl:

### CODE REVIEW

**Comment by Anonmare** [comment]
I don't think the RD needs access to the cloning lab, it's not his job to process dead bodies.

**Comment by TechnoAlchemisto** [comment]
RD shouldn't have it, but good change

**Comment by erwgd** [comment]
I'll see to removing RD's access to cloning!

**Comment by Anonmare** [comment]
In skeleton access sure that's fine enough, though you may want to mod the medbay's door side to require medical access and cloning lab access so the RD doesn't have access to two departments at roundstart.

**Comment by erwgd** [comment]
The medbay-facing door should already work as Anonmare described.

**Comment by erwgd** [comment]
If I removed the Genetics exit buttons and changed access requirements on the purple Genetics Research doors, clones won't be able to leave without assistance, but Science jobs in skeleton crews would be able to access cloning without access to Medbay.

**Comment by XDTM** [comment]
Genetics exit buttons are definitely more important here.

**Comment by erwgd** [comment]
I'll be keeping the Genetics Research and exit buttons as is, then. While Science may get the Cloning Room access level in skeleton crew rounds, they still won't actually be able to access the cloning room since they could push the exit button to access Medbay.

**Comment by erwgd** [comment]
Since science jobs cannot access the cloning room with Cloning Room access alone, I'm removing Cloning Room access from their skeleton crew access.

**Comment by SweaterKittens** [comment]
I'm for this, 100%. One of my roundstart routines as CMO is to go over and turn on Emergency Access to the cloning room doors, so the window doesn't inevitably get broken when a doc/good samaritan comes in and me or the geneticist (if there is one) is nowhere to be found.

**Comment by Arianya** [comment]
Uh, the RD absolutely *should* have genetics access.

Despite being located in Medical, its a science department and they report to the RD.

So either we need to reallocate Genetics to medical or give the RD back access, because the boss not having access to where his subordinates work is kinda silly.

**Comment by SweaterKittens** [comment]
I have always been under the impression that genetics was a Medical department, and that they report to the CMO. Even on the wiki, genetics is listed under Medical. And it's a part of the Medbay, seperated from the Science department. Is my whole life a lie?

**Comment by jughu** [comment]
I mean the cloning part is medbay but the dna research part is part of sciencw and yet cmo has access to muh dna research and rd doesnt have access to muh cloning kick that cmo out of my dna research!!!

**Comment by kevinz000** [comment]
RD > CMO kick the cmo out.

**Comment by jughu** [comment]
Solution is make cloner cloner lab and wall genetics dna research off so PEACE MAY BE RESTORED!!!

**Comment by Arianya** [comment]
Cloning so perfect that it gives brain damage :smirk:

**Comment by JJRcop** [comment]
@Arianya The RD still has genetics access just not access to the cloning room.

**Comment by Arianya** [comment]
@JJRcop I know some maps like box have dedicated Science access, but doesn't not having cloning access make genetics inaccesable on some maps? Admittedly more a mapping issue then a access levels one, but still.

**Comment by JJRcop** [comment]
That will just give the RD more power than they should be given for the sake of bad mapping.

**Comment by Kromgar** [comment]
Its just being able to enter the cloning room how is that broken?

Itt makes upgrading easier

**Comment by jughu** [comment]
I meab cmo can enter genetics lab why shouldnt rd be able to enter cloning?

**Comment by erwgd** [comment]
If somebody enters the cloning room they can use the room's exit button to enter Medbay, so I don't want to give the RD cloning room access as this would indirectly give them a way into Medbay with just their ID.

**Comment by jughu** [comment]
Then remove cmo from genetic labs itself they can just brew mutadone to remove disabilities!

**Comment by optimumtact** [comment]
cloning is a medical department

**Comment by erwgd** [comment]
I worded part of the changelog wrong:
>On Box Station and on Meta Station, the cloning lab doors require Cloning Room access in addition to each door's previous requirements.
The medbay-facing door no longer requires Genetics Lab access, but my changelog implies it still requires it.
*shrug

**Pull request merged**
