### PR TITLE
Fixed pubby emergency shuttle

### LINKED ISSUE #30310: Pubbystation shuttle has terrible copy/paste mistake
I accidentally copy/pasted the maint bar onto the emergency shuttle by mistake, and this is causing it to lose all oxygen :sob: 

DreamMaker isn't working today so I have no way of fixing it

To fix: just copy the shuttle file back onto the map file

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #30310

### CODE REVIEW

**Comment by pubby** [comment]
Thanks a ton, Shiz. I really appreciate how much you've done to fix my stupid mapping mistakes.

**Comment by KorPhaeron** [comment]
Sounds important

**Comment by PraiseRatvar** [comment]
sPEEDMERGeeeeeeeeeeeee

**Comment by Cyberboss** [comment]
S t o p, K o r.

**Comment by KorPhaeron** [comment]
Speedmerging for a map being unplayable is a legitimate use of speedmerge

**Comment by ShizCalev** [comment]
7c6d9-clip-78kb

having a gaping hole in the emergency shuttle does seem like a pretty important issue.

**Pull request merged**
