### PR TITLE
Faster projectiles

### LINKED ISSUE #17598: Projectiles move slower on sybil
Disabler beams and such projectiles move slower then runspeed on sybil making them very, very easy to dodge.
If this isn't a bug, just close it, but I feel it is.

### PR DESCRIPTION
**Pull request by phil235**
Projectiles are now twice as fast. Fixes #17598.

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Does this mean I can't meme with security officers where I have five chasing me before some random grey shirt disarm-shoves me and I get caught?

**Comment by PKPenguin321** [comment]
Sucks

**Comment by Durkel** [comment]
But how am I supposed to dodge all those taser shots?

I know this might piss some people off saying this, but being able to dodge the shots of enemy fire was about the highest skill level we have. Not because it took a lot of effort to actually dodge, but because getting hit once was essentially a death sentence. If we're going to speed up shots so they're un dodge able we should really make a big push towards a non stun based combat system. Otherwise we're really going to be in shit zone central of one shot gg combat.

**Comment by Tacolizard** [comment]
i agree with durkel somewhat. I think we should use different projectile speeds for different weapons. i think that energy-based weapons should keep the current speed, but ballistics should not. we could really use projectile speed as a feature to introduce new meta and combat gimmicks.

**Comment by ShadowDeath6** [comment]
Another sec buff smh :triumph:

**Comment by ChangelingRain** [comment]
I'd suggest doing smaller adjustments, like to 0.9, first.

**Comment by phil235** [comment]
Alright, I'll make it less fast.

**Comment by CPTANT** [comment]
Ohw come on guys, outrunning lasers was complete bullshit.

**Comment by kevinz000** [comment]
I'd suggest test merging with a global var editable by admins to control global default projectile speed so it can be play tested in game.

**Comment by phil235** [comment]
>But how am I supposed to dodge all those taser shots?

There's being able to dodge, and then there's being able to OUTRUN bullets.

**Comment by KorPhaeron** [comment]
Gunfights are far more fun and engaging when they don't just end after two guys pull the trigger at eachother.

**Comment by CPTANT** [comment]
@KorPhaeron 
Gunfights are a lot more engaging if your bullets can actually catch up with the person running away from you....

**Comment by ExcessiveUseOfCobblestone** [comment]
T A S E R B U F F

@CPTANT one click and the fight is over isn't very engaging in the realm of tasers, which if you've managed to nab a lethal gun you probably have access to stun-based ranged weaponry as well.

**Comment by CPTANT** [comment]
Tasers are the least effected by this, since they can only be used close range anyway.

But seriously, say it: "I think people should be able to outrun bullets"

Say it.

**Comment by A-t48** [comment]
Why not keep tasers current speed but increase the speed over other weapons?

**Comment by anconfuzedrock** [comment]
why not just do it to disablers

**Comment by Saegrimr** [comment]
Yet many other codebases already have instant-travel lasers.

**Comment by KorPhaeron** [comment]
@saegrimr

You get banned for killing people on bay so the combat system being fun or balanced doesn't matter

**Comment by Iamgoofball** [comment]
@KorPhaeron you get banned for killing people here too it's just delayed

**Comment by optimumtact** [comment]
If this is just a single var change then admins can adjust it anyway

**Comment by KorPhaeron** [comment]
@optimumtact 

Admins can't adjust it because new projectiles are constantly being created and destroyed (recharging and firing)

@CPTANT 

Yes I think it's more fun when people can outrun the projectiles. No I don't give a shit about realism because nothing in the game is realistic.

**Comment by PKPenguin321** [comment]
Based kor

**Comment by Bawhoppen** [comment]
I don't see any reason for this, and this will just make it combat less interesting

Also I thought that projectile speed gets rounded

**Comment by Iamgoofball** [comment]
@KorPhaeron yeah but it also means that fucking stun baton throw stun chance is more useful than a taser

**Comment by optimumtact** [comment]
Just make it set via a global var on the config datum, then admins can adjust it at will.

**Comment by CPTANT** [comment]
@KorPhaeron 

Hurd dur, my great evasion skills consist of running away from bullets in the same line they are travelling.

**Comment by X-TheDark** [comment]
I was under the impression that `sleep` can sleep at the very minimum `world.tick_lag` amount...and isn't `tick_lag` by default 1? Wouldn't having a `sleep(x)` where `x < world.tick_lag` still sleep for the `world.tick_lag` amount?

**Comment by YakumoChen** [comment]
Playing yakkety sax with greytide is incredibly annoying when they can just outrun every shot I fire

**Comment by KorPhaeron** [comment]
Is this test merged currently? Projectiles seem pretty fast

**Comment by optimumtact** [comment]
The Future is here and it's lag free.

**Comment by KorPhaeron** [comment]
optimum "steelpoint" tact buffing security again

**Comment by optimumtact** [comment]
Madly pressing the arrow keys to jerk your character all over the screen as if they were played by Michael J Fox is not a tactic

**Comment by PKPenguin321** [comment]
You are wrong, the issue was being able to run in the same direction as the bullet and being able to go faster than it, not that bullets can be dodged

**Comment by kevinz000** [comment]
I kinda feel bad now because I can't dodge bullets either.

**Pull request merged**
