### PR TITLE
Revamps Bioterror Darts

### PR DESCRIPTION
**Pull request by MMMiracles**
improve not remove!!!

Turns the bioterror rounds into a less-lethal syringe variant, removing the coniine and spore toxin from it all together.

Comes in a box of 7 syringes that can be loaded into the never used syringe gun or whatever else the OPs can come up with (invite the captain to a dinner and spike his food?).

Still viable for knocking out singular targets quietly, but harder to spam it into a crowd.

### CODE REVIEW

**Comment by daman997** [comment]
was this taken from my idea
if so good job I cannot code for shit

**Comment by Cheridan** [comment]
I think it's more accurate to say that you're removing the darts and replacing them with syringes... In which case, isn't there already a traitor toxin kit?

**Comment by MMMiracles** [comment]
Operatives don't have any spare beakers/syringes on their shuttle unless you consider the 3 charcoal ones enough. This is just meant to fill the gap the bioterror has without the insta-kill ability of it, while making it more difficult to spam into a crowd.

A really determined operative team COULD buy toxin kits and steal shit off the station to max their deathmix I guess but this is just meant to be the non-lethal alternate for quick singular take-downs.

**Comment by optimumtact** [comment]
Non security players should code more :+1:

**Comment by SconesC** [comment]
jokes on you oranges they do play sec :^)

**Comment by Niknakflak** [comment]
eh not really

**Comment by Supermichael777** [comment]
:+1:

**Comment by PKPenguin321** [comment]
\>inb4 the new meta is getting this, putting it in a beaker and throwing it at people

**Comment by MMMiracles** [comment]
people could of done the same thing with the toxin kits for awhile now but I've yet to see it happen so ¯\_(ツ)_/¯

**Comment by PKPenguin321** [comment]
yeah that's because bioterror darts are 100x better

**Comment by Supermichael777** [comment]
people could have used the glasses in the lounge. people realy need to think about how chem application methods could fall into antagonistic hands.

**Pull request merged**
