### PR TITLE
Buffs The Xeno Armblade

### PR DESCRIPTION
**Pull request by DootLord**
Xeno arm-blade takes time to get as well as it requires a sacrifice from the player. Permanently losing their arm for a weapon doesn't make sense when they could just protolathe a circular saw for the same damage without any downsides.

## About The Pull Request

The request simply changes the force damage for the blade from 15 to 25. This may be too much as 20 could be the sweet spot. I feel this should be open for discussion.

I've also updated the text to make it more clear, my first impressions was that that extract would turn into the blade, not my arm itself.

-- Please give any feedback for the rework you can! --

## Why It's Good For The Game

This rewards players that decide to use xeno for a weapon. Xeno takes time to get something out of it and for a weapon to remove the ability to use an arm as well as requiring a time investment to get there it makes no sense for it to do 15 damage given that other surgical tools that are easily accessible from round start do the exact same damage.

## PR Update

After discussion with the community the changes will be as follows:

- The arm is now retractable. A player will take 3 brute and 3 toxin damage on equipping the weapon
- The arm will do 10 brute damage and 5 cellular damage on hit
- MAYBE: The arm athestitcs will be updated to be more slime related.

### CODE REVIEW

**Comment by Dawson1917** [comment]
xenobio gets a 25 damage weapon for playing the game

**Comment by DootLord** [comment]
> xenobio gets a 25 damage weapon for playing the game

Do you feel 20 could be the right amount of damage, or are you completely against this change?

**Comment by Dawson1917** [comment]
> 
> 
> > xenobio gets a 25 damage weapon for playing the game
> 
> Do you feel 20 could be the right amount of damage, or are you completely against this change?

i hate 90% of the random toys xenobio gets but considering welders/saws already do 15 damage this armblade would be better at 18-19 damage. anything over 20 is overkill

**Comment by DootLord** [comment]
> > > xenobio gets a 25 damage weapon for playing the game
> > 
> > 
> > Do you feel 20 could be the right amount of damage, or are you completely against this change?
> 
> i hate 90% of the random toys xenobio gets but considering welders/saws already do 15 damage this armblade would be better at 18-19 damage. anything over 20 is overkill

Okay I feel that. I think 18-19 would be nice to have. Can you see any other issues with it? Also why do you hate xenobio's toys?

**Comment by Dawson1917** [comment]
> Okay I feel that. I think 18-19 would be nice to have. Can you see any other issues with it? 

18-19 is already some of the best damage you can get as a non-antag short of a spear or fireaxe, and the armblade can't be disarmed & stolen like those weapons

**Comment by knacker48** [comment]
Have considered giving it some unique effects instead of just buffing the damage? Maybe make it more of a slime blade rather than a worse armblade? Maybe give it a different damage type or make it do a small amount of clone or toxin damage mixed with the regular brute?

**Comment by MonsWTF** [comment]
Yeah I'm gonna have to lean w/ Knack on this one. Personally (with all the tools we Xenobio's currently have to be able to stun/disable people) it felt like the 15 Damage was just what could be considered fair grounds for a weapon, It's 7-8 hits from crit'ing someone, depending on if they had minor damage already from you disabling them, and can very slowly pry open doors. The drawback of course is that you look like a changeling permanently, but honestly people tend to view someone walking around looking like Ling as "Xeno fuckery".

What other options are possible? Giving it a more slime-based sprite, and getting the option to retract on long cooldown? I certainly think having the damage be a mix of 8-11 Brute and 1-5 cellular would be the next place to take it, as going above 15 dmg feels like a lot to ask.

**Comment by DootLord** [comment]
> Yeah I'm gonna have to lean w/ Knack on this one. Personally (with all the tools we Xenobio's currently have to be able to stun/disable people) it felt like the 15 Damage was just what could be considered fair grounds for a weapon, It's 7-8 hits from crit'ing someone, depending on if they had minor damage already from you disabling them, and can very slowly pry open doors. The drawback of course is that you look like a changeling permanently, but honestly people tend to view someone walking around looking like Ling as "Xeno fuckery".
> 
> What other options are possible? Giving it a more slime-based sprite, and getting the option to retract on long cooldown? I certainly think having the damage be a mix of 8-11 Brute and 1-5 cellular would be the next place to take it, as going above 15 dmg feels like a lot to ask.

I like this idea the most thus far. 

This is my first pull and I'm not used to the code, but I'm determined to see if I can make it work like a togglable ability using the damage split between brute and cellular.

As for the sprite I'm sure I can do some photoshop goodness. I'll get to it this evening.

**Comment by Ty-the-Smonk** [comment]
Ok so I’ve always thought the xenoblade is dumb as fuck since chainsaw arms exist and are just better, so actually make it do an effect (like stamina damage or something)

**Comment by DootLord** [comment]
> Ok so I’ve always thought the xenoblade is dumb as fuck since chainsaw arms exist and are just better, so actually make it do an effect (like stamina damage or something)

I was considering the upgrade to the xenoblade over chainsaw arms is portability. If it's a toggled ability then it frees up a slot and lets you have something half decent to protect yourself with even if you're butt naked.

**Comment by Ty-the-Smonk** [comment]
Well the whole point of the blade is that it removes a hand slot, if you make it toggle able than keep the 15 damage

**Comment by DootLord** [comment]
> Well the whole point of the blade is that it removes a hand slot, if you make it toggle able than keep the 15 damage

Good shout, I feel this makes the most sense balance wise right now. Less power but more utility.

How do people feel about maybe causing damage to the player's arm upon activation in exchange of having an on hit effect with the weapon?

**Comment by Ty-the-Smonk** [comment]
Make it deal 3 brute and unable to be toggled if your arm is broken

**Comment by Ty-the-Smonk** [comment]
3 brute on activation

**Comment by DootLord** [comment]
Do we want any kind of toxic/slime effects in exchange for making the arm deal more self damage?

**Comment by Ty-the-Smonk** [comment]
Change the sprite to look green and transparent and make it deal toxic damage instead, since slimes are assholes

**Comment by Ty-the-Smonk** [comment]
Also might as well rename the pr to a rework of the blade

**Comment by DootLord** [comment]
I'll wait for more feedback first as everyone seems to have very different ideas for this.

**Comment by Ty-the-Smonk** [comment]
Good call

**Comment by carlarctg** [comment]
make it a green-tinted armblade that deals some cellular, is my take on it
putting extracts in it so each one gives it an unique effect would be neat, but it'd be untold levels of xenobiology bloat so probably do not do that
dont have it be transparent other than the inhand, since you'd just see your arm behind the transparent mob armblade

**Comment by Qustinnus** [comment]
don't say rework when you change 2 lines ree

**Comment by DootLord** [comment]
Yeah my bad. Should've done the re-title after my changes

**Comment by JackTGarland** [comment]
> 
> 
> don't say rework when you change 2 lines ree

But if you are changing how it work's fundamentally. It is a re-work.

I prefer the idea that it dose toxic damage, if it is retractable it should do damage to self. But I think should be it. We don't want to make a swis army knife.

**Comment by Dawson1917** [comment]
10 brute 5 cell damage when hitting someone, 3 brute and 3 toxin damage on self when activating the arm - an incentive to use it as a slimeperson

**Comment by Jessen21** [comment]
Well if you're going to give it the retractable function, thats good, it 'does' give it more utility and viability that hasn't been there for it. Of course if it's going to get a retractable function, then we should also look at the chilling green gun-arm version and see if that could use a similar treatment.

**Comment by CRITAWAKETS** [comment]
If you want to make it slime-like, make it so that it builds up charge slowly over time for a large amount of stamina damage with an attack, however attacking gets rid of all the charge.

**Comment by Ty-the-Smonk** [comment]
A charge up attack would be kinda useless as fuck in our combat system

**Comment by Learner10** [comment]
Now, hold on. I can actually see some usage in allowing for the arm to take in various extracts for various types of damage or effects... not all extracts would make sense or have a logical effect, but some would certainly make for some interesting variation on how they'd work.

Hell, you could theoretically make some new effects, like a silver infused arm-blade would drain target nutrition in addition to a semi-weaker basic attack, and then cause additional damage that adds to more if the target were starving, like a Fernet. Orange incorporates some temperature increase and heat damage, Blue is cold heat damage, Metal is pure brute damage, Sepia causes target to slow in speed... you get the picture. Hell, you could make it so that one of the extracts GIVES you the ability to return to an ordinary arm.

The damage stats for the various implants could be shifted, and if we go down the route of a sprite rework, the extract inserted could be displayed as like a colored blobby sphere on the shoulder of the wielder.

**Comment by Shadowflame909** [comment]
>xenobio gets a 25 damage weapon for playing the game

Even the initial change was good tbqh.

Every department gets the equivalent of a missile at round-end.

Robotics once had round-end missiles y'know.

**Comment by MonsWTF** [comment]
> > xenobio gets a 25 damage weapon for playing the game
> 
> Even the initial change was good tbqh.
> 
> Every department gets the equivalent of a missile at round-end.
> 
> Robotics once had round-end missiles y'know.

Yeah, but it'd be one more missile among the various nukes Xenobio already has. 
- We have a crossbreed that is an improved slime transformation that doesn't drop your gear. 
- We have a crossbreed that can make 3 hostile mobs friendly to the summoner
- We have a crossbreed that can shock up to 4 people nearby that aren't wearing insul's for 25 Dmg.
- We have a crossbreed that can set anyone within 5 tiles of your character on fire
- We have multiple crossbreeds for various-sized explosions
- We have a crossbreed that can literally make any clothing space-worthy (preferably warm clothing to prevent space freezing)
- We have multiple types of full-heal crossbreeds, with one sporting brief immortality
- We have a crossbreed that gives us a backup clone in the event we die

The amount of latent power in Xenobio practically rivals that of any attempted Toxins bomber, but the difference is that the good Toxins scientist can't leave their lab with a bomb unauthorized, while Xenobio has practically free-reign to do whatever with their extracts. I would go so far as to say that Xenobio is on-par with Mining's content.

**Comment by Shadowflame909** [comment]
It's strong for sure. But a strong department is nothing new.

I would say most of it's strength are countered by the endgame of other end games anyways.

All crossbreeds come with downsides. This change aint really so different.

And a 25 brute weapon wont save you from botanys instant death limes or do much against a mech

**Comment by MonsWTF** [comment]
What would be the timeframe for when the round has reached "endgame"? 

As it stands, a good Xenobio can reach roughly 19 colors and Rainbow by the 40-minute mark. 

Depending on RNG variables, the Xenobio needs to get Orange and Purple slimes within generation 2 or 3 (first 8 minutes), and getting Green at Gen 4. Essentially, if they specifically built for it, they can have the 25-damage Armblade by the 12-minute point of a round if they rushed it.

**Comment by Shadowflame909** [comment]
RNG like you've said. Unless your IRL luck stat is supreme. You're going to be hard pressed to having your slime machine beyond tier 2 in a tine good enough for the crossbreed req. Ignoring how frequently slime splitting will leave you with the wrong colors for a couple generations of build up.

**Comment by Learner10** [comment]
Yea... 25 damage is a bit much. A person gets sent into crit within 5 seconds, and I think that by the 2nd hit, or after 50 damage is dealt, they get slowed, thus dooming their fate. I'm not sure of the health slowdown stats exactly.

Anyhow, there is VERY little that reaches 25 damage that isn't something outrageous.

**Comment by Shadowflame909** [comment]
Don't fear gamer

E-swords do 30 damage, katanas 40 and 12 tc syndicate revolvers 60.

Ignoring potential armor. You're looking at a couple hits of "wtf" compared to some of the most powerful round-start weapons a crewmember can get.

Looking at you Screwdriver.

**Comment by MonsWTF** [comment]
There's not an extreme amount of RNG luck behind getting enough Oranges and Purple in the early-game. The hardest part is getting the mutations to occur in Gen 1 or 2, and most of the time you are able to get it by pure numbers.

Even if stuck on Tier 2, you can create extra grey slimes to increase the number of offspring and thus, increase the likelihood of hitting at least 1 orange and 1 purple, and from there, 1 green.

By probability standards, at the base 30% Mutation chance, you have a 47.8% chance to get at least one Green slime out of the 4 offspring of an Adult purple. The likelihood of getting a Green increases by ~1.2% per 1% mutation chance of the Adult.

Knowing that likelihood, in the event you get average RNG, you can expect a Xenobiologist rushing for Burning Green to get it within the 5th Generation of slimes, somewhere around 12-16 minutes into the round. This is also easily doable even with Tier 2 parts, but in the event they have Tier 3, they won't have to worry about farming the Oranges as much.

In the event you get terrible RNG or didn't kill at least 5 Oranges for the Green, it could go up another Generation in time, which will delay the Xenobio another 4 minutes. In the event of perfect RNG, you could need 4 minutes less. 

- 8 minutes at the earliest (good RNG)
- 12-16 minutes normally (average RNG)
- 20 minutes or more (bad/terrible RNG)

I also don't think it's fair to compare Traitor items to a job item that cannot be dropped/removed easily. If we are, then that's conceding to the argument that the Armblade is in the same damage-class as spending TC on traitor weaponry.

**Comment by Shadowflame909** [comment]
I was pointing at those items specifically (Katana is something mining can get) to show how high damage items can go yet still giving you time to go "WTF".

Now your baseline is way off. Slime mutation chance starts at 22% One slime will be +2/4 and the other -2/4. With the other two being in the middle for your base RNG.

You have a 78% likely hood that your first mutation will NOT offer any slime mutations.

That's in total 4 minutes already wasted. 

You target the highest slime and go for the one with the 26% mutation chance. Now you have a little over a 1/4th chance. Which can lend you grey, metal, orange, purple, or blue. 

Being quite honest. You're usual RNG is going to be 3 greys with 1 mutation. Usually metal from my experience.

But counting on some sort of luck Master. Let us say you got 1 metal, 1 blue, and 2 greys. Since the pure RNG is all hypothetical.

The Metal was the one with the highest chance so that metal is now at 30%. While one of the grey's is at 24% again.

See my point on how RNG doesn't work in your favor.

Not even counting on the balancing act that is keeping up and making sure you don't run out of monkeys. 

All in All. By the time you roll oranges, and breed them in your favor. Which should be around 24m if you don't get any repeat slimes. (Very common.)  

By this point. I could have been on lavaland and built myself a bone fireaxe. I could have bought guns with cargo, gotten myself a chainsaw arm. Or even sharpened a glass shard to give me a 15 brute discreet cutting weapon.

**Comment by MonsWTF** [comment]
`var/mutation_chance = 30 // Chance of mutating, should be between 25 and 35`

Am I missing somewhere else that the mutation chance has been setup in the code? 30% is the default afaik, not 22%.

`M.mutation_chance = CLAMP(mutation_chance+(rand(5,-5)),0,100)`

Also, the deviation range per split slime is -5 to +5 from the base mutation, not this +2/4 or -2/4 that you suggest?

`		if("grey")
			slime_mutation[1] = "orange"
			slime_mutation[2] = "metal"
			slime_mutation[3] = "blue"
			slime_mutation[4] = "purple"`

And this is the literal list of mutation options for the starting Grey slimes. There is no weighting on Metal slimes greater than the other 3. 

The monkey cubes balancing act is also a non-issue, since any Xenobio can easily make more grey slimes by injecting their extract with plasma, kill that slime, and reap another 2/3 extracts depending on parts Tier.

I do not know why you are referring to Anecdotes as being more relevant than the actual code. As it stands we don't see the Armblade used that often, but I cannot agree with this premise of giving it more damage to make it more viable when Xenobio is already considered "one man god mode" status. 

Giving the armblade damage variety, allowing it to be retractable, and even allowing it to be distinguishable from actual Ling armblades, is plenty enough of a buff to it to make it more desirable, and hell, maybe even profitable for the biologist.

**Comment by Shadowflame909** [comment]
Ahem. Your code is false. It definitely starts at a 22% mutation chance.

Xenobiology could literally become lings before crossbreeding. The armblade is the downgrade.

Tis a weapon that requires effort for its use. You feel like antag items should be inherently better and I agree with that. But the crew vetting antag lite items is traditional /tg/.

Death Neetles are 30 burn damage items. Same as an e-sword 

Stuff like this is countered by creativity, time and effort. The same way it  is made.

If you spend the time getting augmented. You gain an innate stackable armor
Become a pod person,  now you have a healing regen.

Point is  you may think the time does not culminate in getting really strong stuff....

But if you spend the time convincing the ai to turn off holodeck safeties. You get crusader armor and a sword. Or if you float in space long enough you get a
Pulse Pistol

**Comment by MonsWTF** [comment]
Perhaps it is a cultural thing I have yet to immerse myself in makes me not agree with the damage increase. 

I still really want to know where it's 22% and not 30%. I looked in the code under the slimes and that's literally what it tells me.

**Comment by 81Denton** [comment]
@DootLord Are you still working on this PR? If you need help, feel free to ask at the Coderbus Discord, or in #coding-general at the /tg/ Discord server.

**Comment by gueba14** [comment]
so sad that this never got tru, the xeno armblade now is an item no one likes because its so bad comapred to a plasma spear, that takes 15 seconds to do, and this takes a while
i think this should be reignited

**Comment by DootLord** [comment]
> so sad that this never got tru, the xeno armblade now is an item no one likes because its so bad comapred to a plasma spear, that takes 15 seconds to do, and this takes a while i think this should be reignited

I might re-visit it. Not played in years but your comment has me interested to check out the game again.

Lets not necro things this old though haha.

**Pull request closed without merging**
