### PR TITLE
Ban double negatives in contributing guidelines

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Bans double negatives, such as `if (!x) else`, and `!x ? y : z`. This is something I have been telling people for a while, but am just now getting around to codifying.

This often times makes code harder to read and understand, and doesn't provide much benefit.

@tgstation/commit-access

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
how do you feel about 
```
for(var/item in list)
    if(!thecase)
        continue
    other shit
```
Does it fall under this same sort of case?

**Comment by Mothblocks** [comment]
That's fine, I don't really read that as a double negative, especially since it's usually just sanity checks.

**Comment by spookydonut** [comment]
> 
> ## About The Pull Request
> 
> Bans double negatives, such as `if (!x) else`, and `!x ? y : z`. This is something I have been telling people for a while, but am just now getting around to codifying.
> 
> This often times makes code harder to read and understand, and doesn't provide much benefit.
> 
> @tgstation/commit-access

Disagree, early return logic should supersede this.

**Comment by LemonInTheDark** [comment]
Ah I fucked up, to clarify and I suppose restate things, would you be ok with
```
for(var/item in list)
    if(!thecase)
        somethings
        continue
    other shit
```
or
```
for(var/item in list)
    if(!thecase)
        somethings
    else
        other shit
```
is it just the syntax that you're going for here? or the logic behind the code

**Comment by stylemistake** [comment]
Add a paragraph about `? TRUE : FALSE`, which is very close in spirit.

**Comment by Mothblocks** [comment]
I think that's out of scope for what I'm trying to write here which is just about double negatives.

If you made a contributing guideline about that I'd +1 it though.

**Comment by Qustinnus** [comment]
this is ambigious with early returns, and should clarify when it is and isn't correct to do this, because it's something a new coder will probably not know like you do.

**Comment by Cyberboss** [comment]
This seems a bit superfluous

**Comment by Mothblocks** [comment]
That's fine then.

**Pull request closed without merging**
