### PR TITLE
Inhand sprites for whips

### LINKED ISSUE #32262: meat hook inhand needs a unique sprite
IS IT A CHAIN OF COMMAND OR A MEATHOOK???????????????

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Lizard tailwhip, cat tailwhip, and lavaland hook now have their own unique inhand sprites. Fixes minor chain of command inhand inconsistency. Closes #32262

H6XOpqW8iE
Chain of Command, Lizard Tailwhip, Cat Tailwhip, Meathook

## Why It's Good For The Game

To quote the 3 year old issue, "IS IT A CHAIN OF COMMAND OR A MEATHOOK???????????????"

## Changelog
:cl:
imageadd: lizard/cat tailwhip inhand sprites
imageadd: meathook inhand sprite
/:cl:

### CODE REVIEW

**Review by kriskog — APPROVED** [review]

**Comment by kriskog** [comment]
Nice

**Comment by Bawhoppen** [comment]
What about the curator's whip also?

**Comment by itseasytosee** [comment]
Based time to put those sheers to use

**Comment by carlarctg** [comment]
that nine tails whip looks really rad

**Comment by cacogen** [comment]
i never use these but i'll appreciate being killed with one more now

**Pull request merged**
