### PR TITLE
Add parallax sprites from RIS

### PR DESCRIPTION
**Pull request by astralloop**
https://github.com/Noober84555/RetardsInSpaceSS13/commit/940294cce891b7fb346ce20b29d03c6a474e1c21

:cl: Astral
imageadd: Space is now prettier
/:cl:

chronosdp

### CODE REVIEW

**Comment by optimumtact** [comment]
take a picture in /tg/station

**Comment by astralloop** [comment]
ok

**Comment by deathride58** [comment]
Take a picture in widescreen, too, so I know if I have to yell or not.

**Comment by astralloop** [comment]
@optimumtact done

**Comment by optimumtact** [comment]
it looks really nice

**Comment by Xhuis** [comment]
What does it look like near the station?

**Comment by Incoming5643** [comment]
does this break fake space tiles

also cursory "I subjectively like the retro look better" comment

**Comment by Iamgoofball** [comment]
I made fake space tiles use parallax.

**Comment by PKPenguin321** [comment]
space station 13 looks like THAT?

**Comment by ike709** [comment]
SS13 not looking like crap? Heresy.

**Comment by Cyberboss** [comment]
Can we get a small in-motion view of it please?

**Comment by MrDoomBringer** [comment]
@Cyberboss i assume it looks about the same as [this](https://www.youtube.com/watch?v=gOWanXIlSf0)

**Comment by epochayur** [comment]
god damn this looks good, maybe this system could be used for something like fancy planetary backgrounds on away missions ala terraria or something

**Comment by Bawhoppen** [comment]
Coooool

**Comment by MoreRobustThanYou** [comment]
@MrDoomBringer you'd be correct

**Comment by uraniummeltdown** [comment]
@MrDoomBringer Are you the OT Mod?

**Comment by MrStonedOne** [comment]
>I made fake space tiles use parallax.

bitch what I did that.

**Comment by Supermichael777** [comment]
It looks awful please revert. its too busy, classes with our art style and looks unrealistic
https://www.youtube.com/watch?v=lYmGoE-PDBY#t=203

**Comment by optimumtact** [comment]
no

**Comment by astralloop** [comment]
@Supermichael777 who said you had the right to say if the station was in/near a nebula/colored dust cloud or not

**Comment by Noober84555** [comment]
Thanks

**Comment by deranging** [comment]
noober wasn't notified of this until i showed this to him ⛳️ 🏌️

**Comment by WJohn** [comment]
While this is pretty, I think it's slightly overdone. Maybe I'm just nostalgic over the dark space color we had now, but it's very busy. I think the nebula feel could be toned down, as could either the number or size of stars as they *are* larger than they used to be.

**Comment by praisenarsie** [comment]
why wasn't this made a fucking preference, for fuck's sake

**Comment by deranging** [comment]
personally i prefer the original retards in space background over the new one

**Comment by praisenarsie** [comment]
ok but why wasn't this made a preference, i rather have old parallax

**Comment by deranging** [comment]
i like RIS's one more

**Comment by Noober84555** [comment]
I gotta agree with the tone down thing, It's a bit way too colorful. Could do with a bit of gray and a bit of lowering brightness.

**Pull request merged**
