### PR TITLE
paper scraps can't be worn on the head

### LINKED ISSUE #22240: paper scraps can be worn on your head, but they have no sprite
????????????????

see title

### PR DESCRIPTION
**Pull request by Mervill**
fixes #22240

### CODE REVIEW

**Comment by jughu** [comment]
>not making a unique sprite for this

**Comment by Mervill** [comment]
its trash

why

**Comment by jughu** [comment]
I am the thrashman

**Comment by ShadowDeath6** [comment]
> not being able to eat paper scraps

hmm

**Comment by Armhulen** [comment]
instead make it so you can crumple paper into balls and throw it at people/disposals as a cheeky hop, but when you unfold the ball it's the paper scrap

and fix the wearing on head so people don't have INVISIBLE STUN HATS

**Comment by Mervill** [comment]
If you throw paper it turns into a paper airplane

**Pull request merged**
