### PR TITLE
ninjas can now hijack the shuttle

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

ninjas can how hijack with the speed of 1

## Why It's Good For The Game

ninjas are a solo antag that focuses a lot on computers and sabotage, i see no reason to not let them sabotage the shuttle

## Changelog
:cl:
balance: ninjas can now hijack the shuttle
/:cl:
(i dont think hijack changes much other than where the shuttle lands and giving funny messages so i dont think it deserves balance? maintainer feel free to change this)

### CODE REVIEW

**Comment by IndieanaJones** [comment]
If you wanted this to be truly quality, the flavor text could be different and send you to a different location based on hijacker.

**Comment by MrDoomBringer** [comment]
xeno hijacking should crash it into the middle of centcom lul

**Comment by Mothblocks** [comment]
yeah this is balance

**Comment by Dorsisdwarf** [comment]
why would the xenos hijack the shuttle to go to syndie command instead of centcom

**Comment by necromanceranne** [comment]
> why would the xenos hijack the shuttle to go to syndie command instead of centcom

They're not very good pilots.

**Comment by nianjiilical** [comment]
xeno hijack should crash it into centcom and autospawn a ton of npc/monkeybrain human interns for them to eat

**Comment by optimumtact** [comment]
How is an xeno supposed to hijack a shuttle? They don't appear to use computers.

**Comment by MrDoomBringer** [comment]
> How is an xeno supposed to hijack a shuttle? They don't appear to use computers.

if a xeno can operate an elevator then a xeno can meet's nanotrasen's 4th-grade-reading-level shuttle pilot requirements

**Comment by optimumtact** [comment]
I don't agree with this merge

**Pull request merged**
