### PR TITLE
Adds Custom Vending machines to cargo and chemistry, arrivals and departures 

### PR DESCRIPTION
**Pull request by Capsandi**
## About The Pull Request

Adds crew operated vending machines at arrivals, departures, cargo and chemistry.

## Why It's Good For The Game
Cargo can now make cash off of keeping their vending machine stocked with auto-lathe goodies, and medical can now charge for "luxury" drugs, or if you _want_ to be lynched, the cure for the virus epidemic that you **might** have caused. The communist public chem fridge has been booted in favor of the capitalist vending machine, but if you are feeling kind you can still give pills away for free in the vendor. Two more have been added to the high traffic areas of arrivals and departures for assistants to operate.
I don't doubt these will be used more frequently than their brand name brethren. This will add to the importance of caring about your account balance, which, for most jobs, doesn't really matter much right now.
## Changelog
:cl:
add: Added crew operated vending machines at arrivals, departures, cargo and chemistry
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Merge conflict

**Comment by AdmiralPancakes1** [comment]
Do custom vending machines let you dump chem bags into them?

**Comment by Mickyan** [comment]
Something went wrong

Seems odd not to put it outside the commissary considering that's what it's there for, arrivals and departures are anything but high traffic areas

**Comment by Capsandi** [comment]
closing this because i accidentally deleted all my changes, better to start from a blank slate

**Pull request closed without merging**
