### PR TITLE
adds the cringe weaver

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

Fx-Izb9XwAA9cLE

Cringe Weaver! For when they ask for a Lorem ipsum..........
It's a shitpost drink with a recipe based on the pun that it's made with six parts 'form'aldehyde, three parts fringe weaver, and one parts ice. Being made of formaldehyde, it's also a yummy drink that heals the same rate as quadsec, but for coroners! Everyone else thinks it's kinda icky though...
## Why It's Good For The Game

Sin_titulo
## Changelog
:cl:
add: cringe weaver
image: cringe weaver
/:cl:

### CODE REVIEW

**Comment by zeroisthebiggay** [comment]
wtf did i do to `pod_tesla`

**Comment by mikederkan** [comment]
do we need a drink based off of a meme from a game? we already have a few valhalla drinks 

(also please show the sprite in game)

**Comment by zeroisthebiggay** [comment]
> do we need a drink based off of a meme from a game? we already have a few valhalla drinks

i think this is the funniest shit tangible to the human mind
also 'form'aldehyde joke funny

> (also please show the sprite in game)

image

**Comment by zeroisthebiggay** [comment]
brhu

modified sprite

**Comment by EricZilla** [comment]
Since its made with formaldehyde it should have an effect when drank by coroners

**Review by Wallemations — CHANGES_REQUESTED** [review]
image

I doubt you meant to swap that second sprite

Also why does your sprite have a `(0)` in it??

**Comment by zeroisthebiggay** [comment]
> Since its made with formaldehyde it should have an effect when drank by coroners

i could make it not disgust you and heal brute damage that sounds funny

> I doubt you meant to swap that second sprite

correct. i didn't. i'll try and fix it again but the first time i did it didn't seem to work

> Also why does your sprite have a `(0)` in it??

that's an excellent question

**Comment by zeroisthebiggay** [comment]
@Wallemations yeah i literally don't know what is wrong with the dmi i just tried downloading the tesla pod from master and replacing it but it's not registering a change. idk what's causing the `(0)` either

anyways i've made the drink heal coroners and disgust everyone else so it's a little bit more flavorful than just a shitpost since it's made with formaldehyde and may practically benefit coroners as a drink they can make fairly easily with their formaldehyde while also healing them

the mixture is optimized in a way that one bar of silver will make you a hundred units of cringe weaver

**Comment by Wallemations** [comment]
fix your merge conflict
The bot had a bug that should be fixed now too, so once you fix the conflict it should re-run the bot

**Review by Wallemations — APPROVED** [review]
As much as I don't find the joke funny, my job is to make sure sprites look good not make sure PRs are humorous, and the sprite looks pretty good so

**Pull request closed without merging**
