### PR TITLE
Adds "Firing Pins" category to protolathe.

### PR DESCRIPTION
**Pull request by bear1ake**

### CODE REVIEW

**Comment by hornygranny** [comment]
i recommend you make changes on branches rather than your master

**Comment by bear1ake** [comment]
"i recommend you make changes on branches rather than your master"
And name branch like "protolathe-fix?"

**Comment by RemieRichards** [comment]
@bear1ake Anything that you can recognise as the change you want to make, in this case ```protolathe-fix``` would work yes.

**Comment by JJRcop** [comment]
You could even name it "pugglebuttmcstupid" if you wanted to, as long as you remember what it does.

**Comment by RemieRichards** [comment]
ignore JJ he's silly.

**Comment by JJRcop** [comment]
Remi just doesn't have a good taste in branch names, ignore her she's untasteful

**Comment by RemieRichards** [comment]
I have the best taste.

**Pull request closed without merging**
