### PR TITLE
Removes LSD sting

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
In my doomed quest to make changeling tolerable, I'm removing something I think has little actual utility or benefit for the changeling, but is still massively obnoxious for people to deal with.

But if a bunch of people show up to say they love LSD sting I'll close this

### CODE REVIEW

**Comment by Cuboos** [comment]
I WILL ONLY ACCEPT THIS IF PARA STING REPLACES IT

**Comment by Cheridan** [comment]
tbh i was going to do this in my big changeling update but back then intigracy said he liked it and not to take it out and this was before i knew he was kind of a jerk so i listened to him

so :+1:

**Comment by Shapsy** [comment]
Watching people run around and scream about the singularity being loose and then fall on their face or about how there are xenos is pretty funny, I'd be sad to see it go since there's so few ways to make people hallucinate.

**Comment by Buggy123** [comment]
IMO just leave it, it's a fun and potentially useful feature.

**Comment by KorPhaeron** [comment]
It is bloat that gives people an unpleasant experience for no direct benefit to the ling

**Comment by TheNightingale** [comment]
That's exactly why I like it. It doesn't take people out of the round, but it antagonises them. What more could you want?

**Comment by Buggy123** [comment]
Dying is a unpleasant experience and lings have plenty of ways to cause that, and it does have benefit: If you're constantly getting mauled by aliens or knocked down by singulos, you're probably a bit less likely to scream about a changling "killing" you until it's too late.

**Comment by Fox-McCloud** [comment]
:-1: 

Not to keen on this, @KorPhaeron 

While it's moderately annoying to get stung, this is usually used, from what I've seen, by changelings who aren't really too keen on murdering the entire crew, but want to still have a little fun by making them scream about Xenos/the singularity/etc.

**Comment by Zilenan91** [comment]
In my experience this thing is kind of like a parasting lite depending on how often the KO rolls for it.

**Comment by KazeEspada** [comment]
Kor, Zile agrees with you. Just close it. To much hugbox.

**Comment by Cuboos** [comment]
serious post, i've used LSD sting several times as a distraction. LSD-sting a guy a couple times and they're going to be far too panicked to remember who was nearest when they started hallucinating.

**Comment by Buggy123** [comment]
Cuboos multiple stings don't have much of a effect, each sting set's a victim's hallucination to a certain value and stinging again only increases it back up to that value.

**Comment by Cuboos** [comment]
really? because i swear it stacks. i've had ling rounds where i was tripping so hard it was nothing but a constant spam of "i'm heeeeaar", "loook up" and random assistants beating the shit out of me literally without pause.

**Comment by ChangelingRain** [comment]
that's because it sets your hallucination to 400 if it's below that

**Comment by Iamgoofball** [comment]
niknak please post so that I can spam downvotes on you too

**Comment by Core0verload** [comment]
:-1: I like LSD stings. Ling is not just about armblade combat. It has a lot of stealth, distraction and panic-causing tools, and LSD sting is one of them.

**Comment by Archie700** [comment]
Where's the fun removal tag when you need it

**Comment by KorPhaeron** [comment]
rip

**Comment by Cuboos** [comment]
Long Live LSD-string

**Comment by Durkel** [comment]
Nothing more fun then sitting in medical waiting for a variable you have no control over to wear off, Really adds to paranoia when you see that singulo/xeno for the ninth time too. At least we can take comfort that if you're unable to do anything constructive as a changeling you spam this shit and make people miserable without trying.

**Comment by Cuboos** [comment]
There are chemicals that remove hallucination
.

**Pull request closed without merging**
