### PR TITLE
Standard and engineering module tweaks

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Added metal rods and floor tiles to Standard cyborgs.
add: Added a remote signaling device to Engineering cyborg.
/:cl:

- I also broke up the list of modules so now it's a single line per
module, which makes it a little more readable and inline with other
large lists that exist in the codebase. This is why there are so many
line changes.

### CODE REVIEW

**Comment by Armhulen** [comment]
:+1: for rods and tiles

:-1: :-1: :-1: for remote signalling device

**Comment by FantasticFwoosh** [comment]
Make sure they can't lose it putting it inside a object accidentally or materialize more out of battery power.

**Comment by Anonmare** [comment]
I presume the signaller is for anomalies

**Comment by Armhulen** [comment]
and i presume that it'll be used for detonating bombs for mister scientist

engiborg is actually the last borg that needs buffs

**Comment by KorPhaeron** [comment]
What can the borg even signal though without the ability to put signallers in things?

Pretty much just TTVs right?

**Comment by Anonmare** [comment]
I remember one traitor subverting me as a borg and had me drag a locker full of voice-activated bombs to the Emergency shuttle.

It's really more a method of making a borg suicide bomb someone really, or have them be a dead man's trigger

**Comment by GunHog** [comment]
Which can much more reliably be done with a pAI, which will not turn on you unless emp'ed.

**Comment by Anonmare** [comment]
Honestly you could probably add it to every borg module without much danger, it doesn't really fall into a specific category for use

**Pull request merged**
