### PR TITLE
Makes xenobio consoles and stock exchange computers buildable

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Xenobiology consoles are now buildable from circuitboards in R&D. They'll be limited to the area they're built in plus any area with the same name.
add: Stock Exchange computers are now also buildable this way.
/:cl:

Reason for the PR: Xenobiology needs this tool to be able to achieve its goals within a normal round duration, and if they get destroyed/emped they're currently irreplaceable.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
do you mind putting that under the research boards section? Computer boards is cluttered af.

Also, you'd be my hero if you could also add Stock Machines :)

**Comment by XDTM** [comment]
The computer boards are cluttered because every board is in there, putting it elsewhere wouldnt be consistent.
Also sure i'll add r&d stock exchange when i get home.

**Comment by AnturK** [comment]
This smells like a feature.

**Comment by XDTM** [comment]
There you go @ExcessiveUseOfCobblestone

**Comment by ChangelingRain** [comment]
this looks like a feature

**Comment by XDTM** [comment]
i admit it, it's a feature

**Comment by ChangelingRain** [comment]
You need to put the feature down.
There aren't any features in winter.

**Comment by XDTM** [comment]
I hope i remember to reopen this post freeze then

**Pull request merged**
