### PR TITLE
fixes infinite fake snow generation

### PR DESCRIPTION
**Pull request by ShizCalev**
:cl: ShizCalev
fix: Fixed an item duplication bug involving snow tiles.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Should this be a define?

**Comment by ShizCalev** [comment]
> Should this be a define?

?

**Comment by ShizCalev** [comment]
> Should this be a define?

this number is the amount of the stack the element drops when dug up
it only takes 1 tile to make the floor, as with any other kind of plating.

not sure what define you're talking about

**Comment by MrMelbert** [comment]
Oh, I just realized it drops snow tiles and not snow. Disregard

**Pull request merged**
