### PR TITLE
Repathed all the map templates to use the proper floor types.

### PR DESCRIPTION
**Pull request by xxalpha**
All away missions, shuttles, space ruins, lavaland ruins.

No new floor types were created (wow!).

All templates converted to TGM.

This PR finishes the repathing of floors in all the maps. When this PR is merged, the code will be ready for a refactor of floor code to be mindful of floor types instead of juggling icon states.
--

@Aranclanos would be proud right now, I think.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
think you fucked up bro

**Comment by Jalleo** [comment]
What about asteroid?

**Comment by xxalpha** [comment]
Already done.

**Comment by optimumtact** [comment]
Did you check they compiled?

**Comment by xxalpha** [comment]
Nope.

**Comment by xxalpha** [comment]
Compile log:
http://pastebin.com/raw/24trfhPG

Errors on a few maps, but unrelated to this PR. A handful of maps were not compiled due to several errors with the map files unrelated to this PR and I unticked them to compile everything.

All map errors are unrelated to this PR and will need to be fixed later if those maps are to be used.

**Comment by Iamgoofball** [comment]
attn: please dont smoothwall the walls on the goon shuttle, they are intentionally manually smoothed for detailing purposes

**Comment by xxalpha** [comment]
Any other unrelated comments?

**Comment by Iamgoofball** [comment]
i wasn't certain if you did smoothwalling on shuttles that were manuallysmoothed for the purpose of continuity, no need to be an asshole about it

**Comment by xxalpha** [comment]
This is a floor PR, it's in the title and description.

**Comment by Iamgoofball** [comment]
alright

**Pull request merged**
