### PR TITLE
Makes people of ash more tribal

### PR DESCRIPTION
**Pull request by Razharas**
:cl: Razharas
add: Theres now a bone pickaxe and a crafting recipe for it
tweak: Replaces some of the people of ash stuff with bone variants of said stuff
tweak: Makes people of ash only able to craft tribal shit
tweak: Makes people of ash not able to use machinery
tweak: Makes people of ash have their own language
/:cl:

Makes people of ash only able to craft tribal shit

### CODE REVIEW

**Comment by KorPhaeron** [comment]
So they can't make spears anymore?

**Comment by Razharas** [comment]
You need cables to make spears, they dont have access to cables anyway

**Comment by Kraseo** [comment]
And why wouldn't they be able to even make soup?

**Comment by Razharas** [comment]
Well food can be added too
I mean mostly restricting them in fields like machine building and other stuff that feels out of place and is never accessible to them anyway

**Comment by KorPhaeron** [comment]
Machine building does not currently use the crafting system anyway

**Comment by ChangelingRain** [comment]
If the ashlizards get transformed to another species or mindswapped they'll suddenly be able to craft this stuff. I think that's dumb, and you should fix it.

**Comment by Razharas** [comment]
Why would ash not be able to craft stuff if he is forcefully evolved into a superior being such as human

**Comment by Razharas** [comment]
Also swapping minds with someone who took braindamage keeps the braindamage, so i think its fair that in the new stupid body you cant thinks as comprehensively as before

**Comment by Supermichael777** [comment]
UNGA BUNGA

**Comment by Militaires** [comment]
10/10 always nerf liggers.

**Comment by ExcessiveUseOfCobblestone** [comment]
They get a RCD though, so it's not like they're completely unaware of "technology". I'm not sure why a tribal lizard would be unaware of how to create say a spear made from BIG METAL THINGY with BIG SHARP THINGY or some of the other primal weapons that aren't really exclusive to the tribal category, yet can manipulate a device made for replicating/destroying walls,airlocks,floors, and grilles.

**Comment by Razharas** [comment]
Creating something from scratch is much harder that using something
You dont need to understand how RCD works to push one of its two buttons

**Comment by Ergovisavi** [comment]
Honestly I don't even know why they get an RCD or a disk to upgrade the AI. They're cavemen.

Like I get it from a gameplay perspective but from a logic/immersion perspective it's so fucking weird

**Comment by Razharas** [comment]
Ill fix all the immersions in this pr dont you worry

**Comment by KorPhaeron** [comment]
@Ergovisavi 

Den was meant to look like a pile of random stolen crap they'd scavenged

**Comment by Incoming5643** [comment]
Don't call them "ashliggers" in changelog messages (or pull titles for that matter). We can't canonize a term that's taken from a racial slur.

**Comment by PKPenguin321** [comment]
It's not really canonized if its just in the cl

**Comment by Incoming5643** [comment]
Downstreams who don't use the term will see it. Anyone who might ever research the game down the round could see it. That's bad enough to me.

**Comment by FantasticFwoosh** [comment]
I have a few other thought suggestions on ashwalkers if you'd like to hear them, PM me on the forums.

Im not a fan on the tribal crafting being so restrictive to that race, could lead to people (for whatever reason) meta brain transplanting themselves into ashwalkers (technically its a plus, get heat gene and space resistant nobreathe, then cut off your legs for metal ones) just to use a array of tools with easily accessible miner materials (that aren't terribly strong but axes are always useful)

Very personally i like collecting bone objects as RD, to fufill my 'museum' and archeological fantasies by showcasing them around but that's just me, it'd be content going down the drain on a throwaway species that wont even survive long enough to use them because of different things (bad ruin placement = miner powercreep & loot = bosses = poor player co-operation)

**Comment by TechnoAlchemisto** [comment]
can't they still craft regular spears with slapcrafting

**Comment by AdamElTablawy** [comment]
Make them unable to use computers and vendors too. Ashwalkers using tablet laptops and security cameras breaks muh immershin.

**Comment by PKPenguin321** [comment]
@FantasticFwoosh

You can still craft tribal items as a non ashwalker

**Comment by KorPhaeron** [comment]
@adameltablawy

May as well make them simple animals if you restrict them from doing anything but hitting stuff.

**Comment by KorPhaeron** [comment]
It's admittedly rare, but I have had a couple rounds where ash walkers took over the golem ship and mined, did botany with pod people, or got recruited into station nonsense (working in cargo, cultists, gangsters) and limiting situations like that for dubious benefit seems like a bad idea.

Hard limits in what players can do are in general are pretty antithetical to ss13

**Comment by AdamElTablawy** [comment]
i mean true, kor, but on the other hand they're literally primitive unga bunga lizards who kill people for their god

why do they know how to use advanced machinery

like sure, a computer saying LAUNCH SHUTTLE is one thing

doing R&D is...another

**Comment by Razharas** [comment]
Im pretty sure all ghost-spawn mobs have some kind of restrictions on them, be it station spawn stuff and their obedience to creator, drones or swarmers or spiders all of which cant possibly become equal members of the crew
Ashers on the other hand can fit perfectly like a glove despite lore-wise never even seeing humans before and never having any kind of tech
There are possibilities for roleplay in freedom but there are also possibilities for roleplay in lack of freedom, like ashers could totally become friendly to station but they just wont be equal members of crew due to their lack of mental capacity to grasp some tech stuff
I think its more appropriate than them being literally just lizards who for some reason spawned in the lavaland and not on station at roundstart

**Comment by AdamElTablawy** [comment]
i mean, a bunch of braindead idiot lizards mindlessly beating people to death for trespassing?

they'd fit right in with security IMO

**Comment by KorPhaeron** [comment]
I really don't think limiting their communication will make the more fun either. Ashwalker vs Miner negotiations usually break down, but they're tense and memorable when you pull it off.

**Comment by Yiu113** [comment]
@KorPhaeron I don't know, tense negotiations via interpretive dance seems like the best kind of tense negotiations.

**Pull request closed without merging**
