### PR TITLE
Adds a new toy to the arcade machine

### PR DESCRIPTION
**Pull request by Sometinyprick**
Adds a pig mask to the arcade machines which changes your speech to pigspeak, can be turned on
and off.

### CODE REVIEW

**Comment by WJohn** [comment]
:+1:

Should also have a horsemask changes your speech a lot like wizard horse masks.

**Comment by Chocobro** [comment]
inb4 its first live use is erp
:+1:

**Comment by WJohn** [comment]
oink~

**Comment by PKPenguin321** [comment]
Could add this to wizard's curse spell
Change it's name from horseman curse to just animal head curse or just curse
A station of pigs and horses
merge it

**Comment by Alek2ander** [comment]
And chickens.

**Comment by Thunder12345** [comment]
Do a cow mask too and call it Curse of the Farmyard

**Comment by babinsquared** [comment]
Old Macdonald's Curse. Add some backstory about him actually being a wizard with questionable habits.

But anyway :thumbsup: for this.

**Pull request merged**
