### PR TITLE
Gives Mechs Various Levels of Rad Protection

### PR DESCRIPTION
**Pull request by FloranOtten**
## About The Pull Request
Gives mechs rad protection.

## Why It's Good For The Game
Mechs are giant hunks of metal. Makes sense they'd block some rads.  

## Changelog
:cl:
tweak: Gives mechs radproofing
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
why

**Comment by MrDoomBringer** [comment]
it'd be cooler if you could outfit the mech with lead plates or something at the cost of a very slight movement delay

**Comment by Tlaltecuhtli** [comment]
i think an equipment slot would be enough of a price for something so useless

**Comment by FloranOtten** [comment]
This would make the old 'irradiated shoebox' anti mech strategy less valid, and makes using a mech to guard a delamming SM less suicide.

**Comment by necromanceranne** [comment]
It also makes the Elephants Foot Mech strategy more useable for pilots other than plasmamen. Fair warning. That shit fucking busted as hell.

**Comment by MegaEmpirical** [comment]
If a little metal was all it took then the station would be fine. An equipment makes sense though.

**Comment by DapperMola** [comment]
> It also makes the Elephants Foot Mech strategy more useable for pilots other than plasmamen. 

Please, indulge me.

**Comment by necromanceranne** [comment]
Get rad suit. Get 400 or so micro manipulators irradiated in a bluespace RPED you left cooking in the SM. You now have a cancer aura. Nothing living that isn't a plasmaman or golem can approach without contracting horrific radiation poisoning. You basically must send a borg. And borgs can't reasonably fight mechs under asimov since critical effects can cause human harm. (Though it is a slight grey area so mostly best not to toy with it)

**Comment by ExcessiveUseOfCobblestone** [comment]
no one has patched that yet I see

**Comment by FloranOtten** [comment]
> no one has patched that yet I see

Noone wants to try and redo the rad system

**Comment by Tlaltecuhtli** [comment]
make tiny items not affected by rads ¯\_(ツ)_/¯

**Comment by necromanceranne** [comment]
The alternative is of course just irradiating your radsuit by sitting in next to the SM for a while under a holofan. So long as you put up the fan before the SM was started you should be fine.

**Review by SpaceManiac — APPROVED** [review]
Seems fine to me

**Pull request merged**
