### PR TITLE
ghost of poly cannot be shuttle gibbed [Dependent on #81726]

### PR DESCRIPTION
**Pull request by deathrobotpunch**
## About The Pull Request

this PR makes ghost of poly truly immortal by removing the only way they can be killed.

also requires #81726 to function 
## Why It's Good For The Game

YOU CANNOT SILENCE THE PROPHET

also ghost poly is incorporeal so it makes sense

## Changelog
:cl:
add: the ghost of poly has now learned how to phase through shuttles and cannot be crushed
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
@Absolucy is the trait being used correctly?

**Comment by Absolucy** [comment]
@deathrobotpunch no, it's a trait, not a bitflag

**Comment by deathrobotpunch** [comment]
> @deathrobotpunch no, it's a trait, not a bitflag



> @deathrobotpunch no, it's a trait, not a bitflag

how would you apply the trait then?

**Comment by JohnFulpWillard** [comment]
Can revenants be shuttlegibbed? Wouldn't it be better to make all ghost mobs immune to shuttlegibbing than having to individually give this trait?

**Comment by deathrobotpunch** [comment]
> Can revenants be shuttlegibbed? Wouldn't it be better to make all ghost mobs immune to shuttlegibbing than having to individually give this trait?

I could do that but I’m going to have to figure out how to apply the trait first

**Comment by Absolucy** [comment]
@deathrobotpunch https://github.com/tgstation/tgstation/pull/81726/files#diff-2727ff987ddcf1798fb60217139a25f56949abfd9592328de3b7600e9226873eR52-R55

**Comment by deathrobotpunch** [comment]
> @deathrobotpunch https://github.com/tgstation/tgstation/pull/81726/files#diff-2727ff987ddcf1798fb60217139a25f56949abfd9592328de3b7600e9226873eR52-R55

I assume I just insert that in the place of the bitflag?

**Comment by SyncIt21** [comment]
Just draft this PR till https://github.com/tgstation/tgstation/pull/81726 gets merged. Don't put DNM in the title as it has nothing to do with the intent of your PR

**Pull request closed without merging**
