### PR TITLE
Relocates the mining shuttle so it stops spamming errors and trapping people on lavaland if the whiteship lands.

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

As title, makes a dedicated dock on meta, box, and delta.

I tried something a bit radical for meta that people are probably going to hate.
image

## Why It's Good For The Game

This is annoying
Intent of the meta lobby redesign is to get more people using the shuttle because it will be less out of the way.

## Changelog
:cl:
add: The public mining shuttle now has a dedicated dock on Box, Delta, and Meta.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Screenshots pl0x

**Comment by kriskog** [comment]
Metastation assistant buff, fewer spawn points far away from tool storage gloves :smirk:

**Comment by actioninja** [comment]
They spawn in the shitter instead.

**Comment by TheVekter** [comment]
I'm... not certain I like the idea of removing that little lounge space. True, it doesn't get used much, but it's been there for ages and I like how it looks.

That being said, this is still a positive change.

**Comment by necromanceranne** [comment]
I fucking love it, nice.

**Comment by ArcaneMusic** [comment]
Yeah but where will a build a toll booth to demand my troll toll off of latejoiners?

**Comment by Iatots** [comment]
You could have easily stuck it somewhere on the left side of the glass corridors.

**Comment by kriskog** [comment]
But that wouldnt be very radical

**Comment by Tlaltecuhtli** [comment]
i liked that room tho

**Comment by ninjanomnom** [comment]
Docks don't have to be on space you know, if you want to make that an internal area with air and everything you can have the public mining shuttle land in a sealed bay inside the station.

**Comment by RaveRadbury** [comment]
> Docks don't have to be on space you know, if you want to make that an internal area with air and everything you can have the public mining shuttle land in a sealed bay inside the station.

Doesn't it already do that in the aux base room after the base has been launched?

**Comment by ninjanomnom** [comment]
Yeah that's how the aux base works, so far I think I'm the only one who's touched on that particular feature though which is why I'm ~~shilling~~ reminding people it exists.

**Comment by Potato-Masher** [comment]
I mean its a good change but uh, the placement is a bit too radical almost. You can't just take away the lounge area like that. Then again I have no real idea where the shuttle would fit otherwise.

**Comment by Farquaar** [comment]
I love that little lounge. Don't get rid of my precious lounge.

**Comment by MCterra10** [comment]
Kinda needs the double airlocks

**Comment by wesoda25** [comment]
If you're going to use single airlock make it a pressurized room. 

But why not use the left portion of the glass corridor, as others said?

**Comment by 81Denton** [comment]
I can't see the shuttle computer on Metastation, is that a mapdiffbot issue? Also, either double airlocks or a pressurized docking bay for the shuttle would be great since arrivals will be depressurized all the time otherwise.

**Comment by Fikou** [comment]
put the mining shuttle on the crate island north of arrivals in maint instead

**Comment by RaveRadbury** [comment]
The aux hangar already solves this, it's a shame that something like this might have to go through because no one drops the aux base.

**Comment by Learner10** [comment]
> 
> 
> put the mining shuttle on the crate island north of arrivals in maint instead

Awful idea. I'd have to destroy the shuttle just to do my projects on the one partially started area of the station.

**Comment by actioninja** [comment]
god dammit

**Comment by actioninja** [comment]
that was the easiest map conflict resolution ever

**Review by kriskog — COMMENTED** [review]
Looks like there is a wall missing in bathroom
image

Not a huge fan of the side tables in customs office, they seem unnecessary. In addition, breaking in only requires deconstructing the shuttle computer which also inconveniences anyone wishing to use it.  
If you end up keeping the computer where it currently is, it should have a firelock.

**Comment by actioninja** [comment]
good catch on the missing wall. Ended up just moving the tables back to the way they were, considering that the whole reason I moved them was I was originally going to move the console in sec. Added a firelock and a reinforced dir window.

**Comment by kriskog** [comment]
Lets give it a go

**Comment by Twaticus** [comment]
yall need a fuckin aesthetic adviser or something because this is ugly as sin. good concept bad bad bad delivery

**Comment by necromanceranne** [comment]
I'm not too fond of what's happened to the vacant office but tbh tg's aesthetics need more than minor tweaks it needs a fairly major overhaul, and for now it's better functionality because fuck the awkward bullshit you had to put up with because the public dock was used by both the shuttle and the white ship.

Also, was there much stopping anyone from just making the maint tunnel running up along the auxbase just another extention of the main station and put the public dock at the end of that?

Bit late now I suppose but ah well.

**Pull request merged**
