### PR TITLE
fucking murders toolbox sprites

### PR DESCRIPTION
**Pull request by plapatin**
## About The Pull Request
take a wild guess
heres a picture of the toolboxes in case you forgot
image
i didnt change the gold toolbox sprite because i can't even find where it's used, latch code is gone but the defines and sprites are still there
travis is a liar dont listen to him, everything worked fine when i tested it

## Why It's Good For The Game
theres a metric fuckload of discussion about why isometric sprites look awful on the forums
this is my favorite thread regarding such discussion
https://tgstation13.org/phpBB/viewtopic.php?f=2&t=9798
if you dont feel like reading the highlights are:
it's awful at showing depth
its more important to show what a sprite looks like in 3d space than how it might logically look from a specific viewpoint
the old style of sprites works in pretty much any direction, but 3/4 sprites really only work when they face south
creating a new visual style puts us at odds for every single codebase besides goon and colonial marines, along with making sure that we can't port sprites from other codebases
SOUL vs SOULLESS

## Changelog
:cl:
balance: the old toolbox sprites are back
/:cl:

### CODE REVIEW

**Comment by plapatin** [comment]
fuck

**Comment by tralezab** [comment]
why remove the latches?

**Comment by plapatin** [comment]
in all honesty i just didnt want to make new sprites for the latches

**Comment by actioninja** [comment]
these sprites look like trash.

**Comment by optimumtact** [comment]
just no

**Comment by HomocidlePancakes** [comment]
We all already know that this won’t be merged, but in case it does, ancient toolbox will need a new sprite.

**Comment by HomocidlePancakes** [comment]
Ohwow. Closed as I was writing

**Comment by plapatin** [comment]
@optimumtact but why

**Comment by subject217** [comment]
lol

**Pull request closed without merging**
