### PR TITLE
HoS gun ion mode replaces taser mode

### PR DESCRIPTION
**Pull request by 4dplanner**
## About The Pull Request
Makes the HoS gun a more VERSATILE weapon, with modes of fire for every eventuality

## Why It's Good For The Game
HoS gun keeping taser is weird given that it has been removed from all other weapons. I believe this will make the multiphase gun the versatile weapon it always should have been.

## Changelog
:cl:
balance: HoS gun has ion mode to replace taser mode, which fires weak ion bolts (ion bolts with 0 heavy and light range)
tweak: HoS gun now cycles disabler -> laser -> ion
fix: spiral_range properly includes turf contents if dist = 0
fix: weak ion bolts are no longer stronger than strong ion bolts
/:cl:

**cobby edit**: removed
**cobby edit2**: The naksu pr affects more guns than just revolver so I removed `closed PRnum`

### CODE REVIEW

**Comment by bigfatbananacyclops** [comment]
would definitely need more IQ play i like it, but, does the ion explode into a EMP blast like the rifle once it hits a object or wall?

**Comment by zxaber** [comment]
Big nerf to the prosthetic limb trait.

**Comment by wesoda25** [comment]
This is the sec buff I never knew I wanted, time to start playing HOS again.

**Comment by WJohn** [comment]
This is actually totally cool. Shutting down someone who uses energy/charge weapons with this, and being able to handle cyborgs with it... I like it!

**Comment by nemvar** [comment]
Might want to make the HOS gun EMP proof, maybe only when in ion mode.

**Comment by OverlyGeneric** [comment]
rip all friendly borgs.

**Comment by Shadowflame909** [comment]
May want to change the color to make it more different from a disabler.

At least I believe the gun has different colors when set to different modes.

**Comment by actioninja** [comment]
I considered removing it but this is a lot better of an idea. (also I only questioned why I left it in after getting memed by imsxz in a free drone using it and didn't want to ided PR)

**Comment by ShizCalev** [comment]
yeah that's not even slightly a feature addition, this is a straight up balance change my dude.

**Comment by Repukan** [comment]
Make it ion proof

**Comment by Teepeepee** [comment]
ironically, this will make HoS gun better at fighting energy-based weapons like the ones security uses
I'm not really against it but maybe you should consider making it use more ammo on ion mode or something

**Comment by Shadowflame909** [comment]
If this gets it merged, it could just be a one bolt Ion Gun. As in it Ions itself thus making it only useful for one shot before having to recharge.

Unintended Consequence turned into a feature for balance.

**Comment by anconfuzedrock** [comment]
actually my new favorite pr of all time, very simple, fixes absurd inconsistency with a creative and extremely logical solution that doesn't feel rushed.

**Comment by 4dplanner** [comment]
I've thought about it a bit, and I'm not sure it needs to be emp resistant because you can just not fire it at melee range. Being EMP resistant would be an unnecessary increase in power. Perhaps if it turns out to be an issue it could be changed in a future PR.

Anyway, this is probably going to be made obsolete by #44223.

**Comment by PKPenguin321** [comment]
Stealth buff in a huge way

**Comment by Shapsy** [comment]
Can't EMP's perma fuck the battery on guns and permanently lower their capacity

**Comment by necromanceranne** [comment]
I nab this often to validhunt/murderbone. It is THE gun to acquire for the taser. But I also would get an ion if I could to switch off headsets or turn of enemy lasguns. And of course, kill borgs. This is significantly better even if it isn't as bullshit as being tased out of the blue.

**Comment by anconfuzedrock** [comment]
We really shouldn’t be making balance decisions around the idea of traitors having a super easy time killing the HOS and using his stuff, we should be making balance decisions to stop that happening.

**Comment by habader** [comment]
if you use taser mode you're barely even a real person

**Comment by WJohn** [comment]
Now, mind you, ion weapons have their own host of problems, like permanently locking borgs down which is just GG for them, fucking with cells possibly permanently damaging them, causing who knows how many wires to toggle when hitting a door and so on and so forth. That's more due to ions in general needing a bit of a rework to be more consistent, but I'll take ion shots from the HoS's gun over being one of the few remaining sources of tasers.

**Comment by AdamElTablawy** [comment]
Ion weapons are pretty consistently extremely powerful as even though they don't do direct damage, they shut down and disable the usual suspect of weapons you can expect to get killed by, as well as cyborgs, break machines, etc. Serious nerf to borgs, mechs, pretty much immediately lets the HoS win a firefight if the guy has no ballistics. 

Giving the HoS what amounts to a roundstart ion carbine might not be a fantastic idea, considering the ion rifle is balanced around being very bulky and the ion carbine is adv weapons tech specifically because it's so useful.

Considering you can counter stuns and stamina damage and burn damage, but you can't actually counter ion attacks except for avoiding getting hit by them, i'd suggest lowering the amount of ion bolts the HoS' gun can fire.

You can shrug off a tazer with stun resists, shrug off burn damage with medicines, shrug off stamina damage with stun resists, you _can't_ shrug off an ion blast. Permanently lowering the capacity of your guns and draining all their energy as well as pretty much immediately killing anyone with cybernetics, nanites, cyborgs, and turning off their radio/blinding them-all of these are pretty damn powerful.

Personally i'd much rather fight a traitor with the HoS' tazer since I can at least attempt to avoid the electrodes-since ions are AoE, even if I dodge, unless it entirely misses the blast will disable most of my weapons.

**Comment by ShizCalev** [comment]
keep in mind ion bolts will stun & hurt people with prosthetic limbs when they're cause in it's emp pulse too.

**Comment by AdamElTablawy** [comment]
if they picked the prosthetic trait that’s their own choice, and if they lost a limb and got a replacement prosthetic instead of their actual limb that is on them as well

**Comment by Shadowflame909** [comment]
Yeah, not a downside. That nerf wasn't really that bothersome. Now they have a rare reason because this gun is almost never taken out unless all the other options for the HoS are exhausted, to not take that downside so freely.

It could also be a downside for the HoS if one of his allies has the trait and he wants to avoid friendly fire. As Ion Bolts are AOE.

**Comment by AdamElTablawy** [comment]
I can't imagine a HoS caring about friendly fire or his allies as anything other than meatshields, so the above doesn't really apply.

**Comment by anconfuzedrock** [comment]
HOS being able to ion himself and his friends is a perfectly good downside.

**Comment by 4dplanner** [comment]
> i'd suggest lowering the amount of ion bolts the HoS' gun can fire.

good call, will do this

**Comment by 4dplanner** [comment]
Number of ion shots the gun can fire is down to 4. I do agree this'll be strong, but I don't think it'll be overbearingly so - you can counter EMPs by using ballistic weapons or stunbatons. Further, you can actually dodge them quite easily, since an ion bolt will keep travelling until it hits a wall and only has a small 3x3 aoe. Unless you're standing right next to the wall, the aoe won't hit you when you dodge.

**Comment by anconfuzedrock** [comment]
also does the HOS gun start on ion mode now because that'd be pretty awkward if people were confused and thought it was on tase if it's still yellow or on disable if ion shots have a bluish color (maybe make it white or something)

**Comment by 4dplanner** [comment]
> also does the HOS gun start on ion mode now because that'd be pretty awkward if people were confused and thought it was on tase if it's still yellow or on disable if ion shots have a bluish color (maybe make it white or something)

good point, rearranged

**Comment by ExcessiveUseOfCobblestone** [comment]
you should make a variant of the projectile that's 0,1 instead of 1,1 so only the target('s turf) gets hit with the heavy and the others get hit with just a light.

That way it will be less viable than the dedicated EMP gun but still useful if you can aim.

**Comment by 4dplanner** [comment]
> you should make a variant of the projectile that's 0,1 instead of 1,1 so only the target('s turf) gets hit with the heavy and the others get hit with just a light.
> 
> That way it will be less viable than the dedicated EMP gun but still useful if you can aim.

will do

**Pull request merged**
