### PR TITLE
Botany chem touches. RETOUCHED.

### PR DESCRIPTION
**Pull request by xXPawnStarrXx**
## About The Pull Request
This PR seeks to change ~~three~~ FOUR chemicals: ~~Saltpetre,~~ Endurogrow, Weedkiller, Liquid Earthquake and adds organic Weedkiller.
Liquid Earthquake and Endurogrow both raise the lifespan of plants but carry harsher penalties, so using a lot is a quick way to cripple the fruit of your plant.
The weed growth speeds incentivises you to use the autotend mode and also incentivises upgrading of plant trays.

EDIT: After feedback, I was reminded that weedgrowth cannot be adjusted. I have setforth to remedy this by giving weedkiller a weed reversal factor, making it reduce weed vunerability and growth rate. I also added a NEW organic chemical that works the same as weed killer, but is significantly less toxic, but also less effective overall. I have also reverted the changes to saltpetre, you can all relax. ~~I might come back for them in future.~~

## Why It's Good For The Game
This PR however doesn't stop you from just tossing that usual mix in your tray and being done with it, but don't expect the best results anymore. (You will still get potency 100 and 10 yield, just won't get lifespan and endurance)

## Changelog
:cl:
balance: fiddled with fertiliser effects on plants. Endurogrow and Liquid Earthquake no longer need be overlooked.
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
Most fertilizers cause plant growth, not sure why saltpeter specifically would increase weeds.  Furthermore, liquid earthquake already does that, so it seems redundant.

You mention in your PR that autogrow mode is being encouraged, which I believe to be a mistake.  Moving away from autogrow would be far more ideal.

Also, even with autogrow, a weed proc will still damage a plants yeild, even if the weeds are removed instantly via autogrow, so you would get locked in a cycle of CONSTANTLY reboosting yield, which sucks and isn't fun.

**Comment by xXPawnStarrXx** [comment]
> Most fertilizers cause plant growth, not sure why saltpeter specifically would increase weeds. Furthermore, liquid earthquake already does that, so it seems redundant.

I added it specifically to saltpetre because it's effects specifically target growth related traits, growth speed and potency.

> You mention in your PR that autogrow mode is being encouraged, which I believe to be a mistake. Moving away from autogrow would be far more ideal.

The purpose of having the advanced trays is so that you can use the autogrow mode, removing that just makes it so that the only benefit of wasting materials over soil plots is that you can see the lights. Why add a feature to make it useless?

> Also, even with autogrow, a weed proc will still damage a plants yeild, even if the weeds are removed instantly via autogrow, so you would get locked in a cycle of CONSTANTLY needing to reboost yield, which sucks and isn't fun.

This is part of the reason I wanted to do this PR, because one 50/50 mix to just max out potency and yield, then never worry about it again makes botany less fun.

> Edit: if you are looking to boost lifespan for cooking purity(I assume this is the case due to your other PRs), consider using grafts, they already work quite well for this purpose.

That is still a valid option if you do not wish to damage your plant's stats with other reagents, I want to add alternatives instead of ONE way to do things.

**Comment by MTandi** [comment]
I'm supporting the Idea of powerful fertilizers having some downside. They shouldn't be just best, but more focused on some particular stat.

Also the lifespan chem is nice as right now the only option to boost it is to graft harebells to everything, and I made it important for the food ingredient quality.

Not to mention that Diethylamine has been working wrong since its introduction - the comment says that it "culls stability" and in the code in culls instability, but it should reduce it by design.

But I'm no botany main, @MrMelbert had some strong points against nerfing these chems.

**Comment by the-orange-cow** [comment]
> Not to mention that Diethylamine has been working wrong since its introduction - the comment says that it "culls stability" and in the code in culls instability, but it should reduce it by design.

I would imagine it is more likely a misspelling, and that it should read "culls instability", just based off there are already strong options for raising instability.

**Comment by MTandi** [comment]
> I would imagine it is more likely a misspelling, and that it should read "culls instability", just based off there are already strong options for raising instability.

```// This is more bad ass, and pests get hurt by the corrosive nature of it, not the plant. The new trade off is it culls stability.```

The first sentence says that it's good for plant, and the second says "trade off". This is definitely supposed to be a negative thing for the plant.

**Comment by MTandi** [comment]
Also the math of bonus application where it checks the total volume of fertilizer is dumb and also looks like a sloppy mistake from the start.

Why should the plant care whether there are 5 units or 25 in the tray if it only consumes 1 unit per cycle.

We should overhaul all this, raising the bonus, but removing the volume check. Or replace it with some proper logic where you have to maintain the concentration of a chemical against the water.

**Comment by the-orange-cow** [comment]
> > I would imagine it is more likely a misspelling, and that it should read "culls instability", just based off there are already strong options for raising instability.
> 
> ```dm
> // This is more bad ass, and pests get hurt by the corrosive nature of it, not the plant. The new trade off is it culls stability.
> ```
> 
> The first sentence says that it's good for plant, and the second says "trade off". This is definitely supposed to be a negative thing for the plant.

The way you are framing it doesn't make sense.  Instability isn't good or bad, at least not in an absolute sense.  If you are trying to mutate or crosspolonate, instability is great;  if you are trying to stat boost, its bad.  Calling it negative(or positive) ignore core botany functionality.

**Comment by MTandi** [comment]
> > The first sentence says that it's good for plant, and the second says "trade off". This is definitely supposed to be a negative thing for the plant.
> 
> The way you are framing it doesn't make sense. Instability isn't good or bad, at least not in an absolute sense. If you are trying to mutate or crosspolonate, instability is great; if you are trying to stat boost, its bad. Calling it negative(or positive) ignore core botany functionality.

My train of thoughts is that it's good for the plant to be stable instead of having a chance to reduce a stat or mutate into another species. 

I don't know whether the author had the same logic, but regardless, my first point is that it should have some negative aspect.

Diethylamine is used to raise yield, so you're not interesting in mutation when you do this. Mutation may reduce the yield or give you another species with random yield. So it makes sense to me that the "trade off" is the stability increase here.

**Comment by Bibarra** [comment]
Making Saltpetre increase a stat that cannot be changed in any other way outside of hoping for a RNG stat mutation (from high instability, which might kill any production speed you gained) is a good way to ensure it never gets used. Much like Liquid Earthquake is never used.

The Botanist's job is already quite hectic and leaves little time for RP when you have a lot of plants to care for. It doesn't sit right to me that a fertilizer that's supposed to take a fair bit of effort to get your hands on is being made completely worthless. There is nothing in the game that can alter weed chances outside of an extremely lucky RNG stat mutation from instability. (which more than likely will eat your production speed stat first)

> I'm supporting the Idea of powerful fertilizers having some downside. They shouldn't be just best, but more focused on some particular stat.

The downside to Saltpetre is the difficulty in obtaining it. Stealing a chem dispenser is both an IC issue and repeated thefts is an administration failure. A competent botanist can get their hands on it without hacking a vendor or stealing a dispenser.

> Also the lifespan chem is nice as right now the only option to boost it is to graft harebells to everything, and I made it important for the food ingredient quality.

Olive tree grafts immediately max out lifespan, no Harebells needed. The change is nice, but it's not really needed.

> Not to mention that Diethylamine has been working wrong since its introduction - the comment says that it "culls stability" and in the code in culls instability, but it should increase instability by design.

Yeeting out your instability can be a bad thing and is interesting in my opinion if you're trying to keep a plant at high instability but also alive. (Ash, Ammonia, Multiver, Cryox can all achieve that)

I feel the 'why it's good for the game' section is misleading at best. How can intelligent mixes be made if there's nothing to compensate for weed chance? I would also point out that autogrow is simply unavailable more often than not due to power issues that pervade most rounds, AND does not prevent weeds. Even a Weed Adaptation graft doesn't necessarily stop your yield getting killed by weeds.

**Comment by MTandi** [comment]
>The downside to Saltpetre is the difficulty in obtaining it. Stealing a chem dispenser is both an IC issue and repeated thefts is an administration failure. A competent botanist can get their hands on it without hacking a vendor or stealing a dispenser.

Fair point, but the downside just disappears the moment you grab a chem master. Or just set up plumbing.

**Comment by Bibarra** [comment]
> Fair point, but the downside just disappears the moment you grab a chem master. Or just set up plumbing.

Setting up plumbing, finding space, and going through the effort to actually DO that is a fair tradeoff imo. Seems to me to be more of a failure of Medbay/Chemistry design than something Botanists should be targeted for. You're looking at a symptom thinking it's the "problem."

And really, is the benefits of having a fast production speed so overwhelmingly overpowered that there even needs to be a downside? Can't Botanists have something that lightens the workload a little? As I stated earlier, Autogrow is not easily available more often than not, and doesn't even feed the plant meaning you're still trapped in Hydroponics either way.

**Comment by xXPawnStarrXx** [comment]
> Making Saltpetre increase a stat that cannot be changed in any other way outside of hoping for a RNG stat mutation (from high instability, which might kill any production speed you gained) is a good way to ensure it never gets used. Much like Liquid Earthquake is never used.

You do have a fair point, I am already looking weed killers. Someone already brought this up to me, I plan to add the fact the reverse to weedkillers 'cause I haven't seen them used effectively in a while either. I plan to make both of them more useful.

**Comment by xXPawnStarrXx** [comment]
I have received a fair amount of feedback; which I appreciate. I'm looking into solutions to all the issues, The concept of this PR is to specialise the later-game chemicals.

**Comment by IzaIsAGoat12** [comment]
Made a new git account specifically just to say that this fucking "retouch" fuckin' sucks. barely any (compitent) botanists use those chems, and the newer ones dont know to steal a chem dispenser for their plants. theres no reason to make bad things even worse. at this point may as well just remove em'

**Comment by the-orange-cow** [comment]
> Made a new git account specifically just to say that this fucking "retouch" fuckin' sucks. barely any (compitent) botanists use those chems, and the newer ones dont know to steal a chem dispenser for their plants. theres no reason to make bad things even worse. at this point may as well just remove em'

Assuming you're talking about enduragrow and liquid earthquake:

Enduragrow is vital for when the plant has low endurance but you want to shear off genes or lock in a mutation.  Liquid earthquake is useful when you are experimenting with high weed procs.

They are certainly niche, bit far from useless.

**Comment by xXPawnStarrXx** [comment]
> Made a new git account specifically just to say that this fucking "retouch" fuckin' sucks. barely any (compitent) botanists use those chems, and the newer ones dont know to steal a chem dispenser for their plants. theres no reason to make bad things even worse. at this point may as well just remove em'

I'm going to preface this with the fact that I have done this retouch by removing most of the negative effects I added in my first pass of rebalancing. The touched chemicals have the added effect of raising lifespan, which with the new cooking updates holds more value to chefs. I'm going to follow up by asking you provide some constructive criticism beyond "This fuckin' sucks", This game is a community based design. I've taken heed of what other people have mentioned to me and if you notice have passed adjustments. So instead offer something that you'd LIKE to see instead of whining about how I'm touching a chemical you seem to not care about?

Podiums all yours, sweetheart.

**Comment by CRITAWAKETS** [comment]
Not a fan of lifespan being a stat that's able to be raised by chems, it's kinda cool that there is currently a positive stat which is only able to be raised by grafting.

I will say however that the foodening lifespan purity thing should be lowered down from a max of 100, because it makes literally any other plant than olives worthless to graft.

**Comment by xXPawnStarrXx** [comment]
> Not a fan of lifespan being a stat that's able to be raised by chems, it's kinda cool that there is currently a positive stat which is only able to be raised by grafting.
> 
> I will say however that the foodening lifespan purity thing should be lowered down from a max of 100, because it makes literally any other plant than olives worthless to graft.

I was at an impass, it was either add more plants with increased lifespan or add a chemical that does so. Most of the plants are genetically modified so I could reasonably understand a chemical that can make it live longer.

**Comment by dalmationer** [comment]
Enduro-grow has become actually fairly useful as a general chem post-foodening. I've been using an ez-nutriment/enduro-grow mix for food plants, 

In terms of feedback, personally I'd quite like if your pr had a rundown of the effects so I don't have to look into the code haha. I'm not great at parsing it.

**Comment by xXPawnStarrXx** [comment]
> Enduro-grow has become actually fairly useful as a general chem post-foodening. I've been using an ez-nutriment/enduro-grow mix for food plants,
> 
> In terms of feedback, personally I'd quite like if your pr had a rundown of the effects so I don't have to look into the code haha. I'm not great at parsing it.

Yeah. I am tempted to take an entirely new go-over on this; clearly outlining what each thing does because it seems a few people aren't reading much beyond the brief.

**Comment by Bibarra** [comment]
Looking at the newer changes, it makes Weedkiller AND LE actually worth using, so that gets a 👍 from me. I don't really see a problem with Enduro raising lifespan as if you want to instantly max your lifespan the Olives are still right there. Maybe make it a fair bit slower? 0.55 is hilariously fast.

**Comment by xXPawnStarrXx** [comment]
Im going to the drawing board with this one. Going to do everything that affects plants in one.

**Pull request closed without merging**
