### PR TITLE
You can no longer put the nuke disk into a custom vendor.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Prevents station loving items from getting inserted into vendors.

## Why It's Good For The Game

Vendor contents don't check for z level change for performance reasons.

### CODE REVIEW

**Comment by Shapsy** [comment]
There's like a dozen sitcom plot lines you could get out of this

**Comment by ArcaneMusic** [comment]
Broke: Fix the bug, prevent crew from shoving the disc in a vendor

Woke: Prevent vendors containing the disc from leaving Z level by porting the disc out, force crew to spend 10000 credits to get it out

**Comment by PKPenguin321** [comment]
>ops have to covertly open a lemonade stand on the station to buy the disk

**Comment by actioninja** [comment]
conflict

**Comment by Learner10** [comment]
Well, I mean don't the contents just eject out when the vendor is busted anyways? That's usually how it works for other vendors.

Besides, I think it's rather funny!

**Comment by nemvar** [comment]
Too lazy to do this. Code is confusing. Can't remember what did what so that's not a good sign.

**Pull request closed without merging**
