### PR TITLE
Updates Margarita recipe (For real this time) and various alcohol value adjustments

### PR DESCRIPTION
**Pull request by carshalash**
With the recent changes to the way that humans handle alcohol, certain drinks have been left in a rather problematic place where they're too good at getting you drunk to properly enjoy. I change a few of the bigger problem ones, the tonic/soda recipes were left untouched for now.

## Changelog
:cl:
tweak: Added Triple sec to margaritas so they taste less awful.
balance: Rebalanced certain alcohol values.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
i think those were so high because they have certain special effects

**Comment by Fikou** [comment]
hmm today i will make support drinks like between the sheets or brave bull even stronger

**Comment by carshalash** [comment]
Between the sheets is garbage to be honest even with the change.

**Comment by Krysonism** [comment]
Good changes, more drinks should probably be adjusted

**Comment by carshalash** [comment]
> Good changes, more drinks should probably be adjusted

Any ones bothering you in particular?

**Comment by ExcessiveUseOfCobblestone** [comment]
is there any semblance of documentation regarding this variable byond `big mean bad`?

**Comment by carshalash** [comment]
> is there any semblance of documentation regarding this variable byond `big mean bad`?

wut

**Pull request merged**
