### PR TITLE
Cleans up turf underneath fridges

### LINKED ISSUE #35595: Pubbystation chemistry is missing a wall
https://i.imgur.com/PHdDZBt.jpg

Unwrenching the fridge in the Pubby chemistry lab leaves a hole in the wall that isn't covered by shutters.

The meta chem lab has a wall behind the fridge to fix this.

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #35595

### CODE REVIEW

**Comment by coiax** [comment]
So do fridges block vision and gas now?

**Comment by ShizCalev** [comment]
@coiax Unintended, guess I'll just fix it in the other way then. :(

**Comment by DaxDupont** [comment]
The walls were placed to prevent people from breaking into chemistry with just a, wrench and 10 seconds. This was intentional. Please mark this pr as a balance change

**Comment by ShizCalev** [comment]
@DaxDupont This is putting the walls that I removed back though?

**Comment by DaxDupont** [comment]
oh oops

**Pull request merged**
