### PR TITLE
XENO: Ensures the stomach contents list is cleared on thing delete

### LINKED ISSUE #68928: Xeno vore allows you to spam acid and does not spit out mob
better than thousand words https://youtu.be/PJZz3ywnSHQ?t=119

Original PR that readded this: #68312
## Testmerges:

The following pull requests are currently test merged:
[#68599: 'Refactors SM Delaminations to be strategies' by vincentiusvin at commit 606d9b0fbb](https://www.github.com/tgstation/tgstation/pull/68599)
[#68855: 'fixes nuke ops leaders not spawning' by Fikou at commit 5ca8320443](https://www.github.com/tgstation/tgstation/pull/68855)
[#68763: 'Adds the Mothroach' by Justice12354 at commit 55f95faa96](https://www.github.com/tgstation/tgstation/pull/68763)

## Reproduction:

Eat humanoid, wait for them to die, start spraying hallways with acid.

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Resolves a bug with infini york
Fixes #68928

## Changelog

:cl:
fix: You can no longer infinitely york as an alien
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
Why i got bad thought when read the title

**Comment by antropod** [comment]
does it still delete the human inside

**Comment by LemonInTheDark** [comment]
Yeah that's a feature

**Comment by antropod** [comment]
so they just tackle you and strip naked and you get deleted?

**Comment by LemonInTheDark** [comment]
if you die inside their stomach you're "digested" (deleted) yeah

**Review by Timberpoes — CHANGES_REQUESTED** [review]
image

Order of operations: Attempting to log_combat qdeleted things.

**Comment by LemonInTheDark** [comment]
yes honey

**Review by Timberpoes — APPROVED** [review]

**Pull request merged**
