### PR TITLE
Changes the shuttlebar back to pre-revert state

### PR DESCRIPTION
**Pull request by Niknakflak**
Simply undoes the changes and removals that coiax snuck in his with his balloon shuttle PR here: #18915

### CODE REVIEW

**Comment by Cheridan** [comment]
wake me up

**Comment by ChangelingRain** [comment]
>snuck in

>failed to read, at best

**Comment by Niknakflak** [comment]
>cheridan didn't know it was a revert

**Comment by optimumtact** [comment]
>meme arrows in markdown

**Comment by MrStonedOne** [comment]
\>using code blocks to do meme arrows

**Comment by KazeEspada** [comment]
\>Having to be reminded about escape \\

**Comment by coiax** [comment]
> Reverting a PR without even having looked at the changes.

Remember Niknak, once you commit code, it belongs to everyone, blah blah open source blah blah. If you feel so strongly about the design, make your own shuttle bar.

**Comment by Niknakflak** [comment]
I looked at the changes, that's kind of how mapping works, You see the existing changes before you change them

**Comment by Bawhoppen** [comment]
:santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa:

**Comment by optimumtact** [comment]
I am going to merge this because I think coaix should have signposted that they were reverting other changes much more clearly.

I don't think they meant to be malicious, but they should be explicit if they are reverting the work of someone where that work has been merged within the last couple of months and that person is still active.

**Comment by coiax** [comment]
fuck off oranges

**Comment by coiax** [comment]
wasn't even a revert, it's removing a drink and a medbay, I kept all the other stylistic choices which I felt improved the thing. None of this would have happened if people had actually listened and/or respected my input and requests

**Pull request merged**
