### PR TITLE
Makes /tg/station join the hubname reddit memes.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
https://www.reddit.com/r/SS13/comments/5s2agm/the_physical_manifestation_of_cancer/

https://www.reddit.com/r/SS13/comments/5s22po/help/

https://www.reddit.com/r/SS13/comments/5s52uk/alien_isolation_13_now_also_has_a_spammy_server/

https://www.reddit.com/r/SS13/comments/5s3ocv/ss13_hub_040217_still_not_looking_good/

https://www.reddit.com/r/SS13/comments/5s3h61/public_appologie/

This pr makes our font look really small.

### CODE REVIEW

**Comment by Cyberboss** [comment]
OH BOY

**Comment by Incoming5643** [comment]
You didn't even use a blink tag!

**Comment by MrStonedOne** [comment]
\>make the font look small

\>it looks bigger on the client.

**Comment by Bill-Luxe** [comment]
Please no!

**Comment by Anonmare** [comment]
>>/reddit/

**Pull request closed without merging**
