### PR TITLE
Fix malf AI from being able to blow up pipes and other components

### LINKED ISSUE #56581: AI can blow up air-pipes with overload electronics
Round ID: [155485](https://scrubby.melonmesa.com/round/155485)

Reproduction:
well basically the title, the AI can blow up air pipes with overload electronic whatever, admin confirmed it was a code issue, I cant code so here's a bug report.
have an image too https://imgur.com/a/ZgLqd6d

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Fixes #56581
Title, Malf AI won't be able to blow up some atmos machines (like pipes)
reasons:
-Pipes: they don't have any electronics, all pipes are affected, even H/E pipes, multiz adapters, layer adapters, manifolds.
-Unary Tank: Those are the big tanks to store gases, they don't have electronics
-Portable connectors: Connect portable atmos machinery to the pipeline, no electronics
-Heat exchangers: just radiators
-Hypertorus Fusion Reactor: special protection against electronic manipulation
-Manual Valve: no electronics
-Canisters: just a portable big tank

## Why It's Good For The Game
Bug fix

## Changelog
:cl:
fix: fixed malf AI overload ability from blowing up non-machine atmos devices (like pipes) and the HFR
/:cl:

### CODE REVIEW

**Comment by Pinkufeck** [comment]
Are you claiming radiators don't have electronics ?

**Comment by Ghilker** [comment]
> Are you claiming radiators don't have electronics ?

if you claim that these have electronics, i'll smack your face 
image

**Comment by TemporalOroboros** [comment]
I can follow your logic for most of them, but why the HFR?

**Comment by Ghilker** [comment]
> I can follow your logic for most of them, but why the HFR?

The HFR doesn't support pieces of it blowing up and will badly break

**Comment by zxaber** [comment]
Sounds like a bug with the HFR.

**Comment by Mothblocks** [comment]
Merge from latest upstream, the test failure has already been resolved.

**Comment by LemonInTheDark** [comment]
> The HFR doesn't support pieces of it blowing up and will badly break

What happens if it blows up normally? Isn't that a separate issue? or is it something more unique

**Comment by Ghilker** [comment]
> What happens if it blows up normally? Isn't that a separate issue? or is it something more unique

normal blow ups are fine they don't have any issues, but removing a random piece without proper proc calling can be bad. I think the machine could handle it (it can handle having a piece admin qdel and not freak out) but i prefer not having those issues

**Comment by LemonInTheDark** [comment]
Could ya test it? I'm good with blacklisting it, since there are much more interesting ways of sabotaging the thing, but just to be sure

**Comment by Ghilker** [comment]
tested it, exploding the core result in the whole machine deleting (as expected on admin qdel)

**Comment by EnPeignoir** [comment]
Can you maybe give us screens or a video as a proof ?

**Pull request merged**
