### PR TITLE
Mounted Guns

### PR DESCRIPTION
**Pull request by ghost**
_Disclaimer: This is mainly intended for a gamemode I may or may not develop in the near future. This is also WIP, so do not merge it._

They're mounted guns! Highly customizable. They're anchored in place and fire a single projectile in the direction it's facing - it doesn't support target tracking like their more advanced brothers (turrets) can. Things about the guns that can be customized as of right now:
- If it can be fired manually
- The type of projectile it fires, physically (solid or energy)
- The type of projectile actually shot out (i.e. laser, electrode)
- If the gun uses ammo, and, if so, the max amount of ammo
- The item the gun consumes to restock ammo by a set amount (likely will be unique items in the future)
- All messages and sounds upon firing (or failing to do so)
- Delay between shots

These are also intended for admin events. Ever wanted to have a shuttle with remotely-controlled laser cannons? Now you can. Maybe I'll even throw some weak defense turrets on the emergency shuttle, or even make them constructable. Coming soon: friendly cultist beams!

### CODE REVIEW

**Comment by RemieRichards** [comment]
Since this is a mounted gun, logically... this would just store a gun inside the object and then fire the gun.

**Comment by Supermichael777** [comment]
AVAST ME-HARTYS! PREPARE A BROADSIDE ON THAR STATION

**Comment by Anonus** [comment]
Storing a gun means you have to make a gun(with max ammo amount/cell charge) and proper reload/recharge methods instead of just using a fake, but much simpler and easier to tune ammo system.

**Comment by RemieRichards** [comment]
@Anonus no, this should really be a gun stored in the object.

**Comment by Xhuis** [comment]
That would limit the potential customization for the guns, which made me deliberately avoid it.

**Comment by RemieRichards** [comment]
@Xhuis guns are already very customisable.

**Comment by Xhuis** [comment]
I won't be incorporating guns into this design. The items, I mean. I will rename these if it seems like it could be confusing.

**Comment by RemieRichards** [comment]
Then be very aware I'm super not happy with this, and unless things diverge away from the current form, I dont think this should be merged.

**Comment by Xhuis** [comment]
In the interest of closing the number of active PRs I have, this is being closed until I decide to continue it, if ever.

**Pull request closed without merging**
