### PR TITLE
Chunky fingers no longer blocks all mod PC use, instead will cause UI actions to fail (sometimes) 

### LINKED ISSUE #71180: you can't use your pda with insulated gloves on
## Reproduction:
put on insulated gloves
try to use pda
fingers too fat

I know it's technically a modular computer but previous behaviour allowed you to use your pda with insulated gloves on.

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Chunky Fingers no longer blocks all modular PC viewing
- Instead, attempting to use a modular PR in any way (any UI act) will have an RNG chance (75% chance currently, same as MODsuit malfunctioning) from doing nothing. 

Closes #71180

## Why It's Good For The Game

I always thought it was a little silly that you could not even *view* a computer if you had gloves on. It is very annoying for engineers to have to take their gloves off just to check the CIMS interface.

So I decided to rework this mechanic. Chunky fingers will, instead of blocking you from viewing the PC wholesale, instead make it such that (on occasion) your inputs will be dropped. 

Engineers and stuff can view their tablets, PCs, and PDAs like normal, but actually using it will be a crapshoot. Just like real life, you can tap your phone all you want, but sometimes it will just do nothing, because the touch screen doesn't react to the glove's touch. 

Plus I think this is funnier?

image

## Changelog

:cl: Melbert
balance: Chunky Fingers (insuls and hulk) no longer entirely block you from opening modular computers / PDAs. Have you ever actually tried to use a touch screen wearing gloves? Half of your swipes never do anything. So that's what happens instead. It adds a chance of randomly failing UI actions / inputs. And damn, this will be annoying. Just like real life. It'll immerse you. 
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
if you dont have anything visual on the ui for this, people will just think its bugged

**Comment by Iamgoofball** [comment]
replace the mouse cursor with a giant bulky finger that presses buttons in an AOE around the tip of the finger

**Comment by Mothblocks** [comment]
@MrMelbert i say you could keep it simple and have a shared component between whatever uses this that just displays a big modal with the text instead

**Comment by CRITAWAKETS** [comment]
> I don't know what visual would work for it, otherwise I'd make it generic because MODsuits do the same thing

If you want a rather generic visual, just a red X that shows up for a bit whenever an action is cancelled will probably do just fine if there's a message at some point stating what is happening.

**Comment by optimumtact** [comment]
>replace the mouse cursor with a giant bulky finger that presses buttons in an AOE around the tip of the finger

>this will communicate it to the player and make it really funny trying to hit buttons next to other buttons with boxing gloves on

Do this otherwise it's still a no on this change

**Comment by msgerbs** [comment]
Honestly just remove chunky fingers from computers. The whole point of giving insuls chunky fingers per the PR that did it was to keep insul users from firing guns. There was never any real justification given for *why they should also not be able to use modular computers* beyond just "well because that's how chunky fingers works".

**Comment by private-tristan** [comment]
> Honestly just remove chunky fingers from computers. The whole point of giving insuls chunky fingers per the PR that did it was to keep insul users from firing guns. There was never any real justification given for why they should also not be able to use modular computers beyond just "well because that's how chunky fingers works".

Filkou tried that already  #62324 and when I asked oranges if he'd changed his mind he said no.

**Comment by msgerbs** [comment]
So dumb. The justification for adding it was shaky at best but for some reason removing it needs an act of god. I don't get why oranges is so attached to this. The goal was to making insuls have a downside to tiding them, but the only people who ever use computers *are also the only people with legitimate access to insuls*. Random assistants don't care at all that they can't use computers with insuls on.

**Comment by moocowswag** [comment]
>The goal was to making insuls have a downside to tiding them, but the only people who ever use computers _are also the only people with legitimate access to insuls_. Random assistants don't care at all that they can't use computers with insuls on.

Insuls in general shouldnt even be seen as an item tiders go for. You can hack airlocks without them but you cant wire solars or your own apc without them, its just generally everyone suffering because a minority of players that arnt smart enough to realize the time investment into getting insuls is greater than just finding shock/test wires then healing yourself.

Also insuls are expensive and limited yet everyone can have the insulated gene with genetics so why do insulated gloves have the downside while insulated gene makes your finger tips numb but doesnt actually do anything about that.

**Comment by Mothblocks** [comment]
when moocow says assistants dont need to steal insuls to hack doors, keep in mind that i see moocow in rounds put signallers on every door wire one by one and walk back repeatedly for like 2 minutes so he doesnt take damage

im not even saying you need insuls i just think thats extremely funny

**Comment by moocowswag** [comment]
I go through great lengths to not have to heal myself.

**Pull request closed without merging**
