### PR TITLE
Removes the Spooky

### LINKED ISSUE #8136: The chemical krokodil is OP
Considering the benefits skeletons enjoy https://tgstation13.org/wiki/Guide_to_races#Skeletons

They're really OP to let chemistry mass produce. Skeletons should not even be player-transformable and should be kept admin-only.

Players are using it to powergame for a free space suit and bleeding immunity.

### PR DESCRIPTION
**Pull request by Incoming5643**
Skeletons and zombies can no longer be achieved with krokodil and strange reagent.

But they can still show up in rare mutations (I think) and wizard business 

Fixes #8136

### CODE REVIEW

**Comment by pudl** [comment]
N

**Comment by pudl** [comment]
O

**Comment by Incoming5643** [comment]
:skull: :gun: :older_man:

**Comment by Mandurrrh** [comment]
10/10 for the picture

**Comment by JJRcop** [comment]
Maybe skeletons can also have lower brute tolerance? I mean, bones...

**Comment by Dorsisdwarf** [comment]
Give them back their temp/whatever resist and lower their maxhealth, I say

**Comment by Nienhaus** [comment]
cnpr5j5
This is my skeleton, he doesn't like nerfs. :c

**Comment by Deantwo** [comment]
Temperature damage makes sense, radiation not so much.

**Comment by Incoming5643** [comment]
We can (and should!) think of more interesting ways to delineate mutant races from normal play, but for right now I'm just bringing them down to a level where it's alright that the chemists can <a href="http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=175070">skeletonize</a> before the 5 minute mark.

**Comment by dannno** [comment]
This is the wrong way to go about this
just stop any chems from turning you into a skeleton because that's fucking stupid anyways

**Comment by Ikarrus** [comment]
Skeletons aren't even a mutant race.

They're just a stupid joke made even stupider by actually adding them to the game.

**Comment by Nienhaus** [comment]
I want to point out I was just recently told that they are actually ingame. I'm surprised that was done.

**Comment by Incoming5643** [comment]
goonchem

**Comment by Ikarrus** [comment]
No, this is goofchem

**Comment by CocaneStyle** [comment]
I think it would make more sense to just give them less health in exchange for the environmental immunity.

**Comment by Dorsisdwarf** [comment]
This is why we can't just port everything *cough*

**Comment by dannno** [comment]
seriously incoming just remove the skeleton effect entirely from all chemicals, and make zombies really, really shitty.

**Comment by Dorsisdwarf** [comment]
Zombie should be something that only exists for you to be debrained from and put in a new body to clone really

**Comment by Lumipharon** [comment]
Wizards need a spell 'reanimate dead', brings players/mobs back as zombie minions. Use it on a dead zombie to bring it back as a skeleton. After they die as a skeleton they're reduced to just a pile of bones.

Also seriously what the fuck, what does this shitty chem even turn people in skeletons? Supposedly skin and shit can slough off from shared needles or some shit, not TURN INTO AN ANIMATED SKELETON.

**Comment by RemieRichards** [comment]
@Lumipharon 
>Wizards need a spell 'reanimate dead', brings players/mobs back as zombie minions. Use it on a dead zombie to bring it back as a skeleton. After they die as a skeleton they're reduced to just a pile of bones.


COUGH I totally have an artefact for the wizard to bring back up to 3 people as skeletons at a time.
this PR is totally up on our github and has been for a while.

**Comment by Ikarrus** [comment]
It's okay to keep skellies and zombies OP as shit as long as they're limited to admin and antag powers.

**Comment by Incoming5643** [comment]
Fair enough, just give me a second to make this pull that, I'm doing something else right now

**Comment by Durkel** [comment]
I'd rather we just nerfed them. The effects of race were supposed to be minor anyway. Who the hell buffed them in the first place?

**Comment by Ikarrus** [comment]
That's the thing though, they're not supposed to be a race at all. They're meant to be cheap laughs during Halloween.

**Comment by Iamgoofball** [comment]
Hey no stop hold on here

**Comment by dannno** [comment]
how about no because that's crossing the border of haha funny and just stupid and questionable
krokodil can have serious and dangerous effects instead of goofy "woahahaha!! spoopy!!" ones

**Comment by Ikarrus** [comment]
Too goofy for tg, I agree

**Comment by Iamgoofball** [comment]
@dannno but it has serious and dangerous effects still?

@Ikarrus are you talking about the server or the codebase tg?

**Comment by Ikarrus** [comment]
Both. I'm a contributor as well as an admin, don't forget.

**Comment by Iamgoofball** [comment]
How about I add a purely cosmetic zombie species so that I can maintain the "what the fuck happened to your skin" part of krokodil?

As the main reason I added that was so that it was obvious that the guy was suffering bad krokodil effects, because otherwise it's "Oh god my skin is peeling off at the touch in large clumps-wait what my sprite looks just fine".

**Comment by Ikarrus** [comment]
I'd be fine with a replacement "species" if you could make it thematically fitting.

**Comment by Iamgoofball** [comment]
Okay, I'll add that to the goonchem part 5 PR.

**Comment by Ikarrus** [comment]
Well until you do remove remove remove

**Comment by Atskadan** [comment]
all of this is fine as long as there could be some long-winded process to become a skeleton in the future
more so than taking a bunch of drugs and healing yourself before you die
or injecting yourself with mutagen and healing yourself before you die

**Comment by optimumtact** [comment]
Would you please give it a few weeks or so, I promise you the rash of people turning themselves into skeletons will die down.

Smacks of kneejerk changing to me

**Comment by dannno** [comment]
nigga its been more than a few weeks
even if it died down it would still be retarded to have the option of changing into a race so ridiculously superior to humans so easily in the first place
get this shit out of here

**Comment by Miauw62** [comment]
these races were supposed to be gag admin races, i have no idea why anybody would make them this robust.

**Comment by Dorsisdwarf** [comment]
So that the necromancy stone which makes skeletons are better than just a 5-use revflash?

**Comment by dannno** [comment]
to be fair to the necro stone, it's not like the crew would likely be combating them with oxy or rad damage

**Comment by Miauw62** [comment]
>implying a 5-use revflash isn't powerful

**Comment by RemieRichards** [comment]
it's 3 use ._.

**Comment by CollenN** [comment]
You could always just have it add some sort of gross-looking damage overlay to show that holy shit your skin is peeling off

Honestly, I agree, this is way too silly for /tg/. Like, cartoonishly silly. The skeletons were only really  ever meant as a joke, anyway.

**Comment by optimumtact** [comment]
Wait, what if we make skellingtons valid?

**Comment by Ikarrus** [comment]
Noooooope

**Comment by optimumtact** [comment]
What if we make skellingtons able to make others valid?

**Comment by Lumipharon** [comment]
What if we make everyone valid :^)

**Comment by Atskadan** [comment]
>too cartoonish for /tg/

im sorry i didnt know we were a serious roleplaying server

**Pull request merged**
