### PR TITLE
Modern Armor For The Modern Age - Marine ERT's Armor Update

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
It has taken me until now to realize that the current armor of the marine ert makes them look like larping losers, that demand no respect at all.

I have also seen that they really need an air tank and cold protection, otherwise they are entirely useless 9/10 times.

THUS, I have taken it upon myself to fix BOTH of these problems in one swift move.

image

OH AND all the sprites are either straight from, or slightly edited from tgmc, bless them I steal all their armor

## Why It's Good For The Game
The current marine ert looks lame, sad, and is entirely cucked by some slightly bad air and a little cold, which is quite lame when you get to watch supposedly badass tacticool marines get their ass beat by a slight chill. Also this new armor just looks cooler.

## Changelog

:cl:
balance: the marine ert is no longer as vulnerable to atmospheric problems as before
imageadd: a new centcom themed combat uniform
imageadd: objectively better looking marine armor
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
Pictures added

**Comment by optimumtact** [comment]
the needs pictures is an in game picture, not a picture of the sprite

**Comment by Paxilmaniac** [comment]
> the needs pictures is an in game picture, not a picture of the sprite

this is an in game picture, they're just standing on white floors

**Comment by Bawhoppen** [comment]
I'm not really a fan. The sprite quality is just fine, but I think they're far too dark and serious. While the old ERT sprites may have had some issues, their bright color scheme wasn't a problem in my eyes at all, and lended well to their character as a rescue team, rather than a blackops strike team. I think that perhaps an adjustment in line with these sprites, but a much less dark color scheme could be promising.

**Comment by optimumtact** [comment]
they don't really look like marines, they look like a riot squad or something

**Comment by ilikesaying** [comment]
would you rather have this?
griff

**Comment by drIcepop** [comment]
These look really nice, but as someone above said, I think they could use a bit more color. The medical one is amazing though

**Comment by Fikou** [comment]
the commander and sec guy look too similar

**Comment by realthomas69** [comment]
i like these alot, they look very tacticool, nice work. i wish security had armor like this

**Review by Twaticus — APPROVED** [review]

**Comment by Paxilmaniac** [comment]
FUCK its always something with these GOD DAMN MERGE CONFLICTS

**Pull request merged**
