### PR TITLE
tgui: Malfunction Module Picker

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR brings a new UI for the Malfuction Modules Picker derived from Uplink UI made originally by @actioninja. The new UI uses a whole new Malfunction theme.

Modules are sorted by their cost, and will disappear from the menu if they are limited to one purchase only after they are bought. No changes to modules themselves, they were only reorganized in their file and given appropriate category. Code containing UI stuff was moved into a seperate file, as the file with modules was already too large.

**Updated Image:**

FinalMalfMenuUI

## Why It's Good For The Game

Better UI.

## Changelog
:cl: Arkatos and actioninja
add: Malfunction Modules Picker now uses tgui.
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
Death to HTML, glory to TGUI(-next)!

**Comment by Neo-0** [comment]
mechfab tgui-next when

**Comment by stylemistake** [comment]
This theme doesn't differ enough from the other themes (ntos, syndicate), and by looking at the code, I estimate that it adds around 15KB.

Also it might be worth to generalize this template, since there's a lot of copypasta going on and it can be reused in many more interfaces.

**Comment by GunHog** [comment]
Seeing as Malf = Traitor AI now, and that this can be unlocked "Combat Software" disk, you could use the Syndicate theme if you are asked to remove this one. I personally like the theme, though.

Minor nitpick: The indicator for the AI's PT (The one on the top left) could be expanded to "Processing Time", as you really only need to abbreviate the cost buttons; There is plenty of room there for the full text.

Also, please consider the Botcall interface (The one that lets the AI control the station bots) for TGUI Next. It could benefit from have a proper autorefresh.

**Comment by cacogen** [comment]
Thank God. I forget what the old one looks like but iirc it's ancient

**Comment by stylemistake** [comment]
15KB perhaps won't slow down the browser, but extra themes slow down the compiler for sure.

**Comment by Arkatos1** [comment]
@stylemistake I have removed Malfunction theme and replaced it with the Syndicate one.

UI now also uses generalized Uplink interface, which fortunately only required small tweaks.

Main post updated.

**Comment by trollbreeder** [comment]
Shame. I liked the blue style of the malf picker, as if you (the AI) had hacked into a secret NT debug menu.

**Comment by stylemistake** [comment]
I thought a bit about it, and I'd say revert, because having a separate interface file is good for adding new malf-specific features. We will deal with copypasta later, I have some ideas.

**Comment by Arkatos1** [comment]
@stylemistake  Done. Commit reverted and I have changed interface name to the one you suggested to be more clear. Main post updated.

**Review by stylemistake — DISMISSED** [review]

**Comment by Ghilker** [comment]
love it, good job

**Comment by Arkatos1** [comment]
PR is ready for merge and Style has approved it earlier, but a small code cleanup commit dismissed the approval review, so be aware.

**Pull request merged**
