### PR TITLE
[Omega] adds windoor to bar, adds plant disks to botany

### LINKED ISSUE #29949: Omegastation bar doesn't have a windoor + botany doesn't have plant data disks
i was just talking to a friend (Refticano) about maps and he told me this.

@ShizCalev another billionth map issue for shizcalev to mess with

### PR DESCRIPTION
**Pull request by ShizCalev**
Closes #29949

### CODE REVIEW

**Comment by Cyberboss** [comment]
Autotagger only recognizes `Fixes`

**Comment by kilkun** [comment]
pics please

**Comment by PraiseRatvar** [comment]
http://puu.sh/xbuZ8/dd4ef4b09b.png
imagine a windoor there

and imagine a box full of plant data disks in botany

there are your pictures

**Comment by ShizCalev** [comment]
@kilkun http://c2n.me/3MZL9d9.png

here you go fam.

**Pull request merged**
