### PR TITLE
Moves hands to a new sprites, uniforms no longer need holes

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl: nicbn
fix: Now if you lose arms you won't be able to see through your uniform.
/:cl:

#34523

### CODE REVIEW

**Comment by WJohn** [comment]
wait how does this fix the hole issue, exactly? because the fact that the uniforms were drawn *around* the arms with nothing actually existing under them is why they have them now.

**Comment by Bawhoppen** [comment]
Both a code change and a sprite change. They added the stuff that would go under them.

**Comment by ExcessiveUseOfCobblestone** [comment]
It doesn't yet.

**Comment by Bawhoppen** [comment]
It does. Look at uniform.dmi

**Review by ShizCalev — APPROVED** [review]
some small tweaks needed, but i can do it later.

**Comment by ExcessiveUseOfCobblestone** [comment]
stupid misleading bot

**Comment by ShizCalev** [comment]
@WJohn Look good to you?

**Comment by optimumtact** [comment]
NOBODY HAS ANY ARMS

**Comment by nicbn** [comment]
What

**Pull request merged**
