### PR TITLE
Adds a short telegraph to the watcher's blasts

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
balance: Watchers now have a half-second telegraph between charging and firing their freezing blasts.
/:cl:

### BREAKING: A Solution For The Watcher Problem?

SS13, Sector 7 - As more and more miners die to unavoidable or buggy watcher blasts, crew are left wondering what they can possibly do. Nanotrasen scientists think they have a solution.

"Watchers are, obviously, line-of-sight based," explains research director Fludd Plasma. "The lack of warning for their attacks has caused miners to die in swathes, and we think we have a cost-effective and ingenious solution." Fludd explained that it was as simple as facial reconstruction. "If you look ugly enough, the watchers will hesitate a moment before firing. That quick delay can be the difference between life and death."

Nanotrasen stations are expected to begin forcing plastic surgery on new shaft miners within a week's time. While they might not like it at first, tests have shown that it is instrumentally useful in saving their lives.

Xhuis, The Griffon

### The Griffon

___

Watchers now have a telegraph before they fire, in which a sound and message are outputted to everyone nearby. The actual firing takes place about half a second after that message, but the actual firing itself is unchanged. This makes the watchers' shots less unpredictable based on lag and life ticks, but still requires quick reactions and dodging skills to avoid, and should make watchers less irritating to fight against.

This also adds telegraphed shot framework to all hostile simple mobs,

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@Ergovisavi

**Comment by Dorsisdwarf** [comment]
maybe make it a bit less, half a second seems like a lot of warning in a high-speed combat situation?

**Comment by Hatfish** [comment]
Good change, goliaths already have an obvious telegraph and so watchers definitely should as well.

**Comment by KorPhaeron** [comment]
He will surely be here soon

**Comment by ExcessiveUseOfCobblestone** [comment]
@Repukan

**Comment by Xhuis** [comment]
As much as I respect his opinion, do we really need to get input from Ergo on *every* lavaland change?

**Comment by KorPhaeron** [comment]
He basically designed lavaland combat so I think its wise to ask him

**Comment by Repukan** [comment]
Half a second is way too much t b h.

**Comment by Ergovisavi** [comment]
There is a fundamental question you have to ask with this constant attempt to make watchers more "fair"

Is lava land a place where the miner is supposed to learn and then stomp all over the inhabitants, or is lava land a place where the miner is on the defensive? The asteroid was a defensive place, due to limited movespeed, more hostile environment (or rather, the lack thereof), and part of that is Watchers being kind of a pain in the fucking ass to fight sometimes rather than a pure test of your combat abilities.

This is less of a question for me and more of a question for @KorPhaeron . If you want to create an environment where miners are the agressor, push this through, if you want the opposite, deny it. It'sa bout producing a feel, rather than a "This is objectively better" thing.

**Comment by optimumtact** [comment]
well that didn't answer any question so I'll just fucking guess as usual

**Comment by Repukan** [comment]
Why

**Comment by Repukan** [comment]
>Merging something with DNM tag

Fucking fruit reeeeeeeeeeeeeeeee

**Comment by optimumtact** [comment]
>DNM tag until ergo replies
>ergo replies 3 days ago
>neutral response
>literally no further comments on the pr

**Comment by KorPhaeron** [comment]
I forgot sorry!

**Pull request merged**
