### PR TITLE
Light Boxes and Inhand Light Tube Sprites Now Match Their Item Counterparts

### PR DESCRIPTION
**Pull request by RedBaronFlyer**
## About The Pull Request

This PR changes light bulb/tube/mixed boxes and inhand light tube sprites to better match the current light bulb/tube sprites.

The inhand shattered and burned-out inhand sprites for light tubes were also changed to match the current grey/white lighttubes.

## Why It's Good For The Game

Visual consistency with the current light bulb/tube sprites/icons. Currently, inhand sprites for the light tubes are still yellow, and the boxes that hold light tubes/bulbs/both are still yellow as well.

## Photos (before and after)

beforebulbs
afterbulbs

beforeinhand
afterinhand

## Changelog

Inhand light tubes are now white/grey like their object sprite counterparts
Light boxes (tubes, bulbs, and mixed) previous yellow bulb/tube/mixed icons have also been changed to white/grey ones

:cl:
image: light tube inhand sprites are now grey, as are the icons for the light bulb/tube/mixed boxes
/:cl:

### CODE REVIEW

**Comment by RedBaronFlyer** [comment]
I apologize in advance if I goofed something up. This is my first sprite PR.

**Comment by RedBaronFlyer** [comment]
I think I might have goofed something.

**Comment by MTandi** [comment]
I know that this may be correct, but yellow looks nicer - maybe we should update the tube and bulb sprites instead... they're back to having yellow lights anyway.

**Comment by RedBaronFlyer** [comment]
> I know that this may be correct, but yellow looks nicer - maybe we should update the tube and bulb sprites instead... they're back to having yellow lights anyway.

I would be interested in doing that if I could. Unfortunately, I just don't have those skills at the moment.

**Comment by MTandi** [comment]
> I would be interested in doing that if I could. Unfortunately, I just don't have those skills at the moment.

Just do the same thing but, in the `lighting.dmi` and coloring light tubes, bulbs and fixtures in a yellow tint.

**Pull request merged**
