### PR TITLE
Adds a new cytology-focused vending machine to the science area

### PR DESCRIPTION
**Pull request by r3dj4ck0424**
## About The Pull Request
Creates a new vending machine in the science area, called the CytoPro and filled with cytology gear (and a few things that might be useful in xenobiology). This vending machine is added to the cytology labs of all maps.
Here's how it looks in-game (with the panel screwed open, I was hacking it to test at the time)
CytoPro - Metastation
The current product list is shown below.
CytoPro - Products
CytoPro - Contraband
I've put them in the locations shown below.
Birdshot:
CytoPro - Birdshot
Delta:
CytoPro - Deltastation
Icebox:
CytoPro - Icebox
Northstar:
CytoPro - Northstar
Tram:
CytoPro - Tramstation
Wawa:
CytoPro - Wawa

**Feedback on more products welcome!**

## Why It's Good For The Game
Currently, there aren't a lot of backup sources for cytology gear. Most maps spawn with a single cytology closet containing the necessary gear, and good luck to you if someone makes off with the supplies before you get there. In addition to adding a source of backup cytology equipment, I'm hoping that this new vendor makes cytology quicker and more accessible.
Plus, science really needed a new vending machine, and I think the purple-white colour and stylized microscope are neat.
Since the cytology lab is usually located very close to the slime pens, the addition of monkey cube boxes, xeno bags, and bio suits also helps support xenobiology projects. If the 14 cubes supplied at round start are insufficient (which they really shouldn't be) then they can supplement their supply with the boxes in the CytoPro.
## Changelog
:cl:
add: A new vendor of cytology equipment, the CytoPro, is now available in your local science department!
/:cl:

### CODE REVIEW

**Comment by atlasle** [comment]
this is great but cytology will never be fun

**Comment by mc-oofert** [comment]
i think you could just put the vendor inside cyto on wawa

**Review by Wallemations — APPROVED** [review]
Basic vending machine, boring but works fine

**Comment by Ghommie** [comment]
Huge merge conflicts.

**Comment by r3dj4ck0424** [comment]
Hm, that's odd. Must be the wallening map changes. I'll get around to tweaking it soon.

**Comment by r3dj4ck0424** [comment]
I hope that worked

**Comment by Ghommie** [comment]
Scratch your current map changes and redo them, otherwise other PRs are going to suffer from this and eventually some artifacts or mapping errors may slip in through the crack.

**Comment by r3dj4ck0424** [comment]
Very well. Just a moment.

**Comment by r3dj4ck0424** [comment]
I think that's fixed things. Hopefully.

**Pull request merged**
