### PR TITLE
Add cloning

### PR DESCRIPTION
**Pull request by Acensti**
## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Acensti** [comment]
my bad i didnt mean to put PR here, my cat distracted me

**Comment by Time-Green** [comment]
Happens surprisingly often

**Comment by GoldenAlpharex** [comment]
Big dick energy right here

**Comment by Imaginos16** [comment]
Fourth time in a row ladies and gentlemen

**Pull request closed without merging**
