### PR TITLE
Adding the ability to remove the firing pin

### PR DESCRIPTION
**Pull request by bear1ake**
Remove the fucking firing pin from gun with wirecutters! >:D

### CODE REVIEW

**Comment by Firecage** [comment]
This kind of makes firing pins redundant and useless.

**Comment by pudl** [comment]
lmao

**Comment by TheVekter** [comment]
:-1:, no point in firing pins if they're THAT easy to remove.

**Comment by hornygranny** [comment]
This is a stealth revert.

**Comment by bear1ake** [comment]
but gun can't fire without firing pin

**Comment by TZK13** [comment]
A lot of people don't seem to realize that the point of firing pins isn't that they block people from using guns but that they allow you to fire guns with only some firing pins having specific restrictions related to blocking usage. Considering most guns come with default firing pins the only reason why somebody would remove the firing pin would be to either make the gun useless or to replace it with a more restrictive firing pin. Same deal with R&D guns, considering they come out with no pin at all this would hardly negate the usefulness of pins. The only thing would currently effect would be the ability to use nukeop guns but even then you would still have to either find an emag or a replacement pin.

Besides, Cheridan has already said that he intends to add in the ability to remove firing pins in the future although he implied that it would be a bit more of an involved process than this.

**Pull request closed without merging**
