### PR TITLE
Doubles the effect manipulators have on cloning speed

### PR DESCRIPTION
**Pull request by Shadowlight213**
Makes cloning great again.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
shadowlight on point

**Comment by LatD** [comment]
Has the effect been nerfed at some point? I thought they already made it much much faster compared to non-upgraded cloner.

**Comment by PKPenguin321** [comment]
not sure that this is necessary

**Comment by ToadStar** [comment]
Instead of setting the speed coeff to twice the part's rating why not just change lines 216 and 219 so they don't divide it by two.

Note that if you do this, cloning speed moves up from the following speeds at these tiers:
T1: ~190 Seconds (3 Minutes and ten seconds)
T2: ~95 Seconds (Just over a minute and a half)
T3: ~64 Seconds (Just over a minute)
T4: ~48 Seconds (Less then a minute!)

to

T1: ~95 Seconds
T2: ~48 Seconds
T3: ~32 Seconds (Little over half a minute!)
T4: ~24 Seconds (Lightning fast! Under half a minute!)

**Comment by Jazaen** [comment]
An actual buff to genetics. Welp, I haven't seen that in a while.

**Comment by Kromgar** [comment]
Please we need this cloning takes FOREVER now

**Comment by KorPhaeron** [comment]
@Cheridan this actually isnt powercreep, since cloning "upgrades" were added by nerfing cloning and making you fix it every round instead

**Comment by LatD** [comment]
Seems like the time it takes to finish was about doubled when the upgrades were added but this was in 2013.

**Comment by Shadowlight213** [comment]
Alright. I'll make the change when I get home .
I have some ideas about buffing t4 autoscanning to allow for mass scanning that I also want to take a look at implementing.

**Comment by Shadowlight213** [comment]
Closing unless #18131 removes the ghost grab default change. A speed buff is not needed if the players don't need to wait.

**Comment by PKPenguin321** [comment]
there is no reason this and 18131 cant coexist

**Comment by Shadowlight213** [comment]
@PKPenguin321 with 18131 the buff is unneeded as the player doesn't have to wait while cloning.
A three minute or whatever cloning time is perfectly fine if you can just fly around and chat in deadchat the entire time.

**Pull request closed without merging**
