### PR TITLE
Adds toggleable pit grate

### PR DESCRIPTION
**Pull request by AnturK**
Adds button toggleable pit grate. That's all.

~I'll have to upgrade that button signaling a bit.~ Changed my mind, buttons need full refactor so i'll leave this light on that front.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
This will allow for more interesting ruin designs at least.
Indie, its Yahweh, not Jevhovah

**Comment by Tharcoonvagh** [comment]
This is so good, hope it won't get stale

**Comment by OverlyGeneric** [comment]
ah yes, felinids the ultimate test subject since Schrodinger's cat.

**Review by ninjanomnom — APPROVED** [review]

**Comment by Tharcoonvagh** [comment]
How does it work though? Do you have to be on a second zlevel to make a pit grate? How do you connect the button to one?
Can you use two grates with one button?

**Comment by AnturK** [comment]
It's mapper/admin only for now.
Yes.

**Pull request merged**
