### PR TITLE
Riot Gear Update 

### PR DESCRIPTION
**Pull request by Malgover**
## About The Pull Request

Adds the new riot suit sprites I made for Beestation last month.

new1
newer

riot2

## Why It's Good For The Game

The old sprite looked like plate armor from the Middle Ages. This PR fixes that.

## Changelog
:cl:
imageadd: new riot armor sprites
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
SECURITY SPRITE PR DETECTED

ACTIVATED AUTOMATED STEELPOINT PROTECTIONS


https://user-images.githubusercontent.com/2544323/123864220-9d1d9380-d97e-11eb-848f-04949f099dbb.mp4

**Comment by Thunder12345** [comment]
Changelog should be "imageadd: new riot armor sprites", by using add it gets wrongly tagged as a mechanic and either someone removes the tag manually or you end up paying the GBP cost of a mechanic.

**Comment by Malgover** [comment]
> Changelog should be "imageadd: new riot armor sprites", by using add it gets wrongly tagged as a mechanic and either someone removes the tag manually or you end up paying the GBP cost of a mechanic.

I have no idea what GBP is but I updated the changelog.

**Comment by AndroidMK2** [comment]
I very like the sprite, will be easier to distinguish the changeling chitin armor now which pretty much looked like the riot suit covered in blood and some flesh.

**Review by Twaticus — APPROVED** [review]

**Comment by Thunder12345** [comment]
> 
> 
> > Changelog should be "imageadd: new riot armor sprites", by using add it gets wrongly tagged as a mechanic and either someone removes the tag manually or you end up paying the GBP cost of a mechanic.
> 
> I have no idea what GBP is but I updated the changelog.

Fix/Feature Delta, AKA Good Boy Points. Features cost points, fixes and code improvements earn them, the bot yells at you if you make too many features and not enough fixes.

**Pull request merged**
