### PR TITLE
Enables design transfer to autolathe by disk.

### PR DESCRIPTION
**Pull request by octareenroon91**
:cl:
rscadd: New designs can now be added to Autolathes via a design disk. Simply use a disk containing a suitable design on your autolathe.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
I can guarantee no one will use this, but a neat feature nonetheless.

**Comment by Jalleo** [comment]
If only there were better ways coded so far like having multiple designs stored on the disk in a list.

**Comment by KazeEspada** [comment]
Good thought. To bad rnd wont leave their super fort.

**Comment by Jalleo** [comment]
Tbh though cargo could do this with one disk and a R&D console by the autolathe which they could do in less than 5 minuites from roundstart.
Also dosent autolathe refuse any material apart from glass and metal?

**Comment by octareenroon91** [comment]
Yes, this PR doesn't give the autolathe any new materials. This is consistent with the machine's description

**Comment by octareenroon91** [comment]
Proposed additions:
Give autolathe all the materials.
Add a system to import  designs into the autolathe, maybe a laptop.

**Comment by GunHog** [comment]
Limit it to protolathe designs but, let it connect to research network. The RD can block access to things that may be too dangerous to release to the public this way, via the server console.

**Comment by Iamgoofball** [comment]
>**Possibly insist on highest-level reliability.**

Absolutely not. Reliability is an ancient system from ages ago that is 100% horrible to use in practice. Never ever use reliability.

**Comment by octareenroon91** [comment]
I'll code infrastrqcture

**Comment by octareenroon91** [comment]
>iamgoofball
>opposing RNG

I'm a little confused.  In any case, this code is ready to go.

**Comment by Iamgoofball** [comment]
There's good rng and bad rng. Reliability is bad rng

**Pull request merged**
