### PR TITLE
Adds a 1 second delay to moving up and down with the verb/keybinds to disable z-level combat cheese

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Adds a 1 second delay to moving up and down with the verb/keybinds to disable z-level combat cheese

## Why It's Good For The Game

Fighting someone using keybinds to move between z-levels over and over again is damn near impossible. Try it sometimes, it's as bullshit as if we had bombs that were cross-Z-level.

## Changelog
:cl:
balance: Adds a 1 second delay to moving up and down with the verb/keybinds to disable z-level combat cheese
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
This is actually a good change, could make space combat more entertaining on multiz maps

**Comment by Higgin** [comment]
thank God - an end to multi-z flying cheese

just need to do climbing and going between z-levels on climbable objects now

**Comment by HoodMilk** [comment]
Does this effect revenants and ghosts?

**Comment by MrMelbert** [comment]
In its current form it affects all mobs, including cameras (ai) and ghosts

**Review by Ghommie — CHANGES_REQUESTED** [review]
balloon alerts are the better choice for short messages like these.

**Pull request merged**
