### PR TITLE
Adds three new moth wings/markings

### PR DESCRIPTION
**Pull request by FuryMcFlurry**
## About The Pull Request

4 Years ago I created mothpeople, and to my horror it was merged onto TGstation, it was a prank that has gone too far. But mothmen found a (somewhat) warm welcome.
But after its was added, no additional wingstyles or markings were added.
But today marks the time that I learn how to git AND add three whole wing styles and markings.

Here's an close-up to what it looks like.
image

## Why It's Good For The Game

Variety is the spice of life, Adding three more wingstyle with matching markings for mothmen, adds to the spice.

## Changelog
:cl: Fury McFlurry
imageadd: Adds three new moth wings and markings! 
imageadd: They are named: Oakworm, Witchwing, Jungle.
/:cl:

### CODE REVIEW

**Comment by Exavere** [comment]
Entire Group of Moth Mains **BUZZ**.  Looks like a good addition.

**Comment by ATH1909** [comment]
You've performed a great service for mothkind this day.

**Comment by zombiegums** [comment]
Moths are my favourite species on /tg/. These wings are so cute.

**Comment by GuyonBroadway** [comment]
After a few sessions with mister tempgun all mothwings end up the same...

**Comment by AtlasRules** [comment]
i gotta say, the red and blue set look an awful lot like Magnus the Red's wings

i think i've found a new favourite pair

**Comment by HomocidlePancakes** [comment]
Xenos were a mistake.

**Comment by gitbirb** [comment]
red and blue = space american wings. Epic.

**Comment by tmtmtl30** [comment]
oh hell yes, maybe this will give me the inspiration to figure out where exactly i fucked up moth markings and why they don't save

**Comment by FuryMcFlurry** [comment]
@tmtmtl30 I can hook you up with the layers of my sprites, there you can figure it out what I did to get them into a correct possition

**Pull request merged**
