### PR TITLE
Adds Xenobio (BZ) reinforced floor turfs to Xenobiology Secure Pens

### PR DESCRIPTION
**Pull request by Ormebia**
## About The Pull Request
Replaces the `/turf/open/floor/engine` turfs inside all stations' Xenobiology Secure Pens with the `/turf/open/floor/engine/xenobio` turf. This means that they now start full of BZ. This PR also moves or removes various items, tables, and other assorted things in the Secure Pens. This does NOT remove the alien egg spawn, nor does it remove any items which aren't easily replaced (e.g. Nanners).
## Why It's Good For The Game
* Speeds up Xenobio, an infamously slow department
* Xenobio can now focus on breeding slimes without having to constantly worry about feeding every one that they're not immediately using.
* BZ Turfs, as opposed to cans, cannot be harvested without a scrubber setup. As such, it's harder for Cargo, Engineering, or Ordnance to immediately steal the BZ to use in their departments.
* Adds functionality to a part of Xenobio that was otherwise either an abnormally big slime pen or a place to gawk at an alien as it kills you.

This change is precedented, as this is already how Secure Pens on NorthStar are set up.

While the push for departmental cooperation that led to the BZ tank's removal is admirable, I've never once seen Ordnance actually make BZ for Xenobio. As a Xenobiologist, I've asked before, and they've never done it. When Ordnance isn't occupied and I've attempted to make BZ myself, it either takes long enough that the station's already gone to shit, or somebody else takes over Xenobiology. This includes rounds where I have played an RD and announced my intent to return to Xenobio when I am done with Ordnance.

As such, the BZ rarely, if ever, gets made, causing Xenobio, an already time-consuming, RNG-dependent, and frankly, dull department to be even more tedious and not worth the time. I used to semi-regularly make rainbows, while now I'm lucky to even occasionally get to tier 3 slimes on deadpop. Having to take care of every slime you need and kill every one you don't need often results in the Xenobiologist killing slimes that they could've evolved later, simply to not have to spend the space, food, and mental bandwidth on them.
## Changelog
:cl:Sosmaster9000
add:BZ floor turfs in all current station's Xenobio Containment Pens. 
del:Various items (e.g. tables, operating tables, tools, metal sheets, and surgery tools) have been removed from the chambers. 
balance: Xenobiologists now have a BZ-filled containment pen. Don't breathe that!
balance:Some items which either cannot be printed elsewhere or are part of game progression (e.g. teleporter endpoints and, of course, Nanners) have been moved. Alien Spawnpoints are in the same spot.
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
When the bz can was removed from xenonio, the argument was that it would give ordinance something to do to help other parts of the sci department.

I have never seen this done for the benefit of xenobio in a single round.  Even when people did the shells paper(in itself a rare occurrence), they usually make just enough to do the paper, and never bother with xenobio.

It isn't even particularly op, the main benefit is it makes the slimes not move, thus making organising them in the big pen easier.

**Comment by Metekillot** [comment]
> When the bz can was removed from xenonio, the argument was that it would give ordinance something to do to help other parts of the sci department.
> 
> I have never seen this done for the benefit of xenobio in a single round. Even when people did the shells paper(in itself a rare occurrence), they usually make just enough to do the paper, and never bother with xenobio.
> 
> It isn't even particularly op, the main benefit is it makes the slimes not move, thus making organising them in the big pen easier.

It'll also make their AI eval cheaper

**Comment by Elli-Skala** [comment]
May be a good idea to remove the cell chargers/ tables/surgery set ups so it doesn't become a noob trap

**Comment by YakumoChen** [comment]
pre-built changeling gbj

**Comment by Ormebia** [comment]
> May be a good idea to remove the cell chargers/ tables/surgery set ups so it doesn't become a noob trap

Already have!

**Review by Maurukas — APPROVED** [review]
I hate making BZ in particular, and no one has objected. Plus there's a pre-existing subtype specifically for it.

**Pull request merged**
