### PR TITLE
Fix a lot of nonhuman species being unable to strip

### LINKED ISSUE #58495: Ethereals, Plasmamen and many other races cannot use the strip menu
## Reproduction:

1. Be any of the mentioned races
2. Open a strip menu
3. Notice that the buttons are grayed out and the strip window icon is orange

Reproduced on local and live with the following races: Ethereal, Plasmaman, Golems, Nightmare, Abductor, Skeleton and other less common races.  
image

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Fixes #58495. Also splits every inherent_traits list into multiple lines, so that future traits can be added without conflict or hard to read diffs/blames.

## Changelog
:cl:
fix: Fixed a lot of nonhuman species being unable to strip others.
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
#58445 tide goes in tide goes out can't explain that

**Comment by Gandalf2k15** [comment]
Hey, this is pretty important, kinda need to be able to strip :)

**Comment by MrDoomBringer** [comment]
no, I know - I was just making a goof at the bugfix introducing bugs

**Review by Timberpoes — APPROVED** [review]

**Comment by optimumtact** [comment]
> 
> 
> Hey, this is pretty important, kinda need to be able to strip :)

No ERP.

**Comment by interestingusernam3** [comment]
UFO PORNO

**Pull request merged**
