### PR TITLE
removes fungal tb from traitor

### PR DESCRIPTION
**Pull request by LanCartwright**
Don't worry, I'll add in something else later.

### CODE REVIEW

**Comment by Kholdgrave** [comment]
God bless this PR

**Comment by francinum** [comment]
#15016

**Comment by Niknakflak** [comment]
#15016

**Comment by tkdrg** [comment]
Remove `/obj/item/weapon/storage/box/syndie_kit/tuberculosiskit` as well

**Comment by LanCartwright** [comment]
total changes:
Fungal TB stages from 4 to 5.
Warning symptoms start at stage 2.
Stage 3 pushed to Stage 4.
Stage 4 pushed to newly added stage 5.
Blood vomiting removed.
Vomiting now occurs at stage 5.
Majority of actual symptoms occur at stagees 4 and 5.
Removes uplink kit and uplink kit data.

**Comment by Niknakflak** [comment]
Grenade uplink kit is still in

**Comment by LanCartwright** [comment]
read title.

**Comment by tkdrg** [comment]
Sure, we can give this a try. If it is still bad then we can remove it.

**Pull request merged**
