### PR TITLE
Swarmer Balance Changes

### PR DESCRIPTION
**Pull request by IndieanaJones**
## About The Pull Request

This PR updates Swarmers, giving them some much-needed balance tweaks and updates to fit the current state of the game.

**WHAT WAS WRONG WITH SWARMERS**

- No counterplay.  Swarmers currently do not announce their arrival at all (though there appears to be busted code here to make it only announce 25% of the time?  I've never heard it go off.), usually only seen by the AI once they're done eating the sat.  Once found out, they could easily use the vents to be anywhere and everywhere, making stopping them a nigh impossible task and almost always forcing a shuttle call.

- Outdated balancing.  Swarmers were never updated with the changes made to stamina damage and disablers sans a recent PR to their structures, making their disabler shots and melee attacks basically worthless.

**THE CHANGES**

NERFS:
- Swarmers now have an announcement shortly after spawning which will always go off.  The time has been set to give the spawned swarmer enough time to leave the gateway area before being outed.
- Swarmers now have GPS signals (Obscure Signal), preventing them from hiding in shoddy locations in maint and making entire armies while everyone is oblivious.
- Swarmers can no longer break the Ore Silo

BUFFS:
+ Swarmers have had their damage numbers tweaked.  They can fire twice as fast, and their stamina damage melee has been buffed from 15 flat stamina damage to 20-40 stamina damage.
+ Swarmer building costs have been cut down across the board.  Traps and barriers now cost 4 resources each down from 5 each, and replicating costs 40 resources down from 50.

OTHER:
- The swarmer event has been buffed from 7 weight to 8 weight.

Note, I'd also like to register them up for Dynamic's midround antagonist spawns, but as a PR is currently being pushed to solve issues with that system, those changes will not be included in this PR.

## Why It's Good For The Game

Understandably, swarmers are commonly referred to as an example of a roundender.  While round-ending events are fine and dandy, a fully-serviceable crew operating under good circumstances should be able to stave off such a threat, and only forced to leave should this not be true.  Swarmers in their current state, unless the swarmers are very stupid, cannot be stopped and will force a shuttle call guaranteed, regardless of the current state the station is in.  This PR attempts to make the swarmer threat have counterplay from the crew's side, while buffing swarmer capabilities to be able to be more confrontational with the crew.  Hopefully, this should make swarmer gameplay on both sides more interesting.

## Changelog
:cl:
balance: Swarmer threats are now announced to the crew, and swarmers themselves have received a number of software updates from an unknown source
/:cl:

### CODE REVIEW

**Comment by IndieanaJones** [comment]
Note, I am entirely open to changing what this PR entails if good enough suggestions are brought up.  Swarmers are in an odd spot as of now, so some other opinions would be nice.

**Comment by necromanceranne** [comment]
If they can't vent crawl I'd honestly buff their health even more. They literally will get swarmed out the gate (haha get it because they spawn out of the gateway), so they will need to basically stun their way out of it to survive.

**Comment by ATH1909** [comment]
Swarmers still have a shitty maxHealth, though, no? How do you expect that first swarmer to make it past a crowded hallway of people into Maintenance (without intrinsic Maintenance access, IIRC, which means that you're gonna have to break down a door into Maint too) without getting bashed or shot? How do you expect that first swarmer to find the two minutes or so they need to sloooooooowly gain enough mats (you can only eat, like, one sheet per click, even if you're clicking on a stack of 50 sheets) to reproduce (let alone enough time to actually sit still and go through that reproduction process) before they get tracked down by someone who just printed off a GPS (or even just someone who followed their trail of broken doors into maint)?

**Comment by IndieanaJones** [comment]
I'd be open to buffing their max health further for compensation to being more actively in the line of fire.  Note that barrier and trap costs are reduced, so there is a timeframe for the swarmer to eat things in the gateway room before needing to move out.

**Comment by IndieanaJones** [comment]
Addendum to the PR: Swarmer health buff changed from 50 hp to 120 hp.

**Comment by wesoda25** [comment]
If you just removed their ventcrawl and made sure the announcement always went off this would be fine. I do not look forward to the little fuckers being harder to kill.

**Comment by IndieanaJones** [comment]
> double edit: actually I don’t care enough to consider what a perfect balance for swarmers would be but I do know that swarmer combat is cancer already and I do not look forward to them being able to double shot and tank a ton of hits. Aren’t they supposed to be fragile?

Yes, but as of current, swarmers also come paired with high evasiveness which is entirely unmatched.  By removing the vent crawling, they'll be forced into actual combat more often, meaning they'll need to be able to have a better fighting chance.

**Comment by PKPenguin321** [comment]
the nerfs are too hefty. you're taking away their element of surprise, their quick getaway method, and allowing them to be easily tracked. also, considering they typically spawn in the gateway, being unable to ventcrawl means that they will be unable to actually leave without being spotted before their presence is announced. i'll be surprised if they ever reproduce more than once.

they should keep ventcrawl

**Comment by IndieanaJones** [comment]
> the nerfs are too hefty. you're taking away their element of surprise, their quick getaway method, and allowing them to be easily tracked. also, considering they typically spawn in the gateway, being unable to ventcrawl means that they will be unable to actually leave without being spotted before their presence is announced. i'll be surprised if they ever reproduce more than once.
> 
> they should keep ventcrawl

Alright, perhaps then since they have a signal now, we can revert the health to current live and give them back ventcrawl?  The only issue is that they can stall forever in the vents (though xenos can also technically do this) unless someone roasts them alive, which doesn't always happen.

**Comment by Kelenius** [comment]
I think they should be able to ventcrawl. They have very limited mobility without it. Despite the name, they are outnumbered on the station, they are very weak in combat, and even if they knock someone out, all they can do is delay them for a few minutes. This makes them too easy to kill.

**Comment by SkeletalElite** [comment]
Either revert health change and give vent crawl or make them spawn somewhere safer like maint.

**Comment by IndieanaJones** [comment]
Alright, we're going with old health values and vent crawl.  I think being able to track them will certainly help fix their "unstoppable" status for now, though live feedback might be the best way to gauge what other changes may or may not be necessary.

**Comment by OverlyGeneric** [comment]
A good step.

I do wish that swarmers were more like the lavaland ruin than a rather tedious zerg rush enemy.

**Comment by GuillaumePrata** [comment]
I personally dislike both the GPS, Buffed Stats and loss of ventcrawl, Swarmers end the round for 1 reason, they walk into the Vault and eat the silo, then they walk into the Protolathes and eat em too.
When this happens, no one wants to stay on the round anymore since most fun projects need either mats or tech, so people just want a shuttle call so they can have their fun next round.
I would personally blacklist these machines from being consumed and leave em mostly as is, now they cant destroy the station productivity in 20 seconds after the spawn but they can still slowly devour the station if left unchecked, which is what their intended goal is IMO, be a nuisance to the organics so they leave if they cant kill em, not because they cant use the protolathe.

**Comment by IndieanaJones** [comment]
> I personally dislike both the GPS, Buffed Stats and loss of ventcrawl, Swarmers end the round for 1 reason, they walk into the Vault and eat the silo, then they walk into the Protolathes and eat em too.
> When this happens, no one wants to stay on the round anymore since most fun projects need either mats or tech, so people just want a shuttle call so they can have their fun next round.
> I would personally blacklist these machines from being consumed and leave em mostly as is, now they cant destroy the station productivity in 20 seconds after the spawn but they can still slowly devour the station if left unchecked, which is what their intended goal is IMO, be a nuisance to the organics so they leave if they cant kill em, not because they cant use the protolathe.

While this is fine and dandy, keeping swarmers the same while removing their ability to eat the silo doesn't solve their core problems.  In such an instance, while they can't immediately make every department useless, you still have the issue of them b-lining to maint to multiply at insane speeds while nobody knows they even exist, which will cause a shuttle call because with vent crawl, you will never kill all the swarmers.  One will always make it to some obscure location, multiply a bunch, and the whole process restarts itself.


> A good step.
> 
> I do wish that swarmers were more like the lavaland ruin than a rather tedious zerg rush enemy.

This is also an interesting point.  Something this PR doesn't address right now is the fact that swarmers aren't really swarmers until they've been around for a while.  In reality, I'd say spiders actually do the niche of swarming better than swarmers do currently and even with this PR.  So, I propose another alternate idea:

- Swarmer machine spawns in maint, uses xeno spawn locations (only bad one is the plasma container on Box)
- Ghosts interact with the machine to join into a queue, machine spawns swarmers one at a time, following the queue order
- Swarmers lose ventcrawl, but keep their current stats otherwise
- Swap the Swarmer announcement to the one shared by xenomorphs and random spider spawns

Ideally, this would force the swarmers to work together to expand out from the location of the machine, eating everything in their path and actually, y'know, swarming.  However, this might be a deviation too far from the current design, so opinions on this would be appreciated.

**Comment by TheMidnightRose** [comment]
The Swarmer Megafauna beacon is still in the code, making it able to spawn to spawn ghosts off of it, limiting them to only the blue/gray in the queue would be interesting.

**Comment by IndieanaJones** [comment]
> The Swarmer Megafauna beacon is still in the code, making it able to spawn to spawn ghosts off of it, limiting them to only the blue/gray in the queue would be interesting.

Setting up the backend for such a system would be rather simple, I'd probably just use the same sprite and code it myself.

**Comment by GuillaumePrata** [comment]
> While this is fine and dandy, keeping swarmers the same while removing their ability to eat the silo doesn't solve their core problems. In such an instance, while they can't immediately make every department useless, you still have the issue of them b-lining to maint to multiply at insane speeds while nobody knows they even exist, which will cause a shuttle call because with vent crawl, you will never kill all the swarmers. One will always make it to some obscure location, multiply a bunch, and the whole process restarts itself.
Oh I completely agree with that, in my opinion a rework for what you suggested with a Swarmer "Replicator" machine that ghosts can use would be the best, then we can remove Vent crawl and spawn em in maints or if I could just dream without thinking about coding, a small escape pod sized 'ship' docking in some wall outside the station.
If swarmers can spawn outside of the gateway I agree that Vent crawl is bad and just leads to infinite chases.

**Comment by shellspeed1** [comment]
Why not just make swarmers vulnerable to emps?

**Comment by IndieanaJones** [comment]
> Why not just make swarmers vulnerable to emps?

They already are, actually, it just knocks them down to 1 health.

**Comment by ATH1909** [comment]
> > I personally dislike both the GPS, Buffed Stats and loss of ventcrawl, Swarmers end the round for 1 reason, they walk into the Vault and eat the silo, then they walk into the Protolathes and eat em too.
> > When this happens, no one wants to stay on the round anymore since most fun projects need either mats or tech, so people just want a shuttle call so they can have their fun next round.
> > I would personally blacklist these machines from being consumed and leave em mostly as is, now they cant destroy the station productivity in 20 seconds after the spawn but they can still slowly devour the station if left unchecked, which is what their intended goal is IMO, be a nuisance to the organics so they leave if they cant kill em, not because they cant use the protolathe.
> 
> While this is fine and dandy, keeping swarmers the same while removing their ability to eat the silo doesn't solve their core problems. In such an instance, while they can't immediately make every department useless, you still have the issue of them b-lining to maint to multiply at insane speeds while nobody knows they even exist, which will cause a shuttle call because with vent crawl, you will never kill all the swarmers. One will always make it to some obscure location, multiply a bunch, and the whole process restarts itself.
> 
> > A good step.
> > I do wish that swarmers were more like the lavaland ruin than a rather tedious zerg rush enemy.
> 
> This is also an interesting point. Something this PR doesn't address right now is the fact that swarmers aren't really swarmers until they've been around for a while. In reality, I'd say spiders actually do the niche of swarming better than swarmers do currently and even with this PR. So, I propose another alternate idea:
> 
> * Swarmer machine spawns in maint, uses xeno spawn locations (only bad one is the plasma container on Box)
> * Ghosts interact with the machine to join into a queue, machine spawns swarmers one at a time, following the queue order
> * Swarmers lose ventcrawl, but keep their current stats otherwise
> * Swap the Swarmer announcement to the one shared by xenomorphs and random spider spawns
> * The machine handles player spawns, players however can spawn in AI-controlled swarmers
> 
> Ideally, this would force the swarmers to work together to expand out from the location of the machine, eating everything in their path and actually, y'know, swarming. However, this might be a deviation too far from the current design, so opinions on this would be appreciated.

I feel like this'd just turn swarmers into glorified blobs.

I think just blacklisting the ore silos and the lathes from being eaten by swarmers should be enough, tbh. If you're having problems dealing with their ventcrawling, weld the vents and let the atmos techs do their thing.

**Comment by IndieanaJones** [comment]
> I feel like this'd just turn swarmers into glorified blobs.
> 
> I think just blacklisting the ore silos and the lathes from being eaten by swarmers should be enough, tbh. If you're having problems dealing with their ventcrawling, weld the vents and let the atmos techs do their thing.

Ultimately, my current solution still doesn't really fix the issue that swarmers don't swarm at all.  Rather, they're much more effective as individual units then as a whole.

**Comment by Shadowflame909** [comment]
With swarmers being trackable via beacons now, and borgs being unequivocally their counter with very little for swarmers to stop them, outside of running or making a trap that the borg would have to run into...

Can we get lethal red swarmers being swarmer creatable? 👀 

This, or removing the build times swarmer shields/traps have, so they're huntable. But not sitting ducks.

I'm mainly just worried about how easy it'll be for mining borgs to open their GPS device and go swarmer hunting.

**Comment by IndieanaJones** [comment]
> 
> 
> With swarmers being trackable via beacons now, and borgs being unequivocally their counter with very little for swarmers to stop them, outside of running or making a trap that the borg would have to run into...
> 
> Can we get lethal red swarmers being swarmer creatable? 👀
> 
> This, or removing the build times swarmer shields/traps have, so they're huntable. But not sitting ducks.
> 
> I'm mainly just worried about how easy it'll be for mining borgs to open their GPS device and go swarmer hunting.

Doesn't that ultimately defeat the point of swarmers' gimick of being a "technically harmless" antagonist though?

**Comment by Shadowflame909** [comment]
Yeah, you're right...

But to be fair I have no clue who even made swarmers. So if they are not being updated...

It's alright to change the gimmick.

**Comment by IndieanaJones** [comment]
Added: Swarmers can no longer destroy the Ore Silo.

**Comment by ATH1909** [comment]
> Added: Swarmers can no longer destroy the Ore Silo.
> 
> I'm tempted to make an alternate PR to my this PR using the idea above. While I understand it treads similar ground to blob, having blob which mostly relies on the efforts of a single player to swarmers, which is the work of several players, along with being more mob-focused instead of the blob's more structured design, I think it might work better than this.
> 
> You could also argue that swarmers currently tread too close to xenos and spiders (horde, fucks up station, hard to entirely expel), though I'm curious what people think. Is the swarmer printer concept worth taking a crack at?

I mean, blobs also involve multiple players (blobbernauts, blob zombies, etc.)...

**Comment by ATH1909** [comment]
One big issue that I see with the swarmer printer idea is that swarmers currently can't really do much to simplemobs and borgs, so all it'd take to destroy the swarmer printer would be a single competent borg/xenobiologist.

**Comment by IndieanaJones** [comment]
> 
> 
> One big issue that I see with the swarmer printer idea is that swarmers currently can't really do much to simplemobs and borgs, so all it'd take to destroy the swarmer printer would be a single competent borg or xenobiologist.

What I could do to as a solution is make swarmer melee stun cyborgs, and to solve the issue with simple mob attackers, I could make the swarmer bolts more custom and have them apply a freeze effect to simplemobs which long enough to teleport them away.

**Comment by ExcessiveUseOfCobblestone** [comment]
Every Ventcrawler gets looked at like pyro slime, swarmer, vampire, etc. because of ventcrawling

When are we just gonna make Ventcrawling a bit more sensible rather than all-access unless you start ruining the atmos system 😢

**Comment by Kelenius** [comment]
Vents are easy to weld.

**Comment by Shadowflame909** [comment]
> Every Ventcrawler gets looked at like pyro slime, swarmer, vampire, etc. because of ventcrawling
> 
> When are we just gonna make Ventcrawling a bit more sensible rather than all-access unless you start ruining the atmos system 😢

when we add wall crawling and give that to the npc roach mob to buff them

**Comment by Fikou** [comment]
> Swarmers can no longer break the Ore Silo

wow they now go from annoying roundender to completely harmless!

**Comment by lordpidey** [comment]
Alternative balancing approach I had.

A concept called "Swarm pylons"

Swarm pylons have a range of X tiles (To be determined.  5?)

Swarmers can only deconstruct/absorb/etc... when within range of a swarm pylon.

Swarm pylons cost resources, and can only be built within range of another swarm pylon.  (There will be some mechanic to place the first one.)

Swarm pylons can be destroyed with ordinary damage.  (HP to be determined)

This mechanic will soft confine the swarmers to an ever growing area, so you don't need to worry about them being literally everywhere.  It also means that even if the swarmers are all hiding in vents, the crew can still fight back and win by destroying all of the pylons, as once the pylons are all destroyed, no more can be built, and thus no more swarmers can be built.

I'll try making a PR that does this over the weekend.

**Comment by TheVekter** [comment]
I would like justification for the vault change, please.

**Comment by IndieanaJones** [comment]
> I would like justification for the vault change, please.

You can't stop them from eating the ore silo.  Unless they put off the easiest and most rewarding machine off until someone gets into the vault and welds it, which is unlikely, a swarmer spawn will always result in the ore silo being destroyed, which guarantees the round will have to end.  This is the problem with swarmers and labeling things as round-enders.  For example, xenos are roundenders, but you can win against them and continue doing what you're doing if the crew is not in shambles.  Swarmers, on the other hand, cannot be stopped.  By the time you know what's happened, they've already eaten the silo and all the ores in it, meaning that even if you somehow managed to kill every single swarmer despite their ventcrawl ability, until you build a new silo AND fill it with ores, a bunch of jobs are pretty much rendered void.  Due to this, the second a swarmer spawn is known, the shuttle will be immediately called after.

I will admit this isn't the most elegant solution, but its one that I wanted to put out there.  I'm working on an alternative to this PR which would look to solve these issues by changing how swarmers work.  While I understand your round-ender argument on Discord, I firmly believe a properly maintained crew should be able to handle any antagonist's onslaught and come out being able to continue their jobs, instead of immediately calling the shuttle when one spawns because "we're already fucked anyway".

**Comment by IndieanaJones** [comment]
Going with the alternative idea.

**Comment by lordpidey** [comment]
Oh god, my idea?  I was busy and didn't do it.  Want me to start writing it, or are you working on it, @IndieanaJones ?

**Pull request closed without merging**
