### PR TITLE
Fixes mecha drifting.

### PR DESCRIPTION
**Pull request by AnturK**
Also replaced spawn with timer since i was already touching this.

### CODE REVIEW

**Comment by Spaceinaba** [comment]
gone are the days of GAS GAS GAS

**Comment by RemieRichards** [comment]
mutli mech drifting

**Comment by optimumtact** [comment]
why not make it a world timer, then you don't need the sleep at all

**Comment by AnturK** [comment]
Fair point, i'll switch it in a moment.

**Pull request merged**
