### PR TITLE
Fixes map_config validation

### LINKED ISSUE #32201: Map config doesn't load, can't change map to anything but box.
Options aren't even there to change it

### PR DESCRIPTION
**Pull request by Cyberboss**
Closes #32204 
Fixes #32201

### CODE REVIEW

**Comment by SpaceManiac** [comment]
`allow_custom_shuttles` is being set to false by default and none of the map configs set it to true anymore.

**Comment by Cyberboss** [comment]
None ever did iirc

**Comment by SpaceManiac** [comment]
Every map previously set `"allow_custom_shuttles": "yes"` except for RuntimeStation setting it to `"no"`, now no map sets it and it defaults to false, utterly disabling purchasing shuttles. Relevant lines in the communications console:

https://github.com/tgstation/tgstation/blob/8d6bf17c6cd3eb3bd78b8a007379b35d31c7deba/code/game/machinery/computer/communications.dm#L472-473

**Comment by Cyberboss** [comment]
Oh fuck I set it backwards

**Pull request merged**
