### PR TITLE
replaces syndie pistol with .22 pistol

### PR DESCRIPTION
**Pull request by pudl**
-removes the syndie pistol from the uplink
-adds the .22 pistol box to the uplink, 8 tc.
-removes the revolver from the uplink
-adds the revolver box to the uplink, changing the revolver's price from 13 tc to 10.
-removes .357 and 10mm ammo from the uplink
-.22 pistol box contains a .22 pistol and 4 magazines of ammo for it, each holding 10 rounds
-revolver box holds the same except with its own kind of ammo
-adds .22 bullet casing, magazine, and weakbullet4
-.22 pistol holds 10 bullets at a time, each dealing 10 damage. the pistol is automatically suppressed, thus it shoes no messages in the chat and it plays the suppressed sound. this makes it a good stealth weapon that can kill someone in very close range. it can also be held in your pocket.
-renames detective's "revolver" to ".38 revolver"
-renames syndicate "revolver" to ".357 revolver"
-adds a single new box sprite for the new gun

http://puu.sh/g1E05/c165dac78c.png gun sprite credit to wjohnston

### CODE REVIEW

**Comment by paprka** [comment]
:-1: I have already said why. We have a silenced pistol already, you can just make the syndicate pistol spawn with a suppressor.

This severely upsets the balance of the game and the uplink's firearms I've worked a long time on trying to perfect.

**Comment by WJohn** [comment]
10 damage is unbelievably pathetic. Also 10 TC is way too cheap for something that ridiculously deadly.

**Comment by Cheridan** [comment]
Not seeing the point to all this.

**Comment by SconesC** [comment]
I don't understand the (unstated) reasoning behind these changes in the first place

Also why the ever-loving fuck would revolver drop the 10 tc holy shit, it's one of the strongest traitor items and its high as fuck cost is what keeps it balanced - but wait there's more shit? for 10 tc I get a 2-shot crit weapon with a 7-shot magazine and 4 EXTRA MAGS FOR IT?

do you even play the game? seriously, i never thought i'd ask that in sincerity, but what the fuck

furthermore what the hell is the idea behind the pistol, suppressed 10mm is fine as-is, and 10 damage is LAUGHABLE

**Comment by PKPenguin321** [comment]
Traitor's guns are pretty balanced as is, each having their own strengths and weaknesses. This PR makes one extremely underpowered and the other extremely overpowered.
Not only does this upset the balance of the traitor's guns, however, but the balance of the entire uplink, as a revolver would be almost a guaranteed buy with every traitor build with low price for stupidly high damage output. Meanwhile, the pistol will literally never be bought because it is a ranged fire extinguisher.

**Comment by paprka** [comment]
I'll probably end up adding the suppressor to the stechkin by default since you really shouldn't have to buy it separately as a traitor, wheras nuke ops spawn with an unsuppressed one as a backup surplus kinda.

**Comment by An0n3** [comment]
As a proud American patriot it makes me feel bad to admit that while someone is trying to add cheaper guns and more ammunition to the game, it's a poor change .  The bald eagles soaring through my veins cry that I've forsaken my proud ancestors who have enjoyed shooting eachother for centuries as a time honored tradition.  But yeah.

This change adds one completely useless item that already has a flavor analog (that is balanced) and makes an already great item ridiculously powerful in almost every way.

**Comment by Durkel** [comment]
The pistol you're trying to add is unbelievably weak, so much so that a floor tile would be a better weapon.

Also, reducing the cost of the traitor revolver is a terrible idea, it crits in two hits.

The best course I could see here is just not change anything, The stetchkin (They're just labeled syndicate pistols I think now??) Has a decent amount of damage to it to be viable, if you really wanted to change something then you should just make it silenced by default.

:-1:

**Comment by mrpain666** [comment]
DONT TAKE MUH GUNS

**Comment by An0n3** [comment]
I may be wrong but if I remember right changing the 10mm to this means it will do more damage if you just beat people with it, and as much damage as shooting someone if you just throw it at them.

**Comment by hornygranny** [comment]
not good enough

**Pull request closed without merging**
