### PR TITLE
Changes flash Paralyze to Knockdown

### PR DESCRIPTION
**Pull request by Higgin**
## About The Pull Request
picking up the dropped rifles of #78515 and #81618 and making only one small, measurable change that should test the general principles while making life better if they're proven true:

does what it says on the tin: makes flashes Knockdown rather than Paralyze

this will be successful if people report more close fights where flashes were involved and feel better about playing on both sides of flashing/getting flashed

## Why It's Good For The Game

hardstun rocket-tag combat bad. opportunities for counterplay and combos good. 

Paralyzes
- basically prevent you from doing anything. anything.

Knockdowns
- let you try to deploy your flash protection before the follow-up if the opponent's just trying to use the flash
- let you try to crawl, juke, and make your opponent's life a little less simple
- give you an actual choice: do I try to scream HELP immediately after the flash before I get taken out, or try to use an item, swing back, or wriggle out?
- still disarm you if you're standing which is pretty cool I think
- still let you stamcrit some goofball crawling at you even if they keep crawling

doesn't change how mounted flashes or portable flashers work. still 10 and 8s Paralyzes respectively.

not a moth buff because they still can't wear sunglasses to no-sell the flash entirely ha ha goofy bug

## Changelog

:cl:
balance: personal flashes now Knockdown rather than Paralyze direct targets.
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
26th times the try!

**Comment by DrDiasyl** [comment]
Thumbs up just for the dedication.

But in any way, I think flashes are balanced due to how easy they are to counter (face away from the attacker or put on some shades), there is no need to remove their paralyze.

**Comment by Vect0r2** [comment]
borgo nerf :(

**Review by ZephyrTFA — APPROVED** [review]
I'm okay with making it a knockdown instead of a full paralyze, we'll see how this affects usability and balance

**Pull request merged**
