### PR TITLE
Replaces PubbyStation with OmegaStation.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

This, as the title says, replaces PubbyStation with OmegaStation. 

Nothing has really changed from the OmegaStation PR i made previously except that it's on its own branch and Pubby gets removed.

I'm a bit lazy, so i copypasted the original PR info from the old PR at #53495, which reads as follows:

This, well, readds OmegaStation back to the game. I've spent the past month updating it, most of the excluded areas and all of the missing non-head jobs have been added in, many of the issues with the map have been fixed, and i think it's more or less ready for rotation.

Here's a screenshot:[https://amel.pw/trevie/screenshots/s11.png](https://amel.pw/trevie/screenshots/s11.png)

Credits go to me, of course, Okand and whoever else contributed to the map, and the developers of Skyrat's version of Omega, for giving me ideas on where to put things as well as the Toxins Lab and Quartermaster's Office copypasted from their version of the map.

I highly recommend that this gets test merged first, as there might be bugs with the map that need to be ironed out.

## Why It's Good For The Game

Right now, i don't think /tg/ has any real lowpop maps. Pubby is the only "low-pop" map in rotation, and not only is it as large as a medium-pop map, it doesn't really serve low population counts any better than, for example, Meta does.

Omega is more tailored for low population counts than Pubby is, and i think it will do well on low population servers such as Campbell, small or private servers, or during graveyard hours on more populated servers.

## Changelog
:cl:
add: NT's decommissioned "Omega" line of stations have been put back into use.
del: NT's "Pubby" line of stations have been decommissioned 
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
this feels low quality compared to pubby, and also for a way way lower population. Honestly deserves to be added in rather than removing pubby for it (and also give pubby an overhaul or replace it with something of the same size since pubby's got issues from being rather old).

**Comment by CRITAWAKETS** [comment]
The supermatter crystal is a supermatter shard unlike every other map. I recommend fixing that since the difference is cosmetic.

**Comment by Cartographer-D** [comment]
@CRITAWAKETS if you make a list of Pubby's "old" problems, I will take a look at it. I intend to overhaul Pubby over the next year so that would be very helpful.

**Comment by wesoda25** [comment]
I think pubby is definitely a higher quality map, however I can’t deny that we don’t really have a lowpop map and pubby is on the chopping block. Sad but probably for the best. Hopefully down the road a good lowpop will emerge.

**Comment by zxaber** [comment]
I think what bugs me the most about Omega is the two-tile-wide halls. Everything feels so cramped and visually busy. I get that it's sorta the point of a small station, but it makes it not fun to try and navigate.

**Comment by sergeirocks100** [comment]
I heard that it uses a shard because a regular SM crystal could cause a larger explosion if it delaminated, and the station seems to generate power just fine with the supermatter shard, so i'm leaving it alone for now.

I'll go ahead and try to do something about the turbine issue by removing the plasma window.

The map uses all the old piping it had when it got removed in 2018, it would be a pain in the ass to replace it all, but i do plan on replacing it if it gets merged.

While i'll look into the cameras and possibly the heat exchange pipes for the kill room, your other xenobiology suggestions would require pretty heavy redesigns that i'm not sure are feasible.

Based on your suggestion, i decided to give the toxins storage room a nitrous oxide tank and a carbon dioxide tank as well as a huge air scrubber.

I'll go ahead and sprinkle some dust on the abandoned bar, but i don't really see the issue with the dispensers. Every other map except for Meta has a booze dispenser in their bar, and they all seem to be fine. 

I would put the atmos tanks in space, but there's really no room to push them out, especially the southern ones.

The SM seems to do just fine with the single emitter.

While the 2 tile wide hallways bother me a little too, i don't know how to widen them without doing extensive redesigns to the map.

**Comment by Tlaltecuhtli** [comment]
low pop stations which have as gimmick “ cramped out, less features and an eyesore”  harm the servers as they just make people jump ship when they are selected. at least other attempts at “ low pop maps” like shipstation provide uniqueness and interesting gimmicks which make people choose the time zone low pop server over the ones with pop at the time, giving a better snowball pop effect

**Comment by uomo91** [comment]
>Can the station even run on a singular emitter?

Yes.

**Review by ghost — COMMENTED** [review]
Ok time to review the shit out of this:

1. For the love of god make this a normal sm crystal, because you can unwrench sm shards with a wrench and move them around.
image

2. Put more than a single emitter, three minimum.
image

3. Move the engi lockers and clothes vendor out of the sm chamber, there tends to be radiation in there.
image

4. This won't put the scanner goggles inside the suit storage.
image

5. One person with a fire axe can flood atmos with every single tank by breaking the windows, please move them into space.
image

6. Don't give the captain the HoS' energy gun.
image

7. Why does cargo get a special room at evac, this just blocks off another door from the public.
image

8. Why do these maint shutters exist into space?
image

9. More of a suggestion, but these two rooms should be directly connected, without a hallway between them.
image

10. Hydro can't reach this crate in the corner without moving lockers and stuff around, and with that little space it's gonna be an annoyance.
image

11. The library needs a skillchip implanter.
image

12. Replace these anti-breach shield generators with shield wall generators.
image

13. You might not want to just put a second null rod right next to the chaplain's office.
image

14. Xenobio needs a cytology locker, and associated supplies, like a microscope.
image

15. Maint needs loot_site_spawner objects placed around in it, for cytology to be able to do their job.
image
They look like this.

16. All of the atmos pipes outside of atmospherics itself should be repiped to layer four for supply pipes, and layer two for scrubbers pipes.

17. A last note, but more of a suggestion, two tile wide main hallways make the station feel needlessly cramped, and nobody is going to like it, I would suggest changing that.

**Review by ghost — CHANGES_REQUESTED** [review]
Also I know it's supposed to be this station's quirky gimmick, but please god put heads of staff in.

**Comment by sergeirocks100** [comment]
Again, i heard that it uses a SM shard because the regular SM could destroy more if it delaminated, and i don't think anybody will be suicidal enough to steal the SM, so i see no reason to replace it.

The single emitter seems to be fine, and there isn't any room to put any more.

I moved the lockers and the EngiDrobe outside of the engine room.

I would move the atmos tanks out into space, but there's no room to move them out, especially the southern ones that are against the Secure Storage.

the Head of Security doesn't exist, so there's no HoS locker to put the laser gun in, and it wouldn't make sense to put a traitor item in general security, so i don't see the problem with it being in the Captain's locker.

I'll go ahead and merge the Cargo Office into the rest of Evac.

I don't know why the maint shutters into space are there, but i see no reason to remove them.

I could join the Robotics Lab and the Mech Bay together, but it would require extensive redesigns to do so, and it's more trouble than it's worth.

I'll go ahead and add a Skillchip implanter to the library.

I'll replace the shield generators as well.

The sword is a fun little secret, and it wouldn't make sense to remove it.

I already added a cytology locker, in fact, you can see it in the picture you posted.

There's already a loot site spawner or two on the station, but i suppose it wouldn't hurt to add a few more.

While i do intend on redoing the pipes later if the map gets merged, i see no point in redoing them right now when the old pipes work just fine and it would be a pretty large task to do.

While i agree with you on the 2 tile hallways being somewhat cramped, it would require extensive redesigns to the station to widen them, and again, it would be too much trouble to do at this time.

I purposefully left the heads out because the station does not have room for their offices, and it would increase the chances that someone who would join as one of the other heads on another map would join as Captain or HOP.

And if there's one thing lowpop rounds are always short on, it's people who can actually lead the station without hacking open the Captain's locker with a fire axe.

If i do add in the other heads, the best you can hope for is their offices being in the bridge, akin to how Cere did it, or they will simply spawn at their respective consoles at the Bridge.

**Comment by Paxilmaniac** [comment]
The captain already gets the antique laser gun, now that you throw the hos gun in there, that makes uh, let's see...

Five traitor objective items in one room, roundstart.

**Comment by sergeirocks100** [comment]
If the Captain's Office isn't suitable for it, then where else should i put it?

**Comment by Paxilmaniac** [comment]
Make it the warden's job

**Comment by sergeirocks100** [comment]
It seems as if every time Pubby gets updated, it causes merge conflicts because the .dmm doesn't exist.

I can't make people stop working on Pubby, so i will just have to leave a dummy .dmm there for now, to remove either when the PR gets merged, or in a separate PR afterwards.

**Review by kriskog — COMMENTED** [review]
Hard disagree from me. Replacing pubby with a dedicated low pop map gives less high pop variety, and I think that is a bad thing. If we only get to keep four maps supported, pubby is a better candidate than omega.

**Comment by EOBGames** [comment]
Hello, so an alternate PR has been made to this one (see #54020) that will replace Pubby with Kilostation. In the interests of not disappointing anyone (or at least trying not to), I'd like to give you an opportunity to talk things over with the creator of the other PR and see if an agreement can be reached on which should go forward.

**Comment by optimumtact** [comment]
@kriskog don't use the review functionality for opinion comments you boomer

**Comment by 81Denton** [comment]
Agreeing with what kriskrog said, both regarding high pop variety and Omega's poor design. I'm getting the feeling that people who are pro Omega have never had the displeasure to play on it and witness 70%+ crew members killing themselves at the HoPline roundstart.

**Comment by sergeirocks100** [comment]
I don't hate Kilo, but we would be left with no lowpop maps if it took Pubby's place.

I do wish the author the best of luck, though.

As far as i know, suicide HOPline hasn't been a thing in a pretty long time, or at least i haven't seen it personally, so i think it should be fine.

**Comment by Tlaltecuhtli** [comment]
>As far as i know, suicide HOPline hasn't been a thing in a pretty long time, or at least i haven't seen it personally, so i think it should be fine.

because box and omega got removed

**Comment by EOBGames** [comment]
Apologies for the slow response to this PR.
I'd like to start by thanking you for your work on the map, and saying that I respect that it's taken you a while to work on. With that said, I'm going to have to reject this PR.
Given our strict limit of 4 in-repo maps, I don't believe it's wise to make 1/4 of our map list exclusive to lowpop. Additionally, I feel that omega has a number of problems that are too integral to its design for it to work effectively as a TGStation map, as has been noted above. If the out-of-repo map changes go through, I would welcome it in that capacity, but as an in-repo map, it's not going to work out.

**Pull request closed without merging**
