### PR TITLE
Unique ambience for virology!

### PR DESCRIPTION
**Pull request by DrDiasyl**
**THIS IS NOW IN A NEW PR #69407**

## About The Pull Request

Now virology has a new Plague Inc inspired ambience sound (Made by myself in FL studio so no licensing problems). It has it's own define, and is used in the virology area.
There is 3 sounds, you can listen to them there:

https://user-images.githubusercontent.com/42353186/183266002-b0a92f8e-ca70-4b9d-ba7d-2aabf0998c52.mp4

Each of them weights ~100 KB which is not alot.

## Why It's Good For The Game

First of all, medbay literally only has only one ambient sound, and only 1 area of medbay had unique ambience (Morgue). It's neat to have more areas with unique ambiences, especially when that area on almost every map is seperated from the rest of medbay.

With this mysterious ambient, every virologist will feel himself making something _dangerous and scary,_ even if it's a benefical virus.
## Changelog

:cl:
soundadd: Virology got new mysterious ambient sounds.
/:cl:

### CODE REVIEW

**Comment by DrDiasyl** [comment]
I'm considering to lower the BPM and add fade in and fade out. Please for now rate the current version, I will send the "new" one here in comments later, so I can compare ratings of both.

**Comment by CapybaraExtravagante** [comment]
400kb for 20 seconds of audio is quite big. ambilava 3 is like a minute long and is only 200kb. I think you should compress it more.

They sound rly good tho!

Maybe change the naming? ambiviro and then ambiviro1? the other ambience files start at 1, yours should probably do the same.

**Comment by DrDiasyl** [comment]
> 400kb for 20 seconds of audio is quite big. ambilava 3 is like a minute long and is only 200kb. I think you should compress it more.
> 
> They sound rly good tho!
> 
> Maybe change the naming? ambiviro and then ambiviro1? the other ambience files start at 1, yours should probably do the same.

Well, some ambients do start with just plain name without numbers, so I did the same. About the compression, will probably try to lower the size of those

**Comment by DrDiasyl** [comment]
**HERE IS THE NEW PROPOSED VERSION OF MINE, PLEASE TELL ME IF IT'S BETTER THEN PREVIOUS ONE**

https://user-images.githubusercontent.com/42353186/183266002-b0a92f8e-ca70-4b9d-ba7d-2aabf0998c52.mp4

**Comment by CapybaraExtravagante** [comment]
> > 400kb for 20 seconds of audio is quite big. ambilava 3 is like a minute long and is only 200kb. I think you should compress it more.
> > They sound rly good tho!
> > Maybe change the naming? ambiviro and then ambiviro1? the other ambience files start at 1, yours should probably do the same.
> 
> Well, some ambients do start with just plain name without numbers, so I did the same. About the compression, will probably try to lower the size of those

those should probably change too then XD. going from nothing to 1 to 2 makes no sense.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
[rust_g.dll](https://github.com/tgstation/tgstation/pull/69031/files#diff-a76a23ed59550ea278abb2b570f32ddd267a88c100e11def965f52283a14667b)

**Comment by DrDiasyl** [comment]
> [rust_g.dll](https://github.com/tgstation/tgstation/pull/69031/files#diff-a76a23ed59550ea278abb2b570f32ddd267a88c100e11def965f52283a14667b)

How to fix this though?

**Comment by DrDiasyl** [comment]
This works? I have changed it to the one from the tgstation master codebase
@ShizCalev 

Also it gone stale, can you please end your review? It's about the areas code file.
@san7890

**Comment by LemonInTheDark** [comment]
@DrDiasyl 
`git checkout tgstation/master rust_g.dll` (replace tgstation with whatever you have our repo named as a remote)

**Comment by LemonInTheDark** [comment]
Un DNM when rustg is no longer being modified

**Comment by DrDiasyl** [comment]
Now this PR doesn't change rust dll in any way, @LemonInTheDark

**Comment by DrDiasyl** [comment]
Ah shit, changes don't pass now.

**Comment by DrDiasyl** [comment]
Okay. I'm doing this the easier way so I opened #69407 withoug that Rust DLL problem.
@LemonInTheDark

**Pull request closed without merging**
