### PR TITLE
Replaces my old and crusty pp-95 with the cool new nukeops tech on the block, smart SMGs

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

image

smart bullet

Adds the Abielle Smart-SMG to replace the pp-95 entirely.

The Abielle performs nearly identically to the pp-95 in nearly all aspects, doing 0.5 less damage because it's not a projectile modifier on 9mm anymore.

What the Abielle does do majorly differently, is give it's bullets a slight homing ability VS whatever you clicked on. This keeps the weapon equally useless to it's predecessor at spraying blindly down hallways, while rewarding careful aim with bullets that slightly track the target.

## Why It's Good For The Game

The surplus smg sucks, and I don't mean performance-wise (although it certainly does, that's the idea). The surplus smg sucks because typically you would be better suited using it as a melee weapon due to the inaccuracy and low damage. Making the cheapo "I forgot to buy a weapon" gun practically useless is super punishing especially for newer ops who might not remember to buy a weapon first. The smartgun makes the surplus smg still pretty shit compared to the other nukeops guns that can down a man nearly instantly, but means that reinforcements or broke ass nukeops can still be relatively effective so long as they can click on a spaceman across the screen.

## Changelog
:cl:
balance: The nukeops surplus smg, the pp-95, has been reworked into the Abielle Smart-SMG. It performs nearly identically to the pp-95, however it's projectiles get a slight homing ability towards whatever you click on.
sound: New firing sounds for the surplus smg, credit to the m41 sound effects from tgmc
image: New sprites for the surplus smg, made by me
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
imo you should keep the plastikov, its not intended to be actually used outside of being a complete meme or a REALLY cheap solution (so still a meme). Smargun is cool though.

**Comment by Paxilmaniac** [comment]
> imo you should keep the plastikov, its not intended to be actually used outside of being a complete meme or a REALLY cheap solution (so still a meme). Smargun is cool though.

this is still just the plastikov but if you click on people it slightly follows them

i was the one that originally made the plastikov and it sucks i dont like it, this is better

**Comment by SomeoneYouProbablyKnow** [comment]
Maybe it's just the way I play but I feel like clicking directly on the spessmen you're shooting is a bit more "high-end" tech and not something newer players do. So for me it's just a weird change.

Maybe someone can make use of it when double wielding these surplus smgs for a meme but that someone is not going to be a new player. If anything a cool smartgun might be an even bigger bait because it sounds like an actual weapon you'd wanna use.

The IDEA of a smart gun is pretty neat, honestly with nuckies being a violent antag already, why not just make it home in on anyone not on team-nuckie? If as you say the homing's only slight, then it would be the ultimate (but not actually strong) spray and pray weapon for newer players. Yes you'd be able to spray down hallways you don't see but that's.. fine?

**Comment by Paxilmaniac** [comment]
It's def. still a meme weapon but I think giving it a bit more depth by rewarding players for not just blindly spraying down hallways makes it a lot more interesting.

**Comment by Loafin34** [comment]
i think the sprite looks a bit too mashed. could you have the gun barrel be black with stripes of white-blue and the laser be pure white-blue with the green at the end? just so it's more legible?

**Comment by Maximal08** [comment]
I believe that this should not be a replacement for the legendary c20r, but should be a new separate weapon.  Although the idea of a smart weapon is good, it looks like a nerf blaster and looks more like a sprite cannon from nova (which I don't like the look of because they look like toys).

**Comment by SomeoneYouProbablyKnow** [comment]
> The nukeops surplus smg, the pp-95, has been reworked into the Adielle Smart-SMG

Not the C20r. 
But this is what i mean, a "smart gun" doesn't sound like a pile of crap surplus weapon you get for a laugh or because you ran out of money it sounds like an item you can actually use, nd it's bound to confuse more people like that.

**Comment by Maximal08** [comment]
image
We are waiting for the bulldog shotgun in a new design.

**Review by Wallemations — APPROVED** [review]
Good sprite

**Comment by projectkepler-ru** [comment]
thank you for blessing us with more sickass gun holy shit

**Comment by HoodMilk** [comment]
Nomenclature aside (Maybe change the name to Adeline Micro-SMG or something to clarify that it's not a powerful weapon?) It seems like a fun weapon and more satisfying to use than the wall-plinker that is the pp-95

**Comment by Donkier** [comment]
is that some cyberpunk smartgun inspiration Im seeing?

**Pull request merged**
