### PR TITLE
lmao we played ambient sounds every 30 seconds for areas

### PR DESCRIPTION
**Pull request by Iamgoofball**
Fixes #59509

## About The Pull Request

Ups the ambient sound cooldown from *30 seconds* up to like between 2 to 5 minutes.

## Why It's Good For The Game

AI players were feeling malf after the fifth time they heard EVERYBODY GET UP IT'S TIME TO SLAM NOW in the last 3 minutes.

## Changelog
:cl:
fix: Fixes Space Jam spam for the AI.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
why not just apply this to the ai area specifically? i like the regular ambience

**Comment by Iamgoofball** [comment]
@Mothblocks its been a general complaint for months now that the ambient sounds play way too often ever since the rework

**Comment by Fikou** [comment]
> its been a general complaint for months now that the ambient sounds play way too often ever since the rework

do you have any links to see those complaints

**Comment by Mothblocks** [comment]
well i disagree with them and i like zxaber's pr better :-1:

**Comment by Mothblocks** [comment]
i like the ambience times

**Comment by Watermelon914** [comment]
should probably look into soundscapes and moving the ambimalf to a soundscape system which plays at a lower interval. Ambience should play often and only really be ambience rather than sound effects.

**Comment by Watermelon914** [comment]
to add on to the above, ambience for areas should probably just have 1 static sound file that plays over rather than picking from a list. Currently, you have a list and it picks a random file from the list to play to the client.
You could rename the current ambience system to soundscapes and then add on an actual ambience system.

**Pull request closed without merging**
