### PR TITLE
Layers pAIs under mobs to stop bodyblocking

### LINKED ISSUE #23224: PAIS ARE FUCKING HARD TO STOP
i know people say ion gun but i mean those things dont even get fucking stunned i blame mekhi there was a PAI in a emagged janibot this round i destroyed the janibot it kept runnin runnin and runnin i tried to stun it with a baton but it didnt even fucking stop I MEAN DRONES CAN BE STUNNED WHY CANT PAI'S???

### PR DESCRIPTION
**Pull request by silicons**
fixes #23224

### CODE REVIEW

**Comment by Supermichael777** [comment]
Remove pAI TBH so long as they have orders that make them Onehuman Jr there an excuse for ghost valids.

**Comment by Cyberboss** [comment]
Did you test this?

**Comment by kevinz000** [comment]
https://i.imgur.com/z9WY1Ll.gifv yes cyberboss this makes them never pass overh umans.

**Comment by optimumtact** [comment]
this doesn't fix the linked issue at all, they're still annoying

**Comment by kevinz000** [comment]
@optimumtact they've been already nerfed to the ground what do you want done to fix them short of layering them under humans?
they lost ventcrawling, they now have a slow movespeed, they have zero access.

**Comment by optimumtact** [comment]
I suppose that's enough

**Comment by jughu** [comment]
BUT NOW THEY WILL HIDE UNDER HUMANS AND THEN THEY BODY BLOCK THEM JUST PUT A DELAY IN HOLOGRAMMING

**Pull request merged**
