### PR TITLE
Player-craftable Trapdoors

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
Makes trapdoors player-craftable.
Player-crafted trapdoors have a tiny outline as well as being visible on examine. (Mapped in trapdoors have `conspicuous = FALSE` by default)
Trapdoors can be made by using a trapdoor kit (crafted via player crafting menu) on openspace. 
Trapdoor electronics / assembly can be made via autolathe or engineering lathe.
A preloaded trapdoor remote (optional) can be made by crafting the electronics with a compact remote (from science lathe / circuit lab) and some cable coil.
Also allows unlinking trapdoors via a multitool, decreased trapdoor link range, and made some changes to trapdoor code.

Added change: Trapdoors now don't break with just a crowbar

## Why It's Good For The Game
Trapdoors currently can only be added in by mappers and this would allow for a lot of interesting contraptions, while having player-crafted trapdoors be detectable provides some counterplay

## Picture
trapdoorlookdemo

## Changelog

:cl:
add: You can now make trapdoors. Craft a trapdoor kit and use it on an openspace tile to make one, then link and activate it with some trapdoor electronics (printable at an autolathe or the engineering lathe) and optionally a trapdoor remote (crafted in personal crafting menu).
qol: You can now unlink trapdoors by using a multitool on them.
balance: Trapdoors now won't break if you just crowbar them. You need to block them from closing, such as with a lattice, cover it up with a wall, or fully destroy the floor tile its on to get rid of them.
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
> You can now unlink trapdoors by using a multitool on them.
So anyone can unlink hop trapdoor?

**Comment by RandomGamer123** [comment]
> > You can now unlink trapdoors by using a multitool on them.
> > So anyone can unlink hop trapdoor?

Yes, however to be honest anyone could already break hop trapdoor by crowbaring it, so making it unlinkable seems to not be that much of a difference

**Comment by Shadowflame909** [comment]
Does this only work on multi-z-levels? Im kind of confused on where they'd go if it didnt

**Comment by RandomGamer123** [comment]
> Does this only work on multi-z-levels? Im kind of confused on where they'd go if it didnt

You simply wouldn't be able to use the trapdoor kit (since it requires an openspace turf)

**Comment by MrDoomBringer** [comment]
> making it unlinkable seems to not be that much of a difference

The hop trapdoor should be made harder to disable, not easier

**Comment by RandomGamer123** [comment]
> > making it unlinkable seems to not be that much of a difference
> 
> The hop trapdoor should be made harder to disable, not easier

Yeah that's fair, maybe I'll make changing tiles not disable it

**Comment by optimumtact** [comment]
Pictures of it in game

**Comment by RandomGamer123** [comment]
> Pictures of it in game

Added a picture, if you want a video I could also make one

**Comment by MrDoomBringer** [comment]
Great change, great work 👍

**Comment by tralezab** [comment]
amazing, great way to solve problems that stopped me from making trapdoors craftable in the first place.

**Comment by RandomGamer123** [comment]
Was messing around on local and notice that this solution means that you can destroy a trapdoor with a RCD and it doesnt break, looking for a solution and so marked as draft for now

**Comment by RandomGamer123** [comment]
bump

**Pull request merged**
