### PR TITLE
Removes broken light sparks

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
These things cause a lot of lighting updates, and if there are enough will bog down both the lighting and timer subsystem. They are cute, but I dont think they are worth the cost.

## Why It's Good For The Game
Less load on lighting and timer subsystem.

## Changelog
:cl: Skoglol
del: Broken lights no longer spark, removed for performance reasons.
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
These sparks ignite fires. This is a massive nerf to malf AIs.

**Comment by dablusniper** [comment]
They're useful to start fires during plasma floods, I think they should stay.

**Comment by kriskog** [comment]
The sparks when breaking a light still remain, these are just the periodic sparks from broken lights.

**Comment by trollbreeder** [comment]
Periodic sparks ignite as well. Why don't you just remove the light effects from them?

**Comment by fatted50** [comment]
The buzzing is annoying, good PR.

**Comment by Pumpkinoe** [comment]
I agree, just remove the numerous light effects from them, maybe just have one on the fixture as it sparks?

**Comment by cacogen** [comment]
Used to be as a hack malf AI doing braindead babby plasma flooding if you were relying on lights as well as the classic spicy airlock you had one shot, one opportunity and I really don't see why you'd need more

**Comment by Cyberboss** [comment]
Instead of removing it, why not make it less frequent the more it is happening?

**Pull request closed without merging**
