### PR TITLE
Repipes Every Map in Layers 1 and 3

### PR DESCRIPTION
**Pull request by Helianthus00**
## About The Pull Request
This pull request replaces all scrubber piping and all air supply piping on Icebox, Meta, Delta, Pubby, and lavaland with scrubbers being on layer 1, and air supply being on layer 3. Base atmos is basically unchanged, only slight alterations were made beyond just changing the pipes and scrubbers/vents. Supply pipes were done by tracing over the current path, only adjusting when it made sense to do so, so the basic supply pipe setup is practically unchanged for each map. Scrubbers can be different, depending on the map. I tried my best to follow whatever was in the map beforehand, but the changes to scrubbers are more visible than those to air supply (for example, on Meta, scrubbers rarely enter maint, so I have followed this for the most part). All areas with independent air supplies and scrubber systems are maintained, though they are also repiped, with one or two exceptions.

## Why It's Good For The Game
The pipes before were a mess and have been left sloppy from maintenance over time. They also ran through walls often, flowed awkwardly, and just looked terrible. This PR fixes all of that. Now, it should be much easier to access all pipes and follow them to make changes or fixes (or sabotage, in the case of traitors). Layer 2 is reserved for basic pipework, as well as power cables. In atmos and the SM room, I have kept most of the piping close to the walls, as to allow the maximum space for working in layers 1/3. 
Lavaland:
lavaland
Icebox:
icebox
Delta:
delta (2)
Meta:
meta
Pubby:
pubby

## Changelog
:cl:
add: New piping in layers 1/3 to Lavaland
add: New piping in layers 1/3 to Icebox
add: New piping in layers 1/3 to Delta
add: New piping in layers 1/3 to Meta
add: New piping in layers 1/3 to Pubby

/:cl:

### CODE REVIEW

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Security's air supply needs to remain isolated as so;

image


image
Yours is currently pumping the vent directly into the station's main line.

**Comment by LemonInTheDark** [comment]
image
BASED AS HELL

**Comment by Helianthus00** [comment]
@ShizCalev Fixed. I had to shift a bit around in that room, but it still contains the same things.
fixed
fixed2

**Comment by TheVekter** [comment]
I don't even want to know how long this took.

You crazy bastard.

**Comment by Axanthic** [comment]
What did you do for toxins? Would those pipes stay level 2 since users would interact with them?

I think the pipes definitely need changes as most areas if you want to work with pipes you will quickly find that every room has pipes sprayed about. It appears you've chosen the simplify by using two layers as opposed to being constrained by one layer to simplify it. The negative with this is that when working on pipes you will have to know if the pipe you're connecting to is layer 1 or 3. This might cause more usage of layered manifolds.

**Comment by Helianthus00** [comment]
@Axanthic Only scrubber and air supply pipes are changed, except for on Pubby where cyan pipes are used for alternate air supply piping. For toxins, the pipes are unchanged and connected to the distro/scrubber system with layer manifolds. Since all pipes are consistent between all maps as scrubbers being layer 1 and supply being layer 2, people should quickly get used to that as the new norm and though it will cause more usage of layer manifolds, this isn't necessarily a bad thing. Overall, this was intended as more of an update than an optimization. Nothing was really optimized beyond transferring the pipes to new layers and slightly moving them to avoid piping through walls.

**Comment by Helianthus00** [comment]
Okay, no idea why it is still conflicting. I managed to resolve the last conflict just fine, but this one won't go away. I took the map file from pr #52630 (skillchip one) and copy/pasted my pipes over it, so the maps should be identical in all aspects besides the piping. I assume this will need to be manually resolved.

**Comment by Timberpoes** [comment]
The only Delta change in that PR was adding a Skill Station machine next to the Gaming Vendor in the library, I believe replacing the filing cabinet next to it with a `/obj/machinery/skill_station/`

**Comment by Helianthus00** [comment]
@Timberpoes Yeah, that's exactly what my pr 7c56f6d did. When it didn't work, I reverted it and did the map copy thing just in case I missed something minor. Still getting a merge conflict though. I think it's because there is a pipe underneath that tile, so it technically isn't the same tile in my branch and theirs, which is causing the conflict.

**Comment by Helianthus00** [comment]
Just let me know whenever this pr is being considered to be merged or not. Fixing these map conflicts doesn't work most of the time and it's a huge pain to do it over and over again every time a new change is made, so I'll fix them all at the same time whenever that comes up. I'll just copy all of the atmospherics structures from my maps onto whatever the current version of the map is, so it's a problem that can be fixed in ~30 minutes. Having to do it every time the maps are updated though makes me want to tear my hair out.  This method works fine anyway since I only made atmos changes and none of the other changes did this as far as I can tell.

Post a comment here or ping/message me on discord and I'll have it taken care of quickly. Helianthus#9774

**Comment by Helianthus00** [comment]
Okay, again I just updated all the maps, so the conflicts are basically invalid. I simply took my old maps and copied only the atmospherics (everything in /obj/machinery/atmospherics) over the current version of whatever map is the most current. Nothing has changed in the atmospherics as far as I can tell with recent prs, so this should mean that these maps are 100% up to date plus my pipes. There are only still merge conflicts because the piping is so vast and covers so many tiles that it was impossible to not alter other tiles that were recently changed, which is what I assume is causing the merge conflicts. However, all of those things are still there, it is only the underlying pipes that changed and messed up with the auto-merge. (I also caught a single vent that I missed on delta and put one there)

**Comment by actioninja** [comment]
based but also conflictpilled

**Comment by stylemistake** [comment]
You messed up.

**Comment by Helianthus00** [comment]
@actioninja 
Okay, I really don't know what I'm doing, obviously. If I just close this pr and make a new one with a up to date base, would that be fine? All I know is how to put the things on the map, git is not my strong suit.

**Comment by stylemistake** [comment]
Don't close the PR, fix this one until you're satisfied with results, you can use force pushes to change the contents of this PR.

**Comment by Helianthus00** [comment]
Alright. Sorry to everyone that got requested to review. I'll work on fixing it then.

**Comment by Helianthus00** [comment]
ALRIGHT, it's finally fixed. Huge thanks to TheFinalPotato for sitting down with me for close to 3 hours and getting it all worked out. Everything is up to date and ready to be merged once the checks pass anyway.

**Comment by actioninja** [comment]
This is going to cause issues, be around to fix any as they come up. Fantastic work on this though.

**Comment by msgerbs** [comment]
Best PR 2020, from one atmonerd to another!

**Comment by Cyberboss** [comment]
Good PR

**Comment by cacogen** [comment]
how agonising this must've been

**Pull request merged**
