### PR TITLE
Capitalizes machine names when they talk on radio

### PR DESCRIPTION
**Pull request by QualityVan**
:cl: QualityVan
tweak: Machine names will be capitalized when they talk on radio
/:cl:

Apparently their being lowercase was a nuisance for some people.

### CODE REVIEW

**Comment by coiax** [comment]
No. They're machines, they're not people.

**Comment by QualityVan** [comment]
Honestly I don't have super strong opinions about whether this should be merged or not. I just wanted to make a better version of #26801

**Comment by PKPenguin321** [comment]
Looks nicer:+1:

**Comment by lzimann** [comment]
I am not sure on this to be honest, leaving lowercase is good because it shows that it's an object, on the other hand it's kinda weird.

**Comment by coiax** [comment]
Ew why

**Pull request merged**
