### PR TITLE
Reworks how legs are rendered yet again because it was very convaluted i hated it

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

The previous method for masking legs properly involved quite heavy icon manipulation and I didn't like it.
To fix this, I simply made two bodypart layers get used for rendering legs, a low layer (for the leg that should be hidden behind the other in a given dir) and the normal bodypart layer.
This still involves icon manipulation, as the unnecessary dirs need to be cropped properly for the low layer and normal layer, but this should be a considerably simpler and more reliable system.
Additionally, this fixes the issue of husks not having their legs masked for whatever reason.

## Why It's Good For The Game

Legs still overlap properly, but the code no longer gives me migraines.

image
image

## Changelog

Not player facing, unless something went wrong and i failed to notice.

### CODE REVIEW

**Comment by Kapu1178** [comment]
does this account for rotation?

also hijacking the layer used for hands may lead to problems in the future.

CC @GoldenAlpharex

**Comment by ChungusGamer666** [comment]
> 

This does not hijack the hands layer. I just renamed the hands layer because i didn't like the silly name much.
Legs when facing WEST or EAST use a new layer instead, BODYPARTS_LOW_LAYER.

**Comment by Kapu1178** [comment]
> This does not hijack the hands layer. I just renamed the hands layer because i didn't like the silly name much. Legs when facing WEST or EAST use a new layer instead, BODYPARTS_LOW_LAYER.

would you not need to call `update_body_parts()` on `setDir()` to account for rotation changes?

**Comment by ChungusGamer666** [comment]
> 

Not necessary, as the PR states, this creates two masked images instead of one for each leg that remove the appropriate dirs.

**Comment by Kapu1178** [comment]
> > 
> 
> Not necessary, as the PR states, this creates two masked images instead of one for each leg that remove the appropriate dirs.

Alrighty. The leg render stuff isn't my forte, just wanted to clear that up. 👍

**Comment by ChungusGamer666** [comment]
Oh what the fuck.

**Comment by ChungusGamer666** [comment]
Just ran the unit tests locally and screenshot tests passed just fine, I am very sure that this is a false positive...

**Comment by ChungusGamer666** [comment]
Screenshot tests are fucking working now wahoo!!

**Comment by Mothblocks** [comment]
> Just ran the unit tests locally and screenshot tests passed just fine, I am very sure that this is a false positive...

Screenshot tests don't compare on local, they only generate the image

**Comment by ChungusGamer666** [comment]
ok so glass golem screenshots updated, everything looks the same otherwise

**Comment by Kapu1178** [comment]
> ok so glass golem screenshots updated, everything looks the same otherwise should be ready to merge

did you make sure it plays nice with dismemberment when using mismatched limbs? specifically digitigrade + human? etc

**Comment by ChungusGamer666** [comment]
Amputated legs still look normal.
image
image
image

You can still play god in the surgical ward.
image
image

**Comment by ChungusGamer666** [comment]
or @Mothblocks or whatever, should be good to go yup

**Comment by ChungusGamer666** [comment]
true-or-rubbish

**Comment by ChungusGamer666** [comment]
are you fucking kidding

**Comment by ChungusGamer666** [comment]
please merge this. . . . . .

**Pull request merged**
