### PR TITLE
Brain damage forcedsay single string change

### PR DESCRIPTION
**Pull request by Aranclanos**
changes the trauma string "wearnig siNGUARLTY IS .... FIne xDDDDDDDDD" to "wearnig siNGUARLTY is.... FINE haHAAA"

The 'xDDDDDDDDD' broke my immersions

### CODE REVIEW

**Comment by optimumtact** [comment]
you can just remove all the OOC meta references if you want, this is played out now.

**Comment by Arianya** [comment]
+1 for stripping most/all of the blatant OOC

**Comment by Aranclanos** [comment]
sure why not I'll ask for creativity help later

is it bad if I still like 'lifelike texture ;_;' tho

**Review by SpaceManiac — APPROVED** [review]

**Comment by Bawhoppen** [comment]
Something still funny about the fourth-wall breaks being considered a form of brain damage ingame to me.

**Pull request merged**
