### PR TITLE
Legioned Monkeys create different mobs

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

image

A Monkey infested by a Legion will spawn a "Rabble" instead of a "Legion".
This is a somewhat slow 40 HP mob which tries to melee attack nearby people.
Its only real claim to excitement is that it can and will ventcrawl if it has nobody to attack.

## Why It's Good For The Game

Apparently people are creating large amounts of monkeys using monkey cubes and then using the Legion's infestation mechanic to transform them into large groups of much more dangerous mobs.
This is funny and creative but probably shouldn't be as effective as it is.
Replacing Legion Monkeys with this mob will still create a mob of... mobs, but they won't self-perpetuate in the same way.

## Changelog

:cl:
add: A unique kind of mob is created when a Monkey is infested by a Legion.
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
Out of curiosity, are these able to spawn out of scrubber overflow events?  Because that would be amazing.

**Comment by Jacquerel** [comment]
> Out of curiosity, are these able to spawn out of scrubber overflow events? Because that would be amazing.

Not currently although someone could add it

**Comment by moocowswag** [comment]
mutadone foam

**Comment by Jacquerel** [comment]
> mutadone smoke/foam/dropper

Don't worry im going to have a different PR for that

**Review by Wallemations — APPROVED** [review]
Baby legions omg

**Pull request merged**
