### PR TITLE
Adds react's rule of hooks to eslint

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Adds a set of linter rules from eslint's rule of hooks since we are using the real ones now

image
## Why It's Good For The Game
Prevents people from doing strange things which breaks the rules of hooks
## Changelog
N/A nothing player facing

### CODE REVIEW

**Comment by Mothblocks** [comment]
React assumes anything that stats with `use` is a hook. However, `useLocalState` is not only very much not a hook, we also are explicitly not using it like one, such as intentionally using it in class components and such.

I recommend renaming `useLocalState` to `DEPRECATED_useLocalState`. Fixes this while having the nice effect of making it more obvious to maintainers and contributors not to accept that code.

**Comment by MrStonedOne** [comment]
> React assumes anything that stats with use is a hook.

im glad to know that its not just byond that is cursed.

**Comment by MrStonedOne** [comment]
In general i kinda oppose adding bullshit rules like this to the linter.

They provide no value other than to add a bunch of gotchas for new programmers to hit based on bullshit rules that only make sense in limited contexts.

Prettyfer, function name prefix rules, and other style rules in the linter do not provide value, they only become a endless list of bullshit meaningless rules that increases the mental load of programming.

**Comment by jlsnow301** [comment]
> Prettyfer, function name prefix rules, and other style rules in the linter do not provide value, they only become a endless list of bullshit meaningless rules that increases the mental load of programming.

for our fake hooks this makes sense, but for real hooks this rule will prevent a bluescreen

**Comment by MrStonedOne** [comment]
none of what you are saying is making sense.

fake hooks? real hooks? rule of hooks?

Nor is the naming system useful. how does the word `use` relate to hooks?

Why would you be ok with adding rules about the casing of function names or rules that make broad assumptions about function names that start with a common word like `use`?

**Comment by MrStonedOne** [comment]
i think the problem here is react hooks are too finicky and not that coders are holding them wrong.

**Comment by Mothblocks** [comment]
image

**Comment by optimumtact** [comment]
After a robust discussion, mso is happy if we can override the rule to only apply to some paths (if doable)

As per
image


or we use
`// eslint-disable-next-line react-hooks/rules-of-hooks` to supress the rule on calls of useLocalState

Any discussion about deprecating/renaming the function should happen in another PR.

**Comment by Mothblocks** [comment]
Do the latter

**Pull request closed without merging**
