### PR TITLE
Alien nests and some other stuf can be hit again.

### LINKED ISSUE #80311: Cannot physically attack alien nests
Reporting client version: 514.1589

## Issue Summary
Alien nests seem to be unable to be attacked by a person. You have to either burn it, or shoot it.

## Round ID:
[220459](https://scrubby.melonmesa.com/round/220459)

## Testmerges:
- [Bridge Assistant Station Trait](https://www.github.com/tgstation/tgstation/pull/80279)
- [Revert "FOV is Dead (Long Live FOV)"](https://www.github.com/tgstation/tgstation/pull/80301)

## Reproduction:
1. Acquire alien nest (Home grown by your local xenomorph)
2. Attempt to use a method of brute force against the nest to destroy it.
3. Nothing happens.
4. Resort to flamethrower.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Another small issue fixed. Thanks Melbert for telling us what's wrong with it.

EDIT: other objects were rendered unhittable by that flags refactor PR.

## Why It's Good For The Game
Fixes #80311. I made the xmas tree indestructible because the comment to the `NO_DECONSTRUCTION` flag didn't make a load of sense since that doesn't stop it from getting destroyed anyway.

## Changelog

:cl: MrMelbert, Ghommie
fix: Alien nests, and some other stuff, can be physically attacked again.
balance: x-mas trees (the ones with presents), are indestructibles. Truly protected by a yuletide spirit.
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
Can https://github.com/tgstation/tgstation/pull/80104#issuecomment-1847961441 be applied?

**Comment by Ghommie** [comment]
Sure, I'll do it later.

**Comment by Jacquerel** [comment]
Drafting purely because I almost merged it before noticing from the comments that you wanted to add more to this

**Comment by Ghommie** [comment]
Done.

**Pull request merged**
