### PR TITLE
Makes the Roboticist tablet come pre-installed with BotKeeper and SiliConnect.

### PR DESCRIPTION
**Pull request by Nush-Kajul**
## About The Pull Request
Swaps the generic scientist tablet that Roboticists would usually get for one with robotics-related programs.

## Why It's Good For The Game
A lot of new players don't understand how good tablets really are, tending to instead throw them away. It also reduces the time it would take to install these apps for a job that should have them by default.

## Changelog

:cl: 
qol: Makes the roboticist tablet come pre installed with Botkeeper and SiliConnect.
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
Tablets are honestly really good, especially for scientists and roboticists

- program that allows you to PDA message the cyborgs
- program that lets you attempt to send remote signaller signals and then be sad that it's broken
- program that lets you set up chat rooms that no one else sees cause you're the only person who uses a tablet
- holds your ID and fits in your ID slot so you don't lose your ID during PDA bombs and you don't get called a powergamer for leaving your ID out of your PDA
- has a flashlight 
- runs out of power

**Comment by optimumtact** [comment]
This is power creep and you haven't justified it at all.

This kind of thing causes creep by a thousand cuts.

**Comment by Nush-Kajul** [comment]
I apologise if this is a power creep I didn’t intent for it to actually be one i have very minimal experience and just want to make a pr that would make people use tablets more.

**Comment by JohnFulpWillard** [comment]
> 
> 
> This is power creep and you haven't justified it at all.
> 
> This kind of thing causes creep by a thousand cuts.
> 
> If you want people to use these things, try telling them about it IC Instead.

how is this powercreep? The only difference is that Roboticists don't have to take 30 seconds at the start of a round to install these programs. The tablets they spawn with can already download them from the start.

**Comment by GuillaumePrata** [comment]
The scientist tablet has hardware this new one wouldn't have.
It's more like power decreep, roboticist don't need a working signaler in their tablet but on the version we have now, they can download Robotics related apps in 30 seconds and keep the hardware as a bonus.

**Comment by zxaber** [comment]
For the record, I have a plan to change up the modPC enviroment and most crew won't start with a tablet when I'm done.

These apps *still* should be on the roboticist modular computer console, though.

**Pull request closed without merging**
