### PR TITLE
hm

### PR DESCRIPTION
**Pull request by Iamgoofball**
hm

### CODE REVIEW

**Comment by MrStonedOne** [comment]
hmm

**Comment by Repukan** [comment]
Does this mean roundstart Nar'sie will only get one third of the cultists Ratvar would?

**Comment by MrStonedOne** [comment]
almost, its more that round start narsie will only get 70% of the cultists ratvar would.

**Comment by ChangelingRain** [comment]
Ironically, nar-sie starts with more cultists that ratvar does in pretty much all cases.

**Comment by Repukan** [comment]
Nice, realistic details like that really flesh out the game.

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
hey while you're at it give ratvar `gender = MALE`

**Comment by MrStonedOne** [comment]
Gender affirmative action!

THIS IS AN OUTAGE! YOU WILL HEAR FROM MY LAWYER.

**Comment by SgtxRootbeer** [comment]
Must be merged post-haste

**Comment by Armhulen** [comment]
:thinking:

**Comment by Aloraydrel** [comment]
Really makes you think...

**Comment by GunHog** [comment]
I thought Aranclanos did this or would have done this a long time ago!

**Comment by WJohn** [comment]
hmm

**Comment by GunHog** [comment]
Btw, this violates the rule about misleading titles. It is clearly a meme PR, but it does not hurt or affect anything, so maybe it should be made to comply?

**Comment by PKPenguin321** [comment]
🤔

**Comment by Militaires** [comment]
:thinking: :thought_balloon:

**Comment by Anonmare** [comment]
Excuse me, this is my wife you're discussing

**Comment by ma44** [comment]
Did you just assume Nar'sie's gender?

**Comment by GunHog** [comment]
>Did you just assume Nar'sie's gender?

No, we just _declared_ Nar-Sie's gender! The code now makes her female. That means that she now **is**!

**Pull request merged**
