### PR TITLE
Maptext 2023 tweaks 3

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Hopefully the last set of changes in this demonstration of the [Goldilocks principle](https://en.wikipedia.org/wiki/Goldilocks_principle).

Some more font changes, the big (hah) one being the context tooltips again.

- Context tooltips smaller main line, more compact sublines.
- Improves documentation on the usage of the macros.
- Removes incorrect comment I added earlier in tgstation.dme
- Adds black outlines as default in the macros.
- Icon sized letters (Dwarf Fortress, credits).
- Deathrattle and other actions reduced spacing.
- Aligned cooldowns/countdowns.

<details>
<summary>Screenshots</summary>

image

image

image

image

image

image

image

</details>

## Changelog

:cl: LT3
image: More maptext and font tweaks
spellcheck: Context tooltips too small, too big... just right?
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
a few photos would be appreciated here. thanks

**Comment by lessthnthree** [comment]
> a few photos would be appreciated here. thanks

yeah, will be there in a minute once I find that collapsible markup

**Comment by lessthnthree** [comment]
> a few photos would be appreciated here. thanks

Done

**Comment by TheVekter** [comment]
Yeah, that's way better. Thank you. My only worry is that it's still going to be nigh unreadable with longer names, like cargo manifests or some book names.

**Comment by lessthnthree** [comment]
> Yeah, that's way better. Thank you. My only worry is that it's still going to be nigh unreadable with longer names, like cargo manifests or some book names.

We could measure the context maptext and lower the font size if it's over a certain width. I'll keep that as an idea for its own PR.

**Pull request merged**
