### PR TITLE
Fixes smuggler's satchels being usable while hidden

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: You can no longer place items into smuggler's satchels while they're beneath the floor.
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
I don't think this fixes all possible bugs with them, though? Can't you, like, mousedrop them to empty them? Click them to see inventory?

**Comment by Xhuis** [comment]
Ugh, that's true. I'll look for a solution later today.

**Comment by Supermichael777** [comment]
make them abstract if their beneath the floor?

**Comment by Cheridan** [comment]
I think this happens with pipes/wires too, you can hit them while they're visible from t-ray.

**Comment by KorPhaeron** [comment]
Make the t ray poolornew overlays that look like the items hidden underneath rather than actually reveal the item?

**Comment by Xhuis** [comment]
I was thinking about doing that. Does making an overlay with the objects icon state carry over directions, etc?

**Comment by KorPhaeron** [comment]
You can use appearance yes

**Comment by Supermichael777** [comment]
floortiles have some serious fuckery. Their ancient majiks are beyond our understanding

**Comment by KorPhaeron** [comment]
stale

**Comment by Xhuis** [comment]
I completely forgot about this. Oops.

**Comment by KorPhaeron** [comment]
As I remind you ever time, the PR being open or closed does not actually impact your ability to work on something, it's just one button push to reopen it

**Comment by Xhuis** [comment]
I can't reopen PRs closed by maintainers. I can just make a new branch, though, I suppose.

**Pull request closed without merging**
