### PR TITLE
Adds a new, unique sound for polling

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

Port of my downstream PR, https://github.com/Monkestation/Monkestation2.0/pull/2621

This adds a new, unique ringer for prompts/polls (the `SSpolling` ones), [you can preview the sound here.](https://files.catbox.moe/kukr88.ogg)

Sound originally made by @flleeppyy <3

## Why It's Good For The Game

It's nice to have a unique sound for this, as opposed to the normal announcement sound, so you can you're being prompted if you're distracted or tabbed out.

## Changelog
:cl: Absolucy, Flleeppyy
sound: Added a new, unique sound for polling!
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
sounds more like something your phone would emit when booting up than an actual alert sound

**Comment by san7890** [comment]
it would be cool if it was a little more alerty but i think it's okay

**Comment by LemonInTheDark** [comment]
discussed on discord some, needs less leadin is my understanding

**Comment by LemonInTheDark** [comment]
?

**Comment by Absolucy** [comment]
sorry i forgor

latest iteration of the sound: https://files.catbox.moe/kukr88.ogg

**Review by grungussuss — APPROVED** [review]

**Review by SmArtKar — CHANGES_REQUESTED** [review]
New version of the sound is very nice but a bit too loud, I'd say cut it down by 30%?

**Comment by mc-oofert** [comment]
still sounds like a phone bootup sound

**Comment by Absolucy** [comment]
@SmArtKar done (via code tho, I just did `volume = 70`)

**Comment by mc-oofert** [comment]
wow

**Comment by Absolucy** [comment]
2c9

**Comment by mc-oofert** [comment]
I did not mean it in the good sense

**Comment by Sadboysuss** [comment]
> I did not mean it in the good sense

ok make a better one then

**Pull request merged**
