### PR TITLE
Fixes admins needing to ban people for what amounts to a 1 line fix

### PR DESCRIPTION
**Pull request by Iamgoofball**
seriously ffs

also just for @ma44 I replaced it entirely so you dont get any power at all see fair and BALANCED

### CODE REVIEW

**Comment by kevinz000** [comment]
Dumb

**Comment by PKPenguin321** [comment]
ack

**Comment by GunHog** [comment]
A PR very similar to this one has already been denied.

**Comment by Iamgoofball** [comment]
I don't see why we're so opposed to preventing bans

**Comment by kevinz000** [comment]
Just make all mobs godmode already it'll prevent bans right?

**Comment by ma44** [comment]
Hugbox

Let's go remove toxins while were at it, it can lead to a ban from non antags using it

@kevinz000 but you can still station grief, so it won't prevent bans

**Comment by kevinz000** [comment]
Let's just remove goofball it'll save us lots of grief.

**Comment by kevinz000** [comment]
Like what the fuck is with you today goof?

**Comment by Iamgoofball** [comment]
@kevinz000 i'm mad we're banning players instead of fixing issues

full darkRP when?

**Comment by lzimann** [comment]
The ban was not even because he jumped into the SM, there is more to it.

**Pull request closed without merging**
