### PR TITLE
DeltaStation mapping fixes.

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Atomizing these per map to avoid merge conflict hell.
Some cables, some pipes, a couple duplicate APC's, some duplicate camera tags.

## Why It's Good For The Game
Fixes

## Changelog
:cl: Skoglol
fix: Fixed some DeltaStation mapping issues. Removed a couple duplicate APC's, some cables, some dead end pipes.
/:cl:

### CODE REVIEW

**Comment by Anonmare** [comment]
There's also an issue with the SMES at the north-east solar array, it had its input connected to its output as I recall

**Comment by kriskog** [comment]
Thanks, both of the east ones were wrong

**Comment by ShizCalev** [comment]
image
misplaced APC

**Review by ShizCalev — CHANGES_REQUESTED** [review]
.

**Comment by kriskog** [comment]
Hm, dir fuckery maybe. Good catch

**Comment by kriskog** [comment]
Fixed
image

**Pull request merged**
