### PR TITLE
Adds Beanbag Slug Shells to Sec Protolathe

### PR DESCRIPTION
**Pull request by Steelpoint**
As the title states, this PR adds beanbag slug shells to the security protolathe.

Furthermore, it increases the metal cost of the shells to be in line with other shells, both from the autolathe and protolathe. So from 250 metal to 4000 metal. 

:cl: Steelpoint
add: Beanbag slug shells can now be produced at the security protolathe.
tweak: Beanbag slug shells now have the same metal cost as other comparable shotgun shells.
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
If the beanbag shells cost the same, why not just _print a lethal shell and not bother at fucking all with nonlethals_?

**Comment by Steelpoint** [comment]
Because you want to capture someone alive......

**Comment by evsey9** [comment]
make it be at least 2000 metal or something
this will just promote the lethal shitsec behavior. Why bother with beanbag if you can just print buckshot for the same amount of metal and then shoot them until borderline crit, get to sec and heal them up?

**Comment by Eskjjlj** [comment]
The only reason I would print non lethal shells is because they are cheaper. Otherwise buckshot is more effective. Just heal the lad if you want him alive.

**Comment by subject217** [comment]
The only reason I would EVER print beanbags is the price. Otherwise, rubbershot is almost always superior. That's why they're so cheap.

**Comment by Steelpoint** [comment]
Is is 2k metal, for some reason the techfab halves the metal cost of the shells

**Comment by necromanceranne** [comment]
For whatever reason, beanbags are horrifically weaker than rubbershot in every way and weirdly unreliable at incapacitating people. While the bartender, the main user of beanbags, has plenty on hand for the shift if they're not actively fighting people all the time (say, you're taking those beanbags to fight sec as a rev or something), they don't really DO much to stop a fight. Their cheapness is all they have going for them at the moment, so I'd definitely agree with subject on the matter and keep them at a lower price than 4000. If you can print beanbags, you'd almost always just print rubber shot.

**Comment by Steelpoint** [comment]
I've found beanbag slugs seem consistsnt in knocking people down, but thats my opinion.

If the consensus is such ill lower the price a bit

**Comment by subject217** [comment]
They're shit now with the stamina damage changes. If your second shot varies to any limb, you don't get a knockdown. Rubbershot is way better.

**Comment by Steelpoint** [comment]
I dunno, I still two shot stunned a target even when one of my shots hit the leg.

**Comment by necromanceranne** [comment]
I suppose then that beanbags probably need a buff given their current issues if they're going to receive a price increase. Maybe make them more in line with being the nonlethal slug variant.

**Comment by Steelpoint** [comment]
As I just stated, I did a test and the beanbags can reliably stun a target in two hits, irrespective if one of the slugs hits a arm or leg.

**Comment by improvedname** [comment]
If i wanted to stun somoene i just would use my taser. Fuck off we have taser slugs why do we need beanbag sougs

**Comment by subject217** [comment]
Not if both hit the legs. If you get one chest and one leg it'll work yah. What range did you test it at though?

**Comment by Tlaltecuhtli** [comment]
tbh just merge this for consistency its not like beanbang would change stuff

**Pull request merged**
