### PR TITLE
Clone pods now grab their ghost on maturity

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: Cloning pods now grab the clone's mind when the body is ejected,
rather than when it starts cloning.
/:cl:

Keep your features close, and your bug fixes closer. But seperate.

### CODE REVIEW

**Comment by optimumtact** [comment]
Fix feature rebalance?

**Comment by coiax** [comment]
Feature, balance.

**Comment by LatD** [comment]
This still fixes #14392

**Comment by coiax** [comment]
Actually, I think that's already fixed. Cloners no longer eject clientless mobs (because otherwise delayed ghost grabbing wouldn't work)

**Comment by Core0verload** [comment]
Is there any point in this change?

**Comment by Shadowlight213** [comment]
Still don't like it.

**Comment by optimumtact** [comment]
No harm in having a go and then we can undo it later if people don't like it that much

**Pull request merged**
