### PR TITLE
Multiverse clones are now identical to the summoner

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**

### CODE REVIEW

**Comment by optimumtact** [comment]
ANTAG HUDDDDDDDDDDDDd

**Comment by Buggy123** [comment]
Does this include items you're carrying?

**Comment by KorPhaeron** [comment]
@Buggy123 

No they still get a random outfit

@optimumtact 

I can't code sorry

**Comment by Zilenan91** [comment]
@KorPhaeron Can you make them have the same outfit instead because a bunch of dudes wearing pirate outfits or Op gear are going to be a lot more easy to notice than a bunch of dudes whose features are covered up by their clothing. This really won't do anything for anybody but lizard clones.

**Comment by Lumipharon** [comment]
that would make it a Cloner Sword instead of a multimeme sword then.

**Comment by Shadowlight213** [comment]
So much yes. Them only sharing your name was the stupidest thing ever.

**Pull request merged**
