### PR TITLE
[s][wip] A horrifying attempt at replacing tgui's client-side with that of nanoui

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
I'm just posting this PR in case anyone wants to take a crack at this. It's at a point where nanoui windows actually open and mostly render properly if there's a matching template and the data keys haven't been renamed much after the transition to tgui, but almost nothing else works.

If someone who actually knows how byond<->browser integration works, or has the mental fortitude to bulldozer through the slow parts could pick this up and either:
1. Add the missing stuff and take this PR to completion, or
2. Throw out my flailing attempts at and do it properly

I'm willing to provide the help needed to transfer TGUI template files over, but I'm the wrong guy to get the internals working.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
You will be our savior if this works

**Comment by DoctoreMad** [comment]
There's no waking up form this nightmare.

**Comment by kevinz000** [comment]
what's the difference between tgui and nanoui?

**Comment by Iamgoofball** [comment]
Dude, no

Nanoui is OLD tgui

Stop being an idiot 

Tgui is better and more up to date

**Comment by Iamgoofball** [comment]
Also WHY WOULD WE SWITCH TO AN OLDER LESS DOCUMENTED VERSION OF OUR UI

**Comment by Bawhoppen** [comment]
Aside from the fact that tgui is somehow worse than our old nanoui, this isn't the same thing as old nanoui

**Comment by Iamgoofball** [comment]
YOU HAVE NO IDEA WHAT YOU ARE TALKING ABOUT YOU WEREN'T HERE FOR NANOUI

**Comment by Iamgoofball** [comment]
Oh my GOD

**Comment by Bawhoppen** [comment]
What do you mean I wasn't here for NanoUI? Atleast it worked on SOME people's computers

**Comment by DoctoreMad** [comment]
>Also WHY WOULD WE SWITCH TO AN OLDER LESS DOCUMENTED VERSION OF OUR UI
YOU HAVE NO IDEA WHAT YOU ARE TALKING ABOUT YOU WEREN'T HERE FOR NANOUI
Oh my GOD

heh

**Comment by Qbopper** [comment]
goofball doesn't like it so it should be merged

**Comment by vuonojenmustaturska** [comment]
@Iamgoofball using ractive.js for presentation has known problems for lots of users, and unless we are dumping ie8 it is never going to get better. The maintainers are saying windows XP and linux are supported platforms, therefore ie8 cannot ever be dumped.

The whole TGUI stack is a rickety pile of 200 node.js packages, with versions pinned at something that was available in 2015 for mostly unknown reasons (apart from ractive since ractive 0.8+ doesn't work on ie8). Almost no-one actually knows how anything works, it's all been cargo-culted and as infrastructure, TGUI is unmaintained. I have branches where I've attempted to do some housekeeping, some of them even work, just that they also do not fix any of the real problems we have.

The idea in this PR was to port nanoui's doT.js-based lightweight presentation/synchronization layer and keep the byond-side improvements (ui_act(), stuff about who can use what interface etc). If i just wanted to plop in nanoui it'd be as easy as pulling it from bay, they use both side-by-side.

**Comment by Cyberboss** [comment]
Don't feed it after midnight

**Comment by Iamgoofball** [comment]
@vuonojenmustaturska 
I'm fairly certain we officially dropped IE8 and XP support ages ago.

**Comment by Cyberboss** [comment]
Nope

**Comment by Iamgoofball** [comment]
Why the fuck do we have to support windows XP people who refuse to upgrade even though it's 2017

**Comment by DoctoreMad** [comment]
>ITS THE CURRENT YEAR

Who wants to upgrade to Windows newest rickety shit? Are you that kind of goy?

**Comment by Hatfish** [comment]
good, tgui is a fucking pain to resize and the windows always take up half the screen when opened.

**Comment by Qbopper** [comment]
lol

it's probably reasonable to suggest that people move onto windows 7 or something considering it's been 3 years since even microsoft dropped XP, but I don't know enough about the situation to have a real opinion

**Comment by DoctoreMad** [comment]
Windows 7 support has ended already.

**Comment by Qbopper** [comment]
lol

**Comment by Supermichael777** [comment]
vista was field executed soon after xp

**Comment by DoctoreMad** [comment]
>extended support

Iiiiiii stand corrected

**Comment by kilkun** [comment]
lets just go back to bog standard html menus.

**Comment by SgtxRootbeer** [comment]
i liked the html menus, and have no problems with them. if we can get them to autoupdate once a second or something, then i dont think the playerbase cares too much.

**Comment by Qbopper** [comment]
there might be some controversy over the art downgrading, i'm not sure how fancy you can get with the html menus

**Comment by Cyberboss** [comment]
We're not going to use plainhtml either

**Comment by DoctoreMad** [comment]
Once the powergamers realize that they can operate things faster they're going to shut up anyone dissenting about the art downgrade so that's clean.

**Comment by Iamgoofball** [comment]
We lose ALL QoL if we go to html.

**Comment by Kerbin-Fiber** [comment]
As long as this stops the Crew Monitor from crashing my game, I'm with it.

**Comment by MrStonedOne** [comment]
REMOVING IE8 SUPPORT WILL NOT MAKE TGUI BETTER

WE ALREADY TRIED, IT DID NOT ADD ANY SPEED TO TGUI.

**Comment by MrStonedOne** [comment]
Also microsoft removed upgrade support on windows 7 for people with current gen processors to try and force them on 10.

Meaning if you use windows 7 on a 7th generation cpu, you can't get ie9+

**Comment by vuonojenmustaturska** [comment]
is the crew monitor even tgui? isn't it that snowflake one?

**Comment by MrStonedOne** [comment]
also ya, the crew monitor isn't even tgui

**Comment by nicbn** [comment]
This whole nanoui and tgui thing is broken.

Someone needs to rewrite it in a not stupid way.

**Comment by optimumtact** [comment]
if you don't know what you're talking about with respect to what this pr entails please shut your mouth

list of people who should shut their mouth

@Bawhoppen @DoctoreMad @kevinz000 @Iamgoofball @Qbopper @Hatfish @Supermichael777 @kilkun @nicbn

**Comment by Qbopper** [comment]
the orange is sour today

**Comment by Hatfish** [comment]
when was the last time you used a cargo console or a gps @optimumtact ?  They ARE a pain to resize with tgui and can't be moved out of the game window to boot (which is annoying as hell if you want to see something behind the massive tgui window you just opened).  Really, the only bad thing that will come of dropping tgui is losing out on the auto-updating GPS units, and even that isn't too bad since you can just spam the use key for the same effect.

**Comment by KieranCat** [comment]
@Hatfish has a valid point. That, and the GPS/crew monitor not auto-updating could probably be fixed to some degree. If anything, a refresh button.

**Comment by Cyberboss** [comment]
Let's be crystal clear here. TGUI ISN'T GOING ANYWHERE WITHOUT A REPLACEMENT

**Comment by optimumtact** [comment]
None of these comments are not relevant to the task at hand

**Comment by kilkun** [comment]
why is it that nobody can ever explain why they think plain html menus are bad? meanwhile opponents to tgui are in basically every pr relating to it continually repeating plain to see issues with it and other js-based menus.

perhaps if maintainers and the head coder would actually lay down a specific reason beyond "because" tgui prs wouldn't be shit up by people like me who want to see it erased in favor of the minimalistic html menus that the game operated on forever (and some servers still operate on)

if it was so great, we wouldn't need massive prs like this that basically overhaul it because it's a bag of dog dookie.

**Comment by optimumtact** [comment]
The reason we are so keen to move to a controlled templating system is it improves code readability and maintainability as well as centralising a lot of previously replicated and copy pasted checks throughout the codebase

Ideally we would have that and a functional working frontend display that is performing up to scratch, we're just not there yet.

**Comment by Iamgoofball** [comment]
@optimumtact 
can we enforce a nanoui tutorial at least when this is done

**Comment by MrStonedOne** [comment]
ITT people who didn't read the pr.

Like oh my gawd

**Comment by kilkun** [comment]
I don't think as the engine stands you can have both pretty and fast as far as menus are concerned. Nanoui is better than tgui, however really I'd just like to be able to open my uplink without giving my CPU an aneurysm and I'm sketch on if this will solve that.

**Comment by vuonojenmustaturska** [comment]
@Iamgoofball I am not actively working on this, working on JS-stuff with IE on one side and byond on another is not something I'm suited for since I wasn't here when TGUI was made and the documentation is kind of nowhere. 

I will promise you that if someone completes this or some equivalent idea that gets merged, i will help porting the templates and writing documentation.

**Comment by MrStonedOne** [comment]
Oh you can do pretty and fast for menus.

Nothing about tgui's slowdown has to do with pretty, it has to do with lazy.

**Comment by vuonojenmustaturska** [comment]
ui_act now gets called, IE no longer barfs on stupid errors doing that. UI data refreshing doesn't really work.

**Comment by vuonojenmustaturska** [comment]
Might as well keep this open to show commits happening, even if they're very uncommon. Still looking for anyone to take this to completion, i can rebase on master if it helps.

**Pull request closed without merging**
