### PR TITLE
Should hopefully fix the airlock having a wall under it on boxstation's emergency shuttle.

### PR DESCRIPTION
**Pull request by Razoozle**
Should hopefully fix the airlock issue.

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Forgot to mapmerge, hang on.

**Comment by Ultimate-Chimera** [comment]
Fixed. Ready for review and merge.

**Comment by Ultimate-Chimera** [comment]
Four commits? Couldn't squash for some reason.

**Comment by optimumtact** [comment]
Don't worry we can squash when we merge.

**Comment by optimumtact** [comment]
anyway looks good to me.

**Comment by Ultimate-Chimera** [comment]
Cool.

**Pull request merged**
