### PR TITLE
Nerfs soap slips

### PR DESCRIPTION
**Pull request by evsey9**
:cl: Evsey9
balance: Because of NanoTrasen receiving complaints on soap being too slippery and causing too many workplace accidents, they have decided to change the cleaning agent to a less slippery one.
/:cl:
Nerfs soap slips down to 4 seconds, which is still enough to apply cuffs. Syndicate soap stays at 8 seconds, since it's the syndicate!
Why: A soap being able to slip you for 8 seconds ( enough to apply cuffs without any effort which is basically GG you're dead ) is dumb and overpowered IMO, since its an easy stun that can be gotten very easily ( the bathrooms for example ).

### CODE REVIEW

**Comment by InsaneHyena** [comment]
I ded

**Comment by optimumtact** [comment]
Why

**Comment by InsaneHyena** [comment]
I ded

**Comment by evsey9** [comment]
Why would a soap slip someone for so long they can get handcuffed?

**Comment by nicbn** [comment]
Not again

**Comment by nicbn** [comment]
How can I slip shave now?

**Comment by PraiseRatvar** [comment]
slipping is becoming an old, dull combat mechanic and honestly i don't want the janitor to fuck me over with green soap and a edagger

**Comment by evsey9** [comment]
@nicbn  just get barber's aid and a syringe gun, it won't make them bald but it will change their hairstyle.

**Comment by nicbn** [comment]
Not enough fun, I wanna hear the
##BZZZZZZZZZZZZZZZZZZZZZZZZZZRRRRRR

**Comment by evsey9** [comment]
Place a soap in a hallway, wait until someone runs over, stunprod ( you still have 3 seconds for that ), shave.

**Comment by nicbn** [comment]
Stunprod is evil

**Comment by KorPhaeron** [comment]
Balance PR with no justification in OP

**Comment by evsey9** [comment]
there, i updated it

**Comment by ExcessiveUseOfCobblestone** [comment]
you should mention it's enough to apply cuffs since that's your gripe with it

**Comment by evsey9** [comment]
mentioned that too

**Comment by ExcessiveUseOfCobblestone** [comment]
@KorPhaeron

**Comment by calzilla1** [comment]
Have you heard the common phrase "Git Gud"?

**Comment by KingPhilipIII** [comment]
I ded plz nerf

**Comment by meeeeme** [comment]
Does this affect the syndie soap? I would keep the syndie one at 8 but the normal one should be nerfed.

**Comment by evsey9** [comment]
@meeeeme All soap uses the same slips, but I can try doing that.

**Comment by Armhulen** [comment]
don't let this garbage go through ty

**Comment by Armhulen** [comment]
soap is rare, and it's a good item to reflect that

**Comment by banthebantz** [comment]
I DED PLS RESTRT

**Comment by evsey9** [comment]
Soap should be used as an item for cleaning not for fucking killing people

**Comment by banthebantz** [comment]
syringe guns should be used to heal not kill people
syringe guns should be used to heal not kill people

**Comment by banthebantz** [comment]
Terrible argument, tons of silly mechanics are capable of killing people that's what makes the game fun.

Soap slipping has been a thing for years and shall continue to be a thing, don't grudgecode and nerf things just because you lack the basic ability to not walk on the huge soap sprite

**Comment by evsey9** [comment]
with this pr it's still a thing,  but you don't get a FUCKTON of time to cuff someone.

**Comment by FantasticFwoosh** [comment]
- What if i told you, you shouldn't be using soap to arrest or cuff people as per generic principle when you can make a stun-prod or simply spilll water?

Come on now, this is infantile to the highest degree.

**Comment by evsey9** [comment]
I guess you have a point.

**Pull request closed without merging**
