### PR TITLE
Completely removes Clown and Janitor borg modules for completely 100% replacing the jobs they were assigned to instead of supplementing and supporting them, along with adding an extra clown slot to make up for the reduction in clowns

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Completely removes Clown and Janitor borg modules for completely 100% replacing the jobs they were assigned to instead of supplementing and supporting them

Adds another Clown slot at the request of @Kylerace 

## Why It's Good For The Game
149504733-17fe7d0a-7e4a-43f0-8f9a-a00de8a3bbdc
149473017-b7e56931-e751-4f5d-9374-1767f9427a22 (1)

janiborgs and clown borgs suck and, by merely existing on the station, completely obsolete their human/lizard/felinid/moth/plasmaman/ethereal counterparts

they're bad cyborg modules on that alone

to make up for the reduction in clowns, and to ensure everything is perfectly balanced as all things should be, the clown job has been given another slot at maintainer request

## Changelog

:cl:
del: Completely removes Clown and Janitor borg modules
add: another clown slot
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
i stole the comics from @JohnFulpWillard

**Comment by JohnFulpWillard** [comment]
HOLY BASED

**Comment by Addust** [comment]
n o .

**Comment by HugoOdaX** [comment]
WTF based Goof PR?

**Comment by Mosslick** [comment]
Based spite PR

**Comment by rellyreri** [comment]
wait doesn't the med/engi modules do that too

**Comment by SgtHunk** [comment]
> wait doesn't the med/engi modules do that too

it seems the only true option is to remove borg...

**Comment by jughu** [comment]
goof you got it all wrong the humans are taking the jobs of the borgs so we have to remove the humans

**Comment by SexmasterWasTaken** [comment]
> goof you got it all wrong the humans are taking the jobs of the borgs so we have to remove the humans

preferable, janiborgs and clownborgs are more fun and less useless

**Comment by theOOZ** [comment]
haha, very funny...

**Comment by Razharas** [comment]
its just a revernge for female maid borgs and its blatant for everyone to see

**Comment by squi1-rasb** [comment]
Goof PR

**Comment by jlsnow301** [comment]
Sweet payback for the time I got noted for killing a janiborg that drove over my art

**Comment by CRITAWAKETS** [comment]
medborg easily obsolete an entire fully upgraded medbay if it just has upgrades, so that'd be a borg to remove aswell apparantly.

miner borg is not as good a miner but can still mine for the entire station to have enough resources if given the proper upgrades too

**Comment by Iamgoofball** [comment]
@CRITAWAKETS 1 mediborg cannot solo all of the medical cases that come up in an average /tg/ round

1 janiborg can solo all of the mess cases that come up in an average /tg/ round

**Comment by necromanceranne** [comment]
> @CRITAWAKETS 1 mediborg cannot solo all of the medical cases that come up in an average /tg/ round
> 
> 1 janiborg can solo all of the mess cases that come up in an average /tg/ round

Well janitorial work is not particularly nuanced so that's a slightly unfair comparison. 

On top of that, which particular medical problem can a mediborg not solve? They can do quite a lot right now, including chemistry, virology (and I think even xenobiology.)

**Review by Kylerace — CHANGES_REQUESTED** [review]
remove the clown borg removal or this gets closed

**Comment by Iamgoofball** [comment]
@Kylerace what benefit does the clownborg provide that is so essential aside from obsoleting a single slot niche job

**Comment by Kylerace** [comment]
another clown

**Comment by JohnFulpWillard** [comment]
Honestly just removing janiborg is already such a massive W that it's worth to do alone.

**Comment by Iamgoofball** [comment]
@Kylerace so if I add another clown to this PR it's fine?

**Comment by Iamgoofball** [comment]
done

**Comment by JohnFulpWillard** [comment]
our chance at ridding ourselves of the worst borg module is being ripped out of our hands by a classic goof moment...

**Comment by Shadowflame909** [comment]
Aren't clownborgs a timegated item?

Clowns have already had their time to shine. What new jokes could a clownborg tell 1 hr into the round?

Not cool to remove a progression tree item, even though we're severely lacking in them goof!!!

**Comment by Kubisopplay** [comment]
Imagine being angry that someone who decides to spend most of the round cleaning is better at it then someone who only technically has it as a job, can be team antag, has hands which let him do innumerable other things, and has no other drawbacks. Truly remarkable goof, you outdid yourself here

**Comment by Donpedrito** [comment]
The janitor borg is _only_ good at cleaning, and in the event that the janitor actually cares that their job is easier, they can Law 2 it to not clean a certain area or even to get a module reset. Like every other borg module, the janiborg can fill an important role when its respective job isn't present on the station; personally, whenever I play borg I choose a module based on which jobs are filled, and I know I'm not the only one.

**Comment by Jackraxxus** [comment]
Thank you for this bait PR goof I can read the upvotes and know who has brain damage it's very useful!!!!!

**Comment by Kylerace** [comment]
@Iamgoofball remove the clown borg removal or this gets closed

**Comment by adamkad1** [comment]
> @Iamgoofball remove the clown borg removal or this gets closed

Yeah i guess, clown borgs arent exactly easy to make anyway

**Comment by LemonInTheDark** [comment]
I don't see the point in removing clownborg, though I gotta recuse myself from the jannieborg discussion cause I main janitor

**Comment by squi1-rasb** [comment]
You can tell people are just about done with goofs shit

**Comment by LemonInTheDark** [comment]
In fact, I wonder if it wouldn't be better to make janitor borg more like janitor, and less of a god of instacleaning

**Comment by LemonInTheDark** [comment]
> You can tell people are just about done with goofs shit

Reddit

**Comment by Time-Green** [comment]
Making the janiborg only clean by turning on his scrubbers and making him go brrrr with a heavy speedpenalty would fix a lot of issues with them dominating the jani-meta

**Comment by optimumtact** [comment]
k

**Pull request closed without merging**
