### PR TITLE
Sexier Reinforced Glass Sprites

### PR DESCRIPTION
**Pull request by ghost**
ported straight from vg

while mapping a hippie-fied version of MetaStation, I took inspiration from /vg/'s MetaClub, too. However, I just LOVED /vg/'s rglass sprites!

:cl: More Robust Than You
spriteadd: Sexy reinforced windows
/:cl:

## **New:**
capture

## **Old:**
yuckyglass

Notice the new sprite is lighter

### CODE REVIEW

**Comment by GunHog** [comment]
Uhh..Would you give us a comparison?

**Comment by ChangelingRain** [comment]
oh boy, more broken shine lines on windows to add to the already broken shine lines on reinforced plasma glass.

**Comment by MoreRobustThanYou** [comment]
@ChangelingRain ?

_Sent from my Google Kindle Fire HDX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ChangelingRain** [comment]
the shine only appears on i-1 to i-4.

**Comment by MoreRobustThanYou** [comment]
@ChangelingRain how to fix it

**Comment by MoreRobustThanYou** [comment]
Also, the new sprite is lighter

**Comment by ChangelingRain** [comment]
In any case, I like ours better and think that you should apply the shine effect to ours instead of porting theirs.

**Comment by MoreRobustThanYou** [comment]
i wouldn't know how

**Comment by kevinz000** [comment]
then stop.

**Comment by GunHog** [comment]
> then stop.

Very nice, Kev. This will certainly encourage newbie contributors to learn and grow instead of leave!

**Comment by CPTANT** [comment]
I seriously don't see the difference.

**Comment by MoreRobustThanYou** [comment]
@CPTANT new sprite is lighter

**Comment by CPTANT** [comment]
The change is so minor that I honestly don't care.

**Comment by CosmicScientist** [comment]
Could you put them on a side by side straight from the file? It might give a better impression of what's changed even if the in game screenshots don't seem to... show much.

**Comment by Militaires** [comment]
i like it. don't get why everyone's so fucking anal, lighten up you pieces of shit

**Comment by WJohn** [comment]
The only difference I can see at a glance is the inner border that was originally kept to keep it similar to the thin-pane windows is now gone.

I'm pretty indifferent to it. No problem with merging it, though.

**Comment by nicbn** [comment]
Can't even spot the difference

**Comment by ChangelingRain** [comment]
@WJohn, there's an error and the shine effect it should have is missing from all but i-1 to i-4, which is why you're not seeing much of a difference.

**Comment by GunHog** [comment]
This is how it looks to me on /vg/
screenshot 2017-09-04 13 02 36

**Comment by WJohn** [comment]
This seems to be pretty massively disliked so I think I'll be closing this, without a major rework that definitely looks better, it's probably best to avoid touching windows that people will have a kneejerk negative reaction to such a widely seen sprite.

**Comment by Bawhoppen** [comment]
It seems to me the only reason people dislike it is because they can't tell the difference with grilles under it. Look at the indivual dmi files and you'll see the change, which I too think is an improvement.

**Pull request closed without merging**
