### PR TITLE
Automatic changelog compile, [ci skip]

### PR DESCRIPTION
**Pull request by Scruffy2**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by AnturK** [comment]
Something went wrong here.

**Comment by daklaj** [comment]
good first pr

**Review by ShizCalev — CHANGES_REQUESTED** [review]
refer to https://github.com/tgstation/tgstation/blob/master/html/changelogs/__CHANGELOG_README.txt

**Comment by ShizCalev** [comment]
nothing to see here.

**Pull request closed without merging**
