### PR TITLE
Removes Freon bypassing atmos hardsuits

### LINKED ISSUE #20371: atmos hardsuits can't survive freon cold
its dumb

### PR DESCRIPTION
**Pull request by Iamgoofball**
...bypassing atmos hardsuits.
:cl: Iamgoofball
fix: Freon no longer bypasses atmos hardsuits.
/:cl:

Fixes #20371

### CODE REVIEW

**Comment by Armhulen** [comment]
Triggered PKP!

**Comment by Haevacht** [comment]
Misleading title -1

**Comment by Iamgoofball** [comment]
i dont see the problem officer

do you not clearly see the connector ...?

**Comment by Iamgoofball** [comment]
i like to call it the firecage special

**Comment by coiax** [comment]
I don't see what the title/description has to do with the actual changes.

**Comment by Iamgoofball** [comment]
@coiax I was being a lazy fuck and instead of making freon start cold I made it just arbitrarily cool shit

**Comment by CPTANT** [comment]
So basically Freon made you cold ON TOP of it reducing the temperature.....

**Comment by Niknakflak** [comment]
Please stop making memey and misleading titles. You are not funnt

**Comment by GunHog** [comment]
Good change, bad title. We **really** need to crack down on this.

**Comment by RemieRichards** [comment]
we had a thread about this, cease.

**Comment by kevinz000** [comment]
THANKS GOOFBALL!!!

**Comment by Cyberboss** [comment]
Fixes ##20371

**Pull request merged**
