### PR TITLE
Fixes MMI to AI law transfer

### LINKED ISSUE #31004: Syndicate MMI Doesn't do what it says it does
The syndicate MMI in the surgery bundle doesn't actually do what it says on the tin, the description says that when the MMI is used to create a cyborg or an AI, it will give the Cyborg/AI syndicate laws. It works perfectly fine for the cyborgs, but when you build an AI with it, the AI is completely normal and has default asimov laws, despite the fact the AI should have the syndicate law-set.

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Fixes #31004

Newly-built AIs were always initialized with the laws of the AI core itself, which default to Asimov, instead of the laws of the MMI. Also contains very minor (tested) touchups to nearby code. 

[Changelogs]:

:cl: Naksu
fix: Syndicate MMIs will now properly transfer their laws to newly-constructed AIs
/:cl:

[why]: 
Bugfix

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
and before anyone checks, mmi/New() was refactored into Initialize() in #27203 but it didn't touch the syndie mmi New()

**Comment by GunHog** [comment]
:warning: :warning: :warning: **Make sure that this does not break directly setting laws on the core!!** :warning: :warning: :warning:

**Comment by vuonojenmustaturska** [comment]
It does. As per our IRC discussion I'll figure out a way to fix this.

**Comment by vuonojenmustaturska** [comment]
image
New commit is tested

**Pull request merged**
