### PR TITLE
examine-code refactor

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
## About The Pull Request

Refactor examine() to build a list that examinate() then joins and to_chats in one go, rather than examine code sending 100 individual to_chats for every knob on the thing.

## Why It's Good For The Game

tldr 
image

## Changelog
:cl: Naksu
refactor: Refactored examine-code
/:cl:

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
this requires touching like 500+ procs so might take a while

**Comment by Tlaltecuhtli** [comment]
would be nice if the blue text "hints" could be disabled from a preference

**Comment by MrPerson** [comment]
This is very, very good.

**Comment by vuonojenmustaturska** [comment]
No runtimes on current commit on sybil so far, I think I got them all

**Comment by AnturK** [comment]
Got some time on sybil and this is conflict prone so going to go ahead with a merge.

**Comment by AzureWildfire** [comment]
it happens to other huds also, not only sec huds

**Pull request merged**
