### PR TITLE
Overhaul mecha logging

### LINKED ISSUE #39227: Mech logging is bad
So the logging of mechs is stored in the mech's VV itself, meaning if the mech gets broken, those logs are gone

### PR DESCRIPTION
**Pull request by optimumtact**
Closes #39227

Removes user access to the log, not needed and that log can get large

removes all the internal log vars and passes all logging through to a
new log file, the mecha log

This somehow got smashed into the standard logging in that logging overhaul, but should not have been.

:cl: oranges
del: Mecha internal logging removed, admin only
tweak: Mech logging overhauled to not use an internal list
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
yes I know this doesn't compile

**Comment by Qustinnus** [comment]
this doesnt compile

**Comment by AnturK** [comment]
Remind me not to trust what PR author is saying.

**Comment by ShizCalev** [comment]
Fixes #39227 ?

**Comment by optimumtact** [comment]
Yes it will

**Comment by ShizCalev** [comment]
compile

**Comment by optimumtact** [comment]
Soon

**Comment by Cyberboss** [comment]
Your PR is getting old. Either Travis CI is failing, it is still labelled work in progress (change this by adding `[READY]` to the start of your title), or there are unaddressed change requests. This may be closed soon to free up space on our tracker if it remains idle. In the event that it is, please ask in #coderbus on Rizon for it to be reopened once you have resumed work on it.

**Comment by Qustinnus** [comment]
add a good first pr for this guy and maybe a needs help tag

**Pull request closed without merging**
