### PR TITLE
The supermatter now alerts ghosts when it dusts people

### LINKED ISSUE #27662: SM dusting does not show deadchat notice.
Possibly other dusting sources too.

### PR DESCRIPTION
**Pull request by F-OS**
:cl:
fix: NT has installed their patented SPECTRAL ALERT SYSTEM in the SM,
/:cl:

Why?
Fix PRs shouldn't require justification.

Fixes #27662

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
this aint a fix

**Comment by F-OS** [comment]
yes it is

**Comment by coiax** [comment]
I think it might have been that ghosts weren't being notified when someone died, where the cause of death was the SM. Not that the SM needed a special notification.

**Comment by F-OS** [comment]
It's nice for ghosts to have a special notification though as SM dustings can cause delamination and plus it's a very rare type of death

**Comment by coiax** [comment]
Yes, but this doesn't fix the bug. If the bug were fixed, ghosts would get two messages when someone SM dusted.

**Comment by Cyberboss** [comment]
Not a good fix, fix it in dust()

**Pull request closed without merging**
