### PR TITLE
Makes Narsie Rune take 80 seconds instead of 50 seconds

### PR DESCRIPTION
**Pull request by Hoolny**
## About The Pull Request
Increases Narsies cult summon time into one that can actually meet backlash from the crew to start a fight against
## Why It's Good For The Game
Narsie ritual after being done pretty much ends the game and kills everyone near it 50 seconds isn't nearly enough for the crew to get together and go after it.

Such a big thing should take longer 2 minutes would be enough although I am flexible with the time as long as it's more than a meet 50 seconds
## Changelog
:cl:
balance: increase narsie summoning time from 50 seconds to 80 seconds
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
have you considered not letting the cult convert/kill everyone

**Comment by optimumtact** [comment]
The 50 second timer is meant to allow heroic last plays by individual crew, it's not designed to encourage a final giant pvp team vs team battle between teh crew and cult.

by the time cult is summoning narsie rune they've usually already won

**Comment by DAKKA-WAAAGH** [comment]
This seems like a PR put up out of frustration rather than a genuine concern for game balancing. While being able to start drawing the rune is normally a bad sign for the crew, 50 seconds is more than enough time to disrupt it; in some cases it's more than enough time to completely defeat the Cult in one go.

**Comment by SethLafuente** [comment]
> This seems like a PR put up out of frustration rather than a genuine concern for game balancing. While being able to start drawing the rune is normally a bad sign for the crew, 50 seconds is more than enough time to disrupt it; in some cases it's more than enough time to completely defeat the Cult in one go.

it is not more than enough time by the time the crew makes it if they even make it the rune is already summoned

there are far more positives by increasing its time than keeping it at 50 seconds

**Comment by SethLafuente** [comment]
> The 50 second timer is meant to allow heroic last plays by individual crew, it's not designed to encourage a final giant pvp team vs team battle between teh crew and cult.
> 
> by the time cult is summoning narsie rune they've usually already won

image
image

if the cult is summoning narsie before the shuttle can even be called there is a clear flaw in the current system

**Comment by optimumtact** [comment]
that's like, your opinion man

**Comment by SethLafuente** [comment]
Narsie summoning sight being 50 seconds is wrong in a bunch of ways but currently, the player base isn't able to comprehend it and I don't care nearly enough to argue a simple point if its boiled down to "opinion"

**Comment by CRITAWAKETS** [comment]
i actually would've liked it to be increased. though 120 is too much, but something closer to 80 should allow a valiant last effort. right now it's not enough time to reach the area most of the time.

**Comment by wesoda25** [comment]
If you want to increase it then at least make it so that one person doesn't have to stand still the entire time. Attach it to a location, like a special generation shield rune effect which if so much as touched (by a non cultist) cancels the summon.

**Comment by SethLafuente** [comment]
> i actually would've liked it to be increased. though 120 is too much, but something closer to 80 should allow a valiant last effort. right now it's not enough time to reach the area most of the time.

alright we are back

**Comment by AtomTheProphet** [comment]
80 Seconds is much more reasonable.

**Comment by moocowswag** [comment]
on one hand, a longer summon time means you cant as easily summon before shuttle docks at centcomm after waiting for shuttle to leave to start the summon.


on the other hand i dont want to watch a bar fill up for 80 seconds and i dont think anyone does.

**Comment by optimumtact** [comment]
there's no reason to adjust this, unless you can show cult win rate is well above 50%

**Pull request closed without merging**
