### PR TITLE
Changes PA computer sprite and fixes east facing sprites

### PR DESCRIPTION
**Pull request by ghost**
~~PA sprite now comes with mostly invisible pixels to save myself crying whenever I miss it with a cable coil and wire the floor underneath. The most visible example of it in-game (in case you're not looking at the .dmi) is when it is moved:~~
pasprite
~~When on any tile and stationary, I found it next to impossible to identify they existed. If you look between it and the adjacent tiles left and right, you might see you have to look for it. Alpha was set to 10 out of 255 in my editor. I did this because I didn't want to change the sprite itself (I'm a terrible spriter) and it's frustrating to require pixel-perfect precision when you have a dark computer frame on a dark tile.~~

~~Only the interior of the sprite's blank space is filled in for the two sprites of the one shown and the one where there is wiring. I did not do it for the animated holo-computer/active sprites.~~
**Computer sprite is back to normal now.**

Along with this I fixed the glaring issue with a PA facing east by repositioning the end/particle shooting sprites. This is easily visible on metastation (toggle the PA on and set it to 1 or higher) if you want to do a quick check of what it had beforehand.

### CODE REVIEW

**Comment by Jordie0608** [comment]
The var `mouse_opacity` has this same effect without the ugly alpha-washing of a sprite

**Comment by CosmicScientist** [comment]
Er?

**Comment by PKPenguin321** [comment]
mouse_opacity effectively makes the item take up the whole tile without actually having a sprite that covers the whole tile so you can click it easier
we use this for items when they're placed into backpacks, kudzu vines, other fun things

**Comment by CosmicScientist** [comment]
Oh I see! That's how you do that! I'll sort this out when I'm more awake then and get rid of the alpha! Thank you!

**Pull request merged**
