### PR TITLE
Restores mech plasma cutter damage

### PR DESCRIPTION
**Pull request by zxaber**
:cl: Zxaber
balance: Restored mech-mounted plasma cutter damage to their former glory. However, like before, this glory is only applicable in low-atmospheric conditions.
/:cl:

The reasoning for the plasma cutter nerf (easily mass producible, too good compared to alternatives) doesn't really apply to mech cutters.
- In order to use the cutter itself, you have to build the mech too(50 metal sheets and some glass for the frame, 10 more metal and five plasteel for the outer shell, actual assembly time, and time to charge whatever cell you want). While you could conceivably hammer out a few Ripleys with cutters to combat whatever emergency is happening, having the materials to do so means you most likely have the ability to make something better anyway. 
- A Durand with actual combat weapons isn't terribly more difficult to make than a Ripley, but is vastly more powerful.

Several people have expressed a desire for mechs to have a P-KA, but no one has actually stepped up to the plate. Meanwhile, mechs that are generally only made for mining deserve to have some method at fighting off lavaland enemies.

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
Oh wow, it's almost like this is the same damn solution I made in #40495

**Comment by SgtxRootbeer** [comment]
We wouldn't have this issue if @imsxz didn't unwarrantedly nerf it in the first place

**Comment by ExcessiveUseOfCobblestone** [comment]
This is such an odd hill to die on I really don't understand lol.

**Comment by GunHog** [comment]
The cutter is the only ranged weapon a Ripley can use. There is no PKA for it, and coding one could be somewhat hairy, as you would either copy-paste the unique PKA code, shove a hand-held one into a mech mounted version (which would allow it to support upgrades), or code it to a gun that does not support upgrades.

**Comment by zxaber** [comment]
It just bugs me that we got a nerf with no real reasoning behind it. Imsxz gave us a good explanation for hand-held cutter nerfs, but none of it applied to mech nerfs (or the plasma turret nerf, for that matter, but that one was also reverted). Functionally, we got the equivalent of a nerf PR with an empty "why" section. Do you have a good reason for the original nerf?

**Comment by optimumtact** [comment]
this pr was already knocked back once, what makes you think I will accept it now?

**Comment by SgtxRootbeer** [comment]
1, We have a fairly legitimate reason for un-nerfing the cutter
2, the conspiracy theorist inside me thinks you just hate my avatar

**Comment by Whoneedspacee** [comment]
Coming from someone who has played lavaland shit for literally almost a year solid I can say shit was balanced around these mechs having cutters.

Though if I’m being honest it’s unnecessary to actually killing shit and I wonder if you have a good gameplay reason besides shaking it up from a pka all the time.

It really shouldn’t have been nerfed, but I now don’t really see a reason to buff it again. Firefighters can already cross lava and move super fast which is reason enough to use them.

**Comment by zxaber** [comment]
I just wanted to open up conversation. Asking _why_ the mech cutter got nerfed just gets me brushed off, and no one can, or even tries to, give me a answer whatsoever.

It takes a ridiculous amount of shots to kill a goliath now. Legions are borderline unkillable since you can't kill them before they swarm up. These mechs' main role they are built for is mining; they ought to be able to fight the most common enemies down there.

**Comment by SgtxRootbeer** [comment]
It was nerfed because the author who wanted to nerf normal plasma cutters couldn't read code and/or didn't understand balance. And oranges decided not to actually read the code he was merging either. 

We have systems in place to prevent this stupid shit from happening, damnit.

**Comment by Repukan** [comment]
It's a mining mech, not a fauna fighting mech.

Even with the damage cut off you can still run away/strafe off.

Your ash-proof, space proof, health shield doesn't need to full fill a combat role with a high damage delimbing beam.

Just on low pressure it's a meme when this mech can easily vent areas as well

**Comment by SgtxRootbeer** [comment]
@Repukan fine then, we'll remove the pka from the game and simply give the miner a plasma cutter at roundstart.
its a "mining" occupation, not a fauna fighting one. why should a miner, especially one with all the lavaland gear be able to fight fauna, or for that matter, do combat in the first place if he's supposed to be mining rocks?

once again, repukan proves they have nothing but wrong opinions to share.

**Comment by ExcessiveUseOfCobblestone** [comment]
The pKa is way more fleshed out than the PC, and the desire is to remove the PC in favor of a pKa upgrade that functions similarly anyways.

Don't think he said anything that warranted a personal attack besides you disagreeing with him, I'm not sure how that is going to encourage anyone to take you seriously.

**Comment by davethwave** [comment]
Perhaps make said upgrade before nerfing them to oblivion? Also the deep fryer is a lot more fleshed out than the microwave yet there is no discussion to remove that. Discussing about how fleshed out something in comparison in order to remove it is just ridiculous...

**Comment by ExcessiveUseOfCobblestone** [comment]
Fryers and Microwaves perform different functions (Frying an item as opposed to making an intermediate for a prepp'd meal), PCs and pKAs do the same specific functions: Mining/Killing Lavalandies.

At worse the upgrade/removal would be done simultaneously in 1 PR. The nerf was already done for different reasons, which you can read at your own leisure.

**Comment by SgtxRootbeer** [comment]
That does not fix the problem that the mech is imbalanced to use on Lavaland and we have zero alternatives in the present. 

Until you have a mech pka coded and ready to go, we should revert the nerf because it was done for no legitimate reason. Don't leave the game in a half-assed state.

**Comment by zxaber** [comment]
Except the nerf was not done for any given reason, Cobble, which was half the point of this PR. We were given reasoning behind the handheld cutters, but it does not apply to mechs.

Rootbeer, I do agree with Cobble in that there's no need for personal attacks. We can argue our point on its own merrit.

**Comment by ninjanomnom** [comment]
Miners have enough goodies I'm willing to force them to deal with this pain until someone makes a proper alternative like has been talked about. Any other maintainer can feel free to disagree but I prefer the consistency.

**Pull request closed without merging**
