### PR TITLE
Updates Default fps

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Sets default fps setting to 60 fps.
Most users likely don't realize that they can run a framerate higher than the tickrate or would assume that 'fps max = 0' would mean an uncapped framerate.

I've been using this for a while and it's butter smooth.

## Why It's Good For The Game
It's just better - Way smoother. People might not know they can make the game smoother themselves.

## Changelog
:cl:
Changed default fps setting.
/:cl:

### CODE REVIEW

**Review by ShizCalev — APPROVED** [review]

**Comment by Jared-Fogle** [comment]
That's not how you make a changelog.

**Comment by actioninja** [comment]
Closing this because movement animations are still fucky and the effect is more pronounced on 60 fps.
It's not as smooth as it could be, something to speed up glide size for very high speeds at minimum needs to be implemented.
I find the game slightly nauseating at 60 fps because of the camera juddering this causes.

**Comment by Axanthic** [comment]
> Closing this because movement animations are still fucky and the effect is more pronounced on 60 fps.
> It's not as smooth as it could be, something to speed up glide size for very high speeds at minimum needs to be implemented.
> I find the game slightly nauseating at 60 fps because of the camera juddering this causes.
> Nothing wrong with the pr itself though, it does as advertised.

This movement issue is unrelated to FPS.
I think this change is important since I and I'm sure many other users saw the fps_max = 0 setting in-game and assumed it meant 'uncapped' as it does in every game.

Look at these videos and explain in what ways 20 FPS looks better?

The default setting should be the best setting for most users. I also want to make another change that when 0 is used for fps_max it shows the actual frame rate it's locked to as opposed to just '0'

20 FPS
https://drive.google.com/uc?id=1zz5tQBCCY1QrL_TS33oZBh19hQx-6Mia

60 FPS
https://drive.google.com/uc?id=11YUDm2XwnWEXYmTUrq6gX0OuBWHKvkOS

20 FPS Jumping test
https://drive.google.com/uc?id=1OptrWMXsPVY7RQtIiyiYEc30FRRoIti2

60 FPS Jumping test
https://drive.google.com/uc?id=1ustaQB2RIDr0U45I7QQVZoAupJ0BIa-g

**Comment by Axanthic** [comment]
@actioninja Can you please reopen?

**Comment by actioninja** [comment]
Seems like due to some recent byond changes the issue is equal across framerates. auto glide size should probably still happen though.
Just so you know, this will not update people that still use 0 fps it will only be for settings resets and new players.

**Comment by Axanthic** [comment]
Fuck oranges
image

**Pull request closed without merging**
