### PR TITLE
Adds logging to uplinks, spellbooks, and the codex ciatrix

### PR DESCRIPTION
**Pull request by TemporalOroboros**
## About The Pull Request
- Adds logging to various antagonist uplink-equivalents

## Why It's Good For The Game
- It makes it easier to tell who is buying what equipment and how often

## Changelog
:cl:
config: Added a config setting for logging uplink purchases.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
@MrStonedOne config touched

**Comment by LemonInTheDark** [comment]
Why should logging uplink purchases be config?

**Review by spookydonut — APPROVED** [review]

**Comment by TemporalOroboros** [comment]
> 
> 
> Why should logging uplink purchases be config?

Because all of the logging options are config.

**Comment by LemonInTheDark** [comment]
Good god they are

**Pull request merged**
