### PR TITLE
Removes the .psd folder from icons.

### PR DESCRIPTION
**Pull request by praisenarsie**
pointless folder, only 1 seemed useful (which was the airlock one) but the rest are unneeded/obsolete.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:

sources are handy

**Comment by ShizCalev** [comment]
👎

**Comment by outbools** [comment]
@Iamgoofball @ShizCalev you still can get them thanks to git, they are not part of development nor a part of game

**Comment by Cyberboss** [comment]
Remove the ones that aren't in use, keep the ones that are

**Review by ShizCalev — CHANGES_REQUESTED** [review]
only remove locker_template

**Comment by optimumtact** [comment]
These are harmless

**Pull request closed without merging**
