### PR TITLE
Workaround to prevent slippery components from flooding SSgarbage

### PR DESCRIPTION
**Pull request by Cyberboss**
Only create it when needed instead of recreating all the time

### CODE REVIEW

**Comment by optimumtact** [comment]
so much for components eh

**Comment by Cyberboss** [comment]
Exploratory architecture

**Comment by ExcessiveUseOfCobblestone** [comment]
Why do components need to constantly delete and recreate themselves?

**Comment by Cyberboss** [comment]
They now don't delete themselves, that was me being lazy and shitty old code making the problem worse.

**Comment by ExcessiveUseOfCobblestone** [comment]
YOU MADE MY ARCHAEOLOGY COMPONENTS DELETE THEMSELVES REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Pull request merged**
