### PR TITLE
Lube is now cherry-flavored!

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
tweak: Nanotrasen now has added nanobots that secrete cherry juice into Space Lube.
/:cl:

ONE DAY WOODY GOT WOO- AHHH LYNCH MOB

### CODE REVIEW

**Comment by nicbn** [comment]
No.

**Comment by MoreRobustThanYou** [comment]
Yes.

**Comment by nicbn** [comment]
Yes.

**Comment by MoreRobustThanYou** [comment]
fuck I realized this was added already... i just added it to the wrong file

**Comment by nicbn** [comment]
What

**Comment by MoreRobustThanYou** [comment]
i added the flavor to the lube recipe... I notice it was in a recipes file and then looked for the reagant file... 

```	taste_description = "cherry" // by popular demand``` in

**Pull request closed without merging**
