### PR TITLE
Modsuit actions no longer go on cooldown when selected

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Modsuit actions no longer go on cooldown when selected, only when actually used. So you can select an action and use it
## Why It's Good For The Game

I don't even know why this was a thing it just makes modsuits more uncomfortable and unpleasant to use. I see no reason for it to exist so i'm removing it. @Fikou 
## Changelog
:cl:
qol: Modsuit actions no longer go on cooldown when selected
balance: microwave beam module is on a 4s cooldown not 10s
/:cl:

### CODE REVIEW

**Review by Fikou — CHANGES_REQUESTED** [review]
remove the 0.5 cooldown from all the togglable modules if youre removing functionality of it
the intention of the mechanic was spam prevention which probably wasnt needed so yeah its probably fine (check if it doesnt do anything weird if you spamclick with atrocinator/sphere form)

**Comment by carlarctg** [comment]
bro how is this balance

**Comment by Loafin34** [comment]
you're changing cooldowns bro

**Comment by Fikou** [comment]
> bro how is this balance

you are able to use high cooldown modules instantly after pulling them out that changes balance

**Comment by carlarctg** [comment]
i tested a lot of modules until i gave up because there are way too fucking many they all work

also found out microwave beam has 10 second cooldown thats insane. who let them cookn't

merge redy

**Pull request merged**
