### PR TITLE
antag token please kor

### LINKED ISSUE #13536: beer-goggles, armor, and beanbags don't spawn in the bar backroom
Quite a problem for late-joining bartenders being without everything they need but their gun (which probably got stolen by the clown by that point)

### PR DESCRIPTION
**Pull request by Bawhoppen**
fixes https://github.com/tgstation/-tg-station/issues/13897 (I think thats what he meant)

fixes https://github.com/tgstation/-tg-station/issues/13536

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>didnt mapmerge

**Comment by Bawhoppen** [comment]
I did? DID I FUCK UP

**Comment by Bawhoppen** [comment]
WJ YOU BETRAY ME

**Comment by Bawhoppen** [comment]
fucking commie map merger

**Pull request closed without merging**
