### PR TITLE
Makes the lavaland beach bum biodome better

### PR DESCRIPTION
**Pull request by EuSouAFazer**
## About The Pull Request

Makes the beach biodome a lot more up-to-date.

## Why It's Good For The Game

This place and role needs some help.

## Changelog
:cl:
qol: The beach bum biodome looks a lot better now, alongside some item additions.
fix: The piping in the beach bum biodome will no longer go through walls unecessarely
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
Why doesn't the bartender get a door anymore? Maybe a windoor at least?

**Comment by EuSouAFazer** [comment]
> Why doesn't the bartender get a door anymore? Maybe a windoor at least?

The door next to the balcony looked very ugly

**Comment by Helg2** [comment]
Update branch to prevent conflicts please, it was updated recently.

**Comment by Pumpkinoe** [comment]
pictures :)?

**Comment by dieamond13** [comment]
bitrunning also has a level of this so you might wanna change that too

**Comment by notfrying1pans** [comment]
I'm not a fan of wooden walls being partially added to some areas, I think they looked fine before being sandstone.

**Pull request closed without merging**
