### PR TITLE
Whitelists vs Blacklists

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Whitelists are preferable to blacklists

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@tgstation/commit-access if anyone wants to rewrite this to make it sound nicer please feel free to do so

**Comment by Iamgoofball** [comment]
hi yes while this is the sane thing to do, I really don't agree with this as it goes against ss13 tradition of slapping just about anything together, and will result in endless arguments about what makes "sense" for whitelists. Additionally, the example in the text (bags) is the biggest offender of "if we turned this into a whitelist the whitelist would be 1500 lines long"

**Comment by Cyberboss** [comment]
I actually agree with goof, what brought this up?

**Comment by davethwave** [comment]
https://m.youtube.com/watch?v=gRdfX7ut8gw

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss lets go with 38010 where the stationloving uses a blacklist

Personally I think it's a bit backwards to have the person PRing the change to anticipate future PRs that may/may not ever exist rather than the person PRing the new feature make the necessary changes.

If there is a blacklist for species, then species.dm should have a reminder that there is a blacklist for it (or hell don't and we see how it goes, it's ss13 you lose to BS all the time). THAT should be attached on the PR generating the blacklist.

Alternatively you could just make a blacklist readme that people should refer to and add on as needed. With proper filing it should be easy to look in the list to see if your thing is applicable to one.

**Comment by optimumtact** [comment]
yall bikeshedding about a contributing guideline that can easily be ignored if there is a real need

**Comment by ExcessiveUseOfCobblestone** [comment]
If you plan on enforcing it as written it's not bikeshed.

Not that you couldn't just enforce it off the record so 🤷‍♂️

**Pull request closed without merging**
