### PR TITLE
Reverts #32906: "Buffs Laserpointers"

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/tgstation#32906.

@KorPhaeron You seem like you might want to have some sort of involvement in this.
Let's get some historically good maintainers in here, too: @ShizCalev @Cyberboss
I'd tag every maintainer but I don't know the full list and can't remember the code to tag them all.

I imagine this'll be closed regardless, but I at least want some sort of headcoder and other maintainer input on this because it's clear that it was merged in very early hours to prevent people from seeing the change get in. This is a bad change to the codebase because:
* We have historically shown that we don't want to discriminate against a sect of players just because they like cosmetic cat ears
* The primary people who try to insist that catpeople are fetish content do not play Bagil regularly and do not ever interact with the players who do play catpeople, or if they do, allow their predetermined bias to be unshaken in spite of any contradictory evidence and usually end up disliked by those players
* The change itself is snowflakey and badly-coded with organ checks out the wazoo instead of a helper proc and a direct call of  `Move` to `targloc` rather than a `step_to` that would properly use it
* Using the pointer in this way doesn't have a unique message for the user, breaking consistency with the rest of the laser pointer uses
* The original PR was clearly meant as a joke given the low-effort PR body and the fact that the original PR didn't even compile before a maintainer fixed the code for them, and was meant to poke fun at a player who is now at a mechanical disadvantage for their preferred roles despite having contributed more to the server in half a year than most people do ever
* It doesn't check for the kitty ears object, meaning that players who want to be catpeople without having poorly-coded mechanics put them at a disadvantage can still do so
* It doesn't check for even blindness, meaning that cats have an in-built third eye specifically for detecting the presence of laser pointers
* This goes without saying, but deliberately making sure nobody who can oppose the change is online before speedmerging it is clearly underhanded and an abuse of maintainer privileges in the first place

Ain't we better than this? I feel like it's silly to simultaneously tell people not to take Fwooshposting seriously and then immediately fall into exactly what he wants. I don't play a catperson and probably never will, but I think anyone excepting the vocal minority of bitter and jaded community members who rarely play can agree that this is a bad change for multiple reasons!

### CODE REVIEW

**Comment by ShizCalev** [comment]
Was merged during a freeze. Valid salad.

**Comment by Qustinnus** [comment]
no it wasnt

**Comment by Qustinnus** [comment]
https://github.com/tgstation/tgstation/pull/32586 it has been over for 5 hours now

**Comment by Dorsisdwarf** [comment]
I think the change was stupid but are you for real with that PR body? 

Like, please tell me that's a joke.

**Comment by RemieRichards** [comment]
>I'd tag every maintainer but I don't know the full list and can't remember the code to tag them all.

The tag also doesn't work for you, so.

**Comment by Dorsisdwarf** [comment]
Seriously though trim the joke reasons out of the PR or it'll probbably get kicked to death by shitposters

**Comment by Xhuis** [comment]
@ShizCalev It does seem the freeze was over. I changed the PR title in spite of that - I'm sorry for spreading misinformation on that front.

@Dorsisdwarf I'm irritated with the amount of times people have tried to discriminate against a player minority that they don't interact with, and I figured that putting some effort into giving my reasoning for reverting the change might be better than being as low-effort as the merging maintainer.

**Comment by The-clown-known-as-Pepe** [comment]
Why did that PR even got merged.

Speedmerge this 👌

**Comment by Dorsisdwarf** [comment]
> My cat doesnt like laser pointers so logically we have to remove this

**Comment by Xhuis** [comment]
Oh, c'mon now, I was just trying to show that I wasn't all *super serious* about it. I did remove that from the PR body, anyways.

**Comment by The-clown-known-as-Pepe** [comment]
better unsubscribe from this PR before shitflingers come

**Comment by Dorsisdwarf** [comment]
also 👍 this PR, it was an amusing joke PR but oranges ruins every joke

**Comment by Qustinnus** [comment]
I'd like to point out a few things

1. The freeze was over when this was merged

2. The code for checking if someone is a catperson was already in the code like this, a helper would've still been better, though. Not really that big of an issue IMO

3. eye protection stops bright flashes of lights from hurting your eyes. They don't block you from seeing light, like from a laser pointer.

4. Cats loving laser pointers is a stereotype, genuinely going "but one of my cat doesn't even like laser pointers" literaly doesn't matter. laser pointers making cats pounce them is just a things people recognize.

5. "We have historically shown that we don't want to discriminate against a sect of players just because they like cosmetic cat ears"

literaly who is we? You? The people on sligcord that unironically thought this PR stuns you for 10 seconds?  If with "we" you mean the maintainers, then you are wrong. because this was merged, and approved by 2 maintainers.

only thing about this PR that was a bit questionable was oranges early merge.

**Comment by lzimann** [comment]
lmao cat people rekt

**Comment by Xhuis** [comment]
@Qustinnus When I say "we" I cite most of the players, contributors, and maintainers. I'm sure you've heard the saying "one bad apple spoils the bunch" and that still applies here. Just because two maintainers who worked to get the PR speedmerged when everyone as was sleep doesn't mean that every maintainer wanted it, and I guarantee that @KorPhaeron didn't.

**Comment by Kraseo** [comment]
another low effort post & close from @lzimann

**Comment by ShizCalev** [comment]
I play a cat person and I found it hilarious, but it wouldn't have merged it in the end since it seems unbalanced as fuck to be able to instastun someone with a laser pointer.

**Comment by Qustinnus** [comment]
I think thats the players and contributors you hang out with, because in that regard the players and contributors I hang out with are the complete opposite of that. @Xhuis

**Comment by Xhuis** [comment]
Let's get their thoughts, then. Oranges and Antur excluded since they already gave theirs. @ChangelingRain @WJohn @Razharas @Jordie0608

**Comment by Qustinnus** [comment]
razharas isn't even an actual repo member anymore though. Also you forgot @ninjanomnom

**Comment by lzimann** [comment]
I am sure Kor will open if he wants this gone. Also WJohn has no power over this and Raz is no longer a maintainer.

**Comment by Xhuis** [comment]
@Qustinnus I thought Raz was the great timeless one. Damn. Sorry for the ping, Raz. You can go home now.

**Comment by RemieRichards** [comment]
>xhuis pinging joan

toplols.

**Comment by Xhuis** [comment]
It's merciless revenge for all the clockcult PRs that she pinged me in.

**Comment by Arianya** [comment]
While I doubt my opinion on this is in any doubt, I will just note that I don't play as a cat and I'm not a fan of the change mechanically or even as "flavour".

I'll also note some hypocrisy in merging something that is a snowflake check for what should realistically just be a funny message considering how that's generally been seen in other PRs, most recently #32918.

**Comment by ShizCalev** [comment]
Scalerot when

**Comment by Qustinnus** [comment]
@Arianya >snowflake check

how is it a snowflake check? It's the only way to check if someone is a catperson in this shitty mutant system. If you want to get rid of snowflake checks, you have to remove catpeople code.

**Comment by Arianya** [comment]
Two check on every human/carbon in range every time a laserpointer is pointed is pretty snowflake, certainly more snowflake then other PRs that have been denied on similar grounds before. I don't disagree that snowflake checks are needed to some extent, but my point was more the inherent hypocrisy and inconsistency in allowing them in this case when similar "flavour" or "emote" check

Its a minor point, but one worth considering, still.

**Comment by Qustinnus** [comment]
that's fair. I think the grounds for that other PR was that it was simply fluff and not mechanical, while this PR has a direct affect so it makes more sense.

**Comment by Arianya** [comment]
As I say, I do object to the mechanical side as well, especially because its uncounterable (yes yes, all of you typing "just don't play cats" are very funny and original) and will lead to memery about "Its not my fault the cat secofficer got ganged on by revs, I was just pointing a laser pointer!"

**Comment by Qustinnus** [comment]
borgs can be stunned for ages with laserpointers btw

**Comment by Dorsisdwarf** [comment]
coding a nerf pr

**Comment by duncathan** [comment]
Hi I play catpeople sometimes and also I'm a maintainer and also this feature was fucking hilarious so I want it to stay

**Comment by Arianya** [comment]
@Qustinnus non-AoE, RNG stun that is counterweighted by a borg's incapability to be stunned by any non-EMP/non-flash means

@duncathan I think this can exist as a flavour thing without mechanical implication tbh

**Comment by duncathan** [comment]
if someone wants to do that that's cool but just removing it entirely is p lame

**Comment by Qustinnus** [comment]
I have some ideas I'd like to implement if either this gets merged, or when Dorsisdwarf's PR is merged

**Comment by imsxz** [comment]
The borg stun via lasers is 99% chance with a t3 laser iirc, over 100% with a t4 laser.

Side note, can cat people use this to warp themselves into places? More of a catpeople nerf than buff if so. Getting into bridge and such, getting over lava/chasms, etc.

If the above is possible, ~~im gonna start playing a cat on bagil~~ I'd suggest nerfing this silly mechanic but never outright removing it. I think the PR is funny but I'm a bit bias when it comes to cat discrimination.

**Comment by Qustinnus** [comment]
no they can't warp themselves into places

**Comment by calzilla1** [comment]
ITT furry salt

**Comment by Hatfish** [comment]
should be countered by eyewear tbh, bowmans already counter cat ear hearing damage so they aren't shat on as sec so hudglasses should too

**Comment by Xhuis** [comment]
You can't help but feel sorry for calzilla, really. He must be so proud of himself.

**Comment by calzilla1** [comment]
:^)

**Comment by KorPhaeron** [comment]
Needs to respect eye protection or joining security needs to remove cat ears. Having officers get taken down by an unblockable hitscan aoe stun (and their weapons turned on the rest of sec) sounds annoying for me as a human player

Not sure why it wasnt just an on click thing like borgs either

I think it's funny but weirdly balanced right now and I think making it sane would be better than a full revert

**Comment by deathride58** [comment]
"Weirdly balanced" is an understatement.

Beg RnD for an antidrop implant, get someone to implant a cat organ onto you, steal a laser pointer, and watch as you can suddenly teleport anywhere you see.

Also, why was the original PR even speedmerged in the first place

**Comment by imsxz** [comment]
@deathride58 dummy it's only in a view range of 1

**Comment by optimumtact** [comment]
it wasn't speed merged, I just didn't see the flow of events of it being frozen and then reopened, so it looked like it had been open 24 hours

**Comment by optimumtact** [comment]
>This goes without saying, but deliberately making sure nobody who can oppose the change is online before speedmerging it is clearly underhanded and an abuse of maintainer privileges in the first place

Am I supposed to make sure the entire server population has seen a pr before merging it xhuis, should I go around with an excel spreadsheet of every ckey and make sure everyone signs off?

**Comment by optimumtact** [comment]
oh by the way @Arianya I don't agree with the closing of #32918 and I told leoz as much in irc, however, I am not going to close war with him about it, I told MRTY to take it up with the head coder

**Comment by Qustinnus** [comment]
@deathride58 wtf are u on about you can't just teleport places.

**Comment by Xhuis** [comment]
You have a history of disliking catpeople and I was remembering the grammar and bee PRs of incidents past. While you may not have this time, previous incidents with similar situations hinted to me that this was a repetition of those incidents, and though I apologize for having been misinformed and flaming you because of that, I stand by why I had those assumptions.

**Comment by jughu** [comment]
Just make cats have cateyes so you can replaace your eyes to avoid this

**Comment by PKPenguin321** [comment]
holy molehill mountains, batman

**Pull request closed without merging**
