### PR TITLE
Buffs nuke ops [merge ready]

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
-Adds slug ammo for the M12g Bulldog syndicate shotgun, purchaseable for 2 TC in nuke op uplinks
-Changes the default ammo for the Bulldog to be slug

-Fills the syndicate ammo bag that nuke ops used to start with in the gun locker with slug ammo, plus one each of the other kinds.
-Adds the new "loaded" ammo bag to the nuke uplink, at a bargain price (10TC is a lot to spent on default weapon ammo, after all)

-Makes dragonbreath ammunition less expensive

### CODE REVIEW

**Comment by GunHog** [comment]
WE. ARE. OPERATORS. :+1:

**Comment by SconesC** [comment]
For people who don't feel like looking on their own, can you mention the damage of slugs?

**Comment by WJohn** [comment]
Are these the 60 damage single-shot slugs with no spread? Because thank god <3

**Comment by KorPhaeron** [comment]
Not sure an antag type with a 50% winrate/chance of killing everyone really needs a buff.

Buffing their guns in exchange for removing the hacked AI module might be nice though, would rather see the round rely on the team than ":b have your secborg stun the captain and take him to solars"

**Comment by Dorsisdwarf** [comment]
Shotgun slugs, which can be made by any person from cargo en masse, do 60 brute. 

On an armored HOS, that's three shots to down
(note: syndie buckshot rounds point blank require only two shots to down an armored HOS, but require more from range).

Also I've only even heard of :b get the diiisk once, and seen it one other time. It's not easy to subvert the AI as a nuke op, but it is OP. However, that's not within the urview of the PR

**Comment by KorPhaeron** [comment]
Fair enough. I guess my issue with nuke guns being buffed is that sec guns are so garbage but in the middle of typing this I realized I'd just rather fix eguns and tasers than force nuke ops to use buckshot

**Comment by PKPenguin321** [comment]
\>not sneaking explosive implants back in

**Comment by Dorsisdwarf** [comment]
Nuke ops cannot buy revolvers, they're blacklisted from the gamemode

**Comment by SconesC** [comment]
They 100% can buy revolvers though

**Comment by Dorsisdwarf** [comment]
Then my life is a lie and I have been betrayed at every step :(

**Comment by SconesC** [comment]
>not sending a stealth op with a revolver and telling him to murderbone
>not laughing as he kills more than half the crew because they are way too busy trying to valid the redsuits

**Comment by Lumipharon** [comment]
+1 to giving them default slugs, but I don't agree with giving them a huge ass bag of free ammo.

**Comment by WJohn** [comment]
Yeah the ammo bag is a bit much. Why even bother purchasing other ammo?

**Comment by Nanotransistor** [comment]
I like the extra ammo, at least one extra mag per shotgun. But as has been said, 60 brute is a bit too much and it would render all the other weapons pretty much useless.

Maybe instead, give them a new slug type unique to the Ops, with 40 brute + some stam damage. 40 is enough to crit an unarmed person in three hits, and the stamina damage would help against more armored dudes like the HoS and captain.

Also, another suggestion, make them start with one portable defibrillator. The crew gets two, and they are really good in the hands of someone competent. Seems it would be fair.

**Comment by Dorsisdwarf** [comment]
But... the buckshot already does at least 60 brute point-blank, and it's less affected by armor to boot, because each flechette loses less damage due to damage rounding upwards.
I could remove the loaded ammobag from the closet and put it in the uplink as an "Ammo for all" bundle?

**Comment by Lumipharon** [comment]
>point blank

Making a bag full of ammo buyable is a cool idea. Could do it for different ammo types and even different weapons.
Give the ops a small points break for running a set of the same weapons essentially.

**Comment by Nanotransistor** [comment]
Another possibility would be to just buff the stam damage of those buckshots, so that two or three hits should knock anyone down, giving time to run up to the target and finish them off with a 60 brute point blank shot.

**Comment by SconesC** [comment]
@Dorsisdwarf 

However that requires you to click ON them not behind them for the fires point blank shit tier mechanic

**Comment by Dorsisdwarf** [comment]
@Nanotransistor 
The problem with buckshot isn't damage, it's the shit-tier spread system always hitting your op buddies/your buddies hitting you.

Also Scones, I never actually saw any "FIRES POINT BLANK" during testing - thats just what happens when all 8(?) 10-damage pellets hit one target

**Comment by Tunderchief** [comment]
Thank you for this, dwarf. I don't see the ammo bag being a big deal, you should try it out in a merge and get some gameplay opinions in.

Buckshot was a poor idea, and makes it impossible for Ops to stick together in a gunfight without standing still and getting stunspammed, or killing each other with the terrible spread mechanic. I don't think changing the way shotguns functioned originally was very thought out to begin with, as it leads to fairly consistent friendly fire scenarios.

Kor, so far as i know, I am the only op who regularly subverts silicons. It isn't a common occurrence.

**Comment by Lumipharon** [comment]
Each free mag is potentially 4 extra kills. Giving them that bag of ammo for free is pretty major.

**Comment by SconesC** [comment]
@Dorsisdwarf Not sure what you were doing, was able to do it today on Sybil

It's an awkward mechanic and makes all the pellets hit automatically oh well

Anyways this isn't that big a deal, nuke ops often die because they just ran out of ammo, which is kinda silly. It's the one thing they should for sure have  surplus of.

**Comment by Cheridan** [comment]
Please avoid giving Nuke Ops gear for free, it ruins the point of TC-scaling as they are supposed to be at a gear disadvantage in low-pop rounds.

**Comment by Dorsisdwarf** [comment]
Like the insta-kill minibombs, the deadly shotguns, all those AoE items, two 11-TC bombs, and NVGs?

**Comment by Dorsisdwarf** [comment]
*prod*

**Comment by Iamgoofball** [comment]
Are you fucking kidding me dorisdwarf

**Pull request merged**
