### PR TITLE
Brings back separated chemicals without adding it to glowberries. (Closed because apparently botany was changed.)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Lets you get separated chemicals from strange plants, but not glowberries.

## Why It's Good For The Game

Fruit bombs are fun, but getting them from a berry mutation was too OP. Removing the trait entirely was going too far, but making the trait harder to get is fair.

This might even (indirectly) make GOD WHEAT less common, and therefore make being a doctor more fun, by giving botanists more to do other than make GOD WHEAT.*

*ok that thing about GOD WHEAT was mostly just me trying to appeal to the orange man

## Changelog
:cl:
add: Separated chemicals is BACK, but you still can't get it from glowberries.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
It's not gonna happen

**Comment by optimumtact** [comment]
grind the chems and put them in a grenade assembly

**Comment by optimumtact** [comment]
actually shoudl wait the full 24 hours

**Comment by MrMelbert** [comment]
you can literally farm every strange plant trait using high instability plants, this isn't making it hard to get at all

**Comment by TheSpaghetti** [comment]
> you can literally farm every strange plant trait using high instability plants, this isn't making it hard to get at all

what is that? :/

**Comment by MrMelbert** [comment]
> 
> 
> > you can literally farm every strange plant trait using high instability plants, this isn't making it hard to get at all
> 
> what is that? :/

In new hydroponics, when a plant is over 80 instability (a stat that can be raised fairly easily with mutagen or left4zed), they'll randomly roll traits and chemicals that can appear in strange plants, so you can effectively "farm" strange plant rolls

**Comment by evilcyborgmrt** [comment]
Consider that potassium + water was heavily nerfed after separated chems was removed. This might not be so bad

**Comment by wesoda25** [comment]
4d didn’t die for this

**Comment by TheSpaghetti** [comment]
> > > you can literally farm every strange plant trait using high instability plants, this isn't making it hard to get at all
> > 
> > 
> > what is that? :/
> 
> In new hydroponics, when a plant is over 80 instability (a stat that can be raised fairly easily with mutagen or left4zed), they'll randomly roll traits and chemicals that can appear in strange plants, so you can effectively "farm" strange plant rolls
> 
> edit: here's an example of what's possible now with new hydro and why adding back SC is so dangerous - botany can now get dozens of dangerous chems and traits pretty 'consistently' (as consistent as randomly pulling from the list of chems can be)
> highrolling

Well that ruins this PR.

**Pull request closed without merging**
