### PR TITLE
Fixes the free worker bee getting stuck in the hive and never leaving

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by CosmicScientist** [comment]
Three cheers for goof! Hip hip!

**Comment by CosmicScientist** [comment]
I assume you want #32609 to know this PR exists?

**Comment by RemieRichards** [comment]
You realise they are supposed to go into the box, and regularly do as part of the "Go Roam/Go Home" system?

**Comment by DaedalusGame** [comment]
go play the game and test it then jesus

**Comment by optimumtact** [comment]
chill out k I left goof's comment in there it's just bees yo

**Comment by CosmicScientist** [comment]
Can confirm. goof asked for someone else to PR it and that was the description.

**Comment by arsserpentarium** [comment]
wait...Have this fix been tested?

**Comment by Anonmare** [comment]
According to all known laws of aviation...

**Pull request merged**
