### PR TITLE
Bubblegum's charge now goes the full distance to the target

### PR DESCRIPTION
**Pull request by ChangelingRain**
I had to rework has_gravity() to do what I originally wanted to do so that's this pr now?

Big change; has_gravity() is now an atom proc instead of a global, so you can actually override it.
Removed mob_has_gravity() because it'd be redundant.

Basically; instead of bubblegum's charges having a max range of 7, they have a max range of 'however many tiles it is to the target'

### CODE REVIEW

**Comment by lzimann** [comment]
Wasn't this changed recently to charge in that circle instead of like this?

**Comment by ChangelingRain** [comment]
why the fuck would bubblegum's charge be a circle

**Comment by lzimann** [comment]
uhh that marker that shows where the charge will be, not the charge being a circle

**Comment by ChangelingRain** [comment]
It still charges in the general direction of the indicator; the recent changes were to prevent it wandering off to the side at you like a huge murderous ass.

**Comment by Ergovisavi** [comment]
I'm fundamentally opposed to his charge ending in a location other than where the targeting indicator says it will.

Either the tell shows his final location, or the visuals of the tell need to get changed. I fixed bubblegum's charge because the game would literally lie to you and tell you his charge would end in a location when it clearly didn't, which this PR appears to intentionally be recreating?

**Comment by ChangelingRain** [comment]
Mmm. The tell is now a visual effect that should show up pretty well if bubblegum is actually in vision range, instead of the marker.
Also his fucking footsteps will now fall off with distance instead of being hellishly loud no matter where you were.

**Comment by Kromgar** [comment]
But why the hell would you have him charge past his indicator how is that intuitive?

Not to mention there are only 6 people who have actually killed bubblegum more than twice why make him harder?

**Comment by Kromgar** [comment]
This is like making the ash drake landing indicator show up 4 tiles east of where it's gonna smash down.

**Comment by Kromgar** [comment]
Uh so he always hits? He always hits on a charge does that what it does now?

**Comment by Kromgar** [comment]
Also did you delete all the comments?

**Comment by ChangelingRain** [comment]
Instead of only ever charging 7 tiles it'll charge however many it takes to get to where the target/indicator was.

**Pull request merged**
