### PR TITLE
Heretic runes are easier to click through and have a windup for clearing them

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Heretic runes no longer have every single transparent pixel set to 1 alpha, to make it easier to click on objects.

Clearing heretic runes with mansus grasp takes 0.4 seconds of standing still, to prevent you from accidentally clearing it in combat.

Added code for effect remover element to use a windup if set.

## Why It's Good For The Game

> Heretic runes no longer have every single transparent pixel set to 1 alpha, to make it easier to click on objects.

It's legitimately a massive annoyance managing stuff that's on heretic rune tiles because you can't just pick them up because of this strange decision. The runes are thick enough that they aren't hard to click on. I've fumbled around trying to grab the knife I transmuted way too many times to not make this PR.

> Clearing heretic runes with mansus grasp takes 0.4 seconds of standing still, to prevent you from accidentally clearing it in combat.

Similarly to the above, fighting above your rune is very dangerous because a missed click with your grasp clears the rune AND puts your grasp on cooldown, which is terrible, unintended, and will likely lead to your death. To counter this, it has a small, very small windup so that in combat you'll fail it while moving around. I tried setting it to 0.25, but I found it a tad too quick and prone to accidental rune clearing mid-angry-monkey-combat.

## Changelog

:cl:
qol: Heretic runes no longer have every single transparent pixel set to 1 alpha, to make it easier to click on objects.
qol: Clearing heretic runes with mansus grasp takes 0.4 seconds of standing still, to prevent you from accidentally clearing it in combat.
code: Added code for effect remover element to use a windup if set.
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
could help with #72899 if it removes the alpha pixels

**Comment by carlarctg** [comment]
Won't fix the rune being layered over items, but i'm unsure if thats a bug or whatever

**Comment by mikederkan** [comment]
> Won't fix the rune being layered over items, but i'm unsure if thats a bug or whatever

it's an unfortunate part of how ss13 handles 3x3 decals like this, syndie graffiti has the same issue

**Review by Wallemations — APPROVED** [review]

**Comment by Fikou** [comment]
the correct fix for this is https://github.com/tgstation/tgstation/pull/74776

**Comment by MrMelbert** [comment]
> it's an unfortunate part of how ss13 handles 3x3 decals like this, syndie graffiti has the same issue

It's not really, we can fix it, but understanding how is quite complex.

**Comment by carlarctg** [comment]
> the correct fix for this is #74776

No, that's a fix for runes showing above layers but the underlying issue of being unable to click on things below the rune at all persists, such as floor tiles.

**Pull request merged**
