### PR TITLE
GAGS most radio encryption keys

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Swaps all but the translation encryption keys into GAGS sprites
image

## Why It's Good For The Game
Lowers the amount of sprites

## Changelog

:cl: Wallem
imageadd: GAGSifies most of the radio encryption key sprites
/:cl:

### CODE REVIEW

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
Sprite in the screenshots looks rather faded, attempt to up the contrast a lil'

**Comment by Wallemations** [comment]
> Sprite in the screenshots looks rather faded, attempt to up the contrast a lil'

Yea I realized I forgot to change it to the one I made that had higher contrast
changing that now and putting a new screenshot up

**Comment by Wallemations** [comment]
I cannot tell why the linter test failed

**Comment by Wallemations** [comment]
IT'S BECAUSE I PUT AN EXTRA M?????
image

**Review by Imaginos16 — APPROVED** [review]
A bit unrelated to the PR but, if there were two guys on the moon and one of them killed the other with a rock would that be fucked up or what?

**Comment by Wallemations** [comment]
Realized having the translation key be the exact same as it used to be would make it look weird compared to everything else, so I cooked up a sprite for it
asdwedwdasdsdawdwd

**Pull request merged**
