### PR TITLE
Map bug fix/tweaks

### PR DESCRIPTION
**Pull request by Niknakflak**
Fixes a corner going diagonal that shouldn't have been
Updates description of the shuttle

### CODE REVIEW

**Comment by YakumoChen** [comment]
#19044 can you tweak this too? It should be an easy fix.

**Comment by Niknakflak** [comment]
Can you explain it in more detail?  I'm having a little trouble understand what the issue is

**Comment by YakumoChen** [comment]
Someone was standing one tile above the glass door in the AI core on Box, and the turrets couldn't hit them.

**Comment by Niknakflak** [comment]
that still doesn't tell me anything

**Comment by YakumoChen** [comment]
the stun bolts can't hit any of the spaces fore of the AI in it's AI Core chamber.

**Comment by Niknakflak** [comment]
V(._.)V

**Comment by Zilenan91** [comment]
That's intended Yakumo

**Pull request merged**
