### PR TITLE
Gives the mining lockers a seclite.

### PR DESCRIPTION
**Pull request by silicons**
Why not? Seclites are really useful and non roundstart miners will now get one. Roundstart miners getting two is probably not that big of an issue.

### CODE REVIEW

**Comment by JJRcop** [comment]
Keep in mind seclites have 9 force.

**Comment by KorPhaeron** [comment]
What is it about weapon force that triggers the worst bikeshedding known to this codebase?

**Comment by Supermichael777** [comment]
fire extinguishers have 15 force and are never more then a disarm stun away

dont be that fucking guy

**Comment by JJRcop** [comment]
I'm fine with this change, I just wanted it to be out there because, well, they do have 9 force, and it's a potential balance concern. (Personally I'm not concerned about it, but I wanted other people to know)

**Comment by XDTM** [comment]
Fire extinguishers have 10 force in any case, not 15

**Comment by Aloraydrel** [comment]
Power creep

**Comment by GunHog** [comment]
Hardly a "balance concern" when there is a 15 force pickaxe in the same locker. 10 force weapons (fire extinguishers, toolboxes) are also extremely common. Yet another example of Erro's Law in play.

**Comment by optimumtact** [comment]
Only if you add the ability to attach the seclite to the explorers knife.

**Comment by TechnoAlchemisto** [comment]
A 9 force seclite is not a problem

**Comment by TechnoAlchemisto** [comment]
But don't put it on the top of the locker most people won't need it.

**Comment by Cheridan** [comment]
>What is it about weapon force that triggers the worst bikeshedding known to this codebase?

The difference between a great weapon and a useless one is like 10 points, there's no other variables between items to differentiate them like swing speed or range?

**Comment by Thunder12345** [comment]
Range would be pretty awkward to deal with, but modifying click cool down by weapon would be nice

**Comment by Bawhoppen** [comment]
Powercreep

**Comment by kevinz000** [comment]
it's now down deeper in the pile, above the sandbags, shovel, pickaxe, and headset.

**Comment by xxalpha** [comment]
Remember when this was made to be a weapon for security?

**Comment by KorPhaeron** [comment]
does this actually upset you

**Comment by KorPhaeron** [comment]
I promise there are enough generic black flash lights in the ss13 universe to go around

**Comment by ChangelingRain** [comment]
seriously miners already have one, a KA(which is 10 force at range), pickaxes, and this thing is 9 force it's not a big deal

**Comment by xxalpha** [comment]
If it's not a big deal why aren't they given a standard flashlight?

**Comment by KorPhaeron** [comment]
The sec lite matches their colours/theme better. Has a better sprite as well.

**Comment by KorPhaeron** [comment]
Also, again, is the most common flashlight design in the world being something multiple people have access to an actual lore violation in your mind?

You can go buy one at walmart right now.

**Comment by optimumtact** [comment]
Why can't I attache the sec lite to the rails on my tactical knife Kor

**Pull request merged**
