### PR TITLE
Discstation update [Merge Ready]

### PR DESCRIPTION
**Pull request by Strathcona**
Lots of fixes this time around. Renamed the map to avoid future hassle. Apologies for the line change spam.

[Latest Version of the map](https://www.dropbox.com/s/bpgq3bvycw3taeg/DiscStation20.png?dl=0)
- Gave some extra room to the Chapel
- Added Hardsuit to R&D
- Added a few new AI holopads
- Added a Canister port to Prisoner Transfer
- Added Lights to some areas that needed them
- Added a bunch more signs
- Added a SMES to telecoms
- Fixed observer spawn
- Fixed Shuttle
- Fixed misplaced arrivals area (unpowered airlocks)
- Fixed gaps in Fore Port maint (random space areas)
- Fixed Bridge area
- Fixed Misplaced Escape Shuttle areas
- Fixed Mixing Room Vents
- Fixed Pod Areas
- Fixed visible pipes in Janitors Closet
- Fixed Med Research Chem Shutters
- Fixed Mechbay Shutters
- Fixed Research Shutters
- Fixed Eng APC situation
- Fixes Singulo Engine wires
- Fixes AI Turret control
- Electrified a few grilles that should be electrified
- Found a few areas where maint was set to space
- Removed an APC from Bar Backroom (inconsistent)
- Removed Tinted windows
- Remodeled Gravity Generator
- Remodeled Medbay (lowered lobby)

### CODE REVIEW

**Comment by RemieRichards** [comment]
PR is a remake of a PR at 23 hours, best to just label it as ready.

**Comment by Strathcona** [comment]
Travis fails since I've renamed the map. I dunno what to do about that though.

**Comment by WJohn** [comment]
How many attempts is this now? 3?

Sucks to be you man, good luck!

**Comment by Strathcona** [comment]
Only two! It would be lovely if we stop changing the path to items though :P so if I am reading this right, travis ends up spitting out: _maps/map_files/DiscStation/z2.dmm:427:error: cannot find file which is uranium doors on the wizard shuttle. Goddamn. I think I got it though.

**Comment by Supermichael777** [comment]
please don't put actual uranium doors in the wizard shuttle or wizards are going to have a bad day. those were fake uranium doors for a reason

**Comment by Strathcona** [comment]
Thanks for pointing that out, you're totally right. I'll get on that.

**Comment by Strathcona** [comment]
Can I get this Merged? Since it's a remake of an Old PR, it's been around for nearly 2 days and without it, DiscStation can't be played.

**Pull request merged**
