### PR TITLE
Removes metal gear solid boxes

### PR DESCRIPTION
**Pull request by Aranclanos**
like fucking seriously stop trying to add this shit for each new stupid game, movie or funny meimei it comes out

### CODE REVIEW

**Comment by Iamgoofball** [comment]
can you not

:-1:

**Comment by WJohn** [comment]
:-1: x :100: 
why

**Comment by Zilenan91** [comment]
:-1: If it has any actual function aside from just being a reference
:+1: If it does nothing.

**Comment by Iamgoofball** [comment]
@Zilenan91 it has usage, you can move around in it, and it also stores objects, plus it tanks some damage

so I can move around in it, use it to carry inventory items, and then also survive an extra bullet shot with it

it's suprisingly useful

**Comment by SconesC** [comment]
:-1: go away

**Comment by Anonus** [comment]
:-1: 
Aran no.

**Comment by Lijah99** [comment]
If one meme can't work, then others shouldn't :+1: :+1: :+1:

**Comment by as334** [comment]
:-1: It's a fun feature that actually does unique stuff.

**Comment by phil235** [comment]
I'm in favor of removing the exclamation point gimmick, but not complete removal. :-1:

**Comment by Incoming5643** [comment]
I've wanted a box in this game since the day I found it, I just literally had no overwhelming impetus to code it. I thought the recent release would help get it accepted, not get people mad because OH NO RECENT REFERENCES.

If you want to keep meems down just don't merge #12023, that's the reason I kept it separate from #12015.

Remove the ! if you really must, but I was proud of figuring out the new animation shit is all.

Such a lust for revenge

**Comment by Nanotransistor** [comment]
Should just be admin spawned only.

**Comment by Incoming5643** [comment]
The literal furthest I would go is to make them constructible only with a single guaranteed spawn in cargo.

**Comment by Incoming5643** [comment]
(pulls dedicated to boxes: 5)

**Comment by GunHog** [comment]
:-1:

**Comment by Supermichael777** [comment]
box ops was fun :-1:

**Comment by KorPhaeron** [comment]
I don't really understand the "no reference" policy considering we still have literal xenomorphs.

Box is also fun.

**Comment by Incoming5643** [comment]
#12054 opened to stop this/end the madness

**Comment by lollerderby** [comment]
Yeah this awful remove it.

**Comment by PKPenguin321** [comment]
:-1: don't remove it it's fun

**Comment by Shadowlight213** [comment]
:-1:to removing boxes
:+1: to removing Aran

**Comment by Aloraydrel** [comment]
Le no fun allowed face

**Comment by Fox-McCloud** [comment]
What in the world? No :-1:

**Comment by Dorsisdwarf** [comment]
:-1: :100: 

Remove ayyran

**Comment by kyrahabattoir** [comment]
Personally i enjoy references when the creation process is more in the like of "Hmm this would be a nice addition... Hey wait a minute, remember that movie, this it totally it, lets add a little tongue in cheek nod to it"

Unlike "Hey guys lets add a meme!"

**Comment by Giacom** [comment]
\> for each new stupid game
\> MGS boxes
\> new
\> stupid

I thought the "no reference" was for player references. Also yeah this game was built on references.

**Comment by KorPhaeron** [comment]
@kyrahabattoir 

All the subtle stuff like item descriptions gets purged more readily, ironically

**Comment by Kromgar** [comment]
:-1:

**Comment by Spacemanspark** [comment]
:-1:

**Comment by TrustyGun** [comment]
no

**Comment by ike709** [comment]
:-1: doesn't remove aran

**Comment by Aranclanos** [comment]
arrow to the knee xd

**Pull request closed without merging**
