### PR TITLE
Some more tweaks to Geis

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
balance: Geis bindings no longer decay faster if not pulled by a Servant, but last for 20 seconds, from 25.
tweak: Geis bindings will decay slower when on a Sigil of Submission, and, if being pulled by a Servant when crossing a Sigil of Submission, will helpfully remove the pull.
tweak: Removing Geis bindings is no longer instant and can be done by any Servant with a slab, not just the initiator.
wip: Geis no longer prevents you from taking actions, but you remain unable to recite scripture while the target is bound. In addition, dealing damage to a bound target will cause the bindings to decay much more rapidly.
rscadd: You can now remove sigils by hitting them with a clockwork slab for a small refund.
/:cl:

Feedback: Too weak, too hard to use effectively, sigils need to be removable somehow, Geis shouldn't be as loud.

### CODE REVIEW

**Comment by drfino** [comment]
i thought you could always remove runes with a tome?

**Comment by adamkad1** [comment]
bloodcult yes, clockcult no

**Comment by drfino** [comment]
What's the difference?

**Comment by adamkad1** [comment]
entirely different gamemodes?

**Comment by drfino** [comment]
Oh my mistake, I couldn't tell

**Comment by ChangelingRain** [comment]
Honestly I don't want to leave this in the state it's in even with Xhuis's rework up, since it's such a major part of the mode.

**Comment by AnturK** [comment]
So should i be merging this with all these reworks around ? @ChangelingRain @Xhuis @KorPhaeron

**Comment by Xhuis** [comment]
I don't think so. Let Kor decide.

**Comment by KorPhaeron** [comment]
You two know clock cult far better than I do

**Comment by Xhuis** [comment]
My personal opinion is that it would interfere with the rework (given that Geis doesn't even exist in the rework) but I will say that the current version is terrible. It's not really an easy decision.

**Comment by KorPhaeron** [comment]
If it doesnt exist in the rework wouldnt it just be the same amount of work as it is now deleting it?

**Comment by Xhuis** [comment]
That's about right

**Comment by KorPhaeron** [comment]
May as well improve the version thats on server for however long it takes the rework to get done then

**Comment by Xhuis** [comment]
Sounds reasonable to me, yeah.

**Pull request merged**
