### PR TITLE
Fixes goat and cow milking, they were just simply not working.

### PR DESCRIPTION
**Pull request by Aranclanos**

### CODE REVIEW

**Comment by MrPerson** [comment]
Any feature that can literally go months on end being broken without anyone reporting it or caring is obviously a shitty feature that should just be removed

**Comment by Aranclanos** [comment]
nobody reported your UGLY FACE FAGGOT

**Comment by MrPerson** [comment]
:O

**Comment by Iamgoofball** [comment]
maybe this is a sign that more recipes should use milk

**Comment by phil235** [comment]
Milking Pete on Sybil worked fine for me just a couple days ago...

**Comment by Aranclanos** [comment]
conflicts solved

**Comment by Razharas** [comment]
>Someone actually thinks you were getting petes milk from udder

Ahahaha

**Pull request merged**
