### PR TITLE
Makes the posibrain play a ping sound on success.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 

:cl: Dax Dupont
add: Posibrains have gotten a small firmware update, they will now play a sound on successful activation.
/:cl:

[why]: Makes it more noticeable when a posibrain jumps to life when you're busy fiddling with the research console.

### CODE REVIEW

**Comment by DEATHRATTLERS** [comment]
fuck. first the fucking beeping crematorium now this

**Comment by DaxDupont** [comment]
They can't constantly reenter the posibrain without suiciding and manual reactivation though.

**Comment by Buggy123** [comment]
The beeping crematorium was a good change.

**Comment by DaxDupont** [comment]
Open it up to any ghost. 
You generally need to battle for a spot though.

**Pull request merged**
