### PR TITLE
Health analyzer output reordering

### PR DESCRIPTION
**Pull request by kingofkosmos**
Reordered things in the Health Analyzer code. Basically moved things into a more logical order, as in all damage related stuff in one section. Numbers are now rounded and all user.show_messages are user << messages. Also fixed a small typo with the gas scanner, the % wasn't inside spans.

Pics:

**Old** one analyzing a **healthy** patient:
ennen
**Old** one analyzing an **injured** patient:
ennensatutettu

---

**New** one analyzing a **healthy** patient:
uus
**New** one analyzing an **injured** patient:
nimeton

### CODE REVIEW

**Comment by pudl** [comment]
ok

**Comment by Cheridan** [comment]
The space between the numbers and the % symbol for the blood level looks funny, it could probably just be 100% instead of 100 %

Personally I would list the damage type in the order of 
Brute - Burn - Toxin - Suffocation

Which is generally more in line with how common/important that damage type is

**Comment by duncathan** [comment]
> The space between the numbers and the % symbol for the blood level looks funny, it could probably just be 100% instead of 100 %
The % is an SI unit, and SI units must have spaces between the value and unit. There are exceptions, but none are made for %. It's correct.

**Comment by Cheridan** [comment]
fair enough i suppose

**Comment by Miauw62** [comment]
Man I would say that there shouldn't be a space anyway but I'm the dude
that asked for °K to be changed to K because it's more correct so
Op 29-mei-2015 06:14 schreef "Cheridan" <notifications@github.com>:

**Comment by pudl** [comment]
the matter of a space being before a percent sign is often heavily debated, there is no actual consensus. there's two clear sides of the argument: people who grew up writing it simply as "100%", and people who also grew up writing it "100%" and decided that they were different little snowflakes and started using "100 %" because it's edgy.
remove the fucking space

**Comment by duncathan** [comment]
In anything scientific, including medicine, the space is required. In colloquial usage no space is fine, but for this the space is correct.

**Comment by pudl** [comment]
riddle me this nerd: why is alienating/making people think "THAT'S WEIRD" worth it when it makes no fucking difference without the space

**Comment by duncathan** [comment]
What I'm confused about is why the space is making you so upset

**Comment by pudl** [comment]
because adding the space is literally a "i'm better than you losers who dont use the space xD" move based on arbitrary and pretentious rules that no one folows

**Comment by cookingboy3** [comment]
In the great words of Jesus Christ:

"Who gives a fuck"

**Comment by kingofkosmos** [comment]
*In line with common English practice, style guides—such as The Chicago Manual of Style—generally state that the number and percent sign are written without any space in between. However, the International System of Units and the ISO 31-0 standard require a space.*

http://en.wikipedia.org/wiki/Percentage#Word_and_symbol

Pudl is your only reason to be here to cause commotion? These things can be discussed without calling people names. Plus check yourself before you wreck yourself.

**Comment by freerealestate** [comment]
:+1: Really good, we need less text spam in the game

**Pull request merged**
