### PR TITLE
Dropping door bolts has a two second delay.

### PR DESCRIPTION
**Pull request by Cruix**
Related to #17406

:cl:
tweak: Dropping door bolts now takes two seconds, except by cutting the bolt wire, which is still instant. While the door bolts are about to drop, the door bolt lights will flash if they are on.
/:cl:

The delay can be changed for individual doors, but defaults to two seconds. You can cancel the bolts dropping by pulsing the bolt wire or control-clicking as a silicon.

The timer subsystem is excellent. I also added myself to admins.txt.

### CODE REVIEW

**Comment by coiax** [comment]
So who does this nerf exactly? People with remote signallers, people using multitools, and silicons using the door dialogue box instead of ctrl-clicking? It's an odd collection of people.

**Comment by Nyvrem** [comment]
This nerves AI so
https://github.com/tgstation/-tg-station/pull/17406
can happen.

**Comment by Supermichael777** [comment]
remote signaler and multitudes bypass this.

**Comment by Cruix** [comment]
Pulsing the wire with a signaler or multitude had the delay when I tested it. Is it not supposed to, or did you find a bug in my code?

**Comment by Bawhoppen** [comment]
Unnecessary :-1:

**Comment by KorPhaeron** [comment]
Should have a warning message or noise, or else the delay isnt very useful

**Comment by Cruix** [comment]
The bolt lights flash when the bolts are about to go down. What noise should there be, or what should the message be? What should the range on it be?

**Comment by xxalpha** [comment]
I advise careful reviewing of this code.

**Comment by optimumtact** [comment]
It's probably a good idea

**Comment by Robustin** [comment]
This was part of a compromise to removing the AI tracker delay, its still a net buff to the AI without bringing us straight back to the Golden Age of HARMYELLER DOORBOLTER 5000 destroying all the fun on station.

**Comment by optimumtact** [comment]
this needs an ingame poll @Shadowlight213 @KorPhaeron @MrStonedOne @Jordie0608

**Comment by PKPenguin321** [comment]
Should have an audio warning

**Comment by Shadowlight213** [comment]
Poll made

**Comment by optimumtact** [comment]
http://www.ss13.eu/tgdb/tg/ingamepolls.php#p135

Here is the poll in progress by the way. It will end in 3-4 days

**Comment by optimumtact** [comment]
yeah I can see the outcome of this poll already

Sorry, better luck next time

**Pull request closed without merging**
