### PR TITLE
Add laser pointers to techweb

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
This adds laser pointers to the `Advanced Electromagnetic Theory` node.

## Why It's Good For The Game
More ways for people to create and use items.

## Changelog
:cl:
balance: Add laser pointers to techweb
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
This is a balance change since your practilly printing out a ranged flash which also can emp cameras

**Comment by Autisem** [comment]
yeah laser pointers are kinda powerfull, I feel they should be as strong as they are to begin with but adding them to be printed would be hell for malf ai's and rogue borgs

**Comment by timothymtorres** [comment]
I was not aware it had combat potential.  Just thought it was something silly to use on cats and as a pointer.  However even with combat mechanics, flashes are still printable from robotics at roundstart.  Laser pointers spawn on several crew members and are scattered around research, so it's not exactly a rare or hard to get item.

**Comment by Timberpoes** [comment]
If laser pointers become something we can mass print from lathes, they will need adjusting. They are very powerful but not trivial to get ahold of.

I don't want laser pointers to be adjusted and quite like the power band they sit in.

Also having everything printable hinders item scarcity. I prefer item scarcity to resource scarcity.

It's fun to have lots of resources to enable basic job content, and better for the shift's narrative having to hunt for the stuff to make advanced job content. 

When you get a rare item it feels cool, and you know other people may want your rare item which adds a bit extra tension to the shift.

**Comment by timothymtorres** [comment]
I code dived and I forgot to mention that miners can buy laser pointers for 300 points.  So mass buying these isn't really that hard to achieve.  Adding stuff like this to techwebs is more about versality.  If cargo isn't available, then you have another route to achieve it - thus research and mining.

**Pull request closed without merging**
