### PR TITLE
Make puddles not destruct into metal

### PR DESCRIPTION
**Pull request by pubby**
shouldn't be turning into metal stacks after whacking them

### CODE REVIEW

**Comment by CPTANT** [comment]
LYNCH THE PUDDLE

**Comment by JJRcop** [comment]
Instead of making them indestructible, override their deconstruct proc, and remove the part that drops the stack of metal
https://github.com/tgstation/tgstation/blob/030f08c8c69d315aa04930d1539db89025370ca1/code/game/objects/structures/watercloset.dm#L523-L525

**Comment by pubby** [comment]
Dunno if being able to vaporize puddles by whacking them is an improvement over invincible puddles.

**Comment by Cheridan** [comment]
splash splash

**Comment by AnturK** [comment]
Make them deconstructable through buckets.

**Comment by KorPhaeron** [comment]
Does this mean they're bomb proof?

**Comment by pubby** [comment]
@KorPhaeron Hm, it does.

I'll change it to JRRcop's suggestion in a few hours unless someone stops me.

**Comment by Armhulen** [comment]
anturk had the right idea

**Pull request merged**
