### PR TITLE
New burger sprites

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Changes most burger sprites to entirely new custom ones by Boltycat

burgers

Yummy yum!

## Why It's Good For The Game
The original burgers looked like plastic, these look like they were lovingly crafted by a professional chef.

Oh right, the obligatory meme link.
https://youtu.be/BiH8fkJOonQ

## Changelog

:cl: Boltycat
imageadd: Changes most burger sprites for delicious new ones!
/:cl:

### CODE REVIEW

**Comment by MetalClone** [comment]
The pretty patties look cool but the other burgers look like there is maple syrup on top of the buns

**Comment by red-creature** [comment]
why are we respriting this? i'm no spriting professional but these look more like gross plastic than the old ones. also the beret on that burger looks super weird

**Comment by carshalash** [comment]
The top of those buns are burnt... I like the other aspects of the sprites but, that burn is really distracting.

**Comment by VladinXXV** [comment]
I would redo the buns but I am a huge fan of the ideas on things like the wizard burger, ghost burger, cat burger, and clown burger. They have so much more life to them. A rubber chicken in the clown burger....

**Comment by ArcaneDefence** [comment]
There's hanging pixels on the top left of the roburger

**Comment by necromanceranne** [comment]
> There's hanging pixels on the top left of the roburger

that's maybe a icondiff bot problem, not actually a sprite problem. You can't see that pixel in the picture provided.

**Comment by MrDoomBringer** [comment]
image
I'm really sorry but the new base burger sprites do not meet our quality standards. They're too saturated, lack definition (what is with the top of the buns??), lack proper shading, and are in general less pleasing to look at. 

However, I really like the creativity behind the cat/clown/mime/ghost/wizard burger, and strongly suggest we keep those "accessories" and merge them with our existing burger sprites, rather than redoing everything from the ground up.

**Comment by Wallemations** [comment]
IMG_0300
Was told to pack it up.

**Comment by Farquaar** [comment]
I like the wizard burger a lot.

**Pull request closed without merging**
