### PR TITLE
Officer's Sabre > Officer's Rapier

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
spellcheck: Fluff: The officer's sabre is now called the officer's rapier, because it's a rapier.
/:cl:

It's a rapier.

### CODE REVIEW

**Comment by LanCartwright** [comment]
Nine commits.

You're committing to the king of all SS13 codebases. 

Straighten your back because the last thing you wanna do is look like a peasant.

**Comment by PopNotes** [comment]
No I'm not, Goon isn't open source

**Comment by ExcessiveUseOfCobblestone** [comment]
delete that right now

**Comment by PopNotes** [comment]
### :^)

**Comment by Supermichael777** [comment]
\>:^(

**Comment by optimumtact** [comment]
off to goon with you then

**Comment by Supermichael777** [comment]
based

**Comment by PopNotes** [comment]
open this

**Comment by Bawhoppen** [comment]
It can't be a rapier because you're slashing with it (it's made specifically for dismemberment)

**Comment by Bawhoppen** [comment]
Also you don't have to change the name of it in the code, just the ingame name

**Comment by PopNotes** [comment]
the sprite is a rapier

**Comment by Bawhoppen** [comment]
I know, but a sprite issue is a smaller deal than a complete logic shattering name

**Comment by PopNotes** [comment]
I feel like the name matching the sprite is more important than the name matching the function.

Alternatively, think of it this way. "The sword's tip is so carefully crafted that a well-placed stab with enough force behind it can instantly sever a limb."

**Comment by banthebantz** [comment]
You do realize rapiers can slash as well right?

**Comment by Jordie0608** [comment]
For reference: the PR that changed name to sabre https://github.com/tgstation/tgstation/pull/19779

**Comment by PopNotes** [comment]
notice how that was over 10,000 PRs and more than a year ago

times change

**Comment by DoctoreMad** [comment]
It doesn't act like a rapier at all though. A sprite change would be the best, ~really, unless you want to remove it for armor penetration~ oh wait it already has that.

**Comment by optimumtact** [comment]
sorry but this is the design leads decision, and we cannot accept your pr.

@tgstation/commit-access I will close this tomorrow unless any new information comes to light

**Comment by KorPhaeron** [comment]
I just made the name change to troll yackemflam I dont care what the name is so long as it can dismember

**Comment by optimumtact** [comment]
I'm the design lead not you

**Comment by KorPhaeron** [comment]
Oh okay

**Comment by ExcessiveUseOfCobblestone** [comment]
can I be the design vice-lead :3

**Comment by optimumtact** [comment]
you have a merge conflict in the dmi

**Comment by AnturK** [comment]
I'll save you the trouble.

**Comment by Cyberboss** [comment]
Still looks like a rapier though...

**Comment by praisenarsie** [comment]
you're a rapier

**Pull request closed without merging**
