### PR TITLE
Adds in a new fertilizer, the super robust harvest. Made in the biomass generator

### PR DESCRIPTION
**Pull request by ma44**
CL
add: New super robust harvest fertilizer, made in the biomass generator for 1000 biomass a bottle, this fertilizer increases yield by 130% (or 2.30) and prevents mutatioons
/CL

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Wow, this is... really bad.
1000 biomass a bottle for something you can do with normal robust harvest(which also 'prevents mutations'), what the fuck.

**Comment by optimumtact** [comment]
You can wait for feedback

**Comment by optimumtact** [comment]
also it's cl, not CL

**Comment by xxalpha** [comment]
also needs ::

:+1: for even more robust :lemon:

**Comment by ma44** [comment]
Reasons

**Pull request closed without merging**
