### PR TITLE
Fixes unpowered air injectors on pubby

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes complaint raised on the forum.

🆑 ShizCalev
fix: PubbyStation - Unpowered air injectors in various locations have been fixed.
/🆑

### CODE REVIEW

**Comment by epochayur** [comment]
alternate solution: remove pubby

**Comment by Mark9013100** [comment]
just because it's not box doesn't mean it's shit

**Comment by epochayur** [comment]
of course not, it's just shit by its own merit

**Comment by Jordie0608** [comment]
Conflict

**Pull request merged**
