### PR TITLE
Makes revenants spawn on dead bodies & bodycontainers

### PR DESCRIPTION
**Pull request by ShizCalev**
In the interest of streamlining some mapping and making things a little more dynamic, revenant spawnpoints will now be automatically generated with morgue trays, crematoriums, ect. 

They were already placed map side, this just makes it so that newly constructed ones will generate new spawnpoints. Likewise, when the tray is deconstructed/destroy/ect, the landmark will also be removed along with it.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
what happens if someone with a fireaxe smashes all the body containers

**Comment by ShizCalev** [comment]
There are still revenant spawn landmarks placed on the maps, failing that it falls back to carpspawn landmarks placed on the map.

**Comment by coiax** [comment]
Why not just make revenants spawn on top of a dead mob instead. Or track during the round where things have died, and pick from one of those turfs.

**Comment by ShizCalev** [comment]
Fully removed the landmark, now revenants will attempt to spawn off a dead mob on the station as well as morgue trays if there are less than 10 dead mobs to pick from on station.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
