### PR TITLE
resprites radioactive nebula shielding

### PR DESCRIPTION
**Pull request by CoiledLamb**
## About The Pull Request
title. the radioactive nebula shielding has received a glow up - or maybe you're just irradiated! before and after here:
image
comes with a new broken state, for when it's sustained too much damage
image
also, here's the animation for it, took way too long to put this together
nebulashield
## Why It's Good For The Game
when the radioactive nebula event happens, the engineers have to put one of these big machines together, as it becomes a big part of their job to maintain it. certainly it could stand to look as cool and important as it is!
## Changelog
:cl: CoiledLamb, Time-Green
image: resprites the radioactive nebula shielding
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
common lamb W

**Comment by Jezzared** [comment]
The fact that the main tower/pillar thingy doesn't become damaged when the rest of the machine does throws me off a bit.

**Comment by CoiledLamb** [comment]
> The fact that the main tower/pillar thingy doesn't become damaged when the rest of the machine does throws me off a bit.

good catch. i think i intended something for that, but never got around to adding it. i'll play around with it and update the PR

**Comment by HoodMilk** [comment]
Nuclear Throne

**Pull request merged**
