### PR TITLE
Makes the dehydrated carp less ambiguous and decreases its TC cost

### PR DESCRIPTION
**Pull request by ghost**
Just a few extra words to make sure you know something you should do before you do buy it.

Oh and a slight cleaning up of old comments I did so I feel less red-cheeked.

**Edit:** Kerp now costs 2 TCs instead of 3. So that's 10 kerp maximum when spammed instead of 6 which will give some more options for any traitor.

**Edit2:** Down to 1 TC.

:cl:
tweak: Hopefully made the dehydrated carp's uplink description 100% clear.
tweak: Made the dehydrated carp cost 1 TC (instead of 3) to help with your traitor gear combos.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Could you make it 1 point as well? Carp are pretty weak

**Comment by CosmicScientist** [comment]
Erm, are they? I've greentexted (steal nuclear disk) and killed the majority of sec + the HoP + the Captain one round by just buying carp and releasing them in the HoP's line and following them to the bridge.

I might agree with 2 points for a max of 10 carp but allowing 20 carp sounds a bit... nutty... even if they won't all respond to a single spray of a fire extinguisher.

**Comment by Zilenan91** [comment]
Yeah they should be 1 TC tbh. If 2, they'll be completely silly and amazing if Nuke Ops spam them using all their TCs in major hallways, at 1 TC actually viable because of there being no borg.

**Comment by Aloraydrel** [comment]
Like two-three laser shots to kill a carp

Should be one tc tbh

**Comment by duncathan** [comment]
I wanna see 120 carps in fluke ops now

**Comment by CosmicScientist** [comment]
@duncathan Nuclear Carperatives if an admin spawns them carp spacesuits as well.

**Comment by MrStonedOne** [comment]
Please make a changelog,

You can add it to the PR's body rather then as a file now, see here: https://tgstation13.org/phpBB/viewtopic.php?f=5&t=5157

**Comment by CosmicScientist** [comment]
@MrStonedOne sorry I didn't think to include one sooner when I actually started meddling with the TCs.

And thank you very much for making that changelog short cut.

**Comment by Lumipharon** [comment]
I've seen more then one round where ops won by spamming carp, and that was at 3tc each.
150+ carp is gonna be somewhat amusing.

**Pull request merged**
