### PR TITLE
Fix the laptop in Meta's cafe

### LINKED ISSUE #58592: coffee bar has an empty laptop frame instead of a real one
## Reproduction:
the coffee bars have a useless empty laptop frame (/obj/item/modular_computer/laptop) instead of the civilian laptop like in engineering lobby (/obj/item/modular_computer/laptop/preset/civilian) which was presumably the intended result
image
happens on kilostation and metastation, presumably on the other maps where this area was copy pasted onto
image
for the longest time i thought it was intentional but i realized that 1. what the fuck is the point of leaving an empty laptop frame as a bizarre taunt to anyone that dares explore the content in this area and 2. modular computers aren't really useful enough to the average assistant that loots this place to be worth locking behind asking engineers to fill it with parts and 3. the typepath implies that they just typed in laptop and didn't bother to check and see if it turned on

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

The laptop in the cafe on META was not a valid laptop, it was a shell only.
This makes the laptop a functional laptop.

Fixes #58592

## Why It's Good For The Game

The laptop works as expected instead of being a shell of it's self.

## Changelog
:cl:
fix: Meta's café laptop is no longer a shell of it's self
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
on a similar note, the café always has a single 1 credit bill which is weird, was a bigger stack intended?

**Comment by nightred** [comment]
> what about the other maps?
> on a similar note, the café always has just a single 1 credit bill which is weird, was a bigger stack intended?

Where is the cafe on any other map? I could not find it.

**Comment by MrMelbert** [comment]
i thought it was intentional social commentary on the inability for the less fortunate to gain access to modern technology yet they still visit expensive coffee shops

**Comment by nightred** [comment]
> i thought it was intentional social commentary on the inability for the less fortunate to gain access to modern technology yet they still visit expensive coffee shops

Oh I am stealing that for the next time.

**Comment by maxymax13** [comment]
on kilo it's in the hallways under science, it appears to not be on box or delta because box and delta players don't deserve nice things (aka it's impossible to add anything to them)

**Comment by nightred** [comment]
> on kilo it's in the hallways under science, it appears to not be on box or delta because box and delta players don't deserve nice things (aka it's impossible to add anything to them)

I see the dinner, but no cafe and no laptop.
I have filtered out all items taht are not the laptop and still cannot locate it.
image

**Comment by maxymax13** [comment]
guess i was hallucinating

**Comment by nightred** [comment]
Also the single credit was intended on reflection. it was change for the last item/a tip.

**Pull request merged**
