### PR TITLE
Fixes superconduction runtimes

### PR DESCRIPTION
**Pull request by duncathan**
this broke superconduction, but i don't think anyone noticed

### CODE REVIEW

**Comment by coiax** [comment]
What is superconduction

**Comment by duncathan** [comment]
yeah pretty much

**Comment by coiax** [comment]
b-but I wans't meming

**Comment by xxalpha** [comment]
that's exactly it

**Comment by RemieRichards** [comment]
p.high priority, MSO is a little busy but he said he'd update soon.

**Pull request merged**
