### PR TITLE
makes ripley ,odysseus and honk use stock parts on construction 

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl: 
balance: Ripley, Firefighter, Odysseus and H.O.N.K. mechs now also use scanning modules and capacitors on construction. This means that they also gain reduced power consumption and EMP protection from higher-tier stock parts.
/:cl:
someone forgot to add these when they made mechs use different tiers of stock parts

### CODE REVIEW

**Comment by datorangebottle** [comment]
Does this significantly nerf the early power and  availability of RIPLEY mechs? I'd be okay with that. Hell, if robotics loses science access, they then have to badger R&D for the parts.

**Comment by MimicFaux** [comment]
Don't forget to update wiki construction guides

**Review by Cyberboss — DISMISSED** [review]
Jesus fuck what is mech code?

**Comment by zxaber** [comment]
Ripleys and odyssus have never needed stock parts. Is this a "fix" or really a nerf? At least set your changelog correct.

**Comment by subject217** [comment]
How is this a fix? What at all ever suggested that this was unintended?

**Comment by zxaber** [comment]
I suppose. Extra work, for potentially better stats.

I stand by my point that it's _not_ a fix and should be labeled differently, though.

**Comment by subject217** [comment]
It's a "buff" and a nerf. Ripleys and Firefighters are bad at combat regardless. Requiring stock parts just adds another thing that makes them harder to obtain. And these mechs are already pretty much only built for the fun of it.

**Comment by necromanceranne** [comment]
I use mechs a lot. And the firefighter, once fully upgraded with goliath plates, is the beefest tank of all them except for defense mode Durand, and that makes you stand still so it's hardly a positive ability unless it is specific edge cases. The only significant weakest it had was EMP's. Adding stock part scaling removes that entirely.

This is significant because traitor robos can put a gun on firefighters. Most of the shit that would probably fuck up other mechs, like elances, really doesn't work all that well against the pilots of firefighters because of the added bomb protections the firefighter has. So you have a mech that is both significantly tankier than a combat mech, is heavily resistant to emp's, can carry a diamond drill and other useful utility equipment (clamp, rcd, etc.), have room for both the armor modules and if they're a traitor, they can add a gun like the scattershot or SRM-8. The latter being perfectly functional as a kill method on its own because the diamond drill can gib people very quickly.

This is an absolutely disgusting buff to the best mech robos have, and it is entirely undeserved.

Oddy still broken so who gives a fuck about the Oddy.

**Comment by Tlaltecuhtli** [comment]
firefighter being tankier than a combat mech seems an issue of itself

**Comment by Tlaltecuhtli** [comment]
the mech cutter thing was reverted i think so it still has a defense gun in lavaland

**Comment by necromanceranne** [comment]
No it wasn't. Pretty sure it's still quite low. It takes a two minutes or so to kill a goliath. You'd be better off fighting shit on foot with a pka.

**Comment by zxaber** [comment]
I tried to revert it, but it got shot down.

**Comment by ExcessiveUseOfCobblestone** [comment]
no one wants to review mech code lol

**Comment by ExcessiveUseOfCobblestone** [comment]
also add the KA to the miner lol

**Review by 81Denton — APPROVED** [review]
Code looks good (oxymoron since it's mech code), I'm going to merge it and we can always adjust EMP protection later if it becomes an issue

**Comment by ExcessiveUseOfCobblestone** [comment]
the madman

**Pull request merged**
