### PR TITLE
Fixes high luminosity eyes

### PR DESCRIPTION
**Pull request by ghost**
:cl: That Really Good Soda Flavor
fix: High luminosity eyes will have material science instead of an error research type
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Fluff RnD powercreep object has issue straight out of the gates. 🎺  Whats new.

**Comment by GunHog** [comment]
@kevinz000 
### T E S T I N G

**Comment by octareenroon91** [comment]
>blames the PR for misdirected scrutiny

**Comment by kevinz000** [comment]
@FantasticFwoosh same can be said for you.
@GunHog :'(

**Comment by FantasticFwoosh** [comment]
Like what? I can take the guidance and advice in the thread, and don't have to rely or expect people to open issue reports to fix stuff later.

**Pull request merged**
