### PR TITLE
Allows you to wear buckets as hats

### PR DESCRIPTION
**Pull request by ghost**
They block your hair and have 10 brute resistance. Equipping one while it has reagents will spill the reagents onto you.

### CODE REVIEW

**Comment by AnonymousNow** [comment]
Neat.

**Comment by Boredone** [comment]
Not a big deal, but 15 melee protection might be better, same as hardhats.

**Comment by KorPhaeron** [comment]
>merge conflict

**Comment by Xhuis** [comment]
It's the fucking .int cancer shit, not me

**Comment by Xhuis** [comment]
I buffed the protection to 10%. It's less effective than hard hats for balance, because it's readily available from pretty much everywhere and can be produced en masse by an autolathe.

**Comment by KorPhaeron** [comment]
Make it as strong as sec helmets I want buckets to be the new meta

**Comment by optimumtact** [comment]
dude update your master more often

**Comment by WJohn** [comment]
Frankly hard hats and buckets should offer *some* kind of protection that isn't totally worthless compared to sec helmets. 10-15% for one limb is so tiny it might as well not even be there.

**Comment by Lumipharon** [comment]
It's a bucket. On your head.

Pretty sure this would do pretty little, even ignoring the fact that your face is still unprotected.

**Comment by Saegrimr** [comment]
Make it limit view range like welding mask overlay unless you use wirecutters to cut eyeholes.

I want to dunk a bucket on someone's head and run away when they can't see me.

**Comment by Jalleo** [comment]
New meta chemists putting buckets of burning chems onto others heads

**Comment by Steelpoint** [comment]
Helmets, even hardhats, are designed and created to block and protect your head from blunt attacks or falling objects. Or even from bullets and shrapnel in the Helmets case.

A bucket is designed to hold liquid, not for protection and definitely not as headware.

Around 10 brute defence seems fine for the bucket. It still will deflect a bit of damage but it shows a clear difference between a make shift helmet and a actual helmet.

**Comment by Xhuis** [comment]
\>people are debating the right amount of brute protection for a fucking _bucket_

**Comment by RemieRichards** [comment]
@Xhuis 
Erro's law:
Amount of discussion is inversely proportional to the importance of the change

**Comment by Jalleo** [comment]
@remierichards or in this case bucket-shedding instead of bike-shedding

**Comment by RemieRichards** [comment]
Haha, that's a good one

**Comment by daman997** [comment]
game changing :+1:

**Comment by Aranclanos** [comment]
buckethelmet

Remove the BLOCKHAIR, outside of that the sprite looks ugly, but WJ will take care of that.

**Comment by Razharas** [comment]
Yeah we need better sprites

**Comment by AnonymousNow** [comment]
Fuckin' BLOCKHAIR, ruining hoods with its lack of facial hair.

**Pull request merged**
