### PR TITLE
Makes sniper rifle bullets travel significantly faster

### PR DESCRIPTION
**Pull request by silicons**
No, this doesn't make them hitscan.
:cl:
rscadd: Sniper rifles now accelerate their bullets to extreme velocities instead of the average slow bullet.
:cl:
Tested. Works as intended.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
this will likely break something? but who really knows at this point testmerge ASAP

**Comment by kevinz000** [comment]
Last time I tested this locally while trying to make the hitscan projectiles PR this doesn't make it hitscan, just like twice as fast.

**Comment by anconfuzedrock** [comment]
don't just do it to fucking rifle currently you can fucking outrun lasers

**Comment by Bawhoppen** [comment]
that's for a good reason

**Comment by Supermichael777** [comment]
baw fuck off being able to utrun this shit is terible

**Comment by Bawhoppen** [comment]
you can't actually outrun them? they just are dodgeable

**Comment by kevinz000** [comment]
You can but I'm not touching that would be a huge balance change. But outrunning snipers is ridiculous

**Comment by PKPenguin321** [comment]
Mekhi buffing himself

**Comment by AdamElTablawy** [comment]
tbh while it makes 0 sense that you can outrun LIGHT that's one thing since they're easily available but the sniper rifle is a huge investment so being able to just sonic the bullet is annoying

**Comment by Anonmare** [comment]
Yeah but you forget you can propel yourself in space with lasers.
You know, using _light_ to move your fat asses

**Comment by CPTANT** [comment]
Who cares about shitty SS13 physics.

Basically all projectiles are too slow.

All projectile speeds should be 30% faster or so.

**Comment by TechnoAlchemisto** [comment]
Good change, variable muzzle velocity is good, and yeah it's dumb that lasers are slow by they're "sci fi lasers" not real lasers

**Comment by kevinz000** [comment]
My opinion on changing everything to be faster is goodluck getting a security buff past :^)

**Pull request merged**
