### PR TITLE
Tweaks burn rate such that fires last longer but bombs are weaker.

### LINKED ISSUE #11019: Fire burns out nearly instantly in fastmos
Combined with the changes to firestacks putting themselves out/diminishing on transfer, fires are often not very deadly at all. 

If someone call tell me where the formula for burning/consuming plasma in the air is I can try to change it myself.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This will result in longer fires and less explody TTV bombs.

God help us all.

fixes #11019
closes #12876 (pr that shouldn't be combined with this one.)

### CODE REVIEW

**Comment by Alek2ander** [comment]
:-1: I'll have to figure out superboom mixes again. Or should that be :+1: everyone will have to figure out superboom mixes again? Either way, praise chaos.

**Comment by Anonus** [comment]
I, uh, :+1: ? Maybe? I'm not sure. Probably. Toxins can make bombs in 5~ minutes right now so it's probably good.

**Comment by Supermichael777** [comment]
oop! Don't let your memes be dreams.

**Comment by Robustin** [comment]
Should be tested with TTV's before merging.

I doubt this will have the intended effect on bombs at all though. The ease of bomb making comes with being able to heat/chill canisters in science. You can use those to achieve any desired mix within minutes, forcing me to perfect the ratios won't make it any slower after an hour when the new ratios are discovered.

**Comment by Alek2ander** [comment]
I already did some tests. Pretty sure you can't reach bombcap without at least tier 3 parts.

**Comment by as334** [comment]
Toxins REALLY doesn't need a nerf, since chem explosives are already better in every way in terms of availability, ease to construct and suspciousness:-1:

**Comment by Anonus** [comment]
You can't nerf the speed to construct easily because you'd need multiple huge delays to connect stuff to a TTV to nerf the speed.

**Comment by Robustin** [comment]
>Guys we should test this

>Its in the changelog by the time I get home

**Comment by Tokiko1** [comment]
:+1: Indifferent about the bombs, but the TEG and the turbine really needed slower fires for a while now.

**Comment by KorPhaeron** [comment]
@Robustin

Notice how this PR is still open. We ARE testing it

**Comment by Miauw62** [comment]
:+1: for the fires alone

**Comment by bgobandit** [comment]
@Robustin

it's in the changelog as a temporary test, the only way to test it on a live server is to, well, test it on a live server

**Comment by Robustin** [comment]
Well I tested it.

1) Has no identifiable effect on fires. They still burn out just as fast as before. If it weren't in the changelog I wouldn't even believe you if you told me the fire code had been changed.

2) It has a major effect on bombs. Currently this PR/Test might as well be called "huge bomb nerf" because even with optimized mixes you're looking at a 33%-50% reduction in power. I might be able to make them a little stronger on box since I don't have to rely on the shitty burn chamber there but considering that a linear increase/decrease of "paper" bomb strength (i.e. 3/10/20) results in an exponential change to its power, and the r_wall changes from a few months ago, bombs are weaker than ever, in a place with plenty of r_walls you will question whether a TTV or a minibomb has gone off. 

Given that your test change had no effect on fires burning themselves out in seconds, maybe find another approach that doesn't gimp bombs in the process.

**Comment by Shadowlight213** [comment]
@Robustin nerfing bomb is intentional though.

**Comment by duncathan** [comment]
@Shadowlight213 the primary goal of this PR was to get better fires along with nerfed bombs, not just the bombs.

**Comment by Shadowlight213** [comment]
@duncathan I know that. Robustin was just saying make a fire change that doesn't gimp bombs, and I replied that nerfing bombs was intended alongside the better fires. Bomb nerfing wasn't unintended.

**Comment by Alek2ander** [comment]
Looks like when dealing with fires 2 times very honking short is still very honking short. Therefore, suggestion:
Plasma burn rate scales with the amount of Nitrogen. Without any Nitrogen the burn rate should be pretty much the old one, with Nitrogen at the amounts expected in normal station air it should slow down significantly (10x or more).

**Comment by Robustin** [comment]
I thought the issue was people didn't want 5-minute bombs, not people wanted bombs to be weaker than ever.

Either way, booo, between this change the attempt to remove Hulk and all the pushing for removing slipping, it's really disheartening to see all the station's robust tools being chipped away and all the amusing traits of SS13 being destroyed.

**Comment by Miauw62** [comment]
le hugfgxbox xddd
no nerfff plx sno hugboxxx

**Comment by Shadowlight213** [comment]
@Robustin bomb damage is Much, Much more than just filling in a hole. 
I'm not sure how often you play engineer, but bomb damage requires, filling in the hole, repressurizing, rewiring, fixing APCs, repiping, etc. Once you finish that, you gotta go do it for the other 4 holes on station. Of course this is also while hoping the heads don't panic and call the shuttle.
Even if you do manage to fix shit, the floor tiles are all the wrong color.

**Comment by MrStonedOne** [comment]
There was a good chance the test was flawed.

I found a bug that kept hotspots from un-marking the turf as having a fire on it once they died out. Because light fires would cause hotspots to go out then come back as the temperature of nearby turfs overwhelmed the fire temperature with their non fire temperature, then the core fire turf would re-spread.

This is an effect that is more noticeable in lower burn speeds because it also lowers the temperature increase rate (since those two scale off of eachother)

**Comment by dumpdavidson** [comment]
ADMIN LOG: Explosion with size (6, 12, 24, 0) in area Derelict Aft Solar Array (173,112,4)

This just changes the recipe scientists have to use to be a bit more complex.

**Comment by MrStonedOne** [comment]
Ya, thats what I was hoping for, half the explosion side, twice the burn time.

It is a bit less simple then half, as it's offseted, so you notice it more at lower levels but less at higher levels to some degree, but still.

I've been too busy to test this more, and apparently i suck at toxins now. but if that's what you're getting, I say mark this as ready, and we can revisit it if it's too bad

**Comment by duncathan** [comment]
I'm not merging this one; two controversial PRs is enough for my first day

**Comment by dumpdavidson** [comment]
Okay this does pretty much remove canister bombs now that I think of it. Not sure if I like it anymore.

**Comment by Dorsisdwarf** [comment]
:+1: trial it

**Comment by Amemelius** [comment]
Too much of a hardhanded nerf. Also what Robustin said, it feels like with all the recent changes that are being pushed we're trying to chip away at any sort of robust equipment on the station slowly, despite the lethality polling and so forth. Bombs are weaker than ever since they hardly penetrate rwalls and only marginally walls, which line much of the station, and the damage they do is often fixed very quickly due to the better tools engineering has.

Bombs don't need another nerf. I don't know what you guys obsession is with nerfing everything, but it's got to stop. You're even nerfing fucking magic missile for some reason, when the only problem with the wizard's toolkit was infinitely spammable timestop. How about we get some actual buffs instead of nerf after nerf after nerf? I mean, the only flat buff posted in recent memory was the brand new chem buff, but that will inevitably be nerfed in another two weeks or so.

**Comment by Dorsisdwarf** [comment]
Yeah, but the bombcap is STILL higher than it's ever been and you can STILL hit maxcap easily.

**Comment by Robustin** [comment]
You can still hit maxcap because this PR is no longer testmerged.

When it was testmerged I could not get maxcap with any of the methods I tried.

**Comment by Zilenan91** [comment]
So is this merge ready

**Comment by dumpdavidson** [comment]
I tested it on this branch Robustin. You're just doing it wrong.

**Comment by MrStonedOne** [comment]
I'd say go for it
@tgstation/commit-access

**Comment by phil235** [comment]
Let's give it a try.

**Comment by Robustin** [comment]
Ugh AFAIK nothing has really changed since this was test merged, this is still just a bomb nerf PR that does nothing for fires. I can test it, again, but the majority of responses say this puts maxcap out of reach and it removes canister bombs which are awesome.

So yea all I see here is 3-4 people wanting a bomb nerf and pushing it through because MSO ded plz nerf.

**Comment by optimumtact** [comment]
And all I see there is someone upset that the bomb meta changed and they're not as robust as they used to be.

**Comment by dumpdavidson** [comment]
>the majority of responses say this puts maxcap out of reach 
who cares when they're wrong though?

**Comment by Zilenan91** [comment]
Fires are actually super robust now, they're almost like slowmos fires.

**Pull request merged**
