### PR TITLE
Atmos Filter/Scrubber UI update

### PR DESCRIPTION
**Pull request by duncathan**
:cl:
add: Atmos scrubbers (vent and portable) can now filter any and all gases.
/:cl:

image

### CODE REVIEW

**Comment by ACCount12** [comment]
Keep in mind that O2/N2 options allow AI to depressurize the station without flashing the telltale "AI is asshole" red siphon.

**Comment by duncathan** [comment]
They will trigger air alarms though, which is a reasonable tradeoff imo.

**Comment by Anonmare** [comment]
Now plasma people can have scrubbers that filter oxygen for their own private use

**Comment by Anonmare** [comment]
Also I swear I remember being able to scrub Oxygen once upon a time but for the life of me I can't find anything in the history to support that

**Comment by Shadowlight213** [comment]
@anonmare you're probably thinking of bay. Theye had scrubbing all gasses for a while

**Review by ninjanomnom — DISMISSED** [review]

**Pull request merged**
