### PR TITLE
Various Lavaland (and other) Sprite Updates

### PR DESCRIPTION
**Pull request by Mey-Ha-Zah**
## About The Pull Request

This Pr updates various item sprites from lavaland, including sheets, gear, weapons, an organ, trophies and such. Also logs for some reason, don't know why I did just did.

image

Thanks [rlee595](https://github.com/rlee595) for the bone axe.
## Why It's Good For The Game

Better quality sprites equal a better looking game.

## Changelog
:cl:
image: Modifed various lavaland related items. Mostly items with relation to fauna. You can now see features through bone armor. Log sprite also updated. rlee595 Did bone axe.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
The armor worn sprite makes them look fat as hell

**Comment by Mey-Ha-Zah** [comment]
Also IDK it still says merge conflict I fixed it...

**Comment by Pumpkinoe** [comment]
Hey, so, wouldn't removing the shoes & glove parts of the bone armor change how it functions? Doesn't it currently work as shoes or something right now? I might be wrong.
Also, would be really nice to get a lineup of all the sprites outside of campfire light on lavaland since it's very hard to make out the colours - Hope in this looks red.

**Review by Fikou — CHANGES_REQUESTED** [review]
you made bone armor not visually cover your body, you should update it's cover flags and such to be consistent with that.

**Comment by Mey-Ha-Zah** [comment]
image

**Comment by Mey-Ha-Zah** [comment]
To fix fikou's issues, but since this pr isn't about adjusting balance, I've updated the visuals to cover the body.
image

**Comment by orthography** [comment]
Doesn't this cause you to break your ass if you step on a cactus or glass?

**Comment by Mey-Ha-Zah** [comment]
> Doesn't this cause you to break your ass if you step on a cactus or glass?

These should always remain as a possible counter to ashwalkers until they get their hands on a modsuit or something, 6 bones for the ability to ignore glass is not really balanced.

**Comment by Helg2** [comment]
> These should always remain as a possible counter to ashwalkers until they get their hands on a modsuit or something, 6 bones for the ability to ignore glass is not really balanced.

It should be a balance chance then i think.

**Comment by Helg2** [comment]
image

**Comment by Mey-Ha-Zah** [comment]
what I SWEAR

**Comment by Mey-Ha-Zah** [comment]
> image

You are imaging things

**Comment by Mey-Ha-Zah** [comment]
> > These should always remain as a possible counter to ashwalkers until they get their hands on a modsuit or something, 6 bones for the ability to ignore glass is not really balanced.
> 
> It should be a balance change then i think.

Fikou told me to update the cover flags, and I opted to update everything but feet because I dont wanna sprite new boots on the armor.

**Comment by Pumpkinoe** [comment]
new herald cloak is a bite of a downgrade tbh, now it's more of a shawl
sure you couldn't make it longer, maybe incorporate some of its badass spikes rather than the weird eyeballs on it right now?
doesn't the current cloak also have different cover flags, just like what's happened with the skull armor?

**Comment by Pumpkinoe** [comment]
image
image
Your cover flags dog...
code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm if you want to find where the herald cloak code is kept

**Comment by Mey-Ha-Zah** [comment]
Well the previous herald cloak was a copy paste of the goliath cloak with shoulder spikes
New Herald doesn't have those spikes, so I gave it shoulder cannons... but I didn't quite feel right. IDK what to do.

**Comment by Mey-Ha-Zah** [comment]
You know what, I'm unhappy with a few items, and I only opened this because I didn't want to get overloaded with sprites, but I'll make a new PR when I am happy with everything.

**Pull request closed without merging**
