### PR TITLE
Reverts soft crit

### PR DESCRIPTION
**Pull request by lzimann**
Reverts #28649
Alright, so, PR closed for over 2 months, reopening and fast merging, not so good but still valid. 
But fast-merging after pushing to the branch yourself is really shitty(no, I don't care how minimal the push is, still a shit thing to do).

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by KorPhaeron** [comment]
I deleted commented out code again to fix a conflict, go take it up with Cheridan

**Comment by CPTANT** [comment]
Lol, Izimann suddenly caring about the rules.

**Comment by KorPhaeron** [comment]
@CPTANT 

He just doesn't like the change

**Comment by RemieRichards** [comment]
"""design lead""" overstepping his bounds.
@ChangelingRain is working on a new PR, that can be properly reviewed and test merged first

Rather than a PR from JUNE being revived and instamerged

**Comment by KorPhaeron** [comment]
@RemieRichards 

Then wait for the head coder to tell me that if this is about process, revert wars aren't really condoned by the rules either

**Comment by RemieRichards** [comment]
No.
There is no justifying instantly merging a PR from June (2 months old) and if he tries to justify it then he's a fool.

**Comment by lzimann** [comment]
for future reference: the pr was not even working properly

**Pull request merged**
