### PR TITLE
Adds a robotic stomach and makes androids have more robotic organs

### PR DESCRIPTION
**Pull request by Ziiro**
## About The Pull Request

I was doing some testing with an android character and I found it weird they still had meat organs. Fixed that.

## Why It's Good For The Game

More consistency in what an android is. Also more cybernetic organs with funny EMP effects is always cool

## Changelog
:cl:
add: Adds a robotic stomach to the tech web for Mechafabs and Medical Protolathe
tweak: The android species now has robotic eyes, robotic stomach, and robotic ears.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
aren't these better than human organs

**Comment by Ziiro** [comment]
Most of these aren't better. I think maybe the robotic ears take 10% less hearing damage? But all of these have an EMP drawback.

**Comment by Ziiro** [comment]
travis man bad

**Comment by Shadowflame909** [comment]
when the guy who spent the last 30 minutes getting augmented meets my bartender drink of iron + uranium

**Comment by shellspeed1** [comment]
Would it be possible to do an upgraded cybernetic stomach for consistency?

**Comment by Ziiro** [comment]
Problem is I'm not sure what an upgraded stomach look like that doesn't involve me digging around and shitcoding weird stuff. (Vomit code? Taste code? Nutrition going longer?)

Plus that kind of falls under the purview of the nutrition implant. This organ exists just so there's a cybernetic replacement option for the stomach, as well as make it so androids are less meat.

**Comment by Megarop** [comment]
hear me out here
what if we made the nutriment pump stomach replacement instead of an implant and give the synths that instead of a stomach

**Comment by WarlockD** [comment]
So is the "sick" feeling not a component?  I feel like the nutrient implant needs to be separate.  Maybe the normal stomach just prevents the sick so the user doesn't have racial limits on food and the upgradeded one prevents getting fat. Aka bottomless.

**Comment by ExcessiveUseOfCobblestone** [comment]
taking the pump out and replacing it with the stomach would be okay with me tbh. the implants are just wanna be organs anyways.

**Comment by Ziiro** [comment]
Actually that sounds like a good idea. I can do that.

**Comment by Ziiro** [comment]
Alright well I made all those changes and it worked and then I fucked up using git and fucked up my branch because I am a moron have a nice night everyone

**Comment by Tharcoonvagh** [comment]
Darn

**Pull request closed without merging**
