### PR TITLE
New food, drink, and pen sprites

### PR DESCRIPTION
**Pull request by ghost**
ported some sprites from https://github.com/yogstation13/yogstation/pull/2395 (coffee comes from para)

:cl: More Robust Than You
spriteadd: New food, drink, and pen sprites
/:cl:

capture

### CODE REVIEW

**Comment by ChangelingRain** [comment]
why are you porting pillow-shaded garbage

**Comment by Hatfish** [comment]
those pens are some of the ugliest sprites ever conceived.

**Comment by Lexorion** [comment]
I like the pens we currently have a lot more.

**Comment by Armhulen** [comment]
lexorion sums it up pretty well

**Comment by Repukan** [comment]
Do they have a vibrate setting?

**Comment by MoreRobustThanYou** [comment]
Would you guys like this if I didn't mess with the pen sprites?

**Comment by Kerbin-Fiber** [comment]
Yeah, don't mess with the pens, ours are better. The food looks nice though.

**Comment by PKPenguin321** [comment]
Hahahahahahahaha

**Comment by PKPenguin321** [comment]
The fuck are thoooose

**Comment by DoctoreMad** [comment]
I'll accept the tomato and the orange juice, everything else is strictly worse than what we have.

**Comment by DoctoreMad** [comment]
Get a load of this

toot

**Comment by ExcessiveUseOfCobblestone** [comment]
this isn't reddit

**Comment by Super3222** [comment]
different communities, different opinions

**Comment by DaxDupont** [comment]
All of these look bad.

**Comment by KorPhaeron** [comment]
Universal dislike, sorry

**Pull request closed without merging**
