### PR TITLE
Removes crewpinpointer from wardens locker

### PR DESCRIPTION
**Pull request by jughu**
YOU SHOULDNT BE ENCOURAGING THE WARDEN THATS SUPPOSED TO WATCH OVER BRIG TO GO OUT

:cl: Improvedname
Remove: removed wardens crewpointer
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
I could see an argument going both ways

**Comment by jughu** [comment]
prepare yourself bawhoppen this is gonna be a storm

**Comment by Repukan** [comment]
It's so the warden can give it to an officer.

**Comment by DaxDupont** [comment]
Wouldn't it make more sense to add it to the sec vendor then

**Comment by jughu** [comment]
@Repukan now the hos can do it if he really wants to!

@DaxDupont you can already get these from medvendors would be to powercreep to add them to sec too

**Comment by DaxDupont** [comment]
@jughu if you don't want to add them to the sec vendor then the warden should keep it. It should arguably be moved to the armory instead of the locker though.
Warden's job is to guard brig and hand out the gear when the need is there.

**Comment by jughu** [comment]
it isnt hand out if it starts in his locker

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
I'm not sure gating it to the HoS is the right idea

**Comment by BeeSting12** [comment]
Just leave it in the warden's office, he can give it to an officer if needed.

**Comment by jughu** [comment]
@Cyberboss 

theres 4 outcomes really
1. Being put into hos locker
2. keep it in warden's locker but it would encourage them going out
3. adding it to secvendors but then plus medbay ones it gets to much especially if a officer gets easy tracking
4. remove it completly

**Comment by DaxDupont** [comment]
Move it to the armory instead

**Comment by jughu** [comment]
If i move it to the armoury its basical still in the wardens locker since you can use a ion rifle to open it

**Comment by Repukan** [comment]
Is there any evidence, via stats or pictures, of wardens leaving the brig motivated solely by this to hunt antags or people?

**Comment by jughu** [comment]
Warden litteraly gets a crew pointer that be a natural action and most of the wardens ready go out most of time and if i put in the secvendot it just becomes a race who is there first

**Comment by jughu** [comment]
If a admin could make a poll about the options given that be nice

**Comment by KorPhaeron** [comment]
I think the detective already gets one, rest of security doesnt need med equipment

**Comment by jughu** [comment]
@korphaeron so remove it from wardens locker enterily?

**Comment by KorPhaeron** [comment]
Yeah

**Comment by jughu** [comment]
Done

**Comment by jughu** [comment]
@korphaeron this is ready

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by jughu** [comment]
FUK

**Comment by Bawhoppen** [comment]
you just got :fishing_pole_and_fish: BAITED :fishing_pole_and_fish:

**Pull request merged**
