### PR TITLE
resprites 9 hair styles

### PR DESCRIPTION
**Pull request by junkgle01**
## About The Pull Request
resprites the following hairstyles:
Ponytail 6
Kusinagi / Pigtail 1
Pigtails 2
Country
Comet
Braided
Long Side Part
Ponytail 7
Tress Shoulder

<details><summary>Before</summary>
<p>

(null)scrnshot1-export

</p>
</details> 

<details><summary>After</summary>
<p>

actuallyusethisone2-export

</p>
</details> 

the after image is a _little_ outdated but i'm not lining up like 30 characters again

## Why It's Good For The Game

resprites are good!!!

## Changelog
:cl:

image: resprited a few hairstyles

/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
Pigtails/country look really off, like someone took a slice off the top/left side respectively - other than that, great job!

**Comment by carpotoxin** [comment]
Not sure what you changed on pigtails and country according to the previous comment, but they look great to me in the preview.

**Comment by SmArtKar** [comment]
> Not sure what you changed on pigtails and country according to the previous comment, but they look great to me in the preview. No edits necessary.

the screenshot is updated fyi, its good now yeah

**Review by Wallemations — APPROVED** [review]
Great job keeping the style of the originals while updating them

**Comment by DrAmazing343** [comment]
ponytail 6 sovl destroyed... but the season 2 budget is RISING YEAHHHH BABY WE MAKIN' IT BIG WIT THIS ONE YEAHHH

**Comment by krookodilehunter** [comment]
at first i was little bummed about the new country ponytail, but THE NEW SIDE ONE IS SO CUTE HELL YEAH!!!!

**Pull request merged**
