### PR TITLE
test disables ai static to see if it helps maptick enough to justify a refactor of how it works

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
looked at the sendmaps profilers on live and found out that the average movables examined per iteration were > 800 a lot of the time, in a panic i tested things that would justify that number. turns out that vis_contents on turfs is scanned with somewhere between a +10 to +12 radius on view range while normal movables are scanned with a radius of about 1 + view size

this means that vis_contents on turfs are scanned over a huge area, and the most common vis_contents on turfs by far is the ai static movable added to all tiles the ai moves over but arent in range of cameras. if everything counted by the looking for movables step of the sendmaps profiler was equal i expect this would be a large improvement, but i also suspect that vis_contents for shared movables arent as costly to scan as movables on turfs. so we'll see what happens

## Why It's Good For The Game
maptick sucks i hate it its still the single largest cause of lag and its been slowly but surely increasing since underlay lighting. i want to bring it below at least 0.4 so we dont hit the maptick time dilation threshold at 15 players below our expected high pop numbers but i need data on whats causing it

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
AI's randomly just stop getting AI static, so regardless of maptick I think there's some reason to justify a refactor of some sort https://github.com/tgstation/tgstation/issues/38857

**Comment by bluetshirtguy** [comment]
How long does this need to be test merged anyways?

**Comment by Kylerace** [comment]
@bluetshirtguy until the stats graph finalizes which should be in a day or two

**Comment by Kylerace** [comment]
Maptick_Average_by_Server
ok results are in, its about a 0.1-0.12 decrease in maptick per person so thats pretty good

**Pull request closed without merging**
