### PR TITLE
makes vtec module take a small amount of silver

### PR DESCRIPTION
**Pull request by Iamgoofball**
this way mining is required for vtecs and they aren't a roundstart thing

but in the event of no miners R&D isn't completely screwed

alternate fix of #7532

### CODE REVIEW

**Comment by paprka** [comment]
>implying vtecs are the only reason i removed the gold

**Comment by Miauw62** [comment]
Muh sanic secborgs
Op 4-feb.-2015 02:19 schreef "paprka" <notifications@github.com>:

**Comment by Dorsisdwarf** [comment]
There's silver ore in the mining bay. All this does is make you need to nag the cargo tech to take the bar out of the machine. To remove roundstart sanic, you'll need to take that away too.

As fun as sanic is, it's way too easy right now, and I agree with this PR.

**Comment by Saegrimr** [comment]
"i ded pls nerf"

This is fucking hilarious.

**Comment by pudl** [comment]
this is literally the definition of i ded pls nerf, get over it pls

**Comment by paprka** [comment]
Reopened https://github.com/tgstation/-tg-station/pull/7532 because it's better still.

**Comment by GunHog** [comment]
@Iamgoofball I recommend you change the requirement from gold to uranium. The issue being roundstart minerals is solved this way. This way will require miners OR the borg going to the mine to get uranium. Hopefully this means the borg will bring some other things back or face being denied the VTEC by angry Roboticists.

**Comment by Iamgoofball** [comment]
@Saegrimr 
@pudl 
i personally have nothing against this but I felt this was a better fix then removing gold from the vault

@GunHog i can do that

**Comment by Jordie0608** [comment]
Changelog.

**Comment by hornygranny** [comment]
fixed by #7554

**Pull request closed without merging**
