### PR TITLE
Added transit tubes to the RPD

### PR DESCRIPTION
**Pull request by Cruix**
:cl: 
add: The Rapid Piping Device can now dispense transit tubes.
/:cl:

untitled

Transit tubes are fun, but they are almost never built because disposal pipes are so much easier to make with the RPD. In addition, transit tubes are usually built in space, which makes it a pain to use the stationary transit tube machine which requires a powered area.

### CODE REVIEW

**Comment by Jalleo** [comment]
creating meters via the RPD is broken currently can you fix that?

**Comment by Cruix** [comment]
That is for another PR

**Comment by Dorsisdwarf** [comment]
Are transit pipes still dense? Because if transit pipes are being made creatable by the RPD, they need to be non-dense like wastebins were made to avoid free infinite area denial by spamming them

**Comment by Cruix** [comment]
Transit tubes are not dense until they have been wrenched.

**Comment by Cyberboss** [comment]
OP imo

**Comment by Bawhoppen** [comment]
Feels like it's going to far with magical synthesis of large objects...

**Comment by Cruix** [comment]
We passed the ridiculous magical free tube synthesis line a long time ago.

Pros of transit tubes over disposals:
* They are airtight
* They don't require being welded in place
* They look much cooler and more realistic

Cons of transit tubes over disposals:
* They are much, much slower
* They cannot make sharp turns
* You can only walk over the straight ones
* They cannot be hidden under the floor
* More realism means they don't fit the "screaming metal deathtrap" theme as well

In all my years playing this game, I cannot recall a single time someone other than me made a new transit tube system. I am sick of hauling that machine around, wrenching it in place, waiting on the 1.5 second dispensing cooldown, and clicking on the tiny corner of each tube that sticks out from under the machine when they are dispensed.

Unless being able to make them quickly is a significant balance concern, and I do not see why it would be, the creation of transit tube systems should not be limited by their creation being a pain in the ass.

**Comment by PKPenguin321** [comment]
Make sure they're non-dense until wrenched down so you can't flood a hallway with impassable pipes

**Comment by Cruix** [comment]
untitled

**Comment by duncathan** [comment]
fuck yeah

**Pull request merged**
