### PR TITLE
Fixes cables being broken on space ruins by levelupdate()

### LINKED ISSUE #32519: All wires on derelict station point up
Round ID: 78491

For clarity, I mean the exploded, "Russian" station.  I spawned on one of the derelict drone shells and discovered (along with one other player) that all the wires point north.  On tiles where there was more than one wire, they were all on top of each other.

I crowbarred up a few floor tiles to take [this image](https://i.imgur.com/FDyxM59.png), in case my description sucks.

I don't recall this being a problem the last time I was on the derelict station (which I believe was last night) and the server revision points to a [commit from 3 days ago](https://github.com/tgstation/tgstation/commit/d5b9b56858e7c0c52fe1fe239e76defef1f2b180).  I'll be trying it again in a moment to see if it persists between rounds.

EDIT: Seems to have persisted to the next round.  Oddly, the round ID is now 78493.  Maybe I mistyped it originally?

EDITx2: [Extra obvious photo](https://i.imgur.com/SV0SXvo.png), because a friend didn't believe me.

EDITx3: Was poking around the recent commits and noticed [this one](https://github.com/tgstation/tgstation/commit/f6e7a7f249386d5b21179cb4ea59c488e83fee5a) from a couple days ago that was meant to clean up some wires.  It may have cleaned a bit too much.

### LINKED ISSUE #32599: Wires broken on most if not all space ruins
Saw this on the derelict and on the ancient station, here's a pic: https://file.house/oOjl.png

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #32519
Fixes #32599
Closes #32584

### CODE REVIEW

**Comment by AnturK** [comment]
But where is it called from ?

**Comment by ninjanomnom** [comment]
image

**Comment by ShizCalev** [comment]
Moved the init check from update_icon() to hide(), since cable/init already calls hide() anyway, making the call from levelupdate() redundant.

**Comment by ninjanomnom** [comment]
This feels like a bad fix when we already have a way to stop afterchange being called.

**Comment by Cyberboss** [comment]
Ninja's gets the root issue

**Pull request closed without merging**
