### PR TITLE
Adds several templates for space ruins

### PR DESCRIPTION
**Pull request by MMMiracles**
I mean the system exists already and was lacking templates so why not.

**Includes:**
- 5 asteroid templates
- 5 derelict templates
- a space bar (includes a spawner for single ghost to take control of the bar's owner)

Space bar is essentially a giant glass dome ontop of an asteroid with an airlock system for pods.

The minimum size is 20x20 up to 40x40. I made most in mind with hooks and other long sections to help catch various space garbage (such as corpses) and prevent space looping. Ill try and get pictures

will get pictures eventually its hard to crop hng

### CODE REVIEW

**Comment by Zilenan91** [comment]
Can escape pods dock at the space bar? Or are you talking about the spacecraft pods?

**Comment by MMMiracles** [comment]
@Zilenan91 Its just decorative pods.

**Comment by KorPhaeron** [comment]
Do this for lavaland next please thanks

**Comment by Zilenan91** [comment]
So is the space bar literally just the bartender or can ghosts take over the patrons too?

**Comment by MMMiracles** [comment]
@Zilenan91 Only the bartender is an option to take over. Any potential customers or patrons will be the space-goers who happen to bump into it.

**Comment by Zilenan91** [comment]
That sounds boring as hell though, why would a ghost just sit there, possibly forever, waiting for someone who might not even come to him.

**Comment by MMMiracles** [comment]
@Zilenan91 I mean its either that or be a dead person. More ghost-jobs based solely around RP instead of side-antags is a nice thing to have.

**Comment by Zilenan91** [comment]
But how can you rp if you're going to be alone in a round 9 rounds out of 10

**Comment by YakumoChen** [comment]
idea: put a drone spawner in the space bar, but make them snowflake drones with a law that they can't leave the bar.

**Comment by octareenroon91** [comment]
Is it intentional that these are all commented out by default?

**Comment by octareenroon91** [comment]
Would you mind making these maps loadable via the load-map-templates system added in #13852 ?

**Comment by tkdrg** [comment]
I think the entire system is commented out. You might want to enable it if you're doing this. Correct me if I'm wrong @KorPhaeron

**Comment by KorPhaeron** [comment]
Nothing calls the proc currently, you'd just have to add something that would call it at startup

**Pull request merged**
