### PR TITLE
Config loading refactor

### PR DESCRIPTION
**Pull request by Cyberboss**
No more `if(config)`

### CODE REVIEW

**Comment by Incoming5643** [comment]
Have you tested this extensively? I have a bad feeling there was a reason it was like this.

**Comment by Cyberboss** [comment]
Everything looks fine to me. @MrStonedOne ?

**Comment by optimumtact** [comment]
10;40 < Cyberboss> y testmerge?

**Comment by MrStonedOne** [comment]
I was under the understanding that sleeping in a pre-world init proc fucked shit up, and disk i/o sleeps, and thats why it was this way.

**Comment by optimumtact** [comment]
11:04 <+MrStonedOne> Cyberboss, 
11:04 <+MrStonedOne> server crashed
11:05 <%oranges> MrStonedOne: sybil?
11:05 <+MrStonedOne> yes

after a test merge of this

**Comment by Cyberboss** [comment]
Wew

**Comment by MrStonedOne** [comment]
>I was under the understanding that sleeping in a pre-world init proc fucked shit up, and disk i/o sleeps, and thats why it was this way.

**Comment by Cyberboss** [comment]
Strange... Guess I'll call it quits

**Comment by Cyberboss** [comment]
It's now just moving load_configuration out of world.dm + other cleanups

**Pull request merged**
