### PR TITLE
[Ready for Merge] ReAdds AsteroidStation

### PR DESCRIPTION
**Pull request by CorruptComputer**
DNM until feature freeze is over, just PRing this because I'm gonna be away for awhile.
Feel free to edit if you find any problems.

I spent a long time fixing everything that everyone complained about and getting it up to date.
The most notable changes are:
- Added solars
- Remade the asteroid
- Remapped science
- Changed the layout of medical slightly
- Got everything up to date

asteroidstation

EDIT: Just noticed that I didn't crop the image correctly, I can make another if someone requests it.

### CODE REVIEW

**Comment by Xhuis** [comment]
༼ つ ◕ _ ◕ ༽つ PRAISE OUR LORD AND SAVIOR ༼ つ ◕ _ ◕ ༽つ

**Comment by SconesC** [comment]
iirc the northern brig cells were broken in the last version that was live

have those been fixed?

**Comment by SconesC** [comment]
also unless this map image is not updated it looks like chemistry needs chem heaters

and the brig lacks firing pins

**Comment by Supermichael777** [comment]
how do solars work if they are surrounded by asteroid?

**Comment by quaggaman555555** [comment]
OH THANK GOD YES PLEASE

**Comment by CorruptComputer** [comment]
@SconesC I'll check on the brig, and here is the layout with chem heaters:

image


@Supermichael777 I don't believe that its defined in the code that it has to be exposed to space, or you could just think of it as being on the surface of the asteroid.

**Comment by Steelpoint** [comment]
How many times will this thing be hooked up to life support?

**Comment by CorruptComputer** [comment]
Until I lose interest in SS13, because this is honestly my favorite map.

**Comment by pudl** [comment]
im going to be on irc tomorrow, i need to talk to you @corruptcomputer

**Comment by xxalpha** [comment]
I approve of asteroidstation. :+1:

**Comment by Antimattercarp** [comment]
Do we call a murderboner on asteroidstation 'roidrage?

**Comment by Niknakflak** [comment]
Solars work because space has an up and down too so in theory, its exposed to space from the top down.  Still looks odd in our 2D world though

**Comment by CorruptComputer** [comment]
Updated Screenshot:
asteroidstation

**Comment by SconesC** [comment]
Needs the Self-Destruct Device in the vault, rollernuke begone

**Comment by CorruptComputer** [comment]
What is the "Self-Destruct Device" literally every other map has the roller nuke.

**Comment by SconesC** [comment]
No?

Box and Meta do not have the rollernuke and have not for a few monthes now

**Comment by CorruptComputer** [comment]
Then the wiki pictures are out of date :/

**Comment by SconesC** [comment]
Wiki pictures are almost always out of date for areas, seriously.

**Comment by CorruptComputer** [comment]
@pudl Is currently editing the map, but she said she would do it. It'll be in the next commit.

**Comment by CorruptComputer** [comment]
Aesthetics, the vault, and added experimenter.

**Comment by AnturK** [comment]
Add the map to travis build ? Easier to tell if it needs anything that way.

**Comment by CorruptComputer** [comment]
I'm not at home right now, but I think I can add it with the github editor. If not I'll add it when I get back.

**Comment by pudl** [comment]
why the fuck would you add a map that we don't run to travis. ministation isn't on travis for that exact reason. it's rarely used and having it on travis pisses everyone off because they forget to add to the totally irrelevant and never used bullshit.

**Comment by CorruptComputer** [comment]
Because I am hoping that it gets added as one of maps run on a server. Someone talked in IRC about porting VG's voting system to allow this. Also how does this possibly have merge conflicts?? It does nothing but add files!

**Comment by CorruptComputer** [comment]
I fixed the conflict but git isn't letting me push, so I'm just gonna make a new branch :/

**Pull request closed without merging**
