### PR TITLE
Fixed abductors saying "..." out loud whenever they spoke telepathically

### LINKED ISSUE #22910: Ayys say "..." when talking
Ayy telepathy should be silent.

### PR DESCRIPTION
**Pull request by Cruix**
Fixes #22910

### CODE REVIEW

**Comment by Niknakflak** [comment]
Not a bug, I love this. Dont merge this

**Comment by FantasticFwoosh** [comment]
I also like this as a feature, it implies a chatlog notification that the abductors are actually communicating something even if you dont know what it is.

Its more wracking to end up paranoid about a abductor hovering over your chest with surgical tools intent and what they might be saying (RP wise), than for the aliens to just work silently.

**Comment by YakumoChen** [comment]
It could account for body language too.

**Comment by XDTM** [comment]
Yeah but an ayy telepathing in a locker will reveal his location, or a disguised ayy will show his real name instead of id. If you want this as a feature make it an emote.

**Comment by Shadowlight213** [comment]
Doesn't the ... show up in logging too though?

**Pull request merged**
