### PR TITLE
Hand labeler paper roll and toner cartridge can be printed at autolathe and protolathes now

### PR DESCRIPTION
**Pull request by OneAsianTortoise**
## About The Pull Request
**You can print hand labeler paper roll to refill hand labeler now.**
**Edit: You can now also print toner cartridge as well to refill decal painter and airlock painter.**

Previously you could print hand labeler, decal painter and airlock painter at autolathe and protolathes, but you couldn't print their refill at all. WHYYYYY, do you know how much it hurts the environment having to print another hand labeler once you ran out of paper roll.

## Why It's Good For The Game
I mean, you can print hand labeler, decal painter and airlock painter already. I don't see why not being able to print their refill is a thing.

## Changelog

:cl:
qol: hand labeler paper roll and toner cartridge can be printed at autolathe and protolathes now
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
The decal painter also has this problem.

**Comment by OneAsianTortoise** [comment]
> The decal painter also has this problem.

Yeah sure. I will look into it and see if I can add them as well.

**Comment by Farquaar** [comment]
You should make autolathe-printed toner cartridges arbitrarily expensive. It's more realistic that way.

**Comment by optimumtact** [comment]
i think the idea was that you would order them instead, but for minor consumables it's probably better to print.

**Pull request merged**
