### PR TITLE
removes gbp-balances.toml from master

### PR DESCRIPTION
**Pull request by tralezab**
About The Pull Request
removes gbp-balances.toml

Why It's Good For The Game
We use a new system now, old man.

Not player facing

### CODE REVIEW

**Comment by tralezab** [comment]
I'M NOT SPAMMING PRS THIS IS THE RIGHT ONE NOW

**Comment by Qustinnus** [comment]
you lost my trust and now i need proof

**Comment by notfrying1pans** [comment]
i need my gbp nfts

**Comment by notfrying1pans** [comment]
> 
> 
> you lost my trust and now i need proof
image

**Review by notfrying1pans — APPROVED** [review]
yea

**Review by Mothblocks — APPROVED** [review]
This is correct, actually--been meaning to do this for a while. Wish you would've been more specific in the description though. This one was before we moved to a separate branch.

**Pull request merged**
