### PR TITLE
[MAP|MISC] Secway/Janicart Key

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR moves the Secway's key from the Warden's backpack/hands and onto the map itself, inside the armoury ontop of the tracking implants. This PR also moves the Janicart's key from the Janitors backpack and onto the map itself.

The main reason for this is simply because if there is no Warden during a round then no one can use the Secway, which is a oversight in my opinion. This change means anyone who can access the Secway in the first place, thus the armoury, can use the Secway.

Janicart is on request.

### CODE REVIEW

**Comment by GunHog** [comment]
Is the janicart's key the same way? If so, please do so with that one as well!

**Comment by Steelpoint** [comment]
I'll check.

**Comment by Steelpoint** [comment]
Code wise the first janitor gets a key, the second gets a rifle (I mean soap).

I can change it so that the key's on the map, which I think makes sense since otherwise there's no way to use the Janicart.

**Comment by Dorsisdwarf** [comment]
Warden should also spawn with one for all those times some shitbag steals the key/ uses the secway and doesn't return the key. 

Works well on meta, where the key is all-sec access and constantly stolen.

**Comment by Miauw62** [comment]
yeah, same for janitor.

**Comment by freerealestate** [comment]
Pretty sure this was a deliberate choice by paprika, around the time he made security officers spawn with tasers (which was a shit change). Glad to see it reverted.

**Comment by PKPenguin321** [comment]
:+1: more fun carts

**Comment by stapler2025** [comment]
Why can't we just have them be id based. Carrying a key is stupid and this change just means that the first person that can greytide into the janitorial closet will steal the cart.

**Comment by freerealestate** [comment]
Because anybody being able to drive it a lot more fun than just a select few. These never get used anyway.

**Comment by stapler2025** [comment]
Make the secway based on a security ID access

make the janicart set to janitor access


Make them both hackable so that (with slightly more effort than just breaking and entering) you can disable the ID protection.

**Comment by Steelpoint** [comment]
I do think it would be neat if you did not have to hold the keys to drive the vehicles, but I do think the key concept is important since without it anyone with sufficient access could just take the vehicle away.

Anyway, just to mention it but the Janicart's key is now located on the Janitors desk, and the Janitor does not spawn with the keys anymore.

**Comment by Steelpoint** [comment]
I'm not one to shill but I would appricate if this is either merged or rejected as soon as possible, I have several other map related PR's in the backburner and I can't get them up for review for reasons of sanity.

**Pull request merged**
