### PR TITLE
[s] honk

### PR DESCRIPTION
**Pull request by Bawhoppen**
makes all insulated gloves on april fools day orange

(also brings us up to date I guess)

### CODE REVIEW

**Comment by lordpidey** [comment]
what... the fuck is with this PR?

**Comment by Bawhoppen** [comment]
its for april fools day

**Comment by lordpidey** [comment]
No, I mean the 41 commits.

**Comment by Bawhoppen** [comment]
its on the april fools branch so thats because its out of date with the master

**Comment by Cheridan** [comment]
the other prs don't have messed up commits though

**Comment by Bawhoppen** [comment]
goof's did, this will help bring the aprilfoolsbranch up to date with our actual master branch

**Comment by Bawhoppen** [comment]
ARE YOU GOING TO MERGE THIS OR WHAT

**Pull request merged**
