### PR TITLE
Adds a warning to the traitor panel for the last headrev

### LINKED ISSUE #29851: Admins can deconvert last revhead without any warning, ending round early.
There is no warning for the admin that the person is the last/only revhead when deconverting them through the TP. Led to a round ending early by mistake when they requested to be removed as a revhead via ahelp.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #29851

### CODE REVIEW

**Comment by optimumtact** [comment]
This is shitcode, is there any hook when a headrev dies? just make a counter

**Comment by nicbn** [comment]
> This is shitcode

maxresdefault

**Comment by kilkun** [comment]
its gamemode code what do you expect

**Comment by optimumtact** [comment]
<pained sienfield>

**Pull request merged**
