### PR TITLE
RPD Speeds Tweak

### PR DESCRIPTION
**Pull request by 13spacemen**
## About The Pull Request
~~Added a new RPD upgrade, the Instant Fabrication upgrade. Allows instant construction of all pipes and devices. Same tech node as the RPD unwrenching upgrade~~

Lowercased RPD name and lowered the speeds for building atmos pipes/devices, reprogramming stuff and destroying stuff
atmos 0.5s -> 0.3s
reprogram/destroy 0.5s->0.3s
## Why It's Good For The Game
QOL for atmos, makes big atmos/engi projects more viable
Loose pipes/devices don't even have gas in them no point in taking a lot of time to destroy them, they don't cost any materials to make either so nothing is wasted

This especially helps with fixing huge explosions since that leads to 50 pipe fittings being spammed everywhere and takes ages to clean up
## Changelog
:cl:
qol: Lowered the atmos build, reprogram, and destroy delays on the RPD
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
If people could instantly build transit tubes with this upgrade, then I fear people would Fortnite others with this upgrade.

**Comment by 13spacemen** [comment]
> If people could instantly build transit tubes with this upgrade, then I fear people would Fortnite others with this upgrade.

RPD costs a lot of metal and is only available in some lathes (engilathe, science?), and if people are griefing with it as nonantag that's a griefing issue

**Comment by Pickle-Coding** [comment]
> > If people could instantly build transit tubes with this upgrade, then I fear people would Fortnite others with this upgrade.
> 
> 
> 
> RPD costs a lot of metal and is only available in some lathes (engilathe, science?), and if people are griefing with it as nonantag that's a griefing issue

This isn't about nonantags or griefing. People shouldn't be able to Fortnite under any circumstances. It's just way too absurdly powerful, especially since it's free and unlimited.

**Comment by Dorsisdwarf** [comment]
yah,the whole reason we got all those annoying delays on construction was because people used rack-placing and windowmaking for combat/escape advantage

**Comment by LemonInTheDark** [comment]
Don't really like this I don't think.

### Instant Fab

Fortnighting aside, I like how delays on placing give you time to plan out what you're gonna lay down.
You don't really argue for this at all, so I don't have anything to temper that opinion.

If you want to make laying pipe faster, I think you should reduce the delay. Making it instant as an upgrade seems odd.

Honestly I don't really like instant anything, feels out of place if that makes any sense

### Instant Lose Pipes

Similar opinion, I would not be opposed to lowering the time on this,  ~35 (half second each plus transit) seconds of waiting for 50 pipes is silly, but I don't think I want to remove the delay totally.

**Comment by Toparai** [comment]
Why not just leave the delay on transit tubes and modify it however it will end up being modified for the rest?

**Comment by LemonInTheDark** [comment]
0.3 seconds for laying pipe feels a bit fast. I might just be deranged/centrist posting but I genuinely like 0.4/0.5 better. Not sure who tho which is why I feel kinda bad about saying this.
The decon time is fine, nearly instant is more then ok for that

**Comment by 13spacemen** [comment]
@LemonInTheDark atmos build speed is 0.4s now

**Comment by msgerbs** [comment]
This is such a dumb nitpick and I'm sorry, but "lowered speeds" seems a bit unclear, if I saw this in the CL I'd probably assume you made it _slower_. Can you change it to something like "lowered build, reprogram, and destroy delay on the RPD"?

**Comment by optimumtact** [comment]
Someone needs to finish teh construciton tractor

**Pull request merged**
