### PR TITLE
KiwiOui = Badmin

### PR DESCRIPTION
**Pull request by KuiperOort**
Wrong server indeed. My apologies, and delete this.

### CODE REVIEW

**Comment by Haevacht** [comment]
You tried.

**Comment by Jordie0608** [comment]
I believe you have the wrong codebase.

**Comment by lzimann** [comment]
i agree kiwioui is a really bad admin
also wrong server friend!

**Comment by moonheart08** [comment]
He had the wrong codebase haha, ment my personal fork on OBA-code

**Pull request closed without merging**
