### PR TITLE
Clean up atmos meta map + qol

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Clean up meta map from using the manifolds everywhere to using the directional sprites in the map editors.
Adds layer adaptors on the outputs of the main tanks so that players don't have to break windows to replace a pipe (the adaptors are color coded already)

## Why It's Good For The Game
less eyesore for the mappers, better experience for atmos players

## Changelog
:cl:
qol: edited metastation map to use directional sprites instead of the manifold ones
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Why give every mix tank roundstart layer manifolds? Players can make close to the same thing on their own, so why do it for them?

**Comment by Ghilker** [comment]
I got many requests to add those manifolds way before the smart pipes and since people are having a tough time I figured this could help a lot with dealing with the change of pipe system

**Comment by LemonInTheDark** [comment]
Couldn't we fix this problem by running the air mix under the windows? or am I missing something

**Comment by Ghilker** [comment]
Running pipes under windows and walls is a bad move imo, also the main issue here is that many people keep on using the grey pipes and break everything every time they want to do something, this should help, but if you think is best to not add those manifolds I'll remove them

**Comment by LemonInTheDark** [comment]
It'd be nice if you could do that

**Comment by Ghilker** [comment]
done so

**Pull request merged**
