### PR TITLE
Removes hardsuit from bulldog bundle

### PR DESCRIPTION
**Pull request by LanCartwright**
replaces it with thermals

price reduced from 16 (worth 20) to 13 (worth 16).

### CODE REVIEW

**Comment by WJohn** [comment]
:+1: Nice upgrade, I'd say.

**Comment by Lumipharon** [comment]
That's honestly a tad OP, considering bullcuck is 2 hit crit, and thermals are robust as fuck.

Why does the bulldog bundle get unrelated extra shit in it, by the way?

**Comment by newfren** [comment]
Any particular reason for the change?

**Comment by AlexanderUlanH** [comment]
Thermals would make more sense for the sniper rifle bundle. At least the hardsuit was related to something you could do with bulldogs.

**Comment by LanCartwright** [comment]
People got upset about the hardsuit and the bulldog being 2efficient.

Anyway this doesn't actually have to go through. If you'll hate it that much I'll close it and get the sniper bundle changed.

**Comment by Anonmare** [comment]
IIRC thermals makes you vulnerable to flashbangs, the flash protection form the hardsuit is nullified by them.

**Comment by Lumipharon** [comment]
I just don't understand why every other bundle has shit related to the gun -ie: ammo, while the bulldog has completely unrelated pieces of gear.

**Comment by LanCartwright** [comment]
the only other related item would probably  be adrenals (get close) and shield.

Both are really iffy to cram into a package.

**Comment by Lumipharon** [comment]
Err... what about like, ammo? That's pretty related yo.
Bulldogs have tiny mags, and the bundle only comes with 2 spare.

**Comment by duncathan** [comment]
Why not?

**Comment by LanCartwright** [comment]
do not blame me please

**Comment by Lumipharon** [comment]
>c-20r bundle comes with c-20r ammo/suppressor for the gun
>m-90 bundle comes with m-90 ammo/40mm nades/cigarettes

>bulldog bundle comes with some ammo and thermals

Eh, whatevs.

**Pull request merged**
