### PR TITLE
Fixes some quirks with motorised wheelchair density

### LINKED ISSUE #67921: Motorised wheelchairs don't knock over monkies, manual wheelchairs do.
split from #67912 to keep things tidy

I play bartender a lot and want to be able to run over pun pun. the little bastard keeps getting in my way.
While using the paraplegic quirk, manual wheelchairs knock monkies over, but motorised wheelchairs do not. It'd be cool if they were both consistent on this.
I assume this happens for the same reason as #67920

**Reproduction:**
drive into pun pun or any other monkey on a motorised wheelchair.

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Fixes https://github.com/tgstation/tgstation/issues/67921 and https://github.com/tgstation/tgstation/issues/58062

Problem: Motorised Wheelchairs (unlike manual ones) become dense when a mob is buckled. This means you can't trample pun-pun any more, and also means that you can't build certain structures while riding one but can in a manual wheelchair.
Solution: Don't become dense while buckled to a motorised wheelchair.

Problem: Without being dense, Bump will not be called on living mobs you drive into, and so the emag bomb doesn't explode when you run into someone.
Solution: Manually track when we try to bump living mobs and Bump them.
I don't like this solution very much but it was the only way I could think of to preserve existing desired behaviour without making the wheelchair Dense, which itself causes other bugs. 

Perhaps the wheelchair emag response could do with being replaced with something less lazy (why can it materialise a bomb?) but then this would be a balance/feature PR and not a bug fix.

## Why It's Good For The Game

It's good for the two kinds of wheelchair to act consistently, especially if the manual behaviour is more desirable than the motorised behaviour.
It's annoying for people to carry around two wheelchairs so that they can get into a different one if they want to build several walls without crawling around on the ground.
It's funny to run pun-pun over with your chair.

## Changelog

:cl:
fix: Construction and ape-crushing behaviour should be more consistent between manual and motorised wheelchairs.
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
does this effect ramming people with a particular fast motorised wheelchair?

**Comment by Jacquerel** [comment]
> does this effect ramming people with a particular fast motorised wheelchair?

Good catch, it did. 
It should work the same now after this most recent commit.

The intention is that everything should work the same way apart from that you can also trample small mobs and construct wall girders, the same as you can in a manual chair.

**Comment by dalmationer** [comment]
Yesss! I've been hoping for this for some time. Means I don't have to awkwardly have my character switch to another wheelchair (my building wheelchair) just to make a girder, then awkwardly switch back, because it looks very silly.

You can already blow up a motorised wheelchair by putting plasma in the battery, so honestly my gut instinct is to make emagged ones just run people over like mulebots.

**Comment by Jacquerel** [comment]
> Yesss! I've been hoping for this for some time. Means I don't have to awkwardly have my character switch to another wheelchair (my building wheelchair) just to make a girder, then awkwardly switch back, because it looks very silly.
> 
> You can already blow up a motorised wheelchair by putting plasma in the battery, so honestly my gut instinct is to make emagged ones just run people over like mulebots.

I will probably earmark this as a future project, but not part of this PR.
I'd need to keep this code here in any case to properly retain crashing into people even if I replace the emag function.

**Pull request merged**
