### PR TITLE
Stops swarmers from attacking field gens/turret covers

### LINKED ISSUE #37702: Swarmers can attempt to dismantle turret covers
- Swarmer attacks turret cover (/obj/machinery/porta_turret_cover) and dismantles it
- The cover gets restored on the next tick
- No resources are gained

Should probably just be blacklisted, like how the turret underneath is.

### LINKED ISSUE #38282: Swarmers can destroy field generators
Reporting this as an issue since it's extremely inconsistent with what swarmers are allowed to destroy, and incongruent to the purpose of swarmers entirely. As the title says, swarmers can destroy field generators, allowing them to break singularity/tesla containment. It's worth pointing out that they can't destroy ANY part of the station's power system, and they can't make holes to space, but they can make the singularity loose. On that matter, they can also destroy the particle accelerator, but this is a lot less havoc wreaking. Seems like an oversight to me.

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
fix: Swarmers can no longer attack field generators and turret covers.
/:cl:

Fixes: #37702
Fixes: #38282

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
Seems fair enough

**Review by vuonojenmustaturska — APPROVED** [review]

**Comment by 81Denton** [comment]
obj/machinery/shieldwallgen (used in xenobio) and obj/machinery/shieldgen (anti-breach projector) should probably also be blacklisted

**Comment by chesse20** [comment]
Unesscary nerf to swarmers

**Comment by Cyprex** [comment]
This is for turret covers, the actual turrets underneath are unaffected, as such, this is a bugfix and not a balance change.

**Pull request merged**
