### PR TITLE
FlyperzZzon language

### PR DESCRIPTION
**Pull request by Militaires**
buzzity buzz buzz

:cl: Basilman
add: Added a new flyman language, access it with f
/:cl:

[why]: # Flypeople speaking a different language will increase tension and paranoia, I believe that since they're a roundstart race they also deserve their own language.

### CODE REVIEW

**Comment by Kromgar** [comment]
Oh no the flies can now plot to overthrow the people

**Comment by Militaires** [comment]
@Kromgar 

De white man spray our people for too long.

De white man be mugu now we make de suffa ne?

**Comment by QualityVan** [comment]
I demand that AIs and borgs be able to understand this language.

**Comment by coiax** [comment]
Flypeople are just mutant humans.

**Comment by Militaires** [comment]
@QualityVan refer to #26787 and #26780

**Comment by KorPhaeron** [comment]
Doesnt fit the lore sorry, they're just humans who had accidents in the teleporter

**Comment by Militaires** [comment]
@KorPhaeron but didnt u guys say plasmamen are humans who got burned in a plasma accident?

**Comment by KorPhaeron** [comment]
That is /vg/ lore I dont know if we have the same plasmaman thing for sure

**Comment by Militaires** [comment]
@KorPhaeron but also flymen already speak in buzzes and considering they're half fly shouldnt they be able to communicate with buzzing only?

**Comment by KorPhaeron** [comment]
No because it'd be terrible if you couldnt speak for the rest of the round after a tele accident

**Comment by Militaires** [comment]
and funny

**Comment by Militaires** [comment]
also it's not removing human language from flies so you can still speak as a fly GC

**Comment by KorPhaeron** [comment]
I misunderstood your use of the word only

**Comment by Militaires** [comment]
strange years.

**Comment by Cheridan** [comment]
@KorPhaeron 
>That is /vg/ lore I dont know if we have the same plasmaman thing for sure

We have as much plasmamen lore as we have lore on anything, which is none. Shortly after they got Niknak tried to force the lore that they're an alien race with this big write-up on their culture and shit but that's so utterly retarded that there would be an alien race of dickless flammable human skeletons

**Comment by Militaires** [comment]
@cheridan will u reopen this pr if i restore branch ayy lmao

**Pull request closed without merging**
