### PR TITLE
Replaces nuka cola in vendors

### PR DESCRIPTION
**Pull request by ghost**
:cl: SuicidalPickles
balance: Nuka Cola has been removed from vendors, glasses of Narsour are now being distributed in their place.
/:cl:

capture

capture2

1) be literally anybody with an ID
2) run up to a drink vendor
3) pay a measily $25
4) get access to adrenaline-like speeds via nuka cola with zero effort

it was originally $50 for nuka cola and then dropped to $25 for whatever reason, but tbh i feel like raising it any higher really won't change much.
was suggested by some nerd to replace it with narsour, didn't wanna leave the premium drink spot blank.

### CODE REVIEW

**Comment by Therapist1** [comment]
The cola isn’t as powerful as you would think. Drink too much, you’ll get fat, and after 1 minute, your vision will be so shaky you’ll see the AI absorbing honkers in maint.

**Comment by Shadowflame909** [comment]
Nar-Sour is pretty good. So I can't be too mad.

Can't we just move it to contraband though? Emag a vendor for a 50 credit drink that only comes in 1?

**Comment by RogueSteampunker** [comment]
I mean, nuka cola is one of the lesser powerful stimulants, and has some terrifying drawbacks. Not to mention the age-old "uranium is as easy to get as ever" I just don't see this change doing much rather than remove a silly speed boost with downsides and replacing it with a debatable cult buff of "the assistant is screaming narsian, must've hit up a soda machine again"

**Comment by necromanceranne** [comment]
Nar'Sour lets me prank even more so yay

Nuka Cola was kind of too good for what effectively allowed to outrun security with ease if caught. Hell, even downing one sip was enough to scoot away at meth speeds and disappear into maint without affecting your weight too much. There wasn't really any REAL threat of becoming overweight from it.

**Comment by Wilchenx** [comment]
@Therapist1 just counter the shakiness with nicotine+coffee ecig mix

**Comment by coiax** [comment]
Nar'sour is a medium level complexity drink from the Barman, and making it is a fun little treat. Giving everyone the ability to get a Nar'sour from the vending machine just lowers the value of the Bar.

**Comment by imsxz** [comment]
>alcohol in soda vendor
there are employees as young as 17 years of age on station fam thats not legal

**Comment by Tlaltecuhtli** [comment]
why not make the spawned glass have like 5u nuka 45 radium or some shit instead, if we start removing the only things worth buying then we ll go back to credits being a fluff items

**Comment by Ratvar** [comment]
Maybe vendors with food should be fluff, after all?

**Comment by anconfuzedrock** [comment]
Lmao coiax nuka cola is a high level complexity drink from thr barman, and making it is a fun little treat. Giving everyone the ability to buy nuka cola just lowers the value of the bar.
Nuka cola promotes assistants stealing ids to buy shit almost as much as it promotes assistants stealing prisoners and rocketing off to never be seen again.

**Comment by Mickyan** [comment]
what about just removing it or making it more expensive instead of replacing it with something that can fuck up the balance of an entire gamemode

**Comment by Suicidalpickles** [comment]
I just didn't wanna go for outright removal and leave the premium slot empty, but i can get behind probably just adjusting the units that nuka cola bottles have as @Tlaltecuhtli mentioned.

also nuka cola gets you up from being knocked unconscious quicker too

also >cult >balanced
lol

**Pull request closed without merging**
