### PR TITLE
Replaces sleepy pen contents with Zombie Powder.

### PR DESCRIPTION
**Pull request by Iamgoofball**
everyone agrees the sleepy pen is kinda crap right now, this should make it worth buying again.

### CODE REVIEW

**Comment by Incoming5643** [comment]
Might be too strong in the other direction, 30 units of zombie powder  is 75 ticks of utter defenselessness that starts immediately. Para C4 can't be done quite so easy these days, but that's still plenty of time to kill a guy.

**Comment by PKPenguin321** [comment]
o l d   p a r a p e n   b o y s

:+1: to this, parapen got a lot of shit in the great parapen+c4 purge but honestly it went a little overboard. they only really needed to nerf the c4 and as of now the "sleepy pen" sucks massive cock.

**Comment by PKPenguin321** [comment]
also conflicts with https://github.com/tgstation/-tg-station/pull/10142

**Comment by GunHog** [comment]
PARAPEN C4 (but not really) GG

**Comment by Fox-McCloud** [comment]
still kinda skeptical on this; it's a insta-stun that has no obvious tells---like old stungloves. Granted, it is a traitor item, and I do like the direction of there being more lethality in SS13, but I'm not sure this particular change is a good one.

Perhaps a faster acting knockout chem+removing the "you feel a tiny prick!" message?

**Comment by GunHog** [comment]
Eh, do give them a warning at least. Having a chance to defend yourself or call for help is important. Defending yourself much more so.

**Comment by PKPenguin321** [comment]
well yeah but it's the same deal with the pen, you need to get up close before you can inject someone with it and if you're trespassing they're already going to be cautious
if you're in the same job so they're not suspicious then of course you have an advantage of them not having a warning, that's why abductors can disguise as a scientist to kidnap another scientist
it's the same principal only the pen is a one use item

**Comment by PKPenguin321** [comment]
also before you say "this is way too good for murdering people, they have no chance of fighting back because they die/go unconcious too fast," remember that you can already do that with a revolver (three whole times, more if you get ammo)

**Comment by freerealestate** [comment]
You have a chance at dodging a revolver. With this, you can just stab them
and throw a minibomb at them.

**Comment by Iamgoofball** [comment]
@freerealestate 

On paper, you do.
In practice, you can't really dodge it.

Each hit from the revolver does enough damage to bring you down a speed tier. You get easier to hit the first time you're shot, and in practice the first shot usually lands because of surprise.

Unless you're high on meth and morphine 24/7 then you aren't gonna have a good chance at dodging.

**Comment by freerealestate** [comment]
True. I still don't think that's a good precedent to follow, though.

**Comment by Tokiko1** [comment]
A revolver atleast encourages the traitor to do something else in the round that makes it more fun for everyone, like assasinating another important person or printing more ammo for a rampage.

Parapens are stab, gib, sit around all round doing nothing. I agree that the current sleepypen is a rather poor item, but there should be better ways to make it a better item than reverting them to parapens. Parapen encouraged terribly boring traitors.

**Comment by Jalleo** [comment]
Make a different chem that acts like zombie powder but takes aftect after 5 seconds or so. Otherwise this change will be awful. Plus i believe zombie powder deals brain damage which is awful if you survived it and chemistry is gone.

**Comment by WJohn** [comment]
Actually now we have an even cheaper alternative: Parapen + microbomb implant. Instantly knock someone out, implant them so that they gib on death, choke em in a locker, walk away.

**Comment by Miauw62** [comment]
>instant sleep

i removed this for a reason.

**Comment by duncathan** [comment]
What ever happened to 24 hours

**Comment by Jalleo** [comment]
Some stuff dosent need 24 hours to be denied it is rare though.

**Pull request closed without merging**
