### PR TITLE
Fixes blood boil sometimes not working

### PR DESCRIPTION
**Pull request by ChangelingRain**
A loop looping once too many times....

### CODE REVIEW

**Comment by RemieRichards** [comment]
Wait, why can ghosts/nulls be in the invokers list? that sounds like the real bug here.

**Comment by ChangelingRain** [comment]
They can't be, or at least I know of absolutely no way they could be, but this is the only possible thing that could cause the bug I saw even though it makes literally 0 sense.

**Comment by RemieRichards** [comment]
Well A can't exist without B.

**Comment by ChangelingRain** [comment]
Wait, no, I found the error! Ha!

**Pull request merged**
