### PR TITLE
exodrone travel time balance, grammar, fixes and tweaks

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

a little amount of stuff
Wide scans (to discover new areas) are now capped at 10 Minutes
Point scan base time is now 2 minutes
Deep scan base time is now 3 minutes
Fixed several typos
travel time is like 18% faster
you can now upgrade scanner arrays with better scanning modules, 4 bluespace scanning modules = 2 scan power
you can now screwdriver open and deconstruct scanner arrays
examining exodrone launchers now tells you how to remove their fuel pellet

the tree in space adventure has another leave option so you cant get softlocked by having a high confusion value

also the entry log clears itself when the entry limit is reached

## Why It's Good For The Game

grammar fix good

exodrones should not be a waiting simulator, waiting 36 minutes after like 3 scans to click like 3 buttons and get likely nothing valuable in return is stupid

## Changelog
:cl:
fix: you can now deconstruct exodrone scanner arrays
fix: the tree in space exodrone adventure no longer softlocks you
qol: the exodrone launchers now tell you on examine how to remove their fuel canister if you somehow needed to do that
balance: exodrone wide scans are now capped at 10 minutes
balance: exodrone travel times are 18% faster
balance: you can now upgrade scanner arrays for faster wide scan
balance: exodrone point scan and deep scan are faster
spellcheck: fixes several typos related to exodrones and gives scanner control console a description
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
have some issues
- #66085
- #69998
- #70027

**Comment by mc-oofert** [comment]
> have some issues
> 
> * [Various issues with Exploration Drones #66085](https://github.com/tgstation/tgstation/issues/66085)
> * [Cargo Drone Exploration does not give loot #69998](https://github.com/tgstation/tgstation/issues/69998)
> * [Drone Adventure says theres no room for loot when there is #70027](https://github.com/tgstation/tgstation/issues/70027)

the latter two are irrelevant and the first one i dont think we have a space yacht event?

**Comment by Onule** [comment]
> > have some issues
> > 
> > * [Various issues with Exploration Drones #66085](https://github.com/tgstation/tgstation/issues/66085)
> > * [Cargo Drone Exploration does not give loot #69998](https://github.com/tgstation/tgstation/issues/69998)
> > * [Drone Adventure says theres no room for loot when there is #70027](https://github.com/tgstation/tgstation/issues/70027)
> 
> the latter two are irrelevant and the first one i dont think we have a space yacht event?

There is a space yacht event, yes.
I'd like to mention the syndicate drone event also doesn't give the trade contract paper/chip or whatever the reward is.

Also, just reduce the stock parts on the scanners from 4 to 1, 4 lasers and 4 scanning modules is ludicrous.

**Comment by mc-oofert** [comment]
> There is a space yacht event, yes. I'd like to mention the syndicate drone event also doesn't give the trade contract paper/chip or whatever the reward is.

i cant seem to find those adventures on my fork

**Comment by Onule** [comment]
> > There is a space yacht event, yes. I'd like to mention the syndicate drone event also doesn't give the trade contract paper/chip or whatever the reward is.
> 
> i cant seem to find those adventures on my fork

Yeah, a whole bunch of adventures were put someplace else, annoyingly so.

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
