### PR TITLE
Removes toxin from water bottles

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
del: Water bottles no longer contain toxic chemicals.
/:cl:

Taking damage from drinking bottled water is stupid.

### CODE REVIEW

**Comment by Metallusions** [comment]
But, but realism!  100% of people who drink dihydrogen monoxide will die.

**Comment by Cyberboss** [comment]
I think the real bug is that fluorine still does damage at low amounts

**Comment by octareenroon91** [comment]
> I think the real bug is that fluorine still does damage at low amounts

Yeah, it's easiest to give chems linear effects.
O(1) or O(n)

**Comment by Aloraydrel** [comment]
Should of bought a water filter

**Comment by Anonmare** [comment]
Alex Jones was right about the water!

**Comment by Iamgoofball** [comment]
It's miniscule toxloss you fucking pussies

**Comment by duncathan** [comment]
the difference between 100% health and 99% health is more significant than the difference between -100% health and 0% health

**Comment by Bawhoppen** [comment]
okay coiax what part of it being minor don't you get

even if you DID drink all 500u of water in a vending machine, it would add up to a scrawny 7.5 toxin damage

**Comment by Bawhoppen** [comment]
actually I just tested it and it's so minute that it doesn't actually do any damage it

**Comment by ExcessiveUseOfCobblestone** [comment]
nanotrasen is trying to control the population

**Comment by Iamgoofball** [comment]
@KorPhaeron can you close this PR if you're closing stupid kneejerk reverts/stupid kneejerk "if X then Y" prs

**Comment by KorPhaeron** [comment]
Only if you promise to calm down and also buy some life straws

**Comment by TechnoAlchemisto** [comment]
it's fluoride not fluorine

**Comment by KorPhaeron** [comment]
making the frickin lizards gay

**Comment by optimumtact** [comment]
I like this lol

**Pull request closed without merging**
