### PR TITLE
Filters allow air to pass through when not set to filter any gas

### LINKED ISSUE #31829: Filters stop pumping once the filter side reaches 4500KPA even if it's filtering nothing
image
image

@duncathan

### PR DESCRIPTION
**Pull request by duncathan**
Fixes #31829

:cl:
fix: Filters no longer stop passing any gas through if the filtered output is full.
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
That'd sound awesome tbh.

**Comment by duncathan** [comment]
Alright I'll do it tomorrow then

**Comment by praisenarsie** [comment]
how would this affect the sm

**Review by Cyberboss — APPROVED** [review]

**Comment by ShizCalev** [comment]
@praisenarsie It fixes it so that the filter doesn't break if you connect a full tank to the first filter.

**Comment by duncathan** [comment]
Alright, done.

**Pull request merged**
