### PR TITLE
makes screwing windows 1 second faster

### PR DESCRIPTION
**Pull request by PKPenguin321**
reasoning:
try making a window when there is any amount of spacewind

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Why does it take time at all is a better question

**Comment by duncathan** [comment]
that's fantastic reasoning

**Comment by PKPenguin321** [comment]
>Why does it take time at all is a better question

paprika did it to make windows take roughly the same amount of time to deconstruct when he made the "grille-with-four-side-windows" windows into full-tile windows

>that's fantastic reasoning

thank you

**Comment by Core0verload** [comment]
Just axe this cooldown.

**Comment by PKPenguin321** [comment]
baby steps

**Comment by Zilenan91** [comment]
nah break the baby's leg that fuckers gonna leap

**Comment by RandomMarine** [comment]
Honestly, I think the steps need reduced time.

Breaking down a reinforced window + grille with a force 10 weapon.
* Takes roughly 22 seconds.
* Requires just the one item.
* Relatively loud.
* I guess you could step on the broken glass if you're barefoot.

Deconstructing a reinforced window + grille.
* Requires screwdriver, crowbar, and wirecutters. (Wrench optional)
* Takes roughly 16 seconds. (20 if removing the window itself with wrench instead of pulling it away)
* Steps must be retried if anyone bumps into you.
* Only a bit less loud and noticeable.

I think just 3 seconds for each step is more reasonable.

**Comment by PKPenguin321** [comment]
ok ill do more stuff later in more commits later on okay

**Comment by PKPenguin321** [comment]
ok well i guess more decon speeding up will be done in a different PR
i am ok with that
ok

**Pull request merged**
