### PR TITLE
Fox 2.0

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/tgstation/-tg-station/pull/6489/

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Best PR in the history of all TG. Merge now

I'm completely unbiased on this one, trust me.

**Comment by Nienhaus** [comment]
I fixed my problem @tkdrg :p

**Comment by Spacemanspark** [comment]
Merge it in, /tg/ MUST have this.

**Comment by pudl** [comment]
the sprite is bad

**Comment by GunHog** [comment]
No support until you add Fennec Foxes, the best kind of fox: http://wildlife-photographs.blogspot.com/2013/02/Fennec-Fox.html

**Comment by Nienhaus** [comment]
@tkdrg Does this need another 24 hours?

**Comment by paprka** [comment]
faux news

**Comment by Fox-McCloud** [comment]
Congrats! Now Renault just needs added to the map.

**Comment by paprka** [comment]
Why is he not the librarian's pet though!!

**Comment by Fox-McCloud** [comment]
such a noble creature only deserves the full protection of the Captain =p

**Pull request merged**
