### PR TITLE
Updated MetaStation.v41A.II.dmm to MetaStation.v41D.dmm

### PR DESCRIPTION
**Pull request by Metacide**
**Updated MetaStation.v41A.II.dmm to MetaStation.v41D.dmm**
**Updated z2.dmm and z3.dmm**

*Updated Centcom to current version, with added gun/device 'museum' at the escape shuttle dock
*Added extra signs to help navigate between departments
*Added conveyor belt levers to the cargo shuttle
*Added two more air vents to the minisat walkways
*Added commemorative plaque to random tile which has been in deep space for some time
*Added condimaster to bartender's backroom
*Added stack of regular glass to EVA table for regular-glass repairs
*Added missing cargo tech locker to cargo bay
*Replaced all flooring in research firing range with disguised reinforced tiles
*Replaced screwdrivers in botany crate with wirecutters
*Fixed various issues with bot patrol routes
*Fixed conveyors on the cargo shuttle going to the wrong way
*Fixed virology break 'romm' typo
*Fixed emergency shuttle brig being blue and not counting as brig for antag redtext
*Fixed pipe near minisat teleporter occasioanlly resulting in teleported ventcrawlers
*Fixed broken bartender's closet
*Fixed misaligned air scrubber in the cargo bay
*Fixed camera names in experimentation lab and bar backroom
*Fixed odd ventcrawl movement at a vent near arrivals
*Moved mopficcer sweepsky the cleanbot to the center of the station, starting on auto-patrol
*Removed duplicate TV screens in the library private study rooms

I've partially updated the wiki based on a semi-finished previous version of this update which I had to remake. I'll get around to properly updating everything in due course, but for now these images are largely accurate:

Station Map:
https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-06-28%2020-36%20MetaStation.v41C%20Full.png

Engineering Map:
https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-06-28%2020-36%20MetaStation.v41C%20Engineering.png

### CODE REVIEW

**Comment by Metacide** [comment]
Just doing some last tests now.

**Comment by WJohn** [comment]
Holy shit a metastation update after all this time?

Today is a good day.

**Comment by Dorsisdwarf** [comment]
So is the north, tiny belt still the one which leads into the cargo shuttle? because that always annoyed me.

**Comment by Metacide** [comment]
It is. I might switch back to how it used to be with the update after this, though.

**Comment by Metacide** [comment]
Ok, all seems fine on those last checks. Ready to go whenever you folks are.

**Comment by Metacide** [comment]
Oh dear, found a bad issue - the emergency shuttle destroys itself in travel. Fixing that now...

**Comment by Metacide** [comment]
Hmm, interesting. Don't think this can be different from current MetaStation, though, but I'll take a look.

**Comment by Metacide** [comment]
Made a new request here: https://github.com/tgstation/-tg-station/pull/10671

**Pull request closed without merging**
