### PR TITLE
Esword Embedding 

### PR DESCRIPTION
**Pull request by MMMiracles**
If you're crazy enough to spend over a 1/3rd of your TC on a valid stick you might as well be able to throw it at people for added effect.

Compared to an energy dagger, it does 47 brute on an unarmored target with a 100% embed chance. Energy swords after this change do 60 brute on an unarmored target with a 75% embed chance.

### CODE REVIEW

**Comment by Zilenan91** [comment]
If you throw it can you add a power that makes it come back to you because there needs to be a reason to buy this now that parasites are a thing.

**Comment by Anonus** [comment]
That's called TK, you can stab them with the newly embedded esword.

**Comment by Robustin** [comment]
I actually really like that idea of this change + including the "recall" spell automatically bound to the sword (blah blah Bluespace Nano Quantum Dimensional Sciencey tech lets you teleport the sword back to your hand) or double e-sword.

You could actually use the swords without worrying about losing them to the first disarm that lands on you.

**Comment by MMMiracles** [comment]
Eh, I might look into how the ninja sword recalling works for this but this pr is for embedding.

**Comment by Razharas** [comment]
So it embeds despite being off?

**Comment by Razharas** [comment]
@MMMiracles

**Comment by MMMiracles** [comment]
In the combat.dm, theres a throw speed threshold an item has to be at or higher to actually embed, which is 4.

The esword gets a throwspeed of 4 when enabled and goes back to the default 3, so it shouldn't be embedding when off, unless I managed to read the comment on the embed threshold really wrong.

**Pull request merged**
