### PR TITLE
Allows mechas to turn in strafe mode if the user holds Alt

### PR DESCRIPTION
**Pull request by zxaber**
:cl: Zxaber
add: Mechas now ignore strafe mode and turn if the user is holding Alt.
/:cl:

QoL change, clicking the strafe button gets tedious. Actually, I just found out you can Alt-click the mech itself to toggle, but this seems like it would be nicer.

### CODE REVIEW

**Comment by necromanceranne** [comment]
Gygax Drifting incoming.

**Comment by HomocidlePancakes** [comment]
Why hold? Why not have it toggle on key pressed? Not necessearly alt.

**Comment by OverlyGeneric** [comment]
> Why hold? Why not have it toggle on key pressed? Not necessearly alt.

https://www.youtube.com/watch?v=_k_5G5QcmPM

**Comment by zxaber** [comment]
Because generally, you don't need to turn that much back-to-back to justify it being an toggle hotkey. Like when mining, you might do a horizontal cut below a bunch of ore, and then quick-rotate north-facing to just mow down the rock while moving to the side.

**Comment by optimumtact** [comment]
why only on walk intent?

**Comment by zxaber** [comment]
If you are on run intent, holding Alt puts you into walk intent until you let go of Alt. It's a handy hotkey for walking temporarily.

By checking for walk intent, I can allow users to use Alt as a hotkey to temporarily disable strafe mode to make a turn. Strafe mode is re-enabled when the user lets go of Alt.

**Comment by Tlaltecuhtli** [comment]
what happens if you use alt click on mech? does it go off (pressed alt) and on ( alt click)?

**Comment by zxaber** [comment]
Alt-clicking toggles the mech normally and this PR does not affect that.

Fundamentally, all that is going on is that when the game is deciding whether the mech moves or turns, it checks if strafe mode is enabled. At the same time, if the driver is set to walk mode, it ignores the strafe setting (whatever it may be set to) and turns anyway.

**Review by ShizCalev — DISMISSED** [review]

**Review by ShizCalev — CHANGES_REQUESTED** [review]

**Review by ShizCalev — APPROVED** [review]

**Comment by kopoba** [comment]
Why alt and not Ctrl? Ctrl seems to more reasonable choice since you can hold it by little finger when you control mech with arrows and wasd. But with alt you cant use arrows that simple. Seems like PR for only wasd users =(

**Comment by zxaber** [comment]
Man, had you said something before the merge, I could have made it work for both.

Originally, I had used the walk hotkey (which is Alt) because I was checking for the pilot being in walk mode and not by the key itself being held. Eventually, I found out there is a list of keys that the client is holding (hence then "made it less fucky" commit) and just used Alt because that's what I had prior and it worked.

**Comment by optimumtact** [comment]
lmao this guy doesn't use hot keys

**Pull request merged**
