### PR TITLE
Removes the visible messages from crossing vitality matrices

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: Vitality matrices don't have visible messages when someone crosses them anymore.
/:cl:

My client crashed while I was observing because the chat box was being flooded with messages so quickly, which is rather silly, so this removes that.

### CODE REVIEW

**Comment by Buggy123** [comment]
The comforting sigil begins to glow bright blue!
The comforting sigil begins to glow bright blue!

**Comment by Xhuis** [comment]
***
The comforting sigil begins to glow bright blue!

**Comment by Potato-Masher** [comment]
Couldn't hardly watch the battle from that round due to the lag. 

The comforting sigil begins to glow bright blue!

(Also, props to the cultist that managed to find, subdue, and convert a Nightmare into the cult.)

**Comment by Potato-Masher** [comment]
Although, I think it would still be okay to keep a message when you use a non cultist on it and disintegrate them.

**Comment by imsxz** [comment]
Outside of the scope of this PR but vitality spam may want to be looked at. I was in the cult of the round that spawned this pull request and they literally could not kill us, every time we'd get shot to death we'd just get revived right away because there was always a healing rune under us. Sure it takes vitality to heal, but we had around 6k of it.

Making them need to be spread out like wardens would be a pretty solid change for this.

**Comment by imsxz** [comment]
Outside of the scope of this PR but vitality spam may want to be looked at. I was in the cult of the round that spawned this pull request and they literally could not kill us, every time we'd get shot to death we'd just get revived right away because there was always a healing rune under us. Sure it takes vitality to heal, but we had around 6k of it.

Making them need to be spread out like wardens would be a pretty solid change for this.

**Comment by Xhuis** [comment]
I agree for sure. After this PR, I'll probably take another balancing pass.

**Pull request merged**
