### PR TITLE
Revert "Fixes mounted chainsaw deletion"

### PR DESCRIPTION
**Pull request by PKPenguin321**
Reverts tgstation/-tg-station#13836

Fixes https://github.com/tgstation/-tg-station/issues/14020

Reopens https://github.com/tgstation/-tg-station/issues/13092

### CODE REVIEW

**Comment by PKPenguin321** [comment]
haven't actually tested if this fixes it but all evidence of it being broken points to kor's PR so i'm pretty confident in this

**Comment by KorPhaeron** [comment]
Fuck

**Comment by KorPhaeron** [comment]
Wait why does my change not work let me look at the surgery code

**Comment by PKPenguin321** [comment]
i think it's because the putinhands() proc fails if the target is lying down/stunned, so if you're lying on the surgery table it drops the chainsaw. before it worked because the chainsaw had the ABSTRACT flag, so it ignored if you were lying down or something I guess.

**Comment by KorPhaeron** [comment]
Gonna try and figure this out so that the surgery/fix both works

**Comment by PKPenguin321** [comment]
have you tried keeping the ABSTRACT flag but also having the /dropped() at the same time?

**Comment by KorPhaeron** [comment]
No, that is what I'm about to do

**Comment by PKPenguin321** [comment]
pls test it

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/-tg-station/pull/14032 is a better fix

**Pull request closed without merging**
