### PR TITLE
New blackbox sprites

### PR DESCRIPTION
**Pull request by Lexorion**
## Replaces the blackbox sprite with new one [made it less fragile this time]
**Left**: Old one, forgot to take it out of #28285 with the rest of telecomm since it's in a different file (Sorry!)
**Right**: New sprite

**Important**: the gif doesn't loop properly, the sprite does though.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Its called a before and after, not after and before =P

**Comment by Lexorion** [comment]
Heh, my bad!

**Comment by WJohn** [comment]
While generally nice, I think it's kind of flat. The original sprite has indentations in it, and a bigger top half than the bottom. The new one is just one big rectangle that doesn't really jut out visibly. Try adding more bumps and grooves and dimension to it.

**Comment by MrStonedOne** [comment]
Its a black box, not a tape recorder.

The recording mechanism and tape wouldn't be on the outside, visible, unprotected, as that would make it easy to damage. A blackbox is suppose to survive destruction of the station.

While we can handwave some of that away with "bluespace" going this far in the fragile direction is bound to be immersion breaking

**Comment by Supermichael777** [comment]
yuck

**Comment by BeeSting12** [comment]
i kinda like the old one better.

**Review by Cyberboss — APPROVED** [review]

**Comment by GunHog** [comment]
The old one looks better, in my opinion. Like MSO said, a black-box recorder should look tanky and protected!

**Comment by Lexorion** [comment]
Im changing it right now, the picture is outdated but I'm not done yet. New one will be far less fragile and more like the older ones

**Comment by ExcessiveUseOfCobblestone** [comment]
The old one fits with the rest of the tcomms machinery unless they too were recently changed.

**Comment by Lexorion** [comment]
I change the [entire tcomm machinery ](https://github.com/tgstation/tgstation/pull/29943) except this one so it doesn't really fit anymore

**Comment by ExcessiveUseOfCobblestone** [comment]
has lexorion ever done something not good wtf

**Comment by BeeSting12** [comment]
the old one's better than this one but this one can still be improved.

**Comment by Lexorion** [comment]
I'll update this soon ™️

**Comment by AnturK** [comment]
So i guess this isn't finished yet ?

**Comment by tortellinitony** [comment]
I don't like this perspective of sprite, but I must admit the one on the left looks good. This one is fuck ugly

**Comment by Lexorion** [comment]
I already said I'd change it, the picture is outdated and the OP states it, why are people disliking it anyway? I'll just reopen this once I have the time to finish it!

**Comment by Lexorion** [comment]
new sprite

**Comment by GunHog** [comment]
I am...okay with this.

**Comment by ChangelingRain** [comment]
Doesn't really fit the existing machines, tbh.

**Comment by Lexorion** [comment]
Why doesn't it fit? The current blackbox is far too bright and sticks out since I changed [all the other sprites here](https://github.com/tgstation/tgstation/pull/29943)

This is how it looks like at the moment without my PR.

**Comment by MrStonedOne** [comment]
Its easy to varedit an icon. you should include a picture showing the tcoms rooms with both new and old sprites in the same picture.

**Comment by optimumtact** [comment]
it looks okay to me

**Pull request merged**
