### PR TITLE
changes all uses of ammo_casing/BB to loaded_projectile because its a stupid fucking var name seriously BB what is it a blood brother REEEEEEEEEEEEEEEE

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
BB is dumb this gets rid of BB and replaces it with loaded_projectile because thats an actually descriptive name that tells people what it represents, i tested 30 or so guns they all seemed to work correctly and i checked each file before replacing. theres still two files that use BB but its another thing in another context so i guess the menace lives on

## Why It's Good For The Game
i dont know what BB stands for and its used everywhere
hm yes today i shall name the projectile used by this ammo_casing BB because that is clearly a sensible name <- a statement dreamed up by the utterly deranged

## Changelog
:cl:
code: there are no longer BB's inside your guns, whatever that means
/:cl:

### CODE REVIEW

**Comment by TJatPBnJ** [comment]
it's a bb, i think its pretty clear

**Comment by cacogen** [comment]
Yeah I thought similarly years ago looking at this and wondering what the fuck this code even was. It's like Mads Mikkelsen staring at you through a piss filter

**Comment by LemonInTheDark** [comment]
kyler, it doesn't compile

**Comment by Kylerace** [comment]
> 
> 
> kyler, it doesn't compile

it worked on my machine (last night).
uno momento

**Comment by Kylerace** [comment]
this pr might be being visited by the same mysterious oom crashing fairy that almost made me quit working on map template holodeck, one moment

**Comment by Kylerace** [comment]
alright nuked the branch and redid the changes twice and somehow its ok now after ten tries and no crashing

**Pull request closed without merging**
