### PR TITLE
Rejecting an adminhelp no longer returns the verb to the person

### PR DESCRIPTION
**Pull request by lzimann**

### CODE REVIEW

**Comment by optimumtact** [comment]
I'm not sure I agree with this

**Comment by MrStonedOne** [comment]
The entire point of this button is to return the verb.

hell, the ENTIRE reason i even wrote the timer subsystem was so i could do returning the verb in way that wouldn't lead to issues.

**Comment by lollerderby** [comment]
the only adminhelps worth rejecting are trash meme ones, and getting the verb back usually just gives an opportunity for them to send you a second trash meme immediately

most of the time if someone adminhelps something useless like "was that valid" you're just better off asking them to clarify what they're talking about in a reply anyway

**Comment by Anonmare** [comment]
If I don't want to reply to them I just won't reply to them

**Comment by ShadowDeath6** [comment]
>meme ahelp at the beginning of the round
have a legitimate ahelp later
cry for eternity as you realize you lost your ahelp verb

don't you just, like, ban them if they spam ahelps?

**Comment by lzimann** [comment]
@ShadowDeath6 The ahelp verb returns after a few minutes.

**Comment by anconfuzedrock** [comment]
even if it didn't return after a few minutes pray exists and if its really bad you may be able to whine in deadchat or somebody else is already ahelping it

**Comment by MrStonedOne** [comment]
the entire point of this button, is when somebody accidentally hits enter while typing an admin help, so they can put the rest in

prey is not filtered from the public logs and i don't want it to be.

**Comment by ExcessiveUseOfCobblestone** [comment]
why not just separate return and reject?

**Comment by Cyberboss** [comment]
^ I never understood why they were the same thing

**Comment by MrStonedOne** [comment]
Well you could go look at the pr that added them to find out.

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/tgstation/pull/10083

**Comment by MrStonedOne** [comment]
>the only adminhelps worth rejecting are trash meme ones, and getting the verb back usually just gives an opportunity for them to send you a second trash meme immediately

New policy, ban people from adminhelp for making those

**Comment by optimumtact** [comment]
Yeah I really don't see why this is required, you have plenty of tools to deal with people who meme on ahelps

**Pull request closed without merging**
