### PR TITLE
Changes the cost of holoparasites in the traitor uplink from 18 TC to 15 TC.

### PR DESCRIPTION
**Pull request by Borisvanmemes**
Baby's first PR.

:cl: borisvanmemes
balance: Holoparasites now cost 15 TC, down from 18.
/:cl:

[why]: I've always felt like they costed just a bit too much, just a bit.

### CODE REVIEW

**Comment by Eskjjlj** [comment]
Holoparas sure are expensive and they dont provide much benefits unless you rolled Imsxz as a holopara.

**Comment by nicbn** [comment]
Usage of holoparas shouldn't be incentivized, they only encourage murderbone and disencourage harder and more interesting strategies.

Stands may be fun when used once in a while, but they'll get repetitive and boring real quick if they start to appear more often

**Comment by subject217** [comment]
This doesn't change the fact that holoparas are hit or miss. It's just power creep.

**Comment by anconfuzedrock** [comment]
Holoparas were once 12 tc, it was changed for a reason. holoparasites are the most powerful get out of jail free card, along with their unsurpassed utility in one of many fields- the healing one is the envy of the entire medbay AND is an excellent teleporter, for one. Wizards aren't allowed to use healing paras, they're so good. 
Holoparas are also the most frustrating thing to fight in a combat system that so severely supports using stun based weaponry that only really works on humans, while holos can only be hurt with brute force- a regular sec officer is less equipped to fight a holopara than an engineer with a welding tool. adrenals and freedom implants only work so often, but a healing para can sax you out of anything. They really don't need a buff of any fucking form. I didn't even mention explosive paras (THERE'S A REASON WE REMOVED DOOR CHARGES)

**Comment by necromanceranne** [comment]
The problem with holoparasites is that many of them are cheese monsters (explosive and lockers), utterly useless in some or most scenarios (explosive para in any other situation, assassin and it's lackluster impact to a kill, lightning), or highly situational (chaos). The ones that ARE good are support and standard for both being very good in a good variety of combat scenarios and standard just being durable and high damage, allowing it to always contribute in a fight without much threat to the user.

Most holoparasites are so shit at actually fighting. While the holoparasite can't be stunned, the user certainly can, and people who know this can abuse it.

At 15 TC we might see a greater quantity of the better holos because they're safe and reliable and no longer as great a all-or-nothing holoparasites were at 18 TC. You now can get a good variety of equipment for what you need, like no-slips, edaggers and emp kits. EMP kit with holoparasite is already a well known powerful combination that just got way stronger.

**Comment by Potato-Masher** [comment]
Hm... you know, the problem keeps circling back to how the Holoparasite's core design sucks at the moment.

I'd like to do a rework of them to be more fun for everybody involved, but that's only gonna happen when I actually get off my lazy ass and do it.

**Comment by subject217** [comment]
goof had an interesting idea for it albeit somewhat flawed. the PR is totally nuked now though.

also this is basically bike shed: the PR, as the change is very minor and not borne out of any genuine need. so there's no point in arguing here.

**Comment by ExcessiveUseOfCobblestone** [comment]
`/datum/uplink_item/stealthy_tools/stimpack`
`/datum/uplink_item/implants/freedom`

`cost = 5`

lovely...

**Comment by ninjanomnom** [comment]
I don't feel like this change is necessary and holoparasites seem to be in a good spot as far as popularity of choice goes.

**Pull request closed without merging**
