### PR TITLE
Removes some unused sprite files

### PR DESCRIPTION
**Pull request by ACCount12**
Removes two files:
`biomass.dmi` - not related to blob or biomass generator, the only icon used was `rift`. It's moved to `effects.dmi`.
`tubing.dmi` - unused, and the sprites themselves are pretty bad.
`large.dmi` - large pipe sprites, unused.
`virology.dmi` - Baystation virology sprites, unused. Apparently someone planned to port it some time ago.

### CODE REVIEW

**Comment by ShizCalev** [comment]
Old school piping or something?

**Comment by ACCount12** [comment]
Something from the times when porting pipenets to powernet-like construction system (see: BS12 "flexible tubing") was planned.

**Comment by SpaceManiac** [comment]
`icons/obj/atmospherics/pipes/large.dmi` is also unused.

**Comment by ACCount12** [comment]
I might remove it too, but it looks like it's a part of old planned system for refueling shuttles. I want to make something like that work.

**Comment by optimumtact** [comment]
well it's not like it becomes irretrievable, so you should still do it

**Comment by ACCount12** [comment]
Two more unused files are out, including `large.dmi`.

**Pull request merged**
