### PR TITLE
Fixes the crisis of the wand of emergency engine ignition breaking keyfabe

### LINKED ISSUE #11861: Wand of engine ignition consistency
In the wizard den/shuttle, there's a wand for emergency engine ignition at the south end that has a consistency issue.

On examine:
"That's a wand of emergency engine ignition.
Used in emergency's to reignite magma engines. This one appears spent.
It is a small item.
It has the magic crystal shard installed.
Has 100 charges remaining."

The description says it's spent yet it has 100 charges. Not urgent but a tad immersion breaking.

Server revision compiled on: 2015-09-17
a48254f31a0c0b1a552b40fa8c5d7f6372a2ed90

### PR DESCRIPTION
**Pull request by Incoming5643**
Also fixes the Byond Random Number Generator joke structure, who's icon has been missing for like... a year.

Fixes #11861

Magic Mania 1.995282

### CODE REVIEW

**Comment by Incoming5643** [comment]
Don't ask me why the structure of generic/z2 change so bad, I've seen it happen to other maps too and all I can say is that it seems to survive ok without all those lines somehow.

**Comment by WJohn** [comment]
Z2 hasn't been converted back yet so there'll be huge line changes this time.

**Comment by CosmicScientist** [comment]
:+1:

**Comment by Incoming5643** [comment]
Just as a warning if this get merge conflicted I'm gonna have a really hard time giving enough of a fuck to redo these changes

**Pull request merged**
