### PR TITLE
adding the compressed matter cartridge to the engineering protolathe

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request

All it does is add the compressed matter cartridge to the engineering protolathe. It's a super minor change but helps a lot for making stuff like meteorshot techshells.

## Why It's Good For The Game
It just makes too much sense plus engineering just can't make matter cartridges without an autolathe which seems very weird.

## Changelog
:cl:
tweak: added compressed matter cartridges to the engineering protolathe options
tweak: added the matter cartridge to the advanced engineering tech node
/:cl:

### CODE REVIEW

**Comment by FloranOtten** [comment]
Why have this in the Engi protolathe? Just for fluff? I doubt it'll be Engineering making meteor shot shells. Maybe RnD would fit better?

**Comment by daklj** [comment]
looking at the numbers it seems like putting raw metal/glass into an rcd is more effective than using these

might be a good chance to tweak it

**Comment by FloranOtten** [comment]
> looking at the numbers it seems like putting raw metal/glass into an rcd is more effective than using these
> might be a good chance to tweak it

I agree. You could always tell a new engineer from them loading the RCD with cartridges. It's slower, less efficient and generally annoying.

**Comment by Barhandar** [comment]
They can build an autolathe. And usually do because RCDs.

**Comment by SpaceManiac** [comment]
It doesn't seem that unreasonable to ask the engineers to build an autolathe, given that they are specifically empowered to do so.

**Comment by Akrilla** [comment]
Why is something craftable from the autolathe an advanced tech node? This change feels a bit redundant.

**Comment by Tlaltecuhtli** [comment]
> Why is something craftable from the autolathe an advanced tech node? This change feels a bit redundant.

half of the items in techwebs already exist in game, but this one should be put in the starter tech nodes

**Review by 81Denton — CHANGES_REQUESTED** [review]
Move this to the regular engineering node instead and it's good to merge

**Comment by YakumoChen** [comment]
Feels like powercreep tbh, might as well put RCDs themselves and .357 bullets in protolathes to remove most reasons to use an autolathe in the first place

**Comment by 81Denton** [comment]
It's hardly powercreep and makes sense to give the engineering department ammo for their roundstart engineering tool. I mean, sec can print shotgun ammo and .38 from the sec lathe as well. 

@spessbro PR was closed because it's stale, ping me or another maintainer if you want to make the requested changes.

**Pull request closed without merging**
