### PR TITLE
Fixes and improvements to nuke op area & shuttle

### LINKED ISSUE #6789: Someone broke the nuke op equipment room [map]
ss 2015-01-03 at 08 49 35

Sigh

### PR DESCRIPTION
**Pull request by ghost**
I had a PR for this before the subsystem rewrite and it conflicted. This version does not conflict.

picshur

(Image taken with Dream Maker, may be bad quality)
NOTE: Some elements may be missing from picture. This is because the images were taken on a test server that was running on extended, not nuclear emergency.

Issues fixed:
-Tables on the shuttle blocked access to some tools
-There is no wooden table holding the rum or drinking glasses
-Half of the double-airlock to the lockers is blocked (Fixes #6789)
-There are two teleporters

Changes:
-The locker room's layout has been changed slightly (necessary for fix)

~~Was a bit on the fence about having the sixth locker in the locker room but I honestly didn't see the point of it being in the cockpit of the shuttle.~~

_This has been tested and confirmed to work. Transitions do not have a problem._

### CODE REVIEW

**Comment by tkdrg** [comment]
I still think there is no point in having the sixth locker next to the rest. Pap's rationale for adding it was exactly because it was a backup that would be available even after departing from the base. It's useful if someone accidentally c4's the locker room or forgets to get dressed up or whatever.

**Comment by Xhuis** [comment]
That _does_ actually make sense. Let me put it back.

**Comment by vista-** [comment]
What's up with the second teleporter thingy?

**Comment by Xhuis** [comment]
No idea. It was there normally.

**Comment by Anonus** [comment]
It shouldn't be there, that looks like it got cloned somehow.

**Comment by Xhuis** [comment]
I'll remove it.

**Comment by Jordie0608** [comment]
Changelog

**Comment by Xhuis** [comment]
I had to ignore the warning in changelog.html because I didn't know any other way and it was the only way updating it would work.

**Comment by tkdrg** [comment]
You aren't actually supposed to run the python script. Just drop the .yml file there and wait until a maintainer updates the changelog.

**Comment by Xhuis** [comment]
Done, and I squashed the commits since the log was getting a bit long.

**Comment by paprka** [comment]
Uh the tech room with the teleporter is 1 tile too wide

Look at the thrusters, each room has 3 but that one has 4 when it shouldn't

**Comment by tkdrg** [comment]
Did you remember to shorten the docking areas on each of the syndicate shuttle docking ports as well?

**Comment by Xhuis** [comment]
Noooope. Let me do that now.

**Comment by Xhuis** [comment]
Just finished. Tested and confirmed to work correctly with all areas.

**Comment by Jalleo** [comment]
#6789

**Comment by Carn** [comment]
You've removed the z3 dock? :(

**Comment by Carn** [comment]
Oh nevermind, it's github diffviewer being dumb.

**Comment by Miauw62** [comment]
you'll have to resolve conflicts.

**Comment by Xhuis** [comment]
Conflicts? On my end GitHub says there is none.

**Comment by Miauw62** [comment]
It says that it can't be automerged here, so...

**Comment by Steelpoint** [comment]
I fixed this in my ERT PR.

**Comment by Xhuis** [comment]
All right - in that case, there's no reason to fix what's already been fixed.

**Pull request closed without merging**
