### PR TITLE
Moving the light bulb removal function from the left mouse button to the right one & add screen tips

### PR DESCRIPTION
**Pull request by paganiy**
## About The Pull Request
Press RMB to remove light bulb
## Why It's Good For The Game
No, game, I don't want to get burn myself by a light bulb that the mapper has placed right on the same tile as the machine I want to use. Please.
## Changelog
:cl:
qol: Moving the light bulb removal function from the left mouse button to the right one.
qol: Added & improved tips related to the light fixture
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
Don't forget to change context tips

**Comment by paganiy** [comment]
> Don't forget to change context tips

I'm afraid it just doesn't exist

**Comment by Sadboysuss** [comment]
Odd

**Comment by MrMelbert** [comment]
Definitely need to add screentips ifyou're changing it

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
