### PR TITLE
Play stupid games, win fabulous prizes

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request
Disclaimer: I stole this idea from @imsxz.
This PR adds an amputation arcade subtype that dispenses christmas presents instead of arcade prizes. Kind of like an Ancap christmas tree.

## Why It's Good For The Game
This lets admins replace the christmas tree with a messed up alternative if they're feeling like being assholes.

## Changelog
:cl: Denton
add: Added an (admin only) amputation arcade subtype that dispenses wrapped gifts instead of arcade prizes.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Would be better to jus allow easy var edits of what prize is dispensed, would it not?

**Comment by 81Denton** [comment]
Yeah, this is just a quick edit so admins can spawn it in without having to varedit the arcade

**Comment by Tlaltecuhtli** [comment]
can we have a brazilian version where it steals a random organ

**Comment by Michael-Ashfield** [comment]
I can already hear doctors groaning as 20 assistants run in demanding ligament hook surgery so they can game the hell out of this.

**Comment by 81Denton** [comment]
@Tlaltecuhtli I thought that was the Chinese version

**Comment by Tlaltecuhtli** [comment]
the chinese one doesnt give prizes and when you decon it a starving chinaman comes out

**Comment by 81Denton** [comment]
@Michael-Ashfield The machine destroys any chopped off arms, but I guess you could do that with the organ grower or possibly even prosthetics.

**Comment by Dorsisdwarf** [comment]
Wasnt the admin event version of this literally a christmas tree that ate your hand if you grabbed a present from under it

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
