### PR TITLE
Wait what's this PR wait nonoNONONO

### PR DESCRIPTION
**Pull request by RigglePrime**
THEY'RE DOING IT AGAIN RUN

### CODE REVIEW

**Comment by Kubisopplay** [comment]
How can they keep doing this

**Comment by RigglePrime** [comment]
Guh, I really destroyed the commit history with that one rebase...

**Comment by Wallemations** [comment]
Over 100 commits

**Comment by RigglePrime** [comment]
Shush, I forgot to fetch upstream before doing a rebase and it did this

**Pull request closed without merging**
