### PR TITLE
Increases the GBP value of code improvement PRs to 3

### PR DESCRIPTION
**Pull request by BootlegBow**
## About The Pull Request

Title

## Why It's Good For The Game

People who actively try to improve the readability of the code or update old code to follow new code standards should be rewarded a bit better than just 2

### CODE REVIEW

**Comment by BootlegBow** [comment]
fuck

**Comment by optimumtact** [comment]
we're not interested in anyone but maintainers changing this file anyway

**Comment by maxymax13** [comment]
making a gbp value change pr should deduct 20 gbp

**Comment by BootlegBow** [comment]
i'm going to brazil

**Comment by optimumtact** [comment]
* bazil

**Comment by interestingusernam3** [comment]
Epic asterisk fail

**Pull request closed without merging**
