### PR TITLE
Re-adds kekchems

### PR DESCRIPTION
**Pull request by Iamgoofball**
Wanted to save this for #10000, but eh, too long of a wait.

requested by literally everyone ever

no recipes atm while I find ones that don't clash/rewrite some recipes

### CODE REVIEW

**Comment by kyrahabattoir** [comment]
Please add overdose to every reagen!

**Comment by FriikkiM** [comment]
Add Overdose to every goddamn chem, please. Nothing should be as safe as old tricord / DD was to spam.

**Comment by Steelpoint** [comment]
It only took seven months for the message to sink in.

Also Goon or TG spamming medication has always been prevalent, the simple addition of the overdose mechanic at the higher levels is more than sufficient.

**Comment by daman997** [comment]
SPAM TRICORD FOR DAYS :+1:

**Comment by Xhuis** [comment]
Yeah, overdose is good for all the easy chems. A good tradeoff - potency for risk. Also, tricordrazine originally had an 80% chance to heal the damage types instead of just a 100% one, so I think tricord should get that to make omnizine better (or just give tricord a debilitating overdose).

**Comment by Iamgoofball** [comment]
@Xhuis it does have the 80% chance tho

**Comment by Xhuis** [comment]
all right
thanks
and thanks

**Comment by quaggaman555555** [comment]
OH THANK GOD YES PLEASE

**Comment by PKPenguin321** [comment]
:pray: :us: :star:  ;-;7 IT'S FINALLY HAPPENING ;-;7 :star: :us: :pray:

**Comment by Mandurrrh** [comment]
YES

**Comment by Mandurrrh** [comment]
Can you put tri cord back in poppies??

**Comment by Iamgoofball** [comment]
i guess

**Comment by SconesC** [comment]
so will there be any real reason to use one over the other and chemistry will just be flooded with redundant chemicals?

**Comment by Iamgoofball** [comment]
@SconesC people demanded the old chems back so here u go

the new chems stay

the old chems are weaker then the new chems but they're wanted anyways

so they can have them

just use the new chems if you want, and use the old chems if you want

**Comment by SconesC** [comment]
so yes

we will literally have redundant chemicals? as in 2 different things that do the exact same thing?

w/e i guess we can just use them to avoid ODs

**Comment by Iamgoofball** [comment]
i'm adding ODs to them after popular request so

anyways don't complain about redundancy, because you guys demanded these back and I'm not removing the others to compensate

**Comment by Steelpoint** [comment]
Honestly it needs to be one or the other, there's no good reason to flood the game with two entirely different chemical systems.

Just saying "but one of the systems is weaker" is not good enough.

**Comment by duncathan** [comment]
Do you guys not realize that the different chems play a different role? Goon shit is for first aid/medbay lobby healing and is more potent; trek shit is for anything to do with injections - food, medibots/mediborgs, hypospray, sleeper...
It's not redundant.

**Comment by Iamgoofball** [comment]
^^^^ this

Steelpoint, just don't use goonchems if you do not want to, you have an option now.

**Comment by Steelpoint** [comment]
But why do we need two different systems when we can simply add more chemicals that follow the theme of one chemical system that accomplishes what it cannot do currently.

So either more Trek Chemicals that are effective in first aid (Which to be frank it used to be very effective for that) or more Goon Chemicals that are effective in injections.

**Comment by Iamgoofball** [comment]
We end with the same result either way, steelpoint. If I renamed the chems and advertised them as an injection friendly set of chems for goonchem would you be going off about this?

They can mesh together. It works.

**Comment by duncathan** [comment]
What's the difference between a goonchem and a trekchem anyway? Recipe and name. Explain a fundamental mechanical difference between them  The systems aren't mutually exclusive.

**Comment by Steelpoint** [comment]
I should not have to explain the mechanical differences in how Trek chems are made versus how Goon chems are made in game, they both take different methods to produce and (arguably) goon chemicals involve a longer step by step process in its creations.

Overall if you want to expend more time trying to mesh together two systems and balance them out then that's your time sink, I'm suggesting we simply stick with one system (In this case Trek Chem) and balance out from there with the addition of OD.

**Comment by Man-Shroom** [comment]
y'all sum gay niggaz

other servers can have trek and goofchems together so can we
:8ball:

**Comment by Iamgoofball** [comment]
So, just mixing different chemicals is the only reason it's a "completely different system"? No other reasons?

**Comment by PKPenguin321** [comment]
steelpoint pls go
this is a good change, these are good chems, this is good in the long run
who gives a shit if it's not consistent with the rest of the chems, they're not supposed to be

**Comment by Iamgoofball** [comment]
The only thing consistent will be they get ODs, by popular demand. That's about it, though.

**Comment by ike709** [comment]
steelpoint please shush/10 :+1:

**Comment by Dorsisdwarf** [comment]
I will end goofball and all he stands f-
damnit he really did put them back
:+1:

**Comment by pudl** [comment]
tbh: put the chems in their own file, make which chem system the round uses a config option: trek, goon, or both.

**Comment by WJohn** [comment]
Oh my god.

**Comment by Kelenius** [comment]
So how exactly are you supposed to make this shit?

**Comment by pudl** [comment]
@Kelenius im gonna tell the truth and say that im sure everyone here is completely sick of your smug and completely retarded comments on just about everything goof does. how about we all start bringing up your abortion of a chem overhaul you tried to put on bay? you dont even contribute here or play anymore, so please go back to wherever idiots like you shit around nowadays.
or, ignore everything i said and just read the fucking op and you and i can be chill

**Comment by Kelenius** [comment]
I am just wondering why you would need to re-add them if you're going to change their recipe.

I mean, I thought that the whole point of re-adding them is people who just want to make old stuff.

This makes no sense.

**Comment by pudl** [comment]
that's the most retarded assumption i've heard in my entire life.
you think that people will genuinely be upset or have their trekchem nostalgia ruined over the fact that the recipes are minorly changed in order to prevent conflicts? the recipes they had BEFORE they were removed had already gone under constant change in order to prevent conflict, this is no different. jesus christ.

**Comment by Iamgoofball** [comment]
@pudl Holy shit calm down. He was pointing out that there's no recipes.

@Kelenius I'm currently working out recipes. I'll be putting them in mediborgs and shit, along with botany plants again.

**Comment by PKPenguin321** [comment]
@Kelenius nobody that plays the game cares
@pudl stop caring so much

conflict: resolved

**Comment by kyrahabattoir** [comment]
Personally i think it's stupid, the only thing really needed is something medibot friendly (and expensive to produce obviously).

**Comment by Iamgoofball** [comment]
I was gonna put these in medibots and shit

**Comment by GunHog** [comment]
Please do give them to medibots and medical cyborgs, they are currently impotent - combined with the bleeding mechanic, medibots are no longer suitable for things such as after surgery healing or Experimentor disasters.

**Comment by Iamgoofball** [comment]
Inaprov. didn't get an OD because it doesn't really need one, all it does is reduce losebreath

Medibots don't inject more than 15u ever, and mediborgs with tricord really just need to inject once and call it good. The healing from the single injection should be good enough, really.

**Comment by Kelenius** [comment]
What about three medbots injecting at the same time?

**Comment by Iamgoofball** [comment]
@Kelenius don't cluster your medibots, it doesn't heal any faster. Spread them out, cover more area. It'll treat more patients.

**Comment by GunHog** [comment]
Medibots are coded to not inject a patient multiple times, so they are overdose safe unless a cluster of them inject you at once. They will not inject you with more healing chem for the same injury unless 1. It uses the same chem for more than one damage type, or 2. you run out of it.

**Comment by RogerWilcoBeep** [comment]
goofball still cannot into writing good descriptions for chemicals but otherwise :+1:

**Comment by Kelenius** [comment]
Jeez. I'm not saying that I do it, I'm just saying that a lot of people do it, and it's a recipe for disaster. I'd make tricord non-ODable like on bay.

And a changelog.

**Comment by newfren** [comment]
If tricord isn't ODable then I will make 500 units at round start and swallow it all. This is the entire point of OD, you don't just load up on a billion units and regen out of everything.

Also I'm pretty sure if you literally just buffed Saline-Glucose then you wouldn't need to readd trekchem at all because all the other damage types are really easily treatable via injection. Charcoal and Salbutamol are strong as shit.

Also! Styptic Powder and Silver Sulfadiazine can be injected by the sleepers and you'll be fine because of how they work, it's just injecting and ingesting that give the tox damage.

**Comment by AnonymousNow** [comment]
I felt a gentle pull today.

I've been away from SS13 since around the start of the year - I've had a lot to do, what with volunteering, moving house and setting up a new roleplay group. I've met a new group of people, and sort of become the team mum for them. I've started playing D&D, and what time I've assigned to computer games I've mostly spent being a medic on Killing Floor 2 and helicopter support in Grand Theft Auto Online. I've looked in on the forums once or twice, but that's about it.

I felt a gentle pull today. I don't know why, but I had the need to check SS13 again. 

I saw this in the changelog. I rushed here, read this.

Life is good.

Drama aside, I was resistant to the removal of Trekchems from the beginning, and as the replacement system was slowly patched up and bandaged, I saw the shape of what it could have been, but felt the need for the return of our system.
Here's what I thought - readding Trekchem, but making it distinct from Goonchem in its strengths and weaknesses. Specifically, make Trekchems beginner chems - easy to make, harder to overdose on (higher threshold) with a weaker detriment when you do, but significantly weaker. They'd be something that anyone in chemistry could make in a minute, for patching up surface damage when you have the luxury of inexpertise and the time it takes for the medicine to tick. Meanwhile, Goonchems would be the advanced chemicals, the reserve of the actual chemists & CMO - they'd be harder to make, with more of a time investment, and lower overdose thresholds with more detrimental effects. But they're miracle cures, capable of zapping away your wounds in seconds, easy to compare to the lethargic Trekchems.

For example, a trainee doctor who's trying to fill in for an absent chemist reads a book, fiddles with the machine, and in the space of two minutes has some pills in front of you which slowly repair your flesh over about as much time as it took to make them.
Then the chemist comes in, rolls his eyes, spends seven minutes messing around with beakers and machines, and comes up with a pill which helps the dying clown to his feet and back to full health in 30 seconds.
Then the CMO waddles over, smacks the chemist and doctor around the back of the head, and spends ten minutes combining chemicals to make pills that, by using Goon and Trekchems in unison, makes the next victim get up and ready to fight in ten seconds.

You can also extend the differences even further. Somebody suggested that each of the two types could be limited to certain kinds of application or risk toxic damage. It's a no-brainer to suggest that Goonchem, being more complicated, would be able to heal the more complicated damage types (geneloss and brainloss, or whatever they're known as in-code). And you could even have it so that Trekchems are weak because they're straight-up metabolised slower, so that, in theory, you could dose up to a certain point and they'd tick their weak healing effect over that entire time, giving them a different utility to Goonchems once again.

Maybe I'm not the best judge here, but complexity is not necessarily a bad thing. Choice is great, and having options with pretty clear +/- is always appreciated.

Goof, I was short with you when this Goonchem pillaver began. I'm sorry, but I still think that it was more than silly to straight-up remove Trekchems in the first place. Thank you for adding them back, but bear in mind why we wanted them in the first place.

Now out.

**Comment by Iamgoofball** [comment]
>I felt a gentle pull today. 

that's the withdrawal kicking in

**Comment by kyrahabattoir** [comment]
I get defensive when people put healing terms and "10 seconds" in the same sentence.

**Comment by AnonymousNow** [comment]
Yes, that might be a bit much. But it's an example, and it requires significant time and effort to make a medical concoction potent enough to have such an effect.

**Pull request merged**
