### PR TITLE
Fixes sprite issue with security jumpsuit

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

The jumpsuit has a magic armplate that isn't on the left arm until you turn to the west
image
image

## Why It's Good For The Game

sprite inconsistencies!!!!

## Changelog
:cl:
imageadd: fixed a small icon thing with security jumpsuits
/:cl:

### CODE REVIEW

**Comment by Pugie** [comment]
Blessed

**Review by Twaticus — CHANGES_REQUESTED** [review]
>screenshot is of rsecurity_d
>only fixes rsecurity

arm you had one job!!

**Comment by tralezab** [comment]
!?

**Comment by actioninja** [comment]
conflict

**Pull request closed without merging**
