### PR TITLE
Legion mob nerfs

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

This PR does a handful of things to make the hostile "Legion" mob less dangerous.
Firstly: They will spawn extra mobs half as often.
Secondly: Those mobs have the "attack forecast" component also used by Goliaths and some other mining mobs.

Also now Legions can't spawn skulls while they're inside pipes or bags, because that doesn't make any sense.

## Why It's Good For The Game

When converted to basic mobs these guys became _far_ more deadly than they were supposed to be, to the point where even approaching a Legion tendril was basically suicide. 
This was compounded by an issue which would sometimes cause 33% more Legions to be present at the tendril than were supposed to spawn there, but they'd still be fairly scary with just 3 of them.

There were a couple of causes of this which this PR does something to address:
- Simple mob AI was simply a lot more sluggish than Basic Mobs. Legions now react faster and more reliably _actually_ spawn skulls at every available opportunity whereas previously despite having the same cooldown they wouldn't always bother.
- Similarly, the skulls themselves were slower to pick a target and slower to attack, whereas Basic Mob skulls will melee you the instant they detect that you are in range.
- This also means three (or four with the spawner bug) Legions dropping adds on you the second they see _you_, with no guarantee that you have yet seen them. The damage starts to become quite hard to avoid, and 4x Legion skulls (with another four spawning in two seconds) dealing 12 damage each would crit you very quickly.
- Our click CD means it's not even possible to punch four skulls in two seconds even if you managed to time it perfectly.

So to solve this: Spawn fewer of them, they do less damage, and you can step away from their attacks (this gets pretty hard when you're surrounded, but that is by design).

Eventually I am probably going to play like 20 rounds of miner, look at all of the mining mobs we have on each map, and then completely redraw what their roles are in a way that probably changes what this mob does quite significantly... but I'm not going to do it yet. This should do for now.

## Changelog

:cl:
balance: The melee attacks from small mobs spawned by Legions can now be dodged.
balance: Legions spawn their mobs less often.
fix: Legions cannot spawn mobs while inside pipes or closets.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
god damn it the spawner changes werent supposed to be on this branch too

**Comment by iansdoor** [comment]
Thank you! They were so brutal on everyone. 5 to 6 spawn spires were just death zones without aoe.

**Comment by githubuser4141** [comment]
Could the skulls possibly have a nerf to mechs? It's weird having several skulls appear _behind_ a mech, sometimes through solid rock walls, being that skulls didn't used to deal any damage to mechs period. Miss being able to see all the funny skill issue'd miners though.

**Comment by newfren** [comment]
well needed change these are far deadlier than basically any other mining mob

**Comment by Deultus** [comment]
It seems to me that reducing the rate of appearance of small skulls is quite enough. reducing damage looks unnecessary

**Comment by Deultus** [comment]
> > It seems to me that reducing the rate of appearance of small skulls is quite enough. reducing damage looks unnecessary
> 
> they still do a lot of damage even without a lot of skulls, 3 skulls can crit pretty rapidly

you can run away from them, you can kill them with one punch, the problem is the speed of their appearance, but not in any way in damage, this is an unnecessary weakening. fauna should be a great danger, especially since it is one of the sources of good treatment

**Comment by Nidvex250** [comment]
Oh thank goodness. It really felt bad when even Megafauna slayers had to limp back to the outpost because of all the chip damage legions were basically guaranteed to cause by existing now. Imagine how all the newbies and non-slayers must have felt going down to punch rocks only to get eaten by a small cluster of Legion.

**Comment by Exester509** [comment]
Maybe I haven't played enough mining to give an accurate judgement, but I felt like you could dispatch them fairly easily with a PKA and a bayonet. Again, haven't played mining in a while so this is probably inaccurate.

> Could the skulls possibly have a nerf to mechs? It's weird having several skulls appear _behind_ a mech, sometimes through solid rock walls, meaning you have to turn around, shoot/clamp them, then run away because more continue to spawn. being that skulls didn't used to deal any damage to mechs period. Miss being able to see all the funny skill issue'd miners though.

Also, I second this. Mechs don't have the quick response and versatility a human has when fighting legions and their skulls

**Comment by Jacquerel** [comment]
> Maybe I haven't played enough mining to give an accurate judgement, but I felt like you could dispatch them fairly easily with a PKA and a bayonet. Again, haven't played mining in a while so this is probably 

You can. When there's one of them.  
However because their newer AI makes them smart enough to bite _the instant_ they are capable of doing so it's virtually impossible to kill a skull using the bayonet without taking damage in return. This is also sort of fine... when there's one of them.   
You can avoid the damage by shooting them, however the click cooldown after doing this is long enough such that it means you're not going to easily shoot the Legion mob before it spawns another one, so that's a losing game.   

When there's more than one, these factors all combine into making them somewhat hellish unless you are well equipped with an AOE-damage gun mod or have prepped yourself with brimdemon dust which will automatically kill the skulls for you (at the cost of you still taking the quite high damage).

**Comment by NullDagaf** [comment]
> so it's virtually impossible to kill a skull using the bayonet without taking damage in return

You can kill skulls hit-less fairly reliably, as they don't attack until they've fully spawned in (while still being vulnerable themselves).
Still a pain in groups though, as micro-managing where every skull lands isn't fun. So 👍 from me.

**Comment by LePiromano** [comment]
John Mining seal of approval

**Comment by Metekillot** [comment]
Personally I just wouldn't get killed by something that does 48 DPS that doubles every 2 seconds where 100 damage crits you,  but I'm just built different

**Comment by Livrah** [comment]
I don't know why nerf legion.
You cleary can fight off 20 legions and just walk away if it someone bites you. Example:
https://youtu.be/AUDF-9dCJMU?si=wVDd3Hu1qhTnIGAJ

**Comment by CCC23** [comment]
Jesus Christ thank god also with this fact that you can't just put a box between you or shoot in the direction of the horde skulls made them ALOT harder to dodge or block from teleporting behind you

**Comment by DustanHache** [comment]
> I don't know why nerf legion. You cleary can fight off 20 legions and just walk away if it somehow bites you. Example: https://youtu.be/AUDF-9dCJMU?si=wVDd3Hu1qhTnIGAJ

the reason why is because your example is caused by severe lag. You try that shit on a local server or a med-lowpop server, and you will become a corpse VERY fast.

**Comment by Jacquerel** [comment]
I've decided that giving them attack forecast _and_ a damage decrease is probably going to be overshooting the target: Anything with a forecast attack probably should hit reasonably hard when you fail the quick time event.

**Comment by githubuser4141** [comment]
> Maybe I haven't played enough mining to give an accurate judgement, but I felt like you could dispatch them fairly easily with a PKA and a bayonet. Again, haven't played mining in a while so this is probably inaccurate.
> 
> > Could the skulls possibly have a nerf to mechs? It's weird having several skulls appear _behind_ a mech, sometimes through solid rock walls, meaning you have to turn around, shoot/clamp them, then run away because more continue to spawn. being that skulls didn't used to deal any damage to mechs period. Miss being able to see all the funny skill issue'd miners though.
> 
> Also, I second this. Mechs don't have the quick response and versatility a human has when fighting legions and their skulls

Nah, mechs can deal with them easily by avoidance or using Goliath armors, but it's annoying to require at least 2 Goliath armors or 1 armour booster + Goliath if you just want t rescue someone from a legion centre. It's pretty easy otherwise to just flip around a shoot/clamp them when mining

**Pull request merged**
