### PR TITLE
Changes all instances of "RD Console" to "R&D Console"

### PR DESCRIPTION
**Pull request by Spess-Rando**

### CODE REVIEW

**Comment by Core0verload** [comment]
You sure you tested this one?

**Comment by Sligneris** [comment]
It only changes displayed names.

It does not change internal names within the code, so it's pretty unlikely that it'd break anything

**Comment by Core0verload** [comment]
So, no. I just remember that at one point, "&" in object names was displayed as "_". Is this still happening?

**Comment by Kraseo** [comment]
it still does

**Comment by jughu** [comment]
Just call it RnD

**Comment by Sligneris** [comment]
430a685327
There's no need, it works just fine.

**Pull request merged**
