### PR TITLE
Adds PDA vending machine to HoP office [Boxstation]

### LINKED ISSUE #25702: Boxstation's HoP office does not have a PDA vending machine

### PR DESCRIPTION
**Pull request by BeeSting12**
Fixes #25702
so I don't get memed on by the freeze :^)
Before: 

After:

**OUTDATED: IMAGINE THE SPACE LAW BOOK GONE AND WRAPPING PAPER AND A HAND LABELLER IN ITS PLACE**
Pictures are worth a thousand words so just compare the pictures. The TLDR here is that it replaces a chest drawer with the PDA machines, takes out package wrapping paper and a hand labeler to put the chest drawer back, and removes the table that the wrapping paper and labeler was on.

:cl: BeeSting12
add: Boxstation's HoP office now has a PDA tech.
/:cl:

WHY: There is nowhere on boxstation to obtain PDAs until I made this PR. HoP doesn't even have a spare box of them in his office. Additionally, nowhere centralized to get PDA cartridges, although I believe that they can be found in the various departments.

### CODE REVIEW

**Comment by dannno** [comment]
took long enuogh

**Comment by Penguaro** [comment]
There's a box of spare PDAs on the bridge and has been for a while.

**Comment by Penguaro** [comment]
I have to ask, why are you building this off an outdated base? If you brought your master up to current and then branched off that for these changes, you could've done this with one commit.

**Comment by octareenroon91** [comment]
Labeler might be missed.

**Comment by BeeSting12** [comment]
@Penguaro 
Yes, please, that'd be great. I'm not very familiar with git as I haven't used it much. What I've been doing is comparing and making PRs to my fork that updates it. I've only done this when conflicts show up so it is probably out of date.  Anyways, I'll move the PDA box from the bridge to the HOP office- they don't belong there anyway. There's hand labelers in cargo, which the HoP has access to. I could place it back on that table by his locker.

**Comment by Penguaro** [comment]
Bear in mind there is an ID changing station on the bridge as well which is why there can justifiably be a box of IDs and PDAs there. There is also an ID station at the Arrivals Security Checkpoint but I don't believe there are IDs there and really there shouldn't.

**Comment by jughu** [comment]
Removing the hand labeler and wrapping paper no bad bad how im supposed to send replacement idds directly to departments

**Comment by BeeSting12** [comment]
Box's HoP office is so small it's very hard to find places to put stuff without making it look ugly. I'll place the labeler and wrapping paper on the table where space law is I guess.

**Comment by BeeSting12** [comment]
And yeah I'm not putting IDs in arrivals checkpoint, that's the first place people who steal an all access ID go and they should have to work harder to get infinite all access IDs.

**Comment by Penguaro** [comment]
Do keep in mind, an ID terminal can rather easily be built anywhere. The biggest challenge will always be getting either the Captain's or HoP's ID in order to create all access.
-Also, I'll contact you separately about Git.

**Comment by BeeSting12** [comment]
Username's BeeSting12 on discord and steam if you want to contact me there

**Comment by calzilla1** [comment]
What does the wrapping paper and hand labeler serve? I recommend we port vg's dispsals request console mail system

**Comment by Penguaro** [comment]
@calzilla1 The wrapping paper keeps the package intact for shipping and the labeler is a message to the recipient. So a box can show up in the appropriate department but the label might say it's for John Smith. It's an honor system. The labeler servers various IC purposes that may not affect anyone but the person using it but is nice to have if you're the sort who uses it.

Additionally, a port of VGs system will take time to implement. The labeler works now.

**Comment by BeeSting12** [comment]
Hand labeler and wrapping paper are both back. Replaces the space law book, as if anyone uses that in the first place. There's enough space law books lying around that I don't think this would be an issue, plus the HoP shouldn't be performing arrests or sentencing so he doesn't need it.

**Pull request merged**
