### PR TITLE
remaps chemistry to accommodate to the new heaters

### PR DESCRIPTION
**Pull request by pudl**
image

### CODE REVIEW

**Comment by Anonus** [comment]
I don't like being unable to get in through the middle window, or the double chem dispenser line thing.

**Comment by paprka** [comment]
>chemists can use each other's chem dispensers

nope.jpg

**Comment by pudl** [comment]
i honestly have no idea how to make the remap any other way. if you haveany ideas i'll use them

**Comment by tkdrg** [comment]
Maybe just put the 2 heaters in the middle and keep chemmaster/chemdispenser in the sides. Won't solve the window problem though.

**Comment by pudl** [comment]
i think there's still an issue, since either way tampering can happen. and since the wrong temperature can result in lethal reactions, i'd rather have chem dispensers in the center

**Comment by Iamgoofball** [comment]
:+1:

**Comment by paprka** [comment]
a) why did you add a third chemist spawn
b) what is wrong with what we have currently

What we have now:
ss 2015-01-14 at 06 46 43

Just remove the third chem heater in the middle, it's fine outside of that

**Comment by paprka** [comment]
ss 2015-01-14 at 06 53 02

This is what I would do

>you will never be able to move while buckled to an office chair without fire extinguishers

suffering

**Comment by pudl** [comment]
i was asked to remap it, i just did what i could. if someone else agrees that the current design is fine then we can go with that

**Comment by tkdrg** [comment]
I like your design better than paprika's.

**Comment by Iamgoofball** [comment]
I like @pudl chemistry over @paprka chemistry

**Comment by paprka** [comment]
but why

you frequently need to throw shit in the disposal bin and it's easier if it's adjacent

**Comment by Lumipharon** [comment]
If you block me from throwing things into the disposal chute from where I can reach all the chemistry machines, I will murder you. Current/Pap's is more better and more practical.

**Comment by TZK13** [comment]
Agreed with Lum, having a disposals bin easily accessible by both chemists is vital.

**Comment by paprka** [comment]
Mine is good because soon you will be able to move when buckled to roller chairs so you can just roll to the window :+1:

**Comment by pudl** [comment]
i can move the disposal bin easily.
i figured it wasnt vital since metastation had dispoal bin away from the bottom desk

**Comment by paprka** [comment]
your version also allows chemists to scalp chemicals from each other which is :-1:  as fuck

**Pull request closed without merging**
