### PR TITLE
Water will now make you wet

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
Water, when exposed to a mob either via `TOUCH` or `VAPOR` application, will now apply wet stacks to said mob according to the amount of water used. For touch application, the ratio is 0.5 wet stack per unit of water, whereas for vapor application (so for foam and sprays), that ratio is lowered to 0.1 wet stack per unit of water. Yes, that would mean that you could now put someone out by spraying enough water at them with a spray bottle (usually around 50-150u), and I think that is quite simply hilarious.

As a reminder, wet stacks decay slowly over time, however obviously raising your fire stacks (so being exposed to something that's on fire, for instance) will speed up that decay, once https://github.com/tgstation/tgstation/pull/72843 is merged. I separated them in two PRs because honestly the fact that being wet made you more flammable just sounds like a fuckup of the year if I've ever heard one.

I also updated the unit test of water's `expose_mob()` proc, to check that wet stacks were being applied properly, hopefully making sure that there's no regression on that part in the future.

## Why It's Good For The Game
The number one thing you think of when you think of the word wet is water. Water should make you wet, it only makes sense.

## Changelog

:cl: GoldenAlpharex
balance: Water now makes you wet on touch and vapor application, with vapor being much less effective than touch. Yes, that means you can now spend two minutes putting someone out with a spray bottle full of water!
/:cl:

### CODE REVIEW

**Comment by castawaynont** [comment]
water isn't wet, being wet is a state of being inundated with water as a non water substance

**Comment by CRITAWAKETS** [comment]
"water is wet"
LIES!!!1!one!

that said, otherwise seems sensible, though maybe vape clouding the halls with a smoke machine may cause problems

**Comment by GoldenAlpharex** [comment]
> "water is wet" LIES!!!1!one!
> 
> that said, otherwise seems sensible, though maybe vape clouding the halls with a smoke machine may cause problems

I don't know how much smoke machines and vapes expose you with, but the value in wet stacks is intentionally very low so that it should take you a while before you get utterly drenched.

**Comment by Shadowflame909** [comment]
Very useful and good piece of logic this game was missing. I just hope it doesn't mess with that water healing virus (tissue hydration?)

**Comment by Bobthe28th** [comment]
Did this fix #72505 including fixing the fire virus explosion?

**Pull request merged**
