### PR TITLE
Persistent Map Vote Tallies

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

Changes map votes to be based on a persistent tally count.
Tallies for maps are cached between rounds and are added to by map votes.
When a map is chosen, and it wasn't the only valid one, the tallies for said chosen map will be reset.

Refactors map vote handling and moves it from SSmapping to SSmap_vote.
Rock the Vote has been removed as a result of this refactor.

## Why It's Good For The Game

Makes it more likely that all maps will be played over the course of a server instead of always being truly random.
Removes some clutter off of SSmapping.

:cl:
refactor: Map Votes are now carried over between rounds. When a map vote is actually a contest, the winning map will have its votes reset.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Where is the flat bonus?

**Comment by ZephyrTFA** [comment]
> Where is the flat bonus?

I have a minimum tally count, are you looking for maps to get a minimum tally count per vote also?

**Comment by optimumtact** [comment]
@tgstation/owners @tgstation/head-admins 
I'm going to merge this unless you say something

**Comment by LemonInTheDark** [comment]
needs a changelog this is highly player facing

**Comment by LemonInTheDark** [comment]
image
he has not elaborated, marking as draft until worked out (how is this fucking possible)

**Comment by ZephyrTFA** [comment]
Great news.
This compiles just fine on versions above TGS 3.

Bad news.
We still use TGS 3.

**Comment by LemonInTheDark** [comment]
MSOOOOOOO

**Comment by LemonInTheDark** [comment]
is the problem down to the api spec or something?

**Comment by ZephyrTFA** [comment]
Looks to be a byond bug we found through black magic and bad luck.
MSO is trying to narrow down a test case

**Pull request merged**
