### PR TITLE
added improvised heating

### PR DESCRIPTION
**Pull request by Delimusca**
use any fire-producing item on a soda can/bucket/bottle/etc. to heat it up.
also fixes a false boolean on matches.
i'm sure there's a few things i missed, do point out any you find.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

**Comment by fj45** [comment]
What about using space heaters?

**Comment by Jordie0608** [comment]
Changelog

**Comment by Fox-McCloud** [comment]
I'd recommend adding a message too, so it's obvious what's going on:

"you heat the <container> with the <heatythingy>!"

**Comment by Iamgoofball** [comment]
@Fox-McCloud it has a heating message alread

**Comment by Fox-McCloud** [comment]
Derp; missed the obvious.

**Comment by Cheridan** [comment]
Fuck me, we really needed those cooks. :fire:

**Pull request merged**
