### PR TITLE
Removes firing-pins box in RD's locker

### PR DESCRIPTION
**Pull request by Wilchenx**
:cl: Wilchen
del: Removed box of firing pins from rd's locker
/:cl:

Makes no sense since science can't print any guns and probably won't ever be able to again.

### CODE REVIEW

**Comment by Kromgar** [comment]
Boo hiss

**Comment by Wilchenx** [comment]
If they can get sec lathe board they can get pins

**Comment by optimumtact** [comment]
sherrie is right

**Comment by yoyobatty** [comment]
break into sec via one maint
take sec lathe board

**Comment by Shadowflame909** [comment]
I would like this pr to be renamed, this is clearly a nerf! Yet, I think this is futile. If the RD gets access to make guns, why wouldn't he get access to firing pins? This just sorta reduces the amount of firing pins. So a tedious nerf in general.

**Comment by Shadowflame909** [comment]
They're the RD. They won't look suspicious being in security. What's stopping them from making guns with the security prolathe? This just seems like a timegate. Because they'll also have to research mindshield pins instead of starting with 5 of them at roundstart. That's all.

**Comment by Wilchenx** [comment]
Mindshield pins are not normal pins.

**Comment by Shadowflame909** [comment]
That's true, but the RD still gets them only. What point does this serve other than delaying the RD by a millisecond? You may say "RD no longer can make guns" but that's simply untrue. Science, in general, can no longer make guns. I, in fact, would like to argue, that this increases the power the RD has. If you force the RD to make Mindshield pins instead of just using normal ones. A traitor/normal crew-member trying to stop a traitor RD will try to disarm them, steal there gun. Only to be unable to fire it due to such a nerf forcing RD to use more powergamey mechanics to use the weapons they desire!

**Comment by Shadowflame909** [comment]
So my only argument for this is, lets not force people to use mindshield implants. Which can be an unfair advantage that would be NECESSARY for the Research Direction who researches the guns. The less inclined people are to make mindshield pins. The better.

**Comment by Repukan** [comment]
So just move the mindshield pins to sec lathe

**Comment by Wilchenx** [comment]
What the fuck is shadowflame909 on about

**Comment by Bawhoppen** [comment]
Please succeed where I have failed :+1:

**Comment by Shadowflame909** [comment]
Don't "what did he mean by this??? 🤔" Meme me wilchenx. Actually try to understand why you have those 7 downvotes. It's not like I'm making it hard to understand. First off, don't tell me it isn't easy for a head of staff member to get a gun. They all have sec access in one form or another. They can be like "hey security can you open this door to the prolathe room." "Sure ok, no reason not to trust you head of staff member" Secondly, the only creatable firing pins are mind shield and testing lab. I'm not sure why you'd want to FORCE the casual powergamer RD to take 2 seconds to use a mindshield pin on there Tesla guns, its so easy to obtain and is a Huge counter to the average non head of staff player. But sure, let's just delay the RD for a few seconds and force him to powergame for the mindshield pins. RND not having guns was a counter to scientists. It was never gonna effect a head of staff member. This is just gonna make powergame worse. Not fix any "useless code wtf time to remove"

**Comment by ExcessiveUseOfCobblestone** [comment]
It should be a timegate anyways, they are meant to be testing the guns not using them to kill people (well that's what they're fluffed as)

**Comment by iskyp** [comment]
\> research is not supposed to have guns
\> but they should still have firing pins
@Shadowflame909 are you high

**Comment by iskyp** [comment]
also head of staff =/= should have guns

**Comment by Wilchenx** [comment]
@ExcessiveUseOfCobblestone firing range and test range firing pins are still avaible

**Comment by Shadowflame909** [comment]
I'm not complaining about time gating it. Or anything like that. I'm complaining about how this will only force power gamers to use mindshield implants. @ExcessiveUseOfCobblestone Honestly, a better solution would be to move the security prolathe to the armory. RD can just walk in and print a gun, put a mindshield firing pin in and leave. A better solution then this one would be making the locker not open until 22 minutes into the round. That's effectively what this does, but worse!

**Comment by Kromgar** [comment]
That reminds me if sci isnt supposed to have guns... why do they have a weapon testing range?

**Comment by iskyp** [comment]
@Kromgar mappers are lazy
@Shadowflame909 sci shouldn't have guns and if the RD gets guns from sec then they also have to get mindshielded to even use them with this change
a l s o R D s h o u l d n ' t h a v e g u n s w h a t i s y o u r a r g u m e n t

**Comment by YakumoChen** [comment]
ah yes, finally, the last nerf for the completely non-existing "science gun problem"

**Comment by kevinz000** [comment]
bad

**Comment by Shadowflame909** [comment]
@iskyp last comment for this thread but literally "THEY SHOULDN'T HAVE GUNS WHAT ARE YOU ARGUING" is like me saying "ASSISTANTS SHOULDN'T HAVE INSULS WHAT ARE YOU ARGUING ABOUT FORCING THEM TO STEAL NINJA GLOVES" . If what you're saying is correct. THE RD NEVER EVER EVER GETS THERE HANDS ON A GUN? Well, they do. They always will if they really want to. It's not that hard for an RD to walk into the bridge and reach the sec prolathe that's not even in the armory. The point is, you can't stop powergamers from powergaming. So why should we reward them for powergaming? If I were to describe it. It'd be like tricking the powergamer into taking the easier route that has a bunch of mud. Or forcing the powergamer into taking a harder route, that has gold and silver? You'd rather not have them taking either route, but we all know the first one (The regular firing pin) is better then the (mindshield firing pin) route.

**Comment by iskyp** [comment]
>The RD never ever gets their hand on a gun

I'm saying the RD SHOULDN'T have guns, and your point of "OH HE CAN GET IT IF HE WANTS TO" is invalid, because anyone can get a gun if they want to. You can craft it, or break into security and steal their firing pins. It's just easier for some people and harder for others.

Where in my mess of an argument did I ever say "THE RD NEVER GETS GUNS EVER"

>you can't stop powergamers from powergaming

yeah but you can make it harder on them. How does the RD have firing pins make it harder for powergamers to get working guns?

anyways i'm done arguing about this because i want to play video games

**Comment by BeeSting12** [comment]
Science already doesn't get guns, now we're just removing the firing pins since there's no reason for them to be in the locker.

**Pull request merged**
