### PR TITLE
flatpacker

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

adds the flatpacker, it flatpacks machines
2024-02-08 19_47_34-Window
it is unlocked at industrial engineering
honestly i cant really explain how it works but you can just watch the attached video
anyway as for upgrades
the default print time is 4.5 seconds, reduced by the servo tier divided by 2
matter bins increase material capacity
better servos decrease material cost, and the flatpacker cannot print a machine if it contains parts that are of a tier larger than the servos tier

https://github.com/tgstation/tgstation/assets/70376633/01bd21b8-de14-4351-916b-35b4a7f914a0

## Why It's Good For The Game

machine construction sucks, this should be more convenient, this does not replace machine construction at all
compared to machine frames while this is faster and more convenient, it is significantly more costly in materials, and a better servo is needed to use higher tier parts, and the printed machines are always the lowest required tier

## Changelog
:cl:
add: the flatpacker, a machine unlocked at industrial engineering
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Closed for breaching feature freeze

**Comment by mc-oofert** [comment]
> Closed for breaching feature freeze

johnfulpwillard try to benefit the codebase challenge

**Comment by Ekaterina-von-Russland** [comment]
Just make the PR once the feature freeze ends...

**Comment by mc-oofert** [comment]
> Just make the PR once the feature freeze ends...

it  has ended

**Comment by K4rlox** [comment]
> Just make the PR once the feature freeze ends...

talked to fulp, he said he is banned from PRing this feature because he CODED IT during feature freeze

**Comment by Xander3359** [comment]
> > Just make the PR once the feature freeze ends...
> 
> talked to fulp, he said he is banned from PRing this feature because he CODED IT during feature freeze

Yes, that's what happens when you code features during feature freeze.

**Pull request closed without merging**
