### PR TITLE
Adds botany disk fridge to Omega

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: Added a disk compartmentalizer to Omegastation's hydroponics.
/:cl:

Omega is the only map that doesn't have those yet.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
@MrDoomBringer @Mey-Ha-Zah @Onule 

Can one of you artists make a sprite for this. I'm imagining a toaster-looking device that stores floppy disks instead of bread.

**Comment by MrDoomBringer** [comment]
This sounds like something fun! Im out of town rn, but i whipped up something based on an old space-heater reject i made. Howabout something with this general shape/style?
image

**Comment by ExcessiveUseOfCobblestone** [comment]
something like that, yeah. Make it blatantly obvious it's based off a toaster though :^).

**Comment by MrDoomBringer** [comment]
what is with you and toasters

i'll do it for denton

**Comment by ExcessiveUseOfCobblestone** [comment]
because it's funny!

also y-y-y-yeah f-f-f-for d-d-d-d-denton h-h-h-ha-h-ha

**Comment by MrDoomBringer** [comment]
image
wont people just be like "what is this toaster doing in my botany garden"

**Comment by ExcessiveUseOfCobblestone** [comment]
yes that's what ~~we're~~ i'm going for.

**Comment by Mey-Ha-Zah** [comment]
Don't know why I was mentioned... I haven't sprited for SS13 for 2 months.

**Comment by ExcessiveUseOfCobblestone** [comment]
because I've been not-very-active for a while :3

**Comment by 81Denton** [comment]
I feel honored to have a disk toaster sprited for my PR

**Comment by ExcessiveUseOfCobblestone** [comment]
now add it anon....

DO IT!

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
