### PR TITLE
adds a small cave to the norteast of lavaland

### PR DESCRIPTION
**Pull request by Sealed101**
## About The Pull Request

just a small cave near the nercopolis

hi

## Why It's Good For The Game

grug

<details><summary>cough</summary>

https://www.youtube.com/post/Ugkxme3RsuqnXHL3FJTDrZ22fABdA1PMPj2k

</details> 

## Changelog

:cl:
add: some rocks fell and a small cave has unearthed itself on lavaland
/:cl:

### CODE REVIEW

**Comment by MoonDeer728** [comment]
Grug home?

**Comment by Loafin34** [comment]
how cute. probably closed though.

**Comment by notfrying1pans** [comment]
why is it called the gooncave that action is strictly prohibited here

**Comment by Sealed101** [comment]
revenge of the goon folder

**Review by Ghommie — APPROVED** [review]
The maptainers are sleeping.

**Review by Ghommie — CHANGES_REQUESTED** [review]
Maptainer has told me this should probably be a ruin rather than something being directly mapped in the lavaland file.

**Comment by Sealed101** [comment]
it was not meant to be

**Pull request closed without merging**
