### PR TITLE
Adds tarajan race to the game

### PR DESCRIPTION
**Pull request by optimumtact**
as a retardation meme reference

In b4 aran closes without looking

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Zilenan91** [comment]
niceme.me

**Comment by Dorsisdwarf** [comment]
Not retarded enough sounding

**Comment by optimumtact** [comment]
furry detected.

**Comment by Cebasiz** [comment]
muh slippery slope

**Comment by Bawhoppen** [comment]
why did we remove those old meme gibberings anyways

**Comment by Iamgoofball** [comment]
We still have them check the if (1) section of the switch

**Comment by Bawhoppen** [comment]
why do we even have multiple sections of it then and not just one big list

**Comment by Iamgoofball** [comment]
Easier to read.

**Comment by Bawhoppen** [comment]
its not like the first list isn't pretty damn big already

**Comment by Iamgoofball** [comment]
Yeah, but why nake it even bigger?

**Comment by optimumtact** [comment]
It's on my list to fix it some day

**Pull request merged**
