### PR TITLE
Adds fax machines to kitchens

### PR DESCRIPTION
**Pull request by DaxDupont**
## About The Pull Request

Adds fax machines and makes sure paperbins are in the kitchens. Some items have been moved around in the kitchen.

## Why It's Good For The Game

Honestly, I love the fax mechanics. However I noticed that the kitchens were left out. The kitchen is one of the few areas that a fax actually makes sense. Now you can order food through the fax, this way your food might be ready for pickup! 
This honestly makes more sense than some of the existing areas.

## Changelog

:cl: DaxYeen
add: Faxes have been added to most kitchens. This way you can order food for your department or yourself more easily.
add: Paperbins have been added to kitchens missing them.
/:cl:

### CODE REVIEW

**Comment by DaxDupont** [comment]
I don't think most of them do @MrMelbert besides, a fax in a room/area people usually don't really pass a lot makes it a useless fax machine.

**Comment by DaxDupont** [comment]
@MrMelbert on meta I guess you could argue it's in a hallway close enough in view i guess.

**Comment by DaxDupont** [comment]
I moved the service hallway fax  on meta so it's in view better. The kitchen fax has been removed there.

**Comment by JohnFulpWillard** [comment]
image

Only Kilo is missing one

Delta
image

Tram
image

On Icebox it's on the lower floor of service maints, so not even near the techfab
image


I don't want to keep both, however I do find it worthless to be in the Service hallway, unless we can somehow get departmental faxes that announce over the radio when they get one, or being able to ping departments that one directed at them has arrived (like through request consoles), because otherwise I don't see all Service personnel going to their department's Faxes to see if there's anything meant for them.

Meta's is fine for the Kitchen because it's directly behind the kitchen, but cases like Delta where it's across the hallway, Tram which is on the lower floor, and Icebox where both apply, I don't see Cooks checking their faxes very often.

**Comment by DaxDupont** [comment]
Yeah on meta I moved them a few tiles instead.

I'd argue the general department fax can have some uses for non-kitchen usage still.

**Comment by private-tristan** [comment]
> unless we can somehow get departmental faxes that announce over the radio when they get one

don't the requests console (not the departmental ordering console) already do this when you get a request? except the thing is that noone uses them and their only purpose is to beep whenever miners deliver

**Comment by msgerbs** [comment]
Pls no, kitchen counter space already feels super limited on most maps.

**Comment by DaxDupont** [comment]
If the maintainers don't mind me making it publically accessible I can move it to the food counter for more space

**Comment by JohnFulpWillard** [comment]
> > unless we can somehow get departmental faxes that announce over the radio when they get one
> 
> don't the requests console (not the departmental ordering console) already do this when you get a request? except the thing is that noone uses them and their only purpose is to beep whenever miners deliver

This was what I was referencing yes, making them alert new faxes since they already alert mineral dropoffs. The problem would be that faxes would have to change to either;
- faxes be departmental and have department radio, broadcasting there when they get a new fax
- faxes would have to be named after a specific department, and faxing that department would make their request console go off.

Either way, I think it's out of scope for this PR, but I am personally not in favor of cooks having 2 faxes.

**Comment by msgerbs** [comment]
> This was what I was referencing yes, making them alert new faxes since they already alert mineral dropoffs. The problem would be that faxes would have to change to either;
> 
>     * faxes be departmental and have department radio, broadcasting there when they get a new fax
> 
>     * faxes would have to be named after a specific department, and faxing that department would make their request console go off.
> 
> 
> Either way, I think it's out of scope for this PR, but I am personally not in favor of cooks having 2 faxes.

Third option: Faxes could have an encryption key inside them (or just a radio var) telling them where to broadcast, perhaps even a wire to toggle it on and off. But yeah, beyond the scope of this PR and I agree that the cook doesn't need their own fax machine.

**Comment by KommandantJackal** [comment]
> > This was what I was referencing yes, making them alert new faxes since they already alert mineral dropoffs. The problem would be that faxes would have to change to either;
> > ```
> > * faxes be departmental and have department radio, broadcasting there when they get a new fax
> > 
> > * faxes would have to be named after a specific department, and faxing that department would make their request console go off.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Either way, I think it's out of scope for this PR, but I am personally not in favor of cooks having 2 faxes.
> 
> Third option: Faxes could have an encryption key inside them (or just a radio var) telling them where to broadcast, perhaps even a wire to toggle it on and off. But yeah, beyond the scope of this PR and I agree that the cook doesn't need their own fax machine.

Thus is leasing me to the concept of putting Pais in fax machines

**Comment by SuperNovaa41** [comment]
I think they are far better off in the service hallway tbqh

**Comment by JohnFulpWillard** [comment]
I'm closing this PR since we don't plan on merging it. Many alternative ideas were offered here if you want to try implementing those instead, we just disagree with this specific route.

**Pull request closed without merging**
