### PR TITLE
fucking pranked

### PR DESCRIPTION
**Pull request by Iamgoofball**
pranked hardcore

### CODE REVIEW

**Comment by kevinz000** [comment]
[18:07] <Iamgoofball> Xhuis, it's the oldstation sprites
[18:07] <Iamgoofball> like
[18:07] <Iamgoofball> the really really oldstation sporites
[18:07] <Iamgoofball> the shitty ones
[18:07] <Wirewraith> goon emissary #1
[18:07] <Xhuis> omfg lmao
[18:07] <LeoZ> but i don't know you and i don't like the unknown...
[18:07] <vcordie> golfball, you need to include screenshot.
[18:07] <Xhuis> i take it back that's hilarious
[18:07] <Iamgoofball> i wanna see how many peoplke will blindly support this on the promise of 'GETS RID OF FILTHHY GOON"

**Comment by Iamgoofball** [comment]
# HE LIES

# FAKE NEWS

**Comment by Haevacht** [comment]
<vcordie> itt: goof stands in pool of gasoline, lights a match.

**Comment by Iamgoofball** [comment]
_^_

**Comment by MMMiracles** [comment]
port all possible sprites from openss13 and make a pull request

we need to go back our roots

**Comment by Iamgoofball** [comment]
# WE GOTTA GO BACK 2 THE PAST

**Comment by ChangelingRain** [comment]
wow i'm super tired of goof meme prs

**Pull request closed without merging**
