### PR TITLE
Vaccines must now be injected, and require 5 units to cure.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Vaccines must now be injected, and require 5 units to cure.

## Why It's Good For The Game

Currently, the process of curing a virus for the entire crew is:
1. Grab a cured person after giving them their sugar or ethanol or whatever
2. Get a blood sample
3. Go back to the Pandemic
4. Generate a bunch of vaccine culture bottles
5. Make approximately 500~ Vaccine (0.1u) pills and drop them on the floor in front of medbay
6. Go back to virology for the rest of the round, or leave medbay or whatever

This is boring as shit, involves nobody but the virologist and whoever the person who's blood you took is, and leads to massive stacks of objects on the floor.

By making vaccines require injection and a minimum of 5 units, it encourages the virologist to dose out vaccine shots and employ the other medical staff in getting shots in arms. 

This gives viruses more of an opportunity to impact someone rather than them beelining medbay and eating the first pill they see off the ground the second they sniff or see a face pop up on their health HUD. It also means virologists have reasons to keep getting samples from cured patients, as they'll now need to produce far more vaccine culture to cure patients.

Also, I hate seeing 50000 pill stacks of Vaccine (0.1u) on the floor in medbay.

## Changelog

:cl:
balance: Vaccines must now be injected, and require 5 units to cure.
/:cl:

### CODE REVIEW

**Comment by magatsuchi** [comment]
i would rather have one or the other, not both. otherwise this is big SD buff

**Comment by RuneQuester** [comment]
This PR doesn't actually fix any of the issues you stated. It just makes the process 10x slower

**Comment by Iamgoofball** [comment]
It fixes 10,000 pills on the floor of medbay and vaccine microdosing.

**Comment by RuneQuester** [comment]
> It fixes 10,000 pills on the floor of medbay and vaccine microdosing.

...It does, but it doesn't fix this whole process not including anyone but the viro. What it does do, is slow the entire process by like 30 minutes and make it so much more tedious for no real gain.

**Comment by Serxule** [comment]
ah yes make it so everyone has no chance at surviving a death virus. did you not think about how bad certain viruses are?

**Comment by Iamgoofball** [comment]
Worst case we leave it at 5 units, but 0.1u dosing has got to go.

**Comment by Time-Green** [comment]
> Worst case we leave it at 5 units, but 0.1u dosing has got to go.

Why though? On servers with a deadly virus this’ll just make people spent 10 minutes pressing print and waiting for the cooldown while literally everyone dies from the virus

**Comment by CMDR-Gungnir** [comment]
Viruses are kinda balanced around things being how they are now. Even like this, I've seen viruses just decimate the station before.

**Comment by Spookuni** [comment]
I can't wait for the "print three panD.E.M.I.Cs" meta when people get upset that only one doesn't print vaccines fast enough for their tastes.

**Comment by Iamgoofball** [comment]
@Spookuni sounds like engineering gameplay

**Comment by Spookuni** [comment]
Insofar as a department being unable to fully complete what it's designed to do pushing people towards saying fuck it I'll do it myself is everybody else's gameplay, sure. I'm not particularly fussed one way or another, this just seems like it's going to push towards a new meta of "best solution" gameplay, certainly easier to just leave a pile of syringes in the medbay lobby than have MDs do it manually (straight up mechanically, mind, self-injection is instant, injecting someone else has a do_after), but if that's desirable then 🤷. I don't mind.

**Comment by CMDR-Gungnir** [comment]
> Insofar as a department being unable to fully complete what it's designed to do pushing people towards saying fuck it I'll do it myself is everybody else's gameplay, sure. I'm not particularly fussed one way or another, this just seems like it's going to push towards a new meta of "best solution" gameplay, certainly easier to just leave a pile of syringes in the medbay lobby than have MDs do it manually (straight up mechanically, mind, self-injection is instant, injecting someone else has a do_after), but if that's desirable then 🤷. I don't mind.

no spook you'll give him more ideas.

**Comment by Swiftkor** [comment]
I like the idea of vaccination requiring syringes, it just makes sense. I do think if this is implemented you should remove the cooldown for manufacturing new vaccines or make some way to produce them faster if you're going to require 5u

**Comment by lewcc** [comment]
Maybe if the pandemic were upgradable with stock parts to boost the output of vaccine doses (it's still pathed as a computer...) this would make sense, but I agree that it'd just make getting everyone vaccinated while they burn to death in medbay even more of a struggle

**Comment by thgvr** [comment]
Me on the way to print 500 syringes and suck up 5u into them.

**Comment by Muffindrake** [comment]
No go. The fact that people hoard piles of cures on the floor is a symptom of the whole 'cure' process being uninteresting and easy to implement in code. Requiring injection is a good first step. You can dump the rest of the PR.

Instead of a single chemical deleting viruses from existence, how about adding some complexity to the whole cure thing? Have several different antiviral drugs that do different things, can't be injected at the same time, and perhaps be administered in a random order, in order to properly cure someone?

**Comment by tralezab** [comment]
> Me on the way to print 500 syringes and suck up 5u into them.

you say this but even that is better than 0.1u pill spam

**Comment by Justice12354** [comment]
I really liked @lewcc's suggestion. Furthermore, why not increase the minimum required to vaccinate 1u instead of 5u? 5u would be far too much. It'd be basically 1 bottle > 3 people, unless you reduce the cooldown between bottles significantly, in which case you could as well just reduce the quantity required to cure the virus. In order to cure a highpop, it'd be easier to just mass-produce the cure rather than to produce vaccines (even if it means setting everyone to sleep with Haloperidol). This change will most likely just change the way people cure viruses: instead of using vaccines, mass-produce the cure. It's easier, faster, and less annoying.

**Comment by moocowswag** [comment]
requiring injection is kind of an antag buff.

Like you arnt really gonna hurt anyone with fake 0.1 "vaccine" pills unless your pills have something like advanced slime mutation toxin.

But requiring 5u injections to cure means youll be able to disguise those injections.

Which also might result in the virologists being forced to just mass produce vaccine bottles and dropping them + a ton of syringes infront of medbay for people to inspect the bottles and inject themselves, since otherwise they might get lynched for randomly trying to cure infected people.

**Comment by Bawhoppen** [comment]
Good PR, this was cheesy before 👍

**Comment by Acer202** [comment]
> I like the idea of vaccination requiring syringes, it just makes sense. I do think if this is implemented you should remove the cooldown for manufacturing new vaccines or make some way to produce them faster if you're going to require 5u

Aerosolized vaccinations are a real thing. You get antibodies naturally without taking shots all the time. A syringe just happens to be an effective way to do it, but you could manage a vaccination by any method that introduces the antibodies to your body. Requiring a syringe and only a syringe is kinda extreme.

**Comment by Shadowflame909** [comment]
Counterpoint: Viruses are lame and imagine getting murderboned by another player you haven't even interacted with. How messed up is that

**Comment by Mothblocks** [comment]
I do not want virology buffs

**Comment by Farquaar** [comment]
It's barely a buff, let's be honest here.

**Comment by exymian** [comment]
> > I do not want virology buffs
> 
> It's barely a buff, let's be honest here.

its a huge buff what are you talking about

**Comment by B4CKU** [comment]
based PR

**Pull request closed without merging**
