### PR TITLE
[Merge Ready] "AsteroidStation rises from the dead, try two!"

### PR DESCRIPTION
**Pull request by CorruptComputer**
Now without Merge Conflicts!

Look at https://github.com/tgstation/-tg-station/pull/9758 for more details.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Heads up, I just checked solars.dm, they trace to the edge of the world the sun is at in order to determine if they're in shadow. None of the four solar arrays will work

**Comment by Metacide** [comment]
I'd very much like to see this run sometime, more novelty is always needed. :+1:

**Comment by Stickymayhem** [comment]
CorruptComputer chat to me on coderbus or somewhere I want to slam this down Sybil's throat for a few days until they gag on it.

**Comment by Stickymayhem** [comment]
Here are my suggestions: 
- Make teleporter room smaller, give it hallway access and expand maintenance around xenobiology so it connects to it and isn't just a single path one tile wide
-Flip the AI core so it can't be lasered from the front door.
-Move telecomms spare parts to tech storage, that room can be a hall facing light bulb/air canister/space heater storage
-That empty rack in the armory is damaging my autism. Put a kinetic accelerator on it.
-Put two pickaxes in EVA
- Dorms needs two sets of glass doors.
- The laundry place in dorms needs some glass windows or a locker or something to stop it looking so empty
-Singularity field requires more setting up. You're completely insane but this one I can take or leave.
-Some parts of maint look a little unloved.

AI Core, EVA pickaxes and the teleporter are the main changes I'd need to see before forcing this on Sybil.

**Comment by Jordie0608** [comment]
The AI core has shutters under the glass in the middle, unless they've been removed.

**Comment by CorruptComputer** [comment]
@Dorsisdwarf 

I'll see what I can do to get them working.

@Stickymayhem 

* Screenshot was slightly out of date and that's already been done
* Jordie's comment
* I'll look at that for next commit
* I'll look at that for next commit
* I'll look at that for next commit
* I'll look at that for next commit
* I'll look at that for next commit 
* Screenshot was slightly out of date and that's already been done
* Screenshot was slightly out of date and that's already been done

**Comment by CorruptComputer** [comment]
@Stickymayhem 

I did everything you asked except the telecoms storage, the way atmos is set up on the map that is not needed. And, it just makes more sense to have the telecoms stuff with telecoms, at least to me.

**Comment by SconesC** [comment]
depsec must go

**Comment by CorruptComputer** [comment]
@SconesC 

Before I do that, why?

**Comment by SconesC** [comment]
I've discussed this at length with pudl, before, and they seem to think it's still a good idea.

We had Departmental Security lockers on EfficiencyStation 3 and they were absolutely horrifying; literally nothing more than dead drops for traitors. Almost every round was marked with someone quickly emagging into an unsupervised checkpoint to nab a free set of Security gear - And these are in every department. 

It's too easy and the contents are crazy strong for how they are literally just behind 1 door/window in a department that probably gives no fucks about you running off with the locker. Officers should be gearing up in the Brig and going to their posts, not the other way around. You step out of the Brig ready for war, not hustle to your assigned department and try to gear up in the office there.

**Comment by CorruptComputer** [comment]
What if I coded a different locker for departmental security?

**Comment by SconesC** [comment]
What would it contain? If only generic Security supplies (Handcuffs, flashbangs, etc.), I'd rather just have them on the desk.

**Comment by CorruptComputer** [comment]
yeah, but with the locker it isn't just laying on the desk and someone who isn't a traitor cant just break the window to grab it.

**Comment by SconesC** [comment]
It really depends on what the supplies in question are.

**Comment by Cheridan** [comment]
@tgstation/commit-access I need you guys to sign off if you want this map in the repo or not.

**Comment by RemieRichards** [comment]
@Cheridan I don't care for the map tbh but I don't mind it's existence.

**Comment by pudl** [comment]
@sconesc You fool, i specifically was in favor of depsec lockers on eff3 because eff 3 only had 3 lockers in security. Having extras left behind helped.
Asstation has a lot of lockers, so it doesnt need depsec lockers.

**Comment by pudl** [comment]
Unless you wanna not be a cuck and encourage actual fun by giving traitors gear that isnt literally "SHOOT SIX TIMES UR DED"

**Comment by SconesC** [comment]
iirc you refused to add more lockers to security and said "just use depsec"

oh well, another map another time

**Comment by freerealestate** [comment]
Nice to see this gigantic fucker again.

**Comment by Dorsisdwarf** [comment]
CC, did you fix the whole "no solars will work" thing?

**Comment by CorruptComputer** [comment]
Yeah

**Comment by Metacide** [comment]
Looks fun, it good to merge?

**Comment by CorruptComputer** [comment]
Yeah, it is ready.

**Comment by CorruptComputer** [comment]
>mfw

**Comment by CorruptComputer** [comment]
@tgstation/commit-access

**Comment by d3athrow** [comment]
>solars in the roid

uwotm8

**Comment by CorruptComputer** [comment]
Yeah that was fixed

**Comment by palpatine213** [comment]
Could you add intercoms for the other two AI slots? Currently it seems that only the center AI can use the intercoms.

**Comment by CorruptComputer** [comment]
I changed the range so anyone in the room can use them.

**Comment by duncathan** [comment]
Wouldn't that be inconvenient for three AIs to have to fight over one intercom if they don't want the same frequency?

**Comment by CorruptComputer** [comment]
Yeah, and that was kind of the point. Either they learn to cooperate or they won't get anything done.

**Comment by palpatine213** [comment]
Oh, could you add a camera to the northeast solars on the AI core wall there? It seems kinda cheap that the AI can't see that avenue of attack at all since there's only 1 Rwall there.

**Comment by CorruptComputer** [comment]
Will do when I get home. Probably next week if all goes well.

**Comment by Actionb** [comment]
Atmos: Am I seeing this wrong or does the air mix (cyan pipes) have to go through the mix tank and its pipes (yellow) to finally get into distro loop (purple & blue)?
Aside from rendering the mix tank unusable for anything else, having the air for the station go through the mix pipes is a big no-no in my atmos book.
Suggestion: replace the manifold that connects cyan with green via a pump with a 4 way manifold, have cyan and purple meet up directly a little further south. It'd require a bit of pipe shuffling, but won't give experienced atmosians a heart attack.

**Comment by CorruptComputer** [comment]
I haven't gotten around to redoing atmos, but when I get home I will, most likely on Thursday.

**Comment by CorruptComputer** [comment]
Who touched the fire axe cabinet? Because not only do I need to redo the atmos room now, but I need to fix that.

**Comment by CorruptComputer** [comment]
All I have left is some fluff to the atmos room, but its done now.

**Comment by pudl** [comment]
show pic

**Comment by CorruptComputer** [comment]
This will be updated, but here it is as of now:
image

**Comment by Miauw62** [comment]
that is really big, but for atmos really big is generally a good thing.
you should add an external airlock and some rwalls instead of reinforced glass windows everywhere, so you can easily add pipes to space.

**Comment by CorruptComputer** [comment]
@Miauw62 Will do for the next update.

**Comment by duncathan** [comment]
Half of atmos' scrubbers have to be pumped into the waste loop separately. That's not really good. Maybe put the pump where you currently have the meter for the portable scrubbers.

**Comment by CorruptComputer** [comment]
@duncathan Will do for the next update.

**Comment by Razharas** [comment]
Consensus seem to be 'its ok'
Update your atmos and to the merge it goes

**Comment by Razharas** [comment]
@CorruptComputer

**Comment by CorruptComputer** [comment]
@Razharas

**Comment by CorruptComputer** [comment]
What the fuck, it compiled locally.

**Comment by CorruptComputer** [comment]
@Razharas Now its ready.

**Comment by Razharas** [comment]
I really hope i wont regret this

**Comment by freerealestate** [comment]
Finally

**Pull request merged**
