### PR TITLE
new dark gygax sprites (cool and edgy)

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds new dark gygax sprites, these are based on our current gygax sprites, while the old ones were based on the old gygax sprite
credit to vgstation i took them from there and modified the open sprite
for your viewing pleasure
image

## Why It's Good For The Game

we changed the gygax sprite ages ago so why not the dark gygax

## Changelog
:cl:
imageadd: new dark gygax sprites (cool and edgy)
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
https://www.youtube.com/watch?v=3s5o2uWhNe8

**Comment by Krysonism** [comment]
It is a little too dark for my tastes. maybe make the highlights brighter for a shiny black look?

**Comment by Tlaltecuhtli** [comment]
make lights animated

**Comment by Fikou** [comment]
> make lights animated

they are

**Comment by JoshAdamPowell** [comment]
those colours make it look quite culty, like a construct or something

**Pull request merged**
