### PR TITLE
Fixes hearing sounds in crit, that shouldn't be heard

### LINKED ISSUE #23297: you can fully hear the medibots voice lines but not the text while in crit
and that's just no way to be

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request
Closes https://github.com/tgstation/tgstation/issues/23297

## Why It's Good For The Game
Realistically if you are in critical condition you are barely conscious and shouldn't be able to hear the medibot screaming at you from across the room (and probably other sounds that are erroneously played)

## Changelog

:cl:
fix: You will no longer hear medibot voicelines whilst in crit.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Is this all crit or just hardcrit

**Comment by SuperNovaa41** [comment]
> Is this all crit or just hardcrit

hardcrit now.. softcrit wouldn't really make sense now that you mention it

**Comment by ExcessiveUseOfCobblestone** [comment]
im ok with either

**Comment by SuperNovaa41** [comment]
> im ok with either, lmk if u want to edit the pr

i don't really mind either way hardcrit makes more sense

**Pull request merged**
