### PR TITLE
Toolboxing for a cause 2.0 Working Test-merge

### PR DESCRIPTION
**Pull request by CitrusGender**
working branch for the toolboxing for a cause testmerge. All the maps and templates are on here and they're going to be tested before the actual competition.

DO NOT MERGE, CURRENTLY A WORK IN PROGRESS.

### CODE REVIEW

**Comment by Qustinnus** [comment]
>no mat datum toolboxes

citrus :^(

**Comment by MMMiracles** [comment]
matt datom toolboxes

**Comment by nervere** [comment]
"working" testmerge

**Comment by PKPenguin321** [comment]
I think it actually does compile? Travis is upset because of some map fuckery and a runtime in the shuttle subsystem as far as I can tell, but compile works fine which may be enough for a test merge. Idk though

**Comment by CitrusGender** [comment]
Yeah it compiles

**Comment by CitrusGender** [comment]
conflict is probably the .dme file. It will go away the closer we get to the event.

**Comment by CitrusGender** [comment]
fixed it

**Comment by CitrusGender** [comment]
should be ready.

**Comment by actioninja** [comment]
Toolbox is now over and went pretty smoothly from what I understand.

**Pull request closed without merging**
