### PR TITLE
Buffs turbine max rpm & output, more maintainence

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request

Increases max rpm for all turbine parts from 35000 -> 50000 & power rectifier from 0.25 -> 0.3. Below is the comparasion

1. Current Values
     - **Tier 1**: max rpm = 35000,   power_rectifier = 0.25, max output = 131 KW
     - **Tier 4**: max rpm = 550000, power_rectifier = 0.25, max output = 2 MW
2. New Values
     - **Tier 1**: max rpm = 50000,   power_rectifier = 0.3, max output = 225 KW
     - **Tier 4**: max rpm = 781250, power_rectifier = 0.3, max output = 3.51 MW

Depends on https://github.com/tgstation/tgstation/pull/88254 as it adds more general maintenance on top of it

## Why It's Good For The Game
https://github.com/tgstation/tgstation/issues/88231#issuecomment-2501796675 made me sad cause it is. How is it that a solar panel which requires 0 operation cost is able to generate the same amount of power as a tier 1 turbine which requires tons of gas & power(to pump gases from atmos into the incinerator, room requires power etc). We need more returns on our hard work.

Also with the recent power refactor changes, APC's & SMES now has batteries with 10x higher capacity so charging them takes a while & this turbine buff slightly helps in alleviating that

## Changelog
:cl:
balance: turbine now has higher max rpm & increased power output
code: further improved code for turbine
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
Depends on #88254 to display accurate values. Drafting till that gets merged

**Comment by Arturlang** [comment]
Not needed, it can be upgraded to insane values if need be.

**Comment by SyncIt21** [comment]
> Not really needed, it can be upgraded to insane values if need be.

Those insane values are a max 2MW stated in my PR body which isn't that insane at all. Please ready the description.  

Upgrading only makes it capable to withstand higher temps but does not boost output

**Comment by distributivgesetz** [comment]
this might have been an accidental nerf by #81579, but I am not sure what exactly caused it, because I do remember the turbine being decent. Also this will make non-SM syndie comms bases _much_ nicer to use since they arguably suffer the most right now because turbine power generation is pitiful.

**Comment by Arturlang** [comment]
@SyncIt21 Fair, sorry, I'm mistaken, didn't read it was for all turbine parts

**Comment by GuillaumePrata** [comment]
I would go even further on the tier 1 output, to like 1MW.

Power is binary, you either have it in abundance or there is none and the round is over.

If the SM explodes it is an instant shuttle call, having the turbine as a secondary engine to hold the station for a limited time would just be good for the game's meta at the moment.

"But muh power balance rework" This is a joke, I've been hearing this for the 4 years I play the game, and for 4 years the SM exploding ends the round, it is horrible for the new player experience to try and learn a game mechanic core to a job while the weight of 50+ people's fun is over your shoulders.

**Comment by Xander3359** [comment]
> Power is binary, you either have it in abundance or there is none and the round is over.
> "But muh power balance rework" This is a joke, I've been hearing this for the 4 years I play the game, and for 4 years the SM exploding ends the round, it is horrible for the new player experience to try and learn a game mechanic core to a job while the weight of 50+ people's fun is over your shoulders.

I honestly think it would be cool if there were alternative sources of power generation other than the SM/Turbine/Solars, and there being a way to sink excess power to gain something.

**Comment by MatrixOne500** [comment]
This is awesome, thank you so much!

**Comment by SyncIt21** [comment]
> I would go even further on the tier 1 output, to like 1MW.

Hi, Sorry for the late reply.

The idea was to boost the output of a tier 1 turbine(which is now 225 KW) to match the input rate of a tier 1 SMES which is 200KW so its perfectly balanced around that. Also 3 tier 4 SMES(with tier 4 capacitors installed) each having an input of 800 KW would benefit perfectly from 1 tier 4 turbine(which is now 3 MW) leaving behind a excess of 600 KW(3 MW - 2.4 MW[3 SMES * 800 KW]) for the station

I'm not disagreeing with your idea but the problem is boosting tier 1 output to 1 MW would also boost higher tier outputs exponentially so for tier 4 output will be 15 MW!!(Which is 15 times more than basic SM setup) and we don't want the turbine to surpass an SM at any tier. If a PR were made to increase the default input rate of an SMES then we can boost turbine output levels as well but until then i would have no justification to raise it to such high levels at tier 1 itself

As with the values i have tweaked now we would always have a little excess power to send to the station along with charging an SMES which seems balanced overall

**Pull request merged**
