### PR TITLE
Bread Sprite Update

### PR DESCRIPTION
**Pull request by AdipemDragon**
## About The Pull Request
This pull changes all bread sprites, their associated slice sprites and many bread-adjacent ones as well, like the sandwiches, hot-dogs, khachapuri and baguette.
image(1)
This pull also has a small code change to make the spider bread use the spider bread slice instead of the xeno one.

## Why It's Good For The Game
The old bread sprites baffled many; the breads & slices, beyond quick palette changes, weren't distinct in the slightest. I hope to change that with this pull, along with the other sprites.

## Changelog
:cl:

imageadd: Cooks have become better at baking breads.
fix: Spiderbread slice is now visually distinct from the Xenobread one.

/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
me when spider bread
image

**Comment by Low3** [comment]
Okay this is very nice. Love the aesthetic.

**Comment by Pugie** [comment]
moustache bread looks pathetic

**Comment by Livrah** [comment]
I like it. Exept new baguette, no soul.

**Comment by AdipemDragon** [comment]
image
@Livrah @Pugie how about something more like this then?

**Comment by Qustinnus** [comment]
Could you show me how custom bread (both sandwich and normal bread) look now please? :)

**Comment by notdonte** [comment]
> Could you show me how custom bread (both sandwich and normal bread) look now please? :)

it's the loaf with the blue goo inside of it, and custom sandwiches are below regular bread.

**Comment by Farquaar** [comment]
These sprites are phenomenal. Some of them look like they came straight off a bakery shelf.

**Comment by ShibaInuLord** [comment]
my soul!!! looks great though

**Comment by necromanceranne** [comment]
The bread will now actually look like bread and not...whatever it was that they were before.

**Comment by Iatots** [comment]
Butterdog looks like a bananadog, meatbread looks like cocoa swirl bread. Good resprite on the moustache sandwich.
Everything else is great.

**Comment by AdipemDragon** [comment]
> Butterdog looks like a bananadog, meatbread looks like cocoa swirl bread. 

image
and actual meatbread is just Like That

**Comment by interestingusernam3** [comment]
>The bread will now actually look like bread and not...whatever it was that they were before.

Old bread looked like poppy seed rolls but dyuers coloures.

**Comment by Pugie** [comment]
> image
> @Livrah @Pugie how about something more like this then?

good

**Comment by Serxule** [comment]
bread is finally bread instead of, rolled cardboard with a giant crayon

**Comment by Iamgoofball** [comment]
how do modular sandwiches look with this?

**Comment by carshalash** [comment]
Bottom left of the preview image.

**Comment by Iamgoofball** [comment]
nice

**Comment by ATH1909** [comment]
these (and the old sprites) are a bit, uh, big, no?

**Comment by AdipemDragon** [comment]
> these (and the old sprites) are a bit, uh, big, no?

well yeah, food items have always been sorta comically large, so i just tried to keep the size as is (even though yeah i've made some things larger, especially the khachapuri and the baguette)

**Comment by Low3** [comment]
BIG, detailed and tasty looking food is my fetish, keep it huge.

**Comment by Coastfront** [comment]
I can feel the soul leaks

**Pull request merged**
