### PR TITLE
Grinder won't show you reagents if you can't see reagents

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
balance: If you aren't wearing googles that allow you to check reagents in a beaker, you can't see reagents inside a grinder. AIs, borgs and observers and can always see the reagents.
balance: You need to be next to the grinder to see its contents, unless you are AI, borg or observer.
/:cl:

Shouldn't matter for bartenders and chemistry as they spawn with googles.
Makes googles have the utility they should have (seeing reagents you couldn't see with naked eye).

### CODE REVIEW

**Comment by lolman360** [comment]
grinders always have let you see their contents, why's it being changed all of a sudden?

**Comment by Ratvar** [comment]
Yes, no more grinding a pill to see if it's poison or medication!
...won't people just use bar dispenser instead?

**Comment by nicbn** [comment]
That's out of PR scope

**Comment by Barhandar** [comment]
Welcome to "adding radials to grinder was a bad idea and leads to bad changes like this".

Have you thought that maybe the grinder has _integrated display_?

**Comment by MACIEKBAKI** [comment]
-1, radials were a bad idea, dont nerf it more then you've already done.

**Comment by nicbn** [comment]
Yes the grinder currently says it has a integrated display and I'm changing this

**Comment by AdamElTablawy** [comment]
It's not a super terrible nerf, just a change nobody likes because it sucks. Grinder has an integrated menu yet you're removing it for 'consistency'-there is consistency in using a machine to see what is inside a beaker. This is par for the course for chemistry machines or anything else that deals with chemicals in any way.

People don't like this because OH MY GOD TERRIBLE NERF it's just removing a feature for no reason

**Comment by BebeYoshi** [comment]
You can also check the contents with chemaster and anything like that, even botany and the cook have one, so I don't think it would be a nerf honestly, not that I agree with the PR, though.

**Comment by MACIEKBAKI** [comment]
personally I agree with "Need to be close to it to read the display" but don't agree with the goggles stuff.

**Comment by Ratvar** [comment]
Maybe glasses are just useless.

**Comment by Cyprex** [comment]
>Also all jobs that use grinders, except for chefs, spawn with googles.
Do botanists spawn with googles? What about virologists? Also, I'm interpreting "spawn with googles" as them spawning on station with googles on their body, not having googles, which can run out, be stolen, etc. in their department/work area

**Comment by nicbn** [comment]
Virologists will only use them to grind plasma, therefore they already know the products they will get.
Botanists don't use the grinder so often. Even then, we can add googles from them later on if that turns out to be a problem.

Also, if anyone wants to mess with chemistry and see reagents without being a job that has the googles round-start, they could just print some googles in the nearest lathe.

**Comment by Cyprex** [comment]
Are googles really autolathe manufacturable?
Also, virology recipes use silver, gold and uranium as well.

**Comment by nicbn** [comment]
Ok but all of these are a single product so there's no real need to check the reagents
Pretty sure the googles can be manufacturated at protolathe, but if they aren't I can change that later

**Comment by PKPenguin321** [comment]
In the future please put your reasoning for changes in the OP
That said, what's the reasoning for this?

**Comment by nicbn** [comment]
Makes googles have the utility they should have (seeing reagents you couldn't see at naked eye).

**Comment by YakumoChen** [comment]
So effectively you just want to force people to wear shitty glasses

Keep in mind that most jobs that get a grinder also get a PDA program to see chem contents on any item without glasses

**Comment by optimumtact** [comment]
for the reasons stated.

**Pull request closed without merging**
