### PR TITLE
Revert "SWAT vest !!!DOES NOT BUFF SWAT!!!"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#25236

Overpowered vest and contributes to security armour creep

### CODE REVIEW

**Comment by Bawhoppen** [comment]
but security doesn't get it and also its not overpowered and also the other reasons and also freeze

**Comment by Razharas** [comment]
I think sec doesnt have it though?
Its mob loot and space loot only

**Comment by optimumtact** [comment]
Removals are not blocked during the freeze

**Comment by optimumtact** [comment]
armor = list(melee = 40, bullet = 30, laser = 30,energy = 30, bomb = 50, bio = 90, rad = 20, fire = 50, acid = 50)

**Comment by Razharas** [comment]
>security doesn't get it

**Comment by Bawhoppen** [comment]
it isn't, look at the numbers

**Comment by Bawhoppen** [comment]
they already get the helm with the exact same stats, and a normal vest with just slightly lower stats

**Comment by KorPhaeron** [comment]
dude armour lmao

**Comment by Xhuis** [comment]
You guys are hopeless I swear

**Comment by Grazyn** [comment]
> Removals are not blocked during the freeze

I'm predicting this is gonna hurt a lot

**Comment by jughu** [comment]
@optiumtact he even nerfed it 🤔

**Pull request merged**
