### PR TITLE
Renames regen. stasis, adds blood regeneration to fleshmend and feign death

### PR DESCRIPTION
**Pull request by ghost**
Regenerative stasis renamed to revival stasis to properly describe what it does. It's important because people get confused between this and fleshmend, apparently.

Added blood healing to fleshmend and regenerative stasis. WTB better proc for this, but it will do for now.

### CODE REVIEW

**Comment by Lumipharon** [comment]
It's not really feigning death, if you already died, but eh.
I remember when I first played ling, I was more confused by the fact I became conscious, before I pressed (or knew I had to press) the regen button, after the wait.

**Comment by RemieRichards** [comment]
Don't rename Regenerative Stasis.

**Comment by paprka** [comment]
Any particular reason

It's even called fakedeath

**Comment by RemieRichards** [comment]
@paprka that's just a flag that's applied and removed at the end.
I'd bet the majority of uses of an ability that brings you back from the dead, is to bring you back from the dead. if a ling fake's their death they just get dragged to the gibber/crematorium so it seems like a less than solid tactic.

**Comment by dannno** [comment]
The last few times I've actually seen it used to feign death was by people who did it by accident
If you rename it to feign death people are going to get confused and not realise that it can bring them back from the dead probably. Or something. There's just probably a better name.

**Comment by paprka** [comment]
/obj/effect/proc_holder/changeling/fakedeath

**Comment by RemieRichards** [comment]
oh look the proc name is the same as a flag that's applied.

Did you also know the microwave's cooking proc is called Wzhwzh()? Should the microwave be renamed the Wzhwzh machine? (It should but I digress)

Tad sarcastic of me, but you get the point. The name displayed to the player (Up until now, "Regenerative stasis") is more important than the proc name.

**Comment by dannno** [comment]
yeah great pap but that's not what ANYONE knows or refers to it by.

**Comment by paprka** [comment]
Regenerative stasis is getting confused with fleshmend, that's all, but I guess it gives them a big warning about faking your death so it's not so important. I'll add a "You won't be able to revive for x seconds!" to it as well so people really get the idea that it knocks you out for a while.

**Comment by dannno** [comment]
Ech, it could do with a renaming but at the same time "regenerative stasis" is REALLY accurately describing the main function. It's a mistake most people will only make once I guess, no big d.

**Comment by phil235** [comment]
Both names don't describe its function accurately tbh.

**Comment by dannno** [comment]
Maybe "Revival Stasis" would be better? Indicates both that it revives you from death and that it takes time.

**Comment by Iamgoofball** [comment]
revival stasis sounds better imo change it to that

**Comment by paprka** [comment]
Alright.

**Comment by paprka** [comment]
Done

**Comment by ExplosiveCrate** [comment]
Should probably update the PR description to avoid confusion .

**Pull request merged**
