### PR TITLE
Adds Medical HUDGlasses

### PR DESCRIPTION
**Pull request by AnonymousNow**
Adds sunglasses with a built-in medical HUD. Functions as you would expect them to, tested locally with no issues, comes in a stylish blue.

I've wanted this glasses for literally years - longer than many to most of the players on this server have even been around - but it's now that I know how to add them. This simply adds them to the code so that they can be spawned only by admins, for future features and testing - the intention is to add them to medbay eventually.

With security's powercreep, I felt it was important to add a counter of sorts, though a pair of these in medbay would be a drop in the ocean compared to what they get. 

:cl: 
add: Added Medical HUD Sunglasses. Not currently available on-station, unless you can convince Centcom to send you a pair.
/:cl:

sunhudmed

### CODE REVIEW

**Comment by cedarbridge** [comment]
Is there  a specific reason they need to be sunglasses?

**Comment by AnonymousNow** [comment]
@cedarbridge The long answer is it was intended to be a CMO's last line of defence and only means of reliably keeping their HUD back when telebatons and the HUD implanter weren't a thing, as well as a fashion item. Now it's primarily a fashion item and also a possible dynamic changer in medbay, as one person on the medbay staff _may_ be harder to convert _if_ they choose to use the new glasses, _if_ they're placed on the map in medbay. Either way it's intended to keep up with the gorillion HUDglasses that sec gets.

The short answer is: I want to wear blue glasses. Even only as an ERT Medical Officer.

**Comment by Mindustry** [comment]
Pic? Sounds neat and wouldn't mind bugging science to make me a pair

**Comment by jughu** [comment]
>be cmo
>use the medical hud implanter
>walk to brig
>request sunglasses(normal one)
>get it
>mission complete

**Comment by XDTM** [comment]
Probably best to not put them in science.

**Comment by jughu** [comment]
Why cant we just combine huds with sunglasses 🤔

**Comment by AnonymousNow** [comment]
@Mindustry OH SHIT PICTURES THAT'D MAKE SENSE.

**Comment by optimumtact** [comment]
I don't like things that add flash protection to other eyewear as most of them were merged with teh promise that one of the tradeoffs would be giving up flash protection so it's :-1: from me

**Comment by FantasticFwoosh** [comment]
Hey man, you could probably give this it ERT members to save implant headspace, and the CMO's self implanter is good but one use. This is obviously superior because CMO's are not really convertible by flashing and as soon as the CMO dies the implant is lost.

I like it's recognizable blue tint, all & all i support this being a implant replacement for CMO.

> Replacing the self-implanter for CMO would also stop people being shitty & stealing it (HOS's, captains & greyshirts) to stack ontop of sechud sunglasses rather than go get a late-game implant from robo.

**Comment by jughu** [comment]
Ert doesnt need it because their hardsuit already protects them?
Thats atleast what i thought 🤔
I maybe add it in a space ruin hospital as loot

**Comment by Cyberboss** [comment]
@AnonymousNow 

:cl:
add: blah blah blah
/:cl:

**Comment by KingPhilipIII** [comment]
They've had these for a while on Para. The Blueshield gets a pair.

I personally support the CMO only idea. Make them spawn with it. The Heads should be somewhat tough to kill, being heads and all, but otherwise medical personnel shouldn't have flash protection. Sec gets it cause of their flashers.

**Comment by ExcessiveUseOfCobblestone** [comment]
Maybe change these into glasses, not *sun*glasses?

**Comment by Cyberboss** [comment]
That makes them do different than wearable HUDs then

**Comment by ExcessiveUseOfCobblestone** [comment]
That's the point of vanity items

**Comment by RandomMarine** [comment]
>bio resistant
>mechanic

o I'm laffin

**Comment by Repukan** [comment]
Seems unnecessary since medic erts get protection from their hardsuit and CMOS can just wear sunglasses after implanting themselves.

**Comment by anconfuzedrock** [comment]
if it doesn't add it to any maps, whats the problem?

**Comment by Mooseykins** [comment]
yeah but it looks cool 👍

**Comment by jughu** [comment]
>it looks cool

Its litteraly sunglasses with a blue pixel in it

**Comment by Mooseykins** [comment]
what a cool pixel

**Comment by AnonymousNow** [comment]
TBF, it's blue, so it's inherently cooler than red.

**Comment by ExcessiveUseOfCobblestone** [comment]
Oh wait why not give it reagent scan so it's a MedHud that doubles as a reagent viewer. Mechanical that isn't hardcounter to a gamemode!

**Comment by RandomMarine** [comment]
Just sayin' that bio armor does literally nothing.

The only reason why it's even still there is that any attempt to remove the unused values is a time-consuming effort that's doomed to perish in a sea of merge conflicts.

**Comment by Kromgar** [comment]
image

POWERCREPE!

**Comment by BeeSting12** [comment]
science shades next?

**Comment by ExcessiveUseOfCobblestone** [comment]
@RandomMarine time to add bio guns that do only bio damage so you need bio armour

**Comment by Emilc4h** [comment]
I'm biased towards the standard MediHuD myself, but those are kinda neat. The plus side to just implanting yourself and getting some normal sunglasses is you can pretend you're JC Denton, tbh.

@Kromgar unrelated but damn crepes look tasty as fuck

**Comment by RandomMarine** [comment]
@Emilc4h If anyone wants to pretend to be JC then they'll need these glasses for the blue pixel.

**Comment by FantasticFwoosh** [comment]
@BeeSting12 hopefully some pitch black shades & a white cane so i don't have to be subject to seeing the rampant horrible abuse within my department caused by moonlighting & naked lizards.

**Comment by dannno** [comment]
needless

**Comment by AnonymousNow** [comment]
Updated for some visual tweaks. Still want these badly.

**Comment by Repukan** [comment]
I think my main peeve with this is that it's basically buffing a role unequally. Unless other heads had something equivalent added at the same time, then it seems like favoritism to your main role.

**Comment by AnonymousNow** [comment]
@Repukan That's why I suggested that it isn't given to the CMO, but to medbay (anyone could take it with med storage access). Or to Medical EMTs.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's internal jetpacks all over again PANIC

**Comment by jughu** [comment]
>anyone in medbay can take it
>rev
>flashes buffed
>flashes do a reasonable stun
>rip cmo

**Comment by AnonymousNow** [comment]
Yes, I'm hoping that the decision that got a department full of HUDglasses a jetpack built into their head's hardsuit (though not the other two hardsuits in the department) will help facilitate the addition of a single pair of HUDglasses to the department who got a single hardsuit some time after the previously stated department.

I freely admit, if I knew how to code fully, I'd be the Steelpoint of Medbay. But as it stands, I'm just pushing for small, inoffensive additions.

**Comment by optimumtact** [comment]
@tgstation/commit-access if nobody else decides what to do with this in two days I'm going to close it because personally I don't think it's a good change

**Comment by AnonymousNow** [comment]
Personally? It's not even a change, it's an addition that doesn't add anything to the ingame maps. It puts it into the code where it can be used in the future.

Tell me it's overpowered or something, with a straight face. Look at security's situation and tell me that even just adding these to the code would be a bad idea.

**Comment by Jordie0608** [comment]
Well they're not accessible by players so their mixmaxiness doesn't matter until the inevitable future PR where someone adds them to the CMO's default equipment; And then his locker, then all medstaff and finally Runtime.

**Comment by optimumtact** [comment]
Straightest face I can find to tell you that they're overpowred and adding them to the code is a bad idea

**Comment by AnonymousNow** [comment]
I don't see the slippery slope. It's not happened with medbay. Another department, yes, but medbay gets its good stuff rarely. I'd mention specific examples, but I don't want them to be removed. 

I just don't see how these can be overpowered. It's a nonsensical statement in the context of this server.

**Comment by Militaires** [comment]
>With security's powercreep, I felt it was important to add a counter of sorts, though a pair of these in medbay would be a drop in the ocean compared to what they get.

so you're responding to powercreep with more powercreep

why do you think every head has their own fucking personal hardsuit

**Comment by optimumtact** [comment]
REEEEEEEEEEEEEEEEEEEEE dont' remind me

**Comment by AnonymousNow** [comment]
I like the head hardsuits. But no matter.

If this is powercreep, then it's an agonisingly slow crawl compared to another department.

**Comment by AnonymousNow** [comment]
ALRIGHT
NOBODY PANIC
I TRIED TO SYNC ALL THE CONTENT FROM THE PAST WEEK FROM THE MAIN REPOSITORY TO MY FORK
AND NOW IT'S MENTIONING IT HERE AND RUNNING A TRAVIS BUILD LIKE I WAS CHANGING EVERYTHING FOREVER
THIS SHOULD ONLY CHANGE FIVE FILES
DON'T PANIC

God, putting content into the game is pain enough without knowledge of the bloody code. It's going to be grim when my next PR goes up.

**Comment by RemieRichards** [comment]
@AnonymousNow 
>  Files changed 5 

What you're looking at is a merge commit, and they ALL look like that, github knows not to show them as there's no difference between those changed files (because you're updating YOUR repo based on THIS repo, so of course there's no diff)

It's fine, but cute this spooked you.

**Comment by AnonymousNow** [comment]
_(you're updating YOUR repo based on THIS repo, so of course there's no diff)_

Good, good, that's what I intended. Guess it has to recheck the files, which is why Travis is taking so long.

I'm really living up to this "grandpa using the internet for the first time" thing I've got going on here. I think I'll keep off my next experiment until this one goes somewhere, though I have the files on standby now.

**Comment by AnturK** [comment]
Build completed on travis so not sure what's going on with github integration.

**Comment by lzimann** [comment]
This is not even powercreep, it's more of a convenience creep(which is also a big issue by itself).

**Comment by jughu** [comment]
Bluepixel wins everytime

**Comment by AnonymousNow** [comment]
@AnturK Thanks much.

**Pull request merged**
