### PR TITLE
Morgue tray sanity check + code improvement

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Adds a sanity check to the morgue tray.
Somehow this runtimed in a live game, there was a lot going on in the morgue when it happened so it's possible it has something to do with destruction in the same tick as an open?

Also some 1 -> TRUE define replacements

### CODE REVIEW

**Comment by optimumtact** [comment]
I don't think swallowing the runtime helps

**Comment by actioninja** [comment]
I'm not even entirely sure what caused it to runtime, and it only happened once. There's a bunch of other safety checks elsewhere so the only thing I can think of that would cause it is destruction in between the checks and the actual proc call, which I'm not entirely sure if that's a valid usecase we should be considering or not.

**Comment by optimumtact** [comment]
yes, so just blindly swallowing the runtime in future seems silly, just leave it the logs so someone can trace down the real issue.

**Comment by actioninja** [comment]
Fair point, I only ever saw it once and didn't see it again in successive rounds.

**Pull request closed without merging**
