### PR TITLE
Diagnostic HUDs can see shocked doors

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Diagnostic HUDs can now see if airlocks are shocked.
/:cl:

Example gif: https://i.gyazo.com/8911bae7f3ab21ed9a1cb3700e3763bc.mp4

## Why
Adds something to diagnostic HUDs, which are commonly considered the least useful.
Most of all, it allows AIs and borgs to track which doors they shocked, so rogue AIs that get unrogued can seek out every shocked door without having to open a panel every time, and similar situations.

### Other changes
Airlocks now have a set_electrified proc, so it will update the HUD. Timed electrifications only call this on the first and last tick. Those should probably get refactored, but i'm not sure how to go about it right now.

### CODE REVIEW

**Comment by GunHog** [comment]
Terrible sprite, but I guess a proper spriter will improve on it!

**Comment by XDTM** [comment]
I picked the EMP implant sprite, so i'm blaming someone else for it

**Comment by GunHog** [comment]
Oh, this had been part of my original design, but was gutted later. If you made the sprite smaller, you could add things like timer, lights, and safety as well, since those do not ever show on the airlock's sprite.

**Comment by XDTM** [comment]
Could end up cluttered, though.

**Comment by juanototo2** [comment]
I don't even know how to respond to this other than a combination of "Thanks for the powercreep, my roboticist self will love this" and

>buffing anti-traitor AI roboticist shittery with the 50000000000000000 flashes and one single doorhack to the robotics console PLUS ion carbines from R&D and a unslaved engiborg with a posibrain and told to "Go murder this doomsday. Oh, and go get me some snacks."

**Pull request merged**
