### PR TITLE
Adds swapping disks to the plantmanipulator

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]:  

:cl: Dax Dupont
add: You can now swap disks in the plant manipulator.
/:cl:

[why]: Small QoL improvement, allows you to swap disks way faster.

### CODE REVIEW

**Comment by Kromgar** [comment]
YEEEEEEEEEEEEEES

**Comment by BebeYoshi** [comment]
IMPORTANT PR

**Comment by ExcessiveUseOfCobblestone** [comment]
lovely qol

**Comment by JJRcop** [comment]
Don't anyone get any ideas about letting guns do this

**Review by SpaceManiac — DISMISSED** [review]

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Seems like if you have something in your other hand the ejected disk goes to the floor rather than to your empty hand, can that be fixed?

**Comment by DaxDupont** [comment]
Maybe a forcemove to the location of it fails but I might edit put in hands

**Comment by DaxDupont** [comment]
Right so put_in_hands forcemoves it so I don't need to do that before put in hands.

This will put the disk back if it fails to put it in inhand

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Looks like it still puts the disk on the ground, though on top of the machine rather than under the player's feet.

Have you looked at how portable atmos canisters allow hot-swapping tanks? You might be able to follow the same pattern.

**Comment by DaxDupont** [comment]
It's supposed to eject regardless when hands are full, same behavior exists
for beakers and what not if the hand is full. It's also the old behavior.
This is behavior that you want if you're switching and using multiple disks
in sequence.

**Comment by DaxDupont** [comment]
Very much intended behavior, though dropping it under the person was a bad idea. It now follows the old behavior it can't put it in hand.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
