### PR TITLE
Adds more medipens to the medipen refiller

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Adds mining pens and meth pens as things you can refill from the medipen refiller
Regular pen requires Libital
Luxury pen requires Penthrite
Meth pens requires meth
Mutadone pens requires mutadone
Invisibility pens requires saturnX

## Why It's Good For The Game

This is a criminally underused machine that is already hidden by being behind research and construction in the department least likely to build machines, giving them a pretty minor but cool interaction with Mining that could save them some mining points if they put the work in sounds cool.

Regular medipen takes Libital but it also gains epinephrine, aiuri and leporazine, which is fine because these are all just as easy to get than Libital anyways (except for Epinephrine, but it's not a major player here, even in epipens it's used for the formal more) and has the low pressure requirement making it not worthwhile for doctors to abuse.
Luxury medipens takes Penthrite, so even if it makes omnizine and some others, the penthrite alone, being hard to make, requiring Lavaland geysers, AND having the low-pressure on top of it, makes it nice for miners to have. Chemists who goes out of their way to do plunging stuff on lavaland, bluespaces it up, and make a well optimized factory, on top of having to get some pens to refill, makes it a long and worthwhile process for a good item.

For the meth pens, it was added as a nukie only item, and I don't really see why you shouldn't be able to refill them.
Mutadone medipens is just straight up mutadone with nothing extra added on top, so I don't see why it shouldn't be refillable.

## Changelog

:cl:
add: A bunch of new medipens you can refill with the medipen refiller (survival/luxury/mutadone/saturnx/meth)
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
honestly with how little people even know of its existence. I'm half tempted to make it a shift start machine. So that way when people still ignore it I'll have a case to remove it entirely

**Comment by Zergspower** [comment]
tbh it'd get used more if you could create your own medipens - the refiller always seemed so restrictive

**Comment by GuillaumePrata** [comment]
> honestly with how little people even know of its existence. I'm half tempted to make it a shift start machine

This is something I wanted for miners for a long time, new players end up using a lot of their points on new pens while experienced players cruise to the late game gear they want.

If every time a new miner comes back up they get a "free" pen, it would likely decrease the death of new miners, specially on lower pop rounds where they are a lot more important and less likely to be saved.

**Comment by Floofies** [comment]
> tbh it'd get used more if you could create your own medipens - the refiller always seemed so restrictive

I am implementing custom manufacturable medipens via a bounty right now, so this will be a reality soon!

**Comment by JohnFulpWillard** [comment]
Note that per https://github.com/tgstation/tgstation/pull/29139 it's fully intended that medipens cannot be refilled with any custom reagent because of it's ability to pierce everything. If you want to see it added then you'll probably be best off talking with the original creator (goof)

**Comment by MrMelbert** [comment]
> tbh it'd get used more if you could create your own medipens - the refiller always seemed so restrictive

We really don't want custom medipens because then it's basically a Build Your Own Sleepypen. 

Or well, the only way I can see it flying is if custom medipens had an obnoxiously long do-after associated.

**Review by MrMelbert — APPROVED** [review]
I don't even like the fact that the medipen refiller can magically create chemicals - 

I would much prefer if it actually worked as you would expect (put the required chems in, and you get a filled medipen out) 

...but changing that would require we made some chems (cough, Sanguirite) obtainable. (Or maybe we allow it to accept substitutes like pulped banana?)

But in any case this is probably fine.

**Pull request merged**
