### PR TITLE
Are you doing your part? - Marine ert maintenance 2022

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
It's almost been a year since I last messed with marine balance and sprites, and this simply cannot stand.

The short version of this is that I watched starship troopers and had a small bit of inspiration. As a result, new armor sprites, new gear balance.

From left to right, Commander, Trooper, Engineer, Medic
image

Now that same everything with masks and clothes adjusted/moved out of the way
image

### Long version:

Changes to all of the classes - I realized that atmos problems aren't really as big an issue if you just give them an oxygen tank and not much else, so the total space-proofing of their armor has been removed. The helmets are once again open-face, and you can even roll the sleeves up on your jumpsuit now (critical feature).

**The Commander -**

The commander has lost his riot shield in exchange for a backpack, which contains his internals box, a medkit, a megaphone, and two bricks of c4. Visually, they get a functionally identical, but different looking ammo belt, as well as a new generalized uniform with no special markings on it.

**The Trooper -** 

No longer classified as the 'heavy' as this appeared to cause some confusion, and unlike the original version they aren't that much heavier than the others. They've lost their glasses, and like the commander have a new jumpsuit that lacks special marks, oorah!

**The Engineer -** 

Equipment wise, the engineer hasn't changed all that much. The only noticeable difference is that they too seem to have misplaced their glasses, and have been using welding goggles instead.

**The Medic -**

The medic is the class that has gotten the most changes, mainly because they were practically useless at their main job of, well, being a medic before. Because I refuse to trust the future equivalent of the US marines with a medbeam, they have gotten simply upgraded equipment as follows:
image
Their belt has been replaced with one that holds a health analyzer, basic surgery tools for fixing embeds or tending wounds, and a combat injector for when you don't have time for that.
image
Alongside the standard internals box, the medic has two medkits, one standard and one advanced, along with a defib belt and rollerbed, for those times when drugs can't fix the problems at hand.

## Why It's Good For The Game
When I first made marines they were meant to be a sort of middle ground between sending a swarm of interns, and an ert with full suits and advanced tools. The first iteration filled that goal pretty well, but they strayed away from it when I made the second version. Turns out that with spaceproof and seven total magazines of ammo for most of the members, they end up being stronger than the average ert, codes green through like, maybe amber?
I also realized that they didn't really need to be spaceproof in most instances, and that a simple oxygen tank and mask would let them survive most cases that I found them getting entirely destroyed by. With a bit less advanced gear than before, and better means of recovering the wounded and dead after battles, the marines might once again be able to return to their intended role in the ert list.
Besides, open front helmets y'know?
image

## Changelog

:cl:
balance: the marine ert is both no longer spaceproof, and has had equipment changed around
imageadd: updated and new sprites for marine equipment
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
image

I swear bro I've got two other prs open that improve my gbp don't kill me

**Comment by Striders13** [comment]
Don't like removing of spaceproofing. When I send erts the station is totally hull breached everywhere, so they'll just freeze to death in arrivals or be forced to wear lame space suits.

**Comment by Paxilmaniac** [comment]
> Don't like removing of spaceproofing. When I send erts the station is totally hull breached everywhere, so they'll just freeze to death in arrivals or be forced to wear lame space suits.

If the station is spaced don't send marines, I don't know what else to tell you

**Comment by blackdav123** [comment]
at the very least give their suits cold resistance or heaters or something because taking two steps out of the ship and being frozen to death before the only guy with a crowbar can step to the front is awful

**Comment by Striders13** [comment]
> If the station is spaced don't send marines, I don't know what else to tell you

Why would I ever send marines then? What situation warrants weaponry above interns while station is not drilled with holes?

Blobs make breaches, nukies make breaches, space dragons are in space, but most importantly, xenos make breaches. Marines vs xenos is cool and thematic and this makes em a bad pick in this situation.

**Comment by ilikesaying** [comment]
Terragov Marines never fought in a vacuum, they don't know how to as a result.

**Comment by Paxilmaniac** [comment]
finally someone gets it

**Pull request closed without merging**
