### PR TITLE
Refactors leather with crafting, removed bio-generator designs + adds craftable muzzles

### PR DESCRIPTION
**Pull request by FantasticFwoosh**
:cl: Moonlighting Mac says
tweak: After a recent trade fair, employees have took it upon themselves to learn how to craft leather objects out of finished leather sheets, for novices they are pretty good at it! Try it yourself!
add: Muzzles to silence people are now craftable out of leather sheets.
del: You can no longer print off designs from a bio-generator that can now be crafted out of leather sheets.
tweak: Complete sheets of leather can be printed from the bio-generator for 150 biomass to accommodate for a loss of designs.
experiment: Specialist objects from the leather & cloth category bio-generator category were not removed as to encourage interdepartmental interaction & balance.
/:cl:

I felt that the leather stack item was neglected coding wise and far too much based within the biogenerator for common domestic objects such as simple wallets. It also allows universal low-tech crafting with leather as long as you go through the fundamental basis of wetting via a sink & drying (requiring power or surrounding temperatures) as a prerequisite to skinning wild animals for objects.

The muzzle object also included is a nice accompaniment to the biogenerators cloth production to make blindfolds as to create a full set. We might yet get some peace & quiet from WGW readers and other noisy delinquents.

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
Make the muzzle only usable on lizards because they have a snout that fits the muzzle.

**Comment by FantasticFwoosh** [comment]
Haha almost considered it but no.

**Comment by Iamgoofball** [comment]
i see what this is

this is another PR to buff assistant lone wolfs who dont want to rely on others

instead of having to go back to botany when they need stuff they just want to break in, print 50 sheets, and fuck off no interaction

**Comment by FantasticFwoosh** [comment]
If they wanted to play lone wolf, they'd skin animals using a sharp knife themselves and then build a drying rack in the garden, wet & dry the leather there without any botany interaction at all.

Botany already does a over the counter service for cloth & objects, which ideally i want to create a "hard" production line to compliment the "easy" biogenerator. Probably including a botany plant like cotton (collectively thanking IRC for input since its a common idea)

**Comment by swindly** [comment]
It's about time leather gets used.

**Comment by Iamgoofball** [comment]
Listen buddy I think you got the wrong door

**Comment by octareenroon91** [comment]
Please can we get manufacture of a versatile belt (7 slots, max small-size)?

**Comment by optimumtact** [comment]
Leather club's three blocks down @Iamgoofball

**Comment by jughu** [comment]
Do we have fluffy handcuffs?

**Comment by FantasticFwoosh** [comment]
Save the fluffy handcuffs when a full tiger fur pimp suit is in the game, then i can be the boss of this nightclub.

**Review by Cyberboss — APPROVED** [review]

**Comment by jughu** [comment]
You mean muzzles gimp suits for the kinky survivors?

**Comment by FantasticFwoosh** [comment]
Whatever rocks your boat i suppose.

**Comment by octareenroon91** [comment]
>You mean muzzles gimp suits for the kinky survivors?

What, are you too good for black gloves and jumpsuits?

**Pull request merged**
