### PR TITLE
Too much brain damage is now deadly

### PR DESCRIPTION
**Pull request by ghost**
Brain damage now goes up to 200.

**Starting at 125 brain damage**
* You fall down
* You slowly suffocate

**Starting at 190 brain damage**
25% to die every life tick.

Neurotoxin and brainrot are not strengthed, as they are both now unable to reach the fatal 125-190 limit.

:cl: More Robust Than You
add: Too much brain damage is now deadly
tweak: Brain damage can now go up to 200
tweak: Brainrot stops dealing brain damage at 120 brain damage
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by lordpidey** [comment]
Be sure to put a cap on bible and employment contract brain damage then.  There was a problem on paradise in a testmerge of devil, where lawyers would beat people to death with their employment contract.

Hilarious, but we don't want that.

**Comment by RandomMarine** [comment]
Reagents aside, how many uncapped sources of brainloss would that leave?

**Comment by kevinz000** [comment]
the answer is too much. :-1:

**Comment by Armhulen** [comment]
no, we do want that. that sounds fucking awesome for traitor chaplain to make people die with his retardbible

**Comment by nicbn** [comment]
Just remove the brain damage from the bible, it is not op with our medical system.

**Comment by GuyonBroadway** [comment]
Suggested compromise, brain damage will give you clumisiness and toruettes at a high enough level.

**Comment by PopNotes** [comment]
Remove the death part and just make the player constantly trip over themselves, scream randomly and lose the ability to use items/weapons the higher brain damage you have.

**Comment by KorPhaeron** [comment]
Didnt this get rejected

**Comment by ShadowDeath6** [comment]
I think it'd be better to go the opposite route in regards to what's lethal. Brainrot is a disease that damages your brain, it would make sense that you would die from it if left untreated. Same with Neurotoxin, it's a chemical that damages your brain. 
Likewise, I don't think things like chaplain bibles or employment papers should be lethal since the point of the brain damage caused is a joke, not a balancing point.

**Comment by monkeyboyinc** [comment]
Whatever solution is found, I'd rather it not include removing the brain damage from the bible. I love smacking shitters who fuck up the church with the bible.

**Comment by lordpidey** [comment]
> Likewise, I don't think things like chaplain bibles or employment papers should be lethal since the point of the brain damage caused is a joke, not a balancing point.

So... the damage on the employment contract actually IS a balancing point, in that it prevents a really stupid strategy.

If you have too much brain damage, you can't sign an infernal contract, so the brain damage from the employment contract puts a cap on how many times you can sell your soul to the same devil in a row by abusing the contract system.

**Pull request closed without merging**
