### PR TITLE
NEVER BEFORE SEEN 4 DIRECTION CRATE SPRITES from Cornelius Bogfrollup Fitzgerald!

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Crates (At least, nearly all of them. Not laundry or necropolis) have 4 directions and new sprites, nice.

The large crate has been changed, because it has hideously behind the times. It's a one time lock, you pop it open with a crowbar, and it acts like a regular crate from there on out.

## Changelog
:cl: Cornelius Bogfrollup Fitzgerald
imageadd: New crate sprites!
tweak: largecrates don't delete when crowbarred open, rather just acting like a normal crate after you open it up for the first time.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
There are bigger sized variants than these, a little feedback I've gotten is that they're too small and i'm okay with switching to the bigger sized if that seems to be a common complaint

**Comment by Bawhoppen** [comment]
I'm not sure what it is, but something seems off to me about these. Can't quite put it. Maybe not enough texturing on the solid surface areas? Or the borders on some are too light, and others too dark maybe? Not entirely sure. 
I also personally don't think we should do directionals for crates. It's just one of those types of objects that it doesn't work for IMO. (Also it messes up the laying down in crates function then, since humans lay horizontally.)
Also, the coffin I definitely don't think is an improvement at all. The current 3/4ths one we have is pretty good (I think it was made by WJ?).

**Comment by Tlaltecuhtli** [comment]
can you make regular crates as big as the trashbin crate?

**Comment by tralezab** [comment]
*Big anime sigh because I have to do a small amount of work*
Okay, I have these from an older age and they're about the same size as our crates we have now. I'll work on using these

**Comment by Iamgoofball** [comment]
:-1: The spriter is not someone we want to be associated with.

**Comment by MrDoomBringer** [comment]
@Iamgoofball lmao what aren't they just some unitystation person

**Comment by LemonInTheDark** [comment]
They are a right dick to be fair

**Comment by MrDoomBringer** [comment]
oh they made the closets LOL
still who cares if the sprites look good why don't we use them

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=Qn977W9HjWM

... Eh, I'll probably get used to it eventually. These do look a bit small, though.

**Comment by MrDoomBringer** [comment]
post pics of what some of the larger sprites you mentioned look like in-game please
also yeah the old brown caskets were way better

**Comment by tralezab** [comment]
I disagree for a few reasons on the caskets, mainly involving how great the new ones look directionally.

**Comment by cacogen** [comment]
Why is it so hard for people who make sprite PRs to understand the game has a de facto art style? While the game is visually inconsistent due to there having been multiple generations of art styles (e.g. OpenSS13, pre-/tg/ Goon, /tg/) and every sprite not being updated at once, it doesn't matter how skilful or visually pleasing the sprites you're PRing are if they look like they're from Pokemon and the rest of the game doesn't. 

While current crate sprites are ancient and could be modernised and made less boring to look at, the sprites should be more consistent with the rest of the game's (e.g. lockers). People who blindly thumb up PRs because they add new things should be shot.

**Comment by MrDoomBringer** [comment]
>thinking /tg/ has a consistent art style

omegalul

**Comment by cacogen** [comment]
That strawman is the exact opposite of what I said. The art style is inconsistent not intentionally or desirably but because no one can update every sprite in the game at once or by themselves and because of PRs like this being merged. It's an unnecessary change that adds arguably better looking sprites at the cost of further visual inconsistency. The maintainers in charge of sprites or art direction or whatever they're called should clamp down on this to prevent the problem getting worse. It ends up looking amateurish as fuck when this codebase used to be known for its polish compared to servers like Goon or Bay.

**Comment by Tlaltecuhtli** [comment]
do u have wood crat esprit too?

**Comment by tralezab** [comment]
@cacogen polish being every sprite in the game was shit as to now where it's unpolished become some sprites aren't? Not sure I understand

**Comment by cacogen** [comment]
Not all the newer sprites are better. This game is plagued with unnecessary changes to sprites, often the same ones repeatedly, with some worse than what came before. But most of the sprites haven't changed much since /tg/ began.

**Comment by Capsandi** [comment]
Gotta agree with cac here, there's a threshold of quality of sprites in which they just don't need to be replaced. Our current crate sprites have no negative effect on gameplay and better match what is present in the game. Though we are unable to consolidate everything into a single style or palette, that's no excuse to make the wound bigger by needlessly replacing sprites with newer ones which in no way match what is present in the codebase. These do seem to match the TGCM style, perhaps they could find a use there?

**Comment by CRITAWAKETS** [comment]
These sprites look pretty awful even without considering the different art style. They have a lack of detail/shading and a generally bad color palette.

**Comment by Bawhoppen** [comment]
I feel we'd be best off just using the old Bay ones (before they switched style), since they are quite similar to our current ones, except for being slightly updated and in 3/4ths.
Quick screenshot of the dmi just to give an idea: 
image

**Comment by BootlegBow** [comment]
unitystation crates

**Comment by jacklecroy** [comment]
> 
> 
> I feel we'd be best off just using the old Bay ones (before they switched style), since they are quite similar to our current ones, except for being slightly updated and in 3/4ths.
> Quick screenshot of the dmi just to give an idea:
> image

I like these a lot better. My main complaint with this PR is that the corners are rounded, it doesn't look good.

**Comment by optimumtact** [comment]
@cacogen shut up boomer

**Comment by cacogen** [comment]
@Bawhoppen Those are visually consistent and look better than these.

**Comment by wesoda25** [comment]
An official graphic design vision for tg is long overdue, until we get it we're just gonna keep seeing sprites get merged solely because they look better. It might slowdown the spriting pipeline even more since we can't just pick and choose sprites from other servers, but would be better in the long run.

**Comment by MrDoomBringer** [comment]
> until we get it we're just gonna keep seeing sprites get merged solely because they look better.

?????

**Comment by MrDoomBringer** [comment]
ITT people don't realize that good looking sprites > bad looking ""visually consistent"" sprites
there's nothing stopping us from slightly changing the pallet later down the line to make them more in-line with common colors that we use, but for now this is objectively an incremental improvement

**Comment by wesoda25** [comment]
Wdym realize, that's an opinion. I'd rather have uglier sprites that don't stand out. 

THAT BEING SAID, what's in this PR isn't that bad. I'm just talking about in general. These would probably be a net improvement. Although the stuff baw posted looks a lot more fitting for tg.

**Comment by MrDoomBringer** [comment]
@tralezab 
image
gotta say the old sprites still look better imo

**Comment by tralezab** [comment]
@MrDoomBringer How about we keep a shitty coffin (aka unpainted wood) and a high quality coffin as two coffin types :)

**Comment by cacogen** [comment]
@MrDoomBringer The problem with that coffin sprite is the lid looks wrong.

**Comment by MrDoomBringer** [comment]
@cacogen do you mean the new coffin looks wrong? if so, yes. Also because it's jet black, doesn't really fit with the whole light-hearted charm, seems like something from castlevania

**Comment by tralezab** [comment]
Yeah that's what I mean dog imagine if on halloween we brought this out for the vampies

**Comment by tralezab** [comment]
Anyway. God I need to add those big crate sprites already

**Comment by cacogen** [comment]
@MrDoomBringer Yeah, the lid on the new one looks wrong. I don't mind that it's more gothic (I actually prefer it, and also wouldn't mind multiple coffin types provided they're consistent with each other and the game in terms of art style and have the same number of directions) and unlike the crates it fits well with the art style of the old coffin and the game overall. It isn't going for that plasticky blocky modern look like Pokemon/DBZ/Starbound/Risk of Rain etc. like the crates are which arguably looks good but doesn't match the rest of the game.

**Comment by Twaticus** [comment]
the sprites currently in/the image in the OP are an outdated version of the crates we're planning on using

**Comment by Tlaltecuhtli** [comment]
the bayst*tion ones look 2d

**Comment by MrDoomBringer** [comment]
@Twaticus 
>crates we're planning on using

do you refer to the [larger crates](https://github.com/tgstation/tgstation/pull/55340#issuecomment-738624951) trazelb posted in this thread, or something else?

**Comment by tralezab** [comment]
@MrDoomBringer a hybrid, taking the best parts, sizes, and correct opinions from all the sprites we have and comments we've gotten on github that are correct and right

**Comment by SweptWasTaken** [comment]
Idk if this is in anyway useful, but I replaced the crates from cev-eris on SS14 with these crates from Citadel. If you do want to resprite crates for tgstation (I don't know why you would, the crates you have now are fine and look good) you might consider using these ones.


Content Client_2020-12-06_22-23-01

Alternatively, how hard would it be to resprite all the current tgstation sprites with directionals? 

I personally think the crate sprites in this PR look like shit. They look so soft like they're made out of ice-cream.

**Comment by SweptWasTaken** [comment]
> 
> 
> Gotta agree with cac here, there's a threshold of quality of sprites in which they just don't need to be replaced. Our current crate sprites have no negative effect on gameplay and better match what is present in the game. Though we are unable to consolidate everything into a single style or palette, that's no excuse to make the wound bigger by needlessly replacing sprites with newer ones which in no way match what is present in the codebase. These do seem to match the TGCM style, perhaps they could find a use there?

Ye

**Comment by SmArtKar** [comment]
Citadel crates are much better than this shit from unity imo

**Comment by maxymax13** [comment]
why do they look like they're from a game boy advance pokémon game

**Comment by cacogen** [comment]
@SmartKar
Post pic

**Comment by SweptWasTaken** [comment]
> 
> 
> @SmArtKar
> Post pic

Literally check my message 1 message above you orangutan.

**Comment by cacogen** [comment]
Oh, I see. They look like the off-brand equivalent of OP's.

**Comment by Tlaltecuhtli** [comment]
those arent crates they are legos

**Comment by cacogen** [comment]
They click together for easy transport

**Comment by tralezab** [comment]
art lead will open a pr or something when something comes out of it

**Pull request closed without merging**
