### PR TITLE
Fixes being mute giving no feedback when trying to speak

### LINKED ISSUE #4727: Muted people trying to speak don't get any indication
Nothing happens at all, except the command bar getting wiped. This leads to "halp I can't use chat shitty buggy game". A message of some sort when they're trying to speak would probably remedy this.

### PR DESCRIPTION
**Pull request by maartenberg**
Fixes #4727.

### CODE REVIEW

**Comment by Xhuis** [comment]
I think something along the lines of "You can't speak!" is probably better. That's just personal input though.

Either way, :+1:

**Comment by kingofkosmos** [comment]
Could you please use <span class='warning'>? There's no actual danger in being unable to speak.

**Comment by spasticVerbalizer** [comment]
@kingofkosmos Oops, will do.

**Comment by spasticVerbalizer** [comment]
@Xhuis The message is like that because the [megaphone](https://github.com/tgstation/-tg-station/blob/master/code/game/objects/items/devices/megaphone.dm#L35) already had a message for mute people and I copied it for consistency.

**Pull request merged**
