### PR TITLE
Megafauna will now seek out and consume corpses

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
add: Megafauna will now seek and consume corpses of enemies to heal or otherwise.
/:cl:
###### haha

this is really goddamn mean, tbh.
though it's already kind of RNG if they devour you based on if they manage to kill you with an attack so....

Legion is slightly more forgiving, and will instead turn humans into more legion.

### CODE REVIEW

**Comment by TheNightingale** [comment]
Do they heal from eating people? If they don't, they should.

**Comment by TechnoAlchemisto** [comment]
hungry

**Comment by Bawhoppen** [comment]
all fauna should eat people why do they kill them ifnot to eat

**Comment by Robustin** [comment]
Bad change. This pretty much guarantees every MF that ends up on station will kill everyone and its pointless to even fight back.

We already decided players gibbing players was kind of shitty, but at least that action gives ONE of the players some satisfaction. Mobs gibbing players? Who the fuck benefits from that? How does that enhance the game besides reducing server load when everyone logs off?

**Comment by ChangelingRain** [comment]
It already gibs players, this just means it does it consistently instead of only on some ability use/when a melee attack kills a target.

**Comment by jughu** [comment]
Its statyfyibg because its mobs from hell and they should act like they are from hell just make bubblegum tear every limb off your body instead gibbing make colluses gib you make the drake burn you into remains and make legion legionize you

**Comment by Man-Shroom-** [comment]
what the fuck is the above post

**Pull request merged**
