### PR TITLE
Inhand sprites for bolas

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Bolas, reinforced bolas, energy bolas, and cult bolas now have inhands. Gonbolas uses reinforced bola inhands since its the same color and the sprites are too small to make it look anything close to a gondola SORRY. Adds a thrown weapon inhand file. Closes the second half of #47007

dreamseeker_KLe7alK9hF
Original, Reinforced, Cult, Energy

## Why It's Good For The Game

Bolas can fuck your day up in an instant so atleast you get a chance to know when its coming now.

## Changelog
:cl:
imageadd: bola inhand sprites
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Nice

**Comment by Tlaltecuhtli** [comment]
do they move

**Comment by Tharcoonvagh** [comment]
One more reason to vote for ye!

**Comment by necromanceranne** [comment]
Nice, these definitely needed inhands for a while.

**Comment by trollbreeder** [comment]
Fun fact: Energy bola = Ebola

**Pull request merged**
