### PR TITLE
DNA vault balancing

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
Reduced amount of animal and plant DNA needed for the DNA vault objective.
## Why It's Good For The Game
This objective getting completed is incredibly rare, BSA is a fun station objective and gets completed often, The DNA vault is too tedious and hopefully this will counteract that a little bit before some kind of rework comes in to fix the underlying issue of the objective being quite boring.
## Changelog
:cl: grungussuss
balance: The DNA vault now requires less animal and plant DNA to be completed
/:cl:

### CODE REVIEW

**Comment by CCC23** [comment]
wait WHY WAS THE PLANT COUNT TIED TO PLAYER COUNT WHAT

**Comment by Sadboysuss** [comment]
> wait WHY WAS THE PLANT COUNT TIED TO PLAYER COUNT WHAT

idk but it sucked, maybe we could unbind it from player count but I'll wait on a maint opinion.

**Comment by GuillaumePrata** [comment]
Looking for animal DNA is fun, plants is really boring.

Personally I would keep the same value for animals and just remove the plant requirement, it is not engaging at all in any shape or form.

**Comment by Sadboysuss** [comment]
> Looking for animal DNA is fun, plants is really boring.
> 
> Personally I would keep the same value for animals and just remove the plant requirement, it is not engaging at all in any shape or form.

yeah I kinda agree but let's see maint opinion first

**Comment by the-orange-cow** [comment]
I agree that the current requirement for plants is a little high, so reducing it is kino.  Would rather it not be removed completely, it gives botanists a way to positively interact with the station instead of doing the things botanists are known for doing.

**Comment by Higgin** [comment]
great change, might actually see this get done now

**Comment by NullDagaf** [comment]
Just make the DNA probe be able to scan /obj/structure/flora. Way better than plain number tweaks.

**Comment by EricZilla** [comment]
It would be nice if fish counted as animals

**Comment by Livrah** [comment]
Glad to see anything but BSA being completed. 
If only you could scan harvested plants for the DNA too.

**Pull request merged**
