### PR TITLE
A/Dsay radio keys redux

### PR DESCRIPTION
**Pull request by Cyberboss**
Bluh

### CODE REVIEW

**Comment by coiax** [comment]
> still not physical radio keys that you can steal from admins

:-1:

**Comment by vcordie** [comment]
please let me steal the admin radiokey reee

**Comment by Kromgar** [comment]
Make a physical admin radio key for admin memery

**Comment by Cyberboss** [comment]
Different PR you fucking memes

**Comment by coiax** [comment]
> Different PR you fucking memes

I don't remember writing that message, help someone has hacked my account

**Pull request merged**
