### PR TITLE
Assault Pod doors have AI control disabled

### LINKED ISSUE #13844: AI can bolt the doors on the nuke op assault pod
Need to map edit their AI control out

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Also added WARNING SPACE signs in front of the drop pod room

Removed the excess janitors bucket from the bathroom

Fixes #13844

### CODE REVIEW

**Comment by Jalleo** [comment]
Actually having the excess one was good since there are two janitors and when there inst it means you can give robotics a bucket at round start for them to make you a clean bot

**Comment by KorPhaeron** [comment]
@Jalleo 

Nuke ops bathroom

**Comment by Shadowlight213** [comment]
Doesn't this just make the AI need to hack the door? I swear there was a way to make it so that the AI can't hack it at all, but I don't see it used anywhere.

**Comment by Thunder12345** [comment]
By the time the AI hacks the doors the ops will all be out the pod though. The problem is that the AI bolted the pod on arrival before they could get out.

**Comment by tkdrg** [comment]
@KorPhaeron map conflicts for you

**Pull request closed without merging**
