### PR TITLE
Makes tilted vendors now drop premium items too

### PR DESCRIPTION
**Pull request by BadSS13Player**
## About The Pull Request
Adds premium items to the list of items vendors could drop when tilted.

## Why It's Good For The Game
Adds more reward to a high risk action.

## Changelog
:cl:
tweak: Vending machines can now also drop premium items when tilted.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
prob gonna close this, it's not meant to be a fair risk/reward interaction.

If you want premium items, pay for them.

**Comment by ATH1909** [comment]
> prob gonna close this, it's not meant to be a fair risk/reward interaction.
> 
> If you want premium items, pay for them.

it's still not gonna be a fair risk/reward interaction, since there'll be many more non-premium items than premium items (let alone the premium item(s) you want!) in most vending machines. However, by adding a POTENTIAL reward to the pool, it'll encourage more people to risk crushing themselves with vending machines! It's sort of like the lottery, except with a chance of being paralyzed for life.

**Comment by ATH1909** [comment]
And to stave off the no nerf november crowd: This is a fix because many players (including myself) were under the impression that this was already the case- vending machines NOT being able to drop premium items when tilted is an abnormality.

**Comment by ATH1909** [comment]
image

**Comment by LemonInTheDark** [comment]
This seems like a balance change, why do this now? It appears to violate #54733

**Comment by Ryll-Ryll** [comment]
yeah I think this would be best left til december

**Comment by ExcessiveUseOfCobblestone** [comment]
oh yeah we're in november

**Pull request closed without merging**
