### PR TITLE
Fix smoke machine runtime

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
Simple sanity check.

**Comment by Robustin** [comment]
Can someone please fix the settings button. You started this issue and now its worse than ever.

Setting buttons should indicate range but now they're all non responsive except for 3.

**Comment by nicbn** [comment]
I'll take a look on that @Robustin .

**Comment by nicbn** [comment]
Tested it locally with that fix, everything goes just fine.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
