### PR TITLE
Changes the dragon's gender

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
From
Screenshot 2022-02-22 172036

To

This also fixes some pet peeves where they (the coder, not the dragon) were double spacing after periods. Don't do this, it's 2022

## Why It's Good For The Game
Nothing warrants an examination that close

## Changelog

:cl:
spellcheck: Space dragons are now "it" instead of "he".
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
Obligatory trans dragon joke

**Comment by optimumtact** [comment]
shouldn't you ask the creator of the dragon before assuming it's gender?

**Comment by ATH1909** [comment]
> shouldn't you ask the creator of the dragon before assuming it's gender?

*its

**Comment by Bawhoppen** [comment]
Perhaps you should move the level up to /hostile or even /simple_animal so all generic mobs are 'it' unless otherwise specified?

**Comment by jlsnow301** [comment]
> Perhaps you should move the level up to /hostile or even /simple_animal so all generic mobs are 'it' unless otherwise specified?

not a bad idea

**Comment by IndieanaJones** [comment]
What the hell is wrong with double spacing?  Most modern writing formats use it.
Also, the dragon's gender was randomized like all simplemobs, I don't see this this as pertinent but then again, I don't really care.

**Comment by Fikou** [comment]
why though

**Comment by jlsnow301** [comment]
> What the hell is wrong with double spacing?  Most modern writing formats use it.

Strike "modern" - it's a carry over from the typewriter days

**Comment by Ryll-Ryll** [comment]
I guess it's fine, moreso because of the double spacing changes than me caring about dragon genders.

**Pull request merged**
