### PR TITLE
Fixes potential add_to_active() runtime

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Thats intentional

**Comment by Cruix** [comment]
It will short circuit and not evaluate T.air as it is now.

**Comment by MrStonedOne** [comment]
Cruix, thats not cyberboss'es point. expand downward and don't assume

**Comment by MrStonedOne** [comment]
It's typing is for turf/open

but it can handle a non-open turf

This is what the elses are for.

It looks like this proc was changed some since i last fucked with thou, so there might need to be some adjustment

**Pull request closed without merging**
