### PR TITLE
[s] [April Fools] Makes blast doors Texan

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: In an attempt to make machines more approachable by niche users, blast doors now have a distinct Southern personality.
/:cl:

Blast doors now say "Blast it!" when they close.
I assume this is for testmerging when the time comes so I'll leave it open, I suppose?

### CODE REVIEW

**Comment by Cheridan** [comment]
YEEEHAW

**Comment by Cheridan** [comment]
wrong button

**Comment by Xhuis** [comment]
y'all come back now y'hear

**Comment by ShadowDeath6** [comment]
if someone makes some shitty what in tarnation joke I'm unfavoriting xhuis on tg forums

**Comment by calzilla1** [comment]
COW BOY HAT
COW BOY HAT
COW BOY HAT

**Comment by FantasticFwoosh** [comment]
WHAT IN TARNATION

**Comment by AdamElTablawy** [comment]
Crowbarring a depowered blast door should make it shout 'That just ain't right!'

**Comment by KorPhaeron** [comment]
PRs dont need to be open to be testmerged

**Comment by Xhuis** [comment]
That simplifies things.

**Pull request closed without merging**
