### PR TITLE
Singularity_pull() standartize

### PR DESCRIPTION
**Pull request by larentoun**
## About The Pull Request
`/atom/proc/singularity_pull(obj/singularity/singularity, current_size)` is defined, but other procs were just referencing it as a un-typed variable. This PR just makes that every `proc/singularity_pull()` now has arguments and singularity in that argument is now typed.

## Why It's Good For The Game
Standartization?

## Changelog
No changelog needed

### CODE REVIEW

**Comment by SmArtKar** [comment]
``/datum/component/singularity`` passes parent into pull_singularity args, which can be: a tear in reality, nar-sie, reality tear (totally different) and singularity itself. This will only introduce further confusion.

**Comment by larentoun** [comment]
Can't we at least pass it as an atom?

**Comment by SmArtKar** [comment]
> Can't we at least pass it as an atom?

nothing uses those, and if you checked the code you'd realize that size is passed as the first argument and object is passed as second argument, inverse of what you added.

**Comment by larentoun** [comment]
> > Can't we at least pass it as an atom?
> 
> nothing uses those, and if you checked the code you'd realize that size is passed as the first argument and object is passed as second argument, inverse of what you added.

image

But the first argument is `parent`, which is an atom, and the second is the size?

**Comment by larentoun** [comment]
And in a downstream I need to type that `S` to atom to use `var/name` equivalant in `human/singularity_pull()`. I thought some standartization would be nice here too.

**Comment by SmArtKar** [comment]
> > > Can't we at least pass it as an atom?
> > 
> > 
> > nothing uses those, and if you checked the code you'd realize that size is passed as the first argument and object is passed as second argument, inverse of what you added.
> 
> image
> 
> But the first argument is `parent`, which is an atom, and the second is the size?

neeevermind I am extremely confused as to where I looked to find size being first argument. Passing it as an atom would work then, yes - but not obj/singularity like you did as that would lead to a lot of confusion (its like that on atom definition of that proc which is baaad, fix would be appreciated)

**Comment by larentoun** [comment]
> > > > Can't we at least pass it as an atom?
> > > 
> > > 
> > > nothing uses those, and if you checked the code you'd realize that size is passed as the first argument and object is passed as second argument, inverse of what you added.
> > 
> > 
> > image
> > But the first argument is `parent`, which is an atom, and the second is the size?
> 
> neeevermind I am extremely confused as to where I looked to find size being first argument. Passing it as an atom would work then, yes - but not obj/singularity like you did as that would lead to a lot of confusion (its like that on atom definition of that proc which is baaad, fix would be appreciated)

Should I make a new PR for the same-is PR, but with `/singularity_pull(atom/singularity, current_size)` instead of `/singularity_pull(obj/singularity/singularity, current_size)`?

**Pull request closed without merging**
