### PR TITLE
Syndie borg and uplink changes

### PR DESCRIPTION
**Pull request by ghost**
Removed syndie borg LMG. Replaced with large ebow.
Removed syndie borg grenade launcher.
Removed leftover taser code.
Reduced price of explosive implant from 9 to 5.
Buffs cyborg esword by halving the hitcost.

### CODE REVIEW

**Comment by Jordie0608** [comment]
http://en.wikipedia.org/wiki/Changelog

**Comment by paprka** [comment]
C H A N G E L O G
H
A
N
G
E
L
O
G

**Comment by Lumipharon** [comment]
Can we not just give ops back their default explosive implants? Like seriously, literally every nuke round I have been in, or observed sine that change (except for the odd faceroll) has just ended with the crew looting the shit out of all the ops, which utterly fucks them.

**Comment by ExplosiveCrate** [comment]
Doesnt the syndieborg have infinite battery, though?

**Comment by GunHog** [comment]
They have 25 kWh, which normally lets them last the entire mission, unless they overuse their e-sword. It was balanced for the laser-ebow-sword combo, but with this rather significant cut of capability, the esword will be its primary weapon. The energy cost needs to be greatly reduced or removed for it to still be a viable choice for the Ops besides being sent to kill the AI.

**Comment by Niknakflak** [comment]
Doesn't the lmg run out of ammo?  I know the grenade launcher did and despite it being powerful, you burned through it fast.  Either way, these seem like great changes to make your weapons last longer.  Good stuff.

**Comment by paprka** [comment]
The LMG is a pseudo energy gun because it's shitcode so it can regenerate bullets but it gets effected by EMP and then the syndie borg is more or less completely useless

I could make it EMP proof but whatever the lmg and grenade launcher were more of a stand-in because the ebow was too OP which it isn't anymore

**Comment by Niknakflak** [comment]
Hilarious coding

**Comment by Fox-McCloud** [comment]
Syndiborgs definitely need a nerf, but it also feels really crappy not having primary weapon---not saying this is necessarily a bad thing (I agree it's probably needed), it just feels kinda crappy.

**Comment by paprka** [comment]
this large ebow does 20 tox damage but has to be cranked

**Comment by Lumipharon** [comment]
What's the purpose of syndie borgs now? E-sword is not a viable weapon because of its insane energy costs, which means you are going to be killing people SLOWLY with cranking your e-bow, which is just stunlocking people to death. Slowly. Not really in theme with nuke ops - just give thema laser and no ranged stun, atleast they're still dangerous/can deal with fast moving/multiple people, but can't heuheuh stun everything.

**Comment by paprka** [comment]
What about SHOTGUN LASER

**Comment by Lumipharon** [comment]
Spread type attacks already make it harder to work as a team, since you basically have to be in front of your team mates, which makes it pretty clunky tbh.

**Comment by Fox-McCloud** [comment]
@paprka 

What about keeping the LMG, but the bullets it fires do a bit of stamina damage? You could then remove the launcher and decrease the cost of the esword hit a bit.

**Comment by paprka** [comment]
what about a chaingun!!

also the lmg doing damage is not the problem here and not why i removed it

**Comment by GunHog** [comment]
Why DID you remove it? Also chaingun sounds awesome.

**Comment by Dorsisdwarf** [comment]
I'm coding a gatling gun at the moment, when I make that work we could give them that? Chaingun as in massive rate-of-fire, high ammo, low damage, right?

**Comment by paprka** [comment]
The large ebow is perfectly fine, a chaingun wouldn't work right. I would rather see this in action before making further balance changes.

**Comment by vista-** [comment]
I made the esword have a high energy usage because it's supposed to be a faster, more last resort-ish weapon for when you want someone dead, and dead fast. I'd say either lower the energy cost a bit, or lower it even more and make it deal less damage so that at least 4 hits are needed to crit someone (20 damage, accounting for the 20 tox damage that the ebow does). Or just give them a main weapon again.

**Comment by paprka** [comment]
That's what the large ebow is meant to be, a replacement for the laser gun and stuff. I'd rather the borg used syndie tech, yknow

**Comment by paprka** [comment]
Buffed cyborg esword by halving the hitcost.

**Comment by Fox-McCloud** [comment]
Conflicts, also, dunno why this hasn't been merged in yet.

**Comment by paprka** [comment]
Bad maintainers

**Comment by RemieRichards** [comment]
Because that'll really get it merged won't it?

Also conflicts, enjoy.

**Comment by paprka** [comment]
I fixed the conflicts, also I don't care if you merge this or not, if you want a broken unbalanced piece of shit in the code instead that's fine.

**Comment by Lumipharon** [comment]
Can ops just get back their default explosive implants? Not having them seriously fucks over the team, and there aren't that many tc to go around (pap's other change with the gun vouchers might change that though)

**Comment by paprka** [comment]
Yeah the ops will all have semi decent reliable weapons from roundstart plus extra ammo for it so buying explosive implants will be a lot more viable with my voucher changes lum.

**Comment by paprka** [comment]
@someone jesus

**Comment by Razharas** [comment]
Thats some serious syndborg nerf

**Pull request closed without merging**
