### PR TITLE
[s] Replace json_decode with one that validates through rust-g

### PR DESCRIPTION
**Pull request by Mothblocks**
could be backwards incompatible with some stuff, we'll see

### CODE REVIEW

**Comment by msgerbs** [comment]
Why is this a stealth PR?

**Comment by Jared-Fogle** [comment]
@Cyberboss I think it's fine if this gets merged, nice to have an extra layer of sanity.

**Comment by Cyberboss** [comment]
It'll be a big a performance hit, we decode json a LOT (every tgui call)

**Comment by Jared-Fogle** [comment]
Fair enough.

**Pull request closed without merging**
