### PR TITLE
Adds hackable suit sensors

### PR DESCRIPTION
**Pull request by JJRcop**
I made it so you can hack suit sensors by clicking on them with wirecutters, this causes them to capture the current stats, and only show the captured stats, instead of the actual ones.

The intent is to allow people to have suit sensors on so they reduce their likelihood of being a suspect, but that aren't actually reporting their real health and location. Since it never updates, you can be discovered if you have your sensors hacked for too long and there is an attentive person watching sensors.

_NOTE: If you don't actually have the jumpsuit on while hacking it, it will still capture stats.. of nobody.. so you essentially disable the sensors if you hack a jumpsuit that nobody is wearing._

Forum poll: http://tgstation13.org/phpBB/viewtopic.php?f=9&t=1712

**Commit log:**
## d85f504
- Adds new query_sensors proc to jumpsuits that returns a list of lists that contain the various suit sensor data
- Changes the crew monitoring console to call query_sensors on jumpsuits instead of getting the stats itself
- You can hack suit sensors by clicking them with wirecutters, which will cause them to call query_sensors and store the result, only returning the stored result when queried again, you can "unhack" them by clicking on them with wirecutters again

### CODE REVIEW

**Comment by JJRcop** [comment]
Month 3: I am still barely hanging on, avoiding the conflicts at all costs, for they are my death. Luckily my files aren't changed often. This may be my last journal entry.

**Comment by paprka** [comment]
Wasn't @MrPerson 's post on it enough evidence that the maintainers don't want this? I thought he explained the problem rather clearly, but okay

**Comment by JJRcop** [comment]
@Cheridan says 
>this seems fine

@MrPerson says
>Against this 1000%

Doesn't seem unanimous to me.

**Comment by paprka** [comment]
a) nobody metagames/powergames with suit sensors anymore
b) this makes medical doctor a pain in the ass and even less likely to look at suit sensors

Tell me, now that you know this, what's the real value for this feature?

**Comment by paprka** [comment]
Also

>Set suit sensors to coordinate
>Hack them
>Someone goes to the coordinate
>You're not there
>X HACKED HIS SENSORS HE MUST BE ANTAG

**Comment by JJRcop** [comment]
>a) nobody metagames/powergames with suit sensors anymore
Well since this is the main point of the PR, I guess it is pointless then.
I'll leave it up for a few more days and close it if there is no more feedback.

**Comment by JJRcop** [comment]
Basically, now or never for a consensus on the PR, it's been sitting here.

Maintainers?

**Comment by paprka** [comment]
Honestly the 'people metagaming with suit sensors' thing hasn't been a thing for a year+, we added RNG that randomly selects what you suit sensor mode is on every jumpsuit's new() so it's extremely ineffective most of the time.

**Comment by optimumtact** [comment]
I want to break my suit sensors as a rainbowtider

**Comment by TZK13** [comment]
You know if there's anything to take away from all this a traitor item that lets you set up dummy suit sensor targets that you can use to set traps with would be pretty neat.

**Comment by Miauw62** [comment]
Sure I don't mind this @Cheridan pls merge
Op 5-jan.-2015 03:59 schreef "TZK13" <notifications@github.com>:

**Comment by paprka** [comment]
Welp no reason to play MD then

**Comment by hornygranny** [comment]
after bullying JJR and making him fix 10,000 conflicts we just don't like this feature that much

**Pull request closed without merging**
