### PR TITLE
Shuttle rotation decal corner fix (Take 2)

### PR DESCRIPTION
**Pull request by WJohn**
Faster to just remake it when I fucked it up that hard, hah.

Anyway--
No more of this right here:
image

Had to touch a lot of maps because their directions were wrong in the icons file, so when I changed those every map that had these needed updating. I've added a script called cornersfix to mapmerge2/map_scripts for downstream servers.

I'm expecting to fight a lot of merge conflicts with the 6 other map PRs open at this time.

:cl: WJohnston
fix: Fixes warning line corners being all wonky when shuttles rotate.
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
This hasn't failed build, it's just the map diff test fails very easily.

**Comment by Cyprex** [comment]
How does this work? I'd expect the code rotating shuttles would have to rotate the decals and other directional things as well, but this doesn't seem to be the case.

**Comment by WJohn** [comment]
I am just in the dark about how these things rotate with regards to their dir and what icon they're supposed to use. I just made it mimic the colored tile corner decals, and it fixed everything.

**Comment by SpaceManiac** [comment]
In case it's unclear, the old sprites are definitely wrong and this is the right fix. Previously, south = bottom-right and north = bottom-left. Thus if you logically try to rotate the decal 180 degrees from south to north, the visible sprite actually only rotates 90 degrees. This is why everything looked wrong when rotated. There just needs to be an actual logic to which directions hold which sprites.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
