### PR TITLE
Nerfs flash effects on carbons to be a less reliable one-tap/gear-check.

### PR DESCRIPTION
**Pull request by Higgin**
## About The Pull Request
#78515 redux with a couple of slight differences from testing.

Makes flashes 
-deal less stamina damage
-knockdown rather than hard-paralyze
-require the target to be confused in order to knockdown
-edit add: provide a slightly longer screenflash effect

The exact values here mean that
-stamcrit requires two _(edit: it's a random range from 60-80 - it's guaranteed on two)_ targeted flashes on a target facing you directly
-it may require up to four on a target facing you from the side
-the knockdown is as long as the previous paralyze duration was
-if you use the AoE flash mode, you have 10 seconds of confusion for the next direct flash to be a knockdown
-if you flash somebody directly, you have 30 seconds of confusion for the next direct flash to be a knockdown
-edit add: the screenflash effect fades out over 3.5 seconds instead of 2.5 seconds (old)

Additionally:
Makes nightmares have FLASH_PROTECTION_SENSITIVE - sunglasses will help them but still leave them vulnerable to flash effects, welding helmets will fully protect them. 

## Why It's Good For The Game

Same reasons as before. Rocket tag sucks. Binary gear checks suck. Stun combat isn't great. Silicons got their flash nerf in #75819. 

Flashes impose a disadvantage on the player by limiting their senses and ability to usefully interact with the game. If they do that, they shouldn't also remove your ability to do anything with a hard Paralyze because you didn't go rat for sunglasses or something with passive flash protection. 

You can still stamcrit people with them - the ability to spam them is unchanged. With these changes, they combo well with shoves and aren't an instant, binary 'I win.' They can be used to disarm people with the knockdown. If you want toggleable protection like a welding helmet, now, you at least have a slight window to get it down or run if somebody goes to ambush you with a flash. 

Moth buff. Borg nerf. Sec/command nerf. Robotics and engineering nerf? NVG buff? ~~Hypnoflash nerf.~~ The conversion antags using flashes aren't changed. Welding helmet buff. edit: also nightmare nerf. 

edit credit moocowswag: static button flashers and portable flashers still hard-paralyze people - 10 and 8 seconds respectively. If you literally walk into it, that's on you.

## Changelog

:cl:
balance: Flashes now do less stamina damage, Knockdown instead of Paralyze, and require the target to be confused from a previous flash or other source to Knockdown.
balance: Flashes will immediately Knockdown people with sensitive eyes without extra protection.
balance: Flash screenflash effect on direct use lengthened from 2.5 to 3.5s (median of the knockdown time.)
balance: Nightmare eyes are now more sensitive to bright lights than the average person's.
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
how does this impact stagnant flashers like the one in hop line? are they still paralyze or just a knockdown.

**Comment by Higgin** [comment]
> how does this impact stagnant flashers like the one in hop line? are they still guarantee paralyze or just a knockdown.
> 
> Also did you consider upping the blind duration to compensate?

great question, will add it to the OP - static flashers still paralyze for their given time. Static flashers are 10 seconds, portable flashers 8 seconds.

I didn't touch blind durations, but they continue through the knockdown in testing and can be refreshed by subsequent flashes.

**Comment by Helg2** [comment]
Also moths should have double stamina damage imo

**Comment by Higgin** [comment]
> Maybe some effects like drugginess should also act like confusion for flashes? Both for hypnoflashes and combo-ing something with flashing.

@Helg2 I double-checked this and since hypnoflashes apply their own effects, they're actually unaffected.

Making the other effects apply like confusion is a good idea and would soften the extent to which this is a nerf (but still something people can play around, since you can keep your sanity up, not do drugs, etc.)

**Comment by GuillaumePrata** [comment]
The change is good, but bypassing previous flash weakness is odd and these should be kept IMO.

Moths, people with augmented eyes, nightmares and whatever else being weak to flashes is a small, but reliable interaction.

**Comment by LemonInTheDark** [comment]
It was always my understanding that flashes were setup around a general visual impairment on people in range, and a stun on people you click on.
This doesn't seem like a problem to me, if you hit that click (which unlike stun batons most nefarious people are protected against anyway) you get a stun. Why does this need to be nerfed?

**Comment by Livrah** [comment]
> It was always my understanding that flashes were setup around a general visual impairment on people in range, and a stun on people you click on. This doesn't seem like a problem to me, if you hit that click (which unlike stun batons most nefarious people are protected against anyway) you get a stun. Why does this need to be nerfed?

someone plays moth

**Comment by Striders13** [comment]
HUGE MOTH BUFF

**Comment by Higgin** [comment]
> The change is good, but bypassing previous flash weakness is odd and these should be kept IMO.
> 
> Moths, people with augmented eyes, nightmares and whatever else being weak to flashes is a small, but reliable interaction.

funnily enough nightmare eyes don't actually have flash weakness, and moths are still affected like they were before - it doesn't go straight to a paralyze, but sunglasses alone won't protect them. I could work that in though.

**Comment by Higgin** [comment]
> It was always my understanding that flashes were setup around a general visual impairment on people in range, and a stun on people you click on. This doesn't seem like a problem to me, if you hit that click (which unlike stun batons most nefarious people are protected against anyway) you get a stun. Why does this need to be nerfed?

stun batons have a delay and counters in play besides the gear. They're also relatively hard to come by (but can be gotten in the same place you get flash protection from if you hit a sec locker,) whereas flashes can be found and printed all over the damn place. 

It's better gameplay and makes them more suitable as a defensive weapon rather than an I-Win button for them to not be a Paralyze, imo.

**Comment by deathrobotpunch** [comment]
I’m all for borg players but they can be quite overpowered. I don’t think borg flashing should be nerfed as it’s one of the only weaknesses that balances how strong they are.

silicons are in a bad place as it is and nerfing one of the only ways to disable one will not help at all (and could lead to drastic changes in the future).

**Comment by Cheshify** [comment]
It seems like people are sick of stun combat nowadays. Flashes are as strong as they are easy to get, and the gearcheck doesn't feel very fun.

**Comment by deathrobotpunch** [comment]
I think flashes would be better if they acted like the borgs when they get flashed once

**Comment by SimplySmiley123** [comment]
> > and a stun on people you click on.
> 
> Aren't we trying to move away from that? Changes to batons and such. Why would we want an item that's a hard stun unless you gear up with a specific item. The thing is flashes are bad for combat untill the moment they aren't. You'd much rather have anything else but then suddenly there's a moth (deserved) or an antag who forgot to powergame sunglasses (or more likely has xrays) and boom old school instant stun, get fucked

tbh most will cover their face in some way shape or form so you won't really get to know wether your flash will be of any use till you try it

**Pull request closed without merging**
