### PR TITLE
Adds proper sound effects to attacks against flora

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

Adds nine new sound effects: three rock hits, three wood hits and three foliage hits. All creative commons from Freesound (details in file metadata). Rocks are a subtype of flora for some reason.

Also improves code slightly in flora.dm.

https://user-images.githubusercontent.com/25089914/158725533-4f8d3930-778a-4d57-bc69-f83166e87d7a.mp4

## Why It's Good For The Game

Stops that godawful metallic thunk sound from playing when attacking bushes, trees, mushrooms and rocks.

## Changelog

:cl:
soundadd: Sound effects for attacking bushes, trees, mushrooms and rocks.
code: Minor code improvements in flora.dm
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Bless you man

**Comment by Serxule** [comment]
definitely quiet but thank god we have sounds now

**Comment by Likteer** [comment]
Can the old sound be kept for when you finish cutting down a tree? It was pretty satisfying.

**Comment by cacogen** [comment]
>Can the old sound be kept for when you finish cutting down a tree? It was pretty satisfying.

I haven't touched that, it still just plays the attack sound of the item you're sawing with once and then that meteor impact sound when you cut it down.

**Comment by LemonInTheDark** [comment]
immensely based

**Pull request merged**
