### PR TITLE
Spring Cleaning in the RSC

### PR DESCRIPTION
**Pull request by Thunder12345**
Moved lobby music to a new folder in sounds.

Lobby music tracks have been compressed. Shouldn't be any noticeable drop in quality.

Replaced e1m1.ogg with an identical MIDI, which is roughly 2 orders of magnitude smaller.

:cl: Thunder12345
tweak: Replaced the e1m1.ogg (DOOM music) with an identical MIDI, saved 1.5MB of space.
tweak: Relocated and compressed lobby music tracks, saved 8.2 MB of space. (Quality should be unaffected)
/:cl:

### CODE REVIEW

**Comment by Mervill** [comment]
The title music is: 
• Absconditus As heard in the Minerva mod for Half-Life 2 (and is/was available under an open source license) (PS: Someone needs to add the rest of the music from that album) (Title1.ogg)
• The Robocop Gameboy theme (title2.ogg)
• Tin Tin on The Moon (title3.ogg)
• The Room Theme for some fucking reason (title4.ogg)

(thanks [peoplearestrange](https://tgstation13.org/phpBB/viewtopic.php?f=2&t=8770&p=245455#p245399))

**Comment by Thunder12345** [comment]
No, they DON'T need to add the rest of that album, at least not unless they can offer it in MIDI form

I'd also be willing to restore any of the removed tracks if they can be supplied as MIDIs

**Comment by Thunder12345** [comment]
What's it called, I've got the full doom soundtrack in midis right here

**Comment by RemieRichards** [comment]
>what's knee deep in the doot called

cmon thunder.

**Comment by PKPenguin321** [comment]
Aw don't get rid of tin tin, we had that one custom made and it's really good

**Comment by Mervill** [comment]
HL2 - Triage at Dawn by Kelly Bailey (0:15)
https://www.youtube.com/watch?v=rvyswm1UMko

**Comment by Thunder12345** [comment]
Give me a midi and it will come back. We don't need massive music files taking up space.

**Comment by demonfiren** [comment]
How fucking dare you, I want my OOC shitposting soundtrack back.

**Comment by RemieRichards** [comment]
No compression :-1:, not the fucking title themes jesus.

**Comment by Armhulen** [comment]
Removing the two best ones? What the fuck :-1:

**Comment by Thunder12345** [comment]
Don't worry, the only thing I did was convert title1 and title2 to mono, and half the bitrate on clown to match the others

It's the same things I do to my oggs, there's no noticeable difference in quality.

**Comment by kevinz000** [comment]
Wtf don't remove the jazz one

**Comment by RemieRichards** [comment]
@Armhulen well that's just factually wrong.

@Thunder12345 "compression" probably wasn't the right word to use then, it triggers people (as evidenced)

**Comment by Armhulen** [comment]
There's a pretty big difference in quality, considering I can't even hear tintin or the room theme

**Comment by kevinz000** [comment]
Nevermind you didn't I don't think

**Comment by Thunder12345** [comment]
If you're so desperate to have your full jukebox find me midi versions. We don't need over 10MB in songs for the 2 minutes people sit in the lobby.

**Comment by Cyberboss** [comment]
FUCK YOUUUU TITLE3 IS THE BEST ONE!!!!! :-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1:

**Comment by demonfiren** [comment]
Oh fuck, I can definitely hear that.

**Comment by Thunder12345** [comment]
Definitely hear what?

**Comment by lzimann** [comment]
title3 is decent, the other 2 are lame

**Comment by demonfiren** [comment]
@Thunder12345 The compression.

**Comment by lzimann** [comment]
\>also compressing already less than 1mb files

why

**Comment by Incoming5643** [comment]
Remove the room but keep the other, the compression seems excessive, they were already compressed!

**Comment by Mervill** [comment]
Clearly these should all be FLAC files

**Comment by Thunder12345** [comment]
@lzimann see above. No need to have the files bigger than they need to be if there's no difference in sound.

**Comment by Thunder12345** [comment]
\>Test converting one of my oggs to FLAC
\>10x the size

**Comment by Mervill** [comment]
Sounds about right

**Comment by Supermichael777** [comment]
https://www.youtube.com/watch?v=hzPpWInAiOg

**Comment by Supermichael777** [comment]
Are you trying to fake a live performance on top shelf professional audio equipment? if yes flac all the way
else use midi or ogg

**Comment by Iamgoofball** [comment]
:-1: these are all good sounds, the downvotes speak for themselves

**Comment by Supermichael777** [comment]
lobby music for next christmass

**Comment by Supermichael777** [comment]
also might as well re-title i did not grief them to sinister ambition

**Comment by Thunder12345** [comment]
@Iamgoofball we do not need over 10MB of music that will be heard for maybe 2 minutes per round

**Comment by Cyberboss** [comment]
> Double upthumbing your own PR

**Comment by Niknakflak** [comment]
Firstly, Peoplearestrange and mervill keep getting something wrong.  The room theme is not title4 in the code so stop saying it as such.  Secondly, why do you even care if the sounds are large at what 9.8 mb?  That's still really small and I haven't heard anyone complaining about "Wahhh the code is too big".  Title4 also was already sound edited in a way to be very small with maximum sound quality, not sure about the other songs but really, :-1: x :100: No.

**Comment by Iamgoofball** [comment]
It's 2017, 9.8 MB is fucking nothing.

**Comment by Thunder12345** [comment]
@Niknakflak it's twice the bitrate of title1 and title2 plus stereo. Even cutting the bitrate and making it mono it's basically 1MB. Don't say it's edited to be "small" when it's 4x what it could be

**Comment by Niknakflak** [comment]
Because you are sacrificing sound quality for saving size when SIZE ISN'T EVEN AN ISSUE

**Comment by Iamgoofball** [comment]
That sounds like shit. Players don't like shit sounds.

**Comment by Iamgoofball** [comment]
What niknak said.

**Comment by Iamgoofball** [comment]
Also if we're going to complain about stuff being "too big" than disable admin uploading images, those gifs are huge.

**Comment by Thunder12345** [comment]
>Sacrificing sound quality

Point out for me where they sound so dramatically worse. Oh wait you can't.

**Comment by Niknakflak** [comment]
You're sacrificing whole entire sounds due to "saving space" when space isn't even an issue.

**Comment by Thunder12345** [comment]
No I'm not

**Comment by KorPhaeron** [comment]
Why do we need to do this?

**Comment by demonfiren** [comment]
@Thunder12345 That you can't spot any difference between them proves that either a) you're to poor for even a halfway decent audio setup or b) you're hearing impaired, meaning that c) you shouldn't mess with game audio one way or the other.
Crisp isn't what I'd call those, believe me, Goof (for a change), Nik, lizmann and Armhulen.

And yes, you are. Please stop being delusional and don't do the coder thing where you don't listen to feedback.

**Comment by Thunder12345** [comment]
@demonfiren So make some sort of comparison that demonstrates where this mythical difference is

**Comment by Niknakflak** [comment]
He added back the sounds but heavily reduced their quality and bitrate as well as converting them to mono.  So while the sounds are now no longer being removed, he's still making them sound like shit to save space that doesn't need to be saved because 9.8mb is nothing.

**Comment by Niknakflak** [comment]
:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1:

**Comment by demonfiren** [comment]
@Thunder12345 Literally everywhere.
Dullness and extra noise, most notable in Title1 which sounds like you're listening to it with water in your ears.

**Comment by Thunder12345** [comment]
@Niknakflak as far as I am aware there is no noticeable loss of quality compressing this way, it's the same method I use for all my oggs for playing. Please present some form of evidence for your case beyond "I know better"

**Comment by Niknakflak** [comment]
You're decreasing a bit rate from 41000 to 22000 and going from stereo to mono.  If you can't hear how much more shit quality it is, please stop working with sounds.

**Comment by Thunder12345** [comment]
@demonfiren doesn't sound any different to me, can you put the same clip of both versions together one after another so I can compare exactly the same way as you

**Comment by Thunder12345** [comment]
@Niknakflak please demonstrate how these changes alter the final sound, I know the changes I made you don't need to repeat them to me

**Comment by Niknakflak** [comment]
What the fuck do you want me to tell you.  Anyone with ears can listen to the version that's currently on server and then listen to your version and it's noticeably worse.  Listening to sound is subjective but reducing the bitrate is a science.  You are reducing the quality.  It is noticeable, and it does sound bad.  You are also again, all doing this to save space when we don't even have to.  There is ZERO reason to sacrifice quality for this space.

**Comment by Thunder12345** [comment]
@demonfiren oh and here's the punchline of this whole joke. Title1's bitrate wasn't changed, the only thing I did was make it mono. Stop bullshitting because you want to be the cool edgy anti coder player

**Comment by bgobandit** [comment]
how does this pass the code freeze,  incidentally

**Comment by Thunder12345** [comment]
Refactor, adds no new functionality

**Comment by demonfiren** [comment]
Whether or not you believe me and almost every other commenter on this PR on the sound issue, you are facing overwhelming opposition. That alone should tell you something.

**Comment by Thunder12345** [comment]
Is "whether or not you believe me" code for "I've been called out for not knowing what I'm talking about so I will now employ argumentum ad populum"

**Comment by Screemonster** [comment]
"Argumentum ad populum" isn't a fucking fallacy when it's talking about a subjective experience of quality, or do you honestly believe that yours are the Only True Objective Ears?

**Comment by Thunder12345** [comment]
Argumentum ad populum in this case being "hmm awful lot of thumbs downs they must be right"

**Comment by demonfiren** [comment]
Do I smell an absolute division between the server and codebase?

**Comment by bgobandit** [comment]
"Argumentum ad populum" isn't valid when the players are the ones who are going to be hearing this and so their opinion is in fact valid

**Comment by Screemonster** [comment]
"I and many other people, despite your personal feelings, do not find this loss of quality to be an acceptable cost for the meager savings in filesize" is not argumentum ad populum, and saying that it is amounts to just plugging your ears and yelling lalala when you get feedback you don't like.

**Comment by Thunder12345** [comment]
Just produce the comparison I asked for and I'll be satisfied

**Comment by Thunder12345** [comment]
Keep in mind here that if we're at 80+ player high pop and everyone needs to redownload the rsc because it's been updated, an extra 10 MB to every player is almost a gigabyte of resources that didn't need to be sent. The single 10 MB one person sees rapidly adds up if it has to go to every single person.

**Comment by Niknakflak** [comment]
Mr. Phaeron, close this PR.

**Comment by Thunder12345** [comment]
Why!

**Comment by Niknakflak** [comment]
I download 60mb even when I have to redownload everything.  50mb =/= close to a single gb

**Comment by Iamgoofball** [comment]
FROM OUR SOUND GUY:
Cuboos: Uh, 41000 down to 22000 yes you absolutly will notice a difference in quality

**Comment by Thunder12345** [comment]
Perhaps you need to practice your reading comprehension. I never said any single person has to download anything more than the 10 MB. The issue is in cases where the server has to send that 10 MB to several dozen people at once. It's those updates during high pop where, between all 80+ people, the server has to SEND OUT nearly a gigabyte that I can safe it from ever having to do.

**Comment by Thunder12345** [comment]
@Iamgoofball I can always put the ones that were originally 41000 back up to that if it'll stop the reeing, but it's not going to make any difference to title1 or title2, given they were always 22000

**Comment by Iamgoofball** [comment]
You also made them mono. This is heavily noticeable to people with headphones.

**Comment by Thunder12345** [comment]
Well isn't that funny, I actually had to remove something to reduce the filesize. Who'd a thunk. Just how much does it being in mono actually affect their experience. Looking back here to my original point that you listen to this for maybe 2 minutes maximum per round. Is losing your 2 minutes of lobby music sounding different in each ear so utterly experience ruining?

**Comment by Niknakflak** [comment]
If everyone downloads 60mb of data and there are 80 people on the server that's already close to 4gb.  You're saving like what 200mb or something not even client side.  I dunno, were reaching into MSO territory now, but it's still a hard as fuck :-1: because its shitty quality

**Comment by Cuboos** [comment]
Dude... there is a massive noticeable difference in quality. Title3.ogg is missing all the subtle music notes. Title2.ogg sounds like a crappy rip from a GBA game and Title1.ogg is so muddy and un-clear it's garbage. The fuck is wrong with 41000? That is like the perfect balance between quality and file size. There's a reason most games (until very recently) still use a 41000 sample rate. There is literally no need to change the file size on the title music.

**Comment by Thunder12345** [comment]
I don't understand where you get 200 MB from

At 64 MB X 80 players it's 5120 MB total
54.3 MB X 80 is 4344 MB

5120 MB - 4344 MB = 776 MB

Your result seems to be out by a factor of 3.88

I agree though that it's @MrStonedOne's call in the end because he's the one who knows how much of an impact this has

**Comment by Thunder12345** [comment]
@Cuboos as I explained to demonfiren, I didn't touch the bitrate of title1, so I don't know why you're saying it sounds any different

**Comment by Cuboos** [comment]
@Thunder12345 i think it's pretty clear you did.

**Comment by Thunder12345** [comment]
Feel free to open both versions in audacity like I did and compare

**Comment by Cuboos** [comment]
Hah... audacity... fucking pleb

**Comment by Thunder12345** [comment]
Easy to use, free, works, what more do you need

**Comment by Nienhaus** [comment]
Cuboos what ever happened to "Cuboos sound s1 e2" we need better high quality sounds in all of SS13.

**Comment by Cuboos** [comment]
That got merged a while ago.

**Comment by Nienhaus** [comment]
I was making a joke because I only have a PR named "Cuboos sound s1 e1" and not a "Cuboos sound s1 e2"

**Comment by KorPhaeron** [comment]
>argumentum ad populum when its about whether people like music or not

lmao

**Comment by Thunder12345** [comment]
I was really meaning how he was appealing to popular opinion when there is no clear sign of what the playerbase at large thinks

**Comment by Tofa01** [comment]
## **Side By Side Comparison Clip Of Both Uncompressed And Compressed Audio**
This is a side by side of both compressed and uncompressed versions of the music. In my **_OPINION_** the compressed song sounds more "Flat" especially the guitar parts. 

## **Video**
[https://youtu.be/P9BK7fRmh00](url)

**Comment by KorPhaeron** [comment]
Tofa is my favourite new coder

**Comment by Tofa01** [comment]
:)

**Comment by Nienhaus** [comment]
Same.

**Comment by Cuboos** [comment]
@Tofa01 404 not found.

**Comment by Nienhaus** [comment]
I had to copy it into my address bar.

**Comment by Thunder12345** [comment]
@Tofa01 doing gods work.

When listening to them side by side can see there is a very slight difference, but I dunno if it you would notice if you weren't listening to them side by side. I'll go back to the 41000 versions in the morning and see how they compare in size.

**Comment by Thunder12345** [comment]
Also you can remove the revert/removal tag nothing is actually being removed any more

**Comment by Screemonster** [comment]
so much for the "they're getting compressed and that's not up for debate" bit of the commit title then

**Comment by Thunder12345** [comment]
Except they still would be getting compressed, by going from stereo to mono. Halving the bitrate actually, in my experience, doesn't reduce the size nearly as much as stereo -> mono does

**Comment by Cuboos** [comment]
Just watched the video, you can barely hear the main instruments in the compressed version.

**Comment by Niknakflak** [comment]
You should listen to title4.  Thunder's version sounds fucking atrociously awful.

**Comment by Tofa01** [comment]
## **An Update On The Comparison Video I Made**

Just ran some further tests it seems to be that the conversion of the audio from a Stereo format to a Mono format seems to be what causes the drastic drop in audio quality. I am a bit of a audiophile myself my **_Theory_** is that while listening to stereo music the user is able to hear a much wider Sound stage (Not something i made up its an actual thing) this means that the listener is able to more easily distinguish different instruments from each other and able to tell where they are on say a stage. Converting to mono means you loose a lot of that sound stage as all the audio is kinda "mushed" into one audio channel.

**Comment by Supermichael777** [comment]
Thunder get your ears checked

**Comment by MrStonedOne** [comment]
Ya, stop trying to convert sounds to mono, some of them use that info more then others, and does lead to a very dry sounding clip.

Find a program that detects identical stereo channels and only converts those.

Also, as far as rsc goes, server wise we can handle it fine. /tg/ is one of the smallest codebases in terms of rsc size.

The only concern is clients having to download them. Because byond is a meme, clients take forever to download rscs if they are further away from the server, regardless of their bandwidth.

One thing we could do ***Instead*** is move some of these away from the rsc, and instead manually send them to clients after they connect.

In fact most of the sounds could be done this way.

**Comment by Niknakflak** [comment]
Seems unpopular

**Comment by KorPhaeron** [comment]
>Seems unpopular

@tgstation/commit-access 

Can correct me if I'm wrong in closing this, MSO seems to have a less controversial alternative though

**Comment by MrStonedOne** [comment]
Ya, I know byond has the tools to do what i'm suggesting, I just need to do some research on how finicky they are, and then design some sort of systematic way to use it for passive resources thats not too harder to use than currently.

It's currently top of the todo list, but i have a few long/overtime work days ahead of me.

and there are a few features to pr once the freeze ends.

**Comment by optimumtact** [comment]
This PR makes me want to scoop my own eyes out with a spoon

**Pull request closed without merging**
