### PR TITLE
reopens my cult PR that was already merged, changes werent implemented due to the github stuff

### PR DESCRIPTION
**Pull request by imsxz**
https://github.com/tgstation/tgstation/pull/50997

### CODE REVIEW

**Comment by wesoda25** [comment]
hmm im not feeling it anymore 👎

**Comment by imsxz** [comment]
shut the fuck up piece of shit lookin ass bitch boy wannabe coder acting like he knows how to balance lookin idiot dumb

**Comment by saprasam** [comment]
bring back clock cult and i'll be appeased

**Comment by Nebulacrity** [comment]
Yeah, I miss Clock Cult too.

**Pull request merged**
