### PR TITLE
Allow heretic flesh ghouls to use ashen eyes and sickly blades

### PR DESCRIPTION
**Pull request by isaac-smothers**
## About The Pull Request

Heretic flesh ghouls can now use ashen eyes and the sickly flesh blade.

## Why It's Good For The Game

Current heretic flesh path is a great step into necromancy as you can make zombies and kit them out. However, as a heretic you also have the ability to create thermal amulets and sickly knives en masse, but your zombie minions can't use them. 

By enabling heretic flesh ghouls to use thermal amulets and sickly knives, the flesh path:

- Becomes a better competitor against rust and ash
- Carries a stronger theme of necromancy and conjuration
- Will have more synergy between its abilities

## Changelog
:cl:
code: Allow heretic ghouls to use the sickly blade and ashen eyes
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
changelog is what players will see ingame, theres no need to complicate it, just say what it does visibly to players

**Comment by MoonFalcon** [comment]
> changelog is what players will see ingame, theres no need to complicate it, just say what it does visibly to players

Roger that, just simplified it, thanks.

**Comment by ATH1909** [comment]
Why not let them use all three kinds of blades? It's gonna seem weird and inconsistent if they can only use one of them.

**Comment by MoonFalcon** [comment]
> 
> 
> Why not let them use all three kinds of blades? It's gonna seem weird and "inconsistent" if they can only use one of them, especially since the unupgraded blades aren't different from each other in any other way (other than sprites).

They can, this change allows them to use any sickly blade. The flesh blade is the only one that matters though since none of the other paths can summon ghouls with working hands.

**Comment by ATH1909** [comment]
> > Why not let them use all three kinds of blades? It's gonna seem weird and "inconsistent" if they can only use one of them, especially since the unupgraded blades aren't different from each other in any other way (other than sprites).
> 
> They can, this change allows them to use any sickly blade. The flesh blade is the only one that matters though since none of the other paths can summon ghouls with working hands.

Can't the other paths still grab the Voiceless Dead ritual?

**Comment by MoonFalcon** [comment]
Ah good point, I forgot about that.

**Pull request merged**
