### PR TITLE
Adds several new sound effects for the blood cult

### PR DESCRIPTION
**Pull request by ViktorKoL**
## About The Pull Request

A remake of this: https://github.com/tgstation/tgstation/pull/64770.
Adds a new sound effect for when the cult gains its red eyes, for when their halos appear, and a global sound effect for when the cult begins to draw a Nar-Sie rune.

https://github.com/tgstation/tgstation/assets/44502667/f9d478a0-5fc6-4c8c-aa1a-16b7f4e86203

https://github.com/tgstation/tgstation/assets/44502667/4dd40ec6-f501-405d-a8ed-f7214f6a6613

https://github.com/tgstation/tgstation/assets/44502667/6ee8962e-fdbb-41a8-8962-cc19cb0ea1b7

I should probably also note that in the process of folder organization, I moved the blood cult's old antag gain sound effect and renamed it. I hope it doesn't cause any issues...
## Why It's Good For The Game

All these occasions do not have a sound effect unique to them yet. I think they deserve it.
## Changelog
:cl:
sound: the blood cult's rise to power is now accompanied by several new sound effects
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
this is so awesome

**Comment by ViktorKoL** [comment]
One more thing I wanted to ask: should I bother adding some sort of a license file? I've read it makes work easier for contributors in the future, though I'm not sure how...

**Comment by Jacquerel** [comment]
The musical stings are cool but they seem to cut off _very_ abruptly.

**Comment by ViktorKoL** [comment]
> The musical stings are cool but they seem to cut off _very_ abruptly.

If you mean the sound's echo fading out too quick, I've done that in order to make sure the sounds aren't too long (see original PR). I can spread the fade out a bit more if you think it will sound better that way.

**Comment by DaydreamIQ** [comment]
I would love to see a full actual track for that summoning ritual. That shit goes hard

**Comment by ViktorKoL** [comment]
> I would love to see a full actual track for that summoning ritual. That shit goes hard

Feel free to see the original PR for that.

**Comment by iprice** [comment]
Sound effects are really useful ways to draw attention to information.

Love the full length original track too.  No idea if you'd get merged but could you maybe overlay it on a "cult major victory" (the one where the nuke fails), perhaps run some of the quieter part lead in under the cinematic noise (which is just the typical nuke scream iirc), disable the default round end sound, and just let it play out there?  Shame not to make use of the track.

**Pull request merged**
