### PR TITLE
Carp Mutant Tweaks

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Carp Mutant does somewhat encourage the kind of playstyle it's trying to, but it falls short of just bringing a lot of equipment especially considering the cost of becoming one. Swimming through space is admittedly really nice.

- Changes nomad from a negative event to a positive one
- Lungs can now adapt to breathe for 5 minutes of normal air, refreshed by visiting another zlevel (WIP).
- Carp teeth now also serve as crowbars.
- Carp tooth doesn't look awful anymore.

Thinking about adding some off-station self-healing ability, because space exploration ends up with you getting injured and needing to bring meds. Could be another way to make the carp-sploration more enticing.

## Why It's Good For The Game

Nomad being a negative event didn't really ever trigger, 10 minutes on station as a carp mutant just makes zero sense and it is accomplishing the same job the lungs would but with a -3 moodlet. Now it's a nice reward for getting out there. You *should* not have to worry too much about mood as a carp mutant exploring, which is better than having to manage it more.

One problem I found is that I wanted to return and give people my loot, but being on station basically required a healing virus since I could not wear a mask (by design). By changing it to an ability to stay on station for 5 minutes, that should give a good interval to do some stuff. If you really want to stay longer, just leave and come back! Take your carp lungs out for a walk.

Carp teeth felt like they were in a weird spot. They're something you can hand out to people, but... see the above. Beyond that, you probably find better combat weapons... INCLUDING YOUR OWN TEETH, because your teeth can knock down. So I gave it some space exploration utility. I might also change them to shed upon visiting a zlevel you have never seen before. Maybe. The probability thing seems kinda meh, but it should be guaranteed to get a tooth after enough time just statistically so I don't care that much.

## Changelog
:cl:
balance: Changes nomad from a negative event to a positive one
balance: Lungs can now adapt to breathe for 5 minutes of normal air, refreshed by visiting another zlevel (WIP).
balance: Carp teeth now also serve as crowbars.
image: Carp teeth don't look so ugly anymore.
/:cl:

### CODE REVIEW

**Comment by MercuryArrow** [comment]
> One problem I found is that I wanted to return and give people my loot, but being on station basically required a healing virus since I could not wear a mask (by design)

This was always easily overcome by wearing a sealed helmet, since you can still use those to enable internals as a carp mutant - not that you ever had to, the carp lungs have never actually had the intended behaviour of making oxygen do suffocation outside of situations with higher than normal concentrations of O2, from what I've seen. That said, if this means the lungs are finally going to be fixed, it's still a good change.

The rest of the tweaks are nice little quality of life things, but really, carp was already one of the better infusions overall since a spaceproofing mutant kit is one of those things that's useful to everyone at some point or another.  Nomad being a positive is very nice.

**Comment by tralezab** [comment]
> > One problem I found is that I wanted to return and give people my loot, but being on station basically required a healing virus since I could not wear a mask (by design)
> 
> This was always easily overcome by wearing a sealed helmet, since you can still use those to enable internals as a carp mutant - not that you ever had to, the carp lungs have never actually had the intended behaviour of making oxygen do suffocation outside of situations with higher than normal concentrations of O2, from what I've seen. That said, if this means the lungs are finally going to be fixed, it's still a good change. That said, I'm dubious about making the lungs TOO punishing - many newer space ruins have their own internal atmos and atmosfans at the airlocks to prevent leakage. Being too prissy about O2 harming the carp mutants would, ironically, actually prevent them from making the most of their exploration.

I drafted because I wanted to get this kind of feedback, so thank you. At most, the lungs mean if you're staying on the station for longer than just a drop off that you have to occasionally dip out into space just for a moment which seems fair enough, the ability to grant yourself 5 minutes of breathing oxygen is a pleasant way to encourage space ruin hopping both in space and with pressurized oxygenated ruins while not banishing carp mutants away from the station... while still being a restriction! I'll make adjustments if it seems too unfair, but I don't want people just sidestepping a big downside of carp mutant

...That being said, I'm somewhat glad people are sidestepping it right now because the original idea of just "no oxygen idiot" is a bad idea. But let's make it good.

> The rest of the tweaks are nice little quality of life things, but really, carp was already one of the better infusions overall since a spaceproofing mutant kit is one of those things that's useful to everyone at some point or another. Nomad being a positive is very nice.

👍 - my experience too. Carp's generally in a good spot, just touching things up from my own gameplay (i lived but had some notes pr). I really should work on new mutants.

**Comment by EricZilla** [comment]
Since you are already here, I was considering adding a carp tail for fully mutated fish folks and maybe some fin ears for the brain, would you be interested in any of that?

**Comment by tralezab** [comment]
> Since you are already here, I was considering adding a carp tail for fully mutated fish folks and maybe some fin ears for the brain, would you be interested in any of that? I'd do the spritework
> 
> I did a quick draft up of what I had in mind: carp example I figure there are two options, either it uses mutant color so everyone has different random fish colors like they are in nature, or I can do a nicer looking palette based on the carpskin sofa/suit but everyone looks the same

"would i be interested in that" come on listen to you OF COURSE I WOULD LOVE THAT

**Comment by moocowswag** [comment]
I think this is probably the best place to leave my feedback after using carp mutant yesterday

in its current state its really good, the negative moodlet is easy to overcome with the positive moodlets, the inability to breath o2 is forgiving and gives you alot of time to the point where you can safely exist in the station for pretty long periods

I was orbiting around the station with a laser musket as a lizard never leaving the z level just shooting spiders through the exterior glass windows and for once being okay with my room being breached

**Comment by tralezab** [comment]
> I think this is probably the best place to leave my feedback after using carp mutant yesterday
> 
> in its current state its really good, the negative moodlet is easy to overcome with the positive moodlets, the inability to breath o2 is forgiving and gives you alot of time to the point where you can safely exist in the station for pretty long periods
> 
> I was orbiting around the station with a laser musket as a lizard never leaving the z level just shooting spiders through the exterior glass windows and for once i was okay with my room being breached

If you have some notes for other mutants I'll take em

**Comment by EricZilla** [comment]
> 
> "would i be interested in that" come on listen to you OF COURSE I WOULD LOVE THAT. Let's do regular carp color so it doesn't get confused with a lizard tail

wagwagwag
*wag

**Comment by carlarctg** [comment]
Adding a regeneration factor like carp have but only while the player is outside would be both incredibly thematic and make this alluring for space travel without actually impacting balance in any real amount.

**Comment by tralezab** [comment]
ok im being an andy but i will get back to this

**Comment by carlarctg** [comment]
Closer Andy

**Pull request closed without merging**
