### PR TITLE
Makes the roundstart cargo ripley unable to use drills

### PR DESCRIPTION
**Pull request by TheBonded**
## About The Pull Request
Removes the roundstart cargo ripley's ability to have drills installed. Does not affect ripleys built or found during the round.

## Why It's Good For The Game
The roundstart cargo ripley is intended for hauling freight. Let's not give cargo an efficient crate opener and wall destroyer, shall we? 

## Changelog
:cl:
balance: The roundstart cargo ripley can no longer use drills.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
there are 100 other ways to approach this, like making drills a researchable item or adding a proper cargo mech dedicated only to hauling cargo

lazy :-1:

**Comment by TheBonded** [comment]
> there are 100 other ways to approach this, like making drills a researchable item or adding a proper cargo mech dedicated only to hauling cargo
> 
> Will close in 24 hours and let someone approach this properly
> 
> lazy 👎

Fair enough. I'll do some research and come back later to try to approach this properly. I'll let you close this since I'd like to see what suggestions other people might have for a better way. Apologies for making a sub par pull request.

>adding a proper cargo mech dedicated to only hauling cargo
I'm pretty sure that's what this mech was supposed to be, unless I understood the original pr incorrectly, since it only has two equipment slots and has less integrity compared to other ripleys. When I suggested making it unable to use drills on the original pr, the author said they weren't experienced enough to do that but would be happy if someone else coded it for them

>lazy 👎
Spending more time than is required on something that would be fundamentally the same seemed like a waste of time. This only affects one mech per round, so putting in a bunch of time to change the way drills worked seemed like overkill when it only affects a single vehicle. I'll try to do better next time

**Comment by cacogen** [comment]
I don't think he's being lazy I think he's using the solution he has available to him based on his coding knowledge. People would bear down on him if he locked drills behind research to solve this. And as he said, doing that or trying to make an entirely new mech instead of just further nerfing the Ripley subtype to fix this seems like overkill.

I'm not a guncargo player because guns are functionally useless when you can't hit anything because of the latency from here to MSO's weed fort but I'm sure I'll find some crate to benefit from it having an inexplicable hardpoint for drills.

**Comment by optimumtact** [comment]
They will never have opportunities for learning if they don't start any projects outside their current skill level

**Comment by TheBonded** [comment]
@optimumtact  since no one has left any feedback here, do you have any ideas of what you'd like to see replace this fix?

I was thinking of just making a new type of mech under vehicles/mecha/cargo or vehicles/mecha/hauling. Maybe I'll even make multiple types for different types of hauling, like one made for atmos with a built in scrubber and made for hauling canisters. Perhaps every department can get a specialized type of exosuit researchable and buildable during round. 

If you think that's a bad idea, what would you suggest?

**Comment by optimumtact** [comment]
Just make a cargo mech who's job is soley moving crates

it doesn't get attachements, it doesn't get armour or health, or anything. It can just carry 4 crates and moves at regular human speed.

**Comment by TheBonded** [comment]
> Just make a cargo mech who's job is soley moving crates
> 
> it doesn't get attachements, it doesn't get armour or health, or anything. It can just carry 4 crates and moves at regular human speed.

Shouldn't it have something to incentivize people to use it instead of a ripley? Maybe it'd be slightly faster than human speed, or something else to make it not a worse ripley

**Comment by optimumtact** [comment]
the ripley will be something you build, not roundstart.

that's the difference

**Comment by TheBonded** [comment]
> the ripley will be something you build, not roundstart.
> 
> that's the difference

Fair enough, I'll get to spriting

**Comment by Pugie** [comment]
Wall destroying ripley=not an issue -> welding tools exist
Crate opening=also not an issue -> pka's can open crates, private purchasing exists (even if you don't wanna private buy everything you just do that for emitters and then open every crate with the two you get from that)

**Comment by optimumtact** [comment]
nobody asked you stinky

**Comment by Pugie** [comment]
> nobody asked you stinky

mwah

**Pull request closed without merging**
