### PR TITLE
Fixes welding tools being unable to refuel (SPEEDMERGE)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Armhulen** [comment]
S P E E D M E R G E

**Comment by tedward1337** [comment]
This didn't even compile ahhhhhhhh

**Comment by Xhuis** [comment]
___ARE YOU FUCKING SERIOUS?___

**Comment by KorPhaeron** [comment]
I mergee it before travis finished, it compiles

**Comment by Xhuis** [comment]
Oh thank god

**Pull request merged**
