### PR TITLE
Revert "Removes shuttle STV5 from purchase (Shuttle changes #3)"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#23905

# just remove the explosives

### CODE REVIEW

**Comment by Armhulen** [comment]
within SECONDS

still, I agree

**Comment by WJohn** [comment]
kneejerk revert etc

**Comment by optimumtact** [comment]
I've had enough of the shuttles that are memes frankly.

**Comment by optimumtact** [comment]
I dont' see how you can justify this @Cheridan this is just a straight revert of the other pr without even doing the changes everyone suggested.

People are always saying do X and then leaving it up to the person removing some garbage shit to fix it instead of fixing it themselves

**Comment by Cheridan** [comment]
This can be left up while a fix is pending. There isn't any major issues with this shuttle aside from the exploding crates.

**Comment by optimumtact** [comment]
It's a garbage shuttle cheri, that's why they reverted it in the first place

**Comment by Cheridan** [comment]
Still, you ignored the maintainer feedback on the pr and merged it yourself without further discussion "because I'm sick of shuttles." This is still a team effort.

**Comment by optimumtact** [comment]
Well they never listen to me cheri but you dont' seem to care about that

**Comment by KorPhaeron** [comment]
@Iamgoofball 

Please make a PR that both readds it and removes the explosives

**Comment by Iamgoofball** [comment]
will do

**Comment by KorPhaeron** [comment]
okay goof is going to make a better PR and I'm going to merge that

**Pull request closed without merging**
