### PR TITLE
Luxury Elite Bar Capsule

### PR DESCRIPTION
**Pull request by Narcissisko**
Adds a new luxury bar capsule to the miners vending machines which cost ten thousand mining points

This gives miners a reason to continue mining instead of just getting bare minimum materials needed. It also adds extra content to just generally have more fun with.

:cl:
added: shelter_3.dmm map to templates for use as shelter capsule and makes up a majority of the additions
added: More lines to three files under the mining module to add the capsule
/:cl:

https://i.imgur.com/TrWlRoz.jpg
https://i.imgur.com/W2JBm7S.jpg
https://i.imgur.com/HXklGpW.jpg

### CODE REVIEW

**Comment by optimumtact** [comment]
I_think_it's_kicked_in

**Comment by Tlaltecuhtli** [comment]
are the toilets needed? like it ruins the symmetry, why not a vaping zone there instead?

**Comment by Narcissisko** [comment]
> are the toilets needed? like it ruins the symmetry, why not a vaping zone there instead?

Because the vaporwave turf doesn't always appear for some reason and seem to be bugged

**Comment by Shadowflame909** [comment]
We need a bartender in stasis for 10 grand mining dollars

**Comment by Fikou** [comment]
put a space bartender sleeper there if real

**Comment by Borisvanmemes** [comment]
Some type of robot/hologram bartender that can't leave the capsule would be better then just a space bartender spawner, but that's most likely way outta scope for this PR isn't it?

**Comment by anconfuzedrock** [comment]
bardrone

**Comment by Swagile** [comment]
> 
> 
> bardrone

this

my god this is a great PR

really makes me think a good space ruin would be a bunch of abandoned pods used as hallways linked together by normal capsules, luxury capsules for heads of staff, and the bar capsule as the meeting room for all of them

**Comment by Dennok** [comment]
> > bardrone
> 
> this
> 
> my god this is a great PR
> 
> really makes me think a good space ruin would be a bunch of abandoned pods used as hallways linked together by normal capsules, luxury capsules for heads of staff, and the bar capsule as the meeting room for all of them

Need to add, cargo, science, engineer and etc. capsules, 
and we can buy "fast build your own station" kit.

**Comment by Swagile** [comment]
> 
> 
> > > bardrone
> > 
> > 
> > this
> > my god this is a great PR
> > really makes me think a good space ruin would be a bunch of abandoned pods used as hallways linked together by normal capsules, luxury capsules for heads of staff, and the bar capsule as the meeting room for all of them
> 
> Need to add, cargo, science, engineer and etc. capsules,
> and we can buy "fast build your own station" kit.

Cargo is questionable due to how the shuttle works, but science, engineer capsules are doable.

**Comment by ExcessiveUseOfCobblestone** [comment]
if I knew my sides were going to be stolen I wouldn't have went down this PR...

**Comment by Tlaltecuhtli** [comment]
you can do cargo (express console )

also if you want to add a way for people to create a station with pods, add empty pods with directional doors and different size to people fill in with machinery ( fill them if you are feeling creative)

**Comment by Dennok** [comment]
> you can do cargo (express console )
> 
> also if you want to add a way for people to create a station with pods, add empty pods with directional doors and different size to people fill in with machinery ( fill them if you are feeling creative)

I start from R&D,  just copy R&D from station and add servers to it.

Someone i see make station that fit in dorms.

**Pull request merged**
