### PR TITLE
Legitimately closes all issues in the issue tab.

### PR DESCRIPTION
**Pull request by kilkun**
i removed every thing that was causing issues and everything that could potentially cause issues and replaced it with high quality hand written pre-compiled and obfuscated code organized in msq blocks except for the executable that uses some antiquated microsoft compression that i forget the name of on top of XOR encryption. now only cool dudes with pro tools can make contributions because you have to use a hex editor and i lost the documentation that goes with everything so good luck if you lack 1337 h4xx0r sk1llz

finally we can end this feature freeze and get back to quality balance discussions that quickly devolve into flamewars.

# **thank me later**
(not compatible with anything past windows 98 _unless you use an emulator_)

### CODE REVIEW

**Comment by ShizCalev** [comment]
I think this breaks chem.

**Comment by lzimann** [comment]
fix the conflicts so we can merge please

**Comment by Mervill** [comment]
Feels like a balance issue to me

**Comment by kilkun** [comment]
the only balance issue is that looking at anything causes +200 burn damage to the eyes

**Comment by kilkun** [comment]
still working out the kinks

**Comment by Haevacht** [comment]
You are a fucking idiot, and entirely useless.

**Comment by kilkun** [comment]
lol

**Pull request closed without merging**
