### PR TITLE
Refactors the Prison Break event into the Grey Tide event

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
experimental: The Greytide Virus got some teeth.
/:cl:
dreamseeker_2016-06-04_15-34-35

it now picks 1-3 departments to open up.

### CODE REVIEW

**Comment by Man-Shroom-** [comment]
It should announce which departments are now open and also open windoors

**Comment by Bawhoppen** [comment]
no changelog needed for this

**Comment by KorPhaeron** [comment]
It's still pretty meaningless if you dont give any sort of permission to cause a mess. Doesnt matter if the door is open if admins ban people for taking advantage of it.

**Comment by ChangelingRain** [comment]
here's a fancy list of areas it'll open for each, because >goof didn't provide that

##### Security:
1. Vacant Office
2. Security Checkpoint
3. All Department Security Checkpoints
4. Armory
5. Brig
6. Permabrig
7. HoS Office
8. Prisoner Transfer Center
9. Gulag

##### Engineering:
1. Engine Room, including external airlocks
2. SMES Room
3. CE Office
4. Engineering Foyer
5. Gravity Generator

##### Atmospherics:
1. Literally only Atmospherics itself

##### Bridge:
1. Bridge
2. Meeting Room

##### Cargo:
1. Cargo Office
2. Cargo Bay
3. Mining Dock
4. Warehouse

##### Medbay:
1. Research Division, yes, this is the main science hallway area/entrance
2. Medbay
3. Chemistry
4. Medbay Treatment Center
5. Morgue
6. Genetics
7. CMO Office
8. Virology

##### Science:
1. R&D Lab
2. Experimentor Lab
3. Toxins Mixing Room
4. Toxins Storage
5. Testing Lab
6. Xenobiology Lab
7. Toxins Testing Range

**Comment by bgobandit** [comment]
@KorPhaeron Then tell admins not to ban people for it this is literally your job

**Comment by KorPhaeron** [comment]
Easier to add a pseudo antag permission in game

**Comment by Iamgoofball** [comment]
@KorPhaeron why are admins banning people for going through open doors?

**Comment by KorPhaeron** [comment]
Stealing shit I mean

**Comment by Iamgoofball** [comment]
not my problem

**Comment by KorPhaeron** [comment]
Lights out in 3 random departments is way less exciting than dealing with a flash mob

**Comment by Iamgoofball** [comment]
@KorPhaeron you realize it still bolts open all the doors and shit right

**Comment by Anonmare** [comment]
Opening and boltinf open doors is enough to cause chaos.

Say it's a rev round and Sec/Heads of Staff has boarded themselves up in cargo then "beep boop greytide :^))))" All the cargo doors are bolted open.

**Comment by Bawhoppen** [comment]
srry they'd be banned first cause dumb hiding rules :expressionless:

**Comment by LatD** [comment]
This gives antags good opportunities to go and steal stuff behind closed doors. I like this.

**Comment by Davdichan** [comment]
Bridge should include HoP Office, Teleporter and Captain's office. Make it a slightly rarer event but one that is too good to pass up.

**Comment by Iamgoofball** [comment]
@Davdichan i'd have to touch every map file to fix that

**Comment by Davdichan** [comment]
@Iamgoofball Well shit a man can dream.

**Comment by optimumtact** [comment]
So it's the same but now it picks a random department?

**Comment by Iamgoofball** [comment]
1 to 3 random departments. The event tells you how many were opened, but not which ones. I figured people would notice them being opened since it opens every door in picked departments

**Comment by optimumtact** [comment]
This should be fun

**Pull request merged**
