### PR TITLE
Surgical Tables XVIII: The Return: The Saga Continues (final)[1]

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Wow look at this beautiful surgical table, sprited by imaginos
image

Whoa look it even has the right offsets
image

## Why It's Good For The Game

This sprite was all ready to go but the person who made the PR didn't know how to apply the bed offsets so I have nobly stepped up to the challenge

## Changelog

:cl: Imaginos
image: A new sprite for oeprating tables
/:cl:

### CODE REVIEW

**Comment by CoiledLamb** [comment]
this is gonna be the one, i can feel it!

**Comment by Cheshify** [comment]
I like this one

**Comment by nikothedude** [comment]
sorry chief that little red light and its socket are actually copied from goon sprites we're gonna need another total resprite

/s

**Comment by Cheshify** [comment]
sorry bro you used the same color as goon did they're sending the copyright deathsquad to your house.

**Comment by TheVekter** [comment]
Was this approved by Goon

**Pull request merged**
