### PR TITLE
REMOVES feetposters

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

removes the word "feet" from ai vox

## Why It's Good For The Game

fetish content

## Changelog
:cl:
sounddel: removed feet
/:cl:

### CODE REVIEW

**Comment by ninjanomnom** [comment]
ai vox is basicaly asmr which is fetish content and should be removed entirely

**Comment by TheRespectedMan** [comment]
redpilled

**Comment by plapatin** [comment]
ninjanomnom loves feet confirmed

**Comment by Fikou** [comment]
> ai vox is basicaly asmr which is fetish content and should be removed entirely

wtf i cant believe ninjanomnom loves feet so much

**Comment by fludd12** [comment]
This PR sure was a feat of programming intellect.

**Comment by Ty-the-Smonk** [comment]
@fludd12 e n d

**Comment by wesoda25** [comment]
Merge this now ive been harassed by the playerbase as a whole

**Pull request closed without merging**
