### PR TITLE
Splits NOEYES flag.

### PR DESCRIPTION
**Pull request by AnturK**
Closes #43632

Stop making lazy PRs. Dunno about golems and other stuff, honestly this flag is complete nonsense because they do have eye organs.

### CODE REVIEW

**Comment by Barhandar** [comment]
I think that non-antag golems (durathread, bone, ARGUABLY capitalist and communist) are a victim of copypasta and should not have NOFLASH. The antag ones could technically keep it, but bloods don't make golems and clock is gone, so the only source is the lavaland golems, + they can just wear protection.

Also shadowpeople should NOT have NOFLASH, they're vulnerable to bright lights so being flashproof is against the point (if anything, they need to be vulnerable to flashes regardless of protection).

**Comment by Barhandar** [comment]
The new name is hideous


NOEYESPRITES, NOEYEICONS, NOEYEVARIANCE, SCREWDRIVEREDATBIRTH

**Review by ShizCalev — APPROVED** [review]

**Comment by XDTM** [comment]
noflash could potentially become a trait

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/issues/43255

**Comment by ATH1909** [comment]
Guys, let's delay the merging of this by one or two days so that the issue will have been fixed over a month after it was initially reported (which sounds much more impressive than "almost a month after it was initially reported").

**Pull request merged**
