### PR TITLE
Basic Mobs can run away

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

That's right I'm still atomising #71421, some day I might even post something related to carp.
This PR adds various behaviours to basic mobs allowing them to run away, in a couple of variations.

Mice will flee from anyone who doesn't share their factions, at all times (so they will scatter from most humans, but not regal rats). 
Rabbits and Sheep will flee from anyone who has attacked them.
Pigs will run away from people who have attacked them, but only if they're below half health.

https://user-images.githubusercontent.com/7483112/207127135-d1737f91-d3f7-468a-ac60-7c7ae5d6623d.mp4

Mice are still plenty catchable because they don't run _very far_ (or very fast) but I think the chase will be good enrichment.

To achieve this I had to change the signal COMSIG_CARBON_HEALTH_UPDATE into COMSIG_LIVING_HEALTH_UPDATE but frankly the latter seems more sensible anyway.

## Why It's Good For The Game

More behaviours to use later when designing mobs, gradually gives mobs more things to do rather than just sort of moving aimlessly around the area you left them in.
It'll give people hunting rats in maintenance some exercise.

## Changelog

:cl:
add: Mice will now run away from you, you have to catch them if you want to eat them. Use those traps!
add: Rabbits, Sheep, and Pigs likewise won't just sit there and let you pulverise them if they can see an escape route.
/:cl:

### CODE REVIEW

**Comment by Overuseddart** [comment]
Will this break fauna and megafauna code? Might be worth testing because for some reason they break every time mobs are updated.(See mobs have action buttons)

**Comment by Jacquerel** [comment]
> Will this break fauna and megafauna code? Might be worth testing because for some reason they break every time mobs are updated.(See mobs have action buttons)

No it won't, as it also didn't in the numerous other basic mob AI PRs which have been merged over the past several weeks and which neither all but one mining fauna nor any megafauna use.

**Comment by Overuseddart** [comment]
> > Snip?
> 
> No it won't, as it also didn't in the numerous other basic mob AI PRs which have been merged over the past several weeks and which neither all but one mining fauna nor any megafauna use.

Alright, my fault for not keeping up with basic mob prs.

**Comment by optimumtact** [comment]
image

**Comment by the-orange-cow** [comment]
Will hostile mice from regal rats still attack?

**Comment by Jacquerel** [comment]
> Will hostile mice from regal rats still attack?

Yes, they have a separate AI controller which does not understand fear.

> If a mouse flees, does that prevent me from dragging it behind me like a pet?

If it is being dragged then it will cease moving, however it _will_ try to run away the second your grip slips.

**Comment by Wallemations** [comment]
Do pet mice (like Tom) stay put for humans?

**Comment by Jacquerel** [comment]
> Do pet mice (like Tom) stay put for humans?

Good catch, Tom is now no longer scared of humans.

**Pull request merged**
