### PR TITLE
Dissection/Revival Surgery made more easily accessible

### PR DESCRIPTION
**Pull request by terranaut1**
## About The Pull Request

Makes Dissection surgery available at roundstart
Makes Revival surgery available much quicker (New: Base -> Biotech -> WT Surgery -> Advanced Surgery -- Old: Base -> Biotech -> Advanced Biotech -> WT Surgery -> Advanced Surgery -> Experimental Surgery)

## Why It's Good For The Game

Gives MDs something to do and lets them generate some research points at roundstart so they/the CMO can then aggressively bully RnD into researching more surgeries or other medical shit instead of having to beg for it an hour into the game.
Dissecting a monkey gives 1000 research points, dissecting a human gives 2000. The mob needs to be dead, live dissections are not possible. This is unchanged from what it was. I originally tweaked those down a bit (750 and 1500) but since Medical will run out of monkeys quickly if there's an eager MD and would require interaction with Genetics to produce humans I think this is fine and ended up changing my mind about it.

Makes Revival Surgery much faster to research, giving MDs access to it likely before the cloner is fully upgraded, producing a viable alternative to just having a guy lounge around near the cloner.

## Changelog
:cl:

balance: Dissection Surgery removed from Advanced Surgery, made available at roundstart
balance: Revival Surgery from Experimental Surgery down to Advanced Surgery
balance: Skipping the Advanced Biotech requirement for the surgery tree, making it available a step earlier

/:cl:

### CODE REVIEW

**Comment by CPTANT** [comment]
Cool!

Maybe it's a good idea to lower the price of experimental surgery now revival has been removed. The remaining procedures are either minor buffs or gimmicks. 

Maybe 4000 or even 3000?

**Comment by 81Denton** [comment]
Looks good to me

**Comment by adamkad1** [comment]
Can we let medborgs do dissection surgery?

**Comment by ExcessiveUseOfCobblestone** [comment]
44821 will

**Comment by adamkad1** [comment]
what will 44820 do then

**Comment by ExcessiveUseOfCobblestone** [comment]
something completely unrelated I imagine.

44821 is the PR number beside the title.

**Comment by adamkad1** [comment]
also i suppose this would mark the time when medborgs should get 'surgical tool upgrade module'

**Pull request merged**
