### PR TITLE
Holy Water no longer stacks stuttering time infinitely

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
fix: Holy Water no longer leaves you stuttering for years.
/:cl:

By the way, we have no way of healing stuttering aside from adminordrazine or being hit by beepsky.

### CODE REVIEW

**Comment by Supermichael777** [comment]
should probably clamp stuttering in onlife actually

**Comment by ExcessiveUseOfCobblestone** [comment]
Why would medbay stutterwhores create the cure for stuttering? THINK DUKE THINK

**Comment by lordpidey** [comment]
How long does 10 stutter leave you stuttering?

**Comment by XDTM** [comment]
10 seconds/ticks

**Comment by Supermichael777** [comment]
10 life ticks so about 30 seconds

**Comment by XDTM** [comment]
If it ticks down at the same speed as things like Weaken, i think it's seconds, or we'd have Weaken(3) stunning for 9 seconds

**Comment by lordpidey** [comment]
I'd say we should cap it at a minute.

**Comment by XDTM** [comment]
Eh, usually when a chem is no longer in your body the effect does not persist for long, i don't see why it would be different with holy water

**Comment by Cheridan** [comment]
We need to clamp a lot of values like this. Mob code's a mess.

**Pull request merged**
