### PR TITLE
Revert "Server polls create only when done being made"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#28697

Removes needed column needlessly

### CODE REVIEW

**Comment by Jordie0608** [comment]
I don't understand the function; why wouldn't you want to count an option?

**Comment by MrStonedOne** [comment]
Abstain is suppose to basically be a non-vote, so counting it when showing the percentages seems lame and i've always supported this.

**Comment by Jordie0608** [comment]
I think abstains are still important data to show to see who non-voted =P
I'll ask @atlanta_ned about it, perhaps a toggle to hide/unhide abstains is possible.

That aside, I'd like to at least rename the column and rework the alert so it's more clear what they do.
Are there any other missing functionalities here?

**Comment by MrStonedOne** [comment]
its not about hiding the vote, its not not counting it in the percentage of other votes:

option a: 45
option b: 45
abstain: 10

What looks better:

option a: 45%
option b: 45%
abstain: 10%

**or**

option a: 50%
option b: 50%
abstain: -

**Comment by Jordie0608** [comment]
Er yes, that's what I meant sorry.

**Comment by Cyberboss** [comment]
I think this is dealt with

**Pull request closed without merging**
