### PR TITLE
Revert "Makes some get_step(..., 0)s use get_turf(...)"

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/tgstation#34120

hey look ```code\game\gamemodes\antag_spawner.dm:53:error: ?:: missing comma ',' or right-paren ')'```

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
tested locally: changing in_range to the get_step version removes that error

**Comment by praisenarsie** [comment]
@Cyberboss @SpaceManiac

**Comment by RemieRichards** [comment]
To be fair, @Cyberboss also wrote ```source``` twice in his conversion, instead of 1 ```source``` and 1 ```user```

**Comment by Cyberboss** [comment]
b l a m e   m s o

**Comment by praisenarsie** [comment]
blame yourself for not spotting mso's shitcode ;)

**Pull request merged**
