### PR TITLE
Simple animals can be hurt by lightning/tesla

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Instead of just returning 0 for some reason

### CODE REVIEW

**Comment by GunHog** [comment]
Are there any mobs that should resist or ignore tesla shocks that would be affected negatively by this?

**Comment by lordpidey** [comment]
Hmm, perhaps cockroaches and caks?

**Comment by KazeEspada** [comment]
Apparently Goofball said drones when I asked him why simple animals are immune to tesla.

**Comment by AnturK** [comment]
Needs separation for weaker damage or bots and some other simple animals will get fried on shocked doors. Unless you want that.

**Comment by kevinz000** [comment]
While you're at it make xenomorphs actually affected by tesla so I can actually use tesla revolvers on them :)

**Pull request merged**
