### PR TITLE
Miscellaneous Robotic Limb Fixes

### LINKED ISSUE #77033: fully augmented people are not ashstorm or space immune
## Reproduction:

1. get fully augmented
2. walk into space/ash storm
3. start to take cold damage from space / burn damage from the ash storm
4. cry

likely caused by #76817 not accounting for temp and only pressure damage and also completely ignoring ash storms existing

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

In PR #76817, the damage reduction for robotic limbs was changed from being flat to being multiplicative in nature. This wasn't supposed to have secondary mechanical effects on robot limbs, but as always a few slipped by. This PR just cleans up a few of these unintended mechanical changes.

First of all, the change made robotic limbs not fully immune to space damage. They remained immune to damage from pressure but not damage from temperature. Now people with only robotic limbs are immune to the temperature damage and the moodlets caused by low or high temperature. I have tested it, and it works for people who have all robotic limbs, people who have some robotic limbs and some missing, and even the extreme case of a nugget with H.A.R.S. who has nothing _but_ a robotic chest.

Due to technical limitations (`apply_damage` doesn't have a `required_bodytype` argument), people with some robotic limbs and some organic will still take temperature damage on their robotic limbs.

Second of all, androids are once again immune to crit damage. Normally, crit damage is just constant oxyloss, but this obviously doesn't work for species that don't breath. Instead, those species take a small amount of brute damage. Prior to the damage reduction change, this meant that Androids were effectively immune to crit damage. Now they're immune once again.

Finally, you can now cancel surgery on robotic limbs. I don't think this bug was actually caused by the above PR, but I decided to fix it while I was here.

Closes #77033.
## Why It's Good For The Game

The damage reduction change was explicitly not intended to make robotic limbs not-spaceproof, so the first change is by definition a bugfix. As far as I know, crit damage being brute for nobreath species is a much more recent change than the existence of androids, so I think that also qualifies as a bugfix.
## Changelog
:cl:
fix: Having all augmented limbs will make you properly spaceproof once again.
fix: Androids are immune to crit damage again.
fix: Surgery on robotic limbs can be canceled.
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
would close #77033 if you'd also fix ash storm immunity

**Comment by GPeckman** [comment]
> would close #77033 if you'd also fix ash storm immunity

I'm pretty sure high temperature immunity already covers ash storms, but now it should also only affect organic limbs if someone has both organic and robotic limbs.

Although, due to the way the damage adjustment procs work, I'm pretty sure you'll still take just as much damage, it'll just be concentrated to fewer bodyparts.

**Comment by Sealed101** [comment]
there was some piece of code that granted the ash storm immunity trait when the clothing has had enough fire protection but i'm not sure if there was something like this on carbon/living level. also ash storms do `adjustFireLoss()` and not `apply_damage()` so yeah

please test

**Comment by GPeckman** [comment]
I did test it, and it worked. All the limbs but the chest were robotic, and only the chest took damage (but it took damage quite quickly, so I think my theory of overall damage staying the same is probably correct). When all the limbs were robotic, no damage at all.

**Pull request merged**
