### PR TITLE
Redtexting as a traitor now gets you some depressing music played to you

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
soundadd: Redtexting as a traitor now plays a depressing tune to you
/:cl:

Simply adds sound to when you redtext as traitor.  I want to do this to all traitors (and give them unique sounds) but I'll wait for datum antags because apparently it'll be a bit easier then.

https://vocaroo.com/i/s1R9aJYkLvup

### CODE REVIEW

**Comment by calibraptor** [comment]
What about a greentext noise?

https://www.youtube.com/watch?v=d3Awl_5c8jI

**Comment by Qustinnus** [comment]
kek good idea

**Review by ShizCalev — APPROVED** [review]

**Comment by ShadowDeath6** [comment]
just have it play sad trombone or something, I don't want to have a 15 second thing happen every time the round ends with me as traitor

**Comment by Qustinnus** [comment]
stop redtexting then nerd

**Comment by AnonymousNow** [comment]
[My desired greentext theme.](https://www.youtube.com/watch?v=ehhfn9yimj4)

**Comment by PKPenguin321** [comment]
This is the roblox death sound

**Comment by Qustinnus** [comment]
it is not the goddamn oof

**Comment by nicbn** [comment]
Use the "you fail" from TF2

**Comment by nicbn** [comment]
https://www.youtube.com/watch?v=YR82_cpW9Dc

**Pull request merged**
