### PR TITLE
Contribution reorganization: Theft Edition

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

A while back oranges made this really nice pr. #59465 It was mostly done to make snake_case mandatory for pretty much everything, along with a few other style things. But he got fed up with our 800 line contrib file, and decided to split it up. 

I share a similar hatred for our guidelines, people don't read them and finding anything is just guesswork
People will just throw their work at the bottom or top of a file with no regard for any order. It's hell to read and work with.

So I "borrowed legally under agpl v3" ~~stole~~ his code and expanded on it.
I think? he was working with the intent of splitting the main tower file into several different subfiles. I don't think I have the right vision to do that properly, but I've done what I can.

Splits contributing.md's Specifications section into 2 files:
- Style.md, which describes formatting patterns and clean code.
- Standards.md, this lays out the rules we have for code. More function, less cleanliness. 

Each file is separated into different sections. They cover things like styling for procs, variables, paths, or how to structure your code properly, optimization pitfalls to avoid, etc.

I've also created a development guides section in the contributing guidelines, to include links the above alongside things like autodoc, hard deletes, and the policy config section.

Makes a subfolder of .github called /guides to hold files like this, and the ones that exist to teach people how to set up servers.

## Why It's Good For The Game

I got bored, and MSO took away my keys, so I can't fix harddels right now.
Plus if I did my job right this will make learning from and adding to what we've written down much easier.

I'm not sure how good a job I did at the organization here, so feel free to bikeshed about it. https://github.com/LemonInTheDark/tgstation/blob/contrib-redo/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by Mothblocks** [comment]
so this doesn't change anything other than splitting things up right?

**Comment by LemonInTheDark** [comment]
I changed some spelling that my autocorrect claimed to be wrong. Didn't look at first glance like an americanism.
Also changed this line from `Like all languages, Dream Maker has its quirks, some of them are beneficial to us, like these` to `Like all languages, Dream Maker has its quirks, some of them are beneficial to us, some are harmful.` to better support the moving of byond hellspawn into that sub category.

I'm pretty sure that's it. I didn't intentionally change any of the actual rulings, though if you're asking this for the reasons I think, maybe it would be a good idea to ping commit access about it regardless, since it is changing how these things are set up and read.

**Comment by Mothblocks** [comment]
cool

**Comment by LemonInTheDark** [comment]
Fuck it.
@tgstation/commit-access thoughts?

**Review by Mothblocks — APPROVED** [review]

**Review by spookydonut — APPROVED** [review]

**Comment by Jordie0608** [comment]
Seems fine.

**Review by Timberpoes — APPROVED** [review]
I'm doing my part.

**Review by Watermelon914 — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
Ok

**Pull request merged**
