### PR TITLE
Fix 2.4 damage test bug, with proof

### PR DESCRIPTION
**Pull request by Mothblocks**
I tracked down every source of damage, and just ran the test 100 times until it failed.

dreamdaemon_2021-03-08T17-35-07

It was shrapnel, which runs this:

Code_2021-03-08T17-38-59

I made the victim pierce immune, meaning they'll never take embeds.

### CODE REVIEW

**Comment by Mothblocks** [comment]
For posterity, tests in a box is good for general purposes, but it didn't help here--it was never pressure.

**Comment by Ryll-Ryll** [comment]
Well that's embarrassing

**Comment by Mothblocks** [comment]
@Ryll-Ryll I'm thinking of just adding a development only test macro to just run the test 100 times with different random seeds, to spot issues like this faster. Would've helped you here perhaps, since you would've been able to try to go down the same path I did (logging damage).

**Comment by Timberpoes** [comment]
image

Fixes all these accursed CI fails, no game code changes. Merging this early as a result.

Not all these CI failures are a result of the issue, but enough are that I'm tired of restarting CI checks.

**Pull request merged**
