### PR TITLE
Adds a code of conduct

### PR DESCRIPTION
**Pull request by 5dplanner**
## About The Pull Request

Recent controversy that shall go unnamed has made me realise that /tg/ would
benefit greatly from adopting the Contributor Covenant which is a very widely
used and unintrusive code of conduct. This is to ensure productivity in PRs
and inclusivity for maintainers. 
Please don't post off topic politics :(

## Why It's Good For The Game
It's irrelevant to the game itself

## Changelog
:cl:
code: Adds a code of conduct for maintainers
/:cl:

### CODE REVIEW

**Comment by gardenBanter** [comment]
based and redpilled

**Comment by 81Denton** [comment]
I personally prefer flexible Values and Guidelines to a rigid Code of Conduct

**Comment by optimumtact** [comment]
https://github.com/tgstation/tgstation/pull/33313
I already did this joke and better

**Comment by gardenBanter** [comment]
I suggest an alternative code of conduct from which your community might benefit.

PP Station 13 will also be adopting this in July.

https://www.sqlite.org/codeofethics.html

**Comment by FantasticFwoosh** [comment]
Gosh a actually binding limit on :tangerine: and other maintainer' power for everyone to adhere to.
like that's ever going to happen
Like that's ever going to happen

**Comment by optimumtact** [comment]
how would it be binding? It's dependent on me enforcing it

**Comment by gardenBanter** [comment]
I remember when I went on a date with Oranges in mid 2017, she wore a beautiful dress and had glossy orange lipstick

I broke up with her after she failed to bear me a son

**Comment by wesoda25** [comment]
If you’re gonna make a PR don’t be a pussy and use your alt

**Pull request closed without merging**
