### PR TITLE
[MiniStation] Fixed recycler conveyer belt and converted the map.

### PR DESCRIPTION
**Pull request by kyrahabattoir**
This was supposed to be a single tile dir fix
But might aswel convert the map too.

### CODE REVIEW

**Comment by lordpidey** [comment]
In the future: please mention which map you are changing.

**Comment by kyrahabattoir** [comment]
Woops i forgot that i did not metion it anywhere but the branch name, my bad.

**Comment by tkdrg** [comment]
this was done using the bugged version of the new map merger
please redo it using the new one

**Comment by kyrahabattoir** [comment]
okay

**Comment by kyrahabattoir** [comment]
The result is the same everytime i run mapmerge, what's wrong with changing to the new map format?

**Comment by kyrahabattoir** [comment]
Okay, redid the mapmerge

**Pull request merged**
