### PR TITLE
Fixes some chameleon clothing not appearing in the list

### PR DESCRIPTION
**Pull request by XDTM**
By appending (icon_state) to the items. Also made the selection null|anything, so you can cancel the action.

### CODE REVIEW

**Comment by coiax** [comment]
Won't this mean that a bunch of things will have duplicate entries though?

**Comment by XDTM** [comment]
Better that than missing some very common items because they have a snowflake variant overriding it (for example sec armor was being overridden by detective armor, so disguising as sec was hard)

**Comment by coiax** [comment]
Probably need to give things distinctive names then.

**Comment by Mark9013100** [comment]
I think the way bay fixed this was having the item's name, plus the item's sprite name

**Comment by XDTM** [comment]
While that works it's very immersion breaking, which sounds odd from a hrp server

**Comment by coiax** [comment]
I don't think our icon state names are that bad.

**Comment by XDTM** [comment]
it would also remove pointless duplicates like flight_suit and flight_suit/full so, i'm gonna switch to that

**Comment by XDTM** [comment]
Re-did it by appending the icon_states to the items instead. Improper items with quotes were causing issues so i removed the quotes. This only affects the uzi and the bulldog.

**Pull request merged**
