### PR TITLE
[s]Adds detection for spoofed 512 clients

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This detects 512 clients without a valid 512 build.

### CODE REVIEW

**Comment by NazarFogmann** [comment]
lmao

**Comment by ExcessiveUseOfCobblestone** [comment]
@MoreRobustThanYou did you make an account called superpizza? I really like that ckey name and thought of you when I saw it pop up in my notifs that it was using a VPN.

**Comment by Qustinnus** [comment]
@MoreRobustThanYou you have achieved super autism

**Comment by PKPenguin321** [comment]
>the thumbs down react

😂

**Comment by MrDoomBringer** [comment]
image
image

**Pull request merged**
