### PR TITLE
Soulful bodypart names

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

(Please merge https://github.com/tgstation/tgstation/pull/71745 and https://github.com/tgstation/tgstation/pull/71721 before merging this, makes my life easier)

I really, really dislike how bodypart names were set automatically based on the limb ID.
This is pretty shitty for mapping and fucks with using initial(bodypart.name)
Also, that makes it so species ids and limb ids have to be formatted to be readable to players, which a lot of them aren't!
Also also, means the name of bodyparts has to match the species and zone, which is mildly uncool.

So, what did I do? I went through every fucking limb and renamed them all manually instead.

Additionally, mild file reorganization because i didn't like how cluttered parts.dm was.

## Why It's Good For The Game

It allows coders to make more "soulful" bodypart names, like "skeletal chest" instead of "skeleton chest", and "putrid chest" instead of "zombie chest".

## Changelog

:cl:
spellcheck: Some limbs now have more "soulful" names when dismembered, instead of just being named just species + body zone.
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
How did so many integration tests fail? WTF

**Comment by ChungusGamer666** [comment]
look i don't know what the actual fuck is going on but it is NOT my fault brother

**Review by Mothblocks — CHANGES_REQUESTED** [review]
this seems like a straight downgrade to maintainability. if you want to be able to have custom names, you should instead have a variable that limbs can set that will be their name, otherwise default to what we're doing now

**Comment by ChungusGamer666** [comment]
> this seems like a straight downgrade to maintainability. if you want to be able to have custom names, you should instead have a variable that limbs can set that will be their name, otherwise default to what we're doing now

You just need to set one more variable whenever a new bodypart is added. I just cannot agree that this is that much of an extra burden considering how often bodypart_overrides is used on species.
Either this gets merged as is, or I don't care to add another bloat variable to limbs because it's just very dumb for the reasons stated in my PR.

**Comment by Mothblocks** [comment]
it is not dumb at all, your reasons do not at all correlate to "manually define name on everything"

**Pull request closed without merging**
