### PR TITLE
Titanium no longer spawns or is required in any recipes

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It doesn't even fit in the fabricator and all the turfs broke and I'd revert the whole PR if the auto revert button worked, but this is second best.

It can go back into mining when it has an actual use.

### CODE REVIEW

**Comment by optimumtact** [comment]
If you really didn't want the PR merged why didn't you just close it?

**Comment by Aloraydrel** [comment]
cuz ur gay lmao

**Comment by KorPhaeron** [comment]
I thought he was gonna finish it instead of half assing what I asked for and purposefully committing something broken to avoid touching maps

**Comment by Bawhoppen** [comment]
autism kor, Its still useful

**Comment by Bawhoppen** [comment]
also the reason it doesn't fit in the fab is because I didn't originally intend to add recipes yet, but you forced me to

**Comment by ike709** [comment]
#19336

**Comment by Bawhoppen** [comment]
close this PR i'm fixing it just be patient its like 30 files changed

**Comment by Zilenan91** [comment]
Should probably put the pr up before the way to fix this is closed.

**Comment by KorPhaeron** [comment]
He can add it back to mining when it has a real function. None of his work is lost by preventing it from spawning currently.

Buildable shuttles do not exist yet, therefore the materials for them do not need to be obtainable in mining yet.

**Comment by jughu** [comment]
Booo

**Comment by Bawhoppen** [comment]
the fix pr is like 40 files changed so one sec i'll readd it later

**Comment by KorPhaeron** [comment]
readd it when your shuttles actually exist

**Pull request merged**
