### PR TITLE
Adds chicken holochassis for pAI

### PR DESCRIPTION
**Pull request by Tramzz**
Adds a chicken holochassis as one of the selection choices for pAI players.

## About The Pull Request

Adds a chicken holochassis option for pAI. Has its own walk cycle for movement, and a custom rest!
image
image

## Why It's Good For The Game

It gives pAI candidates a new look to choose from for their holochassis emitters. Meant to give pAI players more means of self-expression, alongside the pre-existing choices.
## Changelog

:cl: Tramz
add: Adds a new holochassis for pAI, the chicken.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Finally, good bloat.
do fix your merge conflicts tho. you'll want to install the merge hooks, they'll do the easy stuff automatically

**Comment by Tramzz** [comment]
> Finally, good bloat. do fix your merge conflicts tho. you'll want to install the merge hooks, they'll do the easy stuff automatically

Any way I can reach out to you for some assistance on installing those merge hooks and fixing these merge conflicts? This is my first time dabbling into stuff like this. Should be pretty good to go once the conflicts are fixed though.

**Comment by dragomagol** [comment]
> > Finally, good bloat. do fix your merge conflicts tho. you'll want to install the merge hooks, they'll do the easy stuff automatically
> 
> Any way I can reach out to you for some assistance on installing those merge hooks and fixing these merge conflicts? This is my first time dabbling into stuff like this. Should be pretty good to go once the conflicts are fixed though.

You should be able to get some help from this readme: https://github.com/tgstation/tgstation/tree/master/tools/hooks

Feel free to head on down to the /tg/station discord (or coderbus discord) and ask in there if you're having trouble with it, there's a lot of contributors who'd be willing to help out!

**Comment by Tramzz** [comment]
Going to close this and try remaking, in hopes that doing so will resolve some of the merge conflicts. Have been consulting help on /tg/station discord though so hopefully my next attempt at this goes a bit smoother. Thanks everyone who thought positively of it though, it means a lot.

**Pull request closed without merging**
