### PR TITLE
Makes the ghost follow links work with radios

### LINKED ISSUE #6873: Ghost follow link doesn't work over radios
Which practically defeats the point of it being there in the first place.
It doesn't work for binary, alien chat, or ling chat either, so it's basically pointless half the time.

### PR DESCRIPTION
**Pull request by tkdrg**
fixes #6873

### CODE REVIEW

**Comment by paprka** [comment]
Dead chat too if possible

**Comment by Anonus** [comment]
And alien and binary, and maybe ling chat but probably not ling chat.

**Comment by tkdrg** [comment]
Dead chat and inherent channels aren't easily possible due to the way that current say code is structured, since in those cases the message is only rendered once and skips Hear(). Implementing those would mean rewriting quite a few saycode procs and losing some performance.

**Comment by paprka** [comment]
yeah that's fine

**Pull request merged**
