### PR TITLE
Bepis techs can be found in bitrunning crates, removed from vendors

### PR DESCRIPTION
**Pull request by Profakos**
## About The Pull Request

This PR adds Bepis disks to the main rewards of the Bitrunning crate in addition to the minerals and domain specific rewards. It also removes it from the Bepis vending machine. 

Once per domain, if its difficult was Medium or higher, and the completion score was A or S, and if there are still any leftover locked Bepis tech nodes, a Bepis disk will spawn.

<details>
  <summary>Original PR text</summary>
If domain has a reward value greater than one, it has 10% chance per reward value to drop. No disk is gained if they ran out of techs to unlock. Most of the domains have a reward value of three, so by the law of great numbers they probably get one disk per every three domains run, which should be one disk every 20-30 minutes. At least, if I am correct that domain runs take about five to ten minutes, and the server cooldown is three minutes. If I am incorrect, I can edit the drop chance as needed, of course.

Edit: As I have underestimated how fast Bitrunners can be, I have decreased the chance to be 5% per reward tier.
</details> 

## Why It's Good For The Game

- Bepis disks are expensive, and bitrunners need to spend almost all their NP on gear and abilities
- Downloading secret research data, is flavourful, fitting for invading the forgotten nooks of cyberspace.
- This will allow Bepis tech to be actually used in rounds

## Changelog

:cl:
balance: Bitrunners can now earn Bepis disks, once per medium domain or above, if they scored at least an A.
del: Bitrunners can not buy Bepis disks from their vendors.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
@ArcaneMusic @optimumtact

**Comment by HoodMilk** [comment]
Literally never saw any bitrunners purchase the bepis disks on their own volition after the first week of bitrunning. Good change.

**Comment by Rhials** [comment]
> If domain has a reward value greater than one, it has 10% chance per reward value to drop. No disk is gained if they ran out of techs to unlock. Most of the domains have a reward value of three, so by the law of great numbers they probably get one disk per every three domains run, which should be one disk every 20-30 minutes. At least, if I am correct that domain runs take about five to ten minutes, and the server cooldown is three minutes.

Speaking from experience, you can easily bang out some domains in a matter of 2-3 minutes, even the harder boss-based ones. A bitrunner with enough experience who knows where they're going could crank out disks really fast, especially with upgrades. 

I'd suggest making them even rarer, or maybe extra-rare but are a guaranteed drop in domains where a digital anomaly has been defeated?

**Comment by optimumtact** [comment]
stealing content from another part of the game to juice your rotting corpse of a feature seems hardly fair.

**Comment by EricZilla** [comment]
Bitrunners can already get bepis tech cards this is just changing how they get them

**Comment by optimumtact** [comment]
Yeah it hardly seems fair

**Comment by Profakos** [comment]
> stealing content from another part of the game to juice your rotting corpse of a feature seems hardly fair.

You misunderstood my intentions, I want to save bepis disks, not juice up the bitrunning.

**Comment by Profakos** [comment]
> > If domain has a reward value greater than one, it has 10% chance per reward value to drop. No disk is gained if they ran out of techs to unlock. Most of the domains have a reward value of three, so by the law of great numbers they probably get one disk per every three domains run, which should be one disk every 20-30 minutes. At least, if I am correct that domain runs take about five to ten minutes, and the server cooldown is three minutes.
> 
> Speaking from experience, you can easily bang out some domains in a matter of 2-3 minutes, even the harder boss-based ones. A bitrunner with enough experience who knows where they're going could crank out disks really fast, especially with upgrades.
> 
> I'd suggest making them even rarer, or maybe extra-rare but are a guaranteed drop in domains where a digital anomaly has been defeated?

That is much faster than I thought. I'll halve the chance for now, and think about your anomaly suggestion.

**Comment by Profakos** [comment]
Updated "why its good for the game" to make it clearer that this is meant to be a buff for Bepis techs accessibility, and not a buff to Bitrunning itself.

**Comment by Jacquerel** [comment]
> Yeah it hardly seems fair

This is literally already the only source of that content

**Comment by ArcaneMusic** [comment]
So, for clarity, I did give the original go-ahead to tie BEPIS techs to bitrunning as a purchasable reward since the original method through the BEPIS didn't really have any gameplay, it was basically just an expensive vending machine reward before that. This at the very least gave bitrunners a way to provide some degree of in-round progress to the rest of the station that was unique to the role they wanted to add.

I don't think I like just tying bitrunning disks to crates as a random chance. For starters, random chances of making station-wide progress towards job completion or providing random rewards just... feels bad at a certain point. Take for example virology, where you may dump 20 minutes trying to get a perfect set of symptons to get your mechancially perfect healing virus, or xenobiology, where you spend long periods of time hoping for breeds and crossbreeds and quantities of cores for specific results, it similarly feels bad. 

Looking at the math, you offer a 5-30% chance of getting a BEPIS tech included with your reward crate, while also moving it away from being purchasable. In my limited experience, I've found that bitrunning missions take a bit too long to reset and restart, to the point that it's not really going to feel gratifying to do a long mission and not see that kind of reward from it.

I think you could do better than offering them randomly, and instead make BEPIS techs offered through final mission rank, for example, where missions that you can complete with an S rank or through bonus objectives, they could offer a single, one off disk per mission (Keeping in mind that the contents of BEPIS Tech Disks have a higher power ceiling because of their random nature by themselves, since you don't know if you're getting full blown hypnosis machines or if you're just getting heated coffee mugs)

**Comment by moocowswag** [comment]
It should just be returned to being a money sink, sci doesnt have alot of uses for money outside of anomaly cores.

**Comment by Profakos** [comment]
The issue with the disks being considered steps in job progress, is right now, bitrunners will not really reach that far, as they will try to get better and better equipment instead, as J Snow has confirmed in discord that nobody buys this. This potentially could be fixed via changing prices, but this would have so much ripple effect on bitrunning as a whole.

I have also seen that an alternative is to make them drop if you reach A rank on a Medium Difficulty, once per domain. Can I try that version?

**Comment by Profakos** [comment]
Implemented the above the changes, update PR text accordingly.

**Pull request merged**
