### PR TITLE
Fixes heart attack ghost notification

### LINKED ISSUE #35615: Random Heart Attack click to orbit link in chat does not work
1) Random Heart Attack triggers.
2) As a ghost, try to click the link to orbit the poor sod.
3) Nothing happens.

Round ID: 83513

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
fix: Ghosts should now be able to orbit people who are going into cardiac arrest
/:cl:

Fixes #35615

### CODE REVIEW

**Comment by 81Denton** [comment]
h-he's fast!

**Comment by F-OS** [comment]
@MoreRobustThanYou

stop evading shitler

**Comment by PKPenguin321** [comment]
yall mind if i... steal this gbp?

**Pull request closed without merging**
