### PR TITLE
Moves Wild Biomatter Scan to discount, changes Botanical Engineering point costs

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

On botanical engineering, changed the point cost to 7000
Wild Mutation Scanning experiment has been moved to discount, with a 3500 discount
Trait Scanning now has 2000 discount
## Why It's Good For The Game

Botanical Engineering, as it currently is, is extremely painful to research because
Its like a 33% (on a yield 1 plant, chances will vary with higher yield because apparently its per produce) chance on harvest at 100 instability which when combined with the harvest times of the plant is extremely long
(also poorly explained in the experiment)
This, to make Botanical Engineering less pain, has been moved to discount.

Upping the point cost was because botanical engineering is pretty strong (deathnettles my beloved) and the lack of a required experiment (after the experiment got made optional).

## Changelog
:cl:
balance: Botanical Engineering now costs 7000 points, and its required experiment is now a 3500point discount experiment.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
> (also poorly explained in the experiment)

so... why not explain it better?

**Comment by mc-oofert** [comment]
> > (also poorly explained in the experiment)
> 
> so... why not explain it better?

the current explanation is really just comprehensible only if you codedive, also this PR is about the point costs and making the experiment optional so

**Comment by mc-oofert** [comment]
> > Its like a 33% chance on harvest at 100 instability
> 
> It's rolled per produce, not per harvest...
> 
> At 100 instability it's a 98% chance to get a wild mutation of a 10 yield plant.
> 
> At 30 instability it's a 65% chance.

yeah uhh the experiment still sucks

**Review by MrMelbert — CHANGES_REQUESTED** [review]
The requirements are fine as-is, it's actually very easy and I would wager most botanist wild mutate constantly without even knowing it

At that, you are correct the mechanic and experiment are poorly explained in game

Update the experiment description instead, and maybe give the plant analyzer a hint for wild mutated stuff.

**Comment by mc-oofert** [comment]
> The requirements are fine as-is, it's actually very easy and I would wager most botanist wild mutate constantly without even knowing it
> 
> At that, you are correct the mechanic and experiment are poorly explained in game
> 
> Update the experiment description instead, and maybe give the plant analyzer a hint for wild mutated stuff.

yeah uhh thats gonna need a different PR

**Pull request closed without merging**
