### PR TITLE
Prevents inserted inert legion cores from healing

### PR DESCRIPTION
**Pull request by QualityVan**
:cl: QualityVan
fix: Inserted legion cores no longer work if they went inert before implanting
/:cl:

Move fast or apply stabilizer.

### CODE REVIEW

**Comment by fludd12** [comment]
Don't really think it's necessary, since it requires surgery and such.

**Comment by Core0verload** [comment]
I left you for two months, and you somehow nerfed legion cores into the trash bin. Not cool guys.

**Comment by QualityVan** [comment]
This's a bugfix. The old code prevented cores from going inert once they were implanted, which means that inertness should matter on implanted cores. However, it didn't bother to check for cores that had already gone inert before implanting. Also 'into the trash bin' what.

**Comment by fludd12** [comment]
If legion implants had the Regan over time when implanted still, I'd say this is a good change. As-is, though, it just means nobody will ever implant them.

**Comment by RemieRichards** [comment]
These are still incredibly useful when implanted, if you drop into crit you get fully healed.
This is a bugfix.

**Pull request merged**
