### PR TITLE
Swaps psychologist from Service to Medical

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Every time I discuss Psychologists, the conversation always devolves from whether Psychologist is Service or Medical.

## Why It's Good For The Game

Every other job, including Lawyer, already has a clear department they are in, but not Psychologist.
It is hard to justify Psychologist being in Service rather than Med when they have proper Med access including techfab, with roundstart medical equipment (pills), medical mail things, med comms, **their literal office being in medical**, ect.
Mental health is a Medical problem, not a service one, so Psychologist shouldn't be considered 'Service' just because it doesn't have much content. Service shouldn't be the department you shove "RP" roles in, because otherwise Kitchen/Bar/Chapel wouldn't be considered service anymore.

It also makes no sense for them to be under the HoP, who otherwise has no business in Medical at all. HoP should mind their own business, and while I love the Service department and how well they could all work together, the biggest flaw it has really is how large it is, so cutting this one job that forces Service into an entire new department is really stupid.

## Changelog

:cl:
balance: Psychologists have been moved from Service to be fully part of Medical.
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
Psychologist is an engineering role really.

**Comment by GoldenAlpharex** [comment]
> Psychologist is an engineering role really.

No, no, you seem to be mistaken, it's actually apart of Cargo, you see?

**Comment by Jolly-66** [comment]
> No, no, you seem to be mistaken, it's actually apart of Cargo, you see?

Cargo? I thought it was apart of sec, yknow, gotta keep the warden company.

**Comment by Wallemations** [comment]
Aren't Lawyers dual-department too?

**Comment by CRITAWAKETS** [comment]
> Cargo? I thought it was apart of sec, yknow, gotta keep the warden company.

Sec? REALLY? Come on dude, we all know psychologist does mental health science, so they're a science job.

**Comment by D4C-420** [comment]
> Sec? REALLY? Come on dude, we all know psychologist does mental health science, so they're a science job.

Sci? you clearly NEVER played psychologist. It's clearly a traitor role as only a traitor would bring someone into a room with no windows and ask them to relax. That moff plush sucks out souls after all!

**Comment by EricZilla** [comment]
Are psychs going to get any of the built in stuff medical gets? Like skillchips and stuff? I've always played pysch as the emergency back up emergency back up doctor, and it would be nice if they could do some healing on the side in situations where it comes up.

**Comment by optimumtact** [comment]
I can solve it for you, they're service.

**Pull request closed without merging**
