### PR TITLE
Fixes admin spawned energy cannons/emitters

### LINKED ISSUE #9915: Admin emitter (energycannon) no longer works
This emitter is meant to just be an admin thing you can slam down. It fires constantly and needs no power or turning on. It was a pretty useful tool for various things and I'm sure it wouldn't be difficult to bring back.

@Iamgoofball

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
@Niknakflak 

@Iamgoofball 

How did a one line fix take so many months

Fixes #9915

### CODE REVIEW

**Comment by optimumtact** [comment]
because nobody cared enough to fix it?

**Comment by Aloraydrel** [comment]
Lmao

**Comment by Iamgoofball** [comment]
i was only recently informed that there was an away mission that used them

**Comment by Niknakflak** [comment]
I didnt cause the bug, I just shit on goofball for being a baby about it.

**Pull request merged**
