### PR TITLE
Change injectors on research gateway, and remove the free magic books, remove 'unsalvageable' gateway maps

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request

Replaces the injectors on the "Research" gateway and removes the free magic books in the corner.

Deletes the following "unsalvageable" gateway maps, sourced from https://hackmd.io/@tgstation/SyYb_cjQ9, approved by maptainers:

- Academy
- Challenge
- Space battle
- Wild west

Once this PR is merged, I'll be flipping gateway on servers and we (maptainers, headmins) will be accepting new gateway maps for production.

### CODE REVIEW

**Comment by Colovorat** [comment]
image

💀

**Comment by Snowyypanda** [comment]
hooray to more events, i'd love to see gates being expanded so this is a lovely change

**Comment by ATH1909** [comment]
aw, wild west is going away? was the wishgranter really completely unsalvageable?

**Review by MrMelbert — COMMENTED** [review]
`/obj/machinery/artillerycontrol` is insanely old unmaintained code only used in the spacebattle gateway 🥺

**Comment by Fikou** [comment]
> `/obj/machinery/artillerycontrol` is insanely old unmaintained code only used in the spacebattle gateway 🥺

dont worry i'll refactor it when i remake spacebattle :)

**Comment by Mothblocks** [comment]
@MrMelbert I'll take a look, I intentionally didn't look at code very much because when I started, I realized that a lot of it is still used for other stuff/by admins (like die of fate).

**Comment by tuckerorchistra** [comment]
Wild wild west is based

**Comment by Yobrocharlie** [comment]
image
(necroposting but im going to look into these)

(edit: Wow these are all really really shit, the only semi redeemable one is going to be academy and NO im not going to give the players magical stuff for their time in academy I have a different idea)

**Pull request merged**
