### PR TITLE
Chrono reskin MK ii (4)

### PR DESCRIPTION
**Pull request by JJRcop**
###  Older PR: #41131

:cl: JJRcop & Memager
imageadd: The chronosuit and gun have new sprites.
tweak: The T.E.D has been renamed to the T.A.D and the backpack has been removed. The T.A.D fits directly on your back, but only if you are wearing the chronosuit. You must be wearing the chronosuit bottom for the gun to work.
balance: Since the backpack is removed, you can drop the gun! Don't lose it! 
fix: The chronosuit's teleport animation has been fixed, as has the gun.
/:cl:

Why reskin? @Memager made new sprites based on our existing hardsuits, which I think make the character fit in better. (This is his 4th attempt) He didn't sprite a backpack this time, which was one of the feedback points of the old PR, please let us know if that's still an issue for you.

screenie

I made a new PR because the other one is 14 days old and this is a complete redesign of the new sprites. It looks closer to the old sprites it's replacing than the other PR, we hope you'll like them a lot better.

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
i like it

**Comment by ShizCalev** [comment]
these look creepily thin

**Comment by Bombpants** [comment]
The sprite is cool, but I don't like the change to the gun.

**Comment by evsey9** [comment]
stop bundling sprites changes with balance changes

**Comment by JJRcop** [comment]
Upvote this specific comment if you want the backpack back, it wasn't resprited.

**Comment by Memager** [comment]
fuck ok what do i do shiiiiiiiit

**Comment by Memager** [comment]
keep the other suit then?
https://github.com/tgstation/tgstation/pull/41131

**Comment by miniusAreas** [comment]
I'm not fond of Crono Leigonares being able to drop their gun. Seeing as how two tiders could beat him and use his gun for maximum greytide, its not something im fond of. Still, sprites are cool.

**Comment by JJRcop** [comment]
I'm going to make a bunch of comments here because it's hard to pin down what you guys don't like. Please only upvote the comments you agree with rather than downvoting the ones you don't, and make your own comment if your views don't fit within them.

**Comment by JJRcop** [comment]
I like the new sprites but I want the backpack back.

**Comment by JJRcop** [comment]
I like the sprites from the other PR but I want the backpack back.

**Comment by JJRcop** [comment]
I like these new sprites.

**Comment by JJRcop** [comment]
I prefer the other sprites.

**Comment by tralezab** [comment]
balance tag, sprite tag, and fix tag all in one pr

🤔

**Comment by Militaires** [comment]
looks  great

**Comment by optimumtact** [comment]
please stop bikeshedding over an admin spawn item

**Pull request closed without merging**
