### PR TITLE
removes non syndicate aligned traitor flavors

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
Removes the non syndicate aligned traitor flavors
## Why It's Good For The Game
While these are fun ideas, these flavors are at direct odds with many of the traitor mechanics, including code words, side objectives, final objectives, and how people interact with the traitor role. They do not make sense in the realm of progtot.
## Changelog
:cl: itseasytosee
del: All traitors are now syndicate aligned.
/:cl:

### CODE REVIEW

**Comment by sylvia-from-fulp-station** [comment]
What's the point; it's just flavour text. One of the cool parts of a traitor is they don't need to be strictly syndicate aligned and often work against each other or other syndicate forces like nuke ops.

**Comment by HoodMilk** [comment]
I was always confused how somebody in legal trouble would have access to a syndicate uplink, or what a "Champion of Evil" was.

**Comment by MrMelbert** [comment]
> I was always confused how somebody in legal trouble would have access to a syndicate uplink, or what a "Champion of Evil" was.

image

**Comment by itseasytosee** [comment]
> What's the point; it's just flavour text. One of the cool parts of a traitor is they don't need to be strictly syndicate aligned and often work against each other or other syndicate forces like nuke ops.

Here is my more detailed argument https://tgstation13.org/phpBB/viewtopic.php?f=10&t=37114
Its inconsistent with mechanics.

**Comment by sylvia-from-fulp-station** [comment]
> Here is my more detailed argument https://tgstation13.org/phpBB/viewtopic.php?f=10&t=37114 Its inconsistent with mechanics.

I think your argument is based solely on your own experience and doesn't take into account any other players. 
You can play antagonists however you want; having a syndicate uplink available for side objectives because you are a round start traitor doesn't mean you need to do every single one. The syndicate is a coalition of organizations, with direct rewards for betraying each other (putting 20tc into your uplink). 

It's also not really confusing when next to the popup there is a text box explaining that all the flavour is for bored players. On my first round as traitor I ignored all the flavour text and opened uplink. Eventually I started using it as inspiration for what to spend my TC on and how to go about my objectives. 

I think this PR mainly just hurts players who use this and doesn't even affect people like you who think the flavour is stupid and ignore it.

**Comment by itseasytosee** [comment]
> > Here is my more detailed argument https://tgstation13.org/phpBB/viewtopic.php?f=10&t=37114 Its inconsistent with mechanics.
> 
> I think your argument is based solely on your own experience and doesn't take into account any other players. You can play antagonists however you want; having a syndicate uplink available for side objectives because you are a round start traitor doesn't mean you need to do every single one. The syndicate is a coalition of organizations, with direct rewards for betraying each other (putting 20tc into your uplink).
> 
> It's also not really confusing when next to the popup there is a text box explaining that all the flavour is for bored players. On my first round as traitor I ignored all the flavour text and opened uplink. Eventually I started using it as inspiration for what to spend my TC on and how to go about my objectives.
> 
> I think this PR mainly just hurts players who use this and doesn't even affect people like you who think the flavour is stupid and ignore it.

I think you have misunderstood this PR. This PR doesn't remove flavor text. Just a few flavors that aren't consistent with traitor gameplay

**Comment by xzero314** [comment]
Really disappointing PR. Different flavour texts breed ideas for gimmicks and roleplay

**Comment by kawaiinick** [comment]
I like how these flavours give traitor background more depth, even though it's extremly rarely to see anyone follow their flavour. It's cool how it's not just John Syndicate that hates nanotrasen and there are other reasons for people to betray the company and get their hands on contraband uplink

**Comment by TheSmallBlue** [comment]
> Its inconsistent with mechanics.

But it doesn't have any actual negative impact when it comes to those mechanics. You can still play traitor just fine, regardless of what the flavor text says. At the end of the day, flavor text is just a nice touch to give the act of getting traitor more life. It doesn't harm anyone, I see no point in it being removed.

**Comment by DaydreamIQ** [comment]
Yeah there's nothing really inconsistent about this. Not all traitors need to be syndicate aligned, sometimes you wanna just go fucking apeshit. IAA is really the only one people use as an excuse to be friendtags but any traitor could use that excuse and pretend to be IAA even if this was removed

**Comment by Exester509** [comment]
Fair criticism, bad execution IMO. I'd say the different flavors should be more unique and fitting, like the background of the uplink changing, or getting more specific and similarly round-altering final objectives (NT Internal Affairs calling a deathsquad instead of the battlecruiser for example).

That aside, and perhaps codewords, which don't even make much sense with just syndicates at odds with each other to begin with, I wouldn't say Champions of Evil or Legal Trouble break immersion all that much, and might even fuel some gimmicks.
I'd much rather have this add specific company gear like pens or uniforms to the pointless badassery section to show your special allegiance than outright removing traitor flavor.

**Comment by ninjanomnom** [comment]
There's no harm in having these around, though if someone wants to give the player a bit more control over which types of traitor they're assigned that would be fine. Add a pref to disable silly employers if you'd like.

**Pull request closed without merging**
