### PR TITLE
if you die in a mech you are ejected

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

https://github.com/tgstation/tgstation/assets/70376633/8bef6da9-bfd0-4c57-9614-b3c92514cbba

## Why It's Good For The Game

the sole two normally accessible ways to get dead people out of mechs is the mech removal tool (which probably got destroyed by a traitor or just whoever is rescuing you doesnt have access to), or break the mech (which will piss off whoever made the mech)

making dead people fall out of mechs should be a good way to not get entombed in a mass of steel

## Changelog
:cl:
qol: if you die in a mech you automatically eject
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
this doesnt interact with AIs controlling a mech correct? they already have special behavior

**Comment by mc-oofert** [comment]
let me check

**Comment by mc-oofert** [comment]
ok i have no clue how the fuck would an AI die inside a mech but im going to check against that

**Comment by nikothedude** [comment]
> ok i have no clue how the fuck would an AI die inside a mech but im going to check against that

AI control beacon, malf AI mech domination power

**Comment by mc-oofert** [comment]
ok changed it to only work on normal pilots

**Comment by Likteer** [comment]
Besides this, does the mech removal tool have any other utility?

**Comment by mc-oofert** [comment]
> Besides this, does the mech removal tool have any other utility?

if you somehow manage to immobilize a mech or it runs out of ammo or power or something you can pry out the pilot and lynch them

**Comment by moocowswag** [comment]
Ya mech removal tool is when you value the mech and not the pilot


Its very easy to break into locked mechs now you just have to hack it.

**Comment by timothymtorres** [comment]
> Besides this, does the mech removal tool have any other utility?

It does almost the same amount of damage as a fireaxe. (which is ridiculous)

**Comment by githubuser4141** [comment]
Can this be a setting (on by default) in the mech UI? Some people might prefer not to fall out if dead, could have a setting to eject when crit too?

**Comment by Jacquerel** [comment]
Having to pull people out with a big crowbar is more soulful. If someone would rather be round removed than have their rebuildable mech smashed that's a skill issue.

**Comment by jlsnow301** [comment]
Does this fix #55770

**Comment by mc-oofert** [comment]
> Does this fix #55770

dont know how to reproduce

**Comment by Ghommie** [comment]
Given there're a few tools to remove pilots from a mech without destroying it, this feels like it's going to take some of their utility away, even if it's not a bad PR. It could be an option people can toggle on from the UI if they want to; "skill issue" if they die somehow while stuck inside their mech.

**Comment by optimumtact** [comment]
user is permanently gitbanned

**Pull request merged**
