### PR TITLE
Tablet resprite

### PR DESCRIPTION
**Pull request by JStheguy**
:cl: JStheguy
imageadd: Resprited the tablet, including completely redone screen sprites.
add: Tablets can now come spawn in one of 5 colors; red, green, yellow, blue, and black. 
/:cl:

Honestly, the tablet needed some work done, spritewise, especially with the screen sprites. Though I may have gone overboard somewhat with this ultra high-tech facelift.

image
From left to right: red tablet, off and running the menu; green tablet, off and running the id card program; brown tablet, off and running the alarm program with no detected alerts; blue tablet, off and running the supermatter monitoring program with an inactive supermatter engine; black tablet, off and running one of the syndie programs; old tablet, off and running the id card program

The future is now.
image

### CODE REVIEW

**Comment by deranging** [comment]
looks pretty cool for an underused item

**Comment by dannno** [comment]
nice work

**Comment by dannno** [comment]
I especially like the mock ad

**Comment by GunHog** [comment]
It looks like something Nintendo would make in the late 1900's! So, good job!

**Comment by WJohn** [comment]
Looks good.

**Comment by outbools** [comment]
@GunHog "late 1900's" feels like 1908-1909 im guess Nintendo went cool these years

**Comment by Jalleo** [comment]
I presume @GunHog means 1990's

**Comment by Shadowlight213** [comment]
Eh. I don't really like the new supermatter monitor overlay. It just looks kinda blurry, and the version I did was consistent with the console ones and the header.
Also, I seriously hope that the dimensions of the new tablet screen is the same size as bay's, as I'm not spending a bunch of effort to resize sprites, only to have it thrown away again.

**Pull request merged**
