### PR TITLE
gives security's execution a massive sparta pit 2 zlevels deep on icebox ((MULTI-ZED))

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

image

## Why It's Good For The Game

Unique, memorable and MAP SPECIFIC execution technique makes this super neat. As it were, venting to the snow is just... counter productive and stupid and the rest are on every other map. kept tanks for changeling stuff, and lethalsyringe kit for that. No longer have the gas kill because it wouldn't work with the atmos of the execution room!

## Changelog
:cl:
add: Security's Education room has a sparta pit on icebox
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
In game screenshot
image

**Comment by ArcaneMusic** [comment]
I feel like that grub on the bottom floor is probably dying to the cold temps, right?
You'll probably want a subtype for it.

**Comment by Barhandar** [comment]
How would that lightbulb and flash get replaced if/when they get broken?

**Comment by tralezab** [comment]
I've switched the single bulb with two bulbs to light it up more, they should be reachable

**Comment by MrDoomBringer** [comment]
god this is great

**Review by Timberpoes — APPROVED** [review]

**Pull request merged**
