### PR TITLE
Fixes supermatter getting people banned

### PR DESCRIPTION
**Pull request by Iamgoofball**
# somebody actually got banned this time

# https://tgstation13.org/phpBB/viewtopic.php?f=10&t=10187&p=268583#p268579

we shouldnt be leaving shit in that people get banned for

### CODE REVIEW

**Comment by ma44** [comment]
But why would you want to jump into it?

**Comment by kevinz000** [comment]
Remove /obj/item they get people banned.

**Comment by Iamgoofball** [comment]
@ma44 why do people use fire extinguisher tank suicide?

Holy shit @kevinz000 you know there's a difference between "making sure our players dont get banned for features we add as a joke" and "LOL REMOVE ALL OBJS THEY GET PEOPLE BANNED :^)" stop being a dense fucking autist cuntbucket

**Comment by kevinz000** [comment]
Funny you call me that and tell me that.

**Comment by ma44** [comment]
Because leaving some gibs behind is more cool than harmlessly falling down

Except the gibs are replaced by a singularity

Also this is a bandaid fix, people can still be banned if they are an engineer or chief engineer jumping into it.

**Comment by Iamgoofball** [comment]
The engineers and CE are a lot less likely to jump in to begin with.

**Comment by ma44** [comment]
lot less likely means it can still happen

**Comment by kevinz000** [comment]
Common fucking sense don't fix it with a meme PR.

**Comment by Iamgoofball** [comment]
THIS ISN'T A MEME PR
@ma44
And?
This allows the majority of greyshits to run in and suicide on the crystal without worrying about a ban.

**Comment by Iamgoofball** [comment]
And the majority of the roundstart suicides are assistants.

**Comment by Iamgoofball** [comment]
>3 downvotes

WHY DO YOU WANT TO LET PLAYERS GET BANNED FOR TAKING THEMSELVES OUT OF THE ROUND

**Comment by Iamgoofball** [comment]
WHY DO WE INSIST ON HAVING FUCKING 12 YEAR OLDS ADMIN THE SERVER AND BAN EVERYONE FOR SHIT WE COULD EASILY FIX WITH CODE

**Comment by GunHog** [comment]
I am against this because I want to be able to throw people I capture into it for faster delamination.

**Comment by ma44** [comment]
Because running into a job specific department to go suicide from the engine is like saying i should go deactivate the forcefields to go suicide into the singularity

**Comment by kevinz000** [comment]
@ma44 is right

**Comment by Iamgoofball** [comment]
>Also this shit can release a singularity

WHICH IS WHY I'M MAKING IT SO YOU CAN'T JUST GRIEF A SINGULO INTO EXISTENCE AND GET BANNED FOR IT

**Comment by Iamgoofball** [comment]
@GunHog 
>I am against this because I want to be able to throw people I capture into it for faster delamination.
USE ONE OF THE 50 WAYS TO MAKE THE SM EXPLODE

**Comment by Iamgoofball** [comment]
THROWING PEOPLE IN SHOULD NOT BE THE MOST RELIABLE WAY TO SINGULOOSE

**Comment by ma44** [comment]
>griefing a singularity into existence and a non antag and getting banned for it

Sounds right to me 👍

**Comment by kevinz000** [comment]
Idunno man most of us don't scream and jump into the Supermatter engine when we don't get our grief rolls.

**Comment by Iamgoofball** [comment]
@ma44 
WHY SHOULD WE ALLOW NON ANTAGS TO GRIEF A SINGULO INTO EXISTENCE TO BEGIN WITH

**Comment by Iamgoofball** [comment]
@kevinz000 Obviously enough people are doing it to get banned

**Comment by ma44** [comment]
@Iamgoofball Why should we allow non antag engineers to grief and unleash a singularity/tesla? We should make the singularity/tesla non releasable!

**Comment by kevinz000** [comment]
Great they can take a lesson.

**Comment by AnturK** [comment]
Didn't i close this one already.

**Comment by Iamgoofball** [comment]
HOLY SHIT FINE FUCK YOU I'LL JUST REMOVE GETTING ENERGY ENTIRELY

@ANTUR WHAT THE FUCK ARE YOU DOING

**Comment by kevinz000** [comment]
Rekt

**Comment by GunHog** [comment]
>THROWING PEOPLE IN SHOULD NOT BE THE MOST RELIABLE WAY TO SINGULOOSE

**WHY NOT!?** Besides morons getting themselves banned, why not!?

**Comment by Iamgoofball** [comment]
BECAUSE YOU'RE SUPPOSED TO USE ATMOS FUCK IT JUST REPLACE IT WITH THE SINGULO ENTIRELY WHY DONT YOU

**Comment by GunHog** [comment]
I would, but the PR would get insta-closed.

**Comment by AnturK** [comment]
All bans relating to sm suicide are people doing it repeatedly for consecutive rounds as engineers on roundstart. Is this really that hard to grasp ? Not everything needs to be regulated through code.

**Comment by Tokiko1** [comment]
You know, you can throw yourself into the supermatter without delaminating it. You just have to start the cooling loop first. Jumping into the supermatter when nothing is set up is the equivalent of starting the PA to make a singulo without a containmentfield so you can suicide with it.

**Comment by calzilla1** [comment]
I was an engine an whos

**Pull request closed without merging**
