### PR TITLE
Plant Refactor: The Icons strike back

### LINKED ISSUE #15926: Bluespace Banana pells
### What is the problem?
Slipped on a bluespace banana peel, locked into place. I can do any action but I can't actually move around
### Why is it a problem, or what should have happened?
After the stun you should be able to move
### How can the problem be reproduced?
Slip on bluespace banana peel, try to move, and you can't
###Server Revision
480583da322b4e120ade58cce05f4910d83423b3

Honestly bluespace peels were overpowered anyways as if you slip on a max potency one and go into space it's instant death sometimes :/

### PR DESCRIPTION
**Pull request by Core0verload**
This PR changes `growing.dmi` and plant icons generation procs to make repeating icons less common. 

You can now change `icon_grow`, `icon_harvest` and `icon_dead` vars in plant seeds to override default icons. It means you can use one set of _grow and _dead icons for multiple plants that differ only in products - apples, tomatoes, berries, etc.

Fixes #15926.

Players should notice only one change: missing in-tray sprites for bluespace banana, mimana, carpet and glowcap are fixed. Invisible mimana in tray is now a feature: at some point of growth it becomes invisible, and ready-to-harvest mimana is displayed as grey bananas flying above the tray, held by nothing.

This PR is a part of update line (#15880, #15908) that will greatly reduce amount of clutter in plants code/sprites and, at the last stage, will add bio-engineering - system similar to Bay's xenobotany, except aimed at non-autistic playerbase. The next PR in the line will touch tray code, you all know it's horrible.

### CODE REVIEW

**Comment by Chocobro** [comment]
>Invisible mimana in tray is now a feature

it already is
that's like 80% of the reason i did it

:+1: overall

**Comment by Core0verload** [comment]
I didn't knew it was a feature. Leave a comment with something like `// The missing sprites are totally a feature` next time.

**Comment by Chocobro** [comment]
I don't know why I need to explain this every time
I didn't code it
I idea'd and designed the vast majority of the sprites
please fam

**Comment by phil235** [comment]
Invisible mimana plant is definitely not a feature. I remember making mimana plant sprites myself. (just a recolored version of banana plant)

**Comment by Core0verload** [comment]
It wasn't. Now it is.

**Comment by Chocobro** [comment]
@phil235 
>I remember making mimana plant sprites myself.
your memory is incorrect
i made them a year prior to you making the PR

**Pull request merged**
