### PR TITLE
A cut above. Fire axe resprite.

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR resprites the fire axe. It also gave it different wielded and unwielded  sprites since i had already sprites two different versions and two handed items already support this.

bild

## Why It's Good For The Game

I think it is a shame such a beloved item has such an old soulful sprite.
The axe deserves better,

## Changelog
:cl:
imageadd; The fire axe has been resprited.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
changelog

**Comment by Mothblocks** [comment]
there u go

**Comment by ATH1909** [comment]
:walter:

**Comment by Krysonism** [comment]
I know resprites of iconic items can be controversial. 

So rev up those comments.

**Comment by CRITAWAKETS** [comment]
Looks good, though i feel as if the area to hold the stick or whatever you call it needs less harsh differences in color to indicate itself. Right now it looks like it just has a massive block in the middle.

**Comment by AlinaStarkova** [comment]
this is i think too sharp of a bend, also the handle is too close to the cutting line, if this were to be used in real life there would be risk of smashing your fingers when hitting things since the blade will cut in a bit and your fingers around the handle will risk hitting the wall/window or whatever your smashing

i like the resprite, just maybe push the handle up a pixel to remove that sharp curve near the head

image

**Comment by Krysonism** [comment]
> 
> 
> this is i think too sharp of a bend, also the handle is too close to the cutting line[...]

I will play around with it a bit tomorrow and see if it looks better straightened out. I got this same criticism when i first posted this sprite a few months back so you might be on to some thing.

**Comment by maxymax13** [comment]
handle has too much contrast, looks like polished furniture wood rather than well worn handle, tone down the hue shifting on the red part and make it a brighter red to catch more attention, right now it just looks like a dull uninteresting magenta that doesn't pop out as much

**Comment by AlinaStarkova** [comment]
> 
> 
> > this is i think too sharp of a bend, also the handle is too close to the cutting line[...]
> 
> I will play around with it a bit tomorrow and see if it looks better straightened out. I got this same criticism when i first posted this sprite a few months back so you might be on to some thing.

i do like the very end of the shafts curve though, thats good for leverage when making wide swings so it doesnt slide out of your hand

**Comment by necromanceranne** [comment]
You've been working on this sprite for a while if i remember correctly. Didn't you start this one last year?

**Comment by TheNoobSlayer** [comment]
nah bruh

**Pull request merged**
