### PR TITLE
[WIP]Cloth golem gib fix

### LINKED ISSUE #39050: Odd cloth golem megafauna death
If megafauna kills a cloth golem, they get the "You start gathering your life energy, preparing to rise again..." message and the cloth pile spawns. However, the body also gets gibbed, which ends up preventing revival.

This leaves players in an odd state where game messages tell them that they're getting revived, but they're actually dead. 
Intended behavior would be to dust the cloth pile with no organs spawned.

### PR DESCRIPTION
**Pull request by CreationPro**
[Changelogs]: # (A fix for #39050 . Overrides the cloth golems' gib() proc so that it turns them to ashes instead. If the golem is in a cloth_pile state it also deletes the pile instead of just leaving it there. (What megafauna used to do, basically))

:cl: CreationPro
tweak: Changed cloth golems' gib() function to turn them to ashes instead.
fix: fixed an issue where a cloth golem would get gibbed by megafauna, told to wait for regeneration and get it's head decapitated right after, leaving a permanently dead cloth pile behind.
/:cl:

[why]: # (Fixes #39050)

### CODE REVIEW

**Comment by XDTM** [comment]
This won't work; that human subtype is only used to adminspawn a human as a cloth golem, but normally the species datum is what determines the species.

**Comment by CreationPro** [comment]
Oh crap, you are right.

**Comment by XDTM** [comment]
The `spec_death(gibbed, mob/living/carbon/human/H)` seems ideal for this purpose, though.

**Comment by CreationPro** [comment]
Yeah, that makes sense now. I was trying to use spec_death before, but since admin spawned and manually created golems are different, it wasn't working.

**Comment by XDTM** [comment]
Admin spawned golems are effectievely humans with an auto-applied species datum, so if it works normally it should work with the adminspawn version.

**Pull request closed without merging**
