### PR TITLE
you know what i'm too lazy to finish this object damaging is horrid enough fuck that.

### PR DESCRIPTION
**Pull request by silicons**
:cl:
rscadd: Walls are now able to be damaged!
rscadd: You can examine them to determine how damaged they are! Use a welder on them to repair them!
rscadd: Each wall has different resistances to each kind of projectile, and not all projectiles can damage them. Melee weapons can't scratch them at all!
/:cl:
WIP:
Add a way for people to fix it
Put in different values for things like r_walls
_balance_ it.
Possible **speshul snowflek** wall interactions for the mineral walls and other stuff.

### CODE REVIEW

**Comment by AnonymousNow** [comment]
He actually did it, the absolute madman.

**Comment by ShadowDeath6** [comment]
don't welders take apart walls, though? what if you want to remove a damaged wall?

**Comment by kevinz000** [comment]
for fixing it i havn't decided yet, probably will be a welder on help intent/I'll find a way to do that :P

**Comment by ShadowDeath6** [comment]
maybe metal on a damaged wall to fix it

**Comment by ShadowDeath6** [comment]
:1st_place_medal:

**Comment by PKPenguin321** [comment]
not even close actually

**Pull request closed without merging**
