### PR TITLE
Pope of Sin Update

### PR DESCRIPTION
**Pull request by sawu-tg**
- Acolytes of Hades have received their own unique sprite.
- Fixed an error that would cause Hades to be permanently stuck in Wrath Phase
- Acolytes summoned by Hades are now unable to move more than 6 tiles from him, to prevent leading.
- Hades' Ultimate Wrath has been given an extra effect to indicate it's happening.
- Sins are now global procs.
- Upon death, Hades' corpse will now transform into a portal to the Chapel of Sin, a small away-mission with a puzzle. Completing the puzzle will reward players with an Imbued version of Hades' Staff, giving them access to his power of Judgement.

Layout of the Chapel of Sin:
layout

:cl: Wizard's Federation
fix: Acolytes of Hades have revealed their true forms.
add: We've discovered a way to traverse portals left behind by Hades, and have discovered a great treasure through it.
fix: Hades has undergone Anger Management classes, and should no longer remain wrathful for the duration of his visit.
/:cl:

### CODE REVIEW

**Comment by Jordie0608** [comment]
Remvoing z2 is probably not a good idea

**Comment by sawu-tg** [comment]
@Jordie0608  I think it's just GitHub freaking out. The Chapel is on that level, but it's just placed in space.

**Comment by Jordie0608** [comment]
Still says 77k changes

**Comment by Dorsisdwarf** [comment]
Why is a pope of sin called hades anyway. Is it a reference or something?

**Comment by sawu-tg** [comment]
@Dorsisdwarf It's a reference to Hades, Keeper of the Underworld (the greek god).

**Comment by sawu-tg** [comment]
Also this has been MapMerged and .tgm'd so I haven't the slightest clue why the +/-s are so off.

**Comment by Dorsisdwarf** [comment]
Yes, I know who Hades is. Why is a greek god a "pope of sin"?

**Comment by Thunder12345** [comment]
It's not actually referred to as the Pope of Sin anymore, from what I can see

**Comment by sawu-tg** [comment]
@Dorsisdwarf  Pope of Sin was just the internal name I used for it before actually fleshing it out, and it kinda caught on. His full title is "Hades, [rank] of Sin", the rank randomly being picked on spawn.

Like I've stated before, Hades is the God of the Underworld, and is commonly associated with things like being the Watcher of Souls, Death and Blood. He didn't directly judge Souls himself, but the name was fitting enough in my Eyes.

**Comment by hornygranny** [comment]
power creep ban this sick filth

**Comment by sawu-tg** [comment]
@hornygranny Do you just comment powercreep on every PR?

**Comment by sawu-tg** [comment]
I'm testing loading Pope's Chapel as a Zlevel rather than being on CentCom. Please don't merge this until I ask a maintainer in Coderbus.

**Pull request merged**
