### PR TITLE
The rooms in the back away mission

### PR DESCRIPTION
**Pull request by ZAMODA**
## About The Pull Request
Working on creating a backrooms based/inspired away mission, very work in progress!
Whole map so far:
<details><summary> 4/8/2023 Map</summary>
<p>

image

</p>
</details> 

<details><summary>4/10/2023 Map</summary>
<p>

 image

</p>
</details> 
<details><summary>4/11/2023 Map</summary>
<p>

image

</p>
</details> 

image

## Why It's Good For The Game
New away missions are always good, and Kane Pixels' backrooms is one of the better ones to base it off of.
## Changelog
:cl: Z Man Wit Z Plan
add: Adds the backrooms away mission! (placeholder)
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
i'm not certain i like this in concept but i'm willing to forgive that given that it's been such a long amount of time without a gateway mission. best of luck

**Comment by ZAMODA** [comment]
> i'm not certain i like this in concept but i'm willing to forgive that given that it's been such a long amount of time without a gateway mission. best of luck

thank you for the kind words, I'm trying to be somewhat innovative with the use of one way teleporters to make the whole place more disorienting, and once I get permission from Kane I will also add in the audio beacon sound effect that is in the videos itself.

**Comment by Singul0** [comment]
making the (i assume) randomly generated rooms connect up will be a nightmare no?

**Comment by ZAMODA** [comment]
> making the (i assume) randomly generated rooms connect up will be a nightmare no?

its sadly not randomly generated at the moment, though once I get better at mapping i might come back to this and add that in. Though the one way teleporters and its IMMENSE size will hopefully still give it that sense of randomness.

**Comment by Mothblocks** [comment]
from who

**Comment by ZAMODA** [comment]
> from who

Creator of the backrooms verity I am taking inspiration from.
These two videos are fairly short and showcase it fairly well I'd say
https://www.youtube.com/watch?v=eXdIDjzy6KY
https://www.youtube.com/watch?v=ITuGdHxHi0A

**Comment by ZAMODA** [comment]
i might as well close it myself! (ill reopen at a later state when i actualy have the whole basic layout done)

**Pull request closed without merging**
