### PR TITLE
Mediborg Improvement Drive: Tool Time

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds a full assortment of surgery tools to the mediborg
Mediborgs won't accidentally slice up people if they use the wrong tool
Mediborgs won't fail surgery steps

Split from #7694

### CODE REVIEW

**Comment by xxalpha** [comment]
This should probably be an upgrade module.

**Comment by pudl** [comment]
literally "mediborgs shouldnt have surgery tools, so i'll just make them op as shit and get around it"

**Comment by Incoming5643** [comment]
Keep in mind you can't do surgery on anyone who's not laying down, so if you think this is going to during mediborgs into debraining maniacs you're mistaken.

**Comment by paprka** [comment]
Mediborgs having surgery tools is a good incentive to play mediborg. The admin in charge of silicon policy said it was okay for mediborgs to be doing surgery, even as asimov. Properly done surgery is not harm, and honest mistakes are honest mistakes anyway.

**Comment by Lumipharon** [comment]
except 2-3 of the surgeries literally do cause harm. The other ones (gender, appendix and plastic surgery) are all fine though.

Making the tools safety versions magically is pretty fucking dumb though. Asimov borgs don't just explode if they ACCIDENTALLY harm a human.

**Comment by paprka** [comment]
Again, the guy in charge of the policy says it doesn't fall under asimov harm. So it isn't, end of story.

**Comment by Incoming5643** [comment]
It ain't magic, machines don't get shaken nerves while operating

**Comment by paprka** [comment]
It's not like MDs do surgery anyway tbh

**Comment by Pennwick** [comment]
Hmmm. Aren't there some surgery that require bare hands? Appendectomy and cavity implant removal might be the only two. Maybe removing the appendix should just be a hemostat thing like removing a brain.

**Comment by Lumipharon** [comment]
>Again, the guy in charge of the policy says it doesn't fall under asimov harm. So it isn't, end of story.

But you can literally kill people by successfully doing surgery steps.

AKA: Get up to the 'remove limb' stage of augmenting, then doing another limb. Each one is like 50 damage or some shit. Hell even just doing it once, on a heavily injured person would kill you.

Generic steps like scalpelling people doesn't do damage, though RL obvious would be 'harm', but if we're saying doing 50+ brute to people isn't harm, because of the end goal... uh, that's pretty inconsistant with the rest of silicon policy.

**Comment by Incoming5643** [comment]
I don't think anyone arguing that the augmentation surgery isn't harm. It's also impossible to complete as a mediborg because of the step where you add the robot limb, so if you're in a dark maint hall and the friendly mediborg asks if you want to augment your legs, spoiler alert: He's trying to kill you.

**Comment by paprka** [comment]
Bitch at pandarsenic about it then, that's what he said, so I don't care and neither should you.

**Comment by MrStonedOne** [comment]
Asimov policy dictates that self elected harm is not harm. This is why the ai doesn't bolt down the roboticist at round start.

Remember, anything the ai is allowed or required to let other people do, it can do.

We've actually threaten ais with bannings for not mass driving somebody who wanted to be mass drivered while nekkid, because law 2 and the ai has no law 1 incentive.

**Comment by Lumipharon** [comment]
Actually policy only says that silicons cannot be coerced to obey command with the threat of self harm.
I think the argument about robotics is assuming it is suicide.

I've argued about this in ban requests before, and was told that humans electing to be harmed (going into a fight pit) was not valid, and silicons were obliged to stop them, against their wishes.

**Comment by phil235** [comment]
>Aren't there some surgery that require bare hands?

Yep, these steps could be changed to hemostat

**Comment by Incoming5643** [comment]
That's actually a problem with cavity implants, apparently you can throw nodrop shit in there and it ends up in that limbo you just described. Will fix, but not in the scope of this pull.

**Pull request merged**
