### PR TITLE
Reduces number of changelings per round to 2

### PR DESCRIPTION
**Pull request by Wilchenx**
:cl:
tweak: Reduces number of changelings per round to 2
/:cl:

[why]: # Coderbus agrees that changelings are overpowered, reducing their numbers per round will stop them from dominating rounds untill a proper overhaul comes.

### CODE REVIEW

**Comment by tortellinitony** [comment]
Why is there a codefreeze if nobody listens to it?

**Comment by Repukan** [comment]
Freeze

**Comment by ChangelingRain** [comment]
ice cold

**Comment by Xhuis** [comment]
❄️

**Comment by The-clown-known-as-Pepe** [comment]
i tried

**Comment by BeeSting12** [comment]
RIP

**Comment by DoctoreMad** [comment]
Outside of funny ice memes, how does everyone ACTUALLY feel about this PR?

**Pull request closed without merging**
