### PR TITLE
New space ambient track

### PR DESCRIPTION
**Pull request by atlasle**
## About The Pull Request

Adds a new space ambient track made by me to the game, supposed to be a bit scarier than the others  that  were  recently added as I feel that they're a bit too happy (not to diss I really like them), also cleaned up a bit of ambience.dm as the medical portion of it didn't follow the same rules as the other ones. also also this will only be used for tgstation so license wise I think this is CC BY-SA 3.0 but I'm not sure so correct me if I'm wrong, also this is my first PR so yeah. Here's a link to listen to the track https://voca.ro/18WvrGORDDdR

## Why It's Good For The Game

Variety is the spice of life.

## Changelog

:cl:
sound: A new ambient track will now play in space
/:cl:

### CODE REVIEW

**Comment by LukasBeedellCodestuff** [comment]
good pr quality

**Comment by celulamp** [comment]
being high and traveling space is gonna be way more scary now

**Comment by san7890** [comment]
> CC BY-SA 3.0

yeah that's fine. is this included in the metadata of the audio file? some other people who were adding ambience managed to put the license information in either the license field or the metadata comments (unsure which one) but it would be greatly appreciated if you could do that here as well. it'll be CC BY-SA 3.0 by default but it's just an extra thing to really make sure that people respect your copyright+licensure wishes

**Comment by Farquaar** [comment]
I like!

**Pull request merged**
