### PR TITLE
Add pickup and placing sound for beakers

### PR DESCRIPTION
**Pull request by TheBoondock**
## About The Pull Request
Add a pickup and drop sound for beakers
## Why It's Good For The Game
More sound cues is nice

https://github.com/tgstation/tgstation/assets/92416224/2fc6b2a7-366b-4281-aa2e-c67ee872eba1
## Changelog
:cl:
sound: added pickup and drop sound for beakers
/:cl:

### CODE REVIEW

**Comment by Ilgradhr** [comment]
Can you not make chemistry unbearable?

**Comment by MrMelbert** [comment]
well they're not, so they're doing what you asked for

**Comment by Ilgradhr** [comment]
> well they're not, so they're doing what you asked for

Its getting too noisy doing chems with pouring and picking up/placing sounds. If they add sound for chem machines as they did with gas tanks and gas canisters its going to be so much background noice when you rapid cook some chems.
Im not really against this sound PRs that sprung out lately but they are too loud.

**Comment by MrMelbert** [comment]
Then you should have started with 

> they are too loud

dingus

**Comment by TheBoondock** [comment]
Well its not that loud to me and i think its a nice aesthetic to hear chemical lab sound effects, makes it immersive

**Comment by san7890** [comment]
having a more diverse soundscape is what breaks up repetition, it's far better to cycle through 2 sounds (beakers and glugglugglug stock sound effect) than just the glugglugglug stock sound effect.

**Pull request merged**
