### PR TITLE
You can now buy telecrystals in stacks of 5 and 20

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Telecrystals can be purchased in stacks of five and twenty.
add: The entire stack of telecrystals are added to the uplink when
charging them.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Closing for the feature freeze

**Comment by coiax** [comment]
@ChangelingRain reopen plz

**Comment by KorPhaeron** [comment]
@coiax

**Comment by coiax** [comment]
@KorPhaeron

**Pull request merged**
