### PR TITLE
Patch-16 - Allows admins to see how many players have MIDIs enabled.

### PR DESCRIPTION
**Pull request by silicons**
#22547 closed because feature freeze, told to reopen after freeze.

### CODE REVIEW

**Comment by jughu** [comment]
Time to play you got a steam message notification sound

**Comment by lzimann** [comment]
snowflake and not needed at all

**Comment by Nabski89** [comment]
If it's not truely needed but you want to know, testmerge it?

**Comment by bgobandit** [comment]
can this be moved to its own button (a button that shows global preferences for players) rather than who

**Comment by kevinz000** [comment]
do you need to see everyone's preferences?

**Comment by lzimann** [comment]
at least make it a new verb instead of cluttering who with useless shit

**Comment by Aloraydrel** [comment]
Why is this even needed

**Comment by PKPenguin321** [comment]
Stupid, just get a better taste in midis to play and stop splitting them into 30 parts. I can show you how to convert shit to under 1mb with audacity some time if you'd like

**Comment by juanototo2** [comment]
I know you want to do ear rape when sybil or basil is at 50 or 60, but please. Just... Stop this bloat immediately.

**Comment by Cheridan** [comment]
mehki coding to buff himself yet again

**Pull request closed without merging**
