### PR TITLE
[embarrassing] gene machine hotfix

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
weed rate and weed chance are good when low, not good when high!

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm falling apart

**Comment by Doppeltongue** [comment]
Still doesn't address the problem of production 9 being worse than everything except gatfruit and golden apples. Maybe you should have the base parts be middle of the road, like production 6, yield 5, lifespan 55, endurance 35, weed chance 1 and weed vulnerability 5. Those are the defaults for the supertype that all growns inherit from, and it seems silly to make the machine so much worse than the default.

Instead of having to beg R&D for a usable machine, make the initial machine be used to fix awful traits, and R&D upgrades make the machine transfer great traits.

Also, if you're going to nerf medicinal botany this hard, there needs to be more stuff for botanists to do that makes them relevant to other jobs.

**Comment by kevinz000** [comment]
how about you get good and not rely on a crutch?

**Comment by Kraseo** [comment]
>weed chance 1 being "middle of the road"

LOL

**Comment by Doppeltongue** [comment]
@Kraseo I went by the median. The only plant with worse than that is gaia. I just don't feel that having the machine be several times worse in almost every aspect than default stuff is good design.

@kevinz000 This doesn't affect me, I can make station destroying kudzu faster with the changes, but botanists who want to help the station and don't trawl through the code are going to have a bad time. 

Seriously, I can easily bypass all the shitty ways coderbus has tried to limit botany's griefing, so the changes just make helpful and medicine making botanists take even longer to get their stuff done.

**Comment by ExcessiveUseOfCobblestone** [comment]
this wasn't meant to limit your griefing though, that's why it's a tasteful nerf because it really isn't a nerf at all as you can still do everything you could do, just not as fast or instantly at roundstart.

**Comment by XDTM** [comment]
To be fair you achieved the same result of removing the machine and making botany ask RnD to build it, traits aside.

**Comment by ExcessiveUseOfCobblestone** [comment]
The whole idea you can just give the best stats to your plant across species with no downsides is flawed though from the start.

Gating it behind just building the thing would just make it the equivalent to a gearcheck. 

This is why we need to be careful about implementing crutches, as people find it difficult to walk should they be removed [or in this case nerfed to require cooperation of another department to be reliable].

**Comment by XDTM** [comment]
my point was that its max saveable stats are lower than plant average stats, which leaves very little use cases for this should RnD not be staffed

**Comment by Doppeltongue** [comment]
@ExcessiveUseOfCobblestone It's not a nerf for griefing. It's a massive nerf for botanists that actually want to do things though. Want to make an enormous amount of wood/grass for building? Too bad, you'll have even less time before the shuttle gets to station. Want to make super-medicine for the station? Too bad, no time now. Also, you haven't addressed the fact that the numbers are near the absolute worst. This isn't about having the best stats, this is about garbage stats. 

Production 9 is garbage. Only gatfruit and golden apples have worse with production 10. There is virtually no case where you would use this, and even then it'd barely do anything.



Also, again, it does absolutely nothing for the round-end tedium, but I suppose a forum post would be better for discussing that.

**Comment by ExcessiveUseOfCobblestone** [comment]
This is not the PR to air your gene machine nerf grievances in, this is solely for the FIX of the gene machine which is to make weed related genes go down instead of up.

If you have an issue put it in the coding feedback thread instead so it can be better addressed please.

**Comment by Cheridan** [comment]
@ExcessiveUseOfCobblestone Maybe it would be more consistent if the var was just renamed to Weed Resistance, so that higher=better for all vars?

**Comment by idontwannasignup** [comment]
"I HAVE TO HURRY AND DEBUFF SERVICE DEPARTMENTS" - the nerf
At least lower potency or buff production speed default for balance. 
If the former occurs it'll just stay a trait swapping machine.


Also tagging something like this as [embarrassing] shows how embarrassing the rest of the crew are to antags these days. [prioritize yourself]

**Pull request merged**
