### PR TITLE
Automatic Round-start Access Scaling

### PR DESCRIPTION
**Pull request by Ikarrus**
- Added a new config option MINIMAL_ACCESS_THRESHOLD in game_options.txt that can be used to automatically give players more access during low-pop rounds.
  - If the number of readied players is below this threshold, expanded access will be used and security and assistants will be granted maintenance access if they do not already get it from other server config settings.
  - If the number of readied players exceeds the threshold, minimal access will be used.
  - Default threshold is 20 readied players, which is also when most game modes become available
- Not defining or setting the threshold to 0 will disable this function, if server ops want to manually set the state of round-start access
- If MINIMAL_ACCESS_THRESHOLD is set, players joining the game will be notified whether or not they have expanded access that round.

_This only affects round-start! Access does not automatically change mid-round!_

### CODE REVIEW

**Comment by paprka** [comment]
ok with this, both servers could benefit tbh.

**Comment by Nyvrem** [comment]
You say it only affects round-start but doesn't it also effect joining midround?

**Comment by Deantwo** [comment]
Interesting. Sounds good to me.
Never liked that idea that assistants have maintenance access, but now they'll at least only have maintenance access if security have maintenance access too.

**Comment by Ikarrus** [comment]
All this does is change a config option before access is distributed. If the round has been set to "minimal access mode", it will stay that way for the rest of the round. People who join mid round get the same thing as the people who were there at round start.

It just means you wont suddenly lose maint access because the threshold was reached mid-round.

**Comment by Kromgar** [comment]
Your  taking maint away from assistants in high pop rounds? 30 assitants with nowhere to go might not be a good thing

**Comment by Ikarrus** [comment]
I'm guessing you weren't around for the months were they didn't have maint, then. Your doomsaying holds no ground.

**Comment by pudl** [comment]
when assistants had no maint access they literally shat EVERYTHING up during rounds

**Comment by MrPerson** [comment]
Assistants should keep maint as long as the ass-maint option is on,

Can we not have a discussion about ass-maint? It's a config option, bother the server host if you want it on or off.

**Comment by Ikarrus** [comment]
Yeah, I'll change it so that it just adds the access rather than overriding it altogether.

**Comment by Ikarrus** [comment]
Also Allura, assmiant discussion goes here: https://tgstation13.org/phpBB/viewtopic.php?f=2&t=2636

**Comment by Ikarrus** [comment]
Updated to only add maint access if the threshold isn't reached.

If it is, it no longer overrides server config settings.

This means servers that @MrPerson 's feedback should be addressed.

**Pull request merged**
