### PR TITLE
Pin removal recipe change

### PR DESCRIPTION
**Pull request by Bawhoppen**
Fixes https://github.com/tgstation/-tg-station/issues/12528

Pin removal will now take the upgraded welding tool instead of a plasma cutter

### CODE REVIEW

**Comment by jughu** [comment]
A easier way for me to replace taser pins with laser tag pins force demn security to wear laser tag armour! +1

**Comment by Supermichael777** [comment]
how do you get laser tag pins though?

**Comment by Bawhoppen** [comment]
@Supermichael777 take them out of a laser tag gun

**Comment by PKPenguin321** [comment]
removing pins from guns destroys them you dip

**Comment by Bawhoppen** [comment]
I swore that wasn't the case but maybe

**Comment by PKPenguin321** [comment]
nah they made it that way because they didnt want people taking the standard pins out of the fake laser in the firing range, because "muh antags cant have guns unless they buy an emag!! reeee!!"

**Comment by KorPhaeron** [comment]
Just dunk the guns in lava

**Comment by coiax** [comment]
Just add a box of laser tag pins to the contraband crates of cargo.

**Comment by coiax** [comment]
@Bawhoppen isn't this sort of a weird sidenerf though? an upgraded welding tool takes either the ones in those engineering lockers, or a hacked autolathe. But a plasma cutter can be printed out at R&D.

Is this more about making it accessible to non-Research people? Because I don't know why you can't just use a normal welding torch, or just use two lots of fuel?

**Comment by Bawhoppen** [comment]
@coiax thats a good point I'll fix that

**Comment by Bawhoppen** [comment]
ok now it just uses the base tool

**Pull request merged**
