### PR TITLE
Enables tac reloads for most ballistic weapons.

### PR DESCRIPTION
**Pull request by ShizCalev**
:cl: ShizCalev
tweak: Enabled tactical reloads for most ballistic weapons.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
dont forget ctf "laser guns"

**Comment by JJRcop** [comment]
If you don't know what tactical reload does, it lets you snap a magazine into a gun with an existing magazine in it.
https://github.com/tgstation/tgstation/blob/ff34dc6cf9615553eeaaf3a1fca47a4c71688b8b/code/modules/projectiles/guns/ballistic.dm#L204-L207 https://github.com/tgstation/tgstation/blob/ff34dc6cf9615553eeaaf3a1fca47a4c71688b8b/code/modules/projectiles/guns/ballistic.dm#L181-L184

**Comment by PKPenguin321** [comment]
REEEEELOADING

COVER ME

**Comment by optimumtact** [comment]
GRABBING A MAG HERE

SWITCHING OUT A MAG

**Comment by necromanceranne** [comment]
I kinda got used to not having tactical reload. Even if it did slow me down a bit it encourages you to hold onto your magazines. Like you should. Those are hard to acquire. Bullets themselves less so.

**Comment by actioninja** [comment]
> I kinda got used to not having tactical reload. Even if it did slow me down a bit it encourages you to hold onto your magazines. Like you should. Those are hard to acquire. Bullets themselves less so.

Tac reloading actually swaps the magazine in your hand now instead of dumping it on the floor.

**Comment by Shapsy** [comment]
Boo

Tac-reloading should send the old magazine flying a tile away for effect

**Comment by Tlaltecuhtli** [comment]
> 
> 
> Boo
> 
> Tac-reloading should send the old magazine flying a tile away for effect

make it a config

**Comment by necromanceranne** [comment]
Tactical reloading should send the magazine directly into my opponents eyes to blind them, so they know how much of an operator I am and that I smoke weed.

**Comment by SouDescolado** [comment]
Tactical reloading should have a prob(1) of emptying both magazines on the floor and making bullets go everywhere (Maybe 50 if clumsy)

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
