### PR TITLE
Gas skin interaction - only the basics

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Adds a way to implement gas skin interactions to humans. You can be totally protected by wearing a suit that has STOPSPRESSUREDAMAGE flag (eg space suits)
Currently i've implemented only two gases:
- Water vapor will cloud your vision the higher the mole amount (nothing less than 5 moles, up to being blinded when reaching 30 moles and up), nothing will happen if you protect your eyes or heat
- Nitrium will burn your skin as a caustic gas, unless you're a podperson and you get both tox and brute healed and a small amount of the low metabolization nitrium reagent

## Why It's Good For The Game
Adds an expandable system and a few of the most interesting gas reactions that could happen outside of breathing

## Changelog

:cl:
expansion: adds the gas skin interaction system
expansion: Water vapor will cloud your vision the higher the mole amount (nothing less than 5 moles, up to being blinded when reaching 30 moles and up), nothing will happen if you protect your eyes or heat
expansion: Nitrium will burn your skin as a caustic gas, unless you're a podperson and you get both tox and brute healed and a small amount of the low metabolization nitrium reagent
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
Since the only way to protect from it now is a pressure proof suit, plasmamen clothing will protect them from O2 but they will still interact with Nitrium and burn.
Just something small but that feels odd to left it.

**Comment by Ghilker** [comment]
> Since the only way to protect from it now is a pressure proof suit, plasmamen clothing will protect them from O2 but they will still interact with Nitrium and burn. Just something small but that feels odd to left it.

you're right, i'll see what to do

**Comment by MacBlaze1** [comment]
ghilker coming back for a second round with the world champion atmos maintainer, Lemon. Who will win? Whose vision of Atmos will reign supreme? Find out in 2 weeks.

**Comment by bluetshirtguy** [comment]
Looks cool but they'll probably be a huge amount of small things and jank to come from this.

**Comment by LemonInTheDark** [comment]
I think I mentioned this last time too, I'm a bit concerned about what this'll do to fires

**Comment by Ghilker** [comment]
> I think I mentioned this last time too, I'm a bit concerned about what this'll do to fires

In my tests fires rarely produces more than 10-15 moles of water per tile if in a closed medium room. So the blinding effect will be minimal when inside big flames, you'll get the border effect but you can still see.

It is possible to reach higher amounts of moles but it requires a lot of time and most of the time you've already left the fire

**Comment by Mothblocks** [comment]
Do you consider this a content expansion over a mechanic? This looks like brand new functionality to me.

**Comment by Ghilker** [comment]
> Do you consider this a content expansion over a mechanic? This looks like brand new functionality to me.

We already have environmental interactions with mob, that's why i think is more content expansion than mechanic since it expands on the existing concept.

**Comment by LemonInTheDark** [comment]
I uh, is stale bot not working?

**Comment by LemonInTheDark** [comment]
Will get to this later, need to handle some other things first tho

**Comment by LemonInTheDark** [comment]
Just to be clear, I need more reasoning for why we need this, and also will not merge this with anything that makes fires harder to see stuff in

**Comment by MacBlaze1** [comment]
> Just to be clear, I need more reasoning for why we need this, and also will not merge this with anything that makes fires harder to see stuff in

@LemonInTheDark I would like this to perhaps give freon a skin or organ interaction

**Pull request closed without merging**
