### PR TITLE
Adjust Icebox service sector

### PR DESCRIPTION
**Pull request by fippefi**
## About The Pull Request

Removes firelocks from botany and service airlocks on the 2nd Z-level, puts firelock on botany maint instead. This stops the constant fire alert spam. Besides, what are we trying to protect from with these firelocks, the snow?

## Why It's Good For The Game

Fixes the fire alert spam in botany and service back corridor.

## Changelog

:cl: fippe
fix: Botany and Service firelocks in Icebox moved around to stop fire alarm spam
/:cl:

### CODE REVIEW

**Comment by fippefi** [comment]
in short, it removes these firelocks and puts a firelock on the botany maint door instead, because airlocks shouldn't have firelocks

**Review by san7890 — CHANGES_REQUESTED** [review]
Hey there,

Thanks for the fixes. However, there's no real reason for the maintenance airlock to have a firelock on it in this scenario (it's very, very uncommon for maintenance airlocks to have firelocks on stations), so would you mind removing it/putting it elsewhere? I'm not sure where else you could put it, but if you feel like you can figure something out, that'd be great.

Removing it might be the way to go, but feel free to see if you can't be creative with that. Feel free to mark this PR "Ready for Review" when this has been addressed, I just put it in as a "Draft" for some internal management stuff.

**Comment by fippefi** [comment]
Sounds good. Technically the whole downstairs of botany could be ignored by firelocks; any relevant firelocks are already upstairs anyway so I'll make slight changes then

**Comment by fippefi** [comment]
I removed the maint firelock, there isn't really a reason to do anything fancy about it because it's a simple issue: just this already fixes the constant fire alarm spam in service.

I'm looking at fire alert code in general but I'll make a separate PR for proposed fixes to the somewhat overt alarm spam on icebox. At the moment it triggers far too easily from just below-zero temperatures because it'd hurt a naked carbon.

**Comment by magatsuchi** [comment]
merge from master moment

**Comment by fippefi** [comment]
I'm closing this because I'm hard resetting my master branch and making a new branch for the PR due to merge conflict shittery breaking up; sorry for the ticket trouble - please wait for a second.

**Pull request closed without merging**
