### PR TITLE
Ice Box Station Kitchen Rework - Worthy Of The Name

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

I like all our maps. However, I also listen to a lot of criticism regarding maps. One thing that I've continuously heard across the board is the quality of our kitchen, which Ice Box seems to get the absolute brunt of. It's a very unique design, but it does not work at all for chefs. The concept of having a major and minor kitchen splits the attention unevenly, and it means that a lot of the time, you're stuck leveraging all of the equipment on the lower z-level instead of being up-top and in the light, being able to interact with the crew in a meaningful way. In fact- just look at how few these shutters are:

image

It's an interesting design, but it's ultimately flawed. As far as Multi-Z kitchens go, I have heard that Tramstation does indeed work in it's design of having all the equipment on one z-level (which is easier to parse) and having the cold-room on a lower Z-Level. So, I had a good idea the other day about having a cold room with the walls made of snow. Let's see what that looks like:

image

Pretty neat. If you need more space to store your delicacies, you can get a pickaxe and mine (albeit at the cost of some air-loss). 
Not so bad, I think. I've also shuffled the upper-deck of the kitchen to match:

image

There was an attempt to redo the kitchen earlier this year #66139, but that ultimately fell through for several reasons. People like the diner aesthetic, so I attempted to retain that as much as possible. We also got some nice new diagonal kitchen flooring recently, so I thought I would leverage it. It's a bit difficult to do massive decalling with this diagonal floor variant, but I tried to get something in to add certain levels of contrast.

Wide shot of the lower z-level alterations:

image

## Why It's Good For The Game

Homogenization of maps isn't a good thing, but it's important to notice and change stuff up when it doesn't work. I still like the idea of forcing the crew to have some interaction with the chef, so I kept the shutters to only face towards the diner.

There should be a lot of stuff (both item wise and design-wise) from the old kitchen, as well as design elements and equipment plucked from other maps to form a kitchen that is both more ICE and more BOX.

## Changelog

:cl:
add: Ice Box Station's got a new look. Notably, the cold room is on the bottom floor with the kitchen all being up on the upper Z-Level
/:cl:

### CODE REVIEW

**Comment by bob-b-b** [comment]
Looks nice overall, but it's always felt wrong having bartender/kitchen serving area be on different z levels ontop of being in kind of a new area that isnt super quickly accessible when visiting one or the other.

Don't people usually interact with the bartender when they go to get food and vice versa?

Though i guess thats out of scope for a kitchen rework pr.

**Comment by san7890** [comment]
Tram and IceBox both have the "hole-in-the-wall" bar style where it's slotted on the lower Z-level and has a more Prohibition-type feel. I don't really see any large problems with it, people say it decreases traffic to the bar but it's important to understand that if people odn't want to be in the bar, they won't go to the bar.

It's a shame that Meta and Kilo are the only two that still have the "Maltese Faction" style of Bar and Diner set up, but that's just the way it is. I don't see any pressing need to change that or have it be changed.

**Comment by bluetshirtguy** [comment]
Bless your heart, Interaction is the heart and soul of being chef.

**Comment by Dorsisdwarf** [comment]
Probbably my favorite kitchen design now.

**Comment by bluetshirtguy** [comment]
ah, just as a couple concerns; 1. I think personally the free grill is probably too much, chefs talking to cargo for grills is indeed a good thing
2. A square shape of the kitchen isn't too interesting but if you were  limited then I get it.

**Comment by san7890** [comment]
> ah, just as a couple concerns; 1. I think personally the free grill is probably too much, chefs talking to cargo for grills is indeed a good thing

Tram has a grill, I can remove it if it's concerning.

> 2. A square shape of the kitchen isn't too interesting but if you were  limited then I get it.

It's Ice Box station. I reserve the right to make boxy rooms.

**Review by Maurukas — CHANGES_REQUESTED** [review]
I like it. Two details:

<details>
<summary> Probably a map merge leftover: </summary>

image
</details>

<details>
<summary> Planetary Atmos turf issue in freezer</summary>
This area looks really cool, but it has constant atmospheric problems at roundstart. Specifically /turf/open/floor/plating/snowed is a planetary turf. This means this room is constantly at a temp/pressure that requires internals. It's also hooked into the main atmos grid, which will try to pressurize it up to 101kpa  at room temp - which it will never be able to as the turfs will just delete the excess gas.

image

Suggestion - subtype this turf without the planetary_atmos var, or come up with some other way to make sure this is breathable and not an infinite gas sink.

</details>

**Pull request merged**
