### PR TITLE
Disables all shuttles except for the boxstation one.

### PR DESCRIPTION
**Pull request by Iamgoofball**
All non-box shuttles are replied to with "LYNCH" or ahelping that the captain is griefing. This fixes the issue.

Done at oranges' request.

### CODE REVIEW

**Comment by GunHog** [comment]
Goof just HAS to join in the memes

**Comment by PKPenguin321** [comment]
inb4 oranges speedmerges

**Comment by kevinz000** [comment]
Fuck off.

**Comment by Iamgoofball** [comment]
@kevinz000 When players stop complaining and admins stop banning for buying somethingn other than Box, sure.

**Comment by kevinz000** [comment]
@Iamgoofball you're being a whiney baby and doing your normal "ADMINS BANNED SOMEONE FOR DOING THIS LETS REMOVE IT WITHOUT CONTEXT!~" thing.

**Comment by Iamgoofball** [comment]
@kevinz000 stop ignoring players and admins

**Pull request closed without merging**
