### PR TITLE
Icebox Service Day 0 Patch (Remake of #60701)

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

Remakes #60701 at @Timberpoes request.

EDIT: Adds the Day 1 Patch (more fixes)
EDIT: Addresses #60711 and partially #60700

## Why It's Good For The Game

🐝 

## Changelog
:cl:
fix: Missing APC in Icebox Bar Maint
fix: Changes icebox apiary to the correct type
fix: Icebox Disposals was unlinked under the bar table. This should fix that.
fix: Icebox - It was stated that the new department lacks some visibility so I added some windows to Upstairs Botany to help with that.
fix: Icebox - Bar was mapped using the wrong table type, now it isn't.
fix: Icebox - Kitchen was missing the Processor and Grinder, you can now find them in the freezer and downstairs respectively. 
fix: Icebox - Changes the bot portal in the bar to the correct subtype. 
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
Can you check that cooks have a grinder/proccessor in their kitchen

**Review by Maurukas — CHANGES_REQUESTED** [review]
In the bar, you've used ```/obj/structure/table/wood/bar``` instead. This subtype is used on shuttles/centcom, and has logic on it to prevent climbing, as well as the fireproof, acidproof, lavaproof, and nodeconstruct flags.

Could you swap the bar tables for standard ```/obj/structure/table/wood``` instead?

**Comment by notfrying1pans** [comment]
In my opinion, the kitchen coldroom shouldn't have a glass airlock

**Comment by AlinaStarkova** [comment]
> 
> 
> In the bar, you've used `/obj/structure/table/wood/bar` instead. This subtype is used on shuttles/centcom, and has logic on it to prevent climbing, as well as the fireproof, acidproof, lavaproof, and nodeconstruct flags.
> 
> Could you swap the bar tables for standard `/obj/structure/table/wood` instead?

i had a PR ready to fix this once this PR was merged (as to not cause conflicts) .... my free GBP noooo!

**Pull request merged**
