### PR TITLE
Fixes mixers and filters showing as invisible in the map editor

### PR DESCRIPTION
**Pull request by pxlsr**
## About The Pull Request

It appears the icon naming was broken so I just fixed it

## Why It's Good For The Game

Allows me and others to continue any mapping work

## Changelog
:cl:

fix: Fixes broken icons for default layer mixers and filters

/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
my bad

**Comment by SamuelRowe** [comment]
What must I do to fix the merge conflict?

**Comment by LemonInTheDark** [comment]
you have the github action that compiles changelogs toggled on, as it is by default. you need to go turn it off, and revert your last commit.

**Comment by LemonInTheDark** [comment]
also in general it's a bad idea to pr from master, leads to messes later down the line

**Comment by SamuelRowe** [comment]
> also in general it's a bad idea to pr from master, leads to messes later down the line

cheers mate, which branch should I use?

**Comment by SamuelRowe** [comment]
I'm really confused as to doing this pull request without the changelog @Ghilker could I just get you to make a PR with the files I fixed?

**Comment by SamuelRowe** [comment]
I reallly don't have a clue what I'm doing, it's frustrating me a bit

**Comment by SamuelRowe** [comment]
Please see [https://github.com/tgstation/tgstation/pull/53625](url) for the working PR with less shit mucked up.

**Pull request closed without merging**
