### PR TITLE
Makes the instakill rifle actually instakill

### PR DESCRIPTION
**Pull request by ma44**
:cl:
tweak: Makes the instakill rifle do 1 million damage and have 1 million armor penetration
/:cl:

### CODE REVIEW

**Comment by Carbonhell** [comment]
Why not use the INFINITY define

**Comment by ma44** [comment]
because i don't know how to do anything

**Comment by Incoming5643** [comment]
This was probably not done to spare the megafauna medals.

**Comment by Durkel** [comment]
People still care about those?

**Comment by PKPenguin321** [comment]
What is the point of this

Armor piercing is fine but infinite damage seems kind of hacky

**Comment by MMMiracles** [comment]
The projectile of the instakill rifle ignores all types of shield and armor to instantly gib the victim, the damage means literally nothing unless you fight mobs that return false against gibbing.

**Comment by kevinz000** [comment]
Ma44 stop Kilkun is better.

**Comment by optimumtact** [comment]
This isn't really required, There' no way to get such a rifle in game without badmin intervention right?

**Comment by Shadowlight213** [comment]
@optimumtact Unless some insane person added it to Summon guns, I don't think there is any way. Even ctf needs an admin to turn it on and activate instagib mode.

**Comment by optimumtact** [comment]
Not required, and an admin can edit it in game if required.

**Pull request closed without merging**
