### PR TITLE
Adds sprites for adjustable skirts for most jumpsuits that have one.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Adds sprites for adjusted/folded jumpskirts sprites made by Papaporo, just like jumpsuits have.

## Why It's Good For The Game
Makes Doctors life a lot easier. It's really annoying when you can quickly adjust the jumpsuit of someone for a surgery while if they have a skirt you end up being forced to fully strip the patient.
Less ID theft for when doctors decide to fully strip you at stasis...

Hopefully, in the future, I try my hand at replacing all the roundstart Jumpsuit/skirts to expose the chest, so you don't need to strip a Sec Officer or Lawyer at Stasis because their suits only exposes the arms.

## Changelog
:cl: Guillaume H. Prata / Papaporo Paprito
add: NT shipped new uniform to the station. Jumpskirts can now be adjusted to expose chest/arms just like Jumpsuits already could.
fix: Fix some suits that should expose only the arms fully exposing the chest. Also fix the Botany Jumpsuit having the old style when adjusted.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Tested?

**Comment by GuillaumePrata** [comment]
Yup, checked all skirts in game and couldn't find any error.
Still my last PR had issues so being careful with this one would be wise...

**Comment by LemonInTheDark** [comment]
All the sprites are meant to be in this format right? 
image

There's a few that are more like this, is that intended?
image

**Comment by GuillaumePrata** [comment]
Some suits only fold their arms like this Psychologist one and security ones. The suits would expose the arms but no skirts had this option so I added it since it was an easy thing to sprite.

**Comment by LemonInTheDark** [comment]
Gottcha :)

**Comment by cacogen** [comment]
this revives tactical erp

**Review by Twaticus — APPROVED** [review]
thank you

**Comment by Paprito** [comment]
Bababooye

**Comment by Serxule** [comment]
i can finally be at almost no clothing while still having a jumpsuit

**Comment by AlinaStarkova** [comment]
"Hopefully in the future I try my hand at replacing all the roundstart Jumpsuit/skirts to expose the chest"

😳😳😳

**Comment by GuillaumePrata** [comment]
Ha, I was thinking so much about surgery that I didn't even think of how silly it sounded.

**Comment by GuillaumePrata** [comment]
Sorry for taking long @Rohesie  but I think I fixed the merge conflict... don't know if there is anything else I need to do tho...

**Comment by Rohesie** [comment]
Is the `hydroponics_d` sprite change intended?

**Comment by GuillaumePrata** [comment]
It is, the adjusted hydroponics jumpsuit had the old color palette instead of the new one.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-8). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
