### PR TITLE
TGUI Compiler PHP script

### PR DESCRIPTION
**Pull request by Cyberboss**
What it says on the tin, upload .racts get .js, .css, and gulp output

e.g. https://dextraspace.net/TGUICompiler

### CODE REVIEW

**Comment by Robustin** [comment]
What?

**Comment by AnturK** [comment]
Are we going to include image of fully setup dev environment in the repo next ? This seems like excessive handholding.

**Comment by Cyberboss** [comment]
It was either this or make a new repo for it

**Comment by duncathan** [comment]
I think this is good to have. Anything that can't be compiled with dm.exe is unintuitive to most contributors

**Comment by optimumtact** [comment]
I agree with Antur

**Pull request merged**
