### PR TITLE
Makes the Alt key TOGGLE walk/run

### LINKED ISSUE #23537: User gets stuck in walk when alt-tabbing w/ Hotkeys enabled
Alt-tabbing toggles you into walk mode, however after tabbing back into the game, you are not returned running. (this is a pretty common issues for programs that have functions with alt that don't continue listening once the window loses focus.) 

Would it be possible to switch the run-toggle to a different key? It's rather inconvenient to tab back into a situation where it's critical that you are running (tator eswording you, bomb exploding, insert terrible thing here) and end up just hobbling away.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #23537

:cl: Cyberboss
tweak: The alt key now TOGGLES walking/running
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
Can we get rid of walking entirely? Maybe turn walk into our current running, and running into ye olde sprinting that never stayed for more than like a day or two?

**Comment by ChemicalRascal** [comment]
So if I press ALT to alt-click something...

**Comment by RemieRichards** [comment]
@WJohn no

**Comment by Cyberboss** [comment]
@ChemicalRascal FUCK

**Comment by Kromgar** [comment]
ALT CLICKING REQUIRES YOU STAND STILL

**Comment by ShizCalev** [comment]
Alt-tabbing is still fucked up.

**Pull request closed without merging**
