### PR TITLE
Head beating rebalance

### PR DESCRIPTION
**Pull request by ghost**
Beating someone in the head no longer has a chance to paralyze them for an absurd amount of time.

Instead, it knocks them down just like beating them in the chest has a chance to do, but also adds confusion, since it's harder to knock them when hitting them in the head compared to the chest.

Chest targetting still remains the best option for unarmed melee. Head targeting remains the best option if you have a toolbox or other high-force weapon.

Ideally this rng would be removed entirely, but it's kind of fun when it comes to rev, knocking sense into people quite literally instead of murdering them if they aren't implanted.

The 20 paralyze rng was absolutely disgusting and pretty much made non-stun weapons with high damages ALSO stun weapons which is a little silly.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Finally, the end of changeling batonarm.

**Comment by dannno** [comment]
the knock out on this shit was absolutely absurd
whoever implemented it should be ashamed, and relieved that it is being rectified

**Comment by Steelpoint** [comment]
@Dorsisdwarf 
I thought ling armblades had a rough 50% chance to knock someone out?

**Comment by JJRcop** [comment]
@danno I traced it back to 62e28c2, don't know who the author is since it's from googlecode days and there's only a gmail available.

**Comment by RemieRichards** [comment]
@JJRcop the author is in the gmail address.
It's Mport.

**Comment by Miauw62** [comment]
>mport

DAAAAMMNNN YOUUUUUU MPPOOOOORRRRTTTT!

**Comment by Dorsisdwarf** [comment]
Yeah, but 50% ko and 20 damage might as well be a stunbaton

**Comment by PKPenguin321** [comment]
I'll miss someone hitting the mime in the head once with a crowbar and the mime being unconscious for five minutes, but other than that this is a great change. Remove RNG REMOVE

**Comment by Fox-McCloud** [comment]
:+1:

Good riddance.

**Comment by Jordie0608** [comment]
Changelog

**Comment by Razharas** [comment]
>Ideally this rng would be removed entirely

Just no, fights where everything is calculated are not nice, this is not chess, we already have ranged weapons that are 100% predictable and damn it is bad, no more

**Comment by paprka** [comment]
Razharas you have to be the only person who thinks rng is fun gameplay, it isn't, not in a game with this much potential for lag or other fuckups. The combat is much better when it's consistent.

**Comment by Fox-McCloud** [comment]
I don't see the problem with this PR at all; it's not eliminating RNG combat and making it perfectly calculated, it's just preventing instawin "always target the head" combat.

Why knock someone down for a ~9 seconds when it's a 10% less chance to knock them *unconscious* for ~36 seconds.

**Comment by PKPenguin321** [comment]
Dont think it being closed had to do with the PR itself, some stuff is going on at the tg community at the moment

**Comment by Razharas** [comment]
It was closed for political reasons, code itself is ok

**Comment by paprka** [comment]
Cheri said these existing prs can still be reviewed so it's back i guess

**Comment by dannno** [comment]
it will truly be a shame that you can't make new PRs. i really wish you could have just played nice because you were putting in work that everyone else was too lazy to do and it was great.

**Comment by paprka** [comment]
i doubt this will even be the case danno, there were a lot of misconceptions leading to me getting blacklisted from the server in the first place, but i don't expect any of this to go away any time soon due to the pressuring of certain asspained parties.

**Comment by Cheridan** [comment]
bleh can't be bothered to manual merge this (and nobody else will)

**Pull request closed without merging**
