### PR TITLE
LOWERS THE MONKEY COUNT

### LINKED ISSUE #80308: You can pick monkies from teh species selector
## Issue Summary
This appears to be broken as these are not supposed to be selectable

image

### PR DESCRIPTION
**Pull request by LemonInTheDark**
### Why it's good for the game

Yo bro I put less monkey in your monkey to reduce the monkey per monkey

### CODE REVIEW

**Comment by san7890** [comment]
actually i think people will forget this is an important thing so i think it would be better to do the following on the base proc

```dm
/datum/species/monkey/check_roundstart_eligible()
	if(check_holidays(MONKEYDAY) && (id = SPECIES_MONKEY))
		return TRUE
	return ..()
```

only the base monkey type has this special ID

**Comment by LemonInTheDark** [comment]
> actually i think people will forget this is an important thing so i think it would be better to do the following on the base proc
> 
> ```dm
> /datum/species/monkey/check_roundstart_eligible()
> 	if(check_holidays(MONKEYDAY) && (id = SPECIES_MONKEY))
> 		return TRUE
> 	return ..()
> ```
> 
> only the base monkey type has this special ID

user above me added holodeck monkeys

**Comment by san7890** [comment]
literally nobody remembered it was monkey day

**Comment by LemonInTheDark** [comment]
SAN WHY DO WE HAVE 3 SUBTYPES OF MONKEY THAT AREN'T REAL SANNNN

**Comment by san7890** [comment]
listen i was only responsible for one of those and that was just to get a simple animal cleared while leveraging the complex monkey ai framework that lived on `carbon/human`. i take no responsibility on the humanlegged and freak ones being merged

**Comment by itseasytosee** [comment]
They will remember. The freaks you rejected from your party will remember.

**Pull request merged**
