### PR TITLE
Helmet of Justice nerfs: Lowers the volume by ~40% and raises the cooldown by ~20%

### PR DESCRIPTION
**Pull request by MrsTonedOne**
A replacement or companion for #10495.

old sound: https://tgstation13.org/msoshit/WEEOO1.ogg
New sound: https://tgstation13.org/msoshit/WEEOO2.ogg

### CODE REVIEW

**Comment by Falamazeer** [comment]
Thank you sah!

**Comment by Iamgoofball** [comment]
MSO confirmed for criminal who can't handle the justice

**Comment by freerealestate** [comment]
#10466 WOW

**Comment by bustygoku** [comment]
Please fix https://github.com/tgstation/-tg-station/issues/10077 while you're at it MSO

**Pull request merged**
