### PR TITLE
Ratvar is no longer stopped by pathetic windows

### LINKED ISSUE #28433: Something is weird with Bump() and ratvar
Ratvar cannot escape this tiny brass window box: 
The following code should allow Ratvar to move through any given object. Somehow, Bump() isn't getting called in \~certain cases\~ of which I'm not entirely sure of; movement is called via `step(src, dir_to_step_in)` which should call Bump if it runs into anything.

    /obj/structure/destructible/clockwork/massive/ratvar/Bump(atom/A)
	var/turf/T = get_turf(A)
	if(T == loc)
		T = get_step(A, A.dir) //please don't run into a window like a bird, ratvar
	forceMove(T)
    
    /obj/structure/destructible/clockwork/massive/ratvar/Process_Spacemove()
	return clashing //this var will be FALSE usually, so ratvar will drift

### PR DESCRIPTION
**Pull request by ghost**
:cl: optional name here
fix: Puny windows will no longer stop the progress of Ratvar.
/:cl:

From what I can gather, the old issue was caused by Ratvar being told to move one tile in the direction of A, from A. This meant that Ratvar could get trapped inside of a box of directional windows, because if they faced north, Ratvar would constantly try to step to the north, instead of south, which is the way out. This fixes that by making the new destination be a step from T in the direction from T to A. This sounds like it wouldn't do anything, but it fixed the issue and Ratvar isn't trapped by windows anymore.

Fixes #28433

### CODE REVIEW

**Comment by YotaXP** [comment]
If `get_turf(A) == loc`, then wouldn't `get_dir(src, A)` return `0`?

**Comment by Xhuis** [comment]
I thought so too, but it actually works.

**Comment by YotaXP** [comment]
IIRC, `get_step(T, 0)` will just return `T` since it's a turf, causing this branch to do absolutely nothing.  Have you tried removing lines 51 and 52 completely?

**Comment by Xhuis** [comment]
No, but I'll do that real quick.

**Comment by ChangelingRain** [comment]
This shouldn't do anything, since ratvar isn't on the window's turf; 51 and 52 allow ratvar to leave, for example, the fitness room fighting ring, which has windows on the same turf.

**Comment by Xhuis** [comment]
This seems to be randomly working in some cases and randomly not in others. Byond is really weird. I'll make a fix that actually plays nicely.

**Comment by RemieRichards** [comment]
@YotaXP it will, it's how ```get_turf()``` works.

**Comment by Xhuis** [comment]
This sounds ridiculous, I know it does, but I _promise_ it's working at some times and not working at others. Try it out for yourself if you don't believe me!

**Comment by Xhuis** [comment]
Okay, _now_ it should work properly. It seems to now, at any rate.

**Comment by InsaneHyena** [comment]
Shit god deserves shit weaknesses.

**Comment by Xhuis** [comment]
What do you dislike so much about Ratvar, anyway? Why him in particular, even putting aside your own dislike of the mode?

**Comment by KingPhilipIII** [comment]
Honestly Ratvar has some of the most fleshed out lore of any of the antagonists in SS13. I know on TG roleplay usually isn't that heavily emphasized, but it's still nice to have some backstory so I can scream culty things when Sec is chasing me.

**Comment by Bawhoppen** [comment]
Clock cult is bad lore if you actually read it

**Comment by Xhuis** [comment]
Clockcult lore is actually my headcanon; I really leave the specifics up to players!

**Comment by Cyberboss** [comment]
So, does it work?

**Comment by Xhuis** [comment]
How can windows be real if our eyes aren't real?
(it works!)

**Comment by KingPhilipIII** [comment]
Bad or not, a bitter steampunk enthusiast who's been put in the corner for misbehaving compared to shapeshifting aliens based off The Thing, oversized space fungus, Khorne with a bunch of emo servants AND MOTHERFUCKING SPACE WIZARDS. 

The point is even if you think it's cheesy or bad someone sincerely tried to do something that would stand out in comparison to the other modes.

**Pull request merged**
