### PR TITLE
Revert webhook to when it worked

### LINKED ISSUE #32571: Webhook isn't auto updating
Likely caused by me in #32151, the webhook (@tgstation-server) is not updating itself when a PR is merged that changes its code. In my observations the live version run by @MrStonedOne is stuck at fd26a2884325b205c507babda358090e1321ac06, from PR #32157 (also by me). The reasoning for my suspicions is that @tgstation-server is still tagging PR's with the outdated "Review Again" tag, which was completely removed from the code in f7ed9b5f7ed3349b92b76910738af4cc512ed668. (#32151)

This is probably my fault but I have no idea what I did wrong, I don't have access to error logs. It's also worth keeping in mind that #32151 was merged when the webhook was taken offline for a short duration.

### PR DESCRIPTION
**Pull request by Cyberboss**
Yeah, I just realized GBP hasn't worked since MSO updated it to master. Tagging is broken. Auto-update is broken. Basically the only thing that works is the changelog generator. Unacceptable.

Closes #32571

### CODE REVIEW

**Comment by JJRcop** [comment]
Do we have any error logs?

**Comment by MrStonedOne** [comment]
````
[2017-12-21T20:30:32+00:00] Error on line 797: socket_connect(): unable to connect [111]: Connection refused
[2017-12-22T21:26:35+00:00] Error on line 129: file_get_contents(https://api.github.com/repos/tgstation/tgstation/pulls/33766/comments): failed to open stream: HTTP request failed! 
[2017-12-23T05:16:41+00:00] Error on line 797: socket_connect(): unable to connect [111]: Connection refused
[2017-12-25T18:17:47+00:00] Error on line 797: socket_connect(): unable to connect [111]: Connection refused
[2017-12-27T00:28:23+00:00] Error on line 799: socket_connect(): unable to connect [111]: Connection refused
[2017-12-27T00:29:37+00:00] Error on line 799: socket_connect(): unable to connect [111]: Connection refused
[2017-12-28T16:25:16+00:00] Error on line 180: array_merge(): Argument #1 is not an array
[2017-12-30T11:53:18+00:00] Error on line 799: socket_connect(): unable to connect [111]: Connection refused
[2017-12-30T19:54:31+00:00] Error on line 799: socket_connect(): unable to connect [111]: Connection refused
[2017-12-31T09:07:51+00:00] Error on line 799: socket_connect(): unable to connect [111]: Connection refused
[2017-12-31T20:26:22+00:00] Error on line 549: Use of undefined constant matches - assumed 'matches'
[2017-12-31T23:46:42+00:00] Error on line 799: socket_connect(): unable to connect [111]: Connection refused
[2018-01-02T00:18:23+00:00] Error on line 180: array_merge(): Argument #1 is not an array
[2018-01-02T02:48:20+00:00] Error on line 180: array_merge(): Argument #1 is not an array
[2018-01-02T03:50:07+00:00] Error on line 799: socket_connect(): unable to connect [111]: Connection refused
[2018-01-03T09:24:42+00:00] Error on line 799: socket_connect(): unable to connect [111]: Connection refused
[2018-01-04T16:59:23+00:00] Error on line 817: socket_read(): unable to read from socket [104]: Connection reset by peer
[2018-01-05T06:37:51+00:00] Error on line 180: array_merge(): Argument #1 is not an array

````

**Comment by JJRcop** [comment]
Oops...

**Comment by MrStonedOne** [comment]
Oh, this is my fault.

Fixed.

**Comment by JJRcop** [comment]
I think the `Error on line 549: Use of undefined constant matches - assumed 'matches'` might still be a problem, forgot to use a $

**Comment by MrStonedOne** [comment]
>Basically the only thing that works is the changelog generator. 

Not true.

Basically when I was setting up the byond cdn thing I accidentally the wrong php config file and restricted `tools` php config to only allow execution of files in `static`'s folder

**Pull request closed without merging**
