### PR TITLE
New Donkpocket Box

### PR DESCRIPTION
**Pull request by Chuckleberry-Finn**
:cl: Chuck
imageadd: NT has stopped buying re-boxed storebrand Donkpockets and now stocks stations with real, genuine, tasty Donkpockets!
/:cl:

 

RIP: #35601 
I was asked to throw together some icons for donk baggies, but had some fun making the box.

### CODE REVIEW

**Comment by ChuckTheSheep** [comment]
I re-downloaded the dmi and added my changes. The "borgrped" should not be missing/removed.

**Comment by arsserpentarium** [comment]
Hello, MRTY.

**Comment by WJohn** [comment]
You got any proper before and after pictures?

**Comment by ChuckTheSheep** [comment]
Updated original post.

**Comment by MoreRobustThanYou** [comment]
@ChuckTheSheep fix the conflict. you can do this automatically with the tools/dmitool bat file, then git pulling

**Comment by ChuckTheSheep** [comment]
As we are the same person, you should know we're at work right now. :(

**Comment by nicbn** [comment]
Why did you delete borgrped?

**Comment by MoreRobustThanYou** [comment]
@nicbn icondiffbot is bugged, if you download the dmi, it's still there

**Pull request merged**
