### PR TITLE
Improve tgui routing to allow interface subdirectories

### PR DESCRIPTION
**Pull request by mordent-goonstation**
## About The Pull Request

- Improve tgui routing to support the following interface locations (checking in this order):
    - `/interfaces/Foo/index.tsx`
    - `/interfaces/Foo/index.js`
    - `/Foo.tsx`
    - `/Foo.js`

## Why It's Good For The Game

Allows breaking up behemoth interfaces into smaller parts, letting them be worked on independently.

## Changelog
:cl: Mordent
code: Allowed tgui interfaces to be created in subdirectories
/:cl:

### CODE REVIEW

**Comment by mordent-goonstation** [comment]
Disclosure: I don't play tgstation and only idly glanced at a few other PRs to work out what you want to see in PRs. By all means feel free to edit the changelog stuff accordingly.

**Comment by stylemistake** [comment]
ChemMaster is a very bad example, and I would like you to revert it before this PR is merged.

Please test how big the resulting require context is because you've made it recursive - it will include absolutely every .js file into its list. Might be a source of bloat.

Other than that, I support the changes, it would be very useful for actually large UIs, like DnaConsole; Also it's makes sense for us to support this so that we stay as much in sync as possible.

P.S. I strongly recommend not using default exports because they're notoriously bad to refactor and auto-import, and we need to maintain unity throughout tgui - every module at the moment uses named exports.

**Comment by mordent-goonstation** [comment]
> ChemMaster is a very bad example, and I would like you to revert it.

Bad example as in "it's not a good interface for this", or as in "the way you did it was bad"? If the former, happy for you to suggest one you'd prefer (or I can simply do none of them, but I think having *an* example would be good). I naively chose one that fit the "one file with lots of lines containing several components" criteria. If the latter, happy to discuss why you think that.

**Comment by mordent-goonstation** [comment]
> Please test how big the resulting require context is because you've made it recursive - it will include absolutely every .js file into its list. Might be a source of bloat. You can check with --analyze.

It's recursive within the `interfaces` directory, so AFAICT the only extra files that would be included are if you had .js files in `interfaces` (or its subdirectories) that weren't being included somewhere in the bundle already (to which there is a reasonable argument of "why?"). After replacing the `default` exports with named ones (as suggested above):

image

- All (1.11 MB)
- tgui.bundle.js (735.95 KB)
- tgui-common.bundle.js (348.99 KB)
- tgui-panel.bundle.js (55.9 KB)

- ./packages/tgui/interfaces/ChemMaster (9.17 KB)
- ./packages/tgui/interfaces/ChemMaster/Content.js (2.79 KB)
- ./packages/tgui/interfaces/ChemMaster/PackagingControls/index.js (2.75 KB)
- ./packages/tgui/interfaces/ChemMaster/AnalysisResults.js (1.22 KB)
- ./packages/tgui/interfaces/ChemMaster/ChemicalBuffer/Entry.js (1.21 KB)
- ./packages/tgui/interfaces/ChemMaster/PackagingControls/Item.js (565 B)
- ./packages/tgui/interfaces/ChemMaster/index.js (499 B)
- ./packages/tgui/interfaces/ChemMaster/ChemicalBuffer/index.js (177 B)
- ./packages/tgui/interfaces/ChemMaster/PackagingControls (3.3 KB)
- ./packages/tgui/interfaces/ChemMaster/ChemicalBuffer (1.38 KB)

Baseline (my branch without my commits):

image

- All (1.11 MB)
- tgui.bundle.js (733.75 KB)
- tgui-common.bundle.js (348.99 KB)
- tgui-panel.bundle.js (55.9 KB)

- ./packages/tgui/interfaces/ChemMaster.js (7.69 KB)

The values for my branch with only the changes to the `routes.js` file (i.e. not refactoring ChemMaster) give the same as above (i.e. no change to bundle size).

The change plus ChemMaster refactor increases bundle size by 2.2KB, which is likely the additional boilerplate around the components, increasing ChemMaster by ~20%. Assuming the splitting was done across all interfaces and there was a similar increase (unlikely as most interfaces are not made of multiple components, but going with it as a "worst reasonable case") that would up the parsed size of the interfaces directory from 728.51 KB to ~874KB.

Based solely on this I can understand why you would want to decline this PR, leaving up to your discretion. I would argue that blindly applying it across the codebase would be a huge mistake even if the bundle size was the same, but think that if it improves code readability/maintainability then it could be worth it on a case-by-case basis (for your more complex interfaces, such as the DNAConsole, as you say).

**Comment by mordent-goonstation** [comment]
PR updated to not include ChemMaster refactor.

**Comment by stylemistake** [comment]
I just think you refactored ChemMaster for the sake of an example, but it ended up being a bad example, because it is very boilerplatey, and code monkeys will just blindly copy this pattern which I want to avoid.

I am personally fine with UI being one large file. It requires a decent taste to know when to split the UI module. Ideally there should be a doc explaining how it works, and then those who know would attempt this. (But you're not required to write it in scope of this PR, imma merge this after 24 hours cooldown 👍 )

**Comment by mordent-goonstation** [comment]
> I just think you refactored ChemMaster for the sake of an example

100% correct.

> I am personally fine with UI being one large file. It requires a decent taste to know when to split the UI module

Agreed, and my original ChemMaster example was taken to an extreme case for the sake of illustrating how far you *could* go with it. I would definitely argue that my example was broken up too much. As you highlighted specifically DnaConsole I'm taking a stab at that as an illustrative PR (separate to this one).

Motivation for me making this change is that I want something like this in Goonstation's tgui, and I saw no reason not to implement upstream, but obviously our specific usages within our interfaces will differ.

**Comment by mordent-goonstation** [comment]
Created #57842 as an example refactor using this.

**Pull request merged**
