### PR TITLE
Nerfs shotgun darts

### PR DESCRIPTION
**Pull request by jughu**
ITS TIME TO STOP THE POWERCREEP WE CALL NO REACT SHOTGUN DARTS

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

>cyro syringe requires quite some research with some materials to make
>shotgun darts are no react and 30 units

### CODE REVIEW

**Comment by optimumtact** [comment]
why are you shouting

**Comment by jughu** [comment]
ITS MY VOICE OF BALANCE

**Comment by CPTANT** [comment]
Yeah shotgun darts being no react is really wtf.

**Comment by Repukan** [comment]
Ided

**Review by Cyberboss — APPROVED** [review]

**Comment by Supermichael777** [comment]
holy shit they are

MUAHAHAHAHAH

**Comment by ExcessiveUseOfCobblestone** [comment]
nice pr number

**Comment by RandomMarine** [comment]
How long have they been like this? Since long before humans began allowing reagent reactions in them?

**Comment by DoctoreMad** [comment]
>ELEET PR nerfing something that killed the coder

You know, I agree with with him! I fully do!
But also **WHY**

**Comment by jughu** [comment]
stronk

**Comment by Lumipharon** [comment]
This should not be new to anyone, and isn't really anywher near as strong as it has been in the past.
When goofchem first came out you could make darts that would minibomb gib anyone you shot, with a hilarious 5 second delay.

**Comment by Lumipharon** [comment]
Also just make cryo shotgun darts available from R&D, because shotgun darts are honestly one of the most interesting things you can do right now with guns, and it requires quite a lot of effort to get and use (need a shotgun, autolathe and chem, + time).

**Comment by CPTANT** [comment]
I imagine getting hit by a dart that contains 10u of heated potassium, charcoal and sulfur each would be highly unpleasant.

**Pull request merged**
