### PR TITLE
Adds a mobile camera monitoring console to modular computers

### PR DESCRIPTION
**Pull request by EvilJackCarver**
# WORK IN PROGRESS. Please don't merge yet.

:cl: EvilJackCarver
add: NTNet has added a camera monitor to the modular consoles! You can now view cameras anywhere you want with your laptop, or on your modular console in Research without needing the board. (Sorry, tablet users, that excludes you.)
experiment: This is VERY MUCH a work in progress. 
/:cl:

I've fixed issues that I've found in small-scale testing with a friend, but I expect there may be other issues that might exist - if you could run a testmerge for a short while before merging and let me know of bugs, I'd appreciate it.

I'm also not that great with coding, so if you see something that you feel is a bit of a hack-together, it probably is and any suggestions on fixing that are more than welcome.

# Overview
Adds security camera monitoring to the list of programs on NTNet. You can now watch the armoury get raided from the comfort of your own porcelain throne, if that's the sort of thing that suits your fancy.

# Screenshots

## Home screen
grafik

## Camera list
grafik

## Camera details
grafik

## Watching the feed
grafik

#### The regular version...
grafik

#### ...and the Syndicate version...
grafik

*...complete with edgy pirate team branding and obscene filesize for the authentic Piracy Experience!*

# Debugging information

* Calling the `force_error()` proc will 'crash' the camera monitor program and kick anyone on the camera out of it., as well as generate a runtime.
* 

# Known issues/todo

- [x] ISSUE: The UI header icon for the camera monitoring program is a placeholder.
- [ ] ISSUE: There will sometimes be a camera or two with a blank tag and no GPS coordinates; need to add a `if(c_tag)` check to the camera list rebuild code.
- [ ] Add in code to allow someone to filter cameras by network (private camera networks, anyone?)
- [ ] Make "Close Feed" button take you back to the camera list instead of the home menu
- [ ] (In reference to above bullet) Hell while I'm at it remove checks for if you're viewing camera outside 'viewing camera' screen since it's pretty much useless anyway
- [x] Add a note to the UI that cameras can be quickly searched by using Ctrl-F
- [ ] Figure out how to resolve that merge conflict

### CODE REVIEW

**Comment by GunHog** [comment]
Could you possibly make the buttons wrap into two columns? That list can get quite long!

**Comment by YakumoChen** [comment]
what's the difference between the two downloads? Do you need security access to download the first one and emag for the second?

Also I like this as it gives me an actual half-decent reason to build laptops again

**Comment by EvilJackCarver** [comment]
@GunHog I'll see what I can do, but that may be beyond my skill level at the moment. If you know of any TGUI interface that does the same thing (specifically, sorts list members into two columns) I can look into that and see how it's done, and then look into implementing that here. Otherwise, unfortunately, Ctrl-F may be the best way.

I'll definitely add a note that Ctrl-F can be used to quickly search cameras, though.

@Vidiveni I'll look at it if I have time after work today.

@YakumoChen This is correct; the baseline program requires security equipment access to download. `../pirated` has no access download restriction, but you need to emag the laptop to be able to access it.

**Comment by PKPenguin321** [comment]
>pirated version doesnt have a smaller file size

inaccurate

**Comment by EvilJackCarver** [comment]
I'll poke around that when I get home and see if I can figure out how the
Chem Dispenser does that then. Hopefully it'll be similar in that it calls
{{#each ...}} for the reagents (and not hard-coded)

~ G. A. WILMBROKE

On mobile; typos are my own.

**Comment by EvilJackCarver** [comment]
Closing this to re-open a fresh PR - gonna delete the branch and redo it because trying to fix merge conflicts while doped up on melatonin is very difficult.

**Comment by EvilJackCarver** [comment]
@GunHog I looked and it looks like the way the chem dispenser is sset up I'd need to make the whole text a button in order for it to snap to a grid... not a very good idea if the camera's name is the length of "Central Primary Hallway". Sorry mate.

**Comment by GunHog** [comment]
Thanks for trying! Good luck on fixing your merge stuffs.

**Pull request closed without merging**
