### PR TITLE
Magic Mania 1.91: Life's a lich and then you rework the mechanic to be less terrible

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds the bind soul spell for wizards. It turns them into a lich (skeleton) and gives them access to a long cool down  resurrection spell (starts at 3 minutes).

The resurrection spell can only be used while dead/dying and charges at all times. When used the lich gains a new body at the site of their phylactery and is stunned for a short while. Meanwhile the old wizard body crumbles to dust leaving all the wizards worldly possessions on the ground. Anyone who sees the corpse crumble will also get a cardinal direction pointing towards the wizard.

Every time the wizard dies this way, the time between resurrections is increased by a minute. To take a lich out of the game for good, either destroy the body before the lich can cast the spell again, or destroy the phylactery and kill the wizard one last time.

Liches spawn with robes and spells intact, but nothing else, everything collected on their original body stays there.

As a balance issue, this spell can't be used in the den, the item must be bound after arriving at the station.

Adds a nice black wizard robe ensemble for liches. https://cloud.githubusercontent.com/assets/4176358/6223429/36f49296-b637-11e4-831f-afbc5eddef64.png

Magic mirrors (save for a special badmin only one) can no longer skeletonize people.

Adds a hopeful mulligan fix to wizard rounds problems. Also corrects an adminlog message.

The revengance of #7782

### CODE REVIEW

**Comment by Incoming5643** [comment]
Figure 1: https://www.youtube.com/watch?v=bpgQSbwnWD0

**Comment by Dorsisdwarf** [comment]
Does the phylactery have anything special about it? Visually? What stops a wizard from binding to a single sheet of paper then emptying three whole bins onto the same tile to hide it?

**Comment by Durkel** [comment]
I'm pretty sure zombie has all the same benefits as skeletons, so you might want to blacklist that too.

**Comment by Miauw62** [comment]
>get blink, teleport, jaunt and ressurect

troll wizard :+1:

**Comment by Incoming5643** [comment]
@Dorsisdwarf Right now it turns a shade of dark green, gets a name change, and a description change.

**Comment by PKPenguin321** [comment]
:+1: I was wondering what happened to the original PR

**Pull request merged**
