### PR TITLE
Adds Jackpot medal, awarded for winning a pulse rifle at the arcade.

### PR DESCRIPTION
**Pull request by Shadowlight213**
:cl:
add: You will now receive an achievement for winning a pulse rifle at the arcade.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
RIP completionists

**Comment by Chocobro** [comment]
:+1:

**Comment by Kromgar** [comment]
How do you win a pulse rifle at the arcade?

Emagged?

**Comment by Shadowlight213** [comment]
@Kromgar It's a 1 in a million chance. Emag actually overrides that and wouldn't get you a pulse rifle.

**Comment by Incoming5643** [comment]
Why did you define a string you only used once? That's a net loss.

**Comment by Shadowlight213** [comment]
@Incoming5643 Because Remie would yell at me and make me make it a define if I didn't.
I agree with you on it being a waste, but maintainers say to make it a define.

**Comment by optimumtact** [comment]
How is it a net loss?

**Comment by Shadowlight213** [comment]
Not really a loss so much as it feels pointless.

**Comment by Incoming5643** [comment]
It adds more lines/characters to the file than not defining.

MSO also suggested at one point that defines slow down the compiling process, which is important to me because :sweet_potato: :computer:

**Pull request merged**
