### PR TITLE
Add Slime Scanner to Autolathe

### PR DESCRIPTION
**Pull request by Penguaro**
:cl: Penguaro
add: The Slime Scanner is available from the Autolathe.
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
As mentioned in #26992, currently there are only the two scanners on station and if lost, they are gone for good. This allows their recreation from the autolathe.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
looks fine to me.

**Comment by Penguaro** [comment]
I adjusted the name to have appropriate capitalization. In another PR, I'm going to tweak the rest to be consistent.

**Comment by Penguaro** [comment]
While going through the autolathe designs, I saw that some of the other starting scanners were there and thought it's probably better to just move the slime scanner there from the offset since it is a round start tool anyhow.

Editing PR...

**Comment by FantasticFwoosh** [comment]
There's no real necessity to do that with design disks @Penguaro you can just import the design over.

**Comment by Penguaro** [comment]
@FantasticFwoosh I realize that, and like I said, it's available at round start. There are already Analyzers, Health Analyzers, and Plant Analyzers already in the Autolathe. This seems like more of an oversight that it was missing. The origin tech is only Bio 2 anyhow so it's not as though this is a sneaky shortcut either.

**Comment by XDTM** [comment]
Given that it's a science-only tool it could justify them being in the protolathe, while science does not always have an autolathe.
Either way it's better than them being irreplaceable.

**Comment by Penguaro** [comment]
I won't debate this to death. One other consideration is that many of the designs on the prolathe are unlocked by research and/or have advanced versions available. Mass Spectrometer -> Adv Mass Spect or Micro -> Femtos etc.

It strikes me that this is a basic tool that doesn't get an upgrade and if they're all missing from the xeno lab, it's likely other things are missing as well that need ordering/replicating.

If everyone feels this should be a Prolathe specific item, I can adjust this back there. Logically it just seems like the thing that would be readily available in an autolathe without research. as a basic implement.

**Comment by BeeSting12** [comment]
seems best to just leave it in the autolathe

**Pull request merged**
