### PR TITLE
Improves soulstone code

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Improves soulstone code by removing a redundant iscultist() check. The check immediately before this iscultist() check already checks for the cult antagonist datum, so this iscultist() check isn't needed.

## Why It's Good For The Game

image

image

image

### CODE REVIEW

**Comment by ATH1909** [comment]
> You currently have a negative Fix/Feature pull request delta of -12. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

wha

but https://github.com/tgstation/tgstation/blob/master/.github/gbp-balances.toml says that I have only -1 GBP...

**Comment by Qustinnus** [comment]
lmao

**Comment by ATH1909** [comment]
I've been informed that https://github.com/tgstation/tgstation/blob/gbp-balances/.github/gbp-balances.toml is the branch that contains our actual GBP totals, and that https://github.com/tgstation/tgstation/blob/master/.github/gbp-balances.toml is "just bait".

what the actual fuck

**Comment by maxymax13** [comment]
the gbp debt is catching up to you

**Comment by SuperNovaa41** [comment]
> > You currently have a negative Fix/Feature pull request delta of -12. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> 
> wha
> 
> but https://github.com/tgstation/tgstation/blob/master/.github/gbp-balances.toml says that I have only -1 GBP...

It said this on the other PR too lmao

**Comment by Mothblocks** [comment]
the master one is from before some changes, has been removed now

**Pull request merged**
