### PR TITLE
Gives nukeops a 10tc chameleon kit to purchase

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
add: Nuke Ops can now purchase an insanely marked up Chameleon Kit.
del: Nuke Op Costumes have been removed because of the above being available for your dressup needs.
/:cl:

### CODE REVIEW

**Comment by Wilchenx** [comment]
he comes to save the day once again

**Comment by optimumtact** [comment]
Add the vendor this is not a good pr

**Comment by BlueNothing** [comment]
Why would the Syndicate charge their best agents so much more to use technology they hand out so readily for cheap? Otherwise, I'm all for it.

**Comment by PKPenguin321** [comment]
@BlueNothing game balance reasons

**Comment by PKPenguin321** [comment]
what im more concerned about is why we're adding more costumes to nuke ops when they were deliberately removed in the first place because stealth ops sucked

**Comment by Iamgoofball** [comment]
yeah my goal here is "if we're going to do it we might as well go all the way"

**Pull request closed without merging**
