### PR TITLE
Gang - Purchasing the improvised shotgun actually spawns a gun.

### LINKED ISSUE #28216: Improvised Sawed-off Shotguns from Gang Store don't spawn
Tried to buy one and it didn't spawn, so I tried to buy more.
Took my influence but didn't spawn anything in my hands or on the tiles below me.

This occurred on round 71556.

### PR DESCRIPTION
**Pull request by ShizCalev**
fixes #28216

### CODE REVIEW

**Comment by optimumtact** [comment]
Who merged this? How can it have this many bugs

**Comment by Supermichael777** [comment]
improvised shotguns and shotguns in general are really overpowered

**Comment by ShizCalev** [comment]
@Supermichael777 that is sadly an issue outside of the purview of this PR. feel free to make an issue report about it.

**Comment by Robustin** [comment]
I keep asking Joan to put up the testmerged version since it has all these fixes (and I assumed it would stay testmerged until the poll ends) but its not so we're getting stuff like this.

**Comment by optimumtact** [comment]
Fixes should never be bundled with some other feature for this reason Robutussin

**Comment by Robustin** [comment]
True but when you're tearing a mode inside out and a bug shows up during testing it can be difficult to tell if its something you did while coding or if the bug was there all along.

**Pull request merged**
