### PR TITLE
Ports dash weapons to the dash datum

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
>robustin tries to copypaste dash weapon code into his sword
>maintainers tell him he has to make a datum and cant copypaste
>he copypastes it into a datum and doesnt actually make the original dash weapons use the datum
>PR gets merged

???

This finishes his PR by getting rid of dash weapons and giving the katana a datum

Fixes https://github.com/tgstation/tgstation/issues/31218

### CODE REVIEW

**Comment by Robustin** [comment]
>Touch Kor Code with my PR
>Kor gets offended by my inferior code
>Rest of PR rots because no maintainer will cross Kor

Hmmm

Also by the end it wasn't very copypasta, 2rude.

**Comment by KorPhaeron** [comment]
>Rest of PR rots because no maintainer will cross Kor

I don't have any special say over code standards if anything I have less say than the other maintainers do

**Comment by Robustin** [comment]
When it comes to your own code? Plus it's less about authority on code standards and more just "no maintainer is dumb enough to argue with the person who is Headmin/"""Design Lead"""/Maintainer over something they aren't personally invested in".

**Comment by KorPhaeron** [comment]
Yes, especially when it comes to my own code. @Cyberboss regularly eviscerates it in his reviews

**Comment by optimumtact** [comment]
who merged it

**Comment by AnturK** [comment]
Could you put these in seperate file instead of actions.dm

**Comment by RemieRichards** [comment]
@Robustin nonsense, I regularly shat on kor all the time.

**Comment by Robustin** [comment]
Reminder that the ninja sword can dash every 3 seconds and can build 3 charges.

Just because it's rare doesn't mean it should be stupid.

**Pull request merged**
