### PR TITLE
Removes Fluke Blops

### PR DESCRIPTION
**Pull request by Incoming5643**
Blobs will now be stopped from placing factory/resource nodes where they would do absolutely no good for the blob.

Look mah, a bitflag!

### CODE REVIEW

**Comment by SconesC** [comment]
WHY DIDNT WE MERGE THIS

**Comment by GunHog** [comment]
It is a mix of "git-gud", and limiting strategically. What if you wanted to place a factory, but set up a node later, instead of vise-versa? They could stand to have some warnings, though. 
Warnings are good, hard-limits are bad.

**Comment by Iamgoofball** [comment]
Just add it with an option to disable it with a verb, IMO.

**Comment by Anonus** [comment]
Also, none of that "strategy" gia referenced ever happens or happened. There's no real downside to this, and honestly never was.

**Pull request closed without merging**
