### PR TITLE
Allows any character to use the body type setting regardless of gender

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Removes the restriction on selecting your body type for non-non-binary characters. Prevents the body type option from being wrongly accessible in some cases for genderless species.

## Why It's Good For The Game
Adds another level of harmless character customization, with no obvious downsides in return for allowing even more inclusive character creation.

## Changelog

:cl:
expansion: The option to choose your body type is now available to all characters (with a gendered species)
fix: You can no longer access the body type option on genderless species by setting your gender to other then changing species.
/:cl:

### CODE REVIEW

**Review by Mothblocks — CHANGES_REQUESTED** [review]
We're going to have to migrate the existing binary-gendered characters over so that their body types remain the same. 

I'll commit this to your branch when I can.

**Comment by Mothblocks** [comment]
@Thunder12345 What if we made a new value to body type to just match gender, and made that the default? That's what most people are going to want, but will still allow for people to change body type if they wish to.

**Review by Mothblocks — APPROVED** [review]

**Comment by Thunder12345** [comment]
Thank you for your assistance codermoth

**Comment by KittyNoodle** [comment]
how will this effect gender change potion, will it change body type or gender?

**Comment by Mothblocks** [comment]
It doesn't change it at all because that should never have been using prefs to begin with

**Comment by Mothblocks** [comment]
Do Not TM for migration reasons

**Pull request merged**
