### PR TITLE
Computer console sounds

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request

https://github.com/user-attachments/assets/b756bc49-70f0-4c86-8b04-5f0566d606a2

I've made the sound really quiet (quieter than most other sounds in the game) so it shouldn't be too annoying, there is 7 variants of the clicks so ear fatigue shouldn't strike too bad.
## Why It's Good For The Game
Clicky sounds release a dopamine surge for players and gives you audio feedback when you're doing something, it also triggers when someone is else working at a computer which tells you that they're using it.
## Changelog
:cl: grungussuss
sound: computers now make clicky clacky sounds
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
> can it be turned off in game prefs?

no

**Comment by MTandi** [comment]
Awesome idea to hook it on ui_act.

Thank you for doing all this sound work, they really make the game feel more alive.

**Comment by atlasle** [comment]
i watched the video in public and turned the audio to max cause i couldnt hear it at first...

**Comment by Sadboysuss** [comment]
> Can you add it for laptops too please?

yes.

**Comment by Sadboysuss** [comment]
> i watched the video in public and turned the audio to max cause i couldnt hear it at first...

that's the point, it's supposed to be background and very quiet

**Comment by Sadboysuss** [comment]
> Awesome idea to hook it on ui_act.

melbert's idea

**Comment by Vect0r2** [comment]
I do like the sounds, but they tickle my brain in a way I don't know how to feel. I'll see if I can add more elaboration when I'm not so tired.

**Comment by Sadboysuss** [comment]
need to credit myself in attributions and put the sounds on laptops too so drafting for now

**Comment by Sadboysuss** [comment]
silicons won't make sounds when mashing the keyboard since it's done via remote control

telekinesis users will still make sounds.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Conflicts

**Pull request merged**
