### PR TITLE
The Sisyphus Surgical Table

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

https://github.com/tgstation/tgstation/pull/76523 did not work as intended

Screenshot 2023-07-04 230609

Sisyphus created a new sprite that will hopefully end this once and for all.

Screenshot_2023-07-04_231620

Screenshot_2023-07-04_231629
## Why It's Good For The Game

Hopefully kills the licensing issue.
## Changelog
:cl:
image: Added new Sisyphus brand Surgical Table
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Yeah, but this one's a derivative from a /vg/ sprite.

Source: I'm lying, this sprite looks fine.

**Comment by Wallemations** [comment]
@Imaginos16 dude called you Sisyphus lmaooo
Fitting name based off the amount of times we've had to redo this I think

**Review by Wallemations — APPROVED** [review]

**Comment by Fikou** [comment]
why does the dude lay on the edge of it??

**Comment by Wallemations** [comment]
> why does the dude lay on the edge of it??

It's just a table so you never really get buckled to it to properly position your sprite

**Comment by Fikou** [comment]
yeah but the sprite should account for that and be lower in that case

**Comment by Youtubeboy139** [comment]
> yeah but the sprite should account for that and be lower in that case

It's already been lowered, when overlayed with the original it's a few pixels shorter than before

**Comment by ChungusGamer666** [comment]
It's still better than the oldie sprite, I guess...

**Comment by Capsandi** [comment]
better than the new sprite, very well done

**Comment by norsvenska** [comment]
> why does the dude lay on the edge of it??

It's a problem with buckling. Buckling someone to the table makes their sprite lay on the edge, but placing them on the table through fireman carrying, for example, has it centered. They use different mechanics; the tableplace proc shifts the sprite upwards while normal buckling does not.

**Comment by notfrying1pans** [comment]
i regret to inform you that this still steals from the goon sprite, more specifically this panel bit here, which is used in all 3 of the surgical table resprites, which trace back to goon.
image

I don't think ship of theseusing a sprite to get around licensing will work

**Comment by TheVekter** [comment]
> i regret to inform you that this still steals from the goon sprite, more specifically this panel bit here, which is used in all 3 of the surgical table resprites, which itself is a recoloured version of the original goon sprite. image
> 
> I don't think ship of theseusing a sprite to get around licensing will work

You need to post the Goon sprite and specifically highlight where that is in the resprite. We also need to talk about whether or not we care about an 8x4 segment from the sprite being slightly similar to the Goon sprite is enough reason to be concerned about licensing issues, since eventually you could just say "This 4x4 group of pixels is in the same place as it is on the Goon sprite, we can't use it".

**Comment by Youtubeboy139** [comment]
> i regret to inform you that this still steals from the goon sprite, more specifically this panel bit here, which is used in all 3 of the surgical table resprites, which itself is a recoloured version of the original goon sprite. image
> 
> I don't think ship of theseusing a sprite to get around licensing will work

A goon dev has approved this sprite already

**Comment by TheVekter** [comment]
> A goon dev has approved this sprite already

Thank God. We can finally be done with this.

**Comment by Fikou** [comment]
> > yeah but the sprite should account for that and be lower in that case
> 
> It's already been lowered, when overlayed with the original it's a few pixels shorter than before

it's not been lowered to account for that though. it's just smaller than the current one. the spaceman is still hanging on the edge which looks very weird. imo you should lower the base by 1/2 pixels

**Comment by san7890** [comment]
image

**Comment by Youtubeboy139** [comment]
> it's not been lowered to account for that though. it's just smaller than the current one. the spaceman is still hanging on the edge which looks very weird. imo you should lower the base by 1/2 pixels

It would look like the table is laying on

**Comment by san7890** [comment]
i think maybe it would look better if the sprite were more centered on the table. you can look at how `/obj/structure/bed/double` handles this on `post_buckle_mob()` and `post_unbuckle_mob()`

**Comment by san7890** [comment]
sorry i don't mean use those two procs, i mean look at what those two procs do as far as adjusting/changing the mob's `pixel_y` and applying it into the `mark_patient`/`unmark_patient` procs. i think moving the mob up just a tiny bit will really sell this sprite when it's actually being used.

**Comment by Youtubeboy139** [comment]
> sorry i don't mean use those two procs, i mean look at what those two procs do as far as adjusting/changing the mob's `pixel_y` and applying it into the `mark_patient`/`unmark_patient` procs. i think moving the mob up just a tiny bit will really sell this sprite when it's actually being used.
> 
> if you need help with this reach out

This PR is designed to make TG compliant with licensing, it's fundamentally a sprite change, I have no want nor desire to code how someone is buckled to it. Someone else can code that at a later date, this PR is strictly for licensing issues with Goon.

**Comment by ExcessiveUseOfCobblestone** [comment]
the sprite needs to be shifted up a few pixels, the table literally looks like its clipping into the top part of the wall.

This would also help with the issue mentioned above.

**Comment by san7890** [comment]
i hope you realize we can just revert #76334 and its subsequent PRs to a complaint sprite if that was the keyest of key issues at this current moment

**Comment by Youtubeboy139** [comment]
> the sprite needs to be shifted up a few pixels, the table literally looks like its clipping into the top part of the wall.
> 
> also ur a goob for the above comment

It's not my sprite, I just PRd it

**Comment by Youtubeboy139** [comment]
> i hope you realize we can just revert the sprite to a pre-#76334 state to become compliant if that was the keyest of key issues at this current moment. this is the "prettiest" alternative to that, so it should look as good as possible.

Then I'll let y'all handle that, not my sprite, I just made the PR

**Pull request closed without merging**
