### PR TITLE
Readds headpatting and slapping

### PR DESCRIPTION
**Pull request by Spess-Rando**
reverts #28028

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
no

**Comment by Slignerd** [comment]
You do realize the original removal had twice as many people opposing it than the resident shitposters supporting it?

**Comment by The-clown-known-as-Pepe** [comment]
finally we can slap the living shit out of lizards that wag their tail

**Comment by Qustinnus** [comment]
slapping is fine, headpatting is autistic.

**Comment by The-clown-known-as-Pepe** [comment]
@Qustinnus says the person who added emotes of himself dabbing into the server he's headmin on 👀

**Comment by CPTANT** [comment]
slapping was super lame.

**Comment by The-clown-known-as-Pepe** [comment]
found the lizard

**Comment by Qustinnus** [comment]
discord isn't the server

**Comment by Arianya** [comment]
dabbing is lame tho

**Comment by CPTANT** [comment]
@The-clown-known-as-Pepe  I have literally never played on tg as a ligger.

**Comment by The-clown-known-as-Pepe** [comment]
@CPTANT >on tg

😏

**Comment by Cyberboss** [comment]
If you want it readded, make it not shitcode

**Comment by Slignerd** [comment]
@Cyberboss Define shitcode.

If you mean slapping, then yeah, it does seem somewhat messy. But headpatting code simply uses the same mechanic as hugging.

**Comment by Cyberboss** [comment]
I wasn't supportive of removing it either, but be careful or the fruit will
target hugging next. Reimplement it in a sensible way if you want it in.

**Pull request closed without merging**
