### PR TITLE
chemistry hotfix

### PR DESCRIPTION
**Pull request by pudl**
-adds omnizine to warm donk pockets
-adds mannitol to braincake and brainburgers
-temporarily adds charcoal to the itching powder formula to allow mixing of pentetic acid

### CODE REVIEW

**Comment by Deantwo** [comment]
Should fix https://github.com/tgstation/-tg-station/issues/7252.

**Comment by Deantwo** [comment]
Now your trying to fix https://github.com/tgstation/-tg-station/issues/7229 or what?
Read the comments there for a suggested fix.

**Comment by pudl** [comment]
that fix is retarded

**Comment by Deantwo** [comment]
But you only fixed half of the problem so far, going to change the Salt recipe too?

**Comment by pudl** [comment]
salt doesn't take priority, so pentetic can be mixed regardless

**Comment by AlexanderUlanH** [comment]
Not a huge issue, but this is a very very easy way to get omnizine, compared to botany.

**Pull request merged**
