### PR TITLE
EMPing will sometimes randomly pulse wires

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: EMPs may cause random wires to be pulsed. Please ensure that
sensitive equipment avoids exposure to heavy electromagnetic pulses.
/:cl:

~~10%~~ 33% wire pulse chance, maximum of 3 pulses per atom per EMP.

- [x] ~~Currently not setting off syndicate bombs, need to work out why~~ I had to set off like 50 EMPs near the bomb for it to go off.

### CODE REVIEW

**Comment by coiax** [comment]
@RemieRichards I'm not sure if 10% per wire is enough, but maybe in real play stuff will happen occasionally.

**Comment by coiax** [comment]
What if we changed it to 33% chance?

**Comment by Mindustry** [comment]
Will this affect the PA?

**Comment by PKPenguin321** [comment]
feature freeze is fucking dead

**Comment by Cebasiz** [comment]
>singulo EMP pulses the PA console, turning the PA up

>sing releases itself

feature????

**Comment by Core0verload** [comment]
We would have singulo EMP fucking up singulo cameras and airlocks all the time.

**Comment by XDTM** [comment]
shouldn't it already open them/shock them if that's the case?

**Comment by coiax** [comment]
Cameras don't have wires anymore.

Also, yes, there is a feature freeze, so this won't get merged until the freeze is over.

**Comment by GunHog** [comment]
The PA, and any other machine that is meant to be EMP proof should not be affected by this change.

**Comment by coiax** [comment]
Anything that overrides emp_act() will not have its wires pulsed.

**Comment by KorPhaeron** [comment]
After the freeze please

**Comment by coiax** [comment]
@ChangelingRain reopen plz

**Comment by KorPhaeron** [comment]
>buffing emps

**Comment by AnturK** [comment]
Won't this make singularity able to turn up PA randomly.

**Comment by KorPhaeron** [comment]
Maybe I have low faith in our players but I feel like this puts EMPs into shuttle call territory levels of "this shit isn't worth fixing anymore"

**Comment by coiax** [comment]
Name a pulsed wire that players would view as unfixable.

**Comment by KorPhaeron** [comment]
Not one pulsed wire, but "every single machine in your department now has a random number of pulsed wires good luck figuring that out"

**Comment by coiax** [comment]
Current objects with wires complicated enough to have their own file are:
airalarm.dm   emitter.dm               radio.dm              syndicatebomb.dm
airlock.dm    explosive.dm             r_n_d.dm              tesla_coil.dm
apc.dm        mulebot.dm               robot.dm              vending.dm
autolathe.dm  particle_accelerator.dm  suit_storage_unit.dm  wires.dm

I don't see anything horrific there. Plus this would make throwing EMPs even more arrestable by security, make them more than just "mild damage", gives plausible deniability to cut borg cameras, can lead to "fun" behaviour as the mulebot suddenly runs people over, etc.

**Comment by Cebasiz** [comment]
this is going to cause cyborgs to switch AIs and all kinds of chaos isn't it

i mean not that you'll ever survive an EMP but still conceptually kind of neat

in fact just remove EMP damaged and substitute this instead th x

**Pull request merged**
