### PR TITLE
adds a shower to lavaland seed vault ruin

### LINKED ISSUE #42206: seed vault doesn't have a shower
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Pod people from the seed vault don't get a shower and end up smelling really bad as their space ship fills up with miasma which they can't purge.

### PR DESCRIPTION
**Pull request by granpawalton**
:cl: GranpaWalton
add: The seed vault on lavaland now has a shower incase pod-people get dirty
/:cl:

This fixes #42206 , I can see this also being an issue for a lot of spawn ins

### CODE REVIEW

**Comment by PKPenguin321** [comment]
haha ewww i wonder what what a stinky pod person smells like lol haha

**Comment by Garen7** [comment]
Back when I was a kid my papa used to make his plants take showers with [one of these](https://imgur.com/gallery/1dghx). Why don't botany plants get stinky when you don't give them showers? My immersion is ruined.

**Comment by 81Denton** [comment]
Ah great now every ruin has to have showers mapped in to accomodate the brrrap fetish PR

**Comment by duckay** [comment]
just remove stink instead

**Comment by granpawalton** [comment]
we should just make it so it only punishes people who are blatently dirty like people covered in blood or people who have been dead, right now it is just punishing all players like every 15 minutes and half of the crew have the debuff and are just running around ignoring it

**Comment by tralezab** [comment]
Should podpeople even produce miasma? Should golems produce miasma??

**Comment by ArcaneMusic** [comment]
Yeah, I feel like the root problem here is that plant people shouldn't be affected by hygiene. I mean... they're plants. If they're covered in dirt, that's fine. They're plants. They LIVE in dirt. Even if they have a level of sentience, they still eat raw light, they're basically 90% plant with a little human brain in there. Perhaps that's a different issue entirely.

**Comment by HomocidlePancakes** [comment]
How can something that soen't sweat get dirty? Big 🤔

**Comment by ExcessiveUseOfCobblestone** [comment]
I think addressing the issue directly as done in 42265 is the _cleaner_ solution

**Pull request closed without merging**
