### PR TITLE
Colored and rainbow gloves look better

### PR DESCRIPTION
**Pull request by ChangelingRain**
fucking
There are also on-mob sprite changes but the image of those isn't very helpful and I'm too lazy to do a shot of those ingame.

### CODE REVIEW

**Comment by Anonus** [comment]
For comparison, this is what they looked like before;
gloooooooves

**Comment by WJohn** [comment]
:+1:

**Comment by freerealestate** [comment]
You should probably change the descriptions so they don't describe the colours as being washed out or whatever

**Comment by Anonus** [comment]
They AREN'T described as washed-out, they're literally all "A pair of [color] gloves, they don't look special in any way."

**Comment by freerealestate** [comment]
It happens when you get the coloured gloves by recolouring them in the washing machine. It actually describes them as dodgy. I knew I'd get the wording wrong.

https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/game/machinery/washing_machine.dm#L77

**Comment by daman997** [comment]
ok :+1:

**Comment by SconesC** [comment]
The new "blue" looks a little too similar to Nitrile

**Comment by Firecage** [comment]
@freerealestate That is intended dude. Its not to describe the sprite looking discoloured or anything. That description is intentional for clothing dyed into another colour.

**Comment by freerealestate** [comment]
Yeah, you're right actually. Doesn't really make sense considering
everything you recolour is a perfect reproduction of the original, but it's
useful to check if a clothing item's fake or not.

I always associated the "dodgy colours" message with the shitty glove
sprites OP is fixing.

**Comment by Firecage** [comment]
Don't worry. At first I did aswell.

**Pull request merged**
