### PR TITLE
How To Kill Your Spiders: Spider Update

### PR DESCRIPTION
**Pull request by IndieanaJones**
## About The Pull Request

This is an update to spiders to give the average crewmember more ways to handle them.  The changes are as follows:

- You can set spiders on fire now.  They can put themselves out if they can stand still for 6 seconds.  Note that spiders can set each other on fire if they bump into one another, but that also applies to you.
- Using a fly swatter on a spider does vastly increased damage (30 brute)
- Spraying spiders with pesticides does a solid amount of stamina damage to them (along with a little bit of actual damage, which wasn't added with this PR)

There was also some balancing to the spiders themselves:

- Only hunter and viper spiders inject toxin now, and their poison injection per bite has been decreased by 60% (5 to 2)
- Slightly sped up the rate that broodmothers can lay eggs (15 seconds to 12 seconds)
- Broodmother health increased from 40 to 60
- Broodmother damage increased from 5 to 10 to 10 to 15
- Broodmother web laying speed increased from 4 seconds to 2 seconds

Something to note that the flammable spiders change now also allows any simplemob to be flammable if the var is set to TRUE.  Could be something to consider for some of them in the future.

## Why It's Good For The Game

The changes to the spiders give the crew more logical ways to damage spiders, and unlike a lot of weapons, they are relatively safe to give out to crew without it backfiring.  Allowing spiders to be set on fire also allows things like setting fires or using fire grenades on them to be more satisfying and effective.

The number changes to the spiders themselves involving poison was made because its not very fun to deal with poison in most cases.  Poison's now been restricted to the two spider types who specialize it and they deal much less, so while bitten crewmembers will still need to be concerned, it will take a great deal more bites for them to die to spider toxins.

Finally, the broodmother changes were made in order to give them a little bit more resistance during the earlygame when they're most vulnerable, and allow them to place webs effectively once they have a sufficient egg stockpile.  Now that a majority of the crew has access to spider-slaying weaponry, reducing the egg-laying speed a tad shouldn't be too much of an issue.

## Changelog

:cl:
balance: Spiders can now be set on fire
balance: Spiders now take increased damage to fly swatters
balance: Spiders now take significant stamina damage when in contact with pesticide
balance: Only hunter and viper spiders now inject toxins.  Their toxin injection per bite has been nerfed by 60%.
balance: Broodmothers have been buffed in a number of ways, including more health, more damage, and faster web placement
/:cl:

### CODE REVIEW

**Comment by GolfinhoVoador** [comment]
you know you can just BZ flood, right

**Comment by IndieanaJones** [comment]
> you know you can just BZ flood, right. bz makes it impossible for them to do anything other than exist

Not everyone has access to BZ and spiders have access to atmos-blocking webs.

**Comment by Toastgoats** [comment]
I like a lot of these changes, but spiders are already mercilessly gimped by even the slightest atmos change because you're only informed that you're taking damage once you're practically already dead.

I'd very much prefer this over the janky atmos damage spiders take. But not both.

**Comment by IndieanaJones** [comment]
> I like a lot of these changes, but spiders are already mercilessly gimped by even the slightest atmos change because you're only informed that you're taking damage once you're practically already dead.
> 
> I'd very much prefer this over the janky atmos damage spiders take. But not both.
> 
> Maybe tweak the damage spiders take from atmos so there's more time to notice?

I can agree with this. Most of this PR's inspiration was to make killing spiders less about cheap atmos tactics and putting the power to kill spiders directly into the hands of the crew, as opposed to a small group of armed security guards and atmosians.

**Comment by TemporalOroboros** [comment]
> Only hunter and viper spiders inject toxin now, and their poison injection per bite has been decreased by 60% (5 to 2)
This puts venom injection under the threshold for liver purging (3). Is that intended?

**Comment by theta060** [comment]
spiders are already weak as shit if anything they need flat out buffs

**Comment by gitbirb** [comment]
> > Only hunter and viper spiders inject toxin now, and their poison injection per bite has been decreased by 60% (5 to 2)
> 
> This puts venom injection under the threshold for liver purging (3). Is that intended?

This sounds  important. Also less toxin REALLY gimps the ability for spiders to kill people (especially vipers, which are supposed to be extremely powerful and fast but very weak health-wise, and cost an enriched egg).

**Comment by Serxule** [comment]
> * You can set spiders on fire now.  They can put themselves out if they can stand still for 6 seconds.  Note that spiders can set each other on fire if they bump into one another, but that also applies to you.

this is a bad because they already die insanely fast just from hot air

> * Using a fly swatter on a spider does vastly increased damage (30 brute)

that sounds extremely broken

> * Spraying spiders with pesticides does a solid amount of stamina damage to them (along with a little bit of actual damage, which wasn't added with this PR)

i dont think spiders can even be affected by stamina

> * Only hunter and viper spiders inject toxin now, and their poison injection per bite has been decreased by 60% (5 to 2)

5 to 2 seems too much, its already easily countered

> * Broodmother web laying speed increased from 4 seconds to 2 seconds

why? they're the ones who make nests

**Comment by JohnFulpWillard** [comment]
Ignoring what @Serxule said because no one cares, I think an alternative to the toxin nerf (not an entire alternative but just to not overnerf it) would be to make bio suits protect against getting poison damage, or thick suits in general.

**Comment by Serxule** [comment]
> Ignoring what @Serxule said because no one cares, I think an alternative to the toxin nerf (not an entire alternative but just to not overnerf it) would be to make bio suits protect against getting poison damage, or thick suits in general.

cry harder

**Comment by moocowswag** [comment]
Nerfing viper`s poison injection while also buffing broodmother`s ability to fend for themselves + produce more spiders will probably just get anyone who picks viper over the other 2 upgraded egg options to get hardcore flamed by their fellow spiders, then get flamed by deadchat.

**Comment by ATH1909** [comment]
> Ignoring what @Serxule said because no one cares, I think an alternative to the toxin nerf (not an entire alternative but just to not overnerf it) would be to make bio suits protect against getting poison damage, or thick suits in general.

yeah, I think making them unable to inject poison (but still able to deal damage) through thick clothing (which is something a common crew member can access pretty easily, which is the goal of this PR) would be better than dropping the amount of toxin injected per bite to below the liver purging threshold.

You mentioned that dying to poison is unfun, but that is literally the gameplan of vipers, IIRC. One solution could be to make poison unable to bring you below a certain health threshold (say, 10 health above crit), so a spider at least has to swoop in to cherry tap you.

**Comment by Shadowflame909** [comment]
Jannie get the flamethrower!

**Comment by Dorsisdwarf** [comment]
> Also how long does it take for each spider type to die from being set on fire? Provided that their temperature was completely normal beforehand.
> 
> I have a feeling some spiders will have an extremely short window (viper) to start putting themselves out before its too late and they die anyway.
Spiders take 5 fire damage per 2s Life tick, so they take 15 damage over the course of their six-seconds easily interruptable self-extinguish. Given that they average at like, 30-40 health, that's quite significant extra damage - hitting a spider with an incendiary bullet weapon is probbably a guaranteed DOT kill for most  types. 

I'm a little worried that the self-extinguishing method here is unlike other mobs putting themself out, and without a screenalert or something nobody is gonna learn how to do it without looking it up.

**Comment by moocowswag** [comment]
> Spiders take 5 fire damage per 2s Life tick, so they take at least 15 damage over the course of their six-seconds easily interruptable self-extinguish. Given that they average at like, 30-40 health, that's quite significant extra damage - hitting a spider with an incendiary bullet weapon is probbably a guaranteed DOT kill for non-bruiser types.

They also get increased heat from being on fire aswell right? Id argue it would be over 20 damage from being on fire for six seconds since they`d need to cool down.

**Comment by Livrah** [comment]
How To Kill Your Spiders: Locate them in first 20 minutes.
Most on the time spider nest is destroyed right after the spawn by 1 assistant with a welder and dynamic threat just wasted. Maybe should adress spiders early game by some way, like let broodmother choose a position to spawn (maint areas)?

**Comment by IndieanaJones** [comment]
Alright, here's some additional stuff I'm going to do:

- Hunter and Viper injection reduction undone, both mobs now inject a toxin that does similar toxin damage, but will not send someone into crit.  Viper's venom will probably come with an additional side effect, along with being stronger

- Reduce the amount of unsuitable atmos damage spiders take.  Instead of just trying to open up their nests to space, the strategy should be to burn them instead, which is more interactive for both the spiders and the crew

- Decrease the time it takes for spiders to extinguish themselves

- Remove the BZ interaction with spider structures, if it truly even exists anymore at all (looking at the code I have my doubts)

- Decrease fly swatter damage from 30 to 25

- Maybe change how broodmother spawning works (perhaps a blob-type system instead)

While I know a lot of you here on Github think spiders are pretty weak in their current state, you also have to understand that we have 4 servers and a lot of people with varying opinions which may have influenced some of the balance decisions made in the original PR.  I think making easily accessible crew items like fly swatters and pesticide do more is simply more enjoyable, as it means much less people will be stuck without a means to defend themselves from spiders, something I think is very good.  I also think making spiders interact with more in-game systems (fire) is also good, as it increases the ways people can go about solving the problem of spiders.  Ideally, I'm going to make the adjustments I listed above which will lessen the harshness on the spiders and change the direction of the PR to make spiders more interactive overall.

As I anticipate giving more of the crew access to spider-slaying weaponry will give spiders more resistance to their victories across all servers, I will also look into making their earlygame less harsh, probably via a camera mob someone will be given access to to manually pick a spawn as opposed to pure randomization.  There might also be another broodmother change, but we'll see.  Just give me a bit and I'll update the PR as soon as its ready.

**Comment by DaydreamIQ** [comment]
I like the idea of being able to force spiders back with fire. But considering you can instantly kill a nest by depressurizing it there's just no need

**Comment by wraith-54321** [comment]
I would say maybe make vipers venom paralyze.

**Comment by TheBonded** [comment]
> I like the idea of being able to force spiders back with fire. But considering you can instantly kill a nest by depressurizing it there's just no need

i feel like you posted this without reading the author say in the comment right above yours that the next changes they are working on specifically address the problem of atmos killing spiders

**Comment by Redrover1760** [comment]
> Alright, here's some additional stuff I'm going to do:
> 
> * Hunter and Viper injection reduction undone, both mobs now inject a toxin that does similar toxin damage to what they have now, but will not send someone into crit.  Viper's venom will probably come with an additional side effect, along with being stronger
> * Reduce the amount of unsuitable atmos damage spiders take.  Instead of just trying to open up their nests to space, the strategy should be to burn them instead, which is more interactive for both the spiders and the crew
> * Decrease the time it takes for spiders to extinguish themselves
> * Remove the BZ interaction with spider structures, if it truly even exists anymore at all (looking at the code I have my doubts)
> * Decrease fly swatter damage from 30 to 25
> * Maybe change how broodmother spawning works (perhaps a blob-type system instead)
> 
> While I know a lot of you here on Github think spiders are pretty weak in their current state, you also have to understand that we have 4 servers and a lot of people with varying opinions which may have influenced some of the balance decisions made in the original PR. I think making easily accessible crew items like fly swatters and pesticide do more is simply more enjoyable, as it means much less people will be stuck without a means to defend themselves from spiders, something I think is very good. I also think making spiders interact with more in-game systems (fire) is also good, as it increases the ways people can go about solving the problem of spiders. Ideally, I'm going to make the adjustments I listed above which will lessen the harshness on the spiders and change the direction of the PR to make spiders more interactive overall.
> 
> As I anticipate giving more of the crew access to spider-slaying weaponry will give spiders more resistance to their victories across all servers, I will also look into making their earlygame less harsh, probably via a camera mob someone will be given access to to manually pick a spawn as opposed to pure randomization. Ideally, if Dynamic is going to be spending points on them, then spiders should always provide some base-level threat and not be as easily snuffed out as some of the current random spawns make them out to be. There might also be another broodmother change, but we'll see. Just give me a bit and I'll update the PR as soon as its ready.
> 
> EDIT: Because of the Dynamic 2022 PR currently up, the broodmother spawning will probably have to wait until that's merged so I don't conflict with what Mothblocks is doing, but it will happen.

You should really update the main pr with this to inform people about the extra changes.

**Comment by IndieanaJones** [comment]
I've been a bit busy recently, I'm going to finish the changes I wanted to make and then re-PR this.

**Pull request closed without merging**
