### PR TITLE
You can no longer access maint clockcult bases by turning maint access on

### PR DESCRIPTION
**Pull request by ChangelingRain**
as funny as this is. no.

### CODE REVIEW

**Comment by Robustin** [comment]
Out of curiosity can you hack these doors like normal airlocks?

**Comment by RemieRichards** [comment]
Why are they not called Airclocks? make that a joke like the anima/anime fragments.

**Comment by ChangelingRain** [comment]
You can't hack these, but they've got a simple 3-step deconstruction.

**Comment by Robustin** [comment]
I see, well I am pretty certain that if clock cult doors could fall for emergency maint memes then blood cult doors would do the same, but I'm not sure.

**Comment by ChangelingRain** [comment]
This fixes both, anyway.

**Comment by Iamgoofball** [comment]
remove animes fragments they're corrupting the youth and the american dream

**Pull request merged**
