### PR TITLE
You can cauterize with a laser gun now.

### PR DESCRIPTION
**Pull request by Iamgoofball**
it's a laser it makes sense

### CODE REVIEW

**Comment by CyberbossJHCB** [comment]
-1. It's a pulse not a beam

**Comment by Iamgoofball** [comment]
it's space lasers though???

**Comment by TechnoAlchemisto** [comment]
It's hot so it makes sense

**Comment by PKPenguin321** [comment]
screwing up when using a laser should be catastrophic

**Comment by ExcessiveUseOfCobblestone** [comment]
screwing up when using a laser should do execution damage

**Comment by ShadowDeath6** [comment]
does this imply that lasers can be set to lower damage? if yes then add heat ray feature to lasers
if not then make it actually hit you with a laser when you use it

**Comment by Anonmare** [comment]
@CyberbossJHCB Lasers are actually hot bursts of gas so it works. After all, they have enough mass to change your delta-v.

**Comment by KingPhilipIII** [comment]
Okay. Maybe I don't understand how lasers work, but since when are lasers bursts of gas? It was to my understanding it's focused bursts of heat.

**Comment by Anonmare** [comment]
@KingPhilipIII It's a joke fam. I was making a joke about how you can outrun the lasers and that they move you around in space.

**Comment by KingPhilipIII** [comment]
Okay good. I was having an existential crisis.

**Comment by GunHog** [comment]
Lasers are light. "**L**ight **A**mplification by **S**timulated **E**mission of **R**adiation"

**Comment by BeeSting12** [comment]
make lasers light cigs when?

**Comment by KingPhilipIII** [comment]
I remembered reading somewhere laser was an acronym. Then promptly forgot about it.

**Pull request merged**
