### PR TITLE
Manually smooths out walls on NT Lepton Violet

### LINKED ISSUE #18097: Wabbajack shuttle doesnt rotate very well
shuttle
This was on metastation
@coiax

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
bugfix: Smooths walls on NT Lepton Violet, meaning it can be
rotated without visual bugs.
/:cl:

Fixes #18097.

### CODE REVIEW

**Comment by optimumtact** [comment]
Why are you doing this manually?

**Comment by coiax** [comment]
Because the autosmoothing bugs out with shuttle rotation. So it's been done manually, like all the others have.

**Comment by optimumtact** [comment]
This should be fixed, not hacked

I'm :-1:  on this and the previous fixes

**Comment by coiax** [comment]
It's not hacked, it's manually smoothed, because it's also likely that the autosmoothing didn't do everything exactly in the way that I wanted it to.

**Comment by optimumtact** [comment]
I disagree with that assessment

**Comment by ChangelingRain** [comment]
This is ABSOLUTELY not the right way to fix the issue. Fix shuttle rotation fucking shit up, instead of replacing it with manual smoothing that should probably be avoided where possible.

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Bawhoppen** [comment]
I was going to make auto shuttle wall smoothing like literally tonight, just was doing a few other things quick

**Comment by xxalpha** [comment]
The smoothing is queued on shuttle movement, is it queued on rotation?

**Comment by pudl** [comment]
@ChangelingRain Why should mappers be forced to use smoothwalls? Sometimes there are patterns that cannot be achieved by autosmoothing.

**Comment by xxalpha** [comment]
There is nothing smoothing can't do.

**Comment by KorPhaeron** [comment]
Two maintainers said no

**Pull request closed without merging**
