### PR TITLE
Removes icon state randomization from space turfs.

### LINKED ISSUE #7: Remove space's icon state randomization
Space. There's a lot of it.

There's one last piece of `/turf/open/space/Initialize` that isn't hyper-optimized, setting the dynamic icon_state.

### Estimated Cost
Though not in its own proc, the icon_state set has been measured at 707ms.

### Solutions
The icon state is only used for non-parallax space, which is a rarely used setting, and is more commonly seen in something like camera consoles. A single, nice, tiled icon state should be used. This change is unnoticable to nearly all players.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Another trivial objective from the 'Dev Cycles Initiative': Closes https://github.com/tgstation/dev-cycles-initiative/issues/7

Erg, I've replaced 20 or so icon states with a single one.

## Why It's Good For The Game
According to the issue report: 
> Though not in its own proc, the icon_state set has been measured at 707ms.
Though the icons aree only shown if you've the parallax disabled in your prefs. By default, it's enabled, so it isn't as big of a sacrifice.

Regardless, to make it a nick less dull-looking, the repetition not as obnoxious hopefully, I took the liberty to tamper with the icon and squeeze in a bit of nebula in its background. 😕 
This is of how it looks in the mapper, not animated:
You cannot grasp the true form of the Ghommie's attack!

## Changelog

:cl:
del: Removed icon_state randomization (all but one states) from space turfs to shave a bit of time when initializing maps. This only affects those who have parallax disabled!
imageadd: Prettied up the sole remaining icon state an itsy bit to compensate for it.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
NOOOOOO MY SOULLL

**Review by Mothblocks — APPROVED** [review]

**Comment by Mothblocks** [comment]
Thanks for fixing the stuff I was too bored to 💃

**Comment by Fikou** [comment]
this icon tiles kinda strangely i think, you can see the borders very much

**Comment by Mothblocks** [comment]
@tgstation/sprite-team We want to remove the randomness of space turfs because it's really really slow and scaled badly, can you give a comment on the sprite with that in mind?

**Review by Kylerace — APPROVED** [review]

**Comment by optimumtact** [comment]
This icon looks like absolute dog vomit, full black icon would be preferred

**Pull request merged**
