### PR TITLE
removes recipes for bicard/tricord/kelo/antitox

### PR DESCRIPTION
**Pull request by Iamgoofball**
"hey guys, let's redo the medicine so that there's actual downsides/potential for malpractice/emergent gameplay/more complex recipes to produce cure-alls and the cure-alls aren't always perfect"
*2 years later*
"wtf who re-added all the no-downside cure-alls"

if you wanna be a lazy fuck the garbage trek cure-alls are still in the sleepers and shit

### CODE REVIEW

**Comment by XDTM** [comment]
I'm still gonna brew styptic and splash it in my face

**Comment by Iamgoofball** [comment]
@XDTM the mental image alone makes it worth it

**Comment by XDTM** [comment]
yes

**Comment by PKPenguin321** [comment]
>no downside

they have overdoses

>cureall

they're worse at what they do than goofchems

>this pr remade after already being closed with iirc the OP copy pasted

stop

**Comment by Iamgoofball** [comment]
I handwrote this OP

**Comment by Iamgoofball** [comment]
Overdoses are piss easy to bypass

**Comment by Iamgoofball** [comment]
They're not worse when they stack

**Comment by PKPenguin321** [comment]
Don't they? I once killed a bunch of people as traitor with an upgraded sleeper by overdosing them on every chem (which was horrifyingly lethal)

**Comment by Iamgoofball** [comment]
They're good weapons but for medicine it's easy to avoid the od limit

**Comment by Jalleo** [comment]
Just wondering who readded it? You dont need to ping em.

**Comment by Iamgoofball** [comment]
dunno

**Comment by Bawhoppen** [comment]
T R I M  T H E  C R E E P

**Comment by PKPenguin321** [comment]
trim the creep by nerfing goofchems since they're objectively better than trekchems already

**Comment by Bawhoppen** [comment]
Rise up comrades! For we have sat back too long, letting those who want to oppress us, buff everything into the clouds, thus removing any challenge or intrigue from the game. Now is the time for us to unite against those who wish to see this great game fall to mundanity, and fight for what we truly know is right!
So you must rise up brothers! And help our glorious cause, and to see this game into a new golden age of balance!

**Comment by TechnoAlchemisto** [comment]
op is a dullard

**Comment by Arianya** [comment]
Trim goofchems

**Comment by Cyberboss** [comment]
Duplicate of #24362

**Comment by KorPhaeron** [comment]
Bikeshed PR as long as cyro and the infinite chem sleepers exist so I don't care about it either way, any maintainer is free to do whatever with it

**Comment by Iamgoofball** [comment]
We cant have both active at once because it allows you to stack the healing to absurd levels

**Comment by Iamgoofball** [comment]
I need to nerf sleepers and remove cryo

**Comment by PKPenguin321** [comment]
All this because goof gets triggered whenever somebody mentions how broken goofchem is

**Comment by kevinz000** [comment]
Lol

**Comment by GuyonBroadway** [comment]
If you stick synthflesh in a vape you can outheal someone going at you with a laser gun.

Fix fucking goofchem before touching the last remnants of the old and much more liked system.

**Comment by Iamgoofball** [comment]
why does synthflesh work in a vape, WTF

**Comment by Iamgoofball** [comment]
that's not intended behavior please file a bug report

**Comment by GuyonBroadway** [comment]
Oh no it works perfectly as it creates a smoke cloud that applies the synthflesh as a touch reaction.

**Comment by Arzion5** [comment]
Don't forget that the game shouldn't become more difficult than the other servers. TG is a LRP fast-paced server, this PR would be more suitable for the servers that aim for realism.

**Comment by PKPenguin321** [comment]
Assblasted: The PR
Would it make you feel better if we just renamed the trek chems to "goofium" or some stupid shit instead, goofball?

**Comment by CPTANT** [comment]
Something I was wondering but why don't brute and burn patches have an overdose threshold?

**Comment by Iamgoofball** [comment]
because you gotta apply them in 1 go

I want to remove the over time healing but >>>bicard

**Comment by CPTANT** [comment]
That makes zero sense as a reply Goof

The entire point of OD is that you can't keep re-applying the same thing. You can now take 100 strength 100 brute patches with zero negative effects.

**Comment by Iamgoofball** [comment]
No, the point is to force you to wait before reapplying and force some inv. man

Although yeah that makes sense I'll slap an OD on

**Comment by AnonymousNow** [comment]
Since the introduction of the overdose threshold and peoples' subsequent tendency to accidentally kill patients by facerolling the buttons, I feel as though the weak-but-available Trekchem medicines are in a good place.

**Comment by XDTM** [comment]
Foam is vapor, smoke is touch (inhale if breathed)

**Comment by optimumtact** [comment]
obviously unpopular and I haven't seen design lead give it approval

**Pull request closed without merging**
