### PR TITLE
Properly fixes smart cable lag issues and also fixes the awful connection issues.

### LINKED ISSUE #44929: Solar panel computers wont sync with the solar panels.
Its fucked. Fix it immediately, the station keeps running out of power five minutes into the shift and the AI dies.

### LINKED ISSUE #44935: new mining base has power issues
power runs out withing 10 minutes, maybe put some plasma near the gen so people wont get stuck in there

### LINKED ISSUE #44936: Major powergrid bugs: Almost NO machines connected roundstart!
Almost all the APC's, Smesses,  solar trackers and more didn't connect to the power grid at roundstart! Replacing the wire underneath the structures fixed the issue for that particular machine.

round 112184

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

I ended up just rewriting propagation logic entirely. This needs a bit of cleanup but this is a really high priority fix.
Actually tested this time. I can confirm for sure this is working in all situations that were previously broken.
Closes #44940 
Closes #44936 
Closes #44935 
Closes #44929 
## Why It's Good For The Game

I fucked up bad

## Changelog
:cl:
fix: cables now actually function again (I'm so sorry)
/:cl:

### CODE REVIEW

**Comment by SpaceManiac** [comment]
I assume you didn't mean to delete an unrelated changelog

**Comment by actioninja** [comment]
No, I did not.
Has to be at least one thing going wrong I guess.

**Comment by actioninja** [comment]
I didn't mean to click that fucking button

**Comment by optimumtact** [comment]
this was test merged everywehre and nobody said anything

**Pull request merged**
