### PR TITLE
Adds a config file to enable/disable shuttles from being bought

### PR DESCRIPTION
**Pull request by lzimann**
Works like ruin blacklisting where uncommented paths in config/unbuyableShuttles.txt won't show up in the purchase shuttle menu.

This will only make a difference for shuttles that have a price set in the code(I really don't want to go in balance things by setting a price in all of them so if anyone ever does that, remember to add the path to the txt file).

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@lzimann or we could just remove shuttles from the code that are disabled instead

**Comment by lzimann** [comment]
admins can change to those so it's not really an issue

**Comment by Iamgoofball** [comment]
it is an issue though because captain shuttle purchase

why have a shuttle if the captain can't purchase it

why have purchases at all if the admins control every purchase

**Comment by lzimann** [comment]
oh well that's not my problem nor I care about it

**Comment by KorPhaeron** [comment]
I don't really like adding a backdoor way for an admin to disable something they personally dislike after players/headmins all voted that they enjoy it and it had to go through the review process

**Comment by lzimann** [comment]
if they can't disable and headmins don't want, they will just start banning whoever touches it so this way is the best way...

**Comment by KorPhaeron** [comment]
Then we have a de facto yog council and the separation meme is truly dead

**Comment by Iamgoofball** [comment]
@lzimann or maybe the headmins should consider telling admins not to be douchebags

**Comment by lzimann** [comment]
yea but what if the headmins are the one banning for it

**Comment by Iamgoofball** [comment]
then I might as well remove it from the game because fuck you stop banning people for playing the game the way the coders intended it to be played

**Comment by KorPhaeron** [comment]
Also considering lzimann was both in support of removing buying shuttles entirely and has remote access this feels like a pretty blatant attempt at a backdoor to removing them

**Comment by lzimann** [comment]
if I wanted to remove i would just remove the feature, not do this, I won't even touch the config besides adding it

**Comment by Iamgoofball** [comment]
nah nah

the best way to remove a feature is to remove it stealthily like this

you don't remove outright, otherwise people call you on it

**Comment by optimumtact** [comment]
Lzimann going against the headmins is a problem for the headmins to deal with, not us.

This is logically something any server would potentially want to configure.

**Comment by Cyberboss** [comment]
Separation of admins and coders should be in the /tg/station constitution

**Comment by Bawhoppen** [comment]
it is

**Comment by Iamgoofball** [comment]
alright but if I catch any removed shuttles I'm making a removal PR

**Comment by Iamgoofball** [comment]
why would we bother keeping a shuttle in the code and maintained if we don't use it

**Comment by optimumtact** [comment]
For the same reason we keep the away missions in the code and maintained

for the same reaosn we keep all the other shit like legacy bans

**Pull request merged**
