### PR TITLE
Kill move loop processing if we're deleted

### LINKED ISSUE #78585: Runtime in visual delay
## Reproduction:
1. Load meta station(any other map should work as well)
2. Literarily do nothing. just wait for 5 minutes or less
3. Get runtime
Screenshot (304)

Most of the time reproducible other times random

### LINKED ISSUE #79279: Flaky test monkey_business: Cannot read null.visual_delay
Flaky tests were detected in [this test run](https://github.com/tgstation/tgstation/actions/runs/6646551024/attempts/1). This means that there was a failure that was cleared when the tests were simply restarted.
Failures:
```
monkey_business: [22:02:12] Runtime in movement_types.dm,115: Cannot read null.visual_delay
proc name: process (/datum/move_loop/process)
src: /datum/move_loop/has_target/mo... (/datum/move_loop/has_target/move_towards_budget)
call stack:
/datum/move_loop/has_target/mo... (/datum/move_loop/has_target/move_towards_budget): process()
AI movement (/datum/controller/subsystem/movement/ai_movement): pour bucket(/list (/list))
AI movement (/datum/controller/subsystem/movement/ai_movement): fire(0)
AI movement (/datum/controller/subsystem/movement/ai_movement): fire(0)
AI movement (/datum/controller/subsystem/movement/ai_movement): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop(2)
Master (/datum/controller/master): StartProcessing(0) at movement_types.dm:115
```

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Fixes #79279
Fixes #78585
This _is_ a fix but it's a bit of a hamfisted method.

What I can identify about this bug:
- Sometimes moveloops keep processing after `destroy` is called on them

Resultingly I just check if we've been deleted in `process` and kill our processing if we have. This isn't very elegant.

What I have not identified:
- Why is this even happening? (Difficult, because by the time the runtime triggers we've lost all context as to who it was controlling and why they were deleted)
- Who even tells move loops to start or stop processing? (They don't seem to do it themselves?)

As a result if someone is aware of a more sensible place to locate this check I'm all ears

## Changelog

Not player facing
Makes all of our CI stop failing

### CODE REVIEW

**Comment by SyncIt21** [comment]
> Why is this even happening?

Upon following up the stack trace one cause is when a bot attempts to open an airlock door. It most of the time originates from the ai controller.

**Comment by Jacquerel** [comment]
> Also implement [#78585 (comment)](https://github.com/tgstation/tgstation/issues/78585#issuecomment-1734157823) just in case

I'll be honest while it may be a sensible change I don't think it could be relevant, this isn't happening in cases where it would have naturally ended.

**Comment by SyncIt21** [comment]
> I'll be honest while it may be a sensible change I don't think it could be relevant, this isn't happening in cases where it would have naturally ended.

True it does not help with this issue but as you said a sensible change none the less. Your call

**Comment by SyncIt21** [comment]
All CI is failing without this fix. It's best to merge this asap and then figure out later why the `monkey_business` unit test causes the move loop to delete itself prematurely.

**Comment by Jacquerel** [comment]
Hopefully redundant with #79384

**Pull request closed without merging**
