### PR TITLE
Get more research points from Upgrading & Synchronizing multiple R & D servers

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
Just like crypto mining i.e., when you want more, you build more machines & super cool them similarly if you want more research points you can now build multiple R & D server's & cool them down with freezers

1. Upgrading R & D servers with better scanning modules will generate more points but will also generate more heat so you have to cool down that turf with freezers. Each tier of scanning module has an operational temperature range which must be maintained at all times. If the temps go up your point gain decreases till it becomes 0. If the temps go down you can get an max bonus of 1.5 x the point gain for that tier 
Here is the operational temp range for a specific tier of scanning module
Tier----->Temp
1-------->60-80k
2-------->50-70k
3-------->40-60k
4-------->30-50k

2. If an master server is available & is operational then the contribution of multiple servers is combined together in an diminishing fashion so for example if you have 3 servers the the total contribution from all 3 servers is
`Total contribution = S1/1 + S2/2 + S3/3`
i.e. with each server synchronization overhead increases so for the nth server its contribution is divided by n

Below is the video demonstrating the whole thing

https://user-images.githubusercontent.com/110812394/206917139-5eb4487e-7e6d-43ba-9872-c7bd8aa95bb3.mp4

## Why It's Good For The Game
1. Will encourage R & D to build more servers and they might even talk with engineering to build a dedicated room for running multiple servers thus giving players something to do
2. Makes the master server a little special & so players will be encouraged to protect it better
3. It's also the most logical thing to do because the freezer near the server room served no purpose in keeping the room cool. It 
only deterred antagonist's & regular players from entering the room.  Also, better scanning modules should logically equal to better research and more servers should mean even more research just like in the real world
5. More research points = more fun

## Changelog

:cl:
add: overclocking R & D servers just like in the real world
add: synchronizing multiple R & D servers with an active master
qol: make research faster
/:cl:

### CODE REVIEW

**Comment by TheGreatValvatorez** [comment]
People trying to do everything but expiriscience

**Comment by SyncIt21** [comment]
> So what happens with the servers while in space?

Maximum efficiency if the server is still connected to an apc that is

**Comment by optimumtact** [comment]
I'm simply not interested in this change, I'm always open to more experiments especially ones that replace the scanning experiments, but this is just poorly disguised point farming and it doesn't really fit with the vision I had for experisci which is actually zero points gain without experiments.

Closing in 24 hours.

**Comment by ChungusGamer666** [comment]
Anything that encourages AFKing and waiting for a number to go up is bad and unengaging gameplay.

**Comment by SyncIt21** [comment]
> I'm simply not interested in this change, I'm always open to more experiments especially ones that replace the scanning experiments, but this is just poorly disguised point farming and it doesn't really fit with the vision I had for experisci which is actually zero points gain without experiments.
> 
> Closing in 24 hours.

This PR does not go against your idea of creating more experiments to unlock research upgrades. 

You can have upgrades which requires both an experiment to unlock them & requires high amount of points. 

This will allow you to get that high amount of points faster and will also allow you to increase the points required for an upgrade so that players will be encouraged to use this feature. 

With this you can also remove the dumb idea of discount experiments which literally makes no sense.

**Pull request closed without merging**
