### PR TITLE
Removes two redundant components

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

We're starting to get to have enough components that people don't realise that what they want already exists but doesn't have the name they expect 🙃 

I recently added `track_hierarchical_movement` which is similar enough to `connect_containers` that it shouldn't independently exist, even if I like sending a new signal more than the ugly setup pattern for `connect_loc`.

`trait_loc` is actually older than `give_turf_traits` but `give_turf_traits` covers more edge cases than `turf_loc` so seems like the better one to maintain.
HOWEVER `give_turf_traits` held a list of references to atoms in it, which isn't great in an element. I couldn't think of a way to completely eliminate the list, but it isn't a list of references any more so it shouldn't cause any hard deletions.

## Why It's Good For The Game

Having two components which do the same thing but marginally differently is confusing and going to cause us trouble down the line.

## Changelog

Not player facing

### CODE REVIEW

**Review by Ghommie — COMMENTED** [review]
Remember to remove the `COMSIG_MOVABLE_OR_CONTAINER_MOVED` signal while you're at it.

Also I'll probably change and rename `give_turf_traits` into `give_loc_traits` sometime later (after this is merged). I think it's kinda unneedingly restrictive to limit its effect to turfs.

**Comment by Jacquerel** [comment]
> Also I'll probably change and rename `give_turf_traits` into `give_loc_traits` sometime later (after this is merged). I think it's kinda unneedingly restrictive to limit its effect to turfs.

Unless I am misunderstanding you that would be an unwanted change in function, some of these things definitely aren't supposed to work unless they're on turfs.

**Comment by Ghommie** [comment]
> Unless I am misunderstanding you that would be an unwanted change in function, some of these things definitely aren't supposed to work unless they're on turfs.

Perhaps you're right.

**Comment by san7890** [comment]
undraft when ci is passing

**Pull request merged**
