### PR TITLE
Improvised Shell Rework Attempt 2

### PR DESCRIPTION
**Pull request by Impisi**
Hopefully this follow code standards now. I really feel like I've learned so much on not being a fuck up :)

Anyway, the gist from last time is that improvised shells now have random range and deal more damage. They've still way more gimped than proper buckshot shells. Buckshot will deal 90 point blank, improvised will deal 60 and have much worse range. Also they throw pretty sparks all over the place when you fire them.

Overloaded shells fire four explosive pellets with a good chance of hitting you. They now cost more black powder and now need liquid plasma to make (no, not the stable kind). It isn't strong enough to punch holes in the station but it'll mess up windows and in two shots or so will knock down regular walls. Perfect for B&E/murder if you don't mind getting your ass blown up.

As always, I'm open to all suggestions and criticisms. I nerfed the overloaded shells pellets from 6 to 4 on a suggestion so I _will_ listen.

:cl: Impisi
tweak: Improvised shells now deal more far more damage but are more inaccurate.
tweak: Overloaded shells now require liquid plasma in addition to black powder. Shells now fire explosive pellets that are good at hurting you and everything in front of you.
/:cl:

### CODE REVIEW

**Comment by TheNightingale** [comment]
Is it still more efficient to hack an autolathe and print out slugs or buckshot?

**Comment by Impisi** [comment]
Much more efficient. Not only does buckshot do more damage but it is more accurate and had much longer range.

One of my design paradigms was making it inferior to buckshot to incentivise assistants breaking into cargo. Once they get a taste of the shot they'll want the better version. This creates conflict and conflict is fun.

**Comment by Impisi** [comment]
I probably should have had a flashier title. Like "Adds Flak Effect to Improvised shells"

**Comment by KorPhaeron** [comment]
@duncathan 

This is fine balance wise so whenever

**Pull request merged**
