### PR TITLE
[READY]New Map: Donutstation V.5 (GOLD) (Platinum Hits)

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
add: A new(old?) map, Donutstation, is now in rotation.
/:cl:

[Map Image](https://i.gyazo.com/2c202957214286287767e32882061bfc.png)
[Comparison Image of Original](https://wiki.ss13.co/images/9/9b/DONUTMUTHAFUCCKARS.jpg)

**Progress**
- [x] Departmental Layout
- [x] Atmos
- [x] Wiring
- [x] Detailing/fluff
- [x] Floor tiling

A faithful recreation of Donutstation, keeping some landmarks of the old map similar while bringing in all the new content and departments that come with it.

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
Will it run singulo or supermatter? Or some other engine?

**Comment by MMMiracles** [comment]
It runs singularity.

**Review by Tlaltecuhtli — CHANGES_REQUESTED** [review]
well lets see:
- captain office is too exposed to space
- ai upload too exposed to space
- hos office too exposed to maint

**Comment by MMMiracles** [comment]
@Tlaltecuhtli 

- shouldn't be too big of an issue unless the captain never bothers to grab the disk (his one fucking JOB)
- upload is debatable, i'll slap some external cameras on it and maybe another wall layer if space access is that big of an issue
- hos was meant to have an r-wall surrounding his office, other maps have 1 maint door between his office so it shouldn't be as big of an issue

**Review by Tlaltecuhtli — CHANGES_REQUESTED** [review]
- atmos gas rooms not being in space means if someone breaks the r wall everything gets flooded with NaN pka of gases
- no incinerator
- engineering seems really small

**Review by Tlaltecuhtli — COMMENTED** [review]
- cargo is missing disposals room
- sci missing nanite lab
- medical without morgue  means an overflow of dead bodies

**Comment by MMMiracles** [comment]
- i should probably replace that stupid amount of pressure with gas miners so that isn't as much of an issue
- i'm dumb and forgot to map that in, i even have the incinerator pipeline mapped in on atmos
- comfy engineering
- disposals is on the southern end, haven't built that in yet since i haven't gotten to disposals piping
- fuckin' nanites i'll fix it
- chaplain can deal with the dead, might be an interesting dynamic if he actually gets involved with corpse disposal

**Review by Tlaltecuhtli — CHANGES_REQUESTED** [review]
- no vault

**Comment by Militaires** [comment]
lmao ceres

**Comment by rustledjimm** [comment]
good old map. Most of the points of "X is too exposed" isn't really an argument imo. Just see it as a challenge rather than making everything easy.

**Comment by BeeSting12** [comment]
something being too exposed isn't an argument in most cases, it makes the game more challenging. the mapper's job isn't to make everything 100% antag/thief proof

**Comment by GuyonBroadway** [comment]
Did you know that due to foamcode and the lack of doors back in goons old days it meant chemists on donutstation could make an infinite tidal wave of poo foam and is part of the reason goon removed poo.

I just thought that was interesting.

**Comment by davethwave** [comment]
Sounds like this will interesting.

**Comment by ShizCalev** [comment]
@GuyonBroadway rip self-replicating merculite foam

**Comment by optimumtact** [comment]
no fucking non SM engines

**Comment by MMMiracles** [comment]
pubby has a tesla engine

**Comment by pubby** [comment]
kool map

image

put windows here so there isn't a nasty surprise behind those walls

**Comment by subject217** [comment]
oranges has said before that he doesn't want any new maps with singulo or tesla. 

donutstation is designed around having a singularity in the middle so it doesn't really work otherwise.

**Comment by MMMiracles** [comment]
like i get the sm is technically the more mechanically 'interesting' engine but having some variety in the map pool past a low-pop map and having people interacting with multiple engines isn't a bad thing at all.

**Comment by anconfuzedrock** [comment]
We got a map where assistants get free deathsquad emergency oxygen tanks and a pair of regular ins gloves spawns on the table in tool storage, a map having the horrifying difference of a more vulnerable captain's office isn't too big an issue.

**Comment by dr-bee** [comment]
Boo on the singulo. Replace it with an SM, not only is the SM more interesting to run, having the SM being central to the station will make delamming much more viable method of causing chaos as it will probably damage EVERYTHING.

**Comment by optimumtact** [comment]
I won't merge a map without the right type of engine, this is well established.

**Comment by MMMiracles** [comment]
Won't merge as in you personally won't do it or you'll prevent other maintainers from doing so?

**Comment by optimumtact** [comment]
I'll dab on you so hard you'll fly into orbit above australia

**Comment by MMMiracles** [comment]
maybe i'll have some orange juice with my breakfest tomorrow

**Comment by MMMiracles** [comment]
For real though it should be part of the contributing.dm if its supposed to be well established.

**Comment by KingPhilipIII** [comment]
I live in Florida Oranges. I have countless orchids of your comrades at my mercy. I'll start juicing them.

Do it Oranges. Make an exception.

**Review by francinum — COMMENTED** [review]
- The AI Upload should not be in maintenance, put it back next to engineering or something. The original separation of modules and upload was a small bit of additional difficulty.
- Add a space-gap between the large atmos tanks and the maint hallway.

**Comment by MMMiracles** [comment]
- Maintenance is barebones as is because I don't want to do anything with it yet until I finish the departments. It will have side sections and what-not once I'm done with everything else.

- Not every map has to have the exact same layout with exact same methodology for dealing with a situation. You want to vent the supply? Break the gas miners to kill the flow and deal with the mess afterwards.

**Comment by GunHog** [comment]
Is there an Aux Base?

**Comment by francinum** [comment]
Speaking of different methodology, I see you aren't planning to distribute power through the connecting arms of the singulo containment?

**Comment by Anonmare** [comment]
It looks like you've got the SMES' input and outputs back to front on the map image. The side with the power terminal is the input (the part that takes in and stores power) whilst the part leading out the sides (the red wire) is the output.

**Comment by MMMiracles** [comment]
@francinum that is a really cool idea and I'm stealing it now thank you

**Comment by francinum** [comment]
@MMMiracles if you look closely it's a donut feature.

**Comment by MMMiracles** [comment]
thank you i had to get my bifocals but i can see it now

**Comment by Anonmare** [comment]
I think the AI satellite core entrance foyer might be a bit too big.  If you move the consoles next to the cyborg charger and the rack next to the table, you can squish that room a bit and stretch a wall down the middle of the foyer and leave a turretless access way to reach t-comms

**Comment by MMMiracles** [comment]
Updated map image with local progress.

@Anonmare I plan on reworking the AI sat since I'm not a fan of it myself.
@GunHog I'm putting it on the depatures wing since it'll be a nice medium distance between cargo/science and give a reason to walk up that part other than when the shuttle is called.

**Comment by SpinnerMaster** [comment]
If an admin wanted to fly a deathsquad shuttle to this station and the emergency escape shuttle is docked, where would the deathsquad shuttle dock?

**Comment by subject217** [comment]
any chance we can get an AI sat that isn't modeled after the worst fucking AI sat (meta) with tcomms only accessible by the perma-bolted antechamber

**Comment by MMMiracles** [comment]
@subject217 I can do comms as a separate satellite so trying to access it doesn't raise 2 million red flags for an AI.

**Comment by subject217** [comment]
a proper TCOMMSAT is preferable. It could also just be re-mapped slightly so tcomms is entered by the maintenance room.

**Comment by Bawhoppen** [comment]
If you wanted to be really fun, you could always readd the original tcomms sat out in space.

**Comment by anconfuzedrock** [comment]
Literally gonna write a formal essay on why this should be able to have a singulo

**Comment by Iamgoofball** [comment]
@optimumtact is it acceptable if it has supermstter alongside singulo/tesla as an optional additional engine

**Comment by MMMiracles** [comment]
Updated with a new map image. Progress is gonna slow down starting next week since I'll be busy, but I hope to get the essential shit done by the end of the weekend.

**Comment by plapatin** [comment]
*scream

**Comment by MMMiracles** [comment]
because you should fear the greyshirt lurking the tunnels

**Comment by Cyberboss** [comment]
Let me just state that I have no intention of merging this because I'm trying to finalize the prototype for the new out-of-repo maploading system that will eventually be used for all the current station maps save Meta and Runtime.

This isn't a dismissal of the PR by any means though, feel free to keep getting it test merged.

**Comment by optimumtact** [comment]
I think you're confused, because you meant to say box and runtimestation naturally.

**Comment by francinum** [comment]
Directional windows, and holy shit that AI core is weak as hell.

**Comment by nicbn** [comment]
>directional windows

why

**Comment by Cavoglave** [comment]
For the love of God.
move upload to the AI sat, put telecomms where the upload was.

**Comment by MMMiracles** [comment]
Having the upload on the AI sat essentially means you're never going to see a law change that isn't a head doing it or someone stealing an unload board.

**Comment by DapperMola** [comment]
> haha fear greytiders
is not a valid reason to make virology able to be broken into effortlessly, come on man. why even bother having a secure airlock if you're gonna make a way in thats protected by a single reinforced window?
security aside, why would any room have a window into maint? the point of maint is hidden maintenance tunnels that are tucked away, not some facet of the station being put on display.

**Comment by MMMiracles** [comment]
the point of maintenance tunnels is whatever the FUCK i want them to be as long as they add an interesting  dynamic on the map. the original map had similar windows and i'm curious to see how it plays out.

**Comment by DapperMola** [comment]
nevermind, i really like the silly dinner date behind viro, im sold
-the recycler doesn't have a belt and chute taking recycled materials back to cargo
-i don't think the gulag shuttle dock has a prisoner item retrieval-whatever
-i actually really like the odd number of shield generators in the teleporter, leaves room for more interesting barriers
-also a big fan of how chem is set up

**Comment by nicbn** [comment]
No air alarms at engineering and CE office

**Comment by nicbn** [comment]
also scrubberless and venterless hallway

**Comment by DapperMola** [comment]
do you plan on having cameras around the inside of the donut?

**Comment by MMMiracles** [comment]
Hallways in general do need some work as they're fairly barebones currently, O2/firefighting lockers are all scattered throughout each department's maintenance.  I will probably place some motion cameras around the engine containment for extra security, though.

**Comment by nicbn** [comment]
Also directional windows. Replace them with full tile.

**Comment by MMMiracles** [comment]
directional windows aren't anywhere just an fyi

**Comment by nicbn** [comment]
At least use windows spawners then

**Comment by ShizCalev** [comment]
brig doors aren't cyclelinked.

**Comment by ShizCalev** [comment]
Also may want to double check the brig air supply, not sure if the warden's office is connected, and there doesn't seem to be a buffer between the main air supply and it.

**Comment by MMMiracles** [comment]
The brig doors are cyclelinked, so unless something changed recently they should work. All the brig piping is intact but you are right about a lack of buffer currently.

**Comment by subject217** [comment]
when a fairly large ship like the luxury shuttle docks with the station it destroys/blocks all ways to get in. it's particularly bad in the aforementioned case, as it's indestructible. to resolve this you should add a way to move from dorms to escape.

the atmos tanks are really way too easy to flood the station with. you should just give up on it and give them a layer of space.

**Comment by MMMiracles** [comment]
I'm not 'too' worried about shuttles breaking the dock since larger shuttles in general typically have clipping issues, maybe not as extreme though. Shouldn't the maintenance tunnel below escape be a good enough route, or are some shuttles just completely ruining that too?

The main issue with gas miners currently are that they're indestructible and have high-ish external pressure. I've already resolved the high pressure issue, but I'll have to add a destructible variant of gas miners in a separate PR to give them a better place on stations. As for their placement, I've gone and added a few extra maintenance airlocks in that area so it takes more work to vent atmos contents into the majority of maintenance/main halls.

**Comment by CosmicScientist** [comment]
Finally a reason to be tator and mess with atmos whilst not having atmos access.

**Comment by miniusAreas** [comment]
@MMMiracles A few tips / things you missed / things i saw, from a fellow mapper.
>HoS office is a single rwall from the locker, on meta/deta/box/pubby the HoS office and or locker is a rwall and space.
>Missing execution chamber
> @steamp0rt ***why can he have grenade launchers but not meeee***, jokes aside when i built my brig i though they were a great idea too, but more often than not chem gets ahold of them, or the crew outright dunks on a blob from emitter range. I got criticized heavily for it, so ill give you the same.
>Are those AI boards in the vault?
>Telecoms is quite far from engineering, and same with the trash driver being across the station from cargo.
>Turret control for minsat foyer is in the minsat foyer. This is a big no-no for several reasons, and the controls should be placed in a room right before it. Im unsure if several controlers will sync up, but this is a big no-no.
>use the atmosgas tiles in open_turf, tiles, engine or something along those lines. Two reasons, Atmos tile diffrences, and the miners will take a bit to build pressure without them. The miners are a cool idea otherwise.
>PIPES/WIRES UNDER WALLS. This is a big no no, and i can count more than 5 places around the outside of atmos alone where they go under a wall or even worse, rwall.
>Try using tile decals to alert colorcode the armory, it looks great.
Other than that, nice work dude!

**Comment by subject217** [comment]
@MMMiracles the luxury shuttle also covered the maint tunnel, so you'd have to break through multiple layers of walls to get to the shuttle at that point

**Comment by miniusAreas** [comment]
Also, if you need a hand with the map, Im more than wiling to pour my free time and ability to sit on mapping for hours for no price. Just let me know. Hell, I was concidering remaking Ceres but its not HoP line suicide

**Comment by miniusAreas** [comment]
Also, concider adding emergency one way access on the brig doors so prisoners may freely leave once their sentance is up. @MMMiracles Dont listen to the SM or the singulo, ***let the antimatter seep into your heart and the plasma-heated TEG system burn the station apart, BE DIFFRENT!***

**Comment by optimumtact** [comment]
I have no idea if this is finished or not

**Comment by MMMiracles** [comment]
Still working on it.

**Comment by MMMiracles** [comment]
This is more or less feature complete and ready for review.

**Comment by subject217** [comment]
there's no tool vendor anywhere in engineering

**Comment by MMMiracles** [comment]
angry noise

**Comment by subject217** [comment]
gonna say it once more here for the record but engineering is incredibly lackluster and probably not much fun at all on this map. boring engine, tiny workspace, obnoxious windows to replace without making everything super ugly.

**Comment by MMMiracles** [comment]
Flaps have windoors under them to prevent easy access. These can still be opened/closed.

I don't see extra vulnerability in departments as a bad thing unless it makes break ins too trivial. I personally don't think it'll be that apparent but I might be proven wrong.

**Comment by subject217** [comment]
break ins are already heavily trivial on metastation (my easy point of comparison) so it's probably going to be really awful on this map once people get used to it. assuming that happens.

**Comment by YakumoChen** [comment]
the AI APC is fine where it is, AIs shouldn't have their literal lifeline within easy firing range of an ion gun.

**Comment by subject217** [comment]
I said AI chamber, but what I actually meant was the AI upload. You can decon the wall and hack the APC from safety, block off or destroy the turrets, then turn equipment power back on.

**Comment by coiax** [comment]
@MMMiracles When I refactored poster code to be less shit, I ensured that there was always a clown HONK poster in the Theatre Backroom. Please rectify this absence.

**Comment by subject217** [comment]
In engineering, you've used the departmental protolathe instead of the techfab. The techfabs are designed to be standalone, the protolathes are designed to be in conjunction with an RD console and circuit imprinter. Please correct this.

**Comment by subject217** [comment]
With the transit tubes between the AI and tcomm sats and the station, you should use at least a couple of the sections that allow people to pass over them, if not for the whole thing. Also, it appears that the Tcomms lounge APC is not set up properly and is not giving any power to its systems. It also appears that the transit tube pod is not set up inside the transit tube itself for the tcomms sat, it's out of the tube.

**Comment by ShizCalev** [comment]
Looking at the OP image, the number of atmos vents and scrubbers seem to be EXTREMELY low.

For example, the entire primary hallway only has 4 vents, and 4 scrubbers. Counting an average of ~50 tiles distance between every next vent & scrubber. 

For comparison, Delta has another vent every ~14 tiles, box every ~17, meta every ~19, ect.

**Comment by ShizCalev** [comment]
also TINY FANS
image

**Comment by subject217** [comment]
TINY FANS MAPPED INTO A STATION OH LORD HOW DID I MISS THAT

**Comment by coiax** [comment]
Tiny fans were a mistake

**Comment by MMMiracles** [comment]
there God damn tiny FANS UNDER THE MASS DRIVERS ON EVERY MAP I JUST NEEDED THOSE IN THAT SPOT

**Comment by Tupinambis** [comment]
This looks fantastic, and while some people are nitpicking, we really do need more map variety, and a unique map design like this would work wonders for spicing things up. There are some issues to be addressed, but it should be mostly minor things or things that can be fixed after proper play testing on the live servers. My own suggestion is that all the windows just be fulltile instead of a grill surrounded by windows. That is the standard for all current maps, is easier to work with, and I believe (don't quote me on this) uses less memory.

**Comment by subject217** [comment]
It has been play tested live for like 3 weeks, dude. Do you know what a testmerge is?

**Comment by MMMiracles** [comment]
It's been testmerged for 3 weeks but only ran 4 rounds total, since it needs config changing to be put into rotation.

**Comment by subject217** [comment]
A bunch of admins forced it, I played a lot of rounds on it when you weren't present, and I can't imagine that I was present for all of those either.

**Comment by Tupinambis** [comment]
I wasn't aware it was already testmerged (I usually play on a tg downstream) but the point ultimately still stands. With so few maps to compare it to there aren't really standards, with maybe the exception of box and meta feeling similar. This map is very different from others in rotation. Because of that you can't really make assumptions or judgements without seeing the map in action with players that are used to it, especially when it comes to balance related stuff.

**Comment by Cyberboss** [comment]
No time to work on the new map system right now so let me know when the issues are addressed

**Comment by Cyprex** [comment]
Atmospherics simulation is broken in the gas tanks in atmos. Specifically, the turf with the gas miners starts with ~1500 kpa of gases, while the surrounding turfs in the 3x3 tank are at 0 kpa. No gas exchange is taking place. Deleting a tile in the tank and replacing it appears to fix the problem, and gases seem to propagate normally.

**Comment by Cyprex** [comment]
I like the gas miners in the atmospherics tanks, but consider putting some more gas into the tanks at roundstart, at least in the air tank.

**Comment by MMMiracles** [comment]
@Cyberboss There aren't any outstanding issues and the map has been in active rotation via testmerge for over a week now.

**Comment by Cyberboss** [comment]
Fix travis

**Comment by MMMiracles** [comment]
@Cyberboss we'll get there eventually

**Comment by MMMiracles** [comment]
image

**Comment by kingoftheautism** [comment]
any day now

**Comment by coiax** [comment]
You're missing a `/obj/effect/spawner/xmastree` somewhere, either (or both) in the Chapel or Bar.

**Comment by MMMiracles** [comment]
I fixed that in the tree spawn commit

**Comment by MMMiracles** [comment]
please @coiax come back its been 3 years

**Comment by davethwave** [comment]
The bartender area doesn't have a chemaster unlike the rest of the maps.

**Pull request merged**
