### PR TITLE
Servants of Ratvar know the overall cult status at all times

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Added the clockcult "Global Records" alert, which clock cultists can mouse over to check a variety of information on the clockcult's status, including living servants, number of caches, CV, tinkerer's daemons, if there's an unconverted AI, what clockwork generals can be invoked, and what scripture is unlocked.
/:cl:

Added a tooltip style for clockcult, for fancy clockcult tooltips.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Make this for regular cult too pretty please?

**Comment by WJohn** [comment]
Why does clockcult get this but not other antags? Shouldn't headrevs or nuke ops know the status of their teams, too?

**Comment by ChangelingRain** [comment]
Clockcult has a shitton of stuff it needs to keep track of and is frankly kind of a pain to play if the information is hard to access; no other antag actually NEEDS to keep track of this much stuff.

**Comment by AdamElTablawy** [comment]
It'd be nice for gangleads/revheads to know location and number of anyone on their team on demand, tbh. Rev is barely team based as is-maybe we'd see revheads leading swarms of revs for once instead of flashmaster 9000.

**Comment by PKPenguin321** [comment]
this blatant clock cult favoritism is killing me honestly

>Like no seriously all cult would have in something like this is cultist count, sac target, and location of nar-sie rune, they don't have much to keep track of at all.

i would fucking love to have that kind of thing tracked are you kidding me?
no more "did we sac X yet? are you sure we sacced X? i dont wanna summon nar nar if i don't know we sacced X," no more "do we have enough to summon narsie yet? guys get over here headcount cmon guys," "guys, where's the rune? where's the rune guys oh god somebody make a teleporter send help"

**Comment by optimumtact** [comment]
Favouritism compared to what?

**Comment by PKPenguin321** [comment]
regular cult

**Comment by optimumtact** [comment]
It's not favouritism, it just has a developer who actually cares about the gamemode. It's not like we're intentionally not adding these features to regular cult, it's just nobody actually wants to do it.

That's tough tits for the cultists who enjoy regular cult.

**Comment by PKPenguin321** [comment]
i guess but that wont stop me from bitching about it :pray:

**Comment by ChangelingRain** [comment]
It would be useful, yeah, but I'm not likely to do it myself because I'm busy doing it to clock cult.

**Comment by ChangelingRain** [comment]
That and it's gamemode code, cult's stuff is actively tied to having the mode; they don't and can't have a sac target/rune without the mode, clock cult's stuff is needed even if it's not the actual cult mode.

**Pull request merged**
