### PR TITLE
Tramstation Enlargement Project

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request

This is a big one, a few weeks of on-off work in the making. Big points:

- The tram tunnel is now 7 tiles wider between each segment
- The EVA airlocks that connect between each segment have been given airlock cycles to help balance between the 3 main routes
- Medical has been completely reworked
- New sections of maintenance have been furnished to take advantage of the extra space
- The vault has been split up and relocated once again to keep confusing new players.
- The nuclear device along with the safe/silver crate has been moved below the bridge, accessed through the old power hatch (now vault access). Security and the Bridge wing now share the same power access hatch to compensate.
- The 3x3 silo room under Cargo has been turned into a mini bank vault (Bank of Cargo) with QM access. Let the spice flow.
- A few maintenance sections have been given ways to traverse between levels without having to use the public stair/ladders.
- Each section, both top and bottom, should have a way through maintenance to get between both. Some are official pathways, others are abandoned shafts that can be randomly blocked on a per-round basis.
- Various details added between external station details and 

## Why It's Good For The Game

The main things I've heard negatively about the map were that the tram didn't feel as impactful to use vs just running the gauntlet and that medical's layout wasn't as good as it could be. The slight expansion not only makes the alternative routes longer/varying levels of dangerous, it also gives me more room to redesign Medical to be something more interesting. It also gave me room to be more creative with the maintenance layout with more alternative routes and nooks/crannies.

## Changelog

:cl: MMMiracles
add: Tramstation has gotten an extension, both in size and layout.
add: Tramstation's medical has been completely overhauled to a new layout,  hopefully a better one!
add: New bits of maintenance and maintenance path have been added on both the top and bottom levels of the map.
add: Cargo now resides over a small bank vault that stores both the station's materials and wealth.
/:cl:

[Upper Portion](https://user-images.githubusercontent.com/9276171/146660225-bc7dccd8-0984-41fe-bb72-5fb999a3538a.png)

[Lower Portion](https://user-images.githubusercontent.com/9276171/146660048-b449c757-46b6-4bde-a1ee-4f62292f7ca5.png)

i asked who i had to pay to make this pr and fikou said it was him so here's proof. i assume this will be enough....
image

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
you put the same picture for upper and lower portions

**Comment by MMMiracles** [comment]
check again

**Comment by CRITAWAKETS** [comment]
thanks i can finally now enjoy the great Tramstation Prime in its entirety

**Comment by CRITAWAKETS** [comment]
i dont think the longer tram segments will really discourage using _alternative methods_ especially considering the catwalks on the sides.

**Comment by Zytolg** [comment]
This man really contributed to Fikous onlyfans to get this through the freeze 😞

**Comment by BlueMemesauce** [comment]
Why does it have to be so hard to get anywhere?

Now the tram takes even longer to get to where you need to get, while alternative routes are made worse. The space path adjacent to the tram now has timed airlocks which take forever to get through. It will be much harder to get through without using a space suit.

At least the new maints finally bring ways to get between departments without using the tram.
However, many of them are either in space or have a chance to be blocked off.

This is why many players dislike tramstation. Its just a gimmick that makes the gameplay worse.

**Comment by MMMiracles** [comment]
filtered already and we're only at the bikeshed stage

**Comment by necromanceranne** [comment]
I find it neat that there is an ore vault and a normal vault, and while it is good to keep the ore/money related stuff in cargo and I think that's a very impressive addition, I do find it the nuke vault is comically easy to swoose right into so long as you have a space suit and a bit of time. That shit desperately needs internal + external motion sensors on both levels. It is so detached from the rest of the station that the core theft objective would be a joke.

Also, I'm extremely worried that spacing tram is easier than ever with so many destructible walls attached to maintenance. Tram already has a major issue with vacuums, and all of that southern section on the upper level looks ripe for abuse with comical ease.

**Comment by MMMiracles** [comment]
I don't have much of a problem with reworking the vault now that it's meant mostly for the nuke core, I can look into some different layouts.

Anything maintenance related that isn't solid wall is meant to be 'abandoned' and not always accessible. I'm not too worried about something like the abandoned dorms maintenance getting breached occasionally.

**Comment by Farquaar** [comment]
Can't wait to put prisoners in perma by tossing them over the rail

**Review by MrMelbert — COMMENTED** [review]
<details>

<summary> There are no lights in genetics. Also no air alarm. </summary>

image

</details>

(resolved)

**Review by MrMelbert — COMMENTED** [review]
image

Also a handful of double stacked pipe / cables around, unsure if they're from this project or not

**Review by MrMelbert — COMMENTED** [review]
<details>

<summary> No APC in the central medbay hallway-ish area. No air alarm in medbay's lobby. No intercoms in the treatment center. </summary>

image


image

This area doesn't cover the walls correctly

image

Med sec post isn't connected to powernet or atmos net roundstart

</details>

(resolved)

**Review by MrMelbert — COMMENTED** [review]
<details>

<summary> Neither of these desks have windoors </summary>

image

</details>

(resolved)

**Review by MrMelbert — COMMENTED** [review]
<details>

<summary> Space tile in engineering secure storage </summary>

image

</details>

(resolved)

**Review by MrMelbert — COMMENTED** [review]
<details>

<summary> Wall under shutters + annoying decal layering </summary>

image

image

</details>

(resolved)

**Comment by MrMelbert** [comment]
Issue is older than your PR, but
image
The lower half of the AI sat is unconnected from power and you can probably quick fix it here.

**Comment by Fryzzie** [comment]
Couldnt you drop right into the new cargo vault/bank machine from cargo lobby now? It looks the ore silo is right underneath cargos front door

**Comment by MMMiracles** [comment]
If you want to blow open/deconstruct a floor in a public area, drop in, and still have to deal with the fact you're in a reinforced room with a locked vault door sure.

**Comment by Farquaar** [comment]
Melbert being a hero with the feedback here

**Review by MrMelbert — COMMENTED** [review]
Noticed two other wonky areas. 

<details>

<summary>Telecomms's areas and this bit of maintenance between atmos and maintenance aren't mapped correctly (either no area or incorrect areas)</summary>

image

image

</details>

Remember that maintenance areas should cover the walls of departments ~~for reasons or another~~

**Review by MrMelbert — COMMENTED** [review]
image

Oh yeah, and cryo's freezer isn't hooked up to waste, and won't work.

**Comment by peptron1** [comment]
Are there any sinks outside if virology?

**Review by MrMelbert — APPROVED** [review]
My reviews have been addressed, i'll leave it to the @tgstation/maptainers to do any final review

**Comment by MMMiracles** [comment]
i want my dollar back fikou

**Review by Maurukas — APPROVED** [review]
MrMelbert has done all the hard work here. Looks good.

**Pull request merged**
