### PR TITLE
Disables Draconic for lizard crewmates

### PR DESCRIPTION
**Pull request by ghost**
:cl: That Really Good Soda Flavor
rscdel: Draconic is now only the language of the Ash Walkers.
/:cl:

I think it's silly to treat roundstart species like this.

I wonder what other people think?:

### CODE REVIEW

**Comment by XDTM** [comment]
Is the month over?

**Comment by Really-Good-Soda-Flavor** [comment]
3 weeks, this feature is stupid.

**Comment by bgobandit** [comment]
,o the human is ssstupid

**Comment by Armhulen** [comment]
,o stinky idiot humans think they can remove our native tongue

**Comment by XDTM** [comment]
,o i haven't even played with thisss but i still like the idea

**Comment by Really-Good-Soda-Flavor** [comment]
> ,o i haven't even played with lizard language but i still like the idea

Go figure, looking at your "shells" idea.

**Comment by lzimann** [comment]
@KorPhaeron

**Comment by bgobandit** [comment]
>lizmann the lziard voted thumbs up on this

**Comment by XDTM** [comment]
shouldn't we run a poll or something

**Comment by InsaneHyena** [comment]
>All the usual suspects voting no

**Comment by XDTM** [comment]
>All the usual suspects voting yes

**Comment by Iamgoofball** [comment]
merge my PR instead

**Comment by Iamgoofball** [comment]
#27642

**Comment by KorPhaeron** [comment]
I'd rather remove the lizard language than add a human one

But in the little time I was on during the last month I didn't see draconic used for anything other than trash talk on the radio so I don't think it really harms anything either

I'm ready for a disproportionate amount of arguing over it though!

**Comment by lzimann** [comment]
Just make a decision and stick to it(or eventually someone will make one for you, h-haha)

**Comment by Iamgoofball** [comment]
@KorPhaeron merging my PR will be funnier than removing it tbh

**Comment by KorPhaeron** [comment]
I mean I made a decision like a month ago and the game didn't catch fire and lizard metagangs didn't murder everyone but its such a minor feature that I'm not going to fight forever if it will be periodic drama

**Comment by Really-Good-Soda-Flavor** [comment]
It didn't cause drama before it existed, so it shouldn't cause drama when it no longer exists.

**Comment by XDTM** [comment]
It doesn't need to cause drama while existing either but for some reason there's a crusade against it

**Comment by KorPhaeron** [comment]
Also you dont really have any rationale for the change in the OP

**Comment by FantasticFwoosh** [comment]
Ashwalkers can still speak galactic which is a stupid concept in the first place only substantiated by shoehorned lore about deus ex missionaries or VCR tapes or something and never really actually got a explanation or additional depth.

Atleast remove galactic from ashwalkers & have lizards understand but not speak ashwalker i guess as a compromise.

**Comment by Chronitonity** [comment]
Just give the Curator a way to print out books able to teach Draconic or something.

**Comment by demonfiren** [comment]
@Chronitonity m-muh snowflakes

**Comment by Bawhoppen** [comment]
I'll never understand why people are unironically hateful in a videogame

**Pull request closed without merging**
