### PR TITLE
Adds Early Launch Console to Backup Emergency Shuttle

### PR DESCRIPTION
**Pull request by BeeSting12**
Alright, so I know this is feature freeze, but think of this as fixing an oversight. The backup emergency shuttle, ya know, the one that launches if the regular one's fucked up, doesn't have an early launch console, which all shuttles should have. I added it just north of the desk that's on the shuttle, seemed like the best place.

:cl: BeeSting12
add: Adds emergency launch console to the backup emergency shuttle.
/:cl:
Why: This shuttle has been showing up a lot recently and it's missing the one thing that pretty much all the emergency shuttles have. Just because certain shuttles are broken doesn't mean that the players should be punished by not being able to launch early, if needed.

### CODE REVIEW

**Comment by BeeSting12** [comment]
I'm going to bed, I'll make any edits or answer any questions in the morning.

**Comment by kevinz000** [comment]
yeah I think there's a huge issue if this is being spawned unless it's still the deltastation buggy stuff.

**Comment by coiax** [comment]
For reference, anytime an emergency shuttle docking port is destroyed, the backup shuttle is set as the new "emergency shuttle". However, NORMALLY, there'll be a new emergency shuttle docking port created, which will override the backup one. I don't know why this is being used.

**Comment by BeeSting12** [comment]
Yeah I have no idea how to fix what's causing this but I can at least make it less hellish for the crew.

**Pull request merged**
