### PR TITLE
Monkeys are now more likely to become Gorillas

### PR DESCRIPTION
**Pull request by Robustin**
So I found out today we have gorillas in our code, made from irradiated monkeys, nice!

**I checked the percentage - at max radiation a monkey had a 10% chance to become a gorilla every tick.**

Wow

Then I saw it got nerfed. **Currently at max radiation a monkey has a .01% chance to become a gorilla. Meaning it would take about 30 minutes of max rads for a monkey to transform.** 

Wow

Now I've used advanced mathematics to decide that the decimal place between those two is closer to ideal. **Now its a .1% chance meaning it will take about 3 minutes of max rads.** Max rads are not easy to maintain since it decays fairly quickly and "caps" at 100 and it will be dead before transforming (on average) unless you're also healing them.

Leaving them in their current state - they might as well not exist.

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Ratvar** [comment]
/me puts biobag of monkeys from biogenerator on floor
/me puts down uranium floors
/me waits
/me hmmmms

**Comment by MoreRobustThanYou** [comment]
there is a reason i made them rare. 3 words:

mass produced gorillas

**Comment by deathride58** [comment]
Right now, if you set off 100 monkey cubes from botany/xenobio, and toss one single mutagen+antitox smoke grenade, you'll only get 5 gorillas max, 10 if you're lucky. Testing this PR locally, doing the same exact thing results in all monkeys from those cubes becoming gorillas.

Mass-produced gorillas are real, and you really shouldn't buff them.

**Comment by Robustin** [comment]
The amount of work and setup required to do that pales into comparison to what xenobio can do. If someone wants to exercise creativity to find a way to do that, good for them, if by some miracle it becomes a regular occurrence then we can tweak it more - but your current coefficient means we will see gorillas as often as we see pulse rifles from arcades or pulse rifles from the hidden fake space tile.

**Comment by deathride58** [comment]
All you really need to do to amass 100 monkey cubes is to either grow a bunch of grass in botany, farm grey slimes in xenobiology, or duplicate monkeys via upgraded monkey recyclers. Both botany and xenobio have access to mutagen and what's needed to produce smoke, either due to their job requirements or due to their job's abilities. There is very little actual work required to amass 100+ monkey cubes, and there's no real setup required for it, you just have to do your job for more than 5 minutes. Buffing gorilla mutation rates would completely remove the need for antitoxin during gorilla mass production, making reliably mass-produced botany gorillas even more accessible. Every 1 in 20 monkeys turning into gorillas while on life support in mutagen smoke is a pretty big number when you consider how easy it is to mass-produce monkey cubes.

The sole reason gorillas are so rare via radiation mutation is to make gorilla mass-production require more work.

**Comment by MoreRobustThanYou** [comment]
making shittons of biomass in botany is easy:

step 1. splice watermelon's massive nutriment into grass
step 2. max out said GM grass to potency 100
step 3. spam robust harvest and shit onto it
step 4. farm biomass

**Comment by Supermichael777** [comment]
GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA GORILLA

**Comment by Robustin** [comment]
I simply don't see how this is any different than other mass-animal spamming. It's still very rare because most antags don't want to sit around farming slimes or plants. This isn't unique to Gorillas and Gorillas take many more steps.

It doesn't make any sense to balance around the most OP scenario when nothing else is. It's those unique moments where someone does something crazy like make a gorilla farm that makes this game special. 

If I see it happen more than once a week I'll gladly come back and revert this. Until then the current formula means they're functionally removed from the game.

**Comment by jughu** [comment]
Remember when oldman buffed zombies now people can stop 1 zombie alone barely.
Now he wants to buff gorillas producing.

**Comment by Bawhoppen** [comment]
Robustin is and has been completely out of touch with the spirit of the game for a long time now. If you need an example, just look at that abomination of gang he made.

**Comment by Bawhoppen** [comment]
I feel kind of bad after posting that but Robustin you really don't usually think about your features/changes very much (atleast in the right way)

**Comment by AdamElTablawy** [comment]
APE ESCAPE

**Comment by KorPhaeron** [comment]
I have not seen a single gorilla since I started playing again

**Comment by PopNotes** [comment]
ook

**Pull request merged**
