### PR TITLE
DNA Vault is a little more obtainable, new powers

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
tweak: The DNA Vault has 2 new powers
tweak: The DNA Vault requires super capacitors instead of quadratic
tweak: Cargo's Vault Pack now includes DNA probes
/:cl:

100 rounds since this vault was added and I've never seen it attempted. Since the DNA vault is only the first step (you still need the DNA), this makes it easier to start the project (and its a lot easier to motivate people to participate when they've got a cool machine to gawk at rather than just the empty promises of someone on the radio).

### CODE REVIEW

**Comment by Kraseo** [comment]
you don't get no bursday cake if you don't sing

**Comment by GunHog** [comment]
Let us make this thing actually worth something! :+1:

**Comment by RemieRichards** [comment]
How about a power that modifies ```next_move_modifier```, changing it to 0.5 would make click cooldowns for that mob only be 50%.

**Comment by Robustin** [comment]
Would that simply be a S.next_move_modifier = 0.5?

**Comment by RemieRichards** [comment]
It's a mob var, not a species one.

**Comment by Robustin** [comment]
so uh, H.next_move_modifier?

**Comment by RemieRichards** [comment]
ya.

**Comment by Robustin** [comment]
I'll add it for funsies then, I think that would be the most OP in the hands of an antag but those are the crazy edge cases that bring me back to this game.

**Comment by Kraseo** [comment]
>Let us make this thing actually worth something

make people actually read/bother to purchase the things then talk to me to prove me wrong

**Comment by ExcessiveUseOfCobblestone** [comment]
could you be a bro and atomize the powers [feature] vs the balance change?

**Comment by Robustin** [comment]
If its sufficiently controversial, but given its "endgame" nature and RNG power distribution, I'd perhaps like to see one built before judging if the powers will even show up enough during rounds to justify balance treatment.

**Comment by kevinz000** [comment]
personally the speedmod thing is worrying it's just like old viro stims the only thing that would redeem it is it being harder to get, but then again, it's completely randomized.

**Comment by Robustin** [comment]
I think the most important part is that this is a large enough project that command/security can dictate how it goes down. This isn't some little meme machine you quietly build in the Test Lab and jump out with god_mode active. 

The very nature of inter-dept. cooperation means that this item will tend to buff loyal crew and good boys. I will gladly change it if the players prove me wrong but that would require people actually build this thing first.

**Pull request merged**
