### PR TITLE
Add TGM map format support to the maploader

### PR DESCRIPTION
**Pull request by Menshin**
Performances for Byond format should be unaffected, since it's only adding a comparison in that case.
Some light code cleaning too.

### CODE REVIEW

**Comment by xxalpha** [comment]
Does this read that billion line map layout?

**Comment by Menshin** [comment]
> Does this read that billion line map layout?

I've succesfully loaded _Boxstation_ (in TGM) as an extra 8 z_level, so i guess it handles massive map files pretty well.

**Comment by RemieRichards** [comment]
:+1: Excellent.

**Comment by xxalpha** [comment]
Box station is not yet converted to the billion line map layout format.

**Comment by Menshin** [comment]
Then i've no idea of what you're speaking of...
The maploader probably doesn't do what you're asking then.

**Comment by xxalpha** [comment]
See https://github.com/tgstation/-tg-station/blob/master/_maps/map_files/MiniStation/MiniStation.dmm
And https://gist.github.com/anonymous/3a3607baa60184ffd710

**Comment by Menshin** [comment]
The maploader won't handle this, the _line breaks_ characters not being skipped.
If this ever come to be the TGM standard map layout (which, afaik, it's not presently) it should be easy to make the maploader parse it.

**Comment by xxalpha** [comment]
It already has, the map loader has to be able to parse that.

**Comment by RemieRichards** [comment]
I don't think Billion Line TGM should become the defacto considering it crashes Asteroid Station with a byond bug.

**Comment by xxalpha** [comment]
It crashes Asteroid's z5.dmm

**Comment by MrStonedOne** [comment]
honestly, its just asteroid station, and lummox said he's not ignoring the byond bug, but just busy, so we will find out WHY soon enough.

**Comment by MrStonedOne** [comment]
I think we should favor development ease over a single map that's kinda hated.

**Comment by MrStonedOne** [comment]
Also, I don't like the idea of special treating tgm maps by looking for the comment.

We should make this parser match byond's parsing as closely as possible, so that it can handle any map format that byond accepts, including any made by other code bases.

**Comment by Menshin** [comment]
Well, these elements taken into account, it seems this wasn't the right approach...

**Pull request closed without merging**
