### PR TITLE
makes the microscope wrenchable

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

title, you should be able to move it around
I'm ill, very Ill, so forgive me if this is terrible

## Why It's Good For The Game

sometimes, you want to have your own quiet corner to make an army of roaches, and its neat

## Changelog

:cl:
expansion: Makes the microscope movable via wrenching it. 
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
I'm not quite sure, I've not really touched default acts much, but would this make you unable to re-wrench the microscope into place?

**Comment by thestubborn** [comment]
> 
> 
> I'm not quite sure, I've not really touched default acts much, but would this make you unable to re-wrench the microscope into place?

it shouldnt

**Comment by newfren** [comment]
you can already drag a microscope around though?

**Comment by thestubborn** [comment]
> 
> 
> you can already drag a microscope around though?

you...can?

**Comment by thestubborn** [comment]
huh, you can, well this makes this pr kinda useless

unless maintainers want this to be able to...not be moved

**Comment by Mothblocks** [comment]
its fine

**Pull request closed without merging**
