### PR TITLE
Changes some food type. (Soylent green tastes less funny, clowns everywhere approve.)

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

This PR changes some food types:

- Soylent greens are no longer GROSS.
-  Roffle waffles are no longer TOXIC.

- Space freezies, ice-cream sandwiches, jelly sandwiches and honey buns have SUGAR.
- Honey nut bars have GRAIN instead of FRUIT.
- Cheesy Fries, margherita pizzas and omelette du fromages have DAIRY.
- Butterdogs have GRAIN and DAIRY.
- Eggs benedicts have GRAIN.
- Pigs in a blanket have MEAT and DAIRY.
- Beary pies have FRUIT and MEAT.
- Hot and cold chilies have MEAT.
- Dank pizzas no longer have FRUIT.
- Aesir salads have FRUIT.
- Milo soups have VEGETABLES.

## Why It's Good For The Game

Soylent green and roffle waffles are changed to be less repugnant to make people actually want to eat these fun dishes.

Soylent green is resource intensive to make and is also highly processed so i think it makes sense it is at least palatable.

The other food type changes are for consistency and realism.

## Changelog
:cl:
tweak: Soylent green and roffle waffles are now more palatable.
tweak: Several dishes have had their food types adjusted for realism.
fix: Fixes a typo.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Could you make all clowns like bananas in a future PR? The few clown moth mains that exist would thank you for doing that.

**Comment by Farquaar** [comment]
Why do chillies get the MEAT tag?

**Comment by Ty-the-Smonk** [comment]
> Why do chillies get the MEAT tag?

Chili is a type of meat dish

**Comment by Farquaar** [comment]
Aah, I see. I thought you were referring to the chili plant, as opposed to the dish.

**Comment by Iatots** [comment]
dank pizza has meat taste?

**Pull request merged**
