### PR TITLE
Adds Extended Drill Hair

### PR DESCRIPTION
**Pull request by silicons**
@Okand37 

[why]: A neat new hairstyle for us to play with!

oh yeah sprites aren't mine

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Oh no

**Comment by Okand37** [comment]
As the picture of what it looks like ingame was not included, here is a reference picture.

**Comment by optimumtact** [comment]
[why]: (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

**Comment by kevinz000** [comment]
done

**Comment by MoreRobustThanYou** [comment]
it;s ugly af

**Comment by kevinz000** [comment]
your opinion will be considered morty.

**Comment by GuyonBroadway** [comment]
It just looks like you took the longhaired sprite for the back and just added a few extra pixels to the front. Its not even all that distinctive. 

That being said, kevinz being kevinz part of his fetish probably involves a very particular style of hair at a rather specific lenght.

**Comment by ExcessiveUseOfCobblestone** [comment]
Can you replace the judge wig with this

**Comment by kevinz000** [comment]
@GuyonBroadway please make a better argument than "my fetish" which isn't even a thing here.

**Comment by GuyonBroadway** [comment]
Ok I shall restate and elaborate, it just looks like a few pixels glued to the bottom of the existing hairstyle, making it look like the regular drill hair but just slightly odd like and imperfect reflection. The back also does not match up with the front and sides, looking like a completly different hairstyle.

**Comment by GuyonBroadway** [comment]
Also as a brit my one goal in life is to mock and ridicule, which I will do so without provocation or reason. 

And i shall note that the hair appears to have dimples on the top bits that would facilitate a certain controversial addition that you are infamous for being involved with.

**Comment by Xhuis** [comment]
It looks very unnatural and reminds me more of a wig or hat than actual hair.

**Comment by AnonymousNow** [comment]
It's so stupid.

I want it.

**Comment by Spaceinaba** [comment]
it needs to look more drill-y imo

**Comment by Qbopper** [comment]
with white hair it kinda looks like that stereotypical judge wig thing

**Comment by Iamgoofball** [comment]
this isnt even proper annie may drill hair

**Comment by Armhulen** [comment]
i judge this pr

GUILTY

**Comment by Spaceinaba** [comment]
what if you make the hair a mining drill

**Comment by praisenarsie** [comment]
replace this with the already existing judge hair

**Comment by Qustinnus** [comment]
ugly. take it somewhere else.

**Comment by KorPhaeron** [comment]
@ChangelingRain I don't know if you care about this but you've cared more in the past about aesthetics than most maintainers so it is all yours if you want it

**Comment by ChangelingRain** [comment]
It doesn't look very drill-like tbh
what's it look like in actual colors

**Comment by Okand37** [comment]
The individual I had asked to make the hairstyle had decided to use the regular drill hair as the base, so it isn't straying a large amount from what the regular drill hair ingame looks like, though I agree it does look rather unappealing in greyscale. Unfortunately the spriter did not give me a picture of what it looked like in colour, but as an example here is a picture of the regular ingame drill hair in colour versus greyscale. -If anyone would like to make a better extended drill hair set they are welcome to, however!

**Comment by DoctoreMad** [comment]
Why is this assigned to TWO maintainers
This is actual bikeshedding.

**Comment by Xhuis** [comment]
Nah, bikeshedding is the cat PRs!

**Comment by PKPenguin321** [comment]
Looks like a pharaoh hat. I will color it yellow and be a kang.

**Comment by Repukan** [comment]
Keep your fetish shit in citadel

**Comment by Xhuis** [comment]
You cannot *seriously* be calling a *hairstyle* fetish content. Actually, I'm changing my -1 to a +1 just because of that.

**Comment by Iamgoofball** [comment]
if you're going to add annie may hair go long

**Comment by Repukan** [comment]
Don't you have a gamemode to not finish @Xhuis, stop shitposting in prs and get to work

**Comment by Okand37** [comment]
@Iamgoofball Well, you do have the .dmi for FuryMcFlurry's annie may hairs. If you want to go long, that would be some good material!

**Comment by Iamgoofball** [comment]
@Okand37 dude that was years ago, idk if I even have that still
i'll look around though

**Comment by Okand37** [comment]
@Iamgoofball https://tgstation13.org/phpBB/viewtopic.php?f=11&t=8104&p=258145&hilit=bazaar#p258145 The .dmi is still linked, though I'm unsure if it is still downloadable.

**Comment by FuryMcFlurry** [comment]
image
GET ON MY LEVEL OF DRILLZZZ

**Comment by optimumtact** [comment]
Is this one of your japanese ANNIE MAYS?

**Comment by Okand37** [comment]
@FuryMcFlurry If I thought I could actually get those into the game you're darn right I would PR them. ;--;7

**Comment by PKPenguin321** [comment]
🤢

**Comment by Repukan** [comment]
Can you add All Might's hair too

**Comment by DoctoreMad** [comment]
@optimumtact What sort of comment do you have towards you rampant defense of bikeshedding? Why does a sprite PR need 2 reviewers? Why are you such a fruit?

**Comment by Bawhoppen** [comment]
I vote yes for anime hair. Variety is always good.

**Comment by FuryMcFlurry** [comment]
who want anime hair dmis, pm me on discord. also you need to split them up for the new hair sprites TG uses.

**Comment by ninjanomnom** [comment]
Holy shit I want those drills for my static

**Pull request merged**
