### PR TITLE
Clockcult silicons can now activate Clockwork Structures

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Clockcult silicons can now activate Clockwork Structures from a distance.
rscdel: Interdiction Lenses will not disable cameras if there are no living unconverted AIs.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
Thanks for helping Silicons be more part of the fold, rather than simply feeling like a tacked-on gimmick.

**Comment by coiax** [comment]
I have been a converted Ratvar silicon, and you do feel very... ineffectual.

**Comment by KingPhilipIII** [comment]
Like I said elsewhere, maybe engineering cyborgs should get a cyborg proselytizer. It's not outlandish is it?

**Comment by coiax** [comment]
There are apparently plans in the works giving converted silicons a limited set of scripture and/or tools. Giving all converted silicons a slab that generates components would be helpful.

**Pull request merged**
