### PR TITLE
Frogs can now be picked up. You can fit them in your pockets too! Or you can put them on your head if you want to.

### PR DESCRIPTION
**Pull request by kawoppi**
## About The Pull Request
Allows frogs to be picked up by ctrl+clicking them and dragging them onto your sprite. You can fit them in your pockets too!
frogpockets
You can also put them on your head like you can do with PAIs.
frogonhead2
frogonhead3

Frog on head sprites:
frogonhead1

## Why It's Good For The Game
Brings frogs more in line with other pets and mice (their fellow maint critters) especially. You can put one in your hand and offer somebody a frog. You can fit them in your pockets too! And you can put them on your head so that they can see far and wide.

## Changelog

:cl:
expansion: Frogs can now be picked up. You can fit them in your pockets too!
expansion: Frogs can now be put on your head.
imageadd: Added sprites for (rare) frogs placed on heads
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Is that frog in your pocket or are you just hoppy to see me?

**Comment by bruhlookatthisdood** [comment]
now make it able to be worn on your head and have a little hopping frog on you.

**Comment by Shadowflame909** [comment]
once i can put frogs on my ear and use them like a headset. My reference will be complete

**Comment by bruhlookatthisdood** [comment]
THEY ACTUALLY DID IT OH MY GOD!

**Comment by kawoppi** [comment]
> THEY ACTUALLY DID IT OH MY GOD!

thanks for suggesting it, it was a good idea! 
frog hat

**Comment by dragomagol** [comment]
FROG HAT

**Pull request merged**
