### PR TITLE
Removes DNA Aide

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
-Makes genetics irrelevant
-Obtainable very quickly
-Little downside outside of the randomness 
-Spreads to the whole crew so you have xray hulks running around (either validhunting or breaking into every room for no reason).

Other feeling bad for removing something and not leaving something new in its place I can't really think of a reason to keep it. People have been complaining loudly about this so here is the PR.

If I'm mistaken about the general mood then I guess the PR can be closed though.

Remade because it conflicted with Phils update and its less of a pain to just redo the PR than fix a merge conflict.

### CODE REVIEW

**Comment by hornygranny** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Dorsisdwarf** [comment]
horny/granny :+1:

**Comment by whodaloo** [comment]
:+1:

**Comment by daman997** [comment]
do it do it do it do it do it :+1:

**Comment by GunHog** [comment]
I wish you would have re-worked it to be a heal/SE fixing ability instead of just axing the whole thing.

**Comment by as334** [comment]
:+1:

**Comment by Anonus** [comment]
:+1:

**Comment by Robustin** [comment]
This PR hath the blessing of Oldman Robustin.

May you ever walk in the light my child.

**Comment by Razharas** [comment]
We are really desperate for making viro not useless and you remove one of the rare not completely useless things
This is horrible

**Comment by Durkel** [comment]
This has been a long time coming. Good fucking riddance. :+1:

**Comment by GunHog** [comment]
>We are really desperate for making viro not useless and you remove one of the rare not completely useless things
This is horrible

I am soon to write a solution to this. The idea I proposed in the previous PR, but the current author is too lazy to do himself. They will be in separate files, I guess, so it should not conflict with the merge. I just need to get an understanding of how Phil changed DNA code so I create a virus symptom that cleans the SE without touching the power or race blocks, and will purge radiation and heal cloneloss.

**Comment by KorPhaeron** [comment]
@GunHog 

In all honesty the thing you're proposing is an entirely different power, DNA AIdes is dead either way. I appreciate that someone is willing to make a replacement though

**Comment by PKPenguin321** [comment]
it would be cool if it ticked on genetic powers in your DNA but didn't manifest them, and kept you clean from genetic defects, instead of getting outright removed
but i guess it is pretty shit as it is and somebody could always readd a better version later so yeah :+1:

**Comment by optimumtact** [comment]
Viro was never a proper job anyway, it was tacked on and poorly thought out

**Comment by Kromgar** [comment]
JUST DO IT

**Comment by Kromgar** [comment]
@Razharas 

Viro's "really useful thing" invalidates Genetics entirely especially when Genetics has managed to actually do research and then they get the disease all the powers they got just get removed by DNA aide rewriting their fucking dna because the shitty fucking viro made it airborne.



Also can we get Genetics fixed by removing Goofball's shitty voicebox genetic defects? All the shit he added to genetics only made genetics more of a fucking chore to actually fucking do.


11 fucking blocks to test  with RNG gene editing. Considering you need to have the machine at 5 seconds to actually get near accuracte results its a fucking pain and a half.

**Comment by Giacom** [comment]
Don't know the state of the game now but I was meaning to remove this before I stopped playing.

See #4133

**Comment by Incomptinence** [comment]
I have dnaide a chance I supported it. I must admit it hasn't really served as the chaotic round ender I hoped it would be for virology.

**Comment by Razharas** [comment]
Well if its bad then ok, but please add something good to virology

**Comment by Chocobro** [comment]
@Giacom i'm sure removing something doesn't really break the rules of a feature freeze
just supa saiyan

**Comment by AnonymousNow** [comment]
Yeah, okay.

I hope that we can find more things for virology to do.

**Comment by GunHog** [comment]
I am working on a replacement symptom now, relax.

**Pull request merged**
