### PR TITLE
Assimilation 2.0: Not quite a big enough PR to be worthy of the 2.0 title but almost

### PR DESCRIPTION
**Pull request by Kierany9**
**(This PR is ready unless maintainers state otherwise)**

## About The Pull Request

This is a massive update to Assimilation, made after being generally disappointed with how dissimilar the original design concepts and the gamemode at launch were. While I've got plenty of stuff written in ~~the Official /TG/Station Design Doc~~ ddoc.txt, I think this line from the original PR description sums up what I wanted it to be quite nicely:

>A different take on conversion modes and stealthy antagonists with a large dose of espionage. 

Antagonist VS Antagonist was always a core theme and constant element in the design of Assimilation, but with all the changes and mistakes during both design and implementation, this was absolutely botched. Outside of some cryptic warnings in the greeting and the existence of Network Invasion and Mass Assimilation, there was no real indication that it was the case on launch. The overly time consuming Assimilation process, lack of an endgoal outside of objectives and the overbearing presence of Security during most rounds severely hamper the ability and even the desire to play the mode as intended. Almost every single one of the following changes has been made with fixing the issues outlined here:

### The new Network Invasion: Earn your safety

Network Invasion was, and still is the bread and butter of antag-hunting as a Hivemind Host, but now it's become a rather necessary ability for survival and is given to hosts very early into the game (5 vessels). Previously, any Psychic Links lasted two minutes by default regardless of who got it it or why. Now, hivemind hosts start with a minute and a half on their link, but this is incremented by 10 seconds for every successful use of Network Invasion, plus a bonus 30 seconds against any hivemind hosts who had assimilated that vessel. Civilians retain the 2-minute timer after being mindshielded, meaning that Security has the tracking advantage until later on in the round, as do any hosts who start using NI early. A new power, **Reclaim**, also grants a 30 second bonus against everyone but is riskier and requires far more effort to get.

### New Powers, New Options

While I've been hesitant to add new abilities (or doing anything drastic like combining it with traitor) to Assimilation without making the basic gameplay of the mode fun, or at least engaging, these four new added powers (and one removed power) shift up a lot of how the mode is played, especially since the detection mechanics are deeply tied into a couple of them.

**Reclaim: Requires 5 vessels**
Reclaim is a quick-use power that deals massive damage against hivemind hosts, any unconscious hosts take 100 oxygen damage and any hosts in critical condition are instantly gibbed. Reclaim also provides other benefits, for each host gibbed, an extra one-sided 30 seconds is added to the host's psychic links **and** the vessel count is incremented by five. These aren't real vessels but for all effective purposes outside of manipulating people they count.

**Psychoreception: Requires 5 vessels**
Psychoreception is a very simple power, it'll give you the approximate distance of anybody tracking you and anybody you have a tracking bonus against. While not very useful without Network Invasion and on a rather long cooldown for a hivemind power, it can potentially expose an unsuspecting host and help you keep tabs on who's where if you end up with more than one psychic link.

**Chaos Induction: Requires 15 vessels**
Chaos Induction is the mid-game FUN alternative to Mind Control. Four random vessels become antagonists with a single objective (that they must obey akin to brainwash victims), a surefire road to a massive clusterfuck if enough hosts reach it at the same time and a good way to dispatch of someone you don't particularly fancy dealing with personally.
_(Maintainers, please tell me if this is gong to ruin everything combined with the antag size boost because I've got some ideas on how to tone it down that isn't just a flat numbers reduction)_

**Circadian Shift: Requires 20 vessels**
Circadian Shift is the strongest combat power hivemind hosts get and a large middle finger to anybody thinking they can take them on 1v1, sending anybody in sight to sleep, even silicons! The downside is that the more people put to sleep by this power, the less time it lasts. While a crowd will only be put to sleep for eight seconds, an individual or pair caught in the attack will be asleep for almost half a minute. Hivemind hosts (but not mind controlled vessels) are immune to this power, a saving grace for anybody not wanting to instantly die to Circadian into Reclaim. Using this while mind controlling will put you to sleep, not a terribly smart combat move.

image
_(Clockwise, from top: Reclaim, Chaos Induction, Circadian Shift, Psychoreception)_

**Mass Assimilation: Removed**
With an emphasis on early-game antag fights, Reclaim fills the role that Mass Assimilation once did, hence its removal. Mass Assimilation was also a rather bad ability on its own, due to its massive delay before draining, and lack of a real reward due to being gated behind so many vessels.

### The unlock order

The unlock order for hivemind abilities has been changed and divided into five distinct "tiers". Each tier has a distinct theme and all powers in a tier are unlocked at the same amount of vessels. This way, each host has longer to play around with each set of tools, and each set defines an aspect of the hivemind host's playstyle.

**Roundstart powers:** Assimilate Vessel, Release Vessel, Hive Sight, Neural Shock, Distortion Field
**Tier 1 (5 vessels):** Psychoreception, Reclaim, Network Invasion
**Tier 2 (10 vessels):** Repair Protocol, Telekinetic Field, Induce Panic
**Tier 3 (15 vessels):** Mind Control, Bruteforce, Chaos Induction
**Tier 4 (20 vessels):** Medullary Failure, Circadian Shift

The biggest change is to the roundstart power selection, Distortion Field is a roundstart ability, one that deals 70 stamina damage (factoring in regen) to anybody caught in a screenwide AOE, which should give hosts some oomph from the get-go while not frontloading their combat prowess. The utility powers being the only extra thing unlocked until 10 vessels is extra incentive to start using them for the genuinely useful rewards and making for a more interesting early game other than "assim, wait 30 seconds, repeat until mind control".

### Old powers and quality of life

More minor changes have happened to old abilities, mostly.

Assimilate now has an insignificant cooldown at 5 seconds. This is to mostly eliminate the grind of waiting 30 seconds between assimilations at roundstart when you really need to get at least a few powers.
Bruteforce now immobilizes for 5 seconds after assimilation and can be toggled at will, instead of lasting for 30 seconds after activation. This way feels far less janky to use and the downside makes it not free to use at any time.
Hive Sight also lets you hear. Convenient.
Distortion field no longer hits your body if you use it under mind control, as well as being more useful at lower hive sizes.
Induce Panic is more reliable by no longer having an RNG chance to fail (reduced by hive size) VS mindshields, as well as dealing guaranteed stamina damage. Hivemind hosts only take the stamina damage and jitteriness.

### Gamemode changes

All objectives except for 'escape' and those concerning having a certain hive size have been removed, mostly due to being frustratingly difficult or far too easy to complete due to them being at complete odds with the mechanics of the mode.

The max amount of antagonists has been increased to 8 at 64 players (with a 50% chance of extra), this may be decreased if deemed excessive.

### One Mind: Ascension

(This section may be fleshed out in a future PR)

Once a hivemind host has a lead of at least 20 vessels against every other host (Reclaim vessels count only for the 'lead candidate' here) and has at least 15 vessels (Reclaim vessels don't count here), they unlock the **One Mind** ability. On use, a global sound plays as their vessels drop unconscious and spasm. Fifteen seconds later, ~~the nuke goes off~~ ~~Narsie is summoned~~ ~~the shadowling ascends~~ ~~Ratvar is summoned~~ their vessels wake up as part of the One Mind and get glowy pink head auras. While vessels have no powers as members of the One Mind(besides the ability to communicate telepathically), they must obey their host. A horde of 30 people is dangerous, regardless of how weak they are. The host also gains a bunch of immunities, mostly to environmental effects and stuns.

The sound's licensing info is in license.txt

### Code changes

Hives, and all the code that uses them, have been refactored to store their members as **minds** instead of **living mobs** so that the whole thing makes more sense and is less of a nightmare to update. This should fix some weird edge cases and some (unreported) bugs. A few new helper procs have been added, and others have been given more sensible parents.

## Why It's Good For The Game

I wish I hadn't used "The PR that fixed Assimilation" as a title for the previous large Assim PR, because that just unfucked the awful sec/antag balance that made the mode literally unplayable. This is an earnest attempt to fix the shaky foundation and turn a lackluster mode into what it should've been from the start: a breezy antag vs antag psychic detective caper featuring xcom memes.

## Changelog
:cl: Kierany9
add: Assmilation has received a major update!
remove: Kill, Maroon and Protect objectives have been removed from the mode.
tweak: Powers have been reorganized and are now unlocked in batches every five vessels. This gives hosts more power from the get-go and gives them distinct phases due to each batch affecting a specific area of the host's ability.
tweak: The psychic link pinpointer now starts off with very little time for hosts and must be strengthened by using Network Invasion. Each time a host is detected via NI, they can be tracked for an extra 30 seconds, and every successful use of NI increases the duration of all tracking by 10 seconds. A successful use of a new power, Reclaim, also increases the duration of all tracking by 30 seconds.
tweak: This means that without generous use of Network Invasion and Reclaim, hivemind hosts will lose their radar before Security does.
add: Four new powers have been added!
add: Reclaim is an early-game ability that instantly kills critically injured hosts that are adjacent, and reduces all power requirements by five vessels for each host reclaimed, instantly unlocking your next set of powers.
add: Psychoreception is an early-game ability that gives you the approximate distance of anybody currently tracking you and any hosts you've previously detected via Network Invasion.
add: Chaos Induction is a mid-game power with a single use that turns four random vessels into antagonists with a single, customizable objective.
add: Circadian Shift is a late-game power that sends everybody in sight to sleep for up to almost a minute. The more people affected, the less time it lasts, the minimum being eight seconds.
remove: Mass Assimilation has been removed as Reclaim now fills its role.
tweak: Assimilate Vessel and Release Vessel's cooldown have been reduced to 5 seconds to reduce waiting time between assimilation attempts.
tweak: Bruteforce is no longer temporary, but immobilizes the user for five seconds after assimilation.
tweak: Hive Sight also lets you hear what the vessel does.
tweak: The antag limit has been upped from 6 to 9
code: A lot of internal changes to how Assimilation works. In summary, Assimilation now affects the mind instead of the mob, meaning that players will stay assimilated in a few more scenarios, most notably after death.
balance: Induce Panic and Distortion Field have been buffed to be more reliable, especially at lower hive sizes.
balance: Induce Panic and Circadian Shift can affect silicons but no longer affect hivemind hosts.
experimental: A new endgame has been added. The One Mind that survives this ordeal will show the world the true terror of the word Hivemind.
/:cl:

### CODE REVIEW

**Comment by subject217** [comment]
did the airlock spacing change not make it in, in the end?

**Comment by Kierany9** [comment]
yeah shit lemme update the description

Mind Control now ejects you if you move the vessel more than 14 tiles away from the initial point of control.

**Comment by subject217** [comment]
i believe that is what those in the industry call an epic gamer victory

**Comment by Borisvanmemes** [comment]
Making mind control stop if you get cold/hot still sounds like such a good idea though.

**Comment by Shadowflame909** [comment]
Ok, this is epic.

**Comment by Kierany9** [comment]
>Edit: I hope the One Mind, during ascension. Gets a nice loudspeaker like telepathy to speak to all their hosts, in case they're far away.

Everybody gets telepathy.

Only one guy gets
# **big telepathy.**

**Comment by dr-bee** [comment]
Kind of an unrelated flavor suggestion, but how about instead of just gibbing the crit, reclaim blows their brains up, leaving a brainless corpse. It would both be cooler, more ominous, and still allow some form of revival via botany.

**Comment by ATH1909** [comment]
> Kind of an unrelated flavor suggestion, but how about instead of just gibbing the crit, reclaim blows their brains up, leaving a brainless corpse. It would both be cooler, more ominous, and still allow some form of revival via botany.

This might lead to hiveminds teaming up and willingly "farming" each other, though. Dunno if that's a good or a bad thing.

I personally much prefer the "being too hot/cold snaps you out of mind control" idea over the "moving the victim too far away snaps them out of mind control" idea thematically, although I guess the former "solution" still doesn't solve the problem of space walkies (as you can just strip your target before walking them out of an airlock).

While you're messing with mind control, could you fix the bug that makes hivemind hosts with less than ten hivemind members have a mind control power that's as strong as that of a hivemind host with over 24 hivemind members?

Maybe you could add a changeling-style hivemind host-only telepathy channel so that hivemind hosts can (anonymously, as "Mr. Phi" and the like) set some ground rules for each other and/or arrange deals with each other ("if you leave me Engineering and Botany, I'll let you have Medbay", "don't brute force sec officers yet; you'll get us all caught", etc.). It's really annoying to have your hivemind host round ruined by one brainlet hivemind host that decides to start using very flashy, round type-revealing powers 5-10 minutes into the round, causing sec to panic and order 5 mindshield crates from cargo.

**Comment by ATH1909** [comment]
Will hivemind powers be made less janky to use (i.e. NOT "scroll through a list of your entire hivemind to find the name of the assistant that's beating you to death")? It looks like you've got a swanky new radial menu in the screenshot that you posted.

Could you add a HUD for hivemind hosts that lets them know who is and isn't in their hivemind at a glance?

**Comment by wesoda25** [comment]
There should be some sort of on screen border for mind control to show where you lose control of the victim. Also, does teleportation affect this at all?

**Comment by necromanceranne** [comment]
In the off chance two hiveminds reach One Mind, what differentiates one group of hiveminds to another?

**Comment by davethwave** [comment]
You can't have have 2 One Mind hiveminds, by unlocking it you have to have 20 more hosts that other people so it's impossible to have more than one hivemind with that power.

**Comment by Kierany9** [comment]
Two people can technically get the ability, but using One Mind disables it for everybody else.

**Comment by necromanceranne** [comment]
Coolio, that was basically my only concern and it was almost certainly going to be edge case only.

**Comment by ExcessiveUseOfCobblestone** [comment]
tfw have global procs that are based around a mob argument instead of just having a mob proc

**Comment by Kierany9** [comment]
All the "is he an antag" procs are like that (`iscultist`, `iswizard`, `is_servant_of_ratvar`, plus any I'm forgetting) and I have no clue why.

**Comment by ExcessiveUseOfCobblestone** [comment]
cringe

**Pull request merged**
