### PR TITLE
Tweaks Ice Box security desk

### PR DESCRIPTION
**Pull request by msgerbs**
## About The Pull Request

Adds vents, a camera monitor, and a security officer spawn to the security desk on Ice Box. Also corrects the description of the door buttons to not say they operate the medbay doors.
image

## Why It's Good For The Game

The security desk on Ice Box is underused, which is a shame because it's basically the only way for somebody to talk to sec that isn't over the radio or yelling at an officer as they run by. I hope that adding a spawn here may have a tiny chance of making sec realize this place exists. I added vents because enclosed areas with no vents are silly especially if we expect people to spend time there. And I fixed the description on those buttons because that was an obvious oversight from a copypasta.

## Changelog
:cl: VexingRaven
add: Ventilation and a security monitor have been added to the Ice Box Station security desk
add: A security officer may now spawn at the security desk on Ice Box Station.
spellcheck: Fixed the description of the door controls at the Ice Box Station security desk.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
adding a spawn doesnt mean people will stand still in there

**Comment by msgerbs** [comment]
Obviously, but it doesn't hurt and it's a nice bit of additional flavor having them not all just spawn in a row in the office.

**Comment by anconfuzedrock** [comment]
add a camera monitor to the wall and people will have reason to sit in it more

**Comment by msgerbs** [comment]
> 
> 
> add a camera monitor to the wall and people will have reason to sit in it more
> spawning in a row is nice cuz hos can yell at them roundstart

Good idea. Not convinced that having them spawn there is bad though, the HOS has his radio if he wants to yell at them which is arguably more visible anyway unless he grabs his megaphone. It's not like they will always spawn here, there's still like 12 spawns in the sec office.

**Comment by msgerbs** [comment]
Added a camera monitor to the room. I know you were thinking on the wall, but I'd have to move the buttons and have it be really clutered, and I think this actually looks alright ingame: 
image

**Pull request merged**
