### PR TITLE
book resprite

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

this pr resprites all books, including bibles and the cult tome
sprites by meyhazah
screenshots:
image
image
image
image

## Why It's Good For The Game

they really show their age and could use an update

## Changelog

:cl: MeyHaZah
imageadd: Resprites for every book
/:cl:

### CODE REVIEW

**Comment by Thunder12345** [comment]
Where are the screenshots Fikou, where are the screeeenshooooots

**Comment by Fikou** [comment]
> Where are the screenshots Fikou, where are the screeeenshooooots

https://github.com/tgstation/tgstation/pull/65341/checks?check_run_id=5468293408

**Comment by Thunder12345** [comment]
What's this, a screenshot for ants?

**Comment by Mey-Ha-Zah** [comment]
I just used the Eldritch Codex as a base book, the colors yeah some of them can be improved, but I spent a full day working and I'm tired. I was planning on adding open versions, but thats going to have to wait.

**Comment by Mosslick** [comment]
Why is the insul one just flipping you off

**Comment by Mey-Ha-Zah** [comment]
Its the 'insul't bible

**Comment by CRITAWAKETS** [comment]
I'd suggest making the books bigger, it'll allow getting more detail and such on the sprites.

**Comment by Fikou** [comment]
> What's this, a screenshot for ants?

image

**Comment by Twaticus** [comment]
> > What's this, a screenshot for ants?
> 
> image

add ingame screenshots to the pr

**Comment by Serxule** [comment]
they are wayyyy too small, definite no

**Comment by Serxule** [comment]
adding onto that, some of the books are direct downgrades in sprite quality, also why 3/4? the books should be flat, you dont stand up a book on a table

**Comment by Serxule** [comment]
notible mentions of the downgrades: 
Screenshot_2015
Screenshot_2014
Screenshot_2013
Screenshot_2012
Screenshot_2011

**Comment by Kurgis** [comment]
> notable mentions of the downgrades:

I find whether or not the necronomicon a "downgrade" debatable, including the tomes. The white bible does need to find a higher contrast, hard when using white + yellow, but you pretty much can't see it right now. The Engineering books look like they were replaced with actual in-game objects rather than depictions of them, and I agree that the stylistic changes weren't the best. The Force wall book lost its magic aka glowy bit, though honestly the old book made me think it had to do something with mirrors whenever I saw it anyways. The cooked_book has a place in the server's meme culture the author likely wasn't aware of, I've heard of some tiny-type scripts designed specifically for extremely low res pixel art games, perhaps that can be a solution.

**Comment by Farquaar** [comment]
I'm afraid I don't really like this "petite" style of book. You can't judge a book by its cover, but there is a LOT less room for interesting covers when the sprites have been shrunk so much. Serxule's chosen examples really highlight this issue.

**Comment by Wallemations** [comment]
> some of the books are direct downgrades in quality and detail, also why 3/4? the books should be flat, you dont stand up a book on a table

3/4ths isn't the problem, it's the choice to not use the face of the book as the top, instead using the pages.
If it were the bottom it would look flat.

Also, while I'm not a fan of calling them downgrades, I will agree that the smaller size of the book is not very desirable. 

Again, I like the sprites _generally,_ I like that they're 3/4ths, and I like their colors. Those two things stated before are what really put me off the PR though.

**Comment by Dorsisdwarf** [comment]
> I'm afraid I don't really like this "petite" style of book. You can't judge a book by its cover, but there is a LOT less room for interesting covers when the sprites have been shrunk so much. Serxule's chosen examples really highlight this issue.
> 
> Also, a pet peeve of mine: "they really show their age" doesn't convey any insight into the reasoning behind this resprite. _Why_ don't you like the old sprites? Are they too big? Is the detail too distracting? What makes these new sprites better than the old other than "they're new"?

Honestly I prefer these new smaller sprites. Books are massive table and locker space hogs at the moment, and nobody ever looks at the chaplains custom bible because its always in his pocket for instant application anyway

**Comment by Farquaar** [comment]
> 
> Honestly I prefer these new smaller sprites. Books are massive table and locker space hogs at the moment, and nobody ever looks at the chaplains custom bible because its always in his pocket for instant application anyway

I can't say I agree. Books are a tad big, yes, but no bigger than most of the drink sprites that have been added over the years. Bibles aren't restricted to the chappy, and are often found on tables and can be printed *en masse* in the library.

The major loss incurred by the shrinkage is, to me, the loss of visual information. The current guidebooks (and to an extent the spellbooks) are good at conveying the book's contents without examining. Look at the old engineering guide vs the new- a clearly identifiable spanner has been switched for what looks like a potted cactus. The yellow hardhat has been switched out for a squished, bright orange firefighting helmet. A compact illustration of a forcewall has been switched out for a blue Zelda rupee.

**Comment by Mey-Ha-Zah** [comment]
Well, I decided to listen to feedback and trial a new format for the books. 
image

**Comment by Farquaar** [comment]
> Well, I decided to listen to feedback and trial a new format for the books. image WIP so, give me a little bit to trial and see how things work.
> 
> I'd also like the discuss the issues with books that have been brought up. The engineering books, yes, I changed the art because the original art used in them was a heavy jumble of mixed pixels and I didn't want to re-use those assets. I choose what I thought would be suitable replacements. As I did with a few other books, like the R&D and the Particle accelerator (Don't here any criticisms of those.) If anyone has any solutions I'm all ears. I was just burnt out and didn't want to do any more work then.
> 
> If you have anything to say with me message me on Discord.

For what it's worth, I hope I didn't come off as too harsh in my criticisms. Most of your booksprites are great, and I'm glad you're listening to feedback for the ones that missed the mark.

**Comment by Toastgoats** [comment]
Not bad, but I'd say scale them up a bit.

**Comment by gitbirb** [comment]
why does the mime book look like it's facing a different direction then every other book? (at least in the OP picture, not sure if it was changed)

Asides from that one thing, these changes are great. No book should be twice the size of a spacemans head, even if there is no brain stored in spaceman head. Do the new books have animations or did all the old animations get killed?

**Comment by wesoda25** [comment]
Cool pr fikou ive been enjoying this change 👍

**Pull request merged**
