### PR TITLE
Adds ghost baseball bat.  Also refactors baseball bats slightly.

### PR DESCRIPTION
**Pull request by lordpidey**
## About The Pull Request

Adds a new wizard summonable item, a ghostly baseball bat, that knocks people's ghosts out, who can instantly re-enter their corpse.  Yes, you can knock your own ghost out with this.

The bat can only be effectively used when charged.  It takes 9 seconds to charge, and gains three uses upon charging.  If used uncharged, the victim will re-enter their body in less than a second, automatically.

I chose a cost of two, as it's similar in power to the scrying orb.  It's most useful function will be knocking your own soul out.  However, this has two major balancing factors compared to the scrying orb.  No X-ray vision, and you have to injure yourself to ghost out.  I estimate that those downsides balance out the ability to temporarily ghost other people.

## Why It's Good For The Game

Mildly hilarious wizard ability, it's low cost, unique, and super magical sounding in nature.  Plus, giving wizards more ability to disable people without killing them is a plus.

Also refactors baseball bats slightly, as well as prevents special baseball bat variants from having their names randomly overwritten.

## Changelog
:cl: lordpidey
add: Added a new wizard item, a ghostly baseball bat, that will send people's ghosts flying.
fix: special baseball bat varieties will no longer have their name randomly overwritten.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Wowwwwwwww so greatful for this PR, we are so bare of wizard content that honestly it just needs so much more stuff added, it's not at all an unbalanced antag who is being complained about actively in policy, so I sure am glad we're working hard on adding more things to it. Haha imagine if it was busted and we would have to be looking at fixing it or anything.

Sure am glad that isn't the case

**Comment by lordpidey** [comment]
That was my exact reasoning for giving wizards some LESS LETHAL options.

Murderbone wizards are aggravating for the unrobust.

Giving wizards more combat options that don't take the target out of the round is a GOOD thing.

**Comment by optimumtact** [comment]
In the same way that building a ladder out of dead bodies might eventually work, yes, you might eventually be able to fix wizard by simply adding more spells

**Comment by lordpidey** [comment]
I never claimed this was a panacea that will fix all of the problems with wizard.

It's just a small improvement.

And when we DO decide to buckle down and fix wizard, the more options wizards have that we don't need to remove, the better the end result will be.

**Comment by Zytolg** [comment]
This shouldn't be in the "Defensive" spell list. Utility is a better fit, or straight up Offensive. This may not be an object that immediately kills the defending party, however removing their "ghost" and therefore the mobs mind renders the defender unable to react to however the attacker decides to follow up with this. Immediate isn't immediate and 1-2 seconds makes all the difference in any combat situation.

On another note, this is a really powerful tool considering the scope of the game. This is free access to D-Chat, which by itself is an extraordinarily powerful "20 questions answered free, the traitor is he" utility in the hands of the crew. If that isn't enough, this the ability to ghost wherever, whoever, and whenever you want, and at a low cost too. I honestly think this would be better balanced if the homerun charges were spent per knocking out a ghost, at a high chance, as opposed to all the time any time. Add some niche and cool little interaction for when things aren't a home run.

Overall it's a neat idea, but I don't think it's a good fit as-is.

**Comment by lordpidey** [comment]
> This shouldn't be in the "Defensive" spell list. Utility is a better fit, or straight up Offensive. 

Okay, I'll put it under Utility.

> This is free access to D-Chat, which by itself is an extraordinarily powerful "20 questions answered free, the traitor is he" utility in the hands of the crew.

Yes, but scrying orb already gives this, AND xray vision without needing to injure yourself, also costing 2 points.


> I honestly think this would be better balanced if the homerun charges were spent per knocking out a ghost, at a high chance, as opposed to all the time any time. Add some niche and cool little interaction for when things aren't a home run.

That's actually a really good idea.

**Comment by lordpidey** [comment]
> Okay, I'll put it under Utility.

Turns out Utility isn't a type.

**Comment by PKPenguin321** [comment]
When I added home run functionality there was a bug pointed out after it was merged that let you spam charge startups then use homeruns while the doafters were still ticking down to have functionally unlimited home runs as long as you stood still, not sure if that was ever fixed

**Comment by Rohesie** [comment]
I really dislike this item and the OOC/IC blurring consequences it brings, even more when it falls into the hands of the crew.
Reminding that on dynamic the wizard is just one of the many possible simultaneous antags.

I'm closing this PR. Find a maintainer really interested in it before reopening it.

**Pull request closed without merging**
