### PR TITLE
Increase BYOS cost to 5000 and make it slightly bigger

### PR DESCRIPTION
**Pull request by WJohn**
## About The Pull Request

What it says on the tin. Shuttle is a little big larger, cost has been increased from -2500$ to +2500$.

## Why It's Good For The Game

Allegedly this shuttle is getting bought too much and there's not really any downside to it, so cost increase it is.

## WJohnston
:cl:
balance: BYOS cost increased from -2500$ to +2500$, and made a bit larger.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
>Bigger

>It never gets fully built

I dont think thats needed my friend. A price increase is just fine

**Comment by ishitbyabullet** [comment]
it's the BYO shuttle, not the "guys i made oh hi daniel but with a front lawn" shuttle.

It's fine if it is bigger or as big as it once was imo.

**Comment by Shadowflame909** [comment]
Well now thinking, I'm pretty sure you can only buy this shuttle in the first 10 minutes.

If cargo is A shit and starts spending money, then this shuttle will rarely be seen.

**Comment by zxaber** [comment]
Moving it to zero cost would probably be fine. It's still better than the default shuttle (no ability to emag), but at least there's no direct benefit from it.

I would still love to see the old DIY shuttle back, since that one was fun.

**Comment by bigfatbananacyclops** [comment]
I like that it’s a bigger size because i can make more stuff in the ship, i tried to make a starwars looking fighter once but it was so small and it got messed up by meteors at one point, don’t see the reason for the price raise, but i would be okay with a bigger size, it’s fun to build a shuttle with it and the creativity it allows entertains.

**Comment by ArcaneMusic** [comment]
> 
> 
> Moving it to zero cost would probably be fine. It's still better than the default shuttle (no ability to emag), but at least there's no direct benefit from it.

The thing is, free shuttles will always tend to get bought. The last 2 big "issue" shuttles (Meteor, Daniel) both were in a way free, because anyone can break into the captain's office or bridge with all access, one way or another, and buy it INSTANTLY. Now, the argument can be made that that's less likely with this shuttle as it's time locked, but I think there should be SOME cost to BYOS. Not 5000 credits, but small. 500, 1000 credits.


Either way, the price can always be lowered if nobody buys it anymore.

**Comment by necromanceranne** [comment]
It's been fun to see this shuttle get brought with the more recent changes and seeing the creative shit come out of it. It is actually a pretty fantastic space for build projects and even comes with materials to make that easier.

**Comment by wesoda25** [comment]
The point of BYOS is that it gives you money to purchase mats to build it with.

**Comment by zxaber** [comment]
Yeah, but the new DIY needs literally no work done to be survivable. So you can just buy it for the money and ignore it until you leave.

The old one required walls and someone had to fill it with atmos.

**Comment by wesoda25** [comment]
Then limit BYOS to announced extended or something (do this for gateway too). Making something cost money that would make 0 sense icly to cost money is shitty and I hate how its becoming the meta for discouraging shuttle purchases. Use some fucking imagination instead of going “teehee this cost money big! You buy less??”

**Comment by wesoda25** [comment]
Default Shuttle: walls, atmos, lights, functioning cockpit, brig, and cockpit (at the very least), floors, chairs, doors. 

BYOS: walls atmos 

BYOS costs more?????

**Comment by WJohn** [comment]
Announced extended isn't part of the rotation, unfortunately, so this shuttle would become unseen as a direct result.

**Comment by zxaber** [comment]
It's why I said it would be fine as a flat-zero purchase.

The main reason this shuttle is currently unbalanced is that it gives you cash basically for free, since the shuttle doesn't require any work to be usable (sure, it can be vented by an antag, but the cap's got a hardsuit). There's no expectation that the captain needs to rally the crew into setting the ship up. It's good to go and if someone explodes half of it mid-way through the shift, then that's just unfortunate.

It's not really a grief shuttle like the meteor was made out to be (or Daniel was), so it's not the same reason that we're raising the cost. It's just got zero downsides for the money it gives; Having it be a flat zero would balance out.

**Comment by wesoda25** [comment]
Unless announced extended was disabled at some point in the last two days I think you are wrong chief

**Comment by Tlaltecuhtli** [comment]
weed

**Comment by CPTANT** [comment]
Removing the "Build the actual shuttle" aspect from the BYOS shuttle was dumb.

**Comment by optimumtact** [comment]
:rage1:

**Comment by Dennok** [comment]
Please just make several different BYO shuttles of different sizes and prices.

**Comment by wesoda25** [comment]
I’d like small/medium/large versions of BYOS, giving more credits the higher you go (or supplying more mats the higher they go).

**Comment by Dennok** [comment]
And add ability to sell it back for the credits.

**Review by SpaceManiac — APPROVED** [review]

**Comment by CPTANT** [comment]
Actual build your own shuttle back when?

**Comment by dee-dubya** [comment]
This shuttle wasn't a grief pick, and quite a few people actually enjoyed putting it together. Another fantastic case of coders never actually playing the game and ruining a fun aspect of it for the people who do.

At least set the price to a flat 0 instead of giving it a cost or boon at all, so that there's actually a realistic chance that it'll get purchased, without giving an advantage to the station if it is.

**Comment by optimumtact** [comment]
you're too late

**Comment by Dennok** [comment]
No one forbid you make your pr, and set price to 0

**Comment by dee-dubya** [comment]
Way ahead of you, just had browser troubles. Everyone always says "if you want to see a change, just make a PR", so fuck it, why not?

**Comment by wesoda25** [comment]
Can’t believe this was merged

**Pull request merged**
