### PR TITLE
Makes a hotkey for asay

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
add: New hotkey for admin say command: F3.
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
F4 deadsay please

**Comment by ExcessiveUseOfCobblestone** [comment]
Personally I would prefer :ds and :as prefixes in say if it's possible.

**Comment by Cyberboss** [comment]
its a stupid code issue that we can't actually use radio keys for ghost admins to trigger this so this is a temporary solution

**Comment by ExcessiveUseOfCobblestone** [comment]
what about languages? Could you hijack that system for dsay asay?

**Comment by Cyberboss** [comment]
nah, that's lower in the stack

**Comment by ExcessiveUseOfCobblestone** [comment]
dang

**Comment by MoreRobustThanYou** [comment]
@Cyberboss use saymode datums

**Comment by Cyberboss** [comment]
If you actually read that code you'd understand why it would work for ghosts

**Pull request merged**
