### PR TITLE
Giving the monkeys their tails back

### LINKED ISSUE #76539: Monkeys do NOT have tails.
## Round ID: 
Any but tested in 209608 and the next two.

## Testmerges:
None from what I can see

## Reproduction:
No matter what, monkeys have no tail and this sucks for heretics and such.
1. Gib a monkey
2. No tail will drop no matter what you do

1. Do feature manipulation on a monkey's groin.
2. There are no removable organs.

### PR DESCRIPTION
**Pull request by notlulz**
## About The Pull Request
Proc `should_external_organ_apply_to` skips all "None" features so i changed monkey tail feature to "Monkey" and monkeys now have tails. Heretics should be happy :)

## Why It's Good For The Game
Fixes #76539

## Changelog
:cl:
fix: Monkeys have their tails back.
/:cl:

### CODE REVIEW

**Review by Fikou — CHANGES_REQUESTED** [review]
Your changelog doesn't actually explain anything to a player reading it

**Comment by notlulz** [comment]
> Your changelog doesn't actually explain anything to a player reading it

I don't know what else to put, it's just a small typo.

**Comment by Fikou** [comment]
> > Your changelog doesn't actually explain anything to a player reading it
> 
> I don't know what else to put, it's just a small typo.

Changelogs are meant for players, they should inform the players of changes that happened to the game
Like "Monkeys have their tails back" explains infinitely more than "Fixes a typo"

**Comment by notlulz** [comment]
> > > Your changelog doesn't actually explain anything to a player reading it
> > 
> > 
> > I don't know what else to put, it's just a small typo.
> 
> Changelogs are meant for players, they should inform the players of changes that happened to the game Like "Monkeys have their tails back" explains infinitely more than "Fixes a typo"

Okay, is everything good now?

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
