### PR TITLE
[CANCELED] You will no longer attack or wake operated patient

### PR DESCRIPTION
**Pull request by Mysak0CZ**
If you are operating and use wrong tool or empty hand, you will now not attack or wake patient

:cl:
tweak: You will no longer attack or wake operated patient
/:cl:

Tested on local server

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:-1:

**Comment by lzimann** [comment]
should just add to sugery tools and not for all items, for all items is just plain hugbox...

**Comment by Mysak0CZ** [comment]
I just wrote this to prevent any harm while trying to help

**Comment by MrPerson** [comment]
Since this will annoy players, what's the goal here?

**Comment by Mysak0CZ** [comment]
how cloud not destroying something annoy players?

**Comment by WJohn** [comment]
If you have something like fireaxe in your hand, there is no situation in which clicking someone is accidental. Help intent would prevent you from doing something you intended to do, and that'd be pretty awful to have everybody constantly on disarm/harm intent so they can attack eachother. 

The occasional accidental hit is preferable to the constant inability to intentionally hit.

**Comment by Mysak0CZ** [comment]
OK, i am redoing this for tools

**Comment by Shadowlight213** [comment]
:-1: :x: :100:
Extreme hugbox. The fire extinguisher change was bad enough anyways. Does "aiming" with the extinguisher even do anything useful? I've ended up dying like at least 3 or 4 times because I tried to bash someone's head in with an extinguisher, but ended up just stupidly pointing at them since I was on help intent.

**Comment by Mysak0CZ** [comment]
Ok, you was right, i reverted original edits.
I added, that during surgery you will (with help intent) not attack operated patient and you will not wake him with hand

**Comment by WJohn** [comment]
That's better, then.

**Comment by ExcessiveUseOfCobblestone** [comment]
bit too hugbox for my tastes

**Comment by Bawhoppen** [comment]
H U G  C R E E P

**Comment by Mysak0CZ** [comment]
3 yes, 8 no.
There is nothing more to talk about

**Comment by Bawhoppen** [comment]
You realise you don't have to be democratic right

**Comment by Mysak0CZ** [comment]
yes, but why make a change that will most players hate?

**Comment by PKPenguin321** [comment]
I like this guy

**Pull request closed without merging**
