### PR TITLE
Fix colorful reagent, red powder, and hair dye breaking metabolization

### LINKED ISSUE #52289: Colorful Reagent causing complete inability to process chems
Not sure if this is intended or a bug, but it seemed worth noting. On the last two sessions I've played, I made colorful reagent smoke grenades for fun and tossed them. Anyone who ended up inhaling colorful reagent from said grenades became completely incapable of processing chemicals in any way, even after replacing the organs in question, attempting to purge chems, using nanites...Any solution we came up with didn't work at all. The chemicals are in their body, but they never process or have any affect. We were forced to transfer the victims' brains into another body entirely. (As a humorous side-effect of this, chicken nuggets made from the bodies of people affected in this way still have the chems in them.)

We thought this was a fluke the first time it happened, but it's happening consistently now, so I decided it would be worth reporting as a bug. (Worth noting this happened on Campbell.)

image

~~UPDATE: We just discovered that quantum hairdye also fixes this, for some reason.~~
~~UPDATE: Quantum hairdye does _not_ fix this issue- it seems to purge the colorful reagent, but it itself proceeds to get stuck in the body.~~
UPDATE: Complete bloodpurge using nanites seems to work.

### LINKED ISSUE #52333: metabolise addiction runtiming a few thousand times a round
runtiming a couple thousand times a round

```
[xx:xx:xxx] Runtime in holder.dm, line 384: Cannot create objects of type null.
 proc name: metabolize (/datum/reagents/proc/metabolize)
src: /datum/reagents (/datum/reagents)
call stack:
/datum/reagents (/datum/reagents): metabolize(xxxxxxx (/mob/living/carbon/human), 1, 0)
the liver (/obj/item/organ/liver): on life()
Kel Thuzad (/mob/living/carbon/human): handle organs()
Kel Thuzad (/mob/living/carbon/human): Life(2, 1662)
Kel Thuzad (/mob/living/carbon/human): Life(2, 1662)
Mobs (/datum/controller/subsystem/mobs): fire(1)
Mobs (/datum/controller/subsystem/mobs): ignite(1)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

https://github.com/tgstation/tgstation/blob/0f9f74061fa896b819b05944d5fe6139b609f68f/code/modules/reagents/chemistry/holder.dm#L350-L390

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Fixes #52333. Fixes #52289.

## Changelog
:cl:
fix: Fixed colorful reagent, red powder, and quantum hair dye breaking metabolization.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
I'm not sure why `addiction_type` exists in the first place. It's set to itself on `New()` if it doesn't exist, and the only thing that seems to set it is `/datum/reagent/drug/maint` which sets it to...itself. @EdgeLordExe, git blame suggests you're the one that added this in, anything I'm missing or can I just remove this entirely?

**Comment by Angustmeta** [comment]
The regenerative jelly and polypyr medicines color hair as well. Don't know if those need fixing too or not.

**Comment by Jared-Fogle** [comment]
It's not coloring hair that's the problem, it's the `New` proc not being called. The `SHOULD_CALL_PARENT(TRUE)` line snuffed out any reagents that had the same bug.

**Comment by ExcessiveUseOfCobblestone** [comment]
do we really need a unit test for color reagent?

**Comment by Jared-Fogle** [comment]
I admit it does look silly, but regression tests like these are common elsewhere. The reasoning behind it is not that I expect colorful reagent to break sometime in the future, but that the code down the line relating to metabolization and such elsewhere could. It could become a more general test for metabolizing all chemicals, but that's the purpose it serves right now.

**Comment by ExcessiveUseOfCobblestone** [comment]
when someone wants to implement generic they can, this is currently not needed though.

**Comment by RaveRadbury** [comment]
I think this is also applying to crayons, as I had a round where munching on the mime crayon broke hunger.

**Comment by AnturK** [comment]
Test was fine, we don't tear down env so they're fast enough.

**Comment by Jared-Fogle** [comment]
Yeah, I'd like a more solid assessment on tests. Regression testing is common, it just admittedly looks a little silly for cases like this.

**Pull request merged**
