### PR TITLE
Orbit menu checks ghosts recursively, ghosts have orbit counters

### PR DESCRIPTION
**Pull request by MrDoomBringer**
## About The Pull Request
The orbit-counter of the orbit menu only showed the number of ghosts directly orbiting someone. That means if 100 ghosts were orbiting me, and I was orbiting a living player, the orbit menu would only show that 1 person is orbiting that player.

Secondly, the orbit menu now displays the number of people orbiting a ghost. This is because sometimes everyone is orbiting a single observer, who in turn is following all the action or whatever. This makes it easier to figure out who that is

## Why It's Good For The Game
Makes the orbit menu more clear and usable

## Changelog
:cl:
add: The orbit menu now shows the total number of ghosts orbiting something
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Does this affect the spectral blade at all?

**Comment by MrDoomBringer** [comment]
@ATH1909 Nope, though I took a glance at that code earlier. Would it benefit from this?

**Comment by optimumtact** [comment]
this count is not worth the cost

**Comment by MrDoomBringer** [comment]
@optimumtact It only calls once when the orbit menu is opened. Shouldn't be that much less performant overall than our current implementation as long as it's not called every UI tick

**Comment by MrDoomBringer** [comment]
I can make a note on the proc's documention not to call it frequently if you'd like

**Comment by optimumtact** [comment]
benny harvey, RIP
took the bus to Yoker and never returned. Miss ye big man
<https://youtu.be/WY2r28M1TrY>

**Comment by MrDoomBringer** [comment]
talked with oranges and confirmed that this means the PR is probably fine

**Comment by stylemistake** [comment]
```
code/modules/mob/dead/observer/orbit.dm, line 58, column 50:
warning: field access requires static type: "len"
- code/game/atoms.dm:1565:28: add a return type annotation to /atom/proc/get_all_orbiters
```

**Comment by MrDoomBringer** [comment]
lol i'm dumb

**Pull request merged**
