### PR TITLE
Removes bananium from recycler, adds bananium to asteroid.

### PR DESCRIPTION
**Pull request by Firecage**
This removes Bananium from the recycler, since honestly, it was just ridiculous.

This adds Bananium to be mineable on the asteroid. On the low yield ones, it's as rare as diamonds, aka basically impossible to find. On the high yield ones, it is 6 times rarer than daimonds.

As a minor note, this adds a scan state to the Bananium ore deposits, and also makes them hidden.

### CODE REVIEW

**Comment by Core0verload** [comment]
Reduce the prob to bluespace crystal or diamond levels.

**Comment by Firecage** [comment]
Why exactly core?

**Comment by Core0verload** [comment]
Because bananium must be fucking rare. It's joke material after all.

**Comment by bgobandit** [comment]
A+ for removing bananium from crusher

but this is way way WAY too common for asteroid

**Comment by Firecage** [comment]
bgo. You don't understand. I tested this on the asteroid myself by mining and using a scanner before making the PR. It is quite hard to get, and since it doesn't spread, and only gives 3 ores per deposit. Yah.

Unless you ofcourse mean something else and I just can't understand the meaning.

**Comment by Firecage** [comment]
And Core...that...isn't what I asked. I asked why should I reduce the chances for diamonds and bluespace crystals. Your answer wasn't even close to what I asked.

**Comment by Core0verload** [comment]
I didn't said anything about reducing diamonds or bs crystals. I said that prob 5 for bananium is way too much.

**Comment by bgobandit** [comment]
he didn't say reduce diamond/bluespace chances, he said make bananananananananium as rare or rarer

**Comment by Firecage** [comment]
.....You guys really didn't read the changed code, did you? And you really don't know how minerals on mining functions, do you?

**Comment by TheWiznard** [comment]
Won't people just get around this by keeping it separated until the ore machine is upgraded? Then they'd get tons of it

**Comment by Firecage** [comment]
Wiznard, it is still better than being able to randomly get it from the crusher. This way they atleast worked for it.

**Comment by TheWiznard** [comment]
I can get that side of it, It won't hurt to at least try the rates you have for a while and if it's too much it's just a simple thing to reduce it. Even if they make tons of it they can't do much without RnD besides doors/walls/floor/statue

**Comment by Firecage** [comment]
Well, the worst thing is honk mechs, but this is actually a reduced amount from the crusher.

**Comment by TheWiznard** [comment]
I agree, I didn't even know the crusher could make bananium, it seems dumb to begin with

**Comment by daman997** [comment]
HOOOOOOOOOOOOOOOOOOOOOOOOOOOONK

**Comment by Lumipharon** [comment]
Just leave it as the crashed honk ship only. It's a joke ore that's used only for a honk mech and airhorns.

**Comment by Miauw62** [comment]
Yeah, dont add it to the asteroid.

**Comment by Firecage** [comment]
There is litterally no reason NOT to add it to the asteroid though. People keep talking about its fluff. Most people don't know about the fluff and don't care about it. And it can be used for walls, floors, etc.

**Comment by Miauw62** [comment]
make it extremely rare then, rarer than diamonds and such.

**Comment by Firecage** [comment]
Miauw, that is EXACTLY what I did. Mining asteroid wise, they are extremely rare. If you had to use a weird logic by which mining turfs work, they are about 6 times rarer than daimonds.

**Comment by SconesC** [comment]
Prob is still too high, Bananium shouldn't be a constant find every round and instead a rare but funny thing

**Comment by Firecage** [comment]
Scones, do you NOT understand....do you people really think that bananium would be common like this? Wow...

**Comment by Kromgar** [comment]
The problem is this now makes diamonds even rare same with bluespace

**Comment by freerealestate** [comment]
> On the low yield ones, it's as rare as diamonds, aka basically impossible to find. On the high yield ones, it is 6 times rarer than daimonds.

so what's the point

1. add thing to game
2. thing is never seen

**Comment by Miauw62** [comment]
theres still bananium on the clown shuttle, which isnt very hard to get to.

**Comment by freerealestate** [comment]
It kind of is though, with randomised z-levels. Even now that they're only
randomised at roundstart.

**Comment by Firecage** [comment]
Free, no it isn't. It is fairly easy now to get there and get back.

**Comment by freerealestate** [comment]
if that's the case why add it to the asteroid then

**Comment by Lumipharon** [comment]
It's bananium. Supposedly native only to the clown world.
Clown shuttle supposedly found the clown world  again, which is why they have bananium.

Also yeah, you can get to the clown shuttle in like, 5 minutes from roundstart, consistantly.

**Comment by Razharas** [comment]
Crusher is fixed
We dont need bananium on asteroid

**Pull request closed without merging**
