### PR TITLE
Sec weaponry tweaks.

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: 
tweak: Security Officers get standard tasers instead of hybrids, and the det gets a disabler.
/:cl:

the det needs a self defense weapon that doesn't do damage, and sec officers never use the disabler mode anyway.

also the hos gets a security medal because i like medals

### CODE REVIEW

**Comment by optimumtact** [comment]
Word of advie: Don't bundle multiple changes together like this, it greatly reduces the chances of any one element of it getting in.

Anyway competent sec will be against this because disablers go through windows and this is then a nerf.

**Comment by Tacolizard** [comment]
@optimumtact are you referring to the medal? and i know this won't be merged

**Comment by optimumtact** [comment]
If you know that then why did you make it?

**Comment by Tacolizard** [comment]
@optimumtact well I want it merged but I know it probably won't. Of course it's a nerf but i think it makes gameplay more interesting.

**Comment by CyberbossJHCB** [comment]
>No one ever uses the disabler
You can't be serious

**Comment by ShadowDeath6** [comment]
>implying disablers

**Comment by GunHog** [comment]
> sec officers never use the disabler mode anyway.

Perhaps you should play as Security before you change their balance! Disablers are a more forgiving weapon - they do not punish you as heavily for missing 1-2 shots, go through windows, and are not as heavily limited. It is important to understand what you are doing to the players to which you are making changes, to the players themselves (Sec in this case), and the players that would gain something from the nerf (Antags and greytide).

**Comment by Bawhoppen** [comment]
Wheres that big fat security change tag that my non-sec related PRs need when you need it

**Comment by optimumtact** [comment]
it's deleted

**Comment by PKPenguin321** [comment]
Honestly if you had done this right around when disabler sec was introduced it would've been good, but at this point the game has been built around disablers for long enough that switching back to tasersec is just a pain in the ass. :-1:

**Comment by TechnoAlchemisto** [comment]
Maybe the detective doesn't need a non-harmful method of arrest because he's not an officer... He's just the ... Detective.

Revolver is cool anyways and works 

Also adv tasers are the tits

**Comment by Cheridan** [comment]
It seems that this is not a desired change at this time, sorry.

**Pull request closed without merging**
