### PR TITLE
Adds terry to brain damage lines

### PR DESCRIPTION
**Pull request by ghost**
BERRY IS DOWN!!! BUGGGG?!

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Iatots** [comment]
... ms sybil?

**Review by optimumtact — APPROVED** [review]
finally a brain damage change that is good

**Comment by ExcessiveUseOfCobblestone** [comment]
🅱️ erry

**Comment by Mark9013100** [comment]
ONE SCARY MUTHAFUCKIN TERRY

**Pull request merged**
